In [1]:
# Parameters
run_date = "2026-02-26"
output_dir = "C:\\datum-api-examples-main\\OriON\\signals"

In [2]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [3]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [4]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [5]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2025-11-25 00:00:00
end   = 2026-02-25 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2025-11-25
end_date_str   = 2026-02-25

In [6]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker       value
0      A    65894.16
1     AA  1596127.54
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 12676

In [7]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,country,exchange,market_cap',
    'active': True,
    'us_exchange': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
tickers_df = tickers_df.dropna()

# --- крок 3: додаємо потрібні колонки у df_filtered
top1500 = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(top1500):,} рядків")
top1500.head()

Після фільтрації залишилось: 6,774 рядків

,ticker,value,lvl3,country,exchange,market_cap
0,A,65894.16,Medical Equipment & Devices,UNITED STATES,New York,35285.0
1,AA,1596127.54,Metals & Mining,UNITED STATES,New York,16806.0
2,AAAU,1072592.05,NaN,NaN,NaN,NaN
3,AACG,12.40,Software,UNITED STATES,NASDAQ CM,31.0
4,AAL,1136930.56,Transportation & Logistics,UNITED STATES,NASDAQ GS,8795.0

In [8]:
top1500[top1500["ticker"] == "JD"]

,ticker,value,lvl3,country,exchange,market_cap
3239,JD,2399531.8,E-Commerce Discretionary,UNITED STATES,NASDAQ GS,37483.0

In [9]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [10]:
unique_lvl2 = get_unique_lvl2(top1500)
unique_lvl2

🔹 Знайдено 58 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [11]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "SPY", "BITO"],
    "Banking": ["KRE", "XLF", "SPY", "BITO"],
    "Institutional Financial Svcs": ["XLF", "SPY", "BITO"],
    "Insurance": ["XLF", "SPY", "BITO"],
    "Specialty Finance": ["XLF", "SPY", "BITO"],

    # --- Tech / Internet / Growth ---
    "Software": ["QQQ", "IWM", "SPY"],
    "IT Services": ["QQQ", "IWM", "SPY"],
    "Semiconductors": ["SOXL", "QQQ", "IWM", "SPY"],
    "Technology Hardware": ["QQQ", "SOXL", "IWM", "SPY"],
    "Internet Media & Services": ["QQQ", "KWEB", "IWM", "SPY"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "IWM", "SPY"],
    "Cable & Satellite": ["QQQ", "KWEB", "IWM", "SPY"],
    "Telecommunications": ["QQQ", "KWEB", "IWM", "SPY"],
    "Publishing & Broadcasting": ["QQQ", "KWEB", "IWM", "SPY"],
    "Entertainment Content": ["QQQ", "KWEB", "IWM", "SPY"],
    "Advertising & Marketing": ["QQQ", "KWEB", "IWM", "SPY"],

    # --- Industrials ---
    "Aerospace & Defense": ["IWM", "SPY", "QQQ"],
    "Diversified Industrials": ["SPY", "IWM"],
    "Industrial Intermediate Prod": ["IWM", "SPY"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["IWM", "SPY"],
    "Machinery": ["IWM", "SPY"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["IWM", "SPY"],
    "Electrical Equipment": ["QQQ", "IWM", "SPY"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XLE", "IWM", "SPY"],
    "Oil & Gas Supply Chain": ["XLE", "IWM", "SPY"],
    "Elec & Gas Marketing & Trading": ["XLE", "IWM", "SPY"],
    "Electric Utilities": ["XLE", "IWM", "SPY"],
    "Gas & Water Utilities": ["XLE", "IWM", "SPY"],
    "Renewable Energy": ["XLE", "IWM", "SPY"],
    "Chemicals": ["XLE", "IWM", "SPY"],
    "Metals & Mining": ["GDX", "IWM", "SPY"],
    "Steel": ["GDX", "IWM", "SPY"],
    "Construction Materials": ["IWM", "SPY"],
    "Forestry, Paper & Wood Products": ["IWM", "SPY"],

    # --- Health Care ---
    "Biotech & Pharma": ["QQQ", "IWM", "SPY"],
    "Medical Equipment & Devices": ["QQQ", "IWM", "SPY"],
    "Health Care Facilities & Svcs": ["QQQ", "IWM", "SPY"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["SPY", "IWM"],
    "Beverages": ["SPY", "IWM"],
    "Household Products": ["SPY", "IWM"],
    "Tobacco & Cannabis": ["SPY", "IWM"],
    "Retail - Consumer Staples": ["SPY", "IWM"],
    "Wholesale - Consumer Staples": ["SPY", "IWM"],

    "Retail - Discretionary": ["SPY", "IWM", "QQQ"],
    "Wholesale - Discretionary": ["SPY", "IWM", "QQQ"],
    "Consumer Services": ["SPY", "IWM"],
    "Leisure Facilities & Services": ["SPY", "IWM"],
    "Leisure Products": ["SPY", "IWM"],
    "Apparel & Textile Products": ["SPY", "IWM", "QQQ"],
    "Automotive": ["SPY", "IWM", "QQQ"],
    "Home & Office Products": ["SPY", "IWM"],
    "Home Construction": ["IWM", "SPY"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [12]:
# ------------------------------------------------

In [13]:
import time
import math
import pandas as pd

def corr_beta_best_match_batched(
    x_tickers,
    y_tickers,
    period="6 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.15,
    max_retries=3,
    output_path=None,          # 🔹 тепер дефолт = None
):
    """
    Викликає /calculations/corr_beta/v2 батчами, об'єднує результати в один DataFrame,
    для кожного X-тікера знаходить Y з максимальною кореляцією.

    Повертає (df_all, df_pairs):
      - df_all   : сирий об'єднаний датафрейм з API
      - df_pairs : мапінг X -> найкращий Y
    """
    # --- валідації ---
    if not x_tickers:
        empty_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
        )
        if output_path:
            empty_pairs.to_csv(output_path, index=False)
        return pd.DataFrame(), empty_pairs

    if not y_tickers:
        raise ValueError("y_tickers не може бути порожнім")

    # --- батчинг (індексний підхід, щоб не губити/дублювати X) ---
    y_str = ",".join(map(str, y_tickers))
    results = []
    i = 0
    n = len(x_tickers)
    bs = max(1, int(batch_size))

    while i < n:
        xs = list(map(str, x_tickers[i : i + bs]))
        x_str = ",".join(xs)

        params = {
            "x_tickers": x_str,
            "y_tickers": y_str,
            "period": period,
            "as_pivot": as_pivot,
            "format": fmt,
        }

        attempt = 0
        while True:
            try:
                df_chunk = DatumApi.data_request("/calculations/corr_beta/v2", params)

                # підстраховка типів
                if df_chunk is None:
                    fetched_ok = False
                elif isinstance(df_chunk, pd.DataFrame):
                    fetched_ok = not df_chunk.empty
                else:
                    df_chunk = pd.DataFrame(df_chunk)
                    fetched_ok = not df_chunk.empty

                if fetched_ok:
                    results.append(df_chunk)

                i += len(xs)
                print(f"[{i}/{n}] fetched batch of {len(xs)} X тикерів")
                time.sleep(pause)
                break

            except Exception as e:
                msg = str(e).lower()
                attempt += 1

                if "414" in msg or "uri too large" in msg or "request-uri too large" in msg:
                    new_bs = max(1, bs // 2)
                    if new_bs == bs:
                        if attempt >= max_retries:
                            print(
                                f"⚠️  Пропускаю {len(xs)} X-тикерів (i={i}) "
                                f"після {max_retries} 414-помилок. Помилка: {e}"
                            )
                            i += len(xs)
                            break
                    else:
                        print(
                            f"⚠️  414 на i={i}. Зменшую batch_size {bs} → {new_bs} "
                            f"і формую партію заново."
                        )
                        bs = new_bs
                        break
                else:
                    if attempt >= max_retries:
                        print(
                            f"⚠️  Пропускаю {len(xs)} X-тикерів (i={i}) "
                            f"після {max_retries} спроб. Помилка: {e}"
                        )
                        i += len(xs)
                        break
                    time.sleep(0.5 * attempt)

    df_all = pd.concat(results, ignore_index=True) if results else pd.DataFrame()

    # --- нормалізація назв колонок ---
    def _col(options, cols_lower):
        for c in options:
            if c.lower() in cols_lower:
                return next(cc for cc in df_all.columns if cc.lower() == c.lower())
        return None

    if df_all.empty:
        empty_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
        )
        if output_path:
            empty_pairs.to_csv(output_path, index=False)
        return df_all, empty_pairs

    cols_lower = {c.lower() for c in df_all.columns}

    x_col    = _col(["x_ticker", "x", "ticker_x", "subject", "symbol_x"], cols_lower)
    y_col    = _col(["y_ticker", "y", "ticker_y", "benchmark", "symbol_y"], cols_lower)
    corr_col = _col(["corr", "correlation", "pearson_corr"], cols_lower)
    beta_col = _col(["beta", "beta_coeff"], cols_lower)

    missing = [
        name
        for name, val in [("x_ticker", x_col), ("y_ticker", y_col), ("corr", corr_col)]
        if val is None
    ]
    if missing:
        raise ValueError(
            f"Від API бракує очікуваних колонок: {', '.join(missing)}. "
            f"Є колонки: {list(df_all.columns)}"
        )

    # --- вибір найкращого Y для кожного X за corr ---
    df_sorted = df_all.sort_values(by=corr_col, ascending=False)
    idx_best = df_sorted.groupby(x_col, as_index=False)[corr_col].idxmax()[corr_col]
    df_best = df_sorted.loc[
        idx_best, [x_col, y_col, corr_col] + ([beta_col] if beta_col else [])
    ].copy()

    rename_map = {
        x_col: "x_ticker",
        y_col: "best_y_ticker",
        corr_col: "best_corr",
    }
    if beta_col:
        rename_map[beta_col] = "beta_with_best"
    df_pairs = df_best.rename(columns=rename_map)

    if "beta_with_best" not in df_pairs.columns:
        df_pairs["beta_with_best"] = pd.NA

    df_pairs = df_pairs[["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]]

    if output_path:
        df_pairs.to_csv(output_path, index=False)
        print(f"✅ Збережено {len(df_pairs)} пар у файл: {output_path}")

    return df_all, df_pairs

In [14]:
def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    period="3 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.15,
    max_retries=3,
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
):
    """
    Створює два файли:
      1) output_path (за замовчуванням x_to_best_etf_by_lvl3.csv):
         x_ticker, best_y_ticker, best_corr, beta_with_best, lvl3

      2) bench_path (за замовчуванням ticker_bench.csv):
         ticker, benchmark

    Логіка:
      - Для кожного lvl3-сектора збираємо X-список тікерів.
      - Y-список ETF-ів беремо з sector_to_etf[lvl3].
      - Якщо сектору немає в мапі або список порожній → використовуємо fallback_etfs
        (за замовчуванням ["SPY", "QQQ", "IWM"]).
      - Для кожного тикера залишаємо ETF з максимальною кореляцією.
      - Тікери без lvl3 (NaN) обробляються як сектор 'UNKNOWN' з fallback ETF-ами.
    """

    import pandas as pd  # на випадок, якщо не імпортнуто вище

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]

    if sector_col not in tickers_df.columns:
        raise ValueError(f"У tickers_df немає колонки '{sector_col}'")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"У tickers_df немає колонки '{ticker_col}'")

    # Беремо лише тикер і сектор, але НЕ дропаємо NaN — замінимо їх на 'UNKNOWN'
    df_clean = (
        tickers_df[[ticker_col, sector_col]]
        .drop_duplicates()
        .copy()
    )

    # 🔥 Тікери без сектора → 'UNKNOWN'
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)
    df_clean[ticker_col] = df_clean[ticker_col].astype(str)

    all_sectors = sorted(df_clean[sector_col].unique().tolist())

    all_chunks = []
    all_pairs = []
    sectors_with_fallback = []

    for sector in all_sectors:
        etfs = sector_to_etf.get(sector)

        if not etfs:
            etfs = list(fallback_etfs)
            sectors_with_fallback.append(sector)
            print(
                f"⚠️  Для сектора '{sector}' немає ETF-ів у sector_to_etf — "
                f"використовую fallback: {etfs}"
            )
        else:
            print(f"✅ lvl3: {sector} → ETF-и з мапи: {etfs}")

        x_tickers = (
            df_clean.loc[df_clean[sector_col] == sector, ticker_col]
            .astype(str)
            .unique()
            .tolist()
        )
        if not x_tickers:
            continue

        print(f"\n=== lvl3: {sector} | X-тикерів: {len(x_tickers)} | ETF-и: {etfs} ===")

        df_all_sec, df_pairs_sec = corr_beta_best_match_batched(
            x_tickers=x_tickers,
            y_tickers=etfs,
            period=period,
            as_pivot=as_pivot,
            fmt=fmt,
            batch_size=batch_size,
            pause=pause,
            max_retries=max_retries,
            output_path=None,   # тут не пишемо окремі файли
        )

        if not df_all_sec.empty:
            df_all_sec = df_all_sec.copy()
            df_all_sec[sector_col] = sector
            all_chunks.append(df_all_sec)

        if not df_pairs_sec.empty:
            df_pairs_sec = df_pairs_sec.copy()
            df_pairs_sec[sector_col] = sector
            all_pairs.append(df_pairs_sec)

    df_all = pd.concat(all_chunks, ignore_index=True) if all_chunks else pd.DataFrame()

    if all_pairs:
        df_pairs = pd.concat(all_pairs, ignore_index=True)

        # на випадок дублів по x_ticker — лишаємо найбільшу кореляцію
        df_pairs_sorted = df_pairs.sort_values(by="best_corr", ascending=False)
        idx_best = (
            df_pairs_sorted.groupby("x_ticker", as_index=False)["best_corr"]
            .idxmax()["best_corr"]
        )
        df_pairs = df_pairs_sorted.loc[idx_best].reset_index(drop=True)

        # ⚙️ детальний файл
        df_pairs.to_csv(output_path, index=False)
        print(f"\n✅ Збережено {len(df_pairs)} X→ETF пар у файл: {output_path}")

        # ⚙️ спрощений файл вигляду ticker,benchmark
        df_bench = df_pairs.rename(
            columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"}
        )[["ticker", "benchmark"]]

        df_bench.to_csv(bench_path, index=False)
        print(f"✅ Збережено {len(df_bench)} записів у файл: {bench_path}")

    else:
        df_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", sector_col]
        )
        df_pairs.to_csv(output_path, index=False)
        pd.DataFrame(columns=["ticker", "benchmark"]).to_csv(bench_path, index=False)
        print("\n⚠️ Не вдалося знайти жодної пари X→ETF. Створено порожні файли.")

    if sectors_with_fallback:
        print("\n⚠️ Для цих lvl3 використано fallback ETF-и (SPY, QQQ, IWM):")
        for s in sectors_with_fallback:
            print("   -", s)

    return df_all, df_pairs

In [15]:
# нове: працюємо напряму з таблицею top1500 (ticker + lvl3)
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=top1500,          # DataFrame з колонками ticker, lvl3, ...
    sector_to_etf=sector_to_etf, # мапа lvl3 -> список ETF-ів
    sector_col="lvl3",           # Yазва колонки сектора в top1500
    ticker_col="ticker",         # назва колонки з тикером
    period="3 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.1,
    max_retries=3,
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",  # детальна інфа
    bench_path=str(WORK_DIR / "ticker_bench_.csv")
            # простий файл ticker,benchmark
)

print(df_all.head())
print("Рядків у сирих даних:", len(df_all))
print(df_pairs.head())

✅ lvl3: Advertising & Marketing → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Advertising & Marketing | X-тикерів: 35 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[35/35] fetched batch of 35 X тикерів
✅ lvl3: Aerospace & Defense → ETF-и з мапи: ['IWM', 'SPY', 'QQQ']

=== lvl3: Aerospace & Defense | X-тикерів: 73 | ETF-и: ['IWM', 'SPY', 'QQQ'] ===

[73/73] fetched batch of 73 X тикерів
✅ lvl3: Apparel & Textile Products → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Apparel & Textile Products | X-тикерів: 34 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[34/34] fetched batch of 34 X тикерів
✅ lvl3: Asset Management → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Asset Management | X-тикерів: 194 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[150/194] fetched batch of 150 X тикерів

[194/194] fetched batch of 44 X тикерів
✅ lvl3: Automotive → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Automotive | X-тикерів: 73 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[73/73] fetched batch of 73 X тикерів
✅ lvl3: Banking → ETF-и з мапи: ['KRE', 'XLF', 'SPY', 'BITO']

=== lvl3: Banking | X-тикерів: 206 | ETF-и: ['KRE', 'XLF', 'SPY', 'BITO'] ===

[150/206] fetched batch of 150 X тикерів

[206/206] fetched batch of 56 X тикерів
✅ lvl3: Beverages → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Beverages | X-тикерів: 37 | ETF-и: ['SPY', 'IWM'] ===

[37/37] fetched batch of 37 X тикерів
✅ lvl3: Biotech & Pharma → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Biotech & Pharma | X-тикерів: 668 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/668] fetched batch of 150 X тикерів

[300/668] fetched batch of 150 X тикерів

[450/668] fetched batch of 150 X тикерів

[600/668] fetched batch of 150 X тикерів

[668/668] fetched batch of 68 X тикерів
✅ lvl3: Cable & Satellite → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Cable & Satellite | X-тикерів: 13 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[13/13] fetched batch of 13 X тикерів
✅ lvl3: Chemicals → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Chemicals | X-тикерів: 88 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[88/88] fetched batch of 88 X тикерів
✅ lvl3: Commercial Support Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Commercial Support Services | X-тикерів: 108 | ETF-и: ['IWM', 'SPY'] ===

[108/108] fetched batch of 108 X тикерів
✅ lvl3: Construction Materials → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Construction Materials | X-тикерів: 21 | ETF-и: ['IWM', 'SPY'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Consumer Services → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Consumer Services | X-тикерів: 39 | ETF-и: ['SPY', 'IWM'] ===

[39/39] fetched batch of 39 X тикерів
✅ lvl3: Containers & Packaging → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Containers & Packaging | X-тикерів: 20 | ETF-и: ['IWM', 'SPY'] ===

[20/20] fetched batch of 20 X тикерів
✅ lvl3: Diversified Industrials → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Diversified Industrials | X-тикерів: 7 | ETF-и: ['SPY', 'IWM'] ===

[7/7] fetched batch of 7 X тикерів
✅ lvl3: E-Commerce Discretionary → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: E-Commerce Discretionary | X-тикерів: 49 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[49/49] fetched batch of 49 X тикерів
✅ lvl3: Electric Utilities → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Electric Utilities | X-тикерів: 68 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[68/68] fetched batch of 68 X тикерів
✅ lvl3: Electrical Equipment → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Electrical Equipment | X-тикерів: 93 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[93/93] fetched batch of 93 X тикерів
✅ lvl3: Engineering & Construction → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Engineering & Construction | X-тикерів: 52 | ETF-и: ['IWM', 'SPY'] ===

[52/52] fetched batch of 52 X тикерів
✅ lvl3: Entertainment Content → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Entertainment Content | X-тикерів: 43 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[43/43] fetched batch of 43 X тикерів
✅ lvl3: Food → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Food | X-тикерів: 68 | ETF-и: ['SPY', 'IWM'] ===

[68/68] fetched batch of 68 X тикерів
✅ lvl3: Forestry, Paper & Wood Products → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Forestry, Paper & Wood Products | X-тикерів: 10 | ETF-и: ['IWM', 'SPY'] ===

[10/10] fetched batch of 10 X тикерів
✅ lvl3: Gas & Water Utilities → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Gas & Water Utilities | X-тикерів: 23 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[23/23] fetched batch of 23 X тикерів
✅ lvl3: Health Care Facilities & Svcs → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Health Care Facilities & Svcs | X-тикерів: 99 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[99/99] fetched batch of 99 X тикерів
✅ lvl3: Home & Office Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Home & Office Products | X-тикерів: 21 | ETF-и: ['SPY', 'IWM'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Home Construction → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Home Construction | X-тикерів: 35 | ETF-и: ['IWM', 'SPY'] ===

[35/35] fetched batch of 35 X тикерів
✅ lvl3: Household Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Household Products | X-тикерів: 39 | ETF-и: ['SPY', 'IWM'] ===

[39/39] fetched batch of 39 X тикерів
✅ lvl3: IT Services → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: IT Services | X-тикерів: 66 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[66/66] fetched batch of 66 X тикерів
✅ lvl3: Industrial Intermediate Prod → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Industrial Intermediate Prod | X-тикерів: 20 | ETF-и: ['IWM', 'SPY'] ===

[20/20] fetched batch of 20 X тикерів
✅ lvl3: Industrial Support Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Industrial Support Services | X-тикерів: 30 | ETF-и: ['IWM', 'SPY'] ===

[30/30] fetched batch of 30 X тикерів
✅ lvl3: Institutional Financial Svcs → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Institutional Financial Svcs | X-тикерів: 39 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[39/39] fetched batch of 39 X тикерів
✅ lvl3: Insurance → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Insurance | X-тикерів: 86 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[86/86] fetched batch of 86 X тикерів
✅ lvl3: Internet Media & Services → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Internet Media & Services | X-тикерів: 106 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[106/106] fetched batch of 106 X тикерів
✅ lvl3: Leisure Facilities & Services → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Leisure Facilities & Services | X-тикерів: 112 | ETF-и: ['SPY', 'IWM'] ===

[112/112] fetched batch of 112 X тикерів
✅ lvl3: Leisure Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Leisure Products | X-тикерів: 32 | ETF-и: ['SPY', 'IWM'] ===

[32/32] fetched batch of 32 X тикерів
✅ lvl3: Machinery → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Machinery | X-тикерів: 81 | ETF-и: ['IWM', 'SPY'] ===

[81/81] fetched batch of 81 X тикерів
✅ lvl3: Medical Equipment & Devices → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Medical Equipment & Devices | X-тикерів: 204 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/204] fetched batch of 150 X тикерів

[204/204] fetched batch of 54 X тикерів
✅ lvl3: Metals & Mining → ETF-и з мапи: ['GDX', 'IWM', 'SPY']

=== lvl3: Metals & Mining | X-тикерів: 151 | ETF-и: ['GDX', 'IWM', 'SPY'] ===

[150/151] fetched batch of 150 X тикерів

[151/151] fetched batch of 1 X тикерів
✅ lvl3: Oil & Gas Services & Equip → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Oil & Gas Services & Equip | X-тикерів: 56 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[56/56] fetched batch of 56 X тикерів
✅ lvl3: Oil & Gas Supply Chain → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Oil & Gas Supply Chain | X-тикерів: 139 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[139/139] fetched batch of 139 X тикерів
✅ lvl3: Publishing & Broadcasting → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Publishing & Broadcasting | X-тикерів: 19 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: REIT → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: REIT | X-тикерів: 133 | ETF-и: ['IWM', 'SPY'] ===

[133/133] fetched batch of 133 X тикерів
✅ lvl3: Real Estate Owners & Developers → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Real Estate Owners & Developers | X-тикерів: 13 | ETF-и: ['IWM', 'SPY'] ===

[13/13] fetched batch of 13 X тикерів
✅ lvl3: Real Estate Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Real Estate Services | X-тикерів: 18 | ETF-и: ['IWM', 'SPY'] ===

[18/18] fetched batch of 18 X тикерів
✅ lvl3: Renewable Energy → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Renewable Energy | X-тикерів: 58 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[58/58] fetched batch of 58 X тикерів
✅ lvl3: Retail - Consumer Staples → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Retail - Consumer Staples | X-тикерів: 25 | ETF-и: ['SPY', 'IWM'] ===

[25/25] fetched batch of 25 X тикерів
✅ lvl3: Retail - Discretionary → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Retail - Discretionary | X-тикерів: 103 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[103/103] fetched batch of 103 X тикерів
✅ lvl3: Semiconductors → ETF-и з мапи: ['SOXL', 'QQQ', 'IWM', 'SPY']

=== lvl3: Semiconductors | X-тикерів: 104 | ETF-и: ['SOXL', 'QQQ', 'IWM', 'SPY'] ===

[104/104] fetched batch of 104 X тикерів
✅ lvl3: Software → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Software | X-тикерів: 325 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/325] fetched batch of 150 X тикерів

[300/325] fetched batch of 150 X тикерів

[325/325] fetched batch of 25 X тикерів
✅ lvl3: Specialty Finance → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Specialty Finance | X-тикерів: 171 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[150/171] fetched batch of 150 X тикерів

[171/171] fetched batch of 21 X тикерів
✅ lvl3: Steel → ETF-и з мапи: ['GDX', 'IWM', 'SPY']

=== lvl3: Steel | X-тикерів: 19 | ETF-и: ['GDX', 'IWM', 'SPY'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: Technology Hardware → ETF-и з мапи: ['QQQ', 'SOXL', 'IWM', 'SPY']

=== lvl3: Technology Hardware | X-тикерів: 136 | ETF-и: ['QQQ', 'SOXL', 'IWM', 'SPY'] ===

[136/136] fetched batch of 136 X тикерів
✅ lvl3: Telecommunications → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Telecommunications | X-тикерів: 41 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[41/41] fetched batch of 41 X тикерів
✅ lvl3: Tobacco & Cannabis → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Tobacco & Cannabis | X-тикерів: 19 | ETF-и: ['SPY', 'IWM'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: Transportation & Logistics → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Transportation & Logistics | X-тикерів: 125 | ETF-и: ['IWM', 'SPY'] ===

[125/125] fetched batch of 125 X тикерів
✅ lvl3: Transportation Equipment → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Transportation Equipment | X-тикерів: 20 | ETF-и: ['IWM', 'SPY'] ===

[20/20] fetched batch of 20 X тикерів
⚠️  Для сектора 'UNKNOWN' немає ETF-ів у sector_to_etf — використовую fallback: ['SPY', 'QQQ', 'IWM']

=== lvl3: UNKNOWN | X-тикерів: 2080 | ETF-и: ['SPY', 'QQQ', 'IWM'] ===

[150/2080] fetched batch of 150 X тикерів

[300/2080] fetched batch of 150 X тикерів

[450/2080] fetched batch of 150 X тикерів

[600/2080] fetched batch of 150 X тикерів

[750/2080] fetched batch of 150 X тикерів

[900/2080] fetched batch of 150 X тикерів

[1050/2080] fetched batch of 150 X тикерів

[1200/2080] fetched batch of 150 X тикерів

[1350/2080] fetched batch of 150 X тикерів

[1500/2080] fetched batch of 150 X тикерів

[1650/2080] fetched batch of 150 X тикерів

[1800/2080] fetched batch of 150 X тикерів

[1950/2080] fetched batch of 150 X тикерів

[2080/2080] fetched batch of 130 X тикерів
✅ lvl3: Wholesale - Consumer Staples → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Wholesale - Consumer Staples | X-тикерів: 12 | ETF-и: ['SPY', 'IWM'] ===

[12/12] fetched batch of 12 X тикерів
✅ lvl3: Wholesale - Discretionary → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Wholesale - Discretionary | X-тикерів: 15 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[15/15] fetched batch of 15 X тикерів

✅ Збережено 6599 X→ETF пар у файл: CRACEN/work/x_to_best_etf_by_lvl3.csv
✅ Збережено 6599 записів у файл: C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv

⚠️ Для цих lvl3 використано fallback ETF-и (SPY, QQQ, IWM):
   - UNKNOWN
  x_ticker y_ticker  corr  beta                     lvl3
0      ADV      SPY  0.57  0.84  Advertising & Marketing
1      ADV      IWM  0.40  0.00  Advertising & Marketing
2      ADV      QQQ  0.35  0.00  Advertising & Marketing
3      ADV     KWEB -0.02  0.00  Advertising & Marketing
4      APP      SPY  0.82  2.83  Advertising & Marketing
Рядків у сирих даних: 19441
  x_ticker best_y_ticker  best_corr  beta_with_best  \
0        A           IWM       0.64            0.37
1       AA           GDX       0.78            0.58
2     AAAU           SPY       0.35            0.31
3     AACG           QQQ      -0.02            0.00
4      AAL           SPY       0.82            1.57

                          lvl3
0  Medical Equipment & Devices
1              Metals & Mining
2                      UNKNOWN
3                     Software
4   Transportation & Logistics

In [16]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [17]:
top1500

,ticker,value,lvl3,country,exchange,market_cap
0,A,65894.16,Medical Equipment & Devices,UNITED STATES,New York,35285.0
1,AA,1596127.54,Metals & Mining,UNITED STATES,New York,16806.0
2,AAAU,1072592.05,NaN,NaN,NaN,NaN
3,AACG,12.40,Software,UNITED STATES,NASDAQ CM,31.0
4,AAL,1136930.56,Transportation & Logistics,UNITED STATES,NASDAQ GS,8795.0
...,...,...,...,...,...,...
6769,ZWS,140.89,Machinery,UNITED STATES,New York,8444.0
6770,ZYBT,41.63,Biotech & Pharma,UNITED STATES,NASDAQ CM,42.0
6771,ZYME,34606.19,Biotech & Pharma,UNITED STATES,NASDAQ GS,1818.0
6772,ZYXI,8578.41,NaN,NaN,NaN,NaN
6773,ZYXIQ,8578.41,NaN,NaN,NaN,NaN

In [18]:
import pandas as pd

# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','SOXL']

# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

  ticker
0    SPY
1    IWM
2    GDX
3    XLF
4    QQQ
5    XLE
6    KRE
7   BITO
8   KWEB
9   SOXL

In [19]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=top1500,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=9,
    parallel_tickers=True,
    max_workers_tickers=2,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 5900 тікерів (пропущено 0 по старому маніфесту) | 2025-11-25 00:00:00 → 2026-02-25 23:59:59 | interval=1 | next batch #0302 | run=2ebe3739

   workers: tickers=2, chunks=9 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 874

   📉 пропущені дні (в межах window): 2025-11-25 → 2026-02-25 (93 днів)

   📈 обробляються дні: –

   psutil · старт · 🧠 RAM: 246.9 MB

[10/5900] – BND: empty |   0.17% | ETA 19:25

[20/5900] – BNO: empty |   0.34% | ETA 18:28

[30/5900] – BOBS: empty |   0.51% | ETA 18:27

[40/5900] – BON: empty |   0.68% | ETA 18:24

[50/5900] – BOXX: empty |   0.85% | ETA 17:54

   • RAM · 🧠 RAM: 259.0 MB

[60/5900] – BRCC: empty |   1.02% | ETA 17:40

[70/5900] – BRNS: empty |   1.19% | ETA 17:31

[80/5900] – BRX: empty |   1.36% | ETA 17:24

[90/5900] – BSJQ: empty |   1.53% | ETA 17:20

[100/5900] – BTAL: empty |   1.69% | ETA 17:31

   • RAM · 🧠 RAM: 259.1 MB

[110/5900] – BTCZ: empty |   1.86% | ETA 17:30

[120/5900] – BTM: empty |   2.03% | ETA 17:26

[130/5900] – BTYB: empty |   2.20% | ETA 17:49

[140/5900] – BUR: empty |   2.37% | ETA 17:49

[150/5900] – BVS: empty |   2.54% | ETA 17:49

   • RAM · 🧠 RAM: 259.6 MB

[160/5900] – BWX: empty |   2.71% | ETA 17:59

[170/5900] – BYSI: empty |   2.88% | ETA 17:54

[180/5900] – CABA: empty |   3.05% | ETA 17:45

[190/5900] – CAE: empty |   3.22% | ETA 17:43

[200/5900] – CALX: empty |   3.39% | ETA 17:34

   • RAM · 🧠 RAM: 260.4 MB

[210/5900] – CAPS: empty |   3.56% | ETA 17:20

[220/5900] – CASI: empty |   3.73% | ETA 17:06

[230/5900] – CBAT: empty |   3.90% | ETA 17:12

[240/5900] – CBUS: empty |   4.07% | ETA 17:00

[250/5900] – CCD: empty |   4.24% | ETA 16:49

   • RAM · 🧠 RAM: 260.7 MB

[260/5900] – CCLD: empty |   4.41% | ETA 16:37

[270/5900] – CD: empty |   4.58% | ETA 16:27

[280/5900] – CDRE: empty |   4.75% | ETA 16:25

[290/5900] – CEG: empty |   4.92% | ETA 16:17

[300/5900] – CEPO: empty |   5.08% | ETA 16:09

   • RAM · 🧠 RAM: 260.8 MB

[310/5900] – CFG: empty |   5.25% | ETA 16:03

[320/5900] – CGCT: empty |   5.42% | ETA 16:07

[330/5900] – CGNX: empty |   5.59% | ETA 16:00

[340/5900] – CHCO: empty |   5.76% | ETA 15:54

[350/5900] – CHNR: empty |   5.93% | ETA 15:48

   • RAM · 🧠 RAM: 260.9 MB

[360/5900] – CHSN: empty |   6.10% | ETA 15:41

[370/5900] – CIFR: empty |   6.27% | ETA 15:34

[380/5900] – CINT: empty |   6.44% | ETA 15:28

[390/5900] – CLDX: empty |   6.61% | ETA 15:21

[400/5900] – CLMB: empty |   6.78% | ETA 15:15

   • RAM · 🧠 RAM: 261.0 MB

[410/5900] – CLRB: empty |   6.95% | ETA 15:13

[420/5900] – CLX: empty |   7.12% | ETA 15:07

[430/5900] – CMCT: empty |   7.29% | ETA 15:03

[440/5900] – CMPR: empty |   7.46% | ETA 14:59

[450/5900] – CNCK: empty |   7.63% | ETA 14:55

   • RAM · 🧠 RAM: 261.1 MB

[460/5900] – CNNE: empty |   7.80% | ETA 14:51

[470/5900] – CNTA: empty |   7.97% | ETA 14:47

[480/5900] – COAL: empty |   8.14% | ETA 14:47

[490/5900] – COHR: empty |   8.31% | ETA 14:43

[500/5900] – COLD: empty |   8.47% | ETA 14:39

   • RAM · 🧠 RAM: 261.1 MB

[510/5900] – CONY: empty |   8.64% | ETA 14:35

[520/5900] – COPZ: empty |   8.81% | ETA 14:33

[530/5900] – COTY: empty |   8.98% | ETA 14:30

[540/5900] – CPHI: empty |   9.15% | ETA 14:27

[550/5900] – CPSS: empty |   9.32% | ETA 14:24

   • RAM · 🧠 RAM: 261.2 MB

[560/5900] – CRBU: empty |   9.49% | ETA 14:20

[570/5900] – CRDU: empty |   9.66% | ETA 14:16

[580/5900] – CRH: empty |   9.83% | ETA 14:14

[590/5900] – CRMT: empty |  10.00% | ETA 14:11

[600/5900] – CRSH: empty |  10.17% | ETA 14:07

   • RAM · 🧠 RAM: 261.3 MB

[610/5900] – CRWG: empty |  10.34% | ETA 14:04

[620/5900] – CSGS: empty |  10.51% | ETA 14:00

[630/5900] – CSV: empty |  10.68% | ETA 13:59

[640/5900] – CTM: empty |  10.85% | ETA 13:56

[650/5900] – CTRN: empty |  11.02% | ETA 13:53

   • RAM · 🧠 RAM: 261.4 MB

[660/5900] – CUPR: empty |  11.19% | ETA 13:52

[670/5900] – CVBF: empty |  11.36% | ETA 13:50

[680/5900] – CVRX: empty |  11.53% | ETA 13:47

[690/5900] – CWD: empty |  11.69% | ETA 13:45

[700/5900] – CWVX: empty |  11.86% | ETA 13:44

   • RAM · 🧠 RAM: 261.6 MB

[710/5900] – CYD: empty |  12.03% | ETA 13:43

[720/5900] – D: empty |  12.20% | ETA 13:42

[730/5900] – DAR: empty |  12.37% | ETA 13:39

[740/5900] ✓ DBB: 4,063 рядків |  12.54% | ETA 13:49

[750/5900] ✓ DBRG: 6,853 рядків |  12.71% | ETA 14:11

   • RAM · 🧠 RAM: 274.0 MB

   ⏳ перед flush · 🧠 RAM: 274.0 MB

💾 batch 302 → 54,962 рядків (всього 54,962 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0302.csv.gz

   ✅ після flush · 🧠 RAM: 272.8 MB

[760/5900] ✓ DCOY: 1,548 рядків |  12.88% | ETA 14:33

[770/5900] ✓ DDOG: 9,603 рядків |  13.05% | ETA 14:59

[780/5900] ✓ DERM: 1,653 рядків |  13.22% | ETA 15:27

[790/5900] ✓ DFJ: 1,842 рядків |  13.39% | ETA 15:47

[800/5900] ✓ DGP: 2,703 рядків |  13.56% | ETA 16:06

   • RAM · 🧠 RAM: 317.5 MB

   ⏳ перед flush · 🧠 RAM: 317.5 MB

💾 batch 303 → 297,364 рядків (всього 352,326 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0303.csv.gz

   ✅ після flush · 🧠 RAM: 319.3 MB

[810/5900] ✓ DHI: 7,156 рядків |  13.73% | ETA 16:26

[820/5900] ✓ DIOD: 4,499 рядків |  13.90% | ETA 16:54

[830/5900] ✓ DJD: 1,677 рядків |  14.07% | ETA 17:11

[840/5900] ✓ DKUP: 302 рядків |  14.24% | ETA 17:32

[850/5900] ✓ DLXY: 465 рядків |  14.41% | ETA 17:46

   • RAM · 🧠 RAM: 349.3 MB

   ⏳ перед flush · 🧠 RAM: 349.3 MB

💾 batch 304 → 236,399 рядків (всього 588,725 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0304.csv.gz

   ✅ після flush · 🧠 RAM: 353.2 MB

[860/5900] ✓ DNP: 4,926 рядків |  14.58% | ETA 18:05

[870/5900] ✓ DOGZ: 4,545 рядків |  14.75% | ETA 18:24

[880/5900] ✓ DOX: 6,571 рядків |  14.92% | ETA 18:41

[890/5900] ✓ DRI: 6,239 рядків |  15.08% | ETA 19:00

[900/5900] ✓ DRUG: 1,730 рядків |  15.25% | ETA 19:13

   • RAM · 🧠 RAM: 380.6 MB

   ⏳ перед flush · 🧠 RAM: 380.6 MB

💾 batch 305 → 234,671 рядків (всього 823,396 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0305.csv.gz

   ✅ після flush · 🧠 RAM: 385.3 MB

[910/5900] ✓ DSY: 2,085 рядків |  15.42% | ETA 19:25

[920/5900] ✓ DTST: 397 рядків |  15.59% | ETA 19:39

[930/5900] ✓ DUST: 13,597 рядків |  15.76% | ETA 19:58

[940/5900] ✓ DXC: 7,161 рядків |  15.93% | ETA 20:21

[950/5900] ✓ DYAI: 441 рядків |  16.10% | ETA 20:38

   • RAM · 🧠 RAM: 418.0 MB

   ⏳ перед flush · 🧠 RAM: 418.0 MB

💾 batch 306 → 246,898 рядків (всього 1,070,294 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0306.csv.gz

   ✅ після flush · 🧠 RAM: 421.9 MB

[960/5900] ✓ EARN: 3,929 рядків |  16.27% | ETA 20:50

[970/5900] ✓ ECAT: 5,004 рядків |  16.44% | ETA 21:04

[980/5900] ✓ ECVT: 5,973 рядків |  16.61% | ETA 21:14

[990/5900] ✓ EDN: 1,919 рядків |  16.78% | ETA 21:25

[1000/5900] ✓ EEX: 3,328 рядків |  16.95% | ETA 21:36

   • RAM · 🧠 RAM: 449.5 MB

   ⏳ перед flush · 🧠 RAM: 449.5 MB

💾 batch 307 → 223,449 рядків (всього 1,293,743 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0307.csv.gz

   ✅ після flush · 🧠 RAM: 454.1 MB

[1010/5900] ✓ EFXT: 4,762 рядків |  17.12% | ETA 21:47

[1020/5900] ✓ EH: 5,018 рядків |  17.29% | ETA 21:59

[1030/5900] ✓ EIX: 7,626 рядків |  17.46% | ETA 22:08

[1040/5900] ✓ ELF: 8,326 рядків |  17.63% | ETA 22:20

[1050/5900] ✓ ELTX: 1,974 рядків |  17.80% | ETA 22:30

   • RAM · 🧠 RAM: 484.5 MB

   ⏳ перед flush · 🧠 RAM: 484.5 MB

💾 batch 308 → 225,464 рядків (всього 1,519,207 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0308.csv.gz

   ✅ після flush · 🧠 RAM: 485.8 MB

[1060/5900] ✓ EMBC: 5,225 рядків |  17.97% | ETA 22:39

[1070/5900] ✓ ENFR: 4,906 рядків |  18.14% | ETA 22:52

[1080/5900] ✓ ENR: 6,389 рядків |  18.31% | ETA 23:01

[1090/5900] ✓ ENVX: 8,952 рядків |  18.47% | ETA 23:12

[1100/5900] ✓ EPD: 7,477 рядків |  18.64% | ETA 23:23

   • RAM · 🧠 RAM: 516.1 MB

   ⏳ перед flush · 🧠 RAM: 516.1 MB

💾 batch 309 → 238,628 рядків (всього 1,757,835 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0309.csv.gz

   ✅ після flush · 🧠 RAM: 518.9 MB

[1110/5900] ✓ EPSM: 810 рядків |  18.81% | ETA 23:31

[1120/5900] ✓ EQPT: 5,800 рядків |  18.98% | ETA 23:38

[1130/5900] ✓ ERX: 5,460 рядків |  19.15% | ETA 23:53

[1140/5900] ✓ ESGU: 5,997 рядків |  19.32% | ETA 23:58

[1150/5900] ✓ ESQ: 1,155 рядків |  19.49% | ETA 24:02

   • RAM · 🧠 RAM: 544.6 MB

   ⏳ перед flush · 🧠 RAM: 547.2 MB

💾 batch 310 → 221,206 рядків (всього 1,979,041 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0310.csv.gz

   ✅ після flush · 🧠 RAM: 551.7 MB

[1160/5900] ✓ ETHA: 19,468 рядків |  19.66% | ETA 24:19

[1170/5900] ✓ ETHZ: 5,621 рядків |  19.83% | ETA 24:31

[1180/5900] ✓ EU: 7,085 рядків |  20.00% | ETA 24:41

[1190/5900] ✓ EVEX: 6,224 рядків |  20.17% | ETA 24:45

[1200/5900] ✓ EVSD: 1,883 рядків |  20.34% | ETA 24:53

   • RAM · 🧠 RAM: 585.9 MB

   ⏳ перед flush · 🧠 RAM: 585.9 MB

💾 batch 311 → 279,710 рядків (всього 2,258,751 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0311.csv.gz

   ✅ після flush · 🧠 RAM: 589.2 MB

[1210/5900] ✓ EWC: 7,151 рядків |  20.51% | ETA 25:02

[1220/5900] ✓ EWN: 3,618 рядків |  20.68% | ETA 25:09

[1230/5900] ✓ EWY: 15,918 рядків |  20.85% | ETA 25:21

[1240/5900] ✓ EXLS: 7,028 рядків |  21.02% | ETA 25:30

[1250/5900] ✓ EYPT: 6,202 рядків |  21.19% | ETA 25:40

   • RAM · 🧠 RAM: 628.8 MB

   ⏳ перед flush · 🧠 RAM: 628.8 MB

💾 batch 312 → 301,564 рядків (всього 2,560,315 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0312.csv.gz

   ✅ після flush · 🧠 RAM: 632.6 MB

[1260/5900] ✓ FA: 5,933 рядків |  21.36% | ETA 25:46

[1270/5900] ✓ FAST: 7,528 рядків |  21.53% | ETA 25:51

[1280/5900] ✓ FBIN: 6,967 рядків |  21.69% | ETA 25:57

[1290/5900] ✓ FBTC: 10,982 рядків |  21.86% | ETA 26:05

[1300/5900] ✓ FCO: 1,841 рядків |  22.03% | ETA 26:06

   • RAM · 🧠 RAM: 661.1 MB

   ⏳ перед flush · 🧠 RAM: 661.1 MB

💾 batch 313 → 237,297 рядків (всього 2,797,612 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0313.csv.gz

   ✅ після flush · 🧠 RAM: 666.4 MB

[1310/5900] ✓ FDN: 6,892 рядків |  22.20% | ETA 26:12

[1320/5900] ✓ FEIM: 2,655 рядків |  22.37% | ETA 26:17

[1330/5900] ✓ FER: 6,726 рядків |  22.54% | ETA 26:24

[1340/5900] ✓ FFIN: 5,368 рядків |  22.71% | ETA 26:31

[1350/5900] ✓ FGRU: 288 рядків |  22.88% | ETA 26:30

   • RAM · 🧠 RAM: 698.6 MB

   ⏳ перед flush · 🧠 RAM: 698.6 MB

💾 batch 314 → 261,033 рядків (всього 3,058,645 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0314.csv.gz

   ✅ після flush · 🧠 RAM: 708.1 MB

[1360/5900] ✓ FICO: 7,009 рядків |  23.05% | ETA 26:34

[1370/5900] ✓ FISI: 2,572 рядків |  23.22% | ETA 26:43

[1380/5900] ✓ FIZZ: 3,251 рядків |  23.39% | ETA 26:45

[1390/5900] ✓ FLIN: 5,231 рядків |  23.56% | ETA 26:48

[1400/5900] ✓ FLOT: 6,273 рядків |  23.73% | ETA 26:52

   • RAM · 🧠 RAM: 737.0 MB

   ⏳ перед flush · 🧠 RAM: 737.0 MB

💾 batch 315 → 264,397 рядків (всього 3,323,042 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0315.csv.gz

   ✅ після flush · 🧠 RAM: 739.9 MB

[1410/5900] ✓ FLWS: 4,592 рядків |  23.90% | ETA 26:55

[1420/5900] ✓ FMNB: 4,383 рядків |  24.07% | ETA 26:57

[1430/5900] ✓ FNDF: 7,085 рядків |  24.24% | ETA 27:01

[1440/5900] ✓ FNV: 6,197 рядків |  24.41% | ETA 27:06

[1450/5900] ✓ FOXA: 7,192 рядків |  24.58% | ETA 27:09

   • RAM · 🧠 RAM: 768.7 MB

   ⏳ перед flush · 🧠 RAM: 768.7 MB

💾 batch 316 → 248,784 рядків (всього 3,571,826 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0316.csv.gz

   ✅ після flush · 🧠 RAM: 771.8 MB

[1460/5900] ✓ FRGT: 4,919 рядків |  24.75% | ETA 27:10

[1470/5900] ✓ FSCO: 6,180 рядків |  24.92% | ETA 27:15

[1480/5900] ✓ FTCI: 1,568 рядків |  25.08% | ETA 27:20

[1490/5900] ✓ FTI: 7,285 рядків |  25.25% | ETA 27:21

[1500/5900] ✓ FUFU: 1,226 рядків |  25.42% | ETA 27:23

   • RAM · 🧠 RAM: 793.1 MB

   ⏳ перед flush · 🧠 RAM: 793.1 MB

💾 batch 317 → 262,738 рядків (всього 3,834,564 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0317.csv.gz

   ✅ після flush · 🧠 RAM: 798.1 MB

[1510/5900] ✓ FUTU: 8,933 рядків |  25.59% | ETA 27:27

[1520/5900] ✓ FXC: 1,713 рядків |  25.76% | ETA 27:29

[1530/5900] ✓ G: 6,990 рядків |  25.93% | ETA 27:30

[1540/5900] ✓ GAUZ: 1,216 рядків |  26.10% | ETA 27:31

[1550/5900] ✓ GBX: 2,978 рядків |  26.27% | ETA 27:33

   • RAM · 🧠 RAM: 824.9 MB

   ⏳ перед flush · 🧠 RAM: 824.9 MB

💾 batch 318 → 234,101 рядків (всього 4,068,665 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0318.csv.gz

   ✅ після flush · 🧠 RAM: 828.3 MB

[1560/5900] ✓ GDC: 759 рядків |  26.44% | ETA 27:34

[1570/5900] ✓ GDS: 7,366 рядків |  26.61% | ETA 27:35

[1580/5900] ✓ GE: 9,162 рядків |  26.78% | ETA 27:44

[1590/5900] ✓ GERN: 7,901 рядків |  26.95% | ETA 27:46

[1600/5900] ✓ GFS: 7,836 рядків |  27.12% | ETA 27:51

   • RAM · 🧠 RAM: 842.5 MB

   ⏳ перед flush · 🧠 RAM: 842.5 MB

💾 batch 319 → 275,474 рядків (всього 4,344,139 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0319.csv.gz

   ✅ після flush · 🧠 RAM: 841.5 MB

[1610/5900] ✓ GHC: 2,251 рядків |  27.29% | ETA 27:53

[1620/5900] ✓ GIG: 498 рядків |  27.46% | ETA 27:49

[1630/5900] ✓ GLAD: 3,568 рядків |  27.63% | ETA 27:52

[1640/5900] ✓ GLDM: 16,201 рядків |  27.80% | ETA 27:55

[1650/5900] ✓ GLOO: 990 рядків |  27.97% | ETA 27:55

   • RAM · 🧠 RAM: 810.4 MB

   ⏳ перед flush · 🧠 RAM: 810.4 MB

💾 batch 320 → 240,219 рядків (всього 4,584,358 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0320.csv.gz

   ✅ після flush · 🧠 RAM: 811.4 MB

[1660/5900] ✓ GM: 8,010 рядків |  28.14% | ETA 27:59

[1670/5900] ✓ GMHS: 477 рядків |  28.31% | ETA 27:57

[1680/5900] ✓ GNS: 5,894 рядків |  28.47% | ETA 27:58

[1690/5900] ✓ GOEX: 1,307 рядків |  28.64% | ETA 27:57

[1700/5900] ✓ GOOW: 2,146 рядків |  28.81% | ETA 28:03

   • RAM · 🧠 RAM: 779.3 MB

   ⏳ перед flush · 🧠 RAM: 779.3 MB

💾 batch 321 → 252,866 рядків (всього 4,837,224 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0321.csv.gz

   ✅ після flush · 🧠 RAM: 778.0 MB

[1710/5900] ✓ GOVI: 2,542 рядків |  28.98% | ETA 28:03

[1720/5900] ✓ GPIQ: 8,875 рядків |  29.15% | ETA 28:04

[1730/5900] ✓ GRAG: 167 рядків |  29.32% | ETA 28:07

[1740/5900] ✓ GREK: 2,489 рядків |  29.49% | ETA 28:04

[1750/5900] ✓ GRNY: 7,513 рядків |  29.66% | ETA 28:04

   • RAM · 🧠 RAM: 745.6 MB

   ⏳ перед flush · 🧠 RAM: 745.6 MB

💾 batch 322 → 240,429 рядків (всього 5,077,653 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0322.csv.gz

   ✅ після flush · 🧠 RAM: 748.6 MB

[1760/5900] ✓ GSBD: 6,176 рядків |  29.83% | ETA 28:06

[1770/5900] ✓ GSOL: 6,754 рядків |  30.00% | ETA 28:04

[1780/5900] ✓ GTN: 6,259 рядків |  30.17% | ETA 28:06

[1790/5900] ✓ GVAL: 8,324 рядків |  30.34% | ETA 28:06

[1800/5900] ✓ GXO: 6,397 рядків |  30.51% | ETA 28:04

   • RAM · 🧠 RAM: 719.1 MB

   ⏳ перед flush · 🧠 RAM: 719.1 MB

💾 batch 323 → 245,616 рядків (всього 5,323,269 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0323.csv.gz

   ✅ після flush · 🧠 RAM: 720.1 MB

[1810/5900] ✓ HAO: 217 рядків |  30.68% | ETA 28:04

[1820/5900] ✓ HBNC: 12,937 рядків |  30.85% | ETA 28:03

[1830/5900] ✓ HCTI: 8,603 рядків |  31.02% | ETA 28:04

[1840/5900] ✓ HELE: 5,141 рядків |  31.19% | ETA 28:04

[1850/5900] ✓ HFWA: 3,500 рядків |  31.36% | ETA 28:00

   • RAM · 🧠 RAM: 695.7 MB

   ⏳ перед flush · 🧠 RAM: 695.7 MB

💾 batch 324 → 233,991 рядків (всього 5,557,260 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0324.csv.gz

   ✅ після flush · 🧠 RAM: 698.6 MB

[1860/5900] ✓ HIFS: 2,255 рядків |  31.53% | ETA 27:58

[1870/5900] ✓ HIMZ: 18,514 рядків |  31.69% | ETA 28:00

[1880/5900] ✓ HLAL: 1,735 рядків |  31.86% | ETA 27:59

[1890/5900] ✓ HLT: 7,164 рядків |  32.03% | ETA 28:00

[1900/5900] ✓ HNST: 7,246 рядків |  32.20% | ETA 27:59

   • RAM · 🧠 RAM: 688.9 MB

   ⏳ перед flush · 🧠 RAM: 688.9 MB

💾 batch 325 → 259,880 рядків (всього 5,817,140 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0325.csv.gz

   ✅ після flush · 🧠 RAM: 695.4 MB

[1910/5900] – HOOI: empty |  32.37% | ETA 28:01

[1920/5900] ✓ HOV: 1,665 рядків |  32.54% | ETA 27:59

[1930/5900] ✓ HQY: 5,725 рядків |  32.71% | ETA 27:59

[1940/5900] ✓ HSAI: 8,063 рядків |  32.88% | ETA 28:00

[1950/5900] ✓ HSY: 7,130 рядків |  33.05% | ETA 27:57

   • RAM · 🧠 RAM: 715.2 MB

   ⏳ перед flush · 🧠 RAM: 715.2 MB

💾 batch 326 → 262,221 рядків (всього 6,079,361 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0326.csv.gz

   ✅ після flush · 🧠 RAM: 717.9 MB

[1960/5900] ✓ HTO: 3,434 рядків |  33.22% | ETA 27:55

[1970/5900] ✓ HUMA: 8,427 рядків |  33.39% | ETA 27:54

[1980/5900] ✓ HWH: 533 рядків |  33.56% | ETA 27:53

[1990/5900] ✓ HYGH: 1,617 рядків |  33.73% | ETA 27:51

[2000/5900] ✓ HZO: 11,489 рядків |  33.90% | ETA 27:48

   • RAM · 🧠 RAM: 744.4 MB

   ⏳ перед flush · 🧠 RAM: 744.4 MB

💾 batch 327 → 207,469 рядків (всього 6,286,830 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0327.csv.gz

   ✅ після flush · 🧠 RAM: 749.4 MB

[2010/5900] ✓ IAU: 17,233 рядків |  34.07% | ETA 27:48

[2020/5900] ✓ IBIO: 5,413 рядків |  34.24% | ETA 27:46

[2030/5900] ✓ IBTA: 5,405 рядків |  34.41% | ETA 27:48

[2040/5900] ✓ ICHR: 6,747 рядків |  34.58% | ETA 27:45

[2050/5900] ✓ ICU: 1,272 рядків |  34.75% | ETA 27:43

   • RAM · 🧠 RAM: 779.4 MB

   ⏳ перед flush · 🧠 RAM: 779.4 MB

💾 batch 328 → 255,425 рядків (всього 6,542,255 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0328.csv.gz

   ✅ після flush · 🧠 RAM: 783.9 MB

[2060/5900] ✓ IDNA: 907 рядків |  34.92% | ETA 27:39

[2070/5900] ✓ IEF: 8,603 рядків |  35.08% | ETA 27:39

[2080/5900] ✓ IEUR: 6,786 рядків |  35.25% | ETA 27:38

[2090/5900] ✓ IGIB: 6,560 рядків |  35.42% | ETA 27:36

[2100/5900] ✓ IHAK: 3,935 рядків |  35.59% | ETA 27:34

   • RAM · 🧠 RAM: 795.1 MB

   ⏳ перед flush · 🧠 RAM: 795.1 MB

💾 batch 329 → 208,828 рядків (всього 6,751,083 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0329.csv.gz

   ✅ після flush · 🧠 RAM: 795.0 MB

[2110/5900] ✓ IINN: 3,013 рядків |  35.76% | ETA 27:32

[2120/5900] – ILLR: empty |  35.93% | ETA 27:28

[2130/5900] ✓ IMMX: 5,364 рядків |  36.10% | ETA 27:26

[2140/5900] ✓ IMST: 862 рядків |  36.27% | ETA 27:22

[2150/5900] ✓ INCO: 1,278 рядків |  36.44% | ETA 27:19

   • RAM · 🧠 RAM: 811.0 MB

   ⏳ перед flush · 🧠 RAM: 811.0 MB

💾 batch 330 → 196,504 рядків (всього 6,947,587 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0330.csv.gz

   ✅ після flush · 🧠 RAM: 815.1 MB

[2160/5900] ✓ INDV: 6,289 рядків |  36.61% | ETA 27:17

[2170/5900] ✓ INKT: 302 рядків |  36.78% | ETA 27:15

[2180/5900] ✓ INOD: 8,800 рядків |  36.95% | ETA 27:13

[2190/5900] ✓ INTC: 23,704 рядків |  37.12% | ETA 27:12

[2200/5900] ✓ INVE: 804 рядків |  37.29% | ETA 27:10

   • RAM · 🧠 RAM: 850.1 MB

   ⏳ перед flush · 🧠 RAM: 850.1 MB

💾 batch 331 → 266,937 рядків (всього 7,214,524 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0331.csv.gz

   ✅ після flush · 🧠 RAM: 854.3 MB

[2210/5900] ✓ IONZ: 12,094 рядків |  37.46% | ETA 27:12

[2220/5900] ✓ IPDN: 2,348 рядків |  37.63% | ETA 27:10

[2230/5900] ✓ IPWR: 1,420 рядків |  37.80% | ETA 27:06

[2240/5900] ✓ IR: 7,102 рядків |  37.97% | ETA 27:01

[2250/5900] ✓ IREZ: 14,000 рядків |  38.14% | ETA 27:04

   • RAM · 🧠 RAM: 893.6 MB

   ⏳ перед flush · 🧠 RAM: 893.6 MB

💾 batch 332 → 285,138 рядків (всього 7,499,662 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0332.csv.gz

   ✅ після flush · 🧠 RAM: 895.8 MB

[2260/5900] ✓ ISOU: 2,073 рядків |  38.31% | ETA 27:00

[2270/5900] ✓ ITA: 8,338 рядків |  38.47% | ETA 26:58

[2280/5900] ✓ ITRG: 7,464 рядків |  38.64% | ETA 26:54

[2290/5900] ✓ IUSV: 6,503 рядків |  38.81% | ETA 26:52

[2300/5900] – IVPR: empty |  38.98% | ETA 26:49

   • RAM · 🧠 RAM: 920.0 MB

   ⏳ перед flush · 🧠 RAM: 920.0 MB

💾 batch 333 → 207,026 рядків (всього 7,706,688 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0333.csv.gz

   ✅ після flush · 🧠 RAM: 923.6 MB

[2310/5900] ✓ IWD: 7,214 рядків |  39.15% | ETA 26:49

[2320/5900] ✓ IWY: 6,785 рядків |  39.32% | ETA 26:49

[2330/5900] ✓ IYH: 6,491 рядків |  39.49% | ETA 26:48

[2340/5900] ✓ IZRL: 601 рядків |  39.66% | ETA 26:44

[2350/5900] ✓ JBDI: 1,559 рядків |  39.83% | ETA 26:42

   • RAM · 🧠 RAM: 957.6 MB

   ⏳ перед flush · 🧠 RAM: 957.6 MB

💾 batch 334 → 277,549 рядків (всього 7,984,237 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0334.csv.gz

   ✅ після flush · 🧠 RAM: 962.1 MB

[2360/5900] ✓ JBSS: 1,141 рядків |  40.00% | ETA 26:39

[2370/5900] ✓ JEF: 6,976 рядків |  40.17% | ETA 26:39

[2380/5900] ✓ JG: 165 рядків |  40.34% | ETA 26:37

[2390/5900] ✓ JLHL: 1,900 рядків |  40.51% | ETA 26:35

[2400/5900] ✓ JOBX: 5,826 рядків |  40.68% | ETA 26:34

   • RAM · 🧠 RAM: 985.8 MB

   ⏳ перед flush · 🧠 RAM: 985.8 MB

💾 batch 335 → 276,544 рядків (всього 8,260,781 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0335.csv.gz

   ✅ після flush · 🧠 RAM: 993.9 MB

[2410/5900] – JPX: empty |  40.85% | ETA 26:31

[2420/5900] ✓ JVA: 881 рядків |  41.02% | ETA 26:29

[2430/5900] ✓ KALU: 3,220 рядків |  41.19% | ETA 26:24

[2440/5900] ✓ KBAB: 524 рядків |  41.36% | ETA 26:18

[2450/5900] ✓ KDEF: 2,126 рядків |  41.53% | ETA 26:17

   • RAM · 🧠 RAM: 1,016.3 MB

   ⏳ перед flush · 🧠 RAM: 1,016.3 MB

💾 batch 336 → 202,720 рядків (всього 8,463,501 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0336.csv.gz

   ✅ після flush · 🧠 RAM: 1,019.5 MB

[2460/5900] ✓ KF: 1,540 рядків |  41.69% | ETA 26:13

[2470/5900] ✓ KINS: 2,250 рядків |  41.86% | ETA 26:12

[2480/5900] ✓ KLIP: 966 рядків |  42.03% | ETA 26:09

[2490/5900] ✓ KMI: 8,156 рядків |  42.20% | ETA 26:05

[2500/5900] ✓ KNOP: 1,285 рядків |  42.37% | ETA 26:02

   • RAM · 🧠 RAM: 983.7 MB

   ⏳ перед flush · 🧠 RAM: 983.7 MB

💾 batch 337 → 229,956 рядків (всього 8,693,457 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0337.csv.gz

   ✅ після flush · 🧠 RAM: 981.8 MB

[2510/5900] ✓ KOMP: 1,446 рядків |  42.54% | ETA 26:00

[2520/5900] ✓ KPRX: 785 рядків |  42.71% | ETA 25:57

[2530/5900] ✓ KRNT: 5,030 рядків |  42.88% | ETA 25:55

[2540/5900] ✓ KSCP: 4,076 рядків |  43.05% | ETA 25:51

[2550/5900] ✓ KTOS: 10,834 рядків |  43.22% | ETA 25:48

   • RAM · 🧠 RAM: 938.7 MB

   ⏳ перед flush · 🧠 RAM: 938.7 MB

💾 batch 338 → 257,834 рядків (всього 8,951,291 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0338.csv.gz

   ✅ після flush · 🧠 RAM: 937.5 MB

[2560/5900] ✓ KWEB: 11,111 рядків |  43.39% | ETA 25:46

[2570/5900] ✓ KYTX: 5,365 рядків |  43.56% | ETA 25:42

[2580/5900] ✓ LAKE: 1,823 рядків |  43.73% | ETA 25:41

[2590/5900] – LAZR: empty |  43.90% | ETA 25:38

[2600/5900] ✓ LBTYK: 5,842 рядків |  44.07% | ETA 25:34

   • RAM · 🧠 RAM: 891.9 MB

   ⏳ перед flush · 🧠 RAM: 891.9 MB

💾 batch 339 → 259,381 рядків (всього 9,210,672 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0339.csv.gz

   ✅ після flush · 🧠 RAM: 894.5 MB

[2610/5900] ✓ LDI: 6,977 рядків |  44.24% | ETA 25:31

[2620/5900] ✓ LENZ: 5,615 рядків |  44.41% | ETA 25:27

[2630/5900] ✓ LFT: 2,178 рядків |  44.58% | ETA 25:24

[2640/5900] ✓ LGND: 2,217 рядків |  44.75% | ETA 25:19

[2650/5900] ✓ LI: 9,025 рядків |  44.92% | ETA 25:16

   • RAM · 🧠 RAM: 911.4 MB

   ⏳ перед flush · 🧠 RAM: 911.4 MB

💾 batch 340 → 198,185 рядків (всього 9,408,857 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0340.csv.gz

   ✅ після flush · 🧠 RAM: 914.2 MB

[2660/5900] ✓ LINC: 3,795 рядків |  45.08% | ETA 25:14

[2670/5900] ✓ LITS: 2,562 рядків |  45.25% | ETA 25:10

[2680/5900] ✓ LLY: 11,593 рядків |  45.42% | ETA 25:06

[2690/5900] ✓ LMRI: 4,515 рядків |  45.59% | ETA 25:02

[2700/5900] ✓ LNKS: 2,574 рядків |  45.76% | ETA 24:57

   • RAM · 🧠 RAM: 941.3 MB

   ⏳ перед flush · 🧠 RAM: 941.3 MB

💾 batch 341 → 217,971 рядків (всього 9,626,828 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0341.csv.gz

   ✅ після flush · 🧠 RAM: 945.9 MB

[2710/5900] ✓ LOGI: 6,694 рядків |  45.93% | ETA 24:54

[2720/5900] ✓ LPG: 4,978 рядків |  46.10% | ETA 24:49

[2730/5900] ✓ LQDW: 1,032 рядків |  46.27% | ETA 24:46

[2740/5900] ✓ LSCC: 7,183 рядків |  46.44% | ETA 24:42

[2750/5900] ✓ LTPZ: 1,173 рядків |  46.61% | ETA 24:39

   • RAM · 🧠 RAM: 971.5 MB

   ⏳ перед flush · 🧠 RAM: 971.5 MB

💾 batch 342 → 208,797 рядків (всього 9,835,625 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0342.csv.gz

   ✅ після flush · 🧠 RAM: 975.5 MB

[2760/5900] ✓ LUMN: 9,017 рядків |  46.78% | ETA 24:35

[2770/5900] ✓ LVROF: 6,195 рядків |  46.95% | ETA 24:32

[2780/5900] ✓ LXRX: 7,036 рядків |  47.12% | ETA 24:29

[2790/5900] ✓ LZB: 4,355 рядків |  47.29% | ETA 24:26

[2800/5900] ✓ MAC: 6,638 рядків |  47.46% | ETA 24:22

   • RAM · 🧠 RAM: 1,004.3 MB

   ⏳ перед flush · 🧠 RAM: 1,004.3 MB

💾 batch 343 → 231,729 рядків (всього 10,067,354 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0343.csv.gz

   ✅ після flush · 🧠 RAM: 1,007.6 MB

[2810/5900] ✓ MAN: 6,623 рядків |  47.63% | ETA 24:19

[2820/5900] ✓ MAS: 7,088 рядків |  47.80% | ETA 24:16

[2830/5900] ✓ MAZE: 4,417 рядків |  47.97% | ETA 24:13

[2840/5900] ✓ MBUU: 2,837 рядків |  48.14% | ETA 24:09

[2850/5900] ✓ MCN: 965 рядків |  48.31% | ETA 24:06

   • RAM · 🧠 RAM: 1,038.5 MB

   ⏳ перед flush · 🧠 RAM: 1,038.5 MB

💾 batch 344 → 239,017 рядків (всього 10,306,371 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0344.csv.gz

   ✅ після flush · 🧠 RAM: 1,043.2 MB

[2860/5900] ✓ MD: 4,834 рядків |  48.47% | ETA 24:02

[2870/5900] ✓ MDWD: 1,768 рядків |  48.64% | ETA 23:59

[2880/5900] ✓ MEME: 3,511 рядків |  48.81% | ETA 23:55

[2890/5900] ✓ METL: 1,708 рядків |  48.98% | ETA 23:52

[2900/5900] ✓ MFSI: 3,423 рядків |  49.15% | ETA 23:49

   • RAM · 🧠 RAM: 1,071.5 MB

   ⏳ перед flush · 🧠 RAM: 1,071.5 MB

💾 batch 345 → 238,571 рядків (всього 10,544,942 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0345.csv.gz

   ✅ після flush · 🧠 RAM: 1,076.3 MB

[2910/5900] ✓ MGNX: 4,711 рядків |  49.32% | ETA 23:45

[2920/5900] ✓ MGY: 7,116 рядків |  49.49% | ETA 23:40

[2930/5900] ✓ MIGI: 1,868 рядків |  49.66% | ETA 23:36

[2940/5900] ✓ MITK: 5,604 рядків |  49.83% | ETA 23:32

[2950/5900] ✓ MKZR: 305 рядків |  50.00% | ETA 23:28

   • RAM · 🧠 RAM: 1,021.1 MB

   ⏳ перед flush · 🧠 RAM: 1,021.1 MB

💾 batch 346 → 182,348 рядків (всього 10,727,290 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0346.csv.gz

   ✅ після flush · 🧠 RAM: 1,020.2 MB

[2960/5900] ✓ MLPI: 4,619 рядків |  50.17% | ETA 23:24

[2970/5900] ✓ MMSI: 4,796 рядків |  50.34% | ETA 23:20

[2980/5900] ✓ MNRS: 286 рядків |  50.51% | ETA 23:16

[2990/5900] ✓ MOAT: 6,975 рядків |  50.68% | ETA 23:12

[3000/5900] ✓ MOGU: 471 рядків |  50.85% | ETA 23:08

   • RAM · 🧠 RAM: 969.5 MB

   ⏳ перед flush · 🧠 RAM: 969.5 MB

💾 batch 347 → 213,674 рядків (всього 10,940,964 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0347.csv.gz

   ✅ після flush · 🧠 RAM: 969.6 MB

[3010/5900] ✓ MPB: 2,202 рядків |  51.02% | ETA 23:05

[3020/5900] ✓ MPU: 1,228 рядків |  51.19% | ETA 23:00

[3030/5900] ✓ MRK: 8,746 рядків |  51.36% | ETA 22:57

[3040/5900] – MRUS: empty |  51.53% | ETA 22:52

[3050/5900] ✓ MSBI: 2,026 рядків |  51.69% | ETA 22:49

   • RAM · 🧠 RAM: 923.2 MB

   ⏳ перед flush · 🧠 RAM: 923.2 MB

💾 batch 348 → 251,874 рядків (всього 11,192,838 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0348.csv.gz

   ✅ після flush · 🧠 RAM: 927.7 MB

[3060/5900] ✓ MSFW: 766 рядків |  51.86% | ETA 22:46

[3070/5900] ✓ MSM: 4,794 рядків |  52.03% | ETA 22:42

[3080/5900] ✓ MSTR: 23,534 рядків |  52.20% | ETA 22:39

[3090/5900] ✓ MTBA: 3,232 рядків |  52.37% | ETA 22:38

[3100/5900] ✓ MTLS: 2,229 рядків |  52.54% | ETA 22:34

   • RAM · 🧠 RAM: 877.3 MB

   ⏳ перед flush · 🧠 RAM: 877.3 MB

💾 batch 349 → 309,625 рядків (всього 11,502,463 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0349.csv.gz

   ✅ після flush · 🧠 RAM: 878.2 MB

[3110/5900] ✓ MTZ: 5,650 рядків |  52.71% | ETA 22:30

[3120/5900] ✓ MUU: 16,975 рядків |  52.88% | ETA 22:28

[3130/5900] ✓ MWYN: 1,981 рядків |  53.05% | ETA 22:24

[3140/5900] ✓ MYRG: 2,672 рядків |  53.22% | ETA 22:19

[3150/5900] ✓ NAIL: 7,666 рядків |  53.39% | ETA 22:15

   • RAM · 🧠 RAM: 907.7 MB

   ⏳ перед flush · 🧠 RAM: 907.7 MB

💾 batch 350 → 236,463 рядків (всього 11,738,926 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0350.csv.gz

   ✅ після flush · 🧠 RAM: 913.0 MB

[3160/5900] ✓ NAT: 7,090 рядків |  53.56% | ETA 22:11

[3170/5900] ✓ NBIZ: 2,601 рядків |  53.73% | ETA 22:08

[3180/5900] ✓ NCEW: 191 рядків |  53.90% | ETA 22:03

[3190/5900] ✓ NCT: 1,444 рядків |  54.07% | ETA 21:59

[3200/5900] ✓ NEGG: 1,399 рядків |  54.24% | ETA 21:55

   • RAM · 🧠 RAM: 939.8 MB

   ⏳ перед flush · 🧠 RAM: 939.8 MB

💾 batch 351 → 226,364 рядків (всього 11,965,290 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0351.csv.gz

   ✅ після flush · 🧠 RAM: 944.2 MB

[3210/5900] ✓ NERD: 130 рядків |  54.41% | ETA 21:51

[3220/5900] ✓ NEWP: 6,424 рядків |  54.58% | ETA 21:46

[3230/5900] ✓ NFLU: 4,862 рядків |  54.75% | ETA 21:42

[3240/5900] ✓ NGG: 6,935 рядків |  54.92% | ETA 21:40

[3250/5900] ✓ NICE: 6,450 рядків |  55.08% | ETA 21:35

   • RAM · 🧠 RAM: 951.7 MB

   ⏳ перед flush · 🧠 RAM: 951.7 MB

💾 batch 352 → 236,598 рядків (всього 12,201,888 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0352.csv.gz

   ✅ після flush · 🧠 RAM: 953.9 MB

[3260/5900] ✓ NITO: 1,867 рядків |  55.25% | ETA 21:30

[3270/5900] ✓ NLR: 7,196 рядків |  55.42% | ETA 21:27

[3280/5900] ✓ NMRK: 6,316 рядків |  55.59% | ETA 21:23

[3290/5900] ✓ NNOX: 7,285 рядків |  55.76% | ETA 21:19

[3300/5900] ✓ NOTV: 4,360 рядків |  55.93% | ETA 21:15

   • RAM · 🧠 RAM: 904.5 MB

   ⏳ перед flush · 🧠 RAM: 904.5 MB

💾 batch 353 → 258,984 рядків (всього 12,460,872 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0353.csv.gz

   ✅ після flush · 🧠 RAM: 908.2 MB

[3310/5900] ✓ NPWR: 5,703 рядків |  56.10% | ETA 21:12

[3320/5900] ✓ NRIX: 5,808 рядків |  56.27% | ETA 21:07

[3330/5900] ✓ NSSC: 4,517 рядків |  56.44% | ETA 21:03

[3340/5900] ✓ NTRB: 312 рядків |  56.61% | ETA 20:59

[3350/5900] ✓ NUG: 151 рядків |  56.78% | ETA 20:55

   • RAM · 🧠 RAM: 863.4 MB

   ⏳ перед flush · 🧠 RAM: 863.4 MB

💾 batch 354 → 230,313 рядків (всього 12,691,185 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0354.csv.gz

   ✅ після flush · 🧠 RAM: 862.0 MB

[3360/5900] ✓ NUVL: 4,076 рядків |  56.95% | ETA 20:50

[3370/5900] ✓ NVDG: 4,559 рядків |  57.12% | ETA 20:48

[3380/5900] ✓ NVII: 2,467 рядків |  57.29% | ETA 20:45

[3390/5900] ✓ NVS: 7,705 рядків |  57.46% | ETA 20:41

[3400/5900] ✓ NWE: 5,413 рядків |  57.63% | ETA 20:37

   • RAM · 🧠 RAM: 820.7 MB

   ⏳ перед flush · 🧠 RAM: 820.7 MB

💾 batch 355 → 313,093 рядків (всього 13,004,278 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0355.csv.gz

   ✅ після flush · 🧠 RAM: 820.9 MB

[3410/5900] ✓ NWTG: 387 рядків |  57.80% | ETA 20:32

[3420/5900] ✓ NXTS: 6,422 рядків |  57.97% | ETA 20:28

[3430/5900] ✓ O: 12,581 рядків |  58.14% | ETA 20:24

[3440/5900] ✓ OC: 6,269 рядків |  58.31% | ETA 20:19

[3450/5900] – ODP: empty |  58.47% | ETA 20:15

   • RAM · 🧠 RAM: 789.8 MB

   ⏳ перед flush · 🧠 RAM: 789.8 MB

💾 batch 356 → 240,987 рядків (всього 13,245,265 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0356.csv.gz

   ✅ після flush · 🧠 RAM: 794.0 MB

[3460/5900] ✓ OGE: 6,449 рядків |  58.64% | ETA 20:10

[3470/5900] ✓ OILU: 4,270 рядків |  58.81% | ETA 20:07

[3480/5900] ✓ OLLI: 5,596 рядків |  58.98% | ETA 20:04

[3490/5900] ✓ OMER: 6,775 рядків |  59.15% | ETA 20:00

[3500/5900] ✓ ONDG: 5,894 рядків |  59.32% | ETA 19:56

   • RAM · 🧠 RAM: 757.7 MB

   ⏳ перед flush · 🧠 RAM: 757.7 MB

💾 batch 357 → 288,005 рядків (всього 13,533,270 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0357.csv.gz

   ✅ після flush · 🧠 RAM: 757.1 MB

[3510/5900] ✓ ONMD: 2,209 рядків |  59.49% | ETA 19:53

[3520/5900] ✓ OPENL: 3,232 рядків |  59.66% | ETA 19:48

[3530/5900] ✓ OPRT: 4,881 рядків |  59.83% | ETA 19:45

[3540/5900] ✓ ORC: 8,326 рядків |  60.00% | ETA 19:41

[3550/5900] ✓ ORIS: 1,735 рядків |  60.17% | ETA 19:37

   • RAM · 🧠 RAM: 762.7 MB

   ⏳ перед flush · 🧠 RAM: 762.7 MB

💾 batch 358 → 283,889 рядків (всього 13,817,159 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0358.csv.gz

   ✅ після flush · 🧠 RAM: 763.3 MB

[3560/5900] ✓ OS: 6,938 рядків |  60.34% | ETA 19:33

[3570/5900] ✓ OSUR: 3,953 рядків |  60.51% | ETA 19:29

[3580/5900] ✓ OUST: 7,823 рядків |  60.68% | ETA 19:25

[3590/5900] ✓ OZEM: 744 рядків |  60.85% | ETA 19:21

[3600/5900] ✓ PAG: 3,131 рядків |  61.02% | ETA 19:17

   • RAM · 🧠 RAM: 797.6 MB

   ⏳ перед flush · 🧠 RAM: 797.6 MB

💾 batch 359 → 265,881 рядків (всього 14,083,040 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0359.csv.gz

   ✅ після flush · 🧠 RAM: 801.6 MB

[3610/5900] ✓ PANG: 2,529 рядків |  61.19% | ETA 19:12

[3620/5900] ✓ PATH: 14,364 рядків |  61.36% | ETA 19:08

[3630/5900] ✓ PAYS: 3,787 рядків |  61.53% | ETA 19:04

[3640/5900] ✓ PBR: 9,681 рядків |  61.69% | ETA 19:00

[3650/5900] ✓ PCN: 3,503 рядків |  61.86% | ETA 18:55

   • RAM · 🧠 RAM: 834.0 MB

   ⏳ перед flush · 🧠 RAM: 834.0 MB

💾 batch 360 → 253,191 рядків (всього 14,336,231 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0360.csv.gz

   ✅ після flush · 🧠 RAM: 838.4 MB

[3660/5900] ✓ PDC: 977 рядків |  62.03% | ETA 18:51

[3670/5900] ✓ PDSB: 3,565 рядків |  62.20% | ETA 18:46

[3680/5900] ✓ PENG: 6,029 рядків |  62.37% | ETA 18:42

[3690/5900] ✓ PEW: 2,916 рядків |  62.54% | ETA 18:37

[3700/5900] ✓ PFIS: 2,020 рядків |  62.71% | ETA 18:33

   • RAM · 🧠 RAM: 865.0 MB

   ⏳ перед flush · 🧠 RAM: 865.0 MB

💾 batch 361 → 239,197 рядків (всього 14,575,428 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0361.csv.gz

   ✅ після flush · 🧠 RAM: 867.1 MB

[3710/5900] ✓ PGEN: 7,263 рядків |  62.88% | ETA 18:28

[3720/5900] ✓ PHG: 6,955 рядків |  63.05% | ETA 18:24

[3730/5900] ✓ PHVS: 1,767 рядків |  63.22% | ETA 18:19

[3740/5900] ✓ PINK: 2,324 рядків |  63.39% | ETA 18:14

[3750/5900] ✓ PLBC: 1,766 рядків |  63.56% | ETA 18:10

   • RAM · 🧠 RAM: 804.3 MB

   ⏳ перед flush · 🧠 RAM: 804.3 MB

💾 batch 362 → 255,601 рядків (всього 14,831,029 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0362.csv.gz

   ✅ після flush · 🧠 RAM: 798.1 MB

[3760/5900] ✓ PLRX: 4,162 рядків |  63.73% | ETA 18:06

[3770/5900] ✓ PLTR: 24,376 рядків |  63.90% | ETA 18:02

[3780/5900] ✓ PLXS: 3,603 рядків |  64.07% | ETA 17:58

[3790/5900] ✓ PMTS: 1,052 рядків |  64.24% | ETA 17:53

[3800/5900] ✓ PNRG: 834 рядків |  64.41% | ETA 17:48

   • RAM · 🧠 RAM: 627.6 MB

   ⏳ перед flush · 🧠 RAM: 627.6 MB

💾 batch 363 → 245,971 рядків (всього 15,077,000 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0363.csv.gz

   ✅ після flush · 🧠 RAM: 625.7 MB

[3810/5900] ✓ PONX: 658 рядків |  64.58% | ETA 17:43

[3820/5900] ✓ PPBT: 1,151 рядків |  64.75% | ETA 17:39

[3830/5900] ✓ PR: 7,406 рядків |  64.92% | ETA 17:35

[3840/5900] ✓ PRGO: 6,782 рядків |  65.08% | ETA 17:30

[3850/5900] ✓ PRME: 7,121 рядків |  65.25% | ETA 17:26

   • RAM · 🧠 RAM: 494.8 MB

   ⏳ перед flush · 🧠 RAM: 494.8 MB

💾 batch 364 → 246,268 рядків (всього 15,323,268 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0364.csv.gz

   ✅ після flush · 🧠 RAM: 497.3 MB

[3860/5900] ✓ PRT: 697 рядків |  65.42% | ETA 17:20

[3870/5900] ✓ PSEC: 7,897 рядків |  65.59% | ETA 17:16

[3880/5900] ✓ PSNY: 3,433 рядків |  65.76% | ETA 17:11

[3890/5900] ✓ PTC: 6,223 рядків |  65.93% | ETA 17:07

[3900/5900] ✓ PTNQ: 979 рядків |  66.10% | ETA 17:02

   • RAM · 🧠 RAM: 448.0 MB

   ⏳ перед flush · 🧠 RAM: 448.0 MB

💾 batch 365 → 225,567 рядків (всього 15,548,835 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0365.csv.gz

   ✅ після flush · 🧠 RAM: 449.8 MB

[3910/5900] ✓ PVAL: 22,149 рядків |  66.27% | ETA 16:58

[3920/5900] ✓ PXED: 1,440 рядків |  66.44% | ETA 16:53

[3930/5900] ✓ PZG: 7,875 рядків |  66.61% | ETA 16:49

[3940/5900] ✓ QCML: 1,925 рядків |  66.78% | ETA 16:44

[3950/5900] ✓ QFLR: 1,373 рядків |  66.95% | ETA 16:40

   • RAM · 🧠 RAM: 480.2 MB

   ⏳ перед flush · 🧠 RAM: 480.2 MB

💾 batch 366 → 263,937 рядків (всього 15,812,772 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0366.csv.gz

   ✅ після flush · 🧠 RAM: 486.2 MB

[3960/5900] ✓ QMCO: 5,750 рядків |  67.12% | ETA 16:36

[3970/5900] ✓ QQQE: 4,434 рядків |  67.29% | ETA 16:32

[3980/5900] ✓ QQUP: 336 рядків |  67.46% | ETA 16:27

[3990/5900] ✓ QTRX: 4,353 рядків |  67.63% | ETA 16:23

[4000/5900] ✓ QUSA: 357 рядків |  67.80% | ETA 16:18

   • RAM · 🧠 RAM: 522.9 MB

   ⏳ перед flush · 🧠 RAM: 522.9 MB

💾 batch 367 → 283,946 рядків (всього 16,096,718 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0367.csv.gz

   ✅ після flush · 🧠 RAM: 525.3 MB

[4010/5900] ✓ RACE: 7,841 рядків |  67.97% | ETA 16:13

[4020/5900] ✓ RAY: 596 рядків |  68.14% | ETA 16:08

[4030/5900] ✓ RC: 6,637 рядків |  68.31% | ETA 16:04

[4040/5900] ✓ RCT: 1,973 рядків |  68.47% | ETA 15:59

[4050/5900] ✓ RDTY: 383 рядків |  68.64% | ETA 15:54

   • RAM · 🧠 RAM: 533.1 MB

   ⏳ перед flush · 🧠 RAM: 533.1 MB

💾 batch 368 → 233,474 рядків (всього 16,330,192 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0368.csv.gz

   ✅ після flush · 🧠 RAM: 535.2 MB

[4060/5900] ✓ REAL: 7,139 рядків |  68.81% | ETA 15:50

[4070/5900] ✓ REK: 1,647 рядків |  68.98% | ETA 15:45

[4080/5900] ✓ REPL: 5,917 рядків |  69.15% | ETA 15:40

[4090/5900] ✓ REXR: 6,870 рядків |  69.32% | ETA 15:35

[4100/5900] ✓ RGEN: 5,593 рядків |  69.49% | ETA 15:30

   • RAM · 🧠 RAM: 435.0 MB

   ⏳ перед flush · 🧠 RAM: 435.0 MB

💾 batch 369 → 272,973 рядків (всього 16,603,165 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0369.csv.gz

   ✅ після flush · 🧠 RAM: 436.5 MB

[4110/5900] ✓ RGTZ: 14,784 рядків |  69.66% | ETA 15:26

[4120/5900] ✓ RILY: 4,839 рядків |  69.83% | ETA 15:22

[4130/5900] ✓ RIVN: 14,266 рядків |  70.00% | ETA 15:18

[4140/5900] ✓ RLI: 5,374 рядків |  70.17% | ETA 15:14

[4150/5900] ✓ RMD: 7,083 рядків |  70.34% | ETA 15:09

   • RAM · 🧠 RAM: 457.0 MB

   ⏳ перед flush · 🧠 RAM: 457.0 MB

💾 batch 370 → 321,664 рядків (всього 16,924,829 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0370.csv.gz

   ✅ після flush · 🧠 RAM: 460.1 MB

[4160/5900] ✓ RNR: 4,318 рядків |  70.51% | ETA 15:04

[4170/5900] ✓ ROCK: 3,109 рядків |  70.68% | ETA 14:59

[4180/5900] ✓ RONB: 4,112 рядків |  70.85% | ETA 14:54

[4190/5900] ✓ RPM: 5,894 рядків |  71.02% | ETA 14:49

[4200/5900] ✓ RS: 5,538 рядків |  71.19% | ETA 14:45

   • RAM · 🧠 RAM: 495.1 MB

   ⏳ перед flush · 🧠 RAM: 495.1 MB

💾 batch 371 → 272,652 рядків (всього 17,197,481 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0371.csv.gz

   ✅ після flush · 🧠 RAM: 498.7 MB

[4210/5900] ✓ RTAC: 1,181 рядків |  71.36% | ETA 14:40

[4220/5900] ✓ RVMD: 6,818 рядків |  71.53% | ETA 14:35

[4230/5900] ✓ RWM: 7,174 рядків |  71.69% | ETA 14:30

[4240/5900] ✓ RYDE: 947 рядків |  71.86% | ETA 14:26

[4250/5900] ✓ RZLV: 18,391 рядків |  72.03% | ETA 14:21

   • RAM · 🧠 RAM: 535.4 MB

   ⏳ перед flush · 🧠 RAM: 535.4 MB

💾 batch 372 → 266,856 рядків (всього 17,464,337 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0372.csv.gz

   ✅ після flush · 🧠 RAM: 537.3 MB

[4260/5900] ✓ SAIC: 5,756 рядків |  72.20% | ETA 14:16

[4270/5900] ✓ SARO: 6,984 рядків |  72.37% | ETA 14:11

[4280/5900] ✓ SBCF: 5,199 рядків |  72.54% | ETA 14:07

[4290/5900] ✓ SBIT: 15,789 рядків |  72.71% | ETA 14:02

[4300/5900] ✓ SCCR: 1,319 рядків |  72.88% | ETA 13:57

   • RAM · 🧠 RAM: 450.6 MB

   ⏳ перед flush · 🧠 RAM: 450.6 MB

💾 batch 373 → 247,842 рядків (всього 17,712,179 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0373.csv.gz

   ✅ після flush · 🧠 RAM: 457.5 MB

[4310/5900] ✓ SCHJ: 6,846 рядків |  73.05% | ETA 13:53

[4320/5900] ✓ SCHX: 7,748 рядків |  73.22% | ETA 13:48

[4330/5900] ✓ SCNI: 506 рядків |  73.39% | ETA 13:43

[4340/5900] ✓ SCZM: 5,118 рядків |  73.56% | ETA 13:38

[4350/5900] ✓ SDST: 1,548 рядків |  73.73% | ETA 13:33

   • RAM · 🧠 RAM: 434.3 MB

   ⏳ перед flush · 🧠 RAM: 434.3 MB

💾 batch 374 → 270,037 рядків (всього 17,982,216 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0374.csv.gz

   ✅ після flush · 🧠 RAM: 437.5 MB

[4360/5900] ✓ SEER: 2,484 рядків |  73.90% | ETA 13:28

[4370/5900] ✓ SEPN: 3,516 рядків |  74.07% | ETA 13:23

[4380/5900] ✓ SF: 6,213 рядків |  74.24% | ETA 13:18

[4390/5900] ✓ SFY: 525 рядків |  74.41% | ETA 13:13

[4400/5900] ✓ SGLY: 752 рядків |  74.58% | ETA 13:07

   • RAM · 🧠 RAM: 460.1 MB

   ⏳ перед flush · 🧠 RAM: 460.1 MB

💾 batch 375 → 203,339 рядків (всього 18,185,555 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0375.csv.gz

   ✅ після flush · 🧠 RAM: 463.1 MB

[4410/5900] ✓ SGOV: 22,262 рядків |  74.75% | ETA 13:03

[4420/5900] ✓ SHG: 3,746 рядків |  74.92% | ETA 12:58

[4430/5900] ✓ SHPD: 474 рядків |  75.08% | ETA 12:53

[4440/5900] ✓ SIFY: 1,414 рядків |  75.25% | ETA 12:49

[4450/5900] ✓ SINT: 810 рядків |  75.42% | ETA 12:44

   • RAM · 🧠 RAM: 506.8 MB

   ⏳ перед flush · 🧠 RAM: 506.8 MB

💾 batch 376 → 310,875 рядків (всього 18,496,430 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0376.csv.gz

   ✅ після flush · 🧠 RAM: 508.4 MB

[4460/5900] ✓ SIVR: 17,083 рядків |  75.59% | ETA 12:39

[4470/5900] ✓ SKRE: 2,345 рядків |  75.76% | ETA 12:34

[4480/5900] ✓ SKYY: 5,052 рядків |  75.93% | ETA 12:29

[4490/5900] ✓ SLG: 6,425 рядків |  76.10% | ETA 12:24

[4500/5900] ✓ SLNO: 6,151 рядків |  76.27% | ETA 12:19

   • RAM · 🧠 RAM: 482.2 MB

   ⏳ перед flush · 🧠 RAM: 482.2 MB

💾 batch 377 → 237,240 рядків (всього 18,733,670 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0377.csv.gz

   ✅ після flush · 🧠 RAM: 484.2 MB

[4510/5900] ✓ SLS: 9,344 рядків |  76.44% | ETA 12:14

[4520/5900] ✓ SLYV: 3,914 рядків |  76.61% | ETA 12:09

[4530/5900] ✓ SMCZ: 3,754 рядків |  76.78% | ETA 12:05

[4540/5900] – SMLR: empty |  76.95% | ETA 12:00

[4550/5900] ✓ SMTI: 1,589 рядків |  77.12% | ETA 11:55

   • RAM · 🧠 RAM: 423.3 MB

   ⏳ перед flush · 🧠 RAM: 423.3 MB

💾 batch 378 → 269,130 рядків (всього 19,002,800 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0378.csv.gz

   ✅ після flush · 🧠 RAM: 430.8 MB

[4560/5900] ✓ SNA: 5,666 рядків |  77.29% | ETA 11:50

[4570/5900] ✓ SNDR: 5,942 рядків |  77.46% | ETA 11:46

[4580/5900] ✓ SNOW: 10,335 рядків |  77.63% | ETA 11:41

[4590/5900] ✓ SNX: 5,085 рядків |  77.80% | ETA 11:35

[4600/5900] ✓ SOC: 7,772 рядків |  77.97% | ETA 11:30

   • RAM · 🧠 RAM: 459.3 MB

   ⏳ перед flush · 🧠 RAM: 459.3 MB

💾 batch 379 → 252,992 рядків (всього 19,255,792 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0379.csv.gz

   ✅ після flush · 🧠 RAM: 461.8 MB

[4610/5900] ✓ SOLT: 20,038 рядків |  78.14% | ETA 11:25

[4620/5900] ✓ SORA: 1,298 рядків |  78.31% | ETA 11:20

[4630/5900] ✓ SOXY: 544 рядків |  78.47% | ETA 11:16

[4640/5900] ✓ SPDW: 7,138 рядків |  78.64% | ETA 11:11

[4650/5900] ✓ SPHD: 7,284 рядків |  78.81% | ETA 11:05

   • RAM · 🧠 RAM: 497.4 MB

   ⏳ перед flush · 🧠 RAM: 497.4 MB

💾 batch 380 → 286,755 рядків (всього 19,542,547 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0380.csv.gz

   ✅ після flush · 🧠 RAM: 501.9 MB

[4660/5900] ✓ SPMD: 7,037 рядків |  78.98% | ETA 11:01

[4670/5900] ✓ SPRB: 1,287 рядків |  79.15% | ETA 10:55

[4680/5900] ✓ SPSM: 7,000 рядків |  79.32% | ETA 10:50

[4690/5900] ✓ SPWO: 1,578 рядків |  79.49% | ETA 10:45

[4700/5900] ✓ SPYQ: 59 рядків |  79.66% | ETA 10:41

   • RAM · 🧠 RAM: 508.1 MB

   ⏳ перед flush · 🧠 RAM: 508.1 MB

💾 batch 381 → 273,620 рядків (всього 19,816,167 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0381.csv.gz

   ✅ після flush · 🧠 RAM: 508.9 MB

[4710/5900] ✓ SRAD: 6,630 рядків |  79.83% | ETA 10:36

[4720/5900] ✓ SRTA: 5,427 рядків |  80.00% | ETA 10:31

[4730/5900] ✓ SSII: 1,924 рядків |  80.17% | ETA 10:25

[4740/5900] ✓ SSTI: 3,023 рядків |  80.34% | ETA 10:20

[4750/5900] – STEC: empty |  80.51% | ETA 10:15

   • RAM · 🧠 RAM: 430.1 MB

   ⏳ перед flush · 🧠 RAM: 430.1 MB

💾 batch 382 → 256,837 рядків (всього 20,073,004 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0382.csv.gz

   ✅ після flush · 🧠 RAM: 435.4 MB

[4760/5900] ✓ STK: 1,374 рядків |  80.68% | ETA 10:10

[4770/5900] ✓ STRA: 2,724 рядків |  80.85% | ETA 10:05

[4780/5900] ✓ STSS: 3,431 рядків |  81.02% | ETA 10:00

[4790/5900] ✓ SUGP: 603 рядків |  81.19% | ETA 09:55

[4800/5900] ✓ SUPV: 5,925 рядків |  81.36% | ETA 09:49

   • RAM · 🧠 RAM: 472.6 MB

   ⏳ перед flush · 🧠 RAM: 472.6 MB

💾 batch 383 → 274,279 рядків (всього 20,347,283 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0383.csv.gz

   ✅ після flush · 🧠 RAM: 474.1 MB

[4810/5900] ✓ SVRA: 6,231 рядків |  81.53% | ETA 09:44

[4820/5900] ✓ SWKS: 7,516 рядків |  81.69% | ETA 09:39

[4830/5900] ✓ SYF: 7,158 рядків |  81.86% | ETA 09:34

[4840/5900] – TAIT: empty |  82.03% | ETA 09:29

[4850/5900] ✓ TAP: 7,202 рядків |  82.20% | ETA 09:24

   • RAM · 🧠 RAM: 507.2 MB

   ⏳ перед flush · 🧠 RAM: 507.2 MB

💾 batch 384 → 248,824 рядків (всього 20,596,107 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0384.csv.gz

   ✅ після flush · 🧠 RAM: 510.3 MB

[4860/5900] ✓ TBH: 1,333 рядків |  82.37% | ETA 09:18

[4870/5900] ✓ TCBK: 1,851 рядків |  82.54% | ETA 09:13

[4880/5900] ✓ TDAQ: 2,775 рядків |  82.71% | ETA 09:08

[4890/5900] ✓ TDTH: 4,157 рядків |  82.88% | ETA 09:02

[4900/5900] ✓ TECK: 8,008 рядків |  83.05% | ETA 08:58

   • RAM · 🧠 RAM: 536.0 MB

   ⏳ перед flush · 🧠 RAM: 536.0 MB

💾 batch 385 → 212,677 рядків (всього 20,808,784 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0385.csv.gz

   ✅ після flush · 🧠 RAM: 539.6 MB

[4910/5900] ✓ TEMT: 6,900 рядків |  83.22% | ETA 08:52

[4920/5900] ✓ TERN: 6,715 рядків |  83.39% | ETA 08:47

[4930/5900] ✓ TGE: 868 рядків |  83.56% | ETA 08:42

[4940/5900] ✓ TH: 3,694 рядків |  83.73% | ETA 08:37

[4950/5900] ✓ THR: 4,838 рядків |  83.90% | ETA 08:31

   • RAM · 🧠 RAM: 441.7 MB

   ⏳ перед flush · 🧠 RAM: 441.7 MB

💾 batch 386 → 237,515 рядків (всього 21,046,299 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0386.csv.gz

   ✅ після flush · 🧠 RAM: 446.8 MB

[4960/5900] ✓ TILE: 3,979 рядків |  84.07% | ETA 08:26

[4970/5900] ✓ TKC: 5,060 рядків |  84.24% | ETA 08:21

[4980/5900] ✓ TLRY: 8,125 рядків |  84.41% | ETA 08:16

[4990/5900] ✓ TMC: 10,890 рядків |  84.58% | ETA 08:11

[5000/5900] ✓ TMQ: 10,136 рядків |  84.75% | ETA 08:06

   • RAM · 🧠 RAM: 441.7 MB

   ⏳ перед flush · 🧠 RAM: 441.7 MB

💾 batch 387 → 268,959 рядків (всього 21,315,258 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0387.csv.gz

   ✅ після flush · 🧠 RAM: 444.9 MB

[5010/5900] ✓ TNXP: 4,679 рядків |  84.92% | ETA 08:01

[5020/5900] ✓ TOPT: 5,135 рядків |  85.08% | ETA 07:55

[5030/5900] ✓ TPC: 4,693 рядків |  85.25% | ETA 07:50

[5040/5900] ✓ TRAK: 1,887 рядків |  85.42% | ETA 07:45

[5050/5900] ✓ TRIN: 6,952 рядків |  85.59% | ETA 07:40

   • RAM · 🧠 RAM: 478.3 MB

   ⏳ перед flush · 🧠 RAM: 478.3 MB

💾 batch 388 → 252,267 рядків (всього 21,567,525 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0388.csv.gz

   ✅ після flush · 🧠 RAM: 481.5 MB

[5060/5900] ✓ TROO: 3,186 рядків |  85.76% | ETA 07:34

[5070/5900] ✓ TRUP: 4,795 рядків |  85.93% | ETA 07:29

[5080/5900] ✓ TSES: 1,163 рядків |  86.10% | ETA 07:24

[5090/5900] ✓ TSLL: 25,346 рядків |  86.27% | ETA 07:19

[5100/5900] ✓ TSMG: 2,689 рядків |  86.44% | ETA 07:14

   • RAM · 🧠 RAM: 523.8 MB

   ⏳ перед flush · 🧠 RAM: 523.8 MB

💾 batch 389 → 325,535 рядків (всього 21,893,060 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0389.csv.gz

   ✅ після flush · 🧠 RAM: 527.3 MB

[5110/5900] ✓ TSQ: 2,232 рядків |  86.61% | ETA 07:09

[5120/5900] ✓ TTC: 5,243 рядків |  86.78% | ETA 07:03

[5130/5900] – TTSH: empty |  86.95% | ETA 06:58

[5140/5900] ✓ TV: 5,757 рядків |  87.12% | ETA 06:53

[5150/5900] ✓ TWNP: 3,097 рядків |  87.29% | ETA 06:47

   • RAM · 🧠 RAM: 454.3 MB

   ⏳ перед flush · 🧠 RAM: 454.3 MB

💾 batch 390 → 224,098 рядків (всього 22,117,158 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0390.csv.gz

   ✅ після flush · 🧠 RAM: 458.2 MB

[5160/5900] ✓ TXRH: 5,959 рядків |  87.46% | ETA 06:42

[5170/5900] ✓ TZA: 12,440 рядків |  87.63% | ETA 06:37

[5180/5900] ✓ UAVS: 6,918 рядків |  87.80% | ETA 06:32

[5190/5900] ✓ UCAR: 751 рядків |  87.97% | ETA 06:26

[5200/5900] ✓ UEIC: 967 рядків |  88.14% | ETA 06:21

   • RAM · 🧠 RAM: 437.1 MB

   ⏳ перед flush · 🧠 RAM: 437.1 MB

💾 batch 391 → 254,416 рядків (всього 22,371,574 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0391.csv.gz

   ✅ після flush · 🧠 RAM: 441.6 MB

[5210/5900] ✓ UGE: 1,165 рядків |  88.31% | ETA 06:15

[5220/5900] ✓ UIS: 5,905 рядків |  88.47% | ETA 06:10

[5230/5900] ✓ UMBF: 4,758 рядків |  88.64% | ETA 06:05

[5240/5900] ✓ UNHW: 289 рядків |  88.81% | ETA 06:00

[5250/5900] ✓ UONEK: 169 рядків |  88.98% | ETA 05:54

   • RAM · 🧠 RAM: 472.8 MB

   ⏳ перед flush · 🧠 RAM: 472.8 MB

💾 batch 392 → 253,840 рядків (всього 22,625,414 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0392.csv.gz

   ✅ після flush · 🧠 RAM: 476.6 MB

[5260/5900] ✓ UPST: 10,676 рядків |  89.15% | ETA 05:49

[5270/5900] ✓ URNJ: 5,404 рядків |  89.32% | ETA 05:44

[5280/5900] ✓ USAU: 4,323 рядків |  89.49% | ETA 05:39

[5290/5900] ✓ USG: 129 рядків |  89.66% | ETA 05:33

[5300/5900] ✓ USNA: 1,951 рядків |  89.83% | ETA 05:28

   • RAM · 🧠 RAM: 509.7 MB

   ⏳ перед flush · 🧠 RAM: 509.7 MB

💾 batch 393 → 264,568 рядків (всього 22,889,982 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0393.csv.gz

   ✅ після flush · 🧠 RAM: 515.2 MB

[5310/5900] ✓ UTF: 4,620 рядків |  90.00% | ETA 05:22

[5320/5900] ✓ UUUG: 4,671 рядків |  90.17% | ETA 05:17

[5330/5900] ✓ UYG: 499 рядків |  90.34% | ETA 05:12

[5340/5900] ✓ VAW: 2,225 рядків |  90.51% | ETA 05:06

[5350/5900] ✓ VCR: 2,417 рядків |  90.68% | ETA 05:01

   • RAM · 🧠 RAM: 479.4 MB

   ⏳ перед flush · 🧠 RAM: 479.4 MB

💾 batch 394 → 244,687 рядків (всього 23,134,669 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0394.csv.gz

   ✅ після flush · 🧠 RAM: 482.5 MB

[5360/5900] ✓ VECO: 6,000 рядків |  90.85% | ETA 04:55

[5370/5900] ✓ VERO: 2,366 рядків |  91.02% | ETA 04:50

[5380/5900] ✓ VGIT: 7,221 рядків |  91.19% | ETA 04:45

[5390/5900] ✓ VIAV: 8,057 рядків |  91.36% | ETA 04:39

[5400/5900] ✓ VIR: 8,337 рядків |  91.53% | ETA 04:34

   • RAM · 🧠 RAM: 437.2 MB

   ⏳ перед flush · 🧠 RAM: 437.2 MB

💾 batch 395 → 287,021 рядків (всього 23,421,690 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0395.csv.gz

   ✅ після flush · 🧠 RAM: 439.7 MB

[5410/5900] ✓ VIXM: 2,804 рядків |  91.69% | ETA 04:29

[5420/5900] ✓ VMBS: 6,525 рядків |  91.86% | ETA 04:23

[5430/5900] ✓ VNOM: 7,188 рядків |  92.03% | ETA 04:18

[5440/5900] ✓ VOLT: 3,870 рядків |  92.20% | ETA 04:12

[5450/5900] ✓ VOYA: 5,770 рядків |  92.37% | ETA 04:07

   • RAM · 🧠 RAM: 477.3 MB

   ⏳ перед flush · 🧠 RAM: 477.3 MB

💾 batch 396 → 278,929 рядків (всього 23,700,619 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0396.csv.gz

   ✅ після flush · 🧠 RAM: 479.9 MB

[5460/5900] ✓ VRCA: 2,078 рядків |  92.54% | ETA 04:02

[5470/5900] ✓ VRSK: 7,337 рядків |  92.71% | ETA 03:56

[5480/5900] ✓ VSEE: 2,973 рядків |  92.88% | ETA 03:51

[5490/5900] ✓ VST: 10,800 рядків |  93.05% | ETA 03:45

[5500/5900] ✓ VTI: 10,776 рядків |  93.22% | ETA 03:40

   • RAM · 🧠 RAM: 511.6 MB

   ⏳ перед flush · 🧠 RAM: 511.6 MB

💾 batch 397 → 245,334 рядків (всього 23,945,953 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0397.csv.gz

   ✅ після flush · 🧠 RAM: 515.2 MB

[5510/5900] ✓ VTWO: 7,779 рядків |  93.39% | ETA 03:34

[5520/5900] ✓ VVV: 6,789 рядків |  93.56% | ETA 03:29

[5530/5900] ✓ VYNE: 1,910 рядків |  93.73% | ETA 03:24

[5540/5900] ✓ WAI: 397 рядків |  93.90% | ETA 03:18

[5550/5900] ✓ WBI: 5,117 рядків |  94.07% | ETA 03:13

   • RAM · 🧠 RAM: 502.3 MB

   ⏳ перед flush · 🧠 RAM: 502.3 MB

💾 batch 398 → 257,009 рядків (всього 24,202,962 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0398.csv.gz

   ✅ після flush · 🧠 RAM: 505.1 MB

[5560/5900] ✓ WCT: 1,726 рядків |  94.24% | ETA 03:07

[5570/5900] ✓ WDTE: 678 рядків |  94.41% | ETA 03:02

[5580/5900] ✓ WELL: 7,096 рядків |  94.58% | ETA 02:56

[5590/5900] ✓ WFG: 3,732 рядків |  94.75% | ETA 02:51

[5600/5900] ✓ WHR: 7,049 рядків |  94.92% | ETA 02:45

   • RAM · 🧠 RAM: 431.1 MB

   ⏳ перед flush · 🧠 RAM: 431.1 MB

💾 batch 399 → 223,872 рядків (всього 24,426,834 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0399.csv.gz

   ✅ після flush · 🧠 RAM: 434.1 MB

[5610/5900] ✓ WKC: 5,040 рядків |  95.08% | ETA 02:40

[5620/5900] ✓ WLK: 6,326 рядків |  95.25% | ETA 02:34

[5630/5900] ✓ WNEB: 4,147 рядків |  95.42% | ETA 02:29

[5640/5900] ✓ WPP: 5,795 рядків |  95.59% | ETA 02:23

[5650/5900] ✓ WSBC: 4,308 рядків |  95.76% | ETA 02:18

   • RAM · 🧠 RAM: 462.5 MB

   ⏳ перед flush · 🧠 RAM: 462.5 MB

💾 batch 400 → 221,763 рядків (всього 24,648,597 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0400.csv.gz

   ✅ після flush · 🧠 RAM: 466.5 MB

[5660/5900] ✓ WTBA: 2,684 рядків |  95.93% | ETA 02:12

[5670/5900] ✓ WTRG: 6,936 рядків |  96.10% | ETA 02:07

[5680/5900] ✓ WWR: 6,261 рядків |  96.27% | ETA 02:01

[5690/5900] ✓ XBCI: 640 рядків |  96.44% | ETA 01:56

[5700/5900] ✓ XCUR: 973 рядків |  96.61% | ETA 01:50

   • RAM · 🧠 RAM: 491.4 MB

   ⏳ перед flush · 🧠 RAM: 491.4 MB

💾 batch 401 → 197,573 рядків (всього 24,846,170 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0401.csv.gz

   ✅ після flush · 🧠 RAM: 494.7 MB

[5710/5900] ✓ XHG: 199 рядків |  96.78% | ETA 01:45

[5720/5900] ✓ XLF: 11,394 рядків |  96.95% | ETA 01:39

[5730/5900] ✓ XMAG: 1,330 рядків |  97.12% | ETA 01:34

[5740/5900] ✓ XOM: 12,869 рядків |  97.29% | ETA 01:28

[5750/5900] ✓ XPH: 1,436 рядків |  97.46% | ETA 01:23

   • RAM · 🧠 RAM: 528.1 MB

   ⏳ перед flush · 🧠 RAM: 528.1 MB

💾 batch 402 → 260,055 рядків (всього 25,106,225 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0402.csv.gz

   ✅ після flush · 🧠 RAM: 531.1 MB

[5760/5900] ✓ XRAY: 7,234 рядків |  97.63% | ETA 01:17

[5770/5900] ✓ XRTX: 1,964 рядків |  97.80% | ETA 01:12

[5780/5900] ✓ XTIA: 6,499 рядків |  97.97% | ETA 01:06

[5790/5900] ✓ XXI: 6,791 рядків |  98.14% | ETA 01:00

[5800/5900] ✓ YAAS: 687 рядків |  98.31% | ETA 00:55

   • RAM · 🧠 RAM: 441.5 MB

   ⏳ перед flush · 🧠 RAM: 441.5 MB

💾 batch 403 → 213,321 рядків (всього 25,319,546 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0403.csv.gz

   ✅ після flush · 🧠 RAM: 446.1 MB

[5810/5900] ✓ YCL: 1,298 рядків |  98.47% | ETA 00:49

[5820/5900] – YGMZF: empty |  98.64% | ETA 00:44

[5830/5900] ✓ YOLO: 953 рядків |  98.81% | ETA 00:38

[5840/5900] ✓ YSS: 7,888 рядків |  98.98% | ETA 00:33

[5850/5900] ✓ ZBAI: 119 рядків |  99.15% | ETA 00:27

   • RAM · 🧠 RAM: 429.4 MB

   ⏳ перед flush · 🧠 RAM: 429.4 MB

💾 batch 404 → 161,298 рядків (всього 25,480,844 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0404.csv.gz

   ✅ після flush · 🧠 RAM: 431.5 MB

[5860/5900] ✓ ZEO: 2,064 рядків |  99.32% | ETA 00:22

[5870/5900] ✓ ZIM: 8,776 рядків |  99.49% | ETA 00:16

[5880/5900] ✓ ZNTL: 4,951 рядків |  99.66% | ETA 00:11

[5890/5900] ✓ ZTS: 7,315 рядків |  99.83% | ETA 00:05

[5900/5900] ✓ ZYME: 6,282 рядків | 100.00% | ETA 00:00

   • RAM · 🧠 RAM: 463.2 MB

   ⏳ перед flush · 🧠 RAM: 463.2 MB

💾 batch 405 → 224,404 рядків (всього 25,705,248 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_0405.csv.gz

   ✅ після flush · 🧠 RAM: 465.5 MB

   🔚 фінал · 🧠 RAM: 465.5 MB

🏁 Готово. Нових рядків: 25,705,248 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 54:32

In [20]:
import os, glob, gc, time
from typing import Optional

import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str   = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    aggregate: bool = False,            # False → всі рядки, True → агрегація по (ticker,date)
    chunksize: int = 200_000,           # якщо мало RAM — ще зменш
    compression: str = "snappy",
    log_every: int = 5,
    sort_chunk: bool = True,            # sort within each chunk (ticker,dt)
):
    """
    Проходить по {folder}/{pattern}, фільтрує рядки:
      - за часовим вікном [start_time..end_time] по підрядку часу в 'dt'
      - опційно за датою [date_min..date_max] по підрядку дати в 'dt'
    і стрімово пише у один Parquet.

    Очікувані колонки у CSV: 'ticker','dt','o','h','l','c','v'.
    dt має формат 'YYYY-MM-DD HH:MM:SS' (string).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    # normalize dates (string compare works for YYYY-MM-DD)
    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    # читаємо тільки потрібне, даємо вузькі типи
    usecols = ["ticker", "dt", "o", "h", "l", "c", "v"]
    dtypes = {
        "ticker": "string",
        "dt": "string",         # важливо: фільтруємо по підрядку, без datetime-парсингу
        "o": "float32",
        "h": "float32",
        "l": "float32",
        "c": "float32",
        "v": "float32",
    }

    # підготовка виходу
    if os.path.exists(out_path):
        os.remove(out_path)
    writer = None

    t0 = time.time()
    total_in = total_out = 0
    file_idx = 0

    rng_str = ""
    if date_min or date_max:
        rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]"
    print(f"▶️ START: {folder}/{pattern} → {out_path}  chunksize={chunksize:,}{rng_str}")

    try:
        for path in files:
            file_idx += 1
            chunk_idx = 0

            reader = pd.read_csv(
                path,
                compression="infer",
                usecols=usecols,
                dtype=dtypes,
                chunksize=chunksize,
                low_memory=True,
                # engine="pyarrow",
            )

            for chunk in reader:
                chunk_idx += 1
                total_in += len(chunk)

                # швидке фільтрування по часу: 'YYYY-MM-DD HH:MM:SS'
                t = chunk["dt"].str.slice(11, 19)
                mask = (t >= start_time) & (t <= end_time)

                # фільтр по даті, також строками
                if date_min is not None or date_max is not None:
                    d = chunk["dt"].str.slice(0, 10)
                    if date_min is not None:
                        mask &= (d >= date_min)
                    if date_max is not None:
                        mask &= (d <= date_max)

                cut = chunk.loc[mask].copy()

                if cut.empty:
                    del chunk, t, mask, cut
                    gc.collect()
                    continue

                if aggregate:
                    # дата як рядок 'YYYY-MM-DD'
                    cut["date"] = cut["dt"].str.slice(0, 10)
                    # сорт для стабільності
                    if sort_chunk and {"ticker", "date"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "date"], kind="mergesort")
                    grp = (cut.groupby(["ticker", "date"], as_index=False, observed=True)
                              .agg({"v": "sum"}))  # приклад: сума обсягу; змінюй агрегацію за потреби
                    out_df = grp
                else:
                    # стабільний порядок в межах чанка
                    if sort_chunk and {"ticker", "dt"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "dt"], kind="mergesort")
                    out_df = cut

                table = pa.Table.from_pandas(out_df, preserve_index=False)
                if writer is None:
                    writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
                writer.write_table(table)
                total_out += len(out_df)

                if (chunk_idx % log_every) == 0:
                    elapsed = time.time() - t0
                    print(f"  [{file_idx}/{len(files)}] {os.path.basename(path)} "
                          f"chunk {chunk_idx}  in={total_in:,}  out={total_out:,}  "
                          f"elapsed={elapsed:,.1f}s")

                del chunk, t, mask, cut, out_df, table
                gc.collect()

    finally:
        if writer is not None:
            writer.close()

    print(f"✅ DONE  in={total_in:,} → out={total_out:,}  to {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [21]:
collect_premarket_by_day_stream(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,      # NEW
    date_max=end_date_str,        # NEW
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  chunksize=150,000  date=[2025-11-25..2026-02-25]

  [1/405] intraday_0001.csv.gz chunk 5  in=750,000  out=494,905  elapsed=1.8s

  [2/405] intraday_0002.csv.gz chunk 5  in=1,725,827  out=1,161,736  elapsed=3.9s

  [3/405] intraday_0003.csv.gz chunk 5  in=2,590,424  out=1,758,411  elapsed=5.6s

  [4/405] intraday_0004.csv.gz chunk 5  in=3,333,452  out=2,265,560  elapsed=7.1s

  [5/405] intraday_0005.csv.gz chunk 5  in=4,083,452  out=2,767,474  elapsed=9.0s

  [6/405] intraday_0006.csv.gz chunk 5  in=4,957,443  out=3,348,264  elapsed=11.4s

  [7/405] intraday_0007.csv.gz chunk 5  in=5,912,526  out=3,982,581  elapsed=13.8s

  [8/405] intraday_0008.csv.gz chunk 5  in=6,673,107  out=4,490,498  elapsed=15.8s

  [9/405] intraday_0009.csv.gz chunk 5  in=7,482,671  out=5,023,329  elapsed=17.9s

  [10/405] intraday_0010.csv.gz chunk 5  in=8,422,497  out=5,660,567  elapsed=20.3s

  [11/405] intraday_0011.csv.gz chunk 5  in=9,348,724  out=6,309,064  elapsed=22.8s

  [12/405] intraday_0012.csv.gz chunk 5  in=10,098,724  out=6,824,971  elapsed=24.7s

  [13/405] intraday_0013.csv.gz chunk 5  in=10,952,410  out=7,394,639  elapsed=26.9s

  [14/405] intraday_0014.csv.gz chunk 5  in=11,729,573  out=7,924,518  elapsed=28.9s

  [15/405] intraday_0015.csv.gz chunk 5  in=12,333,647  out=8,335,636  elapsed=30.4s

  [16/405] intraday_0016.csv.gz chunk 5  in=13,083,647  out=8,833,012  elapsed=32.4s

  [17/405] intraday_0017.csv.gz chunk 5  in=14,119,434  out=9,507,523  elapsed=35.1s

  [18/405] intraday_0018.csv.gz chunk 5  in=14,987,474  out=10,127,910  elapsed=37.5s

  [19/405] intraday_0019.csv.gz chunk 5  in=15,723,943  out=10,612,780  elapsed=39.4s

  [20/405] intraday_0020.csv.gz chunk 5  in=16,473,943  out=11,102,382  elapsed=41.3s

  [21/405] intraday_0021.csv.gz chunk 5  in=17,305,781  out=11,662,129  elapsed=43.4s

  [22/405] intraday_0022.csv.gz chunk 5  in=18,114,555  out=12,205,687  elapsed=45.5s

  [23/405] intraday_0023.csv.gz chunk 5  in=18,864,555  out=12,699,614  elapsed=47.4s

  [24/405] intraday_0024.csv.gz chunk 5  in=19,645,557  out=13,237,712  elapsed=49.4s

  [25/405] intraday_0025.csv.gz chunk 5  in=20,416,242  out=13,748,744  elapsed=51.4s

  [26/405] intraday_0026.csv.gz chunk 5  in=21,166,242  out=14,235,227  elapsed=53.3s

  [27/405] intraday_0027.csv.gz chunk 5  in=21,935,669  out=14,757,029  elapsed=55.2s

  [28/405] intraday_0028.csv.gz chunk 5  in=22,685,669  out=15,262,441  elapsed=57.2s

  [29/405] intraday_0029.csv.gz chunk 5  in=23,693,087  out=15,947,534  elapsed=59.8s

  [30/405] intraday_0030.csv.gz chunk 5  in=24,639,604  out=16,580,327  elapsed=62.2s

  [31/405] intraday_0031.csv.gz chunk 5  in=25,543,444  out=17,186,950  elapsed=64.8s

  [32/405] intraday_0032.csv.gz chunk 5  in=26,293,444  out=17,684,738  elapsed=66.6s

  [33/405] intraday_0033.csv.gz chunk 5  in=27,109,346  out=18,222,251  elapsed=68.7s

  [34/405] intraday_0034.csv.gz chunk 5  in=27,922,589  out=18,767,200  elapsed=70.8s

  [35/405] intraday_0035.csv.gz chunk 5  in=28,672,589  out=19,271,872  elapsed=72.7s

  [36/405] intraday_0036.csv.gz chunk 5  in=29,491,745  out=19,836,650  elapsed=74.8s

  [37/405] intraday_0037.csv.gz chunk 5  in=30,234,721  out=20,332,653  elapsed=76.6s

  [38/405] intraday_0038.csv.gz chunk 5  in=30,924,778  out=20,799,459  elapsed=78.4s

  [39/405] intraday_0039.csv.gz chunk 5  in=31,674,778  out=21,294,515  elapsed=80.3s

  [40/405] intraday_0040.csv.gz chunk 5  in=32,407,718  out=21,771,464  elapsed=82.1s

  [41/405] intraday_0041.csv.gz chunk 5  in=33,157,718  out=22,258,793  elapsed=84.0s

  [42/405] intraday_0042.csv.gz chunk 5  in=34,051,794  out=22,869,841  elapsed=86.2s

  [43/405] intraday_0043.csv.gz chunk 5  in=34,960,739  out=23,477,626  elapsed=88.5s

  [44/405] intraday_0044.csv.gz chunk 5  in=35,710,739  out=23,979,454  elapsed=90.4s

  [45/405] intraday_0045.csv.gz chunk 5  in=36,516,274  out=24,512,719  elapsed=92.4s

  [46/405] intraday_0046.csv.gz chunk 5  in=37,318,713  out=25,044,009  elapsed=94.6s

  [47/405] intraday_0047.csv.gz chunk 5  in=38,133,804  out=25,588,842  elapsed=96.6s

  [48/405] intraday_0048.csv.gz chunk 5  in=38,906,436  out=26,111,602  elapsed=98.6s

  [49/405] intraday_0049.csv.gz chunk 5  in=39,656,436  out=26,621,510  elapsed=100.6s

  [50/405] intraday_0050.csv.gz chunk 5  in=40,601,960  out=27,256,221  elapsed=103.0s

  [51/405] intraday_0051.csv.gz chunk 5  in=41,414,383  out=27,809,390  elapsed=105.1s

  [52/405] intraday_0052.csv.gz chunk 5  in=42,164,383  out=28,309,666  elapsed=107.0s

  [53/405] intraday_0053.csv.gz chunk 5  in=42,998,896  out=28,874,208  elapsed=109.1s

  [54/405] intraday_0054.csv.gz chunk 5  in=43,729,514  out=29,359,833  elapsed=110.9s

  [55/405] intraday_0055.csv.gz chunk 5  in=44,479,514  out=29,849,767  elapsed=112.8s

  [56/405] intraday_0056.csv.gz chunk 5  in=45,292,383  out=30,388,749  elapsed=114.8s

  [57/405] intraday_0057.csv.gz chunk 5  in=46,110,329  out=30,945,782  elapsed=116.9s

  [58/405] intraday_0058.csv.gz chunk 5  in=46,830,377  out=31,440,267  elapsed=118.8s

  [59/405] intraday_0059.csv.gz chunk 5  in=47,580,377  out=31,946,578  elapsed=120.7s

  [60/405] intraday_0060.csv.gz chunk 5  in=48,264,439  out=32,413,712  elapsed=122.5s

  [61/405] intraday_0061.csv.gz chunk 5  in=49,014,439  out=32,917,867  elapsed=124.5s

  [62/405] intraday_0062.csv.gz chunk 5  in=50,022,323  out=33,597,090  elapsed=127.1s

  [63/405] intraday_0063.csv.gz chunk 5  in=50,772,323  out=34,113,626  elapsed=129.0s

  [64/405] intraday_0064.csv.gz chunk 5  in=51,725,856  out=34,759,681  elapsed=131.4s

  [65/405] intraday_0065.csv.gz chunk 5  in=52,611,073  out=35,368,914  elapsed=133.8s

  [66/405] intraday_0066.csv.gz chunk 5  in=53,344,110  out=35,865,429  elapsed=135.6s

  [67/405] intraday_0067.csv.gz chunk 5  in=54,094,110  out=36,373,779  elapsed=137.5s

  [68/405] intraday_0068.csv.gz chunk 5  in=54,864,222  out=36,893,863  elapsed=139.5s

  [69/405] intraday_0069.csv.gz chunk 5  in=55,688,820  out=37,438,420  elapsed=141.5s

  [70/405] intraday_0070.csv.gz chunk 5  in=56,497,048  out=37,981,558  elapsed=143.6s

  [71/405] intraday_0071.csv.gz chunk 5  in=57,135,058  out=38,395,993  elapsed=145.2s

  [72/405] intraday_0072.csv.gz chunk 5  in=57,879,667  out=38,894,527  elapsed=147.0s

  [73/405] intraday_0073.csv.gz chunk 5  in=58,629,667  out=39,402,607  elapsed=148.9s

  [74/405] intraday_0074.csv.gz chunk 5  in=59,409,405  out=39,922,716  elapsed=150.7s

  [75/405] intraday_0075.csv.gz chunk 5  in=60,159,405  out=40,417,055  elapsed=152.6s

  [76/405] intraday_0076.csv.gz chunk 5  in=60,866,670  out=40,897,076  elapsed=154.7s

  [77/405] intraday_0077.csv.gz chunk 5  in=61,616,670  out=41,399,107  elapsed=156.6s

  [78/405] intraday_0078.csv.gz chunk 5  in=62,426,095  out=41,918,828  elapsed=158.7s

  [79/405] intraday_0079.csv.gz chunk 5  in=63,486,689  out=42,625,024  elapsed=161.5s

  [80/405] intraday_0080.csv.gz chunk 5  in=64,355,814  out=43,217,284  elapsed=163.8s

  [81/405] intraday_0081.csv.gz chunk 5  in=65,105,814  out=43,727,194  elapsed=165.8s

  [82/405] intraday_0082.csv.gz chunk 5  in=65,923,353  out=44,275,258  elapsed=167.9s

  [83/405] intraday_0083.csv.gz chunk 5  in=66,712,271  out=44,802,607  elapsed=169.7s

  [84/405] intraday_0084.csv.gz chunk 5  in=67,498,390  out=45,313,936  elapsed=171.8s

  [85/405] intraday_0085.csv.gz chunk 5  in=68,668,886  out=46,097,839  elapsed=174.8s

  [86/405] intraday_0086.csv.gz chunk 5  in=69,443,048  out=46,627,543  elapsed=176.9s

  [87/405] intraday_0087.csv.gz chunk 5  in=70,370,846  out=47,261,939  elapsed=179.3s

  [88/405] intraday_0088.csv.gz chunk 5  in=71,314,187  out=47,913,509  elapsed=181.7s

  [89/405] intraday_0089.csv.gz chunk 5  in=72,147,243  out=48,494,115  elapsed=184.0s

  [90/405] intraday_0090.csv.gz chunk 5  in=73,031,904  out=49,096,082  elapsed=186.4s

  [91/405] intraday_0091.csv.gz chunk 5  in=73,819,473  out=49,623,788  elapsed=188.4s

  [92/405] intraday_0092.csv.gz chunk 5  in=74,749,201  out=50,248,190  elapsed=190.9s

  [93/405] intraday_0093.csv.gz chunk 5  in=75,581,839  out=50,806,469  elapsed=193.1s

  [94/405] intraday_0094.csv.gz chunk 5  in=76,397,498  out=51,349,469  elapsed=195.1s

  [95/405] intraday_0095.csv.gz chunk 5  in=77,278,738  out=51,931,714  elapsed=197.4s

  [96/405] intraday_0096.csv.gz chunk 5  in=78,128,774  out=52,490,568  elapsed=199.6s

  [97/405] intraday_0097.csv.gz chunk 5  in=79,010,543  out=53,065,827  elapsed=201.8s

  [98/405] intraday_0098.csv.gz chunk 5  in=79,782,923  out=53,595,309  elapsed=203.8s

  [99/405] intraday_0099.csv.gz chunk 5  in=80,552,827  out=54,108,983  elapsed=205.9s

  [100/405] intraday_0100.csv.gz chunk 5  in=81,613,945  out=54,836,685  elapsed=208.6s

  [101/405] intraday_0101.csv.gz chunk 5  in=82,411,660  out=55,361,277  elapsed=210.6s

  [102/405] intraday_0102.csv.gz chunk 5  in=83,343,388  out=56,001,712  elapsed=213.1s

  [103/405] intraday_0103.csv.gz chunk 5  in=84,277,121  out=56,623,793  elapsed=215.5s

  [104/405] intraday_0104.csv.gz chunk 5  in=85,067,945  out=57,154,440  elapsed=217.7s

  [105/405] intraday_0105.csv.gz chunk 5  in=85,909,844  out=57,738,691  elapsed=219.9s

  [106/405] intraday_0106.csv.gz chunk 5  in=86,782,104  out=58,326,369  elapsed=222.2s

  [107/405] intraday_0107.csv.gz chunk 5  in=87,571,848  out=58,859,306  elapsed=224.3s

  [108/405] intraday_0108.csv.gz chunk 5  in=88,635,246  out=59,579,070  elapsed=227.1s

  [109/405] intraday_0109.csv.gz chunk 5  in=89,429,847  out=60,095,417  elapsed=229.2s

  [110/405] intraday_0110.csv.gz chunk 5  in=90,369,231  out=60,726,184  elapsed=231.6s

  [111/405] intraday_0111.csv.gz chunk 5  in=91,390,909  out=61,390,631  elapsed=234.2s

  [112/405] intraday_0112.csv.gz chunk 5  in=92,177,941  out=61,925,035  elapsed=236.2s

  [113/405] intraday_0113.csv.gz chunk 5  in=93,009,949  out=62,483,312  elapsed=238.3s

  [114/405] intraday_0114.csv.gz chunk 5  in=93,772,660  out=62,992,629  elapsed=240.2s

  [115/405] intraday_0115.csv.gz chunk 5  in=94,609,984  out=63,560,381  elapsed=242.3s

  [116/405] intraday_0116.csv.gz chunk 5  in=95,366,153  out=64,069,119  elapsed=244.3s

  [117/405] intraday_0117.csv.gz chunk 5  in=96,314,921  out=64,713,579  elapsed=246.9s

  [118/405] intraday_0118.csv.gz chunk 5  in=97,100,237  out=65,238,507  elapsed=248.9s

  [119/405] intraday_0119.csv.gz chunk 5  in=98,245,742  out=66,013,578  elapsed=251.9s

  [120/405] intraday_0120.csv.gz chunk 5  in=98,995,742  out=66,522,338  elapsed=253.8s

  [121/405] intraday_0121.csv.gz chunk 5  in=99,855,343  out=67,083,090  elapsed=256.0s

  [122/405] intraday_0122.csv.gz chunk 5  in=100,900,376  out=67,783,741  elapsed=258.7s

  [123/405] intraday_0123.csv.gz chunk 5  in=101,688,876  out=68,318,513  elapsed=260.7s

  [124/405] intraday_0124.csv.gz chunk 5  in=102,540,604  out=68,888,196  elapsed=262.8s

  [125/405] intraday_0125.csv.gz chunk 5  in=103,517,055  out=69,552,459  elapsed=265.3s

  [126/405] intraday_0126.csv.gz chunk 5  in=104,398,833  out=70,143,483  elapsed=267.5s

  [127/405] intraday_0127.csv.gz chunk 5  in=105,314,012  out=70,765,111  elapsed=269.9s

  [128/405] intraday_0128.csv.gz chunk 5  in=106,064,012  out=71,269,694  elapsed=271.7s

  [129/405] intraday_0129.csv.gz chunk 5  in=106,816,285  out=71,757,331  elapsed=273.7s

  [130/405] intraday_0130.csv.gz chunk 5  in=107,676,182  out=72,332,607  elapsed=275.9s

  [131/405] intraday_0131.csv.gz chunk 5  in=108,498,465  out=72,898,727  elapsed=278.0s

  [132/405] intraday_0132.csv.gz chunk 5  in=109,165,533  out=73,327,546  elapsed=279.9s

  [133/405] intraday_0133.csv.gz chunk 5  in=109,915,533  out=73,828,086  elapsed=281.8s

✅ DONE  in=145,537,243 → out=109,394,488  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 386.1s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows.parquet'

In [22]:
import os
import glob
import pandas as pd
from typing import Optional, Dict, Tuple

def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,
) -> pd.DataFrame:
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    OPEN_FROM, OPEN_TO   = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    best_open:  Dict[Tuple[str, str], Tuple[str, float]] = {}
    best_close: Dict[Tuple[str, str], Tuple[str, float]] = {}

    usecols = ["ticker", "dt", "o", "c"]

    for path in files:
        for chunk in pd.read_csv(path, compression="infer", low_memory=False,
                                 chunksize=chunksize, usecols=usecols):
            cols = set(map(str, chunk.columns))
            missing = set(usecols) - cols
            if missing:
                raise KeyError(f"{os.path.basename(path)}: відсутні колонки {missing}")

            dt = chunk["dt"].astype(str)
            if "o" in chunk.columns:
                chunk["o"] = pd.to_numeric(chunk["o"], errors="coerce")
            if "c" in chunk.columns:
                chunk["c"] = pd.to_numeric(chunk["c"], errors="coerce")

            hhmm = dt.str.slice(11, 16)
            date = dt.str.slice(0, 10)

            # OPEN
            mask_o = (hhmm >= OPEN_FROM) & (hhmm <= OPEN_TO) & chunk["o"].notna()
            if mask_o.any():
                cut = chunk.loc[mask_o, ["ticker", "o"]].copy()
                cut["date"] = date[mask_o].values
                cut["dt"]   = dt[mask_o].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="first")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_open.get(key)
                    if (cur is None) or (r.dt < cur[0]):
                        best_open[key] = (r.dt, float(r.o))

            # CLOSE
            mask_c = (hhmm >= CLOSE_FROM) & (hhmm <= CLOSE_TO) & chunk["c"].notna()
            if mask_c.any():
                cut = chunk.loc[mask_c, ["ticker", "c"]].copy()
                cut["date"] = date[mask_c].values
                cut["dt"]   = dt[mask_c].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="last")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_close.get(key)
                    if (cur is None) or (r.dt > cur[0]):
                        best_close[key] = (r.dt, float(r.c))

    opens_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_open.items()],
        columns=["ticker", "date", "open"]
    )
    closes_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_close.items()],
        columns=["ticker", "date", "close"]
    )

    out = pd.merge(opens_df, closes_df, on=["ticker","date"], how="outer") \
            .sort_values(["ticker","date"], kind="stable") \
            .reset_index(drop=True)

    # ⬇️ ОКРУГЛЕННЯ ДО 2 ЗНАКІВ
    if "open" in out.columns:
        out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    if "close" in out.columns:
        out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)

    # завжди Parquet
    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)

    return out

In [23]:
df_oc = build_oc_from_intraday_folder(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "oc.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [24]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [25]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=52.9s

[batch   10] rows=20,000,000  elapsed=110.1s

[batch   15] rows=30,000,000  elapsed=168.7s

[batch   20] rows=40,000,000  elapsed=226.4s

[batch   25] rows=50,000,000  elapsed=283.9s

[batch   30] rows=60,000,000  elapsed=340.2s

[batch   35] rows=70,000,000  elapsed=396.5s

[batch   40] rows=80,000,000  elapsed=452.2s

[batch   45] rows=90,000,000  elapsed=508.2s

[batch   50] rows=100,000,000  elapsed=565.0s

[batch   55] rows=109,394,488  elapsed=620.7s

✅ DONE  rows=109,394,488  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  in 621.0s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet

In [26]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        # нульовий prev_close → NaN, щоб не ділити на 0
        denom = df["prev_close"].replace({0: np.nan})

        # розрахунок % vs prev_close
        pct = (df[value_col] / denom - 1.0) * 100.0

        # ще раз гарантуємо float dtype (без object/pd.NA всередині)
        pct = pd.to_numeric(pct, errors="coerce")

        if round_to is not None:
            pct = pct.round(int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(
                output_path,
                table.schema,
                compression="snappy",
            )
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [27]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

[batch    5] rows=10,000,000  elapsed=9.8s

[batch   10] rows=20,000,000  elapsed=19.8s

[batch   15] rows=30,000,000  elapsed=29.4s

[batch   20] rows=40,000,000  elapsed=39.3s

[batch   25] rows=50,000,000  elapsed=49.0s

[batch   30] rows=60,000,000  elapsed=59.0s

[batch   35] rows=70,000,000  elapsed=69.2s

[batch   40] rows=80,000,000  elapsed=79.9s

[batch   45] rows=90,000,000  elapsed=89.9s

[batch   50] rows=100,000,000  elapsed=100.1s

[batch   55] rows=109,394,488  elapsed=109.7s
✅ DONE  rows=109,394,488  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  in 109.7s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet

In [28]:
import os, re, time, math
import pandas as pd
from typing import Dict, List, Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


# ---------- НАДІЙНЕ ЧИТАННЯ МАПІНГУ (ticker, bench) ----------

def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Читає файл з відповідностями тікер↔бенч. Підтримка:
      - CSV (роздільник ; або , або \t), з/без заголовка
      - XLSX
      - Випадок "все в одній колонці": 'AAPL;SPY' / 'AAPL,SPY'
    Повертає DF: ['ticker','bench'] (UPPER, без дублікатів).
    """
    p = mapping_path
    ext = os.path.splitext(p)[1].lower()

    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(p)
    else:
        # 1) спроба autodetect
        try:
            df = pd.read_csv(p, sep=None, engine="python")
        except Exception:
            # 2) спроби з явними роздільниками
            for sep_try in (";", ",", "\t", "|"):
                try:
                    df = pd.read_csv(p, sep=sep_try, engine="python")
                    break
                except Exception:
                    df = None
            if df is None:
                # 3) можливо, файл без заголовка
                try:
                    df = pd.read_csv(p, header=None, sep=None, engine="python")
                except Exception:
                    # 4) остання спроба — явні сепаратори без заголовка
                    for sep_try in (";", ",", "\t", "|"):
                        try:
                            df = pd.read_csv(p, header=None, sep=sep_try, engine="python")
                            break
                        except Exception:
                            df = None
                    if df is None:
                        raise

    # Якщо одна колонка і виглядає як "AAPL;SPY" — сплітимо
    if df.shape[1] == 1:
        col = df.columns[0]
        # намагаємось розбити за ; або , або \t
        s = df[col].astype(str)
        if s.str.contains(";").any():
            parts = s.str.split(";", n=1, expand=True)
        elif s.str.contains(",").any():
            parts = s.str.split(",", n=1, expand=True)
        elif s.str.contains("\t").any():
            parts = s.str.split("\t", n=1, expand=True)
        else:
            raise KeyError("Не можу знайти роздільник між 'ticker' і 'bench'.")
        df = pd.DataFrame({"ticker": parts[0], "bench": parts[1]})

    # Вгадуємо назви колонок
    cols = {c.lower(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol")
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf")

    # Якщо заголовків нема, але 2 колонки — приймаємо їх як ticker/bench
    if tcol is None or bcol is None:
        if df.shape[1] >= 2:
            tcol = df.columns[0]
            bcol = df.columns[1]
        else:
            raise KeyError("Потрібні колонки 'ticker' і 'bench' у mapping-файлі.")

    out = (
        df[[tcol, bcol]]
        .rename(columns={tcol: "ticker", bcol: "bench"})
        .dropna()
    )
    out["ticker"] = out["ticker"].astype(str).str.strip().str.upper()
    out["bench"]  = out["bench"].astype(str).str.strip().str.upper()
    out = out[out["ticker"] != ""]
    out = out[out["bench"]  != ""]
    return out.drop_duplicates(ignore_index=True)


# ---------- ВИТЯГ corr/beta ДЛЯ ПАР (X, ФІКСОВАНИЙ BENCH) ----------

def _fetch_corr_beta_pairs(
    x_list: List[str],
    bench: str,
    *,
    period: str = "6 months",
    fmt: str = "json_records",
    batch_size: int = 150,
    min_batch_size: int = 10,
    pause: float = 0.15,
    max_retries: int = 3,
    retry_backoff: float = 0.6,
) -> pd.DataFrame:
    results: List[pd.DataFrame] = []
    i, n = 0, len(x_list)
    b = bench

    while i < n:
        cur_bs = min(batch_size, n - i)
        attempt = 0
        while True:
            xs = x_list[i : i + cur_bs]
            params = {
                "x_tickers": ",".join(xs),
                "y_tickers": b,
                "period": period,
                "as_pivot": False,
                "format": fmt,
            }
            try:
                df_chunk = DatumApi.data_request("/calculations/corr_beta/v2", params)
                if df_chunk is not None and not df_chunk.empty:
                    # лишаємо тільки рядки для потрібного bench (на випадок, якщо API поверне зайве)
                    if "y_ticker" in df_chunk.columns:
                        df_chunk = df_chunk[df_chunk["y_ticker"].astype(str).str.upper() == b]
                    results.append(df_chunk)
                i += len(xs)
                time.sleep(pause)  # пауза тільки після успішного батча
                break
            except Exception as e:
                msg = str(e).lower()
                # 414: зменшуємо ЛИШЕ поточний батч
                if "414" in msg or "uri too large" in msg:
                    if cur_bs <= min_batch_size:
                        print(f"⚠️ 414 навіть при batch={cur_bs}. Пропускаю X[{i}:{i+cur_bs}] для {b}.")
                        i += cur_bs
                        break
                    new_bs = max(min_batch_size, cur_bs // 2)
                    print(f"⚠️ 414 → shrink {cur_bs} → {new_bs} для {b} і повторюю.")
                    cur_bs = new_bs
                    continue

                attempt += 1
                if attempt > max_retries:
                    print(f"⚠️  Пропуск X[{i}:{i+cur_bs}] для {b} після {max_reTRIES} ретраїв. Помилка: {e}")
                    i += cur_bs
                    break
                sleep_s = retry_backoff * (2 ** (attempt - 1))
                print(f"⚠️  {e} → retry {attempt}/{max_retries} через {sleep_s:.1f}s")
                time.sleep(sleep_s)

    return pd.concat(results, ignore_index=True) if results else pd.DataFrame()


# ---------- ГОЛОВНА ФУНКЦІЯ ----------

def corr_beta_from_mapping_to_parquet(
    mapping_path: str,
    out_parquet_path: str,
    *,
    period: str = "3 months",
    batch_size: int = 150,
    min_batch_size: int = 10,
    pause: float = 0.15,
    max_retries: int = 3,
    retry_backoff: float = 0.6,
) -> str:
    """
    Читає mapping (ticker, bench) будь-якого адекватного формату,
    групує тікери по бенчу, витягує corr/beta для кожної групи
    і потоково пише результат у Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для запису .parquet")

    map_df = _read_mapping(mapping_path)

    groups: Dict[str, List[str]] = (
        map_df.groupby("bench")["ticker"].apply(lambda s: sorted(set(s.tolist()))).to_dict()
    )

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    writer: Optional[pq.ParquetWriter] = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START corr/beta → {out_parquet_path} | період={period} | бенчів={len(groups)}")

    for b, xs in sorted(groups.items()):
        if not xs:
            continue
        print(f"— Bench {b}: {len(xs)} тикерів")
        df_b = _fetch_corr_beta_pairs(
            xs, b,
            period=period,
            batch_size=batch_size,
            min_batch_size=min_batch_size,
            pause=pause,
            max_retries=max_retries,
            retry_backoff=retry_backoff,
        )
        if df_b is None or df_b.empty:
            continue

        # типи
        for col in ("corr", "beta"):
            if col in df_b.columns:
                df_b[col] = pd.to_numeric(df_b[col], errors="coerce")

        table = pa.Table.from_pandas(df_b, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression="snappy")
        writer.write_table(table)
        total_rows += len(df_b)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path

In [29]:
out_path = corr_beta_from_mapping_to_parquet(
    mapping_path=str(WORK_DIR / "ticker_bench_.csv"),
    out_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    period="3 months",
    batch_size=150,
    pause=0.15,
)
print("Результат:", out_path)

▶️ START corr/beta → C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet | період=3 months | бенчів=10
— Bench BITO: 52 тикерів

— Bench GDX: 129 тикерів

— Bench IWM: 2408 тикерів

— Bench KRE: 139 тикерів

— Bench KWEB: 46 тикерів

— Bench QQQ: 491 тикерів

— Bench SOXL: 26 тикерів

— Bench SPY: 2854 тикерів

— Bench XLE: 183 тикерів

— Bench XLF: 270 тикерів

✅ DONE rows=6,598 → C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet  in 18.9s
Результат: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [30]:

y_list = ["SPY", "IWM", "GDX", "XLF", "QQQ", "XLE", "KRE", "BITO", "SOXL"]

In [31]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    # Читаємо БЕЗ фільтра колонок — так надійніше для різних схем
    table = pq.read_table(path)
    df = table.to_pandas()

    # нормалізуємо імена колонок для пошуку
    name_map = {c: c.strip().lower() for c in df.columns}
    inv_map = {v: k for k, v in name_map.items()}

    has_api    = ("x_ticker" in inv_map) and ("y_ticker" in inv_map)
    has_direct = ("ticker" in inv_map) and ("bench" in inv_map)

    if not (has_api or has_direct):
        # допоміжна підказка, що саме є в файлі
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={
            inv_map["x_ticker"]: "ticker",
            inv_map["y_ticker"]: "bench"
        })
    else:
        df = df.rename(columns={
            inv_map["ticker"]: "ticker",
            inv_map["bench"]:  "bench"
        })

    # corr/beta можуть бути відсутні — створимо
    if "corr" not in name_map.values():
        df["corr"] = pd.NA
    else:
        df = df.rename(columns={inv_map["corr"]: "corr"})
    if "beta" not in name_map.values():
        df["beta"] = pd.NA
    else:
        df = df.rename(columns={inv_map["beta"]: "beta"})

    # залишаємо тільки потрібне
    keep = [c for c in ["ticker", "bench", "corr", "beta"] if c in df.columns]
    df = df[keep].copy()

    # нормалізація значень
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"]  = df["bench"].astype(str).str.strip().str.upper()
    if "corr" in df.columns:
        df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    if "beta" in df.columns:
        df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    # якщо раптом на один тикер кілька рядків — візьмемо з найбільшою corr
    if "corr" in df.columns:
        df = (df.sort_values(["ticker", "corr"], ascending=[True, False])
                .drop_duplicates(subset=["ticker"], keep="first")
                .reset_index(drop=True))
    else:
        df = df.drop_duplicates(subset=["ticker"], keep="first").reset_index(drop=True)

    # гарантуємо повний набір стовпців
    for c in ("corr", "beta"):
        if c not in df.columns:
            df[c] = pd.NA

    return df[["ticker", "bench", "corr", "beta"]]


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), мерджить 'bench','corr','beta' з іншого
    Parquet (мапа) по 'ticker' і пише новий Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0
    batches = 0

    print(f"▶️ START merge → {out_parquet_path}")

    for batch in pf.iter_batches(batch_size=batch_rows):  # читаємо всі колонки
        batches += 1
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")
        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(mapping, on="ticker", how="left", validate="m:1")

        # Переставимо нові колонки за потреби
        if insert_before in merged.columns:
            cols = list(merged.columns)
            for c in ("bench", "corr", "beta"):
                if c in cols: cols.remove(c)
            idx = cols.index(insert_before)
            new_cols = cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]
            merged = merged[new_cols]
        else:
            base = [c for c in merged.columns if c not in ("bench","corr","beta")]
            merged = merged[base + ["bench","corr","beta"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if batches % log_every_batches == 0:
            print(f"[batch {batches:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path


# опціональний аліас під старе ім’я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [32]:
out_path = attach_bench_corr_beta_parquet(
    input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    batch_rows=2_000_000,
    round_decimals=4,
    insert_before="pct_vs_prev_close",
    compression="snappy",
)
print("Готово:", out_path)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

[batch    5] rows=10,000,000  elapsed=19.8s

[batch   10] rows=20,000,000  elapsed=39.6s

[batch   15] rows=30,000,000  elapsed=60.3s

[batch   20] rows=40,000,000  elapsed=79.2s

[batch   25] rows=50,000,000  elapsed=97.5s

[batch   30] rows=60,000,000  elapsed=116.7s

[batch   35] rows=70,000,000  elapsed=136.0s

[batch   40] rows=80,000,000  elapsed=155.5s

[batch   45] rows=90,000,000  elapsed=174.6s

[batch   50] rows=100,000,000  elapsed=194.1s

[batch   55] rows=109,394,488  elapsed=212.5s
✅ DONE rows=109,394,488 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet  in 212.6s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

In [33]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [34]:
peek_parquet("CRACEN/work/premarket_rows_final.parquet", n=620)

Файл: CRACEN/work/premarket_rows_final.parquet
Рядків (meta): 109,394,488
Колонок: 14
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta
NaN у 'bench' (у прев'ю): 0/620
NaN у 'corr' (у прев'ю): 0/620
NaN у 'beta' (у прев'ю): 0/620

Перші рядки:
    ticker                  dt           o           h           l           c         v        date    open  prev_close  Stack% bench  corr  beta
0        A 2025-11-25 00:02:00  151.860001  151.860001  151.860001  151.860001      15.0  2025-11-25  150.78      153.52   -1.08   IWM  0.64  0.37
1        A 2025-11-25 00:47:00  150.160004  150.160004  150.160004  150.160004       1.0  2025-11-25  150.78      153.52   -2.19   IWM  0.64  0.37
2        A 2025-11-25 01:58:00  150.160004  150.160004  150.100006  150.100006      30.0  2025-11-25  150.78      153.52   -2.19   IWM  0.64  0.37
3        A 2025-11-25 02:00:00  150.100006  150.100006  150.100006  150.100006       9.0  2025-11-25  150.78      153.52   -2.23   IWM  0.64  0.37
4        A 2025-11-25 05:14:00  150.990005  150.990005  150.990005  150.990005     100.0  2025-11-25  150.78      153.52   -1.65   IWM  0.64  0.37
5        A 2025-11-25 07:03:00  150.020004  150.020004  150.020004  150.020004     100.0  2025-11-25  150.78      153.52   -2.28   IWM  0.64  0.37
6        A 2025-11-25 07:37:00  150.020004  150.020004  150.020004  150.020004     100.0  2025-11-25  150.78      153.52   -2.28   IWM  0.64  0.37
7        A 2025-11-25 07:55:00  150.039993  150.039993  150.039993  150.039993     100.0  2025-11-25  150.78      153.52   -2.27   IWM  0.64  0.37
8        A 2025-11-25 08:00:00  150.539993  151.000000  150.000000  151.000000     832.0  2025-11-25  150.78      153.52   -1.94   IWM  0.64  0.37
9        A 2025-11-25 08:18:00  150.539993  150.539993  150.539993  150.539993     150.0  2025-11-25  150.78      153.52   -1.94   IWM  0.64  0.37
10       A 2025-11-25 08:19:00  147.781693  147.781693  147.781693  147.781693     100.0  2025-11-25  150.78      153.52   -3.74   IWM  0.64  0.37
11       A 2025-11-25 08:27:00  149.073303  149.500000  149.065002  149.065002     600.0  2025-11-25  150.78      153.52   -2.90   IWM  0.64  0.37
12       A 2025-11-25 08:30:00  149.610001  149.610001  149.610001  149.610001    1000.0  2025-11-25  150.78      153.52   -2.55   IWM  0.64  0.37
13       A 2025-11-25 08:32:00  149.990005  149.990005  149.990005  149.990005     100.0  2025-11-25  150.78      153.52   -2.30   IWM  0.64  0.37
14       A 2025-11-25 08:48:00  149.990005  149.990005  149.990005  149.990005     100.0  2025-11-25  150.78      153.52   -2.30   IWM  0.64  0.37
15       A 2025-11-25 08:52:00  150.259995  150.259995  150.259995  150.259995     100.0  2025-11-25  150.78      153.52   -2.12   IWM  0.64  0.37
16       A 2025-11-25 08:53:00  150.500000  150.500000  150.500000  150.500000     238.0  2025-11-25  150.78      153.52   -1.97   IWM  0.64  0.37
17       A 2025-11-25 08:59:00  150.550003  150.550003  150.550003  150.550003     100.0  2025-11-25  150.78      153.52   -1.93   IWM  0.64  0.37
18       A 2025-11-25 09:00:00  150.500000  150.500000  150.500000  150.500000     174.0  2025-11-25  150.78      153.52   -1.97   IWM  0.64  0.37
19       A 2025-11-25 09:05:00  150.500000  150.500000  150.500000  150.500000     189.0  2025-11-25  150.78      153.52   -1.97   IWM  0.64  0.37
20       A 2025-11-25 09:20:00  151.000000  151.000000  150.770004  151.000000    1355.0  2025-11-25  150.78      153.52   -1.64   IWM  0.64  0.37
21       A 2025-11-25 09:28:00  151.389999  151.449997  151.389999  151.449997     577.0  2025-11-25  150.78      153.52   -1.39   IWM  0.64  0.37
22       A 2025-11-25 09:29:00  151.490005  152.199997  151.490005  152.199997    1199.0  2025-11-25  150.78      153.52   -1.32   IWM  0.64  0.37
23       A 2025-11-25 09:30:00  150.779999  150.895004  148.000107  149.794998   64932.0  2025-11-25  150.78      153.52   -1.78   IWM  0.64  0.37
24       A 2025-11-25 09:31:00  149.789993  151.369995  149.789993  150.690002    9379.0  2025-11-25  150.78      153.52   -2.43   IWM  0.64  0.37
25       A 2025-11-25 09:32:00  150.854996  154.279999  150.854996  153.770004   22249.0  2025-11-25  150.78      153.52   -1.74   IWM  0.64  0.37
26       A 2025-11-25 09:33:00  153.800003  154.279999  153.000000  153.475006   18767.0  2025-11-25  150.78      153.52    0.18   IWM  0.64  0.37
27       A 2025-11-25 09:34:00  153.690002  154.100006  152.481400  153.585007   16192.0  2025-11-25  150.78      153.52    0.11   IWM  0.64  0.37
28       A 2025-11-25 09:35:00  153.585007  154.220001  153.244995  154.179993    7687.0  2025-11-25  150.78      153.52    0.04   IWM  0.64  0.37
29       A 2025-11-25 09:36:00  154.029999  154.850006  153.710007  154.544998   10437.0  2025-11-25  150.78      153.52    0.33   IWM  0.64  0.37
30       A 2025-11-25 09:37:00  154.544998  155.983994  154.544998  155.983994   27961.0  2025-11-25  150.78      153.52    0.67   IWM  0.64  0.37
31       A 2025-11-25 09:38:00  155.990005  156.112503  155.341507  156.000000   18123.0  2025-11-25  150.78      153.52    1.61   IWM  0.64  0.37
32       A 2025-11-25 09:39:00  155.800003  156.779999  155.270004  155.337006    7237.0  2025-11-25  150.78      153.52    1.49   IWM  0.64  0.37
33       A 2025-11-25 09:40:00  155.395004  156.339996  155.250000  156.339996    4352.0  2025-11-25  150.78      153.52    1.22   IWM  0.64  0.37
34       A 2025-11-25 09:41:00  156.779999  157.479996  156.520004  156.520004   10842.0  2025-11-25  150.78      153.52    2.12   IWM  0.64  0.37
35       A 2025-11-25 09:42:00  156.699997  157.470001  156.429993  157.419998    5720.0  2025-11-25  150.78      153.52    2.07   IWM  0.64  0.37
36       A 2025-11-25 09:43:00  157.130005  157.134995  156.520004  156.699997    9849.0  2025-11-25  150.78      153.52    2.35   IWM  0.64  0.37
37       A 2025-11-25 09:44:00  157.009995  157.210007  156.710007  157.210007    4960.0  2025-11-25  150.78      153.52    2.27   IWM  0.64  0.37
38       A 2025-11-25 09:45:00  157.220001  157.440002  157.029999  157.210007    5011.0  2025-11-25  150.78      153.52    2.41   IWM  0.64  0.37
39       A 2025-11-25 09:46:00  157.240005  157.979996  157.240005  157.309998   18044.0  2025-11-25  150.78      153.52    2.42   IWM  0.64  0.37
40       A 2025-11-25 09:47:00  157.274994  157.274994  156.839996  156.929993    1923.0  2025-11-25  150.78      153.52    2.45   IWM  0.64  0.37
41       A 2025-11-25 09:48:00  157.050003  157.179993  156.535004  156.562500    9619.0  2025-11-25  150.78      153.52    2.30   IWM  0.64  0.37
42       A 2025-11-25 09:49:00  156.669998  156.669998  155.490005  156.024994   14645.0  2025-11-25  150.78      153.52    2.05   IWM  0.64  0.37
43       A 2025-11-25 09:50:00  156.289993  156.535004  156.179993  156.475006    4070.0  2025-11-25  150.78      153.52    1.80   IWM  0.64  0.37
44       A 2025-11-25 09:51:00  156.244995  156.250000  155.960007  156.000000    5378.0  2025-11-25  150.78      153.52    1.78   IWM  0.64  0.37
45       A 2025-11-25 09:52:00  156.000000  156.250000  155.380005  155.690002    9412.0  2025-11-25  150.78      153.52    1.62   IWM  0.64  0.37
46       A 2025-11-25 09:53:00  155.714996  156.490005  155.714996  156.324997    5519.0  2025-11-25  150.78      153.52    1.43   IWM  0.64  0.37
47       A 2025-11-25 09:54:00  156.490005  156.550003  156.410004  156.410004    3604.0  2025-11-25  150.78      153.52    1.93   IWM  0.64  0.37
48       A 2025-11-25 09:55:00  156.410004  156.410004  155.729996  156.270004   16064.0  2025-11-25  150.78      153.52    1.88   IWM  0.64  0.37
49       A 2025-11-25 09:56:00  156.264999  156.710007  156.089996  156.529999    5957.0  2025-11-25  150.78      153.52    1.79   IWM  0.64  0.37
50       A 2025-11-25 09:57:00  156.752502  156.752502  156.279999  156.479996    2133.0  2025-11-25  150.78      153.52    2.11   IWM  0.64  0.37
51       A 2025-11-25 09:58:00  156.490005  156.800003  156.490005  156.755005    1017.0  2025-11-25  150.78      153.52    1.93   IWM  0.64  0.37
52       A 2025-11-25 09:59:00  156.755005  156.755005  156.510101  156.755005    2997.0  2025-11-25  150.78      153.52    2.11   IWM  0.64  0.37
53       A 2025-11-25 10:00:00  156.509995  156.910004  156.345001  156.384995    8703.0  2025-11-25  150.78      153.52    1.95   IWM  0.64  0.37
54       A 2025-11-25 10:01:00  156.389999  156.690002  156.300003  156.330002   18760.0  2025-11-25  150.78      153.52    1.87   IWM  0.64  0.37
55       A 2025-11-25 10:02:00  156.449997  156.490005  155.990005  156.172501   25227.0  2025-11-25  150.78      153.52    1.91   IWM  0.64  0.37
56       A 2025-11-25 10:03:00  156.145004  156.710007  156.145004  156.527100    3386.0  2025-11-25  150.78      153.52    1.71   IWM  0.64  0.37
57       A 2025-11-25 10:04:00  156.585007  156.608002  156.289993  156.365005    2745.0  2025-11-25  150.78      153.52    2.00   IWM  0.64  0.37
58       A 2025-11-25 10:05:00  156.419998  156.570007  156.110001  156.110001    4079.0  2025-11-25  150.78      153.52    1.89   IWM  0.64  0.37
59       A 2025-11-25 10:06:00  156.110001  156.279999  155.990005  156.279999    4340.0  2025-11-25  150.78      153.52    1.69   IWM  0.64  0.37
60       A 2025-11-25 10:07:00  156.309998  156.600006  156.309998  156.544998    6826.0  2025-11-25  150.78      153.52    1.82   IWM  0.64  0.37
61       A 2025-11-25 10:08:00  156.550003  156.833405  156.550003  156.634995    2346.0  2025-11-25  150.78      153.52    1.97   IWM  0.64  0.37
62       A 2025-11-25 10:09:00  156.634995  156.639999  156.289993  156.309998   10767.0  2025-11-25  150.78      153.52    2.03   IWM  0.64  0.37
63       A 2025-11-25 10:10:00  156.304993  156.479996  156.293198  156.419998    4162.0  2025-11-25  150.78      153.52    1.81   IWM  0.64  0.37
64       A 2025-11-25 10:11:00  156.399994  156.559998  156.130005  156.149994    9856.0  2025-11-25  150.78      153.52    1.88   IWM  0.64  0.37
65       A 2025-11-25 10:12:00  156.149994  156.149994  155.945007  156.119995    5961.0  2025-11-25  150.78      153.52    1.71   IWM  0.64  0.37
66       A 2025-11-25 10:13:00  156.255005  156.255005  156.130005  156.255005    3129.0  2025-11-25  150.78      153.52    1.78   IWM  0.64  0.37
67       A 2025-11-25 10:14:00  156.255005  156.255005  155.679993  155.940002    5651.0  2025-11-25  150.78      153.52    1.78   IWM  0.64  0.37
68       A 2025-11-25 10:15:00  155.940002  156.210007  155.899994  156.059998    9795.0  2025-11-25  150.78      153.52    1.58   IWM  0.64  0.37
69       A 2025-11-25 10:16:00  156.059998  156.169998  155.800003  156.020004    4735.0  2025-11-25  150.78      153.52    1.65   IWM  0.64  0.37
70       A 2025-11-25 10:17:00  156.059998  156.130005  155.910004  155.910004    1483.0  2025-11-25  150.78      153.52    1.65   IWM  0.64  0.37
71       A 2025-11-25 10:18:00  156.100006  156.100006  155.919998  155.979996    1500.0  2025-11-25  150.78      153.52    1.68   IWM  0.64  0.37
72       A 2025-11-25 10:19:00  155.860001  156.059998  155.860001  155.910004    1786.0  2025-11-25  150.78      153.52    1.52   IWM  0.64  0.37
73       A 2025-11-25 10:20:00  155.550003  155.929993  155.531097  155.839996    2018.0  2025-11-25  150.78      153.52    1.32   IWM  0.64  0.37
74       A 2025-11-25 10:21:00  155.809998  155.929993  155.809998  155.929993     500.0  2025-11-25  150.78      153.52    1.49   IWM  0.64  0.37
75       A 2025-11-25 10:22:00  155.970001  156.070099  155.960007  155.985001    1924.0  2025-11-25  150.78      153.52    1.60   IWM  0.64  0.37
76       A 2025-11-25 10:23:00  155.940002  156.059998  155.759995  156.050003    4335.0  2025-11-25  150.78      153.52    1.58   IWM  0.64  0.37
77       A 2025-11-25 10:24:00  156.024994  156.645004  156.024994  156.639999    7089.0  2025-11-25  150.78      153.52    1.63   IWM  0.64  0.37
78       A 2025-11-25 10:25:00  156.479996  157.000000  156.479996  156.809998    3464.0  2025-11-25  150.78      153.52    1.93   IWM  0.64  0.37
79       A 2025-11-25 10:26:00  156.820007  157.070007  156.820007  157.050003    6463.0  2025-11-25  150.78      153.52    2.15   IWM  0.64  0.37
80       A 2025-11-25 10:27:00  157.000000  157.190002  156.869995  157.029999    9073.0  2025-11-25  150.78      153.52    2.27   IWM  0.64  0.37
81       A 2025-11-25 10:28:00  157.164993  157.500000  157.089996  157.259995    3077.0  2025-11-25  150.78      153.52    2.37   IWM  0.64  0.37
82       A 2025-11-25 10:29:00  157.070007  157.070007  156.809998  157.035004    1100.0  2025-11-25  150.78      153.52    2.31   IWM  0.64  0.37
83       A 2025-11-25 10:30:00  157.089996  157.376007  156.839996  157.376007    2929.0  2025-11-25  150.78      153.52    2.33   IWM  0.64  0.37
84       A 2025-11-25 10:31:00  157.320007  157.500000  157.309998  157.339996    5668.0  2025-11-25  150.78      153.52    2.48   IWM  0.64  0.37
85       A 2025-11-25 10:32:00  157.419998  157.683197  157.419998  157.675003    8061.0  2025-11-25  150.78      153.52    2.54   IWM  0.64  0.37
86       A 2025-11-25 10:33:00  157.675003  157.675003  157.429993  157.669998    3282.0  2025-11-25  150.78      153.52    2.71   IWM  0.64  0.37
87       A 2025-11-25 10:34:00  157.610001  157.860001  157.479996  157.860001     884.0  2025-11-25  150.78      153.52    2.66   IWM  0.64  0.37
88       A 2025-11-25 10:35:00  157.744995  157.830002  157.623795  157.744995    3425.0  2025-11-25  150.78      153.52    2.75   IWM  0.64  0.37
89       A 2025-11-25 10:36:00  157.789993  157.990005  157.789993  157.845001    4302.0  2025-11-25  150.78      153.52    2.78   IWM  0.64  0.37
90       A 2025-11-25 10:37:00  157.860001  157.860001  157.690002  157.785004    2700.0  2025-11-25  150.78      153.52    2.83   IWM  0.64  0.37
91       A 2025-11-25 10:38:00  157.679993  157.929993  157.669998  157.929993    2906.0  2025-11-25  150.78      153.52    2.71   IWM  0.64  0.37
92       A 2025-11-25 10:39:00  157.884995  157.884995  157.789993  157.789993    1010.0  2025-11-25  150.78      153.52    2.84   IWM  0.64  0.37
93       A 2025-11-25 10:40:00  157.789993  158.110001  157.710007  157.945007    7464.0  2025-11-25  150.78      153.52    2.78   IWM  0.64  0.37
94       A 2025-11-25 10:41:00  158.100006  158.250000  158.100006  158.195007    2317.0  2025-11-25  150.78      153.52    2.98   IWM  0.64  0.37
95       A 2025-11-25 10:42:00  158.179993  158.189896  157.979996  158.125000    2594.0  2025-11-25  150.78      153.52    3.04   IWM  0.64  0.37
96       A 2025-11-25 10:43:00  158.145004  158.270004  158.145004  158.270004    1711.0  2025-11-25  150.78      153.52    3.01   IWM  0.64  0.37
97       A 2025-11-25 10:44:00  158.270004  158.520004  158.270004  158.300003    2489.0  2025-11-25  150.78      153.52    3.09   IWM  0.64  0.37
98       A 2025-11-25 10:45:00  158.380005  158.570007  158.320007  158.339996    3474.0  2025-11-25  150.78      153.52    3.17   IWM  0.64  0.37
99       A 2025-11-25 10:46:00  158.289993  158.440002  158.289993  158.404999     800.0  2025-11-25  150.78      153.52    3.11   IWM  0.64  0.37
100      A 2025-11-25 10:47:00  158.320007  158.630005  158.210007  158.210007    1500.0  2025-11-25  150.78      153.52    3.13   IWM  0.64  0.37
101      A 2025-11-25 10:48:00  158.169998  158.289993  157.949997  158.175003    4132.0  2025-11-25  150.78      153.52    3.03   IWM  0.64  0.37
102      A 2025-11-25 10:49:00  158.175003  158.339996  158.149994  158.169998    2083.0  2025-11-25  150.78      153.52    3.03   IWM  0.64  0.37
103      A 2025-11-25 10:50:00  158.429993  158.429993  157.889999  158.009995   16834.0  2025-11-25  150.78      153.52    3.20   IWM  0.64  0.37
104      A 2025-11-25 10:51:00  158.009995  158.039993  157.889999  157.895004    1882.0  2025-11-25  150.78      153.52    2.92   IWM  0.64  0.37
105      A 2025-11-25 10:52:00  157.884995  158.179993  157.660004  158.179993    5087.0  2025-11-25  150.78      153.52    2.84   IWM  0.64  0.37
106      A 2025-11-25 10:53:00  158.300003  158.479904  158.190002  158.190002    3262.0  2025-11-25  150.78      153.52    3.11   IWM  0.64  0.37
107      A 2025-11-25 10:54:00  158.214996  158.259995  158.205002  158.205002     350.0  2025-11-25  150.78      153.52    3.06   IWM  0.64  0.37
108      A 2025-11-25 10:55:00  158.199997  158.199997  158.123199  158.199997    1162.0  2025-11-25  150.78      153.52    3.05   IWM  0.64  0.37
109      A 2025-11-25 10:56:00  158.199997  158.339996  158.029999  158.339996    1650.0  2025-11-25  150.78      153.52    3.05   IWM  0.64  0.37
110      A 2025-11-25 10:57:00  158.195007  158.339996  158.195007  158.195007    1113.0  2025-11-25  150.78      153.52    3.05   IWM  0.64  0.37
111      A 2025-11-25 10:58:00  158.195007  158.490005  158.195007  158.380005    4325.0  2025-11-25  150.78      153.52    3.05   IWM  0.64  0.37
112      A 2025-11-25 10:59:00  158.320007  158.440002  158.309998  158.440002    2594.0  2025-11-25  150.78      153.52    3.13   IWM  0.64  0.37
113      A 2025-11-25 11:00:00  158.440002  158.589996  158.320007  158.384995    4967.0  2025-11-25  150.78      153.52    3.20   IWM  0.64  0.37
114      A 2025-11-25 11:01:00  158.384995  158.789993  158.315002  158.789993    3316.0  2025-11-25  150.78      153.52    3.17   IWM  0.64  0.37
115      A 2025-11-25 11:02:00  158.600006  158.705002  158.600006  158.649994     422.0  2025-11-25  150.78      153.52    3.31   IWM  0.64  0.37
116      A 2025-11-25 11:03:00  158.630005  158.919998  158.630005  158.889999    3420.0  2025-11-25  150.78      153.52    3.33   IWM  0.64  0.37
117      A 2025-11-25 11:04:00  158.770004  158.809998  158.470093  158.809998   10368.0  2025-11-25  150.78      153.52    3.42   IWM  0.64  0.37
118      A 2025-11-25 11:05:00  158.809998  158.830002  158.720001  158.770004    1713.0  2025-11-25  150.78      153.52    3.45   IWM  0.64  0.37
119      A 2025-11-25 11:06:00  158.830002  159.000000  158.830002  158.949997    5745.0  2025-11-25  150.78      153.52    3.46   IWM  0.64  0.37
120      A 2025-11-25 11:07:00  158.929993  159.031097  158.925797  159.031097    5840.0  2025-11-25  150.78      153.52    3.52   IWM  0.64  0.37
121      A 2025-11-25 11:08:00  158.919998  159.360001  158.869995  159.220001    8337.0  2025-11-25  150.78      153.52    3.52   IWM  0.64  0.37
122      A 2025-11-25 11:09:00  159.194504  159.339996  159.119995  159.179993    4782.0  2025-11-25  150.78      153.52    3.70   IWM  0.64  0.37
123      A 2025-11-25 11:10:00  159.149994  159.550003  159.100006  159.524994    5252.0  2025-11-25  150.78      153.52    3.67   IWM  0.64  0.37
124      A 2025-11-25 11:11:00  159.589996  159.589996  159.529999  159.529999     707.0  2025-11-25  150.78      153.52    3.95   IWM  0.64  0.37
125      A 2025-11-25 11:12:00  159.460602  159.639999  159.460602  159.630005    2127.0  2025-11-25  150.78      153.52    3.87   IWM  0.64  0.37
126      A 2025-11-25 11:13:00  159.639999  159.880005  159.639999  159.789993    6939.0  2025-11-25  150.78      153.52    3.99   IWM  0.64  0.37
127      A 2025-11-25 11:14:00  159.789993  159.820007  159.639999  159.649994    6518.0  2025-11-25  150.78      153.52    4.08   IWM  0.64  0.37
128      A 2025-11-25 11:15:00  159.649994  159.679993  159.339996  159.419998   12481.0  2025-11-25  150.78      153.52    3.99   IWM  0.64  0.37
129      A 2025-11-25 11:16:00  159.490005  159.779999  159.490005  159.779999    2895.0  2025-11-25  150.78      153.52    3.89   IWM  0.64  0.37
130      A 2025-11-25 11:17:00  159.820007  159.949997  159.729996  159.770004    8374.0  2025-11-25  150.78      153.52    4.10   IWM  0.64  0.37
131      A 2025-11-25 11:18:00  159.910004  159.919998  159.759995  159.779999    5499.0  2025-11-25  150.78      153.52    4.16   IWM  0.64  0.37
132      A 2025-11-25 11:19:00  159.779999  159.919907  159.570007  159.850006    9437.0  2025-11-25  150.78      153.52    4.08   IWM  0.64  0.37

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta
0,A,2025-11-25 00:02:00,151.860001,151.860001,151.860001,151.860001,15.0,2025-11-25,150.78,153.52,-1.08,IWM,0.64,0.37
1,A,2025-11-25 00:47:00,150.160004,150.160004,150.160004,150.160004,1.0,2025-11-25,150.78,153.52,-2.19,IWM,0.64,0.37
2,A,2025-11-25 01:58:00,150.160004,150.160004,150.100006,150.100006,30.0,2025-11-25,150.78,153.52,-2.19,IWM,0.64,0.37
3,A,2025-11-25 02:00:00,150.100006,150.100006,150.100006,150.100006,9.0,2025-11-25,150.78,153.52,-2.23,IWM,0.64,0.37
4,A,2025-11-25 05:14:00,150.990005,150.990005,150.990005,150.990005,100.0,2025-11-25,150.78,153.52,-1.65,IWM,0.64,0.37
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,A,2025-11-26 12:31:00,155.369995,155.369995,155.369995,155.369995,400.0,2025-11-26,155.74,157.18,-1.15,IWM,0.64,0.37
616,A,2025-11-26 12:32:00,155.320007,155.369995,155.279999,155.300003,2952.0,2025-11-26,155.74,157.18,-1.18,IWM,0.64,0.37
617,A,2025-11-26 12:33:00,155.304993,155.304993,155.190094,155.250000,900.0,2025-11-26,155.74,157.18,-1.19,IWM,0.64,0.37
618,A,2025-11-26 12:34:00,155.250000,155.250000,155.199997,155.199997,400.0,2025-11-26,155.74,157.18,-1.23,IWM,0.64,0.37
619,A,2025-11-26 12:35:00,155.289993,155.404999,155.279999,155.404999,1900.0,2025-11-26,155.74,157.18,-1.20,IWM,0.64,0.37

In [35]:
# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','SOXL']

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [36]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=9,
    parallel_tickers=True,
    max_workers_tickers=2,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,   # ⬅️ додай це
)

▶ Починаємо: 10 тікерів (пропущено 0 по старому маніфесту) | 2025-11-25 00:00:00 → 2026-02-25 23:59:59 | interval=1 | next batch #0022 | run=ead69dc6

   workers: tickers=2, chunks=9 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2025-11-25 → 2026-02-22 (90 днів)

   📈 обробляються дні: 2026-02-23 → 2026-02-25 (3 днів)

   psutil · старт · 🧠 RAM: 2,181.4 MB

[10/10] ✓ SOXL: 4,286 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 2,188.0 MB

💾 batch 22 → 29,200 рядків (всього 29,200 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\ETF\intraday_0022.csv.gz

   ✅ після flush · 🧠 RAM: 2,196.2 MB

   🔚 фінал · 🧠 RAM: 2,196.2 MB

🏁 Готово. Нових рядків: 29,200 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:05

In [37]:
collect_premarket_by_day_stream(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  chunksize=150,000

✅ DONE  in=773,967 → out=773,967  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 2.6s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_etf_rows.parquet'

In [38]:
df_oc = build_oc_from_intraday_folder(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "oc_etf.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date   open  close
0   BITO  2025-10-28  18.96  18.72
1   BITO  2025-10-29  18.70  18.21
2   BITO  2025-10-30  17.83  17.53
3   BITO  2025-10-31  18.09  18.07
4   BITO  2025-11-03  16.89  16.74

In [39]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [40]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=773,967  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 2.7s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [41]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None

def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",   # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Benchk%",  # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        denom = df["prev_close"].replace({0: pd.NA})
        pct = (df[value_col] / denom - 1.0) * 100.0
        if round_to is not None:
            pct = pct.round(round_to)

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",   # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [42]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=773,967  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 0.6s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [43]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception as e:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий файл по ключах ('bench'↔'ticker', 'dt') і пише новий Parquet.
    - У ETF-файлі колонка з відсотком може називатись 'bench%' або 'pct_vs_prev_close' — обидва варіанти підтримуються.
    - Базовий файл не змінюється, додається тільки нова колонка 'Bench%'.
    """

    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    # ---------- 1) Збираємо мапу з ETF-файла: (bench, dt) -> Bench% ----------
    def _read_etf_mapping(etf_parquet: str) -> pd.DataFrame:
        pf = pq.ParquetFile(etf_parquet)
        parts = []
        # читаємо всі колонки, щоб не ловити різні схеми у row-groups
        for batch in pf.iter_batches():
            df = batch.to_pandas()
            # обов'язкові
            for col in ("ticker", "dt"):
                if col not in df.columns:
                    raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")

            # колонка відсотка: bench% або pct_vs_prev_close
            cols_l = {c.lower().strip(): c for c in df.columns}
            if "bench%" in cols_l:
                val_col = cols_l["bench%"]
            elif "pct_vs_prev_close" in cols_l:
                val_col = cols_l["pct_vs_prev_close"]
            else:
                raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

            d = df[["ticker", "dt", val_col]].copy()
            d["ticker"] = d["ticker"].astype(str).str.strip().str.upper()
            d["dt"]     = pd.to_datetime(d["dt"], errors="coerce")
            if align_to_minute:
                d["dt"] = d["dt"].dt.floor("T")
            d = d.dropna(subset=["dt"])
            d = d.rename(columns={"ticker": "bench", val_col: "Bench%"})
            d["Bench%"] = pd.to_numeric(d["Bench%"], errors="coerce")
            parts.append(d)

            del df, d, batch
            gc.collect()

        if not parts:
            return pd.DataFrame(columns=["bench","dt","Bench%"])

        etf_map = pd.concat(parts, ignore_index=True)
        # прибираємо дублікати — залишаємо пізніший запис
        etf_map = (etf_map.sort_values(["bench","dt"])
                           .drop_duplicates(subset=["bench","dt"], keep="last")
                           .reset_index(drop=True))
        return etf_map

    etf_map = _read_etf_mapping(etf_path)
    if round_decimals is not None and "Bench%" in etf_map.columns:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    # ---------- 2) Потоково проходимо базовий файл і підмерджуємо Bench% ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START merge → {out_path}")
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # ключі
        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        df["bench"] = df["bench"].astype(str).str.strip().str.upper()
        df["dt"]    = pd.to_datetime(df["dt"], errors="coerce")
        if align_to_minute:
            df["dt"] = df["dt"].dt.floor("T")

        merged = df.merge(etf_map, on=["bench","dt"], how="left", validate="m:1")

        # розташування 'Bench%'
        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("Bench%")
            pos = cols.index(insert_before)
            cols = cols[:pos] + ["Bench%"] + cols[pos:]
            merged = merged[cols]
        # інакше — залишаємо в кінці як є

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [44]:
merge_bench_pct_from_etf(
    base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    batch_rows=2_000_000,
    align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
    round_decimals=2,
    insert_before=None,          # або, наприклад, "pct_vs_prev_close"
    compression="snappy",
)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet

[batch    5] rows=10,000,000  elapsed=21.1s

[batch   10] rows=20,000,000  elapsed=42.2s

[batch   15] rows=30,000,000  elapsed=63.2s

[batch   20] rows=40,000,000  elapsed=84.6s

[batch   25] rows=50,000,000  elapsed=105.5s

[batch   30] rows=60,000,000  elapsed=126.5s

[batch   35] rows=70,000,000  elapsed=146.9s

[batch   40] rows=80,000,000  elapsed=168.0s

[batch   45] rows=90,000,000  elapsed=189.3s

[batch   50] rows=100,000,000  elapsed=210.5s

[batch   55] rows=109,394,488  elapsed=230.0s
✅ DONE rows=109,394,488 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet  in 230.0s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct.parquet'

In [45]:
import pandas as pd
from tqdm import tqdm   # прогрес-бар

def get_gaps_for_tickers(tickers_df, start_date, end_date):
    """
    Отримує гепи для всіх тикерів із DataFrame tickers_df (колонка 'ticker').
    Використовує ендпоінт /daily/gaps і об’єднує всі результати у один DataFrame.
    """
    all_results = []

    tickers = tickers_df["ticker"].dropna().astype(str).unique().tolist()

    for t in tqdm(tickers, desc="Processing tickers"):
        params = {
            "ticker": t,
            "start_date": start_date,
            "end_date": end_date,
            "format": "json_records"
        }

        try:
            df_gap = DatumApi.data_request("/daily/gaps", params)
            if df_gap is not None and not df_gap.empty:
                all_results.append(df_gap)
        except Exception as e:
            print(f"⚠️ Проблема з {t}: {e}")

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    else:
        return pd.DataFrame()

# === приклад використання ===
df_gaps_all = get_gaps_for_tickers(top1500, start_date = start_date_str, end_date = end_date_str)

print(df_gaps_all.head())
print("Загалом рядків:", len(df_gaps_all))

Processing tickers:   0%|          | 0/6774 [00:00<?, ?it/s]

Processing tickers:   0%|          | 1/6774 [00:00<26:14,  4.30it/s]

Processing tickers:   0%|          | 2/6774 [00:00<24:03,  4.69it/s]

Processing tickers:   0%|          | 3/6774 [00:00<23:20,  4.84it/s]

Processing tickers:   0%|          | 4/6774 [00:00<22:59,  4.91it/s]

Processing tickers:   0%|          | 5/6774 [00:01<22:47,  4.95it/s]

Processing tickers:   0%|          | 6/6774 [00:01<23:07,  4.88it/s]

Processing tickers:   0%|          | 7/6774 [00:01<23:00,  4.90it/s]

Processing tickers:   0%|          | 8/6774 [00:01<22:58,  4.91it/s]

Processing tickers:   0%|          | 9/6774 [00:01<22:48,  4.94it/s]

Processing tickers:   0%|          | 10/6774 [00:02<22:39,  4.98it/s]

Processing tickers:   0%|          | 11/6774 [00:02<22:37,  4.98it/s]

Processing tickers:   0%|          | 12/6774 [00:02<22:46,  4.95it/s]

Processing tickers:   0%|          | 13/6774 [00:02<23:01,  4.89it/s]

Processing tickers:   0%|          | 14/6774 [00:02<22:51,  4.93it/s]

Processing tickers:   0%|          | 15/6774 [00:03<22:44,  4.95it/s]

Processing tickers:   0%|          | 16/6774 [00:03<22:40,  4.97it/s]

Processing tickers:   0%|          | 17/6774 [00:03<22:35,  4.99it/s]

Processing tickers:   0%|          | 18/6774 [00:03<22:30,  5.00it/s]

Processing tickers:   0%|          | 19/6774 [00:03<22:51,  4.92it/s]

Processing tickers:   0%|          | 20/6774 [00:04<22:51,  4.93it/s]

Processing tickers:   0%|          | 21/6774 [00:04<22:44,  4.95it/s]

Processing tickers:   0%|          | 22/6774 [00:04<23:07,  4.87it/s]

Processing tickers:   0%|          | 23/6774 [00:04<22:50,  4.92it/s]

Processing tickers:   0%|          | 24/6774 [00:04<22:55,  4.91it/s]

Processing tickers:   0%|          | 25/6774 [00:05<22:53,  4.92it/s]

Processing tickers:   0%|          | 26/6774 [00:05<22:32,  4.99it/s]

Processing tickers:   0%|          | 27/6774 [00:05<22:48,  4.93it/s]

Processing tickers:   0%|          | 28/6774 [00:05<22:34,  4.98it/s]

Processing tickers:   0%|          | 29/6774 [00:05<22:52,  4.92it/s]

Processing tickers:   0%|          | 30/6774 [00:06<22:43,  4.95it/s]

Processing tickers:   0%|          | 31/6774 [00:06<22:41,  4.95it/s]

Processing tickers:   0%|          | 32/6774 [00:06<22:41,  4.95it/s]

Processing tickers:   0%|          | 33/6774 [00:06<22:44,  4.94it/s]

Processing tickers:   1%|          | 34/6774 [00:06<22:57,  4.89it/s]

Processing tickers:   1%|          | 35/6774 [00:07<22:42,  4.94it/s]

Processing tickers:   1%|          | 36/6774 [00:07<23:38,  4.75it/s]

Processing tickers:   1%|          | 37/6774 [00:07<23:11,  4.84it/s]

Processing tickers:   1%|          | 38/6774 [00:07<23:11,  4.84it/s]

Processing tickers:   1%|          | 39/6774 [00:07<23:10,  4.84it/s]

Processing tickers:   1%|          | 40/6774 [00:08<23:06,  4.86it/s]

Processing tickers:   1%|          | 41/6774 [00:08<23:06,  4.86it/s]

Processing tickers:   1%|          | 42/6774 [00:08<23:03,  4.87it/s]

Processing tickers:   1%|          | 43/6774 [00:08<22:44,  4.93it/s]

Processing tickers:   1%|          | 44/6774 [00:08<22:47,  4.92it/s]

Processing tickers:   1%|          | 45/6774 [00:09<23:05,  4.86it/s]

Processing tickers:   1%|          | 46/6774 [00:09<23:01,  4.87it/s]

Processing tickers:   1%|          | 47/6774 [00:09<23:08,  4.84it/s]

Processing tickers:   1%|          | 48/6774 [00:09<22:58,  4.88it/s]

Processing tickers:   1%|          | 49/6774 [00:09<22:53,  4.90it/s]

Processing tickers:   1%|          | 50/6774 [00:10<22:50,  4.91it/s]

Processing tickers:   1%|          | 51/6774 [00:10<22:43,  4.93it/s]

Processing tickers:   1%|          | 52/6774 [00:10<22:47,  4.92it/s]

Processing tickers:   1%|          | 53/6774 [00:10<22:41,  4.94it/s]

Processing tickers:   1%|          | 54/6774 [00:11<22:41,  4.94it/s]

Processing tickers:   1%|          | 55/6774 [00:11<22:35,  4.96it/s]

Processing tickers:   1%|          | 56/6774 [00:11<22:31,  4.97it/s]

Processing tickers:   1%|          | 57/6774 [00:11<22:39,  4.94it/s]

Processing tickers:   1%|          | 58/6774 [00:11<22:35,  4.95it/s]

Processing tickers:   1%|          | 59/6774 [00:12<22:38,  4.94it/s]

Processing tickers:   1%|          | 60/6774 [00:12<22:45,  4.92it/s]

Processing tickers:   1%|          | 61/6774 [00:12<22:40,  4.93it/s]

Processing tickers:   1%|          | 62/6774 [00:12<22:35,  4.95it/s]

Processing tickers:   1%|          | 63/6774 [00:12<22:31,  4.97it/s]

Processing tickers:   1%|          | 64/6774 [00:13<22:30,  4.97it/s]

Processing tickers:   1%|          | 65/6774 [00:13<22:30,  4.97it/s]

Processing tickers:   1%|          | 66/6774 [00:13<22:31,  4.96it/s]

Processing tickers:   1%|          | 67/6774 [00:13<22:34,  4.95it/s]

Processing tickers:   1%|          | 68/6774 [00:13<22:24,  4.99it/s]

Processing tickers:   1%|          | 69/6774 [00:14<22:22,  4.99it/s]

Processing tickers:   1%|          | 70/6774 [00:14<22:34,  4.95it/s]

Processing tickers:   1%|          | 71/6774 [00:14<22:27,  4.97it/s]

Processing tickers:   1%|          | 72/6774 [00:14<22:28,  4.97it/s]

Processing tickers:   1%|          | 73/6774 [00:14<22:26,  4.98it/s]

Processing tickers:   1%|          | 74/6774 [00:15<22:22,  4.99it/s]

Processing tickers:   1%|          | 75/6774 [00:15<22:16,  5.01it/s]

Processing tickers:   1%|          | 76/6774 [00:15<22:21,  4.99it/s]

Processing tickers:   1%|          | 77/6774 [00:15<22:32,  4.95it/s]

Processing tickers:   1%|          | 78/6774 [00:15<22:23,  4.99it/s]

Processing tickers:   1%|          | 79/6774 [00:16<22:27,  4.97it/s]

Processing tickers:   1%|          | 80/6774 [00:16<23:07,  4.82it/s]

Processing tickers:   1%|          | 81/6774 [00:16<22:51,  4.88it/s]

Processing tickers:   1%|          | 82/6774 [00:16<22:39,  4.92it/s]

Processing tickers:   1%|          | 83/6774 [00:16<22:28,  4.96it/s]

Processing tickers:   1%|          | 84/6774 [00:17<22:21,  4.99it/s]

Processing tickers:   1%|▏         | 85/6774 [00:17<22:10,  5.03it/s]

Processing tickers:   1%|▏         | 86/6774 [00:17<22:10,  5.03it/s]

Processing tickers:   1%|▏         | 87/6774 [00:17<22:09,  5.03it/s]

Processing tickers:   1%|▏         | 88/6774 [00:17<22:17,  5.00it/s]

Processing tickers:   1%|▏         | 89/6774 [00:18<22:10,  5.02it/s]

Processing tickers:   1%|▏         | 90/6774 [00:18<22:06,  5.04it/s]

Processing tickers:   1%|▏         | 91/6774 [00:18<22:08,  5.03it/s]

Processing tickers:   1%|▏         | 92/6774 [00:18<22:15,  5.00it/s]

Processing tickers:   1%|▏         | 93/6774 [00:18<22:23,  4.97it/s]

Processing tickers:   1%|▏         | 94/6774 [00:19<22:23,  4.97it/s]

Processing tickers:   1%|▏         | 95/6774 [00:19<22:40,  4.91it/s]

Processing tickers:   1%|▏         | 96/6774 [00:19<22:24,  4.97it/s]

Processing tickers:   1%|▏         | 97/6774 [00:19<22:26,  4.96it/s]

Processing tickers:   1%|▏         | 98/6774 [00:19<22:44,  4.89it/s]

Processing tickers:   1%|▏         | 99/6774 [00:20<22:35,  4.93it/s]

Processing tickers:   1%|▏         | 100/6774 [00:20<23:17,  4.78it/s]

Processing tickers:   1%|▏         | 101/6774 [00:20<23:55,  4.65it/s]

Processing tickers:   2%|▏         | 102/6774 [00:20<23:38,  4.70it/s]

Processing tickers:   2%|▏         | 103/6774 [00:20<23:17,  4.77it/s]

Processing tickers:   2%|▏         | 104/6774 [00:21<22:49,  4.87it/s]

Processing tickers:   2%|▏         | 105/6774 [00:21<22:46,  4.88it/s]

Processing tickers:   2%|▏         | 106/6774 [00:21<22:42,  4.89it/s]

Processing tickers:   2%|▏         | 107/6774 [00:21<23:02,  4.82it/s]

Processing tickers:   2%|▏         | 108/6774 [00:21<22:47,  4.87it/s]

Processing tickers:   2%|▏         | 109/6774 [00:22<22:41,  4.89it/s]

Processing tickers:   2%|▏         | 110/6774 [00:22<22:39,  4.90it/s]

Processing tickers:   2%|▏         | 111/6774 [00:22<22:32,  4.93it/s]

Processing tickers:   2%|▏         | 112/6774 [00:22<22:35,  4.92it/s]

Processing tickers:   2%|▏         | 113/6774 [00:22<22:28,  4.94it/s]

Processing tickers:   2%|▏         | 114/6774 [00:23<22:19,  4.97it/s]

Processing tickers:   2%|▏         | 115/6774 [00:23<22:25,  4.95it/s]

Processing tickers:   2%|▏         | 116/6774 [00:23<22:22,  4.96it/s]

Processing tickers:   2%|▏         | 117/6774 [00:23<22:36,  4.91it/s]

Processing tickers:   2%|▏         | 118/6774 [00:23<22:44,  4.88it/s]

Processing tickers:   2%|▏         | 119/6774 [00:24<22:58,  4.83it/s]

Processing tickers:   2%|▏         | 120/6774 [00:24<23:49,  4.65it/s]

Processing tickers:   2%|▏         | 121/6774 [00:24<23:20,  4.75it/s]

Processing tickers:   2%|▏         | 122/6774 [00:24<22:59,  4.82it/s]

Processing tickers:   2%|▏         | 123/6774 [00:25<22:38,  4.89it/s]

Processing tickers:   2%|▏         | 124/6774 [00:25<22:35,  4.91it/s]

Processing tickers:   2%|▏         | 125/6774 [00:25<22:24,  4.95it/s]

Processing tickers:   2%|▏         | 126/6774 [00:25<23:09,  4.78it/s]

Processing tickers:   2%|▏         | 127/6774 [00:25<22:53,  4.84it/s]

Processing tickers:   2%|▏         | 128/6774 [00:26<22:55,  4.83it/s]

Processing tickers:   2%|▏         | 129/6774 [00:26<22:38,  4.89it/s]

Processing tickers:   2%|▏         | 130/6774 [00:26<22:28,  4.93it/s]

Processing tickers:   2%|▏         | 131/6774 [00:26<22:22,  4.95it/s]

Processing tickers:   2%|▏         | 132/6774 [00:26<22:14,  4.98it/s]

Processing tickers:   2%|▏         | 133/6774 [00:27<22:12,  4.98it/s]

Processing tickers:   2%|▏         | 134/6774 [00:27<22:20,  4.95it/s]

Processing tickers:   2%|▏         | 135/6774 [00:27<22:15,  4.97it/s]

Processing tickers:   2%|▏         | 136/6774 [00:27<22:18,  4.96it/s]

Processing tickers:   2%|▏         | 137/6774 [00:27<22:18,  4.96it/s]

Processing tickers:   2%|▏         | 138/6774 [00:28<22:23,  4.94it/s]

Processing tickers:   2%|▏         | 139/6774 [00:28<22:38,  4.88it/s]

Processing tickers:   2%|▏         | 140/6774 [00:28<22:46,  4.86it/s]

Processing tickers:   2%|▏         | 141/6774 [00:28<22:33,  4.90it/s]

Processing tickers:   2%|▏         | 142/6774 [00:28<22:27,  4.92it/s]

Processing tickers:   2%|▏         | 143/6774 [00:29<22:20,  4.95it/s]

Processing tickers:   2%|▏         | 144/6774 [00:29<22:16,  4.96it/s]

Processing tickers:   2%|▏         | 145/6774 [00:29<23:15,  4.75it/s]

Processing tickers:   2%|▏         | 146/6774 [00:29<23:53,  4.63it/s]

Processing tickers:   2%|▏         | 147/6774 [00:29<23:31,  4.70it/s]

Processing tickers:   2%|▏         | 148/6774 [00:30<23:05,  4.78it/s]

Processing tickers:   2%|▏         | 149/6774 [00:30<23:29,  4.70it/s]

Processing tickers:   2%|▏         | 150/6774 [00:30<23:07,  4.77it/s]

Processing tickers:   2%|▏         | 151/6774 [00:30<23:06,  4.78it/s]

Processing tickers:   2%|▏         | 152/6774 [00:30<22:40,  4.87it/s]

Processing tickers:   2%|▏         | 153/6774 [00:31<22:40,  4.87it/s]

Processing tickers:   2%|▏         | 154/6774 [00:31<22:33,  4.89it/s]

Processing tickers:   2%|▏         | 155/6774 [00:31<23:12,  4.75it/s]

Processing tickers:   2%|▏         | 156/6774 [00:31<23:00,  4.79it/s]

Processing tickers:   2%|▏         | 157/6774 [00:32<22:42,  4.85it/s]

Processing tickers:   2%|▏         | 158/6774 [00:32<22:29,  4.90it/s]

Processing tickers:   2%|▏         | 159/6774 [00:32<22:16,  4.95it/s]

Processing tickers:   2%|▏         | 160/6774 [00:32<22:09,  4.97it/s]

Processing tickers:   2%|▏         | 161/6774 [00:32<22:22,  4.93it/s]

Processing tickers:   2%|▏         | 162/6774 [00:33<22:23,  4.92it/s]

Processing tickers:   2%|▏         | 163/6774 [00:33<22:28,  4.90it/s]

Processing tickers:   2%|▏         | 164/6774 [00:33<22:17,  4.94it/s]

Processing tickers:   2%|▏         | 165/6774 [00:33<22:07,  4.98it/s]

Processing tickers:   2%|▏         | 166/6774 [00:33<22:05,  4.99it/s]

Processing tickers:   2%|▏         | 167/6774 [00:34<22:30,  4.89it/s]

Processing tickers:   2%|▏         | 168/6774 [00:34<22:11,  4.96it/s]

Processing tickers:   2%|▏         | 169/6774 [00:34<22:11,  4.96it/s]

Processing tickers:   3%|▎         | 170/6774 [00:34<22:04,  4.99it/s]

Processing tickers:   3%|▎         | 171/6774 [00:34<22:10,  4.96it/s]

Processing tickers:   3%|▎         | 172/6774 [00:35<22:10,  4.96it/s]

Processing tickers:   3%|▎         | 173/6774 [00:35<22:05,  4.98it/s]

Processing tickers:   3%|▎         | 174/6774 [00:35<21:59,  5.00it/s]

Processing tickers:   3%|▎         | 175/6774 [00:35<21:57,  5.01it/s]

Processing tickers:   3%|▎         | 176/6774 [00:35<21:55,  5.02it/s]

Processing tickers:   3%|▎         | 177/6774 [00:36<21:56,  5.01it/s]

Processing tickers:   3%|▎         | 178/6774 [00:36<22:32,  4.88it/s]

Processing tickers:   3%|▎         | 179/6774 [00:36<22:10,  4.96it/s]

Processing tickers:   3%|▎         | 180/6774 [00:36<22:22,  4.91it/s]

Processing tickers:   3%|▎         | 181/6774 [00:36<22:39,  4.85it/s]

Processing tickers:   3%|▎         | 182/6774 [00:37<23:09,  4.74it/s]

Processing tickers:   3%|▎         | 183/6774 [00:37<23:27,  4.68it/s]

Processing tickers:   3%|▎         | 184/6774 [00:37<23:07,  4.75it/s]

Processing tickers:   3%|▎         | 185/6774 [00:37<22:45,  4.82it/s]

Processing tickers:   3%|▎         | 186/6774 [00:37<22:53,  4.80it/s]

Processing tickers:   3%|▎         | 187/6774 [00:38<22:38,  4.85it/s]

Processing tickers:   3%|▎         | 188/6774 [00:38<22:27,  4.89it/s]

Processing tickers:   3%|▎         | 189/6774 [00:38<22:17,  4.92it/s]

Processing tickers:   3%|▎         | 190/6774 [00:38<22:22,  4.90it/s]

Processing tickers:   3%|▎         | 191/6774 [00:38<23:00,  4.77it/s]

Processing tickers:   3%|▎         | 192/6774 [00:39<22:38,  4.85it/s]

Processing tickers:   3%|▎         | 193/6774 [00:39<22:27,  4.88it/s]

Processing tickers:   3%|▎         | 194/6774 [00:39<22:57,  4.78it/s]

Processing tickers:   3%|▎         | 195/6774 [00:39<22:35,  4.85it/s]

Processing tickers:   3%|▎         | 196/6774 [00:39<22:30,  4.87it/s]

Processing tickers:   3%|▎         | 197/6774 [00:40<22:45,  4.82it/s]

Processing tickers:   3%|▎         | 198/6774 [00:40<23:15,  4.71it/s]

Processing tickers:   3%|▎         | 199/6774 [00:40<23:03,  4.75it/s]

Processing tickers:   3%|▎         | 200/6774 [00:40<22:42,  4.83it/s]

Processing tickers:   3%|▎         | 201/6774 [00:41<22:27,  4.88it/s]

Processing tickers:   3%|▎         | 202/6774 [00:41<22:36,  4.85it/s]

Processing tickers:   3%|▎         | 203/6774 [00:41<22:23,  4.89it/s]

Processing tickers:   3%|▎         | 204/6774 [00:41<22:15,  4.92it/s]

Processing tickers:   3%|▎         | 205/6774 [00:41<22:05,  4.96it/s]

Processing tickers:   3%|▎         | 206/6774 [00:42<22:02,  4.97it/s]

Processing tickers:   3%|▎         | 207/6774 [00:42<21:53,  5.00it/s]

Processing tickers:   3%|▎         | 208/6774 [00:42<21:52,  5.00it/s]

Processing tickers:   3%|▎         | 209/6774 [00:42<21:46,  5.02it/s]

Processing tickers:   3%|▎         | 210/6774 [00:42<21:48,  5.02it/s]

Processing tickers:   3%|▎         | 211/6774 [00:43<22:23,  4.89it/s]

Processing tickers:   3%|▎         | 212/6774 [00:43<22:34,  4.84it/s]

Processing tickers:   3%|▎         | 213/6774 [00:43<22:21,  4.89it/s]

Processing tickers:   3%|▎         | 214/6774 [00:43<22:11,  4.93it/s]

Processing tickers:   3%|▎         | 215/6774 [00:43<22:05,  4.95it/s]

Processing tickers:   3%|▎         | 216/6774 [00:44<22:01,  4.96it/s]

Processing tickers:   3%|▎         | 217/6774 [00:44<22:04,  4.95it/s]

Processing tickers:   3%|▎         | 218/6774 [00:44<23:08,  4.72it/s]

Processing tickers:   3%|▎         | 219/6774 [00:44<23:44,  4.60it/s]

Processing tickers:   3%|▎         | 220/6774 [00:44<23:12,  4.71it/s]

Processing tickers:   3%|▎         | 221/6774 [00:45<22:46,  4.79it/s]

Processing tickers:   3%|▎         | 222/6774 [00:45<22:51,  4.78it/s]

Processing tickers:   3%|▎         | 223/6774 [00:45<22:32,  4.84it/s]

Processing tickers:   3%|▎         | 224/6774 [00:45<22:19,  4.89it/s]

Processing tickers:   3%|▎         | 225/6774 [00:45<22:09,  4.92it/s]

Processing tickers:   3%|▎         | 226/6774 [00:46<21:56,  4.97it/s]

Processing tickers:   3%|▎         | 227/6774 [00:46<21:54,  4.98it/s]

Processing tickers:   3%|▎         | 228/6774 [00:46<21:48,  5.00it/s]

Processing tickers:   3%|▎         | 229/6774 [00:46<21:56,  4.97it/s]

Processing tickers:   3%|▎         | 230/6774 [00:46<22:37,  4.82it/s]

Processing tickers:   3%|▎         | 231/6774 [00:47<22:48,  4.78it/s]

Processing tickers:   3%|▎         | 232/6774 [00:47<22:26,  4.86it/s]

Processing tickers:   3%|▎         | 233/6774 [00:47<22:17,  4.89it/s]

Processing tickers:   3%|▎         | 234/6774 [00:47<22:10,  4.92it/s]

Processing tickers:   3%|▎         | 235/6774 [00:47<22:00,  4.95it/s]

Processing tickers:   3%|▎         | 236/6774 [00:48<21:52,  4.98it/s]

Processing tickers:   3%|▎         | 237/6774 [00:48<21:56,  4.97it/s]

Processing tickers:   4%|▎         | 238/6774 [00:48<22:20,  4.87it/s]

Processing tickers:   4%|▎         | 239/6774 [00:48<22:09,  4.92it/s]

Processing tickers:   4%|▎         | 240/6774 [00:48<22:09,  4.91it/s]

Processing tickers:   4%|▎         | 241/6774 [00:49<21:59,  4.95it/s]

Processing tickers:   4%|▎         | 242/6774 [00:49<21:55,  4.97it/s]

Processing tickers:   4%|▎         | 243/6774 [00:49<22:28,  4.84it/s]

Processing tickers:   4%|▎         | 244/6774 [00:49<22:17,  4.88it/s]

Processing tickers:   4%|▎         | 245/6774 [00:49<22:01,  4.94it/s]

Processing tickers:   4%|▎         | 246/6774 [00:50<22:01,  4.94it/s]

Processing tickers:   4%|▎         | 247/6774 [00:50<21:53,  4.97it/s]

Processing tickers:   4%|▎         | 248/6774 [00:50<21:43,  5.01it/s]

Processing tickers:   4%|▎         | 249/6774 [00:50<21:41,  5.01it/s]

Processing tickers:   4%|▎         | 250/6774 [00:50<22:15,  4.89it/s]

Processing tickers:   4%|▎         | 251/6774 [00:51<21:58,  4.95it/s]

Processing tickers:   4%|▎         | 252/6774 [00:51<21:54,  4.96it/s]

Processing tickers:   4%|▎         | 253/6774 [00:51<22:10,  4.90it/s]

Processing tickers:   4%|▎         | 254/6774 [00:51<22:02,  4.93it/s]

Processing tickers:   4%|▍         | 255/6774 [00:52<21:54,  4.96it/s]

Processing tickers:   4%|▍         | 256/6774 [00:52<22:23,  4.85it/s]

Processing tickers:   4%|▍         | 257/6774 [00:52<22:42,  4.78it/s]

Processing tickers:   4%|▍         | 258/6774 [00:52<22:19,  4.86it/s]

Processing tickers:   4%|▍         | 259/6774 [00:52<22:06,  4.91it/s]

Processing tickers:   4%|▍         | 260/6774 [00:53<22:50,  4.75it/s]

Processing tickers:   4%|▍         | 261/6774 [00:53<22:59,  4.72it/s]

Processing tickers:   4%|▍         | 262/6774 [00:53<22:55,  4.74it/s]

Processing tickers:   4%|▍         | 263/6774 [00:53<22:31,  4.82it/s]

Processing tickers:   4%|▍         | 264/6774 [00:53<22:28,  4.83it/s]

Processing tickers:   4%|▍         | 265/6774 [00:54<23:08,  4.69it/s]

Processing tickers:   4%|▍         | 266/6774 [00:54<22:42,  4.78it/s]

Processing tickers:   4%|▍         | 267/6774 [00:54<22:19,  4.86it/s]

Processing tickers:   4%|▍         | 268/6774 [00:54<22:43,  4.77it/s]

Processing tickers:   4%|▍         | 269/6774 [00:54<22:26,  4.83it/s]

Processing tickers:   4%|▍         | 270/6774 [00:55<22:10,  4.89it/s]

Processing tickers:   4%|▍         | 271/6774 [00:55<22:09,  4.89it/s]

Processing tickers:   4%|▍         | 272/6774 [00:55<21:55,  4.94it/s]

Processing tickers:   4%|▍         | 273/6774 [00:55<21:45,  4.98it/s]

Processing tickers:   4%|▍         | 274/6774 [00:55<21:42,  4.99it/s]

Processing tickers:   4%|▍         | 275/6774 [00:56<21:41,  4.99it/s]

Processing tickers:   4%|▍         | 276/6774 [00:56<21:39,  5.00it/s]

Processing tickers:   4%|▍         | 277/6774 [00:56<21:37,  5.01it/s]

Processing tickers:   4%|▍         | 278/6774 [00:56<21:37,  5.01it/s]

Processing tickers:   4%|▍         | 279/6774 [00:56<22:36,  4.79it/s]

Processing tickers:   4%|▍         | 280/6774 [00:57<22:25,  4.83it/s]

Processing tickers:   4%|▍         | 281/6774 [00:57<22:15,  4.86it/s]

Processing tickers:   4%|▍         | 282/6774 [00:57<22:25,  4.83it/s]

Processing tickers:   4%|▍         | 283/6774 [00:57<22:11,  4.88it/s]

Processing tickers:   4%|▍         | 284/6774 [00:57<22:04,  4.90it/s]

Processing tickers:   4%|▍         | 285/6774 [00:58<22:10,  4.88it/s]

Processing tickers:   4%|▍         | 286/6774 [00:58<22:20,  4.84it/s]

Processing tickers:   4%|▍         | 287/6774 [00:58<22:07,  4.89it/s]

Processing tickers:   4%|▍         | 288/6774 [00:58<22:10,  4.87it/s]

Processing tickers:   4%|▍         | 289/6774 [00:58<22:01,  4.91it/s]

Processing tickers:   4%|▍         | 290/6774 [00:59<22:08,  4.88it/s]

Processing tickers:   4%|▍         | 291/6774 [00:59<22:02,  4.90it/s]

Processing tickers:   4%|▍         | 292/6774 [00:59<22:05,  4.89it/s]

Processing tickers:   4%|▍         | 293/6774 [00:59<21:59,  4.91it/s]

Processing tickers:   4%|▍         | 294/6774 [01:00<22:33,  4.79it/s]

Processing tickers:   4%|▍         | 295/6774 [01:00<22:21,  4.83it/s]

Processing tickers:   4%|▍         | 296/6774 [01:00<22:35,  4.78it/s]

Processing tickers:   4%|▍         | 297/6774 [01:00<22:42,  4.75it/s]

Processing tickers:   4%|▍         | 298/6774 [01:00<22:19,  4.83it/s]

Processing tickers:   4%|▍         | 299/6774 [01:01<21:57,  4.92it/s]

Processing tickers:   4%|▍         | 300/6774 [01:01<21:45,  4.96it/s]

Processing tickers:   4%|▍         | 301/6774 [01:01<21:38,  4.99it/s]

Processing tickers:   4%|▍         | 302/6774 [01:01<21:36,  4.99it/s]

Processing tickers:   4%|▍         | 303/6774 [01:01<21:38,  4.98it/s]

Processing tickers:   4%|▍         | 304/6774 [01:02<21:36,  4.99it/s]

Processing tickers:   5%|▍         | 305/6774 [01:02<21:53,  4.93it/s]

Processing tickers:   5%|▍         | 306/6774 [01:02<22:35,  4.77it/s]

Processing tickers:   5%|▍         | 307/6774 [01:02<22:16,  4.84it/s]

Processing tickers:   5%|▍         | 308/6774 [01:02<22:17,  4.83it/s]

Processing tickers:   5%|▍         | 309/6774 [01:03<22:03,  4.88it/s]

Processing tickers:   5%|▍         | 310/6774 [01:03<21:52,  4.92it/s]

Processing tickers:   5%|▍         | 311/6774 [01:03<21:53,  4.92it/s]

Processing tickers:   5%|▍         | 312/6774 [01:03<21:49,  4.94it/s]

Processing tickers:   5%|▍         | 313/6774 [01:03<21:42,  4.96it/s]

Processing tickers:   5%|▍         | 314/6774 [01:04<22:04,  4.88it/s]

Processing tickers:   5%|▍         | 315/6774 [01:04<21:52,  4.92it/s]

Processing tickers:   5%|▍         | 316/6774 [01:04<22:20,  4.82it/s]

Processing tickers:   5%|▍         | 317/6774 [01:04<22:07,  4.86it/s]

Processing tickers:   5%|▍         | 318/6774 [01:04<21:50,  4.93it/s]

Processing tickers:   5%|▍         | 319/6774 [01:05<21:43,  4.95it/s]

Processing tickers:   5%|▍         | 320/6774 [01:05<22:30,  4.78it/s]

Processing tickers:   5%|▍         | 321/6774 [01:05<22:34,  4.76it/s]

Processing tickers:   5%|▍         | 322/6774 [01:05<22:21,  4.81it/s]

Processing tickers:   5%|▍         | 323/6774 [01:05<22:05,  4.87it/s]

Processing tickers:   5%|▍         | 324/6774 [01:06<21:56,  4.90it/s]

Processing tickers:   5%|▍         | 325/6774 [01:06<22:07,  4.86it/s]

Processing tickers:   5%|▍         | 326/6774 [01:06<22:43,  4.73it/s]

Processing tickers:   5%|▍         | 327/6774 [01:06<22:22,  4.80it/s]

Processing tickers:   5%|▍         | 328/6774 [01:07<22:20,  4.81it/s]

Processing tickers:   5%|▍         | 329/6774 [01:07<22:01,  4.88it/s]

Processing tickers:   5%|▍         | 330/6774 [01:07<21:49,  4.92it/s]

Processing tickers:   5%|▍         | 331/6774 [01:07<22:47,  4.71it/s]

Processing tickers:   5%|▍         | 332/6774 [01:07<22:46,  4.71it/s]

Processing tickers:   5%|▍         | 333/6774 [01:08<22:26,  4.78it/s]

Processing tickers:   5%|▍         | 334/6774 [01:08<22:06,  4.85it/s]

Processing tickers:   5%|▍         | 335/6774 [01:08<21:53,  4.90it/s]

Processing tickers:   5%|▍         | 336/6774 [01:08<21:49,  4.92it/s]

Processing tickers:   5%|▍         | 337/6774 [01:08<21:37,  4.96it/s]

Processing tickers:   5%|▍         | 338/6774 [01:09<21:40,  4.95it/s]

Processing tickers:   5%|▌         | 339/6774 [01:09<21:48,  4.92it/s]

Processing tickers:   5%|▌         | 340/6774 [01:09<22:47,  4.70it/s]

Processing tickers:   5%|▌         | 341/6774 [01:09<22:25,  4.78it/s]

Processing tickers:   5%|▌         | 342/6774 [01:09<22:37,  4.74it/s]

Processing tickers:   5%|▌         | 343/6774 [01:10<22:16,  4.81it/s]

Processing tickers:   5%|▌         | 344/6774 [01:10<22:08,  4.84it/s]

Processing tickers:   5%|▌         | 345/6774 [01:10<21:51,  4.90it/s]

Processing tickers:   5%|▌         | 346/6774 [01:10<21:42,  4.94it/s]

Processing tickers:   5%|▌         | 347/6774 [01:10<21:49,  4.91it/s]

Processing tickers:   5%|▌         | 348/6774 [01:11<21:44,  4.93it/s]

Processing tickers:   5%|▌         | 349/6774 [01:11<21:37,  4.95it/s]

Processing tickers:   5%|▌         | 350/6774 [01:11<21:24,  5.00it/s]

Processing tickers:   5%|▌         | 351/6774 [01:11<21:29,  4.98it/s]

Processing tickers:   5%|▌         | 352/6774 [01:11<21:32,  4.97it/s]

Processing tickers:   5%|▌         | 353/6774 [01:12<21:27,  4.99it/s]

Processing tickers:   5%|▌         | 354/6774 [01:12<21:26,  4.99it/s]

Processing tickers:   5%|▌         | 355/6774 [01:12<21:20,  5.01it/s]

Processing tickers:   5%|▌         | 356/6774 [01:12<21:14,  5.03it/s]

Processing tickers:   5%|▌         | 357/6774 [01:12<21:22,  5.00it/s]

Processing tickers:   5%|▌         | 358/6774 [01:13<21:23,  5.00it/s]

Processing tickers:   5%|▌         | 359/6774 [01:13<21:12,  5.04it/s]

Processing tickers:   5%|▌         | 360/6774 [01:13<21:22,  5.00it/s]

Processing tickers:   5%|▌         | 361/6774 [01:13<21:33,  4.96it/s]

Processing tickers:   5%|▌         | 362/6774 [01:13<21:30,  4.97it/s]

Processing tickers:   5%|▌         | 363/6774 [01:14<21:28,  4.97it/s]

Processing tickers:   5%|▌         | 364/6774 [01:14<21:28,  4.98it/s]

Processing tickers:   5%|▌         | 365/6774 [01:14<21:45,  4.91it/s]

Processing tickers:   5%|▌         | 366/6774 [01:14<21:41,  4.93it/s]

Processing tickers:   5%|▌         | 367/6774 [01:14<21:41,  4.92it/s]

Processing tickers:   5%|▌         | 368/6774 [01:15<21:28,  4.97it/s]

Processing tickers:   5%|▌         | 369/6774 [01:15<21:19,  5.01it/s]

Processing tickers:   5%|▌         | 370/6774 [01:15<21:59,  4.85it/s]

Processing tickers:   5%|▌         | 371/6774 [01:15<21:58,  4.86it/s]

Processing tickers:   5%|▌         | 372/6774 [01:15<21:42,  4.92it/s]

Processing tickers:   6%|▌         | 373/6774 [01:16<21:32,  4.95it/s]

Processing tickers:   6%|▌         | 374/6774 [01:16<21:34,  4.95it/s]

Processing tickers:   6%|▌         | 375/6774 [01:16<21:38,  4.93it/s]

Processing tickers:   6%|▌         | 376/6774 [01:16<22:12,  4.80it/s]

Processing tickers:   6%|▌         | 377/6774 [01:16<22:00,  4.84it/s]

Processing tickers:   6%|▌         | 378/6774 [01:17<21:51,  4.88it/s]

Processing tickers:   6%|▌         | 379/6774 [01:17<22:37,  4.71it/s]

Processing tickers:   6%|▌         | 380/6774 [01:17<22:10,  4.81it/s]

Processing tickers:   6%|▌         | 381/6774 [01:17<22:41,  4.70it/s]

Processing tickers:   6%|▌         | 382/6774 [01:18<22:31,  4.73it/s]

Processing tickers:   6%|▌         | 383/6774 [01:18<22:09,  4.81it/s]

Processing tickers:   6%|▌         | 384/6774 [01:18<21:49,  4.88it/s]

Processing tickers:   6%|▌         | 385/6774 [01:18<22:00,  4.84it/s]

Processing tickers:   6%|▌         | 386/6774 [01:18<21:49,  4.88it/s]

Processing tickers:   6%|▌         | 387/6774 [01:19<21:36,  4.93it/s]

Processing tickers:   6%|▌         | 388/6774 [01:19<21:40,  4.91it/s]

Processing tickers:   6%|▌         | 389/6774 [01:19<22:20,  4.76it/s]

Processing tickers:   6%|▌         | 390/6774 [01:19<22:29,  4.73it/s]

Processing tickers:   6%|▌         | 391/6774 [01:19<22:05,  4.82it/s]

Processing tickers:   6%|▌         | 392/6774 [01:20<21:50,  4.87it/s]

Processing tickers:   6%|▌         | 393/6774 [01:20<21:53,  4.86it/s]

Processing tickers:   6%|▌         | 394/6774 [01:20<21:41,  4.90it/s]

Processing tickers:   6%|▌         | 395/6774 [01:20<21:35,  4.93it/s]

Processing tickers:   6%|▌         | 396/6774 [01:20<21:24,  4.96it/s]

Processing tickers:   6%|▌         | 397/6774 [01:21<21:32,  4.93it/s]

Processing tickers:   6%|▌         | 398/6774 [01:21<21:30,  4.94it/s]

Processing tickers:   6%|▌         | 399/6774 [01:21<21:13,  5.01it/s]

Processing tickers:   6%|▌         | 400/6774 [01:21<21:15,  5.00it/s]

Processing tickers:   6%|▌         | 401/6774 [01:21<21:17,  4.99it/s]

Processing tickers:   6%|▌         | 402/6774 [01:22<21:18,  4.98it/s]

Processing tickers:   6%|▌         | 403/6774 [01:22<21:19,  4.98it/s]

Processing tickers:   6%|▌         | 404/6774 [01:22<21:24,  4.96it/s]

Processing tickers:   6%|▌         | 405/6774 [01:22<21:22,  4.96it/s]

Processing tickers:   6%|▌         | 406/6774 [01:22<21:32,  4.93it/s]

Processing tickers:   6%|▌         | 407/6774 [01:23<21:30,  4.93it/s]

Processing tickers:   6%|▌         | 408/6774 [01:23<21:23,  4.96it/s]

Processing tickers:   6%|▌         | 409/6774 [01:23<21:19,  4.97it/s]

Processing tickers:   6%|▌         | 410/6774 [01:23<21:27,  4.94it/s]

Processing tickers:   6%|▌         | 411/6774 [01:23<21:30,  4.93it/s]

Processing tickers:   6%|▌         | 412/6774 [01:24<21:28,  4.94it/s]

Processing tickers:   6%|▌         | 413/6774 [01:24<21:21,  4.96it/s]

Processing tickers:   6%|▌         | 414/6774 [01:24<21:51,  4.85it/s]

Processing tickers:   6%|▌         | 415/6774 [01:24<21:46,  4.87it/s]

Processing tickers:   6%|▌         | 416/6774 [01:24<21:31,  4.92it/s]

Processing tickers:   6%|▌         | 417/6774 [01:25<21:49,  4.85it/s]

Processing tickers:   6%|▌         | 418/6774 [01:25<22:39,  4.67it/s]

Processing tickers:   6%|▌         | 419/6774 [01:25<22:11,  4.77it/s]

Processing tickers:   6%|▌         | 420/6774 [01:25<21:50,  4.85it/s]

Processing tickers:   6%|▌         | 421/6774 [01:25<21:39,  4.89it/s]

Processing tickers:   6%|▌         | 422/6774 [01:26<21:46,  4.86it/s]

Processing tickers:   6%|▌         | 423/6774 [01:26<21:42,  4.88it/s]

Processing tickers:   6%|▋         | 424/6774 [01:26<21:34,  4.91it/s]

Processing tickers:   6%|▋         | 425/6774 [01:26<21:48,  4.85it/s]

Processing tickers:   6%|▋         | 426/6774 [01:27<21:37,  4.89it/s]

Processing tickers:   6%|▋         | 427/6774 [01:27<21:28,  4.93it/s]

Processing tickers:   6%|▋         | 428/6774 [01:27<21:22,  4.95it/s]

Processing tickers:   6%|▋         | 429/6774 [01:27<21:19,  4.96it/s]

Processing tickers:   6%|▋         | 430/6774 [01:27<21:10,  4.99it/s]

Processing tickers:   6%|▋         | 431/6774 [01:28<21:04,  5.02it/s]

Processing tickers:   6%|▋         | 432/6774 [01:28<21:05,  5.01it/s]

Processing tickers:   6%|▋         | 433/6774 [01:28<21:00,  5.03it/s]

Processing tickers:   6%|▋         | 434/6774 [01:28<21:09,  5.00it/s]

Processing tickers:   6%|▋         | 435/6774 [01:28<21:08,  5.00it/s]

Processing tickers:   6%|▋         | 436/6774 [01:29<21:22,  4.94it/s]

Processing tickers:   6%|▋         | 437/6774 [01:29<21:13,  4.98it/s]

Processing tickers:   6%|▋         | 438/6774 [01:29<21:12,  4.98it/s]

Processing tickers:   6%|▋         | 439/6774 [01:29<22:19,  4.73it/s]

Processing tickers:   6%|▋         | 440/6774 [01:29<22:05,  4.78it/s]

Processing tickers:   7%|▋         | 441/6774 [01:30<21:50,  4.83it/s]

Processing tickers:   7%|▋         | 442/6774 [01:30<21:34,  4.89it/s]

Processing tickers:   7%|▋         | 443/6774 [01:30<21:23,  4.93it/s]

Processing tickers:   7%|▋         | 444/6774 [01:30<21:31,  4.90it/s]

Processing tickers:   7%|▋         | 445/6774 [01:30<21:22,  4.94it/s]

Processing tickers:   7%|▋         | 446/6774 [01:31<21:18,  4.95it/s]

Processing tickers:   7%|▋         | 447/6774 [01:31<21:42,  4.86it/s]

Processing tickers:   7%|▋         | 448/6774 [01:31<21:47,  4.84it/s]

Processing tickers:   7%|▋         | 449/6774 [01:31<21:34,  4.89it/s]

Processing tickers:   7%|▋         | 450/6774 [01:31<21:28,  4.91it/s]

Processing tickers:   7%|▋         | 451/6774 [01:32<22:11,  4.75it/s]

Processing tickers:   7%|▋         | 452/6774 [01:32<21:49,  4.83it/s]

Processing tickers:   7%|▋         | 453/6774 [01:32<22:07,  4.76it/s]

Processing tickers:   7%|▋         | 454/6774 [01:32<21:48,  4.83it/s]

Processing tickers:   7%|▋         | 455/6774 [01:32<21:36,  4.87it/s]

Processing tickers:   7%|▋         | 456/6774 [01:33<21:19,  4.94it/s]

Processing tickers:   7%|▋         | 457/6774 [01:33<21:16,  4.95it/s]

Processing tickers:   7%|▋         | 458/6774 [01:33<21:18,  4.94it/s]

Processing tickers:   7%|▋         | 459/6774 [01:33<21:04,  4.99it/s]

Processing tickers:   7%|▋         | 460/6774 [01:33<21:12,  4.96it/s]

Processing tickers:   7%|▋         | 461/6774 [01:34<21:10,  4.97it/s]

Processing tickers:   7%|▋         | 462/6774 [01:34<21:04,  4.99it/s]

Processing tickers:   7%|▋         | 463/6774 [01:34<21:01,  5.00it/s]

Processing tickers:   7%|▋         | 464/6774 [01:34<21:37,  4.86it/s]

Processing tickers:   7%|▋         | 465/6774 [01:34<21:45,  4.83it/s]

Processing tickers:   7%|▋         | 466/6774 [01:35<21:40,  4.85it/s]

Processing tickers:   7%|▋         | 467/6774 [01:35<21:39,  4.85it/s]

Processing tickers:   7%|▋         | 468/6774 [01:35<21:25,  4.90it/s]

Processing tickers:   7%|▋         | 469/6774 [01:35<21:17,  4.94it/s]

Processing tickers:   7%|▋         | 470/6774 [01:35<21:05,  4.98it/s]

Processing tickers:   7%|▋         | 471/6774 [01:36<21:14,  4.95it/s]

Processing tickers:   7%|▋         | 472/6774 [01:36<21:11,  4.96it/s]

Processing tickers:   7%|▋         | 473/6774 [01:36<21:07,  4.97it/s]

Processing tickers:   7%|▋         | 474/6774 [01:36<21:10,  4.96it/s]

Processing tickers:   7%|▋         | 475/6774 [01:36<21:23,  4.91it/s]

Processing tickers:   7%|▋         | 476/6774 [01:37<21:14,  4.94it/s]

Processing tickers:   7%|▋         | 477/6774 [01:37<21:11,  4.95it/s]

Processing tickers:   7%|▋         | 478/6774 [01:37<21:05,  4.98it/s]

Processing tickers:   7%|▋         | 479/6774 [01:37<20:54,  5.02it/s]

Processing tickers:   7%|▋         | 480/6774 [01:37<20:59,  5.00it/s]

Processing tickers:   7%|▋         | 481/6774 [01:38<21:05,  4.97it/s]

Processing tickers:   7%|▋         | 482/6774 [01:38<20:53,  5.02it/s]

Processing tickers:   7%|▋         | 483/6774 [01:38<20:56,  5.01it/s]

Processing tickers:   7%|▋         | 484/6774 [01:38<20:49,  5.03it/s]

Processing tickers:   7%|▋         | 485/6774 [01:38<20:59,  4.99it/s]

Processing tickers:   7%|▋         | 486/6774 [01:39<21:14,  4.93it/s]

Processing tickers:   7%|▋         | 487/6774 [01:39<21:35,  4.85it/s]

Processing tickers:   7%|▋         | 488/6774 [01:39<21:16,  4.92it/s]

Processing tickers:   7%|▋         | 489/6774 [01:39<21:13,  4.94it/s]

Processing tickers:   7%|▋         | 490/6774 [01:39<21:09,  4.95it/s]

Processing tickers:   7%|▋         | 491/6774 [01:40<21:11,  4.94it/s]

Processing tickers:   7%|▋         | 492/6774 [01:40<21:19,  4.91it/s]

Processing tickers:   7%|▋         | 493/6774 [01:40<21:15,  4.93it/s]

Processing tickers:   7%|▋         | 494/6774 [01:40<21:14,  4.93it/s]

Processing tickers:   7%|▋         | 495/6774 [01:41<21:02,  4.97it/s]

Processing tickers:   7%|▋         | 496/6774 [01:41<21:04,  4.97it/s]

Processing tickers:   7%|▋         | 497/6774 [01:41<21:01,  4.97it/s]

Processing tickers:   7%|▋         | 498/6774 [01:41<21:09,  4.94it/s]

Processing tickers:   7%|▋         | 499/6774 [01:41<21:06,  4.96it/s]

Processing tickers:   7%|▋         | 500/6774 [01:42<21:04,  4.96it/s]

Processing tickers:   7%|▋         | 501/6774 [01:42<21:06,  4.95it/s]

Processing tickers:   7%|▋         | 502/6774 [01:42<21:21,  4.89it/s]

Processing tickers:   7%|▋         | 503/6774 [01:42<21:13,  4.93it/s]

Processing tickers:   7%|▋         | 504/6774 [01:42<21:06,  4.95it/s]

Processing tickers:   7%|▋         | 505/6774 [01:43<20:59,  4.98it/s]

Processing tickers:   7%|▋         | 506/6774 [01:43<21:11,  4.93it/s]

Processing tickers:   7%|▋         | 507/6774 [01:43<20:59,  4.98it/s]

Processing tickers:   7%|▋         | 508/6774 [01:43<21:02,  4.96it/s]

Processing tickers:   8%|▊         | 509/6774 [01:43<20:54,  4.99it/s]

Processing tickers:   8%|▊         | 510/6774 [01:44<20:54,  4.99it/s]

Processing tickers:   8%|▊         | 511/6774 [01:44<20:53,  5.00it/s]

Processing tickers:   8%|▊         | 512/6774 [01:44<20:52,  5.00it/s]

Processing tickers:   8%|▊         | 513/6774 [01:44<21:30,  4.85it/s]

Processing tickers:   8%|▊         | 514/6774 [01:44<21:20,  4.89it/s]

Processing tickers:   8%|▊         | 515/6774 [01:45<21:08,  4.93it/s]

Processing tickers:   8%|▊         | 516/6774 [01:45<21:10,  4.92it/s]

Processing tickers:   8%|▊         | 517/6774 [01:45<21:04,  4.95it/s]

Processing tickers:   8%|▊         | 518/6774 [01:45<21:00,  4.96it/s]

Processing tickers:   8%|▊         | 519/6774 [01:45<21:46,  4.79it/s]

Processing tickers:   8%|▊         | 520/6774 [01:46<21:35,  4.83it/s]

Processing tickers:   8%|▊         | 521/6774 [01:46<21:13,  4.91it/s]

Processing tickers:   8%|▊         | 522/6774 [01:46<21:27,  4.86it/s]

Processing tickers:   8%|▊         | 523/6774 [01:46<21:14,  4.90it/s]

Processing tickers:   8%|▊         | 524/6774 [01:46<21:28,  4.85it/s]

Processing tickers:   8%|▊         | 525/6774 [01:47<21:19,  4.89it/s]

Processing tickers:   8%|▊         | 526/6774 [01:47<21:09,  4.92it/s]

Processing tickers:   8%|▊         | 527/6774 [01:47<21:08,  4.92it/s]

Processing tickers:   8%|▊         | 528/6774 [01:47<21:10,  4.92it/s]

Processing tickers:   8%|▊         | 529/6774 [01:47<21:10,  4.91it/s]

Processing tickers:   8%|▊         | 530/6774 [01:48<20:58,  4.96it/s]

Processing tickers:   8%|▊         | 531/6774 [01:48<21:11,  4.91it/s]

Processing tickers:   8%|▊         | 532/6774 [01:48<21:09,  4.92it/s]

Processing tickers:   8%|▊         | 533/6774 [01:48<21:09,  4.91it/s]

Processing tickers:   8%|▊         | 534/6774 [01:48<21:03,  4.94it/s]

Processing tickers:   8%|▊         | 535/6774 [01:49<21:04,  4.93it/s]

Processing tickers:   8%|▊         | 536/6774 [01:49<20:52,  4.98it/s]

Processing tickers:   8%|▊         | 537/6774 [01:49<20:50,  4.99it/s]

Processing tickers:   8%|▊         | 538/6774 [01:49<20:48,  4.99it/s]

Processing tickers:   8%|▊         | 539/6774 [01:49<21:20,  4.87it/s]

Processing tickers:   8%|▊         | 540/6774 [01:50<21:06,  4.92it/s]

Processing tickers:   8%|▊         | 541/6774 [01:50<21:12,  4.90it/s]

Processing tickers:   8%|▊         | 542/6774 [01:50<21:10,  4.91it/s]

Processing tickers:   8%|▊         | 543/6774 [01:50<20:58,  4.95it/s]

Processing tickers:   8%|▊         | 544/6774 [01:50<21:14,  4.89it/s]

Processing tickers:   8%|▊         | 545/6774 [01:51<21:03,  4.93it/s]

Processing tickers:   8%|▊         | 546/6774 [01:51<20:49,  4.98it/s]

Processing tickers:   8%|▊         | 547/6774 [01:51<20:42,  5.01it/s]

Processing tickers:   8%|▊         | 548/6774 [01:51<20:41,  5.01it/s]

Processing tickers:   8%|▊         | 549/6774 [01:51<20:44,  5.00it/s]

Processing tickers:   8%|▊         | 550/6774 [01:52<20:49,  4.98it/s]

Processing tickers:   8%|▊         | 551/6774 [01:52<20:46,  4.99it/s]

Processing tickers:   8%|▊         | 552/6774 [01:52<20:45,  5.00it/s]

Processing tickers:   8%|▊         | 553/6774 [01:52<20:40,  5.01it/s]

Processing tickers:   8%|▊         | 554/6774 [01:52<20:38,  5.02it/s]

Processing tickers:   8%|▊         | 555/6774 [01:53<20:41,  5.01it/s]

Processing tickers:   8%|▊         | 556/6774 [01:53<20:40,  5.01it/s]

Processing tickers:   8%|▊         | 557/6774 [01:53<20:55,  4.95it/s]

Processing tickers:   8%|▊         | 558/6774 [01:53<20:51,  4.97it/s]

Processing tickers:   8%|▊         | 559/6774 [01:53<20:47,  4.98it/s]

Processing tickers:   8%|▊         | 560/6774 [01:54<20:42,  5.00it/s]

Processing tickers:   8%|▊         | 561/6774 [01:54<20:44,  4.99it/s]

Processing tickers:   8%|▊         | 562/6774 [01:54<20:39,  5.01it/s]

Processing tickers:   8%|▊         | 563/6774 [01:54<20:44,  4.99it/s]

Processing tickers:   8%|▊         | 564/6774 [01:54<20:48,  4.97it/s]

Processing tickers:   8%|▊         | 565/6774 [01:55<20:46,  4.98it/s]

Processing tickers:   8%|▊         | 566/6774 [01:55<20:47,  4.98it/s]

Processing tickers:   8%|▊         | 567/6774 [01:55<20:50,  4.96it/s]

Processing tickers:   8%|▊         | 568/6774 [01:55<21:00,  4.92it/s]

Processing tickers:   8%|▊         | 569/6774 [01:55<21:26,  4.82it/s]

Processing tickers:   8%|▊         | 570/6774 [01:56<21:20,  4.84it/s]

Processing tickers:   8%|▊         | 571/6774 [01:56<21:18,  4.85it/s]

Processing tickers:   8%|▊         | 572/6774 [01:56<21:12,  4.87it/s]

Processing tickers:   8%|▊         | 573/6774 [01:56<20:58,  4.93it/s]

Processing tickers:   8%|▊         | 574/6774 [01:57<21:11,  4.88it/s]

Processing tickers:   8%|▊         | 575/6774 [01:57<20:56,  4.93it/s]

Processing tickers:   9%|▊         | 576/6774 [01:57<21:12,  4.87it/s]

Processing tickers:   9%|▊         | 577/6774 [01:57<21:03,  4.90it/s]

Processing tickers:   9%|▊         | 578/6774 [01:57<20:45,  4.97it/s]

Processing tickers:   9%|▊         | 579/6774 [01:58<20:41,  4.99it/s]

Processing tickers:   9%|▊         | 580/6774 [01:58<20:47,  4.96it/s]

Processing tickers:   9%|▊         | 581/6774 [01:58<20:50,  4.95it/s]

Processing tickers:   9%|▊         | 582/6774 [01:58<20:44,  4.98it/s]

Processing tickers:   9%|▊         | 583/6774 [01:58<20:54,  4.93it/s]

Processing tickers:   9%|▊         | 584/6774 [01:59<20:55,  4.93it/s]

Processing tickers:   9%|▊         | 585/6774 [01:59<20:47,  4.96it/s]

Processing tickers:   9%|▊         | 586/6774 [01:59<20:50,  4.95it/s]

Processing tickers:   9%|▊         | 587/6774 [01:59<20:46,  4.96it/s]

Processing tickers:   9%|▊         | 588/6774 [01:59<20:40,  4.99it/s]

Processing tickers:   9%|▊         | 589/6774 [02:00<20:34,  5.01it/s]

Processing tickers:   9%|▊         | 590/6774 [02:00<20:40,  4.98it/s]

Processing tickers:   9%|▊         | 591/6774 [02:00<20:37,  5.00it/s]

Processing tickers:   9%|▊         | 592/6774 [02:00<20:37,  4.99it/s]

Processing tickers:   9%|▉         | 593/6774 [02:00<21:04,  4.89it/s]

Processing tickers:   9%|▉         | 594/6774 [02:01<20:52,  4.93it/s]

Processing tickers:   9%|▉         | 595/6774 [02:01<20:52,  4.93it/s]

Processing tickers:   9%|▉         | 596/6774 [02:01<20:44,  4.97it/s]

Processing tickers:   9%|▉         | 597/6774 [02:01<20:35,  5.00it/s]

Processing tickers:   9%|▉         | 598/6774 [02:01<20:32,  5.01it/s]

Processing tickers:   9%|▉         | 599/6774 [02:02<20:31,  5.01it/s]

Processing tickers:   9%|▉         | 600/6774 [02:02<20:32,  5.01it/s]

Processing tickers:   9%|▉         | 601/6774 [02:02<20:28,  5.03it/s]

Processing tickers:   9%|▉         | 602/6774 [02:02<20:31,  5.01it/s]

Processing tickers:   9%|▉         | 603/6774 [02:02<20:25,  5.03it/s]

Processing tickers:   9%|▉         | 604/6774 [02:03<20:54,  4.92it/s]

Processing tickers:   9%|▉         | 605/6774 [02:03<20:48,  4.94it/s]

Processing tickers:   9%|▉         | 606/6774 [02:03<20:43,  4.96it/s]

Processing tickers:   9%|▉         | 607/6774 [02:03<20:31,  5.01it/s]

Processing tickers:   9%|▉         | 608/6774 [02:03<20:28,  5.02it/s]

Processing tickers:   9%|▉         | 609/6774 [02:04<20:27,  5.02it/s]

Processing tickers:   9%|▉         | 610/6774 [02:04<20:18,  5.06it/s]

Processing tickers:   9%|▉         | 611/6774 [02:04<20:21,  5.04it/s]

Processing tickers:   9%|▉         | 612/6774 [02:04<20:25,  5.03it/s]

Processing tickers:   9%|▉         | 613/6774 [02:04<20:37,  4.98it/s]

Processing tickers:   9%|▉         | 614/6774 [02:05<20:34,  4.99it/s]

Processing tickers:   9%|▉         | 615/6774 [02:05<20:30,  5.00it/s]

Processing tickers:   9%|▉         | 616/6774 [02:05<21:08,  4.86it/s]

Processing tickers:   9%|▉         | 617/6774 [02:05<20:57,  4.90it/s]

Processing tickers:   9%|▉         | 618/6774 [02:05<20:51,  4.92it/s]

Processing tickers:   9%|▉         | 619/6774 [02:06<20:44,  4.95it/s]

Processing tickers:   9%|▉         | 620/6774 [02:06<20:55,  4.90it/s]

Processing tickers:   9%|▉         | 621/6774 [02:06<21:24,  4.79it/s]

Processing tickers:   9%|▉         | 622/6774 [02:06<21:23,  4.79it/s]

Processing tickers:   9%|▉         | 623/6774 [02:06<21:04,  4.87it/s]

Processing tickers:   9%|▉         | 624/6774 [02:07<20:50,  4.92it/s]

Processing tickers:   9%|▉         | 625/6774 [02:07<20:40,  4.96it/s]

Processing tickers:   9%|▉         | 626/6774 [02:07<20:55,  4.90it/s]

Processing tickers:   9%|▉         | 627/6774 [02:07<20:47,  4.93it/s]

Processing tickers:   9%|▉         | 628/6774 [02:07<21:05,  4.86it/s]

Processing tickers:   9%|▉         | 629/6774 [02:08<20:50,  4.91it/s]

Processing tickers:   9%|▉         | 630/6774 [02:08<20:40,  4.95it/s]

Processing tickers:   9%|▉         | 631/6774 [02:08<20:31,  4.99it/s]

Processing tickers:   9%|▉         | 632/6774 [02:08<20:45,  4.93it/s]

Processing tickers:   9%|▉         | 633/6774 [02:08<20:35,  4.97it/s]

Processing tickers:   9%|▉         | 634/6774 [02:09<20:28,  5.00it/s]

Processing tickers:   9%|▉         | 635/6774 [02:09<20:47,  4.92it/s]

Processing tickers:   9%|▉         | 636/6774 [02:09<20:43,  4.93it/s]

Processing tickers:   9%|▉         | 637/6774 [02:09<20:38,  4.96it/s]

Processing tickers:   9%|▉         | 638/6774 [02:09<20:32,  4.98it/s]

Processing tickers:   9%|▉         | 639/6774 [02:10<20:33,  4.97it/s]

Processing tickers:   9%|▉         | 640/6774 [02:10<20:34,  4.97it/s]

Processing tickers:   9%|▉         | 641/6774 [02:10<20:35,  4.96it/s]

Processing tickers:   9%|▉         | 642/6774 [02:10<20:39,  4.95it/s]

Processing tickers:   9%|▉         | 643/6774 [02:10<20:29,  4.99it/s]

Processing tickers:  10%|▉         | 644/6774 [02:11<20:25,  5.00it/s]

Processing tickers:  10%|▉         | 645/6774 [02:11<20:41,  4.94it/s]

Processing tickers:  10%|▉         | 646/6774 [02:11<20:28,  4.99it/s]

Processing tickers:  10%|▉         | 647/6774 [02:11<20:36,  4.96it/s]

Processing tickers:  10%|▉         | 648/6774 [02:11<21:10,  4.82it/s]

Processing tickers:  10%|▉         | 649/6774 [02:12<20:49,  4.90it/s]

Processing tickers:  10%|▉         | 650/6774 [02:12<21:01,  4.86it/s]

Processing tickers:  10%|▉         | 651/6774 [02:12<20:56,  4.87it/s]

Processing tickers:  10%|▉         | 652/6774 [02:12<20:45,  4.92it/s]

Processing tickers:  10%|▉         | 653/6774 [02:12<20:56,  4.87it/s]

Processing tickers:  10%|▉         | 654/6774 [02:13<21:16,  4.79it/s]

Processing tickers:  10%|▉         | 655/6774 [02:13<21:34,  4.73it/s]

Processing tickers:  10%|▉         | 656/6774 [02:13<21:08,  4.82it/s]

Processing tickers:  10%|▉         | 657/6774 [02:13<20:52,  4.88it/s]

Processing tickers:  10%|▉         | 658/6774 [02:13<20:44,  4.92it/s]

Processing tickers:  10%|▉         | 659/6774 [02:14<20:38,  4.94it/s]

Processing tickers:  10%|▉         | 660/6774 [02:14<20:35,  4.95it/s]

Processing tickers:  10%|▉         | 661/6774 [02:14<20:34,  4.95it/s]

Processing tickers:  10%|▉         | 662/6774 [02:14<20:32,  4.96it/s]

Processing tickers:  10%|▉         | 663/6774 [02:15<20:30,  4.97it/s]

Processing tickers:  10%|▉         | 664/6774 [02:15<20:40,  4.93it/s]

Processing tickers:  10%|▉         | 665/6774 [02:15<21:23,  4.76it/s]

Processing tickers:  10%|▉         | 666/6774 [02:15<21:06,  4.82it/s]

Processing tickers:  10%|▉         | 667/6774 [02:15<20:49,  4.89it/s]

Processing tickers:  10%|▉         | 668/6774 [02:16<20:57,  4.86it/s]

Processing tickers:  10%|▉         | 669/6774 [02:16<21:31,  4.73it/s]

Processing tickers:  10%|▉         | 670/6774 [02:16<21:24,  4.75it/s]

Processing tickers:  10%|▉         | 671/6774 [02:16<21:03,  4.83it/s]

Processing tickers:  10%|▉         | 672/6774 [02:16<20:52,  4.87it/s]

Processing tickers:  10%|▉         | 673/6774 [02:17<20:48,  4.89it/s]

Processing tickers:  10%|▉         | 674/6774 [02:17<20:36,  4.93it/s]

Processing tickers:  10%|▉         | 675/6774 [02:17<20:38,  4.93it/s]

Processing tickers:  10%|▉         | 676/6774 [02:17<20:44,  4.90it/s]

Processing tickers:  10%|▉         | 677/6774 [02:17<20:54,  4.86it/s]

Processing tickers:  10%|█         | 678/6774 [02:18<20:38,  4.92it/s]

Processing tickers:  10%|█         | 679/6774 [02:18<20:31,  4.95it/s]

Processing tickers:  10%|█         | 680/6774 [02:18<20:48,  4.88it/s]

Processing tickers:  10%|█         | 681/6774 [02:18<20:38,  4.92it/s]

Processing tickers:  10%|█         | 682/6774 [02:18<21:21,  4.75it/s]

Processing tickers:  10%|█         | 683/6774 [02:19<21:02,  4.82it/s]

Processing tickers:  10%|█         | 684/6774 [02:19<21:34,  4.71it/s]

Processing tickers:  10%|█         | 685/6774 [02:19<21:31,  4.71it/s]

Processing tickers:  10%|█         | 686/6774 [02:19<21:28,  4.73it/s]

Processing tickers:  10%|█         | 687/6774 [02:19<21:09,  4.79it/s]

Processing tickers:  10%|█         | 688/6774 [02:20<20:49,  4.87it/s]

Processing tickers:  10%|█         | 689/6774 [02:20<21:04,  4.81it/s]

Processing tickers:  10%|█         | 690/6774 [02:20<21:15,  4.77it/s]

Processing tickers:  10%|█         | 691/6774 [02:20<20:53,  4.85it/s]

Processing tickers:  10%|█         | 692/6774 [02:21<20:44,  4.89it/s]

Processing tickers:  10%|█         | 693/6774 [02:21<20:40,  4.90it/s]

Processing tickers:  10%|█         | 694/6774 [02:21<20:33,  4.93it/s]

Processing tickers:  10%|█         | 695/6774 [02:21<20:30,  4.94it/s]

Processing tickers:  10%|█         | 696/6774 [02:21<20:26,  4.96it/s]

Processing tickers:  10%|█         | 697/6774 [02:22<20:18,  4.99it/s]

Processing tickers:  10%|█         | 698/6774 [02:22<20:17,  4.99it/s]

Processing tickers:  10%|█         | 699/6774 [02:22<20:20,  4.98it/s]

Processing tickers:  10%|█         | 700/6774 [02:22<20:13,  5.00it/s]

Processing tickers:  10%|█         | 701/6774 [02:22<20:10,  5.02it/s]

Processing tickers:  10%|█         | 702/6774 [02:23<20:09,  5.02it/s]

Processing tickers:  10%|█         | 703/6774 [02:23<20:13,  5.00it/s]

Processing tickers:  10%|█         | 704/6774 [02:23<20:22,  4.96it/s]

Processing tickers:  10%|█         | 705/6774 [02:23<20:16,  4.99it/s]

Processing tickers:  10%|█         | 706/6774 [02:23<20:19,  4.98it/s]

Processing tickers:  10%|█         | 707/6774 [02:24<20:18,  4.98it/s]

Processing tickers:  10%|█         | 708/6774 [02:24<20:41,  4.89it/s]

Processing tickers:  10%|█         | 709/6774 [02:24<20:32,  4.92it/s]

Processing tickers:  10%|█         | 710/6774 [02:24<20:25,  4.95it/s]

Processing tickers:  10%|█         | 711/6774 [02:24<20:44,  4.87it/s]

Processing tickers:  11%|█         | 712/6774 [02:25<20:31,  4.92it/s]

Processing tickers:  11%|█         | 713/6774 [02:25<20:22,  4.96it/s]

Processing tickers:  11%|█         | 714/6774 [02:25<20:54,  4.83it/s]

Processing tickers:  11%|█         | 715/6774 [02:25<20:47,  4.86it/s]

Processing tickers:  11%|█         | 716/6774 [02:25<20:53,  4.83it/s]

Processing tickers:  11%|█         | 717/6774 [02:26<20:40,  4.88it/s]

Processing tickers:  11%|█         | 718/6774 [02:26<21:15,  4.75it/s]

Processing tickers:  11%|█         | 719/6774 [02:26<21:16,  4.74it/s]

Processing tickers:  11%|█         | 720/6774 [02:26<21:17,  4.74it/s]

Processing tickers:  11%|█         | 721/6774 [02:26<21:05,  4.78it/s]

Processing tickers:  11%|█         | 722/6774 [02:27<20:56,  4.82it/s]

Processing tickers:  11%|█         | 723/6774 [02:27<20:45,  4.86it/s]

Processing tickers:  11%|█         | 724/6774 [02:27<20:26,  4.93it/s]

Processing tickers:  11%|█         | 725/6774 [02:27<20:20,  4.95it/s]

Processing tickers:  11%|█         | 726/6774 [02:27<20:11,  4.99it/s]

Processing tickers:  11%|█         | 727/6774 [02:28<20:20,  4.95it/s]

Processing tickers:  11%|█         | 728/6774 [02:28<20:19,  4.96it/s]

Processing tickers:  11%|█         | 729/6774 [02:28<20:19,  4.96it/s]

Processing tickers:  11%|█         | 730/6774 [02:28<20:18,  4.96it/s]

Processing tickers:  11%|█         | 731/6774 [02:28<20:17,  4.96it/s]

Processing tickers:  11%|█         | 732/6774 [02:29<20:33,  4.90it/s]

Processing tickers:  11%|█         | 733/6774 [02:29<20:21,  4.94it/s]

Processing tickers:  11%|█         | 734/6774 [02:29<20:42,  4.86it/s]

Processing tickers:  11%|█         | 735/6774 [02:29<21:06,  4.77it/s]

Processing tickers:  11%|█         | 736/6774 [02:29<21:27,  4.69it/s]

Processing tickers:  11%|█         | 737/6774 [02:30<20:55,  4.81it/s]

Processing tickers:  11%|█         | 738/6774 [02:30<20:41,  4.86it/s]

Processing tickers:  11%|█         | 739/6774 [02:30<20:27,  4.91it/s]

Processing tickers:  11%|█         | 740/6774 [02:30<20:18,  4.95it/s]

Processing tickers:  11%|█         | 741/6774 [02:30<20:13,  4.97it/s]

Processing tickers:  11%|█         | 742/6774 [02:31<20:16,  4.96it/s]

Processing tickers:  11%|█         | 743/6774 [02:31<20:18,  4.95it/s]

Processing tickers:  11%|█         | 744/6774 [02:31<20:19,  4.95it/s]

Processing tickers:  11%|█         | 745/6774 [02:31<22:47,  4.41it/s]

Processing tickers:  11%|█         | 746/6774 [02:32<22:04,  4.55it/s]

Processing tickers:  11%|█         | 747/6774 [02:32<21:31,  4.67it/s]

Processing tickers:  11%|█         | 748/6774 [02:32<21:24,  4.69it/s]

Processing tickers:  11%|█         | 749/6774 [02:32<21:46,  4.61it/s]

Processing tickers:  11%|█         | 750/6774 [02:32<21:55,  4.58it/s]

Processing tickers:  11%|█         | 751/6774 [02:33<21:23,  4.69it/s]

Processing tickers:  11%|█         | 752/6774 [02:33<20:56,  4.79it/s]

Processing tickers:  11%|█         | 753/6774 [02:33<20:37,  4.87it/s]

Processing tickers:  11%|█         | 754/6774 [02:33<20:29,  4.89it/s]

Processing tickers:  11%|█         | 755/6774 [02:33<20:34,  4.88it/s]

Processing tickers:  11%|█         | 756/6774 [02:34<20:24,  4.91it/s]

Processing tickers:  11%|█         | 757/6774 [02:34<20:29,  4.89it/s]

Processing tickers:  11%|█         | 758/6774 [02:34<20:14,  4.95it/s]

Processing tickers:  11%|█         | 759/6774 [02:34<21:16,  4.71it/s]

Processing tickers:  11%|█         | 760/6774 [02:34<20:58,  4.78it/s]

Processing tickers:  11%|█         | 761/6774 [02:35<20:41,  4.84it/s]

Processing tickers:  11%|█         | 762/6774 [02:35<20:25,  4.90it/s]

Processing tickers:  11%|█▏        | 763/6774 [02:35<20:35,  4.87it/s]

Processing tickers:  11%|█▏        | 764/6774 [02:35<20:20,  4.92it/s]

Processing tickers:  11%|█▏        | 765/6774 [02:35<20:12,  4.96it/s]

Processing tickers:  11%|█▏        | 766/6774 [02:36<20:48,  4.81it/s]

Processing tickers:  11%|█▏        | 767/6774 [02:36<20:33,  4.87it/s]

Processing tickers:  11%|█▏        | 768/6774 [02:36<20:20,  4.92it/s]

Processing tickers:  11%|█▏        | 769/6774 [02:36<20:13,  4.95it/s]

Processing tickers:  11%|█▏        | 770/6774 [02:37<20:08,  4.97it/s]

Processing tickers:  11%|█▏        | 771/6774 [02:37<20:10,  4.96it/s]

Processing tickers:  11%|█▏        | 772/6774 [02:37<20:04,  4.98it/s]

Processing tickers:  11%|█▏        | 773/6774 [02:37<20:04,  4.98it/s]

Processing tickers:  11%|█▏        | 774/6774 [02:37<20:05,  4.98it/s]

Processing tickers:  11%|█▏        | 775/6774 [02:38<19:58,  5.01it/s]

Processing tickers:  11%|█▏        | 776/6774 [02:38<19:56,  5.01it/s]

Processing tickers:  11%|█▏        | 777/6774 [02:38<19:51,  5.03it/s]

Processing tickers:  11%|█▏        | 778/6774 [02:38<19:59,  5.00it/s]

Processing tickers:  11%|█▏        | 779/6774 [02:38<19:58,  5.00it/s]

Processing tickers:  12%|█▏        | 780/6774 [02:39<20:33,  4.86it/s]

Processing tickers:  12%|█▏        | 781/6774 [02:39<20:25,  4.89it/s]

Processing tickers:  12%|█▏        | 782/6774 [02:39<20:19,  4.91it/s]

Processing tickers:  12%|█▏        | 783/6774 [02:39<20:11,  4.95it/s]

Processing tickers:  12%|█▏        | 784/6774 [02:39<20:56,  4.77it/s]

Processing tickers:  12%|█▏        | 785/6774 [02:40<20:38,  4.83it/s]

Processing tickers:  12%|█▏        | 786/6774 [02:40<20:36,  4.84it/s]

Processing tickers:  12%|█▏        | 787/6774 [02:40<21:15,  4.69it/s]

Processing tickers:  12%|█▏        | 788/6774 [02:40<20:50,  4.79it/s]

Processing tickers:  12%|█▏        | 789/6774 [02:40<21:09,  4.71it/s]

Processing tickers:  12%|█▏        | 790/6774 [02:41<21:04,  4.73it/s]

Processing tickers:  12%|█▏        | 791/6774 [02:41<20:59,  4.75it/s]

Processing tickers:  12%|█▏        | 792/6774 [02:41<20:50,  4.79it/s]

Processing tickers:  12%|█▏        | 793/6774 [02:41<20:39,  4.82it/s]

Processing tickers:  12%|█▏        | 794/6774 [02:41<20:31,  4.86it/s]

Processing tickers:  12%|█▏        | 795/6774 [02:42<20:35,  4.84it/s]

Processing tickers:  12%|█▏        | 796/6774 [02:42<20:24,  4.88it/s]

Processing tickers:  12%|█▏        | 797/6774 [02:42<21:24,  4.65it/s]

Processing tickers:  12%|█▏        | 798/6774 [02:42<20:59,  4.75it/s]

Processing tickers:  12%|█▏        | 799/6774 [02:42<20:41,  4.81it/s]

Processing tickers:  12%|█▏        | 800/6774 [02:43<20:32,  4.85it/s]

Processing tickers:  12%|█▏        | 801/6774 [02:43<20:16,  4.91it/s]

Processing tickers:  12%|█▏        | 802/6774 [02:43<20:29,  4.86it/s]

Processing tickers:  12%|█▏        | 803/6774 [02:43<20:18,  4.90it/s]

Processing tickers:  12%|█▏        | 804/6774 [02:43<20:16,  4.91it/s]

Processing tickers:  12%|█▏        | 805/6774 [02:44<20:12,  4.92it/s]

Processing tickers:  12%|█▏        | 806/6774 [02:44<20:12,  4.92it/s]

Processing tickers:  12%|█▏        | 807/6774 [02:44<20:11,  4.93it/s]

Processing tickers:  12%|█▏        | 808/6774 [02:44<20:38,  4.82it/s]

Processing tickers:  12%|█▏        | 809/6774 [02:45<20:57,  4.74it/s]

Processing tickers:  12%|█▏        | 810/6774 [02:45<20:39,  4.81it/s]

Processing tickers:  12%|█▏        | 811/6774 [02:45<20:17,  4.90it/s]

Processing tickers:  12%|█▏        | 812/6774 [02:45<20:06,  4.94it/s]

Processing tickers:  12%|█▏        | 813/6774 [02:45<20:25,  4.86it/s]

Processing tickers:  12%|█▏        | 814/6774 [02:46<20:20,  4.88it/s]

Processing tickers:  12%|█▏        | 815/6774 [02:46<20:09,  4.93it/s]

Processing tickers:  12%|█▏        | 816/6774 [02:46<20:54,  4.75it/s]

Processing tickers:  12%|█▏        | 817/6774 [02:46<21:14,  4.67it/s]

Processing tickers:  12%|█▏        | 818/6774 [02:46<21:05,  4.71it/s]

Processing tickers:  12%|█▏        | 819/6774 [02:47<20:43,  4.79it/s]

Processing tickers:  12%|█▏        | 820/6774 [02:47<20:27,  4.85it/s]

Processing tickers:  12%|█▏        | 821/6774 [02:47<20:25,  4.86it/s]

Processing tickers:  12%|█▏        | 822/6774 [02:47<20:11,  4.91it/s]

Processing tickers:  12%|█▏        | 823/6774 [02:47<20:00,  4.96it/s]

Processing tickers:  12%|█▏        | 824/6774 [02:48<20:11,  4.91it/s]

Processing tickers:  12%|█▏        | 825/6774 [02:48<20:03,  4.94it/s]

Processing tickers:  12%|█▏        | 826/6774 [02:48<20:35,  4.82it/s]

Processing tickers:  12%|█▏        | 827/6774 [02:48<20:25,  4.85it/s]

Processing tickers:  12%|█▏        | 828/6774 [02:48<20:08,  4.92it/s]

Processing tickers:  12%|█▏        | 829/6774 [02:49<19:57,  4.96it/s]

Processing tickers:  12%|█▏        | 830/6774 [02:49<19:59,  4.96it/s]

Processing tickers:  12%|█▏        | 831/6774 [02:49<20:09,  4.91it/s]

Processing tickers:  12%|█▏        | 832/6774 [02:49<20:04,  4.93it/s]

Processing tickers:  12%|█▏        | 833/6774 [02:49<19:52,  4.98it/s]

Processing tickers:  12%|█▏        | 834/6774 [02:50<19:58,  4.96it/s]

Processing tickers:  12%|█▏        | 835/6774 [02:50<20:22,  4.86it/s]

Processing tickers:  12%|█▏        | 836/6774 [02:50<20:19,  4.87it/s]

Processing tickers:  12%|█▏        | 837/6774 [02:50<20:13,  4.89it/s]

Processing tickers:  12%|█▏        | 838/6774 [02:50<19:58,  4.95it/s]

Processing tickers:  12%|█▏        | 839/6774 [02:51<19:49,  4.99it/s]

Processing tickers:  12%|█▏        | 840/6774 [02:51<19:44,  5.01it/s]

Processing tickers:  12%|█▏        | 841/6774 [02:51<19:47,  5.00it/s]

Processing tickers:  12%|█▏        | 842/6774 [02:51<19:49,  4.99it/s]

Processing tickers:  12%|█▏        | 843/6774 [02:51<19:48,  4.99it/s]

Processing tickers:  12%|█▏        | 844/6774 [02:52<20:16,  4.88it/s]

Processing tickers:  12%|█▏        | 845/6774 [02:52<20:06,  4.91it/s]

Processing tickers:  12%|█▏        | 846/6774 [02:52<20:02,  4.93it/s]

Processing tickers:  13%|█▎        | 847/6774 [02:52<19:58,  4.94it/s]

Processing tickers:  13%|█▎        | 848/6774 [02:52<19:51,  4.98it/s]

Processing tickers:  13%|█▎        | 849/6774 [02:53<19:47,  4.99it/s]

Processing tickers:  13%|█▎        | 850/6774 [02:53<19:54,  4.96it/s]

Processing tickers:  13%|█▎        | 851/6774 [02:53<19:45,  5.00it/s]

Processing tickers:  13%|█▎        | 852/6774 [02:53<19:50,  4.97it/s]

Processing tickers:  13%|█▎        | 853/6774 [02:53<19:49,  4.98it/s]

Processing tickers:  13%|█▎        | 854/6774 [02:54<19:44,  5.00it/s]

Processing tickers:  13%|█▎        | 855/6774 [02:54<19:44,  5.00it/s]

Processing tickers:  13%|█▎        | 856/6774 [02:54<20:09,  4.89it/s]

Processing tickers:  13%|█▎        | 857/6774 [02:54<20:54,  4.72it/s]

Processing tickers:  13%|█▎        | 858/6774 [02:55<21:09,  4.66it/s]

Processing tickers:  13%|█▎        | 859/6774 [02:55<20:46,  4.74it/s]

Processing tickers:  13%|█▎        | 860/6774 [02:55<20:28,  4.81it/s]

Processing tickers:  13%|█▎        | 861/6774 [02:55<20:15,  4.86it/s]

Processing tickers:  13%|█▎        | 862/6774 [02:55<20:18,  4.85it/s]

Processing tickers:  13%|█▎        | 863/6774 [02:56<20:10,  4.88it/s]

Processing tickers:  13%|█▎        | 864/6774 [02:56<20:14,  4.86it/s]

Processing tickers:  13%|█▎        | 865/6774 [02:56<20:41,  4.76it/s]

Processing tickers:  13%|█▎        | 866/6774 [02:56<20:32,  4.80it/s]

Processing tickers:  13%|█▎        | 867/6774 [02:56<20:44,  4.75it/s]

Processing tickers:  13%|█▎        | 868/6774 [02:57<20:33,  4.79it/s]

Processing tickers:  13%|█▎        | 869/6774 [02:57<20:36,  4.77it/s]

Processing tickers:  13%|█▎        | 870/6774 [02:57<20:18,  4.84it/s]

Processing tickers:  13%|█▎        | 871/6774 [02:57<20:12,  4.87it/s]

Processing tickers:  13%|█▎        | 872/6774 [02:57<20:04,  4.90it/s]

Processing tickers:  13%|█▎        | 873/6774 [02:58<19:57,  4.93it/s]

Processing tickers:  13%|█▎        | 874/6774 [02:58<19:52,  4.95it/s]

Processing tickers:  13%|█▎        | 875/6774 [02:58<19:55,  4.94it/s]

Processing tickers:  13%|█▎        | 876/6774 [02:58<19:47,  4.97it/s]

Processing tickers:  13%|█▎        | 877/6774 [02:58<19:46,  4.97it/s]

Processing tickers:  13%|█▎        | 878/6774 [02:59<19:50,  4.95it/s]

Processing tickers:  13%|█▎        | 879/6774 [02:59<19:43,  4.98it/s]

Processing tickers:  13%|█▎        | 880/6774 [02:59<19:39,  5.00it/s]

Processing tickers:  13%|█▎        | 881/6774 [02:59<19:56,  4.92it/s]

Processing tickers:  13%|█▎        | 882/6774 [02:59<19:43,  4.98it/s]

Processing tickers:  13%|█▎        | 883/6774 [03:00<19:42,  4.98it/s]

Processing tickers:  13%|█▎        | 884/6774 [03:00<20:23,  4.81it/s]

Processing tickers:  13%|█▎        | 885/6774 [03:00<20:11,  4.86it/s]

Processing tickers:  13%|█▎        | 886/6774 [03:00<20:00,  4.90it/s]

Processing tickers:  13%|█▎        | 887/6774 [03:00<19:56,  4.92it/s]

Processing tickers:  13%|█▎        | 888/6774 [03:01<19:57,  4.91it/s]

Processing tickers:  13%|█▎        | 889/6774 [03:01<19:46,  4.96it/s]

Processing tickers:  13%|█▎        | 890/6774 [03:01<19:59,  4.91it/s]

Processing tickers:  13%|█▎        | 891/6774 [03:01<20:03,  4.89it/s]

Processing tickers:  13%|█▎        | 892/6774 [03:01<20:31,  4.78it/s]

Processing tickers:  13%|█▎        | 893/6774 [03:02<20:25,  4.80it/s]

Processing tickers:  13%|█▎        | 894/6774 [03:02<20:39,  4.74it/s]

Processing tickers:  13%|█▎        | 895/6774 [03:02<20:56,  4.68it/s]

Processing tickers:  13%|█▎        | 896/6774 [03:02<20:31,  4.77it/s]

Processing tickers:  13%|█▎        | 897/6774 [03:03<20:11,  4.85it/s]

Processing tickers:  13%|█▎        | 898/6774 [03:03<19:57,  4.91it/s]

Processing tickers:  13%|█▎        | 899/6774 [03:03<20:20,  4.81it/s]

Processing tickers:  13%|█▎        | 900/6774 [03:03<20:04,  4.88it/s]

Processing tickers:  13%|█▎        | 901/6774 [03:03<19:49,  4.94it/s]

Processing tickers:  13%|█▎        | 902/6774 [03:04<20:04,  4.87it/s]

Processing tickers:  13%|█▎        | 903/6774 [03:04<20:05,  4.87it/s]

Processing tickers:  13%|█▎        | 904/6774 [03:04<20:22,  4.80it/s]

Processing tickers:  13%|█▎        | 905/6774 [03:04<20:48,  4.70it/s]

Processing tickers:  13%|█▎        | 906/6774 [03:04<20:58,  4.66it/s]

Processing tickers:  13%|█▎        | 907/6774 [03:05<20:57,  4.66it/s]

Processing tickers:  13%|█▎        | 908/6774 [03:05<20:39,  4.73it/s]

Processing tickers:  13%|█▎        | 909/6774 [03:05<21:06,  4.63it/s]

Processing tickers:  13%|█▎        | 910/6774 [03:05<22:47,  4.29it/s]

Processing tickers:  13%|█▎        | 911/6774 [03:06<21:50,  4.47it/s]

Processing tickers:  13%|█▎        | 912/6774 [03:06<21:51,  4.47it/s]

Processing tickers:  13%|█▎        | 913/6774 [03:06<21:29,  4.54it/s]

Processing tickers:  13%|█▎        | 914/6774 [03:06<21:00,  4.65it/s]

Processing tickers:  14%|█▎        | 915/6774 [03:06<20:40,  4.72it/s]

Processing tickers:  14%|█▎        | 916/6774 [03:07<20:27,  4.77it/s]

Processing tickers:  14%|█▎        | 917/6774 [03:07<20:06,  4.85it/s]

Processing tickers:  14%|█▎        | 918/6774 [03:07<20:24,  4.78it/s]

Processing tickers:  14%|█▎        | 919/6774 [03:07<20:04,  4.86it/s]

Processing tickers:  14%|█▎        | 920/6774 [03:07<20:13,  4.83it/s]

Processing tickers:  14%|█▎        | 921/6774 [03:08<20:01,  4.87it/s]

Processing tickers:  14%|█▎        | 922/6774 [03:08<19:58,  4.88it/s]

Processing tickers:  14%|█▎        | 923/6774 [03:08<20:14,  4.82it/s]

Processing tickers:  14%|█▎        | 924/6774 [03:08<20:01,  4.87it/s]

Processing tickers:  14%|█▎        | 925/6774 [03:08<20:00,  4.87it/s]

Processing tickers:  14%|█▎        | 926/6774 [03:09<19:52,  4.90it/s]

Processing tickers:  14%|█▎        | 927/6774 [03:09<19:56,  4.89it/s]

Processing tickers:  14%|█▎        | 928/6774 [03:09<19:46,  4.93it/s]

Processing tickers:  14%|█▎        | 929/6774 [03:09<19:37,  4.96it/s]

Processing tickers:  14%|█▎        | 930/6774 [03:09<19:31,  4.99it/s]

Processing tickers:  14%|█▎        | 931/6774 [03:10<19:21,  5.03it/s]

Processing tickers:  14%|█▍        | 932/6774 [03:10<19:17,  5.05it/s]

Processing tickers:  14%|█▍        | 933/6774 [03:10<19:57,  4.88it/s]

Processing tickers:  14%|█▍        | 934/6774 [03:10<19:41,  4.94it/s]

Processing tickers:  14%|█▍        | 935/6774 [03:10<19:43,  4.93it/s]

Processing tickers:  14%|█▍        | 936/6774 [03:11<19:37,  4.96it/s]

Processing tickers:  14%|█▍        | 937/6774 [03:11<19:43,  4.93it/s]

Processing tickers:  14%|█▍        | 938/6774 [03:11<19:43,  4.93it/s]

Processing tickers:  14%|█▍        | 939/6774 [03:11<19:39,  4.95it/s]

Processing tickers:  14%|█▍        | 940/6774 [03:11<19:35,  4.96it/s]

Processing tickers:  14%|█▍        | 941/6774 [03:12<19:31,  4.98it/s]

Processing tickers:  14%|█▍        | 942/6774 [03:12<19:20,  5.02it/s]

Processing tickers:  14%|█▍        | 943/6774 [03:12<19:34,  4.97it/s]

Processing tickers:  14%|█▍        | 944/6774 [03:12<19:25,  5.00it/s]

Processing tickers:  14%|█▍        | 945/6774 [03:12<19:48,  4.90it/s]

Processing tickers:  14%|█▍        | 946/6774 [03:13<20:02,  4.85it/s]

Processing tickers:  14%|█▍        | 947/6774 [03:13<19:51,  4.89it/s]

Processing tickers:  14%|█▍        | 948/6774 [03:13<19:44,  4.92it/s]

Processing tickers:  14%|█▍        | 949/6774 [03:13<19:38,  4.94it/s]

Processing tickers:  14%|█▍        | 950/6774 [03:13<19:48,  4.90it/s]

Processing tickers:  14%|█▍        | 951/6774 [03:14<20:08,  4.82it/s]

Processing tickers:  14%|█▍        | 952/6774 [03:14<19:55,  4.87it/s]

Processing tickers:  14%|█▍        | 953/6774 [03:14<19:47,  4.90it/s]

Processing tickers:  14%|█▍        | 954/6774 [03:14<19:40,  4.93it/s]

Processing tickers:  14%|█▍        | 955/6774 [03:15<19:35,  4.95it/s]

Processing tickers:  14%|█▍        | 956/6774 [03:15<19:59,  4.85it/s]

Processing tickers:  14%|█▍        | 957/6774 [03:15<19:44,  4.91it/s]

Processing tickers:  14%|█▍        | 958/6774 [03:15<19:34,  4.95it/s]

Processing tickers:  14%|█▍        | 959/6774 [03:15<19:37,  4.94it/s]

Processing tickers:  14%|█▍        | 960/6774 [03:16<19:38,  4.94it/s]

Processing tickers:  14%|█▍        | 961/6774 [03:16<20:11,  4.80it/s]

Processing tickers:  14%|█▍        | 962/6774 [03:16<20:00,  4.84it/s]

Processing tickers:  14%|█▍        | 963/6774 [03:16<19:46,  4.90it/s]

Processing tickers:  14%|█▍        | 964/6774 [03:16<19:45,  4.90it/s]

Processing tickers:  14%|█▍        | 965/6774 [03:17<19:39,  4.92it/s]

Processing tickers:  14%|█▍        | 966/6774 [03:17<19:39,  4.92it/s]

Processing tickers:  14%|█▍        | 967/6774 [03:17<19:34,  4.94it/s]

Processing tickers:  14%|█▍        | 968/6774 [03:17<19:31,  4.95it/s]

Processing tickers:  14%|█▍        | 969/6774 [03:17<19:33,  4.95it/s]

Processing tickers:  14%|█▍        | 970/6774 [03:18<19:21,  5.00it/s]

Processing tickers:  14%|█▍        | 971/6774 [03:18<19:28,  4.97it/s]

Processing tickers:  14%|█▍        | 972/6774 [03:18<19:26,  4.97it/s]

Processing tickers:  14%|█▍        | 973/6774 [03:18<19:41,  4.91it/s]

Processing tickers:  14%|█▍        | 974/6774 [03:18<19:33,  4.94it/s]

Processing tickers:  14%|█▍        | 975/6774 [03:19<19:30,  4.95it/s]

Processing tickers:  14%|█▍        | 976/6774 [03:19<19:40,  4.91it/s]

Processing tickers:  14%|█▍        | 977/6774 [03:19<19:55,  4.85it/s]

Processing tickers:  14%|█▍        | 978/6774 [03:19<19:49,  4.87it/s]

Processing tickers:  14%|█▍        | 979/6774 [03:19<20:27,  4.72it/s]

Processing tickers:  14%|█▍        | 980/6774 [03:20<21:06,  4.57it/s]

Processing tickers:  14%|█▍        | 981/6774 [03:20<20:32,  4.70it/s]

Processing tickers:  14%|█▍        | 982/6774 [03:20<20:56,  4.61it/s]

Processing tickers:  15%|█▍        | 983/6774 [03:20<20:27,  4.72it/s]

Processing tickers:  15%|█▍        | 984/6774 [03:20<20:05,  4.80it/s]

Processing tickers:  15%|█▍        | 985/6774 [03:21<19:46,  4.88it/s]

Processing tickers:  15%|█▍        | 986/6774 [03:21<19:36,  4.92it/s]

Processing tickers:  15%|█▍        | 987/6774 [03:21<19:34,  4.93it/s]

Processing tickers:  15%|█▍        | 988/6774 [03:21<19:23,  4.97it/s]

Processing tickers:  15%|█▍        | 989/6774 [03:21<19:24,  4.97it/s]

Processing tickers:  15%|█▍        | 990/6774 [03:22<19:20,  4.98it/s]

Processing tickers:  15%|█▍        | 991/6774 [03:22<19:40,  4.90it/s]

Processing tickers:  15%|█▍        | 992/6774 [03:22<19:32,  4.93it/s]

Processing tickers:  15%|█▍        | 993/6774 [03:22<19:20,  4.98it/s]

Processing tickers:  15%|█▍        | 994/6774 [03:22<19:43,  4.89it/s]

Processing tickers:  15%|█▍        | 995/6774 [03:23<19:32,  4.93it/s]

Processing tickers:  15%|█▍        | 996/6774 [03:23<19:39,  4.90it/s]

Processing tickers:  15%|█▍        | 997/6774 [03:23<19:42,  4.89it/s]

Processing tickers:  15%|█▍        | 998/6774 [03:23<20:18,  4.74it/s]

Processing tickers:  15%|█▍        | 999/6774 [03:24<19:58,  4.82it/s]

Processing tickers:  15%|█▍        | 1000/6774 [03:24<19:50,  4.85it/s]

Processing tickers:  15%|█▍        | 1001/6774 [03:24<19:39,  4.90it/s]

Processing tickers:  15%|█▍        | 1002/6774 [03:24<19:54,  4.83it/s]

Processing tickers:  15%|█▍        | 1003/6774 [03:24<19:43,  4.88it/s]

Processing tickers:  15%|█▍        | 1004/6774 [03:25<19:30,  4.93it/s]

Processing tickers:  15%|█▍        | 1005/6774 [03:25<19:31,  4.92it/s]

Processing tickers:  15%|█▍        | 1006/6774 [03:25<19:16,  4.99it/s]

Processing tickers:  15%|█▍        | 1007/6774 [03:25<19:22,  4.96it/s]

Processing tickers:  15%|█▍        | 1008/6774 [03:25<19:30,  4.92it/s]

Processing tickers:  15%|█▍        | 1009/6774 [03:26<19:33,  4.91it/s]

Processing tickers:  15%|█▍        | 1010/6774 [03:26<19:25,  4.95it/s]

Processing tickers:  15%|█▍        | 1011/6774 [03:26<19:24,  4.95it/s]

Processing tickers:  15%|█▍        | 1012/6774 [03:26<19:17,  4.98it/s]

Processing tickers:  15%|█▍        | 1013/6774 [03:26<19:12,  5.00it/s]

Processing tickers:  15%|█▍        | 1014/6774 [03:27<19:34,  4.90it/s]

Processing tickers:  15%|█▍        | 1015/6774 [03:27<19:41,  4.87it/s]

Processing tickers:  15%|█▍        | 1016/6774 [03:27<20:04,  4.78it/s]

Processing tickers:  15%|█▌        | 1017/6774 [03:27<19:49,  4.84it/s]

Processing tickers:  15%|█▌        | 1018/6774 [03:27<19:48,  4.84it/s]

Processing tickers:  15%|█▌        | 1019/6774 [03:28<19:27,  4.93it/s]

Processing tickers:  15%|█▌        | 1020/6774 [03:28<19:38,  4.88it/s]

Processing tickers:  15%|█▌        | 1021/6774 [03:28<19:50,  4.83it/s]

Processing tickers:  15%|█▌        | 1022/6774 [03:28<20:04,  4.78it/s]

Processing tickers:  15%|█▌        | 1023/6774 [03:28<19:45,  4.85it/s]

Processing tickers:  15%|█▌        | 1024/6774 [03:29<19:38,  4.88it/s]

Processing tickers:  15%|█▌        | 1025/6774 [03:29<19:32,  4.90it/s]

Processing tickers:  15%|█▌        | 1026/6774 [03:29<19:29,  4.92it/s]

Processing tickers:  15%|█▌        | 1027/6774 [03:29<19:23,  4.94it/s]

Processing tickers:  15%|█▌        | 1028/6774 [03:29<19:23,  4.94it/s]

Processing tickers:  15%|█▌        | 1029/6774 [03:30<19:19,  4.96it/s]

Processing tickers:  15%|█▌        | 1030/6774 [03:30<19:36,  4.88it/s]

Processing tickers:  15%|█▌        | 1031/6774 [03:30<19:29,  4.91it/s]

Processing tickers:  15%|█▌        | 1032/6774 [03:30<19:34,  4.89it/s]

Processing tickers:  15%|█▌        | 1033/6774 [03:30<19:22,  4.94it/s]

Processing tickers:  15%|█▌        | 1034/6774 [03:31<19:13,  4.98it/s]

Processing tickers:  15%|█▌        | 1035/6774 [03:31<19:14,  4.97it/s]

Processing tickers:  15%|█▌        | 1036/6774 [03:31<19:16,  4.96it/s]

Processing tickers:  15%|█▌        | 1037/6774 [03:31<19:50,  4.82it/s]

Processing tickers:  15%|█▌        | 1038/6774 [03:31<19:31,  4.90it/s]

Processing tickers:  15%|█▌        | 1039/6774 [03:32<19:30,  4.90it/s]

Processing tickers:  15%|█▌        | 1040/6774 [03:32<19:21,  4.94it/s]

Processing tickers:  15%|█▌        | 1041/6774 [03:32<19:26,  4.92it/s]

Processing tickers:  15%|█▌        | 1042/6774 [03:32<19:21,  4.93it/s]

Processing tickers:  15%|█▌        | 1043/6774 [03:32<19:14,  4.96it/s]

Processing tickers:  15%|█▌        | 1044/6774 [03:33<19:09,  4.98it/s]

Processing tickers:  15%|█▌        | 1045/6774 [03:33<19:07,  4.99it/s]

Processing tickers:  15%|█▌        | 1046/6774 [03:33<19:08,  4.99it/s]

Processing tickers:  15%|█▌        | 1047/6774 [03:33<19:06,  4.99it/s]

Processing tickers:  15%|█▌        | 1048/6774 [03:33<19:01,  5.02it/s]

Processing tickers:  15%|█▌        | 1049/6774 [03:34<18:54,  5.05it/s]

Processing tickers:  16%|█▌        | 1050/6774 [03:34<18:57,  5.03it/s]

Processing tickers:  16%|█▌        | 1051/6774 [03:34<19:01,  5.01it/s]

Processing tickers:  16%|█▌        | 1052/6774 [03:34<19:00,  5.02it/s]

Processing tickers:  16%|█▌        | 1053/6774 [03:34<19:02,  5.01it/s]

Processing tickers:  16%|█▌        | 1054/6774 [03:35<18:57,  5.03it/s]

Processing tickers:  16%|█▌        | 1055/6774 [03:35<18:56,  5.03it/s]

Processing tickers:  16%|█▌        | 1056/6774 [03:35<19:00,  5.01it/s]

Processing tickers:  16%|█▌        | 1057/6774 [03:35<18:58,  5.02it/s]

Processing tickers:  16%|█▌        | 1058/6774 [03:35<18:57,  5.02it/s]

Processing tickers:  16%|█▌        | 1059/6774 [03:36<18:56,  5.03it/s]

Processing tickers:  16%|█▌        | 1060/6774 [03:36<18:55,  5.03it/s]

Processing tickers:  16%|█▌        | 1061/6774 [03:36<18:54,  5.04it/s]

Processing tickers:  16%|█▌        | 1062/6774 [03:36<18:55,  5.03it/s]

Processing tickers:  16%|█▌        | 1063/6774 [03:36<18:52,  5.04it/s]

Processing tickers:  16%|█▌        | 1064/6774 [03:37<19:17,  4.93it/s]

Processing tickers:  16%|█▌        | 1065/6774 [03:37<19:26,  4.89it/s]

Processing tickers:  16%|█▌        | 1066/6774 [03:37<19:15,  4.94it/s]

Processing tickers:  16%|█▌        | 1067/6774 [03:37<19:27,  4.89it/s]

Processing tickers:  16%|█▌        | 1068/6774 [03:38<19:35,  4.86it/s]

Processing tickers:  16%|█▌        | 1069/6774 [03:38<19:16,  4.93it/s]

Processing tickers:  16%|█▌        | 1070/6774 [03:38<19:20,  4.92it/s]

Processing tickers:  16%|█▌        | 1071/6774 [03:38<19:12,  4.95it/s]

Processing tickers:  16%|█▌        | 1072/6774 [03:38<19:12,  4.95it/s]

Processing tickers:  16%|█▌        | 1073/6774 [03:39<19:10,  4.95it/s]

Processing tickers:  16%|█▌        | 1074/6774 [03:39<19:05,  4.98it/s]

Processing tickers:  16%|█▌        | 1075/6774 [03:39<19:00,  5.00it/s]

Processing tickers:  16%|█▌        | 1076/6774 [03:39<19:39,  4.83it/s]

Processing tickers:  16%|█▌        | 1077/6774 [03:39<19:29,  4.87it/s]

Processing tickers:  16%|█▌        | 1078/6774 [03:40<19:30,  4.87it/s]

Processing tickers:  16%|█▌        | 1079/6774 [03:40<19:29,  4.87it/s]

Processing tickers:  16%|█▌        | 1080/6774 [03:40<19:23,  4.90it/s]

Processing tickers:  16%|█▌        | 1081/6774 [03:40<19:13,  4.94it/s]

Processing tickers:  16%|█▌        | 1082/6774 [03:40<19:04,  4.97it/s]

Processing tickers:  16%|█▌        | 1083/6774 [03:41<19:05,  4.97it/s]

Processing tickers:  16%|█▌        | 1084/6774 [03:41<19:02,  4.98it/s]

Processing tickers:  16%|█▌        | 1085/6774 [03:41<18:57,  5.00it/s]

Processing tickers:  16%|█▌        | 1086/6774 [03:41<19:01,  4.98it/s]

Processing tickers:  16%|█▌        | 1087/6774 [03:41<18:55,  5.01it/s]

Processing tickers:  16%|█▌        | 1088/6774 [03:42<18:53,  5.02it/s]

Processing tickers:  16%|█▌        | 1089/6774 [03:42<18:52,  5.02it/s]

Processing tickers:  16%|█▌        | 1090/6774 [03:42<18:50,  5.03it/s]

Processing tickers:  16%|█▌        | 1091/6774 [03:42<19:03,  4.97it/s]

Processing tickers:  16%|█▌        | 1092/6774 [03:42<19:21,  4.89it/s]

Processing tickers:  16%|█▌        | 1093/6774 [03:43<19:34,  4.84it/s]

Processing tickers:  16%|█▌        | 1094/6774 [03:43<19:49,  4.78it/s]

Processing tickers:  16%|█▌        | 1095/6774 [03:43<19:58,  4.74it/s]

Processing tickers:  16%|█▌        | 1096/6774 [03:43<19:40,  4.81it/s]

Processing tickers:  16%|█▌        | 1097/6774 [03:43<19:57,  4.74it/s]

Processing tickers:  16%|█▌        | 1098/6774 [03:44<19:50,  4.77it/s]

Processing tickers:  16%|█▌        | 1099/6774 [03:44<19:49,  4.77it/s]

Processing tickers:  16%|█▌        | 1100/6774 [03:44<20:16,  4.66it/s]

Processing tickers:  16%|█▋        | 1101/6774 [03:44<20:09,  4.69it/s]

Processing tickers:  16%|█▋        | 1102/6774 [03:44<19:44,  4.79it/s]

Processing tickers:  16%|█▋        | 1103/6774 [03:45<19:26,  4.86it/s]

Processing tickers:  16%|█▋        | 1104/6774 [03:45<19:29,  4.85it/s]

Processing tickers:  16%|█▋        | 1105/6774 [03:45<19:15,  4.90it/s]

Processing tickers:  16%|█▋        | 1106/6774 [03:45<19:19,  4.89it/s]

Processing tickers:  16%|█▋        | 1107/6774 [03:46<19:57,  4.73it/s]

Processing tickers:  16%|█▋        | 1108/6774 [03:46<19:56,  4.74it/s]

Processing tickers:  16%|█▋        | 1109/6774 [03:46<19:45,  4.78it/s]

Processing tickers:  16%|█▋        | 1110/6774 [03:46<19:31,  4.83it/s]

Processing tickers:  16%|█▋        | 1111/6774 [03:46<19:13,  4.91it/s]

Processing tickers:  16%|█▋        | 1112/6774 [03:47<19:16,  4.90it/s]

Processing tickers:  16%|█▋        | 1113/6774 [03:47<19:25,  4.86it/s]

Processing tickers:  16%|█▋        | 1114/6774 [03:47<19:12,  4.91it/s]

Processing tickers:  16%|█▋        | 1115/6774 [03:47<19:06,  4.94it/s]

Processing tickers:  16%|█▋        | 1116/6774 [03:47<19:07,  4.93it/s]

Processing tickers:  16%|█▋        | 1117/6774 [03:48<18:59,  4.96it/s]

Processing tickers:  17%|█▋        | 1118/6774 [03:48<19:04,  4.94it/s]

Processing tickers:  17%|█▋        | 1119/6774 [03:48<19:08,  4.92it/s]

Processing tickers:  17%|█▋        | 1120/6774 [03:48<18:58,  4.97it/s]

Processing tickers:  17%|█▋        | 1121/6774 [03:48<18:47,  5.01it/s]

Processing tickers:  17%|█▋        | 1122/6774 [03:49<18:43,  5.03it/s]

Processing tickers:  17%|█▋        | 1123/6774 [03:49<18:40,  5.04it/s]

Processing tickers:  17%|█▋        | 1124/6774 [03:49<18:46,  5.02it/s]

Processing tickers:  17%|█▋        | 1125/6774 [03:49<18:53,  4.98it/s]

Processing tickers:  17%|█▋        | 1126/6774 [03:49<18:57,  4.96it/s]

Processing tickers:  17%|█▋        | 1127/6774 [03:50<18:52,  4.99it/s]

Processing tickers:  17%|█▋        | 1128/6774 [03:50<18:49,  5.00it/s]

Processing tickers:  17%|█▋        | 1129/6774 [03:50<19:12,  4.90it/s]

Processing tickers:  17%|█▋        | 1130/6774 [03:50<19:03,  4.94it/s]

Processing tickers:  17%|█▋        | 1131/6774 [03:50<18:54,  4.97it/s]

Processing tickers:  17%|█▋        | 1132/6774 [03:51<18:48,  5.00it/s]

Processing tickers:  17%|█▋        | 1133/6774 [03:51<18:51,  4.99it/s]

Processing tickers:  17%|█▋        | 1134/6774 [03:51<19:12,  4.89it/s]

Processing tickers:  17%|█▋        | 1135/6774 [03:51<19:28,  4.83it/s]

Processing tickers:  17%|█▋        | 1136/6774 [03:51<19:11,  4.90it/s]

Processing tickers:  17%|█▋        | 1137/6774 [03:52<18:59,  4.95it/s]

Processing tickers:  17%|█▋        | 1138/6774 [03:52<18:52,  4.98it/s]

Processing tickers:  17%|█▋        | 1139/6774 [03:52<19:16,  4.87it/s]

Processing tickers:  17%|█▋        | 1140/6774 [03:52<19:23,  4.84it/s]

Processing tickers:  17%|█▋        | 1141/6774 [03:52<19:20,  4.85it/s]

Processing tickers:  17%|█▋        | 1142/6774 [03:53<19:07,  4.91it/s]

Processing tickers:  17%|█▋        | 1143/6774 [03:53<18:51,  4.98it/s]

Processing tickers:  17%|█▋        | 1144/6774 [03:53<19:15,  4.87it/s]

Processing tickers:  17%|█▋        | 1145/6774 [03:53<19:09,  4.90it/s]

Processing tickers:  17%|█▋        | 1146/6774 [03:53<19:07,  4.91it/s]

Processing tickers:  17%|█▋        | 1147/6774 [03:54<19:03,  4.92it/s]

Processing tickers:  17%|█▋        | 1148/6774 [03:54<18:54,  4.96it/s]

Processing tickers:  17%|█▋        | 1149/6774 [03:54<19:14,  4.87it/s]

Processing tickers:  17%|█▋        | 1150/6774 [03:54<19:06,  4.90it/s]

Processing tickers:  17%|█▋        | 1151/6774 [03:54<19:14,  4.87it/s]

Processing tickers:  17%|█▋        | 1152/6774 [03:55<19:40,  4.76it/s]

Processing tickers:  17%|█▋        | 1153/6774 [03:55<19:29,  4.81it/s]

Processing tickers:  17%|█▋        | 1154/6774 [03:55<19:21,  4.84it/s]

Processing tickers:  17%|█▋        | 1155/6774 [03:55<19:50,  4.72it/s]

Processing tickers:  17%|█▋        | 1156/6774 [03:55<19:56,  4.70it/s]

Processing tickers:  17%|█▋        | 1157/6774 [03:56<19:30,  4.80it/s]

Processing tickers:  17%|█▋        | 1158/6774 [03:56<19:20,  4.84it/s]

Processing tickers:  17%|█▋        | 1159/6774 [03:56<19:08,  4.89it/s]

Processing tickers:  17%|█▋        | 1160/6774 [03:56<19:00,  4.92it/s]

Processing tickers:  17%|█▋        | 1161/6774 [03:57<19:14,  4.86it/s]

Processing tickers:  17%|█▋        | 1162/6774 [03:57<19:05,  4.90it/s]

Processing tickers:  17%|█▋        | 1163/6774 [03:57<18:59,  4.92it/s]

Processing tickers:  17%|█▋        | 1164/6774 [03:57<19:01,  4.91it/s]

Processing tickers:  17%|█▋        | 1165/6774 [03:57<19:06,  4.89it/s]

Processing tickers:  17%|█▋        | 1166/6774 [03:58<19:10,  4.88it/s]

Processing tickers:  17%|█▋        | 1167/6774 [03:58<19:12,  4.86it/s]

Processing tickers:  17%|█▋        | 1168/6774 [03:58<18:59,  4.92it/s]

Processing tickers:  17%|█▋        | 1169/6774 [03:58<19:20,  4.83it/s]

Processing tickers:  17%|█▋        | 1170/6774 [03:58<19:14,  4.86it/s]

Processing tickers:  17%|█▋        | 1171/6774 [03:59<19:24,  4.81it/s]

Processing tickers:  17%|█▋        | 1172/6774 [03:59<19:10,  4.87it/s]

Processing tickers:  17%|█▋        | 1173/6774 [03:59<19:09,  4.87it/s]

Processing tickers:  17%|█▋        | 1174/6774 [03:59<18:54,  4.93it/s]

Processing tickers:  17%|█▋        | 1175/6774 [03:59<18:55,  4.93it/s]

Processing tickers:  17%|█▋        | 1176/6774 [04:00<18:59,  4.91it/s]

Processing tickers:  17%|█▋        | 1177/6774 [04:00<18:48,  4.96it/s]

Processing tickers:  17%|█▋        | 1178/6774 [04:00<19:41,  4.73it/s]

Processing tickers:  17%|█▋        | 1179/6774 [04:00<19:21,  4.82it/s]

Processing tickers:  17%|█▋        | 1180/6774 [04:00<19:16,  4.84it/s]

Processing tickers:  17%|█▋        | 1181/6774 [04:01<19:00,  4.90it/s]

Processing tickers:  17%|█▋        | 1182/6774 [04:01<18:51,  4.94it/s]

Processing tickers:  17%|█▋        | 1183/6774 [04:01<18:54,  4.93it/s]

Processing tickers:  17%|█▋        | 1184/6774 [04:01<19:33,  4.76it/s]

Processing tickers:  17%|█▋        | 1185/6774 [04:01<19:25,  4.80it/s]

Processing tickers:  18%|█▊        | 1186/6774 [04:02<19:06,  4.88it/s]

Processing tickers:  18%|█▊        | 1187/6774 [04:02<18:52,  4.93it/s]

Processing tickers:  18%|█▊        | 1188/6774 [04:02<18:51,  4.94it/s]

Processing tickers:  18%|█▊        | 1189/6774 [04:02<18:44,  4.97it/s]

Processing tickers:  18%|█▊        | 1190/6774 [04:02<18:54,  4.92it/s]

Processing tickers:  18%|█▊        | 1191/6774 [04:03<18:49,  4.94it/s]

Processing tickers:  18%|█▊        | 1192/6774 [04:03<18:39,  4.99it/s]

Processing tickers:  18%|█▊        | 1193/6774 [04:03<18:34,  5.01it/s]

Processing tickers:  18%|█▊        | 1194/6774 [04:03<18:43,  4.97it/s]

Processing tickers:  18%|█▊        | 1195/6774 [04:03<18:38,  4.99it/s]

Processing tickers:  18%|█▊        | 1196/6774 [04:04<18:48,  4.94it/s]

Processing tickers:  18%|█▊        | 1197/6774 [04:04<19:01,  4.89it/s]

Processing tickers:  18%|█▊        | 1198/6774 [04:04<18:49,  4.94it/s]

Processing tickers:  18%|█▊        | 1199/6774 [04:04<18:46,  4.95it/s]

Processing tickers:  18%|█▊        | 1200/6774 [04:04<18:47,  4.94it/s]

Processing tickers:  18%|█▊        | 1201/6774 [04:05<18:46,  4.95it/s]

Processing tickers:  18%|█▊        | 1202/6774 [04:05<18:46,  4.95it/s]

Processing tickers:  18%|█▊        | 1203/6774 [04:05<19:46,  4.70it/s]

Processing tickers:  18%|█▊        | 1204/6774 [04:05<19:27,  4.77it/s]

Processing tickers:  18%|█▊        | 1205/6774 [04:06<19:19,  4.80it/s]

Processing tickers:  18%|█▊        | 1206/6774 [04:06<19:16,  4.82it/s]

Processing tickers:  18%|█▊        | 1207/6774 [04:06<19:13,  4.83it/s]

Processing tickers:  18%|█▊        | 1208/6774 [04:06<19:01,  4.88it/s]

Processing tickers:  18%|█▊        | 1209/6774 [04:06<18:50,  4.92it/s]

Processing tickers:  18%|█▊        | 1210/6774 [04:07<18:56,  4.90it/s]

Processing tickers:  18%|█▊        | 1211/6774 [04:07<18:50,  4.92it/s]

Processing tickers:  18%|█▊        | 1212/6774 [04:07<18:49,  4.93it/s]

Processing tickers:  18%|█▊        | 1213/6774 [04:07<19:04,  4.86it/s]

Processing tickers:  18%|█▊        | 1214/6774 [04:07<18:55,  4.90it/s]

Processing tickers:  18%|█▊        | 1215/6774 [04:08<18:53,  4.91it/s]

Processing tickers:  18%|█▊        | 1216/6774 [04:08<18:46,  4.93it/s]

Processing tickers:  18%|█▊        | 1217/6774 [04:08<18:44,  4.94it/s]

Processing tickers:  18%|█▊        | 1218/6774 [04:08<18:35,  4.98it/s]

Processing tickers:  18%|█▊        | 1219/6774 [04:08<19:13,  4.82it/s]

Processing tickers:  18%|█▊        | 1220/6774 [04:09<19:18,  4.79it/s]

Processing tickers:  18%|█▊        | 1221/6774 [04:09<19:36,  4.72it/s]

Processing tickers:  18%|█▊        | 1222/6774 [04:09<19:25,  4.76it/s]

Processing tickers:  18%|█▊        | 1223/6774 [04:09<19:15,  4.80it/s]

Processing tickers:  18%|█▊        | 1224/6774 [04:09<19:08,  4.83it/s]

Processing tickers:  18%|█▊        | 1225/6774 [04:10<18:58,  4.87it/s]

Processing tickers:  18%|█▊        | 1226/6774 [04:10<18:47,  4.92it/s]

Processing tickers:  18%|█▊        | 1227/6774 [04:10<19:05,  4.84it/s]

Processing tickers:  18%|█▊        | 1228/6774 [04:10<19:41,  4.70it/s]

Processing tickers:  18%|█▊        | 1229/6774 [04:10<19:29,  4.74it/s]

Processing tickers:  18%|█▊        | 1230/6774 [04:11<19:01,  4.86it/s]

Processing tickers:  18%|█▊        | 1231/6774 [04:11<18:53,  4.89it/s]

Processing tickers:  18%|█▊        | 1232/6774 [04:11<18:44,  4.93it/s]

Processing tickers:  18%|█▊        | 1233/6774 [04:11<18:45,  4.92it/s]

Processing tickers:  18%|█▊        | 1234/6774 [04:11<18:38,  4.95it/s]

Processing tickers:  18%|█▊        | 1235/6774 [04:12<18:33,  4.97it/s]

Processing tickers:  18%|█▊        | 1236/6774 [04:12<18:30,  4.99it/s]

Processing tickers:  18%|█▊        | 1237/6774 [04:12<18:28,  5.00it/s]

Processing tickers:  18%|█▊        | 1238/6774 [04:12<18:29,  4.99it/s]

Processing tickers:  18%|█▊        | 1239/6774 [04:12<18:27,  5.00it/s]

Processing tickers:  18%|█▊        | 1240/6774 [04:13<18:24,  5.01it/s]

Processing tickers:  18%|█▊        | 1241/6774 [04:13<18:34,  4.97it/s]

Processing tickers:  18%|█▊        | 1242/6774 [04:13<18:39,  4.94it/s]

Processing tickers:  18%|█▊        | 1243/6774 [04:13<18:36,  4.95it/s]

Processing tickers:  18%|█▊        | 1244/6774 [04:13<18:41,  4.93it/s]

Processing tickers:  18%|█▊        | 1245/6774 [04:14<19:11,  4.80it/s]

Processing tickers:  18%|█▊        | 1246/6774 [04:14<18:54,  4.87it/s]

Processing tickers:  18%|█▊        | 1247/6774 [04:14<18:43,  4.92it/s]

Processing tickers:  18%|█▊        | 1248/6774 [04:14<18:46,  4.91it/s]

Processing tickers:  18%|█▊        | 1249/6774 [04:14<18:56,  4.86it/s]

Processing tickers:  18%|█▊        | 1250/6774 [04:15<18:46,  4.91it/s]

Processing tickers:  18%|█▊        | 1251/6774 [04:15<18:46,  4.90it/s]

Processing tickers:  18%|█▊        | 1252/6774 [04:15<18:42,  4.92it/s]

Processing tickers:  18%|█▊        | 1253/6774 [04:15<18:37,  4.94it/s]

Processing tickers:  19%|█▊        | 1254/6774 [04:16<18:33,  4.96it/s]

Processing tickers:  19%|█▊        | 1255/6774 [04:16<18:28,  4.98it/s]

Processing tickers:  19%|█▊        | 1256/6774 [04:16<18:27,  4.98it/s]

Processing tickers:  19%|█▊        | 1257/6774 [04:16<18:44,  4.91it/s]

Processing tickers:  19%|█▊        | 1258/6774 [04:16<19:02,  4.83it/s]

Processing tickers:  19%|█▊        | 1259/6774 [04:17<18:48,  4.89it/s]

Processing tickers:  19%|█▊        | 1260/6774 [04:17<18:36,  4.94it/s]

Processing tickers:  19%|█▊        | 1261/6774 [04:17<18:35,  4.94it/s]

Processing tickers:  19%|█▊        | 1262/6774 [04:17<18:25,  4.99it/s]

Processing tickers:  19%|█▊        | 1263/6774 [04:17<18:26,  4.98it/s]

Processing tickers:  19%|█▊        | 1264/6774 [04:18<18:27,  4.98it/s]

Processing tickers:  19%|█▊        | 1265/6774 [04:18<18:26,  4.98it/s]

Processing tickers:  19%|█▊        | 1266/6774 [04:18<18:31,  4.96it/s]

Processing tickers:  19%|█▊        | 1267/6774 [04:18<19:04,  4.81it/s]

Processing tickers:  19%|█▊        | 1268/6774 [04:18<18:49,  4.88it/s]

Processing tickers:  19%|█▊        | 1269/6774 [04:19<18:44,  4.89it/s]

Processing tickers:  19%|█▊        | 1270/6774 [04:19<18:35,  4.93it/s]

Processing tickers:  19%|█▉        | 1271/6774 [04:19<18:32,  4.95it/s]

Processing tickers:  19%|█▉        | 1272/6774 [04:19<18:31,  4.95it/s]

Processing tickers:  19%|█▉        | 1273/6774 [04:19<18:26,  4.97it/s]

Processing tickers:  19%|█▉        | 1274/6774 [04:20<18:27,  4.96it/s]

Processing tickers:  19%|█▉        | 1275/6774 [04:20<18:27,  4.97it/s]

Processing tickers:  19%|█▉        | 1276/6774 [04:20<18:19,  5.00it/s]

Processing tickers:  19%|█▉        | 1277/6774 [04:20<18:20,  4.99it/s]

Processing tickers:  19%|█▉        | 1278/6774 [04:20<18:40,  4.90it/s]

Processing tickers:  19%|█▉        | 1279/6774 [04:21<18:38,  4.91it/s]

Processing tickers:  19%|█▉        | 1280/6774 [04:21<18:27,  4.96it/s]

Processing tickers:  19%|█▉        | 1281/6774 [04:21<18:50,  4.86it/s]

Processing tickers:  19%|█▉        | 1282/6774 [04:21<18:39,  4.91it/s]

Processing tickers:  19%|█▉        | 1283/6774 [04:21<18:33,  4.93it/s]

Processing tickers:  19%|█▉        | 1284/6774 [04:22<18:30,  4.94it/s]

Processing tickers:  19%|█▉        | 1285/6774 [04:22<18:27,  4.95it/s]

Processing tickers:  19%|█▉        | 1286/6774 [04:22<18:40,  4.90it/s]

Processing tickers:  19%|█▉        | 1287/6774 [04:22<18:28,  4.95it/s]

Processing tickers:  19%|█▉        | 1288/6774 [04:22<18:29,  4.95it/s]

Processing tickers:  19%|█▉        | 1289/6774 [04:23<18:37,  4.91it/s]

Processing tickers:  19%|█▉        | 1290/6774 [04:23<18:35,  4.92it/s]

Processing tickers:  19%|█▉        | 1291/6774 [04:23<18:45,  4.87it/s]

Processing tickers:  19%|█▉        | 1292/6774 [04:23<18:32,  4.93it/s]

Processing tickers:  19%|█▉        | 1293/6774 [04:23<19:35,  4.66it/s]

Processing tickers:  19%|█▉        | 1294/6774 [04:24<19:29,  4.69it/s]

Processing tickers:  19%|█▉        | 1295/6774 [04:24<19:40,  4.64it/s]

Processing tickers:  19%|█▉        | 1296/6774 [04:24<19:31,  4.68it/s]

Processing tickers:  19%|█▉        | 1297/6774 [04:24<19:49,  4.60it/s]

Processing tickers:  19%|█▉        | 1298/6774 [04:25<21:15,  4.29it/s]

Processing tickers:  19%|█▉        | 1299/6774 [04:25<20:30,  4.45it/s]

Processing tickers:  19%|█▉        | 1300/6774 [04:25<20:01,  4.55it/s]

Processing tickers:  19%|█▉        | 1301/6774 [04:25<19:32,  4.67it/s]

Processing tickers:  19%|█▉        | 1302/6774 [04:25<19:43,  4.62it/s]

Processing tickers:  19%|█▉        | 1303/6774 [04:26<19:19,  4.72it/s]

Processing tickers:  19%|█▉        | 1304/6774 [04:26<18:58,  4.80it/s]

Processing tickers:  19%|█▉        | 1305/6774 [04:26<18:52,  4.83it/s]

Processing tickers:  19%|█▉        | 1306/6774 [04:26<19:00,  4.80it/s]

Processing tickers:  19%|█▉        | 1307/6774 [04:26<18:58,  4.80it/s]

Processing tickers:  19%|█▉        | 1308/6774 [04:27<19:29,  4.67it/s]

Processing tickers:  19%|█▉        | 1309/6774 [04:27<19:40,  4.63it/s]

Processing tickers:  19%|█▉        | 1310/6774 [04:27<19:10,  4.75it/s]

Processing tickers:  19%|█▉        | 1311/6774 [04:27<18:51,  4.83it/s]

Processing tickers:  19%|█▉        | 1312/6774 [04:28<18:55,  4.81it/s]

Processing tickers:  19%|█▉        | 1313/6774 [04:28<19:08,  4.76it/s]

Processing tickers:  19%|█▉        | 1314/6774 [04:28<19:06,  4.76it/s]

Processing tickers:  19%|█▉        | 1315/6774 [04:28<18:54,  4.81it/s]

Processing tickers:  19%|█▉        | 1316/6774 [04:28<19:22,  4.69it/s]

Processing tickers:  19%|█▉        | 1317/6774 [04:29<18:57,  4.80it/s]

Processing tickers:  19%|█▉        | 1318/6774 [04:29<19:14,  4.73it/s]

Processing tickers:  19%|█▉        | 1319/6774 [04:29<19:07,  4.75it/s]

Processing tickers:  19%|█▉        | 1320/6774 [04:29<18:53,  4.81it/s]

Processing tickers:  20%|█▉        | 1321/6774 [04:29<18:51,  4.82it/s]

Processing tickers:  20%|█▉        | 1322/6774 [04:30<18:33,  4.89it/s]

Processing tickers:  20%|█▉        | 1323/6774 [04:30<18:26,  4.93it/s]

Processing tickers:  20%|█▉        | 1324/6774 [04:30<18:30,  4.91it/s]

Processing tickers:  20%|█▉        | 1325/6774 [04:30<18:47,  4.83it/s]

Processing tickers:  20%|█▉        | 1326/6774 [04:30<19:01,  4.77it/s]

Processing tickers:  20%|█▉        | 1327/6774 [04:31<18:46,  4.84it/s]

Processing tickers:  20%|█▉        | 1328/6774 [04:31<18:29,  4.91it/s]

Processing tickers:  20%|█▉        | 1329/6774 [04:31<18:25,  4.92it/s]

Processing tickers:  20%|█▉        | 1330/6774 [04:31<18:19,  4.95it/s]

Processing tickers:  20%|█▉        | 1331/6774 [04:31<18:28,  4.91it/s]

Processing tickers:  20%|█▉        | 1332/6774 [04:32<18:43,  4.84it/s]

Processing tickers:  20%|█▉        | 1333/6774 [04:32<18:36,  4.87it/s]

Processing tickers:  20%|█▉        | 1334/6774 [04:32<18:55,  4.79it/s]

Processing tickers:  20%|█▉        | 1335/6774 [04:32<18:48,  4.82it/s]

Processing tickers:  20%|█▉        | 1336/6774 [04:32<18:43,  4.84it/s]

Processing tickers:  20%|█▉        | 1337/6774 [04:33<18:36,  4.87it/s]

Processing tickers:  20%|█▉        | 1338/6774 [04:33<18:57,  4.78it/s]

Processing tickers:  20%|█▉        | 1339/6774 [04:33<18:58,  4.77it/s]

Processing tickers:  20%|█▉        | 1340/6774 [04:33<19:11,  4.72it/s]

Processing tickers:  20%|█▉        | 1341/6774 [04:34<19:19,  4.68it/s]

Processing tickers:  20%|█▉        | 1342/6774 [04:34<19:28,  4.65it/s]

Processing tickers:  20%|█▉        | 1343/6774 [04:34<19:07,  4.73it/s]

Processing tickers:  20%|█▉        | 1344/6774 [04:34<18:52,  4.79it/s]

Processing tickers:  20%|█▉        | 1345/6774 [04:34<18:56,  4.78it/s]

Processing tickers:  20%|█▉        | 1346/6774 [04:35<19:20,  4.68it/s]

Processing tickers:  20%|█▉        | 1347/6774 [04:35<19:01,  4.76it/s]

Processing tickers:  20%|█▉        | 1348/6774 [04:35<18:52,  4.79it/s]

Processing tickers:  20%|█▉        | 1349/6774 [04:35<19:24,  4.66it/s]

Processing tickers:  20%|█▉        | 1350/6774 [04:35<19:44,  4.58it/s]

Processing tickers:  20%|█▉        | 1351/6774 [04:36<19:29,  4.64it/s]

Processing tickers:  20%|█▉        | 1352/6774 [04:36<19:04,  4.74it/s]

Processing tickers:  20%|█▉        | 1353/6774 [04:36<18:59,  4.76it/s]

Processing tickers:  20%|█▉        | 1354/6774 [04:36<19:19,  4.67it/s]

Processing tickers:  20%|██        | 1355/6774 [04:37<19:02,  4.74it/s]

Processing tickers:  20%|██        | 1356/6774 [04:37<18:43,  4.82it/s]

Processing tickers:  20%|██        | 1357/6774 [04:37<19:01,  4.75it/s]

Processing tickers:  20%|██        | 1358/6774 [04:37<19:05,  4.73it/s]

Processing tickers:  20%|██        | 1359/6774 [04:37<18:51,  4.79it/s]

Processing tickers:  20%|██        | 1360/6774 [04:38<19:00,  4.75it/s]

Processing tickers:  20%|██        | 1361/6774 [04:38<18:39,  4.84it/s]

Processing tickers:  20%|██        | 1362/6774 [04:38<18:44,  4.81it/s]

Processing tickers:  20%|██        | 1363/6774 [04:38<18:32,  4.86it/s]

Processing tickers:  20%|██        | 1364/6774 [04:38<18:56,  4.76it/s]

Processing tickers:  20%|██        | 1365/6774 [04:39<18:41,  4.82it/s]

Processing tickers:  20%|██        | 1366/6774 [04:39<18:29,  4.88it/s]

Processing tickers:  20%|██        | 1367/6774 [04:39<18:21,  4.91it/s]

Processing tickers:  20%|██        | 1368/6774 [04:39<18:18,  4.92it/s]

Processing tickers:  20%|██        | 1369/6774 [04:39<18:51,  4.78it/s]

Processing tickers:  20%|██        | 1370/6774 [04:40<18:41,  4.82it/s]

Processing tickers:  20%|██        | 1371/6774 [04:40<18:26,  4.88it/s]

Processing tickers:  20%|██        | 1372/6774 [04:40<18:24,  4.89it/s]

Processing tickers:  20%|██        | 1373/6774 [04:40<18:15,  4.93it/s]

Processing tickers:  20%|██        | 1374/6774 [04:40<18:34,  4.84it/s]

Processing tickers:  20%|██        | 1375/6774 [04:41<18:27,  4.87it/s]

Processing tickers:  20%|██        | 1376/6774 [04:41<18:33,  4.85it/s]

Processing tickers:  20%|██        | 1377/6774 [04:41<18:21,  4.90it/s]

Processing tickers:  20%|██        | 1378/6774 [04:41<18:31,  4.86it/s]

Processing tickers:  20%|██        | 1379/6774 [04:41<18:17,  4.91it/s]

Processing tickers:  20%|██        | 1380/6774 [04:42<18:20,  4.90it/s]

Processing tickers:  20%|██        | 1381/6774 [04:42<18:42,  4.80it/s]

Processing tickers:  20%|██        | 1382/6774 [04:42<18:31,  4.85it/s]

Processing tickers:  20%|██        | 1383/6774 [04:42<18:31,  4.85it/s]

Processing tickers:  20%|██        | 1384/6774 [04:42<18:27,  4.87it/s]

Processing tickers:  20%|██        | 1385/6774 [04:43<18:19,  4.90it/s]

Processing tickers:  20%|██        | 1386/6774 [04:43<18:12,  4.93it/s]

Processing tickers:  20%|██        | 1387/6774 [04:43<18:24,  4.88it/s]

Processing tickers:  20%|██        | 1388/6774 [04:43<18:16,  4.91it/s]

Processing tickers:  21%|██        | 1389/6774 [04:43<18:13,  4.93it/s]

Processing tickers:  21%|██        | 1390/6774 [04:44<18:49,  4.76it/s]

Processing tickers:  21%|██        | 1391/6774 [04:44<19:05,  4.70it/s]

Processing tickers:  21%|██        | 1392/6774 [04:44<18:41,  4.80it/s]

Processing tickers:  21%|██        | 1393/6774 [04:44<18:41,  4.80it/s]

Processing tickers:  21%|██        | 1394/6774 [04:45<18:32,  4.84it/s]

Processing tickers:  21%|██        | 1395/6774 [04:45<18:23,  4.88it/s]

Processing tickers:  21%|██        | 1396/6774 [04:45<18:12,  4.92it/s]

Processing tickers:  21%|██        | 1397/6774 [04:45<18:12,  4.92it/s]

Processing tickers:  21%|██        | 1398/6774 [04:45<18:28,  4.85it/s]

Processing tickers:  21%|██        | 1399/6774 [04:46<18:53,  4.74it/s]

Processing tickers:  21%|██        | 1400/6774 [04:46<18:36,  4.81it/s]

Processing tickers:  21%|██        | 1401/6774 [04:46<18:45,  4.77it/s]

Processing tickers:  21%|██        | 1402/6774 [04:46<18:42,  4.78it/s]

Processing tickers:  21%|██        | 1403/6774 [04:46<18:29,  4.84it/s]

Processing tickers:  21%|██        | 1404/6774 [04:47<19:02,  4.70it/s]

Processing tickers:  21%|██        | 1405/6774 [04:47<18:36,  4.81it/s]

Processing tickers:  21%|██        | 1406/6774 [04:47<18:29,  4.84it/s]

Processing tickers:  21%|██        | 1407/6774 [04:47<18:20,  4.88it/s]

Processing tickers:  21%|██        | 1408/6774 [04:47<18:09,  4.92it/s]

Processing tickers:  21%|██        | 1409/6774 [04:48<18:01,  4.96it/s]

Processing tickers:  21%|██        | 1410/6774 [04:48<17:57,  4.98it/s]

Processing tickers:  21%|██        | 1411/6774 [04:48<17:56,  4.98it/s]

Processing tickers:  21%|██        | 1412/6774 [04:48<17:54,  4.99it/s]

Processing tickers:  21%|██        | 1413/6774 [04:48<18:03,  4.95it/s]

Processing tickers:  21%|██        | 1414/6774 [04:49<18:02,  4.95it/s]

Processing tickers:  21%|██        | 1415/6774 [04:49<18:01,  4.96it/s]

Processing tickers:  21%|██        | 1416/6774 [04:49<18:24,  4.85it/s]

Processing tickers:  21%|██        | 1417/6774 [04:49<18:12,  4.91it/s]

Processing tickers:  21%|██        | 1418/6774 [04:49<18:34,  4.80it/s]

Processing tickers:  21%|██        | 1419/6774 [04:50<18:27,  4.83it/s]

Processing tickers:  21%|██        | 1420/6774 [04:50<20:39,  4.32it/s]

Processing tickers:  21%|██        | 1421/6774 [04:50<20:03,  4.45it/s]

Processing tickers:  21%|██        | 1422/6774 [04:50<20:05,  4.44it/s]

Processing tickers:  21%|██        | 1423/6774 [04:51<19:37,  4.55it/s]

Processing tickers:  21%|██        | 1424/6774 [04:51<19:17,  4.62it/s]

Processing tickers:  21%|██        | 1425/6774 [04:51<19:01,  4.68it/s]

Processing tickers:  21%|██        | 1426/6774 [04:51<18:52,  4.72it/s]

Processing tickers:  21%|██        | 1427/6774 [04:51<18:39,  4.78it/s]

Processing tickers:  21%|██        | 1428/6774 [04:52<18:30,  4.82it/s]

Processing tickers:  21%|██        | 1429/6774 [04:52<18:23,  4.84it/s]

Processing tickers:  21%|██        | 1430/6774 [04:52<18:34,  4.79it/s]

Processing tickers:  21%|██        | 1431/6774 [04:52<19:01,  4.68it/s]

Processing tickers:  21%|██        | 1432/6774 [04:52<18:50,  4.72it/s]

Processing tickers:  21%|██        | 1433/6774 [04:53<18:31,  4.81it/s]

Processing tickers:  21%|██        | 1434/6774 [04:53<18:29,  4.81it/s]

Processing tickers:  21%|██        | 1435/6774 [04:53<18:24,  4.83it/s]

Processing tickers:  21%|██        | 1436/6774 [04:53<18:14,  4.88it/s]

Processing tickers:  21%|██        | 1437/6774 [04:54<18:10,  4.89it/s]

Processing tickers:  21%|██        | 1438/6774 [04:54<18:24,  4.83it/s]

Processing tickers:  21%|██        | 1439/6774 [04:54<18:26,  4.82it/s]

Processing tickers:  21%|██▏       | 1440/6774 [04:54<18:57,  4.69it/s]

Processing tickers:  21%|██▏       | 1441/6774 [04:54<18:36,  4.78it/s]

Processing tickers:  21%|██▏       | 1442/6774 [04:55<18:36,  4.77it/s]

Processing tickers:  21%|██▏       | 1443/6774 [04:55<19:12,  4.62it/s]

Processing tickers:  21%|██▏       | 1444/6774 [04:55<19:16,  4.61it/s]

Processing tickers:  21%|██▏       | 1445/6774 [04:55<18:47,  4.73it/s]

Processing tickers:  21%|██▏       | 1446/6774 [04:55<18:30,  4.80it/s]

Processing tickers:  21%|██▏       | 1447/6774 [04:56<18:54,  4.70it/s]

Processing tickers:  21%|██▏       | 1448/6774 [04:56<18:37,  4.77it/s]

Processing tickers:  21%|██▏       | 1449/6774 [04:56<19:04,  4.65it/s]

Processing tickers:  21%|██▏       | 1450/6774 [04:56<18:43,  4.74it/s]

Processing tickers:  21%|██▏       | 1451/6774 [04:56<18:32,  4.79it/s]

Processing tickers:  21%|██▏       | 1452/6774 [04:57<19:01,  4.66it/s]

Processing tickers:  21%|██▏       | 1453/6774 [04:57<19:12,  4.62it/s]

Processing tickers:  21%|██▏       | 1454/6774 [04:57<18:42,  4.74it/s]

Processing tickers:  21%|██▏       | 1455/6774 [04:57<18:28,  4.80it/s]

Processing tickers:  21%|██▏       | 1456/6774 [04:58<18:12,  4.87it/s]

Processing tickers:  22%|██▏       | 1457/6774 [04:58<18:08,  4.89it/s]

Processing tickers:  22%|██▏       | 1458/6774 [04:58<18:37,  4.76it/s]

Processing tickers:  22%|██▏       | 1459/6774 [04:58<18:21,  4.82it/s]

Processing tickers:  22%|██▏       | 1460/6774 [04:58<18:17,  4.84it/s]

Processing tickers:  22%|██▏       | 1461/6774 [04:59<18:16,  4.85it/s]

Processing tickers:  22%|██▏       | 1462/6774 [04:59<18:07,  4.89it/s]

Processing tickers:  22%|██▏       | 1463/6774 [04:59<18:04,  4.90it/s]

Processing tickers:  22%|██▏       | 1464/6774 [04:59<18:39,  4.74it/s]

Processing tickers:  22%|██▏       | 1465/6774 [04:59<20:43,  4.27it/s]

Processing tickers:  22%|██▏       | 1466/6774 [05:00<20:17,  4.36it/s]

Processing tickers:  22%|██▏       | 1467/6774 [05:00<19:33,  4.52it/s]

Processing tickers:  22%|██▏       | 1468/6774 [05:00<19:07,  4.63it/s]

Processing tickers:  22%|██▏       | 1469/6774 [05:00<18:52,  4.68it/s]

Processing tickers:  22%|██▏       | 1470/6774 [05:01<18:29,  4.78it/s]

Processing tickers:  22%|██▏       | 1471/6774 [05:01<18:16,  4.83it/s]

Processing tickers:  22%|██▏       | 1472/6774 [05:01<18:06,  4.88it/s]

Processing tickers:  22%|██▏       | 1473/6774 [05:01<17:57,  4.92it/s]

Processing tickers:  22%|██▏       | 1474/6774 [05:01<17:58,  4.92it/s]

Processing tickers:  22%|██▏       | 1475/6774 [05:02<18:24,  4.80it/s]

Processing tickers:  22%|██▏       | 1476/6774 [05:02<18:13,  4.85it/s]

Processing tickers:  22%|██▏       | 1477/6774 [05:02<18:31,  4.76it/s]

Processing tickers:  22%|██▏       | 1478/6774 [05:02<18:17,  4.83it/s]

Processing tickers:  22%|██▏       | 1479/6774 [05:02<18:03,  4.89it/s]

Processing tickers:  22%|██▏       | 1480/6774 [05:03<18:20,  4.81it/s]

Processing tickers:  22%|██▏       | 1481/6774 [05:03<18:09,  4.86it/s]

Processing tickers:  22%|██▏       | 1482/6774 [05:03<18:37,  4.74it/s]

Processing tickers:  22%|██▏       | 1483/6774 [05:03<18:14,  4.83it/s]

Processing tickers:  22%|██▏       | 1484/6774 [05:03<18:13,  4.84it/s]

Processing tickers:  22%|██▏       | 1485/6774 [05:04<18:01,  4.89it/s]

Processing tickers:  22%|██▏       | 1486/6774 [05:04<17:52,  4.93it/s]

Processing tickers:  22%|██▏       | 1487/6774 [05:04<18:06,  4.87it/s]

Processing tickers:  22%|██▏       | 1488/6774 [05:04<18:01,  4.89it/s]

Processing tickers:  22%|██▏       | 1489/6774 [05:04<18:14,  4.83it/s]

Processing tickers:  22%|██▏       | 1490/6774 [05:05<18:11,  4.84it/s]

Processing tickers:  22%|██▏       | 1491/6774 [05:05<18:11,  4.84it/s]

Processing tickers:  22%|██▏       | 1492/6774 [05:05<18:03,  4.88it/s]

Processing tickers:  22%|██▏       | 1493/6774 [05:05<17:57,  4.90it/s]

Processing tickers:  22%|██▏       | 1494/6774 [05:05<17:52,  4.92it/s]

Processing tickers:  22%|██▏       | 1495/6774 [05:06<18:24,  4.78it/s]

Processing tickers:  22%|██▏       | 1496/6774 [05:06<18:15,  4.82it/s]

Processing tickers:  22%|██▏       | 1497/6774 [05:06<18:02,  4.88it/s]

Processing tickers:  22%|██▏       | 1498/6774 [05:06<17:52,  4.92it/s]

Processing tickers:  22%|██▏       | 1499/6774 [05:06<17:44,  4.96it/s]

Processing tickers:  22%|██▏       | 1500/6774 [05:07<17:46,  4.95it/s]

Processing tickers:  22%|██▏       | 1501/6774 [05:07<18:01,  4.87it/s]

Processing tickers:  22%|██▏       | 1502/6774 [05:07<17:46,  4.94it/s]

Processing tickers:  22%|██▏       | 1503/6774 [05:07<17:48,  4.93it/s]

Processing tickers:  22%|██▏       | 1504/6774 [05:07<18:18,  4.80it/s]

Processing tickers:  22%|██▏       | 1505/6774 [05:08<18:10,  4.83it/s]

Processing tickers:  22%|██▏       | 1506/6774 [05:08<18:21,  4.78it/s]

Processing tickers:  22%|██▏       | 1507/6774 [05:08<18:34,  4.73it/s]

Processing tickers:  22%|██▏       | 1508/6774 [05:08<18:21,  4.78it/s]

Processing tickers:  22%|██▏       | 1509/6774 [05:09<18:03,  4.86it/s]

Processing tickers:  22%|██▏       | 1510/6774 [05:09<17:54,  4.90it/s]

Processing tickers:  22%|██▏       | 1511/6774 [05:09<17:48,  4.92it/s]

Processing tickers:  22%|██▏       | 1512/6774 [05:09<18:05,  4.85it/s]

Processing tickers:  22%|██▏       | 1513/6774 [05:09<18:09,  4.83it/s]

Processing tickers:  22%|██▏       | 1514/6774 [05:10<18:26,  4.75it/s]

Processing tickers:  22%|██▏       | 1515/6774 [05:10<18:39,  4.70it/s]

Processing tickers:  22%|██▏       | 1516/6774 [05:10<18:33,  4.72it/s]

Processing tickers:  22%|██▏       | 1517/6774 [05:10<18:42,  4.68it/s]

Processing tickers:  22%|██▏       | 1518/6774 [05:10<18:45,  4.67it/s]

Processing tickers:  22%|██▏       | 1519/6774 [05:11<18:30,  4.73it/s]

Processing tickers:  22%|██▏       | 1520/6774 [05:11<18:13,  4.81it/s]

Processing tickers:  22%|██▏       | 1521/6774 [05:11<18:13,  4.80it/s]

Processing tickers:  22%|██▏       | 1522/6774 [05:11<18:03,  4.85it/s]

Processing tickers:  22%|██▏       | 1523/6774 [05:11<17:52,  4.89it/s]

Processing tickers:  22%|██▏       | 1524/6774 [05:12<17:43,  4.94it/s]

Processing tickers:  23%|██▎       | 1525/6774 [05:12<17:46,  4.92it/s]

Processing tickers:  23%|██▎       | 1526/6774 [05:12<17:52,  4.89it/s]

Processing tickers:  23%|██▎       | 1527/6774 [05:12<17:38,  4.96it/s]

Processing tickers:  23%|██▎       | 1528/6774 [05:12<17:50,  4.90it/s]

Processing tickers:  23%|██▎       | 1529/6774 [05:13<18:19,  4.77it/s]

Processing tickers:  23%|██▎       | 1530/6774 [05:13<18:03,  4.84it/s]

Processing tickers:  23%|██▎       | 1531/6774 [05:13<17:58,  4.86it/s]

Processing tickers:  23%|██▎       | 1532/6774 [05:13<17:54,  4.88it/s]

Processing tickers:  23%|██▎       | 1533/6774 [05:14<17:57,  4.86it/s]

Processing tickers:  23%|██▎       | 1534/6774 [05:14<17:47,  4.91it/s]

Processing tickers:  23%|██▎       | 1535/6774 [05:14<17:40,  4.94it/s]

Processing tickers:  23%|██▎       | 1536/6774 [05:14<17:38,  4.95it/s]

Processing tickers:  23%|██▎       | 1537/6774 [05:14<17:35,  4.96it/s]

Processing tickers:  23%|██▎       | 1538/6774 [05:15<17:44,  4.92it/s]

Processing tickers:  23%|██▎       | 1539/6774 [05:15<17:37,  4.95it/s]

Processing tickers:  23%|██▎       | 1540/6774 [05:15<17:34,  4.96it/s]

Processing tickers:  23%|██▎       | 1541/6774 [05:15<17:59,  4.85it/s]

Processing tickers:  23%|██▎       | 1542/6774 [05:15<18:27,  4.73it/s]

Processing tickers:  23%|██▎       | 1543/6774 [05:16<18:16,  4.77it/s]

Processing tickers:  23%|██▎       | 1544/6774 [05:16<17:57,  4.85it/s]

Processing tickers:  23%|██▎       | 1545/6774 [05:16<17:55,  4.86it/s]

Processing tickers:  23%|██▎       | 1546/6774 [05:16<17:48,  4.89it/s]

Processing tickers:  23%|██▎       | 1547/6774 [05:16<17:49,  4.89it/s]

Processing tickers:  23%|██▎       | 1548/6774 [05:17<17:55,  4.86it/s]

Processing tickers:  23%|██▎       | 1549/6774 [05:17<17:45,  4.90it/s]

Processing tickers:  23%|██▎       | 1550/6774 [05:17<17:51,  4.87it/s]

Processing tickers:  23%|██▎       | 1551/6774 [05:17<17:50,  4.88it/s]

Processing tickers:  23%|██▎       | 1552/6774 [05:17<17:42,  4.92it/s]

Processing tickers:  23%|██▎       | 1553/6774 [05:18<17:34,  4.95it/s]

Processing tickers:  23%|██▎       | 1554/6774 [05:18<17:22,  5.01it/s]

Processing tickers:  23%|██▎       | 1555/6774 [05:18<17:41,  4.92it/s]

Processing tickers:  23%|██▎       | 1556/6774 [05:18<17:39,  4.92it/s]

Processing tickers:  23%|██▎       | 1557/6774 [05:18<17:46,  4.89it/s]

Processing tickers:  23%|██▎       | 1558/6774 [05:19<17:50,  4.87it/s]

Processing tickers:  23%|██▎       | 1559/6774 [05:19<17:41,  4.91it/s]

Processing tickers:  23%|██▎       | 1560/6774 [05:19<17:38,  4.93it/s]

Processing tickers:  23%|██▎       | 1561/6774 [05:19<17:41,  4.91it/s]

Processing tickers:  23%|██▎       | 1562/6774 [05:19<17:46,  4.88it/s]

Processing tickers:  23%|██▎       | 1563/6774 [05:20<17:35,  4.94it/s]

Processing tickers:  23%|██▎       | 1564/6774 [05:20<17:30,  4.96it/s]

Processing tickers:  23%|██▎       | 1565/6774 [05:20<17:34,  4.94it/s]

Processing tickers:  23%|██▎       | 1566/6774 [05:20<17:32,  4.95it/s]

Processing tickers:  23%|██▎       | 1567/6774 [05:20<17:58,  4.83it/s]

Processing tickers:  23%|██▎       | 1568/6774 [05:21<18:04,  4.80it/s]

Processing tickers:  23%|██▎       | 1569/6774 [05:21<18:22,  4.72it/s]

Processing tickers:  23%|██▎       | 1570/6774 [05:21<18:20,  4.73it/s]

Processing tickers:  23%|██▎       | 1571/6774 [05:21<18:04,  4.80it/s]

Processing tickers:  23%|██▎       | 1572/6774 [05:21<18:05,  4.79it/s]

Processing tickers:  23%|██▎       | 1573/6774 [05:22<17:46,  4.88it/s]

Processing tickers:  23%|██▎       | 1574/6774 [05:22<17:36,  4.92it/s]

Processing tickers:  23%|██▎       | 1575/6774 [05:22<18:10,  4.77it/s]

Processing tickers:  23%|██▎       | 1576/6774 [05:22<17:58,  4.82it/s]

Processing tickers:  23%|██▎       | 1577/6774 [05:23<17:53,  4.84it/s]

Processing tickers:  23%|██▎       | 1578/6774 [05:23<17:53,  4.84it/s]

Processing tickers:  23%|██▎       | 1579/6774 [05:23<18:06,  4.78it/s]

Processing tickers:  23%|██▎       | 1580/6774 [05:23<18:06,  4.78it/s]

Processing tickers:  23%|██▎       | 1581/6774 [05:23<17:58,  4.82it/s]

Processing tickers:  23%|██▎       | 1582/6774 [05:24<17:51,  4.84it/s]

Processing tickers:  23%|██▎       | 1583/6774 [05:24<18:14,  4.74it/s]

Processing tickers:  23%|██▎       | 1584/6774 [05:24<18:20,  4.72it/s]

Processing tickers:  23%|██▎       | 1585/6774 [05:24<18:04,  4.79it/s]

Processing tickers:  23%|██▎       | 1586/6774 [05:24<18:07,  4.77it/s]

Processing tickers:  23%|██▎       | 1587/6774 [05:25<18:34,  4.65it/s]

Processing tickers:  23%|██▎       | 1588/6774 [05:25<18:21,  4.71it/s]

Processing tickers:  23%|██▎       | 1589/6774 [05:25<18:27,  4.68it/s]

Processing tickers:  23%|██▎       | 1590/6774 [05:25<18:30,  4.67it/s]

Processing tickers:  23%|██▎       | 1591/6774 [05:25<18:06,  4.77it/s]

Processing tickers:  24%|██▎       | 1592/6774 [05:26<17:47,  4.85it/s]

Processing tickers:  24%|██▎       | 1593/6774 [05:26<17:40,  4.89it/s]

Processing tickers:  24%|██▎       | 1594/6774 [05:26<17:27,  4.94it/s]

Processing tickers:  24%|██▎       | 1595/6774 [05:26<17:26,  4.95it/s]

Processing tickers:  24%|██▎       | 1596/6774 [05:26<17:25,  4.95it/s]

Processing tickers:  24%|██▎       | 1597/6774 [05:27<17:23,  4.96it/s]

Processing tickers:  24%|██▎       | 1598/6774 [05:27<17:42,  4.87it/s]

Processing tickers:  24%|██▎       | 1599/6774 [05:27<17:42,  4.87it/s]

Processing tickers:  24%|██▎       | 1600/6774 [05:27<17:34,  4.91it/s]

Processing tickers:  24%|██▎       | 1601/6774 [05:27<17:34,  4.90it/s]

Processing tickers:  24%|██▎       | 1602/6774 [05:28<17:31,  4.92it/s]

Processing tickers:  24%|██▎       | 1603/6774 [05:28<17:28,  4.93it/s]

Processing tickers:  24%|██▎       | 1604/6774 [05:28<17:30,  4.92it/s]

Processing tickers:  24%|██▎       | 1605/6774 [05:28<17:30,  4.92it/s]

Processing tickers:  24%|██▎       | 1606/6774 [05:29<17:25,  4.94it/s]

Processing tickers:  24%|██▎       | 1607/6774 [05:29<17:32,  4.91it/s]

Processing tickers:  24%|██▎       | 1608/6774 [05:29<17:29,  4.92it/s]

Processing tickers:  24%|██▍       | 1609/6774 [05:29<17:19,  4.97it/s]

Processing tickers:  24%|██▍       | 1610/6774 [05:29<17:25,  4.94it/s]

Processing tickers:  24%|██▍       | 1611/6774 [05:30<17:21,  4.96it/s]

Processing tickers:  24%|██▍       | 1612/6774 [05:30<17:47,  4.84it/s]

Processing tickers:  24%|██▍       | 1613/6774 [05:30<17:31,  4.91it/s]

Processing tickers:  24%|██▍       | 1614/6774 [05:30<17:37,  4.88it/s]

Processing tickers:  24%|██▍       | 1615/6774 [05:30<17:25,  4.93it/s]

Processing tickers:  24%|██▍       | 1616/6774 [05:31<17:19,  4.96it/s]

Processing tickers:  24%|██▍       | 1617/6774 [05:31<17:23,  4.94it/s]

Processing tickers:  24%|██▍       | 1618/6774 [05:31<17:36,  4.88it/s]

Processing tickers:  24%|██▍       | 1619/6774 [05:31<17:30,  4.91it/s]

Processing tickers:  24%|██▍       | 1620/6774 [05:31<17:30,  4.91it/s]

Processing tickers:  24%|██▍       | 1621/6774 [05:32<17:22,  4.94it/s]

Processing tickers:  24%|██▍       | 1622/6774 [05:32<17:25,  4.93it/s]

Processing tickers:  24%|██▍       | 1623/6774 [05:32<17:54,  4.79it/s]

Processing tickers:  24%|██▍       | 1624/6774 [05:32<17:47,  4.82it/s]

Processing tickers:  24%|██▍       | 1625/6774 [05:32<17:39,  4.86it/s]

Processing tickers:  24%|██▍       | 1626/6774 [05:33<17:33,  4.89it/s]

Processing tickers:  24%|██▍       | 1627/6774 [05:33<17:21,  4.94it/s]

Processing tickers:  24%|██▍       | 1628/6774 [05:33<17:38,  4.86it/s]

Processing tickers:  24%|██▍       | 1629/6774 [05:33<17:33,  4.88it/s]

Processing tickers:  24%|██▍       | 1630/6774 [05:33<17:29,  4.90it/s]

Processing tickers:  24%|██▍       | 1631/6774 [05:34<17:21,  4.94it/s]

Processing tickers:  24%|██▍       | 1632/6774 [05:34<17:20,  4.94it/s]

Processing tickers:  24%|██▍       | 1633/6774 [05:34<17:26,  4.91it/s]

Processing tickers:  24%|██▍       | 1634/6774 [05:34<17:26,  4.91it/s]

Processing tickers:  24%|██▍       | 1635/6774 [05:34<17:40,  4.84it/s]

Processing tickers:  24%|██▍       | 1636/6774 [05:35<19:19,  4.43it/s]

Processing tickers:  24%|██▍       | 1637/6774 [05:35<18:56,  4.52it/s]

Processing tickers:  24%|██▍       | 1638/6774 [05:35<18:28,  4.63it/s]

Processing tickers:  24%|██▍       | 1639/6774 [05:35<18:14,  4.69it/s]

Processing tickers:  24%|██▍       | 1640/6774 [05:36<18:07,  4.72it/s]

Processing tickers:  24%|██▍       | 1641/6774 [05:36<17:52,  4.79it/s]

Processing tickers:  24%|██▍       | 1642/6774 [05:36<17:37,  4.85it/s]

Processing tickers:  24%|██▍       | 1643/6774 [05:36<17:43,  4.83it/s]

Processing tickers:  24%|██▍       | 1644/6774 [05:36<17:32,  4.87it/s]

Processing tickers:  24%|██▍       | 1645/6774 [05:37<17:20,  4.93it/s]

Processing tickers:  24%|██▍       | 1646/6774 [05:37<17:16,  4.95it/s]

Processing tickers:  24%|██▍       | 1647/6774 [05:37<17:08,  4.98it/s]

Processing tickers:  24%|██▍       | 1648/6774 [05:37<17:05,  5.00it/s]

Processing tickers:  24%|██▍       | 1649/6774 [05:37<17:11,  4.97it/s]

Processing tickers:  24%|██▍       | 1650/6774 [05:38<17:05,  4.99it/s]

Processing tickers:  24%|██▍       | 1651/6774 [05:38<17:04,  5.00it/s]

Processing tickers:  24%|██▍       | 1652/6774 [05:38<17:02,  5.01it/s]

Processing tickers:  24%|██▍       | 1653/6774 [05:38<17:01,  5.01it/s]

Processing tickers:  24%|██▍       | 1654/6774 [05:38<17:02,  5.01it/s]

Processing tickers:  24%|██▍       | 1655/6774 [05:39<17:01,  5.01it/s]

Processing tickers:  24%|██▍       | 1656/6774 [05:39<17:02,  5.00it/s]

Processing tickers:  24%|██▍       | 1657/6774 [05:39<17:09,  4.97it/s]

Processing tickers:  24%|██▍       | 1658/6774 [05:39<17:00,  5.01it/s]

Processing tickers:  24%|██▍       | 1659/6774 [05:39<17:01,  5.01it/s]

Processing tickers:  25%|██▍       | 1660/6774 [05:40<17:00,  5.01it/s]

Processing tickers:  25%|██▍       | 1661/6774 [05:40<17:22,  4.91it/s]

Processing tickers:  25%|██▍       | 1662/6774 [05:40<17:15,  4.94it/s]

Processing tickers:  25%|██▍       | 1663/6774 [05:40<17:11,  4.95it/s]

Processing tickers:  25%|██▍       | 1664/6774 [05:40<17:06,  4.98it/s]

Processing tickers:  25%|██▍       | 1665/6774 [05:41<17:05,  4.98it/s]

Processing tickers:  25%|██▍       | 1666/6774 [05:41<17:10,  4.96it/s]

Processing tickers:  25%|██▍       | 1667/6774 [05:41<17:24,  4.89it/s]

Processing tickers:  25%|██▍       | 1668/6774 [05:41<17:14,  4.94it/s]

Processing tickers:  25%|██▍       | 1669/6774 [05:41<17:10,  4.95it/s]

Processing tickers:  25%|██▍       | 1670/6774 [05:42<17:07,  4.97it/s]

Processing tickers:  25%|██▍       | 1671/6774 [05:42<17:01,  5.00it/s]

Processing tickers:  25%|██▍       | 1672/6774 [05:42<17:14,  4.93it/s]

Processing tickers:  25%|██▍       | 1673/6774 [05:42<17:10,  4.95it/s]

Processing tickers:  25%|██▍       | 1674/6774 [05:42<17:08,  4.96it/s]

Processing tickers:  25%|██▍       | 1675/6774 [05:43<17:05,  4.97it/s]

Processing tickers:  25%|██▍       | 1676/6774 [05:43<17:03,  4.98it/s]

Processing tickers:  25%|██▍       | 1677/6774 [05:43<17:20,  4.90it/s]

Processing tickers:  25%|██▍       | 1678/6774 [05:43<17:18,  4.91it/s]

Processing tickers:  25%|██▍       | 1679/6774 [05:43<17:34,  4.83it/s]

Processing tickers:  25%|██▍       | 1680/6774 [05:44<17:21,  4.89it/s]

Processing tickers:  25%|██▍       | 1681/6774 [05:44<17:19,  4.90it/s]

Processing tickers:  25%|██▍       | 1682/6774 [05:44<17:19,  4.90it/s]

Processing tickers:  25%|██▍       | 1683/6774 [05:44<17:19,  4.90it/s]

Processing tickers:  25%|██▍       | 1684/6774 [05:44<17:14,  4.92it/s]

Processing tickers:  25%|██▍       | 1685/6774 [05:45<17:06,  4.96it/s]

Processing tickers:  25%|██▍       | 1686/6774 [05:45<17:13,  4.92it/s]

Processing tickers:  25%|██▍       | 1687/6774 [05:45<17:11,  4.93it/s]

Processing tickers:  25%|██▍       | 1688/6774 [05:45<17:11,  4.93it/s]

Processing tickers:  25%|██▍       | 1689/6774 [05:45<17:05,  4.96it/s]

Processing tickers:  25%|██▍       | 1690/6774 [05:46<16:58,  4.99it/s]

Processing tickers:  25%|██▍       | 1691/6774 [05:46<17:01,  4.97it/s]

Processing tickers:  25%|██▍       | 1692/6774 [05:46<17:20,  4.88it/s]

Processing tickers:  25%|██▍       | 1693/6774 [05:46<17:14,  4.91it/s]

Processing tickers:  25%|██▌       | 1694/6774 [05:46<17:12,  4.92it/s]

Processing tickers:  25%|██▌       | 1695/6774 [05:47<17:03,  4.96it/s]

Processing tickers:  25%|██▌       | 1696/6774 [05:47<16:56,  5.00it/s]

Processing tickers:  25%|██▌       | 1697/6774 [05:47<16:54,  5.01it/s]

Processing tickers:  25%|██▌       | 1698/6774 [05:47<16:53,  5.01it/s]

Processing tickers:  25%|██▌       | 1699/6774 [05:47<16:57,  4.99it/s]

Processing tickers:  25%|██▌       | 1700/6774 [05:48<16:54,  5.00it/s]

Processing tickers:  25%|██▌       | 1701/6774 [05:48<16:51,  5.02it/s]

Processing tickers:  25%|██▌       | 1702/6774 [05:48<16:57,  4.99it/s]

Processing tickers:  25%|██▌       | 1703/6774 [05:48<16:57,  4.98it/s]

Processing tickers:  25%|██▌       | 1704/6774 [05:48<16:58,  4.98it/s]

Processing tickers:  25%|██▌       | 1705/6774 [05:49<16:56,  4.99it/s]

Processing tickers:  25%|██▌       | 1706/6774 [05:49<17:14,  4.90it/s]

Processing tickers:  25%|██▌       | 1707/6774 [05:49<17:04,  4.94it/s]

Processing tickers:  25%|██▌       | 1708/6774 [05:49<17:07,  4.93it/s]

Processing tickers:  25%|██▌       | 1709/6774 [05:49<17:04,  4.94it/s]

Processing tickers:  25%|██▌       | 1710/6774 [05:50<17:45,  4.75it/s]

Processing tickers:  25%|██▌       | 1711/6774 [05:50<17:33,  4.81it/s]

Processing tickers:  25%|██▌       | 1712/6774 [05:50<17:27,  4.83it/s]

Processing tickers:  25%|██▌       | 1713/6774 [05:50<17:13,  4.90it/s]

Processing tickers:  25%|██▌       | 1714/6774 [05:50<17:07,  4.93it/s]

Processing tickers:  25%|██▌       | 1715/6774 [05:51<16:57,  4.97it/s]

Processing tickers:  25%|██▌       | 1716/6774 [05:51<16:53,  4.99it/s]

Processing tickers:  25%|██▌       | 1717/6774 [05:51<17:02,  4.95it/s]

Processing tickers:  25%|██▌       | 1718/6774 [05:51<17:05,  4.93it/s]

Processing tickers:  25%|██▌       | 1719/6774 [05:51<16:57,  4.97it/s]

Processing tickers:  25%|██▌       | 1720/6774 [05:52<16:51,  5.00it/s]

Processing tickers:  25%|██▌       | 1721/6774 [05:52<16:49,  5.00it/s]

Processing tickers:  25%|██▌       | 1722/6774 [05:52<16:46,  5.02it/s]

Processing tickers:  25%|██▌       | 1723/6774 [05:52<17:02,  4.94it/s]

Processing tickers:  25%|██▌       | 1724/6774 [05:52<16:59,  4.95it/s]

Processing tickers:  25%|██▌       | 1725/6774 [05:53<17:06,  4.92it/s]

Processing tickers:  25%|██▌       | 1726/6774 [05:53<17:16,  4.87it/s]

Processing tickers:  25%|██▌       | 1727/6774 [05:53<17:11,  4.89it/s]

Processing tickers:  26%|██▌       | 1728/6774 [05:53<17:07,  4.91it/s]

Processing tickers:  26%|██▌       | 1729/6774 [05:54<16:59,  4.95it/s]

Processing tickers:  26%|██▌       | 1730/6774 [05:54<16:57,  4.96it/s]

Processing tickers:  26%|██▌       | 1731/6774 [05:54<16:52,  4.98it/s]

Processing tickers:  26%|██▌       | 1732/6774 [05:54<16:59,  4.95it/s]

Processing tickers:  26%|██▌       | 1733/6774 [05:54<17:13,  4.88it/s]

Processing tickers:  26%|██▌       | 1734/6774 [05:55<17:13,  4.87it/s]

Processing tickers:  26%|██▌       | 1735/6774 [05:55<17:10,  4.89it/s]

Processing tickers:  26%|██▌       | 1736/6774 [05:55<17:00,  4.93it/s]

Processing tickers:  26%|██▌       | 1737/6774 [05:55<16:58,  4.95it/s]

Processing tickers:  26%|██▌       | 1738/6774 [05:55<16:54,  4.97it/s]

Processing tickers:  26%|██▌       | 1739/6774 [05:56<16:51,  4.98it/s]

Processing tickers:  26%|██▌       | 1740/6774 [05:56<16:58,  4.94it/s]

Processing tickers:  26%|██▌       | 1741/6774 [05:56<17:11,  4.88it/s]

Processing tickers:  26%|██▌       | 1742/6774 [05:56<16:56,  4.95it/s]

Processing tickers:  26%|██▌       | 1743/6774 [05:56<17:06,  4.90it/s]

Processing tickers:  26%|██▌       | 1744/6774 [05:57<17:38,  4.75it/s]

Processing tickers:  26%|██▌       | 1745/6774 [05:57<17:19,  4.84it/s]

Processing tickers:  26%|██▌       | 1746/6774 [05:57<17:23,  4.82it/s]

Processing tickers:  26%|██▌       | 1747/6774 [05:57<17:12,  4.87it/s]

Processing tickers:  26%|██▌       | 1748/6774 [05:57<17:02,  4.92it/s]

Processing tickers:  26%|██▌       | 1749/6774 [05:58<16:53,  4.96it/s]

Processing tickers:  26%|██▌       | 1750/6774 [05:58<16:49,  4.98it/s]

Processing tickers:  26%|██▌       | 1751/6774 [05:58<17:13,  4.86it/s]

Processing tickers:  26%|██▌       | 1752/6774 [05:58<17:03,  4.91it/s]

Processing tickers:  26%|██▌       | 1753/6774 [05:58<16:57,  4.94it/s]

Processing tickers:  26%|██▌       | 1754/6774 [05:59<16:56,  4.94it/s]

Processing tickers:  26%|██▌       | 1755/6774 [05:59<16:54,  4.95it/s]

Processing tickers:  26%|██▌       | 1756/6774 [05:59<17:06,  4.89it/s]

Processing tickers:  26%|██▌       | 1757/6774 [05:59<17:32,  4.77it/s]

Processing tickers:  26%|██▌       | 1758/6774 [05:59<17:36,  4.75it/s]

Processing tickers:  26%|██▌       | 1759/6774 [06:00<17:19,  4.82it/s]

Processing tickers:  26%|██▌       | 1760/6774 [06:00<17:10,  4.86it/s]

Processing tickers:  26%|██▌       | 1761/6774 [06:00<17:03,  4.90it/s]

Processing tickers:  26%|██▌       | 1762/6774 [06:00<17:24,  4.80it/s]

Processing tickers:  26%|██▌       | 1763/6774 [06:00<17:18,  4.83it/s]

Processing tickers:  26%|██▌       | 1764/6774 [06:01<17:35,  4.75it/s]

Processing tickers:  26%|██▌       | 1765/6774 [06:01<17:20,  4.81it/s]

Processing tickers:  26%|██▌       | 1766/6774 [06:01<17:08,  4.87it/s]

Processing tickers:  26%|██▌       | 1767/6774 [06:01<16:56,  4.92it/s]

Processing tickers:  26%|██▌       | 1768/6774 [06:01<16:56,  4.92it/s]

Processing tickers:  26%|██▌       | 1769/6774 [06:02<16:48,  4.96it/s]

Processing tickers:  26%|██▌       | 1770/6774 [06:02<17:04,  4.89it/s]

Processing tickers:  26%|██▌       | 1771/6774 [06:02<17:03,  4.89it/s]

Processing tickers:  26%|██▌       | 1772/6774 [06:02<16:58,  4.91it/s]

Processing tickers:  26%|██▌       | 1773/6774 [06:03<16:55,  4.92it/s]

Processing tickers:  26%|██▌       | 1774/6774 [06:03<16:49,  4.96it/s]

Processing tickers:  26%|██▌       | 1775/6774 [06:03<16:44,  4.98it/s]

Processing tickers:  26%|██▌       | 1776/6774 [06:03<16:46,  4.97it/s]

Processing tickers:  26%|██▌       | 1777/6774 [06:03<16:46,  4.96it/s]

Processing tickers:  26%|██▌       | 1778/6774 [06:04<16:45,  4.97it/s]

Processing tickers:  26%|██▋       | 1779/6774 [06:04<16:41,  4.99it/s]

Processing tickers:  26%|██▋       | 1780/6774 [06:04<16:39,  5.00it/s]

Processing tickers:  26%|██▋       | 1781/6774 [06:04<17:11,  4.84it/s]

Processing tickers:  26%|██▋       | 1782/6774 [06:04<17:21,  4.79it/s]

Processing tickers:  26%|██▋       | 1783/6774 [06:05<17:35,  4.73it/s]

Processing tickers:  26%|██▋       | 1784/6774 [06:05<17:19,  4.80it/s]

Processing tickers:  26%|██▋       | 1785/6774 [06:05<17:19,  4.80it/s]

Processing tickers:  26%|██▋       | 1786/6774 [06:05<17:10,  4.84it/s]

Processing tickers:  26%|██▋       | 1787/6774 [06:05<17:07,  4.85it/s]

Processing tickers:  26%|██▋       | 1788/6774 [06:06<16:57,  4.90it/s]

Processing tickers:  26%|██▋       | 1789/6774 [06:06<16:52,  4.92it/s]

Processing tickers:  26%|██▋       | 1790/6774 [06:06<17:09,  4.84it/s]

Processing tickers:  26%|██▋       | 1791/6774 [06:06<17:29,  4.75it/s]

Processing tickers:  26%|██▋       | 1792/6774 [06:06<17:18,  4.80it/s]

Processing tickers:  26%|██▋       | 1793/6774 [06:07<17:06,  4.85it/s]

Processing tickers:  26%|██▋       | 1794/6774 [06:07<17:02,  4.87it/s]

Processing tickers:  26%|██▋       | 1795/6774 [06:07<16:56,  4.90it/s]

Processing tickers:  27%|██▋       | 1796/6774 [06:07<16:54,  4.91it/s]

Processing tickers:  27%|██▋       | 1797/6774 [06:07<16:51,  4.92it/s]

Processing tickers:  27%|██▋       | 1798/6774 [06:08<16:41,  4.97it/s]

Processing tickers:  27%|██▋       | 1799/6774 [06:08<16:47,  4.94it/s]

Processing tickers:  27%|██▋       | 1800/6774 [06:08<16:45,  4.95it/s]

Processing tickers:  27%|██▋       | 1801/6774 [06:08<16:45,  4.94it/s]

Processing tickers:  27%|██▋       | 1802/6774 [06:08<16:44,  4.95it/s]

Processing tickers:  27%|██▋       | 1803/6774 [06:09<16:43,  4.95it/s]

Processing tickers:  27%|██▋       | 1804/6774 [06:09<16:41,  4.96it/s]

Processing tickers:  27%|██▋       | 1805/6774 [06:09<16:40,  4.97it/s]

Processing tickers:  27%|██▋       | 1806/6774 [06:09<16:40,  4.96it/s]

Processing tickers:  27%|██▋       | 1807/6774 [06:09<16:41,  4.96it/s]

Processing tickers:  27%|██▋       | 1808/6774 [06:10<16:41,  4.96it/s]

Processing tickers:  27%|██▋       | 1809/6774 [06:10<16:34,  4.99it/s]

Processing tickers:  27%|██▋       | 1810/6774 [06:10<17:14,  4.80it/s]

Processing tickers:  27%|██▋       | 1811/6774 [06:10<16:55,  4.89it/s]

Processing tickers:  27%|██▋       | 1812/6774 [06:10<16:45,  4.93it/s]

Processing tickers:  27%|██▋       | 1813/6774 [06:11<16:44,  4.94it/s]

Processing tickers:  27%|██▋       | 1814/6774 [06:11<16:40,  4.96it/s]

Processing tickers:  27%|██▋       | 1815/6774 [06:11<17:10,  4.81it/s]

Processing tickers:  27%|██▋       | 1816/6774 [06:11<17:12,  4.80it/s]

Processing tickers:  27%|██▋       | 1817/6774 [06:11<17:03,  4.84it/s]

Processing tickers:  27%|██▋       | 1818/6774 [06:12<16:50,  4.91it/s]

Processing tickers:  27%|██▋       | 1819/6774 [06:12<16:43,  4.94it/s]

Processing tickers:  27%|██▋       | 1820/6774 [06:12<17:10,  4.81it/s]

Processing tickers:  27%|██▋       | 1821/6774 [06:12<17:01,  4.85it/s]

Processing tickers:  27%|██▋       | 1822/6774 [06:13<16:50,  4.90it/s]

Processing tickers:  27%|██▋       | 1823/6774 [06:13<16:43,  4.93it/s]

Processing tickers:  27%|██▋       | 1824/6774 [06:13<17:08,  4.81it/s]

Processing tickers:  27%|██▋       | 1825/6774 [06:13<16:55,  4.87it/s]

Processing tickers:  27%|██▋       | 1826/6774 [06:13<16:45,  4.92it/s]

Processing tickers:  27%|██▋       | 1827/6774 [06:14<16:38,  4.95it/s]

Processing tickers:  27%|██▋       | 1828/6774 [06:14<17:42,  4.65it/s]

Processing tickers:  27%|██▋       | 1829/6774 [06:14<17:41,  4.66it/s]

Processing tickers:  27%|██▋       | 1830/6774 [06:14<17:27,  4.72it/s]

Processing tickers:  27%|██▋       | 1831/6774 [06:14<17:25,  4.73it/s]

Processing tickers:  27%|██▋       | 1832/6774 [06:15<17:28,  4.72it/s]

Processing tickers:  27%|██▋       | 1833/6774 [06:15<17:04,  4.82it/s]

Processing tickers:  27%|██▋       | 1834/6774 [06:15<17:32,  4.69it/s]

Processing tickers:  27%|██▋       | 1835/6774 [06:15<17:59,  4.58it/s]

Processing tickers:  27%|██▋       | 1836/6774 [06:15<17:33,  4.69it/s]

Processing tickers:  27%|██▋       | 1837/6774 [06:16<17:19,  4.75it/s]

Processing tickers:  27%|██▋       | 1838/6774 [06:16<17:04,  4.82it/s]

Processing tickers:  27%|██▋       | 1839/6774 [06:16<16:55,  4.86it/s]

Processing tickers:  27%|██▋       | 1840/6774 [06:16<16:47,  4.90it/s]

Processing tickers:  27%|██▋       | 1841/6774 [06:16<16:47,  4.90it/s]

Processing tickers:  27%|██▋       | 1842/6774 [06:17<16:44,  4.91it/s]

Processing tickers:  27%|██▋       | 1843/6774 [06:17<16:35,  4.95it/s]

Processing tickers:  27%|██▋       | 1844/6774 [06:17<16:38,  4.94it/s]

Processing tickers:  27%|██▋       | 1845/6774 [06:17<17:22,  4.73it/s]

Processing tickers:  27%|██▋       | 1846/6774 [06:18<17:07,  4.80it/s]

Processing tickers:  27%|██▋       | 1847/6774 [06:18<16:55,  4.85it/s]

Processing tickers:  27%|██▋       | 1848/6774 [06:18<16:46,  4.89it/s]

Processing tickers:  27%|██▋       | 1849/6774 [06:18<16:39,  4.93it/s]

Processing tickers:  27%|██▋       | 1850/6774 [06:18<16:35,  4.95it/s]

Processing tickers:  27%|██▋       | 1851/6774 [06:19<16:32,  4.96it/s]

Processing tickers:  27%|██▋       | 1852/6774 [06:19<16:29,  4.98it/s]

Processing tickers:  27%|██▋       | 1853/6774 [06:19<17:00,  4.82it/s]

Processing tickers:  27%|██▋       | 1854/6774 [06:19<16:50,  4.87it/s]

Processing tickers:  27%|██▋       | 1855/6774 [06:19<16:42,  4.91it/s]

Processing tickers:  27%|██▋       | 1856/6774 [06:20<16:45,  4.89it/s]

Processing tickers:  27%|██▋       | 1857/6774 [06:20<16:36,  4.93it/s]

Processing tickers:  27%|██▋       | 1858/6774 [06:20<16:32,  4.95it/s]

Processing tickers:  27%|██▋       | 1859/6774 [06:20<16:34,  4.94it/s]

Processing tickers:  27%|██▋       | 1860/6774 [06:20<16:31,  4.96it/s]

Processing tickers:  27%|██▋       | 1861/6774 [06:21<16:33,  4.94it/s]

Processing tickers:  27%|██▋       | 1862/6774 [06:21<16:32,  4.95it/s]

Processing tickers:  28%|██▊       | 1863/6774 [06:21<16:55,  4.84it/s]

Processing tickers:  28%|██▊       | 1864/6774 [06:21<16:48,  4.87it/s]

Processing tickers:  28%|██▊       | 1865/6774 [06:21<16:34,  4.94it/s]

Processing tickers:  28%|██▊       | 1866/6774 [06:22<16:28,  4.97it/s]

Processing tickers:  28%|██▊       | 1867/6774 [06:22<16:26,  4.97it/s]

Processing tickers:  28%|██▊       | 1868/6774 [06:22<16:42,  4.89it/s]

Processing tickers:  28%|██▊       | 1869/6774 [06:22<16:35,  4.93it/s]

Processing tickers:  28%|██▊       | 1870/6774 [06:22<16:30,  4.95it/s]

Processing tickers:  28%|██▊       | 1871/6774 [06:23<16:25,  4.97it/s]

Processing tickers:  28%|██▊       | 1872/6774 [06:23<16:37,  4.91it/s]

Processing tickers:  28%|██▊       | 1873/6774 [06:23<16:43,  4.89it/s]

Processing tickers:  28%|██▊       | 1874/6774 [06:23<16:32,  4.93it/s]

Processing tickers:  28%|██▊       | 1875/6774 [06:23<16:30,  4.95it/s]

Processing tickers:  28%|██▊       | 1876/6774 [06:24<16:25,  4.97it/s]

Processing tickers:  28%|██▊       | 1877/6774 [06:24<16:20,  4.99it/s]

Processing tickers:  28%|██▊       | 1878/6774 [06:24<16:18,  5.00it/s]

Processing tickers:  28%|██▊       | 1879/6774 [06:24<16:19,  5.00it/s]

Processing tickers:  28%|██▊       | 1880/6774 [06:24<16:29,  4.95it/s]

Processing tickers:  28%|██▊       | 1881/6774 [06:25<16:25,  4.97it/s]

Processing tickers:  28%|██▊       | 1882/6774 [06:25<16:22,  4.98it/s]

Processing tickers:  28%|██▊       | 1883/6774 [06:25<16:34,  4.92it/s]

Processing tickers:  28%|██▊       | 1884/6774 [06:25<16:31,  4.93it/s]

Processing tickers:  28%|██▊       | 1885/6774 [06:25<17:03,  4.78it/s]

Processing tickers:  28%|██▊       | 1886/6774 [06:26<16:53,  4.82it/s]

Processing tickers:  28%|██▊       | 1887/6774 [06:26<16:41,  4.88it/s]

Processing tickers:  28%|██▊       | 1888/6774 [06:26<17:00,  4.79it/s]

Processing tickers:  28%|██▊       | 1889/6774 [06:26<16:45,  4.86it/s]

Processing tickers:  28%|██▊       | 1890/6774 [06:26<16:41,  4.88it/s]

Processing tickers:  28%|██▊       | 1891/6774 [06:27<16:29,  4.94it/s]

Processing tickers:  28%|██▊       | 1892/6774 [06:27<17:56,  4.54it/s]

Processing tickers:  28%|██▊       | 1893/6774 [06:27<17:25,  4.67it/s]

Processing tickers:  28%|██▊       | 1894/6774 [06:27<17:18,  4.70it/s]

Processing tickers:  28%|██▊       | 1895/6774 [06:28<18:54,  4.30it/s]

Processing tickers:  28%|██▊       | 1896/6774 [06:28<18:25,  4.41it/s]

Processing tickers:  28%|██▊       | 1897/6774 [06:28<17:40,  4.60it/s]

Processing tickers:  28%|██▊       | 1898/6774 [06:28<17:18,  4.70it/s]

Processing tickers:  28%|██▊       | 1899/6774 [06:28<17:01,  4.77it/s]

Processing tickers:  28%|██▊       | 1900/6774 [06:29<16:49,  4.83it/s]

Processing tickers:  28%|██▊       | 1901/6774 [06:29<16:43,  4.86it/s]

Processing tickers:  28%|██▊       | 1902/6774 [06:29<16:34,  4.90it/s]

Processing tickers:  28%|██▊       | 1903/6774 [06:29<16:59,  4.78it/s]

Processing tickers:  28%|██▊       | 1904/6774 [06:30<18:33,  4.37it/s]

Processing tickers:  28%|██▊       | 1905/6774 [06:30<18:06,  4.48it/s]

Processing tickers:  28%|██▊       | 1906/6774 [06:30<17:34,  4.62it/s]

Processing tickers:  28%|██▊       | 1907/6774 [06:30<17:13,  4.71it/s]

Processing tickers:  28%|██▊       | 1908/6774 [06:30<16:59,  4.77it/s]

Processing tickers:  28%|██▊       | 1909/6774 [06:31<17:24,  4.66it/s]

Processing tickers:  28%|██▊       | 1910/6774 [06:31<16:58,  4.78it/s]

Processing tickers:  28%|██▊       | 1911/6774 [06:31<16:52,  4.80it/s]

Processing tickers:  28%|██▊       | 1912/6774 [06:31<16:40,  4.86it/s]

Processing tickers:  28%|██▊       | 1913/6774 [06:31<17:05,  4.74it/s]

Processing tickers:  28%|██▊       | 1914/6774 [06:32<16:45,  4.83it/s]

Processing tickers:  28%|██▊       | 1915/6774 [06:32<16:33,  4.89it/s]

Processing tickers:  28%|██▊       | 1916/6774 [06:32<16:40,  4.86it/s]

Processing tickers:  28%|██▊       | 1917/6774 [06:32<16:33,  4.89it/s]

Processing tickers:  28%|██▊       | 1918/6774 [06:32<17:05,  4.74it/s]

Processing tickers:  28%|██▊       | 1919/6774 [06:33<16:47,  4.82it/s]

Processing tickers:  28%|██▊       | 1920/6774 [06:33<16:40,  4.85it/s]

Processing tickers:  28%|██▊       | 1921/6774 [06:33<16:28,  4.91it/s]

Processing tickers:  28%|██▊       | 1922/6774 [06:33<16:56,  4.78it/s]

Processing tickers:  28%|██▊       | 1923/6774 [06:33<16:49,  4.81it/s]

Processing tickers:  28%|██▊       | 1924/6774 [06:34<16:55,  4.78it/s]

Processing tickers:  28%|██▊       | 1925/6774 [06:34<16:35,  4.87it/s]

Processing tickers:  28%|██▊       | 1926/6774 [06:34<16:34,  4.88it/s]

Processing tickers:  28%|██▊       | 1927/6774 [06:34<17:04,  4.73it/s]

Processing tickers:  28%|██▊       | 1928/6774 [06:34<16:53,  4.78it/s]

Processing tickers:  28%|██▊       | 1929/6774 [06:35<16:38,  4.85it/s]

Processing tickers:  28%|██▊       | 1930/6774 [06:35<16:28,  4.90it/s]

Processing tickers:  29%|██▊       | 1931/6774 [06:35<16:29,  4.89it/s]

Processing tickers:  29%|██▊       | 1932/6774 [06:35<16:48,  4.80it/s]

Processing tickers:  29%|██▊       | 1933/6774 [06:36<16:37,  4.85it/s]

Processing tickers:  29%|██▊       | 1934/6774 [06:36<16:27,  4.90it/s]

Processing tickers:  29%|██▊       | 1935/6774 [06:36<16:24,  4.91it/s]

Processing tickers:  29%|██▊       | 1936/6774 [06:36<16:18,  4.94it/s]

Processing tickers:  29%|██▊       | 1937/6774 [06:36<16:17,  4.95it/s]

Processing tickers:  29%|██▊       | 1938/6774 [06:37<16:34,  4.86it/s]

Processing tickers:  29%|██▊       | 1939/6774 [06:37<16:30,  4.88it/s]

Processing tickers:  29%|██▊       | 1940/6774 [06:37<16:32,  4.87it/s]

Processing tickers:  29%|██▊       | 1941/6774 [06:37<16:18,  4.94it/s]

Processing tickers:  29%|██▊       | 1942/6774 [06:37<16:18,  4.94it/s]

Processing tickers:  29%|██▊       | 1943/6774 [06:38<16:15,  4.95it/s]

Processing tickers:  29%|██▊       | 1944/6774 [06:38<16:18,  4.94it/s]

Processing tickers:  29%|██▊       | 1945/6774 [06:38<16:11,  4.97it/s]

Processing tickers:  29%|██▊       | 1946/6774 [06:38<16:08,  4.99it/s]

Processing tickers:  29%|██▊       | 1947/6774 [06:38<16:04,  5.00it/s]

Processing tickers:  29%|██▉       | 1948/6774 [06:39<16:35,  4.85it/s]

Processing tickers:  29%|██▉       | 1949/6774 [06:39<16:23,  4.91it/s]

Processing tickers:  29%|██▉       | 1950/6774 [06:39<16:22,  4.91it/s]

Processing tickers:  29%|██▉       | 1951/6774 [06:39<16:19,  4.93it/s]

Processing tickers:  29%|██▉       | 1952/6774 [06:39<16:38,  4.83it/s]

Processing tickers:  29%|██▉       | 1953/6774 [06:40<16:29,  4.87it/s]

Processing tickers:  29%|██▉       | 1954/6774 [06:40<16:23,  4.90it/s]

Processing tickers:  29%|██▉       | 1955/6774 [06:40<16:30,  4.86it/s]

Processing tickers:  29%|██▉       | 1956/6774 [06:40<16:15,  4.94it/s]

Processing tickers:  29%|██▉       | 1957/6774 [06:40<16:06,  4.98it/s]

Processing tickers:  29%|██▉       | 1958/6774 [06:41<16:14,  4.94it/s]

Processing tickers:  29%|██▉       | 1959/6774 [06:41<16:08,  4.97it/s]

Processing tickers:  29%|██▉       | 1960/6774 [06:41<16:19,  4.92it/s]

Processing tickers:  29%|██▉       | 1961/6774 [06:41<16:16,  4.93it/s]

Processing tickers:  29%|██▉       | 1962/6774 [06:41<16:31,  4.85it/s]

Processing tickers:  29%|██▉       | 1963/6774 [06:42<16:20,  4.91it/s]

Processing tickers:  29%|██▉       | 1964/6774 [06:42<16:18,  4.91it/s]

Processing tickers:  29%|██▉       | 1965/6774 [06:42<16:26,  4.87it/s]

Processing tickers:  29%|██▉       | 1966/6774 [06:42<16:17,  4.92it/s]

Processing tickers:  29%|██▉       | 1967/6774 [06:42<16:39,  4.81it/s]

Processing tickers:  29%|██▉       | 1968/6774 [06:43<16:46,  4.77it/s]

Processing tickers:  29%|██▉       | 1969/6774 [06:43<16:35,  4.83it/s]

Processing tickers:  29%|██▉       | 1970/6774 [06:43<16:57,  4.72it/s]

Processing tickers:  29%|██▉       | 1971/6774 [06:43<16:39,  4.81it/s]

Processing tickers:  29%|██▉       | 1972/6774 [06:43<16:27,  4.86it/s]

Processing tickers:  29%|██▉       | 1973/6774 [06:44<16:14,  4.92it/s]

Processing tickers:  29%|██▉       | 1974/6774 [06:44<16:07,  4.96it/s]

Processing tickers:  29%|██▉       | 1975/6774 [06:44<16:04,  4.97it/s]

Processing tickers:  29%|██▉       | 1976/6774 [06:44<16:29,  4.85it/s]

Processing tickers:  29%|██▉       | 1977/6774 [06:44<16:32,  4.83it/s]

Processing tickers:  29%|██▉       | 1978/6774 [06:45<16:35,  4.82it/s]

Processing tickers:  29%|██▉       | 1979/6774 [06:45<16:33,  4.82it/s]

Processing tickers:  29%|██▉       | 1980/6774 [06:45<16:16,  4.91it/s]

Processing tickers:  29%|██▉       | 1981/6774 [06:45<16:12,  4.93it/s]

Processing tickers:  29%|██▉       | 1982/6774 [06:46<16:12,  4.93it/s]

Processing tickers:  29%|██▉       | 1983/6774 [06:46<16:10,  4.93it/s]

Processing tickers:  29%|██▉       | 1984/6774 [06:46<16:10,  4.94it/s]

Processing tickers:  29%|██▉       | 1985/6774 [06:46<16:02,  4.97it/s]

Processing tickers:  29%|██▉       | 1986/6774 [06:46<16:00,  4.98it/s]

Processing tickers:  29%|██▉       | 1987/6774 [06:47<15:55,  5.01it/s]

Processing tickers:  29%|██▉       | 1988/6774 [06:47<15:53,  5.02it/s]

Processing tickers:  29%|██▉       | 1989/6774 [06:47<15:57,  5.00it/s]

Processing tickers:  29%|██▉       | 1990/6774 [06:47<16:09,  4.93it/s]

Processing tickers:  29%|██▉       | 1991/6774 [06:47<16:18,  4.89it/s]

Processing tickers:  29%|██▉       | 1992/6774 [06:48<16:14,  4.91it/s]

Processing tickers:  29%|██▉       | 1993/6774 [06:48<16:12,  4.92it/s]

Processing tickers:  29%|██▉       | 1994/6774 [06:48<16:14,  4.90it/s]

Processing tickers:  29%|██▉       | 1995/6774 [06:48<16:04,  4.96it/s]

Processing tickers:  29%|██▉       | 1996/6774 [06:48<16:08,  4.94it/s]

Processing tickers:  29%|██▉       | 1997/6774 [06:49<16:29,  4.83it/s]

Processing tickers:  29%|██▉       | 1998/6774 [06:49<16:19,  4.87it/s]

Processing tickers:  30%|██▉       | 1999/6774 [06:49<17:02,  4.67it/s]

Processing tickers:  30%|██▉       | 2000/6774 [06:49<16:43,  4.76it/s]

Processing tickers:  30%|██▉       | 2001/6774 [06:49<16:32,  4.81it/s]

Processing tickers:  30%|██▉       | 2002/6774 [06:50<17:01,  4.67it/s]

Processing tickers:  30%|██▉       | 2003/6774 [06:50<16:38,  4.78it/s]

Processing tickers:  30%|██▉       | 2004/6774 [06:50<16:30,  4.82it/s]

Processing tickers:  30%|██▉       | 2005/6774 [06:50<16:19,  4.87it/s]

Processing tickers:  30%|██▉       | 2006/6774 [06:50<16:07,  4.93it/s]

Processing tickers:  30%|██▉       | 2007/6774 [06:51<16:11,  4.91it/s]

Processing tickers:  30%|██▉       | 2008/6774 [06:51<16:46,  4.73it/s]

Processing tickers:  30%|██▉       | 2009/6774 [06:51<16:50,  4.72it/s]

Processing tickers:  30%|██▉       | 2010/6774 [06:51<16:30,  4.81it/s]

Processing tickers:  30%|██▉       | 2011/6774 [06:51<16:21,  4.85it/s]

Processing tickers:  30%|██▉       | 2012/6774 [06:52<16:08,  4.92it/s]

Processing tickers:  30%|██▉       | 2013/6774 [06:52<16:01,  4.95it/s]

Processing tickers:  30%|██▉       | 2014/6774 [06:52<15:59,  4.96it/s]

Processing tickers:  30%|██▉       | 2015/6774 [06:52<16:03,  4.94it/s]

Processing tickers:  30%|██▉       | 2016/6774 [06:52<16:05,  4.93it/s]

Processing tickers:  30%|██▉       | 2017/6774 [06:53<15:58,  4.96it/s]

Processing tickers:  30%|██▉       | 2018/6774 [06:53<15:53,  4.99it/s]

Processing tickers:  30%|██▉       | 2019/6774 [06:53<15:53,  4.99it/s]

Processing tickers:  30%|██▉       | 2020/6774 [06:53<15:49,  5.00it/s]

Processing tickers:  30%|██▉       | 2021/6774 [06:53<15:55,  4.97it/s]

Processing tickers:  30%|██▉       | 2022/6774 [06:54<15:53,  4.99it/s]

Processing tickers:  30%|██▉       | 2023/6774 [06:54<16:05,  4.92it/s]

Processing tickers:  30%|██▉       | 2024/6774 [06:54<16:41,  4.74it/s]

Processing tickers:  30%|██▉       | 2025/6774 [06:54<16:30,  4.80it/s]

Processing tickers:  30%|██▉       | 2026/6774 [06:55<16:38,  4.75it/s]

Processing tickers:  30%|██▉       | 2027/6774 [06:55<16:44,  4.73it/s]

Processing tickers:  30%|██▉       | 2028/6774 [06:55<16:29,  4.80it/s]

Processing tickers:  30%|██▉       | 2029/6774 [06:55<16:12,  4.88it/s]

Processing tickers:  30%|██▉       | 2030/6774 [06:55<16:36,  4.76it/s]

Processing tickers:  30%|██▉       | 2031/6774 [06:56<16:23,  4.82it/s]

Processing tickers:  30%|██▉       | 2032/6774 [06:56<16:08,  4.89it/s]

Processing tickers:  30%|███       | 2033/6774 [06:56<16:18,  4.84it/s]

Processing tickers:  30%|███       | 2034/6774 [06:56<16:18,  4.84it/s]

Processing tickers:  30%|███       | 2035/6774 [06:56<16:26,  4.81it/s]

Processing tickers:  30%|███       | 2036/6774 [06:57<16:44,  4.72it/s]

Processing tickers:  30%|███       | 2037/6774 [06:57<16:25,  4.81it/s]

Processing tickers:  30%|███       | 2038/6774 [06:57<16:43,  4.72it/s]

Processing tickers:  30%|███       | 2039/6774 [06:57<16:24,  4.81it/s]

Processing tickers:  30%|███       | 2040/6774 [06:57<16:14,  4.86it/s]

Processing tickers:  30%|███       | 2041/6774 [06:58<16:12,  4.87it/s]

Processing tickers:  30%|███       | 2042/6774 [06:58<16:22,  4.82it/s]

Processing tickers:  30%|███       | 2043/6774 [06:58<16:23,  4.81it/s]

Processing tickers:  30%|███       | 2044/6774 [06:58<16:17,  4.84it/s]

Processing tickers:  30%|███       | 2045/6774 [06:58<16:33,  4.76it/s]

Processing tickers:  30%|███       | 2046/6774 [06:59<17:10,  4.59it/s]

Processing tickers:  30%|███       | 2047/6774 [06:59<16:41,  4.72it/s]

Processing tickers:  30%|███       | 2048/6774 [06:59<16:26,  4.79it/s]

Processing tickers:  30%|███       | 2049/6774 [06:59<16:16,  4.84it/s]

Processing tickers:  30%|███       | 2050/6774 [07:00<16:05,  4.89it/s]

Processing tickers:  30%|███       | 2051/6774 [07:00<16:03,  4.90it/s]

Processing tickers:  30%|███       | 2052/6774 [07:00<15:58,  4.93it/s]

Processing tickers:  30%|███       | 2053/6774 [07:00<16:08,  4.87it/s]

Processing tickers:  30%|███       | 2054/6774 [07:00<16:26,  4.78it/s]

Processing tickers:  30%|███       | 2055/6774 [07:01<16:37,  4.73it/s]

Processing tickers:  30%|███       | 2056/6774 [07:01<16:50,  4.67it/s]

Processing tickers:  30%|███       | 2057/6774 [07:01<16:41,  4.71it/s]

Processing tickers:  30%|███       | 2058/6774 [07:01<16:24,  4.79it/s]

Processing tickers:  30%|███       | 2059/6774 [07:01<16:10,  4.86it/s]

Processing tickers:  30%|███       | 2060/6774 [07:02<16:06,  4.88it/s]

Processing tickers:  30%|███       | 2061/6774 [07:02<15:54,  4.94it/s]

Processing tickers:  30%|███       | 2062/6774 [07:02<15:57,  4.92it/s]

Processing tickers:  30%|███       | 2063/6774 [07:02<15:55,  4.93it/s]

Processing tickers:  30%|███       | 2064/6774 [07:02<16:09,  4.86it/s]

Processing tickers:  30%|███       | 2065/6774 [07:03<16:01,  4.90it/s]

Processing tickers:  30%|███       | 2066/6774 [07:03<16:25,  4.78it/s]

Processing tickers:  31%|███       | 2067/6774 [07:03<16:11,  4.85it/s]

Processing tickers:  31%|███       | 2068/6774 [07:03<16:10,  4.85it/s]

Processing tickers:  31%|███       | 2069/6774 [07:03<16:06,  4.87it/s]

Processing tickers:  31%|███       | 2070/6774 [07:04<16:01,  4.89it/s]

Processing tickers:  31%|███       | 2071/6774 [07:04<15:48,  4.96it/s]

Processing tickers:  31%|███       | 2072/6774 [07:04<15:55,  4.92it/s]

Processing tickers:  31%|███       | 2073/6774 [07:04<15:49,  4.95it/s]

Processing tickers:  31%|███       | 2074/6774 [07:04<15:43,  4.98it/s]

Processing tickers:  31%|███       | 2075/6774 [07:05<15:47,  4.96it/s]

Processing tickers:  31%|███       | 2076/6774 [07:05<15:42,  4.98it/s]

Processing tickers:  31%|███       | 2077/6774 [07:05<15:40,  4.99it/s]

Processing tickers:  31%|███       | 2078/6774 [07:05<15:41,  4.99it/s]

Processing tickers:  31%|███       | 2079/6774 [07:05<15:55,  4.91it/s]

Processing tickers:  31%|███       | 2080/6774 [07:06<15:56,  4.91it/s]

Processing tickers:  31%|███       | 2081/6774 [07:06<16:01,  4.88it/s]

Processing tickers:  31%|███       | 2082/6774 [07:06<15:53,  4.92it/s]

Processing tickers:  31%|███       | 2083/6774 [07:06<15:52,  4.92it/s]

Processing tickers:  31%|███       | 2084/6774 [07:06<15:57,  4.90it/s]

Processing tickers:  31%|███       | 2085/6774 [07:07<15:52,  4.92it/s]

Processing tickers:  31%|███       | 2086/6774 [07:07<15:47,  4.95it/s]

Processing tickers:  31%|███       | 2087/6774 [07:07<15:44,  4.96it/s]

Processing tickers:  31%|███       | 2088/6774 [07:07<15:45,  4.96it/s]

Processing tickers:  31%|███       | 2089/6774 [07:07<15:39,  4.98it/s]

Processing tickers:  31%|███       | 2090/6774 [07:08<15:38,  4.99it/s]

Processing tickers:  31%|███       | 2091/6774 [07:08<15:48,  4.94it/s]

Processing tickers:  31%|███       | 2092/6774 [07:08<16:19,  4.78it/s]

Processing tickers:  31%|███       | 2093/6774 [07:08<16:04,  4.85it/s]

Processing tickers:  31%|███       | 2094/6774 [07:09<16:01,  4.87it/s]

Processing tickers:  31%|███       | 2095/6774 [07:09<15:56,  4.89it/s]

Processing tickers:  31%|███       | 2096/6774 [07:09<15:47,  4.94it/s]

Processing tickers:  31%|███       | 2097/6774 [07:09<16:22,  4.76it/s]

Processing tickers:  31%|███       | 2098/6774 [07:09<16:06,  4.84it/s]

Processing tickers:  31%|███       | 2099/6774 [07:10<16:05,  4.84it/s]

Processing tickers:  31%|███       | 2100/6774 [07:10<16:11,  4.81it/s]

Processing tickers:  31%|███       | 2101/6774 [07:10<15:58,  4.88it/s]

Processing tickers:  31%|███       | 2102/6774 [07:10<16:21,  4.76it/s]

Processing tickers:  31%|███       | 2103/6774 [07:10<16:42,  4.66it/s]

Processing tickers:  31%|███       | 2104/6774 [07:11<16:26,  4.74it/s]

Processing tickers:  31%|███       | 2105/6774 [07:11<16:16,  4.78it/s]

Processing tickers:  31%|███       | 2106/6774 [07:11<16:04,  4.84it/s]

Processing tickers:  31%|███       | 2107/6774 [07:11<16:08,  4.82it/s]

Processing tickers:  31%|███       | 2108/6774 [07:11<16:10,  4.81it/s]

Processing tickers:  31%|███       | 2109/6774 [07:12<16:20,  4.76it/s]

Processing tickers:  31%|███       | 2110/6774 [07:12<16:25,  4.73it/s]

Processing tickers:  31%|███       | 2111/6774 [07:12<16:14,  4.78it/s]

Processing tickers:  31%|███       | 2112/6774 [07:12<16:28,  4.72it/s]

Processing tickers:  31%|███       | 2113/6774 [07:12<16:08,  4.81it/s]

Processing tickers:  31%|███       | 2114/6774 [07:13<16:04,  4.83it/s]

Processing tickers:  31%|███       | 2115/6774 [07:13<15:46,  4.92it/s]

Processing tickers:  31%|███       | 2116/6774 [07:13<15:37,  4.97it/s]

Processing tickers:  31%|███▏      | 2117/6774 [07:13<15:31,  5.00it/s]

Processing tickers:  31%|███▏      | 2118/6774 [07:13<15:32,  4.99it/s]

Processing tickers:  31%|███▏      | 2119/6774 [07:14<15:34,  4.98it/s]

Processing tickers:  31%|███▏      | 2120/6774 [07:14<15:43,  4.93it/s]

Processing tickers:  31%|███▏      | 2121/6774 [07:14<15:44,  4.92it/s]

Processing tickers:  31%|███▏      | 2122/6774 [07:14<15:41,  4.94it/s]

Processing tickers:  31%|███▏      | 2123/6774 [07:14<15:39,  4.95it/s]

Processing tickers:  31%|███▏      | 2124/6774 [07:15<15:32,  4.99it/s]

Processing tickers:  31%|███▏      | 2125/6774 [07:15<15:27,  5.01it/s]

Processing tickers:  31%|███▏      | 2126/6774 [07:15<15:31,  4.99it/s]

Processing tickers:  31%|███▏      | 2127/6774 [07:15<15:46,  4.91it/s]

Processing tickers:  31%|███▏      | 2128/6774 [07:15<15:37,  4.96it/s]

Processing tickers:  31%|███▏      | 2129/6774 [07:16<15:35,  4.96it/s]

Processing tickers:  31%|███▏      | 2130/6774 [07:16<15:49,  4.89it/s]

Processing tickers:  31%|███▏      | 2131/6774 [07:16<15:39,  4.94it/s]

Processing tickers:  31%|███▏      | 2132/6774 [07:16<15:36,  4.96it/s]

Processing tickers:  31%|███▏      | 2133/6774 [07:17<15:33,  4.97it/s]

Processing tickers:  32%|███▏      | 2134/6774 [07:17<15:28,  5.00it/s]

Processing tickers:  32%|███▏      | 2135/6774 [07:17<15:37,  4.95it/s]

Processing tickers:  32%|███▏      | 2136/6774 [07:17<16:11,  4.78it/s]

Processing tickers:  32%|███▏      | 2137/6774 [07:17<15:58,  4.84it/s]

Processing tickers:  32%|███▏      | 2138/6774 [07:18<15:46,  4.90it/s]

Processing tickers:  32%|███▏      | 2139/6774 [07:18<15:39,  4.93it/s]

Processing tickers:  32%|███▏      | 2140/6774 [07:18<15:32,  4.97it/s]

Processing tickers:  32%|███▏      | 2141/6774 [07:18<15:29,  4.98it/s]

Processing tickers:  32%|███▏      | 2142/6774 [07:18<15:38,  4.94it/s]

Processing tickers:  32%|███▏      | 2143/6774 [07:19<15:34,  4.96it/s]

Processing tickers:  32%|███▏      | 2144/6774 [07:19<15:41,  4.92it/s]

Processing tickers:  32%|███▏      | 2145/6774 [07:19<15:34,  4.95it/s]

Processing tickers:  32%|███▏      | 2146/6774 [07:19<15:43,  4.90it/s]

Processing tickers:  32%|███▏      | 2147/6774 [07:19<15:34,  4.95it/s]

Processing tickers:  32%|███▏      | 2148/6774 [07:20<15:33,  4.95it/s]

Processing tickers:  32%|███▏      | 2149/6774 [07:20<15:34,  4.95it/s]

Processing tickers:  32%|███▏      | 2150/6774 [07:20<15:29,  4.97it/s]

Processing tickers:  32%|███▏      | 2151/6774 [07:20<15:54,  4.84it/s]

Processing tickers:  32%|███▏      | 2152/6774 [07:20<16:22,  4.70it/s]

Processing tickers:  32%|███▏      | 2153/6774 [07:21<16:13,  4.75it/s]

Processing tickers:  32%|███▏      | 2154/6774 [07:21<16:02,  4.80it/s]

Processing tickers:  32%|███▏      | 2155/6774 [07:21<16:15,  4.74it/s]

Processing tickers:  32%|███▏      | 2156/6774 [07:21<15:59,  4.81it/s]

Processing tickers:  32%|███▏      | 2157/6774 [07:21<16:18,  4.72it/s]

Processing tickers:  32%|███▏      | 2158/6774 [07:22<15:59,  4.81it/s]

Processing tickers:  32%|███▏      | 2159/6774 [07:22<15:48,  4.87it/s]

Processing tickers:  32%|███▏      | 2160/6774 [07:22<15:42,  4.90it/s]

Processing tickers:  32%|███▏      | 2161/6774 [07:22<15:44,  4.88it/s]

Processing tickers:  32%|███▏      | 2162/6774 [07:22<15:36,  4.93it/s]

Processing tickers:  32%|███▏      | 2163/6774 [07:23<15:30,  4.95it/s]

Processing tickers:  32%|███▏      | 2164/6774 [07:23<15:29,  4.96it/s]

Processing tickers:  32%|███▏      | 2165/6774 [07:23<15:30,  4.95it/s]

Processing tickers:  32%|███▏      | 2166/6774 [07:23<15:27,  4.97it/s]

Processing tickers:  32%|███▏      | 2167/6774 [07:23<15:40,  4.90it/s]

Processing tickers:  32%|███▏      | 2168/6774 [07:24<15:35,  4.92it/s]

Processing tickers:  32%|███▏      | 2169/6774 [07:24<15:31,  4.94it/s]

Processing tickers:  32%|███▏      | 2170/6774 [07:24<15:34,  4.93it/s]

Processing tickers:  32%|███▏      | 2171/6774 [07:24<15:30,  4.95it/s]

Processing tickers:  32%|███▏      | 2172/6774 [07:24<15:25,  4.97it/s]

Processing tickers:  32%|███▏      | 2173/6774 [07:25<15:25,  4.97it/s]

Processing tickers:  32%|███▏      | 2174/6774 [07:25<15:26,  4.96it/s]

Processing tickers:  32%|███▏      | 2175/6774 [07:25<15:24,  4.97it/s]

Processing tickers:  32%|███▏      | 2176/6774 [07:25<15:19,  5.00it/s]

Processing tickers:  32%|███▏      | 2177/6774 [07:25<15:19,  5.00it/s]

Processing tickers:  32%|███▏      | 2178/6774 [07:26<15:19,  5.00it/s]

Processing tickers:  32%|███▏      | 2179/6774 [07:26<15:21,  4.98it/s]

Processing tickers:  32%|███▏      | 2180/6774 [07:26<15:20,  4.99it/s]

Processing tickers:  32%|███▏      | 2181/6774 [07:26<15:20,  4.99it/s]

Processing tickers:  32%|███▏      | 2182/6774 [07:26<15:18,  5.00it/s]

Processing tickers:  32%|███▏      | 2183/6774 [07:27<15:12,  5.03it/s]

Processing tickers:  32%|███▏      | 2184/6774 [07:27<15:12,  5.03it/s]

Processing tickers:  32%|███▏      | 2185/6774 [07:27<15:14,  5.02it/s]

Processing tickers:  32%|███▏      | 2186/6774 [07:27<15:12,  5.03it/s]

Processing tickers:  32%|███▏      | 2187/6774 [07:27<15:48,  4.84it/s]

Processing tickers:  32%|███▏      | 2188/6774 [07:28<15:31,  4.92it/s]

Processing tickers:  32%|███▏      | 2189/6774 [07:28<15:31,  4.92it/s]

Processing tickers:  32%|███▏      | 2190/6774 [07:28<15:23,  4.96it/s]

Processing tickers:  32%|███▏      | 2191/6774 [07:28<15:20,  4.98it/s]

Processing tickers:  32%|███▏      | 2192/6774 [07:28<15:20,  4.98it/s]

Processing tickers:  32%|███▏      | 2193/6774 [07:29<15:18,  4.99it/s]

Processing tickers:  32%|███▏      | 2194/6774 [07:29<15:11,  5.02it/s]

Processing tickers:  32%|███▏      | 2195/6774 [07:29<15:13,  5.01it/s]

Processing tickers:  32%|███▏      | 2196/6774 [07:29<15:15,  5.00it/s]

Processing tickers:  32%|███▏      | 2197/6774 [07:29<15:15,  5.00it/s]

Processing tickers:  32%|███▏      | 2198/6774 [07:30<15:12,  5.01it/s]

Processing tickers:  32%|███▏      | 2199/6774 [07:30<15:16,  4.99it/s]

Processing tickers:  32%|███▏      | 2200/6774 [07:30<15:24,  4.95it/s]

Processing tickers:  32%|███▏      | 2201/6774 [07:30<15:52,  4.80it/s]

Processing tickers:  33%|███▎      | 2202/6774 [07:31<15:50,  4.81it/s]

Processing tickers:  33%|███▎      | 2203/6774 [07:31<15:47,  4.83it/s]

Processing tickers:  33%|███▎      | 2204/6774 [07:31<15:48,  4.82it/s]

Processing tickers:  33%|███▎      | 2205/6774 [07:31<15:56,  4.78it/s]

Processing tickers:  33%|███▎      | 2206/6774 [07:31<15:45,  4.83it/s]

Processing tickers:  33%|███▎      | 2207/6774 [07:32<15:31,  4.90it/s]

Processing tickers:  33%|███▎      | 2208/6774 [07:32<15:35,  4.88it/s]

Processing tickers:  33%|███▎      | 2209/6774 [07:32<15:31,  4.90it/s]

Processing tickers:  33%|███▎      | 2210/6774 [07:32<15:25,  4.93it/s]

Processing tickers:  33%|███▎      | 2211/6774 [07:32<15:16,  4.98it/s]

Processing tickers:  33%|███▎      | 2212/6774 [07:33<15:16,  4.98it/s]

Processing tickers:  33%|███▎      | 2213/6774 [07:33<15:45,  4.82it/s]

Processing tickers:  33%|███▎      | 2214/6774 [07:33<15:56,  4.77it/s]

Processing tickers:  33%|███▎      | 2215/6774 [07:33<15:47,  4.81it/s]

Processing tickers:  33%|███▎      | 2216/6774 [07:33<15:42,  4.83it/s]

Processing tickers:  33%|███▎      | 2217/6774 [07:34<15:28,  4.91it/s]

Processing tickers:  33%|███▎      | 2218/6774 [07:34<15:25,  4.92it/s]

Processing tickers:  33%|███▎      | 2219/6774 [07:34<15:25,  4.92it/s]

Processing tickers:  33%|███▎      | 2220/6774 [07:34<15:27,  4.91it/s]

Processing tickers:  33%|███▎      | 2221/6774 [07:34<15:23,  4.93it/s]

Processing tickers:  33%|███▎      | 2222/6774 [07:35<15:20,  4.95it/s]

Processing tickers:  33%|███▎      | 2223/6774 [07:35<15:12,  4.99it/s]

Processing tickers:  33%|███▎      | 2224/6774 [07:35<15:11,  4.99it/s]

Processing tickers:  33%|███▎      | 2225/6774 [07:35<15:10,  5.00it/s]

Processing tickers:  33%|███▎      | 2226/6774 [07:35<15:46,  4.80it/s]

Processing tickers:  33%|███▎      | 2227/6774 [07:36<15:33,  4.87it/s]

Processing tickers:  33%|███▎      | 2228/6774 [07:36<15:33,  4.87it/s]

Processing tickers:  33%|███▎      | 2229/6774 [07:36<15:31,  4.88it/s]

Processing tickers:  33%|███▎      | 2230/6774 [07:36<15:39,  4.84it/s]

Processing tickers:  33%|███▎      | 2231/6774 [07:36<15:28,  4.89it/s]

Processing tickers:  33%|███▎      | 2232/6774 [07:37<15:31,  4.88it/s]

Processing tickers:  33%|███▎      | 2233/6774 [07:37<15:31,  4.88it/s]

Processing tickers:  33%|███▎      | 2234/6774 [07:37<15:31,  4.88it/s]

Processing tickers:  33%|███▎      | 2235/6774 [07:37<15:24,  4.91it/s]

Processing tickers:  33%|███▎      | 2236/6774 [07:37<15:20,  4.93it/s]

Processing tickers:  33%|███▎      | 2237/6774 [07:38<15:15,  4.96it/s]

Processing tickers:  33%|███▎      | 2238/6774 [07:38<15:12,  4.97it/s]

Processing tickers:  33%|███▎      | 2239/6774 [07:38<15:09,  4.99it/s]

Processing tickers:  33%|███▎      | 2240/6774 [07:38<15:11,  4.97it/s]

Processing tickers:  33%|███▎      | 2241/6774 [07:38<15:50,  4.77it/s]

Processing tickers:  33%|███▎      | 2242/6774 [07:39<15:39,  4.82it/s]

Processing tickers:  33%|███▎      | 2243/6774 [07:39<15:24,  4.90it/s]

Processing tickers:  33%|███▎      | 2244/6774 [07:39<15:15,  4.95it/s]

Processing tickers:  33%|███▎      | 2245/6774 [07:39<15:10,  4.97it/s]

Processing tickers:  33%|███▎      | 2246/6774 [07:39<15:11,  4.97it/s]

Processing tickers:  33%|███▎      | 2247/6774 [07:40<15:21,  4.91it/s]

Processing tickers:  33%|███▎      | 2248/6774 [07:40<15:21,  4.91it/s]

Processing tickers:  33%|███▎      | 2249/6774 [07:40<15:18,  4.93it/s]

Processing tickers:  33%|███▎      | 2250/6774 [07:40<15:16,  4.93it/s]

Processing tickers:  33%|███▎      | 2251/6774 [07:41<15:11,  4.96it/s]

Processing tickers:  33%|███▎      | 2252/6774 [07:41<15:12,  4.95it/s]

Processing tickers:  33%|███▎      | 2253/6774 [07:41<15:09,  4.97it/s]

Processing tickers:  33%|███▎      | 2254/6774 [07:41<15:18,  4.92it/s]

Processing tickers:  33%|███▎      | 2255/6774 [07:41<15:16,  4.93it/s]

Processing tickers:  33%|███▎      | 2256/6774 [07:42<15:12,  4.95it/s]

Processing tickers:  33%|███▎      | 2257/6774 [07:42<15:11,  4.96it/s]

Processing tickers:  33%|███▎      | 2258/6774 [07:42<15:06,  4.98it/s]

Processing tickers:  33%|███▎      | 2259/6774 [07:42<14:59,  5.02it/s]

Processing tickers:  33%|███▎      | 2260/6774 [07:42<14:55,  5.04it/s]

Processing tickers:  33%|███▎      | 2261/6774 [07:43<15:01,  5.00it/s]

Processing tickers:  33%|███▎      | 2262/6774 [07:43<15:03,  4.99it/s]

Processing tickers:  33%|███▎      | 2263/6774 [07:43<15:04,  4.99it/s]

Processing tickers:  33%|███▎      | 2264/6774 [07:43<15:07,  4.97it/s]

Processing tickers:  33%|███▎      | 2265/6774 [07:43<15:06,  4.97it/s]

Processing tickers:  33%|███▎      | 2266/6774 [07:44<15:42,  4.78it/s]

Processing tickers:  33%|███▎      | 2267/6774 [07:44<15:32,  4.83it/s]

Processing tickers:  33%|███▎      | 2268/6774 [07:44<16:06,  4.66it/s]

Processing tickers:  33%|███▎      | 2269/6774 [07:44<15:53,  4.73it/s]

Processing tickers:  34%|███▎      | 2270/6774 [07:44<15:59,  4.70it/s]

Processing tickers:  34%|███▎      | 2271/6774 [07:45<15:41,  4.78it/s]

Processing tickers:  34%|███▎      | 2272/6774 [07:45<15:26,  4.86it/s]

Processing tickers:  34%|███▎      | 2273/6774 [07:45<15:34,  4.82it/s]

Processing tickers:  34%|███▎      | 2274/6774 [07:45<15:38,  4.80it/s]

Processing tickers:  34%|███▎      | 2275/6774 [07:45<15:49,  4.74it/s]

Processing tickers:  34%|███▎      | 2276/6774 [07:46<15:33,  4.82it/s]

Processing tickers:  34%|███▎      | 2277/6774 [07:46<15:23,  4.87it/s]

Processing tickers:  34%|███▎      | 2278/6774 [07:46<15:31,  4.83it/s]

Processing tickers:  34%|███▎      | 2279/6774 [07:46<15:27,  4.84it/s]

Processing tickers:  34%|███▎      | 2280/6774 [07:46<15:18,  4.89it/s]

Processing tickers:  34%|███▎      | 2281/6774 [07:47<15:43,  4.76it/s]

Processing tickers:  34%|███▎      | 2282/6774 [07:47<15:26,  4.85it/s]

Processing tickers:  34%|███▎      | 2283/6774 [07:47<15:49,  4.73it/s]

Processing tickers:  34%|███▎      | 2284/6774 [07:47<15:32,  4.82it/s]

Processing tickers:  34%|███▎      | 2285/6774 [07:48<15:21,  4.87it/s]

Processing tickers:  34%|███▎      | 2286/6774 [07:48<15:08,  4.94it/s]

Processing tickers:  34%|███▍      | 2287/6774 [07:48<15:03,  4.96it/s]

Processing tickers:  34%|███▍      | 2288/6774 [07:48<15:01,  4.97it/s]

Processing tickers:  34%|███▍      | 2289/6774 [07:48<15:10,  4.92it/s]

Processing tickers:  34%|███▍      | 2290/6774 [07:49<15:07,  4.94it/s]

Processing tickers:  34%|███▍      | 2291/6774 [07:49<15:02,  4.97it/s]

Processing tickers:  34%|███▍      | 2292/6774 [07:49<14:56,  5.00it/s]

Processing tickers:  34%|███▍      | 2293/6774 [07:49<15:16,  4.89it/s]

Processing tickers:  34%|███▍      | 2294/6774 [07:49<15:20,  4.87it/s]

Processing tickers:  34%|███▍      | 2295/6774 [07:50<15:53,  4.70it/s]

Processing tickers:  34%|███▍      | 2296/6774 [07:50<15:40,  4.76it/s]

Processing tickers:  34%|███▍      | 2297/6774 [07:50<15:28,  4.82it/s]

Processing tickers:  34%|███▍      | 2298/6774 [07:50<15:45,  4.74it/s]

Processing tickers:  34%|███▍      | 2299/6774 [07:50<15:31,  4.81it/s]

Processing tickers:  34%|███▍      | 2300/6774 [07:51<15:31,  4.80it/s]

Processing tickers:  34%|███▍      | 2301/6774 [07:51<15:16,  4.88it/s]

Processing tickers:  34%|███▍      | 2302/6774 [07:51<15:19,  4.86it/s]

Processing tickers:  34%|███▍      | 2303/6774 [07:51<15:06,  4.93it/s]

Processing tickers:  34%|███▍      | 2304/6774 [07:51<15:01,  4.96it/s]

Processing tickers:  34%|███▍      | 2305/6774 [07:52<15:00,  4.96it/s]

Processing tickers:  34%|███▍      | 2306/6774 [07:52<14:52,  5.01it/s]

Processing tickers:  34%|███▍      | 2307/6774 [07:52<14:55,  4.99it/s]

Processing tickers:  34%|███▍      | 2308/6774 [07:52<14:57,  4.98it/s]

Processing tickers:  34%|███▍      | 2309/6774 [07:52<14:59,  4.97it/s]

Processing tickers:  34%|███▍      | 2310/6774 [07:53<14:57,  4.97it/s]

Processing tickers:  34%|███▍      | 2311/6774 [07:53<14:57,  4.97it/s]

Processing tickers:  34%|███▍      | 2312/6774 [07:53<15:05,  4.93it/s]

Processing tickers:  34%|███▍      | 2313/6774 [07:53<15:00,  4.95it/s]

Processing tickers:  34%|███▍      | 2314/6774 [07:53<14:55,  4.98it/s]

Processing tickers:  34%|███▍      | 2315/6774 [07:54<14:50,  5.01it/s]

Processing tickers:  34%|███▍      | 2316/6774 [07:54<14:50,  5.00it/s]

Processing tickers:  34%|███▍      | 2317/6774 [07:54<15:03,  4.93it/s]

Processing tickers:  34%|███▍      | 2318/6774 [07:54<15:00,  4.95it/s]

Processing tickers:  34%|███▍      | 2319/6774 [07:54<15:34,  4.77it/s]

Processing tickers:  34%|███▍      | 2320/6774 [07:55<15:16,  4.86it/s]

Processing tickers:  34%|███▍      | 2321/6774 [07:55<15:05,  4.92it/s]

Processing tickers:  34%|███▍      | 2322/6774 [07:55<14:56,  4.96it/s]

Processing tickers:  34%|███▍      | 2323/6774 [07:55<14:53,  4.98it/s]

Processing tickers:  34%|███▍      | 2324/6774 [07:55<14:51,  4.99it/s]

Processing tickers:  34%|███▍      | 2325/6774 [07:56<14:48,  5.01it/s]

Processing tickers:  34%|███▍      | 2326/6774 [07:56<15:27,  4.80it/s]

Processing tickers:  34%|███▍      | 2327/6774 [07:56<15:19,  4.83it/s]

Processing tickers:  34%|███▍      | 2328/6774 [07:56<15:12,  4.87it/s]

Processing tickers:  34%|███▍      | 2329/6774 [07:56<15:01,  4.93it/s]

Processing tickers:  34%|███▍      | 2330/6774 [07:57<15:14,  4.86it/s]

Processing tickers:  34%|███▍      | 2331/6774 [07:57<15:03,  4.92it/s]

Processing tickers:  34%|███▍      | 2332/6774 [07:57<14:56,  4.95it/s]

Processing tickers:  34%|███▍      | 2333/6774 [07:57<14:50,  4.98it/s]

Processing tickers:  34%|███▍      | 2334/6774 [07:57<14:44,  5.02it/s]

Processing tickers:  34%|███▍      | 2335/6774 [07:58<14:46,  5.01it/s]

Processing tickers:  34%|███▍      | 2336/6774 [07:58<14:42,  5.03it/s]

Processing tickers:  34%|███▍      | 2337/6774 [07:58<14:46,  5.01it/s]

Processing tickers:  35%|███▍      | 2338/6774 [07:58<14:49,  4.99it/s]

Processing tickers:  35%|███▍      | 2339/6774 [07:58<15:00,  4.92it/s]

Processing tickers:  35%|███▍      | 2340/6774 [07:59<14:58,  4.94it/s]

Processing tickers:  35%|███▍      | 2341/6774 [07:59<15:20,  4.82it/s]

Processing tickers:  35%|███▍      | 2342/6774 [07:59<15:14,  4.85it/s]

Processing tickers:  35%|███▍      | 2343/6774 [07:59<15:12,  4.85it/s]

Processing tickers:  35%|███▍      | 2344/6774 [07:59<15:02,  4.91it/s]

Processing tickers:  35%|███▍      | 2345/6774 [08:00<14:56,  4.94it/s]

Processing tickers:  35%|███▍      | 2346/6774 [08:00<15:09,  4.87it/s]

Processing tickers:  35%|███▍      | 2347/6774 [08:00<15:22,  4.80it/s]

Processing tickers:  35%|███▍      | 2348/6774 [08:00<15:09,  4.86it/s]

Processing tickers:  35%|███▍      | 2349/6774 [08:01<14:59,  4.92it/s]

Processing tickers:  35%|███▍      | 2350/6774 [08:01<14:55,  4.94it/s]

Processing tickers:  35%|███▍      | 2351/6774 [08:01<14:56,  4.93it/s]

Processing tickers:  35%|███▍      | 2352/6774 [08:01<14:59,  4.91it/s]

Processing tickers:  35%|███▍      | 2353/6774 [08:01<14:55,  4.94it/s]

Processing tickers:  35%|███▍      | 2354/6774 [08:02<14:55,  4.94it/s]

Processing tickers:  35%|███▍      | 2355/6774 [08:02<14:51,  4.96it/s]

Processing tickers:  35%|███▍      | 2356/6774 [08:02<14:53,  4.94it/s]

Processing tickers:  35%|███▍      | 2357/6774 [08:02<14:51,  4.95it/s]

Processing tickers:  35%|███▍      | 2358/6774 [08:02<14:40,  5.01it/s]

Processing tickers:  35%|███▍      | 2359/6774 [08:03<14:41,  5.01it/s]

Processing tickers:  35%|███▍      | 2360/6774 [08:03<15:20,  4.79it/s]

Processing tickers:  35%|███▍      | 2361/6774 [08:03<15:10,  4.85it/s]

Processing tickers:  35%|███▍      | 2362/6774 [08:03<15:18,  4.80it/s]

Processing tickers:  35%|███▍      | 2363/6774 [08:03<15:03,  4.88it/s]

Processing tickers:  35%|███▍      | 2364/6774 [08:04<14:56,  4.92it/s]

Processing tickers:  35%|███▍      | 2365/6774 [08:04<14:51,  4.95it/s]

Processing tickers:  35%|███▍      | 2366/6774 [08:04<14:58,  4.91it/s]

Processing tickers:  35%|███▍      | 2367/6774 [08:04<14:55,  4.92it/s]

Processing tickers:  35%|███▍      | 2368/6774 [08:04<14:49,  4.95it/s]

Processing tickers:  35%|███▍      | 2369/6774 [08:05<14:47,  4.96it/s]

Processing tickers:  35%|███▍      | 2370/6774 [08:05<14:47,  4.96it/s]

Processing tickers:  35%|███▌      | 2371/6774 [08:05<14:57,  4.91it/s]

Processing tickers:  35%|███▌      | 2372/6774 [08:05<15:09,  4.84it/s]

Processing tickers:  35%|███▌      | 2373/6774 [08:05<15:03,  4.87it/s]

Processing tickers:  35%|███▌      | 2374/6774 [08:06<15:20,  4.78it/s]

Processing tickers:  35%|███▌      | 2375/6774 [08:06<15:09,  4.84it/s]

Processing tickers:  35%|███▌      | 2376/6774 [08:06<15:01,  4.88it/s]

Processing tickers:  35%|███▌      | 2377/6774 [08:06<14:56,  4.91it/s]

Processing tickers:  35%|███▌      | 2378/6774 [08:06<14:50,  4.94it/s]

Processing tickers:  35%|███▌      | 2379/6774 [08:07<14:49,  4.94it/s]

Processing tickers:  35%|███▌      | 2380/6774 [08:07<14:49,  4.94it/s]

Processing tickers:  35%|███▌      | 2381/6774 [08:07<14:55,  4.90it/s]

Processing tickers:  35%|███▌      | 2382/6774 [08:07<15:00,  4.88it/s]

Processing tickers:  35%|███▌      | 2383/6774 [08:07<14:50,  4.93it/s]

Processing tickers:  35%|███▌      | 2384/6774 [08:08<14:43,  4.97it/s]

Processing tickers:  35%|███▌      | 2385/6774 [08:08<14:42,  4.97it/s]

Processing tickers:  35%|███▌      | 2386/6774 [08:08<14:43,  4.97it/s]

Processing tickers:  35%|███▌      | 2387/6774 [08:08<15:12,  4.81it/s]

Processing tickers:  35%|███▌      | 2388/6774 [08:08<15:00,  4.87it/s]

Processing tickers:  35%|███▌      | 2389/6774 [08:09<14:51,  4.92it/s]

Processing tickers:  35%|███▌      | 2390/6774 [08:09<14:46,  4.95it/s]

Processing tickers:  35%|███▌      | 2391/6774 [08:09<14:49,  4.93it/s]

Processing tickers:  35%|███▌      | 2392/6774 [08:09<14:43,  4.96it/s]

Processing tickers:  35%|███▌      | 2393/6774 [08:09<14:39,  4.98it/s]

Processing tickers:  35%|███▌      | 2394/6774 [08:10<14:38,  4.99it/s]

Processing tickers:  35%|███▌      | 2395/6774 [08:10<14:50,  4.92it/s]

Processing tickers:  35%|███▌      | 2396/6774 [08:10<15:09,  4.82it/s]

Processing tickers:  35%|███▌      | 2397/6774 [08:10<15:27,  4.72it/s]

Processing tickers:  35%|███▌      | 2398/6774 [08:11<15:10,  4.81it/s]

Processing tickers:  35%|███▌      | 2399/6774 [08:11<15:06,  4.83it/s]

Processing tickers:  35%|███▌      | 2400/6774 [08:11<15:16,  4.77it/s]

Processing tickers:  35%|███▌      | 2401/6774 [08:11<15:07,  4.82it/s]

Processing tickers:  35%|███▌      | 2402/6774 [08:11<14:55,  4.88it/s]

Processing tickers:  35%|███▌      | 2403/6774 [08:12<14:50,  4.91it/s]

Processing tickers:  35%|███▌      | 2404/6774 [08:12<14:44,  4.94it/s]

Processing tickers:  36%|███▌      | 2405/6774 [08:12<14:37,  4.98it/s]

Processing tickers:  36%|███▌      | 2406/6774 [08:12<14:36,  4.99it/s]

Processing tickers:  36%|███▌      | 2407/6774 [08:12<14:33,  5.00it/s]

Processing tickers:  36%|███▌      | 2408/6774 [08:13<14:32,  5.01it/s]

Processing tickers:  36%|███▌      | 2409/6774 [08:13<14:29,  5.02it/s]

Processing tickers:  36%|███▌      | 2410/6774 [08:13<14:25,  5.04it/s]

Processing tickers:  36%|███▌      | 2411/6774 [08:13<14:22,  5.06it/s]

Processing tickers:  36%|███▌      | 2412/6774 [08:13<14:21,  5.06it/s]

Processing tickers:  36%|███▌      | 2413/6774 [08:14<14:26,  5.03it/s]

Processing tickers:  36%|███▌      | 2414/6774 [08:14<14:49,  4.90it/s]

Processing tickers:  36%|███▌      | 2415/6774 [08:14<14:43,  4.93it/s]

Processing tickers:  36%|███▌      | 2416/6774 [08:14<14:38,  4.96it/s]

Processing tickers:  36%|███▌      | 2417/6774 [08:14<14:51,  4.89it/s]

Processing tickers:  36%|███▌      | 2418/6774 [08:15<14:51,  4.88it/s]

Processing tickers:  36%|███▌      | 2419/6774 [08:15<14:42,  4.94it/s]

Processing tickers:  36%|███▌      | 2420/6774 [08:15<14:36,  4.97it/s]

Processing tickers:  36%|███▌      | 2421/6774 [08:15<14:33,  4.98it/s]

Processing tickers:  36%|███▌      | 2422/6774 [08:15<14:52,  4.88it/s]

Processing tickers:  36%|███▌      | 2423/6774 [08:16<14:44,  4.92it/s]

Processing tickers:  36%|███▌      | 2424/6774 [08:16<14:42,  4.93it/s]

Processing tickers:  36%|███▌      | 2425/6774 [08:16<15:19,  4.73it/s]

Processing tickers:  36%|███▌      | 2426/6774 [08:16<15:06,  4.80it/s]

Processing tickers:  36%|███▌      | 2427/6774 [08:16<15:06,  4.80it/s]

Processing tickers:  36%|███▌      | 2428/6774 [08:17<14:55,  4.85it/s]

Processing tickers:  36%|███▌      | 2429/6774 [08:17<14:50,  4.88it/s]

Processing tickers:  36%|███▌      | 2430/6774 [08:17<14:54,  4.86it/s]

Processing tickers:  36%|███▌      | 2431/6774 [08:17<14:50,  4.87it/s]

Processing tickers:  36%|███▌      | 2432/6774 [08:17<15:11,  4.76it/s]

Processing tickers:  36%|███▌      | 2433/6774 [08:18<14:58,  4.83it/s]

Processing tickers:  36%|███▌      | 2434/6774 [08:18<14:49,  4.88it/s]

Processing tickers:  36%|███▌      | 2435/6774 [08:18<14:43,  4.91it/s]

Processing tickers:  36%|███▌      | 2436/6774 [08:18<14:35,  4.96it/s]

Processing tickers:  36%|███▌      | 2437/6774 [08:18<14:33,  4.96it/s]

Processing tickers:  36%|███▌      | 2438/6774 [08:19<14:30,  4.98it/s]

Processing tickers:  36%|███▌      | 2439/6774 [08:19<14:26,  5.00it/s]

Processing tickers:  36%|███▌      | 2440/6774 [08:19<14:27,  5.00it/s]

Processing tickers:  36%|███▌      | 2441/6774 [08:19<14:46,  4.89it/s]

Processing tickers:  36%|███▌      | 2442/6774 [08:19<14:41,  4.92it/s]

Processing tickers:  36%|███▌      | 2443/6774 [08:20<14:42,  4.91it/s]

Processing tickers:  36%|███▌      | 2444/6774 [08:20<14:39,  4.92it/s]

Processing tickers:  36%|███▌      | 2445/6774 [08:20<14:33,  4.95it/s]

Processing tickers:  36%|███▌      | 2446/6774 [08:20<14:41,  4.91it/s]

Processing tickers:  36%|███▌      | 2447/6774 [08:20<15:05,  4.78it/s]

Processing tickers:  36%|███▌      | 2448/6774 [08:21<14:53,  4.84it/s]

Processing tickers:  36%|███▌      | 2449/6774 [08:21<14:41,  4.91it/s]

Processing tickers:  36%|███▌      | 2450/6774 [08:21<14:37,  4.93it/s]

Processing tickers:  36%|███▌      | 2451/6774 [08:21<14:34,  4.95it/s]

Processing tickers:  36%|███▌      | 2452/6774 [08:21<14:48,  4.86it/s]

Processing tickers:  36%|███▌      | 2453/6774 [08:22<14:34,  4.94it/s]

Processing tickers:  36%|███▌      | 2454/6774 [08:22<14:35,  4.93it/s]

Processing tickers:  36%|███▌      | 2455/6774 [08:22<14:27,  4.98it/s]

Processing tickers:  36%|███▋      | 2456/6774 [08:22<14:25,  4.99it/s]

Processing tickers:  36%|███▋      | 2457/6774 [08:22<14:23,  5.00it/s]

Processing tickers:  36%|███▋      | 2458/6774 [08:23<14:25,  4.99it/s]

Processing tickers:  36%|███▋      | 2459/6774 [08:23<14:25,  4.98it/s]

Processing tickers:  36%|███▋      | 2460/6774 [08:23<14:43,  4.88it/s]

Processing tickers:  36%|███▋      | 2461/6774 [08:23<14:46,  4.87it/s]

Processing tickers:  36%|███▋      | 2462/6774 [08:24<14:45,  4.87it/s]

Processing tickers:  36%|███▋      | 2463/6774 [08:24<14:37,  4.91it/s]

Processing tickers:  36%|███▋      | 2464/6774 [08:24<14:33,  4.94it/s]

Processing tickers:  36%|███▋      | 2465/6774 [08:24<14:27,  4.96it/s]

Processing tickers:  36%|███▋      | 2466/6774 [08:24<14:34,  4.93it/s]

Processing tickers:  36%|███▋      | 2467/6774 [08:25<14:32,  4.93it/s]

Processing tickers:  36%|███▋      | 2468/6774 [08:25<15:03,  4.77it/s]

Processing tickers:  36%|███▋      | 2469/6774 [08:25<16:06,  4.46it/s]

Processing tickers:  36%|███▋      | 2470/6774 [08:25<15:37,  4.59it/s]

Processing tickers:  36%|███▋      | 2471/6774 [08:25<15:22,  4.67it/s]

Processing tickers:  36%|███▋      | 2472/6774 [08:26<15:26,  4.64it/s]

Processing tickers:  37%|███▋      | 2473/6774 [08:26<15:08,  4.73it/s]

Processing tickers:  37%|███▋      | 2474/6774 [08:26<15:07,  4.74it/s]

Processing tickers:  37%|███▋      | 2475/6774 [08:26<14:57,  4.79it/s]

Processing tickers:  37%|███▋      | 2476/6774 [08:26<14:59,  4.78it/s]

Processing tickers:  37%|███▋      | 2477/6774 [08:27<14:54,  4.81it/s]

Processing tickers:  37%|███▋      | 2478/6774 [08:27<14:42,  4.87it/s]

Processing tickers:  37%|███▋      | 2479/6774 [08:27<15:04,  4.75it/s]

Processing tickers:  37%|███▋      | 2480/6774 [08:27<14:52,  4.81it/s]

Processing tickers:  37%|███▋      | 2481/6774 [08:27<14:47,  4.84it/s]

Processing tickers:  37%|███▋      | 2482/6774 [08:28<14:34,  4.91it/s]

Processing tickers:  37%|███▋      | 2483/6774 [08:28<14:40,  4.88it/s]

Processing tickers:  37%|███▋      | 2484/6774 [08:28<14:30,  4.93it/s]

Processing tickers:  37%|███▋      | 2485/6774 [08:28<14:29,  4.93it/s]

Processing tickers:  37%|███▋      | 2486/6774 [08:29<14:46,  4.84it/s]

Processing tickers:  37%|███▋      | 2487/6774 [08:29<14:34,  4.90it/s]

Processing tickers:  37%|███▋      | 2488/6774 [08:29<14:31,  4.92it/s]

Processing tickers:  37%|███▋      | 2489/6774 [08:29<14:28,  4.93it/s]

Processing tickers:  37%|███▋      | 2490/6774 [08:29<14:26,  4.94it/s]

Processing tickers:  37%|███▋      | 2491/6774 [08:30<14:38,  4.87it/s]

Processing tickers:  37%|███▋      | 2492/6774 [08:30<14:31,  4.91it/s]

Processing tickers:  37%|███▋      | 2493/6774 [08:30<14:24,  4.95it/s]

Processing tickers:  37%|███▋      | 2494/6774 [08:30<14:18,  4.98it/s]

Processing tickers:  37%|███▋      | 2495/6774 [08:30<14:22,  4.96it/s]

Processing tickers:  37%|███▋      | 2496/6774 [08:31<14:24,  4.95it/s]

Processing tickers:  37%|███▋      | 2497/6774 [08:31<14:27,  4.93it/s]

Processing tickers:  37%|███▋      | 2498/6774 [08:31<14:21,  4.97it/s]

Processing tickers:  37%|███▋      | 2499/6774 [08:31<14:23,  4.95it/s]

Processing tickers:  37%|███▋      | 2500/6774 [08:31<14:24,  4.94it/s]

Processing tickers:  37%|███▋      | 2501/6774 [08:32<14:25,  4.94it/s]

Processing tickers:  37%|███▋      | 2502/6774 [08:32<14:30,  4.91it/s]

Processing tickers:  37%|███▋      | 2503/6774 [08:32<14:28,  4.92it/s]

Processing tickers:  37%|███▋      | 2504/6774 [08:32<14:45,  4.82it/s]

Processing tickers:  37%|███▋      | 2505/6774 [08:32<14:37,  4.86it/s]

Processing tickers:  37%|███▋      | 2506/6774 [08:33<14:26,  4.92it/s]

Processing tickers:  37%|███▋      | 2507/6774 [08:33<14:19,  4.96it/s]

Processing tickers:  37%|███▋      | 2508/6774 [08:33<14:44,  4.82it/s]

Processing tickers:  37%|███▋      | 2509/6774 [08:33<14:43,  4.83it/s]

Processing tickers:  37%|███▋      | 2510/6774 [08:33<14:41,  4.84it/s]

Processing tickers:  37%|███▋      | 2511/6774 [08:34<15:18,  4.64it/s]

Processing tickers:  37%|███▋      | 2512/6774 [08:34<14:58,  4.75it/s]

Processing tickers:  37%|███▋      | 2513/6774 [08:34<14:43,  4.82it/s]

Processing tickers:  37%|███▋      | 2514/6774 [08:34<14:32,  4.88it/s]

Processing tickers:  37%|███▋      | 2515/6774 [08:34<14:24,  4.92it/s]

Processing tickers:  37%|███▋      | 2516/6774 [08:35<14:22,  4.94it/s]

Processing tickers:  37%|███▋      | 2517/6774 [08:35<14:43,  4.82it/s]

Processing tickers:  37%|███▋      | 2518/6774 [08:35<14:58,  4.74it/s]

Processing tickers:  37%|███▋      | 2519/6774 [08:35<15:15,  4.65it/s]

Processing tickers:  37%|███▋      | 2520/6774 [08:36<15:32,  4.56it/s]

Processing tickers:  37%|███▋      | 2521/6774 [08:36<15:17,  4.64it/s]

Processing tickers:  37%|███▋      | 2522/6774 [08:36<14:54,  4.75it/s]

Processing tickers:  37%|███▋      | 2523/6774 [08:36<14:42,  4.82it/s]

Processing tickers:  37%|███▋      | 2524/6774 [08:36<14:31,  4.88it/s]

Processing tickers:  37%|███▋      | 2525/6774 [08:37<14:21,  4.93it/s]

Processing tickers:  37%|███▋      | 2526/6774 [08:37<14:19,  4.94it/s]

Processing tickers:  37%|███▋      | 2527/6774 [08:37<14:12,  4.98it/s]

Processing tickers:  37%|███▋      | 2528/6774 [08:37<14:14,  4.97it/s]

Processing tickers:  37%|███▋      | 2529/6774 [08:37<14:35,  4.85it/s]

Processing tickers:  37%|███▋      | 2530/6774 [08:38<14:26,  4.90it/s]

Processing tickers:  37%|███▋      | 2531/6774 [08:38<14:17,  4.95it/s]

Processing tickers:  37%|███▋      | 2532/6774 [08:38<14:17,  4.95it/s]

Processing tickers:  37%|███▋      | 2533/6774 [08:38<14:13,  4.97it/s]

Processing tickers:  37%|███▋      | 2534/6774 [08:38<14:15,  4.96it/s]

Processing tickers:  37%|███▋      | 2535/6774 [08:39<14:08,  4.99it/s]

Processing tickers:  37%|███▋      | 2536/6774 [08:39<14:08,  4.99it/s]

Processing tickers:  37%|███▋      | 2537/6774 [08:39<14:04,  5.02it/s]

Processing tickers:  37%|███▋      | 2538/6774 [08:39<14:06,  5.00it/s]

Processing tickers:  37%|███▋      | 2539/6774 [08:39<14:27,  4.88it/s]

Processing tickers:  37%|███▋      | 2540/6774 [08:40<14:22,  4.91it/s]

Processing tickers:  38%|███▊      | 2541/6774 [08:40<14:19,  4.93it/s]

Processing tickers:  38%|███▊      | 2542/6774 [08:40<14:25,  4.89it/s]

Processing tickers:  38%|███▊      | 2543/6774 [08:40<14:25,  4.89it/s]

Processing tickers:  38%|███▊      | 2544/6774 [08:40<14:51,  4.74it/s]

Processing tickers:  38%|███▊      | 2545/6774 [08:41<14:37,  4.82it/s]

Processing tickers:  38%|███▊      | 2546/6774 [08:41<14:29,  4.86it/s]

Processing tickers:  38%|███▊      | 2547/6774 [08:41<14:34,  4.83it/s]

Processing tickers:  38%|███▊      | 2548/6774 [08:41<14:25,  4.88it/s]

Processing tickers:  38%|███▊      | 2549/6774 [08:41<14:17,  4.93it/s]

Processing tickers:  38%|███▊      | 2550/6774 [08:42<14:11,  4.96it/s]

Processing tickers:  38%|███▊      | 2551/6774 [08:42<14:03,  5.01it/s]

Processing tickers:  38%|███▊      | 2552/6774 [08:42<14:11,  4.96it/s]

Processing tickers:  38%|███▊      | 2553/6774 [08:42<14:06,  4.99it/s]

Processing tickers:  38%|███▊      | 2554/6774 [08:42<14:06,  4.99it/s]

Processing tickers:  38%|███▊      | 2555/6774 [08:43<14:05,  4.99it/s]

Processing tickers:  38%|███▊      | 2556/6774 [08:43<14:32,  4.83it/s]

Processing tickers:  38%|███▊      | 2557/6774 [08:43<14:20,  4.90it/s]

Processing tickers:  38%|███▊      | 2558/6774 [08:43<14:14,  4.94it/s]

Processing tickers:  38%|███▊      | 2559/6774 [08:43<14:36,  4.81it/s]

Processing tickers:  38%|███▊      | 2560/6774 [08:44<14:27,  4.86it/s]

Processing tickers:  38%|███▊      | 2561/6774 [08:44<14:41,  4.78it/s]

Processing tickers:  38%|███▊      | 2562/6774 [08:44<14:52,  4.72it/s]

Processing tickers:  38%|███▊      | 2563/6774 [08:44<14:43,  4.77it/s]

Processing tickers:  38%|███▊      | 2564/6774 [08:44<14:37,  4.80it/s]

Processing tickers:  38%|███▊      | 2565/6774 [08:45<14:34,  4.81it/s]

Processing tickers:  38%|███▊      | 2566/6774 [08:45<14:22,  4.88it/s]

Processing tickers:  38%|███▊      | 2567/6774 [08:45<14:44,  4.76it/s]

Processing tickers:  38%|███▊      | 2568/6774 [08:45<14:35,  4.80it/s]

Processing tickers:  38%|███▊      | 2569/6774 [08:46<14:40,  4.77it/s]

Processing tickers:  38%|███▊      | 2570/6774 [08:46<14:29,  4.83it/s]

Processing tickers:  38%|███▊      | 2571/6774 [08:46<14:20,  4.88it/s]

Processing tickers:  38%|███▊      | 2572/6774 [08:46<14:14,  4.92it/s]

Processing tickers:  38%|███▊      | 2573/6774 [08:46<14:06,  4.97it/s]

Processing tickers:  38%|███▊      | 2574/6774 [08:47<14:02,  4.99it/s]

Processing tickers:  38%|███▊      | 2575/6774 [08:47<14:03,  4.98it/s]

Processing tickers:  38%|███▊      | 2576/6774 [08:47<13:57,  5.01it/s]

Processing tickers:  38%|███▊      | 2577/6774 [08:47<13:59,  5.00it/s]

Processing tickers:  38%|███▊      | 2578/6774 [08:47<13:59,  5.00it/s]

Processing tickers:  38%|███▊      | 2579/6774 [08:48<14:00,  4.99it/s]

Processing tickers:  38%|███▊      | 2580/6774 [08:48<13:58,  5.00it/s]

Processing tickers:  38%|███▊      | 2581/6774 [08:48<14:07,  4.94it/s]

Processing tickers:  38%|███▊      | 2582/6774 [08:48<14:10,  4.93it/s]

Processing tickers:  38%|███▊      | 2583/6774 [08:48<14:10,  4.92it/s]

Processing tickers:  38%|███▊      | 2584/6774 [08:49<14:10,  4.93it/s]

Processing tickers:  38%|███▊      | 2585/6774 [08:49<14:06,  4.95it/s]

Processing tickers:  38%|███▊      | 2586/6774 [08:49<14:04,  4.96it/s]

Processing tickers:  38%|███▊      | 2587/6774 [08:49<14:03,  4.96it/s]

Processing tickers:  38%|███▊      | 2588/6774 [08:49<14:02,  4.97it/s]

Processing tickers:  38%|███▊      | 2589/6774 [08:50<14:01,  4.97it/s]

Processing tickers:  38%|███▊      | 2590/6774 [08:50<14:19,  4.87it/s]

Processing tickers:  38%|███▊      | 2591/6774 [08:50<14:27,  4.82it/s]

Processing tickers:  38%|███▊      | 2592/6774 [08:50<14:14,  4.90it/s]

Processing tickers:  38%|███▊      | 2593/6774 [08:50<14:06,  4.94it/s]

Processing tickers:  38%|███▊      | 2594/6774 [08:51<14:02,  4.96it/s]

Processing tickers:  38%|███▊      | 2595/6774 [08:51<14:00,  4.97it/s]

Processing tickers:  38%|███▊      | 2596/6774 [08:51<14:04,  4.95it/s]

Processing tickers:  38%|███▊      | 2597/6774 [08:51<14:06,  4.94it/s]

Processing tickers:  38%|███▊      | 2598/6774 [08:51<14:01,  4.96it/s]

Processing tickers:  38%|███▊      | 2599/6774 [08:52<13:57,  4.99it/s]

Processing tickers:  38%|███▊      | 2600/6774 [08:52<13:54,  5.00it/s]

Processing tickers:  38%|███▊      | 2601/6774 [08:52<14:14,  4.88it/s]

Processing tickers:  38%|███▊      | 2602/6774 [08:52<14:30,  4.79it/s]

Processing tickers:  38%|███▊      | 2603/6774 [08:52<14:37,  4.76it/s]

Processing tickers:  38%|███▊      | 2604/6774 [08:53<14:27,  4.81it/s]

Processing tickers:  38%|███▊      | 2605/6774 [08:53<14:17,  4.86it/s]

Processing tickers:  38%|███▊      | 2606/6774 [08:53<14:24,  4.82it/s]

Processing tickers:  38%|███▊      | 2607/6774 [08:53<14:16,  4.86it/s]

Processing tickers:  39%|███▊      | 2608/6774 [08:53<14:13,  4.88it/s]

Processing tickers:  39%|███▊      | 2609/6774 [08:54<14:13,  4.88it/s]

Processing tickers:  39%|███▊      | 2610/6774 [08:54<14:09,  4.90it/s]

Processing tickers:  39%|███▊      | 2611/6774 [08:54<14:08,  4.91it/s]

Processing tickers:  39%|███▊      | 2612/6774 [08:54<14:03,  4.94it/s]

Processing tickers:  39%|███▊      | 2613/6774 [08:54<13:54,  4.99it/s]

Processing tickers:  39%|███▊      | 2614/6774 [08:55<13:55,  4.98it/s]

Processing tickers:  39%|███▊      | 2615/6774 [08:55<13:51,  5.00it/s]

Processing tickers:  39%|███▊      | 2616/6774 [08:55<14:25,  4.81it/s]

Processing tickers:  39%|███▊      | 2617/6774 [08:55<14:18,  4.84it/s]

Processing tickers:  39%|███▊      | 2618/6774 [08:55<14:21,  4.82it/s]

Processing tickers:  39%|███▊      | 2619/6774 [08:56<14:10,  4.88it/s]

Processing tickers:  39%|███▊      | 2620/6774 [08:56<14:02,  4.93it/s]

Processing tickers:  39%|███▊      | 2621/6774 [08:56<14:01,  4.94it/s]

Processing tickers:  39%|███▊      | 2622/6774 [08:56<13:59,  4.94it/s]

Processing tickers:  39%|███▊      | 2623/6774 [08:57<14:08,  4.89it/s]

Processing tickers:  39%|███▊      | 2624/6774 [08:57<13:59,  4.94it/s]

Processing tickers:  39%|███▉      | 2625/6774 [08:57<13:57,  4.95it/s]

Processing tickers:  39%|███▉      | 2626/6774 [08:57<13:53,  4.97it/s]

Processing tickers:  39%|███▉      | 2627/6774 [08:57<13:57,  4.95it/s]

Processing tickers:  39%|███▉      | 2628/6774 [08:58<13:51,  4.98it/s]

Processing tickers:  39%|███▉      | 2629/6774 [08:58<13:51,  4.98it/s]

Processing tickers:  39%|███▉      | 2630/6774 [08:58<13:50,  4.99it/s]

Processing tickers:  39%|███▉      | 2631/6774 [08:58<13:57,  4.95it/s]

Processing tickers:  39%|███▉      | 2632/6774 [08:58<13:54,  4.96it/s]

Processing tickers:  39%|███▉      | 2633/6774 [08:59<14:05,  4.89it/s]

Processing tickers:  39%|███▉      | 2634/6774 [08:59<14:02,  4.91it/s]

Processing tickers:  39%|███▉      | 2635/6774 [08:59<13:53,  4.96it/s]

Processing tickers:  39%|███▉      | 2636/6774 [08:59<14:22,  4.80it/s]

Processing tickers:  39%|███▉      | 2637/6774 [08:59<14:17,  4.83it/s]

Processing tickers:  39%|███▉      | 2638/6774 [09:00<14:08,  4.87it/s]

Processing tickers:  39%|███▉      | 2639/6774 [09:00<14:02,  4.91it/s]

Processing tickers:  39%|███▉      | 2640/6774 [09:00<14:04,  4.89it/s]

Processing tickers:  39%|███▉      | 2641/6774 [09:00<14:01,  4.91it/s]

Processing tickers:  39%|███▉      | 2642/6774 [09:00<14:06,  4.88it/s]

Processing tickers:  39%|███▉      | 2643/6774 [09:01<14:00,  4.92it/s]

Processing tickers:  39%|███▉      | 2644/6774 [09:01<13:49,  4.98it/s]

Processing tickers:  39%|███▉      | 2645/6774 [09:01<14:28,  4.75it/s]

Processing tickers:  39%|███▉      | 2646/6774 [09:01<14:16,  4.82it/s]

Processing tickers:  39%|███▉      | 2647/6774 [09:01<14:11,  4.85it/s]

Processing tickers:  39%|███▉      | 2648/6774 [09:02<14:20,  4.79it/s]

Processing tickers:  39%|███▉      | 2649/6774 [09:02<14:23,  4.78it/s]

Processing tickers:  39%|███▉      | 2650/6774 [09:02<14:14,  4.83it/s]

Processing tickers:  39%|███▉      | 2651/6774 [09:02<14:05,  4.88it/s]

Processing tickers:  39%|███▉      | 2652/6774 [09:02<14:15,  4.82it/s]

Processing tickers:  39%|███▉      | 2653/6774 [09:03<14:06,  4.87it/s]

Processing tickers:  39%|███▉      | 2654/6774 [09:03<13:56,  4.93it/s]

Processing tickers:  39%|███▉      | 2655/6774 [09:03<13:50,  4.96it/s]

Processing tickers:  39%|███▉      | 2656/6774 [09:03<14:34,  4.71it/s]

Processing tickers:  39%|███▉      | 2657/6774 [09:03<14:16,  4.81it/s]

Processing tickers:  39%|███▉      | 2658/6774 [09:04<14:03,  4.88it/s]

Processing tickers:  39%|███▉      | 2659/6774 [09:04<14:11,  4.83it/s]

Processing tickers:  39%|███▉      | 2660/6774 [09:04<14:17,  4.80it/s]

Processing tickers:  39%|███▉      | 2661/6774 [09:04<14:08,  4.85it/s]

Processing tickers:  39%|███▉      | 2662/6774 [09:04<13:55,  4.92it/s]

Processing tickers:  39%|███▉      | 2663/6774 [09:05<14:07,  4.85it/s]

Processing tickers:  39%|███▉      | 2664/6774 [09:05<14:04,  4.87it/s]

Processing tickers:  39%|███▉      | 2665/6774 [09:05<13:52,  4.94it/s]

Processing tickers:  39%|███▉      | 2666/6774 [09:05<14:13,  4.81it/s]

Processing tickers:  39%|███▉      | 2667/6774 [09:06<14:05,  4.86it/s]

Processing tickers:  39%|███▉      | 2668/6774 [09:06<13:58,  4.90it/s]

Processing tickers:  39%|███▉      | 2669/6774 [09:06<14:01,  4.88it/s]

Processing tickers:  39%|███▉      | 2670/6774 [09:06<14:16,  4.79it/s]

Processing tickers:  39%|███▉      | 2671/6774 [09:06<14:08,  4.84it/s]

Processing tickers:  39%|███▉      | 2672/6774 [09:07<14:10,  4.83it/s]

Processing tickers:  39%|███▉      | 2673/6774 [09:07<14:02,  4.87it/s]

Processing tickers:  39%|███▉      | 2674/6774 [09:07<13:58,  4.89it/s]

Processing tickers:  39%|███▉      | 2675/6774 [09:07<13:58,  4.89it/s]

Processing tickers:  40%|███▉      | 2676/6774 [09:07<13:57,  4.89it/s]

Processing tickers:  40%|███▉      | 2677/6774 [09:08<13:51,  4.93it/s]

Processing tickers:  40%|███▉      | 2678/6774 [09:08<13:45,  4.96it/s]

Processing tickers:  40%|███▉      | 2679/6774 [09:08<13:53,  4.91it/s]

Processing tickers:  40%|███▉      | 2680/6774 [09:08<13:54,  4.90it/s]

Processing tickers:  40%|███▉      | 2681/6774 [09:08<13:47,  4.95it/s]

Processing tickers:  40%|███▉      | 2682/6774 [09:09<13:45,  4.96it/s]

Processing tickers:  40%|███▉      | 2683/6774 [09:09<13:42,  4.98it/s]

Processing tickers:  40%|███▉      | 2684/6774 [09:09<13:51,  4.92it/s]

Processing tickers:  40%|███▉      | 2685/6774 [09:09<13:55,  4.90it/s]

Processing tickers:  40%|███▉      | 2686/6774 [09:09<13:51,  4.92it/s]

Processing tickers:  40%|███▉      | 2687/6774 [09:10<13:52,  4.91it/s]

Processing tickers:  40%|███▉      | 2688/6774 [09:10<13:46,  4.94it/s]

Processing tickers:  40%|███▉      | 2689/6774 [09:10<13:53,  4.90it/s]

Processing tickers:  40%|███▉      | 2690/6774 [09:10<13:46,  4.94it/s]

Processing tickers:  40%|███▉      | 2691/6774 [09:10<13:42,  4.97it/s]

Processing tickers:  40%|███▉      | 2692/6774 [09:11<13:56,  4.88it/s]

Processing tickers:  40%|███▉      | 2693/6774 [09:11<13:48,  4.93it/s]

Processing tickers:  40%|███▉      | 2694/6774 [09:11<14:10,  4.80it/s]

Processing tickers:  40%|███▉      | 2695/6774 [09:11<13:59,  4.86it/s]

Processing tickers:  40%|███▉      | 2696/6774 [09:11<13:51,  4.91it/s]

Processing tickers:  40%|███▉      | 2697/6774 [09:12<13:53,  4.89it/s]

Processing tickers:  40%|███▉      | 2698/6774 [09:12<13:50,  4.91it/s]

Processing tickers:  40%|███▉      | 2699/6774 [09:12<13:44,  4.94it/s]

Processing tickers:  40%|███▉      | 2700/6774 [09:12<13:38,  4.98it/s]

Processing tickers:  40%|███▉      | 2701/6774 [09:12<13:36,  4.99it/s]

Processing tickers:  40%|███▉      | 2702/6774 [09:13<13:32,  5.01it/s]

Processing tickers:  40%|███▉      | 2703/6774 [09:13<13:38,  4.97it/s]

Processing tickers:  40%|███▉      | 2704/6774 [09:13<13:36,  4.98it/s]

Processing tickers:  40%|███▉      | 2705/6774 [09:13<13:36,  4.99it/s]

Processing tickers:  40%|███▉      | 2706/6774 [09:13<13:37,  4.98it/s]

Processing tickers:  40%|███▉      | 2707/6774 [09:14<13:37,  4.98it/s]

Processing tickers:  40%|███▉      | 2708/6774 [09:14<13:31,  5.01it/s]

Processing tickers:  40%|███▉      | 2709/6774 [09:14<13:33,  5.00it/s]

Processing tickers:  40%|████      | 2710/6774 [09:14<13:33,  5.00it/s]

Processing tickers:  40%|████      | 2711/6774 [09:14<13:32,  5.00it/s]

Processing tickers:  40%|████      | 2712/6774 [09:15<13:36,  4.98it/s]

Processing tickers:  40%|████      | 2713/6774 [09:15<13:27,  5.03it/s]

Processing tickers:  40%|████      | 2714/6774 [09:15<13:34,  4.98it/s]

Processing tickers:  40%|████      | 2715/6774 [09:15<13:31,  5.00it/s]

Processing tickers:  40%|████      | 2716/6774 [09:15<13:32,  4.99it/s]

Processing tickers:  40%|████      | 2717/6774 [09:16<13:41,  4.94it/s]

Processing tickers:  40%|████      | 2718/6774 [09:16<13:38,  4.96it/s]

Processing tickers:  40%|████      | 2719/6774 [09:16<13:45,  4.91it/s]

Processing tickers:  40%|████      | 2720/6774 [09:16<13:35,  4.97it/s]

Processing tickers:  40%|████      | 2721/6774 [09:16<13:31,  4.99it/s]

Processing tickers:  40%|████      | 2722/6774 [09:17<13:39,  4.94it/s]

Processing tickers:  40%|████      | 2723/6774 [09:17<13:33,  4.98it/s]

Processing tickers:  40%|████      | 2724/6774 [09:17<13:30,  5.00it/s]

Processing tickers:  40%|████      | 2725/6774 [09:17<13:42,  4.92it/s]

Processing tickers:  40%|████      | 2726/6774 [09:17<14:04,  4.80it/s]

Processing tickers:  40%|████      | 2727/6774 [09:18<14:24,  4.68it/s]

Processing tickers:  40%|████      | 2728/6774 [09:18<14:41,  4.59it/s]

Processing tickers:  40%|████      | 2729/6774 [09:18<14:17,  4.72it/s]

Processing tickers:  40%|████      | 2730/6774 [09:18<14:03,  4.79it/s]

Processing tickers:  40%|████      | 2731/6774 [09:19<13:49,  4.87it/s]

Processing tickers:  40%|████      | 2732/6774 [09:19<14:20,  4.70it/s]

Processing tickers:  40%|████      | 2733/6774 [09:19<14:45,  4.56it/s]

Processing tickers:  40%|████      | 2734/6774 [09:19<14:22,  4.69it/s]

Processing tickers:  40%|████      | 2735/6774 [09:19<14:22,  4.69it/s]

Processing tickers:  40%|████      | 2736/6774 [09:20<14:09,  4.76it/s]

Processing tickers:  40%|████      | 2737/6774 [09:20<13:53,  4.84it/s]

Processing tickers:  40%|████      | 2738/6774 [09:20<14:03,  4.78it/s]

Processing tickers:  40%|████      | 2739/6774 [09:20<14:02,  4.79it/s]

Processing tickers:  40%|████      | 2740/6774 [09:20<14:07,  4.76it/s]

Processing tickers:  40%|████      | 2741/6774 [09:21<14:01,  4.79it/s]

Processing tickers:  40%|████      | 2742/6774 [09:21<13:53,  4.83it/s]

Processing tickers:  40%|████      | 2743/6774 [09:21<14:04,  4.77it/s]

Processing tickers:  41%|████      | 2744/6774 [09:21<13:51,  4.85it/s]

Processing tickers:  41%|████      | 2745/6774 [09:21<13:53,  4.83it/s]

Processing tickers:  41%|████      | 2746/6774 [09:22<13:44,  4.88it/s]

Processing tickers:  41%|████      | 2747/6774 [09:22<13:41,  4.90it/s]

Processing tickers:  41%|████      | 2748/6774 [09:22<13:30,  4.97it/s]

Processing tickers:  41%|████      | 2749/6774 [09:22<13:27,  4.99it/s]

Processing tickers:  41%|████      | 2750/6774 [09:22<13:27,  4.98it/s]

Processing tickers:  41%|████      | 2751/6774 [09:23<13:25,  4.99it/s]

Processing tickers:  41%|████      | 2752/6774 [09:23<13:22,  5.01it/s]

Processing tickers:  41%|████      | 2753/6774 [09:23<13:34,  4.94it/s]

Processing tickers:  41%|████      | 2754/6774 [09:23<16:28,  4.07it/s]

Processing tickers:  41%|████      | 2755/6774 [09:24<15:29,  4.33it/s]

Processing tickers:  41%|████      | 2756/6774 [09:24<14:53,  4.50it/s]

Processing tickers:  41%|████      | 2757/6774 [09:24<14:29,  4.62it/s]

Processing tickers:  41%|████      | 2758/6774 [09:24<14:21,  4.66it/s]

Processing tickers:  41%|████      | 2759/6774 [09:24<14:01,  4.77it/s]

Processing tickers:  41%|████      | 2760/6774 [09:25<13:52,  4.82it/s]

Processing tickers:  41%|████      | 2761/6774 [09:25<13:42,  4.88it/s]

Processing tickers:  41%|████      | 2762/6774 [09:25<13:39,  4.89it/s]

Processing tickers:  41%|████      | 2763/6774 [09:25<13:35,  4.92it/s]

Processing tickers:  41%|████      | 2764/6774 [09:25<13:26,  4.97it/s]

Processing tickers:  41%|████      | 2765/6774 [09:26<13:26,  4.97it/s]

Processing tickers:  41%|████      | 2766/6774 [09:26<13:22,  5.00it/s]

Processing tickers:  41%|████      | 2767/6774 [09:26<13:25,  4.97it/s]

Processing tickers:  41%|████      | 2768/6774 [09:26<13:45,  4.86it/s]

Processing tickers:  41%|████      | 2769/6774 [09:26<13:45,  4.85it/s]

Processing tickers:  41%|████      | 2770/6774 [09:27<13:34,  4.92it/s]

Processing tickers:  41%|████      | 2771/6774 [09:27<13:30,  4.94it/s]

Processing tickers:  41%|████      | 2772/6774 [09:27<13:27,  4.95it/s]

Processing tickers:  41%|████      | 2773/6774 [09:27<13:54,  4.80it/s]

Processing tickers:  41%|████      | 2774/6774 [09:27<13:47,  4.83it/s]

Processing tickers:  41%|████      | 2775/6774 [09:28<13:39,  4.88it/s]

Processing tickers:  41%|████      | 2776/6774 [09:28<13:29,  4.94it/s]

Processing tickers:  41%|████      | 2777/6774 [09:28<13:25,  4.96it/s]

Processing tickers:  41%|████      | 2778/6774 [09:28<13:20,  4.99it/s]

Processing tickers:  41%|████      | 2779/6774 [09:28<13:19,  5.00it/s]

Processing tickers:  41%|████      | 2780/6774 [09:29<13:15,  5.02it/s]

Processing tickers:  41%|████      | 2781/6774 [09:29<13:18,  5.00it/s]

Processing tickers:  41%|████      | 2782/6774 [09:29<13:20,  4.98it/s]

Processing tickers:  41%|████      | 2783/6774 [09:29<13:21,  4.98it/s]

Processing tickers:  41%|████      | 2784/6774 [09:29<13:27,  4.94it/s]

Processing tickers:  41%|████      | 2785/6774 [09:30<13:18,  5.00it/s]

Processing tickers:  41%|████      | 2786/6774 [09:30<13:27,  4.94it/s]

Processing tickers:  41%|████      | 2787/6774 [09:30<13:25,  4.95it/s]

Processing tickers:  41%|████      | 2788/6774 [09:30<13:22,  4.97it/s]

Processing tickers:  41%|████      | 2789/6774 [09:30<13:21,  4.97it/s]

Processing tickers:  41%|████      | 2790/6774 [09:31<13:19,  4.98it/s]

Processing tickers:  41%|████      | 2791/6774 [09:31<13:19,  4.98it/s]

Processing tickers:  41%|████      | 2792/6774 [09:31<13:28,  4.92it/s]

Processing tickers:  41%|████      | 2793/6774 [09:31<13:20,  4.97it/s]

Processing tickers:  41%|████      | 2794/6774 [09:32<13:36,  4.87it/s]

Processing tickers:  41%|████▏     | 2795/6774 [09:32<13:29,  4.92it/s]

Processing tickers:  41%|████▏     | 2796/6774 [09:32<13:21,  4.96it/s]

Processing tickers:  41%|████▏     | 2797/6774 [09:32<13:17,  4.99it/s]

Processing tickers:  41%|████▏     | 2798/6774 [09:32<13:17,  4.98it/s]

Processing tickers:  41%|████▏     | 2799/6774 [09:33<13:17,  4.98it/s]

Processing tickers:  41%|████▏     | 2800/6774 [09:33<13:22,  4.95it/s]

Processing tickers:  41%|████▏     | 2801/6774 [09:33<13:37,  4.86it/s]

Processing tickers:  41%|████▏     | 2802/6774 [09:33<13:27,  4.92it/s]

Processing tickers:  41%|████▏     | 2803/6774 [09:33<13:19,  4.97it/s]

Processing tickers:  41%|████▏     | 2804/6774 [09:34<13:44,  4.82it/s]

Processing tickers:  41%|████▏     | 2805/6774 [09:34<13:36,  4.86it/s]

Processing tickers:  41%|████▏     | 2806/6774 [09:34<13:30,  4.89it/s]

Processing tickers:  41%|████▏     | 2807/6774 [09:34<13:24,  4.93it/s]

Processing tickers:  41%|████▏     | 2808/6774 [09:34<13:19,  4.96it/s]

Processing tickers:  41%|████▏     | 2809/6774 [09:35<13:27,  4.91it/s]

Processing tickers:  41%|████▏     | 2810/6774 [09:35<13:24,  4.93it/s]

Processing tickers:  41%|████▏     | 2811/6774 [09:35<13:19,  4.96it/s]

Processing tickers:  42%|████▏     | 2812/6774 [09:35<13:15,  4.98it/s]

Processing tickers:  42%|████▏     | 2813/6774 [09:35<13:12,  5.00it/s]

Processing tickers:  42%|████▏     | 2814/6774 [09:36<13:25,  4.92it/s]

Processing tickers:  42%|████▏     | 2815/6774 [09:36<13:40,  4.82it/s]

Processing tickers:  42%|████▏     | 2816/6774 [09:36<14:11,  4.65it/s]

Processing tickers:  42%|████▏     | 2817/6774 [09:36<13:54,  4.74it/s]

Processing tickers:  42%|████▏     | 2818/6774 [09:36<13:41,  4.81it/s]

Processing tickers:  42%|████▏     | 2819/6774 [09:37<13:55,  4.74it/s]

Processing tickers:  42%|████▏     | 2820/6774 [09:37<13:34,  4.86it/s]

Processing tickers:  42%|████▏     | 2821/6774 [09:37<13:21,  4.93it/s]

Processing tickers:  42%|████▏     | 2822/6774 [09:37<13:21,  4.93it/s]

Processing tickers:  42%|████▏     | 2823/6774 [09:37<13:22,  4.92it/s]

Processing tickers:  42%|████▏     | 2824/6774 [09:38<13:14,  4.97it/s]

Processing tickers:  42%|████▏     | 2825/6774 [09:38<13:15,  4.96it/s]

Processing tickers:  42%|████▏     | 2826/6774 [09:38<13:20,  4.93it/s]

Processing tickers:  42%|████▏     | 2827/6774 [09:38<13:14,  4.97it/s]

Processing tickers:  42%|████▏     | 2828/6774 [09:38<13:09,  5.00it/s]

Processing tickers:  42%|████▏     | 2829/6774 [09:39<13:14,  4.97it/s]

Processing tickers:  42%|████▏     | 2830/6774 [09:39<13:11,  4.98it/s]

Processing tickers:  42%|████▏     | 2831/6774 [09:39<13:09,  5.00it/s]

Processing tickers:  42%|████▏     | 2832/6774 [09:39<13:06,  5.01it/s]

Processing tickers:  42%|████▏     | 2833/6774 [09:39<13:06,  5.01it/s]

Processing tickers:  42%|████▏     | 2834/6774 [09:40<13:11,  4.98it/s]

Processing tickers:  42%|████▏     | 2835/6774 [09:40<13:08,  5.00it/s]

Processing tickers:  42%|████▏     | 2836/6774 [09:40<13:07,  5.00it/s]

Processing tickers:  42%|████▏     | 2837/6774 [09:40<13:30,  4.86it/s]

Processing tickers:  42%|████▏     | 2838/6774 [09:40<13:33,  4.84it/s]

Processing tickers:  42%|████▏     | 2839/6774 [09:41<13:24,  4.89it/s]

Processing tickers:  42%|████▏     | 2840/6774 [09:41<13:30,  4.85it/s]

Processing tickers:  42%|████▏     | 2841/6774 [09:41<13:23,  4.89it/s]

Processing tickers:  42%|████▏     | 2842/6774 [09:41<13:47,  4.75it/s]

Processing tickers:  42%|████▏     | 2843/6774 [09:42<13:41,  4.79it/s]

Processing tickers:  42%|████▏     | 2844/6774 [09:42<13:30,  4.85it/s]

Processing tickers:  42%|████▏     | 2845/6774 [09:42<13:27,  4.86it/s]

Processing tickers:  42%|████▏     | 2846/6774 [09:42<13:21,  4.90it/s]

Processing tickers:  42%|████▏     | 2847/6774 [09:42<13:37,  4.81it/s]

Processing tickers:  42%|████▏     | 2848/6774 [09:43<13:50,  4.73it/s]

Processing tickers:  42%|████▏     | 2849/6774 [09:43<13:32,  4.83it/s]

Processing tickers:  42%|████▏     | 2850/6774 [09:43<13:20,  4.90it/s]

Processing tickers:  42%|████▏     | 2851/6774 [09:43<13:15,  4.93it/s]

Processing tickers:  42%|████▏     | 2852/6774 [09:43<13:17,  4.92it/s]

Processing tickers:  42%|████▏     | 2853/6774 [09:44<13:19,  4.91it/s]

Processing tickers:  42%|████▏     | 2854/6774 [09:44<13:14,  4.93it/s]

Processing tickers:  42%|████▏     | 2855/6774 [09:44<13:48,  4.73it/s]

Processing tickers:  42%|████▏     | 2856/6774 [09:44<13:39,  4.78it/s]

Processing tickers:  42%|████▏     | 2857/6774 [09:44<13:38,  4.79it/s]

Processing tickers:  42%|████▏     | 2858/6774 [09:45<13:25,  4.86it/s]

Processing tickers:  42%|████▏     | 2859/6774 [09:45<13:14,  4.92it/s]

Processing tickers:  42%|████▏     | 2860/6774 [09:45<13:26,  4.85it/s]

Processing tickers:  42%|████▏     | 2861/6774 [09:45<13:32,  4.82it/s]

Processing tickers:  42%|████▏     | 2862/6774 [09:45<13:38,  4.78it/s]

Processing tickers:  42%|████▏     | 2863/6774 [09:46<13:27,  4.84it/s]

Processing tickers:  42%|████▏     | 2864/6774 [09:46<13:21,  4.88it/s]

Processing tickers:  42%|████▏     | 2865/6774 [09:46<13:31,  4.82it/s]

Processing tickers:  42%|████▏     | 2866/6774 [09:46<13:31,  4.82it/s]

Processing tickers:  42%|████▏     | 2867/6774 [09:46<13:21,  4.87it/s]

Processing tickers:  42%|████▏     | 2868/6774 [09:47<13:09,  4.95it/s]

Processing tickers:  42%|████▏     | 2869/6774 [09:47<13:07,  4.96it/s]

Processing tickers:  42%|████▏     | 2870/6774 [09:47<13:06,  4.97it/s]

Processing tickers:  42%|████▏     | 2871/6774 [09:47<13:02,  4.98it/s]

Processing tickers:  42%|████▏     | 2872/6774 [09:47<13:01,  4.99it/s]

Processing tickers:  42%|████▏     | 2873/6774 [09:48<12:56,  5.03it/s]

Processing tickers:  42%|████▏     | 2874/6774 [09:48<12:54,  5.03it/s]

Processing tickers:  42%|████▏     | 2875/6774 [09:48<12:52,  5.05it/s]

Processing tickers:  42%|████▏     | 2876/6774 [09:48<12:53,  5.04it/s]

Processing tickers:  42%|████▏     | 2877/6774 [09:48<13:03,  4.97it/s]

Processing tickers:  42%|████▏     | 2878/6774 [09:49<13:08,  4.94it/s]

Processing tickers:  43%|████▎     | 2879/6774 [09:49<13:05,  4.96it/s]

Processing tickers:  43%|████▎     | 2880/6774 [09:49<12:59,  5.00it/s]

Processing tickers:  43%|████▎     | 2881/6774 [09:49<12:53,  5.03it/s]

Processing tickers:  43%|████▎     | 2882/6774 [09:49<12:58,  5.00it/s]

Processing tickers:  43%|████▎     | 2883/6774 [09:50<12:58,  5.00it/s]

Processing tickers:  43%|████▎     | 2884/6774 [09:50<12:54,  5.02it/s]

Processing tickers:  43%|████▎     | 2885/6774 [09:50<12:59,  4.99it/s]

Processing tickers:  43%|████▎     | 2886/6774 [09:50<13:11,  4.91it/s]

Processing tickers:  43%|████▎     | 2887/6774 [09:50<13:03,  4.96it/s]

Processing tickers:  43%|████▎     | 2888/6774 [09:51<12:59,  4.98it/s]

Processing tickers:  43%|████▎     | 2889/6774 [09:51<13:32,  4.78it/s]

Processing tickers:  43%|████▎     | 2890/6774 [09:51<13:17,  4.87it/s]

Processing tickers:  43%|████▎     | 2891/6774 [09:51<13:22,  4.84it/s]

Processing tickers:  43%|████▎     | 2892/6774 [09:51<13:11,  4.90it/s]

Processing tickers:  43%|████▎     | 2893/6774 [09:52<13:17,  4.87it/s]

Processing tickers:  43%|████▎     | 2894/6774 [09:52<13:20,  4.85it/s]

Processing tickers:  43%|████▎     | 2895/6774 [09:52<13:13,  4.89it/s]

Processing tickers:  43%|████▎     | 2896/6774 [09:52<13:09,  4.91it/s]

Processing tickers:  43%|████▎     | 2897/6774 [09:52<13:04,  4.94it/s]

Processing tickers:  43%|████▎     | 2898/6774 [09:53<13:00,  4.96it/s]

Processing tickers:  43%|████▎     | 2899/6774 [09:53<14:21,  4.50it/s]

Processing tickers:  43%|████▎     | 2900/6774 [09:53<14:05,  4.58it/s]

Processing tickers:  43%|████▎     | 2901/6774 [09:53<13:52,  4.65it/s]

Processing tickers:  43%|████▎     | 2902/6774 [09:54<13:36,  4.74it/s]

Processing tickers:  43%|████▎     | 2903/6774 [09:54<13:20,  4.84it/s]

Processing tickers:  43%|████▎     | 2904/6774 [09:54<13:31,  4.77it/s]

Processing tickers:  43%|████▎     | 2905/6774 [09:54<13:31,  4.77it/s]

Processing tickers:  43%|████▎     | 2906/6774 [09:54<13:21,  4.83it/s]

Processing tickers:  43%|████▎     | 2907/6774 [09:55<13:12,  4.88it/s]

Processing tickers:  43%|████▎     | 2908/6774 [09:55<12:59,  4.96it/s]

Processing tickers:  43%|████▎     | 2909/6774 [09:55<14:35,  4.41it/s]

Processing tickers:  43%|████▎     | 2910/6774 [09:55<14:07,  4.56it/s]

Processing tickers:  43%|████▎     | 2911/6774 [09:55<13:43,  4.69it/s]

Processing tickers:  43%|████▎     | 2912/6774 [09:56<13:26,  4.79it/s]

Processing tickers:  43%|████▎     | 2913/6774 [09:56<13:11,  4.88it/s]

Processing tickers:  43%|████▎     | 2914/6774 [09:56<13:05,  4.91it/s]

Processing tickers:  43%|████▎     | 2915/6774 [09:56<13:23,  4.80it/s]

Processing tickers:  43%|████▎     | 2916/6774 [09:57<13:37,  4.72it/s]

Processing tickers:  43%|████▎     | 2917/6774 [09:57<13:26,  4.78it/s]

Processing tickers:  43%|████▎     | 2918/6774 [09:57<13:21,  4.81it/s]

Processing tickers:  43%|████▎     | 2919/6774 [09:57<13:14,  4.85it/s]

Processing tickers:  43%|████▎     | 2920/6774 [09:57<13:25,  4.79it/s]

Processing tickers:  43%|████▎     | 2921/6774 [09:58<13:17,  4.83it/s]

Processing tickers:  43%|████▎     | 2922/6774 [09:58<13:07,  4.89it/s]

Processing tickers:  43%|████▎     | 2923/6774 [09:58<13:03,  4.91it/s]

Processing tickers:  43%|████▎     | 2924/6774 [09:58<13:01,  4.93it/s]

Processing tickers:  43%|████▎     | 2925/6774 [09:58<13:00,  4.93it/s]

Processing tickers:  43%|████▎     | 2926/6774 [09:59<13:00,  4.93it/s]

Processing tickers:  43%|████▎     | 2927/6774 [09:59<13:14,  4.84it/s]

Processing tickers:  43%|████▎     | 2928/6774 [09:59<13:15,  4.83it/s]

Processing tickers:  43%|████▎     | 2929/6774 [09:59<13:11,  4.86it/s]

Processing tickers:  43%|████▎     | 2930/6774 [09:59<14:02,  4.56it/s]

Processing tickers:  43%|████▎     | 2931/6774 [10:00<13:39,  4.69it/s]

Processing tickers:  43%|████▎     | 2932/6774 [10:00<13:28,  4.75it/s]

Processing tickers:  43%|████▎     | 2933/6774 [10:00<13:16,  4.82it/s]

Processing tickers:  43%|████▎     | 2934/6774 [10:00<13:11,  4.85it/s]

Processing tickers:  43%|████▎     | 2935/6774 [10:00<13:10,  4.86it/s]

Processing tickers:  43%|████▎     | 2936/6774 [10:01<13:14,  4.83it/s]

Processing tickers:  43%|████▎     | 2937/6774 [10:01<13:04,  4.89it/s]

Processing tickers:  43%|████▎     | 2938/6774 [10:01<12:57,  4.94it/s]

Processing tickers:  43%|████▎     | 2939/6774 [10:01<12:56,  4.94it/s]

Processing tickers:  43%|████▎     | 2940/6774 [10:01<12:59,  4.92it/s]

Processing tickers:  43%|████▎     | 2941/6774 [10:02<12:57,  4.93it/s]

Processing tickers:  43%|████▎     | 2942/6774 [10:02<12:56,  4.94it/s]

Processing tickers:  43%|████▎     | 2943/6774 [10:02<13:01,  4.90it/s]

Processing tickers:  43%|████▎     | 2944/6774 [10:02<13:05,  4.88it/s]

Processing tickers:  43%|████▎     | 2945/6774 [10:02<12:57,  4.93it/s]

Processing tickers:  43%|████▎     | 2946/6774 [10:03<13:30,  4.72it/s]

Processing tickers:  44%|████▎     | 2947/6774 [10:03<13:16,  4.80it/s]

Processing tickers:  44%|████▎     | 2948/6774 [10:03<13:18,  4.79it/s]

Processing tickers:  44%|████▎     | 2949/6774 [10:03<13:09,  4.84it/s]

Processing tickers:  44%|████▎     | 2950/6774 [10:04<13:14,  4.81it/s]

Processing tickers:  44%|████▎     | 2951/6774 [10:04<13:07,  4.85it/s]

Processing tickers:  44%|████▎     | 2952/6774 [10:04<13:01,  4.89it/s]

Processing tickers:  44%|████▎     | 2953/6774 [10:04<13:04,  4.87it/s]

Processing tickers:  44%|████▎     | 2954/6774 [10:04<13:01,  4.89it/s]

Processing tickers:  44%|████▎     | 2955/6774 [10:05<12:53,  4.94it/s]

Processing tickers:  44%|████▎     | 2956/6774 [10:05<12:50,  4.96it/s]

Processing tickers:  44%|████▎     | 2957/6774 [10:05<12:47,  4.97it/s]

Processing tickers:  44%|████▎     | 2958/6774 [10:05<12:52,  4.94it/s]

Processing tickers:  44%|████▎     | 2959/6774 [10:05<12:50,  4.95it/s]

Processing tickers:  44%|████▎     | 2960/6774 [10:06<13:01,  4.88it/s]

Processing tickers:  44%|████▎     | 2961/6774 [10:06<12:52,  4.94it/s]

Processing tickers:  44%|████▎     | 2962/6774 [10:06<12:51,  4.94it/s]

Processing tickers:  44%|████▎     | 2963/6774 [10:06<12:49,  4.95it/s]

Processing tickers:  44%|████▍     | 2964/6774 [10:06<13:21,  4.75it/s]

Processing tickers:  44%|████▍     | 2965/6774 [10:07<13:10,  4.82it/s]

Processing tickers:  44%|████▍     | 2966/6774 [10:07<13:04,  4.85it/s]

Processing tickers:  44%|████▍     | 2967/6774 [10:07<13:10,  4.82it/s]

Processing tickers:  44%|████▍     | 2968/6774 [10:07<13:16,  4.78it/s]

Processing tickers:  44%|████▍     | 2969/6774 [10:07<13:18,  4.77it/s]

Processing tickers:  44%|████▍     | 2970/6774 [10:08<13:03,  4.85it/s]

Processing tickers:  44%|████▍     | 2971/6774 [10:08<12:57,  4.89it/s]

Processing tickers:  44%|████▍     | 2972/6774 [10:08<13:01,  4.87it/s]

Processing tickers:  44%|████▍     | 2973/6774 [10:08<12:53,  4.91it/s]

Processing tickers:  44%|████▍     | 2974/6774 [10:08<12:48,  4.94it/s]

Processing tickers:  44%|████▍     | 2975/6774 [10:09<12:50,  4.93it/s]

Processing tickers:  44%|████▍     | 2976/6774 [10:09<12:45,  4.96it/s]

Processing tickers:  44%|████▍     | 2977/6774 [10:09<12:48,  4.94it/s]

Processing tickers:  44%|████▍     | 2978/6774 [10:09<12:44,  4.96it/s]

Processing tickers:  44%|████▍     | 2979/6774 [10:09<12:44,  4.97it/s]

Processing tickers:  44%|████▍     | 2980/6774 [10:10<12:43,  4.97it/s]

Processing tickers:  44%|████▍     | 2981/6774 [10:10<12:47,  4.94it/s]

Processing tickers:  44%|████▍     | 2982/6774 [10:10<12:46,  4.95it/s]

Processing tickers:  44%|████▍     | 2983/6774 [10:10<12:50,  4.92it/s]

Processing tickers:  44%|████▍     | 2984/6774 [10:10<13:15,  4.76it/s]

Processing tickers:  44%|████▍     | 2985/6774 [10:11<13:08,  4.81it/s]

Processing tickers:  44%|████▍     | 2986/6774 [10:11<13:03,  4.83it/s]

Processing tickers:  44%|████▍     | 2987/6774 [10:11<13:00,  4.85it/s]

Processing tickers:  44%|████▍     | 2988/6774 [10:11<12:57,  4.87it/s]

Processing tickers:  44%|████▍     | 2989/6774 [10:11<12:47,  4.93it/s]

Processing tickers:  44%|████▍     | 2990/6774 [10:12<12:41,  4.97it/s]

Processing tickers:  44%|████▍     | 2991/6774 [10:12<12:41,  4.97it/s]

Processing tickers:  44%|████▍     | 2992/6774 [10:12<12:55,  4.88it/s]

Processing tickers:  44%|████▍     | 2993/6774 [10:12<12:51,  4.90it/s]

Processing tickers:  44%|████▍     | 2994/6774 [10:13<12:45,  4.94it/s]

Processing tickers:  44%|████▍     | 2995/6774 [10:13<12:38,  4.98it/s]

Processing tickers:  44%|████▍     | 2996/6774 [10:13<12:44,  4.94it/s]

Processing tickers:  44%|████▍     | 2997/6774 [10:13<12:46,  4.93it/s]

Processing tickers:  44%|████▍     | 2998/6774 [10:13<12:40,  4.97it/s]

Processing tickers:  44%|████▍     | 2999/6774 [10:14<12:40,  4.97it/s]

Processing tickers:  44%|████▍     | 3000/6774 [10:14<12:41,  4.95it/s]

Processing tickers:  44%|████▍     | 3001/6774 [10:14<12:39,  4.97it/s]

Processing tickers:  44%|████▍     | 3002/6774 [10:14<12:39,  4.97it/s]

Processing tickers:  44%|████▍     | 3003/6774 [10:14<12:52,  4.88it/s]

Processing tickers:  44%|████▍     | 3004/6774 [10:15<12:45,  4.92it/s]

Processing tickers:  44%|████▍     | 3005/6774 [10:15<12:44,  4.93it/s]

Processing tickers:  44%|████▍     | 3006/6774 [10:15<12:38,  4.97it/s]

Processing tickers:  44%|████▍     | 3007/6774 [10:15<12:39,  4.96it/s]

Processing tickers:  44%|████▍     | 3008/6774 [10:15<12:42,  4.94it/s]

Processing tickers:  44%|████▍     | 3009/6774 [10:16<12:36,  4.98it/s]

Processing tickers:  44%|████▍     | 3010/6774 [10:16<12:31,  5.01it/s]

Processing tickers:  44%|████▍     | 3011/6774 [10:16<12:36,  4.97it/s]

Processing tickers:  44%|████▍     | 3012/6774 [10:16<12:40,  4.95it/s]

Processing tickers:  44%|████▍     | 3013/6774 [10:16<12:34,  4.98it/s]

Processing tickers:  44%|████▍     | 3014/6774 [10:17<12:26,  5.04it/s]

Processing tickers:  45%|████▍     | 3015/6774 [10:17<12:37,  4.96it/s]

Processing tickers:  45%|████▍     | 3016/6774 [10:17<12:36,  4.97it/s]

Processing tickers:  45%|████▍     | 3017/6774 [10:17<12:38,  4.96it/s]

Processing tickers:  45%|████▍     | 3018/6774 [10:17<12:35,  4.97it/s]

Processing tickers:  45%|████▍     | 3019/6774 [10:18<12:30,  5.00it/s]

Processing tickers:  45%|████▍     | 3020/6774 [10:18<12:31,  5.00it/s]

Processing tickers:  45%|████▍     | 3021/6774 [10:18<12:28,  5.02it/s]

Processing tickers:  45%|████▍     | 3022/6774 [10:18<12:26,  5.03it/s]

Processing tickers:  45%|████▍     | 3023/6774 [10:18<12:27,  5.02it/s]

Processing tickers:  45%|████▍     | 3024/6774 [10:19<12:28,  5.01it/s]

Processing tickers:  45%|████▍     | 3025/6774 [10:19<12:23,  5.04it/s]

Processing tickers:  45%|████▍     | 3026/6774 [10:19<12:30,  4.99it/s]

Processing tickers:  45%|████▍     | 3027/6774 [10:19<12:32,  4.98it/s]

Processing tickers:  45%|████▍     | 3028/6774 [10:19<12:29,  5.00it/s]

Processing tickers:  45%|████▍     | 3029/6774 [10:20<12:27,  5.01it/s]

Processing tickers:  45%|████▍     | 3030/6774 [10:20<12:26,  5.02it/s]

Processing tickers:  45%|████▍     | 3031/6774 [10:20<12:25,  5.02it/s]

Processing tickers:  45%|████▍     | 3032/6774 [10:20<12:25,  5.02it/s]

Processing tickers:  45%|████▍     | 3033/6774 [10:20<12:31,  4.98it/s]

Processing tickers:  45%|████▍     | 3034/6774 [10:21<12:30,  4.99it/s]

Processing tickers:  45%|████▍     | 3035/6774 [10:21<12:29,  4.99it/s]

Processing tickers:  45%|████▍     | 3036/6774 [10:21<12:23,  5.03it/s]

Processing tickers:  45%|████▍     | 3037/6774 [10:21<12:52,  4.84it/s]

Processing tickers:  45%|████▍     | 3038/6774 [10:21<12:45,  4.88it/s]

Processing tickers:  45%|████▍     | 3039/6774 [10:22<12:42,  4.90it/s]

Processing tickers:  45%|████▍     | 3040/6774 [10:22<12:35,  4.94it/s]

Processing tickers:  45%|████▍     | 3041/6774 [10:22<12:31,  4.97it/s]

Processing tickers:  45%|████▍     | 3042/6774 [10:22<12:37,  4.93it/s]

Processing tickers:  45%|████▍     | 3043/6774 [10:22<12:34,  4.95it/s]

Processing tickers:  45%|████▍     | 3044/6774 [10:23<12:32,  4.95it/s]

Processing tickers:  45%|████▍     | 3045/6774 [10:23<12:31,  4.96it/s]

Processing tickers:  45%|████▍     | 3046/6774 [10:23<12:51,  4.83it/s]

Processing tickers:  45%|████▍     | 3047/6774 [10:23<12:40,  4.90it/s]

Processing tickers:  45%|████▍     | 3048/6774 [10:23<12:40,  4.90it/s]

Processing tickers:  45%|████▌     | 3049/6774 [10:24<12:36,  4.93it/s]

Processing tickers:  45%|████▌     | 3050/6774 [10:24<12:31,  4.95it/s]

Processing tickers:  45%|████▌     | 3051/6774 [10:24<12:35,  4.93it/s]

Processing tickers:  45%|████▌     | 3052/6774 [10:24<12:27,  4.98it/s]

Processing tickers:  45%|████▌     | 3053/6774 [10:24<12:23,  5.00it/s]

Processing tickers:  45%|████▌     | 3054/6774 [10:25<12:24,  4.99it/s]

Processing tickers:  45%|████▌     | 3055/6774 [10:25<12:25,  4.99it/s]

Processing tickers:  45%|████▌     | 3056/6774 [10:25<12:31,  4.94it/s]

Processing tickers:  45%|████▌     | 3057/6774 [10:25<12:28,  4.97it/s]

Processing tickers:  45%|████▌     | 3058/6774 [10:25<12:26,  4.98it/s]

Processing tickers:  45%|████▌     | 3059/6774 [10:26<12:38,  4.90it/s]

Processing tickers:  45%|████▌     | 3060/6774 [10:26<12:42,  4.87it/s]

Processing tickers:  45%|████▌     | 3061/6774 [10:26<12:38,  4.89it/s]

Processing tickers:  45%|████▌     | 3062/6774 [10:26<12:33,  4.93it/s]

Processing tickers:  45%|████▌     | 3063/6774 [10:26<12:47,  4.83it/s]

Processing tickers:  45%|████▌     | 3064/6774 [10:27<12:36,  4.91it/s]

Processing tickers:  45%|████▌     | 3065/6774 [10:27<12:27,  4.96it/s]

Processing tickers:  45%|████▌     | 3066/6774 [10:27<12:25,  4.97it/s]

Processing tickers:  45%|████▌     | 3067/6774 [10:27<12:22,  4.99it/s]

Processing tickers:  45%|████▌     | 3068/6774 [10:27<12:19,  5.01it/s]

Processing tickers:  45%|████▌     | 3069/6774 [10:28<12:31,  4.93it/s]

Processing tickers:  45%|████▌     | 3070/6774 [10:28<12:27,  4.95it/s]

Processing tickers:  45%|████▌     | 3071/6774 [10:28<12:29,  4.94it/s]

Processing tickers:  45%|████▌     | 3072/6774 [10:28<12:33,  4.91it/s]

Processing tickers:  45%|████▌     | 3073/6774 [10:28<12:38,  4.88it/s]

Processing tickers:  45%|████▌     | 3074/6774 [10:29<12:37,  4.88it/s]

Processing tickers:  45%|████▌     | 3075/6774 [10:29<12:36,  4.89it/s]

Processing tickers:  45%|████▌     | 3076/6774 [10:29<12:40,  4.86it/s]

Processing tickers:  45%|████▌     | 3077/6774 [10:29<12:38,  4.88it/s]

Processing tickers:  45%|████▌     | 3078/6774 [10:29<12:32,  4.91it/s]

Processing tickers:  45%|████▌     | 3079/6774 [10:30<12:47,  4.82it/s]

Processing tickers:  45%|████▌     | 3080/6774 [10:30<12:40,  4.86it/s]

Processing tickers:  45%|████▌     | 3081/6774 [10:30<12:31,  4.92it/s]

Processing tickers:  45%|████▌     | 3082/6774 [10:30<12:25,  4.95it/s]

Processing tickers:  46%|████▌     | 3083/6774 [10:30<12:24,  4.96it/s]

Processing tickers:  46%|████▌     | 3084/6774 [10:31<12:41,  4.85it/s]

Processing tickers:  46%|████▌     | 3085/6774 [10:31<12:57,  4.75it/s]

Processing tickers:  46%|████▌     | 3086/6774 [10:31<13:03,  4.70it/s]

Processing tickers:  46%|████▌     | 3087/6774 [10:31<12:47,  4.80it/s]

Processing tickers:  46%|████▌     | 3088/6774 [10:32<12:35,  4.88it/s]

Processing tickers:  46%|████▌     | 3089/6774 [10:32<12:27,  4.93it/s]

Processing tickers:  46%|████▌     | 3090/6774 [10:32<12:41,  4.84it/s]

Processing tickers:  46%|████▌     | 3091/6774 [10:32<12:37,  4.86it/s]

Processing tickers:  46%|████▌     | 3092/6774 [10:32<12:38,  4.86it/s]

Processing tickers:  46%|████▌     | 3093/6774 [10:33<12:32,  4.89it/s]

Processing tickers:  46%|████▌     | 3094/6774 [10:33<12:27,  4.92it/s]

Processing tickers:  46%|████▌     | 3095/6774 [10:33<12:45,  4.80it/s]

Processing tickers:  46%|████▌     | 3096/6774 [10:33<12:51,  4.77it/s]

Processing tickers:  46%|████▌     | 3097/6774 [10:33<12:43,  4.82it/s]

Processing tickers:  46%|████▌     | 3098/6774 [10:34<12:34,  4.87it/s]

Processing tickers:  46%|████▌     | 3099/6774 [10:34<12:43,  4.81it/s]

Processing tickers:  46%|████▌     | 3100/6774 [10:34<12:50,  4.77it/s]

Processing tickers:  46%|████▌     | 3101/6774 [10:34<13:11,  4.64it/s]

Processing tickers:  46%|████▌     | 3102/6774 [10:34<12:51,  4.76it/s]

Processing tickers:  46%|████▌     | 3103/6774 [10:35<12:45,  4.80it/s]

Processing tickers:  46%|████▌     | 3104/6774 [10:35<12:38,  4.84it/s]

Processing tickers:  46%|████▌     | 3105/6774 [10:35<13:00,  4.70it/s]

Processing tickers:  46%|████▌     | 3106/6774 [10:35<13:02,  4.69it/s]

Processing tickers:  46%|████▌     | 3107/6774 [10:35<12:42,  4.81it/s]

Processing tickers:  46%|████▌     | 3108/6774 [10:36<12:32,  4.87it/s]

Processing tickers:  46%|████▌     | 3109/6774 [10:36<12:25,  4.92it/s]

Processing tickers:  46%|████▌     | 3110/6774 [10:36<12:20,  4.95it/s]

Processing tickers:  46%|████▌     | 3111/6774 [10:36<12:45,  4.78it/s]

Processing tickers:  46%|████▌     | 3112/6774 [10:37<12:38,  4.83it/s]

Processing tickers:  46%|████▌     | 3113/6774 [10:37<12:44,  4.79it/s]

Processing tickers:  46%|████▌     | 3114/6774 [10:37<12:32,  4.86it/s]

Processing tickers:  46%|████▌     | 3115/6774 [10:37<12:26,  4.90it/s]

Processing tickers:  46%|████▌     | 3116/6774 [10:37<12:20,  4.94it/s]

Processing tickers:  46%|████▌     | 3117/6774 [10:38<12:18,  4.95it/s]

Processing tickers:  46%|████▌     | 3118/6774 [10:38<12:18,  4.95it/s]

Processing tickers:  46%|████▌     | 3119/6774 [10:38<12:43,  4.79it/s]

Processing tickers:  46%|████▌     | 3120/6774 [10:38<12:47,  4.76it/s]

Processing tickers:  46%|████▌     | 3121/6774 [10:38<12:47,  4.76it/s]

Processing tickers:  46%|████▌     | 3122/6774 [10:39<12:41,  4.80it/s]

Processing tickers:  46%|████▌     | 3123/6774 [10:39<12:34,  4.84it/s]

Processing tickers:  46%|████▌     | 3124/6774 [10:39<12:53,  4.72it/s]

Processing tickers:  46%|████▌     | 3125/6774 [10:39<12:39,  4.81it/s]

Processing tickers:  46%|████▌     | 3126/6774 [10:39<12:28,  4.87it/s]

Processing tickers:  46%|████▌     | 3127/6774 [10:40<12:21,  4.92it/s]

Processing tickers:  46%|████▌     | 3128/6774 [10:40<12:22,  4.91it/s]

Processing tickers:  46%|████▌     | 3129/6774 [10:40<12:28,  4.87it/s]

Processing tickers:  46%|████▌     | 3130/6774 [10:40<12:22,  4.91it/s]

Processing tickers:  46%|████▌     | 3131/6774 [10:40<12:18,  4.94it/s]

Processing tickers:  46%|████▌     | 3132/6774 [10:41<12:35,  4.82it/s]

Processing tickers:  46%|████▋     | 3133/6774 [10:41<12:21,  4.91it/s]

Processing tickers:  46%|████▋     | 3134/6774 [10:41<12:16,  4.94it/s]

Processing tickers:  46%|████▋     | 3135/6774 [10:41<12:22,  4.90it/s]

Processing tickers:  46%|████▋     | 3136/6774 [10:41<12:14,  4.95it/s]

Processing tickers:  46%|████▋     | 3137/6774 [10:42<12:11,  4.97it/s]

Processing tickers:  46%|████▋     | 3138/6774 [10:42<12:05,  5.01it/s]

Processing tickers:  46%|████▋     | 3139/6774 [10:42<12:09,  4.98it/s]

Processing tickers:  46%|████▋     | 3140/6774 [10:42<12:11,  4.97it/s]

Processing tickers:  46%|████▋     | 3141/6774 [10:42<12:06,  5.00it/s]

Processing tickers:  46%|████▋     | 3142/6774 [10:43<12:05,  5.01it/s]

Processing tickers:  46%|████▋     | 3143/6774 [10:43<12:04,  5.01it/s]

Processing tickers:  46%|████▋     | 3144/6774 [10:43<12:07,  4.99it/s]

Processing tickers:  46%|████▋     | 3145/6774 [10:43<12:16,  4.93it/s]

Processing tickers:  46%|████▋     | 3146/6774 [10:43<12:10,  4.97it/s]

Processing tickers:  46%|████▋     | 3147/6774 [10:44<12:06,  4.99it/s]

Processing tickers:  46%|████▋     | 3148/6774 [10:44<12:07,  4.98it/s]

Processing tickers:  46%|████▋     | 3149/6774 [10:44<12:40,  4.76it/s]

Processing tickers:  47%|████▋     | 3150/6774 [10:44<12:46,  4.73it/s]

Processing tickers:  47%|████▋     | 3151/6774 [10:44<12:36,  4.79it/s]

Processing tickers:  47%|████▋     | 3152/6774 [10:45<12:28,  4.84it/s]

Processing tickers:  47%|████▋     | 3153/6774 [10:45<12:19,  4.90it/s]

Processing tickers:  47%|████▋     | 3154/6774 [10:45<12:26,  4.85it/s]

Processing tickers:  47%|████▋     | 3155/6774 [10:45<12:15,  4.92it/s]

Processing tickers:  47%|████▋     | 3156/6774 [10:45<12:05,  4.98it/s]

Processing tickers:  47%|████▋     | 3157/6774 [10:46<12:28,  4.83it/s]

Processing tickers:  47%|████▋     | 3158/6774 [10:46<12:37,  4.77it/s]

Processing tickers:  47%|████▋     | 3159/6774 [10:46<12:32,  4.80it/s]

Processing tickers:  47%|████▋     | 3160/6774 [10:46<12:26,  4.84it/s]

Processing tickers:  47%|████▋     | 3161/6774 [10:47<12:20,  4.88it/s]

Processing tickers:  47%|████▋     | 3162/6774 [10:47<12:16,  4.91it/s]

Processing tickers:  47%|████▋     | 3163/6774 [10:47<12:10,  4.94it/s]

Processing tickers:  47%|████▋     | 3164/6774 [10:47<12:05,  4.97it/s]

Processing tickers:  47%|████▋     | 3165/6774 [10:47<12:36,  4.77it/s]

Processing tickers:  47%|████▋     | 3166/6774 [10:48<12:27,  4.82it/s]

Processing tickers:  47%|████▋     | 3167/6774 [10:48<12:18,  4.88it/s]

Processing tickers:  47%|████▋     | 3168/6774 [10:48<12:33,  4.79it/s]

Processing tickers:  47%|████▋     | 3169/6774 [10:48<12:22,  4.86it/s]

Processing tickers:  47%|████▋     | 3170/6774 [10:48<12:27,  4.82it/s]

Processing tickers:  47%|████▋     | 3171/6774 [10:49<12:19,  4.87it/s]

Processing tickers:  47%|████▋     | 3172/6774 [10:49<12:10,  4.93it/s]

Processing tickers:  47%|████▋     | 3173/6774 [10:49<12:37,  4.76it/s]

Processing tickers:  47%|████▋     | 3174/6774 [10:49<12:22,  4.85it/s]

Processing tickers:  47%|████▋     | 3175/6774 [10:49<12:12,  4.91it/s]

Processing tickers:  47%|████▋     | 3176/6774 [10:50<12:34,  4.77it/s]

Processing tickers:  47%|████▋     | 3177/6774 [10:50<12:21,  4.85it/s]

Processing tickers:  47%|████▋     | 3178/6774 [10:50<12:13,  4.90it/s]

Processing tickers:  47%|████▋     | 3179/6774 [10:50<12:40,  4.73it/s]

Processing tickers:  47%|████▋     | 3180/6774 [10:50<12:46,  4.69it/s]

Processing tickers:  47%|████▋     | 3181/6774 [10:51<12:31,  4.78it/s]

Processing tickers:  47%|████▋     | 3182/6774 [10:51<12:20,  4.85it/s]

Processing tickers:  47%|████▋     | 3183/6774 [10:51<12:34,  4.76it/s]

Processing tickers:  47%|████▋     | 3184/6774 [10:51<12:20,  4.85it/s]

Processing tickers:  47%|████▋     | 3185/6774 [10:51<12:18,  4.86it/s]

Processing tickers:  47%|████▋     | 3186/6774 [10:52<12:10,  4.91it/s]

Processing tickers:  47%|████▋     | 3187/6774 [10:52<12:02,  4.97it/s]

Processing tickers:  47%|████▋     | 3188/6774 [10:52<12:18,  4.86it/s]

Processing tickers:  47%|████▋     | 3189/6774 [10:52<12:13,  4.89it/s]

Processing tickers:  47%|████▋     | 3190/6774 [10:53<12:29,  4.78it/s]

Processing tickers:  47%|████▋     | 3191/6774 [10:53<12:19,  4.85it/s]

Processing tickers:  47%|████▋     | 3192/6774 [10:53<12:39,  4.72it/s]

Processing tickers:  47%|████▋     | 3193/6774 [10:53<12:27,  4.79it/s]

Processing tickers:  47%|████▋     | 3194/6774 [10:53<12:21,  4.83it/s]

Processing tickers:  47%|████▋     | 3195/6774 [10:54<12:19,  4.84it/s]

Processing tickers:  47%|████▋     | 3196/6774 [10:54<12:11,  4.89it/s]

Processing tickers:  47%|████▋     | 3197/6774 [10:54<12:09,  4.90it/s]

Processing tickers:  47%|████▋     | 3198/6774 [10:54<12:09,  4.90it/s]

Processing tickers:  47%|████▋     | 3199/6774 [10:54<12:01,  4.96it/s]

Processing tickers:  47%|████▋     | 3200/6774 [10:55<11:56,  4.99it/s]

Processing tickers:  47%|████▋     | 3201/6774 [10:55<11:56,  4.99it/s]

Processing tickers:  47%|████▋     | 3202/6774 [10:55<12:03,  4.94it/s]

Processing tickers:  47%|████▋     | 3203/6774 [10:55<12:06,  4.91it/s]

Processing tickers:  47%|████▋     | 3204/6774 [10:55<12:03,  4.94it/s]

Processing tickers:  47%|████▋     | 3205/6774 [10:56<11:57,  4.97it/s]

Processing tickers:  47%|████▋     | 3206/6774 [10:56<12:13,  4.86it/s]

Processing tickers:  47%|████▋     | 3207/6774 [10:56<12:23,  4.80it/s]

Processing tickers:  47%|████▋     | 3208/6774 [10:56<12:21,  4.81it/s]

Processing tickers:  47%|████▋     | 3209/6774 [10:56<12:21,  4.81it/s]

Processing tickers:  47%|████▋     | 3210/6774 [10:57<12:13,  4.86it/s]

Processing tickers:  47%|████▋     | 3211/6774 [10:57<12:06,  4.91it/s]

Processing tickers:  47%|████▋     | 3212/6774 [10:57<12:07,  4.89it/s]

Processing tickers:  47%|████▋     | 3213/6774 [10:57<12:03,  4.92it/s]

Processing tickers:  47%|████▋     | 3214/6774 [10:57<12:04,  4.92it/s]

Processing tickers:  47%|████▋     | 3215/6774 [10:58<12:02,  4.93it/s]

Processing tickers:  47%|████▋     | 3216/6774 [10:58<12:05,  4.91it/s]

Processing tickers:  47%|████▋     | 3217/6774 [10:58<11:58,  4.95it/s]

Processing tickers:  48%|████▊     | 3218/6774 [10:58<11:58,  4.95it/s]

Processing tickers:  48%|████▊     | 3219/6774 [10:58<12:01,  4.93it/s]

Processing tickers:  48%|████▊     | 3220/6774 [10:59<12:03,  4.91it/s]

Processing tickers:  48%|████▊     | 3221/6774 [10:59<12:05,  4.90it/s]

Processing tickers:  48%|████▊     | 3222/6774 [10:59<12:01,  4.92it/s]

Processing tickers:  48%|████▊     | 3223/6774 [10:59<11:58,  4.94it/s]

Processing tickers:  48%|████▊     | 3224/6774 [10:59<12:03,  4.91it/s]

Processing tickers:  48%|████▊     | 3225/6774 [11:00<12:02,  4.91it/s]

Processing tickers:  48%|████▊     | 3226/6774 [11:00<12:20,  4.79it/s]

Processing tickers:  48%|████▊     | 3227/6774 [11:00<12:18,  4.80it/s]

Processing tickers:  48%|████▊     | 3228/6774 [11:00<12:16,  4.81it/s]

Processing tickers:  48%|████▊     | 3229/6774 [11:01<12:06,  4.88it/s]

Processing tickers:  48%|████▊     | 3230/6774 [11:01<12:01,  4.91it/s]

Processing tickers:  48%|████▊     | 3231/6774 [11:01<12:03,  4.90it/s]

Processing tickers:  48%|████▊     | 3232/6774 [11:01<12:29,  4.73it/s]

Processing tickers:  48%|████▊     | 3233/6774 [11:01<12:16,  4.81it/s]

Processing tickers:  48%|████▊     | 3234/6774 [11:02<12:08,  4.86it/s]

Processing tickers:  48%|████▊     | 3235/6774 [11:02<12:01,  4.90it/s]

Processing tickers:  48%|████▊     | 3236/6774 [11:02<11:54,  4.95it/s]

Processing tickers:  48%|████▊     | 3237/6774 [11:02<12:01,  4.90it/s]

Processing tickers:  48%|████▊     | 3238/6774 [11:02<11:53,  4.95it/s]

Processing tickers:  48%|████▊     | 3239/6774 [11:03<11:47,  4.99it/s]

Processing tickers:  48%|████▊     | 3240/6774 [11:03<11:50,  4.97it/s]

Processing tickers:  48%|████▊     | 3241/6774 [11:03<11:45,  5.01it/s]

Processing tickers:  48%|████▊     | 3242/6774 [11:03<11:53,  4.95it/s]

Processing tickers:  48%|████▊     | 3243/6774 [11:03<11:51,  4.96it/s]

Processing tickers:  48%|████▊     | 3244/6774 [11:04<11:48,  4.98it/s]

Processing tickers:  48%|████▊     | 3245/6774 [11:04<11:47,  4.99it/s]

Processing tickers:  48%|████▊     | 3246/6774 [11:04<11:56,  4.93it/s]

Processing tickers:  48%|████▊     | 3247/6774 [11:04<12:12,  4.81it/s]

Processing tickers:  48%|████▊     | 3248/6774 [11:04<12:27,  4.72it/s]

Processing tickers:  48%|████▊     | 3249/6774 [11:05<12:13,  4.80it/s]

Processing tickers:  48%|████▊     | 3250/6774 [11:05<12:06,  4.85it/s]

Processing tickers:  48%|████▊     | 3251/6774 [11:05<12:08,  4.84it/s]

Processing tickers:  48%|████▊     | 3252/6774 [11:05<12:05,  4.86it/s]

Processing tickers:  48%|████▊     | 3253/6774 [11:05<12:04,  4.86it/s]

Processing tickers:  48%|████▊     | 3254/6774 [11:06<12:10,  4.82it/s]

Processing tickers:  48%|████▊     | 3255/6774 [11:06<12:09,  4.82it/s]

Processing tickers:  48%|████▊     | 3256/6774 [11:06<11:59,  4.89it/s]

Processing tickers:  48%|████▊     | 3257/6774 [11:06<11:54,  4.92it/s]

Processing tickers:  48%|████▊     | 3258/6774 [11:06<11:51,  4.94it/s]

Processing tickers:  48%|████▊     | 3259/6774 [11:07<11:46,  4.98it/s]

Processing tickers:  48%|████▊     | 3260/6774 [11:07<11:43,  4.99it/s]

Processing tickers:  48%|████▊     | 3261/6774 [11:07<11:44,  4.99it/s]

Processing tickers:  48%|████▊     | 3262/6774 [11:07<11:54,  4.92it/s]

Processing tickers:  48%|████▊     | 3263/6774 [11:07<11:48,  4.95it/s]

Processing tickers:  48%|████▊     | 3264/6774 [11:08<11:49,  4.94it/s]

Processing tickers:  48%|████▊     | 3265/6774 [11:08<11:51,  4.93it/s]

Processing tickers:  48%|████▊     | 3266/6774 [11:08<11:48,  4.95it/s]

Processing tickers:  48%|████▊     | 3267/6774 [11:08<11:50,  4.94it/s]

Processing tickers:  48%|████▊     | 3268/6774 [11:08<11:49,  4.94it/s]

Processing tickers:  48%|████▊     | 3269/6774 [11:09<12:06,  4.82it/s]

Processing tickers:  48%|████▊     | 3270/6774 [11:09<11:58,  4.88it/s]

Processing tickers:  48%|████▊     | 3271/6774 [11:09<11:54,  4.90it/s]

Processing tickers:  48%|████▊     | 3272/6774 [11:09<11:49,  4.94it/s]

Processing tickers:  48%|████▊     | 3273/6774 [11:10<12:30,  4.66it/s]

Processing tickers:  48%|████▊     | 3274/6774 [11:10<12:40,  4.60it/s]

Processing tickers:  48%|████▊     | 3275/6774 [11:10<12:24,  4.70it/s]

Processing tickers:  48%|████▊     | 3276/6774 [11:10<12:12,  4.78it/s]

Processing tickers:  48%|████▊     | 3277/6774 [11:10<12:00,  4.85it/s]

Processing tickers:  48%|████▊     | 3278/6774 [11:11<11:57,  4.87it/s]

Processing tickers:  48%|████▊     | 3279/6774 [11:11<11:50,  4.92it/s]

Processing tickers:  48%|████▊     | 3280/6774 [11:11<11:45,  4.95it/s]

Processing tickers:  48%|████▊     | 3281/6774 [11:11<12:00,  4.85it/s]

Processing tickers:  48%|████▊     | 3282/6774 [11:11<11:58,  4.86it/s]

Processing tickers:  48%|████▊     | 3283/6774 [11:12<11:51,  4.90it/s]

Processing tickers:  48%|████▊     | 3284/6774 [11:12<12:13,  4.76it/s]

Processing tickers:  48%|████▊     | 3285/6774 [11:12<12:15,  4.75it/s]

Processing tickers:  49%|████▊     | 3286/6774 [11:12<12:06,  4.80it/s]

Processing tickers:  49%|████▊     | 3287/6774 [11:12<12:02,  4.82it/s]

Processing tickers:  49%|████▊     | 3288/6774 [11:13<11:52,  4.89it/s]

Processing tickers:  49%|████▊     | 3289/6774 [11:13<11:45,  4.94it/s]

Processing tickers:  49%|████▊     | 3290/6774 [11:13<12:04,  4.81it/s]

Processing tickers:  49%|████▊     | 3291/6774 [11:13<11:54,  4.87it/s]

Processing tickers:  49%|████▊     | 3292/6774 [11:13<11:47,  4.92it/s]

Processing tickers:  49%|████▊     | 3293/6774 [11:14<12:02,  4.82it/s]

Processing tickers:  49%|████▊     | 3294/6774 [11:14<11:55,  4.86it/s]

Processing tickers:  49%|████▊     | 3295/6774 [11:14<11:52,  4.89it/s]

Processing tickers:  49%|████▊     | 3296/6774 [11:14<11:49,  4.90it/s]

Processing tickers:  49%|████▊     | 3297/6774 [11:14<11:49,  4.90it/s]

Processing tickers:  49%|████▊     | 3298/6774 [11:15<11:38,  4.97it/s]

Processing tickers:  49%|████▊     | 3299/6774 [11:15<11:37,  4.98it/s]

Processing tickers:  49%|████▊     | 3300/6774 [11:15<11:48,  4.90it/s]

Processing tickers:  49%|████▊     | 3301/6774 [11:15<11:42,  4.94it/s]

Processing tickers:  49%|████▊     | 3302/6774 [11:15<11:37,  4.98it/s]

Processing tickers:  49%|████▉     | 3303/6774 [11:16<11:49,  4.89it/s]

Processing tickers:  49%|████▉     | 3304/6774 [11:16<11:44,  4.93it/s]

Processing tickers:  49%|████▉     | 3305/6774 [11:16<11:45,  4.92it/s]

Processing tickers:  49%|████▉     | 3306/6774 [11:16<11:57,  4.83it/s]

Processing tickers:  49%|████▉     | 3307/6774 [11:16<11:55,  4.85it/s]

Processing tickers:  49%|████▉     | 3308/6774 [11:17<11:48,  4.89it/s]

Processing tickers:  49%|████▉     | 3309/6774 [11:17<11:43,  4.92it/s]

Processing tickers:  49%|████▉     | 3310/6774 [11:17<11:50,  4.87it/s]

Processing tickers:  49%|████▉     | 3311/6774 [11:17<11:44,  4.91it/s]

Processing tickers:  49%|████▉     | 3312/6774 [11:18<11:54,  4.84it/s]

Processing tickers:  49%|████▉     | 3313/6774 [11:18<11:46,  4.90it/s]

Processing tickers:  49%|████▉     | 3314/6774 [11:18<11:43,  4.92it/s]

Processing tickers:  49%|████▉     | 3315/6774 [11:18<11:44,  4.91it/s]

Processing tickers:  49%|████▉     | 3316/6774 [11:18<11:47,  4.89it/s]

Processing tickers:  49%|████▉     | 3317/6774 [11:19<12:06,  4.76it/s]

Processing tickers:  49%|████▉     | 3318/6774 [11:19<11:59,  4.80it/s]

Processing tickers:  49%|████▉     | 3319/6774 [11:19<12:10,  4.73it/s]

Processing tickers:  49%|████▉     | 3320/6774 [11:19<12:09,  4.74it/s]

Processing tickers:  49%|████▉     | 3321/6774 [11:19<12:14,  4.70it/s]

Processing tickers:  49%|████▉     | 3322/6774 [11:20<11:59,  4.80it/s]

Processing tickers:  49%|████▉     | 3323/6774 [11:20<12:08,  4.74it/s]

Processing tickers:  49%|████▉     | 3324/6774 [11:20<12:03,  4.77it/s]

Processing tickers:  49%|████▉     | 3325/6774 [11:20<12:02,  4.78it/s]

Processing tickers:  49%|████▉     | 3326/6774 [11:20<12:00,  4.78it/s]

Processing tickers:  49%|████▉     | 3327/6774 [11:21<11:46,  4.88it/s]

Processing tickers:  49%|████▉     | 3328/6774 [11:21<12:05,  4.75it/s]

Processing tickers:  49%|████▉     | 3329/6774 [11:21<11:50,  4.85it/s]

Processing tickers:  49%|████▉     | 3330/6774 [11:21<11:46,  4.88it/s]

Processing tickers:  49%|████▉     | 3331/6774 [11:21<11:48,  4.86it/s]

Processing tickers:  49%|████▉     | 3332/6774 [11:22<11:57,  4.80it/s]

Processing tickers:  49%|████▉     | 3333/6774 [11:22<12:08,  4.72it/s]

Processing tickers:  49%|████▉     | 3334/6774 [11:22<11:54,  4.82it/s]

Processing tickers:  49%|████▉     | 3335/6774 [11:22<11:45,  4.88it/s]

Processing tickers:  49%|████▉     | 3336/6774 [11:22<11:50,  4.84it/s]

Processing tickers:  49%|████▉     | 3337/6774 [11:23<11:43,  4.89it/s]

Processing tickers:  49%|████▉     | 3338/6774 [11:23<11:34,  4.95it/s]

Processing tickers:  49%|████▉     | 3339/6774 [11:23<11:31,  4.97it/s]

Processing tickers:  49%|████▉     | 3340/6774 [11:23<11:36,  4.93it/s]

Processing tickers:  49%|████▉     | 3341/6774 [11:23<11:35,  4.94it/s]

Processing tickers:  49%|████▉     | 3342/6774 [11:24<11:32,  4.95it/s]

Processing tickers:  49%|████▉     | 3343/6774 [11:24<11:26,  5.00it/s]

Processing tickers:  49%|████▉     | 3344/6774 [11:24<11:25,  5.00it/s]

Processing tickers:  49%|████▉     | 3345/6774 [11:24<11:23,  5.02it/s]

Processing tickers:  49%|████▉     | 3346/6774 [11:24<11:24,  5.01it/s]

Processing tickers:  49%|████▉     | 3347/6774 [11:25<11:29,  4.97it/s]

Processing tickers:  49%|████▉     | 3348/6774 [11:25<11:32,  4.95it/s]

Processing tickers:  49%|████▉     | 3349/6774 [11:25<11:31,  4.95it/s]

Processing tickers:  49%|████▉     | 3350/6774 [11:25<11:32,  4.94it/s]

Processing tickers:  49%|████▉     | 3351/6774 [11:26<11:48,  4.83it/s]

Processing tickers:  49%|████▉     | 3352/6774 [11:26<11:42,  4.87it/s]

Processing tickers:  49%|████▉     | 3353/6774 [11:26<11:35,  4.92it/s]

Processing tickers:  50%|████▉     | 3354/6774 [11:26<11:35,  4.91it/s]

Processing tickers:  50%|████▉     | 3355/6774 [11:26<11:29,  4.96it/s]

Processing tickers:  50%|████▉     | 3356/6774 [11:27<11:28,  4.96it/s]

Processing tickers:  50%|████▉     | 3357/6774 [11:27<11:36,  4.90it/s]

Processing tickers:  50%|████▉     | 3358/6774 [11:27<11:47,  4.83it/s]

Processing tickers:  50%|████▉     | 3359/6774 [11:27<11:46,  4.83it/s]

Processing tickers:  50%|████▉     | 3360/6774 [11:27<11:41,  4.87it/s]

Processing tickers:  50%|████▉     | 3361/6774 [11:28<11:36,  4.90it/s]

Processing tickers:  50%|████▉     | 3362/6774 [11:28<11:32,  4.93it/s]

Processing tickers:  50%|████▉     | 3363/6774 [11:28<11:28,  4.96it/s]

Processing tickers:  50%|████▉     | 3364/6774 [11:28<11:47,  4.82it/s]

Processing tickers:  50%|████▉     | 3365/6774 [11:28<11:36,  4.89it/s]

Processing tickers:  50%|████▉     | 3366/6774 [11:29<11:44,  4.84it/s]

Processing tickers:  50%|████▉     | 3367/6774 [11:29<11:34,  4.90it/s]

Processing tickers:  50%|████▉     | 3368/6774 [11:29<11:58,  4.74it/s]

Processing tickers:  50%|████▉     | 3369/6774 [11:29<12:00,  4.73it/s]

Processing tickers:  50%|████▉     | 3370/6774 [11:29<11:52,  4.78it/s]

Processing tickers:  50%|████▉     | 3371/6774 [11:30<11:44,  4.83it/s]

Processing tickers:  50%|████▉     | 3372/6774 [11:30<11:37,  4.88it/s]

Processing tickers:  50%|████▉     | 3373/6774 [11:30<11:30,  4.92it/s]

Processing tickers:  50%|████▉     | 3374/6774 [11:30<11:24,  4.96it/s]

Processing tickers:  50%|████▉     | 3375/6774 [11:30<11:30,  4.92it/s]

Processing tickers:  50%|████▉     | 3376/6774 [11:31<11:25,  4.96it/s]

Processing tickers:  50%|████▉     | 3377/6774 [11:31<11:41,  4.84it/s]

Processing tickers:  50%|████▉     | 3378/6774 [11:31<11:43,  4.82it/s]

Processing tickers:  50%|████▉     | 3379/6774 [11:31<11:36,  4.88it/s]

Processing tickers:  50%|████▉     | 3380/6774 [11:31<11:42,  4.83it/s]

Processing tickers:  50%|████▉     | 3381/6774 [11:32<11:32,  4.90it/s]

Processing tickers:  50%|████▉     | 3382/6774 [11:32<11:27,  4.93it/s]

Processing tickers:  50%|████▉     | 3383/6774 [11:32<11:25,  4.95it/s]

Processing tickers:  50%|████▉     | 3384/6774 [11:32<11:23,  4.96it/s]

Processing tickers:  50%|████▉     | 3385/6774 [11:32<11:27,  4.93it/s]

Processing tickers:  50%|████▉     | 3386/6774 [11:33<11:26,  4.94it/s]

Processing tickers:  50%|█████     | 3387/6774 [11:33<11:31,  4.90it/s]

Processing tickers:  50%|█████     | 3388/6774 [11:33<11:29,  4.91it/s]

Processing tickers:  50%|█████     | 3389/6774 [11:33<11:22,  4.96it/s]

Processing tickers:  50%|█████     | 3390/6774 [11:33<11:15,  5.01it/s]

Processing tickers:  50%|█████     | 3391/6774 [11:34<11:24,  4.94it/s]

Processing tickers:  50%|█████     | 3392/6774 [11:34<11:15,  5.01it/s]

Processing tickers:  50%|█████     | 3393/6774 [11:34<11:16,  5.00it/s]

Processing tickers:  50%|█████     | 3394/6774 [11:34<11:43,  4.80it/s]

Processing tickers:  50%|█████     | 3395/6774 [11:35<12:13,  4.61it/s]

Processing tickers:  50%|█████     | 3396/6774 [11:35<12:20,  4.56it/s]

Processing tickers:  50%|█████     | 3397/6774 [11:35<12:31,  4.50it/s]

Processing tickers:  50%|█████     | 3398/6774 [11:35<12:29,  4.50it/s]

Processing tickers:  50%|█████     | 3399/6774 [11:35<12:18,  4.57it/s]

Processing tickers:  50%|█████     | 3400/6774 [11:36<12:05,  4.65it/s]

Processing tickers:  50%|█████     | 3401/6774 [11:36<12:17,  4.58it/s]

Processing tickers:  50%|█████     | 3402/6774 [11:36<11:57,  4.70it/s]

Processing tickers:  50%|█████     | 3403/6774 [11:36<11:42,  4.80it/s]

Processing tickers:  50%|█████     | 3404/6774 [11:36<11:35,  4.84it/s]

Processing tickers:  50%|█████     | 3405/6774 [11:37<11:32,  4.86it/s]

Processing tickers:  50%|█████     | 3406/6774 [11:37<11:24,  4.92it/s]

Processing tickers:  50%|█████     | 3407/6774 [11:37<11:20,  4.95it/s]

Processing tickers:  50%|█████     | 3408/6774 [11:37<11:16,  4.98it/s]

Processing tickers:  50%|█████     | 3409/6774 [11:37<11:15,  4.98it/s]

Processing tickers:  50%|█████     | 3410/6774 [11:38<11:38,  4.82it/s]

Processing tickers:  50%|█████     | 3411/6774 [11:38<11:28,  4.89it/s]

Processing tickers:  50%|█████     | 3412/6774 [11:38<11:21,  4.93it/s]

Processing tickers:  50%|█████     | 3413/6774 [11:38<11:14,  4.98it/s]

Processing tickers:  50%|█████     | 3414/6774 [11:38<11:22,  4.93it/s]

Processing tickers:  50%|█████     | 3415/6774 [11:39<11:17,  4.96it/s]

Processing tickers:  50%|█████     | 3416/6774 [11:39<11:18,  4.95it/s]

Processing tickers:  50%|█████     | 3417/6774 [11:39<11:16,  4.96it/s]

Processing tickers:  50%|█████     | 3418/6774 [11:39<11:15,  4.97it/s]

Processing tickers:  50%|█████     | 3419/6774 [11:39<11:13,  4.98it/s]

Processing tickers:  50%|█████     | 3420/6774 [11:40<11:13,  4.98it/s]

Processing tickers:  51%|█████     | 3421/6774 [11:40<11:10,  5.00it/s]

Processing tickers:  51%|█████     | 3422/6774 [11:40<11:08,  5.01it/s]

Processing tickers:  51%|█████     | 3423/6774 [11:40<11:22,  4.91it/s]

Processing tickers:  51%|█████     | 3424/6774 [11:40<11:16,  4.95it/s]

Processing tickers:  51%|█████     | 3425/6774 [11:41<11:32,  4.84it/s]

Processing tickers:  51%|█████     | 3426/6774 [11:41<11:21,  4.91it/s]

Processing tickers:  51%|█████     | 3427/6774 [11:41<11:16,  4.95it/s]

Processing tickers:  51%|█████     | 3428/6774 [11:41<11:14,  4.96it/s]

Processing tickers:  51%|█████     | 3429/6774 [11:42<11:10,  4.99it/s]

Processing tickers:  51%|█████     | 3430/6774 [11:42<11:38,  4.78it/s]

Processing tickers:  51%|█████     | 3431/6774 [11:42<11:48,  4.72it/s]

Processing tickers:  51%|█████     | 3432/6774 [11:42<11:33,  4.82it/s]

Processing tickers:  51%|█████     | 3433/6774 [11:42<11:23,  4.89it/s]

Processing tickers:  51%|█████     | 3434/6774 [11:43<11:15,  4.94it/s]

Processing tickers:  51%|█████     | 3435/6774 [11:43<11:12,  4.97it/s]

Processing tickers:  51%|█████     | 3436/6774 [11:43<11:13,  4.96it/s]

Processing tickers:  51%|█████     | 3437/6774 [11:43<11:07,  5.00it/s]

Processing tickers:  51%|█████     | 3438/6774 [11:43<11:19,  4.91it/s]

Processing tickers:  51%|█████     | 3439/6774 [11:44<11:21,  4.89it/s]

Processing tickers:  51%|█████     | 3440/6774 [11:44<11:28,  4.84it/s]

Processing tickers:  51%|█████     | 3441/6774 [11:44<11:43,  4.73it/s]

Processing tickers:  51%|█████     | 3442/6774 [11:44<11:42,  4.74it/s]

Processing tickers:  51%|█████     | 3443/6774 [11:44<11:39,  4.76it/s]

Processing tickers:  51%|█████     | 3444/6774 [11:45<11:32,  4.81it/s]

Processing tickers:  51%|█████     | 3445/6774 [11:45<11:23,  4.87it/s]

Processing tickers:  51%|█████     | 3446/6774 [11:45<11:33,  4.80it/s]

Processing tickers:  51%|█████     | 3447/6774 [11:45<11:51,  4.67it/s]

Processing tickers:  51%|█████     | 3448/6774 [11:45<11:40,  4.75it/s]

Processing tickers:  51%|█████     | 3449/6774 [11:46<11:32,  4.80it/s]

Processing tickers:  51%|█████     | 3450/6774 [11:46<11:27,  4.83it/s]

Processing tickers:  51%|█████     | 3451/6774 [11:46<11:36,  4.77it/s]

Processing tickers:  51%|█████     | 3452/6774 [11:46<11:28,  4.82it/s]

Processing tickers:  51%|█████     | 3453/6774 [11:46<11:24,  4.85it/s]

Processing tickers:  51%|█████     | 3454/6774 [11:47<11:27,  4.83it/s]

Processing tickers:  51%|█████     | 3455/6774 [11:47<11:26,  4.83it/s]

Processing tickers:  51%|█████     | 3456/6774 [11:47<11:26,  4.83it/s]

Processing tickers:  51%|█████     | 3457/6774 [11:47<11:19,  4.88it/s]

Processing tickers:  51%|█████     | 3458/6774 [11:48<11:12,  4.93it/s]

Processing tickers:  51%|█████     | 3459/6774 [11:48<11:14,  4.91it/s]

Processing tickers:  51%|█████     | 3460/6774 [11:48<11:15,  4.91it/s]

Processing tickers:  51%|█████     | 3461/6774 [11:48<11:10,  4.94it/s]

Processing tickers:  51%|█████     | 3462/6774 [11:48<11:11,  4.93it/s]

Processing tickers:  51%|█████     | 3463/6774 [11:49<11:22,  4.85it/s]

Processing tickers:  51%|█████     | 3464/6774 [11:49<11:25,  4.83it/s]

Processing tickers:  51%|█████     | 3465/6774 [11:49<11:15,  4.90it/s]

Processing tickers:  51%|█████     | 3466/6774 [11:49<11:10,  4.93it/s]

Processing tickers:  51%|█████     | 3467/6774 [11:49<11:04,  4.97it/s]

Processing tickers:  51%|█████     | 3468/6774 [11:50<11:14,  4.90it/s]

Processing tickers:  51%|█████     | 3469/6774 [11:50<11:19,  4.87it/s]

Processing tickers:  51%|█████     | 3470/6774 [11:50<11:32,  4.77it/s]

Processing tickers:  51%|█████     | 3471/6774 [11:50<11:20,  4.86it/s]

Processing tickers:  51%|█████▏    | 3472/6774 [11:50<11:20,  4.85it/s]

Processing tickers:  51%|█████▏    | 3473/6774 [11:51<11:19,  4.86it/s]

Processing tickers:  51%|█████▏    | 3474/6774 [11:51<11:14,  4.89it/s]

Processing tickers:  51%|█████▏    | 3475/6774 [11:51<11:28,  4.79it/s]

Processing tickers:  51%|█████▏    | 3476/6774 [11:51<11:17,  4.86it/s]

Processing tickers:  51%|█████▏    | 3477/6774 [11:51<11:26,  4.81it/s]

Processing tickers:  51%|█████▏    | 3478/6774 [11:52<11:14,  4.88it/s]

Processing tickers:  51%|█████▏    | 3479/6774 [11:52<11:11,  4.91it/s]

Processing tickers:  51%|█████▏    | 3480/6774 [11:52<11:06,  4.94it/s]

Processing tickers:  51%|█████▏    | 3481/6774 [11:52<11:15,  4.87it/s]

Processing tickers:  51%|█████▏    | 3482/6774 [11:52<11:09,  4.91it/s]

Processing tickers:  51%|█████▏    | 3483/6774 [11:53<11:04,  4.95it/s]

Processing tickers:  51%|█████▏    | 3484/6774 [11:53<10:59,  4.99it/s]

Processing tickers:  51%|█████▏    | 3485/6774 [11:53<11:16,  4.86it/s]

Processing tickers:  51%|█████▏    | 3486/6774 [11:53<11:11,  4.90it/s]

Processing tickers:  51%|█████▏    | 3487/6774 [11:53<11:05,  4.94it/s]

Processing tickers:  51%|█████▏    | 3488/6774 [11:54<11:05,  4.94it/s]

Processing tickers:  52%|█████▏    | 3489/6774 [11:54<11:01,  4.97it/s]

Processing tickers:  52%|█████▏    | 3490/6774 [11:54<10:58,  4.99it/s]

Processing tickers:  52%|█████▏    | 3491/6774 [11:54<10:58,  4.99it/s]

Processing tickers:  52%|█████▏    | 3492/6774 [11:54<11:10,  4.90it/s]

Processing tickers:  52%|█████▏    | 3493/6774 [11:55<11:15,  4.86it/s]

Processing tickers:  52%|█████▏    | 3494/6774 [11:55<11:12,  4.87it/s]

Processing tickers:  52%|█████▏    | 3495/6774 [11:55<11:05,  4.93it/s]

Processing tickers:  52%|█████▏    | 3496/6774 [11:55<11:02,  4.95it/s]

Processing tickers:  52%|█████▏    | 3497/6774 [11:55<11:02,  4.95it/s]

Processing tickers:  52%|█████▏    | 3498/6774 [11:56<10:58,  4.97it/s]

Processing tickers:  52%|█████▏    | 3499/6774 [11:56<11:19,  4.82it/s]

Processing tickers:  52%|█████▏    | 3500/6774 [11:56<11:10,  4.88it/s]

Processing tickers:  52%|█████▏    | 3501/6774 [11:56<11:07,  4.90it/s]

Processing tickers:  52%|█████▏    | 3502/6774 [11:56<11:07,  4.90it/s]

Processing tickers:  52%|█████▏    | 3503/6774 [11:57<11:10,  4.88it/s]

Processing tickers:  52%|█████▏    | 3504/6774 [11:57<11:04,  4.92it/s]

Processing tickers:  52%|█████▏    | 3505/6774 [11:57<10:57,  4.97it/s]

Processing tickers:  52%|█████▏    | 3506/6774 [11:57<10:54,  4.99it/s]

Processing tickers:  52%|█████▏    | 3507/6774 [11:57<10:54,  4.99it/s]

Processing tickers:  52%|█████▏    | 3508/6774 [11:58<10:54,  4.99it/s]

Processing tickers:  52%|█████▏    | 3509/6774 [11:58<10:56,  4.97it/s]

Processing tickers:  52%|█████▏    | 3510/6774 [11:58<11:35,  4.69it/s]

Processing tickers:  52%|█████▏    | 3511/6774 [11:58<11:22,  4.78it/s]

Processing tickers:  52%|█████▏    | 3512/6774 [11:59<11:18,  4.81it/s]

Processing tickers:  52%|█████▏    | 3513/6774 [11:59<11:13,  4.84it/s]

Processing tickers:  52%|█████▏    | 3514/6774 [11:59<11:02,  4.92it/s]

Processing tickers:  52%|█████▏    | 3515/6774 [11:59<11:06,  4.89it/s]

Processing tickers:  52%|█████▏    | 3516/6774 [11:59<11:00,  4.94it/s]

Processing tickers:  52%|█████▏    | 3517/6774 [12:00<10:58,  4.95it/s]

Processing tickers:  52%|█████▏    | 3518/6774 [12:00<10:57,  4.96it/s]

Processing tickers:  52%|█████▏    | 3519/6774 [12:00<10:57,  4.95it/s]

Processing tickers:  52%|█████▏    | 3520/6774 [12:00<10:53,  4.98it/s]

Processing tickers:  52%|█████▏    | 3521/6774 [12:00<10:47,  5.02it/s]

Processing tickers:  52%|█████▏    | 3522/6774 [12:01<10:54,  4.97it/s]

Processing tickers:  52%|█████▏    | 3523/6774 [12:01<10:53,  4.97it/s]

Processing tickers:  52%|█████▏    | 3524/6774 [12:01<11:25,  4.74it/s]

Processing tickers:  52%|█████▏    | 3525/6774 [12:01<11:13,  4.82it/s]

Processing tickers:  52%|█████▏    | 3526/6774 [12:01<11:06,  4.88it/s]

Processing tickers:  52%|█████▏    | 3527/6774 [12:02<11:06,  4.87it/s]

Processing tickers:  52%|█████▏    | 3528/6774 [12:02<11:09,  4.85it/s]

Processing tickers:  52%|█████▏    | 3529/6774 [12:02<11:09,  4.84it/s]

Processing tickers:  52%|█████▏    | 3530/6774 [12:02<11:07,  4.86it/s]

Processing tickers:  52%|█████▏    | 3531/6774 [12:02<11:06,  4.87it/s]

Processing tickers:  52%|█████▏    | 3532/6774 [12:03<11:03,  4.89it/s]

Processing tickers:  52%|█████▏    | 3533/6774 [12:03<10:57,  4.93it/s]

Processing tickers:  52%|█████▏    | 3534/6774 [12:03<10:55,  4.94it/s]

Processing tickers:  52%|█████▏    | 3535/6774 [12:03<10:54,  4.95it/s]

Processing tickers:  52%|█████▏    | 3536/6774 [12:03<10:51,  4.97it/s]

Processing tickers:  52%|█████▏    | 3537/6774 [12:04<12:08,  4.45it/s]

Processing tickers:  52%|█████▏    | 3538/6774 [12:04<11:44,  4.59it/s]

Processing tickers:  52%|█████▏    | 3539/6774 [12:04<11:31,  4.68it/s]

Processing tickers:  52%|█████▏    | 3540/6774 [12:04<11:21,  4.75it/s]

Processing tickers:  52%|█████▏    | 3541/6774 [12:05<11:29,  4.69it/s]

Processing tickers:  52%|█████▏    | 3542/6774 [12:05<11:18,  4.77it/s]

Processing tickers:  52%|█████▏    | 3543/6774 [12:05<11:24,  4.72it/s]

Processing tickers:  52%|█████▏    | 3544/6774 [12:05<11:10,  4.82it/s]

Processing tickers:  52%|█████▏    | 3545/6774 [12:05<11:10,  4.81it/s]

Processing tickers:  52%|█████▏    | 3546/6774 [12:06<11:12,  4.80it/s]

Processing tickers:  52%|█████▏    | 3547/6774 [12:06<10:59,  4.89it/s]

Processing tickers:  52%|█████▏    | 3548/6774 [12:06<11:10,  4.81it/s]

Processing tickers:  52%|█████▏    | 3549/6774 [12:06<11:27,  4.69it/s]

Processing tickers:  52%|█████▏    | 3550/6774 [12:06<11:19,  4.74it/s]

Processing tickers:  52%|█████▏    | 3551/6774 [12:07<11:08,  4.82it/s]

Processing tickers:  52%|█████▏    | 3552/6774 [12:07<11:05,  4.84it/s]

Processing tickers:  52%|█████▏    | 3553/6774 [12:07<10:55,  4.91it/s]

Processing tickers:  52%|█████▏    | 3554/6774 [12:07<10:49,  4.96it/s]

Processing tickers:  52%|█████▏    | 3555/6774 [12:07<10:49,  4.96it/s]

Processing tickers:  52%|█████▏    | 3556/6774 [12:08<10:45,  4.99it/s]

Processing tickers:  53%|█████▎    | 3557/6774 [12:08<10:57,  4.90it/s]

Processing tickers:  53%|█████▎    | 3558/6774 [12:08<11:14,  4.77it/s]

Processing tickers:  53%|█████▎    | 3559/6774 [12:08<11:08,  4.81it/s]

Processing tickers:  53%|█████▎    | 3560/6774 [12:08<11:32,  4.64it/s]

Processing tickers:  53%|█████▎    | 3561/6774 [12:09<11:18,  4.73it/s]

Processing tickers:  53%|█████▎    | 3562/6774 [12:09<11:07,  4.81it/s]

Processing tickers:  53%|█████▎    | 3563/6774 [12:09<11:20,  4.72it/s]

Processing tickers:  53%|█████▎    | 3564/6774 [12:09<11:23,  4.70it/s]

Processing tickers:  53%|█████▎    | 3565/6774 [12:10<11:08,  4.80it/s]

Processing tickers:  53%|█████▎    | 3566/6774 [12:10<10:59,  4.86it/s]

Processing tickers:  53%|█████▎    | 3567/6774 [12:10<10:54,  4.90it/s]

Processing tickers:  53%|█████▎    | 3568/6774 [12:10<10:58,  4.87it/s]

Processing tickers:  53%|█████▎    | 3569/6774 [12:10<10:51,  4.92it/s]

Processing tickers:  53%|█████▎    | 3570/6774 [12:11<10:52,  4.91it/s]

Processing tickers:  53%|█████▎    | 3571/6774 [12:11<11:06,  4.80it/s]

Processing tickers:  53%|█████▎    | 3572/6774 [12:11<11:07,  4.80it/s]

Processing tickers:  53%|█████▎    | 3573/6774 [12:11<10:59,  4.85it/s]

Processing tickers:  53%|█████▎    | 3574/6774 [12:11<11:01,  4.84it/s]

Processing tickers:  53%|█████▎    | 3575/6774 [12:12<10:55,  4.88it/s]

Processing tickers:  53%|█████▎    | 3576/6774 [12:12<11:00,  4.84it/s]

Processing tickers:  53%|█████▎    | 3577/6774 [12:12<11:23,  4.68it/s]

Processing tickers:  53%|█████▎    | 3578/6774 [12:12<11:10,  4.77it/s]

Processing tickers:  53%|█████▎    | 3579/6774 [12:12<10:56,  4.86it/s]

Processing tickers:  53%|█████▎    | 3580/6774 [12:13<11:11,  4.76it/s]

Processing tickers:  53%|█████▎    | 3581/6774 [12:13<11:01,  4.82it/s]

Processing tickers:  53%|█████▎    | 3582/6774 [12:13<11:02,  4.82it/s]

Processing tickers:  53%|█████▎    | 3583/6774 [12:13<10:53,  4.88it/s]

Processing tickers:  53%|█████▎    | 3584/6774 [12:13<11:01,  4.82it/s]

Processing tickers:  53%|█████▎    | 3585/6774 [12:14<11:03,  4.81it/s]

Processing tickers:  53%|█████▎    | 3586/6774 [12:14<11:03,  4.80it/s]

Processing tickers:  53%|█████▎    | 3587/6774 [12:14<10:53,  4.88it/s]

Processing tickers:  53%|█████▎    | 3588/6774 [12:14<10:54,  4.86it/s]

Processing tickers:  53%|█████▎    | 3589/6774 [12:14<10:44,  4.94it/s]

Processing tickers:  53%|█████▎    | 3590/6774 [12:15<10:40,  4.97it/s]

Processing tickers:  53%|█████▎    | 3591/6774 [12:15<10:36,  5.00it/s]

Processing tickers:  53%|█████▎    | 3592/6774 [12:15<10:38,  4.99it/s]

Processing tickers:  53%|█████▎    | 3593/6774 [12:15<10:42,  4.95it/s]

Processing tickers:  53%|█████▎    | 3594/6774 [12:15<10:37,  4.99it/s]

Processing tickers:  53%|█████▎    | 3595/6774 [12:16<10:37,  4.99it/s]

Processing tickers:  53%|█████▎    | 3596/6774 [12:16<10:32,  5.03it/s]

Processing tickers:  53%|█████▎    | 3597/6774 [12:16<10:47,  4.91it/s]

Processing tickers:  53%|█████▎    | 3598/6774 [12:16<10:58,  4.82it/s]

Processing tickers:  53%|█████▎    | 3599/6774 [12:16<10:50,  4.88it/s]

Processing tickers:  53%|█████▎    | 3600/6774 [12:17<10:45,  4.92it/s]

Processing tickers:  53%|█████▎    | 3601/6774 [12:17<11:03,  4.78it/s]

Processing tickers:  53%|█████▎    | 3602/6774 [12:17<10:56,  4.83it/s]

Processing tickers:  53%|█████▎    | 3603/6774 [12:17<11:10,  4.73it/s]

Processing tickers:  53%|█████▎    | 3604/6774 [12:18<11:08,  4.74it/s]

Processing tickers:  53%|█████▎    | 3605/6774 [12:18<10:57,  4.82it/s]

Processing tickers:  53%|█████▎    | 3606/6774 [12:18<11:02,  4.78it/s]

Processing tickers:  53%|█████▎    | 3607/6774 [12:18<10:53,  4.84it/s]

Processing tickers:  53%|█████▎    | 3608/6774 [12:18<10:45,  4.91it/s]

Processing tickers:  53%|█████▎    | 3609/6774 [12:19<10:43,  4.92it/s]

Processing tickers:  53%|█████▎    | 3610/6774 [12:19<10:38,  4.95it/s]

Processing tickers:  53%|█████▎    | 3611/6774 [12:19<10:38,  4.96it/s]

Processing tickers:  53%|█████▎    | 3612/6774 [12:19<10:35,  4.98it/s]

Processing tickers:  53%|█████▎    | 3613/6774 [12:19<10:33,  4.99it/s]

Processing tickers:  53%|█████▎    | 3614/6774 [12:20<10:30,  5.01it/s]

Processing tickers:  53%|█████▎    | 3615/6774 [12:20<10:26,  5.04it/s]

Processing tickers:  53%|█████▎    | 3616/6774 [12:20<10:29,  5.02it/s]

Processing tickers:  53%|█████▎    | 3617/6774 [12:20<10:35,  4.97it/s]

Processing tickers:  53%|█████▎    | 3618/6774 [12:20<10:32,  4.99it/s]

Processing tickers:  53%|█████▎    | 3619/6774 [12:21<10:30,  5.01it/s]

Processing tickers:  53%|█████▎    | 3620/6774 [12:21<10:28,  5.02it/s]

Processing tickers:  53%|█████▎    | 3621/6774 [12:21<10:25,  5.04it/s]

Processing tickers:  53%|█████▎    | 3622/6774 [12:21<10:23,  5.05it/s]

Processing tickers:  53%|█████▎    | 3623/6774 [12:21<10:28,  5.01it/s]

Processing tickers:  53%|█████▎    | 3624/6774 [12:22<10:28,  5.01it/s]

Processing tickers:  54%|█████▎    | 3625/6774 [12:22<10:29,  5.01it/s]

Processing tickers:  54%|█████▎    | 3626/6774 [12:22<10:28,  5.01it/s]

Processing tickers:  54%|█████▎    | 3627/6774 [12:22<10:27,  5.01it/s]

Processing tickers:  54%|█████▎    | 3628/6774 [12:22<10:29,  4.99it/s]

Processing tickers:  54%|█████▎    | 3629/6774 [12:23<10:29,  4.99it/s]

Processing tickers:  54%|█████▎    | 3630/6774 [12:23<10:36,  4.94it/s]

Processing tickers:  54%|█████▎    | 3631/6774 [12:23<10:30,  4.99it/s]

Processing tickers:  54%|█████▎    | 3632/6774 [12:23<10:30,  4.99it/s]

Processing tickers:  54%|█████▎    | 3633/6774 [12:23<10:28,  5.00it/s]

Processing tickers:  54%|█████▎    | 3634/6774 [12:24<10:29,  4.99it/s]

Processing tickers:  54%|█████▎    | 3635/6774 [12:24<10:33,  4.96it/s]

Processing tickers:  54%|█████▎    | 3636/6774 [12:24<10:29,  4.98it/s]

Processing tickers:  54%|█████▎    | 3637/6774 [12:24<10:27,  5.00it/s]

Processing tickers:  54%|█████▎    | 3638/6774 [12:24<10:26,  5.00it/s]

Processing tickers:  54%|█████▎    | 3639/6774 [12:25<10:26,  5.00it/s]

Processing tickers:  54%|█████▎    | 3640/6774 [12:25<10:26,  5.00it/s]

Processing tickers:  54%|█████▎    | 3641/6774 [12:25<10:26,  5.00it/s]

Processing tickers:  54%|█████▍    | 3642/6774 [12:25<10:32,  4.95it/s]

Processing tickers:  54%|█████▍    | 3643/6774 [12:25<10:39,  4.89it/s]

Processing tickers:  54%|█████▍    | 3644/6774 [12:26<10:35,  4.93it/s]

Processing tickers:  54%|█████▍    | 3645/6774 [12:26<10:32,  4.95it/s]

Processing tickers:  54%|█████▍    | 3646/6774 [12:26<10:28,  4.98it/s]

Processing tickers:  54%|█████▍    | 3647/6774 [12:26<10:24,  5.01it/s]

Processing tickers:  54%|█████▍    | 3648/6774 [12:26<10:33,  4.93it/s]

Processing tickers:  54%|█████▍    | 3649/6774 [12:27<10:32,  4.94it/s]

Processing tickers:  54%|█████▍    | 3650/6774 [12:27<10:31,  4.95it/s]

Processing tickers:  54%|█████▍    | 3651/6774 [12:27<11:20,  4.59it/s]

Processing tickers:  54%|█████▍    | 3652/6774 [12:27<11:03,  4.71it/s]

Processing tickers:  54%|█████▍    | 3653/6774 [12:27<10:50,  4.80it/s]

Processing tickers:  54%|█████▍    | 3654/6774 [12:28<10:42,  4.85it/s]

Processing tickers:  54%|█████▍    | 3655/6774 [12:28<10:38,  4.88it/s]

Processing tickers:  54%|█████▍    | 3656/6774 [12:28<10:33,  4.92it/s]

Processing tickers:  54%|█████▍    | 3657/6774 [12:28<10:31,  4.94it/s]

Processing tickers:  54%|█████▍    | 3658/6774 [12:28<10:28,  4.95it/s]

Processing tickers:  54%|█████▍    | 3659/6774 [12:29<10:25,  4.98it/s]

Processing tickers:  54%|█████▍    | 3660/6774 [12:29<10:25,  4.98it/s]

Processing tickers:  54%|█████▍    | 3661/6774 [12:29<10:53,  4.76it/s]

Processing tickers:  54%|█████▍    | 3662/6774 [12:29<10:57,  4.73it/s]

Processing tickers:  54%|█████▍    | 3663/6774 [12:29<10:43,  4.84it/s]

Processing tickers:  54%|█████▍    | 3664/6774 [12:30<10:34,  4.90it/s]

Processing tickers:  54%|█████▍    | 3665/6774 [12:30<10:46,  4.81it/s]

Processing tickers:  54%|█████▍    | 3666/6774 [12:30<10:38,  4.87it/s]

Processing tickers:  54%|█████▍    | 3667/6774 [12:30<10:31,  4.92it/s]

Processing tickers:  54%|█████▍    | 3668/6774 [12:30<10:25,  4.97it/s]

Processing tickers:  54%|█████▍    | 3669/6774 [12:31<10:37,  4.87it/s]

Processing tickers:  54%|█████▍    | 3670/6774 [12:31<10:30,  4.92it/s]

Processing tickers:  54%|█████▍    | 3671/6774 [12:31<10:30,  4.92it/s]

Processing tickers:  54%|█████▍    | 3672/6774 [12:31<10:27,  4.95it/s]

Processing tickers:  54%|█████▍    | 3673/6774 [12:31<10:27,  4.94it/s]

Processing tickers:  54%|█████▍    | 3674/6774 [12:32<10:22,  4.98it/s]

Processing tickers:  54%|█████▍    | 3675/6774 [12:32<10:17,  5.02it/s]

Processing tickers:  54%|█████▍    | 3676/6774 [12:32<10:35,  4.87it/s]

Processing tickers:  54%|█████▍    | 3677/6774 [12:32<10:48,  4.77it/s]

Processing tickers:  54%|█████▍    | 3678/6774 [12:33<10:39,  4.84it/s]

Processing tickers:  54%|█████▍    | 3679/6774 [12:33<10:35,  4.87it/s]

Processing tickers:  54%|█████▍    | 3680/6774 [12:33<10:29,  4.91it/s]

Processing tickers:  54%|█████▍    | 3681/6774 [12:33<10:24,  4.95it/s]

Processing tickers:  54%|█████▍    | 3682/6774 [12:33<10:21,  4.97it/s]

Processing tickers:  54%|█████▍    | 3683/6774 [12:34<10:27,  4.93it/s]

Processing tickers:  54%|█████▍    | 3684/6774 [12:34<10:42,  4.81it/s]

Processing tickers:  54%|█████▍    | 3685/6774 [12:34<10:38,  4.84it/s]

Processing tickers:  54%|█████▍    | 3686/6774 [12:34<10:38,  4.83it/s]

Processing tickers:  54%|█████▍    | 3687/6774 [12:34<10:52,  4.73it/s]

Processing tickers:  54%|█████▍    | 3688/6774 [12:35<10:54,  4.71it/s]

Processing tickers:  54%|█████▍    | 3689/6774 [12:35<11:03,  4.65it/s]

Processing tickers:  54%|█████▍    | 3690/6774 [12:35<10:45,  4.78it/s]

Processing tickers:  54%|█████▍    | 3691/6774 [12:35<10:58,  4.68it/s]

Processing tickers:  55%|█████▍    | 3692/6774 [12:35<10:46,  4.77it/s]

Processing tickers:  55%|█████▍    | 3693/6774 [12:36<10:40,  4.81it/s]

Processing tickers:  55%|█████▍    | 3694/6774 [12:36<10:37,  4.83it/s]

Processing tickers:  55%|█████▍    | 3695/6774 [12:36<10:33,  4.86it/s]

Processing tickers:  55%|█████▍    | 3696/6774 [12:36<10:49,  4.74it/s]

Processing tickers:  55%|█████▍    | 3697/6774 [12:36<10:38,  4.82it/s]

Processing tickers:  55%|█████▍    | 3698/6774 [12:37<10:30,  4.88it/s]

Processing tickers:  55%|█████▍    | 3699/6774 [12:37<10:24,  4.93it/s]

Processing tickers:  55%|█████▍    | 3700/6774 [12:37<10:20,  4.95it/s]

Processing tickers:  55%|█████▍    | 3701/6774 [12:37<10:17,  4.98it/s]

Processing tickers:  55%|█████▍    | 3702/6774 [12:37<10:14,  5.00it/s]

Processing tickers:  55%|█████▍    | 3703/6774 [12:38<10:12,  5.02it/s]

Processing tickers:  55%|█████▍    | 3704/6774 [12:38<10:13,  5.01it/s]

Processing tickers:  55%|█████▍    | 3705/6774 [12:38<10:27,  4.89it/s]

Processing tickers:  55%|█████▍    | 3706/6774 [12:38<10:23,  4.92it/s]

Processing tickers:  55%|█████▍    | 3707/6774 [12:38<10:22,  4.93it/s]

Processing tickers:  55%|█████▍    | 3708/6774 [12:39<10:30,  4.86it/s]

Processing tickers:  55%|█████▍    | 3709/6774 [12:39<10:31,  4.86it/s]

Processing tickers:  55%|█████▍    | 3710/6774 [12:39<10:37,  4.81it/s]

Processing tickers:  55%|█████▍    | 3711/6774 [12:39<10:29,  4.87it/s]

Processing tickers:  55%|█████▍    | 3712/6774 [12:40<10:42,  4.76it/s]

Processing tickers:  55%|█████▍    | 3713/6774 [12:40<10:32,  4.84it/s]

Processing tickers:  55%|█████▍    | 3714/6774 [12:40<10:25,  4.89it/s]

Processing tickers:  55%|█████▍    | 3715/6774 [12:40<10:23,  4.90it/s]

Processing tickers:  55%|█████▍    | 3716/6774 [12:40<10:21,  4.92it/s]

Processing tickers:  55%|█████▍    | 3717/6774 [12:41<10:15,  4.96it/s]

Processing tickers:  55%|█████▍    | 3718/6774 [12:41<10:23,  4.90it/s]

Processing tickers:  55%|█████▍    | 3719/6774 [12:41<10:16,  4.96it/s]

Processing tickers:  55%|█████▍    | 3720/6774 [12:41<11:42,  4.35it/s]

Processing tickers:  55%|█████▍    | 3721/6774 [12:41<11:19,  4.49it/s]

Processing tickers:  55%|█████▍    | 3722/6774 [12:42<10:59,  4.63it/s]

Processing tickers:  55%|█████▍    | 3723/6774 [12:42<10:45,  4.73it/s]

Processing tickers:  55%|█████▍    | 3724/6774 [12:42<10:32,  4.83it/s]

Processing tickers:  55%|█████▍    | 3725/6774 [12:42<10:26,  4.87it/s]

Processing tickers:  55%|█████▌    | 3726/6774 [12:42<10:16,  4.94it/s]

Processing tickers:  55%|█████▌    | 3727/6774 [12:43<10:13,  4.97it/s]

Processing tickers:  55%|█████▌    | 3728/6774 [12:43<10:18,  4.93it/s]

Processing tickers:  55%|█████▌    | 3729/6774 [12:43<10:26,  4.86it/s]

Processing tickers:  55%|█████▌    | 3730/6774 [12:43<10:18,  4.93it/s]

Processing tickers:  55%|█████▌    | 3731/6774 [12:43<10:18,  4.92it/s]

Processing tickers:  55%|█████▌    | 3732/6774 [12:44<10:15,  4.94it/s]

Processing tickers:  55%|█████▌    | 3733/6774 [12:44<10:18,  4.92it/s]

Processing tickers:  55%|█████▌    | 3734/6774 [12:44<10:15,  4.94it/s]

Processing tickers:  55%|█████▌    | 3735/6774 [12:44<10:18,  4.91it/s]

Processing tickers:  55%|█████▌    | 3736/6774 [12:44<10:14,  4.94it/s]

Processing tickers:  55%|█████▌    | 3737/6774 [12:45<10:14,  4.94it/s]

Processing tickers:  55%|█████▌    | 3738/6774 [12:45<10:10,  4.97it/s]

Processing tickers:  55%|█████▌    | 3739/6774 [12:45<10:22,  4.87it/s]

Processing tickers:  55%|█████▌    | 3740/6774 [12:45<10:20,  4.89it/s]

Processing tickers:  55%|█████▌    | 3741/6774 [12:46<10:41,  4.73it/s]

Processing tickers:  55%|█████▌    | 3742/6774 [12:46<10:39,  4.74it/s]

Processing tickers:  55%|█████▌    | 3743/6774 [12:46<10:27,  4.83it/s]

Processing tickers:  55%|█████▌    | 3744/6774 [12:46<10:21,  4.87it/s]

Processing tickers:  55%|█████▌    | 3745/6774 [12:46<10:20,  4.88it/s]

Processing tickers:  55%|█████▌    | 3746/6774 [12:47<10:19,  4.88it/s]

Processing tickers:  55%|█████▌    | 3747/6774 [12:47<10:26,  4.83it/s]

Processing tickers:  55%|█████▌    | 3748/6774 [12:47<10:16,  4.90it/s]

Processing tickers:  55%|█████▌    | 3749/6774 [12:47<10:11,  4.95it/s]

Processing tickers:  55%|█████▌    | 3750/6774 [12:47<10:08,  4.97it/s]

Processing tickers:  55%|█████▌    | 3751/6774 [12:48<10:09,  4.96it/s]

Processing tickers:  55%|█████▌    | 3752/6774 [12:48<10:23,  4.85it/s]

Processing tickers:  55%|█████▌    | 3753/6774 [12:48<10:15,  4.91it/s]

Processing tickers:  55%|█████▌    | 3754/6774 [12:48<10:15,  4.91it/s]

Processing tickers:  55%|█████▌    | 3755/6774 [12:48<10:11,  4.94it/s]

Processing tickers:  55%|█████▌    | 3756/6774 [12:49<10:07,  4.97it/s]

Processing tickers:  55%|█████▌    | 3757/6774 [12:49<10:06,  4.98it/s]

Processing tickers:  55%|█████▌    | 3758/6774 [12:49<10:34,  4.75it/s]

Processing tickers:  55%|█████▌    | 3759/6774 [12:49<10:25,  4.82it/s]

Processing tickers:  56%|█████▌    | 3760/6774 [12:49<10:17,  4.88it/s]

Processing tickers:  56%|█████▌    | 3761/6774 [12:50<10:19,  4.86it/s]

Processing tickers:  56%|█████▌    | 3762/6774 [12:50<10:11,  4.92it/s]

Processing tickers:  56%|█████▌    | 3763/6774 [12:50<10:20,  4.85it/s]

Processing tickers:  56%|█████▌    | 3764/6774 [12:50<10:16,  4.88it/s]

Processing tickers:  56%|█████▌    | 3765/6774 [12:50<10:09,  4.93it/s]

Processing tickers:  56%|█████▌    | 3766/6774 [12:51<10:21,  4.84it/s]

Processing tickers:  56%|█████▌    | 3767/6774 [12:51<10:33,  4.75it/s]

Processing tickers:  56%|█████▌    | 3768/6774 [12:51<10:21,  4.83it/s]

Processing tickers:  56%|█████▌    | 3769/6774 [12:51<10:19,  4.85it/s]

Processing tickers:  56%|█████▌    | 3770/6774 [12:51<10:18,  4.85it/s]

Processing tickers:  56%|█████▌    | 3771/6774 [12:52<10:09,  4.93it/s]

Processing tickers:  56%|█████▌    | 3772/6774 [12:52<10:06,  4.95it/s]

Processing tickers:  56%|█████▌    | 3773/6774 [12:52<10:25,  4.79it/s]

Processing tickers:  56%|█████▌    | 3774/6774 [12:52<10:16,  4.87it/s]

Processing tickers:  56%|█████▌    | 3775/6774 [12:52<10:06,  4.94it/s]

Processing tickers:  56%|█████▌    | 3776/6774 [12:53<10:05,  4.95it/s]

Processing tickers:  56%|█████▌    | 3777/6774 [12:53<10:00,  4.99it/s]

Processing tickers:  56%|█████▌    | 3778/6774 [12:53<10:04,  4.96it/s]

Processing tickers:  56%|█████▌    | 3779/6774 [12:53<10:00,  4.98it/s]

Processing tickers:  56%|█████▌    | 3780/6774 [12:53<09:58,  5.00it/s]

Processing tickers:  56%|█████▌    | 3781/6774 [12:54<10:14,  4.87it/s]

Processing tickers:  56%|█████▌    | 3782/6774 [12:54<10:10,  4.90it/s]

Processing tickers:  56%|█████▌    | 3783/6774 [12:54<10:18,  4.83it/s]

Processing tickers:  56%|█████▌    | 3784/6774 [12:54<10:13,  4.87it/s]

Processing tickers:  56%|█████▌    | 3785/6774 [12:54<10:08,  4.91it/s]

Processing tickers:  56%|█████▌    | 3786/6774 [12:55<10:04,  4.94it/s]

Processing tickers:  56%|█████▌    | 3787/6774 [12:55<09:57,  5.00it/s]

Processing tickers:  56%|█████▌    | 3788/6774 [12:55<10:20,  4.81it/s]

Processing tickers:  56%|█████▌    | 3789/6774 [12:55<10:13,  4.87it/s]

Processing tickers:  56%|█████▌    | 3790/6774 [12:56<10:04,  4.93it/s]

Processing tickers:  56%|█████▌    | 3791/6774 [12:56<10:07,  4.91it/s]

Processing tickers:  56%|█████▌    | 3792/6774 [12:56<10:03,  4.94it/s]

Processing tickers:  56%|█████▌    | 3793/6774 [12:56<10:04,  4.93it/s]

Processing tickers:  56%|█████▌    | 3794/6774 [12:56<09:58,  4.98it/s]

Processing tickers:  56%|█████▌    | 3795/6774 [12:57<10:05,  4.92it/s]

Processing tickers:  56%|█████▌    | 3796/6774 [12:57<10:00,  4.96it/s]

Processing tickers:  56%|█████▌    | 3797/6774 [12:57<09:55,  5.00it/s]

Processing tickers:  56%|█████▌    | 3798/6774 [12:57<09:53,  5.02it/s]

Processing tickers:  56%|█████▌    | 3799/6774 [12:57<09:58,  4.97it/s]

Processing tickers:  56%|█████▌    | 3800/6774 [12:58<09:58,  4.97it/s]

Processing tickers:  56%|█████▌    | 3801/6774 [12:58<10:10,  4.87it/s]

Processing tickers:  56%|█████▌    | 3802/6774 [12:58<10:12,  4.86it/s]

Processing tickers:  56%|█████▌    | 3803/6774 [12:58<10:06,  4.90it/s]

Processing tickers:  56%|█████▌    | 3804/6774 [12:58<10:03,  4.92it/s]

Processing tickers:  56%|█████▌    | 3805/6774 [12:59<09:59,  4.95it/s]

Processing tickers:  56%|█████▌    | 3806/6774 [12:59<09:56,  4.97it/s]

Processing tickers:  56%|█████▌    | 3807/6774 [12:59<10:24,  4.75it/s]

Processing tickers:  56%|█████▌    | 3808/6774 [12:59<10:35,  4.67it/s]

Processing tickers:  56%|█████▌    | 3809/6774 [12:59<10:32,  4.68it/s]

Processing tickers:  56%|█████▌    | 3810/6774 [13:00<10:33,  4.68it/s]

Processing tickers:  56%|█████▋    | 3811/6774 [13:00<10:21,  4.76it/s]

Processing tickers:  56%|█████▋    | 3812/6774 [13:00<10:14,  4.82it/s]

Processing tickers:  56%|█████▋    | 3813/6774 [13:00<10:25,  4.73it/s]

Processing tickers:  56%|█████▋    | 3814/6774 [13:00<10:18,  4.79it/s]

Processing tickers:  56%|█████▋    | 3815/6774 [13:01<10:12,  4.83it/s]

Processing tickers:  56%|█████▋    | 3816/6774 [13:01<10:10,  4.85it/s]

Processing tickers:  56%|█████▋    | 3817/6774 [13:01<10:09,  4.85it/s]

Processing tickers:  56%|█████▋    | 3818/6774 [13:01<10:04,  4.89it/s]

Processing tickers:  56%|█████▋    | 3819/6774 [13:01<09:57,  4.95it/s]

Processing tickers:  56%|█████▋    | 3820/6774 [13:02<10:17,  4.78it/s]

Processing tickers:  56%|█████▋    | 3821/6774 [13:02<10:10,  4.84it/s]

Processing tickers:  56%|█████▋    | 3822/6774 [13:02<10:05,  4.87it/s]

Processing tickers:  56%|█████▋    | 3823/6774 [13:02<10:08,  4.85it/s]

Processing tickers:  56%|█████▋    | 3824/6774 [13:02<10:01,  4.90it/s]

Processing tickers:  56%|█████▋    | 3825/6774 [13:03<09:55,  4.95it/s]

Processing tickers:  56%|█████▋    | 3826/6774 [13:03<09:54,  4.96it/s]

Processing tickers:  56%|█████▋    | 3827/6774 [13:03<09:53,  4.97it/s]

Processing tickers:  57%|█████▋    | 3828/6774 [13:03<09:56,  4.94it/s]

Processing tickers:  57%|█████▋    | 3829/6774 [13:04<09:54,  4.95it/s]

Processing tickers:  57%|█████▋    | 3830/6774 [13:04<09:55,  4.94it/s]

Processing tickers:  57%|█████▋    | 3831/6774 [13:04<09:55,  4.94it/s]

Processing tickers:  57%|█████▋    | 3832/6774 [13:04<09:50,  4.98it/s]

Processing tickers:  57%|█████▋    | 3833/6774 [13:04<09:48,  5.00it/s]

Processing tickers:  57%|█████▋    | 3834/6774 [13:05<09:53,  4.96it/s]

Processing tickers:  57%|█████▋    | 3835/6774 [13:05<09:52,  4.96it/s]

Processing tickers:  57%|█████▋    | 3836/6774 [13:05<09:53,  4.95it/s]

Processing tickers:  57%|█████▋    | 3837/6774 [13:05<09:50,  4.97it/s]

Processing tickers:  57%|█████▋    | 3838/6774 [13:05<09:50,  4.97it/s]

Processing tickers:  57%|█████▋    | 3839/6774 [13:06<10:04,  4.85it/s]

Processing tickers:  57%|█████▋    | 3840/6774 [13:06<10:02,  4.87it/s]

Processing tickers:  57%|█████▋    | 3841/6774 [13:06<09:55,  4.93it/s]

Processing tickers:  57%|█████▋    | 3842/6774 [13:06<09:51,  4.96it/s]

Processing tickers:  57%|█████▋    | 3843/6774 [13:06<09:51,  4.96it/s]

Processing tickers:  57%|█████▋    | 3844/6774 [13:07<09:53,  4.94it/s]

Processing tickers:  57%|█████▋    | 3845/6774 [13:07<09:51,  4.95it/s]

Processing tickers:  57%|█████▋    | 3846/6774 [13:07<09:51,  4.95it/s]

Processing tickers:  57%|█████▋    | 3847/6774 [13:07<09:48,  4.98it/s]

Processing tickers:  57%|█████▋    | 3848/6774 [13:07<10:13,  4.77it/s]

Processing tickers:  57%|█████▋    | 3849/6774 [13:08<10:15,  4.75it/s]

Processing tickers:  57%|█████▋    | 3850/6774 [13:08<10:03,  4.84it/s]

Processing tickers:  57%|█████▋    | 3851/6774 [13:08<10:01,  4.86it/s]

Processing tickers:  57%|█████▋    | 3852/6774 [13:08<09:58,  4.89it/s]

Processing tickers:  57%|█████▋    | 3853/6774 [13:08<09:51,  4.94it/s]

Processing tickers:  57%|█████▋    | 3854/6774 [13:09<09:46,  4.97it/s]

Processing tickers:  57%|█████▋    | 3855/6774 [13:09<09:53,  4.92it/s]

Processing tickers:  57%|█████▋    | 3856/6774 [13:09<09:54,  4.91it/s]

Processing tickers:  57%|█████▋    | 3857/6774 [13:09<09:51,  4.93it/s]

Processing tickers:  57%|█████▋    | 3858/6774 [13:09<09:51,  4.93it/s]

Processing tickers:  57%|█████▋    | 3859/6774 [13:10<09:44,  4.99it/s]

Processing tickers:  57%|█████▋    | 3860/6774 [13:10<09:47,  4.96it/s]

Processing tickers:  57%|█████▋    | 3861/6774 [13:10<09:50,  4.93it/s]

Processing tickers:  57%|█████▋    | 3862/6774 [13:10<09:47,  4.96it/s]

Processing tickers:  57%|█████▋    | 3863/6774 [13:10<09:54,  4.90it/s]

Processing tickers:  57%|█████▋    | 3864/6774 [13:11<09:52,  4.91it/s]

Processing tickers:  57%|█████▋    | 3865/6774 [13:11<09:47,  4.95it/s]

Processing tickers:  57%|█████▋    | 3866/6774 [13:11<10:08,  4.78it/s]

Processing tickers:  57%|█████▋    | 3867/6774 [13:11<10:00,  4.84it/s]

Processing tickers:  57%|█████▋    | 3868/6774 [13:11<09:58,  4.85it/s]

Processing tickers:  57%|█████▋    | 3869/6774 [13:12<10:06,  4.79it/s]

Processing tickers:  57%|█████▋    | 3870/6774 [13:12<10:03,  4.81it/s]

Processing tickers:  57%|█████▋    | 3871/6774 [13:12<10:05,  4.80it/s]

Processing tickers:  57%|█████▋    | 3872/6774 [13:12<09:58,  4.85it/s]

Processing tickers:  57%|█████▋    | 3873/6774 [13:12<10:03,  4.81it/s]

Processing tickers:  57%|█████▋    | 3874/6774 [13:13<09:55,  4.87it/s]

Processing tickers:  57%|█████▋    | 3875/6774 [13:13<09:48,  4.93it/s]

Processing tickers:  57%|█████▋    | 3876/6774 [13:13<09:54,  4.87it/s]

Processing tickers:  57%|█████▋    | 3877/6774 [13:13<09:51,  4.90it/s]

Processing tickers:  57%|█████▋    | 3878/6774 [13:13<09:46,  4.94it/s]

Processing tickers:  57%|█████▋    | 3879/6774 [13:14<10:13,  4.72it/s]

Processing tickers:  57%|█████▋    | 3880/6774 [13:14<10:16,  4.70it/s]

Processing tickers:  57%|█████▋    | 3881/6774 [13:14<10:08,  4.76it/s]

Processing tickers:  57%|█████▋    | 3882/6774 [13:14<10:02,  4.80it/s]

Processing tickers:  57%|█████▋    | 3883/6774 [13:15<09:56,  4.85it/s]

Processing tickers:  57%|█████▋    | 3884/6774 [13:15<09:51,  4.89it/s]

Processing tickers:  57%|█████▋    | 3885/6774 [13:15<09:45,  4.93it/s]

Processing tickers:  57%|█████▋    | 3886/6774 [13:15<09:41,  4.97it/s]

Processing tickers:  57%|█████▋    | 3887/6774 [13:15<09:42,  4.96it/s]

Processing tickers:  57%|█████▋    | 3888/6774 [13:16<09:40,  4.97it/s]

Processing tickers:  57%|█████▋    | 3889/6774 [13:16<09:41,  4.96it/s]

Processing tickers:  57%|█████▋    | 3890/6774 [13:16<09:39,  4.98it/s]

Processing tickers:  57%|█████▋    | 3891/6774 [13:16<09:57,  4.83it/s]

Processing tickers:  57%|█████▋    | 3892/6774 [13:16<09:49,  4.89it/s]

Processing tickers:  57%|█████▋    | 3893/6774 [13:17<09:45,  4.92it/s]

Processing tickers:  57%|█████▋    | 3894/6774 [13:17<09:46,  4.91it/s]

Processing tickers:  57%|█████▋    | 3895/6774 [13:17<09:52,  4.86it/s]

Processing tickers:  58%|█████▊    | 3896/6774 [13:17<09:48,  4.89it/s]

Processing tickers:  58%|█████▊    | 3897/6774 [13:17<09:44,  4.92it/s]

Processing tickers:  58%|█████▊    | 3898/6774 [13:18<09:47,  4.89it/s]

Processing tickers:  58%|█████▊    | 3899/6774 [13:18<09:50,  4.87it/s]

Processing tickers:  58%|█████▊    | 3900/6774 [13:18<09:48,  4.88it/s]

Processing tickers:  58%|█████▊    | 3901/6774 [13:18<09:47,  4.89it/s]

Processing tickers:  58%|█████▊    | 3902/6774 [13:18<09:44,  4.92it/s]

Processing tickers:  58%|█████▊    | 3903/6774 [13:19<09:40,  4.95it/s]

Processing tickers:  58%|█████▊    | 3904/6774 [13:19<09:38,  4.96it/s]

Processing tickers:  58%|█████▊    | 3905/6774 [13:19<09:40,  4.94it/s]

Processing tickers:  58%|█████▊    | 3906/6774 [13:19<09:43,  4.92it/s]

Processing tickers:  58%|█████▊    | 3907/6774 [13:19<09:52,  4.84it/s]

Processing tickers:  58%|█████▊    | 3908/6774 [13:20<09:45,  4.89it/s]

Processing tickers:  58%|█████▊    | 3909/6774 [13:20<09:48,  4.87it/s]

Processing tickers:  58%|█████▊    | 3910/6774 [13:20<09:40,  4.94it/s]

Processing tickers:  58%|█████▊    | 3911/6774 [13:20<09:39,  4.94it/s]

Processing tickers:  58%|█████▊    | 3912/6774 [13:20<09:37,  4.96it/s]

Processing tickers:  58%|█████▊    | 3913/6774 [13:21<09:37,  4.95it/s]

Processing tickers:  58%|█████▊    | 3914/6774 [13:21<09:34,  4.98it/s]

Processing tickers:  58%|█████▊    | 3915/6774 [13:21<09:31,  5.00it/s]

Processing tickers:  58%|█████▊    | 3916/6774 [13:21<09:31,  5.00it/s]

Processing tickers:  58%|█████▊    | 3917/6774 [13:21<09:28,  5.03it/s]

Processing tickers:  58%|█████▊    | 3918/6774 [13:22<09:31,  5.00it/s]

Processing tickers:  58%|█████▊    | 3919/6774 [13:22<09:30,  5.01it/s]

Processing tickers:  58%|█████▊    | 3920/6774 [13:22<09:28,  5.02it/s]

Processing tickers:  58%|█████▊    | 3921/6774 [13:22<09:26,  5.04it/s]

Processing tickers:  58%|█████▊    | 3922/6774 [13:22<09:24,  5.05it/s]

Processing tickers:  58%|█████▊    | 3923/6774 [13:23<09:27,  5.02it/s]

Processing tickers:  58%|█████▊    | 3924/6774 [13:23<09:25,  5.04it/s]

Processing tickers:  58%|█████▊    | 3925/6774 [13:23<09:26,  5.03it/s]

Processing tickers:  58%|█████▊    | 3926/6774 [13:23<09:31,  4.98it/s]

Processing tickers:  58%|█████▊    | 3927/6774 [13:23<09:29,  5.00it/s]

Processing tickers:  58%|█████▊    | 3928/6774 [13:24<09:35,  4.95it/s]

Processing tickers:  58%|█████▊    | 3929/6774 [13:24<09:38,  4.92it/s]

Processing tickers:  58%|█████▊    | 3930/6774 [13:24<09:34,  4.95it/s]

Processing tickers:  58%|█████▊    | 3931/6774 [13:24<09:37,  4.92it/s]

Processing tickers:  58%|█████▊    | 3932/6774 [13:24<09:37,  4.92it/s]

Processing tickers:  58%|█████▊    | 3933/6774 [13:25<09:33,  4.95it/s]

Processing tickers:  58%|█████▊    | 3934/6774 [13:25<09:36,  4.93it/s]

Processing tickers:  58%|█████▊    | 3935/6774 [13:25<09:31,  4.96it/s]

Processing tickers:  58%|█████▊    | 3936/6774 [13:25<09:33,  4.95it/s]

Processing tickers:  58%|█████▊    | 3937/6774 [13:25<09:35,  4.93it/s]

Processing tickers:  58%|█████▊    | 3938/6774 [13:26<09:28,  4.99it/s]

Processing tickers:  58%|█████▊    | 3939/6774 [13:26<09:37,  4.91it/s]

Processing tickers:  58%|█████▊    | 3940/6774 [13:26<09:37,  4.91it/s]

Processing tickers:  58%|█████▊    | 3941/6774 [13:26<09:36,  4.92it/s]

Processing tickers:  58%|█████▊    | 3942/6774 [13:26<09:40,  4.88it/s]

Processing tickers:  58%|█████▊    | 3943/6774 [13:27<09:43,  4.85it/s]

Processing tickers:  58%|█████▊    | 3944/6774 [13:27<09:36,  4.91it/s]

Processing tickers:  58%|█████▊    | 3945/6774 [13:27<09:34,  4.93it/s]

Processing tickers:  58%|█████▊    | 3946/6774 [13:27<09:56,  4.74it/s]

Processing tickers:  58%|█████▊    | 3947/6774 [13:28<09:47,  4.82it/s]

Processing tickers:  58%|█████▊    | 3948/6774 [13:28<09:51,  4.78it/s]

Processing tickers:  58%|█████▊    | 3949/6774 [13:28<09:40,  4.87it/s]

Processing tickers:  58%|█████▊    | 3950/6774 [13:28<09:36,  4.90it/s]

Processing tickers:  58%|█████▊    | 3951/6774 [13:28<09:35,  4.91it/s]

Processing tickers:  58%|█████▊    | 3952/6774 [13:29<09:29,  4.96it/s]

Processing tickers:  58%|█████▊    | 3953/6774 [13:29<09:24,  5.00it/s]

Processing tickers:  58%|█████▊    | 3954/6774 [13:29<09:25,  4.99it/s]

Processing tickers:  58%|█████▊    | 3955/6774 [13:29<09:23,  5.00it/s]

Processing tickers:  58%|█████▊    | 3956/6774 [13:29<09:23,  5.00it/s]

Processing tickers:  58%|█████▊    | 3957/6774 [13:30<09:21,  5.02it/s]

Processing tickers:  58%|█████▊    | 3958/6774 [13:30<09:22,  5.01it/s]

Processing tickers:  58%|█████▊    | 3959/6774 [13:30<09:20,  5.02it/s]

Processing tickers:  58%|█████▊    | 3960/6774 [13:30<09:29,  4.94it/s]

Processing tickers:  58%|█████▊    | 3961/6774 [13:30<09:29,  4.94it/s]

Processing tickers:  58%|█████▊    | 3962/6774 [13:31<09:23,  4.99it/s]

Processing tickers:  59%|█████▊    | 3963/6774 [13:31<09:23,  4.98it/s]

Processing tickers:  59%|█████▊    | 3964/6774 [13:31<09:32,  4.91it/s]

Processing tickers:  59%|█████▊    | 3965/6774 [13:31<09:25,  4.97it/s]

Processing tickers:  59%|█████▊    | 3966/6774 [13:31<09:22,  4.99it/s]

Processing tickers:  59%|█████▊    | 3967/6774 [13:32<09:28,  4.94it/s]

Processing tickers:  59%|█████▊    | 3968/6774 [13:32<09:25,  4.97it/s]

Processing tickers:  59%|█████▊    | 3969/6774 [13:32<09:23,  4.98it/s]

Processing tickers:  59%|█████▊    | 3970/6774 [13:32<09:21,  4.99it/s]

Processing tickers:  59%|█████▊    | 3971/6774 [13:32<09:20,  5.00it/s]

Processing tickers:  59%|█████▊    | 3972/6774 [13:33<09:34,  4.87it/s]

Processing tickers:  59%|█████▊    | 3973/6774 [13:33<09:31,  4.90it/s]

Processing tickers:  59%|█████▊    | 3974/6774 [13:33<09:38,  4.84it/s]

Processing tickers:  59%|█████▊    | 3975/6774 [13:33<09:29,  4.91it/s]

Processing tickers:  59%|█████▊    | 3976/6774 [13:33<09:30,  4.90it/s]

Processing tickers:  59%|█████▊    | 3977/6774 [13:34<09:25,  4.95it/s]

Processing tickers:  59%|█████▊    | 3978/6774 [13:34<09:26,  4.93it/s]

Processing tickers:  59%|█████▊    | 3979/6774 [13:34<09:36,  4.85it/s]

Processing tickers:  59%|█████▉    | 3980/6774 [13:34<09:34,  4.86it/s]

Processing tickers:  59%|█████▉    | 3981/6774 [13:34<09:40,  4.81it/s]

Processing tickers:  59%|█████▉    | 3982/6774 [13:35<09:30,  4.89it/s]

Processing tickers:  59%|█████▉    | 3983/6774 [13:35<09:26,  4.93it/s]

Processing tickers:  59%|█████▉    | 3984/6774 [13:35<09:29,  4.90it/s]

Processing tickers:  59%|█████▉    | 3985/6774 [13:35<09:58,  4.66it/s]

Processing tickers:  59%|█████▉    | 3986/6774 [13:35<09:46,  4.76it/s]

Processing tickers:  59%|█████▉    | 3987/6774 [13:36<09:45,  4.76it/s]

Processing tickers:  59%|█████▉    | 3988/6774 [13:36<09:36,  4.83it/s]

Processing tickers:  59%|█████▉    | 3989/6774 [13:36<09:30,  4.88it/s]

Processing tickers:  59%|█████▉    | 3990/6774 [13:36<09:39,  4.81it/s]

Processing tickers:  59%|█████▉    | 3991/6774 [13:36<09:33,  4.85it/s]

Processing tickers:  59%|█████▉    | 3992/6774 [13:37<09:29,  4.89it/s]

Processing tickers:  59%|█████▉    | 3993/6774 [13:37<09:28,  4.89it/s]

Processing tickers:  59%|█████▉    | 3994/6774 [13:37<09:23,  4.93it/s]

Processing tickers:  59%|█████▉    | 3995/6774 [13:37<09:18,  4.98it/s]

Processing tickers:  59%|█████▉    | 3996/6774 [13:38<09:47,  4.73it/s]

Processing tickers:  59%|█████▉    | 3997/6774 [13:38<09:39,  4.79it/s]

Processing tickers:  59%|█████▉    | 3998/6774 [13:38<09:30,  4.87it/s]

Processing tickers:  59%|█████▉    | 3999/6774 [13:38<09:23,  4.92it/s]

Processing tickers:  59%|█████▉    | 4000/6774 [13:38<09:22,  4.93it/s]

Processing tickers:  59%|█████▉    | 4001/6774 [13:39<09:25,  4.90it/s]

Processing tickers:  59%|█████▉    | 4002/6774 [13:39<09:19,  4.95it/s]

Processing tickers:  59%|█████▉    | 4003/6774 [13:39<09:30,  4.86it/s]

Processing tickers:  59%|█████▉    | 4004/6774 [13:39<09:22,  4.92it/s]

Processing tickers:  59%|█████▉    | 4005/6774 [13:39<09:23,  4.91it/s]

Processing tickers:  59%|█████▉    | 4006/6774 [13:40<09:23,  4.91it/s]

Processing tickers:  59%|█████▉    | 4007/6774 [13:40<09:21,  4.93it/s]

Processing tickers:  59%|█████▉    | 4008/6774 [13:40<09:18,  4.95it/s]

Processing tickers:  59%|█████▉    | 4009/6774 [13:40<09:14,  4.99it/s]

Processing tickers:  59%|█████▉    | 4010/6774 [13:40<09:11,  5.01it/s]

Processing tickers:  59%|█████▉    | 4011/6774 [13:41<09:09,  5.03it/s]

Processing tickers:  59%|█████▉    | 4012/6774 [13:41<09:07,  5.04it/s]

Processing tickers:  59%|█████▉    | 4013/6774 [13:41<09:08,  5.04it/s]

Processing tickers:  59%|█████▉    | 4014/6774 [13:41<09:11,  5.00it/s]

Processing tickers:  59%|█████▉    | 4015/6774 [13:41<09:16,  4.96it/s]

Processing tickers:  59%|█████▉    | 4016/6774 [13:42<09:15,  4.96it/s]

Processing tickers:  59%|█████▉    | 4017/6774 [13:42<09:15,  4.96it/s]

Processing tickers:  59%|█████▉    | 4018/6774 [13:42<09:12,  4.99it/s]

Processing tickers:  59%|█████▉    | 4019/6774 [13:42<09:07,  5.03it/s]

Processing tickers:  59%|█████▉    | 4020/6774 [13:42<09:08,  5.02it/s]

Processing tickers:  59%|█████▉    | 4021/6774 [13:43<09:10,  5.00it/s]

Processing tickers:  59%|█████▉    | 4022/6774 [13:43<09:09,  5.01it/s]

Processing tickers:  59%|█████▉    | 4023/6774 [13:43<09:24,  4.87it/s]

Processing tickers:  59%|█████▉    | 4024/6774 [13:43<09:22,  4.89it/s]

Processing tickers:  59%|█████▉    | 4025/6774 [13:43<09:19,  4.91it/s]

Processing tickers:  59%|█████▉    | 4026/6774 [13:44<09:16,  4.94it/s]

Processing tickers:  59%|█████▉    | 4027/6774 [13:44<09:16,  4.93it/s]

Processing tickers:  59%|█████▉    | 4028/6774 [13:44<09:14,  4.95it/s]

Processing tickers:  59%|█████▉    | 4029/6774 [13:44<09:17,  4.92it/s]

Processing tickers:  59%|█████▉    | 4030/6774 [13:44<09:20,  4.90it/s]

Processing tickers:  60%|█████▉    | 4031/6774 [13:45<09:33,  4.78it/s]

Processing tickers:  60%|█████▉    | 4032/6774 [13:45<09:23,  4.87it/s]

Processing tickers:  60%|█████▉    | 4033/6774 [13:45<09:33,  4.78it/s]

Processing tickers:  60%|█████▉    | 4034/6774 [13:45<09:23,  4.86it/s]

Processing tickers:  60%|█████▉    | 4035/6774 [13:45<09:23,  4.86it/s]

Processing tickers:  60%|█████▉    | 4036/6774 [13:46<09:21,  4.88it/s]

Processing tickers:  60%|█████▉    | 4037/6774 [13:46<09:34,  4.76it/s]

Processing tickers:  60%|█████▉    | 4038/6774 [13:46<09:24,  4.85it/s]

Processing tickers:  60%|█████▉    | 4039/6774 [13:46<09:22,  4.86it/s]

Processing tickers:  60%|█████▉    | 4040/6774 [13:46<09:20,  4.88it/s]

Processing tickers:  60%|█████▉    | 4041/6774 [13:47<09:16,  4.91it/s]

Processing tickers:  60%|█████▉    | 4042/6774 [13:47<09:33,  4.77it/s]

Processing tickers:  60%|█████▉    | 4043/6774 [13:47<09:24,  4.84it/s]

Processing tickers:  60%|█████▉    | 4044/6774 [13:47<09:19,  4.88it/s]

Processing tickers:  60%|█████▉    | 4045/6774 [13:47<09:15,  4.91it/s]

Processing tickers:  60%|█████▉    | 4046/6774 [13:48<09:16,  4.90it/s]

Processing tickers:  60%|█████▉    | 4047/6774 [13:48<09:13,  4.93it/s]

Processing tickers:  60%|█████▉    | 4048/6774 [13:48<09:13,  4.92it/s]

Processing tickers:  60%|█████▉    | 4049/6774 [13:48<09:25,  4.82it/s]

Processing tickers:  60%|█████▉    | 4050/6774 [13:48<09:24,  4.83it/s]

Processing tickers:  60%|█████▉    | 4051/6774 [13:49<09:18,  4.87it/s]

Processing tickers:  60%|█████▉    | 4052/6774 [13:49<09:21,  4.85it/s]

Processing tickers:  60%|█████▉    | 4053/6774 [13:49<09:23,  4.83it/s]

Processing tickers:  60%|█████▉    | 4054/6774 [13:49<09:17,  4.88it/s]

Processing tickers:  60%|█████▉    | 4055/6774 [13:50<09:13,  4.91it/s]

Processing tickers:  60%|█████▉    | 4056/6774 [13:50<09:14,  4.90it/s]

Processing tickers:  60%|█████▉    | 4057/6774 [13:50<09:11,  4.92it/s]

Processing tickers:  60%|█████▉    | 4058/6774 [13:50<09:09,  4.94it/s]

Processing tickers:  60%|█████▉    | 4059/6774 [13:50<09:03,  5.00it/s]

Processing tickers:  60%|█████▉    | 4060/6774 [13:51<09:03,  4.99it/s]

Processing tickers:  60%|█████▉    | 4061/6774 [13:51<09:15,  4.89it/s]

Processing tickers:  60%|█████▉    | 4062/6774 [13:51<09:08,  4.94it/s]

Processing tickers:  60%|█████▉    | 4063/6774 [13:51<09:08,  4.94it/s]

Processing tickers:  60%|█████▉    | 4064/6774 [13:51<09:05,  4.97it/s]

Processing tickers:  60%|██████    | 4065/6774 [13:52<09:00,  5.02it/s]

Processing tickers:  60%|██████    | 4066/6774 [13:52<08:59,  5.02it/s]

Processing tickers:  60%|██████    | 4067/6774 [13:52<09:01,  5.00it/s]

Processing tickers:  60%|██████    | 4068/6774 [13:52<09:01,  5.00it/s]

Processing tickers:  60%|██████    | 4069/6774 [13:52<09:04,  4.97it/s]

Processing tickers:  60%|██████    | 4070/6774 [13:53<09:00,  5.00it/s]

Processing tickers:  60%|██████    | 4071/6774 [13:53<09:02,  4.98it/s]

Processing tickers:  60%|██████    | 4072/6774 [13:53<09:02,  4.98it/s]

Processing tickers:  60%|██████    | 4073/6774 [13:53<09:06,  4.94it/s]

Processing tickers:  60%|██████    | 4074/6774 [13:53<09:03,  4.96it/s]

Processing tickers:  60%|██████    | 4075/6774 [13:54<09:00,  5.00it/s]

Processing tickers:  60%|██████    | 4076/6774 [13:54<09:06,  4.94it/s]

Processing tickers:  60%|██████    | 4077/6774 [13:54<09:02,  4.97it/s]

Processing tickers:  60%|██████    | 4078/6774 [13:54<09:02,  4.97it/s]

Processing tickers:  60%|██████    | 4079/6774 [13:54<08:57,  5.02it/s]

Processing tickers:  60%|██████    | 4080/6774 [13:55<09:03,  4.96it/s]

Processing tickers:  60%|██████    | 4081/6774 [13:55<09:00,  4.98it/s]

Processing tickers:  60%|██████    | 4082/6774 [13:55<08:58,  5.00it/s]

Processing tickers:  60%|██████    | 4083/6774 [13:55<09:00,  4.98it/s]

Processing tickers:  60%|██████    | 4084/6774 [13:55<09:02,  4.96it/s]

Processing tickers:  60%|██████    | 4085/6774 [13:56<09:11,  4.88it/s]

Processing tickers:  60%|██████    | 4086/6774 [13:56<09:04,  4.94it/s]

Processing tickers:  60%|██████    | 4087/6774 [13:56<09:21,  4.79it/s]

Processing tickers:  60%|██████    | 4088/6774 [13:56<09:11,  4.87it/s]

Processing tickers:  60%|██████    | 4089/6774 [13:56<09:04,  4.93it/s]

Processing tickers:  60%|██████    | 4090/6774 [13:57<09:02,  4.95it/s]

Processing tickers:  60%|██████    | 4091/6774 [13:57<09:10,  4.87it/s]

Processing tickers:  60%|██████    | 4092/6774 [13:57<09:18,  4.80it/s]

Processing tickers:  60%|██████    | 4093/6774 [13:57<09:08,  4.89it/s]

Processing tickers:  60%|██████    | 4094/6774 [13:57<09:07,  4.89it/s]

Processing tickers:  60%|██████    | 4095/6774 [13:58<09:17,  4.80it/s]

Processing tickers:  60%|██████    | 4096/6774 [13:58<09:18,  4.79it/s]

Processing tickers:  60%|██████    | 4097/6774 [13:58<09:09,  4.87it/s]

Processing tickers:  60%|██████    | 4098/6774 [13:58<09:04,  4.92it/s]

Processing tickers:  61%|██████    | 4099/6774 [13:58<09:01,  4.94it/s]

Processing tickers:  61%|██████    | 4100/6774 [13:59<08:57,  4.97it/s]

Processing tickers:  61%|██████    | 4101/6774 [13:59<08:55,  4.99it/s]

Processing tickers:  61%|██████    | 4102/6774 [13:59<08:54,  5.00it/s]

Processing tickers:  61%|██████    | 4103/6774 [13:59<08:55,  4.99it/s]

Processing tickers:  61%|██████    | 4104/6774 [13:59<08:55,  4.98it/s]

Processing tickers:  61%|██████    | 4105/6774 [14:00<08:57,  4.97it/s]

Processing tickers:  61%|██████    | 4106/6774 [14:00<09:09,  4.86it/s]

Processing tickers:  61%|██████    | 4107/6774 [14:00<09:11,  4.84it/s]

Processing tickers:  61%|██████    | 4108/6774 [14:00<09:05,  4.89it/s]

Processing tickers:  61%|██████    | 4109/6774 [14:00<09:02,  4.91it/s]

Processing tickers:  61%|██████    | 4110/6774 [14:01<09:20,  4.75it/s]

Processing tickers:  61%|██████    | 4111/6774 [14:01<09:07,  4.86it/s]

Processing tickers:  61%|██████    | 4112/6774 [14:01<09:09,  4.85it/s]

Processing tickers:  61%|██████    | 4113/6774 [14:01<09:03,  4.89it/s]

Processing tickers:  61%|██████    | 4114/6774 [14:01<09:06,  4.87it/s]

Processing tickers:  61%|██████    | 4115/6774 [14:02<09:10,  4.83it/s]

Processing tickers:  61%|██████    | 4116/6774 [14:02<09:17,  4.77it/s]

Processing tickers:  61%|██████    | 4117/6774 [14:02<09:07,  4.85it/s]

Processing tickers:  61%|██████    | 4118/6774 [14:02<09:02,  4.89it/s]

Processing tickers:  61%|██████    | 4119/6774 [14:03<09:11,  4.81it/s]

Processing tickers:  61%|██████    | 4120/6774 [14:03<09:07,  4.85it/s]

Processing tickers:  61%|██████    | 4121/6774 [14:03<09:03,  4.89it/s]

Processing tickers:  61%|██████    | 4122/6774 [14:03<09:03,  4.88it/s]

Processing tickers:  61%|██████    | 4123/6774 [14:03<08:59,  4.91it/s]

Processing tickers:  61%|██████    | 4124/6774 [14:04<09:00,  4.90it/s]

Processing tickers:  61%|██████    | 4125/6774 [14:04<08:53,  4.96it/s]

Processing tickers:  61%|██████    | 4126/6774 [14:04<08:51,  4.99it/s]

Processing tickers:  61%|██████    | 4127/6774 [14:04<08:56,  4.94it/s]

Processing tickers:  61%|██████    | 4128/6774 [14:04<08:54,  4.95it/s]

Processing tickers:  61%|██████    | 4129/6774 [14:05<08:55,  4.94it/s]

Processing tickers:  61%|██████    | 4130/6774 [14:05<09:03,  4.87it/s]

Processing tickers:  61%|██████    | 4131/6774 [14:05<08:55,  4.93it/s]

Processing tickers:  61%|██████    | 4132/6774 [14:05<08:57,  4.92it/s]

Processing tickers:  61%|██████    | 4133/6774 [14:05<08:52,  4.96it/s]

Processing tickers:  61%|██████    | 4134/6774 [14:06<08:53,  4.95it/s]

Processing tickers:  61%|██████    | 4135/6774 [14:06<09:04,  4.85it/s]

Processing tickers:  61%|██████    | 4136/6774 [14:06<09:20,  4.71it/s]

Processing tickers:  61%|██████    | 4137/6774 [14:06<09:11,  4.78it/s]

Processing tickers:  61%|██████    | 4138/6774 [14:06<09:08,  4.80it/s]

Processing tickers:  61%|██████    | 4139/6774 [14:07<09:18,  4.72it/s]

Processing tickers:  61%|██████    | 4140/6774 [14:07<09:09,  4.79it/s]

Processing tickers:  61%|██████    | 4141/6774 [14:07<09:02,  4.85it/s]

Processing tickers:  61%|██████    | 4142/6774 [14:07<08:55,  4.91it/s]

Processing tickers:  61%|██████    | 4143/6774 [14:07<08:51,  4.95it/s]

Processing tickers:  61%|██████    | 4144/6774 [14:08<08:49,  4.96it/s]

Processing tickers:  61%|██████    | 4145/6774 [14:08<08:48,  4.97it/s]

Processing tickers:  61%|██████    | 4146/6774 [14:08<08:53,  4.93it/s]

Processing tickers:  61%|██████    | 4147/6774 [14:08<08:53,  4.93it/s]

Processing tickers:  61%|██████    | 4148/6774 [14:08<08:50,  4.95it/s]

Processing tickers:  61%|██████    | 4149/6774 [14:09<09:00,  4.86it/s]

Processing tickers:  61%|██████▏   | 4150/6774 [14:09<08:58,  4.87it/s]

Processing tickers:  61%|██████▏   | 4151/6774 [14:09<08:57,  4.88it/s]

Processing tickers:  61%|██████▏   | 4152/6774 [14:09<08:56,  4.89it/s]

Processing tickers:  61%|██████▏   | 4153/6774 [14:09<08:51,  4.93it/s]

Processing tickers:  61%|██████▏   | 4154/6774 [14:10<08:50,  4.94it/s]

Processing tickers:  61%|██████▏   | 4155/6774 [14:10<08:54,  4.90it/s]

Processing tickers:  61%|██████▏   | 4156/6774 [14:10<08:53,  4.90it/s]

Processing tickers:  61%|██████▏   | 4157/6774 [14:10<08:50,  4.93it/s]

Processing tickers:  61%|██████▏   | 4158/6774 [14:10<08:48,  4.95it/s]

Processing tickers:  61%|██████▏   | 4159/6774 [14:11<08:48,  4.95it/s]

Processing tickers:  61%|██████▏   | 4160/6774 [14:11<08:46,  4.97it/s]

Processing tickers:  61%|██████▏   | 4161/6774 [14:11<08:42,  5.00it/s]

Processing tickers:  61%|██████▏   | 4162/6774 [14:11<08:39,  5.02it/s]

Processing tickers:  61%|██████▏   | 4163/6774 [14:11<08:40,  5.01it/s]

Processing tickers:  61%|██████▏   | 4164/6774 [14:12<08:49,  4.93it/s]

Processing tickers:  61%|██████▏   | 4165/6774 [14:12<08:45,  4.96it/s]

Processing tickers:  61%|██████▏   | 4166/6774 [14:12<08:42,  4.99it/s]

Processing tickers:  62%|██████▏   | 4167/6774 [14:12<08:49,  4.92it/s]

Processing tickers:  62%|██████▏   | 4168/6774 [14:13<08:58,  4.84it/s]

Processing tickers:  62%|██████▏   | 4169/6774 [14:13<08:52,  4.89it/s]

Processing tickers:  62%|██████▏   | 4170/6774 [14:13<08:49,  4.92it/s]

Processing tickers:  62%|██████▏   | 4171/6774 [14:13<08:47,  4.94it/s]

Processing tickers:  62%|██████▏   | 4172/6774 [14:13<08:47,  4.93it/s]

Processing tickers:  62%|██████▏   | 4173/6774 [14:14<08:46,  4.94it/s]

Processing tickers:  62%|██████▏   | 4174/6774 [14:14<08:43,  4.97it/s]

Processing tickers:  62%|██████▏   | 4175/6774 [14:14<08:41,  4.99it/s]

Processing tickers:  62%|██████▏   | 4176/6774 [14:14<08:38,  5.01it/s]

Processing tickers:  62%|██████▏   | 4177/6774 [14:14<08:41,  4.98it/s]

Processing tickers:  62%|██████▏   | 4178/6774 [14:15<08:38,  5.00it/s]

Processing tickers:  62%|██████▏   | 4179/6774 [14:15<08:45,  4.94it/s]

Processing tickers:  62%|██████▏   | 4180/6774 [14:15<08:45,  4.94it/s]

Processing tickers:  62%|██████▏   | 4181/6774 [14:15<08:46,  4.93it/s]

Processing tickers:  62%|██████▏   | 4182/6774 [14:15<08:43,  4.95it/s]

Processing tickers:  62%|██████▏   | 4183/6774 [14:16<08:46,  4.92it/s]

Processing tickers:  62%|██████▏   | 4184/6774 [14:16<08:49,  4.89it/s]

Processing tickers:  62%|██████▏   | 4185/6774 [14:16<08:43,  4.95it/s]

Processing tickers:  62%|██████▏   | 4186/6774 [14:16<08:56,  4.82it/s]

Processing tickers:  62%|██████▏   | 4187/6774 [14:16<08:54,  4.84it/s]

Processing tickers:  62%|██████▏   | 4188/6774 [14:17<08:49,  4.88it/s]

Processing tickers:  62%|██████▏   | 4189/6774 [14:17<08:47,  4.90it/s]

Processing tickers:  62%|██████▏   | 4190/6774 [14:17<08:47,  4.90it/s]

Processing tickers:  62%|██████▏   | 4191/6774 [14:17<08:45,  4.91it/s]

Processing tickers:  62%|██████▏   | 4192/6774 [14:17<08:39,  4.97it/s]

Processing tickers:  62%|██████▏   | 4193/6774 [14:18<08:40,  4.96it/s]

Processing tickers:  62%|██████▏   | 4194/6774 [14:18<08:47,  4.89it/s]

Processing tickers:  62%|██████▏   | 4195/6774 [14:18<08:48,  4.88it/s]

Processing tickers:  62%|██████▏   | 4196/6774 [14:18<08:43,  4.92it/s]

Processing tickers:  62%|██████▏   | 4197/6774 [14:18<08:40,  4.95it/s]

Processing tickers:  62%|██████▏   | 4198/6774 [14:19<08:37,  4.98it/s]

Processing tickers:  62%|██████▏   | 4199/6774 [14:19<08:35,  5.00it/s]

Processing tickers:  62%|██████▏   | 4200/6774 [14:19<08:45,  4.90it/s]

Processing tickers:  62%|██████▏   | 4201/6774 [14:19<08:40,  4.94it/s]

Processing tickers:  62%|██████▏   | 4202/6774 [14:19<08:35,  4.99it/s]

Processing tickers:  62%|██████▏   | 4203/6774 [14:20<08:34,  4.99it/s]

Processing tickers:  62%|██████▏   | 4204/6774 [14:20<08:33,  5.01it/s]

Processing tickers:  62%|██████▏   | 4205/6774 [14:20<08:36,  4.98it/s]

Processing tickers:  62%|██████▏   | 4206/6774 [14:20<08:34,  4.99it/s]

Processing tickers:  62%|██████▏   | 4207/6774 [14:20<08:30,  5.03it/s]

Processing tickers:  62%|██████▏   | 4208/6774 [14:21<08:27,  5.05it/s]

Processing tickers:  62%|██████▏   | 4209/6774 [14:21<08:31,  5.02it/s]

Processing tickers:  62%|██████▏   | 4210/6774 [14:21<08:39,  4.93it/s]

Processing tickers:  62%|██████▏   | 4211/6774 [14:21<08:36,  4.96it/s]

Processing tickers:  62%|██████▏   | 4212/6774 [14:21<08:33,  4.99it/s]

Processing tickers:  62%|██████▏   | 4213/6774 [14:22<08:32,  5.00it/s]

Processing tickers:  62%|██████▏   | 4214/6774 [14:22<08:34,  4.98it/s]

Processing tickers:  62%|██████▏   | 4215/6774 [14:22<08:40,  4.92it/s]

Processing tickers:  62%|██████▏   | 4216/6774 [14:22<08:38,  4.94it/s]

Processing tickers:  62%|██████▏   | 4217/6774 [14:22<08:31,  4.99it/s]

Processing tickers:  62%|██████▏   | 4218/6774 [14:23<08:30,  5.01it/s]

Processing tickers:  62%|██████▏   | 4219/6774 [14:23<08:29,  5.02it/s]

Processing tickers:  62%|██████▏   | 4220/6774 [14:23<08:39,  4.92it/s]

Processing tickers:  62%|██████▏   | 4221/6774 [14:23<08:37,  4.93it/s]

Processing tickers:  62%|██████▏   | 4222/6774 [14:23<08:44,  4.87it/s]

Processing tickers:  62%|██████▏   | 4223/6774 [14:24<08:38,  4.92it/s]

Processing tickers:  62%|██████▏   | 4224/6774 [14:24<08:36,  4.94it/s]

Processing tickers:  62%|██████▏   | 4225/6774 [14:24<08:35,  4.95it/s]

Processing tickers:  62%|██████▏   | 4226/6774 [14:24<08:32,  4.98it/s]

Processing tickers:  62%|██████▏   | 4227/6774 [14:24<08:30,  4.99it/s]

Processing tickers:  62%|██████▏   | 4228/6774 [14:25<08:42,  4.88it/s]

Processing tickers:  62%|██████▏   | 4229/6774 [14:25<08:37,  4.92it/s]

Processing tickers:  62%|██████▏   | 4230/6774 [14:25<08:32,  4.97it/s]

Processing tickers:  62%|██████▏   | 4231/6774 [14:25<08:30,  4.98it/s]

Processing tickers:  62%|██████▏   | 4232/6774 [14:25<08:27,  5.01it/s]

Processing tickers:  62%|██████▏   | 4233/6774 [14:26<08:27,  5.00it/s]

Processing tickers:  63%|██████▎   | 4234/6774 [14:26<08:46,  4.83it/s]

Processing tickers:  63%|██████▎   | 4235/6774 [14:26<08:54,  4.75it/s]

Processing tickers:  63%|██████▎   | 4236/6774 [14:26<09:01,  4.69it/s]

Processing tickers:  63%|██████▎   | 4237/6774 [14:26<08:51,  4.78it/s]

Processing tickers:  63%|██████▎   | 4238/6774 [14:27<09:05,  4.65it/s]

Processing tickers:  63%|██████▎   | 4239/6774 [14:27<08:57,  4.72it/s]

Processing tickers:  63%|██████▎   | 4240/6774 [14:27<08:47,  4.80it/s]

Processing tickers:  63%|██████▎   | 4241/6774 [14:27<08:50,  4.78it/s]

Processing tickers:  63%|██████▎   | 4242/6774 [14:28<08:43,  4.84it/s]

Processing tickers:  63%|██████▎   | 4243/6774 [14:28<08:42,  4.85it/s]

Processing tickers:  63%|██████▎   | 4244/6774 [14:28<08:39,  4.87it/s]

Processing tickers:  63%|██████▎   | 4245/6774 [14:28<08:32,  4.94it/s]

Processing tickers:  63%|██████▎   | 4246/6774 [14:28<08:37,  4.88it/s]

Processing tickers:  63%|██████▎   | 4247/6774 [14:29<08:35,  4.91it/s]

Processing tickers:  63%|██████▎   | 4248/6774 [14:29<08:39,  4.86it/s]

Processing tickers:  63%|██████▎   | 4249/6774 [14:29<08:44,  4.81it/s]

Processing tickers:  63%|██████▎   | 4250/6774 [14:29<08:35,  4.90it/s]

Processing tickers:  63%|██████▎   | 4251/6774 [14:29<08:43,  4.82it/s]

Processing tickers:  63%|██████▎   | 4252/6774 [14:30<08:38,  4.87it/s]

Processing tickers:  63%|██████▎   | 4253/6774 [14:30<08:32,  4.92it/s]

Processing tickers:  63%|██████▎   | 4254/6774 [14:30<08:37,  4.87it/s]

Processing tickers:  63%|██████▎   | 4255/6774 [14:30<08:40,  4.84it/s]

Processing tickers:  63%|██████▎   | 4256/6774 [14:30<08:38,  4.86it/s]

Processing tickers:  63%|██████▎   | 4257/6774 [14:31<08:33,  4.90it/s]

Processing tickers:  63%|██████▎   | 4258/6774 [14:31<08:50,  4.74it/s]

Processing tickers:  63%|██████▎   | 4259/6774 [14:31<08:44,  4.80it/s]

Processing tickers:  63%|██████▎   | 4260/6774 [14:31<08:37,  4.86it/s]

Processing tickers:  63%|██████▎   | 4261/6774 [14:31<08:31,  4.92it/s]

Processing tickers:  63%|██████▎   | 4262/6774 [14:32<08:29,  4.93it/s]

Processing tickers:  63%|██████▎   | 4263/6774 [14:32<08:28,  4.94it/s]

Processing tickers:  63%|██████▎   | 4264/6774 [14:32<08:23,  4.98it/s]

Processing tickers:  63%|██████▎   | 4265/6774 [14:32<08:24,  4.98it/s]

Processing tickers:  63%|██████▎   | 4266/6774 [14:32<08:25,  4.96it/s]

Processing tickers:  63%|██████▎   | 4267/6774 [14:33<08:25,  4.96it/s]

Processing tickers:  63%|██████▎   | 4268/6774 [14:33<08:43,  4.79it/s]

Processing tickers:  63%|██████▎   | 4269/6774 [14:33<08:36,  4.85it/s]

Processing tickers:  63%|██████▎   | 4270/6774 [14:33<08:41,  4.80it/s]

Processing tickers:  63%|██████▎   | 4271/6774 [14:33<08:36,  4.84it/s]

Processing tickers:  63%|██████▎   | 4272/6774 [14:34<08:32,  4.88it/s]

Processing tickers:  63%|██████▎   | 4273/6774 [14:34<08:35,  4.86it/s]

Processing tickers:  63%|██████▎   | 4274/6774 [14:34<09:22,  4.45it/s]

Processing tickers:  63%|██████▎   | 4275/6774 [14:34<09:02,  4.61it/s]

Processing tickers:  63%|██████▎   | 4276/6774 [14:35<08:48,  4.73it/s]

Processing tickers:  63%|██████▎   | 4277/6774 [14:35<08:42,  4.78it/s]

Processing tickers:  63%|██████▎   | 4278/6774 [14:35<08:35,  4.84it/s]

Processing tickers:  63%|██████▎   | 4279/6774 [14:35<08:30,  4.89it/s]

Processing tickers:  63%|██████▎   | 4280/6774 [14:35<08:38,  4.81it/s]

Processing tickers:  63%|██████▎   | 4281/6774 [14:36<08:32,  4.86it/s]

Processing tickers:  63%|██████▎   | 4282/6774 [14:36<08:28,  4.90it/s]

Processing tickers:  63%|██████▎   | 4283/6774 [14:36<08:38,  4.81it/s]

Processing tickers:  63%|██████▎   | 4284/6774 [14:36<08:35,  4.83it/s]

Processing tickers:  63%|██████▎   | 4285/6774 [14:36<08:46,  4.73it/s]

Processing tickers:  63%|██████▎   | 4286/6774 [14:37<08:50,  4.69it/s]

Processing tickers:  63%|██████▎   | 4287/6774 [14:37<08:39,  4.79it/s]

Processing tickers:  63%|██████▎   | 4288/6774 [14:37<08:35,  4.82it/s]

Processing tickers:  63%|██████▎   | 4289/6774 [14:37<08:34,  4.83it/s]

Processing tickers:  63%|██████▎   | 4290/6774 [14:37<08:47,  4.71it/s]

Processing tickers:  63%|██████▎   | 4291/6774 [14:38<08:34,  4.82it/s]

Processing tickers:  63%|██████▎   | 4292/6774 [14:38<08:29,  4.87it/s]

Processing tickers:  63%|██████▎   | 4293/6774 [14:38<08:44,  4.73it/s]

Processing tickers:  63%|██████▎   | 4294/6774 [14:38<08:35,  4.81it/s]

Processing tickers:  63%|██████▎   | 4295/6774 [14:38<08:32,  4.84it/s]

Processing tickers:  63%|██████▎   | 4296/6774 [14:39<08:27,  4.88it/s]

Processing tickers:  63%|██████▎   | 4297/6774 [14:39<08:23,  4.92it/s]

Processing tickers:  63%|██████▎   | 4298/6774 [14:39<08:30,  4.85it/s]

Processing tickers:  63%|██████▎   | 4299/6774 [14:39<08:40,  4.75it/s]

Processing tickers:  63%|██████▎   | 4300/6774 [14:40<08:31,  4.83it/s]

Processing tickers:  63%|██████▎   | 4301/6774 [14:40<08:27,  4.87it/s]

Processing tickers:  64%|██████▎   | 4302/6774 [14:40<08:35,  4.80it/s]

Processing tickers:  64%|██████▎   | 4303/6774 [14:40<08:29,  4.85it/s]

Processing tickers:  64%|██████▎   | 4304/6774 [14:40<08:25,  4.89it/s]

Processing tickers:  64%|██████▎   | 4305/6774 [14:41<08:22,  4.91it/s]

Processing tickers:  64%|██████▎   | 4306/6774 [14:41<08:34,  4.80it/s]

Processing tickers:  64%|██████▎   | 4307/6774 [14:41<08:32,  4.81it/s]

Processing tickers:  64%|██████▎   | 4308/6774 [14:41<08:44,  4.70it/s]

Processing tickers:  64%|██████▎   | 4309/6774 [14:41<08:38,  4.76it/s]

Processing tickers:  64%|██████▎   | 4310/6774 [14:42<08:32,  4.80it/s]

Processing tickers:  64%|██████▎   | 4311/6774 [14:42<08:35,  4.78it/s]

Processing tickers:  64%|██████▎   | 4312/6774 [14:42<08:28,  4.85it/s]

Processing tickers:  64%|██████▎   | 4313/6774 [14:42<08:26,  4.86it/s]

Processing tickers:  64%|██████▎   | 4314/6774 [14:42<08:24,  4.88it/s]

Processing tickers:  64%|██████▎   | 4315/6774 [14:43<08:20,  4.91it/s]

Processing tickers:  64%|██████▎   | 4316/6774 [14:43<08:19,  4.92it/s]

Processing tickers:  64%|██████▎   | 4317/6774 [14:43<08:28,  4.84it/s]

Processing tickers:  64%|██████▎   | 4318/6774 [14:43<08:21,  4.90it/s]

Processing tickers:  64%|██████▍   | 4319/6774 [14:43<08:16,  4.94it/s]

Processing tickers:  64%|██████▍   | 4320/6774 [14:44<08:13,  4.97it/s]

Processing tickers:  64%|██████▍   | 4321/6774 [14:44<08:11,  4.99it/s]

Processing tickers:  64%|██████▍   | 4322/6774 [14:44<08:15,  4.95it/s]

Processing tickers:  64%|██████▍   | 4323/6774 [14:44<08:16,  4.94it/s]

Processing tickers:  64%|██████▍   | 4324/6774 [14:44<08:13,  4.96it/s]

Processing tickers:  64%|██████▍   | 4325/6774 [14:45<08:09,  5.00it/s]

Processing tickers:  64%|██████▍   | 4326/6774 [14:45<08:10,  4.99it/s]

Processing tickers:  64%|██████▍   | 4327/6774 [14:45<08:18,  4.91it/s]

Processing tickers:  64%|██████▍   | 4328/6774 [14:45<08:18,  4.91it/s]

Processing tickers:  64%|██████▍   | 4329/6774 [14:45<08:19,  4.89it/s]

Processing tickers:  64%|██████▍   | 4330/6774 [14:46<08:16,  4.92it/s]

Processing tickers:  64%|██████▍   | 4331/6774 [14:46<08:26,  4.82it/s]

Processing tickers:  64%|██████▍   | 4332/6774 [14:46<08:29,  4.79it/s]

Processing tickers:  64%|██████▍   | 4333/6774 [14:46<08:22,  4.85it/s]

Processing tickers:  64%|██████▍   | 4334/6774 [14:46<08:18,  4.90it/s]

Processing tickers:  64%|██████▍   | 4335/6774 [14:47<08:30,  4.78it/s]

Processing tickers:  64%|██████▍   | 4336/6774 [14:47<08:22,  4.85it/s]

Processing tickers:  64%|██████▍   | 4337/6774 [14:47<08:13,  4.94it/s]

Processing tickers:  64%|██████▍   | 4338/6774 [14:47<08:10,  4.96it/s]

Processing tickers:  64%|██████▍   | 4339/6774 [14:48<08:21,  4.86it/s]

Processing tickers:  64%|██████▍   | 4340/6774 [14:48<08:14,  4.92it/s]

Processing tickers:  64%|██████▍   | 4341/6774 [14:48<08:12,  4.94it/s]

Processing tickers:  64%|██████▍   | 4342/6774 [14:48<08:16,  4.90it/s]

Processing tickers:  64%|██████▍   | 4343/6774 [14:48<08:15,  4.91it/s]

Processing tickers:  64%|██████▍   | 4344/6774 [14:49<08:31,  4.75it/s]

Processing tickers:  64%|██████▍   | 4345/6774 [14:49<08:27,  4.79it/s]

Processing tickers:  64%|██████▍   | 4346/6774 [14:49<08:36,  4.70it/s]

Processing tickers:  64%|██████▍   | 4347/6774 [14:49<08:29,  4.77it/s]

Processing tickers:  64%|██████▍   | 4348/6774 [14:49<08:29,  4.76it/s]

Processing tickers:  64%|██████▍   | 4349/6774 [14:50<08:39,  4.67it/s]

Processing tickers:  64%|██████▍   | 4350/6774 [14:50<08:26,  4.78it/s]

Processing tickers:  64%|██████▍   | 4351/6774 [14:50<08:18,  4.86it/s]

Processing tickers:  64%|██████▍   | 4352/6774 [14:50<08:31,  4.73it/s]

Processing tickers:  64%|██████▍   | 4353/6774 [14:50<08:27,  4.77it/s]

Processing tickers:  64%|██████▍   | 4354/6774 [14:51<08:22,  4.82it/s]

Processing tickers:  64%|██████▍   | 4355/6774 [14:51<08:20,  4.83it/s]

Processing tickers:  64%|██████▍   | 4356/6774 [14:51<08:32,  4.72it/s]

Processing tickers:  64%|██████▍   | 4357/6774 [14:51<08:31,  4.73it/s]

Processing tickers:  64%|██████▍   | 4358/6774 [14:51<08:22,  4.81it/s]

Processing tickers:  64%|██████▍   | 4359/6774 [14:52<08:33,  4.70it/s]

Processing tickers:  64%|██████▍   | 4360/6774 [14:52<08:23,  4.79it/s]

Processing tickers:  64%|██████▍   | 4361/6774 [14:52<08:31,  4.72it/s]

Processing tickers:  64%|██████▍   | 4362/6774 [14:52<08:23,  4.79it/s]

Processing tickers:  64%|██████▍   | 4363/6774 [14:53<08:16,  4.86it/s]

Processing tickers:  64%|██████▍   | 4364/6774 [14:53<08:12,  4.89it/s]

Processing tickers:  64%|██████▍   | 4365/6774 [14:53<08:08,  4.93it/s]

Processing tickers:  64%|██████▍   | 4366/6774 [14:53<08:11,  4.90it/s]

Processing tickers:  64%|██████▍   | 4367/6774 [14:53<08:07,  4.94it/s]

Processing tickers:  64%|██████▍   | 4368/6774 [14:54<08:02,  4.99it/s]

Processing tickers:  64%|██████▍   | 4369/6774 [14:54<08:01,  4.99it/s]

Processing tickers:  65%|██████▍   | 4370/6774 [14:54<08:10,  4.91it/s]

Processing tickers:  65%|██████▍   | 4371/6774 [14:54<08:06,  4.94it/s]

Processing tickers:  65%|██████▍   | 4372/6774 [14:54<08:03,  4.97it/s]

Processing tickers:  65%|██████▍   | 4373/6774 [14:55<08:01,  4.99it/s]

Processing tickers:  65%|██████▍   | 4374/6774 [14:55<08:04,  4.96it/s]

Processing tickers:  65%|██████▍   | 4375/6774 [14:55<08:02,  4.98it/s]

Processing tickers:  65%|██████▍   | 4376/6774 [14:55<08:02,  4.97it/s]

Processing tickers:  65%|██████▍   | 4377/6774 [14:55<08:05,  4.94it/s]

Processing tickers:  65%|██████▍   | 4378/6774 [14:56<08:09,  4.90it/s]

Processing tickers:  65%|██████▍   | 4379/6774 [14:56<08:09,  4.89it/s]

Processing tickers:  65%|██████▍   | 4380/6774 [14:56<08:17,  4.81it/s]

Processing tickers:  65%|██████▍   | 4381/6774 [14:56<08:24,  4.75it/s]

Processing tickers:  65%|██████▍   | 4382/6774 [14:56<08:17,  4.81it/s]

Processing tickers:  65%|██████▍   | 4383/6774 [14:57<08:31,  4.68it/s]

Processing tickers:  65%|██████▍   | 4384/6774 [14:57<08:35,  4.63it/s]

Processing tickers:  65%|██████▍   | 4385/6774 [14:57<08:36,  4.63it/s]

Processing tickers:  65%|██████▍   | 4386/6774 [14:57<08:25,  4.72it/s]

Processing tickers:  65%|██████▍   | 4387/6774 [14:57<08:17,  4.80it/s]

Processing tickers:  65%|██████▍   | 4388/6774 [14:58<08:24,  4.73it/s]

Processing tickers:  65%|██████▍   | 4389/6774 [14:58<08:15,  4.82it/s]

Processing tickers:  65%|██████▍   | 4390/6774 [14:58<08:23,  4.73it/s]

Processing tickers:  65%|██████▍   | 4391/6774 [14:58<08:24,  4.72it/s]

Processing tickers:  65%|██████▍   | 4392/6774 [14:59<08:15,  4.81it/s]

Processing tickers:  65%|██████▍   | 4393/6774 [14:59<08:18,  4.78it/s]

Processing tickers:  65%|██████▍   | 4394/6774 [14:59<08:14,  4.81it/s]

Processing tickers:  65%|██████▍   | 4395/6774 [14:59<08:08,  4.87it/s]

Processing tickers:  65%|██████▍   | 4396/6774 [14:59<08:06,  4.89it/s]

Processing tickers:  65%|██████▍   | 4397/6774 [15:00<08:01,  4.93it/s]

Processing tickers:  65%|██████▍   | 4398/6774 [15:00<07:58,  4.96it/s]

Processing tickers:  65%|██████▍   | 4399/6774 [15:00<07:54,  5.00it/s]

Processing tickers:  65%|██████▍   | 4400/6774 [15:00<07:55,  5.00it/s]

Processing tickers:  65%|██████▍   | 4401/6774 [15:00<08:54,  4.44it/s]

Processing tickers:  65%|██████▍   | 4402/6774 [15:01<08:44,  4.52it/s]

Processing tickers:  65%|██████▍   | 4403/6774 [15:01<08:28,  4.66it/s]

Processing tickers:  65%|██████▌   | 4404/6774 [15:01<08:18,  4.76it/s]

Processing tickers:  65%|██████▌   | 4405/6774 [15:01<08:38,  4.57it/s]

Processing tickers:  65%|██████▌   | 4406/6774 [15:01<08:27,  4.67it/s]

Processing tickers:  65%|██████▌   | 4407/6774 [15:02<08:16,  4.77it/s]

Processing tickers:  65%|██████▌   | 4408/6774 [15:02<08:20,  4.73it/s]

Processing tickers:  65%|██████▌   | 4409/6774 [15:02<08:26,  4.67it/s]

Processing tickers:  65%|██████▌   | 4410/6774 [15:02<08:20,  4.72it/s]

Processing tickers:  65%|██████▌   | 4411/6774 [15:03<08:15,  4.77it/s]

Processing tickers:  65%|██████▌   | 4412/6774 [15:03<08:08,  4.84it/s]

Processing tickers:  65%|██████▌   | 4413/6774 [15:03<08:07,  4.85it/s]

Processing tickers:  65%|██████▌   | 4414/6774 [15:03<08:01,  4.91it/s]

Processing tickers:  65%|██████▌   | 4415/6774 [15:03<08:02,  4.89it/s]

Processing tickers:  65%|██████▌   | 4416/6774 [15:04<07:58,  4.93it/s]

Processing tickers:  65%|██████▌   | 4417/6774 [15:04<08:00,  4.90it/s]

Processing tickers:  65%|██████▌   | 4418/6774 [15:04<07:57,  4.94it/s]

Processing tickers:  65%|██████▌   | 4419/6774 [15:04<07:53,  4.98it/s]

Processing tickers:  65%|██████▌   | 4420/6774 [15:04<07:52,  4.98it/s]

Processing tickers:  65%|██████▌   | 4421/6774 [15:05<07:49,  5.02it/s]

Processing tickers:  65%|██████▌   | 4422/6774 [15:05<07:47,  5.03it/s]

Processing tickers:  65%|██████▌   | 4423/6774 [15:05<08:02,  4.88it/s]

Processing tickers:  65%|██████▌   | 4424/6774 [15:05<08:02,  4.87it/s]

Processing tickers:  65%|██████▌   | 4425/6774 [15:05<08:00,  4.89it/s]

Processing tickers:  65%|██████▌   | 4426/6774 [15:06<07:54,  4.94it/s]

Processing tickers:  65%|██████▌   | 4427/6774 [15:06<07:55,  4.93it/s]

Processing tickers:  65%|██████▌   | 4428/6774 [15:06<07:52,  4.97it/s]

Processing tickers:  65%|██████▌   | 4429/6774 [15:06<07:54,  4.94it/s]

Processing tickers:  65%|██████▌   | 4430/6774 [15:06<08:13,  4.75it/s]

Processing tickers:  65%|██████▌   | 4431/6774 [15:07<08:08,  4.80it/s]

Processing tickers:  65%|██████▌   | 4432/6774 [15:07<08:17,  4.71it/s]

Processing tickers:  65%|██████▌   | 4433/6774 [15:07<08:19,  4.69it/s]

Processing tickers:  65%|██████▌   | 4434/6774 [15:07<08:17,  4.70it/s]

Processing tickers:  65%|██████▌   | 4435/6774 [15:07<08:12,  4.75it/s]

Processing tickers:  65%|██████▌   | 4436/6774 [15:08<08:19,  4.68it/s]

Processing tickers:  66%|██████▌   | 4437/6774 [15:08<08:08,  4.78it/s]

Processing tickers:  66%|██████▌   | 4438/6774 [15:08<08:03,  4.83it/s]

Processing tickers:  66%|██████▌   | 4439/6774 [15:08<08:01,  4.85it/s]

Processing tickers:  66%|██████▌   | 4440/6774 [15:08<07:55,  4.91it/s]

Processing tickers:  66%|██████▌   | 4441/6774 [15:09<07:50,  4.95it/s]

Processing tickers:  66%|██████▌   | 4442/6774 [15:09<07:46,  4.99it/s]

Processing tickers:  66%|██████▌   | 4443/6774 [15:09<07:44,  5.01it/s]

Processing tickers:  66%|██████▌   | 4444/6774 [15:09<07:50,  4.95it/s]

Processing tickers:  66%|██████▌   | 4445/6774 [15:09<07:50,  4.95it/s]

Processing tickers:  66%|██████▌   | 4446/6774 [15:10<07:49,  4.96it/s]

Processing tickers:  66%|██████▌   | 4447/6774 [15:10<08:02,  4.83it/s]

Processing tickers:  66%|██████▌   | 4448/6774 [15:10<07:55,  4.89it/s]

Processing tickers:  66%|██████▌   | 4449/6774 [15:10<07:51,  4.93it/s]

Processing tickers:  66%|██████▌   | 4450/6774 [15:10<07:47,  4.97it/s]

Processing tickers:  66%|██████▌   | 4451/6774 [15:11<07:45,  4.99it/s]

Processing tickers:  66%|██████▌   | 4452/6774 [15:11<07:41,  5.03it/s]

Processing tickers:  66%|██████▌   | 4453/6774 [15:11<07:43,  5.00it/s]

Processing tickers:  66%|██████▌   | 4454/6774 [15:11<07:46,  4.98it/s]

Processing tickers:  66%|██████▌   | 4455/6774 [15:11<07:58,  4.85it/s]

Processing tickers:  66%|██████▌   | 4456/6774 [15:12<07:52,  4.91it/s]

Processing tickers:  66%|██████▌   | 4457/6774 [15:12<07:48,  4.95it/s]

Processing tickers:  66%|██████▌   | 4458/6774 [15:12<07:48,  4.94it/s]

Processing tickers:  66%|██████▌   | 4459/6774 [15:12<07:48,  4.94it/s]

Processing tickers:  66%|██████▌   | 4460/6774 [15:12<07:46,  4.96it/s]

Processing tickers:  66%|██████▌   | 4461/6774 [15:13<07:46,  4.95it/s]

Processing tickers:  66%|██████▌   | 4462/6774 [15:13<07:55,  4.86it/s]

Processing tickers:  66%|██████▌   | 4463/6774 [15:13<07:50,  4.91it/s]

Processing tickers:  66%|██████▌   | 4464/6774 [15:13<07:48,  4.93it/s]

Processing tickers:  66%|██████▌   | 4465/6774 [15:14<07:46,  4.95it/s]

Processing tickers:  66%|██████▌   | 4466/6774 [15:14<07:45,  4.96it/s]

Processing tickers:  66%|██████▌   | 4467/6774 [15:14<07:43,  4.97it/s]

Processing tickers:  66%|██████▌   | 4468/6774 [15:14<07:50,  4.90it/s]

Processing tickers:  66%|██████▌   | 4469/6774 [15:14<07:48,  4.92it/s]

Processing tickers:  66%|██████▌   | 4470/6774 [15:15<07:45,  4.95it/s]

Processing tickers:  66%|██████▌   | 4471/6774 [15:15<07:42,  4.98it/s]

Processing tickers:  66%|██████▌   | 4472/6774 [15:15<07:45,  4.94it/s]

Processing tickers:  66%|██████▌   | 4473/6774 [15:15<07:41,  4.98it/s]

Processing tickers:  66%|██████▌   | 4474/6774 [15:15<07:41,  4.98it/s]

Processing tickers:  66%|██████▌   | 4475/6774 [15:16<07:48,  4.91it/s]

Processing tickers:  66%|██████▌   | 4476/6774 [15:16<07:44,  4.95it/s]

Processing tickers:  66%|██████▌   | 4477/6774 [15:16<07:46,  4.93it/s]

Processing tickers:  66%|██████▌   | 4478/6774 [15:16<07:57,  4.81it/s]

Processing tickers:  66%|██████▌   | 4479/6774 [15:16<07:50,  4.87it/s]

Processing tickers:  66%|██████▌   | 4480/6774 [15:17<07:50,  4.88it/s]

Processing tickers:  66%|██████▌   | 4481/6774 [15:17<07:47,  4.90it/s]

Processing tickers:  66%|██████▌   | 4482/6774 [15:17<07:51,  4.86it/s]

Processing tickers:  66%|██████▌   | 4483/6774 [15:17<07:47,  4.90it/s]

Processing tickers:  66%|██████▌   | 4484/6774 [15:17<07:53,  4.84it/s]

Processing tickers:  66%|██████▌   | 4485/6774 [15:18<07:45,  4.92it/s]

Processing tickers:  66%|██████▌   | 4486/6774 [15:18<07:45,  4.92it/s]

Processing tickers:  66%|██████▌   | 4487/6774 [15:18<07:52,  4.84it/s]

Processing tickers:  66%|██████▋   | 4488/6774 [15:18<08:02,  4.74it/s]

Processing tickers:  66%|██████▋   | 4489/6774 [15:18<07:55,  4.80it/s]

Processing tickers:  66%|██████▋   | 4490/6774 [15:19<07:49,  4.86it/s]

Processing tickers:  66%|██████▋   | 4491/6774 [15:19<07:46,  4.89it/s]

Processing tickers:  66%|██████▋   | 4492/6774 [15:19<07:44,  4.91it/s]

Processing tickers:  66%|██████▋   | 4493/6774 [15:19<07:44,  4.91it/s]

Processing tickers:  66%|██████▋   | 4494/6774 [15:19<07:42,  4.93it/s]

Processing tickers:  66%|██████▋   | 4495/6774 [15:20<07:39,  4.96it/s]

Processing tickers:  66%|██████▋   | 4496/6774 [15:20<07:38,  4.97it/s]

Processing tickers:  66%|██████▋   | 4497/6774 [15:20<07:38,  4.97it/s]

Processing tickers:  66%|██████▋   | 4498/6774 [15:20<07:37,  4.97it/s]

Processing tickers:  66%|██████▋   | 4499/6774 [15:20<07:39,  4.96it/s]

Processing tickers:  66%|██████▋   | 4500/6774 [15:21<07:41,  4.93it/s]

Processing tickers:  66%|██████▋   | 4501/6774 [15:21<07:38,  4.96it/s]

Processing tickers:  66%|██████▋   | 4502/6774 [15:21<07:52,  4.81it/s]

Processing tickers:  66%|██████▋   | 4503/6774 [15:21<07:48,  4.85it/s]

Processing tickers:  66%|██████▋   | 4504/6774 [15:21<07:43,  4.90it/s]

Processing tickers:  67%|██████▋   | 4505/6774 [15:22<11:29,  3.29it/s]

Processing tickers:  67%|██████▋   | 4506/6774 [15:22<10:19,  3.66it/s]

Processing tickers:  67%|██████▋   | 4507/6774 [15:22<09:27,  4.00it/s]

Processing tickers:  67%|██████▋   | 4508/6774 [15:23<08:53,  4.25it/s]

Processing tickers:  67%|██████▋   | 4509/6774 [15:23<08:29,  4.44it/s]

Processing tickers:  67%|██████▋   | 4510/6774 [15:23<08:14,  4.58it/s]

Processing tickers:  67%|██████▋   | 4511/6774 [15:23<08:02,  4.69it/s]

Processing tickers:  67%|██████▋   | 4512/6774 [15:23<07:56,  4.74it/s]

Processing tickers:  67%|██████▋   | 4513/6774 [15:24<07:45,  4.86it/s]

Processing tickers:  67%|██████▋   | 4514/6774 [15:24<07:43,  4.88it/s]

Processing tickers:  67%|██████▋   | 4515/6774 [15:24<07:40,  4.91it/s]

Processing tickers:  67%|██████▋   | 4516/6774 [15:24<07:37,  4.93it/s]

Processing tickers:  67%|██████▋   | 4517/6774 [15:24<07:38,  4.92it/s]

Processing tickers:  67%|██████▋   | 4518/6774 [15:25<07:47,  4.83it/s]

Processing tickers:  67%|██████▋   | 4519/6774 [15:25<07:46,  4.84it/s]

Processing tickers:  67%|██████▋   | 4520/6774 [15:25<07:41,  4.89it/s]

Processing tickers:  67%|██████▋   | 4521/6774 [15:25<07:38,  4.91it/s]

Processing tickers:  67%|██████▋   | 4522/6774 [15:25<07:34,  4.95it/s]

Processing tickers:  67%|██████▋   | 4523/6774 [15:26<07:40,  4.88it/s]

Processing tickers:  67%|██████▋   | 4524/6774 [15:26<07:43,  4.85it/s]

Processing tickers:  67%|██████▋   | 4525/6774 [15:26<07:44,  4.85it/s]

Processing tickers:  67%|██████▋   | 4526/6774 [15:26<07:56,  4.72it/s]

Processing tickers:  67%|██████▋   | 4527/6774 [15:26<07:47,  4.80it/s]

Processing tickers:  67%|██████▋   | 4528/6774 [15:27<07:48,  4.79it/s]

Processing tickers:  67%|██████▋   | 4529/6774 [15:27<07:40,  4.87it/s]

Processing tickers:  67%|██████▋   | 4530/6774 [15:27<07:35,  4.92it/s]

Processing tickers:  67%|██████▋   | 4531/6774 [15:27<07:42,  4.85it/s]

Processing tickers:  67%|██████▋   | 4532/6774 [15:28<07:42,  4.84it/s]

Processing tickers:  67%|██████▋   | 4533/6774 [15:28<07:47,  4.79it/s]

Processing tickers:  67%|██████▋   | 4534/6774 [15:28<07:39,  4.88it/s]

Processing tickers:  67%|██████▋   | 4535/6774 [15:28<07:36,  4.90it/s]

Processing tickers:  67%|██████▋   | 4536/6774 [15:28<07:39,  4.88it/s]

Processing tickers:  67%|██████▋   | 4537/6774 [15:29<07:34,  4.92it/s]

Processing tickers:  67%|██████▋   | 4538/6774 [15:29<07:35,  4.91it/s]

Processing tickers:  67%|██████▋   | 4539/6774 [15:29<07:30,  4.96it/s]

Processing tickers:  67%|██████▋   | 4540/6774 [15:29<08:17,  4.49it/s]

Processing tickers:  67%|██████▋   | 4541/6774 [15:29<08:12,  4.53it/s]

Processing tickers:  67%|██████▋   | 4542/6774 [15:30<07:58,  4.67it/s]

Processing tickers:  67%|██████▋   | 4543/6774 [15:30<07:53,  4.71it/s]

Processing tickers:  67%|██████▋   | 4544/6774 [15:30<07:47,  4.77it/s]

Processing tickers:  67%|██████▋   | 4545/6774 [15:30<07:37,  4.87it/s]

Processing tickers:  67%|██████▋   | 4546/6774 [15:30<07:42,  4.82it/s]

Processing tickers:  67%|██████▋   | 4547/6774 [15:31<07:46,  4.78it/s]

Processing tickers:  67%|██████▋   | 4548/6774 [15:31<07:41,  4.82it/s]

Processing tickers:  67%|██████▋   | 4549/6774 [15:31<07:37,  4.86it/s]

Processing tickers:  67%|██████▋   | 4550/6774 [15:31<07:37,  4.86it/s]

Processing tickers:  67%|██████▋   | 4551/6774 [15:31<07:33,  4.90it/s]

Processing tickers:  67%|██████▋   | 4552/6774 [15:32<07:31,  4.92it/s]

Processing tickers:  67%|██████▋   | 4553/6774 [15:32<07:28,  4.95it/s]

Processing tickers:  67%|██████▋   | 4554/6774 [15:32<07:29,  4.93it/s]

Processing tickers:  67%|██████▋   | 4555/6774 [15:32<07:29,  4.94it/s]

Processing tickers:  67%|██████▋   | 4556/6774 [15:32<07:26,  4.97it/s]

Processing tickers:  67%|██████▋   | 4557/6774 [15:33<07:23,  5.00it/s]

Processing tickers:  67%|██████▋   | 4558/6774 [15:33<07:31,  4.91it/s]

Processing tickers:  67%|██████▋   | 4559/6774 [15:33<07:28,  4.94it/s]

Processing tickers:  67%|██████▋   | 4560/6774 [15:33<07:24,  4.99it/s]

Processing tickers:  67%|██████▋   | 4561/6774 [15:33<07:23,  4.99it/s]

Processing tickers:  67%|██████▋   | 4562/6774 [15:34<07:23,  4.99it/s]

Processing tickers:  67%|██████▋   | 4563/6774 [15:34<07:20,  5.02it/s]

Processing tickers:  67%|██████▋   | 4564/6774 [15:34<07:19,  5.02it/s]

Processing tickers:  67%|██████▋   | 4565/6774 [15:34<07:22,  4.99it/s]

Processing tickers:  67%|██████▋   | 4566/6774 [15:34<07:23,  4.98it/s]

Processing tickers:  67%|██████▋   | 4567/6774 [15:35<07:22,  4.98it/s]

Processing tickers:  67%|██████▋   | 4568/6774 [15:35<07:23,  4.98it/s]

Processing tickers:  67%|██████▋   | 4569/6774 [15:35<07:22,  4.99it/s]

Processing tickers:  67%|██████▋   | 4570/6774 [15:35<07:22,  4.98it/s]

Processing tickers:  67%|██████▋   | 4571/6774 [15:35<07:20,  5.00it/s]

Processing tickers:  67%|██████▋   | 4572/6774 [15:36<07:18,  5.02it/s]

Processing tickers:  68%|██████▊   | 4573/6774 [15:36<07:16,  5.04it/s]

Processing tickers:  68%|██████▊   | 4574/6774 [15:36<07:18,  5.02it/s]

Processing tickers:  68%|██████▊   | 4575/6774 [15:36<07:19,  5.00it/s]

Processing tickers:  68%|██████▊   | 4576/6774 [15:36<07:29,  4.89it/s]

Processing tickers:  68%|██████▊   | 4577/6774 [15:37<07:36,  4.81it/s]

Processing tickers:  68%|██████▊   | 4578/6774 [15:37<07:28,  4.90it/s]

Processing tickers:  68%|██████▊   | 4579/6774 [15:37<07:31,  4.86it/s]

Processing tickers:  68%|██████▊   | 4580/6774 [15:37<07:29,  4.88it/s]

Processing tickers:  68%|██████▊   | 4581/6774 [15:38<07:48,  4.68it/s]

Processing tickers:  68%|██████▊   | 4582/6774 [15:38<07:50,  4.66it/s]

Processing tickers:  68%|██████▊   | 4583/6774 [15:38<07:45,  4.71it/s]

Processing tickers:  68%|██████▊   | 4584/6774 [15:38<07:39,  4.77it/s]

Processing tickers:  68%|██████▊   | 4585/6774 [15:38<07:30,  4.86it/s]

Processing tickers:  68%|██████▊   | 4586/6774 [15:39<07:26,  4.90it/s]

Processing tickers:  68%|██████▊   | 4587/6774 [15:39<07:24,  4.92it/s]

Processing tickers:  68%|██████▊   | 4588/6774 [15:39<07:25,  4.91it/s]

Processing tickers:  68%|██████▊   | 4589/6774 [15:39<07:40,  4.75it/s]

Processing tickers:  68%|██████▊   | 4590/6774 [15:39<07:37,  4.77it/s]

Processing tickers:  68%|██████▊   | 4591/6774 [15:40<07:52,  4.62it/s]

Processing tickers:  68%|██████▊   | 4592/6774 [15:40<07:40,  4.74it/s]

Processing tickers:  68%|██████▊   | 4593/6774 [15:40<07:32,  4.82it/s]

Processing tickers:  68%|██████▊   | 4594/6774 [15:40<07:31,  4.83it/s]

Processing tickers:  68%|██████▊   | 4595/6774 [15:40<07:25,  4.89it/s]

Processing tickers:  68%|██████▊   | 4596/6774 [15:41<07:21,  4.94it/s]

Processing tickers:  68%|██████▊   | 4597/6774 [15:41<07:21,  4.93it/s]

Processing tickers:  68%|██████▊   | 4598/6774 [15:41<07:19,  4.95it/s]

Processing tickers:  68%|██████▊   | 4599/6774 [15:41<07:18,  4.97it/s]

Processing tickers:  68%|██████▊   | 4600/6774 [15:41<07:34,  4.78it/s]

Processing tickers:  68%|██████▊   | 4601/6774 [15:42<07:31,  4.82it/s]

Processing tickers:  68%|██████▊   | 4602/6774 [15:42<07:26,  4.86it/s]

Processing tickers:  68%|██████▊   | 4603/6774 [15:42<07:42,  4.69it/s]

Processing tickers:  68%|██████▊   | 4604/6774 [15:42<07:38,  4.74it/s]

Processing tickers:  68%|██████▊   | 4605/6774 [15:43<07:32,  4.79it/s]

Processing tickers:  68%|██████▊   | 4606/6774 [15:43<07:27,  4.84it/s]

Processing tickers:  68%|██████▊   | 4607/6774 [15:43<07:33,  4.77it/s]

Processing tickers:  68%|██████▊   | 4608/6774 [15:43<07:28,  4.83it/s]

Processing tickers:  68%|██████▊   | 4609/6774 [15:43<07:23,  4.88it/s]

Processing tickers:  68%|██████▊   | 4610/6774 [15:44<07:27,  4.84it/s]

Processing tickers:  68%|██████▊   | 4611/6774 [15:44<07:23,  4.87it/s]

Processing tickers:  68%|██████▊   | 4612/6774 [15:44<07:17,  4.94it/s]

Processing tickers:  68%|██████▊   | 4613/6774 [15:44<07:15,  4.96it/s]

Processing tickers:  68%|██████▊   | 4614/6774 [15:44<07:16,  4.95it/s]

Processing tickers:  68%|██████▊   | 4615/6774 [15:45<07:14,  4.97it/s]

Processing tickers:  68%|██████▊   | 4616/6774 [15:45<07:11,  5.00it/s]

Processing tickers:  68%|██████▊   | 4617/6774 [15:45<07:08,  5.03it/s]

Processing tickers:  68%|██████▊   | 4618/6774 [15:45<07:07,  5.04it/s]

Processing tickers:  68%|██████▊   | 4619/6774 [15:45<07:21,  4.89it/s]

Processing tickers:  68%|██████▊   | 4620/6774 [15:46<07:19,  4.90it/s]

Processing tickers:  68%|██████▊   | 4621/6774 [15:46<07:14,  4.96it/s]

Processing tickers:  68%|██████▊   | 4622/6774 [15:46<07:10,  5.00it/s]

Processing tickers:  68%|██████▊   | 4623/6774 [15:46<07:12,  4.97it/s]

Processing tickers:  68%|██████▊   | 4624/6774 [15:46<07:09,  5.00it/s]

Processing tickers:  68%|██████▊   | 4625/6774 [15:47<07:12,  4.97it/s]

Processing tickers:  68%|██████▊   | 4626/6774 [15:47<07:11,  4.98it/s]

Processing tickers:  68%|██████▊   | 4627/6774 [15:47<07:09,  5.00it/s]

Processing tickers:  68%|██████▊   | 4628/6774 [15:47<07:12,  4.96it/s]

Processing tickers:  68%|██████▊   | 4629/6774 [15:47<07:19,  4.88it/s]

Processing tickers:  68%|██████▊   | 4630/6774 [15:48<07:16,  4.91it/s]

Processing tickers:  68%|██████▊   | 4631/6774 [15:48<07:29,  4.77it/s]

Processing tickers:  68%|██████▊   | 4632/6774 [15:48<07:25,  4.81it/s]

Processing tickers:  68%|██████▊   | 4633/6774 [15:48<07:16,  4.90it/s]

Processing tickers:  68%|██████▊   | 4634/6774 [15:48<07:31,  4.74it/s]

Processing tickers:  68%|██████▊   | 4635/6774 [15:49<07:29,  4.76it/s]

Processing tickers:  68%|██████▊   | 4636/6774 [15:49<07:22,  4.83it/s]

Processing tickers:  68%|██████▊   | 4637/6774 [15:49<07:20,  4.85it/s]

Processing tickers:  68%|██████▊   | 4638/6774 [15:49<07:16,  4.89it/s]

Processing tickers:  68%|██████▊   | 4639/6774 [15:49<07:13,  4.92it/s]

Processing tickers:  68%|██████▊   | 4640/6774 [15:50<07:12,  4.94it/s]

Processing tickers:  69%|██████▊   | 4641/6774 [15:50<07:10,  4.95it/s]

Processing tickers:  69%|██████▊   | 4642/6774 [15:50<07:21,  4.83it/s]

Processing tickers:  69%|██████▊   | 4643/6774 [15:50<07:19,  4.85it/s]

Processing tickers:  69%|██████▊   | 4644/6774 [15:50<07:16,  4.88it/s]

Processing tickers:  69%|██████▊   | 4645/6774 [15:51<07:12,  4.92it/s]

Processing tickers:  69%|██████▊   | 4646/6774 [15:51<07:13,  4.91it/s]

Processing tickers:  69%|██████▊   | 4647/6774 [15:51<07:18,  4.85it/s]

Processing tickers:  69%|██████▊   | 4648/6774 [15:51<07:13,  4.91it/s]

Processing tickers:  69%|██████▊   | 4649/6774 [15:51<07:10,  4.94it/s]

Processing tickers:  69%|██████▊   | 4650/6774 [15:52<07:10,  4.93it/s]

Processing tickers:  69%|██████▊   | 4651/6774 [15:52<07:07,  4.97it/s]

Processing tickers:  69%|██████▊   | 4652/6774 [15:52<07:06,  4.98it/s]

Processing tickers:  69%|██████▊   | 4653/6774 [15:52<07:12,  4.91it/s]

Processing tickers:  69%|██████▊   | 4654/6774 [15:52<07:08,  4.94it/s]

Processing tickers:  69%|██████▊   | 4655/6774 [15:53<07:05,  4.98it/s]

Processing tickers:  69%|██████▊   | 4656/6774 [15:53<07:14,  4.88it/s]

Processing tickers:  69%|██████▊   | 4657/6774 [15:53<07:15,  4.86it/s]

Processing tickers:  69%|██████▉   | 4658/6774 [15:53<07:21,  4.79it/s]

Processing tickers:  69%|██████▉   | 4659/6774 [15:54<07:15,  4.85it/s]

Processing tickers:  69%|██████▉   | 4660/6774 [15:54<07:16,  4.84it/s]

Processing tickers:  69%|██████▉   | 4661/6774 [15:54<07:12,  4.88it/s]

Processing tickers:  69%|██████▉   | 4662/6774 [15:54<07:08,  4.93it/s]

Processing tickers:  69%|██████▉   | 4663/6774 [15:54<07:08,  4.92it/s]

Processing tickers:  69%|██████▉   | 4664/6774 [15:55<07:11,  4.89it/s]

Processing tickers:  69%|██████▉   | 4665/6774 [15:55<07:09,  4.91it/s]

Processing tickers:  69%|██████▉   | 4666/6774 [15:55<07:07,  4.93it/s]

Processing tickers:  69%|██████▉   | 4667/6774 [15:55<07:19,  4.79it/s]

Processing tickers:  69%|██████▉   | 4668/6774 [15:55<07:12,  4.87it/s]

Processing tickers:  69%|██████▉   | 4669/6774 [15:56<07:06,  4.93it/s]

Processing tickers:  69%|██████▉   | 4670/6774 [15:56<07:07,  4.92it/s]

Processing tickers:  69%|██████▉   | 4671/6774 [15:56<07:08,  4.91it/s]

Processing tickers:  69%|██████▉   | 4672/6774 [15:56<07:09,  4.90it/s]

Processing tickers:  69%|██████▉   | 4673/6774 [15:56<07:09,  4.89it/s]

Processing tickers:  69%|██████▉   | 4674/6774 [15:57<07:05,  4.93it/s]

Processing tickers:  69%|██████▉   | 4675/6774 [15:57<07:19,  4.78it/s]

Processing tickers:  69%|██████▉   | 4676/6774 [15:57<07:16,  4.81it/s]

Processing tickers:  69%|██████▉   | 4677/6774 [15:57<07:18,  4.79it/s]

Processing tickers:  69%|██████▉   | 4678/6774 [15:57<07:11,  4.85it/s]

Processing tickers:  69%|██████▉   | 4679/6774 [15:58<07:09,  4.88it/s]

Processing tickers:  69%|██████▉   | 4680/6774 [15:58<07:04,  4.93it/s]

Processing tickers:  69%|██████▉   | 4681/6774 [15:58<07:07,  4.89it/s]

Processing tickers:  69%|██████▉   | 4682/6774 [15:58<07:11,  4.85it/s]

Processing tickers:  69%|██████▉   | 4683/6774 [15:58<07:06,  4.91it/s]

Processing tickers:  69%|██████▉   | 4684/6774 [15:59<07:06,  4.90it/s]

Processing tickers:  69%|██████▉   | 4685/6774 [15:59<07:00,  4.97it/s]

Processing tickers:  69%|██████▉   | 4686/6774 [15:59<06:58,  4.99it/s]

Processing tickers:  69%|██████▉   | 4687/6774 [15:59<06:58,  4.98it/s]

Processing tickers:  69%|██████▉   | 4688/6774 [15:59<06:58,  4.98it/s]

Processing tickers:  69%|██████▉   | 4689/6774 [16:00<07:01,  4.95it/s]

Processing tickers:  69%|██████▉   | 4690/6774 [16:00<07:00,  4.96it/s]

Processing tickers:  69%|██████▉   | 4691/6774 [16:00<06:58,  4.97it/s]

Processing tickers:  69%|██████▉   | 4692/6774 [16:00<06:57,  4.99it/s]

Processing tickers:  69%|██████▉   | 4693/6774 [16:00<06:55,  5.01it/s]

Processing tickers:  69%|██████▉   | 4694/6774 [16:01<06:54,  5.01it/s]

Processing tickers:  69%|██████▉   | 4695/6774 [16:01<06:55,  5.01it/s]

Processing tickers:  69%|██████▉   | 4696/6774 [16:01<06:59,  4.96it/s]

Processing tickers:  69%|██████▉   | 4697/6774 [16:01<07:04,  4.90it/s]

Processing tickers:  69%|██████▉   | 4698/6774 [16:01<07:00,  4.94it/s]

Processing tickers:  69%|██████▉   | 4699/6774 [16:02<06:59,  4.95it/s]

Processing tickers:  69%|██████▉   | 4700/6774 [16:02<06:57,  4.97it/s]

Processing tickers:  69%|██████▉   | 4701/6774 [16:02<06:58,  4.96it/s]

Processing tickers:  69%|██████▉   | 4702/6774 [16:02<06:54,  5.00it/s]

Processing tickers:  69%|██████▉   | 4703/6774 [16:02<06:54,  5.00it/s]

Processing tickers:  69%|██████▉   | 4704/6774 [16:03<06:52,  5.01it/s]

Processing tickers:  69%|██████▉   | 4705/6774 [16:03<06:52,  5.02it/s]

Processing tickers:  69%|██████▉   | 4706/6774 [16:03<06:55,  4.98it/s]

Processing tickers:  69%|██████▉   | 4707/6774 [16:03<06:52,  5.01it/s]

Processing tickers:  70%|██████▉   | 4708/6774 [16:03<06:52,  5.01it/s]

Processing tickers:  70%|██████▉   | 4709/6774 [16:04<06:53,  4.99it/s]

Processing tickers:  70%|██████▉   | 4710/6774 [16:04<06:55,  4.97it/s]

Processing tickers:  70%|██████▉   | 4711/6774 [16:04<07:03,  4.87it/s]

Processing tickers:  70%|██████▉   | 4712/6774 [16:04<07:06,  4.83it/s]

Processing tickers:  70%|██████▉   | 4713/6774 [16:04<07:00,  4.90it/s]

Processing tickers:  70%|██████▉   | 4714/6774 [16:05<06:56,  4.95it/s]

Processing tickers:  70%|██████▉   | 4715/6774 [16:05<07:00,  4.89it/s]

Processing tickers:  70%|██████▉   | 4716/6774 [16:05<07:01,  4.88it/s]

Processing tickers:  70%|██████▉   | 4717/6774 [16:05<07:01,  4.88it/s]

Processing tickers:  70%|██████▉   | 4718/6774 [16:06<07:03,  4.85it/s]

Processing tickers:  70%|██████▉   | 4719/6774 [16:06<06:57,  4.92it/s]

Processing tickers:  70%|██████▉   | 4720/6774 [16:06<06:59,  4.89it/s]

Processing tickers:  70%|██████▉   | 4721/6774 [16:06<07:03,  4.85it/s]

Processing tickers:  70%|██████▉   | 4722/6774 [16:06<06:59,  4.89it/s]

Processing tickers:  70%|██████▉   | 4723/6774 [16:07<06:57,  4.91it/s]

Processing tickers:  70%|██████▉   | 4724/6774 [16:07<06:58,  4.90it/s]

Processing tickers:  70%|██████▉   | 4725/6774 [16:07<07:10,  4.76it/s]

Processing tickers:  70%|██████▉   | 4726/6774 [16:07<07:12,  4.74it/s]

Processing tickers:  70%|██████▉   | 4727/6774 [16:07<07:06,  4.80it/s]

Processing tickers:  70%|██████▉   | 4728/6774 [16:08<07:04,  4.81it/s]

Processing tickers:  70%|██████▉   | 4729/6774 [16:08<06:59,  4.87it/s]

Processing tickers:  70%|██████▉   | 4730/6774 [16:08<07:05,  4.81it/s]

Processing tickers:  70%|██████▉   | 4731/6774 [16:08<07:09,  4.76it/s]

Processing tickers:  70%|██████▉   | 4732/6774 [16:08<07:10,  4.74it/s]

Processing tickers:  70%|██████▉   | 4733/6774 [16:09<07:01,  4.84it/s]

Processing tickers:  70%|██████▉   | 4734/6774 [16:09<06:57,  4.89it/s]

Processing tickers:  70%|██████▉   | 4735/6774 [16:09<07:06,  4.78it/s]

Processing tickers:  70%|██████▉   | 4736/6774 [16:09<07:09,  4.75it/s]

Processing tickers:  70%|██████▉   | 4737/6774 [16:09<07:01,  4.83it/s]

Processing tickers:  70%|██████▉   | 4738/6774 [16:10<06:56,  4.89it/s]

Processing tickers:  70%|██████▉   | 4739/6774 [16:10<06:54,  4.90it/s]

Processing tickers:  70%|██████▉   | 4740/6774 [16:10<06:55,  4.89it/s]

Processing tickers:  70%|██████▉   | 4741/6774 [16:10<06:54,  4.91it/s]

Processing tickers:  70%|███████   | 4742/6774 [16:10<07:04,  4.79it/s]

Processing tickers:  70%|███████   | 4743/6774 [16:11<06:56,  4.88it/s]

Processing tickers:  70%|███████   | 4744/6774 [16:11<06:52,  4.92it/s]

Processing tickers:  70%|███████   | 4745/6774 [16:11<07:08,  4.74it/s]

Processing tickers:  70%|███████   | 4746/6774 [16:11<06:59,  4.83it/s]

Processing tickers:  70%|███████   | 4747/6774 [16:11<06:54,  4.89it/s]

Processing tickers:  70%|███████   | 4748/6774 [16:12<06:53,  4.90it/s]

Processing tickers:  70%|███████   | 4749/6774 [16:12<06:48,  4.96it/s]

Processing tickers:  70%|███████   | 4750/6774 [16:12<06:48,  4.96it/s]

Processing tickers:  70%|███████   | 4751/6774 [16:12<06:45,  4.99it/s]

Processing tickers:  70%|███████   | 4752/6774 [16:12<06:43,  5.02it/s]

Processing tickers:  70%|███████   | 4753/6774 [16:13<06:41,  5.03it/s]

Processing tickers:  70%|███████   | 4754/6774 [16:13<06:42,  5.02it/s]

Processing tickers:  70%|███████   | 4755/6774 [16:13<06:52,  4.90it/s]

Processing tickers:  70%|███████   | 4756/6774 [16:13<06:49,  4.93it/s]

Processing tickers:  70%|███████   | 4757/6774 [16:14<06:48,  4.93it/s]

Processing tickers:  70%|███████   | 4758/6774 [16:14<06:49,  4.93it/s]

Processing tickers:  70%|███████   | 4759/6774 [16:14<06:47,  4.94it/s]

Processing tickers:  70%|███████   | 4760/6774 [16:14<06:46,  4.95it/s]

Processing tickers:  70%|███████   | 4761/6774 [16:14<06:48,  4.93it/s]

Processing tickers:  70%|███████   | 4762/6774 [16:15<06:47,  4.94it/s]

Processing tickers:  70%|███████   | 4763/6774 [16:15<06:47,  4.94it/s]

Processing tickers:  70%|███████   | 4764/6774 [16:15<06:44,  4.98it/s]

Processing tickers:  70%|███████   | 4765/6774 [16:15<07:12,  4.64it/s]

Processing tickers:  70%|███████   | 4766/6774 [16:15<07:12,  4.65it/s]

Processing tickers:  70%|███████   | 4767/6774 [16:16<07:04,  4.73it/s]

Processing tickers:  70%|███████   | 4768/6774 [16:16<06:57,  4.80it/s]

Processing tickers:  70%|███████   | 4769/6774 [16:16<06:58,  4.79it/s]

Processing tickers:  70%|███████   | 4770/6774 [16:16<07:00,  4.77it/s]

Processing tickers:  70%|███████   | 4771/6774 [16:16<06:53,  4.84it/s]

Processing tickers:  70%|███████   | 4772/6774 [16:17<06:49,  4.88it/s]

Processing tickers:  70%|███████   | 4773/6774 [16:17<06:45,  4.93it/s]

Processing tickers:  70%|███████   | 4774/6774 [16:17<06:43,  4.96it/s]

Processing tickers:  70%|███████   | 4775/6774 [16:17<06:40,  4.99it/s]

Processing tickers:  71%|███████   | 4776/6774 [16:17<06:38,  5.01it/s]

Processing tickers:  71%|███████   | 4777/6774 [16:18<06:39,  5.00it/s]

Processing tickers:  71%|███████   | 4778/6774 [16:18<06:39,  4.99it/s]

Processing tickers:  71%|███████   | 4779/6774 [16:18<06:45,  4.92it/s]

Processing tickers:  71%|███████   | 4780/6774 [16:18<07:01,  4.73it/s]

Processing tickers:  71%|███████   | 4781/6774 [16:18<06:53,  4.82it/s]

Processing tickers:  71%|███████   | 4782/6774 [16:19<06:51,  4.84it/s]

Processing tickers:  71%|███████   | 4783/6774 [16:19<06:51,  4.84it/s]

Processing tickers:  71%|███████   | 4784/6774 [16:19<06:50,  4.85it/s]

Processing tickers:  71%|███████   | 4785/6774 [16:19<06:51,  4.83it/s]

Processing tickers:  71%|███████   | 4786/6774 [16:19<06:52,  4.82it/s]

Processing tickers:  71%|███████   | 4787/6774 [16:20<06:56,  4.77it/s]

Processing tickers:  71%|███████   | 4788/6774 [16:20<06:50,  4.83it/s]

Processing tickers:  71%|███████   | 4789/6774 [16:20<07:03,  4.68it/s]

Processing tickers:  71%|███████   | 4790/6774 [16:20<06:58,  4.74it/s]

Processing tickers:  71%|███████   | 4791/6774 [16:21<06:52,  4.80it/s]

Processing tickers:  71%|███████   | 4792/6774 [16:21<06:50,  4.83it/s]

Processing tickers:  71%|███████   | 4793/6774 [16:21<06:58,  4.73it/s]

Processing tickers:  71%|███████   | 4794/6774 [16:21<06:51,  4.81it/s]

Processing tickers:  71%|███████   | 4795/6774 [16:21<06:56,  4.75it/s]

Processing tickers:  71%|███████   | 4796/6774 [16:22<06:48,  4.84it/s]

Processing tickers:  71%|███████   | 4797/6774 [16:22<06:44,  4.88it/s]

Processing tickers:  71%|███████   | 4798/6774 [16:22<06:45,  4.87it/s]

Processing tickers:  71%|███████   | 4799/6774 [16:22<06:42,  4.91it/s]

Processing tickers:  71%|███████   | 4800/6774 [16:22<06:38,  4.95it/s]

Processing tickers:  71%|███████   | 4801/6774 [16:23<06:38,  4.95it/s]

Processing tickers:  71%|███████   | 4802/6774 [16:23<06:37,  4.97it/s]

Processing tickers:  71%|███████   | 4803/6774 [16:23<06:45,  4.86it/s]

Processing tickers:  71%|███████   | 4804/6774 [16:23<06:54,  4.76it/s]

Processing tickers:  71%|███████   | 4805/6774 [16:23<07:03,  4.65it/s]

Processing tickers:  71%|███████   | 4806/6774 [16:24<06:52,  4.77it/s]

Processing tickers:  71%|███████   | 4807/6774 [16:24<06:51,  4.78it/s]

Processing tickers:  71%|███████   | 4808/6774 [16:24<06:47,  4.83it/s]

Processing tickers:  71%|███████   | 4809/6774 [16:24<06:41,  4.89it/s]

Processing tickers:  71%|███████   | 4810/6774 [16:24<06:40,  4.91it/s]

Processing tickers:  71%|███████   | 4811/6774 [16:25<06:39,  4.91it/s]

Processing tickers:  71%|███████   | 4812/6774 [16:25<06:37,  4.94it/s]

Processing tickers:  71%|███████   | 4813/6774 [16:25<06:37,  4.93it/s]

Processing tickers:  71%|███████   | 4814/6774 [16:25<06:37,  4.93it/s]

Processing tickers:  71%|███████   | 4815/6774 [16:25<06:35,  4.95it/s]

Processing tickers:  71%|███████   | 4816/6774 [16:26<06:34,  4.97it/s]

Processing tickers:  71%|███████   | 4817/6774 [16:26<06:42,  4.87it/s]

Processing tickers:  71%|███████   | 4818/6774 [16:26<06:58,  4.68it/s]

Processing tickers:  71%|███████   | 4819/6774 [16:26<06:53,  4.72it/s]

Processing tickers:  71%|███████   | 4820/6774 [16:27<06:46,  4.81it/s]

Processing tickers:  71%|███████   | 4821/6774 [16:27<06:42,  4.85it/s]

Processing tickers:  71%|███████   | 4822/6774 [16:27<06:38,  4.90it/s]

Processing tickers:  71%|███████   | 4823/6774 [16:27<06:43,  4.83it/s]

Processing tickers:  71%|███████   | 4824/6774 [16:27<06:44,  4.82it/s]

Processing tickers:  71%|███████   | 4825/6774 [16:28<06:44,  4.82it/s]

Processing tickers:  71%|███████   | 4826/6774 [16:28<06:35,  4.92it/s]

Processing tickers:  71%|███████▏  | 4827/6774 [16:28<06:51,  4.73it/s]

Processing tickers:  71%|███████▏  | 4828/6774 [16:28<06:44,  4.81it/s]

Processing tickers:  71%|███████▏  | 4829/6774 [16:28<06:39,  4.86it/s]

Processing tickers:  71%|███████▏  | 4830/6774 [16:29<06:36,  4.91it/s]

Processing tickers:  71%|███████▏  | 4831/6774 [16:29<06:45,  4.79it/s]

Processing tickers:  71%|███████▏  | 4832/6774 [16:29<06:48,  4.75it/s]

Processing tickers:  71%|███████▏  | 4833/6774 [16:29<06:41,  4.83it/s]

Processing tickers:  71%|███████▏  | 4834/6774 [16:29<06:40,  4.84it/s]

Processing tickers:  71%|███████▏  | 4835/6774 [16:30<06:36,  4.89it/s]

Processing tickers:  71%|███████▏  | 4836/6774 [16:30<06:34,  4.91it/s]

Processing tickers:  71%|███████▏  | 4837/6774 [16:30<06:34,  4.91it/s]

Processing tickers:  71%|███████▏  | 4838/6774 [16:30<06:32,  4.93it/s]

Processing tickers:  71%|███████▏  | 4839/6774 [16:30<06:30,  4.95it/s]

Processing tickers:  71%|███████▏  | 4840/6774 [16:31<06:33,  4.91it/s]

Processing tickers:  71%|███████▏  | 4841/6774 [16:31<06:44,  4.78it/s]

Processing tickers:  71%|███████▏  | 4842/6774 [16:31<06:39,  4.84it/s]

Processing tickers:  71%|███████▏  | 4843/6774 [16:31<06:40,  4.83it/s]

Processing tickers:  72%|███████▏  | 4844/6774 [16:31<06:33,  4.90it/s]

Processing tickers:  72%|███████▏  | 4845/6774 [16:32<06:32,  4.91it/s]

Processing tickers:  72%|███████▏  | 4846/6774 [16:32<06:30,  4.93it/s]

Processing tickers:  72%|███████▏  | 4847/6774 [16:32<06:28,  4.96it/s]

Processing tickers:  72%|███████▏  | 4848/6774 [16:32<06:41,  4.79it/s]

Processing tickers:  72%|███████▏  | 4849/6774 [16:32<06:36,  4.86it/s]

Processing tickers:  72%|███████▏  | 4850/6774 [16:33<06:31,  4.92it/s]

Processing tickers:  72%|███████▏  | 4851/6774 [16:33<06:27,  4.96it/s]

Processing tickers:  72%|███████▏  | 4852/6774 [16:33<06:38,  4.83it/s]

Processing tickers:  72%|███████▏  | 4853/6774 [16:33<06:32,  4.90it/s]

Processing tickers:  72%|███████▏  | 4854/6774 [16:33<06:29,  4.93it/s]

Processing tickers:  72%|███████▏  | 4855/6774 [16:34<06:32,  4.90it/s]

Processing tickers:  72%|███████▏  | 4856/6774 [16:34<06:27,  4.95it/s]

Processing tickers:  72%|███████▏  | 4857/6774 [16:34<06:30,  4.90it/s]

Processing tickers:  72%|███████▏  | 4858/6774 [16:34<06:28,  4.94it/s]

Processing tickers:  72%|███████▏  | 4859/6774 [16:34<06:26,  4.96it/s]

Processing tickers:  72%|███████▏  | 4860/6774 [16:35<06:28,  4.93it/s]

Processing tickers:  72%|███████▏  | 4861/6774 [16:35<06:36,  4.82it/s]

Processing tickers:  72%|███████▏  | 4862/6774 [16:35<06:29,  4.90it/s]

Processing tickers:  72%|███████▏  | 4863/6774 [16:35<06:27,  4.94it/s]

Processing tickers:  72%|███████▏  | 4864/6774 [16:36<06:28,  4.92it/s]

Processing tickers:  72%|███████▏  | 4865/6774 [16:36<06:25,  4.95it/s]

Processing tickers:  72%|███████▏  | 4866/6774 [16:36<06:39,  4.78it/s]

Processing tickers:  72%|███████▏  | 4867/6774 [16:36<06:33,  4.84it/s]

Processing tickers:  72%|███████▏  | 4868/6774 [16:36<06:43,  4.73it/s]

Processing tickers:  72%|███████▏  | 4869/6774 [16:37<06:39,  4.77it/s]

Processing tickers:  72%|███████▏  | 4870/6774 [16:37<06:32,  4.85it/s]

Processing tickers:  72%|███████▏  | 4871/6774 [16:37<06:29,  4.88it/s]

Processing tickers:  72%|███████▏  | 4872/6774 [16:37<06:32,  4.85it/s]

Processing tickers:  72%|███████▏  | 4873/6774 [16:37<06:31,  4.86it/s]

Processing tickers:  72%|███████▏  | 4874/6774 [16:38<06:35,  4.80it/s]

Processing tickers:  72%|███████▏  | 4875/6774 [16:38<06:29,  4.88it/s]

Processing tickers:  72%|███████▏  | 4876/6774 [16:38<06:33,  4.82it/s]

Processing tickers:  72%|███████▏  | 4877/6774 [16:38<06:45,  4.68it/s]

Processing tickers:  72%|███████▏  | 4878/6774 [16:38<06:38,  4.76it/s]

Processing tickers:  72%|███████▏  | 4879/6774 [16:39<06:41,  4.73it/s]

Processing tickers:  72%|███████▏  | 4880/6774 [16:39<06:35,  4.78it/s]

Processing tickers:  72%|███████▏  | 4881/6774 [16:39<06:29,  4.86it/s]

Processing tickers:  72%|███████▏  | 4882/6774 [16:39<06:25,  4.90it/s]

Processing tickers:  72%|███████▏  | 4883/6774 [16:39<06:23,  4.93it/s]

Processing tickers:  72%|███████▏  | 4884/6774 [16:40<06:21,  4.95it/s]

Processing tickers:  72%|███████▏  | 4885/6774 [16:40<06:21,  4.95it/s]

Processing tickers:  72%|███████▏  | 4886/6774 [16:40<06:20,  4.96it/s]

Processing tickers:  72%|███████▏  | 4887/6774 [16:40<06:20,  4.96it/s]

Processing tickers:  72%|███████▏  | 4888/6774 [16:40<06:19,  4.97it/s]

Processing tickers:  72%|███████▏  | 4889/6774 [16:41<06:18,  4.99it/s]

Processing tickers:  72%|███████▏  | 4890/6774 [16:41<06:16,  5.01it/s]

Processing tickers:  72%|███████▏  | 4891/6774 [16:41<06:15,  5.01it/s]

Processing tickers:  72%|███████▏  | 4892/6774 [16:41<06:22,  4.91it/s]

Processing tickers:  72%|███████▏  | 4893/6774 [16:41<06:24,  4.89it/s]

Processing tickers:  72%|███████▏  | 4894/6774 [16:42<06:19,  4.95it/s]

Processing tickers:  72%|███████▏  | 4895/6774 [16:42<06:17,  4.98it/s]

Processing tickers:  72%|███████▏  | 4896/6774 [16:42<06:18,  4.96it/s]

Processing tickers:  72%|███████▏  | 4897/6774 [16:42<06:17,  4.97it/s]

Processing tickers:  72%|███████▏  | 4898/6774 [16:42<06:16,  4.98it/s]

Processing tickers:  72%|███████▏  | 4899/6774 [16:43<06:17,  4.97it/s]

Processing tickers:  72%|███████▏  | 4900/6774 [16:43<06:15,  4.99it/s]

Processing tickers:  72%|███████▏  | 4901/6774 [16:43<06:27,  4.83it/s]

Processing tickers:  72%|███████▏  | 4902/6774 [16:43<06:26,  4.84it/s]

Processing tickers:  72%|███████▏  | 4903/6774 [16:43<06:24,  4.87it/s]

Processing tickers:  72%|███████▏  | 4904/6774 [16:44<06:19,  4.92it/s]

Processing tickers:  72%|███████▏  | 4905/6774 [16:44<06:20,  4.91it/s]

Processing tickers:  72%|███████▏  | 4906/6774 [16:44<06:26,  4.83it/s]

Processing tickers:  72%|███████▏  | 4907/6774 [16:44<06:27,  4.82it/s]

Processing tickers:  72%|███████▏  | 4908/6774 [16:45<06:24,  4.85it/s]

Processing tickers:  72%|███████▏  | 4909/6774 [16:45<06:22,  4.87it/s]

Processing tickers:  72%|███████▏  | 4910/6774 [16:45<06:18,  4.92it/s]

Processing tickers:  72%|███████▏  | 4911/6774 [16:45<06:16,  4.95it/s]

Processing tickers:  73%|███████▎  | 4912/6774 [16:45<06:16,  4.95it/s]

Processing tickers:  73%|███████▎  | 4913/6774 [16:46<06:15,  4.96it/s]

Processing tickers:  73%|███████▎  | 4914/6774 [16:46<06:16,  4.95it/s]

Processing tickers:  73%|███████▎  | 4915/6774 [16:46<06:17,  4.93it/s]

Processing tickers:  73%|███████▎  | 4916/6774 [16:46<06:15,  4.94it/s]

Processing tickers:  73%|███████▎  | 4917/6774 [16:46<06:14,  4.95it/s]

Processing tickers:  73%|███████▎  | 4918/6774 [16:47<06:26,  4.80it/s]

Processing tickers:  73%|███████▎  | 4919/6774 [16:47<06:39,  4.65it/s]

Processing tickers:  73%|███████▎  | 4920/6774 [16:47<06:32,  4.72it/s]

Processing tickers:  73%|███████▎  | 4921/6774 [16:47<06:28,  4.77it/s]

Processing tickers:  73%|███████▎  | 4922/6774 [16:47<06:24,  4.82it/s]

Processing tickers:  73%|███████▎  | 4923/6774 [16:48<06:20,  4.86it/s]

Processing tickers:  73%|███████▎  | 4924/6774 [16:48<06:30,  4.74it/s]

Processing tickers:  73%|███████▎  | 4925/6774 [16:48<06:23,  4.82it/s]

Processing tickers:  73%|███████▎  | 4926/6774 [16:48<06:24,  4.81it/s]

Processing tickers:  73%|███████▎  | 4927/6774 [16:48<06:21,  4.84it/s]

Processing tickers:  73%|███████▎  | 4928/6774 [16:49<06:18,  4.88it/s]

Processing tickers:  73%|███████▎  | 4929/6774 [16:49<06:14,  4.93it/s]

Processing tickers:  73%|███████▎  | 4930/6774 [16:49<06:19,  4.86it/s]

Processing tickers:  73%|███████▎  | 4931/6774 [16:49<06:14,  4.92it/s]

Processing tickers:  73%|███████▎  | 4932/6774 [16:49<06:11,  4.95it/s]

Processing tickers:  73%|███████▎  | 4933/6774 [16:50<06:11,  4.96it/s]

Processing tickers:  73%|███████▎  | 4934/6774 [16:50<06:10,  4.97it/s]

Processing tickers:  73%|███████▎  | 4935/6774 [16:50<06:19,  4.84it/s]

Processing tickers:  73%|███████▎  | 4936/6774 [16:50<06:15,  4.90it/s]

Processing tickers:  73%|███████▎  | 4937/6774 [16:50<06:17,  4.87it/s]

Processing tickers:  73%|███████▎  | 4938/6774 [16:51<06:14,  4.91it/s]

Processing tickers:  73%|███████▎  | 4939/6774 [16:51<06:13,  4.91it/s]

Processing tickers:  73%|███████▎  | 4940/6774 [16:51<06:21,  4.81it/s]

Processing tickers:  73%|███████▎  | 4941/6774 [16:51<06:20,  4.82it/s]

Processing tickers:  73%|███████▎  | 4942/6774 [16:52<06:28,  4.72it/s]

Processing tickers:  73%|███████▎  | 4943/6774 [16:52<06:22,  4.79it/s]

Processing tickers:  73%|███████▎  | 4944/6774 [16:52<06:19,  4.82it/s]

Processing tickers:  73%|███████▎  | 4945/6774 [16:52<06:17,  4.84it/s]

Processing tickers:  73%|███████▎  | 4946/6774 [16:52<06:13,  4.90it/s]

Processing tickers:  73%|███████▎  | 4947/6774 [16:53<06:14,  4.88it/s]

Processing tickers:  73%|███████▎  | 4948/6774 [16:53<06:13,  4.89it/s]

Processing tickers:  73%|███████▎  | 4949/6774 [16:53<06:13,  4.89it/s]

Processing tickers:  73%|███████▎  | 4950/6774 [16:53<06:17,  4.83it/s]

Processing tickers:  73%|███████▎  | 4951/6774 [16:53<06:56,  4.38it/s]

Processing tickers:  73%|███████▎  | 4952/6774 [16:54<06:39,  4.56it/s]

Processing tickers:  73%|███████▎  | 4953/6774 [16:54<06:27,  4.70it/s]

Processing tickers:  73%|███████▎  | 4954/6774 [16:54<06:21,  4.77it/s]

Processing tickers:  73%|███████▎  | 4955/6774 [16:54<06:14,  4.86it/s]

Processing tickers:  73%|███████▎  | 4956/6774 [16:54<06:10,  4.90it/s]

Processing tickers:  73%|███████▎  | 4957/6774 [16:55<06:07,  4.95it/s]

Processing tickers:  73%|███████▎  | 4958/6774 [16:55<06:08,  4.93it/s]

Processing tickers:  73%|███████▎  | 4959/6774 [16:55<06:09,  4.91it/s]

Processing tickers:  73%|███████▎  | 4960/6774 [16:55<06:09,  4.91it/s]

Processing tickers:  73%|███████▎  | 4961/6774 [16:55<06:06,  4.95it/s]

Processing tickers:  73%|███████▎  | 4962/6774 [16:56<06:04,  4.97it/s]

Processing tickers:  73%|███████▎  | 4963/6774 [16:56<06:04,  4.97it/s]

Processing tickers:  73%|███████▎  | 4964/6774 [16:56<06:04,  4.96it/s]

Processing tickers:  73%|███████▎  | 4965/6774 [16:56<06:03,  4.98it/s]

Processing tickers:  73%|███████▎  | 4966/6774 [16:56<06:02,  4.99it/s]

Processing tickers:  73%|███████▎  | 4967/6774 [16:57<06:05,  4.94it/s]

Processing tickers:  73%|███████▎  | 4968/6774 [16:57<06:04,  4.95it/s]

Processing tickers:  73%|███████▎  | 4969/6774 [16:57<06:24,  4.70it/s]

Processing tickers:  73%|███████▎  | 4970/6774 [16:57<06:19,  4.75it/s]

Processing tickers:  73%|███████▎  | 4971/6774 [16:58<06:16,  4.78it/s]

Processing tickers:  73%|███████▎  | 4972/6774 [16:58<06:25,  4.67it/s]

Processing tickers:  73%|███████▎  | 4973/6774 [16:58<06:16,  4.78it/s]

Processing tickers:  73%|███████▎  | 4974/6774 [16:58<06:11,  4.85it/s]

Processing tickers:  73%|███████▎  | 4975/6774 [16:58<06:19,  4.74it/s]

Processing tickers:  73%|███████▎  | 4976/6774 [16:59<06:16,  4.77it/s]

Processing tickers:  73%|███████▎  | 4977/6774 [16:59<06:29,  4.61it/s]

Processing tickers:  73%|███████▎  | 4978/6774 [16:59<06:23,  4.69it/s]

Processing tickers:  74%|███████▎  | 4979/6774 [16:59<06:16,  4.77it/s]

Processing tickers:  74%|███████▎  | 4980/6774 [16:59<06:16,  4.77it/s]

Processing tickers:  74%|███████▎  | 4981/6774 [17:00<06:10,  4.83it/s]

Processing tickers:  74%|███████▎  | 4982/6774 [17:00<06:19,  4.72it/s]

Processing tickers:  74%|███████▎  | 4983/6774 [17:00<06:13,  4.80it/s]

Processing tickers:  74%|███████▎  | 4984/6774 [17:00<06:12,  4.81it/s]

Processing tickers:  74%|███████▎  | 4985/6774 [17:00<06:06,  4.87it/s]

Processing tickers:  74%|███████▎  | 4986/6774 [17:01<06:03,  4.91it/s]

Processing tickers:  74%|███████▎  | 4987/6774 [17:01<06:07,  4.86it/s]

Processing tickers:  74%|███████▎  | 4988/6774 [17:01<06:03,  4.91it/s]

Processing tickers:  74%|███████▎  | 4989/6774 [17:01<06:03,  4.91it/s]

Processing tickers:  74%|███████▎  | 4990/6774 [17:01<06:00,  4.95it/s]

Processing tickers:  74%|███████▎  | 4991/6774 [17:02<06:00,  4.95it/s]

Processing tickers:  74%|███████▎  | 4992/6774 [17:02<05:57,  4.98it/s]

Processing tickers:  74%|███████▎  | 4993/6774 [17:02<05:57,  4.99it/s]

Processing tickers:  74%|███████▎  | 4994/6774 [17:02<05:58,  4.97it/s]

Processing tickers:  74%|███████▎  | 4995/6774 [17:02<05:56,  4.99it/s]

Processing tickers:  74%|███████▍  | 4996/6774 [17:03<05:58,  4.95it/s]

Processing tickers:  74%|███████▍  | 4997/6774 [17:03<06:01,  4.92it/s]

Processing tickers:  74%|███████▍  | 4998/6774 [17:03<06:16,  4.72it/s]

Processing tickers:  74%|███████▍  | 4999/6774 [17:03<06:13,  4.75it/s]

Processing tickers:  74%|███████▍  | 5000/6774 [17:03<06:07,  4.83it/s]

Processing tickers:  74%|███████▍  | 5001/6774 [17:04<06:03,  4.87it/s]

Processing tickers:  74%|███████▍  | 5002/6774 [17:04<05:59,  4.92it/s]

Processing tickers:  74%|███████▍  | 5003/6774 [17:04<06:18,  4.68it/s]

Processing tickers:  74%|███████▍  | 5004/6774 [17:04<06:10,  4.77it/s]

Processing tickers:  74%|███████▍  | 5005/6774 [17:05<06:06,  4.83it/s]

Processing tickers:  74%|███████▍  | 5006/6774 [17:05<06:00,  4.90it/s]

Processing tickers:  74%|███████▍  | 5007/6774 [17:05<06:03,  4.87it/s]

Processing tickers:  74%|███████▍  | 5008/6774 [17:05<05:58,  4.92it/s]

Processing tickers:  74%|███████▍  | 5009/6774 [17:05<05:57,  4.94it/s]

Processing tickers:  74%|███████▍  | 5010/6774 [17:06<05:57,  4.94it/s]

Processing tickers:  74%|███████▍  | 5011/6774 [17:06<05:59,  4.90it/s]

Processing tickers:  74%|███████▍  | 5012/6774 [17:06<06:09,  4.77it/s]

Processing tickers:  74%|███████▍  | 5013/6774 [17:06<06:06,  4.81it/s]

Processing tickers:  74%|███████▍  | 5014/6774 [17:06<06:04,  4.83it/s]

Processing tickers:  74%|███████▍  | 5015/6774 [17:07<05:58,  4.91it/s]

Processing tickers:  74%|███████▍  | 5016/6774 [17:07<06:18,  4.64it/s]

Processing tickers:  74%|███████▍  | 5017/6774 [17:07<06:09,  4.76it/s]

Processing tickers:  74%|███████▍  | 5018/6774 [17:07<06:25,  4.56it/s]

Processing tickers:  74%|███████▍  | 5019/6774 [17:07<06:21,  4.60it/s]

Processing tickers:  74%|███████▍  | 5020/6774 [17:08<06:11,  4.72it/s]

Processing tickers:  74%|███████▍  | 5021/6774 [17:08<06:14,  4.68it/s]

Processing tickers:  74%|███████▍  | 5022/6774 [17:08<06:04,  4.80it/s]

Processing tickers:  74%|███████▍  | 5023/6774 [17:08<05:59,  4.87it/s]

Processing tickers:  74%|███████▍  | 5024/6774 [17:09<06:12,  4.70it/s]

Processing tickers:  74%|███████▍  | 5025/6774 [17:09<06:06,  4.77it/s]

Processing tickers:  74%|███████▍  | 5026/6774 [17:09<05:59,  4.86it/s]

Processing tickers:  74%|███████▍  | 5027/6774 [17:09<05:57,  4.89it/s]

Processing tickers:  74%|███████▍  | 5028/6774 [17:09<05:54,  4.93it/s]

Processing tickers:  74%|███████▍  | 5029/6774 [17:10<05:55,  4.91it/s]

Processing tickers:  74%|███████▍  | 5030/6774 [17:10<05:52,  4.95it/s]

Processing tickers:  74%|███████▍  | 5031/6774 [17:10<05:50,  4.97it/s]

Processing tickers:  74%|███████▍  | 5032/6774 [17:10<05:50,  4.97it/s]

Processing tickers:  74%|███████▍  | 5033/6774 [17:10<05:50,  4.97it/s]

Processing tickers:  74%|███████▍  | 5034/6774 [17:11<05:46,  5.02it/s]

Processing tickers:  74%|███████▍  | 5035/6774 [17:11<05:53,  4.92it/s]

Processing tickers:  74%|███████▍  | 5036/6774 [17:11<05:58,  4.84it/s]

Processing tickers:  74%|███████▍  | 5037/6774 [17:11<05:54,  4.90it/s]

Processing tickers:  74%|███████▍  | 5038/6774 [17:11<06:02,  4.79it/s]

Processing tickers:  74%|███████▍  | 5039/6774 [17:12<05:55,  4.88it/s]

Processing tickers:  74%|███████▍  | 5040/6774 [17:12<05:59,  4.82it/s]

Processing tickers:  74%|███████▍  | 5041/6774 [17:12<06:00,  4.80it/s]

Processing tickers:  74%|███████▍  | 5042/6774 [17:12<06:01,  4.79it/s]

Processing tickers:  74%|███████▍  | 5043/6774 [17:12<06:03,  4.76it/s]

Processing tickers:  74%|███████▍  | 5044/6774 [17:13<06:00,  4.80it/s]

Processing tickers:  74%|███████▍  | 5045/6774 [17:13<05:54,  4.88it/s]

Processing tickers:  74%|███████▍  | 5046/6774 [17:13<06:07,  4.70it/s]

Processing tickers:  75%|███████▍  | 5047/6774 [17:13<06:02,  4.76it/s]

Processing tickers:  75%|███████▍  | 5048/6774 [17:13<05:56,  4.85it/s]

Processing tickers:  75%|███████▍  | 5049/6774 [17:14<05:52,  4.90it/s]

Processing tickers:  75%|███████▍  | 5050/6774 [17:14<06:01,  4.77it/s]

Processing tickers:  75%|███████▍  | 5051/6774 [17:14<05:57,  4.82it/s]

Processing tickers:  75%|███████▍  | 5052/6774 [17:14<05:53,  4.88it/s]

Processing tickers:  75%|███████▍  | 5053/6774 [17:14<05:48,  4.94it/s]

Processing tickers:  75%|███████▍  | 5054/6774 [17:15<06:02,  4.75it/s]

Processing tickers:  75%|███████▍  | 5055/6774 [17:15<05:56,  4.82it/s]

Processing tickers:  75%|███████▍  | 5056/6774 [17:15<05:58,  4.79it/s]

Processing tickers:  75%|███████▍  | 5057/6774 [17:15<05:55,  4.83it/s]

Processing tickers:  75%|███████▍  | 5058/6774 [17:15<05:51,  4.89it/s]

Processing tickers:  75%|███████▍  | 5059/6774 [17:16<05:48,  4.92it/s]

Processing tickers:  75%|███████▍  | 5060/6774 [17:16<05:47,  4.93it/s]

Processing tickers:  75%|███████▍  | 5061/6774 [17:16<05:52,  4.86it/s]

Processing tickers:  75%|███████▍  | 5062/6774 [17:16<05:50,  4.88it/s]

Processing tickers:  75%|███████▍  | 5063/6774 [17:17<05:56,  4.79it/s]

Processing tickers:  75%|███████▍  | 5064/6774 [17:17<05:50,  4.89it/s]

Processing tickers:  75%|███████▍  | 5065/6774 [17:17<05:47,  4.91it/s]

Processing tickers:  75%|███████▍  | 5066/6774 [17:17<05:43,  4.97it/s]

Processing tickers:  75%|███████▍  | 5067/6774 [17:17<05:44,  4.95it/s]

Processing tickers:  75%|███████▍  | 5068/6774 [17:18<05:44,  4.95it/s]

Processing tickers:  75%|███████▍  | 5069/6774 [17:18<05:42,  4.98it/s]

Processing tickers:  75%|███████▍  | 5070/6774 [17:18<05:40,  5.01it/s]

Processing tickers:  75%|███████▍  | 5071/6774 [17:18<05:40,  5.00it/s]

Processing tickers:  75%|███████▍  | 5072/6774 [17:18<05:51,  4.84it/s]

Processing tickers:  75%|███████▍  | 5073/6774 [17:19<05:54,  4.79it/s]

Processing tickers:  75%|███████▍  | 5074/6774 [17:19<05:50,  4.85it/s]

Processing tickers:  75%|███████▍  | 5075/6774 [17:19<05:53,  4.80it/s]

Processing tickers:  75%|███████▍  | 5076/6774 [17:19<05:50,  4.85it/s]

Processing tickers:  75%|███████▍  | 5077/6774 [17:19<05:48,  4.87it/s]

Processing tickers:  75%|███████▍  | 5078/6774 [17:20<05:44,  4.92it/s]

Processing tickers:  75%|███████▍  | 5079/6774 [17:20<05:39,  4.99it/s]

Processing tickers:  75%|███████▍  | 5080/6774 [17:20<05:42,  4.94it/s]

Processing tickers:  75%|███████▌  | 5081/6774 [17:20<05:46,  4.89it/s]

Processing tickers:  75%|███████▌  | 5082/6774 [17:20<05:45,  4.89it/s]

Processing tickers:  75%|███████▌  | 5083/6774 [17:21<05:44,  4.91it/s]

Processing tickers:  75%|███████▌  | 5084/6774 [17:21<05:42,  4.93it/s]

Processing tickers:  75%|███████▌  | 5085/6774 [17:21<05:51,  4.80it/s]

Processing tickers:  75%|███████▌  | 5086/6774 [17:21<05:47,  4.86it/s]

Processing tickers:  75%|███████▌  | 5087/6774 [17:21<05:44,  4.90it/s]

Processing tickers:  75%|███████▌  | 5088/6774 [17:22<05:41,  4.93it/s]

Processing tickers:  75%|███████▌  | 5089/6774 [17:22<05:38,  4.97it/s]

Processing tickers:  75%|███████▌  | 5090/6774 [17:22<05:43,  4.91it/s]

Processing tickers:  75%|███████▌  | 5091/6774 [17:22<05:40,  4.94it/s]

Processing tickers:  75%|███████▌  | 5092/6774 [17:22<05:37,  4.98it/s]

Processing tickers:  75%|███████▌  | 5093/6774 [17:23<05:46,  4.85it/s]

Processing tickers:  75%|███████▌  | 5094/6774 [17:23<05:42,  4.91it/s]

Processing tickers:  75%|███████▌  | 5095/6774 [17:23<05:37,  4.97it/s]

Processing tickers:  75%|███████▌  | 5096/6774 [17:23<05:36,  4.99it/s]

Processing tickers:  75%|███████▌  | 5097/6774 [17:23<05:33,  5.03it/s]

Processing tickers:  75%|███████▌  | 5098/6774 [17:24<05:33,  5.02it/s]

Processing tickers:  75%|███████▌  | 5099/6774 [17:24<05:33,  5.03it/s]

Processing tickers:  75%|███████▌  | 5100/6774 [17:24<05:32,  5.04it/s]

Processing tickers:  75%|███████▌  | 5101/6774 [17:24<05:33,  5.02it/s]

Processing tickers:  75%|███████▌  | 5102/6774 [17:24<05:34,  5.00it/s]

Processing tickers:  75%|███████▌  | 5103/6774 [17:25<05:35,  4.99it/s]

Processing tickers:  75%|███████▌  | 5104/6774 [17:25<05:33,  5.01it/s]

Processing tickers:  75%|███████▌  | 5105/6774 [17:25<05:45,  4.83it/s]

Processing tickers:  75%|███████▌  | 5106/6774 [17:25<05:48,  4.79it/s]

Processing tickers:  75%|███████▌  | 5107/6774 [17:25<05:43,  4.85it/s]

Processing tickers:  75%|███████▌  | 5108/6774 [17:26<05:49,  4.76it/s]

Processing tickers:  75%|███████▌  | 5109/6774 [17:26<05:43,  4.84it/s]

Processing tickers:  75%|███████▌  | 5110/6774 [17:26<05:41,  4.88it/s]

Processing tickers:  75%|███████▌  | 5111/6774 [17:26<05:44,  4.82it/s]

Processing tickers:  75%|███████▌  | 5112/6774 [17:26<05:42,  4.85it/s]

Processing tickers:  75%|███████▌  | 5113/6774 [17:27<05:39,  4.89it/s]

Processing tickers:  75%|███████▌  | 5114/6774 [17:27<05:36,  4.94it/s]

Processing tickers:  76%|███████▌  | 5115/6774 [17:27<05:33,  4.98it/s]

Processing tickers:  76%|███████▌  | 5116/6774 [17:27<05:32,  4.99it/s]

Processing tickers:  76%|███████▌  | 5117/6774 [17:27<05:34,  4.95it/s]

Processing tickers:  76%|███████▌  | 5118/6774 [17:28<05:33,  4.96it/s]

Processing tickers:  76%|███████▌  | 5119/6774 [17:28<05:33,  4.96it/s]

Processing tickers:  76%|███████▌  | 5120/6774 [17:28<05:31,  4.99it/s]

Processing tickers:  76%|███████▌  | 5121/6774 [17:28<05:36,  4.91it/s]

Processing tickers:  76%|███████▌  | 5122/6774 [17:29<05:37,  4.89it/s]

Processing tickers:  76%|███████▌  | 5123/6774 [17:29<05:35,  4.92it/s]

Processing tickers:  76%|███████▌  | 5124/6774 [17:29<05:33,  4.94it/s]

Processing tickers:  76%|███████▌  | 5125/6774 [17:29<05:32,  4.96it/s]

Processing tickers:  76%|███████▌  | 5126/6774 [17:29<05:33,  4.95it/s]

Processing tickers:  76%|███████▌  | 5127/6774 [17:30<05:32,  4.96it/s]

Processing tickers:  76%|███████▌  | 5128/6774 [17:30<05:30,  4.98it/s]

Processing tickers:  76%|███████▌  | 5129/6774 [17:30<05:28,  5.01it/s]

Processing tickers:  76%|███████▌  | 5130/6774 [17:30<05:33,  4.93it/s]

Processing tickers:  76%|███████▌  | 5131/6774 [17:30<05:31,  4.96it/s]

Processing tickers:  76%|███████▌  | 5132/6774 [17:31<05:29,  4.98it/s]

Processing tickers:  76%|███████▌  | 5133/6774 [17:31<05:36,  4.88it/s]

Processing tickers:  76%|███████▌  | 5134/6774 [17:31<05:34,  4.90it/s]

Processing tickers:  76%|███████▌  | 5135/6774 [17:31<05:30,  4.96it/s]

Processing tickers:  76%|███████▌  | 5136/6774 [17:31<05:27,  5.01it/s]

Processing tickers:  76%|███████▌  | 5137/6774 [17:32<05:39,  4.82it/s]

Processing tickers:  76%|███████▌  | 5138/6774 [17:32<05:40,  4.80it/s]

Processing tickers:  76%|███████▌  | 5139/6774 [17:32<05:41,  4.79it/s]

Processing tickers:  76%|███████▌  | 5140/6774 [17:32<05:40,  4.80it/s]

Processing tickers:  76%|███████▌  | 5141/6774 [17:32<05:41,  4.79it/s]

Processing tickers:  76%|███████▌  | 5142/6774 [17:33<05:37,  4.84it/s]

Processing tickers:  76%|███████▌  | 5143/6774 [17:33<05:39,  4.81it/s]

Processing tickers:  76%|███████▌  | 5144/6774 [17:33<05:38,  4.82it/s]

Processing tickers:  76%|███████▌  | 5145/6774 [17:33<05:35,  4.86it/s]

Processing tickers:  76%|███████▌  | 5146/6774 [17:33<05:33,  4.89it/s]

Processing tickers:  76%|███████▌  | 5147/6774 [17:34<05:29,  4.93it/s]

Processing tickers:  76%|███████▌  | 5148/6774 [17:34<05:26,  4.98it/s]

Processing tickers:  76%|███████▌  | 5149/6774 [17:34<05:26,  4.98it/s]

Processing tickers:  76%|███████▌  | 5150/6774 [17:34<05:24,  5.00it/s]

Processing tickers:  76%|███████▌  | 5151/6774 [17:34<05:24,  5.00it/s]

Processing tickers:  76%|███████▌  | 5152/6774 [17:35<05:22,  5.03it/s]

Processing tickers:  76%|███████▌  | 5153/6774 [17:35<05:24,  5.00it/s]

Processing tickers:  76%|███████▌  | 5154/6774 [17:35<05:24,  5.00it/s]

Processing tickers:  76%|███████▌  | 5155/6774 [17:35<05:25,  4.97it/s]

Processing tickers:  76%|███████▌  | 5156/6774 [17:35<05:24,  4.99it/s]

Processing tickers:  76%|███████▌  | 5157/6774 [17:36<05:23,  5.00it/s]

Processing tickers:  76%|███████▌  | 5158/6774 [17:36<05:21,  5.02it/s]

Processing tickers:  76%|███████▌  | 5159/6774 [17:36<05:21,  5.03it/s]

Processing tickers:  76%|███████▌  | 5160/6774 [17:36<05:21,  5.02it/s]

Processing tickers:  76%|███████▌  | 5161/6774 [17:36<05:26,  4.95it/s]

Processing tickers:  76%|███████▌  | 5162/6774 [17:37<05:25,  4.95it/s]

Processing tickers:  76%|███████▌  | 5163/6774 [17:37<05:22,  5.00it/s]

Processing tickers:  76%|███████▌  | 5164/6774 [17:37<05:24,  4.96it/s]

Processing tickers:  76%|███████▌  | 5165/6774 [17:37<05:23,  4.97it/s]

Processing tickers:  76%|███████▋  | 5166/6774 [17:37<05:26,  4.93it/s]

Processing tickers:  76%|███████▋  | 5167/6774 [17:38<05:25,  4.94it/s]

Processing tickers:  76%|███████▋  | 5168/6774 [17:38<05:24,  4.96it/s]

Processing tickers:  76%|███████▋  | 5169/6774 [17:38<05:27,  4.90it/s]

Processing tickers:  76%|███████▋  | 5170/6774 [17:38<05:28,  4.88it/s]

Processing tickers:  76%|███████▋  | 5171/6774 [17:38<05:30,  4.85it/s]

Processing tickers:  76%|███████▋  | 5172/6774 [17:39<05:39,  4.72it/s]

Processing tickers:  76%|███████▋  | 5173/6774 [17:39<05:34,  4.79it/s]

Processing tickers:  76%|███████▋  | 5174/6774 [17:39<05:30,  4.84it/s]

Processing tickers:  76%|███████▋  | 5175/6774 [17:39<05:26,  4.89it/s]

Processing tickers:  76%|███████▋  | 5176/6774 [17:39<05:24,  4.92it/s]

Processing tickers:  76%|███████▋  | 5177/6774 [17:40<05:23,  4.94it/s]

Processing tickers:  76%|███████▋  | 5178/6774 [17:40<05:23,  4.94it/s]

Processing tickers:  76%|███████▋  | 5179/6774 [17:40<05:21,  4.97it/s]

Processing tickers:  76%|███████▋  | 5180/6774 [17:40<05:19,  4.98it/s]

Processing tickers:  76%|███████▋  | 5181/6774 [17:40<05:17,  5.01it/s]

Processing tickers:  76%|███████▋  | 5182/6774 [17:41<05:17,  5.01it/s]

Processing tickers:  77%|███████▋  | 5183/6774 [17:41<05:16,  5.03it/s]

Processing tickers:  77%|███████▋  | 5184/6774 [17:41<05:18,  5.00it/s]

Processing tickers:  77%|███████▋  | 5185/6774 [17:41<05:16,  5.02it/s]

Processing tickers:  77%|███████▋  | 5186/6774 [17:41<05:24,  4.90it/s]

Processing tickers:  77%|███████▋  | 5187/6774 [17:42<05:20,  4.95it/s]

Processing tickers:  77%|███████▋  | 5188/6774 [17:42<05:19,  4.96it/s]

Processing tickers:  77%|███████▋  | 5189/6774 [17:42<05:18,  4.97it/s]

Processing tickers:  77%|███████▋  | 5190/6774 [17:42<05:15,  5.02it/s]

Processing tickers:  77%|███████▋  | 5191/6774 [17:42<05:17,  4.99it/s]

Processing tickers:  77%|███████▋  | 5192/6774 [17:43<05:17,  4.98it/s]

Processing tickers:  77%|███████▋  | 5193/6774 [17:43<05:19,  4.95it/s]

Processing tickers:  77%|███████▋  | 5194/6774 [17:43<05:26,  4.84it/s]

Processing tickers:  77%|███████▋  | 5195/6774 [17:43<05:40,  4.64it/s]

Processing tickers:  77%|███████▋  | 5196/6774 [17:44<05:35,  4.70it/s]

Processing tickers:  77%|███████▋  | 5197/6774 [17:44<05:30,  4.77it/s]

Processing tickers:  77%|███████▋  | 5198/6774 [17:44<05:28,  4.80it/s]

Processing tickers:  77%|███████▋  | 5199/6774 [17:44<05:29,  4.78it/s]

Processing tickers:  77%|███████▋  | 5200/6774 [17:44<05:27,  4.80it/s]

Processing tickers:  77%|███████▋  | 5201/6774 [17:45<05:23,  4.87it/s]

Processing tickers:  77%|███████▋  | 5202/6774 [17:45<05:26,  4.82it/s]

Processing tickers:  77%|███████▋  | 5203/6774 [17:45<05:29,  4.77it/s]

Processing tickers:  77%|███████▋  | 5204/6774 [17:45<05:29,  4.76it/s]

Processing tickers:  77%|███████▋  | 5205/6774 [17:45<05:25,  4.81it/s]

Processing tickers:  77%|███████▋  | 5206/6774 [17:46<05:23,  4.85it/s]

Processing tickers:  77%|███████▋  | 5207/6774 [17:46<05:20,  4.88it/s]

Processing tickers:  77%|███████▋  | 5208/6774 [17:46<05:19,  4.91it/s]

Processing tickers:  77%|███████▋  | 5209/6774 [17:46<05:21,  4.87it/s]

Processing tickers:  77%|███████▋  | 5210/6774 [17:46<05:25,  4.80it/s]

Processing tickers:  77%|███████▋  | 5211/6774 [17:47<05:21,  4.86it/s]

Processing tickers:  77%|███████▋  | 5212/6774 [17:47<05:16,  4.93it/s]

Processing tickers:  77%|███████▋  | 5213/6774 [17:47<05:20,  4.87it/s]

Processing tickers:  77%|███████▋  | 5214/6774 [17:47<05:19,  4.88it/s]

Processing tickers:  77%|███████▋  | 5215/6774 [17:47<05:14,  4.95it/s]

Processing tickers:  77%|███████▋  | 5216/6774 [17:48<05:13,  4.98it/s]

Processing tickers:  77%|███████▋  | 5217/6774 [17:48<05:10,  5.01it/s]

Processing tickers:  77%|███████▋  | 5218/6774 [17:48<05:09,  5.02it/s]

Processing tickers:  77%|███████▋  | 5219/6774 [17:48<05:10,  5.01it/s]

Processing tickers:  77%|███████▋  | 5220/6774 [17:48<05:09,  5.02it/s]

Processing tickers:  77%|███████▋  | 5221/6774 [17:49<05:13,  4.95it/s]

Processing tickers:  77%|███████▋  | 5222/6774 [17:49<05:10,  5.00it/s]

Processing tickers:  77%|███████▋  | 5223/6774 [17:49<05:13,  4.95it/s]

Processing tickers:  77%|███████▋  | 5224/6774 [17:49<05:13,  4.94it/s]

Processing tickers:  77%|███████▋  | 5225/6774 [17:49<05:12,  4.95it/s]

Processing tickers:  77%|███████▋  | 5226/6774 [17:50<05:09,  5.00it/s]

Processing tickers:  77%|███████▋  | 5227/6774 [17:50<05:08,  5.02it/s]

Processing tickers:  77%|███████▋  | 5228/6774 [17:50<05:09,  5.00it/s]

Processing tickers:  77%|███████▋  | 5229/6774 [17:50<05:09,  4.99it/s]

Processing tickers:  77%|███████▋  | 5230/6774 [17:50<05:13,  4.92it/s]

Processing tickers:  77%|███████▋  | 5231/6774 [17:51<05:16,  4.88it/s]

Processing tickers:  77%|███████▋  | 5232/6774 [17:51<05:12,  4.93it/s]

Processing tickers:  77%|███████▋  | 5233/6774 [17:51<05:12,  4.94it/s]

Processing tickers:  77%|███████▋  | 5234/6774 [17:51<05:09,  4.98it/s]

Processing tickers:  77%|███████▋  | 5235/6774 [17:51<05:08,  4.98it/s]

Processing tickers:  77%|███████▋  | 5236/6774 [17:52<05:11,  4.93it/s]

Processing tickers:  77%|███████▋  | 5237/6774 [17:52<05:09,  4.97it/s]

Processing tickers:  77%|███████▋  | 5238/6774 [17:52<05:08,  4.97it/s]

Processing tickers:  77%|███████▋  | 5239/6774 [17:52<05:08,  4.98it/s]

Processing tickers:  77%|███████▋  | 5240/6774 [17:52<05:05,  5.01it/s]

Processing tickers:  77%|███████▋  | 5241/6774 [17:53<05:07,  4.98it/s]

Processing tickers:  77%|███████▋  | 5242/6774 [17:53<05:09,  4.95it/s]

Processing tickers:  77%|███████▋  | 5243/6774 [17:53<05:08,  4.96it/s]

Processing tickers:  77%|███████▋  | 5244/6774 [17:53<05:11,  4.92it/s]

Processing tickers:  77%|███████▋  | 5245/6774 [17:53<05:08,  4.95it/s]

Processing tickers:  77%|███████▋  | 5246/6774 [17:54<05:09,  4.93it/s]

Processing tickers:  77%|███████▋  | 5247/6774 [17:54<05:08,  4.94it/s]

Processing tickers:  77%|███████▋  | 5248/6774 [17:54<05:08,  4.95it/s]

Processing tickers:  77%|███████▋  | 5249/6774 [17:54<05:04,  5.01it/s]

Processing tickers:  78%|███████▊  | 5250/6774 [17:54<05:03,  5.02it/s]

Processing tickers:  78%|███████▊  | 5251/6774 [17:55<05:03,  5.02it/s]

Processing tickers:  78%|███████▊  | 5252/6774 [17:55<05:03,  5.02it/s]

Processing tickers:  78%|███████▊  | 5253/6774 [17:55<05:03,  5.02it/s]

Processing tickers:  78%|███████▊  | 5254/6774 [17:55<05:00,  5.05it/s]

Processing tickers:  78%|███████▊  | 5255/6774 [17:55<05:00,  5.06it/s]

Processing tickers:  78%|███████▊  | 5256/6774 [17:56<05:01,  5.04it/s]

Processing tickers:  78%|███████▊  | 5257/6774 [17:56<05:01,  5.03it/s]

Processing tickers:  78%|███████▊  | 5258/6774 [17:56<05:03,  4.99it/s]

Processing tickers:  78%|███████▊  | 5259/6774 [17:56<05:03,  5.00it/s]

Processing tickers:  78%|███████▊  | 5260/6774 [17:56<05:04,  4.97it/s]

Processing tickers:  78%|███████▊  | 5261/6774 [17:57<05:09,  4.88it/s]

Processing tickers:  78%|███████▊  | 5262/6774 [17:57<05:07,  4.92it/s]

Processing tickers:  78%|███████▊  | 5263/6774 [17:57<05:05,  4.94it/s]

Processing tickers:  78%|███████▊  | 5264/6774 [17:57<05:05,  4.94it/s]

Processing tickers:  78%|███████▊  | 5265/6774 [17:58<05:04,  4.96it/s]

Processing tickers:  78%|███████▊  | 5266/6774 [17:58<05:03,  4.96it/s]

Processing tickers:  78%|███████▊  | 5267/6774 [17:58<05:04,  4.94it/s]

Processing tickers:  78%|███████▊  | 5268/6774 [17:58<05:03,  4.96it/s]

Processing tickers:  78%|███████▊  | 5269/6774 [17:58<05:04,  4.94it/s]

Processing tickers:  78%|███████▊  | 5270/6774 [17:59<05:02,  4.97it/s]

Processing tickers:  78%|███████▊  | 5271/6774 [17:59<05:09,  4.85it/s]

Processing tickers:  78%|███████▊  | 5272/6774 [17:59<05:04,  4.93it/s]

Processing tickers:  78%|███████▊  | 5273/6774 [17:59<05:08,  4.86it/s]

Processing tickers:  78%|███████▊  | 5274/6774 [17:59<05:09,  4.85it/s]

Processing tickers:  78%|███████▊  | 5275/6774 [18:00<05:06,  4.89it/s]

Processing tickers:  78%|███████▊  | 5276/6774 [18:00<05:03,  4.94it/s]

Processing tickers:  78%|███████▊  | 5277/6774 [18:00<05:05,  4.90it/s]

Processing tickers:  78%|███████▊  | 5278/6774 [18:00<05:03,  4.92it/s]

Processing tickers:  78%|███████▊  | 5279/6774 [18:00<05:04,  4.91it/s]

Processing tickers:  78%|███████▊  | 5280/6774 [18:01<05:01,  4.95it/s]

Processing tickers:  78%|███████▊  | 5281/6774 [18:01<05:00,  4.97it/s]

Processing tickers:  78%|███████▊  | 5282/6774 [18:01<05:00,  4.96it/s]

Processing tickers:  78%|███████▊  | 5283/6774 [18:01<04:58,  4.99it/s]

Processing tickers:  78%|███████▊  | 5284/6774 [18:01<04:58,  4.99it/s]

Processing tickers:  78%|███████▊  | 5285/6774 [18:02<05:05,  4.88it/s]

Processing tickers:  78%|███████▊  | 5286/6774 [18:02<05:05,  4.87it/s]

Processing tickers:  78%|███████▊  | 5287/6774 [18:02<05:05,  4.86it/s]

Processing tickers:  78%|███████▊  | 5288/6774 [18:02<05:05,  4.86it/s]

Processing tickers:  78%|███████▊  | 5289/6774 [18:02<05:03,  4.90it/s]

Processing tickers:  78%|███████▊  | 5290/6774 [18:03<05:00,  4.94it/s]

Processing tickers:  78%|███████▊  | 5291/6774 [18:03<05:00,  4.94it/s]

Processing tickers:  78%|███████▊  | 5292/6774 [18:03<05:04,  4.87it/s]

Processing tickers:  78%|███████▊  | 5293/6774 [18:03<05:02,  4.89it/s]

Processing tickers:  78%|███████▊  | 5294/6774 [18:03<05:04,  4.86it/s]

Processing tickers:  78%|███████▊  | 5295/6774 [18:04<05:10,  4.76it/s]

Processing tickers:  78%|███████▊  | 5296/6774 [18:04<05:05,  4.83it/s]

Processing tickers:  78%|███████▊  | 5297/6774 [18:04<05:02,  4.89it/s]

Processing tickers:  78%|███████▊  | 5298/6774 [18:04<04:59,  4.93it/s]

Processing tickers:  78%|███████▊  | 5299/6774 [18:04<04:57,  4.96it/s]

Processing tickers:  78%|███████▊  | 5300/6774 [18:05<04:54,  5.00it/s]

Processing tickers:  78%|███████▊  | 5301/6774 [18:05<04:53,  5.02it/s]

Processing tickers:  78%|███████▊  | 5302/6774 [18:05<05:01,  4.88it/s]

Processing tickers:  78%|███████▊  | 5303/6774 [18:05<04:58,  4.93it/s]

Processing tickers:  78%|███████▊  | 5304/6774 [18:05<04:56,  4.97it/s]

Processing tickers:  78%|███████▊  | 5305/6774 [18:06<04:55,  4.97it/s]

Processing tickers:  78%|███████▊  | 5306/6774 [18:06<04:58,  4.93it/s]

Processing tickers:  78%|███████▊  | 5307/6774 [18:06<04:55,  4.96it/s]

Processing tickers:  78%|███████▊  | 5308/6774 [18:06<04:55,  4.95it/s]

Processing tickers:  78%|███████▊  | 5309/6774 [18:06<04:54,  4.98it/s]

Processing tickers:  78%|███████▊  | 5310/6774 [18:07<04:52,  5.00it/s]

Processing tickers:  78%|███████▊  | 5311/6774 [18:07<04:51,  5.02it/s]

Processing tickers:  78%|███████▊  | 5312/6774 [18:07<04:55,  4.95it/s]

Processing tickers:  78%|███████▊  | 5313/6774 [18:07<04:54,  4.97it/s]

Processing tickers:  78%|███████▊  | 5314/6774 [18:07<04:53,  4.98it/s]

Processing tickers:  78%|███████▊  | 5315/6774 [18:08<04:56,  4.92it/s]

Processing tickers:  78%|███████▊  | 5316/6774 [18:08<04:54,  4.94it/s]

Processing tickers:  78%|███████▊  | 5317/6774 [18:08<04:58,  4.89it/s]

Processing tickers:  79%|███████▊  | 5318/6774 [18:08<05:03,  4.80it/s]

Processing tickers:  79%|███████▊  | 5319/6774 [18:08<04:58,  4.87it/s]

Processing tickers:  79%|███████▊  | 5320/6774 [18:09<04:56,  4.90it/s]

Processing tickers:  79%|███████▊  | 5321/6774 [18:09<04:54,  4.93it/s]

Processing tickers:  79%|███████▊  | 5322/6774 [18:09<04:52,  4.96it/s]

Processing tickers:  79%|███████▊  | 5323/6774 [18:09<04:52,  4.97it/s]

Processing tickers:  79%|███████▊  | 5324/6774 [18:09<04:52,  4.96it/s]

Processing tickers:  79%|███████▊  | 5325/6774 [18:10<04:51,  4.97it/s]

Processing tickers:  79%|███████▊  | 5326/6774 [18:10<04:52,  4.96it/s]

Processing tickers:  79%|███████▊  | 5327/6774 [18:10<04:51,  4.96it/s]

Processing tickers:  79%|███████▊  | 5328/6774 [18:10<04:51,  4.97it/s]

Processing tickers:  79%|███████▊  | 5329/6774 [18:10<04:50,  4.98it/s]

Processing tickers:  79%|███████▊  | 5330/6774 [18:11<04:51,  4.96it/s]

Processing tickers:  79%|███████▊  | 5331/6774 [18:11<04:49,  4.98it/s]

Processing tickers:  79%|███████▊  | 5332/6774 [18:11<04:49,  4.98it/s]

Processing tickers:  79%|███████▊  | 5333/6774 [18:11<04:49,  4.97it/s]

Processing tickers:  79%|███████▊  | 5334/6774 [18:11<04:51,  4.94it/s]

Processing tickers:  79%|███████▉  | 5335/6774 [18:12<04:51,  4.93it/s]

Processing tickers:  79%|███████▉  | 5336/6774 [18:12<04:48,  4.98it/s]

Processing tickers:  79%|███████▉  | 5337/6774 [18:12<04:48,  4.98it/s]

Processing tickers:  79%|███████▉  | 5338/6774 [18:12<04:52,  4.91it/s]

Processing tickers:  79%|███████▉  | 5339/6774 [18:13<04:51,  4.93it/s]

Processing tickers:  79%|███████▉  | 5340/6774 [18:13<04:50,  4.94it/s]

Processing tickers:  79%|███████▉  | 5341/6774 [18:13<04:49,  4.95it/s]

Processing tickers:  79%|███████▉  | 5342/6774 [18:13<04:50,  4.93it/s]

Processing tickers:  79%|███████▉  | 5343/6774 [18:13<04:52,  4.89it/s]

Processing tickers:  79%|███████▉  | 5344/6774 [18:14<04:59,  4.77it/s]

Processing tickers:  79%|███████▉  | 5345/6774 [18:14<04:55,  4.84it/s]

Processing tickers:  79%|███████▉  | 5346/6774 [18:14<04:52,  4.89it/s]

Processing tickers:  79%|███████▉  | 5347/6774 [18:14<05:00,  4.75it/s]

Processing tickers:  79%|███████▉  | 5348/6774 [18:14<04:55,  4.83it/s]

Processing tickers:  79%|███████▉  | 5349/6774 [18:15<04:52,  4.87it/s]

Processing tickers:  79%|███████▉  | 5350/6774 [18:15<04:51,  4.88it/s]

Processing tickers:  79%|███████▉  | 5351/6774 [18:15<04:53,  4.85it/s]

Processing tickers:  79%|███████▉  | 5352/6774 [18:15<04:51,  4.87it/s]

Processing tickers:  79%|███████▉  | 5353/6774 [18:15<04:49,  4.91it/s]

Processing tickers:  79%|███████▉  | 5354/6774 [18:16<04:47,  4.93it/s]

Processing tickers:  79%|███████▉  | 5355/6774 [18:16<04:48,  4.92it/s]

Processing tickers:  79%|███████▉  | 5356/6774 [18:16<04:50,  4.88it/s]

Processing tickers:  79%|███████▉  | 5357/6774 [18:16<04:53,  4.83it/s]

Processing tickers:  79%|███████▉  | 5358/6774 [18:16<04:50,  4.87it/s]

Processing tickers:  79%|███████▉  | 5359/6774 [18:17<04:48,  4.90it/s]

Processing tickers:  79%|███████▉  | 5360/6774 [18:17<04:47,  4.92it/s]

Processing tickers:  79%|███████▉  | 5361/6774 [18:17<04:48,  4.89it/s]

Processing tickers:  79%|███████▉  | 5362/6774 [18:17<04:47,  4.91it/s]

Processing tickers:  79%|███████▉  | 5363/6774 [18:17<04:45,  4.94it/s]

Processing tickers:  79%|███████▉  | 5364/6774 [18:18<04:44,  4.95it/s]

Processing tickers:  79%|███████▉  | 5365/6774 [18:18<04:41,  5.00it/s]

Processing tickers:  79%|███████▉  | 5366/6774 [18:18<04:42,  4.99it/s]

Processing tickers:  79%|███████▉  | 5367/6774 [18:18<04:43,  4.96it/s]

Processing tickers:  79%|███████▉  | 5368/6774 [18:18<04:43,  4.95it/s]

Processing tickers:  79%|███████▉  | 5369/6774 [18:19<04:43,  4.96it/s]

Processing tickers:  79%|███████▉  | 5370/6774 [18:19<04:42,  4.98it/s]

Processing tickers:  79%|███████▉  | 5371/6774 [18:19<04:42,  4.97it/s]

Processing tickers:  79%|███████▉  | 5372/6774 [18:19<04:41,  4.98it/s]

Processing tickers:  79%|███████▉  | 5373/6774 [18:19<04:42,  4.97it/s]

Processing tickers:  79%|███████▉  | 5374/6774 [18:20<04:40,  4.99it/s]

Processing tickers:  79%|███████▉  | 5375/6774 [18:20<04:41,  4.96it/s]

Processing tickers:  79%|███████▉  | 5376/6774 [18:20<04:40,  4.98it/s]

Processing tickers:  79%|███████▉  | 5377/6774 [18:20<04:42,  4.94it/s]

Processing tickers:  79%|███████▉  | 5378/6774 [18:20<04:39,  4.99it/s]

Processing tickers:  79%|███████▉  | 5379/6774 [18:21<04:38,  5.00it/s]

Processing tickers:  79%|███████▉  | 5380/6774 [18:21<04:43,  4.91it/s]

Processing tickers:  79%|███████▉  | 5381/6774 [18:21<04:53,  4.75it/s]

Processing tickers:  79%|███████▉  | 5382/6774 [18:21<04:47,  4.84it/s]

Processing tickers:  79%|███████▉  | 5383/6774 [18:21<04:45,  4.88it/s]

Processing tickers:  79%|███████▉  | 5384/6774 [18:22<04:42,  4.93it/s]

Processing tickers:  79%|███████▉  | 5385/6774 [18:22<04:44,  4.89it/s]

Processing tickers:  80%|███████▉  | 5386/6774 [18:22<04:46,  4.84it/s]

Processing tickers:  80%|███████▉  | 5387/6774 [18:22<04:44,  4.87it/s]

Processing tickers:  80%|███████▉  | 5388/6774 [18:23<04:52,  4.74it/s]

Processing tickers:  80%|███████▉  | 5389/6774 [18:23<04:49,  4.79it/s]

Processing tickers:  80%|███████▉  | 5390/6774 [18:23<04:45,  4.85it/s]

Processing tickers:  80%|███████▉  | 5391/6774 [18:23<04:41,  4.91it/s]

Processing tickers:  80%|███████▉  | 5392/6774 [18:23<04:45,  4.84it/s]

Processing tickers:  80%|███████▉  | 5393/6774 [18:24<04:41,  4.91it/s]

Processing tickers:  80%|███████▉  | 5394/6774 [18:24<04:45,  4.83it/s]

Processing tickers:  80%|███████▉  | 5395/6774 [18:24<04:40,  4.91it/s]

Processing tickers:  80%|███████▉  | 5396/6774 [18:24<04:37,  4.96it/s]

Processing tickers:  80%|███████▉  | 5397/6774 [18:24<04:38,  4.94it/s]

Processing tickers:  80%|███████▉  | 5398/6774 [18:25<04:35,  5.00it/s]

Processing tickers:  80%|███████▉  | 5399/6774 [18:25<04:34,  5.01it/s]

Processing tickers:  80%|███████▉  | 5400/6774 [18:25<04:33,  5.03it/s]

Processing tickers:  80%|███████▉  | 5401/6774 [18:25<04:31,  5.05it/s]

Processing tickers:  80%|███████▉  | 5402/6774 [18:25<04:32,  5.04it/s]

Processing tickers:  80%|███████▉  | 5403/6774 [18:26<04:39,  4.91it/s]

Processing tickers:  80%|███████▉  | 5404/6774 [18:26<04:41,  4.86it/s]

Processing tickers:  80%|███████▉  | 5405/6774 [18:26<04:51,  4.70it/s]

Processing tickers:  80%|███████▉  | 5406/6774 [18:26<04:44,  4.81it/s]

Processing tickers:  80%|███████▉  | 5407/6774 [18:26<04:43,  4.82it/s]

Processing tickers:  80%|███████▉  | 5408/6774 [18:27<04:40,  4.86it/s]

Processing tickers:  80%|███████▉  | 5409/6774 [18:27<04:42,  4.84it/s]

Processing tickers:  80%|███████▉  | 5410/6774 [18:27<04:40,  4.86it/s]

Processing tickers:  80%|███████▉  | 5411/6774 [18:27<04:39,  4.88it/s]

Processing tickers:  80%|███████▉  | 5412/6774 [18:27<04:36,  4.93it/s]

Processing tickers:  80%|███████▉  | 5413/6774 [18:28<04:48,  4.72it/s]

Processing tickers:  80%|███████▉  | 5414/6774 [18:28<04:50,  4.68it/s]

Processing tickers:  80%|███████▉  | 5415/6774 [18:28<04:45,  4.75it/s]

Processing tickers:  80%|███████▉  | 5416/6774 [18:28<04:43,  4.80it/s]

Processing tickers:  80%|███████▉  | 5417/6774 [18:28<04:45,  4.76it/s]

Processing tickers:  80%|███████▉  | 5418/6774 [18:29<04:43,  4.79it/s]

Processing tickers:  80%|███████▉  | 5419/6774 [18:29<04:38,  4.87it/s]

Processing tickers:  80%|████████  | 5420/6774 [18:29<04:41,  4.82it/s]

Processing tickers:  80%|████████  | 5421/6774 [18:29<04:38,  4.86it/s]

Processing tickers:  80%|████████  | 5422/6774 [18:30<04:41,  4.80it/s]

Processing tickers:  80%|████████  | 5423/6774 [18:30<04:38,  4.84it/s]

Processing tickers:  80%|████████  | 5424/6774 [18:30<04:35,  4.90it/s]

Processing tickers:  80%|████████  | 5425/6774 [18:30<04:39,  4.83it/s]

Processing tickers:  80%|████████  | 5426/6774 [18:30<04:35,  4.90it/s]

Processing tickers:  80%|████████  | 5427/6774 [18:31<04:37,  4.86it/s]

Processing tickers:  80%|████████  | 5428/6774 [18:31<04:34,  4.91it/s]

Processing tickers:  80%|████████  | 5429/6774 [18:31<04:30,  4.97it/s]

Processing tickers:  80%|████████  | 5430/6774 [18:31<04:29,  4.99it/s]

Processing tickers:  80%|████████  | 5431/6774 [18:31<04:34,  4.90it/s]

Processing tickers:  80%|████████  | 5432/6774 [18:32<04:39,  4.81it/s]

Processing tickers:  80%|████████  | 5433/6774 [18:32<04:36,  4.85it/s]

Processing tickers:  80%|████████  | 5434/6774 [18:32<04:48,  4.64it/s]

Processing tickers:  80%|████████  | 5435/6774 [18:32<04:41,  4.76it/s]

Processing tickers:  80%|████████  | 5436/6774 [18:32<04:42,  4.74it/s]

Processing tickers:  80%|████████  | 5437/6774 [18:33<04:39,  4.78it/s]

Processing tickers:  80%|████████  | 5438/6774 [18:33<04:44,  4.70it/s]

Processing tickers:  80%|████████  | 5439/6774 [18:33<04:45,  4.68it/s]

Processing tickers:  80%|████████  | 5440/6774 [18:33<04:40,  4.75it/s]

Processing tickers:  80%|████████  | 5441/6774 [18:33<04:40,  4.76it/s]

Processing tickers:  80%|████████  | 5442/6774 [18:34<04:43,  4.70it/s]

Processing tickers:  80%|████████  | 5443/6774 [18:34<04:37,  4.80it/s]

Processing tickers:  80%|████████  | 5444/6774 [18:34<04:33,  4.87it/s]

Processing tickers:  80%|████████  | 5445/6774 [18:34<04:31,  4.90it/s]

Processing tickers:  80%|████████  | 5446/6774 [18:34<04:27,  4.96it/s]

Processing tickers:  80%|████████  | 5447/6774 [18:35<04:26,  4.98it/s]

Processing tickers:  80%|████████  | 5448/6774 [18:35<04:29,  4.93it/s]

Processing tickers:  80%|████████  | 5449/6774 [18:35<04:41,  4.70it/s]

Processing tickers:  80%|████████  | 5450/6774 [18:35<04:41,  4.70it/s]

Processing tickers:  80%|████████  | 5451/6774 [18:36<04:35,  4.79it/s]

Processing tickers:  80%|████████  | 5452/6774 [18:36<04:38,  4.74it/s]

Processing tickers:  80%|████████  | 5453/6774 [18:36<04:34,  4.81it/s]

Processing tickers:  81%|████████  | 5454/6774 [18:36<04:38,  4.74it/s]

Processing tickers:  81%|████████  | 5455/6774 [18:36<04:42,  4.67it/s]

Processing tickers:  81%|████████  | 5456/6774 [18:37<04:43,  4.66it/s]

Processing tickers:  81%|████████  | 5457/6774 [18:37<04:35,  4.77it/s]

Processing tickers:  81%|████████  | 5458/6774 [18:37<04:34,  4.79it/s]

Processing tickers:  81%|████████  | 5459/6774 [18:37<04:31,  4.85it/s]

Processing tickers:  81%|████████  | 5460/6774 [18:37<04:31,  4.84it/s]

Processing tickers:  81%|████████  | 5461/6774 [18:38<04:29,  4.87it/s]

Processing tickers:  81%|████████  | 5462/6774 [18:38<04:38,  4.71it/s]

Processing tickers:  81%|████████  | 5463/6774 [18:38<04:34,  4.78it/s]

Processing tickers:  81%|████████  | 5464/6774 [18:38<04:31,  4.82it/s]

Processing tickers:  81%|████████  | 5465/6774 [18:38<04:28,  4.88it/s]

Processing tickers:  81%|████████  | 5466/6774 [18:39<04:32,  4.80it/s]

Processing tickers:  81%|████████  | 5467/6774 [18:39<04:29,  4.85it/s]

Processing tickers:  81%|████████  | 5468/6774 [18:39<04:26,  4.90it/s]

Processing tickers:  81%|████████  | 5469/6774 [18:39<04:25,  4.91it/s]

Processing tickers:  81%|████████  | 5470/6774 [18:39<04:28,  4.85it/s]

Processing tickers:  81%|████████  | 5471/6774 [18:40<04:26,  4.90it/s]

Processing tickers:  81%|████████  | 5472/6774 [18:40<04:31,  4.79it/s]

Processing tickers:  81%|████████  | 5473/6774 [18:40<04:36,  4.70it/s]

Processing tickers:  81%|████████  | 5474/6774 [18:40<04:31,  4.79it/s]

Processing tickers:  81%|████████  | 5475/6774 [18:41<04:27,  4.86it/s]

Processing tickers:  81%|████████  | 5476/6774 [18:41<04:24,  4.91it/s]

Processing tickers:  81%|████████  | 5477/6774 [18:41<04:21,  4.95it/s]

Processing tickers:  81%|████████  | 5478/6774 [18:41<04:22,  4.94it/s]

Processing tickers:  81%|████████  | 5479/6774 [18:41<04:28,  4.83it/s]

Processing tickers:  81%|████████  | 5480/6774 [18:42<04:31,  4.76it/s]

Processing tickers:  81%|████████  | 5481/6774 [18:42<04:35,  4.70it/s]

Processing tickers:  81%|████████  | 5482/6774 [18:42<04:29,  4.80it/s]

Processing tickers:  81%|████████  | 5483/6774 [18:42<04:27,  4.82it/s]

Processing tickers:  81%|████████  | 5484/6774 [18:42<04:24,  4.88it/s]

Processing tickers:  81%|████████  | 5485/6774 [18:43<04:24,  4.88it/s]

Processing tickers:  81%|████████  | 5486/6774 [18:43<04:21,  4.92it/s]

Processing tickers:  81%|████████  | 5487/6774 [18:43<04:24,  4.87it/s]

Processing tickers:  81%|████████  | 5488/6774 [18:43<04:21,  4.92it/s]

Processing tickers:  81%|████████  | 5489/6774 [18:43<04:21,  4.92it/s]

Processing tickers:  81%|████████  | 5490/6774 [18:44<04:18,  4.96it/s]

Processing tickers:  81%|████████  | 5491/6774 [18:44<04:17,  4.98it/s]

Processing tickers:  81%|████████  | 5492/6774 [18:44<04:21,  4.90it/s]

Processing tickers:  81%|████████  | 5493/6774 [18:44<04:22,  4.87it/s]

Processing tickers:  81%|████████  | 5494/6774 [18:44<04:22,  4.89it/s]

Processing tickers:  81%|████████  | 5495/6774 [18:45<04:27,  4.79it/s]

Processing tickers:  81%|████████  | 5496/6774 [18:45<04:29,  4.75it/s]

Processing tickers:  81%|████████  | 5497/6774 [18:45<04:24,  4.82it/s]

Processing tickers:  81%|████████  | 5498/6774 [18:45<04:20,  4.90it/s]

Processing tickers:  81%|████████  | 5499/6774 [18:45<04:16,  4.96it/s]

Processing tickers:  81%|████████  | 5500/6774 [18:46<04:27,  4.77it/s]

Processing tickers:  81%|████████  | 5501/6774 [18:46<04:26,  4.78it/s]

Processing tickers:  81%|████████  | 5502/6774 [18:46<04:28,  4.73it/s]

Processing tickers:  81%|████████  | 5503/6774 [18:46<04:23,  4.81it/s]

Processing tickers:  81%|████████▏ | 5504/6774 [18:46<04:24,  4.79it/s]

Processing tickers:  81%|████████▏ | 5505/6774 [18:47<04:25,  4.79it/s]

Processing tickers:  81%|████████▏ | 5506/6774 [18:47<04:56,  4.28it/s]

Processing tickers:  81%|████████▏ | 5507/6774 [18:47<04:46,  4.43it/s]

Processing tickers:  81%|████████▏ | 5508/6774 [18:47<04:36,  4.58it/s]

Processing tickers:  81%|████████▏ | 5509/6774 [18:48<04:30,  4.67it/s]

Processing tickers:  81%|████████▏ | 5510/6774 [18:48<04:27,  4.72it/s]

Processing tickers:  81%|████████▏ | 5511/6774 [18:48<04:21,  4.83it/s]

Processing tickers:  81%|████████▏ | 5512/6774 [18:48<04:24,  4.77it/s]

Processing tickers:  81%|████████▏ | 5513/6774 [18:48<04:22,  4.81it/s]

Processing tickers:  81%|████████▏ | 5514/6774 [18:49<04:21,  4.83it/s]

Processing tickers:  81%|████████▏ | 5515/6774 [18:49<04:17,  4.88it/s]

Processing tickers:  81%|████████▏ | 5516/6774 [18:49<04:21,  4.81it/s]

Processing tickers:  81%|████████▏ | 5517/6774 [18:49<04:23,  4.76it/s]

Processing tickers:  81%|████████▏ | 5518/6774 [18:49<04:25,  4.72it/s]

Processing tickers:  81%|████████▏ | 5519/6774 [18:50<04:33,  4.59it/s]

Processing tickers:  81%|████████▏ | 5520/6774 [18:50<04:31,  4.62it/s]

Processing tickers:  82%|████████▏ | 5521/6774 [18:50<04:27,  4.69it/s]

Processing tickers:  82%|████████▏ | 5522/6774 [18:50<04:48,  4.34it/s]

Processing tickers:  82%|████████▏ | 5523/6774 [18:51<04:38,  4.49it/s]

Processing tickers:  82%|████████▏ | 5524/6774 [18:51<04:30,  4.62it/s]

Processing tickers:  82%|████████▏ | 5525/6774 [18:51<04:25,  4.71it/s]

Processing tickers:  82%|████████▏ | 5526/6774 [18:51<04:23,  4.75it/s]

Processing tickers:  82%|████████▏ | 5527/6774 [18:51<04:24,  4.72it/s]

Processing tickers:  82%|████████▏ | 5528/6774 [18:52<04:26,  4.68it/s]

Processing tickers:  82%|████████▏ | 5529/6774 [18:52<04:22,  4.74it/s]

Processing tickers:  82%|████████▏ | 5530/6774 [18:52<04:17,  4.83it/s]

Processing tickers:  82%|████████▏ | 5531/6774 [18:52<04:15,  4.87it/s]

Processing tickers:  82%|████████▏ | 5532/6774 [18:52<04:21,  4.75it/s]

Processing tickers:  82%|████████▏ | 5533/6774 [18:53<04:18,  4.80it/s]

Processing tickers:  82%|████████▏ | 5534/6774 [18:53<04:15,  4.85it/s]

Processing tickers:  82%|████████▏ | 5535/6774 [18:53<04:21,  4.74it/s]

Processing tickers:  82%|████████▏ | 5536/6774 [18:53<04:19,  4.76it/s]

Processing tickers:  82%|████████▏ | 5537/6774 [18:54<04:15,  4.85it/s]

Processing tickers:  82%|████████▏ | 5538/6774 [18:54<04:11,  4.92it/s]

Processing tickers:  82%|████████▏ | 5539/6774 [18:54<04:09,  4.96it/s]

Processing tickers:  82%|████████▏ | 5540/6774 [18:54<04:16,  4.82it/s]

Processing tickers:  82%|████████▏ | 5541/6774 [18:54<04:16,  4.81it/s]

Processing tickers:  82%|████████▏ | 5542/6774 [18:55<04:12,  4.89it/s]

Processing tickers:  82%|████████▏ | 5543/6774 [18:55<04:12,  4.88it/s]

Processing tickers:  82%|████████▏ | 5544/6774 [18:55<04:16,  4.79it/s]

Processing tickers:  82%|████████▏ | 5545/6774 [18:55<04:21,  4.70it/s]

Processing tickers:  82%|████████▏ | 5546/6774 [18:55<04:16,  4.79it/s]

Processing tickers:  82%|████████▏ | 5547/6774 [18:56<04:16,  4.78it/s]

Processing tickers:  82%|████████▏ | 5548/6774 [18:56<04:12,  4.85it/s]

Processing tickers:  82%|████████▏ | 5549/6774 [18:56<04:14,  4.81it/s]

Processing tickers:  82%|████████▏ | 5550/6774 [18:56<04:13,  4.83it/s]

Processing tickers:  82%|████████▏ | 5551/6774 [18:56<04:16,  4.77it/s]

Processing tickers:  82%|████████▏ | 5552/6774 [18:57<04:13,  4.83it/s]

Processing tickers:  82%|████████▏ | 5553/6774 [18:57<04:10,  4.88it/s]

Processing tickers:  82%|████████▏ | 5554/6774 [18:57<04:09,  4.88it/s]

Processing tickers:  82%|████████▏ | 5555/6774 [18:57<04:06,  4.94it/s]

Processing tickers:  82%|████████▏ | 5556/6774 [18:57<04:05,  4.97it/s]

Processing tickers:  82%|████████▏ | 5557/6774 [18:58<04:05,  4.96it/s]

Processing tickers:  82%|████████▏ | 5558/6774 [18:58<04:04,  4.96it/s]

Processing tickers:  82%|████████▏ | 5559/6774 [18:58<04:04,  4.98it/s]

Processing tickers:  82%|████████▏ | 5560/6774 [18:58<04:03,  4.99it/s]

Processing tickers:  82%|████████▏ | 5561/6774 [18:58<03:59,  5.06it/s]

Processing tickers:  82%|████████▏ | 5562/6774 [18:59<04:26,  4.55it/s]

Processing tickers:  82%|████████▏ | 5563/6774 [18:59<04:21,  4.62it/s]

Processing tickers:  82%|████████▏ | 5564/6774 [18:59<04:16,  4.72it/s]

Processing tickers:  82%|████████▏ | 5565/6774 [18:59<04:14,  4.75it/s]

Processing tickers:  82%|████████▏ | 5566/6774 [18:59<04:09,  4.84it/s]

Processing tickers:  82%|████████▏ | 5567/6774 [19:00<04:07,  4.88it/s]

Processing tickers:  82%|████████▏ | 5568/6774 [19:00<04:06,  4.89it/s]

Processing tickers:  82%|████████▏ | 5569/6774 [19:00<04:04,  4.93it/s]

Processing tickers:  82%|████████▏ | 5570/6774 [19:00<04:06,  4.88it/s]

Processing tickers:  82%|████████▏ | 5571/6774 [19:01<04:04,  4.92it/s]

Processing tickers:  82%|████████▏ | 5572/6774 [19:01<04:03,  4.93it/s]

Processing tickers:  82%|████████▏ | 5573/6774 [19:01<04:04,  4.91it/s]

Processing tickers:  82%|████████▏ | 5574/6774 [19:01<04:10,  4.80it/s]

Processing tickers:  82%|████████▏ | 5575/6774 [19:01<04:08,  4.82it/s]

Processing tickers:  82%|████████▏ | 5576/6774 [19:02<04:17,  4.66it/s]

Processing tickers:  82%|████████▏ | 5577/6774 [19:02<04:12,  4.74it/s]

Processing tickers:  82%|████████▏ | 5578/6774 [19:02<04:15,  4.69it/s]

Processing tickers:  82%|████████▏ | 5579/6774 [19:02<04:18,  4.63it/s]

Processing tickers:  82%|████████▏ | 5580/6774 [19:02<04:11,  4.75it/s]

Processing tickers:  82%|████████▏ | 5581/6774 [19:03<04:07,  4.82it/s]

Processing tickers:  82%|████████▏ | 5582/6774 [19:03<04:07,  4.82it/s]

Processing tickers:  82%|████████▏ | 5583/6774 [19:03<04:08,  4.80it/s]

Processing tickers:  82%|████████▏ | 5584/6774 [19:03<04:06,  4.83it/s]

Processing tickers:  82%|████████▏ | 5585/6774 [19:03<04:02,  4.89it/s]

Processing tickers:  82%|████████▏ | 5586/6774 [19:04<04:06,  4.82it/s]

Processing tickers:  82%|████████▏ | 5587/6774 [19:04<04:09,  4.75it/s]

Processing tickers:  82%|████████▏ | 5588/6774 [19:04<04:07,  4.79it/s]

Processing tickers:  83%|████████▎ | 5589/6774 [19:04<04:07,  4.80it/s]

Processing tickers:  83%|████████▎ | 5590/6774 [19:04<04:03,  4.86it/s]

Processing tickers:  83%|████████▎ | 5591/6774 [19:05<04:01,  4.90it/s]

Processing tickers:  83%|████████▎ | 5592/6774 [19:05<03:59,  4.93it/s]

Processing tickers:  83%|████████▎ | 5593/6774 [19:05<03:58,  4.96it/s]

Processing tickers:  83%|████████▎ | 5594/6774 [19:05<03:57,  4.97it/s]

Processing tickers:  83%|████████▎ | 5595/6774 [19:05<03:57,  4.96it/s]

Processing tickers:  83%|████████▎ | 5596/6774 [19:06<03:57,  4.97it/s]

Processing tickers:  83%|████████▎ | 5597/6774 [19:06<03:58,  4.93it/s]

Processing tickers:  83%|████████▎ | 5598/6774 [19:06<04:02,  4.85it/s]

Processing tickers:  83%|████████▎ | 5599/6774 [19:06<04:01,  4.87it/s]

Processing tickers:  83%|████████▎ | 5600/6774 [19:07<03:59,  4.90it/s]

Processing tickers:  83%|████████▎ | 5601/6774 [19:07<04:03,  4.81it/s]

Processing tickers:  83%|████████▎ | 5602/6774 [19:07<04:01,  4.84it/s]

Processing tickers:  83%|████████▎ | 5603/6774 [19:07<04:00,  4.87it/s]

Processing tickers:  83%|████████▎ | 5604/6774 [19:07<03:57,  4.92it/s]

Processing tickers:  83%|████████▎ | 5605/6774 [19:08<03:59,  4.87it/s]

Processing tickers:  83%|████████▎ | 5606/6774 [19:08<03:56,  4.93it/s]

Processing tickers:  83%|████████▎ | 5607/6774 [19:08<03:55,  4.96it/s]

Processing tickers:  83%|████████▎ | 5608/6774 [19:08<04:03,  4.80it/s]

Processing tickers:  83%|████████▎ | 5609/6774 [19:08<04:02,  4.81it/s]

Processing tickers:  83%|████████▎ | 5610/6774 [19:09<03:59,  4.86it/s]

Processing tickers:  83%|████████▎ | 5611/6774 [19:09<03:58,  4.87it/s]

Processing tickers:  83%|████████▎ | 5612/6774 [19:09<04:01,  4.82it/s]

Processing tickers:  83%|████████▎ | 5613/6774 [19:09<04:02,  4.80it/s]

Processing tickers:  83%|████████▎ | 5614/6774 [19:09<04:06,  4.71it/s]

Processing tickers:  83%|████████▎ | 5615/6774 [19:10<04:01,  4.79it/s]

Processing tickers:  83%|████████▎ | 5616/6774 [19:10<04:04,  4.73it/s]

Processing tickers:  83%|████████▎ | 5617/6774 [19:10<04:03,  4.76it/s]

Processing tickers:  83%|████████▎ | 5618/6774 [19:10<03:58,  4.84it/s]

Processing tickers:  83%|████████▎ | 5619/6774 [19:10<03:58,  4.85it/s]

Processing tickers:  83%|████████▎ | 5620/6774 [19:11<03:56,  4.89it/s]

Processing tickers:  83%|████████▎ | 5621/6774 [19:11<03:54,  4.91it/s]

Processing tickers:  83%|████████▎ | 5622/6774 [19:11<03:57,  4.84it/s]

Processing tickers:  83%|████████▎ | 5623/6774 [19:11<03:58,  4.82it/s]

Processing tickers:  83%|████████▎ | 5624/6774 [19:11<03:56,  4.86it/s]

Processing tickers:  83%|████████▎ | 5625/6774 [19:12<03:55,  4.89it/s]

Processing tickers:  83%|████████▎ | 5626/6774 [19:12<03:54,  4.89it/s]

Processing tickers:  83%|████████▎ | 5627/6774 [19:12<03:54,  4.90it/s]

Processing tickers:  83%|████████▎ | 5628/6774 [19:12<03:56,  4.85it/s]

Processing tickers:  83%|████████▎ | 5629/6774 [19:13<03:59,  4.79it/s]

Processing tickers:  83%|████████▎ | 5630/6774 [19:13<03:56,  4.84it/s]

Processing tickers:  83%|████████▎ | 5631/6774 [19:13<03:53,  4.89it/s]

Processing tickers:  83%|████████▎ | 5632/6774 [19:13<03:53,  4.88it/s]

Processing tickers:  83%|████████▎ | 5633/6774 [19:13<04:10,  4.56it/s]

Processing tickers:  83%|████████▎ | 5634/6774 [19:14<04:01,  4.72it/s]

Processing tickers:  83%|████████▎ | 5635/6774 [19:14<03:57,  4.80it/s]

Processing tickers:  83%|████████▎ | 5636/6774 [19:14<03:57,  4.79it/s]

Processing tickers:  83%|████████▎ | 5637/6774 [19:14<03:54,  4.85it/s]

Processing tickers:  83%|████████▎ | 5638/6774 [19:14<03:53,  4.86it/s]

Processing tickers:  83%|████████▎ | 5639/6774 [19:15<03:50,  4.91it/s]

Processing tickers:  83%|████████▎ | 5640/6774 [19:15<03:55,  4.81it/s]

Processing tickers:  83%|████████▎ | 5641/6774 [19:15<03:57,  4.77it/s]

Processing tickers:  83%|████████▎ | 5642/6774 [19:15<03:54,  4.83it/s]

Processing tickers:  83%|████████▎ | 5643/6774 [19:15<03:51,  4.88it/s]

Processing tickers:  83%|████████▎ | 5644/6774 [19:16<03:49,  4.93it/s]

Processing tickers:  83%|████████▎ | 5645/6774 [19:16<03:47,  4.95it/s]

Processing tickers:  83%|████████▎ | 5646/6774 [19:16<03:51,  4.88it/s]

Processing tickers:  83%|████████▎ | 5647/6774 [19:16<03:48,  4.93it/s]

Processing tickers:  83%|████████▎ | 5648/6774 [19:16<03:50,  4.89it/s]

Processing tickers:  83%|████████▎ | 5649/6774 [19:17<03:50,  4.88it/s]

Processing tickers:  83%|████████▎ | 5650/6774 [19:17<03:47,  4.94it/s]

Processing tickers:  83%|████████▎ | 5651/6774 [19:17<03:51,  4.86it/s]

Processing tickers:  83%|████████▎ | 5652/6774 [19:17<03:50,  4.87it/s]

Processing tickers:  83%|████████▎ | 5653/6774 [19:17<03:48,  4.91it/s]

Processing tickers:  83%|████████▎ | 5654/6774 [19:18<03:46,  4.95it/s]

Processing tickers:  83%|████████▎ | 5655/6774 [19:18<03:50,  4.85it/s]

Processing tickers:  83%|████████▎ | 5656/6774 [19:18<03:48,  4.89it/s]

Processing tickers:  84%|████████▎ | 5657/6774 [19:18<03:46,  4.94it/s]

Processing tickers:  84%|████████▎ | 5658/6774 [19:18<03:52,  4.80it/s]

Processing tickers:  84%|████████▎ | 5659/6774 [19:19<03:49,  4.86it/s]

Processing tickers:  84%|████████▎ | 5660/6774 [19:19<03:45,  4.94it/s]

Processing tickers:  84%|████████▎ | 5661/6774 [19:19<03:51,  4.80it/s]

Processing tickers:  84%|████████▎ | 5662/6774 [19:19<03:54,  4.74it/s]

Processing tickers:  84%|████████▎ | 5663/6774 [19:20<03:51,  4.81it/s]

Processing tickers:  84%|████████▎ | 5664/6774 [19:20<03:47,  4.89it/s]

Processing tickers:  84%|████████▎ | 5665/6774 [19:20<03:45,  4.92it/s]

Processing tickers:  84%|████████▎ | 5666/6774 [19:20<03:43,  4.95it/s]

Processing tickers:  84%|████████▎ | 5667/6774 [19:20<03:48,  4.85it/s]

Processing tickers:  84%|████████▎ | 5668/6774 [19:21<03:50,  4.81it/s]

Processing tickers:  84%|████████▎ | 5669/6774 [19:21<03:46,  4.89it/s]

Processing tickers:  84%|████████▎ | 5670/6774 [19:21<03:44,  4.91it/s]

Processing tickers:  84%|████████▎ | 5671/6774 [19:21<03:43,  4.93it/s]

Processing tickers:  84%|████████▎ | 5672/6774 [19:21<03:42,  4.95it/s]

Processing tickers:  84%|████████▎ | 5673/6774 [19:22<03:41,  4.96it/s]

Processing tickers:  84%|████████▍ | 5674/6774 [19:22<03:39,  5.00it/s]

Processing tickers:  84%|████████▍ | 5675/6774 [19:22<03:39,  5.00it/s]

Processing tickers:  84%|████████▍ | 5676/6774 [19:22<03:40,  4.98it/s]

Processing tickers:  84%|████████▍ | 5677/6774 [19:22<03:39,  4.99it/s]

Processing tickers:  84%|████████▍ | 5678/6774 [19:23<03:39,  5.00it/s]

Processing tickers:  84%|████████▍ | 5679/6774 [19:23<03:37,  5.04it/s]

Processing tickers:  84%|████████▍ | 5680/6774 [19:23<03:38,  5.00it/s]

Processing tickers:  84%|████████▍ | 5681/6774 [19:23<03:37,  5.02it/s]

Processing tickers:  84%|████████▍ | 5682/6774 [19:23<03:39,  4.98it/s]

Processing tickers:  84%|████████▍ | 5683/6774 [19:24<03:39,  4.98it/s]

Processing tickers:  84%|████████▍ | 5684/6774 [19:24<03:37,  5.01it/s]

Processing tickers:  84%|████████▍ | 5685/6774 [19:24<03:40,  4.93it/s]

Processing tickers:  84%|████████▍ | 5686/6774 [19:24<03:39,  4.96it/s]

Processing tickers:  84%|████████▍ | 5687/6774 [19:24<03:38,  4.97it/s]

Processing tickers:  84%|████████▍ | 5688/6774 [19:25<03:38,  4.97it/s]

Processing tickers:  84%|████████▍ | 5689/6774 [19:25<03:39,  4.95it/s]

Processing tickers:  84%|████████▍ | 5690/6774 [19:25<03:38,  4.97it/s]

Processing tickers:  84%|████████▍ | 5691/6774 [19:25<03:40,  4.92it/s]

Processing tickers:  84%|████████▍ | 5692/6774 [19:25<03:40,  4.91it/s]

Processing tickers:  84%|████████▍ | 5693/6774 [19:26<03:39,  4.93it/s]

Processing tickers:  84%|████████▍ | 5694/6774 [19:26<03:39,  4.92it/s]

Processing tickers:  84%|████████▍ | 5695/6774 [19:26<03:40,  4.88it/s]

Processing tickers:  84%|████████▍ | 5696/6774 [19:26<03:39,  4.90it/s]

Processing tickers:  84%|████████▍ | 5697/6774 [19:26<03:42,  4.85it/s]

Processing tickers:  84%|████████▍ | 5698/6774 [19:27<03:41,  4.87it/s]

Processing tickers:  84%|████████▍ | 5699/6774 [19:27<03:40,  4.88it/s]

Processing tickers:  84%|████████▍ | 5700/6774 [19:27<03:43,  4.80it/s]

Processing tickers:  84%|████████▍ | 5701/6774 [19:27<03:39,  4.88it/s]

Processing tickers:  84%|████████▍ | 5702/6774 [19:27<03:38,  4.90it/s]

Processing tickers:  84%|████████▍ | 5703/6774 [19:28<03:37,  4.93it/s]

Processing tickers:  84%|████████▍ | 5704/6774 [19:28<03:35,  4.97it/s]

Processing tickers:  84%|████████▍ | 5705/6774 [19:28<03:37,  4.91it/s]

Processing tickers:  84%|████████▍ | 5706/6774 [19:28<03:39,  4.88it/s]

Processing tickers:  84%|████████▍ | 5707/6774 [19:28<03:43,  4.77it/s]

Processing tickers:  84%|████████▍ | 5708/6774 [19:29<03:42,  4.79it/s]

Processing tickers:  84%|████████▍ | 5709/6774 [19:29<03:39,  4.86it/s]

Processing tickers:  84%|████████▍ | 5710/6774 [19:29<03:40,  4.82it/s]

Processing tickers:  84%|████████▍ | 5711/6774 [19:29<03:39,  4.85it/s]

Processing tickers:  84%|████████▍ | 5712/6774 [19:29<03:38,  4.86it/s]

Processing tickers:  84%|████████▍ | 5713/6774 [19:30<03:39,  4.83it/s]

Processing tickers:  84%|████████▍ | 5714/6774 [19:30<03:36,  4.90it/s]

Processing tickers:  84%|████████▍ | 5715/6774 [19:30<03:40,  4.80it/s]

Processing tickers:  84%|████████▍ | 5716/6774 [19:30<03:37,  4.85it/s]

Processing tickers:  84%|████████▍ | 5717/6774 [19:30<03:35,  4.90it/s]

Processing tickers:  84%|████████▍ | 5718/6774 [19:31<03:34,  4.91it/s]

Processing tickers:  84%|████████▍ | 5719/6774 [19:31<03:34,  4.91it/s]

Processing tickers:  84%|████████▍ | 5720/6774 [19:31<03:34,  4.92it/s]

Processing tickers:  84%|████████▍ | 5721/6774 [19:31<03:33,  4.93it/s]

Processing tickers:  84%|████████▍ | 5722/6774 [19:32<03:32,  4.95it/s]

Processing tickers:  84%|████████▍ | 5723/6774 [19:32<03:32,  4.94it/s]

Processing tickers:  84%|████████▍ | 5724/6774 [19:32<03:36,  4.86it/s]

Processing tickers:  85%|████████▍ | 5725/6774 [19:32<03:34,  4.90it/s]

Processing tickers:  85%|████████▍ | 5726/6774 [19:32<03:34,  4.89it/s]

Processing tickers:  85%|████████▍ | 5727/6774 [19:33<03:41,  4.72it/s]

Processing tickers:  85%|████████▍ | 5728/6774 [19:33<03:37,  4.82it/s]

Processing tickers:  85%|████████▍ | 5729/6774 [19:33<03:33,  4.90it/s]

Processing tickers:  85%|████████▍ | 5730/6774 [19:33<03:33,  4.89it/s]

Processing tickers:  85%|████████▍ | 5731/6774 [19:33<03:32,  4.91it/s]

Processing tickers:  85%|████████▍ | 5732/6774 [19:34<03:31,  4.94it/s]

Processing tickers:  85%|████████▍ | 5733/6774 [19:34<03:29,  4.96it/s]

Processing tickers:  85%|████████▍ | 5734/6774 [19:34<03:28,  4.98it/s]

Processing tickers:  85%|████████▍ | 5735/6774 [19:34<03:27,  5.00it/s]

Processing tickers:  85%|████████▍ | 5736/6774 [19:34<03:34,  4.83it/s]

Processing tickers:  85%|████████▍ | 5737/6774 [19:35<03:32,  4.89it/s]

Processing tickers:  85%|████████▍ | 5738/6774 [19:35<03:30,  4.93it/s]

Processing tickers:  85%|████████▍ | 5739/6774 [19:35<03:31,  4.88it/s]

Processing tickers:  85%|████████▍ | 5740/6774 [19:35<03:29,  4.95it/s]

Processing tickers:  85%|████████▍ | 5741/6774 [19:35<03:27,  4.97it/s]

Processing tickers:  85%|████████▍ | 5742/6774 [19:36<03:27,  4.98it/s]

Processing tickers:  85%|████████▍ | 5743/6774 [19:36<03:26,  5.00it/s]

Processing tickers:  85%|████████▍ | 5744/6774 [19:36<03:29,  4.91it/s]

Processing tickers:  85%|████████▍ | 5745/6774 [19:36<03:27,  4.95it/s]

Processing tickers:  85%|████████▍ | 5746/6774 [19:36<03:28,  4.92it/s]

Processing tickers:  85%|████████▍ | 5747/6774 [19:37<03:27,  4.96it/s]

Processing tickers:  85%|████████▍ | 5748/6774 [19:37<03:26,  4.97it/s]

Processing tickers:  85%|████████▍ | 5749/6774 [19:37<03:26,  4.96it/s]

Processing tickers:  85%|████████▍ | 5750/6774 [19:37<03:24,  5.00it/s]

Processing tickers:  85%|████████▍ | 5751/6774 [19:37<03:24,  5.01it/s]

Processing tickers:  85%|████████▍ | 5752/6774 [19:38<03:24,  4.99it/s]

Processing tickers:  85%|████████▍ | 5753/6774 [19:38<03:23,  5.01it/s]

Processing tickers:  85%|████████▍ | 5754/6774 [19:38<03:26,  4.94it/s]

Processing tickers:  85%|████████▍ | 5755/6774 [19:38<03:27,  4.91it/s]

Processing tickers:  85%|████████▍ | 5756/6774 [19:38<03:27,  4.92it/s]

Processing tickers:  85%|████████▍ | 5757/6774 [19:39<03:27,  4.91it/s]

Processing tickers:  85%|████████▌ | 5758/6774 [19:39<03:27,  4.91it/s]

Processing tickers:  85%|████████▌ | 5759/6774 [19:39<03:24,  4.95it/s]

Processing tickers:  85%|████████▌ | 5760/6774 [19:39<03:23,  4.99it/s]

Processing tickers:  85%|████████▌ | 5761/6774 [19:39<03:22,  5.00it/s]

Processing tickers:  85%|████████▌ | 5762/6774 [19:40<03:24,  4.94it/s]

Processing tickers:  85%|████████▌ | 5763/6774 [19:40<03:24,  4.95it/s]

Processing tickers:  85%|████████▌ | 5764/6774 [19:40<03:24,  4.95it/s]

Processing tickers:  85%|████████▌ | 5765/6774 [19:40<03:22,  4.99it/s]

Processing tickers:  85%|████████▌ | 5766/6774 [19:40<03:22,  4.97it/s]

Processing tickers:  85%|████████▌ | 5767/6774 [19:41<03:21,  4.99it/s]

Processing tickers:  85%|████████▌ | 5768/6774 [19:41<03:20,  5.01it/s]

Processing tickers:  85%|████████▌ | 5769/6774 [19:41<03:19,  5.03it/s]

Processing tickers:  85%|████████▌ | 5770/6774 [19:41<03:20,  5.00it/s]

Processing tickers:  85%|████████▌ | 5771/6774 [19:41<03:20,  5.01it/s]

Processing tickers:  85%|████████▌ | 5772/6774 [19:42<03:23,  4.92it/s]

Processing tickers:  85%|████████▌ | 5773/6774 [19:42<03:22,  4.95it/s]

Processing tickers:  85%|████████▌ | 5774/6774 [19:42<03:20,  4.99it/s]

Processing tickers:  85%|████████▌ | 5775/6774 [19:42<03:20,  4.99it/s]

Processing tickers:  85%|████████▌ | 5776/6774 [19:42<03:18,  5.03it/s]

Processing tickers:  85%|████████▌ | 5777/6774 [19:43<03:18,  5.01it/s]

Processing tickers:  85%|████████▌ | 5778/6774 [19:43<03:19,  5.00it/s]

Processing tickers:  85%|████████▌ | 5779/6774 [19:43<03:18,  5.01it/s]

Processing tickers:  85%|████████▌ | 5780/6774 [19:43<03:23,  4.89it/s]

Processing tickers:  85%|████████▌ | 5781/6774 [19:43<03:22,  4.91it/s]

Processing tickers:  85%|████████▌ | 5782/6774 [19:44<03:21,  4.92it/s]

Processing tickers:  85%|████████▌ | 5783/6774 [19:44<03:23,  4.88it/s]

Processing tickers:  85%|████████▌ | 5784/6774 [19:44<03:21,  4.91it/s]

Processing tickers:  85%|████████▌ | 5785/6774 [19:44<03:23,  4.86it/s]

Processing tickers:  85%|████████▌ | 5786/6774 [19:44<03:24,  4.83it/s]

Processing tickers:  85%|████████▌ | 5787/6774 [19:45<03:21,  4.89it/s]

Processing tickers:  85%|████████▌ | 5788/6774 [19:45<03:19,  4.94it/s]

Processing tickers:  85%|████████▌ | 5789/6774 [19:45<03:18,  4.97it/s]

Processing tickers:  85%|████████▌ | 5790/6774 [19:45<03:17,  4.98it/s]

Processing tickers:  85%|████████▌ | 5791/6774 [19:45<03:17,  4.97it/s]

Processing tickers:  86%|████████▌ | 5792/6774 [19:46<03:17,  4.97it/s]

Processing tickers:  86%|████████▌ | 5793/6774 [19:46<03:17,  4.98it/s]

Processing tickers:  86%|████████▌ | 5794/6774 [19:46<03:18,  4.93it/s]

Processing tickers:  86%|████████▌ | 5795/6774 [19:46<03:19,  4.91it/s]

Processing tickers:  86%|████████▌ | 5796/6774 [19:46<03:16,  4.96it/s]

Processing tickers:  86%|████████▌ | 5797/6774 [19:47<03:17,  4.95it/s]

Processing tickers:  86%|████████▌ | 5798/6774 [19:47<03:15,  4.99it/s]

Processing tickers:  86%|████████▌ | 5799/6774 [19:47<03:13,  5.03it/s]

Processing tickers:  86%|████████▌ | 5800/6774 [19:47<03:22,  4.81it/s]

Processing tickers:  86%|████████▌ | 5801/6774 [19:48<03:23,  4.79it/s]

Processing tickers:  86%|████████▌ | 5802/6774 [19:48<03:24,  4.76it/s]

Processing tickers:  86%|████████▌ | 5803/6774 [19:48<03:25,  4.72it/s]

Processing tickers:  86%|████████▌ | 5804/6774 [19:48<03:22,  4.78it/s]

Processing tickers:  86%|████████▌ | 5805/6774 [19:48<03:19,  4.85it/s]

Processing tickers:  86%|████████▌ | 5806/6774 [19:49<03:18,  4.86it/s]

Processing tickers:  86%|████████▌ | 5807/6774 [19:49<03:17,  4.90it/s]

Processing tickers:  86%|████████▌ | 5808/6774 [19:49<03:15,  4.95it/s]

Processing tickers:  86%|████████▌ | 5809/6774 [19:49<03:14,  4.96it/s]

Processing tickers:  86%|████████▌ | 5810/6774 [19:49<03:13,  4.99it/s]

Processing tickers:  86%|████████▌ | 5811/6774 [19:50<03:11,  5.02it/s]

Processing tickers:  86%|████████▌ | 5812/6774 [19:50<03:11,  5.03it/s]

Processing tickers:  86%|████████▌ | 5813/6774 [19:50<03:11,  5.02it/s]

Processing tickers:  86%|████████▌ | 5814/6774 [19:50<03:11,  5.02it/s]

Processing tickers:  86%|████████▌ | 5815/6774 [19:50<03:11,  5.00it/s]

Processing tickers:  86%|████████▌ | 5816/6774 [19:51<03:11,  5.01it/s]

Processing tickers:  86%|████████▌ | 5817/6774 [19:51<03:11,  4.99it/s]

Processing tickers:  86%|████████▌ | 5818/6774 [19:51<03:11,  4.99it/s]

Processing tickers:  86%|████████▌ | 5819/6774 [19:51<03:11,  4.98it/s]

Processing tickers:  86%|████████▌ | 5820/6774 [19:51<03:10,  5.01it/s]

Processing tickers:  86%|████████▌ | 5821/6774 [19:52<03:09,  5.03it/s]

Processing tickers:  86%|████████▌ | 5822/6774 [19:52<03:09,  5.02it/s]

Processing tickers:  86%|████████▌ | 5823/6774 [19:52<03:11,  4.97it/s]

Processing tickers:  86%|████████▌ | 5824/6774 [19:52<03:10,  5.00it/s]

Processing tickers:  86%|████████▌ | 5825/6774 [19:52<03:10,  4.97it/s]

Processing tickers:  86%|████████▌ | 5826/6774 [19:53<03:10,  4.99it/s]

Processing tickers:  86%|████████▌ | 5827/6774 [19:53<03:09,  4.99it/s]

Processing tickers:  86%|████████▌ | 5828/6774 [19:53<03:09,  5.00it/s]

Processing tickers:  86%|████████▌ | 5829/6774 [19:53<03:08,  5.01it/s]

Processing tickers:  86%|████████▌ | 5830/6774 [19:53<03:08,  5.01it/s]

Processing tickers:  86%|████████▌ | 5831/6774 [19:54<03:07,  5.03it/s]

Processing tickers:  86%|████████▌ | 5832/6774 [19:54<03:06,  5.05it/s]

Processing tickers:  86%|████████▌ | 5833/6774 [19:54<03:06,  5.04it/s]

Processing tickers:  86%|████████▌ | 5834/6774 [19:54<03:10,  4.94it/s]

Processing tickers:  86%|████████▌ | 5835/6774 [19:54<03:09,  4.96it/s]

Processing tickers:  86%|████████▌ | 5836/6774 [19:55<03:08,  4.97it/s]

Processing tickers:  86%|████████▌ | 5837/6774 [19:55<03:12,  4.86it/s]

Processing tickers:  86%|████████▌ | 5838/6774 [19:55<03:10,  4.91it/s]

Processing tickers:  86%|████████▌ | 5839/6774 [19:55<03:09,  4.94it/s]

Processing tickers:  86%|████████▌ | 5840/6774 [19:55<03:10,  4.91it/s]

Processing tickers:  86%|████████▌ | 5841/6774 [19:56<03:08,  4.95it/s]

Processing tickers:  86%|████████▌ | 5842/6774 [19:56<03:08,  4.95it/s]

Processing tickers:  86%|████████▋ | 5843/6774 [19:56<03:08,  4.95it/s]

Processing tickers:  86%|████████▋ | 5844/6774 [19:56<03:06,  4.98it/s]

Processing tickers:  86%|████████▋ | 5845/6774 [19:56<03:12,  4.83it/s]

Processing tickers:  86%|████████▋ | 5846/6774 [19:57<03:08,  4.91it/s]

Processing tickers:  86%|████████▋ | 5847/6774 [19:57<03:08,  4.92it/s]

Processing tickers:  86%|████████▋ | 5848/6774 [19:57<03:12,  4.81it/s]

Processing tickers:  86%|████████▋ | 5849/6774 [19:57<03:10,  4.85it/s]

Processing tickers:  86%|████████▋ | 5850/6774 [19:57<03:09,  4.88it/s]

Processing tickers:  86%|████████▋ | 5851/6774 [19:58<03:07,  4.91it/s]

Processing tickers:  86%|████████▋ | 5852/6774 [19:58<03:07,  4.92it/s]

Processing tickers:  86%|████████▋ | 5853/6774 [19:58<03:14,  4.73it/s]

Processing tickers:  86%|████████▋ | 5854/6774 [19:58<03:12,  4.78it/s]

Processing tickers:  86%|████████▋ | 5855/6774 [19:58<03:09,  4.86it/s]

Processing tickers:  86%|████████▋ | 5856/6774 [19:59<03:09,  4.86it/s]

Processing tickers:  86%|████████▋ | 5857/6774 [19:59<03:09,  4.83it/s]

Processing tickers:  86%|████████▋ | 5858/6774 [19:59<03:07,  4.88it/s]

Processing tickers:  86%|████████▋ | 5859/6774 [19:59<03:08,  4.87it/s]

Processing tickers:  87%|████████▋ | 5860/6774 [19:59<03:12,  4.76it/s]

Processing tickers:  87%|████████▋ | 5861/6774 [20:00<03:09,  4.83it/s]

Processing tickers:  87%|████████▋ | 5862/6774 [20:02<12:39,  1.20it/s]

Processing tickers:  87%|████████▋ | 5863/6774 [20:02<10:03,  1.51it/s]

Processing tickers:  87%|████████▋ | 5864/6774 [20:02<07:57,  1.91it/s]

Processing tickers:  87%|████████▋ | 5865/6774 [20:03<06:31,  2.32it/s]

Processing tickers:  87%|████████▋ | 5866/6774 [20:03<05:35,  2.70it/s]

Processing tickers:  87%|████████▋ | 5867/6774 [20:03<04:50,  3.12it/s]

Processing tickers:  87%|████████▋ | 5868/6774 [20:03<04:16,  3.53it/s]

Processing tickers:  87%|████████▋ | 5869/6774 [20:03<03:54,  3.85it/s]

Processing tickers:  87%|████████▋ | 5870/6774 [20:04<03:39,  4.12it/s]

Processing tickers:  87%|████████▋ | 5871/6774 [20:04<03:27,  4.35it/s]

Processing tickers:  87%|████████▋ | 5872/6774 [20:04<03:22,  4.44it/s]

Processing tickers:  87%|████████▋ | 5873/6774 [20:04<03:17,  4.57it/s]

Processing tickers:  87%|████████▋ | 5874/6774 [20:05<03:10,  4.72it/s]

Processing tickers:  87%|████████▋ | 5875/6774 [20:05<03:08,  4.77it/s]

Processing tickers:  87%|████████▋ | 5876/6774 [20:05<03:05,  4.84it/s]

Processing tickers:  87%|████████▋ | 5877/6774 [20:05<03:05,  4.83it/s]

Processing tickers:  87%|████████▋ | 5878/6774 [20:05<03:05,  4.84it/s]

Processing tickers:  87%|████████▋ | 5879/6774 [20:06<03:02,  4.91it/s]

Processing tickers:  87%|████████▋ | 5880/6774 [20:06<03:06,  4.80it/s]

Processing tickers:  87%|████████▋ | 5881/6774 [20:06<03:03,  4.85it/s]

Processing tickers:  87%|████████▋ | 5882/6774 [20:06<03:02,  4.88it/s]

Processing tickers:  87%|████████▋ | 5883/6774 [20:06<03:00,  4.93it/s]

Processing tickers:  87%|████████▋ | 5884/6774 [20:07<03:01,  4.90it/s]

Processing tickers:  87%|████████▋ | 5885/6774 [20:07<02:59,  4.95it/s]

Processing tickers:  87%|████████▋ | 5886/6774 [20:07<03:00,  4.91it/s]

Processing tickers:  87%|████████▋ | 5887/6774 [20:07<03:01,  4.89it/s]

Processing tickers:  87%|████████▋ | 5888/6774 [20:07<03:08,  4.71it/s]

Processing tickers:  87%|████████▋ | 5889/6774 [20:08<03:11,  4.62it/s]

Processing tickers:  87%|████████▋ | 5890/6774 [20:08<03:13,  4.56it/s]

Processing tickers:  87%|████████▋ | 5891/6774 [20:08<03:07,  4.70it/s]

Processing tickers:  87%|████████▋ | 5892/6774 [20:08<03:03,  4.80it/s]

Processing tickers:  87%|████████▋ | 5893/6774 [20:08<03:03,  4.79it/s]

Processing tickers:  87%|████████▋ | 5894/6774 [20:09<03:03,  4.79it/s]

Processing tickers:  87%|████████▋ | 5895/6774 [20:09<03:04,  4.77it/s]

Processing tickers:  87%|████████▋ | 5896/6774 [20:09<03:04,  4.75it/s]

Processing tickers:  87%|████████▋ | 5897/6774 [20:09<03:11,  4.58it/s]

Processing tickers:  87%|████████▋ | 5898/6774 [20:10<03:09,  4.63it/s]

Processing tickers:  87%|████████▋ | 5899/6774 [20:10<03:04,  4.74it/s]

Processing tickers:  87%|████████▋ | 5900/6774 [20:10<03:01,  4.82it/s]

Processing tickers:  87%|████████▋ | 5901/6774 [20:10<03:01,  4.82it/s]

Processing tickers:  87%|████████▋ | 5902/6774 [20:10<02:59,  4.85it/s]

Processing tickers:  87%|████████▋ | 5903/6774 [20:11<02:58,  4.88it/s]

Processing tickers:  87%|████████▋ | 5904/6774 [20:11<02:56,  4.92it/s]

Processing tickers:  87%|████████▋ | 5905/6774 [20:11<02:55,  4.96it/s]

Processing tickers:  87%|████████▋ | 5906/6774 [20:11<02:54,  4.97it/s]

Processing tickers:  87%|████████▋ | 5907/6774 [20:11<02:53,  4.99it/s]

Processing tickers:  87%|████████▋ | 5908/6774 [20:12<02:54,  4.96it/s]

Processing tickers:  87%|████████▋ | 5909/6774 [20:12<02:54,  4.97it/s]

Processing tickers:  87%|████████▋ | 5910/6774 [20:12<02:57,  4.88it/s]

Processing tickers:  87%|████████▋ | 5911/6774 [20:12<02:55,  4.91it/s]

Processing tickers:  87%|████████▋ | 5912/6774 [20:12<02:59,  4.80it/s]

Processing tickers:  87%|████████▋ | 5913/6774 [20:13<02:58,  4.83it/s]

Processing tickers:  87%|████████▋ | 5914/6774 [20:13<02:55,  4.89it/s]

Processing tickers:  87%|████████▋ | 5915/6774 [20:13<02:57,  4.85it/s]

Processing tickers:  87%|████████▋ | 5916/6774 [20:13<02:54,  4.91it/s]

Processing tickers:  87%|████████▋ | 5917/6774 [20:13<02:58,  4.81it/s]

Processing tickers:  87%|████████▋ | 5918/6774 [20:14<02:56,  4.85it/s]

Processing tickers:  87%|████████▋ | 5919/6774 [20:14<02:55,  4.87it/s]

Processing tickers:  87%|████████▋ | 5920/6774 [20:14<02:55,  4.86it/s]

Processing tickers:  87%|████████▋ | 5921/6774 [20:14<02:54,  4.88it/s]

Processing tickers:  87%|████████▋ | 5922/6774 [20:14<02:53,  4.91it/s]

Processing tickers:  87%|████████▋ | 5923/6774 [20:15<02:54,  4.88it/s]

Processing tickers:  87%|████████▋ | 5924/6774 [20:15<02:53,  4.89it/s]

Processing tickers:  87%|████████▋ | 5925/6774 [20:15<02:52,  4.93it/s]

Processing tickers:  87%|████████▋ | 5926/6774 [20:15<02:52,  4.90it/s]

Processing tickers:  87%|████████▋ | 5927/6774 [20:15<02:54,  4.84it/s]

Processing tickers:  88%|████████▊ | 5928/6774 [20:16<02:54,  4.85it/s]

Processing tickers:  88%|████████▊ | 5929/6774 [20:16<02:58,  4.72it/s]

Processing tickers:  88%|████████▊ | 5930/6774 [20:16<03:01,  4.65it/s]

Processing tickers:  88%|████████▊ | 5931/6774 [20:16<02:58,  4.72it/s]

Processing tickers:  88%|████████▊ | 5932/6774 [20:17<02:57,  4.73it/s]

Processing tickers:  88%|████████▊ | 5933/6774 [20:17<02:57,  4.74it/s]

Processing tickers:  88%|████████▊ | 5934/6774 [20:17<02:53,  4.83it/s]

Processing tickers:  88%|████████▊ | 5935/6774 [20:17<02:54,  4.82it/s]

Processing tickers:  88%|████████▊ | 5936/6774 [20:17<02:51,  4.90it/s]

Processing tickers:  88%|████████▊ | 5937/6774 [20:18<02:50,  4.90it/s]

Processing tickers:  88%|████████▊ | 5938/6774 [20:18<02:50,  4.89it/s]

Processing tickers:  88%|████████▊ | 5939/6774 [20:18<02:48,  4.96it/s]

Processing tickers:  88%|████████▊ | 5940/6774 [20:18<02:49,  4.92it/s]

Processing tickers:  88%|████████▊ | 5941/6774 [20:18<02:51,  4.85it/s]

Processing tickers:  88%|████████▊ | 5942/6774 [20:19<02:55,  4.74it/s]

Processing tickers:  88%|████████▊ | 5943/6774 [20:19<02:51,  4.84it/s]

Processing tickers:  88%|████████▊ | 5944/6774 [20:19<02:52,  4.80it/s]

Processing tickers:  88%|████████▊ | 5945/6774 [20:19<02:52,  4.80it/s]

Processing tickers:  88%|████████▊ | 5946/6774 [20:19<02:55,  4.73it/s]

Processing tickers:  88%|████████▊ | 5947/6774 [20:20<02:53,  4.75it/s]

Processing tickers:  88%|████████▊ | 5948/6774 [20:20<02:50,  4.83it/s]

Processing tickers:  88%|████████▊ | 5949/6774 [20:20<02:51,  4.81it/s]

Processing tickers:  88%|████████▊ | 5950/6774 [20:20<02:49,  4.86it/s]

Processing tickers:  88%|████████▊ | 5951/6774 [20:20<02:49,  4.87it/s]

Processing tickers:  88%|████████▊ | 5952/6774 [20:21<02:48,  4.87it/s]

Processing tickers:  88%|████████▊ | 5953/6774 [20:21<02:47,  4.89it/s]

Processing tickers:  88%|████████▊ | 5954/6774 [20:21<02:45,  4.96it/s]

Processing tickers:  88%|████████▊ | 5955/6774 [20:21<02:46,  4.93it/s]

Processing tickers:  88%|████████▊ | 5956/6774 [20:21<02:45,  4.95it/s]

Processing tickers:  88%|████████▊ | 5957/6774 [20:22<02:45,  4.93it/s]

Processing tickers:  88%|████████▊ | 5958/6774 [20:22<02:44,  4.96it/s]

Processing tickers:  88%|████████▊ | 5959/6774 [20:22<02:45,  4.92it/s]

Processing tickers:  88%|████████▊ | 5960/6774 [20:22<02:45,  4.92it/s]

Processing tickers:  88%|████████▊ | 5961/6774 [20:22<02:44,  4.95it/s]

Processing tickers:  88%|████████▊ | 5962/6774 [20:23<02:43,  4.98it/s]

Processing tickers:  88%|████████▊ | 5963/6774 [20:23<02:42,  4.98it/s]

Processing tickers:  88%|████████▊ | 5964/6774 [20:23<02:42,  4.99it/s]

Processing tickers:  88%|████████▊ | 5965/6774 [20:23<02:41,  5.01it/s]

Processing tickers:  88%|████████▊ | 5966/6774 [20:24<02:55,  4.62it/s]

Processing tickers:  88%|████████▊ | 5967/6774 [20:24<02:51,  4.70it/s]

Processing tickers:  88%|████████▊ | 5968/6774 [20:24<02:48,  4.77it/s]

Processing tickers:  88%|████████▊ | 5969/6774 [20:24<02:45,  4.85it/s]

Processing tickers:  88%|████████▊ | 5970/6774 [20:24<02:50,  4.71it/s]

Processing tickers:  88%|████████▊ | 5971/6774 [20:25<02:47,  4.80it/s]

Processing tickers:  88%|████████▊ | 5972/6774 [20:25<02:45,  4.85it/s]

Processing tickers:  88%|████████▊ | 5973/6774 [20:25<02:42,  4.92it/s]

Processing tickers:  88%|████████▊ | 5974/6774 [20:25<02:42,  4.94it/s]

Processing tickers:  88%|████████▊ | 5975/6774 [20:25<02:41,  4.95it/s]

Processing tickers:  88%|████████▊ | 5976/6774 [20:26<02:39,  4.99it/s]

Processing tickers:  88%|████████▊ | 5977/6774 [20:26<02:39,  5.01it/s]

Processing tickers:  88%|████████▊ | 5978/6774 [20:26<02:41,  4.92it/s]

Processing tickers:  88%|████████▊ | 5979/6774 [20:26<02:40,  4.95it/s]

Processing tickers:  88%|████████▊ | 5980/6774 [20:26<02:45,  4.79it/s]

Processing tickers:  88%|████████▊ | 5981/6774 [20:27<02:43,  4.84it/s]

Processing tickers:  88%|████████▊ | 5982/6774 [20:27<02:42,  4.87it/s]

Processing tickers:  88%|████████▊ | 5983/6774 [20:27<02:44,  4.82it/s]

Processing tickers:  88%|████████▊ | 5984/6774 [20:27<02:42,  4.86it/s]

Processing tickers:  88%|████████▊ | 5985/6774 [20:27<02:45,  4.77it/s]

Processing tickers:  88%|████████▊ | 5986/6774 [20:28<02:43,  4.83it/s]

Processing tickers:  88%|████████▊ | 5987/6774 [20:28<02:41,  4.86it/s]

Processing tickers:  88%|████████▊ | 5988/6774 [20:28<02:42,  4.85it/s]

Processing tickers:  88%|████████▊ | 5989/6774 [20:28<02:40,  4.89it/s]

Processing tickers:  88%|████████▊ | 5990/6774 [20:28<02:40,  4.90it/s]

Processing tickers:  88%|████████▊ | 5991/6774 [20:29<02:39,  4.91it/s]

Processing tickers:  88%|████████▊ | 5992/6774 [20:29<02:38,  4.95it/s]

Processing tickers:  88%|████████▊ | 5993/6774 [20:29<02:37,  4.97it/s]

Processing tickers:  88%|████████▊ | 5994/6774 [20:29<02:37,  4.97it/s]

Processing tickers:  89%|████████▊ | 5995/6774 [20:29<02:39,  4.87it/s]

Processing tickers:  89%|████████▊ | 5996/6774 [20:30<02:40,  4.84it/s]

Processing tickers:  89%|████████▊ | 5997/6774 [20:30<02:38,  4.89it/s]

Processing tickers:  89%|████████▊ | 5998/6774 [20:30<02:36,  4.94it/s]

Processing tickers:  89%|████████▊ | 5999/6774 [20:30<02:36,  4.96it/s]

Processing tickers:  89%|████████▊ | 6000/6774 [20:30<02:36,  4.95it/s]

Processing tickers:  89%|████████▊ | 6001/6774 [20:31<02:37,  4.91it/s]

Processing tickers:  89%|████████▊ | 6002/6774 [20:31<02:36,  4.94it/s]

Processing tickers:  89%|████████▊ | 6003/6774 [20:31<02:41,  4.77it/s]

Processing tickers:  89%|████████▊ | 6004/6774 [20:31<02:39,  4.82it/s]

Processing tickers:  89%|████████▊ | 6005/6774 [20:31<02:43,  4.70it/s]

Processing tickers:  89%|████████▊ | 6006/6774 [20:32<02:44,  4.68it/s]

Processing tickers:  89%|████████▊ | 6007/6774 [20:32<02:40,  4.77it/s]

Processing tickers:  89%|████████▊ | 6008/6774 [20:32<02:42,  4.71it/s]

Processing tickers:  89%|████████▊ | 6009/6774 [20:32<02:39,  4.81it/s]

Processing tickers:  89%|████████▊ | 6010/6774 [20:33<02:38,  4.83it/s]

Processing tickers:  89%|████████▊ | 6011/6774 [20:33<02:35,  4.90it/s]

Processing tickers:  89%|████████▉ | 6012/6774 [20:33<02:34,  4.95it/s]

Processing tickers:  89%|████████▉ | 6013/6774 [20:33<02:43,  4.65it/s]

Processing tickers:  89%|████████▉ | 6014/6774 [20:33<02:49,  4.49it/s]

Processing tickers:  89%|████████▉ | 6015/6774 [20:34<02:45,  4.57it/s]

Processing tickers:  89%|████████▉ | 6016/6774 [20:34<02:42,  4.68it/s]

Processing tickers:  89%|████████▉ | 6017/6774 [20:34<02:44,  4.59it/s]

Processing tickers:  89%|████████▉ | 6018/6774 [20:34<02:39,  4.73it/s]

Processing tickers:  89%|████████▉ | 6019/6774 [20:34<02:42,  4.66it/s]

Processing tickers:  89%|████████▉ | 6020/6774 [20:35<02:38,  4.76it/s]

Processing tickers:  89%|████████▉ | 6021/6774 [20:35<02:35,  4.84it/s]

Processing tickers:  89%|████████▉ | 6022/6774 [20:35<02:35,  4.83it/s]

Processing tickers:  89%|████████▉ | 6023/6774 [20:35<02:34,  4.86it/s]

Processing tickers:  89%|████████▉ | 6024/6774 [20:35<02:32,  4.92it/s]

Processing tickers:  89%|████████▉ | 6025/6774 [20:36<02:32,  4.91it/s]

Processing tickers:  89%|████████▉ | 6026/6774 [20:36<02:32,  4.91it/s]

Processing tickers:  89%|████████▉ | 6027/6774 [20:36<02:37,  4.74it/s]

Processing tickers:  89%|████████▉ | 6028/6774 [20:36<02:36,  4.78it/s]

Processing tickers:  89%|████████▉ | 6029/6774 [20:37<02:33,  4.86it/s]

Processing tickers:  89%|████████▉ | 6030/6774 [20:37<02:38,  4.69it/s]

Processing tickers:  89%|████████▉ | 6031/6774 [20:37<02:34,  4.80it/s]

Processing tickers:  89%|████████▉ | 6032/6774 [20:37<02:41,  4.58it/s]

Processing tickers:  89%|████████▉ | 6033/6774 [20:37<02:37,  4.70it/s]

Processing tickers:  89%|████████▉ | 6034/6774 [20:38<02:34,  4.78it/s]

Processing tickers:  89%|████████▉ | 6035/6774 [20:38<02:31,  4.86it/s]

Processing tickers:  89%|████████▉ | 6036/6774 [20:38<02:33,  4.80it/s]

Processing tickers:  89%|████████▉ | 6037/6774 [20:38<02:32,  4.84it/s]

Processing tickers:  89%|████████▉ | 6038/6774 [20:38<02:30,  4.89it/s]

Processing tickers:  89%|████████▉ | 6039/6774 [20:39<02:29,  4.91it/s]

Processing tickers:  89%|████████▉ | 6040/6774 [20:39<02:27,  4.96it/s]

Processing tickers:  89%|████████▉ | 6041/6774 [20:39<02:33,  4.78it/s]

Processing tickers:  89%|████████▉ | 6042/6774 [20:39<02:32,  4.81it/s]

Processing tickers:  89%|████████▉ | 6043/6774 [20:39<02:30,  4.87it/s]

Processing tickers:  89%|████████▉ | 6044/6774 [20:40<02:30,  4.84it/s]

Processing tickers:  89%|████████▉ | 6045/6774 [20:40<02:30,  4.84it/s]

Processing tickers:  89%|████████▉ | 6046/6774 [20:40<02:29,  4.87it/s]

Processing tickers:  89%|████████▉ | 6047/6774 [20:40<02:28,  4.88it/s]

Processing tickers:  89%|████████▉ | 6048/6774 [20:40<02:30,  4.84it/s]

Processing tickers:  89%|████████▉ | 6049/6774 [20:41<02:32,  4.76it/s]

Processing tickers:  89%|████████▉ | 6050/6774 [20:41<02:29,  4.83it/s]

Processing tickers:  89%|████████▉ | 6051/6774 [20:41<02:32,  4.73it/s]

Processing tickers:  89%|████████▉ | 6052/6774 [20:41<02:30,  4.81it/s]

Processing tickers:  89%|████████▉ | 6053/6774 [20:42<02:28,  4.86it/s]

Processing tickers:  89%|████████▉ | 6054/6774 [20:42<02:30,  4.80it/s]

Processing tickers:  89%|████████▉ | 6055/6774 [20:42<02:27,  4.87it/s]

Processing tickers:  89%|████████▉ | 6056/6774 [20:42<02:28,  4.84it/s]

Processing tickers:  89%|████████▉ | 6057/6774 [20:42<02:29,  4.81it/s]

Processing tickers:  89%|████████▉ | 6058/6774 [20:43<02:27,  4.86it/s]

Processing tickers:  89%|████████▉ | 6059/6774 [20:43<02:25,  4.91it/s]

Processing tickers:  89%|████████▉ | 6060/6774 [20:43<02:24,  4.95it/s]

Processing tickers:  89%|████████▉ | 6061/6774 [20:43<02:23,  4.96it/s]

Processing tickers:  89%|████████▉ | 6062/6774 [20:43<02:23,  4.95it/s]

Processing tickers:  90%|████████▉ | 6063/6774 [20:44<02:27,  4.81it/s]

Processing tickers:  90%|████████▉ | 6064/6774 [20:44<02:26,  4.85it/s]

Processing tickers:  90%|████████▉ | 6065/6774 [20:44<02:31,  4.67it/s]

Processing tickers:  90%|████████▉ | 6066/6774 [20:44<02:29,  4.74it/s]

Processing tickers:  90%|████████▉ | 6067/6774 [20:44<02:27,  4.78it/s]

Processing tickers:  90%|████████▉ | 6068/6774 [20:45<02:25,  4.85it/s]

Processing tickers:  90%|████████▉ | 6069/6774 [20:45<02:24,  4.88it/s]

Processing tickers:  90%|████████▉ | 6070/6774 [20:45<02:22,  4.92it/s]

Processing tickers:  90%|████████▉ | 6071/6774 [20:45<02:21,  4.95it/s]

Processing tickers:  90%|████████▉ | 6072/6774 [20:45<02:22,  4.91it/s]

Processing tickers:  90%|████████▉ | 6073/6774 [20:46<02:21,  4.95it/s]

Processing tickers:  90%|████████▉ | 6074/6774 [20:46<02:21,  4.93it/s]

Processing tickers:  90%|████████▉ | 6075/6774 [20:46<02:21,  4.93it/s]

Processing tickers:  90%|████████▉ | 6076/6774 [20:46<02:20,  4.98it/s]

Processing tickers:  90%|████████▉ | 6077/6774 [20:46<02:24,  4.82it/s]

Processing tickers:  90%|████████▉ | 6078/6774 [20:47<02:23,  4.86it/s]

Processing tickers:  90%|████████▉ | 6079/6774 [20:47<02:21,  4.91it/s]

Processing tickers:  90%|████████▉ | 6080/6774 [20:47<02:20,  4.92it/s]

Processing tickers:  90%|████████▉ | 6081/6774 [20:47<02:19,  4.98it/s]

Processing tickers:  90%|████████▉ | 6082/6774 [20:47<02:19,  4.95it/s]

Processing tickers:  90%|████████▉ | 6083/6774 [20:48<02:23,  4.83it/s]

Processing tickers:  90%|████████▉ | 6084/6774 [20:48<02:22,  4.83it/s]

Processing tickers:  90%|████████▉ | 6085/6774 [20:48<02:23,  4.80it/s]

Processing tickers:  90%|████████▉ | 6086/6774 [20:48<02:25,  4.74it/s]

Processing tickers:  90%|████████▉ | 6087/6774 [20:49<02:25,  4.71it/s]

Processing tickers:  90%|████████▉ | 6088/6774 [20:49<02:23,  4.78it/s]

Processing tickers:  90%|████████▉ | 6089/6774 [20:49<02:24,  4.76it/s]

Processing tickers:  90%|████████▉ | 6090/6774 [20:49<02:25,  4.69it/s]

Processing tickers:  90%|████████▉ | 6091/6774 [20:49<02:22,  4.79it/s]

Processing tickers:  90%|████████▉ | 6092/6774 [20:50<02:21,  4.83it/s]

Processing tickers:  90%|████████▉ | 6093/6774 [20:50<02:20,  4.84it/s]

Processing tickers:  90%|████████▉ | 6094/6774 [20:50<02:18,  4.91it/s]

Processing tickers:  90%|████████▉ | 6095/6774 [20:50<02:17,  4.95it/s]

Processing tickers:  90%|████████▉ | 6096/6774 [20:50<02:16,  4.98it/s]

Processing tickers:  90%|█████████ | 6097/6774 [20:51<02:16,  4.98it/s]

Processing tickers:  90%|█████████ | 6098/6774 [20:51<02:14,  5.01it/s]

Processing tickers:  90%|█████████ | 6099/6774 [20:51<02:14,  5.03it/s]

Processing tickers:  90%|█████████ | 6100/6774 [20:51<02:14,  5.00it/s]

Processing tickers:  90%|█████████ | 6101/6774 [20:51<02:14,  5.01it/s]

Processing tickers:  90%|█████████ | 6102/6774 [20:52<02:15,  4.94it/s]

Processing tickers:  90%|█████████ | 6103/6774 [20:52<02:16,  4.93it/s]

Processing tickers:  90%|█████████ | 6104/6774 [20:52<02:17,  4.86it/s]

Processing tickers:  90%|█████████ | 6105/6774 [20:52<02:17,  4.87it/s]

Processing tickers:  90%|█████████ | 6106/6774 [20:52<02:18,  4.84it/s]

Processing tickers:  90%|█████████ | 6107/6774 [20:53<02:16,  4.87it/s]

Processing tickers:  90%|█████████ | 6108/6774 [20:53<02:15,  4.91it/s]

Processing tickers:  90%|█████████ | 6109/6774 [20:53<02:17,  4.83it/s]

Processing tickers:  90%|█████████ | 6110/6774 [20:53<02:18,  4.80it/s]

Processing tickers:  90%|█████████ | 6111/6774 [20:53<02:15,  4.88it/s]

Processing tickers:  90%|█████████ | 6112/6774 [20:54<02:15,  4.90it/s]

Processing tickers:  90%|█████████ | 6113/6774 [20:54<02:13,  4.95it/s]

Processing tickers:  90%|█████████ | 6114/6774 [20:54<02:13,  4.95it/s]

Processing tickers:  90%|█████████ | 6115/6774 [20:54<02:14,  4.92it/s]

Processing tickers:  90%|█████████ | 6116/6774 [20:54<02:13,  4.94it/s]

Processing tickers:  90%|█████████ | 6117/6774 [20:55<02:12,  4.94it/s]

Processing tickers:  90%|█████████ | 6118/6774 [20:55<02:13,  4.92it/s]

Processing tickers:  90%|█████████ | 6119/6774 [20:55<02:14,  4.86it/s]

Processing tickers:  90%|█████████ | 6120/6774 [20:55<02:14,  4.87it/s]

Processing tickers:  90%|█████████ | 6121/6774 [20:55<02:12,  4.94it/s]

Processing tickers:  90%|█████████ | 6122/6774 [20:56<02:11,  4.95it/s]

Processing tickers:  90%|█████████ | 6123/6774 [20:56<02:11,  4.95it/s]

Processing tickers:  90%|█████████ | 6124/6774 [20:56<02:10,  5.00it/s]

Processing tickers:  90%|█████████ | 6125/6774 [20:56<02:09,  5.01it/s]

Processing tickers:  90%|█████████ | 6126/6774 [20:56<02:09,  5.02it/s]

Processing tickers:  90%|█████████ | 6127/6774 [20:57<02:08,  5.03it/s]

Processing tickers:  90%|█████████ | 6128/6774 [20:57<02:09,  5.01it/s]

Processing tickers:  90%|█████████ | 6129/6774 [20:57<02:09,  5.00it/s]

Processing tickers:  90%|█████████ | 6130/6774 [20:57<02:08,  5.01it/s]

Processing tickers:  91%|█████████ | 6131/6774 [20:57<02:08,  4.99it/s]

Processing tickers:  91%|█████████ | 6132/6774 [20:58<02:08,  5.01it/s]

Processing tickers:  91%|█████████ | 6133/6774 [20:58<02:10,  4.90it/s]

Processing tickers:  91%|█████████ | 6134/6774 [20:58<02:09,  4.95it/s]

Processing tickers:  91%|█████████ | 6135/6774 [20:58<02:08,  4.98it/s]

Processing tickers:  91%|█████████ | 6136/6774 [20:58<02:08,  4.97it/s]

Processing tickers:  91%|█████████ | 6137/6774 [20:59<02:08,  4.96it/s]

Processing tickers:  91%|█████████ | 6138/6774 [20:59<02:08,  4.97it/s]

Processing tickers:  91%|█████████ | 6139/6774 [20:59<02:08,  4.95it/s]

Processing tickers:  91%|█████████ | 6140/6774 [20:59<02:10,  4.87it/s]

Processing tickers:  91%|█████████ | 6141/6774 [20:59<02:09,  4.87it/s]

Processing tickers:  91%|█████████ | 6142/6774 [21:00<02:08,  4.93it/s]

Processing tickers:  91%|█████████ | 6143/6774 [21:00<02:07,  4.94it/s]

Processing tickers:  91%|█████████ | 6144/6774 [21:00<02:07,  4.95it/s]

Processing tickers:  91%|█████████ | 6145/6774 [21:00<02:06,  4.97it/s]

Processing tickers:  91%|█████████ | 6146/6774 [21:00<02:07,  4.91it/s]

Processing tickers:  91%|█████████ | 6147/6774 [21:01<02:06,  4.97it/s]

Processing tickers:  91%|█████████ | 6148/6774 [21:01<02:06,  4.96it/s]

Processing tickers:  91%|█████████ | 6149/6774 [21:01<02:09,  4.81it/s]

Processing tickers:  91%|█████████ | 6150/6774 [21:01<02:08,  4.86it/s]

Processing tickers:  91%|█████████ | 6151/6774 [21:02<02:08,  4.84it/s]

Processing tickers:  91%|█████████ | 6152/6774 [21:02<02:10,  4.78it/s]

Processing tickers:  91%|█████████ | 6153/6774 [21:02<02:09,  4.80it/s]

Processing tickers:  91%|█████████ | 6154/6774 [21:02<02:07,  4.85it/s]

Processing tickers:  91%|█████████ | 6155/6774 [21:02<02:06,  4.89it/s]

Processing tickers:  91%|█████████ | 6156/6774 [21:03<02:09,  4.76it/s]

Processing tickers:  91%|█████████ | 6157/6774 [21:03<02:07,  4.83it/s]

Processing tickers:  91%|█████████ | 6158/6774 [21:03<02:06,  4.86it/s]

Processing tickers:  91%|█████████ | 6159/6774 [21:03<02:09,  4.75it/s]

Processing tickers:  91%|█████████ | 6160/6774 [21:03<02:08,  4.77it/s]

Processing tickers:  91%|█████████ | 6161/6774 [21:04<02:06,  4.86it/s]

Processing tickers:  91%|█████████ | 6162/6774 [21:04<02:04,  4.91it/s]

Processing tickers:  91%|█████████ | 6163/6774 [21:04<02:05,  4.87it/s]

Processing tickers:  91%|█████████ | 6164/6774 [21:04<02:05,  4.87it/s]

Processing tickers:  91%|█████████ | 6165/6774 [21:04<02:04,  4.90it/s]

Processing tickers:  91%|█████████ | 6166/6774 [21:05<02:07,  4.79it/s]

Processing tickers:  91%|█████████ | 6167/6774 [21:05<02:05,  4.83it/s]

Processing tickers:  91%|█████████ | 6168/6774 [21:05<02:03,  4.89it/s]

Processing tickers:  91%|█████████ | 6169/6774 [21:05<02:02,  4.93it/s]

Processing tickers:  91%|█████████ | 6170/6774 [21:05<02:02,  4.93it/s]

Processing tickers:  91%|█████████ | 6171/6774 [21:06<02:01,  4.95it/s]

Processing tickers:  91%|█████████ | 6172/6774 [21:06<02:01,  4.97it/s]

Processing tickers:  91%|█████████ | 6173/6774 [21:06<02:01,  4.96it/s]

Processing tickers:  91%|█████████ | 6174/6774 [21:06<02:01,  4.94it/s]

Processing tickers:  91%|█████████ | 6175/6774 [21:06<02:00,  4.95it/s]

Processing tickers:  91%|█████████ | 6176/6774 [21:07<02:00,  4.96it/s]

Processing tickers:  91%|█████████ | 6177/6774 [21:07<02:00,  4.95it/s]

Processing tickers:  91%|█████████ | 6178/6774 [21:07<01:59,  4.97it/s]

Processing tickers:  91%|█████████ | 6179/6774 [21:07<01:58,  5.00it/s]

Processing tickers:  91%|█████████ | 6180/6774 [21:07<01:59,  4.97it/s]

Processing tickers:  91%|█████████ | 6181/6774 [21:08<01:59,  4.98it/s]

Processing tickers:  91%|█████████▏| 6182/6774 [21:08<01:58,  5.01it/s]

Processing tickers:  91%|█████████▏| 6183/6774 [21:08<01:57,  5.02it/s]

Processing tickers:  91%|█████████▏| 6184/6774 [21:08<01:58,  4.96it/s]

Processing tickers:  91%|█████████▏| 6185/6774 [21:08<01:58,  4.97it/s]

Processing tickers:  91%|█████████▏| 6186/6774 [21:09<01:58,  4.95it/s]

Processing tickers:  91%|█████████▏| 6187/6774 [21:09<01:59,  4.93it/s]

Processing tickers:  91%|█████████▏| 6188/6774 [21:09<01:59,  4.91it/s]

Processing tickers:  91%|█████████▏| 6189/6774 [21:09<01:59,  4.91it/s]

Processing tickers:  91%|█████████▏| 6190/6774 [21:09<01:57,  4.95it/s]

Processing tickers:  91%|█████████▏| 6191/6774 [21:10<01:58,  4.93it/s]

Processing tickers:  91%|█████████▏| 6192/6774 [21:10<01:57,  4.95it/s]

Processing tickers:  91%|█████████▏| 6193/6774 [21:10<01:57,  4.94it/s]

Processing tickers:  91%|█████████▏| 6194/6774 [21:10<01:57,  4.93it/s]

Processing tickers:  91%|█████████▏| 6195/6774 [21:10<01:59,  4.83it/s]

Processing tickers:  91%|█████████▏| 6196/6774 [21:11<02:00,  4.78it/s]

Processing tickers:  91%|█████████▏| 6197/6774 [21:11<02:03,  4.69it/s]

Processing tickers:  91%|█████████▏| 6198/6774 [21:11<02:00,  4.78it/s]

Processing tickers:  92%|█████████▏| 6199/6774 [21:11<02:02,  4.70it/s]

Processing tickers:  92%|█████████▏| 6200/6774 [21:12<02:01,  4.74it/s]

Processing tickers:  92%|█████████▏| 6201/6774 [21:12<01:58,  4.82it/s]

Processing tickers:  92%|█████████▏| 6202/6774 [21:12<01:56,  4.89it/s]

Processing tickers:  92%|█████████▏| 6203/6774 [21:12<01:55,  4.93it/s]

Processing tickers:  92%|█████████▏| 6204/6774 [21:12<01:55,  4.93it/s]

Processing tickers:  92%|█████████▏| 6205/6774 [21:13<02:00,  4.70it/s]

Processing tickers:  92%|█████████▏| 6206/6774 [21:13<01:58,  4.80it/s]

Processing tickers:  92%|█████████▏| 6207/6774 [21:13<02:02,  4.64it/s]

Processing tickers:  92%|█████████▏| 6208/6774 [21:13<01:59,  4.73it/s]

Processing tickers:  92%|█████████▏| 6209/6774 [21:13<01:58,  4.76it/s]

Processing tickers:  92%|█████████▏| 6210/6774 [21:14<01:58,  4.75it/s]

Processing tickers:  92%|█████████▏| 6211/6774 [21:14<01:56,  4.82it/s]

Processing tickers:  92%|█████████▏| 6212/6774 [21:14<01:59,  4.72it/s]

Processing tickers:  92%|█████████▏| 6213/6774 [21:14<01:58,  4.74it/s]

Processing tickers:  92%|█████████▏| 6214/6774 [21:14<01:55,  4.83it/s]

Processing tickers:  92%|█████████▏| 6215/6774 [21:15<01:55,  4.86it/s]

Processing tickers:  92%|█████████▏| 6216/6774 [21:15<01:53,  4.91it/s]

Processing tickers:  92%|█████████▏| 6217/6774 [21:15<01:52,  4.95it/s]

Processing tickers:  92%|█████████▏| 6218/6774 [21:15<01:53,  4.90it/s]

Processing tickers:  92%|█████████▏| 6219/6774 [21:15<01:51,  4.96it/s]

Processing tickers:  92%|█████████▏| 6220/6774 [21:16<01:50,  4.99it/s]

Processing tickers:  92%|█████████▏| 6221/6774 [21:16<01:53,  4.89it/s]

Processing tickers:  92%|█████████▏| 6222/6774 [21:16<01:52,  4.91it/s]

Processing tickers:  92%|█████████▏| 6223/6774 [21:16<01:52,  4.90it/s]

Processing tickers:  92%|█████████▏| 6224/6774 [21:16<01:52,  4.87it/s]

Processing tickers:  92%|█████████▏| 6225/6774 [21:17<01:51,  4.93it/s]

Processing tickers:  92%|█████████▏| 6226/6774 [21:17<01:50,  4.95it/s]

Processing tickers:  92%|█████████▏| 6227/6774 [21:17<01:50,  4.94it/s]

Processing tickers:  92%|█████████▏| 6228/6774 [21:17<01:50,  4.93it/s]

Processing tickers:  92%|█████████▏| 6229/6774 [21:17<01:50,  4.93it/s]

Processing tickers:  92%|█████████▏| 6230/6774 [21:18<01:50,  4.90it/s]

Processing tickers:  92%|█████████▏| 6231/6774 [21:18<01:50,  4.90it/s]

Processing tickers:  92%|█████████▏| 6232/6774 [21:18<01:50,  4.91it/s]

Processing tickers:  92%|█████████▏| 6233/6774 [21:18<01:49,  4.94it/s]

Processing tickers:  92%|█████████▏| 6234/6774 [21:19<01:48,  4.96it/s]

Processing tickers:  92%|█████████▏| 6235/6774 [21:19<01:49,  4.91it/s]

Processing tickers:  92%|█████████▏| 6236/6774 [21:19<01:48,  4.95it/s]

Processing tickers:  92%|█████████▏| 6237/6774 [21:19<01:47,  5.00it/s]

Processing tickers:  92%|█████████▏| 6238/6774 [21:19<01:47,  4.99it/s]

Processing tickers:  92%|█████████▏| 6239/6774 [21:20<01:46,  5.01it/s]

Processing tickers:  92%|█████████▏| 6240/6774 [21:20<01:46,  5.01it/s]

Processing tickers:  92%|█████████▏| 6241/6774 [21:20<01:46,  5.00it/s]

Processing tickers:  92%|█████████▏| 6242/6774 [21:20<01:49,  4.85it/s]

Processing tickers:  92%|█████████▏| 6243/6774 [21:20<01:48,  4.90it/s]

Processing tickers:  92%|█████████▏| 6244/6774 [21:21<01:48,  4.90it/s]

Processing tickers:  92%|█████████▏| 6245/6774 [21:21<01:51,  4.73it/s]

Processing tickers:  92%|█████████▏| 6246/6774 [21:21<01:52,  4.70it/s]

Processing tickers:  92%|█████████▏| 6247/6774 [21:21<01:51,  4.73it/s]

Processing tickers:  92%|█████████▏| 6248/6774 [21:21<01:49,  4.79it/s]

Processing tickers:  92%|█████████▏| 6249/6774 [21:22<01:48,  4.83it/s]

Processing tickers:  92%|█████████▏| 6250/6774 [21:22<01:46,  4.90it/s]

Processing tickers:  92%|█████████▏| 6251/6774 [21:22<01:48,  4.81it/s]

Processing tickers:  92%|█████████▏| 6252/6774 [21:22<01:49,  4.77it/s]

Processing tickers:  92%|█████████▏| 6253/6774 [21:22<01:47,  4.86it/s]

Processing tickers:  92%|█████████▏| 6254/6774 [21:23<01:45,  4.91it/s]

Processing tickers:  92%|█████████▏| 6255/6774 [21:23<01:44,  4.98it/s]

Processing tickers:  92%|█████████▏| 6256/6774 [21:23<01:43,  4.99it/s]

Processing tickers:  92%|█████████▏| 6257/6774 [21:23<01:43,  4.97it/s]

Processing tickers:  92%|█████████▏| 6258/6774 [21:23<01:43,  4.97it/s]

Processing tickers:  92%|█████████▏| 6259/6774 [21:24<01:42,  5.01it/s]

Processing tickers:  92%|█████████▏| 6260/6774 [21:24<01:42,  5.02it/s]

Processing tickers:  92%|█████████▏| 6261/6774 [21:24<01:42,  5.00it/s]

Processing tickers:  92%|█████████▏| 6262/6774 [21:24<01:42,  5.02it/s]

Processing tickers:  92%|█████████▏| 6263/6774 [21:24<01:42,  5.01it/s]

Processing tickers:  92%|█████████▏| 6264/6774 [21:25<01:45,  4.84it/s]

Processing tickers:  92%|█████████▏| 6265/6774 [21:25<01:43,  4.91it/s]

Processing tickers:  93%|█████████▎| 6266/6774 [21:25<01:42,  4.95it/s]

Processing tickers:  93%|█████████▎| 6267/6774 [21:25<01:42,  4.96it/s]

Processing tickers:  93%|█████████▎| 6268/6774 [21:25<01:41,  4.98it/s]

Processing tickers:  93%|█████████▎| 6269/6774 [21:26<01:40,  5.00it/s]

Processing tickers:  93%|█████████▎| 6270/6774 [21:26<01:41,  4.94it/s]

Processing tickers:  93%|█████████▎| 6271/6774 [21:26<01:41,  4.95it/s]

Processing tickers:  93%|█████████▎| 6272/6774 [21:26<01:42,  4.92it/s]

Processing tickers:  93%|█████████▎| 6273/6774 [21:26<01:40,  4.96it/s]

Processing tickers:  93%|█████████▎| 6274/6774 [21:27<01:42,  4.88it/s]

Processing tickers:  93%|█████████▎| 6275/6774 [21:27<01:41,  4.93it/s]

Processing tickers:  93%|█████████▎| 6276/6774 [21:27<01:40,  4.94it/s]

Processing tickers:  93%|█████████▎| 6277/6774 [21:27<01:40,  4.94it/s]

Processing tickers:  93%|█████████▎| 6278/6774 [21:27<01:39,  4.96it/s]

Processing tickers:  93%|█████████▎| 6279/6774 [21:28<01:42,  4.82it/s]

Processing tickers:  93%|█████████▎| 6280/6774 [21:28<01:40,  4.90it/s]

Processing tickers:  93%|█████████▎| 6281/6774 [21:28<01:41,  4.86it/s]

Processing tickers:  93%|█████████▎| 6282/6774 [21:28<01:40,  4.87it/s]

Processing tickers:  93%|█████████▎| 6283/6774 [21:28<01:40,  4.90it/s]

Processing tickers:  93%|█████████▎| 6284/6774 [21:29<01:41,  4.82it/s]

Processing tickers:  93%|█████████▎| 6285/6774 [21:29<01:40,  4.86it/s]

Processing tickers:  93%|█████████▎| 6286/6774 [21:29<01:39,  4.90it/s]

Processing tickers:  93%|█████████▎| 6287/6774 [21:29<01:38,  4.92it/s]

Processing tickers:  93%|█████████▎| 6288/6774 [21:30<01:38,  4.92it/s]

Processing tickers:  93%|█████████▎| 6289/6774 [21:30<01:38,  4.93it/s]

Processing tickers:  93%|█████████▎| 6290/6774 [21:30<01:37,  4.96it/s]

Processing tickers:  93%|█████████▎| 6291/6774 [21:30<01:36,  4.98it/s]

Processing tickers:  93%|█████████▎| 6292/6774 [21:30<01:37,  4.97it/s]

Processing tickers:  93%|█████████▎| 6293/6774 [21:31<01:36,  4.98it/s]

Processing tickers:  93%|█████████▎| 6294/6774 [21:31<01:35,  5.00it/s]

Processing tickers:  93%|█████████▎| 6295/6774 [21:31<01:35,  5.01it/s]

Processing tickers:  93%|█████████▎| 6296/6774 [21:31<01:35,  5.00it/s]

Processing tickers:  93%|█████████▎| 6297/6774 [21:31<01:36,  4.95it/s]

Processing tickers:  93%|█████████▎| 6298/6774 [21:32<01:36,  4.93it/s]

Processing tickers:  93%|█████████▎| 6299/6774 [21:32<01:37,  4.86it/s]

Processing tickers:  93%|█████████▎| 6300/6774 [21:32<01:36,  4.92it/s]

Processing tickers:  93%|█████████▎| 6301/6774 [21:32<01:35,  4.94it/s]

Processing tickers:  93%|█████████▎| 6302/6774 [21:32<01:35,  4.96it/s]

Processing tickers:  93%|█████████▎| 6303/6774 [21:33<01:35,  4.93it/s]

Processing tickers:  93%|█████████▎| 6304/6774 [21:33<01:35,  4.94it/s]

Processing tickers:  93%|█████████▎| 6305/6774 [21:33<01:34,  4.96it/s]

Processing tickers:  93%|█████████▎| 6306/6774 [21:33<01:34,  4.96it/s]

Processing tickers:  93%|█████████▎| 6307/6774 [21:33<01:33,  4.98it/s]

Processing tickers:  93%|█████████▎| 6308/6774 [21:34<01:34,  4.91it/s]

Processing tickers:  93%|█████████▎| 6309/6774 [21:34<01:35,  4.88it/s]

Processing tickers:  93%|█████████▎| 6310/6774 [21:34<01:34,  4.92it/s]

Processing tickers:  93%|█████████▎| 6311/6774 [21:34<01:35,  4.86it/s]

Processing tickers:  93%|█████████▎| 6312/6774 [21:34<01:33,  4.92it/s]

Processing tickers:  93%|█████████▎| 6313/6774 [21:35<01:34,  4.89it/s]

Processing tickers:  93%|█████████▎| 6314/6774 [21:35<01:35,  4.84it/s]

Processing tickers:  93%|█████████▎| 6315/6774 [21:35<01:36,  4.74it/s]

Processing tickers:  93%|█████████▎| 6316/6774 [21:35<01:37,  4.70it/s]

Processing tickers:  93%|█████████▎| 6317/6774 [21:35<01:37,  4.70it/s]

Processing tickers:  93%|█████████▎| 6318/6774 [21:36<01:35,  4.77it/s]

Processing tickers:  93%|█████████▎| 6319/6774 [21:36<01:34,  4.82it/s]

Processing tickers:  93%|█████████▎| 6320/6774 [21:36<01:36,  4.71it/s]

Processing tickers:  93%|█████████▎| 6321/6774 [21:36<01:37,  4.66it/s]

Processing tickers:  93%|█████████▎| 6322/6774 [21:36<01:35,  4.75it/s]

Processing tickers:  93%|█████████▎| 6323/6774 [21:37<01:33,  4.81it/s]

Processing tickers:  93%|█████████▎| 6324/6774 [21:37<01:32,  4.87it/s]

Processing tickers:  93%|█████████▎| 6325/6774 [21:37<01:35,  4.68it/s]

Processing tickers:  93%|█████████▎| 6326/6774 [21:37<01:35,  4.71it/s]

Processing tickers:  93%|█████████▎| 6327/6774 [21:38<01:35,  4.69it/s]

Processing tickers:  93%|█████████▎| 6328/6774 [21:38<01:33,  4.77it/s]

Processing tickers:  93%|█████████▎| 6329/6774 [21:38<01:31,  4.84it/s]

Processing tickers:  93%|█████████▎| 6330/6774 [21:38<01:30,  4.88it/s]

Processing tickers:  93%|█████████▎| 6331/6774 [21:38<01:30,  4.88it/s]

Processing tickers:  93%|█████████▎| 6332/6774 [21:39<01:30,  4.86it/s]

Processing tickers:  93%|█████████▎| 6333/6774 [21:39<01:31,  4.80it/s]

Processing tickers:  94%|█████████▎| 6334/6774 [21:39<01:31,  4.81it/s]

Processing tickers:  94%|█████████▎| 6335/6774 [21:39<01:30,  4.87it/s]

Processing tickers:  94%|█████████▎| 6336/6774 [21:39<01:29,  4.91it/s]

Processing tickers:  94%|█████████▎| 6337/6774 [21:40<01:28,  4.92it/s]

Processing tickers:  94%|█████████▎| 6338/6774 [21:40<01:29,  4.88it/s]

Processing tickers:  94%|█████████▎| 6339/6774 [21:40<01:29,  4.83it/s]

Processing tickers:  94%|█████████▎| 6340/6774 [21:40<01:29,  4.84it/s]

Processing tickers:  94%|█████████▎| 6341/6774 [21:40<01:31,  4.75it/s]

Processing tickers:  94%|█████████▎| 6342/6774 [21:41<01:30,  4.79it/s]

Processing tickers:  94%|█████████▎| 6343/6774 [21:41<01:28,  4.87it/s]

Processing tickers:  94%|█████████▎| 6344/6774 [21:41<01:29,  4.80it/s]

Processing tickers:  94%|█████████▎| 6345/6774 [21:41<01:29,  4.77it/s]

Processing tickers:  94%|█████████▎| 6346/6774 [21:41<01:29,  4.79it/s]

Processing tickers:  94%|█████████▎| 6347/6774 [21:42<01:28,  4.84it/s]

Processing tickers:  94%|█████████▎| 6348/6774 [21:42<01:28,  4.80it/s]

Processing tickers:  94%|█████████▎| 6349/6774 [21:42<01:27,  4.83it/s]

Processing tickers:  94%|█████████▎| 6350/6774 [21:42<01:26,  4.91it/s]

Processing tickers:  94%|█████████▍| 6351/6774 [21:42<01:26,  4.90it/s]

Processing tickers:  94%|█████████▍| 6352/6774 [21:43<01:25,  4.92it/s]

Processing tickers:  94%|█████████▍| 6353/6774 [21:43<01:24,  4.97it/s]

Processing tickers:  94%|█████████▍| 6354/6774 [21:43<01:24,  4.98it/s]

Processing tickers:  94%|█████████▍| 6355/6774 [21:43<01:25,  4.90it/s]

Processing tickers:  94%|█████████▍| 6356/6774 [21:43<01:24,  4.93it/s]

Processing tickers:  94%|█████████▍| 6357/6774 [21:44<01:24,  4.93it/s]

Processing tickers:  94%|█████████▍| 6358/6774 [21:44<01:24,  4.93it/s]

Processing tickers:  94%|█████████▍| 6359/6774 [21:44<01:23,  4.97it/s]

Processing tickers:  94%|█████████▍| 6360/6774 [21:44<01:23,  4.99it/s]

Processing tickers:  94%|█████████▍| 6361/6774 [21:44<01:23,  4.97it/s]

Processing tickers:  94%|█████████▍| 6362/6774 [21:45<01:22,  5.01it/s]

Processing tickers:  94%|█████████▍| 6363/6774 [21:45<01:22,  4.98it/s]

Processing tickers:  94%|█████████▍| 6364/6774 [21:45<01:24,  4.87it/s]

Processing tickers:  94%|█████████▍| 6365/6774 [21:45<01:28,  4.64it/s]

Processing tickers:  94%|█████████▍| 6366/6774 [21:46<01:25,  4.76it/s]

Processing tickers:  94%|█████████▍| 6367/6774 [21:46<01:24,  4.84it/s]

Processing tickers:  94%|█████████▍| 6368/6774 [21:46<01:22,  4.93it/s]

Processing tickers:  94%|█████████▍| 6369/6774 [21:46<01:22,  4.94it/s]

Processing tickers:  94%|█████████▍| 6370/6774 [21:46<01:22,  4.89it/s]

Processing tickers:  94%|█████████▍| 6371/6774 [21:47<01:22,  4.90it/s]

Processing tickers:  94%|█████████▍| 6372/6774 [21:47<01:21,  4.92it/s]

Processing tickers:  94%|█████████▍| 6373/6774 [21:47<01:20,  4.97it/s]

Processing tickers:  94%|█████████▍| 6374/6774 [21:47<01:23,  4.81it/s]

Processing tickers:  94%|█████████▍| 6375/6774 [21:47<01:24,  4.74it/s]

Processing tickers:  94%|█████████▍| 6376/6774 [21:48<01:26,  4.60it/s]

Processing tickers:  94%|█████████▍| 6377/6774 [21:48<01:24,  4.71it/s]

Processing tickers:  94%|█████████▍| 6378/6774 [21:48<01:23,  4.75it/s]

Processing tickers:  94%|█████████▍| 6379/6774 [21:48<01:21,  4.84it/s]

Processing tickers:  94%|█████████▍| 6380/6774 [21:48<01:22,  4.80it/s]

Processing tickers:  94%|█████████▍| 6381/6774 [21:49<01:22,  4.75it/s]

Processing tickers:  94%|█████████▍| 6382/6774 [21:49<01:22,  4.78it/s]

Processing tickers:  94%|█████████▍| 6383/6774 [21:49<01:21,  4.82it/s]

Processing tickers:  94%|█████████▍| 6384/6774 [21:49<01:21,  4.80it/s]

Processing tickers:  94%|█████████▍| 6385/6774 [21:49<01:21,  4.76it/s]

Processing tickers:  94%|█████████▍| 6386/6774 [21:50<01:20,  4.84it/s]

Processing tickers:  94%|█████████▍| 6387/6774 [21:50<01:19,  4.88it/s]

Processing tickers:  94%|█████████▍| 6388/6774 [21:50<01:19,  4.85it/s]

Processing tickers:  94%|█████████▍| 6389/6774 [21:50<01:18,  4.92it/s]

Processing tickers:  94%|█████████▍| 6390/6774 [21:50<01:18,  4.92it/s]

Processing tickers:  94%|█████████▍| 6391/6774 [21:51<01:18,  4.91it/s]

Processing tickers:  94%|█████████▍| 6392/6774 [21:51<01:17,  4.90it/s]

Processing tickers:  94%|█████████▍| 6393/6774 [21:51<01:17,  4.89it/s]

Processing tickers:  94%|█████████▍| 6394/6774 [21:51<01:17,  4.89it/s]

Processing tickers:  94%|█████████▍| 6395/6774 [21:52<01:18,  4.84it/s]

Processing tickers:  94%|█████████▍| 6396/6774 [21:52<01:17,  4.89it/s]

Processing tickers:  94%|█████████▍| 6397/6774 [21:52<01:16,  4.92it/s]

Processing tickers:  94%|█████████▍| 6398/6774 [21:52<01:16,  4.93it/s]

Processing tickers:  94%|█████████▍| 6399/6774 [21:52<01:16,  4.91it/s]

Processing tickers:  94%|█████████▍| 6400/6774 [21:53<01:16,  4.92it/s]

Processing tickers:  94%|█████████▍| 6401/6774 [21:53<01:15,  4.94it/s]

Processing tickers:  95%|█████████▍| 6402/6774 [21:53<01:14,  4.97it/s]

Processing tickers:  95%|█████████▍| 6403/6774 [21:53<01:15,  4.93it/s]

Processing tickers:  95%|█████████▍| 6404/6774 [21:53<01:14,  4.96it/s]

Processing tickers:  95%|█████████▍| 6405/6774 [21:54<01:14,  4.94it/s]

Processing tickers:  95%|█████████▍| 6406/6774 [21:54<01:14,  4.92it/s]

Processing tickers:  95%|█████████▍| 6407/6774 [21:54<01:13,  4.98it/s]

Processing tickers:  95%|█████████▍| 6408/6774 [21:54<01:13,  4.95it/s]

Processing tickers:  95%|█████████▍| 6409/6774 [21:54<01:13,  4.96it/s]

Processing tickers:  95%|█████████▍| 6410/6774 [21:55<01:14,  4.88it/s]

Processing tickers:  95%|█████████▍| 6411/6774 [21:55<01:13,  4.92it/s]

Processing tickers:  95%|█████████▍| 6412/6774 [21:55<01:14,  4.87it/s]

Processing tickers:  95%|█████████▍| 6413/6774 [21:55<01:13,  4.90it/s]

Processing tickers:  95%|█████████▍| 6414/6774 [21:55<01:14,  4.84it/s]

Processing tickers:  95%|█████████▍| 6415/6774 [21:56<01:13,  4.87it/s]

Processing tickers:  95%|█████████▍| 6416/6774 [21:56<01:12,  4.91it/s]

Processing tickers:  95%|█████████▍| 6417/6774 [21:56<01:13,  4.85it/s]

Processing tickers:  95%|█████████▍| 6418/6774 [21:56<01:12,  4.89it/s]

Processing tickers:  95%|█████████▍| 6419/6774 [21:56<01:12,  4.87it/s]

Processing tickers:  95%|█████████▍| 6420/6774 [21:57<01:12,  4.91it/s]

Processing tickers:  95%|█████████▍| 6421/6774 [21:57<01:11,  4.96it/s]

Processing tickers:  95%|█████████▍| 6422/6774 [21:57<01:10,  4.96it/s]

Processing tickers:  95%|█████████▍| 6423/6774 [21:57<01:10,  4.97it/s]

Processing tickers:  95%|█████████▍| 6424/6774 [21:57<01:10,  4.93it/s]

Processing tickers:  95%|█████████▍| 6425/6774 [21:58<01:10,  4.94it/s]

Processing tickers:  95%|█████████▍| 6426/6774 [21:58<01:10,  4.92it/s]

Processing tickers:  95%|█████████▍| 6427/6774 [21:58<01:09,  4.96it/s]

Processing tickers:  95%|█████████▍| 6428/6774 [21:58<01:09,  4.96it/s]

Processing tickers:  95%|█████████▍| 6429/6774 [21:58<01:09,  4.97it/s]

Processing tickers:  95%|█████████▍| 6430/6774 [21:59<01:09,  4.98it/s]

Processing tickers:  95%|█████████▍| 6431/6774 [21:59<01:09,  4.97it/s]

Processing tickers:  95%|█████████▍| 6432/6774 [21:59<01:08,  4.97it/s]

Processing tickers:  95%|█████████▍| 6433/6774 [21:59<01:09,  4.92it/s]

Processing tickers:  95%|█████████▍| 6434/6774 [21:59<01:08,  4.94it/s]

Processing tickers:  95%|█████████▍| 6435/6774 [22:00<01:08,  4.96it/s]

Processing tickers:  95%|█████████▌| 6436/6774 [22:00<01:08,  4.97it/s]

Processing tickers:  95%|█████████▌| 6437/6774 [22:00<01:07,  4.96it/s]

Processing tickers:  95%|█████████▌| 6438/6774 [22:00<01:09,  4.86it/s]

Processing tickers:  95%|█████████▌| 6439/6774 [22:00<01:08,  4.89it/s]

Processing tickers:  95%|█████████▌| 6440/6774 [22:01<01:07,  4.92it/s]

Processing tickers:  95%|█████████▌| 6441/6774 [22:01<01:07,  4.94it/s]

Processing tickers:  95%|█████████▌| 6442/6774 [22:01<01:09,  4.79it/s]

Processing tickers:  95%|█████████▌| 6443/6774 [22:01<01:09,  4.78it/s]

Processing tickers:  95%|█████████▌| 6444/6774 [22:01<01:07,  4.87it/s]

Processing tickers:  95%|█████████▌| 6445/6774 [22:02<01:06,  4.92it/s]

Processing tickers:  95%|█████████▌| 6446/6774 [22:02<01:06,  4.94it/s]

Processing tickers:  95%|█████████▌| 6447/6774 [22:02<01:07,  4.84it/s]

Processing tickers:  95%|█████████▌| 6448/6774 [22:02<01:07,  4.86it/s]

Processing tickers:  95%|█████████▌| 6449/6774 [22:03<01:06,  4.87it/s]

Processing tickers:  95%|█████████▌| 6450/6774 [22:03<01:05,  4.93it/s]

Processing tickers:  95%|█████████▌| 6451/6774 [22:03<01:05,  4.91it/s]

Processing tickers:  95%|█████████▌| 6452/6774 [22:03<01:07,  4.79it/s]

Processing tickers:  95%|█████████▌| 6453/6774 [22:03<01:05,  4.87it/s]

Processing tickers:  95%|█████████▌| 6454/6774 [22:04<01:05,  4.89it/s]

Processing tickers:  95%|█████████▌| 6455/6774 [22:04<01:05,  4.85it/s]

Processing tickers:  95%|█████████▌| 6456/6774 [22:04<01:05,  4.85it/s]

Processing tickers:  95%|█████████▌| 6457/6774 [22:04<01:04,  4.90it/s]

Processing tickers:  95%|█████████▌| 6458/6774 [22:04<01:04,  4.91it/s]

Processing tickers:  95%|█████████▌| 6459/6774 [22:05<01:05,  4.84it/s]

Processing tickers:  95%|█████████▌| 6460/6774 [22:05<01:04,  4.87it/s]

Processing tickers:  95%|█████████▌| 6461/6774 [22:05<01:05,  4.80it/s]

Processing tickers:  95%|█████████▌| 6462/6774 [22:05<01:04,  4.85it/s]

Processing tickers:  95%|█████████▌| 6463/6774 [22:05<01:03,  4.87it/s]

Processing tickers:  95%|█████████▌| 6464/6774 [22:06<01:04,  4.82it/s]

Processing tickers:  95%|█████████▌| 6465/6774 [22:06<01:04,  4.80it/s]

Processing tickers:  95%|█████████▌| 6466/6774 [22:06<01:05,  4.74it/s]

Processing tickers:  95%|█████████▌| 6467/6774 [22:06<01:03,  4.80it/s]

Processing tickers:  95%|█████████▌| 6468/6774 [22:06<01:02,  4.86it/s]

Processing tickers:  95%|█████████▌| 6469/6774 [22:07<01:02,  4.89it/s]

Processing tickers:  96%|█████████▌| 6470/6774 [22:07<01:02,  4.84it/s]

Processing tickers:  96%|█████████▌| 6471/6774 [22:07<01:03,  4.80it/s]

Processing tickers:  96%|█████████▌| 6472/6774 [22:07<01:02,  4.86it/s]

Processing tickers:  96%|█████████▌| 6473/6774 [22:07<01:02,  4.85it/s]

Processing tickers:  96%|█████████▌| 6474/6774 [22:08<01:01,  4.85it/s]

Processing tickers:  96%|█████████▌| 6475/6774 [22:08<01:00,  4.90it/s]

Processing tickers:  96%|█████████▌| 6476/6774 [22:08<01:00,  4.89it/s]

Processing tickers:  96%|█████████▌| 6477/6774 [22:08<01:01,  4.86it/s]

Processing tickers:  96%|█████████▌| 6478/6774 [22:08<00:59,  4.93it/s]

Processing tickers:  96%|█████████▌| 6479/6774 [22:09<01:00,  4.87it/s]

Processing tickers:  96%|█████████▌| 6480/6774 [22:09<00:59,  4.95it/s]

Processing tickers:  96%|█████████▌| 6481/6774 [22:09<00:58,  4.97it/s]

Processing tickers:  96%|█████████▌| 6482/6774 [22:09<00:59,  4.94it/s]

Processing tickers:  96%|█████████▌| 6483/6774 [22:09<00:58,  4.95it/s]

Processing tickers:  96%|█████████▌| 6484/6774 [22:10<00:58,  4.99it/s]

Processing tickers:  96%|█████████▌| 6485/6774 [22:10<00:57,  4.99it/s]

Processing tickers:  96%|█████████▌| 6486/6774 [22:10<00:58,  4.95it/s]

Processing tickers:  96%|█████████▌| 6487/6774 [22:10<00:57,  4.97it/s]

Processing tickers:  96%|█████████▌| 6488/6774 [22:10<00:58,  4.89it/s]

Processing tickers:  96%|█████████▌| 6489/6774 [22:11<00:59,  4.78it/s]

Processing tickers:  96%|█████████▌| 6490/6774 [22:11<00:59,  4.80it/s]

Processing tickers:  96%|█████████▌| 6491/6774 [22:11<00:58,  4.84it/s]

Processing tickers:  96%|█████████▌| 6492/6774 [22:11<00:58,  4.79it/s]

Processing tickers:  96%|█████████▌| 6493/6774 [22:12<00:57,  4.88it/s]

Processing tickers:  96%|█████████▌| 6494/6774 [22:12<00:57,  4.86it/s]

Processing tickers:  96%|█████████▌| 6495/6774 [22:12<00:57,  4.86it/s]

Processing tickers:  96%|█████████▌| 6496/6774 [22:12<00:57,  4.83it/s]

Processing tickers:  96%|█████████▌| 6497/6774 [22:12<00:56,  4.88it/s]

Processing tickers:  96%|█████████▌| 6498/6774 [22:13<00:56,  4.90it/s]

Processing tickers:  96%|█████████▌| 6499/6774 [22:13<00:55,  4.94it/s]

Processing tickers:  96%|█████████▌| 6500/6774 [22:13<00:55,  4.94it/s]

Processing tickers:  96%|█████████▌| 6501/6774 [22:13<00:54,  4.97it/s]

Processing tickers:  96%|█████████▌| 6502/6774 [22:13<00:55,  4.90it/s]

Processing tickers:  96%|█████████▌| 6503/6774 [22:14<00:54,  4.94it/s]

Processing tickers:  96%|█████████▌| 6504/6774 [22:14<00:54,  4.95it/s]

Processing tickers:  96%|█████████▌| 6505/6774 [22:14<00:55,  4.87it/s]

Processing tickers:  96%|█████████▌| 6506/6774 [22:15<02:19,  1.93it/s]

Processing tickers:  96%|█████████▌| 6507/6774 [22:15<01:53,  2.36it/s]

Processing tickers:  96%|█████████▌| 6508/6774 [22:16<01:35,  2.80it/s]

Processing tickers:  96%|█████████▌| 6509/6774 [22:16<01:22,  3.22it/s]

Processing tickers:  96%|█████████▌| 6510/6774 [22:16<01:12,  3.62it/s]

Processing tickers:  96%|█████████▌| 6511/6774 [22:16<01:06,  3.93it/s]

Processing tickers:  96%|█████████▌| 6512/6774 [22:16<01:02,  4.21it/s]

Processing tickers:  96%|█████████▌| 6513/6774 [22:17<00:59,  4.40it/s]

Processing tickers:  96%|█████████▌| 6514/6774 [22:17<00:57,  4.56it/s]

Processing tickers:  96%|█████████▌| 6515/6774 [22:17<00:55,  4.66it/s]

Processing tickers:  96%|█████████▌| 6516/6774 [22:17<00:54,  4.76it/s]

Processing tickers:  96%|█████████▌| 6517/6774 [22:17<00:53,  4.81it/s]

Processing tickers:  96%|█████████▌| 6518/6774 [22:18<00:53,  4.81it/s]

Processing tickers:  96%|█████████▌| 6519/6774 [22:18<00:51,  4.91it/s]

Processing tickers:  96%|█████████▋| 6520/6774 [22:18<00:51,  4.93it/s]

Processing tickers:  96%|█████████▋| 6521/6774 [22:18<00:51,  4.90it/s]

Processing tickers:  96%|█████████▋| 6522/6774 [22:18<00:51,  4.88it/s]

Processing tickers:  96%|█████████▋| 6523/6774 [22:19<00:51,  4.90it/s]

Processing tickers:  96%|█████████▋| 6524/6774 [22:19<00:50,  4.95it/s]

Processing tickers:  96%|█████████▋| 6525/6774 [22:19<00:50,  4.97it/s]

Processing tickers:  96%|█████████▋| 6526/6774 [22:19<00:49,  4.97it/s]

Processing tickers:  96%|█████████▋| 6527/6774 [22:19<00:49,  4.99it/s]

Processing tickers:  96%|█████████▋| 6528/6774 [22:20<00:49,  5.01it/s]

Processing tickers:  96%|█████████▋| 6529/6774 [22:20<00:48,  5.02it/s]

Processing tickers:  96%|█████████▋| 6530/6774 [22:20<00:48,  5.02it/s]

Processing tickers:  96%|█████████▋| 6531/6774 [22:20<00:49,  4.91it/s]

Processing tickers:  96%|█████████▋| 6532/6774 [22:20<00:49,  4.93it/s]

Processing tickers:  96%|█████████▋| 6533/6774 [22:21<00:48,  4.94it/s]

Processing tickers:  96%|█████████▋| 6534/6774 [22:21<00:48,  4.91it/s]

Processing tickers:  96%|█████████▋| 6535/6774 [22:21<00:49,  4.84it/s]

Processing tickers:  96%|█████████▋| 6536/6774 [22:21<00:49,  4.82it/s]

Processing tickers:  97%|█████████▋| 6537/6774 [22:22<00:49,  4.78it/s]

Processing tickers:  97%|█████████▋| 6538/6774 [22:22<00:48,  4.84it/s]

Processing tickers:  97%|█████████▋| 6539/6774 [22:22<00:48,  4.85it/s]

Processing tickers:  97%|█████████▋| 6540/6774 [22:22<00:48,  4.78it/s]

Processing tickers:  97%|█████████▋| 6541/6774 [22:22<00:48,  4.83it/s]

Processing tickers:  97%|█████████▋| 6542/6774 [22:23<00:47,  4.88it/s]

Processing tickers:  97%|█████████▋| 6543/6774 [22:23<00:47,  4.91it/s]

Processing tickers:  97%|█████████▋| 6544/6774 [22:23<00:46,  4.92it/s]

Processing tickers:  97%|█████████▋| 6545/6774 [22:23<00:46,  4.94it/s]

Processing tickers:  97%|█████████▋| 6546/6774 [22:23<00:46,  4.92it/s]

Processing tickers:  97%|█████████▋| 6547/6774 [22:24<00:45,  4.94it/s]

Processing tickers:  97%|█████████▋| 6548/6774 [22:24<00:45,  4.93it/s]

Processing tickers:  97%|█████████▋| 6549/6774 [22:24<00:45,  4.96it/s]

Processing tickers:  97%|█████████▋| 6550/6774 [22:24<00:45,  4.94it/s]

Processing tickers:  97%|█████████▋| 6551/6774 [22:24<00:45,  4.90it/s]

Processing tickers:  97%|█████████▋| 6552/6774 [22:25<00:45,  4.87it/s]

Processing tickers:  97%|█████████▋| 6553/6774 [22:25<00:45,  4.89it/s]

Processing tickers:  97%|█████████▋| 6554/6774 [22:25<00:44,  4.91it/s]

Processing tickers:  97%|█████████▋| 6555/6774 [22:25<00:45,  4.79it/s]

Processing tickers:  97%|█████████▋| 6556/6774 [22:25<00:44,  4.87it/s]

Processing tickers:  97%|█████████▋| 6557/6774 [22:26<00:44,  4.93it/s]

Processing tickers:  97%|█████████▋| 6558/6774 [22:26<00:43,  4.96it/s]

Processing tickers:  97%|█████████▋| 6559/6774 [22:26<00:44,  4.88it/s]

Processing tickers:  97%|█████████▋| 6560/6774 [22:26<00:44,  4.83it/s]

Processing tickers:  97%|█████████▋| 6561/6774 [22:26<00:45,  4.72it/s]

Processing tickers:  97%|█████████▋| 6562/6774 [22:27<00:44,  4.75it/s]

Processing tickers:  97%|█████████▋| 6563/6774 [22:27<00:45,  4.68it/s]

Processing tickers:  97%|█████████▋| 6564/6774 [22:27<00:45,  4.58it/s]

Processing tickers:  97%|█████████▋| 6565/6774 [22:27<00:46,  4.52it/s]

Processing tickers:  97%|█████████▋| 6566/6774 [22:28<00:45,  4.62it/s]

Processing tickers:  97%|█████████▋| 6567/6774 [22:28<00:44,  4.61it/s]

Processing tickers:  97%|█████████▋| 6568/6774 [22:28<00:43,  4.71it/s]

Processing tickers:  97%|█████████▋| 6569/6774 [22:28<00:43,  4.74it/s]

Processing tickers:  97%|█████████▋| 6570/6774 [22:28<00:42,  4.82it/s]

Processing tickers:  97%|█████████▋| 6571/6774 [22:29<00:41,  4.89it/s]

Processing tickers:  97%|█████████▋| 6572/6774 [22:29<00:41,  4.92it/s]

Processing tickers:  97%|█████████▋| 6573/6774 [22:29<00:40,  4.96it/s]

Processing tickers:  97%|█████████▋| 6574/6774 [22:29<00:39,  5.00it/s]

Processing tickers:  97%|█████████▋| 6575/6774 [22:29<00:39,  5.01it/s]

Processing tickers:  97%|█████████▋| 6576/6774 [22:30<00:39,  5.02it/s]

Processing tickers:  97%|█████████▋| 6577/6774 [22:30<00:39,  5.01it/s]

Processing tickers:  97%|█████████▋| 6578/6774 [22:30<00:39,  4.99it/s]

Processing tickers:  97%|█████████▋| 6579/6774 [22:30<00:39,  5.00it/s]

Processing tickers:  97%|█████████▋| 6580/6774 [22:30<00:38,  4.99it/s]

Processing tickers:  97%|█████████▋| 6581/6774 [22:31<00:38,  5.01it/s]

Processing tickers:  97%|█████████▋| 6582/6774 [22:31<00:38,  4.99it/s]

Processing tickers:  97%|█████████▋| 6583/6774 [22:31<00:38,  5.00it/s]

Processing tickers:  97%|█████████▋| 6584/6774 [22:31<00:38,  4.98it/s]

Processing tickers:  97%|█████████▋| 6585/6774 [22:31<00:37,  4.98it/s]

Processing tickers:  97%|█████████▋| 6586/6774 [22:32<00:37,  5.00it/s]

Processing tickers:  97%|█████████▋| 6587/6774 [22:32<00:37,  5.00it/s]

Processing tickers:  97%|█████████▋| 6588/6774 [22:32<00:36,  5.04it/s]

Processing tickers:  97%|█████████▋| 6589/6774 [22:32<00:36,  5.00it/s]

Processing tickers:  97%|█████████▋| 6590/6774 [22:32<00:37,  4.97it/s]

Processing tickers:  97%|█████████▋| 6591/6774 [22:33<00:36,  4.97it/s]

Processing tickers:  97%|█████████▋| 6592/6774 [22:33<00:37,  4.80it/s]

Processing tickers:  97%|█████████▋| 6593/6774 [22:33<00:37,  4.78it/s]

Processing tickers:  97%|█████████▋| 6594/6774 [22:33<00:37,  4.83it/s]

Processing tickers:  97%|█████████▋| 6595/6774 [22:33<00:36,  4.87it/s]

Processing tickers:  97%|█████████▋| 6596/6774 [22:34<00:36,  4.84it/s]

Processing tickers:  97%|█████████▋| 6597/6774 [22:34<00:36,  4.89it/s]

Processing tickers:  97%|█████████▋| 6598/6774 [22:34<00:36,  4.83it/s]

Processing tickers:  97%|█████████▋| 6599/6774 [22:34<00:35,  4.87it/s]

Processing tickers:  97%|█████████▋| 6600/6774 [22:34<00:35,  4.90it/s]

Processing tickers:  97%|█████████▋| 6601/6774 [22:35<00:35,  4.91it/s]

Processing tickers:  97%|█████████▋| 6602/6774 [22:35<00:34,  4.94it/s]

Processing tickers:  97%|█████████▋| 6603/6774 [22:35<00:34,  4.97it/s]

Processing tickers:  97%|█████████▋| 6604/6774 [22:35<00:34,  4.97it/s]

Processing tickers:  98%|█████████▊| 6605/6774 [22:35<00:34,  4.95it/s]

Processing tickers:  98%|█████████▊| 6606/6774 [22:36<00:33,  5.01it/s]

Processing tickers:  98%|█████████▊| 6607/6774 [22:36<00:33,  5.01it/s]

Processing tickers:  98%|█████████▊| 6608/6774 [22:36<00:33,  5.01it/s]

Processing tickers:  98%|█████████▊| 6609/6774 [22:36<00:33,  4.97it/s]

Processing tickers:  98%|█████████▊| 6610/6774 [22:36<00:32,  4.99it/s]

Processing tickers:  98%|█████████▊| 6611/6774 [22:37<00:32,  4.98it/s]

Processing tickers:  98%|█████████▊| 6612/6774 [22:37<00:32,  5.00it/s]

Processing tickers:  98%|█████████▊| 6613/6774 [22:37<00:32,  4.97it/s]

Processing tickers:  98%|█████████▊| 6614/6774 [22:37<00:32,  4.95it/s]

Processing tickers:  98%|█████████▊| 6615/6774 [22:37<00:31,  5.00it/s]

Processing tickers:  98%|█████████▊| 6616/6774 [22:38<00:31,  4.99it/s]

Processing tickers:  98%|█████████▊| 6617/6774 [22:38<00:32,  4.89it/s]

Processing tickers:  98%|█████████▊| 6618/6774 [22:38<00:31,  4.96it/s]

Processing tickers:  98%|█████████▊| 6619/6774 [22:38<00:32,  4.79it/s]

Processing tickers:  98%|█████████▊| 6620/6774 [22:38<00:31,  4.87it/s]

Processing tickers:  98%|█████████▊| 6621/6774 [22:39<00:31,  4.90it/s]

Processing tickers:  98%|█████████▊| 6622/6774 [22:39<00:30,  4.91it/s]

Processing tickers:  98%|█████████▊| 6623/6774 [22:39<00:30,  4.94it/s]

Processing tickers:  98%|█████████▊| 6624/6774 [22:39<00:30,  4.96it/s]

Processing tickers:  98%|█████████▊| 6625/6774 [22:39<00:30,  4.95it/s]

Processing tickers:  98%|█████████▊| 6626/6774 [22:40<00:29,  4.98it/s]

Processing tickers:  98%|█████████▊| 6627/6774 [22:40<00:29,  5.00it/s]

Processing tickers:  98%|█████████▊| 6628/6774 [22:40<00:29,  4.90it/s]

Processing tickers:  98%|█████████▊| 6629/6774 [22:40<00:29,  4.95it/s]

Processing tickers:  98%|█████████▊| 6630/6774 [22:40<00:29,  4.83it/s]

Processing tickers:  98%|█████████▊| 6631/6774 [22:41<00:29,  4.84it/s]

Processing tickers:  98%|█████████▊| 6632/6774 [22:41<00:29,  4.79it/s]

Processing tickers:  98%|█████████▊| 6633/6774 [22:41<00:29,  4.86it/s]

Processing tickers:  98%|█████████▊| 6634/6774 [22:41<00:28,  4.88it/s]

Processing tickers:  98%|█████████▊| 6635/6774 [22:42<00:28,  4.92it/s]

Processing tickers:  98%|█████████▊| 6636/6774 [22:42<00:28,  4.79it/s]

Processing tickers:  98%|█████████▊| 6637/6774 [22:42<00:28,  4.77it/s]

Processing tickers:  98%|█████████▊| 6638/6774 [22:42<00:28,  4.71it/s]

Processing tickers:  98%|█████████▊| 6639/6774 [22:42<00:29,  4.65it/s]

Processing tickers:  98%|█████████▊| 6640/6774 [22:43<00:28,  4.74it/s]

Processing tickers:  98%|█████████▊| 6641/6774 [22:43<00:27,  4.75it/s]

Processing tickers:  98%|█████████▊| 6642/6774 [22:43<00:27,  4.75it/s]

Processing tickers:  98%|█████████▊| 6643/6774 [22:43<00:27,  4.75it/s]

Processing tickers:  98%|█████████▊| 6644/6774 [22:43<00:27,  4.80it/s]

Processing tickers:  98%|█████████▊| 6645/6774 [22:44<00:26,  4.84it/s]

Processing tickers:  98%|█████████▊| 6646/6774 [22:44<00:26,  4.80it/s]

Processing tickers:  98%|█████████▊| 6647/6774 [22:44<00:26,  4.86it/s]

Processing tickers:  98%|█████████▊| 6648/6774 [22:44<00:25,  4.86it/s]

Processing tickers:  98%|█████████▊| 6649/6774 [22:44<00:25,  4.94it/s]

Processing tickers:  98%|█████████▊| 6650/6774 [22:45<00:25,  4.80it/s]

Processing tickers:  98%|█████████▊| 6651/6774 [22:45<00:25,  4.87it/s]

Processing tickers:  98%|█████████▊| 6652/6774 [22:45<00:25,  4.86it/s]

Processing tickers:  98%|█████████▊| 6653/6774 [22:45<00:24,  4.89it/s]

Processing tickers:  98%|█████████▊| 6654/6774 [22:45<00:25,  4.74it/s]

Processing tickers:  98%|█████████▊| 6655/6774 [22:46<00:24,  4.78it/s]

Processing tickers:  98%|█████████▊| 6656/6774 [22:46<00:24,  4.85it/s]

Processing tickers:  98%|█████████▊| 6657/6774 [22:46<00:24,  4.78it/s]

Processing tickers:  98%|█████████▊| 6658/6774 [22:46<00:24,  4.82it/s]

Processing tickers:  98%|█████████▊| 6659/6774 [22:47<00:24,  4.79it/s]

Processing tickers:  98%|█████████▊| 6660/6774 [22:47<00:24,  4.74it/s]

Processing tickers:  98%|█████████▊| 6661/6774 [22:47<00:23,  4.80it/s]

Processing tickers:  98%|█████████▊| 6662/6774 [22:47<00:23,  4.73it/s]

Processing tickers:  98%|█████████▊| 6663/6774 [22:47<00:23,  4.68it/s]

Processing tickers:  98%|█████████▊| 6664/6774 [22:48<00:23,  4.78it/s]

Processing tickers:  98%|█████████▊| 6665/6774 [22:48<00:23,  4.67it/s]

Processing tickers:  98%|█████████▊| 6666/6774 [22:48<00:23,  4.62it/s]

Processing tickers:  98%|█████████▊| 6667/6774 [22:48<00:22,  4.72it/s]

Processing tickers:  98%|█████████▊| 6668/6774 [22:48<00:22,  4.76it/s]

Processing tickers:  98%|█████████▊| 6669/6774 [22:49<00:21,  4.80it/s]

Processing tickers:  98%|█████████▊| 6670/6774 [22:49<00:21,  4.80it/s]

Processing tickers:  98%|█████████▊| 6671/6774 [22:49<00:21,  4.70it/s]

Processing tickers:  98%|█████████▊| 6672/6774 [22:49<00:21,  4.65it/s]

Processing tickers:  99%|█████████▊| 6673/6774 [22:49<00:21,  4.76it/s]

Processing tickers:  99%|█████████▊| 6674/6774 [22:50<00:21,  4.71it/s]

Processing tickers:  99%|█████████▊| 6675/6774 [22:50<00:20,  4.79it/s]

Processing tickers:  99%|█████████▊| 6676/6774 [22:50<00:20,  4.77it/s]

Processing tickers:  99%|█████████▊| 6677/6774 [22:50<00:20,  4.84it/s]

Processing tickers:  99%|█████████▊| 6678/6774 [22:51<00:19,  4.90it/s]

Processing tickers:  99%|█████████▊| 6679/6774 [22:51<00:19,  4.87it/s]

Processing tickers:  99%|█████████▊| 6680/6774 [22:51<00:19,  4.90it/s]

Processing tickers:  99%|█████████▊| 6681/6774 [22:51<00:19,  4.78it/s]

Processing tickers:  99%|█████████▊| 6682/6774 [22:51<00:19,  4.82it/s]

Processing tickers:  99%|█████████▊| 6683/6774 [22:52<00:18,  4.88it/s]

Processing tickers:  99%|█████████▊| 6684/6774 [22:52<00:18,  4.91it/s]

Processing tickers:  99%|█████████▊| 6685/6774 [22:52<00:17,  4.96it/s]

Processing tickers:  99%|█████████▊| 6686/6774 [22:52<00:17,  4.99it/s]

Processing tickers:  99%|█████████▊| 6687/6774 [22:52<00:17,  4.98it/s]

Processing tickers:  99%|█████████▊| 6688/6774 [22:53<00:17,  4.93it/s]

Processing tickers:  99%|█████████▊| 6689/6774 [22:53<00:17,  4.93it/s]

Processing tickers:  99%|█████████▉| 6690/6774 [22:53<00:17,  4.79it/s]

Processing tickers:  99%|█████████▉| 6691/6774 [22:53<00:17,  4.83it/s]

Processing tickers:  99%|█████████▉| 6692/6774 [22:53<00:16,  4.90it/s]

Processing tickers:  99%|█████████▉| 6693/6774 [22:54<00:16,  4.93it/s]

Processing tickers:  99%|█████████▉| 6694/6774 [22:54<00:16,  4.89it/s]

Processing tickers:  99%|█████████▉| 6695/6774 [22:54<00:16,  4.80it/s]

Processing tickers:  99%|█████████▉| 6696/6774 [22:54<00:16,  4.84it/s]

Processing tickers:  99%|█████████▉| 6697/6774 [22:54<00:15,  4.90it/s]

Processing tickers:  99%|█████████▉| 6698/6774 [22:55<00:15,  4.95it/s]

Processing tickers:  99%|█████████▉| 6699/6774 [22:55<00:15,  4.84it/s]

Processing tickers:  99%|█████████▉| 6700/6774 [22:55<00:15,  4.89it/s]

Processing tickers:  99%|█████████▉| 6701/6774 [22:55<00:14,  4.90it/s]

Processing tickers:  99%|█████████▉| 6702/6774 [22:55<00:14,  4.95it/s]

Processing tickers:  99%|█████████▉| 6703/6774 [22:56<00:14,  4.97it/s]

Processing tickers:  99%|█████████▉| 6704/6774 [22:56<00:14,  4.95it/s]

Processing tickers:  99%|█████████▉| 6705/6774 [22:56<00:13,  4.95it/s]

Processing tickers:  99%|█████████▉| 6706/6774 [22:56<00:13,  4.91it/s]

Processing tickers:  99%|█████████▉| 6707/6774 [22:56<00:13,  4.86it/s]

Processing tickers:  99%|█████████▉| 6708/6774 [22:57<00:13,  4.93it/s]

Processing tickers:  99%|█████████▉| 6709/6774 [22:57<00:13,  4.87it/s]

Processing tickers:  99%|█████████▉| 6710/6774 [22:57<00:13,  4.79it/s]

Processing tickers:  99%|█████████▉| 6711/6774 [22:57<00:13,  4.84it/s]

Processing tickers:  99%|█████████▉| 6712/6774 [22:57<00:12,  4.92it/s]

Processing tickers:  99%|█████████▉| 6713/6774 [22:58<00:12,  4.94it/s]

Processing tickers:  99%|█████████▉| 6714/6774 [22:58<00:12,  4.93it/s]

Processing tickers:  99%|█████████▉| 6715/6774 [22:58<00:11,  4.95it/s]

Processing tickers:  99%|█████████▉| 6716/6774 [22:58<00:11,  4.89it/s]

Processing tickers:  99%|█████████▉| 6717/6774 [22:58<00:11,  4.94it/s]

Processing tickers:  99%|█████████▉| 6718/6774 [22:59<00:11,  4.95it/s]

Processing tickers:  99%|█████████▉| 6719/6774 [22:59<00:11,  4.95it/s]

Processing tickers:  99%|█████████▉| 6720/6774 [22:59<00:10,  4.98it/s]

Processing tickers:  99%|█████████▉| 6721/6774 [22:59<00:10,  4.98it/s]

Processing tickers:  99%|█████████▉| 6722/6774 [22:59<00:10,  4.99it/s]

Processing tickers:  99%|█████████▉| 6723/6774 [23:00<00:10,  5.02it/s]

Processing tickers:  99%|█████████▉| 6724/6774 [23:00<00:11,  4.51it/s]

Processing tickers:  99%|█████████▉| 6725/6774 [23:00<00:10,  4.64it/s]

Processing tickers:  99%|█████████▉| 6726/6774 [23:00<00:10,  4.71it/s]

Processing tickers:  99%|█████████▉| 6727/6774 [23:01<00:10,  4.69it/s]

Processing tickers:  99%|█████████▉| 6728/6774 [23:01<00:09,  4.80it/s]

Processing tickers:  99%|█████████▉| 6729/6774 [23:01<00:09,  4.74it/s]

Processing tickers:  99%|█████████▉| 6730/6774 [23:01<00:09,  4.81it/s]

Processing tickers:  99%|█████████▉| 6731/6774 [23:01<00:08,  4.86it/s]

Processing tickers:  99%|█████████▉| 6732/6774 [23:02<00:08,  4.90it/s]

Processing tickers:  99%|█████████▉| 6733/6774 [23:02<00:08,  4.93it/s]

Processing tickers:  99%|█████████▉| 6734/6774 [23:02<00:08,  4.93it/s]

Processing tickers:  99%|█████████▉| 6735/6774 [23:02<00:08,  4.84it/s]

Processing tickers:  99%|█████████▉| 6736/6774 [23:02<00:07,  4.83it/s]

Processing tickers:  99%|█████████▉| 6737/6774 [23:03<00:07,  4.89it/s]

Processing tickers:  99%|█████████▉| 6738/6774 [23:03<00:07,  4.75it/s]

Processing tickers:  99%|█████████▉| 6739/6774 [23:03<00:07,  4.79it/s]

Processing tickers:  99%|█████████▉| 6740/6774 [23:03<00:07,  4.85it/s]

Processing tickers: 100%|█████████▉| 6741/6774 [23:03<00:06,  4.90it/s]

Processing tickers: 100%|█████████▉| 6742/6774 [23:04<00:06,  4.95it/s]

Processing tickers: 100%|█████████▉| 6743/6774 [23:04<00:06,  4.95it/s]

Processing tickers: 100%|█████████▉| 6744/6774 [23:04<00:06,  4.95it/s]

Processing tickers: 100%|█████████▉| 6745/6774 [23:04<00:06,  4.81it/s]

Processing tickers: 100%|█████████▉| 6746/6774 [23:04<00:05,  4.82it/s]

Processing tickers: 100%|█████████▉| 6747/6774 [23:05<00:05,  4.87it/s]

Processing tickers: 100%|█████████▉| 6748/6774 [23:05<00:05,  4.91it/s]

Processing tickers: 100%|█████████▉| 6749/6774 [23:05<00:05,  4.83it/s]

Processing tickers: 100%|█████████▉| 6750/6774 [23:05<00:04,  4.88it/s]

Processing tickers: 100%|█████████▉| 6751/6774 [23:05<00:04,  4.85it/s]

Processing tickers: 100%|█████████▉| 6752/6774 [23:06<00:04,  4.90it/s]

Processing tickers: 100%|█████████▉| 6753/6774 [23:06<00:04,  4.93it/s]

Processing tickers: 100%|█████████▉| 6754/6774 [23:06<00:04,  4.89it/s]

Processing tickers: 100%|█████████▉| 6755/6774 [23:06<00:03,  4.90it/s]

Processing tickers: 100%|█████████▉| 6756/6774 [23:06<00:03,  4.89it/s]

Processing tickers: 100%|█████████▉| 6757/6774 [23:07<00:03,  4.82it/s]

Processing tickers: 100%|█████████▉| 6758/6774 [23:07<00:03,  4.91it/s]

Processing tickers: 100%|█████████▉| 6759/6774 [23:07<00:03,  4.95it/s]

Processing tickers: 100%|█████████▉| 6760/6774 [23:07<00:02,  4.96it/s]

Processing tickers: 100%|█████████▉| 6761/6774 [23:08<00:02,  4.98it/s]

Processing tickers: 100%|█████████▉| 6762/6774 [23:08<00:02,  5.00it/s]

Processing tickers: 100%|█████████▉| 6763/6774 [23:08<00:02,  4.99it/s]

Processing tickers: 100%|█████████▉| 6764/6774 [23:08<00:02,  4.88it/s]

Processing tickers: 100%|█████████▉| 6765/6774 [23:08<00:01,  4.91it/s]

Processing tickers: 100%|█████████▉| 6766/6774 [23:09<00:01,  4.93it/s]

Processing tickers: 100%|█████████▉| 6767/6774 [23:09<00:01,  4.94it/s]

Processing tickers: 100%|█████████▉| 6768/6774 [23:09<00:01,  4.94it/s]

Processing tickers: 100%|█████████▉| 6769/6774 [23:09<00:01,  4.82it/s]

Processing tickers: 100%|█████████▉| 6770/6774 [23:09<00:00,  4.88it/s]

Processing tickers: 100%|█████████▉| 6771/6774 [23:10<00:00,  4.92it/s]

Processing tickers: 100%|█████████▉| 6772/6774 [23:10<00:00,  4.96it/s]

Processing tickers: 100%|█████████▉| 6773/6774 [23:10<00:00,  5.01it/s]

Processing tickers: 100%|██████████| 6774/6774 [23:10<00:00,  5.01it/s]

Processing tickers: 100%|██████████| 6774/6774 [23:10<00:00,  4.87it/s]

         date ticker   gap
0  2025-11-25      A -1.84
1  2025-11-26      A -0.93
2  2025-11-28      A -0.17
3  2025-12-01      A -0.63
4  2025-12-02      A  0.57
Загалом рядків: 408921

In [46]:
std_by_ticker = (
    df_gaps_all.groupby("ticker")["gap"]
    .std()                 # std по групі (ddof=1)
    .round(2)              # округлення до 2 знаків
    .reset_index(name="sigma")
)

In [47]:
std_by_ticker

     ticker  sigma
0         A   0.61
1        AA   1.93
2      AAAU   1.67
3      AACG   3.76
4       AAL   0.99
...     ...    ...
6769    ZWS   0.79
6770   ZYBT   3.51
6771   ZYME   1.14
6772   ZYXI  11.35
6773  ZYXIQ  13.18

[6774 rows x 2 columns]

In [48]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    # знайдемо колонки гнучко
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"]  = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker зі скріна
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%" або "pct_vs_prev_close"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet та зберігає новий файл.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    # вихідний шлях
    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    # підготовка мапи sigma
    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)

    # запис у тимчасовий файл → атомарна заміна
    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}")
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(sigma_map, on="ticker", how="left", validate="m:1")

        # розташувати 'sigma' за бажанням
        if insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("sigma")
            idx = cols.index(insert_before)
            cols = cols[:idx] + ["sigma"] + cols[idx:]
            merged = merged[cols]
        else:
            base_cols = [c for c in merged.columns if c != "sigma"]
            merged = merged[base_cols + ["sigma"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # атомарна заміна
    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [49]:
# std_by_ticker має колонки: ['ticker','sigma']
add_sigma_by_ticker_to_parquet(
    base_path=str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    sigma_df=std_by_ticker,  # <- твій DF зі скріна
    # або sigma_path="CRACEN/std_by_ticker.parquet"/".csv"
    insert_before=None,      # або "Bench%" / "pct_vs_prev_close" — куди вставити
)

▶️ START merge sigma → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000  elapsed=20.5s

[batch   10] rows=20,000,000  elapsed=40.0s

[batch   15] rows=30,000,000  elapsed=60.4s

[batch   20] rows=40,000,000  elapsed=80.7s

[batch   25] rows=50,000,000  elapsed=100.6s

[batch   30] rows=60,000,000  elapsed=120.9s

[batch   35] rows=70,000,000  elapsed=140.8s

[batch   40] rows=80,000,000  elapsed=161.4s

[batch   45] rows=90,000,000  elapsed=181.9s

[batch   50] rows=100,000,000  elapsed=201.7s

[batch   55] rows=109,394,488  elapsed=220.9s
✅ DONE rows=109,394,488 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  in 221.0s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct_with_sigma.parquet'

In [50]:
peek_parquet("CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet", n=21150)

Файл: CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 109,394,488
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 0/21150
NaN у 'corr' (у прев'ю): 0/21150
NaN у 'beta' (у прев'ю): 0/21150

Перші рядки:

      ticker                  dt           o           h           l           c          v        date    open  prev_close  Stack% bench  corr  beta  Bench%  sigma
0          A 2025-11-25 00:02:00  151.860001  151.860001  151.860001  151.860001       15.0  2025-11-25  150.78      153.52   -1.08   IWM  0.64  0.37    0.03   0.61
1          A 2025-11-25 00:47:00  150.160004  150.160004  150.160004  150.160004        1.0  2025-11-25  150.78      153.52   -2.19   IWM  0.64  0.37     NaN   0.61
2          A 2025-11-25 01:58:00  150.160004  150.160004  150.100006  150.100006       30.0  2025-11-25  150.78      153.52   -2.19   IWM  0.64  0.37     NaN   0.61
3          A 2025-11-25 02:00:00  150.100006  150.100006  150.100006  150.100006        9.0  2025-11-25  150.78      153.52   -2.23   IWM  0.64  0.37     NaN   0.61
4          A 2025-11-25 05:14:00  150.990005  150.990005  150.990005  150.990005      100.0  2025-11-25  150.78      153.52   -1.65   IWM  0.64  0.37   -0.08   0.61
5          A 2025-11-25 07:03:00  150.020004  150.020004  150.020004  150.020004      100.0  2025-11-25  150.78      153.52   -2.28   IWM  0.64  0.37    0.12   0.61
6          A 2025-11-25 07:37:00  150.020004  150.020004  150.020004  150.020004      100.0  2025-11-25  150.78      153.52   -2.28   IWM  0.64  0.37     NaN   0.61
7          A 2025-11-25 07:55:00  150.039993  150.039993  150.039993  150.039993      100.0  2025-11-25  150.78      153.52   -2.27   IWM  0.64  0.37    0.34   0.61
8          A 2025-11-25 08:00:00  150.539993  151.000000  150.000000  151.000000      832.0  2025-11-25  150.78      153.52   -1.94   IWM  0.64  0.37   -0.14   0.61
9          A 2025-11-25 08:18:00  150.539993  150.539993  150.539993  150.539993      150.0  2025-11-25  150.78      153.52   -1.94   IWM  0.64  0.37    0.56   0.61
10         A 2025-11-25 08:19:00  147.781693  147.781693  147.781693  147.781693      100.0  2025-11-25  150.78      153.52   -3.74   IWM  0.64  0.37    0.58   0.61
11         A 2025-11-25 08:27:00  149.073303  149.500000  149.065002  149.065002      600.0  2025-11-25  150.78      153.52   -2.90   IWM  0.64  0.37    0.49   0.61
12         A 2025-11-25 08:30:00  149.610001  149.610001  149.610001  149.610001     1000.0  2025-11-25  150.78      153.52   -2.55   IWM  0.64  0.37    0.52   0.61
13         A 2025-11-25 08:32:00  149.990005  149.990005  149.990005  149.990005      100.0  2025-11-25  150.78      153.52   -2.30   IWM  0.64  0.37    0.59   0.61
14         A 2025-11-25 08:48:00  149.990005  149.990005  149.990005  149.990005      100.0  2025-11-25  150.78      153.52   -2.30   IWM  0.64  0.37    0.31   0.61
15         A 2025-11-25 08:52:00  150.259995  150.259995  150.259995  150.259995      100.0  2025-11-25  150.78      153.52   -2.12   IWM  0.64  0.37    0.35   0.61
16         A 2025-11-25 08:53:00  150.500000  150.500000  150.500000  150.500000      238.0  2025-11-25  150.78      153.52   -1.97   IWM  0.64  0.37    0.31   0.61
17         A 2025-11-25 08:59:00  150.550003  150.550003  150.550003  150.550003      100.0  2025-11-25  150.78      153.52   -1.93   IWM  0.64  0.37    0.29   0.61
18         A 2025-11-25 09:00:00  150.500000  150.500000  150.500000  150.500000      174.0  2025-11-25  150.78      153.52   -1.97   IWM  0.64  0.37    0.32   0.61
19         A 2025-11-25 09:05:00  150.500000  150.500000  150.500000  150.500000      189.0  2025-11-25  150.78      153.52   -1.97   IWM  0.64  0.37    0.26   0.61
20         A 2025-11-25 09:20:00  151.000000  151.000000  150.770004  151.000000     1355.0  2025-11-25  150.78      153.52   -1.64   IWM  0.64  0.37    0.23   0.61
21         A 2025-11-25 09:28:00  151.389999  151.449997  151.389999  151.449997      577.0  2025-11-25  150.78      153.52   -1.39   IWM  0.64  0.37    0.25   0.61
22         A 2025-11-25 09:29:00  151.490005  152.199997  151.490005  152.199997     1199.0  2025-11-25  150.78      153.52   -1.32   IWM  0.64  0.37    0.23   0.61
23         A 2025-11-25 09:30:00  150.779999  150.895004  148.000107  149.794998    64932.0  2025-11-25  150.78      153.52   -1.78   IWM  0.64  0.37    0.35   0.61
24         A 2025-11-25 09:31:00  149.789993  151.369995  149.789993  150.690002     9379.0  2025-11-25  150.78      153.52   -2.43   IWM  0.64  0.37    0.40   0.61
25         A 2025-11-25 09:32:00  150.854996  154.279999  150.854996  153.770004    22249.0  2025-11-25  150.78      153.52   -1.74   IWM  0.64  0.37    0.64   0.61
26         A 2025-11-25 09:33:00  153.800003  154.279999  153.000000  153.475006    18767.0  2025-11-25  150.78      153.52    0.18   IWM  0.64  0.37    0.74   0.61
27         A 2025-11-25 09:34:00  153.690002  154.100006  152.481400  153.585007    16192.0  2025-11-25  150.78      153.52    0.11   IWM  0.64  0.37    0.71   0.61
28         A 2025-11-25 09:35:00  153.585007  154.220001  153.244995  154.179993     7687.0  2025-11-25  150.78      153.52    0.04   IWM  0.64  0.37    0.71   0.61
29         A 2025-11-25 09:36:00  154.029999  154.850006  153.710007  154.544998    10437.0  2025-11-25  150.78      153.52    0.33   IWM  0.64  0.37    0.74   0.61
30         A 2025-11-25 09:37:00  154.544998  155.983994  154.544998  155.983994    27961.0  2025-11-25  150.78      153.52    0.67   IWM  0.64  0.37    0.76   0.61
31         A 2025-11-25 09:38:00  155.990005  156.112503  155.341507  156.000000    18123.0  2025-11-25  150.78      153.52    1.61   IWM  0.64  0.37    0.74   0.61
32         A 2025-11-25 09:39:00  155.800003  156.779999  155.270004  155.337006     7237.0  2025-11-25  150.78      153.52    1.49   IWM  0.64  0.37    0.78   0.61
33         A 2025-11-25 09:40:00  155.395004  156.339996  155.250000  156.339996     4352.0  2025-11-25  150.78      153.52    1.22   IWM  0.64  0.37    0.66   0.61
34         A 2025-11-25 09:41:00  156.779999  157.479996  156.520004  156.520004    10842.0  2025-11-25  150.78      153.52    2.12   IWM  0.64  0.37    0.60   0.61
35         A 2025-11-25 09:42:00  156.699997  157.470001  156.429993  157.419998     5720.0  2025-11-25  150.78      153.52    2.07   IWM  0.64  0.37    0.67   0.61
36         A 2025-11-25 09:43:00  157.130005  157.134995  156.520004  156.699997     9849.0  2025-11-25  150.78      153.52    2.35   IWM  0.64  0.37    0.51   0.61
37         A 2025-11-25 09:44:00  157.009995  157.210007  156.710007  157.210007     4960.0  2025-11-25  150.78      153.52    2.27   IWM  0.64  0.37    0.40   0.61
38         A 2025-11-25 09:45:00  157.220001  157.440002  157.029999  157.210007     5011.0  2025-11-25  150.78      153.52    2.41   IWM  0.64  0.37    0.44   0.61
39         A 2025-11-25 09:46:00  157.240005  157.979996  157.240005  157.309998    18044.0  2025-11-25  150.78      153.52    2.42   IWM  0.64  0.37    0.35   0.61
40         A 2025-11-25 09:47:00  157.274994  157.274994  156.839996  156.929993     1923.0  2025-11-25  150.78      153.52    2.45   IWM  0.64  0.37    0.34   0.61
41         A 2025-11-25 09:48:00  157.050003  157.179993  156.535004  156.562500     9619.0  2025-11-25  150.78      153.52    2.30   IWM  0.64  0.37    0.22   0.61
42         A 2025-11-25 09:49:00  156.669998  156.669998  155.490005  156.024994    14645.0  2025-11-25  150.78      153.52    2.05   IWM  0.64  0.37    0.18   0.61
43         A 2025-11-25 09:50:00  156.289993  156.535004  156.179993  156.475006     4070.0  2025-11-25  150.78      153.52    1.80   IWM  0.64  0.37    0.12   0.61
44         A 2025-11-25 09:51:00  156.244995  156.250000  155.960007  156.000000     5378.0  2025-11-25  150.78      153.52    1.78   IWM  0.64  0.37    0.30   0.61
45         A 2025-11-25 09:52:00  156.000000  156.250000  155.380005  155.690002     9412.0  2025-11-25  150.78      153.52    1.62   IWM  0.64  0.37    0.50   0.61
46         A 2025-11-25 09:53:00  155.714996  156.490005  155.714996  156.324997     5519.0  2025-11-25  150.78      153.52    1.43   IWM  0.64  0.37    0.63   0.61
47         A 2025-11-25 09:54:00  156.490005  156.550003  156.410004  156.410004     3604.0  2025-11-25  150.78      153.52    1.93   IWM  0.64  0.37    0.63   0.61
48         A 2025-11-25 09:55:00  156.410004  156.410004  155.729996  156.270004    16064.0  2025-11-25  150.78      153.52    1.88   IWM  0.64  0.37    0.64   0.61
49         A 2025-11-25 09:56:00  156.264999  156.710007  156.089996  156.529999     5957.0  2025-11-25  150.78      153.52    1.79   IWM  0.64  0.37    0.73   0.61
50         A 2025-11-25 09:57:00  156.752502  156.752502  156.279999  156.479996     2133.0  2025-11-25  150.78      153.52    2.11   IWM  0.64  0.37    0.76   0.61
51         A 2025-11-25 09:58:00  156.490005  156.800003  156.490005  156.755005     1017.0  2025-11-25  150.78      153.52    1.93   IWM  0.64  0.37    0.79   0.61
52         A 2025-11-25 09:59:00  156.755005  156.755005  156.510101  156.755005     2997.0  2025-11-25  150.78      153.52    2.11   IWM  0.64  0.37    0.94   0.61
53         A 2025-11-25 10:00:00  156.509995  156.910004  156.345001  156.384995     8703.0  2025-11-25  150.78      153.52    1.95   IWM  0.64  0.37    1.05   0.61
54         A 2025-11-25 10:01:00  156.389999  156.690002  156.300003  156.330002    18760.0  2025-11-25  150.78      153.52    1.87   IWM  0.64  0.37    1.18   0.61
55         A 2025-11-25 10:02:00  156.449997  156.490005  155.990005  156.172501    25227.0  2025-11-25  150.78      153.52    1.91   IWM  0.64  0.37    1.16   0.61
56         A 2025-11-25 10:03:00  156.145004  156.710007  156.145004  156.527100     3386.0  2025-11-25  150.78      153.52    1.71   IWM  0.64  0.37    0.99   0.61
57         A 2025-11-25 10:04:00  156.585007  156.608002  156.289993  156.365005     2745.0  2025-11-25  150.78      153.52    2.00   IWM  0.64  0.37    0.84   0.61
58         A 2025-11-25 10:05:00  156.419998  156.570007  156.110001  156.110001     4079.0  2025-11-25  150.78      153.52    1.89   IWM  0.64  0.37    0.82   0.61
59         A 2025-11-25 10:06:00  156.110001  156.279999  155.990005  156.279999     4340.0  2025-11-25  150.78      153.52    1.69   IWM  0.64  0.37    0.93   0.61
60         A 2025-11-25 10:07:00  156.309998  156.600006  156.309998  156.544998     6826.0  2025-11-25  150.78      153.52    1.82   IWM  0.64  0.37    0.95   0.61
61         A 2025-11-25 10:08:00  156.550003  156.833405  156.550003  156.634995     2346.0  2025-11-25  150.78      153.52    1.97   IWM  0.64  0.37    1.02   0.61
62         A 2025-11-25 10:09:00  156.634995  156.639999  156.289993  156.309998    10767.0  2025-11-25  150.78      153.52    2.03   IWM  0.64  0.37    1.07   0.61
63         A 2025-11-25 10:10:00  156.304993  156.479996  156.293198  156.419998     4162.0  2025-11-25  150.78      153.52    1.81   IWM  0.64  0.37    1.06   0.61
64         A 2025-11-25 10:11:00  156.399994  156.559998  156.130005  156.149994     9856.0  2025-11-25  150.78      153.52    1.88   IWM  0.64  0.37    1.10   0.61
65         A 2025-11-25 10:12:00  156.149994  156.149994  155.945007  156.119995     5961.0  2025-11-25  150.78      153.52    1.71   IWM  0.64  0.37    0.93   0.61
66         A 2025-11-25 10:13:00  156.255005  156.255005  156.130005  156.255005     3129.0  2025-11-25  150.78      153.52    1.78   IWM  0.64  0.37    1.03   0.61
67         A 2025-11-25 10:14:00  156.255005  156.255005  155.679993  155.940002     5651.0  2025-11-25  150.78      153.52    1.78   IWM  0.64  0.37    1.01   0.61
68         A 2025-11-25 10:15:00  155.940002  156.210007  155.899994  156.059998     9795.0  2025-11-25  150.78      153.52    1.58   IWM  0.64  0.37    0.83   0.61
69         A 2025-11-25 10:16:00  156.059998  156.169998  155.800003  156.020004     4735.0  2025-11-25  150.78      153.52    1.65   IWM  0.64  0.37    0.82   0.61
70         A 2025-11-25 10:17:00  156.059998  156.130005  155.910004  155.910004     1483.0  2025-11-25  150.78      153.52    1.65   IWM  0.64  0.37    0.85   0.61
71         A 2025-11-25 10:18:00  156.100006  156.100006  155.919998  155.979996     1500.0  2025-11-25  150.78      153.52    1.68   IWM  0.64  0.37    0.83   0.61
72         A 2025-11-25 10:19:00  155.860001  156.059998  155.860001  155.910004     1786.0  2025-11-25  150.78      153.52    1.52   IWM  0.64  0.37    0.92   0.61
73         A 2025-11-25 10:20:00  155.550003  155.929993  155.531097  155.839996     2018.0  2025-11-25  150.78      153.52    1.32   IWM  0.64  0.37    0.85   0.61
74         A 2025-11-25 10:21:00  155.809998  155.929993  155.809998  155.929993      500.0  2025-11-25  150.78      153.52    1.49   IWM  0.64  0.37    0.76   0.61
75         A 2025-11-25 10:22:00  155.970001  156.070099  155.960007  155.985001     1924.0  2025-11-25  150.78      153.52    1.60   IWM  0.64  0.37    0.78   0.61
76         A 2025-11-25 10:23:00  155.940002  156.059998  155.759995  156.050003     4335.0  2025-11-25  150.78      153.52    1.58   IWM  0.64  0.37    0.75   0.61
77         A 2025-11-25 10:24:00  156.024994  156.645004  156.024994  156.639999     7089.0  2025-11-25  150.78      153.52    1.63   IWM  0.64  0.37    0.75   0.61
78         A 2025-11-25 10:25:00  156.479996  157.000000  156.479996  156.809998     3464.0  2025-11-25  150.78      153.52    1.93   IWM  0.64  0.37    0.78   0.61
79         A 2025-11-25 10:26:00  156.820007  157.070007  156.820007  157.050003     6463.0  2025-11-25  150.78      153.52    2.15   IWM  0.64  0.37    0.92   0.61
80         A 2025-11-25 10:27:00  157.000000  157.190002  156.869995  157.029999     9073.0  2025-11-25  150.78      153.52    2.27   IWM  0.64  0.37    0.96   0.61
81         A 2025-11-25 10:28:00  157.164993  157.500000  157.089996  157.259995     3077.0  2025-11-25  150.78      153.52    2.37   IWM  0.64  0.37    0.91   0.61
82         A 2025-11-25 10:29:00  157.070007  157.070007  156.809998  157.035004     1100.0  2025-11-25  150.78      153.52    2.31   IWM  0.64  0.37    0.98   0.61
83         A 2025-11-25 10:30:00  157.089996  157.376007  156.839996  157.376007     2929.0  2025-11-25  150.78      153.52    2.33   IWM  0.64  0.37    1.05   0.61
84         A 2025-11-25 10:31:00  157.320007  157.500000  157.309998  157.339996     5668.0  2025-11-25  150.78      153.52    2.48   IWM  0.64  0.37    1.16   0.61
85         A 2025-11-25 10:32:00  157.419998  157.683197  157.419998  157.675003     8061.0  2025-11-25  150.78      153.52    2.54   IWM  0.64  0.37    1.20   0.61
86         A 2025-11-25 10:33:00  157.675003  157.675003  157.429993  157.669998     3282.0  2025-11-25  150.78      153.52    2.71   IWM  0.64  0.37    1.22   0.61
87         A 2025-11-25 10:34:00  157.610001  157.860001  157.479996  157.860001      884.0  2025-11-25  150.78      153.52    2.66   IWM  0.64  0.37    1.24   0.61
88         A 2025-11-25 10:35:00  157.744995  157.830002  157.623795  157.744995     3425.0  2025-11-25  150.78      153.52    2.75   IWM  0.64  0.37    1.25   0.61
89         A 2025-11-25 10:36:00  157.789993  157.990005  157.789993  157.845001     4302.0  2025-11-25  150.78      153.52    2.78   IWM  0.64  0.37    1.18   0.61
90         A 2025-11-25 10:37:00  157.860001  157.860001  157.690002  157.785004     2700.0  2025-11-25  150.78      153.52    2.83   IWM  0.64  0.37    1.35   0.61
91         A 2025-11-25 10:38:00  157.679993  157.929993  157.669998  157.929993     2906.0  2025-11-25  150.78      153.52    2.71   IWM  0.64  0.37    1.38   0.61
92         A 2025-11-25 10:39:00  157.884995  157.884995  157.789993  157.789993     1010.0  2025-11-25  150.78      153.52    2.84   IWM  0.64  0.37    1.37   0.61
93         A 2025-11-25 10:40:00  157.789993  158.110001  157.710007  157.945007     7464.0  2025-11-25  150.78      153.52    2.78   IWM  0.64  0.37    1.35   0.61
94         A 2025-11-25 10:41:00  158.100006  158.250000  158.100006  158.195007     2317.0  2025-11-25  150.78      153.52    2.98   IWM  0.64  0.37    1.37   0.61
95         A 2025-11-25 10:42:00  158.179993  158.189896  157.979996  158.125000     2594.0  2025-11-25  150.78      153.52    3.04   IWM  0.64  0.37    1.36   0.61
96         A 2025-11-25 10:43:00  158.145004  158.270004  158.145004  158.270004     1711.0  2025-11-25  150.78      153.52    3.01   IWM  0.64  0.37    1.40   0.61
97         A 2025-11-25 10:44:00  158.270004  158.520004  158.270004  158.300003     2489.0  2025-11-25  150.78      153.52    3.09   IWM  0.64  0.37    1.45   0.61
98         A 2025-11-25 10:45:00  158.380005  158.570007  158.320007  158.339996     3474.0  2025-11-25  150.78      153.52    3.17   IWM  0.64  0.37    1.53   0.61
99         A 2025-11-25 10:46:00  158.289993  158.440002  158.289993  158.404999      800.0  2025-11-25  150.78      153.52    3.11   IWM  0.64  0.37    1.61   0.61
100        A 2025-11-25 10:47:00  158.320007  158.630005  158.210007  158.210007     1500.0  2025-11-25  150.78      153.52    3.13   IWM  0.64  0.37    1.60   0.61
101        A 2025-11-25 10:48:00  158.169998  158.289993  157.949997  158.175003     4132.0  2025-11-25  150.78      153.52    3.03   IWM  0.64  0.37    1.57   0.61
102        A 2025-11-25 10:49:00  158.175003  158.339996  158.149994  158.169998     2083.0  2025-11-25  150.78      153.52    3.03   IWM  0.64  0.37    1.52   0.61
103        A 2025-11-25 10:50:00  158.429993  158.429993  157.889999  158.009995    16834.0  2025-11-25  150.78      153.52    3.20   IWM  0.64  0.37    1.44   0.61
104        A 2025-11-25 10:51:00  158.009995  158.039993  157.889999  157.895004     1882.0  2025-11-25  150.78      153.52    2.92   IWM  0.64  0.37    1.34   0.61
105        A 2025-11-25 10:52:00  157.884995  158.179993  157.660004  158.179993     5087.0  2025-11-25  150.78      153.52    2.84   IWM  0.64  0.37    1.29   0.61
106        A 2025-11-25 10:53:00  158.300003  158.479904  158.190002  158.190002     3262.0  2025-11-25  150.78      153.52    3.11   IWM  0.64  0.37    1.34   0.61
107        A 2025-11-25 10:54:00  158.214996  158.259995  158.205002  158.205002      350.0  2025-11-25  150.78      153.52    3.06   IWM  0.64  0.37    1.30   0.61
108        A 2025-11-25 10:55:00  158.199997  158.199997  158.123199  158.199997     1162.0  2025-11-25  150.78      153.52    3.05   IWM  0.64  0.37    1.24   0.61
109        A 2025-11-25 10:56:00  158.199997  158.339996  158.029999  158.339996     1650.0  2025-11-25  150.78      153.52    3.05   IWM  0.64  0.37    1.19   0.61
110        A 2025-11-25 10:57:00  158.195007  158.339996  158.195007  158.195007     1113.0  2025-11-25  150.78      153.52    3.05   IWM  0.64  0.37    1.23   0.61
111        A 2025-11-25 10:58:00  158.195007  158.490005  158.195007  158.380005     4325.0  2025-11-25  150.78      153.52    3.05   IWM  0.64  0.37    1.37   0.61
112        A 2025-11-25 10:59:00  158.320007  158.440002  158.309998  158.440002     2594.0  2025-11-25  150.78      153.52    3.13   IWM  0.64  0.37    1.36   0.61
113        A 2025-11-25 11:00:00  158.440002  158.589996  158.320007  158.384995     4967.0  2025-11-25  150.78      153.52    3.20   IWM  0.64  0.37    1.36   0.61
114        A 2025-11-25 11:01:00  158.384995  158.789993  158.315002  158.789993     3316.0  2025-11-25  150.78      153.52    3.17   IWM  0.64  0.37    1.37   0.61
115        A 2025-11-25 11:02:00  158.600006  158.705002  158.600006  158.649994      422.0  2025-11-25  150.78      153.52    3.31   IWM  0.64  0.37    1.35   0.61
116        A 2025-11-25 11:03:00  158.630005  158.919998  158.630005  158.889999     3420.0  2025-11-25  150.78      153.52    3.33   IWM  0.64  0.37    1.30   0.61
117        A 2025-11-25 11:04:00  158.770004  158.809998  158.470093  158.809998    10368.0  2025-11-25  150.78      153.52    3.42   IWM  0.64  0.37    1.28   0.61
118        A 2025-11-25 11:05:00  158.809998  158.830002  158.720001  158.770004     1713.0  2025-11-25  150.78      153.52    3.45   IWM  0.64  0.37    1.33   0.61
119        A 2025-11-25 11:06:00  158.830002  159.000000  158.830002  158.949997     5745.0  2025-11-25  150.78      153.52    3.46   IWM  0.64  0.37    1.23   0.61

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,A,2025-11-25 00:02:00,151.860001,151.860001,151.860001,151.860001,15.0,2025-11-25,150.78,153.52,-1.08,IWM,0.64,0.37,0.03,0.61
1,A,2025-11-25 00:47:00,150.160004,150.160004,150.160004,150.160004,1.0,2025-11-25,150.78,153.52,-2.19,IWM,0.64,0.37,NaN,0.61
2,A,2025-11-25 01:58:00,150.160004,150.160004,150.100006,150.100006,30.0,2025-11-25,150.78,153.52,-2.19,IWM,0.64,0.37,NaN,0.61
3,A,2025-11-25 02:00:00,150.100006,150.100006,150.100006,150.100006,9.0,2025-11-25,150.78,153.52,-2.23,IWM,0.64,0.37,NaN,0.61
4,A,2025-11-25 05:14:00,150.990005,150.990005,150.990005,150.990005,100.0,2025-11-25,150.78,153.52,-1.65,IWM,0.64,0.37,-0.08,0.61
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,AA,2025-12-11 14:36:00,47.320000,47.330002,47.310001,47.320000,2268.0,2025-12-11,44.50,44.64,6.00,GDX,0.78,0.58,4.52,1.93
21146,AA,2025-12-11 14:37:00,47.310001,47.320000,47.299999,47.314999,3658.0,2025-12-11,44.50,44.64,5.98,GDX,0.78,0.58,4.52,1.93
21147,AA,2025-12-11 14:38:00,47.314999,47.320000,47.310001,47.310001,3410.0,2025-12-11,44.50,44.64,5.99,GDX,0.78,0.58,4.46,1.93
21148,AA,2025-12-11 14:39:00,47.310001,47.310001,47.259998,47.259998,6006.0,2025-12-11,44.50,44.64,5.98,GDX,0.78,0.58,4.48,1.93
21149,AA,2025-12-11 14:40:00,47.250000,47.264999,47.240002,47.264999,5295.0,2025-12-11,44.50,44.64,5.85,GDX,0.78,0.58,4.46,1.93

In [51]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
except Exception:
    pa = pq = ds = None


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    roundtrip_pandas: bool = True,   # найнадійніше для sort_values
    log_every: int = 200,
):
    """
    Rewrites input parquet into output parquet in strict physical order:
      ticker A→Z, then (date, dt) within each ticker (or dt only).
    Uses dataset scanning per ticker to avoid global in-memory sort.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")

    # Discover columns
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    has_date = ("date" in schema_names)
    has_dt   = ("dt" in schema_names)

    # get unique tickers (safe, but could be heavy; acceptable for your use-case)
    tickers_tbl = dataset.to_table(columns=["ticker"])
    tickers = sorted(pd.unique(tickers_tbl.column("ticker").to_pandas().astype(str)))
    del tickers_tbl
    gc.collect()

    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    writer = None
    total_written = 0
    t0 = time.time()

    print(f"▶ SORT: {input_path} → {output_path} | tickers={len(tickers):,} | has_date={has_date} has_dt={has_dt}")

    try:
        for i, tk in enumerate(tickers, 1):
            # Filter rows for this ticker
            filt = (ds.field("ticker") == tk)
            table = dataset.to_table(filter=filt)
            if table.num_rows == 0:
                continue

            if roundtrip_pandas:
                df = table.to_pandas()
                # Ensure date exists if needed
                if has_date:
                    # keep as-is; assume date is string 'YYYY-MM-DD'
                    pass
                elif has_dt and ("date" not in df.columns):
                    # If no date column exists, optionally derive it (not required for sort)
                    pass

                if has_date and has_dt and {"date", "dt"}.issubset(df.columns):
                    df.sort_values(["date", "dt"], kind="mergesort", inplace=True)
                elif has_dt and "dt" in df.columns:
                    df.sort_values(["dt"], kind="mergesort", inplace=True)
                else:
                    # fallback: stable sort by all columns
                    df.sort_values(list(df.columns), kind="mergesort", inplace=True)

                out_table = pa.Table.from_pandas(df, preserve_index=False)
                del df
            else:
                # Arrow-only fallback (less flexible)
                out_table = table

            if writer is None:
                writer = pq.ParquetWriter(tmp_out, out_table.schema, compression=compression)

            writer.write_table(out_table)
            total_written += out_table.num_rows

            if (i % log_every) == 0:
                print(f"  [{i:>6}/{len(tickers):,}] {tk}  written={total_written:,}  elapsed={time.time()-t0:,.1f}s")

            del table, out_table
            gc.collect()

    finally:
        if writer is not None:
            writer.close()

    # atomic replace
    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)

    print(f"✅ SORT DONE: {total_written:,} rows → {output_path} | time={time.time()-t0:,.1f}s")
    return output_path


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # використовується як batch_rows для Parquet
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,      # NEW: rewrite final sorted
) -> str:
    """
    Parquet-версія.
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.
    Працює потоково.

    NEW:
      - якщо sort_final_by_ticker=True, то фінальний output_path буде фізично
        відсортований: ticker A→Z, всередині тикера date,dt (або dt).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    batch_rows = chunksize

    # 1) write unsorted tmp parquet
    tmp_unsorted = output_path + f".tmp_unsorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_unsorted):
        os.remove(tmp_unsorted)

    pf = pq.ParquetFile(input_path)
    writer = None
    total = 0

    print(f"▶ START (Parquet): {input_path}  →  {output_path} | batch_rows≈{batch_rows:,}")

    for bi, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # гнучке визначення колонок
        names = {c.lower().strip(): c for c in df.columns}
        stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
        bench_col = names.get("bench%")
        beta_col  = names.get("beta")
        sigma_col = names.get("sigma")

        need = {
            "stack%/pct_vs_prev_close": stack_col,
            "bench%": bench_col,
            "beta": beta_col,
            "sigma": sigma_col,
        }
        missing = [k for k, v in need.items() if v is None]
        if missing:
            raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

        # приберемо старі результати, якщо були
        for col in ("t_p", "deviation", "dev_sig"):
            if col in df.columns:
                del df[col]

        # числові типи
        df[stack_col] = pd.to_numeric(df[stack_col], errors="coerce")
        df[bench_col] = pd.to_numeric(df[bench_col], errors="coerce")
        df[beta_col]  = pd.to_numeric(df[beta_col],  errors="coerce")
        df[sigma_col] = pd.to_numeric(df[sigma_col], errors="coerce")

        # обчислення
        tp  = df[stack_col] * df[beta_col]
        dev = tp - df[bench_col]
        denom = df[sigma_col].replace({0: np.nan})
        dsg = dev / denom

        # округлення
        if round_tp_dev is not None:
            tp  = tp.round(round_tp_dev)
            dev = dev.round(round_tp_dev)
        if round_devsig is not None:
            dsg = dsg.round(round_devsig)

        # додати в кінець
        df["t_p"] = tp
        df["deviation"] = dev
        df["dev_sig"] = dsg

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_unsorted, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if bi % 5 == 0:
            print(f"[batch {bi:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # 2) sort & finalize
    if sort_final_by_ticker:
        # rewrite sorted to output_path
        _write_final_sorted_alphabetical(
            tmp_unsorted,
            output_path,
            compression=compression,
            roundtrip_pandas=True,
            log_every=200,
        )
        # cleanup unsorted tmp
        try:
            os.remove(tmp_unsorted)
        except Exception:
            pass
    else:
        # atomic replace unsorted as final
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_unsorted, output_path)

    print(f"✅ DONE: {total:,} rows → {output_path} | total_time={time.time()-t0:,.1f}s")
    return output_path

In [52]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (Parquet): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\final.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=14.1s

[batch   10] rows=20,000,000  elapsed=29.0s

[batch   15] rows=30,000,000  elapsed=43.7s

[batch   20] rows=40,000,000  elapsed=58.5s

[batch   25] rows=50,000,000  elapsed=73.3s

[batch   30] rows=60,000,000  elapsed=87.7s

[batch   35] rows=70,000,000  elapsed=102.9s

[batch   40] rows=80,000,000  elapsed=117.2s

[batch   45] rows=90,000,000  elapsed=131.5s

[batch   50] rows=100,000,000  elapsed=146.3s

[batch   55] rows=109,394,488  elapsed=160.0s

▶ SORT: C:\datum-api-examples-main\OriON\CRACEN\final.parquet.tmp_unsorted_12800_1772132833 → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | tickers=6,892 | has_date=True has_dt=True

  [   200/6,892] AIS  written=3,266,843  elapsed=37.3s

  [   400/6,892] AQMS  written=6,551,160  elapsed=74.7s

  [   600/6,892] AXIA/P  written=9,882,140  elapsed=112.5s

  [   800/6,892] BITU  written=12,909,082  elapsed=149.4s

  [  1000/6,892] BTOG  written=15,956,225  elapsed=186.9s

  [  1200/6,892] CGCB  written=19,112,055  elapsed=224.9s

  [  1400/6,892] CON  written=21,989,655  elapsed=262.0s

  [  1600/6,892] CX  written=25,382,909  elapsed=299.5s

  [  1800/6,892] DRKY  written=28,422,529  elapsed=337.1s

  [  2000/6,892] ENVB  written=31,236,611  elapsed=374.2s

  [  2200/6,892] FBP  written=34,553,121  elapsed=411.5s

  [  2400/6,892] FSV  written=37,580,292  elapsed=448.9s

  [  2600/6,892] GNLN  written=40,699,922  elapsed=485.9s

  [  2800/6,892] HITI  written=43,757,645  elapsed=523.7s

  [  3000/6,892] IDYA  written=46,794,805  elapsed=561.1s

  [  3200/6,892] ISPR  written=49,844,309  elapsed=598.9s

  [  3400/6,892] KE  written=52,966,657  elapsed=635.5s

  [  3600/6,892] LIEN  written=56,043,938  elapsed=671.9s

  [  3800/6,892] MCO  written=58,926,465  elapsed=706.7s

  [  4000/6,892] MSBI  written=61,809,594  elapsed=743.0s

  [  4200/6,892] NIHI  written=65,092,413  elapsed=777.6s

  [  4400/6,892] OCGN  written=68,419,387  elapsed=815.2s

  [  4600/6,892] PBP  written=71,954,038  elapsed=850.9s

  [  4800/6,892] PRDO  written=75,183,387  elapsed=886.3s

  [  5000/6,892] RC  written=78,418,405  elapsed=922.0s

  [  5200/6,892] RVYL  written=81,723,862  elapsed=958.6s

  [  5400/6,892] SHLD  written=85,061,771  elapsed=993.3s

  [  5600/6,892] SORA  written=88,453,587  elapsed=1,029.4s

  [  5800/6,892] SWK  written=91,962,644  elapsed=1,064.6s

  [  6000/6,892] TONX  written=95,168,039  elapsed=1,100.8s

  [  6200/6,892] UHG  written=98,598,981  elapsed=1,136.6s

  [  6400/6,892] VLTO  written=102,099,652  elapsed=1,173.4s

  [  6600/6,892] WKSP  written=105,265,930  elapsed=1,208.5s

  [  6800/6,892] YCBD  written=108,135,084  elapsed=1,239.0s

✅ SORT DONE: 109,394,488 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | time=1,251.0s

✅ DONE: 109,394,488 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=1,424.6s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'

In [53]:
import pyarrow.dataset as ds

path = str(FINAL_PATH)

ticker = "AAPL"

dataset = ds.dataset(path, format="parquet")

table = dataset.to_table(
    filter=(ds.field("ticker") == ticker)
)

df = table.to_pandas()

# якщо є date + dt — відсортуємо, щоб це були саме "перші" по часу
if {"date", "dt"}.issubset(df.columns):
    df = df.sort_values(["date", "dt"])

display(df)

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma,t_p,deviation,dev_sig
0,AAPL,2025-11-25 00:00:00,274.769989,274.779999,274.769989,274.779999,12.0,2025-11-25,275.27,275.80,-0.37,SPY,0.73,0.45,0.01,0.52,-0.17,-0.18,-0.339423
1,AAPL,2025-11-25 00:01:00,274.779999,274.779999,274.700012,274.779999,17.0,2025-11-25,275.27,275.80,-0.37,SPY,0.73,0.45,0.02,0.52,-0.17,-0.19,-0.358654
2,AAPL,2025-11-25 00:02:00,274.799988,274.809998,274.799988,274.809998,94.0,2025-11-25,275.27,275.80,-0.36,SPY,0.73,0.45,0.02,0.52,-0.16,-0.18,-0.350000
3,AAPL,2025-11-25 00:03:00,274.809998,274.850006,274.809998,274.850006,287.0,2025-11-25,275.27,275.80,-0.36,SPY,0.73,0.45,0.02,0.52,-0.16,-0.18,-0.350000
4,AAPL,2025-11-25 00:04:00,274.850006,274.850006,274.730011,274.730011,18.0,2025-11-25,275.27,275.80,-0.34,SPY,0.73,0.45,0.03,0.52,-0.15,-0.18,-0.351923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70841,AAPL,2026-02-25 23:52:00,273.679993,273.690002,273.679993,273.690002,4.0,2026-02-25,271.73,272.17,0.55,SPY,0.73,0.45,NaN,0.52,0.25,NaN,NaN
70842,AAPL,2026-02-25 23:53:00,273.690002,273.690002,273.690002,273.690002,51.0,2026-02-25,271.73,272.17,0.56,SPY,0.73,0.45,0.70,0.52,0.25,-0.45,-0.861538
70843,AAPL,2026-02-25 23:55:00,273.700012,273.700012,273.670013,273.670013,47.0,2026-02-25,271.73,272.17,0.56,SPY,0.73,0.45,0.70,0.52,0.25,-0.45,-0.861538
70844,AAPL,2026-02-25 23:56:00,273.690002,273.690002,273.679993,273.679993,9.0,2026-02-25,271.73,272.17,0.56,SPY,0.73,0.45,0.70,0.52,0.25,-0.45,-0.861538
70845,AAPL,2026-02-25 23:59:00,273.720001,273.720001,273.720001,273.720001,1.0,2026-02-25,271.73,272.17,0.57,SPY,0.73,0.45,0.69,0.52,0.26,-0.43,-0.833654