In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2026-03-06 00:00:00
end   = 2026-06-06 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2026-03-06
end_date_str   = 2026-06-06

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker       value
0      A    50931.11
1     AA  1733512.34
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 13080

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,market_cap',
    'active': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
tickers_df = tickers_df.dropna()

# --- крок 3: додаємо потрібні колонки у df_filtered
TICKERS = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(TICKERS):,} рядків")
TICKERS.head()

Після фільтрації залишилось: 7,211 рядків

  ticker       value                         lvl3  market_cap
0      A    50931.11  Medical Equipment & Devices     38252.0
1     AA  1733512.34              Metals & Mining     18971.0
2   AAAU   393575.35                          NaN         NaN
3   AACG       21.99                     Software        46.0
4   AACP        9.95             Asset Management       234.0

In [7]:
TICKERS[TICKERS["ticker"] == "JD"]

     ticker       value                      lvl3  market_cap
3442     JD  2525151.79  E-Commerce Discretionary     35036.0

In [8]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [9]:
unique_lvl2 = get_unique_lvl2(TICKERS)
unique_lvl2

🔹 Знайдено 59 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Elec & Gas Marketing & Trading',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [10]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "SPY", "IBIT"],
    "Banking": ["KRE", "XLF", "SPY", "IBIT"],
    "Institutional Financial Svcs": ["XLF", "SPY", "IBIT"],
    "Insurance": ["XLF", "SPY", "IBIT"],
    "Specialty Finance": ["XLF", "SPY", "IBIT"],

    # --- Tech / Internet / Growth ---
    "Software": ["IGV", "QQQ", "IWM", "SPY"],  
    "IT Services": ["IGV", "QQQ", "IWM", "SPY"],
    "Semiconductors": ["SMH", "SOXX", "QQQ", "IWM", "SPY"],  
    "Technology Hardware": ["XLK", "QQQ", "SOXX", "IWM", "SPY"],
    "Internet Media & Services": ["QQQ", "KWEB", "IWM", "SPY"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "IWM", "SPY"],
    "Cable & Satellite": ["QQQ", "KWEB", "IWM", "SPY"],
    "Telecommunications": ["QQQ", "KWEB", "IWM", "SPY"],
    "Publishing & Broadcasting": ["QQQ", "KWEB", "IWM", "SPY"],
    "Entertainment Content": ["QQQ", "KWEB", "IWM", "SPY"],
    "Advertising & Marketing": ["QQQ", "KWEB", "IWM", "SPY"],

    # --- Industrials ---
    "Aerospace & Defense": ["ITA", "XLI", "IWM", "SPY"], 
    "Diversified Industrials": ["XLI", "SPY", "IWM"],
    "Industrial Intermediate Prod": ["XLI", "IWM", "SPY"],
    "Industrial Support Services": ["XLI", "IWM", "SPY"],
    "Engineering & Construction": ["XLI", "IWM", "SPY"],
    "Machinery": ["XLI", "IWM", "SPY"],
    "Transportation & Logistics": ["XTN", "XLI", "IWM", "SPY"],  
    "Transportation Equipment": ["XLI", "IWM", "SPY"],
    "Commercial Support Services": ["XLI", "IWM", "SPY"],
    "Containers & Packaging": ["XLI", "IWM", "SPY"],
    "Electrical Equipment": ["XLI", "QQQ", "IWM", "SPY"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["OIH", "XLE", "IWM", "SPY"],  
    "Oil & Gas Supply Chain": ["XLE", "IWM", "SPY"],
    "Elec & Gas Marketing & Trading": ["XLU", "XLE", "IWM", "SPY"],
    "Electric Utilities": ["XLU", "XLE", "IWM", "SPY"],         
    "Gas & Water Utilities": ["XLU", "IWM", "SPY"],
    "Renewable Energy": ["ICLN", "XLE", "IWM", "SPY"],           
    "Chemicals": ["XLB", "XLE", "IWM", "SPY"],                  
    "Metals & Mining": ["GDX", "XLB", "IWM", "SPY"],
    "Steel": ["SLX", "GDX", "XLB", "IWM", "SPY"],             
    "Construction Materials": ["XLB", "IWM", "SPY"],
    "Forestry, Paper & Wood Products": ["XLB", "IWM", "SPY"],

    # --- Health Care ---
    "Biotech & Pharma": ["IBB", "XBI", "QQQ", "IWM", "SPY"], 
    "Medical Equipment & Devices": ["IHI", "XLV", "IWM", "SPY"], 
    "Health Care Facilities & Svcs": ["IHF", "XLV", "IWM", "SPY"], 

    # --- Consumer Staples / Discretionary ---
    "Food": ["XLP", "SPY", "IWM"],
    "Beverages": ["XLP", "SPY", "IWM"],
    "Household Products": ["XLP", "SPY", "IWM"],
    "Tobacco & Cannabis": ["XLP", "SPY", "IWM"],
    "Retail - Consumer Staples": ["XLP", "SPY", "IWM"],
    "Wholesale - Consumer Staples": ["XLP", "SPY", "IWM"],

    "Retail - Discretionary": ["XRT", "XLY", "SPY", "IWM"], 
    "Wholesale - Discretionary": ["XLY", "SPY", "IWM"],
    "Consumer Services": ["XLY", "SPY", "IWM"],
    "Leisure Facilities & Services": ["XLY", "SPY", "IWM"],
    "Leisure Products": ["XLY", "SPY", "IWM"],
    "Apparel & Textile Products": ["XLY", "SPY", "IWM", "QQQ"],
    "Automotive": ["XLY", "SPY", "IWM", "QQQ"],
    "Home & Office Products": ["XLY", "SPY", "IWM"],
    "Home Construction": ["XHB", "IWM", "SPY"],          

    # --- Real Estate ---
    "REIT": ["VNQ", "IWM", "SPY"], 
    "Real Estate Owners & Developers": ["VNQ", "IWM", "SPY"],
    "Real Estate Services": ["VNQ", "IWM", "SPY"],
}

In [11]:
# ------------------------------------------------

In [12]:
import numpy as np
import pandas as pd


def calc_corr_beta_from_joined_gaps(df_pair: pd.DataFrame, x_col: str = "gap_x", y_col: str = "gap_y"):
    """
    Local corr/beta calculation without /calculations/corr_beta API.

    corr = Pearson(x, y)
    beta = cov(x, y) / var(y)
    """
    d = df_pair[[x_col, y_col]].copy()
    d[x_col] = pd.to_numeric(d[x_col], errors="coerce")
    d[y_col] = pd.to_numeric(d[y_col], errors="coerce")
    d = d.dropna()

    n = len(d)
    if n < 2:
        return np.nan, np.nan, n

    var_y = float(d[y_col].var(ddof=1))
    corr = float(d[x_col].corr(d[y_col]))

    if np.isnan(var_y) or var_y == 0:
        return corr, np.nan, n

    cov_xy = float(d[[x_col, y_col]].cov(ddof=1).iloc[0, 1])
    beta = cov_xy / var_y
    return corr, beta, n


def corr_beta_best_match_from_gaps(
    stock_gap_df: pd.DataFrame,
    etf_gap_df: pd.DataFrame,
    x_tickers,
    y_tickers,
    *,
    min_overlap: int = 20,
    output_path: str = None,
):
    """
    Pick best Y per X using local gaps.

    stock_gap_df: ['ticker','date','gap']
    etf_gap_df:   ['ticker','date','gap']
    """
    sx = stock_gap_df.copy()
    sy = etf_gap_df.copy()

    for df in (sx, sy):
        if not {"ticker", "date", "gap"}.issubset(df.columns):
            raise KeyError("Expected columns ['ticker','date','gap'] in gap data")
        df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.strftime("%Y-%m-%d")
        df["gap"] = pd.to_numeric(df["gap"], errors="coerce")

    s_map = {t: g[["date", "gap"]].copy() for t, g in sx.groupby("ticker")}
    e_map = {t: g[["date", "gap"]].copy() for t, g in sy.groupby("ticker")}

    rows_all = []
    rows_best = []

    for x in [str(v).upper() for v in x_tickers]:
        g_x = s_map.get(x)
        if g_x is None or g_x.empty:
            continue

        best = None
        for y in [str(v).upper() for v in y_tickers]:
            g_y = e_map.get(y)
            if g_y is None or g_y.empty:
                continue

            m = g_x.merge(g_y, on="date", how="inner", suffixes=("_x", "_y")).dropna()
            corr, beta, n = calc_corr_beta_from_joined_gaps(m, x_col="gap_x", y_col="gap_y")
            if n < int(min_overlap) or pd.isna(corr):
                continue

            row = {
                "x_ticker": x,
                "y_ticker": y,
                "corr": corr,
                "beta": beta,
                "n_overlap": n,
            }
            rows_all.append(row)
            if best is None or row["corr"] > best["corr"]:
                best = row

        if best is not None:
            rows_best.append({
                "x_ticker": best["x_ticker"],
                "best_y_ticker": best["y_ticker"],
                "best_corr": best["corr"],
                "beta_with_best": best["beta"],
                "n_overlap": best["n_overlap"],
            })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "n_overlap"])

    if output_path:
        df_pairs.to_csv(output_path, index=False)

    return df_all, df_pairs

In [13]:
def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
    start_date=None,
    end_date=None,
    last_n_reports=20,
    cap_q=0.95,
    min_hist_for_cap=20,
    min_overlap=20,
):
    import numpy as np
    import pandas as pd
    from concurrent.futures import ThreadPoolExecutor

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]
    if start_date is None:
        start_date = globals().get("start_date_str")
    if end_date is None:
        end_date = globals().get("end_date_str")
    if not start_date or not end_date:
        raise ValueError("Provide start_date/end_date or define start_date_str/end_date_str")
    if sector_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{sector_col}' column")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{ticker_col}' column")

    s_date, e_date = str(start_date)[:10], str(end_date)[:10]

    def _pick_col(df, candidates):
        cols_l = {c.lower().strip(): c for c in df.columns}
        return next((cols_l[c.lower()] for c in candidates if c.lower() in cols_l), None)

    def _fetch_gap(t):
        try:
            dfg = DatumApi.data_request("/daily/gaps", {
                "ticker": t, "start_date": s_date, "end_date": e_date, "format": "json_records",
            })
            if dfg is None or dfg.empty:
                return None
            dcol = _pick_col(dfg, ["date", "move_date", "dt", "datetime", "day"])
            if dcol is None or "gap" not in dfg.columns:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(dfg[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
                "gap": pd.to_numeric(dfg["gap"], errors="coerce"),
            }).dropna()
            return out if not out.empty else None
        except Exception as ex:
            print(f"WARN gaps fail {t}: {ex}")
            return None

    def _fetch_report(t):
        try:
            rep = DatumApi.data_request("/reports", {
                "ticker": t, "start_move_date": s_date, "end_move_date": e_date,
            })
            if rep is None or rep.empty:
                return None
            dcol = _pick_col(rep, ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"])
            if dcol is None:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(rep[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
            }).dropna().sort_values("date").tail(int(last_n_reports))
            return out if not out.empty else None
        except Exception as ex:
            print(f"WARN reports fail {t}: {ex}")
            return None

    # ── prepare ──────────────────────────────────────────────────────────────
    df_clean = tickers_df[[ticker_col, sector_col]].drop_duplicates().copy()
    df_clean[ticker_col] = df_clean[ticker_col].astype(str).str.strip().str.upper()
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)

    stocks = sorted(df_clean[ticker_col].dropna().unique())
    etf_candidates = set(fallback_etfs)
    for sec in df_clean[sector_col].unique():
        etf_candidates.update(sector_to_etf.get(sec, fallback_etfs) or fallback_etfs)
    etf_candidates = sorted(str(x).upper() for x in etf_candidates)

    print(f"START gaps: stocks={len(stocks)} etfs={len(etf_candidates)} window={s_date}..{e_date}")

    # ── parallel fetch: all gaps + reports in one pool ────────────────────────
    all_gap_tickers = sorted(set(stocks) | set(etf_candidates))
    with ThreadPoolExecutor(max_workers=min(64, len(all_gap_tickers) + len(stocks))) as ex:
        gap_futs  = {t: ex.submit(_fetch_gap,    t) for t in all_gap_tickers}
        rep_futs  = {t: ex.submit(_fetch_report, t) for t in stocks}

    gap_res = {t: f.result() for t, f in gap_futs.items()}
    rep_res = {t: f.result() for t, f in rep_futs.items()}

    def _concat(parts, cols):
        valid = [p for p in parts if p is not None]
        return pd.concat(valid, ignore_index=True) if valid else pd.DataFrame(columns=cols)

    stock_gaps = _concat([gap_res.get(t) for t in stocks],         ["ticker", "date", "gap"])
    etf_gaps   = _concat([gap_res.get(t) for t in etf_candidates], ["ticker", "date", "gap"])
    reports    = _concat([rep_res.get(t) for t in stocks],          ["ticker", "date"]).drop_duplicates()

    # ── exclude report days ──────────────────────────────────────────────────
    if not reports.empty and not stock_gaps.empty:
        m = stock_gaps.merge(reports.assign(_rep=1), on=["ticker", "date"], how="left")
        stock_gaps = m[m["_rep"].isna()][["ticker", "date", "gap"]].copy()

    # ── drop anomalies (vectorised) ──────────────────────────────────────────
    if not stock_gaps.empty:
        stock_gaps["gap"] = pd.to_numeric(stock_gaps["gap"], errors="coerce")
        abs_gap = stock_gaps["gap"].abs()
        cnts = stock_gaps.groupby("ticker")["gap"].transform("count")
        eligible = cnts >= min_hist_for_cap
        if eligible.any():
            caps = (stock_gaps[eligible]
                    .groupby("ticker")["gap"]
                    .agg(lambda x: np.quantile(x.abs(), cap_q)))
            cap_mapped = stock_gaps["ticker"].map(caps)
            stock_gaps = stock_gaps[(~eligible) | (abs_gap <= cap_mapped)].reset_index(drop=True)

    # ── build ETF numpy matrix: rows=dates, cols=etfs ───────────────────────
    if not etf_gaps.empty:
        etf_pivot = etf_gaps.pivot_table(index="date", columns="ticker", values="gap", aggfunc="first")
        date_to_row = {d: i for i, d in enumerate(etf_pivot.index)}
        etf_to_col  = {c: i for i, c in enumerate(etf_pivot.columns)}
        etf_arr     = etf_pivot.to_numpy(dtype=float)
    else:
        date_to_row = {}; etf_to_col = {}; etf_arr = np.empty((0, 0))

    stock_map = (
        {t: g.set_index("date")["gap"] for t, g in stock_gaps.groupby("ticker")}
        if not stock_gaps.empty else {}
    )

    # ── corr/beta loop ───────────────────────────────────────────────────────
    rows_all = []
    rows_best = []
    sectors_with_fallback = []

    for sec in sorted(df_clean[sector_col].unique()):
        etfs_raw = sector_to_etf.get(sec)
        if not etfs_raw:
            etfs_raw = list(fallback_etfs)
            sectors_with_fallback.append(sec)
        etfs = [str(e).upper() for e in etfs_raw]
        etfs_ok  = [e for e in etfs if e in etf_to_col]
        col_idxs = [etf_to_col[e] for e in etfs_ok]
        if not col_idxs:
            continue

        for st in sorted(df_clean.loc[df_clean[sector_col] == sec, ticker_col].unique()):
            sx = stock_map.get(st)
            if sx is None or sx.empty:
                continue

            st_dates = [d for d in sx.index if d in date_to_row]
            if not st_dates:
                continue

            row_idxs = [date_to_row[d] for d in st_dates]
            x_vals   = sx[st_dates].to_numpy(dtype=float)
            y_mat    = etf_arr[np.ix_(row_idxs, col_idxs)]   # (n_dates, n_etfs)
            valid_x  = ~np.isnan(x_vals)

            best_corr = -np.inf
            best_etf  = None
            best_beta = np.nan
            best_n    = 0

            for j, etf in enumerate(etfs_ok):
                mask = valid_x & ~np.isnan(y_mat[:, j])
                n = int(mask.sum())
                if n < min_overlap:
                    continue

                xv = x_vals[mask];  yv = y_mat[mask, j]
                xc = xv - xv.mean(); yc = yv - yv.mean()
                var_y = float((yc * yc).sum() / (n - 1))
                if var_y == 0 or np.isnan(var_y):
                    continue
                cov_xy = float((xc * yc).sum() / (n - 1))
                std_x  = float(np.sqrt((xc * xc).sum() / (n - 1)))
                if std_x == 0:
                    continue
                corr = cov_xy / (std_x * np.sqrt(var_y))
                beta = cov_xy / var_y

                rows_all.append({"x_ticker": st, "y_ticker": etf, "corr": corr, "beta": beta, "lvl3": sec, "n_overlap": n})

                if corr > best_corr:
                    best_corr, best_etf, best_beta, best_n = corr, etf, beta, n

            if best_etf is not None:
                rows_best.append({"x_ticker": st, "best_y_ticker": best_etf, "best_corr": best_corr,
                                  "beta_with_best": best_beta, "lvl3": sec, "n_overlap": best_n})

    # ── output ───────────────────────────────────────────────────────────────
    df_all   = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best) if rows_best else pd.DataFrame(
        columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "lvl3", "n_overlap"])

    df_pairs.to_csv(output_path, index=False)
    df_bench = df_pairs.rename(columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"})[["ticker", "benchmark"]]
    df_bench.to_csv(bench_path, index=False)

    print(f"DONE pairs: {len(df_pairs)} -> {output_path}")
    print(f"DONE bench map: {len(df_bench)} -> {bench_path}")
    if sectors_with_fallback:
        print("Fallback ETF used for sectors:", ", ".join(map(str, sectors_with_fallback[:20])))

    return df_all, df_pairs

In [14]:
# Local corr/beta: stock gaps vs ETF gaps, excluding report days and stock outliers
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=TICKERS,
    sector_to_etf=sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path=str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path=str(WORK_DIR / "ticker_bench_.csv"),
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    cap_q=0.95,
    min_hist_for_cap=20,
    min_overlap=20,
)

# Prepare parquet for downstream merge (cell 31)
corr_beta_pairs = df_pairs.rename(columns={
    "best_y_ticker": "y_ticker",
    "best_corr": "corr",
    "beta_with_best": "beta",
})[["x_ticker", "y_ticker", "corr", "beta"]].copy()

corr_beta_pairs.to_parquet(str(WORK_DIR / "corr_beta_pairs.parquet"), index=False)

print(df_all.head())
print("Rows in raw stock-etf pairs:", len(df_all))
print(df_pairs.head())
print("Saved:", str(WORK_DIR / "corr_beta_pairs.parquet"))

START gaps: stocks=7211 etfs=31 window=2026-03-06..2026-06-06

DONE pairs: 7074 -> C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
DONE bench map: 7074 -> C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv
Fallback ETF used for sectors: UNKNOWN
  x_ticker y_ticker      corr      beta                     lvl3  n_overlap
0      ADV      QQQ  0.111736  0.152381  Advertising & Marketing         59
1      ADV     KWEB  0.145493  0.112247  Advertising & Marketing         59
2      ADV      IWM  0.165440  0.203582  Advertising & Marketing         59
3      ADV      SPY  0.182025  0.330725  Advertising & Marketing         59
4     AEHL      QQQ  0.458988  2.681018  Advertising & Marketing         60
Rows in raw stock-etf pairs: 25342
  x_ticker best_y_ticker  best_corr  beta_with_best                     lvl3  \
0      ADV           SPY   0.182025        0.330725  Advertising & Marketing
1     AEHL           QQQ   0.458988        2.681018  Advertising & Marketing
2      APP           SPY   0.403704        1.039864  Advertising & Marketing
3     AREN           SPY   0.449746        0.975719  Advertising & Marketing
4     BAOS           IWM   0.150614        0.406521  Advertising & Marketing

   n_overlap
0         59
1         60
2         59
3         58
4         58
Saved: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [15]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [16]:
TICKERS

     ticker       value                         lvl3  market_cap
0         A    50931.11  Medical Equipment & Devices     38252.0
1        AA  1733512.34              Metals & Mining     18971.0
2      AAAU   393575.35                          NaN         NaN
3      AACG       21.99                     Software        46.0
4      AACP        9.95             Asset Management       234.0
...     ...         ...                          ...         ...
7206   ZVOL      808.18                          NaN         NaN
7207   ZVRA    22821.75             Biotech & Pharma       627.0
7208    ZWS     1428.01                    Machinery      7904.0
7209   ZYBT       38.41             Biotech & Pharma        24.0
7210   ZYME    51031.02             Biotech & Pharma      1768.0

[7211 rows x 4 columns]

In [17]:
import pandas as pd

# список тикерів
tickers = [
    'SPY', 'IWM', 'GDX', 'XLF', 'QQQ', 'XLE', 'KRE', 'IBIT', 'KWEB', 'XLP', 'SOXX',
    'IGV', 'SMH', 'XLK', 'ITA', 'XLI', 'XTN', 'OIH', 'XLU', 'ICLN', 'XLB', 'SLX',
    'IBB', 'XBI', 'IHI', 'XLV', 'IHF', 'XRT', 'XLY', 'XHB', 'VNQ',
]


# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

   ticker
0     SPY
1     IWM
2     GDX
3     XLF
4     QQQ
5     XLE
6     KRE
7    IBIT
8    KWEB
9     XLP
10   SOXX
11    IGV
12    SMH
13    XLK
14    ITA
15    XLI
16    XTN
17    OIH
18    XLU
19   ICLN
20    XLB
21    SLX
22    IBB
23    XBI
24    IHI
25    XLV
26    IHF
27    XRT
28    XLY
29    XHB
30    VNQ

In [18]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=TICKERS,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=6,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 7211 тікерів (пропущено 0 по старому маніфесту) | 2026-03-06 00:00:00 → 2026-06-06 23:59:59 | interval=1 | next batch #7433 | run=ba0a630a

   workers: tickers=6, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-03-06 → 2026-06-05 (92 днів)

   📈 обробляються дні: 2026-06-06 → 2026-06-06 (1 днів)

   psutil · старт · 🧠 RAM: 347.6 MB

[10/7211] – AAON: empty |   0.14% | ETA 17:10

[20/7211] – AAPU: empty |   0.28% | ETA 15:37

[30/7211] – ABCB: empty |   0.42% | ETA 14:46

[40/7211] – ABSI: empty |   0.55% | ETA 14:17

[50/7211] – ACA: empty |   0.69% | ETA 13:56

   • RAM · 🧠 RAM: 357.8 MB

[60/7211] – ACGL: empty |   0.83% | ETA 13:38

[70/7211] – ACLX: empty |   0.97% | ETA 13:32

[80/7211] – ACRV: empty |   1.11% | ETA 13:28

[90/7211] – AD: empty |   1.25% | ETA 13:35

[100/7211] – ADIL: empty |   1.39% | ETA 13:30

   • RAM · 🧠 RAM: 362.8 MB

[110/7211] – ADUR: empty |   1.53% | ETA 13:25

[120/7211] – AEHL: empty |   1.66% | ETA 13:31

[130/7211] – AERO: empty |   1.80% | ETA 13:38

[140/7211] – AFG: empty |   1.94% | ETA 13:34

[150/7211] – AGCC: empty |   2.08% | ETA 13:32

   • RAM · 🧠 RAM: 362.6 MB

[160/7211] – AGIX: empty |   2.22% | ETA 13:27

[170/7211] – AGRO: empty |   2.36% | ETA 13:33

[180/7211] – AHRT: empty |   2.50% | ETA 13:33

[190/7211] – AIBD: empty |   2.63% | ETA 13:40

[200/7211] – AIMD: empty |   2.77% | ETA 13:36

   • RAM · 🧠 RAM: 362.6 MB

   ⏳ перед flush · 🧠 RAM: 362.6 MB

💾 batch 7433 → 108 рядків (всього 108 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7433.csv.gz

   ✅ після flush · 🧠 RAM: 362.6 MB

[210/7211] ✓ AIQD: 35 рядків |   2.91% | ETA 13:34

[220/7211] – AIT: empty |   3.05% | ETA 13:37

[230/7211] – AKBA: empty |   3.19% | ETA 13:40

[240/7211] – ALB: empty |   3.33% | ETA 13:33

[250/7211] – ALGT: empty |   3.47% | ETA 13:34

   • RAM · 🧠 RAM: 364.4 MB

   ⏳ перед flush · 🧠 RAM: 364.4 MB

💾 batch 7434 → 35 рядків (всього 143 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7434.csv.gz

   ✅ після flush · 🧠 RAM: 364.4 MB

[260/7211] – ALLE: empty |   3.61% | ETA 13:41

[270/7211] – ALNY: empty |   3.74% | ETA 13:39

[280/7211] – ALTI: empty |   3.88% | ETA 13:35

[290/7211] – AMAU: empty |   4.02% | ETA 13:46

[300/7211] – AMC: empty |   4.16% | ETA 13:43

   • RAM · 🧠 RAM: 362.0 MB

[310/7211] – AMDW: empty |   4.30% | ETA 13:44

[320/7211] – AMOD: empty |   4.44% | ETA 13:42

[330/7211] – AMS: empty |   4.58% | ETA 13:40

[340/7211] – AMTX: empty |   4.72% | ETA 13:36

[350/7211] – AMZO: empty |   4.85% | ETA 13:34

   • RAM · 🧠 RAM: 362.0 MB

[360/7211] – ANDG: empty |   4.99% | ETA 13:32

[370/7211] – ANIP: empty |   5.13% | ETA 13:28

[380/7211] – ANVS: empty |   5.27% | ETA 13:26

[390/7211] – AOTG: empty |   5.41% | ETA 13:26

[400/7211] – APG: empty |   5.55% | ETA 13:27

   • RAM · 🧠 RAM: 362.0 MB

[410/7211] – APP: empty |   5.69% | ETA 13:26

[420/7211] – AQB: empty |   5.82% | ETA 13:29

[430/7211] – ARBB: empty |   5.96% | ETA 13:27

[440/7211] – ARDX: empty |   6.10% | ETA 13:25

[450/7211] – ARKF: empty |   6.24% | ETA 13:24

   • RAM · 🧠 RAM: 362.0 MB

[460/7211] – ARMK: empty |   6.38% | ETA 13:24

[470/7211] – ARR: empty |   6.52% | ETA 13:22

[480/7211] – ARX: empty |   6.66% | ETA 13:24

[490/7211] – ASGN: empty |   6.80% | ETA 13:23

[500/7211] – ASND: empty |   6.93% | ETA 13:21

   • RAM · 🧠 RAM: 362.0 MB

[510/7211] – ASST: empty |   7.07% | ETA 13:19

[520/7211] – ASX: empty |   7.21% | ETA 13:19

[530/7211] – ATEN: empty |   7.35% | ETA 13:15

[540/7211] – ATII: empty |   7.49% | ETA 13:15

[550/7211] – ATRA: empty |   7.63% | ETA 13:14

   • RAM · 🧠 RAM: 362.6 MB

[560/7211] – AUDC: empty |   7.77% | ETA 13:12

[570/7211] – AUUD: empty |   7.90% | ETA 13:11

[580/7211] – AVDV: empty |   8.04% | ETA 13:07

[590/7211] – AVIG: empty |   8.18% | ETA 13:06

[600/7211] – AVNW: empty |   8.32% | ETA 13:02

   • RAM · 🧠 RAM: 361.1 MB

[610/7211] – AVY: empty |   8.46% | ETA 13:02

[620/7211] – AX: empty |   8.60% | ETA 13:00

[630/7211] – AXTI: empty |   8.74% | ETA 13:00

[640/7211] – AZN: empty |   8.88% | ETA 12:58

[650/7211] – BABO: empty |   9.01% | ETA 12:56

   • RAM · 🧠 RAM: 358.8 MB

[660/7211] – BAH: empty |   9.15% | ETA 12:54

[670/7211] – BAOS: empty |   9.29% | ETA 12:54

[680/7211] – BB: empty |   9.43% | ETA 12:54

[690/7211] – BBCA: empty |   9.57% | ETA 12:53

[700/7211] – BBSI: empty |   9.71% | ETA 12:52

   • RAM · 🧠 RAM: 355.7 MB

[710/7211] – BC: empty |   9.85% | ETA 12:48

[720/7211] – BCDA: empty |   9.98% | ETA 12:47

[730/7211] – BCRX: empty |  10.12% | ETA 12:45

[740/7211] – BDJ: empty |  10.26% | ETA 12:43

[750/7211] – BEEM: empty |  10.40% | ETA 12:40

   • RAM · 🧠 RAM: 345.4 MB

[760/7211] – BETA: empty |  10.54% | ETA 12:40

[770/7211] – BF.B: empty |  10.68% | ETA 12:38

[780/7211] – BG: empty |  10.82% | ETA 12:37

[790/7211] – BGS: empty |  10.96% | ETA 12:37

[800/7211] – BHK: empty |  11.09% | ETA 12:35

   • RAM · 🧠 RAM: 343.8 MB

   ⏳ перед flush · 🧠 RAM: 343.8 MB

💾 batch 7435 → 22 рядків (всього 165 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7435.csv.gz

   ✅ після flush · 🧠 RAM: 343.8 MB

[810/7211] – BIDG: empty |  11.23% | ETA 12:33

[820/7211] – BIPC: empty |  11.37% | ETA 12:33

[830/7211] – BITO: empty |  11.51% | ETA 12:31

[840/7211] – BIZD: empty |  11.65% | ETA 12:30

[850/7211] – BKLN: empty |  11.79% | ETA 12:28

   • RAM · 🧠 RAM: 343.4 MB

[860/7211] – BLBD: empty |  11.93% | ETA 12:27

[870/7211] – BLK: empty |  12.06% | ETA 12:25

[880/7211] – BLRX: empty |  12.20% | ETA 12:23

[890/7211] – BMA: empty |  12.34% | ETA 12:20

[900/7211] – BMR: empty |  12.48% | ETA 12:20

   • RAM · 🧠 RAM: 342.5 MB

[910/7211] – BN: empty |  12.62% | ETA 12:18

[920/7211] – BNL: empty |  12.76% | ETA 12:17

[930/7211] – BOBS: empty |  12.90% | ETA 12:16

[940/7211] – BOH: empty |  13.04% | ETA 12:14

[950/7211] – BOW: empty |  13.17% | ETA 12:13

   • RAM · 🧠 RAM: 342.3 MB

   ⏳ перед flush · 🧠 RAM: 342.3 MB

💾 batch 7436 → 7,883 рядків (всього 8,048 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7436.csv.gz

   ✅ після flush · 🧠 RAM: 342.5 MB

[960/7211] – BRAG: empty |  13.31% | ETA 12:12

[970/7211] – BRKHU: empty |  13.45% | ETA 12:09

[980/7211] – BRN: empty |  13.59% | ETA 12:09

[990/7211] – BRZE: empty |  13.73% | ETA 12:09

[1000/7211] – BSOL: empty |  13.87% | ETA 12:08

   • RAM · 🧠 RAM: 341.4 MB

   ⏳ перед flush · 🧠 RAM: 341.4 MB

💾 batch 7437 → 2,512 рядків (всього 10,560 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7437.csv.gz

   ✅ після flush · 🧠 RAM: 340.7 MB

[1010/7211] – BTC: empty |  14.01% | ETA 12:07

[1020/7211] – BTDR: empty |  14.15% | ETA 12:06

[1030/7211] – BTMCQ: empty |  14.28% | ETA 12:05

[1040/7211] – BTX: empty |  14.42% | ETA 12:04

[1050/7211] – BTAI: empty |  14.56% | ETA 12:03

   • RAM · 🧠 RAM: 334.9 MB

   ⏳ перед flush · 🧠 RAM: 334.9 MB

💾 batch 7438 → 43 рядків (всього 10,603 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7438.csv.gz

   ✅ після flush · 🧠 RAM: 334.9 MB

[1060/7211] – BVC: empty |  14.70% | ETA 12:01

[1070/7211] – BWLP: empty |  14.84% | ETA 12:00

[1080/7211] – BYAH: empty |  14.98% | ETA 11:59

[1090/7211] – BZH: empty |  15.12% | ETA 11:57

[1100/7211] – CACI: empty |  15.25% | ETA 11:56

   • RAM · 🧠 RAM: 330.7 MB

[1110/7211] – CALC: empty |  15.39% | ETA 11:55

[1120/7211] – CANG: empty |  15.53% | ETA 11:53

[1130/7211] – CARS: empty |  15.67% | ETA 11:52

[1140/7211] – CATY: empty |  15.81% | ETA 11:51

[1150/7211] – CBL: empty |  15.95% | ETA 11:49

   • RAM · 🧠 RAM: 327.3 MB

[1160/7211] – CBT: empty |  16.09% | ETA 11:49

[1170/7211] – CCCC: empty |  16.23% | ETA 11:49

[1180/7211] – CCK: empty |  16.36% | ETA 11:48

[1190/7211] – CCTG: empty |  16.50% | ETA 11:46

[1200/7211] – CDRE: empty |  16.64% | ETA 11:46

   • RAM · 🧠 RAM: 326.2 MB

[1210/7211] – CEG: empty |  16.78% | ETA 11:44

[1220/7211] – CEPT: empty |  16.92% | ETA 11:43

[1230/7211] – CF: empty |  17.06% | ETA 11:43

[1240/7211] – CG: empty |  17.20% | ETA 11:41

[1250/7211] – CGMS: empty |  17.33% | ETA 11:40

   • RAM · 🧠 RAM: 323.7 MB

[1260/7211] – CGW: empty |  17.47% | ETA 11:39

[1270/7211] – CHE: empty |  17.61% | ETA 11:37

[1280/7211] – CHPS: empty |  17.75% | ETA 11:36

[1290/7211] – CHTR: empty |  17.89% | ETA 11:35

[1300/7211] – CIEG: empty |  18.03% | ETA 11:34

   • RAM · 🧠 RAM: 323.7 MB

[1310/7211] – CIM: empty |  18.17% | ETA 11:33

[1320/7211] – CJMB: empty |  18.31% | ETA 11:31

[1330/7211] – CLH: empty |  18.44% | ETA 11:30

[1340/7211] – CLOU: empty |  18.58% | ETA 11:28

[1350/7211] – CLSK: empty |  18.72% | ETA 11:27

   • RAM · 🧠 RAM: 323.7 MB

[1360/7211] – CMC: empty |  18.86% | ETA 11:26

[1370/7211] – CMI: empty |  19.00% | ETA 11:26

[1380/7211] – CMTL: empty |  19.14% | ETA 11:24

[1390/7211] – CNEY: empty |  19.28% | ETA 11:23

[1400/7211] – CNRG: empty |  19.41% | ETA 11:21

   • RAM · 🧠 RAM: 321.4 MB

[1410/7211] – CNTX: empty |  19.55% | ETA 11:20

[1420/7211] – COCH: empty |  19.69% | ETA 11:18

[1430/7211] – COHH: empty |  19.83% | ETA 11:17

[1440/7211] – COLD: empty |  19.97% | ETA 11:15

[1450/7211] – CON: empty |  20.11% | ETA 11:14

   • RAM · 🧠 RAM: 319.9 MB

[1460/7211] – COPJ: empty |  20.25% | ETA 11:13

[1470/7211] – CORZW: empty |  20.39% | ETA 11:12

[1480/7211] ✓ COWG: 1,819 рядків |  20.52% | ETA 11:10

[1490/7211] – CPER: empty |  20.66% | ETA 11:09

[1500/7211] – CPS: empty |  20.80% | ETA 11:08

   • RAM · 🧠 RAM: 319.6 MB

   ⏳ перед flush · 🧠 RAM: 319.6 MB

💾 batch 7439 → 1,819 рядків (всього 12,422 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7439.csv.gz

   ✅ після flush · 🧠 RAM: 319.8 MB

[1510/7211] – CRAI: empty |  20.94% | ETA 11:07

[1520/7211] – CRCO: empty |  21.08% | ETA 11:06

[1530/7211] – CRGO: empty |  21.22% | ETA 11:04

[1540/7211] – CRMG: empty |  21.36% | ETA 11:04

[1550/7211] – CROX: empty |  21.49% | ETA 11:01

   • RAM · 🧠 RAM: 319.8 MB

   ⏳ перед flush · 🧠 RAM: 319.8 MB

💾 batch 7440 → 176 рядків (всього 12,598 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7440.csv.gz

   ✅ після flush · 🧠 RAM: 319.9 MB

[1560/7211] – CRVL: empty |  21.63% | ETA 11:00

[1570/7211] – CSAN: empty |  21.77% | ETA 10:59

[1580/7211] – CSQ: empty |  21.91% | ETA 10:58

[1590/7211] – CTAS: empty |  22.05% | ETA 10:57

[1600/7211] – CTO: empty |  22.19% | ETA 10:56

   • RAM · 🧠 RAM: 319.9 MB

[1610/7211] – CTVA: empty |  22.33% | ETA 10:55

[1620/7211] – CUK: empty |  22.47% | ETA 10:54

[1630/7211] – CVGI: empty |  22.60% | ETA 10:53

[1640/7211] – CVNA: empty |  22.74% | ETA 10:52

[1650/7211] – CWD: empty |  22.88% | ETA 10:50

   • RAM · 🧠 RAM: 314.2 MB

[1660/7211] – CX: empty |  23.02% | ETA 10:49

[1670/7211] – CYCN: empty |  23.16% | ETA 10:48

[1680/7211] – CZR: empty |  23.30% | ETA 10:47

[1690/7211] – DAR: empty |  23.44% | ETA 10:45

[1700/7211] – DBC: empty |  23.58% | ETA 10:44

   • RAM · 🧠 RAM: 307.6 MB

[1710/7211] – DBRG: empty |  23.71% | ETA 10:42

[1720/7211] – DCTH: empty |  23.85% | ETA 10:42

[1730/7211] – DE: empty |  23.99% | ETA 10:41

[1740/7211] – DETX: empty |  24.13% | ETA 10:40

[1750/7211] – DFH: empty |  24.27% | ETA 10:40

   • RAM · 🧠 RAM: 306.7 MB

[1760/7211] – DFSD: empty |  24.41% | ETA 10:38

[1770/7211] – DGX: empty |  24.55% | ETA 10:37

[1780/7211] – DHS: empty |  24.68% | ETA 10:36

[1790/7211] – DIOD: empty |  24.82% | ETA 10:35

[1800/7211] – DJIA: empty |  24.96% | ETA 10:35

   • RAM · 🧠 RAM: 306.0 MB

   ⏳ перед flush · 🧠 RAM: 306.0 MB

💾 batch 7441 → 4,857 рядків (всього 17,455 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7441.csv.gz

   ✅ після flush · 🧠 RAM: 306.6 MB

[1810/7211] – DKS: empty |  25.10% | ETA 10:34

[1820/7211] – DLX: empty |  25.24% | ETA 10:33

[1830/7211] – DNLI: empty |  25.38% | ETA 10:32

[1840/7211] – DOGD: empty |  25.52% | ETA 10:32

[1850/7211] – DOX: empty |  25.66% | ETA 10:32

   • RAM · 🧠 RAM: 303.4 MB

   ⏳ перед flush · 🧠 RAM: 303.4 MB

💾 batch 7442 → 134 рядків (всього 17,589 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7442.csv.gz

   ✅ після flush · 🧠 RAM: 303.3 MB

[1860/7211] – DRD: empty |  25.79% | ETA 10:31

[1870/7211] – DRNZ: empty |  25.93% | ETA 10:30

[1880/7211] – DSL: empty |  26.07% | ETA 10:29

[1890/7211] – DTE: empty |  26.21% | ETA 10:29

[1900/7211] – DUKR: empty |  26.35% | ETA 10:27

   • RAM · 🧠 RAM: 302.4 MB

   ⏳ перед flush · 🧠 RAM: 302.4 MB

💾 batch 7443 → 1,156 рядків (всього 18,745 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7443.csv.gz

   ✅ після flush · 🧠 RAM: 303.0 MB

[1910/7211] – DVLT: empty |  26.49% | ETA 10:26

[1920/7211] – DXJ: empty |  26.63% | ETA 10:25

[1930/7211] – DYN: empty |  26.76% | ETA 10:23

[1940/7211] – EBC: empty |  26.90% | ETA 10:22

[1950/7211] – ECC: empty |  27.04% | ETA 10:21

   • RAM · 🧠 RAM: 301.4 MB

[1960/7211] – ECX: empty |  27.18% | ETA 10:19

[1970/7211] – EDIV: empty |  27.32% | ETA 10:18

[1980/7211] – EDU: empty |  27.46% | ETA 10:17

[1990/7211] – EFOR: empty |  27.60% | ETA 10:15

[2000/7211] – EGGY: empty |  27.74% | ETA 10:15

   • RAM · 🧠 RAM: 300.9 MB

[2010/7211] – EIDO: empty |  27.87% | ETA 10:13

[2020/7211] – ELBM: empty |  28.01% | ETA 10:12

[2030/7211] – ELPC: empty |  28.15% | ETA 10:12

[2040/7211] – ELVA: empty |  28.29% | ETA 10:10

[2050/7211] – EMD: empty |  28.43% | ETA 10:09

   • RAM · 🧠 RAM: 300.9 MB

[2060/7211] – ENFR: empty |  28.57% | ETA 10:08

[2070/7211] – ENPX: empty |  28.71% | ETA 10:06

[2080/7211] – ENVX: empty |  28.84% | ETA 10:05

[2090/7211] – EP: empty |  28.98% | ETA 10:04

[2100/7211] – EPRX: empty |  29.12% | ETA 10:03

   • RAM · 🧠 RAM: 298.9 MB

[2110/7211] – EQR: empty |  29.26% | ETA 10:03

[2120/7211] – ERX: empty |  29.40% | ETA 10:02

[2130/7211] ✓ ESGL: 13 рядків |  29.54% | ETA 10:01

[2140/7211] – ESPO: empty |  29.68% | ETA 10:00

[2150/7211] – ETH: empty |  29.82% | ETA 09:59

   • RAM · 🧠 RAM: 298.8 MB

   ⏳ перед flush · 🧠 RAM: 298.8 MB

💾 batch 7444 → 13 рядків (всього 18,758 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7444.csv.gz

   ✅ після flush · 🧠 RAM: 298.8 MB

[2160/7211] – ETNG: empty |  29.95% | ETA 09:58

[2170/7211] – ETSY: empty |  30.09% | ETA 09:57

[2180/7211] – EURL: empty |  30.23% | ETA 09:56

[2190/7211] – EVH: empty |  30.37% | ETA 09:54

[2200/7211] – EVTC: empty |  30.51% | ETA 09:53

   • RAM · 🧠 RAM: 300.1 MB

   ⏳ перед flush · 🧠 RAM: 300.1 MB

💾 batch 7445 → 23 рядків (всього 18,781 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7445.csv.gz

   ✅ після flush · 🧠 RAM: 300.1 MB

[2210/7211] – EWG: empty |  30.65% | ETA 09:52

[2220/7211] – EWT: empty |  30.79% | ETA 09:51

[2230/7211] – EXC: empty |  30.92% | ETA 09:50

[2240/7211] – EXPD: empty |  31.06% | ETA 09:49

[2250/7211] – EZET: empty |  31.20% | ETA 09:48

   • RAM · 🧠 RAM: 299.5 MB

[2260/7211] – FALN: empty |  31.34% | ETA 09:47

[2270/7211] – FATN: empty |  31.48% | ETA 09:45

[2280/7211] – FBK: empty |  31.62% | ETA 09:44

[2290/7211] – FC: empty |  31.76% | ETA 09:43

[2300/7211] – FCO: empty |  31.90% | ETA 09:41

   • RAM · 🧠 RAM: 298.8 MB

[2310/7211] – FDMT: empty |  32.03% | ETA 09:40

[2320/7211] – FEIM: empty |  32.17% | ETA 09:39

[2330/7211] – FEPI: empty |  32.31% | ETA 09:38

[2340/7211] – FFIC: empty |  32.45% | ETA 09:36

[2350/7211] – FGL: empty |  32.59% | ETA 09:35

   • RAM · 🧠 RAM: 298.8 MB

[2360/7211] – FIAT: empty |  32.73% | ETA 09:34

[2370/7211] – FINX: empty |  32.87% | ETA 09:33

[2380/7211] – FIVN: empty |  33.01% | ETA 09:32

[2390/7211] – FLG: empty |  33.14% | ETA 09:30

[2400/7211] – FLNA: empty |  33.28% | ETA 09:29

   • RAM · 🧠 RAM: 299.1 MB

[2410/7211] – FLR: empty |  33.42% | ETA 09:28

[2420/7211] – FLYX: empty |  33.56% | ETA 09:27

[2430/7211] – FMTM: empty |  33.70% | ETA 09:26

[2440/7211] – FNDF: empty |  33.84% | ETA 09:24

[2450/7211] – FNUC: empty |  33.98% | ETA 09:24

   • RAM · 🧠 RAM: 298.9 MB

[2460/7211] – FNF: empty |  34.11% | ETA 09:23

[2470/7211] – FPS: empty |  34.25% | ETA 09:23

[2480/7211] – FRGT: empty |  34.39% | ETA 09:22

[2490/7211] – FRSX: empty |  34.53% | ETA 09:21

[2500/7211] – FSOL: empty |  34.67% | ETA 09:20

   • RAM · 🧠 RAM: 299.1 MB

   ⏳ перед flush · 🧠 RAM: 299.1 MB

💾 batch 7446 → 102 рядків (всього 18,883 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7446.csv.gz

   ✅ після flush · 🧠 RAM: 299.2 MB

[2510/7211] – FTDR: empty |  34.81% | ETA 09:19

[2520/7211] – FTLF: empty |  34.95% | ETA 09:18

[2530/7211] – FUBO: empty |  35.09% | ETA 09:17

[2540/7211] – FUTG: empty |  35.22% | ETA 09:16

[2550/7211] – FWRD: empty |  35.36% | ETA 09:15

   • RAM · 🧠 RAM: 298.6 MB

[2560/7211] – FXP: empty |  35.50% | ETA 09:14

[2570/7211] – GALT: empty |  35.64% | ETA 09:13

[2580/7211] – GAVA: empty |  35.78% | ETA 09:11

[2590/7211] – GBUG: empty |  35.92% | ETA 09:10

[2600/7211] – GCTS: empty |  36.06% | ETA 09:09

   • RAM · 🧠 RAM: 297.9 MB

[2610/7211] – GDS: empty |  36.19% | ETA 09:08

[2620/7211] – GDYN: empty |  36.33% | ETA 09:06

[2630/7211] – GENI: empty |  36.47% | ETA 09:06

[2640/7211] – GETY: empty |  36.61% | ETA 09:04

[2650/7211] – GGB: empty |  36.75% | ETA 09:03

   • RAM · 🧠 RAM: 296.4 MB

[2660/7211] – GHM: empty |  36.89% | ETA 09:02

[2670/7211] – GILD: empty |  37.03% | ETA 09:00

[2680/7211] – GLD: empty |  37.17% | ETA 08:59

[2690/7211] – GLDW: empty |  37.30% | ETA 08:58

[2700/7211] – GLNK: empty |  37.44% | ETA 08:57

   • RAM · 🧠 RAM: 293.4 MB

[2710/7211] – GLUE: empty |  37.58% | ETA 08:56

[2720/7211] – GME/W: empty |  37.72% | ETA 08:54

[2730/7211] – GNL: empty |  37.86% | ETA 08:53

[2740/7211] – GO: empty |  38.00% | ETA 08:52

[2750/7211] – GOLY: empty |  38.14% | ETA 08:51

   • RAM · 🧠 RAM: 292.0 MB

[2760/7211] – GORO: empty |  38.27% | ETA 08:50

[2770/7211] – GPGI: empty |  38.41% | ETA 08:48

[2780/7211] – GPT: empty |  38.55% | ETA 08:47

[2790/7211] – GRCE: empty |  38.69% | ETA 08:46

[2800/7211] – GRML: empty |  38.83% | ETA 08:44

   • RAM · 🧠 RAM: 291.3 MB

[2810/7211] – GRRR: empty |  38.97% | ETA 08:43

[2820/7211] – GSIW: empty |  39.11% | ETA 08:42

[2830/7211] – GTES: empty |  39.25% | ETA 08:41

[2840/7211] – GURE: empty |  39.38% | ETA 08:40

[2850/7211] – GXAI: empty |  39.52% | ETA 08:38

   • RAM · 🧠 RAM: 290.3 MB

[2860/7211] – HAFC: empty |  39.66% | ETA 08:37

[2870/7211] – HAWK: empty |  39.80% | ETA 08:36

[2880/7211] – HCAT: empty |  39.94% | ETA 08:35

[2890/7211] – HCTI: empty |  40.08% | ETA 08:33

[2900/7211] – HEI: empty |  40.22% | ETA 08:32

   • RAM · 🧠 RAM: 289.9 MB

[2910/7211] – HFWA: empty |  40.36% | ETA 08:31

[2920/7211] – HIBS: empty |  40.49% | ETA 08:30

[2930/7211] – HIT: empty |  40.63% | ETA 08:29

[2940/7211] – HKIT: empty |  40.77% | ETA 08:27

[2950/7211] – HLNE: empty |  40.91% | ETA 08:26

   • RAM · 🧠 RAM: 288.4 MB

[2960/7211] – HNDL: empty |  41.05% | ETA 08:25

[2970/7211] – HOLO: empty |  41.19% | ETA 08:24

[2980/7211] – HOOY: empty |  41.33% | ETA 08:23

[2990/7211] – HPE: empty |  41.46% | ETA 08:22

[3000/7211] – HRI: empty |  41.60% | ETA 08:21

   • RAM · 🧠 RAM: 289.8 MB

[3010/7211] – HSBC: empty |  41.74% | ETA 08:20

[3020/7211] – HTB: empty |  41.88% | ETA 08:19

[3030/7211] – HTZ: empty |  42.02% | ETA 08:17

[3040/7211] – HUDI: empty |  42.16% | ETA 08:16

[3050/7211] – HVAC: empty |  42.30% | ETA 08:15

   • RAM · 🧠 RAM: 289.2 MB

[3060/7211] – HYFT: empty |  42.44% | ETA 08:14

[3070/7211] – HYPR: empty |  42.57% | ETA 08:13

[3080/7211] – IAUI: empty |  42.71% | ETA 08:12

[3090/7211] – IBIO: empty |  42.85% | ETA 08:11

[3100/7211] – IBOT: empty |  42.99% | ETA 08:09

   • RAM · 🧠 RAM: 289.3 MB

[3110/7211] – ICFI: empty |  43.13% | ETA 08:08

[3120/7211] – ICVT: empty |  43.27% | ETA 08:07

[3130/7211] – IDNA: empty |  43.41% | ETA 08:06

[3140/7211] – IDXX: empty |  43.54% | ETA 08:05

[3150/7211] – IEX: empty |  43.68% | ETA 08:04

   • RAM · 🧠 RAM: 288.7 MB

[3160/7211] – IGC: empty |  43.82% | ETA 08:03

[3170/7211] – IGR: empty |  43.96% | ETA 08:02

[3180/7211] – IHRT: empty |  44.10% | ETA 08:00

[3190/7211] – IJH: empty |  44.24% | ETA 07:59

[3200/7211] – IMA: empty |  44.38% | ETA 07:58

   • RAM · 🧠 RAM: 289.0 MB

[3210/7211] – IMNN: empty |  44.52% | ETA 07:57

[3220/7211] – IMTX: empty |  44.65% | ETA 07:55

[3230/7211] – INCR: empty |  44.79% | ETA 07:54

[3240/7211] – INDV: empty |  44.93% | ETA 07:53

[3250/7211] – INGN: empty |  45.07% | ETA 07:52

   • RAM · 🧠 RAM: 290.0 MB

[3260/7211] – INO: empty |  45.21% | ETA 07:51

[3270/7211] – INTC: empty |  45.35% | ETA 07:50

[3280/7211] – INV: empty |  45.49% | ETA 07:49

[3290/7211] – IONQ/W: empty |  45.62% | ETA 07:48

[3300/7211] – IOYY: empty |  45.76% | ETA 07:47

   • RAM · 🧠 RAM: 290.2 MB

   ⏳ перед flush · 🧠 RAM: 290.2 MB

💾 batch 7447 → 918 рядків (всього 19,801 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7447.csv.gz

   ✅ після flush · 🧠 RAM: 290.7 MB

[3310/7211] – IPO: empty |  45.90% | ETA 07:45

[3320/7211] – IR: empty |  46.04% | ETA 07:44

[3330/7211] – IRMD: empty |  46.18% | ETA 07:43

[3340/7211] – ISRA: empty |  46.32% | ETA 07:42

[3350/7211] – ITDF: empty |  46.46% | ETA 07:41

   • RAM · 🧠 RAM: 290.7 MB

[3360/7211] – ITRN: empty |  46.60% | ETA 07:40

[3370/7211] – IVE: empty |  46.73% | ETA 07:39

[3380/7211] – IVR: empty |  46.87% | ETA 07:38

[3390/7211] – IWMI: empty |  47.01% | ETA 07:36

[3400/7211] – IX: empty |  47.15% | ETA 07:35

   • RAM · 🧠 RAM: 290.6 MB

[3410/7211] – IYT: empty |  47.29% | ETA 07:34

[3420/7211] – J: empty |  47.43% | ETA 07:33

[3430/7211] – JBHT: empty |  47.57% | ETA 07:32

[3440/7211] – JCSE: empty |  47.70% | ETA 07:31

[3450/7211] – JEPI: empty |  47.84% | ETA 07:29

   • RAM · 🧠 RAM: 290.2 MB

[3460/7211] – JFLX: empty |  47.98% | ETA 07:28

[3470/7211] – JMBS: empty |  48.12% | ETA 07:27

[3480/7211] – JOB: empty |  48.26% | ETA 07:26

[3490/7211] – JPIB: empty |  48.40% | ETA 07:25

[3500/7211] – JSCP: empty |  48.54% | ETA 07:23

   • RAM · 🧠 RAM: 291.8 MB

[3510/7211] – JXI: empty |  48.68% | ETA 07:22

[3520/7211] – KB: empty |  48.81% | ETA 07:21

[3530/7211] – KCOP: empty |  48.95% | ETA 07:20

[3540/7211] – KELYA: empty |  49.09% | ETA 07:19

[3550/7211] – KGEI: empty |  49.23% | ETA 07:17

   • RAM · 🧠 RAM: 291.0 MB

[3560/7211] – KIE: empty |  49.37% | ETA 07:16

[3570/7211] – KLIC: empty |  49.51% | ETA 07:15

[3580/7211] – KMLI: empty |  49.65% | ETA 07:14

[3590/7211] – KNF: empty |  49.79% | ETA 07:13

[3600/7211] – KODK: empty |  49.92% | ETA 07:12

   • RAM · 🧠 RAM: 290.6 MB

[3610/7211] – KOSS: empty |  50.06% | ETA 07:11

[3620/7211] – KREF: empty |  50.20% | ETA 07:09

[3630/7211] – KRRO: empty |  50.34% | ETA 07:08

[3640/7211] – KT: empty |  50.48% | ETA 07:07

[3650/7211] – KUST: empty |  50.62% | ETA 07:06

   • RAM · 🧠 RAM: 290.3 MB

[3660/7211] – KYLD: empty |  50.76% | ETA 07:05

[3670/7211] – LABU: empty |  50.89% | ETA 07:04

[3680/7211] – LASE: empty |  51.03% | ETA 07:03

[3690/7211] – LBTYA: empty |  51.17% | ETA 07:02

[3700/7211] – LCIZ: empty |  51.31% | ETA 07:01

   • RAM · 🧠 RAM: 289.7 MB

[3710/7211] – LECO: empty |  51.45% | ETA 07:00

[3720/7211] – LEVI: empty |  51.59% | ETA 06:59

[3730/7211] – LFUS: empty |  51.73% | ETA 06:58

[3740/7211] – LGO: empty |  51.87% | ETA 06:57

[3750/7211] – LIF: empty |  52.00% | ETA 06:56

   • RAM · 🧠 RAM: 290.4 MB

   ⏳ перед flush · 🧠 RAM: 290.4 MB

💾 batch 7448 → 899 рядків (всього 20,700 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7448.csv.gz

   ✅ після flush · 🧠 RAM: 290.8 MB

[3760/7211] – LINE: empty |  52.14% | ETA 06:55

[3770/7211] – LADR: empty |  52.28% | ETA 06:54

[3780/7211] – LLYVA: empty |  52.42% | ETA 06:53

[3790/7211] – LMRI: empty |  52.56% | ETA 06:51

[3800/7211] – LNKS: empty |  52.70% | ETA 06:50

   • RAM · 🧠 RAM: 290.2 MB

[3810/7211] – LODE: empty |  52.84% | ETA 06:49

[3820/7211] – LOUP: empty |  52.97% | ETA 06:48

[3830/7211] – LPSN: empty |  53.11% | ETA 06:47

[3840/7211] – LRE: empty |  53.25% | ETA 06:46

[3850/7211] – LSTA: empty |  53.39% | ETA 06:44

   • RAM · 🧠 RAM: 290.4 MB

[3860/7211] – LUCD: empty |  53.53% | ETA 06:43

[3870/7211] – LUNR: empty |  53.67% | ETA 06:42

[3880/7211] – LXEH: empty |  53.81% | ETA 06:41

[3890/7211] – LYRA: empty |  53.95% | ETA 06:40

[3900/7211] – MAAS: empty |  54.08% | ETA 06:39

   • RAM · 🧠 RAM: 290.5 MB

[3910/7211] – MAIA: empty |  54.22% | ETA 06:38

[3920/7211] – MANU: empty |  54.36% | ETA 06:37

[3930/7211] – MASK: empty |  54.50% | ETA 06:36

[3940/7211] – MAXNQ: empty |  54.64% | ETA 06:35

[3950/7211] – MBLY: empty |  54.78% | ETA 06:34

   • RAM · 🧠 RAM: 291.5 MB

[3960/7211] – MCGA: empty |  54.92% | ETA 06:33

[3970/7211] – MCY: empty |  55.05% | ETA 06:31

[3980/7211] – MDLN: empty |  55.19% | ETA 06:30

[3990/7211] – MDY: empty |  55.33% | ETA 06:29

[4000/7211] – MESO: empty |  55.47% | ETA 06:28

   • RAM · 🧠 RAM: 291.5 MB

[4010/7211] – METW: empty |  55.61% | ETA 06:26

[4020/7211] – MFSG: empty |  55.75% | ETA 06:26

[4030/7211] – MGPI: empty |  55.89% | ETA 06:25

[4040/7211] – MI: empty |  56.03% | ETA 06:24

[4050/7211] – MINY: empty |  56.16% | ETA 06:22

   • RAM · 🧠 RAM: 299.5 MB

[4060/7211] – MJ: empty |  56.30% | ETA 06:21

[4070/7211] – MLAB: empty |  56.44% | ETA 06:20

[4080/7211] – MLSS: empty |  56.58% | ETA 06:19

[4090/7211] – MMYT: empty |  56.72% | ETA 06:18

[4100/7211] – MNSB: empty |  56.86% | ETA 06:17

   • RAM · 🧠 RAM: 299.5 MB

[4110/7211] – MOBI: empty |  57.00% | ETA 06:16

[4120/7211] – MOO: empty |  57.13% | ETA 06:14

[4130/7211] – MPG: empty |  57.27% | ETA 06:13

[4140/7211] – MQ: empty |  57.41% | ETA 06:12

[4150/7211] – MRK: empty |  57.55% | ETA 06:11

   • RAM · 🧠 RAM: 299.6 MB

[4160/7211] – MRTN: empty |  57.69% | ETA 06:10

[4170/7211] – MSCI: empty |  57.83% | ETA 06:09

[4180/7211] – MSFW: empty |  57.97% | ETA 06:08

[4190/7211] – MSM: empty |  58.11% | ETA 06:07

[4200/7211] – MSTU: empty |  58.24% | ETA 06:06

   • RAM · 🧠 RAM: 300.2 MB

[4210/7211] – MTC: empty |  58.38% | ETA 06:05

[4220/7211] – MTNB: empty |  58.52% | ETA 06:03

[4230/7211] – MTZ: empty |  58.66% | ETA 06:02

[4240/7211] – MVIS: empty |  58.80% | ETA 06:01

[4250/7211] – MX: empty |  58.94% | ETA 06:00

   • RAM · 🧠 RAM: 299.4 MB

[4260/7211] – MYGN: empty |  59.08% | ETA 05:59

[4270/7211] – MZTI: empty |  59.22% | ETA 05:58

[4280/7211] – NAMS: empty |  59.35% | ETA 05:57

[4290/7211] – NAVI: empty |  59.49% | ETA 05:55

[4300/7211] – NBP: empty |  59.63% | ETA 05:54

   • RAM · 🧠 RAM: 299.0 MB

[4310/7211] – NCI: empty |  59.77% | ETA 05:53

[4320/7211] – NCT: empty |  59.91% | ETA 05:52

[4330/7211] – NEE: empty |  60.05% | ETA 05:51

[4340/7211] ✓ NEPH: 163 рядків |  60.19% | ETA 05:50

[4350/7211] – NEXR: empty |  60.32% | ETA 05:49

   • RAM · 🧠 RAM: 298.4 MB

   ⏳ перед flush · 🧠 RAM: 298.4 MB

💾 batch 7449 → 163 рядків (всього 20,863 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7449.csv.gz

   ✅ після flush · 🧠 RAM: 298.5 MB

[4360/7211] – NFLW: empty |  60.46% | ETA 05:48

[4370/7211] – NGL: empty |  60.60% | ETA 05:47

[4380/7211] – NI: empty |  60.74% | ETA 05:45

[4390/7211] – NIOG: empty |  60.88% | ETA 05:44

[4400/7211] – NKSH: empty |  61.02% | ETA 05:43

   • RAM · 🧠 RAM: 298.8 MB

[4410/7211] – NMRA: empty |  61.16% | ETA 05:42

[4420/7211] – NNN: empty |  61.30% | ETA 05:41

[4430/7211] – NORW: empty |  61.43% | ETA 05:40

[4440/7211] – NPK: empty |  61.57% | ETA 05:39

[4450/7211] – NRGU: empty |  61.71% | ETA 05:38

   • RAM · 🧠 RAM: 298.5 MB

[4460/7211] – NLY: empty |  61.85% | ETA 05:36

[4470/7211] – NTCT: empty |  61.99% | ETA 05:35

[4480/7211] – NTRA: empty |  62.13% | ETA 05:34

[4490/7211] – NUGT: empty |  62.27% | ETA 05:33

[4500/7211] – NVAX: empty |  62.40% | ETA 05:32

   • RAM · 🧠 RAM: 298.4 MB

[4510/7211] – NVDS: empty |  62.54% | ETA 05:31

[4520/7211] – NVMI: empty |  62.68% | ETA 05:29

[4530/7211] – NVT: empty |  62.82% | ETA 05:28

[4540/7211] – NWGL: empty |  62.96% | ETA 05:27

[4550/7211] – NXE: empty |  63.10% | ETA 05:26

   • RAM · 🧠 RAM: 297.5 MB

[4560/7211] – NXT: empty |  63.24% | ETA 05:25

[4570/7211] – NZF: empty |  63.38% | ETA 05:24

[4580/7211] – OCC: empty |  63.51% | ETA 05:23

[4590/7211] – OCUL: empty |  63.65% | ETA 05:22

[4600/7211] – OESX: empty |  63.79% | ETA 05:21

   • RAM · 🧠 RAM: 298.2 MB

[4610/7211] – OGI: empty |  63.93% | ETA 05:20

[4620/7211] – OILT: empty |  64.07% | ETA 05:18

[4630/7211] – OKTG: empty |  64.21% | ETA 05:17

[4640/7211] – OM: empty |  64.35% | ETA 05:16

[4650/7211] – ON: empty |  64.48% | ETA 05:15

   • RAM · 🧠 RAM: 298.2 MB

   ⏳ перед flush · 🧠 RAM: 298.2 MB

💾 batch 7450 → 8 рядків (всього 20,871 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7450.csv.gz

   ✅ після flush · 🧠 RAM: 298.2 MB

[4660/7211] – ONDU: empty |  64.62% | ETA 05:14

[4670/7211] – ONT: empty |  64.76% | ETA 05:12

[4680/7211] – OPEG: empty |  64.90% | ETA 05:11

[4690/7211] – OPRT: empty |  65.04% | ETA 05:10

[4700/7211] – ORBX: empty |  65.18% | ETA 05:09

   • RAM · 🧠 RAM: 298.3 MB

[4710/7211] – ORIC: empty |  65.32% | ETA 05:08

[4720/7211] – OS: empty |  65.46% | ETA 05:06

[4730/7211] – OSS: empty |  65.59% | ETA 05:05

[4740/7211] – OTH: empty |  65.73% | ETA 05:04

[4750/7211] – OVV: empty |  65.87% | ETA 05:03

   • RAM · 🧠 RAM: 298.2 MB

[4760/7211] – PAA: empty |  66.01% | ETA 05:02

[4770/7211] – PAG: empty |  66.15% | ETA 05:00

[4780/7211] – PAPI: empty |  66.29% | ETA 04:59

[4790/7211] – PAVM: empty |  66.43% | ETA 04:58

[4800/7211] – PAYO: empty |  66.56% | ETA 04:57

   • RAM · 🧠 RAM: 298.2 MB

[4810/7211] – PBR: empty |  66.70% | ETA 04:55

[4820/7211] – PCF: empty |  66.84% | ETA 04:54

[4830/7211] – PCVX: empty |  66.98% | ETA 04:53

[4840/7211] – PDO: empty |  67.12% | ETA 04:52

[4850/7211] – PEBO: empty |  67.26% | ETA 04:51

   • RAM · 🧠 RAM: 298.7 MB

   ⏳ перед flush · 🧠 RAM: 298.7 MB

💾 batch 7451 → 45 рядків (всього 20,916 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7451.csv.gz

   ✅ після flush · 🧠 RAM: 298.7 MB

[4860/7211] – PERF: empty |  67.40% | ETA 04:49

[4870/7211] – PFF: empty |  67.54% | ETA 04:48

[4880/7211] – PFS: empty |  67.67% | ETA 04:47

[4890/7211] – PGX: empty |  67.81% | ETA 04:46

[4900/7211] – PHI: empty |  67.95% | ETA 04:45

   • RAM · 🧠 RAM: 298.7 MB

[4910/7211] – PI: empty |  68.09% | ETA 04:44

[4920/7211] – PKBK: empty |  68.23% | ETA 04:42

[4930/7211] – PLAG: empty |  68.37% | ETA 04:41

[4940/7211] – PLRX: empty |  68.51% | ETA 04:40

[4950/7211] – PLTW: empty |  68.65% | ETA 04:39

   • RAM · 🧠 RAM: 299.1 MB

   ⏳ перед flush · 🧠 RAM: 299.1 MB

💾 batch 7452 → 1,336 рядків (всього 22,252 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7452.csv.gz

   ✅ після flush · 🧠 RAM: 299.9 MB

[4960/7211] – PLYX: empty |  68.78% | ETA 04:38

[4970/7211] – PMN: empty |  68.92% | ETA 04:36

[4980/7211] – PNC: empty |  69.06% | ETA 04:35

[4990/7211] – POLA: empty |  69.20% | ETA 04:34

[5000/7211] – POWW: empty |  69.34% | ETA 04:33

   • RAM · 🧠 RAM: 299.3 MB

[5010/7211] – PPL: empty |  69.48% | ETA 04:32

[5020/7211] – PRCH: empty |  69.62% | ETA 04:30

[5030/7211] – PRK: empty |  69.75% | ETA 04:29

[5040/7211] ✓ PRPO: 1,817 рядків |  69.89% | ETA 04:28

[5050/7211] – PRTH: empty |  70.03% | ETA 04:27

   • RAM · 🧠 RAM: 299.6 MB

   ⏳ перед flush · 🧠 RAM: 299.6 MB

💾 batch 7453 → 4,456 рядків (всього 26,708 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7453.csv.gz

   ✅ після flush · 🧠 RAM: 300.9 MB

[5060/7211] – PSHG: empty |  70.17% | ETA 04:25

[5070/7211] – PSN: empty |  70.31% | ETA 04:24

[5080/7211] – PSTG: empty |  70.45% | ETA 04:23

[5090/7211] – PTNQ: empty |  70.59% | ETA 04:22

[5100/7211] – PULS: empty |  70.73% | ETA 04:21

   • RAM · 🧠 RAM: 298.9 MB

[5110/7211] – PWRD: empty |  70.86% | ETA 04:19

[5120/7211] – PXS: empty |  71.00% | ETA 04:18

[5130/7211] – Q: empty |  71.14% | ETA 04:17

[5140/7211] – QCML: empty |  71.28% | ETA 04:16

[5150/7211] – QGEN: empty |  71.42% | ETA 04:15

   • RAM · 🧠 RAM: 299.8 MB

[5160/7211] – QNST: empty |  71.56% | ETA 04:13

[5170/7211] – QQQA: empty |  71.70% | ETA 04:12

[5180/7211] – QQQY: empty |  71.83% | ETA 04:11

[5190/7211] – QTEXW: empty |  71.97% | ETA 04:10

[5200/7211] – QUCY: empty |  72.11% | ETA 04:08

   • RAM · 🧠 RAM: 300.8 MB

   ⏳ перед flush · 🧠 RAM: 300.8 MB

💾 batch 7454 → 4,285 рядків (всього 30,993 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7454.csv.gz

   ✅ після flush · 🧠 RAM: 301.8 MB

[5210/7211] – QYLD: empty |  72.25% | ETA 04:07

[5220/7211] – RAIN: empty |  72.39% | ETA 04:06

[5230/7211] – RBLU: empty |  72.53% | ETA 04:05

[5240/7211] – RCEL: empty |  72.67% | ETA 04:04

[5250/7211] – RDAC: empty |  72.81% | ETA 04:02

   • RAM · 🧠 RAM: 305.5 MB

[5260/7211] – RDVI: empty |  72.94% | ETA 04:01

[5270/7211] – REA: empty |  73.08% | ETA 04:00

[5280/7211] – REGN: empty |  73.22% | ETA 03:59

[5290/7211] – RENX: empty |  73.36% | ETA 03:58

[5300/7211] – REW: empty |  73.50% | ETA 03:56

   • RAM · 🧠 RAM: 306.1 MB

[5310/7211] – RFIX: empty |  73.64% | ETA 03:55

[5320/7211] – RGTIW: empty |  73.78% | ETA 03:54

[5330/7211] – RHP: empty |  73.91% | ETA 03:53

[5340/7211] – RITR: empty |  74.05% | ETA 03:52

[5350/7211] – RKTL: empty |  74.19% | ETA 03:50

   • RAM · 🧠 RAM: 305.4 MB

[5360/7211] – RMAX: empty |  74.33% | ETA 03:49

[5370/7211] – RNAC: empty |  74.47% | ETA 03:48

[5380/7211] – ROBO: empty |  74.61% | ETA 03:47

[5390/7211] – ROK: empty |  74.75% | ETA 03:45

[5400/7211] – ROST: empty |  74.89% | ETA 03:44

   • RAM · 🧠 RAM: 305.4 MB

[5410/7211] – RQI: empty |  75.02% | ETA 03:43

[5420/7211] – RSI: empty |  75.16% | ETA 03:42

[5430/7211] – RTB: empty |  75.30% | ETA 03:41

[5440/7211] – RUSHB: empty |  75.44% | ETA 03:39

[5450/7211] – RVTY: empty |  75.58% | ETA 03:38

   • RAM · 🧠 RAM: 305.4 MB

[5460/7211] – RY: empty |  75.72% | ETA 03:37

[5470/7211] – RYTM: empty |  75.86% | ETA 03:36

[5480/7211] – SAFX: empty |  76.00% | ETA 03:34

[5490/7211] – SANM: empty |  76.13% | ETA 03:33

[5500/7211] – SB: empty |  76.27% | ETA 03:32

   • RAM · 🧠 RAM: 305.4 MB

[5510/7211] – SBFM: empty |  76.41% | ETA 03:31

[5520/7211] – SBU: empty |  76.55% | ETA 03:29

[5530/7211] – SCHF: empty |  76.69% | ETA 03:28

[5540/7211] – SCHM: empty |  76.83% | ETA 03:27

[5550/7211] – SCI: empty |  76.97% | ETA 03:26

   • RAM · 🧠 RAM: 305.4 MB

[5560/7211] – SCOP: empty |  77.10% | ETA 03:25

[5570/7211] – SDCI: empty |  77.24% | ETA 03:23

[5580/7211] – SDY: empty |  77.38% | ETA 03:22

[5590/7211] – SEF: empty |  77.52% | ETA 03:21

[5600/7211] – SEPN: empty |  77.66% | ETA 03:20

   • RAM · 🧠 RAM: 305.4 MB

[5610/7211] – SFBS: empty |  77.80% | ETA 03:18

[5620/7211] – SFY: empty |  77.94% | ETA 03:17

[5630/7211] – SGMT: empty |  78.08% | ETA 03:16

[5640/7211] – SHBI: empty |  78.21% | ETA 03:15

[5650/7211] – SHMD: empty |  78.35% | ETA 03:13

   • RAM · 🧠 RAM: 305.4 MB

[5660/7211] – SHY: empty |  78.49% | ETA 03:12

[5670/7211] – SIGI: empty |  78.63% | ETA 03:11

[5680/7211] – SITE: empty |  78.77% | ETA 03:10

[5690/7211] – SKF: empty |  78.91% | ETA 03:09

[5700/7211] – SKY: empty |  79.05% | ETA 03:07

   • RAM · 🧠 RAM: 305.4 MB

[5710/7211] – SKYY: empty |  79.18% | ETA 03:06

[5720/7211] – SLG: empty |  79.32% | ETA 03:05

[5730/7211] – SLNG: empty |  79.46% | ETA 03:04

[5740/7211] – SLV: empty |  79.60% | ETA 03:02

[5750/7211] – SMBC: empty |  79.74% | ETA 03:01

   • RAM · 🧠 RAM: 305.3 MB

[5760/7211] – SMFG: empty |  79.88% | ETA 03:00

[5770/7211] – SMPL: empty |  80.02% | ETA 02:59

[5780/7211] – SMU: empty |  80.16% | ETA 02:58

[5790/7211] – SNA: empty |  80.29% | ETA 02:56

[5800/7211] – SNDR: empty |  80.43% | ETA 02:55

   • RAM · 🧠 RAM: 305.0 MB

[5810/7211] – SNOW: empty |  80.57% | ETA 02:54

[5820/7211] – SNWV: empty |  80.71% | ETA 02:53

[5830/7211] – SOFI: empty |  80.85% | ETA 02:52

[5840/7211] – SOLX: empty |  80.99% | ETA 02:50

[5850/7211] – SOUNW: empty |  81.13% | ETA 02:49

   • RAM · 🧠 RAM: 303.9 MB

[5860/7211] – SPAB: empty |  81.26% | ETA 02:48

[5870/7211] – SPEM: empty |  81.40% | ETA 02:47

[5880/7211] – SPHR: empty |  81.54% | ETA 02:45

[5890/7211] – SPNT: empty |  81.68% | ETA 02:44

[5900/7211] – SPRO: empty |  81.82% | ETA 02:43

   • RAM · 🧠 RAM: 302.9 MB

[5910/7211] – SPTS: empty |  81.96% | ETA 02:42

[5920/7211] – SPXU: empty |  82.10% | ETA 02:40

[5930/7211] – SPYU: empty |  82.24% | ETA 02:39

[5940/7211] – SRCE: empty |  82.37% | ETA 02:38

[5950/7211] – SRTY: empty |  82.51% | ETA 02:37

   • RAM · 🧠 RAM: 302.2 MB

[5960/7211] – SSD: empty |  82.65% | ETA 02:36

[5970/7211] – SSYS: empty |  82.79% | ETA 02:34

[5980/7211] – STEL: empty |  82.93% | ETA 02:33

[5990/7211] – STIP: empty |  83.07% | ETA 02:32

[6000/7211] – STNG: empty |  83.21% | ETA 02:31

   • RAM · 🧠 RAM: 302.0 MB

[6010/7211] – STRS: empty |  83.34% | ETA 02:30

[6020/7211] – STUB: empty |  83.48% | ETA 02:28

[6030/7211] – SUIG: empty |  83.62% | ETA 02:27

[6040/7211] – SUPX: empty |  83.76% | ETA 02:26

[6050/7211] – SVRE: empty |  83.90% | ETA 02:25

   • RAM · 🧠 RAM: 301.2 MB

   ⏳ перед flush · 🧠 RAM: 301.2 MB

💾 batch 7455 → 720 рядків (всього 31,713 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7455.csv.gz

   ✅ після flush · 🧠 RAM: 301.6 MB

[6060/7211] – SWVL: empty |  84.04% | ETA 02:24

[6070/7211] – SY: empty |  84.18% | ETA 02:22

[6080/7211] – TAC: empty |  84.32% | ETA 02:21

[6090/7211] – TAOX: empty |  84.45% | ETA 02:20

[6100/7211] – TBCH: empty |  84.59% | ETA 02:19

   • RAM · 🧠 RAM: 301.0 MB

[6110/7211] – TBLL: empty |  84.73% | ETA 02:18

[6120/7211] – TCHI: empty |  84.87% | ETA 02:16

[6130/7211] – TDAX: empty |  85.01% | ETA 02:15

[6140/7211] – TDUP: empty |  85.15% | ETA 02:14

[6150/7211] – TECS: empty |  85.29% | ETA 02:13

   • RAM · 🧠 RAM: 301.0 MB

   ⏳ перед flush · 🧠 RAM: 301.0 MB

💾 batch 7456 → 317 рядків (всього 32,030 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7456.csv.gz

   ✅ після flush · 🧠 RAM: 301.1 MB

[6160/7211] – TENB: empty |  85.43% | ETA 02:11

[6170/7211] – TEX: empty |  85.56% | ETA 02:10

[6180/7211] – TG: empty |  85.70% | ETA 02:09

[6190/7211] – TGTX: empty |  85.84% | ETA 02:08

[6200/7211] – THQ: empty |  85.98% | ETA 02:07

   • RAM · 🧠 RAM: 302.3 MB

[6210/7211] – TIGO: empty |  86.12% | ETA 02:05

[6220/7211] – TJX: empty |  86.26% | ETA 02:04

[6230/7211] – TLK: empty |  86.40% | ETA 02:03

[6240/7211] – TLX: empty |  86.53% | ETA 02:02

[6250/7211] – TME: empty |  86.67% | ETA 02:00

   • RAM · 🧠 RAM: 301.4 MB

[6260/7211] – TNA: empty |  86.81% | ETA 01:59

[6270/7211] – TNXP: empty |  86.95% | ETA 01:58

[6280/7211] – TORO: empty |  87.09% | ETA 01:57

[6290/7211] – TPET: empty |  87.23% | ETA 01:55

[6300/7211] – TR: empty |  87.37% | ETA 01:54

   • RAM · 🧠 RAM: 296.7 MB

[6310/7211] – TRI: empty |  87.51% | ETA 01:53

[6320/7211] – TRNR: empty |  87.64% | ETA 01:52

[6330/7211] – TRTX: empty |  87.78% | ETA 01:50

[6340/7211] – TSCO: empty |  87.92% | ETA 01:49

[6350/7211] – TSLI: empty |  88.06% | ETA 01:48

   • RAM · 🧠 RAM: 296.7 MB

[6360/7211] – TSLZ: empty |  88.20% | ETA 01:47

[6370/7211] – TSPY: empty |  88.34% | ETA 01:45

[6380/7211] – TTAM: empty |  88.48% | ETA 01:44

[6390/7211] – TTI: empty |  88.61% | ETA 01:43

[6400/7211] – TUYA: empty |  88.75% | ETA 01:42

   • RAM · 🧠 RAM: 297.6 MB

[6410/7211] – TWIN: empty |  88.89% | ETA 01:40

[6420/7211] – TXNU: empty |  89.03% | ETA 01:39

[6430/7211] – TYG: empty |  89.17% | ETA 01:38

[6440/7211] – U: empty |  89.31% | ETA 01:37

[6450/7211] – UBSI: empty |  89.45% | ETA 01:35

   • RAM · 🧠 RAM: 297.6 MB

[6460/7211] – UCYB: empty |  89.59% | ETA 01:34

[6470/7211] – UFO: empty |  89.72% | ETA 01:33

[6480/7211] – UGRO: empty |  89.86% | ETA 01:32

[6490/7211] – UL: empty |  90.00% | ETA 01:30

[6500/7211] – ULY: empty |  90.14% | ETA 01:29

   • RAM · 🧠 RAM: 301.3 MB

   ⏳ перед flush · 🧠 RAM: 301.3 MB

💾 batch 7457 → 4,223 рядків (всього 36,253 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7457.csv.gz

   ✅ після flush · 🧠 RAM: 301.8 MB

[6510/7211] – UNG: empty |  90.28% | ETA 01:28

[6520/7211] – UOKA: empty |  90.42% | ETA 01:27

[6530/7211] – UPS: empty |  90.56% | ETA 01:25

[6540/7211] – URA: empty |  90.69% | ETA 01:24

[6550/7211] – USAU: empty |  90.83% | ETA 01:23

   • RAM · 🧠 RAM: 301.4 MB

   ⏳ перед flush · 🧠 RAM: 301.4 MB

💾 batch 7458 → 23 рядків (всього 36,276 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7458.csv.gz

   ✅ після flush · 🧠 RAM: 301.4 MB

[6560/7211] – USEA: empty |  90.97% | ETA 01:22

[6570/7211] – USLM: empty |  91.11% | ETA 01:20

[6580/7211] – USPH: empty |  91.25% | ETA 01:19

[6590/7211] – UTI: empty |  91.39% | ETA 01:18

[6600/7211] – UVIX: empty |  91.53% | ETA 01:17

   • RAM · 🧠 RAM: 300.3 MB

   ⏳ перед flush · 🧠 RAM: 300.3 MB

💾 batch 7459 → 131 рядків (всього 36,407 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7459.csv.gz

   ✅ після flush · 🧠 RAM: 299.9 MB

[6610/7211] – V: empty |  91.67% | ETA 01:15

[6620/7211] – VBIO: empty |  91.80% | ETA 01:14

[6630/7211] – VCIG: empty |  91.94% | ETA 01:13

[6640/7211] – VDC: empty |  92.08% | ETA 01:12

[6650/7211] – VERI: empty |  92.22% | ETA 01:10

   • RAM · 🧠 RAM: 301.1 MB

   ⏳ перед flush · 🧠 RAM: 301.1 MB

💾 batch 7460 → 211 рядків (всього 36,618 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7460.csv.gz

   ✅ після flush · 🧠 RAM: 301.2 MB

[6660/7211] – VFH: empty |  92.36% | ETA 01:09

[6670/7211] – VGNT: empty |  92.50% | ETA 01:08

[6680/7211] – VICI: empty |  92.64% | ETA 01:07

[6690/7211] – VIOT: empty |  92.77% | ETA 01:05

[6700/7211] – VITL: empty |  92.91% | ETA 01:04

   • RAM · 🧠 RAM: 301.5 MB

   ⏳ перед flush · 🧠 RAM: 301.5 MB

💾 batch 7461 → 306 рядків (всього 36,924 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_7461.csv.gz

   ✅ після flush · 🧠 RAM: 301.6 MB

[6710/7211] – VLTO: empty |  93.05% | ETA 01:03

[6720/7211] – VMI: empty |  93.19% | ETA 01:02

[6730/7211] – VNRX: empty |  93.33% | ETA 01:00

[6740/7211] – VOO: empty |  93.47% | ETA 00:59

[6750/7211] – VPLS: empty |  93.61% | ETA 00:58

   • RAM · 🧠 RAM: 301.4 MB

[6760/7211] – VRP: empty |  93.75% | ETA 00:56

[6770/7211] – VSA: empty |  93.88% | ETA 00:55

[6780/7211] – VSS: empty |  94.02% | ETA 00:54

[6790/7211] – VSXY: empty |  94.16% | ETA 00:53

[6800/7211] – VTOL: empty |  94.30% | ETA 00:51

   • RAM · 🧠 RAM: 303.5 MB

[6810/7211] – VUZI: empty |  94.44% | ETA 00:50

[6820/7211] – VXUS: empty |  94.58% | ETA 00:49

[6830/7211] – W: empty |  94.72% | ETA 00:48

[6840/7211] – WANT: empty |  94.86% | ETA 00:46

[6850/7211] – WBX: empty |  94.99% | ETA 00:45

   • RAM · 🧠 RAM: 302.6 MB

[6860/7211] – WDAF: empty |  95.13% | ETA 00:44

[6870/7211] – WDRN: empty |  95.27% | ETA 00:43

[6880/7211] – WEN: empty |  95.41% | ETA 00:41

[6890/7211] – WFC: empty |  95.55% | ETA 00:40

[6900/7211] – WHLR: empty |  95.69% | ETA 00:39

   • RAM · 🧠 RAM: 302.6 MB

[6910/7211] – WK: empty |  95.83% | ETA 00:38

[6920/7211] – WLTH: empty |  95.96% | ETA 00:36

[6930/7211] – WNEB: empty |  96.10% | ETA 00:35

[6940/7211] – WPM: empty |  96.24% | ETA 00:34

[6950/7211] – WSBC: empty |  96.38% | ETA 00:33

   • RAM · 🧠 RAM: 302.6 MB

[6960/7211] – WTBA: empty |  96.52% | ETA 00:31

[6970/7211] – WTS: empty |  96.66% | ETA 00:30

[6980/7211] – WWR: empty |  96.80% | ETA 00:29

[6990/7211] – XAGG: empty |  96.94% | ETA 00:28

[7000/7211] – XCCC: empty |  97.07% | ETA 00:26

   • RAM · 🧠 RAM: 303.1 MB

[7010/7211] – XENE: empty |  97.21% | ETA 00:25

[7020/7211] – XLB: empty |  97.35% | ETA 00:24

[7030/7211] – XLRE: empty |  97.49% | ETA 00:22

[7040/7211] – XME: empty |  97.63% | ETA 00:21

[7050/7211] – XOM: empty |  97.77% | ETA 00:20

   • RAM · 🧠 RAM: 302.9 MB

[7060/7211] – XPAY: empty |  97.91% | ETA 00:19

[7070/7211] – XQQI: empty |  98.04% | ETA 00:17

[7080/7211] – XRPT: empty |  98.18% | ETA 00:16

[7090/7211] – XSEM: empty |  98.32% | ETA 00:15

[7100/7211] – XWEL: empty |  98.46% | ETA 00:14

   • RAM · 🧠 RAM: 302.9 MB

[7110/7211] – XYZ: empty |  98.60% | ETA 00:12

[7120/7211] – YBTY: empty |  98.74% | ETA 00:11

[7130/7211] – YETI: empty |  98.88% | ETA 00:10

[7140/7211] – YOLO: empty |  99.02% | ETA 00:09

[7150/7211] – YSG: empty |  99.15% | ETA 00:07

   • RAM · 🧠 RAM: 302.9 MB

[7160/7211] – Z: empty |  99.29% | ETA 00:06

[7170/7211] – ZENA: empty |  99.43% | ETA 00:05

[7180/7211] – ZION: empty |  99.57% | ETA 00:03

[7190/7211] – ZOOZ: empty |  99.71% | ETA 00:02

[7200/7211] – ZTR: empty |  99.85% | ETA 00:01

   • RAM · 🧠 RAM: 302.9 MB

[7210/7211] – ZWS: empty |  99.99% | ETA 00:00

[7211/7211] – ZYME: empty | 100.00% | ETA 00:00

   🔚 фінал · 🧠 RAM: 302.7 MB

🏁 Готово. Нових рядків: 36,924 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 15:15

In [19]:
import os, glob, gc, time
from typing import Optional

import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str   = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    aggregate: bool = False,            # False → всі рядки, True → агрегація по (ticker,date)
    chunksize: int = 200_000,           # якщо мало RAM — ще зменш
    compression: str = "snappy",
    log_every: int = 5,
    sort_chunk: bool = True,            # sort within each chunk (ticker,dt)
):
    """
    Проходить по {folder}/{pattern}, фільтрує рядки:
      - за часовим вікном [start_time..end_time] по підрядку часу в 'dt'
      - опційно за датою [date_min..date_max] по підрядку дати в 'dt'
    і стрімово пише у один Parquet.

    Очікувані колонки у CSV: 'ticker','dt','o','h','l','c','v'.
    dt має формат 'YYYY-MM-DD HH:MM:SS' (string).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    # normalize dates (string compare works for YYYY-MM-DD)
    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    # читаємо тільки потрібне, даємо вузькі типи
    usecols = ["ticker", "dt", "o", "h", "l", "c", "v"]
    dtypes = {
        "ticker": "string",
        "dt": "string",         # важливо: фільтруємо по підрядку, без datetime-парсингу
        "o": "float32",
        "h": "float32",
        "l": "float32",
        "c": "float32",
        "v": "float32",
    }

    # підготовка виходу
    if os.path.exists(out_path):
        os.remove(out_path)
    writer = None

    t0 = time.time()
    total_in = total_out = 0
    file_idx = 0

    rng_str = ""
    if date_min or date_max:
        rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]"
    print(f"▶️ START: {folder}/{pattern} → {out_path}  chunksize={chunksize:,}{rng_str}")

    try:
        for path in files:
            file_idx += 1
            chunk_idx = 0

            reader = pd.read_csv(
                path,
                compression="infer",
                usecols=usecols,
                dtype=dtypes,
                chunksize=chunksize,
                low_memory=True,
                # engine="pyarrow",
            )

            for chunk in reader:
                chunk_idx += 1
                total_in += len(chunk)

                # швидке фільтрування по часу: 'YYYY-MM-DD HH:MM:SS'
                t = chunk["dt"].str.slice(11, 19)
                mask = (t >= start_time) & (t <= end_time)

                # фільтр по даті, також строками
                if date_min is not None or date_max is not None:
                    d = chunk["dt"].str.slice(0, 10)
                    if date_min is not None:
                        mask &= (d >= date_min)
                    if date_max is not None:
                        mask &= (d <= date_max)

                cut = chunk.loc[mask].copy()

                if cut.empty:
                    del chunk, t, mask, cut
                    gc.collect()
                    continue

                if aggregate:
                    # дата як рядок 'YYYY-MM-DD'
                    cut["date"] = cut["dt"].str.slice(0, 10)
                    # сорт для стабільності
                    if sort_chunk and {"ticker", "date"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "date"], kind="mergesort")
                    grp = (cut.groupby(["ticker", "date"], as_index=False, observed=True)
                              .agg({"v": "sum"}))  # приклад: сума обсягу; змінюй агрегацію за потреби
                    out_df = grp
                else:
                    # стабільний порядок в межах чанка
                    if sort_chunk and {"ticker", "dt"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "dt"], kind="mergesort")
                    out_df = cut

                table = pa.Table.from_pandas(out_df, preserve_index=False)
                if writer is None:
                    writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
                writer.write_table(table)
                total_out += len(out_df)

                if (chunk_idx % log_every) == 0:
                    elapsed = time.time() - t0
                    print(f"  [{file_idx}/{len(files)}] {os.path.basename(path)} "
                          f"chunk {chunk_idx}  in={total_in:,}  out={total_out:,}  "
                          f"elapsed={elapsed:,.1f}s")

                del chunk, t, mask, cut, out_df, table
                gc.collect()

    finally:
        if writer is not None:
            writer.close()

    print(f"✅ DONE  in={total_in:,} → out={total_out:,}  to {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [20]:
collect_premarket_by_day_stream(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,      # NEW
    date_max=end_date_str,        # NEW
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  chunksize=150,000  date=[2026-03-06..2026-06-06]

✅ DONE  in=276,877,118 → out=117,495,650  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 490.2s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows.parquet'

In [21]:
import os
import glob
import pandas as pd
from typing import Optional, Dict, Tuple

def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,
) -> pd.DataFrame:
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    OPEN_FROM, OPEN_TO   = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    best_open:  Dict[Tuple[str, str], Tuple[str, float]] = {}
    best_close: Dict[Tuple[str, str], Tuple[str, float]] = {}

    usecols = ["ticker", "dt", "o", "c"]

    for path in files:
        for chunk in pd.read_csv(path, compression="infer", low_memory=False,
                                 chunksize=chunksize, usecols=usecols):
            cols = set(map(str, chunk.columns))
            missing = set(usecols) - cols
            if missing:
                raise KeyError(f"{os.path.basename(path)}: відсутні колонки {missing}")

            dt = chunk["dt"].astype(str)
            if "o" in chunk.columns:
                chunk["o"] = pd.to_numeric(chunk["o"], errors="coerce")
            if "c" in chunk.columns:
                chunk["c"] = pd.to_numeric(chunk["c"], errors="coerce")

            hhmm = dt.str.slice(11, 16)
            date = dt.str.slice(0, 10)

            # OPEN
            mask_o = (hhmm >= OPEN_FROM) & (hhmm <= OPEN_TO) & chunk["o"].notna()
            if mask_o.any():
                cut = chunk.loc[mask_o, ["ticker", "o"]].copy()
                cut["date"] = date[mask_o].values
                cut["dt"]   = dt[mask_o].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="first")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_open.get(key)
                    if (cur is None) or (r.dt < cur[0]):
                        best_open[key] = (r.dt, float(r.o))

            # CLOSE
            mask_c = (hhmm >= CLOSE_FROM) & (hhmm <= CLOSE_TO) & chunk["c"].notna()
            if mask_c.any():
                cut = chunk.loc[mask_c, ["ticker", "c"]].copy()
                cut["date"] = date[mask_c].values
                cut["dt"]   = dt[mask_c].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="last")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_close.get(key)
                    if (cur is None) or (r.dt > cur[0]):
                        best_close[key] = (r.dt, float(r.c))

    opens_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_open.items()],
        columns=["ticker", "date", "open"]
    )
    closes_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_close.items()],
        columns=["ticker", "date", "close"]
    )

    out = pd.merge(opens_df, closes_df, on=["ticker","date"], how="outer") \
            .sort_values(["ticker","date"], kind="stable") \
            .reset_index(drop=True)

    # ⬇️ ОКРУГЛЕННЯ ДО 2 ЗНАКІВ
    if "open" in out.columns:
        out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    if "close" in out.columns:
        out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)

    # завжди Parquet
    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)

    return out

In [22]:
df_oc = build_oc_from_intraday_folder(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "oc.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [23]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [24]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=65.6s

[batch   10] rows=20,000,000  elapsed=131.3s

[batch   15] rows=30,000,000  elapsed=197.2s

[batch   20] rows=40,000,000  elapsed=263.0s

[batch   25] rows=50,000,000  elapsed=329.1s

[batch   30] rows=60,000,000  elapsed=395.0s

[batch   35] rows=70,000,000  elapsed=460.0s

[batch   40] rows=80,000,000  elapsed=525.3s

[batch   45] rows=90,000,000  elapsed=591.4s

[batch   50] rows=100,000,000  elapsed=657.2s

[batch   55] rows=110,000,000  elapsed=722.9s

✅ DONE  rows=117,495,650  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  in 774.4s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet

In [25]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        # нульовий prev_close → NaN, щоб не ділити на 0
        denom = df["prev_close"].replace({0: np.nan})

        # розрахунок % vs prev_close
        pct = (df[value_col] / denom - 1.0) * 100.0

        # ще раз гарантуємо float dtype (без object/pd.NA всередині)
        pct = pd.to_numeric(pct, errors="coerce")

        if round_to is not None:
            pct = pct.round(int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(
                output_path,
                table.schema,
                compression="snappy",
            )
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [26]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

[batch    5] rows=10,000,000  elapsed=7.5s

[batch   10] rows=20,000,000  elapsed=15.0s

[batch   15] rows=30,000,000  elapsed=22.6s

[batch   20] rows=40,000,000  elapsed=30.1s

[batch   25] rows=50,000,000  elapsed=37.6s

[batch   30] rows=60,000,000  elapsed=45.3s

[batch   35] rows=70,000,000  elapsed=52.9s

[batch   40] rows=80,000,000  elapsed=60.5s

[batch   45] rows=90,000,000  elapsed=67.9s

[batch   50] rows=100,000,000  elapsed=75.6s

[batch   55] rows=110,000,000  elapsed=83.1s

✅ DONE  rows=117,495,650  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  in 88.9s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet

In [27]:
import os
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Read ticker->bench mapping from csv/xlsx and return ['ticker','bench'].
    """
    ext = os.path.splitext(mapping_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(mapping_path)
    else:
        try:
            df = pd.read_csv(mapping_path, sep=None, engine="python")
        except Exception:
            df = pd.read_csv(mapping_path)

    cols = {c.lower().strip(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol") or list(df.columns)[0]
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf") or list(df.columns)[1]

    out = df[[tcol, bcol]].rename(columns={tcol: "ticker", bcol: "bench"}).dropna()
    out["ticker"] = out["ticker"].astype(str).str.upper().str.strip()
    out["bench"] = out["bench"].astype(str).str.upper().str.strip()
    out = out[(out["ticker"] != "") & (out["bench"] != "")]
    return out.drop_duplicates(ignore_index=True)


def corr_beta_from_mapping_to_parquet(*args, **kwargs):
    """
    Deprecated API path removed.
    corr/beta is now computed locally in cell 12 and written in cell 13/28.
    """
    raise RuntimeError(
        "corr_beta_from_mapping_to_parquet is deprecated. "
        "Use local calculation in cell 12 and parquet output in cell 13/28."
    )

In [28]:
import os
import pandas as pd

out_path = str(WORK_DIR / "corr_beta_pairs.parquet")

# If parquet already exists from cell 13, keep it.
# Otherwise rebuild it from x_to_best_etf_by_lvl3.csv (no API calls).
if not os.path.exists(out_path):
    src_csv = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv")
    if not os.path.exists(src_csv):
        raise FileNotFoundError(f"Neither {out_path} nor {src_csv} exists")

    d = pd.read_csv(src_csv)
    need = ["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
    miss = [c for c in need if c not in d.columns]
    if miss:
        raise KeyError(f"Missing columns in {src_csv}: {miss}")

    d = d.rename(columns={
        "best_y_ticker": "y_ticker",
        "best_corr": "corr",
        "beta_with_best": "beta",
    })[["x_ticker", "y_ticker", "corr", "beta"]]
    d.to_parquet(out_path, index=False)

print("Result:", out_path)

Result: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [29]:

y_list = ["SPY", "IWM", "GDX", "XLF", "QQQ", "XLE", "KRE", "BITO", "XLP", "SOXX"]

In [30]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    # Читаємо БЕЗ фільтра колонок — так надійніше для різних схем
    table = pq.read_table(path)
    df = table.to_pandas()

    # нормалізуємо імена колонок для пошуку
    name_map = {c: c.strip().lower() for c in df.columns}
    inv_map = {v: k for k, v in name_map.items()}

    has_api    = ("x_ticker" in inv_map) and ("y_ticker" in inv_map)
    has_direct = ("ticker" in inv_map) and ("bench" in inv_map)

    if not (has_api or has_direct):
        # допоміжна підказка, що саме є в файлі
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={
            inv_map["x_ticker"]: "ticker",
            inv_map["y_ticker"]: "bench"
        })
    else:
        df = df.rename(columns={
            inv_map["ticker"]: "ticker",
            inv_map["bench"]:  "bench"
        })

    # corr/beta можуть бути відсутні — створимо
    if "corr" not in name_map.values():
        df["corr"] = pd.NA
    else:
        df = df.rename(columns={inv_map["corr"]: "corr"})
    if "beta" not in name_map.values():
        df["beta"] = pd.NA
    else:
        df = df.rename(columns={inv_map["beta"]: "beta"})

    # залишаємо тільки потрібне
    keep = [c for c in ["ticker", "bench", "corr", "beta"] if c in df.columns]
    df = df[keep].copy()

    # нормалізація значень
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"]  = df["bench"].astype(str).str.strip().str.upper()
    if "corr" in df.columns:
        df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    if "beta" in df.columns:
        df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    # якщо раптом на один тикер кілька рядків — візьмемо з найбільшою corr
    if "corr" in df.columns:
        df = (df.sort_values(["ticker", "corr"], ascending=[True, False])
                .drop_duplicates(subset=["ticker"], keep="first")
                .reset_index(drop=True))
    else:
        df = df.drop_duplicates(subset=["ticker"], keep="first").reset_index(drop=True)

    # гарантуємо повний набір стовпців
    for c in ("corr", "beta"):
        if c not in df.columns:
            df[c] = pd.NA

    return df[["ticker", "bench", "corr", "beta"]]


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), мерджить 'bench','corr','beta' з іншого
    Parquet (мапа) по 'ticker' і пише новий Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0
    batches = 0

    print(f"▶️ START merge → {out_parquet_path}")

    for batch in pf.iter_batches(batch_size=batch_rows):  # читаємо всі колонки
        batches += 1
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")
        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(mapping, on="ticker", how="left", validate="m:1")

        # Переставимо нові колонки за потреби
        if insert_before in merged.columns:
            cols = list(merged.columns)
            for c in ("bench", "corr", "beta"):
                if c in cols: cols.remove(c)
            idx = cols.index(insert_before)
            new_cols = cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]
            merged = merged[new_cols]
        else:
            base = [c for c in merged.columns if c not in ("bench","corr","beta")]
            merged = merged[base + ["bench","corr","beta"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if batches % log_every_batches == 0:
            print(f"[batch {batches:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path


# опціональний аліас під старе ім’я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [31]:
out_path = attach_bench_corr_beta_parquet(
    input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    batch_rows=2_000_000,
    round_decimals=4,
    insert_before="pct_vs_prev_close",
    compression="snappy",
)
print("Готово:", out_path)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

[batch    5] rows=10,000,000  elapsed=17.4s

[batch   10] rows=20,000,000  elapsed=34.8s

[batch   15] rows=30,000,000  elapsed=52.3s

[batch   20] rows=40,000,000  elapsed=69.8s

[batch   25] rows=50,000,000  elapsed=87.2s

[batch   30] rows=60,000,000  elapsed=104.0s

[batch   35] rows=70,000,000  elapsed=121.2s

[batch   40] rows=80,000,000  elapsed=138.5s

[batch   45] rows=90,000,000  elapsed=156.0s

[batch   50] rows=100,000,000  elapsed=173.5s

[batch   55] rows=110,000,000  elapsed=190.5s

✅ DONE rows=117,495,650 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet  in 203.8s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

In [32]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [33]:
peek_parquet("CRACEN/work/premarket_rows_final.parquet", n=620)

Файл: CRACEN/work/premarket_rows_final.parquet
Рядків (meta): 117,495,650
Колонок: 14
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta
NaN у 'bench' (у прев'ю): 0/620
NaN у 'corr' (у прев'ю): 0/620
NaN у 'beta' (у прев'ю): 0/620

Перші рядки:
    ticker                  dt           o           h           l           c         v        date    open  prev_close  Stack% bench    corr    beta
0        A 2026-03-06 09:30:00  116.660004  116.660004  116.160004  116.160004   14743.0  2026-03-06  116.66      118.13   -1.24   IWM  0.7442  0.6533
1        A 2026-03-06 09:31:00  116.555000  116.555000  116.547501  116.555000     697.0  2026-03-06  116.66      118.13   -1.33   IWM  0.7442  0.6533
2        A 2026-03-06 09:32:00  116.502502  116.550003  116.050003  116.550003    1952.0  2026-03-06  116.66      118.13   -1.38   IWM  0.7442  0.6533
3        A 2026-03-06 09:33:00  116.464996  116.464996  116.464996  116.464996     200.0  2026-03-06  116.66      118.13   -1.41   IWM  0.7442  0.6533
4        A 2026-03-06 09:34:00  116.250000  116.250000  116.250000  116.250000     400.0  2026-03-06  116.66      118.13   -1.59   IWM  0.7442  0.6533
5        A 2026-03-06 09:35:00  116.349998  116.470001  116.160004  116.290001    3634.0  2026-03-06  116.66      118.13   -1.51   IWM  0.7442  0.6533
6        A 2026-03-06 09:36:00  116.040001  116.040001  116.010002  116.010002     500.0  2026-03-06  116.66      118.13   -1.77   IWM  0.7442  0.6533
7        A 2026-03-06 09:37:00  116.044998  116.135002  116.000000  116.000000    1200.0  2026-03-06  116.66      118.13   -1.77   IWM  0.7442  0.6533
8        A 2026-03-06 09:38:00  116.190002  116.190002  115.974998  116.059998     950.0  2026-03-06  116.66      118.13   -1.64   IWM  0.7442  0.6533
9        A 2026-03-06 09:39:00  115.839996  116.000000  115.589996  115.589996    3220.0  2026-03-06  116.66      118.13   -1.94   IWM  0.7442  0.6533
10       A 2026-03-06 09:40:00  115.775002  115.775002  115.775002  115.775002     250.0  2026-03-06  116.66      118.13   -1.99   IWM  0.7442  0.6533
11       A 2026-03-06 09:41:00  115.529999  115.705002  115.500000  115.665001    1176.0  2026-03-06  116.66      118.13   -2.20   IWM  0.7442  0.6533
12       A 2026-03-06 09:42:00  115.769997  115.769997  115.599998  115.599998     600.0  2026-03-06  116.66      118.13   -2.00   IWM  0.7442  0.6533
13       A 2026-03-06 09:43:00  115.635002  115.800003  115.635002  115.699997     500.0  2026-03-06  116.66      118.13   -2.11   IWM  0.7442  0.6533
14       A 2026-03-06 09:44:00  115.790001  115.830002  115.720001  115.750000     850.0  2026-03-06  116.66      118.13   -1.98   IWM  0.7442  0.6533
15       A 2026-03-06 09:45:00  115.610001  115.650002  115.610001  115.629997     300.0  2026-03-06  116.66      118.13   -2.13   IWM  0.7442  0.6533
16       A 2026-03-06 09:46:00  115.489998  115.519997  115.489998  115.519997     931.0  2026-03-06  116.66      118.13   -2.23   IWM  0.7442  0.6533
17       A 2026-03-06 09:47:00  115.510002  115.660004  115.510002  115.660004    1153.0  2026-03-06  116.66      118.13   -2.22   IWM  0.7442  0.6533
18       A 2026-03-06 09:48:00  115.665001  115.665001  115.665001  115.665001    1833.0  2026-03-06  116.66      118.13   -2.09   IWM  0.7442  0.6533
19       A 2026-03-06 09:49:00  115.669998  115.669998  115.669998  115.669998     600.0  2026-03-06  116.66      118.13   -2.08   IWM  0.7442  0.6533
20       A 2026-03-06 09:50:00  115.669998  115.669998  115.625000  115.665001    2400.0  2026-03-06  116.66      118.13   -2.08   IWM  0.7442  0.6533
21       A 2026-03-06 09:51:00  115.680000  116.032799  115.680000  115.809998    2183.0  2026-03-06  116.66      118.13   -2.07   IWM  0.7442  0.6533
22       A 2026-03-06 09:52:00  115.639999  115.639999  115.529999  115.529999     563.0  2026-03-06  116.66      118.13   -2.11   IWM  0.7442  0.6533
23       A 2026-03-06 09:53:00  115.379997  115.389999  115.279999  115.334999    1300.0  2026-03-06  116.66      118.13   -2.33   IWM  0.7442  0.6533
24       A 2026-03-06 09:55:00  115.315002  115.449997  115.315002  115.360001   14537.0  2026-03-06  116.66      118.13   -2.38   IWM  0.7442  0.6533
25       A 2026-03-06 09:56:00  115.360001  115.550003  115.360001  115.535004    5263.0  2026-03-06  116.66      118.13   -2.34   IWM  0.7442  0.6533
26       A 2026-03-06 09:57:00  115.519997  115.519997  115.230003  115.230003    4300.0  2026-03-06  116.66      118.13   -2.21   IWM  0.7442  0.6533
27       A 2026-03-06 09:58:00  115.339996  115.339996  115.339996  115.339996     100.0  2026-03-06  116.66      118.13   -2.36   IWM  0.7442  0.6533
28       A 2026-03-06 10:00:00  115.440002  115.820000  115.440002  115.820000    1393.0  2026-03-06  116.66      118.13   -2.28   IWM  0.7442  0.6533
29       A 2026-03-06 10:01:00  115.779999  115.779999  115.779999  115.779999     100.0  2026-03-06  116.66      118.13   -1.99   IWM  0.7442  0.6533
30       A 2026-03-06 10:02:00  115.860001  115.959999  115.779999  115.779999     739.0  2026-03-06  116.66      118.13   -1.92   IWM  0.7442  0.6533
31       A 2026-03-06 10:03:00  115.800003  115.809998  115.589996  115.637497    2800.0  2026-03-06  116.66      118.13   -1.97   IWM  0.7442  0.6533
32       A 2026-03-06 10:04:00  115.589996  115.790001  115.589996  115.790001    1383.0  2026-03-06  116.66      118.13   -2.15   IWM  0.7442  0.6533
33       A 2026-03-06 10:05:00  115.690002  115.690002  115.595001  115.595001     300.0  2026-03-06  116.66      118.13   -2.07   IWM  0.7442  0.6533
34       A 2026-03-06 10:06:00  115.595001  115.680000  115.595001  115.605003     615.0  2026-03-06  116.66      118.13   -2.15   IWM  0.7442  0.6533
35       A 2026-03-06 10:07:00  115.650002  115.709999  115.625000  115.669998    1300.0  2026-03-06  116.66      118.13   -2.10   IWM  0.7442  0.6533
36       A 2026-03-06 10:08:00  115.580002  115.879997  115.570000  115.690002    2236.0  2026-03-06  116.66      118.13   -2.16   IWM  0.7442  0.6533
37       A 2026-03-06 10:09:00  115.669998  115.669998  115.480003  115.580002    3434.0  2026-03-06  116.66      118.13   -2.08   IWM  0.7442  0.6533
38       A 2026-03-06 10:10:00  115.614998  115.614998  115.614998  115.614998     100.0  2026-03-06  116.66      118.13   -2.13   IWM  0.7442  0.6533
39       A 2026-03-06 10:11:00  115.760002  115.769997  115.750000  115.760002     400.0  2026-03-06  116.66      118.13   -2.01   IWM  0.7442  0.6533
40       A 2026-03-06 10:12:00  115.669998  115.669998  115.669998  115.669998     200.0  2026-03-06  116.66      118.13   -2.08   IWM  0.7442  0.6533
41       A 2026-03-06 10:13:00  115.769997  115.800003  115.745003  115.790001     900.0  2026-03-06  116.66      118.13   -2.00   IWM  0.7442  0.6533
42       A 2026-03-06 10:14:00  115.629997  115.760002  115.629997  115.760002     900.0  2026-03-06  116.66      118.13   -2.12   IWM  0.7442  0.6533
43       A 2026-03-06 10:15:00  115.809998  115.809998  115.760002  115.809998     700.0  2026-03-06  116.66      118.13   -1.96   IWM  0.7442  0.6533
44       A 2026-03-06 10:16:00  115.709999  115.709999  115.709999  115.709999     139.0  2026-03-06  116.66      118.13   -2.05   IWM  0.7442  0.6533
45       A 2026-03-06 10:18:00  115.800003  115.800003  115.709999  115.730003    1184.0  2026-03-06  116.66      118.13   -1.97   IWM  0.7442  0.6533
46       A 2026-03-06 10:19:00  115.754997  115.754997  115.519997  115.589996    1522.0  2026-03-06  116.66      118.13   -2.01   IWM  0.7442  0.6533
47       A 2026-03-06 10:20:00  115.529999  115.540001  115.529999  115.529999    1221.0  2026-03-06  116.66      118.13   -2.20   IWM  0.7442  0.6533
48       A 2026-03-06 10:21:00  115.540001  115.650002  115.529999  115.650002     500.0  2026-03-06  116.66      118.13   -2.19   IWM  0.7442  0.6533
49       A 2026-03-06 10:22:00  115.690002  115.690002  115.580002  115.580002     200.0  2026-03-06  116.66      118.13   -2.07   IWM  0.7442  0.6533
50       A 2026-03-06 10:23:00  115.754997  115.900002  115.754997  115.805000    1200.0  2026-03-06  116.66      118.13   -2.01   IWM  0.7442  0.6533
51       A 2026-03-06 10:24:00  115.870003  115.870003  115.849998  115.855003     425.0  2026-03-06  116.66      118.13   -1.91   IWM  0.7442  0.6533
52       A 2026-03-06 10:25:00  115.855003  115.855003  115.855003  115.855003     600.0  2026-03-06  116.66      118.13   -1.93   IWM  0.7442  0.6533
53       A 2026-03-06 10:26:00  115.860001  115.860001  115.860001  115.860001     800.0  2026-03-06  116.66      118.13   -1.92   IWM  0.7442  0.6533
54       A 2026-03-06 10:27:00  115.870003  116.070000  115.870003  116.000000    1000.0  2026-03-06  116.66      118.13   -1.91   IWM  0.7442  0.6533
55       A 2026-03-06 10:29:00  115.910004  115.910004  115.660004  115.809998   66091.0  2026-03-06  116.66      118.13   -1.88   IWM  0.7442  0.6533
56       A 2026-03-06 10:30:00  115.930000  115.985001  115.930000  115.970001    1532.0  2026-03-06  116.66      118.13   -1.86   IWM  0.7442  0.6533
57       A 2026-03-06 10:31:00  116.015900  116.080002  116.010002  116.019997    1016.0  2026-03-06  116.66      118.13   -1.79   IWM  0.7442  0.6533
58       A 2026-03-06 10:33:00  116.065002  116.160004  115.910004  116.160004    1482.0  2026-03-06  116.66      118.13   -1.75   IWM  0.7442  0.6533
59       A 2026-03-06 10:35:00  116.099998  116.264999  116.099998  116.264999    1326.0  2026-03-06  116.66      118.13   -1.72   IWM  0.7442  0.6533
60       A 2026-03-06 10:36:00  116.260002  116.364998  116.260002  116.364998     600.0  2026-03-06  116.66      118.13   -1.58   IWM  0.7442  0.6533
61       A 2026-03-06 10:37:00  116.370003  116.375000  116.260002  116.349998     750.0  2026-03-06  116.66      118.13   -1.49   IWM  0.7442  0.6533
62       A 2026-03-06 10:38:00  116.370003  116.519997  116.370003  116.404999     625.0  2026-03-06  116.66      118.13   -1.49   IWM  0.7442  0.6533
63       A 2026-03-06 10:39:00  116.400002  116.410004  116.370003  116.410004     800.0  2026-03-06  116.66      118.13   -1.46   IWM  0.7442  0.6533
64       A 2026-03-06 10:40:00  116.410004  116.410004  116.300003  116.300003    1300.0  2026-03-06  116.66      118.13   -1.46   IWM  0.7442  0.6533
65       A 2026-03-06 10:41:00  116.290001  116.330002  116.279999  116.324997    1435.0  2026-03-06  116.66      118.13   -1.56   IWM  0.7442  0.6533
66       A 2026-03-06 10:42:00  116.250000  116.324997  116.199997  116.320000    1402.0  2026-03-06  116.66      118.13   -1.59   IWM  0.7442  0.6533
67       A 2026-03-06 10:43:00  116.239998  116.250000  116.239998  116.245003    1547.0  2026-03-06  116.66      118.13   -1.60   IWM  0.7442  0.6533
68       A 2026-03-06 10:44:00  116.260002  116.260002  116.150002  116.180000    1500.0  2026-03-06  116.66      118.13   -1.58   IWM  0.7442  0.6533
69       A 2026-03-06 10:45:00  116.080002  116.154999  115.989998  115.989998    1160.0  2026-03-06  116.66      118.13   -1.74   IWM  0.7442  0.6533
70       A 2026-03-06 10:46:00  115.940002  116.019997  115.889999  116.014999    1158.0  2026-03-06  116.66      118.13   -1.85   IWM  0.7442  0.6533
71       A 2026-03-06 10:47:00  115.989998  115.989998  115.989998  115.989998     100.0  2026-03-06  116.66      118.13   -1.81   IWM  0.7442  0.6533
72       A 2026-03-06 10:48:00  115.985001  116.175003  115.985001  116.120003    1100.0  2026-03-06  116.66      118.13   -1.82   IWM  0.7442  0.6533
73       A 2026-03-06 10:49:00  116.099998  116.099998  116.099998  116.099998     100.0  2026-03-06  116.66      118.13   -1.72   IWM  0.7442  0.6533
74       A 2026-03-06 10:50:00  116.084999  116.084999  115.985001  116.000000     600.0  2026-03-06  116.66      118.13   -1.73   IWM  0.7442  0.6533
75       A 2026-03-06 10:51:00  116.000000  116.000000  115.919998  115.919998     370.0  2026-03-06  116.66      118.13   -1.80   IWM  0.7442  0.6533
76       A 2026-03-06 10:52:00  115.889999  115.889999  115.800003  115.809998    3365.0  2026-03-06  116.66      118.13   -1.90   IWM  0.7442  0.6533
77       A 2026-03-06 10:53:00  115.830002  115.919998  115.820000  115.845001    1220.0  2026-03-06  116.66      118.13   -1.95   IWM  0.7442  0.6533
78       A 2026-03-06 10:54:00  115.930000  115.930000  115.849998  115.885002    1038.0  2026-03-06  116.66      118.13   -1.86   IWM  0.7442  0.6533
79       A 2026-03-06 10:55:00  115.940002  116.175003  115.930000  116.089996    1472.0  2026-03-06  116.66      118.13   -1.85   IWM  0.7442  0.6533
80       A 2026-03-06 10:56:00  116.180000  116.260002  116.180000  116.260002    1600.0  2026-03-06  116.66      118.13   -1.65   IWM  0.7442  0.6533
81       A 2026-03-06 10:57:00  116.264999  116.264999  116.264999  116.264999     100.0  2026-03-06  116.66      118.13   -1.58   IWM  0.7442  0.6533
82       A 2026-03-06 10:58:00  116.209999  116.239998  116.129997  116.129997    1500.0  2026-03-06  116.66      118.13   -1.63   IWM  0.7442  0.6533
83       A 2026-03-06 10:59:00  116.235001  116.260002  116.180000  116.260002     700.0  2026-03-06  116.66      118.13   -1.60   IWM  0.7442  0.6533
84       A 2026-03-06 11:00:00  116.260002  116.489998  116.239998  116.440002    4059.0  2026-03-06  116.66      118.13   -1.58   IWM  0.7442  0.6533
85       A 2026-03-06 11:01:00  116.449997  116.569000  116.449997  116.569000    2593.0  2026-03-06  116.66      118.13   -1.42   IWM  0.7442  0.6533
86       A 2026-03-06 11:02:00  116.480003  116.589996  116.480003  116.500000    2525.0  2026-03-06  116.66      118.13   -1.40   IWM  0.7442  0.6533
87       A 2026-03-06 11:03:00  116.430000  116.555000  116.400002  116.485001    1000.0  2026-03-06  116.66      118.13   -1.44   IWM  0.7442  0.6533
88       A 2026-03-06 11:04:00  116.485001  116.660004  116.431999  116.580002    3975.0  2026-03-06  116.66      118.13   -1.39   IWM  0.7442  0.6533
89       A 2026-03-06 11:05:00  116.500000  116.574997  116.459999  116.459999    1200.0  2026-03-06  116.66      118.13   -1.38   IWM  0.7442  0.6533
90       A 2026-03-06 11:06:00  116.605003  116.605003  116.389999  116.389999    1200.0  2026-03-06  116.66      118.13   -1.29   IWM  0.7442  0.6533
91       A 2026-03-06 11:07:00  116.459999  116.464996  116.349998  116.349998     701.0  2026-03-06  116.66      118.13   -1.41   IWM  0.7442  0.6533
92       A 2026-03-06 11:08:00  116.349998  116.434998  116.349998  116.434998     519.0  2026-03-06  116.66      118.13   -1.51   IWM  0.7442  0.6533
93       A 2026-03-06 11:09:00  116.349998  116.449997  116.339996  116.339996    1250.0  2026-03-06  116.66      118.13   -1.51   IWM  0.7442  0.6533
94       A 2026-03-06 11:10:00  116.339996  116.437302  116.320000  116.410004    1211.0  2026-03-06  116.66      118.13   -1.52   IWM  0.7442  0.6533
95       A 2026-03-06 11:11:00  116.300003  116.410004  116.239998  116.320000    1251.0  2026-03-06  116.66      118.13   -1.55   IWM  0.7442  0.6533
96       A 2026-03-06 11:12:00  116.220001  116.330002  116.209999  116.260002     900.0  2026-03-06  116.66      118.13   -1.62   IWM  0.7442  0.6533
97       A 2026-03-06 11:13:00  116.339996  116.394997  116.309998  116.320000    3945.0  2026-03-06  116.66      118.13   -1.52   IWM  0.7442  0.6533
98       A 2026-03-06 11:14:00  116.389999  116.394997  116.290001  116.290001     500.0  2026-03-06  116.66      118.13   -1.47   IWM  0.7442  0.6533
99       A 2026-03-06 11:15:00  116.330002  116.349998  116.180000  116.349998    2346.0  2026-03-06  116.66      118.13   -1.52   IWM  0.7442  0.6533
100      A 2026-03-06 11:16:00  116.440002  116.510002  116.404999  116.510002    4151.0  2026-03-06  116.66      118.13   -1.43   IWM  0.7442  0.6533
101      A 2026-03-06 11:17:00  116.434998  116.434998  116.330002  116.330002     800.0  2026-03-06  116.66      118.13   -1.43   IWM  0.7442  0.6533
102      A 2026-03-06 11:18:00  116.330002  116.379997  116.330002  116.334999     666.0  2026-03-06  116.66      118.13   -1.52   IWM  0.7442  0.6533
103      A 2026-03-06 11:19:00  116.309998  116.320000  116.309998  116.320000     300.0  2026-03-06  116.66      118.13   -1.54   IWM  0.7442  0.6533
104      A 2026-03-06 11:20:00  116.370003  116.379898  116.269997  116.269997     631.0  2026-03-06  116.66      118.13   -1.49   IWM  0.7442  0.6533
105      A 2026-03-06 11:21:00  116.309998  116.400002  116.309998  116.320000    6200.0  2026-03-06  116.66      118.13   -1.54   IWM  0.7442  0.6533
106      A 2026-03-06 11:22:00  116.385002  116.385002  116.160004  116.220001    2390.0  2026-03-06  116.66      118.13   -1.48   IWM  0.7442  0.6533
107      A 2026-03-06 11:23:00  116.150002  116.182503  116.150002  116.165001     400.0  2026-03-06  116.66      118.13   -1.68   IWM  0.7442  0.6533
108      A 2026-03-06 11:24:00  116.169998  116.339996  116.169998  116.339996    1422.0  2026-03-06  116.66      118.13   -1.66   IWM  0.7442  0.6533
109      A 2026-03-06 11:25:00  116.410004  116.410004  116.410004  116.410004     200.0  2026-03-06  116.66      118.13   -1.46   IWM  0.7442  0.6533
110      A 2026-03-06 11:26:00  116.410004  116.410004  116.330002  116.345001     900.0  2026-03-06  116.66      118.13   -1.46   IWM  0.7442  0.6533
111      A 2026-03-06 11:27:00  116.345001  116.419998  116.199997  116.230003    2600.0  2026-03-06  116.66      118.13   -1.51   IWM  0.7442  0.6533
112      A 2026-03-06 11:28:00  116.230003  116.309998  116.230003  116.275002     500.0  2026-03-06  116.66      118.13   -1.61   IWM  0.7442  0.6533
113      A 2026-03-06 11:29:00  116.275002  116.300003  116.269997  116.290001     900.0  2026-03-06  116.66      118.13   -1.57   IWM  0.7442  0.6533
114      A 2026-03-06 11:30:00  116.324997  116.324997  116.129997  116.129997     900.0  2026-03-06  116.66      118.13   -1.53   IWM  0.7442  0.6533
115      A 2026-03-06 11:31:00  116.180000  116.260002  116.180000  116.260002    1591.0  2026-03-06  116.66      118.13   -1.65   IWM  0.7442  0.6533
116      A 2026-03-06 11:32:00  116.260002  116.339996  116.260002  116.339996     401.0  2026-03-06  116.66      118.13   -1.58   IWM  0.7442  0.6533
117      A 2026-03-06 11:33:00  116.300003  116.300003  116.250000  116.250000     400.0  2026-03-06  116.66      118.13   -1.55   IWM  0.7442  0.6533
118      A 2026-03-06 11:34:00  116.254997  116.254997  116.089996  116.199997    1520.0  2026-03-06  116.66      118.13   -1.59   IWM  0.7442  0.6533
119      A 2026-03-06 11:35:00  116.239998  116.349998  116.239998  116.309998    1425.0  2026-03-06  116.66      118.13   -1.60   IWM  0.7442  0.6533
120      A 2026-03-06 11:36:00  116.309998  116.419998  116.309998  116.400002    1111.0  2026-03-06  116.66      118.13   -1.54   IWM  0.7442  0.6533
121      A 2026-03-06 11:37:00  116.400002  116.480003  116.400002  116.480003     400.0  2026-03-06  116.66      118.13   -1.46   IWM  0.7442  0.6533
122      A 2026-03-06 11:38:00  116.510002  116.680000  116.510002  116.599998    7234.0  2026-03-06  116.66      118.13   -1.37   IWM  0.7442  0.6533
123      A 2026-03-06 11:39:00  116.614998  116.614998  116.614998  116.614998     100.0  2026-03-06  116.66      118.13   -1.28   IWM  0.7442  0.6533
124      A 2026-03-06 11:40:00  116.519997  116.559998  116.440002  116.550003    1300.0  2026-03-06  116.66      118.13   -1.36   IWM  0.7442  0.6533
125      A 2026-03-06 11:41:00  116.504997  116.504997  116.504997  116.504997     200.0  2026-03-06  116.66      118.13   -1.38   IWM  0.7442  0.6533
126      A 2026-03-06 11:43:00  116.495003  116.495003  116.320000  116.320000     700.0  2026-03-06  116.66      118.13   -1.38   IWM  0.7442  0.6533
127      A 2026-03-06 11:44:00  116.290001  116.339996  116.260002  116.260002     600.0  2026-03-06  116.66      118.13   -1.56   IWM  0.7442  0.6533
128      A 2026-03-06 11:45:00  116.324997  116.510002  116.324997  116.510002    1175.0  2026-03-06  116.66      118.13   -1.53   IWM  0.7442  0.6533

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta
0,A,2026-03-06 09:30:00,116.660004,116.660004,116.160004,116.160004,14743.0,2026-03-06,116.66,118.13,-1.24,IWM,0.7442,0.6533
1,A,2026-03-06 09:31:00,116.555000,116.555000,116.547501,116.555000,697.0,2026-03-06,116.66,118.13,-1.33,IWM,0.7442,0.6533
2,A,2026-03-06 09:32:00,116.502502,116.550003,116.050003,116.550003,1952.0,2026-03-06,116.66,118.13,-1.38,IWM,0.7442,0.6533
3,A,2026-03-06 09:33:00,116.464996,116.464996,116.464996,116.464996,200.0,2026-03-06,116.66,118.13,-1.41,IWM,0.7442,0.6533
4,A,2026-03-06 09:34:00,116.250000,116.250000,116.250000,116.250000,400.0,2026-03-06,116.66,118.13,-1.59,IWM,0.7442,0.6533
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,A,2026-03-09 13:05:00,114.830002,114.834999,114.800003,114.822502,1400.0,2026-03-09,114.88,115.08,-0.22,IWM,0.7442,0.6533
616,A,2026-03-09 13:06:00,114.834999,114.930000,114.834999,114.930000,1425.0,2026-03-09,114.88,115.08,-0.21,IWM,0.7442,0.6533
617,A,2026-03-09 13:07:00,114.915001,115.040001,114.849998,114.870003,3607.0,2026-03-09,114.88,115.08,-0.14,IWM,0.7442,0.6533
618,A,2026-03-09 13:08:00,114.809998,114.930000,114.775002,114.775002,1668.0,2026-03-09,114.88,115.08,-0.23,IWM,0.7442,0.6533
619,A,2026-03-09 13:09:00,114.820000,114.849998,114.820000,114.849998,433.0,2026-03-09,114.88,115.08,-0.23,IWM,0.7442,0.6533

In [34]:
# список тикерів
tickers = [
    'SPY', 'IWM', 'GDX', 'XLF', 'QQQ', 'XLE', 'KRE', 'IBIT', 'KWEB', 'XLP', 'SOXX',
    'IGV', 'SMH', 'XLK', 'ITA', 'XLI', 'XTN', 'OIH', 'XLU', 'ICLN', 'XLB', 'SLX',
    'IBB', 'XBI', 'IHI', 'XLV', 'IHF', 'XRT', 'XLY', 'XHB', 'VNQ',
]

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [35]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=6,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 31 тікерів (пропущено 0 по старому маніфесту) | 2026-03-06 00:00:00 → 2026-06-06 23:59:59 | interval=1 | next batch #0072 | run=3422f316

   workers: tickers=6, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-03-06 → 2026-06-05 (92 днів)

   📈 обробляються дні: 2026-06-06 → 2026-06-06 (1 днів)

   psutil · старт · 🧠 RAM: 1,527.0 MB

[10/31] – IBIT: empty |  32.26% | ETA 00:03

[20/31] – ICLN: empty |  64.52% | ETA 00:01

[30/31] – XRT: empty |  96.77% | ETA 00:00

[31/31] – SLX: empty | 100.00% | ETA 00:00

   🔚 фінал · 🧠 RAM: 1,512.3 MB

🏁 Готово. Нових рядків: 0 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:14

In [36]:
collect_premarket_by_day_stream(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  chunksize=150,000

  [69/71] intraday_0069.csv.gz chunk 5  in=2,122,725  out=2,122,725  elapsed=5.0s
✅ DONE  in=2,157,947 → out=2,157,947  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 5.1s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_etf_rows.parquet'

In [37]:
df_oc = build_oc_from_intraday_folder(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "oc_etf.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date   open  close
0   BITO  2025-10-28  18.96  18.72
1   BITO  2025-10-29  18.70  18.21
2   BITO  2025-10-30  17.83  17.53
3   BITO  2025-10-31  18.09  18.07
4   BITO  2025-11-03  16.89  16.74

In [38]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [39]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=2,157,947  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 6.5s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [40]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None

def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",   # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Benchk%",  # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        denom = df["prev_close"].replace({0: pd.NA})
        pct = (df[value_col] / denom - 1.0) * 100.0
        if round_to is not None:
            pct = pct.round(round_to)

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",   # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [41]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=2,157,947  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 1.6s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [42]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception as e:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий файл по ключах ('bench'↔'ticker', 'dt') і пише новий Parquet.
    - У ETF-файлі колонка з відсотком може називатись 'bench%' або 'pct_vs_prev_close' — обидва варіанти підтримуються.
    - Базовий файл не змінюється, додається тільки нова колонка 'Bench%'.
    """

    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    # ---------- 1) Збираємо мапу з ETF-файла: (bench, dt) -> Bench% ----------
    def _read_etf_mapping(etf_parquet: str) -> pd.DataFrame:
        pf = pq.ParquetFile(etf_parquet)
        parts = []
        # читаємо всі колонки, щоб не ловити різні схеми у row-groups
        for batch in pf.iter_batches():
            df = batch.to_pandas()
            # обов'язкові
            for col in ("ticker", "dt"):
                if col not in df.columns:
                    raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")

            # колонка відсотка: bench% або pct_vs_prev_close
            cols_l = {c.lower().strip(): c for c in df.columns}
            if "bench%" in cols_l:
                val_col = cols_l["bench%"]
            elif "pct_vs_prev_close" in cols_l:
                val_col = cols_l["pct_vs_prev_close"]
            else:
                raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

            d = df[["ticker", "dt", val_col]].copy()
            d["ticker"] = d["ticker"].astype(str).str.strip().str.upper()
            d["dt"]     = pd.to_datetime(d["dt"], errors="coerce")
            if align_to_minute:
                d["dt"] = d["dt"].dt.floor("T")
            d = d.dropna(subset=["dt"])
            d = d.rename(columns={"ticker": "bench", val_col: "Bench%"})
            d["Bench%"] = pd.to_numeric(d["Bench%"], errors="coerce")
            parts.append(d)

            del df, d, batch
            gc.collect()

        if not parts:
            return pd.DataFrame(columns=["bench","dt","Bench%"])

        etf_map = pd.concat(parts, ignore_index=True)
        # прибираємо дублікати — залишаємо пізніший запис
        etf_map = (etf_map.sort_values(["bench","dt"])
                           .drop_duplicates(subset=["bench","dt"], keep="last")
                           .reset_index(drop=True))
        return etf_map

    etf_map = _read_etf_mapping(etf_path)
    if round_decimals is not None and "Bench%" in etf_map.columns:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    # ---------- 2) Потоково проходимо базовий файл і підмерджуємо Bench% ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START merge → {out_path}")
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # ключі
        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        df["bench"] = df["bench"].astype(str).str.strip().str.upper()
        df["dt"]    = pd.to_datetime(df["dt"], errors="coerce")
        if align_to_minute:
            df["dt"] = df["dt"].dt.floor("T")

        merged = df.merge(etf_map, on=["bench","dt"], how="left", validate="m:1")

        # розташування 'Bench%'
        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("Bench%")
            pos = cols.index(insert_before)
            cols = cols[:pos] + ["Bench%"] + cols[pos:]
            merged = merged[cols]
        # інакше — залишаємо в кінці як є

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [43]:
merge_bench_pct_from_etf(
    base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    batch_rows=2_000_000,
    align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
    round_decimals=2,
    insert_before=None,          # або, наприклад, "pct_vs_prev_close"
    compression="snappy",
)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet

[batch    5] rows=10,000,000  elapsed=20.7s

[batch   10] rows=20,000,000  elapsed=40.3s

[batch   15] rows=30,000,000  elapsed=60.1s

[batch   20] rows=40,000,000  elapsed=79.7s

[batch   25] rows=50,000,000  elapsed=100.1s

[batch   30] rows=60,000,000  elapsed=120.1s

[batch   35] rows=70,000,000  elapsed=140.4s

[batch   40] rows=80,000,000  elapsed=160.9s

[batch   45] rows=90,000,000  elapsed=180.8s

[batch   50] rows=100,000,000  elapsed=200.8s

[batch   55] rows=110,000,000  elapsed=220.8s

✅ DONE rows=117,495,650 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet  in 236.3s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct.parquet'

In [44]:
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm


def _pick_first_existing(df: pd.DataFrame, candidates):
    cols_l = {c.lower().strip(): c for c in df.columns}
    for c in candidates:
        if c.lower() in cols_l:
            return cols_l[c.lower()]
    return None


def get_reports(ticker, last_n_reports, start_date, end_date):
    try:
        params = {
            "ticker": str(ticker),
            "start_move_date": str(start_date)[:10],
            "end_move_date": str(end_date)[:10],
        }

        reports_df = DatumApi.data_request("/reports", params)

        if reports_df is None or reports_df.empty:
            return pd.DataFrame(columns=["ticker", "report_date"])

        date_col = _pick_first_existing(
            reports_df,
            ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"],
        )
        if date_col is None:
            return pd.DataFrame(columns=["ticker", "report_date"])

        out = reports_df.copy()
        out["report_date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
        out["ticker"] = str(ticker).upper()
        out = out.dropna(subset=["report_date"])
        out = out.sort_values("report_date").tail(int(last_n_reports))
        return out[["ticker", "report_date"]].reset_index(drop=True)

    except Exception as e:
        print(f"Report fetch failed for {ticker}: {e}")
        return pd.DataFrame(columns=["ticker", "report_date"])


def get_reports_for_tickers(tickers_df, start_date, end_date, last_n_reports=20):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    parts = []

    for t in tqdm(tickers, desc="Reports"):
        rep = get_reports(ticker=t, last_n_reports=last_n_reports, start_date=start_date, end_date=end_date)
        if rep is not None and not rep.empty:
            parts.append(rep)

    if not parts:
        empty = pd.DataFrame(columns=["ticker", "report_date"])
        return empty, {}

    reports = pd.concat(parts, ignore_index=True).drop_duplicates(["ticker", "report_date"])
    report_days_map = reports.groupby("ticker")["report_date"].apply(set).to_dict()
    return reports, report_days_map


def get_gaps_for_tickers_excluding_reports(tickers_df, start_date, end_date, report_days_map):
    all_results = []
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()

    for t in tqdm(tickers, desc="Gaps (ex-reports)"):
        params = {
            "ticker": t,
            "start_date": str(start_date)[:10],
            "end_date": str(end_date)[:10],
            "format": "json_records",
        }

        try:
            df_gap = DatumApi.data_request("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                continue

            date_col = _pick_first_existing(df_gap, ["date", "move_date", "dt", "datetime", "day"])
            if date_col is None:
                continue

            out = df_gap.copy()
            out["ticker"] = out.get("ticker", t).astype(str).str.upper() if "ticker" in out.columns else t
            out["date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
            out["gap"] = pd.to_numeric(out.get("gap"), errors="coerce")
            out = out.dropna(subset=["date", "gap"])

            report_days = report_days_map.get(t, set())
            if report_days:
                out = out[~out["date"].isin(report_days)]

            if not out.empty:
                all_results.append(out)

        except Exception as e:
            print(f"Gap fetch failed for {t}: {e}")

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    return pd.DataFrame(columns=["ticker", "date", "gap"])


def add_rolling_sigma_cap(
    df,
    value_col,
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.95,
    min_periods=None,
):
    if min_periods is None:
        min_periods = window

    out = df.sort_values([group_col, date_col]).copy()

    def compute_sigma(s):
        x = s.shift(1)

        def f(arr):
            arr = arr[~np.isnan(arr)]
            if len(arr) < min_periods:
                return np.nan

            cap = np.quantile(np.abs(arr), cap_q)
            arr_capped = np.clip(arr, -cap, cap)

            return np.std(arr_capped, ddof=1)

        return x.rolling(window, min_periods=min_periods).apply(f, raw=True)

    out[f"{value_col}_sigma_{window}d_cap"] = (
        out.groupby(group_col)[value_col].transform(compute_sigma)
    )

    return out


# 1) Report days in the working window
reports_df, report_days_map = get_reports_for_tickers(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
)
print("Report rows:", len(reports_df))

# 2) Gaps without report days
df_gaps_all = get_gaps_for_tickers_excluding_reports(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    report_days_map=report_days_map,
)
print("Rows in gaps (without report days):", len(df_gaps_all))

Reports:   0%|          | 0/7211 [00:00<?, ?it/s]

Reports:   0%|          | 1/7211 [00:00<46:45,  2.57it/s]

Reports:   0%|          | 2/7211 [00:00<33:57,  3.54it/s]

Reports:   0%|          | 3/7211 [00:00<32:32,  3.69it/s]

Reports:   0%|          | 4/7211 [00:01<29:37,  4.05it/s]

Reports:   0%|          | 5/7211 [00:01<30:21,  3.96it/s]

Reports:   0%|          | 6/7211 [00:01<30:34,  3.93it/s]

Reports:   0%|          | 7/7211 [00:01<28:20,  4.24it/s]

Reports:   0%|          | 8/7211 [00:01<26:51,  4.47it/s]

Reports:   0%|          | 9/7211 [00:02<25:33,  4.70it/s]

Reports:   0%|          | 10/7211 [00:02<24:55,  4.81it/s]

Reports:   0%|          | 11/7211 [00:02<27:43,  4.33it/s]

Reports:   0%|          | 12/7211 [00:02<28:46,  4.17it/s]

Reports:   0%|          | 13/7211 [00:03<28:46,  4.17it/s]

Reports:   0%|          | 14/7211 [00:03<27:03,  4.43it/s]

Reports:   0%|          | 15/7211 [00:03<29:17,  4.09it/s]

Reports:   0%|          | 16/7211 [00:03<27:41,  4.33it/s]

Reports:   0%|          | 17/7211 [00:04<26:07,  4.59it/s]

Reports:   0%|          | 18/7211 [00:04<25:43,  4.66it/s]

Reports:   0%|          | 19/7211 [00:04<25:41,  4.67it/s]

Reports:   0%|          | 20/7211 [00:04<24:35,  4.87it/s]

Reports:   0%|          | 21/7211 [00:04<24:01,  4.99it/s]

Reports:   0%|          | 22/7211 [00:05<23:37,  5.07it/s]

Reports:   0%|          | 23/7211 [00:05<23:36,  5.08it/s]

Reports:   0%|          | 24/7211 [00:05<24:01,  4.98it/s]

Reports:   0%|          | 25/7211 [00:05<24:07,  4.96it/s]

Reports:   0%|          | 26/7211 [00:05<23:20,  5.13it/s]

Reports:   0%|          | 27/7211 [00:05<23:05,  5.18it/s]

Reports:   0%|          | 28/7211 [00:06<23:29,  5.09it/s]

Reports:   0%|          | 29/7211 [00:06<23:48,  5.03it/s]

Reports:   0%|          | 30/7211 [00:06<24:16,  4.93it/s]

Reports:   0%|          | 31/7211 [00:06<24:05,  4.97it/s]

Reports:   0%|          | 32/7211 [00:06<23:54,  5.00it/s]

Reports:   0%|          | 33/7211 [00:07<23:42,  5.04it/s]

Reports:   0%|          | 34/7211 [00:07<23:47,  5.03it/s]

Reports:   0%|          | 35/7211 [00:07<23:39,  5.06it/s]

Reports:   0%|          | 36/7211 [00:07<23:41,  5.05it/s]

Reports:   1%|          | 37/7211 [00:08<24:44,  4.83it/s]

Reports:   1%|          | 38/7211 [00:08<24:04,  4.97it/s]

Reports:   1%|          | 39/7211 [00:08<24:46,  4.83it/s]

Reports:   1%|          | 40/7211 [00:08<24:17,  4.92it/s]

Reports:   1%|          | 41/7211 [00:08<24:18,  4.92it/s]

Reports:   1%|          | 42/7211 [00:09<23:52,  5.00it/s]

Reports:   1%|          | 43/7211 [00:09<23:39,  5.05it/s]

Reports:   1%|          | 44/7211 [00:09<24:17,  4.92it/s]

Reports:   1%|          | 45/7211 [00:09<23:40,  5.04it/s]

Reports:   1%|          | 46/7211 [00:09<23:18,  5.12it/s]

Reports:   1%|          | 47/7211 [00:09<22:47,  5.24it/s]

Reports:   1%|          | 48/7211 [00:10<22:26,  5.32it/s]

Reports:   1%|          | 49/7211 [00:10<22:23,  5.33it/s]

Reports:   1%|          | 50/7211 [00:10<22:47,  5.24it/s]

Reports:   1%|          | 51/7211 [00:10<22:47,  5.24it/s]

Reports:   1%|          | 52/7211 [00:10<23:27,  5.09it/s]

Reports:   1%|          | 53/7211 [00:11<23:39,  5.04it/s]

Reports:   1%|          | 54/7211 [00:11<23:07,  5.16it/s]

Reports:   1%|          | 55/7211 [00:11<23:01,  5.18it/s]

Reports:   1%|          | 56/7211 [00:11<22:57,  5.19it/s]

Reports:   1%|          | 57/7211 [00:11<22:58,  5.19it/s]

Reports:   1%|          | 58/7211 [00:12<22:54,  5.20it/s]

Reports:   1%|          | 59/7211 [00:12<23:08,  5.15it/s]

Reports:   1%|          | 60/7211 [00:12<23:19,  5.11it/s]

Reports:   1%|          | 61/7211 [00:12<23:14,  5.13it/s]

Reports:   1%|          | 62/7211 [00:12<23:49,  5.00it/s]

Reports:   1%|          | 63/7211 [00:13<24:20,  4.89it/s]

Reports:   1%|          | 64/7211 [00:13<23:53,  4.99it/s]

Reports:   1%|          | 65/7211 [00:13<24:01,  4.96it/s]

Reports:   1%|          | 66/7211 [00:13<23:55,  4.98it/s]

Reports:   1%|          | 67/7211 [00:13<23:08,  5.14it/s]

Reports:   1%|          | 68/7211 [00:14<22:50,  5.21it/s]

Reports:   1%|          | 69/7211 [00:14<23:27,  5.07it/s]

Reports:   1%|          | 70/7211 [00:14<23:30,  5.06it/s]

Reports:   1%|          | 71/7211 [00:14<23:52,  4.98it/s]

Reports:   1%|          | 72/7211 [00:14<23:45,  5.01it/s]

Reports:   1%|          | 73/7211 [00:15<23:20,  5.10it/s]

Reports:   1%|          | 74/7211 [00:15<23:18,  5.10it/s]

Reports:   1%|          | 75/7211 [00:15<23:22,  5.09it/s]

Reports:   1%|          | 76/7211 [00:15<23:35,  5.04it/s]

Reports:   1%|          | 77/7211 [00:15<23:25,  5.08it/s]

Reports:   1%|          | 78/7211 [00:16<22:54,  5.19it/s]

Reports:   1%|          | 79/7211 [00:16<22:54,  5.19it/s]

Reports:   1%|          | 80/7211 [00:16<23:05,  5.15it/s]

Reports:   1%|          | 81/7211 [00:16<23:09,  5.13it/s]

Reports:   1%|          | 82/7211 [00:16<22:53,  5.19it/s]

Reports:   1%|          | 83/7211 [00:17<22:42,  5.23it/s]

Reports:   1%|          | 84/7211 [00:17<22:42,  5.23it/s]

Reports:   1%|          | 85/7211 [00:17<23:21,  5.09it/s]

Reports:   1%|          | 86/7211 [00:17<23:13,  5.11it/s]

Reports:   1%|          | 87/7211 [00:17<22:47,  5.21it/s]

Reports:   1%|          | 88/7211 [00:17<22:26,  5.29it/s]

Reports:   1%|          | 89/7211 [00:18<22:38,  5.24it/s]

Reports:   1%|          | 90/7211 [00:18<22:42,  5.23it/s]

Reports:   1%|▏         | 91/7211 [00:18<22:56,  5.17it/s]

Reports:   1%|▏         | 92/7211 [00:18<22:36,  5.25it/s]

Reports:   1%|▏         | 93/7211 [00:18<22:59,  5.16it/s]

Reports:   1%|▏         | 94/7211 [00:19<23:18,  5.09it/s]

Reports:   1%|▏         | 95/7211 [00:19<23:19,  5.08it/s]

Reports:   1%|▏         | 96/7211 [00:19<23:20,  5.08it/s]

Reports:   1%|▏         | 97/7211 [00:19<23:43,  5.00it/s]

Reports:   1%|▏         | 98/7211 [00:19<23:23,  5.07it/s]

Reports:   1%|▏         | 99/7211 [00:20<23:37,  5.02it/s]

Reports:   1%|▏         | 100/7211 [00:20<23:28,  5.05it/s]

Reports:   1%|▏         | 101/7211 [00:20<23:28,  5.05it/s]

Reports:   1%|▏         | 102/7211 [00:20<23:39,  5.01it/s]

Reports:   1%|▏         | 103/7211 [00:29<5:25:00,  2.74s/it]

Reports:   1%|▏         | 104/7211 [00:29<3:57:02,  2.00s/it]

Reports:   1%|▏         | 105/7211 [00:29<2:52:50,  1.46s/it]

Reports:   1%|▏         | 106/7211 [00:30<2:08:18,  1.08s/it]

Reports:   1%|▏         | 107/7211 [00:30<1:36:41,  1.22it/s]

Reports:   1%|▏         | 108/7211 [00:30<1:14:45,  1.58it/s]

Reports:   2%|▏         | 109/7211 [00:31<1:34:15,  1.26it/s]

Reports:   2%|▏         | 110/7211 [00:31<1:13:03,  1.62it/s]

Reports:   2%|▏         | 111/7211 [00:32<57:46,  2.05it/s]

Reports:   2%|▏         | 112/7211 [00:32<47:11,  2.51it/s]

Reports:   2%|▏         | 113/7211 [00:32<39:54,  2.96it/s]

Reports:   2%|▏         | 114/7211 [00:32<35:07,  3.37it/s]

Reports:   2%|▏         | 115/7211 [00:32<30:44,  3.85it/s]

Reports:   2%|▏         | 116/7211 [00:33<28:43,  4.12it/s]

Reports:   2%|▏         | 117/7211 [00:33<26:39,  4.44it/s]

Reports:   2%|▏         | 118/7211 [00:33<25:40,  4.61it/s]

Reports:   2%|▏         | 119/7211 [00:33<24:49,  4.76it/s]

Reports:   2%|▏         | 120/7211 [00:33<24:23,  4.85it/s]

Reports:   2%|▏         | 121/7211 [00:33<23:50,  4.96it/s]

Reports:   2%|▏         | 122/7211 [00:34<23:12,  5.09it/s]

Reports:   2%|▏         | 123/7211 [00:34<23:10,  5.10it/s]

Reports:   2%|▏         | 124/7211 [00:34<22:36,  5.23it/s]

Reports:   2%|▏         | 125/7211 [00:34<22:35,  5.23it/s]

Reports:   2%|▏         | 126/7211 [00:34<23:25,  5.04it/s]

Reports:   2%|▏         | 127/7211 [00:35<23:45,  4.97it/s]

Reports:   2%|▏         | 128/7211 [00:35<23:20,  5.06it/s]

Reports:   2%|▏         | 129/7211 [00:35<23:13,  5.08it/s]

Reports:   2%|▏         | 130/7211 [00:35<23:15,  5.07it/s]

Reports:   2%|▏         | 131/7211 [00:49<8:37:50,  4.39s/it]

Reports:   2%|▏         | 132/7211 [00:50<6:09:27,  3.13s/it]

Reports:   2%|▏         | 133/7211 [00:50<4:25:02,  2.25s/it]

Reports:   2%|▏         | 134/7211 [00:50<3:12:05,  1.63s/it]

Reports:   2%|▏         | 135/7211 [00:50<2:20:51,  1.19s/it]

Reports:   2%|▏         | 136/7211 [00:50<1:47:55,  1.09it/s]

Reports:   2%|▏         | 137/7211 [00:51<1:22:53,  1.42it/s]

Reports:   2%|▏         | 138/7211 [00:51<1:04:48,  1.82it/s]

Reports:   2%|▏         | 139/7211 [00:51<52:15,  2.26it/s]

Reports:   2%|▏         | 140/7211 [00:51<43:57,  2.68it/s]

Reports:   2%|▏         | 141/7211 [00:51<38:15,  3.08it/s]

Reports:   2%|▏         | 142/7211 [00:52<33:55,  3.47it/s]

Reports:   2%|▏         | 143/7211 [00:52<30:14,  3.90it/s]

Reports:   2%|▏         | 144/7211 [00:52<27:58,  4.21it/s]

Reports:   2%|▏         | 145/7211 [00:52<26:00,  4.53it/s]

Reports:   2%|▏         | 146/7211 [00:52<24:42,  4.77it/s]

Reports:   2%|▏         | 147/7211 [00:53<23:53,  4.93it/s]

Reports:   2%|▏         | 148/7211 [00:53<23:23,  5.03it/s]

Reports:   2%|▏         | 149/7211 [00:53<23:23,  5.03it/s]

Reports:   2%|▏         | 150/7211 [00:53<24:15,  4.85it/s]

Reports:   2%|▏         | 151/7211 [00:53<23:30,  5.01it/s]

Reports:   2%|▏         | 152/7211 [00:54<23:44,  4.96it/s]

Reports:   2%|▏         | 153/7211 [01:19<14:59:10,  7.64s/it]

Reports:   2%|▏         | 154/7211 [01:19<10:35:54,  5.41s/it]

Reports:   2%|▏         | 155/7211 [01:19<7:31:37,  3.84s/it]

Reports:   2%|▏         | 156/7211 [01:19<5:22:52,  2.75s/it]

Reports:   2%|▏         | 157/7211 [01:19<3:52:42,  1.98s/it]

Reports:   2%|▏         | 158/7211 [01:20<2:50:03,  1.45s/it]

Reports:   2%|▏         | 159/7211 [01:20<2:05:42,  1.07s/it]

Reports:   2%|▏         | 160/7211 [01:20<1:34:34,  1.24it/s]

Reports:   2%|▏         | 161/7211 [01:20<1:13:26,  1.60it/s]

Reports:   2%|▏         | 162/7211 [01:20<58:23,  2.01it/s]

Reports:   2%|▏         | 163/7211 [01:20<47:15,  2.49it/s]

Reports:   2%|▏         | 164/7211 [01:21<39:29,  2.97it/s]

Reports:   2%|▏         | 165/7211 [01:21<34:28,  3.41it/s]

Reports:   2%|▏         | 166/7211 [01:21<31:38,  3.71it/s]

Reports:   2%|▏         | 167/7211 [01:21<30:36,  3.84it/s]

Reports:   2%|▏         | 168/7211 [01:22<28:17,  4.15it/s]

Reports:   2%|▏         | 169/7211 [01:22<26:29,  4.43it/s]

Reports:   2%|▏         | 170/7211 [01:22<25:30,  4.60it/s]

Reports:   2%|▏         | 171/7211 [01:22<24:30,  4.79it/s]

Reports:   2%|▏         | 172/7211 [01:22<24:03,  4.88it/s]

Reports:   2%|▏         | 173/7211 [01:22<24:04,  4.87it/s]

Reports:   2%|▏         | 174/7211 [01:23<23:58,  4.89it/s]

Reports:   2%|▏         | 175/7211 [01:23<23:15,  5.04it/s]

Reports:   2%|▏         | 176/7211 [01:23<23:12,  5.05it/s]

Reports:   2%|▏         | 177/7211 [01:23<22:47,  5.14it/s]

Reports:   2%|▏         | 178/7211 [01:23<22:24,  5.23it/s]

Reports:   2%|▏         | 179/7211 [01:24<22:22,  5.24it/s]

Reports:   2%|▏         | 180/7211 [01:24<22:01,  5.32it/s]

Reports:   3%|▎         | 181/7211 [01:24<22:29,  5.21it/s]

Reports:   3%|▎         | 182/7211 [01:24<22:41,  5.16it/s]

Reports:   3%|▎         | 183/7211 [01:24<22:23,  5.23it/s]

Reports:   3%|▎         | 184/7211 [01:25<22:30,  5.20it/s]

Reports:   3%|▎         | 185/7211 [01:25<22:34,  5.19it/s]

Reports:   3%|▎         | 186/7211 [01:25<22:29,  5.20it/s]

Reports:   3%|▎         | 187/7211 [01:25<22:04,  5.30it/s]

Reports:   3%|▎         | 188/7211 [01:25<22:07,  5.29it/s]

Reports:   3%|▎         | 189/7211 [01:26<21:59,  5.32it/s]

Reports:   3%|▎         | 190/7211 [01:26<22:23,  5.22it/s]

Reports:   3%|▎         | 191/7211 [01:26<22:25,  5.22it/s]

Reports:   3%|▎         | 192/7211 [01:26<22:47,  5.13it/s]

Reports:   3%|▎         | 193/7211 [01:26<22:20,  5.23it/s]

Reports:   3%|▎         | 194/7211 [01:27<22:17,  5.25it/s]

Reports:   3%|▎         | 195/7211 [01:27<22:57,  5.09it/s]

Reports:   3%|▎         | 196/7211 [01:27<22:34,  5.18it/s]

Reports:   3%|▎         | 197/7211 [01:27<22:44,  5.14it/s]

Reports:   3%|▎         | 198/7211 [01:27<22:19,  5.23it/s]

Reports:   3%|▎         | 199/7211 [01:27<22:16,  5.25it/s]

Reports:   3%|▎         | 200/7211 [01:28<22:07,  5.28it/s]

Reports:   3%|▎         | 201/7211 [01:28<22:12,  5.26it/s]

Reports:   3%|▎         | 202/7211 [01:28<22:43,  5.14it/s]

Reports:   3%|▎         | 203/7211 [01:28<22:51,  5.11it/s]

Reports:   3%|▎         | 204/7211 [01:28<22:29,  5.19it/s]

Reports:   3%|▎         | 205/7211 [01:29<22:19,  5.23it/s]

Reports:   3%|▎         | 206/7211 [01:29<22:03,  5.29it/s]

Reports:   3%|▎         | 207/7211 [01:29<22:38,  5.15it/s]

Reports:   3%|▎         | 208/7211 [01:29<22:23,  5.21it/s]

Reports:   3%|▎         | 209/7211 [01:29<22:38,  5.16it/s]

Reports:   3%|▎         | 210/7211 [01:30<22:43,  5.13it/s]

Reports:   3%|▎         | 211/7211 [01:30<22:21,  5.22it/s]

Reports:   3%|▎         | 212/7211 [01:30<23:07,  5.04it/s]

Reports:   3%|▎         | 213/7211 [01:30<23:10,  5.03it/s]

Reports:   3%|▎         | 214/7211 [01:30<23:05,  5.05it/s]

Reports:   3%|▎         | 215/7211 [01:31<23:19,  5.00it/s]

Reports:   3%|▎         | 216/7211 [01:31<22:51,  5.10it/s]

Reports:   3%|▎         | 217/7211 [01:31<22:56,  5.08it/s]

Reports:   3%|▎         | 218/7211 [01:31<23:26,  4.97it/s]

Reports:   3%|▎         | 219/7211 [01:31<23:24,  4.98it/s]

Reports:   3%|▎         | 220/7211 [01:32<23:08,  5.03it/s]

Reports:   3%|▎         | 221/7211 [01:32<22:50,  5.10it/s]

Reports:   3%|▎         | 222/7211 [01:32<22:52,  5.09it/s]

Reports:   3%|▎         | 223/7211 [01:32<23:04,  5.05it/s]

Reports:   3%|▎         | 224/7211 [01:32<23:18,  4.99it/s]

Reports:   3%|▎         | 225/7211 [01:33<22:39,  5.14it/s]

Reports:   3%|▎         | 226/7211 [01:33<22:15,  5.23it/s]

Reports:   3%|▎         | 227/7211 [01:33<22:14,  5.23it/s]

Reports:   3%|▎         | 228/7211 [01:33<23:01,  5.05it/s]

Reports:   3%|▎         | 229/7211 [01:33<23:17,  5.00it/s]

Reports:   3%|▎         | 230/7211 [01:34<23:26,  4.96it/s]

Reports:   3%|▎         | 231/7211 [01:34<22:49,  5.10it/s]

Reports:   3%|▎         | 232/7211 [01:34<22:31,  5.16it/s]

Reports:   3%|▎         | 233/7211 [01:34<23:18,  4.99it/s]

Reports:   3%|▎         | 234/7211 [01:34<22:56,  5.07it/s]

Reports:   3%|▎         | 235/7211 [01:35<22:37,  5.14it/s]

Reports:   3%|▎         | 236/7211 [01:35<22:37,  5.14it/s]

Reports:   3%|▎         | 237/7211 [01:35<22:17,  5.21it/s]

Reports:   3%|▎         | 238/7211 [01:35<22:53,  5.08it/s]

Reports:   3%|▎         | 239/7211 [01:35<22:33,  5.15it/s]

Reports:   3%|▎         | 240/7211 [01:35<22:35,  5.14it/s]

Reports:   3%|▎         | 241/7211 [01:36<22:16,  5.22it/s]

Reports:   3%|▎         | 242/7211 [01:36<22:10,  5.24it/s]

Reports:   3%|▎         | 243/7211 [01:38<1:27:00,  1.33it/s]

Reports:   3%|▎         | 244/7211 [01:38<1:08:08,  1.70it/s]

Reports:   3%|▎         | 245/7211 [01:38<54:17,  2.14it/s]

Reports:   3%|▎         | 246/7211 [01:39<44:34,  2.60it/s]

Reports:   3%|▎         | 247/7211 [01:39<38:04,  3.05it/s]

Reports:   3%|▎         | 248/7211 [01:39<33:08,  3.50it/s]

Reports:   3%|▎         | 249/7211 [01:39<30:40,  3.78it/s]

Reports:   3%|▎         | 250/7211 [01:39<28:07,  4.12it/s]

Reports:   3%|▎         | 251/7211 [01:39<26:14,  4.42it/s]

Reports:   3%|▎         | 252/7211 [01:40<25:14,  4.59it/s]

Reports:   4%|▎         | 253/7211 [01:40<24:46,  4.68it/s]

Reports:   4%|▎         | 254/7211 [01:40<23:57,  4.84it/s]

Reports:   4%|▎         | 255/7211 [01:40<23:28,  4.94it/s]

Reports:   4%|▎         | 256/7211 [01:40<23:18,  4.97it/s]

Reports:   4%|▎         | 257/7211 [01:41<22:51,  5.07it/s]

Reports:   4%|▎         | 258/7211 [01:41<22:48,  5.08it/s]

Reports:   4%|▎         | 259/7211 [01:41<22:36,  5.13it/s]

Reports:   4%|▎         | 260/7211 [01:41<22:39,  5.11it/s]

Reports:   4%|▎         | 261/7211 [01:41<22:46,  5.09it/s]

Reports:   4%|▎         | 262/7211 [01:42<23:10,  5.00it/s]

Reports:   4%|▎         | 263/7211 [01:42<22:53,  5.06it/s]

Reports:   4%|▎         | 264/7211 [01:42<22:49,  5.07it/s]

Reports:   4%|▎         | 265/7211 [01:42<22:28,  5.15it/s]

Reports:   4%|▎         | 266/7211 [01:42<22:24,  5.16it/s]

Reports:   4%|▎         | 267/7211 [01:43<22:18,  5.19it/s]

Reports:   4%|▎         | 268/7211 [01:43<22:00,  5.26it/s]

Reports:   4%|▎         | 269/7211 [01:43<21:48,  5.31it/s]

Reports:   4%|▎         | 270/7211 [01:43<22:22,  5.17it/s]

Reports:   4%|▍         | 271/7211 [01:43<22:49,  5.07it/s]

Reports:   4%|▍         | 272/7211 [01:44<24:30,  4.72it/s]

Reports:   4%|▍         | 273/7211 [01:44<23:41,  4.88it/s]

Reports:   4%|▍         | 274/7211 [01:44<22:46,  5.08it/s]

Reports:   4%|▍         | 275/7211 [01:44<23:13,  4.98it/s]

Reports:   4%|▍         | 276/7211 [01:44<22:51,  5.06it/s]

Reports:   4%|▍         | 277/7211 [01:45<22:45,  5.08it/s]

Reports:   4%|▍         | 278/7211 [01:45<22:56,  5.04it/s]

Reports:   4%|▍         | 279/7211 [01:45<22:45,  5.08it/s]

Reports:   4%|▍         | 280/7211 [01:45<22:48,  5.06it/s]

Reports:   4%|▍         | 281/7211 [01:45<22:13,  5.20it/s]

Reports:   4%|▍         | 282/7211 [01:46<22:21,  5.17it/s]

Reports:   4%|▍         | 283/7211 [01:46<22:34,  5.12it/s]

Reports:   4%|▍         | 284/7211 [01:46<22:18,  5.17it/s]

Reports:   4%|▍         | 285/7211 [01:46<22:21,  5.16it/s]

Reports:   4%|▍         | 286/7211 [01:46<22:32,  5.12it/s]

Reports:   4%|▍         | 287/7211 [01:47<22:09,  5.21it/s]

Reports:   4%|▍         | 288/7211 [01:47<22:18,  5.17it/s]

Reports:   4%|▍         | 289/7211 [01:47<22:04,  5.23it/s]

Reports:   4%|▍         | 290/7211 [01:47<21:43,  5.31it/s]

Reports:   4%|▍         | 291/7211 [01:47<21:38,  5.33it/s]

Reports:   4%|▍         | 292/7211 [01:47<21:26,  5.38it/s]

Reports:   4%|▍         | 293/7211 [01:48<21:27,  5.37it/s]

Reports:   4%|▍         | 294/7211 [01:48<21:58,  5.24it/s]

Reports:   4%|▍         | 295/7211 [01:48<22:46,  5.06it/s]

Reports:   4%|▍         | 296/7211 [01:48<23:20,  4.94it/s]

Reports:   4%|▍         | 297/7211 [01:48<23:07,  4.98it/s]

Reports:   4%|▍         | 298/7211 [01:49<22:49,  5.05it/s]

Reports:   4%|▍         | 299/7211 [01:49<22:43,  5.07it/s]

Reports:   4%|▍         | 300/7211 [01:49<23:07,  4.98it/s]

Reports:   4%|▍         | 301/7211 [01:49<22:43,  5.07it/s]

Reports:   4%|▍         | 302/7211 [01:49<23:05,  4.99it/s]

Reports:   4%|▍         | 303/7211 [01:50<22:34,  5.10it/s]

Reports:   4%|▍         | 304/7211 [01:50<23:41,  4.86it/s]

Reports:   4%|▍         | 305/7211 [01:50<23:10,  4.97it/s]

Reports:   4%|▍         | 306/7211 [01:50<23:30,  4.89it/s]

Reports:   4%|▍         | 307/7211 [01:50<22:50,  5.04it/s]

Reports:   4%|▍         | 308/7211 [01:51<22:26,  5.13it/s]

Reports:   4%|▍         | 309/7211 [01:51<22:26,  5.13it/s]

Reports:   4%|▍         | 310/7211 [01:51<22:27,  5.12it/s]

Reports:   4%|▍         | 311/7211 [01:51<22:26,  5.12it/s]

Reports:   4%|▍         | 312/7211 [01:51<22:43,  5.06it/s]

Reports:   4%|▍         | 313/7211 [01:52<22:30,  5.11it/s]

Reports:   4%|▍         | 314/7211 [01:52<22:49,  5.03it/s]

Reports:   4%|▍         | 315/7211 [01:52<22:29,  5.11it/s]

Reports:   4%|▍         | 316/7211 [01:52<22:43,  5.06it/s]

Reports:   4%|▍         | 317/7211 [01:52<22:58,  5.00it/s]

Reports:   4%|▍         | 318/7211 [01:53<22:49,  5.03it/s]

Reports:   4%|▍         | 319/7211 [01:53<22:43,  5.05it/s]

Reports:   4%|▍         | 320/7211 [01:53<22:17,  5.15it/s]

Reports:   4%|▍         | 321/7211 [01:53<22:34,  5.09it/s]

Reports:   4%|▍         | 322/7211 [01:53<23:06,  4.97it/s]

Reports:   4%|▍         | 323/7211 [01:54<23:19,  4.92it/s]

Reports:   4%|▍         | 324/7211 [01:54<22:58,  5.00it/s]

Reports:   5%|▍         | 325/7211 [01:54<22:49,  5.03it/s]

Reports:   5%|▍         | 326/7211 [01:54<22:52,  5.02it/s]

Reports:   5%|▍         | 327/7211 [01:54<22:43,  5.05it/s]

Reports:   5%|▍         | 328/7211 [01:55<22:36,  5.07it/s]

Reports:   5%|▍         | 329/7211 [01:55<22:49,  5.03it/s]

Reports:   5%|▍         | 330/7211 [01:55<23:59,  4.78it/s]

Reports:   5%|▍         | 331/7211 [01:55<23:39,  4.85it/s]

Reports:   5%|▍         | 332/7211 [01:55<23:33,  4.87it/s]

Reports:   5%|▍         | 333/7211 [01:56<22:47,  5.03it/s]

Reports:   5%|▍         | 334/7211 [01:56<22:48,  5.03it/s]

Reports:   5%|▍         | 335/7211 [01:56<22:26,  5.11it/s]

Reports:   5%|▍         | 336/7211 [01:56<21:57,  5.22it/s]

Reports:   5%|▍         | 337/7211 [01:56<22:19,  5.13it/s]

Reports:   5%|▍         | 338/7211 [01:57<22:21,  5.12it/s]

Reports:   5%|▍         | 339/7211 [01:57<22:07,  5.18it/s]

Reports:   5%|▍         | 340/7211 [01:57<22:24,  5.11it/s]

Reports:   5%|▍         | 341/7211 [01:57<22:31,  5.08it/s]

Reports:   5%|▍         | 342/7211 [01:57<22:04,  5.19it/s]

Reports:   5%|▍         | 343/7211 [01:58<22:17,  5.13it/s]

Reports:   5%|▍         | 344/7211 [01:58<22:09,  5.16it/s]

Reports:   5%|▍         | 345/7211 [01:58<22:23,  5.11it/s]

Reports:   5%|▍         | 346/7211 [01:58<22:04,  5.18it/s]

Reports:   5%|▍         | 347/7211 [01:58<21:59,  5.20it/s]

Reports:   5%|▍         | 348/7211 [01:59<21:44,  5.26it/s]

Reports:   5%|▍         | 349/7211 [01:59<22:12,  5.15it/s]

Reports:   5%|▍         | 350/7211 [01:59<21:44,  5.26it/s]

Reports:   5%|▍         | 351/7211 [01:59<21:42,  5.27it/s]

Reports:   5%|▍         | 352/7211 [01:59<21:48,  5.24it/s]

Reports:   5%|▍         | 353/7211 [01:59<21:35,  5.29it/s]

Reports:   5%|▍         | 354/7211 [02:00<21:39,  5.28it/s]

Reports:   5%|▍         | 355/7211 [02:00<21:33,  5.30it/s]

Reports:   5%|▍         | 356/7211 [02:00<21:22,  5.34it/s]

Reports:   5%|▍         | 357/7211 [02:00<21:35,  5.29it/s]

Reports:   5%|▍         | 358/7211 [02:00<22:11,  5.15it/s]

Reports:   5%|▍         | 359/7211 [02:01<22:08,  5.16it/s]

Reports:   5%|▍         | 360/7211 [02:01<22:16,  5.12it/s]

Reports:   5%|▌         | 361/7211 [02:01<21:54,  5.21it/s]

Reports:   5%|▌         | 362/7211 [02:01<21:49,  5.23it/s]

Reports:   5%|▌         | 363/7211 [02:01<22:09,  5.15it/s]

Reports:   5%|▌         | 364/7211 [02:02<22:13,  5.13it/s]

Reports:   5%|▌         | 365/7211 [02:02<22:52,  4.99it/s]

Reports:   5%|▌         | 366/7211 [02:02<23:03,  4.95it/s]

Reports:   5%|▌         | 367/7211 [02:02<22:29,  5.07it/s]

Reports:   5%|▌         | 368/7211 [02:02<22:52,  4.99it/s]

Reports:   5%|▌         | 369/7211 [02:03<22:47,  5.00it/s]

Reports:   5%|▌         | 370/7211 [02:03<22:47,  5.00it/s]

Reports:   5%|▌         | 371/7211 [02:03<22:31,  5.06it/s]

Reports:   5%|▌         | 372/7211 [02:03<22:23,  5.09it/s]

Reports:   5%|▌         | 373/7211 [02:03<22:05,  5.16it/s]

Reports:   5%|▌         | 374/7211 [02:04<22:09,  5.14it/s]

Reports:   5%|▌         | 375/7211 [02:04<21:52,  5.21it/s]

Reports:   5%|▌         | 376/7211 [02:04<22:13,  5.13it/s]

Reports:   5%|▌         | 377/7211 [02:04<22:14,  5.12it/s]

Reports:   5%|▌         | 378/7211 [02:04<22:24,  5.08it/s]

Reports:   5%|▌         | 379/7211 [02:05<22:09,  5.14it/s]

Reports:   5%|▌         | 380/7211 [02:05<22:17,  5.11it/s]

Reports:   5%|▌         | 381/7211 [02:05<22:37,  5.03it/s]

Reports:   5%|▌         | 382/7211 [02:05<22:21,  5.09it/s]

Reports:   5%|▌         | 383/7211 [02:05<21:50,  5.21it/s]

Reports:   5%|▌         | 384/7211 [02:06<21:44,  5.23it/s]

Reports:   5%|▌         | 385/7211 [02:06<22:36,  5.03it/s]

Reports:   5%|▌         | 386/7211 [02:06<22:34,  5.04it/s]

Reports:   5%|▌         | 387/7211 [02:06<23:02,  4.94it/s]

Reports:   5%|▌         | 388/7211 [02:06<22:51,  4.98it/s]

Reports:   5%|▌         | 389/7211 [02:07<22:29,  5.06it/s]

Reports:   5%|▌         | 390/7211 [02:07<22:31,  5.05it/s]

Reports:   5%|▌         | 391/7211 [02:07<22:20,  5.09it/s]

Reports:   5%|▌         | 392/7211 [02:07<22:59,  4.94it/s]

Reports:   5%|▌         | 393/7211 [02:07<23:13,  4.89it/s]

Reports:   5%|▌         | 394/7211 [02:08<23:08,  4.91it/s]

Reports:   5%|▌         | 395/7211 [02:08<22:36,  5.03it/s]

Reports:   5%|▌         | 396/7211 [02:08<23:10,  4.90it/s]

Reports:   6%|▌         | 397/7211 [02:08<23:25,  4.85it/s]

Reports:   6%|▌         | 398/7211 [02:08<22:49,  4.98it/s]

Reports:   6%|▌         | 399/7211 [02:09<22:19,  5.09it/s]

Reports:   6%|▌         | 400/7211 [02:09<21:54,  5.18it/s]

Reports:   6%|▌         | 401/7211 [02:09<22:17,  5.09it/s]

Reports:   6%|▌         | 402/7211 [02:09<22:46,  4.98it/s]

Reports:   6%|▌         | 403/7211 [02:09<23:11,  4.89it/s]

Reports:   6%|▌         | 404/7211 [02:10<24:21,  4.66it/s]

Reports:   6%|▌         | 405/7211 [02:10<26:24,  4.29it/s]

Reports:   6%|▌         | 406/7211 [02:10<25:34,  4.44it/s]

Reports:   6%|▌         | 407/7211 [02:10<24:24,  4.65it/s]

Reports:   6%|▌         | 408/7211 [02:10<23:39,  4.79it/s]

Reports:   6%|▌         | 409/7211 [02:11<23:00,  4.93it/s]

Reports:   6%|▌         | 410/7211 [02:11<22:42,  4.99it/s]

Reports:   6%|▌         | 411/7211 [02:11<22:52,  4.96it/s]

Reports:   6%|▌         | 412/7211 [02:11<22:33,  5.02it/s]

Reports:   6%|▌         | 413/7211 [02:11<22:49,  4.96it/s]

Reports:   6%|▌         | 414/7211 [02:12<22:28,  5.04it/s]

Reports:   6%|▌         | 415/7211 [02:12<22:25,  5.05it/s]

Reports:   6%|▌         | 416/7211 [02:12<21:58,  5.15it/s]

Reports:   6%|▌         | 417/7211 [02:12<22:14,  5.09it/s]

Reports:   6%|▌         | 418/7211 [02:12<24:12,  4.68it/s]

Reports:   6%|▌         | 419/7211 [02:13<29:50,  3.79it/s]

Reports:   6%|▌         | 420/7211 [02:13<29:18,  3.86it/s]

Reports:   6%|▌         | 421/7211 [02:13<28:58,  3.90it/s]

Reports:   6%|▌         | 422/7211 [02:14<26:27,  4.28it/s]

Reports:   6%|▌         | 423/7211 [02:14<25:00,  4.52it/s]

Reports:   6%|▌         | 424/7211 [02:14<24:21,  4.64it/s]

Reports:   6%|▌         | 425/7211 [02:14<23:50,  4.75it/s]

Reports:   6%|▌         | 426/7211 [02:14<23:23,  4.83it/s]

Reports:   6%|▌         | 427/7211 [02:15<22:56,  4.93it/s]

Reports:   6%|▌         | 428/7211 [02:15<22:18,  5.07it/s]

Reports:   6%|▌         | 429/7211 [02:15<21:58,  5.14it/s]

Reports:   6%|▌         | 430/7211 [02:15<21:54,  5.16it/s]

Reports:   6%|▌         | 431/7211 [02:15<21:48,  5.18it/s]

Reports:   6%|▌         | 432/7211 [02:15<21:45,  5.19it/s]

Reports:   6%|▌         | 433/7211 [02:16<21:53,  5.16it/s]

Reports:   6%|▌         | 434/7211 [02:16<22:32,  5.01it/s]

Reports:   6%|▌         | 435/7211 [02:16<22:45,  4.96it/s]

Reports:   6%|▌         | 436/7211 [02:16<22:46,  4.96it/s]

Reports:   6%|▌         | 437/7211 [02:16<22:18,  5.06it/s]

Reports:   6%|▌         | 438/7211 [02:17<22:11,  5.09it/s]

Reports:   6%|▌         | 439/7211 [02:17<22:40,  4.98it/s]

Reports:   6%|▌         | 440/7211 [02:17<22:50,  4.94it/s]

Reports:   6%|▌         | 441/7211 [02:17<22:57,  4.91it/s]

Reports:   6%|▌         | 442/7211 [02:17<22:31,  5.01it/s]

Reports:   6%|▌         | 443/7211 [02:18<22:25,  5.03it/s]

Reports:   6%|▌         | 444/7211 [02:18<22:18,  5.05it/s]

Reports:   6%|▌         | 445/7211 [02:18<22:21,  5.04it/s]

Reports:   6%|▌         | 446/7211 [02:18<22:00,  5.12it/s]

Reports:   6%|▌         | 447/7211 [02:18<21:51,  5.16it/s]

Reports:   6%|▌         | 448/7211 [02:19<21:59,  5.12it/s]

Reports:   6%|▌         | 449/7211 [02:19<22:25,  5.03it/s]

Reports:   6%|▌         | 450/7211 [02:19<22:17,  5.06it/s]

Reports:   6%|▋         | 451/7211 [02:19<22:07,  5.09it/s]

Reports:   6%|▋         | 452/7211 [02:19<21:58,  5.13it/s]

Reports:   6%|▋         | 453/7211 [02:20<21:43,  5.18it/s]

Reports:   6%|▋         | 454/7211 [02:20<21:41,  5.19it/s]

Reports:   6%|▋         | 455/7211 [02:20<22:00,  5.12it/s]

Reports:   6%|▋         | 456/7211 [02:20<21:46,  5.17it/s]

Reports:   6%|▋         | 457/7211 [02:20<22:00,  5.12it/s]

Reports:   6%|▋         | 458/7211 [02:21<21:58,  5.12it/s]

Reports:   6%|▋         | 459/7211 [02:21<21:41,  5.19it/s]

Reports:   6%|▋         | 460/7211 [02:21<21:53,  5.14it/s]

Reports:   6%|▋         | 461/7211 [02:21<21:32,  5.22it/s]

Reports:   6%|▋         | 462/7211 [02:21<21:17,  5.28it/s]

Reports:   6%|▋         | 463/7211 [02:22<21:16,  5.29it/s]

Reports:   6%|▋         | 464/7211 [02:22<22:03,  5.10it/s]

Reports:   6%|▋         | 465/7211 [02:22<21:58,  5.12it/s]

Reports:   6%|▋         | 466/7211 [02:22<21:51,  5.14it/s]

Reports:   6%|▋         | 467/7211 [02:22<22:10,  5.07it/s]

Reports:   6%|▋         | 468/7211 [02:23<21:59,  5.11it/s]

Reports:   7%|▋         | 469/7211 [02:23<22:43,  4.94it/s]

Reports:   7%|▋         | 470/7211 [02:23<22:15,  5.05it/s]

Reports:   7%|▋         | 471/7211 [02:23<22:15,  5.05it/s]

Reports:   7%|▋         | 472/7211 [02:23<21:56,  5.12it/s]

Reports:   7%|▋         | 473/7211 [02:24<22:08,  5.07it/s]

Reports:   7%|▋         | 474/7211 [02:24<21:31,  5.22it/s]

Reports:   7%|▋         | 475/7211 [02:24<22:09,  5.07it/s]

Reports:   7%|▋         | 476/7211 [02:24<22:08,  5.07it/s]

Reports:   7%|▋         | 477/7211 [02:24<22:16,  5.04it/s]

Reports:   7%|▋         | 478/7211 [02:25<22:38,  4.96it/s]

Reports:   7%|▋         | 479/7211 [02:25<22:49,  4.92it/s]

Reports:   7%|▋         | 480/7211 [02:25<22:54,  4.90it/s]

Reports:   7%|▋         | 481/7211 [02:25<22:27,  5.00it/s]

Reports:   7%|▋         | 482/7211 [02:25<22:38,  4.95it/s]

Reports:   7%|▋         | 483/7211 [02:26<22:59,  4.88it/s]

Reports:   7%|▋         | 484/7211 [02:26<22:14,  5.04it/s]

Reports:   7%|▋         | 485/7211 [02:26<22:44,  4.93it/s]

Reports:   7%|▋         | 486/7211 [02:26<22:05,  5.07it/s]

Reports:   7%|▋         | 487/7211 [02:26<22:01,  5.09it/s]

Reports:   7%|▋         | 488/7211 [02:27<21:47,  5.14it/s]

Reports:   7%|▋         | 489/7211 [02:27<21:20,  5.25it/s]

Reports:   7%|▋         | 490/7211 [02:27<21:10,  5.29it/s]

Reports:   7%|▋         | 491/7211 [02:27<21:46,  5.14it/s]

Reports:   7%|▋         | 492/7211 [02:27<22:09,  5.05it/s]

Reports:   7%|▋         | 493/7211 [02:28<21:53,  5.11it/s]

Reports:   7%|▋         | 494/7211 [02:28<22:14,  5.04it/s]

Reports:   7%|▋         | 495/7211 [02:28<21:56,  5.10it/s]

Reports:   7%|▋         | 496/7211 [02:28<21:45,  5.14it/s]

Reports:   7%|▋         | 497/7211 [02:28<22:08,  5.05it/s]

Reports:   7%|▋         | 498/7211 [02:28<21:20,  5.24it/s]

Reports:   7%|▋         | 499/7211 [02:29<21:59,  5.09it/s]

Reports:   7%|▋         | 500/7211 [02:29<21:49,  5.13it/s]

Reports:   7%|▋         | 501/7211 [02:29<21:40,  5.16it/s]

Reports:   7%|▋         | 502/7211 [02:29<22:02,  5.07it/s]

Reports:   7%|▋         | 503/7211 [02:29<22:27,  4.98it/s]

Reports:   7%|▋         | 504/7211 [02:30<22:44,  4.91it/s]

Reports:   7%|▋         | 505/7211 [02:30<22:14,  5.03it/s]

Reports:   7%|▋         | 506/7211 [02:30<21:41,  5.15it/s]

Reports:   7%|▋         | 507/7211 [02:30<22:01,  5.07it/s]

Reports:   7%|▋         | 508/7211 [02:30<22:07,  5.05it/s]

Reports:   7%|▋         | 509/7211 [02:31<21:58,  5.08it/s]

Reports:   7%|▋         | 510/7211 [02:31<21:57,  5.09it/s]

Reports:   7%|▋         | 511/7211 [02:31<22:07,  5.05it/s]

Reports:   7%|▋         | 512/7211 [02:31<22:26,  4.97it/s]

Reports:   7%|▋         | 513/7211 [02:31<22:14,  5.02it/s]

Reports:   7%|▋         | 514/7211 [02:32<22:28,  4.97it/s]

Reports:   7%|▋         | 515/7211 [02:32<22:32,  4.95it/s]

Reports:   7%|▋         | 516/7211 [02:32<22:16,  5.01it/s]

Reports:   7%|▋         | 517/7211 [02:32<21:51,  5.11it/s]

Reports:   7%|▋         | 518/7211 [02:32<21:26,  5.20it/s]

Reports:   7%|▋         | 519/7211 [02:33<21:18,  5.24it/s]

Reports:   7%|▋         | 520/7211 [02:33<21:18,  5.23it/s]

Reports:   7%|▋         | 521/7211 [02:33<21:28,  5.19it/s]

Reports:   7%|▋         | 522/7211 [02:33<21:34,  5.17it/s]

Reports:   7%|▋         | 523/7211 [02:33<22:23,  4.98it/s]

Reports:   7%|▋         | 524/7211 [02:34<22:16,  5.00it/s]

Reports:   7%|▋         | 525/7211 [02:34<22:32,  4.94it/s]

Reports:   7%|▋         | 526/7211 [02:34<22:37,  4.93it/s]

Reports:   7%|▋         | 527/7211 [02:34<22:37,  4.93it/s]

Reports:   7%|▋         | 528/7211 [02:34<22:25,  4.97it/s]

Reports:   7%|▋         | 529/7211 [02:35<22:17,  4.99it/s]

Reports:   7%|▋         | 530/7211 [02:35<21:59,  5.06it/s]

Reports:   7%|▋         | 531/7211 [02:35<22:16,  5.00it/s]

Reports:   7%|▋         | 532/7211 [02:35<22:08,  5.03it/s]

Reports:   7%|▋         | 533/7211 [02:35<22:20,  4.98it/s]

Reports:   7%|▋         | 534/7211 [02:36<21:47,  5.11it/s]

Reports:   7%|▋         | 535/7211 [02:36<21:38,  5.14it/s]

Reports:   7%|▋         | 536/7211 [02:36<21:24,  5.20it/s]

Reports:   7%|▋         | 537/7211 [02:36<21:13,  5.24it/s]

Reports:   7%|▋         | 538/7211 [02:36<21:20,  5.21it/s]

Reports:   7%|▋         | 539/7211 [02:37<21:25,  5.19it/s]

Reports:   7%|▋         | 540/7211 [02:37<22:04,  5.04it/s]

Reports:   8%|▊         | 541/7211 [02:37<22:13,  5.00it/s]

Reports:   8%|▊         | 542/7211 [02:37<22:32,  4.93it/s]

Reports:   8%|▊         | 543/7211 [02:37<22:24,  4.96it/s]

Reports:   8%|▊         | 544/7211 [02:38<22:43,  4.89it/s]

Reports:   8%|▊         | 545/7211 [02:38<22:38,  4.91it/s]

Reports:   8%|▊         | 546/7211 [02:38<22:42,  4.89it/s]

Reports:   8%|▊         | 547/7211 [02:38<22:45,  4.88it/s]

Reports:   8%|▊         | 548/7211 [02:38<23:18,  4.76it/s]

Reports:   8%|▊         | 549/7211 [02:39<22:57,  4.84it/s]

Reports:   8%|▊         | 550/7211 [02:39<22:49,  4.86it/s]

Reports:   8%|▊         | 551/7211 [02:39<22:31,  4.93it/s]

Reports:   8%|▊         | 552/7211 [02:39<22:32,  4.92it/s]

Reports:   8%|▊         | 553/7211 [02:39<22:57,  4.83it/s]

Reports:   8%|▊         | 554/7211 [02:40<22:04,  5.03it/s]

Reports:   8%|▊         | 555/7211 [02:40<21:40,  5.12it/s]

Reports:   8%|▊         | 556/7211 [02:40<21:43,  5.10it/s]

Reports:   8%|▊         | 557/7211 [02:40<21:56,  5.05it/s]

Reports:   8%|▊         | 558/7211 [02:40<22:27,  4.94it/s]

Reports:   8%|▊         | 559/7211 [02:41<22:28,  4.93it/s]

Reports:   8%|▊         | 560/7211 [02:41<22:07,  5.01it/s]

Reports:   8%|▊         | 561/7211 [02:41<22:06,  5.01it/s]

Reports:   8%|▊         | 562/7211 [02:41<22:21,  4.96it/s]

Reports:   8%|▊         | 563/7211 [02:41<22:08,  5.01it/s]

Reports:   8%|▊         | 564/7211 [02:42<22:21,  4.96it/s]

Reports:   8%|▊         | 565/7211 [02:42<22:55,  4.83it/s]

Reports:   8%|▊         | 566/7211 [02:42<22:40,  4.89it/s]

Reports:   8%|▊         | 567/7211 [02:42<22:31,  4.92it/s]

Reports:   8%|▊         | 568/7211 [02:42<22:23,  4.94it/s]

Reports:   8%|▊         | 569/7211 [02:43<22:34,  4.90it/s]

Reports:   8%|▊         | 570/7211 [02:43<22:11,  4.99it/s]

Reports:   8%|▊         | 571/7211 [02:43<21:57,  5.04it/s]

Reports:   8%|▊         | 572/7211 [02:43<22:08,  5.00it/s]

Reports:   8%|▊         | 573/7211 [02:43<21:53,  5.06it/s]

Reports:   8%|▊         | 574/7211 [02:44<22:13,  4.98it/s]

Reports:   8%|▊         | 575/7211 [02:44<21:40,  5.10it/s]

Reports:   8%|▊         | 576/7211 [02:44<21:46,  5.08it/s]

Reports:   8%|▊         | 577/7211 [02:44<21:44,  5.09it/s]

Reports:   8%|▊         | 578/7211 [02:44<22:00,  5.02it/s]

Reports:   8%|▊         | 579/7211 [02:45<22:17,  4.96it/s]

Reports:   8%|▊         | 580/7211 [02:45<22:06,  5.00it/s]

Reports:   8%|▊         | 581/7211 [02:45<21:44,  5.08it/s]

Reports:   8%|▊         | 582/7211 [02:45<21:46,  5.07it/s]

Reports:   8%|▊         | 583/7211 [02:45<21:46,  5.07it/s]

Reports:   8%|▊         | 584/7211 [02:46<21:32,  5.13it/s]

Reports:   8%|▊         | 585/7211 [02:46<21:57,  5.03it/s]

Reports:   8%|▊         | 586/7211 [02:46<22:04,  5.00it/s]

Reports:   8%|▊         | 587/7211 [02:46<21:41,  5.09it/s]

Reports:   8%|▊         | 588/7211 [02:46<21:46,  5.07it/s]

Reports:   8%|▊         | 589/7211 [02:47<21:20,  5.17it/s]

Reports:   8%|▊         | 590/7211 [02:47<21:37,  5.10it/s]

Reports:   8%|▊         | 591/7211 [02:47<21:20,  5.17it/s]

Reports:   8%|▊         | 592/7211 [02:47<21:08,  5.22it/s]

Reports:   8%|▊         | 593/7211 [02:47<20:54,  5.27it/s]

Reports:   8%|▊         | 594/7211 [02:48<21:00,  5.25it/s]

Reports:   8%|▊         | 595/7211 [02:48<22:11,  4.97it/s]

Reports:   8%|▊         | 596/7211 [02:48<22:04,  4.99it/s]

Reports:   8%|▊         | 597/7211 [02:48<21:47,  5.06it/s]

Reports:   8%|▊         | 598/7211 [02:48<21:30,  5.12it/s]

Reports:   8%|▊         | 599/7211 [02:49<21:50,  5.05it/s]

Reports:   8%|▊         | 600/7211 [02:49<21:42,  5.07it/s]

Reports:   8%|▊         | 601/7211 [02:49<21:38,  5.09it/s]

Reports:   8%|▊         | 602/7211 [02:49<21:53,  5.03it/s]

Reports:   8%|▊         | 603/7211 [02:49<21:50,  5.04it/s]

Reports:   8%|▊         | 604/7211 [02:50<21:19,  5.16it/s]

Reports:   8%|▊         | 605/7211 [02:50<21:16,  5.17it/s]

Reports:   8%|▊         | 606/7211 [02:50<21:44,  5.06it/s]

Reports:   8%|▊         | 607/7211 [02:50<21:57,  5.01it/s]

Reports:   8%|▊         | 608/7211 [02:50<21:35,  5.10it/s]

Reports:   8%|▊         | 609/7211 [02:51<21:24,  5.14it/s]

Reports:   8%|▊         | 610/7211 [02:51<21:35,  5.10it/s]

Reports:   8%|▊         | 611/7211 [02:51<21:34,  5.10it/s]

Reports:   8%|▊         | 612/7211 [02:51<21:49,  5.04it/s]

Reports:   9%|▊         | 613/7211 [02:51<21:35,  5.09it/s]

Reports:   9%|▊         | 614/7211 [02:52<21:08,  5.20it/s]

Reports:   9%|▊         | 615/7211 [02:52<20:59,  5.24it/s]

Reports:   9%|▊         | 616/7211 [02:52<20:52,  5.27it/s]

Reports:   9%|▊         | 617/7211 [02:52<20:53,  5.26it/s]

Reports:   9%|▊         | 618/7211 [02:52<21:06,  5.21it/s]

Reports:   9%|▊         | 619/7211 [02:52<20:48,  5.28it/s]

Reports:   9%|▊         | 620/7211 [02:53<21:15,  5.17it/s]

Reports:   9%|▊         | 621/7211 [02:53<21:44,  5.05it/s]

Reports:   9%|▊         | 622/7211 [02:53<21:27,  5.12it/s]

Reports:   9%|▊         | 623/7211 [02:53<21:14,  5.17it/s]

Reports:   9%|▊         | 624/7211 [02:53<21:34,  5.09it/s]

Reports:   9%|▊         | 625/7211 [02:54<21:32,  5.10it/s]

Reports:   9%|▊         | 626/7211 [02:54<21:49,  5.03it/s]

Reports:   9%|▊         | 627/7211 [02:54<21:52,  5.02it/s]

Reports:   9%|▊         | 628/7211 [02:54<21:52,  5.02it/s]

Reports:   9%|▊         | 629/7211 [02:54<22:08,  4.95it/s]

Reports:   9%|▊         | 630/7211 [02:55<22:24,  4.90it/s]

Reports:   9%|▉         | 631/7211 [02:55<21:53,  5.01it/s]

Reports:   9%|▉         | 632/7211 [02:55<22:09,  4.95it/s]

Reports:   9%|▉         | 633/7211 [02:55<21:34,  5.08it/s]

Reports:   9%|▉         | 634/7211 [02:55<21:49,  5.02it/s]

Reports:   9%|▉         | 635/7211 [02:56<21:28,  5.10it/s]

Reports:   9%|▉         | 636/7211 [02:56<21:04,  5.20it/s]

Reports:   9%|▉         | 637/7211 [02:56<21:10,  5.18it/s]

Reports:   9%|▉         | 638/7211 [02:56<20:57,  5.23it/s]

Reports:   9%|▉         | 639/7211 [02:56<20:53,  5.24it/s]

Reports:   9%|▉         | 640/7211 [02:57<21:27,  5.10it/s]

Reports:   9%|▉         | 641/7211 [02:57<21:29,  5.09it/s]

Reports:   9%|▉         | 642/7211 [02:57<21:32,  5.08it/s]

Reports:   9%|▉         | 643/7211 [02:57<22:02,  4.97it/s]

Reports:   9%|▉         | 644/7211 [02:57<22:01,  4.97it/s]

Reports:   9%|▉         | 645/7211 [02:58<21:56,  4.99it/s]

Reports:   9%|▉         | 646/7211 [02:58<21:57,  4.98it/s]

Reports:   9%|▉         | 647/7211 [02:58<21:52,  5.00it/s]

Reports:   9%|▉         | 648/7211 [02:58<21:50,  5.01it/s]

Reports:   9%|▉         | 649/7211 [02:58<21:54,  4.99it/s]

Reports:   9%|▉         | 650/7211 [02:59<21:54,  4.99it/s]

Reports:   9%|▉         | 651/7211 [02:59<21:34,  5.07it/s]

Reports:   9%|▉         | 652/7211 [02:59<21:18,  5.13it/s]

Reports:   9%|▉         | 653/7211 [02:59<21:11,  5.16it/s]

Reports:   9%|▉         | 654/7211 [02:59<21:06,  5.18it/s]

Reports:   9%|▉         | 655/7211 [03:00<21:23,  5.11it/s]

Reports:   9%|▉         | 656/7211 [03:00<21:11,  5.16it/s]

Reports:   9%|▉         | 657/7211 [03:00<21:31,  5.08it/s]

Reports:   9%|▉         | 658/7211 [03:00<21:20,  5.12it/s]

Reports:   9%|▉         | 659/7211 [03:00<20:53,  5.23it/s]

Reports:   9%|▉         | 660/7211 [03:01<20:55,  5.22it/s]

Reports:   9%|▉         | 661/7211 [03:01<21:01,  5.19it/s]

Reports:   9%|▉         | 662/7211 [03:01<21:03,  5.18it/s]

Reports:   9%|▉         | 663/7211 [03:01<21:29,  5.08it/s]

Reports:   9%|▉         | 664/7211 [03:01<21:13,  5.14it/s]

Reports:   9%|▉         | 665/7211 [03:02<21:12,  5.14it/s]

Reports:   9%|▉         | 666/7211 [03:02<20:47,  5.25it/s]

Reports:   9%|▉         | 667/7211 [03:02<21:15,  5.13it/s]

Reports:   9%|▉         | 668/7211 [03:02<21:01,  5.19it/s]

Reports:   9%|▉         | 669/7211 [03:02<21:04,  5.17it/s]

Reports:   9%|▉         | 670/7211 [03:02<20:53,  5.22it/s]

Reports:   9%|▉         | 671/7211 [03:03<20:42,  5.26it/s]

Reports:   9%|▉         | 672/7211 [03:03<20:34,  5.30it/s]

Reports:   9%|▉         | 673/7211 [03:03<20:35,  5.29it/s]

Reports:   9%|▉         | 674/7211 [03:03<20:43,  5.26it/s]

Reports:   9%|▉         | 675/7211 [03:03<20:43,  5.25it/s]

Reports:   9%|▉         | 676/7211 [03:04<20:31,  5.31it/s]

Reports:   9%|▉         | 677/7211 [03:04<20:49,  5.23it/s]

Reports:   9%|▉         | 678/7211 [03:04<21:06,  5.16it/s]

Reports:   9%|▉         | 679/7211 [03:04<21:36,  5.04it/s]

Reports:   9%|▉         | 680/7211 [03:04<21:36,  5.04it/s]

Reports:   9%|▉         | 681/7211 [03:05<22:18,  4.88it/s]

Reports:   9%|▉         | 682/7211 [03:05<22:12,  4.90it/s]

Reports:   9%|▉         | 683/7211 [03:05<21:47,  4.99it/s]

Reports:   9%|▉         | 684/7211 [03:05<21:22,  5.09it/s]

Reports:   9%|▉         | 685/7211 [03:05<21:20,  5.10it/s]

Reports:  10%|▉         | 686/7211 [03:06<21:05,  5.16it/s]

Reports:  10%|▉         | 687/7211 [03:06<21:19,  5.10it/s]

Reports:  10%|▉         | 688/7211 [03:06<21:04,  5.16it/s]

Reports:  10%|▉         | 689/7211 [03:06<21:21,  5.09it/s]

Reports:  10%|▉         | 690/7211 [03:06<21:28,  5.06it/s]

Reports:  10%|▉         | 691/7211 [03:07<21:22,  5.08it/s]

Reports:  10%|▉         | 692/7211 [03:07<21:44,  5.00it/s]

Reports:  10%|▉         | 693/7211 [03:07<21:49,  4.98it/s]

Reports:  10%|▉         | 694/7211 [03:07<21:57,  4.95it/s]

Reports:  10%|▉         | 695/7211 [03:07<21:47,  4.98it/s]

Reports:  10%|▉         | 696/7211 [03:08<21:46,  4.99it/s]

Reports:  10%|▉         | 697/7211 [03:08<21:40,  5.01it/s]

Reports:  10%|▉         | 698/7211 [03:08<21:07,  5.14it/s]

Reports:  10%|▉         | 699/7211 [03:08<21:11,  5.12it/s]

Reports:  10%|▉         | 700/7211 [03:08<20:45,  5.23it/s]

Reports:  10%|▉         | 701/7211 [03:09<21:15,  5.10it/s]

Reports:  10%|▉         | 702/7211 [03:09<20:48,  5.22it/s]

Reports:  10%|▉         | 703/7211 [03:09<21:14,  5.10it/s]

Reports:  10%|▉         | 704/7211 [03:09<21:13,  5.11it/s]

Reports:  10%|▉         | 705/7211 [03:09<21:07,  5.13it/s]

Reports:  10%|▉         | 706/7211 [03:10<21:34,  5.02it/s]

Reports:  10%|▉         | 707/7211 [03:10<21:33,  5.03it/s]

Reports:  10%|▉         | 708/7211 [03:10<21:27,  5.05it/s]

Reports:  10%|▉         | 709/7211 [03:10<21:53,  4.95it/s]

Reports:  10%|▉         | 710/7211 [03:10<21:32,  5.03it/s]

Reports:  10%|▉         | 711/7211 [03:11<21:28,  5.04it/s]

Reports:  10%|▉         | 712/7211 [03:11<20:59,  5.16it/s]

Reports:  10%|▉         | 713/7211 [03:11<20:51,  5.19it/s]

Reports:  10%|▉         | 714/7211 [03:11<20:32,  5.27it/s]

Reports:  10%|▉         | 715/7211 [03:11<20:29,  5.28it/s]

Reports:  10%|▉         | 716/7211 [03:11<21:01,  5.15it/s]

Reports:  10%|▉         | 717/7211 [03:12<21:27,  5.04it/s]

Reports:  10%|▉         | 718/7211 [03:12<20:58,  5.16it/s]

Reports:  10%|▉         | 719/7211 [03:12<20:48,  5.20it/s]

Reports:  10%|▉         | 720/7211 [03:12<20:43,  5.22it/s]

Reports:  10%|▉         | 721/7211 [03:12<20:32,  5.26it/s]

Reports:  10%|█         | 722/7211 [03:13<20:42,  5.22it/s]

Reports:  10%|█         | 723/7211 [03:13<20:44,  5.21it/s]

Reports:  10%|█         | 724/7211 [03:13<20:33,  5.26it/s]

Reports:  10%|█         | 725/7211 [03:13<20:36,  5.25it/s]

Reports:  10%|█         | 726/7211 [03:13<20:34,  5.25it/s]

Reports:  10%|█         | 727/7211 [03:14<20:56,  5.16it/s]

Reports:  10%|█         | 728/7211 [03:14<20:53,  5.17it/s]

Reports:  10%|█         | 729/7211 [03:14<20:53,  5.17it/s]

Reports:  10%|█         | 730/7211 [03:14<20:37,  5.24it/s]

Reports:  10%|█         | 731/7211 [03:14<20:50,  5.18it/s]

Reports:  10%|█         | 732/7211 [03:15<21:53,  4.93it/s]

Reports:  10%|█         | 733/7211 [03:15<21:58,  4.91it/s]

Reports:  10%|█         | 734/7211 [03:15<21:39,  4.99it/s]

Reports:  10%|█         | 735/7211 [03:15<21:25,  5.04it/s]

Reports:  10%|█         | 736/7211 [03:15<21:30,  5.02it/s]

Reports:  10%|█         | 737/7211 [03:16<21:54,  4.92it/s]

Reports:  10%|█         | 738/7211 [03:16<21:48,  4.95it/s]

Reports:  10%|█         | 739/7211 [03:16<21:44,  4.96it/s]

Reports:  10%|█         | 740/7211 [03:16<21:06,  5.11it/s]

Reports:  10%|█         | 741/7211 [03:16<21:00,  5.13it/s]

Reports:  10%|█         | 742/7211 [03:17<20:52,  5.16it/s]

Reports:  10%|█         | 743/7211 [03:17<20:56,  5.15it/s]

Reports:  10%|█         | 744/7211 [03:17<21:23,  5.04it/s]

Reports:  10%|█         | 745/7211 [03:17<21:02,  5.12it/s]

Reports:  10%|█         | 746/7211 [03:17<23:08,  4.66it/s]

Reports:  10%|█         | 747/7211 [03:18<24:38,  4.37it/s]

Reports:  10%|█         | 748/7211 [03:18<24:18,  4.43it/s]

Reports:  10%|█         | 749/7211 [03:18<25:10,  4.28it/s]

Reports:  10%|█         | 750/7211 [03:18<26:22,  4.08it/s]

Reports:  10%|█         | 751/7211 [03:19<25:58,  4.15it/s]

Reports:  10%|█         | 752/7211 [03:19<26:49,  4.01it/s]

Reports:  10%|█         | 753/7211 [03:19<27:01,  3.98it/s]

Reports:  10%|█         | 754/7211 [03:19<27:46,  3.87it/s]

Reports:  10%|█         | 755/7211 [03:20<28:04,  3.83it/s]

Reports:  10%|█         | 756/7211 [03:20<28:30,  3.77it/s]

Reports:  10%|█         | 757/7211 [03:20<28:48,  3.73it/s]

Reports:  11%|█         | 758/7211 [03:21<29:01,  3.71it/s]

Reports:  11%|█         | 759/7211 [03:21<27:44,  3.88it/s]

Reports:  11%|█         | 760/7211 [03:21<27:09,  3.96it/s]

Reports:  11%|█         | 761/7211 [03:21<27:49,  3.86it/s]

Reports:  11%|█         | 762/7211 [03:22<26:47,  4.01it/s]

Reports:  11%|█         | 763/7211 [03:22<24:36,  4.37it/s]

Reports:  11%|█         | 764/7211 [03:22<23:15,  4.62it/s]

Reports:  11%|█         | 765/7211 [03:22<22:31,  4.77it/s]

Reports:  11%|█         | 766/7211 [03:22<22:15,  4.82it/s]

Reports:  11%|█         | 767/7211 [03:22<21:40,  4.95it/s]

Reports:  11%|█         | 768/7211 [03:23<21:17,  5.04it/s]

Reports:  11%|█         | 769/7211 [03:23<21:19,  5.04it/s]

Reports:  11%|█         | 770/7211 [03:23<21:06,  5.08it/s]

Reports:  11%|█         | 771/7211 [03:23<20:57,  5.12it/s]

Reports:  11%|█         | 772/7211 [03:23<21:01,  5.10it/s]

Reports:  11%|█         | 773/7211 [03:24<21:13,  5.06it/s]

Reports:  11%|█         | 774/7211 [03:24<21:03,  5.10it/s]

Reports:  11%|█         | 775/7211 [03:24<20:54,  5.13it/s]

Reports:  11%|█         | 776/7211 [03:24<20:44,  5.17it/s]

Reports:  11%|█         | 777/7211 [03:24<21:23,  5.01it/s]

Reports:  11%|█         | 778/7211 [03:25<21:02,  5.10it/s]

Reports:  11%|█         | 779/7211 [03:25<20:49,  5.15it/s]

Reports:  11%|█         | 780/7211 [03:25<21:00,  5.10it/s]

Reports:  11%|█         | 781/7211 [03:25<24:02,  4.46it/s]

Reports:  11%|█         | 782/7211 [03:25<22:52,  4.68it/s]

Reports:  11%|█         | 783/7211 [03:26<22:09,  4.84it/s]

Reports:  11%|█         | 784/7211 [03:26<21:30,  4.98it/s]

Reports:  11%|█         | 785/7211 [03:26<21:06,  5.07it/s]

Reports:  11%|█         | 786/7211 [03:26<20:47,  5.15it/s]

Reports:  11%|█         | 787/7211 [03:26<20:45,  5.16it/s]

Reports:  11%|█         | 788/7211 [03:27<20:38,  5.19it/s]

Reports:  11%|█         | 789/7211 [03:27<20:31,  5.22it/s]

Reports:  11%|█         | 790/7211 [03:27<20:25,  5.24it/s]

Reports:  11%|█         | 791/7211 [03:27<20:34,  5.20it/s]

Reports:  11%|█         | 792/7211 [03:27<20:58,  5.10it/s]

Reports:  11%|█         | 793/7211 [03:28<20:59,  5.10it/s]

Reports:  11%|█         | 794/7211 [03:28<21:03,  5.08it/s]

Reports:  11%|█         | 795/7211 [03:28<20:47,  5.14it/s]

Reports:  11%|█         | 796/7211 [03:28<20:32,  5.21it/s]

Reports:  11%|█         | 797/7211 [03:28<20:33,  5.20it/s]

Reports:  11%|█         | 798/7211 [03:29<23:01,  4.64it/s]

Reports:  11%|█         | 799/7211 [03:29<22:23,  4.77it/s]

Reports:  11%|█         | 800/7211 [03:29<22:29,  4.75it/s]

Reports:  11%|█         | 801/7211 [03:29<22:20,  4.78it/s]

Reports:  11%|█         | 802/7211 [03:29<22:09,  4.82it/s]

Reports:  11%|█         | 803/7211 [03:30<22:32,  4.74it/s]

Reports:  11%|█         | 804/7211 [03:30<22:47,  4.69it/s]

Reports:  11%|█         | 805/7211 [03:30<22:40,  4.71it/s]

Reports:  11%|█         | 806/7211 [03:30<22:07,  4.83it/s]

Reports:  11%|█         | 807/7211 [03:30<21:41,  4.92it/s]

Reports:  11%|█         | 808/7211 [03:31<20:59,  5.09it/s]

Reports:  11%|█         | 809/7211 [03:31<20:50,  5.12it/s]

Reports:  11%|█         | 810/7211 [03:31<21:07,  5.05it/s]

Reports:  11%|█         | 811/7211 [03:31<20:46,  5.13it/s]

Reports:  11%|█▏        | 812/7211 [03:31<20:40,  5.16it/s]

Reports:  11%|█▏        | 813/7211 [03:32<20:44,  5.14it/s]

Reports:  11%|█▏        | 814/7211 [03:32<21:02,  5.07it/s]

Reports:  11%|█▏        | 815/7211 [03:32<21:09,  5.04it/s]

Reports:  11%|█▏        | 816/7211 [03:32<20:52,  5.11it/s]

Reports:  11%|█▏        | 817/7211 [03:32<21:10,  5.03it/s]

Reports:  11%|█▏        | 818/7211 [03:33<21:05,  5.05it/s]

Reports:  11%|█▏        | 819/7211 [03:33<21:18,  5.00it/s]

Reports:  11%|█▏        | 820/7211 [03:33<21:25,  4.97it/s]

Reports:  11%|█▏        | 821/7211 [03:33<21:00,  5.07it/s]

Reports:  11%|█▏        | 822/7211 [03:33<21:22,  4.98it/s]

Reports:  11%|█▏        | 823/7211 [03:34<20:56,  5.08it/s]

Reports:  11%|█▏        | 824/7211 [03:34<20:51,  5.10it/s]

Reports:  11%|█▏        | 825/7211 [03:34<20:40,  5.15it/s]

Reports:  11%|█▏        | 826/7211 [03:34<20:32,  5.18it/s]

Reports:  11%|█▏        | 827/7211 [03:34<20:14,  5.25it/s]

Reports:  11%|█▏        | 828/7211 [03:35<20:11,  5.27it/s]

Reports:  11%|█▏        | 829/7211 [03:35<20:23,  5.22it/s]

Reports:  12%|█▏        | 830/7211 [03:35<20:40,  5.14it/s]

Reports:  12%|█▏        | 831/7211 [03:35<20:46,  5.12it/s]

Reports:  12%|█▏        | 832/7211 [03:35<20:31,  5.18it/s]

Reports:  12%|█▏        | 833/7211 [03:36<20:14,  5.25it/s]

Reports:  12%|█▏        | 834/7211 [03:36<20:54,  5.08it/s]

Reports:  12%|█▏        | 835/7211 [03:36<20:53,  5.08it/s]

Reports:  12%|█▏        | 836/7211 [03:36<21:17,  4.99it/s]

Reports:  12%|█▏        | 837/7211 [03:36<20:58,  5.07it/s]

Reports:  12%|█▏        | 838/7211 [03:37<21:13,  5.00it/s]

Reports:  12%|█▏        | 839/7211 [03:37<21:03,  5.04it/s]

Reports:  12%|█▏        | 840/7211 [03:37<21:01,  5.05it/s]

Reports:  12%|█▏        | 841/7211 [03:37<20:56,  5.07it/s]

Reports:  12%|█▏        | 842/7211 [03:37<21:02,  5.04it/s]

Reports:  12%|█▏        | 843/7211 [03:38<20:38,  5.14it/s]

Reports:  12%|█▏        | 844/7211 [03:38<20:38,  5.14it/s]

Reports:  12%|█▏        | 845/7211 [03:38<20:34,  5.16it/s]

Reports:  12%|█▏        | 846/7211 [03:38<20:30,  5.17it/s]

Reports:  12%|█▏        | 847/7211 [03:38<20:32,  5.16it/s]

Reports:  12%|█▏        | 848/7211 [03:39<21:11,  5.01it/s]

Reports:  12%|█▏        | 849/7211 [03:39<21:01,  5.04it/s]

Reports:  12%|█▏        | 850/7211 [03:39<20:50,  5.09it/s]

Reports:  12%|█▏        | 851/7211 [03:39<20:39,  5.13it/s]

Reports:  12%|█▏        | 852/7211 [03:39<20:26,  5.18it/s]

Reports:  12%|█▏        | 853/7211 [03:39<20:39,  5.13it/s]

Reports:  12%|█▏        | 854/7211 [03:40<20:31,  5.16it/s]

Reports:  12%|█▏        | 855/7211 [03:40<20:32,  5.16it/s]

Reports:  12%|█▏        | 856/7211 [03:40<20:47,  5.09it/s]

Reports:  12%|█▏        | 857/7211 [03:40<21:05,  5.02it/s]

Reports:  12%|█▏        | 858/7211 [03:40<21:21,  4.96it/s]

Reports:  12%|█▏        | 859/7211 [03:41<20:46,  5.09it/s]

Reports:  12%|█▏        | 860/7211 [03:41<20:35,  5.14it/s]

Reports:  12%|█▏        | 861/7211 [03:41<20:24,  5.18it/s]

Reports:  12%|█▏        | 862/7211 [03:41<21:15,  4.98it/s]

Reports:  12%|█▏        | 863/7211 [03:41<21:05,  5.02it/s]

Reports:  12%|█▏        | 864/7211 [03:42<21:22,  4.95it/s]

Reports:  12%|█▏        | 865/7211 [03:42<21:28,  4.92it/s]

Reports:  12%|█▏        | 866/7211 [03:42<21:47,  4.85it/s]

Reports:  12%|█▏        | 867/7211 [03:42<21:23,  4.94it/s]

Reports:  12%|█▏        | 868/7211 [03:42<21:20,  4.95it/s]

Reports:  12%|█▏        | 869/7211 [03:43<20:51,  5.07it/s]

Reports:  12%|█▏        | 870/7211 [03:43<20:20,  5.20it/s]

Reports:  12%|█▏        | 871/7211 [03:43<20:10,  5.24it/s]

Reports:  12%|█▏        | 872/7211 [03:43<20:19,  5.20it/s]

Reports:  12%|█▏        | 873/7211 [03:43<21:09,  4.99it/s]

Reports:  12%|█▏        | 874/7211 [03:44<21:14,  4.97it/s]

Reports:  12%|█▏        | 875/7211 [03:44<21:03,  5.02it/s]

Reports:  12%|█▏        | 876/7211 [03:44<20:42,  5.10it/s]

Reports:  12%|█▏        | 877/7211 [03:44<20:53,  5.05it/s]

Reports:  12%|█▏        | 878/7211 [03:44<21:02,  5.02it/s]

Reports:  12%|█▏        | 879/7211 [03:45<20:25,  5.16it/s]

Reports:  12%|█▏        | 880/7211 [03:45<20:15,  5.21it/s]

Reports:  12%|█▏        | 881/7211 [03:45<20:28,  5.15it/s]

Reports:  12%|█▏        | 882/7211 [03:45<20:09,  5.23it/s]

Reports:  12%|█▏        | 883/7211 [03:45<21:07,  4.99it/s]

Reports:  12%|█▏        | 884/7211 [03:46<20:44,  5.08it/s]

Reports:  12%|█▏        | 885/7211 [03:46<21:11,  4.98it/s]

Reports:  12%|█▏        | 886/7211 [03:46<20:46,  5.07it/s]

Reports:  12%|█▏        | 887/7211 [03:46<20:29,  5.14it/s]

Reports:  12%|█▏        | 888/7211 [03:46<20:33,  5.13it/s]

Reports:  12%|█▏        | 889/7211 [03:47<20:58,  5.02it/s]

Reports:  12%|█▏        | 890/7211 [03:47<21:32,  4.89it/s]

Reports:  12%|█▏        | 891/7211 [03:47<21:02,  5.01it/s]

Reports:  12%|█▏        | 892/7211 [03:47<21:03,  5.00it/s]

Reports:  12%|█▏        | 893/7211 [03:47<20:41,  5.09it/s]

Reports:  12%|█▏        | 894/7211 [03:48<20:41,  5.09it/s]

Reports:  12%|█▏        | 895/7211 [03:48<20:39,  5.09it/s]

Reports:  12%|█▏        | 896/7211 [03:48<20:37,  5.10it/s]

Reports:  12%|█▏        | 897/7211 [03:48<20:25,  5.15it/s]

Reports:  12%|█▏        | 898/7211 [03:48<20:59,  5.01it/s]

Reports:  12%|█▏        | 899/7211 [03:49<20:54,  5.03it/s]

Reports:  12%|█▏        | 900/7211 [03:49<20:31,  5.13it/s]

Reports:  12%|█▏        | 901/7211 [03:49<20:11,  5.21it/s]

Reports:  13%|█▎        | 902/7211 [03:49<19:58,  5.27it/s]

Reports:  13%|█▎        | 903/7211 [03:49<20:05,  5.23it/s]

Reports:  13%|█▎        | 904/7211 [03:50<20:27,  5.14it/s]

Reports:  13%|█▎        | 905/7211 [03:50<20:37,  5.09it/s]

Reports:  13%|█▎        | 906/7211 [03:50<22:39,  4.64it/s]

Reports:  13%|█▎        | 907/7211 [03:50<22:16,  4.72it/s]

Reports:  13%|█▎        | 908/7211 [03:50<21:59,  4.78it/s]

Reports:  13%|█▎        | 909/7211 [03:51<21:19,  4.92it/s]

Reports:  13%|█▎        | 910/7211 [03:51<21:06,  4.98it/s]

Reports:  13%|█▎        | 911/7211 [03:51<20:53,  5.03it/s]

Reports:  13%|█▎        | 912/7211 [03:51<20:45,  5.06it/s]

Reports:  13%|█▎        | 913/7211 [03:51<20:20,  5.16it/s]

Reports:  13%|█▎        | 914/7211 [03:52<20:28,  5.12it/s]

Reports:  13%|█▎        | 915/7211 [03:52<20:22,  5.15it/s]

Reports:  13%|█▎        | 916/7211 [03:52<20:20,  5.16it/s]

Reports:  13%|█▎        | 917/7211 [03:52<20:24,  5.14it/s]

Reports:  13%|█▎        | 918/7211 [03:52<20:30,  5.11it/s]

Reports:  13%|█▎        | 919/7211 [03:53<20:21,  5.15it/s]

Reports:  13%|█▎        | 920/7211 [03:53<20:26,  5.13it/s]

Reports:  13%|█▎        | 921/7211 [03:53<20:20,  5.16it/s]

Reports:  13%|█▎        | 922/7211 [03:53<20:15,  5.17it/s]

Reports:  13%|█▎        | 923/7211 [03:53<20:20,  5.15it/s]

Reports:  13%|█▎        | 924/7211 [03:53<20:12,  5.18it/s]

Reports:  13%|█▎        | 925/7211 [03:54<20:10,  5.19it/s]

Reports:  13%|█▎        | 926/7211 [03:54<20:09,  5.20it/s]

Reports:  13%|█▎        | 927/7211 [03:54<20:10,  5.19it/s]

Reports:  13%|█▎        | 928/7211 [03:54<20:35,  5.09it/s]

Reports:  13%|█▎        | 929/7211 [03:54<20:23,  5.13it/s]

Reports:  13%|█▎        | 930/7211 [03:55<20:12,  5.18it/s]

Reports:  13%|█▎        | 931/7211 [03:55<20:25,  5.12it/s]

Reports:  13%|█▎        | 932/7211 [03:55<20:10,  5.19it/s]

Reports:  13%|█▎        | 933/7211 [03:55<20:18,  5.15it/s]

Reports:  13%|█▎        | 934/7211 [03:55<20:33,  5.09it/s]

Reports:  13%|█▎        | 935/7211 [03:56<20:23,  5.13it/s]

Reports:  13%|█▎        | 936/7211 [03:56<20:30,  5.10it/s]

Reports:  13%|█▎        | 937/7211 [03:56<20:29,  5.10it/s]

Reports:  13%|█▎        | 938/7211 [03:56<20:27,  5.11it/s]

Reports:  13%|█▎        | 939/7211 [03:56<20:55,  5.00it/s]

Reports:  13%|█▎        | 940/7211 [03:57<20:55,  5.00it/s]

Reports:  13%|█▎        | 941/7211 [03:58<1:03:13,  1.65it/s]

Reports:  13%|█▎        | 942/7211 [03:58<50:48,  2.06it/s]

Reports:  13%|█▎        | 943/7211 [04:24<13:54:02,  7.98s/it]

Reports:  13%|█▎        | 944/7211 [04:24<9:50:04,  5.65s/it]

Reports:  13%|█▎        | 945/7211 [04:24<6:59:28,  4.02s/it]

Reports:  13%|█▎        | 946/7211 [04:24<4:59:45,  2.87s/it]

Reports:  13%|█▎        | 947/7211 [04:25<3:35:56,  2.07s/it]

Reports:  13%|█▎        | 948/7211 [04:25<2:37:16,  1.51s/it]

Reports:  13%|█▎        | 949/7211 [04:25<1:56:28,  1.12s/it]

Reports:  13%|█▎        | 950/7211 [04:25<1:27:29,  1.19it/s]

Reports:  13%|█▎        | 951/7211 [04:25<1:07:22,  1.55it/s]

Reports:  13%|█▎        | 952/7211 [04:26<54:10,  1.93it/s]

Reports:  13%|█▎        | 953/7211 [04:26<47:43,  2.19it/s]

Reports:  13%|█▎        | 954/7211 [04:26<40:58,  2.55it/s]

Reports:  13%|█▎        | 955/7211 [04:26<36:07,  2.89it/s]

Reports:  13%|█▎        | 956/7211 [04:27<32:45,  3.18it/s]

Reports:  13%|█▎        | 957/7211 [04:27<29:04,  3.59it/s]

Reports:  13%|█▎        | 958/7211 [04:27<26:28,  3.94it/s]

Reports:  13%|█▎        | 959/7211 [04:27<24:46,  4.21it/s]

Reports:  13%|█▎        | 960/7211 [04:28<23:43,  4.39it/s]

Reports:  13%|█▎        | 961/7211 [04:28<22:47,  4.57it/s]

Reports:  13%|█▎        | 962/7211 [04:28<22:27,  4.64it/s]

Reports:  13%|█▎        | 963/7211 [04:28<21:37,  4.82it/s]

Reports:  13%|█▎        | 964/7211 [04:28<21:11,  4.91it/s]

Reports:  13%|█▎        | 965/7211 [04:28<20:56,  4.97it/s]

Reports:  13%|█▎        | 966/7211 [04:29<20:54,  4.98it/s]

Reports:  13%|█▎        | 967/7211 [04:29<21:04,  4.94it/s]

Reports:  13%|█▎        | 968/7211 [04:29<21:03,  4.94it/s]

Reports:  13%|█▎        | 969/7211 [04:29<21:11,  4.91it/s]

Reports:  13%|█▎        | 970/7211 [04:30<20:46,  5.01it/s]

Reports:  13%|█▎        | 971/7211 [04:30<20:39,  5.04it/s]

Reports:  13%|█▎        | 972/7211 [04:30<20:24,  5.10it/s]

Reports:  13%|█▎        | 973/7211 [04:30<20:22,  5.10it/s]

Reports:  14%|█▎        | 974/7211 [04:30<20:04,  5.18it/s]

Reports:  14%|█▎        | 975/7211 [04:30<19:58,  5.20it/s]

Reports:  14%|█▎        | 976/7211 [04:31<19:49,  5.24it/s]

Reports:  14%|█▎        | 977/7211 [04:31<20:46,  5.00it/s]

Reports:  14%|█▎        | 978/7211 [04:31<20:58,  4.95it/s]

Reports:  14%|█▎        | 979/7211 [04:31<21:06,  4.92it/s]

Reports:  14%|█▎        | 980/7211 [04:31<21:03,  4.93it/s]

Reports:  14%|█▎        | 981/7211 [04:32<20:53,  4.97it/s]

Reports:  14%|█▎        | 982/7211 [04:32<20:57,  4.95it/s]

Reports:  14%|█▎        | 983/7211 [04:32<20:27,  5.07it/s]

Reports:  14%|█▎        | 984/7211 [04:32<21:01,  4.94it/s]

Reports:  14%|█▎        | 985/7211 [04:32<20:30,  5.06it/s]

Reports:  14%|█▎        | 986/7211 [04:33<20:32,  5.05it/s]

Reports:  14%|█▎        | 987/7211 [04:33<20:12,  5.13it/s]

Reports:  14%|█▎        | 988/7211 [04:33<20:25,  5.08it/s]

Reports:  14%|█▎        | 989/7211 [04:33<20:27,  5.07it/s]

Reports:  14%|█▎        | 990/7211 [04:33<20:22,  5.09it/s]

Reports:  14%|█▎        | 991/7211 [04:34<20:13,  5.13it/s]

Reports:  14%|█▍        | 992/7211 [04:34<20:17,  5.11it/s]

Reports:  14%|█▍        | 993/7211 [04:34<20:03,  5.17it/s]

Reports:  14%|█▍        | 994/7211 [04:34<20:24,  5.08it/s]

Reports:  14%|█▍        | 995/7211 [04:34<20:20,  5.09it/s]

Reports:  14%|█▍        | 996/7211 [04:35<20:36,  5.03it/s]

Reports:  14%|█▍        | 997/7211 [04:35<20:26,  5.07it/s]

Reports:  14%|█▍        | 998/7211 [04:35<20:42,  5.00it/s]

Reports:  14%|█▍        | 999/7211 [04:35<28:06,  3.68it/s]

Reports:  14%|█▍        | 1000/7211 [04:36<25:18,  4.09it/s]

Reports:  14%|█▍        | 1001/7211 [04:36<24:17,  4.26it/s]

Reports:  14%|█▍        | 1002/7211 [04:36<22:56,  4.51it/s]

Reports:  14%|█▍        | 1003/7211 [04:36<21:56,  4.72it/s]

Reports:  14%|█▍        | 1004/7211 [04:36<21:33,  4.80it/s]

Reports:  14%|█▍        | 1005/7211 [04:37<21:43,  4.76it/s]

Reports:  14%|█▍        | 1006/7211 [04:37<21:05,  4.90it/s]

Reports:  14%|█▍        | 1007/7211 [04:37<20:28,  5.05it/s]

Reports:  14%|█▍        | 1008/7211 [04:37<20:29,  5.04it/s]

Reports:  14%|█▍        | 1009/7211 [04:37<20:30,  5.04it/s]

Reports:  14%|█▍        | 1010/7211 [04:38<20:37,  5.01it/s]

Reports:  14%|█▍        | 1011/7211 [04:38<20:22,  5.07it/s]

Reports:  14%|█▍        | 1012/7211 [04:38<19:49,  5.21it/s]

Reports:  14%|█▍        | 1013/7211 [04:38<20:06,  5.14it/s]

Reports:  14%|█▍        | 1014/7211 [04:38<20:28,  5.04it/s]

Reports:  14%|█▍        | 1015/7211 [04:39<20:14,  5.10it/s]

Reports:  14%|█▍        | 1016/7211 [04:39<19:59,  5.16it/s]

Reports:  14%|█▍        | 1017/7211 [04:39<19:56,  5.18it/s]

Reports:  14%|█▍        | 1018/7211 [04:39<20:12,  5.11it/s]

Reports:  14%|█▍        | 1019/7211 [04:39<20:14,  5.10it/s]

Reports:  14%|█▍        | 1020/7211 [04:40<19:54,  5.18it/s]

Reports:  14%|█▍        | 1021/7211 [04:40<19:50,  5.20it/s]

Reports:  14%|█▍        | 1022/7211 [04:40<19:30,  5.29it/s]

Reports:  14%|█▍        | 1023/7211 [04:40<20:00,  5.15it/s]

Reports:  14%|█▍        | 1024/7211 [04:40<20:18,  5.08it/s]

Reports:  14%|█▍        | 1025/7211 [04:41<20:40,  4.99it/s]

Reports:  14%|█▍        | 1026/7211 [04:41<20:10,  5.11it/s]

Reports:  14%|█▍        | 1027/7211 [04:41<20:09,  5.11it/s]

Reports:  14%|█▍        | 1028/7211 [04:41<20:01,  5.15it/s]

Reports:  14%|█▍        | 1029/7211 [04:41<20:01,  5.15it/s]

Reports:  14%|█▍        | 1030/7211 [04:42<20:12,  5.10it/s]

Reports:  14%|█▍        | 1031/7211 [04:42<20:01,  5.14it/s]

Reports:  14%|█▍        | 1032/7211 [04:42<19:57,  5.16it/s]

Reports:  14%|█▍        | 1033/7211 [04:42<19:59,  5.15it/s]

Reports:  14%|█▍        | 1034/7211 [04:42<19:59,  5.15it/s]

Reports:  14%|█▍        | 1035/7211 [04:42<19:38,  5.24it/s]

Reports:  14%|█▍        | 1036/7211 [04:43<19:29,  5.28it/s]

Reports:  14%|█▍        | 1037/7211 [04:43<19:32,  5.26it/s]

Reports:  14%|█▍        | 1038/7211 [04:43<19:11,  5.36it/s]

Reports:  14%|█▍        | 1039/7211 [04:43<19:29,  5.28it/s]

Reports:  14%|█▍        | 1040/7211 [04:43<19:59,  5.14it/s]

Reports:  14%|█▍        | 1041/7211 [04:44<20:28,  5.02it/s]

Reports:  14%|█▍        | 1042/7211 [04:44<20:00,  5.14it/s]

Reports:  14%|█▍        | 1043/7211 [04:44<19:54,  5.16it/s]

Reports:  14%|█▍        | 1044/7211 [04:44<19:44,  5.21it/s]

Reports:  14%|█▍        | 1045/7211 [04:44<20:11,  5.09it/s]

Reports:  15%|█▍        | 1046/7211 [04:45<20:14,  5.08it/s]

Reports:  15%|█▍        | 1047/7211 [04:45<20:19,  5.06it/s]

Reports:  15%|█▍        | 1048/7211 [04:45<20:26,  5.02it/s]

Reports:  15%|█▍        | 1049/7211 [04:45<20:06,  5.11it/s]

Reports:  15%|█▍        | 1050/7211 [04:45<19:55,  5.15it/s]

Reports:  15%|█▍        | 1051/7211 [04:46<19:48,  5.18it/s]

Reports:  15%|█▍        | 1052/7211 [04:46<19:50,  5.17it/s]

Reports:  15%|█▍        | 1053/7211 [04:46<19:44,  5.20it/s]

Reports:  15%|█▍        | 1054/7211 [04:46<20:17,  5.06it/s]

Reports:  15%|█▍        | 1055/7211 [04:46<20:18,  5.05it/s]

Reports:  15%|█▍        | 1056/7211 [04:47<19:59,  5.13it/s]

Reports:  15%|█▍        | 1057/7211 [04:47<19:45,  5.19it/s]

Reports:  15%|█▍        | 1058/7211 [04:47<19:38,  5.22it/s]

Reports:  15%|█▍        | 1059/7211 [04:47<20:14,  5.06it/s]

Reports:  15%|█▍        | 1060/7211 [04:47<19:54,  5.15it/s]

Reports:  15%|█▍        | 1061/7211 [04:48<19:42,  5.20it/s]

Reports:  15%|█▍        | 1062/7211 [04:48<20:11,  5.08it/s]

Reports:  15%|█▍        | 1063/7211 [04:48<20:06,  5.10it/s]

Reports:  15%|█▍        | 1064/7211 [04:48<20:22,  5.03it/s]

Reports:  15%|█▍        | 1065/7211 [04:48<20:16,  5.05it/s]

Reports:  15%|█▍        | 1066/7211 [04:49<22:56,  4.47it/s]

Reports:  15%|█▍        | 1067/7211 [04:49<21:48,  4.70it/s]

Reports:  15%|█▍        | 1068/7211 [04:49<21:09,  4.84it/s]

Reports:  15%|█▍        | 1069/7211 [04:49<20:48,  4.92it/s]

Reports:  15%|█▍        | 1070/7211 [04:49<20:35,  4.97it/s]

Reports:  15%|█▍        | 1071/7211 [04:50<20:09,  5.08it/s]

Reports:  15%|█▍        | 1072/7211 [04:50<20:32,  4.98it/s]

Reports:  15%|█▍        | 1073/7211 [04:50<20:18,  5.04it/s]

Reports:  15%|█▍        | 1074/7211 [04:50<19:55,  5.13it/s]

Reports:  15%|█▍        | 1075/7211 [04:50<19:59,  5.11it/s]

Reports:  15%|█▍        | 1076/7211 [04:51<20:16,  5.04it/s]

Reports:  15%|█▍        | 1077/7211 [04:51<20:14,  5.05it/s]

Reports:  15%|█▍        | 1078/7211 [04:51<20:17,  5.04it/s]

Reports:  15%|█▍        | 1079/7211 [04:51<20:45,  4.92it/s]

Reports:  15%|█▍        | 1080/7211 [04:51<20:35,  4.96it/s]

Reports:  15%|█▍        | 1081/7211 [04:52<20:35,  4.96it/s]

Reports:  15%|█▌        | 1082/7211 [04:52<20:08,  5.07it/s]

Reports:  15%|█▌        | 1083/7211 [04:52<19:49,  5.15it/s]

Reports:  15%|█▌        | 1084/7211 [04:52<19:57,  5.11it/s]

Reports:  15%|█▌        | 1085/7211 [04:52<20:12,  5.05it/s]

Reports:  15%|█▌        | 1086/7211 [04:53<20:04,  5.09it/s]

Reports:  15%|█▌        | 1087/7211 [04:53<20:00,  5.10it/s]

Reports:  15%|█▌        | 1088/7211 [04:53<20:00,  5.10it/s]

Reports:  15%|█▌        | 1089/7211 [04:53<20:07,  5.07it/s]

Reports:  15%|█▌        | 1090/7211 [04:53<20:04,  5.08it/s]

Reports:  15%|█▌        | 1091/7211 [04:54<20:02,  5.09it/s]

Reports:  15%|█▌        | 1092/7211 [04:54<20:33,  4.96it/s]

Reports:  15%|█▌        | 1093/7211 [04:54<20:19,  5.02it/s]

Reports:  15%|█▌        | 1094/7211 [04:54<20:21,  5.01it/s]

Reports:  15%|█▌        | 1095/7211 [04:54<20:57,  4.87it/s]

Reports:  15%|█▌        | 1096/7211 [04:55<20:18,  5.02it/s]

Reports:  15%|█▌        | 1097/7211 [04:55<20:04,  5.08it/s]

Reports:  15%|█▌        | 1098/7211 [04:55<19:48,  5.14it/s]

Reports:  15%|█▌        | 1099/7211 [04:55<19:49,  5.14it/s]

Reports:  15%|█▌        | 1100/7211 [04:55<20:09,  5.05it/s]

Reports:  15%|█▌        | 1101/7211 [04:56<19:53,  5.12it/s]

Reports:  15%|█▌        | 1102/7211 [04:56<20:22,  5.00it/s]

Reports:  15%|█▌        | 1103/7211 [04:56<20:33,  4.95it/s]

Reports:  15%|█▌        | 1104/7211 [04:56<20:07,  5.06it/s]

Reports:  15%|█▌        | 1105/7211 [04:56<20:18,  5.01it/s]

Reports:  15%|█▌        | 1106/7211 [04:57<20:22,  4.99it/s]

Reports:  15%|█▌        | 1107/7211 [04:57<20:01,  5.08it/s]

Reports:  15%|█▌        | 1108/7211 [04:57<19:52,  5.12it/s]

Reports:  15%|█▌        | 1109/7211 [04:57<19:39,  5.17it/s]

Reports:  15%|█▌        | 1110/7211 [04:57<19:42,  5.16it/s]

Reports:  15%|█▌        | 1111/7211 [04:57<19:52,  5.11it/s]

Reports:  15%|█▌        | 1112/7211 [04:58<19:52,  5.11it/s]

Reports:  15%|█▌        | 1113/7211 [04:58<19:32,  5.20it/s]

Reports:  15%|█▌        | 1114/7211 [04:58<19:56,  5.10it/s]

Reports:  15%|█▌        | 1115/7211 [04:58<19:33,  5.19it/s]

Reports:  15%|█▌        | 1116/7211 [04:58<19:56,  5.09it/s]

Reports:  15%|█▌        | 1117/7211 [04:59<19:40,  5.16it/s]

Reports:  16%|█▌        | 1118/7211 [04:59<19:39,  5.16it/s]

Reports:  16%|█▌        | 1119/7211 [04:59<19:29,  5.21it/s]

Reports:  16%|█▌        | 1120/7211 [04:59<19:43,  5.15it/s]

Reports:  16%|█▌        | 1121/7211 [04:59<20:02,  5.06it/s]

Reports:  16%|█▌        | 1122/7211 [05:00<20:06,  5.05it/s]

Reports:  16%|█▌        | 1123/7211 [05:00<19:48,  5.12it/s]

Reports:  16%|█▌        | 1124/7211 [05:00<19:45,  5.13it/s]

Reports:  16%|█▌        | 1125/7211 [05:00<19:34,  5.18it/s]

Reports:  16%|█▌        | 1126/7211 [05:00<19:31,  5.19it/s]

Reports:  16%|█▌        | 1127/7211 [05:01<19:34,  5.18it/s]

Reports:  16%|█▌        | 1128/7211 [05:01<19:28,  5.20it/s]

Reports:  16%|█▌        | 1129/7211 [05:01<20:17,  5.00it/s]

Reports:  16%|█▌        | 1130/7211 [05:01<20:09,  5.03it/s]

Reports:  16%|█▌        | 1131/7211 [05:01<20:15,  5.00it/s]

Reports:  16%|█▌        | 1132/7211 [05:02<20:11,  5.02it/s]

Reports:  16%|█▌        | 1133/7211 [05:02<20:29,  4.94it/s]

Reports:  16%|█▌        | 1134/7211 [05:02<20:06,  5.04it/s]

Reports:  16%|█▌        | 1135/7211 [05:02<19:48,  5.11it/s]

Reports:  16%|█▌        | 1136/7211 [05:02<19:34,  5.17it/s]

Reports:  16%|█▌        | 1137/7211 [05:03<19:48,  5.11it/s]

Reports:  16%|█▌        | 1138/7211 [05:03<19:19,  5.24it/s]

Reports:  16%|█▌        | 1139/7211 [05:03<19:59,  5.06it/s]

Reports:  16%|█▌        | 1140/7211 [05:03<19:58,  5.06it/s]

Reports:  16%|█▌        | 1141/7211 [05:03<19:48,  5.11it/s]

Reports:  16%|█▌        | 1142/7211 [05:04<19:58,  5.06it/s]

Reports:  16%|█▌        | 1143/7211 [05:04<20:23,  4.96it/s]

Reports:  16%|█▌        | 1144/7211 [05:04<20:06,  5.03it/s]

Reports:  16%|█▌        | 1145/7211 [05:04<19:52,  5.09it/s]

Reports:  16%|█▌        | 1146/7211 [05:04<19:50,  5.10it/s]

Reports:  16%|█▌        | 1147/7211 [05:05<19:51,  5.09it/s]

Reports:  16%|█▌        | 1148/7211 [05:05<19:35,  5.16it/s]

Reports:  16%|█▌        | 1149/7211 [05:05<19:41,  5.13it/s]

Reports:  16%|█▌        | 1150/7211 [05:05<20:26,  4.94it/s]

Reports:  16%|█▌        | 1151/7211 [05:05<20:24,  4.95it/s]

Reports:  16%|█▌        | 1152/7211 [05:06<20:15,  4.98it/s]

Reports:  16%|█▌        | 1153/7211 [05:06<20:18,  4.97it/s]

Reports:  16%|█▌        | 1154/7211 [05:06<19:56,  5.06it/s]

Reports:  16%|█▌        | 1155/7211 [05:06<19:51,  5.08it/s]

Reports:  16%|█▌        | 1156/7211 [05:06<20:00,  5.04it/s]

Reports:  16%|█▌        | 1157/7211 [05:07<19:50,  5.08it/s]

Reports:  16%|█▌        | 1158/7211 [05:07<19:47,  5.10it/s]

Reports:  16%|█▌        | 1159/7211 [05:07<19:43,  5.11it/s]

Reports:  16%|█▌        | 1160/7211 [05:07<19:34,  5.15it/s]

Reports:  16%|█▌        | 1161/7211 [05:07<19:33,  5.16it/s]

Reports:  16%|█▌        | 1162/7211 [05:08<19:53,  5.07it/s]

Reports:  16%|█▌        | 1163/7211 [05:08<20:09,  5.00it/s]

Reports:  16%|█▌        | 1164/7211 [05:08<20:14,  4.98it/s]

Reports:  16%|█▌        | 1165/7211 [05:08<20:57,  4.81it/s]

Reports:  16%|█▌        | 1166/7211 [05:08<20:28,  4.92it/s]

Reports:  16%|█▌        | 1167/7211 [05:09<20:22,  4.94it/s]

Reports:  16%|█▌        | 1168/7211 [05:09<20:28,  4.92it/s]

Reports:  16%|█▌        | 1169/7211 [05:09<20:00,  5.03it/s]

Reports:  16%|█▌        | 1170/7211 [05:09<20:20,  4.95it/s]

Reports:  16%|█▌        | 1171/7211 [05:09<20:24,  4.93it/s]

Reports:  16%|█▋        | 1172/7211 [05:10<20:41,  4.87it/s]

Reports:  16%|█▋        | 1173/7211 [05:10<20:28,  4.91it/s]

Reports:  16%|█▋        | 1174/7211 [05:10<20:20,  4.95it/s]

Reports:  16%|█▋        | 1175/7211 [05:10<20:29,  4.91it/s]

Reports:  16%|█▋        | 1176/7211 [05:10<20:19,  4.95it/s]

Reports:  16%|█▋        | 1177/7211 [05:11<19:50,  5.07it/s]

Reports:  16%|█▋        | 1178/7211 [05:11<19:58,  5.03it/s]

Reports:  16%|█▋        | 1179/7211 [05:11<19:39,  5.12it/s]

Reports:  16%|█▋        | 1180/7211 [05:11<19:40,  5.11it/s]

Reports:  16%|█▋        | 1181/7211 [05:11<19:38,  5.12it/s]

Reports:  16%|█▋        | 1182/7211 [05:12<19:44,  5.09it/s]

Reports:  16%|█▋        | 1183/7211 [05:12<20:08,  4.99it/s]

Reports:  16%|█▋        | 1184/7211 [05:12<20:19,  4.94it/s]

Reports:  16%|█▋        | 1185/7211 [05:12<20:09,  4.98it/s]

Reports:  16%|█▋        | 1186/7211 [05:12<19:53,  5.05it/s]

Reports:  16%|█▋        | 1187/7211 [05:13<19:42,  5.10it/s]

Reports:  16%|█▋        | 1188/7211 [05:13<19:28,  5.15it/s]

Reports:  16%|█▋        | 1189/7211 [05:13<19:48,  5.07it/s]

Reports:  17%|█▋        | 1190/7211 [05:13<19:28,  5.15it/s]

Reports:  17%|█▋        | 1191/7211 [05:13<19:22,  5.18it/s]

Reports:  17%|█▋        | 1192/7211 [05:13<19:40,  5.10it/s]

Reports:  17%|█▋        | 1193/7211 [05:14<19:56,  5.03it/s]

Reports:  17%|█▋        | 1194/7211 [05:14<19:41,  5.09it/s]

Reports:  17%|█▋        | 1195/7211 [05:14<19:35,  5.12it/s]

Reports:  17%|█▋        | 1196/7211 [05:14<19:21,  5.18it/s]

Reports:  17%|█▋        | 1197/7211 [05:14<19:33,  5.12it/s]

Reports:  17%|█▋        | 1198/7211 [05:15<19:54,  5.04it/s]

Reports:  17%|█▋        | 1199/7211 [05:15<19:37,  5.11it/s]

Reports:  17%|█▋        | 1200/7211 [05:15<19:33,  5.12it/s]

Reports:  17%|█▋        | 1201/7211 [05:15<19:27,  5.15it/s]

Reports:  17%|█▋        | 1202/7211 [05:15<19:20,  5.18it/s]

Reports:  17%|█▋        | 1203/7211 [05:16<19:16,  5.19it/s]

Reports:  17%|█▋        | 1204/7211 [05:16<19:24,  5.16it/s]

Reports:  17%|█▋        | 1205/7211 [05:16<19:50,  5.05it/s]

Reports:  17%|█▋        | 1206/7211 [05:16<19:44,  5.07it/s]

Reports:  17%|█▋        | 1207/7211 [05:16<20:06,  4.98it/s]

Reports:  17%|█▋        | 1208/7211 [05:17<20:16,  4.94it/s]

Reports:  17%|█▋        | 1209/7211 [05:17<19:57,  5.01it/s]

Reports:  17%|█▋        | 1210/7211 [05:17<24:05,  4.15it/s]

Reports:  17%|█▋        | 1211/7211 [05:17<23:11,  4.31it/s]

Reports:  17%|█▋        | 1212/7211 [05:18<22:13,  4.50it/s]

Reports:  17%|█▋        | 1213/7211 [05:18<21:17,  4.70it/s]

Reports:  17%|█▋        | 1214/7211 [05:18<23:11,  4.31it/s]

Reports:  17%|█▋        | 1215/7211 [05:18<22:28,  4.45it/s]

Reports:  17%|█▋        | 1216/7211 [05:18<21:23,  4.67it/s]

Reports:  17%|█▋        | 1217/7211 [05:19<20:47,  4.81it/s]

Reports:  17%|█▋        | 1218/7211 [05:19<26:25,  3.78it/s]

Reports:  17%|█▋        | 1219/7211 [05:19<24:17,  4.11it/s]

Reports:  17%|█▋        | 1220/7211 [05:19<23:03,  4.33it/s]

Reports:  17%|█▋        | 1221/7211 [05:20<26:35,  3.75it/s]

Reports:  17%|█▋        | 1222/7211 [05:20<24:15,  4.11it/s]

Reports:  17%|█▋        | 1223/7211 [05:20<22:32,  4.43it/s]

Reports:  17%|█▋        | 1224/7211 [05:20<21:30,  4.64it/s]

Reports:  17%|█▋        | 1225/7211 [05:21<24:07,  4.14it/s]

Reports:  17%|█▋        | 1226/7211 [05:21<22:46,  4.38it/s]

Reports:  17%|█▋        | 1227/7211 [05:22<50:19,  1.98it/s]

Reports:  17%|█▋        | 1228/7211 [05:22<46:01,  2.17it/s]

Reports:  17%|█▋        | 1229/7211 [05:23<38:05,  2.62it/s]

Reports:  17%|█▋        | 1230/7211 [05:23<32:32,  3.06it/s]

Reports:  17%|█▋        | 1231/7211 [05:23<36:40,  2.72it/s]

Reports:  17%|█▋        | 1232/7211 [05:23<32:08,  3.10it/s]

Reports:  17%|█▋        | 1233/7211 [05:24<28:10,  3.54it/s]

Reports:  17%|█▋        | 1234/7211 [05:24<32:26,  3.07it/s]

Reports:  17%|█▋        | 1235/7211 [05:24<28:14,  3.53it/s]

Reports:  17%|█▋        | 1236/7211 [05:24<26:14,  3.80it/s]

Reports:  17%|█▋        | 1237/7211 [05:25<32:06,  3.10it/s]

Reports:  17%|█▋        | 1238/7211 [05:25<28:10,  3.53it/s]

Reports:  17%|█▋        | 1239/7211 [05:26<37:47,  2.63it/s]

Reports:  17%|█▋        | 1240/7211 [05:26<32:22,  3.07it/s]

Reports:  17%|█▋        | 1241/7211 [05:26<28:11,  3.53it/s]

Reports:  17%|█▋        | 1242/7211 [05:26<25:22,  3.92it/s]

Reports:  17%|█▋        | 1243/7211 [05:26<23:40,  4.20it/s]

Reports:  17%|█▋        | 1244/7211 [05:28<48:44,  2.04it/s]

Reports:  17%|█▋        | 1245/7211 [05:28<39:34,  2.51it/s]

Reports:  17%|█▋        | 1246/7211 [05:28<33:23,  2.98it/s]

Reports:  17%|█▋        | 1247/7211 [05:28<29:43,  3.34it/s]

Reports:  17%|█▋        | 1248/7211 [05:28<26:41,  3.72it/s]

Reports:  17%|█▋        | 1249/7211 [05:29<24:10,  4.11it/s]

Reports:  17%|█▋        | 1250/7211 [05:29<22:31,  4.41it/s]

Reports:  17%|█▋        | 1251/7211 [05:29<21:25,  4.63it/s]

Reports:  17%|█▋        | 1252/7211 [05:29<20:42,  4.79it/s]

Reports:  17%|█▋        | 1253/7211 [05:29<21:30,  4.62it/s]

Reports:  17%|█▋        | 1254/7211 [05:30<21:14,  4.67it/s]

Reports:  17%|█▋        | 1255/7211 [05:30<20:35,  4.82it/s]

Reports:  17%|█▋        | 1256/7211 [05:30<20:42,  4.79it/s]

Reports:  17%|█▋        | 1257/7211 [05:30<20:57,  4.73it/s]

Reports:  17%|█▋        | 1258/7211 [05:30<20:12,  4.91it/s]

Reports:  17%|█▋        | 1259/7211 [05:31<19:38,  5.05it/s]

Reports:  17%|█▋        | 1260/7211 [05:31<19:25,  5.11it/s]

Reports:  17%|█▋        | 1261/7211 [05:31<19:59,  4.96it/s]

Reports:  18%|█▊        | 1262/7211 [05:31<22:10,  4.47it/s]

Reports:  18%|█▊        | 1263/7211 [05:31<21:45,  4.56it/s]

Reports:  18%|█▊        | 1264/7211 [05:32<23:27,  4.23it/s]

Reports:  18%|█▊        | 1265/7211 [05:32<22:28,  4.41it/s]

Reports:  18%|█▊        | 1266/7211 [05:32<21:20,  4.64it/s]

Reports:  18%|█▊        | 1267/7211 [05:32<20:29,  4.83it/s]

Reports:  18%|█▊        | 1268/7211 [05:32<20:25,  4.85it/s]

Reports:  18%|█▊        | 1269/7211 [05:33<20:15,  4.89it/s]

Reports:  18%|█▊        | 1270/7211 [05:33<19:59,  4.95it/s]

Reports:  18%|█▊        | 1271/7211 [05:33<20:15,  4.89it/s]

Reports:  18%|█▊        | 1272/7211 [05:33<20:08,  4.91it/s]

Reports:  18%|█▊        | 1273/7211 [05:33<19:51,  4.98it/s]

Reports:  18%|█▊        | 1274/7211 [05:34<19:46,  5.00it/s]

Reports:  18%|█▊        | 1275/7211 [05:34<19:18,  5.12it/s]

Reports:  18%|█▊        | 1276/7211 [05:34<19:21,  5.11it/s]

Reports:  18%|█▊        | 1277/7211 [05:34<19:39,  5.03it/s]

Reports:  18%|█▊        | 1278/7211 [05:34<19:48,  4.99it/s]

Reports:  18%|█▊        | 1279/7211 [05:35<19:43,  5.01it/s]

Reports:  18%|█▊        | 1280/7211 [05:35<19:23,  5.10it/s]

Reports:  18%|█▊        | 1281/7211 [05:35<19:04,  5.18it/s]

Reports:  18%|█▊        | 1282/7211 [05:35<24:15,  4.07it/s]

Reports:  18%|█▊        | 1283/7211 [05:36<22:59,  4.30it/s]

Reports:  18%|█▊        | 1284/7211 [05:36<21:33,  4.58it/s]

Reports:  18%|█▊        | 1285/7211 [05:36<20:45,  4.76it/s]

Reports:  18%|█▊        | 1286/7211 [05:36<20:08,  4.90it/s]

Reports:  18%|█▊        | 1287/7211 [05:36<19:39,  5.02it/s]

Reports:  18%|█▊        | 1288/7211 [05:37<19:48,  4.98it/s]

Reports:  18%|█▊        | 1289/7211 [05:37<19:30,  5.06it/s]

Reports:  18%|█▊        | 1290/7211 [05:37<19:34,  5.04it/s]

Reports:  18%|█▊        | 1291/7211 [05:37<19:20,  5.10it/s]

Reports:  18%|█▊        | 1292/7211 [05:37<19:32,  5.05it/s]

Reports:  18%|█▊        | 1293/7211 [05:38<19:25,  5.08it/s]

Reports:  18%|█▊        | 1294/7211 [05:38<18:52,  5.23it/s]

Reports:  18%|█▊        | 1295/7211 [05:38<19:16,  5.12it/s]

Reports:  18%|█▊        | 1296/7211 [05:38<19:35,  5.03it/s]

Reports:  18%|█▊        | 1297/7211 [05:38<19:22,  5.09it/s]

Reports:  18%|█▊        | 1298/7211 [05:39<19:09,  5.15it/s]

Reports:  18%|█▊        | 1299/7211 [05:39<18:52,  5.22it/s]

Reports:  18%|█▊        | 1300/7211 [05:39<18:52,  5.22it/s]

Reports:  18%|█▊        | 1301/7211 [05:39<19:18,  5.10it/s]

Reports:  18%|█▊        | 1302/7211 [05:39<19:03,  5.17it/s]

Reports:  18%|█▊        | 1303/7211 [05:39<19:00,  5.18it/s]

Reports:  18%|█▊        | 1304/7211 [05:40<19:01,  5.18it/s]

Reports:  18%|█▊        | 1305/7211 [05:40<18:58,  5.19it/s]

Reports:  18%|█▊        | 1306/7211 [05:40<18:59,  5.18it/s]

Reports:  18%|█▊        | 1307/7211 [05:40<18:50,  5.22it/s]

Reports:  18%|█▊        | 1308/7211 [05:40<18:36,  5.29it/s]

Reports:  18%|█▊        | 1309/7211 [05:41<18:33,  5.30it/s]

Reports:  18%|█▊        | 1310/7211 [05:41<18:33,  5.30it/s]

Reports:  18%|█▊        | 1311/7211 [05:41<18:39,  5.27it/s]

Reports:  18%|█▊        | 1312/7211 [05:43<1:25:11,  1.15it/s]

Reports:  18%|█▊        | 1313/7211 [05:44<1:07:34,  1.45it/s]

Reports:  18%|█▊        | 1314/7211 [05:44<53:07,  1.85it/s]

Reports:  18%|█▊        | 1315/7211 [05:44<43:40,  2.25it/s]

Reports:  18%|█▊        | 1316/7211 [05:45<59:06,  1.66it/s]

Reports:  18%|█▊        | 1317/7211 [05:45<47:01,  2.09it/s]

Reports:  18%|█▊        | 1318/7211 [05:46<58:44,  1.67it/s]

Reports:  18%|█▊        | 1319/7211 [05:46<47:26,  2.07it/s]

Reports:  18%|█▊        | 1320/7211 [05:47<38:56,  2.52it/s]

Reports:  18%|█▊        | 1321/7211 [05:47<40:18,  2.44it/s]

Reports:  18%|█▊        | 1322/7211 [05:47<33:52,  2.90it/s]

Reports:  18%|█▊        | 1323/7211 [05:47<29:27,  3.33it/s]

Reports:  18%|█▊        | 1324/7211 [05:48<26:32,  3.70it/s]

Reports:  18%|█▊        | 1325/7211 [05:48<27:05,  3.62it/s]

Reports:  18%|█▊        | 1326/7211 [05:48<24:44,  3.97it/s]

Reports:  18%|█▊        | 1327/7211 [05:48<23:06,  4.24it/s]

Reports:  18%|█▊        | 1328/7211 [05:49<22:26,  4.37it/s]

Reports:  18%|█▊        | 1329/7211 [05:49<21:37,  4.53it/s]

Reports:  18%|█▊        | 1330/7211 [05:49<20:56,  4.68it/s]

Reports:  18%|█▊        | 1331/7211 [05:49<20:50,  4.70it/s]

Reports:  18%|█▊        | 1332/7211 [05:49<19:57,  4.91it/s]

Reports:  18%|█▊        | 1333/7211 [05:50<19:53,  4.93it/s]

Reports:  18%|█▊        | 1334/7211 [05:50<19:47,  4.95it/s]

Reports:  19%|█▊        | 1335/7211 [05:50<19:34,  5.00it/s]

Reports:  19%|█▊        | 1336/7211 [05:50<19:08,  5.12it/s]

Reports:  19%|█▊        | 1337/7211 [05:50<24:13,  4.04it/s]

Reports:  19%|█▊        | 1338/7211 [05:51<23:11,  4.22it/s]

Reports:  19%|█▊        | 1339/7211 [05:51<22:05,  4.43it/s]

Reports:  19%|█▊        | 1340/7211 [05:51<21:03,  4.65it/s]

Reports:  19%|█▊        | 1341/7211 [05:51<20:44,  4.72it/s]

Reports:  19%|█▊        | 1342/7211 [05:51<19:55,  4.91it/s]

Reports:  19%|█▊        | 1343/7211 [05:52<19:52,  4.92it/s]

Reports:  19%|█▊        | 1344/7211 [05:52<19:46,  4.95it/s]

Reports:  19%|█▊        | 1345/7211 [05:52<19:37,  4.98it/s]

Reports:  19%|█▊        | 1346/7211 [05:52<19:24,  5.03it/s]

Reports:  19%|█▊        | 1347/7211 [05:52<19:38,  4.98it/s]

Reports:  19%|█▊        | 1348/7211 [05:53<20:07,  4.85it/s]

Reports:  19%|█▊        | 1349/7211 [05:53<19:32,  5.00it/s]

Reports:  19%|█▊        | 1350/7211 [05:53<20:41,  4.72it/s]

Reports:  19%|█▊        | 1351/7211 [05:53<20:22,  4.79it/s]

Reports:  19%|█▊        | 1352/7211 [05:53<19:39,  4.97it/s]

Reports:  19%|█▉        | 1353/7211 [05:54<20:00,  4.88it/s]

Reports:  19%|█▉        | 1354/7211 [05:54<19:39,  4.97it/s]

Reports:  19%|█▉        | 1355/7211 [05:54<19:16,  5.07it/s]

Reports:  19%|█▉        | 1356/7211 [05:54<19:31,  5.00it/s]

Reports:  19%|█▉        | 1357/7211 [05:55<20:10,  4.83it/s]

Reports:  19%|█▉        | 1358/7211 [05:55<20:06,  4.85it/s]

Reports:  19%|█▉        | 1359/7211 [05:55<20:01,  4.87it/s]

Reports:  19%|█▉        | 1360/7211 [05:55<19:55,  4.89it/s]

Reports:  19%|█▉        | 1361/7211 [05:55<19:29,  5.00it/s]

Reports:  19%|█▉        | 1362/7211 [05:55<19:13,  5.07it/s]

Reports:  19%|█▉        | 1363/7211 [05:56<18:56,  5.15it/s]

Reports:  19%|█▉        | 1364/7211 [05:56<18:55,  5.15it/s]

Reports:  19%|█▉        | 1365/7211 [05:56<19:43,  4.94it/s]

Reports:  19%|█▉        | 1366/7211 [05:56<20:44,  4.70it/s]

Reports:  19%|█▉        | 1367/7211 [05:57<19:49,  4.91it/s]

Reports:  19%|█▉        | 1368/7211 [05:57<19:43,  4.94it/s]

Reports:  19%|█▉        | 1369/7211 [05:57<19:44,  4.93it/s]

Reports:  19%|█▉        | 1370/7211 [05:57<20:07,  4.84it/s]

Reports:  19%|█▉        | 1371/7211 [05:57<19:48,  4.91it/s]

Reports:  19%|█▉        | 1372/7211 [05:58<19:20,  5.03it/s]

Reports:  19%|█▉        | 1373/7211 [05:58<19:01,  5.12it/s]

Reports:  19%|█▉        | 1374/7211 [05:58<19:04,  5.10it/s]

Reports:  19%|█▉        | 1375/7211 [05:58<19:01,  5.11it/s]

Reports:  19%|█▉        | 1376/7211 [05:58<19:21,  5.02it/s]

Reports:  19%|█▉        | 1377/7211 [05:59<19:32,  4.98it/s]

Reports:  19%|█▉        | 1378/7211 [05:59<19:26,  5.00it/s]

Reports:  19%|█▉        | 1379/7211 [05:59<19:02,  5.10it/s]

Reports:  19%|█▉        | 1380/7211 [05:59<19:28,  4.99it/s]

Reports:  19%|█▉        | 1381/7211 [05:59<19:10,  5.07it/s]

Reports:  19%|█▉        | 1382/7211 [06:00<19:29,  4.98it/s]

Reports:  19%|█▉        | 1383/7211 [06:00<19:13,  5.05it/s]

Reports:  19%|█▉        | 1384/7211 [06:00<19:05,  5.09it/s]

Reports:  19%|█▉        | 1385/7211 [06:00<18:56,  5.12it/s]

Reports:  19%|█▉        | 1386/7211 [06:00<18:45,  5.18it/s]

Reports:  19%|█▉        | 1387/7211 [06:00<18:40,  5.20it/s]

Reports:  19%|█▉        | 1388/7211 [06:03<1:17:37,  1.25it/s]

Reports:  19%|█▉        | 1389/7211 [06:03<1:00:07,  1.61it/s]

Reports:  19%|█▉        | 1390/7211 [06:03<47:47,  2.03it/s]

Reports:  19%|█▉        | 1391/7211 [06:03<39:04,  2.48it/s]

Reports:  19%|█▉        | 1392/7211 [06:03<33:20,  2.91it/s]

Reports:  19%|█▉        | 1393/7211 [06:04<29:15,  3.31it/s]

Reports:  19%|█▉        | 1394/7211 [06:04<26:46,  3.62it/s]

Reports:  19%|█▉        | 1395/7211 [06:04<24:06,  4.02it/s]

Reports:  19%|█▉        | 1396/7211 [06:06<58:35,  1.65it/s]

Reports:  19%|█▉        | 1397/7211 [06:06<47:03,  2.06it/s]

Reports:  19%|█▉        | 1398/7211 [06:06<38:39,  2.51it/s]

Reports:  19%|█▉        | 1399/7211 [06:06<33:09,  2.92it/s]

Reports:  19%|█▉        | 1400/7211 [06:06<29:09,  3.32it/s]

Reports:  19%|█▉        | 1401/7211 [06:07<25:54,  3.74it/s]

Reports:  19%|█▉        | 1402/7211 [06:07<23:48,  4.07it/s]

Reports:  19%|█▉        | 1403/7211 [06:07<22:48,  4.24it/s]

Reports:  19%|█▉        | 1404/7211 [06:07<22:16,  4.35it/s]

Reports:  19%|█▉        | 1405/7211 [06:07<21:06,  4.59it/s]

Reports:  19%|█▉        | 1406/7211 [06:08<20:29,  4.72it/s]

Reports:  20%|█▉        | 1407/7211 [06:08<35:51,  2.70it/s]

Reports:  20%|█▉        | 1408/7211 [06:08<30:50,  3.14it/s]

Reports:  20%|█▉        | 1409/7211 [06:09<27:12,  3.55it/s]

Reports:  20%|█▉        | 1410/7211 [06:09<24:24,  3.96it/s]

Reports:  20%|█▉        | 1411/7211 [06:09<22:45,  4.25it/s]

Reports:  20%|█▉        | 1412/7211 [06:09<21:29,  4.50it/s]

Reports:  20%|█▉        | 1413/7211 [06:09<21:11,  4.56it/s]

Reports:  20%|█▉        | 1414/7211 [06:10<20:55,  4.62it/s]

Reports:  20%|█▉        | 1415/7211 [06:10<20:03,  4.82it/s]

Reports:  20%|█▉        | 1416/7211 [06:10<19:27,  4.97it/s]

Reports:  20%|█▉        | 1417/7211 [06:10<19:04,  5.06it/s]

Reports:  20%|█▉        | 1418/7211 [06:10<19:25,  4.97it/s]

Reports:  20%|█▉        | 1419/7211 [06:11<19:24,  4.97it/s]

Reports:  20%|█▉        | 1420/7211 [06:11<19:07,  5.05it/s]

Reports:  20%|█▉        | 1421/7211 [06:11<18:47,  5.14it/s]

Reports:  20%|█▉        | 1422/7211 [06:12<29:16,  3.30it/s]

Reports:  20%|█▉        | 1423/7211 [06:12<26:15,  3.67it/s]

Reports:  20%|█▉        | 1424/7211 [06:12<24:22,  3.96it/s]

Reports:  20%|█▉        | 1425/7211 [06:12<23:07,  4.17it/s]

Reports:  20%|█▉        | 1426/7211 [06:12<21:45,  4.43it/s]

Reports:  20%|█▉        | 1427/7211 [06:13<20:40,  4.66it/s]

Reports:  20%|█▉        | 1428/7211 [06:13<20:39,  4.67it/s]

Reports:  20%|█▉        | 1429/7211 [06:13<20:18,  4.75it/s]

Reports:  20%|█▉        | 1430/7211 [06:13<20:07,  4.79it/s]

Reports:  20%|█▉        | 1431/7211 [06:13<19:36,  4.91it/s]

Reports:  20%|█▉        | 1432/7211 [06:14<19:01,  5.06it/s]

Reports:  20%|█▉        | 1433/7211 [06:14<18:52,  5.10it/s]

Reports:  20%|█▉        | 1434/7211 [06:14<18:52,  5.10it/s]

Reports:  20%|█▉        | 1435/7211 [06:14<18:58,  5.08it/s]

Reports:  20%|█▉        | 1436/7211 [06:14<18:45,  5.13it/s]

Reports:  20%|█▉        | 1437/7211 [06:15<18:38,  5.16it/s]

Reports:  20%|█▉        | 1438/7211 [06:15<18:44,  5.13it/s]

Reports:  20%|█▉        | 1439/7211 [06:15<18:38,  5.16it/s]

Reports:  20%|█▉        | 1440/7211 [06:15<18:25,  5.22it/s]

Reports:  20%|█▉        | 1441/7211 [06:15<19:31,  4.92it/s]

Reports:  20%|█▉        | 1442/7211 [06:16<35:03,  2.74it/s]

Reports:  20%|██        | 1443/7211 [06:16<30:54,  3.11it/s]

Reports:  20%|██        | 1444/7211 [06:17<27:29,  3.50it/s]

Reports:  20%|██        | 1445/7211 [06:17<24:57,  3.85it/s]

Reports:  20%|██        | 1446/7211 [06:17<22:50,  4.21it/s]

Reports:  20%|██        | 1447/7211 [06:17<21:16,  4.51it/s]

Reports:  20%|██        | 1448/7211 [06:17<20:11,  4.76it/s]

Reports:  20%|██        | 1449/7211 [06:17<20:01,  4.80it/s]

Reports:  20%|██        | 1450/7211 [06:18<19:41,  4.88it/s]

Reports:  20%|██        | 1451/7211 [06:18<19:25,  4.94it/s]

Reports:  20%|██        | 1452/7211 [06:18<19:12,  5.00it/s]

Reports:  20%|██        | 1453/7211 [06:18<19:18,  4.97it/s]

Reports:  20%|██        | 1454/7211 [06:18<19:02,  5.04it/s]

Reports:  20%|██        | 1455/7211 [06:19<18:37,  5.15it/s]

Reports:  20%|██        | 1456/7211 [06:19<18:59,  5.05it/s]

Reports:  20%|██        | 1457/7211 [06:19<18:53,  5.08it/s]

Reports:  20%|██        | 1458/7211 [06:19<18:38,  5.15it/s]

Reports:  20%|██        | 1459/7211 [06:19<18:50,  5.09it/s]

Reports:  20%|██        | 1460/7211 [06:20<18:44,  5.11it/s]

Reports:  20%|██        | 1461/7211 [06:20<18:51,  5.08it/s]

Reports:  20%|██        | 1462/7211 [06:32<6:14:10,  3.91s/it]

Reports:  20%|██        | 1463/7211 [06:33<4:27:40,  2.79s/it]

Reports:  20%|██        | 1464/7211 [06:33<3:12:48,  2.01s/it]

Reports:  20%|██        | 1465/7211 [06:33<2:20:43,  1.47s/it]

Reports:  20%|██        | 1466/7211 [06:33<1:44:38,  1.09s/it]

Reports:  20%|██        | 1467/7211 [06:33<1:18:44,  1.22it/s]

Reports:  20%|██        | 1468/7211 [06:34<1:00:49,  1.57it/s]

Reports:  20%|██        | 1469/7211 [06:34<48:02,  1.99it/s]

Reports:  20%|██        | 1470/7211 [06:34<39:06,  2.45it/s]

Reports:  20%|██        | 1471/7211 [06:34<32:51,  2.91it/s]

Reports:  20%|██        | 1472/7211 [06:34<28:45,  3.33it/s]

Reports:  20%|██        | 1473/7211 [06:35<26:02,  3.67it/s]

Reports:  20%|██        | 1474/7211 [06:35<23:40,  4.04it/s]

Reports:  20%|██        | 1475/7211 [06:35<22:03,  4.33it/s]

Reports:  20%|██        | 1476/7211 [06:35<21:01,  4.54it/s]

Reports:  20%|██        | 1477/7211 [06:35<20:34,  4.64it/s]

Reports:  20%|██        | 1478/7211 [06:36<20:02,  4.77it/s]

Reports:  21%|██        | 1479/7211 [06:36<19:48,  4.82it/s]

Reports:  21%|██        | 1480/7211 [06:36<19:54,  4.80it/s]

Reports:  21%|██        | 1481/7211 [06:36<19:14,  4.96it/s]

Reports:  21%|██        | 1482/7211 [06:36<18:54,  5.05it/s]

Reports:  21%|██        | 1483/7211 [06:37<19:06,  5.00it/s]

Reports:  21%|██        | 1484/7211 [06:37<18:46,  5.08it/s]

Reports:  21%|██        | 1485/7211 [06:37<18:35,  5.13it/s]

Reports:  21%|██        | 1486/7211 [06:37<18:32,  5.15it/s]

Reports:  21%|██        | 1487/7211 [06:37<18:51,  5.06it/s]

Reports:  21%|██        | 1488/7211 [06:37<18:22,  5.19it/s]

Reports:  21%|██        | 1489/7211 [06:38<18:14,  5.23it/s]

Reports:  21%|██        | 1490/7211 [06:38<18:08,  5.26it/s]

Reports:  21%|██        | 1491/7211 [06:38<18:52,  5.05it/s]

Reports:  21%|██        | 1492/7211 [06:38<18:59,  5.02it/s]

Reports:  21%|██        | 1493/7211 [06:38<18:43,  5.09it/s]

Reports:  21%|██        | 1494/7211 [06:39<18:49,  5.06it/s]

Reports:  21%|██        | 1495/7211 [06:39<18:54,  5.04it/s]

Reports:  21%|██        | 1496/7211 [06:39<18:29,  5.15it/s]

Reports:  21%|██        | 1497/7211 [06:39<18:08,  5.25it/s]

Reports:  21%|██        | 1498/7211 [06:39<18:38,  5.11it/s]

Reports:  21%|██        | 1499/7211 [06:40<18:38,  5.11it/s]

Reports:  21%|██        | 1500/7211 [06:40<18:43,  5.08it/s]

Reports:  21%|██        | 1501/7211 [06:40<18:48,  5.06it/s]

Reports:  21%|██        | 1502/7211 [06:40<18:32,  5.13it/s]

Reports:  21%|██        | 1503/7211 [06:40<20:51,  4.56it/s]

Reports:  21%|██        | 1504/7211 [06:41<20:29,  4.64it/s]

Reports:  21%|██        | 1505/7211 [06:41<19:55,  4.77it/s]

Reports:  21%|██        | 1506/7211 [06:41<19:33,  4.86it/s]

Reports:  21%|██        | 1507/7211 [06:41<19:06,  4.97it/s]

Reports:  21%|██        | 1508/7211 [06:41<18:47,  5.06it/s]

Reports:  21%|██        | 1509/7211 [06:42<19:21,  4.91it/s]

Reports:  21%|██        | 1510/7211 [06:42<18:56,  5.02it/s]

Reports:  21%|██        | 1511/7211 [06:42<18:43,  5.07it/s]

Reports:  21%|██        | 1512/7211 [06:42<18:50,  5.04it/s]

Reports:  21%|██        | 1513/7211 [06:42<18:52,  5.03it/s]

Reports:  21%|██        | 1514/7211 [06:43<18:54,  5.02it/s]

Reports:  21%|██        | 1515/7211 [06:43<18:44,  5.07it/s]

Reports:  21%|██        | 1516/7211 [06:43<18:48,  5.05it/s]

Reports:  21%|██        | 1517/7211 [06:43<18:49,  5.04it/s]

Reports:  21%|██        | 1518/7211 [06:43<18:40,  5.08it/s]

Reports:  21%|██        | 1519/7211 [06:44<19:11,  4.94it/s]

Reports:  21%|██        | 1520/7211 [06:44<18:51,  5.03it/s]

Reports:  21%|██        | 1521/7211 [06:44<19:13,  4.93it/s]

Reports:  21%|██        | 1522/7211 [06:44<18:55,  5.01it/s]

Reports:  21%|██        | 1523/7211 [06:44<18:43,  5.06it/s]

Reports:  21%|██        | 1524/7211 [06:45<21:30,  4.41it/s]

Reports:  21%|██        | 1525/7211 [06:45<21:59,  4.31it/s]

Reports:  21%|██        | 1526/7211 [06:45<20:58,  4.52it/s]

Reports:  21%|██        | 1527/7211 [06:45<20:09,  4.70it/s]

Reports:  21%|██        | 1528/7211 [06:46<19:55,  4.75it/s]

Reports:  21%|██        | 1529/7211 [06:46<19:13,  4.92it/s]

Reports:  21%|██        | 1530/7211 [06:46<19:04,  4.96it/s]

Reports:  21%|██        | 1531/7211 [06:46<18:59,  4.99it/s]

Reports:  21%|██        | 1532/7211 [06:46<18:39,  5.07it/s]

Reports:  21%|██▏       | 1533/7211 [06:47<18:27,  5.13it/s]

Reports:  21%|██▏       | 1534/7211 [06:47<18:31,  5.11it/s]

Reports:  21%|██▏       | 1535/7211 [06:47<18:25,  5.13it/s]

Reports:  21%|██▏       | 1536/7211 [06:47<18:22,  5.15it/s]

Reports:  21%|██▏       | 1537/7211 [06:47<18:44,  5.05it/s]

Reports:  21%|██▏       | 1538/7211 [06:48<18:37,  5.08it/s]

Reports:  21%|██▏       | 1539/7211 [06:48<18:32,  5.10it/s]

Reports:  21%|██▏       | 1540/7211 [06:48<18:46,  5.03it/s]

Reports:  21%|██▏       | 1541/7211 [06:48<18:41,  5.06it/s]

Reports:  21%|██▏       | 1542/7211 [06:48<18:14,  5.18it/s]

Reports:  21%|██▏       | 1543/7211 [06:48<17:54,  5.28it/s]

Reports:  21%|██▏       | 1544/7211 [06:49<18:00,  5.24it/s]

Reports:  21%|██▏       | 1545/7211 [06:49<17:59,  5.25it/s]

Reports:  21%|██▏       | 1546/7211 [06:49<17:49,  5.30it/s]

Reports:  21%|██▏       | 1547/7211 [06:49<17:51,  5.29it/s]

Reports:  21%|██▏       | 1548/7211 [06:49<17:54,  5.27it/s]

Reports:  21%|██▏       | 1549/7211 [06:50<17:54,  5.27it/s]

Reports:  21%|██▏       | 1550/7211 [06:50<18:08,  5.20it/s]

Reports:  22%|██▏       | 1551/7211 [06:50<18:02,  5.23it/s]

Reports:  22%|██▏       | 1552/7211 [06:50<18:08,  5.20it/s]

Reports:  22%|██▏       | 1553/7211 [06:50<18:20,  5.14it/s]

Reports:  22%|██▏       | 1554/7211 [06:51<18:15,  5.16it/s]

Reports:  22%|██▏       | 1555/7211 [06:51<18:16,  5.16it/s]

Reports:  22%|██▏       | 1556/7211 [06:51<17:59,  5.24it/s]

Reports:  22%|██▏       | 1557/7211 [06:51<17:47,  5.30it/s]

Reports:  22%|██▏       | 1558/7211 [06:51<17:45,  5.31it/s]

Reports:  22%|██▏       | 1559/7211 [06:52<17:53,  5.27it/s]

Reports:  22%|██▏       | 1560/7211 [06:52<17:50,  5.28it/s]

Reports:  22%|██▏       | 1561/7211 [06:52<18:03,  5.21it/s]

Reports:  22%|██▏       | 1562/7211 [06:52<19:07,  4.92it/s]

Reports:  22%|██▏       | 1563/7211 [06:52<18:46,  5.01it/s]

Reports:  22%|██▏       | 1564/7211 [06:53<18:57,  4.96it/s]

Reports:  22%|██▏       | 1565/7211 [06:53<18:28,  5.09it/s]

Reports:  22%|██▏       | 1566/7211 [06:53<18:12,  5.17it/s]

Reports:  22%|██▏       | 1567/7211 [06:53<18:50,  4.99it/s]

Reports:  22%|██▏       | 1568/7211 [06:53<18:38,  5.04it/s]

Reports:  22%|██▏       | 1569/7211 [06:54<18:57,  4.96it/s]

Reports:  22%|██▏       | 1570/7211 [06:54<18:59,  4.95it/s]

Reports:  22%|██▏       | 1571/7211 [06:54<18:37,  5.05it/s]

Reports:  22%|██▏       | 1572/7211 [06:54<18:39,  5.03it/s]

Reports:  22%|██▏       | 1573/7211 [06:54<18:51,  4.98it/s]

Reports:  22%|██▏       | 1574/7211 [06:55<18:49,  4.99it/s]

Reports:  22%|██▏       | 1575/7211 [06:55<18:09,  5.17it/s]

Reports:  22%|██▏       | 1576/7211 [06:55<18:23,  5.11it/s]

Reports:  22%|██▏       | 1577/7211 [06:55<18:01,  5.21it/s]

Reports:  22%|██▏       | 1578/7211 [06:55<18:15,  5.14it/s]

Reports:  22%|██▏       | 1579/7211 [06:56<18:13,  5.15it/s]

Reports:  22%|██▏       | 1580/7211 [06:56<18:46,  5.00it/s]

Reports:  22%|██▏       | 1581/7211 [06:56<18:28,  5.08it/s]

Reports:  22%|██▏       | 1582/7211 [06:56<19:13,  4.88it/s]

Reports:  22%|██▏       | 1583/7211 [06:56<18:40,  5.02it/s]

Reports:  22%|██▏       | 1584/7211 [06:57<18:29,  5.07it/s]

Reports:  22%|██▏       | 1585/7211 [06:57<18:19,  5.12it/s]

Reports:  22%|██▏       | 1586/7211 [06:57<18:14,  5.14it/s]

Reports:  22%|██▏       | 1587/7211 [06:57<18:28,  5.07it/s]

Reports:  22%|██▏       | 1588/7211 [06:57<18:32,  5.05it/s]

Reports:  22%|██▏       | 1589/7211 [06:58<18:37,  5.03it/s]

Reports:  22%|██▏       | 1590/7211 [06:58<18:33,  5.05it/s]

Reports:  22%|██▏       | 1591/7211 [06:58<18:16,  5.12it/s]

Reports:  22%|██▏       | 1592/7211 [06:58<18:15,  5.13it/s]

Reports:  22%|██▏       | 1593/7211 [06:58<17:55,  5.22it/s]

Reports:  22%|██▏       | 1594/7211 [06:58<18:09,  5.16it/s]

Reports:  22%|██▏       | 1595/7211 [06:59<18:06,  5.17it/s]

Reports:  22%|██▏       | 1596/7211 [06:59<18:05,  5.17it/s]

Reports:  22%|██▏       | 1597/7211 [06:59<18:01,  5.19it/s]

Reports:  22%|██▏       | 1598/7211 [06:59<18:07,  5.16it/s]

Reports:  22%|██▏       | 1599/7211 [06:59<18:13,  5.13it/s]

Reports:  22%|██▏       | 1600/7211 [07:00<18:19,  5.11it/s]

Reports:  22%|██▏       | 1601/7211 [07:00<17:57,  5.21it/s]

Reports:  22%|██▏       | 1602/7211 [07:00<17:58,  5.20it/s]

Reports:  22%|██▏       | 1603/7211 [07:00<18:39,  5.01it/s]

Reports:  22%|██▏       | 1604/7211 [07:00<18:27,  5.06it/s]

Reports:  22%|██▏       | 1605/7211 [07:01<17:56,  5.21it/s]

Reports:  22%|██▏       | 1606/7211 [07:01<18:08,  5.15it/s]

Reports:  22%|██▏       | 1607/7211 [07:01<17:55,  5.21it/s]

Reports:  22%|██▏       | 1608/7211 [07:01<20:14,  4.61it/s]

Reports:  22%|██▏       | 1609/7211 [07:01<19:35,  4.77it/s]

Reports:  22%|██▏       | 1610/7211 [07:02<19:04,  4.89it/s]

Reports:  22%|██▏       | 1611/7211 [07:02<18:37,  5.01it/s]

Reports:  22%|██▏       | 1612/7211 [07:02<18:34,  5.02it/s]

Reports:  22%|██▏       | 1613/7211 [07:02<18:18,  5.09it/s]

Reports:  22%|██▏       | 1614/7211 [07:02<18:30,  5.04it/s]

Reports:  22%|██▏       | 1615/7211 [07:03<18:21,  5.08it/s]

Reports:  22%|██▏       | 1616/7211 [07:03<18:12,  5.12it/s]

Reports:  22%|██▏       | 1617/7211 [07:03<18:10,  5.13it/s]

Reports:  22%|██▏       | 1618/7211 [07:03<18:08,  5.14it/s]

Reports:  22%|██▏       | 1619/7211 [07:03<18:01,  5.17it/s]

Reports:  22%|██▏       | 1620/7211 [07:04<17:52,  5.21it/s]

Reports:  22%|██▏       | 1621/7211 [07:04<17:35,  5.30it/s]

Reports:  22%|██▏       | 1622/7211 [07:04<17:23,  5.36it/s]

Reports:  23%|██▎       | 1623/7211 [07:04<17:24,  5.35it/s]

Reports:  23%|██▎       | 1624/7211 [07:04<17:23,  5.36it/s]

Reports:  23%|██▎       | 1625/7211 [07:05<17:34,  5.30it/s]

Reports:  23%|██▎       | 1626/7211 [07:05<17:27,  5.33it/s]

Reports:  23%|██▎       | 1627/7211 [07:05<18:16,  5.09it/s]

Reports:  23%|██▎       | 1628/7211 [07:05<18:59,  4.90it/s]

Reports:  23%|██▎       | 1629/7211 [07:05<18:50,  4.94it/s]

Reports:  23%|██▎       | 1630/7211 [07:06<18:14,  5.10it/s]

Reports:  23%|██▎       | 1631/7211 [07:06<18:09,  5.12it/s]

Reports:  23%|██▎       | 1632/7211 [07:06<17:59,  5.17it/s]

Reports:  23%|██▎       | 1633/7211 [07:06<17:54,  5.19it/s]

Reports:  23%|██▎       | 1634/7211 [07:06<18:05,  5.14it/s]

Reports:  23%|██▎       | 1635/7211 [07:06<18:00,  5.16it/s]

Reports:  23%|██▎       | 1636/7211 [07:07<17:54,  5.19it/s]

Reports:  23%|██▎       | 1637/7211 [07:07<18:09,  5.12it/s]

Reports:  23%|██▎       | 1638/7211 [07:07<18:35,  5.00it/s]

Reports:  23%|██▎       | 1639/7211 [07:07<18:11,  5.11it/s]

Reports:  23%|██▎       | 1640/7211 [07:07<17:46,  5.23it/s]

Reports:  23%|██▎       | 1641/7211 [07:08<18:04,  5.14it/s]

Reports:  23%|██▎       | 1642/7211 [07:08<18:17,  5.08it/s]

Reports:  23%|██▎       | 1643/7211 [07:08<18:12,  5.10it/s]

Reports:  23%|██▎       | 1644/7211 [07:08<18:29,  5.02it/s]

Reports:  23%|██▎       | 1645/7211 [07:08<18:16,  5.08it/s]

Reports:  23%|██▎       | 1646/7211 [07:09<18:28,  5.02it/s]

Reports:  23%|██▎       | 1647/7211 [07:09<18:07,  5.11it/s]

Reports:  23%|██▎       | 1648/7211 [07:09<18:10,  5.10it/s]

Reports:  23%|██▎       | 1649/7211 [07:09<18:00,  5.15it/s]

Reports:  23%|██▎       | 1650/7211 [07:09<18:18,  5.06it/s]

Reports:  23%|██▎       | 1651/7211 [07:10<18:05,  5.12it/s]

Reports:  23%|██▎       | 1652/7211 [07:10<22:25,  4.13it/s]

Reports:  23%|██▎       | 1653/7211 [07:10<21:11,  4.37it/s]

Reports:  23%|██▎       | 1654/7211 [07:10<20:14,  4.58it/s]

Reports:  23%|██▎       | 1655/7211 [07:11<19:26,  4.76it/s]

Reports:  23%|██▎       | 1656/7211 [07:11<19:13,  4.82it/s]

Reports:  23%|██▎       | 1657/7211 [07:11<18:56,  4.89it/s]

Reports:  23%|██▎       | 1658/7211 [07:11<18:43,  4.94it/s]

Reports:  23%|██▎       | 1659/7211 [07:11<18:13,  5.08it/s]

Reports:  23%|██▎       | 1660/7211 [07:12<18:01,  5.13it/s]

Reports:  23%|██▎       | 1661/7211 [07:12<17:48,  5.19it/s]

Reports:  23%|██▎       | 1662/7211 [07:12<18:19,  5.04it/s]

Reports:  23%|██▎       | 1663/7211 [07:12<18:03,  5.12it/s]

Reports:  23%|██▎       | 1664/7211 [07:12<17:51,  5.18it/s]

Reports:  23%|██▎       | 1665/7211 [07:12<17:47,  5.20it/s]

Reports:  23%|██▎       | 1666/7211 [07:13<17:25,  5.30it/s]

Reports:  23%|██▎       | 1667/7211 [07:13<21:23,  4.32it/s]

Reports:  23%|██▎       | 1668/7211 [07:13<20:28,  4.51it/s]

Reports:  23%|██▎       | 1669/7211 [07:13<20:19,  4.55it/s]

Reports:  23%|██▎       | 1670/7211 [07:14<19:34,  4.72it/s]

Reports:  23%|██▎       | 1671/7211 [07:14<19:10,  4.82it/s]

Reports:  23%|██▎       | 1672/7211 [07:14<18:31,  4.98it/s]

Reports:  23%|██▎       | 1673/7211 [07:14<18:47,  4.91it/s]

Reports:  23%|██▎       | 1674/7211 [07:14<19:06,  4.83it/s]

Reports:  23%|██▎       | 1675/7211 [07:15<18:59,  4.86it/s]

Reports:  23%|██▎       | 1676/7211 [07:15<18:33,  4.97it/s]

Reports:  23%|██▎       | 1677/7211 [07:15<18:36,  4.96it/s]

Reports:  23%|██▎       | 1678/7211 [07:15<18:17,  5.04it/s]

Reports:  23%|██▎       | 1679/7211 [07:15<17:48,  5.18it/s]

Reports:  23%|██▎       | 1680/7211 [07:16<17:36,  5.23it/s]

Reports:  23%|██▎       | 1681/7211 [07:16<17:29,  5.27it/s]

Reports:  23%|██▎       | 1682/7211 [07:16<17:39,  5.22it/s]

Reports:  23%|██▎       | 1683/7211 [07:16<17:36,  5.23it/s]

Reports:  23%|██▎       | 1684/7211 [07:16<17:25,  5.29it/s]

Reports:  23%|██▎       | 1685/7211 [07:17<17:50,  5.16it/s]

Reports:  23%|██▎       | 1686/7211 [07:17<17:38,  5.22it/s]

Reports:  23%|██▎       | 1687/7211 [07:17<17:46,  5.18it/s]

Reports:  23%|██▎       | 1688/7211 [07:17<17:40,  5.21it/s]

Reports:  23%|██▎       | 1689/7211 [07:17<17:58,  5.12it/s]

Reports:  23%|██▎       | 1690/7211 [07:18<19:26,  4.73it/s]

Reports:  23%|██▎       | 1691/7211 [07:18<18:54,  4.87it/s]

Reports:  23%|██▎       | 1692/7211 [07:18<18:52,  4.87it/s]

Reports:  23%|██▎       | 1693/7211 [07:18<18:58,  4.85it/s]

Reports:  23%|██▎       | 1694/7211 [07:18<18:49,  4.89it/s]

Reports:  24%|██▎       | 1695/7211 [07:19<18:32,  4.96it/s]

Reports:  24%|██▎       | 1696/7211 [07:19<18:05,  5.08it/s]

Reports:  24%|██▎       | 1697/7211 [07:19<17:38,  5.21it/s]

Reports:  24%|██▎       | 1698/7211 [07:19<17:45,  5.18it/s]

Reports:  24%|██▎       | 1699/7211 [07:19<17:30,  5.25it/s]

Reports:  24%|██▎       | 1700/7211 [07:19<17:17,  5.31it/s]

Reports:  24%|██▎       | 1701/7211 [07:20<17:28,  5.26it/s]

Reports:  24%|██▎       | 1702/7211 [07:20<18:05,  5.08it/s]

Reports:  24%|██▎       | 1703/7211 [07:20<17:40,  5.19it/s]

Reports:  24%|██▎       | 1704/7211 [07:20<17:33,  5.23it/s]

Reports:  24%|██▎       | 1705/7211 [07:20<17:15,  5.31it/s]

Reports:  24%|██▎       | 1706/7211 [07:21<17:18,  5.30it/s]

Reports:  24%|██▎       | 1707/7211 [07:21<17:26,  5.26it/s]

Reports:  24%|██▎       | 1708/7211 [07:21<17:17,  5.31it/s]

Reports:  24%|██▎       | 1709/7211 [07:21<17:12,  5.33it/s]

Reports:  24%|██▎       | 1710/7211 [07:21<18:01,  5.09it/s]

Reports:  24%|██▎       | 1711/7211 [07:22<17:46,  5.16it/s]

Reports:  24%|██▎       | 1712/7211 [07:22<18:08,  5.05it/s]

Reports:  24%|██▍       | 1713/7211 [07:22<17:56,  5.11it/s]

Reports:  24%|██▍       | 1714/7211 [07:22<17:52,  5.12it/s]

Reports:  24%|██▍       | 1715/7211 [07:22<18:06,  5.06it/s]

Reports:  24%|██▍       | 1716/7211 [07:23<18:02,  5.08it/s]

Reports:  24%|██▍       | 1717/7211 [07:23<17:39,  5.19it/s]

Reports:  24%|██▍       | 1718/7211 [07:23<18:04,  5.06it/s]

Reports:  24%|██▍       | 1719/7211 [07:23<17:52,  5.12it/s]

Reports:  24%|██▍       | 1720/7211 [07:23<17:32,  5.22it/s]

Reports:  24%|██▍       | 1721/7211 [07:24<17:39,  5.18it/s]

Reports:  24%|██▍       | 1722/7211 [07:24<17:29,  5.23it/s]

Reports:  24%|██▍       | 1723/7211 [07:24<17:27,  5.24it/s]

Reports:  24%|██▍       | 1724/7211 [07:24<17:46,  5.15it/s]

Reports:  24%|██▍       | 1725/7211 [07:24<17:43,  5.16it/s]

Reports:  24%|██▍       | 1726/7211 [07:25<17:28,  5.23it/s]

Reports:  24%|██▍       | 1727/7211 [07:25<17:23,  5.26it/s]

Reports:  24%|██▍       | 1728/7211 [07:25<17:37,  5.18it/s]

Reports:  24%|██▍       | 1729/7211 [07:25<17:25,  5.24it/s]

Reports:  24%|██▍       | 1730/7211 [07:25<17:29,  5.22it/s]

Reports:  24%|██▍       | 1731/7211 [07:25<17:28,  5.23it/s]

Reports:  24%|██▍       | 1732/7211 [07:26<17:16,  5.28it/s]

Reports:  24%|██▍       | 1733/7211 [07:26<17:28,  5.23it/s]

Reports:  24%|██▍       | 1734/7211 [07:26<17:33,  5.20it/s]

Reports:  24%|██▍       | 1735/7211 [07:26<17:26,  5.23it/s]

Reports:  24%|██▍       | 1736/7211 [07:26<17:49,  5.12it/s]

Reports:  24%|██▍       | 1737/7211 [07:27<17:40,  5.16it/s]

Reports:  24%|██▍       | 1738/7211 [07:27<17:35,  5.19it/s]

Reports:  24%|██▍       | 1739/7211 [07:27<17:51,  5.11it/s]

Reports:  24%|██▍       | 1740/7211 [07:27<17:35,  5.18it/s]

Reports:  24%|██▍       | 1741/7211 [07:27<17:33,  5.19it/s]

Reports:  24%|██▍       | 1742/7211 [07:28<17:30,  5.21it/s]

Reports:  24%|██▍       | 1743/7211 [07:28<17:29,  5.21it/s]

Reports:  24%|██▍       | 1744/7211 [07:28<17:18,  5.26it/s]

Reports:  24%|██▍       | 1745/7211 [07:28<17:58,  5.07it/s]

Reports:  24%|██▍       | 1746/7211 [07:28<17:38,  5.16it/s]

Reports:  24%|██▍       | 1747/7211 [07:29<17:43,  5.14it/s]

Reports:  24%|██▍       | 1748/7211 [07:29<17:43,  5.14it/s]

Reports:  24%|██▍       | 1749/7211 [07:29<17:33,  5.19it/s]

Reports:  24%|██▍       | 1750/7211 [07:29<18:04,  5.04it/s]

Reports:  24%|██▍       | 1751/7211 [07:29<17:45,  5.12it/s]

Reports:  24%|██▍       | 1752/7211 [07:30<17:32,  5.19it/s]

Reports:  24%|██▍       | 1753/7211 [07:30<17:48,  5.11it/s]

Reports:  24%|██▍       | 1754/7211 [07:30<17:48,  5.11it/s]

Reports:  24%|██▍       | 1755/7211 [07:30<17:28,  5.20it/s]

Reports:  24%|██▍       | 1756/7211 [07:30<17:25,  5.22it/s]

Reports:  24%|██▍       | 1757/7211 [07:31<17:47,  5.11it/s]

Reports:  24%|██▍       | 1758/7211 [07:31<17:35,  5.17it/s]

Reports:  24%|██▍       | 1759/7211 [07:31<17:37,  5.15it/s]

Reports:  24%|██▍       | 1760/7211 [07:31<17:17,  5.25it/s]

Reports:  24%|██▍       | 1761/7211 [07:31<17:07,  5.30it/s]

Reports:  24%|██▍       | 1762/7211 [07:31<17:08,  5.30it/s]

Reports:  24%|██▍       | 1763/7211 [07:32<17:45,  5.11it/s]

Reports:  24%|██▍       | 1764/7211 [07:32<18:09,  5.00it/s]

Reports:  24%|██▍       | 1765/7211 [07:32<17:51,  5.08it/s]

Reports:  24%|██▍       | 1766/7211 [07:32<18:11,  4.99it/s]

Reports:  25%|██▍       | 1767/7211 [07:32<17:52,  5.08it/s]

Reports:  25%|██▍       | 1768/7211 [07:33<17:46,  5.10it/s]

Reports:  25%|██▍       | 1769/7211 [07:33<24:21,  3.72it/s]

Reports:  25%|██▍       | 1770/7211 [07:33<22:06,  4.10it/s]

Reports:  25%|██▍       | 1771/7211 [07:33<20:29,  4.43it/s]

Reports:  25%|██▍       | 1772/7211 [07:34<19:52,  4.56it/s]

Reports:  25%|██▍       | 1773/7211 [07:34<18:56,  4.79it/s]

Reports:  25%|██▍       | 1774/7211 [07:34<21:07,  4.29it/s]

Reports:  25%|██▍       | 1775/7211 [07:34<19:44,  4.59it/s]

Reports:  25%|██▍       | 1776/7211 [07:35<19:11,  4.72it/s]

Reports:  25%|██▍       | 1777/7211 [07:35<18:41,  4.85it/s]

Reports:  25%|██▍       | 1778/7211 [07:35<24:52,  3.64it/s]

Reports:  25%|██▍       | 1779/7211 [07:35<23:03,  3.93it/s]

Reports:  25%|██▍       | 1780/7211 [07:36<21:21,  4.24it/s]

Reports:  25%|██▍       | 1781/7211 [07:36<20:09,  4.49it/s]

Reports:  25%|██▍       | 1782/7211 [07:36<23:05,  3.92it/s]

Reports:  25%|██▍       | 1783/7211 [07:36<21:32,  4.20it/s]

Reports:  25%|██▍       | 1784/7211 [07:36<20:05,  4.50it/s]

Reports:  25%|██▍       | 1785/7211 [07:37<19:07,  4.73it/s]

Reports:  25%|██▍       | 1786/7211 [07:37<18:45,  4.82it/s]

Reports:  25%|██▍       | 1787/7211 [07:37<18:16,  4.94it/s]

Reports:  25%|██▍       | 1788/7211 [07:37<18:02,  5.01it/s]

Reports:  25%|██▍       | 1789/7211 [07:37<18:03,  5.00it/s]

Reports:  25%|██▍       | 1790/7211 [07:38<17:45,  5.09it/s]

Reports:  25%|██▍       | 1791/7211 [07:38<17:42,  5.10it/s]

Reports:  25%|██▍       | 1792/7211 [07:38<17:28,  5.17it/s]

Reports:  25%|██▍       | 1793/7211 [07:38<20:05,  4.49it/s]

Reports:  25%|██▍       | 1794/7211 [07:38<19:24,  4.65it/s]

Reports:  25%|██▍       | 1795/7211 [07:39<18:57,  4.76it/s]

Reports:  25%|██▍       | 1796/7211 [07:39<18:56,  4.77it/s]

Reports:  25%|██▍       | 1797/7211 [07:39<18:45,  4.81it/s]

Reports:  25%|██▍       | 1798/7211 [07:39<18:04,  4.99it/s]

Reports:  25%|██▍       | 1799/7211 [07:39<18:07,  4.98it/s]

Reports:  25%|██▍       | 1800/7211 [07:40<23:32,  3.83it/s]

Reports:  25%|██▍       | 1801/7211 [07:40<23:46,  3.79it/s]

Reports:  25%|██▍       | 1802/7211 [07:40<22:53,  3.94it/s]

Reports:  25%|██▌       | 1803/7211 [07:41<25:05,  3.59it/s]

Reports:  25%|██▌       | 1804/7211 [07:41<22:59,  3.92it/s]

Reports:  25%|██▌       | 1805/7211 [07:41<21:01,  4.29it/s]

Reports:  25%|██▌       | 1806/7211 [07:41<20:25,  4.41it/s]

Reports:  25%|██▌       | 1807/7211 [07:42<21:45,  4.14it/s]

Reports:  25%|██▌       | 1808/7211 [07:42<20:25,  4.41it/s]

Reports:  25%|██▌       | 1809/7211 [07:42<19:29,  4.62it/s]

Reports:  25%|██▌       | 1810/7211 [07:42<18:41,  4.82it/s]

Reports:  25%|██▌       | 1811/7211 [07:42<18:25,  4.89it/s]

Reports:  25%|██▌       | 1812/7211 [07:43<17:47,  5.06it/s]

Reports:  25%|██▌       | 1813/7211 [07:43<24:08,  3.73it/s]

Reports:  25%|██▌       | 1814/7211 [07:43<21:50,  4.12it/s]

Reports:  25%|██▌       | 1815/7211 [07:43<20:35,  4.37it/s]

Reports:  25%|██▌       | 1816/7211 [07:44<20:03,  4.48it/s]

Reports:  25%|██▌       | 1817/7211 [07:44<22:56,  3.92it/s]

Reports:  25%|██▌       | 1818/7211 [07:44<21:49,  4.12it/s]

Reports:  25%|██▌       | 1819/7211 [07:44<20:27,  4.39it/s]

Reports:  25%|██▌       | 1820/7211 [07:44<19:23,  4.63it/s]

Reports:  25%|██▌       | 1821/7211 [07:45<21:59,  4.08it/s]

Reports:  25%|██▌       | 1822/7211 [07:45<20:52,  4.30it/s]

Reports:  25%|██▌       | 1823/7211 [07:45<19:33,  4.59it/s]

Reports:  25%|██▌       | 1824/7211 [07:45<18:50,  4.77it/s]

Reports:  25%|██▌       | 1825/7211 [07:46<18:26,  4.87it/s]

Reports:  25%|██▌       | 1826/7211 [07:46<18:24,  4.87it/s]

Reports:  25%|██▌       | 1827/7211 [07:46<17:52,  5.02it/s]

Reports:  25%|██▌       | 1828/7211 [07:46<17:40,  5.08it/s]

Reports:  25%|██▌       | 1829/7211 [07:46<18:08,  4.94it/s]

Reports:  25%|██▌       | 1830/7211 [07:47<18:05,  4.96it/s]

Reports:  25%|██▌       | 1831/7211 [07:47<18:17,  4.90it/s]

Reports:  25%|██▌       | 1832/7211 [07:47<17:54,  5.01it/s]

Reports:  25%|██▌       | 1833/7211 [07:47<17:44,  5.05it/s]

Reports:  25%|██▌       | 1834/7211 [07:47<17:30,  5.12it/s]

Reports:  25%|██▌       | 1835/7211 [07:48<17:54,  5.00it/s]

Reports:  25%|██▌       | 1836/7211 [07:48<18:00,  4.97it/s]

Reports:  25%|██▌       | 1837/7211 [07:49<39:41,  2.26it/s]

Reports:  25%|██▌       | 1838/7211 [07:49<32:52,  2.72it/s]

Reports:  26%|██▌       | 1839/7211 [07:49<28:04,  3.19it/s]

Reports:  26%|██▌       | 1840/7211 [07:49<24:43,  3.62it/s]

Reports:  26%|██▌       | 1841/7211 [07:50<22:22,  4.00it/s]

Reports:  26%|██▌       | 1842/7211 [07:50<20:45,  4.31it/s]

Reports:  26%|██▌       | 1843/7211 [07:50<19:22,  4.62it/s]

Reports:  26%|██▌       | 1844/7211 [07:50<18:35,  4.81it/s]

Reports:  26%|██▌       | 1845/7211 [07:50<18:09,  4.92it/s]

Reports:  26%|██▌       | 1846/7211 [07:50<17:48,  5.02it/s]

Reports:  26%|██▌       | 1847/7211 [07:51<17:37,  5.07it/s]

Reports:  26%|██▌       | 1848/7211 [07:51<17:49,  5.02it/s]

Reports:  26%|██▌       | 1849/7211 [07:51<17:36,  5.08it/s]

Reports:  26%|██▌       | 1850/7211 [07:51<17:25,  5.13it/s]

Reports:  26%|██▌       | 1851/7211 [07:51<17:38,  5.06it/s]

Reports:  26%|██▌       | 1852/7211 [07:52<18:02,  4.95it/s]

Reports:  26%|██▌       | 1853/7211 [07:52<18:01,  4.95it/s]

Reports:  26%|██▌       | 1854/7211 [07:52<17:50,  5.01it/s]

Reports:  26%|██▌       | 1855/7211 [07:52<17:34,  5.08it/s]

Reports:  26%|██▌       | 1856/7211 [07:52<17:39,  5.05it/s]

Reports:  26%|██▌       | 1857/7211 [07:53<17:29,  5.10it/s]

Reports:  26%|██▌       | 1858/7211 [07:53<17:38,  5.06it/s]

Reports:  26%|██▌       | 1859/7211 [07:53<17:36,  5.06it/s]

Reports:  26%|██▌       | 1860/7211 [07:53<17:15,  5.17it/s]

Reports:  26%|██▌       | 1861/7211 [07:53<17:28,  5.10it/s]

Reports:  26%|██▌       | 1862/7211 [07:54<17:30,  5.09it/s]

Reports:  26%|██▌       | 1863/7211 [07:54<17:25,  5.11it/s]

Reports:  26%|██▌       | 1864/7211 [07:54<17:26,  5.11it/s]

Reports:  26%|██▌       | 1865/7211 [07:54<17:04,  5.22it/s]

Reports:  26%|██▌       | 1866/7211 [07:54<17:16,  5.16it/s]

Reports:  26%|██▌       | 1867/7211 [07:55<17:13,  5.17it/s]

Reports:  26%|██▌       | 1868/7211 [07:55<17:46,  5.01it/s]

Reports:  26%|██▌       | 1869/7211 [07:55<17:26,  5.10it/s]

Reports:  26%|██▌       | 1870/7211 [07:55<17:35,  5.06it/s]

Reports:  26%|██▌       | 1871/7211 [07:55<17:04,  5.21it/s]

Reports:  26%|██▌       | 1872/7211 [07:56<17:25,  5.11it/s]

Reports:  26%|██▌       | 1873/7211 [07:56<17:31,  5.08it/s]

Reports:  26%|██▌       | 1874/7211 [07:56<17:41,  5.03it/s]

Reports:  26%|██▌       | 1875/7211 [07:56<17:35,  5.06it/s]

Reports:  26%|██▌       | 1876/7211 [07:56<17:25,  5.10it/s]

Reports:  26%|██▌       | 1877/7211 [07:57<17:27,  5.09it/s]

Reports:  26%|██▌       | 1878/7211 [07:57<17:45,  5.00it/s]

Reports:  26%|██▌       | 1879/7211 [07:57<17:49,  4.99it/s]

Reports:  26%|██▌       | 1880/7211 [07:57<17:33,  5.06it/s]

Reports:  26%|██▌       | 1881/7211 [07:57<17:39,  5.03it/s]

Reports:  26%|██▌       | 1882/7211 [07:58<17:46,  5.00it/s]

Reports:  26%|██▌       | 1883/7211 [07:58<18:10,  4.88it/s]

Reports:  26%|██▌       | 1884/7211 [07:58<18:12,  4.87it/s]

Reports:  26%|██▌       | 1885/7211 [07:58<17:42,  5.01it/s]

Reports:  26%|██▌       | 1886/7211 [07:58<17:35,  5.04it/s]

Reports:  26%|██▌       | 1887/7211 [08:09<4:47:08,  3.24s/it]

Reports:  26%|██▌       | 1888/7211 [08:09<3:26:46,  2.33s/it]

Reports:  26%|██▌       | 1889/7211 [08:09<2:29:45,  1.69s/it]

Reports:  26%|██▌       | 1890/7211 [08:09<1:49:39,  1.24s/it]

Reports:  26%|██▌       | 1891/7211 [08:09<1:21:57,  1.08it/s]

Reports:  26%|██▌       | 1892/7211 [08:10<1:02:19,  1.42it/s]

Reports:  26%|██▋       | 1893/7211 [08:10<48:58,  1.81it/s]

Reports:  26%|██▋       | 1894/7211 [08:10<39:17,  2.26it/s]

Reports:  26%|██▋       | 1895/7211 [08:10<32:19,  2.74it/s]

Reports:  26%|██▋       | 1896/7211 [08:10<27:34,  3.21it/s]

Reports:  26%|██▋       | 1897/7211 [08:11<24:28,  3.62it/s]

Reports:  26%|██▋       | 1898/7211 [08:11<22:00,  4.02it/s]

Reports:  26%|██▋       | 1899/7211 [08:11<20:40,  4.28it/s]

Reports:  26%|██▋       | 1900/7211 [08:11<19:19,  4.58it/s]

Reports:  26%|██▋       | 1901/7211 [08:11<18:30,  4.78it/s]

Reports:  26%|██▋       | 1902/7211 [08:12<17:54,  4.94it/s]

Reports:  26%|██▋       | 1903/7211 [08:12<17:38,  5.01it/s]

Reports:  26%|██▋       | 1904/7211 [08:12<17:23,  5.08it/s]

Reports:  26%|██▋       | 1905/7211 [08:12<17:51,  4.95it/s]

Reports:  26%|██▋       | 1906/7211 [08:12<17:33,  5.04it/s]

Reports:  26%|██▋       | 1907/7211 [08:13<17:16,  5.12it/s]

Reports:  26%|██▋       | 1908/7211 [08:13<17:19,  5.10it/s]

Reports:  26%|██▋       | 1909/7211 [08:13<17:17,  5.11it/s]

Reports:  26%|██▋       | 1910/7211 [08:13<17:24,  5.08it/s]

Reports:  27%|██▋       | 1911/7211 [08:13<17:35,  5.02it/s]

Reports:  27%|██▋       | 1912/7211 [08:14<17:39,  5.00it/s]

Reports:  27%|██▋       | 1913/7211 [08:14<17:18,  5.10it/s]

Reports:  27%|██▋       | 1914/7211 [08:14<17:06,  5.16it/s]

Reports:  27%|██▋       | 1915/7211 [08:14<16:56,  5.21it/s]

Reports:  27%|██▋       | 1916/7211 [08:14<17:15,  5.11it/s]

Reports:  27%|██▋       | 1917/7211 [08:14<17:09,  5.14it/s]

Reports:  27%|██▋       | 1918/7211 [08:15<17:08,  5.14it/s]

Reports:  27%|██▋       | 1919/7211 [08:15<17:50,  4.94it/s]

Reports:  27%|██▋       | 1920/7211 [08:15<17:24,  5.06it/s]

Reports:  27%|██▋       | 1921/7211 [08:15<17:22,  5.08it/s]

Reports:  27%|██▋       | 1922/7211 [08:15<17:03,  5.17it/s]

Reports:  27%|██▋       | 1923/7211 [08:16<17:35,  5.01it/s]

Reports:  27%|██▋       | 1924/7211 [08:16<17:28,  5.04it/s]

Reports:  27%|██▋       | 1925/7211 [08:16<17:07,  5.14it/s]

Reports:  27%|██▋       | 1926/7211 [08:16<16:50,  5.23it/s]

Reports:  27%|██▋       | 1927/7211 [08:16<17:02,  5.17it/s]

Reports:  27%|██▋       | 1928/7211 [08:17<17:39,  4.99it/s]

Reports:  27%|██▋       | 1929/7211 [08:17<17:11,  5.12it/s]

Reports:  27%|██▋       | 1930/7211 [08:17<17:05,  5.15it/s]

Reports:  27%|██▋       | 1931/7211 [08:17<16:59,  5.18it/s]

Reports:  27%|██▋       | 1932/7211 [08:17<17:07,  5.14it/s]

Reports:  27%|██▋       | 1933/7211 [08:18<16:49,  5.23it/s]

Reports:  27%|██▋       | 1934/7211 [08:18<16:57,  5.19it/s]

Reports:  27%|██▋       | 1935/7211 [08:18<16:50,  5.22it/s]

Reports:  27%|██▋       | 1936/7211 [08:18<17:10,  5.12it/s]

Reports:  27%|██▋       | 1937/7211 [08:18<17:01,  5.16it/s]

Reports:  27%|██▋       | 1938/7211 [08:19<16:38,  5.28it/s]

Reports:  27%|██▋       | 1939/7211 [08:19<16:29,  5.33it/s]

Reports:  27%|██▋       | 1940/7211 [08:19<16:58,  5.18it/s]

Reports:  27%|██▋       | 1941/7211 [08:19<17:20,  5.06it/s]

Reports:  27%|██▋       | 1942/7211 [08:19<17:02,  5.16it/s]

Reports:  27%|██▋       | 1943/7211 [08:20<17:00,  5.16it/s]

Reports:  27%|██▋       | 1944/7211 [08:20<17:05,  5.14it/s]

Reports:  27%|██▋       | 1945/7211 [08:20<16:55,  5.19it/s]

Reports:  27%|██▋       | 1946/7211 [08:20<17:19,  5.07it/s]

Reports:  27%|██▋       | 1947/7211 [08:20<16:57,  5.17it/s]

Reports:  27%|██▋       | 1948/7211 [08:21<17:16,  5.08it/s]

Reports:  27%|██▋       | 1949/7211 [08:21<17:24,  5.04it/s]

Reports:  27%|██▋       | 1950/7211 [08:21<17:11,  5.10it/s]

Reports:  27%|██▋       | 1951/7211 [08:21<17:02,  5.14it/s]

Reports:  27%|██▋       | 1952/7211 [08:21<17:04,  5.13it/s]

Reports:  27%|██▋       | 1953/7211 [08:21<16:35,  5.28it/s]

Reports:  27%|██▋       | 1954/7211 [08:22<16:33,  5.29it/s]

Reports:  27%|██▋       | 1955/7211 [08:22<16:40,  5.26it/s]

Reports:  27%|██▋       | 1956/7211 [08:22<16:25,  5.33it/s]

Reports:  27%|██▋       | 1957/7211 [08:22<16:22,  5.35it/s]

Reports:  27%|██▋       | 1958/7211 [08:22<16:55,  5.17it/s]

Reports:  27%|██▋       | 1959/7211 [08:23<17:04,  5.13it/s]

Reports:  27%|██▋       | 1960/7211 [08:23<17:01,  5.14it/s]

Reports:  27%|██▋       | 1961/7211 [08:23<17:43,  4.94it/s]

Reports:  27%|██▋       | 1962/7211 [08:23<17:29,  5.00it/s]

Reports:  27%|██▋       | 1963/7211 [08:23<17:28,  5.01it/s]

Reports:  27%|██▋       | 1964/7211 [08:24<17:16,  5.06it/s]

Reports:  27%|██▋       | 1965/7211 [08:24<17:03,  5.13it/s]

Reports:  27%|██▋       | 1966/7211 [08:24<16:44,  5.22it/s]

Reports:  27%|██▋       | 1967/7211 [08:24<16:54,  5.17it/s]

Reports:  27%|██▋       | 1968/7211 [08:25<21:09,  4.13it/s]

Reports:  27%|██▋       | 1969/7211 [08:25<20:02,  4.36it/s]

Reports:  27%|██▋       | 1970/7211 [08:25<19:01,  4.59it/s]

Reports:  27%|██▋       | 1971/7211 [08:25<18:23,  4.75it/s]

Reports:  27%|██▋       | 1972/7211 [08:25<17:59,  4.86it/s]

Reports:  27%|██▋       | 1973/7211 [08:26<18:01,  4.84it/s]

Reports:  27%|██▋       | 1974/7211 [08:26<17:57,  4.86it/s]

Reports:  27%|██▋       | 1975/7211 [08:26<17:27,  5.00it/s]

Reports:  27%|██▋       | 1976/7211 [08:26<17:06,  5.10it/s]

Reports:  27%|██▋       | 1977/7211 [08:26<17:17,  5.04it/s]

Reports:  27%|██▋       | 1978/7211 [08:27<17:00,  5.13it/s]

Reports:  27%|██▋       | 1979/7211 [08:27<16:40,  5.23it/s]

Reports:  27%|██▋       | 1980/7211 [08:27<16:39,  5.24it/s]

Reports:  27%|██▋       | 1981/7211 [08:27<16:35,  5.25it/s]

Reports:  27%|██▋       | 1982/7211 [08:27<16:20,  5.33it/s]

Reports:  27%|██▋       | 1983/7211 [08:27<16:27,  5.29it/s]

Reports:  28%|██▊       | 1984/7211 [08:28<16:22,  5.32it/s]

Reports:  28%|██▊       | 1985/7211 [08:28<16:20,  5.33it/s]

Reports:  28%|██▊       | 1986/7211 [08:28<16:42,  5.21it/s]

Reports:  28%|██▊       | 1987/7211 [08:28<16:37,  5.24it/s]

Reports:  28%|██▊       | 1988/7211 [08:28<16:44,  5.20it/s]

Reports:  28%|██▊       | 1989/7211 [08:29<16:31,  5.27it/s]

Reports:  28%|██▊       | 1990/7211 [08:29<16:47,  5.18it/s]

Reports:  28%|██▊       | 1991/7211 [08:29<17:18,  5.02it/s]

Reports:  28%|██▊       | 1992/7211 [08:29<17:24,  5.00it/s]

Reports:  28%|██▊       | 1993/7211 [08:29<17:01,  5.11it/s]

Reports:  28%|██▊       | 1994/7211 [08:30<16:53,  5.15it/s]

Reports:  28%|██▊       | 1995/7211 [08:30<16:47,  5.18it/s]

Reports:  28%|██▊       | 1996/7211 [08:30<17:07,  5.08it/s]

Reports:  28%|██▊       | 1997/7211 [08:30<17:31,  4.96it/s]

Reports:  28%|██▊       | 1998/7211 [08:30<17:33,  4.95it/s]

Reports:  28%|██▊       | 1999/7211 [08:31<17:29,  4.96it/s]

Reports:  28%|██▊       | 2000/7211 [08:31<16:58,  5.12it/s]

Reports:  28%|██▊       | 2001/7211 [08:31<16:52,  5.15it/s]

Reports:  28%|██▊       | 2002/7211 [08:31<16:44,  5.18it/s]

Reports:  28%|██▊       | 2003/7211 [08:31<16:36,  5.23it/s]

Reports:  28%|██▊       | 2004/7211 [08:32<16:47,  5.17it/s]

Reports:  28%|██▊       | 2005/7211 [08:32<16:32,  5.25it/s]

Reports:  28%|██▊       | 2006/7211 [08:32<16:27,  5.27it/s]

Reports:  28%|██▊       | 2007/7211 [08:32<16:48,  5.16it/s]

Reports:  28%|██▊       | 2008/7211 [08:32<16:38,  5.21it/s]

Reports:  28%|██▊       | 2009/7211 [08:33<16:45,  5.17it/s]

Reports:  28%|██▊       | 2010/7211 [08:33<16:42,  5.19it/s]

Reports:  28%|██▊       | 2011/7211 [08:33<16:27,  5.27it/s]

Reports:  28%|██▊       | 2012/7211 [08:33<16:46,  5.16it/s]

Reports:  28%|██▊       | 2013/7211 [08:33<16:44,  5.17it/s]

Reports:  28%|██▊       | 2014/7211 [08:33<16:42,  5.19it/s]

Reports:  28%|██▊       | 2015/7211 [08:34<16:38,  5.20it/s]

Reports:  28%|██▊       | 2016/7211 [08:34<16:28,  5.26it/s]

Reports:  28%|██▊       | 2017/7211 [08:34<16:45,  5.16it/s]

Reports:  28%|██▊       | 2018/7211 [08:34<16:31,  5.23it/s]

Reports:  28%|██▊       | 2019/7211 [08:34<16:56,  5.11it/s]

Reports:  28%|██▊       | 2020/7211 [08:35<16:50,  5.14it/s]

Reports:  28%|██▊       | 2021/7211 [08:35<16:50,  5.13it/s]

Reports:  28%|██▊       | 2022/7211 [08:35<16:48,  5.14it/s]

Reports:  28%|██▊       | 2023/7211 [08:35<16:36,  5.20it/s]

Reports:  28%|██▊       | 2024/7211 [08:35<16:38,  5.20it/s]

Reports:  28%|██▊       | 2025/7211 [08:36<16:46,  5.15it/s]

Reports:  28%|██▊       | 2026/7211 [08:36<16:42,  5.17it/s]

Reports:  28%|██▊       | 2027/7211 [08:36<16:23,  5.27it/s]

Reports:  28%|██▊       | 2028/7211 [08:36<16:24,  5.26it/s]

Reports:  28%|██▊       | 2029/7211 [08:36<16:48,  5.14it/s]

Reports:  28%|██▊       | 2030/7211 [08:37<16:41,  5.18it/s]

Reports:  28%|██▊       | 2031/7211 [08:37<16:28,  5.24it/s]

Reports:  28%|██▊       | 2032/7211 [08:37<16:31,  5.23it/s]

Reports:  28%|██▊       | 2033/7211 [08:37<16:51,  5.12it/s]

Reports:  28%|██▊       | 2034/7211 [08:37<16:59,  5.08it/s]

Reports:  28%|██▊       | 2035/7211 [08:38<17:05,  5.05it/s]

Reports:  28%|██▊       | 2036/7211 [08:38<17:09,  5.02it/s]

Reports:  28%|██▊       | 2037/7211 [08:38<16:51,  5.12it/s]

Reports:  28%|██▊       | 2038/7211 [08:38<16:56,  5.09it/s]

Reports:  28%|██▊       | 2039/7211 [08:38<17:07,  5.04it/s]

Reports:  28%|██▊       | 2040/7211 [08:39<16:53,  5.10it/s]

Reports:  28%|██▊       | 2041/7211 [08:39<16:52,  5.11it/s]

Reports:  28%|██▊       | 2042/7211 [08:39<16:30,  5.22it/s]

Reports:  28%|██▊       | 2043/7211 [08:39<16:39,  5.17it/s]

Reports:  28%|██▊       | 2044/7211 [08:39<16:30,  5.22it/s]

Reports:  28%|██▊       | 2045/7211 [08:41<1:05:56,  1.31it/s]

Reports:  28%|██▊       | 2046/7211 [08:42<50:56,  1.69it/s]

Reports:  28%|██▊       | 2047/7211 [08:42<41:05,  2.09it/s]

Reports:  28%|██▊       | 2048/7211 [08:42<34:10,  2.52it/s]

Reports:  28%|██▊       | 2049/7211 [08:42<29:12,  2.95it/s]

Reports:  28%|██▊       | 2050/7211 [08:42<25:26,  3.38it/s]

Reports:  28%|██▊       | 2051/7211 [08:43<22:42,  3.79it/s]

Reports:  28%|██▊       | 2052/7211 [08:43<20:55,  4.11it/s]

Reports:  28%|██▊       | 2053/7211 [08:43<19:31,  4.40it/s]

Reports:  28%|██▊       | 2054/7211 [08:43<18:30,  4.64it/s]

Reports:  28%|██▊       | 2055/7211 [08:43<18:11,  4.73it/s]

Reports:  29%|██▊       | 2056/7211 [08:44<17:30,  4.91it/s]

Reports:  29%|██▊       | 2057/7211 [08:44<17:00,  5.05it/s]

Reports:  29%|██▊       | 2058/7211 [08:44<16:41,  5.14it/s]

Reports:  29%|██▊       | 2059/7211 [08:44<16:22,  5.25it/s]

Reports:  29%|██▊       | 2060/7211 [08:44<16:18,  5.27it/s]

Reports:  29%|██▊       | 2061/7211 [08:44<16:11,  5.30it/s]

Reports:  29%|██▊       | 2062/7211 [08:45<15:58,  5.37it/s]

Reports:  29%|██▊       | 2063/7211 [08:45<18:30,  4.64it/s]

Reports:  29%|██▊       | 2064/7211 [08:45<18:55,  4.53it/s]

Reports:  29%|██▊       | 2065/7211 [08:45<21:10,  4.05it/s]

Reports:  29%|██▊       | 2066/7211 [08:46<20:21,  4.21it/s]

Reports:  29%|██▊       | 2067/7211 [08:46<18:54,  4.53it/s]

Reports:  29%|██▊       | 2068/7211 [08:46<17:53,  4.79it/s]

Reports:  29%|██▊       | 2069/7211 [08:46<17:11,  4.98it/s]

Reports:  29%|██▊       | 2070/7211 [08:46<17:19,  4.95it/s]

Reports:  29%|██▊       | 2071/7211 [08:47<16:50,  5.09it/s]

Reports:  29%|██▊       | 2072/7211 [08:47<16:56,  5.06it/s]

Reports:  29%|██▊       | 2073/7211 [08:47<16:37,  5.15it/s]

Reports:  29%|██▉       | 2074/7211 [08:47<17:06,  5.00it/s]

Reports:  29%|██▉       | 2075/7211 [08:47<17:07,  5.00it/s]

Reports:  29%|██▉       | 2076/7211 [08:48<17:13,  4.97it/s]

Reports:  29%|██▉       | 2077/7211 [08:48<16:52,  5.07it/s]

Reports:  29%|██▉       | 2078/7211 [08:48<16:48,  5.09it/s]

Reports:  29%|██▉       | 2079/7211 [08:48<16:57,  5.04it/s]

Reports:  29%|██▉       | 2080/7211 [08:48<17:16,  4.95it/s]

Reports:  29%|██▉       | 2081/7211 [08:49<17:13,  4.97it/s]

Reports:  29%|██▉       | 2082/7211 [08:49<17:16,  4.95it/s]

Reports:  29%|██▉       | 2083/7211 [08:49<16:46,  5.09it/s]

Reports:  29%|██▉       | 2084/7211 [08:49<16:45,  5.10it/s]

Reports:  29%|██▉       | 2085/7211 [08:49<16:25,  5.20it/s]

Reports:  29%|██▉       | 2086/7211 [08:50<16:25,  5.20it/s]

Reports:  29%|██▉       | 2087/7211 [08:50<16:35,  5.15it/s]

Reports:  29%|██▉       | 2088/7211 [08:50<16:17,  5.24it/s]

Reports:  29%|██▉       | 2089/7211 [08:50<16:16,  5.25it/s]

Reports:  29%|██▉       | 2090/7211 [08:50<16:13,  5.26it/s]

Reports:  29%|██▉       | 2091/7211 [08:51<16:26,  5.19it/s]

Reports:  29%|██▉       | 2092/7211 [08:51<18:18,  4.66it/s]

Reports:  29%|██▉       | 2093/7211 [08:51<18:01,  4.73it/s]

Reports:  29%|██▉       | 2094/7211 [08:51<17:23,  4.90it/s]

Reports:  29%|██▉       | 2095/7211 [08:51<16:55,  5.04it/s]

Reports:  29%|██▉       | 2096/7211 [08:52<16:40,  5.11it/s]

Reports:  29%|██▉       | 2097/7211 [08:53<35:57,  2.37it/s]

Reports:  29%|██▉       | 2098/7211 [08:53<30:32,  2.79it/s]

Reports:  29%|██▉       | 2099/7211 [08:53<26:32,  3.21it/s]

Reports:  29%|██▉       | 2100/7211 [08:53<23:45,  3.59it/s]

Reports:  29%|██▉       | 2101/7211 [08:53<21:57,  3.88it/s]

Reports:  29%|██▉       | 2102/7211 [08:54<20:14,  4.21it/s]

Reports:  29%|██▉       | 2103/7211 [08:54<18:58,  4.49it/s]

Reports:  29%|██▉       | 2104/7211 [08:54<19:01,  4.47it/s]

Reports:  29%|██▉       | 2105/7211 [08:54<18:28,  4.61it/s]

Reports:  29%|██▉       | 2106/7211 [08:54<17:47,  4.78it/s]

Reports:  29%|██▉       | 2107/7211 [08:55<17:33,  4.84it/s]

Reports:  29%|██▉       | 2108/7211 [08:55<17:36,  4.83it/s]

Reports:  29%|██▉       | 2109/7211 [08:55<17:20,  4.91it/s]

Reports:  29%|██▉       | 2110/7211 [08:55<17:23,  4.89it/s]

Reports:  29%|██▉       | 2111/7211 [08:55<17:06,  4.97it/s]

Reports:  29%|██▉       | 2112/7211 [08:56<16:45,  5.07it/s]

Reports:  29%|██▉       | 2113/7211 [08:56<16:27,  5.16it/s]

Reports:  29%|██▉       | 2114/7211 [08:57<41:43,  2.04it/s]

Reports:  29%|██▉       | 2115/7211 [08:57<34:28,  2.46it/s]

Reports:  29%|██▉       | 2116/7211 [08:57<29:00,  2.93it/s]

Reports:  29%|██▉       | 2117/7211 [08:57<24:59,  3.40it/s]

Reports:  29%|██▉       | 2118/7211 [08:58<22:11,  3.83it/s]

Reports:  29%|██▉       | 2119/7211 [08:58<20:28,  4.15it/s]

Reports:  29%|██▉       | 2120/7211 [08:58<18:53,  4.49it/s]

Reports:  29%|██▉       | 2121/7211 [08:58<18:05,  4.69it/s]

Reports:  29%|██▉       | 2122/7211 [08:58<17:42,  4.79it/s]

Reports:  29%|██▉       | 2123/7211 [08:59<17:06,  4.96it/s]

Reports:  29%|██▉       | 2124/7211 [08:59<16:32,  5.13it/s]

Reports:  29%|██▉       | 2125/7211 [08:59<16:31,  5.13it/s]

Reports:  29%|██▉       | 2126/7211 [08:59<16:15,  5.21it/s]

Reports:  29%|██▉       | 2127/7211 [08:59<16:23,  5.17it/s]

Reports:  30%|██▉       | 2128/7211 [09:00<16:27,  5.15it/s]

Reports:  30%|██▉       | 2129/7211 [09:00<16:20,  5.18it/s]

Reports:  30%|██▉       | 2130/7211 [09:00<16:33,  5.11it/s]

Reports:  30%|██▉       | 2131/7211 [09:00<17:14,  4.91it/s]

Reports:  30%|██▉       | 2132/7211 [09:00<17:02,  4.97it/s]

Reports:  30%|██▉       | 2133/7211 [09:01<16:40,  5.08it/s]

Reports:  30%|██▉       | 2134/7211 [09:01<29:03,  2.91it/s]

Reports:  30%|██▉       | 2135/7211 [09:02<28:03,  3.02it/s]

Reports:  30%|██▉       | 2136/7211 [09:02<30:14,  2.80it/s]

Reports:  30%|██▉       | 2137/7211 [09:02<26:15,  3.22it/s]

Reports:  30%|██▉       | 2138/7211 [09:02<23:22,  3.62it/s]

Reports:  30%|██▉       | 2139/7211 [09:03<21:04,  4.01it/s]

Reports:  30%|██▉       | 2140/7211 [09:03<19:29,  4.34it/s]

Reports:  30%|██▉       | 2141/7211 [09:03<23:18,  3.63it/s]

Reports:  30%|██▉       | 2142/7211 [09:03<21:17,  3.97it/s]

Reports:  30%|██▉       | 2143/7211 [09:04<19:48,  4.26it/s]

Reports:  30%|██▉       | 2144/7211 [09:04<23:03,  3.66it/s]

Reports:  30%|██▉       | 2145/7211 [09:05<34:11,  2.47it/s]

Reports:  30%|██▉       | 2146/7211 [09:05<28:52,  2.92it/s]

Reports:  30%|██▉       | 2147/7211 [09:05<24:58,  3.38it/s]

Reports:  30%|██▉       | 2148/7211 [09:05<22:24,  3.76it/s]

Reports:  30%|██▉       | 2149/7211 [09:05<20:21,  4.14it/s]

Reports:  30%|██▉       | 2150/7211 [09:06<19:13,  4.39it/s]

Reports:  30%|██▉       | 2151/7211 [09:06<18:11,  4.63it/s]

Reports:  30%|██▉       | 2152/7211 [09:06<17:31,  4.81it/s]

Reports:  30%|██▉       | 2153/7211 [09:06<16:53,  4.99it/s]

Reports:  30%|██▉       | 2154/7211 [09:06<16:40,  5.05it/s]

Reports:  30%|██▉       | 2155/7211 [09:06<16:19,  5.16it/s]

Reports:  30%|██▉       | 2156/7211 [09:07<16:02,  5.25it/s]

Reports:  30%|██▉       | 2157/7211 [09:07<16:16,  5.17it/s]

Reports:  30%|██▉       | 2158/7211 [09:07<16:26,  5.12it/s]

Reports:  30%|██▉       | 2159/7211 [09:07<16:22,  5.14it/s]

Reports:  30%|██▉       | 2160/7211 [09:07<16:09,  5.21it/s]

Reports:  30%|██▉       | 2161/7211 [09:08<16:03,  5.24it/s]

Reports:  30%|██▉       | 2162/7211 [09:08<16:39,  5.05it/s]

Reports:  30%|██▉       | 2163/7211 [09:08<16:56,  4.97it/s]

Reports:  30%|███       | 2164/7211 [09:08<16:46,  5.02it/s]

Reports:  30%|███       | 2165/7211 [09:08<16:31,  5.09it/s]

Reports:  30%|███       | 2166/7211 [09:09<16:37,  5.06it/s]

Reports:  30%|███       | 2167/7211 [09:09<16:19,  5.15it/s]

Reports:  30%|███       | 2168/7211 [09:09<16:23,  5.13it/s]

Reports:  30%|███       | 2169/7211 [09:09<16:34,  5.07it/s]

Reports:  30%|███       | 2170/7211 [09:09<16:31,  5.08it/s]

Reports:  30%|███       | 2171/7211 [09:10<16:56,  4.96it/s]

Reports:  30%|███       | 2172/7211 [09:10<17:08,  4.90it/s]

Reports:  30%|███       | 2173/7211 [09:10<16:46,  5.00it/s]

Reports:  30%|███       | 2174/7211 [09:10<16:46,  5.01it/s]

Reports:  30%|███       | 2175/7211 [09:10<17:00,  4.94it/s]

Reports:  30%|███       | 2176/7211 [09:11<16:53,  4.97it/s]

Reports:  30%|███       | 2177/7211 [09:11<16:21,  5.13it/s]

Reports:  30%|███       | 2178/7211 [09:11<16:08,  5.20it/s]

Reports:  30%|███       | 2179/7211 [09:11<16:14,  5.16it/s]

Reports:  30%|███       | 2180/7211 [09:11<16:04,  5.21it/s]

Reports:  30%|███       | 2181/7211 [09:12<16:03,  5.22it/s]

Reports:  30%|███       | 2182/7211 [09:12<16:01,  5.23it/s]

Reports:  30%|███       | 2183/7211 [09:12<15:48,  5.30it/s]

Reports:  30%|███       | 2184/7211 [09:12<16:11,  5.18it/s]

Reports:  30%|███       | 2185/7211 [09:12<16:23,  5.11it/s]

Reports:  30%|███       | 2186/7211 [09:13<16:10,  5.18it/s]

Reports:  30%|███       | 2187/7211 [09:13<16:24,  5.11it/s]

Reports:  30%|███       | 2188/7211 [09:13<16:38,  5.03it/s]

Reports:  30%|███       | 2189/7211 [09:13<17:06,  4.89it/s]

Reports:  30%|███       | 2190/7211 [09:13<16:45,  4.99it/s]

Reports:  30%|███       | 2191/7211 [09:14<17:05,  4.89it/s]

Reports:  30%|███       | 2192/7211 [09:14<16:41,  5.01it/s]

Reports:  30%|███       | 2193/7211 [09:14<16:24,  5.10it/s]

Reports:  30%|███       | 2194/7211 [09:14<16:27,  5.08it/s]

Reports:  30%|███       | 2195/7211 [09:14<16:20,  5.12it/s]

Reports:  30%|███       | 2196/7211 [09:15<16:20,  5.12it/s]

Reports:  30%|███       | 2197/7211 [09:15<16:09,  5.17it/s]

Reports:  30%|███       | 2198/7211 [09:15<16:04,  5.20it/s]

Reports:  30%|███       | 2199/7211 [09:15<16:00,  5.22it/s]

Reports:  31%|███       | 2200/7211 [09:15<15:54,  5.25it/s]

Reports:  31%|███       | 2201/7211 [09:15<15:38,  5.34it/s]

Reports:  31%|███       | 2202/7211 [09:16<15:44,  5.31it/s]

Reports:  31%|███       | 2203/7211 [09:16<16:09,  5.17it/s]

Reports:  31%|███       | 2204/7211 [09:16<16:07,  5.18it/s]

Reports:  31%|███       | 2205/7211 [09:16<16:14,  5.14it/s]

Reports:  31%|███       | 2206/7211 [09:16<15:58,  5.22it/s]

Reports:  31%|███       | 2207/7211 [09:17<16:11,  5.15it/s]

Reports:  31%|███       | 2208/7211 [09:17<16:23,  5.09it/s]

Reports:  31%|███       | 2209/7211 [09:17<16:07,  5.17it/s]

Reports:  31%|███       | 2210/7211 [09:17<16:10,  5.15it/s]

Reports:  31%|███       | 2211/7211 [09:17<16:33,  5.03it/s]

Reports:  31%|███       | 2212/7211 [09:18<16:16,  5.12it/s]

Reports:  31%|███       | 2213/7211 [09:18<16:02,  5.20it/s]

Reports:  31%|███       | 2214/7211 [09:18<15:41,  5.31it/s]

Reports:  31%|███       | 2215/7211 [09:18<15:47,  5.27it/s]

Reports:  31%|███       | 2216/7211 [09:18<17:12,  4.84it/s]

Reports:  31%|███       | 2217/7211 [09:19<16:40,  4.99it/s]

Reports:  31%|███       | 2218/7211 [09:19<16:32,  5.03it/s]

Reports:  31%|███       | 2219/7211 [09:19<16:19,  5.09it/s]

Reports:  31%|███       | 2220/7211 [09:19<16:18,  5.10it/s]

Reports:  31%|███       | 2221/7211 [09:19<16:33,  5.02it/s]

Reports:  31%|███       | 2222/7211 [09:20<16:28,  5.05it/s]

Reports:  31%|███       | 2223/7211 [09:20<16:20,  5.09it/s]

Reports:  31%|███       | 2224/7211 [09:20<16:11,  5.13it/s]

Reports:  31%|███       | 2225/7211 [09:20<16:08,  5.15it/s]

Reports:  31%|███       | 2226/7211 [09:20<16:00,  5.19it/s]

Reports:  31%|███       | 2227/7211 [09:21<15:54,  5.22it/s]

Reports:  31%|███       | 2228/7211 [09:21<15:45,  5.27it/s]

Reports:  31%|███       | 2229/7211 [09:21<15:43,  5.28it/s]

Reports:  31%|███       | 2230/7211 [09:21<15:43,  5.28it/s]

Reports:  31%|███       | 2231/7211 [09:21<16:04,  5.16it/s]

Reports:  31%|███       | 2232/7211 [09:22<15:52,  5.23it/s]

Reports:  31%|███       | 2233/7211 [09:22<15:45,  5.26it/s]

Reports:  31%|███       | 2234/7211 [09:22<16:25,  5.05it/s]

Reports:  31%|███       | 2235/7211 [09:22<16:03,  5.16it/s]

Reports:  31%|███       | 2236/7211 [09:22<15:54,  5.21it/s]

Reports:  31%|███       | 2237/7211 [09:22<15:50,  5.23it/s]

Reports:  31%|███       | 2238/7211 [09:23<15:55,  5.20it/s]

Reports:  31%|███       | 2239/7211 [09:23<15:45,  5.26it/s]

Reports:  31%|███       | 2240/7211 [09:23<16:08,  5.13it/s]

Reports:  31%|███       | 2241/7211 [09:23<16:15,  5.09it/s]

Reports:  31%|███       | 2242/7211 [09:23<16:03,  5.16it/s]

Reports:  31%|███       | 2243/7211 [09:24<16:01,  5.17it/s]

Reports:  31%|███       | 2244/7211 [09:24<16:30,  5.01it/s]

Reports:  31%|███       | 2245/7211 [09:24<16:17,  5.08it/s]

Reports:  31%|███       | 2246/7211 [09:24<16:04,  5.15it/s]

Reports:  31%|███       | 2247/7211 [09:24<16:15,  5.09it/s]

Reports:  31%|███       | 2248/7211 [09:25<16:27,  5.03it/s]

Reports:  31%|███       | 2249/7211 [09:25<16:22,  5.05it/s]

Reports:  31%|███       | 2250/7211 [09:25<16:33,  4.99it/s]

Reports:  31%|███       | 2251/7211 [09:25<16:39,  4.96it/s]

Reports:  31%|███       | 2252/7211 [09:25<16:28,  5.01it/s]

Reports:  31%|███       | 2253/7211 [09:26<16:18,  5.07it/s]

Reports:  31%|███▏      | 2254/7211 [09:26<16:12,  5.10it/s]

Reports:  31%|███▏      | 2255/7211 [09:26<16:22,  5.04it/s]

Reports:  31%|███▏      | 2256/7211 [09:26<15:54,  5.19it/s]

Reports:  31%|███▏      | 2257/7211 [09:26<15:45,  5.24it/s]

Reports:  31%|███▏      | 2258/7211 [09:27<15:52,  5.20it/s]

Reports:  31%|███▏      | 2259/7211 [09:27<16:02,  5.15it/s]

Reports:  31%|███▏      | 2260/7211 [09:27<15:56,  5.18it/s]

Reports:  31%|███▏      | 2261/7211 [09:27<16:26,  5.02it/s]

Reports:  31%|███▏      | 2262/7211 [09:27<16:11,  5.09it/s]

Reports:  31%|███▏      | 2263/7211 [09:28<16:14,  5.08it/s]

Reports:  31%|███▏      | 2264/7211 [09:28<15:51,  5.20it/s]

Reports:  31%|███▏      | 2265/7211 [09:28<15:57,  5.17it/s]

Reports:  31%|███▏      | 2266/7211 [09:28<16:22,  5.03it/s]

Reports:  31%|███▏      | 2267/7211 [09:28<15:58,  5.16it/s]

Reports:  31%|███▏      | 2268/7211 [09:29<16:03,  5.13it/s]

Reports:  31%|███▏      | 2269/7211 [09:29<16:21,  5.04it/s]

Reports:  31%|███▏      | 2270/7211 [09:29<16:15,  5.06it/s]

Reports:  31%|███▏      | 2271/7211 [09:29<16:20,  5.04it/s]

Reports:  32%|███▏      | 2272/7211 [09:29<16:07,  5.11it/s]

Reports:  32%|███▏      | 2273/7211 [09:30<15:52,  5.18it/s]

Reports:  32%|███▏      | 2274/7211 [09:30<15:40,  5.25it/s]

Reports:  32%|███▏      | 2275/7211 [09:30<15:43,  5.23it/s]

Reports:  32%|███▏      | 2276/7211 [09:30<15:47,  5.21it/s]

Reports:  32%|███▏      | 2277/7211 [09:30<16:03,  5.12it/s]

Reports:  32%|███▏      | 2278/7211 [09:31<16:03,  5.12it/s]

Reports:  32%|███▏      | 2279/7211 [09:31<15:40,  5.25it/s]

Reports:  32%|███▏      | 2280/7211 [09:31<15:35,  5.27it/s]

Reports:  32%|███▏      | 2281/7211 [09:31<15:29,  5.31it/s]

Reports:  32%|███▏      | 2282/7211 [09:31<15:33,  5.28it/s]

Reports:  32%|███▏      | 2283/7211 [09:31<15:48,  5.20it/s]

Reports:  32%|███▏      | 2284/7211 [09:32<15:27,  5.31it/s]

Reports:  32%|███▏      | 2285/7211 [09:32<15:45,  5.21it/s]

Reports:  32%|███▏      | 2286/7211 [09:32<15:54,  5.16it/s]

Reports:  32%|███▏      | 2287/7211 [09:32<15:51,  5.18it/s]

Reports:  32%|███▏      | 2288/7211 [09:32<16:02,  5.12it/s]

Reports:  32%|███▏      | 2289/7211 [09:33<21:35,  3.80it/s]

Reports:  32%|███▏      | 2290/7211 [09:33<19:36,  4.18it/s]

Reports:  32%|███▏      | 2291/7211 [09:33<18:33,  4.42it/s]

Reports:  32%|███▏      | 2292/7211 [09:33<18:22,  4.46it/s]

Reports:  32%|███▏      | 2293/7211 [09:34<17:24,  4.71it/s]

Reports:  32%|███▏      | 2294/7211 [09:34<16:54,  4.85it/s]

Reports:  32%|███▏      | 2295/7211 [09:34<16:22,  5.00it/s]

Reports:  32%|███▏      | 2296/7211 [09:34<16:07,  5.08it/s]

Reports:  32%|███▏      | 2297/7211 [09:34<15:52,  5.16it/s]

Reports:  32%|███▏      | 2298/7211 [09:35<15:36,  5.25it/s]

Reports:  32%|███▏      | 2299/7211 [09:35<15:37,  5.24it/s]

Reports:  32%|███▏      | 2300/7211 [09:35<15:56,  5.14it/s]

Reports:  32%|███▏      | 2301/7211 [09:35<15:54,  5.14it/s]

Reports:  32%|███▏      | 2302/7211 [09:35<15:56,  5.13it/s]

Reports:  32%|███▏      | 2303/7211 [09:36<15:55,  5.14it/s]

Reports:  32%|███▏      | 2304/7211 [09:36<15:37,  5.23it/s]

Reports:  32%|███▏      | 2305/7211 [09:36<15:29,  5.28it/s]

Reports:  32%|███▏      | 2306/7211 [09:36<15:24,  5.30it/s]

Reports:  32%|███▏      | 2307/7211 [09:36<15:36,  5.24it/s]

Reports:  32%|███▏      | 2308/7211 [09:36<15:30,  5.27it/s]

Reports:  32%|███▏      | 2309/7211 [09:37<15:21,  5.32it/s]

Reports:  32%|███▏      | 2310/7211 [09:37<15:36,  5.23it/s]

Reports:  32%|███▏      | 2311/7211 [09:37<15:43,  5.19it/s]

Reports:  32%|███▏      | 2312/7211 [09:39<57:13,  1.43it/s]

Reports:  32%|███▏      | 2313/7211 [09:39<44:59,  1.81it/s]

Reports:  32%|███▏      | 2314/7211 [09:39<36:03,  2.26it/s]

Reports:  32%|███▏      | 2315/7211 [09:40<30:21,  2.69it/s]

Reports:  32%|███▏      | 2316/7211 [09:40<25:48,  3.16it/s]

Reports:  32%|███▏      | 2317/7211 [09:40<23:41,  3.44it/s]

Reports:  32%|███▏      | 2318/7211 [09:40<21:49,  3.74it/s]

Reports:  32%|███▏      | 2319/7211 [09:40<19:57,  4.08it/s]

Reports:  32%|███▏      | 2320/7211 [09:41<18:29,  4.41it/s]

Reports:  32%|███▏      | 2321/7211 [09:41<18:03,  4.51it/s]

Reports:  32%|███▏      | 2322/7211 [09:41<17:29,  4.66it/s]

Reports:  32%|███▏      | 2323/7211 [09:41<16:52,  4.83it/s]

Reports:  32%|███▏      | 2324/7211 [09:41<16:31,  4.93it/s]

Reports:  32%|███▏      | 2325/7211 [09:42<16:28,  4.95it/s]

Reports:  32%|███▏      | 2326/7211 [09:42<16:39,  4.89it/s]

Reports:  32%|███▏      | 2327/7211 [09:42<16:23,  4.97it/s]

Reports:  32%|███▏      | 2328/7211 [09:42<16:04,  5.06it/s]

Reports:  32%|███▏      | 2329/7211 [09:42<15:51,  5.13it/s]

Reports:  32%|███▏      | 2330/7211 [09:43<16:04,  5.06it/s]

Reports:  32%|███▏      | 2331/7211 [09:43<15:48,  5.15it/s]

Reports:  32%|███▏      | 2332/7211 [09:43<16:35,  4.90it/s]

Reports:  32%|███▏      | 2333/7211 [09:43<16:27,  4.94it/s]

Reports:  32%|███▏      | 2334/7211 [09:43<15:53,  5.11it/s]

Reports:  32%|███▏      | 2335/7211 [09:44<15:52,  5.12it/s]

Reports:  32%|███▏      | 2336/7211 [09:44<15:37,  5.20it/s]

Reports:  32%|███▏      | 2337/7211 [09:44<16:26,  4.94it/s]

Reports:  32%|███▏      | 2338/7211 [09:44<16:56,  4.79it/s]

Reports:  32%|███▏      | 2339/7211 [09:44<16:39,  4.87it/s]

Reports:  32%|███▏      | 2340/7211 [09:45<16:43,  4.85it/s]

Reports:  32%|███▏      | 2341/7211 [09:45<16:20,  4.97it/s]

Reports:  32%|███▏      | 2342/7211 [09:45<16:27,  4.93it/s]

Reports:  32%|███▏      | 2343/7211 [09:45<16:54,  4.80it/s]

Reports:  33%|███▎      | 2344/7211 [09:45<16:21,  4.96it/s]

Reports:  33%|███▎      | 2345/7211 [09:46<16:04,  5.04it/s]

Reports:  33%|███▎      | 2346/7211 [09:46<16:01,  5.06it/s]

Reports:  33%|███▎      | 2347/7211 [09:46<16:09,  5.02it/s]

Reports:  33%|███▎      | 2348/7211 [09:46<16:02,  5.05it/s]

Reports:  33%|███▎      | 2349/7211 [09:46<15:58,  5.07it/s]

Reports:  33%|███▎      | 2350/7211 [09:47<15:45,  5.14it/s]

Reports:  33%|███▎      | 2351/7211 [09:47<15:32,  5.21it/s]

Reports:  33%|███▎      | 2352/7211 [09:47<15:23,  5.26it/s]

Reports:  33%|███▎      | 2353/7211 [09:47<15:21,  5.27it/s]

Reports:  33%|███▎      | 2354/7211 [09:47<15:26,  5.24it/s]

Reports:  33%|███▎      | 2355/7211 [09:47<15:16,  5.30it/s]

Reports:  33%|███▎      | 2356/7211 [09:48<15:30,  5.22it/s]

Reports:  33%|███▎      | 2357/7211 [09:48<15:22,  5.26it/s]

Reports:  33%|███▎      | 2358/7211 [09:48<15:29,  5.22it/s]

Reports:  33%|███▎      | 2359/7211 [09:48<15:32,  5.20it/s]

Reports:  33%|███▎      | 2360/7211 [09:48<15:43,  5.14it/s]

Reports:  33%|███▎      | 2361/7211 [09:49<16:00,  5.05it/s]

Reports:  33%|███▎      | 2362/7211 [09:49<15:56,  5.07it/s]

Reports:  33%|███▎      | 2363/7211 [09:49<15:44,  5.13it/s]

Reports:  33%|███▎      | 2364/7211 [09:49<15:33,  5.20it/s]

Reports:  33%|███▎      | 2365/7211 [09:49<15:48,  5.11it/s]

Reports:  33%|███▎      | 2366/7211 [09:50<15:31,  5.20it/s]

Reports:  33%|███▎      | 2367/7211 [09:50<17:03,  4.73it/s]

Reports:  33%|███▎      | 2368/7211 [09:50<17:29,  4.61it/s]

Reports:  33%|███▎      | 2369/7211 [09:50<19:27,  4.15it/s]

Reports:  33%|███▎      | 2370/7211 [09:51<18:25,  4.38it/s]

Reports:  33%|███▎      | 2371/7211 [09:51<17:31,  4.60it/s]

Reports:  33%|███▎      | 2372/7211 [09:51<16:37,  4.85it/s]

Reports:  33%|███▎      | 2373/7211 [09:51<17:10,  4.70it/s]

Reports:  33%|███▎      | 2374/7211 [09:51<16:20,  4.93it/s]

Reports:  33%|███▎      | 2375/7211 [09:52<16:04,  5.02it/s]

Reports:  33%|███▎      | 2376/7211 [09:52<16:07,  5.00it/s]

Reports:  33%|███▎      | 2377/7211 [09:52<15:56,  5.05it/s]

Reports:  33%|███▎      | 2378/7211 [09:52<19:46,  4.07it/s]

Reports:  33%|███▎      | 2379/7211 [09:52<18:15,  4.41it/s]

Reports:  33%|███▎      | 2380/7211 [09:53<17:19,  4.65it/s]

Reports:  33%|███▎      | 2381/7211 [09:53<16:32,  4.86it/s]

Reports:  33%|███▎      | 2382/7211 [09:53<16:00,  5.03it/s]

Reports:  33%|███▎      | 2383/7211 [09:53<15:53,  5.06it/s]

Reports:  33%|███▎      | 2384/7211 [09:53<15:49,  5.08it/s]

Reports:  33%|███▎      | 2385/7211 [09:54<16:25,  4.90it/s]

Reports:  33%|███▎      | 2386/7211 [09:54<16:08,  4.98it/s]

Reports:  33%|███▎      | 2387/7211 [09:54<15:45,  5.10it/s]

Reports:  33%|███▎      | 2388/7211 [09:54<15:38,  5.14it/s]

Reports:  33%|███▎      | 2389/7211 [09:54<16:05,  5.00it/s]

Reports:  33%|███▎      | 2390/7211 [09:55<15:55,  5.04it/s]

Reports:  33%|███▎      | 2391/7211 [09:55<16:03,  5.00it/s]

Reports:  33%|███▎      | 2392/7211 [09:55<15:54,  5.05it/s]

Reports:  33%|███▎      | 2393/7211 [09:55<15:59,  5.02it/s]

Reports:  33%|███▎      | 2394/7211 [09:55<16:05,  4.99it/s]

Reports:  33%|███▎      | 2395/7211 [09:56<15:38,  5.13it/s]

Reports:  33%|███▎      | 2396/7211 [09:56<15:36,  5.14it/s]

Reports:  33%|███▎      | 2397/7211 [09:56<15:17,  5.25it/s]

Reports:  33%|███▎      | 2398/7211 [09:56<16:16,  4.93it/s]

Reports:  33%|███▎      | 2399/7211 [09:56<15:59,  5.01it/s]

Reports:  33%|███▎      | 2400/7211 [09:57<16:01,  5.00it/s]

Reports:  33%|███▎      | 2401/7211 [09:57<15:34,  5.14it/s]

Reports:  33%|███▎      | 2402/7211 [09:57<15:47,  5.08it/s]

Reports:  33%|███▎      | 2403/7211 [09:57<15:39,  5.12it/s]

Reports:  33%|███▎      | 2404/7211 [09:58<42:10,  1.90it/s]

Reports:  33%|███▎      | 2405/7211 [09:59<34:07,  2.35it/s]

Reports:  33%|███▎      | 2406/7211 [09:59<28:26,  2.82it/s]

Reports:  33%|███▎      | 2407/7211 [09:59<24:18,  3.29it/s]

Reports:  33%|███▎      | 2408/7211 [09:59<21:47,  3.67it/s]

Reports:  33%|███▎      | 2409/7211 [09:59<19:57,  4.01it/s]

Reports:  33%|███▎      | 2410/7211 [10:00<18:26,  4.34it/s]

Reports:  33%|███▎      | 2411/7211 [10:00<17:26,  4.59it/s]

Reports:  33%|███▎      | 2412/7211 [10:00<16:50,  4.75it/s]

Reports:  33%|███▎      | 2413/7211 [10:00<16:19,  4.90it/s]

Reports:  33%|███▎      | 2414/7211 [10:00<15:54,  5.03it/s]

Reports:  33%|███▎      | 2415/7211 [10:01<15:59,  5.00it/s]

Reports:  34%|███▎      | 2416/7211 [10:01<15:59,  5.00it/s]

Reports:  34%|███▎      | 2417/7211 [10:01<15:54,  5.02it/s]

Reports:  34%|███▎      | 2418/7211 [10:01<15:45,  5.07it/s]

Reports:  34%|███▎      | 2419/7211 [10:01<16:03,  4.98it/s]

Reports:  34%|███▎      | 2420/7211 [10:02<15:41,  5.09it/s]

Reports:  34%|███▎      | 2421/7211 [10:02<15:22,  5.19it/s]

Reports:  34%|███▎      | 2422/7211 [10:02<15:29,  5.15it/s]

Reports:  34%|███▎      | 2423/7211 [10:02<15:50,  5.04it/s]

Reports:  34%|███▎      | 2424/7211 [10:02<16:00,  4.98it/s]

Reports:  34%|███▎      | 2425/7211 [10:03<15:53,  5.02it/s]

Reports:  34%|███▎      | 2426/7211 [10:03<15:54,  5.01it/s]

Reports:  34%|███▎      | 2427/7211 [10:03<15:31,  5.14it/s]

Reports:  34%|███▎      | 2428/7211 [10:03<15:58,  4.99it/s]

Reports:  34%|███▎      | 2429/7211 [10:03<15:57,  5.00it/s]

Reports:  34%|███▎      | 2430/7211 [10:04<15:42,  5.08it/s]

Reports:  34%|███▎      | 2431/7211 [10:04<15:27,  5.16it/s]

Reports:  34%|███▎      | 2432/7211 [10:04<15:32,  5.12it/s]

Reports:  34%|███▎      | 2433/7211 [10:04<15:56,  5.00it/s]

Reports:  34%|███▍      | 2434/7211 [10:04<16:00,  4.97it/s]

Reports:  34%|███▍      | 2435/7211 [10:05<15:33,  5.12it/s]

Reports:  34%|███▍      | 2436/7211 [10:05<15:39,  5.08it/s]

Reports:  34%|███▍      | 2437/7211 [10:05<15:20,  5.19it/s]

Reports:  34%|███▍      | 2438/7211 [10:05<15:15,  5.21it/s]

Reports:  34%|███▍      | 2439/7211 [10:05<15:14,  5.22it/s]

Reports:  34%|███▍      | 2440/7211 [10:05<14:57,  5.32it/s]

Reports:  34%|███▍      | 2441/7211 [10:06<14:53,  5.34it/s]

Reports:  34%|███▍      | 2442/7211 [10:06<14:56,  5.32it/s]

Reports:  34%|███▍      | 2443/7211 [10:06<15:02,  5.28it/s]

Reports:  34%|███▍      | 2444/7211 [10:06<14:55,  5.32it/s]

Reports:  34%|███▍      | 2445/7211 [10:06<15:10,  5.23it/s]

Reports:  34%|███▍      | 2446/7211 [10:07<14:59,  5.29it/s]

Reports:  34%|███▍      | 2447/7211 [10:07<14:57,  5.31it/s]

Reports:  34%|███▍      | 2448/7211 [10:07<14:55,  5.32it/s]

Reports:  34%|███▍      | 2449/7211 [10:07<15:00,  5.29it/s]

Reports:  34%|███▍      | 2450/7211 [10:07<15:13,  5.21it/s]

Reports:  34%|███▍      | 2451/7211 [10:08<15:17,  5.19it/s]

Reports:  34%|███▍      | 2452/7211 [10:08<14:59,  5.29it/s]

Reports:  34%|███▍      | 2453/7211 [10:08<15:04,  5.26it/s]

Reports:  34%|███▍      | 2454/7211 [10:08<15:13,  5.21it/s]

Reports:  34%|███▍      | 2455/7211 [10:08<15:05,  5.25it/s]

Reports:  34%|███▍      | 2456/7211 [10:09<14:52,  5.33it/s]

Reports:  34%|███▍      | 2457/7211 [10:09<14:56,  5.30it/s]

Reports:  34%|███▍      | 2458/7211 [10:09<14:58,  5.29it/s]

Reports:  34%|███▍      | 2459/7211 [10:09<15:13,  5.20it/s]

Reports:  34%|███▍      | 2460/7211 [10:09<15:02,  5.27it/s]

Reports:  34%|███▍      | 2461/7211 [10:09<15:16,  5.18it/s]

Reports:  34%|███▍      | 2462/7211 [10:10<15:23,  5.14it/s]

Reports:  34%|███▍      | 2463/7211 [10:10<15:15,  5.19it/s]

Reports:  34%|███▍      | 2464/7211 [10:10<15:24,  5.13it/s]

Reports:  34%|███▍      | 2465/7211 [10:10<15:57,  4.96it/s]

Reports:  34%|███▍      | 2466/7211 [10:10<15:34,  5.08it/s]

Reports:  34%|███▍      | 2467/7211 [10:11<15:38,  5.05it/s]

Reports:  34%|███▍      | 2468/7211 [10:11<15:43,  5.03it/s]

Reports:  34%|███▍      | 2469/7211 [10:11<15:26,  5.12it/s]

Reports:  34%|███▍      | 2470/7211 [10:11<15:13,  5.19it/s]

Reports:  34%|███▍      | 2471/7211 [10:11<15:32,  5.08it/s]

Reports:  34%|███▍      | 2472/7211 [10:12<15:29,  5.10it/s]

Reports:  34%|███▍      | 2473/7211 [10:12<15:19,  5.15it/s]

Reports:  34%|███▍      | 2474/7211 [10:12<15:32,  5.08it/s]

Reports:  34%|███▍      | 2475/7211 [10:12<15:29,  5.09it/s]

Reports:  34%|███▍      | 2476/7211 [10:12<15:33,  5.07it/s]

Reports:  34%|███▍      | 2477/7211 [10:13<15:35,  5.06it/s]

Reports:  34%|███▍      | 2478/7211 [10:13<15:20,  5.14it/s]

Reports:  34%|███▍      | 2479/7211 [10:13<15:25,  5.11it/s]

Reports:  34%|███▍      | 2480/7211 [10:13<15:07,  5.21it/s]

Reports:  34%|███▍      | 2481/7211 [10:13<15:03,  5.23it/s]

Reports:  34%|███▍      | 2482/7211 [10:14<15:23,  5.12it/s]

Reports:  34%|███▍      | 2483/7211 [10:35<8:32:35,  6.51s/it]

Reports:  34%|███▍      | 2484/7211 [10:35<6:05:15,  4.64s/it]

Reports:  34%|███▍      | 2485/7211 [10:35<4:19:53,  3.30s/it]

Reports:  34%|███▍      | 2486/7211 [10:35<3:06:31,  2.37s/it]

Reports:  34%|███▍      | 2487/7211 [10:36<2:15:10,  1.72s/it]

Reports:  35%|███▍      | 2488/7211 [10:36<1:39:02,  1.26s/it]

Reports:  35%|███▍      | 2489/7211 [10:36<1:14:12,  1.06it/s]

Reports:  35%|███▍      | 2490/7211 [10:36<56:23,  1.40it/s]

Reports:  35%|███▍      | 2491/7211 [10:36<44:03,  1.79it/s]

Reports:  35%|███▍      | 2492/7211 [10:37<35:40,  2.20it/s]

Reports:  35%|███▍      | 2493/7211 [10:37<29:34,  2.66it/s]

Reports:  35%|███▍      | 2494/7211 [10:37<25:18,  3.11it/s]

Reports:  35%|███▍      | 2495/7211 [10:37<22:08,  3.55it/s]

Reports:  35%|███▍      | 2496/7211 [10:37<20:30,  3.83it/s]

Reports:  35%|███▍      | 2497/7211 [10:38<19:10,  4.10it/s]

Reports:  35%|███▍      | 2498/7211 [10:38<17:58,  4.37it/s]

Reports:  35%|███▍      | 2499/7211 [10:38<17:27,  4.50it/s]

Reports:  35%|███▍      | 2500/7211 [10:38<16:48,  4.67it/s]

Reports:  35%|███▍      | 2501/7211 [10:38<16:32,  4.75it/s]

Reports:  35%|███▍      | 2502/7211 [10:39<16:12,  4.84it/s]

Reports:  35%|███▍      | 2503/7211 [10:39<16:20,  4.80it/s]

Reports:  35%|███▍      | 2504/7211 [10:39<16:03,  4.88it/s]

Reports:  35%|███▍      | 2505/7211 [10:39<15:38,  5.01it/s]

Reports:  35%|███▍      | 2506/7211 [10:39<15:53,  4.93it/s]

Reports:  35%|███▍      | 2507/7211 [10:40<15:32,  5.04it/s]

Reports:  35%|███▍      | 2508/7211 [10:40<15:37,  5.02it/s]

Reports:  35%|███▍      | 2509/7211 [10:40<15:20,  5.11it/s]

Reports:  35%|███▍      | 2510/7211 [10:40<15:09,  5.17it/s]

Reports:  35%|███▍      | 2511/7211 [10:40<15:22,  5.10it/s]

Reports:  35%|███▍      | 2512/7211 [10:41<16:14,  4.82it/s]

Reports:  35%|███▍      | 2513/7211 [10:41<15:46,  4.96it/s]

Reports:  35%|███▍      | 2514/7211 [10:41<15:20,  5.10it/s]

Reports:  35%|███▍      | 2515/7211 [10:41<14:57,  5.23it/s]

Reports:  35%|███▍      | 2516/7211 [10:41<15:02,  5.20it/s]

Reports:  35%|███▍      | 2517/7211 [10:42<14:49,  5.28it/s]

Reports:  35%|███▍      | 2518/7211 [10:42<14:42,  5.32it/s]

Reports:  35%|███▍      | 2519/7211 [10:42<14:30,  5.39it/s]

Reports:  35%|███▍      | 2520/7211 [10:42<15:31,  5.04it/s]

Reports:  35%|███▍      | 2521/7211 [10:42<15:24,  5.07it/s]

Reports:  35%|███▍      | 2522/7211 [10:43<15:14,  5.13it/s]

Reports:  35%|███▍      | 2523/7211 [10:43<15:24,  5.07it/s]

Reports:  35%|███▌      | 2524/7211 [10:43<15:20,  5.09it/s]

Reports:  35%|███▌      | 2525/7211 [10:43<15:17,  5.11it/s]

Reports:  35%|███▌      | 2526/7211 [10:43<14:58,  5.22it/s]

Reports:  35%|███▌      | 2527/7211 [10:44<14:56,  5.23it/s]

Reports:  35%|███▌      | 2528/7211 [10:44<14:56,  5.22it/s]

Reports:  35%|███▌      | 2529/7211 [10:44<14:47,  5.28it/s]

Reports:  35%|███▌      | 2530/7211 [10:44<14:46,  5.28it/s]

Reports:  35%|███▌      | 2531/7211 [10:44<14:37,  5.34it/s]

Reports:  35%|███▌      | 2532/7211 [10:44<14:41,  5.31it/s]

Reports:  35%|███▌      | 2533/7211 [10:45<14:47,  5.27it/s]

Reports:  35%|███▌      | 2534/7211 [10:45<14:38,  5.33it/s]

Reports:  35%|███▌      | 2535/7211 [10:45<14:57,  5.21it/s]

Reports:  35%|███▌      | 2536/7211 [10:45<15:08,  5.15it/s]

Reports:  35%|███▌      | 2537/7211 [10:45<15:02,  5.18it/s]

Reports:  35%|███▌      | 2538/7211 [10:46<15:15,  5.10it/s]

Reports:  35%|███▌      | 2539/7211 [10:46<15:17,  5.09it/s]

Reports:  35%|███▌      | 2540/7211 [10:46<14:54,  5.22it/s]

Reports:  35%|███▌      | 2541/7211 [10:46<14:49,  5.25it/s]

Reports:  35%|███▌      | 2542/7211 [10:46<14:45,  5.27it/s]

Reports:  35%|███▌      | 2543/7211 [10:47<15:09,  5.13it/s]

Reports:  35%|███▌      | 2544/7211 [10:47<15:05,  5.16it/s]

Reports:  35%|███▌      | 2545/7211 [10:47<14:58,  5.19it/s]

Reports:  35%|███▌      | 2546/7211 [10:47<15:16,  5.09it/s]

Reports:  35%|███▌      | 2547/7211 [10:47<15:01,  5.17it/s]

Reports:  35%|███▌      | 2548/7211 [10:48<15:21,  5.06it/s]

Reports:  35%|███▌      | 2549/7211 [10:48<15:01,  5.17it/s]

Reports:  35%|███▌      | 2550/7211 [10:48<15:13,  5.10it/s]

Reports:  35%|███▌      | 2551/7211 [10:48<15:33,  4.99it/s]

Reports:  35%|███▌      | 2552/7211 [10:48<15:37,  4.97it/s]

Reports:  35%|███▌      | 2553/7211 [10:49<15:25,  5.03it/s]

Reports:  35%|███▌      | 2554/7211 [10:49<15:00,  5.17it/s]

Reports:  35%|███▌      | 2555/7211 [10:49<14:43,  5.27it/s]

Reports:  35%|███▌      | 2556/7211 [10:49<14:34,  5.32it/s]

Reports:  35%|███▌      | 2557/7211 [10:49<14:25,  5.38it/s]

Reports:  35%|███▌      | 2558/7211 [10:49<14:23,  5.39it/s]

Reports:  35%|███▌      | 2559/7211 [10:50<14:52,  5.21it/s]

Reports:  36%|███▌      | 2560/7211 [10:50<14:43,  5.26it/s]

Reports:  36%|███▌      | 2561/7211 [10:50<14:55,  5.19it/s]

Reports:  36%|███▌      | 2562/7211 [10:50<15:17,  5.07it/s]

Reports:  36%|███▌      | 2563/7211 [10:50<14:51,  5.21it/s]

Reports:  36%|███▌      | 2564/7211 [10:51<14:53,  5.20it/s]

Reports:  36%|███▌      | 2565/7211 [10:51<14:44,  5.25it/s]

Reports:  36%|███▌      | 2566/7211 [10:51<14:30,  5.34it/s]

Reports:  36%|███▌      | 2567/7211 [10:51<14:43,  5.26it/s]

Reports:  36%|███▌      | 2568/7211 [10:51<14:32,  5.32it/s]

Reports:  36%|███▌      | 2569/7211 [10:52<14:31,  5.33it/s]

Reports:  36%|███▌      | 2570/7211 [10:52<14:44,  5.25it/s]

Reports:  36%|███▌      | 2571/7211 [10:52<14:41,  5.27it/s]

Reports:  36%|███▌      | 2572/7211 [10:52<14:46,  5.23it/s]

Reports:  36%|███▌      | 2573/7211 [10:52<14:37,  5.29it/s]

Reports:  36%|███▌      | 2574/7211 [10:53<14:53,  5.19it/s]

Reports:  36%|███▌      | 2575/7211 [10:53<15:03,  5.13it/s]

Reports:  36%|███▌      | 2576/7211 [10:53<15:09,  5.09it/s]

Reports:  36%|███▌      | 2577/7211 [10:53<15:24,  5.01it/s]

Reports:  36%|███▌      | 2578/7211 [10:53<15:16,  5.06it/s]

Reports:  36%|███▌      | 2579/7211 [10:54<15:28,  4.99it/s]

Reports:  36%|███▌      | 2580/7211 [10:54<15:07,  5.11it/s]

Reports:  36%|███▌      | 2581/7211 [10:54<15:00,  5.14it/s]

Reports:  36%|███▌      | 2582/7211 [10:54<15:05,  5.11it/s]

Reports:  36%|███▌      | 2583/7211 [10:54<15:07,  5.10it/s]

Reports:  36%|███▌      | 2584/7211 [10:55<15:10,  5.08it/s]

Reports:  36%|███▌      | 2585/7211 [10:55<15:24,  5.00it/s]

Reports:  36%|███▌      | 2586/7211 [10:55<17:05,  4.51it/s]

Reports:  36%|███▌      | 2587/7211 [10:55<17:35,  4.38it/s]

Reports:  36%|███▌      | 2588/7211 [10:55<17:09,  4.49it/s]

Reports:  36%|███▌      | 2589/7211 [10:56<16:24,  4.69it/s]

Reports:  36%|███▌      | 2590/7211 [10:56<16:14,  4.74it/s]

Reports:  36%|███▌      | 2591/7211 [10:56<15:44,  4.89it/s]

Reports:  36%|███▌      | 2592/7211 [10:56<15:23,  5.00it/s]

Reports:  36%|███▌      | 2593/7211 [10:56<15:08,  5.09it/s]

Reports:  36%|███▌      | 2594/7211 [10:57<14:55,  5.16it/s]

Reports:  36%|███▌      | 2595/7211 [10:57<14:45,  5.21it/s]

Reports:  36%|███▌      | 2596/7211 [10:57<14:41,  5.24it/s]

Reports:  36%|███▌      | 2597/7211 [10:57<14:49,  5.19it/s]

Reports:  36%|███▌      | 2598/7211 [10:57<14:52,  5.17it/s]

Reports:  36%|███▌      | 2599/7211 [10:58<14:46,  5.20it/s]

Reports:  36%|███▌      | 2600/7211 [10:58<14:48,  5.19it/s]

Reports:  36%|███▌      | 2601/7211 [10:58<14:43,  5.22it/s]

Reports:  36%|███▌      | 2602/7211 [10:58<14:32,  5.28it/s]

Reports:  36%|███▌      | 2603/7211 [10:58<14:40,  5.23it/s]

Reports:  36%|███▌      | 2604/7211 [10:59<14:30,  5.29it/s]

Reports:  36%|███▌      | 2605/7211 [10:59<14:24,  5.33it/s]

Reports:  36%|███▌      | 2606/7211 [10:59<14:15,  5.39it/s]

Reports:  36%|███▌      | 2607/7211 [10:59<14:16,  5.37it/s]

Reports:  36%|███▌      | 2608/7211 [10:59<14:19,  5.35it/s]

Reports:  36%|███▌      | 2609/7211 [10:59<14:19,  5.35it/s]

Reports:  36%|███▌      | 2610/7211 [11:00<14:16,  5.37it/s]

Reports:  36%|███▌      | 2611/7211 [11:00<14:27,  5.30it/s]

Reports:  36%|███▌      | 2612/7211 [11:00<14:30,  5.28it/s]

Reports:  36%|███▌      | 2613/7211 [11:00<14:22,  5.33it/s]

Reports:  36%|███▋      | 2614/7211 [11:00<14:21,  5.33it/s]

Reports:  36%|███▋      | 2615/7211 [11:01<14:33,  5.26it/s]

Reports:  36%|███▋      | 2616/7211 [11:01<14:16,  5.36it/s]

Reports:  36%|███▋      | 2617/7211 [11:01<14:29,  5.28it/s]

Reports:  36%|███▋      | 2618/7211 [11:01<14:43,  5.20it/s]

Reports:  36%|███▋      | 2619/7211 [11:01<14:44,  5.19it/s]

Reports:  36%|███▋      | 2620/7211 [11:02<14:37,  5.23it/s]

Reports:  36%|███▋      | 2621/7211 [11:02<14:27,  5.29it/s]

Reports:  36%|███▋      | 2622/7211 [11:02<14:42,  5.20it/s]

Reports:  36%|███▋      | 2623/7211 [11:02<14:30,  5.27it/s]

Reports:  36%|███▋      | 2624/7211 [11:02<14:48,  5.16it/s]

Reports:  36%|███▋      | 2625/7211 [11:02<14:44,  5.18it/s]

Reports:  36%|███▋      | 2626/7211 [11:03<14:38,  5.22it/s]

Reports:  36%|███▋      | 2627/7211 [11:03<14:33,  5.25it/s]

Reports:  36%|███▋      | 2628/7211 [11:03<14:46,  5.17it/s]

Reports:  36%|███▋      | 2629/7211 [11:03<15:08,  5.04it/s]

Reports:  36%|███▋      | 2630/7211 [11:03<15:07,  5.05it/s]

Reports:  36%|███▋      | 2631/7211 [11:04<18:07,  4.21it/s]

Reports:  36%|███▋      | 2632/7211 [11:04<16:54,  4.51it/s]

Reports:  37%|███▋      | 2633/7211 [11:04<16:31,  4.62it/s]

Reports:  37%|███▋      | 2634/7211 [11:04<15:53,  4.80it/s]

Reports:  37%|███▋      | 2635/7211 [11:05<15:49,  4.82it/s]

Reports:  37%|███▋      | 2636/7211 [11:05<15:14,  5.00it/s]

Reports:  37%|███▋      | 2637/7211 [11:05<15:19,  4.97it/s]

Reports:  37%|███▋      | 2638/7211 [11:05<15:05,  5.05it/s]

Reports:  37%|███▋      | 2639/7211 [11:05<15:04,  5.06it/s]

Reports:  37%|███▋      | 2640/7211 [11:06<14:50,  5.13it/s]

Reports:  37%|███▋      | 2641/7211 [11:06<14:52,  5.12it/s]

Reports:  37%|███▋      | 2642/7211 [11:06<14:45,  5.16it/s]

Reports:  37%|███▋      | 2643/7211 [11:06<14:55,  5.10it/s]

Reports:  37%|███▋      | 2644/7211 [11:06<15:02,  5.06it/s]

Reports:  37%|███▋      | 2645/7211 [11:07<14:53,  5.11it/s]

Reports:  37%|███▋      | 2646/7211 [11:07<14:22,  5.29it/s]

Reports:  37%|███▋      | 2647/7211 [11:07<14:28,  5.25it/s]

Reports:  37%|███▋      | 2648/7211 [11:07<14:39,  5.19it/s]

Reports:  37%|███▋      | 2649/7211 [11:07<14:28,  5.25it/s]

Reports:  37%|███▋      | 2650/7211 [11:07<14:31,  5.23it/s]

Reports:  37%|███▋      | 2651/7211 [11:08<14:44,  5.16it/s]

Reports:  37%|███▋      | 2652/7211 [11:08<14:39,  5.18it/s]

Reports:  37%|███▋      | 2653/7211 [11:08<14:21,  5.29it/s]

Reports:  37%|███▋      | 2654/7211 [11:08<14:08,  5.37it/s]

Reports:  37%|███▋      | 2655/7211 [11:08<14:24,  5.27it/s]

Reports:  37%|███▋      | 2656/7211 [11:09<19:37,  3.87it/s]

Reports:  37%|███▋      | 2657/7211 [11:09<18:02,  4.21it/s]

Reports:  37%|███▋      | 2658/7211 [11:09<17:05,  4.44it/s]

Reports:  37%|███▋      | 2659/7211 [11:09<16:33,  4.58it/s]

Reports:  37%|███▋      | 2660/7211 [11:10<15:56,  4.76it/s]

Reports:  37%|███▋      | 2661/7211 [11:10<15:16,  4.97it/s]

Reports:  37%|███▋      | 2662/7211 [11:10<14:40,  5.17it/s]

Reports:  37%|███▋      | 2663/7211 [11:10<14:51,  5.10it/s]

Reports:  37%|███▋      | 2664/7211 [11:10<14:54,  5.09it/s]

Reports:  37%|███▋      | 2665/7211 [11:11<15:02,  5.04it/s]

Reports:  37%|███▋      | 2666/7211 [11:11<14:37,  5.18it/s]

Reports:  37%|███▋      | 2667/7211 [11:11<14:27,  5.24it/s]

Reports:  37%|███▋      | 2668/7211 [11:11<14:29,  5.22it/s]

Reports:  37%|███▋      | 2669/7211 [11:11<14:24,  5.25it/s]

Reports:  37%|███▋      | 2670/7211 [11:12<14:25,  5.25it/s]

Reports:  37%|███▋      | 2671/7211 [11:12<14:44,  5.13it/s]

Reports:  37%|███▋      | 2672/7211 [11:12<15:08,  5.00it/s]

Reports:  37%|███▋      | 2673/7211 [11:12<20:16,  3.73it/s]

Reports:  37%|███▋      | 2674/7211 [11:13<18:40,  4.05it/s]

Reports:  37%|███▋      | 2675/7211 [11:13<17:14,  4.38it/s]

Reports:  37%|███▋      | 2676/7211 [11:13<16:37,  4.55it/s]

Reports:  37%|███▋      | 2677/7211 [11:13<16:15,  4.65it/s]

Reports:  37%|███▋      | 2678/7211 [11:13<15:40,  4.82it/s]

Reports:  37%|███▋      | 2679/7211 [11:14<15:24,  4.90it/s]

Reports:  37%|███▋      | 2680/7211 [11:14<14:56,  5.06it/s]

Reports:  37%|███▋      | 2681/7211 [11:14<14:48,  5.10it/s]

Reports:  37%|███▋      | 2682/7211 [11:14<14:44,  5.12it/s]

Reports:  37%|███▋      | 2683/7211 [11:14<14:22,  5.25it/s]

Reports:  37%|███▋      | 2684/7211 [11:14<14:10,  5.32it/s]

Reports:  37%|███▋      | 2685/7211 [11:15<14:06,  5.34it/s]

Reports:  37%|███▋      | 2686/7211 [11:15<14:13,  5.30it/s]

Reports:  37%|███▋      | 2687/7211 [11:15<14:12,  5.31it/s]

Reports:  37%|███▋      | 2688/7211 [11:15<14:11,  5.31it/s]

Reports:  37%|███▋      | 2689/7211 [11:15<14:26,  5.22it/s]

Reports:  37%|███▋      | 2690/7211 [11:16<14:29,  5.20it/s]

Reports:  37%|███▋      | 2691/7211 [11:16<14:35,  5.16it/s]

Reports:  37%|███▋      | 2692/7211 [11:16<14:23,  5.23it/s]

Reports:  37%|███▋      | 2693/7211 [11:16<14:32,  5.18it/s]

Reports:  37%|███▋      | 2694/7211 [11:16<14:19,  5.25it/s]

Reports:  37%|███▋      | 2695/7211 [11:17<14:27,  5.21it/s]

Reports:  37%|███▋      | 2696/7211 [11:17<14:26,  5.21it/s]

Reports:  37%|███▋      | 2697/7211 [11:17<14:28,  5.20it/s]

Reports:  37%|███▋      | 2698/7211 [11:17<14:30,  5.19it/s]

Reports:  37%|███▋      | 2699/7211 [11:17<14:25,  5.21it/s]

Reports:  37%|███▋      | 2700/7211 [11:18<14:18,  5.26it/s]

Reports:  37%|███▋      | 2701/7211 [11:18<14:12,  5.29it/s]

Reports:  37%|███▋      | 2702/7211 [11:18<15:25,  4.87it/s]

Reports:  37%|███▋      | 2703/7211 [11:18<15:07,  4.97it/s]

Reports:  37%|███▋      | 2704/7211 [11:18<15:15,  4.92it/s]

Reports:  38%|███▊      | 2705/7211 [11:19<15:13,  4.93it/s]

Reports:  38%|███▊      | 2706/7211 [11:19<14:54,  5.03it/s]

Reports:  38%|███▊      | 2707/7211 [11:19<15:02,  4.99it/s]

Reports:  38%|███▊      | 2708/7211 [11:19<14:49,  5.06it/s]

Reports:  38%|███▊      | 2709/7211 [11:19<14:37,  5.13it/s]

Reports:  38%|███▊      | 2710/7211 [11:20<14:37,  5.13it/s]

Reports:  38%|███▊      | 2711/7211 [11:20<14:43,  5.09it/s]

Reports:  38%|███▊      | 2712/7211 [11:20<14:23,  5.21it/s]

Reports:  38%|███▊      | 2713/7211 [11:20<14:20,  5.23it/s]

Reports:  38%|███▊      | 2714/7211 [11:20<14:27,  5.19it/s]

Reports:  38%|███▊      | 2715/7211 [11:20<14:20,  5.22it/s]

Reports:  38%|███▊      | 2716/7211 [11:21<14:39,  5.11it/s]

Reports:  38%|███▊      | 2717/7211 [11:21<14:27,  5.18it/s]

Reports:  38%|███▊      | 2718/7211 [11:21<14:43,  5.08it/s]

Reports:  38%|███▊      | 2719/7211 [11:21<14:49,  5.05it/s]

Reports:  38%|███▊      | 2720/7211 [11:21<14:34,  5.14it/s]

Reports:  38%|███▊      | 2721/7211 [11:22<14:43,  5.08it/s]

Reports:  38%|███▊      | 2722/7211 [11:22<14:31,  5.15it/s]

Reports:  38%|███▊      | 2723/7211 [11:22<14:42,  5.08it/s]

Reports:  38%|███▊      | 2724/7211 [11:22<14:24,  5.19it/s]

Reports:  38%|███▊      | 2725/7211 [11:22<14:21,  5.21it/s]

Reports:  38%|███▊      | 2726/7211 [11:23<14:36,  5.12it/s]

Reports:  38%|███▊      | 2727/7211 [11:23<14:17,  5.23it/s]

Reports:  38%|███▊      | 2728/7211 [11:23<14:29,  5.16it/s]

Reports:  38%|███▊      | 2729/7211 [11:23<14:32,  5.14it/s]

Reports:  38%|███▊      | 2730/7211 [11:23<15:01,  4.97it/s]

Reports:  38%|███▊      | 2731/7211 [11:24<16:32,  4.51it/s]

Reports:  38%|███▊      | 2732/7211 [11:24<15:51,  4.71it/s]

Reports:  38%|███▊      | 2733/7211 [11:24<15:18,  4.88it/s]

Reports:  38%|███▊      | 2734/7211 [11:24<15:22,  4.85it/s]

Reports:  38%|███▊      | 2735/7211 [11:24<14:50,  5.02it/s]

Reports:  38%|███▊      | 2736/7211 [11:25<14:33,  5.12it/s]

Reports:  38%|███▊      | 2737/7211 [11:25<14:25,  5.17it/s]

Reports:  38%|███▊      | 2738/7211 [11:25<14:40,  5.08it/s]

Reports:  38%|███▊      | 2739/7211 [11:25<14:42,  5.07it/s]

Reports:  38%|███▊      | 2740/7211 [11:25<14:45,  5.05it/s]

Reports:  38%|███▊      | 2741/7211 [11:26<14:27,  5.15it/s]

Reports:  38%|███▊      | 2742/7211 [11:26<14:32,  5.12it/s]

Reports:  38%|███▊      | 2743/7211 [11:26<14:25,  5.17it/s]

Reports:  38%|███▊      | 2744/7211 [11:26<14:19,  5.20it/s]

Reports:  38%|███▊      | 2745/7211 [11:26<14:13,  5.23it/s]

Reports:  38%|███▊      | 2746/7211 [11:27<14:25,  5.16it/s]

Reports:  38%|███▊      | 2747/7211 [11:27<14:23,  5.17it/s]

Reports:  38%|███▊      | 2748/7211 [11:27<14:14,  5.22it/s]

Reports:  38%|███▊      | 2749/7211 [11:27<14:07,  5.27it/s]

Reports:  38%|███▊      | 2750/7211 [11:27<14:21,  5.18it/s]

Reports:  38%|███▊      | 2751/7211 [11:29<37:49,  1.97it/s]

Reports:  38%|███▊      | 2752/7211 [11:29<30:56,  2.40it/s]

Reports:  38%|███▊      | 2753/7211 [11:29<25:59,  2.86it/s]

Reports:  38%|███▊      | 2754/7211 [11:29<22:33,  3.29it/s]

Reports:  38%|███▊      | 2755/7211 [11:29<19:53,  3.73it/s]

Reports:  38%|███▊      | 2756/7211 [11:30<18:16,  4.06it/s]

Reports:  38%|███▊      | 2757/7211 [11:30<17:01,  4.36it/s]

Reports:  38%|███▊      | 2758/7211 [11:30<16:07,  4.60it/s]

Reports:  38%|███▊      | 2759/7211 [11:30<15:25,  4.81it/s]

Reports:  38%|███▊      | 2760/7211 [11:30<14:50,  5.00it/s]

Reports:  38%|███▊      | 2761/7211 [11:31<14:38,  5.06it/s]

Reports:  38%|███▊      | 2762/7211 [11:31<14:31,  5.10it/s]

Reports:  38%|███▊      | 2763/7211 [11:31<14:32,  5.10it/s]

Reports:  38%|███▊      | 2764/7211 [11:31<14:16,  5.19it/s]

Reports:  38%|███▊      | 2765/7211 [11:31<14:13,  5.21it/s]

Reports:  38%|███▊      | 2766/7211 [11:31<14:33,  5.09it/s]

Reports:  38%|███▊      | 2767/7211 [11:32<14:15,  5.20it/s]

Reports:  38%|███▊      | 2768/7211 [11:32<14:15,  5.19it/s]

Reports:  38%|███▊      | 2769/7211 [11:32<14:10,  5.22it/s]

Reports:  38%|███▊      | 2770/7211 [11:32<14:06,  5.25it/s]

Reports:  38%|███▊      | 2771/7211 [11:32<14:18,  5.17it/s]

Reports:  38%|███▊      | 2772/7211 [11:33<14:08,  5.23it/s]

Reports:  38%|███▊      | 2773/7211 [11:33<14:04,  5.26it/s]

Reports:  38%|███▊      | 2774/7211 [11:33<13:55,  5.31it/s]

Reports:  38%|███▊      | 2775/7211 [11:33<14:00,  5.28it/s]

Reports:  38%|███▊      | 2776/7211 [11:33<14:01,  5.27it/s]

Reports:  39%|███▊      | 2777/7211 [11:34<16:46,  4.41it/s]

Reports:  39%|███▊      | 2778/7211 [11:36<59:38,  1.24it/s]

Reports:  39%|███▊      | 2779/7211 [11:36<47:01,  1.57it/s]

Reports:  39%|███▊      | 2780/7211 [11:36<37:22,  1.98it/s]

Reports:  39%|███▊      | 2781/7211 [11:37<39:53,  1.85it/s]

Reports:  39%|███▊      | 2782/7211 [11:37<32:01,  2.31it/s]

Reports:  39%|███▊      | 2783/7211 [11:37<26:33,  2.78it/s]

Reports:  39%|███▊      | 2784/7211 [11:37<22:52,  3.23it/s]

Reports:  39%|███▊      | 2785/7211 [11:38<29:37,  2.49it/s]

Reports:  39%|███▊      | 2786/7211 [11:38<25:07,  2.94it/s]

Reports:  39%|███▊      | 2787/7211 [11:38<21:48,  3.38it/s]

Reports:  39%|███▊      | 2788/7211 [11:39<19:36,  3.76it/s]

Reports:  39%|███▊      | 2789/7211 [11:39<17:53,  4.12it/s]

Reports:  39%|███▊      | 2790/7211 [11:39<17:02,  4.32it/s]

Reports:  39%|███▊      | 2791/7211 [11:39<16:31,  4.46it/s]

Reports:  39%|███▊      | 2792/7211 [11:39<15:40,  4.70it/s]

Reports:  39%|███▊      | 2793/7211 [11:40<15:24,  4.78it/s]

Reports:  39%|███▊      | 2794/7211 [11:40<15:22,  4.79it/s]

Reports:  39%|███▉      | 2795/7211 [11:40<14:57,  4.92it/s]

Reports:  39%|███▉      | 2796/7211 [11:40<14:43,  5.00it/s]

Reports:  39%|███▉      | 2797/7211 [11:40<14:32,  5.06it/s]

Reports:  39%|███▉      | 2798/7211 [11:41<15:06,  4.87it/s]

Reports:  39%|███▉      | 2799/7211 [11:41<14:45,  4.98it/s]

Reports:  39%|███▉      | 2800/7211 [11:41<14:19,  5.13it/s]

Reports:  39%|███▉      | 2801/7211 [11:41<14:33,  5.05it/s]

Reports:  39%|███▉      | 2802/7211 [11:41<14:34,  5.04it/s]

Reports:  39%|███▉      | 2803/7211 [11:42<14:27,  5.08it/s]

Reports:  39%|███▉      | 2804/7211 [11:42<14:07,  5.20it/s]

Reports:  39%|███▉      | 2805/7211 [11:42<14:00,  5.24it/s]

Reports:  39%|███▉      | 2806/7211 [11:42<14:08,  5.19it/s]

Reports:  39%|███▉      | 2807/7211 [11:42<14:27,  5.07it/s]

Reports:  39%|███▉      | 2808/7211 [11:43<14:26,  5.08it/s]

Reports:  39%|███▉      | 2809/7211 [11:43<14:20,  5.11it/s]

Reports:  39%|███▉      | 2810/7211 [11:43<14:25,  5.09it/s]

Reports:  39%|███▉      | 2811/7211 [11:43<14:15,  5.14it/s]

Reports:  39%|███▉      | 2812/7211 [11:43<14:19,  5.12it/s]

Reports:  39%|███▉      | 2813/7211 [11:44<14:09,  5.18it/s]

Reports:  39%|███▉      | 2814/7211 [11:44<14:19,  5.11it/s]

Reports:  39%|███▉      | 2815/7211 [11:44<14:05,  5.20it/s]

Reports:  39%|███▉      | 2816/7211 [11:44<14:05,  5.20it/s]

Reports:  39%|███▉      | 2817/7211 [11:44<13:55,  5.26it/s]

Reports:  39%|███▉      | 2818/7211 [11:45<13:47,  5.31it/s]

Reports:  39%|███▉      | 2819/7211 [11:45<13:43,  5.33it/s]

Reports:  39%|███▉      | 2820/7211 [11:45<13:54,  5.26it/s]

Reports:  39%|███▉      | 2821/7211 [11:45<13:46,  5.31it/s]

Reports:  39%|███▉      | 2822/7211 [11:45<14:01,  5.22it/s]

Reports:  39%|███▉      | 2823/7211 [11:46<14:16,  5.12it/s]

Reports:  39%|███▉      | 2824/7211 [11:46<14:20,  5.10it/s]

Reports:  39%|███▉      | 2825/7211 [11:46<14:01,  5.21it/s]

Reports:  39%|███▉      | 2826/7211 [11:46<14:00,  5.22it/s]

Reports:  39%|███▉      | 2827/7211 [11:46<13:41,  5.34it/s]

Reports:  39%|███▉      | 2828/7211 [11:46<13:51,  5.27it/s]

Reports:  39%|███▉      | 2829/7211 [11:47<14:03,  5.19it/s]

Reports:  39%|███▉      | 2830/7211 [11:47<14:06,  5.18it/s]

Reports:  39%|███▉      | 2831/7211 [11:47<13:53,  5.26it/s]

Reports:  39%|███▉      | 2832/7211 [11:47<14:05,  5.18it/s]

Reports:  39%|███▉      | 2833/7211 [11:47<14:16,  5.11it/s]

Reports:  39%|███▉      | 2834/7211 [11:48<14:20,  5.09it/s]

Reports:  39%|███▉      | 2835/7211 [11:48<14:19,  5.09it/s]

Reports:  39%|███▉      | 2836/7211 [11:48<14:22,  5.07it/s]

Reports:  39%|███▉      | 2837/7211 [11:48<14:29,  5.03it/s]

Reports:  39%|███▉      | 2838/7211 [11:48<14:33,  5.00it/s]

Reports:  39%|███▉      | 2839/7211 [11:49<14:16,  5.11it/s]

Reports:  39%|███▉      | 2840/7211 [11:49<14:01,  5.20it/s]

Reports:  39%|███▉      | 2841/7211 [11:49<13:47,  5.28it/s]

Reports:  39%|███▉      | 2842/7211 [11:49<13:42,  5.31it/s]

Reports:  39%|███▉      | 2843/7211 [11:49<13:48,  5.27it/s]

Reports:  39%|███▉      | 2844/7211 [11:50<13:49,  5.27it/s]

Reports:  39%|███▉      | 2845/7211 [11:50<13:53,  5.24it/s]

Reports:  39%|███▉      | 2846/7211 [11:50<13:51,  5.25it/s]

Reports:  39%|███▉      | 2847/7211 [11:50<14:09,  5.14it/s]

Reports:  39%|███▉      | 2848/7211 [11:50<14:08,  5.14it/s]

Reports:  40%|███▉      | 2849/7211 [11:51<14:05,  5.16it/s]

Reports:  40%|███▉      | 2850/7211 [11:51<13:45,  5.28it/s]

Reports:  40%|███▉      | 2851/7211 [11:51<14:02,  5.17it/s]

Reports:  40%|███▉      | 2852/7211 [11:51<13:58,  5.20it/s]

Reports:  40%|███▉      | 2853/7211 [11:51<14:18,  5.08it/s]

Reports:  40%|███▉      | 2854/7211 [11:52<32:41,  2.22it/s]

Reports:  40%|███▉      | 2855/7211 [11:53<27:15,  2.66it/s]

Reports:  40%|███▉      | 2856/7211 [11:53<23:30,  3.09it/s]

Reports:  40%|███▉      | 2857/7211 [11:53<20:35,  3.52it/s]

Reports:  40%|███▉      | 2858/7211 [11:53<18:35,  3.90it/s]

Reports:  40%|███▉      | 2859/7211 [11:53<17:06,  4.24it/s]

Reports:  40%|███▉      | 2860/7211 [11:54<16:09,  4.49it/s]

Reports:  40%|███▉      | 2861/7211 [11:54<15:46,  4.60it/s]

Reports:  40%|███▉      | 2862/7211 [11:54<15:07,  4.79it/s]

Reports:  40%|███▉      | 2863/7211 [11:54<14:44,  4.92it/s]

Reports:  40%|███▉      | 2864/7211 [11:54<14:47,  4.90it/s]

Reports:  40%|███▉      | 2865/7211 [11:54<14:19,  5.06it/s]

Reports:  40%|███▉      | 2866/7211 [11:55<14:16,  5.07it/s]

Reports:  40%|███▉      | 2867/7211 [11:55<13:58,  5.18it/s]

Reports:  40%|███▉      | 2868/7211 [11:55<13:44,  5.27it/s]

Reports:  40%|███▉      | 2869/7211 [11:55<13:51,  5.22it/s]

Reports:  40%|███▉      | 2870/7211 [11:55<14:13,  5.09it/s]

Reports:  40%|███▉      | 2871/7211 [11:56<13:54,  5.20it/s]

Reports:  40%|███▉      | 2872/7211 [11:56<14:10,  5.10it/s]

Reports:  40%|███▉      | 2873/7211 [11:56<23:51,  3.03it/s]

Reports:  40%|███▉      | 2874/7211 [11:57<21:02,  3.44it/s]

Reports:  40%|███▉      | 2875/7211 [11:57<18:41,  3.87it/s]

Reports:  40%|███▉      | 2876/7211 [11:58<32:38,  2.21it/s]

Reports:  40%|███▉      | 2877/7211 [11:58<26:52,  2.69it/s]

Reports:  40%|███▉      | 2878/7211 [11:58<23:05,  3.13it/s]

Reports:  40%|███▉      | 2879/7211 [11:58<20:13,  3.57it/s]

Reports:  40%|███▉      | 2880/7211 [11:59<18:22,  3.93it/s]

Reports:  40%|███▉      | 2881/7211 [11:59<17:20,  4.16it/s]

Reports:  40%|███▉      | 2882/7211 [11:59<16:05,  4.48it/s]

Reports:  40%|███▉      | 2883/7211 [11:59<15:36,  4.62it/s]

Reports:  40%|███▉      | 2884/7211 [11:59<14:59,  4.81it/s]

Reports:  40%|████      | 2885/7211 [12:00<14:45,  4.89it/s]

Reports:  40%|████      | 2886/7211 [12:00<15:00,  4.80it/s]

Reports:  40%|████      | 2887/7211 [12:00<17:17,  4.17it/s]

Reports:  40%|████      | 2888/7211 [12:00<17:18,  4.16it/s]

Reports:  40%|████      | 2889/7211 [12:00<16:18,  4.42it/s]

Reports:  40%|████      | 2890/7211 [12:01<15:19,  4.70it/s]

Reports:  40%|████      | 2891/7211 [12:01<15:03,  4.78it/s]

Reports:  40%|████      | 2892/7211 [12:01<14:46,  4.87it/s]

Reports:  40%|████      | 2893/7211 [12:01<14:21,  5.01it/s]

Reports:  40%|████      | 2894/7211 [12:01<14:16,  5.04it/s]

Reports:  40%|████      | 2895/7211 [12:02<14:00,  5.14it/s]

Reports:  40%|████      | 2896/7211 [12:02<14:01,  5.13it/s]

Reports:  40%|████      | 2897/7211 [12:02<13:43,  5.24it/s]

Reports:  40%|████      | 2898/7211 [12:02<13:34,  5.30it/s]

Reports:  40%|████      | 2899/7211 [12:03<18:56,  3.80it/s]

Reports:  40%|████      | 2900/7211 [12:03<17:13,  4.17it/s]

Reports:  40%|████      | 2901/7211 [12:03<16:10,  4.44it/s]

Reports:  40%|████      | 2902/7211 [12:03<15:21,  4.68it/s]

Reports:  40%|████      | 2903/7211 [12:03<14:38,  4.90it/s]

Reports:  40%|████      | 2904/7211 [12:04<14:10,  5.07it/s]

Reports:  40%|████      | 2905/7211 [12:04<14:00,  5.12it/s]

Reports:  40%|████      | 2906/7211 [12:04<13:53,  5.17it/s]

Reports:  40%|████      | 2907/7211 [12:04<13:44,  5.22it/s]

Reports:  40%|████      | 2908/7211 [12:04<13:34,  5.28it/s]

Reports:  40%|████      | 2909/7211 [12:04<13:34,  5.28it/s]

Reports:  40%|████      | 2910/7211 [12:05<13:38,  5.26it/s]

Reports:  40%|████      | 2911/7211 [12:05<13:46,  5.20it/s]

Reports:  40%|████      | 2912/7211 [12:05<13:42,  5.22it/s]

Reports:  40%|████      | 2913/7211 [12:05<13:55,  5.14it/s]

Reports:  40%|████      | 2914/7211 [12:05<13:51,  5.17it/s]

Reports:  40%|████      | 2915/7211 [12:06<13:50,  5.17it/s]

Reports:  40%|████      | 2916/7211 [12:06<24:19,  2.94it/s]

Reports:  40%|████      | 2917/7211 [12:07<23:59,  2.98it/s]

Reports:  40%|████      | 2918/7211 [12:07<21:18,  3.36it/s]

Reports:  40%|████      | 2919/7211 [12:07<19:29,  3.67it/s]

Reports:  40%|████      | 2920/7211 [12:07<17:30,  4.08it/s]

Reports:  41%|████      | 2921/7211 [12:07<16:18,  4.38it/s]

Reports:  41%|████      | 2922/7211 [12:08<15:56,  4.48it/s]

Reports:  41%|████      | 2923/7211 [12:08<15:34,  4.59it/s]

Reports:  41%|████      | 2924/7211 [12:08<14:57,  4.78it/s]

Reports:  41%|████      | 2925/7211 [12:08<14:48,  4.82it/s]

Reports:  41%|████      | 2926/7211 [12:08<14:39,  4.87it/s]

Reports:  41%|████      | 2927/7211 [12:09<14:06,  5.06it/s]

Reports:  41%|████      | 2928/7211 [12:09<14:05,  5.06it/s]

Reports:  41%|████      | 2929/7211 [12:09<13:49,  5.16it/s]

Reports:  41%|████      | 2930/7211 [12:09<13:48,  5.16it/s]

Reports:  41%|████      | 2931/7211 [12:09<14:02,  5.08it/s]

Reports:  41%|████      | 2932/7211 [12:10<13:54,  5.13it/s]

Reports:  41%|████      | 2933/7211 [12:10<13:53,  5.13it/s]

Reports:  41%|████      | 2934/7211 [12:10<13:45,  5.18it/s]

Reports:  41%|████      | 2935/7211 [12:10<13:39,  5.22it/s]

Reports:  41%|████      | 2936/7211 [12:10<13:44,  5.18it/s]

Reports:  41%|████      | 2937/7211 [12:11<13:35,  5.24it/s]

Reports:  41%|████      | 2938/7211 [12:11<13:25,  5.30it/s]

Reports:  41%|████      | 2939/7211 [12:11<13:42,  5.19it/s]

Reports:  41%|████      | 2940/7211 [12:11<13:43,  5.19it/s]

Reports:  41%|████      | 2941/7211 [12:11<14:07,  5.04it/s]

Reports:  41%|████      | 2942/7211 [12:12<13:55,  5.11it/s]

Reports:  41%|████      | 2943/7211 [12:12<13:41,  5.20it/s]

Reports:  41%|████      | 2944/7211 [12:12<13:53,  5.12it/s]

Reports:  41%|████      | 2945/7211 [12:12<13:59,  5.08it/s]

Reports:  41%|████      | 2946/7211 [12:13<20:17,  3.50it/s]

Reports:  41%|████      | 2947/7211 [12:13<18:41,  3.80it/s]

Reports:  41%|████      | 2948/7211 [12:13<17:37,  4.03it/s]

Reports:  41%|████      | 2949/7211 [12:13<16:18,  4.35it/s]

Reports:  41%|████      | 2950/7211 [12:13<15:31,  4.57it/s]

Reports:  41%|████      | 2951/7211 [12:14<14:54,  4.76it/s]

Reports:  41%|████      | 2952/7211 [12:14<14:36,  4.86it/s]

Reports:  41%|████      | 2953/7211 [12:14<15:02,  4.72it/s]

Reports:  41%|████      | 2954/7211 [12:14<15:05,  4.70it/s]

Reports:  41%|████      | 2955/7211 [12:14<14:43,  4.82it/s]

Reports:  41%|████      | 2956/7211 [12:15<14:19,  4.95it/s]

Reports:  41%|████      | 2957/7211 [12:15<13:57,  5.08it/s]

Reports:  41%|████      | 2958/7211 [12:15<13:47,  5.14it/s]

Reports:  41%|████      | 2959/7211 [12:15<13:40,  5.18it/s]

Reports:  41%|████      | 2960/7211 [12:15<13:47,  5.14it/s]

Reports:  41%|████      | 2961/7211 [12:16<13:59,  5.06it/s]

Reports:  41%|████      | 2962/7211 [12:16<14:12,  4.98it/s]

Reports:  41%|████      | 2963/7211 [12:16<14:16,  4.96it/s]

Reports:  41%|████      | 2964/7211 [12:16<13:57,  5.07it/s]

Reports:  41%|████      | 2965/7211 [12:16<14:08,  5.00it/s]

Reports:  41%|████      | 2966/7211 [12:17<14:04,  5.03it/s]

Reports:  41%|████      | 2967/7211 [12:17<14:30,  4.88it/s]

Reports:  41%|████      | 2968/7211 [12:17<14:11,  4.98it/s]

Reports:  41%|████      | 2969/7211 [12:17<14:18,  4.94it/s]

Reports:  41%|████      | 2970/7211 [12:18<19:28,  3.63it/s]

Reports:  41%|████      | 2971/7211 [12:18<17:48,  3.97it/s]

Reports:  41%|████      | 2972/7211 [12:18<16:45,  4.21it/s]

Reports:  41%|████      | 2973/7211 [12:18<15:47,  4.47it/s]

Reports:  41%|████      | 2974/7211 [12:18<15:17,  4.62it/s]

Reports:  41%|████▏     | 2975/7211 [12:19<14:50,  4.76it/s]

Reports:  41%|████▏     | 2976/7211 [12:19<14:25,  4.89it/s]

Reports:  41%|████▏     | 2977/7211 [12:19<14:16,  4.94it/s]

Reports:  41%|████▏     | 2978/7211 [12:19<14:14,  4.95it/s]

Reports:  41%|████▏     | 2979/7211 [12:19<14:16,  4.94it/s]

Reports:  41%|████▏     | 2980/7211 [12:20<13:53,  5.08it/s]

Reports:  41%|████▏     | 2981/7211 [12:20<14:17,  4.94it/s]

Reports:  41%|████▏     | 2982/7211 [12:20<14:01,  5.03it/s]

Reports:  41%|████▏     | 2983/7211 [12:20<14:12,  4.96it/s]

Reports:  41%|████▏     | 2984/7211 [12:20<14:14,  4.95it/s]

Reports:  41%|████▏     | 2985/7211 [12:21<13:59,  5.04it/s]

Reports:  41%|████▏     | 2986/7211 [12:21<13:43,  5.13it/s]

Reports:  41%|████▏     | 2987/7211 [12:21<13:25,  5.24it/s]

Reports:  41%|████▏     | 2988/7211 [12:21<13:51,  5.08it/s]

Reports:  41%|████▏     | 2989/7211 [12:21<14:03,  5.00it/s]

Reports:  41%|████▏     | 2990/7211 [12:22<13:51,  5.07it/s]

Reports:  41%|████▏     | 2991/7211 [12:22<13:42,  5.13it/s]

Reports:  41%|████▏     | 2992/7211 [12:22<13:48,  5.09it/s]

Reports:  42%|████▏     | 2993/7211 [12:22<13:58,  5.03it/s]

Reports:  42%|████▏     | 2994/7211 [12:22<13:57,  5.03it/s]

Reports:  42%|████▏     | 2995/7211 [12:23<14:04,  4.99it/s]

Reports:  42%|████▏     | 2996/7211 [12:23<13:52,  5.07it/s]

Reports:  42%|████▏     | 2997/7211 [12:23<13:47,  5.10it/s]

Reports:  42%|████▏     | 2998/7211 [12:23<13:37,  5.15it/s]

Reports:  42%|████▏     | 2999/7211 [12:23<13:30,  5.19it/s]

Reports:  42%|████▏     | 3000/7211 [12:24<16:41,  4.20it/s]

Reports:  42%|████▏     | 3001/7211 [12:24<15:29,  4.53it/s]

Reports:  42%|████▏     | 3002/7211 [12:24<14:58,  4.68it/s]

Reports:  42%|████▏     | 3003/7211 [12:24<14:38,  4.79it/s]

Reports:  42%|████▏     | 3004/7211 [12:25<18:47,  3.73it/s]

Reports:  42%|████▏     | 3005/7211 [12:25<17:09,  4.08it/s]

Reports:  42%|████▏     | 3006/7211 [12:25<16:07,  4.35it/s]

Reports:  42%|████▏     | 3007/7211 [12:25<15:12,  4.60it/s]

Reports:  42%|████▏     | 3008/7211 [12:25<14:38,  4.79it/s]

Reports:  42%|████▏     | 3009/7211 [12:26<17:54,  3.91it/s]

Reports:  42%|████▏     | 3010/7211 [12:26<16:30,  4.24it/s]

Reports:  42%|████▏     | 3011/7211 [12:26<15:54,  4.40it/s]

Reports:  42%|████▏     | 3012/7211 [12:26<15:24,  4.54it/s]

Reports:  42%|████▏     | 3013/7211 [12:27<14:50,  4.71it/s]

Reports:  42%|████▏     | 3014/7211 [12:27<14:16,  4.90it/s]

Reports:  42%|████▏     | 3015/7211 [12:27<14:07,  4.95it/s]

Reports:  42%|████▏     | 3016/7211 [12:27<13:49,  5.06it/s]

Reports:  42%|████▏     | 3017/7211 [12:27<13:41,  5.11it/s]

Reports:  42%|████▏     | 3018/7211 [12:28<13:46,  5.07it/s]

Reports:  42%|████▏     | 3019/7211 [12:28<13:53,  5.03it/s]

Reports:  42%|████▏     | 3020/7211 [12:28<13:45,  5.08it/s]

Reports:  42%|████▏     | 3021/7211 [12:28<13:32,  5.15it/s]

Reports:  42%|████▏     | 3022/7211 [12:28<13:41,  5.10it/s]

Reports:  42%|████▏     | 3023/7211 [12:29<13:26,  5.19it/s]

Reports:  42%|████▏     | 3024/7211 [12:29<13:24,  5.20it/s]

Reports:  42%|████▏     | 3025/7211 [12:29<13:36,  5.13it/s]

Reports:  42%|████▏     | 3026/7211 [12:29<13:32,  5.15it/s]

Reports:  42%|████▏     | 3027/7211 [12:29<13:37,  5.12it/s]

Reports:  42%|████▏     | 3028/7211 [12:30<13:47,  5.05it/s]

Reports:  42%|████▏     | 3029/7211 [12:30<13:33,  5.14it/s]

Reports:  42%|████▏     | 3030/7211 [12:30<13:25,  5.19it/s]

Reports:  42%|████▏     | 3031/7211 [12:30<13:38,  5.11it/s]

Reports:  42%|████▏     | 3032/7211 [12:30<13:20,  5.22it/s]

Reports:  42%|████▏     | 3033/7211 [12:30<13:32,  5.14it/s]

Reports:  42%|████▏     | 3034/7211 [12:31<13:18,  5.23it/s]

Reports:  42%|████▏     | 3035/7211 [12:31<13:04,  5.32it/s]

Reports:  42%|████▏     | 3036/7211 [12:31<13:02,  5.33it/s]

Reports:  42%|████▏     | 3037/7211 [12:31<13:02,  5.33it/s]

Reports:  42%|████▏     | 3038/7211 [12:31<13:14,  5.25it/s]

Reports:  42%|████▏     | 3039/7211 [12:32<13:14,  5.25it/s]

Reports:  42%|████▏     | 3040/7211 [12:32<13:12,  5.26it/s]

Reports:  42%|████▏     | 3041/7211 [12:32<13:36,  5.11it/s]

Reports:  42%|████▏     | 3042/7211 [12:32<13:48,  5.03it/s]

Reports:  42%|████▏     | 3043/7211 [12:32<14:12,  4.89it/s]

Reports:  42%|████▏     | 3044/7211 [12:33<13:50,  5.01it/s]

Reports:  42%|████▏     | 3045/7211 [12:33<14:02,  4.95it/s]

Reports:  42%|████▏     | 3046/7211 [12:33<13:54,  4.99it/s]

Reports:  42%|████▏     | 3047/7211 [12:33<13:43,  5.06it/s]

Reports:  42%|████▏     | 3048/7211 [12:33<13:48,  5.03it/s]

Reports:  42%|████▏     | 3049/7211 [12:34<15:22,  4.51it/s]

Reports:  42%|████▏     | 3050/7211 [12:34<14:49,  4.68it/s]

Reports:  42%|████▏     | 3051/7211 [12:34<14:18,  4.84it/s]

Reports:  42%|████▏     | 3052/7211 [12:34<14:08,  4.90it/s]

Reports:  42%|████▏     | 3053/7211 [12:34<13:49,  5.01it/s]

Reports:  42%|████▏     | 3054/7211 [12:35<13:32,  5.12it/s]

Reports:  42%|████▏     | 3055/7211 [12:35<13:46,  5.03it/s]

Reports:  42%|████▏     | 3056/7211 [12:35<13:43,  5.04it/s]

Reports:  42%|████▏     | 3057/7211 [12:35<13:35,  5.09it/s]

Reports:  42%|████▏     | 3058/7211 [12:35<13:47,  5.02it/s]

Reports:  42%|████▏     | 3059/7211 [12:36<14:00,  4.94it/s]

Reports:  42%|████▏     | 3060/7211 [12:36<13:40,  5.06it/s]

Reports:  42%|████▏     | 3061/7211 [12:36<13:35,  5.09it/s]

Reports:  42%|████▏     | 3062/7211 [12:36<13:34,  5.09it/s]

Reports:  42%|████▏     | 3063/7211 [12:36<13:37,  5.08it/s]

Reports:  42%|████▏     | 3064/7211 [12:37<13:24,  5.15it/s]

Reports:  43%|████▎     | 3065/7211 [12:37<13:26,  5.14it/s]

Reports:  43%|████▎     | 3066/7211 [12:37<13:17,  5.20it/s]

Reports:  43%|████▎     | 3067/7211 [12:37<13:27,  5.13it/s]

Reports:  43%|████▎     | 3068/7211 [12:37<13:22,  5.17it/s]

Reports:  43%|████▎     | 3069/7211 [12:38<13:23,  5.16it/s]

Reports:  43%|████▎     | 3070/7211 [12:38<13:27,  5.13it/s]

Reports:  43%|████▎     | 3071/7211 [12:38<13:36,  5.07it/s]

Reports:  43%|████▎     | 3072/7211 [12:38<13:28,  5.12it/s]

Reports:  43%|████▎     | 3073/7211 [12:38<13:24,  5.15it/s]

Reports:  43%|████▎     | 3074/7211 [12:39<13:11,  5.22it/s]

Reports:  43%|████▎     | 3075/7211 [12:39<13:16,  5.19it/s]

Reports:  43%|████▎     | 3076/7211 [12:39<13:13,  5.21it/s]

Reports:  43%|████▎     | 3077/7211 [12:39<13:23,  5.14it/s]

Reports:  43%|████▎     | 3078/7211 [12:39<13:13,  5.21it/s]

Reports:  43%|████▎     | 3079/7211 [12:40<13:12,  5.22it/s]

Reports:  43%|████▎     | 3080/7211 [12:40<13:21,  5.16it/s]

Reports:  43%|████▎     | 3081/7211 [12:40<13:03,  5.27it/s]

Reports:  43%|████▎     | 3082/7211 [12:40<12:52,  5.35it/s]

Reports:  43%|████▎     | 3083/7211 [12:40<12:57,  5.31it/s]

Reports:  43%|████▎     | 3084/7211 [12:40<12:47,  5.38it/s]

Reports:  43%|████▎     | 3085/7211 [12:41<13:16,  5.18it/s]

Reports:  43%|████▎     | 3086/7211 [12:41<13:53,  4.95it/s]

Reports:  43%|████▎     | 3087/7211 [12:41<13:36,  5.05it/s]

Reports:  43%|████▎     | 3088/7211 [12:41<13:18,  5.17it/s]

Reports:  43%|████▎     | 3089/7211 [12:41<13:44,  5.00it/s]

Reports:  43%|████▎     | 3090/7211 [12:42<13:25,  5.12it/s]

Reports:  43%|████▎     | 3091/7211 [12:42<13:09,  5.22it/s]

Reports:  43%|████▎     | 3092/7211 [12:42<13:20,  5.15it/s]

Reports:  43%|████▎     | 3093/7211 [12:42<13:07,  5.23it/s]

Reports:  43%|████▎     | 3094/7211 [12:42<13:29,  5.09it/s]

Reports:  43%|████▎     | 3095/7211 [12:43<13:19,  5.15it/s]

Reports:  43%|████▎     | 3096/7211 [12:43<13:26,  5.10it/s]

Reports:  43%|████▎     | 3097/7211 [12:43<13:33,  5.06it/s]

Reports:  43%|████▎     | 3098/7211 [12:43<13:20,  5.14it/s]

Reports:  43%|████▎     | 3099/7211 [12:43<13:15,  5.17it/s]

Reports:  43%|████▎     | 3100/7211 [12:44<12:56,  5.29it/s]

Reports:  43%|████▎     | 3101/7211 [12:44<13:01,  5.26it/s]

Reports:  43%|████▎     | 3102/7211 [12:44<13:11,  5.19it/s]

Reports:  43%|████▎     | 3103/7211 [12:44<13:24,  5.11it/s]

Reports:  43%|████▎     | 3104/7211 [12:44<13:03,  5.24it/s]

Reports:  43%|████▎     | 3105/7211 [12:45<13:02,  5.25it/s]

Reports:  43%|████▎     | 3106/7211 [12:45<12:56,  5.29it/s]

Reports:  43%|████▎     | 3107/7211 [12:45<13:07,  5.21it/s]

Reports:  43%|████▎     | 3108/7211 [12:45<13:00,  5.25it/s]

Reports:  43%|████▎     | 3109/7211 [12:45<12:53,  5.31it/s]

Reports:  43%|████▎     | 3110/7211 [12:45<12:48,  5.33it/s]

Reports:  43%|████▎     | 3111/7211 [12:46<12:54,  5.29it/s]

Reports:  43%|████▎     | 3112/7211 [12:46<13:02,  5.24it/s]

Reports:  43%|████▎     | 3113/7211 [12:46<12:53,  5.30it/s]

Reports:  43%|████▎     | 3114/7211 [12:46<12:57,  5.27it/s]

Reports:  43%|████▎     | 3115/7211 [12:46<12:50,  5.32it/s]

Reports:  43%|████▎     | 3116/7211 [12:47<12:46,  5.34it/s]

Reports:  43%|████▎     | 3117/7211 [12:47<12:48,  5.33it/s]

Reports:  43%|████▎     | 3118/7211 [12:47<12:51,  5.31it/s]

Reports:  43%|████▎     | 3119/7211 [12:47<12:42,  5.37it/s]

Reports:  43%|████▎     | 3120/7211 [12:47<12:54,  5.28it/s]

Reports:  43%|████▎     | 3121/7211 [12:48<13:00,  5.24it/s]

Reports:  43%|████▎     | 3122/7211 [12:48<12:54,  5.28it/s]

Reports:  43%|████▎     | 3123/7211 [12:48<12:57,  5.26it/s]

Reports:  43%|████▎     | 3124/7211 [12:48<13:10,  5.17it/s]

Reports:  43%|████▎     | 3125/7211 [12:48<13:04,  5.21it/s]

Reports:  43%|████▎     | 3126/7211 [12:49<12:52,  5.29it/s]

Reports:  43%|████▎     | 3127/7211 [12:49<12:51,  5.29it/s]

Reports:  43%|████▎     | 3128/7211 [12:49<12:39,  5.37it/s]

Reports:  43%|████▎     | 3129/7211 [12:49<12:59,  5.24it/s]

Reports:  43%|████▎     | 3130/7211 [12:49<13:05,  5.19it/s]

Reports:  43%|████▎     | 3131/7211 [12:49<13:19,  5.11it/s]

Reports:  43%|████▎     | 3132/7211 [12:50<13:20,  5.10it/s]

Reports:  43%|████▎     | 3133/7211 [12:50<13:00,  5.23it/s]

Reports:  43%|████▎     | 3134/7211 [12:50<12:53,  5.27it/s]

Reports:  43%|████▎     | 3135/7211 [12:50<13:30,  5.03it/s]

Reports:  43%|████▎     | 3136/7211 [12:50<13:17,  5.11it/s]

Reports:  44%|████▎     | 3137/7211 [12:51<13:00,  5.22it/s]

Reports:  44%|████▎     | 3138/7211 [12:51<13:03,  5.20it/s]

Reports:  44%|████▎     | 3139/7211 [12:51<13:07,  5.17it/s]

Reports:  44%|████▎     | 3140/7211 [12:51<13:03,  5.20it/s]

Reports:  44%|████▎     | 3141/7211 [12:51<13:20,  5.08it/s]

Reports:  44%|████▎     | 3142/7211 [12:52<13:09,  5.15it/s]

Reports:  44%|████▎     | 3143/7211 [12:52<12:53,  5.26it/s]

Reports:  44%|████▎     | 3144/7211 [12:52<12:45,  5.31it/s]

Reports:  44%|████▎     | 3145/7211 [12:52<12:54,  5.25it/s]

Reports:  44%|████▎     | 3146/7211 [12:52<12:55,  5.24it/s]

Reports:  44%|████▎     | 3147/7211 [12:53<12:58,  5.22it/s]

Reports:  44%|████▎     | 3148/7211 [12:53<12:55,  5.24it/s]

Reports:  44%|████▎     | 3149/7211 [12:53<12:51,  5.27it/s]

Reports:  44%|████▎     | 3150/7211 [12:53<12:45,  5.30it/s]

Reports:  44%|████▎     | 3151/7211 [12:53<15:24,  4.39it/s]

Reports:  44%|████▎     | 3152/7211 [12:54<14:48,  4.57it/s]

Reports:  44%|████▎     | 3153/7211 [12:54<14:46,  4.58it/s]

Reports:  44%|████▎     | 3154/7211 [12:54<17:52,  3.78it/s]

Reports:  44%|████▍     | 3155/7211 [12:54<16:28,  4.10it/s]

Reports:  44%|████▍     | 3156/7211 [12:55<15:29,  4.36it/s]

Reports:  44%|████▍     | 3157/7211 [12:55<14:39,  4.61it/s]

Reports:  44%|████▍     | 3158/7211 [12:55<14:20,  4.71it/s]

Reports:  44%|████▍     | 3159/7211 [12:55<13:51,  4.87it/s]

Reports:  44%|████▍     | 3160/7211 [12:55<13:49,  4.88it/s]

Reports:  44%|████▍     | 3161/7211 [12:56<13:26,  5.02it/s]

Reports:  44%|████▍     | 3162/7211 [12:56<13:29,  5.00it/s]

Reports:  44%|████▍     | 3163/7211 [12:56<13:26,  5.02it/s]

Reports:  44%|████▍     | 3164/7211 [12:56<13:23,  5.04it/s]

Reports:  44%|████▍     | 3165/7211 [12:56<13:02,  5.17it/s]

Reports:  44%|████▍     | 3166/7211 [12:57<13:06,  5.14it/s]

Reports:  44%|████▍     | 3167/7211 [12:57<13:07,  5.14it/s]

Reports:  44%|████▍     | 3168/7211 [12:57<13:11,  5.11it/s]

Reports:  44%|████▍     | 3169/7211 [12:57<13:13,  5.09it/s]

Reports:  44%|████▍     | 3170/7211 [12:57<13:02,  5.16it/s]

Reports:  44%|████▍     | 3171/7211 [12:58<13:00,  5.18it/s]

Reports:  44%|████▍     | 3172/7211 [12:58<12:45,  5.28it/s]

Reports:  44%|████▍     | 3173/7211 [12:58<17:51,  3.77it/s]

Reports:  44%|████▍     | 3174/7211 [12:58<16:40,  4.03it/s]

Reports:  44%|████▍     | 3175/7211 [12:59<15:26,  4.36it/s]

Reports:  44%|████▍     | 3176/7211 [12:59<14:39,  4.59it/s]

Reports:  44%|████▍     | 3177/7211 [12:59<19:06,  3.52it/s]

Reports:  44%|████▍     | 3178/7211 [12:59<17:14,  3.90it/s]

Reports:  44%|████▍     | 3179/7211 [13:00<16:12,  4.15it/s]

Reports:  44%|████▍     | 3180/7211 [13:00<15:21,  4.38it/s]

Reports:  44%|████▍     | 3181/7211 [13:00<15:01,  4.47it/s]

Reports:  44%|████▍     | 3182/7211 [13:00<14:26,  4.65it/s]

Reports:  44%|████▍     | 3183/7211 [13:00<13:43,  4.89it/s]

Reports:  44%|████▍     | 3184/7211 [13:01<13:33,  4.95it/s]

Reports:  44%|████▍     | 3185/7211 [13:01<13:38,  4.92it/s]

Reports:  44%|████▍     | 3186/7211 [13:01<13:23,  5.01it/s]

Reports:  44%|████▍     | 3187/7211 [13:01<13:20,  5.03it/s]

Reports:  44%|████▍     | 3188/7211 [13:01<13:31,  4.96it/s]

Reports:  44%|████▍     | 3189/7211 [13:02<13:21,  5.02it/s]

Reports:  44%|████▍     | 3190/7211 [13:02<13:08,  5.10it/s]

Reports:  44%|████▍     | 3191/7211 [13:02<12:58,  5.16it/s]

Reports:  44%|████▍     | 3192/7211 [13:02<13:11,  5.08it/s]

Reports:  44%|████▍     | 3193/7211 [13:02<13:13,  5.07it/s]

Reports:  44%|████▍     | 3194/7211 [13:03<13:23,  5.00it/s]

Reports:  44%|████▍     | 3195/7211 [13:03<13:08,  5.09it/s]

Reports:  44%|████▍     | 3196/7211 [13:03<13:11,  5.07it/s]

Reports:  44%|████▍     | 3197/7211 [13:03<13:07,  5.10it/s]

Reports:  44%|████▍     | 3198/7211 [13:03<12:57,  5.16it/s]

Reports:  44%|████▍     | 3199/7211 [13:04<13:11,  5.07it/s]

Reports:  44%|████▍     | 3200/7211 [13:04<13:04,  5.11it/s]

Reports:  44%|████▍     | 3201/7211 [13:04<16:54,  3.95it/s]

Reports:  44%|████▍     | 3202/7211 [13:04<15:33,  4.30it/s]

Reports:  44%|████▍     | 3203/7211 [13:04<14:51,  4.50it/s]

Reports:  44%|████▍     | 3204/7211 [13:05<15:55,  4.19it/s]

Reports:  44%|████▍     | 3205/7211 [13:05<17:37,  3.79it/s]

Reports:  44%|████▍     | 3206/7211 [13:05<16:34,  4.03it/s]

Reports:  44%|████▍     | 3207/7211 [13:06<15:36,  4.27it/s]

Reports:  44%|████▍     | 3208/7211 [13:06<14:41,  4.54it/s]

Reports:  45%|████▍     | 3209/7211 [13:06<14:26,  4.62it/s]

Reports:  45%|████▍     | 3210/7211 [13:06<14:03,  4.74it/s]

Reports:  45%|████▍     | 3211/7211 [13:06<13:51,  4.81it/s]

Reports:  45%|████▍     | 3212/7211 [13:07<13:46,  4.84it/s]

Reports:  45%|████▍     | 3213/7211 [13:07<13:30,  4.93it/s]

Reports:  45%|████▍     | 3214/7211 [13:07<13:22,  4.98it/s]

Reports:  45%|████▍     | 3215/7211 [13:07<13:08,  5.07it/s]

Reports:  45%|████▍     | 3216/7211 [13:07<13:17,  5.01it/s]

Reports:  45%|████▍     | 3217/7211 [13:07<13:05,  5.08it/s]

Reports:  45%|████▍     | 3218/7211 [13:08<12:54,  5.16it/s]

Reports:  45%|████▍     | 3219/7211 [13:08<13:01,  5.11it/s]

Reports:  45%|████▍     | 3220/7211 [13:08<12:50,  5.18it/s]

Reports:  45%|████▍     | 3221/7211 [13:08<13:03,  5.09it/s]

Reports:  45%|████▍     | 3222/7211 [13:08<12:59,  5.12it/s]

Reports:  45%|████▍     | 3223/7211 [13:09<13:07,  5.06it/s]

Reports:  45%|████▍     | 3224/7211 [13:09<13:06,  5.07it/s]

Reports:  45%|████▍     | 3225/7211 [13:09<12:48,  5.19it/s]

Reports:  45%|████▍     | 3226/7211 [13:09<13:11,  5.04it/s]

Reports:  45%|████▍     | 3227/7211 [13:09<13:25,  4.95it/s]

Reports:  45%|████▍     | 3228/7211 [13:10<13:03,  5.08it/s]

Reports:  45%|████▍     | 3229/7211 [13:10<12:54,  5.14it/s]

Reports:  45%|████▍     | 3230/7211 [13:10<13:08,  5.05it/s]

Reports:  45%|████▍     | 3231/7211 [13:10<13:02,  5.09it/s]

Reports:  45%|████▍     | 3232/7211 [13:10<13:00,  5.10it/s]

Reports:  45%|████▍     | 3233/7211 [13:11<12:50,  5.16it/s]

Reports:  45%|████▍     | 3234/7211 [13:11<12:50,  5.16it/s]

Reports:  45%|████▍     | 3235/7211 [13:11<12:40,  5.23it/s]

Reports:  45%|████▍     | 3236/7211 [13:11<12:43,  5.21it/s]

Reports:  45%|████▍     | 3237/7211 [13:11<12:33,  5.28it/s]

Reports:  45%|████▍     | 3238/7211 [13:12<12:55,  5.12it/s]

Reports:  45%|████▍     | 3239/7211 [13:12<13:06,  5.05it/s]

Reports:  45%|████▍     | 3240/7211 [13:12<13:16,  4.99it/s]

Reports:  45%|████▍     | 3241/7211 [13:12<13:04,  5.06it/s]

Reports:  45%|████▍     | 3242/7211 [13:12<12:55,  5.12it/s]

Reports:  45%|████▍     | 3243/7211 [13:13<12:56,  5.11it/s]

Reports:  45%|████▍     | 3244/7211 [13:13<12:52,  5.14it/s]

Reports:  45%|████▌     | 3245/7211 [13:13<13:05,  5.05it/s]

Reports:  45%|████▌     | 3246/7211 [13:13<12:59,  5.08it/s]

Reports:  45%|████▌     | 3247/7211 [13:13<12:45,  5.18it/s]

Reports:  45%|████▌     | 3248/7211 [13:14<12:52,  5.13it/s]

Reports:  45%|████▌     | 3249/7211 [13:14<12:46,  5.17it/s]

Reports:  45%|████▌     | 3250/7211 [13:14<12:41,  5.20it/s]

Reports:  45%|████▌     | 3251/7211 [13:14<12:49,  5.15it/s]

Reports:  45%|████▌     | 3252/7211 [13:14<12:42,  5.19it/s]

Reports:  45%|████▌     | 3253/7211 [13:14<12:30,  5.28it/s]

Reports:  45%|████▌     | 3254/7211 [13:15<12:39,  5.21it/s]

Reports:  45%|████▌     | 3255/7211 [13:15<12:29,  5.28it/s]

Reports:  45%|████▌     | 3256/7211 [13:15<12:37,  5.22it/s]

Reports:  45%|████▌     | 3257/7211 [13:15<12:53,  5.11it/s]

Reports:  45%|████▌     | 3258/7211 [13:15<12:37,  5.22it/s]

Reports:  45%|████▌     | 3259/7211 [13:16<12:39,  5.20it/s]

Reports:  45%|████▌     | 3260/7211 [13:16<12:45,  5.16it/s]

Reports:  45%|████▌     | 3261/7211 [13:16<12:41,  5.19it/s]

Reports:  45%|████▌     | 3262/7211 [13:16<12:33,  5.24it/s]

Reports:  45%|████▌     | 3263/7211 [13:16<12:49,  5.13it/s]

Reports:  45%|████▌     | 3264/7211 [13:17<12:36,  5.22it/s]

Reports:  45%|████▌     | 3265/7211 [13:17<12:39,  5.20it/s]

Reports:  45%|████▌     | 3266/7211 [13:17<13:16,  4.96it/s]

Reports:  45%|████▌     | 3267/7211 [13:17<13:03,  5.03it/s]

Reports:  45%|████▌     | 3268/7211 [13:17<13:34,  4.84it/s]

Reports:  45%|████▌     | 3269/7211 [13:18<13:24,  4.90it/s]

Reports:  45%|████▌     | 3270/7211 [13:18<13:10,  4.98it/s]

Reports:  45%|████▌     | 3271/7211 [13:18<13:14,  4.96it/s]

Reports:  45%|████▌     | 3272/7211 [13:18<13:13,  4.96it/s]

Reports:  45%|████▌     | 3273/7211 [13:18<13:12,  4.97it/s]

Reports:  45%|████▌     | 3274/7211 [13:19<14:19,  4.58it/s]

Reports:  45%|████▌     | 3275/7211 [13:19<14:06,  4.65it/s]

Reports:  45%|████▌     | 3276/7211 [13:19<13:52,  4.73it/s]

Reports:  45%|████▌     | 3277/7211 [13:19<13:20,  4.91it/s]

Reports:  45%|████▌     | 3278/7211 [13:19<13:23,  4.89it/s]

Reports:  45%|████▌     | 3279/7211 [13:20<13:21,  4.91it/s]

Reports:  45%|████▌     | 3280/7211 [13:20<13:21,  4.91it/s]

Reports:  45%|████▌     | 3281/7211 [13:20<13:05,  5.00it/s]

Reports:  46%|████▌     | 3282/7211 [13:20<12:52,  5.09it/s]

Reports:  46%|████▌     | 3283/7211 [13:20<13:01,  5.02it/s]

Reports:  46%|████▌     | 3284/7211 [13:21<13:06,  5.00it/s]

Reports:  46%|████▌     | 3285/7211 [13:21<13:05,  5.00it/s]

Reports:  46%|████▌     | 3286/7211 [13:21<12:54,  5.07it/s]

Reports:  46%|████▌     | 3287/7211 [13:21<13:06,  4.99it/s]

Reports:  46%|████▌     | 3288/7211 [13:21<12:46,  5.12it/s]

Reports:  46%|████▌     | 3289/7211 [13:22<12:34,  5.20it/s]

Reports:  46%|████▌     | 3290/7211 [13:22<12:24,  5.27it/s]

Reports:  46%|████▌     | 3291/7211 [13:22<12:33,  5.20it/s]

Reports:  46%|████▌     | 3292/7211 [13:22<12:34,  5.19it/s]

Reports:  46%|████▌     | 3293/7211 [13:22<12:41,  5.14it/s]

Reports:  46%|████▌     | 3294/7211 [13:23<12:26,  5.25it/s]

Reports:  46%|████▌     | 3295/7211 [13:23<12:30,  5.22it/s]

Reports:  46%|████▌     | 3296/7211 [13:23<12:21,  5.28it/s]

Reports:  46%|████▌     | 3297/7211 [13:23<12:12,  5.35it/s]

Reports:  46%|████▌     | 3298/7211 [13:23<12:18,  5.30it/s]

Reports:  46%|████▌     | 3299/7211 [13:24<12:31,  5.20it/s]

Reports:  46%|████▌     | 3300/7211 [13:24<12:25,  5.24it/s]

Reports:  46%|████▌     | 3301/7211 [13:24<12:21,  5.27it/s]

Reports:  46%|████▌     | 3302/7211 [13:24<13:35,  4.79it/s]

Reports:  46%|████▌     | 3303/7211 [13:24<13:08,  4.96it/s]

Reports:  46%|████▌     | 3304/7211 [13:25<13:14,  4.91it/s]

Reports:  46%|████▌     | 3305/7211 [13:25<12:53,  5.05it/s]

Reports:  46%|████▌     | 3306/7211 [13:25<12:51,  5.06it/s]

Reports:  46%|████▌     | 3307/7211 [13:25<12:41,  5.12it/s]

Reports:  46%|████▌     | 3308/7211 [13:25<12:40,  5.13it/s]

Reports:  46%|████▌     | 3309/7211 [13:26<13:23,  4.86it/s]

Reports:  46%|████▌     | 3310/7211 [13:26<13:21,  4.87it/s]

Reports:  46%|████▌     | 3311/7211 [13:26<12:58,  5.01it/s]

Reports:  46%|████▌     | 3312/7211 [13:26<13:00,  4.99it/s]

Reports:  46%|████▌     | 3313/7211 [13:26<12:57,  5.01it/s]

Reports:  46%|████▌     | 3314/7211 [13:27<12:55,  5.02it/s]

Reports:  46%|████▌     | 3315/7211 [13:27<12:45,  5.09it/s]

Reports:  46%|████▌     | 3316/7211 [13:27<12:42,  5.11it/s]

Reports:  46%|████▌     | 3317/7211 [13:27<12:52,  5.04it/s]

Reports:  46%|████▌     | 3318/7211 [13:27<12:44,  5.09it/s]

Reports:  46%|████▌     | 3319/7211 [13:28<12:37,  5.14it/s]

Reports:  46%|████▌     | 3320/7211 [13:28<12:39,  5.13it/s]

Reports:  46%|████▌     | 3321/7211 [13:28<13:02,  4.97it/s]

Reports:  46%|████▌     | 3322/7211 [13:28<12:53,  5.03it/s]

Reports:  46%|████▌     | 3323/7211 [13:28<12:55,  5.01it/s]

Reports:  46%|████▌     | 3324/7211 [13:29<12:59,  4.98it/s]

Reports:  46%|████▌     | 3325/7211 [13:29<12:58,  4.99it/s]

Reports:  46%|████▌     | 3326/7211 [13:29<12:50,  5.04it/s]

Reports:  46%|████▌     | 3327/7211 [13:29<12:38,  5.12it/s]

Reports:  46%|████▌     | 3328/7211 [13:29<12:36,  5.14it/s]

Reports:  46%|████▌     | 3329/7211 [13:30<12:42,  5.09it/s]

Reports:  46%|████▌     | 3330/7211 [13:30<12:39,  5.11it/s]

Reports:  46%|████▌     | 3331/7211 [13:30<13:23,  4.83it/s]

Reports:  46%|████▌     | 3332/7211 [13:30<13:09,  4.91it/s]

Reports:  46%|████▌     | 3333/7211 [13:30<12:45,  5.07it/s]

Reports:  46%|████▌     | 3334/7211 [13:31<12:56,  4.99it/s]

Reports:  46%|████▌     | 3335/7211 [13:31<12:39,  5.10it/s]

Reports:  46%|████▋     | 3336/7211 [13:31<12:33,  5.14it/s]

Reports:  46%|████▋     | 3337/7211 [13:31<12:33,  5.14it/s]

Reports:  46%|████▋     | 3338/7211 [13:31<12:33,  5.14it/s]

Reports:  46%|████▋     | 3339/7211 [13:31<12:20,  5.23it/s]

Reports:  46%|████▋     | 3340/7211 [13:32<12:28,  5.17it/s]

Reports:  46%|████▋     | 3341/7211 [13:32<12:17,  5.25it/s]

Reports:  46%|████▋     | 3342/7211 [13:32<12:16,  5.25it/s]

Reports:  46%|████▋     | 3343/7211 [13:32<12:21,  5.22it/s]

Reports:  46%|████▋     | 3344/7211 [13:32<12:25,  5.19it/s]

Reports:  46%|████▋     | 3345/7211 [13:33<12:23,  5.20it/s]

Reports:  46%|████▋     | 3346/7211 [13:33<12:32,  5.14it/s]

Reports:  46%|████▋     | 3347/7211 [13:33<12:30,  5.15it/s]

Reports:  46%|████▋     | 3348/7211 [13:33<12:45,  5.04it/s]

Reports:  46%|████▋     | 3349/7211 [13:33<12:33,  5.13it/s]

Reports:  46%|████▋     | 3350/7211 [13:34<12:36,  5.10it/s]

Reports:  46%|████▋     | 3351/7211 [13:34<12:49,  5.02it/s]

Reports:  46%|████▋     | 3352/7211 [13:34<12:42,  5.06it/s]

Reports:  46%|████▋     | 3353/7211 [13:34<12:34,  5.11it/s]

Reports:  47%|████▋     | 3354/7211 [13:34<12:31,  5.13it/s]

Reports:  47%|████▋     | 3355/7211 [13:35<12:23,  5.19it/s]

Reports:  47%|████▋     | 3356/7211 [13:35<12:17,  5.23it/s]

Reports:  47%|████▋     | 3357/7211 [13:35<12:22,  5.19it/s]

Reports:  47%|████▋     | 3358/7211 [13:35<12:13,  5.26it/s]

Reports:  47%|████▋     | 3359/7211 [13:35<12:20,  5.20it/s]

Reports:  47%|████▋     | 3360/7211 [13:36<12:29,  5.14it/s]

Reports:  47%|████▋     | 3361/7211 [13:36<12:39,  5.07it/s]

Reports:  47%|████▋     | 3362/7211 [13:36<12:37,  5.08it/s]

Reports:  47%|████▋     | 3363/7211 [13:36<12:42,  5.05it/s]

Reports:  47%|████▋     | 3364/7211 [13:36<12:38,  5.07it/s]

Reports:  47%|████▋     | 3365/7211 [13:37<12:48,  5.01it/s]

Reports:  47%|████▋     | 3366/7211 [13:37<12:37,  5.08it/s]

Reports:  47%|████▋     | 3367/7211 [13:37<12:38,  5.07it/s]

Reports:  47%|████▋     | 3368/7211 [13:37<12:28,  5.14it/s]

Reports:  47%|████▋     | 3369/7211 [13:37<12:13,  5.24it/s]

Reports:  47%|████▋     | 3370/7211 [13:38<12:01,  5.32it/s]

Reports:  47%|████▋     | 3371/7211 [13:38<12:05,  5.29it/s]

Reports:  47%|████▋     | 3372/7211 [13:38<12:21,  5.18it/s]

Reports:  47%|████▋     | 3373/7211 [13:38<12:07,  5.28it/s]

Reports:  47%|████▋     | 3374/7211 [13:38<12:28,  5.13it/s]

Reports:  47%|████▋     | 3375/7211 [13:38<12:29,  5.12it/s]

Reports:  47%|████▋     | 3376/7211 [13:39<12:30,  5.11it/s]

Reports:  47%|████▋     | 3377/7211 [13:39<12:45,  5.01it/s]

Reports:  47%|████▋     | 3378/7211 [13:39<12:27,  5.13it/s]

Reports:  47%|████▋     | 3379/7211 [13:39<12:33,  5.09it/s]

Reports:  47%|████▋     | 3380/7211 [13:39<12:35,  5.07it/s]

Reports:  47%|████▋     | 3381/7211 [13:40<12:27,  5.12it/s]

Reports:  47%|████▋     | 3382/7211 [13:40<12:21,  5.17it/s]

Reports:  47%|████▋     | 3383/7211 [13:40<12:09,  5.25it/s]

Reports:  47%|████▋     | 3384/7211 [13:40<12:01,  5.31it/s]

Reports:  47%|████▋     | 3385/7211 [13:40<12:24,  5.14it/s]

Reports:  47%|████▋     | 3386/7211 [13:41<12:32,  5.09it/s]

Reports:  47%|████▋     | 3387/7211 [13:41<12:25,  5.13it/s]

Reports:  47%|████▋     | 3388/7211 [13:41<12:34,  5.06it/s]

Reports:  47%|████▋     | 3389/7211 [13:41<12:18,  5.17it/s]

Reports:  47%|████▋     | 3390/7211 [13:41<12:08,  5.25it/s]

Reports:  47%|████▋     | 3391/7211 [13:42<12:17,  5.18it/s]

Reports:  47%|████▋     | 3392/7211 [13:42<12:07,  5.25it/s]

Reports:  47%|████▋     | 3393/7211 [13:42<12:00,  5.30it/s]

Reports:  47%|████▋     | 3394/7211 [13:42<12:18,  5.17it/s]

Reports:  47%|████▋     | 3395/7211 [13:42<12:36,  5.05it/s]

Reports:  47%|████▋     | 3396/7211 [13:43<12:27,  5.10it/s]

Reports:  47%|████▋     | 3397/7211 [13:43<12:10,  5.22it/s]

Reports:  47%|████▋     | 3398/7211 [13:43<12:26,  5.11it/s]

Reports:  47%|████▋     | 3399/7211 [13:43<12:17,  5.17it/s]

Reports:  47%|████▋     | 3400/7211 [13:43<12:07,  5.24it/s]

Reports:  47%|████▋     | 3401/7211 [13:44<12:25,  5.11it/s]

Reports:  47%|████▋     | 3402/7211 [13:44<12:17,  5.16it/s]

Reports:  47%|████▋     | 3403/7211 [13:44<12:09,  5.22it/s]

Reports:  47%|████▋     | 3404/7211 [13:44<12:05,  5.25it/s]

Reports:  47%|████▋     | 3405/7211 [13:44<12:16,  5.17it/s]

Reports:  47%|████▋     | 3406/7211 [13:44<12:10,  5.21it/s]

Reports:  47%|████▋     | 3407/7211 [13:45<12:13,  5.18it/s]

Reports:  47%|████▋     | 3408/7211 [13:45<12:09,  5.21it/s]

Reports:  47%|████▋     | 3409/7211 [13:45<12:12,  5.19it/s]

Reports:  47%|████▋     | 3410/7211 [13:45<12:04,  5.24it/s]

Reports:  47%|████▋     | 3411/7211 [13:45<12:02,  5.26it/s]

Reports:  47%|████▋     | 3412/7211 [13:46<11:56,  5.30it/s]

Reports:  47%|████▋     | 3413/7211 [13:46<11:56,  5.30it/s]

Reports:  47%|████▋     | 3414/7211 [13:46<11:47,  5.37it/s]

Reports:  47%|████▋     | 3415/7211 [13:46<11:50,  5.34it/s]

Reports:  47%|████▋     | 3416/7211 [13:46<11:51,  5.33it/s]

Reports:  47%|████▋     | 3417/7211 [13:47<12:01,  5.26it/s]

Reports:  47%|████▋     | 3418/7211 [13:47<12:07,  5.22it/s]

Reports:  47%|████▋     | 3419/7211 [13:47<11:56,  5.29it/s]

Reports:  47%|████▋     | 3420/7211 [13:47<12:07,  5.21it/s]

Reports:  47%|████▋     | 3421/7211 [13:47<12:12,  5.17it/s]

Reports:  47%|████▋     | 3422/7211 [13:48<12:32,  5.04it/s]

Reports:  47%|████▋     | 3423/7211 [13:48<12:36,  5.01it/s]

Reports:  47%|████▋     | 3424/7211 [13:48<12:31,  5.04it/s]

Reports:  47%|████▋     | 3425/7211 [13:48<12:23,  5.09it/s]

Reports:  48%|████▊     | 3426/7211 [13:48<12:27,  5.06it/s]

Reports:  48%|████▊     | 3427/7211 [13:49<12:28,  5.05it/s]

Reports:  48%|████▊     | 3428/7211 [13:49<12:36,  5.00it/s]

Reports:  48%|████▊     | 3429/7211 [13:49<12:34,  5.01it/s]

Reports:  48%|████▊     | 3430/7211 [13:49<12:30,  5.04it/s]

Reports:  48%|████▊     | 3431/7211 [13:49<12:26,  5.06it/s]

Reports:  48%|████▊     | 3432/7211 [13:50<12:38,  4.98it/s]

Reports:  48%|████▊     | 3433/7211 [13:50<12:49,  4.91it/s]

Reports:  48%|████▊     | 3434/7211 [13:50<12:45,  4.93it/s]

Reports:  48%|████▊     | 3435/7211 [13:50<14:23,  4.37it/s]

Reports:  48%|████▊     | 3436/7211 [13:50<14:12,  4.43it/s]

Reports:  48%|████▊     | 3437/7211 [13:51<13:43,  4.58it/s]

Reports:  48%|████▊     | 3438/7211 [13:51<13:14,  4.75it/s]

Reports:  48%|████▊     | 3439/7211 [13:51<12:49,  4.90it/s]

Reports:  48%|████▊     | 3440/7211 [13:51<12:49,  4.90it/s]

Reports:  48%|████▊     | 3441/7211 [13:51<12:40,  4.96it/s]

Reports:  48%|████▊     | 3442/7211 [13:52<12:32,  5.01it/s]

Reports:  48%|████▊     | 3443/7211 [13:52<12:20,  5.09it/s]

Reports:  48%|████▊     | 3444/7211 [13:52<12:28,  5.03it/s]

Reports:  48%|████▊     | 3445/7211 [13:52<12:43,  4.93it/s]

Reports:  48%|████▊     | 3446/7211 [13:52<12:47,  4.91it/s]

Reports:  48%|████▊     | 3447/7211 [13:53<12:41,  4.94it/s]

Reports:  48%|████▊     | 3448/7211 [13:53<12:33,  5.00it/s]

Reports:  48%|████▊     | 3449/7211 [13:53<12:21,  5.07it/s]

Reports:  48%|████▊     | 3450/7211 [13:53<12:27,  5.03it/s]

Reports:  48%|████▊     | 3451/7211 [13:53<12:25,  5.04it/s]

Reports:  48%|████▊     | 3452/7211 [13:54<12:20,  5.08it/s]

Reports:  48%|████▊     | 3453/7211 [13:54<12:19,  5.08it/s]

Reports:  48%|████▊     | 3454/7211 [13:54<12:10,  5.15it/s]

Reports:  48%|████▊     | 3455/7211 [13:54<12:11,  5.13it/s]

Reports:  48%|████▊     | 3456/7211 [13:54<12:25,  5.04it/s]

Reports:  48%|████▊     | 3457/7211 [13:55<12:07,  5.16it/s]

Reports:  48%|████▊     | 3458/7211 [13:55<12:23,  5.05it/s]

Reports:  48%|████▊     | 3459/7211 [13:55<12:15,  5.10it/s]

Reports:  48%|████▊     | 3460/7211 [13:55<12:08,  5.15it/s]

Reports:  48%|████▊     | 3461/7211 [13:55<12:08,  5.15it/s]

Reports:  48%|████▊     | 3462/7211 [13:56<12:16,  5.09it/s]

Reports:  48%|████▊     | 3463/7211 [13:56<12:22,  5.05it/s]

Reports:  48%|████▊     | 3464/7211 [13:56<12:14,  5.10it/s]

Reports:  48%|████▊     | 3465/7211 [13:56<12:10,  5.13it/s]

Reports:  48%|████▊     | 3466/7211 [13:56<12:06,  5.16it/s]

Reports:  48%|████▊     | 3467/7211 [13:57<12:22,  5.04it/s]

Reports:  48%|████▊     | 3468/7211 [13:57<12:26,  5.01it/s]

Reports:  48%|████▊     | 3469/7211 [13:57<12:34,  4.96it/s]

Reports:  48%|████▊     | 3470/7211 [13:57<12:53,  4.84it/s]

Reports:  48%|████▊     | 3471/7211 [13:57<12:50,  4.85it/s]

Reports:  48%|████▊     | 3472/7211 [13:58<12:28,  5.00it/s]

Reports:  48%|████▊     | 3473/7211 [13:58<12:27,  5.00it/s]

Reports:  48%|████▊     | 3474/7211 [13:58<12:14,  5.09it/s]

Reports:  48%|████▊     | 3475/7211 [13:58<12:30,  4.98it/s]

Reports:  48%|████▊     | 3476/7211 [13:58<12:14,  5.08it/s]

Reports:  48%|████▊     | 3477/7211 [13:59<12:05,  5.15it/s]

Reports:  48%|████▊     | 3478/7211 [13:59<12:01,  5.17it/s]

Reports:  48%|████▊     | 3479/7211 [13:59<12:11,  5.10it/s]

Reports:  48%|████▊     | 3480/7211 [13:59<12:23,  5.02it/s]

Reports:  48%|████▊     | 3481/7211 [13:59<12:08,  5.12it/s]

Reports:  48%|████▊     | 3482/7211 [14:00<12:17,  5.06it/s]

Reports:  48%|████▊     | 3483/7211 [14:00<12:19,  5.04it/s]

Reports:  48%|████▊     | 3484/7211 [14:00<12:16,  5.06it/s]

Reports:  48%|████▊     | 3485/7211 [14:00<12:12,  5.08it/s]

Reports:  48%|████▊     | 3486/7211 [14:00<12:19,  5.04it/s]

Reports:  48%|████▊     | 3487/7211 [14:01<12:18,  5.05it/s]

Reports:  48%|████▊     | 3488/7211 [14:01<12:23,  5.01it/s]

Reports:  48%|████▊     | 3489/7211 [14:01<12:15,  5.06it/s]

Reports:  48%|████▊     | 3490/7211 [14:01<12:12,  5.08it/s]

Reports:  48%|████▊     | 3491/7211 [14:01<12:06,  5.12it/s]

Reports:  48%|████▊     | 3492/7211 [14:02<11:52,  5.22it/s]

Reports:  48%|████▊     | 3493/7211 [14:02<11:53,  5.21it/s]

Reports:  48%|████▊     | 3494/7211 [14:02<12:06,  5.12it/s]

Reports:  48%|████▊     | 3495/7211 [14:02<12:15,  5.05it/s]

Reports:  48%|████▊     | 3496/7211 [14:02<12:11,  5.08it/s]

Reports:  48%|████▊     | 3497/7211 [14:03<12:07,  5.11it/s]

Reports:  49%|████▊     | 3498/7211 [14:03<12:17,  5.03it/s]

Reports:  49%|████▊     | 3499/7211 [14:03<13:00,  4.76it/s]

Reports:  49%|████▊     | 3500/7211 [14:03<12:42,  4.86it/s]

Reports:  49%|████▊     | 3501/7211 [14:03<12:22,  5.00it/s]

Reports:  49%|████▊     | 3502/7211 [14:04<12:27,  4.96it/s]

Reports:  49%|████▊     | 3503/7211 [14:04<12:33,  4.92it/s]

Reports:  49%|████▊     | 3504/7211 [14:04<12:32,  4.93it/s]

Reports:  49%|████▊     | 3505/7211 [14:04<12:22,  4.99it/s]

Reports:  49%|████▊     | 3506/7211 [14:04<12:37,  4.89it/s]

Reports:  49%|████▊     | 3507/7211 [14:05<12:37,  4.89it/s]

Reports:  49%|████▊     | 3508/7211 [14:05<12:35,  4.90it/s]

Reports:  49%|████▊     | 3509/7211 [14:05<12:24,  4.97it/s]

Reports:  49%|████▊     | 3510/7211 [14:05<12:34,  4.91it/s]

Reports:  49%|████▊     | 3511/7211 [14:05<12:29,  4.94it/s]

Reports:  49%|████▊     | 3512/7211 [14:06<12:21,  4.99it/s]

Reports:  49%|████▊     | 3513/7211 [14:06<12:09,  5.07it/s]

Reports:  49%|████▊     | 3514/7211 [14:06<12:06,  5.09it/s]

Reports:  49%|████▊     | 3515/7211 [14:06<12:25,  4.96it/s]

Reports:  49%|████▉     | 3516/7211 [14:06<12:25,  4.96it/s]

Reports:  49%|████▉     | 3517/7211 [14:07<12:30,  4.92it/s]

Reports:  49%|████▉     | 3518/7211 [14:07<12:17,  5.01it/s]

Reports:  49%|████▉     | 3519/7211 [14:07<12:26,  4.95it/s]

Reports:  49%|████▉     | 3520/7211 [14:07<12:14,  5.02it/s]

Reports:  49%|████▉     | 3521/7211 [14:07<12:02,  5.10it/s]

Reports:  49%|████▉     | 3522/7211 [14:08<11:55,  5.16it/s]

Reports:  49%|████▉     | 3523/7211 [14:08<11:45,  5.23it/s]

Reports:  49%|████▉     | 3524/7211 [14:08<11:58,  5.13it/s]

Reports:  49%|████▉     | 3525/7211 [14:08<11:54,  5.16it/s]

Reports:  49%|████▉     | 3526/7211 [14:08<11:55,  5.15it/s]

Reports:  49%|████▉     | 3527/7211 [14:09<12:05,  5.08it/s]

Reports:  49%|████▉     | 3528/7211 [14:09<11:51,  5.17it/s]

Reports:  49%|████▉     | 3529/7211 [14:09<11:48,  5.20it/s]

Reports:  49%|████▉     | 3530/7211 [14:09<11:41,  5.25it/s]

Reports:  49%|████▉     | 3531/7211 [14:09<11:46,  5.21it/s]

Reports:  49%|████▉     | 3532/7211 [14:10<13:26,  4.56it/s]

Reports:  49%|████▉     | 3533/7211 [14:10<14:21,  4.27it/s]

Reports:  49%|████▉     | 3534/7211 [14:10<14:45,  4.15it/s]

Reports:  49%|████▉     | 3535/7211 [14:10<14:38,  4.19it/s]

Reports:  49%|████▉     | 3536/7211 [14:11<14:24,  4.25it/s]

Reports:  49%|████▉     | 3537/7211 [14:11<13:43,  4.46it/s]

Reports:  49%|████▉     | 3538/7211 [14:11<13:06,  4.67it/s]

Reports:  49%|████▉     | 3539/7211 [14:11<12:39,  4.83it/s]

Reports:  49%|████▉     | 3540/7211 [14:11<12:21,  4.95it/s]

Reports:  49%|████▉     | 3541/7211 [14:12<12:17,  4.98it/s]

Reports:  49%|████▉     | 3542/7211 [14:12<12:07,  5.04it/s]

Reports:  49%|████▉     | 3543/7211 [14:12<11:57,  5.11it/s]

Reports:  49%|████▉     | 3544/7211 [14:12<11:52,  5.15it/s]

Reports:  49%|████▉     | 3545/7211 [14:12<11:50,  5.16it/s]

Reports:  49%|████▉     | 3546/7211 [14:12<11:49,  5.17it/s]

Reports:  49%|████▉     | 3547/7211 [14:13<12:10,  5.02it/s]

Reports:  49%|████▉     | 3548/7211 [14:13<12:02,  5.07it/s]

Reports:  49%|████▉     | 3549/7211 [14:13<11:49,  5.16it/s]

Reports:  49%|████▉     | 3550/7211 [14:13<11:50,  5.15it/s]

Reports:  49%|████▉     | 3551/7211 [14:13<12:07,  5.03it/s]

Reports:  49%|████▉     | 3552/7211 [14:14<11:52,  5.14it/s]

Reports:  49%|████▉     | 3553/7211 [14:14<11:56,  5.10it/s]

Reports:  49%|████▉     | 3554/7211 [14:14<12:01,  5.07it/s]

Reports:  49%|████▉     | 3555/7211 [14:14<11:59,  5.08it/s]

Reports:  49%|████▉     | 3556/7211 [14:14<11:59,  5.08it/s]

Reports:  49%|████▉     | 3557/7211 [14:15<12:13,  4.98it/s]

Reports:  49%|████▉     | 3558/7211 [14:15<12:03,  5.05it/s]

Reports:  49%|████▉     | 3559/7211 [14:15<11:55,  5.11it/s]

Reports:  49%|████▉     | 3560/7211 [14:15<11:50,  5.14it/s]

Reports:  49%|████▉     | 3561/7211 [14:15<12:12,  4.98it/s]

Reports:  49%|████▉     | 3562/7211 [14:16<12:15,  4.96it/s]

Reports:  49%|████▉     | 3563/7211 [14:16<12:05,  5.03it/s]

Reports:  49%|████▉     | 3564/7211 [14:16<11:57,  5.08it/s]

Reports:  49%|████▉     | 3565/7211 [14:16<11:52,  5.12it/s]

Reports:  49%|████▉     | 3566/7211 [14:16<11:46,  5.16it/s]

Reports:  49%|████▉     | 3567/7211 [14:17<11:40,  5.20it/s]

Reports:  49%|████▉     | 3568/7211 [14:17<11:49,  5.13it/s]

Reports:  49%|████▉     | 3569/7211 [14:17<11:59,  5.06it/s]

Reports:  50%|████▉     | 3570/7211 [14:17<11:59,  5.06it/s]

Reports:  50%|████▉     | 3571/7211 [14:17<11:52,  5.11it/s]

Reports:  50%|████▉     | 3572/7211 [14:18<12:12,  4.97it/s]

Reports:  50%|████▉     | 3573/7211 [14:18<12:01,  5.05it/s]

Reports:  50%|████▉     | 3574/7211 [14:18<11:47,  5.14it/s]

Reports:  50%|████▉     | 3575/7211 [14:18<11:48,  5.14it/s]

Reports:  50%|████▉     | 3576/7211 [14:18<11:57,  5.07it/s]

Reports:  50%|████▉     | 3577/7211 [14:19<11:54,  5.09it/s]

Reports:  50%|████▉     | 3578/7211 [14:19<11:53,  5.09it/s]

Reports:  50%|████▉     | 3579/7211 [14:19<12:04,  5.02it/s]

Reports:  50%|████▉     | 3580/7211 [14:19<12:11,  4.96it/s]

Reports:  50%|████▉     | 3581/7211 [14:19<11:58,  5.05it/s]

Reports:  50%|████▉     | 3582/7211 [14:20<11:55,  5.07it/s]

Reports:  50%|████▉     | 3583/7211 [14:20<11:49,  5.11it/s]

Reports:  50%|████▉     | 3584/7211 [14:20<11:43,  5.16it/s]

Reports:  50%|████▉     | 3585/7211 [14:20<12:03,  5.01it/s]

Reports:  50%|████▉     | 3586/7211 [14:20<12:21,  4.89it/s]

Reports:  50%|████▉     | 3587/7211 [14:21<12:08,  4.97it/s]

Reports:  50%|████▉     | 3588/7211 [14:21<12:06,  4.99it/s]

Reports:  50%|████▉     | 3589/7211 [14:21<12:02,  5.01it/s]

Reports:  50%|████▉     | 3590/7211 [14:21<15:26,  3.91it/s]

Reports:  50%|████▉     | 3591/7211 [14:22<14:19,  4.21it/s]

Reports:  50%|████▉     | 3592/7211 [14:22<13:36,  4.43it/s]

Reports:  50%|████▉     | 3593/7211 [14:22<13:11,  4.57it/s]

Reports:  50%|████▉     | 3594/7211 [14:22<12:55,  4.67it/s]

Reports:  50%|████▉     | 3595/7211 [14:22<12:40,  4.75it/s]

Reports:  50%|████▉     | 3596/7211 [14:23<12:27,  4.84it/s]

Reports:  50%|████▉     | 3597/7211 [14:23<12:19,  4.88it/s]

Reports:  50%|████▉     | 3598/7211 [14:23<12:25,  4.84it/s]

Reports:  50%|████▉     | 3599/7211 [14:23<12:26,  4.84it/s]

Reports:  50%|████▉     | 3600/7211 [14:23<12:07,  4.97it/s]

Reports:  50%|████▉     | 3601/7211 [14:24<11:59,  5.01it/s]

Reports:  50%|████▉     | 3602/7211 [14:24<11:45,  5.11it/s]

Reports:  50%|████▉     | 3603/7211 [14:24<11:30,  5.22it/s]

Reports:  50%|████▉     | 3604/7211 [14:24<11:30,  5.23it/s]

Reports:  50%|████▉     | 3605/7211 [14:24<11:33,  5.20it/s]

Reports:  50%|█████     | 3606/7211 [14:25<11:51,  5.06it/s]

Reports:  50%|█████     | 3607/7211 [14:25<12:02,  4.99it/s]

Reports:  50%|█████     | 3608/7211 [14:25<11:54,  5.04it/s]

Reports:  50%|█████     | 3609/7211 [14:25<11:48,  5.08it/s]

Reports:  50%|█████     | 3610/7211 [14:25<11:35,  5.18it/s]

Reports:  50%|█████     | 3611/7211 [14:25<11:28,  5.23it/s]

Reports:  50%|█████     | 3612/7211 [14:26<11:29,  5.22it/s]

Reports:  50%|█████     | 3613/7211 [14:26<11:35,  5.17it/s]

Reports:  50%|█████     | 3614/7211 [14:26<11:35,  5.17it/s]

Reports:  50%|█████     | 3615/7211 [14:26<11:41,  5.12it/s]

Reports:  50%|█████     | 3616/7211 [14:26<11:34,  5.18it/s]

Reports:  50%|█████     | 3617/7211 [14:28<36:57,  1.62it/s]

Reports:  50%|█████     | 3618/7211 [14:28<29:34,  2.02it/s]

Reports:  50%|█████     | 3619/7211 [14:28<24:19,  2.46it/s]

Reports:  50%|█████     | 3620/7211 [14:29<20:27,  2.93it/s]

Reports:  50%|█████     | 3621/7211 [14:30<32:42,  1.83it/s]

Reports:  50%|█████     | 3622/7211 [14:30<26:31,  2.26it/s]

Reports:  50%|█████     | 3623/7211 [14:31<33:45,  1.77it/s]

Reports:  50%|█████     | 3624/7211 [14:31<27:11,  2.20it/s]

Reports:  50%|█████     | 3625/7211 [14:31<22:39,  2.64it/s]

Reports:  50%|█████     | 3626/7211 [14:31<19:17,  3.10it/s]

Reports:  50%|█████     | 3627/7211 [14:32<16:50,  3.55it/s]

Reports:  50%|█████     | 3628/7211 [14:32<15:23,  3.88it/s]

Reports:  50%|█████     | 3629/7211 [14:32<14:31,  4.11it/s]

Reports:  50%|█████     | 3630/7211 [14:32<14:03,  4.25it/s]

Reports:  50%|█████     | 3631/7211 [14:32<13:16,  4.50it/s]

Reports:  50%|█████     | 3632/7211 [14:33<12:50,  4.65it/s]

Reports:  50%|█████     | 3633/7211 [14:33<12:36,  4.73it/s]

Reports:  50%|█████     | 3634/7211 [14:33<12:30,  4.77it/s]

Reports:  50%|█████     | 3635/7211 [14:33<12:15,  4.86it/s]

Reports:  50%|█████     | 3636/7211 [14:33<12:01,  4.95it/s]

Reports:  50%|█████     | 3637/7211 [14:34<11:44,  5.07it/s]

Reports:  50%|█████     | 3638/7211 [14:34<11:38,  5.11it/s]

Reports:  50%|█████     | 3639/7211 [14:34<11:36,  5.13it/s]

Reports:  50%|█████     | 3640/7211 [14:34<11:51,  5.02it/s]

Reports:  50%|█████     | 3641/7211 [14:34<11:50,  5.03it/s]

Reports:  51%|█████     | 3642/7211 [14:35<11:47,  5.05it/s]

Reports:  51%|█████     | 3643/7211 [14:35<11:53,  5.00it/s]

Reports:  51%|█████     | 3644/7211 [14:35<11:55,  4.99it/s]

Reports:  51%|█████     | 3645/7211 [14:35<11:48,  5.03it/s]

Reports:  51%|█████     | 3646/7211 [14:35<11:56,  4.98it/s]

Reports:  51%|█████     | 3647/7211 [14:36<11:49,  5.03it/s]

Reports:  51%|█████     | 3648/7211 [14:36<11:40,  5.08it/s]

Reports:  51%|█████     | 3649/7211 [14:36<11:58,  4.96it/s]

Reports:  51%|█████     | 3650/7211 [14:36<11:57,  4.97it/s]

Reports:  51%|█████     | 3651/7211 [14:36<11:50,  5.01it/s]

Reports:  51%|█████     | 3652/7211 [14:36<11:40,  5.08it/s]

Reports:  51%|█████     | 3653/7211 [14:37<11:32,  5.14it/s]

Reports:  51%|█████     | 3654/7211 [14:37<11:35,  5.11it/s]

Reports:  51%|█████     | 3655/7211 [14:37<11:36,  5.11it/s]

Reports:  51%|█████     | 3656/7211 [14:41<1:25:05,  1.44s/it]

Reports:  51%|█████     | 3657/7211 [14:42<1:02:57,  1.06s/it]

Reports:  51%|█████     | 3658/7211 [14:42<47:27,  1.25it/s]

Reports:  51%|█████     | 3659/7211 [14:42<36:35,  1.62it/s]

Reports:  51%|█████     | 3660/7211 [14:42<28:57,  2.04it/s]

Reports:  51%|█████     | 3661/7211 [14:42<23:45,  2.49it/s]

Reports:  51%|█████     | 3662/7211 [14:43<20:14,  2.92it/s]

Reports:  51%|█████     | 3663/7211 [14:43<17:39,  3.35it/s]

Reports:  51%|█████     | 3664/7211 [14:43<15:54,  3.72it/s]

Reports:  51%|█████     | 3665/7211 [14:43<14:39,  4.03it/s]

Reports:  51%|█████     | 3666/7211 [14:43<14:00,  4.22it/s]

Reports:  51%|█████     | 3667/7211 [14:44<13:14,  4.46it/s]

Reports:  51%|█████     | 3668/7211 [14:44<12:46,  4.62it/s]

Reports:  51%|█████     | 3669/7211 [14:44<12:19,  4.79it/s]

Reports:  51%|█████     | 3670/7211 [14:44<12:13,  4.83it/s]

Reports:  51%|█████     | 3671/7211 [14:44<11:51,  4.97it/s]

Reports:  51%|█████     | 3672/7211 [14:45<11:37,  5.08it/s]

Reports:  51%|█████     | 3673/7211 [14:45<11:28,  5.14it/s]

Reports:  51%|█████     | 3674/7211 [14:45<11:27,  5.14it/s]

Reports:  51%|█████     | 3675/7211 [14:45<11:27,  5.14it/s]

Reports:  51%|█████     | 3676/7211 [14:45<11:47,  5.00it/s]

Reports:  51%|█████     | 3677/7211 [14:46<11:51,  4.97it/s]

Reports:  51%|█████     | 3678/7211 [14:46<11:49,  4.98it/s]

Reports:  51%|█████     | 3679/7211 [14:46<11:51,  4.97it/s]

Reports:  51%|█████     | 3680/7211 [14:46<12:06,  4.86it/s]

Reports:  51%|█████     | 3681/7211 [14:46<12:11,  4.83it/s]

Reports:  51%|█████     | 3682/7211 [14:47<11:55,  4.93it/s]

Reports:  51%|█████     | 3683/7211 [14:47<14:18,  4.11it/s]

Reports:  51%|█████     | 3684/7211 [14:47<13:38,  4.31it/s]

Reports:  51%|█████     | 3685/7211 [14:47<13:18,  4.41it/s]

Reports:  51%|█████     | 3686/7211 [14:48<12:37,  4.65it/s]

Reports:  51%|█████     | 3687/7211 [14:48<12:11,  4.82it/s]

Reports:  51%|█████     | 3688/7211 [14:48<11:54,  4.93it/s]

Reports:  51%|█████     | 3689/7211 [14:48<11:43,  5.01it/s]

Reports:  51%|█████     | 3690/7211 [14:48<11:45,  4.99it/s]

Reports:  51%|█████     | 3691/7211 [14:48<11:45,  4.99it/s]

Reports:  51%|█████     | 3692/7211 [14:49<11:39,  5.03it/s]

Reports:  51%|█████     | 3693/7211 [14:49<11:46,  4.98it/s]

Reports:  51%|█████     | 3694/7211 [14:49<11:33,  5.07it/s]

Reports:  51%|█████     | 3695/7211 [14:49<11:24,  5.14it/s]

Reports:  51%|█████▏    | 3696/7211 [14:49<11:23,  5.14it/s]

Reports:  51%|█████▏    | 3697/7211 [14:50<11:36,  5.05it/s]

Reports:  51%|█████▏    | 3698/7211 [14:50<11:18,  5.18it/s]

Reports:  51%|█████▏    | 3699/7211 [14:50<11:46,  4.97it/s]

Reports:  51%|█████▏    | 3700/7211 [14:50<11:55,  4.91it/s]

Reports:  51%|█████▏    | 3701/7211 [14:50<11:44,  4.98it/s]

Reports:  51%|█████▏    | 3702/7211 [14:51<11:46,  4.97it/s]

Reports:  51%|█████▏    | 3703/7211 [14:51<11:36,  5.04it/s]

Reports:  51%|█████▏    | 3704/7211 [14:51<11:31,  5.07it/s]

Reports:  51%|█████▏    | 3705/7211 [14:51<11:39,  5.01it/s]

Reports:  51%|█████▏    | 3706/7211 [14:51<11:52,  4.92it/s]

Reports:  51%|█████▏    | 3707/7211 [14:52<11:50,  4.93it/s]

Reports:  51%|█████▏    | 3708/7211 [14:52<21:57,  2.66it/s]

Reports:  51%|█████▏    | 3709/7211 [14:53<18:44,  3.11it/s]

Reports:  51%|█████▏    | 3710/7211 [14:53<16:36,  3.51it/s]

Reports:  51%|█████▏    | 3711/7211 [14:53<15:02,  3.88it/s]

Reports:  51%|█████▏    | 3712/7211 [14:53<14:03,  4.15it/s]

Reports:  51%|█████▏    | 3713/7211 [14:53<13:24,  4.35it/s]

Reports:  52%|█████▏    | 3714/7211 [14:54<12:45,  4.57it/s]

Reports:  52%|█████▏    | 3715/7211 [14:54<12:14,  4.76it/s]

Reports:  52%|█████▏    | 3716/7211 [14:54<12:04,  4.82it/s]

Reports:  52%|█████▏    | 3717/7211 [14:55<19:08,  3.04it/s]

Reports:  52%|█████▏    | 3718/7211 [14:55<16:48,  3.47it/s]

Reports:  52%|█████▏    | 3719/7211 [14:55<15:07,  3.85it/s]

Reports:  52%|█████▏    | 3720/7211 [14:56<23:29,  2.48it/s]

Reports:  52%|█████▏    | 3721/7211 [14:56<23:57,  2.43it/s]

Reports:  52%|█████▏    | 3722/7211 [14:56<20:05,  2.89it/s]

Reports:  52%|█████▏    | 3723/7211 [14:57<17:19,  3.36it/s]

Reports:  52%|█████▏    | 3724/7211 [14:57<15:46,  3.68it/s]

Reports:  52%|█████▏    | 3725/7211 [14:57<14:36,  3.98it/s]

Reports:  52%|█████▏    | 3726/7211 [14:57<13:50,  4.19it/s]

Reports:  52%|█████▏    | 3727/7211 [14:57<13:13,  4.39it/s]

Reports:  52%|█████▏    | 3728/7211 [14:58<12:46,  4.55it/s]

Reports:  52%|█████▏    | 3729/7211 [14:58<12:19,  4.71it/s]

Reports:  52%|█████▏    | 3730/7211 [14:58<11:52,  4.89it/s]

Reports:  52%|█████▏    | 3731/7211 [14:58<11:50,  4.90it/s]

Reports:  52%|█████▏    | 3732/7211 [14:58<11:56,  4.86it/s]

Reports:  52%|█████▏    | 3733/7211 [14:59<11:53,  4.88it/s]

Reports:  52%|█████▏    | 3734/7211 [14:59<11:36,  4.99it/s]

Reports:  52%|█████▏    | 3735/7211 [14:59<11:29,  5.04it/s]

Reports:  52%|█████▏    | 3736/7211 [14:59<11:18,  5.12it/s]

Reports:  52%|█████▏    | 3737/7211 [14:59<11:12,  5.17it/s]

Reports:  52%|█████▏    | 3738/7211 [15:00<11:25,  5.07it/s]

Reports:  52%|█████▏    | 3739/7211 [15:00<11:28,  5.04it/s]

Reports:  52%|█████▏    | 3740/7211 [15:00<11:29,  5.04it/s]

Reports:  52%|█████▏    | 3741/7211 [15:00<11:24,  5.07it/s]

Reports:  52%|█████▏    | 3742/7211 [15:00<11:21,  5.09it/s]

Reports:  52%|█████▏    | 3743/7211 [15:01<11:15,  5.13it/s]

Reports:  52%|█████▏    | 3744/7211 [15:01<11:15,  5.13it/s]

Reports:  52%|█████▏    | 3745/7211 [15:01<11:12,  5.15it/s]

Reports:  52%|█████▏    | 3746/7211 [15:01<11:10,  5.17it/s]

Reports:  52%|█████▏    | 3747/7211 [15:01<11:06,  5.20it/s]

Reports:  52%|█████▏    | 3748/7211 [15:02<11:06,  5.20it/s]

Reports:  52%|█████▏    | 3749/7211 [15:02<11:07,  5.19it/s]

Reports:  52%|█████▏    | 3750/7211 [15:02<11:06,  5.19it/s]

Reports:  52%|█████▏    | 3751/7211 [15:02<11:03,  5.21it/s]

Reports:  52%|█████▏    | 3752/7211 [15:02<11:11,  5.15it/s]

Reports:  52%|█████▏    | 3753/7211 [15:02<11:16,  5.11it/s]

Reports:  52%|█████▏    | 3754/7211 [15:03<11:10,  5.16it/s]

Reports:  52%|█████▏    | 3755/7211 [15:03<13:25,  4.29it/s]

Reports:  52%|█████▏    | 3756/7211 [15:03<12:37,  4.56it/s]

Reports:  52%|█████▏    | 3757/7211 [15:03<12:25,  4.63it/s]

Reports:  52%|█████▏    | 3758/7211 [15:04<15:50,  3.63it/s]

Reports:  52%|█████▏    | 3759/7211 [15:04<14:33,  3.95it/s]

Reports:  52%|█████▏    | 3760/7211 [15:04<13:29,  4.26it/s]

Reports:  52%|█████▏    | 3761/7211 [15:05<16:54,  3.40it/s]

Reports:  52%|█████▏    | 3762/7211 [15:05<15:17,  3.76it/s]

Reports:  52%|█████▏    | 3763/7211 [15:05<14:17,  4.02it/s]

Reports:  52%|█████▏    | 3764/7211 [15:05<14:18,  4.01it/s]

Reports:  52%|█████▏    | 3765/7211 [15:05<13:29,  4.26it/s]

Reports:  52%|█████▏    | 3766/7211 [15:06<12:44,  4.50it/s]

Reports:  52%|█████▏    | 3767/7211 [15:06<12:21,  4.65it/s]

Reports:  52%|█████▏    | 3768/7211 [15:06<11:50,  4.84it/s]

Reports:  52%|█████▏    | 3769/7211 [15:06<11:26,  5.02it/s]

Reports:  52%|█████▏    | 3770/7211 [15:06<11:14,  5.10it/s]

Reports:  52%|█████▏    | 3771/7211 [15:07<11:05,  5.17it/s]

Reports:  52%|█████▏    | 3772/7211 [15:07<10:52,  5.27it/s]

Reports:  52%|█████▏    | 3773/7211 [15:07<10:51,  5.28it/s]

Reports:  52%|█████▏    | 3774/7211 [15:07<11:13,  5.10it/s]

Reports:  52%|█████▏    | 3775/7211 [15:07<11:09,  5.13it/s]

Reports:  52%|█████▏    | 3776/7211 [15:08<11:09,  5.13it/s]

Reports:  52%|█████▏    | 3777/7211 [15:08<11:10,  5.12it/s]

Reports:  52%|█████▏    | 3778/7211 [15:08<11:15,  5.08it/s]

Reports:  52%|█████▏    | 3779/7211 [15:08<11:14,  5.09it/s]

Reports:  52%|█████▏    | 3780/7211 [15:08<11:06,  5.15it/s]

Reports:  52%|█████▏    | 3781/7211 [15:09<10:55,  5.23it/s]

Reports:  52%|█████▏    | 3782/7211 [15:09<10:51,  5.26it/s]

Reports:  52%|█████▏    | 3783/7211 [15:09<10:46,  5.31it/s]

Reports:  52%|█████▏    | 3784/7211 [15:09<10:57,  5.21it/s]

Reports:  52%|█████▏    | 3785/7211 [15:09<10:55,  5.22it/s]

Reports:  53%|█████▎    | 3786/7211 [15:10<10:50,  5.26it/s]

Reports:  53%|█████▎    | 3787/7211 [15:10<11:08,  5.12it/s]

Reports:  53%|█████▎    | 3788/7211 [15:10<11:08,  5.12it/s]

Reports:  53%|█████▎    | 3789/7211 [15:10<11:13,  5.08it/s]

Reports:  53%|█████▎    | 3790/7211 [15:10<11:15,  5.06it/s]

Reports:  53%|█████▎    | 3791/7211 [15:11<11:22,  5.01it/s]

Reports:  53%|█████▎    | 3792/7211 [15:11<11:07,  5.12it/s]

Reports:  53%|█████▎    | 3793/7211 [15:11<11:03,  5.15it/s]

Reports:  53%|█████▎    | 3794/7211 [15:11<11:00,  5.17it/s]

Reports:  53%|█████▎    | 3795/7211 [15:11<12:27,  4.57it/s]

Reports:  53%|█████▎    | 3796/7211 [15:12<11:53,  4.79it/s]

Reports:  53%|█████▎    | 3797/7211 [15:12<11:41,  4.86it/s]

Reports:  53%|█████▎    | 3798/7211 [15:12<11:23,  4.99it/s]

Reports:  53%|█████▎    | 3799/7211 [15:12<11:27,  4.96it/s]

Reports:  53%|█████▎    | 3800/7211 [15:12<11:13,  5.06it/s]

Reports:  53%|█████▎    | 3801/7211 [15:13<11:07,  5.11it/s]

Reports:  53%|█████▎    | 3802/7211 [15:13<11:06,  5.12it/s]

Reports:  53%|█████▎    | 3803/7211 [15:13<11:07,  5.11it/s]

Reports:  53%|█████▎    | 3804/7211 [15:13<11:19,  5.01it/s]

Reports:  53%|█████▎    | 3805/7211 [15:13<11:27,  4.96it/s]

Reports:  53%|█████▎    | 3806/7211 [15:14<11:19,  5.01it/s]

Reports:  53%|█████▎    | 3807/7211 [15:14<11:06,  5.11it/s]

Reports:  53%|█████▎    | 3808/7211 [15:14<11:17,  5.02it/s]

Reports:  53%|█████▎    | 3809/7211 [15:14<11:14,  5.04it/s]

Reports:  53%|█████▎    | 3810/7211 [15:14<11:03,  5.12it/s]

Reports:  53%|█████▎    | 3811/7211 [15:14<11:03,  5.13it/s]

Reports:  53%|█████▎    | 3812/7211 [15:15<11:50,  4.78it/s]

Reports:  53%|█████▎    | 3813/7211 [15:15<12:59,  4.36it/s]

Reports:  53%|█████▎    | 3814/7211 [15:15<13:08,  4.31it/s]

Reports:  53%|█████▎    | 3815/7211 [15:15<12:27,  4.55it/s]

Reports:  53%|█████▎    | 3816/7211 [15:16<15:22,  3.68it/s]

Reports:  53%|█████▎    | 3817/7211 [15:16<15:24,  3.67it/s]

Reports:  53%|█████▎    | 3818/7211 [15:16<15:27,  3.66it/s]

Reports:  53%|█████▎    | 3819/7211 [15:17<15:27,  3.66it/s]

Reports:  53%|█████▎    | 3820/7211 [15:17<14:40,  3.85it/s]

Reports:  53%|█████▎    | 3821/7211 [15:17<15:42,  3.60it/s]

Reports:  53%|█████▎    | 3822/7211 [15:17<15:31,  3.64it/s]

Reports:  53%|█████▎    | 3823/7211 [15:18<14:44,  3.83it/s]

Reports:  53%|█████▎    | 3824/7211 [15:18<15:44,  3.59it/s]

Reports:  53%|█████▎    | 3825/7211 [15:18<16:03,  3.51it/s]

Reports:  53%|█████▎    | 3826/7211 [15:19<15:49,  3.57it/s]

Reports:  53%|█████▎    | 3827/7211 [15:19<15:54,  3.55it/s]

Reports:  53%|█████▎    | 3828/7211 [15:19<14:31,  3.88it/s]

Reports:  53%|█████▎    | 3829/7211 [15:19<13:39,  4.13it/s]

Reports:  53%|█████▎    | 3830/7211 [15:19<13:09,  4.28it/s]

Reports:  53%|█████▎    | 3831/7211 [15:20<12:22,  4.55it/s]

Reports:  53%|█████▎    | 3832/7211 [15:20<11:59,  4.69it/s]

Reports:  53%|█████▎    | 3833/7211 [15:20<11:45,  4.79it/s]

Reports:  53%|█████▎    | 3834/7211 [15:20<11:35,  4.86it/s]

Reports:  53%|█████▎    | 3835/7211 [15:20<11:19,  4.97it/s]

Reports:  53%|█████▎    | 3836/7211 [15:21<11:22,  4.94it/s]

Reports:  53%|█████▎    | 3837/7211 [15:21<11:13,  5.01it/s]

Reports:  53%|█████▎    | 3838/7211 [15:21<11:03,  5.08it/s]

Reports:  53%|█████▎    | 3839/7211 [15:21<10:53,  5.16it/s]

Reports:  53%|█████▎    | 3840/7211 [15:21<10:54,  5.15it/s]

Reports:  53%|█████▎    | 3841/7211 [15:22<10:44,  5.23it/s]

Reports:  53%|█████▎    | 3842/7211 [15:22<10:35,  5.30it/s]

Reports:  53%|█████▎    | 3843/7211 [15:22<10:40,  5.26it/s]

Reports:  53%|█████▎    | 3844/7211 [15:22<10:52,  5.16it/s]

Reports:  53%|█████▎    | 3845/7211 [15:22<10:47,  5.20it/s]

Reports:  53%|█████▎    | 3846/7211 [15:23<10:56,  5.12it/s]

Reports:  53%|█████▎    | 3847/7211 [15:23<10:57,  5.12it/s]

Reports:  53%|█████▎    | 3848/7211 [15:23<11:05,  5.06it/s]

Reports:  53%|█████▎    | 3849/7211 [15:23<10:53,  5.14it/s]

Reports:  53%|█████▎    | 3850/7211 [15:23<11:10,  5.01it/s]

Reports:  53%|█████▎    | 3851/7211 [15:24<10:55,  5.13it/s]

Reports:  53%|█████▎    | 3852/7211 [15:24<11:03,  5.07it/s]

Reports:  53%|█████▎    | 3853/7211 [15:24<11:00,  5.08it/s]

Reports:  53%|█████▎    | 3854/7211 [15:24<10:51,  5.15it/s]

Reports:  53%|█████▎    | 3855/7211 [15:24<10:50,  5.16it/s]

Reports:  53%|█████▎    | 3856/7211 [15:25<10:51,  5.15it/s]

Reports:  53%|█████▎    | 3857/7211 [15:25<10:48,  5.17it/s]

Reports:  54%|█████▎    | 3858/7211 [15:25<10:38,  5.25it/s]

Reports:  54%|█████▎    | 3859/7211 [15:25<10:46,  5.19it/s]

Reports:  54%|█████▎    | 3860/7211 [15:25<10:41,  5.22it/s]

Reports:  54%|█████▎    | 3861/7211 [15:26<10:45,  5.19it/s]

Reports:  54%|█████▎    | 3862/7211 [15:26<10:36,  5.26it/s]

Reports:  54%|█████▎    | 3863/7211 [15:26<10:38,  5.24it/s]

Reports:  54%|█████▎    | 3864/7211 [15:26<10:52,  5.13it/s]

Reports:  54%|█████▎    | 3865/7211 [15:26<10:39,  5.23it/s]

Reports:  54%|█████▎    | 3866/7211 [15:26<10:38,  5.24it/s]

Reports:  54%|█████▎    | 3867/7211 [15:27<10:51,  5.13it/s]

Reports:  54%|█████▎    | 3868/7211 [15:27<11:00,  5.06it/s]

Reports:  54%|█████▎    | 3869/7211 [15:27<10:52,  5.12it/s]

Reports:  54%|█████▎    | 3870/7211 [15:27<10:47,  5.16it/s]

Reports:  54%|█████▎    | 3871/7211 [15:27<11:02,  5.04it/s]

Reports:  54%|█████▎    | 3872/7211 [15:28<10:58,  5.07it/s]

Reports:  54%|█████▎    | 3873/7211 [15:28<10:55,  5.09it/s]

Reports:  54%|█████▎    | 3874/7211 [15:28<10:48,  5.14it/s]

Reports:  54%|█████▎    | 3875/7211 [15:28<10:42,  5.20it/s]

Reports:  54%|█████▍    | 3876/7211 [15:28<10:54,  5.09it/s]

Reports:  54%|█████▍    | 3877/7211 [15:29<10:59,  5.05it/s]

Reports:  54%|█████▍    | 3878/7211 [15:29<11:03,  5.02it/s]

Reports:  54%|█████▍    | 3879/7211 [15:29<11:07,  4.99it/s]

Reports:  54%|█████▍    | 3880/7211 [15:29<11:12,  4.96it/s]

Reports:  54%|█████▍    | 3881/7211 [15:29<11:01,  5.03it/s]

Reports:  54%|█████▍    | 3882/7211 [15:30<10:55,  5.08it/s]

Reports:  54%|█████▍    | 3883/7211 [15:30<10:45,  5.15it/s]

Reports:  54%|█████▍    | 3884/7211 [15:30<10:42,  5.18it/s]

Reports:  54%|█████▍    | 3885/7211 [15:30<10:48,  5.13it/s]

Reports:  54%|█████▍    | 3886/7211 [15:30<10:36,  5.22it/s]

Reports:  54%|█████▍    | 3887/7211 [15:31<10:39,  5.20it/s]

Reports:  54%|█████▍    | 3888/7211 [15:31<10:34,  5.24it/s]

Reports:  54%|█████▍    | 3889/7211 [15:31<10:51,  5.10it/s]

Reports:  54%|█████▍    | 3890/7211 [15:31<11:00,  5.03it/s]

Reports:  54%|█████▍    | 3891/7211 [15:31<11:06,  4.98it/s]

Reports:  54%|█████▍    | 3892/7211 [15:32<11:11,  4.94it/s]

Reports:  54%|█████▍    | 3893/7211 [15:32<11:00,  5.02it/s]

Reports:  54%|█████▍    | 3894/7211 [15:32<10:51,  5.09it/s]

Reports:  54%|█████▍    | 3895/7211 [15:32<10:42,  5.16it/s]

Reports:  54%|█████▍    | 3896/7211 [15:32<10:47,  5.12it/s]

Reports:  54%|█████▍    | 3897/7211 [15:33<19:46,  2.79it/s]

Reports:  54%|█████▍    | 3898/7211 [15:33<17:06,  3.23it/s]

Reports:  54%|█████▍    | 3899/7211 [15:34<15:43,  3.51it/s]

Reports:  54%|█████▍    | 3900/7211 [15:34<14:02,  3.93it/s]

Reports:  54%|█████▍    | 3901/7211 [15:34<13:13,  4.17it/s]

Reports:  54%|█████▍    | 3902/7211 [15:34<12:27,  4.43it/s]

Reports:  54%|█████▍    | 3903/7211 [15:34<11:53,  4.64it/s]

Reports:  54%|█████▍    | 3904/7211 [15:34<11:30,  4.79it/s]

Reports:  54%|█████▍    | 3905/7211 [15:35<11:07,  4.95it/s]

Reports:  54%|█████▍    | 3906/7211 [15:35<10:55,  5.04it/s]

Reports:  54%|█████▍    | 3907/7211 [15:35<10:47,  5.10it/s]

Reports:  54%|█████▍    | 3908/7211 [15:35<11:40,  4.71it/s]

Reports:  54%|█████▍    | 3909/7211 [15:36<11:27,  4.80it/s]

Reports:  54%|█████▍    | 3910/7211 [15:36<11:14,  4.89it/s]

Reports:  54%|█████▍    | 3911/7211 [15:36<11:00,  4.99it/s]

Reports:  54%|█████▍    | 3912/7211 [15:36<11:01,  4.99it/s]

Reports:  54%|█████▍    | 3913/7211 [15:36<10:51,  5.06it/s]

Reports:  54%|█████▍    | 3914/7211 [15:36<10:36,  5.18it/s]

Reports:  54%|█████▍    | 3915/7211 [15:37<10:31,  5.22it/s]

Reports:  54%|█████▍    | 3916/7211 [15:37<10:52,  5.05it/s]

Reports:  54%|█████▍    | 3917/7211 [15:37<10:52,  5.05it/s]

Reports:  54%|█████▍    | 3918/7211 [15:37<10:48,  5.08it/s]

Reports:  54%|█████▍    | 3919/7211 [15:37<10:41,  5.13it/s]

Reports:  54%|█████▍    | 3920/7211 [15:38<10:41,  5.13it/s]

Reports:  54%|█████▍    | 3921/7211 [15:38<10:46,  5.09it/s]

Reports:  54%|█████▍    | 3922/7211 [15:38<10:52,  5.04it/s]

Reports:  54%|█████▍    | 3923/7211 [15:38<10:54,  5.02it/s]

Reports:  54%|█████▍    | 3924/7211 [15:38<11:19,  4.84it/s]

Reports:  54%|█████▍    | 3925/7211 [15:39<11:03,  4.95it/s]

Reports:  54%|█████▍    | 3926/7211 [15:39<10:47,  5.07it/s]

Reports:  54%|█████▍    | 3927/7211 [15:39<10:37,  5.15it/s]

Reports:  54%|█████▍    | 3928/7211 [15:39<10:32,  5.19it/s]

Reports:  54%|█████▍    | 3929/7211 [15:39<10:37,  5.15it/s]

Reports:  55%|█████▍    | 3930/7211 [15:40<10:36,  5.16it/s]

Reports:  55%|█████▍    | 3931/7211 [15:40<10:46,  5.08it/s]

Reports:  55%|█████▍    | 3932/7211 [15:40<10:23,  5.26it/s]

Reports:  55%|█████▍    | 3933/7211 [15:40<10:31,  5.19it/s]

Reports:  55%|█████▍    | 3934/7211 [15:40<10:24,  5.25it/s]

Reports:  55%|█████▍    | 3935/7211 [15:41<10:32,  5.18it/s]

Reports:  55%|█████▍    | 3936/7211 [15:41<10:42,  5.09it/s]

Reports:  55%|█████▍    | 3937/7211 [15:41<10:37,  5.13it/s]

Reports:  55%|█████▍    | 3938/7211 [15:41<10:26,  5.23it/s]

Reports:  55%|█████▍    | 3939/7211 [15:41<12:37,  4.32it/s]

Reports:  55%|█████▍    | 3940/7211 [15:42<11:57,  4.56it/s]

Reports:  55%|█████▍    | 3941/7211 [15:42<11:29,  4.74it/s]

Reports:  55%|█████▍    | 3942/7211 [15:42<11:07,  4.90it/s]

Reports:  55%|█████▍    | 3943/7211 [15:42<10:51,  5.02it/s]

Reports:  55%|█████▍    | 3944/7211 [15:42<10:40,  5.10it/s]

Reports:  55%|█████▍    | 3945/7211 [15:43<10:41,  5.09it/s]

Reports:  55%|█████▍    | 3946/7211 [15:43<10:32,  5.16it/s]

Reports:  55%|█████▍    | 3947/7211 [15:43<10:36,  5.13it/s]

Reports:  55%|█████▍    | 3948/7211 [15:43<10:33,  5.15it/s]

Reports:  55%|█████▍    | 3949/7211 [15:43<10:44,  5.06it/s]

Reports:  55%|█████▍    | 3950/7211 [15:44<10:45,  5.05it/s]

Reports:  55%|█████▍    | 3951/7211 [15:44<10:44,  5.06it/s]

Reports:  55%|█████▍    | 3952/7211 [15:44<10:36,  5.12it/s]

Reports:  55%|█████▍    | 3953/7211 [15:44<10:30,  5.17it/s]

Reports:  55%|█████▍    | 3954/7211 [15:44<10:30,  5.16it/s]

Reports:  55%|█████▍    | 3955/7211 [15:45<10:32,  5.15it/s]

Reports:  55%|█████▍    | 3956/7211 [15:45<10:40,  5.08it/s]

Reports:  55%|█████▍    | 3957/7211 [15:45<10:29,  5.17it/s]

Reports:  55%|█████▍    | 3958/7211 [15:45<10:35,  5.12it/s]

Reports:  55%|█████▍    | 3959/7211 [15:45<10:34,  5.12it/s]

Reports:  55%|█████▍    | 3960/7211 [15:46<10:25,  5.19it/s]

Reports:  55%|█████▍    | 3961/7211 [15:46<10:28,  5.17it/s]

Reports:  55%|█████▍    | 3962/7211 [15:46<10:21,  5.23it/s]

Reports:  55%|█████▍    | 3963/7211 [15:46<10:22,  5.21it/s]

Reports:  55%|█████▍    | 3964/7211 [15:46<10:13,  5.29it/s]

Reports:  55%|█████▍    | 3965/7211 [15:47<10:29,  5.16it/s]

Reports:  55%|█████▍    | 3966/7211 [15:47<10:25,  5.19it/s]

Reports:  55%|█████▌    | 3967/7211 [15:47<13:28,  4.01it/s]

Reports:  55%|█████▌    | 3968/7211 [15:47<12:34,  4.30it/s]

Reports:  55%|█████▌    | 3969/7211 [15:47<11:43,  4.61it/s]

Reports:  55%|█████▌    | 3970/7211 [15:48<11:17,  4.78it/s]

Reports:  55%|█████▌    | 3971/7211 [15:48<10:56,  4.93it/s]

Reports:  55%|█████▌    | 3972/7211 [15:48<10:51,  4.97it/s]

Reports:  55%|█████▌    | 3973/7211 [15:48<10:53,  4.95it/s]

Reports:  55%|█████▌    | 3974/7211 [15:48<10:52,  4.96it/s]

Reports:  55%|█████▌    | 3975/7211 [15:49<10:38,  5.07it/s]

Reports:  55%|█████▌    | 3976/7211 [15:49<10:29,  5.14it/s]

Reports:  55%|█████▌    | 3977/7211 [15:49<10:27,  5.15it/s]

Reports:  55%|█████▌    | 3978/7211 [15:49<10:34,  5.09it/s]

Reports:  55%|█████▌    | 3979/7211 [15:49<10:39,  5.06it/s]

Reports:  55%|█████▌    | 3980/7211 [15:50<10:29,  5.14it/s]

Reports:  55%|█████▌    | 3981/7211 [15:50<10:28,  5.14it/s]

Reports:  55%|█████▌    | 3982/7211 [15:50<10:45,  5.00it/s]

Reports:  55%|█████▌    | 3983/7211 [15:50<11:03,  4.87it/s]

Reports:  55%|█████▌    | 3984/7211 [15:50<11:00,  4.88it/s]

Reports:  55%|█████▌    | 3985/7211 [15:51<10:58,  4.90it/s]

Reports:  55%|█████▌    | 3986/7211 [15:51<11:01,  4.88it/s]

Reports:  55%|█████▌    | 3987/7211 [15:51<10:53,  4.93it/s]

Reports:  55%|█████▌    | 3988/7211 [15:51<10:36,  5.07it/s]

Reports:  55%|█████▌    | 3989/7211 [15:51<10:33,  5.09it/s]

Reports:  55%|█████▌    | 3990/7211 [15:52<10:29,  5.12it/s]

Reports:  55%|█████▌    | 3991/7211 [15:52<10:26,  5.14it/s]

Reports:  55%|█████▌    | 3992/7211 [15:52<10:18,  5.21it/s]

Reports:  55%|█████▌    | 3993/7211 [15:52<10:18,  5.21it/s]

Reports:  55%|█████▌    | 3994/7211 [15:52<10:22,  5.17it/s]

Reports:  55%|█████▌    | 3995/7211 [15:53<10:31,  5.10it/s]

Reports:  55%|█████▌    | 3996/7211 [15:53<10:23,  5.16it/s]

Reports:  55%|█████▌    | 3997/7211 [15:53<10:17,  5.20it/s]

Reports:  55%|█████▌    | 3998/7211 [15:53<10:27,  5.12it/s]

Reports:  55%|█████▌    | 3999/7211 [15:53<10:20,  5.18it/s]

Reports:  55%|█████▌    | 4000/7211 [15:54<10:20,  5.17it/s]

Reports:  55%|█████▌    | 4001/7211 [15:54<10:23,  5.15it/s]

Reports:  55%|█████▌    | 4002/7211 [15:54<10:23,  5.14it/s]

Reports:  56%|█████▌    | 4003/7211 [15:54<10:31,  5.08it/s]

Reports:  56%|█████▌    | 4004/7211 [15:54<10:28,  5.10it/s]

Reports:  56%|█████▌    | 4005/7211 [15:55<10:40,  5.00it/s]

Reports:  56%|█████▌    | 4006/7211 [15:55<10:32,  5.07it/s]

Reports:  56%|█████▌    | 4007/7211 [15:55<10:25,  5.12it/s]

Reports:  56%|█████▌    | 4008/7211 [15:55<10:17,  5.19it/s]

Reports:  56%|█████▌    | 4009/7211 [15:55<10:18,  5.18it/s]

Reports:  56%|█████▌    | 4010/7211 [15:55<10:13,  5.22it/s]

Reports:  56%|█████▌    | 4011/7211 [15:56<10:32,  5.06it/s]

Reports:  56%|█████▌    | 4012/7211 [15:56<10:36,  5.03it/s]

Reports:  56%|█████▌    | 4013/7211 [15:56<10:30,  5.07it/s]

Reports:  56%|█████▌    | 4014/7211 [15:56<10:24,  5.12it/s]

Reports:  56%|█████▌    | 4015/7211 [15:56<10:14,  5.20it/s]

Reports:  56%|█████▌    | 4016/7211 [15:57<10:43,  4.96it/s]

Reports:  56%|█████▌    | 4017/7211 [15:57<10:37,  5.01it/s]

Reports:  56%|█████▌    | 4018/7211 [15:57<10:27,  5.09it/s]

Reports:  56%|█████▌    | 4019/7211 [15:57<10:27,  5.08it/s]

Reports:  56%|█████▌    | 4020/7211 [15:57<10:23,  5.11it/s]

Reports:  56%|█████▌    | 4021/7211 [15:58<10:40,  4.98it/s]

Reports:  56%|█████▌    | 4022/7211 [15:58<10:39,  4.99it/s]

Reports:  56%|█████▌    | 4023/7211 [15:58<10:38,  4.99it/s]

Reports:  56%|█████▌    | 4024/7211 [15:58<10:35,  5.01it/s]

Reports:  56%|█████▌    | 4025/7211 [15:58<10:34,  5.02it/s]

Reports:  56%|█████▌    | 4026/7211 [15:59<10:12,  5.20it/s]

Reports:  56%|█████▌    | 4027/7211 [15:59<10:24,  5.10it/s]

Reports:  56%|█████▌    | 4028/7211 [15:59<10:25,  5.09it/s]

Reports:  56%|█████▌    | 4029/7211 [15:59<11:38,  4.56it/s]

Reports:  56%|█████▌    | 4030/7211 [16:00<11:20,  4.67it/s]

Reports:  56%|█████▌    | 4031/7211 [16:00<10:59,  4.82it/s]

Reports:  56%|█████▌    | 4032/7211 [16:00<10:49,  4.90it/s]

Reports:  56%|█████▌    | 4033/7211 [16:00<10:41,  4.95it/s]

Reports:  56%|█████▌    | 4034/7211 [16:00<10:42,  4.94it/s]

Reports:  56%|█████▌    | 4035/7211 [16:00<10:26,  5.07it/s]

Reports:  56%|█████▌    | 4036/7211 [16:01<10:27,  5.06it/s]

Reports:  56%|█████▌    | 4037/7211 [16:01<10:34,  5.00it/s]

Reports:  56%|█████▌    | 4038/7211 [16:01<10:53,  4.85it/s]

Reports:  56%|█████▌    | 4039/7211 [16:01<10:40,  4.95it/s]

Reports:  56%|█████▌    | 4040/7211 [16:02<10:30,  5.03it/s]

Reports:  56%|█████▌    | 4041/7211 [16:02<10:27,  5.05it/s]

Reports:  56%|█████▌    | 4042/7211 [16:02<10:21,  5.10it/s]

Reports:  56%|█████▌    | 4043/7211 [16:02<10:18,  5.12it/s]

Reports:  56%|█████▌    | 4044/7211 [16:02<11:42,  4.51it/s]

Reports:  56%|█████▌    | 4045/7211 [16:03<11:10,  4.72it/s]

Reports:  56%|█████▌    | 4046/7211 [16:03<10:54,  4.84it/s]

Reports:  56%|█████▌    | 4047/7211 [16:03<10:34,  4.98it/s]

Reports:  56%|█████▌    | 4048/7211 [16:03<10:34,  4.98it/s]

Reports:  56%|█████▌    | 4049/7211 [16:03<10:25,  5.06it/s]

Reports:  56%|█████▌    | 4050/7211 [16:04<10:12,  5.16it/s]

Reports:  56%|█████▌    | 4051/7211 [16:04<10:03,  5.23it/s]

Reports:  56%|█████▌    | 4052/7211 [16:04<10:07,  5.20it/s]

Reports:  56%|█████▌    | 4053/7211 [16:04<10:09,  5.18it/s]

Reports:  56%|█████▌    | 4054/7211 [16:04<10:05,  5.21it/s]

Reports:  56%|█████▌    | 4055/7211 [16:04<09:56,  5.29it/s]

Reports:  56%|█████▌    | 4056/7211 [16:05<09:54,  5.31it/s]

Reports:  56%|█████▋    | 4057/7211 [16:05<10:23,  5.06it/s]

Reports:  56%|█████▋    | 4058/7211 [16:05<10:16,  5.12it/s]

Reports:  56%|█████▋    | 4059/7211 [16:05<10:17,  5.11it/s]

Reports:  56%|█████▋    | 4060/7211 [16:05<10:21,  5.07it/s]

Reports:  56%|█████▋    | 4061/7211 [16:06<10:12,  5.14it/s]

Reports:  56%|█████▋    | 4062/7211 [16:06<10:25,  5.04it/s]

Reports:  56%|█████▋    | 4063/7211 [16:06<10:14,  5.12it/s]

Reports:  56%|█████▋    | 4064/7211 [16:06<10:13,  5.13it/s]

Reports:  56%|█████▋    | 4065/7211 [16:06<10:34,  4.96it/s]

Reports:  56%|█████▋    | 4066/7211 [16:07<10:47,  4.86it/s]

Reports:  56%|█████▋    | 4067/7211 [16:07<10:39,  4.91it/s]

Reports:  56%|█████▋    | 4068/7211 [16:07<10:34,  4.96it/s]

Reports:  56%|█████▋    | 4069/7211 [16:07<10:17,  5.09it/s]

Reports:  56%|█████▋    | 4070/7211 [16:07<10:11,  5.14it/s]

Reports:  56%|█████▋    | 4071/7211 [16:08<10:20,  5.06it/s]

Reports:  56%|█████▋    | 4072/7211 [16:08<10:26,  5.01it/s]

Reports:  56%|█████▋    | 4073/7211 [16:08<10:15,  5.10it/s]

Reports:  56%|█████▋    | 4074/7211 [16:08<10:12,  5.12it/s]

Reports:  57%|█████▋    | 4075/7211 [16:08<10:16,  5.08it/s]

Reports:  57%|█████▋    | 4076/7211 [16:09<10:22,  5.03it/s]

Reports:  57%|█████▋    | 4077/7211 [16:09<10:12,  5.11it/s]

Reports:  57%|█████▋    | 4078/7211 [16:09<10:13,  5.10it/s]

Reports:  57%|█████▋    | 4079/7211 [16:09<10:16,  5.08it/s]

Reports:  57%|█████▋    | 4080/7211 [16:09<10:06,  5.16it/s]

Reports:  57%|█████▋    | 4081/7211 [16:10<10:02,  5.19it/s]

Reports:  57%|█████▋    | 4082/7211 [16:10<09:56,  5.25it/s]

Reports:  57%|█████▋    | 4083/7211 [16:10<10:02,  5.19it/s]

Reports:  57%|█████▋    | 4084/7211 [16:10<10:08,  5.14it/s]

Reports:  57%|█████▋    | 4085/7211 [16:10<10:01,  5.20it/s]

Reports:  57%|█████▋    | 4086/7211 [16:11<09:57,  5.23it/s]

Reports:  57%|█████▋    | 4087/7211 [16:11<09:55,  5.25it/s]

Reports:  57%|█████▋    | 4088/7211 [16:11<10:02,  5.19it/s]

Reports:  57%|█████▋    | 4089/7211 [16:11<10:21,  5.03it/s]

Reports:  57%|█████▋    | 4090/7211 [16:11<10:25,  4.99it/s]

Reports:  57%|█████▋    | 4091/7211 [16:12<10:11,  5.10it/s]

Reports:  57%|█████▋    | 4092/7211 [16:12<10:16,  5.06it/s]

Reports:  57%|█████▋    | 4093/7211 [16:12<10:22,  5.01it/s]

Reports:  57%|█████▋    | 4094/7211 [16:12<10:09,  5.12it/s]

Reports:  57%|█████▋    | 4095/7211 [16:12<10:17,  5.05it/s]

Reports:  57%|█████▋    | 4096/7211 [16:13<10:19,  5.03it/s]

Reports:  57%|█████▋    | 4097/7211 [16:13<10:10,  5.10it/s]

Reports:  57%|█████▋    | 4098/7211 [16:13<10:08,  5.11it/s]

Reports:  57%|█████▋    | 4099/7211 [16:13<10:20,  5.02it/s]

Reports:  57%|█████▋    | 4100/7211 [16:13<10:05,  5.14it/s]

Reports:  57%|█████▋    | 4101/7211 [16:13<09:56,  5.22it/s]

Reports:  57%|█████▋    | 4102/7211 [16:14<13:20,  3.88it/s]

Reports:  57%|█████▋    | 4103/7211 [16:14<12:22,  4.19it/s]

Reports:  57%|█████▋    | 4104/7211 [16:14<11:39,  4.44it/s]

Reports:  57%|█████▋    | 4105/7211 [16:14<11:10,  4.63it/s]

Reports:  57%|█████▋    | 4106/7211 [16:15<10:59,  4.71it/s]

Reports:  57%|█████▋    | 4107/7211 [16:15<10:41,  4.84it/s]

Reports:  57%|█████▋    | 4108/7211 [16:15<10:21,  4.99it/s]

Reports:  57%|█████▋    | 4109/7211 [16:15<10:08,  5.10it/s]

Reports:  57%|█████▋    | 4110/7211 [16:15<10:00,  5.16it/s]

Reports:  57%|█████▋    | 4111/7211 [16:16<09:54,  5.22it/s]

Reports:  57%|█████▋    | 4112/7211 [16:16<09:48,  5.27it/s]

Reports:  57%|█████▋    | 4113/7211 [16:16<09:54,  5.21it/s]

Reports:  57%|█████▋    | 4114/7211 [16:16<09:52,  5.23it/s]

Reports:  57%|█████▋    | 4115/7211 [16:16<10:11,  5.06it/s]

Reports:  57%|█████▋    | 4116/7211 [16:17<10:06,  5.10it/s]

Reports:  57%|█████▋    | 4117/7211 [16:17<09:57,  5.17it/s]

Reports:  57%|█████▋    | 4118/7211 [16:17<10:03,  5.12it/s]

Reports:  57%|█████▋    | 4119/7211 [16:17<10:03,  5.12it/s]

Reports:  57%|█████▋    | 4120/7211 [16:17<10:02,  5.13it/s]

Reports:  57%|█████▋    | 4121/7211 [16:18<09:56,  5.18it/s]

Reports:  57%|█████▋    | 4122/7211 [16:18<09:53,  5.21it/s]

Reports:  57%|█████▋    | 4123/7211 [16:18<09:50,  5.23it/s]

Reports:  57%|█████▋    | 4124/7211 [16:18<09:57,  5.17it/s]

Reports:  57%|█████▋    | 4125/7211 [16:18<09:48,  5.24it/s]

Reports:  57%|█████▋    | 4126/7211 [16:19<10:14,  5.02it/s]

Reports:  57%|█████▋    | 4127/7211 [16:19<10:14,  5.02it/s]

Reports:  57%|█████▋    | 4128/7211 [16:19<10:10,  5.05it/s]

Reports:  57%|█████▋    | 4129/7211 [16:19<10:07,  5.07it/s]

Reports:  57%|█████▋    | 4130/7211 [16:19<09:56,  5.16it/s]

Reports:  57%|█████▋    | 4131/7211 [16:20<09:51,  5.21it/s]

Reports:  57%|█████▋    | 4132/7211 [16:20<10:13,  5.02it/s]

Reports:  57%|█████▋    | 4133/7211 [16:20<10:08,  5.06it/s]

Reports:  57%|█████▋    | 4134/7211 [16:20<10:00,  5.12it/s]

Reports:  57%|█████▋    | 4135/7211 [16:20<09:58,  5.14it/s]

Reports:  57%|█████▋    | 4136/7211 [16:21<09:57,  5.14it/s]

Reports:  57%|█████▋    | 4137/7211 [16:21<09:52,  5.19it/s]

Reports:  57%|█████▋    | 4138/7211 [16:21<09:43,  5.27it/s]

Reports:  57%|█████▋    | 4139/7211 [16:21<09:38,  5.31it/s]

Reports:  57%|█████▋    | 4140/7211 [16:21<09:51,  5.20it/s]

Reports:  57%|█████▋    | 4141/7211 [16:21<09:54,  5.16it/s]

Reports:  57%|█████▋    | 4142/7211 [16:22<09:53,  5.17it/s]

Reports:  57%|█████▋    | 4143/7211 [16:22<09:49,  5.20it/s]

Reports:  57%|█████▋    | 4144/7211 [16:22<09:48,  5.21it/s]

Reports:  57%|█████▋    | 4145/7211 [16:22<09:55,  5.15it/s]

Reports:  57%|█████▋    | 4146/7211 [16:23<12:34,  4.06it/s]

Reports:  58%|█████▊    | 4147/7211 [16:23<12:01,  4.25it/s]

Reports:  58%|█████▊    | 4148/7211 [16:23<11:46,  4.33it/s]

Reports:  58%|█████▊    | 4149/7211 [16:23<12:29,  4.08it/s]

Reports:  58%|█████▊    | 4150/7211 [16:24<11:48,  4.32it/s]

Reports:  58%|█████▊    | 4151/7211 [16:24<11:20,  4.50it/s]

Reports:  58%|█████▊    | 4152/7211 [16:24<11:08,  4.57it/s]

Reports:  58%|█████▊    | 4153/7211 [16:24<10:57,  4.65it/s]

Reports:  58%|█████▊    | 4154/7211 [16:24<10:33,  4.82it/s]

Reports:  58%|█████▊    | 4155/7211 [16:25<10:15,  4.96it/s]

Reports:  58%|█████▊    | 4156/7211 [16:25<10:15,  4.96it/s]

Reports:  58%|█████▊    | 4157/7211 [16:25<09:55,  5.13it/s]

Reports:  58%|█████▊    | 4158/7211 [16:25<09:47,  5.20it/s]

Reports:  58%|█████▊    | 4159/7211 [16:25<09:54,  5.13it/s]

Reports:  58%|█████▊    | 4160/7211 [16:25<09:54,  5.13it/s]

Reports:  58%|█████▊    | 4161/7211 [16:26<10:00,  5.08it/s]

Reports:  58%|█████▊    | 4162/7211 [16:27<28:39,  1.77it/s]

Reports:  58%|█████▊    | 4163/7211 [16:27<23:09,  2.19it/s]

Reports:  58%|█████▊    | 4164/7211 [16:27<19:03,  2.66it/s]

Reports:  58%|█████▊    | 4165/7211 [16:28<16:14,  3.13it/s]

Reports:  58%|█████▊    | 4166/7211 [16:51<6:10:44,  7.31s/it]

Reports:  58%|█████▊    | 4167/7211 [16:51<4:22:23,  5.17s/it]

Reports:  58%|█████▊    | 4168/7211 [16:52<3:06:39,  3.68s/it]

Reports:  58%|█████▊    | 4169/7211 [16:52<2:13:45,  2.64s/it]

Reports:  58%|█████▊    | 4170/7211 [16:52<1:36:27,  1.90s/it]

Reports:  58%|█████▊    | 4171/7211 [16:52<1:10:24,  1.39s/it]

Reports:  58%|█████▊    | 4172/7211 [16:52<52:11,  1.03s/it]

Reports:  58%|█████▊    | 4173/7211 [16:53<39:26,  1.28it/s]

Reports:  58%|█████▊    | 4174/7211 [16:53<30:43,  1.65it/s]

Reports:  58%|█████▊    | 4175/7211 [16:53<24:28,  2.07it/s]

Reports:  58%|█████▊    | 4176/7211 [16:53<20:09,  2.51it/s]

Reports:  58%|█████▊    | 4177/7211 [16:53<17:01,  2.97it/s]

Reports:  58%|█████▊    | 4178/7211 [16:54<14:43,  3.43it/s]

Reports:  58%|█████▊    | 4179/7211 [16:54<13:12,  3.83it/s]

Reports:  58%|█████▊    | 4180/7211 [16:54<12:04,  4.19it/s]

Reports:  58%|█████▊    | 4181/7211 [16:54<11:19,  4.46it/s]

Reports:  58%|█████▊    | 4182/7211 [16:54<10:38,  4.74it/s]

Reports:  58%|█████▊    | 4183/7211 [16:55<10:24,  4.85it/s]

Reports:  58%|█████▊    | 4184/7211 [16:55<10:04,  5.01it/s]

Reports:  58%|█████▊    | 4185/7211 [16:55<10:06,  4.99it/s]

Reports:  58%|█████▊    | 4186/7211 [16:55<10:07,  4.98it/s]

Reports:  58%|█████▊    | 4187/7211 [16:55<09:54,  5.08it/s]

Reports:  58%|█████▊    | 4188/7211 [16:56<09:54,  5.08it/s]

Reports:  58%|█████▊    | 4189/7211 [16:56<09:52,  5.10it/s]

Reports:  58%|█████▊    | 4190/7211 [16:56<09:46,  5.15it/s]

Reports:  58%|█████▊    | 4191/7211 [16:56<09:41,  5.19it/s]

Reports:  58%|█████▊    | 4192/7211 [16:56<09:39,  5.21it/s]

Reports:  58%|█████▊    | 4193/7211 [16:56<09:36,  5.24it/s]

Reports:  58%|█████▊    | 4194/7211 [16:57<09:33,  5.26it/s]

Reports:  58%|█████▊    | 4195/7211 [16:57<09:28,  5.30it/s]

Reports:  58%|█████▊    | 4196/7211 [16:57<09:23,  5.35it/s]

Reports:  58%|█████▊    | 4197/7211 [16:57<09:48,  5.12it/s]

Reports:  58%|█████▊    | 4198/7211 [16:57<09:42,  5.17it/s]

Reports:  58%|█████▊    | 4199/7211 [16:58<09:37,  5.22it/s]

Reports:  58%|█████▊    | 4200/7211 [16:58<09:52,  5.08it/s]

Reports:  58%|█████▊    | 4201/7211 [16:58<09:45,  5.14it/s]

Reports:  58%|█████▊    | 4202/7211 [16:58<09:42,  5.16it/s]

Reports:  58%|█████▊    | 4203/7211 [16:58<09:44,  5.15it/s]

Reports:  58%|█████▊    | 4204/7211 [16:59<09:36,  5.21it/s]

Reports:  58%|█████▊    | 4205/7211 [16:59<09:40,  5.18it/s]

Reports:  58%|█████▊    | 4206/7211 [16:59<09:37,  5.20it/s]

Reports:  58%|█████▊    | 4207/7211 [16:59<09:37,  5.21it/s]

Reports:  58%|█████▊    | 4208/7211 [16:59<09:34,  5.23it/s]

Reports:  58%|█████▊    | 4209/7211 [17:00<09:49,  5.10it/s]

Reports:  58%|█████▊    | 4210/7211 [17:00<09:42,  5.16it/s]

Reports:  58%|█████▊    | 4211/7211 [17:07<1:57:04,  2.34s/it]

Reports:  58%|█████▊    | 4212/7211 [17:07<1:25:08,  1.70s/it]

Reports:  58%|█████▊    | 4213/7211 [17:08<1:02:35,  1.25s/it]

Reports:  58%|█████▊    | 4214/7211 [17:08<46:45,  1.07it/s]

Reports:  58%|█████▊    | 4215/7211 [17:08<35:41,  1.40it/s]

Reports:  58%|█████▊    | 4216/7211 [17:08<27:47,  1.80it/s]

Reports:  58%|█████▊    | 4217/7211 [17:08<22:23,  2.23it/s]

Reports:  58%|█████▊    | 4218/7211 [17:09<18:33,  2.69it/s]

Reports:  59%|█████▊    | 4219/7211 [17:09<15:46,  3.16it/s]

Reports:  59%|█████▊    | 4220/7211 [17:09<13:53,  3.59it/s]

Reports:  59%|█████▊    | 4221/7211 [17:09<12:28,  4.00it/s]

Reports:  59%|█████▊    | 4222/7211 [17:09<11:35,  4.30it/s]

Reports:  59%|█████▊    | 4223/7211 [17:09<10:56,  4.55it/s]

Reports:  59%|█████▊    | 4224/7211 [17:10<13:25,  3.71it/s]

Reports:  59%|█████▊    | 4225/7211 [17:10<12:14,  4.07it/s]

Reports:  59%|█████▊    | 4226/7211 [17:10<11:24,  4.36it/s]

Reports:  59%|█████▊    | 4227/7211 [17:10<10:56,  4.55it/s]

Reports:  59%|█████▊    | 4228/7211 [17:11<10:28,  4.74it/s]

Reports:  59%|█████▊    | 4229/7211 [17:11<10:07,  4.91it/s]

Reports:  59%|█████▊    | 4230/7211 [17:11<10:02,  4.95it/s]

Reports:  59%|█████▊    | 4231/7211 [17:11<09:50,  5.05it/s]

Reports:  59%|█████▊    | 4232/7211 [17:11<09:48,  5.06it/s]

Reports:  59%|█████▊    | 4233/7211 [17:12<09:53,  5.02it/s]

Reports:  59%|█████▊    | 4234/7211 [17:12<09:45,  5.08it/s]

Reports:  59%|█████▊    | 4235/7211 [17:12<09:33,  5.19it/s]

Reports:  59%|█████▊    | 4236/7211 [17:12<09:44,  5.09it/s]

Reports:  59%|█████▉    | 4237/7211 [17:12<09:31,  5.20it/s]

Reports:  59%|█████▉    | 4238/7211 [17:13<09:40,  5.12it/s]

Reports:  59%|█████▉    | 4239/7211 [17:13<09:47,  5.06it/s]

Reports:  59%|█████▉    | 4240/7211 [17:13<09:36,  5.15it/s]

Reports:  59%|█████▉    | 4241/7211 [17:13<09:30,  5.21it/s]

Reports:  59%|█████▉    | 4242/7211 [17:13<09:30,  5.20it/s]

Reports:  59%|█████▉    | 4243/7211 [17:14<09:24,  5.26it/s]

Reports:  59%|█████▉    | 4244/7211 [17:14<09:26,  5.23it/s]

Reports:  59%|█████▉    | 4245/7211 [17:14<09:25,  5.25it/s]

Reports:  59%|█████▉    | 4246/7211 [17:14<09:25,  5.24it/s]

Reports:  59%|█████▉    | 4247/7211 [17:14<09:41,  5.10it/s]

Reports:  59%|█████▉    | 4248/7211 [17:14<09:33,  5.17it/s]

Reports:  59%|█████▉    | 4249/7211 [17:15<09:40,  5.10it/s]

Reports:  59%|█████▉    | 4250/7211 [17:15<09:33,  5.17it/s]

Reports:  59%|█████▉    | 4251/7211 [17:15<09:37,  5.13it/s]

Reports:  59%|█████▉    | 4252/7211 [17:15<09:31,  5.18it/s]

Reports:  59%|█████▉    | 4253/7211 [17:15<09:35,  5.14it/s]

Reports:  59%|█████▉    | 4254/7211 [17:16<09:45,  5.05it/s]

Reports:  59%|█████▉    | 4255/7211 [17:16<09:45,  5.05it/s]

Reports:  59%|█████▉    | 4256/7211 [17:16<09:43,  5.07it/s]

Reports:  59%|█████▉    | 4257/7211 [17:16<09:39,  5.10it/s]

Reports:  59%|█████▉    | 4258/7211 [17:16<09:45,  5.05it/s]

Reports:  59%|█████▉    | 4259/7211 [17:17<09:47,  5.02it/s]

Reports:  59%|█████▉    | 4260/7211 [17:17<09:42,  5.06it/s]

Reports:  59%|█████▉    | 4261/7211 [17:17<09:42,  5.06it/s]

Reports:  59%|█████▉    | 4262/7211 [17:17<09:38,  5.10it/s]

Reports:  59%|█████▉    | 4263/7211 [17:17<09:48,  5.01it/s]

Reports:  59%|█████▉    | 4264/7211 [17:18<09:45,  5.04it/s]

Reports:  59%|█████▉    | 4265/7211 [17:18<09:44,  5.04it/s]

Reports:  59%|█████▉    | 4266/7211 [17:18<09:49,  5.00it/s]

Reports:  59%|█████▉    | 4267/7211 [17:18<09:33,  5.13it/s]

Reports:  59%|█████▉    | 4268/7211 [17:18<09:48,  5.00it/s]

Reports:  59%|█████▉    | 4269/7211 [17:19<09:38,  5.09it/s]

Reports:  59%|█████▉    | 4270/7211 [17:19<09:30,  5.15it/s]

Reports:  59%|█████▉    | 4271/7211 [17:19<09:24,  5.21it/s]

Reports:  59%|█████▉    | 4272/7211 [17:19<09:22,  5.23it/s]

Reports:  59%|█████▉    | 4273/7211 [17:19<09:15,  5.29it/s]

Reports:  59%|█████▉    | 4274/7211 [17:20<09:13,  5.31it/s]

Reports:  59%|█████▉    | 4275/7211 [17:20<09:16,  5.27it/s]

Reports:  59%|█████▉    | 4276/7211 [17:20<09:16,  5.27it/s]

Reports:  59%|█████▉    | 4277/7211 [17:20<09:13,  5.30it/s]

Reports:  59%|█████▉    | 4278/7211 [17:20<09:21,  5.22it/s]

Reports:  59%|█████▉    | 4279/7211 [17:21<09:19,  5.24it/s]

Reports:  59%|█████▉    | 4280/7211 [17:21<09:15,  5.28it/s]

Reports:  59%|█████▉    | 4281/7211 [17:21<09:41,  5.03it/s]

Reports:  59%|█████▉    | 4282/7211 [17:21<09:32,  5.12it/s]

Reports:  59%|█████▉    | 4283/7211 [17:21<09:23,  5.20it/s]

Reports:  59%|█████▉    | 4284/7211 [17:21<09:15,  5.27it/s]

Reports:  59%|█████▉    | 4285/7211 [17:22<09:16,  5.25it/s]

Reports:  59%|█████▉    | 4286/7211 [17:22<09:26,  5.16it/s]

Reports:  59%|█████▉    | 4287/7211 [17:22<09:29,  5.13it/s]

Reports:  59%|█████▉    | 4288/7211 [17:22<09:23,  5.19it/s]

Reports:  59%|█████▉    | 4289/7211 [17:22<09:25,  5.17it/s]

Reports:  59%|█████▉    | 4290/7211 [17:23<09:19,  5.22it/s]

Reports:  60%|█████▉    | 4291/7211 [17:23<09:23,  5.18it/s]

Reports:  60%|█████▉    | 4292/7211 [17:23<09:20,  5.21it/s]

Reports:  60%|█████▉    | 4293/7211 [17:23<09:25,  5.16it/s]

Reports:  60%|█████▉    | 4294/7211 [17:23<09:27,  5.14it/s]

Reports:  60%|█████▉    | 4295/7211 [17:24<09:18,  5.22it/s]

Reports:  60%|█████▉    | 4296/7211 [17:24<09:15,  5.25it/s]

Reports:  60%|█████▉    | 4297/7211 [17:24<09:18,  5.21it/s]

Reports:  60%|█████▉    | 4298/7211 [17:24<09:23,  5.17it/s]

Reports:  60%|█████▉    | 4299/7211 [17:24<09:18,  5.22it/s]

Reports:  60%|█████▉    | 4300/7211 [17:25<09:11,  5.28it/s]

Reports:  60%|█████▉    | 4301/7211 [17:25<09:22,  5.17it/s]

Reports:  60%|█████▉    | 4302/7211 [17:25<09:35,  5.05it/s]

Reports:  60%|█████▉    | 4303/7211 [17:25<09:42,  4.99it/s]

Reports:  60%|█████▉    | 4304/7211 [17:25<09:40,  5.01it/s]

Reports:  60%|█████▉    | 4305/7211 [17:26<09:34,  5.06it/s]

Reports:  60%|█████▉    | 4306/7211 [17:26<09:24,  5.14it/s]

Reports:  60%|█████▉    | 4307/7211 [17:26<09:25,  5.13it/s]

Reports:  60%|█████▉    | 4308/7211 [17:26<09:21,  5.17it/s]

Reports:  60%|█████▉    | 4309/7211 [17:26<09:16,  5.21it/s]

Reports:  60%|█████▉    | 4310/7211 [17:27<09:26,  5.12it/s]

Reports:  60%|█████▉    | 4311/7211 [17:27<09:22,  5.15it/s]

Reports:  60%|█████▉    | 4312/7211 [17:27<09:16,  5.21it/s]

Reports:  60%|█████▉    | 4313/7211 [17:27<09:28,  5.10it/s]

Reports:  60%|█████▉    | 4314/7211 [17:27<09:19,  5.18it/s]

Reports:  60%|█████▉    | 4315/7211 [17:27<09:21,  5.16it/s]

Reports:  60%|█████▉    | 4316/7211 [17:28<09:20,  5.17it/s]

Reports:  60%|█████▉    | 4317/7211 [17:28<10:11,  4.73it/s]

Reports:  60%|█████▉    | 4318/7211 [17:28<10:28,  4.60it/s]

Reports:  60%|█████▉    | 4319/7211 [17:28<10:16,  4.69it/s]

Reports:  60%|█████▉    | 4320/7211 [17:29<10:19,  4.66it/s]

Reports:  60%|█████▉    | 4321/7211 [17:29<10:57,  4.39it/s]

Reports:  60%|█████▉    | 4322/7211 [17:29<11:13,  4.29it/s]

Reports:  60%|█████▉    | 4323/7211 [17:29<10:29,  4.59it/s]

Reports:  60%|█████▉    | 4324/7211 [17:29<10:16,  4.69it/s]

Reports:  60%|█████▉    | 4325/7211 [17:30<10:09,  4.73it/s]

Reports:  60%|█████▉    | 4326/7211 [17:30<09:46,  4.92it/s]

Reports:  60%|██████    | 4327/7211 [17:30<09:41,  4.96it/s]

Reports:  60%|██████    | 4328/7211 [17:30<09:29,  5.06it/s]

Reports:  60%|██████    | 4329/7211 [17:30<09:23,  5.11it/s]

Reports:  60%|██████    | 4330/7211 [17:31<09:10,  5.23it/s]

Reports:  60%|██████    | 4331/7211 [17:31<09:10,  5.23it/s]

Reports:  60%|██████    | 4332/7211 [17:31<09:03,  5.30it/s]

Reports:  60%|██████    | 4333/7211 [17:31<09:00,  5.33it/s]

Reports:  60%|██████    | 4334/7211 [17:31<09:05,  5.27it/s]

Reports:  60%|██████    | 4335/7211 [17:32<09:05,  5.27it/s]

Reports:  60%|██████    | 4336/7211 [17:32<09:13,  5.20it/s]

Reports:  60%|██████    | 4337/7211 [17:32<09:09,  5.23it/s]

Reports:  60%|██████    | 4338/7211 [17:32<09:27,  5.06it/s]

Reports:  60%|██████    | 4339/7211 [17:32<09:35,  4.99it/s]

Reports:  60%|██████    | 4340/7211 [17:33<09:40,  4.95it/s]

Reports:  60%|██████    | 4341/7211 [17:33<09:35,  4.99it/s]

Reports:  60%|██████    | 4342/7211 [17:33<09:24,  5.08it/s]

Reports:  60%|██████    | 4343/7211 [17:33<09:37,  4.96it/s]

Reports:  60%|██████    | 4344/7211 [17:33<09:26,  5.06it/s]

Reports:  60%|██████    | 4345/7211 [17:34<09:32,  5.00it/s]

Reports:  60%|██████    | 4346/7211 [17:34<09:22,  5.10it/s]

Reports:  60%|██████    | 4347/7211 [17:34<09:19,  5.12it/s]

Reports:  60%|██████    | 4348/7211 [17:34<09:15,  5.15it/s]

Reports:  60%|██████    | 4349/7211 [17:34<09:15,  5.15it/s]

Reports:  60%|██████    | 4350/7211 [17:35<09:06,  5.23it/s]

Reports:  60%|██████    | 4351/7211 [17:35<09:13,  5.17it/s]

Reports:  60%|██████    | 4352/7211 [17:35<09:04,  5.25it/s]

Reports:  60%|██████    | 4353/7211 [17:35<09:13,  5.17it/s]

Reports:  60%|██████    | 4354/7211 [17:35<09:13,  5.16it/s]

Reports:  60%|██████    | 4355/7211 [17:35<09:06,  5.23it/s]

Reports:  60%|██████    | 4356/7211 [17:36<09:09,  5.19it/s]

Reports:  60%|██████    | 4357/7211 [17:36<09:11,  5.18it/s]

Reports:  60%|██████    | 4358/7211 [17:36<09:14,  5.14it/s]

Reports:  60%|██████    | 4359/7211 [17:36<09:17,  5.11it/s]

Reports:  60%|██████    | 4360/7211 [17:36<09:22,  5.07it/s]

Reports:  60%|██████    | 4361/7211 [17:37<09:38,  4.93it/s]

Reports:  60%|██████    | 4362/7211 [17:37<09:25,  5.04it/s]

Reports:  61%|██████    | 4363/7211 [17:37<09:30,  4.99it/s]

Reports:  61%|██████    | 4364/7211 [17:37<09:29,  5.00it/s]

Reports:  61%|██████    | 4365/7211 [17:37<09:21,  5.07it/s]

Reports:  61%|██████    | 4366/7211 [17:38<09:32,  4.97it/s]

Reports:  61%|██████    | 4367/7211 [17:38<09:26,  5.02it/s]

Reports:  61%|██████    | 4368/7211 [17:38<09:41,  4.89it/s]

Reports:  61%|██████    | 4369/7211 [17:38<09:38,  4.91it/s]

Reports:  61%|██████    | 4370/7211 [17:38<09:33,  4.95it/s]

Reports:  61%|██████    | 4371/7211 [17:39<11:38,  4.07it/s]

Reports:  61%|██████    | 4372/7211 [17:39<11:04,  4.27it/s]

Reports:  61%|██████    | 4373/7211 [17:39<10:29,  4.51it/s]

Reports:  61%|██████    | 4374/7211 [17:39<10:13,  4.62it/s]

Reports:  61%|██████    | 4375/7211 [17:40<09:52,  4.78it/s]

Reports:  61%|██████    | 4376/7211 [17:40<09:34,  4.93it/s]

Reports:  61%|██████    | 4377/7211 [17:40<09:29,  4.98it/s]

Reports:  61%|██████    | 4378/7211 [17:40<09:21,  5.04it/s]

Reports:  61%|██████    | 4379/7211 [17:40<09:11,  5.13it/s]

Reports:  61%|██████    | 4380/7211 [17:41<09:00,  5.23it/s]

Reports:  61%|██████    | 4381/7211 [17:41<08:59,  5.24it/s]

Reports:  61%|██████    | 4382/7211 [17:41<09:01,  5.23it/s]

Reports:  61%|██████    | 4383/7211 [17:41<09:00,  5.23it/s]

Reports:  61%|██████    | 4384/7211 [17:41<08:56,  5.27it/s]

Reports:  61%|██████    | 4385/7211 [17:42<09:12,  5.11it/s]

Reports:  61%|██████    | 4386/7211 [17:42<09:04,  5.19it/s]

Reports:  61%|██████    | 4387/7211 [17:42<09:02,  5.21it/s]

Reports:  61%|██████    | 4388/7211 [17:42<09:02,  5.21it/s]

Reports:  61%|██████    | 4389/7211 [17:42<09:10,  5.12it/s]

Reports:  61%|██████    | 4390/7211 [17:43<09:18,  5.05it/s]

Reports:  61%|██████    | 4391/7211 [17:43<09:15,  5.07it/s]

Reports:  61%|██████    | 4392/7211 [17:43<09:56,  4.73it/s]

Reports:  61%|██████    | 4393/7211 [17:43<09:50,  4.77it/s]

Reports:  61%|██████    | 4394/7211 [17:43<09:38,  4.87it/s]

Reports:  61%|██████    | 4395/7211 [17:44<09:26,  4.97it/s]

Reports:  61%|██████    | 4396/7211 [17:44<09:15,  5.07it/s]

Reports:  61%|██████    | 4397/7211 [17:44<09:07,  5.14it/s]

Reports:  61%|██████    | 4398/7211 [17:44<09:15,  5.06it/s]

Reports:  61%|██████    | 4399/7211 [17:44<09:10,  5.10it/s]

Reports:  61%|██████    | 4400/7211 [17:45<09:17,  5.04it/s]

Reports:  61%|██████    | 4401/7211 [17:45<09:18,  5.04it/s]

Reports:  61%|██████    | 4402/7211 [17:45<09:10,  5.10it/s]

Reports:  61%|██████    | 4403/7211 [17:45<09:15,  5.05it/s]

Reports:  61%|██████    | 4404/7211 [17:45<09:17,  5.03it/s]

Reports:  61%|██████    | 4405/7211 [17:46<09:24,  4.97it/s]

Reports:  61%|██████    | 4406/7211 [17:46<09:11,  5.08it/s]

Reports:  61%|██████    | 4407/7211 [17:46<09:00,  5.19it/s]

Reports:  61%|██████    | 4408/7211 [17:46<09:03,  5.16it/s]

Reports:  61%|██████    | 4409/7211 [17:46<08:55,  5.23it/s]

Reports:  61%|██████    | 4410/7211 [17:46<09:13,  5.06it/s]

Reports:  61%|██████    | 4411/7211 [17:47<09:18,  5.02it/s]

Reports:  61%|██████    | 4412/7211 [17:47<09:22,  4.98it/s]

Reports:  61%|██████    | 4413/7211 [17:47<09:22,  4.98it/s]

Reports:  61%|██████    | 4414/7211 [17:47<09:15,  5.03it/s]

Reports:  61%|██████    | 4415/7211 [17:48<13:29,  3.46it/s]

Reports:  61%|██████    | 4416/7211 [17:48<12:00,  3.88it/s]

Reports:  61%|██████▏   | 4417/7211 [17:48<11:09,  4.17it/s]

Reports:  61%|██████▏   | 4418/7211 [17:48<10:32,  4.42it/s]

Reports:  61%|██████▏   | 4419/7211 [17:49<10:09,  4.58it/s]

Reports:  61%|██████▏   | 4420/7211 [17:49<09:50,  4.72it/s]

Reports:  61%|██████▏   | 4421/7211 [17:49<09:31,  4.88it/s]

Reports:  61%|██████▏   | 4422/7211 [17:49<09:22,  4.96it/s]

Reports:  61%|██████▏   | 4423/7211 [17:49<09:08,  5.08it/s]

Reports:  61%|██████▏   | 4424/7211 [17:50<09:12,  5.04it/s]

Reports:  61%|██████▏   | 4425/7211 [17:50<09:05,  5.11it/s]

Reports:  61%|██████▏   | 4426/7211 [17:50<09:02,  5.13it/s]

Reports:  61%|██████▏   | 4427/7211 [17:50<08:58,  5.17it/s]

Reports:  61%|██████▏   | 4428/7211 [17:50<08:57,  5.18it/s]

Reports:  61%|██████▏   | 4429/7211 [17:50<08:50,  5.24it/s]

Reports:  61%|██████▏   | 4430/7211 [17:51<08:57,  5.17it/s]

Reports:  61%|██████▏   | 4431/7211 [17:51<08:53,  5.21it/s]

Reports:  61%|██████▏   | 4432/7211 [17:51<08:54,  5.20it/s]

Reports:  61%|██████▏   | 4433/7211 [17:51<08:51,  5.23it/s]

Reports:  61%|██████▏   | 4434/7211 [17:51<08:55,  5.18it/s]

Reports:  62%|██████▏   | 4435/7211 [17:52<08:52,  5.21it/s]

Reports:  62%|██████▏   | 4436/7211 [17:52<08:55,  5.19it/s]

Reports:  62%|██████▏   | 4437/7211 [17:52<08:53,  5.20it/s]

Reports:  62%|██████▏   | 4438/7211 [17:52<08:50,  5.22it/s]

Reports:  62%|██████▏   | 4439/7211 [17:52<09:02,  5.11it/s]

Reports:  62%|██████▏   | 4440/7211 [17:54<24:05,  1.92it/s]

Reports:  62%|██████▏   | 4441/7211 [17:54<19:58,  2.31it/s]

Reports:  62%|██████▏   | 4442/7211 [17:54<16:39,  2.77it/s]

Reports:  62%|██████▏   | 4443/7211 [17:54<14:19,  3.22it/s]

Reports:  62%|██████▏   | 4444/7211 [17:55<12:50,  3.59it/s]

Reports:  62%|██████▏   | 4445/7211 [17:55<11:34,  3.98it/s]

Reports:  62%|██████▏   | 4446/7211 [17:55<10:39,  4.32it/s]

Reports:  62%|██████▏   | 4447/7211 [17:55<10:03,  4.58it/s]

Reports:  62%|██████▏   | 4448/7211 [17:56<17:34,  2.62it/s]

Reports:  62%|██████▏   | 4449/7211 [17:56<15:10,  3.03it/s]

Reports:  62%|██████▏   | 4450/7211 [17:56<13:31,  3.40it/s]

Reports:  62%|██████▏   | 4451/7211 [17:56<12:15,  3.75it/s]

Reports:  62%|██████▏   | 4452/7211 [17:57<11:22,  4.04it/s]

Reports:  62%|██████▏   | 4453/7211 [17:57<10:47,  4.26it/s]

Reports:  62%|██████▏   | 4454/7211 [17:57<10:18,  4.46it/s]

Reports:  62%|██████▏   | 4455/7211 [17:57<10:05,  4.55it/s]

Reports:  62%|██████▏   | 4456/7211 [17:57<09:54,  4.64it/s]

Reports:  62%|██████▏   | 4457/7211 [17:58<09:29,  4.84it/s]

Reports:  62%|██████▏   | 4458/7211 [17:58<09:14,  4.96it/s]

Reports:  62%|██████▏   | 4459/7211 [17:58<09:25,  4.86it/s]

Reports:  62%|██████▏   | 4460/7211 [17:58<09:38,  4.76it/s]

Reports:  62%|██████▏   | 4461/7211 [17:59<09:23,  4.88it/s]

Reports:  62%|██████▏   | 4462/7211 [17:59<09:19,  4.91it/s]

Reports:  62%|██████▏   | 4463/7211 [17:59<09:12,  4.97it/s]

Reports:  62%|██████▏   | 4464/7211 [17:59<09:21,  4.89it/s]

Reports:  62%|██████▏   | 4465/7211 [17:59<09:21,  4.89it/s]

Reports:  62%|██████▏   | 4466/7211 [18:00<09:20,  4.90it/s]

Reports:  62%|██████▏   | 4467/7211 [18:00<09:10,  4.98it/s]

Reports:  62%|██████▏   | 4468/7211 [18:00<09:01,  5.06it/s]

Reports:  62%|██████▏   | 4469/7211 [18:00<13:58,  3.27it/s]

Reports:  62%|██████▏   | 4470/7211 [18:01<12:29,  3.66it/s]

Reports:  62%|██████▏   | 4471/7211 [18:01<11:22,  4.01it/s]

Reports:  62%|██████▏   | 4472/7211 [18:01<10:30,  4.35it/s]

Reports:  62%|██████▏   | 4473/7211 [18:01<10:00,  4.56it/s]

Reports:  62%|██████▏   | 4474/7211 [18:01<09:49,  4.64it/s]

Reports:  62%|██████▏   | 4475/7211 [18:02<09:38,  4.73it/s]

Reports:  62%|██████▏   | 4476/7211 [18:02<09:16,  4.91it/s]

Reports:  62%|██████▏   | 4477/7211 [18:02<09:02,  5.04it/s]

Reports:  62%|██████▏   | 4478/7211 [18:02<09:17,  4.90it/s]

Reports:  62%|██████▏   | 4479/7211 [18:02<09:16,  4.91it/s]

Reports:  62%|██████▏   | 4480/7211 [18:03<09:14,  4.92it/s]

Reports:  62%|██████▏   | 4481/7211 [18:03<09:28,  4.80it/s]

Reports:  62%|██████▏   | 4482/7211 [18:03<12:52,  3.53it/s]

Reports:  62%|██████▏   | 4483/7211 [18:03<11:37,  3.91it/s]

Reports:  62%|██████▏   | 4484/7211 [18:04<10:44,  4.23it/s]

Reports:  62%|██████▏   | 4485/7211 [18:04<10:04,  4.51it/s]

Reports:  62%|██████▏   | 4486/7211 [18:04<09:42,  4.68it/s]

Reports:  62%|██████▏   | 4487/7211 [18:04<09:21,  4.85it/s]

Reports:  62%|██████▏   | 4488/7211 [18:04<09:13,  4.92it/s]

Reports:  62%|██████▏   | 4489/7211 [18:05<09:07,  4.97it/s]

Reports:  62%|██████▏   | 4490/7211 [18:05<09:03,  5.01it/s]

Reports:  62%|██████▏   | 4491/7211 [18:05<08:54,  5.09it/s]

Reports:  62%|██████▏   | 4492/7211 [18:05<08:49,  5.14it/s]

Reports:  62%|██████▏   | 4493/7211 [18:05<08:48,  5.14it/s]

Reports:  62%|██████▏   | 4494/7211 [18:06<08:52,  5.11it/s]

Reports:  62%|██████▏   | 4495/7211 [18:06<08:40,  5.21it/s]

Reports:  62%|██████▏   | 4496/7211 [18:06<08:42,  5.19it/s]

Reports:  62%|██████▏   | 4497/7211 [18:06<08:37,  5.25it/s]

Reports:  62%|██████▏   | 4498/7211 [18:06<08:30,  5.31it/s]

Reports:  62%|██████▏   | 4499/7211 [18:07<08:42,  5.19it/s]

Reports:  62%|██████▏   | 4500/7211 [18:07<08:40,  5.21it/s]

Reports:  62%|██████▏   | 4501/7211 [18:07<08:38,  5.22it/s]

Reports:  62%|██████▏   | 4502/7211 [18:07<08:42,  5.18it/s]

Reports:  62%|██████▏   | 4503/7211 [18:08<16:08,  2.80it/s]

Reports:  62%|██████▏   | 4504/7211 [18:08<14:06,  3.20it/s]

Reports:  62%|██████▏   | 4505/7211 [18:08<12:33,  3.59it/s]

Reports:  62%|██████▏   | 4506/7211 [18:08<11:30,  3.92it/s]

Reports:  63%|██████▎   | 4507/7211 [18:09<10:37,  4.24it/s]

Reports:  63%|██████▎   | 4508/7211 [18:09<13:36,  3.31it/s]

Reports:  63%|██████▎   | 4509/7211 [18:09<12:07,  3.71it/s]

Reports:  63%|██████▎   | 4510/7211 [18:10<10:59,  4.09it/s]

Reports:  63%|██████▎   | 4511/7211 [18:10<10:20,  4.35it/s]

Reports:  63%|██████▎   | 4512/7211 [18:10<12:58,  3.47it/s]

Reports:  63%|██████▎   | 4513/7211 [18:10<11:38,  3.86it/s]

Reports:  63%|██████▎   | 4514/7211 [18:11<10:53,  4.13it/s]

Reports:  63%|██████▎   | 4515/7211 [18:11<10:19,  4.35it/s]

Reports:  63%|██████▎   | 4516/7211 [19:11<13:39:38, 18.25s/it]

Reports:  63%|██████▎   | 4517/7211 [19:11<9:36:28, 12.84s/it]

Reports:  63%|██████▎   | 4518/7211 [19:11<6:46:07,  9.05s/it]

Reports:  63%|██████▎   | 4519/7211 [19:12<4:46:42,  6.39s/it]

Reports:  63%|██████▎   | 4520/7211 [19:12<3:23:09,  4.53s/it]

Reports:  63%|██████▎   | 4521/7211 [19:12<2:24:41,  3.23s/it]

Reports:  63%|██████▎   | 4522/7211 [19:12<1:43:49,  2.32s/it]

Reports:  63%|██████▎   | 4523/7211 [19:12<1:15:23,  1.68s/it]

Reports:  63%|██████▎   | 4524/7211 [19:13<55:38,  1.24s/it]

Reports:  63%|██████▎   | 4525/7211 [19:13<41:26,  1.08it/s]

Reports:  63%|██████▎   | 4526/7211 [19:13<31:34,  1.42it/s]

Reports:  63%|██████▎   | 4527/7211 [19:13<24:40,  1.81it/s]

Reports:  63%|██████▎   | 4528/7211 [19:13<19:46,  2.26it/s]

Reports:  63%|██████▎   | 4529/7211 [19:14<16:28,  2.71it/s]

Reports:  63%|██████▎   | 4530/7211 [19:14<14:08,  3.16it/s]

Reports:  63%|██████▎   | 4531/7211 [19:14<12:27,  3.58it/s]

Reports:  63%|██████▎   | 4532/7211 [19:14<11:17,  3.95it/s]

Reports:  63%|██████▎   | 4533/7211 [19:14<10:24,  4.29it/s]

Reports:  63%|██████▎   | 4534/7211 [19:15<09:46,  4.56it/s]

Reports:  63%|██████▎   | 4535/7211 [19:15<09:19,  4.78it/s]

Reports:  63%|██████▎   | 4536/7211 [19:15<10:17,  4.33it/s]

Reports:  63%|██████▎   | 4537/7211 [19:15<09:44,  4.57it/s]

Reports:  63%|██████▎   | 4538/7211 [19:15<09:25,  4.72it/s]

Reports:  63%|██████▎   | 4539/7211 [19:16<09:08,  4.87it/s]

Reports:  63%|██████▎   | 4540/7211 [19:16<09:08,  4.87it/s]

Reports:  63%|██████▎   | 4541/7211 [19:16<08:50,  5.04it/s]

Reports:  63%|██████▎   | 4542/7211 [19:16<08:58,  4.96it/s]

Reports:  63%|██████▎   | 4543/7211 [19:16<08:56,  4.97it/s]

Reports:  63%|██████▎   | 4544/7211 [19:17<08:58,  4.95it/s]

Reports:  63%|██████▎   | 4545/7211 [19:19<42:52,  1.04it/s]

Reports:  63%|██████▎   | 4546/7211 [19:20<32:54,  1.35it/s]

Reports:  63%|██████▎   | 4547/7211 [19:20<25:30,  1.74it/s]

Reports:  63%|██████▎   | 4548/7211 [19:20<20:25,  2.17it/s]

Reports:  63%|██████▎   | 4549/7211 [19:20<16:48,  2.64it/s]

Reports:  63%|██████▎   | 4550/7211 [19:20<14:13,  3.12it/s]

Reports:  63%|██████▎   | 4551/7211 [19:20<12:36,  3.52it/s]

Reports:  63%|██████▎   | 4552/7211 [19:21<11:25,  3.88it/s]

Reports:  63%|██████▎   | 4553/7211 [19:21<10:32,  4.20it/s]

Reports:  63%|██████▎   | 4554/7211 [19:21<09:47,  4.52it/s]

Reports:  63%|██████▎   | 4555/7211 [19:21<09:20,  4.74it/s]

Reports:  63%|██████▎   | 4556/7211 [19:21<09:20,  4.73it/s]

Reports:  63%|██████▎   | 4557/7211 [19:22<08:58,  4.93it/s]

Reports:  63%|██████▎   | 4558/7211 [19:22<09:09,  4.83it/s]

Reports:  63%|██████▎   | 4559/7211 [19:22<09:01,  4.90it/s]

Reports:  63%|██████▎   | 4560/7211 [19:22<08:47,  5.03it/s]

Reports:  63%|██████▎   | 4561/7211 [19:22<08:55,  4.95it/s]

Reports:  63%|██████▎   | 4562/7211 [19:23<08:51,  4.98it/s]

Reports:  63%|██████▎   | 4563/7211 [19:23<09:03,  4.87it/s]

Reports:  63%|██████▎   | 4564/7211 [19:23<09:01,  4.89it/s]

Reports:  63%|██████▎   | 4565/7211 [19:23<08:50,  4.99it/s]

Reports:  63%|██████▎   | 4566/7211 [19:24<12:04,  3.65it/s]

Reports:  63%|██████▎   | 4567/7211 [19:24<11:03,  3.98it/s]

Reports:  63%|██████▎   | 4568/7211 [19:24<10:25,  4.22it/s]

Reports:  63%|██████▎   | 4569/7211 [19:24<09:45,  4.51it/s]

Reports:  63%|██████▎   | 4570/7211 [19:24<09:28,  4.64it/s]

Reports:  63%|██████▎   | 4571/7211 [19:25<09:06,  4.83it/s]

Reports:  63%|██████▎   | 4572/7211 [19:25<08:58,  4.90it/s]

Reports:  63%|██████▎   | 4573/7211 [19:25<08:46,  5.01it/s]

Reports:  63%|██████▎   | 4574/7211 [19:25<11:32,  3.81it/s]

Reports:  63%|██████▎   | 4575/7211 [19:26<10:30,  4.18it/s]

Reports:  63%|██████▎   | 4576/7211 [19:26<09:45,  4.50it/s]

Reports:  63%|██████▎   | 4577/7211 [19:26<09:27,  4.64it/s]

Reports:  63%|██████▎   | 4578/7211 [19:27<12:36,  3.48it/s]

Reports:  64%|██████▎   | 4579/7211 [19:27<11:24,  3.84it/s]

Reports:  64%|██████▎   | 4580/7211 [19:27<10:37,  4.12it/s]

Reports:  64%|██████▎   | 4581/7211 [19:27<09:53,  4.43it/s]

Reports:  64%|██████▎   | 4582/7211 [19:27<09:26,  4.64it/s]

Reports:  64%|██████▎   | 4583/7211 [19:27<09:04,  4.83it/s]

Reports:  64%|██████▎   | 4584/7211 [19:28<12:05,  3.62it/s]

Reports:  64%|██████▎   | 4585/7211 [19:28<11:01,  3.97it/s]

Reports:  64%|██████▎   | 4586/7211 [19:28<10:24,  4.20it/s]

Reports:  64%|██████▎   | 4587/7211 [19:28<09:45,  4.48it/s]

Reports:  64%|██████▎   | 4588/7211 [19:29<09:28,  4.61it/s]

Reports:  64%|██████▎   | 4589/7211 [19:29<09:20,  4.68it/s]

Reports:  64%|██████▎   | 4590/7211 [19:29<09:13,  4.74it/s]

Reports:  64%|██████▎   | 4591/7211 [19:29<09:05,  4.80it/s]

Reports:  64%|██████▎   | 4592/7211 [19:30<08:59,  4.86it/s]

Reports:  64%|██████▎   | 4593/7211 [19:30<08:48,  4.96it/s]

Reports:  64%|██████▎   | 4594/7211 [19:30<08:37,  5.05it/s]

Reports:  64%|██████▎   | 4595/7211 [19:30<08:32,  5.10it/s]

Reports:  64%|██████▎   | 4596/7211 [19:30<08:29,  5.14it/s]

Reports:  64%|██████▎   | 4597/7211 [19:30<08:22,  5.20it/s]

Reports:  64%|██████▍   | 4598/7211 [19:31<08:19,  5.23it/s]

Reports:  64%|██████▍   | 4599/7211 [19:31<08:30,  5.11it/s]

Reports:  64%|██████▍   | 4600/7211 [19:31<08:23,  5.18it/s]

Reports:  64%|██████▍   | 4601/7211 [19:31<09:37,  4.52it/s]

Reports:  64%|██████▍   | 4602/7211 [19:32<09:21,  4.65it/s]

Reports:  64%|██████▍   | 4603/7211 [19:32<09:05,  4.78it/s]

Reports:  64%|██████▍   | 4604/7211 [19:32<08:54,  4.88it/s]

Reports:  64%|██████▍   | 4605/7211 [19:32<10:56,  3.97it/s]

Reports:  64%|██████▍   | 4606/7211 [19:32<10:19,  4.20it/s]

Reports:  64%|██████▍   | 4607/7211 [19:33<09:52,  4.39it/s]

Reports:  64%|██████▍   | 4608/7211 [19:33<09:25,  4.60it/s]

Reports:  64%|██████▍   | 4609/7211 [19:33<09:34,  4.53it/s]

Reports:  64%|██████▍   | 4610/7211 [19:33<09:12,  4.71it/s]

Reports:  64%|██████▍   | 4611/7211 [19:34<09:04,  4.77it/s]

Reports:  64%|██████▍   | 4612/7211 [19:34<08:55,  4.85it/s]

Reports:  64%|██████▍   | 4613/7211 [19:34<08:56,  4.84it/s]

Reports:  64%|██████▍   | 4614/7211 [19:34<08:53,  4.87it/s]

Reports:  64%|██████▍   | 4615/7211 [19:34<08:52,  4.87it/s]

Reports:  64%|██████▍   | 4616/7211 [19:35<08:58,  4.82it/s]

Reports:  64%|██████▍   | 4617/7211 [19:35<08:47,  4.92it/s]

Reports:  64%|██████▍   | 4618/7211 [19:35<08:45,  4.94it/s]

Reports:  64%|██████▍   | 4619/7211 [19:35<08:46,  4.92it/s]

Reports:  64%|██████▍   | 4620/7211 [19:35<08:33,  5.05it/s]

Reports:  64%|██████▍   | 4621/7211 [19:36<08:23,  5.14it/s]

Reports:  64%|██████▍   | 4622/7211 [19:36<08:21,  5.17it/s]

Reports:  64%|██████▍   | 4623/7211 [19:36<08:15,  5.22it/s]

Reports:  64%|██████▍   | 4624/7211 [19:36<08:11,  5.27it/s]

Reports:  64%|██████▍   | 4625/7211 [19:36<08:14,  5.23it/s]

Reports:  64%|██████▍   | 4626/7211 [19:36<08:09,  5.28it/s]

Reports:  64%|██████▍   | 4627/7211 [19:37<08:08,  5.29it/s]

Reports:  64%|██████▍   | 4628/7211 [19:37<08:20,  5.16it/s]

Reports:  64%|██████▍   | 4629/7211 [19:37<08:29,  5.07it/s]

Reports:  64%|██████▍   | 4630/7211 [19:37<08:35,  5.00it/s]

Reports:  64%|██████▍   | 4631/7211 [19:37<08:28,  5.07it/s]

Reports:  64%|██████▍   | 4632/7211 [19:38<08:22,  5.13it/s]

Reports:  64%|██████▍   | 4633/7211 [19:38<08:35,  5.01it/s]

Reports:  64%|██████▍   | 4634/7211 [19:38<09:34,  4.48it/s]

Reports:  64%|██████▍   | 4635/7211 [19:38<10:07,  4.24it/s]

Reports:  64%|██████▍   | 4636/7211 [19:39<10:15,  4.18it/s]

Reports:  64%|██████▍   | 4637/7211 [19:39<10:30,  4.08it/s]

Reports:  64%|██████▍   | 4638/7211 [19:39<10:24,  4.12it/s]

Reports:  64%|██████▍   | 4639/7211 [19:39<09:42,  4.42it/s]

Reports:  64%|██████▍   | 4640/7211 [19:40<09:18,  4.60it/s]

Reports:  64%|██████▍   | 4641/7211 [19:40<08:55,  4.80it/s]

Reports:  64%|██████▍   | 4642/7211 [19:40<08:40,  4.93it/s]

Reports:  64%|██████▍   | 4643/7211 [19:40<08:29,  5.04it/s]

Reports:  64%|██████▍   | 4644/7211 [19:40<08:39,  4.94it/s]

Reports:  64%|██████▍   | 4645/7211 [19:40<08:32,  5.00it/s]

Reports:  64%|██████▍   | 4646/7211 [19:41<08:28,  5.05it/s]

Reports:  64%|██████▍   | 4647/7211 [19:41<08:23,  5.09it/s]

Reports:  64%|██████▍   | 4648/7211 [19:41<08:35,  4.97it/s]

Reports:  64%|██████▍   | 4649/7211 [19:41<08:36,  4.96it/s]

Reports:  64%|██████▍   | 4650/7211 [19:41<08:27,  5.04it/s]

Reports:  64%|██████▍   | 4651/7211 [19:42<08:30,  5.01it/s]

Reports:  65%|██████▍   | 4652/7211 [19:42<08:22,  5.09it/s]

Reports:  65%|██████▍   | 4653/7211 [19:42<08:24,  5.07it/s]

Reports:  65%|██████▍   | 4654/7211 [19:42<08:27,  5.04it/s]

Reports:  65%|██████▍   | 4655/7211 [19:42<08:32,  4.99it/s]

Reports:  65%|██████▍   | 4656/7211 [19:43<08:35,  4.95it/s]

Reports:  65%|██████▍   | 4657/7211 [19:43<08:39,  4.91it/s]

Reports:  65%|██████▍   | 4658/7211 [19:43<08:26,  5.05it/s]

Reports:  65%|██████▍   | 4659/7211 [19:43<08:28,  5.02it/s]

Reports:  65%|██████▍   | 4660/7211 [19:43<08:18,  5.12it/s]

Reports:  65%|██████▍   | 4661/7211 [19:44<08:16,  5.14it/s]

Reports:  65%|██████▍   | 4662/7211 [19:44<08:12,  5.18it/s]

Reports:  65%|██████▍   | 4663/7211 [19:44<08:08,  5.22it/s]

Reports:  65%|██████▍   | 4664/7211 [19:44<08:16,  5.13it/s]

Reports:  65%|██████▍   | 4665/7211 [19:44<08:25,  5.03it/s]

Reports:  65%|██████▍   | 4666/7211 [19:45<08:22,  5.07it/s]

Reports:  65%|██████▍   | 4667/7211 [19:45<08:21,  5.07it/s]

Reports:  65%|██████▍   | 4668/7211 [19:45<08:17,  5.11it/s]

Reports:  65%|██████▍   | 4669/7211 [19:45<08:15,  5.13it/s]

Reports:  65%|██████▍   | 4670/7211 [19:45<08:13,  5.15it/s]

Reports:  65%|██████▍   | 4671/7211 [19:46<08:18,  5.09it/s]

Reports:  65%|██████▍   | 4672/7211 [19:46<08:21,  5.06it/s]

Reports:  65%|██████▍   | 4673/7211 [19:46<08:21,  5.06it/s]

Reports:  65%|██████▍   | 4674/7211 [19:46<08:12,  5.15it/s]

Reports:  65%|██████▍   | 4675/7211 [19:46<08:15,  5.12it/s]

Reports:  65%|██████▍   | 4676/7211 [19:47<08:24,  5.03it/s]

Reports:  65%|██████▍   | 4677/7211 [19:47<08:19,  5.08it/s]

Reports:  65%|██████▍   | 4678/7211 [19:47<08:16,  5.10it/s]

Reports:  65%|██████▍   | 4679/7211 [19:47<08:10,  5.16it/s]

Reports:  65%|██████▍   | 4680/7211 [19:47<08:10,  5.16it/s]

Reports:  65%|██████▍   | 4681/7211 [19:48<08:21,  5.05it/s]

Reports:  65%|██████▍   | 4682/7211 [19:48<08:17,  5.08it/s]

Reports:  65%|██████▍   | 4683/7211 [19:48<08:13,  5.13it/s]

Reports:  65%|██████▍   | 4684/7211 [19:48<08:09,  5.17it/s]

Reports:  65%|██████▍   | 4685/7211 [19:48<08:04,  5.21it/s]

Reports:  65%|██████▍   | 4686/7211 [19:49<08:09,  5.16it/s]

Reports:  65%|██████▍   | 4687/7211 [19:49<08:21,  5.03it/s]

Reports:  65%|██████▌   | 4688/7211 [19:49<08:11,  5.13it/s]

Reports:  65%|██████▌   | 4689/7211 [19:49<08:12,  5.12it/s]

Reports:  65%|██████▌   | 4690/7211 [19:49<08:06,  5.18it/s]

Reports:  65%|██████▌   | 4691/7211 [19:50<08:11,  5.12it/s]

Reports:  65%|██████▌   | 4692/7211 [19:50<08:16,  5.08it/s]

Reports:  65%|██████▌   | 4693/7211 [19:50<08:06,  5.17it/s]

Reports:  65%|██████▌   | 4694/7211 [19:50<08:12,  5.11it/s]

Reports:  65%|██████▌   | 4695/7211 [19:50<08:10,  5.13it/s]

Reports:  65%|██████▌   | 4696/7211 [19:50<08:08,  5.15it/s]

Reports:  65%|██████▌   | 4697/7211 [19:51<07:58,  5.25it/s]

Reports:  65%|██████▌   | 4698/7211 [19:51<08:05,  5.17it/s]

Reports:  65%|██████▌   | 4699/7211 [19:51<08:01,  5.22it/s]

Reports:  65%|██████▌   | 4700/7211 [19:51<08:04,  5.18it/s]

Reports:  65%|██████▌   | 4701/7211 [19:51<08:05,  5.17it/s]

Reports:  65%|██████▌   | 4702/7211 [19:52<08:04,  5.18it/s]

Reports:  65%|██████▌   | 4703/7211 [19:52<08:18,  5.04it/s]

Reports:  65%|██████▌   | 4704/7211 [19:52<08:15,  5.06it/s]

Reports:  65%|██████▌   | 4705/7211 [19:52<08:16,  5.05it/s]

Reports:  65%|██████▌   | 4706/7211 [19:52<08:08,  5.13it/s]

Reports:  65%|██████▌   | 4707/7211 [19:53<08:16,  5.04it/s]

Reports:  65%|██████▌   | 4708/7211 [19:53<08:24,  4.96it/s]

Reports:  65%|██████▌   | 4709/7211 [19:53<08:19,  5.01it/s]

Reports:  65%|██████▌   | 4710/7211 [19:53<08:25,  4.95it/s]

Reports:  65%|██████▌   | 4711/7211 [19:53<08:12,  5.08it/s]

Reports:  65%|██████▌   | 4712/7211 [19:54<08:16,  5.03it/s]

Reports:  65%|██████▌   | 4713/7211 [19:54<08:18,  5.01it/s]

Reports:  65%|██████▌   | 4714/7211 [19:54<08:18,  5.01it/s]

Reports:  65%|██████▌   | 4715/7211 [19:54<08:37,  4.83it/s]

Reports:  65%|██████▌   | 4716/7211 [19:54<08:21,  4.98it/s]

Reports:  65%|██████▌   | 4717/7211 [19:55<08:20,  4.99it/s]

Reports:  65%|██████▌   | 4718/7211 [19:55<08:08,  5.10it/s]

Reports:  65%|██████▌   | 4719/7211 [19:55<08:12,  5.06it/s]

Reports:  65%|██████▌   | 4720/7211 [19:55<08:08,  5.09it/s]

Reports:  65%|██████▌   | 4721/7211 [19:55<08:12,  5.06it/s]

Reports:  65%|██████▌   | 4722/7211 [19:56<08:04,  5.14it/s]

Reports:  65%|██████▌   | 4723/7211 [19:56<07:59,  5.19it/s]

Reports:  66%|██████▌   | 4724/7211 [19:56<07:51,  5.27it/s]

Reports:  66%|██████▌   | 4725/7211 [19:56<07:49,  5.29it/s]

Reports:  66%|██████▌   | 4726/7211 [19:56<07:49,  5.29it/s]

Reports:  66%|██████▌   | 4727/7211 [19:57<07:54,  5.24it/s]

Reports:  66%|██████▌   | 4728/7211 [19:57<14:13,  2.91it/s]

Reports:  66%|██████▌   | 4729/7211 [19:57<12:18,  3.36it/s]

Reports:  66%|██████▌   | 4730/7211 [19:58<10:53,  3.80it/s]

Reports:  66%|██████▌   | 4731/7211 [19:58<09:57,  4.15it/s]

Reports:  66%|██████▌   | 4732/7211 [19:58<09:22,  4.41it/s]

Reports:  66%|██████▌   | 4733/7211 [19:58<08:54,  4.63it/s]

Reports:  66%|██████▌   | 4734/7211 [19:58<08:46,  4.71it/s]

Reports:  66%|██████▌   | 4735/7211 [19:59<08:41,  4.75it/s]

Reports:  66%|██████▌   | 4736/7211 [19:59<08:24,  4.91it/s]

Reports:  66%|██████▌   | 4737/7211 [19:59<08:12,  5.02it/s]

Reports:  66%|██████▌   | 4738/7211 [19:59<08:20,  4.94it/s]

Reports:  66%|██████▌   | 4739/7211 [19:59<08:22,  4.92it/s]

Reports:  66%|██████▌   | 4740/7211 [20:00<08:18,  4.96it/s]

Reports:  66%|██████▌   | 4741/7211 [20:06<1:19:42,  1.94s/it]

Reports:  66%|██████▌   | 4742/7211 [20:06<58:27,  1.42s/it]

Reports:  66%|██████▌   | 4743/7211 [20:06<43:18,  1.05s/it]

Reports:  66%|██████▌   | 4744/7211 [20:06<32:38,  1.26it/s]

Reports:  66%|██████▌   | 4745/7211 [20:06<25:21,  1.62it/s]

Reports:  66%|██████▌   | 4746/7211 [20:07<20:13,  2.03it/s]

Reports:  66%|██████▌   | 4747/7211 [20:07<16:43,  2.45it/s]

Reports:  66%|██████▌   | 4748/7211 [20:07<14:14,  2.88it/s]

Reports:  66%|██████▌   | 4749/7211 [20:07<13:14,  3.10it/s]

Reports:  66%|██████▌   | 4750/7211 [20:07<11:34,  3.54it/s]

Reports:  66%|██████▌   | 4751/7211 [20:08<10:43,  3.82it/s]

Reports:  66%|██████▌   | 4752/7211 [20:08<09:54,  4.14it/s]

Reports:  66%|██████▌   | 4753/7211 [20:08<09:17,  4.41it/s]

Reports:  66%|██████▌   | 4754/7211 [20:08<08:53,  4.60it/s]

Reports:  66%|██████▌   | 4755/7211 [20:08<08:33,  4.78it/s]

Reports:  66%|██████▌   | 4756/7211 [20:09<08:26,  4.84it/s]

Reports:  66%|██████▌   | 4757/7211 [20:09<08:21,  4.89it/s]

Reports:  66%|██████▌   | 4758/7211 [20:09<08:13,  4.97it/s]

Reports:  66%|██████▌   | 4759/7211 [20:09<08:01,  5.09it/s]

Reports:  66%|██████▌   | 4760/7211 [20:09<08:06,  5.04it/s]

Reports:  66%|██████▌   | 4761/7211 [20:10<07:58,  5.12it/s]

Reports:  66%|██████▌   | 4762/7211 [20:10<07:55,  5.15it/s]

Reports:  66%|██████▌   | 4763/7211 [20:10<07:54,  5.16it/s]

Reports:  66%|██████▌   | 4764/7211 [20:10<07:53,  5.17it/s]

Reports:  66%|██████▌   | 4765/7211 [20:10<07:49,  5.21it/s]

Reports:  66%|██████▌   | 4766/7211 [20:11<07:45,  5.25it/s]

Reports:  66%|██████▌   | 4767/7211 [20:11<07:51,  5.19it/s]

Reports:  66%|██████▌   | 4768/7211 [20:11<07:49,  5.21it/s]

Reports:  66%|██████▌   | 4769/7211 [20:11<07:55,  5.14it/s]

Reports:  66%|██████▌   | 4770/7211 [20:11<08:11,  4.96it/s]

Reports:  66%|██████▌   | 4771/7211 [20:12<08:04,  5.04it/s]

Reports:  66%|██████▌   | 4772/7211 [20:12<07:57,  5.10it/s]

Reports:  66%|██████▌   | 4773/7211 [20:12<07:58,  5.10it/s]

Reports:  66%|██████▌   | 4774/7211 [20:12<08:02,  5.05it/s]

Reports:  66%|██████▌   | 4775/7211 [20:12<08:05,  5.02it/s]

Reports:  66%|██████▌   | 4776/7211 [20:13<07:57,  5.10it/s]

Reports:  66%|██████▌   | 4777/7211 [20:13<07:54,  5.12it/s]

Reports:  66%|██████▋   | 4778/7211 [20:13<07:59,  5.07it/s]

Reports:  66%|██████▋   | 4779/7211 [20:13<07:55,  5.12it/s]

Reports:  66%|██████▋   | 4780/7211 [20:13<07:58,  5.08it/s]

Reports:  66%|██████▋   | 4781/7211 [20:14<07:55,  5.12it/s]

Reports:  66%|██████▋   | 4782/7211 [20:14<07:56,  5.10it/s]

Reports:  66%|██████▋   | 4783/7211 [20:14<07:49,  5.17it/s]

Reports:  66%|██████▋   | 4784/7211 [20:14<08:03,  5.02it/s]

Reports:  66%|██████▋   | 4785/7211 [20:14<07:58,  5.07it/s]

Reports:  66%|██████▋   | 4786/7211 [20:15<07:49,  5.16it/s]

Reports:  66%|██████▋   | 4787/7211 [20:15<07:48,  5.17it/s]

Reports:  66%|██████▋   | 4788/7211 [20:15<07:48,  5.18it/s]

Reports:  66%|██████▋   | 4789/7211 [20:15<07:47,  5.18it/s]

Reports:  66%|██████▋   | 4790/7211 [20:15<07:42,  5.24it/s]

Reports:  66%|██████▋   | 4791/7211 [20:15<07:41,  5.25it/s]

Reports:  66%|██████▋   | 4792/7211 [20:16<07:48,  5.16it/s]

Reports:  66%|██████▋   | 4793/7211 [20:16<07:40,  5.25it/s]

Reports:  66%|██████▋   | 4794/7211 [20:16<07:43,  5.21it/s]

Reports:  66%|██████▋   | 4795/7211 [20:16<07:45,  5.19it/s]

Reports:  67%|██████▋   | 4796/7211 [20:16<07:49,  5.14it/s]

Reports:  67%|██████▋   | 4797/7211 [20:17<08:05,  4.97it/s]

Reports:  67%|██████▋   | 4798/7211 [20:17<08:06,  4.96it/s]

Reports:  67%|██████▋   | 4799/7211 [20:17<08:06,  4.96it/s]

Reports:  67%|██████▋   | 4800/7211 [20:17<08:00,  5.02it/s]

Reports:  67%|██████▋   | 4801/7211 [20:17<07:59,  5.03it/s]

Reports:  67%|██████▋   | 4802/7211 [20:18<08:03,  4.98it/s]

Reports:  67%|██████▋   | 4803/7211 [20:18<08:10,  4.91it/s]

Reports:  67%|██████▋   | 4804/7211 [20:18<08:02,  4.99it/s]

Reports:  67%|██████▋   | 4805/7211 [20:18<08:02,  4.99it/s]

Reports:  67%|██████▋   | 4806/7211 [20:18<08:12,  4.89it/s]

Reports:  67%|██████▋   | 4807/7211 [20:19<08:55,  4.49it/s]

Reports:  67%|██████▋   | 4808/7211 [20:19<08:30,  4.71it/s]

Reports:  67%|██████▋   | 4809/7211 [20:19<08:20,  4.80it/s]

Reports:  67%|██████▋   | 4810/7211 [20:19<08:02,  4.97it/s]

Reports:  67%|██████▋   | 4811/7211 [20:20<08:00,  4.99it/s]

Reports:  67%|██████▋   | 4812/7211 [20:20<07:54,  5.05it/s]

Reports:  67%|██████▋   | 4813/7211 [20:20<07:52,  5.08it/s]

Reports:  67%|██████▋   | 4814/7211 [20:20<07:45,  5.15it/s]

Reports:  67%|██████▋   | 4815/7211 [20:20<07:45,  5.15it/s]

Reports:  67%|██████▋   | 4816/7211 [20:20<07:48,  5.11it/s]

Reports:  67%|██████▋   | 4817/7211 [20:21<07:45,  5.14it/s]

Reports:  67%|██████▋   | 4818/7211 [20:21<07:50,  5.09it/s]

Reports:  67%|██████▋   | 4819/7211 [20:21<07:49,  5.09it/s]

Reports:  67%|██████▋   | 4820/7211 [20:21<07:46,  5.12it/s]

Reports:  67%|██████▋   | 4821/7211 [20:21<07:41,  5.18it/s]

Reports:  67%|██████▋   | 4822/7211 [20:22<07:49,  5.09it/s]

Reports:  67%|██████▋   | 4823/7211 [20:22<07:47,  5.11it/s]

Reports:  67%|██████▋   | 4824/7211 [20:22<07:42,  5.16it/s]

Reports:  67%|██████▋   | 4825/7211 [20:22<07:46,  5.11it/s]

Reports:  67%|██████▋   | 4826/7211 [20:22<07:48,  5.09it/s]

Reports:  67%|██████▋   | 4827/7211 [20:23<07:45,  5.13it/s]

Reports:  67%|██████▋   | 4828/7211 [20:23<07:47,  5.10it/s]

Reports:  67%|██████▋   | 4829/7211 [20:23<07:55,  5.01it/s]

Reports:  67%|██████▋   | 4830/7211 [20:23<07:49,  5.07it/s]

Reports:  67%|██████▋   | 4831/7211 [20:23<07:55,  5.00it/s]

Reports:  67%|██████▋   | 4832/7211 [20:24<07:58,  4.97it/s]

Reports:  67%|██████▋   | 4833/7211 [20:24<07:47,  5.09it/s]

Reports:  67%|██████▋   | 4834/7211 [20:24<07:41,  5.15it/s]

Reports:  67%|██████▋   | 4835/7211 [20:24<07:43,  5.13it/s]

Reports:  67%|██████▋   | 4836/7211 [20:24<07:58,  4.97it/s]

Reports:  67%|██████▋   | 4837/7211 [20:25<07:54,  5.01it/s]

Reports:  67%|██████▋   | 4838/7211 [20:25<07:45,  5.10it/s]

Reports:  67%|██████▋   | 4839/7211 [20:25<07:43,  5.12it/s]

Reports:  67%|██████▋   | 4840/7211 [20:25<07:39,  5.16it/s]

Reports:  67%|██████▋   | 4841/7211 [20:25<07:41,  5.14it/s]

Reports:  67%|██████▋   | 4842/7211 [20:26<09:00,  4.39it/s]

Reports:  67%|██████▋   | 4843/7211 [20:26<08:25,  4.68it/s]

Reports:  67%|██████▋   | 4844/7211 [20:26<08:15,  4.77it/s]

Reports:  67%|██████▋   | 4845/7211 [20:26<08:15,  4.78it/s]

Reports:  67%|██████▋   | 4846/7211 [20:26<08:04,  4.88it/s]

Reports:  67%|██████▋   | 4847/7211 [20:27<07:59,  4.93it/s]

Reports:  67%|██████▋   | 4848/7211 [20:27<07:58,  4.93it/s]

Reports:  67%|██████▋   | 4849/7211 [20:27<07:58,  4.93it/s]

Reports:  67%|██████▋   | 4850/7211 [20:27<07:55,  4.97it/s]

Reports:  67%|██████▋   | 4851/7211 [20:27<07:48,  5.04it/s]

Reports:  67%|██████▋   | 4852/7211 [20:28<07:41,  5.12it/s]

Reports:  67%|██████▋   | 4853/7211 [20:28<07:46,  5.06it/s]

Reports:  67%|██████▋   | 4854/7211 [20:28<07:41,  5.10it/s]

Reports:  67%|██████▋   | 4855/7211 [20:28<07:49,  5.02it/s]

Reports:  67%|██████▋   | 4856/7211 [20:28<07:39,  5.13it/s]

Reports:  67%|██████▋   | 4857/7211 [20:29<07:38,  5.14it/s]

Reports:  67%|██████▋   | 4858/7211 [20:29<07:36,  5.16it/s]

Reports:  67%|██████▋   | 4859/7211 [20:29<07:41,  5.10it/s]

Reports:  67%|██████▋   | 4860/7211 [20:29<07:46,  5.04it/s]

Reports:  67%|██████▋   | 4861/7211 [20:29<07:48,  5.02it/s]

Reports:  67%|██████▋   | 4862/7211 [20:30<07:47,  5.02it/s]

Reports:  67%|██████▋   | 4863/7211 [20:30<07:36,  5.14it/s]

Reports:  67%|██████▋   | 4864/7211 [20:30<07:27,  5.24it/s]

Reports:  67%|██████▋   | 4865/7211 [20:30<07:31,  5.19it/s]

Reports:  67%|██████▋   | 4866/7211 [20:30<07:33,  5.17it/s]

Reports:  67%|██████▋   | 4867/7211 [20:31<07:40,  5.09it/s]

Reports:  68%|██████▊   | 4868/7211 [20:31<07:29,  5.21it/s]

Reports:  68%|██████▊   | 4869/7211 [20:31<07:26,  5.24it/s]

Reports:  68%|██████▊   | 4870/7211 [20:31<07:29,  5.21it/s]

Reports:  68%|██████▊   | 4871/7211 [20:31<07:25,  5.26it/s]

Reports:  68%|██████▊   | 4872/7211 [20:32<07:24,  5.27it/s]

Reports:  68%|██████▊   | 4873/7211 [20:32<07:23,  5.27it/s]

Reports:  68%|██████▊   | 4874/7211 [20:32<07:19,  5.32it/s]

Reports:  68%|██████▊   | 4875/7211 [20:32<07:41,  5.06it/s]

Reports:  68%|██████▊   | 4876/7211 [20:32<07:35,  5.13it/s]

Reports:  68%|██████▊   | 4877/7211 [20:33<07:26,  5.22it/s]

Reports:  68%|██████▊   | 4878/7211 [20:33<07:25,  5.24it/s]

Reports:  68%|██████▊   | 4879/7211 [20:33<07:23,  5.26it/s]

Reports:  68%|██████▊   | 4880/7211 [20:33<07:34,  5.12it/s]

Reports:  68%|██████▊   | 4881/7211 [20:33<07:36,  5.10it/s]

Reports:  68%|██████▊   | 4882/7211 [20:33<07:29,  5.19it/s]

Reports:  68%|██████▊   | 4883/7211 [20:34<07:30,  5.17it/s]

Reports:  68%|██████▊   | 4884/7211 [20:34<07:25,  5.22it/s]

Reports:  68%|██████▊   | 4885/7211 [20:34<07:22,  5.26it/s]

Reports:  68%|██████▊   | 4886/7211 [20:34<07:20,  5.28it/s]

Reports:  68%|██████▊   | 4887/7211 [20:34<07:29,  5.17it/s]

Reports:  68%|██████▊   | 4888/7211 [20:35<07:33,  5.12it/s]

Reports:  68%|██████▊   | 4889/7211 [20:35<07:33,  5.12it/s]

Reports:  68%|██████▊   | 4890/7211 [20:35<07:40,  5.04it/s]

Reports:  68%|██████▊   | 4891/7211 [20:35<08:13,  4.70it/s]

Reports:  68%|██████▊   | 4892/7211 [20:35<07:55,  4.87it/s]

Reports:  68%|██████▊   | 4893/7211 [20:36<07:50,  4.93it/s]

Reports:  68%|██████▊   | 4894/7211 [20:36<08:38,  4.47it/s]

Reports:  68%|██████▊   | 4895/7211 [20:36<08:21,  4.62it/s]

Reports:  68%|██████▊   | 4896/7211 [20:36<07:59,  4.83it/s]

Reports:  68%|██████▊   | 4897/7211 [20:37<07:53,  4.88it/s]

Reports:  68%|██████▊   | 4898/7211 [20:37<07:43,  4.99it/s]

Reports:  68%|██████▊   | 4899/7211 [20:37<07:34,  5.09it/s]

Reports:  68%|██████▊   | 4900/7211 [20:37<07:30,  5.13it/s]

Reports:  68%|██████▊   | 4901/7211 [20:37<07:32,  5.11it/s]

Reports:  68%|██████▊   | 4902/7211 [20:37<07:27,  5.16it/s]

Reports:  68%|██████▊   | 4903/7211 [20:38<07:29,  5.14it/s]

Reports:  68%|██████▊   | 4904/7211 [20:38<07:18,  5.26it/s]

Reports:  68%|██████▊   | 4905/7211 [20:38<07:12,  5.33it/s]

Reports:  68%|██████▊   | 4906/7211 [20:38<07:13,  5.32it/s]

Reports:  68%|██████▊   | 4907/7211 [20:38<07:22,  5.20it/s]

Reports:  68%|██████▊   | 4908/7211 [20:39<07:22,  5.20it/s]

Reports:  68%|██████▊   | 4909/7211 [20:39<07:19,  5.24it/s]

Reports:  68%|██████▊   | 4910/7211 [20:39<07:22,  5.20it/s]

Reports:  68%|██████▊   | 4911/7211 [20:39<07:25,  5.17it/s]

Reports:  68%|██████▊   | 4912/7211 [20:39<07:20,  5.22it/s]

Reports:  68%|██████▊   | 4913/7211 [20:40<07:15,  5.27it/s]

Reports:  68%|██████▊   | 4914/7211 [20:40<07:14,  5.29it/s]

Reports:  68%|██████▊   | 4915/7211 [20:40<07:23,  5.18it/s]

Reports:  68%|██████▊   | 4916/7211 [20:40<07:21,  5.19it/s]

Reports:  68%|██████▊   | 4917/7211 [20:40<07:16,  5.25it/s]

Reports:  68%|██████▊   | 4918/7211 [20:41<07:36,  5.02it/s]

Reports:  68%|██████▊   | 4919/7211 [20:41<07:35,  5.03it/s]

Reports:  68%|██████▊   | 4920/7211 [20:41<07:32,  5.07it/s]

Reports:  68%|██████▊   | 4921/7211 [20:41<07:31,  5.07it/s]

Reports:  68%|██████▊   | 4922/7211 [20:41<07:20,  5.20it/s]

Reports:  68%|██████▊   | 4923/7211 [20:42<07:28,  5.11it/s]

Reports:  68%|██████▊   | 4924/7211 [20:42<07:20,  5.20it/s]

Reports:  68%|██████▊   | 4925/7211 [20:42<07:19,  5.20it/s]

Reports:  68%|██████▊   | 4926/7211 [20:42<07:10,  5.31it/s]

Reports:  68%|██████▊   | 4927/7211 [20:42<07:22,  5.16it/s]

Reports:  68%|██████▊   | 4928/7211 [20:42<07:18,  5.21it/s]

Reports:  68%|██████▊   | 4929/7211 [20:43<07:25,  5.12it/s]

Reports:  68%|██████▊   | 4930/7211 [20:43<07:17,  5.21it/s]

Reports:  68%|██████▊   | 4931/7211 [20:43<07:10,  5.29it/s]

Reports:  68%|██████▊   | 4932/7211 [20:43<07:13,  5.26it/s]

Reports:  68%|██████▊   | 4933/7211 [20:43<07:10,  5.29it/s]

Reports:  68%|██████▊   | 4934/7211 [20:44<07:18,  5.20it/s]

Reports:  68%|██████▊   | 4935/7211 [20:44<07:26,  5.10it/s]

Reports:  68%|██████▊   | 4936/7211 [20:44<07:38,  4.96it/s]

Reports:  68%|██████▊   | 4937/7211 [20:44<07:35,  4.99it/s]

Reports:  68%|██████▊   | 4938/7211 [20:44<07:33,  5.01it/s]

Reports:  68%|██████▊   | 4939/7211 [20:45<07:24,  5.11it/s]

Reports:  69%|██████▊   | 4940/7211 [20:45<07:25,  5.10it/s]

Reports:  69%|██████▊   | 4941/7211 [20:45<07:31,  5.03it/s]

Reports:  69%|██████▊   | 4942/7211 [20:45<07:46,  4.86it/s]

Reports:  69%|██████▊   | 4943/7211 [20:45<07:40,  4.92it/s]

Reports:  69%|██████▊   | 4944/7211 [20:46<07:40,  4.93it/s]

Reports:  69%|██████▊   | 4945/7211 [20:46<07:35,  4.98it/s]

Reports:  69%|██████▊   | 4946/7211 [20:46<07:24,  5.10it/s]

Reports:  69%|██████▊   | 4947/7211 [20:46<07:17,  5.17it/s]

Reports:  69%|██████▊   | 4948/7211 [20:46<07:28,  5.05it/s]

Reports:  69%|██████▊   | 4949/7211 [20:47<13:27,  2.80it/s]

Reports:  69%|██████▊   | 4950/7211 [20:47<11:36,  3.25it/s]

Reports:  69%|██████▊   | 4951/7211 [20:48<10:11,  3.69it/s]

Reports:  69%|██████▊   | 4952/7211 [20:48<09:22,  4.01it/s]

Reports:  69%|██████▊   | 4953/7211 [20:48<08:47,  4.28it/s]

Reports:  69%|██████▊   | 4954/7211 [20:48<08:12,  4.58it/s]

Reports:  69%|██████▊   | 4955/7211 [20:48<07:49,  4.80it/s]

Reports:  69%|██████▊   | 4956/7211 [20:48<07:31,  4.99it/s]

Reports:  69%|██████▊   | 4957/7211 [20:49<07:26,  5.05it/s]

Reports:  69%|██████▉   | 4958/7211 [20:49<07:19,  5.13it/s]

Reports:  69%|██████▉   | 4959/7211 [20:49<07:14,  5.18it/s]

Reports:  69%|██████▉   | 4960/7211 [20:50<13:08,  2.85it/s]

Reports:  69%|██████▉   | 4961/7211 [20:50<11:17,  3.32it/s]

Reports:  69%|██████▉   | 4962/7211 [20:50<10:03,  3.73it/s]

Reports:  69%|██████▉   | 4963/7211 [20:50<09:08,  4.10it/s]

Reports:  69%|██████▉   | 4964/7211 [20:51<10:12,  3.67it/s]

Reports:  69%|██████▉   | 4965/7211 [20:51<09:15,  4.04it/s]

Reports:  69%|██████▉   | 4966/7211 [20:51<08:33,  4.37it/s]

Reports:  69%|██████▉   | 4967/7211 [20:51<08:07,  4.60it/s]

Reports:  69%|██████▉   | 4968/7211 [20:51<07:55,  4.72it/s]

Reports:  69%|██████▉   | 4969/7211 [20:52<07:39,  4.88it/s]

Reports:  69%|██████▉   | 4970/7211 [20:52<07:40,  4.87it/s]

Reports:  69%|██████▉   | 4971/7211 [20:52<07:29,  4.98it/s]

Reports:  69%|██████▉   | 4972/7211 [20:52<07:20,  5.09it/s]

Reports:  69%|██████▉   | 4973/7211 [20:52<07:17,  5.11it/s]

Reports:  69%|██████▉   | 4974/7211 [20:53<07:18,  5.10it/s]

Reports:  69%|██████▉   | 4975/7211 [20:53<07:12,  5.17it/s]

Reports:  69%|██████▉   | 4976/7211 [20:53<07:03,  5.28it/s]

Reports:  69%|██████▉   | 4977/7211 [20:53<07:03,  5.27it/s]

Reports:  69%|██████▉   | 4978/7211 [20:53<07:04,  5.26it/s]

Reports:  69%|██████▉   | 4979/7211 [20:54<07:02,  5.28it/s]

Reports:  69%|██████▉   | 4980/7211 [20:54<07:11,  5.18it/s]

Reports:  69%|██████▉   | 4981/7211 [20:54<07:03,  5.26it/s]

Reports:  69%|██████▉   | 4982/7211 [20:54<07:08,  5.20it/s]

Reports:  69%|██████▉   | 4983/7211 [20:54<07:10,  5.17it/s]

Reports:  69%|██████▉   | 4984/7211 [20:55<07:16,  5.10it/s]

Reports:  69%|██████▉   | 4985/7211 [20:55<07:10,  5.17it/s]

Reports:  69%|██████▉   | 4986/7211 [20:55<07:05,  5.23it/s]

Reports:  69%|██████▉   | 4987/7211 [20:55<07:10,  5.16it/s]

Reports:  69%|██████▉   | 4988/7211 [20:55<07:04,  5.24it/s]

Reports:  69%|██████▉   | 4989/7211 [20:55<06:59,  5.30it/s]

Reports:  69%|██████▉   | 4990/7211 [20:56<07:05,  5.22it/s]

Reports:  69%|██████▉   | 4991/7211 [20:56<07:03,  5.24it/s]

Reports:  69%|██████▉   | 4992/7211 [20:56<06:58,  5.30it/s]

Reports:  69%|██████▉   | 4993/7211 [20:56<07:02,  5.25it/s]

Reports:  69%|██████▉   | 4994/7211 [20:56<07:12,  5.13it/s]

Reports:  69%|██████▉   | 4995/7211 [20:57<07:17,  5.07it/s]

Reports:  69%|██████▉   | 4996/7211 [20:57<07:12,  5.12it/s]

Reports:  69%|██████▉   | 4997/7211 [20:57<07:04,  5.22it/s]

Reports:  69%|██████▉   | 4998/7211 [20:57<07:10,  5.13it/s]

Reports:  69%|██████▉   | 4999/7211 [20:57<07:09,  5.15it/s]

Reports:  69%|██████▉   | 5000/7211 [20:58<07:09,  5.14it/s]

Reports:  69%|██████▉   | 5001/7211 [20:58<07:03,  5.22it/s]

Reports:  69%|██████▉   | 5002/7211 [20:58<07:00,  5.25it/s]

Reports:  69%|██████▉   | 5003/7211 [20:58<07:14,  5.08it/s]

Reports:  69%|██████▉   | 5004/7211 [20:58<07:14,  5.08it/s]

Reports:  69%|██████▉   | 5005/7211 [20:59<07:04,  5.20it/s]

Reports:  69%|██████▉   | 5006/7211 [20:59<07:00,  5.24it/s]

Reports:  69%|██████▉   | 5007/7211 [20:59<06:57,  5.28it/s]

Reports:  69%|██████▉   | 5008/7211 [20:59<06:58,  5.26it/s]

Reports:  69%|██████▉   | 5009/7211 [20:59<08:13,  4.46it/s]

Reports:  69%|██████▉   | 5010/7211 [21:00<07:58,  4.60it/s]

Reports:  69%|██████▉   | 5011/7211 [21:00<07:49,  4.69it/s]

Reports:  70%|██████▉   | 5012/7211 [21:00<07:39,  4.79it/s]

Reports:  70%|██████▉   | 5013/7211 [21:00<07:39,  4.78it/s]

Reports:  70%|██████▉   | 5014/7211 [21:00<07:35,  4.82it/s]

Reports:  70%|██████▉   | 5015/7211 [21:01<07:38,  4.79it/s]

Reports:  70%|██████▉   | 5016/7211 [21:01<07:25,  4.93it/s]

Reports:  70%|██████▉   | 5017/7211 [21:01<07:16,  5.02it/s]

Reports:  70%|██████▉   | 5018/7211 [21:01<07:10,  5.10it/s]

Reports:  70%|██████▉   | 5019/7211 [21:01<07:11,  5.08it/s]

Reports:  70%|██████▉   | 5020/7211 [21:02<07:06,  5.14it/s]

Reports:  70%|██████▉   | 5021/7211 [21:02<07:00,  5.21it/s]

Reports:  70%|██████▉   | 5022/7211 [21:02<07:06,  5.13it/s]

Reports:  70%|██████▉   | 5023/7211 [21:06<51:26,  1.41s/it]

Reports:  70%|██████▉   | 5024/7211 [21:06<38:01,  1.04s/it]

Reports:  70%|██████▉   | 5025/7211 [21:07<28:51,  1.26it/s]

Reports:  70%|██████▉   | 5026/7211 [21:07<22:22,  1.63it/s]

Reports:  70%|██████▉   | 5027/7211 [21:07<17:44,  2.05it/s]

Reports:  70%|██████▉   | 5028/7211 [21:07<14:30,  2.51it/s]

Reports:  70%|██████▉   | 5029/7211 [21:07<12:20,  2.95it/s]

Reports:  70%|██████▉   | 5030/7211 [21:08<10:51,  3.35it/s]

Reports:  70%|██████▉   | 5031/7211 [21:08<09:53,  3.67it/s]

Reports:  70%|██████▉   | 5032/7211 [21:08<09:04,  4.00it/s]

Reports:  70%|██████▉   | 5033/7211 [21:08<08:32,  4.25it/s]

Reports:  70%|██████▉   | 5034/7211 [21:08<08:11,  4.43it/s]

Reports:  70%|██████▉   | 5035/7211 [21:09<08:02,  4.51it/s]

Reports:  70%|██████▉   | 5036/7211 [21:09<07:48,  4.65it/s]

Reports:  70%|██████▉   | 5037/7211 [21:09<07:36,  4.76it/s]

Reports:  70%|██████▉   | 5038/7211 [21:09<07:19,  4.94it/s]

Reports:  70%|██████▉   | 5039/7211 [21:09<07:23,  4.90it/s]

Reports:  70%|██████▉   | 5040/7211 [21:10<07:20,  4.93it/s]

Reports:  70%|██████▉   | 5041/7211 [21:10<07:22,  4.91it/s]

Reports:  70%|██████▉   | 5042/7211 [21:10<07:17,  4.95it/s]

Reports:  70%|██████▉   | 5043/7211 [21:10<07:13,  5.00it/s]

Reports:  70%|██████▉   | 5044/7211 [21:10<07:11,  5.02it/s]

Reports:  70%|██████▉   | 5045/7211 [21:11<07:14,  4.98it/s]

Reports:  70%|██████▉   | 5046/7211 [21:11<07:16,  4.96it/s]

Reports:  70%|██████▉   | 5047/7211 [21:11<07:09,  5.04it/s]

Reports:  70%|███████   | 5048/7211 [21:11<07:12,  5.01it/s]

Reports:  70%|███████   | 5049/7211 [21:11<07:11,  5.01it/s]

Reports:  70%|███████   | 5050/7211 [21:12<07:03,  5.11it/s]

Reports:  70%|███████   | 5051/7211 [21:12<07:11,  5.01it/s]

Reports:  70%|███████   | 5052/7211 [21:12<07:06,  5.06it/s]

Reports:  70%|███████   | 5053/7211 [21:12<07:07,  5.05it/s]

Reports:  70%|███████   | 5054/7211 [21:12<07:07,  5.05it/s]

Reports:  70%|███████   | 5055/7211 [21:13<07:03,  5.09it/s]

Reports:  70%|███████   | 5056/7211 [21:13<06:57,  5.16it/s]

Reports:  70%|███████   | 5057/7211 [21:13<06:55,  5.18it/s]

Reports:  70%|███████   | 5058/7211 [21:13<06:49,  5.25it/s]

Reports:  70%|███████   | 5059/7211 [21:13<06:47,  5.28it/s]

Reports:  70%|███████   | 5060/7211 [21:14<06:46,  5.30it/s]

Reports:  70%|███████   | 5061/7211 [21:14<06:53,  5.20it/s]

Reports:  70%|███████   | 5062/7211 [21:14<07:00,  5.12it/s]

Reports:  70%|███████   | 5063/7211 [21:14<07:01,  5.09it/s]

Reports:  70%|███████   | 5064/7211 [21:14<07:09,  5.00it/s]

Reports:  70%|███████   | 5065/7211 [21:15<07:10,  4.99it/s]

Reports:  70%|███████   | 5066/7211 [21:15<07:01,  5.09it/s]

Reports:  70%|███████   | 5067/7211 [21:15<06:57,  5.14it/s]

Reports:  70%|███████   | 5068/7211 [21:15<06:55,  5.15it/s]

Reports:  70%|███████   | 5069/7211 [21:15<06:55,  5.16it/s]

Reports:  70%|███████   | 5070/7211 [21:16<07:00,  5.09it/s]

Reports:  70%|███████   | 5071/7211 [21:16<06:57,  5.13it/s]

Reports:  70%|███████   | 5072/7211 [21:16<07:00,  5.08it/s]

Reports:  70%|███████   | 5073/7211 [21:16<06:58,  5.10it/s]

Reports:  70%|███████   | 5074/7211 [21:16<06:54,  5.16it/s]

Reports:  70%|███████   | 5075/7211 [21:17<06:53,  5.17it/s]

Reports:  70%|███████   | 5076/7211 [21:17<08:21,  4.26it/s]

Reports:  70%|███████   | 5077/7211 [21:17<07:52,  4.51it/s]

Reports:  70%|███████   | 5078/7211 [21:17<07:29,  4.75it/s]

Reports:  70%|███████   | 5079/7211 [21:17<07:25,  4.78it/s]

Reports:  70%|███████   | 5080/7211 [21:19<17:42,  2.01it/s]

Reports:  70%|███████   | 5081/7211 [21:19<14:32,  2.44it/s]

Reports:  70%|███████   | 5082/7211 [21:19<12:15,  2.89it/s]

Reports:  70%|███████   | 5083/7211 [21:19<10:48,  3.28it/s]

Reports:  71%|███████   | 5084/7211 [21:19<09:55,  3.57it/s]

Reports:  71%|███████   | 5085/7211 [21:20<09:04,  3.90it/s]

Reports:  71%|███████   | 5086/7211 [21:20<08:23,  4.22it/s]

Reports:  71%|███████   | 5087/7211 [21:20<07:54,  4.48it/s]

Reports:  71%|███████   | 5088/7211 [21:20<07:26,  4.76it/s]

Reports:  71%|███████   | 5089/7211 [21:20<07:09,  4.94it/s]

Reports:  71%|███████   | 5090/7211 [21:21<07:02,  5.02it/s]

Reports:  71%|███████   | 5091/7211 [21:21<06:54,  5.12it/s]

Reports:  71%|███████   | 5092/7211 [21:21<09:35,  3.68it/s]

Reports:  71%|███████   | 5093/7211 [21:21<08:45,  4.03it/s]

Reports:  71%|███████   | 5094/7211 [21:22<08:12,  4.30it/s]

Reports:  71%|███████   | 5095/7211 [21:22<07:38,  4.61it/s]

Reports:  71%|███████   | 5096/7211 [21:22<07:22,  4.78it/s]

Reports:  71%|███████   | 5097/7211 [21:22<07:08,  4.93it/s]

Reports:  71%|███████   | 5098/7211 [21:22<06:59,  5.04it/s]

Reports:  71%|███████   | 5099/7211 [21:23<06:54,  5.10it/s]

Reports:  71%|███████   | 5100/7211 [21:23<06:51,  5.13it/s]

Reports:  71%|███████   | 5101/7211 [21:23<06:50,  5.14it/s]

Reports:  71%|███████   | 5102/7211 [21:23<06:45,  5.21it/s]

Reports:  71%|███████   | 5103/7211 [21:23<06:35,  5.33it/s]

Reports:  71%|███████   | 5104/7211 [21:23<06:36,  5.32it/s]

Reports:  71%|███████   | 5105/7211 [21:24<06:41,  5.25it/s]

Reports:  71%|███████   | 5106/7211 [21:24<06:43,  5.22it/s]

Reports:  71%|███████   | 5107/7211 [21:24<06:41,  5.25it/s]

Reports:  71%|███████   | 5108/7211 [21:24<06:42,  5.22it/s]

Reports:  71%|███████   | 5109/7211 [21:24<06:55,  5.06it/s]

Reports:  71%|███████   | 5110/7211 [21:25<07:00,  5.00it/s]

Reports:  71%|███████   | 5111/7211 [21:25<06:51,  5.11it/s]

Reports:  71%|███████   | 5112/7211 [21:25<06:43,  5.20it/s]

Reports:  71%|███████   | 5113/7211 [21:25<06:43,  5.20it/s]

Reports:  71%|███████   | 5114/7211 [21:25<06:51,  5.09it/s]

Reports:  71%|███████   | 5115/7211 [21:26<06:57,  5.02it/s]

Reports:  71%|███████   | 5116/7211 [21:26<06:49,  5.12it/s]

Reports:  71%|███████   | 5117/7211 [21:26<06:43,  5.19it/s]

Reports:  71%|███████   | 5118/7211 [21:26<06:40,  5.22it/s]

Reports:  71%|███████   | 5119/7211 [21:26<06:50,  5.09it/s]

Reports:  71%|███████   | 5120/7211 [21:27<06:58,  5.00it/s]

Reports:  71%|███████   | 5121/7211 [21:27<06:52,  5.07it/s]

Reports:  71%|███████   | 5122/7211 [21:27<06:44,  5.17it/s]

Reports:  71%|███████   | 5123/7211 [21:27<08:19,  4.18it/s]

Reports:  71%|███████   | 5124/7211 [21:28<07:58,  4.36it/s]

Reports:  71%|███████   | 5125/7211 [21:28<07:32,  4.61it/s]

Reports:  71%|███████   | 5126/7211 [21:28<07:17,  4.77it/s]

Reports:  71%|███████   | 5127/7211 [21:28<08:27,  4.10it/s]

Reports:  71%|███████   | 5128/7211 [21:28<07:55,  4.39it/s]

Reports:  71%|███████   | 5129/7211 [21:29<07:35,  4.57it/s]

Reports:  71%|███████   | 5130/7211 [21:29<07:26,  4.66it/s]

Reports:  71%|███████   | 5131/7211 [21:29<07:24,  4.68it/s]

Reports:  71%|███████   | 5132/7211 [21:29<07:18,  4.74it/s]

Reports:  71%|███████   | 5133/7211 [21:29<07:11,  4.82it/s]

Reports:  71%|███████   | 5134/7211 [21:30<06:56,  4.99it/s]

Reports:  71%|███████   | 5135/7211 [21:30<07:43,  4.48it/s]

Reports:  71%|███████   | 5136/7211 [21:30<07:23,  4.67it/s]

Reports:  71%|███████   | 5137/7211 [21:30<07:12,  4.79it/s]

Reports:  71%|███████▏  | 5138/7211 [21:30<06:59,  4.94it/s]

Reports:  71%|███████▏  | 5139/7211 [21:31<06:53,  5.01it/s]

Reports:  71%|███████▏  | 5140/7211 [21:31<06:53,  5.01it/s]

Reports:  71%|███████▏  | 5141/7211 [21:31<06:46,  5.09it/s]

Reports:  71%|███████▏  | 5142/7211 [21:31<06:42,  5.14it/s]

Reports:  71%|███████▏  | 5143/7211 [21:31<06:40,  5.16it/s]

Reports:  71%|███████▏  | 5144/7211 [21:32<06:32,  5.26it/s]

Reports:  71%|███████▏  | 5145/7211 [21:32<08:00,  4.30it/s]

Reports:  71%|███████▏  | 5146/7211 [21:32<07:34,  4.55it/s]

Reports:  71%|███████▏  | 5147/7211 [21:32<07:12,  4.77it/s]

Reports:  71%|███████▏  | 5148/7211 [21:33<07:07,  4.82it/s]

Reports:  71%|███████▏  | 5149/7211 [21:33<06:59,  4.92it/s]

Reports:  71%|███████▏  | 5150/7211 [21:33<06:52,  5.00it/s]

Reports:  71%|███████▏  | 5151/7211 [21:33<06:53,  4.98it/s]

Reports:  71%|███████▏  | 5152/7211 [21:33<06:45,  5.07it/s]

Reports:  71%|███████▏  | 5153/7211 [21:33<06:36,  5.19it/s]

Reports:  71%|███████▏  | 5154/7211 [21:34<06:30,  5.27it/s]

Reports:  71%|███████▏  | 5155/7211 [21:34<06:26,  5.32it/s]

Reports:  72%|███████▏  | 5156/7211 [21:34<06:28,  5.29it/s]

Reports:  72%|███████▏  | 5157/7211 [21:34<06:43,  5.10it/s]

Reports:  72%|███████▏  | 5158/7211 [21:34<06:39,  5.13it/s]

Reports:  72%|███████▏  | 5159/7211 [21:35<06:33,  5.22it/s]

Reports:  72%|███████▏  | 5160/7211 [21:35<06:33,  5.21it/s]

Reports:  72%|███████▏  | 5161/7211 [21:35<06:37,  5.16it/s]

Reports:  72%|███████▏  | 5162/7211 [21:35<06:37,  5.15it/s]

Reports:  72%|███████▏  | 5163/7211 [21:36<07:33,  4.52it/s]

Reports:  72%|███████▏  | 5164/7211 [21:36<07:45,  4.40it/s]

Reports:  72%|███████▏  | 5165/7211 [21:36<07:22,  4.63it/s]

Reports:  72%|███████▏  | 5166/7211 [21:36<07:06,  4.79it/s]

Reports:  72%|███████▏  | 5167/7211 [21:36<06:59,  4.87it/s]

Reports:  72%|███████▏  | 5168/7211 [21:37<06:49,  4.99it/s]

Reports:  72%|███████▏  | 5169/7211 [21:37<06:45,  5.04it/s]

Reports:  72%|███████▏  | 5170/7211 [21:37<06:29,  5.23it/s]

Reports:  72%|███████▏  | 5171/7211 [21:37<06:31,  5.21it/s]

Reports:  72%|███████▏  | 5172/7211 [21:37<06:28,  5.25it/s]

Reports:  72%|███████▏  | 5173/7211 [21:37<06:28,  5.25it/s]

Reports:  72%|███████▏  | 5174/7211 [21:38<06:26,  5.27it/s]

Reports:  72%|███████▏  | 5175/7211 [21:38<06:23,  5.31it/s]

Reports:  72%|███████▏  | 5176/7211 [21:38<06:24,  5.29it/s]

Reports:  72%|███████▏  | 5177/7211 [21:38<06:18,  5.37it/s]

Reports:  72%|███████▏  | 5178/7211 [21:38<06:15,  5.41it/s]

Reports:  72%|███████▏  | 5179/7211 [21:39<06:13,  5.44it/s]

Reports:  72%|███████▏  | 5180/7211 [21:39<06:12,  5.46it/s]

Reports:  72%|███████▏  | 5181/7211 [21:39<06:17,  5.38it/s]

Reports:  72%|███████▏  | 5182/7211 [21:39<06:19,  5.35it/s]

Reports:  72%|███████▏  | 5183/7211 [21:39<06:21,  5.31it/s]

Reports:  72%|███████▏  | 5184/7211 [21:40<06:21,  5.32it/s]

Reports:  72%|███████▏  | 5185/7211 [21:40<06:24,  5.27it/s]

Reports:  72%|███████▏  | 5186/7211 [21:40<06:28,  5.22it/s]

Reports:  72%|███████▏  | 5187/7211 [21:40<06:28,  5.21it/s]

Reports:  72%|███████▏  | 5188/7211 [21:40<06:23,  5.27it/s]

Reports:  72%|███████▏  | 5189/7211 [21:40<06:21,  5.30it/s]

Reports:  72%|███████▏  | 5190/7211 [21:41<06:17,  5.35it/s]

Reports:  72%|███████▏  | 5191/7211 [21:41<06:24,  5.26it/s]

Reports:  72%|███████▏  | 5192/7211 [21:41<06:22,  5.28it/s]

Reports:  72%|███████▏  | 5193/7211 [21:41<06:26,  5.23it/s]

Reports:  72%|███████▏  | 5194/7211 [21:41<06:29,  5.18it/s]

Reports:  72%|███████▏  | 5195/7211 [21:42<07:33,  4.44it/s]

Reports:  72%|███████▏  | 5196/7211 [21:42<07:11,  4.67it/s]

Reports:  72%|███████▏  | 5197/7211 [21:42<06:56,  4.83it/s]

Reports:  72%|███████▏  | 5198/7211 [21:42<06:51,  4.89it/s]

Reports:  72%|███████▏  | 5199/7211 [21:43<06:51,  4.88it/s]

Reports:  72%|███████▏  | 5200/7211 [21:43<06:35,  5.09it/s]

Reports:  72%|███████▏  | 5201/7211 [21:43<06:41,  5.00it/s]

Reports:  72%|███████▏  | 5202/7211 [21:43<06:36,  5.06it/s]

Reports:  72%|███████▏  | 5203/7211 [21:43<06:28,  5.17it/s]

Reports:  72%|███████▏  | 5204/7211 [21:43<06:27,  5.18it/s]

Reports:  72%|███████▏  | 5205/7211 [21:44<06:22,  5.24it/s]

Reports:  72%|███████▏  | 5206/7211 [21:44<06:24,  5.21it/s]

Reports:  72%|███████▏  | 5207/7211 [21:44<06:27,  5.17it/s]

Reports:  72%|███████▏  | 5208/7211 [21:44<06:30,  5.13it/s]

Reports:  72%|███████▏  | 5209/7211 [21:44<06:36,  5.05it/s]

Reports:  72%|███████▏  | 5210/7211 [21:45<06:26,  5.18it/s]

Reports:  72%|███████▏  | 5211/7211 [21:45<06:26,  5.17it/s]

Reports:  72%|███████▏  | 5212/7211 [21:45<06:21,  5.24it/s]

Reports:  72%|███████▏  | 5213/7211 [21:45<06:23,  5.21it/s]

Reports:  72%|███████▏  | 5214/7211 [21:45<06:16,  5.30it/s]

Reports:  72%|███████▏  | 5215/7211 [21:46<06:22,  5.22it/s]

Reports:  72%|███████▏  | 5216/7211 [21:46<06:16,  5.30it/s]

Reports:  72%|███████▏  | 5217/7211 [21:46<06:18,  5.27it/s]

Reports:  72%|███████▏  | 5218/7211 [21:46<06:19,  5.26it/s]

Reports:  72%|███████▏  | 5219/7211 [21:46<06:19,  5.24it/s]

Reports:  72%|███████▏  | 5220/7211 [21:47<06:17,  5.27it/s]

Reports:  72%|███████▏  | 5221/7211 [21:47<06:17,  5.28it/s]

Reports:  72%|███████▏  | 5222/7211 [21:47<06:29,  5.11it/s]

Reports:  72%|███████▏  | 5223/7211 [21:47<07:28,  4.44it/s]

Reports:  72%|███████▏  | 5224/7211 [21:47<07:29,  4.42it/s]

Reports:  72%|███████▏  | 5225/7211 [21:48<07:19,  4.51it/s]

Reports:  72%|███████▏  | 5226/7211 [21:48<07:06,  4.66it/s]

Reports:  72%|███████▏  | 5227/7211 [21:48<06:51,  4.83it/s]

Reports:  73%|███████▎  | 5228/7211 [21:48<06:38,  4.97it/s]

Reports:  73%|███████▎  | 5229/7211 [21:48<06:39,  4.97it/s]

Reports:  73%|███████▎  | 5230/7211 [21:49<06:46,  4.87it/s]

Reports:  73%|███████▎  | 5231/7211 [21:49<06:38,  4.96it/s]

Reports:  73%|███████▎  | 5232/7211 [21:49<06:26,  5.12it/s]

Reports:  73%|███████▎  | 5233/7211 [21:49<06:21,  5.18it/s]

Reports:  73%|███████▎  | 5234/7211 [21:49<06:19,  5.22it/s]

Reports:  73%|███████▎  | 5235/7211 [21:50<06:14,  5.27it/s]

Reports:  73%|███████▎  | 5236/7211 [21:50<06:11,  5.31it/s]

Reports:  73%|███████▎  | 5237/7211 [21:50<06:13,  5.28it/s]

Reports:  73%|███████▎  | 5238/7211 [21:50<06:19,  5.20it/s]

Reports:  73%|███████▎  | 5239/7211 [21:50<06:18,  5.20it/s]

Reports:  73%|███████▎  | 5240/7211 [21:51<06:16,  5.24it/s]

Reports:  73%|███████▎  | 5241/7211 [21:51<06:17,  5.22it/s]

Reports:  73%|███████▎  | 5242/7211 [21:51<06:15,  5.24it/s]

Reports:  73%|███████▎  | 5243/7211 [21:51<06:22,  5.14it/s]

Reports:  73%|███████▎  | 5244/7211 [21:51<06:22,  5.14it/s]

Reports:  73%|███████▎  | 5245/7211 [21:52<06:21,  5.15it/s]

Reports:  73%|███████▎  | 5246/7211 [21:52<06:21,  5.15it/s]

Reports:  73%|███████▎  | 5247/7211 [21:52<06:20,  5.16it/s]

Reports:  73%|███████▎  | 5248/7211 [21:52<06:12,  5.27it/s]

Reports:  73%|███████▎  | 5249/7211 [21:52<06:13,  5.26it/s]

Reports:  73%|███████▎  | 5250/7211 [21:52<06:12,  5.27it/s]

Reports:  73%|███████▎  | 5251/7211 [21:53<06:12,  5.26it/s]

Reports:  73%|███████▎  | 5252/7211 [21:53<06:15,  5.21it/s]

Reports:  73%|███████▎  | 5253/7211 [21:53<06:22,  5.12it/s]

Reports:  73%|███████▎  | 5254/7211 [21:53<06:19,  5.16it/s]

Reports:  73%|███████▎  | 5255/7211 [21:53<06:22,  5.11it/s]

Reports:  73%|███████▎  | 5256/7211 [21:54<06:18,  5.17it/s]

Reports:  73%|███████▎  | 5257/7211 [21:54<06:16,  5.20it/s]

Reports:  73%|███████▎  | 5258/7211 [21:54<06:14,  5.22it/s]

Reports:  73%|███████▎  | 5259/7211 [21:54<06:11,  5.25it/s]

Reports:  73%|███████▎  | 5260/7211 [21:54<06:10,  5.27it/s]

Reports:  73%|███████▎  | 5261/7211 [21:55<06:10,  5.27it/s]

Reports:  73%|███████▎  | 5262/7211 [21:55<06:08,  5.29it/s]

Reports:  73%|███████▎  | 5263/7211 [21:55<06:09,  5.27it/s]

Reports:  73%|███████▎  | 5264/7211 [21:55<06:08,  5.29it/s]

Reports:  73%|███████▎  | 5265/7211 [21:55<06:15,  5.19it/s]

Reports:  73%|███████▎  | 5266/7211 [21:56<06:12,  5.22it/s]

Reports:  73%|███████▎  | 5267/7211 [21:56<06:15,  5.18it/s]

Reports:  73%|███████▎  | 5268/7211 [21:56<06:20,  5.10it/s]

Reports:  73%|███████▎  | 5269/7211 [21:56<06:23,  5.06it/s]

Reports:  73%|███████▎  | 5270/7211 [21:56<06:13,  5.19it/s]

Reports:  73%|███████▎  | 5271/7211 [21:56<06:07,  5.28it/s]

Reports:  73%|███████▎  | 5272/7211 [21:57<06:12,  5.21it/s]

Reports:  73%|███████▎  | 5273/7211 [21:57<06:14,  5.17it/s]

Reports:  73%|███████▎  | 5274/7211 [21:57<06:15,  5.16it/s]

Reports:  73%|███████▎  | 5275/7211 [21:57<06:08,  5.25it/s]

Reports:  73%|███████▎  | 5276/7211 [21:58<08:13,  3.92it/s]

Reports:  73%|███████▎  | 5277/7211 [21:58<07:31,  4.28it/s]

Reports:  73%|███████▎  | 5278/7211 [21:58<07:17,  4.42it/s]

Reports:  73%|███████▎  | 5279/7211 [21:58<07:07,  4.52it/s]

Reports:  73%|███████▎  | 5280/7211 [21:58<06:52,  4.68it/s]

Reports:  73%|███████▎  | 5281/7211 [21:59<06:44,  4.77it/s]

Reports:  73%|███████▎  | 5282/7211 [21:59<06:38,  4.85it/s]

Reports:  73%|███████▎  | 5283/7211 [21:59<06:32,  4.91it/s]

Reports:  73%|███████▎  | 5284/7211 [21:59<06:28,  4.96it/s]

Reports:  73%|███████▎  | 5285/7211 [21:59<06:18,  5.09it/s]

Reports:  73%|███████▎  | 5286/7211 [22:00<06:24,  5.01it/s]

Reports:  73%|███████▎  | 5287/7211 [22:00<06:36,  4.85it/s]

Reports:  73%|███████▎  | 5288/7211 [22:00<06:36,  4.85it/s]

Reports:  73%|███████▎  | 5289/7211 [22:00<06:33,  4.89it/s]

Reports:  73%|███████▎  | 5290/7211 [22:00<06:21,  5.04it/s]

Reports:  73%|███████▎  | 5291/7211 [22:01<06:13,  5.14it/s]

Reports:  73%|███████▎  | 5292/7211 [22:01<06:12,  5.15it/s]

Reports:  73%|███████▎  | 5293/7211 [22:01<06:09,  5.19it/s]

Reports:  73%|███████▎  | 5294/7211 [22:01<06:06,  5.23it/s]

Reports:  73%|███████▎  | 5295/7211 [22:01<06:15,  5.10it/s]

Reports:  73%|███████▎  | 5296/7211 [22:02<06:17,  5.07it/s]

Reports:  73%|███████▎  | 5297/7211 [22:02<06:16,  5.09it/s]

Reports:  73%|███████▎  | 5298/7211 [22:02<06:20,  5.03it/s]

Reports:  73%|███████▎  | 5299/7211 [22:02<06:15,  5.09it/s]

Reports:  73%|███████▎  | 5300/7211 [22:02<06:15,  5.10it/s]

Reports:  74%|███████▎  | 5301/7211 [22:03<06:23,  4.98it/s]

Reports:  74%|███████▎  | 5302/7211 [22:03<06:20,  5.01it/s]

Reports:  74%|███████▎  | 5303/7211 [22:03<06:16,  5.07it/s]

Reports:  74%|███████▎  | 5304/7211 [22:03<06:15,  5.08it/s]

Reports:  74%|███████▎  | 5305/7211 [22:03<06:11,  5.12it/s]

Reports:  74%|███████▎  | 5306/7211 [22:04<06:13,  5.09it/s]

Reports:  74%|███████▎  | 5307/7211 [22:04<06:12,  5.11it/s]

Reports:  74%|███████▎  | 5308/7211 [22:04<06:12,  5.11it/s]

Reports:  74%|███████▎  | 5309/7211 [22:04<06:07,  5.17it/s]

Reports:  74%|███████▎  | 5310/7211 [22:04<06:06,  5.19it/s]

Reports:  74%|███████▎  | 5311/7211 [22:05<06:14,  5.08it/s]

Reports:  74%|███████▎  | 5312/7211 [22:05<06:06,  5.18it/s]

Reports:  74%|███████▎  | 5313/7211 [22:05<06:08,  5.15it/s]

Reports:  74%|███████▎  | 5314/7211 [22:05<06:05,  5.20it/s]

Reports:  74%|███████▎  | 5315/7211 [22:05<06:06,  5.17it/s]

Reports:  74%|███████▎  | 5316/7211 [22:06<06:14,  5.06it/s]

Reports:  74%|███████▎  | 5317/7211 [22:06<06:08,  5.14it/s]

Reports:  74%|███████▎  | 5318/7211 [22:06<06:08,  5.14it/s]

Reports:  74%|███████▍  | 5319/7211 [22:06<06:11,  5.09it/s]

Reports:  74%|███████▍  | 5320/7211 [22:06<06:17,  5.01it/s]

Reports:  74%|███████▍  | 5321/7211 [22:07<06:05,  5.17it/s]

Reports:  74%|███████▍  | 5322/7211 [22:07<06:08,  5.13it/s]

Reports:  74%|███████▍  | 5323/7211 [22:07<06:06,  5.15it/s]

Reports:  74%|███████▍  | 5324/7211 [22:07<06:05,  5.16it/s]

Reports:  74%|███████▍  | 5325/7211 [22:07<05:59,  5.25it/s]

Reports:  74%|███████▍  | 5326/7211 [22:07<05:57,  5.27it/s]

Reports:  74%|███████▍  | 5327/7211 [22:08<06:05,  5.15it/s]

Reports:  74%|███████▍  | 5328/7211 [22:08<06:02,  5.20it/s]

Reports:  74%|███████▍  | 5329/7211 [22:08<05:55,  5.29it/s]

Reports:  74%|███████▍  | 5330/7211 [22:08<05:56,  5.27it/s]

Reports:  74%|███████▍  | 5331/7211 [22:08<05:59,  5.23it/s]

Reports:  74%|███████▍  | 5332/7211 [22:09<06:28,  4.83it/s]

Reports:  74%|███████▍  | 5333/7211 [22:09<06:23,  4.90it/s]

Reports:  74%|███████▍  | 5334/7211 [22:09<06:18,  4.96it/s]

Reports:  74%|███████▍  | 5335/7211 [22:09<06:12,  5.04it/s]

Reports:  74%|███████▍  | 5336/7211 [22:09<06:09,  5.07it/s]

Reports:  74%|███████▍  | 5337/7211 [22:10<06:07,  5.11it/s]

Reports:  74%|███████▍  | 5338/7211 [22:10<06:10,  5.05it/s]

Reports:  74%|███████▍  | 5339/7211 [22:10<06:04,  5.13it/s]

Reports:  74%|███████▍  | 5340/7211 [22:10<06:01,  5.18it/s]

Reports:  74%|███████▍  | 5341/7211 [22:10<06:16,  4.97it/s]

Reports:  74%|███████▍  | 5342/7211 [22:11<06:16,  4.97it/s]

Reports:  74%|███████▍  | 5343/7211 [22:11<06:09,  5.06it/s]

Reports:  74%|███████▍  | 5344/7211 [22:11<06:08,  5.06it/s]

Reports:  74%|███████▍  | 5345/7211 [22:11<06:05,  5.11it/s]

Reports:  74%|███████▍  | 5346/7211 [22:11<06:09,  5.05it/s]

Reports:  74%|███████▍  | 5347/7211 [22:12<06:11,  5.02it/s]

Reports:  74%|███████▍  | 5348/7211 [22:12<06:13,  4.99it/s]

Reports:  74%|███████▍  | 5349/7211 [22:12<06:06,  5.08it/s]

Reports:  74%|███████▍  | 5350/7211 [22:12<06:06,  5.08it/s]

Reports:  74%|███████▍  | 5351/7211 [22:12<06:00,  5.16it/s]

Reports:  74%|███████▍  | 5352/7211 [22:13<05:55,  5.23it/s]

Reports:  74%|███████▍  | 5353/7211 [22:13<06:09,  5.03it/s]

Reports:  74%|███████▍  | 5354/7211 [22:13<06:05,  5.08it/s]

Reports:  74%|███████▍  | 5355/7211 [22:13<06:05,  5.07it/s]

Reports:  74%|███████▍  | 5356/7211 [22:13<06:09,  5.02it/s]

Reports:  74%|███████▍  | 5357/7211 [22:14<06:01,  5.13it/s]

Reports:  74%|███████▍  | 5358/7211 [22:14<06:04,  5.09it/s]

Reports:  74%|███████▍  | 5359/7211 [22:14<06:01,  5.12it/s]

Reports:  74%|███████▍  | 5360/7211 [22:14<06:00,  5.13it/s]

Reports:  74%|███████▍  | 5361/7211 [22:14<06:02,  5.10it/s]

Reports:  74%|███████▍  | 5362/7211 [22:15<05:59,  5.14it/s]

Reports:  74%|███████▍  | 5363/7211 [22:15<06:02,  5.10it/s]

Reports:  74%|███████▍  | 5364/7211 [22:15<06:01,  5.11it/s]

Reports:  74%|███████▍  | 5365/7211 [22:15<05:58,  5.15it/s]

Reports:  74%|███████▍  | 5366/7211 [22:15<06:05,  5.05it/s]

Reports:  74%|███████▍  | 5367/7211 [22:16<06:03,  5.08it/s]

Reports:  74%|███████▍  | 5368/7211 [22:16<05:58,  5.13it/s]

Reports:  74%|███████▍  | 5369/7211 [22:16<05:55,  5.17it/s]

Reports:  74%|███████▍  | 5370/7211 [22:16<05:53,  5.21it/s]

Reports:  74%|███████▍  | 5371/7211 [22:16<05:54,  5.20it/s]

Reports:  74%|███████▍  | 5372/7211 [22:16<05:48,  5.28it/s]

Reports:  75%|███████▍  | 5373/7211 [22:17<05:55,  5.17it/s]

Reports:  75%|███████▍  | 5374/7211 [22:17<06:01,  5.08it/s]

Reports:  75%|███████▍  | 5375/7211 [22:17<05:54,  5.18it/s]

Reports:  75%|███████▍  | 5376/7211 [22:17<05:55,  5.17it/s]

Reports:  75%|███████▍  | 5377/7211 [22:17<05:49,  5.25it/s]

Reports:  75%|███████▍  | 5378/7211 [22:18<05:50,  5.23it/s]

Reports:  75%|███████▍  | 5379/7211 [22:18<05:56,  5.14it/s]

Reports:  75%|███████▍  | 5380/7211 [22:18<05:56,  5.14it/s]

Reports:  75%|███████▍  | 5381/7211 [22:18<06:00,  5.07it/s]

Reports:  75%|███████▍  | 5382/7211 [22:18<05:53,  5.18it/s]

Reports:  75%|███████▍  | 5383/7211 [22:19<05:48,  5.24it/s]

Reports:  75%|███████▍  | 5384/7211 [22:19<05:47,  5.26it/s]

Reports:  75%|███████▍  | 5385/7211 [22:19<05:53,  5.16it/s]

Reports:  75%|███████▍  | 5386/7211 [22:19<05:49,  5.23it/s]

Reports:  75%|███████▍  | 5387/7211 [22:19<05:51,  5.19it/s]

Reports:  75%|███████▍  | 5388/7211 [22:20<05:47,  5.24it/s]

Reports:  75%|███████▍  | 5389/7211 [22:20<05:56,  5.11it/s]

Reports:  75%|███████▍  | 5390/7211 [22:20<06:06,  4.97it/s]

Reports:  75%|███████▍  | 5391/7211 [22:20<06:02,  5.02it/s]

Reports:  75%|███████▍  | 5392/7211 [22:20<05:55,  5.12it/s]

Reports:  75%|███████▍  | 5393/7211 [22:21<05:49,  5.20it/s]

Reports:  75%|███████▍  | 5394/7211 [22:21<05:49,  5.20it/s]

Reports:  75%|███████▍  | 5395/7211 [22:21<05:44,  5.27it/s]

Reports:  75%|███████▍  | 5396/7211 [22:21<05:46,  5.24it/s]

Reports:  75%|███████▍  | 5397/7211 [22:21<05:42,  5.30it/s]

Reports:  75%|███████▍  | 5398/7211 [22:22<05:43,  5.27it/s]

Reports:  75%|███████▍  | 5399/7211 [22:22<05:45,  5.25it/s]

Reports:  75%|███████▍  | 5400/7211 [22:22<05:53,  5.13it/s]

Reports:  75%|███████▍  | 5401/7211 [22:22<05:51,  5.15it/s]

Reports:  75%|███████▍  | 5402/7211 [22:22<05:45,  5.23it/s]

Reports:  75%|███████▍  | 5403/7211 [22:22<05:44,  5.25it/s]

Reports:  75%|███████▍  | 5404/7211 [22:23<05:49,  5.16it/s]

Reports:  75%|███████▍  | 5405/7211 [22:23<05:47,  5.19it/s]

Reports:  75%|███████▍  | 5406/7211 [22:23<05:47,  5.19it/s]

Reports:  75%|███████▍  | 5407/7211 [22:23<05:51,  5.13it/s]

Reports:  75%|███████▍  | 5408/7211 [22:23<05:55,  5.07it/s]

Reports:  75%|███████▌  | 5409/7211 [22:24<06:05,  4.93it/s]

Reports:  75%|███████▌  | 5410/7211 [22:24<06:05,  4.93it/s]

Reports:  75%|███████▌  | 5411/7211 [22:24<05:57,  5.04it/s]

Reports:  75%|███████▌  | 5412/7211 [22:24<05:49,  5.15it/s]

Reports:  75%|███████▌  | 5413/7211 [22:24<05:53,  5.09it/s]

Reports:  75%|███████▌  | 5414/7211 [22:25<05:51,  5.11it/s]

Reports:  75%|███████▌  | 5415/7211 [22:25<05:53,  5.08it/s]

Reports:  75%|███████▌  | 5416/7211 [22:25<05:53,  5.08it/s]

Reports:  75%|███████▌  | 5417/7211 [22:25<05:51,  5.10it/s]

Reports:  75%|███████▌  | 5418/7211 [22:25<05:54,  5.06it/s]

Reports:  75%|███████▌  | 5419/7211 [22:27<15:00,  1.99it/s]

Reports:  75%|███████▌  | 5420/7211 [22:27<12:10,  2.45it/s]

Reports:  75%|███████▌  | 5421/7211 [22:27<10:11,  2.93it/s]

Reports:  75%|███████▌  | 5422/7211 [22:27<08:56,  3.34it/s]

Reports:  75%|███████▌  | 5423/7211 [22:27<07:58,  3.74it/s]

Reports:  75%|███████▌  | 5424/7211 [22:28<07:14,  4.11it/s]

Reports:  75%|███████▌  | 5425/7211 [22:28<06:52,  4.33it/s]

Reports:  75%|███████▌  | 5426/7211 [22:28<06:30,  4.57it/s]

Reports:  75%|███████▌  | 5427/7211 [22:28<06:16,  4.74it/s]

Reports:  75%|███████▌  | 5428/7211 [22:28<06:06,  4.86it/s]

Reports:  75%|███████▌  | 5429/7211 [22:29<06:02,  4.91it/s]

Reports:  75%|███████▌  | 5430/7211 [22:29<06:00,  4.94it/s]

Reports:  75%|███████▌  | 5431/7211 [22:29<05:58,  4.97it/s]

Reports:  75%|███████▌  | 5432/7211 [22:29<05:49,  5.09it/s]

Reports:  75%|███████▌  | 5433/7211 [22:29<05:45,  5.14it/s]

Reports:  75%|███████▌  | 5434/7211 [22:30<05:45,  5.15it/s]

Reports:  75%|███████▌  | 5435/7211 [22:30<05:38,  5.24it/s]

Reports:  75%|███████▌  | 5436/7211 [22:30<05:39,  5.23it/s]

Reports:  75%|███████▌  | 5437/7211 [22:30<05:37,  5.26it/s]

Reports:  75%|███████▌  | 5438/7211 [22:30<05:49,  5.07it/s]

Reports:  75%|███████▌  | 5439/7211 [22:31<05:51,  5.04it/s]

Reports:  75%|███████▌  | 5440/7211 [22:31<05:46,  5.12it/s]

Reports:  75%|███████▌  | 5441/7211 [22:31<05:46,  5.11it/s]

Reports:  75%|███████▌  | 5442/7211 [22:31<05:40,  5.20it/s]

Reports:  75%|███████▌  | 5443/7211 [22:31<05:41,  5.18it/s]

Reports:  75%|███████▌  | 5444/7211 [22:32<05:47,  5.08it/s]

Reports:  76%|███████▌  | 5445/7211 [22:32<05:43,  5.14it/s]

Reports:  76%|███████▌  | 5446/7211 [22:32<05:48,  5.07it/s]

Reports:  76%|███████▌  | 5447/7211 [23:19<6:59:25, 14.27s/it]

Reports:  76%|███████▌  | 5448/7211 [23:19<4:55:09, 10.04s/it]

Reports:  76%|███████▌  | 5449/7211 [23:19<3:28:08,  7.09s/it]

Reports:  76%|███████▌  | 5450/7211 [23:20<2:27:14,  5.02s/it]

Reports:  76%|███████▌  | 5451/7211 [23:20<1:44:52,  3.58s/it]

Reports:  76%|███████▌  | 5452/7211 [23:20<1:15:11,  2.56s/it]

Reports:  76%|███████▌  | 5453/7211 [23:20<54:15,  1.85s/it]

Reports:  76%|███████▌  | 5454/7211 [23:20<39:33,  1.35s/it]

Reports:  76%|███████▌  | 5455/7211 [23:21<29:31,  1.01s/it]

Reports:  76%|███████▌  | 5456/7211 [23:21<23:24,  1.25it/s]

Reports:  76%|███████▌  | 5457/7211 [23:21<18:02,  1.62it/s]

Reports:  76%|███████▌  | 5458/7211 [23:21<14:27,  2.02it/s]

Reports:  76%|███████▌  | 5459/7211 [23:21<11:52,  2.46it/s]

Reports:  76%|███████▌  | 5460/7211 [23:22<11:51,  2.46it/s]

Reports:  76%|███████▌  | 5461/7211 [23:22<09:54,  2.94it/s]

Reports:  76%|███████▌  | 5462/7211 [23:22<08:33,  3.40it/s]

Reports:  76%|███████▌  | 5463/7211 [23:22<07:50,  3.71it/s]

Reports:  76%|███████▌  | 5464/7211 [23:23<07:14,  4.02it/s]

Reports:  76%|███████▌  | 5465/7211 [23:23<06:42,  4.34it/s]

Reports:  76%|███████▌  | 5466/7211 [23:23<06:19,  4.60it/s]

Reports:  76%|███████▌  | 5467/7211 [23:23<06:03,  4.79it/s]

Reports:  76%|███████▌  | 5468/7211 [23:23<05:59,  4.85it/s]

Reports:  76%|███████▌  | 5469/7211 [23:24<05:50,  4.97it/s]

Reports:  76%|███████▌  | 5470/7211 [23:24<05:41,  5.10it/s]

Reports:  76%|███████▌  | 5471/7211 [23:24<05:39,  5.13it/s]

Reports:  76%|███████▌  | 5472/7211 [23:24<05:34,  5.20it/s]

Reports:  76%|███████▌  | 5473/7211 [23:24<05:35,  5.17it/s]

Reports:  76%|███████▌  | 5474/7211 [23:25<05:34,  5.19it/s]

Reports:  76%|███████▌  | 5475/7211 [23:25<05:30,  5.25it/s]

Reports:  76%|███████▌  | 5476/7211 [23:25<05:36,  5.15it/s]

Reports:  76%|███████▌  | 5477/7211 [23:25<05:40,  5.09it/s]

Reports:  76%|███████▌  | 5478/7211 [23:25<05:39,  5.10it/s]

Reports:  76%|███████▌  | 5479/7211 [23:26<05:53,  4.90it/s]

Reports:  76%|███████▌  | 5480/7211 [23:26<05:48,  4.97it/s]

Reports:  76%|███████▌  | 5481/7211 [23:26<05:49,  4.95it/s]

Reports:  76%|███████▌  | 5482/7211 [23:30<38:47,  1.35s/it]

Reports:  76%|███████▌  | 5483/7211 [23:30<28:45,  1.00it/s]

Reports:  76%|███████▌  | 5484/7211 [23:30<21:48,  1.32it/s]

Reports:  76%|███████▌  | 5485/7211 [23:31<17:01,  1.69it/s]

Reports:  76%|███████▌  | 5486/7211 [23:31<13:46,  2.09it/s]

Reports:  76%|███████▌  | 5487/7211 [23:31<11:19,  2.54it/s]

Reports:  76%|███████▌  | 5488/7211 [23:31<09:41,  2.96it/s]

Reports:  76%|███████▌  | 5489/7211 [23:31<08:22,  3.43it/s]

Reports:  76%|███████▌  | 5490/7211 [23:32<07:48,  3.68it/s]

Reports:  76%|███████▌  | 5491/7211 [23:32<07:13,  3.97it/s]

Reports:  76%|███████▌  | 5492/7211 [23:32<06:45,  4.24it/s]

Reports:  76%|███████▌  | 5493/7211 [23:32<06:28,  4.42it/s]

Reports:  76%|███████▌  | 5494/7211 [23:32<06:09,  4.64it/s]

Reports:  76%|███████▌  | 5495/7211 [23:33<05:54,  4.84it/s]

Reports:  76%|███████▌  | 5496/7211 [23:33<05:54,  4.83it/s]

Reports:  76%|███████▌  | 5497/7211 [23:33<05:48,  4.92it/s]

Reports:  76%|███████▌  | 5498/7211 [23:33<07:35,  3.76it/s]

Reports:  76%|███████▋  | 5499/7211 [23:34<06:53,  4.14it/s]

Reports:  76%|███████▋  | 5500/7211 [23:34<06:34,  4.34it/s]

Reports:  76%|███████▋  | 5501/7211 [23:34<06:10,  4.62it/s]

Reports:  76%|███████▋  | 5502/7211 [23:34<05:54,  4.82it/s]

Reports:  76%|███████▋  | 5503/7211 [23:34<05:41,  5.01it/s]

Reports:  76%|███████▋  | 5504/7211 [23:35<05:37,  5.06it/s]

Reports:  76%|███████▋  | 5505/7211 [23:35<05:40,  5.00it/s]

Reports:  76%|███████▋  | 5506/7211 [23:35<05:39,  5.02it/s]

Reports:  76%|███████▋  | 5507/7211 [23:35<07:22,  3.85it/s]

Reports:  76%|███████▋  | 5508/7211 [23:36<06:49,  4.16it/s]

Reports:  76%|███████▋  | 5509/7211 [23:36<06:20,  4.47it/s]

Reports:  76%|███████▋  | 5510/7211 [23:36<06:12,  4.57it/s]

Reports:  76%|███████▋  | 5511/7211 [23:36<06:05,  4.65it/s]

Reports:  76%|███████▋  | 5512/7211 [23:36<05:57,  4.75it/s]

Reports:  76%|███████▋  | 5513/7211 [23:37<05:48,  4.87it/s]

Reports:  76%|███████▋  | 5514/7211 [23:37<05:44,  4.93it/s]

Reports:  76%|███████▋  | 5515/7211 [23:37<05:44,  4.92it/s]

Reports:  76%|███████▋  | 5516/7211 [23:37<05:37,  5.02it/s]

Reports:  77%|███████▋  | 5517/7211 [23:37<05:32,  5.10it/s]

Reports:  77%|███████▋  | 5518/7211 [23:37<05:29,  5.14it/s]

Reports:  77%|███████▋  | 5519/7211 [23:38<05:27,  5.17it/s]

Reports:  77%|███████▋  | 5520/7211 [23:38<05:25,  5.20it/s]

Reports:  77%|███████▋  | 5521/7211 [23:38<05:21,  5.26it/s]

Reports:  77%|███████▋  | 5522/7211 [23:39<11:11,  2.52it/s]

Reports:  77%|███████▋  | 5523/7211 [23:39<09:24,  2.99it/s]

Reports:  77%|███████▋  | 5524/7211 [23:39<08:19,  3.38it/s]

Reports:  77%|███████▋  | 5525/7211 [23:40<07:30,  3.74it/s]

Reports:  77%|███████▋  | 5526/7211 [23:40<06:50,  4.10it/s]

Reports:  77%|███████▋  | 5527/7211 [23:40<06:22,  4.41it/s]

Reports:  77%|███████▋  | 5528/7211 [23:40<06:04,  4.62it/s]

Reports:  77%|███████▋  | 5529/7211 [23:40<05:45,  4.87it/s]

Reports:  77%|███████▋  | 5530/7211 [23:40<05:35,  5.01it/s]

Reports:  77%|███████▋  | 5531/7211 [23:41<05:26,  5.14it/s]

Reports:  77%|███████▋  | 5532/7211 [23:41<05:29,  5.10it/s]

Reports:  77%|███████▋  | 5533/7211 [23:41<05:27,  5.13it/s]

Reports:  77%|███████▋  | 5534/7211 [23:41<05:23,  5.19it/s]

Reports:  77%|███████▋  | 5535/7211 [23:41<05:21,  5.22it/s]

Reports:  77%|███████▋  | 5536/7211 [23:42<05:21,  5.21it/s]

Reports:  77%|███████▋  | 5537/7211 [23:42<05:21,  5.21it/s]

Reports:  77%|███████▋  | 5538/7211 [23:42<05:15,  5.29it/s]

Reports:  77%|███████▋  | 5539/7211 [23:42<05:27,  5.11it/s]

Reports:  77%|███████▋  | 5540/7211 [23:42<05:24,  5.14it/s]

Reports:  77%|███████▋  | 5541/7211 [23:43<05:21,  5.19it/s]

Reports:  77%|███████▋  | 5542/7211 [23:43<05:20,  5.21it/s]

Reports:  77%|███████▋  | 5543/7211 [23:43<05:22,  5.18it/s]

Reports:  77%|███████▋  | 5544/7211 [23:43<05:24,  5.14it/s]

Reports:  77%|███████▋  | 5545/7211 [23:43<05:25,  5.11it/s]

Reports:  77%|███████▋  | 5546/7211 [23:44<05:25,  5.11it/s]

Reports:  77%|███████▋  | 5547/7211 [23:44<08:51,  3.13it/s]

Reports:  77%|███████▋  | 5548/7211 [23:44<07:44,  3.58it/s]

Reports:  77%|███████▋  | 5549/7211 [23:45<07:03,  3.92it/s]

Reports:  77%|███████▋  | 5550/7211 [23:45<06:41,  4.14it/s]

Reports:  77%|███████▋  | 5551/7211 [23:45<06:11,  4.46it/s]

Reports:  77%|███████▋  | 5552/7211 [23:45<06:06,  4.52it/s]

Reports:  77%|███████▋  | 5553/7211 [23:45<06:00,  4.60it/s]

Reports:  77%|███████▋  | 5554/7211 [23:46<05:53,  4.69it/s]

Reports:  77%|███████▋  | 5555/7211 [23:46<05:40,  4.86it/s]

Reports:  77%|███████▋  | 5556/7211 [23:46<06:41,  4.12it/s]

Reports:  77%|███████▋  | 5557/7211 [23:46<06:21,  4.34it/s]

Reports:  77%|███████▋  | 5558/7211 [23:47<06:13,  4.43it/s]

Reports:  77%|███████▋  | 5559/7211 [23:47<05:56,  4.63it/s]

Reports:  77%|███████▋  | 5560/7211 [23:47<06:03,  4.54it/s]

Reports:  77%|███████▋  | 5561/7211 [23:47<05:49,  4.72it/s]

Reports:  77%|███████▋  | 5562/7211 [23:47<05:40,  4.84it/s]

Reports:  77%|███████▋  | 5563/7211 [23:48<05:32,  4.96it/s]

Reports:  77%|███████▋  | 5564/7211 [23:48<05:34,  4.93it/s]

Reports:  77%|███████▋  | 5565/7211 [23:48<05:25,  5.05it/s]

Reports:  77%|███████▋  | 5566/7211 [23:48<05:25,  5.06it/s]

Reports:  77%|███████▋  | 5567/7211 [23:48<05:23,  5.09it/s]

Reports:  77%|███████▋  | 5568/7211 [23:48<05:23,  5.08it/s]

Reports:  77%|███████▋  | 5569/7211 [23:49<05:20,  5.13it/s]

Reports:  77%|███████▋  | 5570/7211 [23:49<05:15,  5.20it/s]

Reports:  77%|███████▋  | 5571/7211 [23:49<05:15,  5.20it/s]

Reports:  77%|███████▋  | 5572/7211 [23:49<05:12,  5.24it/s]

Reports:  77%|███████▋  | 5573/7211 [23:49<05:19,  5.13it/s]

Reports:  77%|███████▋  | 5574/7211 [23:50<05:16,  5.17it/s]

Reports:  77%|███████▋  | 5575/7211 [23:50<05:19,  5.13it/s]

Reports:  77%|███████▋  | 5576/7211 [23:50<05:13,  5.21it/s]

Reports:  77%|███████▋  | 5577/7211 [23:50<05:11,  5.25it/s]

Reports:  77%|███████▋  | 5578/7211 [23:50<05:20,  5.10it/s]

Reports:  77%|███████▋  | 5579/7211 [23:51<05:11,  5.23it/s]

Reports:  77%|███████▋  | 5580/7211 [23:51<05:11,  5.24it/s]

Reports:  77%|███████▋  | 5581/7211 [23:51<05:08,  5.29it/s]

Reports:  77%|███████▋  | 5582/7211 [23:52<10:16,  2.64it/s]

Reports:  77%|███████▋  | 5583/7211 [23:52<08:44,  3.10it/s]

Reports:  77%|███████▋  | 5584/7211 [23:52<07:42,  3.52it/s]

Reports:  77%|███████▋  | 5585/7211 [23:52<06:53,  3.93it/s]

Reports:  77%|███████▋  | 5586/7211 [23:53<06:22,  4.25it/s]

Reports:  77%|███████▋  | 5587/7211 [23:53<06:06,  4.43it/s]

Reports:  77%|███████▋  | 5588/7211 [23:53<05:43,  4.73it/s]

Reports:  78%|███████▊  | 5589/7211 [23:53<06:08,  4.40it/s]

Reports:  78%|███████▊  | 5590/7211 [23:53<05:51,  4.62it/s]

Reports:  78%|███████▊  | 5591/7211 [23:54<05:34,  4.84it/s]

Reports:  78%|███████▊  | 5592/7211 [23:54<05:24,  4.99it/s]

Reports:  78%|███████▊  | 5593/7211 [23:54<06:30,  4.15it/s]

Reports:  78%|███████▊  | 5594/7211 [23:54<06:01,  4.47it/s]

Reports:  78%|███████▊  | 5595/7211 [23:54<05:46,  4.67it/s]

Reports:  78%|███████▊  | 5596/7211 [23:55<05:36,  4.80it/s]

Reports:  78%|███████▊  | 5597/7211 [23:55<05:30,  4.89it/s]

Reports:  78%|███████▊  | 5598/7211 [23:55<05:19,  5.04it/s]

Reports:  78%|███████▊  | 5599/7211 [23:55<05:17,  5.07it/s]

Reports:  78%|███████▊  | 5600/7211 [23:55<05:16,  5.08it/s]

Reports:  78%|███████▊  | 5601/7211 [23:56<05:14,  5.12it/s]

Reports:  78%|███████▊  | 5602/7211 [23:56<05:11,  5.17it/s]

Reports:  78%|███████▊  | 5603/7211 [23:56<05:19,  5.04it/s]

Reports:  78%|███████▊  | 5604/7211 [23:56<05:16,  5.08it/s]

Reports:  78%|███████▊  | 5605/7211 [23:56<05:19,  5.03it/s]

Reports:  78%|███████▊  | 5606/7211 [23:57<05:11,  5.16it/s]

Reports:  78%|███████▊  | 5607/7211 [23:57<05:08,  5.21it/s]

Reports:  78%|███████▊  | 5608/7211 [24:00<30:13,  1.13s/it]

Reports:  78%|███████▊  | 5609/7211 [24:00<22:55,  1.16it/s]

Reports:  78%|███████▊  | 5610/7211 [24:01<17:37,  1.51it/s]

Reports:  78%|███████▊  | 5611/7211 [24:01<13:54,  1.92it/s]

Reports:  78%|███████▊  | 5612/7211 [24:01<11:13,  2.37it/s]

Reports:  78%|███████▊  | 5613/7211 [24:01<09:26,  2.82it/s]

Reports:  78%|███████▊  | 5614/7211 [24:01<08:10,  3.26it/s]

Reports:  78%|███████▊  | 5615/7211 [24:02<07:14,  3.67it/s]

Reports:  78%|███████▊  | 5616/7211 [24:02<08:06,  3.28it/s]

Reports:  78%|███████▊  | 5617/7211 [24:02<07:17,  3.64it/s]

Reports:  78%|███████▊  | 5618/7211 [24:02<06:35,  4.03it/s]

Reports:  78%|███████▊  | 5619/7211 [24:02<06:04,  4.37it/s]

Reports:  78%|███████▊  | 5620/7211 [24:03<05:44,  4.62it/s]

Reports:  78%|███████▊  | 5621/7211 [24:03<05:34,  4.75it/s]

Reports:  78%|███████▊  | 5622/7211 [24:03<05:23,  4.91it/s]

Reports:  78%|███████▊  | 5623/7211 [24:03<05:12,  5.08it/s]

Reports:  78%|███████▊  | 5624/7211 [24:03<05:02,  5.24it/s]

Reports:  78%|███████▊  | 5625/7211 [24:04<05:06,  5.17it/s]

Reports:  78%|███████▊  | 5626/7211 [24:04<05:08,  5.14it/s]

Reports:  78%|███████▊  | 5627/7211 [24:04<05:13,  5.05it/s]

Reports:  78%|███████▊  | 5628/7211 [24:04<05:06,  5.16it/s]

Reports:  78%|███████▊  | 5629/7211 [24:04<05:00,  5.26it/s]

Reports:  78%|███████▊  | 5630/7211 [24:05<05:04,  5.19it/s]

Reports:  78%|███████▊  | 5631/7211 [24:05<05:11,  5.07it/s]

Reports:  78%|███████▊  | 5632/7211 [24:05<05:06,  5.15it/s]

Reports:  78%|███████▊  | 5633/7211 [24:05<05:04,  5.18it/s]

Reports:  78%|███████▊  | 5634/7211 [24:05<05:01,  5.24it/s]

Reports:  78%|███████▊  | 5635/7211 [24:06<05:00,  5.24it/s]

Reports:  78%|███████▊  | 5636/7211 [24:06<04:58,  5.28it/s]

Reports:  78%|███████▊  | 5637/7211 [24:06<04:56,  5.31it/s]

Reports:  78%|███████▊  | 5638/7211 [24:06<06:46,  3.87it/s]

Reports:  78%|███████▊  | 5639/7211 [24:07<06:21,  4.12it/s]

Reports:  78%|███████▊  | 5640/7211 [24:07<05:55,  4.42it/s]

Reports:  78%|███████▊  | 5641/7211 [24:07<05:33,  4.71it/s]

Reports:  78%|███████▊  | 5642/7211 [24:07<05:28,  4.78it/s]

Reports:  78%|███████▊  | 5643/7211 [24:07<05:24,  4.83it/s]

Reports:  78%|███████▊  | 5644/7211 [24:07<05:11,  5.04it/s]

Reports:  78%|███████▊  | 5645/7211 [24:08<06:47,  3.84it/s]

Reports:  78%|███████▊  | 5646/7211 [24:08<06:19,  4.12it/s]

Reports:  78%|███████▊  | 5647/7211 [24:08<05:59,  4.35it/s]

Reports:  78%|███████▊  | 5648/7211 [24:08<05:44,  4.54it/s]

Reports:  78%|███████▊  | 5649/7211 [24:09<05:25,  4.79it/s]

Reports:  78%|███████▊  | 5650/7211 [24:09<05:18,  4.90it/s]

Reports:  78%|███████▊  | 5651/7211 [24:09<05:16,  4.93it/s]

Reports:  78%|███████▊  | 5652/7211 [24:09<05:10,  5.02it/s]

Reports:  78%|███████▊  | 5653/7211 [24:09<05:09,  5.03it/s]

Reports:  78%|███████▊  | 5654/7211 [24:10<08:08,  3.19it/s]

Reports:  78%|███████▊  | 5655/7211 [24:10<07:13,  3.59it/s]

Reports:  78%|███████▊  | 5656/7211 [24:10<06:43,  3.85it/s]

Reports:  78%|███████▊  | 5657/7211 [24:11<06:10,  4.19it/s]

Reports:  78%|███████▊  | 5658/7211 [24:11<05:44,  4.50it/s]

Reports:  78%|███████▊  | 5659/7211 [24:11<05:27,  4.74it/s]

Reports:  78%|███████▊  | 5660/7211 [24:11<05:17,  4.89it/s]

Reports:  79%|███████▊  | 5661/7211 [24:11<05:05,  5.07it/s]

Reports:  79%|███████▊  | 5662/7211 [24:12<05:08,  5.03it/s]

Reports:  79%|███████▊  | 5663/7211 [24:12<05:02,  5.11it/s]

Reports:  79%|███████▊  | 5664/7211 [24:12<04:58,  5.17it/s]

Reports:  79%|███████▊  | 5665/7211 [24:12<04:53,  5.27it/s]

Reports:  79%|███████▊  | 5666/7211 [24:12<04:56,  5.22it/s]

Reports:  79%|███████▊  | 5667/7211 [24:13<04:57,  5.19it/s]

Reports:  79%|███████▊  | 5668/7211 [24:13<04:58,  5.17it/s]

Reports:  79%|███████▊  | 5669/7211 [24:13<05:26,  4.72it/s]

Reports:  79%|███████▊  | 5670/7211 [24:13<05:22,  4.77it/s]

Reports:  79%|███████▊  | 5671/7211 [24:13<05:14,  4.90it/s]

Reports:  79%|███████▊  | 5672/7211 [24:14<05:08,  4.98it/s]

Reports:  79%|███████▊  | 5673/7211 [24:14<05:10,  4.96it/s]

Reports:  79%|███████▊  | 5674/7211 [24:14<05:07,  5.00it/s]

Reports:  79%|███████▊  | 5675/7211 [24:14<05:03,  5.06it/s]

Reports:  79%|███████▊  | 5676/7211 [24:14<05:01,  5.09it/s]

Reports:  79%|███████▊  | 5677/7211 [24:15<04:57,  5.16it/s]

Reports:  79%|███████▊  | 5678/7211 [24:15<04:54,  5.20it/s]

Reports:  79%|███████▉  | 5679/7211 [24:15<05:01,  5.08it/s]

Reports:  79%|███████▉  | 5680/7211 [24:15<05:07,  4.98it/s]

Reports:  79%|███████▉  | 5681/7211 [24:15<05:06,  4.99it/s]

Reports:  79%|███████▉  | 5682/7211 [24:16<05:02,  5.05it/s]

Reports:  79%|███████▉  | 5683/7211 [24:16<04:59,  5.11it/s]

Reports:  79%|███████▉  | 5684/7211 [24:16<04:58,  5.12it/s]

Reports:  79%|███████▉  | 5685/7211 [24:16<04:55,  5.16it/s]

Reports:  79%|███████▉  | 5686/7211 [24:16<04:57,  5.13it/s]

Reports:  79%|███████▉  | 5687/7211 [24:16<04:51,  5.23it/s]

Reports:  79%|███████▉  | 5688/7211 [24:17<04:51,  5.22it/s]

Reports:  79%|███████▉  | 5689/7211 [24:17<04:51,  5.22it/s]

Reports:  79%|███████▉  | 5690/7211 [24:17<04:49,  5.25it/s]

Reports:  79%|███████▉  | 5691/7211 [24:17<04:53,  5.18it/s]

Reports:  79%|███████▉  | 5692/7211 [24:17<04:51,  5.22it/s]

Reports:  79%|███████▉  | 5693/7211 [24:18<04:50,  5.22it/s]

Reports:  79%|███████▉  | 5694/7211 [24:18<04:57,  5.10it/s]

Reports:  79%|███████▉  | 5695/7211 [24:18<04:59,  5.07it/s]

Reports:  79%|███████▉  | 5696/7211 [24:18<04:56,  5.11it/s]

Reports:  79%|███████▉  | 5697/7211 [24:18<05:02,  5.00it/s]

Reports:  79%|███████▉  | 5698/7211 [24:19<04:56,  5.10it/s]

Reports:  79%|███████▉  | 5699/7211 [24:19<04:56,  5.10it/s]

Reports:  79%|███████▉  | 5700/7211 [24:19<04:56,  5.09it/s]

Reports:  79%|███████▉  | 5701/7211 [24:19<05:02,  4.99it/s]

Reports:  79%|███████▉  | 5702/7211 [24:19<05:05,  4.93it/s]

Reports:  79%|███████▉  | 5703/7211 [24:20<04:58,  5.05it/s]

Reports:  79%|███████▉  | 5704/7211 [24:20<05:00,  5.02it/s]

Reports:  79%|███████▉  | 5705/7211 [24:20<04:52,  5.15it/s]

Reports:  79%|███████▉  | 5706/7211 [24:20<04:55,  5.10it/s]

Reports:  79%|███████▉  | 5707/7211 [24:20<04:52,  5.15it/s]

Reports:  79%|███████▉  | 5708/7211 [24:21<04:49,  5.20it/s]

Reports:  79%|███████▉  | 5709/7211 [24:21<04:54,  5.10it/s]

Reports:  79%|███████▉  | 5710/7211 [24:21<04:54,  5.10it/s]

Reports:  79%|███████▉  | 5711/7211 [24:21<04:48,  5.20it/s]

Reports:  79%|███████▉  | 5712/7211 [24:21<04:47,  5.21it/s]

Reports:  79%|███████▉  | 5713/7211 [24:22<04:46,  5.22it/s]

Reports:  79%|███████▉  | 5714/7211 [24:22<04:47,  5.20it/s]

Reports:  79%|███████▉  | 5715/7211 [24:22<04:47,  5.20it/s]

Reports:  79%|███████▉  | 5716/7211 [24:22<04:47,  5.20it/s]

Reports:  79%|███████▉  | 5717/7211 [24:22<04:42,  5.28it/s]

Reports:  79%|███████▉  | 5718/7211 [24:23<04:50,  5.14it/s]

Reports:  79%|███████▉  | 5719/7211 [24:23<04:52,  5.11it/s]

Reports:  79%|███████▉  | 5720/7211 [24:23<04:48,  5.17it/s]

Reports:  79%|███████▉  | 5721/7211 [24:23<04:46,  5.20it/s]

Reports:  79%|███████▉  | 5722/7211 [24:23<04:45,  5.22it/s]

Reports:  79%|███████▉  | 5723/7211 [24:23<04:45,  5.20it/s]

Reports:  79%|███████▉  | 5724/7211 [24:24<04:41,  5.28it/s]

Reports:  79%|███████▉  | 5725/7211 [24:24<04:51,  5.10it/s]

Reports:  79%|███████▉  | 5726/7211 [24:24<04:52,  5.09it/s]

Reports:  79%|███████▉  | 5727/7211 [24:24<04:43,  5.24it/s]

Reports:  79%|███████▉  | 5728/7211 [24:24<04:45,  5.19it/s]

Reports:  79%|███████▉  | 5729/7211 [24:25<04:53,  5.05it/s]

Reports:  79%|███████▉  | 5730/7211 [24:25<04:54,  5.04it/s]

Reports:  79%|███████▉  | 5731/7211 [24:25<04:49,  5.11it/s]

Reports:  79%|███████▉  | 5732/7211 [24:25<04:45,  5.18it/s]

Reports:  80%|███████▉  | 5733/7211 [24:25<04:49,  5.10it/s]

Reports:  80%|███████▉  | 5734/7211 [24:26<04:46,  5.15it/s]

Reports:  80%|███████▉  | 5735/7211 [24:26<04:45,  5.18it/s]

Reports:  80%|███████▉  | 5736/7211 [24:26<04:43,  5.20it/s]

Reports:  80%|███████▉  | 5737/7211 [24:26<04:47,  5.13it/s]

Reports:  80%|███████▉  | 5738/7211 [24:26<04:45,  5.15it/s]

Reports:  80%|███████▉  | 5739/7211 [24:27<04:42,  5.22it/s]

Reports:  80%|███████▉  | 5740/7211 [24:27<04:44,  5.17it/s]

Reports:  80%|███████▉  | 5741/7211 [24:28<14:22,  1.70it/s]

Reports:  80%|███████▉  | 5742/7211 [24:28<11:23,  2.15it/s]

Reports:  80%|███████▉  | 5743/7211 [24:29<09:22,  2.61it/s]

Reports:  80%|███████▉  | 5744/7211 [24:29<07:59,  3.06it/s]

Reports:  80%|███████▉  | 5745/7211 [24:29<07:00,  3.49it/s]

Reports:  80%|███████▉  | 5746/7211 [24:29<06:20,  3.85it/s]

Reports:  80%|███████▉  | 5747/7211 [24:29<05:50,  4.18it/s]

Reports:  80%|███████▉  | 5748/7211 [24:30<05:43,  4.26it/s]

Reports:  80%|███████▉  | 5749/7211 [24:30<05:27,  4.46it/s]

Reports:  80%|███████▉  | 5750/7211 [24:30<05:11,  4.70it/s]

Reports:  80%|███████▉  | 5751/7211 [24:30<05:06,  4.77it/s]

Reports:  80%|███████▉  | 5752/7211 [24:30<05:05,  4.78it/s]

Reports:  80%|███████▉  | 5753/7211 [24:31<05:02,  4.82it/s]

Reports:  80%|███████▉  | 5754/7211 [24:31<04:54,  4.95it/s]

Reports:  80%|███████▉  | 5755/7211 [24:31<04:49,  5.02it/s]

Reports:  80%|███████▉  | 5756/7211 [24:31<06:10,  3.92it/s]

Reports:  80%|███████▉  | 5757/7211 [24:32<05:42,  4.24it/s]

Reports:  80%|███████▉  | 5758/7211 [24:32<05:22,  4.51it/s]

Reports:  80%|███████▉  | 5759/7211 [24:32<05:07,  4.72it/s]

Reports:  80%|███████▉  | 5760/7211 [24:32<04:57,  4.87it/s]

Reports:  80%|███████▉  | 5761/7211 [24:32<04:55,  4.91it/s]

Reports:  80%|███████▉  | 5762/7211 [24:33<04:51,  4.96it/s]

Reports:  80%|███████▉  | 5763/7211 [24:33<04:50,  4.99it/s]

Reports:  80%|███████▉  | 5764/7211 [24:33<04:43,  5.11it/s]

Reports:  80%|███████▉  | 5765/7211 [24:33<04:40,  5.16it/s]

Reports:  80%|███████▉  | 5766/7211 [24:33<04:42,  5.11it/s]

Reports:  80%|███████▉  | 5767/7211 [24:34<04:44,  5.07it/s]

Reports:  80%|███████▉  | 5768/7211 [24:34<04:40,  5.15it/s]

Reports:  80%|████████  | 5769/7211 [24:34<04:34,  5.24it/s]

Reports:  80%|████████  | 5770/7211 [24:34<04:30,  5.33it/s]

Reports:  80%|████████  | 5771/7211 [24:34<04:35,  5.23it/s]

Reports:  80%|████████  | 5772/7211 [24:35<04:38,  5.16it/s]

Reports:  80%|████████  | 5773/7211 [24:35<04:39,  5.15it/s]

Reports:  80%|████████  | 5774/7211 [24:35<05:16,  4.54it/s]

Reports:  80%|████████  | 5775/7211 [24:35<05:08,  4.65it/s]

Reports:  80%|████████  | 5776/7211 [24:35<04:58,  4.81it/s]

Reports:  80%|████████  | 5777/7211 [24:36<04:50,  4.94it/s]

Reports:  80%|████████  | 5778/7211 [24:36<04:43,  5.05it/s]

Reports:  80%|████████  | 5779/7211 [24:36<05:57,  4.01it/s]

Reports:  80%|████████  | 5780/7211 [24:36<05:29,  4.35it/s]

Reports:  80%|████████  | 5781/7211 [24:36<05:09,  4.62it/s]

Reports:  80%|████████  | 5782/7211 [24:37<04:55,  4.83it/s]

Reports:  80%|████████  | 5783/7211 [24:37<04:54,  4.86it/s]

Reports:  80%|████████  | 5784/7211 [24:37<04:45,  5.00it/s]

Reports:  80%|████████  | 5785/7211 [24:37<04:37,  5.14it/s]

Reports:  80%|████████  | 5786/7211 [24:37<04:37,  5.14it/s]

Reports:  80%|████████  | 5787/7211 [24:38<04:33,  5.21it/s]

Reports:  80%|████████  | 5788/7211 [24:38<04:34,  5.18it/s]

Reports:  80%|████████  | 5789/7211 [24:38<04:33,  5.19it/s]

Reports:  80%|████████  | 5790/7211 [24:38<04:31,  5.24it/s]

Reports:  80%|████████  | 5791/7211 [24:38<04:33,  5.19it/s]

Reports:  80%|████████  | 5792/7211 [24:39<04:31,  5.24it/s]

Reports:  80%|████████  | 5793/7211 [24:39<04:35,  5.14it/s]

Reports:  80%|████████  | 5794/7211 [24:39<04:41,  5.03it/s]

Reports:  80%|████████  | 5795/7211 [24:39<04:40,  5.04it/s]

Reports:  80%|████████  | 5796/7211 [24:39<04:38,  5.08it/s]

Reports:  80%|████████  | 5797/7211 [24:40<04:32,  5.18it/s]

Reports:  80%|████████  | 5798/7211 [24:40<04:29,  5.25it/s]

Reports:  80%|████████  | 5799/7211 [24:40<04:30,  5.23it/s]

Reports:  80%|████████  | 5800/7211 [24:40<04:26,  5.29it/s]

Reports:  80%|████████  | 5801/7211 [24:40<04:26,  5.30it/s]

Reports:  80%|████████  | 5802/7211 [24:41<04:29,  5.23it/s]

Reports:  80%|████████  | 5803/7211 [24:41<04:29,  5.23it/s]

Reports:  80%|████████  | 5804/7211 [24:41<04:31,  5.19it/s]

Reports:  81%|████████  | 5805/7211 [24:41<04:33,  5.15it/s]

Reports:  81%|████████  | 5806/7211 [24:41<04:35,  5.09it/s]

Reports:  81%|████████  | 5807/7211 [24:42<04:35,  5.09it/s]

Reports:  81%|████████  | 5808/7211 [24:42<04:37,  5.05it/s]

Reports:  81%|████████  | 5809/7211 [24:42<04:36,  5.07it/s]

Reports:  81%|████████  | 5810/7211 [24:42<04:30,  5.17it/s]

Reports:  81%|████████  | 5811/7211 [24:42<04:38,  5.02it/s]

Reports:  81%|████████  | 5812/7211 [24:42<04:37,  5.03it/s]

Reports:  81%|████████  | 5813/7211 [24:43<04:31,  5.15it/s]

Reports:  81%|████████  | 5814/7211 [24:43<04:30,  5.17it/s]

Reports:  81%|████████  | 5815/7211 [24:43<04:27,  5.22it/s]

Reports:  81%|████████  | 5816/7211 [24:43<04:29,  5.18it/s]

Reports:  81%|████████  | 5817/7211 [24:43<04:26,  5.23it/s]

Reports:  81%|████████  | 5818/7211 [24:44<04:21,  5.32it/s]

Reports:  81%|████████  | 5819/7211 [24:44<04:20,  5.35it/s]

Reports:  81%|████████  | 5820/7211 [24:44<04:26,  5.22it/s]

Reports:  81%|████████  | 5821/7211 [24:44<04:21,  5.31it/s]

Reports:  81%|████████  | 5822/7211 [24:44<04:23,  5.28it/s]

Reports:  81%|████████  | 5823/7211 [24:45<04:19,  5.35it/s]

Reports:  81%|████████  | 5824/7211 [24:45<04:22,  5.28it/s]

Reports:  81%|████████  | 5825/7211 [24:45<04:18,  5.37it/s]

Reports:  81%|████████  | 5826/7211 [24:45<04:18,  5.35it/s]

Reports:  81%|████████  | 5827/7211 [24:45<04:26,  5.19it/s]

Reports:  81%|████████  | 5828/7211 [24:46<04:25,  5.20it/s]

Reports:  81%|████████  | 5829/7211 [24:46<04:27,  5.17it/s]

Reports:  81%|████████  | 5830/7211 [24:46<04:31,  5.09it/s]

Reports:  81%|████████  | 5831/7211 [24:46<04:25,  5.19it/s]

Reports:  81%|████████  | 5832/7211 [24:46<04:20,  5.29it/s]

Reports:  81%|████████  | 5833/7211 [24:46<04:25,  5.20it/s]

Reports:  81%|████████  | 5834/7211 [24:47<04:21,  5.26it/s]

Reports:  81%|████████  | 5835/7211 [24:47<04:24,  5.20it/s]

Reports:  81%|████████  | 5836/7211 [24:47<04:22,  5.23it/s]

Reports:  81%|████████  | 5837/7211 [24:47<04:21,  5.26it/s]

Reports:  81%|████████  | 5838/7211 [24:47<04:23,  5.21it/s]

Reports:  81%|████████  | 5839/7211 [24:48<04:21,  5.24it/s]

Reports:  81%|████████  | 5840/7211 [24:48<04:17,  5.33it/s]

Reports:  81%|████████  | 5841/7211 [24:48<04:16,  5.34it/s]

Reports:  81%|████████  | 5842/7211 [24:48<04:14,  5.38it/s]

Reports:  81%|████████  | 5843/7211 [24:48<04:17,  5.31it/s]

Reports:  81%|████████  | 5844/7211 [24:49<04:19,  5.26it/s]

Reports:  81%|████████  | 5845/7211 [24:49<04:18,  5.29it/s]

Reports:  81%|████████  | 5846/7211 [24:49<04:16,  5.31it/s]

Reports:  81%|████████  | 5847/7211 [24:49<04:22,  5.21it/s]

Reports:  81%|████████  | 5848/7211 [24:49<04:20,  5.24it/s]

Reports:  81%|████████  | 5849/7211 [24:50<04:18,  5.27it/s]

Reports:  81%|████████  | 5850/7211 [24:50<04:27,  5.10it/s]

Reports:  81%|████████  | 5851/7211 [24:50<04:29,  5.05it/s]

Reports:  81%|████████  | 5852/7211 [24:50<04:31,  5.01it/s]

Reports:  81%|████████  | 5853/7211 [24:50<04:27,  5.08it/s]

Reports:  81%|████████  | 5854/7211 [24:51<04:25,  5.11it/s]

Reports:  81%|████████  | 5855/7211 [24:51<04:20,  5.21it/s]

Reports:  81%|████████  | 5856/7211 [24:51<04:13,  5.35it/s]

Reports:  81%|████████  | 5857/7211 [24:51<04:13,  5.34it/s]

Reports:  81%|████████  | 5858/7211 [24:51<04:11,  5.39it/s]

Reports:  81%|████████▏ | 5859/7211 [24:51<04:13,  5.34it/s]

Reports:  81%|████████▏ | 5860/7211 [24:52<04:16,  5.26it/s]

Reports:  81%|████████▏ | 5861/7211 [24:52<04:13,  5.33it/s]

Reports:  81%|████████▏ | 5862/7211 [24:52<04:12,  5.35it/s]

Reports:  81%|████████▏ | 5863/7211 [24:52<04:12,  5.33it/s]

Reports:  81%|████████▏ | 5864/7211 [24:52<04:14,  5.30it/s]

Reports:  81%|████████▏ | 5865/7211 [24:53<04:16,  5.25it/s]

Reports:  81%|████████▏ | 5866/7211 [24:53<04:12,  5.34it/s]

Reports:  81%|████████▏ | 5867/7211 [24:53<05:05,  4.40it/s]

Reports:  81%|████████▏ | 5868/7211 [24:53<04:47,  4.67it/s]

Reports:  81%|████████▏ | 5869/7211 [24:53<04:34,  4.88it/s]

Reports:  81%|████████▏ | 5870/7211 [24:54<04:25,  5.05it/s]

Reports:  81%|████████▏ | 5871/7211 [24:54<04:19,  5.16it/s]

Reports:  81%|████████▏ | 5872/7211 [24:54<04:19,  5.16it/s]

Reports:  81%|████████▏ | 5873/7211 [24:54<04:17,  5.20it/s]

Reports:  81%|████████▏ | 5874/7211 [24:54<04:17,  5.19it/s]

Reports:  81%|████████▏ | 5875/7211 [24:55<04:15,  5.22it/s]

Reports:  81%|████████▏ | 5876/7211 [24:55<04:11,  5.31it/s]

Reports:  82%|████████▏ | 5877/7211 [24:55<04:10,  5.33it/s]

Reports:  82%|████████▏ | 5878/7211 [24:55<04:17,  5.18it/s]

Reports:  82%|████████▏ | 5879/7211 [24:55<04:12,  5.28it/s]

Reports:  82%|████████▏ | 5880/7211 [24:56<04:10,  5.32it/s]

Reports:  82%|████████▏ | 5881/7211 [24:56<04:08,  5.36it/s]

Reports:  82%|████████▏ | 5882/7211 [24:56<04:06,  5.40it/s]

Reports:  82%|████████▏ | 5883/7211 [24:56<04:05,  5.41it/s]

Reports:  82%|████████▏ | 5884/7211 [24:56<04:05,  5.40it/s]

Reports:  82%|████████▏ | 5885/7211 [24:56<04:05,  5.40it/s]

Reports:  82%|████████▏ | 5886/7211 [24:57<04:09,  5.31it/s]

Reports:  82%|████████▏ | 5887/7211 [24:57<04:13,  5.22it/s]

Reports:  82%|████████▏ | 5888/7211 [24:57<04:14,  5.20it/s]

Reports:  82%|████████▏ | 5889/7211 [24:57<04:15,  5.18it/s]

Reports:  82%|████████▏ | 5890/7211 [24:57<04:15,  5.17it/s]

Reports:  82%|████████▏ | 5891/7211 [24:58<04:15,  5.17it/s]

Reports:  82%|████████▏ | 5892/7211 [24:58<04:13,  5.21it/s]

Reports:  82%|████████▏ | 5893/7211 [24:58<04:14,  5.18it/s]

Reports:  82%|████████▏ | 5894/7211 [24:58<04:16,  5.14it/s]

Reports:  82%|████████▏ | 5895/7211 [24:58<04:11,  5.24it/s]

Reports:  82%|████████▏ | 5896/7211 [24:59<04:10,  5.26it/s]

Reports:  82%|████████▏ | 5897/7211 [24:59<04:11,  5.22it/s]

Reports:  82%|████████▏ | 5898/7211 [24:59<04:05,  5.34it/s]

Reports:  82%|████████▏ | 5899/7211 [24:59<04:03,  5.38it/s]

Reports:  82%|████████▏ | 5900/7211 [24:59<04:06,  5.33it/s]

Reports:  82%|████████▏ | 5901/7211 [24:59<04:08,  5.27it/s]

Reports:  82%|████████▏ | 5902/7211 [25:00<04:07,  5.30it/s]

Reports:  82%|████████▏ | 5903/7211 [25:00<04:59,  4.37it/s]

Reports:  82%|████████▏ | 5904/7211 [25:00<04:45,  4.58it/s]

Reports:  82%|████████▏ | 5905/7211 [25:00<04:33,  4.78it/s]

Reports:  82%|████████▏ | 5906/7211 [25:01<04:27,  4.88it/s]

Reports:  82%|████████▏ | 5907/7211 [25:01<04:25,  4.92it/s]

Reports:  82%|████████▏ | 5908/7211 [25:01<04:21,  4.97it/s]

Reports:  82%|████████▏ | 5909/7211 [25:01<04:14,  5.12it/s]

Reports:  82%|████████▏ | 5910/7211 [25:01<04:19,  5.01it/s]

Reports:  82%|████████▏ | 5911/7211 [25:02<04:15,  5.10it/s]

Reports:  82%|████████▏ | 5912/7211 [25:02<04:12,  5.14it/s]

Reports:  82%|████████▏ | 5913/7211 [25:02<04:36,  4.69it/s]

Reports:  82%|████████▏ | 5914/7211 [25:02<04:34,  4.72it/s]

Reports:  82%|████████▏ | 5915/7211 [25:02<04:34,  4.73it/s]

Reports:  82%|████████▏ | 5916/7211 [25:03<05:13,  4.13it/s]

Reports:  82%|████████▏ | 5917/7211 [25:03<05:04,  4.25it/s]

Reports:  82%|████████▏ | 5918/7211 [25:03<04:54,  4.39it/s]

Reports:  82%|████████▏ | 5919/7211 [25:03<04:40,  4.61it/s]

Reports:  82%|████████▏ | 5920/7211 [25:04<04:32,  4.73it/s]

Reports:  82%|████████▏ | 5921/7211 [25:04<04:23,  4.90it/s]

Reports:  82%|████████▏ | 5922/7211 [25:04<04:19,  4.97it/s]

Reports:  82%|████████▏ | 5923/7211 [25:04<04:15,  5.03it/s]

Reports:  82%|████████▏ | 5924/7211 [25:04<04:15,  5.03it/s]

Reports:  82%|████████▏ | 5925/7211 [25:05<04:09,  5.16it/s]

Reports:  82%|████████▏ | 5926/7211 [25:05<04:04,  5.25it/s]

Reports:  82%|████████▏ | 5927/7211 [25:05<04:00,  5.33it/s]

Reports:  82%|████████▏ | 5928/7211 [25:05<03:59,  5.36it/s]

Reports:  82%|████████▏ | 5929/7211 [25:05<04:03,  5.26it/s]

Reports:  82%|████████▏ | 5930/7211 [25:06<05:17,  4.03it/s]

Reports:  82%|████████▏ | 5931/7211 [25:06<04:53,  4.36it/s]

Reports:  82%|████████▏ | 5932/7211 [25:06<04:38,  4.59it/s]

Reports:  82%|████████▏ | 5933/7211 [25:06<04:23,  4.85it/s]

Reports:  82%|████████▏ | 5934/7211 [25:06<04:18,  4.95it/s]

Reports:  82%|████████▏ | 5935/7211 [25:07<04:11,  5.07it/s]

Reports:  82%|████████▏ | 5936/7211 [25:07<04:11,  5.07it/s]

Reports:  82%|████████▏ | 5937/7211 [25:07<04:05,  5.19it/s]

Reports:  82%|████████▏ | 5938/7211 [25:07<04:05,  5.19it/s]

Reports:  82%|████████▏ | 5939/7211 [25:07<04:10,  5.08it/s]

Reports:  82%|████████▏ | 5940/7211 [25:08<04:11,  5.06it/s]

Reports:  82%|████████▏ | 5941/7211 [25:08<04:11,  5.06it/s]

Reports:  82%|████████▏ | 5942/7211 [25:08<04:11,  5.05it/s]

Reports:  82%|████████▏ | 5943/7211 [25:08<04:49,  4.39it/s]

Reports:  82%|████████▏ | 5944/7211 [25:08<04:36,  4.59it/s]

Reports:  82%|████████▏ | 5945/7211 [25:09<04:43,  4.46it/s]

Reports:  82%|████████▏ | 5946/7211 [25:09<04:32,  4.63it/s]

Reports:  82%|████████▏ | 5947/7211 [25:09<04:25,  4.75it/s]

Reports:  82%|████████▏ | 5948/7211 [25:09<04:14,  4.95it/s]

Reports:  82%|████████▏ | 5949/7211 [25:09<04:10,  5.03it/s]

Reports:  83%|████████▎ | 5950/7211 [25:10<04:07,  5.09it/s]

Reports:  83%|████████▎ | 5951/7211 [25:10<04:19,  4.86it/s]

Reports:  83%|████████▎ | 5952/7211 [25:10<04:10,  5.03it/s]

Reports:  83%|████████▎ | 5953/7211 [25:10<04:10,  5.02it/s]

Reports:  83%|████████▎ | 5954/7211 [25:10<04:06,  5.10it/s]

Reports:  83%|████████▎ | 5955/7211 [25:11<04:14,  4.93it/s]

Reports:  83%|████████▎ | 5956/7211 [25:11<04:08,  5.05it/s]

Reports:  83%|████████▎ | 5957/7211 [25:11<04:03,  5.15it/s]

Reports:  83%|████████▎ | 5958/7211 [25:11<04:13,  4.94it/s]

Reports:  83%|████████▎ | 5959/7211 [25:11<04:07,  5.06it/s]

Reports:  83%|████████▎ | 5960/7211 [25:12<04:05,  5.10it/s]

Reports:  83%|████████▎ | 5961/7211 [25:12<04:00,  5.19it/s]

Reports:  83%|████████▎ | 5962/7211 [25:12<04:01,  5.17it/s]

Reports:  83%|████████▎ | 5963/7211 [25:12<03:59,  5.22it/s]

Reports:  83%|████████▎ | 5964/7211 [25:12<03:54,  5.32it/s]

Reports:  83%|████████▎ | 5965/7211 [25:13<03:56,  5.27it/s]

Reports:  83%|████████▎ | 5966/7211 [25:13<03:57,  5.25it/s]

Reports:  83%|████████▎ | 5967/7211 [25:13<03:56,  5.25it/s]

Reports:  83%|████████▎ | 5968/7211 [25:13<03:56,  5.26it/s]

Reports:  83%|████████▎ | 5969/7211 [25:13<03:53,  5.32it/s]

Reports:  83%|████████▎ | 5970/7211 [25:14<03:52,  5.33it/s]

Reports:  83%|████████▎ | 5971/7211 [25:14<03:54,  5.29it/s]

Reports:  83%|████████▎ | 5972/7211 [25:14<03:58,  5.20it/s]

Reports:  83%|████████▎ | 5973/7211 [25:14<03:55,  5.26it/s]

Reports:  83%|████████▎ | 5974/7211 [25:14<03:59,  5.17it/s]

Reports:  83%|████████▎ | 5975/7211 [25:14<03:55,  5.26it/s]

Reports:  83%|████████▎ | 5976/7211 [25:15<03:56,  5.22it/s]

Reports:  83%|████████▎ | 5977/7211 [25:15<04:38,  4.43it/s]

Reports:  83%|████████▎ | 5978/7211 [25:15<04:24,  4.67it/s]

Reports:  83%|████████▎ | 5979/7211 [25:15<04:12,  4.88it/s]

Reports:  83%|████████▎ | 5980/7211 [25:16<04:10,  4.92it/s]

Reports:  83%|████████▎ | 5981/7211 [25:16<04:07,  4.97it/s]

Reports:  83%|████████▎ | 5982/7211 [25:16<04:05,  5.00it/s]

Reports:  83%|████████▎ | 5983/7211 [25:16<04:09,  4.92it/s]

Reports:  83%|████████▎ | 5984/7211 [25:16<04:03,  5.05it/s]

Reports:  83%|████████▎ | 5985/7211 [25:17<03:57,  5.16it/s]

Reports:  83%|████████▎ | 5986/7211 [25:17<03:59,  5.11it/s]

Reports:  83%|████████▎ | 5987/7211 [25:17<04:27,  4.58it/s]

Reports:  83%|████████▎ | 5988/7211 [25:17<04:21,  4.68it/s]

Reports:  83%|████████▎ | 5989/7211 [25:17<04:11,  4.86it/s]

Reports:  83%|████████▎ | 5990/7211 [25:18<04:03,  5.01it/s]

Reports:  83%|████████▎ | 5991/7211 [25:18<03:59,  5.09it/s]

Reports:  83%|████████▎ | 5992/7211 [25:18<03:58,  5.10it/s]

Reports:  83%|████████▎ | 5993/7211 [25:18<03:54,  5.20it/s]

Reports:  83%|████████▎ | 5994/7211 [25:18<03:51,  5.25it/s]

Reports:  83%|████████▎ | 5995/7211 [25:19<03:50,  5.27it/s]

Reports:  83%|████████▎ | 5996/7211 [25:19<03:47,  5.35it/s]

Reports:  83%|████████▎ | 5997/7211 [25:19<03:49,  5.30it/s]

Reports:  83%|████████▎ | 5998/7211 [25:19<03:48,  5.32it/s]

Reports:  83%|████████▎ | 5999/7211 [25:19<03:52,  5.20it/s]

Reports:  83%|████████▎ | 6000/7211 [25:19<03:51,  5.23it/s]

Reports:  83%|████████▎ | 6001/7211 [25:20<03:47,  5.33it/s]

Reports:  83%|████████▎ | 6002/7211 [25:20<03:52,  5.20it/s]

Reports:  83%|████████▎ | 6003/7211 [25:20<03:53,  5.16it/s]

Reports:  83%|████████▎ | 6004/7211 [25:20<03:59,  5.04it/s]

Reports:  83%|████████▎ | 6005/7211 [25:20<04:00,  5.01it/s]

Reports:  83%|████████▎ | 6006/7211 [25:21<03:52,  5.17it/s]

Reports:  83%|████████▎ | 6007/7211 [25:21<04:36,  4.36it/s]

Reports:  83%|████████▎ | 6008/7211 [25:21<04:25,  4.53it/s]

Reports:  83%|████████▎ | 6009/7211 [25:21<04:19,  4.63it/s]

Reports:  83%|████████▎ | 6010/7211 [25:22<04:10,  4.79it/s]

Reports:  83%|████████▎ | 6011/7211 [25:22<04:20,  4.60it/s]

Reports:  83%|████████▎ | 6012/7211 [25:22<04:09,  4.81it/s]

Reports:  83%|████████▎ | 6013/7211 [25:22<04:09,  4.80it/s]

Reports:  83%|████████▎ | 6014/7211 [25:22<04:02,  4.93it/s]

Reports:  83%|████████▎ | 6015/7211 [25:23<03:58,  5.02it/s]

Reports:  83%|████████▎ | 6016/7211 [25:23<03:52,  5.14it/s]

Reports:  83%|████████▎ | 6017/7211 [25:23<03:55,  5.08it/s]

Reports:  83%|████████▎ | 6018/7211 [25:23<03:49,  5.20it/s]

Reports:  83%|████████▎ | 6019/7211 [25:23<03:50,  5.18it/s]

Reports:  83%|████████▎ | 6020/7211 [25:24<04:04,  4.86it/s]

Reports:  83%|████████▎ | 6021/7211 [25:24<04:03,  4.90it/s]

Reports:  84%|████████▎ | 6022/7211 [25:24<04:01,  4.93it/s]

Reports:  84%|████████▎ | 6023/7211 [25:24<03:58,  4.99it/s]

Reports:  84%|████████▎ | 6024/7211 [25:24<03:53,  5.08it/s]

Reports:  84%|████████▎ | 6025/7211 [25:25<03:48,  5.19it/s]

Reports:  84%|████████▎ | 6026/7211 [25:25<03:45,  5.26it/s]

Reports:  84%|████████▎ | 6027/7211 [25:25<03:43,  5.30it/s]

Reports:  84%|████████▎ | 6028/7211 [25:25<03:48,  5.18it/s]

Reports:  84%|████████▎ | 6029/7211 [25:25<03:53,  5.05it/s]

Reports:  84%|████████▎ | 6030/7211 [25:25<03:50,  5.12it/s]

Reports:  84%|████████▎ | 6031/7211 [25:26<03:48,  5.16it/s]

Reports:  84%|████████▎ | 6032/7211 [25:26<03:49,  5.13it/s]

Reports:  84%|████████▎ | 6033/7211 [25:26<03:49,  5.13it/s]

Reports:  84%|████████▎ | 6034/7211 [25:26<03:45,  5.22it/s]

Reports:  84%|████████▎ | 6035/7211 [25:26<03:48,  5.15it/s]

Reports:  84%|████████▎ | 6036/7211 [25:27<03:48,  5.15it/s]

Reports:  84%|████████▎ | 6037/7211 [25:27<03:52,  5.04it/s]

Reports:  84%|████████▎ | 6038/7211 [25:27<03:47,  5.15it/s]

Reports:  84%|████████▎ | 6039/7211 [25:27<03:51,  5.06it/s]

Reports:  84%|████████▍ | 6040/7211 [25:27<03:48,  5.12it/s]

Reports:  84%|████████▍ | 6041/7211 [25:28<03:54,  4.99it/s]

Reports:  84%|████████▍ | 6042/7211 [25:28<03:55,  4.96it/s]

Reports:  84%|████████▍ | 6043/7211 [25:28<03:55,  4.97it/s]

Reports:  84%|████████▍ | 6044/7211 [25:28<03:54,  4.98it/s]

Reports:  84%|████████▍ | 6045/7211 [25:28<03:48,  5.10it/s]

Reports:  84%|████████▍ | 6046/7211 [25:29<03:44,  5.19it/s]

Reports:  84%|████████▍ | 6047/7211 [25:29<03:40,  5.27it/s]

Reports:  84%|████████▍ | 6048/7211 [25:29<03:38,  5.33it/s]

Reports:  84%|████████▍ | 6049/7211 [25:29<03:36,  5.37it/s]

Reports:  84%|████████▍ | 6050/7211 [25:29<03:41,  5.25it/s]

Reports:  84%|████████▍ | 6051/7211 [25:30<04:54,  3.94it/s]

Reports:  84%|████████▍ | 6052/7211 [25:30<04:36,  4.20it/s]

Reports:  84%|████████▍ | 6053/7211 [25:30<04:19,  4.47it/s]

Reports:  84%|████████▍ | 6054/7211 [25:30<04:10,  4.62it/s]

Reports:  84%|████████▍ | 6055/7211 [25:31<05:05,  3.78it/s]

Reports:  84%|████████▍ | 6056/7211 [25:31<04:38,  4.15it/s]

Reports:  84%|████████▍ | 6057/7211 [25:31<04:20,  4.44it/s]

Reports:  84%|████████▍ | 6058/7211 [25:31<04:08,  4.64it/s]

Reports:  84%|████████▍ | 6059/7211 [25:31<03:57,  4.85it/s]

Reports:  84%|████████▍ | 6060/7211 [25:32<03:56,  4.87it/s]

Reports:  84%|████████▍ | 6061/7211 [25:32<03:55,  4.89it/s]

Reports:  84%|████████▍ | 6062/7211 [25:32<03:48,  5.03it/s]

Reports:  84%|████████▍ | 6063/7211 [25:32<03:47,  5.05it/s]

Reports:  84%|████████▍ | 6064/7211 [25:32<03:45,  5.08it/s]

Reports:  84%|████████▍ | 6065/7211 [25:33<03:44,  5.12it/s]

Reports:  84%|████████▍ | 6066/7211 [25:33<03:45,  5.08it/s]

Reports:  84%|████████▍ | 6067/7211 [25:33<03:42,  5.13it/s]

Reports:  84%|████████▍ | 6068/7211 [25:33<03:39,  5.21it/s]

Reports:  84%|████████▍ | 6069/7211 [25:33<03:38,  5.23it/s]

Reports:  84%|████████▍ | 6070/7211 [25:34<03:42,  5.12it/s]

Reports:  84%|████████▍ | 6071/7211 [25:34<03:42,  5.12it/s]

Reports:  84%|████████▍ | 6072/7211 [25:34<03:40,  5.17it/s]

Reports:  84%|████████▍ | 6073/7211 [25:34<03:39,  5.18it/s]

Reports:  84%|████████▍ | 6074/7211 [25:34<03:43,  5.08it/s]

Reports:  84%|████████▍ | 6075/7211 [25:35<03:40,  5.15it/s]

Reports:  84%|████████▍ | 6076/7211 [25:35<03:45,  5.02it/s]

Reports:  84%|████████▍ | 6077/7211 [25:35<03:44,  5.06it/s]

Reports:  84%|████████▍ | 6078/7211 [25:35<04:02,  4.67it/s]

Reports:  84%|████████▍ | 6079/7211 [25:57<2:03:04,  6.52s/it]

Reports:  84%|████████▍ | 6080/7211 [25:57<1:27:15,  4.63s/it]

Reports:  84%|████████▍ | 6081/7211 [25:57<1:02:11,  3.30s/it]

Reports:  84%|████████▍ | 6082/7211 [25:57<44:40,  2.37s/it]

Reports:  84%|████████▍ | 6083/7211 [25:57<32:20,  1.72s/it]

Reports:  84%|████████▍ | 6084/7211 [25:58<23:39,  1.26s/it]

Reports:  84%|████████▍ | 6085/7211 [25:58<17:36,  1.07it/s]

Reports:  84%|████████▍ | 6086/7211 [25:58<13:26,  1.39it/s]

Reports:  84%|████████▍ | 6087/7211 [25:58<10:32,  1.78it/s]

Reports:  84%|████████▍ | 6088/7211 [25:58<08:26,  2.22it/s]

Reports:  84%|████████▍ | 6089/7211 [25:58<06:55,  2.70it/s]

Reports:  84%|████████▍ | 6090/7211 [25:59<05:54,  3.16it/s]

Reports:  84%|████████▍ | 6091/7211 [25:59<05:13,  3.57it/s]

Reports:  84%|████████▍ | 6092/7211 [25:59<04:42,  3.96it/s]

Reports:  84%|████████▍ | 6093/7211 [25:59<04:21,  4.28it/s]

Reports:  85%|████████▍ | 6094/7211 [25:59<04:09,  4.47it/s]

Reports:  85%|████████▍ | 6095/7211 [26:00<03:58,  4.69it/s]

Reports:  85%|████████▍ | 6096/7211 [26:00<03:53,  4.78it/s]

Reports:  85%|████████▍ | 6097/7211 [26:00<03:49,  4.86it/s]

Reports:  85%|████████▍ | 6098/7211 [26:00<03:41,  5.01it/s]

Reports:  85%|████████▍ | 6099/7211 [26:00<03:38,  5.08it/s]

Reports:  85%|████████▍ | 6100/7211 [26:01<04:03,  4.56it/s]

Reports:  85%|████████▍ | 6101/7211 [26:01<03:57,  4.68it/s]

Reports:  85%|████████▍ | 6102/7211 [26:01<03:50,  4.81it/s]

Reports:  85%|████████▍ | 6103/7211 [26:01<03:49,  4.82it/s]

Reports:  85%|████████▍ | 6104/7211 [26:01<03:42,  4.98it/s]

Reports:  85%|████████▍ | 6105/7211 [26:02<03:42,  4.98it/s]

Reports:  85%|████████▍ | 6106/7211 [26:02<03:39,  5.05it/s]

Reports:  85%|████████▍ | 6107/7211 [26:02<03:30,  5.24it/s]

Reports:  85%|████████▍ | 6108/7211 [26:02<03:33,  5.17it/s]

Reports:  85%|████████▍ | 6109/7211 [26:02<03:35,  5.11it/s]

Reports:  85%|████████▍ | 6110/7211 [26:03<03:33,  5.17it/s]

Reports:  85%|████████▍ | 6111/7211 [26:03<03:33,  5.16it/s]

Reports:  85%|████████▍ | 6112/7211 [26:03<03:32,  5.17it/s]

Reports:  85%|████████▍ | 6113/7211 [26:03<03:31,  5.19it/s]

Reports:  85%|████████▍ | 6114/7211 [26:03<03:29,  5.23it/s]

Reports:  85%|████████▍ | 6115/7211 [26:04<03:26,  5.30it/s]

Reports:  85%|████████▍ | 6116/7211 [26:04<03:28,  5.26it/s]

Reports:  85%|████████▍ | 6117/7211 [26:04<03:26,  5.29it/s]

Reports:  85%|████████▍ | 6118/7211 [26:04<03:28,  5.25it/s]

Reports:  85%|████████▍ | 6119/7211 [26:04<03:27,  5.26it/s]

Reports:  85%|████████▍ | 6120/7211 [26:05<03:30,  5.18it/s]

Reports:  85%|████████▍ | 6121/7211 [26:05<03:33,  5.10it/s]

Reports:  85%|████████▍ | 6122/7211 [26:05<03:29,  5.19it/s]

Reports:  85%|████████▍ | 6123/7211 [26:05<03:30,  5.16it/s]

Reports:  85%|████████▍ | 6124/7211 [26:05<03:26,  5.26it/s]

Reports:  85%|████████▍ | 6125/7211 [26:05<03:24,  5.30it/s]

Reports:  85%|████████▍ | 6126/7211 [26:06<03:25,  5.29it/s]

Reports:  85%|████████▍ | 6127/7211 [26:06<03:28,  5.20it/s]

Reports:  85%|████████▍ | 6128/7211 [26:06<03:28,  5.20it/s]

Reports:  85%|████████▍ | 6129/7211 [26:06<03:26,  5.23it/s]

Reports:  85%|████████▌ | 6130/7211 [26:06<03:26,  5.23it/s]

Reports:  85%|████████▌ | 6131/7211 [26:07<03:25,  5.26it/s]

Reports:  85%|████████▌ | 6132/7211 [26:07<03:29,  5.15it/s]

Reports:  85%|████████▌ | 6133/7211 [26:07<03:33,  5.04it/s]

Reports:  85%|████████▌ | 6134/7211 [26:07<03:42,  4.85it/s]

Reports:  85%|████████▌ | 6135/7211 [26:08<04:08,  4.33it/s]

Reports:  85%|████████▌ | 6136/7211 [26:08<04:12,  4.26it/s]

Reports:  85%|████████▌ | 6137/7211 [26:08<04:06,  4.35it/s]

Reports:  85%|████████▌ | 6138/7211 [26:08<04:32,  3.93it/s]

Reports:  85%|████████▌ | 6139/7211 [26:09<04:16,  4.17it/s]

Reports:  85%|████████▌ | 6140/7211 [26:09<04:00,  4.45it/s]

Reports:  85%|████████▌ | 6141/7211 [26:09<03:48,  4.68it/s]

Reports:  85%|████████▌ | 6142/7211 [26:09<03:40,  4.85it/s]

Reports:  85%|████████▌ | 6143/7211 [26:09<03:39,  4.86it/s]

Reports:  85%|████████▌ | 6144/7211 [26:10<03:40,  4.84it/s]

Reports:  85%|████████▌ | 6145/7211 [26:10<03:41,  4.80it/s]

Reports:  85%|████████▌ | 6146/7211 [26:10<03:41,  4.80it/s]

Reports:  85%|████████▌ | 6147/7211 [26:10<03:37,  4.90it/s]

Reports:  85%|████████▌ | 6148/7211 [26:10<03:33,  4.99it/s]

Reports:  85%|████████▌ | 6149/7211 [26:11<03:32,  5.00it/s]

Reports:  85%|████████▌ | 6150/7211 [26:11<03:33,  4.97it/s]

Reports:  85%|████████▌ | 6151/7211 [26:11<03:30,  5.04it/s]

Reports:  85%|████████▌ | 6152/7211 [26:11<03:25,  5.16it/s]

Reports:  85%|████████▌ | 6153/7211 [26:11<03:25,  5.16it/s]

Reports:  85%|████████▌ | 6154/7211 [26:11<03:22,  5.21it/s]

Reports:  85%|████████▌ | 6155/7211 [26:12<03:25,  5.15it/s]

Reports:  85%|████████▌ | 6156/7211 [26:12<03:22,  5.22it/s]

Reports:  85%|████████▌ | 6157/7211 [26:12<03:21,  5.24it/s]

Reports:  85%|████████▌ | 6158/7211 [26:12<03:20,  5.25it/s]

Reports:  85%|████████▌ | 6159/7211 [26:12<03:20,  5.24it/s]

Reports:  85%|████████▌ | 6160/7211 [26:13<03:49,  4.57it/s]

Reports:  85%|████████▌ | 6161/7211 [26:13<03:43,  4.70it/s]

Reports:  85%|████████▌ | 6162/7211 [26:13<03:35,  4.86it/s]

Reports:  85%|████████▌ | 6163/7211 [26:13<03:29,  4.99it/s]

Reports:  85%|████████▌ | 6164/7211 [26:13<03:29,  4.99it/s]

Reports:  85%|████████▌ | 6165/7211 [26:14<04:05,  4.26it/s]

Reports:  86%|████████▌ | 6166/7211 [26:14<03:53,  4.48it/s]

Reports:  86%|████████▌ | 6167/7211 [26:14<03:43,  4.68it/s]

Reports:  86%|████████▌ | 6168/7211 [26:14<03:37,  4.79it/s]

Reports:  86%|████████▌ | 6169/7211 [26:15<03:30,  4.95it/s]

Reports:  86%|████████▌ | 6170/7211 [26:15<03:31,  4.93it/s]

Reports:  86%|████████▌ | 6171/7211 [26:15<03:28,  5.00it/s]

Reports:  86%|████████▌ | 6172/7211 [26:15<03:28,  4.99it/s]

Reports:  86%|████████▌ | 6173/7211 [26:15<03:24,  5.07it/s]

Reports:  86%|████████▌ | 6174/7211 [26:16<03:23,  5.10it/s]

Reports:  86%|████████▌ | 6175/7211 [26:16<03:19,  5.19it/s]

Reports:  86%|████████▌ | 6176/7211 [26:16<03:20,  5.15it/s]

Reports:  86%|████████▌ | 6177/7211 [26:16<03:20,  5.16it/s]

Reports:  86%|████████▌ | 6178/7211 [26:16<03:16,  5.27it/s]

Reports:  86%|████████▌ | 6179/7211 [26:17<03:15,  5.28it/s]

Reports:  86%|████████▌ | 6180/7211 [26:17<03:15,  5.27it/s]

Reports:  86%|████████▌ | 6181/7211 [26:17<03:13,  5.33it/s]

Reports:  86%|████████▌ | 6182/7211 [26:17<03:14,  5.29it/s]

Reports:  86%|████████▌ | 6183/7211 [26:17<03:16,  5.23it/s]

Reports:  86%|████████▌ | 6184/7211 [26:17<03:15,  5.27it/s]

Reports:  86%|████████▌ | 6185/7211 [26:18<03:13,  5.29it/s]

Reports:  86%|████████▌ | 6186/7211 [26:18<03:15,  5.25it/s]

Reports:  86%|████████▌ | 6187/7211 [26:18<03:16,  5.20it/s]

Reports:  86%|████████▌ | 6188/7211 [26:18<03:19,  5.13it/s]

Reports:  86%|████████▌ | 6189/7211 [26:18<03:24,  5.01it/s]

Reports:  86%|████████▌ | 6190/7211 [26:19<03:24,  4.99it/s]

Reports:  86%|████████▌ | 6191/7211 [26:19<03:24,  5.00it/s]

Reports:  86%|████████▌ | 6192/7211 [26:19<03:21,  5.07it/s]

Reports:  86%|████████▌ | 6193/7211 [26:19<03:21,  5.06it/s]

Reports:  86%|████████▌ | 6194/7211 [26:19<03:21,  5.04it/s]

Reports:  86%|████████▌ | 6195/7211 [26:20<03:18,  5.11it/s]

Reports:  86%|████████▌ | 6196/7211 [26:20<03:19,  5.09it/s]

Reports:  86%|████████▌ | 6197/7211 [26:20<03:17,  5.14it/s]

Reports:  86%|████████▌ | 6198/7211 [26:20<03:19,  5.08it/s]

Reports:  86%|████████▌ | 6199/7211 [26:20<03:17,  5.11it/s]

Reports:  86%|████████▌ | 6200/7211 [26:21<03:16,  5.15it/s]

Reports:  86%|████████▌ | 6201/7211 [26:21<03:18,  5.08it/s]

Reports:  86%|████████▌ | 6202/7211 [26:21<03:16,  5.14it/s]

Reports:  86%|████████▌ | 6203/7211 [26:21<03:17,  5.11it/s]

Reports:  86%|████████▌ | 6204/7211 [26:21<03:14,  5.17it/s]

Reports:  86%|████████▌ | 6205/7211 [26:22<03:13,  5.20it/s]

Reports:  86%|████████▌ | 6206/7211 [26:22<03:12,  5.23it/s]

Reports:  86%|████████▌ | 6207/7211 [26:22<03:13,  5.18it/s]

Reports:  86%|████████▌ | 6208/7211 [26:22<03:14,  5.14it/s]

Reports:  86%|████████▌ | 6209/7211 [26:22<03:14,  5.14it/s]

Reports:  86%|████████▌ | 6210/7211 [26:23<03:18,  5.05it/s]

Reports:  86%|████████▌ | 6211/7211 [26:23<03:14,  5.14it/s]

Reports:  86%|████████▌ | 6212/7211 [26:23<03:12,  5.20it/s]

Reports:  86%|████████▌ | 6213/7211 [26:23<03:11,  5.22it/s]

Reports:  86%|████████▌ | 6214/7211 [26:23<03:13,  5.14it/s]

Reports:  86%|████████▌ | 6215/7211 [26:24<03:10,  5.22it/s]

Reports:  86%|████████▌ | 6216/7211 [26:24<03:12,  5.18it/s]

Reports:  86%|████████▌ | 6217/7211 [26:24<03:09,  5.26it/s]

Reports:  86%|████████▌ | 6218/7211 [26:24<03:07,  5.29it/s]

Reports:  86%|████████▌ | 6219/7211 [26:24<03:08,  5.25it/s]

Reports:  86%|████████▋ | 6220/7211 [26:24<03:15,  5.08it/s]

Reports:  86%|████████▋ | 6221/7211 [26:25<03:13,  5.12it/s]

Reports:  86%|████████▋ | 6222/7211 [26:25<03:10,  5.19it/s]

Reports:  86%|████████▋ | 6223/7211 [26:25<03:09,  5.21it/s]

Reports:  86%|████████▋ | 6224/7211 [26:25<03:08,  5.23it/s]

Reports:  86%|████████▋ | 6225/7211 [26:25<03:09,  5.19it/s]

Reports:  86%|████████▋ | 6226/7211 [26:26<03:07,  5.25it/s]

Reports:  86%|████████▋ | 6227/7211 [26:26<03:08,  5.21it/s]

Reports:  86%|████████▋ | 6228/7211 [26:26<03:10,  5.17it/s]

Reports:  86%|████████▋ | 6229/7211 [26:26<03:09,  5.19it/s]

Reports:  86%|████████▋ | 6230/7211 [26:26<03:05,  5.28it/s]

Reports:  86%|████████▋ | 6231/7211 [26:27<03:09,  5.16it/s]

Reports:  86%|████████▋ | 6232/7211 [26:27<03:11,  5.11it/s]

Reports:  86%|████████▋ | 6233/7211 [26:27<03:06,  5.25it/s]

Reports:  86%|████████▋ | 6234/7211 [26:27<03:09,  5.15it/s]

Reports:  86%|████████▋ | 6235/7211 [26:27<03:13,  5.05it/s]

Reports:  86%|████████▋ | 6236/7211 [26:28<03:11,  5.10it/s]

Reports:  86%|████████▋ | 6237/7211 [26:28<03:11,  5.08it/s]

Reports:  87%|████████▋ | 6238/7211 [26:28<03:10,  5.11it/s]

Reports:  87%|████████▋ | 6239/7211 [26:28<03:06,  5.20it/s]

Reports:  87%|████████▋ | 6240/7211 [26:28<03:05,  5.22it/s]

Reports:  87%|████████▋ | 6241/7211 [26:29<03:03,  5.28it/s]

Reports:  87%|████████▋ | 6242/7211 [26:29<03:05,  5.23it/s]

Reports:  87%|████████▋ | 6243/7211 [26:29<03:05,  5.22it/s]

Reports:  87%|████████▋ | 6244/7211 [26:29<03:03,  5.28it/s]

Reports:  87%|████████▋ | 6245/7211 [26:29<03:04,  5.22it/s]

Reports:  87%|████████▋ | 6246/7211 [26:29<03:05,  5.21it/s]

Reports:  87%|████████▋ | 6247/7211 [26:30<03:04,  5.24it/s]

Reports:  87%|████████▋ | 6248/7211 [26:30<03:05,  5.20it/s]

Reports:  87%|████████▋ | 6249/7211 [26:30<03:03,  5.24it/s]

Reports:  87%|████████▋ | 6250/7211 [26:30<03:03,  5.23it/s]

Reports:  87%|████████▋ | 6251/7211 [26:30<03:05,  5.19it/s]

Reports:  87%|████████▋ | 6252/7211 [26:31<03:04,  5.20it/s]

Reports:  87%|████████▋ | 6253/7211 [26:31<03:02,  5.26it/s]

Reports:  87%|████████▋ | 6254/7211 [26:31<03:04,  5.18it/s]

Reports:  87%|████████▋ | 6255/7211 [26:31<03:03,  5.21it/s]

Reports:  87%|████████▋ | 6256/7211 [26:31<03:06,  5.13it/s]

Reports:  87%|████████▋ | 6257/7211 [26:32<03:07,  5.08it/s]

Reports:  87%|████████▋ | 6258/7211 [26:32<03:04,  5.15it/s]

Reports:  87%|████████▋ | 6259/7211 [26:32<03:03,  5.20it/s]

Reports:  87%|████████▋ | 6260/7211 [26:32<03:00,  5.26it/s]

Reports:  87%|████████▋ | 6261/7211 [26:32<02:57,  5.35it/s]

Reports:  87%|████████▋ | 6262/7211 [26:33<03:02,  5.19it/s]

Reports:  87%|████████▋ | 6263/7211 [26:33<03:01,  5.24it/s]

Reports:  87%|████████▋ | 6264/7211 [26:33<03:01,  5.23it/s]

Reports:  87%|████████▋ | 6265/7211 [26:33<03:03,  5.16it/s]

Reports:  87%|████████▋ | 6266/7211 [26:33<03:05,  5.09it/s]

Reports:  87%|████████▋ | 6267/7211 [26:34<03:05,  5.08it/s]

Reports:  87%|████████▋ | 6268/7211 [26:34<03:05,  5.09it/s]

Reports:  87%|████████▋ | 6269/7211 [26:34<03:05,  5.06it/s]

Reports:  87%|████████▋ | 6270/7211 [26:34<03:05,  5.08it/s]

Reports:  87%|████████▋ | 6271/7211 [26:34<03:04,  5.08it/s]

Reports:  87%|████████▋ | 6272/7211 [26:34<03:01,  5.17it/s]

Reports:  87%|████████▋ | 6273/7211 [26:35<03:02,  5.13it/s]

Reports:  87%|████████▋ | 6274/7211 [26:35<03:01,  5.17it/s]

Reports:  87%|████████▋ | 6275/7211 [26:35<03:03,  5.09it/s]

Reports:  87%|████████▋ | 6276/7211 [26:35<03:07,  5.00it/s]

Reports:  87%|████████▋ | 6277/7211 [26:35<03:03,  5.10it/s]

Reports:  87%|████████▋ | 6278/7211 [26:36<03:04,  5.07it/s]

Reports:  87%|████████▋ | 6279/7211 [26:36<04:56,  3.15it/s]

Reports:  87%|████████▋ | 6280/7211 [26:36<04:18,  3.59it/s]

Reports:  87%|████████▋ | 6281/7211 [26:37<03:55,  3.94it/s]

Reports:  87%|████████▋ | 6282/7211 [26:37<03:41,  4.20it/s]

Reports:  87%|████████▋ | 6283/7211 [26:37<03:26,  4.49it/s]

Reports:  87%|████████▋ | 6284/7211 [26:37<03:17,  4.69it/s]

Reports:  87%|████████▋ | 6285/7211 [26:37<03:10,  4.85it/s]

Reports:  87%|████████▋ | 6286/7211 [26:38<03:11,  4.82it/s]

Reports:  87%|████████▋ | 6287/7211 [26:38<03:07,  4.94it/s]

Reports:  87%|████████▋ | 6288/7211 [26:38<03:03,  5.04it/s]

Reports:  87%|████████▋ | 6289/7211 [26:39<08:55,  1.72it/s]

Reports:  87%|████████▋ | 6290/7211 [26:40<07:09,  2.14it/s]

Reports:  87%|████████▋ | 6291/7211 [26:40<05:51,  2.62it/s]

Reports:  87%|████████▋ | 6292/7211 [26:40<05:03,  3.03it/s]

Reports:  87%|████████▋ | 6293/7211 [26:40<04:24,  3.47it/s]

Reports:  87%|████████▋ | 6294/7211 [26:40<03:56,  3.88it/s]

Reports:  87%|████████▋ | 6295/7211 [26:41<03:44,  4.09it/s]

Reports:  87%|████████▋ | 6296/7211 [26:41<03:33,  4.29it/s]

Reports:  87%|████████▋ | 6297/7211 [26:41<03:21,  4.53it/s]

Reports:  87%|████████▋ | 6298/7211 [26:41<03:17,  4.62it/s]

Reports:  87%|████████▋ | 6299/7211 [26:41<03:11,  4.76it/s]

Reports:  87%|████████▋ | 6300/7211 [26:42<03:06,  4.88it/s]

Reports:  87%|████████▋ | 6301/7211 [26:42<03:08,  4.83it/s]

Reports:  87%|████████▋ | 6302/7211 [26:42<03:07,  4.85it/s]

Reports:  87%|████████▋ | 6303/7211 [26:42<03:04,  4.91it/s]

Reports:  87%|████████▋ | 6304/7211 [26:42<02:58,  5.08it/s]

Reports:  87%|████████▋ | 6305/7211 [26:43<05:19,  2.84it/s]

Reports:  87%|████████▋ | 6306/7211 [26:43<04:32,  3.32it/s]

Reports:  87%|████████▋ | 6307/7211 [26:44<04:03,  3.72it/s]

Reports:  87%|████████▋ | 6308/7211 [26:44<03:49,  3.93it/s]

Reports:  87%|████████▋ | 6309/7211 [26:44<03:31,  4.26it/s]

Reports:  88%|████████▊ | 6310/7211 [26:44<03:23,  4.42it/s]

Reports:  88%|████████▊ | 6311/7211 [26:44<03:14,  4.63it/s]

Reports:  88%|████████▊ | 6312/7211 [26:45<03:08,  4.77it/s]

Reports:  88%|████████▊ | 6313/7211 [26:45<03:09,  4.74it/s]

Reports:  88%|████████▊ | 6314/7211 [26:45<03:04,  4.87it/s]

Reports:  88%|████████▊ | 6315/7211 [26:45<03:00,  4.96it/s]

Reports:  88%|████████▊ | 6316/7211 [26:45<02:58,  5.02it/s]

Reports:  88%|████████▊ | 6317/7211 [26:46<03:47,  3.93it/s]

Reports:  88%|████████▊ | 6318/7211 [26:46<03:35,  4.14it/s]

Reports:  88%|████████▊ | 6319/7211 [26:46<03:22,  4.42it/s]

Reports:  88%|████████▊ | 6320/7211 [26:46<03:15,  4.55it/s]

Reports:  88%|████████▊ | 6321/7211 [26:47<03:10,  4.66it/s]

Reports:  88%|████████▊ | 6322/7211 [26:47<03:03,  4.85it/s]

Reports:  88%|████████▊ | 6323/7211 [26:47<03:00,  4.93it/s]

Reports:  88%|████████▊ | 6324/7211 [26:47<03:00,  4.91it/s]

Reports:  88%|████████▊ | 6325/7211 [26:47<03:00,  4.91it/s]

Reports:  88%|████████▊ | 6326/7211 [26:48<02:55,  5.05it/s]

Reports:  88%|████████▊ | 6327/7211 [26:48<02:55,  5.04it/s]

Reports:  88%|████████▊ | 6328/7211 [26:48<02:52,  5.12it/s]

Reports:  88%|████████▊ | 6329/7211 [26:48<02:50,  5.16it/s]

Reports:  88%|████████▊ | 6330/7211 [26:48<02:50,  5.17it/s]

Reports:  88%|████████▊ | 6331/7211 [26:48<02:51,  5.14it/s]

Reports:  88%|████████▊ | 6332/7211 [26:49<02:48,  5.22it/s]

Reports:  88%|████████▊ | 6333/7211 [26:49<02:52,  5.09it/s]

Reports:  88%|████████▊ | 6334/7211 [26:49<02:52,  5.10it/s]

Reports:  88%|████████▊ | 6335/7211 [26:49<02:55,  5.00it/s]

Reports:  88%|████████▊ | 6336/7211 [26:49<02:50,  5.14it/s]

Reports:  88%|████████▊ | 6337/7211 [26:50<02:52,  5.08it/s]

Reports:  88%|████████▊ | 6338/7211 [26:50<04:30,  3.23it/s]

Reports:  88%|████████▊ | 6339/7211 [26:50<03:59,  3.64it/s]

Reports:  88%|████████▊ | 6340/7211 [26:51<03:37,  4.00it/s]

Reports:  88%|████████▊ | 6341/7211 [26:51<03:24,  4.26it/s]

Reports:  88%|████████▊ | 6342/7211 [26:51<03:12,  4.51it/s]

Reports:  88%|████████▊ | 6343/7211 [26:51<03:04,  4.70it/s]

Reports:  88%|████████▊ | 6344/7211 [26:51<03:02,  4.75it/s]

Reports:  88%|████████▊ | 6345/7211 [26:52<02:57,  4.89it/s]

Reports:  88%|████████▊ | 6346/7211 [26:52<02:52,  5.03it/s]

Reports:  88%|████████▊ | 6347/7211 [26:52<02:48,  5.13it/s]

Reports:  88%|████████▊ | 6348/7211 [26:55<14:23,  1.00s/it]

Reports:  88%|████████▊ | 6349/7211 [26:55<10:56,  1.31it/s]

Reports:  88%|████████▊ | 6350/7211 [26:55<08:28,  1.69it/s]

Reports:  88%|████████▊ | 6351/7211 [26:55<06:45,  2.12it/s]

Reports:  88%|████████▊ | 6352/7211 [26:56<05:33,  2.58it/s]

Reports:  88%|████████▊ | 6353/7211 [26:56<04:48,  2.97it/s]

Reports:  88%|████████▊ | 6354/7211 [26:56<04:10,  3.43it/s]

Reports:  88%|████████▊ | 6355/7211 [26:56<03:40,  3.88it/s]

Reports:  88%|████████▊ | 6356/7211 [26:56<03:26,  4.14it/s]

Reports:  88%|████████▊ | 6357/7211 [26:57<03:12,  4.44it/s]

Reports:  88%|████████▊ | 6358/7211 [26:57<03:03,  4.66it/s]

Reports:  88%|████████▊ | 6359/7211 [26:57<02:56,  4.82it/s]

Reports:  88%|████████▊ | 6360/7211 [26:57<02:51,  4.97it/s]

Reports:  88%|████████▊ | 6361/7211 [26:57<02:46,  5.11it/s]

Reports:  88%|████████▊ | 6362/7211 [26:58<02:45,  5.12it/s]

Reports:  88%|████████▊ | 6363/7211 [26:58<02:45,  5.14it/s]

Reports:  88%|████████▊ | 6364/7211 [26:58<02:41,  5.25it/s]

Reports:  88%|████████▊ | 6365/7211 [26:58<02:45,  5.12it/s]

Reports:  88%|████████▊ | 6366/7211 [26:58<02:41,  5.22it/s]

Reports:  88%|████████▊ | 6367/7211 [26:59<02:43,  5.16it/s]

Reports:  88%|████████▊ | 6368/7211 [26:59<02:42,  5.19it/s]

Reports:  88%|████████▊ | 6369/7211 [26:59<02:41,  5.21it/s]

Reports:  88%|████████▊ | 6370/7211 [26:59<02:41,  5.21it/s]

Reports:  88%|████████▊ | 6371/7211 [26:59<02:40,  5.25it/s]

Reports:  88%|████████▊ | 6372/7211 [26:59<02:39,  5.25it/s]

Reports:  88%|████████▊ | 6373/7211 [27:00<02:41,  5.19it/s]

Reports:  88%|████████▊ | 6374/7211 [27:00<02:45,  5.07it/s]

Reports:  88%|████████▊ | 6375/7211 [27:00<02:43,  5.12it/s]

Reports:  88%|████████▊ | 6376/7211 [27:00<02:39,  5.23it/s]

Reports:  88%|████████▊ | 6377/7211 [27:00<02:41,  5.16it/s]

Reports:  88%|████████▊ | 6378/7211 [27:01<02:38,  5.26it/s]

Reports:  88%|████████▊ | 6379/7211 [27:01<02:40,  5.19it/s]

Reports:  88%|████████▊ | 6380/7211 [27:01<02:38,  5.25it/s]

Reports:  88%|████████▊ | 6381/7211 [27:01<02:40,  5.18it/s]

Reports:  89%|████████▊ | 6382/7211 [27:01<02:41,  5.14it/s]

Reports:  89%|████████▊ | 6383/7211 [27:02<02:38,  5.21it/s]

Reports:  89%|████████▊ | 6384/7211 [27:02<02:41,  5.13it/s]

Reports:  89%|████████▊ | 6385/7211 [27:02<02:47,  4.94it/s]

Reports:  89%|████████▊ | 6386/7211 [27:02<02:43,  5.06it/s]

Reports:  89%|████████▊ | 6387/7211 [27:02<02:47,  4.93it/s]

Reports:  89%|████████▊ | 6388/7211 [27:03<02:42,  5.06it/s]

Reports:  89%|████████▊ | 6389/7211 [27:03<02:43,  5.03it/s]

Reports:  89%|████████▊ | 6390/7211 [27:03<02:44,  5.00it/s]

Reports:  89%|████████▊ | 6391/7211 [27:03<02:45,  4.97it/s]

Reports:  89%|████████▊ | 6392/7211 [27:03<02:47,  4.90it/s]

Reports:  89%|████████▊ | 6393/7211 [27:04<02:47,  4.89it/s]

Reports:  89%|████████▊ | 6394/7211 [27:04<02:48,  4.85it/s]

Reports:  89%|████████▊ | 6395/7211 [27:04<02:45,  4.93it/s]

Reports:  89%|████████▊ | 6396/7211 [27:04<02:39,  5.10it/s]

Reports:  89%|████████▊ | 6397/7211 [27:04<02:44,  4.94it/s]

Reports:  89%|████████▊ | 6398/7211 [27:05<02:43,  4.97it/s]

Reports:  89%|████████▊ | 6399/7211 [27:05<02:39,  5.10it/s]

Reports:  89%|████████▉ | 6400/7211 [27:05<02:39,  5.07it/s]

Reports:  89%|████████▉ | 6401/7211 [27:05<02:40,  5.04it/s]

Reports:  89%|████████▉ | 6402/7211 [27:05<02:45,  4.89it/s]

Reports:  89%|████████▉ | 6403/7211 [27:06<02:41,  4.99it/s]

Reports:  89%|████████▉ | 6404/7211 [27:06<02:37,  5.12it/s]

Reports:  89%|████████▉ | 6405/7211 [27:06<02:37,  5.12it/s]

Reports:  89%|████████▉ | 6406/7211 [27:06<02:42,  4.96it/s]

Reports:  89%|████████▉ | 6407/7211 [27:06<02:45,  4.84it/s]

Reports:  89%|████████▉ | 6408/7211 [27:07<02:41,  4.96it/s]

Reports:  89%|████████▉ | 6409/7211 [27:07<02:45,  4.84it/s]

Reports:  89%|████████▉ | 6410/7211 [27:07<02:43,  4.89it/s]

Reports:  89%|████████▉ | 6411/7211 [27:07<02:42,  4.92it/s]

Reports:  89%|████████▉ | 6412/7211 [27:07<02:41,  4.96it/s]

Reports:  89%|████████▉ | 6413/7211 [27:08<02:39,  5.00it/s]

Reports:  89%|████████▉ | 6414/7211 [27:08<02:43,  4.87it/s]

Reports:  89%|████████▉ | 6415/7211 [27:08<02:40,  4.96it/s]

Reports:  89%|████████▉ | 6416/7211 [27:08<02:36,  5.08it/s]

Reports:  89%|████████▉ | 6417/7211 [27:08<02:36,  5.07it/s]

Reports:  89%|████████▉ | 6418/7211 [27:09<02:37,  5.03it/s]

Reports:  89%|████████▉ | 6419/7211 [27:09<02:37,  5.02it/s]

Reports:  89%|████████▉ | 6420/7211 [27:09<02:33,  5.16it/s]

Reports:  89%|████████▉ | 6421/7211 [27:09<02:30,  5.25it/s]

Reports:  89%|████████▉ | 6422/7211 [27:09<02:28,  5.30it/s]

Reports:  89%|████████▉ | 6423/7211 [27:10<02:30,  5.25it/s]

Reports:  89%|████████▉ | 6424/7211 [27:10<02:28,  5.29it/s]

Reports:  89%|████████▉ | 6425/7211 [27:10<02:32,  5.16it/s]

Reports:  89%|████████▉ | 6426/7211 [27:10<02:31,  5.17it/s]

Reports:  89%|████████▉ | 6427/7211 [27:10<02:31,  5.17it/s]

Reports:  89%|████████▉ | 6428/7211 [27:11<02:32,  5.14it/s]

Reports:  89%|████████▉ | 6429/7211 [27:11<02:32,  5.12it/s]

Reports:  89%|████████▉ | 6430/7211 [27:11<02:36,  4.99it/s]

Reports:  89%|████████▉ | 6431/7211 [27:11<02:32,  5.10it/s]

Reports:  89%|████████▉ | 6432/7211 [27:11<02:32,  5.10it/s]

Reports:  89%|████████▉ | 6433/7211 [27:12<02:32,  5.12it/s]

Reports:  89%|████████▉ | 6434/7211 [27:12<02:31,  5.14it/s]

Reports:  89%|████████▉ | 6435/7211 [27:12<02:35,  5.00it/s]

Reports:  89%|████████▉ | 6436/7211 [27:12<02:34,  5.01it/s]

Reports:  89%|████████▉ | 6437/7211 [27:12<02:35,  4.99it/s]

Reports:  89%|████████▉ | 6438/7211 [27:13<02:34,  5.01it/s]

Reports:  89%|████████▉ | 6439/7211 [27:13<02:32,  5.07it/s]

Reports:  89%|████████▉ | 6440/7211 [27:13<02:31,  5.10it/s]

Reports:  89%|████████▉ | 6441/7211 [27:13<02:29,  5.14it/s]

Reports:  89%|████████▉ | 6442/7211 [27:13<02:28,  5.17it/s]

Reports:  89%|████████▉ | 6443/7211 [27:14<02:29,  5.13it/s]

Reports:  89%|████████▉ | 6444/7211 [27:14<02:30,  5.11it/s]

Reports:  89%|████████▉ | 6445/7211 [27:14<02:28,  5.15it/s]

Reports:  89%|████████▉ | 6446/7211 [27:14<02:30,  5.09it/s]

Reports:  89%|████████▉ | 6447/7211 [27:14<02:29,  5.13it/s]

Reports:  89%|████████▉ | 6448/7211 [27:14<02:26,  5.22it/s]

Reports:  89%|████████▉ | 6449/7211 [27:15<02:24,  5.28it/s]

Reports:  89%|████████▉ | 6450/7211 [27:15<02:22,  5.32it/s]

Reports:  89%|████████▉ | 6451/7211 [27:15<02:26,  5.20it/s]

Reports:  89%|████████▉ | 6452/7211 [27:15<02:26,  5.18it/s]

Reports:  89%|████████▉ | 6453/7211 [27:15<02:25,  5.22it/s]

Reports:  90%|████████▉ | 6454/7211 [27:16<02:24,  5.23it/s]

Reports:  90%|████████▉ | 6455/7211 [27:16<02:23,  5.29it/s]

Reports:  90%|████████▉ | 6456/7211 [27:16<02:25,  5.20it/s]

Reports:  90%|████████▉ | 6457/7211 [27:16<02:25,  5.17it/s]

Reports:  90%|████████▉ | 6458/7211 [27:16<02:25,  5.18it/s]

Reports:  90%|████████▉ | 6459/7211 [27:17<02:22,  5.27it/s]

Reports:  90%|████████▉ | 6460/7211 [27:17<02:21,  5.29it/s]

Reports:  90%|████████▉ | 6461/7211 [27:17<02:22,  5.27it/s]

Reports:  90%|████████▉ | 6462/7211 [27:17<02:21,  5.27it/s]

Reports:  90%|████████▉ | 6463/7211 [27:17<02:20,  5.31it/s]

Reports:  90%|████████▉ | 6464/7211 [27:18<02:23,  5.21it/s]

Reports:  90%|████████▉ | 6465/7211 [27:18<02:26,  5.08it/s]

Reports:  90%|████████▉ | 6466/7211 [27:18<02:25,  5.12it/s]

Reports:  90%|████████▉ | 6467/7211 [27:18<02:21,  5.25it/s]

Reports:  90%|████████▉ | 6468/7211 [27:18<02:23,  5.19it/s]

Reports:  90%|████████▉ | 6469/7211 [27:19<02:22,  5.19it/s]

Reports:  90%|████████▉ | 6470/7211 [27:19<02:20,  5.28it/s]

Reports:  90%|████████▉ | 6471/7211 [27:19<02:22,  5.20it/s]

Reports:  90%|████████▉ | 6472/7211 [27:19<02:23,  5.14it/s]

Reports:  90%|████████▉ | 6473/7211 [27:19<02:22,  5.18it/s]

Reports:  90%|████████▉ | 6474/7211 [27:19<02:25,  5.06it/s]

Reports:  90%|████████▉ | 6475/7211 [27:20<02:24,  5.09it/s]

Reports:  90%|████████▉ | 6476/7211 [27:20<02:24,  5.08it/s]

Reports:  90%|████████▉ | 6477/7211 [27:20<02:23,  5.12it/s]

Reports:  90%|████████▉ | 6478/7211 [27:20<02:20,  5.22it/s]

Reports:  90%|████████▉ | 6479/7211 [27:20<02:19,  5.23it/s]

Reports:  90%|████████▉ | 6480/7211 [27:21<02:19,  5.26it/s]

Reports:  90%|████████▉ | 6481/7211 [27:21<02:17,  5.30it/s]

Reports:  90%|████████▉ | 6482/7211 [27:21<02:17,  5.31it/s]

Reports:  90%|████████▉ | 6483/7211 [27:21<02:18,  5.25it/s]

Reports:  90%|████████▉ | 6484/7211 [27:21<02:18,  5.25it/s]

Reports:  90%|████████▉ | 6485/7211 [27:22<02:17,  5.29it/s]

Reports:  90%|████████▉ | 6486/7211 [27:22<02:20,  5.17it/s]

Reports:  90%|████████▉ | 6487/7211 [27:22<02:20,  5.16it/s]

Reports:  90%|████████▉ | 6488/7211 [27:22<02:19,  5.18it/s]

Reports:  90%|████████▉ | 6489/7211 [27:22<02:18,  5.23it/s]

Reports:  90%|█████████ | 6490/7211 [27:23<02:17,  5.26it/s]

Reports:  90%|█████████ | 6491/7211 [27:23<02:18,  5.21it/s]

Reports:  90%|█████████ | 6492/7211 [27:23<02:20,  5.13it/s]

Reports:  90%|█████████ | 6493/7211 [27:23<02:20,  5.10it/s]

Reports:  90%|█████████ | 6494/7211 [27:23<02:18,  5.16it/s]

Reports:  90%|█████████ | 6495/7211 [27:24<02:19,  5.14it/s]

Reports:  90%|█████████ | 6496/7211 [27:24<02:20,  5.11it/s]

Reports:  90%|█████████ | 6497/7211 [27:24<02:19,  5.13it/s]

Reports:  90%|█████████ | 6498/7211 [27:24<02:18,  5.13it/s]

Reports:  90%|█████████ | 6499/7211 [27:24<02:15,  5.25it/s]

Reports:  90%|█████████ | 6500/7211 [27:24<02:18,  5.14it/s]

Reports:  90%|█████████ | 6501/7211 [27:25<02:20,  5.07it/s]

Reports:  90%|█████████ | 6502/7211 [27:25<02:24,  4.91it/s]

Reports:  90%|█████████ | 6503/7211 [27:25<02:22,  4.95it/s]

Reports:  90%|█████████ | 6504/7211 [27:25<02:19,  5.08it/s]

Reports:  90%|█████████ | 6505/7211 [27:25<02:17,  5.14it/s]

Reports:  90%|█████████ | 6506/7211 [27:26<02:14,  5.24it/s]

Reports:  90%|█████████ | 6507/7211 [27:26<02:17,  5.12it/s]

Reports:  90%|█████████ | 6508/7211 [27:26<02:18,  5.08it/s]

Reports:  90%|█████████ | 6509/7211 [27:26<02:17,  5.10it/s]

Reports:  90%|█████████ | 6510/7211 [27:26<02:17,  5.12it/s]

Reports:  90%|█████████ | 6511/7211 [27:27<02:16,  5.14it/s]

Reports:  90%|█████████ | 6512/7211 [27:27<02:13,  5.24it/s]

Reports:  90%|█████████ | 6513/7211 [27:27<02:11,  5.29it/s]

Reports:  90%|█████████ | 6514/7211 [27:27<02:11,  5.29it/s]

Reports:  90%|█████████ | 6515/7211 [27:27<02:15,  5.14it/s]

Reports:  90%|█████████ | 6516/7211 [27:28<02:15,  5.14it/s]

Reports:  90%|█████████ | 6517/7211 [27:28<02:12,  5.23it/s]

Reports:  90%|█████████ | 6518/7211 [27:28<02:13,  5.17it/s]

Reports:  90%|█████████ | 6519/7211 [27:28<02:14,  5.13it/s]

Reports:  90%|█████████ | 6520/7211 [27:28<02:13,  5.17it/s]

Reports:  90%|█████████ | 6521/7211 [27:29<02:11,  5.26it/s]

Reports:  90%|█████████ | 6522/7211 [27:29<02:09,  5.33it/s]

Reports:  90%|█████████ | 6523/7211 [27:29<02:12,  5.21it/s]

Reports:  90%|█████████ | 6524/7211 [27:29<02:10,  5.27it/s]

Reports:  90%|█████████ | 6525/7211 [27:29<02:10,  5.25it/s]

Reports:  91%|█████████ | 6526/7211 [27:30<02:11,  5.23it/s]

Reports:  91%|█████████ | 6527/7211 [27:30<02:12,  5.16it/s]

Reports:  91%|█████████ | 6528/7211 [27:30<02:12,  5.17it/s]

Reports:  91%|█████████ | 6529/7211 [27:30<02:15,  5.02it/s]

Reports:  91%|█████████ | 6530/7211 [27:30<02:11,  5.17it/s]

Reports:  91%|█████████ | 6531/7211 [27:30<02:10,  5.21it/s]

Reports:  91%|█████████ | 6532/7211 [27:31<02:10,  5.21it/s]

Reports:  91%|█████████ | 6533/7211 [27:31<02:10,  5.19it/s]

Reports:  91%|█████████ | 6534/7211 [27:31<02:08,  5.29it/s]

Reports:  91%|█████████ | 6535/7211 [27:31<02:09,  5.23it/s]

Reports:  91%|█████████ | 6536/7211 [27:31<02:08,  5.26it/s]

Reports:  91%|█████████ | 6537/7211 [27:32<02:06,  5.34it/s]

Reports:  91%|█████████ | 6538/7211 [27:32<02:06,  5.34it/s]

Reports:  91%|█████████ | 6539/7211 [27:32<02:06,  5.33it/s]

Reports:  91%|█████████ | 6540/7211 [27:32<02:10,  5.14it/s]

Reports:  91%|█████████ | 6541/7211 [27:32<02:09,  5.16it/s]

Reports:  91%|█████████ | 6542/7211 [27:33<02:09,  5.17it/s]

Reports:  91%|█████████ | 6543/7211 [27:33<02:07,  5.22it/s]

Reports:  91%|█████████ | 6544/7211 [27:33<02:06,  5.28it/s]

Reports:  91%|█████████ | 6545/7211 [27:33<02:10,  5.12it/s]

Reports:  91%|█████████ | 6546/7211 [27:33<02:07,  5.21it/s]

Reports:  91%|█████████ | 6547/7211 [27:34<02:07,  5.23it/s]

Reports:  91%|█████████ | 6548/7211 [27:34<02:06,  5.23it/s]

Reports:  91%|█████████ | 6549/7211 [27:34<02:05,  5.27it/s]

Reports:  91%|█████████ | 6550/7211 [27:34<02:06,  5.24it/s]

Reports:  91%|█████████ | 6551/7211 [27:34<02:08,  5.15it/s]

Reports:  91%|█████████ | 6552/7211 [27:35<02:07,  5.16it/s]

Reports:  91%|█████████ | 6553/7211 [27:35<02:09,  5.07it/s]

Reports:  91%|█████████ | 6554/7211 [27:35<02:08,  5.13it/s]

Reports:  91%|█████████ | 6555/7211 [27:35<02:09,  5.05it/s]

Reports:  91%|█████████ | 6556/7211 [27:35<02:08,  5.10it/s]

Reports:  91%|█████████ | 6557/7211 [27:36<02:09,  5.04it/s]

Reports:  91%|█████████ | 6558/7211 [27:36<02:06,  5.15it/s]

Reports:  91%|█████████ | 6559/7211 [27:36<02:05,  5.19it/s]

Reports:  91%|█████████ | 6560/7211 [27:36<02:05,  5.19it/s]

Reports:  91%|█████████ | 6561/7211 [27:36<02:04,  5.21it/s]

Reports:  91%|█████████ | 6562/7211 [27:36<02:06,  5.13it/s]

Reports:  91%|█████████ | 6563/7211 [27:37<02:04,  5.19it/s]

Reports:  91%|█████████ | 6564/7211 [27:37<02:03,  5.25it/s]

Reports:  91%|█████████ | 6565/7211 [27:37<02:04,  5.19it/s]

Reports:  91%|█████████ | 6566/7211 [27:37<02:06,  5.08it/s]

Reports:  91%|█████████ | 6567/7211 [27:37<02:09,  4.97it/s]

Reports:  91%|█████████ | 6568/7211 [27:38<02:07,  5.03it/s]

Reports:  91%|█████████ | 6569/7211 [27:38<02:05,  5.10it/s]

Reports:  91%|█████████ | 6570/7211 [27:38<02:05,  5.12it/s]

Reports:  91%|█████████ | 6571/7211 [27:38<02:05,  5.11it/s]

Reports:  91%|█████████ | 6572/7211 [27:38<02:05,  5.09it/s]

Reports:  91%|█████████ | 6573/7211 [27:39<02:04,  5.11it/s]

Reports:  91%|█████████ | 6574/7211 [27:39<02:03,  5.15it/s]

Reports:  91%|█████████ | 6575/7211 [27:39<02:01,  5.25it/s]

Reports:  91%|█████████ | 6576/7211 [27:39<02:00,  5.26it/s]

Reports:  91%|█████████ | 6577/7211 [27:39<01:59,  5.32it/s]

Reports:  91%|█████████ | 6578/7211 [27:40<02:01,  5.21it/s]

Reports:  91%|█████████ | 6579/7211 [27:40<02:01,  5.22it/s]

Reports:  91%|█████████ | 6580/7211 [27:40<01:59,  5.26it/s]

Reports:  91%|█████████▏| 6581/7211 [27:40<02:01,  5.19it/s]

Reports:  91%|█████████▏| 6582/7211 [27:40<02:00,  5.24it/s]

Reports:  91%|█████████▏| 6583/7211 [27:41<01:57,  5.33it/s]

Reports:  91%|█████████▏| 6584/7211 [27:41<01:56,  5.36it/s]

Reports:  91%|█████████▏| 6585/7211 [27:41<01:57,  5.35it/s]

Reports:  91%|█████████▏| 6586/7211 [27:41<01:57,  5.31it/s]

Reports:  91%|█████████▏| 6587/7211 [27:41<01:56,  5.38it/s]

Reports:  91%|█████████▏| 6588/7211 [27:41<01:57,  5.31it/s]

Reports:  91%|█████████▏| 6589/7211 [27:42<01:59,  5.22it/s]

Reports:  91%|█████████▏| 6590/7211 [27:42<01:58,  5.25it/s]

Reports:  91%|█████████▏| 6591/7211 [27:42<01:56,  5.31it/s]

Reports:  91%|█████████▏| 6592/7211 [27:42<02:00,  5.15it/s]

Reports:  91%|█████████▏| 6593/7211 [27:42<02:01,  5.08it/s]

Reports:  91%|█████████▏| 6594/7211 [27:43<02:02,  5.04it/s]

Reports:  91%|█████████▏| 6595/7211 [27:43<02:01,  5.05it/s]

Reports:  91%|█████████▏| 6596/7211 [27:43<01:58,  5.18it/s]

Reports:  91%|█████████▏| 6597/7211 [27:43<01:57,  5.22it/s]

Reports:  91%|█████████▏| 6598/7211 [27:43<01:57,  5.22it/s]

Reports:  92%|█████████▏| 6599/7211 [27:44<01:59,  5.10it/s]

Reports:  92%|█████████▏| 6600/7211 [27:44<01:59,  5.11it/s]

Reports:  92%|█████████▏| 6601/7211 [27:44<01:58,  5.17it/s]

Reports:  92%|█████████▏| 6602/7211 [27:44<01:58,  5.14it/s]

Reports:  92%|█████████▏| 6603/7211 [27:44<02:00,  5.04it/s]

Reports:  92%|█████████▏| 6604/7211 [27:45<02:00,  5.02it/s]

Reports:  92%|█████████▏| 6605/7211 [27:45<01:58,  5.10it/s]

Reports:  92%|█████████▏| 6606/7211 [27:45<02:44,  3.68it/s]

Reports:  92%|█████████▏| 6607/7211 [27:45<02:32,  3.96it/s]

Reports:  92%|█████████▏| 6608/7211 [27:46<02:20,  4.29it/s]

Reports:  92%|█████████▏| 6609/7211 [27:46<02:13,  4.50it/s]

Reports:  92%|█████████▏| 6610/7211 [27:46<02:06,  4.74it/s]

Reports:  92%|█████████▏| 6611/7211 [27:46<02:06,  4.74it/s]

Reports:  92%|█████████▏| 6612/7211 [27:46<02:02,  4.91it/s]

Reports:  92%|█████████▏| 6613/7211 [27:47<02:01,  4.94it/s]

Reports:  92%|█████████▏| 6614/7211 [27:47<01:59,  4.99it/s]

Reports:  92%|█████████▏| 6615/7211 [27:47<01:58,  5.05it/s]

Reports:  92%|█████████▏| 6616/7211 [27:47<01:57,  5.08it/s]

Reports:  92%|█████████▏| 6617/7211 [27:47<01:55,  5.16it/s]

Reports:  92%|█████████▏| 6618/7211 [27:48<01:54,  5.18it/s]

Reports:  92%|█████████▏| 6619/7211 [27:48<01:52,  5.24it/s]

Reports:  92%|█████████▏| 6620/7211 [27:48<02:04,  4.75it/s]

Reports:  92%|█████████▏| 6621/7211 [27:48<01:59,  4.94it/s]

Reports:  92%|█████████▏| 6622/7211 [27:48<01:56,  5.04it/s]

Reports:  92%|█████████▏| 6623/7211 [27:49<01:56,  5.03it/s]

Reports:  92%|█████████▏| 6624/7211 [27:49<01:54,  5.11it/s]

Reports:  92%|█████████▏| 6625/7211 [27:49<01:52,  5.21it/s]

Reports:  92%|█████████▏| 6626/7211 [27:49<01:50,  5.28it/s]

Reports:  92%|█████████▏| 6627/7211 [27:49<01:52,  5.20it/s]

Reports:  92%|█████████▏| 6628/7211 [27:50<01:51,  5.24it/s]

Reports:  92%|█████████▏| 6629/7211 [27:50<02:04,  4.68it/s]

Reports:  92%|█████████▏| 6630/7211 [27:50<02:00,  4.84it/s]

Reports:  92%|█████████▏| 6631/7211 [27:50<01:59,  4.86it/s]

Reports:  92%|█████████▏| 6632/7211 [27:50<01:55,  5.03it/s]

Reports:  92%|█████████▏| 6633/7211 [27:51<01:52,  5.15it/s]

Reports:  92%|█████████▏| 6634/7211 [27:51<01:53,  5.06it/s]

Reports:  92%|█████████▏| 6635/7211 [27:51<01:52,  5.13it/s]

Reports:  92%|█████████▏| 6636/7211 [27:51<01:49,  5.24it/s]

Reports:  92%|█████████▏| 6637/7211 [27:51<01:47,  5.33it/s]

Reports:  92%|█████████▏| 6638/7211 [27:51<01:48,  5.30it/s]

Reports:  92%|█████████▏| 6639/7211 [27:52<01:48,  5.27it/s]

Reports:  92%|█████████▏| 6640/7211 [27:52<01:48,  5.27it/s]

Reports:  92%|█████████▏| 6641/7211 [27:52<01:46,  5.37it/s]

Reports:  92%|█████████▏| 6642/7211 [27:52<01:47,  5.29it/s]

Reports:  92%|█████████▏| 6643/7211 [27:52<01:49,  5.18it/s]

Reports:  92%|█████████▏| 6644/7211 [27:53<01:48,  5.25it/s]

Reports:  92%|█████████▏| 6645/7211 [27:53<01:47,  5.24it/s]

Reports:  92%|█████████▏| 6646/7211 [27:53<01:48,  5.23it/s]

Reports:  92%|█████████▏| 6647/7211 [27:53<01:48,  5.20it/s]

Reports:  92%|█████████▏| 6648/7211 [27:53<01:52,  5.01it/s]

Reports:  92%|█████████▏| 6649/7211 [27:54<01:53,  4.97it/s]

Reports:  92%|█████████▏| 6650/7211 [27:54<01:51,  5.05it/s]

Reports:  92%|█████████▏| 6651/7211 [27:54<01:50,  5.08it/s]

Reports:  92%|█████████▏| 6652/7211 [27:54<01:51,  5.02it/s]

Reports:  92%|█████████▏| 6653/7211 [27:54<01:51,  5.02it/s]

Reports:  92%|█████████▏| 6654/7211 [27:55<01:51,  5.00it/s]

Reports:  92%|█████████▏| 6655/7211 [27:55<01:50,  5.04it/s]

Reports:  92%|█████████▏| 6656/7211 [27:55<01:48,  5.12it/s]

Reports:  92%|█████████▏| 6657/7211 [27:55<01:45,  5.24it/s]

Reports:  92%|█████████▏| 6658/7211 [27:55<01:48,  5.08it/s]

Reports:  92%|█████████▏| 6659/7211 [27:56<01:50,  4.99it/s]

Reports:  92%|█████████▏| 6660/7211 [27:56<01:48,  5.09it/s]

Reports:  92%|█████████▏| 6661/7211 [27:56<01:46,  5.14it/s]

Reports:  92%|█████████▏| 6662/7211 [27:56<01:46,  5.16it/s]

Reports:  92%|█████████▏| 6663/7211 [27:56<01:45,  5.20it/s]

Reports:  92%|█████████▏| 6664/7211 [27:57<01:45,  5.18it/s]

Reports:  92%|█████████▏| 6665/7211 [27:57<01:44,  5.22it/s]

Reports:  92%|█████████▏| 6666/7211 [27:57<01:43,  5.26it/s]

Reports:  92%|█████████▏| 6667/7211 [27:57<01:41,  5.33it/s]

Reports:  92%|█████████▏| 6668/7211 [27:57<01:42,  5.29it/s]

Reports:  92%|█████████▏| 6669/7211 [27:57<01:42,  5.27it/s]

Reports:  92%|█████████▏| 6670/7211 [27:58<01:40,  5.37it/s]

Reports:  93%|█████████▎| 6671/7211 [27:58<01:40,  5.40it/s]

Reports:  93%|█████████▎| 6672/7211 [27:58<01:40,  5.38it/s]

Reports:  93%|█████████▎| 6673/7211 [27:58<01:38,  5.45it/s]

Reports:  93%|█████████▎| 6674/7211 [27:58<01:44,  5.14it/s]

Reports:  93%|█████████▎| 6675/7211 [27:59<01:51,  4.79it/s]

Reports:  93%|█████████▎| 6676/7211 [27:59<01:50,  4.83it/s]

Reports:  93%|█████████▎| 6677/7211 [27:59<01:54,  4.68it/s]

Reports:  93%|█████████▎| 6678/7211 [27:59<01:51,  4.76it/s]

Reports:  93%|█████████▎| 6679/7211 [28:00<01:49,  4.86it/s]

Reports:  93%|█████████▎| 6680/7211 [28:00<01:48,  4.91it/s]

Reports:  93%|█████████▎| 6681/7211 [28:00<01:44,  5.06it/s]

Reports:  93%|█████████▎| 6682/7211 [28:00<01:44,  5.08it/s]

Reports:  93%|█████████▎| 6683/7211 [28:00<01:41,  5.19it/s]

Reports:  93%|█████████▎| 6684/7211 [28:00<01:41,  5.22it/s]

Reports:  93%|█████████▎| 6685/7211 [28:01<01:39,  5.29it/s]

Reports:  93%|█████████▎| 6686/7211 [28:01<01:38,  5.34it/s]

Reports:  93%|█████████▎| 6687/7211 [28:01<01:38,  5.34it/s]

Reports:  93%|█████████▎| 6688/7211 [28:01<01:38,  5.29it/s]

Reports:  93%|█████████▎| 6689/7211 [28:01<01:42,  5.11it/s]

Reports:  93%|█████████▎| 6690/7211 [28:02<01:40,  5.18it/s]

Reports:  93%|█████████▎| 6691/7211 [28:02<01:40,  5.19it/s]

Reports:  93%|█████████▎| 6692/7211 [28:02<01:40,  5.16it/s]

Reports:  93%|█████████▎| 6693/7211 [28:02<01:40,  5.14it/s]

Reports:  93%|█████████▎| 6694/7211 [28:02<01:41,  5.09it/s]

Reports:  93%|█████████▎| 6695/7211 [28:03<01:40,  5.13it/s]

Reports:  93%|█████████▎| 6696/7211 [28:03<01:38,  5.22it/s]

Reports:  93%|█████████▎| 6697/7211 [28:03<01:39,  5.16it/s]

Reports:  93%|█████████▎| 6698/7211 [28:03<01:41,  5.03it/s]

Reports:  93%|█████████▎| 6699/7211 [28:03<01:40,  5.10it/s]

Reports:  93%|█████████▎| 6700/7211 [28:04<01:39,  5.15it/s]

Reports:  93%|█████████▎| 6701/7211 [28:04<01:37,  5.24it/s]

Reports:  93%|█████████▎| 6702/7211 [28:04<01:36,  5.28it/s]

Reports:  93%|█████████▎| 6703/7211 [28:04<01:35,  5.30it/s]

Reports:  93%|█████████▎| 6704/7211 [28:04<01:36,  5.23it/s]

Reports:  93%|█████████▎| 6705/7211 [28:04<01:36,  5.24it/s]

Reports:  93%|█████████▎| 6706/7211 [28:05<01:39,  5.10it/s]

Reports:  93%|█████████▎| 6707/7211 [28:05<01:38,  5.10it/s]

Reports:  93%|█████████▎| 6708/7211 [28:05<01:38,  5.12it/s]

Reports:  93%|█████████▎| 6709/7211 [28:05<01:37,  5.14it/s]

Reports:  93%|█████████▎| 6710/7211 [28:05<01:39,  5.05it/s]

Reports:  93%|█████████▎| 6711/7211 [28:06<01:40,  4.96it/s]

Reports:  93%|█████████▎| 6712/7211 [28:06<01:39,  5.01it/s]

Reports:  93%|█████████▎| 6713/7211 [28:06<01:39,  4.99it/s]

Reports:  93%|█████████▎| 6714/7211 [28:06<01:37,  5.10it/s]

Reports:  93%|█████████▎| 6715/7211 [28:06<01:36,  5.12it/s]

Reports:  93%|█████████▎| 6716/7211 [28:07<01:36,  5.13it/s]

Reports:  93%|█████████▎| 6717/7211 [28:07<01:38,  5.02it/s]

Reports:  93%|█████████▎| 6718/7211 [28:07<01:37,  5.04it/s]

Reports:  93%|█████████▎| 6719/7211 [28:07<01:37,  5.07it/s]

Reports:  93%|█████████▎| 6720/7211 [28:07<01:35,  5.16it/s]

Reports:  93%|█████████▎| 6721/7211 [28:08<01:33,  5.24it/s]

Reports:  93%|█████████▎| 6722/7211 [28:08<01:32,  5.27it/s]

Reports:  93%|█████████▎| 6723/7211 [28:08<01:33,  5.21it/s]

Reports:  93%|█████████▎| 6724/7211 [28:08<01:34,  5.18it/s]

Reports:  93%|█████████▎| 6725/7211 [28:08<01:40,  4.83it/s]

Reports:  93%|█████████▎| 6726/7211 [28:09<01:36,  5.02it/s]

Reports:  93%|█████████▎| 6727/7211 [28:09<01:37,  4.95it/s]

Reports:  93%|█████████▎| 6728/7211 [28:09<01:35,  5.05it/s]

Reports:  93%|█████████▎| 6729/7211 [28:09<01:33,  5.15it/s]

Reports:  93%|█████████▎| 6730/7211 [28:09<01:34,  5.07it/s]

Reports:  93%|█████████▎| 6731/7211 [28:10<01:33,  5.15it/s]

Reports:  93%|█████████▎| 6732/7211 [28:10<01:34,  5.06it/s]

Reports:  93%|█████████▎| 6733/7211 [28:10<01:33,  5.13it/s]

Reports:  93%|█████████▎| 6734/7211 [28:10<01:32,  5.17it/s]

Reports:  93%|█████████▎| 6735/7211 [28:10<01:31,  5.20it/s]

Reports:  93%|█████████▎| 6736/7211 [28:11<01:30,  5.26it/s]

Reports:  93%|█████████▎| 6737/7211 [28:11<01:31,  5.19it/s]

Reports:  93%|█████████▎| 6738/7211 [28:11<01:32,  5.13it/s]

Reports:  93%|█████████▎| 6739/7211 [28:11<01:30,  5.20it/s]

Reports:  93%|█████████▎| 6740/7211 [28:11<01:29,  5.28it/s]

Reports:  93%|█████████▎| 6741/7211 [28:12<01:27,  5.34it/s]

Reports:  93%|█████████▎| 6742/7211 [28:12<01:28,  5.29it/s]

Reports:  94%|█████████▎| 6743/7211 [28:12<01:29,  5.23it/s]

Reports:  94%|█████████▎| 6744/7211 [28:12<01:27,  5.31it/s]

Reports:  94%|█████████▎| 6745/7211 [28:12<01:29,  5.24it/s]

Reports:  94%|█████████▎| 6746/7211 [28:13<01:30,  5.13it/s]

Reports:  94%|█████████▎| 6747/7211 [28:13<01:31,  5.06it/s]

Reports:  94%|█████████▎| 6748/7211 [28:13<01:33,  4.96it/s]

Reports:  94%|█████████▎| 6749/7211 [28:13<01:30,  5.11it/s]

Reports:  94%|█████████▎| 6750/7211 [28:13<01:28,  5.20it/s]

Reports:  94%|█████████▎| 6751/7211 [28:13<01:28,  5.21it/s]

Reports:  94%|█████████▎| 6752/7211 [28:14<01:32,  4.97it/s]

Reports:  94%|█████████▎| 6753/7211 [28:14<01:32,  4.98it/s]

Reports:  94%|█████████▎| 6754/7211 [28:14<01:31,  5.00it/s]

Reports:  94%|█████████▎| 6755/7211 [28:14<01:29,  5.11it/s]

Reports:  94%|█████████▎| 6756/7211 [28:14<01:29,  5.10it/s]

Reports:  94%|█████████▎| 6757/7211 [28:15<01:29,  5.07it/s]

Reports:  94%|█████████▎| 6758/7211 [28:15<01:30,  4.99it/s]

Reports:  94%|█████████▎| 6759/7211 [28:15<01:27,  5.14it/s]

Reports:  94%|█████████▎| 6760/7211 [28:15<01:27,  5.13it/s]

Reports:  94%|█████████▍| 6761/7211 [28:15<01:26,  5.18it/s]

Reports:  94%|█████████▍| 6762/7211 [28:16<01:28,  5.08it/s]

Reports:  94%|█████████▍| 6763/7211 [28:16<01:28,  5.06it/s]

Reports:  94%|█████████▍| 6764/7211 [28:16<01:28,  5.06it/s]

Reports:  94%|█████████▍| 6765/7211 [28:16<01:25,  5.19it/s]

Reports:  94%|█████████▍| 6766/7211 [28:16<01:30,  4.93it/s]

Reports:  94%|█████████▍| 6767/7211 [28:17<01:38,  4.51it/s]

Reports:  94%|█████████▍| 6768/7211 [28:17<01:37,  4.55it/s]

Reports:  94%|█████████▍| 6769/7211 [28:17<01:35,  4.61it/s]

Reports:  94%|█████████▍| 6770/7211 [28:17<01:43,  4.25it/s]

Reports:  94%|█████████▍| 6771/7211 [28:18<01:42,  4.31it/s]

Reports:  94%|█████████▍| 6772/7211 [28:18<02:12,  3.32it/s]

Reports:  94%|█████████▍| 6773/7211 [28:18<02:01,  3.59it/s]

Reports:  94%|█████████▍| 6774/7211 [28:19<02:03,  3.55it/s]

Reports:  94%|█████████▍| 6775/7211 [28:19<01:59,  3.64it/s]

Reports:  94%|█████████▍| 6776/7211 [28:19<02:05,  3.48it/s]

Reports:  94%|█████████▍| 6777/7211 [28:19<01:57,  3.70it/s]

Reports:  94%|█████████▍| 6778/7211 [28:20<02:12,  3.28it/s]

Reports:  94%|█████████▍| 6779/7211 [28:20<01:58,  3.63it/s]

Reports:  94%|█████████▍| 6780/7211 [28:20<01:50,  3.90it/s]

Reports:  94%|█████████▍| 6781/7211 [28:20<01:44,  4.12it/s]

Reports:  94%|█████████▍| 6782/7211 [28:21<01:49,  3.93it/s]

Reports:  94%|█████████▍| 6783/7211 [28:21<01:43,  4.12it/s]

Reports:  94%|█████████▍| 6784/7211 [28:21<01:37,  4.38it/s]

Reports:  94%|█████████▍| 6785/7211 [28:21<01:32,  4.61it/s]

Reports:  94%|█████████▍| 6786/7211 [28:22<01:28,  4.81it/s]

Reports:  94%|█████████▍| 6787/7211 [28:22<01:25,  4.95it/s]

Reports:  94%|█████████▍| 6788/7211 [28:22<01:22,  5.10it/s]

Reports:  94%|█████████▍| 6789/7211 [28:22<01:21,  5.16it/s]

Reports:  94%|█████████▍| 6790/7211 [28:22<01:21,  5.15it/s]

Reports:  94%|█████████▍| 6791/7211 [28:22<01:19,  5.29it/s]

Reports:  94%|█████████▍| 6792/7211 [28:23<01:21,  5.12it/s]

Reports:  94%|█████████▍| 6793/7211 [28:23<01:20,  5.16it/s]

Reports:  94%|█████████▍| 6794/7211 [28:23<01:21,  5.11it/s]

Reports:  94%|█████████▍| 6795/7211 [28:23<01:20,  5.15it/s]

Reports:  94%|█████████▍| 6796/7211 [28:23<01:19,  5.19it/s]

Reports:  94%|█████████▍| 6797/7211 [28:24<01:24,  4.90it/s]

Reports:  94%|█████████▍| 6798/7211 [28:24<01:22,  5.00it/s]

Reports:  94%|█████████▍| 6799/7211 [28:24<01:20,  5.12it/s]

Reports:  94%|█████████▍| 6800/7211 [28:24<01:20,  5.08it/s]

Reports:  94%|█████████▍| 6801/7211 [28:24<01:20,  5.08it/s]

Reports:  94%|█████████▍| 6802/7211 [28:25<01:22,  4.97it/s]

Reports:  94%|█████████▍| 6803/7211 [28:25<01:22,  4.94it/s]

Reports:  94%|█████████▍| 6804/7211 [28:25<01:21,  4.96it/s]

Reports:  94%|█████████▍| 6805/7211 [28:25<01:19,  5.08it/s]

Reports:  94%|█████████▍| 6806/7211 [28:25<01:19,  5.12it/s]

Reports:  94%|█████████▍| 6807/7211 [28:26<01:19,  5.11it/s]

Reports:  94%|█████████▍| 6808/7211 [28:26<01:17,  5.23it/s]

Reports:  94%|█████████▍| 6809/7211 [28:26<01:15,  5.31it/s]

Reports:  94%|█████████▍| 6810/7211 [28:26<01:16,  5.26it/s]

Reports:  94%|█████████▍| 6811/7211 [28:26<01:15,  5.32it/s]

Reports:  94%|█████████▍| 6812/7211 [28:27<01:15,  5.32it/s]

Reports:  94%|█████████▍| 6813/7211 [28:27<01:14,  5.37it/s]

Reports:  94%|█████████▍| 6814/7211 [28:27<01:13,  5.42it/s]

Reports:  95%|█████████▍| 6815/7211 [28:27<01:13,  5.42it/s]

Reports:  95%|█████████▍| 6816/7211 [28:27<01:14,  5.32it/s]

Reports:  95%|█████████▍| 6817/7211 [28:27<01:15,  5.21it/s]

Reports:  95%|█████████▍| 6818/7211 [28:28<01:15,  5.21it/s]

Reports:  95%|█████████▍| 6819/7211 [28:28<01:14,  5.30it/s]

Reports:  95%|█████████▍| 6820/7211 [28:28<01:14,  5.28it/s]

Reports:  95%|█████████▍| 6821/7211 [28:28<01:12,  5.37it/s]

Reports:  95%|█████████▍| 6822/7211 [28:28<01:12,  5.39it/s]

Reports:  95%|█████████▍| 6823/7211 [28:29<01:13,  5.29it/s]

Reports:  95%|█████████▍| 6824/7211 [28:29<01:13,  5.28it/s]

Reports:  95%|█████████▍| 6825/7211 [28:29<01:12,  5.30it/s]

Reports:  95%|█████████▍| 6826/7211 [28:29<01:12,  5.32it/s]

Reports:  95%|█████████▍| 6827/7211 [28:29<01:11,  5.35it/s]

Reports:  95%|█████████▍| 6828/7211 [28:30<01:12,  5.31it/s]

Reports:  95%|█████████▍| 6829/7211 [28:30<01:12,  5.25it/s]

Reports:  95%|█████████▍| 6830/7211 [28:30<01:12,  5.28it/s]

Reports:  95%|█████████▍| 6831/7211 [28:30<01:13,  5.20it/s]

Reports:  95%|█████████▍| 6832/7211 [28:30<01:13,  5.16it/s]

Reports:  95%|█████████▍| 6833/7211 [28:31<01:13,  5.13it/s]

Reports:  95%|█████████▍| 6834/7211 [28:31<01:13,  5.11it/s]

Reports:  95%|█████████▍| 6835/7211 [28:31<01:14,  5.04it/s]

Reports:  95%|█████████▍| 6836/7211 [28:31<01:12,  5.14it/s]

Reports:  95%|█████████▍| 6837/7211 [28:31<01:13,  5.09it/s]

Reports:  95%|█████████▍| 6838/7211 [28:32<01:12,  5.17it/s]

Reports:  95%|█████████▍| 6839/7211 [28:32<01:10,  5.28it/s]

Reports:  95%|█████████▍| 6840/7211 [28:32<01:10,  5.28it/s]

Reports:  95%|█████████▍| 6841/7211 [28:32<01:10,  5.25it/s]

Reports:  95%|█████████▍| 6842/7211 [28:32<01:10,  5.26it/s]

Reports:  95%|█████████▍| 6843/7211 [28:32<01:11,  5.17it/s]

Reports:  95%|█████████▍| 6844/7211 [28:33<01:10,  5.18it/s]

Reports:  95%|█████████▍| 6845/7211 [28:33<01:10,  5.17it/s]

Reports:  95%|█████████▍| 6846/7211 [28:33<01:11,  5.11it/s]

Reports:  95%|█████████▍| 6847/7211 [28:33<01:09,  5.26it/s]

Reports:  95%|█████████▍| 6848/7211 [28:33<01:10,  5.11it/s]

Reports:  95%|█████████▍| 6849/7211 [28:34<01:12,  4.97it/s]

Reports:  95%|█████████▍| 6850/7211 [28:34<01:12,  4.96it/s]

Reports:  95%|█████████▌| 6851/7211 [28:34<01:11,  5.07it/s]

Reports:  95%|█████████▌| 6852/7211 [28:34<01:09,  5.18it/s]

Reports:  95%|█████████▌| 6853/7211 [28:34<01:10,  5.10it/s]

Reports:  95%|█████████▌| 6854/7211 [28:35<01:08,  5.19it/s]

Reports:  95%|█████████▌| 6855/7211 [28:35<01:11,  5.01it/s]

Reports:  95%|█████████▌| 6856/7211 [28:35<01:09,  5.09it/s]

Reports:  95%|█████████▌| 6857/7211 [28:35<01:09,  5.11it/s]

Reports:  95%|█████████▌| 6858/7211 [28:35<01:08,  5.12it/s]

Reports:  95%|█████████▌| 6859/7211 [28:36<01:08,  5.16it/s]

Reports:  95%|█████████▌| 6860/7211 [28:36<01:09,  5.08it/s]

Reports:  95%|█████████▌| 6861/7211 [28:36<01:07,  5.16it/s]

Reports:  95%|█████████▌| 6862/7211 [28:36<01:07,  5.14it/s]

Reports:  95%|█████████▌| 6863/7211 [28:36<01:07,  5.17it/s]

Reports:  95%|█████████▌| 6864/7211 [28:37<01:06,  5.24it/s]

Reports:  95%|█████████▌| 6865/7211 [28:37<01:06,  5.17it/s]

Reports:  95%|█████████▌| 6866/7211 [28:37<01:07,  5.13it/s]

Reports:  95%|█████████▌| 6867/7211 [28:37<01:06,  5.21it/s]

Reports:  95%|█████████▌| 6868/7211 [28:37<01:04,  5.30it/s]

Reports:  95%|█████████▌| 6869/7211 [28:38<01:05,  5.23it/s]

Reports:  95%|█████████▌| 6870/7211 [28:38<01:05,  5.23it/s]

Reports:  95%|█████████▌| 6871/7211 [28:38<01:04,  5.27it/s]

Reports:  95%|█████████▌| 6872/7211 [28:38<01:03,  5.31it/s]

Reports:  95%|█████████▌| 6873/7211 [28:38<01:03,  5.31it/s]

Reports:  95%|█████████▌| 6874/7211 [28:38<01:02,  5.37it/s]

Reports:  95%|█████████▌| 6875/7211 [28:39<01:03,  5.33it/s]

Reports:  95%|█████████▌| 6876/7211 [28:39<01:02,  5.40it/s]

Reports:  95%|█████████▌| 6877/7211 [28:39<01:02,  5.31it/s]

Reports:  95%|█████████▌| 6878/7211 [28:39<01:02,  5.36it/s]

Reports:  95%|█████████▌| 6879/7211 [28:39<01:02,  5.28it/s]

Reports:  95%|█████████▌| 6880/7211 [28:40<01:04,  5.14it/s]

Reports:  95%|█████████▌| 6881/7211 [28:40<01:03,  5.19it/s]

Reports:  95%|█████████▌| 6882/7211 [28:40<01:03,  5.22it/s]

Reports:  95%|█████████▌| 6883/7211 [28:40<01:03,  5.17it/s]

Reports:  95%|█████████▌| 6884/7211 [28:40<01:01,  5.31it/s]

Reports:  95%|█████████▌| 6885/7211 [28:41<01:01,  5.26it/s]

Reports:  95%|█████████▌| 6886/7211 [28:41<01:01,  5.32it/s]

Reports:  96%|█████████▌| 6887/7211 [28:41<01:02,  5.22it/s]

Reports:  96%|█████████▌| 6888/7211 [28:41<01:03,  5.09it/s]

Reports:  96%|█████████▌| 6889/7211 [28:41<01:01,  5.20it/s]

Reports:  96%|█████████▌| 6890/7211 [28:42<01:02,  5.17it/s]

Reports:  96%|█████████▌| 6891/7211 [28:42<01:01,  5.17it/s]

Reports:  96%|█████████▌| 6892/7211 [28:42<01:00,  5.24it/s]

Reports:  96%|█████████▌| 6893/7211 [28:42<01:00,  5.25it/s]

Reports:  96%|█████████▌| 6894/7211 [28:42<01:01,  5.15it/s]

Reports:  96%|█████████▌| 6895/7211 [28:42<01:00,  5.26it/s]

Reports:  96%|█████████▌| 6896/7211 [28:43<01:01,  5.12it/s]

Reports:  96%|█████████▌| 6897/7211 [28:48<09:38,  1.84s/it]

Reports:  96%|█████████▌| 6898/7211 [28:49<07:02,  1.35s/it]

Reports:  96%|█████████▌| 6899/7211 [28:49<05:14,  1.01s/it]

Reports:  96%|█████████▌| 6900/7211 [28:49<03:58,  1.31it/s]

Reports:  96%|█████████▌| 6901/7211 [28:49<03:04,  1.68it/s]

Reports:  96%|█████████▌| 6902/7211 [28:50<03:20,  1.54it/s]

Reports:  96%|█████████▌| 6903/7211 [28:50<02:37,  1.95it/s]

Reports:  96%|█████████▌| 6904/7211 [28:50<02:08,  2.38it/s]

Reports:  96%|█████████▌| 6905/7211 [28:51<01:48,  2.82it/s]

Reports:  96%|█████████▌| 6906/7211 [28:51<01:34,  3.23it/s]

Reports:  96%|█████████▌| 6907/7211 [28:51<01:22,  3.68it/s]

Reports:  96%|█████████▌| 6908/7211 [28:51<01:15,  4.03it/s]

Reports:  96%|█████████▌| 6909/7211 [28:51<01:11,  4.21it/s]

Reports:  96%|█████████▌| 6910/7211 [28:52<01:09,  4.35it/s]

Reports:  96%|█████████▌| 6911/7211 [28:52<01:05,  4.57it/s]

Reports:  96%|█████████▌| 6912/7211 [28:52<01:02,  4.81it/s]

Reports:  96%|█████████▌| 6913/7211 [28:52<01:00,  4.90it/s]

Reports:  96%|█████████▌| 6914/7211 [28:52<00:59,  4.98it/s]

Reports:  96%|█████████▌| 6915/7211 [28:53<00:58,  5.03it/s]

Reports:  96%|█████████▌| 6916/7211 [28:53<00:57,  5.12it/s]

Reports:  96%|█████████▌| 6917/7211 [28:53<00:57,  5.08it/s]

Reports:  96%|█████████▌| 6918/7211 [28:53<00:56,  5.19it/s]

Reports:  96%|█████████▌| 6919/7211 [28:53<00:56,  5.19it/s]

Reports:  96%|█████████▌| 6920/7211 [28:53<00:55,  5.26it/s]

Reports:  96%|█████████▌| 6921/7211 [28:54<00:56,  5.10it/s]

Reports:  96%|█████████▌| 6922/7211 [28:54<00:55,  5.19it/s]

Reports:  96%|█████████▌| 6923/7211 [28:54<00:55,  5.20it/s]

Reports:  96%|█████████▌| 6924/7211 [28:54<00:54,  5.24it/s]

Reports:  96%|█████████▌| 6925/7211 [28:54<00:55,  5.15it/s]

Reports:  96%|█████████▌| 6926/7211 [28:55<00:56,  5.09it/s]

Reports:  96%|█████████▌| 6927/7211 [28:55<00:56,  5.06it/s]

Reports:  96%|█████████▌| 6928/7211 [28:55<00:54,  5.15it/s]

Reports:  96%|█████████▌| 6929/7211 [28:55<00:54,  5.13it/s]

Reports:  96%|█████████▌| 6930/7211 [28:55<00:55,  5.03it/s]

Reports:  96%|█████████▌| 6931/7211 [28:56<00:54,  5.15it/s]

Reports:  96%|█████████▌| 6932/7211 [28:56<00:54,  5.16it/s]

Reports:  96%|█████████▌| 6933/7211 [28:56<01:19,  3.51it/s]

Reports:  96%|█████████▌| 6934/7211 [28:56<01:11,  3.90it/s]

Reports:  96%|█████████▌| 6935/7211 [28:57<01:06,  4.15it/s]

Reports:  96%|█████████▌| 6936/7211 [28:57<01:03,  4.33it/s]

Reports:  96%|█████████▌| 6937/7211 [28:57<01:01,  4.47it/s]

Reports:  96%|█████████▌| 6938/7211 [28:57<00:57,  4.75it/s]

Reports:  96%|█████████▌| 6939/7211 [28:57<00:55,  4.90it/s]

Reports:  96%|█████████▌| 6940/7211 [28:58<00:54,  5.00it/s]

Reports:  96%|█████████▋| 6941/7211 [28:58<00:54,  4.93it/s]

Reports:  96%|█████████▋| 6942/7211 [28:58<00:54,  4.96it/s]

Reports:  96%|█████████▋| 6943/7211 [28:58<00:53,  5.01it/s]

Reports:  96%|█████████▋| 6944/7211 [28:58<00:52,  5.12it/s]

Reports:  96%|█████████▋| 6945/7211 [28:59<00:51,  5.14it/s]

Reports:  96%|█████████▋| 6946/7211 [28:59<00:52,  5.08it/s]

Reports:  96%|█████████▋| 6947/7211 [28:59<00:53,  4.93it/s]

Reports:  96%|█████████▋| 6948/7211 [28:59<00:53,  4.88it/s]

Reports:  96%|█████████▋| 6949/7211 [28:59<00:51,  5.10it/s]

Reports:  96%|█████████▋| 6950/7211 [29:00<00:51,  5.06it/s]

Reports:  96%|█████████▋| 6951/7211 [29:00<00:51,  5.00it/s]

Reports:  96%|█████████▋| 6952/7211 [29:00<00:51,  5.00it/s]

Reports:  96%|█████████▋| 6953/7211 [29:00<00:51,  5.04it/s]

Reports:  96%|█████████▋| 6954/7211 [29:00<00:51,  4.97it/s]

Reports:  96%|█████████▋| 6955/7211 [29:01<00:50,  5.05it/s]

Reports:  96%|█████████▋| 6956/7211 [29:01<00:50,  5.06it/s]

Reports:  96%|█████████▋| 6957/7211 [29:01<00:50,  5.01it/s]

Reports:  96%|█████████▋| 6958/7211 [29:01<00:50,  4.97it/s]

Reports:  97%|█████████▋| 6959/7211 [29:01<00:49,  5.05it/s]

Reports:  97%|█████████▋| 6960/7211 [29:02<00:49,  5.07it/s]

Reports:  97%|█████████▋| 6961/7211 [29:02<00:48,  5.18it/s]

Reports:  97%|█████████▋| 6962/7211 [29:02<00:48,  5.18it/s]

Reports:  97%|█████████▋| 6963/7211 [29:02<00:48,  5.09it/s]

Reports:  97%|█████████▋| 6964/7211 [29:02<00:49,  4.97it/s]

Reports:  97%|█████████▋| 6965/7211 [29:03<00:50,  4.91it/s]

Reports:  97%|█████████▋| 6966/7211 [29:03<00:49,  4.95it/s]

Reports:  97%|█████████▋| 6967/7211 [29:03<00:48,  5.03it/s]

Reports:  97%|█████████▋| 6968/7211 [29:03<00:48,  5.05it/s]

Reports:  97%|█████████▋| 6969/7211 [29:03<00:47,  5.11it/s]

Reports:  97%|█████████▋| 6970/7211 [29:04<00:46,  5.18it/s]

Reports:  97%|█████████▋| 6971/7211 [29:04<00:46,  5.17it/s]

Reports:  97%|█████████▋| 6972/7211 [29:04<00:45,  5.22it/s]

Reports:  97%|█████████▋| 6973/7211 [29:04<00:45,  5.22it/s]

Reports:  97%|█████████▋| 6974/7211 [29:04<00:46,  5.15it/s]

Reports:  97%|█████████▋| 6975/7211 [29:05<00:46,  5.09it/s]

Reports:  97%|█████████▋| 6976/7211 [29:05<00:46,  5.11it/s]

Reports:  97%|█████████▋| 6977/7211 [29:05<00:45,  5.15it/s]

Reports:  97%|█████████▋| 6978/7211 [29:05<00:45,  5.14it/s]

Reports:  97%|█████████▋| 6979/7211 [29:05<00:44,  5.19it/s]

Reports:  97%|█████████▋| 6980/7211 [29:06<00:44,  5.18it/s]

Reports:  97%|█████████▋| 6981/7211 [29:06<00:45,  5.08it/s]

Reports:  97%|█████████▋| 6982/7211 [29:06<00:45,  4.99it/s]

Reports:  97%|█████████▋| 6983/7211 [29:06<00:44,  5.11it/s]

Reports:  97%|█████████▋| 6984/7211 [29:06<00:48,  4.65it/s]

Reports:  97%|█████████▋| 6985/7211 [29:07<00:46,  4.82it/s]

Reports:  97%|█████████▋| 6986/7211 [29:07<00:46,  4.87it/s]

Reports:  97%|█████████▋| 6987/7211 [29:07<00:44,  4.99it/s]

Reports:  97%|█████████▋| 6988/7211 [29:07<00:44,  5.05it/s]

Reports:  97%|█████████▋| 6989/7211 [29:07<00:44,  5.02it/s]

Reports:  97%|█████████▋| 6990/7211 [29:08<00:43,  5.04it/s]

Reports:  97%|█████████▋| 6991/7211 [29:08<00:42,  5.14it/s]

Reports:  97%|█████████▋| 6992/7211 [29:08<00:42,  5.17it/s]

Reports:  97%|█████████▋| 6993/7211 [29:08<00:42,  5.17it/s]

Reports:  97%|█████████▋| 6994/7211 [29:08<00:41,  5.24it/s]

Reports:  97%|█████████▋| 6995/7211 [29:09<00:41,  5.26it/s]

Reports:  97%|█████████▋| 6996/7211 [29:09<00:40,  5.32it/s]

Reports:  97%|█████████▋| 6997/7211 [29:09<00:41,  5.21it/s]

Reports:  97%|█████████▋| 6998/7211 [29:09<00:41,  5.11it/s]

Reports:  97%|█████████▋| 6999/7211 [29:09<00:40,  5.22it/s]

Reports:  97%|█████████▋| 7000/7211 [29:09<00:40,  5.23it/s]

Reports:  97%|█████████▋| 7001/7211 [29:10<00:40,  5.21it/s]

Reports:  97%|█████████▋| 7002/7211 [29:10<00:39,  5.30it/s]

Reports:  97%|█████████▋| 7003/7211 [29:10<00:40,  5.20it/s]

Reports:  97%|█████████▋| 7004/7211 [29:10<00:40,  5.14it/s]

Reports:  97%|█████████▋| 7005/7211 [29:10<00:41,  5.00it/s]

Reports:  97%|█████████▋| 7006/7211 [29:11<00:40,  5.04it/s]

Reports:  97%|█████████▋| 7007/7211 [29:11<00:40,  5.02it/s]

Reports:  97%|█████████▋| 7008/7211 [29:11<00:40,  5.03it/s]

Reports:  97%|█████████▋| 7009/7211 [29:11<00:39,  5.07it/s]

Reports:  97%|█████████▋| 7010/7211 [29:11<00:39,  5.03it/s]

Reports:  97%|█████████▋| 7011/7211 [29:12<00:39,  5.07it/s]

Reports:  97%|█████████▋| 7012/7211 [29:12<00:38,  5.16it/s]

Reports:  97%|█████████▋| 7013/7211 [29:12<00:38,  5.18it/s]

Reports:  97%|█████████▋| 7014/7211 [29:12<00:37,  5.23it/s]

Reports:  97%|█████████▋| 7015/7211 [29:12<00:38,  5.12it/s]

Reports:  97%|█████████▋| 7016/7211 [29:13<00:38,  5.07it/s]

Reports:  97%|█████████▋| 7017/7211 [29:13<00:37,  5.14it/s]

Reports:  97%|█████████▋| 7018/7211 [29:13<00:36,  5.23it/s]

Reports:  97%|█████████▋| 7019/7211 [29:13<00:36,  5.25it/s]

Reports:  97%|█████████▋| 7020/7211 [29:13<00:36,  5.27it/s]

Reports:  97%|█████████▋| 7021/7211 [29:14<00:36,  5.20it/s]

Reports:  97%|█████████▋| 7022/7211 [29:14<00:35,  5.29it/s]

Reports:  97%|█████████▋| 7023/7211 [29:14<00:35,  5.32it/s]

Reports:  97%|█████████▋| 7024/7211 [29:14<00:35,  5.23it/s]

Reports:  97%|█████████▋| 7025/7211 [29:14<00:35,  5.25it/s]

Reports:  97%|█████████▋| 7026/7211 [29:15<00:34,  5.31it/s]

Reports:  97%|█████████▋| 7027/7211 [29:15<00:34,  5.29it/s]

Reports:  97%|█████████▋| 7028/7211 [29:15<00:35,  5.22it/s]

Reports:  97%|█████████▋| 7029/7211 [29:15<00:34,  5.24it/s]

Reports:  97%|█████████▋| 7030/7211 [29:15<00:34,  5.23it/s]

Reports:  98%|█████████▊| 7031/7211 [29:15<00:33,  5.31it/s]

Reports:  98%|█████████▊| 7032/7211 [29:16<00:33,  5.27it/s]

Reports:  98%|█████████▊| 7033/7211 [29:16<00:33,  5.31it/s]

Reports:  98%|█████████▊| 7034/7211 [29:16<00:33,  5.21it/s]

Reports:  98%|█████████▊| 7035/7211 [29:16<00:34,  5.16it/s]

Reports:  98%|█████████▊| 7036/7211 [29:16<00:34,  5.10it/s]

Reports:  98%|█████████▊| 7037/7211 [29:17<00:33,  5.21it/s]

Reports:  98%|█████████▊| 7038/7211 [29:17<00:32,  5.32it/s]

Reports:  98%|█████████▊| 7039/7211 [29:17<00:32,  5.31it/s]

Reports:  98%|█████████▊| 7040/7211 [29:17<00:32,  5.24it/s]

Reports:  98%|█████████▊| 7041/7211 [29:17<00:32,  5.30it/s]

Reports:  98%|█████████▊| 7042/7211 [29:18<00:31,  5.34it/s]

Reports:  98%|█████████▊| 7043/7211 [29:18<00:31,  5.29it/s]

Reports:  98%|█████████▊| 7044/7211 [29:18<00:31,  5.31it/s]

Reports:  98%|█████████▊| 7045/7211 [29:18<00:32,  5.14it/s]

Reports:  98%|█████████▊| 7046/7211 [29:18<00:32,  5.13it/s]

Reports:  98%|█████████▊| 7047/7211 [29:19<00:31,  5.19it/s]

Reports:  98%|█████████▊| 7048/7211 [29:19<00:31,  5.15it/s]

Reports:  98%|█████████▊| 7049/7211 [29:19<00:31,  5.13it/s]

Reports:  98%|█████████▊| 7050/7211 [29:19<00:30,  5.21it/s]

Reports:  98%|█████████▊| 7051/7211 [29:19<00:30,  5.26it/s]

Reports:  98%|█████████▊| 7052/7211 [29:19<00:30,  5.29it/s]

Reports:  98%|█████████▊| 7053/7211 [29:20<00:30,  5.17it/s]

Reports:  98%|█████████▊| 7054/7211 [29:20<00:30,  5.17it/s]

Reports:  98%|█████████▊| 7055/7211 [29:20<00:30,  5.13it/s]

Reports:  98%|█████████▊| 7056/7211 [29:20<00:30,  5.11it/s]

Reports:  98%|█████████▊| 7057/7211 [29:20<00:29,  5.24it/s]

Reports:  98%|█████████▊| 7058/7211 [29:21<00:28,  5.28it/s]

Reports:  98%|█████████▊| 7059/7211 [29:21<00:28,  5.33it/s]

Reports:  98%|█████████▊| 7060/7211 [29:21<00:28,  5.24it/s]

Reports:  98%|█████████▊| 7061/7211 [29:24<02:53,  1.15s/it]

Reports:  98%|█████████▊| 7062/7211 [29:25<02:11,  1.13it/s]

Reports:  98%|█████████▊| 7063/7211 [29:25<01:41,  1.46it/s]

Reports:  98%|█████████▊| 7064/7211 [29:25<01:25,  1.72it/s]

Reports:  98%|█████████▊| 7065/7211 [29:25<01:10,  2.08it/s]

Reports:  98%|█████████▊| 7066/7211 [29:26<00:58,  2.49it/s]

Reports:  98%|█████████▊| 7067/7211 [29:26<00:49,  2.94it/s]

Reports:  98%|█████████▊| 7068/7211 [29:26<00:42,  3.39it/s]

Reports:  98%|█████████▊| 7069/7211 [29:26<00:38,  3.72it/s]

Reports:  98%|█████████▊| 7070/7211 [29:26<00:34,  4.06it/s]

Reports:  98%|█████████▊| 7071/7211 [29:27<00:32,  4.30it/s]

Reports:  98%|█████████▊| 7072/7211 [29:27<00:30,  4.55it/s]

Reports:  98%|█████████▊| 7073/7211 [29:27<00:29,  4.72it/s]

Reports:  98%|█████████▊| 7074/7211 [29:27<00:28,  4.80it/s]

Reports:  98%|█████████▊| 7075/7211 [29:27<00:27,  4.93it/s]

Reports:  98%|█████████▊| 7076/7211 [29:28<00:46,  2.91it/s]

Reports:  98%|█████████▊| 7077/7211 [29:28<00:39,  3.38it/s]

Reports:  98%|█████████▊| 7078/7211 [29:29<00:34,  3.80it/s]

Reports:  98%|█████████▊| 7079/7211 [29:29<00:31,  4.21it/s]

Reports:  98%|█████████▊| 7080/7211 [29:29<00:28,  4.53it/s]

Reports:  98%|█████████▊| 7081/7211 [29:29<00:28,  4.56it/s]

Reports:  98%|█████████▊| 7082/7211 [29:29<00:27,  4.75it/s]

Reports:  98%|█████████▊| 7083/7211 [29:29<00:25,  5.03it/s]

Reports:  98%|█████████▊| 7084/7211 [29:30<00:25,  5.04it/s]

Reports:  98%|█████████▊| 7085/7211 [29:30<00:24,  5.07it/s]

Reports:  98%|█████████▊| 7086/7211 [29:30<00:25,  4.93it/s]

Reports:  98%|█████████▊| 7087/7211 [29:30<00:24,  5.02it/s]

Reports:  98%|█████████▊| 7088/7211 [29:30<00:24,  5.09it/s]

Reports:  98%|█████████▊| 7089/7211 [29:31<00:23,  5.12it/s]

Reports:  98%|█████████▊| 7090/7211 [29:31<00:23,  5.14it/s]

Reports:  98%|█████████▊| 7091/7211 [29:31<00:23,  5.19it/s]

Reports:  98%|█████████▊| 7092/7211 [29:31<00:22,  5.22it/s]

Reports:  98%|█████████▊| 7093/7211 [29:31<00:22,  5.31it/s]

Reports:  98%|█████████▊| 7094/7211 [29:32<00:22,  5.24it/s]

Reports:  98%|█████████▊| 7095/7211 [29:32<00:22,  5.21it/s]

Reports:  98%|█████████▊| 7096/7211 [29:32<00:21,  5.24it/s]

Reports:  98%|█████████▊| 7097/7211 [29:32<00:21,  5.20it/s]

Reports:  98%|█████████▊| 7098/7211 [29:32<00:21,  5.23it/s]

Reports:  98%|█████████▊| 7099/7211 [29:33<00:21,  5.25it/s]

Reports:  98%|█████████▊| 7100/7211 [29:33<00:21,  5.14it/s]

Reports:  98%|█████████▊| 7101/7211 [29:33<00:21,  5.04it/s]

Reports:  98%|█████████▊| 7102/7211 [29:33<00:21,  5.02it/s]

Reports:  99%|█████████▊| 7103/7211 [29:33<00:21,  5.06it/s]

Reports:  99%|█████████▊| 7104/7211 [29:34<00:20,  5.18it/s]

Reports:  99%|█████████▊| 7105/7211 [29:34<00:20,  5.17it/s]

Reports:  99%|█████████▊| 7106/7211 [29:34<00:20,  5.20it/s]

Reports:  99%|█████████▊| 7107/7211 [29:34<00:20,  5.16it/s]

Reports:  99%|█████████▊| 7108/7211 [29:34<00:19,  5.19it/s]

Reports:  99%|█████████▊| 7109/7211 [29:35<00:36,  2.82it/s]

Reports:  99%|█████████▊| 7110/7211 [29:35<00:31,  3.24it/s]

Reports:  99%|█████████▊| 7111/7211 [29:35<00:27,  3.61it/s]

Reports:  99%|█████████▊| 7112/7211 [29:36<00:25,  3.95it/s]

Reports:  99%|█████████▊| 7113/7211 [29:36<00:23,  4.25it/s]

Reports:  99%|█████████▊| 7114/7211 [29:36<00:21,  4.51it/s]

Reports:  99%|█████████▊| 7115/7211 [29:36<00:20,  4.66it/s]

Reports:  99%|█████████▊| 7116/7211 [29:36<00:19,  4.84it/s]

Reports:  99%|█████████▊| 7117/7211 [29:37<00:19,  4.94it/s]

Reports:  99%|█████████▊| 7118/7211 [29:37<00:18,  5.05it/s]

Reports:  99%|█████████▊| 7119/7211 [29:37<00:17,  5.18it/s]

Reports:  99%|█████████▊| 7120/7211 [29:37<00:17,  5.13it/s]

Reports:  99%|█████████▉| 7121/7211 [29:37<00:17,  5.21it/s]

Reports:  99%|█████████▉| 7122/7211 [29:38<00:17,  5.17it/s]

Reports:  99%|█████████▉| 7123/7211 [29:38<00:28,  3.11it/s]

Reports:  99%|█████████▉| 7124/7211 [29:38<00:24,  3.55it/s]

Reports:  99%|█████████▉| 7125/7211 [29:39<00:21,  3.93it/s]

Reports:  99%|█████████▉| 7126/7211 [29:39<00:19,  4.29it/s]

Reports:  99%|█████████▉| 7127/7211 [29:39<00:18,  4.48it/s]

Reports:  99%|█████████▉| 7128/7211 [29:39<00:17,  4.73it/s]

Reports:  99%|█████████▉| 7129/7211 [29:39<00:17,  4.82it/s]

Reports:  99%|█████████▉| 7130/7211 [29:40<00:16,  4.86it/s]

Reports:  99%|█████████▉| 7131/7211 [29:40<00:16,  4.99it/s]

Reports:  99%|█████████▉| 7132/7211 [29:40<00:15,  5.08it/s]

Reports:  99%|█████████▉| 7133/7211 [29:40<00:15,  5.17it/s]

Reports:  99%|█████████▉| 7134/7211 [29:40<00:14,  5.19it/s]

Reports:  99%|█████████▉| 7135/7211 [29:40<00:14,  5.15it/s]

Reports:  99%|█████████▉| 7136/7211 [29:41<00:14,  5.25it/s]

Reports:  99%|█████████▉| 7137/7211 [29:41<00:14,  5.23it/s]

Reports:  99%|█████████▉| 7138/7211 [29:41<00:14,  5.16it/s]

Reports:  99%|█████████▉| 7139/7211 [29:41<00:14,  5.11it/s]

Reports:  99%|█████████▉| 7140/7211 [29:41<00:14,  5.01it/s]

Reports:  99%|█████████▉| 7141/7211 [29:42<00:13,  5.07it/s]

Reports:  99%|█████████▉| 7142/7211 [29:42<00:13,  5.16it/s]

Reports:  99%|█████████▉| 7143/7211 [29:42<00:13,  5.09it/s]

Reports:  99%|█████████▉| 7144/7211 [29:42<00:13,  5.02it/s]

Reports:  99%|█████████▉| 7145/7211 [29:42<00:13,  5.02it/s]

Reports:  99%|█████████▉| 7146/7211 [29:43<00:15,  4.14it/s]

Reports:  99%|█████████▉| 7147/7211 [29:43<00:15,  4.03it/s]

Reports:  99%|█████████▉| 7148/7211 [29:43<00:14,  4.32it/s]

Reports:  99%|█████████▉| 7149/7211 [29:43<00:13,  4.46it/s]

Reports:  99%|█████████▉| 7150/7211 [29:44<00:13,  4.67it/s]

Reports:  99%|█████████▉| 7151/7211 [29:44<00:12,  4.77it/s]

Reports:  99%|█████████▉| 7152/7211 [29:44<00:12,  4.88it/s]

Reports:  99%|█████████▉| 7153/7211 [29:44<00:11,  5.01it/s]

Reports:  99%|█████████▉| 7154/7211 [29:44<00:11,  5.13it/s]

Reports:  99%|█████████▉| 7155/7211 [29:45<00:10,  5.13it/s]

Reports:  99%|█████████▉| 7156/7211 [29:45<00:10,  5.19it/s]

Reports:  99%|█████████▉| 7157/7211 [29:45<00:10,  5.23it/s]

Reports:  99%|█████████▉| 7158/7211 [29:45<00:10,  5.18it/s]

Reports:  99%|█████████▉| 7159/7211 [29:45<00:10,  5.13it/s]

Reports:  99%|█████████▉| 7160/7211 [29:46<00:09,  5.20it/s]

Reports:  99%|█████████▉| 7161/7211 [29:46<00:09,  5.21it/s]

Reports:  99%|█████████▉| 7162/7211 [29:46<00:09,  5.19it/s]

Reports:  99%|█████████▉| 7163/7211 [29:46<00:09,  5.24it/s]

Reports:  99%|█████████▉| 7164/7211 [29:46<00:09,  5.22it/s]

Reports:  99%|█████████▉| 7165/7211 [29:47<00:12,  3.62it/s]

Reports:  99%|█████████▉| 7166/7211 [29:47<00:11,  3.92it/s]

Reports:  99%|█████████▉| 7167/7211 [29:47<00:10,  4.26it/s]

Reports:  99%|█████████▉| 7168/7211 [29:47<00:09,  4.48it/s]

Reports:  99%|█████████▉| 7169/7211 [29:48<00:09,  4.65it/s]

Reports:  99%|█████████▉| 7170/7211 [29:48<00:08,  4.72it/s]

Reports:  99%|█████████▉| 7171/7211 [29:48<00:08,  4.74it/s]

Reports:  99%|█████████▉| 7172/7211 [29:48<00:08,  4.83it/s]

Reports:  99%|█████████▉| 7173/7211 [29:48<00:07,  4.99it/s]

Reports:  99%|█████████▉| 7174/7211 [29:49<00:07,  5.10it/s]

Reports: 100%|█████████▉| 7175/7211 [29:49<00:07,  5.10it/s]

Reports: 100%|█████████▉| 7176/7211 [29:49<00:06,  5.11it/s]

Reports: 100%|█████████▉| 7177/7211 [29:49<00:06,  5.21it/s]

Reports: 100%|█████████▉| 7178/7211 [29:49<00:06,  5.16it/s]

Reports: 100%|█████████▉| 7179/7211 [29:50<00:06,  5.18it/s]

Reports: 100%|█████████▉| 7180/7211 [29:50<00:06,  5.09it/s]

Reports: 100%|█████████▉| 7181/7211 [29:50<00:05,  5.05it/s]

Reports: 100%|█████████▉| 7182/7211 [29:50<00:05,  5.15it/s]

Reports: 100%|█████████▉| 7183/7211 [29:50<00:05,  5.15it/s]

Reports: 100%|█████████▉| 7184/7211 [29:50<00:05,  5.20it/s]

Reports: 100%|█████████▉| 7185/7211 [29:51<00:04,  5.24it/s]

Reports: 100%|█████████▉| 7186/7211 [29:51<00:04,  5.13it/s]

Reports: 100%|█████████▉| 7187/7211 [29:51<00:04,  5.12it/s]

Reports: 100%|█████████▉| 7188/7211 [29:51<00:04,  4.99it/s]

Reports: 100%|█████████▉| 7189/7211 [29:51<00:04,  5.03it/s]

Reports: 100%|█████████▉| 7190/7211 [29:52<00:04,  5.09it/s]

Reports: 100%|█████████▉| 7191/7211 [29:52<00:03,  5.04it/s]

Reports: 100%|█████████▉| 7192/7211 [29:52<00:03,  4.99it/s]

Reports: 100%|█████████▉| 7193/7211 [29:52<00:03,  5.11it/s]

Reports: 100%|█████████▉| 7194/7211 [29:52<00:03,  5.17it/s]

Reports: 100%|█████████▉| 7195/7211 [29:53<00:03,  5.11it/s]

Reports: 100%|█████████▉| 7196/7211 [29:53<00:02,  5.16it/s]

Reports: 100%|█████████▉| 7197/7211 [29:53<00:02,  5.15it/s]

Reports: 100%|█████████▉| 7198/7211 [29:53<00:02,  5.00it/s]

Reports: 100%|█████████▉| 7199/7211 [29:53<00:02,  5.04it/s]

Reports: 100%|█████████▉| 7200/7211 [29:54<00:02,  5.18it/s]

Reports: 100%|█████████▉| 7201/7211 [29:54<00:01,  5.23it/s]

Reports: 100%|█████████▉| 7202/7211 [29:54<00:01,  5.23it/s]

Reports: 100%|█████████▉| 7203/7211 [29:54<00:01,  5.29it/s]

Reports: 100%|█████████▉| 7204/7211 [29:54<00:01,  5.13it/s]

Reports: 100%|█████████▉| 7205/7211 [29:55<00:01,  5.10it/s]

Reports: 100%|█████████▉| 7206/7211 [29:55<00:00,  5.08it/s]

Reports: 100%|█████████▉| 7207/7211 [29:55<00:00,  5.11it/s]

Reports: 100%|█████████▉| 7208/7211 [29:55<00:00,  5.12it/s]

Reports: 100%|█████████▉| 7209/7211 [29:55<00:00,  5.01it/s]

Reports: 100%|█████████▉| 7210/7211 [29:56<00:00,  4.99it/s]

Reports: 100%|██████████| 7211/7211 [29:56<00:00,  5.10it/s]

Reports: 100%|██████████| 7211/7211 [29:56<00:00,  4.01it/s]

Report rows: 5109

Gaps (ex-reports):   0%|          | 0/7211 [00:00<?, ?it/s]

Gaps (ex-reports):   0%|          | 1/7211 [00:00<26:02,  4.62it/s]

Gaps (ex-reports):   0%|          | 2/7211 [00:00<25:20,  4.74it/s]

Gaps (ex-reports):   0%|          | 3/7211 [00:00<25:12,  4.76it/s]

Gaps (ex-reports):   0%|          | 4/7211 [00:00<24:52,  4.83it/s]

Gaps (ex-reports):   0%|          | 5/7211 [00:01<25:25,  4.72it/s]

Gaps (ex-reports):   0%|          | 6/7211 [00:01<24:58,  4.81it/s]

Gaps (ex-reports):   0%|          | 7/7211 [00:01<25:05,  4.79it/s]

Gaps (ex-reports):   0%|          | 8/7211 [00:01<25:00,  4.80it/s]

Gaps (ex-reports):   0%|          | 9/7211 [00:01<24:49,  4.84it/s]

Gaps (ex-reports):   0%|          | 10/7211 [00:02<24:28,  4.90it/s]

Gaps (ex-reports):   0%|          | 11/7211 [00:02<24:12,  4.96it/s]

Gaps (ex-reports):   0%|          | 12/7211 [00:02<24:13,  4.95it/s]

Gaps (ex-reports):   0%|          | 13/7211 [00:02<24:12,  4.96it/s]

Gaps (ex-reports):   0%|          | 14/7211 [00:02<24:00,  5.00it/s]

Gaps (ex-reports):   0%|          | 15/7211 [00:03<24:13,  4.95it/s]

Gaps (ex-reports):   0%|          | 16/7211 [00:03<24:19,  4.93it/s]

Gaps (ex-reports):   0%|          | 17/7211 [00:03<24:30,  4.89it/s]

Gaps (ex-reports):   0%|          | 18/7211 [00:03<23:59,  5.00it/s]

Gaps (ex-reports):   0%|          | 19/7211 [00:03<23:46,  5.04it/s]

Gaps (ex-reports):   0%|          | 20/7211 [00:04<23:37,  5.07it/s]

Gaps (ex-reports):   0%|          | 21/7211 [00:04<23:53,  5.02it/s]

Gaps (ex-reports):   0%|          | 22/7211 [00:04<23:41,  5.06it/s]

Gaps (ex-reports):   0%|          | 23/7211 [00:04<24:18,  4.93it/s]

Gaps (ex-reports):   0%|          | 24/7211 [00:04<24:01,  4.98it/s]

Gaps (ex-reports):   0%|          | 25/7211 [00:05<24:28,  4.89it/s]

Gaps (ex-reports):   0%|          | 26/7211 [00:05<23:59,  4.99it/s]

Gaps (ex-reports):   0%|          | 27/7211 [00:05<23:28,  5.10it/s]

Gaps (ex-reports):   0%|          | 28/7211 [00:05<23:31,  5.09it/s]

Gaps (ex-reports):   0%|          | 29/7211 [00:05<24:13,  4.94it/s]

Gaps (ex-reports):   0%|          | 30/7211 [00:06<24:24,  4.90it/s]

Gaps (ex-reports):   0%|          | 31/7211 [00:06<24:28,  4.89it/s]

Gaps (ex-reports):   0%|          | 32/7211 [00:06<24:23,  4.91it/s]

Gaps (ex-reports):   0%|          | 33/7211 [00:06<23:53,  5.01it/s]

Gaps (ex-reports):   0%|          | 34/7211 [00:06<24:28,  4.89it/s]

Gaps (ex-reports):   0%|          | 35/7211 [00:07<24:38,  4.85it/s]

Gaps (ex-reports):   0%|          | 36/7211 [00:07<24:35,  4.86it/s]

Gaps (ex-reports):   1%|          | 37/7211 [00:07<24:39,  4.85it/s]

Gaps (ex-reports):   1%|          | 38/7211 [00:07<24:38,  4.85it/s]

Gaps (ex-reports):   1%|          | 39/7211 [00:07<24:02,  4.97it/s]

Gaps (ex-reports):   1%|          | 40/7211 [00:08<23:56,  4.99it/s]

Gaps (ex-reports):   1%|          | 41/7211 [00:08<24:16,  4.92it/s]

Gaps (ex-reports):   1%|          | 42/7211 [00:08<24:37,  4.85it/s]

Gaps (ex-reports):   1%|          | 43/7211 [00:08<24:20,  4.91it/s]

Gaps (ex-reports):   1%|          | 44/7211 [00:08<24:01,  4.97it/s]

Gaps (ex-reports):   1%|          | 45/7211 [00:09<24:25,  4.89it/s]

Gaps (ex-reports):   1%|          | 46/7211 [00:09<24:55,  4.79it/s]

Gaps (ex-reports):   1%|          | 47/7211 [00:09<24:23,  4.90it/s]

Gaps (ex-reports):   1%|          | 48/7211 [00:09<23:52,  5.00it/s]

Gaps (ex-reports):   1%|          | 49/7211 [00:09<23:38,  5.05it/s]

Gaps (ex-reports):   1%|          | 50/7211 [00:10<24:08,  4.94it/s]

Gaps (ex-reports):   1%|          | 51/7211 [00:10<24:16,  4.92it/s]

Gaps (ex-reports):   1%|          | 52/7211 [00:10<24:34,  4.85it/s]

Gaps (ex-reports):   1%|          | 53/7211 [00:10<24:26,  4.88it/s]

Gaps (ex-reports):   1%|          | 54/7211 [00:10<24:04,  4.96it/s]

Gaps (ex-reports):   1%|          | 55/7211 [00:11<23:45,  5.02it/s]

Gaps (ex-reports):   1%|          | 56/7211 [00:11<24:48,  4.81it/s]

Gaps (ex-reports):   1%|          | 57/7211 [00:11<24:48,  4.80it/s]

Gaps (ex-reports):   1%|          | 58/7211 [00:11<24:30,  4.86it/s]

Gaps (ex-reports):   1%|          | 59/7211 [00:12<24:59,  4.77it/s]

Gaps (ex-reports):   1%|          | 60/7211 [00:12<24:36,  4.84it/s]

Gaps (ex-reports):   1%|          | 61/7211 [00:12<25:25,  4.69it/s]

Gaps (ex-reports):   1%|          | 62/7211 [00:12<25:04,  4.75it/s]

Gaps (ex-reports):   1%|          | 63/7211 [00:12<25:08,  4.74it/s]

Gaps (ex-reports):   1%|          | 64/7211 [00:13<24:52,  4.79it/s]

Gaps (ex-reports):   1%|          | 65/7211 [00:13<26:59,  4.41it/s]

Gaps (ex-reports):   1%|          | 66/7211 [00:13<26:31,  4.49it/s]

Gaps (ex-reports):   1%|          | 67/7211 [00:13<25:38,  4.64it/s]

Gaps (ex-reports):   1%|          | 68/7211 [00:13<24:52,  4.79it/s]

Gaps (ex-reports):   1%|          | 69/7211 [00:14<24:55,  4.77it/s]

Gaps (ex-reports):   1%|          | 70/7211 [00:14<24:48,  4.80it/s]

Gaps (ex-reports):   1%|          | 71/7211 [00:14<24:36,  4.84it/s]

Gaps (ex-reports):   1%|          | 72/7211 [00:14<24:08,  4.93it/s]

Gaps (ex-reports):   1%|          | 73/7211 [00:14<24:23,  4.88it/s]

Gaps (ex-reports):   1%|          | 74/7211 [00:15<23:49,  4.99it/s]

Gaps (ex-reports):   1%|          | 75/7211 [00:15<23:45,  5.01it/s]

Gaps (ex-reports):   1%|          | 76/7211 [00:15<24:13,  4.91it/s]

Gaps (ex-reports):   1%|          | 77/7211 [00:15<23:58,  4.96it/s]

Gaps (ex-reports):   1%|          | 78/7211 [00:15<24:12,  4.91it/s]

Gaps (ex-reports):   1%|          | 79/7211 [00:16<23:47,  5.00it/s]

Gaps (ex-reports):   1%|          | 80/7211 [00:16<23:41,  5.02it/s]

Gaps (ex-reports):   1%|          | 81/7211 [00:16<24:14,  4.90it/s]

Gaps (ex-reports):   1%|          | 82/7211 [00:16<23:50,  4.98it/s]

Gaps (ex-reports):   1%|          | 83/7211 [00:16<24:02,  4.94it/s]

Gaps (ex-reports):   1%|          | 84/7211 [00:17<23:48,  4.99it/s]

Gaps (ex-reports):   1%|          | 85/7211 [00:17<24:23,  4.87it/s]

Gaps (ex-reports):   1%|          | 86/7211 [00:17<24:16,  4.89it/s]

Gaps (ex-reports):   1%|          | 87/7211 [00:18<44:17,  2.68it/s]

Gaps (ex-reports):   1%|          | 88/7211 [00:18<38:15,  3.10it/s]

Gaps (ex-reports):   1%|          | 89/7211 [00:18<33:45,  3.52it/s]

Gaps (ex-reports):   1%|          | 90/7211 [00:18<30:27,  3.90it/s]

Gaps (ex-reports):   1%|▏         | 91/7211 [00:19<28:54,  4.10it/s]

Gaps (ex-reports):   1%|▏         | 92/7211 [00:19<27:30,  4.31it/s]

Gaps (ex-reports):   1%|▏         | 93/7211 [00:19<26:40,  4.45it/s]

Gaps (ex-reports):   1%|▏         | 94/7211 [00:19<26:16,  4.51it/s]

Gaps (ex-reports):   1%|▏         | 95/7211 [00:19<25:32,  4.64it/s]

Gaps (ex-reports):   1%|▏         | 96/7211 [00:20<25:37,  4.63it/s]

Gaps (ex-reports):   1%|▏         | 97/7211 [00:20<25:40,  4.62it/s]

Gaps (ex-reports):   1%|▏         | 98/7211 [00:20<25:43,  4.61it/s]

Gaps (ex-reports):   1%|▏         | 99/7211 [00:20<24:57,  4.75it/s]

Gaps (ex-reports):   1%|▏         | 100/7211 [00:21<25:09,  4.71it/s]

Gaps (ex-reports):   1%|▏         | 101/7211 [00:21<24:55,  4.75it/s]

Gaps (ex-reports):   1%|▏         | 102/7211 [00:21<24:37,  4.81it/s]

Gaps (ex-reports):   1%|▏         | 103/7211 [00:21<24:32,  4.83it/s]

Gaps (ex-reports):   1%|▏         | 104/7211 [00:21<24:27,  4.84it/s]

Gaps (ex-reports):   1%|▏         | 105/7211 [00:22<24:04,  4.92it/s]

Gaps (ex-reports):   1%|▏         | 106/7211 [00:22<24:42,  4.79it/s]

Gaps (ex-reports):   1%|▏         | 107/7211 [00:22<24:34,  4.82it/s]

Gaps (ex-reports):   1%|▏         | 108/7211 [00:22<24:01,  4.93it/s]

Gaps (ex-reports):   2%|▏         | 109/7211 [00:22<24:09,  4.90it/s]

Gaps (ex-reports):   2%|▏         | 110/7211 [00:23<24:48,  4.77it/s]

Gaps (ex-reports):   2%|▏         | 111/7211 [00:23<24:32,  4.82it/s]

Gaps (ex-reports):   2%|▏         | 112/7211 [00:23<24:30,  4.83it/s]

Gaps (ex-reports):   2%|▏         | 113/7211 [00:23<23:47,  4.97it/s]

Gaps (ex-reports):   2%|▏         | 114/7211 [00:23<23:34,  5.02it/s]

Gaps (ex-reports):   2%|▏         | 115/7211 [00:24<23:23,  5.06it/s]

Gaps (ex-reports):   2%|▏         | 116/7211 [00:24<23:00,  5.14it/s]

Gaps (ex-reports):   2%|▏         | 117/7211 [00:24<22:55,  5.16it/s]

Gaps (ex-reports):   2%|▏         | 118/7211 [00:24<23:00,  5.14it/s]

Gaps (ex-reports):   2%|▏         | 119/7211 [00:24<23:32,  5.02it/s]

Gaps (ex-reports):   2%|▏         | 120/7211 [00:25<23:33,  5.02it/s]

Gaps (ex-reports):   2%|▏         | 121/7211 [00:25<23:26,  5.04it/s]

Gaps (ex-reports):   2%|▏         | 122/7211 [00:25<23:34,  5.01it/s]

Gaps (ex-reports):   2%|▏         | 123/7211 [00:25<23:52,  4.95it/s]

Gaps (ex-reports):   2%|▏         | 124/7211 [00:25<23:51,  4.95it/s]

Gaps (ex-reports):   2%|▏         | 125/7211 [00:26<23:23,  5.05it/s]

Gaps (ex-reports):   2%|▏         | 126/7211 [00:26<24:04,  4.91it/s]

Gaps (ex-reports):   2%|▏         | 127/7211 [00:26<24:29,  4.82it/s]

Gaps (ex-reports):   2%|▏         | 128/7211 [00:26<32:20,  3.65it/s]

Gaps (ex-reports):   2%|▏         | 129/7211 [00:27<30:00,  3.93it/s]

Gaps (ex-reports):   2%|▏         | 130/7211 [00:27<28:26,  4.15it/s]

Gaps (ex-reports):   2%|▏         | 131/7211 [00:27<26:47,  4.40it/s]

Gaps (ex-reports):   2%|▏         | 132/7211 [00:27<27:24,  4.31it/s]

Gaps (ex-reports):   2%|▏         | 133/7211 [00:38<6:45:35,  3.44s/it]

Gaps (ex-reports):   2%|▏         | 134/7211 [00:41<6:18:59,  3.21s/it]

Gaps (ex-reports):   2%|▏         | 135/7211 [00:41<4:33:45,  2.32s/it]

Gaps (ex-reports):   2%|▏         | 136/7211 [00:41<3:19:03,  1.69s/it]

Gaps (ex-reports):   2%|▏         | 137/7211 [00:42<2:26:27,  1.24s/it]

Gaps (ex-reports):   2%|▏         | 138/7211 [00:42<1:49:34,  1.08it/s]

Gaps (ex-reports):   2%|▏         | 139/7211 [00:42<1:24:03,  1.40it/s]

Gaps (ex-reports):   2%|▏         | 140/7211 [00:42<1:05:53,  1.79it/s]

Gaps (ex-reports):   2%|▏         | 141/7211 [00:42<53:11,  2.22it/s]

Gaps (ex-reports):   2%|▏         | 142/7211 [00:43<45:21,  2.60it/s]

Gaps (ex-reports):   2%|▏         | 143/7211 [00:43<38:37,  3.05it/s]

Gaps (ex-reports):   2%|▏         | 144/7211 [00:43<33:44,  3.49it/s]

Gaps (ex-reports):   2%|▏         | 145/7211 [00:43<31:15,  3.77it/s]

Gaps (ex-reports):   2%|▏         | 146/7211 [00:43<29:14,  4.03it/s]

Gaps (ex-reports):   2%|▏         | 147/7211 [00:44<27:50,  4.23it/s]

Gaps (ex-reports):   2%|▏         | 148/7211 [00:44<27:06,  4.34it/s]

Gaps (ex-reports):   2%|▏         | 149/7211 [00:44<26:19,  4.47it/s]

Gaps (ex-reports):   2%|▏         | 150/7211 [00:44<25:01,  4.70it/s]

Gaps (ex-reports):   2%|▏         | 151/7211 [00:44<24:29,  4.80it/s]

Gaps (ex-reports):   2%|▏         | 152/7211 [00:45<24:50,  4.74it/s]

Gaps (ex-reports):   2%|▏         | 153/7211 [00:45<24:34,  4.79it/s]

Gaps (ex-reports):   2%|▏         | 154/7211 [00:46<54:09,  2.17it/s]

Gaps (ex-reports):   2%|▏         | 155/7211 [00:46<44:49,  2.62it/s]

Gaps (ex-reports):   2%|▏         | 156/7211 [00:46<38:13,  3.08it/s]

Gaps (ex-reports):   2%|▏         | 157/7211 [00:47<34:19,  3.42it/s]

Gaps (ex-reports):   2%|▏         | 158/7211 [00:47<31:03,  3.78it/s]

Gaps (ex-reports):   2%|▏         | 159/7211 [00:47<29:32,  3.98it/s]

Gaps (ex-reports):   2%|▏         | 160/7211 [00:47<27:26,  4.28it/s]

Gaps (ex-reports):   2%|▏         | 161/7211 [00:47<26:28,  4.44it/s]

Gaps (ex-reports):   2%|▏         | 162/7211 [00:48<25:45,  4.56it/s]

Gaps (ex-reports):   2%|▏         | 163/7211 [00:48<24:59,  4.70it/s]

Gaps (ex-reports):   2%|▏         | 164/7211 [00:48<24:30,  4.79it/s]

Gaps (ex-reports):   2%|▏         | 165/7211 [00:48<24:19,  4.83it/s]

Gaps (ex-reports):   2%|▏         | 166/7211 [00:48<24:46,  4.74it/s]

Gaps (ex-reports):   2%|▏         | 167/7211 [00:49<24:46,  4.74it/s]

Gaps (ex-reports):   2%|▏         | 168/7211 [00:49<24:30,  4.79it/s]

Gaps (ex-reports):   2%|▏         | 169/7211 [00:49<24:09,  4.86it/s]

Gaps (ex-reports):   2%|▏         | 170/7211 [00:49<23:55,  4.90it/s]

Gaps (ex-reports):   2%|▏         | 171/7211 [00:49<24:01,  4.88it/s]

Gaps (ex-reports):   2%|▏         | 172/7211 [00:50<23:51,  4.92it/s]

Gaps (ex-reports):   2%|▏         | 173/7211 [00:50<24:16,  4.83it/s]

Gaps (ex-reports):   2%|▏         | 174/7211 [00:50<24:12,  4.84it/s]

Gaps (ex-reports):   2%|▏         | 175/7211 [00:50<24:29,  4.79it/s]

Gaps (ex-reports):   2%|▏         | 176/7211 [00:50<24:06,  4.86it/s]

Gaps (ex-reports):   2%|▏         | 177/7211 [00:51<23:37,  4.96it/s]

Gaps (ex-reports):   2%|▏         | 178/7211 [00:51<23:28,  4.99it/s]

Gaps (ex-reports):   2%|▏         | 179/7211 [00:51<24:30,  4.78it/s]

Gaps (ex-reports):   2%|▏         | 180/7211 [00:51<24:13,  4.84it/s]

Gaps (ex-reports):   3%|▎         | 181/7211 [00:51<24:07,  4.86it/s]

Gaps (ex-reports):   3%|▎         | 182/7211 [00:52<23:38,  4.95it/s]

Gaps (ex-reports):   3%|▎         | 183/7211 [00:52<23:39,  4.95it/s]

Gaps (ex-reports):   3%|▎         | 184/7211 [00:52<23:51,  4.91it/s]

Gaps (ex-reports):   3%|▎         | 185/7211 [00:52<24:04,  4.86it/s]

Gaps (ex-reports):   3%|▎         | 186/7211 [00:52<24:02,  4.87it/s]

Gaps (ex-reports):   3%|▎         | 187/7211 [00:53<23:52,  4.90it/s]

Gaps (ex-reports):   3%|▎         | 188/7211 [00:53<23:41,  4.94it/s]

Gaps (ex-reports):   3%|▎         | 189/7211 [00:53<24:01,  4.87it/s]

Gaps (ex-reports):   3%|▎         | 190/7211 [00:53<23:50,  4.91it/s]

Gaps (ex-reports):   3%|▎         | 191/7211 [00:53<24:13,  4.83it/s]

Gaps (ex-reports):   3%|▎         | 192/7211 [00:54<23:52,  4.90it/s]

Gaps (ex-reports):   3%|▎         | 193/7211 [00:54<24:04,  4.86it/s]

Gaps (ex-reports):   3%|▎         | 194/7211 [00:54<24:11,  4.84it/s]

Gaps (ex-reports):   3%|▎         | 195/7211 [00:55<32:53,  3.55it/s]

Gaps (ex-reports):   3%|▎         | 196/7211 [00:55<30:08,  3.88it/s]

Gaps (ex-reports):   3%|▎         | 197/7211 [00:55<28:20,  4.12it/s]

Gaps (ex-reports):   3%|▎         | 198/7211 [00:55<27:10,  4.30it/s]

Gaps (ex-reports):   3%|▎         | 199/7211 [00:55<26:09,  4.47it/s]

Gaps (ex-reports):   3%|▎         | 200/7211 [00:57<1:07:15,  1.74it/s]

Gaps (ex-reports):   3%|▎         | 201/7211 [00:57<54:15,  2.15it/s]

Gaps (ex-reports):   3%|▎         | 202/7211 [00:57<44:57,  2.60it/s]

Gaps (ex-reports):   3%|▎         | 203/7211 [00:57<38:28,  3.04it/s]

Gaps (ex-reports):   3%|▎         | 204/7211 [00:58<33:40,  3.47it/s]

Gaps (ex-reports):   3%|▎         | 205/7211 [00:58<30:23,  3.84it/s]

Gaps (ex-reports):   3%|▎         | 206/7211 [00:58<28:13,  4.14it/s]

Gaps (ex-reports):   3%|▎         | 207/7211 [00:58<26:43,  4.37it/s]

Gaps (ex-reports):   3%|▎         | 208/7211 [00:58<26:15,  4.44it/s]

Gaps (ex-reports):   3%|▎         | 209/7211 [00:59<25:19,  4.61it/s]

Gaps (ex-reports):   3%|▎         | 210/7211 [00:59<24:42,  4.72it/s]

Gaps (ex-reports):   3%|▎         | 211/7211 [00:59<24:21,  4.79it/s]

Gaps (ex-reports):   3%|▎         | 212/7211 [00:59<23:46,  4.91it/s]

Gaps (ex-reports):   3%|▎         | 213/7211 [00:59<24:10,  4.82it/s]

Gaps (ex-reports):   3%|▎         | 214/7211 [01:00<23:54,  4.88it/s]

Gaps (ex-reports):   3%|▎         | 215/7211 [01:00<23:45,  4.91it/s]

Gaps (ex-reports):   3%|▎         | 216/7211 [01:00<24:09,  4.83it/s]

Gaps (ex-reports):   3%|▎         | 217/7211 [01:00<24:20,  4.79it/s]

Gaps (ex-reports):   3%|▎         | 218/7211 [01:00<23:38,  4.93it/s]

Gaps (ex-reports):   3%|▎         | 219/7211 [01:01<23:22,  4.99it/s]

Gaps (ex-reports):   3%|▎         | 220/7211 [01:01<32:25,  3.59it/s]

Gaps (ex-reports):   3%|▎         | 221/7211 [01:01<29:21,  3.97it/s]

Gaps (ex-reports):   3%|▎         | 222/7211 [01:01<27:47,  4.19it/s]

Gaps (ex-reports):   3%|▎         | 223/7211 [01:02<26:19,  4.42it/s]

Gaps (ex-reports):   3%|▎         | 224/7211 [01:02<25:51,  4.50it/s]

Gaps (ex-reports):   3%|▎         | 225/7211 [01:02<24:56,  4.67it/s]

Gaps (ex-reports):   3%|▎         | 226/7211 [01:02<24:18,  4.79it/s]

Gaps (ex-reports):   3%|▎         | 227/7211 [01:02<24:06,  4.83it/s]

Gaps (ex-reports):   3%|▎         | 228/7211 [01:03<23:46,  4.90it/s]

Gaps (ex-reports):   3%|▎         | 229/7211 [01:03<23:25,  4.97it/s]

Gaps (ex-reports):   3%|▎         | 230/7211 [01:03<23:52,  4.87it/s]

Gaps (ex-reports):   3%|▎         | 231/7211 [01:03<24:13,  4.80it/s]

Gaps (ex-reports):   3%|▎         | 232/7211 [01:03<23:42,  4.91it/s]

Gaps (ex-reports):   3%|▎         | 233/7211 [01:04<23:29,  4.95it/s]

Gaps (ex-reports):   3%|▎         | 234/7211 [01:04<23:45,  4.89it/s]

Gaps (ex-reports):   3%|▎         | 235/7211 [01:04<23:46,  4.89it/s]

Gaps (ex-reports):   3%|▎         | 236/7211 [01:04<23:48,  4.88it/s]

Gaps (ex-reports):   3%|▎         | 237/7211 [01:04<23:13,  5.00it/s]

Gaps (ex-reports):   3%|▎         | 238/7211 [01:05<23:06,  5.03it/s]

Gaps (ex-reports):   3%|▎         | 239/7211 [01:05<23:11,  5.01it/s]

Gaps (ex-reports):   3%|▎         | 240/7211 [01:05<23:47,  4.88it/s]

Gaps (ex-reports):   3%|▎         | 241/7211 [01:05<23:44,  4.89it/s]

Gaps (ex-reports):   3%|▎         | 242/7211 [01:05<23:33,  4.93it/s]

Gaps (ex-reports):   3%|▎         | 243/7211 [01:06<23:52,  4.87it/s]

Gaps (ex-reports):   3%|▎         | 244/7211 [01:06<23:35,  4.92it/s]

Gaps (ex-reports):   3%|▎         | 245/7211 [01:06<23:47,  4.88it/s]

Gaps (ex-reports):   3%|▎         | 246/7211 [01:06<24:16,  4.78it/s]

Gaps (ex-reports):   3%|▎         | 247/7211 [01:07<23:31,  4.94it/s]

Gaps (ex-reports):   3%|▎         | 248/7211 [01:07<23:33,  4.92it/s]

Gaps (ex-reports):   3%|▎         | 249/7211 [01:07<23:04,  5.03it/s]

Gaps (ex-reports):   3%|▎         | 250/7211 [01:07<23:36,  4.91it/s]

Gaps (ex-reports):   3%|▎         | 251/7211 [01:07<23:20,  4.97it/s]

Gaps (ex-reports):   3%|▎         | 252/7211 [01:08<23:21,  4.97it/s]

Gaps (ex-reports):   4%|▎         | 253/7211 [01:08<23:47,  4.87it/s]

Gaps (ex-reports):   4%|▎         | 254/7211 [01:08<23:48,  4.87it/s]

Gaps (ex-reports):   4%|▎         | 255/7211 [01:08<23:36,  4.91it/s]

Gaps (ex-reports):   4%|▎         | 256/7211 [01:08<23:31,  4.93it/s]

Gaps (ex-reports):   4%|▎         | 257/7211 [01:09<31:13,  3.71it/s]

Gaps (ex-reports):   4%|▎         | 258/7211 [01:09<28:57,  4.00it/s]

Gaps (ex-reports):   4%|▎         | 259/7211 [01:09<27:33,  4.20it/s]

Gaps (ex-reports):   4%|▎         | 260/7211 [01:09<26:28,  4.38it/s]

Gaps (ex-reports):   4%|▎         | 261/7211 [01:10<25:51,  4.48it/s]

Gaps (ex-reports):   4%|▎         | 262/7211 [01:10<25:52,  4.48it/s]

Gaps (ex-reports):   4%|▎         | 263/7211 [01:10<25:27,  4.55it/s]

Gaps (ex-reports):   4%|▎         | 264/7211 [01:10<24:48,  4.67it/s]

Gaps (ex-reports):   4%|▎         | 265/7211 [01:10<24:22,  4.75it/s]

Gaps (ex-reports):   4%|▎         | 266/7211 [01:11<24:01,  4.82it/s]

Gaps (ex-reports):   4%|▎         | 267/7211 [01:11<24:11,  4.79it/s]

Gaps (ex-reports):   4%|▎         | 268/7211 [01:11<23:55,  4.84it/s]

Gaps (ex-reports):   4%|▎         | 269/7211 [01:11<24:02,  4.81it/s]

Gaps (ex-reports):   4%|▎         | 270/7211 [01:11<23:19,  4.96it/s]

Gaps (ex-reports):   4%|▍         | 271/7211 [01:12<22:55,  5.04it/s]

Gaps (ex-reports):   4%|▍         | 272/7211 [01:12<23:01,  5.02it/s]

Gaps (ex-reports):   4%|▍         | 273/7211 [01:12<23:09,  4.99it/s]

Gaps (ex-reports):   4%|▍         | 274/7211 [01:12<24:03,  4.81it/s]

Gaps (ex-reports):   4%|▍         | 275/7211 [01:12<23:24,  4.94it/s]

Gaps (ex-reports):   4%|▍         | 276/7211 [01:13<23:13,  4.98it/s]

Gaps (ex-reports):   4%|▍         | 277/7211 [01:13<23:15,  4.97it/s]

Gaps (ex-reports):   4%|▍         | 278/7211 [01:13<23:11,  4.98it/s]

Gaps (ex-reports):   4%|▍         | 279/7211 [01:13<23:14,  4.97it/s]

Gaps (ex-reports):   4%|▍         | 280/7211 [01:13<23:23,  4.94it/s]

Gaps (ex-reports):   4%|▍         | 281/7211 [01:14<23:02,  5.01it/s]

Gaps (ex-reports):   4%|▍         | 282/7211 [01:14<23:04,  5.00it/s]

Gaps (ex-reports):   4%|▍         | 283/7211 [01:14<23:03,  5.01it/s]

Gaps (ex-reports):   4%|▍         | 284/7211 [01:14<23:35,  4.89it/s]

Gaps (ex-reports):   4%|▍         | 285/7211 [01:14<23:34,  4.90it/s]

Gaps (ex-reports):   4%|▍         | 286/7211 [01:15<23:11,  4.98it/s]

Gaps (ex-reports):   4%|▍         | 287/7211 [01:15<23:29,  4.91it/s]

Gaps (ex-reports):   4%|▍         | 288/7211 [01:15<24:20,  4.74it/s]

Gaps (ex-reports):   4%|▍         | 289/7211 [01:15<23:54,  4.82it/s]

Gaps (ex-reports):   4%|▍         | 290/7211 [01:16<23:53,  4.83it/s]

Gaps (ex-reports):   4%|▍         | 291/7211 [01:16<23:43,  4.86it/s]

Gaps (ex-reports):   4%|▍         | 292/7211 [01:16<23:54,  4.82it/s]

Gaps (ex-reports):   4%|▍         | 293/7211 [01:16<23:25,  4.92it/s]

Gaps (ex-reports):   4%|▍         | 294/7211 [01:16<24:42,  4.67it/s]

Gaps (ex-reports):   4%|▍         | 295/7211 [01:17<24:06,  4.78it/s]

Gaps (ex-reports):   4%|▍         | 296/7211 [01:17<24:02,  4.79it/s]

Gaps (ex-reports):   4%|▍         | 297/7211 [01:17<23:23,  4.93it/s]

Gaps (ex-reports):   4%|▍         | 298/7211 [01:17<23:42,  4.86it/s]

Gaps (ex-reports):   4%|▍         | 299/7211 [01:17<23:52,  4.82it/s]

Gaps (ex-reports):   4%|▍         | 300/7211 [01:18<23:41,  4.86it/s]

Gaps (ex-reports):   4%|▍         | 301/7211 [01:18<24:22,  4.72it/s]

Gaps (ex-reports):   4%|▍         | 302/7211 [01:18<24:07,  4.77it/s]

Gaps (ex-reports):   4%|▍         | 303/7211 [01:18<24:10,  4.76it/s]

Gaps (ex-reports):   4%|▍         | 304/7211 [01:18<23:28,  4.90it/s]

Gaps (ex-reports):   4%|▍         | 305/7211 [01:19<23:24,  4.92it/s]

Gaps (ex-reports):   4%|▍         | 306/7211 [01:19<23:45,  4.84it/s]

Gaps (ex-reports):   4%|▍         | 307/7211 [01:19<23:39,  4.86it/s]

Gaps (ex-reports):   4%|▍         | 308/7211 [01:19<23:34,  4.88it/s]

Gaps (ex-reports):   4%|▍         | 309/7211 [01:19<23:42,  4.85it/s]

Gaps (ex-reports):   4%|▍         | 310/7211 [01:20<24:01,  4.79it/s]

Gaps (ex-reports):   4%|▍         | 311/7211 [01:20<23:32,  4.88it/s]

Gaps (ex-reports):   4%|▍         | 312/7211 [01:20<23:01,  4.99it/s]

Gaps (ex-reports):   4%|▍         | 313/7211 [01:20<22:58,  5.01it/s]

Gaps (ex-reports):   4%|▍         | 314/7211 [01:20<23:32,  4.88it/s]

Gaps (ex-reports):   4%|▍         | 315/7211 [01:21<23:17,  4.93it/s]

Gaps (ex-reports):   4%|▍         | 316/7211 [01:21<23:26,  4.90it/s]

Gaps (ex-reports):   4%|▍         | 317/7211 [01:21<23:28,  4.90it/s]

Gaps (ex-reports):   4%|▍         | 318/7211 [01:21<23:15,  4.94it/s]

Gaps (ex-reports):   4%|▍         | 319/7211 [01:21<23:16,  4.94it/s]

Gaps (ex-reports):   4%|▍         | 320/7211 [01:22<23:29,  4.89it/s]

Gaps (ex-reports):   4%|▍         | 321/7211 [01:22<25:21,  4.53it/s]

Gaps (ex-reports):   4%|▍         | 322/7211 [01:22<24:27,  4.69it/s]

Gaps (ex-reports):   4%|▍         | 323/7211 [01:22<24:27,  4.69it/s]

Gaps (ex-reports):   4%|▍         | 324/7211 [01:23<24:08,  4.76it/s]

Gaps (ex-reports):   5%|▍         | 325/7211 [01:23<31:42,  3.62it/s]

Gaps (ex-reports):   5%|▍         | 326/7211 [01:23<29:26,  3.90it/s]

Gaps (ex-reports):   5%|▍         | 327/7211 [01:23<27:38,  4.15it/s]

Gaps (ex-reports):   5%|▍         | 328/7211 [01:24<26:39,  4.30it/s]

Gaps (ex-reports):   5%|▍         | 329/7211 [01:24<25:25,  4.51it/s]

Gaps (ex-reports):   5%|▍         | 330/7211 [01:24<24:36,  4.66it/s]

Gaps (ex-reports):   5%|▍         | 331/7211 [01:24<24:24,  4.70it/s]

Gaps (ex-reports):   5%|▍         | 332/7211 [01:24<24:20,  4.71it/s]

Gaps (ex-reports):   5%|▍         | 333/7211 [01:25<24:07,  4.75it/s]

Gaps (ex-reports):   5%|▍         | 334/7211 [01:25<24:09,  4.74it/s]

Gaps (ex-reports):   5%|▍         | 335/7211 [01:25<23:53,  4.80it/s]

Gaps (ex-reports):   5%|▍         | 336/7211 [01:25<24:06,  4.75it/s]

Gaps (ex-reports):   5%|▍         | 337/7211 [01:25<23:56,  4.78it/s]

Gaps (ex-reports):   5%|▍         | 338/7211 [01:26<23:44,  4.83it/s]

Gaps (ex-reports):   5%|▍         | 339/7211 [01:26<23:34,  4.86it/s]

Gaps (ex-reports):   5%|▍         | 340/7211 [01:26<23:07,  4.95it/s]

Gaps (ex-reports):   5%|▍         | 341/7211 [01:26<23:01,  4.97it/s]

Gaps (ex-reports):   5%|▍         | 342/7211 [01:26<23:29,  4.87it/s]

Gaps (ex-reports):   5%|▍         | 343/7211 [01:27<39:48,  2.88it/s]

Gaps (ex-reports):   5%|▍         | 344/7211 [01:27<34:51,  3.28it/s]

Gaps (ex-reports):   5%|▍         | 345/7211 [01:28<31:12,  3.67it/s]

Gaps (ex-reports):   5%|▍         | 346/7211 [01:28<28:49,  3.97it/s]

Gaps (ex-reports):   5%|▍         | 347/7211 [01:28<27:16,  4.19it/s]

Gaps (ex-reports):   5%|▍         | 348/7211 [01:28<25:55,  4.41it/s]

Gaps (ex-reports):   5%|▍         | 349/7211 [01:28<25:02,  4.57it/s]

Gaps (ex-reports):   5%|▍         | 350/7211 [01:29<24:39,  4.64it/s]

Gaps (ex-reports):   5%|▍         | 351/7211 [01:29<24:03,  4.75it/s]

Gaps (ex-reports):   5%|▍         | 352/7211 [01:29<23:41,  4.82it/s]

Gaps (ex-reports):   5%|▍         | 353/7211 [01:29<23:43,  4.82it/s]

Gaps (ex-reports):   5%|▍         | 354/7211 [01:29<24:31,  4.66it/s]

Gaps (ex-reports):   5%|▍         | 355/7211 [01:30<24:14,  4.71it/s]

Gaps (ex-reports):   5%|▍         | 356/7211 [01:30<24:15,  4.71it/s]

Gaps (ex-reports):   5%|▍         | 357/7211 [01:30<24:27,  4.67it/s]

Gaps (ex-reports):   5%|▍         | 358/7211 [01:30<23:36,  4.84it/s]

Gaps (ex-reports):   5%|▍         | 359/7211 [01:30<23:28,  4.87it/s]

Gaps (ex-reports):   5%|▍         | 360/7211 [01:31<23:31,  4.85it/s]

Gaps (ex-reports):   5%|▌         | 361/7211 [01:31<23:28,  4.86it/s]

Gaps (ex-reports):   5%|▌         | 362/7211 [02:31<34:44:21, 18.26s/it]

Gaps (ex-reports):   5%|▌         | 363/7211 [02:31<24:25:47, 12.84s/it]

Gaps (ex-reports):   5%|▌         | 364/7211 [02:32<17:12:25,  9.05s/it]

Gaps (ex-reports):   5%|▌         | 365/7211 [02:32<12:10:13,  6.40s/it]

Gaps (ex-reports):   5%|▌         | 366/7211 [02:32<8:38:07,  4.54s/it]

Gaps (ex-reports):   5%|▌         | 367/7211 [02:32<6:09:08,  3.24s/it]

Gaps (ex-reports):   5%|▌         | 368/7211 [02:32<4:25:23,  2.33s/it]

Gaps (ex-reports):   5%|▌         | 369/7211 [02:33<3:39:34,  1.93s/it]

Gaps (ex-reports):   5%|▌         | 370/7211 [02:34<2:40:47,  1.41s/it]

Gaps (ex-reports):   5%|▌         | 371/7211 [02:34<1:59:46,  1.05s/it]

Gaps (ex-reports):   5%|▌         | 372/7211 [02:34<1:30:07,  1.26it/s]

Gaps (ex-reports):   5%|▌         | 373/7211 [02:34<1:10:28,  1.62it/s]

Gaps (ex-reports):   5%|▌         | 374/7211 [02:34<56:50,  2.00it/s]

Gaps (ex-reports):   5%|▌         | 375/7211 [02:35<46:46,  2.44it/s]

Gaps (ex-reports):   5%|▌         | 376/7211 [02:35<39:26,  2.89it/s]

Gaps (ex-reports):   5%|▌         | 377/7211 [02:35<35:08,  3.24it/s]

Gaps (ex-reports):   5%|▌         | 378/7211 [02:35<31:16,  3.64it/s]

Gaps (ex-reports):   5%|▌         | 379/7211 [02:36<29:11,  3.90it/s]

Gaps (ex-reports):   5%|▌         | 380/7211 [02:36<27:23,  4.16it/s]

Gaps (ex-reports):   5%|▌         | 381/7211 [02:36<26:14,  4.34it/s]

Gaps (ex-reports):   5%|▌         | 382/7211 [02:36<25:22,  4.49it/s]

Gaps (ex-reports):   5%|▌         | 383/7211 [02:36<24:54,  4.57it/s]

Gaps (ex-reports):   5%|▌         | 384/7211 [02:37<24:36,  4.62it/s]

Gaps (ex-reports):   5%|▌         | 385/7211 [02:37<24:14,  4.69it/s]

Gaps (ex-reports):   5%|▌         | 386/7211 [02:37<23:36,  4.82it/s]

Gaps (ex-reports):   5%|▌         | 387/7211 [02:37<23:40,  4.80it/s]

Gaps (ex-reports):   5%|▌         | 388/7211 [02:37<23:40,  4.80it/s]

Gaps (ex-reports):   5%|▌         | 389/7211 [02:38<23:32,  4.83it/s]

Gaps (ex-reports):   5%|▌         | 390/7211 [02:38<23:04,  4.93it/s]

Gaps (ex-reports):   5%|▌         | 391/7211 [02:38<23:14,  4.89it/s]

Gaps (ex-reports):   5%|▌         | 392/7211 [02:38<23:16,  4.88it/s]

Gaps (ex-reports):   5%|▌         | 393/7211 [02:38<23:19,  4.87it/s]

Gaps (ex-reports):   5%|▌         | 394/7211 [02:39<22:55,  4.96it/s]

Gaps (ex-reports):   5%|▌         | 395/7211 [02:39<23:03,  4.93it/s]

Gaps (ex-reports):   5%|▌         | 396/7211 [02:39<22:48,  4.98it/s]

Gaps (ex-reports):   6%|▌         | 397/7211 [02:39<23:16,  4.88it/s]

Gaps (ex-reports):   6%|▌         | 398/7211 [02:39<23:32,  4.82it/s]

Gaps (ex-reports):   6%|▌         | 399/7211 [02:40<23:05,  4.92it/s]

Gaps (ex-reports):   6%|▌         | 400/7211 [02:40<23:11,  4.90it/s]

Gaps (ex-reports):   6%|▌         | 401/7211 [02:40<23:18,  4.87it/s]

Gaps (ex-reports):   6%|▌         | 402/7211 [02:40<23:23,  4.85it/s]

Gaps (ex-reports):   6%|▌         | 403/7211 [02:40<23:25,  4.84it/s]

Gaps (ex-reports):   6%|▌         | 404/7211 [02:41<22:55,  4.95it/s]

Gaps (ex-reports):   6%|▌         | 405/7211 [02:41<22:58,  4.94it/s]

Gaps (ex-reports):   6%|▌         | 406/7211 [02:41<22:54,  4.95it/s]

Gaps (ex-reports):   6%|▌         | 407/7211 [02:41<23:04,  4.91it/s]

Gaps (ex-reports):   6%|▌         | 408/7211 [02:41<22:54,  4.95it/s]

Gaps (ex-reports):   6%|▌         | 409/7211 [02:42<22:32,  5.03it/s]

Gaps (ex-reports):   6%|▌         | 410/7211 [02:42<23:00,  4.93it/s]

Gaps (ex-reports):   6%|▌         | 411/7211 [02:42<23:10,  4.89it/s]

Gaps (ex-reports):   6%|▌         | 412/7211 [02:42<23:22,  4.85it/s]

Gaps (ex-reports):   6%|▌         | 413/7211 [02:42<23:10,  4.89it/s]

Gaps (ex-reports):   6%|▌         | 414/7211 [02:43<22:41,  4.99it/s]

Gaps (ex-reports):   6%|▌         | 415/7211 [02:43<23:21,  4.85it/s]

Gaps (ex-reports):   6%|▌         | 416/7211 [02:43<23:24,  4.84it/s]

Gaps (ex-reports):   6%|▌         | 417/7211 [02:43<23:04,  4.91it/s]

Gaps (ex-reports):   6%|▌         | 418/7211 [02:43<22:50,  4.96it/s]

Gaps (ex-reports):   6%|▌         | 419/7211 [02:44<23:13,  4.87it/s]

Gaps (ex-reports):   6%|▌         | 420/7211 [02:44<23:22,  4.84it/s]

Gaps (ex-reports):   6%|▌         | 421/7211 [02:44<23:07,  4.90it/s]

Gaps (ex-reports):   6%|▌         | 422/7211 [02:44<22:41,  4.99it/s]

Gaps (ex-reports):   6%|▌         | 423/7211 [02:44<22:36,  5.01it/s]

Gaps (ex-reports):   6%|▌         | 424/7211 [02:45<30:41,  3.69it/s]

Gaps (ex-reports):   6%|▌         | 425/7211 [02:45<28:13,  4.01it/s]

Gaps (ex-reports):   6%|▌         | 426/7211 [02:45<26:49,  4.21it/s]

Gaps (ex-reports):   6%|▌         | 427/7211 [02:46<26:23,  4.28it/s]

Gaps (ex-reports):   6%|▌         | 428/7211 [02:46<25:22,  4.45it/s]

Gaps (ex-reports):   6%|▌         | 429/7211 [02:46<24:17,  4.65it/s]

Gaps (ex-reports):   6%|▌         | 430/7211 [02:46<23:25,  4.82it/s]

Gaps (ex-reports):   6%|▌         | 431/7211 [02:46<23:10,  4.88it/s]

Gaps (ex-reports):   6%|▌         | 432/7211 [02:47<23:24,  4.83it/s]

Gaps (ex-reports):   6%|▌         | 433/7211 [02:47<23:17,  4.85it/s]

Gaps (ex-reports):   6%|▌         | 434/7211 [02:47<23:19,  4.84it/s]

Gaps (ex-reports):   6%|▌         | 435/7211 [02:47<23:10,  4.87it/s]

Gaps (ex-reports):   6%|▌         | 436/7211 [02:47<22:52,  4.94it/s]

Gaps (ex-reports):   6%|▌         | 437/7211 [02:48<23:01,  4.90it/s]

Gaps (ex-reports):   6%|▌         | 438/7211 [02:48<22:54,  4.93it/s]

Gaps (ex-reports):   6%|▌         | 439/7211 [02:48<23:28,  4.81it/s]

Gaps (ex-reports):   6%|▌         | 440/7211 [02:48<23:18,  4.84it/s]

Gaps (ex-reports):   6%|▌         | 441/7211 [02:48<22:58,  4.91it/s]

Gaps (ex-reports):   6%|▌         | 442/7211 [02:49<23:32,  4.79it/s]

Gaps (ex-reports):   6%|▌         | 443/7211 [02:49<23:03,  4.89it/s]

Gaps (ex-reports):   6%|▌         | 444/7211 [02:49<23:02,  4.89it/s]

Gaps (ex-reports):   6%|▌         | 445/7211 [02:49<22:59,  4.91it/s]

Gaps (ex-reports):   6%|▌         | 446/7211 [02:49<22:48,  4.94it/s]

Gaps (ex-reports):   6%|▌         | 447/7211 [02:50<22:24,  5.03it/s]

Gaps (ex-reports):   6%|▌         | 448/7211 [02:50<22:24,  5.03it/s]

Gaps (ex-reports):   6%|▌         | 449/7211 [02:50<22:28,  5.01it/s]

Gaps (ex-reports):   6%|▌         | 450/7211 [02:50<22:35,  4.99it/s]

Gaps (ex-reports):   6%|▋         | 451/7211 [02:50<22:32,  5.00it/s]

Gaps (ex-reports):   6%|▋         | 452/7211 [02:51<22:30,  5.00it/s]

Gaps (ex-reports):   6%|▋         | 453/7211 [02:51<22:30,  5.01it/s]

Gaps (ex-reports):   6%|▋         | 454/7211 [02:51<22:29,  5.01it/s]

Gaps (ex-reports):   6%|▋         | 455/7211 [02:51<23:02,  4.89it/s]

Gaps (ex-reports):   6%|▋         | 456/7211 [02:51<22:31,  5.00it/s]

Gaps (ex-reports):   6%|▋         | 457/7211 [02:52<22:46,  4.94it/s]

Gaps (ex-reports):   6%|▋         | 458/7211 [02:52<22:48,  4.93it/s]

Gaps (ex-reports):   6%|▋         | 459/7211 [02:52<23:07,  4.87it/s]

Gaps (ex-reports):   6%|▋         | 460/7211 [02:52<22:52,  4.92it/s]

Gaps (ex-reports):   6%|▋         | 461/7211 [02:52<23:27,  4.79it/s]

Gaps (ex-reports):   6%|▋         | 462/7211 [02:53<23:04,  4.87it/s]

Gaps (ex-reports):   6%|▋         | 463/7211 [02:53<23:23,  4.81it/s]

Gaps (ex-reports):   6%|▋         | 464/7211 [02:53<23:25,  4.80it/s]

Gaps (ex-reports):   6%|▋         | 465/7211 [02:53<23:00,  4.89it/s]

Gaps (ex-reports):   6%|▋         | 466/7211 [02:53<22:45,  4.94it/s]

Gaps (ex-reports):   6%|▋         | 467/7211 [02:54<22:37,  4.97it/s]

Gaps (ex-reports):   6%|▋         | 468/7211 [02:54<22:21,  5.03it/s]

Gaps (ex-reports):   7%|▋         | 469/7211 [02:54<22:23,  5.02it/s]

Gaps (ex-reports):   7%|▋         | 470/7211 [02:54<22:53,  4.91it/s]

Gaps (ex-reports):   7%|▋         | 471/7211 [02:54<22:58,  4.89it/s]

Gaps (ex-reports):   7%|▋         | 472/7211 [02:55<22:39,  4.96it/s]

Gaps (ex-reports):   7%|▋         | 473/7211 [02:55<22:51,  4.91it/s]

Gaps (ex-reports):   7%|▋         | 474/7211 [02:55<22:49,  4.92it/s]

Gaps (ex-reports):   7%|▋         | 475/7211 [02:55<23:02,  4.87it/s]

Gaps (ex-reports):   7%|▋         | 476/7211 [02:56<23:25,  4.79it/s]

Gaps (ex-reports):   7%|▋         | 477/7211 [02:56<23:06,  4.86it/s]

Gaps (ex-reports):   7%|▋         | 478/7211 [02:56<23:00,  4.88it/s]

Gaps (ex-reports):   7%|▋         | 479/7211 [02:56<23:13,  4.83it/s]

Gaps (ex-reports):   7%|▋         | 480/7211 [02:56<23:09,  4.84it/s]

Gaps (ex-reports):   7%|▋         | 481/7211 [02:57<23:46,  4.72it/s]

Gaps (ex-reports):   7%|▋         | 482/7211 [02:57<23:11,  4.84it/s]

Gaps (ex-reports):   7%|▋         | 483/7211 [02:57<22:58,  4.88it/s]

Gaps (ex-reports):   7%|▋         | 484/7211 [02:57<22:47,  4.92it/s]

Gaps (ex-reports):   7%|▋         | 485/7211 [02:57<22:55,  4.89it/s]

Gaps (ex-reports):   7%|▋         | 486/7211 [02:58<22:34,  4.96it/s]

Gaps (ex-reports):   7%|▋         | 487/7211 [02:58<22:45,  4.92it/s]

Gaps (ex-reports):   7%|▋         | 488/7211 [02:58<22:41,  4.94it/s]

Gaps (ex-reports):   7%|▋         | 489/7211 [02:58<22:46,  4.92it/s]

Gaps (ex-reports):   7%|▋         | 490/7211 [02:58<22:43,  4.93it/s]

Gaps (ex-reports):   7%|▋         | 491/7211 [02:59<22:44,  4.93it/s]

Gaps (ex-reports):   7%|▋         | 492/7211 [02:59<22:36,  4.95it/s]

Gaps (ex-reports):   7%|▋         | 493/7211 [02:59<22:29,  4.98it/s]

Gaps (ex-reports):   7%|▋         | 494/7211 [02:59<22:10,  5.05it/s]

Gaps (ex-reports):   7%|▋         | 495/7211 [02:59<22:41,  4.93it/s]

Gaps (ex-reports):   7%|▋         | 496/7211 [03:00<22:44,  4.92it/s]

Gaps (ex-reports):   7%|▋         | 497/7211 [03:00<22:38,  4.94it/s]

Gaps (ex-reports):   7%|▋         | 498/7211 [03:00<26:08,  4.28it/s]

Gaps (ex-reports):   7%|▋         | 499/7211 [03:00<25:15,  4.43it/s]

Gaps (ex-reports):   7%|▋         | 500/7211 [03:00<24:14,  4.61it/s]

Gaps (ex-reports):   7%|▋         | 501/7211 [03:01<24:05,  4.64it/s]

Gaps (ex-reports):   7%|▋         | 502/7211 [03:01<23:26,  4.77it/s]

Gaps (ex-reports):   7%|▋         | 503/7211 [03:01<23:02,  4.85it/s]

Gaps (ex-reports):   7%|▋         | 504/7211 [03:01<23:03,  4.85it/s]

Gaps (ex-reports):   7%|▋         | 505/7211 [03:01<23:01,  4.85it/s]

Gaps (ex-reports):   7%|▋         | 506/7211 [03:02<22:40,  4.93it/s]

Gaps (ex-reports):   7%|▋         | 507/7211 [03:02<22:08,  5.04it/s]

Gaps (ex-reports):   7%|▋         | 508/7211 [03:02<23:03,  4.84it/s]

Gaps (ex-reports):   7%|▋         | 509/7211 [03:02<23:09,  4.82it/s]

Gaps (ex-reports):   7%|▋         | 510/7211 [03:03<23:04,  4.84it/s]

Gaps (ex-reports):   7%|▋         | 511/7211 [03:03<22:51,  4.89it/s]

Gaps (ex-reports):   7%|▋         | 512/7211 [03:03<22:42,  4.92it/s]

Gaps (ex-reports):   7%|▋         | 513/7211 [03:03<22:56,  4.87it/s]

Gaps (ex-reports):   7%|▋         | 514/7211 [03:03<22:58,  4.86it/s]

Gaps (ex-reports):   7%|▋         | 515/7211 [03:04<23:01,  4.85it/s]

Gaps (ex-reports):   7%|▋         | 516/7211 [03:04<23:02,  4.84it/s]

Gaps (ex-reports):   7%|▋         | 517/7211 [03:04<22:54,  4.87it/s]

Gaps (ex-reports):   7%|▋         | 518/7211 [03:04<22:58,  4.86it/s]

Gaps (ex-reports):   7%|▋         | 519/7211 [03:04<22:48,  4.89it/s]

Gaps (ex-reports):   7%|▋         | 520/7211 [03:05<22:49,  4.89it/s]

Gaps (ex-reports):   7%|▋         | 521/7211 [03:05<22:38,  4.92it/s]

Gaps (ex-reports):   7%|▋         | 522/7211 [03:05<22:11,  5.03it/s]

Gaps (ex-reports):   7%|▋         | 523/7211 [03:05<22:12,  5.02it/s]

Gaps (ex-reports):   7%|▋         | 524/7211 [03:05<22:48,  4.89it/s]

Gaps (ex-reports):   7%|▋         | 525/7211 [03:06<22:16,  5.00it/s]

Gaps (ex-reports):   7%|▋         | 526/7211 [03:06<22:49,  4.88it/s]

Gaps (ex-reports):   7%|▋         | 527/7211 [03:06<22:37,  4.92it/s]

Gaps (ex-reports):   7%|▋         | 528/7211 [03:06<22:36,  4.93it/s]

Gaps (ex-reports):   7%|▋         | 529/7211 [03:06<25:17,  4.40it/s]

Gaps (ex-reports):   7%|▋         | 530/7211 [03:07<24:47,  4.49it/s]

Gaps (ex-reports):   7%|▋         | 531/7211 [03:07<24:21,  4.57it/s]

Gaps (ex-reports):   7%|▋         | 532/7211 [03:07<23:43,  4.69it/s]

Gaps (ex-reports):   7%|▋         | 533/7211 [03:07<23:23,  4.76it/s]

Gaps (ex-reports):   7%|▋         | 534/7211 [03:08<23:27,  4.74it/s]

Gaps (ex-reports):   7%|▋         | 535/7211 [03:08<23:29,  4.74it/s]

Gaps (ex-reports):   7%|▋         | 536/7211 [03:08<23:16,  4.78it/s]

Gaps (ex-reports):   7%|▋         | 537/7211 [03:08<23:15,  4.78it/s]

Gaps (ex-reports):   7%|▋         | 538/7211 [03:08<23:11,  4.80it/s]

Gaps (ex-reports):   7%|▋         | 539/7211 [03:09<22:52,  4.86it/s]

Gaps (ex-reports):   7%|▋         | 540/7211 [03:09<22:47,  4.88it/s]

Gaps (ex-reports):   8%|▊         | 541/7211 [03:09<22:52,  4.86it/s]

Gaps (ex-reports):   8%|▊         | 542/7211 [03:09<22:57,  4.84it/s]

Gaps (ex-reports):   8%|▊         | 543/7211 [03:09<23:01,  4.83it/s]

Gaps (ex-reports):   8%|▊         | 544/7211 [03:10<23:14,  4.78it/s]

Gaps (ex-reports):   8%|▊         | 545/7211 [03:10<22:55,  4.85it/s]

Gaps (ex-reports):   8%|▊         | 546/7211 [03:10<22:36,  4.91it/s]

Gaps (ex-reports):   8%|▊         | 547/7211 [03:10<22:40,  4.90it/s]

Gaps (ex-reports):   8%|▊         | 548/7211 [03:10<22:15,  4.99it/s]

Gaps (ex-reports):   8%|▊         | 549/7211 [03:11<22:59,  4.83it/s]

Gaps (ex-reports):   8%|▊         | 550/7211 [03:11<22:54,  4.85it/s]

Gaps (ex-reports):   8%|▊         | 551/7211 [03:11<22:32,  4.93it/s]

Gaps (ex-reports):   8%|▊         | 552/7211 [03:11<22:15,  4.99it/s]

Gaps (ex-reports):   8%|▊         | 553/7211 [03:11<22:36,  4.91it/s]

Gaps (ex-reports):   8%|▊         | 554/7211 [03:12<22:57,  4.83it/s]

Gaps (ex-reports):   8%|▊         | 555/7211 [03:12<23:07,  4.80it/s]

Gaps (ex-reports):   8%|▊         | 556/7211 [03:12<23:09,  4.79it/s]

Gaps (ex-reports):   8%|▊         | 557/7211 [03:12<23:29,  4.72it/s]

Gaps (ex-reports):   8%|▊         | 558/7211 [03:12<23:09,  4.79it/s]

Gaps (ex-reports):   8%|▊         | 559/7211 [03:13<22:57,  4.83it/s]

Gaps (ex-reports):   8%|▊         | 560/7211 [03:13<23:01,  4.81it/s]

Gaps (ex-reports):   8%|▊         | 561/7211 [03:13<23:04,  4.80it/s]

Gaps (ex-reports):   8%|▊         | 562/7211 [03:13<23:03,  4.81it/s]

Gaps (ex-reports):   8%|▊         | 563/7211 [03:13<23:14,  4.77it/s]

Gaps (ex-reports):   8%|▊         | 564/7211 [03:14<22:49,  4.85it/s]

Gaps (ex-reports):   8%|▊         | 565/7211 [03:14<22:36,  4.90it/s]

Gaps (ex-reports):   8%|▊         | 566/7211 [03:14<22:39,  4.89it/s]

Gaps (ex-reports):   8%|▊         | 567/7211 [03:14<22:57,  4.82it/s]

Gaps (ex-reports):   8%|▊         | 568/7211 [03:15<22:38,  4.89it/s]

Gaps (ex-reports):   8%|▊         | 569/7211 [03:15<22:56,  4.83it/s]

Gaps (ex-reports):   8%|▊         | 570/7211 [03:15<23:08,  4.78it/s]

Gaps (ex-reports):   8%|▊         | 571/7211 [03:15<23:03,  4.80it/s]

Gaps (ex-reports):   8%|▊         | 572/7211 [03:15<22:44,  4.86it/s]

Gaps (ex-reports):   8%|▊         | 573/7211 [03:16<24:47,  4.46it/s]

Gaps (ex-reports):   8%|▊         | 574/7211 [03:16<24:15,  4.56it/s]

Gaps (ex-reports):   8%|▊         | 575/7211 [03:16<23:33,  4.70it/s]

Gaps (ex-reports):   8%|▊         | 576/7211 [03:16<22:45,  4.86it/s]

Gaps (ex-reports):   8%|▊         | 577/7211 [03:16<22:26,  4.93it/s]

Gaps (ex-reports):   8%|▊         | 578/7211 [03:17<22:27,  4.92it/s]

Gaps (ex-reports):   8%|▊         | 579/7211 [03:17<22:22,  4.94it/s]

Gaps (ex-reports):   8%|▊         | 580/7211 [03:17<22:15,  4.97it/s]

Gaps (ex-reports):   8%|▊         | 581/7211 [03:17<22:55,  4.82it/s]

Gaps (ex-reports):   8%|▊         | 582/7211 [03:17<22:29,  4.91it/s]

Gaps (ex-reports):   8%|▊         | 583/7211 [03:18<22:50,  4.84it/s]

Gaps (ex-reports):   8%|▊         | 584/7211 [03:18<22:40,  4.87it/s]

Gaps (ex-reports):   8%|▊         | 585/7211 [03:18<22:27,  4.92it/s]

Gaps (ex-reports):   8%|▊         | 586/7211 [03:18<22:21,  4.94it/s]

Gaps (ex-reports):   8%|▊         | 587/7211 [03:19<24:43,  4.47it/s]

Gaps (ex-reports):   8%|▊         | 588/7211 [03:19<23:36,  4.68it/s]

Gaps (ex-reports):   8%|▊         | 589/7211 [03:19<23:07,  4.77it/s]

Gaps (ex-reports):   8%|▊         | 590/7211 [03:19<22:51,  4.83it/s]

Gaps (ex-reports):   8%|▊         | 591/7211 [03:19<22:27,  4.91it/s]

Gaps (ex-reports):   8%|▊         | 592/7211 [03:20<22:36,  4.88it/s]

Gaps (ex-reports):   8%|▊         | 593/7211 [03:20<22:42,  4.86it/s]

Gaps (ex-reports):   8%|▊         | 594/7211 [03:20<22:10,  4.97it/s]

Gaps (ex-reports):   8%|▊         | 595/7211 [03:20<22:40,  4.86it/s]

Gaps (ex-reports):   8%|▊         | 596/7211 [03:20<22:33,  4.89it/s]

Gaps (ex-reports):   8%|▊         | 597/7211 [03:21<22:49,  4.83it/s]

Gaps (ex-reports):   8%|▊         | 598/7211 [03:21<22:37,  4.87it/s]

Gaps (ex-reports):   8%|▊         | 599/7211 [03:21<22:33,  4.88it/s]

Gaps (ex-reports):   8%|▊         | 600/7211 [03:21<22:18,  4.94it/s]

Gaps (ex-reports):   8%|▊         | 601/7211 [03:21<22:48,  4.83it/s]

Gaps (ex-reports):   8%|▊         | 602/7211 [03:22<22:40,  4.86it/s]

Gaps (ex-reports):   8%|▊         | 603/7211 [03:22<22:47,  4.83it/s]

Gaps (ex-reports):   8%|▊         | 604/7211 [03:22<22:38,  4.86it/s]

Gaps (ex-reports):   8%|▊         | 605/7211 [03:22<21:59,  5.01it/s]

Gaps (ex-reports):   8%|▊         | 606/7211 [03:22<22:27,  4.90it/s]

Gaps (ex-reports):   8%|▊         | 607/7211 [03:23<22:35,  4.87it/s]

Gaps (ex-reports):   8%|▊         | 608/7211 [03:23<22:45,  4.84it/s]

Gaps (ex-reports):   8%|▊         | 609/7211 [03:23<22:12,  4.96it/s]

Gaps (ex-reports):   8%|▊         | 610/7211 [03:23<22:42,  4.84it/s]

Gaps (ex-reports):   8%|▊         | 611/7211 [03:23<23:07,  4.76it/s]

Gaps (ex-reports):   8%|▊         | 612/7211 [03:24<23:18,  4.72it/s]

Gaps (ex-reports):   9%|▊         | 613/7211 [03:24<23:04,  4.76it/s]

Gaps (ex-reports):   9%|▊         | 614/7211 [03:24<23:11,  4.74it/s]

Gaps (ex-reports):   9%|▊         | 615/7211 [03:24<22:38,  4.86it/s]

Gaps (ex-reports):   9%|▊         | 616/7211 [03:24<22:10,  4.96it/s]

Gaps (ex-reports):   9%|▊         | 617/7211 [03:25<21:54,  5.02it/s]

Gaps (ex-reports):   9%|▊         | 618/7211 [03:25<22:04,  4.98it/s]

Gaps (ex-reports):   9%|▊         | 619/7211 [03:25<21:54,  5.01it/s]

Gaps (ex-reports):   9%|▊         | 620/7211 [03:25<21:39,  5.07it/s]

Gaps (ex-reports):   9%|▊         | 621/7211 [03:25<21:49,  5.03it/s]

Gaps (ex-reports):   9%|▊         | 622/7211 [03:26<21:36,  5.08it/s]

Gaps (ex-reports):   9%|▊         | 623/7211 [03:26<22:03,  4.98it/s]

Gaps (ex-reports):   9%|▊         | 624/7211 [03:26<22:34,  4.86it/s]

Gaps (ex-reports):   9%|▊         | 625/7211 [03:26<22:42,  4.84it/s]

Gaps (ex-reports):   9%|▊         | 626/7211 [03:26<22:40,  4.84it/s]

Gaps (ex-reports):   9%|▊         | 627/7211 [03:27<22:28,  4.88it/s]

Gaps (ex-reports):   9%|▊         | 628/7211 [03:27<22:05,  4.97it/s]

Gaps (ex-reports):   9%|▊         | 629/7211 [03:27<22:33,  4.86it/s]

Gaps (ex-reports):   9%|▊         | 630/7211 [03:27<22:26,  4.89it/s]

Gaps (ex-reports):   9%|▉         | 631/7211 [03:27<22:58,  4.77it/s]

Gaps (ex-reports):   9%|▉         | 632/7211 [03:28<23:06,  4.74it/s]

Gaps (ex-reports):   9%|▉         | 633/7211 [03:28<22:59,  4.77it/s]

Gaps (ex-reports):   9%|▉         | 634/7211 [03:28<23:10,  4.73it/s]

Gaps (ex-reports):   9%|▉         | 635/7211 [03:28<22:46,  4.81it/s]

Gaps (ex-reports):   9%|▉         | 636/7211 [03:29<22:10,  4.94it/s]

Gaps (ex-reports):   9%|▉         | 637/7211 [03:29<21:48,  5.02it/s]

Gaps (ex-reports):   9%|▉         | 638/7211 [03:29<21:40,  5.05it/s]

Gaps (ex-reports):   9%|▉         | 639/7211 [03:29<22:04,  4.96it/s]

Gaps (ex-reports):   9%|▉         | 640/7211 [03:29<22:16,  4.92it/s]

Gaps (ex-reports):   9%|▉         | 641/7211 [03:30<22:31,  4.86it/s]

Gaps (ex-reports):   9%|▉         | 642/7211 [03:30<22:34,  4.85it/s]

Gaps (ex-reports):   9%|▉         | 643/7211 [03:30<23:02,  4.75it/s]

Gaps (ex-reports):   9%|▉         | 644/7211 [03:30<22:51,  4.79it/s]

Gaps (ex-reports):   9%|▉         | 645/7211 [03:30<22:34,  4.85it/s]

Gaps (ex-reports):   9%|▉         | 646/7211 [03:31<22:27,  4.87it/s]

Gaps (ex-reports):   9%|▉         | 647/7211 [03:31<22:21,  4.89it/s]

Gaps (ex-reports):   9%|▉         | 648/7211 [03:31<22:27,  4.87it/s]

Gaps (ex-reports):   9%|▉         | 649/7211 [03:31<22:04,  4.95it/s]

Gaps (ex-reports):   9%|▉         | 650/7211 [03:31<22:19,  4.90it/s]

Gaps (ex-reports):   9%|▉         | 651/7211 [03:32<22:05,  4.95it/s]

Gaps (ex-reports):   9%|▉         | 652/7211 [03:32<22:29,  4.86it/s]

Gaps (ex-reports):   9%|▉         | 653/7211 [03:32<22:06,  4.94it/s]

Gaps (ex-reports):   9%|▉         | 654/7211 [03:32<22:50,  4.79it/s]

Gaps (ex-reports):   9%|▉         | 655/7211 [03:32<22:08,  4.93it/s]

Gaps (ex-reports):   9%|▉         | 656/7211 [03:33<22:11,  4.92it/s]

Gaps (ex-reports):   9%|▉         | 657/7211 [03:33<22:36,  4.83it/s]

Gaps (ex-reports):   9%|▉         | 658/7211 [03:33<22:34,  4.84it/s]

Gaps (ex-reports):   9%|▉         | 659/7211 [03:33<22:09,  4.93it/s]

Gaps (ex-reports):   9%|▉         | 660/7211 [03:33<22:22,  4.88it/s]

Gaps (ex-reports):   9%|▉         | 661/7211 [03:34<22:28,  4.86it/s]

Gaps (ex-reports):   9%|▉         | 662/7211 [03:34<22:33,  4.84it/s]

Gaps (ex-reports):   9%|▉         | 663/7211 [03:34<22:39,  4.82it/s]

Gaps (ex-reports):   9%|▉         | 664/7211 [03:34<22:31,  4.84it/s]

Gaps (ex-reports):   9%|▉         | 665/7211 [03:34<22:50,  4.77it/s]

Gaps (ex-reports):   9%|▉         | 666/7211 [03:35<22:32,  4.84it/s]

Gaps (ex-reports):   9%|▉         | 667/7211 [03:35<22:05,  4.94it/s]

Gaps (ex-reports):   9%|▉         | 668/7211 [03:35<22:42,  4.80it/s]

Gaps (ex-reports):   9%|▉         | 669/7211 [03:35<22:28,  4.85it/s]

Gaps (ex-reports):   9%|▉         | 670/7211 [03:35<22:13,  4.90it/s]

Gaps (ex-reports):   9%|▉         | 671/7211 [03:36<22:01,  4.95it/s]

Gaps (ex-reports):   9%|▉         | 672/7211 [03:36<22:04,  4.94it/s]

Gaps (ex-reports):   9%|▉         | 673/7211 [03:36<21:43,  5.02it/s]

Gaps (ex-reports):   9%|▉         | 674/7211 [03:36<23:33,  4.62it/s]

Gaps (ex-reports):   9%|▉         | 675/7211 [03:37<23:42,  4.60it/s]

Gaps (ex-reports):   9%|▉         | 676/7211 [03:37<23:28,  4.64it/s]

Gaps (ex-reports):   9%|▉         | 677/7211 [03:37<23:33,  4.62it/s]

Gaps (ex-reports):   9%|▉         | 678/7211 [03:37<23:06,  4.71it/s]

Gaps (ex-reports):   9%|▉         | 679/7211 [03:37<23:06,  4.71it/s]

Gaps (ex-reports):   9%|▉         | 680/7211 [03:38<23:05,  4.71it/s]

Gaps (ex-reports):   9%|▉         | 681/7211 [03:38<22:56,  4.74it/s]

Gaps (ex-reports):   9%|▉         | 682/7211 [03:38<22:47,  4.77it/s]

Gaps (ex-reports):   9%|▉         | 683/7211 [03:38<22:33,  4.82it/s]

Gaps (ex-reports):   9%|▉         | 684/7211 [03:38<22:22,  4.86it/s]

Gaps (ex-reports):   9%|▉         | 685/7211 [03:39<22:15,  4.89it/s]

Gaps (ex-reports):  10%|▉         | 686/7211 [03:39<22:27,  4.84it/s]

Gaps (ex-reports):  10%|▉         | 687/7211 [03:39<22:12,  4.90it/s]

Gaps (ex-reports):  10%|▉         | 688/7211 [03:39<22:09,  4.91it/s]

Gaps (ex-reports):  10%|▉         | 689/7211 [03:39<22:26,  4.84it/s]

Gaps (ex-reports):  10%|▉         | 690/7211 [03:40<22:29,  4.83it/s]

Gaps (ex-reports):  10%|▉         | 691/7211 [03:40<21:54,  4.96it/s]

Gaps (ex-reports):  10%|▉         | 692/7211 [03:40<21:31,  5.05it/s]

Gaps (ex-reports):  10%|▉         | 693/7211 [03:40<22:12,  4.89it/s]

Gaps (ex-reports):  10%|▉         | 694/7211 [03:40<21:59,  4.94it/s]

Gaps (ex-reports):  10%|▉         | 695/7211 [03:41<22:01,  4.93it/s]

Gaps (ex-reports):  10%|▉         | 696/7211 [03:41<21:47,  4.98it/s]

Gaps (ex-reports):  10%|▉         | 697/7211 [03:41<21:45,  4.99it/s]

Gaps (ex-reports):  10%|▉         | 698/7211 [03:41<21:54,  4.95it/s]

Gaps (ex-reports):  10%|▉         | 699/7211 [03:41<21:58,  4.94it/s]

Gaps (ex-reports):  10%|▉         | 700/7211 [03:42<22:09,  4.90it/s]

Gaps (ex-reports):  10%|▉         | 701/7211 [03:42<22:43,  4.77it/s]

Gaps (ex-reports):  10%|▉         | 702/7211 [03:42<22:09,  4.90it/s]

Gaps (ex-reports):  10%|▉         | 703/7211 [03:42<21:44,  4.99it/s]

Gaps (ex-reports):  10%|▉         | 704/7211 [03:43<22:07,  4.90it/s]

Gaps (ex-reports):  10%|▉         | 705/7211 [03:43<21:47,  4.98it/s]

Gaps (ex-reports):  10%|▉         | 706/7211 [03:43<22:00,  4.93it/s]

Gaps (ex-reports):  10%|▉         | 707/7211 [03:43<22:18,  4.86it/s]

Gaps (ex-reports):  10%|▉         | 708/7211 [03:43<22:11,  4.88it/s]

Gaps (ex-reports):  10%|▉         | 709/7211 [03:44<21:50,  4.96it/s]

Gaps (ex-reports):  10%|▉         | 710/7211 [03:44<21:27,  5.05it/s]

Gaps (ex-reports):  10%|▉         | 711/7211 [03:44<21:51,  4.96it/s]

Gaps (ex-reports):  10%|▉         | 712/7211 [03:44<22:20,  4.85it/s]

Gaps (ex-reports):  10%|▉         | 713/7211 [03:44<22:17,  4.86it/s]

Gaps (ex-reports):  10%|▉         | 714/7211 [03:45<22:24,  4.83it/s]

Gaps (ex-reports):  10%|▉         | 715/7211 [03:45<21:57,  4.93it/s]

Gaps (ex-reports):  10%|▉         | 716/7211 [03:45<22:17,  4.86it/s]

Gaps (ex-reports):  10%|▉         | 717/7211 [03:45<22:18,  4.85it/s]

Gaps (ex-reports):  10%|▉         | 718/7211 [03:45<22:18,  4.85it/s]

Gaps (ex-reports):  10%|▉         | 719/7211 [03:46<21:58,  4.92it/s]

Gaps (ex-reports):  10%|▉         | 720/7211 [03:46<21:58,  4.92it/s]

Gaps (ex-reports):  10%|▉         | 721/7211 [03:46<21:44,  4.97it/s]

Gaps (ex-reports):  10%|█         | 722/7211 [03:46<22:11,  4.87it/s]

Gaps (ex-reports):  10%|█         | 723/7211 [03:46<22:02,  4.90it/s]

Gaps (ex-reports):  10%|█         | 724/7211 [03:47<22:19,  4.84it/s]

Gaps (ex-reports):  10%|█         | 725/7211 [03:47<22:03,  4.90it/s]

Gaps (ex-reports):  10%|█         | 726/7211 [03:47<25:13,  4.28it/s]

Gaps (ex-reports):  10%|█         | 727/7211 [03:47<26:27,  4.09it/s]

Gaps (ex-reports):  10%|█         | 728/7211 [03:48<27:08,  3.98it/s]

Gaps (ex-reports):  10%|█         | 729/7211 [03:48<26:50,  4.03it/s]

Gaps (ex-reports):  10%|█         | 730/7211 [03:48<25:37,  4.21it/s]

Gaps (ex-reports):  10%|█         | 731/7211 [03:48<24:29,  4.41it/s]

Gaps (ex-reports):  10%|█         | 732/7211 [03:48<24:01,  4.49it/s]

Gaps (ex-reports):  10%|█         | 733/7211 [03:49<23:24,  4.61it/s]

Gaps (ex-reports):  10%|█         | 734/7211 [03:49<22:58,  4.70it/s]

Gaps (ex-reports):  10%|█         | 735/7211 [03:49<23:00,  4.69it/s]

Gaps (ex-reports):  10%|█         | 736/7211 [03:49<22:54,  4.71it/s]

Gaps (ex-reports):  10%|█         | 737/7211 [03:50<22:53,  4.71it/s]

Gaps (ex-reports):  10%|█         | 738/7211 [03:50<22:32,  4.79it/s]

Gaps (ex-reports):  10%|█         | 739/7211 [03:50<22:14,  4.85it/s]

Gaps (ex-reports):  10%|█         | 740/7211 [03:50<22:36,  4.77it/s]

Gaps (ex-reports):  10%|█         | 741/7211 [03:50<22:53,  4.71it/s]

Gaps (ex-reports):  10%|█         | 742/7211 [03:51<23:07,  4.66it/s]

Gaps (ex-reports):  10%|█         | 743/7211 [03:51<22:14,  4.85it/s]

Gaps (ex-reports):  10%|█         | 744/7211 [03:51<22:18,  4.83it/s]

Gaps (ex-reports):  10%|█         | 745/7211 [03:51<22:14,  4.84it/s]

Gaps (ex-reports):  10%|█         | 746/7211 [03:51<21:53,  4.92it/s]

Gaps (ex-reports):  10%|█         | 747/7211 [03:52<21:50,  4.93it/s]

Gaps (ex-reports):  10%|█         | 748/7211 [03:52<21:51,  4.93it/s]

Gaps (ex-reports):  10%|█         | 749/7211 [03:52<22:16,  4.83it/s]

Gaps (ex-reports):  10%|█         | 750/7211 [03:52<22:26,  4.80it/s]

Gaps (ex-reports):  10%|█         | 751/7211 [03:52<22:24,  4.81it/s]

Gaps (ex-reports):  10%|█         | 752/7211 [03:53<22:19,  4.82it/s]

Gaps (ex-reports):  10%|█         | 753/7211 [03:53<22:38,  4.75it/s]

Gaps (ex-reports):  10%|█         | 754/7211 [03:53<22:03,  4.88it/s]

Gaps (ex-reports):  10%|█         | 755/7211 [03:53<22:01,  4.88it/s]

Gaps (ex-reports):  10%|█         | 756/7211 [03:53<21:53,  4.91it/s]

Gaps (ex-reports):  10%|█         | 757/7211 [03:54<21:32,  4.99it/s]

Gaps (ex-reports):  11%|█         | 758/7211 [03:54<22:02,  4.88it/s]

Gaps (ex-reports):  11%|█         | 759/7211 [03:54<22:13,  4.84it/s]

Gaps (ex-reports):  11%|█         | 760/7211 [03:54<21:49,  4.92it/s]

Gaps (ex-reports):  11%|█         | 761/7211 [03:54<21:52,  4.91it/s]

Gaps (ex-reports):  11%|█         | 762/7211 [03:55<21:37,  4.97it/s]

Gaps (ex-reports):  11%|█         | 763/7211 [03:55<21:42,  4.95it/s]

Gaps (ex-reports):  11%|█         | 764/7211 [03:55<21:22,  5.03it/s]

Gaps (ex-reports):  11%|█         | 765/7211 [03:55<21:18,  5.04it/s]

Gaps (ex-reports):  11%|█         | 766/7211 [03:55<21:44,  4.94it/s]

Gaps (ex-reports):  11%|█         | 767/7211 [03:56<21:48,  4.92it/s]

Gaps (ex-reports):  11%|█         | 768/7211 [03:56<21:17,  5.04it/s]

Gaps (ex-reports):  11%|█         | 769/7211 [03:56<21:47,  4.93it/s]

Gaps (ex-reports):  11%|█         | 770/7211 [03:56<24:31,  4.38it/s]

Gaps (ex-reports):  11%|█         | 771/7211 [03:57<24:00,  4.47it/s]

Gaps (ex-reports):  11%|█         | 772/7211 [03:57<23:15,  4.62it/s]

Gaps (ex-reports):  11%|█         | 773/7211 [03:57<22:26,  4.78it/s]

Gaps (ex-reports):  11%|█         | 774/7211 [03:57<22:01,  4.87it/s]

Gaps (ex-reports):  11%|█         | 775/7211 [03:57<21:31,  4.98it/s]

Gaps (ex-reports):  11%|█         | 776/7211 [03:58<21:23,  5.01it/s]

Gaps (ex-reports):  11%|█         | 777/7211 [03:58<21:41,  4.95it/s]

Gaps (ex-reports):  11%|█         | 778/7211 [03:58<21:40,  4.94it/s]

Gaps (ex-reports):  11%|█         | 779/7211 [03:58<21:39,  4.95it/s]

Gaps (ex-reports):  11%|█         | 780/7211 [03:58<21:27,  4.99it/s]

Gaps (ex-reports):  11%|█         | 781/7211 [03:59<21:48,  4.91it/s]

Gaps (ex-reports):  11%|█         | 782/7211 [03:59<21:24,  5.01it/s]

Gaps (ex-reports):  11%|█         | 783/7211 [03:59<21:58,  4.88it/s]

Gaps (ex-reports):  11%|█         | 784/7211 [03:59<21:30,  4.98it/s]

Gaps (ex-reports):  11%|█         | 785/7211 [03:59<21:05,  5.08it/s]

Gaps (ex-reports):  11%|█         | 786/7211 [04:00<21:21,  5.01it/s]

Gaps (ex-reports):  11%|█         | 787/7211 [04:00<21:18,  5.02it/s]

Gaps (ex-reports):  11%|█         | 788/7211 [04:00<21:35,  4.96it/s]

Gaps (ex-reports):  11%|█         | 789/7211 [04:00<21:33,  4.97it/s]

Gaps (ex-reports):  11%|█         | 790/7211 [04:00<21:23,  5.00it/s]

Gaps (ex-reports):  11%|█         | 791/7211 [04:01<21:49,  4.90it/s]

Gaps (ex-reports):  11%|█         | 792/7211 [04:01<21:48,  4.90it/s]

Gaps (ex-reports):  11%|█         | 793/7211 [04:01<21:35,  4.95it/s]

Gaps (ex-reports):  11%|█         | 794/7211 [04:01<21:16,  5.03it/s]

Gaps (ex-reports):  11%|█         | 795/7211 [04:01<21:25,  4.99it/s]

Gaps (ex-reports):  11%|█         | 796/7211 [04:02<21:49,  4.90it/s]

Gaps (ex-reports):  11%|█         | 797/7211 [04:02<21:29,  4.97it/s]

Gaps (ex-reports):  11%|█         | 798/7211 [04:02<21:20,  5.01it/s]

Gaps (ex-reports):  11%|█         | 799/7211 [04:02<21:09,  5.05it/s]

Gaps (ex-reports):  11%|█         | 800/7211 [04:02<21:28,  4.97it/s]

Gaps (ex-reports):  11%|█         | 801/7211 [04:03<21:15,  5.03it/s]

Gaps (ex-reports):  11%|█         | 802/7211 [04:03<20:48,  5.13it/s]

Gaps (ex-reports):  11%|█         | 803/7211 [04:03<21:30,  4.96it/s]

Gaps (ex-reports):  11%|█         | 804/7211 [04:03<21:36,  4.94it/s]

Gaps (ex-reports):  11%|█         | 805/7211 [04:03<22:02,  4.84it/s]

Gaps (ex-reports):  11%|█         | 806/7211 [04:04<21:44,  4.91it/s]

Gaps (ex-reports):  11%|█         | 807/7211 [04:04<22:16,  4.79it/s]

Gaps (ex-reports):  11%|█         | 808/7211 [04:04<21:59,  4.85it/s]

Gaps (ex-reports):  11%|█         | 809/7211 [04:04<21:59,  4.85it/s]

Gaps (ex-reports):  11%|█         | 810/7211 [04:04<22:03,  4.84it/s]

Gaps (ex-reports):  11%|█         | 811/7211 [04:05<22:24,  4.76it/s]

Gaps (ex-reports):  11%|█▏        | 812/7211 [04:05<21:57,  4.86it/s]

Gaps (ex-reports):  11%|█▏        | 813/7211 [04:05<21:54,  4.87it/s]

Gaps (ex-reports):  11%|█▏        | 814/7211 [04:05<21:58,  4.85it/s]

Gaps (ex-reports):  11%|█▏        | 815/7211 [04:05<21:42,  4.91it/s]

Gaps (ex-reports):  11%|█▏        | 816/7211 [04:06<22:04,  4.83it/s]

Gaps (ex-reports):  11%|█▏        | 817/7211 [04:06<21:45,  4.90it/s]

Gaps (ex-reports):  11%|█▏        | 818/7211 [04:06<21:34,  4.94it/s]

Gaps (ex-reports):  11%|█▏        | 819/7211 [04:06<21:34,  4.94it/s]

Gaps (ex-reports):  11%|█▏        | 820/7211 [04:06<21:42,  4.91it/s]

Gaps (ex-reports):  11%|█▏        | 821/7211 [04:07<21:30,  4.95it/s]

Gaps (ex-reports):  11%|█▏        | 822/7211 [04:07<21:29,  4.95it/s]

Gaps (ex-reports):  11%|█▏        | 823/7211 [04:07<21:18,  5.00it/s]

Gaps (ex-reports):  11%|█▏        | 824/7211 [04:07<22:18,  4.77it/s]

Gaps (ex-reports):  11%|█▏        | 825/7211 [04:08<22:02,  4.83it/s]

Gaps (ex-reports):  11%|█▏        | 826/7211 [04:08<21:27,  4.96it/s]

Gaps (ex-reports):  11%|█▏        | 827/7211 [04:08<21:13,  5.01it/s]

Gaps (ex-reports):  11%|█▏        | 828/7211 [04:08<21:10,  5.02it/s]

Gaps (ex-reports):  11%|█▏        | 829/7211 [04:08<21:16,  5.00it/s]

Gaps (ex-reports):  12%|█▏        | 830/7211 [04:08<21:14,  5.01it/s]

Gaps (ex-reports):  12%|█▏        | 831/7211 [04:09<21:29,  4.95it/s]

Gaps (ex-reports):  12%|█▏        | 832/7211 [04:09<21:24,  4.97it/s]

Gaps (ex-reports):  12%|█▏        | 833/7211 [04:09<21:19,  4.98it/s]

Gaps (ex-reports):  12%|█▏        | 834/7211 [04:09<21:16,  4.99it/s]

Gaps (ex-reports):  12%|█▏        | 835/7211 [04:09<21:11,  5.01it/s]

Gaps (ex-reports):  12%|█▏        | 836/7211 [04:10<21:17,  4.99it/s]

Gaps (ex-reports):  12%|█▏        | 837/7211 [04:10<21:03,  5.04it/s]

Gaps (ex-reports):  12%|█▏        | 838/7211 [04:10<21:37,  4.91it/s]

Gaps (ex-reports):  12%|█▏        | 839/7211 [04:10<21:36,  4.91it/s]

Gaps (ex-reports):  12%|█▏        | 840/7211 [04:11<21:34,  4.92it/s]

Gaps (ex-reports):  12%|█▏        | 841/7211 [04:11<22:00,  4.82it/s]

Gaps (ex-reports):  12%|█▏        | 842/7211 [04:11<22:19,  4.76it/s]

Gaps (ex-reports):  12%|█▏        | 843/7211 [04:12<44:22,  2.39it/s]

Gaps (ex-reports):  12%|█▏        | 844/7211 [04:12<38:17,  2.77it/s]

Gaps (ex-reports):  12%|█▏        | 845/7211 [04:12<33:22,  3.18it/s]

Gaps (ex-reports):  12%|█▏        | 846/7211 [04:12<29:53,  3.55it/s]

Gaps (ex-reports):  12%|█▏        | 847/7211 [04:13<27:35,  3.84it/s]

Gaps (ex-reports):  12%|█▏        | 848/7211 [04:13<26:02,  4.07it/s]

Gaps (ex-reports):  12%|█▏        | 849/7211 [04:13<24:38,  4.30it/s]

Gaps (ex-reports):  12%|█▏        | 850/7211 [04:13<24:35,  4.31it/s]

Gaps (ex-reports):  12%|█▏        | 851/7211 [04:14<23:29,  4.51it/s]

Gaps (ex-reports):  12%|█▏        | 852/7211 [04:14<22:46,  4.65it/s]

Gaps (ex-reports):  12%|█▏        | 853/7211 [04:14<22:17,  4.75it/s]

Gaps (ex-reports):  12%|█▏        | 854/7211 [04:14<21:32,  4.92it/s]

Gaps (ex-reports):  12%|█▏        | 855/7211 [04:14<21:48,  4.86it/s]

Gaps (ex-reports):  12%|█▏        | 856/7211 [04:15<21:53,  4.84it/s]

Gaps (ex-reports):  12%|█▏        | 857/7211 [04:15<21:48,  4.85it/s]

Gaps (ex-reports):  12%|█▏        | 858/7211 [04:15<21:31,  4.92it/s]

Gaps (ex-reports):  12%|█▏        | 859/7211 [04:15<21:48,  4.86it/s]

Gaps (ex-reports):  12%|█▏        | 860/7211 [04:15<21:47,  4.86it/s]

Gaps (ex-reports):  12%|█▏        | 861/7211 [04:16<21:42,  4.87it/s]

Gaps (ex-reports):  12%|█▏        | 862/7211 [04:16<21:57,  4.82it/s]

Gaps (ex-reports):  12%|█▏        | 863/7211 [04:16<21:29,  4.92it/s]

Gaps (ex-reports):  12%|█▏        | 864/7211 [04:16<21:30,  4.92it/s]

Gaps (ex-reports):  12%|█▏        | 865/7211 [04:16<21:36,  4.90it/s]

Gaps (ex-reports):  12%|█▏        | 866/7211 [04:17<21:19,  4.96it/s]

Gaps (ex-reports):  12%|█▏        | 867/7211 [04:17<20:55,  5.05it/s]

Gaps (ex-reports):  12%|█▏        | 868/7211 [04:17<20:49,  5.08it/s]

Gaps (ex-reports):  12%|█▏        | 869/7211 [04:17<21:03,  5.02it/s]

Gaps (ex-reports):  12%|█▏        | 870/7211 [04:17<20:52,  5.06it/s]

Gaps (ex-reports):  12%|█▏        | 871/7211 [04:18<20:48,  5.08it/s]

Gaps (ex-reports):  12%|█▏        | 872/7211 [04:18<21:10,  4.99it/s]

Gaps (ex-reports):  12%|█▏        | 873/7211 [04:18<21:19,  4.95it/s]

Gaps (ex-reports):  12%|█▏        | 874/7211 [04:18<21:36,  4.89it/s]

Gaps (ex-reports):  12%|█▏        | 875/7211 [04:18<21:31,  4.90it/s]

Gaps (ex-reports):  12%|█▏        | 876/7211 [04:19<21:21,  4.94it/s]

Gaps (ex-reports):  12%|█▏        | 877/7211 [04:19<21:18,  4.95it/s]

Gaps (ex-reports):  12%|█▏        | 878/7211 [04:19<21:02,  5.02it/s]

Gaps (ex-reports):  12%|█▏        | 879/7211 [04:19<21:00,  5.03it/s]

Gaps (ex-reports):  12%|█▏        | 880/7211 [04:19<21:21,  4.94it/s]

Gaps (ex-reports):  12%|█▏        | 881/7211 [04:20<21:36,  4.88it/s]

Gaps (ex-reports):  12%|█▏        | 882/7211 [04:20<21:24,  4.93it/s]

Gaps (ex-reports):  12%|█▏        | 883/7211 [04:20<20:59,  5.03it/s]

Gaps (ex-reports):  12%|█▏        | 884/7211 [04:20<21:11,  4.98it/s]

Gaps (ex-reports):  12%|█▏        | 885/7211 [04:20<21:12,  4.97it/s]

Gaps (ex-reports):  12%|█▏        | 886/7211 [04:21<21:35,  4.88it/s]

Gaps (ex-reports):  12%|█▏        | 887/7211 [04:21<21:26,  4.91it/s]

Gaps (ex-reports):  12%|█▏        | 888/7211 [04:21<21:22,  4.93it/s]

Gaps (ex-reports):  12%|█▏        | 889/7211 [04:21<21:21,  4.94it/s]

Gaps (ex-reports):  12%|█▏        | 890/7211 [04:21<21:48,  4.83it/s]

Gaps (ex-reports):  12%|█▏        | 891/7211 [04:22<21:44,  4.84it/s]

Gaps (ex-reports):  12%|█▏        | 892/7211 [04:22<21:37,  4.87it/s]

Gaps (ex-reports):  12%|█▏        | 893/7211 [04:22<21:26,  4.91it/s]

Gaps (ex-reports):  12%|█▏        | 894/7211 [04:22<21:12,  4.96it/s]

Gaps (ex-reports):  12%|█▏        | 895/7211 [04:22<21:18,  4.94it/s]

Gaps (ex-reports):  12%|█▏        | 896/7211 [04:23<20:57,  5.02it/s]

Gaps (ex-reports):  12%|█▏        | 897/7211 [04:23<21:10,  4.97it/s]

Gaps (ex-reports):  12%|█▏        | 898/7211 [04:23<21:19,  4.93it/s]

Gaps (ex-reports):  12%|█▏        | 899/7211 [04:23<21:14,  4.95it/s]

Gaps (ex-reports):  12%|█▏        | 900/7211 [04:23<20:57,  5.02it/s]

Gaps (ex-reports):  12%|█▏        | 901/7211 [04:24<21:07,  4.98it/s]

Gaps (ex-reports):  13%|█▎        | 902/7211 [04:24<21:10,  4.97it/s]

Gaps (ex-reports):  13%|█▎        | 903/7211 [04:24<21:05,  4.99it/s]

Gaps (ex-reports):  13%|█▎        | 904/7211 [04:24<20:37,  5.10it/s]

Gaps (ex-reports):  13%|█▎        | 905/7211 [04:24<20:30,  5.12it/s]

Gaps (ex-reports):  13%|█▎        | 906/7211 [04:25<20:52,  5.03it/s]

Gaps (ex-reports):  13%|█▎        | 907/7211 [04:25<21:31,  4.88it/s]

Gaps (ex-reports):  13%|█▎        | 908/7211 [04:25<21:39,  4.85it/s]

Gaps (ex-reports):  13%|█▎        | 909/7211 [04:25<21:28,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 910/7211 [04:25<21:13,  4.95it/s]

Gaps (ex-reports):  13%|█▎        | 911/7211 [04:26<21:14,  4.94it/s]

Gaps (ex-reports):  13%|█▎        | 912/7211 [04:26<21:34,  4.87it/s]

Gaps (ex-reports):  13%|█▎        | 913/7211 [04:26<21:42,  4.83it/s]

Gaps (ex-reports):  13%|█▎        | 914/7211 [04:26<21:38,  4.85it/s]

Gaps (ex-reports):  13%|█▎        | 915/7211 [04:26<21:13,  4.94it/s]

Gaps (ex-reports):  13%|█▎        | 916/7211 [04:27<21:43,  4.83it/s]

Gaps (ex-reports):  13%|█▎        | 917/7211 [04:27<21:27,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 918/7211 [04:27<21:28,  4.88it/s]

Gaps (ex-reports):  13%|█▎        | 919/7211 [04:27<21:29,  4.88it/s]

Gaps (ex-reports):  13%|█▎        | 920/7211 [04:27<21:04,  4.98it/s]

Gaps (ex-reports):  13%|█▎        | 921/7211 [04:28<21:40,  4.84it/s]

Gaps (ex-reports):  13%|█▎        | 922/7211 [04:28<21:21,  4.91it/s]

Gaps (ex-reports):  13%|█▎        | 923/7211 [04:28<21:10,  4.95it/s]

Gaps (ex-reports):  13%|█▎        | 924/7211 [04:28<21:40,  4.83it/s]

Gaps (ex-reports):  13%|█▎        | 925/7211 [04:29<21:57,  4.77it/s]

Gaps (ex-reports):  13%|█▎        | 926/7211 [04:29<21:59,  4.76it/s]

Gaps (ex-reports):  13%|█▎        | 927/7211 [04:29<21:54,  4.78it/s]

Gaps (ex-reports):  13%|█▎        | 928/7211 [04:29<21:37,  4.84it/s]

Gaps (ex-reports):  13%|█▎        | 929/7211 [04:30<36:24,  2.88it/s]

Gaps (ex-reports):  13%|█▎        | 930/7211 [04:30<31:42,  3.30it/s]

Gaps (ex-reports):  13%|█▎        | 931/7211 [04:30<28:26,  3.68it/s]

Gaps (ex-reports):  13%|█▎        | 932/7211 [04:30<26:24,  3.96it/s]

Gaps (ex-reports):  13%|█▎        | 933/7211 [04:32<53:38,  1.95it/s]

Gaps (ex-reports):  13%|█▎        | 934/7211 [04:32<43:59,  2.38it/s]

Gaps (ex-reports):  13%|█▎        | 935/7211 [04:32<36:55,  2.83it/s]

Gaps (ex-reports):  13%|█▎        | 936/7211 [04:32<32:19,  3.24it/s]

Gaps (ex-reports):  13%|█▎        | 937/7211 [04:32<29:26,  3.55it/s]

Gaps (ex-reports):  13%|█▎        | 938/7211 [04:33<26:46,  3.90it/s]

Gaps (ex-reports):  13%|█▎        | 939/7211 [04:33<24:50,  4.21it/s]

Gaps (ex-reports):  13%|█▎        | 940/7211 [04:33<24:01,  4.35it/s]

Gaps (ex-reports):  13%|█▎        | 941/7211 [04:33<23:30,  4.45it/s]

Gaps (ex-reports):  13%|█▎        | 942/7211 [04:33<23:00,  4.54it/s]

Gaps (ex-reports):  13%|█▎        | 943/7211 [04:34<22:43,  4.60it/s]

Gaps (ex-reports):  13%|█▎        | 944/7211 [04:34<28:06,  3.72it/s]

Gaps (ex-reports):  13%|█▎        | 945/7211 [04:34<25:50,  4.04it/s]

Gaps (ex-reports):  13%|█▎        | 946/7211 [04:34<24:57,  4.18it/s]

Gaps (ex-reports):  13%|█▎        | 947/7211 [04:35<23:41,  4.41it/s]

Gaps (ex-reports):  13%|█▎        | 948/7211 [04:35<22:56,  4.55it/s]

Gaps (ex-reports):  13%|█▎        | 949/7211 [04:35<22:19,  4.68it/s]

Gaps (ex-reports):  13%|█▎        | 950/7211 [04:35<22:04,  4.73it/s]

Gaps (ex-reports):  13%|█▎        | 951/7211 [04:35<21:30,  4.85it/s]

Gaps (ex-reports):  13%|█▎        | 952/7211 [04:36<21:03,  4.95it/s]

Gaps (ex-reports):  13%|█▎        | 953/7211 [04:36<20:42,  5.04it/s]

Gaps (ex-reports):  13%|█▎        | 954/7211 [04:36<20:29,  5.09it/s]

Gaps (ex-reports):  13%|█▎        | 955/7211 [04:36<20:29,  5.09it/s]

Gaps (ex-reports):  13%|█▎        | 956/7211 [04:36<20:42,  5.03it/s]

Gaps (ex-reports):  13%|█▎        | 957/7211 [04:37<21:05,  4.94it/s]

Gaps (ex-reports):  13%|█▎        | 958/7211 [04:37<21:24,  4.87it/s]

Gaps (ex-reports):  13%|█▎        | 959/7211 [04:37<21:10,  4.92it/s]

Gaps (ex-reports):  13%|█▎        | 960/7211 [04:37<21:14,  4.90it/s]

Gaps (ex-reports):  13%|█▎        | 961/7211 [04:37<21:17,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 962/7211 [04:38<21:12,  4.91it/s]

Gaps (ex-reports):  13%|█▎        | 963/7211 [04:38<21:18,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 964/7211 [04:38<21:25,  4.86it/s]

Gaps (ex-reports):  13%|█▎        | 965/7211 [04:38<21:32,  4.83it/s]

Gaps (ex-reports):  13%|█▎        | 966/7211 [04:38<21:07,  4.93it/s]

Gaps (ex-reports):  13%|█▎        | 967/7211 [04:39<21:29,  4.84it/s]

Gaps (ex-reports):  13%|█▎        | 968/7211 [04:39<21:18,  4.88it/s]

Gaps (ex-reports):  13%|█▎        | 969/7211 [04:39<21:16,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 970/7211 [04:39<22:16,  4.67it/s]

Gaps (ex-reports):  13%|█▎        | 971/7211 [04:40<21:53,  4.75it/s]

Gaps (ex-reports):  13%|█▎        | 972/7211 [04:40<21:18,  4.88it/s]

Gaps (ex-reports):  13%|█▎        | 973/7211 [04:40<21:18,  4.88it/s]

Gaps (ex-reports):  14%|█▎        | 974/7211 [04:40<21:07,  4.92it/s]

Gaps (ex-reports):  14%|█▎        | 975/7211 [04:40<20:57,  4.96it/s]

Gaps (ex-reports):  14%|█▎        | 976/7211 [04:40<20:43,  5.01it/s]

Gaps (ex-reports):  14%|█▎        | 977/7211 [04:41<21:05,  4.93it/s]

Gaps (ex-reports):  14%|█▎        | 978/7211 [04:41<21:15,  4.89it/s]

Gaps (ex-reports):  14%|█▎        | 979/7211 [04:41<21:34,  4.82it/s]

Gaps (ex-reports):  14%|█▎        | 980/7211 [04:41<21:17,  4.88it/s]

Gaps (ex-reports):  14%|█▎        | 981/7211 [04:42<21:00,  4.94it/s]

Gaps (ex-reports):  14%|█▎        | 982/7211 [04:42<21:02,  4.93it/s]

Gaps (ex-reports):  14%|█▎        | 983/7211 [04:42<20:44,  5.00it/s]

Gaps (ex-reports):  14%|█▎        | 984/7211 [04:42<20:52,  4.97it/s]

Gaps (ex-reports):  14%|█▎        | 985/7211 [04:42<20:42,  5.01it/s]

Gaps (ex-reports):  14%|█▎        | 986/7211 [04:43<20:34,  5.04it/s]

Gaps (ex-reports):  14%|█▎        | 987/7211 [04:43<20:37,  5.03it/s]

Gaps (ex-reports):  14%|█▎        | 988/7211 [04:43<20:36,  5.03it/s]

Gaps (ex-reports):  14%|█▎        | 989/7211 [04:43<20:41,  5.01it/s]

Gaps (ex-reports):  14%|█▎        | 990/7211 [04:43<20:28,  5.06it/s]

Gaps (ex-reports):  14%|█▎        | 991/7211 [04:44<20:20,  5.10it/s]

Gaps (ex-reports):  14%|█▍        | 992/7211 [04:44<20:13,  5.13it/s]

Gaps (ex-reports):  14%|█▍        | 993/7211 [04:44<20:20,  5.09it/s]

Gaps (ex-reports):  14%|█▍        | 994/7211 [04:44<20:28,  5.06it/s]

Gaps (ex-reports):  14%|█▍        | 995/7211 [04:44<20:17,  5.11it/s]

Gaps (ex-reports):  14%|█▍        | 996/7211 [04:44<20:10,  5.13it/s]

Gaps (ex-reports):  14%|█▍        | 997/7211 [04:45<20:06,  5.15it/s]

Gaps (ex-reports):  14%|█▍        | 998/7211 [04:45<20:30,  5.05it/s]

Gaps (ex-reports):  14%|█▍        | 999/7211 [04:45<20:57,  4.94it/s]

Gaps (ex-reports):  14%|█▍        | 1000/7211 [04:45<20:54,  4.95it/s]

Gaps (ex-reports):  14%|█▍        | 1001/7211 [04:46<21:06,  4.90it/s]

Gaps (ex-reports):  14%|█▍        | 1002/7211 [04:46<20:53,  4.95it/s]

Gaps (ex-reports):  14%|█▍        | 1003/7211 [04:46<21:01,  4.92it/s]

Gaps (ex-reports):  14%|█▍        | 1004/7211 [04:46<20:52,  4.96it/s]

Gaps (ex-reports):  14%|█▍        | 1005/7211 [04:46<22:23,  4.62it/s]

Gaps (ex-reports):  14%|█▍        | 1006/7211 [04:47<22:23,  4.62it/s]

Gaps (ex-reports):  14%|█▍        | 1007/7211 [04:47<22:02,  4.69it/s]

Gaps (ex-reports):  14%|█▍        | 1008/7211 [04:47<21:23,  4.83it/s]

Gaps (ex-reports):  14%|█▍        | 1009/7211 [04:47<21:06,  4.90it/s]

Gaps (ex-reports):  14%|█▍        | 1010/7211 [04:47<21:31,  4.80it/s]

Gaps (ex-reports):  14%|█▍        | 1011/7211 [04:48<21:38,  4.77it/s]

Gaps (ex-reports):  14%|█▍        | 1012/7211 [04:48<21:16,  4.86it/s]

Gaps (ex-reports):  14%|█▍        | 1013/7211 [04:48<20:46,  4.97it/s]

Gaps (ex-reports):  14%|█▍        | 1014/7211 [04:48<20:40,  4.99it/s]

Gaps (ex-reports):  14%|█▍        | 1015/7211 [04:48<20:39,  5.00it/s]

Gaps (ex-reports):  14%|█▍        | 1016/7211 [04:49<20:42,  4.99it/s]

Gaps (ex-reports):  14%|█▍        | 1017/7211 [04:49<21:09,  4.88it/s]

Gaps (ex-reports):  14%|█▍        | 1018/7211 [04:49<21:29,  4.80it/s]

Gaps (ex-reports):  14%|█▍        | 1019/7211 [04:49<21:29,  4.80it/s]

Gaps (ex-reports):  14%|█▍        | 1020/7211 [04:49<21:37,  4.77it/s]

Gaps (ex-reports):  14%|█▍        | 1021/7211 [04:50<21:23,  4.82it/s]

Gaps (ex-reports):  14%|█▍        | 1022/7211 [04:50<21:28,  4.80it/s]

Gaps (ex-reports):  14%|█▍        | 1023/7211 [04:50<21:16,  4.85it/s]

Gaps (ex-reports):  14%|█▍        | 1024/7211 [04:50<20:57,  4.92it/s]

Gaps (ex-reports):  14%|█▍        | 1025/7211 [04:50<21:00,  4.91it/s]

Gaps (ex-reports):  14%|█▍        | 1026/7211 [04:51<20:41,  4.98it/s]

Gaps (ex-reports):  14%|█▍        | 1027/7211 [04:51<20:54,  4.93it/s]

Gaps (ex-reports):  14%|█▍        | 1028/7211 [04:51<20:56,  4.92it/s]

Gaps (ex-reports):  14%|█▍        | 1029/7211 [04:51<20:40,  4.98it/s]

Gaps (ex-reports):  14%|█▍        | 1030/7211 [04:51<20:57,  4.92it/s]

Gaps (ex-reports):  14%|█▍        | 1031/7211 [04:52<21:03,  4.89it/s]

Gaps (ex-reports):  14%|█▍        | 1032/7211 [04:52<23:00,  4.47it/s]

Gaps (ex-reports):  14%|█▍        | 1033/7211 [04:52<23:32,  4.37it/s]

Gaps (ex-reports):  14%|█▍        | 1034/7211 [04:52<24:42,  4.17it/s]

Gaps (ex-reports):  14%|█▍        | 1035/7211 [04:53<25:52,  3.98it/s]

Gaps (ex-reports):  14%|█▍        | 1036/7211 [04:53<24:04,  4.27it/s]

Gaps (ex-reports):  14%|█▍        | 1037/7211 [04:53<23:00,  4.47it/s]

Gaps (ex-reports):  14%|█▍        | 1038/7211 [04:53<22:15,  4.62it/s]

Gaps (ex-reports):  14%|█▍        | 1039/7211 [04:54<22:12,  4.63it/s]

Gaps (ex-reports):  14%|█▍        | 1040/7211 [04:54<21:44,  4.73it/s]

Gaps (ex-reports):  14%|█▍        | 1041/7211 [04:54<21:47,  4.72it/s]

Gaps (ex-reports):  14%|█▍        | 1042/7211 [04:54<21:48,  4.71it/s]

Gaps (ex-reports):  14%|█▍        | 1043/7211 [04:54<21:22,  4.81it/s]

Gaps (ex-reports):  14%|█▍        | 1044/7211 [04:55<21:19,  4.82it/s]

Gaps (ex-reports):  14%|█▍        | 1045/7211 [04:55<21:01,  4.89it/s]

Gaps (ex-reports):  15%|█▍        | 1046/7211 [04:55<21:08,  4.86it/s]

Gaps (ex-reports):  15%|█▍        | 1047/7211 [04:55<21:05,  4.87it/s]

Gaps (ex-reports):  15%|█▍        | 1048/7211 [04:55<20:44,  4.95it/s]

Gaps (ex-reports):  15%|█▍        | 1049/7211 [04:56<20:42,  4.96it/s]

Gaps (ex-reports):  15%|█▍        | 1050/7211 [04:56<21:12,  4.84it/s]

Gaps (ex-reports):  15%|█▍        | 1051/7211 [04:56<20:45,  4.95it/s]

Gaps (ex-reports):  15%|█▍        | 1052/7211 [04:56<20:58,  4.90it/s]

Gaps (ex-reports):  15%|█▍        | 1053/7211 [04:56<21:07,  4.86it/s]

Gaps (ex-reports):  15%|█▍        | 1054/7211 [04:57<21:00,  4.88it/s]

Gaps (ex-reports):  15%|█▍        | 1055/7211 [04:57<20:33,  4.99it/s]

Gaps (ex-reports):  15%|█▍        | 1056/7211 [04:57<20:24,  5.03it/s]

Gaps (ex-reports):  15%|█▍        | 1057/7211 [04:57<21:00,  4.88it/s]

Gaps (ex-reports):  15%|█▍        | 1058/7211 [04:57<20:44,  4.95it/s]

Gaps (ex-reports):  15%|█▍        | 1059/7211 [04:58<20:55,  4.90it/s]

Gaps (ex-reports):  15%|█▍        | 1060/7211 [04:58<21:14,  4.82it/s]

Gaps (ex-reports):  15%|█▍        | 1061/7211 [04:58<21:05,  4.86it/s]

Gaps (ex-reports):  15%|█▍        | 1062/7211 [04:58<21:25,  4.78it/s]

Gaps (ex-reports):  15%|█▍        | 1063/7211 [04:58<21:10,  4.84it/s]

Gaps (ex-reports):  15%|█▍        | 1064/7211 [04:59<21:04,  4.86it/s]

Gaps (ex-reports):  15%|█▍        | 1065/7211 [04:59<20:54,  4.90it/s]

Gaps (ex-reports):  15%|█▍        | 1066/7211 [04:59<21:05,  4.86it/s]

Gaps (ex-reports):  15%|█▍        | 1067/7211 [04:59<20:56,  4.89it/s]

Gaps (ex-reports):  15%|█▍        | 1068/7211 [04:59<20:50,  4.91it/s]

Gaps (ex-reports):  15%|█▍        | 1069/7211 [05:00<20:54,  4.90it/s]

Gaps (ex-reports):  15%|█▍        | 1070/7211 [05:00<20:56,  4.89it/s]

Gaps (ex-reports):  15%|█▍        | 1071/7211 [05:00<20:51,  4.90it/s]

Gaps (ex-reports):  15%|█▍        | 1072/7211 [05:00<20:38,  4.96it/s]

Gaps (ex-reports):  15%|█▍        | 1073/7211 [05:00<20:42,  4.94it/s]

Gaps (ex-reports):  15%|█▍        | 1074/7211 [05:01<20:34,  4.97it/s]

Gaps (ex-reports):  15%|█▍        | 1075/7211 [05:01<20:40,  4.95it/s]

Gaps (ex-reports):  15%|█▍        | 1076/7211 [05:01<20:25,  5.01it/s]

Gaps (ex-reports):  15%|█▍        | 1077/7211 [05:01<20:36,  4.96it/s]

Gaps (ex-reports):  15%|█▍        | 1078/7211 [05:01<20:15,  5.05it/s]

Gaps (ex-reports):  15%|█▍        | 1079/7211 [05:02<20:24,  5.01it/s]

Gaps (ex-reports):  15%|█▍        | 1080/7211 [05:02<20:31,  4.98it/s]

Gaps (ex-reports):  15%|█▍        | 1081/7211 [05:02<20:11,  5.06it/s]

Gaps (ex-reports):  15%|█▌        | 1082/7211 [05:02<19:56,  5.12it/s]

Gaps (ex-reports):  15%|█▌        | 1083/7211 [05:02<19:54,  5.13it/s]

Gaps (ex-reports):  15%|█▌        | 1084/7211 [05:03<20:21,  5.02it/s]

Gaps (ex-reports):  15%|█▌        | 1085/7211 [05:03<20:22,  5.01it/s]

Gaps (ex-reports):  15%|█▌        | 1086/7211 [05:03<20:47,  4.91it/s]

Gaps (ex-reports):  15%|█▌        | 1087/7211 [05:03<20:43,  4.93it/s]

Gaps (ex-reports):  15%|█▌        | 1088/7211 [05:03<20:36,  4.95it/s]

Gaps (ex-reports):  15%|█▌        | 1089/7211 [05:04<20:33,  4.96it/s]

Gaps (ex-reports):  15%|█▌        | 1090/7211 [05:04<20:32,  4.97it/s]

Gaps (ex-reports):  15%|█▌        | 1091/7211 [05:04<20:32,  4.97it/s]

Gaps (ex-reports):  15%|█▌        | 1092/7211 [05:04<20:49,  4.90it/s]

Gaps (ex-reports):  15%|█▌        | 1093/7211 [05:04<20:49,  4.90it/s]

Gaps (ex-reports):  15%|█▌        | 1094/7211 [05:05<22:28,  4.54it/s]

Gaps (ex-reports):  15%|█▌        | 1095/7211 [05:05<21:31,  4.73it/s]

Gaps (ex-reports):  15%|█▌        | 1096/7211 [05:05<21:01,  4.85it/s]

Gaps (ex-reports):  15%|█▌        | 1097/7211 [05:05<20:56,  4.87it/s]

Gaps (ex-reports):  15%|█▌        | 1098/7211 [05:06<20:34,  4.95it/s]

Gaps (ex-reports):  15%|█▌        | 1099/7211 [05:06<20:19,  5.01it/s]

Gaps (ex-reports):  15%|█▌        | 1100/7211 [05:06<20:46,  4.90it/s]

Gaps (ex-reports):  15%|█▌        | 1101/7211 [05:06<20:37,  4.94it/s]

Gaps (ex-reports):  15%|█▌        | 1102/7211 [05:06<20:39,  4.93it/s]

Gaps (ex-reports):  15%|█▌        | 1103/7211 [05:07<20:32,  4.96it/s]

Gaps (ex-reports):  15%|█▌        | 1104/7211 [05:07<20:45,  4.90it/s]

Gaps (ex-reports):  15%|█▌        | 1105/7211 [05:07<20:19,  5.01it/s]

Gaps (ex-reports):  15%|█▌        | 1106/7211 [05:07<20:07,  5.06it/s]

Gaps (ex-reports):  15%|█▌        | 1107/7211 [05:07<19:55,  5.11it/s]

Gaps (ex-reports):  15%|█▌        | 1108/7211 [05:08<20:14,  5.02it/s]

Gaps (ex-reports):  15%|█▌        | 1109/7211 [05:08<20:06,  5.06it/s]

Gaps (ex-reports):  15%|█▌        | 1110/7211 [05:08<19:49,  5.13it/s]

Gaps (ex-reports):  15%|█▌        | 1111/7211 [05:08<19:49,  5.13it/s]

Gaps (ex-reports):  15%|█▌        | 1112/7211 [05:08<20:01,  5.08it/s]

Gaps (ex-reports):  15%|█▌        | 1113/7211 [05:09<20:03,  5.07it/s]

Gaps (ex-reports):  15%|█▌        | 1114/7211 [05:09<19:50,  5.12it/s]

Gaps (ex-reports):  15%|█▌        | 1115/7211 [05:09<19:48,  5.13it/s]

Gaps (ex-reports):  15%|█▌        | 1116/7211 [05:09<22:29,  4.52it/s]

Gaps (ex-reports):  15%|█▌        | 1117/7211 [05:09<21:39,  4.69it/s]

Gaps (ex-reports):  16%|█▌        | 1118/7211 [05:10<21:33,  4.71it/s]

Gaps (ex-reports):  16%|█▌        | 1119/7211 [05:10<21:08,  4.80it/s]

Gaps (ex-reports):  16%|█▌        | 1120/7211 [05:10<21:02,  4.82it/s]

Gaps (ex-reports):  16%|█▌        | 1121/7211 [05:10<20:31,  4.94it/s]

Gaps (ex-reports):  16%|█▌        | 1122/7211 [05:10<20:45,  4.89it/s]

Gaps (ex-reports):  16%|█▌        | 1123/7211 [05:11<21:25,  4.73it/s]

Gaps (ex-reports):  16%|█▌        | 1124/7211 [05:11<21:09,  4.79it/s]

Gaps (ex-reports):  16%|█▌        | 1125/7211 [05:11<20:38,  4.91it/s]

Gaps (ex-reports):  16%|█▌        | 1126/7211 [05:11<20:33,  4.93it/s]

Gaps (ex-reports):  16%|█▌        | 1127/7211 [05:11<20:52,  4.86it/s]

Gaps (ex-reports):  16%|█▌        | 1128/7211 [05:12<20:31,  4.94it/s]

Gaps (ex-reports):  16%|█▌        | 1129/7211 [05:12<20:23,  4.97it/s]

Gaps (ex-reports):  16%|█▌        | 1130/7211 [05:12<20:38,  4.91it/s]

Gaps (ex-reports):  16%|█▌        | 1131/7211 [05:12<20:43,  4.89it/s]

Gaps (ex-reports):  16%|█▌        | 1132/7211 [05:12<21:03,  4.81it/s]

Gaps (ex-reports):  16%|█▌        | 1133/7211 [05:13<20:56,  4.84it/s]

Gaps (ex-reports):  16%|█▌        | 1134/7211 [05:13<20:59,  4.82it/s]

Gaps (ex-reports):  16%|█▌        | 1135/7211 [05:13<21:11,  4.78it/s]

Gaps (ex-reports):  16%|█▌        | 1136/7211 [05:13<20:52,  4.85it/s]

Gaps (ex-reports):  16%|█▌        | 1137/7211 [05:13<20:59,  4.82it/s]

Gaps (ex-reports):  16%|█▌        | 1138/7211 [05:14<20:58,  4.82it/s]

Gaps (ex-reports):  16%|█▌        | 1139/7211 [05:14<20:44,  4.88it/s]

Gaps (ex-reports):  16%|█▌        | 1140/7211 [05:14<20:18,  4.98it/s]

Gaps (ex-reports):  16%|█▌        | 1141/7211 [05:14<20:13,  5.00it/s]

Gaps (ex-reports):  16%|█▌        | 1142/7211 [05:14<20:21,  4.97it/s]

Gaps (ex-reports):  16%|█▌        | 1143/7211 [05:15<20:01,  5.05it/s]

Gaps (ex-reports):  16%|█▌        | 1144/7211 [05:15<19:51,  5.09it/s]

Gaps (ex-reports):  16%|█▌        | 1145/7211 [05:15<19:42,  5.13it/s]

Gaps (ex-reports):  16%|█▌        | 1146/7211 [05:15<19:57,  5.07it/s]

Gaps (ex-reports):  16%|█▌        | 1147/7211 [05:15<20:01,  5.05it/s]

Gaps (ex-reports):  16%|█▌        | 1148/7211 [05:16<20:24,  4.95it/s]

Gaps (ex-reports):  16%|█▌        | 1149/7211 [05:16<20:31,  4.92it/s]

Gaps (ex-reports):  16%|█▌        | 1150/7211 [05:16<20:45,  4.87it/s]

Gaps (ex-reports):  16%|█▌        | 1151/7211 [05:16<22:38,  4.46it/s]

Gaps (ex-reports):  16%|█▌        | 1152/7211 [05:17<22:07,  4.57it/s]

Gaps (ex-reports):  16%|█▌        | 1153/7211 [05:17<21:35,  4.68it/s]

Gaps (ex-reports):  16%|█▌        | 1154/7211 [05:17<21:10,  4.77it/s]

Gaps (ex-reports):  16%|█▌        | 1155/7211 [05:17<20:53,  4.83it/s]

Gaps (ex-reports):  16%|█▌        | 1156/7211 [05:17<20:36,  4.90it/s]

Gaps (ex-reports):  16%|█▌        | 1157/7211 [05:18<20:22,  4.95it/s]

Gaps (ex-reports):  16%|█▌        | 1158/7211 [05:18<20:22,  4.95it/s]

Gaps (ex-reports):  16%|█▌        | 1159/7211 [05:18<20:14,  4.98it/s]

Gaps (ex-reports):  16%|█▌        | 1160/7211 [05:18<20:01,  5.04it/s]

Gaps (ex-reports):  16%|█▌        | 1161/7211 [05:18<19:55,  5.06it/s]

Gaps (ex-reports):  16%|█▌        | 1162/7211 [05:19<20:04,  5.02it/s]

Gaps (ex-reports):  16%|█▌        | 1163/7211 [05:19<20:23,  4.94it/s]

Gaps (ex-reports):  16%|█▌        | 1164/7211 [05:19<20:32,  4.91it/s]

Gaps (ex-reports):  16%|█▌        | 1165/7211 [05:19<20:23,  4.94it/s]

Gaps (ex-reports):  16%|█▌        | 1166/7211 [05:19<20:11,  4.99it/s]

Gaps (ex-reports):  16%|█▌        | 1167/7211 [05:20<20:12,  4.98it/s]

Gaps (ex-reports):  16%|█▌        | 1168/7211 [05:20<19:46,  5.09it/s]

Gaps (ex-reports):  16%|█▌        | 1169/7211 [05:20<19:44,  5.10it/s]

Gaps (ex-reports):  16%|█▌        | 1170/7211 [05:20<20:15,  4.97it/s]

Gaps (ex-reports):  16%|█▌        | 1171/7211 [05:20<20:23,  4.94it/s]

Gaps (ex-reports):  16%|█▋        | 1172/7211 [05:21<20:18,  4.95it/s]

Gaps (ex-reports):  16%|█▋        | 1173/7211 [05:21<20:14,  4.97it/s]

Gaps (ex-reports):  16%|█▋        | 1174/7211 [05:21<20:34,  4.89it/s]

Gaps (ex-reports):  16%|█▋        | 1175/7211 [05:21<20:25,  4.92it/s]

Gaps (ex-reports):  16%|█▋        | 1176/7211 [05:21<19:52,  5.06it/s]

Gaps (ex-reports):  16%|█▋        | 1177/7211 [05:22<19:53,  5.06it/s]

Gaps (ex-reports):  16%|█▋        | 1178/7211 [05:22<20:10,  4.99it/s]

Gaps (ex-reports):  16%|█▋        | 1179/7211 [05:22<20:30,  4.90it/s]

Gaps (ex-reports):  16%|█▋        | 1180/7211 [05:22<20:47,  4.84it/s]

Gaps (ex-reports):  16%|█▋        | 1181/7211 [05:22<20:40,  4.86it/s]

Gaps (ex-reports):  16%|█▋        | 1182/7211 [05:23<20:44,  4.84it/s]

Gaps (ex-reports):  16%|█▋        | 1183/7211 [05:23<20:42,  4.85it/s]

Gaps (ex-reports):  16%|█▋        | 1184/7211 [05:23<20:45,  4.84it/s]

Gaps (ex-reports):  16%|█▋        | 1185/7211 [05:23<21:00,  4.78it/s]

Gaps (ex-reports):  16%|█▋        | 1186/7211 [05:23<21:01,  4.78it/s]

Gaps (ex-reports):  16%|█▋        | 1187/7211 [05:24<20:54,  4.80it/s]

Gaps (ex-reports):  16%|█▋        | 1188/7211 [05:24<21:01,  4.78it/s]

Gaps (ex-reports):  16%|█▋        | 1189/7211 [05:24<20:45,  4.83it/s]

Gaps (ex-reports):  17%|█▋        | 1190/7211 [05:24<20:51,  4.81it/s]

Gaps (ex-reports):  17%|█▋        | 1191/7211 [05:24<20:40,  4.85it/s]

Gaps (ex-reports):  17%|█▋        | 1192/7211 [05:25<20:53,  4.80it/s]

Gaps (ex-reports):  17%|█▋        | 1193/7211 [05:25<20:53,  4.80it/s]

Gaps (ex-reports):  17%|█▋        | 1194/7211 [05:25<20:35,  4.87it/s]

Gaps (ex-reports):  17%|█▋        | 1195/7211 [05:25<20:08,  4.98it/s]

Gaps (ex-reports):  17%|█▋        | 1196/7211 [05:25<19:55,  5.03it/s]

Gaps (ex-reports):  17%|█▋        | 1197/7211 [05:26<20:17,  4.94it/s]

Gaps (ex-reports):  17%|█▋        | 1198/7211 [05:26<22:51,  4.39it/s]

Gaps (ex-reports):  17%|█▋        | 1199/7211 [05:26<22:21,  4.48it/s]

Gaps (ex-reports):  17%|█▋        | 1200/7211 [05:26<21:54,  4.57it/s]

Gaps (ex-reports):  17%|█▋        | 1201/7211 [05:27<46:24,  2.16it/s]

Gaps (ex-reports):  17%|█▋        | 1202/7211 [05:28<38:46,  2.58it/s]

Gaps (ex-reports):  17%|█▋        | 1203/7211 [05:28<34:06,  2.94it/s]

Gaps (ex-reports):  17%|█▋        | 1204/7211 [05:28<30:16,  3.31it/s]

Gaps (ex-reports):  17%|█▋        | 1205/7211 [05:29<47:24,  2.11it/s]

Gaps (ex-reports):  17%|█▋        | 1206/7211 [05:29<39:31,  2.53it/s]

Gaps (ex-reports):  17%|█▋        | 1207/7211 [05:29<33:36,  2.98it/s]

Gaps (ex-reports):  17%|█▋        | 1208/7211 [05:30<30:11,  3.31it/s]

Gaps (ex-reports):  17%|█▋        | 1209/7211 [05:30<27:30,  3.64it/s]

Gaps (ex-reports):  17%|█▋        | 1210/7211 [05:30<25:25,  3.93it/s]

Gaps (ex-reports):  17%|█▋        | 1211/7211 [05:31<40:55,  2.44it/s]

Gaps (ex-reports):  17%|█▋        | 1212/7211 [05:31<34:50,  2.87it/s]

Gaps (ex-reports):  17%|█▋        | 1213/7211 [05:31<30:31,  3.28it/s]

Gaps (ex-reports):  17%|█▋        | 1214/7211 [05:31<27:29,  3.64it/s]

Gaps (ex-reports):  17%|█▋        | 1215/7211 [05:32<25:09,  3.97it/s]

Gaps (ex-reports):  17%|█▋        | 1216/7211 [05:32<24:04,  4.15it/s]

Gaps (ex-reports):  17%|█▋        | 1217/7211 [05:32<22:22,  4.46it/s]

Gaps (ex-reports):  17%|█▋        | 1218/7211 [05:32<21:45,  4.59it/s]

Gaps (ex-reports):  17%|█▋        | 1219/7211 [05:32<21:27,  4.65it/s]

Gaps (ex-reports):  17%|█▋        | 1220/7211 [05:33<21:28,  4.65it/s]

Gaps (ex-reports):  17%|█▋        | 1221/7211 [05:33<22:03,  4.53it/s]

Gaps (ex-reports):  17%|█▋        | 1222/7211 [05:33<21:30,  4.64it/s]

Gaps (ex-reports):  17%|█▋        | 1223/7211 [05:33<21:05,  4.73it/s]

Gaps (ex-reports):  17%|█▋        | 1224/7211 [05:33<20:52,  4.78it/s]

Gaps (ex-reports):  17%|█▋        | 1225/7211 [05:34<20:28,  4.87it/s]

Gaps (ex-reports):  17%|█▋        | 1226/7211 [05:34<20:29,  4.87it/s]

Gaps (ex-reports):  17%|█▋        | 1227/7211 [05:34<20:27,  4.88it/s]

Gaps (ex-reports):  17%|█▋        | 1228/7211 [05:34<20:29,  4.87it/s]

Gaps (ex-reports):  17%|█▋        | 1229/7211 [05:34<20:16,  4.92it/s]

Gaps (ex-reports):  17%|█▋        | 1230/7211 [05:36<1:00:28,  1.65it/s]

Gaps (ex-reports):  17%|█▋        | 1231/7211 [05:36<48:11,  2.07it/s]

Gaps (ex-reports):  17%|█▋        | 1232/7211 [05:36<39:50,  2.50it/s]

Gaps (ex-reports):  17%|█▋        | 1233/7211 [05:37<33:48,  2.95it/s]

Gaps (ex-reports):  17%|█▋        | 1234/7211 [05:37<29:59,  3.32it/s]

Gaps (ex-reports):  17%|█▋        | 1235/7211 [05:37<27:23,  3.64it/s]

Gaps (ex-reports):  17%|█▋        | 1236/7211 [05:37<29:44,  3.35it/s]

Gaps (ex-reports):  17%|█▋        | 1237/7211 [05:38<26:30,  3.76it/s]

Gaps (ex-reports):  17%|█▋        | 1238/7211 [05:38<24:42,  4.03it/s]

Gaps (ex-reports):  17%|█▋        | 1239/7211 [05:38<23:08,  4.30it/s]

Gaps (ex-reports):  17%|█▋        | 1240/7211 [05:38<22:24,  4.44it/s]

Gaps (ex-reports):  17%|█▋        | 1241/7211 [05:38<21:52,  4.55it/s]

Gaps (ex-reports):  17%|█▋        | 1242/7211 [05:39<21:06,  4.71it/s]

Gaps (ex-reports):  17%|█▋        | 1243/7211 [05:39<20:48,  4.78it/s]

Gaps (ex-reports):  17%|█▋        | 1244/7211 [05:39<20:36,  4.83it/s]

Gaps (ex-reports):  17%|█▋        | 1245/7211 [05:39<20:20,  4.89it/s]

Gaps (ex-reports):  17%|█▋        | 1246/7211 [05:39<20:44,  4.79it/s]

Gaps (ex-reports):  17%|█▋        | 1247/7211 [05:40<20:36,  4.82it/s]

Gaps (ex-reports):  17%|█▋        | 1248/7211 [05:40<20:55,  4.75it/s]

Gaps (ex-reports):  17%|█▋        | 1249/7211 [05:40<20:43,  4.79it/s]

Gaps (ex-reports):  17%|█▋        | 1250/7211 [05:40<20:36,  4.82it/s]

Gaps (ex-reports):  17%|█▋        | 1251/7211 [05:40<20:38,  4.81it/s]

Gaps (ex-reports):  17%|█▋        | 1252/7211 [05:41<20:24,  4.87it/s]

Gaps (ex-reports):  17%|█▋        | 1253/7211 [05:41<19:56,  4.98it/s]

Gaps (ex-reports):  17%|█▋        | 1254/7211 [05:41<19:40,  5.04it/s]

Gaps (ex-reports):  17%|█▋        | 1255/7211 [05:41<20:13,  4.91it/s]

Gaps (ex-reports):  17%|█▋        | 1256/7211 [05:41<20:21,  4.88it/s]

Gaps (ex-reports):  17%|█▋        | 1257/7211 [05:42<21:08,  4.69it/s]

Gaps (ex-reports):  17%|█▋        | 1258/7211 [05:42<20:34,  4.82it/s]

Gaps (ex-reports):  17%|█▋        | 1259/7211 [05:42<20:35,  4.82it/s]

Gaps (ex-reports):  17%|█▋        | 1260/7211 [05:42<20:11,  4.91it/s]

Gaps (ex-reports):  17%|█▋        | 1261/7211 [05:42<20:12,  4.91it/s]

Gaps (ex-reports):  18%|█▊        | 1262/7211 [05:43<20:19,  4.88it/s]

Gaps (ex-reports):  18%|█▊        | 1263/7211 [05:43<20:05,  4.94it/s]

Gaps (ex-reports):  18%|█▊        | 1264/7211 [05:43<20:06,  4.93it/s]

Gaps (ex-reports):  18%|█▊        | 1265/7211 [05:43<19:50,  5.00it/s]

Gaps (ex-reports):  18%|█▊        | 1266/7211 [05:44<20:00,  4.95it/s]

Gaps (ex-reports):  18%|█▊        | 1267/7211 [05:44<20:00,  4.95it/s]

Gaps (ex-reports):  18%|█▊        | 1268/7211 [05:44<19:55,  4.97it/s]

Gaps (ex-reports):  18%|█▊        | 1269/7211 [05:44<19:35,  5.05it/s]

Gaps (ex-reports):  18%|█▊        | 1270/7211 [05:44<19:21,  5.12it/s]

Gaps (ex-reports):  18%|█▊        | 1271/7211 [05:44<19:18,  5.13it/s]

Gaps (ex-reports):  18%|█▊        | 1272/7211 [05:45<19:39,  5.04it/s]

Gaps (ex-reports):  18%|█▊        | 1273/7211 [05:45<19:39,  5.03it/s]

Gaps (ex-reports):  18%|█▊        | 1274/7211 [05:45<19:49,  4.99it/s]

Gaps (ex-reports):  18%|█▊        | 1275/7211 [05:45<20:01,  4.94it/s]

Gaps (ex-reports):  18%|█▊        | 1276/7211 [05:45<19:43,  5.01it/s]

Gaps (ex-reports):  18%|█▊        | 1277/7211 [05:46<20:03,  4.93it/s]

Gaps (ex-reports):  18%|█▊        | 1278/7211 [05:46<20:11,  4.90it/s]

Gaps (ex-reports):  18%|█▊        | 1279/7211 [05:46<20:07,  4.91it/s]

Gaps (ex-reports):  18%|█▊        | 1280/7211 [05:46<20:23,  4.85it/s]

Gaps (ex-reports):  18%|█▊        | 1281/7211 [05:47<30:27,  3.24it/s]

Gaps (ex-reports):  18%|█▊        | 1282/7211 [05:47<27:37,  3.58it/s]

Gaps (ex-reports):  18%|█▊        | 1283/7211 [05:47<25:19,  3.90it/s]

Gaps (ex-reports):  18%|█▊        | 1284/7211 [05:47<24:03,  4.11it/s]

Gaps (ex-reports):  18%|█▊        | 1285/7211 [05:48<22:38,  4.36it/s]

Gaps (ex-reports):  18%|█▊        | 1286/7211 [05:48<21:28,  4.60it/s]

Gaps (ex-reports):  18%|█▊        | 1287/7211 [05:48<21:05,  4.68it/s]

Gaps (ex-reports):  18%|█▊        | 1288/7211 [05:48<20:43,  4.76it/s]

Gaps (ex-reports):  18%|█▊        | 1289/7211 [05:49<21:08,  4.67it/s]

Gaps (ex-reports):  18%|█▊        | 1290/7211 [05:49<20:35,  4.79it/s]

Gaps (ex-reports):  18%|█▊        | 1291/7211 [05:49<20:33,  4.80it/s]

Gaps (ex-reports):  18%|█▊        | 1292/7211 [05:49<20:41,  4.77it/s]

Gaps (ex-reports):  18%|█▊        | 1293/7211 [05:49<22:08,  4.46it/s]

Gaps (ex-reports):  18%|█▊        | 1294/7211 [05:50<21:50,  4.52it/s]

Gaps (ex-reports):  18%|█▊        | 1295/7211 [05:50<21:43,  4.54it/s]

Gaps (ex-reports):  18%|█▊        | 1296/7211 [05:50<21:50,  4.51it/s]

Gaps (ex-reports):  18%|█▊        | 1297/7211 [05:50<21:10,  4.65it/s]

Gaps (ex-reports):  18%|█▊        | 1298/7211 [05:50<20:44,  4.75it/s]

Gaps (ex-reports):  18%|█▊        | 1299/7211 [05:51<20:36,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1300/7211 [05:51<20:07,  4.90it/s]

Gaps (ex-reports):  18%|█▊        | 1301/7211 [05:51<20:38,  4.77it/s]

Gaps (ex-reports):  18%|█▊        | 1302/7211 [05:51<20:04,  4.91it/s]

Gaps (ex-reports):  18%|█▊        | 1303/7211 [05:51<20:36,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1304/7211 [05:52<20:36,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1305/7211 [05:52<20:26,  4.82it/s]

Gaps (ex-reports):  18%|█▊        | 1306/7211 [05:52<27:47,  3.54it/s]

Gaps (ex-reports):  18%|█▊        | 1307/7211 [05:53<25:41,  3.83it/s]

Gaps (ex-reports):  18%|█▊        | 1308/7211 [05:53<23:51,  4.12it/s]

Gaps (ex-reports):  18%|█▊        | 1309/7211 [05:53<22:46,  4.32it/s]

Gaps (ex-reports):  18%|█▊        | 1310/7211 [05:53<21:46,  4.52it/s]

Gaps (ex-reports):  18%|█▊        | 1311/7211 [05:53<21:11,  4.64it/s]

Gaps (ex-reports):  18%|█▊        | 1312/7211 [05:54<21:12,  4.63it/s]

Gaps (ex-reports):  18%|█▊        | 1313/7211 [05:54<20:34,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1314/7211 [05:54<20:40,  4.75it/s]

Gaps (ex-reports):  18%|█▊        | 1315/7211 [05:54<20:38,  4.76it/s]

Gaps (ex-reports):  18%|█▊        | 1316/7211 [05:54<20:26,  4.81it/s]

Gaps (ex-reports):  18%|█▊        | 1317/7211 [05:55<20:28,  4.80it/s]

Gaps (ex-reports):  18%|█▊        | 1318/7211 [05:55<20:26,  4.80it/s]

Gaps (ex-reports):  18%|█▊        | 1319/7211 [05:55<20:31,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1320/7211 [05:55<20:15,  4.85it/s]

Gaps (ex-reports):  18%|█▊        | 1321/7211 [05:55<19:46,  4.96it/s]

Gaps (ex-reports):  18%|█▊        | 1322/7211 [05:56<19:42,  4.98it/s]

Gaps (ex-reports):  18%|█▊        | 1323/7211 [05:56<20:06,  4.88it/s]

Gaps (ex-reports):  18%|█▊        | 1324/7211 [05:56<21:01,  4.67it/s]

Gaps (ex-reports):  18%|█▊        | 1325/7211 [05:56<20:17,  4.83it/s]

Gaps (ex-reports):  18%|█▊        | 1326/7211 [05:56<20:31,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1327/7211 [05:57<21:47,  4.50it/s]

Gaps (ex-reports):  18%|█▊        | 1328/7211 [05:57<23:20,  4.20it/s]

Gaps (ex-reports):  18%|█▊        | 1329/7211 [05:57<24:06,  4.07it/s]

Gaps (ex-reports):  18%|█▊        | 1330/7211 [05:58<45:22,  2.16it/s]

Gaps (ex-reports):  18%|█▊        | 1331/7211 [05:58<37:31,  2.61it/s]

Gaps (ex-reports):  18%|█▊        | 1332/7211 [05:59<32:23,  3.03it/s]

Gaps (ex-reports):  18%|█▊        | 1333/7211 [05:59<28:53,  3.39it/s]

Gaps (ex-reports):  18%|█▊        | 1334/7211 [05:59<26:40,  3.67it/s]

Gaps (ex-reports):  19%|█▊        | 1335/7211 [05:59<25:05,  3.90it/s]

Gaps (ex-reports):  19%|█▊        | 1336/7211 [05:59<23:10,  4.23it/s]

Gaps (ex-reports):  19%|█▊        | 1337/7211 [06:00<22:04,  4.44it/s]

Gaps (ex-reports):  19%|█▊        | 1338/7211 [06:00<21:29,  4.55it/s]

Gaps (ex-reports):  19%|█▊        | 1339/7211 [06:00<20:42,  4.73it/s]

Gaps (ex-reports):  19%|█▊        | 1340/7211 [06:00<20:19,  4.82it/s]

Gaps (ex-reports):  19%|█▊        | 1341/7211 [06:00<20:21,  4.80it/s]

Gaps (ex-reports):  19%|█▊        | 1342/7211 [06:01<20:19,  4.81it/s]

Gaps (ex-reports):  19%|█▊        | 1343/7211 [06:01<20:35,  4.75it/s]

Gaps (ex-reports):  19%|█▊        | 1344/7211 [06:01<20:03,  4.88it/s]

Gaps (ex-reports):  19%|█▊        | 1345/7211 [06:01<20:33,  4.75it/s]

Gaps (ex-reports):  19%|█▊        | 1346/7211 [06:02<20:08,  4.85it/s]

Gaps (ex-reports):  19%|█▊        | 1347/7211 [06:02<22:51,  4.28it/s]

Gaps (ex-reports):  19%|█▊        | 1348/7211 [06:02<21:56,  4.45it/s]

Gaps (ex-reports):  19%|█▊        | 1349/7211 [06:02<21:32,  4.54it/s]

Gaps (ex-reports):  19%|█▊        | 1350/7211 [06:02<21:07,  4.62it/s]

Gaps (ex-reports):  19%|█▊        | 1351/7211 [06:03<20:37,  4.74it/s]

Gaps (ex-reports):  19%|█▊        | 1352/7211 [06:03<20:38,  4.73it/s]

Gaps (ex-reports):  19%|█▉        | 1353/7211 [06:03<20:20,  4.80it/s]

Gaps (ex-reports):  19%|█▉        | 1354/7211 [06:03<20:02,  4.87it/s]

Gaps (ex-reports):  19%|█▉        | 1355/7211 [06:03<19:45,  4.94it/s]

Gaps (ex-reports):  19%|█▉        | 1356/7211 [06:04<19:46,  4.94it/s]

Gaps (ex-reports):  19%|█▉        | 1357/7211 [06:04<19:53,  4.91it/s]

Gaps (ex-reports):  19%|█▉        | 1358/7211 [06:04<19:29,  5.00it/s]

Gaps (ex-reports):  19%|█▉        | 1359/7211 [06:04<19:08,  5.10it/s]

Gaps (ex-reports):  19%|█▉        | 1360/7211 [06:04<19:39,  4.96it/s]

Gaps (ex-reports):  19%|█▉        | 1361/7211 [06:05<19:28,  5.01it/s]

Gaps (ex-reports):  19%|█▉        | 1362/7211 [06:05<19:30,  5.00it/s]

Gaps (ex-reports):  19%|█▉        | 1363/7211 [06:05<19:34,  4.98it/s]

Gaps (ex-reports):  19%|█▉        | 1364/7211 [06:05<20:02,  4.86it/s]

Gaps (ex-reports):  19%|█▉        | 1365/7211 [06:05<20:00,  4.87it/s]

Gaps (ex-reports):  19%|█▉        | 1366/7211 [06:06<19:32,  4.99it/s]

Gaps (ex-reports):  19%|█▉        | 1367/7211 [06:06<19:34,  4.98it/s]

Gaps (ex-reports):  19%|█▉        | 1368/7211 [06:06<19:33,  4.98it/s]

Gaps (ex-reports):  19%|█▉        | 1369/7211 [06:06<19:31,  4.99it/s]

Gaps (ex-reports):  19%|█▉        | 1370/7211 [06:06<19:16,  5.05it/s]

Gaps (ex-reports):  19%|█▉        | 1371/7211 [06:07<19:17,  5.05it/s]

Gaps (ex-reports):  19%|█▉        | 1372/7211 [06:07<19:24,  5.01it/s]

Gaps (ex-reports):  19%|█▉        | 1373/7211 [06:07<19:19,  5.03it/s]

Gaps (ex-reports):  19%|█▉        | 1374/7211 [06:07<19:22,  5.02it/s]

Gaps (ex-reports):  19%|█▉        | 1375/7211 [06:07<19:20,  5.03it/s]

Gaps (ex-reports):  19%|█▉        | 1376/7211 [06:08<19:28,  4.99it/s]

Gaps (ex-reports):  19%|█▉        | 1377/7211 [06:08<19:18,  5.03it/s]

Gaps (ex-reports):  19%|█▉        | 1378/7211 [06:08<19:11,  5.07it/s]

Gaps (ex-reports):  19%|█▉        | 1379/7211 [06:08<19:22,  5.02it/s]

Gaps (ex-reports):  19%|█▉        | 1380/7211 [06:08<19:19,  5.03it/s]

Gaps (ex-reports):  19%|█▉        | 1381/7211 [06:09<19:37,  4.95it/s]

Gaps (ex-reports):  19%|█▉        | 1382/7211 [06:10<1:06:48,  1.45it/s]

Gaps (ex-reports):  19%|█▉        | 1383/7211 [06:11<52:50,  1.84it/s]

Gaps (ex-reports):  19%|█▉        | 1384/7211 [06:11<43:04,  2.25it/s]

Gaps (ex-reports):  19%|█▉        | 1385/7211 [06:11<36:14,  2.68it/s]

Gaps (ex-reports):  19%|█▉        | 1386/7211 [06:11<31:08,  3.12it/s]

Gaps (ex-reports):  19%|█▉        | 1387/7211 [06:11<27:34,  3.52it/s]

Gaps (ex-reports):  19%|█▉        | 1388/7211 [06:12<25:22,  3.82it/s]

Gaps (ex-reports):  19%|█▉        | 1389/7211 [06:12<23:47,  4.08it/s]

Gaps (ex-reports):  19%|█▉        | 1390/7211 [06:12<22:05,  4.39it/s]

Gaps (ex-reports):  19%|█▉        | 1391/7211 [06:12<21:10,  4.58it/s]

Gaps (ex-reports):  19%|█▉        | 1392/7211 [06:12<20:42,  4.68it/s]

Gaps (ex-reports):  19%|█▉        | 1393/7211 [06:13<20:45,  4.67it/s]

Gaps (ex-reports):  19%|█▉        | 1394/7211 [06:13<20:40,  4.69it/s]

Gaps (ex-reports):  19%|█▉        | 1395/7211 [06:13<20:10,  4.81it/s]

Gaps (ex-reports):  19%|█▉        | 1396/7211 [06:14<48:13,  2.01it/s]

Gaps (ex-reports):  19%|█▉        | 1397/7211 [06:15<39:47,  2.43it/s]

Gaps (ex-reports):  19%|█▉        | 1398/7211 [06:15<34:34,  2.80it/s]

Gaps (ex-reports):  19%|█▉        | 1399/7211 [06:15<30:22,  3.19it/s]

Gaps (ex-reports):  19%|█▉        | 1400/7211 [06:15<26:59,  3.59it/s]

Gaps (ex-reports):  19%|█▉        | 1401/7211 [06:15<25:01,  3.87it/s]

Gaps (ex-reports):  19%|█▉        | 1402/7211 [06:16<23:18,  4.15it/s]

Gaps (ex-reports):  19%|█▉        | 1403/7211 [06:16<22:24,  4.32it/s]

Gaps (ex-reports):  19%|█▉        | 1404/7211 [06:16<22:07,  4.38it/s]

Gaps (ex-reports):  19%|█▉        | 1405/7211 [06:16<21:40,  4.47it/s]

Gaps (ex-reports):  19%|█▉        | 1406/7211 [06:16<21:05,  4.59it/s]

Gaps (ex-reports):  20%|█▉        | 1407/7211 [06:17<20:19,  4.76it/s]

Gaps (ex-reports):  20%|█▉        | 1408/7211 [06:17<19:45,  4.90it/s]

Gaps (ex-reports):  20%|█▉        | 1409/7211 [06:17<19:15,  5.02it/s]

Gaps (ex-reports):  20%|█▉        | 1410/7211 [06:17<19:35,  4.94it/s]

Gaps (ex-reports):  20%|█▉        | 1411/7211 [06:17<19:39,  4.92it/s]

Gaps (ex-reports):  20%|█▉        | 1412/7211 [06:18<19:54,  4.86it/s]

Gaps (ex-reports):  20%|█▉        | 1413/7211 [06:18<19:56,  4.84it/s]

Gaps (ex-reports):  20%|█▉        | 1414/7211 [06:18<19:46,  4.88it/s]

Gaps (ex-reports):  20%|█▉        | 1415/7211 [06:18<19:24,  4.98it/s]

Gaps (ex-reports):  20%|█▉        | 1416/7211 [06:18<19:16,  5.01it/s]

Gaps (ex-reports):  20%|█▉        | 1417/7211 [06:19<19:33,  4.94it/s]

Gaps (ex-reports):  20%|█▉        | 1418/7211 [06:19<19:44,  4.89it/s]

Gaps (ex-reports):  20%|█▉        | 1419/7211 [06:19<19:28,  4.96it/s]

Gaps (ex-reports):  20%|█▉        | 1420/7211 [06:19<19:14,  5.01it/s]

Gaps (ex-reports):  20%|█▉        | 1421/7211 [06:19<19:15,  5.01it/s]

Gaps (ex-reports):  20%|█▉        | 1422/7211 [06:20<19:33,  4.93it/s]

Gaps (ex-reports):  20%|█▉        | 1423/7211 [06:20<19:04,  5.06it/s]

Gaps (ex-reports):  20%|█▉        | 1424/7211 [06:20<18:51,  5.12it/s]

Gaps (ex-reports):  20%|█▉        | 1425/7211 [06:20<18:53,  5.10it/s]

Gaps (ex-reports):  20%|█▉        | 1426/7211 [06:20<19:06,  5.05it/s]

Gaps (ex-reports):  20%|█▉        | 1427/7211 [06:21<19:18,  4.99it/s]

Gaps (ex-reports):  20%|█▉        | 1428/7211 [06:21<20:09,  4.78it/s]

Gaps (ex-reports):  20%|█▉        | 1429/7211 [06:21<20:11,  4.77it/s]

Gaps (ex-reports):  20%|█▉        | 1430/7211 [06:21<20:08,  4.78it/s]

Gaps (ex-reports):  20%|█▉        | 1431/7211 [06:21<20:16,  4.75it/s]

Gaps (ex-reports):  20%|█▉        | 1432/7211 [06:22<19:51,  4.85it/s]

Gaps (ex-reports):  20%|█▉        | 1433/7211 [06:22<19:35,  4.92it/s]

Gaps (ex-reports):  20%|█▉        | 1434/7211 [06:22<20:58,  4.59it/s]

Gaps (ex-reports):  20%|█▉        | 1435/7211 [06:22<20:13,  4.76it/s]

Gaps (ex-reports):  20%|█▉        | 1436/7211 [06:22<20:00,  4.81it/s]

Gaps (ex-reports):  20%|█▉        | 1437/7211 [06:23<19:42,  4.88it/s]

Gaps (ex-reports):  20%|█▉        | 1438/7211 [06:23<19:21,  4.97it/s]

Gaps (ex-reports):  20%|█▉        | 1439/7211 [06:23<19:27,  4.94it/s]

Gaps (ex-reports):  20%|█▉        | 1440/7211 [06:23<19:14,  5.00it/s]

Gaps (ex-reports):  20%|█▉        | 1441/7211 [06:23<19:08,  5.03it/s]

Gaps (ex-reports):  20%|█▉        | 1442/7211 [06:24<19:40,  4.89it/s]

Gaps (ex-reports):  20%|██        | 1443/7211 [06:24<19:41,  4.88it/s]

Gaps (ex-reports):  20%|██        | 1444/7211 [06:24<20:04,  4.79it/s]

Gaps (ex-reports):  20%|██        | 1445/7211 [06:24<20:01,  4.80it/s]

Gaps (ex-reports):  20%|██        | 1446/7211 [06:25<20:15,  4.74it/s]

Gaps (ex-reports):  20%|██        | 1447/7211 [06:25<20:02,  4.79it/s]

Gaps (ex-reports):  20%|██        | 1448/7211 [06:25<20:08,  4.77it/s]

Gaps (ex-reports):  20%|██        | 1449/7211 [06:25<19:46,  4.86it/s]

Gaps (ex-reports):  20%|██        | 1450/7211 [06:25<19:49,  4.84it/s]

Gaps (ex-reports):  20%|██        | 1451/7211 [06:26<19:44,  4.86it/s]

Gaps (ex-reports):  20%|██        | 1452/7211 [06:26<19:52,  4.83it/s]

Gaps (ex-reports):  20%|██        | 1453/7211 [06:26<19:34,  4.90it/s]

Gaps (ex-reports):  20%|██        | 1454/7211 [06:26<19:49,  4.84it/s]

Gaps (ex-reports):  20%|██        | 1455/7211 [06:26<19:56,  4.81it/s]

Gaps (ex-reports):  20%|██        | 1456/7211 [06:27<19:56,  4.81it/s]

Gaps (ex-reports):  20%|██        | 1457/7211 [06:27<19:42,  4.87it/s]

Gaps (ex-reports):  20%|██        | 1458/7211 [06:27<19:30,  4.92it/s]

Gaps (ex-reports):  20%|██        | 1459/7211 [06:27<19:40,  4.87it/s]

Gaps (ex-reports):  20%|██        | 1460/7211 [06:27<19:24,  4.94it/s]

Gaps (ex-reports):  20%|██        | 1461/7211 [06:28<19:34,  4.90it/s]

Gaps (ex-reports):  20%|██        | 1462/7211 [06:28<19:24,  4.94it/s]

Gaps (ex-reports):  20%|██        | 1463/7211 [06:28<19:10,  4.99it/s]

Gaps (ex-reports):  20%|██        | 1464/7211 [06:28<19:29,  4.91it/s]

Gaps (ex-reports):  20%|██        | 1465/7211 [06:28<19:48,  4.84it/s]

Gaps (ex-reports):  20%|██        | 1466/7211 [06:29<19:20,  4.95it/s]

Gaps (ex-reports):  20%|██        | 1467/7211 [06:29<20:34,  4.65it/s]

Gaps (ex-reports):  20%|██        | 1468/7211 [06:29<20:26,  4.68it/s]

Gaps (ex-reports):  20%|██        | 1469/7211 [06:29<19:59,  4.79it/s]

Gaps (ex-reports):  20%|██        | 1470/7211 [06:29<19:29,  4.91it/s]

Gaps (ex-reports):  20%|██        | 1471/7211 [06:30<19:33,  4.89it/s]

Gaps (ex-reports):  20%|██        | 1472/7211 [06:30<19:46,  4.84it/s]

Gaps (ex-reports):  20%|██        | 1473/7211 [06:30<19:17,  4.96it/s]

Gaps (ex-reports):  20%|██        | 1474/7211 [06:30<19:07,  5.00it/s]

Gaps (ex-reports):  20%|██        | 1475/7211 [06:30<19:19,  4.95it/s]

Gaps (ex-reports):  20%|██        | 1476/7211 [06:31<19:46,  4.83it/s]

Gaps (ex-reports):  20%|██        | 1477/7211 [06:31<19:31,  4.89it/s]

Gaps (ex-reports):  20%|██        | 1478/7211 [06:31<19:31,  4.90it/s]

Gaps (ex-reports):  21%|██        | 1479/7211 [06:31<19:20,  4.94it/s]

Gaps (ex-reports):  21%|██        | 1480/7211 [06:32<19:20,  4.94it/s]

Gaps (ex-reports):  21%|██        | 1481/7211 [06:32<19:20,  4.94it/s]

Gaps (ex-reports):  21%|██        | 1482/7211 [06:32<19:11,  4.98it/s]

Gaps (ex-reports):  21%|██        | 1483/7211 [06:32<19:08,  4.99it/s]

Gaps (ex-reports):  21%|██        | 1484/7211 [06:32<19:15,  4.96it/s]

Gaps (ex-reports):  21%|██        | 1485/7211 [06:33<19:08,  4.98it/s]

Gaps (ex-reports):  21%|██        | 1486/7211 [06:33<19:16,  4.95it/s]

Gaps (ex-reports):  21%|██        | 1487/7211 [06:33<19:31,  4.89it/s]

Gaps (ex-reports):  21%|██        | 1488/7211 [06:33<19:26,  4.91it/s]

Gaps (ex-reports):  21%|██        | 1489/7211 [06:33<19:03,  5.00it/s]

Gaps (ex-reports):  21%|██        | 1490/7211 [06:34<18:45,  5.08it/s]

Gaps (ex-reports):  21%|██        | 1491/7211 [06:34<18:46,  5.08it/s]

Gaps (ex-reports):  21%|██        | 1492/7211 [06:34<18:48,  5.07it/s]

Gaps (ex-reports):  21%|██        | 1493/7211 [06:34<19:15,  4.95it/s]

Gaps (ex-reports):  21%|██        | 1494/7211 [06:34<19:10,  4.97it/s]

Gaps (ex-reports):  21%|██        | 1495/7211 [06:35<19:36,  4.86it/s]

Gaps (ex-reports):  21%|██        | 1496/7211 [06:35<19:12,  4.96it/s]

Gaps (ex-reports):  21%|██        | 1497/7211 [06:35<19:48,  4.81it/s]

Gaps (ex-reports):  21%|██        | 1498/7211 [06:35<20:17,  4.69it/s]

Gaps (ex-reports):  21%|██        | 1499/7211 [06:35<20:12,  4.71it/s]

Gaps (ex-reports):  21%|██        | 1500/7211 [06:36<20:03,  4.74it/s]

Gaps (ex-reports):  21%|██        | 1501/7211 [06:36<20:06,  4.73it/s]

Gaps (ex-reports):  21%|██        | 1502/7211 [06:36<20:02,  4.75it/s]

Gaps (ex-reports):  21%|██        | 1503/7211 [06:36<20:17,  4.69it/s]

Gaps (ex-reports):  21%|██        | 1504/7211 [06:36<19:42,  4.83it/s]

Gaps (ex-reports):  21%|██        | 1505/7211 [06:37<19:38,  4.84it/s]

Gaps (ex-reports):  21%|██        | 1506/7211 [06:37<19:37,  4.85it/s]

Gaps (ex-reports):  21%|██        | 1507/7211 [06:37<19:12,  4.95it/s]

Gaps (ex-reports):  21%|██        | 1508/7211 [06:37<19:19,  4.92it/s]

Gaps (ex-reports):  21%|██        | 1509/7211 [06:37<19:16,  4.93it/s]

Gaps (ex-reports):  21%|██        | 1510/7211 [06:38<19:11,  4.95it/s]

Gaps (ex-reports):  21%|██        | 1511/7211 [06:38<19:25,  4.89it/s]

Gaps (ex-reports):  21%|██        | 1512/7211 [06:38<19:03,  4.98it/s]

Gaps (ex-reports):  21%|██        | 1513/7211 [06:38<19:32,  4.86it/s]

Gaps (ex-reports):  21%|██        | 1514/7211 [06:38<19:20,  4.91it/s]

Gaps (ex-reports):  21%|██        | 1515/7211 [06:39<19:33,  4.85it/s]

Gaps (ex-reports):  21%|██        | 1516/7211 [06:39<19:38,  4.83it/s]

Gaps (ex-reports):  21%|██        | 1517/7211 [06:39<19:52,  4.78it/s]

Gaps (ex-reports):  21%|██        | 1518/7211 [06:39<19:35,  4.84it/s]

Gaps (ex-reports):  21%|██        | 1519/7211 [06:39<19:10,  4.95it/s]

Gaps (ex-reports):  21%|██        | 1520/7211 [06:40<19:11,  4.94it/s]

Gaps (ex-reports):  21%|██        | 1521/7211 [06:40<19:04,  4.97it/s]

Gaps (ex-reports):  21%|██        | 1522/7211 [06:40<19:17,  4.91it/s]

Gaps (ex-reports):  21%|██        | 1523/7211 [06:40<19:09,  4.95it/s]

Gaps (ex-reports):  21%|██        | 1524/7211 [06:41<19:29,  4.86it/s]

Gaps (ex-reports):  21%|██        | 1525/7211 [06:41<19:29,  4.86it/s]

Gaps (ex-reports):  21%|██        | 1526/7211 [06:41<19:48,  4.78it/s]

Gaps (ex-reports):  21%|██        | 1527/7211 [06:41<19:32,  4.85it/s]

Gaps (ex-reports):  21%|██        | 1528/7211 [06:41<19:26,  4.87it/s]

Gaps (ex-reports):  21%|██        | 1529/7211 [06:42<19:36,  4.83it/s]

Gaps (ex-reports):  21%|██        | 1530/7211 [06:42<19:03,  4.97it/s]

Gaps (ex-reports):  21%|██        | 1531/7211 [06:42<19:16,  4.91it/s]

Gaps (ex-reports):  21%|██        | 1532/7211 [06:42<19:12,  4.93it/s]

Gaps (ex-reports):  21%|██▏       | 1533/7211 [06:42<19:20,  4.89it/s]

Gaps (ex-reports):  21%|██▏       | 1534/7211 [06:43<19:27,  4.86it/s]

Gaps (ex-reports):  21%|██▏       | 1535/7211 [06:43<19:24,  4.87it/s]

Gaps (ex-reports):  21%|██▏       | 1536/7211 [06:43<19:32,  4.84it/s]

Gaps (ex-reports):  21%|██▏       | 1537/7211 [06:43<19:24,  4.87it/s]

Gaps (ex-reports):  21%|██▏       | 1538/7211 [06:43<19:09,  4.94it/s]

Gaps (ex-reports):  21%|██▏       | 1539/7211 [06:44<18:55,  4.99it/s]

Gaps (ex-reports):  21%|██▏       | 1540/7211 [06:44<19:21,  4.88it/s]

Gaps (ex-reports):  21%|██▏       | 1541/7211 [06:44<19:02,  4.96it/s]

Gaps (ex-reports):  21%|██▏       | 1542/7211 [06:44<19:01,  4.97it/s]

Gaps (ex-reports):  21%|██▏       | 1543/7211 [06:44<18:49,  5.02it/s]

Gaps (ex-reports):  21%|██▏       | 1544/7211 [06:45<18:54,  5.00it/s]

Gaps (ex-reports):  21%|██▏       | 1545/7211 [06:45<18:59,  4.97it/s]

Gaps (ex-reports):  21%|██▏       | 1546/7211 [06:45<18:40,  5.05it/s]

Gaps (ex-reports):  21%|██▏       | 1547/7211 [06:45<18:49,  5.01it/s]

Gaps (ex-reports):  21%|██▏       | 1548/7211 [06:45<19:04,  4.95it/s]

Gaps (ex-reports):  21%|██▏       | 1549/7211 [06:46<19:07,  4.94it/s]

Gaps (ex-reports):  21%|██▏       | 1550/7211 [06:46<19:15,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1551/7211 [06:46<19:18,  4.89it/s]

Gaps (ex-reports):  22%|██▏       | 1552/7211 [06:46<19:02,  4.95it/s]

Gaps (ex-reports):  22%|██▏       | 1553/7211 [06:46<19:03,  4.95it/s]

Gaps (ex-reports):  22%|██▏       | 1554/7211 [06:47<19:20,  4.87it/s]

Gaps (ex-reports):  22%|██▏       | 1555/7211 [06:47<19:31,  4.83it/s]

Gaps (ex-reports):  22%|██▏       | 1556/7211 [06:47<19:30,  4.83it/s]

Gaps (ex-reports):  22%|██▏       | 1557/7211 [06:47<19:21,  4.87it/s]

Gaps (ex-reports):  22%|██▏       | 1558/7211 [06:47<18:54,  4.98it/s]

Gaps (ex-reports):  22%|██▏       | 1559/7211 [06:48<19:09,  4.92it/s]

Gaps (ex-reports):  22%|██▏       | 1560/7211 [06:48<19:13,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1561/7211 [06:48<19:26,  4.84it/s]

Gaps (ex-reports):  22%|██▏       | 1562/7211 [06:48<19:34,  4.81it/s]

Gaps (ex-reports):  22%|██▏       | 1563/7211 [06:48<19:23,  4.85it/s]

Gaps (ex-reports):  22%|██▏       | 1564/7211 [06:49<18:56,  4.97it/s]

Gaps (ex-reports):  22%|██▏       | 1565/7211 [06:49<18:54,  4.98it/s]

Gaps (ex-reports):  22%|██▏       | 1566/7211 [06:49<19:23,  4.85it/s]

Gaps (ex-reports):  22%|██▏       | 1567/7211 [06:49<18:54,  4.98it/s]

Gaps (ex-reports):  22%|██▏       | 1568/7211 [06:49<18:58,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1569/7211 [06:50<19:04,  4.93it/s]

Gaps (ex-reports):  22%|██▏       | 1570/7211 [06:50<18:57,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1571/7211 [06:50<18:46,  5.00it/s]

Gaps (ex-reports):  22%|██▏       | 1572/7211 [06:50<18:37,  5.05it/s]

Gaps (ex-reports):  22%|██▏       | 1573/7211 [06:50<18:49,  4.99it/s]

Gaps (ex-reports):  22%|██▏       | 1574/7211 [06:51<18:35,  5.05it/s]

Gaps (ex-reports):  22%|██▏       | 1575/7211 [06:51<18:48,  4.99it/s]

Gaps (ex-reports):  22%|██▏       | 1576/7211 [06:51<19:10,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1577/7211 [06:51<19:07,  4.91it/s]

Gaps (ex-reports):  22%|██▏       | 1578/7211 [06:51<19:13,  4.88it/s]

Gaps (ex-reports):  22%|██▏       | 1579/7211 [06:52<18:59,  4.94it/s]

Gaps (ex-reports):  22%|██▏       | 1580/7211 [06:52<19:11,  4.89it/s]

Gaps (ex-reports):  22%|██▏       | 1581/7211 [06:52<19:10,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1582/7211 [06:52<19:05,  4.91it/s]

Gaps (ex-reports):  22%|██▏       | 1583/7211 [06:52<19:13,  4.88it/s]

Gaps (ex-reports):  22%|██▏       | 1584/7211 [06:53<19:08,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1585/7211 [06:53<18:43,  5.01it/s]

Gaps (ex-reports):  22%|██▏       | 1586/7211 [06:53<18:37,  5.03it/s]

Gaps (ex-reports):  22%|██▏       | 1587/7211 [06:53<18:54,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1588/7211 [06:53<18:53,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1589/7211 [06:54<18:50,  4.97it/s]

Gaps (ex-reports):  22%|██▏       | 1590/7211 [06:54<18:49,  4.98it/s]

Gaps (ex-reports):  22%|██▏       | 1591/7211 [06:54<19:03,  4.91it/s]

Gaps (ex-reports):  22%|██▏       | 1592/7211 [06:54<18:47,  4.98it/s]

Gaps (ex-reports):  22%|██▏       | 1593/7211 [06:54<18:21,  5.10it/s]

Gaps (ex-reports):  22%|██▏       | 1594/7211 [06:55<18:47,  4.98it/s]

Gaps (ex-reports):  22%|██▏       | 1595/7211 [06:55<18:30,  5.06it/s]

Gaps (ex-reports):  22%|██▏       | 1596/7211 [06:55<18:49,  4.97it/s]

Gaps (ex-reports):  22%|██▏       | 1597/7211 [06:55<18:36,  5.03it/s]

Gaps (ex-reports):  22%|██▏       | 1598/7211 [06:55<18:21,  5.10it/s]

Gaps (ex-reports):  22%|██▏       | 1599/7211 [07:01<2:57:01,  1.89s/it]

Gaps (ex-reports):  22%|██▏       | 1600/7211 [07:02<2:09:48,  1.39s/it]

Gaps (ex-reports):  22%|██▏       | 1601/7211 [07:02<1:38:49,  1.06s/it]

Gaps (ex-reports):  22%|██▏       | 1602/7211 [07:02<1:16:19,  1.22it/s]

Gaps (ex-reports):  22%|██▏       | 1603/7211 [07:02<1:01:39,  1.52it/s]

Gaps (ex-reports):  22%|██▏       | 1604/7211 [07:03<50:19,  1.86it/s]

Gaps (ex-reports):  22%|██▏       | 1605/7211 [07:03<41:12,  2.27it/s]

Gaps (ex-reports):  22%|██▏       | 1606/7211 [07:03<34:41,  2.69it/s]

Gaps (ex-reports):  22%|██▏       | 1607/7211 [07:03<30:14,  3.09it/s]

Gaps (ex-reports):  22%|██▏       | 1608/7211 [07:03<26:43,  3.49it/s]

Gaps (ex-reports):  22%|██▏       | 1609/7211 [07:04<24:06,  3.87it/s]

Gaps (ex-reports):  22%|██▏       | 1610/7211 [07:04<22:29,  4.15it/s]

Gaps (ex-reports):  22%|██▏       | 1611/7211 [07:04<22:10,  4.21it/s]

Gaps (ex-reports):  22%|██▏       | 1612/7211 [07:04<21:30,  4.34it/s]

Gaps (ex-reports):  22%|██▏       | 1613/7211 [07:05<20:48,  4.48it/s]

Gaps (ex-reports):  22%|██▏       | 1614/7211 [07:05<20:34,  4.53it/s]

Gaps (ex-reports):  22%|██▏       | 1615/7211 [07:05<20:18,  4.59it/s]

Gaps (ex-reports):  22%|██▏       | 1616/7211 [07:05<19:47,  4.71it/s]

Gaps (ex-reports):  22%|██▏       | 1617/7211 [07:05<19:20,  4.82it/s]

Gaps (ex-reports):  22%|██▏       | 1618/7211 [07:06<18:24,  5.06it/s]

Gaps (ex-reports):  22%|██▏       | 1619/7211 [07:06<18:34,  5.02it/s]

Gaps (ex-reports):  22%|██▏       | 1620/7211 [07:06<18:37,  5.00it/s]

Gaps (ex-reports):  22%|██▏       | 1621/7211 [07:06<18:52,  4.93it/s]

Gaps (ex-reports):  22%|██▏       | 1622/7211 [07:06<20:13,  4.60it/s]

Gaps (ex-reports):  23%|██▎       | 1623/7211 [07:07<19:35,  4.75it/s]

Gaps (ex-reports):  23%|██▎       | 1624/7211 [07:07<19:16,  4.83it/s]

Gaps (ex-reports):  23%|██▎       | 1625/7211 [07:07<19:12,  4.84it/s]

Gaps (ex-reports):  23%|██▎       | 1626/7211 [07:07<19:19,  4.82it/s]

Gaps (ex-reports):  23%|██▎       | 1627/7211 [07:07<19:19,  4.81it/s]

Gaps (ex-reports):  23%|██▎       | 1628/7211 [07:08<19:12,  4.84it/s]

Gaps (ex-reports):  23%|██▎       | 1629/7211 [07:08<18:45,  4.96it/s]

Gaps (ex-reports):  23%|██▎       | 1630/7211 [07:08<18:52,  4.93it/s]

Gaps (ex-reports):  23%|██▎       | 1631/7211 [07:08<19:12,  4.84it/s]

Gaps (ex-reports):  23%|██▎       | 1632/7211 [07:08<19:14,  4.83it/s]

Gaps (ex-reports):  23%|██▎       | 1633/7211 [07:09<19:14,  4.83it/s]

Gaps (ex-reports):  23%|██▎       | 1634/7211 [07:09<19:35,  4.75it/s]

Gaps (ex-reports):  23%|██▎       | 1635/7211 [07:09<19:10,  4.85it/s]

Gaps (ex-reports):  23%|██▎       | 1636/7211 [07:09<19:09,  4.85it/s]

Gaps (ex-reports):  23%|██▎       | 1637/7211 [07:09<18:48,  4.94it/s]

Gaps (ex-reports):  23%|██▎       | 1638/7211 [07:10<18:42,  4.97it/s]

Gaps (ex-reports):  23%|██▎       | 1639/7211 [07:10<19:08,  4.85it/s]

Gaps (ex-reports):  23%|██▎       | 1640/7211 [07:10<19:17,  4.81it/s]

Gaps (ex-reports):  23%|██▎       | 1641/7211 [07:10<19:23,  4.79it/s]

Gaps (ex-reports):  23%|██▎       | 1642/7211 [07:10<19:23,  4.79it/s]

Gaps (ex-reports):  23%|██▎       | 1643/7211 [07:11<19:05,  4.86it/s]

Gaps (ex-reports):  23%|██▎       | 1644/7211 [07:11<19:12,  4.83it/s]

Gaps (ex-reports):  23%|██▎       | 1645/7211 [07:11<19:07,  4.85it/s]

Gaps (ex-reports):  23%|██▎       | 1646/7211 [07:11<18:44,  4.95it/s]

Gaps (ex-reports):  23%|██▎       | 1647/7211 [07:11<18:51,  4.92it/s]

Gaps (ex-reports):  23%|██▎       | 1648/7211 [07:12<18:56,  4.89it/s]

Gaps (ex-reports):  23%|██▎       | 1649/7211 [07:12<18:48,  4.93it/s]

Gaps (ex-reports):  23%|██▎       | 1650/7211 [07:12<18:52,  4.91it/s]

Gaps (ex-reports):  23%|██▎       | 1651/7211 [07:12<18:45,  4.94it/s]

Gaps (ex-reports):  23%|██▎       | 1652/7211 [07:13<18:56,  4.89it/s]

Gaps (ex-reports):  23%|██▎       | 1653/7211 [07:13<18:51,  4.91it/s]

Gaps (ex-reports):  23%|██▎       | 1654/7211 [07:13<18:47,  4.93it/s]

Gaps (ex-reports):  23%|██▎       | 1655/7211 [07:13<19:09,  4.83it/s]

Gaps (ex-reports):  23%|██▎       | 1656/7211 [07:13<18:38,  4.97it/s]

Gaps (ex-reports):  23%|██▎       | 1657/7211 [07:14<19:19,  4.79it/s]

Gaps (ex-reports):  23%|██▎       | 1658/7211 [07:14<18:48,  4.92it/s]

Gaps (ex-reports):  23%|██▎       | 1659/7211 [07:14<19:23,  4.77it/s]

Gaps (ex-reports):  23%|██▎       | 1660/7211 [07:14<19:03,  4.86it/s]

Gaps (ex-reports):  23%|██▎       | 1661/7211 [07:14<19:19,  4.79it/s]

Gaps (ex-reports):  23%|██▎       | 1662/7211 [07:15<19:04,  4.85it/s]

Gaps (ex-reports):  23%|██▎       | 1663/7211 [07:15<18:59,  4.87it/s]

Gaps (ex-reports):  23%|██▎       | 1664/7211 [07:15<18:45,  4.93it/s]

Gaps (ex-reports):  23%|██▎       | 1665/7211 [07:15<18:49,  4.91it/s]

Gaps (ex-reports):  23%|██▎       | 1666/7211 [07:15<18:43,  4.93it/s]

Gaps (ex-reports):  23%|██▎       | 1667/7211 [07:16<18:57,  4.87it/s]

Gaps (ex-reports):  23%|██▎       | 1668/7211 [07:16<18:39,  4.95it/s]

Gaps (ex-reports):  23%|██▎       | 1669/7211 [07:16<18:56,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1670/7211 [07:16<19:08,  4.83it/s]

Gaps (ex-reports):  23%|██▎       | 1671/7211 [07:16<18:54,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1672/7211 [07:17<19:10,  4.81it/s]

Gaps (ex-reports):  23%|██▎       | 1673/7211 [07:17<19:14,  4.80it/s]

Gaps (ex-reports):  23%|██▎       | 1674/7211 [07:17<19:26,  4.75it/s]

Gaps (ex-reports):  23%|██▎       | 1675/7211 [07:17<19:13,  4.80it/s]

Gaps (ex-reports):  23%|██▎       | 1676/7211 [07:17<19:33,  4.71it/s]

Gaps (ex-reports):  23%|██▎       | 1677/7211 [07:18<19:48,  4.66it/s]

Gaps (ex-reports):  23%|██▎       | 1678/7211 [07:18<19:22,  4.76it/s]

Gaps (ex-reports):  23%|██▎       | 1679/7211 [07:18<19:17,  4.78it/s]

Gaps (ex-reports):  23%|██▎       | 1680/7211 [07:18<19:02,  4.84it/s]

Gaps (ex-reports):  23%|██▎       | 1681/7211 [07:18<18:34,  4.96it/s]

Gaps (ex-reports):  23%|██▎       | 1682/7211 [07:19<18:45,  4.91it/s]

Gaps (ex-reports):  23%|██▎       | 1683/7211 [07:19<18:33,  4.96it/s]

Gaps (ex-reports):  23%|██▎       | 1684/7211 [07:19<18:36,  4.95it/s]

Gaps (ex-reports):  23%|██▎       | 1685/7211 [07:19<18:26,  5.00it/s]

Gaps (ex-reports):  23%|██▎       | 1686/7211 [07:19<18:26,  4.99it/s]

Gaps (ex-reports):  23%|██▎       | 1687/7211 [07:20<19:19,  4.76it/s]

Gaps (ex-reports):  23%|██▎       | 1688/7211 [07:20<19:09,  4.80it/s]

Gaps (ex-reports):  23%|██▎       | 1689/7211 [07:20<18:42,  4.92it/s]

Gaps (ex-reports):  23%|██▎       | 1690/7211 [07:20<18:23,  5.00it/s]

Gaps (ex-reports):  23%|██▎       | 1691/7211 [07:21<18:42,  4.92it/s]

Gaps (ex-reports):  23%|██▎       | 1692/7211 [07:21<18:51,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1693/7211 [07:21<18:42,  4.91it/s]

Gaps (ex-reports):  23%|██▎       | 1694/7211 [07:21<18:48,  4.89it/s]

Gaps (ex-reports):  24%|██▎       | 1695/7211 [07:21<18:44,  4.91it/s]

Gaps (ex-reports):  24%|██▎       | 1696/7211 [07:22<18:58,  4.84it/s]

Gaps (ex-reports):  24%|██▎       | 1697/7211 [07:22<18:46,  4.90it/s]

Gaps (ex-reports):  24%|██▎       | 1698/7211 [07:22<18:59,  4.84it/s]

Gaps (ex-reports):  24%|██▎       | 1699/7211 [07:22<18:56,  4.85it/s]

Gaps (ex-reports):  24%|██▎       | 1700/7211 [07:22<19:35,  4.69it/s]

Gaps (ex-reports):  24%|██▎       | 1701/7211 [07:23<19:21,  4.75it/s]

Gaps (ex-reports):  24%|██▎       | 1702/7211 [07:23<19:26,  4.72it/s]

Gaps (ex-reports):  24%|██▎       | 1703/7211 [07:23<19:09,  4.79it/s]

Gaps (ex-reports):  24%|██▎       | 1704/7211 [07:23<18:41,  4.91it/s]

Gaps (ex-reports):  24%|██▎       | 1705/7211 [07:23<18:51,  4.87it/s]

Gaps (ex-reports):  24%|██▎       | 1706/7211 [07:24<18:56,  4.84it/s]

Gaps (ex-reports):  24%|██▎       | 1707/7211 [07:24<18:49,  4.87it/s]

Gaps (ex-reports):  24%|██▎       | 1708/7211 [07:24<18:50,  4.87it/s]

Gaps (ex-reports):  24%|██▎       | 1709/7211 [07:24<18:43,  4.90it/s]

Gaps (ex-reports):  24%|██▎       | 1710/7211 [07:24<18:41,  4.90it/s]

Gaps (ex-reports):  24%|██▎       | 1711/7211 [07:25<18:25,  4.98it/s]

Gaps (ex-reports):  24%|██▎       | 1712/7211 [07:25<18:47,  4.88it/s]

Gaps (ex-reports):  24%|██▍       | 1713/7211 [07:25<18:53,  4.85it/s]

Gaps (ex-reports):  24%|██▍       | 1714/7211 [07:25<18:43,  4.89it/s]

Gaps (ex-reports):  24%|██▍       | 1715/7211 [07:25<18:55,  4.84it/s]

Gaps (ex-reports):  24%|██▍       | 1716/7211 [07:26<19:06,  4.79it/s]

Gaps (ex-reports):  24%|██▍       | 1717/7211 [07:26<18:57,  4.83it/s]

Gaps (ex-reports):  24%|██▍       | 1718/7211 [07:26<18:46,  4.88it/s]

Gaps (ex-reports):  24%|██▍       | 1719/7211 [07:26<18:50,  4.86it/s]

Gaps (ex-reports):  24%|██▍       | 1720/7211 [07:27<19:00,  4.82it/s]

Gaps (ex-reports):  24%|██▍       | 1721/7211 [07:27<18:47,  4.87it/s]

Gaps (ex-reports):  24%|██▍       | 1722/7211 [07:27<19:08,  4.78it/s]

Gaps (ex-reports):  24%|██▍       | 1723/7211 [07:27<18:42,  4.89it/s]

Gaps (ex-reports):  24%|██▍       | 1724/7211 [07:27<18:22,  4.98it/s]

Gaps (ex-reports):  24%|██▍       | 1725/7211 [07:28<18:43,  4.88it/s]

Gaps (ex-reports):  24%|██▍       | 1726/7211 [07:28<18:37,  4.91it/s]

Gaps (ex-reports):  24%|██▍       | 1727/7211 [07:28<18:31,  4.93it/s]

Gaps (ex-reports):  24%|██▍       | 1728/7211 [07:28<18:35,  4.92it/s]

Gaps (ex-reports):  24%|██▍       | 1729/7211 [07:28<18:45,  4.87it/s]

Gaps (ex-reports):  24%|██▍       | 1730/7211 [07:29<18:47,  4.86it/s]

Gaps (ex-reports):  24%|██▍       | 1731/7211 [07:29<18:53,  4.83it/s]

Gaps (ex-reports):  24%|██▍       | 1732/7211 [07:29<18:54,  4.83it/s]

Gaps (ex-reports):  24%|██▍       | 1733/7211 [07:29<18:54,  4.83it/s]

Gaps (ex-reports):  24%|██▍       | 1734/7211 [07:29<18:23,  4.96it/s]

Gaps (ex-reports):  24%|██▍       | 1735/7211 [07:30<18:45,  4.86it/s]

Gaps (ex-reports):  24%|██▍       | 1736/7211 [07:30<18:46,  4.86it/s]

Gaps (ex-reports):  24%|██▍       | 1737/7211 [07:30<18:27,  4.94it/s]

Gaps (ex-reports):  24%|██▍       | 1738/7211 [07:30<18:54,  4.82it/s]

Gaps (ex-reports):  24%|██▍       | 1739/7211 [07:30<18:44,  4.87it/s]

Gaps (ex-reports):  24%|██▍       | 1740/7211 [07:31<19:08,  4.76it/s]

Gaps (ex-reports):  24%|██▍       | 1741/7211 [07:31<19:09,  4.76it/s]

Gaps (ex-reports):  24%|██▍       | 1742/7211 [07:31<18:50,  4.84it/s]

Gaps (ex-reports):  24%|██▍       | 1743/7211 [07:31<18:31,  4.92it/s]

Gaps (ex-reports):  24%|██▍       | 1744/7211 [07:31<18:27,  4.94it/s]

Gaps (ex-reports):  24%|██▍       | 1745/7211 [07:32<18:44,  4.86it/s]

Gaps (ex-reports):  24%|██▍       | 1746/7211 [07:32<18:57,  4.80it/s]

Gaps (ex-reports):  24%|██▍       | 1747/7211 [07:32<19:29,  4.67it/s]

Gaps (ex-reports):  24%|██▍       | 1748/7211 [07:32<19:20,  4.71it/s]

Gaps (ex-reports):  24%|██▍       | 1749/7211 [07:32<18:48,  4.84it/s]

Gaps (ex-reports):  24%|██▍       | 1750/7211 [07:33<18:56,  4.81it/s]

Gaps (ex-reports):  24%|██▍       | 1751/7211 [07:33<18:58,  4.80it/s]

Gaps (ex-reports):  24%|██▍       | 1752/7211 [07:33<18:46,  4.84it/s]

Gaps (ex-reports):  24%|██▍       | 1753/7211 [07:33<18:55,  4.81it/s]

Gaps (ex-reports):  24%|██▍       | 1754/7211 [07:34<19:12,  4.74it/s]

Gaps (ex-reports):  24%|██▍       | 1755/7211 [07:34<18:41,  4.86it/s]

Gaps (ex-reports):  24%|██▍       | 1756/7211 [07:34<19:12,  4.73it/s]

Gaps (ex-reports):  24%|██▍       | 1757/7211 [07:34<19:10,  4.74it/s]

Gaps (ex-reports):  24%|██▍       | 1758/7211 [07:34<18:50,  4.82it/s]

Gaps (ex-reports):  24%|██▍       | 1759/7211 [07:35<19:00,  4.78it/s]

Gaps (ex-reports):  24%|██▍       | 1760/7211 [07:35<18:45,  4.84it/s]

Gaps (ex-reports):  24%|██▍       | 1761/7211 [07:35<19:07,  4.75it/s]

Gaps (ex-reports):  24%|██▍       | 1762/7211 [07:35<18:40,  4.86it/s]

Gaps (ex-reports):  24%|██▍       | 1763/7211 [07:35<18:22,  4.94it/s]

Gaps (ex-reports):  24%|██▍       | 1764/7211 [07:36<18:38,  4.87it/s]

Gaps (ex-reports):  24%|██▍       | 1765/7211 [07:36<18:24,  4.93it/s]

Gaps (ex-reports):  24%|██▍       | 1766/7211 [07:36<18:23,  4.94it/s]

Gaps (ex-reports):  25%|██▍       | 1767/7211 [07:36<18:15,  4.97it/s]

Gaps (ex-reports):  25%|██▍       | 1768/7211 [07:36<18:31,  4.90it/s]

Gaps (ex-reports):  25%|██▍       | 1769/7211 [07:37<18:09,  4.99it/s]

Gaps (ex-reports):  25%|██▍       | 1770/7211 [07:37<18:08,  5.00it/s]

Gaps (ex-reports):  25%|██▍       | 1771/7211 [07:37<18:07,  5.00it/s]

Gaps (ex-reports):  25%|██▍       | 1772/7211 [07:37<17:57,  5.05it/s]

Gaps (ex-reports):  25%|██▍       | 1773/7211 [07:37<17:50,  5.08it/s]

Gaps (ex-reports):  25%|██▍       | 1774/7211 [07:38<18:04,  5.01it/s]

Gaps (ex-reports):  25%|██▍       | 1775/7211 [07:38<18:05,  5.01it/s]

Gaps (ex-reports):  25%|██▍       | 1776/7211 [07:38<18:03,  5.01it/s]

Gaps (ex-reports):  25%|██▍       | 1777/7211 [07:38<17:55,  5.05it/s]

Gaps (ex-reports):  25%|██▍       | 1778/7211 [07:38<18:26,  4.91it/s]

Gaps (ex-reports):  25%|██▍       | 1779/7211 [07:39<18:49,  4.81it/s]

Gaps (ex-reports):  25%|██▍       | 1780/7211 [07:39<18:47,  4.82it/s]

Gaps (ex-reports):  25%|██▍       | 1781/7211 [07:39<19:10,  4.72it/s]

Gaps (ex-reports):  25%|██▍       | 1782/7211 [07:39<19:21,  4.67it/s]

Gaps (ex-reports):  25%|██▍       | 1783/7211 [07:39<18:54,  4.78it/s]

Gaps (ex-reports):  25%|██▍       | 1784/7211 [07:40<18:56,  4.78it/s]

Gaps (ex-reports):  25%|██▍       | 1785/7211 [07:40<18:48,  4.81it/s]

Gaps (ex-reports):  25%|██▍       | 1786/7211 [07:40<18:37,  4.86it/s]

Gaps (ex-reports):  25%|██▍       | 1787/7211 [07:40<18:22,  4.92it/s]

Gaps (ex-reports):  25%|██▍       | 1788/7211 [07:40<18:46,  4.81it/s]

Gaps (ex-reports):  25%|██▍       | 1789/7211 [07:41<18:44,  4.82it/s]

Gaps (ex-reports):  25%|██▍       | 1790/7211 [07:41<18:45,  4.82it/s]

Gaps (ex-reports):  25%|██▍       | 1791/7211 [07:41<18:58,  4.76it/s]

Gaps (ex-reports):  25%|██▍       | 1792/7211 [07:41<18:37,  4.85it/s]

Gaps (ex-reports):  25%|██▍       | 1793/7211 [07:42<18:41,  4.83it/s]

Gaps (ex-reports):  25%|██▍       | 1794/7211 [07:42<18:14,  4.95it/s]

Gaps (ex-reports):  25%|██▍       | 1795/7211 [07:42<18:38,  4.84it/s]

Gaps (ex-reports):  25%|██▍       | 1796/7211 [07:42<18:18,  4.93it/s]

Gaps (ex-reports):  25%|██▍       | 1797/7211 [07:42<18:07,  4.98it/s]

Gaps (ex-reports):  25%|██▍       | 1798/7211 [07:43<18:03,  4.99it/s]

Gaps (ex-reports):  25%|██▍       | 1799/7211 [07:43<18:17,  4.93it/s]

Gaps (ex-reports):  25%|██▍       | 1800/7211 [07:43<18:13,  4.95it/s]

Gaps (ex-reports):  25%|██▍       | 1801/7211 [07:43<18:07,  4.97it/s]

Gaps (ex-reports):  25%|██▍       | 1802/7211 [07:43<18:21,  4.91it/s]

Gaps (ex-reports):  25%|██▌       | 1803/7211 [07:44<18:24,  4.90it/s]

Gaps (ex-reports):  25%|██▌       | 1804/7211 [07:44<18:12,  4.95it/s]

Gaps (ex-reports):  25%|██▌       | 1805/7211 [07:44<17:57,  5.01it/s]

Gaps (ex-reports):  25%|██▌       | 1806/7211 [07:44<18:16,  4.93it/s]

Gaps (ex-reports):  25%|██▌       | 1807/7211 [07:44<17:53,  5.03it/s]

Gaps (ex-reports):  25%|██▌       | 1808/7211 [07:45<17:45,  5.07it/s]

Gaps (ex-reports):  25%|██▌       | 1809/7211 [07:45<17:51,  5.04it/s]

Gaps (ex-reports):  25%|██▌       | 1810/7211 [07:45<18:04,  4.98it/s]

Gaps (ex-reports):  25%|██▌       | 1811/7211 [07:45<18:08,  4.96it/s]

Gaps (ex-reports):  25%|██▌       | 1812/7211 [07:45<17:52,  5.03it/s]

Gaps (ex-reports):  25%|██▌       | 1813/7211 [07:46<18:04,  4.98it/s]

Gaps (ex-reports):  25%|██▌       | 1814/7211 [07:46<18:11,  4.95it/s]

Gaps (ex-reports):  25%|██▌       | 1815/7211 [07:46<18:00,  5.00it/s]

Gaps (ex-reports):  25%|██▌       | 1816/7211 [07:46<17:45,  5.06it/s]

Gaps (ex-reports):  25%|██▌       | 1817/7211 [07:46<17:58,  5.00it/s]

Gaps (ex-reports):  25%|██▌       | 1818/7211 [07:47<17:50,  5.04it/s]

Gaps (ex-reports):  25%|██▌       | 1819/7211 [07:47<17:35,  5.11it/s]

Gaps (ex-reports):  25%|██▌       | 1820/7211 [07:47<17:54,  5.02it/s]

Gaps (ex-reports):  25%|██▌       | 1821/7211 [07:47<17:54,  5.01it/s]

Gaps (ex-reports):  25%|██▌       | 1822/7211 [07:47<17:59,  4.99it/s]

Gaps (ex-reports):  25%|██▌       | 1823/7211 [07:48<18:32,  4.84it/s]

Gaps (ex-reports):  25%|██▌       | 1824/7211 [07:48<18:13,  4.93it/s]

Gaps (ex-reports):  25%|██▌       | 1825/7211 [07:48<17:57,  5.00it/s]

Gaps (ex-reports):  25%|██▌       | 1826/7211 [07:48<17:51,  5.03it/s]

Gaps (ex-reports):  25%|██▌       | 1827/7211 [07:48<18:20,  4.89it/s]

Gaps (ex-reports):  25%|██▌       | 1828/7211 [07:49<18:08,  4.95it/s]

Gaps (ex-reports):  25%|██▌       | 1829/7211 [07:49<17:45,  5.05it/s]

Gaps (ex-reports):  25%|██▌       | 1830/7211 [07:49<17:48,  5.04it/s]

Gaps (ex-reports):  25%|██▌       | 1831/7211 [07:49<17:50,  5.03it/s]

Gaps (ex-reports):  25%|██▌       | 1832/7211 [07:49<17:50,  5.02it/s]

Gaps (ex-reports):  25%|██▌       | 1833/7211 [07:50<17:34,  5.10it/s]

Gaps (ex-reports):  25%|██▌       | 1834/7211 [07:50<17:51,  5.02it/s]

Gaps (ex-reports):  25%|██▌       | 1835/7211 [07:50<17:45,  5.04it/s]

Gaps (ex-reports):  25%|██▌       | 1836/7211 [07:50<17:57,  4.99it/s]

Gaps (ex-reports):  25%|██▌       | 1837/7211 [07:50<18:43,  4.78it/s]

Gaps (ex-reports):  25%|██▌       | 1838/7211 [07:51<18:28,  4.85it/s]

Gaps (ex-reports):  26%|██▌       | 1839/7211 [07:51<18:25,  4.86it/s]

Gaps (ex-reports):  26%|██▌       | 1840/7211 [07:51<18:33,  4.82it/s]

Gaps (ex-reports):  26%|██▌       | 1841/7211 [07:51<18:27,  4.85it/s]

Gaps (ex-reports):  26%|██▌       | 1842/7211 [07:51<18:15,  4.90it/s]

Gaps (ex-reports):  26%|██▌       | 1843/7211 [07:52<18:29,  4.84it/s]

Gaps (ex-reports):  26%|██▌       | 1844/7211 [07:52<18:29,  4.84it/s]

Gaps (ex-reports):  26%|██▌       | 1845/7211 [07:52<21:29,  4.16it/s]

Gaps (ex-reports):  26%|██▌       | 1846/7211 [07:52<20:30,  4.36it/s]

Gaps (ex-reports):  26%|██▌       | 1847/7211 [07:53<19:34,  4.57it/s]

Gaps (ex-reports):  26%|██▌       | 1848/7211 [07:53<18:48,  4.75it/s]

Gaps (ex-reports):  26%|██▌       | 1849/7211 [07:53<25:43,  3.47it/s]

Gaps (ex-reports):  26%|██▌       | 1850/7211 [07:53<23:03,  3.87it/s]

Gaps (ex-reports):  26%|██▌       | 1851/7211 [07:54<21:43,  4.11it/s]

Gaps (ex-reports):  26%|██▌       | 1852/7211 [07:54<20:35,  4.34it/s]

Gaps (ex-reports):  26%|██▌       | 1853/7211 [07:54<19:42,  4.53it/s]

Gaps (ex-reports):  26%|██▌       | 1854/7211 [07:54<18:58,  4.71it/s]

Gaps (ex-reports):  26%|██▌       | 1855/7211 [07:54<18:49,  4.74it/s]

Gaps (ex-reports):  26%|██▌       | 1856/7211 [07:55<18:53,  4.72it/s]

Gaps (ex-reports):  26%|██▌       | 1857/7211 [07:55<18:44,  4.76it/s]

Gaps (ex-reports):  26%|██▌       | 1858/7211 [07:55<18:51,  4.73it/s]

Gaps (ex-reports):  26%|██▌       | 1859/7211 [07:55<18:40,  4.78it/s]

Gaps (ex-reports):  26%|██▌       | 1860/7211 [07:55<18:35,  4.80it/s]

Gaps (ex-reports):  26%|██▌       | 1861/7211 [07:56<18:41,  4.77it/s]

Gaps (ex-reports):  26%|██▌       | 1862/7211 [07:56<18:39,  4.78it/s]

Gaps (ex-reports):  26%|██▌       | 1863/7211 [07:56<18:30,  4.82it/s]

Gaps (ex-reports):  26%|██▌       | 1864/7211 [07:56<18:49,  4.74it/s]

Gaps (ex-reports):  26%|██▌       | 1865/7211 [07:56<18:28,  4.82it/s]

Gaps (ex-reports):  26%|██▌       | 1866/7211 [07:57<18:22,  4.85it/s]

Gaps (ex-reports):  26%|██▌       | 1867/7211 [07:57<18:29,  4.82it/s]

Gaps (ex-reports):  26%|██▌       | 1868/7211 [07:57<18:29,  4.81it/s]

Gaps (ex-reports):  26%|██▌       | 1869/7211 [07:57<18:30,  4.81it/s]

Gaps (ex-reports):  26%|██▌       | 1870/7211 [07:57<17:59,  4.95it/s]

Gaps (ex-reports):  26%|██▌       | 1871/7211 [07:58<17:57,  4.96it/s]

Gaps (ex-reports):  26%|██▌       | 1872/7211 [07:58<17:45,  5.01it/s]

Gaps (ex-reports):  26%|██▌       | 1873/7211 [07:58<17:50,  4.99it/s]

Gaps (ex-reports):  26%|██▌       | 1874/7211 [07:58<17:29,  5.08it/s]

Gaps (ex-reports):  26%|██▌       | 1875/7211 [07:58<17:25,  5.10it/s]

Gaps (ex-reports):  26%|██▌       | 1876/7211 [07:59<17:39,  5.03it/s]

Gaps (ex-reports):  26%|██▌       | 1877/7211 [07:59<17:38,  5.04it/s]

Gaps (ex-reports):  26%|██▌       | 1878/7211 [07:59<17:59,  4.94it/s]

Gaps (ex-reports):  26%|██▌       | 1879/7211 [07:59<17:56,  4.95it/s]

Gaps (ex-reports):  26%|██▌       | 1880/7211 [07:59<17:55,  4.96it/s]

Gaps (ex-reports):  26%|██▌       | 1881/7211 [08:00<17:56,  4.95it/s]

Gaps (ex-reports):  26%|██▌       | 1882/7211 [08:00<18:04,  4.91it/s]

Gaps (ex-reports):  26%|██▌       | 1883/7211 [08:00<18:05,  4.91it/s]

Gaps (ex-reports):  26%|██▌       | 1884/7211 [08:00<18:27,  4.81it/s]

Gaps (ex-reports):  26%|██▌       | 1885/7211 [08:01<18:12,  4.87it/s]

Gaps (ex-reports):  26%|██▌       | 1886/7211 [08:01<18:26,  4.81it/s]

Gaps (ex-reports):  26%|██▌       | 1887/7211 [08:01<18:28,  4.80it/s]

Gaps (ex-reports):  26%|██▌       | 1888/7211 [08:01<18:52,  4.70it/s]

Gaps (ex-reports):  26%|██▌       | 1889/7211 [08:01<18:31,  4.79it/s]

Gaps (ex-reports):  26%|██▌       | 1890/7211 [08:02<18:20,  4.83it/s]

Gaps (ex-reports):  26%|██▌       | 1891/7211 [08:02<18:12,  4.87it/s]

Gaps (ex-reports):  26%|██▌       | 1892/7211 [08:02<18:25,  4.81it/s]

Gaps (ex-reports):  26%|██▋       | 1893/7211 [08:02<18:21,  4.83it/s]

Gaps (ex-reports):  26%|██▋       | 1894/7211 [08:02<17:49,  4.97it/s]

Gaps (ex-reports):  26%|██▋       | 1895/7211 [08:03<17:34,  5.04it/s]

Gaps (ex-reports):  26%|██▋       | 1896/7211 [08:03<17:35,  5.04it/s]

Gaps (ex-reports):  26%|██▋       | 1897/7211 [08:03<17:48,  4.98it/s]

Gaps (ex-reports):  26%|██▋       | 1898/7211 [08:03<17:57,  4.93it/s]

Gaps (ex-reports):  26%|██▋       | 1899/7211 [08:03<18:01,  4.91it/s]

Gaps (ex-reports):  26%|██▋       | 1900/7211 [08:04<18:02,  4.90it/s]

Gaps (ex-reports):  26%|██▋       | 1901/7211 [08:04<18:04,  4.90it/s]

Gaps (ex-reports):  26%|██▋       | 1902/7211 [08:04<17:56,  4.93it/s]

Gaps (ex-reports):  26%|██▋       | 1903/7211 [08:04<17:41,  5.00it/s]

Gaps (ex-reports):  26%|██▋       | 1904/7211 [08:04<17:29,  5.06it/s]

Gaps (ex-reports):  26%|██▋       | 1905/7211 [08:05<17:18,  5.11it/s]

Gaps (ex-reports):  26%|██▋       | 1906/7211 [08:05<17:17,  5.11it/s]

Gaps (ex-reports):  26%|██▋       | 1907/7211 [08:05<17:40,  5.00it/s]

Gaps (ex-reports):  26%|██▋       | 1908/7211 [08:05<17:44,  4.98it/s]

Gaps (ex-reports):  26%|██▋       | 1909/7211 [08:05<17:55,  4.93it/s]

Gaps (ex-reports):  26%|██▋       | 1910/7211 [08:06<18:00,  4.91it/s]

Gaps (ex-reports):  27%|██▋       | 1911/7211 [08:06<18:09,  4.87it/s]

Gaps (ex-reports):  27%|██▋       | 1912/7211 [08:06<17:47,  4.96it/s]

Gaps (ex-reports):  27%|██▋       | 1913/7211 [08:06<17:25,  5.07it/s]

Gaps (ex-reports):  27%|██▋       | 1914/7211 [08:06<17:13,  5.12it/s]

Gaps (ex-reports):  27%|██▋       | 1915/7211 [08:07<17:37,  5.01it/s]

Gaps (ex-reports):  27%|██▋       | 1916/7211 [08:07<19:27,  4.53it/s]

Gaps (ex-reports):  27%|██▋       | 1917/7211 [08:07<20:29,  4.30it/s]

Gaps (ex-reports):  27%|██▋       | 1918/7211 [08:07<20:40,  4.27it/s]

Gaps (ex-reports):  27%|██▋       | 1919/7211 [08:08<21:13,  4.15it/s]

Gaps (ex-reports):  27%|██▋       | 1920/7211 [08:08<19:53,  4.43it/s]

Gaps (ex-reports):  27%|██▋       | 1921/7211 [08:08<19:12,  4.59it/s]

Gaps (ex-reports):  27%|██▋       | 1922/7211 [08:08<19:20,  4.56it/s]

Gaps (ex-reports):  27%|██▋       | 1923/7211 [08:08<18:36,  4.74it/s]

Gaps (ex-reports):  27%|██▋       | 1924/7211 [08:09<18:21,  4.80it/s]

Gaps (ex-reports):  27%|██▋       | 1925/7211 [08:09<17:55,  4.92it/s]

Gaps (ex-reports):  27%|██▋       | 1926/7211 [08:09<18:05,  4.87it/s]

Gaps (ex-reports):  27%|██▋       | 1927/7211 [08:09<17:33,  5.02it/s]

Gaps (ex-reports):  27%|██▋       | 1928/7211 [08:09<17:34,  5.01it/s]

Gaps (ex-reports):  27%|██▋       | 1929/7211 [08:10<18:11,  4.84it/s]

Gaps (ex-reports):  27%|██▋       | 1930/7211 [08:10<18:06,  4.86it/s]

Gaps (ex-reports):  27%|██▋       | 1931/7211 [08:10<18:02,  4.88it/s]

Gaps (ex-reports):  27%|██▋       | 1932/7211 [08:10<17:57,  4.90it/s]

Gaps (ex-reports):  27%|██▋       | 1933/7211 [08:10<17:38,  4.98it/s]

Gaps (ex-reports):  27%|██▋       | 1934/7211 [08:11<17:34,  5.00it/s]

Gaps (ex-reports):  27%|██▋       | 1935/7211 [08:11<17:13,  5.10it/s]

Gaps (ex-reports):  27%|██▋       | 1936/7211 [08:11<17:29,  5.03it/s]

Gaps (ex-reports):  27%|██▋       | 1937/7211 [08:11<17:26,  5.04it/s]

Gaps (ex-reports):  27%|██▋       | 1938/7211 [08:11<17:35,  4.99it/s]

Gaps (ex-reports):  27%|██▋       | 1939/7211 [08:12<17:23,  5.05it/s]

Gaps (ex-reports):  27%|██▋       | 1940/7211 [08:12<17:51,  4.92it/s]

Gaps (ex-reports):  27%|██▋       | 1941/7211 [08:12<17:25,  5.04it/s]

Gaps (ex-reports):  27%|██▋       | 1942/7211 [08:12<17:36,  4.99it/s]

Gaps (ex-reports):  27%|██▋       | 1943/7211 [08:12<17:19,  5.07it/s]

Gaps (ex-reports):  27%|██▋       | 1944/7211 [08:13<17:12,  5.10it/s]

Gaps (ex-reports):  27%|██▋       | 1945/7211 [08:13<17:31,  5.01it/s]

Gaps (ex-reports):  27%|██▋       | 1946/7211 [08:13<17:25,  5.04it/s]

Gaps (ex-reports):  27%|██▋       | 1947/7211 [08:13<17:32,  5.00it/s]

Gaps (ex-reports):  27%|██▋       | 1948/7211 [08:13<17:36,  4.98it/s]

Gaps (ex-reports):  27%|██▋       | 1949/7211 [08:14<17:49,  4.92it/s]

Gaps (ex-reports):  27%|██▋       | 1950/7211 [08:14<17:58,  4.88it/s]

Gaps (ex-reports):  27%|██▋       | 1951/7211 [08:14<18:05,  4.85it/s]

Gaps (ex-reports):  27%|██▋       | 1952/7211 [08:14<17:56,  4.88it/s]

Gaps (ex-reports):  27%|██▋       | 1953/7211 [08:14<17:56,  4.88it/s]

Gaps (ex-reports):  27%|██▋       | 1954/7211 [08:15<17:41,  4.95it/s]

Gaps (ex-reports):  27%|██▋       | 1955/7211 [08:15<18:01,  4.86it/s]

Gaps (ex-reports):  27%|██▋       | 1956/7211 [08:15<18:05,  4.84it/s]

Gaps (ex-reports):  27%|██▋       | 1957/7211 [08:15<17:54,  4.89it/s]

Gaps (ex-reports):  27%|██▋       | 1958/7211 [08:15<17:53,  4.89it/s]

Gaps (ex-reports):  27%|██▋       | 1959/7211 [08:16<18:14,  4.80it/s]

Gaps (ex-reports):  27%|██▋       | 1960/7211 [08:16<18:18,  4.78it/s]

Gaps (ex-reports):  27%|██▋       | 1961/7211 [08:16<21:21,  4.10it/s]

Gaps (ex-reports):  27%|██▋       | 1962/7211 [08:16<19:58,  4.38it/s]

Gaps (ex-reports):  27%|██▋       | 1963/7211 [08:17<19:03,  4.59it/s]

Gaps (ex-reports):  27%|██▋       | 1964/7211 [08:17<18:23,  4.75it/s]

Gaps (ex-reports):  27%|██▋       | 1965/7211 [08:17<17:52,  4.89it/s]

Gaps (ex-reports):  27%|██▋       | 1966/7211 [08:17<17:33,  4.98it/s]

Gaps (ex-reports):  27%|██▋       | 1967/7211 [08:17<19:53,  4.39it/s]

Gaps (ex-reports):  27%|██▋       | 1968/7211 [08:18<19:36,  4.46it/s]

Gaps (ex-reports):  27%|██▋       | 1969/7211 [08:18<19:29,  4.48it/s]

Gaps (ex-reports):  27%|██▋       | 1970/7211 [08:18<19:04,  4.58it/s]

Gaps (ex-reports):  27%|██▋       | 1971/7211 [08:18<18:32,  4.71it/s]

Gaps (ex-reports):  27%|██▋       | 1972/7211 [08:19<18:08,  4.81it/s]

Gaps (ex-reports):  27%|██▋       | 1973/7211 [08:19<17:41,  4.94it/s]

Gaps (ex-reports):  27%|██▋       | 1974/7211 [08:19<17:34,  4.97it/s]

Gaps (ex-reports):  27%|██▋       | 1975/7211 [08:19<17:42,  4.93it/s]

Gaps (ex-reports):  27%|██▋       | 1976/7211 [08:19<17:44,  4.92it/s]

Gaps (ex-reports):  27%|██▋       | 1977/7211 [08:20<17:45,  4.91it/s]

Gaps (ex-reports):  27%|██▋       | 1978/7211 [08:20<17:35,  4.96it/s]

Gaps (ex-reports):  27%|██▋       | 1979/7211 [08:20<17:17,  5.04it/s]

Gaps (ex-reports):  27%|██▋       | 1980/7211 [08:20<17:44,  4.92it/s]

Gaps (ex-reports):  27%|██▋       | 1981/7211 [08:20<17:53,  4.87it/s]

Gaps (ex-reports):  27%|██▋       | 1982/7211 [08:21<17:55,  4.86it/s]

Gaps (ex-reports):  27%|██▋       | 1983/7211 [08:21<18:05,  4.82it/s]

Gaps (ex-reports):  28%|██▊       | 1984/7211 [08:21<18:08,  4.80it/s]

Gaps (ex-reports):  28%|██▊       | 1985/7211 [08:21<17:53,  4.87it/s]

Gaps (ex-reports):  28%|██▊       | 1986/7211 [08:21<17:42,  4.92it/s]

Gaps (ex-reports):  28%|██▊       | 1987/7211 [08:22<17:58,  4.84it/s]

Gaps (ex-reports):  28%|██▊       | 1988/7211 [08:22<17:58,  4.84it/s]

Gaps (ex-reports):  28%|██▊       | 1989/7211 [08:22<17:43,  4.91it/s]

Gaps (ex-reports):  28%|██▊       | 1990/7211 [08:22<18:14,  4.77it/s]

Gaps (ex-reports):  28%|██▊       | 1991/7211 [08:22<17:49,  4.88it/s]

Gaps (ex-reports):  28%|██▊       | 1992/7211 [08:23<17:29,  4.97it/s]

Gaps (ex-reports):  28%|██▊       | 1993/7211 [08:23<17:11,  5.06it/s]

Gaps (ex-reports):  28%|██▊       | 1994/7211 [08:23<17:05,  5.09it/s]

Gaps (ex-reports):  28%|██▊       | 1995/7211 [08:23<17:08,  5.07it/s]

Gaps (ex-reports):  28%|██▊       | 1996/7211 [08:23<17:34,  4.95it/s]

Gaps (ex-reports):  28%|██▊       | 1997/7211 [08:24<17:43,  4.90it/s]

Gaps (ex-reports):  28%|██▊       | 1998/7211 [08:24<17:42,  4.91it/s]

Gaps (ex-reports):  28%|██▊       | 1999/7211 [08:25<31:08,  2.79it/s]

Gaps (ex-reports):  28%|██▊       | 2000/7211 [08:25<27:08,  3.20it/s]

Gaps (ex-reports):  28%|██▊       | 2001/7211 [08:25<24:14,  3.58it/s]

Gaps (ex-reports):  28%|██▊       | 2002/7211 [08:25<22:32,  3.85it/s]

Gaps (ex-reports):  28%|██▊       | 2003/7211 [08:25<21:09,  4.10it/s]

Gaps (ex-reports):  28%|██▊       | 2004/7211 [08:26<20:08,  4.31it/s]

Gaps (ex-reports):  28%|██▊       | 2005/7211 [08:26<19:15,  4.51it/s]

Gaps (ex-reports):  28%|██▊       | 2006/7211 [08:26<18:51,  4.60it/s]

Gaps (ex-reports):  28%|██▊       | 2007/7211 [08:26<18:46,  4.62it/s]

Gaps (ex-reports):  28%|██▊       | 2008/7211 [08:26<18:28,  4.69it/s]

Gaps (ex-reports):  28%|██▊       | 2009/7211 [08:27<18:20,  4.73it/s]

Gaps (ex-reports):  28%|██▊       | 2010/7211 [08:27<17:49,  4.86it/s]

Gaps (ex-reports):  28%|██▊       | 2011/7211 [08:27<18:11,  4.77it/s]

Gaps (ex-reports):  28%|██▊       | 2012/7211 [08:27<17:55,  4.83it/s]

Gaps (ex-reports):  28%|██▊       | 2013/7211 [08:27<17:46,  4.87it/s]

Gaps (ex-reports):  28%|██▊       | 2014/7211 [08:28<17:54,  4.83it/s]

Gaps (ex-reports):  28%|██▊       | 2015/7211 [08:28<18:01,  4.80it/s]

Gaps (ex-reports):  28%|██▊       | 2016/7211 [08:28<18:24,  4.70it/s]

Gaps (ex-reports):  28%|██▊       | 2017/7211 [08:28<17:56,  4.83it/s]

Gaps (ex-reports):  28%|██▊       | 2018/7211 [08:28<17:55,  4.83it/s]

Gaps (ex-reports):  28%|██▊       | 2019/7211 [08:29<17:50,  4.85it/s]

Gaps (ex-reports):  28%|██▊       | 2020/7211 [08:29<18:09,  4.76it/s]

Gaps (ex-reports):  28%|██▊       | 2021/7211 [08:29<17:48,  4.86it/s]

Gaps (ex-reports):  28%|██▊       | 2022/7211 [08:29<17:51,  4.84it/s]

Gaps (ex-reports):  28%|██▊       | 2023/7211 [08:29<17:42,  4.88it/s]

Gaps (ex-reports):  28%|██▊       | 2024/7211 [08:30<17:30,  4.94it/s]

Gaps (ex-reports):  28%|██▊       | 2025/7211 [08:30<17:15,  5.01it/s]

Gaps (ex-reports):  28%|██▊       | 2026/7211 [08:30<17:11,  5.03it/s]

Gaps (ex-reports):  28%|██▊       | 2027/7211 [08:30<17:42,  4.88it/s]

Gaps (ex-reports):  28%|██▊       | 2028/7211 [08:31<41:18,  2.09it/s]

Gaps (ex-reports):  28%|██▊       | 2029/7211 [08:32<34:24,  2.51it/s]

Gaps (ex-reports):  28%|██▊       | 2030/7211 [08:32<29:27,  2.93it/s]

Gaps (ex-reports):  28%|██▊       | 2031/7211 [08:32<25:51,  3.34it/s]

Gaps (ex-reports):  28%|██▊       | 2032/7211 [08:32<23:08,  3.73it/s]

Gaps (ex-reports):  28%|██▊       | 2033/7211 [08:32<21:09,  4.08it/s]

Gaps (ex-reports):  28%|██▊       | 2034/7211 [08:33<19:56,  4.33it/s]

Gaps (ex-reports):  28%|██▊       | 2035/7211 [08:33<19:04,  4.52it/s]

Gaps (ex-reports):  28%|██▊       | 2036/7211 [08:33<19:00,  4.54it/s]

Gaps (ex-reports):  28%|██▊       | 2037/7211 [08:33<18:45,  4.60it/s]

Gaps (ex-reports):  28%|██▊       | 2038/7211 [08:33<18:27,  4.67it/s]

Gaps (ex-reports):  28%|██▊       | 2039/7211 [08:34<18:22,  4.69it/s]

Gaps (ex-reports):  28%|██▊       | 2040/7211 [08:34<18:04,  4.77it/s]

Gaps (ex-reports):  28%|██▊       | 2041/7211 [08:34<17:53,  4.82it/s]

Gaps (ex-reports):  28%|██▊       | 2042/7211 [08:34<17:40,  4.87it/s]

Gaps (ex-reports):  28%|██▊       | 2043/7211 [08:34<17:31,  4.92it/s]

Gaps (ex-reports):  28%|██▊       | 2044/7211 [08:35<17:38,  4.88it/s]

Gaps (ex-reports):  28%|██▊       | 2045/7211 [08:35<31:07,  2.77it/s]

Gaps (ex-reports):  28%|██▊       | 2046/7211 [08:36<27:23,  3.14it/s]

Gaps (ex-reports):  28%|██▊       | 2047/7211 [08:36<24:47,  3.47it/s]

Gaps (ex-reports):  28%|██▊       | 2048/7211 [08:36<22:38,  3.80it/s]

Gaps (ex-reports):  28%|██▊       | 2049/7211 [08:36<21:09,  4.07it/s]

Gaps (ex-reports):  28%|██▊       | 2050/7211 [08:36<20:10,  4.26it/s]

Gaps (ex-reports):  28%|██▊       | 2051/7211 [08:37<19:20,  4.45it/s]

Gaps (ex-reports):  28%|██▊       | 2052/7211 [08:37<18:53,  4.55it/s]

Gaps (ex-reports):  28%|██▊       | 2053/7211 [08:37<18:14,  4.71it/s]

Gaps (ex-reports):  28%|██▊       | 2054/7211 [08:37<17:38,  4.87it/s]

Gaps (ex-reports):  28%|██▊       | 2055/7211 [08:37<17:29,  4.92it/s]

Gaps (ex-reports):  29%|██▊       | 2056/7211 [08:38<17:26,  4.93it/s]

Gaps (ex-reports):  29%|██▊       | 2057/7211 [08:38<18:01,  4.76it/s]

Gaps (ex-reports):  29%|██▊       | 2058/7211 [08:38<18:10,  4.72it/s]

Gaps (ex-reports):  29%|██▊       | 2059/7211 [08:38<17:48,  4.82it/s]

Gaps (ex-reports):  29%|██▊       | 2060/7211 [08:38<17:26,  4.92it/s]

Gaps (ex-reports):  29%|██▊       | 2061/7211 [08:39<17:14,  4.98it/s]

Gaps (ex-reports):  29%|██▊       | 2062/7211 [08:39<17:31,  4.90it/s]

Gaps (ex-reports):  29%|██▊       | 2063/7211 [08:39<17:42,  4.84it/s]

Gaps (ex-reports):  29%|██▊       | 2064/7211 [08:39<17:34,  4.88it/s]

Gaps (ex-reports):  29%|██▊       | 2065/7211 [08:39<17:44,  4.83it/s]

Gaps (ex-reports):  29%|██▊       | 2066/7211 [08:40<17:46,  4.82it/s]

Gaps (ex-reports):  29%|██▊       | 2067/7211 [08:40<18:01,  4.75it/s]

Gaps (ex-reports):  29%|██▊       | 2068/7211 [08:40<17:49,  4.81it/s]

Gaps (ex-reports):  29%|██▊       | 2069/7211 [08:40<17:42,  4.84it/s]

Gaps (ex-reports):  29%|██▊       | 2070/7211 [08:41<17:31,  4.89it/s]

Gaps (ex-reports):  29%|██▊       | 2071/7211 [08:41<17:12,  4.98it/s]

Gaps (ex-reports):  29%|██▊       | 2072/7211 [08:41<17:07,  5.00it/s]

Gaps (ex-reports):  29%|██▊       | 2073/7211 [08:41<17:26,  4.91it/s]

Gaps (ex-reports):  29%|██▉       | 2074/7211 [08:41<18:31,  4.62it/s]

Gaps (ex-reports):  29%|██▉       | 2075/7211 [08:42<18:21,  4.66it/s]

Gaps (ex-reports):  29%|██▉       | 2076/7211 [08:42<18:22,  4.66it/s]

Gaps (ex-reports):  29%|██▉       | 2077/7211 [08:42<18:28,  4.63it/s]

Gaps (ex-reports):  29%|██▉       | 2078/7211 [08:42<17:57,  4.76it/s]

Gaps (ex-reports):  29%|██▉       | 2079/7211 [08:42<17:49,  4.80it/s]

Gaps (ex-reports):  29%|██▉       | 2080/7211 [08:43<18:05,  4.73it/s]

Gaps (ex-reports):  29%|██▉       | 2081/7211 [08:43<17:54,  4.77it/s]

Gaps (ex-reports):  29%|██▉       | 2082/7211 [08:43<17:44,  4.82it/s]

Gaps (ex-reports):  29%|██▉       | 2083/7211 [08:43<17:21,  4.92it/s]

Gaps (ex-reports):  29%|██▉       | 2084/7211 [08:43<17:07,  4.99it/s]

Gaps (ex-reports):  29%|██▉       | 2085/7211 [08:44<17:05,  5.00it/s]

Gaps (ex-reports):  29%|██▉       | 2086/7211 [08:44<17:25,  4.90it/s]

Gaps (ex-reports):  29%|██▉       | 2087/7211 [08:44<18:33,  4.60it/s]

Gaps (ex-reports):  29%|██▉       | 2088/7211 [08:44<18:14,  4.68it/s]

Gaps (ex-reports):  29%|██▉       | 2089/7211 [08:44<18:01,  4.74it/s]

Gaps (ex-reports):  29%|██▉       | 2090/7211 [08:45<17:32,  4.87it/s]

Gaps (ex-reports):  29%|██▉       | 2091/7211 [08:45<17:15,  4.94it/s]

Gaps (ex-reports):  29%|██▉       | 2092/7211 [08:45<16:56,  5.04it/s]

Gaps (ex-reports):  29%|██▉       | 2093/7211 [08:45<16:47,  5.08it/s]

Gaps (ex-reports):  29%|██▉       | 2094/7211 [08:45<16:33,  5.15it/s]

Gaps (ex-reports):  29%|██▉       | 2095/7211 [08:46<16:56,  5.03it/s]

Gaps (ex-reports):  29%|██▉       | 2096/7211 [08:46<16:55,  5.04it/s]

Gaps (ex-reports):  29%|██▉       | 2097/7211 [08:46<17:12,  4.95it/s]

Gaps (ex-reports):  29%|██▉       | 2098/7211 [08:46<17:23,  4.90it/s]

Gaps (ex-reports):  29%|██▉       | 2099/7211 [08:46<17:27,  4.88it/s]

Gaps (ex-reports):  29%|██▉       | 2100/7211 [08:47<17:27,  4.88it/s]

Gaps (ex-reports):  29%|██▉       | 2101/7211 [08:47<22:38,  3.76it/s]

Gaps (ex-reports):  29%|██▉       | 2102/7211 [08:47<21:12,  4.02it/s]

Gaps (ex-reports):  29%|██▉       | 2103/7211 [08:48<19:54,  4.27it/s]

Gaps (ex-reports):  29%|██▉       | 2104/7211 [08:48<19:22,  4.39it/s]

Gaps (ex-reports):  29%|██▉       | 2105/7211 [08:48<18:52,  4.51it/s]

Gaps (ex-reports):  29%|██▉       | 2106/7211 [08:48<18:26,  4.61it/s]

Gaps (ex-reports):  29%|██▉       | 2107/7211 [08:48<18:11,  4.68it/s]

Gaps (ex-reports):  29%|██▉       | 2108/7211 [08:49<17:54,  4.75it/s]

Gaps (ex-reports):  29%|██▉       | 2109/7211 [08:49<17:40,  4.81it/s]

Gaps (ex-reports):  29%|██▉       | 2110/7211 [08:49<17:46,  4.78it/s]

Gaps (ex-reports):  29%|██▉       | 2111/7211 [08:49<17:41,  4.80it/s]

Gaps (ex-reports):  29%|██▉       | 2112/7211 [08:49<17:28,  4.86it/s]

Gaps (ex-reports):  29%|██▉       | 2113/7211 [08:50<17:25,  4.88it/s]

Gaps (ex-reports):  29%|██▉       | 2114/7211 [08:50<17:32,  4.84it/s]

Gaps (ex-reports):  29%|██▉       | 2115/7211 [08:50<17:30,  4.85it/s]

Gaps (ex-reports):  29%|██▉       | 2116/7211 [08:50<17:31,  4.85it/s]

Gaps (ex-reports):  29%|██▉       | 2117/7211 [08:50<17:31,  4.84it/s]

Gaps (ex-reports):  29%|██▉       | 2118/7211 [08:51<17:35,  4.83it/s]

Gaps (ex-reports):  29%|██▉       | 2119/7211 [08:51<17:28,  4.86it/s]

Gaps (ex-reports):  29%|██▉       | 2120/7211 [08:51<17:40,  4.80it/s]

Gaps (ex-reports):  29%|██▉       | 2121/7211 [08:51<17:32,  4.84it/s]

Gaps (ex-reports):  29%|██▉       | 2122/7211 [08:51<17:45,  4.77it/s]

Gaps (ex-reports):  29%|██▉       | 2123/7211 [08:52<17:46,  4.77it/s]

Gaps (ex-reports):  29%|██▉       | 2124/7211 [08:52<17:31,  4.84it/s]

Gaps (ex-reports):  29%|██▉       | 2125/7211 [08:52<17:11,  4.93it/s]

Gaps (ex-reports):  29%|██▉       | 2126/7211 [08:52<17:10,  4.94it/s]

Gaps (ex-reports):  29%|██▉       | 2127/7211 [08:52<17:01,  4.98it/s]

Gaps (ex-reports):  30%|██▉       | 2128/7211 [08:53<17:02,  4.97it/s]

Gaps (ex-reports):  30%|██▉       | 2129/7211 [08:53<17:07,  4.94it/s]

Gaps (ex-reports):  30%|██▉       | 2130/7211 [08:53<17:04,  4.96it/s]

Gaps (ex-reports):  30%|██▉       | 2131/7211 [08:53<16:46,  5.05it/s]

Gaps (ex-reports):  30%|██▉       | 2132/7211 [08:53<16:29,  5.13it/s]

Gaps (ex-reports):  30%|██▉       | 2133/7211 [08:54<16:21,  5.17it/s]

Gaps (ex-reports):  30%|██▉       | 2134/7211 [08:54<16:54,  5.00it/s]

Gaps (ex-reports):  30%|██▉       | 2135/7211 [08:54<16:51,  5.02it/s]

Gaps (ex-reports):  30%|██▉       | 2136/7211 [08:54<17:14,  4.90it/s]

Gaps (ex-reports):  30%|██▉       | 2137/7211 [08:54<17:03,  4.96it/s]

Gaps (ex-reports):  30%|██▉       | 2138/7211 [08:55<17:14,  4.90it/s]

Gaps (ex-reports):  30%|██▉       | 2139/7211 [08:55<17:08,  4.93it/s]

Gaps (ex-reports):  30%|██▉       | 2140/7211 [08:55<17:08,  4.93it/s]

Gaps (ex-reports):  30%|██▉       | 2141/7211 [08:55<17:05,  4.94it/s]

Gaps (ex-reports):  30%|██▉       | 2142/7211 [08:55<16:55,  4.99it/s]

Gaps (ex-reports):  30%|██▉       | 2143/7211 [08:56<16:39,  5.07it/s]

Gaps (ex-reports):  30%|██▉       | 2144/7211 [08:56<16:47,  5.03it/s]

Gaps (ex-reports):  30%|██▉       | 2145/7211 [08:56<17:18,  4.88it/s]

Gaps (ex-reports):  30%|██▉       | 2146/7211 [08:56<17:19,  4.87it/s]

Gaps (ex-reports):  30%|██▉       | 2147/7211 [08:56<17:17,  4.88it/s]

Gaps (ex-reports):  30%|██▉       | 2148/7211 [08:57<17:03,  4.95it/s]

Gaps (ex-reports):  30%|██▉       | 2149/7211 [08:57<16:49,  5.01it/s]

Gaps (ex-reports):  30%|██▉       | 2150/7211 [08:57<17:03,  4.95it/s]

Gaps (ex-reports):  30%|██▉       | 2151/7211 [08:57<17:12,  4.90it/s]

Gaps (ex-reports):  30%|██▉       | 2152/7211 [08:57<16:46,  5.03it/s]

Gaps (ex-reports):  30%|██▉       | 2153/7211 [08:58<16:52,  4.99it/s]

Gaps (ex-reports):  30%|██▉       | 2154/7211 [08:58<16:48,  5.01it/s]

Gaps (ex-reports):  30%|██▉       | 2155/7211 [08:58<17:16,  4.88it/s]

Gaps (ex-reports):  30%|██▉       | 2156/7211 [08:58<17:01,  4.95it/s]

Gaps (ex-reports):  30%|██▉       | 2157/7211 [08:58<16:52,  4.99it/s]

Gaps (ex-reports):  30%|██▉       | 2158/7211 [08:59<16:35,  5.07it/s]

Gaps (ex-reports):  30%|██▉       | 2159/7211 [08:59<16:56,  4.97it/s]

Gaps (ex-reports):  30%|██▉       | 2160/7211 [08:59<17:22,  4.84it/s]

Gaps (ex-reports):  30%|██▉       | 2161/7211 [08:59<17:09,  4.91it/s]

Gaps (ex-reports):  30%|██▉       | 2162/7211 [08:59<17:07,  4.91it/s]

Gaps (ex-reports):  30%|██▉       | 2163/7211 [09:00<17:16,  4.87it/s]

Gaps (ex-reports):  30%|███       | 2164/7211 [09:00<17:33,  4.79it/s]

Gaps (ex-reports):  30%|███       | 2165/7211 [09:00<17:29,  4.81it/s]

Gaps (ex-reports):  30%|███       | 2166/7211 [09:00<17:17,  4.86it/s]

Gaps (ex-reports):  30%|███       | 2167/7211 [09:01<17:31,  4.80it/s]

Gaps (ex-reports):  30%|███       | 2168/7211 [09:01<17:14,  4.88it/s]

Gaps (ex-reports):  30%|███       | 2169/7211 [09:01<16:59,  4.95it/s]

Gaps (ex-reports):  30%|███       | 2170/7211 [09:01<16:40,  5.04it/s]

Gaps (ex-reports):  30%|███       | 2171/7211 [09:01<17:44,  4.74it/s]

Gaps (ex-reports):  30%|███       | 2172/7211 [09:02<17:19,  4.85it/s]

Gaps (ex-reports):  30%|███       | 2173/7211 [09:02<17:25,  4.82it/s]

Gaps (ex-reports):  30%|███       | 2174/7211 [09:02<17:17,  4.85it/s]

Gaps (ex-reports):  30%|███       | 2175/7211 [09:02<17:00,  4.93it/s]

Gaps (ex-reports):  30%|███       | 2176/7211 [09:02<17:17,  4.85it/s]

Gaps (ex-reports):  30%|███       | 2177/7211 [09:03<17:07,  4.90it/s]

Gaps (ex-reports):  30%|███       | 2178/7211 [09:03<16:41,  5.03it/s]

Gaps (ex-reports):  30%|███       | 2179/7211 [09:03<16:47,  4.99it/s]

Gaps (ex-reports):  30%|███       | 2180/7211 [09:03<16:59,  4.93it/s]

Gaps (ex-reports):  30%|███       | 2181/7211 [09:03<17:24,  4.82it/s]

Gaps (ex-reports):  30%|███       | 2182/7211 [09:04<17:21,  4.83it/s]

Gaps (ex-reports):  30%|███       | 2183/7211 [09:04<17:06,  4.90it/s]

Gaps (ex-reports):  30%|███       | 2184/7211 [09:04<17:09,  4.88it/s]

Gaps (ex-reports):  30%|███       | 2185/7211 [09:04<17:18,  4.84it/s]

Gaps (ex-reports):  30%|███       | 2186/7211 [09:04<17:12,  4.87it/s]

Gaps (ex-reports):  30%|███       | 2187/7211 [09:05<17:12,  4.87it/s]

Gaps (ex-reports):  30%|███       | 2188/7211 [09:05<17:27,  4.79it/s]

Gaps (ex-reports):  30%|███       | 2189/7211 [09:05<17:29,  4.78it/s]

Gaps (ex-reports):  30%|███       | 2190/7211 [09:05<17:13,  4.86it/s]

Gaps (ex-reports):  30%|███       | 2191/7211 [09:05<17:00,  4.92it/s]

Gaps (ex-reports):  30%|███       | 2192/7211 [09:06<17:20,  4.82it/s]

Gaps (ex-reports):  30%|███       | 2193/7211 [09:06<17:04,  4.90it/s]

Gaps (ex-reports):  30%|███       | 2194/7211 [09:06<16:42,  5.01it/s]

Gaps (ex-reports):  30%|███       | 2195/7211 [09:06<17:11,  4.86it/s]

Gaps (ex-reports):  30%|███       | 2196/7211 [09:06<17:07,  4.88it/s]

Gaps (ex-reports):  30%|███       | 2197/7211 [09:07<17:05,  4.89it/s]

Gaps (ex-reports):  30%|███       | 2198/7211 [09:07<16:55,  4.94it/s]

Gaps (ex-reports):  30%|███       | 2199/7211 [09:07<16:48,  4.97it/s]

Gaps (ex-reports):  31%|███       | 2200/7211 [09:07<16:56,  4.93it/s]

Gaps (ex-reports):  31%|███       | 2201/7211 [09:07<17:28,  4.78it/s]

Gaps (ex-reports):  31%|███       | 2202/7211 [09:08<17:08,  4.87it/s]

Gaps (ex-reports):  31%|███       | 2203/7211 [09:08<16:48,  4.96it/s]

Gaps (ex-reports):  31%|███       | 2204/7211 [09:08<16:54,  4.93it/s]

Gaps (ex-reports):  31%|███       | 2205/7211 [09:08<16:41,  5.00it/s]

Gaps (ex-reports):  31%|███       | 2206/7211 [09:08<16:54,  4.93it/s]

Gaps (ex-reports):  31%|███       | 2207/7211 [09:09<16:55,  4.93it/s]

Gaps (ex-reports):  31%|███       | 2208/7211 [09:09<16:39,  5.00it/s]

Gaps (ex-reports):  31%|███       | 2209/7211 [09:09<16:30,  5.05it/s]

Gaps (ex-reports):  31%|███       | 2210/7211 [09:09<16:51,  4.95it/s]

Gaps (ex-reports):  31%|███       | 2211/7211 [09:10<17:02,  4.89it/s]

Gaps (ex-reports):  31%|███       | 2212/7211 [09:10<16:53,  4.93it/s]

Gaps (ex-reports):  31%|███       | 2213/7211 [09:10<17:05,  4.87it/s]

Gaps (ex-reports):  31%|███       | 2214/7211 [09:10<17:01,  4.89it/s]

Gaps (ex-reports):  31%|███       | 2215/7211 [09:10<17:12,  4.84it/s]

Gaps (ex-reports):  31%|███       | 2216/7211 [09:11<17:31,  4.75it/s]

Gaps (ex-reports):  31%|███       | 2217/7211 [09:11<17:19,  4.80it/s]

Gaps (ex-reports):  31%|███       | 2218/7211 [09:11<17:12,  4.84it/s]

Gaps (ex-reports):  31%|███       | 2219/7211 [09:11<16:53,  4.92it/s]

Gaps (ex-reports):  31%|███       | 2220/7211 [09:11<16:53,  4.93it/s]

Gaps (ex-reports):  31%|███       | 2221/7211 [09:12<16:43,  4.97it/s]

Gaps (ex-reports):  31%|███       | 2222/7211 [09:12<16:51,  4.93it/s]

Gaps (ex-reports):  31%|███       | 2223/7211 [09:12<16:43,  4.97it/s]

Gaps (ex-reports):  31%|███       | 2224/7211 [09:12<16:48,  4.95it/s]

Gaps (ex-reports):  31%|███       | 2225/7211 [09:12<19:35,  4.24it/s]

Gaps (ex-reports):  31%|███       | 2226/7211 [09:13<18:32,  4.48it/s]

Gaps (ex-reports):  31%|███       | 2227/7211 [09:13<18:07,  4.59it/s]

Gaps (ex-reports):  31%|███       | 2228/7211 [09:13<17:45,  4.68it/s]

Gaps (ex-reports):  31%|███       | 2229/7211 [09:13<17:26,  4.76it/s]

Gaps (ex-reports):  31%|███       | 2230/7211 [09:13<17:27,  4.76it/s]

Gaps (ex-reports):  31%|███       | 2231/7211 [09:14<17:14,  4.81it/s]

Gaps (ex-reports):  31%|███       | 2232/7211 [09:14<16:51,  4.92it/s]

Gaps (ex-reports):  31%|███       | 2233/7211 [09:14<17:09,  4.84it/s]

Gaps (ex-reports):  31%|███       | 2234/7211 [09:14<16:59,  4.88it/s]

Gaps (ex-reports):  31%|███       | 2235/7211 [09:14<16:36,  4.99it/s]

Gaps (ex-reports):  31%|███       | 2236/7211 [09:15<16:27,  5.04it/s]

Gaps (ex-reports):  31%|███       | 2237/7211 [09:15<16:23,  5.06it/s]

Gaps (ex-reports):  31%|███       | 2238/7211 [09:15<16:36,  4.99it/s]

Gaps (ex-reports):  31%|███       | 2239/7211 [09:15<16:24,  5.05it/s]

Gaps (ex-reports):  31%|███       | 2240/7211 [09:15<16:38,  4.98it/s]

Gaps (ex-reports):  31%|███       | 2241/7211 [09:16<16:52,  4.91it/s]

Gaps (ex-reports):  31%|███       | 2242/7211 [09:16<16:55,  4.89it/s]

Gaps (ex-reports):  31%|███       | 2243/7211 [09:16<16:59,  4.87it/s]

Gaps (ex-reports):  31%|███       | 2244/7211 [09:16<16:59,  4.87it/s]

Gaps (ex-reports):  31%|███       | 2245/7211 [09:17<16:41,  4.96it/s]

Gaps (ex-reports):  31%|███       | 2246/7211 [09:17<16:59,  4.87it/s]

Gaps (ex-reports):  31%|███       | 2247/7211 [09:17<16:41,  4.96it/s]

Gaps (ex-reports):  31%|███       | 2248/7211 [09:17<16:39,  4.96it/s]

Gaps (ex-reports):  31%|███       | 2249/7211 [09:17<16:31,  5.01it/s]

Gaps (ex-reports):  31%|███       | 2250/7211 [09:18<16:39,  4.96it/s]

Gaps (ex-reports):  31%|███       | 2251/7211 [09:18<16:51,  4.90it/s]

Gaps (ex-reports):  31%|███       | 2252/7211 [09:18<16:29,  5.01it/s]

Gaps (ex-reports):  31%|███       | 2253/7211 [09:18<16:43,  4.94it/s]

Gaps (ex-reports):  31%|███▏      | 2254/7211 [09:18<17:12,  4.80it/s]

Gaps (ex-reports):  31%|███▏      | 2255/7211 [09:19<17:37,  4.69it/s]

Gaps (ex-reports):  31%|███▏      | 2256/7211 [09:19<17:41,  4.67it/s]

Gaps (ex-reports):  31%|███▏      | 2257/7211 [09:19<17:30,  4.71it/s]

Gaps (ex-reports):  31%|███▏      | 2258/7211 [09:19<17:25,  4.74it/s]

Gaps (ex-reports):  31%|███▏      | 2259/7211 [09:19<17:20,  4.76it/s]

Gaps (ex-reports):  31%|███▏      | 2260/7211 [09:20<17:38,  4.68it/s]

Gaps (ex-reports):  31%|███▏      | 2261/7211 [09:20<17:36,  4.68it/s]

Gaps (ex-reports):  31%|███▏      | 2262/7211 [09:20<17:14,  4.78it/s]

Gaps (ex-reports):  31%|███▏      | 2263/7211 [09:20<17:10,  4.80it/s]

Gaps (ex-reports):  31%|███▏      | 2264/7211 [09:20<17:42,  4.65it/s]

Gaps (ex-reports):  31%|███▏      | 2265/7211 [09:21<17:39,  4.67it/s]

Gaps (ex-reports):  31%|███▏      | 2266/7211 [09:21<17:23,  4.74it/s]

Gaps (ex-reports):  31%|███▏      | 2267/7211 [09:21<17:12,  4.79it/s]

Gaps (ex-reports):  31%|███▏      | 2268/7211 [09:21<17:16,  4.77it/s]

Gaps (ex-reports):  31%|███▏      | 2269/7211 [09:22<17:06,  4.81it/s]

Gaps (ex-reports):  31%|███▏      | 2270/7211 [09:22<16:57,  4.85it/s]

Gaps (ex-reports):  31%|███▏      | 2271/7211 [09:22<16:50,  4.89it/s]

Gaps (ex-reports):  32%|███▏      | 2272/7211 [09:22<16:58,  4.85it/s]

Gaps (ex-reports):  32%|███▏      | 2273/7211 [09:22<16:48,  4.90it/s]

Gaps (ex-reports):  32%|███▏      | 2274/7211 [09:23<16:41,  4.93it/s]

Gaps (ex-reports):  32%|███▏      | 2275/7211 [09:23<16:48,  4.90it/s]

Gaps (ex-reports):  32%|███▏      | 2276/7211 [09:23<16:45,  4.91it/s]

Gaps (ex-reports):  32%|███▏      | 2277/7211 [09:23<16:55,  4.86it/s]

Gaps (ex-reports):  32%|███▏      | 2278/7211 [09:23<16:46,  4.90it/s]

Gaps (ex-reports):  32%|███▏      | 2279/7211 [09:24<16:31,  4.98it/s]

Gaps (ex-reports):  32%|███▏      | 2280/7211 [09:24<16:18,  5.04it/s]

Gaps (ex-reports):  32%|███▏      | 2281/7211 [09:24<16:41,  4.92it/s]

Gaps (ex-reports):  32%|███▏      | 2282/7211 [09:24<16:43,  4.91it/s]

Gaps (ex-reports):  32%|███▏      | 2283/7211 [09:24<16:47,  4.89it/s]

Gaps (ex-reports):  32%|███▏      | 2284/7211 [09:25<16:58,  4.84it/s]

Gaps (ex-reports):  32%|███▏      | 2285/7211 [09:25<17:03,  4.81it/s]

Gaps (ex-reports):  32%|███▏      | 2286/7211 [09:25<16:53,  4.86it/s]

Gaps (ex-reports):  32%|███▏      | 2287/7211 [09:25<17:11,  4.77it/s]

Gaps (ex-reports):  32%|███▏      | 2288/7211 [09:25<17:00,  4.82it/s]

Gaps (ex-reports):  32%|███▏      | 2289/7211 [09:26<17:06,  4.79it/s]

Gaps (ex-reports):  32%|███▏      | 2290/7211 [09:26<17:00,  4.82it/s]

Gaps (ex-reports):  32%|███▏      | 2291/7211 [09:26<17:03,  4.81it/s]

Gaps (ex-reports):  32%|███▏      | 2292/7211 [09:26<17:33,  4.67it/s]

Gaps (ex-reports):  32%|███▏      | 2293/7211 [09:26<17:10,  4.77it/s]

Gaps (ex-reports):  32%|███▏      | 2294/7211 [09:27<16:43,  4.90it/s]

Gaps (ex-reports):  32%|███▏      | 2295/7211 [09:27<16:35,  4.94it/s]

Gaps (ex-reports):  32%|███▏      | 2296/7211 [09:27<16:54,  4.85it/s]

Gaps (ex-reports):  32%|███▏      | 2297/7211 [09:27<16:42,  4.90it/s]

Gaps (ex-reports):  32%|███▏      | 2298/7211 [09:27<16:52,  4.85it/s]

Gaps (ex-reports):  32%|███▏      | 2299/7211 [09:28<16:40,  4.91it/s]

Gaps (ex-reports):  32%|███▏      | 2300/7211 [09:28<17:10,  4.76it/s]

Gaps (ex-reports):  32%|███▏      | 2301/7211 [09:28<17:11,  4.76it/s]

Gaps (ex-reports):  32%|███▏      | 2302/7211 [09:28<16:46,  4.88it/s]

Gaps (ex-reports):  32%|███▏      | 2303/7211 [09:29<16:39,  4.91it/s]

Gaps (ex-reports):  32%|███▏      | 2304/7211 [09:29<16:45,  4.88it/s]

Gaps (ex-reports):  32%|███▏      | 2305/7211 [09:29<16:49,  4.86it/s]

Gaps (ex-reports):  32%|███▏      | 2306/7211 [09:29<16:39,  4.91it/s]

Gaps (ex-reports):  32%|███▏      | 2307/7211 [09:29<17:07,  4.77it/s]

Gaps (ex-reports):  32%|███▏      | 2308/7211 [09:30<16:58,  4.81it/s]

Gaps (ex-reports):  32%|███▏      | 2309/7211 [09:30<17:29,  4.67it/s]

Gaps (ex-reports):  32%|███▏      | 2310/7211 [09:30<16:57,  4.81it/s]

Gaps (ex-reports):  32%|███▏      | 2311/7211 [09:30<17:23,  4.69it/s]

Gaps (ex-reports):  32%|███▏      | 2312/7211 [09:30<16:51,  4.84it/s]

Gaps (ex-reports):  32%|███▏      | 2313/7211 [09:31<16:41,  4.89it/s]

Gaps (ex-reports):  32%|███▏      | 2314/7211 [09:31<16:40,  4.89it/s]

Gaps (ex-reports):  32%|███▏      | 2315/7211 [09:31<16:36,  4.92it/s]

Gaps (ex-reports):  32%|███▏      | 2316/7211 [09:31<16:18,  5.00it/s]

Gaps (ex-reports):  32%|███▏      | 2317/7211 [09:32<23:14,  3.51it/s]

Gaps (ex-reports):  32%|███▏      | 2318/7211 [09:32<20:52,  3.91it/s]

Gaps (ex-reports):  32%|███▏      | 2319/7211 [09:32<19:33,  4.17it/s]

Gaps (ex-reports):  32%|███▏      | 2320/7211 [09:32<19:02,  4.28it/s]

Gaps (ex-reports):  32%|███▏      | 2321/7211 [09:32<18:28,  4.41it/s]

Gaps (ex-reports):  32%|███▏      | 2322/7211 [09:33<17:56,  4.54it/s]

Gaps (ex-reports):  32%|███▏      | 2323/7211 [09:33<17:43,  4.60it/s]

Gaps (ex-reports):  32%|███▏      | 2324/7211 [09:33<17:19,  4.70it/s]

Gaps (ex-reports):  32%|███▏      | 2325/7211 [09:33<16:55,  4.81it/s]

Gaps (ex-reports):  32%|███▏      | 2326/7211 [09:34<16:54,  4.82it/s]

Gaps (ex-reports):  32%|███▏      | 2327/7211 [09:34<17:35,  4.63it/s]

Gaps (ex-reports):  32%|███▏      | 2328/7211 [09:34<17:00,  4.78it/s]

Gaps (ex-reports):  32%|███▏      | 2329/7211 [09:34<16:41,  4.88it/s]

Gaps (ex-reports):  32%|███▏      | 2330/7211 [09:34<16:40,  4.88it/s]

Gaps (ex-reports):  32%|███▏      | 2331/7211 [09:35<16:22,  4.97it/s]

Gaps (ex-reports):  32%|███▏      | 2332/7211 [09:35<16:07,  5.04it/s]

Gaps (ex-reports):  32%|███▏      | 2333/7211 [09:35<16:12,  5.02it/s]

Gaps (ex-reports):  32%|███▏      | 2334/7211 [09:35<16:14,  5.01it/s]

Gaps (ex-reports):  32%|███▏      | 2335/7211 [09:35<16:27,  4.94it/s]

Gaps (ex-reports):  32%|███▏      | 2336/7211 [09:36<16:30,  4.92it/s]

Gaps (ex-reports):  32%|███▏      | 2337/7211 [09:36<16:31,  4.92it/s]

Gaps (ex-reports):  32%|███▏      | 2338/7211 [09:36<16:20,  4.97it/s]

Gaps (ex-reports):  32%|███▏      | 2339/7211 [09:36<16:02,  5.06it/s]

Gaps (ex-reports):  32%|███▏      | 2340/7211 [09:36<15:50,  5.12it/s]

Gaps (ex-reports):  32%|███▏      | 2341/7211 [09:37<15:51,  5.12it/s]

Gaps (ex-reports):  32%|███▏      | 2342/7211 [09:37<16:30,  4.92it/s]

Gaps (ex-reports):  32%|███▏      | 2343/7211 [09:37<16:46,  4.84it/s]

Gaps (ex-reports):  33%|███▎      | 2344/7211 [09:37<16:44,  4.85it/s]

Gaps (ex-reports):  33%|███▎      | 2345/7211 [09:37<16:47,  4.83it/s]

Gaps (ex-reports):  33%|███▎      | 2346/7211 [09:38<16:37,  4.88it/s]

Gaps (ex-reports):  33%|███▎      | 2347/7211 [09:38<16:34,  4.89it/s]

Gaps (ex-reports):  33%|███▎      | 2348/7211 [09:38<16:22,  4.95it/s]

Gaps (ex-reports):  33%|███▎      | 2349/7211 [09:38<16:16,  4.98it/s]

Gaps (ex-reports):  33%|███▎      | 2350/7211 [09:38<16:19,  4.96it/s]

Gaps (ex-reports):  33%|███▎      | 2351/7211 [09:39<16:25,  4.93it/s]

Gaps (ex-reports):  33%|███▎      | 2352/7211 [09:39<16:21,  4.95it/s]

Gaps (ex-reports):  33%|███▎      | 2353/7211 [09:39<16:23,  4.94it/s]

Gaps (ex-reports):  33%|███▎      | 2354/7211 [09:39<23:03,  3.51it/s]

Gaps (ex-reports):  33%|███▎      | 2355/7211 [09:40<20:52,  3.88it/s]

Gaps (ex-reports):  33%|███▎      | 2356/7211 [09:40<19:41,  4.11it/s]

Gaps (ex-reports):  33%|███▎      | 2357/7211 [09:40<19:02,  4.25it/s]

Gaps (ex-reports):  33%|███▎      | 2358/7211 [09:40<18:21,  4.41it/s]

Gaps (ex-reports):  33%|███▎      | 2359/7211 [09:40<18:02,  4.48it/s]

Gaps (ex-reports):  33%|███▎      | 2360/7211 [09:41<17:19,  4.67it/s]

Gaps (ex-reports):  33%|███▎      | 2361/7211 [09:41<16:48,  4.81it/s]

Gaps (ex-reports):  33%|███▎      | 2362/7211 [09:41<16:30,  4.89it/s]

Gaps (ex-reports):  33%|███▎      | 2363/7211 [09:41<16:44,  4.83it/s]

Gaps (ex-reports):  33%|███▎      | 2364/7211 [09:41<16:47,  4.81it/s]

Gaps (ex-reports):  33%|███▎      | 2365/7211 [09:42<16:38,  4.85it/s]

Gaps (ex-reports):  33%|███▎      | 2366/7211 [09:42<16:38,  4.85it/s]

Gaps (ex-reports):  33%|███▎      | 2367/7211 [09:42<16:51,  4.79it/s]

Gaps (ex-reports):  33%|███▎      | 2368/7211 [09:42<16:46,  4.81it/s]

Gaps (ex-reports):  33%|███▎      | 2369/7211 [09:43<16:46,  4.81it/s]

Gaps (ex-reports):  33%|███▎      | 2370/7211 [09:43<16:36,  4.86it/s]

Gaps (ex-reports):  33%|███▎      | 2371/7211 [09:43<16:20,  4.94it/s]

Gaps (ex-reports):  33%|███▎      | 2372/7211 [09:43<16:28,  4.89it/s]

Gaps (ex-reports):  33%|███▎      | 2373/7211 [09:43<16:42,  4.83it/s]

Gaps (ex-reports):  33%|███▎      | 2374/7211 [09:44<16:40,  4.84it/s]

Gaps (ex-reports):  33%|███▎      | 2375/7211 [09:44<16:56,  4.76it/s]

Gaps (ex-reports):  33%|███▎      | 2376/7211 [09:44<17:05,  4.72it/s]

Gaps (ex-reports):  33%|███▎      | 2377/7211 [09:44<16:57,  4.75it/s]

Gaps (ex-reports):  33%|███▎      | 2378/7211 [09:44<17:10,  4.69it/s]

Gaps (ex-reports):  33%|███▎      | 2379/7211 [09:45<17:12,  4.68it/s]

Gaps (ex-reports):  33%|███▎      | 2380/7211 [09:45<17:05,  4.71it/s]

Gaps (ex-reports):  33%|███▎      | 2381/7211 [09:45<16:53,  4.77it/s]

Gaps (ex-reports):  33%|███▎      | 2382/7211 [09:45<16:54,  4.76it/s]

Gaps (ex-reports):  33%|███▎      | 2383/7211 [09:45<16:52,  4.77it/s]

Gaps (ex-reports):  33%|███▎      | 2384/7211 [09:46<16:43,  4.81it/s]

Gaps (ex-reports):  33%|███▎      | 2385/7211 [09:46<16:32,  4.86it/s]

Gaps (ex-reports):  33%|███▎      | 2386/7211 [09:46<16:39,  4.83it/s]

Gaps (ex-reports):  33%|███▎      | 2387/7211 [09:46<16:15,  4.95it/s]

Gaps (ex-reports):  33%|███▎      | 2388/7211 [09:46<16:07,  4.99it/s]

Gaps (ex-reports):  33%|███▎      | 2389/7211 [09:47<16:23,  4.90it/s]

Gaps (ex-reports):  33%|███▎      | 2390/7211 [09:47<16:44,  4.80it/s]

Gaps (ex-reports):  33%|███▎      | 2391/7211 [09:50<1:18:46,  1.02it/s]

Gaps (ex-reports):  33%|███▎      | 2392/7211 [09:50<1:00:08,  1.34it/s]

Gaps (ex-reports):  33%|███▎      | 2393/7211 [09:50<47:07,  1.70it/s]

Gaps (ex-reports):  33%|███▎      | 2394/7211 [09:50<37:35,  2.14it/s]

Gaps (ex-reports):  33%|███▎      | 2395/7211 [09:50<31:06,  2.58it/s]

Gaps (ex-reports):  33%|███▎      | 2396/7211 [09:51<26:19,  3.05it/s]

Gaps (ex-reports):  33%|███▎      | 2397/7211 [09:51<23:28,  3.42it/s]

Gaps (ex-reports):  33%|███▎      | 2398/7211 [09:51<21:40,  3.70it/s]

Gaps (ex-reports):  33%|███▎      | 2399/7211 [09:51<19:46,  4.06it/s]

Gaps (ex-reports):  33%|███▎      | 2400/7211 [09:51<18:44,  4.28it/s]

Gaps (ex-reports):  33%|███▎      | 2401/7211 [09:52<18:10,  4.41it/s]

Gaps (ex-reports):  33%|███▎      | 2402/7211 [09:52<17:38,  4.54it/s]

Gaps (ex-reports):  33%|███▎      | 2403/7211 [09:52<17:24,  4.60it/s]

Gaps (ex-reports):  33%|███▎      | 2404/7211 [09:52<17:21,  4.62it/s]

Gaps (ex-reports):  33%|███▎      | 2405/7211 [09:53<17:05,  4.69it/s]

Gaps (ex-reports):  33%|███▎      | 2406/7211 [09:53<17:03,  4.70it/s]

Gaps (ex-reports):  33%|███▎      | 2407/7211 [09:53<17:02,  4.70it/s]

Gaps (ex-reports):  33%|███▎      | 2408/7211 [09:53<16:47,  4.77it/s]

Gaps (ex-reports):  33%|███▎      | 2409/7211 [09:53<16:24,  4.88it/s]

Gaps (ex-reports):  33%|███▎      | 2410/7211 [09:54<16:29,  4.85it/s]

Gaps (ex-reports):  33%|███▎      | 2411/7211 [09:54<16:31,  4.84it/s]

Gaps (ex-reports):  33%|███▎      | 2412/7211 [09:54<16:06,  4.97it/s]

Gaps (ex-reports):  33%|███▎      | 2413/7211 [09:54<16:02,  4.99it/s]

Gaps (ex-reports):  33%|███▎      | 2414/7211 [09:54<16:10,  4.94it/s]

Gaps (ex-reports):  33%|███▎      | 2415/7211 [09:55<16:23,  4.87it/s]

Gaps (ex-reports):  34%|███▎      | 2416/7211 [09:55<16:19,  4.89it/s]

Gaps (ex-reports):  34%|███▎      | 2417/7211 [09:55<16:17,  4.90it/s]

Gaps (ex-reports):  34%|███▎      | 2418/7211 [09:55<16:04,  4.97it/s]

Gaps (ex-reports):  34%|███▎      | 2419/7211 [09:55<15:48,  5.05it/s]

Gaps (ex-reports):  34%|███▎      | 2420/7211 [09:56<16:10,  4.94it/s]

Gaps (ex-reports):  34%|███▎      | 2421/7211 [09:56<15:55,  5.01it/s]

Gaps (ex-reports):  34%|███▎      | 2422/7211 [09:56<16:13,  4.92it/s]

Gaps (ex-reports):  34%|███▎      | 2423/7211 [09:56<16:18,  4.89it/s]

Gaps (ex-reports):  34%|███▎      | 2424/7211 [09:56<16:09,  4.94it/s]

Gaps (ex-reports):  34%|███▎      | 2425/7211 [09:57<15:57,  5.00it/s]

Gaps (ex-reports):  34%|███▎      | 2426/7211 [09:57<16:20,  4.88it/s]

Gaps (ex-reports):  34%|███▎      | 2427/7211 [09:57<16:01,  4.98it/s]

Gaps (ex-reports):  34%|███▎      | 2428/7211 [09:57<16:10,  4.93it/s]

Gaps (ex-reports):  34%|███▎      | 2429/7211 [09:57<16:13,  4.91it/s]

Gaps (ex-reports):  34%|███▎      | 2430/7211 [09:58<16:14,  4.91it/s]

Gaps (ex-reports):  34%|███▎      | 2431/7211 [09:58<16:07,  4.94it/s]

Gaps (ex-reports):  34%|███▎      | 2432/7211 [09:58<16:07,  4.94it/s]

Gaps (ex-reports):  34%|███▎      | 2433/7211 [09:58<16:04,  4.95it/s]

Gaps (ex-reports):  34%|███▍      | 2434/7211 [09:58<15:58,  4.98it/s]

Gaps (ex-reports):  34%|███▍      | 2435/7211 [09:59<16:13,  4.90it/s]

Gaps (ex-reports):  34%|███▍      | 2436/7211 [09:59<16:27,  4.83it/s]

Gaps (ex-reports):  34%|███▍      | 2437/7211 [09:59<16:12,  4.91it/s]

Gaps (ex-reports):  34%|███▍      | 2438/7211 [09:59<16:00,  4.97it/s]

Gaps (ex-reports):  34%|███▍      | 2439/7211 [09:59<16:01,  4.96it/s]

Gaps (ex-reports):  34%|███▍      | 2440/7211 [10:00<15:54,  5.00it/s]

Gaps (ex-reports):  34%|███▍      | 2441/7211 [10:00<16:02,  4.96it/s]

Gaps (ex-reports):  34%|███▍      | 2442/7211 [10:00<16:12,  4.91it/s]

Gaps (ex-reports):  34%|███▍      | 2443/7211 [10:00<16:18,  4.87it/s]

Gaps (ex-reports):  34%|███▍      | 2444/7211 [10:00<16:16,  4.88it/s]

Gaps (ex-reports):  34%|███▍      | 2445/7211 [10:01<16:21,  4.86it/s]

Gaps (ex-reports):  34%|███▍      | 2446/7211 [10:01<16:34,  4.79it/s]

Gaps (ex-reports):  34%|███▍      | 2447/7211 [10:01<16:36,  4.78it/s]

Gaps (ex-reports):  34%|███▍      | 2448/7211 [10:01<16:13,  4.89it/s]

Gaps (ex-reports):  34%|███▍      | 2449/7211 [10:01<16:15,  4.88it/s]

Gaps (ex-reports):  34%|███▍      | 2450/7211 [10:02<16:10,  4.91it/s]

Gaps (ex-reports):  34%|███▍      | 2451/7211 [10:02<16:24,  4.83it/s]

Gaps (ex-reports):  34%|███▍      | 2452/7211 [10:02<16:19,  4.86it/s]

Gaps (ex-reports):  34%|███▍      | 2453/7211 [10:02<16:24,  4.83it/s]

Gaps (ex-reports):  34%|███▍      | 2454/7211 [10:03<16:24,  4.83it/s]

Gaps (ex-reports):  34%|███▍      | 2455/7211 [10:03<16:09,  4.91it/s]

Gaps (ex-reports):  34%|███▍      | 2456/7211 [10:03<15:57,  4.97it/s]

Gaps (ex-reports):  34%|███▍      | 2457/7211 [10:03<15:49,  5.00it/s]

Gaps (ex-reports):  34%|███▍      | 2458/7211 [10:03<15:35,  5.08it/s]

Gaps (ex-reports):  34%|███▍      | 2459/7211 [10:04<16:06,  4.92it/s]

Gaps (ex-reports):  34%|███▍      | 2460/7211 [10:04<15:58,  4.96it/s]

Gaps (ex-reports):  34%|███▍      | 2461/7211 [10:04<16:02,  4.94it/s]

Gaps (ex-reports):  34%|███▍      | 2462/7211 [10:04<16:13,  4.88it/s]

Gaps (ex-reports):  34%|███▍      | 2463/7211 [10:04<16:21,  4.84it/s]

Gaps (ex-reports):  34%|███▍      | 2464/7211 [10:05<16:19,  4.85it/s]

Gaps (ex-reports):  34%|███▍      | 2465/7211 [10:05<16:46,  4.72it/s]

Gaps (ex-reports):  34%|███▍      | 2466/7211 [10:05<16:36,  4.76it/s]

Gaps (ex-reports):  34%|███▍      | 2467/7211 [10:05<16:32,  4.78it/s]

Gaps (ex-reports):  34%|███▍      | 2468/7211 [10:05<16:16,  4.86it/s]

Gaps (ex-reports):  34%|███▍      | 2469/7211 [10:06<16:06,  4.91it/s]

Gaps (ex-reports):  34%|███▍      | 2470/7211 [10:06<15:52,  4.98it/s]

Gaps (ex-reports):  34%|███▍      | 2471/7211 [10:06<15:55,  4.96it/s]

Gaps (ex-reports):  34%|███▍      | 2472/7211 [10:06<15:55,  4.96it/s]

Gaps (ex-reports):  34%|███▍      | 2473/7211 [10:06<16:06,  4.90it/s]

Gaps (ex-reports):  34%|███▍      | 2474/7211 [10:07<16:13,  4.87it/s]

Gaps (ex-reports):  34%|███▍      | 2475/7211 [10:07<16:39,  4.74it/s]

Gaps (ex-reports):  34%|███▍      | 2476/7211 [10:07<16:21,  4.82it/s]

Gaps (ex-reports):  34%|███▍      | 2477/7211 [10:07<16:07,  4.90it/s]

Gaps (ex-reports):  34%|███▍      | 2478/7211 [10:07<16:19,  4.83it/s]

Gaps (ex-reports):  34%|███▍      | 2479/7211 [10:08<16:09,  4.88it/s]

Gaps (ex-reports):  34%|███▍      | 2480/7211 [10:08<15:57,  4.94it/s]

Gaps (ex-reports):  34%|███▍      | 2481/7211 [10:08<15:29,  5.09it/s]

Gaps (ex-reports):  34%|███▍      | 2482/7211 [10:08<15:42,  5.02it/s]

Gaps (ex-reports):  34%|███▍      | 2483/7211 [10:08<15:44,  5.01it/s]

Gaps (ex-reports):  34%|███▍      | 2484/7211 [10:09<15:44,  5.00it/s]

Gaps (ex-reports):  34%|███▍      | 2485/7211 [10:09<16:05,  4.89it/s]

Gaps (ex-reports):  34%|███▍      | 2486/7211 [10:09<16:05,  4.89it/s]

Gaps (ex-reports):  34%|███▍      | 2487/7211 [10:09<16:24,  4.80it/s]

Gaps (ex-reports):  35%|███▍      | 2488/7211 [10:09<16:09,  4.87it/s]

Gaps (ex-reports):  35%|███▍      | 2489/7211 [10:10<15:58,  4.93it/s]

Gaps (ex-reports):  35%|███▍      | 2490/7211 [10:10<15:49,  4.97it/s]

Gaps (ex-reports):  35%|███▍      | 2491/7211 [10:10<15:51,  4.96it/s]

Gaps (ex-reports):  35%|███▍      | 2492/7211 [10:10<15:50,  4.97it/s]

Gaps (ex-reports):  35%|███▍      | 2493/7211 [10:10<15:36,  5.04it/s]

Gaps (ex-reports):  35%|███▍      | 2494/7211 [10:11<15:55,  4.93it/s]

Gaps (ex-reports):  35%|███▍      | 2495/7211 [10:11<15:52,  4.95it/s]

Gaps (ex-reports):  35%|███▍      | 2496/7211 [10:11<16:01,  4.90it/s]

Gaps (ex-reports):  35%|███▍      | 2497/7211 [10:11<15:58,  4.92it/s]

Gaps (ex-reports):  35%|███▍      | 2498/7211 [10:12<17:47,  4.42it/s]

Gaps (ex-reports):  35%|███▍      | 2499/7211 [10:12<17:02,  4.61it/s]

Gaps (ex-reports):  35%|███▍      | 2500/7211 [10:12<16:51,  4.66it/s]

Gaps (ex-reports):  35%|███▍      | 2501/7211 [10:12<16:40,  4.71it/s]

Gaps (ex-reports):  35%|███▍      | 2502/7211 [10:12<16:28,  4.77it/s]

Gaps (ex-reports):  35%|███▍      | 2503/7211 [10:13<16:48,  4.67it/s]

Gaps (ex-reports):  35%|███▍      | 2504/7211 [10:13<17:09,  4.57it/s]

Gaps (ex-reports):  35%|███▍      | 2505/7211 [10:13<17:04,  4.59it/s]

Gaps (ex-reports):  35%|███▍      | 2506/7211 [10:13<16:42,  4.69it/s]

Gaps (ex-reports):  35%|███▍      | 2507/7211 [10:13<16:27,  4.76it/s]

Gaps (ex-reports):  35%|███▍      | 2508/7211 [10:14<16:24,  4.78it/s]

Gaps (ex-reports):  35%|███▍      | 2509/7211 [10:14<16:18,  4.80it/s]

Gaps (ex-reports):  35%|███▍      | 2510/7211 [10:14<16:12,  4.83it/s]

Gaps (ex-reports):  35%|███▍      | 2511/7211 [10:14<16:05,  4.87it/s]

Gaps (ex-reports):  35%|███▍      | 2512/7211 [10:14<16:19,  4.79it/s]

Gaps (ex-reports):  35%|███▍      | 2513/7211 [10:15<16:11,  4.84it/s]

Gaps (ex-reports):  35%|███▍      | 2514/7211 [10:15<16:12,  4.83it/s]

Gaps (ex-reports):  35%|███▍      | 2515/7211 [10:15<16:18,  4.80it/s]

Gaps (ex-reports):  35%|███▍      | 2516/7211 [10:15<16:12,  4.83it/s]

Gaps (ex-reports):  35%|███▍      | 2517/7211 [10:16<15:54,  4.92it/s]

Gaps (ex-reports):  35%|███▍      | 2518/7211 [10:16<17:01,  4.60it/s]

Gaps (ex-reports):  35%|███▍      | 2519/7211 [10:16<19:25,  4.03it/s]

Gaps (ex-reports):  35%|███▍      | 2520/7211 [10:16<19:47,  3.95it/s]

Gaps (ex-reports):  35%|███▍      | 2521/7211 [10:17<19:30,  4.01it/s]

Gaps (ex-reports):  35%|███▍      | 2522/7211 [10:17<18:22,  4.25it/s]

Gaps (ex-reports):  35%|███▍      | 2523/7211 [10:17<17:39,  4.42it/s]

Gaps (ex-reports):  35%|███▌      | 2524/7211 [10:17<17:08,  4.56it/s]

Gaps (ex-reports):  35%|███▌      | 2525/7211 [10:17<16:43,  4.67it/s]

Gaps (ex-reports):  35%|███▌      | 2526/7211 [10:18<16:32,  4.72it/s]

Gaps (ex-reports):  35%|███▌      | 2527/7211 [10:18<16:35,  4.71it/s]

Gaps (ex-reports):  35%|███▌      | 2528/7211 [10:18<16:22,  4.77it/s]

Gaps (ex-reports):  35%|███▌      | 2529/7211 [10:18<16:04,  4.85it/s]

Gaps (ex-reports):  35%|███▌      | 2530/7211 [10:18<16:00,  4.88it/s]

Gaps (ex-reports):  35%|███▌      | 2531/7211 [10:19<16:06,  4.84it/s]

Gaps (ex-reports):  35%|███▌      | 2532/7211 [10:19<15:53,  4.91it/s]

Gaps (ex-reports):  35%|███▌      | 2533/7211 [10:19<15:45,  4.95it/s]

Gaps (ex-reports):  35%|███▌      | 2534/7211 [10:19<15:35,  5.00it/s]

Gaps (ex-reports):  35%|███▌      | 2535/7211 [10:19<15:41,  4.97it/s]

Gaps (ex-reports):  35%|███▌      | 2536/7211 [10:20<15:39,  4.98it/s]

Gaps (ex-reports):  35%|███▌      | 2537/7211 [10:20<16:35,  4.70it/s]

Gaps (ex-reports):  35%|███▌      | 2538/7211 [10:20<16:59,  4.58it/s]

Gaps (ex-reports):  35%|███▌      | 2539/7211 [10:20<16:37,  4.68it/s]

Gaps (ex-reports):  35%|███▌      | 2540/7211 [10:20<16:19,  4.77it/s]

Gaps (ex-reports):  35%|███▌      | 2541/7211 [10:21<16:01,  4.86it/s]

Gaps (ex-reports):  35%|███▌      | 2542/7211 [10:21<16:00,  4.86it/s]

Gaps (ex-reports):  35%|███▌      | 2543/7211 [10:21<15:57,  4.88it/s]

Gaps (ex-reports):  35%|███▌      | 2544/7211 [10:21<16:07,  4.82it/s]

Gaps (ex-reports):  35%|███▌      | 2545/7211 [10:22<16:10,  4.81it/s]

Gaps (ex-reports):  35%|███▌      | 2546/7211 [10:22<16:13,  4.79it/s]

Gaps (ex-reports):  35%|███▌      | 2547/7211 [10:22<16:08,  4.82it/s]

Gaps (ex-reports):  35%|███▌      | 2548/7211 [10:22<15:41,  4.95it/s]

Gaps (ex-reports):  35%|███▌      | 2549/7211 [10:22<15:38,  4.97it/s]

Gaps (ex-reports):  35%|███▌      | 2550/7211 [10:23<15:57,  4.87it/s]

Gaps (ex-reports):  35%|███▌      | 2551/7211 [10:23<15:41,  4.95it/s]

Gaps (ex-reports):  35%|███▌      | 2552/7211 [10:23<15:26,  5.03it/s]

Gaps (ex-reports):  35%|███▌      | 2553/7211 [10:23<15:16,  5.08it/s]

Gaps (ex-reports):  35%|███▌      | 2554/7211 [10:23<15:29,  5.01it/s]

Gaps (ex-reports):  35%|███▌      | 2555/7211 [10:24<15:29,  5.01it/s]

Gaps (ex-reports):  35%|███▌      | 2556/7211 [10:24<15:17,  5.07it/s]

Gaps (ex-reports):  35%|███▌      | 2557/7211 [10:24<15:17,  5.07it/s]

Gaps (ex-reports):  35%|███▌      | 2558/7211 [10:24<15:25,  5.03it/s]

Gaps (ex-reports):  35%|███▌      | 2559/7211 [10:24<15:41,  4.94it/s]

Gaps (ex-reports):  36%|███▌      | 2560/7211 [10:25<15:43,  4.93it/s]

Gaps (ex-reports):  36%|███▌      | 2561/7211 [10:25<15:52,  4.88it/s]

Gaps (ex-reports):  36%|███▌      | 2562/7211 [10:25<15:53,  4.88it/s]

Gaps (ex-reports):  36%|███▌      | 2563/7211 [10:25<15:39,  4.94it/s]

Gaps (ex-reports):  36%|███▌      | 2564/7211 [10:25<15:48,  4.90it/s]

Gaps (ex-reports):  36%|███▌      | 2565/7211 [10:26<15:53,  4.87it/s]

Gaps (ex-reports):  36%|███▌      | 2566/7211 [10:26<15:57,  4.85it/s]

Gaps (ex-reports):  36%|███▌      | 2567/7211 [10:26<15:59,  4.84it/s]

Gaps (ex-reports):  36%|███▌      | 2568/7211 [10:26<16:15,  4.76it/s]

Gaps (ex-reports):  36%|███▌      | 2569/7211 [10:26<16:17,  4.75it/s]

Gaps (ex-reports):  36%|███▌      | 2570/7211 [10:27<16:17,  4.75it/s]

Gaps (ex-reports):  36%|███▌      | 2571/7211 [10:27<16:45,  4.62it/s]

Gaps (ex-reports):  36%|███▌      | 2572/7211 [10:27<16:33,  4.67it/s]

Gaps (ex-reports):  36%|███▌      | 2573/7211 [10:27<16:17,  4.74it/s]

Gaps (ex-reports):  36%|███▌      | 2574/7211 [10:27<16:06,  4.80it/s]

Gaps (ex-reports):  36%|███▌      | 2575/7211 [10:28<15:47,  4.89it/s]

Gaps (ex-reports):  36%|███▌      | 2576/7211 [10:28<15:26,  5.01it/s]

Gaps (ex-reports):  36%|███▌      | 2577/7211 [10:28<15:42,  4.92it/s]

Gaps (ex-reports):  36%|███▌      | 2578/7211 [10:28<16:02,  4.82it/s]

Gaps (ex-reports):  36%|███▌      | 2579/7211 [10:28<15:52,  4.86it/s]

Gaps (ex-reports):  36%|███▌      | 2580/7211 [10:29<15:50,  4.87it/s]

Gaps (ex-reports):  36%|███▌      | 2581/7211 [10:29<16:04,  4.80it/s]

Gaps (ex-reports):  36%|███▌      | 2582/7211 [10:29<16:05,  4.79it/s]

Gaps (ex-reports):  36%|███▌      | 2583/7211 [10:29<16:05,  4.79it/s]

Gaps (ex-reports):  36%|███▌      | 2584/7211 [10:30<15:59,  4.82it/s]

Gaps (ex-reports):  36%|███▌      | 2585/7211 [10:30<16:15,  4.74it/s]

Gaps (ex-reports):  36%|███▌      | 2586/7211 [10:30<16:11,  4.76it/s]

Gaps (ex-reports):  36%|███▌      | 2587/7211 [10:30<16:12,  4.76it/s]

Gaps (ex-reports):  36%|███▌      | 2588/7211 [10:30<16:22,  4.70it/s]

Gaps (ex-reports):  36%|███▌      | 2589/7211 [10:31<17:20,  4.44it/s]

Gaps (ex-reports):  36%|███▌      | 2590/7211 [10:31<16:56,  4.55it/s]

Gaps (ex-reports):  36%|███▌      | 2591/7211 [10:31<16:29,  4.67it/s]

Gaps (ex-reports):  36%|███▌      | 2592/7211 [10:31<16:26,  4.68it/s]

Gaps (ex-reports):  36%|███▌      | 2593/7211 [10:31<16:23,  4.70it/s]

Gaps (ex-reports):  36%|███▌      | 2594/7211 [10:32<16:02,  4.80it/s]

Gaps (ex-reports):  36%|███▌      | 2595/7211 [10:32<15:45,  4.88it/s]

Gaps (ex-reports):  36%|███▌      | 2596/7211 [10:32<16:07,  4.77it/s]

Gaps (ex-reports):  36%|███▌      | 2597/7211 [10:32<16:01,  4.80it/s]

Gaps (ex-reports):  36%|███▌      | 2598/7211 [10:32<16:17,  4.72it/s]

Gaps (ex-reports):  36%|███▌      | 2599/7211 [10:33<16:01,  4.80it/s]

Gaps (ex-reports):  36%|███▌      | 2600/7211 [10:33<15:47,  4.87it/s]

Gaps (ex-reports):  36%|███▌      | 2601/7211 [10:33<15:45,  4.88it/s]

Gaps (ex-reports):  36%|███▌      | 2602/7211 [10:33<15:59,  4.80it/s]

Gaps (ex-reports):  36%|███▌      | 2603/7211 [10:34<15:50,  4.85it/s]

Gaps (ex-reports):  36%|███▌      | 2604/7211 [10:34<15:41,  4.89it/s]

Gaps (ex-reports):  36%|███▌      | 2605/7211 [10:34<15:55,  4.82it/s]

Gaps (ex-reports):  36%|███▌      | 2606/7211 [10:34<16:11,  4.74it/s]

Gaps (ex-reports):  36%|███▌      | 2607/7211 [10:34<15:56,  4.81it/s]

Gaps (ex-reports):  36%|███▌      | 2608/7211 [10:35<15:49,  4.85it/s]

Gaps (ex-reports):  36%|███▌      | 2609/7211 [10:35<15:56,  4.81it/s]

Gaps (ex-reports):  36%|███▌      | 2610/7211 [10:35<15:39,  4.90it/s]

Gaps (ex-reports):  36%|███▌      | 2611/7211 [10:35<15:27,  4.96it/s]

Gaps (ex-reports):  36%|███▌      | 2612/7211 [10:35<15:29,  4.95it/s]

Gaps (ex-reports):  36%|███▌      | 2613/7211 [10:36<33:12,  2.31it/s]

Gaps (ex-reports):  36%|███▋      | 2614/7211 [10:37<27:53,  2.75it/s]

Gaps (ex-reports):  36%|███▋      | 2615/7211 [10:37<26:08,  2.93it/s]

Gaps (ex-reports):  36%|███▋      | 2616/7211 [10:37<22:55,  3.34it/s]

Gaps (ex-reports):  36%|███▋      | 2617/7211 [10:37<20:33,  3.72it/s]

Gaps (ex-reports):  36%|███▋      | 2618/7211 [10:37<18:49,  4.06it/s]

Gaps (ex-reports):  36%|███▋      | 2619/7211 [10:38<17:37,  4.34it/s]

Gaps (ex-reports):  36%|███▋      | 2620/7211 [10:38<17:17,  4.43it/s]

Gaps (ex-reports):  36%|███▋      | 2621/7211 [10:38<16:44,  4.57it/s]

Gaps (ex-reports):  36%|███▋      | 2622/7211 [10:38<16:45,  4.56it/s]

Gaps (ex-reports):  36%|███▋      | 2623/7211 [10:38<16:02,  4.77it/s]

Gaps (ex-reports):  36%|███▋      | 2624/7211 [10:39<15:57,  4.79it/s]

Gaps (ex-reports):  36%|███▋      | 2625/7211 [10:39<15:55,  4.80it/s]

Gaps (ex-reports):  36%|███▋      | 2626/7211 [10:39<16:10,  4.72it/s]

Gaps (ex-reports):  36%|███▋      | 2627/7211 [10:39<15:41,  4.87it/s]

Gaps (ex-reports):  36%|███▋      | 2628/7211 [10:39<15:37,  4.89it/s]

Gaps (ex-reports):  36%|███▋      | 2629/7211 [10:40<15:35,  4.90it/s]

Gaps (ex-reports):  36%|███▋      | 2630/7211 [10:40<15:49,  4.82it/s]

Gaps (ex-reports):  36%|███▋      | 2631/7211 [10:40<15:54,  4.80it/s]

Gaps (ex-reports):  36%|███▋      | 2632/7211 [10:40<16:02,  4.76it/s]

Gaps (ex-reports):  37%|███▋      | 2633/7211 [10:41<16:06,  4.74it/s]

Gaps (ex-reports):  37%|███▋      | 2634/7211 [10:41<17:24,  4.38it/s]

Gaps (ex-reports):  37%|███▋      | 2635/7211 [10:41<16:47,  4.54it/s]

Gaps (ex-reports):  37%|███▋      | 2636/7211 [10:41<16:34,  4.60it/s]

Gaps (ex-reports):  37%|███▋      | 2637/7211 [10:41<16:13,  4.70it/s]

Gaps (ex-reports):  37%|███▋      | 2638/7211 [10:42<16:02,  4.75it/s]

Gaps (ex-reports):  37%|███▋      | 2639/7211 [10:42<15:39,  4.86it/s]

Gaps (ex-reports):  37%|███▋      | 2640/7211 [10:42<15:41,  4.86it/s]

Gaps (ex-reports):  37%|███▋      | 2641/7211 [10:42<15:49,  4.81it/s]

Gaps (ex-reports):  37%|███▋      | 2642/7211 [10:42<15:40,  4.86it/s]

Gaps (ex-reports):  37%|███▋      | 2643/7211 [10:43<15:46,  4.83it/s]

Gaps (ex-reports):  37%|███▋      | 2644/7211 [10:43<15:30,  4.91it/s]

Gaps (ex-reports):  37%|███▋      | 2645/7211 [10:43<15:32,  4.89it/s]

Gaps (ex-reports):  37%|███▋      | 2646/7211 [10:43<15:59,  4.76it/s]

Gaps (ex-reports):  37%|███▋      | 2647/7211 [10:43<16:07,  4.72it/s]

Gaps (ex-reports):  37%|███▋      | 2648/7211 [10:44<15:47,  4.82it/s]

Gaps (ex-reports):  37%|███▋      | 2649/7211 [10:44<15:32,  4.89it/s]

Gaps (ex-reports):  37%|███▋      | 2650/7211 [10:44<15:34,  4.88it/s]

Gaps (ex-reports):  37%|███▋      | 2651/7211 [10:44<15:27,  4.92it/s]

Gaps (ex-reports):  37%|███▋      | 2652/7211 [10:44<15:16,  4.98it/s]

Gaps (ex-reports):  37%|███▋      | 2653/7211 [10:45<15:14,  4.98it/s]

Gaps (ex-reports):  37%|███▋      | 2654/7211 [10:45<15:25,  4.93it/s]

Gaps (ex-reports):  37%|███▋      | 2655/7211 [10:45<15:34,  4.87it/s]

Gaps (ex-reports):  37%|███▋      | 2656/7211 [10:45<15:58,  4.75it/s]

Gaps (ex-reports):  37%|███▋      | 2657/7211 [10:46<15:52,  4.78it/s]

Gaps (ex-reports):  37%|███▋      | 2658/7211 [10:46<15:50,  4.79it/s]

Gaps (ex-reports):  37%|███▋      | 2659/7211 [10:46<15:45,  4.82it/s]

Gaps (ex-reports):  37%|███▋      | 2660/7211 [10:46<15:51,  4.78it/s]

Gaps (ex-reports):  37%|███▋      | 2661/7211 [10:46<15:42,  4.83it/s]

Gaps (ex-reports):  37%|███▋      | 2662/7211 [10:47<15:22,  4.93it/s]

Gaps (ex-reports):  37%|███▋      | 2663/7211 [10:47<15:06,  5.02it/s]

Gaps (ex-reports):  37%|███▋      | 2664/7211 [10:47<15:24,  4.92it/s]

Gaps (ex-reports):  37%|███▋      | 2665/7211 [10:47<15:45,  4.81it/s]

Gaps (ex-reports):  37%|███▋      | 2666/7211 [10:47<15:29,  4.89it/s]

Gaps (ex-reports):  37%|███▋      | 2667/7211 [10:48<15:47,  4.80it/s]

Gaps (ex-reports):  37%|███▋      | 2668/7211 [10:48<15:32,  4.87it/s]

Gaps (ex-reports):  37%|███▋      | 2669/7211 [10:48<15:47,  4.79it/s]

Gaps (ex-reports):  37%|███▋      | 2670/7211 [10:48<15:45,  4.80it/s]

Gaps (ex-reports):  37%|███▋      | 2671/7211 [10:48<15:45,  4.80it/s]

Gaps (ex-reports):  37%|███▋      | 2672/7211 [10:49<15:41,  4.82it/s]

Gaps (ex-reports):  37%|███▋      | 2673/7211 [10:49<15:28,  4.89it/s]

Gaps (ex-reports):  37%|███▋      | 2674/7211 [10:49<15:34,  4.86it/s]

Gaps (ex-reports):  37%|███▋      | 2675/7211 [10:49<15:44,  4.80it/s]

Gaps (ex-reports):  37%|███▋      | 2676/7211 [10:49<15:37,  4.84it/s]

Gaps (ex-reports):  37%|███▋      | 2677/7211 [10:50<15:20,  4.92it/s]

Gaps (ex-reports):  37%|███▋      | 2678/7211 [10:50<15:34,  4.85it/s]

Gaps (ex-reports):  37%|███▋      | 2679/7211 [10:50<15:26,  4.89it/s]

Gaps (ex-reports):  37%|███▋      | 2680/7211 [10:50<15:15,  4.95it/s]

Gaps (ex-reports):  37%|███▋      | 2681/7211 [10:50<15:25,  4.90it/s]

Gaps (ex-reports):  37%|███▋      | 2682/7211 [10:51<15:22,  4.91it/s]

Gaps (ex-reports):  37%|███▋      | 2683/7211 [10:51<15:05,  5.00it/s]

Gaps (ex-reports):  37%|███▋      | 2684/7211 [10:51<14:57,  5.05it/s]

Gaps (ex-reports):  37%|███▋      | 2685/7211 [10:51<15:07,  4.99it/s]

Gaps (ex-reports):  37%|███▋      | 2686/7211 [10:51<14:57,  5.04it/s]

Gaps (ex-reports):  37%|███▋      | 2687/7211 [10:52<15:05,  5.00it/s]

Gaps (ex-reports):  37%|███▋      | 2688/7211 [10:52<15:15,  4.94it/s]

Gaps (ex-reports):  37%|███▋      | 2689/7211 [10:52<15:33,  4.84it/s]

Gaps (ex-reports):  37%|███▋      | 2690/7211 [10:52<15:36,  4.83it/s]

Gaps (ex-reports):  37%|███▋      | 2691/7211 [10:52<15:29,  4.86it/s]

Gaps (ex-reports):  37%|███▋      | 2692/7211 [10:53<15:36,  4.83it/s]

Gaps (ex-reports):  37%|███▋      | 2693/7211 [10:53<15:34,  4.84it/s]

Gaps (ex-reports):  37%|███▋      | 2694/7211 [10:53<15:34,  4.83it/s]

Gaps (ex-reports):  37%|███▋      | 2695/7211 [10:53<15:13,  4.95it/s]

Gaps (ex-reports):  37%|███▋      | 2696/7211 [10:53<15:06,  4.98it/s]

Gaps (ex-reports):  37%|███▋      | 2697/7211 [10:54<15:14,  4.93it/s]

Gaps (ex-reports):  37%|███▋      | 2698/7211 [10:54<15:40,  4.80it/s]

Gaps (ex-reports):  37%|███▋      | 2699/7211 [10:54<15:15,  4.93it/s]

Gaps (ex-reports):  37%|███▋      | 2700/7211 [10:54<15:08,  4.97it/s]

Gaps (ex-reports):  37%|███▋      | 2701/7211 [10:55<15:20,  4.90it/s]

Gaps (ex-reports):  37%|███▋      | 2702/7211 [10:55<15:02,  5.00it/s]

Gaps (ex-reports):  37%|███▋      | 2703/7211 [10:55<15:10,  4.95it/s]

Gaps (ex-reports):  37%|███▋      | 2704/7211 [10:55<15:14,  4.93it/s]

Gaps (ex-reports):  38%|███▊      | 2705/7211 [10:55<15:09,  4.96it/s]

Gaps (ex-reports):  38%|███▊      | 2706/7211 [10:56<15:07,  4.97it/s]

Gaps (ex-reports):  38%|███▊      | 2707/7211 [10:56<14:43,  5.10it/s]

Gaps (ex-reports):  38%|███▊      | 2708/7211 [10:56<14:51,  5.05it/s]

Gaps (ex-reports):  38%|███▊      | 2709/7211 [10:56<15:27,  4.85it/s]

Gaps (ex-reports):  38%|███▊      | 2710/7211 [10:56<15:37,  4.80it/s]

Gaps (ex-reports):  38%|███▊      | 2711/7211 [10:57<15:45,  4.76it/s]

Gaps (ex-reports):  38%|███▊      | 2712/7211 [10:57<15:43,  4.77it/s]

Gaps (ex-reports):  38%|███▊      | 2713/7211 [10:57<15:49,  4.74it/s]

Gaps (ex-reports):  38%|███▊      | 2714/7211 [10:57<15:43,  4.77it/s]

Gaps (ex-reports):  38%|███▊      | 2715/7211 [10:57<15:45,  4.76it/s]

Gaps (ex-reports):  38%|███▊      | 2716/7211 [10:58<16:13,  4.62it/s]

Gaps (ex-reports):  38%|███▊      | 2717/7211 [10:58<16:20,  4.58it/s]

Gaps (ex-reports):  38%|███▊      | 2718/7211 [10:58<15:44,  4.76it/s]

Gaps (ex-reports):  38%|███▊      | 2719/7211 [10:58<15:48,  4.74it/s]

Gaps (ex-reports):  38%|███▊      | 2720/7211 [10:58<15:31,  4.82it/s]

Gaps (ex-reports):  38%|███▊      | 2721/7211 [10:59<15:15,  4.91it/s]

Gaps (ex-reports):  38%|███▊      | 2722/7211 [10:59<15:14,  4.91it/s]

Gaps (ex-reports):  38%|███▊      | 2723/7211 [10:59<15:02,  4.97it/s]

Gaps (ex-reports):  38%|███▊      | 2724/7211 [10:59<15:07,  4.95it/s]

Gaps (ex-reports):  38%|███▊      | 2725/7211 [10:59<15:07,  4.94it/s]

Gaps (ex-reports):  38%|███▊      | 2726/7211 [11:00<15:28,  4.83it/s]

Gaps (ex-reports):  38%|███▊      | 2727/7211 [11:00<15:14,  4.90it/s]

Gaps (ex-reports):  38%|███▊      | 2728/7211 [11:00<15:05,  4.95it/s]

Gaps (ex-reports):  38%|███▊      | 2729/7211 [11:00<15:00,  4.98it/s]

Gaps (ex-reports):  38%|███▊      | 2730/7211 [11:01<18:55,  3.94it/s]

Gaps (ex-reports):  38%|███▊      | 2731/7211 [11:01<17:50,  4.18it/s]

Gaps (ex-reports):  38%|███▊      | 2732/7211 [11:01<17:03,  4.38it/s]

Gaps (ex-reports):  38%|███▊      | 2733/7211 [11:01<16:13,  4.60it/s]

Gaps (ex-reports):  38%|███▊      | 2734/7211 [11:01<15:40,  4.76it/s]

Gaps (ex-reports):  38%|███▊      | 2735/7211 [11:02<15:33,  4.80it/s]

Gaps (ex-reports):  38%|███▊      | 2736/7211 [11:02<15:25,  4.84it/s]

Gaps (ex-reports):  38%|███▊      | 2737/7211 [11:02<16:13,  4.60it/s]

Gaps (ex-reports):  38%|███▊      | 2738/7211 [11:02<15:53,  4.69it/s]

Gaps (ex-reports):  38%|███▊      | 2739/7211 [11:03<22:22,  3.33it/s]

Gaps (ex-reports):  38%|███▊      | 2740/7211 [11:03<19:51,  3.75it/s]

Gaps (ex-reports):  38%|███▊      | 2741/7211 [11:03<18:18,  4.07it/s]

Gaps (ex-reports):  38%|███▊      | 2742/7211 [11:03<17:04,  4.36it/s]

Gaps (ex-reports):  38%|███▊      | 2743/7211 [11:04<16:19,  4.56it/s]

Gaps (ex-reports):  38%|███▊      | 2744/7211 [11:04<15:38,  4.76it/s]

Gaps (ex-reports):  38%|███▊      | 2745/7211 [11:04<15:21,  4.85it/s]

Gaps (ex-reports):  38%|███▊      | 2746/7211 [11:04<15:29,  4.80it/s]

Gaps (ex-reports):  38%|███▊      | 2747/7211 [11:04<15:24,  4.83it/s]

Gaps (ex-reports):  38%|███▊      | 2748/7211 [11:05<15:29,  4.80it/s]

Gaps (ex-reports):  38%|███▊      | 2749/7211 [11:05<15:17,  4.86it/s]

Gaps (ex-reports):  38%|███▊      | 2750/7211 [11:05<15:08,  4.91it/s]

Gaps (ex-reports):  38%|███▊      | 2751/7211 [11:05<15:21,  4.84it/s]

Gaps (ex-reports):  38%|███▊      | 2752/7211 [11:05<15:14,  4.88it/s]

Gaps (ex-reports):  38%|███▊      | 2753/7211 [11:06<15:09,  4.90it/s]

Gaps (ex-reports):  38%|███▊      | 2754/7211 [11:06<14:54,  4.99it/s]

Gaps (ex-reports):  38%|███▊      | 2755/7211 [11:06<14:54,  4.98it/s]

Gaps (ex-reports):  38%|███▊      | 2756/7211 [11:06<15:00,  4.95it/s]

Gaps (ex-reports):  38%|███▊      | 2757/7211 [11:06<15:08,  4.90it/s]

Gaps (ex-reports):  38%|███▊      | 2758/7211 [11:07<15:15,  4.86it/s]

Gaps (ex-reports):  38%|███▊      | 2759/7211 [11:07<15:39,  4.74it/s]

Gaps (ex-reports):  38%|███▊      | 2760/7211 [11:07<15:28,  4.79it/s]

Gaps (ex-reports):  38%|███▊      | 2761/7211 [11:07<15:04,  4.92it/s]

Gaps (ex-reports):  38%|███▊      | 2762/7211 [11:07<14:52,  4.98it/s]

Gaps (ex-reports):  38%|███▊      | 2763/7211 [11:09<52:45,  1.41it/s]

Gaps (ex-reports):  38%|███▊      | 2764/7211 [11:10<41:20,  1.79it/s]

Gaps (ex-reports):  38%|███▊      | 2765/7211 [11:10<33:30,  2.21it/s]

Gaps (ex-reports):  38%|███▊      | 2766/7211 [11:10<28:12,  2.63it/s]

Gaps (ex-reports):  38%|███▊      | 2767/7211 [11:10<24:04,  3.08it/s]

Gaps (ex-reports):  38%|███▊      | 2768/7211 [11:10<22:35,  3.28it/s]

Gaps (ex-reports):  38%|███▊      | 2769/7211 [11:12<41:24,  1.79it/s]

Gaps (ex-reports):  38%|███▊      | 2770/7211 [11:12<33:24,  2.22it/s]

Gaps (ex-reports):  38%|███▊      | 2771/7211 [11:12<28:06,  2.63it/s]

Gaps (ex-reports):  38%|███▊      | 2772/7211 [11:12<24:04,  3.07it/s]

Gaps (ex-reports):  38%|███▊      | 2773/7211 [11:12<21:24,  3.45it/s]

Gaps (ex-reports):  38%|███▊      | 2774/7211 [11:13<19:25,  3.81it/s]

Gaps (ex-reports):  38%|███▊      | 2775/7211 [11:13<18:06,  4.08it/s]

Gaps (ex-reports):  38%|███▊      | 2776/7211 [11:13<17:11,  4.30it/s]

Gaps (ex-reports):  39%|███▊      | 2777/7211 [11:13<16:56,  4.36it/s]

Gaps (ex-reports):  39%|███▊      | 2778/7211 [11:13<16:20,  4.52it/s]

Gaps (ex-reports):  39%|███▊      | 2779/7211 [11:14<16:05,  4.59it/s]

Gaps (ex-reports):  39%|███▊      | 2780/7211 [11:14<16:07,  4.58it/s]

Gaps (ex-reports):  39%|███▊      | 2781/7211 [11:14<16:18,  4.53it/s]

Gaps (ex-reports):  39%|███▊      | 2782/7211 [11:14<16:00,  4.61it/s]

Gaps (ex-reports):  39%|███▊      | 2783/7211 [11:14<15:40,  4.71it/s]

Gaps (ex-reports):  39%|███▊      | 2784/7211 [11:15<15:17,  4.83it/s]

Gaps (ex-reports):  39%|███▊      | 2785/7211 [11:15<15:13,  4.85it/s]

Gaps (ex-reports):  39%|███▊      | 2786/7211 [11:15<14:55,  4.94it/s]

Gaps (ex-reports):  39%|███▊      | 2787/7211 [11:15<15:02,  4.90it/s]

Gaps (ex-reports):  39%|███▊      | 2788/7211 [11:15<15:05,  4.89it/s]

Gaps (ex-reports):  39%|███▊      | 2789/7211 [11:16<15:10,  4.86it/s]

Gaps (ex-reports):  39%|███▊      | 2790/7211 [11:16<15:01,  4.91it/s]

Gaps (ex-reports):  39%|███▊      | 2791/7211 [11:16<15:06,  4.88it/s]

Gaps (ex-reports):  39%|███▊      | 2792/7211 [11:16<14:46,  4.99it/s]

Gaps (ex-reports):  39%|███▊      | 2793/7211 [11:16<15:02,  4.89it/s]

Gaps (ex-reports):  39%|███▊      | 2794/7211 [11:17<15:00,  4.90it/s]

Gaps (ex-reports):  39%|███▉      | 2795/7211 [11:17<14:41,  5.01it/s]

Gaps (ex-reports):  39%|███▉      | 2796/7211 [11:17<15:05,  4.87it/s]

Gaps (ex-reports):  39%|███▉      | 2797/7211 [11:17<15:26,  4.76it/s]

Gaps (ex-reports):  39%|███▉      | 2798/7211 [11:18<15:30,  4.74it/s]

Gaps (ex-reports):  39%|███▉      | 2799/7211 [11:18<15:14,  4.83it/s]

Gaps (ex-reports):  39%|███▉      | 2800/7211 [11:18<14:56,  4.92it/s]

Gaps (ex-reports):  39%|███▉      | 2801/7211 [11:18<15:16,  4.81it/s]

Gaps (ex-reports):  39%|███▉      | 2802/7211 [11:18<15:07,  4.86it/s]

Gaps (ex-reports):  39%|███▉      | 2803/7211 [11:19<15:09,  4.85it/s]

Gaps (ex-reports):  39%|███▉      | 2804/7211 [11:19<15:04,  4.87it/s]

Gaps (ex-reports):  39%|███▉      | 2805/7211 [11:19<15:00,  4.89it/s]

Gaps (ex-reports):  39%|███▉      | 2806/7211 [11:19<15:02,  4.88it/s]

Gaps (ex-reports):  39%|███▉      | 2807/7211 [11:19<16:31,  4.44it/s]

Gaps (ex-reports):  39%|███▉      | 2808/7211 [11:20<15:57,  4.60it/s]

Gaps (ex-reports):  39%|███▉      | 2809/7211 [11:20<15:40,  4.68it/s]

Gaps (ex-reports):  39%|███▉      | 2810/7211 [11:20<15:21,  4.78it/s]

Gaps (ex-reports):  39%|███▉      | 2811/7211 [11:20<15:00,  4.89it/s]

Gaps (ex-reports):  39%|███▉      | 2812/7211 [11:20<15:07,  4.85it/s]

Gaps (ex-reports):  39%|███▉      | 2813/7211 [11:21<15:54,  4.61it/s]

Gaps (ex-reports):  39%|███▉      | 2814/7211 [11:21<16:30,  4.44it/s]

Gaps (ex-reports):  39%|███▉      | 2815/7211 [11:21<16:34,  4.42it/s]

Gaps (ex-reports):  39%|███▉      | 2816/7211 [11:21<18:23,  3.98it/s]

Gaps (ex-reports):  39%|███▉      | 2817/7211 [11:22<20:24,  3.59it/s]

Gaps (ex-reports):  39%|███▉      | 2818/7211 [11:22<20:19,  3.60it/s]

Gaps (ex-reports):  39%|███▉      | 2819/7211 [11:22<20:11,  3.63it/s]

Gaps (ex-reports):  39%|███▉      | 2820/7211 [11:23<20:12,  3.62it/s]

Gaps (ex-reports):  39%|███▉      | 2821/7211 [11:23<20:01,  3.65it/s]

Gaps (ex-reports):  39%|███▉      | 2822/7211 [11:23<18:56,  3.86it/s]

Gaps (ex-reports):  39%|███▉      | 2823/7211 [11:23<20:23,  3.59it/s]

Gaps (ex-reports):  39%|███▉      | 2824/7211 [11:24<20:14,  3.61it/s]

Gaps (ex-reports):  39%|███▉      | 2825/7211 [11:24<20:11,  3.62it/s]

Gaps (ex-reports):  39%|███▉      | 2826/7211 [11:24<19:57,  3.66it/s]

Gaps (ex-reports):  39%|███▉      | 2827/7211 [11:25<19:58,  3.66it/s]

Gaps (ex-reports):  39%|███▉      | 2828/7211 [11:25<19:00,  3.84it/s]

Gaps (ex-reports):  39%|███▉      | 2829/7211 [11:25<17:48,  4.10it/s]

Gaps (ex-reports):  39%|███▉      | 2830/7211 [11:25<16:54,  4.32it/s]

Gaps (ex-reports):  39%|███▉      | 2831/7211 [11:25<16:12,  4.50it/s]

Gaps (ex-reports):  39%|███▉      | 2832/7211 [11:26<15:43,  4.64it/s]

Gaps (ex-reports):  39%|███▉      | 2833/7211 [11:26<15:43,  4.64it/s]

Gaps (ex-reports):  39%|███▉      | 2834/7211 [11:26<15:46,  4.62it/s]

Gaps (ex-reports):  39%|███▉      | 2835/7211 [11:26<15:42,  4.64it/s]

Gaps (ex-reports):  39%|███▉      | 2836/7211 [11:26<15:34,  4.68it/s]

Gaps (ex-reports):  39%|███▉      | 2837/7211 [11:27<15:30,  4.70it/s]

Gaps (ex-reports):  39%|███▉      | 2838/7211 [11:27<15:27,  4.71it/s]

Gaps (ex-reports):  39%|███▉      | 2839/7211 [11:27<15:52,  4.59it/s]

Gaps (ex-reports):  39%|███▉      | 2840/7211 [11:27<15:54,  4.58it/s]

Gaps (ex-reports):  39%|███▉      | 2841/7211 [11:28<15:40,  4.65it/s]

Gaps (ex-reports):  39%|███▉      | 2842/7211 [11:28<15:31,  4.69it/s]

Gaps (ex-reports):  39%|███▉      | 2843/7211 [11:28<14:59,  4.85it/s]

Gaps (ex-reports):  39%|███▉      | 2844/7211 [11:28<14:56,  4.87it/s]

Gaps (ex-reports):  39%|███▉      | 2845/7211 [11:28<15:17,  4.76it/s]

Gaps (ex-reports):  39%|███▉      | 2846/7211 [11:29<15:28,  4.70it/s]

Gaps (ex-reports):  39%|███▉      | 2847/7211 [11:29<15:12,  4.78it/s]

Gaps (ex-reports):  39%|███▉      | 2848/7211 [11:29<15:09,  4.80it/s]

Gaps (ex-reports):  40%|███▉      | 2849/7211 [11:29<15:16,  4.76it/s]

Gaps (ex-reports):  40%|███▉      | 2850/7211 [11:29<15:15,  4.76it/s]

Gaps (ex-reports):  40%|███▉      | 2851/7211 [11:30<14:59,  4.85it/s]

Gaps (ex-reports):  40%|███▉      | 2852/7211 [11:30<14:38,  4.96it/s]

Gaps (ex-reports):  40%|███▉      | 2853/7211 [11:30<14:41,  4.94it/s]

Gaps (ex-reports):  40%|███▉      | 2854/7211 [11:30<14:52,  4.88it/s]

Gaps (ex-reports):  40%|███▉      | 2855/7211 [11:30<14:48,  4.90it/s]

Gaps (ex-reports):  40%|███▉      | 2856/7211 [11:31<14:54,  4.87it/s]

Gaps (ex-reports):  40%|███▉      | 2857/7211 [11:31<15:09,  4.79it/s]

Gaps (ex-reports):  40%|███▉      | 2858/7211 [11:31<15:03,  4.82it/s]

Gaps (ex-reports):  40%|███▉      | 2859/7211 [11:31<14:51,  4.88it/s]

Gaps (ex-reports):  40%|███▉      | 2860/7211 [11:31<14:34,  4.97it/s]

Gaps (ex-reports):  40%|███▉      | 2861/7211 [11:32<14:41,  4.93it/s]

Gaps (ex-reports):  40%|███▉      | 2862/7211 [11:32<14:42,  4.93it/s]

Gaps (ex-reports):  40%|███▉      | 2863/7211 [11:32<15:02,  4.82it/s]

Gaps (ex-reports):  40%|███▉      | 2864/7211 [11:32<15:01,  4.82it/s]

Gaps (ex-reports):  40%|███▉      | 2865/7211 [11:32<15:23,  4.71it/s]

Gaps (ex-reports):  40%|███▉      | 2866/7211 [11:33<15:12,  4.76it/s]

Gaps (ex-reports):  40%|███▉      | 2867/7211 [11:33<14:47,  4.89it/s]

Gaps (ex-reports):  40%|███▉      | 2868/7211 [11:33<14:42,  4.92it/s]

Gaps (ex-reports):  40%|███▉      | 2869/7211 [11:33<14:40,  4.93it/s]

Gaps (ex-reports):  40%|███▉      | 2870/7211 [11:33<14:53,  4.86it/s]

Gaps (ex-reports):  40%|███▉      | 2871/7211 [11:34<15:01,  4.81it/s]

Gaps (ex-reports):  40%|███▉      | 2872/7211 [11:34<14:49,  4.88it/s]

Gaps (ex-reports):  40%|███▉      | 2873/7211 [11:34<15:04,  4.80it/s]

Gaps (ex-reports):  40%|███▉      | 2874/7211 [11:34<14:48,  4.88it/s]

Gaps (ex-reports):  40%|███▉      | 2875/7211 [11:35<14:53,  4.85it/s]

Gaps (ex-reports):  40%|███▉      | 2876/7211 [11:35<14:59,  4.82it/s]

Gaps (ex-reports):  40%|███▉      | 2877/7211 [11:35<14:38,  4.94it/s]

Gaps (ex-reports):  40%|███▉      | 2878/7211 [11:35<14:50,  4.87it/s]

Gaps (ex-reports):  40%|███▉      | 2879/7211 [11:35<14:52,  4.85it/s]

Gaps (ex-reports):  40%|███▉      | 2880/7211 [11:36<15:07,  4.77it/s]

Gaps (ex-reports):  40%|███▉      | 2881/7211 [11:36<15:14,  4.73it/s]

Gaps (ex-reports):  40%|███▉      | 2882/7211 [11:36<15:08,  4.77it/s]

Gaps (ex-reports):  40%|███▉      | 2883/7211 [11:36<14:51,  4.85it/s]

Gaps (ex-reports):  40%|███▉      | 2884/7211 [11:36<14:54,  4.84it/s]

Gaps (ex-reports):  40%|████      | 2885/7211 [11:37<14:51,  4.85it/s]

Gaps (ex-reports):  40%|████      | 2886/7211 [11:37<14:53,  4.84it/s]

Gaps (ex-reports):  40%|████      | 2887/7211 [11:53<6:03:46,  5.05s/it]

Gaps (ex-reports):  40%|████      | 2888/7211 [11:53<4:18:47,  3.59s/it]

Gaps (ex-reports):  40%|████      | 2889/7211 [11:54<3:05:32,  2.58s/it]

Gaps (ex-reports):  40%|████      | 2890/7211 [11:54<2:14:16,  1.86s/it]

Gaps (ex-reports):  40%|████      | 2891/7211 [11:54<1:38:26,  1.37s/it]

Gaps (ex-reports):  40%|████      | 2892/7211 [11:54<1:13:11,  1.02s/it]

Gaps (ex-reports):  40%|████      | 2893/7211 [11:54<55:40,  1.29it/s]

Gaps (ex-reports):  40%|████      | 2894/7211 [11:55<43:30,  1.65it/s]

Gaps (ex-reports):  40%|████      | 2895/7211 [11:55<34:35,  2.08it/s]

Gaps (ex-reports):  40%|████      | 2896/7211 [11:55<28:35,  2.52it/s]

Gaps (ex-reports):  40%|████      | 2897/7211 [11:55<24:16,  2.96it/s]

Gaps (ex-reports):  40%|████      | 2898/7211 [11:55<21:49,  3.29it/s]

Gaps (ex-reports):  40%|████      | 2899/7211 [11:56<19:30,  3.68it/s]

Gaps (ex-reports):  40%|████      | 2900/7211 [11:56<18:14,  3.94it/s]

Gaps (ex-reports):  40%|████      | 2901/7211 [11:56<17:17,  4.16it/s]

Gaps (ex-reports):  40%|████      | 2902/7211 [11:56<16:30,  4.35it/s]

Gaps (ex-reports):  40%|████      | 2903/7211 [11:56<15:58,  4.50it/s]

Gaps (ex-reports):  40%|████      | 2904/7211 [11:57<15:17,  4.69it/s]

Gaps (ex-reports):  40%|████      | 2905/7211 [11:57<15:32,  4.62it/s]

Gaps (ex-reports):  40%|████      | 2906/7211 [11:57<16:26,  4.36it/s]

Gaps (ex-reports):  40%|████      | 2907/7211 [11:57<15:56,  4.50it/s]

Gaps (ex-reports):  40%|████      | 2908/7211 [11:58<15:43,  4.56it/s]

Gaps (ex-reports):  40%|████      | 2909/7211 [11:58<15:16,  4.69it/s]

Gaps (ex-reports):  40%|████      | 2910/7211 [11:58<15:15,  4.70it/s]

Gaps (ex-reports):  40%|████      | 2911/7211 [11:58<14:56,  4.80it/s]

Gaps (ex-reports):  40%|████      | 2912/7211 [11:58<14:49,  4.83it/s]

Gaps (ex-reports):  40%|████      | 2913/7211 [11:59<14:55,  4.80it/s]

Gaps (ex-reports):  40%|████      | 2914/7211 [11:59<14:47,  4.84it/s]

Gaps (ex-reports):  40%|████      | 2915/7211 [11:59<14:31,  4.93it/s]

Gaps (ex-reports):  40%|████      | 2916/7211 [11:59<14:31,  4.93it/s]

Gaps (ex-reports):  40%|████      | 2917/7211 [11:59<14:26,  4.95it/s]

Gaps (ex-reports):  40%|████      | 2918/7211 [12:00<14:41,  4.87it/s]

Gaps (ex-reports):  40%|████      | 2919/7211 [12:00<14:44,  4.85it/s]

Gaps (ex-reports):  40%|████      | 2920/7211 [12:00<14:41,  4.87it/s]

Gaps (ex-reports):  41%|████      | 2921/7211 [12:00<14:43,  4.86it/s]

Gaps (ex-reports):  41%|████      | 2922/7211 [12:00<14:28,  4.94it/s]

Gaps (ex-reports):  41%|████      | 2923/7211 [12:01<14:15,  5.01it/s]

Gaps (ex-reports):  41%|████      | 2924/7211 [12:01<14:17,  5.00it/s]

Gaps (ex-reports):  41%|████      | 2925/7211 [12:01<14:50,  4.81it/s]

Gaps (ex-reports):  41%|████      | 2926/7211 [12:01<14:29,  4.93it/s]

Gaps (ex-reports):  41%|████      | 2927/7211 [12:01<14:14,  5.01it/s]

Gaps (ex-reports):  41%|████      | 2928/7211 [12:02<14:19,  4.98it/s]

Gaps (ex-reports):  41%|████      | 2929/7211 [12:02<14:25,  4.95it/s]

Gaps (ex-reports):  41%|████      | 2930/7211 [12:02<14:23,  4.96it/s]

Gaps (ex-reports):  41%|████      | 2931/7211 [12:02<14:31,  4.91it/s]

Gaps (ex-reports):  41%|████      | 2932/7211 [12:02<14:34,  4.89it/s]

Gaps (ex-reports):  41%|████      | 2933/7211 [12:03<14:31,  4.91it/s]

Gaps (ex-reports):  41%|████      | 2934/7211 [12:03<14:21,  4.97it/s]

Gaps (ex-reports):  41%|████      | 2935/7211 [12:03<14:24,  4.94it/s]

Gaps (ex-reports):  41%|████      | 2936/7211 [12:03<14:34,  4.89it/s]

Gaps (ex-reports):  41%|████      | 2937/7211 [12:03<14:25,  4.94it/s]

Gaps (ex-reports):  41%|████      | 2938/7211 [12:04<14:48,  4.81it/s]

Gaps (ex-reports):  41%|████      | 2939/7211 [12:04<22:20,  3.19it/s]

Gaps (ex-reports):  41%|████      | 2940/7211 [12:04<19:44,  3.61it/s]

Gaps (ex-reports):  41%|████      | 2941/7211 [12:05<18:20,  3.88it/s]

Gaps (ex-reports):  41%|████      | 2942/7211 [12:05<17:17,  4.11it/s]

Gaps (ex-reports):  41%|████      | 2943/7211 [12:05<16:13,  4.39it/s]

Gaps (ex-reports):  41%|████      | 2944/7211 [12:05<15:57,  4.46it/s]

Gaps (ex-reports):  41%|████      | 2945/7211 [12:05<15:28,  4.60it/s]

Gaps (ex-reports):  41%|████      | 2946/7211 [12:06<15:16,  4.65it/s]

Gaps (ex-reports):  41%|████      | 2947/7211 [12:06<15:18,  4.64it/s]

Gaps (ex-reports):  41%|████      | 2948/7211 [12:06<15:03,  4.72it/s]

Gaps (ex-reports):  41%|████      | 2949/7211 [12:06<14:55,  4.76it/s]

Gaps (ex-reports):  41%|████      | 2950/7211 [12:06<14:51,  4.78it/s]

Gaps (ex-reports):  41%|████      | 2951/7211 [12:07<14:47,  4.80it/s]

Gaps (ex-reports):  41%|████      | 2952/7211 [12:07<14:50,  4.78it/s]

Gaps (ex-reports):  41%|████      | 2953/7211 [12:07<15:16,  4.64it/s]

Gaps (ex-reports):  41%|████      | 2954/7211 [12:07<15:10,  4.67it/s]

Gaps (ex-reports):  41%|████      | 2955/7211 [12:08<15:01,  4.72it/s]

Gaps (ex-reports):  41%|████      | 2956/7211 [12:08<14:44,  4.81it/s]

Gaps (ex-reports):  41%|████      | 2957/7211 [12:08<14:56,  4.75it/s]

Gaps (ex-reports):  41%|████      | 2958/7211 [12:08<14:49,  4.78it/s]

Gaps (ex-reports):  41%|████      | 2959/7211 [12:08<14:54,  4.75it/s]

Gaps (ex-reports):  41%|████      | 2960/7211 [12:09<14:52,  4.77it/s]

Gaps (ex-reports):  41%|████      | 2961/7211 [12:09<14:33,  4.86it/s]

Gaps (ex-reports):  41%|████      | 2962/7211 [12:09<14:36,  4.85it/s]

Gaps (ex-reports):  41%|████      | 2963/7211 [12:09<14:46,  4.79it/s]

Gaps (ex-reports):  41%|████      | 2964/7211 [12:09<14:39,  4.83it/s]

Gaps (ex-reports):  41%|████      | 2965/7211 [12:10<14:39,  4.83it/s]

Gaps (ex-reports):  41%|████      | 2966/7211 [12:10<14:35,  4.85it/s]

Gaps (ex-reports):  41%|████      | 2967/7211 [12:10<14:33,  4.86it/s]

Gaps (ex-reports):  41%|████      | 2968/7211 [12:10<14:23,  4.91it/s]

Gaps (ex-reports):  41%|████      | 2969/7211 [12:10<14:31,  4.87it/s]

Gaps (ex-reports):  41%|████      | 2970/7211 [12:11<14:25,  4.90it/s]

Gaps (ex-reports):  41%|████      | 2971/7211 [12:11<14:07,  5.00it/s]

Gaps (ex-reports):  41%|████      | 2972/7211 [12:11<13:57,  5.06it/s]

Gaps (ex-reports):  41%|████      | 2973/7211 [12:11<13:54,  5.08it/s]

Gaps (ex-reports):  41%|████      | 2974/7211 [12:11<14:10,  4.98it/s]

Gaps (ex-reports):  41%|████▏     | 2975/7211 [12:12<14:14,  4.96it/s]

Gaps (ex-reports):  41%|████▏     | 2976/7211 [12:12<14:34,  4.84it/s]

Gaps (ex-reports):  41%|████▏     | 2977/7211 [12:12<14:34,  4.84it/s]

Gaps (ex-reports):  41%|████▏     | 2978/7211 [12:12<14:24,  4.90it/s]

Gaps (ex-reports):  41%|████▏     | 2979/7211 [12:12<14:16,  4.94it/s]

Gaps (ex-reports):  41%|████▏     | 2980/7211 [12:13<14:32,  4.85it/s]

Gaps (ex-reports):  41%|████▏     | 2981/7211 [12:13<14:26,  4.88it/s]

Gaps (ex-reports):  41%|████▏     | 2982/7211 [12:13<14:16,  4.94it/s]

Gaps (ex-reports):  41%|████▏     | 2983/7211 [12:13<14:08,  4.98it/s]

Gaps (ex-reports):  41%|████▏     | 2984/7211 [12:13<14:24,  4.89it/s]

Gaps (ex-reports):  41%|████▏     | 2985/7211 [12:14<14:22,  4.90it/s]

Gaps (ex-reports):  41%|████▏     | 2986/7211 [12:14<14:37,  4.81it/s]

Gaps (ex-reports):  41%|████▏     | 2987/7211 [12:14<15:37,  4.50it/s]

Gaps (ex-reports):  41%|████▏     | 2988/7211 [12:14<14:54,  4.72it/s]

Gaps (ex-reports):  41%|████▏     | 2989/7211 [12:15<14:49,  4.75it/s]

Gaps (ex-reports):  41%|████▏     | 2990/7211 [12:15<15:03,  4.67it/s]

Gaps (ex-reports):  41%|████▏     | 2991/7211 [12:15<14:39,  4.80it/s]

Gaps (ex-reports):  41%|████▏     | 2992/7211 [12:15<14:41,  4.79it/s]

Gaps (ex-reports):  42%|████▏     | 2993/7211 [12:15<14:15,  4.93it/s]

Gaps (ex-reports):  42%|████▏     | 2994/7211 [12:16<14:10,  4.96it/s]

Gaps (ex-reports):  42%|████▏     | 2995/7211 [12:16<14:15,  4.93it/s]

Gaps (ex-reports):  42%|████▏     | 2996/7211 [12:16<14:05,  4.98it/s]

Gaps (ex-reports):  42%|████▏     | 2997/7211 [12:16<14:03,  4.99it/s]

Gaps (ex-reports):  42%|████▏     | 2998/7211 [12:16<14:22,  4.89it/s]

Gaps (ex-reports):  42%|████▏     | 2999/7211 [12:17<14:31,  4.83it/s]

Gaps (ex-reports):  42%|████▏     | 3000/7211 [12:17<14:20,  4.89it/s]

Gaps (ex-reports):  42%|████▏     | 3001/7211 [12:17<14:27,  4.85it/s]

Gaps (ex-reports):  42%|████▏     | 3002/7211 [12:17<14:23,  4.88it/s]

Gaps (ex-reports):  42%|████▏     | 3003/7211 [12:17<14:07,  4.97it/s]

Gaps (ex-reports):  42%|████▏     | 3004/7211 [12:18<14:30,  4.83it/s]

Gaps (ex-reports):  42%|████▏     | 3005/7211 [12:18<14:19,  4.90it/s]

Gaps (ex-reports):  42%|████▏     | 3006/7211 [12:18<14:35,  4.81it/s]

Gaps (ex-reports):  42%|████▏     | 3007/7211 [12:18<14:50,  4.72it/s]

Gaps (ex-reports):  42%|████▏     | 3008/7211 [12:18<14:35,  4.80it/s]

Gaps (ex-reports):  42%|████▏     | 3009/7211 [12:19<14:21,  4.88it/s]

Gaps (ex-reports):  42%|████▏     | 3010/7211 [12:19<14:40,  4.77it/s]

Gaps (ex-reports):  42%|████▏     | 3011/7211 [12:19<14:30,  4.82it/s]

Gaps (ex-reports):  42%|████▏     | 3012/7211 [12:19<14:17,  4.90it/s]

Gaps (ex-reports):  42%|████▏     | 3013/7211 [12:19<14:06,  4.96it/s]

Gaps (ex-reports):  42%|████▏     | 3014/7211 [12:20<14:15,  4.90it/s]

Gaps (ex-reports):  42%|████▏     | 3015/7211 [12:20<14:18,  4.89it/s]

Gaps (ex-reports):  42%|████▏     | 3016/7211 [12:20<14:10,  4.94it/s]

Gaps (ex-reports):  42%|████▏     | 3017/7211 [12:20<14:24,  4.85it/s]

Gaps (ex-reports):  42%|████▏     | 3018/7211 [12:20<14:26,  4.84it/s]

Gaps (ex-reports):  42%|████▏     | 3019/7211 [12:21<14:20,  4.87it/s]

Gaps (ex-reports):  42%|████▏     | 3020/7211 [12:21<14:23,  4.86it/s]

Gaps (ex-reports):  42%|████▏     | 3021/7211 [12:21<14:45,  4.73it/s]

Gaps (ex-reports):  42%|████▏     | 3022/7211 [12:21<14:40,  4.76it/s]

Gaps (ex-reports):  42%|████▏     | 3023/7211 [12:21<14:33,  4.79it/s]

Gaps (ex-reports):  42%|████▏     | 3024/7211 [12:22<14:32,  4.80it/s]

Gaps (ex-reports):  42%|████▏     | 3025/7211 [12:22<14:12,  4.91it/s]

Gaps (ex-reports):  42%|████▏     | 3026/7211 [12:22<14:30,  4.81it/s]

Gaps (ex-reports):  42%|████▏     | 3027/7211 [12:22<14:13,  4.90it/s]

Gaps (ex-reports):  42%|████▏     | 3028/7211 [12:23<14:18,  4.87it/s]

Gaps (ex-reports):  42%|████▏     | 3029/7211 [12:23<14:07,  4.94it/s]

Gaps (ex-reports):  42%|████▏     | 3030/7211 [12:23<14:09,  4.92it/s]

Gaps (ex-reports):  42%|████▏     | 3031/7211 [12:23<14:20,  4.86it/s]

Gaps (ex-reports):  42%|████▏     | 3032/7211 [12:23<14:01,  4.97it/s]

Gaps (ex-reports):  42%|████▏     | 3033/7211 [12:24<13:57,  4.99it/s]

Gaps (ex-reports):  42%|████▏     | 3034/7211 [12:24<14:12,  4.90it/s]

Gaps (ex-reports):  42%|████▏     | 3035/7211 [12:24<13:54,  5.00it/s]

Gaps (ex-reports):  42%|████▏     | 3036/7211 [12:24<14:15,  4.88it/s]

Gaps (ex-reports):  42%|████▏     | 3037/7211 [12:24<14:16,  4.87it/s]

Gaps (ex-reports):  42%|████▏     | 3038/7211 [12:25<14:20,  4.85it/s]

Gaps (ex-reports):  42%|████▏     | 3039/7211 [12:25<14:21,  4.84it/s]

Gaps (ex-reports):  42%|████▏     | 3040/7211 [12:25<14:29,  4.80it/s]

Gaps (ex-reports):  42%|████▏     | 3041/7211 [12:25<14:49,  4.69it/s]

Gaps (ex-reports):  42%|████▏     | 3042/7211 [12:25<14:45,  4.71it/s]

Gaps (ex-reports):  42%|████▏     | 3043/7211 [12:26<14:20,  4.84it/s]

Gaps (ex-reports):  42%|████▏     | 3044/7211 [12:26<14:22,  4.83it/s]

Gaps (ex-reports):  42%|████▏     | 3045/7211 [12:26<14:18,  4.86it/s]

Gaps (ex-reports):  42%|████▏     | 3046/7211 [12:26<14:32,  4.77it/s]

Gaps (ex-reports):  42%|████▏     | 3047/7211 [12:26<14:17,  4.85it/s]

Gaps (ex-reports):  42%|████▏     | 3048/7211 [12:27<14:18,  4.85it/s]

Gaps (ex-reports):  42%|████▏     | 3049/7211 [12:27<14:30,  4.78it/s]

Gaps (ex-reports):  42%|████▏     | 3050/7211 [12:27<14:17,  4.85it/s]

Gaps (ex-reports):  42%|████▏     | 3051/7211 [12:27<13:59,  4.95it/s]

Gaps (ex-reports):  42%|████▏     | 3052/7211 [12:27<14:05,  4.92it/s]

Gaps (ex-reports):  42%|████▏     | 3053/7211 [12:28<14:16,  4.86it/s]

Gaps (ex-reports):  42%|████▏     | 3054/7211 [12:28<14:30,  4.78it/s]

Gaps (ex-reports):  42%|████▏     | 3055/7211 [12:28<14:12,  4.87it/s]

Gaps (ex-reports):  42%|████▏     | 3056/7211 [12:28<14:20,  4.83it/s]

Gaps (ex-reports):  42%|████▏     | 3057/7211 [12:28<14:23,  4.81it/s]

Gaps (ex-reports):  42%|████▏     | 3058/7211 [12:29<14:25,  4.80it/s]

Gaps (ex-reports):  42%|████▏     | 3059/7211 [12:29<15:53,  4.35it/s]

Gaps (ex-reports):  42%|████▏     | 3060/7211 [12:29<16:43,  4.13it/s]

Gaps (ex-reports):  42%|████▏     | 3061/7211 [12:30<17:39,  3.92it/s]

Gaps (ex-reports):  42%|████▏     | 3062/7211 [12:30<17:04,  4.05it/s]

Gaps (ex-reports):  42%|████▏     | 3063/7211 [12:30<16:21,  4.23it/s]

Gaps (ex-reports):  42%|████▏     | 3064/7211 [12:30<15:48,  4.37it/s]

Gaps (ex-reports):  43%|████▎     | 3065/7211 [12:30<15:15,  4.53it/s]

Gaps (ex-reports):  43%|████▎     | 3066/7211 [12:31<15:04,  4.58it/s]

Gaps (ex-reports):  43%|████▎     | 3067/7211 [12:31<15:00,  4.60it/s]

Gaps (ex-reports):  43%|████▎     | 3068/7211 [12:31<14:44,  4.68it/s]

Gaps (ex-reports):  43%|████▎     | 3069/7211 [12:31<14:38,  4.72it/s]

Gaps (ex-reports):  43%|████▎     | 3070/7211 [12:31<14:31,  4.75it/s]

Gaps (ex-reports):  43%|████▎     | 3071/7211 [12:32<14:22,  4.80it/s]

Gaps (ex-reports):  43%|████▎     | 3072/7211 [12:32<14:17,  4.83it/s]

Gaps (ex-reports):  43%|████▎     | 3073/7211 [12:32<14:17,  4.83it/s]

Gaps (ex-reports):  43%|████▎     | 3074/7211 [12:32<14:17,  4.83it/s]

Gaps (ex-reports):  43%|████▎     | 3075/7211 [12:32<14:03,  4.90it/s]

Gaps (ex-reports):  43%|████▎     | 3076/7211 [12:33<14:07,  4.88it/s]

Gaps (ex-reports):  43%|████▎     | 3077/7211 [12:33<13:51,  4.97it/s]

Gaps (ex-reports):  43%|████▎     | 3078/7211 [12:33<14:01,  4.91it/s]

Gaps (ex-reports):  43%|████▎     | 3079/7211 [12:33<14:18,  4.81it/s]

Gaps (ex-reports):  43%|████▎     | 3080/7211 [12:33<14:03,  4.90it/s]

Gaps (ex-reports):  43%|████▎     | 3081/7211 [12:34<14:05,  4.88it/s]

Gaps (ex-reports):  43%|████▎     | 3082/7211 [12:34<13:57,  4.93it/s]

Gaps (ex-reports):  43%|████▎     | 3083/7211 [12:34<14:36,  4.71it/s]

Gaps (ex-reports):  43%|████▎     | 3084/7211 [12:34<14:13,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3085/7211 [12:35<14:13,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3086/7211 [12:35<14:10,  4.85it/s]

Gaps (ex-reports):  43%|████▎     | 3087/7211 [12:35<13:53,  4.95it/s]

Gaps (ex-reports):  43%|████▎     | 3088/7211 [12:35<13:47,  4.98it/s]

Gaps (ex-reports):  43%|████▎     | 3089/7211 [12:35<14:05,  4.88it/s]

Gaps (ex-reports):  43%|████▎     | 3090/7211 [12:36<14:22,  4.78it/s]

Gaps (ex-reports):  43%|████▎     | 3091/7211 [12:36<14:17,  4.81it/s]

Gaps (ex-reports):  43%|████▎     | 3092/7211 [12:36<14:24,  4.76it/s]

Gaps (ex-reports):  43%|████▎     | 3093/7211 [12:36<13:59,  4.90it/s]

Gaps (ex-reports):  43%|████▎     | 3094/7211 [12:36<13:54,  4.93it/s]

Gaps (ex-reports):  43%|████▎     | 3095/7211 [12:37<13:56,  4.92it/s]

Gaps (ex-reports):  43%|████▎     | 3096/7211 [12:37<13:53,  4.93it/s]

Gaps (ex-reports):  43%|████▎     | 3097/7211 [12:37<13:44,  4.99it/s]

Gaps (ex-reports):  43%|████▎     | 3098/7211 [12:37<14:00,  4.89it/s]

Gaps (ex-reports):  43%|████▎     | 3099/7211 [12:37<13:52,  4.94it/s]

Gaps (ex-reports):  43%|████▎     | 3100/7211 [12:38<13:46,  4.97it/s]

Gaps (ex-reports):  43%|████▎     | 3101/7211 [12:38<13:58,  4.90it/s]

Gaps (ex-reports):  43%|████▎     | 3102/7211 [12:38<14:08,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3103/7211 [12:38<13:55,  4.92it/s]

Gaps (ex-reports):  43%|████▎     | 3104/7211 [12:38<13:41,  5.00it/s]

Gaps (ex-reports):  43%|████▎     | 3105/7211 [12:39<14:15,  4.80it/s]

Gaps (ex-reports):  43%|████▎     | 3106/7211 [12:39<14:25,  4.74it/s]

Gaps (ex-reports):  43%|████▎     | 3107/7211 [12:39<14:07,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3108/7211 [12:39<13:47,  4.96it/s]

Gaps (ex-reports):  43%|████▎     | 3109/7211 [12:39<13:47,  4.96it/s]

Gaps (ex-reports):  43%|████▎     | 3110/7211 [12:40<13:40,  5.00it/s]

Gaps (ex-reports):  43%|████▎     | 3111/7211 [12:40<13:50,  4.94it/s]

Gaps (ex-reports):  43%|████▎     | 3112/7211 [12:40<13:49,  4.94it/s]

Gaps (ex-reports):  43%|████▎     | 3113/7211 [12:40<13:48,  4.95it/s]

Gaps (ex-reports):  43%|████▎     | 3114/7211 [12:40<13:35,  5.02it/s]

Gaps (ex-reports):  43%|████▎     | 3115/7211 [12:41<13:59,  4.88it/s]

Gaps (ex-reports):  43%|████▎     | 3116/7211 [12:41<14:08,  4.83it/s]

Gaps (ex-reports):  43%|████▎     | 3117/7211 [12:41<14:08,  4.83it/s]

Gaps (ex-reports):  43%|████▎     | 3118/7211 [12:41<14:16,  4.78it/s]

Gaps (ex-reports):  43%|████▎     | 3119/7211 [12:41<14:17,  4.77it/s]

Gaps (ex-reports):  43%|████▎     | 3120/7211 [12:42<14:19,  4.76it/s]

Gaps (ex-reports):  43%|████▎     | 3121/7211 [12:42<14:13,  4.79it/s]

Gaps (ex-reports):  43%|████▎     | 3122/7211 [12:42<14:18,  4.76it/s]

Gaps (ex-reports):  43%|████▎     | 3123/7211 [12:42<14:07,  4.82it/s]

Gaps (ex-reports):  43%|████▎     | 3124/7211 [12:43<14:15,  4.78it/s]

Gaps (ex-reports):  43%|████▎     | 3125/7211 [12:43<14:20,  4.75it/s]

Gaps (ex-reports):  43%|████▎     | 3126/7211 [12:43<14:14,  4.78it/s]

Gaps (ex-reports):  43%|████▎     | 3127/7211 [12:43<14:04,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3128/7211 [12:43<14:19,  4.75it/s]

Gaps (ex-reports):  43%|████▎     | 3129/7211 [12:44<14:01,  4.85it/s]

Gaps (ex-reports):  43%|████▎     | 3130/7211 [12:44<14:00,  4.86it/s]

Gaps (ex-reports):  43%|████▎     | 3131/7211 [12:44<14:09,  4.80it/s]

Gaps (ex-reports):  43%|████▎     | 3132/7211 [12:44<14:15,  4.77it/s]

Gaps (ex-reports):  43%|████▎     | 3133/7211 [12:44<14:01,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3134/7211 [12:45<14:17,  4.76it/s]

Gaps (ex-reports):  43%|████▎     | 3135/7211 [12:45<14:37,  4.65it/s]

Gaps (ex-reports):  43%|████▎     | 3136/7211 [12:45<14:21,  4.73it/s]

Gaps (ex-reports):  44%|████▎     | 3137/7211 [12:45<14:16,  4.76it/s]

Gaps (ex-reports):  44%|████▎     | 3138/7211 [12:45<14:01,  4.84it/s]

Gaps (ex-reports):  44%|████▎     | 3139/7211 [12:46<13:55,  4.87it/s]

Gaps (ex-reports):  44%|████▎     | 3140/7211 [12:46<14:04,  4.82it/s]

Gaps (ex-reports):  44%|████▎     | 3141/7211 [12:46<13:57,  4.86it/s]

Gaps (ex-reports):  44%|████▎     | 3142/7211 [12:46<13:55,  4.87it/s]

Gaps (ex-reports):  44%|████▎     | 3143/7211 [12:46<14:00,  4.84it/s]

Gaps (ex-reports):  44%|████▎     | 3144/7211 [12:47<14:05,  4.81it/s]

Gaps (ex-reports):  44%|████▎     | 3145/7211 [12:47<14:06,  4.81it/s]

Gaps (ex-reports):  44%|████▎     | 3146/7211 [12:47<13:54,  4.87it/s]

Gaps (ex-reports):  44%|████▎     | 3147/7211 [12:47<13:42,  4.94it/s]

Gaps (ex-reports):  44%|████▎     | 3148/7211 [12:48<14:02,  4.82it/s]

Gaps (ex-reports):  44%|████▎     | 3149/7211 [12:48<13:56,  4.86it/s]

Gaps (ex-reports):  44%|████▎     | 3150/7211 [12:48<13:59,  4.84it/s]

Gaps (ex-reports):  44%|████▎     | 3151/7211 [12:48<14:01,  4.83it/s]

Gaps (ex-reports):  44%|████▎     | 3152/7211 [12:48<13:57,  4.85it/s]

Gaps (ex-reports):  44%|████▎     | 3153/7211 [12:49<13:58,  4.84it/s]

Gaps (ex-reports):  44%|████▎     | 3154/7211 [12:49<14:06,  4.79it/s]

Gaps (ex-reports):  44%|████▍     | 3155/7211 [12:49<14:08,  4.78it/s]

Gaps (ex-reports):  44%|████▍     | 3156/7211 [12:49<13:53,  4.86it/s]

Gaps (ex-reports):  44%|████▍     | 3157/7211 [12:49<13:40,  4.94it/s]

Gaps (ex-reports):  44%|████▍     | 3158/7211 [12:50<13:58,  4.83it/s]

Gaps (ex-reports):  44%|████▍     | 3159/7211 [12:50<13:47,  4.90it/s]

Gaps (ex-reports):  44%|████▍     | 3160/7211 [12:50<13:52,  4.86it/s]

Gaps (ex-reports):  44%|████▍     | 3161/7211 [12:50<13:54,  4.85it/s]

Gaps (ex-reports):  44%|████▍     | 3162/7211 [12:50<13:55,  4.85it/s]

Gaps (ex-reports):  44%|████▍     | 3163/7211 [12:51<13:55,  4.85it/s]

Gaps (ex-reports):  44%|████▍     | 3164/7211 [12:51<13:45,  4.90it/s]

Gaps (ex-reports):  44%|████▍     | 3165/7211 [12:51<13:53,  4.85it/s]

Gaps (ex-reports):  44%|████▍     | 3166/7211 [12:51<13:55,  4.84it/s]

Gaps (ex-reports):  44%|████▍     | 3167/7211 [12:51<13:45,  4.90it/s]

Gaps (ex-reports):  44%|████▍     | 3168/7211 [12:52<13:38,  4.94it/s]

Gaps (ex-reports):  44%|████▍     | 3169/7211 [12:52<13:54,  4.85it/s]

Gaps (ex-reports):  44%|████▍     | 3170/7211 [12:52<13:56,  4.83it/s]

Gaps (ex-reports):  44%|████▍     | 3171/7211 [12:52<13:58,  4.82it/s]

Gaps (ex-reports):  44%|████▍     | 3172/7211 [12:52<14:14,  4.72it/s]

Gaps (ex-reports):  44%|████▍     | 3173/7211 [12:53<14:05,  4.78it/s]

Gaps (ex-reports):  44%|████▍     | 3174/7211 [12:53<13:52,  4.85it/s]

Gaps (ex-reports):  44%|████▍     | 3175/7211 [12:53<13:53,  4.84it/s]

Gaps (ex-reports):  44%|████▍     | 3176/7211 [12:53<14:06,  4.77it/s]

Gaps (ex-reports):  44%|████▍     | 3177/7211 [12:54<14:04,  4.78it/s]

Gaps (ex-reports):  44%|████▍     | 3178/7211 [12:54<13:55,  4.83it/s]

Gaps (ex-reports):  44%|████▍     | 3179/7211 [12:54<13:37,  4.93it/s]

Gaps (ex-reports):  44%|████▍     | 3180/7211 [12:54<13:44,  4.89it/s]

Gaps (ex-reports):  44%|████▍     | 3181/7211 [12:54<13:23,  5.02it/s]

Gaps (ex-reports):  44%|████▍     | 3182/7211 [12:55<13:32,  4.96it/s]

Gaps (ex-reports):  44%|████▍     | 3183/7211 [12:55<13:45,  4.88it/s]

Gaps (ex-reports):  44%|████▍     | 3184/7211 [12:55<13:44,  4.88it/s]

Gaps (ex-reports):  44%|████▍     | 3185/7211 [12:56<35:06,  1.91it/s]

Gaps (ex-reports):  44%|████▍     | 3186/7211 [12:56<28:58,  2.32it/s]

Gaps (ex-reports):  44%|████▍     | 3187/7211 [12:57<24:18,  2.76it/s]

Gaps (ex-reports):  44%|████▍     | 3188/7211 [12:57<21:21,  3.14it/s]

Gaps (ex-reports):  44%|████▍     | 3189/7211 [12:57<19:18,  3.47it/s]

Gaps (ex-reports):  44%|████▍     | 3190/7211 [12:57<17:40,  3.79it/s]

Gaps (ex-reports):  44%|████▍     | 3191/7211 [12:57<16:33,  4.04it/s]

Gaps (ex-reports):  44%|████▍     | 3192/7211 [12:58<15:44,  4.25it/s]

Gaps (ex-reports):  44%|████▍     | 3193/7211 [12:58<15:10,  4.41it/s]

Gaps (ex-reports):  44%|████▍     | 3194/7211 [12:58<14:51,  4.51it/s]

Gaps (ex-reports):  44%|████▍     | 3195/7211 [12:58<14:34,  4.59it/s]

Gaps (ex-reports):  44%|████▍     | 3196/7211 [12:59<14:39,  4.57it/s]

Gaps (ex-reports):  44%|████▍     | 3197/7211 [12:59<14:17,  4.68it/s]

Gaps (ex-reports):  44%|████▍     | 3198/7211 [12:59<13:49,  4.84it/s]

Gaps (ex-reports):  44%|████▍     | 3199/7211 [12:59<14:07,  4.74it/s]

Gaps (ex-reports):  44%|████▍     | 3200/7211 [12:59<13:55,  4.80it/s]

Gaps (ex-reports):  44%|████▍     | 3201/7211 [13:00<14:02,  4.76it/s]

Gaps (ex-reports):  44%|████▍     | 3202/7211 [13:00<13:50,  4.83it/s]

Gaps (ex-reports):  44%|████▍     | 3203/7211 [13:00<13:53,  4.81it/s]

Gaps (ex-reports):  44%|████▍     | 3204/7211 [13:00<14:00,  4.77it/s]

Gaps (ex-reports):  44%|████▍     | 3205/7211 [13:00<14:07,  4.73it/s]

Gaps (ex-reports):  44%|████▍     | 3206/7211 [13:01<13:43,  4.86it/s]

Gaps (ex-reports):  44%|████▍     | 3207/7211 [13:01<13:33,  4.92it/s]

Gaps (ex-reports):  44%|████▍     | 3208/7211 [13:01<13:44,  4.85it/s]

Gaps (ex-reports):  45%|████▍     | 3209/7211 [13:01<13:48,  4.83it/s]

Gaps (ex-reports):  45%|████▍     | 3210/7211 [13:02<17:27,  3.82it/s]

Gaps (ex-reports):  45%|████▍     | 3211/7211 [13:02<16:05,  4.14it/s]

Gaps (ex-reports):  45%|████▍     | 3212/7211 [13:02<15:25,  4.32it/s]

Gaps (ex-reports):  45%|████▍     | 3213/7211 [13:02<15:14,  4.37it/s]

Gaps (ex-reports):  45%|████▍     | 3214/7211 [13:02<14:48,  4.50it/s]

Gaps (ex-reports):  45%|████▍     | 3215/7211 [13:03<14:48,  4.50it/s]

Gaps (ex-reports):  45%|████▍     | 3216/7211 [13:03<14:46,  4.50it/s]

Gaps (ex-reports):  45%|████▍     | 3217/7211 [13:03<14:21,  4.64it/s]

Gaps (ex-reports):  45%|████▍     | 3218/7211 [13:03<14:23,  4.62it/s]

Gaps (ex-reports):  45%|████▍     | 3219/7211 [13:03<14:08,  4.70it/s]

Gaps (ex-reports):  45%|████▍     | 3220/7211 [13:04<14:00,  4.75it/s]

Gaps (ex-reports):  45%|████▍     | 3221/7211 [13:04<13:44,  4.84it/s]

Gaps (ex-reports):  45%|████▍     | 3222/7211 [13:04<13:34,  4.90it/s]

Gaps (ex-reports):  45%|████▍     | 3223/7211 [13:04<13:40,  4.86it/s]

Gaps (ex-reports):  45%|████▍     | 3224/7211 [13:04<13:48,  4.81it/s]

Gaps (ex-reports):  45%|████▍     | 3225/7211 [13:05<13:40,  4.86it/s]

Gaps (ex-reports):  45%|████▍     | 3226/7211 [13:05<13:43,  4.84it/s]

Gaps (ex-reports):  45%|████▍     | 3227/7211 [13:05<13:51,  4.79it/s]

Gaps (ex-reports):  45%|████▍     | 3228/7211 [13:05<13:41,  4.85it/s]

Gaps (ex-reports):  45%|████▍     | 3229/7211 [13:06<13:20,  4.97it/s]

Gaps (ex-reports):  45%|████▍     | 3230/7211 [13:06<13:14,  5.01it/s]

Gaps (ex-reports):  45%|████▍     | 3231/7211 [13:06<13:36,  4.87it/s]

Gaps (ex-reports):  45%|████▍     | 3232/7211 [13:06<13:30,  4.91it/s]

Gaps (ex-reports):  45%|████▍     | 3233/7211 [13:06<13:47,  4.81it/s]

Gaps (ex-reports):  45%|████▍     | 3234/7211 [13:07<13:43,  4.83it/s]

Gaps (ex-reports):  45%|████▍     | 3235/7211 [13:07<13:29,  4.91it/s]

Gaps (ex-reports):  45%|████▍     | 3236/7211 [13:07<13:16,  4.99it/s]

Gaps (ex-reports):  45%|████▍     | 3237/7211 [13:07<13:15,  5.00it/s]

Gaps (ex-reports):  45%|████▍     | 3238/7211 [13:07<13:15,  5.00it/s]

Gaps (ex-reports):  45%|████▍     | 3239/7211 [13:08<13:13,  5.00it/s]

Gaps (ex-reports):  45%|████▍     | 3240/7211 [13:08<13:11,  5.02it/s]

Gaps (ex-reports):  45%|████▍     | 3241/7211 [13:08<13:03,  5.07it/s]

Gaps (ex-reports):  45%|████▍     | 3242/7211 [13:08<13:13,  5.00it/s]

Gaps (ex-reports):  45%|████▍     | 3243/7211 [13:08<13:33,  4.88it/s]

Gaps (ex-reports):  45%|████▍     | 3244/7211 [13:09<13:31,  4.89it/s]

Gaps (ex-reports):  45%|████▌     | 3245/7211 [13:09<13:48,  4.78it/s]

Gaps (ex-reports):  45%|████▌     | 3246/7211 [13:09<13:53,  4.76it/s]

Gaps (ex-reports):  45%|████▌     | 3247/7211 [13:09<13:49,  4.78it/s]

Gaps (ex-reports):  45%|████▌     | 3248/7211 [13:09<13:29,  4.89it/s]

Gaps (ex-reports):  45%|████▌     | 3249/7211 [13:10<13:38,  4.84it/s]

Gaps (ex-reports):  45%|████▌     | 3250/7211 [13:10<13:25,  4.92it/s]

Gaps (ex-reports):  45%|████▌     | 3251/7211 [13:10<13:09,  5.02it/s]

Gaps (ex-reports):  45%|████▌     | 3252/7211 [13:10<13:18,  4.96it/s]

Gaps (ex-reports):  45%|████▌     | 3253/7211 [13:10<13:34,  4.86it/s]

Gaps (ex-reports):  45%|████▌     | 3254/7211 [13:11<13:18,  4.95it/s]

Gaps (ex-reports):  45%|████▌     | 3255/7211 [13:11<13:07,  5.03it/s]

Gaps (ex-reports):  45%|████▌     | 3256/7211 [13:11<13:18,  4.95it/s]

Gaps (ex-reports):  45%|████▌     | 3257/7211 [13:11<13:24,  4.91it/s]

Gaps (ex-reports):  45%|████▌     | 3258/7211 [13:11<13:08,  5.01it/s]

Gaps (ex-reports):  45%|████▌     | 3259/7211 [13:12<13:18,  4.95it/s]

Gaps (ex-reports):  45%|████▌     | 3260/7211 [13:12<13:28,  4.89it/s]

Gaps (ex-reports):  45%|████▌     | 3261/7211 [13:12<13:24,  4.91it/s]

Gaps (ex-reports):  45%|████▌     | 3262/7211 [13:12<13:19,  4.94it/s]

Gaps (ex-reports):  45%|████▌     | 3263/7211 [13:12<13:01,  5.05it/s]

Gaps (ex-reports):  45%|████▌     | 3264/7211 [13:13<13:20,  4.93it/s]

Gaps (ex-reports):  45%|████▌     | 3265/7211 [13:13<13:37,  4.83it/s]

Gaps (ex-reports):  45%|████▌     | 3266/7211 [13:13<13:40,  4.81it/s]

Gaps (ex-reports):  45%|████▌     | 3267/7211 [13:13<13:36,  4.83it/s]

Gaps (ex-reports):  45%|████▌     | 3268/7211 [13:13<13:38,  4.82it/s]

Gaps (ex-reports):  45%|████▌     | 3269/7211 [13:14<13:40,  4.81it/s]

Gaps (ex-reports):  45%|████▌     | 3270/7211 [13:14<13:24,  4.90it/s]

Gaps (ex-reports):  45%|████▌     | 3271/7211 [13:14<13:15,  4.95it/s]

Gaps (ex-reports):  45%|████▌     | 3272/7211 [13:14<13:21,  4.92it/s]

Gaps (ex-reports):  45%|████▌     | 3273/7211 [13:14<13:31,  4.85it/s]

Gaps (ex-reports):  45%|████▌     | 3274/7211 [13:15<13:28,  4.87it/s]

Gaps (ex-reports):  45%|████▌     | 3275/7211 [13:15<13:33,  4.84it/s]

Gaps (ex-reports):  45%|████▌     | 3276/7211 [13:15<13:26,  4.88it/s]

Gaps (ex-reports):  45%|████▌     | 3277/7211 [13:15<13:49,  4.74it/s]

Gaps (ex-reports):  45%|████▌     | 3278/7211 [13:16<13:26,  4.88it/s]

Gaps (ex-reports):  45%|████▌     | 3279/7211 [13:16<13:31,  4.84it/s]

Gaps (ex-reports):  45%|████▌     | 3280/7211 [13:16<13:24,  4.89it/s]

Gaps (ex-reports):  45%|████▌     | 3281/7211 [13:16<13:33,  4.83it/s]

Gaps (ex-reports):  46%|████▌     | 3282/7211 [13:16<13:39,  4.79it/s]

Gaps (ex-reports):  46%|████▌     | 3283/7211 [13:17<13:33,  4.83it/s]

Gaps (ex-reports):  46%|████▌     | 3284/7211 [13:17<13:28,  4.85it/s]

Gaps (ex-reports):  46%|████▌     | 3285/7211 [13:17<13:37,  4.80it/s]

Gaps (ex-reports):  46%|████▌     | 3286/7211 [13:17<13:20,  4.90it/s]

Gaps (ex-reports):  46%|████▌     | 3287/7211 [13:17<13:18,  4.91it/s]

Gaps (ex-reports):  46%|████▌     | 3288/7211 [13:18<13:42,  4.77it/s]

Gaps (ex-reports):  46%|████▌     | 3289/7211 [13:18<13:49,  4.73it/s]

Gaps (ex-reports):  46%|████▌     | 3290/7211 [13:18<13:38,  4.79it/s]

Gaps (ex-reports):  46%|████▌     | 3291/7211 [13:18<13:23,  4.88it/s]

Gaps (ex-reports):  46%|████▌     | 3292/7211 [13:18<13:13,  4.94it/s]

Gaps (ex-reports):  46%|████▌     | 3293/7211 [13:19<13:14,  4.93it/s]

Gaps (ex-reports):  46%|████▌     | 3294/7211 [13:19<13:54,  4.69it/s]

Gaps (ex-reports):  46%|████▌     | 3295/7211 [13:19<13:32,  4.82it/s]

Gaps (ex-reports):  46%|████▌     | 3296/7211 [13:19<13:42,  4.76it/s]

Gaps (ex-reports):  46%|████▌     | 3297/7211 [13:19<13:36,  4.79it/s]

Gaps (ex-reports):  46%|████▌     | 3298/7211 [13:20<13:45,  4.74it/s]

Gaps (ex-reports):  46%|████▌     | 3299/7211 [13:20<13:35,  4.80it/s]

Gaps (ex-reports):  46%|████▌     | 3300/7211 [13:20<13:24,  4.86it/s]

Gaps (ex-reports):  46%|████▌     | 3301/7211 [13:20<13:13,  4.93it/s]

Gaps (ex-reports):  46%|████▌     | 3302/7211 [13:21<14:36,  4.46it/s]

Gaps (ex-reports):  46%|████▌     | 3303/7211 [13:21<14:13,  4.58it/s]

Gaps (ex-reports):  46%|████▌     | 3304/7211 [13:21<13:45,  4.73it/s]

Gaps (ex-reports):  46%|████▌     | 3305/7211 [13:21<14:46,  4.41it/s]

Gaps (ex-reports):  46%|████▌     | 3306/7211 [13:21<14:33,  4.47it/s]

Gaps (ex-reports):  46%|████▌     | 3307/7211 [13:22<14:13,  4.57it/s]

Gaps (ex-reports):  46%|████▌     | 3308/7211 [13:22<25:17,  2.57it/s]

Gaps (ex-reports):  46%|████▌     | 3309/7211 [13:23<21:40,  3.00it/s]

Gaps (ex-reports):  46%|████▌     | 3310/7211 [13:23<19:07,  3.40it/s]

Gaps (ex-reports):  46%|████▌     | 3311/7211 [13:23<17:16,  3.76it/s]

Gaps (ex-reports):  46%|████▌     | 3312/7211 [13:23<16:07,  4.03it/s]

Gaps (ex-reports):  46%|████▌     | 3313/7211 [13:23<15:02,  4.32it/s]

Gaps (ex-reports):  46%|████▌     | 3314/7211 [13:24<14:32,  4.46it/s]

Gaps (ex-reports):  46%|████▌     | 3315/7211 [13:24<14:05,  4.61it/s]

Gaps (ex-reports):  46%|████▌     | 3316/7211 [13:24<13:52,  4.68it/s]

Gaps (ex-reports):  46%|████▌     | 3317/7211 [13:24<13:34,  4.78it/s]

Gaps (ex-reports):  46%|████▌     | 3318/7211 [13:24<13:14,  4.90it/s]

Gaps (ex-reports):  46%|████▌     | 3319/7211 [13:25<13:00,  4.99it/s]

Gaps (ex-reports):  46%|████▌     | 3320/7211 [13:25<13:05,  4.95it/s]

Gaps (ex-reports):  46%|████▌     | 3321/7211 [13:25<13:11,  4.92it/s]

Gaps (ex-reports):  46%|████▌     | 3322/7211 [13:25<13:08,  4.93it/s]

Gaps (ex-reports):  46%|████▌     | 3323/7211 [13:25<13:07,  4.93it/s]

Gaps (ex-reports):  46%|████▌     | 3324/7211 [13:26<13:13,  4.90it/s]

Gaps (ex-reports):  46%|████▌     | 3325/7211 [13:26<13:20,  4.85it/s]

Gaps (ex-reports):  46%|████▌     | 3326/7211 [13:26<13:17,  4.87it/s]

Gaps (ex-reports):  46%|████▌     | 3327/7211 [13:26<13:27,  4.81it/s]

Gaps (ex-reports):  46%|████▌     | 3328/7211 [13:26<13:24,  4.82it/s]

Gaps (ex-reports):  46%|████▌     | 3329/7211 [13:27<13:18,  4.86it/s]

Gaps (ex-reports):  46%|████▌     | 3330/7211 [13:27<13:02,  4.96it/s]

Gaps (ex-reports):  46%|████▌     | 3331/7211 [13:27<12:53,  5.02it/s]

Gaps (ex-reports):  46%|████▌     | 3332/7211 [13:27<13:03,  4.95it/s]

Gaps (ex-reports):  46%|████▌     | 3333/7211 [13:27<13:03,  4.95it/s]

Gaps (ex-reports):  46%|████▌     | 3334/7211 [13:28<13:09,  4.91it/s]

Gaps (ex-reports):  46%|████▌     | 3335/7211 [13:28<13:04,  4.94it/s]

Gaps (ex-reports):  46%|████▋     | 3336/7211 [13:28<13:07,  4.92it/s]

Gaps (ex-reports):  46%|████▋     | 3337/7211 [13:28<12:48,  5.04it/s]

Gaps (ex-reports):  46%|████▋     | 3338/7211 [13:28<12:58,  4.97it/s]

Gaps (ex-reports):  46%|████▋     | 3339/7211 [13:29<13:09,  4.90it/s]

Gaps (ex-reports):  46%|████▋     | 3340/7211 [13:29<12:57,  4.98it/s]

Gaps (ex-reports):  46%|████▋     | 3341/7211 [13:29<13:15,  4.87it/s]

Gaps (ex-reports):  46%|████▋     | 3342/7211 [13:29<13:06,  4.92it/s]

Gaps (ex-reports):  46%|████▋     | 3343/7211 [13:30<13:11,  4.89it/s]

Gaps (ex-reports):  46%|████▋     | 3344/7211 [13:30<13:08,  4.90it/s]

Gaps (ex-reports):  46%|████▋     | 3345/7211 [13:30<13:03,  4.94it/s]

Gaps (ex-reports):  46%|████▋     | 3346/7211 [13:30<12:47,  5.03it/s]

Gaps (ex-reports):  46%|████▋     | 3347/7211 [13:30<13:12,  4.87it/s]

Gaps (ex-reports):  46%|████▋     | 3348/7211 [13:31<13:17,  4.84it/s]

Gaps (ex-reports):  46%|████▋     | 3349/7211 [13:31<13:21,  4.82it/s]

Gaps (ex-reports):  46%|████▋     | 3350/7211 [13:31<13:07,  4.90it/s]

Gaps (ex-reports):  46%|████▋     | 3351/7211 [13:31<13:23,  4.80it/s]

Gaps (ex-reports):  46%|████▋     | 3352/7211 [13:31<13:13,  4.86it/s]

Gaps (ex-reports):  46%|████▋     | 3353/7211 [13:32<13:03,  4.92it/s]

Gaps (ex-reports):  47%|████▋     | 3354/7211 [13:32<13:07,  4.90it/s]

Gaps (ex-reports):  47%|████▋     | 3355/7211 [13:32<13:09,  4.88it/s]

Gaps (ex-reports):  47%|████▋     | 3356/7211 [13:32<12:53,  4.99it/s]

Gaps (ex-reports):  47%|████▋     | 3357/7211 [13:32<12:45,  5.03it/s]

Gaps (ex-reports):  47%|████▋     | 3358/7211 [13:33<12:59,  4.94it/s]

Gaps (ex-reports):  47%|████▋     | 3359/7211 [13:33<12:43,  5.04it/s]

Gaps (ex-reports):  47%|████▋     | 3360/7211 [13:33<12:40,  5.06it/s]

Gaps (ex-reports):  47%|████▋     | 3361/7211 [13:33<12:38,  5.08it/s]

Gaps (ex-reports):  47%|████▋     | 3362/7211 [13:33<12:44,  5.03it/s]

Gaps (ex-reports):  47%|████▋     | 3363/7211 [13:34<12:56,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3364/7211 [13:34<12:59,  4.94it/s]

Gaps (ex-reports):  47%|████▋     | 3365/7211 [13:34<14:45,  4.34it/s]

Gaps (ex-reports):  47%|████▋     | 3366/7211 [13:34<14:47,  4.33it/s]

Gaps (ex-reports):  47%|████▋     | 3367/7211 [13:35<16:16,  3.94it/s]

Gaps (ex-reports):  47%|████▋     | 3368/7211 [13:35<16:07,  3.97it/s]

Gaps (ex-reports):  47%|████▋     | 3369/7211 [13:35<15:01,  4.26it/s]

Gaps (ex-reports):  47%|████▋     | 3370/7211 [13:35<14:08,  4.52it/s]

Gaps (ex-reports):  47%|████▋     | 3371/7211 [13:35<13:39,  4.69it/s]

Gaps (ex-reports):  47%|████▋     | 3372/7211 [13:36<13:26,  4.76it/s]

Gaps (ex-reports):  47%|████▋     | 3373/7211 [13:36<13:21,  4.79it/s]

Gaps (ex-reports):  47%|████▋     | 3374/7211 [13:36<13:13,  4.83it/s]

Gaps (ex-reports):  47%|████▋     | 3375/7211 [13:36<13:04,  4.89it/s]

Gaps (ex-reports):  47%|████▋     | 3376/7211 [13:36<13:01,  4.91it/s]

Gaps (ex-reports):  47%|████▋     | 3377/7211 [13:37<13:03,  4.89it/s]

Gaps (ex-reports):  47%|████▋     | 3378/7211 [13:37<13:15,  4.82it/s]

Gaps (ex-reports):  47%|████▋     | 3379/7211 [13:37<13:59,  4.57it/s]

Gaps (ex-reports):  47%|████▋     | 3380/7211 [13:37<13:35,  4.70it/s]

Gaps (ex-reports):  47%|████▋     | 3381/7211 [13:37<13:24,  4.76it/s]

Gaps (ex-reports):  47%|████▋     | 3382/7211 [13:38<13:10,  4.84it/s]

Gaps (ex-reports):  47%|████▋     | 3383/7211 [13:38<13:09,  4.85it/s]

Gaps (ex-reports):  47%|████▋     | 3384/7211 [13:38<12:52,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3385/7211 [13:38<12:57,  4.92it/s]

Gaps (ex-reports):  47%|████▋     | 3386/7211 [13:39<13:09,  4.85it/s]

Gaps (ex-reports):  47%|████▋     | 3387/7211 [13:39<13:05,  4.87it/s]

Gaps (ex-reports):  47%|████▋     | 3388/7211 [13:39<12:51,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3389/7211 [13:39<12:37,  5.05it/s]

Gaps (ex-reports):  47%|████▋     | 3390/7211 [13:39<12:55,  4.93it/s]

Gaps (ex-reports):  47%|████▋     | 3391/7211 [13:40<12:52,  4.94it/s]

Gaps (ex-reports):  47%|████▋     | 3392/7211 [13:40<12:42,  5.01it/s]

Gaps (ex-reports):  47%|████▋     | 3393/7211 [13:40<12:39,  5.03it/s]

Gaps (ex-reports):  47%|████▋     | 3394/7211 [13:40<12:46,  4.98it/s]

Gaps (ex-reports):  47%|████▋     | 3395/7211 [13:40<12:50,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3396/7211 [13:41<12:44,  4.99it/s]

Gaps (ex-reports):  47%|████▋     | 3397/7211 [13:41<12:55,  4.92it/s]

Gaps (ex-reports):  47%|████▋     | 3398/7211 [13:41<12:54,  4.93it/s]

Gaps (ex-reports):  47%|████▋     | 3399/7211 [13:41<13:09,  4.83it/s]

Gaps (ex-reports):  47%|████▋     | 3400/7211 [13:41<12:49,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3401/7211 [13:42<12:58,  4.89it/s]

Gaps (ex-reports):  47%|████▋     | 3402/7211 [13:42<12:56,  4.91it/s]

Gaps (ex-reports):  47%|████▋     | 3403/7211 [13:42<12:45,  4.98it/s]

Gaps (ex-reports):  47%|████▋     | 3404/7211 [13:42<12:47,  4.96it/s]

Gaps (ex-reports):  47%|████▋     | 3405/7211 [13:42<12:39,  5.01it/s]

Gaps (ex-reports):  47%|████▋     | 3406/7211 [13:43<12:51,  4.93it/s]

Gaps (ex-reports):  47%|████▋     | 3407/7211 [13:43<12:56,  4.90it/s]

Gaps (ex-reports):  47%|████▋     | 3408/7211 [13:43<13:14,  4.79it/s]

Gaps (ex-reports):  47%|████▋     | 3409/7211 [13:43<12:53,  4.92it/s]

Gaps (ex-reports):  47%|████▋     | 3410/7211 [13:43<12:46,  4.96it/s]

Gaps (ex-reports):  47%|████▋     | 3411/7211 [13:44<12:41,  4.99it/s]

Gaps (ex-reports):  47%|████▋     | 3412/7211 [13:44<12:42,  4.98it/s]

Gaps (ex-reports):  47%|████▋     | 3413/7211 [13:44<12:35,  5.03it/s]

Gaps (ex-reports):  47%|████▋     | 3414/7211 [13:44<12:47,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3415/7211 [13:44<12:47,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3416/7211 [13:45<12:57,  4.88it/s]

Gaps (ex-reports):  47%|████▋     | 3417/7211 [13:45<12:48,  4.94it/s]

Gaps (ex-reports):  47%|████▋     | 3418/7211 [13:45<13:04,  4.83it/s]

Gaps (ex-reports):  47%|████▋     | 3419/7211 [13:45<12:53,  4.90it/s]

Gaps (ex-reports):  47%|████▋     | 3420/7211 [13:45<12:56,  4.88it/s]

Gaps (ex-reports):  47%|████▋     | 3421/7211 [13:46<12:54,  4.89it/s]

Gaps (ex-reports):  47%|████▋     | 3422/7211 [13:46<12:38,  5.00it/s]

Gaps (ex-reports):  47%|████▋     | 3423/7211 [13:46<12:31,  5.04it/s]

Gaps (ex-reports):  47%|████▋     | 3424/7211 [13:46<12:41,  4.97it/s]

Gaps (ex-reports):  47%|████▋     | 3425/7211 [13:46<12:49,  4.92it/s]

Gaps (ex-reports):  48%|████▊     | 3426/7211 [13:47<12:50,  4.92it/s]

Gaps (ex-reports):  48%|████▊     | 3427/7211 [13:47<13:02,  4.84it/s]

Gaps (ex-reports):  48%|████▊     | 3428/7211 [13:47<13:12,  4.77it/s]

Gaps (ex-reports):  48%|████▊     | 3429/7211 [13:47<13:11,  4.78it/s]

Gaps (ex-reports):  48%|████▊     | 3430/7211 [13:47<13:04,  4.82it/s]

Gaps (ex-reports):  48%|████▊     | 3431/7211 [13:48<13:03,  4.82it/s]

Gaps (ex-reports):  48%|████▊     | 3432/7211 [13:48<13:01,  4.83it/s]

Gaps (ex-reports):  48%|████▊     | 3433/7211 [13:48<12:50,  4.90it/s]

Gaps (ex-reports):  48%|████▊     | 3434/7211 [13:48<12:56,  4.86it/s]

Gaps (ex-reports):  48%|████▊     | 3435/7211 [13:48<12:54,  4.88it/s]

Gaps (ex-reports):  48%|████▊     | 3436/7211 [13:49<12:45,  4.93it/s]

Gaps (ex-reports):  48%|████▊     | 3437/7211 [13:49<12:27,  5.05it/s]

Gaps (ex-reports):  48%|████▊     | 3438/7211 [13:49<12:36,  4.99it/s]

Gaps (ex-reports):  48%|████▊     | 3439/7211 [13:49<12:30,  5.02it/s]

Gaps (ex-reports):  48%|████▊     | 3440/7211 [13:49<12:21,  5.09it/s]

Gaps (ex-reports):  48%|████▊     | 3441/7211 [13:50<12:31,  5.01it/s]

Gaps (ex-reports):  48%|████▊     | 3442/7211 [13:50<12:25,  5.05it/s]

Gaps (ex-reports):  48%|████▊     | 3443/7211 [13:50<12:41,  4.95it/s]

Gaps (ex-reports):  48%|████▊     | 3444/7211 [13:50<12:38,  4.97it/s]

Gaps (ex-reports):  48%|████▊     | 3445/7211 [13:50<12:30,  5.02it/s]

Gaps (ex-reports):  48%|████▊     | 3446/7211 [13:51<12:29,  5.02it/s]

Gaps (ex-reports):  48%|████▊     | 3447/7211 [13:51<12:23,  5.06it/s]

Gaps (ex-reports):  48%|████▊     | 3448/7211 [13:51<12:30,  5.02it/s]

Gaps (ex-reports):  48%|████▊     | 3449/7211 [13:51<12:38,  4.96it/s]

Gaps (ex-reports):  48%|████▊     | 3450/7211 [13:51<12:42,  4.93it/s]

Gaps (ex-reports):  48%|████▊     | 3451/7211 [13:52<12:41,  4.94it/s]

Gaps (ex-reports):  48%|████▊     | 3452/7211 [13:52<12:30,  5.01it/s]

Gaps (ex-reports):  48%|████▊     | 3453/7211 [13:52<12:28,  5.02it/s]

Gaps (ex-reports):  48%|████▊     | 3454/7211 [13:52<12:32,  4.99it/s]

Gaps (ex-reports):  48%|████▊     | 3455/7211 [13:52<12:32,  4.99it/s]

Gaps (ex-reports):  48%|████▊     | 3456/7211 [13:53<12:38,  4.95it/s]

Gaps (ex-reports):  48%|████▊     | 3457/7211 [13:53<12:30,  5.00it/s]

Gaps (ex-reports):  48%|████▊     | 3458/7211 [13:53<12:41,  4.93it/s]

Gaps (ex-reports):  48%|████▊     | 3459/7211 [13:53<12:41,  4.93it/s]

Gaps (ex-reports):  48%|████▊     | 3460/7211 [13:53<12:45,  4.90it/s]

Gaps (ex-reports):  48%|████▊     | 3461/7211 [13:54<12:47,  4.89it/s]

Gaps (ex-reports):  48%|████▊     | 3462/7211 [13:54<12:37,  4.95it/s]

Gaps (ex-reports):  48%|████▊     | 3463/7211 [13:54<12:30,  5.00it/s]

Gaps (ex-reports):  48%|████▊     | 3464/7211 [13:54<12:40,  4.92it/s]

Gaps (ex-reports):  48%|████▊     | 3465/7211 [13:54<12:52,  4.85it/s]

Gaps (ex-reports):  48%|████▊     | 3466/7211 [13:55<12:42,  4.91it/s]

Gaps (ex-reports):  48%|████▊     | 3467/7211 [13:55<12:27,  5.01it/s]

Gaps (ex-reports):  48%|████▊     | 3468/7211 [13:55<12:41,  4.92it/s]

Gaps (ex-reports):  48%|████▊     | 3469/7211 [13:55<12:21,  5.05it/s]

Gaps (ex-reports):  48%|████▊     | 3470/7211 [13:55<12:31,  4.98it/s]

Gaps (ex-reports):  48%|████▊     | 3471/7211 [13:56<12:20,  5.05it/s]

Gaps (ex-reports):  48%|████▊     | 3472/7211 [13:56<12:17,  5.07it/s]

Gaps (ex-reports):  48%|████▊     | 3473/7211 [13:56<12:27,  5.00it/s]

Gaps (ex-reports):  48%|████▊     | 3474/7211 [13:56<12:15,  5.08it/s]

Gaps (ex-reports):  48%|████▊     | 3475/7211 [13:56<12:14,  5.09it/s]

Gaps (ex-reports):  48%|████▊     | 3476/7211 [13:57<12:30,  4.98it/s]

Gaps (ex-reports):  48%|████▊     | 3477/7211 [13:57<12:32,  4.96it/s]

Gaps (ex-reports):  48%|████▊     | 3478/7211 [13:57<12:41,  4.90it/s]

Gaps (ex-reports):  48%|████▊     | 3479/7211 [13:57<12:25,  5.01it/s]

Gaps (ex-reports):  48%|████▊     | 3480/7211 [13:57<12:27,  4.99it/s]

Gaps (ex-reports):  48%|████▊     | 3481/7211 [13:58<12:24,  5.01it/s]

Gaps (ex-reports):  48%|████▊     | 3482/7211 [13:58<12:11,  5.10it/s]

Gaps (ex-reports):  48%|████▊     | 3483/7211 [13:58<12:11,  5.10it/s]

Gaps (ex-reports):  48%|████▊     | 3484/7211 [13:58<12:08,  5.12it/s]

Gaps (ex-reports):  48%|████▊     | 3485/7211 [13:58<12:18,  5.05it/s]

Gaps (ex-reports):  48%|████▊     | 3486/7211 [13:59<12:11,  5.10it/s]

Gaps (ex-reports):  48%|████▊     | 3487/7211 [13:59<12:09,  5.10it/s]

Gaps (ex-reports):  48%|████▊     | 3488/7211 [13:59<12:32,  4.95it/s]

Gaps (ex-reports):  48%|████▊     | 3489/7211 [13:59<12:20,  5.02it/s]

Gaps (ex-reports):  48%|████▊     | 3490/7211 [13:59<12:15,  5.06it/s]

Gaps (ex-reports):  48%|████▊     | 3491/7211 [14:00<12:25,  4.99it/s]

Gaps (ex-reports):  48%|████▊     | 3492/7211 [14:00<12:19,  5.03it/s]

Gaps (ex-reports):  48%|████▊     | 3493/7211 [14:00<12:33,  4.93it/s]

Gaps (ex-reports):  48%|████▊     | 3494/7211 [14:00<12:36,  4.92it/s]

Gaps (ex-reports):  48%|████▊     | 3495/7211 [14:00<12:43,  4.86it/s]

Gaps (ex-reports):  48%|████▊     | 3496/7211 [14:01<12:25,  4.99it/s]

Gaps (ex-reports):  48%|████▊     | 3497/7211 [14:01<12:45,  4.85it/s]

Gaps (ex-reports):  49%|████▊     | 3498/7211 [14:01<12:38,  4.89it/s]

Gaps (ex-reports):  49%|████▊     | 3499/7211 [14:01<12:40,  4.88it/s]

Gaps (ex-reports):  49%|████▊     | 3500/7211 [14:01<12:29,  4.95it/s]

Gaps (ex-reports):  49%|████▊     | 3501/7211 [14:02<12:30,  4.94it/s]

Gaps (ex-reports):  49%|████▊     | 3502/7211 [14:02<12:25,  4.97it/s]

Gaps (ex-reports):  49%|████▊     | 3503/7211 [14:02<12:30,  4.94it/s]

Gaps (ex-reports):  49%|████▊     | 3504/7211 [14:02<12:36,  4.90it/s]

Gaps (ex-reports):  49%|████▊     | 3505/7211 [14:02<12:22,  4.99it/s]

Gaps (ex-reports):  49%|████▊     | 3506/7211 [14:03<12:18,  5.02it/s]

Gaps (ex-reports):  49%|████▊     | 3507/7211 [14:03<12:20,  5.00it/s]

Gaps (ex-reports):  49%|████▊     | 3508/7211 [14:03<12:46,  4.83it/s]

Gaps (ex-reports):  49%|████▊     | 3509/7211 [14:03<12:32,  4.92it/s]

Gaps (ex-reports):  49%|████▊     | 3510/7211 [14:04<12:20,  5.00it/s]

Gaps (ex-reports):  49%|████▊     | 3511/7211 [14:04<12:25,  4.96it/s]

Gaps (ex-reports):  49%|████▊     | 3512/7211 [14:04<12:23,  4.98it/s]

Gaps (ex-reports):  49%|████▊     | 3513/7211 [14:04<12:25,  4.96it/s]

Gaps (ex-reports):  49%|████▊     | 3514/7211 [14:04<12:14,  5.04it/s]

Gaps (ex-reports):  49%|████▊     | 3515/7211 [14:05<12:20,  4.99it/s]

Gaps (ex-reports):  49%|████▉     | 3516/7211 [14:08<1:05:42,  1.07s/it]

Gaps (ex-reports):  49%|████▉     | 3517/7211 [14:08<49:30,  1.24it/s]

Gaps (ex-reports):  49%|████▉     | 3518/7211 [14:08<38:39,  1.59it/s]

Gaps (ex-reports):  49%|████▉     | 3519/7211 [14:08<30:43,  2.00it/s]

Gaps (ex-reports):  49%|████▉     | 3520/7211 [14:08<25:02,  2.46it/s]

Gaps (ex-reports):  49%|████▉     | 3521/7211 [14:09<21:04,  2.92it/s]

Gaps (ex-reports):  49%|████▉     | 3522/7211 [14:09<18:30,  3.32it/s]

Gaps (ex-reports):  49%|████▉     | 3523/7211 [14:09<16:34,  3.71it/s]

Gaps (ex-reports):  49%|████▉     | 3524/7211 [14:09<15:04,  4.08it/s]

Gaps (ex-reports):  49%|████▉     | 3525/7211 [14:09<14:09,  4.34it/s]

Gaps (ex-reports):  49%|████▉     | 3526/7211 [14:10<13:39,  4.50it/s]

Gaps (ex-reports):  49%|████▉     | 3527/7211 [14:10<13:23,  4.59it/s]

Gaps (ex-reports):  49%|████▉     | 3528/7211 [14:10<12:53,  4.76it/s]

Gaps (ex-reports):  49%|████▉     | 3529/7211 [14:10<12:47,  4.80it/s]

Gaps (ex-reports):  49%|████▉     | 3530/7211 [14:10<12:35,  4.87it/s]

Gaps (ex-reports):  49%|████▉     | 3531/7211 [14:11<12:20,  4.97it/s]

Gaps (ex-reports):  49%|████▉     | 3532/7211 [14:11<12:21,  4.96it/s]

Gaps (ex-reports):  49%|████▉     | 3533/7211 [14:11<12:10,  5.03it/s]

Gaps (ex-reports):  49%|████▉     | 3534/7211 [14:11<12:09,  5.04it/s]

Gaps (ex-reports):  49%|████▉     | 3535/7211 [14:11<12:27,  4.92it/s]

Gaps (ex-reports):  49%|████▉     | 3536/7211 [14:12<12:31,  4.89it/s]

Gaps (ex-reports):  49%|████▉     | 3537/7211 [14:12<12:38,  4.84it/s]

Gaps (ex-reports):  49%|████▉     | 3538/7211 [14:12<12:49,  4.77it/s]

Gaps (ex-reports):  49%|████▉     | 3539/7211 [14:12<12:38,  4.84it/s]

Gaps (ex-reports):  49%|████▉     | 3540/7211 [14:12<12:32,  4.88it/s]

Gaps (ex-reports):  49%|████▉     | 3541/7211 [14:13<12:39,  4.83it/s]

Gaps (ex-reports):  49%|████▉     | 3542/7211 [14:13<12:49,  4.77it/s]

Gaps (ex-reports):  49%|████▉     | 3543/7211 [14:13<12:34,  4.86it/s]

Gaps (ex-reports):  49%|████▉     | 3544/7211 [14:13<12:30,  4.89it/s]

Gaps (ex-reports):  49%|████▉     | 3545/7211 [14:13<12:19,  4.95it/s]

Gaps (ex-reports):  49%|████▉     | 3546/7211 [14:14<12:40,  4.82it/s]

Gaps (ex-reports):  49%|████▉     | 3547/7211 [14:14<12:36,  4.84it/s]

Gaps (ex-reports):  49%|████▉     | 3548/7211 [14:14<12:34,  4.86it/s]

Gaps (ex-reports):  49%|████▉     | 3549/7211 [14:14<12:34,  4.85it/s]

Gaps (ex-reports):  49%|████▉     | 3550/7211 [14:14<12:49,  4.76it/s]

Gaps (ex-reports):  49%|████▉     | 3551/7211 [14:15<12:33,  4.86it/s]

Gaps (ex-reports):  49%|████▉     | 3552/7211 [14:15<12:31,  4.87it/s]

Gaps (ex-reports):  49%|████▉     | 3553/7211 [14:15<12:13,  4.99it/s]

Gaps (ex-reports):  49%|████▉     | 3554/7211 [14:15<12:05,  5.04it/s]

Gaps (ex-reports):  49%|████▉     | 3555/7211 [14:15<12:07,  5.03it/s]

Gaps (ex-reports):  49%|████▉     | 3556/7211 [14:16<12:07,  5.03it/s]

Gaps (ex-reports):  49%|████▉     | 3557/7211 [14:16<12:00,  5.07it/s]

Gaps (ex-reports):  49%|████▉     | 3558/7211 [14:16<11:56,  5.10it/s]

Gaps (ex-reports):  49%|████▉     | 3559/7211 [14:16<11:50,  5.14it/s]

Gaps (ex-reports):  49%|████▉     | 3560/7211 [14:16<11:45,  5.17it/s]

Gaps (ex-reports):  49%|████▉     | 3561/7211 [14:17<11:59,  5.08it/s]

Gaps (ex-reports):  49%|████▉     | 3562/7211 [14:17<12:16,  4.95it/s]

Gaps (ex-reports):  49%|████▉     | 3563/7211 [14:17<12:38,  4.81it/s]

Gaps (ex-reports):  49%|████▉     | 3564/7211 [14:17<12:21,  4.92it/s]

Gaps (ex-reports):  49%|████▉     | 3565/7211 [14:17<12:09,  5.00it/s]

Gaps (ex-reports):  49%|████▉     | 3566/7211 [14:18<11:57,  5.08it/s]

Gaps (ex-reports):  49%|████▉     | 3567/7211 [14:18<11:49,  5.14it/s]

Gaps (ex-reports):  49%|████▉     | 3568/7211 [14:18<11:55,  5.09it/s]

Gaps (ex-reports):  49%|████▉     | 3569/7211 [14:18<12:06,  5.01it/s]

Gaps (ex-reports):  50%|████▉     | 3570/7211 [14:18<12:17,  4.94it/s]

Gaps (ex-reports):  50%|████▉     | 3571/7211 [14:19<12:21,  4.91it/s]

Gaps (ex-reports):  50%|████▉     | 3572/7211 [14:19<12:07,  5.00it/s]

Gaps (ex-reports):  50%|████▉     | 3573/7211 [14:19<11:56,  5.07it/s]

Gaps (ex-reports):  50%|████▉     | 3574/7211 [14:19<11:51,  5.11it/s]

Gaps (ex-reports):  50%|████▉     | 3575/7211 [14:19<11:52,  5.10it/s]

Gaps (ex-reports):  50%|████▉     | 3576/7211 [14:20<11:45,  5.15it/s]

Gaps (ex-reports):  50%|████▉     | 3577/7211 [14:20<12:02,  5.03it/s]

Gaps (ex-reports):  50%|████▉     | 3578/7211 [14:20<12:10,  4.98it/s]

Gaps (ex-reports):  50%|████▉     | 3579/7211 [14:20<12:03,  5.02it/s]

Gaps (ex-reports):  50%|████▉     | 3580/7211 [14:20<12:11,  4.96it/s]

Gaps (ex-reports):  50%|████▉     | 3581/7211 [14:21<12:14,  4.94it/s]

Gaps (ex-reports):  50%|████▉     | 3582/7211 [14:21<12:12,  4.96it/s]

Gaps (ex-reports):  50%|████▉     | 3583/7211 [14:21<12:12,  4.95it/s]

Gaps (ex-reports):  50%|████▉     | 3584/7211 [14:21<12:09,  4.97it/s]

Gaps (ex-reports):  50%|████▉     | 3585/7211 [14:21<12:12,  4.95it/s]

Gaps (ex-reports):  50%|████▉     | 3586/7211 [14:22<12:07,  4.98it/s]

Gaps (ex-reports):  50%|████▉     | 3587/7211 [14:22<12:06,  4.99it/s]

Gaps (ex-reports):  50%|████▉     | 3588/7211 [14:22<12:03,  5.01it/s]

Gaps (ex-reports):  50%|████▉     | 3589/7211 [14:22<12:09,  4.96it/s]

Gaps (ex-reports):  50%|████▉     | 3590/7211 [14:22<12:11,  4.95it/s]

Gaps (ex-reports):  50%|████▉     | 3591/7211 [14:23<12:00,  5.02it/s]

Gaps (ex-reports):  50%|████▉     | 3592/7211 [14:23<11:54,  5.06it/s]

Gaps (ex-reports):  50%|████▉     | 3593/7211 [14:23<12:09,  4.96it/s]

Gaps (ex-reports):  50%|████▉     | 3594/7211 [14:23<12:10,  4.95it/s]

Gaps (ex-reports):  50%|████▉     | 3595/7211 [14:23<12:01,  5.01it/s]

Gaps (ex-reports):  50%|████▉     | 3596/7211 [14:24<12:08,  4.96it/s]

Gaps (ex-reports):  50%|████▉     | 3597/7211 [14:24<12:00,  5.02it/s]

Gaps (ex-reports):  50%|████▉     | 3598/7211 [14:24<12:17,  4.90it/s]

Gaps (ex-reports):  50%|████▉     | 3599/7211 [14:24<12:11,  4.94it/s]

Gaps (ex-reports):  50%|████▉     | 3600/7211 [14:24<12:26,  4.84it/s]

Gaps (ex-reports):  50%|████▉     | 3601/7211 [14:25<12:21,  4.87it/s]

Gaps (ex-reports):  50%|████▉     | 3602/7211 [14:25<12:38,  4.76it/s]

Gaps (ex-reports):  50%|████▉     | 3603/7211 [14:25<12:24,  4.85it/s]

Gaps (ex-reports):  50%|████▉     | 3604/7211 [14:25<12:08,  4.95it/s]

Gaps (ex-reports):  50%|████▉     | 3605/7211 [14:40<4:41:33,  4.68s/it]

Gaps (ex-reports):  50%|█████     | 3606/7211 [14:41<3:20:48,  3.34s/it]

Gaps (ex-reports):  50%|█████     | 3607/7211 [14:41<2:24:14,  2.40s/it]

Gaps (ex-reports):  50%|█████     | 3608/7211 [14:41<1:44:54,  1.75s/it]

Gaps (ex-reports):  50%|█████     | 3609/7211 [14:41<1:16:59,  1.28s/it]

Gaps (ex-reports):  50%|█████     | 3610/7211 [14:41<57:21,  1.05it/s]

Gaps (ex-reports):  50%|█████     | 3611/7211 [14:42<43:37,  1.38it/s]

Gaps (ex-reports):  50%|█████     | 3612/7211 [14:42<34:11,  1.75it/s]

Gaps (ex-reports):  50%|█████     | 3613/7211 [14:42<27:42,  2.16it/s]

Gaps (ex-reports):  50%|█████     | 3614/7211 [14:42<23:07,  2.59it/s]

Gaps (ex-reports):  50%|█████     | 3615/7211 [14:42<19:33,  3.06it/s]

Gaps (ex-reports):  50%|█████     | 3616/7211 [14:43<17:15,  3.47it/s]

Gaps (ex-reports):  50%|█████     | 3617/7211 [14:43<15:42,  3.81it/s]

Gaps (ex-reports):  50%|█████     | 3618/7211 [14:43<14:26,  4.15it/s]

Gaps (ex-reports):  50%|█████     | 3619/7211 [14:43<13:32,  4.42it/s]

Gaps (ex-reports):  50%|█████     | 3620/7211 [14:43<13:06,  4.57it/s]

Gaps (ex-reports):  50%|█████     | 3621/7211 [14:44<12:44,  4.70it/s]

Gaps (ex-reports):  50%|█████     | 3622/7211 [14:44<12:33,  4.77it/s]

Gaps (ex-reports):  50%|█████     | 3623/7211 [14:44<12:21,  4.84it/s]

Gaps (ex-reports):  50%|█████     | 3624/7211 [14:44<12:29,  4.79it/s]

Gaps (ex-reports):  50%|█████     | 3625/7211 [14:44<12:19,  4.85it/s]

Gaps (ex-reports):  50%|█████     | 3626/7211 [14:45<12:06,  4.94it/s]

Gaps (ex-reports):  50%|█████     | 3627/7211 [14:45<12:09,  4.91it/s]

Gaps (ex-reports):  50%|█████     | 3628/7211 [14:45<12:00,  4.98it/s]

Gaps (ex-reports):  50%|█████     | 3629/7211 [14:45<12:02,  4.95it/s]

Gaps (ex-reports):  50%|█████     | 3630/7211 [14:45<12:18,  4.85it/s]

Gaps (ex-reports):  50%|█████     | 3631/7211 [14:46<12:10,  4.90it/s]

Gaps (ex-reports):  50%|█████     | 3632/7211 [14:46<11:59,  4.97it/s]

Gaps (ex-reports):  50%|█████     | 3633/7211 [14:46<12:09,  4.90it/s]

Gaps (ex-reports):  50%|█████     | 3634/7211 [14:46<12:09,  4.90it/s]

Gaps (ex-reports):  50%|█████     | 3635/7211 [14:47<12:07,  4.91it/s]

Gaps (ex-reports):  50%|█████     | 3636/7211 [14:47<12:15,  4.86it/s]

Gaps (ex-reports):  50%|█████     | 3637/7211 [14:47<12:11,  4.89it/s]

Gaps (ex-reports):  50%|█████     | 3638/7211 [14:47<12:09,  4.90it/s]

Gaps (ex-reports):  50%|█████     | 3639/7211 [14:47<11:56,  4.98it/s]

Gaps (ex-reports):  50%|█████     | 3640/7211 [14:48<12:00,  4.96it/s]

Gaps (ex-reports):  50%|█████     | 3641/7211 [14:48<11:55,  4.99it/s]

Gaps (ex-reports):  51%|█████     | 3642/7211 [14:48<11:56,  4.98it/s]

Gaps (ex-reports):  51%|█████     | 3643/7211 [14:48<11:51,  5.02it/s]

Gaps (ex-reports):  51%|█████     | 3644/7211 [14:48<11:55,  4.98it/s]

Gaps (ex-reports):  51%|█████     | 3645/7211 [14:49<12:02,  4.94it/s]

Gaps (ex-reports):  51%|█████     | 3646/7211 [14:49<11:52,  5.00it/s]

Gaps (ex-reports):  51%|█████     | 3647/7211 [14:49<11:54,  4.99it/s]

Gaps (ex-reports):  51%|█████     | 3648/7211 [14:49<11:54,  4.99it/s]

Gaps (ex-reports):  51%|█████     | 3649/7211 [14:49<11:52,  5.00it/s]

Gaps (ex-reports):  51%|█████     | 3650/7211 [14:50<11:52,  5.00it/s]

Gaps (ex-reports):  51%|█████     | 3651/7211 [14:50<11:43,  5.06it/s]

Gaps (ex-reports):  51%|█████     | 3652/7211 [14:50<11:37,  5.10it/s]

Gaps (ex-reports):  51%|█████     | 3653/7211 [14:50<11:35,  5.12it/s]

Gaps (ex-reports):  51%|█████     | 3654/7211 [14:50<11:39,  5.08it/s]

Gaps (ex-reports):  51%|█████     | 3655/7211 [14:50<11:43,  5.06it/s]

Gaps (ex-reports):  51%|█████     | 3656/7211 [14:51<11:33,  5.12it/s]

Gaps (ex-reports):  51%|█████     | 3657/7211 [14:51<11:32,  5.14it/s]

Gaps (ex-reports):  51%|█████     | 3658/7211 [14:51<11:30,  5.15it/s]

Gaps (ex-reports):  51%|█████     | 3659/7211 [14:51<11:39,  5.08it/s]

Gaps (ex-reports):  51%|█████     | 3660/7211 [14:51<11:37,  5.09it/s]

Gaps (ex-reports):  51%|█████     | 3661/7211 [14:52<11:31,  5.13it/s]

Gaps (ex-reports):  51%|█████     | 3662/7211 [14:52<11:29,  5.14it/s]

Gaps (ex-reports):  51%|█████     | 3663/7211 [14:52<11:44,  5.03it/s]

Gaps (ex-reports):  51%|█████     | 3664/7211 [14:52<11:43,  5.04it/s]

Gaps (ex-reports):  51%|█████     | 3665/7211 [14:52<11:56,  4.95it/s]

Gaps (ex-reports):  51%|█████     | 3666/7211 [14:53<11:59,  4.93it/s]

Gaps (ex-reports):  51%|█████     | 3667/7211 [14:53<12:09,  4.86it/s]

Gaps (ex-reports):  51%|█████     | 3668/7211 [14:54<28:06,  2.10it/s]

Gaps (ex-reports):  51%|█████     | 3669/7211 [14:54<23:11,  2.55it/s]

Gaps (ex-reports):  51%|█████     | 3670/7211 [14:54<19:35,  3.01it/s]

Gaps (ex-reports):  51%|█████     | 3671/7211 [14:55<17:19,  3.40it/s]

Gaps (ex-reports):  51%|█████     | 3672/7211 [14:55<15:40,  3.76it/s]

Gaps (ex-reports):  51%|█████     | 3673/7211 [14:55<14:40,  4.02it/s]

Gaps (ex-reports):  51%|█████     | 3674/7211 [14:55<13:49,  4.26it/s]

Gaps (ex-reports):  51%|█████     | 3675/7211 [14:55<13:10,  4.47it/s]

Gaps (ex-reports):  51%|█████     | 3676/7211 [14:56<12:59,  4.53it/s]

Gaps (ex-reports):  51%|█████     | 3677/7211 [14:56<12:47,  4.61it/s]

Gaps (ex-reports):  51%|█████     | 3678/7211 [14:56<12:32,  4.69it/s]

Gaps (ex-reports):  51%|█████     | 3679/7211 [14:56<12:21,  4.77it/s]

Gaps (ex-reports):  51%|█████     | 3680/7211 [14:56<12:04,  4.87it/s]

Gaps (ex-reports):  51%|█████     | 3681/7211 [14:57<12:09,  4.84it/s]

Gaps (ex-reports):  51%|█████     | 3682/7211 [14:57<12:21,  4.76it/s]

Gaps (ex-reports):  51%|█████     | 3683/7211 [14:57<12:13,  4.81it/s]

Gaps (ex-reports):  51%|█████     | 3684/7211 [14:57<12:12,  4.81it/s]

Gaps (ex-reports):  51%|█████     | 3685/7211 [14:57<12:05,  4.86it/s]

Gaps (ex-reports):  51%|█████     | 3686/7211 [14:58<11:50,  4.96it/s]

Gaps (ex-reports):  51%|█████     | 3687/7211 [14:58<11:44,  5.00it/s]

Gaps (ex-reports):  51%|█████     | 3688/7211 [14:58<11:48,  4.97it/s]

Gaps (ex-reports):  51%|█████     | 3689/7211 [14:58<11:47,  4.98it/s]

Gaps (ex-reports):  51%|█████     | 3690/7211 [14:58<11:52,  4.94it/s]

Gaps (ex-reports):  51%|█████     | 3691/7211 [14:59<12:11,  4.81it/s]

Gaps (ex-reports):  51%|█████     | 3692/7211 [14:59<12:05,  4.85it/s]

Gaps (ex-reports):  51%|█████     | 3693/7211 [14:59<12:05,  4.85it/s]

Gaps (ex-reports):  51%|█████     | 3694/7211 [14:59<12:02,  4.87it/s]

Gaps (ex-reports):  51%|█████     | 3695/7211 [14:59<12:03,  4.86it/s]

Gaps (ex-reports):  51%|█████▏    | 3696/7211 [15:00<11:59,  4.88it/s]

Gaps (ex-reports):  51%|█████▏    | 3697/7211 [15:00<11:55,  4.91it/s]

Gaps (ex-reports):  51%|█████▏    | 3698/7211 [15:00<11:52,  4.93it/s]

Gaps (ex-reports):  51%|█████▏    | 3699/7211 [15:00<12:02,  4.86it/s]

Gaps (ex-reports):  51%|█████▏    | 3700/7211 [15:01<12:10,  4.81it/s]

Gaps (ex-reports):  51%|█████▏    | 3701/7211 [15:01<11:57,  4.89it/s]

Gaps (ex-reports):  51%|█████▏    | 3702/7211 [15:01<11:43,  4.99it/s]

Gaps (ex-reports):  51%|█████▏    | 3703/7211 [15:01<11:34,  5.05it/s]

Gaps (ex-reports):  51%|█████▏    | 3704/7211 [15:01<11:32,  5.07it/s]

Gaps (ex-reports):  51%|█████▏    | 3705/7211 [15:02<11:40,  5.00it/s]

Gaps (ex-reports):  51%|█████▏    | 3706/7211 [15:02<11:34,  5.05it/s]

Gaps (ex-reports):  51%|█████▏    | 3707/7211 [15:02<11:47,  4.96it/s]

Gaps (ex-reports):  51%|█████▏    | 3708/7211 [15:02<11:45,  4.97it/s]

Gaps (ex-reports):  51%|█████▏    | 3709/7211 [15:02<11:44,  4.97it/s]

Gaps (ex-reports):  51%|█████▏    | 3710/7211 [15:03<11:52,  4.91it/s]

Gaps (ex-reports):  51%|█████▏    | 3711/7211 [15:03<11:49,  4.93it/s]

Gaps (ex-reports):  51%|█████▏    | 3712/7211 [15:03<11:57,  4.87it/s]

Gaps (ex-reports):  51%|█████▏    | 3713/7211 [15:03<11:56,  4.88it/s]

Gaps (ex-reports):  52%|█████▏    | 3714/7211 [15:03<11:50,  4.92it/s]

Gaps (ex-reports):  52%|█████▏    | 3715/7211 [15:04<11:44,  4.96it/s]

Gaps (ex-reports):  52%|█████▏    | 3716/7211 [15:04<11:53,  4.90it/s]

Gaps (ex-reports):  52%|█████▏    | 3717/7211 [15:04<11:46,  4.94it/s]

Gaps (ex-reports):  52%|█████▏    | 3718/7211 [15:04<11:46,  4.95it/s]

Gaps (ex-reports):  52%|█████▏    | 3719/7211 [15:04<11:36,  5.01it/s]

Gaps (ex-reports):  52%|█████▏    | 3720/7211 [15:05<11:42,  4.97it/s]

Gaps (ex-reports):  52%|█████▏    | 3721/7211 [15:05<11:33,  5.04it/s]

Gaps (ex-reports):  52%|█████▏    | 3722/7211 [15:05<11:25,  5.09it/s]

Gaps (ex-reports):  52%|█████▏    | 3723/7211 [15:05<11:40,  4.98it/s]

Gaps (ex-reports):  52%|█████▏    | 3724/7211 [15:05<11:32,  5.04it/s]

Gaps (ex-reports):  52%|█████▏    | 3725/7211 [15:06<11:48,  4.92it/s]

Gaps (ex-reports):  52%|█████▏    | 3726/7211 [15:06<11:48,  4.92it/s]

Gaps (ex-reports):  52%|█████▏    | 3727/7211 [15:06<11:53,  4.88it/s]

Gaps (ex-reports):  52%|█████▏    | 3728/7211 [15:06<12:03,  4.81it/s]

Gaps (ex-reports):  52%|█████▏    | 3729/7211 [15:06<11:55,  4.87it/s]

Gaps (ex-reports):  52%|█████▏    | 3730/7211 [15:07<11:57,  4.85it/s]

Gaps (ex-reports):  52%|█████▏    | 3731/7211 [15:07<12:01,  4.83it/s]

Gaps (ex-reports):  52%|█████▏    | 3732/7211 [15:07<11:57,  4.85it/s]

Gaps (ex-reports):  52%|█████▏    | 3733/7211 [15:07<12:06,  4.79it/s]

Gaps (ex-reports):  52%|█████▏    | 3734/7211 [15:07<11:58,  4.84it/s]

Gaps (ex-reports):  52%|█████▏    | 3735/7211 [15:08<11:40,  4.96it/s]

Gaps (ex-reports):  52%|█████▏    | 3736/7211 [15:08<11:29,  5.04it/s]

Gaps (ex-reports):  52%|█████▏    | 3737/7211 [15:08<11:26,  5.06it/s]

Gaps (ex-reports):  52%|█████▏    | 3738/7211 [15:08<11:38,  4.97it/s]

Gaps (ex-reports):  52%|█████▏    | 3739/7211 [15:08<11:50,  4.89it/s]

Gaps (ex-reports):  52%|█████▏    | 3740/7211 [15:09<11:49,  4.89it/s]

Gaps (ex-reports):  52%|█████▏    | 3741/7211 [15:09<12:26,  4.65it/s]

Gaps (ex-reports):  52%|█████▏    | 3742/7211 [15:09<12:11,  4.75it/s]

Gaps (ex-reports):  52%|█████▏    | 3743/7211 [15:09<12:18,  4.69it/s]

Gaps (ex-reports):  52%|█████▏    | 3744/7211 [15:09<12:19,  4.69it/s]

Gaps (ex-reports):  52%|█████▏    | 3745/7211 [15:10<11:59,  4.82it/s]

Gaps (ex-reports):  52%|█████▏    | 3746/7211 [15:10<11:45,  4.91it/s]

Gaps (ex-reports):  52%|█████▏    | 3747/7211 [15:10<12:26,  4.64it/s]

Gaps (ex-reports):  52%|█████▏    | 3748/7211 [15:10<12:27,  4.64it/s]

Gaps (ex-reports):  52%|█████▏    | 3749/7211 [15:11<12:05,  4.77it/s]

Gaps (ex-reports):  52%|█████▏    | 3750/7211 [15:11<11:46,  4.90it/s]

Gaps (ex-reports):  52%|█████▏    | 3751/7211 [15:11<11:35,  4.97it/s]

Gaps (ex-reports):  52%|█████▏    | 3752/7211 [15:11<11:25,  5.04it/s]

Gaps (ex-reports):  52%|█████▏    | 3753/7211 [15:11<11:15,  5.12it/s]

Gaps (ex-reports):  52%|█████▏    | 3754/7211 [15:11<11:08,  5.17it/s]

Gaps (ex-reports):  52%|█████▏    | 3755/7211 [15:12<11:39,  4.94it/s]

Gaps (ex-reports):  52%|█████▏    | 3756/7211 [15:12<11:33,  4.98it/s]

Gaps (ex-reports):  52%|█████▏    | 3757/7211 [15:12<11:20,  5.07it/s]

Gaps (ex-reports):  52%|█████▏    | 3758/7211 [15:12<11:22,  5.06it/s]

Gaps (ex-reports):  52%|█████▏    | 3759/7211 [15:12<11:32,  4.99it/s]

Gaps (ex-reports):  52%|█████▏    | 3760/7211 [15:13<11:34,  4.97it/s]

Gaps (ex-reports):  52%|█████▏    | 3761/7211 [15:13<11:40,  4.93it/s]

Gaps (ex-reports):  52%|█████▏    | 3762/7211 [15:13<11:35,  4.96it/s]

Gaps (ex-reports):  52%|█████▏    | 3763/7211 [15:13<11:34,  4.96it/s]

Gaps (ex-reports):  52%|█████▏    | 3764/7211 [15:13<11:21,  5.06it/s]

Gaps (ex-reports):  52%|█████▏    | 3765/7211 [15:14<11:15,  5.10it/s]

Gaps (ex-reports):  52%|█████▏    | 3766/7211 [15:14<11:13,  5.12it/s]

Gaps (ex-reports):  52%|█████▏    | 3767/7211 [15:14<11:09,  5.15it/s]

Gaps (ex-reports):  52%|█████▏    | 3768/7211 [15:14<11:06,  5.16it/s]

Gaps (ex-reports):  52%|█████▏    | 3769/7211 [15:14<11:07,  5.16it/s]

Gaps (ex-reports):  52%|█████▏    | 3770/7211 [15:15<11:21,  5.05it/s]

Gaps (ex-reports):  52%|█████▏    | 3771/7211 [15:15<11:17,  5.08it/s]

Gaps (ex-reports):  52%|█████▏    | 3772/7211 [15:15<11:21,  5.05it/s]

Gaps (ex-reports):  52%|█████▏    | 3773/7211 [15:15<11:15,  5.09it/s]

Gaps (ex-reports):  52%|█████▏    | 3774/7211 [15:15<11:15,  5.09it/s]

Gaps (ex-reports):  52%|█████▏    | 3775/7211 [15:16<11:28,  4.99it/s]

Gaps (ex-reports):  52%|█████▏    | 3776/7211 [15:16<11:34,  4.95it/s]

Gaps (ex-reports):  52%|█████▏    | 3777/7211 [15:16<11:48,  4.85it/s]

Gaps (ex-reports):  52%|█████▏    | 3778/7211 [15:16<11:37,  4.92it/s]

Gaps (ex-reports):  52%|█████▏    | 3779/7211 [15:16<11:49,  4.84it/s]

Gaps (ex-reports):  52%|█████▏    | 3780/7211 [15:17<12:09,  4.70it/s]

Gaps (ex-reports):  52%|█████▏    | 3781/7211 [15:17<11:57,  4.78it/s]

Gaps (ex-reports):  52%|█████▏    | 3782/7211 [15:17<11:46,  4.85it/s]

Gaps (ex-reports):  52%|█████▏    | 3783/7211 [15:17<11:41,  4.89it/s]

Gaps (ex-reports):  52%|█████▏    | 3784/7211 [15:18<11:25,  5.00it/s]

Gaps (ex-reports):  52%|█████▏    | 3785/7211 [15:18<11:35,  4.92it/s]

Gaps (ex-reports):  53%|█████▎    | 3786/7211 [15:18<11:27,  4.98it/s]

Gaps (ex-reports):  53%|█████▎    | 3787/7211 [15:18<11:43,  4.87it/s]

Gaps (ex-reports):  53%|█████▎    | 3788/7211 [15:18<11:36,  4.92it/s]

Gaps (ex-reports):  53%|█████▎    | 3789/7211 [15:19<11:40,  4.88it/s]

Gaps (ex-reports):  53%|█████▎    | 3790/7211 [15:19<11:45,  4.85it/s]

Gaps (ex-reports):  53%|█████▎    | 3791/7211 [15:19<11:40,  4.88it/s]

Gaps (ex-reports):  53%|█████▎    | 3792/7211 [15:19<11:43,  4.86it/s]

Gaps (ex-reports):  53%|█████▎    | 3793/7211 [15:19<11:39,  4.88it/s]

Gaps (ex-reports):  53%|█████▎    | 3794/7211 [15:20<11:37,  4.90it/s]

Gaps (ex-reports):  53%|█████▎    | 3795/7211 [15:20<11:38,  4.89it/s]

Gaps (ex-reports):  53%|█████▎    | 3796/7211 [15:20<11:30,  4.94it/s]

Gaps (ex-reports):  53%|█████▎    | 3797/7211 [15:20<11:32,  4.93it/s]

Gaps (ex-reports):  53%|█████▎    | 3798/7211 [15:20<11:36,  4.90it/s]

Gaps (ex-reports):  53%|█████▎    | 3799/7211 [15:21<11:24,  4.99it/s]

Gaps (ex-reports):  53%|█████▎    | 3800/7211 [15:21<11:15,  5.05it/s]

Gaps (ex-reports):  53%|█████▎    | 3801/7211 [15:21<11:27,  4.96it/s]

Gaps (ex-reports):  53%|█████▎    | 3802/7211 [15:21<11:38,  4.88it/s]

Gaps (ex-reports):  53%|█████▎    | 3803/7211 [15:21<11:38,  4.88it/s]

Gaps (ex-reports):  53%|█████▎    | 3804/7211 [15:22<11:37,  4.89it/s]

Gaps (ex-reports):  53%|█████▎    | 3805/7211 [15:22<11:22,  4.99it/s]

Gaps (ex-reports):  53%|█████▎    | 3806/7211 [15:22<11:15,  5.04it/s]

Gaps (ex-reports):  53%|█████▎    | 3807/7211 [15:22<11:30,  4.93it/s]

Gaps (ex-reports):  53%|█████▎    | 3808/7211 [15:22<11:30,  4.93it/s]

Gaps (ex-reports):  53%|█████▎    | 3809/7211 [15:23<11:20,  5.00it/s]

Gaps (ex-reports):  53%|█████▎    | 3810/7211 [15:23<11:30,  4.92it/s]

Gaps (ex-reports):  53%|█████▎    | 3811/7211 [15:23<11:20,  4.99it/s]

Gaps (ex-reports):  53%|█████▎    | 3812/7211 [15:23<11:22,  4.98it/s]

Gaps (ex-reports):  53%|█████▎    | 3813/7211 [15:23<11:23,  4.97it/s]

Gaps (ex-reports):  53%|█████▎    | 3814/7211 [15:24<11:26,  4.95it/s]

Gaps (ex-reports):  53%|█████▎    | 3815/7211 [15:24<11:14,  5.03it/s]

Gaps (ex-reports):  53%|█████▎    | 3816/7211 [15:24<11:11,  5.06it/s]

Gaps (ex-reports):  53%|█████▎    | 3817/7211 [15:24<11:18,  5.00it/s]

Gaps (ex-reports):  53%|█████▎    | 3818/7211 [15:24<11:25,  4.95it/s]

Gaps (ex-reports):  53%|█████▎    | 3819/7211 [15:25<11:17,  5.01it/s]

Gaps (ex-reports):  53%|█████▎    | 3820/7211 [15:25<11:06,  5.09it/s]

Gaps (ex-reports):  53%|█████▎    | 3821/7211 [15:25<11:17,  5.00it/s]

Gaps (ex-reports):  53%|█████▎    | 3822/7211 [15:25<11:07,  5.08it/s]

Gaps (ex-reports):  53%|█████▎    | 3823/7211 [15:25<11:01,  5.12it/s]

Gaps (ex-reports):  53%|█████▎    | 3824/7211 [15:26<11:16,  5.00it/s]

Gaps (ex-reports):  53%|█████▎    | 3825/7211 [15:26<11:15,  5.01it/s]

Gaps (ex-reports):  53%|█████▎    | 3826/7211 [15:26<11:06,  5.08it/s]

Gaps (ex-reports):  53%|█████▎    | 3827/7211 [15:26<11:12,  5.03it/s]

Gaps (ex-reports):  53%|█████▎    | 3828/7211 [15:26<11:00,  5.12it/s]

Gaps (ex-reports):  53%|█████▎    | 3829/7211 [15:27<10:59,  5.13it/s]

Gaps (ex-reports):  53%|█████▎    | 3830/7211 [15:27<11:05,  5.08it/s]

Gaps (ex-reports):  53%|█████▎    | 3831/7211 [15:27<11:16,  4.99it/s]

Gaps (ex-reports):  53%|█████▎    | 3832/7211 [15:27<11:19,  4.97it/s]

Gaps (ex-reports):  53%|█████▎    | 3833/7211 [15:27<11:28,  4.90it/s]

Gaps (ex-reports):  53%|█████▎    | 3834/7211 [15:28<11:30,  4.89it/s]

Gaps (ex-reports):  53%|█████▎    | 3835/7211 [15:28<11:37,  4.84it/s]

Gaps (ex-reports):  53%|█████▎    | 3836/7211 [15:28<11:24,  4.93it/s]

Gaps (ex-reports):  53%|█████▎    | 3837/7211 [15:28<11:34,  4.86it/s]

Gaps (ex-reports):  53%|█████▎    | 3838/7211 [15:28<11:26,  4.91it/s]

Gaps (ex-reports):  53%|█████▎    | 3839/7211 [15:29<11:25,  4.92it/s]

Gaps (ex-reports):  53%|█████▎    | 3840/7211 [15:29<11:20,  4.96it/s]

Gaps (ex-reports):  53%|█████▎    | 3841/7211 [15:29<11:36,  4.84it/s]

Gaps (ex-reports):  53%|█████▎    | 3842/7211 [15:29<11:42,  4.80it/s]

Gaps (ex-reports):  53%|█████▎    | 3843/7211 [15:29<11:47,  4.76it/s]

Gaps (ex-reports):  53%|█████▎    | 3844/7211 [15:30<11:40,  4.80it/s]

Gaps (ex-reports):  53%|█████▎    | 3845/7211 [15:30<11:46,  4.77it/s]

Gaps (ex-reports):  53%|█████▎    | 3846/7211 [15:30<11:39,  4.81it/s]

Gaps (ex-reports):  53%|█████▎    | 3847/7211 [15:30<11:34,  4.84it/s]

Gaps (ex-reports):  53%|█████▎    | 3848/7211 [15:30<11:26,  4.90it/s]

Gaps (ex-reports):  53%|█████▎    | 3849/7211 [15:31<11:33,  4.85it/s]

Gaps (ex-reports):  53%|█████▎    | 3850/7211 [15:31<11:55,  4.70it/s]

Gaps (ex-reports):  53%|█████▎    | 3851/7211 [15:31<11:49,  4.74it/s]

Gaps (ex-reports):  53%|█████▎    | 3852/7211 [15:31<11:52,  4.71it/s]

Gaps (ex-reports):  53%|█████▎    | 3853/7211 [15:32<11:28,  4.87it/s]

Gaps (ex-reports):  53%|█████▎    | 3854/7211 [15:32<11:26,  4.89it/s]

Gaps (ex-reports):  53%|█████▎    | 3855/7211 [15:32<11:21,  4.92it/s]

Gaps (ex-reports):  53%|█████▎    | 3856/7211 [15:32<11:40,  4.79it/s]

Gaps (ex-reports):  53%|█████▎    | 3857/7211 [15:32<11:41,  4.78it/s]

Gaps (ex-reports):  54%|█████▎    | 3858/7211 [15:33<11:34,  4.83it/s]

Gaps (ex-reports):  54%|█████▎    | 3859/7211 [15:33<11:41,  4.78it/s]

Gaps (ex-reports):  54%|█████▎    | 3860/7211 [15:33<11:29,  4.86it/s]

Gaps (ex-reports):  54%|█████▎    | 3861/7211 [15:33<11:45,  4.75it/s]

Gaps (ex-reports):  54%|█████▎    | 3862/7211 [15:33<11:35,  4.81it/s]

Gaps (ex-reports):  54%|█████▎    | 3863/7211 [15:34<11:30,  4.85it/s]

Gaps (ex-reports):  54%|█████▎    | 3864/7211 [15:34<11:32,  4.84it/s]

Gaps (ex-reports):  54%|█████▎    | 3865/7211 [15:34<11:28,  4.86it/s]

Gaps (ex-reports):  54%|█████▎    | 3866/7211 [15:34<11:27,  4.87it/s]

Gaps (ex-reports):  54%|█████▎    | 3867/7211 [15:34<11:24,  4.89it/s]

Gaps (ex-reports):  54%|█████▎    | 3868/7211 [15:35<11:14,  4.96it/s]

Gaps (ex-reports):  54%|█████▎    | 3869/7211 [15:35<11:04,  5.03it/s]

Gaps (ex-reports):  54%|█████▎    | 3870/7211 [15:35<10:57,  5.08it/s]

Gaps (ex-reports):  54%|█████▎    | 3871/7211 [15:35<10:51,  5.13it/s]

Gaps (ex-reports):  54%|█████▎    | 3872/7211 [15:35<11:00,  5.05it/s]

Gaps (ex-reports):  54%|█████▎    | 3873/7211 [15:36<11:12,  4.96it/s]

Gaps (ex-reports):  54%|█████▎    | 3874/7211 [15:36<11:13,  4.95it/s]

Gaps (ex-reports):  54%|█████▎    | 3875/7211 [15:36<11:22,  4.89it/s]

Gaps (ex-reports):  54%|█████▍    | 3876/7211 [15:36<11:27,  4.85it/s]

Gaps (ex-reports):  54%|█████▍    | 3877/7211 [15:36<11:28,  4.84it/s]

Gaps (ex-reports):  54%|█████▍    | 3878/7211 [15:37<11:50,  4.69it/s]

Gaps (ex-reports):  54%|█████▍    | 3879/7211 [15:37<11:39,  4.76it/s]

Gaps (ex-reports):  54%|█████▍    | 3880/7211 [15:37<12:00,  4.62it/s]

Gaps (ex-reports):  54%|█████▍    | 3881/7211 [15:37<11:49,  4.69it/s]

Gaps (ex-reports):  54%|█████▍    | 3882/7211 [15:37<11:35,  4.78it/s]

Gaps (ex-reports):  54%|█████▍    | 3883/7211 [15:38<11:51,  4.68it/s]

Gaps (ex-reports):  54%|█████▍    | 3884/7211 [15:38<11:39,  4.76it/s]

Gaps (ex-reports):  54%|█████▍    | 3885/7211 [15:38<11:22,  4.87it/s]

Gaps (ex-reports):  54%|█████▍    | 3886/7211 [15:38<11:23,  4.87it/s]

Gaps (ex-reports):  54%|█████▍    | 3887/7211 [15:39<11:35,  4.78it/s]

Gaps (ex-reports):  54%|█████▍    | 3888/7211 [15:39<11:43,  4.72it/s]

Gaps (ex-reports):  54%|█████▍    | 3889/7211 [15:39<11:48,  4.69it/s]

Gaps (ex-reports):  54%|█████▍    | 3890/7211 [15:39<11:46,  4.70it/s]

Gaps (ex-reports):  54%|█████▍    | 3891/7211 [15:39<11:32,  4.80it/s]

Gaps (ex-reports):  54%|█████▍    | 3892/7211 [15:40<11:31,  4.80it/s]

Gaps (ex-reports):  54%|█████▍    | 3893/7211 [15:40<11:26,  4.84it/s]

Gaps (ex-reports):  54%|█████▍    | 3894/7211 [15:40<11:42,  4.72it/s]

Gaps (ex-reports):  54%|█████▍    | 3895/7211 [15:40<11:39,  4.74it/s]

Gaps (ex-reports):  54%|█████▍    | 3896/7211 [15:40<11:37,  4.75it/s]

Gaps (ex-reports):  54%|█████▍    | 3897/7211 [15:41<12:00,  4.60it/s]

Gaps (ex-reports):  54%|█████▍    | 3898/7211 [15:41<11:50,  4.66it/s]

Gaps (ex-reports):  54%|█████▍    | 3899/7211 [15:41<11:44,  4.70it/s]

Gaps (ex-reports):  54%|█████▍    | 3900/7211 [15:41<11:31,  4.79it/s]

Gaps (ex-reports):  54%|█████▍    | 3901/7211 [15:41<11:22,  4.85it/s]

Gaps (ex-reports):  54%|█████▍    | 3902/7211 [15:42<11:24,  4.84it/s]

Gaps (ex-reports):  54%|█████▍    | 3903/7211 [15:42<11:06,  4.96it/s]

Gaps (ex-reports):  54%|█████▍    | 3904/7211 [15:42<10:55,  5.04it/s]

Gaps (ex-reports):  54%|█████▍    | 3905/7211 [15:42<10:57,  5.03it/s]

Gaps (ex-reports):  54%|█████▍    | 3906/7211 [15:42<10:47,  5.11it/s]

Gaps (ex-reports):  54%|█████▍    | 3907/7211 [15:43<10:54,  5.04it/s]

Gaps (ex-reports):  54%|█████▍    | 3908/7211 [15:43<10:48,  5.09it/s]

Gaps (ex-reports):  54%|█████▍    | 3909/7211 [15:43<10:45,  5.12it/s]

Gaps (ex-reports):  54%|█████▍    | 3910/7211 [15:43<10:43,  5.13it/s]

Gaps (ex-reports):  54%|█████▍    | 3911/7211 [15:43<10:56,  5.03it/s]

Gaps (ex-reports):  54%|█████▍    | 3912/7211 [15:44<10:45,  5.11it/s]

Gaps (ex-reports):  54%|█████▍    | 3913/7211 [15:44<11:01,  4.98it/s]

Gaps (ex-reports):  54%|█████▍    | 3914/7211 [15:44<11:38,  4.72it/s]

Gaps (ex-reports):  54%|█████▍    | 3915/7211 [15:44<12:40,  4.33it/s]

Gaps (ex-reports):  54%|█████▍    | 3916/7211 [15:45<13:16,  4.14it/s]

Gaps (ex-reports):  54%|█████▍    | 3917/7211 [15:45<13:12,  4.16it/s]

Gaps (ex-reports):  54%|█████▍    | 3918/7211 [15:45<12:33,  4.37it/s]

Gaps (ex-reports):  54%|█████▍    | 3919/7211 [15:45<12:07,  4.52it/s]

Gaps (ex-reports):  54%|█████▍    | 3920/7211 [15:45<12:05,  4.53it/s]

Gaps (ex-reports):  54%|█████▍    | 3921/7211 [15:46<11:40,  4.70it/s]

Gaps (ex-reports):  54%|█████▍    | 3922/7211 [15:46<11:26,  4.79it/s]

Gaps (ex-reports):  54%|█████▍    | 3923/7211 [15:46<11:18,  4.84it/s]

Gaps (ex-reports):  54%|█████▍    | 3924/7211 [15:46<12:00,  4.56it/s]

Gaps (ex-reports):  54%|█████▍    | 3925/7211 [15:48<32:47,  1.67it/s]

Gaps (ex-reports):  54%|█████▍    | 3926/7211 [15:48<26:26,  2.07it/s]

Gaps (ex-reports):  54%|█████▍    | 3927/7211 [15:48<21:51,  2.50it/s]

Gaps (ex-reports):  54%|█████▍    | 3928/7211 [15:48<19:05,  2.87it/s]

Gaps (ex-reports):  54%|█████▍    | 3929/7211 [15:49<16:40,  3.28it/s]

Gaps (ex-reports):  55%|█████▍    | 3930/7211 [15:49<15:05,  3.62it/s]

Gaps (ex-reports):  55%|█████▍    | 3931/7211 [15:49<13:49,  3.95it/s]

Gaps (ex-reports):  55%|█████▍    | 3932/7211 [15:49<13:09,  4.15it/s]

Gaps (ex-reports):  55%|█████▍    | 3933/7211 [15:50<12:35,  4.34it/s]

Gaps (ex-reports):  55%|█████▍    | 3934/7211 [15:50<12:03,  4.53it/s]

Gaps (ex-reports):  55%|█████▍    | 3935/7211 [15:50<11:51,  4.60it/s]

Gaps (ex-reports):  55%|█████▍    | 3936/7211 [15:50<11:39,  4.68it/s]

Gaps (ex-reports):  55%|█████▍    | 3937/7211 [15:50<11:21,  4.80it/s]

Gaps (ex-reports):  55%|█████▍    | 3938/7211 [15:51<11:18,  4.82it/s]

Gaps (ex-reports):  55%|█████▍    | 3939/7211 [15:51<11:03,  4.93it/s]

Gaps (ex-reports):  55%|█████▍    | 3940/7211 [15:51<11:06,  4.91it/s]

Gaps (ex-reports):  55%|█████▍    | 3941/7211 [15:51<11:17,  4.82it/s]

Gaps (ex-reports):  55%|█████▍    | 3942/7211 [15:51<11:12,  4.86it/s]

Gaps (ex-reports):  55%|█████▍    | 3943/7211 [15:52<11:31,  4.72it/s]

Gaps (ex-reports):  55%|█████▍    | 3944/7211 [15:52<11:13,  4.85it/s]

Gaps (ex-reports):  55%|█████▍    | 3945/7211 [15:52<11:06,  4.90it/s]

Gaps (ex-reports):  55%|█████▍    | 3946/7211 [15:52<11:14,  4.84it/s]

Gaps (ex-reports):  55%|█████▍    | 3947/7211 [15:52<11:11,  4.86it/s]

Gaps (ex-reports):  55%|█████▍    | 3948/7211 [15:53<11:04,  4.91it/s]

Gaps (ex-reports):  55%|█████▍    | 3949/7211 [15:53<10:55,  4.97it/s]

Gaps (ex-reports):  55%|█████▍    | 3950/7211 [15:53<10:52,  5.00it/s]

Gaps (ex-reports):  55%|█████▍    | 3951/7211 [15:53<10:54,  4.98it/s]

Gaps (ex-reports):  55%|█████▍    | 3952/7211 [15:53<10:49,  5.02it/s]

Gaps (ex-reports):  55%|█████▍    | 3953/7211 [15:54<10:56,  4.96it/s]

Gaps (ex-reports):  55%|█████▍    | 3954/7211 [15:54<10:59,  4.94it/s]

Gaps (ex-reports):  55%|█████▍    | 3955/7211 [15:54<10:55,  4.97it/s]

Gaps (ex-reports):  55%|█████▍    | 3956/7211 [15:54<10:59,  4.94it/s]

Gaps (ex-reports):  55%|█████▍    | 3957/7211 [15:54<10:47,  5.03it/s]

Gaps (ex-reports):  55%|█████▍    | 3958/7211 [15:55<10:57,  4.95it/s]

Gaps (ex-reports):  55%|█████▍    | 3959/7211 [15:55<10:48,  5.02it/s]

Gaps (ex-reports):  55%|█████▍    | 3960/7211 [15:55<10:58,  4.94it/s]

Gaps (ex-reports):  55%|█████▍    | 3961/7211 [15:55<10:51,  4.99it/s]

Gaps (ex-reports):  55%|█████▍    | 3962/7211 [15:55<11:00,  4.92it/s]

Gaps (ex-reports):  55%|█████▍    | 3963/7211 [15:56<10:59,  4.92it/s]

Gaps (ex-reports):  55%|█████▍    | 3964/7211 [15:56<10:48,  5.01it/s]

Gaps (ex-reports):  55%|█████▍    | 3965/7211 [15:56<10:56,  4.94it/s]

Gaps (ex-reports):  55%|█████▍    | 3966/7211 [15:56<11:07,  4.86it/s]

Gaps (ex-reports):  55%|█████▌    | 3967/7211 [15:56<11:06,  4.87it/s]

Gaps (ex-reports):  55%|█████▌    | 3968/7211 [15:57<11:08,  4.85it/s]

Gaps (ex-reports):  55%|█████▌    | 3969/7211 [15:57<10:57,  4.93it/s]

Gaps (ex-reports):  55%|█████▌    | 3970/7211 [15:57<10:56,  4.94it/s]

Gaps (ex-reports):  55%|█████▌    | 3971/7211 [15:57<10:55,  4.94it/s]

Gaps (ex-reports):  55%|█████▌    | 3972/7211 [15:57<10:53,  4.96it/s]

Gaps (ex-reports):  55%|█████▌    | 3973/7211 [15:58<10:46,  5.01it/s]

Gaps (ex-reports):  55%|█████▌    | 3974/7211 [15:58<10:58,  4.91it/s]

Gaps (ex-reports):  55%|█████▌    | 3975/7211 [15:58<10:59,  4.90it/s]

Gaps (ex-reports):  55%|█████▌    | 3976/7211 [15:58<10:54,  4.94it/s]

Gaps (ex-reports):  55%|█████▌    | 3977/7211 [15:58<10:56,  4.93it/s]

Gaps (ex-reports):  55%|█████▌    | 3978/7211 [15:59<11:02,  4.88it/s]

Gaps (ex-reports):  55%|█████▌    | 3979/7211 [15:59<11:11,  4.81it/s]

Gaps (ex-reports):  55%|█████▌    | 3980/7211 [15:59<11:01,  4.88it/s]

Gaps (ex-reports):  55%|█████▌    | 3981/7211 [15:59<11:05,  4.86it/s]

Gaps (ex-reports):  55%|█████▌    | 3982/7211 [15:59<11:15,  4.78it/s]

Gaps (ex-reports):  55%|█████▌    | 3983/7211 [16:00<10:58,  4.90it/s]

Gaps (ex-reports):  55%|█████▌    | 3984/7211 [16:00<10:44,  5.01it/s]

Gaps (ex-reports):  55%|█████▌    | 3985/7211 [16:00<10:41,  5.03it/s]

Gaps (ex-reports):  55%|█████▌    | 3986/7211 [16:00<10:37,  5.06it/s]

Gaps (ex-reports):  55%|█████▌    | 3987/7211 [16:00<10:38,  5.05it/s]

Gaps (ex-reports):  55%|█████▌    | 3988/7211 [16:01<10:45,  4.99it/s]

Gaps (ex-reports):  55%|█████▌    | 3989/7211 [16:01<10:48,  4.97it/s]

Gaps (ex-reports):  55%|█████▌    | 3990/7211 [16:01<10:54,  4.92it/s]

Gaps (ex-reports):  55%|█████▌    | 3991/7211 [16:01<11:14,  4.78it/s]

Gaps (ex-reports):  55%|█████▌    | 3992/7211 [16:01<10:51,  4.94it/s]

Gaps (ex-reports):  55%|█████▌    | 3993/7211 [16:02<10:49,  4.96it/s]

Gaps (ex-reports):  55%|█████▌    | 3994/7211 [16:02<10:38,  5.04it/s]

Gaps (ex-reports):  55%|█████▌    | 3995/7211 [16:02<10:43,  5.00it/s]

Gaps (ex-reports):  55%|█████▌    | 3996/7211 [16:02<10:47,  4.97it/s]

Gaps (ex-reports):  55%|█████▌    | 3997/7211 [16:02<10:46,  4.97it/s]

Gaps (ex-reports):  55%|█████▌    | 3998/7211 [16:03<10:49,  4.95it/s]

Gaps (ex-reports):  55%|█████▌    | 3999/7211 [16:03<10:39,  5.02it/s]

Gaps (ex-reports):  55%|█████▌    | 4000/7211 [16:03<10:28,  5.11it/s]

Gaps (ex-reports):  55%|█████▌    | 4001/7211 [16:03<10:27,  5.12it/s]

Gaps (ex-reports):  55%|█████▌    | 4002/7211 [16:03<10:45,  4.97it/s]

Gaps (ex-reports):  56%|█████▌    | 4003/7211 [16:04<10:47,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 4004/7211 [16:04<10:36,  5.04it/s]

Gaps (ex-reports):  56%|█████▌    | 4005/7211 [16:04<10:34,  5.05it/s]

Gaps (ex-reports):  56%|█████▌    | 4006/7211 [16:04<10:42,  4.98it/s]

Gaps (ex-reports):  56%|█████▌    | 4007/7211 [16:04<10:38,  5.02it/s]

Gaps (ex-reports):  56%|█████▌    | 4008/7211 [16:05<10:28,  5.10it/s]

Gaps (ex-reports):  56%|█████▌    | 4009/7211 [16:05<10:36,  5.03it/s]

Gaps (ex-reports):  56%|█████▌    | 4010/7211 [16:05<10:29,  5.08it/s]

Gaps (ex-reports):  56%|█████▌    | 4011/7211 [16:05<10:28,  5.09it/s]

Gaps (ex-reports):  56%|█████▌    | 4012/7211 [16:05<10:45,  4.96it/s]

Gaps (ex-reports):  56%|█████▌    | 4013/7211 [16:06<10:42,  4.98it/s]

Gaps (ex-reports):  56%|█████▌    | 4014/7211 [16:06<10:35,  5.03it/s]

Gaps (ex-reports):  56%|█████▌    | 4015/7211 [16:06<10:43,  4.96it/s]

Gaps (ex-reports):  56%|█████▌    | 4016/7211 [16:06<10:52,  4.89it/s]

Gaps (ex-reports):  56%|█████▌    | 4017/7211 [16:06<10:37,  5.01it/s]

Gaps (ex-reports):  56%|█████▌    | 4018/7211 [16:07<10:49,  4.92it/s]

Gaps (ex-reports):  56%|█████▌    | 4019/7211 [16:07<10:49,  4.92it/s]

Gaps (ex-reports):  56%|█████▌    | 4020/7211 [16:07<10:37,  5.00it/s]

Gaps (ex-reports):  56%|█████▌    | 4021/7211 [16:07<10:43,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 4022/7211 [16:07<10:35,  5.02it/s]

Gaps (ex-reports):  56%|█████▌    | 4023/7211 [16:08<10:44,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 4024/7211 [16:08<10:33,  5.03it/s]

Gaps (ex-reports):  56%|█████▌    | 4025/7211 [16:08<10:26,  5.08it/s]

Gaps (ex-reports):  56%|█████▌    | 4026/7211 [16:08<10:20,  5.13it/s]

Gaps (ex-reports):  56%|█████▌    | 4027/7211 [16:08<10:19,  5.14it/s]

Gaps (ex-reports):  56%|█████▌    | 4028/7211 [16:09<10:29,  5.05it/s]

Gaps (ex-reports):  56%|█████▌    | 4029/7211 [16:09<10:38,  4.98it/s]

Gaps (ex-reports):  56%|█████▌    | 4030/7211 [16:09<10:31,  5.04it/s]

Gaps (ex-reports):  56%|█████▌    | 4031/7211 [16:09<10:42,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 4032/7211 [16:09<10:33,  5.02it/s]

Gaps (ex-reports):  56%|█████▌    | 4033/7211 [16:10<10:31,  5.03it/s]

Gaps (ex-reports):  56%|█████▌    | 4034/7211 [16:10<10:36,  5.00it/s]

Gaps (ex-reports):  56%|█████▌    | 4035/7211 [16:10<10:22,  5.10it/s]

Gaps (ex-reports):  56%|█████▌    | 4036/7211 [16:10<10:37,  4.98it/s]

Gaps (ex-reports):  56%|█████▌    | 4037/7211 [16:10<10:28,  5.05it/s]

Gaps (ex-reports):  56%|█████▌    | 4038/7211 [16:11<10:22,  5.09it/s]

Gaps (ex-reports):  56%|█████▌    | 4039/7211 [16:11<10:22,  5.09it/s]

Gaps (ex-reports):  56%|█████▌    | 4040/7211 [16:11<10:14,  5.16it/s]

Gaps (ex-reports):  56%|█████▌    | 4041/7211 [16:11<10:15,  5.15it/s]

Gaps (ex-reports):  56%|█████▌    | 4042/7211 [16:24<3:23:16,  3.85s/it]

Gaps (ex-reports):  56%|█████▌    | 4043/7211 [16:24<2:25:25,  2.75s/it]

Gaps (ex-reports):  56%|█████▌    | 4044/7211 [16:24<1:44:47,  1.99s/it]

Gaps (ex-reports):  56%|█████▌    | 4045/7211 [16:24<1:16:46,  1.46s/it]

Gaps (ex-reports):  56%|█████▌    | 4046/7211 [16:24<56:50,  1.08s/it]

Gaps (ex-reports):  56%|█████▌    | 4047/7211 [16:25<43:04,  1.22it/s]

Gaps (ex-reports):  56%|█████▌    | 4048/7211 [16:25<33:32,  1.57it/s]

Gaps (ex-reports):  56%|█████▌    | 4049/7211 [16:25<26:31,  1.99it/s]

Gaps (ex-reports):  56%|█████▌    | 4050/7211 [16:25<21:50,  2.41it/s]

Gaps (ex-reports):  56%|█████▌    | 4051/7211 [16:25<18:34,  2.84it/s]

Gaps (ex-reports):  56%|█████▌    | 4052/7211 [16:26<16:18,  3.23it/s]

Gaps (ex-reports):  56%|█████▌    | 4053/7211 [16:26<14:44,  3.57it/s]

Gaps (ex-reports):  56%|█████▌    | 4054/7211 [16:26<13:30,  3.89it/s]

Gaps (ex-reports):  56%|█████▌    | 4055/7211 [16:26<12:39,  4.16it/s]

Gaps (ex-reports):  56%|█████▌    | 4056/7211 [16:26<11:55,  4.41it/s]

Gaps (ex-reports):  56%|█████▋    | 4057/7211 [16:27<11:25,  4.60it/s]

Gaps (ex-reports):  56%|█████▋    | 4058/7211 [16:27<11:15,  4.67it/s]

Gaps (ex-reports):  56%|█████▋    | 4059/7211 [16:27<11:08,  4.71it/s]

Gaps (ex-reports):  56%|█████▋    | 4060/7211 [16:27<11:09,  4.71it/s]

Gaps (ex-reports):  56%|█████▋    | 4061/7211 [16:27<11:00,  4.77it/s]

Gaps (ex-reports):  56%|█████▋    | 4062/7211 [16:28<10:43,  4.90it/s]

Gaps (ex-reports):  56%|█████▋    | 4063/7211 [16:28<10:36,  4.94it/s]

Gaps (ex-reports):  56%|█████▋    | 4064/7211 [16:28<10:38,  4.93it/s]

Gaps (ex-reports):  56%|█████▋    | 4065/7211 [16:28<10:50,  4.84it/s]

Gaps (ex-reports):  56%|█████▋    | 4066/7211 [16:28<11:02,  4.75it/s]

Gaps (ex-reports):  56%|█████▋    | 4067/7211 [16:29<11:40,  4.49it/s]

Gaps (ex-reports):  56%|█████▋    | 4068/7211 [16:29<11:26,  4.58it/s]

Gaps (ex-reports):  56%|█████▋    | 4069/7211 [16:29<11:03,  4.73it/s]

Gaps (ex-reports):  56%|█████▋    | 4070/7211 [16:29<10:45,  4.87it/s]

Gaps (ex-reports):  56%|█████▋    | 4071/7211 [16:30<10:54,  4.80it/s]

Gaps (ex-reports):  56%|█████▋    | 4072/7211 [16:30<10:42,  4.89it/s]

Gaps (ex-reports):  56%|█████▋    | 4073/7211 [16:30<10:39,  4.90it/s]

Gaps (ex-reports):  56%|█████▋    | 4074/7211 [16:30<10:39,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4075/7211 [16:30<10:52,  4.81it/s]

Gaps (ex-reports):  57%|█████▋    | 4076/7211 [16:31<10:53,  4.80it/s]

Gaps (ex-reports):  57%|█████▋    | 4077/7211 [16:31<10:41,  4.89it/s]

Gaps (ex-reports):  57%|█████▋    | 4078/7211 [16:31<10:55,  4.78it/s]

Gaps (ex-reports):  57%|█████▋    | 4079/7211 [16:31<10:37,  4.91it/s]

Gaps (ex-reports):  57%|█████▋    | 4080/7211 [16:31<10:32,  4.95it/s]

Gaps (ex-reports):  57%|█████▋    | 4081/7211 [16:32<10:36,  4.91it/s]

Gaps (ex-reports):  57%|█████▋    | 4082/7211 [16:32<10:34,  4.93it/s]

Gaps (ex-reports):  57%|█████▋    | 4083/7211 [16:32<10:26,  4.99it/s]

Gaps (ex-reports):  57%|█████▋    | 4084/7211 [16:32<10:25,  5.00it/s]

Gaps (ex-reports):  57%|█████▋    | 4085/7211 [16:32<10:35,  4.92it/s]

Gaps (ex-reports):  57%|█████▋    | 4086/7211 [16:33<10:35,  4.91it/s]

Gaps (ex-reports):  57%|█████▋    | 4087/7211 [16:33<10:50,  4.80it/s]

Gaps (ex-reports):  57%|█████▋    | 4088/7211 [16:33<10:45,  4.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4089/7211 [16:33<10:36,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4090/7211 [16:33<10:44,  4.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4091/7211 [16:34<10:40,  4.87it/s]

Gaps (ex-reports):  57%|█████▋    | 4092/7211 [16:34<10:32,  4.93it/s]

Gaps (ex-reports):  57%|█████▋    | 4093/7211 [16:34<10:36,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4094/7211 [16:34<10:38,  4.88it/s]

Gaps (ex-reports):  57%|█████▋    | 4095/7211 [16:34<10:40,  4.86it/s]

Gaps (ex-reports):  57%|█████▋    | 4096/7211 [16:35<10:28,  4.96it/s]

Gaps (ex-reports):  57%|█████▋    | 4097/7211 [16:35<10:25,  4.98it/s]

Gaps (ex-reports):  57%|█████▋    | 4098/7211 [16:35<10:32,  4.92it/s]

Gaps (ex-reports):  57%|█████▋    | 4099/7211 [16:35<10:27,  4.96it/s]

Gaps (ex-reports):  57%|█████▋    | 4100/7211 [16:35<10:19,  5.02it/s]

Gaps (ex-reports):  57%|█████▋    | 4101/7211 [16:36<10:13,  5.07it/s]

Gaps (ex-reports):  57%|█████▋    | 4102/7211 [16:36<10:11,  5.09it/s]

Gaps (ex-reports):  57%|█████▋    | 4103/7211 [16:36<10:17,  5.03it/s]

Gaps (ex-reports):  57%|█████▋    | 4104/7211 [16:36<10:10,  5.09it/s]

Gaps (ex-reports):  57%|█████▋    | 4105/7211 [16:36<10:08,  5.11it/s]

Gaps (ex-reports):  57%|█████▋    | 4106/7211 [16:37<10:26,  4.95it/s]

Gaps (ex-reports):  57%|█████▋    | 4107/7211 [16:37<10:36,  4.88it/s]

Gaps (ex-reports):  57%|█████▋    | 4108/7211 [16:37<10:28,  4.93it/s]

Gaps (ex-reports):  57%|█████▋    | 4109/7211 [16:37<10:32,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4110/7211 [16:37<10:38,  4.86it/s]

Gaps (ex-reports):  57%|█████▋    | 4111/7211 [16:38<10:41,  4.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4112/7211 [16:38<10:25,  4.95it/s]

Gaps (ex-reports):  57%|█████▋    | 4113/7211 [16:38<10:28,  4.93it/s]

Gaps (ex-reports):  57%|█████▋    | 4114/7211 [16:38<10:15,  5.03it/s]

Gaps (ex-reports):  57%|█████▋    | 4115/7211 [16:38<10:06,  5.11it/s]

Gaps (ex-reports):  57%|█████▋    | 4116/7211 [16:39<10:07,  5.10it/s]

Gaps (ex-reports):  57%|█████▋    | 4117/7211 [16:39<10:25,  4.95it/s]

Gaps (ex-reports):  57%|█████▋    | 4118/7211 [16:39<10:49,  4.76it/s]

Gaps (ex-reports):  57%|█████▋    | 4119/7211 [16:39<10:41,  4.82it/s]

Gaps (ex-reports):  57%|█████▋    | 4120/7211 [16:40<10:38,  4.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4121/7211 [16:40<10:36,  4.86it/s]

Gaps (ex-reports):  57%|█████▋    | 4122/7211 [16:40<10:40,  4.82it/s]

Gaps (ex-reports):  57%|█████▋    | 4123/7211 [16:40<10:44,  4.79it/s]

Gaps (ex-reports):  57%|█████▋    | 4124/7211 [16:40<10:39,  4.83it/s]

Gaps (ex-reports):  57%|█████▋    | 4125/7211 [16:41<10:48,  4.76it/s]

Gaps (ex-reports):  57%|█████▋    | 4126/7211 [16:41<10:32,  4.88it/s]

Gaps (ex-reports):  57%|█████▋    | 4127/7211 [16:41<10:38,  4.83it/s]

Gaps (ex-reports):  57%|█████▋    | 4128/7211 [16:41<10:35,  4.85it/s]

Gaps (ex-reports):  57%|█████▋    | 4129/7211 [16:41<10:21,  4.96it/s]

Gaps (ex-reports):  57%|█████▋    | 4130/7211 [16:42<10:18,  4.98it/s]

Gaps (ex-reports):  57%|█████▋    | 4131/7211 [16:42<10:26,  4.92it/s]

Gaps (ex-reports):  57%|█████▋    | 4132/7211 [16:42<10:34,  4.86it/s]

Gaps (ex-reports):  57%|█████▋    | 4133/7211 [16:42<10:27,  4.91it/s]

Gaps (ex-reports):  57%|█████▋    | 4134/7211 [16:42<10:26,  4.91it/s]

Gaps (ex-reports):  57%|█████▋    | 4135/7211 [16:43<10:20,  4.96it/s]

Gaps (ex-reports):  57%|█████▋    | 4136/7211 [16:43<10:11,  5.03it/s]

Gaps (ex-reports):  57%|█████▋    | 4137/7211 [16:43<10:07,  5.06it/s]

Gaps (ex-reports):  57%|█████▋    | 4138/7211 [16:43<10:05,  5.07it/s]

Gaps (ex-reports):  57%|█████▋    | 4139/7211 [16:43<10:12,  5.01it/s]

Gaps (ex-reports):  57%|█████▋    | 4140/7211 [16:44<10:26,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4141/7211 [16:44<11:36,  4.41it/s]

Gaps (ex-reports):  57%|█████▋    | 4142/7211 [16:44<11:28,  4.46it/s]

Gaps (ex-reports):  57%|█████▋    | 4143/7211 [16:44<11:12,  4.56it/s]

Gaps (ex-reports):  57%|█████▋    | 4144/7211 [16:44<10:51,  4.71it/s]

Gaps (ex-reports):  57%|█████▋    | 4145/7211 [16:45<10:49,  4.72it/s]

Gaps (ex-reports):  57%|█████▋    | 4146/7211 [16:45<10:46,  4.74it/s]

Gaps (ex-reports):  58%|█████▊    | 4147/7211 [16:45<10:39,  4.79it/s]

Gaps (ex-reports):  58%|█████▊    | 4148/7211 [16:45<10:46,  4.74it/s]

Gaps (ex-reports):  58%|█████▊    | 4149/7211 [16:46<10:54,  4.68it/s]

Gaps (ex-reports):  58%|█████▊    | 4150/7211 [16:46<10:49,  4.72it/s]

Gaps (ex-reports):  58%|█████▊    | 4151/7211 [16:46<10:30,  4.85it/s]

Gaps (ex-reports):  58%|█████▊    | 4152/7211 [16:46<10:29,  4.86it/s]

Gaps (ex-reports):  58%|█████▊    | 4153/7211 [16:46<10:34,  4.82it/s]

Gaps (ex-reports):  58%|█████▊    | 4154/7211 [16:47<10:31,  4.84it/s]

Gaps (ex-reports):  58%|█████▊    | 4155/7211 [16:47<10:16,  4.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4156/7211 [16:47<10:16,  4.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4157/7211 [16:47<11:03,  4.60it/s]

Gaps (ex-reports):  58%|█████▊    | 4158/7211 [16:47<10:51,  4.69it/s]

Gaps (ex-reports):  58%|█████▊    | 4159/7211 [16:48<10:43,  4.75it/s]

Gaps (ex-reports):  58%|█████▊    | 4160/7211 [16:48<10:29,  4.85it/s]

Gaps (ex-reports):  58%|█████▊    | 4161/7211 [16:48<10:27,  4.86it/s]

Gaps (ex-reports):  58%|█████▊    | 4162/7211 [16:48<10:22,  4.90it/s]

Gaps (ex-reports):  58%|█████▊    | 4163/7211 [16:48<10:20,  4.92it/s]

Gaps (ex-reports):  58%|█████▊    | 4164/7211 [16:49<10:20,  4.91it/s]

Gaps (ex-reports):  58%|█████▊    | 4165/7211 [16:49<10:20,  4.91it/s]

Gaps (ex-reports):  58%|█████▊    | 4166/7211 [16:49<10:23,  4.89it/s]

Gaps (ex-reports):  58%|█████▊    | 4167/7211 [16:49<11:17,  4.49it/s]

Gaps (ex-reports):  58%|█████▊    | 4168/7211 [16:50<11:54,  4.26it/s]

Gaps (ex-reports):  58%|█████▊    | 4169/7211 [16:50<12:05,  4.19it/s]

Gaps (ex-reports):  58%|█████▊    | 4170/7211 [16:50<12:56,  3.91it/s]

Gaps (ex-reports):  58%|█████▊    | 4171/7211 [16:50<12:14,  4.14it/s]

Gaps (ex-reports):  58%|█████▊    | 4172/7211 [16:51<11:39,  4.35it/s]

Gaps (ex-reports):  58%|█████▊    | 4173/7211 [16:51<11:08,  4.54it/s]

Gaps (ex-reports):  58%|█████▊    | 4174/7211 [16:51<10:54,  4.64it/s]

Gaps (ex-reports):  58%|█████▊    | 4175/7211 [16:51<10:43,  4.72it/s]

Gaps (ex-reports):  58%|█████▊    | 4176/7211 [16:51<10:28,  4.83it/s]

Gaps (ex-reports):  58%|█████▊    | 4177/7211 [16:52<10:13,  4.95it/s]

Gaps (ex-reports):  58%|█████▊    | 4178/7211 [16:52<10:07,  4.99it/s]

Gaps (ex-reports):  58%|█████▊    | 4179/7211 [16:52<10:13,  4.94it/s]

Gaps (ex-reports):  58%|█████▊    | 4180/7211 [16:52<14:22,  3.51it/s]

Gaps (ex-reports):  58%|█████▊    | 4181/7211 [16:53<13:02,  3.87it/s]

Gaps (ex-reports):  58%|█████▊    | 4182/7211 [16:53<12:16,  4.11it/s]

Gaps (ex-reports):  58%|█████▊    | 4183/7211 [16:53<11:29,  4.39it/s]

Gaps (ex-reports):  58%|█████▊    | 4184/7211 [16:53<11:11,  4.51it/s]

Gaps (ex-reports):  58%|█████▊    | 4185/7211 [16:53<10:49,  4.66it/s]

Gaps (ex-reports):  58%|█████▊    | 4186/7211 [16:54<10:28,  4.81it/s]

Gaps (ex-reports):  58%|█████▊    | 4187/7211 [16:54<10:24,  4.84it/s]

Gaps (ex-reports):  58%|█████▊    | 4188/7211 [16:54<10:11,  4.95it/s]

Gaps (ex-reports):  58%|█████▊    | 4189/7211 [16:54<10:21,  4.86it/s]

Gaps (ex-reports):  58%|█████▊    | 4190/7211 [16:54<10:15,  4.91it/s]

Gaps (ex-reports):  58%|█████▊    | 4191/7211 [16:55<10:03,  5.01it/s]

Gaps (ex-reports):  58%|█████▊    | 4192/7211 [16:55<10:01,  5.02it/s]

Gaps (ex-reports):  58%|█████▊    | 4193/7211 [16:55<09:53,  5.09it/s]

Gaps (ex-reports):  58%|█████▊    | 4194/7211 [16:55<09:58,  5.04it/s]

Gaps (ex-reports):  58%|█████▊    | 4195/7211 [16:55<10:10,  4.94it/s]

Gaps (ex-reports):  58%|█████▊    | 4196/7211 [16:56<10:00,  5.02it/s]

Gaps (ex-reports):  58%|█████▊    | 4197/7211 [16:56<10:07,  4.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4198/7211 [16:56<10:13,  4.91it/s]

Gaps (ex-reports):  58%|█████▊    | 4199/7211 [16:56<10:01,  5.01it/s]

Gaps (ex-reports):  58%|█████▊    | 4200/7211 [16:56<10:09,  4.94it/s]

Gaps (ex-reports):  58%|█████▊    | 4201/7211 [16:57<09:58,  5.03it/s]

Gaps (ex-reports):  58%|█████▊    | 4202/7211 [16:57<10:11,  4.92it/s]

Gaps (ex-reports):  58%|█████▊    | 4203/7211 [16:57<10:12,  4.91it/s]

Gaps (ex-reports):  58%|█████▊    | 4204/7211 [16:57<10:03,  4.98it/s]

Gaps (ex-reports):  58%|█████▊    | 4205/7211 [16:57<09:55,  5.05it/s]

Gaps (ex-reports):  58%|█████▊    | 4206/7211 [16:58<09:49,  5.10it/s]

Gaps (ex-reports):  58%|█████▊    | 4207/7211 [16:58<09:51,  5.08it/s]

Gaps (ex-reports):  58%|█████▊    | 4208/7211 [16:58<09:42,  5.16it/s]

Gaps (ex-reports):  58%|█████▊    | 4209/7211 [16:58<09:44,  5.13it/s]

Gaps (ex-reports):  58%|█████▊    | 4210/7211 [16:58<09:50,  5.09it/s]

Gaps (ex-reports):  58%|█████▊    | 4211/7211 [16:59<09:49,  5.09it/s]

Gaps (ex-reports):  58%|█████▊    | 4212/7211 [16:59<09:43,  5.14it/s]

Gaps (ex-reports):  58%|█████▊    | 4213/7211 [16:59<09:39,  5.17it/s]

Gaps (ex-reports):  58%|█████▊    | 4214/7211 [16:59<09:42,  5.14it/s]

Gaps (ex-reports):  58%|█████▊    | 4215/7211 [16:59<09:44,  5.13it/s]

Gaps (ex-reports):  58%|█████▊    | 4216/7211 [17:00<10:04,  4.95it/s]

Gaps (ex-reports):  58%|█████▊    | 4217/7211 [17:00<09:53,  5.04it/s]

Gaps (ex-reports):  58%|█████▊    | 4218/7211 [17:00<10:07,  4.93it/s]

Gaps (ex-reports):  59%|█████▊    | 4219/7211 [17:00<10:06,  4.93it/s]

Gaps (ex-reports):  59%|█████▊    | 4220/7211 [17:00<10:15,  4.86it/s]

Gaps (ex-reports):  59%|█████▊    | 4221/7211 [17:01<10:15,  4.86it/s]

Gaps (ex-reports):  59%|█████▊    | 4222/7211 [17:01<10:07,  4.92it/s]

Gaps (ex-reports):  59%|█████▊    | 4223/7211 [17:01<10:04,  4.94it/s]

Gaps (ex-reports):  59%|█████▊    | 4224/7211 [17:01<10:09,  4.90it/s]

Gaps (ex-reports):  59%|█████▊    | 4225/7211 [17:01<10:07,  4.91it/s]

Gaps (ex-reports):  59%|█████▊    | 4226/7211 [17:02<10:08,  4.90it/s]

Gaps (ex-reports):  59%|█████▊    | 4227/7211 [17:02<10:23,  4.79it/s]

Gaps (ex-reports):  59%|█████▊    | 4228/7211 [17:02<10:07,  4.91it/s]

Gaps (ex-reports):  59%|█████▊    | 4229/7211 [17:02<09:56,  5.00it/s]

Gaps (ex-reports):  59%|█████▊    | 4230/7211 [17:02<09:47,  5.07it/s]

Gaps (ex-reports):  59%|█████▊    | 4231/7211 [17:03<09:41,  5.13it/s]

Gaps (ex-reports):  59%|█████▊    | 4232/7211 [17:03<09:40,  5.13it/s]

Gaps (ex-reports):  59%|█████▊    | 4233/7211 [17:03<09:55,  5.00it/s]

Gaps (ex-reports):  59%|█████▊    | 4234/7211 [17:03<10:14,  4.85it/s]

Gaps (ex-reports):  59%|█████▊    | 4235/7211 [17:03<10:00,  4.95it/s]

Gaps (ex-reports):  59%|█████▊    | 4236/7211 [17:04<09:52,  5.02it/s]

Gaps (ex-reports):  59%|█████▉    | 4237/7211 [17:04<09:43,  5.09it/s]

Gaps (ex-reports):  59%|█████▉    | 4238/7211 [17:04<09:41,  5.11it/s]

Gaps (ex-reports):  59%|█████▉    | 4239/7211 [17:04<09:43,  5.09it/s]

Gaps (ex-reports):  59%|█████▉    | 4240/7211 [17:04<09:48,  5.05it/s]

Gaps (ex-reports):  59%|█████▉    | 4241/7211 [17:05<09:45,  5.08it/s]

Gaps (ex-reports):  59%|█████▉    | 4242/7211 [17:05<09:49,  5.03it/s]

Gaps (ex-reports):  59%|█████▉    | 4243/7211 [17:05<09:49,  5.03it/s]

Gaps (ex-reports):  59%|█████▉    | 4244/7211 [17:05<09:44,  5.07it/s]

Gaps (ex-reports):  59%|█████▉    | 4245/7211 [17:05<09:47,  5.05it/s]

Gaps (ex-reports):  59%|█████▉    | 4246/7211 [17:06<09:46,  5.05it/s]

Gaps (ex-reports):  59%|█████▉    | 4247/7211 [17:06<09:54,  4.98it/s]

Gaps (ex-reports):  59%|█████▉    | 4248/7211 [17:06<10:09,  4.86it/s]

Gaps (ex-reports):  59%|█████▉    | 4249/7211 [17:06<10:09,  4.86it/s]

Gaps (ex-reports):  59%|█████▉    | 4250/7211 [17:06<10:09,  4.86it/s]

Gaps (ex-reports):  59%|█████▉    | 4251/7211 [17:07<10:02,  4.91it/s]

Gaps (ex-reports):  59%|█████▉    | 4252/7211 [17:07<09:51,  5.00it/s]

Gaps (ex-reports):  59%|█████▉    | 4253/7211 [17:07<09:51,  5.00it/s]

Gaps (ex-reports):  59%|█████▉    | 4254/7211 [17:07<09:52,  4.99it/s]

Gaps (ex-reports):  59%|█████▉    | 4255/7211 [17:07<09:50,  5.00it/s]

Gaps (ex-reports):  59%|█████▉    | 4256/7211 [17:08<09:51,  4.99it/s]

Gaps (ex-reports):  59%|█████▉    | 4257/7211 [17:08<09:41,  5.08it/s]

Gaps (ex-reports):  59%|█████▉    | 4258/7211 [17:08<09:40,  5.09it/s]

Gaps (ex-reports):  59%|█████▉    | 4259/7211 [17:08<09:55,  4.96it/s]

Gaps (ex-reports):  59%|█████▉    | 4260/7211 [17:08<09:55,  4.96it/s]

Gaps (ex-reports):  59%|█████▉    | 4261/7211 [17:09<09:49,  5.01it/s]

Gaps (ex-reports):  59%|█████▉    | 4262/7211 [17:09<09:39,  5.08it/s]

Gaps (ex-reports):  59%|█████▉    | 4263/7211 [17:09<09:35,  5.12it/s]

Gaps (ex-reports):  59%|█████▉    | 4264/7211 [17:09<09:32,  5.15it/s]

Gaps (ex-reports):  59%|█████▉    | 4265/7211 [17:09<09:44,  5.04it/s]

Gaps (ex-reports):  59%|█████▉    | 4266/7211 [17:10<09:46,  5.02it/s]

Gaps (ex-reports):  59%|█████▉    | 4267/7211 [17:10<10:00,  4.91it/s]

Gaps (ex-reports):  59%|█████▉    | 4268/7211 [17:10<09:50,  4.99it/s]

Gaps (ex-reports):  59%|█████▉    | 4269/7211 [17:10<09:42,  5.05it/s]

Gaps (ex-reports):  59%|█████▉    | 4270/7211 [17:10<09:35,  5.11it/s]

Gaps (ex-reports):  59%|█████▉    | 4271/7211 [17:11<09:33,  5.12it/s]

Gaps (ex-reports):  59%|█████▉    | 4272/7211 [17:11<09:44,  5.03it/s]

Gaps (ex-reports):  59%|█████▉    | 4273/7211 [17:11<09:44,  5.02it/s]

Gaps (ex-reports):  59%|█████▉    | 4274/7211 [17:11<09:53,  4.95it/s]

Gaps (ex-reports):  59%|█████▉    | 4275/7211 [17:11<09:49,  4.98it/s]

Gaps (ex-reports):  59%|█████▉    | 4276/7211 [17:12<09:51,  4.96it/s]

Gaps (ex-reports):  59%|█████▉    | 4277/7211 [17:12<10:04,  4.85it/s]

Gaps (ex-reports):  59%|█████▉    | 4278/7211 [17:12<10:03,  4.86it/s]

Gaps (ex-reports):  59%|█████▉    | 4279/7211 [17:12<09:50,  4.96it/s]

Gaps (ex-reports):  59%|█████▉    | 4280/7211 [17:12<09:41,  5.04it/s]

Gaps (ex-reports):  59%|█████▉    | 4281/7211 [17:13<09:44,  5.01it/s]

Gaps (ex-reports):  59%|█████▉    | 4282/7211 [17:13<09:39,  5.06it/s]

Gaps (ex-reports):  59%|█████▉    | 4283/7211 [17:13<09:40,  5.04it/s]

Gaps (ex-reports):  59%|█████▉    | 4284/7211 [17:13<09:51,  4.95it/s]

Gaps (ex-reports):  59%|█████▉    | 4285/7211 [17:13<09:58,  4.89it/s]

Gaps (ex-reports):  59%|█████▉    | 4286/7211 [17:14<09:51,  4.94it/s]

Gaps (ex-reports):  59%|█████▉    | 4287/7211 [17:14<09:41,  5.03it/s]

Gaps (ex-reports):  59%|█████▉    | 4288/7211 [17:14<09:33,  5.10it/s]

Gaps (ex-reports):  59%|█████▉    | 4289/7211 [17:14<09:38,  5.05it/s]

Gaps (ex-reports):  59%|█████▉    | 4290/7211 [17:14<09:48,  4.97it/s]

Gaps (ex-reports):  60%|█████▉    | 4291/7211 [17:15<09:49,  4.95it/s]

Gaps (ex-reports):  60%|█████▉    | 4292/7211 [17:15<09:38,  5.05it/s]

Gaps (ex-reports):  60%|█████▉    | 4293/7211 [17:15<09:33,  5.08it/s]

Gaps (ex-reports):  60%|█████▉    | 4294/7211 [17:15<09:31,  5.10it/s]

Gaps (ex-reports):  60%|█████▉    | 4295/7211 [17:15<09:46,  4.97it/s]

Gaps (ex-reports):  60%|█████▉    | 4296/7211 [17:16<09:45,  4.98it/s]

Gaps (ex-reports):  60%|█████▉    | 4297/7211 [17:16<09:37,  5.04it/s]

Gaps (ex-reports):  60%|█████▉    | 4298/7211 [17:16<10:00,  4.85it/s]

Gaps (ex-reports):  60%|█████▉    | 4299/7211 [17:16<10:01,  4.84it/s]

Gaps (ex-reports):  60%|█████▉    | 4300/7211 [17:16<11:30,  4.21it/s]

Gaps (ex-reports):  60%|█████▉    | 4301/7211 [17:17<11:06,  4.37it/s]

Gaps (ex-reports):  60%|█████▉    | 4302/7211 [17:17<10:47,  4.49it/s]

Gaps (ex-reports):  60%|█████▉    | 4303/7211 [17:17<10:36,  4.57it/s]

Gaps (ex-reports):  60%|█████▉    | 4304/7211 [17:17<10:29,  4.62it/s]

Gaps (ex-reports):  60%|█████▉    | 4305/7211 [17:18<10:16,  4.72it/s]

Gaps (ex-reports):  60%|█████▉    | 4306/7211 [17:18<10:06,  4.79it/s]

Gaps (ex-reports):  60%|█████▉    | 4307/7211 [17:18<10:15,  4.72it/s]

Gaps (ex-reports):  60%|█████▉    | 4308/7211 [17:18<10:05,  4.79it/s]

Gaps (ex-reports):  60%|█████▉    | 4309/7211 [17:18<10:03,  4.81it/s]

Gaps (ex-reports):  60%|█████▉    | 4310/7211 [17:19<10:07,  4.77it/s]

Gaps (ex-reports):  60%|█████▉    | 4311/7211 [17:19<10:14,  4.72it/s]

Gaps (ex-reports):  60%|█████▉    | 4312/7211 [17:19<09:56,  4.86it/s]

Gaps (ex-reports):  60%|█████▉    | 4313/7211 [17:19<09:46,  4.94it/s]

Gaps (ex-reports):  60%|█████▉    | 4314/7211 [17:19<09:45,  4.95it/s]

Gaps (ex-reports):  60%|█████▉    | 4315/7211 [17:20<09:50,  4.91it/s]

Gaps (ex-reports):  60%|█████▉    | 4316/7211 [17:20<09:50,  4.90it/s]

Gaps (ex-reports):  60%|█████▉    | 4317/7211 [17:20<09:35,  5.03it/s]

Gaps (ex-reports):  60%|█████▉    | 4318/7211 [17:20<09:30,  5.07it/s]

Gaps (ex-reports):  60%|█████▉    | 4319/7211 [17:20<09:46,  4.93it/s]

Gaps (ex-reports):  60%|█████▉    | 4320/7211 [17:21<09:56,  4.84it/s]

Gaps (ex-reports):  60%|█████▉    | 4321/7211 [17:21<16:07,  2.99it/s]

Gaps (ex-reports):  60%|█████▉    | 4322/7211 [17:21<14:20,  3.36it/s]

Gaps (ex-reports):  60%|█████▉    | 4323/7211 [17:22<12:49,  3.75it/s]

Gaps (ex-reports):  60%|█████▉    | 4324/7211 [17:22<11:53,  4.04it/s]

Gaps (ex-reports):  60%|█████▉    | 4325/7211 [17:22<11:08,  4.31it/s]

Gaps (ex-reports):  60%|█████▉    | 4326/7211 [17:22<10:46,  4.46it/s]

Gaps (ex-reports):  60%|██████    | 4327/7211 [17:22<10:25,  4.61it/s]

Gaps (ex-reports):  60%|██████    | 4328/7211 [17:23<10:13,  4.70it/s]

Gaps (ex-reports):  60%|██████    | 4329/7211 [17:23<10:00,  4.80it/s]

Gaps (ex-reports):  60%|██████    | 4330/7211 [17:23<10:09,  4.73it/s]

Gaps (ex-reports):  60%|██████    | 4331/7211 [17:23<09:49,  4.89it/s]

Gaps (ex-reports):  60%|██████    | 4332/7211 [17:23<09:46,  4.91it/s]

Gaps (ex-reports):  60%|██████    | 4333/7211 [17:24<09:48,  4.89it/s]

Gaps (ex-reports):  60%|██████    | 4334/7211 [17:24<09:46,  4.91it/s]

Gaps (ex-reports):  60%|██████    | 4335/7211 [17:24<09:51,  4.86it/s]

Gaps (ex-reports):  60%|██████    | 4336/7211 [17:24<09:39,  4.96it/s]

Gaps (ex-reports):  60%|██████    | 4337/7211 [17:24<09:36,  4.98it/s]

Gaps (ex-reports):  60%|██████    | 4338/7211 [17:25<09:35,  4.99it/s]

Gaps (ex-reports):  60%|██████    | 4339/7211 [17:25<09:47,  4.89it/s]

Gaps (ex-reports):  60%|██████    | 4340/7211 [17:25<09:30,  5.04it/s]

Gaps (ex-reports):  60%|██████    | 4341/7211 [17:25<09:36,  4.98it/s]

Gaps (ex-reports):  60%|██████    | 4342/7211 [17:25<09:59,  4.79it/s]

Gaps (ex-reports):  60%|██████    | 4343/7211 [17:26<09:44,  4.91it/s]

Gaps (ex-reports):  60%|██████    | 4344/7211 [17:26<09:44,  4.91it/s]

Gaps (ex-reports):  60%|██████    | 4345/7211 [17:26<09:56,  4.81it/s]

Gaps (ex-reports):  60%|██████    | 4346/7211 [17:26<09:50,  4.85it/s]

Gaps (ex-reports):  60%|██████    | 4347/7211 [17:27<09:53,  4.82it/s]

Gaps (ex-reports):  60%|██████    | 4348/7211 [17:27<09:56,  4.80it/s]

Gaps (ex-reports):  60%|██████    | 4349/7211 [17:27<10:02,  4.75it/s]

Gaps (ex-reports):  60%|██████    | 4350/7211 [17:27<09:56,  4.80it/s]

Gaps (ex-reports):  60%|██████    | 4351/7211 [17:27<09:52,  4.83it/s]

Gaps (ex-reports):  60%|██████    | 4352/7211 [17:28<09:57,  4.78it/s]

Gaps (ex-reports):  60%|██████    | 4353/7211 [17:28<09:55,  4.80it/s]

Gaps (ex-reports):  60%|██████    | 4354/7211 [17:28<09:53,  4.81it/s]

Gaps (ex-reports):  60%|██████    | 4355/7211 [17:28<09:47,  4.86it/s]

Gaps (ex-reports):  60%|██████    | 4356/7211 [17:28<09:52,  4.82it/s]

Gaps (ex-reports):  60%|██████    | 4357/7211 [17:29<09:56,  4.79it/s]

Gaps (ex-reports):  60%|██████    | 4358/7211 [17:29<15:06,  3.15it/s]

Gaps (ex-reports):  60%|██████    | 4359/7211 [17:29<13:20,  3.56it/s]

Gaps (ex-reports):  60%|██████    | 4360/7211 [17:30<12:20,  3.85it/s]

Gaps (ex-reports):  60%|██████    | 4361/7211 [17:30<11:28,  4.14it/s]

Gaps (ex-reports):  60%|██████    | 4362/7211 [17:30<10:46,  4.40it/s]

Gaps (ex-reports):  61%|██████    | 4363/7211 [17:30<10:22,  4.57it/s]

Gaps (ex-reports):  61%|██████    | 4364/7211 [17:30<10:07,  4.68it/s]

Gaps (ex-reports):  61%|██████    | 4365/7211 [17:31<09:53,  4.80it/s]

Gaps (ex-reports):  61%|██████    | 4366/7211 [17:31<09:48,  4.83it/s]

Gaps (ex-reports):  61%|██████    | 4367/7211 [17:31<09:33,  4.96it/s]

Gaps (ex-reports):  61%|██████    | 4368/7211 [17:31<09:22,  5.06it/s]

Gaps (ex-reports):  61%|██████    | 4369/7211 [17:31<09:28,  5.00it/s]

Gaps (ex-reports):  61%|██████    | 4370/7211 [17:32<09:37,  4.92it/s]

Gaps (ex-reports):  61%|██████    | 4371/7211 [17:32<09:35,  4.94it/s]

Gaps (ex-reports):  61%|██████    | 4372/7211 [17:32<09:21,  5.05it/s]

Gaps (ex-reports):  61%|██████    | 4373/7211 [17:32<09:27,  5.00it/s]

Gaps (ex-reports):  61%|██████    | 4374/7211 [17:32<09:32,  4.95it/s]

Gaps (ex-reports):  61%|██████    | 4375/7211 [17:33<09:37,  4.91it/s]

Gaps (ex-reports):  61%|██████    | 4376/7211 [17:33<09:31,  4.96it/s]

Gaps (ex-reports):  61%|██████    | 4377/7211 [17:33<09:40,  4.88it/s]

Gaps (ex-reports):  61%|██████    | 4378/7211 [17:33<09:27,  5.00it/s]

Gaps (ex-reports):  61%|██████    | 4379/7211 [17:34<18:29,  2.55it/s]

Gaps (ex-reports):  61%|██████    | 4380/7211 [17:34<15:44,  3.00it/s]

Gaps (ex-reports):  61%|██████    | 4381/7211 [17:34<13:45,  3.43it/s]

Gaps (ex-reports):  61%|██████    | 4382/7211 [17:35<12:34,  3.75it/s]

Gaps (ex-reports):  61%|██████    | 4383/7211 [17:35<11:49,  3.99it/s]

Gaps (ex-reports):  61%|██████    | 4384/7211 [17:35<11:09,  4.22it/s]

Gaps (ex-reports):  61%|██████    | 4385/7211 [17:35<10:26,  4.51it/s]

Gaps (ex-reports):  61%|██████    | 4386/7211 [17:35<10:15,  4.59it/s]

Gaps (ex-reports):  61%|██████    | 4387/7211 [17:36<09:50,  4.78it/s]

Gaps (ex-reports):  61%|██████    | 4388/7211 [17:36<09:51,  4.77it/s]

Gaps (ex-reports):  61%|██████    | 4389/7211 [17:36<10:09,  4.63it/s]

Gaps (ex-reports):  61%|██████    | 4390/7211 [17:36<10:13,  4.60it/s]

Gaps (ex-reports):  61%|██████    | 4391/7211 [17:36<10:01,  4.69it/s]

Gaps (ex-reports):  61%|██████    | 4392/7211 [17:37<09:46,  4.80it/s]

Gaps (ex-reports):  61%|██████    | 4393/7211 [17:37<09:42,  4.84it/s]

Gaps (ex-reports):  61%|██████    | 4394/7211 [17:37<11:25,  4.11it/s]

Gaps (ex-reports):  61%|██████    | 4395/7211 [17:37<10:50,  4.33it/s]

Gaps (ex-reports):  61%|██████    | 4396/7211 [17:38<10:31,  4.46it/s]

Gaps (ex-reports):  61%|██████    | 4397/7211 [17:38<10:18,  4.55it/s]

Gaps (ex-reports):  61%|██████    | 4398/7211 [17:38<10:26,  4.49it/s]

Gaps (ex-reports):  61%|██████    | 4399/7211 [17:38<10:06,  4.64it/s]

Gaps (ex-reports):  61%|██████    | 4400/7211 [17:38<09:46,  4.79it/s]

Gaps (ex-reports):  61%|██████    | 4401/7211 [17:39<09:29,  4.94it/s]

Gaps (ex-reports):  61%|██████    | 4402/7211 [17:39<09:31,  4.92it/s]

Gaps (ex-reports):  61%|██████    | 4403/7211 [17:39<09:29,  4.93it/s]

Gaps (ex-reports):  61%|██████    | 4404/7211 [17:39<09:35,  4.88it/s]

Gaps (ex-reports):  61%|██████    | 4405/7211 [17:39<09:32,  4.90it/s]

Gaps (ex-reports):  61%|██████    | 4406/7211 [17:40<13:04,  3.57it/s]

Gaps (ex-reports):  61%|██████    | 4407/7211 [17:40<11:58,  3.90it/s]

Gaps (ex-reports):  61%|██████    | 4408/7211 [17:40<11:02,  4.23it/s]

Gaps (ex-reports):  61%|██████    | 4409/7211 [17:41<10:30,  4.45it/s]

Gaps (ex-reports):  61%|██████    | 4410/7211 [17:41<10:10,  4.59it/s]

Gaps (ex-reports):  61%|██████    | 4411/7211 [17:41<09:46,  4.77it/s]

Gaps (ex-reports):  61%|██████    | 4412/7211 [17:41<09:38,  4.83it/s]

Gaps (ex-reports):  61%|██████    | 4413/7211 [17:41<09:27,  4.93it/s]

Gaps (ex-reports):  61%|██████    | 4414/7211 [17:41<09:31,  4.89it/s]

Gaps (ex-reports):  61%|██████    | 4415/7211 [17:42<09:29,  4.91it/s]

Gaps (ex-reports):  61%|██████    | 4416/7211 [17:42<09:34,  4.87it/s]

Gaps (ex-reports):  61%|██████▏   | 4417/7211 [17:42<09:17,  5.01it/s]

Gaps (ex-reports):  61%|██████▏   | 4418/7211 [17:42<09:26,  4.93it/s]

Gaps (ex-reports):  61%|██████▏   | 4419/7211 [17:43<09:21,  4.97it/s]

Gaps (ex-reports):  61%|██████▏   | 4420/7211 [17:43<09:23,  4.96it/s]

Gaps (ex-reports):  61%|██████▏   | 4421/7211 [17:43<09:17,  5.00it/s]

Gaps (ex-reports):  61%|██████▏   | 4422/7211 [17:43<09:08,  5.08it/s]

Gaps (ex-reports):  61%|██████▏   | 4423/7211 [17:43<09:04,  5.12it/s]

Gaps (ex-reports):  61%|██████▏   | 4424/7211 [17:43<09:07,  5.09it/s]

Gaps (ex-reports):  61%|██████▏   | 4425/7211 [17:44<09:15,  5.02it/s]

Gaps (ex-reports):  61%|██████▏   | 4426/7211 [17:44<09:11,  5.05it/s]

Gaps (ex-reports):  61%|██████▏   | 4427/7211 [17:44<09:04,  5.11it/s]

Gaps (ex-reports):  61%|██████▏   | 4428/7211 [17:44<09:12,  5.04it/s]

Gaps (ex-reports):  61%|██████▏   | 4429/7211 [17:44<09:12,  5.04it/s]

Gaps (ex-reports):  61%|██████▏   | 4430/7211 [17:45<09:17,  4.99it/s]

Gaps (ex-reports):  61%|██████▏   | 4431/7211 [17:45<09:22,  4.94it/s]

Gaps (ex-reports):  61%|██████▏   | 4432/7211 [17:45<09:27,  4.90it/s]

Gaps (ex-reports):  61%|██████▏   | 4433/7211 [17:45<09:23,  4.93it/s]

Gaps (ex-reports):  61%|██████▏   | 4434/7211 [17:45<09:17,  4.98it/s]

Gaps (ex-reports):  62%|██████▏   | 4435/7211 [17:46<09:15,  5.00it/s]

Gaps (ex-reports):  62%|██████▏   | 4436/7211 [17:46<09:22,  4.94it/s]

Gaps (ex-reports):  62%|██████▏   | 4437/7211 [17:46<09:11,  5.03it/s]

Gaps (ex-reports):  62%|██████▏   | 4438/7211 [17:46<09:18,  4.97it/s]

Gaps (ex-reports):  62%|██████▏   | 4439/7211 [17:47<09:24,  4.91it/s]

Gaps (ex-reports):  62%|██████▏   | 4440/7211 [17:47<09:21,  4.93it/s]

Gaps (ex-reports):  62%|██████▏   | 4441/7211 [17:47<09:21,  4.94it/s]

Gaps (ex-reports):  62%|██████▏   | 4442/7211 [17:47<09:16,  4.98it/s]

Gaps (ex-reports):  62%|██████▏   | 4443/7211 [17:47<09:13,  5.00it/s]

Gaps (ex-reports):  62%|██████▏   | 4444/7211 [17:47<09:06,  5.06it/s]

Gaps (ex-reports):  62%|██████▏   | 4445/7211 [17:48<09:01,  5.11it/s]

Gaps (ex-reports):  62%|██████▏   | 4446/7211 [17:48<09:43,  4.74it/s]

Gaps (ex-reports):  62%|██████▏   | 4447/7211 [17:48<09:43,  4.74it/s]

Gaps (ex-reports):  62%|██████▏   | 4448/7211 [17:48<09:45,  4.72it/s]

Gaps (ex-reports):  62%|██████▏   | 4449/7211 [17:49<09:29,  4.85it/s]

Gaps (ex-reports):  62%|██████▏   | 4450/7211 [17:49<09:17,  4.95it/s]

Gaps (ex-reports):  62%|██████▏   | 4451/7211 [17:49<09:08,  5.03it/s]

Gaps (ex-reports):  62%|██████▏   | 4452/7211 [17:49<09:04,  5.07it/s]

Gaps (ex-reports):  62%|██████▏   | 4453/7211 [17:49<08:56,  5.14it/s]

Gaps (ex-reports):  62%|██████▏   | 4454/7211 [17:50<08:57,  5.13it/s]

Gaps (ex-reports):  62%|██████▏   | 4455/7211 [17:50<09:05,  5.05it/s]

Gaps (ex-reports):  62%|██████▏   | 4456/7211 [17:50<09:15,  4.96it/s]

Gaps (ex-reports):  62%|██████▏   | 4457/7211 [17:50<09:16,  4.95it/s]

Gaps (ex-reports):  62%|██████▏   | 4458/7211 [17:50<09:09,  5.01it/s]

Gaps (ex-reports):  62%|██████▏   | 4459/7211 [17:51<09:11,  4.99it/s]

Gaps (ex-reports):  62%|██████▏   | 4460/7211 [17:51<09:21,  4.90it/s]

Gaps (ex-reports):  62%|██████▏   | 4461/7211 [17:51<09:13,  4.97it/s]

Gaps (ex-reports):  62%|██████▏   | 4462/7211 [17:51<09:06,  5.03it/s]

Gaps (ex-reports):  62%|██████▏   | 4463/7211 [17:51<09:09,  5.00it/s]

Gaps (ex-reports):  62%|██████▏   | 4464/7211 [17:52<09:16,  4.93it/s]

Gaps (ex-reports):  62%|██████▏   | 4465/7211 [17:52<09:15,  4.94it/s]

Gaps (ex-reports):  62%|██████▏   | 4466/7211 [17:52<09:13,  4.96it/s]

Gaps (ex-reports):  62%|██████▏   | 4467/7211 [17:52<09:02,  5.06it/s]

Gaps (ex-reports):  62%|██████▏   | 4468/7211 [17:52<09:02,  5.06it/s]

Gaps (ex-reports):  62%|██████▏   | 4469/7211 [17:53<08:59,  5.08it/s]

Gaps (ex-reports):  62%|██████▏   | 4470/7211 [17:53<08:59,  5.08it/s]

Gaps (ex-reports):  62%|██████▏   | 4471/7211 [17:53<09:06,  5.01it/s]

Gaps (ex-reports):  62%|██████▏   | 4472/7211 [17:53<09:12,  4.96it/s]

Gaps (ex-reports):  62%|██████▏   | 4473/7211 [17:53<09:09,  4.98it/s]

Gaps (ex-reports):  62%|██████▏   | 4474/7211 [17:54<09:09,  4.98it/s]

Gaps (ex-reports):  62%|██████▏   | 4475/7211 [17:54<09:00,  5.06it/s]

Gaps (ex-reports):  62%|██████▏   | 4476/7211 [17:54<09:08,  4.99it/s]

Gaps (ex-reports):  62%|██████▏   | 4477/7211 [17:54<09:06,  5.00it/s]

Gaps (ex-reports):  62%|██████▏   | 4478/7211 [17:54<10:23,  4.39it/s]

Gaps (ex-reports):  62%|██████▏   | 4479/7211 [17:55<10:47,  4.22it/s]

Gaps (ex-reports):  62%|██████▏   | 4480/7211 [17:55<10:51,  4.19it/s]

Gaps (ex-reports):  62%|██████▏   | 4481/7211 [17:55<10:17,  4.42it/s]

Gaps (ex-reports):  62%|██████▏   | 4482/7211 [17:55<10:00,  4.54it/s]

Gaps (ex-reports):  62%|██████▏   | 4483/7211 [17:56<09:54,  4.59it/s]

Gaps (ex-reports):  62%|██████▏   | 4484/7211 [17:56<09:36,  4.73it/s]

Gaps (ex-reports):  62%|██████▏   | 4485/7211 [17:56<09:31,  4.77it/s]

Gaps (ex-reports):  62%|██████▏   | 4486/7211 [17:56<09:33,  4.75it/s]

Gaps (ex-reports):  62%|██████▏   | 4487/7211 [17:56<09:27,  4.80it/s]

Gaps (ex-reports):  62%|██████▏   | 4488/7211 [17:57<09:22,  4.84it/s]

Gaps (ex-reports):  62%|██████▏   | 4489/7211 [17:57<09:11,  4.93it/s]

Gaps (ex-reports):  62%|██████▏   | 4490/7211 [17:57<09:02,  5.01it/s]

Gaps (ex-reports):  62%|██████▏   | 4491/7211 [17:57<08:58,  5.05it/s]

Gaps (ex-reports):  62%|██████▏   | 4492/7211 [17:57<08:52,  5.10it/s]

Gaps (ex-reports):  62%|██████▏   | 4493/7211 [17:58<08:52,  5.10it/s]

Gaps (ex-reports):  62%|██████▏   | 4494/7211 [17:58<09:02,  5.01it/s]

Gaps (ex-reports):  62%|██████▏   | 4495/7211 [17:58<09:05,  4.98it/s]

Gaps (ex-reports):  62%|██████▏   | 4496/7211 [17:58<08:56,  5.06it/s]

Gaps (ex-reports):  62%|██████▏   | 4497/7211 [17:58<08:59,  5.03it/s]

Gaps (ex-reports):  62%|██████▏   | 4498/7211 [17:59<09:02,  5.00it/s]

Gaps (ex-reports):  62%|██████▏   | 4499/7211 [17:59<08:53,  5.08it/s]

Gaps (ex-reports):  62%|██████▏   | 4500/7211 [17:59<08:57,  5.04it/s]

Gaps (ex-reports):  62%|██████▏   | 4501/7211 [17:59<08:54,  5.07it/s]

Gaps (ex-reports):  62%|██████▏   | 4502/7211 [17:59<08:51,  5.10it/s]

Gaps (ex-reports):  62%|██████▏   | 4503/7211 [18:00<08:47,  5.13it/s]

Gaps (ex-reports):  62%|██████▏   | 4504/7211 [18:00<08:44,  5.16it/s]

Gaps (ex-reports):  62%|██████▏   | 4505/7211 [18:00<08:44,  5.16it/s]

Gaps (ex-reports):  62%|██████▏   | 4506/7211 [18:00<08:56,  5.04it/s]

Gaps (ex-reports):  63%|██████▎   | 4507/7211 [18:00<08:57,  5.03it/s]

Gaps (ex-reports):  63%|██████▎   | 4508/7211 [18:00<08:56,  5.04it/s]

Gaps (ex-reports):  63%|██████▎   | 4509/7211 [18:01<08:56,  5.04it/s]

Gaps (ex-reports):  63%|██████▎   | 4510/7211 [18:01<08:58,  5.02it/s]

Gaps (ex-reports):  63%|██████▎   | 4511/7211 [18:01<09:03,  4.97it/s]

Gaps (ex-reports):  63%|██████▎   | 4512/7211 [18:01<09:13,  4.87it/s]

Gaps (ex-reports):  63%|██████▎   | 4513/7211 [18:02<08:59,  5.00it/s]

Gaps (ex-reports):  63%|██████▎   | 4514/7211 [18:02<09:04,  4.95it/s]

Gaps (ex-reports):  63%|██████▎   | 4515/7211 [18:02<09:00,  4.98it/s]

Gaps (ex-reports):  63%|██████▎   | 4516/7211 [18:02<09:02,  4.97it/s]

Gaps (ex-reports):  63%|██████▎   | 4517/7211 [18:02<09:03,  4.95it/s]

Gaps (ex-reports):  63%|██████▎   | 4518/7211 [18:03<09:07,  4.92it/s]

Gaps (ex-reports):  63%|██████▎   | 4519/7211 [18:03<09:08,  4.90it/s]

Gaps (ex-reports):  63%|██████▎   | 4520/7211 [18:03<09:12,  4.87it/s]

Gaps (ex-reports):  63%|██████▎   | 4521/7211 [18:03<09:10,  4.89it/s]

Gaps (ex-reports):  63%|██████▎   | 4522/7211 [18:03<08:59,  4.98it/s]

Gaps (ex-reports):  63%|██████▎   | 4523/7211 [18:04<08:49,  5.08it/s]

Gaps (ex-reports):  63%|██████▎   | 4524/7211 [18:04<08:48,  5.08it/s]

Gaps (ex-reports):  63%|██████▎   | 4525/7211 [18:04<08:48,  5.08it/s]

Gaps (ex-reports):  63%|██████▎   | 4526/7211 [18:04<08:58,  4.98it/s]

Gaps (ex-reports):  63%|██████▎   | 4527/7211 [18:04<09:01,  4.96it/s]

Gaps (ex-reports):  63%|██████▎   | 4528/7211 [18:05<09:07,  4.90it/s]

Gaps (ex-reports):  63%|██████▎   | 4529/7211 [18:05<09:04,  4.92it/s]

Gaps (ex-reports):  63%|██████▎   | 4530/7211 [18:05<09:08,  4.88it/s]

Gaps (ex-reports):  63%|██████▎   | 4531/7211 [18:05<09:04,  4.92it/s]

Gaps (ex-reports):  63%|██████▎   | 4532/7211 [18:05<08:51,  5.04it/s]

Gaps (ex-reports):  63%|██████▎   | 4533/7211 [18:06<09:06,  4.90it/s]

Gaps (ex-reports):  63%|██████▎   | 4534/7211 [18:06<11:03,  4.03it/s]

Gaps (ex-reports):  63%|██████▎   | 4535/7211 [18:06<10:21,  4.31it/s]

Gaps (ex-reports):  63%|██████▎   | 4536/7211 [18:06<11:35,  3.85it/s]

Gaps (ex-reports):  63%|██████▎   | 4537/7211 [18:07<10:41,  4.17it/s]

Gaps (ex-reports):  63%|██████▎   | 4538/7211 [18:07<10:03,  4.43it/s]

Gaps (ex-reports):  63%|██████▎   | 4539/7211 [18:07<09:34,  4.65it/s]

Gaps (ex-reports):  63%|██████▎   | 4540/7211 [18:07<09:17,  4.79it/s]

Gaps (ex-reports):  63%|██████▎   | 4541/7211 [18:07<09:07,  4.88it/s]

Gaps (ex-reports):  63%|██████▎   | 4542/7211 [18:08<09:19,  4.77it/s]

Gaps (ex-reports):  63%|██████▎   | 4543/7211 [18:08<09:01,  4.92it/s]

Gaps (ex-reports):  63%|██████▎   | 4544/7211 [18:08<08:54,  4.99it/s]

Gaps (ex-reports):  63%|██████▎   | 4545/7211 [18:08<08:52,  5.01it/s]

Gaps (ex-reports):  63%|██████▎   | 4546/7211 [18:08<08:55,  4.98it/s]

Gaps (ex-reports):  63%|██████▎   | 4547/7211 [18:09<08:46,  5.06it/s]

Gaps (ex-reports):  63%|██████▎   | 4548/7211 [18:09<08:48,  5.04it/s]

Gaps (ex-reports):  63%|██████▎   | 4549/7211 [18:09<08:49,  5.03it/s]

Gaps (ex-reports):  63%|██████▎   | 4550/7211 [18:09<08:53,  4.99it/s]

Gaps (ex-reports):  63%|██████▎   | 4551/7211 [18:09<08:48,  5.03it/s]

Gaps (ex-reports):  63%|██████▎   | 4552/7211 [18:10<08:42,  5.09it/s]

Gaps (ex-reports):  63%|██████▎   | 4553/7211 [18:10<08:41,  5.10it/s]

Gaps (ex-reports):  63%|██████▎   | 4554/7211 [18:10<08:34,  5.16it/s]

Gaps (ex-reports):  63%|██████▎   | 4555/7211 [18:10<08:34,  5.17it/s]

Gaps (ex-reports):  63%|██████▎   | 4556/7211 [18:10<08:40,  5.10it/s]

Gaps (ex-reports):  63%|██████▎   | 4557/7211 [18:11<08:43,  5.07it/s]

Gaps (ex-reports):  63%|██████▎   | 4558/7211 [18:11<08:42,  5.08it/s]

Gaps (ex-reports):  63%|██████▎   | 4559/7211 [18:11<08:47,  5.03it/s]

Gaps (ex-reports):  63%|██████▎   | 4560/7211 [18:11<08:44,  5.05it/s]

Gaps (ex-reports):  63%|██████▎   | 4561/7211 [18:11<08:57,  4.93it/s]

Gaps (ex-reports):  63%|██████▎   | 4562/7211 [18:12<09:03,  4.87it/s]

Gaps (ex-reports):  63%|██████▎   | 4563/7211 [18:12<08:57,  4.93it/s]

Gaps (ex-reports):  63%|██████▎   | 4564/7211 [18:12<08:58,  4.92it/s]

Gaps (ex-reports):  63%|██████▎   | 4565/7211 [18:12<08:53,  4.96it/s]

Gaps (ex-reports):  63%|██████▎   | 4566/7211 [18:12<09:33,  4.61it/s]

Gaps (ex-reports):  63%|██████▎   | 4567/7211 [18:13<09:12,  4.79it/s]

Gaps (ex-reports):  63%|██████▎   | 4568/7211 [18:13<09:30,  4.64it/s]

Gaps (ex-reports):  63%|██████▎   | 4569/7211 [18:13<09:22,  4.70it/s]

Gaps (ex-reports):  63%|██████▎   | 4570/7211 [18:13<09:14,  4.76it/s]

Gaps (ex-reports):  63%|██████▎   | 4571/7211 [18:13<09:14,  4.76it/s]

Gaps (ex-reports):  63%|██████▎   | 4572/7211 [18:14<09:11,  4.78it/s]

Gaps (ex-reports):  63%|██████▎   | 4573/7211 [18:14<09:09,  4.80it/s]

Gaps (ex-reports):  63%|██████▎   | 4574/7211 [18:14<08:57,  4.91it/s]

Gaps (ex-reports):  63%|██████▎   | 4575/7211 [18:14<08:50,  4.97it/s]

Gaps (ex-reports):  63%|██████▎   | 4576/7211 [18:14<08:39,  5.07it/s]

Gaps (ex-reports):  63%|██████▎   | 4577/7211 [18:15<08:52,  4.95it/s]

Gaps (ex-reports):  63%|██████▎   | 4578/7211 [18:15<08:52,  4.95it/s]

Gaps (ex-reports):  64%|██████▎   | 4579/7211 [18:15<08:47,  4.99it/s]

Gaps (ex-reports):  64%|██████▎   | 4580/7211 [18:15<08:55,  4.91it/s]

Gaps (ex-reports):  64%|██████▎   | 4581/7211 [18:15<08:48,  4.98it/s]

Gaps (ex-reports):  64%|██████▎   | 4582/7211 [18:16<08:54,  4.91it/s]

Gaps (ex-reports):  64%|██████▎   | 4583/7211 [18:16<08:51,  4.95it/s]

Gaps (ex-reports):  64%|██████▎   | 4584/7211 [18:16<08:45,  5.00it/s]

Gaps (ex-reports):  64%|██████▎   | 4585/7211 [18:16<08:54,  4.91it/s]

Gaps (ex-reports):  64%|██████▎   | 4586/7211 [18:16<08:56,  4.90it/s]

Gaps (ex-reports):  64%|██████▎   | 4587/7211 [18:17<08:53,  4.92it/s]

Gaps (ex-reports):  64%|██████▎   | 4588/7211 [18:17<08:47,  4.97it/s]

Gaps (ex-reports):  64%|██████▎   | 4589/7211 [18:17<08:37,  5.07it/s]

Gaps (ex-reports):  64%|██████▎   | 4590/7211 [18:17<08:38,  5.05it/s]

Gaps (ex-reports):  64%|██████▎   | 4591/7211 [18:17<08:36,  5.08it/s]

Gaps (ex-reports):  64%|██████▎   | 4592/7211 [18:18<08:39,  5.04it/s]

Gaps (ex-reports):  64%|██████▎   | 4593/7211 [18:18<08:45,  4.98it/s]

Gaps (ex-reports):  64%|██████▎   | 4594/7211 [18:18<08:36,  5.06it/s]

Gaps (ex-reports):  64%|██████▎   | 4595/7211 [18:18<08:33,  5.09it/s]

Gaps (ex-reports):  64%|██████▎   | 4596/7211 [18:18<08:49,  4.94it/s]

Gaps (ex-reports):  64%|██████▎   | 4597/7211 [18:19<08:44,  4.98it/s]

Gaps (ex-reports):  64%|██████▍   | 4598/7211 [18:19<08:51,  4.92it/s]

Gaps (ex-reports):  64%|██████▍   | 4599/7211 [18:19<08:41,  5.01it/s]

Gaps (ex-reports):  64%|██████▍   | 4600/7211 [18:19<08:54,  4.88it/s]

Gaps (ex-reports):  64%|██████▍   | 4601/7211 [18:19<08:47,  4.95it/s]

Gaps (ex-reports):  64%|██████▍   | 4602/7211 [18:20<08:46,  4.95it/s]

Gaps (ex-reports):  64%|██████▍   | 4603/7211 [18:20<09:09,  4.74it/s]

Gaps (ex-reports):  64%|██████▍   | 4604/7211 [18:20<09:03,  4.80it/s]

Gaps (ex-reports):  64%|██████▍   | 4605/7211 [18:20<09:01,  4.81it/s]

Gaps (ex-reports):  64%|██████▍   | 4606/7211 [18:21<09:04,  4.79it/s]

Gaps (ex-reports):  64%|██████▍   | 4607/7211 [18:21<08:46,  4.95it/s]

Gaps (ex-reports):  64%|██████▍   | 4608/7211 [18:21<08:51,  4.90it/s]

Gaps (ex-reports):  64%|██████▍   | 4609/7211 [18:21<08:56,  4.85it/s]

Gaps (ex-reports):  64%|██████▍   | 4610/7211 [18:21<08:55,  4.85it/s]

Gaps (ex-reports):  64%|██████▍   | 4611/7211 [18:22<08:46,  4.94it/s]

Gaps (ex-reports):  64%|██████▍   | 4612/7211 [18:22<08:41,  4.98it/s]

Gaps (ex-reports):  64%|██████▍   | 4613/7211 [18:22<08:44,  4.95it/s]

Gaps (ex-reports):  64%|██████▍   | 4614/7211 [18:22<08:40,  4.99it/s]

Gaps (ex-reports):  64%|██████▍   | 4615/7211 [18:22<08:37,  5.02it/s]

Gaps (ex-reports):  64%|██████▍   | 4616/7211 [18:23<08:38,  5.01it/s]

Gaps (ex-reports):  64%|██████▍   | 4617/7211 [18:23<08:42,  4.96it/s]

Gaps (ex-reports):  64%|██████▍   | 4618/7211 [18:23<08:43,  4.95it/s]

Gaps (ex-reports):  64%|██████▍   | 4619/7211 [18:23<08:35,  5.03it/s]

Gaps (ex-reports):  64%|██████▍   | 4620/7211 [18:23<08:24,  5.13it/s]

Gaps (ex-reports):  64%|██████▍   | 4621/7211 [18:24<08:28,  5.09it/s]

Gaps (ex-reports):  64%|██████▍   | 4622/7211 [18:24<08:34,  5.03it/s]

Gaps (ex-reports):  64%|██████▍   | 4623/7211 [18:24<08:36,  5.01it/s]

Gaps (ex-reports):  64%|██████▍   | 4624/7211 [18:24<08:35,  5.02it/s]

Gaps (ex-reports):  64%|██████▍   | 4625/7211 [18:24<08:30,  5.07it/s]

Gaps (ex-reports):  64%|██████▍   | 4626/7211 [18:25<08:23,  5.13it/s]

Gaps (ex-reports):  64%|██████▍   | 4627/7211 [18:25<08:22,  5.14it/s]

Gaps (ex-reports):  64%|██████▍   | 4628/7211 [18:25<08:29,  5.07it/s]

Gaps (ex-reports):  64%|██████▍   | 4629/7211 [18:25<08:32,  5.03it/s]

Gaps (ex-reports):  64%|██████▍   | 4630/7211 [18:25<08:23,  5.12it/s]

Gaps (ex-reports):  64%|██████▍   | 4631/7211 [18:25<08:24,  5.11it/s]

Gaps (ex-reports):  64%|██████▍   | 4632/7211 [18:26<08:19,  5.16it/s]

Gaps (ex-reports):  64%|██████▍   | 4633/7211 [18:26<08:22,  5.13it/s]

Gaps (ex-reports):  64%|██████▍   | 4634/7211 [18:26<08:31,  5.04it/s]

Gaps (ex-reports):  64%|██████▍   | 4635/7211 [18:26<08:45,  4.90it/s]

Gaps (ex-reports):  64%|██████▍   | 4636/7211 [18:26<08:34,  5.00it/s]

Gaps (ex-reports):  64%|██████▍   | 4637/7211 [18:27<08:36,  4.98it/s]

Gaps (ex-reports):  64%|██████▍   | 4638/7211 [18:27<08:32,  5.02it/s]

Gaps (ex-reports):  64%|██████▍   | 4639/7211 [18:27<08:26,  5.08it/s]

Gaps (ex-reports):  64%|██████▍   | 4640/7211 [18:27<08:40,  4.94it/s]

Gaps (ex-reports):  64%|██████▍   | 4641/7211 [18:27<08:33,  5.00it/s]

Gaps (ex-reports):  64%|██████▍   | 4642/7211 [18:28<08:39,  4.95it/s]

Gaps (ex-reports):  64%|██████▍   | 4643/7211 [18:28<08:43,  4.90it/s]

Gaps (ex-reports):  64%|██████▍   | 4644/7211 [18:28<08:41,  4.93it/s]

Gaps (ex-reports):  64%|██████▍   | 4645/7211 [18:28<08:33,  5.00it/s]

Gaps (ex-reports):  64%|██████▍   | 4646/7211 [18:29<08:40,  4.93it/s]

Gaps (ex-reports):  64%|██████▍   | 4647/7211 [18:29<08:55,  4.79it/s]

Gaps (ex-reports):  64%|██████▍   | 4648/7211 [18:29<08:54,  4.80it/s]

Gaps (ex-reports):  64%|██████▍   | 4649/7211 [18:29<08:41,  4.91it/s]

Gaps (ex-reports):  64%|██████▍   | 4650/7211 [18:29<08:36,  4.96it/s]

Gaps (ex-reports):  64%|██████▍   | 4651/7211 [18:30<08:37,  4.95it/s]

Gaps (ex-reports):  65%|██████▍   | 4652/7211 [18:30<08:29,  5.02it/s]

Gaps (ex-reports):  65%|██████▍   | 4653/7211 [18:30<08:29,  5.03it/s]

Gaps (ex-reports):  65%|██████▍   | 4654/7211 [18:30<08:39,  4.93it/s]

Gaps (ex-reports):  65%|██████▍   | 4655/7211 [18:30<08:37,  4.94it/s]

Gaps (ex-reports):  65%|██████▍   | 4656/7211 [18:31<08:39,  4.92it/s]

Gaps (ex-reports):  65%|██████▍   | 4657/7211 [18:31<08:48,  4.84it/s]

Gaps (ex-reports):  65%|██████▍   | 4658/7211 [18:31<08:49,  4.82it/s]

Gaps (ex-reports):  65%|██████▍   | 4659/7211 [18:31<08:46,  4.85it/s]

Gaps (ex-reports):  65%|██████▍   | 4660/7211 [18:31<08:49,  4.82it/s]

Gaps (ex-reports):  65%|██████▍   | 4661/7211 [18:32<08:48,  4.82it/s]

Gaps (ex-reports):  65%|██████▍   | 4662/7211 [18:32<08:45,  4.85it/s]

Gaps (ex-reports):  65%|██████▍   | 4663/7211 [18:32<08:40,  4.89it/s]

Gaps (ex-reports):  65%|██████▍   | 4664/7211 [18:32<08:46,  4.84it/s]

Gaps (ex-reports):  65%|██████▍   | 4665/7211 [18:32<08:41,  4.88it/s]

Gaps (ex-reports):  65%|██████▍   | 4666/7211 [18:33<08:40,  4.89it/s]

Gaps (ex-reports):  65%|██████▍   | 4667/7211 [18:33<08:30,  4.98it/s]

Gaps (ex-reports):  65%|██████▍   | 4668/7211 [18:33<08:35,  4.93it/s]

Gaps (ex-reports):  65%|██████▍   | 4669/7211 [18:33<08:32,  4.96it/s]

Gaps (ex-reports):  65%|██████▍   | 4670/7211 [18:33<08:32,  4.96it/s]

Gaps (ex-reports):  65%|██████▍   | 4671/7211 [18:34<08:28,  5.00it/s]

Gaps (ex-reports):  65%|██████▍   | 4672/7211 [18:34<08:42,  4.86it/s]

Gaps (ex-reports):  65%|██████▍   | 4673/7211 [18:34<08:40,  4.88it/s]

Gaps (ex-reports):  65%|██████▍   | 4674/7211 [18:34<08:38,  4.89it/s]

Gaps (ex-reports):  65%|██████▍   | 4675/7211 [18:34<08:43,  4.84it/s]

Gaps (ex-reports):  65%|██████▍   | 4676/7211 [18:35<08:50,  4.78it/s]

Gaps (ex-reports):  65%|██████▍   | 4677/7211 [18:35<08:56,  4.73it/s]

Gaps (ex-reports):  65%|██████▍   | 4678/7211 [18:35<08:57,  4.71it/s]

Gaps (ex-reports):  65%|██████▍   | 4679/7211 [18:35<08:45,  4.82it/s]

Gaps (ex-reports):  65%|██████▍   | 4680/7211 [18:35<08:39,  4.88it/s]

Gaps (ex-reports):  65%|██████▍   | 4681/7211 [18:36<08:35,  4.91it/s]

Gaps (ex-reports):  65%|██████▍   | 4682/7211 [18:36<08:26,  4.99it/s]

Gaps (ex-reports):  65%|██████▍   | 4683/7211 [18:36<08:18,  5.07it/s]

Gaps (ex-reports):  65%|██████▍   | 4684/7211 [18:36<09:13,  4.56it/s]

Gaps (ex-reports):  65%|██████▍   | 4685/7211 [18:37<08:57,  4.70it/s]

Gaps (ex-reports):  65%|██████▍   | 4686/7211 [18:37<08:51,  4.75it/s]

Gaps (ex-reports):  65%|██████▍   | 4687/7211 [18:37<08:41,  4.84it/s]

Gaps (ex-reports):  65%|██████▌   | 4688/7211 [18:37<08:34,  4.91it/s]

Gaps (ex-reports):  65%|██████▌   | 4689/7211 [18:37<08:25,  4.99it/s]

Gaps (ex-reports):  65%|██████▌   | 4690/7211 [18:38<08:27,  4.97it/s]

Gaps (ex-reports):  65%|██████▌   | 4691/7211 [18:38<08:27,  4.97it/s]

Gaps (ex-reports):  65%|██████▌   | 4692/7211 [18:38<08:25,  4.99it/s]

Gaps (ex-reports):  65%|██████▌   | 4693/7211 [18:38<08:33,  4.91it/s]

Gaps (ex-reports):  65%|██████▌   | 4694/7211 [18:38<09:40,  4.34it/s]

Gaps (ex-reports):  65%|██████▌   | 4695/7211 [18:39<09:14,  4.54it/s]

Gaps (ex-reports):  65%|██████▌   | 4696/7211 [18:39<09:07,  4.59it/s]

Gaps (ex-reports):  65%|██████▌   | 4697/7211 [18:39<08:54,  4.70it/s]

Gaps (ex-reports):  65%|██████▌   | 4698/7211 [18:39<08:40,  4.82it/s]

Gaps (ex-reports):  65%|██████▌   | 4699/7211 [18:39<08:43,  4.80it/s]

Gaps (ex-reports):  65%|██████▌   | 4700/7211 [18:40<08:41,  4.82it/s]

Gaps (ex-reports):  65%|██████▌   | 4701/7211 [18:40<08:42,  4.81it/s]

Gaps (ex-reports):  65%|██████▌   | 4702/7211 [18:40<08:37,  4.85it/s]

Gaps (ex-reports):  65%|██████▌   | 4703/7211 [18:40<08:27,  4.94it/s]

Gaps (ex-reports):  65%|██████▌   | 4704/7211 [18:41<13:19,  3.14it/s]

Gaps (ex-reports):  65%|██████▌   | 4705/7211 [18:41<11:46,  3.54it/s]

Gaps (ex-reports):  65%|██████▌   | 4706/7211 [18:41<10:50,  3.85it/s]

Gaps (ex-reports):  65%|██████▌   | 4707/7211 [18:41<09:57,  4.19it/s]

Gaps (ex-reports):  65%|██████▌   | 4708/7211 [18:42<09:32,  4.37it/s]

Gaps (ex-reports):  65%|██████▌   | 4709/7211 [18:42<09:08,  4.56it/s]

Gaps (ex-reports):  65%|██████▌   | 4710/7211 [18:42<09:01,  4.62it/s]

Gaps (ex-reports):  65%|██████▌   | 4711/7211 [18:42<08:47,  4.74it/s]

Gaps (ex-reports):  65%|██████▌   | 4712/7211 [18:42<08:50,  4.71it/s]

Gaps (ex-reports):  65%|██████▌   | 4713/7211 [18:43<08:41,  4.79it/s]

Gaps (ex-reports):  65%|██████▌   | 4714/7211 [18:43<08:42,  4.78it/s]

Gaps (ex-reports):  65%|██████▌   | 4715/7211 [18:43<08:28,  4.91it/s]

Gaps (ex-reports):  65%|██████▌   | 4716/7211 [18:43<08:23,  4.96it/s]

Gaps (ex-reports):  65%|██████▌   | 4717/7211 [18:43<08:23,  4.96it/s]

Gaps (ex-reports):  65%|██████▌   | 4718/7211 [18:44<08:26,  4.93it/s]

Gaps (ex-reports):  65%|██████▌   | 4719/7211 [18:44<08:27,  4.91it/s]

Gaps (ex-reports):  65%|██████▌   | 4720/7211 [18:44<09:46,  4.25it/s]

Gaps (ex-reports):  65%|██████▌   | 4721/7211 [18:44<09:08,  4.54it/s]

Gaps (ex-reports):  65%|██████▌   | 4722/7211 [18:45<08:52,  4.68it/s]

Gaps (ex-reports):  65%|██████▌   | 4723/7211 [18:45<09:06,  4.55it/s]

Gaps (ex-reports):  66%|██████▌   | 4724/7211 [18:45<08:52,  4.67it/s]

Gaps (ex-reports):  66%|██████▌   | 4725/7211 [18:45<08:58,  4.62it/s]

Gaps (ex-reports):  66%|██████▌   | 4726/7211 [18:45<08:45,  4.73it/s]

Gaps (ex-reports):  66%|██████▌   | 4727/7211 [18:46<08:34,  4.82it/s]

Gaps (ex-reports):  66%|██████▌   | 4728/7211 [18:46<08:34,  4.82it/s]

Gaps (ex-reports):  66%|██████▌   | 4729/7211 [18:46<08:32,  4.84it/s]

Gaps (ex-reports):  66%|██████▌   | 4730/7211 [18:46<08:31,  4.85it/s]

Gaps (ex-reports):  66%|██████▌   | 4731/7211 [18:46<08:35,  4.81it/s]

Gaps (ex-reports):  66%|██████▌   | 4732/7211 [18:47<08:26,  4.89it/s]

Gaps (ex-reports):  66%|██████▌   | 4733/7211 [18:47<08:19,  4.96it/s]

Gaps (ex-reports):  66%|██████▌   | 4734/7211 [18:47<08:27,  4.88it/s]

Gaps (ex-reports):  66%|██████▌   | 4735/7211 [18:47<08:31,  4.84it/s]

Gaps (ex-reports):  66%|██████▌   | 4736/7211 [18:47<08:26,  4.88it/s]

Gaps (ex-reports):  66%|██████▌   | 4737/7211 [18:48<08:23,  4.91it/s]

Gaps (ex-reports):  66%|██████▌   | 4738/7211 [18:48<08:21,  4.93it/s]

Gaps (ex-reports):  66%|██████▌   | 4739/7211 [18:48<08:11,  5.03it/s]

Gaps (ex-reports):  66%|██████▌   | 4740/7211 [18:48<08:15,  4.99it/s]

Gaps (ex-reports):  66%|██████▌   | 4741/7211 [18:48<08:10,  5.03it/s]

Gaps (ex-reports):  66%|██████▌   | 4742/7211 [18:49<08:13,  5.00it/s]

Gaps (ex-reports):  66%|██████▌   | 4743/7211 [18:49<08:11,  5.03it/s]

Gaps (ex-reports):  66%|██████▌   | 4744/7211 [18:49<08:07,  5.06it/s]

Gaps (ex-reports):  66%|██████▌   | 4745/7211 [18:49<08:08,  5.05it/s]

Gaps (ex-reports):  66%|██████▌   | 4746/7211 [18:49<08:09,  5.03it/s]

Gaps (ex-reports):  66%|██████▌   | 4747/7211 [18:50<08:09,  5.03it/s]

Gaps (ex-reports):  66%|██████▌   | 4748/7211 [18:50<08:30,  4.83it/s]

Gaps (ex-reports):  66%|██████▌   | 4749/7211 [18:50<08:28,  4.84it/s]

Gaps (ex-reports):  66%|██████▌   | 4750/7211 [18:51<17:10,  2.39it/s]

Gaps (ex-reports):  66%|██████▌   | 4751/7211 [18:51<14:28,  2.83it/s]

Gaps (ex-reports):  66%|██████▌   | 4752/7211 [18:51<12:39,  3.24it/s]

Gaps (ex-reports):  66%|██████▌   | 4753/7211 [18:52<11:24,  3.59it/s]

Gaps (ex-reports):  66%|██████▌   | 4754/7211 [18:52<10:20,  3.96it/s]

Gaps (ex-reports):  66%|██████▌   | 4755/7211 [18:52<09:33,  4.28it/s]

Gaps (ex-reports):  66%|██████▌   | 4756/7211 [18:52<09:06,  4.49it/s]

Gaps (ex-reports):  66%|██████▌   | 4757/7211 [18:52<09:50,  4.16it/s]

Gaps (ex-reports):  66%|██████▌   | 4758/7211 [18:53<09:12,  4.44it/s]

Gaps (ex-reports):  66%|██████▌   | 4759/7211 [18:53<09:06,  4.48it/s]

Gaps (ex-reports):  66%|██████▌   | 4760/7211 [18:53<09:01,  4.52it/s]

Gaps (ex-reports):  66%|██████▌   | 4761/7211 [18:53<08:41,  4.70it/s]

Gaps (ex-reports):  66%|██████▌   | 4762/7211 [18:54<08:36,  4.74it/s]

Gaps (ex-reports):  66%|██████▌   | 4763/7211 [18:54<08:22,  4.87it/s]

Gaps (ex-reports):  66%|██████▌   | 4764/7211 [18:54<08:14,  4.95it/s]

Gaps (ex-reports):  66%|██████▌   | 4765/7211 [18:54<08:10,  4.98it/s]

Gaps (ex-reports):  66%|██████▌   | 4766/7211 [18:54<08:12,  4.96it/s]

Gaps (ex-reports):  66%|██████▌   | 4767/7211 [18:54<08:14,  4.94it/s]

Gaps (ex-reports):  66%|██████▌   | 4768/7211 [18:55<08:09,  4.99it/s]

Gaps (ex-reports):  66%|██████▌   | 4769/7211 [18:55<08:18,  4.90it/s]

Gaps (ex-reports):  66%|██████▌   | 4770/7211 [18:55<08:16,  4.92it/s]

Gaps (ex-reports):  66%|██████▌   | 4771/7211 [18:55<08:09,  4.98it/s]

Gaps (ex-reports):  66%|██████▌   | 4772/7211 [18:55<08:00,  5.08it/s]

Gaps (ex-reports):  66%|██████▌   | 4773/7211 [18:56<07:55,  5.12it/s]

Gaps (ex-reports):  66%|██████▌   | 4774/7211 [18:56<07:54,  5.14it/s]

Gaps (ex-reports):  66%|██████▌   | 4775/7211 [18:56<07:59,  5.08it/s]

Gaps (ex-reports):  66%|██████▌   | 4776/7211 [18:57<14:49,  2.74it/s]

Gaps (ex-reports):  66%|██████▌   | 4777/7211 [18:57<12:41,  3.20it/s]

Gaps (ex-reports):  66%|██████▋   | 4778/7211 [18:57<11:23,  3.56it/s]

Gaps (ex-reports):  66%|██████▋   | 4779/7211 [18:57<10:37,  3.82it/s]

Gaps (ex-reports):  66%|██████▋   | 4780/7211 [18:58<09:55,  4.08it/s]

Gaps (ex-reports):  66%|██████▋   | 4781/7211 [18:58<09:28,  4.27it/s]

Gaps (ex-reports):  66%|██████▋   | 4782/7211 [18:58<08:51,  4.57it/s]

Gaps (ex-reports):  66%|██████▋   | 4783/7211 [18:58<08:38,  4.68it/s]

Gaps (ex-reports):  66%|██████▋   | 4784/7211 [18:58<08:34,  4.72it/s]

Gaps (ex-reports):  66%|██████▋   | 4785/7211 [18:59<08:28,  4.77it/s]

Gaps (ex-reports):  66%|██████▋   | 4786/7211 [18:59<08:28,  4.77it/s]

Gaps (ex-reports):  66%|██████▋   | 4787/7211 [18:59<08:21,  4.84it/s]

Gaps (ex-reports):  66%|██████▋   | 4788/7211 [18:59<09:09,  4.41it/s]

Gaps (ex-reports):  66%|██████▋   | 4789/7211 [19:00<09:34,  4.21it/s]

Gaps (ex-reports):  66%|██████▋   | 4790/7211 [19:00<09:35,  4.21it/s]

Gaps (ex-reports):  66%|██████▋   | 4791/7211 [19:00<09:50,  4.10it/s]

Gaps (ex-reports):  66%|██████▋   | 4792/7211 [19:00<09:23,  4.29it/s]

Gaps (ex-reports):  66%|██████▋   | 4793/7211 [19:01<09:04,  4.44it/s]

Gaps (ex-reports):  66%|██████▋   | 4794/7211 [19:01<08:55,  4.51it/s]

Gaps (ex-reports):  66%|██████▋   | 4795/7211 [19:01<08:44,  4.61it/s]

Gaps (ex-reports):  67%|██████▋   | 4796/7211 [19:01<08:45,  4.59it/s]

Gaps (ex-reports):  67%|██████▋   | 4797/7211 [19:01<08:24,  4.78it/s]

Gaps (ex-reports):  67%|██████▋   | 4798/7211 [19:02<08:24,  4.78it/s]

Gaps (ex-reports):  67%|██████▋   | 4799/7211 [19:02<08:27,  4.75it/s]

Gaps (ex-reports):  67%|██████▋   | 4800/7211 [19:02<08:24,  4.78it/s]

Gaps (ex-reports):  67%|██████▋   | 4801/7211 [19:02<08:21,  4.81it/s]

Gaps (ex-reports):  67%|██████▋   | 4802/7211 [19:02<08:38,  4.64it/s]

Gaps (ex-reports):  67%|██████▋   | 4803/7211 [19:03<08:30,  4.72it/s]

Gaps (ex-reports):  67%|██████▋   | 4804/7211 [19:03<08:32,  4.70it/s]

Gaps (ex-reports):  67%|██████▋   | 4805/7211 [19:03<08:41,  4.61it/s]

Gaps (ex-reports):  67%|██████▋   | 4806/7211 [19:03<08:28,  4.73it/s]

Gaps (ex-reports):  67%|██████▋   | 4807/7211 [19:03<08:27,  4.74it/s]

Gaps (ex-reports):  67%|██████▋   | 4808/7211 [19:04<08:25,  4.76it/s]

Gaps (ex-reports):  67%|██████▋   | 4809/7211 [19:04<08:15,  4.85it/s]

Gaps (ex-reports):  67%|██████▋   | 4810/7211 [19:04<08:12,  4.87it/s]

Gaps (ex-reports):  67%|██████▋   | 4811/7211 [19:04<08:07,  4.92it/s]

Gaps (ex-reports):  67%|██████▋   | 4812/7211 [19:04<08:19,  4.80it/s]

Gaps (ex-reports):  67%|██████▋   | 4813/7211 [19:05<08:08,  4.91it/s]

Gaps (ex-reports):  67%|██████▋   | 4814/7211 [19:05<08:01,  4.98it/s]

Gaps (ex-reports):  67%|██████▋   | 4815/7211 [19:05<07:57,  5.02it/s]

Gaps (ex-reports):  67%|██████▋   | 4816/7211 [19:05<07:51,  5.08it/s]

Gaps (ex-reports):  67%|██████▋   | 4817/7211 [19:05<08:09,  4.89it/s]

Gaps (ex-reports):  67%|██████▋   | 4818/7211 [19:06<08:06,  4.92it/s]

Gaps (ex-reports):  67%|██████▋   | 4819/7211 [19:06<08:06,  4.92it/s]

Gaps (ex-reports):  67%|██████▋   | 4820/7211 [19:06<08:10,  4.88it/s]

Gaps (ex-reports):  67%|██████▋   | 4821/7211 [19:06<08:08,  4.89it/s]

Gaps (ex-reports):  67%|██████▋   | 4822/7211 [19:07<08:48,  4.52it/s]

Gaps (ex-reports):  67%|██████▋   | 4823/7211 [19:07<08:43,  4.56it/s]

Gaps (ex-reports):  67%|██████▋   | 4824/7211 [19:07<08:33,  4.65it/s]

Gaps (ex-reports):  67%|██████▋   | 4825/7211 [19:07<08:22,  4.75it/s]

Gaps (ex-reports):  67%|██████▋   | 4826/7211 [19:07<08:23,  4.74it/s]

Gaps (ex-reports):  67%|██████▋   | 4827/7211 [19:08<08:19,  4.77it/s]

Gaps (ex-reports):  67%|██████▋   | 4828/7211 [19:08<08:30,  4.67it/s]

Gaps (ex-reports):  67%|██████▋   | 4829/7211 [19:08<08:24,  4.72it/s]

Gaps (ex-reports):  67%|██████▋   | 4830/7211 [19:08<08:11,  4.84it/s]

Gaps (ex-reports):  67%|██████▋   | 4831/7211 [19:08<08:34,  4.63it/s]

Gaps (ex-reports):  67%|██████▋   | 4832/7211 [19:09<08:25,  4.71it/s]

Gaps (ex-reports):  67%|██████▋   | 4833/7211 [19:09<08:15,  4.80it/s]

Gaps (ex-reports):  67%|██████▋   | 4834/7211 [19:09<07:59,  4.95it/s]

Gaps (ex-reports):  67%|██████▋   | 4835/7211 [19:09<08:06,  4.89it/s]

Gaps (ex-reports):  67%|██████▋   | 4836/7211 [19:09<08:01,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4837/7211 [19:10<08:08,  4.86it/s]

Gaps (ex-reports):  67%|██████▋   | 4838/7211 [19:10<07:58,  4.96it/s]

Gaps (ex-reports):  67%|██████▋   | 4839/7211 [19:10<07:54,  5.00it/s]

Gaps (ex-reports):  67%|██████▋   | 4840/7211 [19:10<08:00,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4841/7211 [19:10<08:00,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4842/7211 [19:11<08:14,  4.79it/s]

Gaps (ex-reports):  67%|██████▋   | 4843/7211 [19:11<08:14,  4.79it/s]

Gaps (ex-reports):  67%|██████▋   | 4844/7211 [19:11<08:08,  4.85it/s]

Gaps (ex-reports):  67%|██████▋   | 4845/7211 [19:11<08:44,  4.51it/s]

Gaps (ex-reports):  67%|██████▋   | 4846/7211 [19:12<12:56,  3.04it/s]

Gaps (ex-reports):  67%|██████▋   | 4847/7211 [19:12<11:23,  3.46it/s]

Gaps (ex-reports):  67%|██████▋   | 4848/7211 [19:12<10:29,  3.75it/s]

Gaps (ex-reports):  67%|██████▋   | 4849/7211 [19:13<09:47,  4.02it/s]

Gaps (ex-reports):  67%|██████▋   | 4850/7211 [19:13<09:20,  4.22it/s]

Gaps (ex-reports):  67%|██████▋   | 4851/7211 [19:13<08:54,  4.41it/s]

Gaps (ex-reports):  67%|██████▋   | 4852/7211 [19:13<08:50,  4.45it/s]

Gaps (ex-reports):  67%|██████▋   | 4853/7211 [19:13<08:31,  4.61it/s]

Gaps (ex-reports):  67%|██████▋   | 4854/7211 [19:14<08:24,  4.68it/s]

Gaps (ex-reports):  67%|██████▋   | 4855/7211 [19:14<08:14,  4.77it/s]

Gaps (ex-reports):  67%|██████▋   | 4856/7211 [19:14<08:08,  4.82it/s]

Gaps (ex-reports):  67%|██████▋   | 4857/7211 [19:14<08:07,  4.83it/s]

Gaps (ex-reports):  67%|██████▋   | 4858/7211 [19:14<08:15,  4.75it/s]

Gaps (ex-reports):  67%|██████▋   | 4859/7211 [19:15<08:07,  4.82it/s]

Gaps (ex-reports):  67%|██████▋   | 4860/7211 [19:15<08:15,  4.74it/s]

Gaps (ex-reports):  67%|██████▋   | 4861/7211 [19:15<08:15,  4.75it/s]

Gaps (ex-reports):  67%|██████▋   | 4862/7211 [19:15<08:11,  4.78it/s]

Gaps (ex-reports):  67%|██████▋   | 4863/7211 [19:15<08:01,  4.88it/s]

Gaps (ex-reports):  67%|██████▋   | 4864/7211 [19:16<07:56,  4.92it/s]

Gaps (ex-reports):  67%|██████▋   | 4865/7211 [19:16<07:54,  4.94it/s]

Gaps (ex-reports):  67%|██████▋   | 4866/7211 [19:16<08:02,  4.86it/s]

Gaps (ex-reports):  67%|██████▋   | 4867/7211 [19:16<08:02,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4868/7211 [19:16<08:02,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4869/7211 [19:17<08:01,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4870/7211 [19:17<07:54,  4.93it/s]

Gaps (ex-reports):  68%|██████▊   | 4871/7211 [19:17<07:59,  4.88it/s]

Gaps (ex-reports):  68%|██████▊   | 4872/7211 [19:17<07:57,  4.90it/s]

Gaps (ex-reports):  68%|██████▊   | 4873/7211 [19:18<08:02,  4.85it/s]

Gaps (ex-reports):  68%|██████▊   | 4874/7211 [19:18<08:04,  4.82it/s]

Gaps (ex-reports):  68%|██████▊   | 4875/7211 [19:18<08:05,  4.81it/s]

Gaps (ex-reports):  68%|██████▊   | 4876/7211 [19:18<08:07,  4.79it/s]

Gaps (ex-reports):  68%|██████▊   | 4877/7211 [19:18<08:02,  4.83it/s]

Gaps (ex-reports):  68%|██████▊   | 4878/7211 [19:19<08:05,  4.80it/s]

Gaps (ex-reports):  68%|██████▊   | 4879/7211 [19:19<07:55,  4.90it/s]

Gaps (ex-reports):  68%|██████▊   | 4880/7211 [19:19<07:59,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4881/7211 [19:19<07:56,  4.89it/s]

Gaps (ex-reports):  68%|██████▊   | 4882/7211 [19:19<07:55,  4.90it/s]

Gaps (ex-reports):  68%|██████▊   | 4883/7211 [19:20<07:49,  4.96it/s]

Gaps (ex-reports):  68%|██████▊   | 4884/7211 [19:20<07:49,  4.95it/s]

Gaps (ex-reports):  68%|██████▊   | 4885/7211 [19:20<07:52,  4.93it/s]

Gaps (ex-reports):  68%|██████▊   | 4886/7211 [19:20<07:49,  4.95it/s]

Gaps (ex-reports):  68%|██████▊   | 4887/7211 [19:20<07:48,  4.96it/s]

Gaps (ex-reports):  68%|██████▊   | 4888/7211 [19:21<07:47,  4.97it/s]

Gaps (ex-reports):  68%|██████▊   | 4889/7211 [19:21<07:50,  4.93it/s]

Gaps (ex-reports):  68%|██████▊   | 4890/7211 [19:21<07:51,  4.92it/s]

Gaps (ex-reports):  68%|██████▊   | 4891/7211 [19:21<07:52,  4.91it/s]

Gaps (ex-reports):  68%|██████▊   | 4892/7211 [19:21<07:53,  4.89it/s]

Gaps (ex-reports):  68%|██████▊   | 4893/7211 [19:22<07:57,  4.85it/s]

Gaps (ex-reports):  68%|██████▊   | 4894/7211 [19:22<07:57,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4895/7211 [19:22<07:59,  4.83it/s]

Gaps (ex-reports):  68%|██████▊   | 4896/7211 [19:22<07:59,  4.82it/s]

Gaps (ex-reports):  68%|██████▊   | 4897/7211 [19:22<08:02,  4.80it/s]

Gaps (ex-reports):  68%|██████▊   | 4898/7211 [19:23<07:58,  4.83it/s]

Gaps (ex-reports):  68%|██████▊   | 4899/7211 [19:23<07:59,  4.82it/s]

Gaps (ex-reports):  68%|██████▊   | 4900/7211 [19:23<07:44,  4.97it/s]

Gaps (ex-reports):  68%|██████▊   | 4901/7211 [19:23<07:48,  4.93it/s]

Gaps (ex-reports):  68%|██████▊   | 4902/7211 [19:23<07:52,  4.88it/s]

Gaps (ex-reports):  68%|██████▊   | 4903/7211 [19:24<07:47,  4.94it/s]

Gaps (ex-reports):  68%|██████▊   | 4904/7211 [19:24<07:46,  4.95it/s]

Gaps (ex-reports):  68%|██████▊   | 4905/7211 [19:24<07:41,  4.99it/s]

Gaps (ex-reports):  68%|██████▊   | 4906/7211 [19:24<07:46,  4.94it/s]

Gaps (ex-reports):  68%|██████▊   | 4907/7211 [19:24<07:46,  4.94it/s]

Gaps (ex-reports):  68%|██████▊   | 4908/7211 [19:25<07:38,  5.02it/s]

Gaps (ex-reports):  68%|██████▊   | 4909/7211 [19:25<07:41,  4.99it/s]

Gaps (ex-reports):  68%|██████▊   | 4910/7211 [19:25<07:38,  5.02it/s]

Gaps (ex-reports):  68%|██████▊   | 4911/7211 [19:25<08:00,  4.79it/s]

Gaps (ex-reports):  68%|██████▊   | 4912/7211 [19:25<08:03,  4.76it/s]

Gaps (ex-reports):  68%|██████▊   | 4913/7211 [19:26<07:49,  4.90it/s]

Gaps (ex-reports):  68%|██████▊   | 4914/7211 [19:26<07:57,  4.81it/s]

Gaps (ex-reports):  68%|██████▊   | 4915/7211 [19:26<07:42,  4.97it/s]

Gaps (ex-reports):  68%|██████▊   | 4916/7211 [19:26<07:40,  4.99it/s]

Gaps (ex-reports):  68%|██████▊   | 4917/7211 [19:26<07:47,  4.90it/s]

Gaps (ex-reports):  68%|██████▊   | 4918/7211 [19:27<07:53,  4.84it/s]

Gaps (ex-reports):  68%|██████▊   | 4919/7211 [19:27<07:46,  4.91it/s]

Gaps (ex-reports):  68%|██████▊   | 4920/7211 [19:27<07:38,  5.00it/s]

Gaps (ex-reports):  68%|██████▊   | 4921/7211 [19:27<07:32,  5.06it/s]

Gaps (ex-reports):  68%|██████▊   | 4922/7211 [19:27<07:33,  5.05it/s]

Gaps (ex-reports):  68%|██████▊   | 4923/7211 [19:28<07:33,  5.05it/s]

Gaps (ex-reports):  68%|██████▊   | 4924/7211 [19:28<07:39,  4.98it/s]

Gaps (ex-reports):  68%|██████▊   | 4925/7211 [19:28<07:36,  5.01it/s]

Gaps (ex-reports):  68%|██████▊   | 4926/7211 [19:28<07:38,  4.98it/s]

Gaps (ex-reports):  68%|██████▊   | 4927/7211 [19:28<07:43,  4.93it/s]

Gaps (ex-reports):  68%|██████▊   | 4928/7211 [19:29<07:39,  4.97it/s]

Gaps (ex-reports):  68%|██████▊   | 4929/7211 [19:29<07:46,  4.89it/s]

Gaps (ex-reports):  68%|██████▊   | 4930/7211 [19:29<07:51,  4.84it/s]

Gaps (ex-reports):  68%|██████▊   | 4931/7211 [19:29<07:49,  4.85it/s]

Gaps (ex-reports):  68%|██████▊   | 4932/7211 [19:30<07:48,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4933/7211 [19:30<07:48,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4934/7211 [19:30<07:41,  4.93it/s]

Gaps (ex-reports):  68%|██████▊   | 4935/7211 [19:30<07:33,  5.02it/s]

Gaps (ex-reports):  68%|██████▊   | 4936/7211 [19:30<07:33,  5.02it/s]

Gaps (ex-reports):  68%|██████▊   | 4937/7211 [19:31<07:47,  4.87it/s]

Gaps (ex-reports):  68%|██████▊   | 4938/7211 [19:31<07:41,  4.92it/s]

Gaps (ex-reports):  68%|██████▊   | 4939/7211 [19:31<14:00,  2.70it/s]

Gaps (ex-reports):  69%|██████▊   | 4940/7211 [19:32<12:22,  3.06it/s]

Gaps (ex-reports):  69%|██████▊   | 4941/7211 [19:32<11:05,  3.41it/s]

Gaps (ex-reports):  69%|██████▊   | 4942/7211 [19:32<10:04,  3.75it/s]

Gaps (ex-reports):  69%|██████▊   | 4943/7211 [19:32<09:17,  4.06it/s]

Gaps (ex-reports):  69%|██████▊   | 4944/7211 [19:33<08:51,  4.26it/s]

Gaps (ex-reports):  69%|██████▊   | 4945/7211 [19:33<08:29,  4.45it/s]

Gaps (ex-reports):  69%|██████▊   | 4946/7211 [19:33<08:06,  4.66it/s]

Gaps (ex-reports):  69%|██████▊   | 4947/7211 [19:33<07:55,  4.76it/s]

Gaps (ex-reports):  69%|██████▊   | 4948/7211 [19:33<07:53,  4.78it/s]

Gaps (ex-reports):  69%|██████▊   | 4949/7211 [19:34<07:52,  4.79it/s]

Gaps (ex-reports):  69%|██████▊   | 4950/7211 [19:34<07:56,  4.75it/s]

Gaps (ex-reports):  69%|██████▊   | 4951/7211 [19:34<07:51,  4.79it/s]

Gaps (ex-reports):  69%|██████▊   | 4952/7211 [19:34<07:49,  4.81it/s]

Gaps (ex-reports):  69%|██████▊   | 4953/7211 [19:34<07:50,  4.80it/s]

Gaps (ex-reports):  69%|██████▊   | 4954/7211 [19:35<07:48,  4.82it/s]

Gaps (ex-reports):  69%|██████▊   | 4955/7211 [19:35<07:43,  4.86it/s]

Gaps (ex-reports):  69%|██████▊   | 4956/7211 [19:35<07:35,  4.95it/s]

Gaps (ex-reports):  69%|██████▊   | 4957/7211 [19:35<07:31,  4.99it/s]

Gaps (ex-reports):  69%|██████▉   | 4958/7211 [19:35<07:32,  4.98it/s]

Gaps (ex-reports):  69%|██████▉   | 4959/7211 [19:36<07:33,  4.97it/s]

Gaps (ex-reports):  69%|██████▉   | 4960/7211 [19:36<07:32,  4.97it/s]

Gaps (ex-reports):  69%|██████▉   | 4961/7211 [19:36<07:36,  4.93it/s]

Gaps (ex-reports):  69%|██████▉   | 4962/7211 [19:36<07:42,  4.86it/s]

Gaps (ex-reports):  69%|██████▉   | 4963/7211 [19:36<07:44,  4.84it/s]

Gaps (ex-reports):  69%|██████▉   | 4964/7211 [19:37<07:40,  4.88it/s]

Gaps (ex-reports):  69%|██████▉   | 4965/7211 [19:37<07:54,  4.74it/s]

Gaps (ex-reports):  69%|██████▉   | 4966/7211 [19:37<08:18,  4.50it/s]

Gaps (ex-reports):  69%|██████▉   | 4967/7211 [19:37<08:06,  4.62it/s]

Gaps (ex-reports):  69%|██████▉   | 4968/7211 [19:38<08:01,  4.66it/s]

Gaps (ex-reports):  69%|██████▉   | 4969/7211 [19:38<07:53,  4.73it/s]

Gaps (ex-reports):  69%|██████▉   | 4970/7211 [19:38<07:49,  4.77it/s]

Gaps (ex-reports):  69%|██████▉   | 4971/7211 [19:38<07:49,  4.77it/s]

Gaps (ex-reports):  69%|██████▉   | 4972/7211 [19:38<07:44,  4.82it/s]

Gaps (ex-reports):  69%|██████▉   | 4973/7211 [19:39<07:47,  4.79it/s]

Gaps (ex-reports):  69%|██████▉   | 4974/7211 [19:39<07:36,  4.90it/s]

Gaps (ex-reports):  69%|██████▉   | 4975/7211 [19:39<07:26,  5.01it/s]

Gaps (ex-reports):  69%|██████▉   | 4976/7211 [19:39<07:20,  5.07it/s]

Gaps (ex-reports):  69%|██████▉   | 4977/7211 [19:39<07:23,  5.04it/s]

Gaps (ex-reports):  69%|██████▉   | 4978/7211 [19:40<07:22,  5.04it/s]

Gaps (ex-reports):  69%|██████▉   | 4979/7211 [19:40<07:18,  5.09it/s]

Gaps (ex-reports):  69%|██████▉   | 4980/7211 [19:40<07:15,  5.12it/s]

Gaps (ex-reports):  69%|██████▉   | 4981/7211 [19:40<07:15,  5.12it/s]

Gaps (ex-reports):  69%|██████▉   | 4982/7211 [19:40<07:12,  5.15it/s]

Gaps (ex-reports):  69%|██████▉   | 4983/7211 [19:40<07:12,  5.15it/s]

Gaps (ex-reports):  69%|██████▉   | 4984/7211 [19:41<07:15,  5.11it/s]

Gaps (ex-reports):  69%|██████▉   | 4985/7211 [19:41<07:31,  4.93it/s]

Gaps (ex-reports):  69%|██████▉   | 4986/7211 [19:41<07:27,  4.97it/s]

Gaps (ex-reports):  69%|██████▉   | 4987/7211 [19:41<07:31,  4.92it/s]

Gaps (ex-reports):  69%|██████▉   | 4988/7211 [19:41<07:27,  4.97it/s]

Gaps (ex-reports):  69%|██████▉   | 4989/7211 [19:42<07:31,  4.92it/s]

Gaps (ex-reports):  69%|██████▉   | 4990/7211 [19:42<07:27,  4.96it/s]

Gaps (ex-reports):  69%|██████▉   | 4991/7211 [19:42<07:31,  4.92it/s]

Gaps (ex-reports):  69%|██████▉   | 4992/7211 [19:42<07:25,  4.99it/s]

Gaps (ex-reports):  69%|██████▉   | 4993/7211 [19:43<07:34,  4.88it/s]

Gaps (ex-reports):  69%|██████▉   | 4994/7211 [19:43<07:28,  4.94it/s]

Gaps (ex-reports):  69%|██████▉   | 4995/7211 [19:43<07:26,  4.96it/s]

Gaps (ex-reports):  69%|██████▉   | 4996/7211 [19:43<07:31,  4.90it/s]

Gaps (ex-reports):  69%|██████▉   | 4997/7211 [19:43<07:31,  4.90it/s]

Gaps (ex-reports):  69%|██████▉   | 4998/7211 [19:44<07:36,  4.85it/s]

Gaps (ex-reports):  69%|██████▉   | 4999/7211 [19:44<07:33,  4.88it/s]

Gaps (ex-reports):  69%|██████▉   | 5000/7211 [19:44<07:24,  4.98it/s]

Gaps (ex-reports):  69%|██████▉   | 5001/7211 [19:44<07:23,  4.98it/s]

Gaps (ex-reports):  69%|██████▉   | 5002/7211 [19:44<07:25,  4.96it/s]

Gaps (ex-reports):  69%|██████▉   | 5003/7211 [19:45<07:28,  4.92it/s]

Gaps (ex-reports):  69%|██████▉   | 5004/7211 [19:45<07:21,  5.00it/s]

Gaps (ex-reports):  69%|██████▉   | 5005/7211 [19:45<07:30,  4.89it/s]

Gaps (ex-reports):  69%|██████▉   | 5006/7211 [19:45<07:28,  4.92it/s]

Gaps (ex-reports):  69%|██████▉   | 5007/7211 [19:45<07:26,  4.94it/s]

Gaps (ex-reports):  69%|██████▉   | 5008/7211 [19:46<07:23,  4.96it/s]

Gaps (ex-reports):  69%|██████▉   | 5009/7211 [19:46<07:20,  5.00it/s]

Gaps (ex-reports):  69%|██████▉   | 5010/7211 [19:46<07:28,  4.91it/s]

Gaps (ex-reports):  69%|██████▉   | 5011/7211 [19:46<07:26,  4.93it/s]

Gaps (ex-reports):  70%|██████▉   | 5012/7211 [19:46<07:20,  4.99it/s]

Gaps (ex-reports):  70%|██████▉   | 5013/7211 [19:47<07:16,  5.03it/s]

Gaps (ex-reports):  70%|██████▉   | 5014/7211 [19:47<07:20,  4.99it/s]

Gaps (ex-reports):  70%|██████▉   | 5015/7211 [19:47<07:14,  5.06it/s]

Gaps (ex-reports):  70%|██████▉   | 5016/7211 [19:47<07:08,  5.13it/s]

Gaps (ex-reports):  70%|██████▉   | 5017/7211 [19:47<07:16,  5.02it/s]

Gaps (ex-reports):  70%|██████▉   | 5018/7211 [19:48<07:18,  5.00it/s]

Gaps (ex-reports):  70%|██████▉   | 5019/7211 [19:48<11:10,  3.27it/s]

Gaps (ex-reports):  70%|██████▉   | 5020/7211 [19:48<10:01,  3.64it/s]

Gaps (ex-reports):  70%|██████▉   | 5021/7211 [19:49<09:20,  3.91it/s]

Gaps (ex-reports):  70%|██████▉   | 5022/7211 [19:49<08:42,  4.19it/s]

Gaps (ex-reports):  70%|██████▉   | 5023/7211 [19:49<08:10,  4.46it/s]

Gaps (ex-reports):  70%|██████▉   | 5024/7211 [19:49<07:58,  4.57it/s]

Gaps (ex-reports):  70%|██████▉   | 5025/7211 [19:49<07:44,  4.71it/s]

Gaps (ex-reports):  70%|██████▉   | 5026/7211 [19:49<07:29,  4.86it/s]

Gaps (ex-reports):  70%|██████▉   | 5027/7211 [19:50<07:33,  4.82it/s]

Gaps (ex-reports):  70%|██████▉   | 5028/7211 [19:50<07:32,  4.83it/s]

Gaps (ex-reports):  70%|██████▉   | 5029/7211 [19:50<07:29,  4.85it/s]

Gaps (ex-reports):  70%|██████▉   | 5030/7211 [19:50<07:21,  4.94it/s]

Gaps (ex-reports):  70%|██████▉   | 5031/7211 [19:51<07:16,  5.00it/s]

Gaps (ex-reports):  70%|██████▉   | 5032/7211 [19:51<07:17,  4.99it/s]

Gaps (ex-reports):  70%|██████▉   | 5033/7211 [19:51<07:15,  5.00it/s]

Gaps (ex-reports):  70%|██████▉   | 5034/7211 [19:51<07:23,  4.91it/s]

Gaps (ex-reports):  70%|██████▉   | 5035/7211 [19:51<07:18,  4.96it/s]

Gaps (ex-reports):  70%|██████▉   | 5036/7211 [19:52<07:16,  4.99it/s]

Gaps (ex-reports):  70%|██████▉   | 5037/7211 [19:52<07:23,  4.90it/s]

Gaps (ex-reports):  70%|██████▉   | 5038/7211 [19:52<07:31,  4.81it/s]

Gaps (ex-reports):  70%|██████▉   | 5039/7211 [19:52<07:26,  4.86it/s]

Gaps (ex-reports):  70%|██████▉   | 5040/7211 [19:52<07:22,  4.91it/s]

Gaps (ex-reports):  70%|██████▉   | 5041/7211 [19:53<07:38,  4.73it/s]

Gaps (ex-reports):  70%|██████▉   | 5042/7211 [19:53<07:44,  4.67it/s]

Gaps (ex-reports):  70%|██████▉   | 5043/7211 [19:53<07:44,  4.67it/s]

Gaps (ex-reports):  70%|██████▉   | 5044/7211 [19:53<07:30,  4.81it/s]

Gaps (ex-reports):  70%|██████▉   | 5045/7211 [19:53<07:27,  4.84it/s]

Gaps (ex-reports):  70%|██████▉   | 5046/7211 [19:54<07:22,  4.89it/s]

Gaps (ex-reports):  70%|██████▉   | 5047/7211 [19:54<07:33,  4.78it/s]

Gaps (ex-reports):  70%|███████   | 5048/7211 [19:54<07:32,  4.78it/s]

Gaps (ex-reports):  70%|███████   | 5049/7211 [19:54<07:19,  4.92it/s]

Gaps (ex-reports):  70%|███████   | 5050/7211 [19:54<07:19,  4.91it/s]

Gaps (ex-reports):  70%|███████   | 5051/7211 [19:55<07:15,  4.96it/s]

Gaps (ex-reports):  70%|███████   | 5052/7211 [19:55<07:17,  4.94it/s]

Gaps (ex-reports):  70%|███████   | 5053/7211 [19:55<07:11,  5.00it/s]

Gaps (ex-reports):  70%|███████   | 5054/7211 [19:55<07:06,  5.06it/s]

Gaps (ex-reports):  70%|███████   | 5055/7211 [19:55<07:09,  5.02it/s]

Gaps (ex-reports):  70%|███████   | 5056/7211 [19:56<07:08,  5.03it/s]

Gaps (ex-reports):  70%|███████   | 5057/7211 [19:56<07:08,  5.03it/s]

Gaps (ex-reports):  70%|███████   | 5058/7211 [19:56<07:03,  5.08it/s]

Gaps (ex-reports):  70%|███████   | 5059/7211 [19:56<07:06,  5.04it/s]

Gaps (ex-reports):  70%|███████   | 5060/7211 [19:56<07:06,  5.04it/s]

Gaps (ex-reports):  70%|███████   | 5061/7211 [19:57<07:13,  4.96it/s]

Gaps (ex-reports):  70%|███████   | 5062/7211 [19:57<07:16,  4.92it/s]

Gaps (ex-reports):  70%|███████   | 5063/7211 [19:57<07:16,  4.92it/s]

Gaps (ex-reports):  70%|███████   | 5064/7211 [19:57<07:16,  4.92it/s]

Gaps (ex-reports):  70%|███████   | 5065/7211 [19:58<08:02,  4.45it/s]

Gaps (ex-reports):  70%|███████   | 5066/7211 [19:58<07:55,  4.51it/s]

Gaps (ex-reports):  70%|███████   | 5067/7211 [19:58<07:50,  4.55it/s]

Gaps (ex-reports):  70%|███████   | 5068/7211 [19:58<07:43,  4.62it/s]

Gaps (ex-reports):  70%|███████   | 5069/7211 [19:58<07:27,  4.79it/s]

Gaps (ex-reports):  70%|███████   | 5070/7211 [19:59<07:25,  4.81it/s]

Gaps (ex-reports):  70%|███████   | 5071/7211 [19:59<07:21,  4.85it/s]

Gaps (ex-reports):  70%|███████   | 5072/7211 [19:59<07:16,  4.90it/s]

Gaps (ex-reports):  70%|███████   | 5073/7211 [19:59<07:08,  4.99it/s]

Gaps (ex-reports):  70%|███████   | 5074/7211 [19:59<06:59,  5.10it/s]

Gaps (ex-reports):  70%|███████   | 5075/7211 [20:00<06:59,  5.09it/s]

Gaps (ex-reports):  70%|███████   | 5076/7211 [20:00<07:02,  5.05it/s]

Gaps (ex-reports):  70%|███████   | 5077/7211 [20:00<07:04,  5.03it/s]

Gaps (ex-reports):  70%|███████   | 5078/7211 [20:00<07:52,  4.52it/s]

Gaps (ex-reports):  70%|███████   | 5079/7211 [20:00<07:45,  4.58it/s]

Gaps (ex-reports):  70%|███████   | 5080/7211 [20:01<07:39,  4.64it/s]

Gaps (ex-reports):  70%|███████   | 5081/7211 [20:01<07:42,  4.61it/s]

Gaps (ex-reports):  70%|███████   | 5082/7211 [20:01<07:43,  4.60it/s]

Gaps (ex-reports):  70%|███████   | 5083/7211 [20:01<07:38,  4.65it/s]

Gaps (ex-reports):  71%|███████   | 5084/7211 [20:01<07:32,  4.70it/s]

Gaps (ex-reports):  71%|███████   | 5085/7211 [20:02<07:22,  4.81it/s]

Gaps (ex-reports):  71%|███████   | 5086/7211 [20:02<07:18,  4.85it/s]

Gaps (ex-reports):  71%|███████   | 5087/7211 [20:02<07:09,  4.95it/s]

Gaps (ex-reports):  71%|███████   | 5088/7211 [20:02<07:11,  4.92it/s]

Gaps (ex-reports):  71%|███████   | 5089/7211 [20:02<07:16,  4.86it/s]

Gaps (ex-reports):  71%|███████   | 5090/7211 [20:03<07:08,  4.95it/s]

Gaps (ex-reports):  71%|███████   | 5091/7211 [20:03<06:59,  5.05it/s]

Gaps (ex-reports):  71%|███████   | 5092/7211 [20:03<07:02,  5.02it/s]

Gaps (ex-reports):  71%|███████   | 5093/7211 [20:03<07:04,  4.99it/s]

Gaps (ex-reports):  71%|███████   | 5094/7211 [20:03<07:10,  4.91it/s]

Gaps (ex-reports):  71%|███████   | 5095/7211 [20:04<07:09,  4.92it/s]

Gaps (ex-reports):  71%|███████   | 5096/7211 [20:18<2:39:19,  4.52s/it]

Gaps (ex-reports):  71%|███████   | 5097/7211 [20:18<1:53:42,  3.23s/it]

Gaps (ex-reports):  71%|███████   | 5098/7211 [20:19<1:21:46,  2.32s/it]

Gaps (ex-reports):  71%|███████   | 5099/7211 [20:19<59:22,  1.69s/it]

Gaps (ex-reports):  71%|███████   | 5100/7211 [20:19<43:43,  1.24s/it]

Gaps (ex-reports):  71%|███████   | 5101/7211 [20:19<32:46,  1.07it/s]

Gaps (ex-reports):  71%|███████   | 5102/7211 [20:20<25:03,  1.40it/s]

Gaps (ex-reports):  71%|███████   | 5103/7211 [20:20<23:59,  1.46it/s]

Gaps (ex-reports):  71%|███████   | 5104/7211 [20:20<19:12,  1.83it/s]

Gaps (ex-reports):  71%|███████   | 5105/7211 [20:21<15:36,  2.25it/s]

Gaps (ex-reports):  71%|███████   | 5106/7211 [20:21<12:58,  2.70it/s]

Gaps (ex-reports):  71%|███████   | 5107/7211 [20:21<11:20,  3.09it/s]

Gaps (ex-reports):  71%|███████   | 5108/7211 [20:21<10:05,  3.47it/s]

Gaps (ex-reports):  71%|███████   | 5109/7211 [20:21<09:13,  3.80it/s]

Gaps (ex-reports):  71%|███████   | 5110/7211 [20:22<12:04,  2.90it/s]

Gaps (ex-reports):  71%|███████   | 5111/7211 [20:22<10:36,  3.30it/s]

Gaps (ex-reports):  71%|███████   | 5112/7211 [20:22<09:37,  3.63it/s]

Gaps (ex-reports):  71%|███████   | 5113/7211 [20:23<08:54,  3.93it/s]

Gaps (ex-reports):  71%|███████   | 5114/7211 [20:23<08:18,  4.21it/s]

Gaps (ex-reports):  71%|███████   | 5115/7211 [20:23<07:55,  4.41it/s]

Gaps (ex-reports):  71%|███████   | 5116/7211 [20:23<07:36,  4.59it/s]

Gaps (ex-reports):  71%|███████   | 5117/7211 [20:23<07:31,  4.63it/s]

Gaps (ex-reports):  71%|███████   | 5118/7211 [20:24<07:23,  4.72it/s]

Gaps (ex-reports):  71%|███████   | 5119/7211 [20:24<07:10,  4.86it/s]

Gaps (ex-reports):  71%|███████   | 5120/7211 [20:24<07:02,  4.95it/s]

Gaps (ex-reports):  71%|███████   | 5121/7211 [20:24<07:05,  4.92it/s]

Gaps (ex-reports):  71%|███████   | 5122/7211 [20:24<07:05,  4.91it/s]

Gaps (ex-reports):  71%|███████   | 5123/7211 [20:25<07:04,  4.92it/s]

Gaps (ex-reports):  71%|███████   | 5124/7211 [20:25<07:08,  4.87it/s]

Gaps (ex-reports):  71%|███████   | 5125/7211 [20:25<07:15,  4.79it/s]

Gaps (ex-reports):  71%|███████   | 5126/7211 [20:25<07:11,  4.83it/s]

Gaps (ex-reports):  71%|███████   | 5127/7211 [20:25<07:10,  4.84it/s]

Gaps (ex-reports):  71%|███████   | 5128/7211 [20:26<07:03,  4.92it/s]

Gaps (ex-reports):  71%|███████   | 5129/7211 [20:26<07:09,  4.85it/s]

Gaps (ex-reports):  71%|███████   | 5130/7211 [20:26<07:04,  4.90it/s]

Gaps (ex-reports):  71%|███████   | 5131/7211 [20:26<07:02,  4.92it/s]

Gaps (ex-reports):  71%|███████   | 5132/7211 [20:26<06:59,  4.95it/s]

Gaps (ex-reports):  71%|███████   | 5133/7211 [20:27<07:03,  4.91it/s]

Gaps (ex-reports):  71%|███████   | 5134/7211 [20:27<07:17,  4.75it/s]

Gaps (ex-reports):  71%|███████   | 5135/7211 [20:27<07:12,  4.80it/s]

Gaps (ex-reports):  71%|███████   | 5136/7211 [20:27<07:18,  4.74it/s]

Gaps (ex-reports):  71%|███████   | 5137/7211 [20:27<07:12,  4.80it/s]

Gaps (ex-reports):  71%|███████▏  | 5138/7211 [20:28<07:18,  4.73it/s]

Gaps (ex-reports):  71%|███████▏  | 5139/7211 [20:28<07:19,  4.72it/s]

Gaps (ex-reports):  71%|███████▏  | 5140/7211 [20:28<07:14,  4.76it/s]

Gaps (ex-reports):  71%|███████▏  | 5141/7211 [20:28<07:04,  4.87it/s]

Gaps (ex-reports):  71%|███████▏  | 5142/7211 [20:28<06:58,  4.94it/s]

Gaps (ex-reports):  71%|███████▏  | 5143/7211 [20:29<07:00,  4.92it/s]

Gaps (ex-reports):  71%|███████▏  | 5144/7211 [20:29<06:47,  5.08it/s]

Gaps (ex-reports):  71%|███████▏  | 5145/7211 [20:29<06:52,  5.00it/s]

Gaps (ex-reports):  71%|███████▏  | 5146/7211 [20:29<07:00,  4.91it/s]

Gaps (ex-reports):  71%|███████▏  | 5147/7211 [20:29<06:56,  4.96it/s]

Gaps (ex-reports):  71%|███████▏  | 5148/7211 [20:30<06:58,  4.93it/s]

Gaps (ex-reports):  71%|███████▏  | 5149/7211 [21:30<10:27:24, 18.26s/it]

Gaps (ex-reports):  71%|███████▏  | 5150/7211 [21:30<7:20:58, 12.84s/it]

Gaps (ex-reports):  71%|███████▏  | 5151/7211 [21:30<5:10:39,  9.05s/it]

Gaps (ex-reports):  71%|███████▏  | 5152/7211 [21:31<3:39:22,  6.39s/it]

Gaps (ex-reports):  71%|███████▏  | 5153/7211 [21:31<2:35:36,  4.54s/it]

Gaps (ex-reports):  71%|███████▏  | 5154/7211 [21:31<1:51:02,  3.24s/it]

Gaps (ex-reports):  71%|███████▏  | 5155/7211 [21:31<1:19:50,  2.33s/it]

Gaps (ex-reports):  72%|███████▏  | 5156/7211 [21:31<58:00,  1.69s/it]

Gaps (ex-reports):  72%|███████▏  | 5157/7211 [21:32<42:43,  1.25s/it]

Gaps (ex-reports):  72%|███████▏  | 5158/7211 [21:32<31:58,  1.07it/s]

Gaps (ex-reports):  72%|███████▏  | 5159/7211 [21:32<24:30,  1.40it/s]

Gaps (ex-reports):  72%|███████▏  | 5160/7211 [21:32<19:17,  1.77it/s]

Gaps (ex-reports):  72%|███████▏  | 5161/7211 [21:33<15:38,  2.18it/s]

Gaps (ex-reports):  72%|███████▏  | 5162/7211 [21:33<13:00,  2.62it/s]

Gaps (ex-reports):  72%|███████▏  | 5163/7211 [21:33<11:05,  3.08it/s]

Gaps (ex-reports):  72%|███████▏  | 5164/7211 [21:33<09:52,  3.45it/s]

Gaps (ex-reports):  72%|███████▏  | 5165/7211 [21:33<08:54,  3.83it/s]

Gaps (ex-reports):  72%|███████▏  | 5166/7211 [21:34<08:28,  4.02it/s]

Gaps (ex-reports):  72%|███████▏  | 5167/7211 [21:34<07:54,  4.31it/s]

Gaps (ex-reports):  72%|███████▏  | 5168/7211 [21:34<07:31,  4.52it/s]

Gaps (ex-reports):  72%|███████▏  | 5169/7211 [21:34<07:20,  4.64it/s]

Gaps (ex-reports):  72%|███████▏  | 5170/7211 [21:34<07:22,  4.62it/s]

Gaps (ex-reports):  72%|███████▏  | 5171/7211 [21:35<07:13,  4.71it/s]

Gaps (ex-reports):  72%|███████▏  | 5172/7211 [21:35<07:08,  4.76it/s]

Gaps (ex-reports):  72%|███████▏  | 5173/7211 [21:35<07:06,  4.78it/s]

Gaps (ex-reports):  72%|███████▏  | 5174/7211 [21:35<07:08,  4.76it/s]

Gaps (ex-reports):  72%|███████▏  | 5175/7211 [21:35<07:06,  4.78it/s]

Gaps (ex-reports):  72%|███████▏  | 5176/7211 [21:36<06:55,  4.90it/s]

Gaps (ex-reports):  72%|███████▏  | 5177/7211 [21:36<06:54,  4.90it/s]

Gaps (ex-reports):  72%|███████▏  | 5178/7211 [21:36<06:52,  4.93it/s]

Gaps (ex-reports):  72%|███████▏  | 5179/7211 [21:36<06:54,  4.90it/s]

Gaps (ex-reports):  72%|███████▏  | 5180/7211 [21:36<06:49,  4.96it/s]

Gaps (ex-reports):  72%|███████▏  | 5181/7211 [21:37<06:56,  4.88it/s]

Gaps (ex-reports):  72%|███████▏  | 5182/7211 [21:37<06:59,  4.84it/s]

Gaps (ex-reports):  72%|███████▏  | 5183/7211 [21:37<06:59,  4.83it/s]

Gaps (ex-reports):  72%|███████▏  | 5184/7211 [21:37<07:04,  4.78it/s]

Gaps (ex-reports):  72%|███████▏  | 5185/7211 [21:37<07:02,  4.80it/s]

Gaps (ex-reports):  72%|███████▏  | 5186/7211 [21:38<07:05,  4.76it/s]

Gaps (ex-reports):  72%|███████▏  | 5187/7211 [21:38<07:03,  4.78it/s]

Gaps (ex-reports):  72%|███████▏  | 5188/7211 [21:38<06:58,  4.83it/s]

Gaps (ex-reports):  72%|███████▏  | 5189/7211 [21:38<07:00,  4.81it/s]

Gaps (ex-reports):  72%|███████▏  | 5190/7211 [21:38<06:57,  4.85it/s]

Gaps (ex-reports):  72%|███████▏  | 5191/7211 [21:39<06:56,  4.85it/s]

Gaps (ex-reports):  72%|███████▏  | 5192/7211 [21:39<06:52,  4.89it/s]

Gaps (ex-reports):  72%|███████▏  | 5193/7211 [21:39<06:52,  4.90it/s]

Gaps (ex-reports):  72%|███████▏  | 5194/7211 [21:39<06:47,  4.95it/s]

Gaps (ex-reports):  72%|███████▏  | 5195/7211 [21:39<06:50,  4.91it/s]

Gaps (ex-reports):  72%|███████▏  | 5196/7211 [21:40<06:55,  4.85it/s]

Gaps (ex-reports):  72%|███████▏  | 5197/7211 [21:40<06:50,  4.91it/s]

Gaps (ex-reports):  72%|███████▏  | 5198/7211 [21:40<06:56,  4.84it/s]

Gaps (ex-reports):  72%|███████▏  | 5199/7211 [21:40<07:00,  4.78it/s]

Gaps (ex-reports):  72%|███████▏  | 5200/7211 [21:41<06:57,  4.81it/s]

Gaps (ex-reports):  72%|███████▏  | 5201/7211 [21:41<06:55,  4.84it/s]

Gaps (ex-reports):  72%|███████▏  | 5202/7211 [21:41<06:53,  4.86it/s]

Gaps (ex-reports):  72%|███████▏  | 5203/7211 [21:41<06:51,  4.87it/s]

Gaps (ex-reports):  72%|███████▏  | 5204/7211 [21:41<06:54,  4.85it/s]

Gaps (ex-reports):  72%|███████▏  | 5205/7211 [21:42<06:49,  4.90it/s]

Gaps (ex-reports):  72%|███████▏  | 5206/7211 [21:42<06:41,  4.99it/s]

Gaps (ex-reports):  72%|███████▏  | 5207/7211 [21:42<06:36,  5.05it/s]

Gaps (ex-reports):  72%|███████▏  | 5208/7211 [21:42<06:43,  4.97it/s]

Gaps (ex-reports):  72%|███████▏  | 5209/7211 [21:42<06:46,  4.93it/s]

Gaps (ex-reports):  72%|███████▏  | 5210/7211 [21:43<06:44,  4.95it/s]

Gaps (ex-reports):  72%|███████▏  | 5211/7211 [21:43<06:45,  4.93it/s]

Gaps (ex-reports):  72%|███████▏  | 5212/7211 [21:43<06:47,  4.91it/s]

Gaps (ex-reports):  72%|███████▏  | 5213/7211 [21:43<06:53,  4.83it/s]

Gaps (ex-reports):  72%|███████▏  | 5214/7211 [21:43<07:01,  4.74it/s]

Gaps (ex-reports):  72%|███████▏  | 5215/7211 [21:44<07:03,  4.72it/s]

Gaps (ex-reports):  72%|███████▏  | 5216/7211 [21:44<06:59,  4.76it/s]

Gaps (ex-reports):  72%|███████▏  | 5217/7211 [21:44<06:51,  4.85it/s]

Gaps (ex-reports):  72%|███████▏  | 5218/7211 [21:44<06:45,  4.91it/s]

Gaps (ex-reports):  72%|███████▏  | 5219/7211 [21:44<06:46,  4.90it/s]

Gaps (ex-reports):  72%|███████▏  | 5220/7211 [21:45<06:49,  4.86it/s]

Gaps (ex-reports):  72%|███████▏  | 5221/7211 [21:45<06:48,  4.87it/s]

Gaps (ex-reports):  72%|███████▏  | 5222/7211 [21:45<06:41,  4.95it/s]

Gaps (ex-reports):  72%|███████▏  | 5223/7211 [21:45<06:45,  4.90it/s]

Gaps (ex-reports):  72%|███████▏  | 5224/7211 [21:45<06:53,  4.80it/s]

Gaps (ex-reports):  72%|███████▏  | 5225/7211 [21:46<06:48,  4.87it/s]

Gaps (ex-reports):  72%|███████▏  | 5226/7211 [21:46<06:53,  4.80it/s]

Gaps (ex-reports):  72%|███████▏  | 5227/7211 [21:46<06:49,  4.85it/s]

Gaps (ex-reports):  73%|███████▎  | 5228/7211 [21:46<06:53,  4.79it/s]

Gaps (ex-reports):  73%|███████▎  | 5229/7211 [21:47<06:56,  4.76it/s]

Gaps (ex-reports):  73%|███████▎  | 5230/7211 [21:47<06:54,  4.78it/s]

Gaps (ex-reports):  73%|███████▎  | 5231/7211 [21:47<06:46,  4.87it/s]

Gaps (ex-reports):  73%|███████▎  | 5232/7211 [21:47<06:44,  4.89it/s]

Gaps (ex-reports):  73%|███████▎  | 5233/7211 [21:47<06:42,  4.91it/s]

Gaps (ex-reports):  73%|███████▎  | 5234/7211 [21:48<06:47,  4.85it/s]

Gaps (ex-reports):  73%|███████▎  | 5235/7211 [21:48<06:44,  4.88it/s]

Gaps (ex-reports):  73%|███████▎  | 5236/7211 [21:48<06:36,  4.99it/s]

Gaps (ex-reports):  73%|███████▎  | 5237/7211 [21:48<06:36,  4.97it/s]

Gaps (ex-reports):  73%|███████▎  | 5238/7211 [21:48<06:35,  4.99it/s]

Gaps (ex-reports):  73%|███████▎  | 5239/7211 [21:49<06:43,  4.89it/s]

Gaps (ex-reports):  73%|███████▎  | 5240/7211 [21:49<06:50,  4.80it/s]

Gaps (ex-reports):  73%|███████▎  | 5241/7211 [21:49<06:40,  4.91it/s]

Gaps (ex-reports):  73%|███████▎  | 5242/7211 [21:49<06:37,  4.95it/s]

Gaps (ex-reports):  73%|███████▎  | 5243/7211 [21:49<06:40,  4.92it/s]

Gaps (ex-reports):  73%|███████▎  | 5244/7211 [21:50<06:44,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5245/7211 [21:50<06:45,  4.84it/s]

Gaps (ex-reports):  73%|███████▎  | 5246/7211 [21:50<06:54,  4.74it/s]

Gaps (ex-reports):  73%|███████▎  | 5247/7211 [21:50<06:58,  4.69it/s]

Gaps (ex-reports):  73%|███████▎  | 5248/7211 [21:50<06:53,  4.74it/s]

Gaps (ex-reports):  73%|███████▎  | 5249/7211 [21:51<06:52,  4.76it/s]

Gaps (ex-reports):  73%|███████▎  | 5250/7211 [21:51<06:52,  4.76it/s]

Gaps (ex-reports):  73%|███████▎  | 5251/7211 [21:51<06:43,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5252/7211 [21:51<06:50,  4.77it/s]

Gaps (ex-reports):  73%|███████▎  | 5253/7211 [21:51<06:48,  4.79it/s]

Gaps (ex-reports):  73%|███████▎  | 5254/7211 [21:52<06:44,  4.84it/s]

Gaps (ex-reports):  73%|███████▎  | 5255/7211 [21:52<06:34,  4.95it/s]

Gaps (ex-reports):  73%|███████▎  | 5256/7211 [21:52<06:30,  5.01it/s]

Gaps (ex-reports):  73%|███████▎  | 5257/7211 [21:52<06:38,  4.90it/s]

Gaps (ex-reports):  73%|███████▎  | 5258/7211 [21:52<06:36,  4.92it/s]

Gaps (ex-reports):  73%|███████▎  | 5259/7211 [21:53<06:38,  4.90it/s]

Gaps (ex-reports):  73%|███████▎  | 5260/7211 [21:53<06:45,  4.81it/s]

Gaps (ex-reports):  73%|███████▎  | 5261/7211 [21:53<06:41,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5262/7211 [21:53<06:39,  4.88it/s]

Gaps (ex-reports):  73%|███████▎  | 5263/7211 [21:53<06:42,  4.84it/s]

Gaps (ex-reports):  73%|███████▎  | 5264/7211 [21:54<06:44,  4.81it/s]

Gaps (ex-reports):  73%|███████▎  | 5265/7211 [21:54<06:43,  4.82it/s]

Gaps (ex-reports):  73%|███████▎  | 5266/7211 [21:54<06:40,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5267/7211 [21:54<06:40,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5268/7211 [21:55<06:44,  4.80it/s]

Gaps (ex-reports):  73%|███████▎  | 5269/7211 [21:55<06:45,  4.79it/s]

Gaps (ex-reports):  73%|███████▎  | 5270/7211 [21:55<06:45,  4.78it/s]

Gaps (ex-reports):  73%|███████▎  | 5271/7211 [21:55<06:45,  4.78it/s]

Gaps (ex-reports):  73%|███████▎  | 5272/7211 [21:55<06:47,  4.76it/s]

Gaps (ex-reports):  73%|███████▎  | 5273/7211 [21:56<06:53,  4.69it/s]

Gaps (ex-reports):  73%|███████▎  | 5274/7211 [21:56<06:48,  4.74it/s]

Gaps (ex-reports):  73%|███████▎  | 5275/7211 [21:56<07:56,  4.07it/s]

Gaps (ex-reports):  73%|███████▎  | 5276/7211 [21:56<07:43,  4.18it/s]

Gaps (ex-reports):  73%|███████▎  | 5277/7211 [21:57<07:25,  4.34it/s]

Gaps (ex-reports):  73%|███████▎  | 5278/7211 [21:57<07:25,  4.34it/s]

Gaps (ex-reports):  73%|███████▎  | 5279/7211 [21:57<07:04,  4.55it/s]

Gaps (ex-reports):  73%|███████▎  | 5280/7211 [21:57<07:04,  4.55it/s]

Gaps (ex-reports):  73%|███████▎  | 5281/7211 [21:57<07:11,  4.47it/s]

Gaps (ex-reports):  73%|███████▎  | 5282/7211 [21:58<07:01,  4.58it/s]

Gaps (ex-reports):  73%|███████▎  | 5283/7211 [21:58<06:55,  4.64it/s]

Gaps (ex-reports):  73%|███████▎  | 5284/7211 [21:58<06:40,  4.81it/s]

Gaps (ex-reports):  73%|███████▎  | 5285/7211 [21:58<06:36,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5286/7211 [21:58<06:34,  4.88it/s]

Gaps (ex-reports):  73%|███████▎  | 5287/7211 [21:59<06:35,  4.87it/s]

Gaps (ex-reports):  73%|███████▎  | 5288/7211 [21:59<06:33,  4.89it/s]

Gaps (ex-reports):  73%|███████▎  | 5289/7211 [21:59<06:31,  4.91it/s]

Gaps (ex-reports):  73%|███████▎  | 5290/7211 [21:59<06:28,  4.95it/s]

Gaps (ex-reports):  73%|███████▎  | 5291/7211 [21:59<06:22,  5.02it/s]

Gaps (ex-reports):  73%|███████▎  | 5292/7211 [22:00<06:24,  5.00it/s]

Gaps (ex-reports):  73%|███████▎  | 5293/7211 [22:00<06:27,  4.95it/s]

Gaps (ex-reports):  73%|███████▎  | 5294/7211 [22:00<06:30,  4.91it/s]

Gaps (ex-reports):  73%|███████▎  | 5295/7211 [22:00<06:29,  4.92it/s]

Gaps (ex-reports):  73%|███████▎  | 5296/7211 [22:00<06:38,  4.81it/s]

Gaps (ex-reports):  73%|███████▎  | 5297/7211 [22:01<06:34,  4.85it/s]

Gaps (ex-reports):  73%|███████▎  | 5298/7211 [22:01<06:40,  4.78it/s]

Gaps (ex-reports):  73%|███████▎  | 5299/7211 [22:01<06:29,  4.91it/s]

Gaps (ex-reports):  73%|███████▎  | 5300/7211 [22:01<06:37,  4.81it/s]

Gaps (ex-reports):  74%|███████▎  | 5301/7211 [22:02<06:30,  4.89it/s]

Gaps (ex-reports):  74%|███████▎  | 5302/7211 [22:02<06:24,  4.97it/s]

Gaps (ex-reports):  74%|███████▎  | 5303/7211 [22:02<06:19,  5.03it/s]

Gaps (ex-reports):  74%|███████▎  | 5304/7211 [22:02<06:15,  5.08it/s]

Gaps (ex-reports):  74%|███████▎  | 5305/7211 [22:02<06:23,  4.97it/s]

Gaps (ex-reports):  74%|███████▎  | 5306/7211 [22:03<06:23,  4.96it/s]

Gaps (ex-reports):  74%|███████▎  | 5307/7211 [22:03<06:22,  4.98it/s]

Gaps (ex-reports):  74%|███████▎  | 5308/7211 [22:03<06:23,  4.96it/s]

Gaps (ex-reports):  74%|███████▎  | 5309/7211 [22:03<06:21,  4.99it/s]

Gaps (ex-reports):  74%|███████▎  | 5310/7211 [22:03<06:21,  4.98it/s]

Gaps (ex-reports):  74%|███████▎  | 5311/7211 [22:03<06:17,  5.04it/s]

Gaps (ex-reports):  74%|███████▎  | 5312/7211 [22:04<06:27,  4.90it/s]

Gaps (ex-reports):  74%|███████▎  | 5313/7211 [22:04<06:31,  4.85it/s]

Gaps (ex-reports):  74%|███████▎  | 5314/7211 [22:04<06:28,  4.88it/s]

Gaps (ex-reports):  74%|███████▎  | 5315/7211 [22:04<06:33,  4.81it/s]

Gaps (ex-reports):  74%|███████▎  | 5316/7211 [22:05<06:28,  4.87it/s]

Gaps (ex-reports):  74%|███████▎  | 5317/7211 [22:05<06:29,  4.87it/s]

Gaps (ex-reports):  74%|███████▎  | 5318/7211 [22:05<06:29,  4.86it/s]

Gaps (ex-reports):  74%|███████▍  | 5319/7211 [22:05<06:42,  4.70it/s]

Gaps (ex-reports):  74%|███████▍  | 5320/7211 [22:05<06:40,  4.73it/s]

Gaps (ex-reports):  74%|███████▍  | 5321/7211 [22:06<06:37,  4.75it/s]

Gaps (ex-reports):  74%|███████▍  | 5322/7211 [22:06<06:37,  4.76it/s]

Gaps (ex-reports):  74%|███████▍  | 5323/7211 [22:06<06:26,  4.88it/s]

Gaps (ex-reports):  74%|███████▍  | 5324/7211 [22:06<06:26,  4.88it/s]

Gaps (ex-reports):  74%|███████▍  | 5325/7211 [22:06<06:20,  4.96it/s]

Gaps (ex-reports):  74%|███████▍  | 5326/7211 [22:07<06:23,  4.91it/s]

Gaps (ex-reports):  74%|███████▍  | 5327/7211 [22:07<07:04,  4.44it/s]

Gaps (ex-reports):  74%|███████▍  | 5328/7211 [22:07<06:54,  4.54it/s]

Gaps (ex-reports):  74%|███████▍  | 5329/7211 [22:07<06:46,  4.63it/s]

Gaps (ex-reports):  74%|███████▍  | 5330/7211 [22:07<06:33,  4.78it/s]

Gaps (ex-reports):  74%|███████▍  | 5331/7211 [22:08<06:30,  4.82it/s]

Gaps (ex-reports):  74%|███████▍  | 5332/7211 [22:08<06:21,  4.92it/s]

Gaps (ex-reports):  74%|███████▍  | 5333/7211 [22:08<06:14,  5.01it/s]

Gaps (ex-reports):  74%|███████▍  | 5334/7211 [22:08<06:13,  5.03it/s]

Gaps (ex-reports):  74%|███████▍  | 5335/7211 [22:08<06:15,  5.00it/s]

Gaps (ex-reports):  74%|███████▍  | 5336/7211 [22:09<06:09,  5.08it/s]

Gaps (ex-reports):  74%|███████▍  | 5337/7211 [22:09<06:17,  4.96it/s]

Gaps (ex-reports):  74%|███████▍  | 5338/7211 [22:09<06:20,  4.92it/s]

Gaps (ex-reports):  74%|███████▍  | 5339/7211 [22:09<06:21,  4.91it/s]

Gaps (ex-reports):  74%|███████▍  | 5340/7211 [22:09<06:13,  5.01it/s]

Gaps (ex-reports):  74%|███████▍  | 5341/7211 [22:10<06:12,  5.02it/s]

Gaps (ex-reports):  74%|███████▍  | 5342/7211 [22:10<06:08,  5.07it/s]

Gaps (ex-reports):  74%|███████▍  | 5343/7211 [22:10<06:05,  5.12it/s]

Gaps (ex-reports):  74%|███████▍  | 5344/7211 [22:10<06:08,  5.07it/s]

Gaps (ex-reports):  74%|███████▍  | 5345/7211 [22:10<06:17,  4.94it/s]

Gaps (ex-reports):  74%|███████▍  | 5346/7211 [22:11<06:19,  4.91it/s]

Gaps (ex-reports):  74%|███████▍  | 5347/7211 [22:11<06:20,  4.90it/s]

Gaps (ex-reports):  74%|███████▍  | 5348/7211 [22:11<06:33,  4.73it/s]

Gaps (ex-reports):  74%|███████▍  | 5349/7211 [22:11<06:34,  4.72it/s]

Gaps (ex-reports):  74%|███████▍  | 5350/7211 [22:12<06:26,  4.81it/s]

Gaps (ex-reports):  74%|███████▍  | 5351/7211 [22:12<06:17,  4.92it/s]

Gaps (ex-reports):  74%|███████▍  | 5352/7211 [22:12<06:13,  4.97it/s]

Gaps (ex-reports):  74%|███████▍  | 5353/7211 [22:12<06:17,  4.92it/s]

Gaps (ex-reports):  74%|███████▍  | 5354/7211 [22:12<06:18,  4.91it/s]

Gaps (ex-reports):  74%|███████▍  | 5355/7211 [22:13<06:11,  5.00it/s]

Gaps (ex-reports):  74%|███████▍  | 5356/7211 [22:13<06:14,  4.95it/s]

Gaps (ex-reports):  74%|███████▍  | 5357/7211 [22:13<06:25,  4.81it/s]

Gaps (ex-reports):  74%|███████▍  | 5358/7211 [22:13<06:19,  4.89it/s]

Gaps (ex-reports):  74%|███████▍  | 5359/7211 [22:13<06:10,  5.00it/s]

Gaps (ex-reports):  74%|███████▍  | 5360/7211 [22:23<1:34:42,  3.07s/it]

Gaps (ex-reports):  74%|███████▍  | 5361/7211 [22:23<1:08:10,  2.21s/it]

Gaps (ex-reports):  74%|███████▍  | 5362/7211 [22:24<49:27,  1.60s/it]

Gaps (ex-reports):  74%|███████▍  | 5363/7211 [22:24<36:31,  1.19s/it]

Gaps (ex-reports):  74%|███████▍  | 5364/7211 [22:24<27:22,  1.12it/s]

Gaps (ex-reports):  74%|███████▍  | 5365/7211 [22:24<20:56,  1.47it/s]

Gaps (ex-reports):  74%|███████▍  | 5366/7211 [22:24<16:31,  1.86it/s]

Gaps (ex-reports):  74%|███████▍  | 5367/7211 [22:25<13:26,  2.29it/s]

Gaps (ex-reports):  74%|███████▍  | 5368/7211 [22:25<11:21,  2.70it/s]

Gaps (ex-reports):  74%|███████▍  | 5369/7211 [22:25<09:52,  3.11it/s]

Gaps (ex-reports):  74%|███████▍  | 5370/7211 [22:25<08:47,  3.49it/s]

Gaps (ex-reports):  74%|███████▍  | 5371/7211 [22:25<07:56,  3.86it/s]

Gaps (ex-reports):  74%|███████▍  | 5372/7211 [22:26<07:29,  4.09it/s]

Gaps (ex-reports):  75%|███████▍  | 5373/7211 [22:26<07:08,  4.29it/s]

Gaps (ex-reports):  75%|███████▍  | 5374/7211 [22:26<06:45,  4.53it/s]

Gaps (ex-reports):  75%|███████▍  | 5375/7211 [22:26<06:28,  4.73it/s]

Gaps (ex-reports):  75%|███████▍  | 5376/7211 [22:26<06:25,  4.76it/s]

Gaps (ex-reports):  75%|███████▍  | 5377/7211 [22:27<06:20,  4.82it/s]

Gaps (ex-reports):  75%|███████▍  | 5378/7211 [22:27<06:17,  4.86it/s]

Gaps (ex-reports):  75%|███████▍  | 5379/7211 [22:27<06:05,  5.01it/s]

Gaps (ex-reports):  75%|███████▍  | 5380/7211 [22:27<06:04,  5.02it/s]

Gaps (ex-reports):  75%|███████▍  | 5381/7211 [22:27<05:59,  5.10it/s]

Gaps (ex-reports):  75%|███████▍  | 5382/7211 [22:28<06:00,  5.07it/s]

Gaps (ex-reports):  75%|███████▍  | 5383/7211 [22:28<06:07,  4.97it/s]

Gaps (ex-reports):  75%|███████▍  | 5384/7211 [22:28<06:10,  4.93it/s]

Gaps (ex-reports):  75%|███████▍  | 5385/7211 [22:28<06:09,  4.94it/s]

Gaps (ex-reports):  75%|███████▍  | 5386/7211 [22:28<06:06,  4.98it/s]

Gaps (ex-reports):  75%|███████▍  | 5387/7211 [22:29<06:12,  4.90it/s]

Gaps (ex-reports):  75%|███████▍  | 5388/7211 [22:29<06:06,  4.97it/s]

Gaps (ex-reports):  75%|███████▍  | 5389/7211 [22:29<06:13,  4.88it/s]

Gaps (ex-reports):  75%|███████▍  | 5390/7211 [22:29<06:09,  4.93it/s]

Gaps (ex-reports):  75%|███████▍  | 5391/7211 [22:29<06:08,  4.93it/s]

Gaps (ex-reports):  75%|███████▍  | 5392/7211 [22:30<06:03,  5.00it/s]

Gaps (ex-reports):  75%|███████▍  | 5393/7211 [22:30<06:06,  4.96it/s]

Gaps (ex-reports):  75%|███████▍  | 5394/7211 [22:30<06:00,  5.04it/s]

Gaps (ex-reports):  75%|███████▍  | 5395/7211 [22:30<06:20,  4.78it/s]

Gaps (ex-reports):  75%|███████▍  | 5396/7211 [22:30<06:21,  4.76it/s]

Gaps (ex-reports):  75%|███████▍  | 5397/7211 [22:31<06:16,  4.81it/s]

Gaps (ex-reports):  75%|███████▍  | 5398/7211 [22:31<06:10,  4.90it/s]

Gaps (ex-reports):  75%|███████▍  | 5399/7211 [22:31<06:08,  4.91it/s]

Gaps (ex-reports):  75%|███████▍  | 5400/7211 [22:31<06:08,  4.92it/s]

Gaps (ex-reports):  75%|███████▍  | 5401/7211 [22:31<06:11,  4.87it/s]

Gaps (ex-reports):  75%|███████▍  | 5402/7211 [22:32<06:07,  4.92it/s]

Gaps (ex-reports):  75%|███████▍  | 5403/7211 [22:32<06:00,  5.01it/s]

Gaps (ex-reports):  75%|███████▍  | 5404/7211 [22:32<06:04,  4.96it/s]

Gaps (ex-reports):  75%|███████▍  | 5405/7211 [22:32<06:10,  4.87it/s]

Gaps (ex-reports):  75%|███████▍  | 5406/7211 [22:32<06:04,  4.96it/s]

Gaps (ex-reports):  75%|███████▍  | 5407/7211 [22:33<06:09,  4.88it/s]

Gaps (ex-reports):  75%|███████▍  | 5408/7211 [22:33<06:12,  4.85it/s]

Gaps (ex-reports):  75%|███████▌  | 5409/7211 [22:33<06:12,  4.84it/s]

Gaps (ex-reports):  75%|███████▌  | 5410/7211 [22:33<06:07,  4.90it/s]

Gaps (ex-reports):  75%|███████▌  | 5411/7211 [22:33<06:10,  4.86it/s]

Gaps (ex-reports):  75%|███████▌  | 5412/7211 [22:34<06:03,  4.95it/s]

Gaps (ex-reports):  75%|███████▌  | 5413/7211 [22:34<06:14,  4.80it/s]

Gaps (ex-reports):  75%|███████▌  | 5414/7211 [22:34<06:14,  4.79it/s]

Gaps (ex-reports):  75%|███████▌  | 5415/7211 [22:34<06:08,  4.87it/s]

Gaps (ex-reports):  75%|███████▌  | 5416/7211 [22:34<06:07,  4.88it/s]

Gaps (ex-reports):  75%|███████▌  | 5417/7211 [22:35<06:04,  4.93it/s]

Gaps (ex-reports):  75%|███████▌  | 5418/7211 [22:35<06:08,  4.87it/s]

Gaps (ex-reports):  75%|███████▌  | 5419/7211 [22:35<06:09,  4.85it/s]

Gaps (ex-reports):  75%|███████▌  | 5420/7211 [22:35<06:07,  4.88it/s]

Gaps (ex-reports):  75%|███████▌  | 5421/7211 [22:35<06:04,  4.91it/s]

Gaps (ex-reports):  75%|███████▌  | 5422/7211 [22:36<06:10,  4.83it/s]

Gaps (ex-reports):  75%|███████▌  | 5423/7211 [22:36<06:19,  4.71it/s]

Gaps (ex-reports):  75%|███████▌  | 5424/7211 [22:36<06:16,  4.74it/s]

Gaps (ex-reports):  75%|███████▌  | 5425/7211 [22:36<06:19,  4.71it/s]

Gaps (ex-reports):  75%|███████▌  | 5426/7211 [22:37<06:14,  4.76it/s]

Gaps (ex-reports):  75%|███████▌  | 5427/7211 [22:37<06:15,  4.76it/s]

Gaps (ex-reports):  75%|███████▌  | 5428/7211 [22:37<06:07,  4.85it/s]

Gaps (ex-reports):  75%|███████▌  | 5429/7211 [22:37<06:09,  4.82it/s]

Gaps (ex-reports):  75%|███████▌  | 5430/7211 [22:37<06:01,  4.93it/s]

Gaps (ex-reports):  75%|███████▌  | 5431/7211 [22:38<06:03,  4.90it/s]

Gaps (ex-reports):  75%|███████▌  | 5432/7211 [22:38<05:57,  4.97it/s]

Gaps (ex-reports):  75%|███████▌  | 5433/7211 [22:38<06:03,  4.90it/s]

Gaps (ex-reports):  75%|███████▌  | 5434/7211 [22:38<06:03,  4.89it/s]

Gaps (ex-reports):  75%|███████▌  | 5435/7211 [22:38<05:56,  4.98it/s]

Gaps (ex-reports):  75%|███████▌  | 5436/7211 [22:39<06:05,  4.85it/s]

Gaps (ex-reports):  75%|███████▌  | 5437/7211 [22:39<06:07,  4.83it/s]

Gaps (ex-reports):  75%|███████▌  | 5438/7211 [22:39<05:57,  4.95it/s]

Gaps (ex-reports):  75%|███████▌  | 5439/7211 [22:39<06:04,  4.86it/s]

Gaps (ex-reports):  75%|███████▌  | 5440/7211 [22:39<06:02,  4.89it/s]

Gaps (ex-reports):  75%|███████▌  | 5441/7211 [22:40<05:56,  4.96it/s]

Gaps (ex-reports):  75%|███████▌  | 5442/7211 [22:40<05:51,  5.03it/s]

Gaps (ex-reports):  75%|███████▌  | 5443/7211 [22:40<05:51,  5.03it/s]

Gaps (ex-reports):  75%|███████▌  | 5444/7211 [22:40<05:58,  4.92it/s]

Gaps (ex-reports):  76%|███████▌  | 5445/7211 [22:40<05:56,  4.96it/s]

Gaps (ex-reports):  76%|███████▌  | 5446/7211 [22:41<05:59,  4.91it/s]

Gaps (ex-reports):  76%|███████▌  | 5447/7211 [22:41<05:52,  5.00it/s]

Gaps (ex-reports):  76%|███████▌  | 5448/7211 [22:41<05:56,  4.95it/s]

Gaps (ex-reports):  76%|███████▌  | 5449/7211 [22:41<05:53,  4.98it/s]

Gaps (ex-reports):  76%|███████▌  | 5450/7211 [22:41<05:47,  5.06it/s]

Gaps (ex-reports):  76%|███████▌  | 5451/7211 [22:42<05:55,  4.96it/s]

Gaps (ex-reports):  76%|███████▌  | 5452/7211 [22:42<05:59,  4.90it/s]

Gaps (ex-reports):  76%|███████▌  | 5453/7211 [22:42<05:55,  4.95it/s]

Gaps (ex-reports):  76%|███████▌  | 5454/7211 [22:42<05:51,  4.99it/s]

Gaps (ex-reports):  76%|███████▌  | 5455/7211 [22:42<05:52,  4.98it/s]

Gaps (ex-reports):  76%|███████▌  | 5456/7211 [22:43<05:57,  4.90it/s]

Gaps (ex-reports):  76%|███████▌  | 5457/7211 [22:43<06:05,  4.80it/s]

Gaps (ex-reports):  76%|███████▌  | 5458/7211 [22:43<05:58,  4.89it/s]

Gaps (ex-reports):  76%|███████▌  | 5459/7211 [22:43<05:52,  4.97it/s]

Gaps (ex-reports):  76%|███████▌  | 5460/7211 [22:43<05:47,  5.04it/s]

Gaps (ex-reports):  76%|███████▌  | 5461/7211 [22:44<05:52,  4.96it/s]

Gaps (ex-reports):  76%|███████▌  | 5462/7211 [22:44<05:53,  4.94it/s]

Gaps (ex-reports):  76%|███████▌  | 5463/7211 [22:44<05:46,  5.04it/s]

Gaps (ex-reports):  76%|███████▌  | 5464/7211 [22:44<05:47,  5.02it/s]

Gaps (ex-reports):  76%|███████▌  | 5465/7211 [22:44<05:48,  5.01it/s]

Gaps (ex-reports):  76%|███████▌  | 5466/7211 [22:45<05:43,  5.08it/s]

Gaps (ex-reports):  76%|███████▌  | 5467/7211 [22:45<05:49,  5.00it/s]

Gaps (ex-reports):  76%|███████▌  | 5468/7211 [22:45<05:46,  5.03it/s]

Gaps (ex-reports):  76%|███████▌  | 5469/7211 [22:45<05:41,  5.10it/s]

Gaps (ex-reports):  76%|███████▌  | 5470/7211 [22:45<05:39,  5.12it/s]

Gaps (ex-reports):  76%|███████▌  | 5471/7211 [22:46<05:38,  5.15it/s]

Gaps (ex-reports):  76%|███████▌  | 5472/7211 [22:46<05:56,  4.87it/s]

Gaps (ex-reports):  76%|███████▌  | 5473/7211 [22:46<05:53,  4.92it/s]

Gaps (ex-reports):  76%|███████▌  | 5474/7211 [22:46<05:50,  4.96it/s]

Gaps (ex-reports):  76%|███████▌  | 5475/7211 [22:46<05:50,  4.96it/s]

Gaps (ex-reports):  76%|███████▌  | 5476/7211 [22:47<05:47,  5.00it/s]

Gaps (ex-reports):  76%|███████▌  | 5477/7211 [22:47<05:56,  4.86it/s]

Gaps (ex-reports):  76%|███████▌  | 5478/7211 [22:47<06:26,  4.48it/s]

Gaps (ex-reports):  76%|███████▌  | 5479/7211 [22:47<06:15,  4.61it/s]

Gaps (ex-reports):  76%|███████▌  | 5480/7211 [22:48<06:09,  4.69it/s]

Gaps (ex-reports):  76%|███████▌  | 5481/7211 [22:48<06:06,  4.73it/s]

Gaps (ex-reports):  76%|███████▌  | 5482/7211 [22:48<05:56,  4.85it/s]

Gaps (ex-reports):  76%|███████▌  | 5483/7211 [22:48<05:56,  4.84it/s]

Gaps (ex-reports):  76%|███████▌  | 5484/7211 [22:48<05:50,  4.93it/s]

Gaps (ex-reports):  76%|███████▌  | 5485/7211 [22:49<05:45,  4.99it/s]

Gaps (ex-reports):  76%|███████▌  | 5486/7211 [22:49<05:49,  4.94it/s]

Gaps (ex-reports):  76%|███████▌  | 5487/7211 [22:49<05:50,  4.92it/s]

Gaps (ex-reports):  76%|███████▌  | 5488/7211 [22:49<05:49,  4.93it/s]

Gaps (ex-reports):  76%|███████▌  | 5489/7211 [22:49<05:49,  4.93it/s]

Gaps (ex-reports):  76%|███████▌  | 5490/7211 [22:50<06:03,  4.73it/s]

Gaps (ex-reports):  76%|███████▌  | 5491/7211 [22:52<26:09,  1.10it/s]

Gaps (ex-reports):  76%|███████▌  | 5492/7211 [22:52<20:02,  1.43it/s]

Gaps (ex-reports):  76%|███████▌  | 5493/7211 [22:53<15:45,  1.82it/s]

Gaps (ex-reports):  76%|███████▌  | 5494/7211 [22:53<12:44,  2.25it/s]

Gaps (ex-reports):  76%|███████▌  | 5495/7211 [22:53<10:43,  2.67it/s]

Gaps (ex-reports):  76%|███████▌  | 5496/7211 [22:53<10:43,  2.66it/s]

Gaps (ex-reports):  76%|███████▌  | 5497/7211 [22:53<09:12,  3.10it/s]

Gaps (ex-reports):  76%|███████▌  | 5498/7211 [22:54<13:40,  2.09it/s]

Gaps (ex-reports):  76%|███████▋  | 5499/7211 [22:55<11:31,  2.48it/s]

Gaps (ex-reports):  76%|███████▋  | 5500/7211 [22:55<09:52,  2.89it/s]

Gaps (ex-reports):  76%|███████▋  | 5501/7211 [22:55<08:33,  3.33it/s]

Gaps (ex-reports):  76%|███████▋  | 5502/7211 [22:55<07:43,  3.69it/s]

Gaps (ex-reports):  76%|███████▋  | 5503/7211 [22:55<07:02,  4.05it/s]

Gaps (ex-reports):  76%|███████▋  | 5504/7211 [22:56<06:40,  4.26it/s]

Gaps (ex-reports):  76%|███████▋  | 5505/7211 [22:56<06:21,  4.48it/s]

Gaps (ex-reports):  76%|███████▋  | 5506/7211 [22:56<06:10,  4.60it/s]

Gaps (ex-reports):  76%|███████▋  | 5507/7211 [22:56<06:04,  4.67it/s]

Gaps (ex-reports):  76%|███████▋  | 5508/7211 [22:56<05:52,  4.84it/s]

Gaps (ex-reports):  76%|███████▋  | 5509/7211 [22:57<05:45,  4.93it/s]

Gaps (ex-reports):  76%|███████▋  | 5510/7211 [22:57<05:46,  4.91it/s]

Gaps (ex-reports):  76%|███████▋  | 5511/7211 [22:57<05:54,  4.80it/s]

Gaps (ex-reports):  76%|███████▋  | 5512/7211 [22:57<05:49,  4.86it/s]

Gaps (ex-reports):  76%|███████▋  | 5513/7211 [22:57<05:41,  4.97it/s]

Gaps (ex-reports):  76%|███████▋  | 5514/7211 [22:58<05:37,  5.03it/s]

Gaps (ex-reports):  76%|███████▋  | 5515/7211 [22:58<05:33,  5.08it/s]

Gaps (ex-reports):  76%|███████▋  | 5516/7211 [22:58<05:41,  4.97it/s]

Gaps (ex-reports):  77%|███████▋  | 5517/7211 [22:58<05:46,  4.89it/s]

Gaps (ex-reports):  77%|███████▋  | 5518/7211 [22:58<05:43,  4.92it/s]

Gaps (ex-reports):  77%|███████▋  | 5519/7211 [22:59<05:44,  4.91it/s]

Gaps (ex-reports):  77%|███████▋  | 5520/7211 [22:59<05:55,  4.75it/s]

Gaps (ex-reports):  77%|███████▋  | 5521/7211 [22:59<05:52,  4.79it/s]

Gaps (ex-reports):  77%|███████▋  | 5522/7211 [22:59<05:43,  4.92it/s]

Gaps (ex-reports):  77%|███████▋  | 5523/7211 [22:59<05:45,  4.88it/s]

Gaps (ex-reports):  77%|███████▋  | 5524/7211 [23:00<05:43,  4.92it/s]

Gaps (ex-reports):  77%|███████▋  | 5525/7211 [23:00<05:53,  4.77it/s]

Gaps (ex-reports):  77%|███████▋  | 5526/7211 [23:00<05:49,  4.83it/s]

Gaps (ex-reports):  77%|███████▋  | 5527/7211 [23:00<05:51,  4.79it/s]

Gaps (ex-reports):  77%|███████▋  | 5528/7211 [23:00<05:54,  4.75it/s]

Gaps (ex-reports):  77%|███████▋  | 5529/7211 [23:01<05:47,  4.84it/s]

Gaps (ex-reports):  77%|███████▋  | 5530/7211 [23:01<05:40,  4.93it/s]

Gaps (ex-reports):  77%|███████▋  | 5531/7211 [23:01<05:44,  4.87it/s]

Gaps (ex-reports):  77%|███████▋  | 5532/7211 [23:01<05:44,  4.88it/s]

Gaps (ex-reports):  77%|███████▋  | 5533/7211 [23:01<05:37,  4.97it/s]

Gaps (ex-reports):  77%|███████▋  | 5534/7211 [23:02<05:32,  5.04it/s]

Gaps (ex-reports):  77%|███████▋  | 5535/7211 [23:02<05:30,  5.07it/s]

Gaps (ex-reports):  77%|███████▋  | 5536/7211 [23:02<05:35,  4.99it/s]

Gaps (ex-reports):  77%|███████▋  | 5537/7211 [23:02<05:27,  5.11it/s]

Gaps (ex-reports):  77%|███████▋  | 5538/7211 [23:02<05:32,  5.03it/s]

Gaps (ex-reports):  77%|███████▋  | 5539/7211 [23:03<05:31,  5.04it/s]

Gaps (ex-reports):  77%|███████▋  | 5540/7211 [23:03<05:36,  4.96it/s]

Gaps (ex-reports):  77%|███████▋  | 5541/7211 [23:03<05:36,  4.96it/s]

Gaps (ex-reports):  77%|███████▋  | 5542/7211 [23:03<05:34,  4.99it/s]

Gaps (ex-reports):  77%|███████▋  | 5543/7211 [23:03<05:36,  4.96it/s]

Gaps (ex-reports):  77%|███████▋  | 5544/7211 [23:04<05:32,  5.02it/s]

Gaps (ex-reports):  77%|███████▋  | 5545/7211 [23:04<05:33,  4.99it/s]

Gaps (ex-reports):  77%|███████▋  | 5546/7211 [23:04<05:40,  4.89it/s]

Gaps (ex-reports):  77%|███████▋  | 5547/7211 [23:04<05:39,  4.90it/s]

Gaps (ex-reports):  77%|███████▋  | 5548/7211 [23:04<05:35,  4.95it/s]

Gaps (ex-reports):  77%|███████▋  | 5549/7211 [23:05<05:36,  4.94it/s]

Gaps (ex-reports):  77%|███████▋  | 5550/7211 [23:05<05:35,  4.96it/s]

Gaps (ex-reports):  77%|███████▋  | 5551/7211 [23:05<05:40,  4.88it/s]

Gaps (ex-reports):  77%|███████▋  | 5552/7211 [23:05<05:40,  4.87it/s]

Gaps (ex-reports):  77%|███████▋  | 5553/7211 [23:06<05:36,  4.92it/s]

Gaps (ex-reports):  77%|███████▋  | 5554/7211 [23:06<05:30,  5.01it/s]

Gaps (ex-reports):  77%|███████▋  | 5555/7211 [23:06<05:42,  4.83it/s]

Gaps (ex-reports):  77%|███████▋  | 5556/7211 [23:06<05:34,  4.95it/s]

Gaps (ex-reports):  77%|███████▋  | 5557/7211 [23:06<05:38,  4.89it/s]

Gaps (ex-reports):  77%|███████▋  | 5558/7211 [23:07<05:32,  4.98it/s]

Gaps (ex-reports):  77%|███████▋  | 5559/7211 [23:07<05:26,  5.06it/s]

Gaps (ex-reports):  77%|███████▋  | 5560/7211 [23:07<05:27,  5.04it/s]

Gaps (ex-reports):  77%|███████▋  | 5561/7211 [23:07<05:28,  5.02it/s]

Gaps (ex-reports):  77%|███████▋  | 5562/7211 [23:07<05:25,  5.07it/s]

Gaps (ex-reports):  77%|███████▋  | 5563/7211 [23:07<05:22,  5.11it/s]

Gaps (ex-reports):  77%|███████▋  | 5564/7211 [23:08<05:18,  5.17it/s]

Gaps (ex-reports):  77%|███████▋  | 5565/7211 [23:08<05:21,  5.13it/s]

Gaps (ex-reports):  77%|███████▋  | 5566/7211 [23:08<05:24,  5.06it/s]

Gaps (ex-reports):  77%|███████▋  | 5567/7211 [23:08<05:24,  5.07it/s]

Gaps (ex-reports):  77%|███████▋  | 5568/7211 [23:08<05:28,  5.00it/s]

Gaps (ex-reports):  77%|███████▋  | 5569/7211 [23:09<05:23,  5.08it/s]

Gaps (ex-reports):  77%|███████▋  | 5570/7211 [23:09<05:22,  5.09it/s]

Gaps (ex-reports):  77%|███████▋  | 5571/7211 [23:09<05:22,  5.09it/s]

Gaps (ex-reports):  77%|███████▋  | 5572/7211 [23:09<05:29,  4.98it/s]

Gaps (ex-reports):  77%|███████▋  | 5573/7211 [23:09<05:30,  4.96it/s]

Gaps (ex-reports):  77%|███████▋  | 5574/7211 [23:10<05:29,  4.97it/s]

Gaps (ex-reports):  77%|███████▋  | 5575/7211 [23:10<05:25,  5.03it/s]

Gaps (ex-reports):  77%|███████▋  | 5576/7211 [23:10<05:23,  5.05it/s]

Gaps (ex-reports):  77%|███████▋  | 5577/7211 [23:10<05:24,  5.04it/s]

Gaps (ex-reports):  77%|███████▋  | 5578/7211 [23:10<05:32,  4.92it/s]

Gaps (ex-reports):  77%|███████▋  | 5579/7211 [23:11<05:25,  5.02it/s]

Gaps (ex-reports):  77%|███████▋  | 5580/7211 [23:11<05:23,  5.05it/s]

Gaps (ex-reports):  77%|███████▋  | 5581/7211 [23:11<05:21,  5.07it/s]

Gaps (ex-reports):  77%|███████▋  | 5582/7211 [23:11<05:27,  4.97it/s]

Gaps (ex-reports):  77%|███████▋  | 5583/7211 [23:11<05:28,  4.96it/s]

Gaps (ex-reports):  77%|███████▋  | 5584/7211 [23:12<05:34,  4.86it/s]

Gaps (ex-reports):  77%|███████▋  | 5585/7211 [23:13<14:42,  1.84it/s]

Gaps (ex-reports):  77%|███████▋  | 5586/7211 [23:13<11:53,  2.28it/s]

Gaps (ex-reports):  77%|███████▋  | 5587/7211 [23:13<09:53,  2.74it/s]

Gaps (ex-reports):  77%|███████▋  | 5588/7211 [23:14<08:29,  3.18it/s]

Gaps (ex-reports):  78%|███████▊  | 5589/7211 [23:14<07:45,  3.48it/s]

Gaps (ex-reports):  78%|███████▊  | 5590/7211 [23:14<07:08,  3.79it/s]

Gaps (ex-reports):  78%|███████▊  | 5591/7211 [23:14<06:37,  4.08it/s]

Gaps (ex-reports):  78%|███████▊  | 5592/7211 [23:14<06:13,  4.34it/s]

Gaps (ex-reports):  78%|███████▊  | 5593/7211 [23:15<06:05,  4.43it/s]

Gaps (ex-reports):  78%|███████▊  | 5594/7211 [23:15<05:53,  4.58it/s]

Gaps (ex-reports):  78%|███████▊  | 5595/7211 [23:15<05:43,  4.71it/s]

Gaps (ex-reports):  78%|███████▊  | 5596/7211 [23:15<05:41,  4.73it/s]

Gaps (ex-reports):  78%|███████▊  | 5597/7211 [23:15<05:37,  4.78it/s]

Gaps (ex-reports):  78%|███████▊  | 5598/7211 [23:16<05:29,  4.90it/s]

Gaps (ex-reports):  78%|███████▊  | 5599/7211 [23:16<05:29,  4.89it/s]

Gaps (ex-reports):  78%|███████▊  | 5600/7211 [23:16<05:34,  4.82it/s]

Gaps (ex-reports):  78%|███████▊  | 5601/7211 [23:16<05:38,  4.76it/s]

Gaps (ex-reports):  78%|███████▊  | 5602/7211 [23:16<05:32,  4.84it/s]

Gaps (ex-reports):  78%|███████▊  | 5603/7211 [23:17<05:32,  4.84it/s]

Gaps (ex-reports):  78%|███████▊  | 5604/7211 [23:17<05:31,  4.85it/s]

Gaps (ex-reports):  78%|███████▊  | 5605/7211 [23:17<05:31,  4.84it/s]

Gaps (ex-reports):  78%|███████▊  | 5606/7211 [23:17<05:30,  4.86it/s]

Gaps (ex-reports):  78%|███████▊  | 5607/7211 [23:18<05:31,  4.83it/s]

Gaps (ex-reports):  78%|███████▊  | 5608/7211 [23:18<05:39,  4.73it/s]

Gaps (ex-reports):  78%|███████▊  | 5609/7211 [23:18<05:38,  4.73it/s]

Gaps (ex-reports):  78%|███████▊  | 5610/7211 [23:18<05:30,  4.85it/s]

Gaps (ex-reports):  78%|███████▊  | 5611/7211 [23:19<07:19,  3.64it/s]

Gaps (ex-reports):  78%|███████▊  | 5612/7211 [23:19<06:41,  3.98it/s]

Gaps (ex-reports):  78%|███████▊  | 5613/7211 [23:19<06:16,  4.24it/s]

Gaps (ex-reports):  78%|███████▊  | 5614/7211 [23:19<05:59,  4.44it/s]

Gaps (ex-reports):  78%|███████▊  | 5615/7211 [23:19<05:45,  4.62it/s]

Gaps (ex-reports):  78%|███████▊  | 5616/7211 [23:20<05:50,  4.55it/s]

Gaps (ex-reports):  78%|███████▊  | 5617/7211 [23:20<05:40,  4.68it/s]

Gaps (ex-reports):  78%|███████▊  | 5618/7211 [23:20<05:33,  4.78it/s]

Gaps (ex-reports):  78%|███████▊  | 5619/7211 [23:20<05:25,  4.89it/s]

Gaps (ex-reports):  78%|███████▊  | 5620/7211 [23:20<05:25,  4.89it/s]

Gaps (ex-reports):  78%|███████▊  | 5621/7211 [23:21<05:32,  4.78it/s]

Gaps (ex-reports):  78%|███████▊  | 5622/7211 [23:21<05:37,  4.71it/s]

Gaps (ex-reports):  78%|███████▊  | 5623/7211 [23:21<05:33,  4.76it/s]

Gaps (ex-reports):  78%|███████▊  | 5624/7211 [23:21<05:29,  4.82it/s]

Gaps (ex-reports):  78%|███████▊  | 5625/7211 [23:21<05:25,  4.88it/s]

Gaps (ex-reports):  78%|███████▊  | 5626/7211 [23:22<05:26,  4.86it/s]

Gaps (ex-reports):  78%|███████▊  | 5627/7211 [23:22<05:35,  4.72it/s]

Gaps (ex-reports):  78%|███████▊  | 5628/7211 [23:22<05:24,  4.88it/s]

Gaps (ex-reports):  78%|███████▊  | 5629/7211 [23:22<05:17,  4.98it/s]

Gaps (ex-reports):  78%|███████▊  | 5630/7211 [23:22<05:14,  5.03it/s]

Gaps (ex-reports):  78%|███████▊  | 5631/7211 [23:23<05:12,  5.06it/s]

Gaps (ex-reports):  78%|███████▊  | 5632/7211 [23:23<05:15,  5.01it/s]

Gaps (ex-reports):  78%|███████▊  | 5633/7211 [23:23<05:19,  4.94it/s]

Gaps (ex-reports):  78%|███████▊  | 5634/7211 [23:23<05:14,  5.01it/s]

Gaps (ex-reports):  78%|███████▊  | 5635/7211 [23:24<05:44,  4.58it/s]

Gaps (ex-reports):  78%|███████▊  | 5636/7211 [23:24<05:37,  4.67it/s]

Gaps (ex-reports):  78%|███████▊  | 5637/7211 [23:24<05:35,  4.69it/s]

Gaps (ex-reports):  78%|███████▊  | 5638/7211 [23:44<2:43:28,  6.24s/it]

Gaps (ex-reports):  78%|███████▊  | 5639/7211 [23:44<1:55:53,  4.42s/it]

Gaps (ex-reports):  78%|███████▊  | 5640/7211 [23:45<1:22:41,  3.16s/it]

Gaps (ex-reports):  78%|███████▊  | 5641/7211 [23:45<59:32,  2.28s/it]

Gaps (ex-reports):  78%|███████▊  | 5642/7211 [23:45<43:15,  1.65s/it]

Gaps (ex-reports):  78%|███████▊  | 5643/7211 [23:45<31:51,  1.22s/it]

Gaps (ex-reports):  78%|███████▊  | 5644/7211 [23:45<23:50,  1.10it/s]

Gaps (ex-reports):  78%|███████▊  | 5645/7211 [23:46<18:14,  1.43it/s]

Gaps (ex-reports):  78%|███████▊  | 5646/7211 [23:46<14:27,  1.80it/s]

Gaps (ex-reports):  78%|███████▊  | 5647/7211 [23:46<11:44,  2.22it/s]

Gaps (ex-reports):  78%|███████▊  | 5648/7211 [23:46<09:45,  2.67it/s]

Gaps (ex-reports):  78%|███████▊  | 5649/7211 [23:46<08:21,  3.11it/s]

Gaps (ex-reports):  78%|███████▊  | 5650/7211 [23:47<07:26,  3.49it/s]

Gaps (ex-reports):  78%|███████▊  | 5651/7211 [23:47<06:46,  3.84it/s]

Gaps (ex-reports):  78%|███████▊  | 5652/7211 [23:47<06:26,  4.03it/s]

Gaps (ex-reports):  78%|███████▊  | 5653/7211 [23:47<06:03,  4.28it/s]

Gaps (ex-reports):  78%|███████▊  | 5654/7211 [23:47<05:46,  4.49it/s]

Gaps (ex-reports):  78%|███████▊  | 5655/7211 [23:48<05:36,  4.63it/s]

Gaps (ex-reports):  78%|███████▊  | 5656/7211 [23:48<05:32,  4.67it/s]

Gaps (ex-reports):  78%|███████▊  | 5657/7211 [23:48<05:30,  4.71it/s]

Gaps (ex-reports):  78%|███████▊  | 5658/7211 [23:48<05:28,  4.72it/s]

Gaps (ex-reports):  78%|███████▊  | 5659/7211 [23:49<05:21,  4.82it/s]

Gaps (ex-reports):  78%|███████▊  | 5660/7211 [23:49<05:24,  4.77it/s]

Gaps (ex-reports):  79%|███████▊  | 5661/7211 [23:49<05:26,  4.74it/s]

Gaps (ex-reports):  79%|███████▊  | 5662/7211 [23:49<05:24,  4.78it/s]

Gaps (ex-reports):  79%|███████▊  | 5663/7211 [23:49<05:24,  4.77it/s]

Gaps (ex-reports):  79%|███████▊  | 5664/7211 [23:50<05:17,  4.87it/s]

Gaps (ex-reports):  79%|███████▊  | 5665/7211 [23:50<05:11,  4.97it/s]

Gaps (ex-reports):  79%|███████▊  | 5666/7211 [23:50<05:15,  4.90it/s]

Gaps (ex-reports):  79%|███████▊  | 5667/7211 [23:50<05:14,  4.91it/s]

Gaps (ex-reports):  79%|███████▊  | 5668/7211 [23:50<05:14,  4.90it/s]

Gaps (ex-reports):  79%|███████▊  | 5669/7211 [23:51<05:10,  4.96it/s]

Gaps (ex-reports):  79%|███████▊  | 5670/7211 [23:51<05:12,  4.93it/s]

Gaps (ex-reports):  79%|███████▊  | 5671/7211 [23:51<05:12,  4.92it/s]

Gaps (ex-reports):  79%|███████▊  | 5672/7211 [23:51<05:16,  4.87it/s]

Gaps (ex-reports):  79%|███████▊  | 5673/7211 [23:51<05:21,  4.79it/s]

Gaps (ex-reports):  79%|███████▊  | 5674/7211 [23:52<05:12,  4.92it/s]

Gaps (ex-reports):  79%|███████▊  | 5675/7211 [23:52<05:06,  5.01it/s]

Gaps (ex-reports):  79%|███████▊  | 5676/7211 [23:52<05:15,  4.86it/s]

Gaps (ex-reports):  79%|███████▊  | 5677/7211 [23:52<05:07,  4.98it/s]

Gaps (ex-reports):  79%|███████▊  | 5678/7211 [23:52<05:10,  4.94it/s]

Gaps (ex-reports):  79%|███████▉  | 5679/7211 [23:53<05:12,  4.90it/s]

Gaps (ex-reports):  79%|███████▉  | 5680/7211 [23:53<05:13,  4.88it/s]

Gaps (ex-reports):  79%|███████▉  | 5681/7211 [23:53<05:12,  4.90it/s]

Gaps (ex-reports):  79%|███████▉  | 5682/7211 [23:53<05:10,  4.92it/s]

Gaps (ex-reports):  79%|███████▉  | 5683/7211 [23:53<05:09,  4.94it/s]

Gaps (ex-reports):  79%|███████▉  | 5684/7211 [23:54<05:03,  5.03it/s]

Gaps (ex-reports):  79%|███████▉  | 5685/7211 [23:54<04:59,  5.09it/s]

Gaps (ex-reports):  79%|███████▉  | 5686/7211 [23:54<05:05,  4.99it/s]

Gaps (ex-reports):  79%|███████▉  | 5687/7211 [23:54<05:09,  4.92it/s]

Gaps (ex-reports):  79%|███████▉  | 5688/7211 [23:54<05:09,  4.92it/s]

Gaps (ex-reports):  79%|███████▉  | 5689/7211 [23:55<05:05,  4.99it/s]

Gaps (ex-reports):  79%|███████▉  | 5690/7211 [23:55<05:01,  5.05it/s]

Gaps (ex-reports):  79%|███████▉  | 5691/7211 [23:55<04:56,  5.13it/s]

Gaps (ex-reports):  79%|███████▉  | 5692/7211 [23:55<04:56,  5.13it/s]

Gaps (ex-reports):  79%|███████▉  | 5693/7211 [23:55<05:01,  5.03it/s]

Gaps (ex-reports):  79%|███████▉  | 5694/7211 [23:56<04:59,  5.07it/s]

Gaps (ex-reports):  79%|███████▉  | 5695/7211 [23:56<04:56,  5.11it/s]

Gaps (ex-reports):  79%|███████▉  | 5696/7211 [23:56<04:54,  5.14it/s]

Gaps (ex-reports):  79%|███████▉  | 5697/7211 [23:56<05:01,  5.02it/s]

Gaps (ex-reports):  79%|███████▉  | 5698/7211 [23:56<04:57,  5.09it/s]

Gaps (ex-reports):  79%|███████▉  | 5699/7211 [23:57<04:55,  5.12it/s]

Gaps (ex-reports):  79%|███████▉  | 5700/7211 [23:57<04:53,  5.15it/s]

Gaps (ex-reports):  79%|███████▉  | 5701/7211 [23:57<04:53,  5.14it/s]

Gaps (ex-reports):  79%|███████▉  | 5702/7211 [23:57<04:57,  5.07it/s]

Gaps (ex-reports):  79%|███████▉  | 5703/7211 [23:57<05:03,  4.97it/s]

Gaps (ex-reports):  79%|███████▉  | 5704/7211 [23:58<04:57,  5.07it/s]

Gaps (ex-reports):  79%|███████▉  | 5705/7211 [23:58<04:57,  5.06it/s]

Gaps (ex-reports):  79%|███████▉  | 5706/7211 [23:58<05:00,  5.01it/s]

Gaps (ex-reports):  79%|███████▉  | 5707/7211 [23:58<04:56,  5.07it/s]

Gaps (ex-reports):  79%|███████▉  | 5708/7211 [23:58<04:55,  5.08it/s]

Gaps (ex-reports):  79%|███████▉  | 5709/7211 [23:59<05:00,  4.99it/s]

Gaps (ex-reports):  79%|███████▉  | 5710/7211 [23:59<05:03,  4.95it/s]

Gaps (ex-reports):  79%|███████▉  | 5711/7211 [23:59<05:06,  4.89it/s]

Gaps (ex-reports):  79%|███████▉  | 5712/7211 [23:59<05:06,  4.90it/s]

Gaps (ex-reports):  79%|███████▉  | 5713/7211 [23:59<05:08,  4.85it/s]

Gaps (ex-reports):  79%|███████▉  | 5714/7211 [24:00<05:06,  4.88it/s]

Gaps (ex-reports):  79%|███████▉  | 5715/7211 [24:00<05:02,  4.95it/s]

Gaps (ex-reports):  79%|███████▉  | 5716/7211 [24:00<05:06,  4.87it/s]

Gaps (ex-reports):  79%|███████▉  | 5717/7211 [24:01<09:43,  2.56it/s]

Gaps (ex-reports):  79%|███████▉  | 5718/7211 [24:01<08:16,  3.01it/s]

Gaps (ex-reports):  79%|███████▉  | 5719/7211 [24:01<07:23,  3.37it/s]

Gaps (ex-reports):  79%|███████▉  | 5720/7211 [24:01<06:39,  3.73it/s]

Gaps (ex-reports):  79%|███████▉  | 5721/7211 [24:02<06:06,  4.06it/s]

Gaps (ex-reports):  79%|███████▉  | 5722/7211 [24:02<05:42,  4.35it/s]

Gaps (ex-reports):  79%|███████▉  | 5723/7211 [24:02<05:23,  4.60it/s]

Gaps (ex-reports):  79%|███████▉  | 5724/7211 [24:02<05:19,  4.66it/s]

Gaps (ex-reports):  79%|███████▉  | 5725/7211 [24:02<05:09,  4.80it/s]

Gaps (ex-reports):  79%|███████▉  | 5726/7211 [24:03<06:56,  3.56it/s]

Gaps (ex-reports):  79%|███████▉  | 5727/7211 [24:03<06:16,  3.94it/s]

Gaps (ex-reports):  79%|███████▉  | 5728/7211 [24:03<05:46,  4.29it/s]

Gaps (ex-reports):  79%|███████▉  | 5729/7211 [24:03<05:30,  4.49it/s]

Gaps (ex-reports):  79%|███████▉  | 5730/7211 [24:04<05:16,  4.68it/s]

Gaps (ex-reports):  79%|███████▉  | 5731/7211 [24:04<05:17,  4.66it/s]

Gaps (ex-reports):  79%|███████▉  | 5732/7211 [24:04<05:10,  4.76it/s]

Gaps (ex-reports):  80%|███████▉  | 5733/7211 [24:04<05:00,  4.92it/s]

Gaps (ex-reports):  80%|███████▉  | 5734/7211 [24:04<04:57,  4.96it/s]

Gaps (ex-reports):  80%|███████▉  | 5735/7211 [24:05<04:52,  5.05it/s]

Gaps (ex-reports):  80%|███████▉  | 5736/7211 [24:05<04:47,  5.13it/s]

Gaps (ex-reports):  80%|███████▉  | 5737/7211 [24:05<04:49,  5.10it/s]

Gaps (ex-reports):  80%|███████▉  | 5738/7211 [24:05<04:57,  4.95it/s]

Gaps (ex-reports):  80%|███████▉  | 5739/7211 [24:05<04:56,  4.96it/s]

Gaps (ex-reports):  80%|███████▉  | 5740/7211 [24:06<04:52,  5.03it/s]

Gaps (ex-reports):  80%|███████▉  | 5741/7211 [24:06<04:59,  4.91it/s]

Gaps (ex-reports):  80%|███████▉  | 5742/7211 [24:09<30:29,  1.25s/it]

Gaps (ex-reports):  80%|███████▉  | 5743/7211 [24:10<22:53,  1.07it/s]

Gaps (ex-reports):  80%|███████▉  | 5744/7211 [24:10<17:32,  1.39it/s]

Gaps (ex-reports):  80%|███████▉  | 5745/7211 [24:10<14:13,  1.72it/s]

Gaps (ex-reports):  80%|███████▉  | 5746/7211 [24:10<11:19,  2.15it/s]

Gaps (ex-reports):  80%|███████▉  | 5747/7211 [24:11<09:21,  2.61it/s]

Gaps (ex-reports):  80%|███████▉  | 5748/7211 [24:11<07:58,  3.05it/s]

Gaps (ex-reports):  80%|███████▉  | 5749/7211 [24:11<07:05,  3.43it/s]

Gaps (ex-reports):  80%|███████▉  | 5750/7211 [24:11<06:20,  3.84it/s]

Gaps (ex-reports):  80%|███████▉  | 5751/7211 [24:11<05:56,  4.10it/s]

Gaps (ex-reports):  80%|███████▉  | 5752/7211 [24:12<05:32,  4.38it/s]

Gaps (ex-reports):  80%|███████▉  | 5753/7211 [24:12<05:24,  4.50it/s]

Gaps (ex-reports):  80%|███████▉  | 5754/7211 [24:12<05:09,  4.71it/s]

Gaps (ex-reports):  80%|███████▉  | 5755/7211 [24:12<05:01,  4.82it/s]

Gaps (ex-reports):  80%|███████▉  | 5756/7211 [24:12<05:05,  4.77it/s]

Gaps (ex-reports):  80%|███████▉  | 5757/7211 [24:13<05:02,  4.81it/s]

Gaps (ex-reports):  80%|███████▉  | 5758/7211 [24:13<05:06,  4.73it/s]

Gaps (ex-reports):  80%|███████▉  | 5759/7211 [24:13<05:00,  4.83it/s]

Gaps (ex-reports):  80%|███████▉  | 5760/7211 [24:13<04:54,  4.93it/s]

Gaps (ex-reports):  80%|███████▉  | 5761/7211 [24:13<04:58,  4.86it/s]

Gaps (ex-reports):  80%|███████▉  | 5762/7211 [24:14<04:55,  4.90it/s]

Gaps (ex-reports):  80%|███████▉  | 5763/7211 [24:17<30:56,  1.28s/it]

Gaps (ex-reports):  80%|███████▉  | 5764/7211 [24:18<23:17,  1.04it/s]

Gaps (ex-reports):  80%|███████▉  | 5765/7211 [24:21<43:16,  1.80s/it]

Gaps (ex-reports):  80%|███████▉  | 5766/7211 [24:22<31:43,  1.32s/it]

Gaps (ex-reports):  80%|███████▉  | 5767/7211 [24:22<23:35,  1.02it/s]

Gaps (ex-reports):  80%|███████▉  | 5768/7211 [24:22<17:56,  1.34it/s]

Gaps (ex-reports):  80%|████████  | 5769/7211 [24:22<13:54,  1.73it/s]

Gaps (ex-reports):  80%|████████  | 5770/7211 [24:22<11:14,  2.14it/s]

Gaps (ex-reports):  80%|████████  | 5771/7211 [24:23<09:15,  2.59it/s]

Gaps (ex-reports):  80%|████████  | 5772/7211 [24:23<07:51,  3.05it/s]

Gaps (ex-reports):  80%|████████  | 5773/7211 [24:23<06:54,  3.47it/s]

Gaps (ex-reports):  80%|████████  | 5774/7211 [24:23<06:19,  3.79it/s]

Gaps (ex-reports):  80%|████████  | 5775/7211 [24:23<05:56,  4.03it/s]

Gaps (ex-reports):  80%|████████  | 5776/7211 [24:24<05:38,  4.24it/s]

Gaps (ex-reports):  80%|████████  | 5777/7211 [24:24<05:23,  4.43it/s]

Gaps (ex-reports):  80%|████████  | 5778/7211 [24:24<05:21,  4.45it/s]

Gaps (ex-reports):  80%|████████  | 5779/7211 [24:24<05:11,  4.60it/s]

Gaps (ex-reports):  80%|████████  | 5780/7211 [24:24<05:07,  4.66it/s]

Gaps (ex-reports):  80%|████████  | 5781/7211 [24:25<05:02,  4.72it/s]

Gaps (ex-reports):  80%|████████  | 5782/7211 [24:25<04:57,  4.81it/s]

Gaps (ex-reports):  80%|████████  | 5783/7211 [24:25<04:53,  4.87it/s]

Gaps (ex-reports):  80%|████████  | 5784/7211 [24:25<04:56,  4.81it/s]

Gaps (ex-reports):  80%|████████  | 5785/7211 [24:25<04:55,  4.83it/s]

Gaps (ex-reports):  80%|████████  | 5786/7211 [24:26<04:49,  4.92it/s]

Gaps (ex-reports):  80%|████████  | 5787/7211 [24:26<04:43,  5.02it/s]

Gaps (ex-reports):  80%|████████  | 5788/7211 [24:26<04:42,  5.03it/s]

Gaps (ex-reports):  80%|████████  | 5789/7211 [24:26<04:50,  4.89it/s]

Gaps (ex-reports):  80%|████████  | 5790/7211 [24:26<05:01,  4.71it/s]

Gaps (ex-reports):  80%|████████  | 5791/7211 [24:27<05:31,  4.29it/s]

Gaps (ex-reports):  80%|████████  | 5792/7211 [24:27<05:40,  4.16it/s]

Gaps (ex-reports):  80%|████████  | 5793/7211 [24:27<05:43,  4.13it/s]

Gaps (ex-reports):  80%|████████  | 5794/7211 [24:27<05:27,  4.33it/s]

Gaps (ex-reports):  80%|████████  | 5795/7211 [24:28<05:17,  4.46it/s]

Gaps (ex-reports):  80%|████████  | 5796/7211 [24:28<05:05,  4.63it/s]

Gaps (ex-reports):  80%|████████  | 5797/7211 [24:28<04:59,  4.73it/s]

Gaps (ex-reports):  80%|████████  | 5798/7211 [24:28<04:55,  4.78it/s]

Gaps (ex-reports):  80%|████████  | 5799/7211 [24:28<04:50,  4.86it/s]

Gaps (ex-reports):  80%|████████  | 5800/7211 [24:29<04:45,  4.95it/s]

Gaps (ex-reports):  80%|████████  | 5801/7211 [24:29<04:51,  4.83it/s]

Gaps (ex-reports):  80%|████████  | 5802/7211 [24:29<04:50,  4.85it/s]

Gaps (ex-reports):  80%|████████  | 5803/7211 [24:29<04:45,  4.93it/s]

Gaps (ex-reports):  80%|████████  | 5804/7211 [24:29<04:41,  5.00it/s]

Gaps (ex-reports):  81%|████████  | 5805/7211 [24:30<04:44,  4.94it/s]

Gaps (ex-reports):  81%|████████  | 5806/7211 [24:30<04:43,  4.96it/s]

Gaps (ex-reports):  81%|████████  | 5807/7211 [24:32<15:01,  1.56it/s]

Gaps (ex-reports):  81%|████████  | 5808/7211 [24:32<12:04,  1.94it/s]

Gaps (ex-reports):  81%|████████  | 5809/7211 [24:32<09:49,  2.38it/s]

Gaps (ex-reports):  81%|████████  | 5810/7211 [24:32<08:11,  2.85it/s]

Gaps (ex-reports):  81%|████████  | 5811/7211 [24:32<07:13,  3.23it/s]

Gaps (ex-reports):  81%|████████  | 5812/7211 [24:33<06:30,  3.58it/s]

Gaps (ex-reports):  81%|████████  | 5813/7211 [24:33<05:55,  3.93it/s]

Gaps (ex-reports):  81%|████████  | 5814/7211 [24:33<05:35,  4.17it/s]

Gaps (ex-reports):  81%|████████  | 5815/7211 [24:33<05:19,  4.37it/s]

Gaps (ex-reports):  81%|████████  | 5816/7211 [24:33<05:02,  4.61it/s]

Gaps (ex-reports):  81%|████████  | 5817/7211 [24:34<05:01,  4.63it/s]

Gaps (ex-reports):  81%|████████  | 5818/7211 [24:34<04:58,  4.66it/s]

Gaps (ex-reports):  81%|████████  | 5819/7211 [24:34<04:52,  4.75it/s]

Gaps (ex-reports):  81%|████████  | 5820/7211 [24:34<04:44,  4.90it/s]

Gaps (ex-reports):  81%|████████  | 5821/7211 [24:34<04:41,  4.94it/s]

Gaps (ex-reports):  81%|████████  | 5822/7211 [24:35<04:41,  4.94it/s]

Gaps (ex-reports):  81%|████████  | 5823/7211 [24:35<04:37,  4.99it/s]

Gaps (ex-reports):  81%|████████  | 5824/7211 [24:35<04:34,  5.06it/s]

Gaps (ex-reports):  81%|████████  | 5825/7211 [24:35<04:44,  4.86it/s]

Gaps (ex-reports):  81%|████████  | 5826/7211 [24:35<04:42,  4.90it/s]

Gaps (ex-reports):  81%|████████  | 5827/7211 [24:36<04:40,  4.93it/s]

Gaps (ex-reports):  81%|████████  | 5828/7211 [24:36<04:42,  4.89it/s]

Gaps (ex-reports):  81%|████████  | 5829/7211 [24:36<04:43,  4.87it/s]

Gaps (ex-reports):  81%|████████  | 5830/7211 [24:36<04:37,  4.97it/s]

Gaps (ex-reports):  81%|████████  | 5831/7211 [24:36<04:34,  5.04it/s]

Gaps (ex-reports):  81%|████████  | 5832/7211 [24:37<04:36,  4.99it/s]

Gaps (ex-reports):  81%|████████  | 5833/7211 [24:37<04:39,  4.93it/s]

Gaps (ex-reports):  81%|████████  | 5834/7211 [24:37<04:45,  4.83it/s]

Gaps (ex-reports):  81%|████████  | 5835/7211 [24:37<04:45,  4.83it/s]

Gaps (ex-reports):  81%|████████  | 5836/7211 [24:37<04:44,  4.84it/s]

Gaps (ex-reports):  81%|████████  | 5837/7211 [24:38<04:41,  4.87it/s]

Gaps (ex-reports):  81%|████████  | 5838/7211 [24:38<04:48,  4.76it/s]

Gaps (ex-reports):  81%|████████  | 5839/7211 [24:38<04:45,  4.81it/s]

Gaps (ex-reports):  81%|████████  | 5840/7211 [24:38<04:43,  4.84it/s]

Gaps (ex-reports):  81%|████████  | 5841/7211 [24:38<04:37,  4.94it/s]

Gaps (ex-reports):  81%|████████  | 5842/7211 [24:39<04:38,  4.91it/s]

Gaps (ex-reports):  81%|████████  | 5843/7211 [24:39<04:43,  4.83it/s]

Gaps (ex-reports):  81%|████████  | 5844/7211 [24:39<04:39,  4.89it/s]

Gaps (ex-reports):  81%|████████  | 5845/7211 [24:39<04:40,  4.86it/s]

Gaps (ex-reports):  81%|████████  | 5846/7211 [24:39<04:38,  4.89it/s]

Gaps (ex-reports):  81%|████████  | 5847/7211 [24:40<04:38,  4.91it/s]

Gaps (ex-reports):  81%|████████  | 5848/7211 [24:40<04:39,  4.87it/s]

Gaps (ex-reports):  81%|████████  | 5849/7211 [24:40<04:43,  4.80it/s]

Gaps (ex-reports):  81%|████████  | 5850/7211 [24:40<04:39,  4.87it/s]

Gaps (ex-reports):  81%|████████  | 5851/7211 [24:40<04:41,  4.83it/s]

Gaps (ex-reports):  81%|████████  | 5852/7211 [24:41<04:41,  4.83it/s]

Gaps (ex-reports):  81%|████████  | 5853/7211 [24:41<04:35,  4.93it/s]

Gaps (ex-reports):  81%|████████  | 5854/7211 [24:41<04:29,  5.04it/s]

Gaps (ex-reports):  81%|████████  | 5855/7211 [24:45<29:13,  1.29s/it]

Gaps (ex-reports):  81%|████████  | 5856/7211 [24:45<21:48,  1.04it/s]

Gaps (ex-reports):  81%|████████  | 5857/7211 [24:45<16:40,  1.35it/s]

Gaps (ex-reports):  81%|████████  | 5858/7211 [24:46<13:16,  1.70it/s]

Gaps (ex-reports):  81%|████████▏ | 5859/7211 [24:46<10:41,  2.11it/s]

Gaps (ex-reports):  81%|████████▏ | 5860/7211 [24:46<08:46,  2.57it/s]

Gaps (ex-reports):  81%|████████▏ | 5861/7211 [24:46<07:24,  3.04it/s]

Gaps (ex-reports):  81%|████████▏ | 5862/7211 [24:46<06:31,  3.44it/s]

Gaps (ex-reports):  81%|████████▏ | 5863/7211 [24:47<06:00,  3.74it/s]

Gaps (ex-reports):  81%|████████▏ | 5864/7211 [24:47<05:32,  4.06it/s]

Gaps (ex-reports):  81%|████████▏ | 5865/7211 [24:47<05:20,  4.21it/s]

Gaps (ex-reports):  81%|████████▏ | 5866/7211 [24:47<05:06,  4.39it/s]

Gaps (ex-reports):  81%|████████▏ | 5867/7211 [24:47<04:56,  4.54it/s]

Gaps (ex-reports):  81%|████████▏ | 5868/7211 [24:48<04:53,  4.58it/s]

Gaps (ex-reports):  81%|████████▏ | 5869/7211 [24:48<04:53,  4.58it/s]

Gaps (ex-reports):  81%|████████▏ | 5870/7211 [24:48<04:49,  4.63it/s]

Gaps (ex-reports):  81%|████████▏ | 5871/7211 [24:48<04:44,  4.71it/s]

Gaps (ex-reports):  81%|████████▏ | 5872/7211 [24:48<04:35,  4.87it/s]

Gaps (ex-reports):  81%|████████▏ | 5873/7211 [24:49<04:34,  4.88it/s]

Gaps (ex-reports):  81%|████████▏ | 5874/7211 [24:49<04:32,  4.91it/s]

Gaps (ex-reports):  81%|████████▏ | 5875/7211 [24:49<04:32,  4.90it/s]

Gaps (ex-reports):  81%|████████▏ | 5876/7211 [24:49<04:37,  4.81it/s]

Gaps (ex-reports):  82%|████████▏ | 5877/7211 [24:49<04:35,  4.83it/s]

Gaps (ex-reports):  82%|████████▏ | 5878/7211 [24:50<04:33,  4.87it/s]

Gaps (ex-reports):  82%|████████▏ | 5879/7211 [24:50<04:28,  4.96it/s]

Gaps (ex-reports):  82%|████████▏ | 5880/7211 [24:50<04:25,  5.02it/s]

Gaps (ex-reports):  82%|████████▏ | 5881/7211 [24:50<04:26,  4.99it/s]

Gaps (ex-reports):  82%|████████▏ | 5882/7211 [24:50<04:22,  5.06it/s]

Gaps (ex-reports):  82%|████████▏ | 5883/7211 [24:51<04:20,  5.10it/s]

Gaps (ex-reports):  82%|████████▏ | 5884/7211 [24:51<04:23,  5.04it/s]

Gaps (ex-reports):  82%|████████▏ | 5885/7211 [24:51<04:27,  4.95it/s]

Gaps (ex-reports):  82%|████████▏ | 5886/7211 [24:51<04:24,  5.00it/s]

Gaps (ex-reports):  82%|████████▏ | 5887/7211 [24:52<07:23,  2.99it/s]

Gaps (ex-reports):  82%|████████▏ | 5888/7211 [24:52<06:31,  3.38it/s]

Gaps (ex-reports):  82%|████████▏ | 5889/7211 [24:52<05:54,  3.73it/s]

Gaps (ex-reports):  82%|████████▏ | 5890/7211 [24:53<05:25,  4.06it/s]

Gaps (ex-reports):  82%|████████▏ | 5891/7211 [24:53<05:08,  4.27it/s]

Gaps (ex-reports):  82%|████████▏ | 5892/7211 [24:53<05:06,  4.30it/s]

Gaps (ex-reports):  82%|████████▏ | 5893/7211 [24:53<04:57,  4.43it/s]

Gaps (ex-reports):  82%|████████▏ | 5894/7211 [24:53<04:46,  4.59it/s]

Gaps (ex-reports):  82%|████████▏ | 5895/7211 [24:54<05:15,  4.18it/s]

Gaps (ex-reports):  82%|████████▏ | 5896/7211 [24:54<04:56,  4.43it/s]

Gaps (ex-reports):  82%|████████▏ | 5897/7211 [24:54<04:48,  4.56it/s]

Gaps (ex-reports):  82%|████████▏ | 5898/7211 [24:54<04:43,  4.63it/s]

Gaps (ex-reports):  82%|████████▏ | 5899/7211 [24:54<04:35,  4.76it/s]

Gaps (ex-reports):  82%|████████▏ | 5900/7211 [24:55<04:35,  4.76it/s]

Gaps (ex-reports):  82%|████████▏ | 5901/7211 [24:55<04:35,  4.76it/s]

Gaps (ex-reports):  82%|████████▏ | 5902/7211 [24:55<04:33,  4.79it/s]

Gaps (ex-reports):  82%|████████▏ | 5903/7211 [24:55<04:31,  4.82it/s]

Gaps (ex-reports):  82%|████████▏ | 5904/7211 [24:55<04:25,  4.93it/s]

Gaps (ex-reports):  82%|████████▏ | 5905/7211 [24:56<04:27,  4.87it/s]

Gaps (ex-reports):  82%|████████▏ | 5906/7211 [24:56<04:22,  4.97it/s]

Gaps (ex-reports):  82%|████████▏ | 5907/7211 [24:56<04:18,  5.05it/s]

Gaps (ex-reports):  82%|████████▏ | 5908/7211 [24:56<04:25,  4.92it/s]

Gaps (ex-reports):  82%|████████▏ | 5909/7211 [24:56<04:24,  4.93it/s]

Gaps (ex-reports):  82%|████████▏ | 5910/7211 [24:57<04:18,  5.03it/s]

Gaps (ex-reports):  82%|████████▏ | 5911/7211 [24:57<04:13,  5.13it/s]

Gaps (ex-reports):  82%|████████▏ | 5912/7211 [24:57<04:14,  5.10it/s]

Gaps (ex-reports):  82%|████████▏ | 5913/7211 [24:57<04:13,  5.11it/s]

Gaps (ex-reports):  82%|████████▏ | 5914/7211 [24:57<04:11,  5.16it/s]

Gaps (ex-reports):  82%|████████▏ | 5915/7211 [24:58<04:15,  5.07it/s]

Gaps (ex-reports):  82%|████████▏ | 5916/7211 [24:58<04:21,  4.96it/s]

Gaps (ex-reports):  82%|████████▏ | 5917/7211 [24:58<04:19,  4.99it/s]

Gaps (ex-reports):  82%|████████▏ | 5918/7211 [24:58<04:19,  4.98it/s]

Gaps (ex-reports):  82%|████████▏ | 5919/7211 [24:58<04:15,  5.05it/s]

Gaps (ex-reports):  82%|████████▏ | 5920/7211 [24:59<04:13,  5.10it/s]

Gaps (ex-reports):  82%|████████▏ | 5921/7211 [24:59<04:19,  4.97it/s]

Gaps (ex-reports):  82%|████████▏ | 5922/7211 [24:59<04:21,  4.93it/s]

Gaps (ex-reports):  82%|████████▏ | 5923/7211 [24:59<04:20,  4.94it/s]

Gaps (ex-reports):  82%|████████▏ | 5924/7211 [24:59<04:29,  4.77it/s]

Gaps (ex-reports):  82%|████████▏ | 5925/7211 [25:00<04:27,  4.81it/s]

Gaps (ex-reports):  82%|████████▏ | 5926/7211 [25:00<04:23,  4.88it/s]

Gaps (ex-reports):  82%|████████▏ | 5927/7211 [25:00<04:15,  5.02it/s]

Gaps (ex-reports):  82%|████████▏ | 5928/7211 [25:00<04:14,  5.05it/s]

Gaps (ex-reports):  82%|████████▏ | 5929/7211 [25:00<04:19,  4.94it/s]

Gaps (ex-reports):  82%|████████▏ | 5930/7211 [25:02<11:13,  1.90it/s]

Gaps (ex-reports):  82%|████████▏ | 5931/7211 [25:02<09:11,  2.32it/s]

Gaps (ex-reports):  82%|████████▏ | 5932/7211 [25:02<07:41,  2.77it/s]

Gaps (ex-reports):  82%|████████▏ | 5933/7211 [25:02<06:38,  3.21it/s]

Gaps (ex-reports):  82%|████████▏ | 5934/7211 [25:03<05:50,  3.64it/s]

Gaps (ex-reports):  82%|████████▏ | 5935/7211 [25:03<05:20,  3.98it/s]

Gaps (ex-reports):  82%|████████▏ | 5936/7211 [25:03<05:04,  4.18it/s]

Gaps (ex-reports):  82%|████████▏ | 5937/7211 [25:03<05:26,  3.90it/s]

Gaps (ex-reports):  82%|████████▏ | 5938/7211 [25:03<05:05,  4.17it/s]

Gaps (ex-reports):  82%|████████▏ | 5939/7211 [25:04<05:11,  4.08it/s]

Gaps (ex-reports):  82%|████████▏ | 5940/7211 [25:04<04:58,  4.26it/s]

Gaps (ex-reports):  82%|████████▏ | 5941/7211 [25:04<04:44,  4.46it/s]

Gaps (ex-reports):  82%|████████▏ | 5942/7211 [25:04<04:31,  4.67it/s]

Gaps (ex-reports):  82%|████████▏ | 5943/7211 [25:05<04:24,  4.79it/s]

Gaps (ex-reports):  82%|████████▏ | 5944/7211 [25:05<04:22,  4.82it/s]

Gaps (ex-reports):  82%|████████▏ | 5945/7211 [25:05<04:30,  4.69it/s]

Gaps (ex-reports):  82%|████████▏ | 5946/7211 [25:05<04:27,  4.73it/s]

Gaps (ex-reports):  82%|████████▏ | 5947/7211 [25:05<04:26,  4.75it/s]

Gaps (ex-reports):  82%|████████▏ | 5948/7211 [25:06<04:31,  4.65it/s]

Gaps (ex-reports):  82%|████████▏ | 5949/7211 [25:06<04:30,  4.66it/s]

Gaps (ex-reports):  83%|████████▎ | 5950/7211 [25:06<04:28,  4.70it/s]

Gaps (ex-reports):  83%|████████▎ | 5951/7211 [25:06<04:24,  4.76it/s]

Gaps (ex-reports):  83%|████████▎ | 5952/7211 [25:06<04:20,  4.84it/s]

Gaps (ex-reports):  83%|████████▎ | 5953/7211 [25:07<04:17,  4.88it/s]

Gaps (ex-reports):  83%|████████▎ | 5954/7211 [25:07<04:20,  4.83it/s]

Gaps (ex-reports):  83%|████████▎ | 5955/7211 [25:07<04:44,  4.41it/s]

Gaps (ex-reports):  83%|████████▎ | 5956/7211 [25:07<04:37,  4.53it/s]

Gaps (ex-reports):  83%|████████▎ | 5957/7211 [25:08<04:31,  4.62it/s]

Gaps (ex-reports):  83%|████████▎ | 5958/7211 [25:08<04:25,  4.72it/s]

Gaps (ex-reports):  83%|████████▎ | 5959/7211 [25:08<04:18,  4.84it/s]

Gaps (ex-reports):  83%|████████▎ | 5960/7211 [25:08<04:13,  4.93it/s]

Gaps (ex-reports):  83%|████████▎ | 5961/7211 [26:08<6:20:06, 18.25s/it]

Gaps (ex-reports):  83%|████████▎ | 5962/7211 [26:09<4:27:03, 12.83s/it]

Gaps (ex-reports):  83%|████████▎ | 5963/7211 [26:09<3:08:10,  9.05s/it]

Gaps (ex-reports):  83%|████████▎ | 5964/7211 [26:09<2:12:50,  6.39s/it]

Gaps (ex-reports):  83%|████████▎ | 5965/7211 [26:09<1:34:11,  4.54s/it]

Gaps (ex-reports):  83%|████████▎ | 5966/7211 [26:09<1:07:05,  3.23s/it]

Gaps (ex-reports):  83%|████████▎ | 5967/7211 [26:10<48:14,  2.33s/it]

Gaps (ex-reports):  83%|████████▎ | 5968/7211 [26:10<35:00,  1.69s/it]

Gaps (ex-reports):  83%|████████▎ | 5969/7211 [26:10<25:42,  1.24s/it]

Gaps (ex-reports):  83%|████████▎ | 5970/7211 [26:10<19:15,  1.07it/s]

Gaps (ex-reports):  83%|████████▎ | 5971/7211 [26:10<14:46,  1.40it/s]

Gaps (ex-reports):  83%|████████▎ | 5972/7211 [26:11<11:36,  1.78it/s]

Gaps (ex-reports):  83%|████████▎ | 5973/7211 [26:11<10:17,  2.01it/s]

Gaps (ex-reports):  83%|████████▎ | 5974/7211 [26:11<08:24,  2.45it/s]

Gaps (ex-reports):  83%|████████▎ | 5975/7211 [26:11<07:10,  2.87it/s]

Gaps (ex-reports):  83%|████████▎ | 5976/7211 [26:12<06:18,  3.27it/s]

Gaps (ex-reports):  83%|████████▎ | 5977/7211 [26:12<05:34,  3.69it/s]

Gaps (ex-reports):  83%|████████▎ | 5978/7211 [26:12<05:11,  3.96it/s]

Gaps (ex-reports):  83%|████████▎ | 5979/7211 [26:12<04:55,  4.17it/s]

Gaps (ex-reports):  83%|████████▎ | 5980/7211 [26:12<04:39,  4.40it/s]

Gaps (ex-reports):  83%|████████▎ | 5981/7211 [26:13<04:28,  4.58it/s]

Gaps (ex-reports):  83%|████████▎ | 5982/7211 [26:13<04:22,  4.69it/s]

Gaps (ex-reports):  83%|████████▎ | 5983/7211 [26:13<04:19,  4.74it/s]

Gaps (ex-reports):  83%|████████▎ | 5984/7211 [26:13<04:45,  4.29it/s]

Gaps (ex-reports):  83%|████████▎ | 5985/7211 [26:14<04:37,  4.41it/s]

Gaps (ex-reports):  83%|████████▎ | 5986/7211 [26:14<04:26,  4.60it/s]

Gaps (ex-reports):  83%|████████▎ | 5987/7211 [26:14<04:21,  4.69it/s]

Gaps (ex-reports):  83%|████████▎ | 5988/7211 [26:14<04:18,  4.72it/s]

Gaps (ex-reports):  83%|████████▎ | 5989/7211 [26:14<04:18,  4.73it/s]

Gaps (ex-reports):  83%|████████▎ | 5990/7211 [26:15<04:13,  4.82it/s]

Gaps (ex-reports):  83%|████████▎ | 5991/7211 [26:15<04:16,  4.75it/s]

Gaps (ex-reports):  83%|████████▎ | 5992/7211 [26:15<04:11,  4.84it/s]

Gaps (ex-reports):  83%|████████▎ | 5993/7211 [26:15<04:13,  4.80it/s]

Gaps (ex-reports):  83%|████████▎ | 5994/7211 [26:15<04:15,  4.77it/s]

Gaps (ex-reports):  83%|████████▎ | 5995/7211 [26:16<04:12,  4.81it/s]

Gaps (ex-reports):  83%|████████▎ | 5996/7211 [26:16<04:07,  4.91it/s]

Gaps (ex-reports):  83%|████████▎ | 5997/7211 [26:16<04:07,  4.90it/s]

Gaps (ex-reports):  83%|████████▎ | 5998/7211 [26:17<08:01,  2.52it/s]

Gaps (ex-reports):  83%|████████▎ | 5999/7211 [26:17<06:46,  2.98it/s]

Gaps (ex-reports):  83%|████████▎ | 6000/7211 [26:17<06:05,  3.32it/s]

Gaps (ex-reports):  83%|████████▎ | 6001/7211 [26:17<05:30,  3.66it/s]

Gaps (ex-reports):  83%|████████▎ | 6002/7211 [26:18<05:04,  3.97it/s]

Gaps (ex-reports):  83%|████████▎ | 6003/7211 [26:18<04:45,  4.23it/s]

Gaps (ex-reports):  83%|████████▎ | 6004/7211 [26:18<04:38,  4.34it/s]

Gaps (ex-reports):  83%|████████▎ | 6005/7211 [26:18<04:30,  4.46it/s]

Gaps (ex-reports):  83%|████████▎ | 6006/7211 [26:19<04:25,  4.53it/s]

Gaps (ex-reports):  83%|████████▎ | 6007/7211 [26:19<04:17,  4.67it/s]

Gaps (ex-reports):  83%|████████▎ | 6008/7211 [26:19<04:17,  4.67it/s]

Gaps (ex-reports):  83%|████████▎ | 6009/7211 [26:19<04:17,  4.67it/s]

Gaps (ex-reports):  83%|████████▎ | 6010/7211 [26:19<04:11,  4.77it/s]

Gaps (ex-reports):  83%|████████▎ | 6011/7211 [26:20<04:15,  4.69it/s]

Gaps (ex-reports):  83%|████████▎ | 6012/7211 [26:20<05:43,  3.49it/s]

Gaps (ex-reports):  83%|████████▎ | 6013/7211 [26:20<05:11,  3.85it/s]

Gaps (ex-reports):  83%|████████▎ | 6014/7211 [26:20<04:49,  4.13it/s]

Gaps (ex-reports):  83%|████████▎ | 6015/7211 [26:21<04:34,  4.36it/s]

Gaps (ex-reports):  83%|████████▎ | 6016/7211 [26:21<04:22,  4.56it/s]

Gaps (ex-reports):  83%|████████▎ | 6017/7211 [26:21<04:11,  4.75it/s]

Gaps (ex-reports):  83%|████████▎ | 6018/7211 [26:21<04:04,  4.87it/s]

Gaps (ex-reports):  83%|████████▎ | 6019/7211 [26:21<04:04,  4.87it/s]

Gaps (ex-reports):  83%|████████▎ | 6020/7211 [26:22<03:59,  4.98it/s]

Gaps (ex-reports):  83%|████████▎ | 6021/7211 [26:22<03:59,  4.98it/s]

Gaps (ex-reports):  84%|████████▎ | 6022/7211 [26:22<04:22,  4.53it/s]

Gaps (ex-reports):  84%|████████▎ | 6023/7211 [26:22<04:22,  4.53it/s]

Gaps (ex-reports):  84%|████████▎ | 6024/7211 [26:22<04:16,  4.62it/s]

Gaps (ex-reports):  84%|████████▎ | 6025/7211 [26:23<04:11,  4.72it/s]

Gaps (ex-reports):  84%|████████▎ | 6026/7211 [26:23<04:09,  4.74it/s]

Gaps (ex-reports):  84%|████████▎ | 6027/7211 [26:23<04:08,  4.77it/s]

Gaps (ex-reports):  84%|████████▎ | 6028/7211 [26:23<04:07,  4.79it/s]

Gaps (ex-reports):  84%|████████▎ | 6029/7211 [26:24<04:06,  4.80it/s]

Gaps (ex-reports):  84%|████████▎ | 6030/7211 [26:24<04:00,  4.92it/s]

Gaps (ex-reports):  84%|████████▎ | 6031/7211 [26:24<03:57,  4.97it/s]

Gaps (ex-reports):  84%|████████▎ | 6032/7211 [26:24<03:57,  4.95it/s]

Gaps (ex-reports):  84%|████████▎ | 6033/7211 [26:24<03:56,  4.99it/s]

Gaps (ex-reports):  84%|████████▎ | 6034/7211 [26:25<03:55,  5.00it/s]

Gaps (ex-reports):  84%|████████▎ | 6035/7211 [26:25<06:14,  3.14it/s]

Gaps (ex-reports):  84%|████████▎ | 6036/7211 [26:25<05:29,  3.57it/s]

Gaps (ex-reports):  84%|████████▎ | 6037/7211 [26:25<04:57,  3.95it/s]

Gaps (ex-reports):  84%|████████▎ | 6038/7211 [26:26<04:36,  4.24it/s]

Gaps (ex-reports):  84%|████████▎ | 6039/7211 [26:26<04:26,  4.40it/s]

Gaps (ex-reports):  84%|████████▍ | 6040/7211 [26:26<04:14,  4.60it/s]

Gaps (ex-reports):  84%|████████▍ | 6041/7211 [26:26<04:10,  4.68it/s]

Gaps (ex-reports):  84%|████████▍ | 6042/7211 [26:27<04:19,  4.51it/s]

Gaps (ex-reports):  84%|████████▍ | 6043/7211 [26:27<04:15,  4.57it/s]

Gaps (ex-reports):  84%|████████▍ | 6044/7211 [26:27<04:12,  4.62it/s]

Gaps (ex-reports):  84%|████████▍ | 6045/7211 [26:27<04:07,  4.71it/s]

Gaps (ex-reports):  84%|████████▍ | 6046/7211 [26:27<04:02,  4.80it/s]

Gaps (ex-reports):  84%|████████▍ | 6047/7211 [26:28<03:56,  4.92it/s]

Gaps (ex-reports):  84%|████████▍ | 6048/7211 [26:28<03:56,  4.92it/s]

Gaps (ex-reports):  84%|████████▍ | 6049/7211 [26:28<03:52,  5.00it/s]

Gaps (ex-reports):  84%|████████▍ | 6050/7211 [26:29<08:44,  2.22it/s]

Gaps (ex-reports):  84%|████████▍ | 6051/7211 [26:29<07:12,  2.68it/s]

Gaps (ex-reports):  84%|████████▍ | 6052/7211 [26:29<06:09,  3.13it/s]

Gaps (ex-reports):  84%|████████▍ | 6053/7211 [26:30<05:24,  3.57it/s]

Gaps (ex-reports):  84%|████████▍ | 6054/7211 [26:30<04:59,  3.86it/s]

Gaps (ex-reports):  84%|████████▍ | 6055/7211 [26:30<04:46,  4.04it/s]

Gaps (ex-reports):  84%|████████▍ | 6056/7211 [26:30<04:29,  4.28it/s]

Gaps (ex-reports):  84%|████████▍ | 6057/7211 [26:30<04:22,  4.40it/s]

Gaps (ex-reports):  84%|████████▍ | 6058/7211 [26:31<04:10,  4.60it/s]

Gaps (ex-reports):  84%|████████▍ | 6059/7211 [26:31<04:03,  4.73it/s]

Gaps (ex-reports):  84%|████████▍ | 6060/7211 [26:31<03:58,  4.82it/s]

Gaps (ex-reports):  84%|████████▍ | 6061/7211 [26:31<03:57,  4.84it/s]

Gaps (ex-reports):  84%|████████▍ | 6062/7211 [26:31<03:58,  4.82it/s]

Gaps (ex-reports):  84%|████████▍ | 6063/7211 [26:32<03:56,  4.85it/s]

Gaps (ex-reports):  84%|████████▍ | 6064/7211 [26:32<03:57,  4.82it/s]

Gaps (ex-reports):  84%|████████▍ | 6065/7211 [26:32<03:59,  4.79it/s]

Gaps (ex-reports):  84%|████████▍ | 6066/7211 [26:32<03:56,  4.83it/s]

Gaps (ex-reports):  84%|████████▍ | 6067/7211 [26:32<03:52,  4.91it/s]

Gaps (ex-reports):  84%|████████▍ | 6068/7211 [26:33<03:55,  4.86it/s]

Gaps (ex-reports):  84%|████████▍ | 6069/7211 [26:33<03:55,  4.85it/s]

Gaps (ex-reports):  84%|████████▍ | 6070/7211 [26:33<05:29,  3.46it/s]

Gaps (ex-reports):  84%|████████▍ | 6071/7211 [26:34<05:04,  3.75it/s]

Gaps (ex-reports):  84%|████████▍ | 6072/7211 [26:34<04:38,  4.10it/s]

Gaps (ex-reports):  84%|████████▍ | 6073/7211 [26:34<04:28,  4.24it/s]

Gaps (ex-reports):  84%|████████▍ | 6074/7211 [26:34<04:18,  4.40it/s]

Gaps (ex-reports):  84%|████████▍ | 6075/7211 [26:34<04:11,  4.51it/s]

Gaps (ex-reports):  84%|████████▍ | 6076/7211 [26:35<04:04,  4.64it/s]

Gaps (ex-reports):  84%|████████▍ | 6077/7211 [26:35<04:02,  4.69it/s]

Gaps (ex-reports):  84%|████████▍ | 6078/7211 [26:35<03:55,  4.81it/s]

Gaps (ex-reports):  84%|████████▍ | 6079/7211 [26:36<06:01,  3.13it/s]

Gaps (ex-reports):  84%|████████▍ | 6080/7211 [26:36<05:21,  3.51it/s]

Gaps (ex-reports):  84%|████████▍ | 6081/7211 [26:36<04:52,  3.86it/s]

Gaps (ex-reports):  84%|████████▍ | 6082/7211 [26:36<05:05,  3.69it/s]

Gaps (ex-reports):  84%|████████▍ | 6083/7211 [26:37<05:01,  3.74it/s]

Gaps (ex-reports):  84%|████████▍ | 6084/7211 [26:37<04:52,  3.85it/s]

Gaps (ex-reports):  84%|████████▍ | 6085/7211 [26:37<04:32,  4.14it/s]

Gaps (ex-reports):  84%|████████▍ | 6086/7211 [26:37<04:18,  4.35it/s]

Gaps (ex-reports):  84%|████████▍ | 6087/7211 [26:37<04:09,  4.50it/s]

Gaps (ex-reports):  84%|████████▍ | 6088/7211 [26:38<04:07,  4.53it/s]

Gaps (ex-reports):  84%|████████▍ | 6089/7211 [26:38<03:59,  4.69it/s]

Gaps (ex-reports):  84%|████████▍ | 6090/7211 [26:38<03:53,  4.79it/s]

Gaps (ex-reports):  84%|████████▍ | 6091/7211 [26:38<03:51,  4.84it/s]

Gaps (ex-reports):  84%|████████▍ | 6092/7211 [26:38<03:49,  4.88it/s]

Gaps (ex-reports):  84%|████████▍ | 6093/7211 [26:39<03:47,  4.92it/s]

Gaps (ex-reports):  85%|████████▍ | 6094/7211 [26:39<03:43,  4.99it/s]

Gaps (ex-reports):  85%|████████▍ | 6095/7211 [26:39<03:42,  5.02it/s]

Gaps (ex-reports):  85%|████████▍ | 6096/7211 [26:39<03:45,  4.95it/s]

Gaps (ex-reports):  85%|████████▍ | 6097/7211 [26:39<03:44,  4.96it/s]

Gaps (ex-reports):  85%|████████▍ | 6098/7211 [26:40<03:40,  5.05it/s]

Gaps (ex-reports):  85%|████████▍ | 6099/7211 [26:40<03:42,  5.00it/s]

Gaps (ex-reports):  85%|████████▍ | 6100/7211 [26:40<05:33,  3.33it/s]

Gaps (ex-reports):  85%|████████▍ | 6101/7211 [26:40<04:56,  3.74it/s]

Gaps (ex-reports):  85%|████████▍ | 6102/7211 [26:41<04:32,  4.06it/s]

Gaps (ex-reports):  85%|████████▍ | 6103/7211 [26:41<04:18,  4.28it/s]

Gaps (ex-reports):  85%|████████▍ | 6104/7211 [26:41<04:04,  4.52it/s]

Gaps (ex-reports):  85%|████████▍ | 6105/7211 [26:41<04:02,  4.56it/s]

Gaps (ex-reports):  85%|████████▍ | 6106/7211 [26:42<03:59,  4.62it/s]

Gaps (ex-reports):  85%|████████▍ | 6107/7211 [26:42<03:52,  4.75it/s]

Gaps (ex-reports):  85%|████████▍ | 6108/7211 [26:42<03:47,  4.86it/s]

Gaps (ex-reports):  85%|████████▍ | 6109/7211 [26:42<03:42,  4.95it/s]

Gaps (ex-reports):  85%|████████▍ | 6110/7211 [26:42<03:40,  4.99it/s]

Gaps (ex-reports):  85%|████████▍ | 6111/7211 [26:43<03:43,  4.92it/s]

Gaps (ex-reports):  85%|████████▍ | 6112/7211 [26:43<03:38,  5.03it/s]

Gaps (ex-reports):  85%|████████▍ | 6113/7211 [26:43<03:41,  4.96it/s]

Gaps (ex-reports):  85%|████████▍ | 6114/7211 [26:43<03:44,  4.89it/s]

Gaps (ex-reports):  85%|████████▍ | 6115/7211 [26:43<03:44,  4.88it/s]

Gaps (ex-reports):  85%|████████▍ | 6116/7211 [26:44<03:47,  4.81it/s]

Gaps (ex-reports):  85%|████████▍ | 6117/7211 [26:44<03:41,  4.93it/s]

Gaps (ex-reports):  85%|████████▍ | 6118/7211 [26:44<03:39,  4.99it/s]

Gaps (ex-reports):  85%|████████▍ | 6119/7211 [26:44<03:37,  5.03it/s]

Gaps (ex-reports):  85%|████████▍ | 6120/7211 [26:44<03:41,  4.93it/s]

Gaps (ex-reports):  85%|████████▍ | 6121/7211 [26:45<03:41,  4.91it/s]

Gaps (ex-reports):  85%|████████▍ | 6122/7211 [26:45<03:42,  4.89it/s]

Gaps (ex-reports):  85%|████████▍ | 6123/7211 [26:45<03:42,  4.89it/s]

Gaps (ex-reports):  85%|████████▍ | 6124/7211 [26:45<03:37,  4.99it/s]

Gaps (ex-reports):  85%|████████▍ | 6125/7211 [26:45<03:35,  5.04it/s]

Gaps (ex-reports):  85%|████████▍ | 6126/7211 [26:46<03:34,  5.06it/s]

Gaps (ex-reports):  85%|████████▍ | 6127/7211 [26:46<03:41,  4.90it/s]

Gaps (ex-reports):  85%|████████▍ | 6128/7211 [26:46<03:37,  4.98it/s]

Gaps (ex-reports):  85%|████████▍ | 6129/7211 [26:46<03:40,  4.90it/s]

Gaps (ex-reports):  85%|████████▌ | 6130/7211 [26:46<03:40,  4.91it/s]

Gaps (ex-reports):  85%|████████▌ | 6131/7211 [26:47<03:38,  4.95it/s]

Gaps (ex-reports):  85%|████████▌ | 6132/7211 [26:47<03:38,  4.94it/s]

Gaps (ex-reports):  85%|████████▌ | 6133/7211 [26:47<03:35,  5.01it/s]

Gaps (ex-reports):  85%|████████▌ | 6134/7211 [26:47<03:38,  4.93it/s]

Gaps (ex-reports):  85%|████████▌ | 6135/7211 [26:47<03:35,  4.99it/s]

Gaps (ex-reports):  85%|████████▌ | 6136/7211 [26:48<03:38,  4.92it/s]

Gaps (ex-reports):  85%|████████▌ | 6137/7211 [26:48<03:36,  4.96it/s]

Gaps (ex-reports):  85%|████████▌ | 6138/7211 [26:48<04:04,  4.38it/s]

Gaps (ex-reports):  85%|████████▌ | 6139/7211 [26:48<04:00,  4.45it/s]

Gaps (ex-reports):  85%|████████▌ | 6140/7211 [26:48<03:57,  4.52it/s]

Gaps (ex-reports):  85%|████████▌ | 6141/7211 [26:49<03:48,  4.69it/s]

Gaps (ex-reports):  85%|████████▌ | 6142/7211 [26:49<03:41,  4.82it/s]

Gaps (ex-reports):  85%|████████▌ | 6143/7211 [26:50<06:21,  2.80it/s]

Gaps (ex-reports):  85%|████████▌ | 6144/7211 [26:50<05:27,  3.26it/s]

Gaps (ex-reports):  85%|████████▌ | 6145/7211 [26:50<04:53,  3.63it/s]

Gaps (ex-reports):  85%|████████▌ | 6146/7211 [26:55<29:14,  1.65s/it]

Gaps (ex-reports):  85%|████████▌ | 6147/7211 [26:55<21:30,  1.21s/it]

Gaps (ex-reports):  85%|████████▌ | 6148/7211 [26:55<16:07,  1.10it/s]

Gaps (ex-reports):  85%|████████▌ | 6149/7211 [26:55<12:23,  1.43it/s]

Gaps (ex-reports):  85%|████████▌ | 6150/7211 [26:56<09:40,  1.83it/s]

Gaps (ex-reports):  85%|████████▌ | 6151/7211 [26:56<07:51,  2.25it/s]

Gaps (ex-reports):  85%|████████▌ | 6152/7211 [26:56<06:32,  2.70it/s]

Gaps (ex-reports):  85%|████████▌ | 6153/7211 [26:56<05:40,  3.10it/s]

Gaps (ex-reports):  85%|████████▌ | 6154/7211 [26:56<05:02,  3.50it/s]

Gaps (ex-reports):  85%|████████▌ | 6155/7211 [26:57<04:38,  3.80it/s]

Gaps (ex-reports):  85%|████████▌ | 6156/7211 [26:57<04:26,  3.96it/s]

Gaps (ex-reports):  85%|████████▌ | 6157/7211 [26:57<04:13,  4.16it/s]

Gaps (ex-reports):  85%|████████▌ | 6158/7211 [26:57<04:05,  4.29it/s]

Gaps (ex-reports):  85%|████████▌ | 6159/7211 [26:58<04:02,  4.34it/s]

Gaps (ex-reports):  85%|████████▌ | 6160/7211 [26:58<03:54,  4.48it/s]

Gaps (ex-reports):  85%|████████▌ | 6161/7211 [26:58<03:48,  4.59it/s]

Gaps (ex-reports):  85%|████████▌ | 6162/7211 [26:58<03:42,  4.72it/s]

Gaps (ex-reports):  85%|████████▌ | 6163/7211 [26:58<03:45,  4.65it/s]

Gaps (ex-reports):  85%|████████▌ | 6164/7211 [26:59<03:44,  4.66it/s]

Gaps (ex-reports):  85%|████████▌ | 6165/7211 [26:59<03:40,  4.74it/s]

Gaps (ex-reports):  86%|████████▌ | 6166/7211 [26:59<03:35,  4.84it/s]

Gaps (ex-reports):  86%|████████▌ | 6167/7211 [26:59<03:37,  4.80it/s]

Gaps (ex-reports):  86%|████████▌ | 6168/7211 [26:59<03:35,  4.83it/s]

Gaps (ex-reports):  86%|████████▌ | 6169/7211 [27:00<03:33,  4.87it/s]

Gaps (ex-reports):  86%|████████▌ | 6170/7211 [27:00<03:29,  4.96it/s]

Gaps (ex-reports):  86%|████████▌ | 6171/7211 [27:00<03:31,  4.92it/s]

Gaps (ex-reports):  86%|████████▌ | 6172/7211 [27:01<09:40,  1.79it/s]

Gaps (ex-reports):  86%|████████▌ | 6173/7211 [27:02<07:48,  2.22it/s]

Gaps (ex-reports):  86%|████████▌ | 6174/7211 [27:02<06:33,  2.63it/s]

Gaps (ex-reports):  86%|████████▌ | 6175/7211 [27:02<05:39,  3.05it/s]

Gaps (ex-reports):  86%|████████▌ | 6176/7211 [27:02<05:00,  3.44it/s]

Gaps (ex-reports):  86%|████████▌ | 6177/7211 [27:02<04:29,  3.83it/s]

Gaps (ex-reports):  86%|████████▌ | 6178/7211 [27:03<04:08,  4.15it/s]

Gaps (ex-reports):  86%|████████▌ | 6179/7211 [27:03<03:55,  4.38it/s]

Gaps (ex-reports):  86%|████████▌ | 6180/7211 [27:03<03:48,  4.51it/s]

Gaps (ex-reports):  86%|████████▌ | 6181/7211 [27:03<03:43,  4.62it/s]

Gaps (ex-reports):  86%|████████▌ | 6182/7211 [27:03<03:35,  4.77it/s]

Gaps (ex-reports):  86%|████████▌ | 6183/7211 [27:04<03:35,  4.77it/s]

Gaps (ex-reports):  86%|████████▌ | 6184/7211 [27:04<03:29,  4.90it/s]

Gaps (ex-reports):  86%|████████▌ | 6185/7211 [27:04<03:25,  5.00it/s]

Gaps (ex-reports):  86%|████████▌ | 6186/7211 [27:04<03:22,  5.05it/s]

Gaps (ex-reports):  86%|████████▌ | 6187/7211 [27:04<03:20,  5.09it/s]

Gaps (ex-reports):  86%|████████▌ | 6188/7211 [27:05<03:21,  5.07it/s]

Gaps (ex-reports):  86%|████████▌ | 6189/7211 [27:05<03:21,  5.07it/s]

Gaps (ex-reports):  86%|████████▌ | 6190/7211 [27:05<03:26,  4.94it/s]

Gaps (ex-reports):  86%|████████▌ | 6191/7211 [27:05<03:26,  4.93it/s]

Gaps (ex-reports):  86%|████████▌ | 6192/7211 [27:05<03:22,  5.02it/s]

Gaps (ex-reports):  86%|████████▌ | 6193/7211 [27:06<03:30,  4.82it/s]

Gaps (ex-reports):  86%|████████▌ | 6194/7211 [27:06<03:26,  4.92it/s]

Gaps (ex-reports):  86%|████████▌ | 6195/7211 [27:06<03:27,  4.90it/s]

Gaps (ex-reports):  86%|████████▌ | 6196/7211 [27:06<03:24,  4.97it/s]

Gaps (ex-reports):  86%|████████▌ | 6197/7211 [27:06<03:21,  5.04it/s]

Gaps (ex-reports):  86%|████████▌ | 6198/7211 [27:07<03:49,  4.41it/s]

Gaps (ex-reports):  86%|████████▌ | 6199/7211 [27:07<03:41,  4.57it/s]

Gaps (ex-reports):  86%|████████▌ | 6200/7211 [27:07<03:41,  4.57it/s]

Gaps (ex-reports):  86%|████████▌ | 6201/7211 [27:07<03:37,  4.65it/s]

Gaps (ex-reports):  86%|████████▌ | 6202/7211 [27:07<03:33,  4.73it/s]

Gaps (ex-reports):  86%|████████▌ | 6203/7211 [27:08<03:31,  4.76it/s]

Gaps (ex-reports):  86%|████████▌ | 6204/7211 [27:08<03:31,  4.76it/s]

Gaps (ex-reports):  86%|████████▌ | 6205/7211 [27:11<17:50,  1.06s/it]

Gaps (ex-reports):  86%|████████▌ | 6206/7211 [27:11<13:27,  1.24it/s]

Gaps (ex-reports):  86%|████████▌ | 6207/7211 [27:11<10:26,  1.60it/s]

Gaps (ex-reports):  86%|████████▌ | 6208/7211 [27:12<08:21,  2.00it/s]

Gaps (ex-reports):  86%|████████▌ | 6209/7211 [27:12<06:52,  2.43it/s]

Gaps (ex-reports):  86%|████████▌ | 6210/7211 [27:12<05:49,  2.86it/s]

Gaps (ex-reports):  86%|████████▌ | 6211/7211 [27:12<05:04,  3.29it/s]

Gaps (ex-reports):  86%|████████▌ | 6212/7211 [27:12<04:37,  3.60it/s]

Gaps (ex-reports):  86%|████████▌ | 6213/7211 [27:13<04:13,  3.94it/s]

Gaps (ex-reports):  86%|████████▌ | 6214/7211 [27:13<03:55,  4.24it/s]

Gaps (ex-reports):  86%|████████▌ | 6215/7211 [27:13<03:43,  4.46it/s]

Gaps (ex-reports):  86%|████████▌ | 6216/7211 [27:13<03:36,  4.59it/s]

Gaps (ex-reports):  86%|████████▌ | 6217/7211 [27:13<03:28,  4.78it/s]

Gaps (ex-reports):  86%|████████▌ | 6218/7211 [27:14<03:27,  4.79it/s]

Gaps (ex-reports):  86%|████████▌ | 6219/7211 [27:14<03:20,  4.94it/s]

Gaps (ex-reports):  86%|████████▋ | 6220/7211 [27:14<03:19,  4.97it/s]

Gaps (ex-reports):  86%|████████▋ | 6221/7211 [27:14<03:21,  4.91it/s]

Gaps (ex-reports):  86%|████████▋ | 6222/7211 [27:14<03:21,  4.90it/s]

Gaps (ex-reports):  86%|████████▋ | 6223/7211 [27:15<03:18,  4.99it/s]

Gaps (ex-reports):  86%|████████▋ | 6224/7211 [27:15<03:14,  5.08it/s]

Gaps (ex-reports):  86%|████████▋ | 6225/7211 [27:15<03:12,  5.11it/s]

Gaps (ex-reports):  86%|████████▋ | 6226/7211 [27:15<03:17,  4.98it/s]

Gaps (ex-reports):  86%|████████▋ | 6227/7211 [27:15<03:19,  4.94it/s]

Gaps (ex-reports):  86%|████████▋ | 6228/7211 [27:16<03:21,  4.87it/s]

Gaps (ex-reports):  86%|████████▋ | 6229/7211 [27:16<03:21,  4.87it/s]

Gaps (ex-reports):  86%|████████▋ | 6230/7211 [27:16<03:20,  4.88it/s]

Gaps (ex-reports):  86%|████████▋ | 6231/7211 [27:16<03:17,  4.97it/s]

Gaps (ex-reports):  86%|████████▋ | 6232/7211 [27:16<03:18,  4.92it/s]

Gaps (ex-reports):  86%|████████▋ | 6233/7211 [27:17<03:16,  4.97it/s]

Gaps (ex-reports):  86%|████████▋ | 6234/7211 [27:17<03:17,  4.96it/s]

Gaps (ex-reports):  86%|████████▋ | 6235/7211 [27:17<03:16,  4.96it/s]

Gaps (ex-reports):  86%|████████▋ | 6236/7211 [27:17<03:20,  4.87it/s]

Gaps (ex-reports):  86%|████████▋ | 6237/7211 [27:17<03:17,  4.94it/s]

Gaps (ex-reports):  87%|████████▋ | 6238/7211 [27:18<03:20,  4.84it/s]

Gaps (ex-reports):  87%|████████▋ | 6239/7211 [27:18<03:24,  4.75it/s]

Gaps (ex-reports):  87%|████████▋ | 6240/7211 [27:18<03:19,  4.87it/s]

Gaps (ex-reports):  87%|████████▋ | 6241/7211 [27:18<03:18,  4.89it/s]

Gaps (ex-reports):  87%|████████▋ | 6242/7211 [27:18<03:18,  4.89it/s]

Gaps (ex-reports):  87%|████████▋ | 6243/7211 [27:19<03:18,  4.89it/s]

Gaps (ex-reports):  87%|████████▋ | 6244/7211 [27:19<03:21,  4.80it/s]

Gaps (ex-reports):  87%|████████▋ | 6245/7211 [27:19<03:20,  4.82it/s]

Gaps (ex-reports):  87%|████████▋ | 6246/7211 [27:19<03:21,  4.80it/s]

Gaps (ex-reports):  87%|████████▋ | 6247/7211 [27:19<03:15,  4.94it/s]

Gaps (ex-reports):  87%|████████▋ | 6248/7211 [27:20<03:12,  5.00it/s]

Gaps (ex-reports):  87%|████████▋ | 6249/7211 [27:20<03:13,  4.97it/s]

Gaps (ex-reports):  87%|████████▋ | 6250/7211 [27:20<03:11,  5.01it/s]

Gaps (ex-reports):  87%|████████▋ | 6251/7211 [27:20<03:13,  4.97it/s]

Gaps (ex-reports):  87%|████████▋ | 6252/7211 [27:23<15:40,  1.02it/s]

Gaps (ex-reports):  87%|████████▋ | 6253/7211 [27:23<11:58,  1.33it/s]

Gaps (ex-reports):  87%|████████▋ | 6254/7211 [27:27<26:30,  1.66s/it]

Gaps (ex-reports):  87%|████████▋ | 6255/7211 [27:27<19:31,  1.22s/it]

Gaps (ex-reports):  87%|████████▋ | 6256/7211 [27:27<14:38,  1.09it/s]

Gaps (ex-reports):  87%|████████▋ | 6257/7211 [27:28<11:17,  1.41it/s]

Gaps (ex-reports):  87%|████████▋ | 6258/7211 [27:28<08:51,  1.79it/s]

Gaps (ex-reports):  87%|████████▋ | 6259/7211 [27:28<07:09,  2.21it/s]

Gaps (ex-reports):  87%|████████▋ | 6260/7211 [27:28<06:00,  2.64it/s]

Gaps (ex-reports):  87%|████████▋ | 6261/7211 [27:29<05:07,  3.09it/s]

Gaps (ex-reports):  87%|████████▋ | 6262/7211 [27:29<04:31,  3.50it/s]

Gaps (ex-reports):  87%|████████▋ | 6263/7211 [27:29<04:07,  3.84it/s]

Gaps (ex-reports):  87%|████████▋ | 6264/7211 [27:29<03:50,  4.11it/s]

Gaps (ex-reports):  87%|████████▋ | 6265/7211 [27:29<03:34,  4.41it/s]

Gaps (ex-reports):  87%|████████▋ | 6266/7211 [27:30<03:24,  4.62it/s]

Gaps (ex-reports):  87%|████████▋ | 6267/7211 [27:30<03:21,  4.69it/s]

Gaps (ex-reports):  87%|████████▋ | 6268/7211 [27:30<03:24,  4.62it/s]

Gaps (ex-reports):  87%|████████▋ | 6269/7211 [27:30<03:17,  4.78it/s]

Gaps (ex-reports):  87%|████████▋ | 6270/7211 [27:30<03:17,  4.77it/s]

Gaps (ex-reports):  87%|████████▋ | 6271/7211 [27:31<03:13,  4.86it/s]

Gaps (ex-reports):  87%|████████▋ | 6272/7211 [27:31<03:11,  4.89it/s]

Gaps (ex-reports):  87%|████████▋ | 6273/7211 [27:31<03:09,  4.95it/s]

Gaps (ex-reports):  87%|████████▋ | 6274/7211 [27:31<03:05,  5.04it/s]

Gaps (ex-reports):  87%|████████▋ | 6275/7211 [27:31<03:03,  5.09it/s]

Gaps (ex-reports):  87%|████████▋ | 6276/7211 [27:32<03:02,  5.11it/s]

Gaps (ex-reports):  87%|████████▋ | 6277/7211 [27:32<03:06,  5.01it/s]

Gaps (ex-reports):  87%|████████▋ | 6278/7211 [27:32<03:09,  4.92it/s]

Gaps (ex-reports):  87%|████████▋ | 6279/7211 [27:32<03:08,  4.94it/s]

Gaps (ex-reports):  87%|████████▋ | 6280/7211 [27:32<03:09,  4.90it/s]

Gaps (ex-reports):  87%|████████▋ | 6281/7211 [27:33<03:06,  4.98it/s]

Gaps (ex-reports):  87%|████████▋ | 6282/7211 [27:33<03:06,  4.97it/s]

Gaps (ex-reports):  87%|████████▋ | 6283/7211 [27:33<03:06,  4.97it/s]

Gaps (ex-reports):  87%|████████▋ | 6284/7211 [27:33<03:06,  4.98it/s]

Gaps (ex-reports):  87%|████████▋ | 6285/7211 [27:33<03:04,  5.01it/s]

Gaps (ex-reports):  87%|████████▋ | 6286/7211 [27:34<03:01,  5.10it/s]

Gaps (ex-reports):  87%|████████▋ | 6287/7211 [27:34<03:05,  4.98it/s]

Gaps (ex-reports):  87%|████████▋ | 6288/7211 [27:34<03:07,  4.92it/s]

Gaps (ex-reports):  87%|████████▋ | 6289/7211 [27:34<03:07,  4.92it/s]

Gaps (ex-reports):  87%|████████▋ | 6290/7211 [27:34<03:11,  4.81it/s]

Gaps (ex-reports):  87%|████████▋ | 6291/7211 [27:35<03:09,  4.86it/s]

Gaps (ex-reports):  87%|████████▋ | 6292/7211 [27:35<03:04,  4.99it/s]

Gaps (ex-reports):  87%|████████▋ | 6293/7211 [27:35<03:03,  5.01it/s]

Gaps (ex-reports):  87%|████████▋ | 6294/7211 [27:35<03:06,  4.93it/s]

Gaps (ex-reports):  87%|████████▋ | 6295/7211 [27:36<04:31,  3.37it/s]

Gaps (ex-reports):  87%|████████▋ | 6296/7211 [27:39<20:04,  1.32s/it]

Gaps (ex-reports):  87%|████████▋ | 6297/7211 [27:40<14:55,  1.02it/s]

Gaps (ex-reports):  87%|████████▋ | 6298/7211 [27:40<11:19,  1.34it/s]

Gaps (ex-reports):  87%|████████▋ | 6299/7211 [27:40<08:52,  1.71it/s]

Gaps (ex-reports):  87%|████████▋ | 6300/7211 [27:40<07:09,  2.12it/s]

Gaps (ex-reports):  87%|████████▋ | 6301/7211 [27:40<05:56,  2.56it/s]

Gaps (ex-reports):  87%|████████▋ | 6302/7211 [27:41<05:04,  2.98it/s]

Gaps (ex-reports):  87%|████████▋ | 6303/7211 [27:41<04:31,  3.35it/s]

Gaps (ex-reports):  87%|████████▋ | 6304/7211 [27:41<04:01,  3.76it/s]

Gaps (ex-reports):  87%|████████▋ | 6305/7211 [27:41<04:17,  3.52it/s]

Gaps (ex-reports):  87%|████████▋ | 6306/7211 [27:42<04:08,  3.64it/s]

Gaps (ex-reports):  87%|████████▋ | 6307/7211 [27:42<03:52,  3.89it/s]

Gaps (ex-reports):  87%|████████▋ | 6308/7211 [27:42<03:34,  4.22it/s]

Gaps (ex-reports):  87%|████████▋ | 6309/7211 [27:42<03:24,  4.42it/s]

Gaps (ex-reports):  88%|████████▊ | 6310/7211 [27:42<03:15,  4.61it/s]

Gaps (ex-reports):  88%|████████▊ | 6311/7211 [27:43<03:08,  4.76it/s]

Gaps (ex-reports):  88%|████████▊ | 6312/7211 [27:43<03:08,  4.77it/s]

Gaps (ex-reports):  88%|████████▊ | 6313/7211 [27:43<03:09,  4.75it/s]

Gaps (ex-reports):  88%|████████▊ | 6314/7211 [27:43<03:06,  4.82it/s]

Gaps (ex-reports):  88%|████████▊ | 6315/7211 [27:43<03:09,  4.72it/s]

Gaps (ex-reports):  88%|████████▊ | 6316/7211 [27:44<03:08,  4.75it/s]

Gaps (ex-reports):  88%|████████▊ | 6317/7211 [27:44<05:33,  2.68it/s]

Gaps (ex-reports):  88%|████████▊ | 6318/7211 [27:48<18:09,  1.22s/it]

Gaps (ex-reports):  88%|████████▊ | 6319/7211 [27:48<13:37,  1.09it/s]

Gaps (ex-reports):  88%|████████▊ | 6320/7211 [27:48<10:24,  1.43it/s]

Gaps (ex-reports):  88%|████████▊ | 6321/7211 [27:48<08:11,  1.81it/s]

Gaps (ex-reports):  88%|████████▊ | 6322/7211 [27:48<06:41,  2.22it/s]

Gaps (ex-reports):  88%|████████▊ | 6323/7211 [27:49<05:36,  2.64it/s]

Gaps (ex-reports):  88%|████████▊ | 6324/7211 [27:49<04:47,  3.08it/s]

Gaps (ex-reports):  88%|████████▊ | 6325/7211 [27:49<04:15,  3.46it/s]

Gaps (ex-reports):  88%|████████▊ | 6326/7211 [27:49<03:50,  3.84it/s]

Gaps (ex-reports):  88%|████████▊ | 6327/7211 [27:49<03:36,  4.08it/s]

Gaps (ex-reports):  88%|████████▊ | 6328/7211 [27:50<03:27,  4.26it/s]

Gaps (ex-reports):  88%|████████▊ | 6329/7211 [27:50<03:26,  4.27it/s]

Gaps (ex-reports):  88%|████████▊ | 6330/7211 [27:50<03:15,  4.51it/s]

Gaps (ex-reports):  88%|████████▊ | 6331/7211 [27:50<03:08,  4.66it/s]

Gaps (ex-reports):  88%|████████▊ | 6332/7211 [27:50<03:07,  4.70it/s]

Gaps (ex-reports):  88%|████████▊ | 6333/7211 [27:51<03:07,  4.67it/s]

Gaps (ex-reports):  88%|████████▊ | 6334/7211 [27:51<03:02,  4.81it/s]

Gaps (ex-reports):  88%|████████▊ | 6335/7211 [27:51<02:58,  4.90it/s]

Gaps (ex-reports):  88%|████████▊ | 6336/7211 [27:51<03:03,  4.76it/s]

Gaps (ex-reports):  88%|████████▊ | 6337/7211 [27:51<03:02,  4.78it/s]

Gaps (ex-reports):  88%|████████▊ | 6338/7211 [27:52<03:02,  4.79it/s]

Gaps (ex-reports):  88%|████████▊ | 6339/7211 [27:52<03:04,  4.72it/s]

Gaps (ex-reports):  88%|████████▊ | 6340/7211 [27:52<03:00,  4.82it/s]

Gaps (ex-reports):  88%|████████▊ | 6341/7211 [27:56<18:09,  1.25s/it]

Gaps (ex-reports):  88%|████████▊ | 6342/7211 [27:56<13:37,  1.06it/s]

Gaps (ex-reports):  88%|████████▊ | 6343/7211 [27:56<10:24,  1.39it/s]

Gaps (ex-reports):  88%|████████▊ | 6344/7211 [27:56<08:07,  1.78it/s]

Gaps (ex-reports):  88%|████████▊ | 6345/7211 [27:57<06:30,  2.22it/s]

Gaps (ex-reports):  88%|████████▊ | 6346/7211 [27:57<05:29,  2.62it/s]

Gaps (ex-reports):  88%|████████▊ | 6347/7211 [27:57<04:41,  3.07it/s]

Gaps (ex-reports):  88%|████████▊ | 6348/7211 [27:57<04:06,  3.50it/s]

Gaps (ex-reports):  88%|████████▊ | 6349/7211 [27:57<03:45,  3.82it/s]

Gaps (ex-reports):  88%|████████▊ | 6350/7211 [27:58<03:26,  4.17it/s]

Gaps (ex-reports):  88%|████████▊ | 6351/7211 [27:58<03:22,  4.25it/s]

Gaps (ex-reports):  88%|████████▊ | 6352/7211 [27:58<03:11,  4.48it/s]

Gaps (ex-reports):  88%|████████▊ | 6353/7211 [27:58<03:07,  4.57it/s]

Gaps (ex-reports):  88%|████████▊ | 6354/7211 [27:58<02:59,  4.77it/s]

Gaps (ex-reports):  88%|████████▊ | 6355/7211 [27:59<02:55,  4.89it/s]

Gaps (ex-reports):  88%|████████▊ | 6356/7211 [27:59<02:59,  4.77it/s]

Gaps (ex-reports):  88%|████████▊ | 6357/7211 [27:59<02:57,  4.82it/s]

Gaps (ex-reports):  88%|████████▊ | 6358/7211 [27:59<02:56,  4.82it/s]

Gaps (ex-reports):  88%|████████▊ | 6359/7211 [27:59<02:55,  4.85it/s]

Gaps (ex-reports):  88%|████████▊ | 6360/7211 [28:00<02:52,  4.92it/s]

Gaps (ex-reports):  88%|████████▊ | 6361/7211 [28:00<02:53,  4.89it/s]

Gaps (ex-reports):  88%|████████▊ | 6362/7211 [28:00<02:54,  4.86it/s]

Gaps (ex-reports):  88%|████████▊ | 6363/7211 [28:00<02:52,  4.92it/s]

Gaps (ex-reports):  88%|████████▊ | 6364/7211 [28:00<02:51,  4.95it/s]

Gaps (ex-reports):  88%|████████▊ | 6365/7211 [28:01<02:49,  5.00it/s]

Gaps (ex-reports):  88%|████████▊ | 6366/7211 [28:01<02:48,  5.03it/s]

Gaps (ex-reports):  88%|████████▊ | 6367/7211 [28:01<02:48,  5.01it/s]

Gaps (ex-reports):  88%|████████▊ | 6368/7211 [28:01<02:50,  4.93it/s]

Gaps (ex-reports):  88%|████████▊ | 6369/7211 [28:01<02:50,  4.94it/s]

Gaps (ex-reports):  88%|████████▊ | 6370/7211 [28:02<02:49,  4.95it/s]

Gaps (ex-reports):  88%|████████▊ | 6371/7211 [28:02<02:49,  4.95it/s]

Gaps (ex-reports):  88%|████████▊ | 6372/7211 [28:02<02:57,  4.73it/s]

Gaps (ex-reports):  88%|████████▊ | 6373/7211 [28:02<02:55,  4.78it/s]

Gaps (ex-reports):  88%|████████▊ | 6374/7211 [28:03<02:55,  4.78it/s]

Gaps (ex-reports):  88%|████████▊ | 6375/7211 [28:03<02:49,  4.92it/s]

Gaps (ex-reports):  88%|████████▊ | 6376/7211 [28:03<02:47,  4.99it/s]

Gaps (ex-reports):  88%|████████▊ | 6377/7211 [28:03<02:51,  4.87it/s]

Gaps (ex-reports):  88%|████████▊ | 6378/7211 [28:03<02:50,  4.88it/s]

Gaps (ex-reports):  88%|████████▊ | 6379/7211 [28:04<02:53,  4.78it/s]

Gaps (ex-reports):  88%|████████▊ | 6380/7211 [28:04<02:49,  4.90it/s]

Gaps (ex-reports):  88%|████████▊ | 6381/7211 [28:04<02:46,  4.97it/s]

Gaps (ex-reports):  89%|████████▊ | 6382/7211 [28:04<02:47,  4.96it/s]

Gaps (ex-reports):  89%|████████▊ | 6383/7211 [28:04<02:47,  4.93it/s]

Gaps (ex-reports):  89%|████████▊ | 6384/7211 [28:05<02:50,  4.86it/s]

Gaps (ex-reports):  89%|████████▊ | 6385/7211 [28:05<02:49,  4.86it/s]

Gaps (ex-reports):  89%|████████▊ | 6386/7211 [28:05<02:47,  4.92it/s]

Gaps (ex-reports):  89%|████████▊ | 6387/7211 [28:05<02:49,  4.87it/s]

Gaps (ex-reports):  89%|████████▊ | 6388/7211 [28:05<02:51,  4.81it/s]

Gaps (ex-reports):  89%|████████▊ | 6389/7211 [28:06<02:50,  4.81it/s]

Gaps (ex-reports):  89%|████████▊ | 6390/7211 [28:06<02:48,  4.86it/s]

Gaps (ex-reports):  89%|████████▊ | 6391/7211 [28:06<02:47,  4.88it/s]

Gaps (ex-reports):  89%|████████▊ | 6392/7211 [28:06<02:46,  4.91it/s]

Gaps (ex-reports):  89%|████████▊ | 6393/7211 [28:06<02:46,  4.92it/s]

Gaps (ex-reports):  89%|████████▊ | 6394/7211 [28:07<02:45,  4.94it/s]

Gaps (ex-reports):  89%|████████▊ | 6395/7211 [28:07<02:46,  4.89it/s]

Gaps (ex-reports):  89%|████████▊ | 6396/7211 [28:07<02:44,  4.97it/s]

Gaps (ex-reports):  89%|████████▊ | 6397/7211 [28:07<02:43,  4.99it/s]

Gaps (ex-reports):  89%|████████▊ | 6398/7211 [28:07<02:40,  5.06it/s]

Gaps (ex-reports):  89%|████████▊ | 6399/7211 [28:08<02:40,  5.05it/s]

Gaps (ex-reports):  89%|████████▉ | 6400/7211 [28:08<02:44,  4.94it/s]

Gaps (ex-reports):  89%|████████▉ | 6401/7211 [28:08<02:41,  5.03it/s]

Gaps (ex-reports):  89%|████████▉ | 6402/7211 [28:08<02:41,  5.01it/s]

Gaps (ex-reports):  89%|████████▉ | 6403/7211 [28:08<02:39,  5.06it/s]

Gaps (ex-reports):  89%|████████▉ | 6404/7211 [28:09<02:41,  5.01it/s]

Gaps (ex-reports):  89%|████████▉ | 6405/7211 [28:09<02:40,  5.03it/s]

Gaps (ex-reports):  89%|████████▉ | 6406/7211 [28:09<02:40,  5.03it/s]

Gaps (ex-reports):  89%|████████▉ | 6407/7211 [28:09<02:40,  5.02it/s]

Gaps (ex-reports):  89%|████████▉ | 6408/7211 [28:09<02:37,  5.09it/s]

Gaps (ex-reports):  89%|████████▉ | 6409/7211 [28:10<02:40,  5.00it/s]

Gaps (ex-reports):  89%|████████▉ | 6410/7211 [28:10<02:38,  5.06it/s]

Gaps (ex-reports):  89%|████████▉ | 6411/7211 [28:10<02:37,  5.08it/s]

Gaps (ex-reports):  89%|████████▉ | 6412/7211 [28:10<02:39,  5.02it/s]

Gaps (ex-reports):  89%|████████▉ | 6413/7211 [28:10<02:37,  5.07it/s]

Gaps (ex-reports):  89%|████████▉ | 6414/7211 [28:11<02:36,  5.09it/s]

Gaps (ex-reports):  89%|████████▉ | 6415/7211 [28:11<02:34,  5.15it/s]

Gaps (ex-reports):  89%|████████▉ | 6416/7211 [28:11<02:37,  5.04it/s]

Gaps (ex-reports):  89%|████████▉ | 6417/7211 [28:11<02:39,  4.97it/s]

Gaps (ex-reports):  89%|████████▉ | 6418/7211 [28:11<02:43,  4.85it/s]

Gaps (ex-reports):  89%|████████▉ | 6419/7211 [28:12<02:43,  4.85it/s]

Gaps (ex-reports):  89%|████████▉ | 6420/7211 [28:12<02:43,  4.83it/s]

Gaps (ex-reports):  89%|████████▉ | 6421/7211 [28:12<02:43,  4.84it/s]

Gaps (ex-reports):  89%|████████▉ | 6422/7211 [28:12<02:44,  4.79it/s]

Gaps (ex-reports):  89%|████████▉ | 6423/7211 [28:12<02:41,  4.88it/s]

Gaps (ex-reports):  89%|████████▉ | 6424/7211 [28:13<02:41,  4.88it/s]

Gaps (ex-reports):  89%|████████▉ | 6425/7211 [28:13<02:41,  4.85it/s]

Gaps (ex-reports):  89%|████████▉ | 6426/7211 [28:13<02:45,  4.75it/s]

Gaps (ex-reports):  89%|████████▉ | 6427/7211 [28:13<02:40,  4.89it/s]

Gaps (ex-reports):  89%|████████▉ | 6428/7211 [28:13<02:38,  4.94it/s]

Gaps (ex-reports):  89%|████████▉ | 6429/7211 [28:14<02:38,  4.94it/s]

Gaps (ex-reports):  89%|████████▉ | 6430/7211 [28:14<02:39,  4.89it/s]

Gaps (ex-reports):  89%|████████▉ | 6431/7211 [28:14<02:37,  4.96it/s]

Gaps (ex-reports):  89%|████████▉ | 6432/7211 [28:14<02:35,  5.01it/s]

Gaps (ex-reports):  89%|████████▉ | 6433/7211 [28:14<02:36,  4.98it/s]

Gaps (ex-reports):  89%|████████▉ | 6434/7211 [28:15<02:33,  5.06it/s]

Gaps (ex-reports):  89%|████████▉ | 6435/7211 [28:15<02:38,  4.89it/s]

Gaps (ex-reports):  89%|████████▉ | 6436/7211 [28:15<02:41,  4.81it/s]

Gaps (ex-reports):  89%|████████▉ | 6437/7211 [28:15<02:40,  4.83it/s]

Gaps (ex-reports):  89%|████████▉ | 6438/7211 [28:15<02:36,  4.93it/s]

Gaps (ex-reports):  89%|████████▉ | 6439/7211 [28:16<02:33,  5.03it/s]

Gaps (ex-reports):  89%|████████▉ | 6440/7211 [28:16<02:33,  5.02it/s]

Gaps (ex-reports):  89%|████████▉ | 6441/7211 [28:16<02:34,  5.00it/s]

Gaps (ex-reports):  89%|████████▉ | 6442/7211 [28:16<02:35,  4.93it/s]

Gaps (ex-reports):  89%|████████▉ | 6443/7211 [28:16<02:36,  4.92it/s]

Gaps (ex-reports):  89%|████████▉ | 6444/7211 [28:17<02:33,  5.01it/s]

Gaps (ex-reports):  89%|████████▉ | 6445/7211 [28:17<02:37,  4.87it/s]

Gaps (ex-reports):  89%|████████▉ | 6446/7211 [28:17<02:36,  4.87it/s]

Gaps (ex-reports):  89%|████████▉ | 6447/7211 [28:17<02:32,  5.00it/s]

Gaps (ex-reports):  89%|████████▉ | 6448/7211 [28:17<02:34,  4.93it/s]

Gaps (ex-reports):  89%|████████▉ | 6449/7211 [28:18<02:35,  4.90it/s]

Gaps (ex-reports):  89%|████████▉ | 6450/7211 [28:18<02:32,  5.00it/s]

Gaps (ex-reports):  89%|████████▉ | 6451/7211 [28:18<02:34,  4.92it/s]

Gaps (ex-reports):  89%|████████▉ | 6452/7211 [28:18<02:32,  4.96it/s]

Gaps (ex-reports):  89%|████████▉ | 6453/7211 [28:18<02:33,  4.94it/s]

Gaps (ex-reports):  90%|████████▉ | 6454/7211 [28:19<02:34,  4.89it/s]

Gaps (ex-reports):  90%|████████▉ | 6455/7211 [28:19<02:37,  4.79it/s]

Gaps (ex-reports):  90%|████████▉ | 6456/7211 [28:19<02:37,  4.79it/s]

Gaps (ex-reports):  90%|████████▉ | 6457/7211 [28:19<02:40,  4.69it/s]

Gaps (ex-reports):  90%|████████▉ | 6458/7211 [28:20<02:37,  4.78it/s]

Gaps (ex-reports):  90%|████████▉ | 6459/7211 [28:20<02:35,  4.83it/s]

Gaps (ex-reports):  90%|████████▉ | 6460/7211 [28:20<02:37,  4.76it/s]

Gaps (ex-reports):  90%|████████▉ | 6461/7211 [28:20<02:34,  4.86it/s]

Gaps (ex-reports):  90%|████████▉ | 6462/7211 [28:20<02:31,  4.94it/s]

Gaps (ex-reports):  90%|████████▉ | 6463/7211 [28:21<02:31,  4.95it/s]

Gaps (ex-reports):  90%|████████▉ | 6464/7211 [28:21<02:30,  4.97it/s]

Gaps (ex-reports):  90%|████████▉ | 6465/7211 [28:21<02:32,  4.88it/s]

Gaps (ex-reports):  90%|████████▉ | 6466/7211 [28:21<02:31,  4.90it/s]

Gaps (ex-reports):  90%|████████▉ | 6467/7211 [28:21<02:34,  4.80it/s]

Gaps (ex-reports):  90%|████████▉ | 6468/7211 [28:22<02:30,  4.94it/s]

Gaps (ex-reports):  90%|████████▉ | 6469/7211 [28:22<02:30,  4.93it/s]

Gaps (ex-reports):  90%|████████▉ | 6470/7211 [28:22<02:30,  4.92it/s]

Gaps (ex-reports):  90%|████████▉ | 6471/7211 [28:22<02:28,  4.98it/s]

Gaps (ex-reports):  90%|████████▉ | 6472/7211 [28:22<02:27,  5.01it/s]

Gaps (ex-reports):  90%|████████▉ | 6473/7211 [28:23<02:29,  4.95it/s]

Gaps (ex-reports):  90%|████████▉ | 6474/7211 [28:23<02:29,  4.92it/s]

Gaps (ex-reports):  90%|████████▉ | 6475/7211 [28:23<02:30,  4.88it/s]

Gaps (ex-reports):  90%|████████▉ | 6476/7211 [28:23<02:27,  4.99it/s]

Gaps (ex-reports):  90%|████████▉ | 6477/7211 [28:23<02:34,  4.77it/s]

Gaps (ex-reports):  90%|████████▉ | 6478/7211 [28:24<02:33,  4.79it/s]

Gaps (ex-reports):  90%|████████▉ | 6479/7211 [28:24<02:33,  4.78it/s]

Gaps (ex-reports):  90%|████████▉ | 6480/7211 [28:24<02:28,  4.93it/s]

Gaps (ex-reports):  90%|████████▉ | 6481/7211 [28:24<02:28,  4.90it/s]

Gaps (ex-reports):  90%|████████▉ | 6482/7211 [28:24<02:27,  4.94it/s]

Gaps (ex-reports):  90%|████████▉ | 6483/7211 [28:25<02:27,  4.94it/s]

Gaps (ex-reports):  90%|████████▉ | 6484/7211 [28:25<02:27,  4.93it/s]

Gaps (ex-reports):  90%|████████▉ | 6485/7211 [28:25<02:29,  4.85it/s]

Gaps (ex-reports):  90%|████████▉ | 6486/7211 [28:25<02:29,  4.85it/s]

Gaps (ex-reports):  90%|████████▉ | 6487/7211 [28:25<02:28,  4.88it/s]

Gaps (ex-reports):  90%|████████▉ | 6488/7211 [28:26<02:26,  4.93it/s]

Gaps (ex-reports):  90%|████████▉ | 6489/7211 [28:26<02:25,  4.96it/s]

Gaps (ex-reports):  90%|█████████ | 6490/7211 [28:26<02:25,  4.96it/s]

Gaps (ex-reports):  90%|█████████ | 6491/7211 [28:26<02:23,  5.03it/s]

Gaps (ex-reports):  90%|█████████ | 6492/7211 [28:26<02:22,  5.06it/s]

Gaps (ex-reports):  90%|█████████ | 6493/7211 [28:27<02:23,  5.01it/s]

Gaps (ex-reports):  90%|█████████ | 6494/7211 [28:27<02:25,  4.93it/s]

Gaps (ex-reports):  90%|█████████ | 6495/7211 [28:27<02:26,  4.89it/s]

Gaps (ex-reports):  90%|█████████ | 6496/7211 [28:27<02:27,  4.83it/s]

Gaps (ex-reports):  90%|█████████ | 6497/7211 [28:27<02:27,  4.85it/s]

Gaps (ex-reports):  90%|█████████ | 6498/7211 [28:28<02:26,  4.88it/s]

Gaps (ex-reports):  90%|█████████ | 6499/7211 [28:28<02:23,  4.95it/s]

Gaps (ex-reports):  90%|█████████ | 6500/7211 [28:28<02:21,  5.03it/s]

Gaps (ex-reports):  90%|█████████ | 6501/7211 [28:28<02:19,  5.10it/s]

Gaps (ex-reports):  90%|█████████ | 6502/7211 [28:28<02:19,  5.09it/s]

Gaps (ex-reports):  90%|█████████ | 6503/7211 [28:29<02:22,  4.97it/s]

Gaps (ex-reports):  90%|█████████ | 6504/7211 [28:29<02:23,  4.94it/s]

Gaps (ex-reports):  90%|█████████ | 6505/7211 [28:29<02:23,  4.91it/s]

Gaps (ex-reports):  90%|█████████ | 6506/7211 [28:29<02:24,  4.87it/s]

Gaps (ex-reports):  90%|█████████ | 6507/7211 [28:30<02:25,  4.84it/s]

Gaps (ex-reports):  90%|█████████ | 6508/7211 [28:30<02:25,  4.85it/s]

Gaps (ex-reports):  90%|█████████ | 6509/7211 [28:30<02:21,  4.95it/s]

Gaps (ex-reports):  90%|█████████ | 6510/7211 [28:30<02:19,  5.01it/s]

Gaps (ex-reports):  90%|█████████ | 6511/7211 [28:30<02:23,  4.87it/s]

Gaps (ex-reports):  90%|█████████ | 6512/7211 [28:31<02:29,  4.69it/s]

Gaps (ex-reports):  90%|█████████ | 6513/7211 [28:31<02:26,  4.75it/s]

Gaps (ex-reports):  90%|█████████ | 6514/7211 [28:31<02:26,  4.75it/s]

Gaps (ex-reports):  90%|█████████ | 6515/7211 [28:31<02:25,  4.79it/s]

Gaps (ex-reports):  90%|█████████ | 6516/7211 [28:31<02:22,  4.89it/s]

Gaps (ex-reports):  90%|█████████ | 6517/7211 [28:32<02:22,  4.86it/s]

Gaps (ex-reports):  90%|█████████ | 6518/7211 [28:32<02:21,  4.88it/s]

Gaps (ex-reports):  90%|█████████ | 6519/7211 [28:32<02:26,  4.74it/s]

Gaps (ex-reports):  90%|█████████ | 6520/7211 [28:32<02:21,  4.88it/s]

Gaps (ex-reports):  90%|█████████ | 6521/7211 [28:32<02:19,  4.96it/s]

Gaps (ex-reports):  90%|█████████ | 6522/7211 [28:33<02:20,  4.91it/s]

Gaps (ex-reports):  90%|█████████ | 6523/7211 [28:33<02:20,  4.88it/s]

Gaps (ex-reports):  90%|█████████ | 6524/7211 [28:33<02:19,  4.93it/s]

Gaps (ex-reports):  90%|█████████ | 6525/7211 [28:33<02:20,  4.87it/s]

Gaps (ex-reports):  91%|█████████ | 6526/7211 [28:33<02:19,  4.92it/s]

Gaps (ex-reports):  91%|█████████ | 6527/7211 [28:34<02:20,  4.87it/s]

Gaps (ex-reports):  91%|█████████ | 6528/7211 [28:34<02:19,  4.90it/s]

Gaps (ex-reports):  91%|█████████ | 6529/7211 [28:34<02:19,  4.87it/s]

Gaps (ex-reports):  91%|█████████ | 6530/7211 [28:34<02:19,  4.87it/s]

Gaps (ex-reports):  91%|█████████ | 6531/7211 [28:34<02:18,  4.90it/s]

Gaps (ex-reports):  91%|█████████ | 6532/7211 [28:35<02:15,  5.00it/s]

Gaps (ex-reports):  91%|█████████ | 6533/7211 [28:35<02:16,  4.96it/s]

Gaps (ex-reports):  91%|█████████ | 6534/7211 [28:35<02:15,  4.98it/s]

Gaps (ex-reports):  91%|█████████ | 6535/7211 [28:35<02:14,  5.04it/s]

Gaps (ex-reports):  91%|█████████ | 6536/7211 [28:35<02:12,  5.09it/s]

Gaps (ex-reports):  91%|█████████ | 6537/7211 [28:36<02:11,  5.11it/s]

Gaps (ex-reports):  91%|█████████ | 6538/7211 [28:36<02:16,  4.92it/s]

Gaps (ex-reports):  91%|█████████ | 6539/7211 [28:36<02:14,  5.00it/s]

Gaps (ex-reports):  91%|█████████ | 6540/7211 [28:36<02:12,  5.05it/s]

Gaps (ex-reports):  91%|█████████ | 6541/7211 [28:36<02:13,  5.00it/s]

Gaps (ex-reports):  91%|█████████ | 6542/7211 [28:37<02:17,  4.88it/s]

Gaps (ex-reports):  91%|█████████ | 6543/7211 [28:37<02:15,  4.91it/s]

Gaps (ex-reports):  91%|█████████ | 6544/7211 [28:37<02:13,  5.00it/s]

Gaps (ex-reports):  91%|█████████ | 6545/7211 [28:37<02:14,  4.95it/s]

Gaps (ex-reports):  91%|█████████ | 6546/7211 [28:37<02:15,  4.89it/s]

Gaps (ex-reports):  91%|█████████ | 6547/7211 [28:38<02:13,  4.96it/s]

Gaps (ex-reports):  91%|█████████ | 6548/7211 [28:38<02:12,  5.01it/s]

Gaps (ex-reports):  91%|█████████ | 6549/7211 [28:38<02:15,  4.90it/s]

Gaps (ex-reports):  91%|█████████ | 6550/7211 [28:38<02:19,  4.72it/s]

Gaps (ex-reports):  91%|█████████ | 6551/7211 [28:38<02:20,  4.71it/s]

Gaps (ex-reports):  91%|█████████ | 6552/7211 [28:39<02:18,  4.76it/s]

Gaps (ex-reports):  91%|█████████ | 6553/7211 [28:39<02:14,  4.88it/s]

Gaps (ex-reports):  91%|█████████ | 6554/7211 [28:39<02:14,  4.90it/s]

Gaps (ex-reports):  91%|█████████ | 6555/7211 [28:39<02:12,  4.96it/s]

Gaps (ex-reports):  91%|█████████ | 6556/7211 [28:40<02:17,  4.76it/s]

Gaps (ex-reports):  91%|█████████ | 6557/7211 [28:40<02:17,  4.77it/s]

Gaps (ex-reports):  91%|█████████ | 6558/7211 [28:40<02:17,  4.76it/s]

Gaps (ex-reports):  91%|█████████ | 6559/7211 [28:40<02:15,  4.80it/s]

Gaps (ex-reports):  91%|█████████ | 6560/7211 [28:40<02:17,  4.73it/s]

Gaps (ex-reports):  91%|█████████ | 6561/7211 [28:41<02:14,  4.82it/s]

Gaps (ex-reports):  91%|█████████ | 6562/7211 [28:41<02:13,  4.85it/s]

Gaps (ex-reports):  91%|█████████ | 6563/7211 [28:41<02:12,  4.90it/s]

Gaps (ex-reports):  91%|█████████ | 6564/7211 [28:41<02:12,  4.87it/s]

Gaps (ex-reports):  91%|█████████ | 6565/7211 [28:41<02:12,  4.89it/s]

Gaps (ex-reports):  91%|█████████ | 6566/7211 [28:42<02:10,  4.94it/s]

Gaps (ex-reports):  91%|█████████ | 6567/7211 [28:42<02:14,  4.80it/s]

Gaps (ex-reports):  91%|█████████ | 6568/7211 [28:42<02:13,  4.82it/s]

Gaps (ex-reports):  91%|█████████ | 6569/7211 [28:42<02:14,  4.76it/s]

Gaps (ex-reports):  91%|█████████ | 6570/7211 [28:42<02:15,  4.74it/s]

Gaps (ex-reports):  91%|█████████ | 6571/7211 [28:43<02:12,  4.84it/s]

Gaps (ex-reports):  91%|█████████ | 6572/7211 [28:43<02:15,  4.72it/s]

Gaps (ex-reports):  91%|█████████ | 6573/7211 [28:43<02:13,  4.79it/s]

Gaps (ex-reports):  91%|█████████ | 6574/7211 [28:43<02:09,  4.92it/s]

Gaps (ex-reports):  91%|█████████ | 6575/7211 [28:43<02:11,  4.84it/s]

Gaps (ex-reports):  91%|█████████ | 6576/7211 [28:44<02:08,  4.94it/s]

Gaps (ex-reports):  91%|█████████ | 6577/7211 [28:44<02:09,  4.90it/s]

Gaps (ex-reports):  91%|█████████ | 6578/7211 [28:44<02:10,  4.85it/s]

Gaps (ex-reports):  91%|█████████ | 6579/7211 [28:44<02:08,  4.93it/s]

Gaps (ex-reports):  91%|█████████ | 6580/7211 [28:44<02:07,  4.96it/s]

Gaps (ex-reports):  91%|█████████▏| 6581/7211 [28:45<02:04,  5.06it/s]

Gaps (ex-reports):  91%|█████████▏| 6582/7211 [28:45<02:05,  5.00it/s]

Gaps (ex-reports):  91%|█████████▏| 6583/7211 [28:45<02:07,  4.92it/s]

Gaps (ex-reports):  91%|█████████▏| 6584/7211 [28:45<02:09,  4.84it/s]

Gaps (ex-reports):  91%|█████████▏| 6585/7211 [28:45<02:09,  4.85it/s]

Gaps (ex-reports):  91%|█████████▏| 6586/7211 [28:46<02:09,  4.84it/s]

Gaps (ex-reports):  91%|█████████▏| 6587/7211 [28:46<02:09,  4.83it/s]

Gaps (ex-reports):  91%|█████████▏| 6588/7211 [28:46<02:11,  4.74it/s]

Gaps (ex-reports):  91%|█████████▏| 6589/7211 [28:46<02:24,  4.30it/s]

Gaps (ex-reports):  91%|█████████▏| 6590/7211 [28:47<02:27,  4.22it/s]

Gaps (ex-reports):  91%|█████████▏| 6591/7211 [28:47<02:23,  4.32it/s]

Gaps (ex-reports):  91%|█████████▏| 6592/7211 [28:47<02:27,  4.19it/s]

Gaps (ex-reports):  91%|█████████▏| 6593/7211 [28:47<02:20,  4.41it/s]

Gaps (ex-reports):  91%|█████████▏| 6594/7211 [28:48<02:17,  4.48it/s]

Gaps (ex-reports):  91%|█████████▏| 6595/7211 [28:48<02:12,  4.64it/s]

Gaps (ex-reports):  91%|█████████▏| 6596/7211 [28:48<02:31,  4.07it/s]

Gaps (ex-reports):  91%|█████████▏| 6597/7211 [28:48<02:21,  4.33it/s]

Gaps (ex-reports):  91%|█████████▏| 6598/7211 [28:48<02:13,  4.59it/s]

Gaps (ex-reports):  92%|█████████▏| 6599/7211 [28:49<02:13,  4.57it/s]

Gaps (ex-reports):  92%|█████████▏| 6600/7211 [28:49<02:11,  4.66it/s]

Gaps (ex-reports):  92%|█████████▏| 6601/7211 [28:49<02:10,  4.66it/s]

Gaps (ex-reports):  92%|█████████▏| 6602/7211 [28:49<02:08,  4.72it/s]

Gaps (ex-reports):  92%|█████████▏| 6603/7211 [28:49<02:07,  4.79it/s]

Gaps (ex-reports):  92%|█████████▏| 6604/7211 [28:50<03:06,  3.25it/s]

Gaps (ex-reports):  92%|█████████▏| 6605/7211 [28:50<02:45,  3.65it/s]

Gaps (ex-reports):  92%|█████████▏| 6606/7211 [28:50<02:31,  3.99it/s]

Gaps (ex-reports):  92%|█████████▏| 6607/7211 [28:51<02:23,  4.19it/s]

Gaps (ex-reports):  92%|█████████▏| 6608/7211 [28:51<02:19,  4.32it/s]

Gaps (ex-reports):  92%|█████████▏| 6609/7211 [28:51<02:15,  4.45it/s]

Gaps (ex-reports):  92%|█████████▏| 6610/7211 [28:51<02:13,  4.49it/s]

Gaps (ex-reports):  92%|█████████▏| 6611/7211 [28:51<02:09,  4.65it/s]

Gaps (ex-reports):  92%|█████████▏| 6612/7211 [28:52<02:06,  4.74it/s]

Gaps (ex-reports):  92%|█████████▏| 6613/7211 [28:52<02:05,  4.78it/s]

Gaps (ex-reports):  92%|█████████▏| 6614/7211 [28:52<02:05,  4.77it/s]

Gaps (ex-reports):  92%|█████████▏| 6615/7211 [28:52<02:03,  4.82it/s]

Gaps (ex-reports):  92%|█████████▏| 6616/7211 [28:52<02:00,  4.95it/s]

Gaps (ex-reports):  92%|█████████▏| 6617/7211 [28:53<01:58,  5.02it/s]

Gaps (ex-reports):  92%|█████████▏| 6618/7211 [28:53<01:57,  5.03it/s]

Gaps (ex-reports):  92%|█████████▏| 6619/7211 [28:53<01:59,  4.94it/s]

Gaps (ex-reports):  92%|█████████▏| 6620/7211 [28:53<01:59,  4.94it/s]

Gaps (ex-reports):  92%|█████████▏| 6621/7211 [28:53<01:57,  5.03it/s]

Gaps (ex-reports):  92%|█████████▏| 6622/7211 [28:54<01:55,  5.11it/s]

Gaps (ex-reports):  92%|█████████▏| 6623/7211 [28:54<01:56,  5.07it/s]

Gaps (ex-reports):  92%|█████████▏| 6624/7211 [28:54<01:54,  5.13it/s]

Gaps (ex-reports):  92%|█████████▏| 6625/7211 [28:54<01:54,  5.13it/s]

Gaps (ex-reports):  92%|█████████▏| 6626/7211 [28:54<01:55,  5.08it/s]

Gaps (ex-reports):  92%|█████████▏| 6627/7211 [28:55<01:55,  5.07it/s]

Gaps (ex-reports):  92%|█████████▏| 6628/7211 [28:55<01:55,  5.05it/s]

Gaps (ex-reports):  92%|█████████▏| 6629/7211 [28:55<01:54,  5.09it/s]

Gaps (ex-reports):  92%|█████████▏| 6630/7211 [28:55<01:54,  5.07it/s]

Gaps (ex-reports):  92%|█████████▏| 6631/7211 [28:55<01:56,  4.99it/s]

Gaps (ex-reports):  92%|█████████▏| 6632/7211 [28:56<01:56,  4.98it/s]

Gaps (ex-reports):  92%|█████████▏| 6633/7211 [28:56<01:57,  4.90it/s]

Gaps (ex-reports):  92%|█████████▏| 6634/7211 [28:56<01:59,  4.84it/s]

Gaps (ex-reports):  92%|█████████▏| 6635/7211 [28:56<01:58,  4.85it/s]

Gaps (ex-reports):  92%|█████████▏| 6636/7211 [28:56<01:57,  4.90it/s]

Gaps (ex-reports):  92%|█████████▏| 6637/7211 [28:57<01:58,  4.83it/s]

Gaps (ex-reports):  92%|█████████▏| 6638/7211 [28:57<01:56,  4.94it/s]

Gaps (ex-reports):  92%|█████████▏| 6639/7211 [28:58<04:09,  2.29it/s]

Gaps (ex-reports):  92%|█████████▏| 6640/7211 [28:58<03:28,  2.74it/s]

Gaps (ex-reports):  92%|█████████▏| 6641/7211 [28:58<02:59,  3.17it/s]

Gaps (ex-reports):  92%|█████████▏| 6642/7211 [28:58<02:42,  3.50it/s]

Gaps (ex-reports):  92%|█████████▏| 6643/7211 [28:59<02:26,  3.87it/s]

Gaps (ex-reports):  92%|█████████▏| 6644/7211 [28:59<02:18,  4.10it/s]

Gaps (ex-reports):  92%|█████████▏| 6645/7211 [28:59<02:24,  3.90it/s]

Gaps (ex-reports):  92%|█████████▏| 6646/7211 [28:59<02:14,  4.19it/s]

Gaps (ex-reports):  92%|█████████▏| 6647/7211 [29:00<02:09,  4.36it/s]

Gaps (ex-reports):  92%|█████████▏| 6648/7211 [29:00<02:02,  4.61it/s]

Gaps (ex-reports):  92%|█████████▏| 6649/7211 [29:01<05:27,  1.71it/s]

Gaps (ex-reports):  92%|█████████▏| 6650/7211 [29:01<04:22,  2.14it/s]

Gaps (ex-reports):  92%|█████████▏| 6651/7211 [29:02<03:37,  2.58it/s]

Gaps (ex-reports):  92%|█████████▏| 6652/7211 [29:02<03:06,  3.00it/s]

Gaps (ex-reports):  92%|█████████▏| 6653/7211 [29:02<02:43,  3.42it/s]

Gaps (ex-reports):  92%|█████████▏| 6654/7211 [29:02<02:25,  3.82it/s]

Gaps (ex-reports):  92%|█████████▏| 6655/7211 [29:02<02:15,  4.12it/s]

Gaps (ex-reports):  92%|█████████▏| 6656/7211 [29:03<02:08,  4.32it/s]

Gaps (ex-reports):  92%|█████████▏| 6657/7211 [29:03<02:02,  4.51it/s]

Gaps (ex-reports):  92%|█████████▏| 6658/7211 [29:03<02:01,  4.56it/s]

Gaps (ex-reports):  92%|█████████▏| 6659/7211 [29:03<01:55,  4.76it/s]

Gaps (ex-reports):  92%|█████████▏| 6660/7211 [29:03<01:55,  4.77it/s]

Gaps (ex-reports):  92%|█████████▏| 6661/7211 [29:04<01:54,  4.82it/s]

Gaps (ex-reports):  92%|█████████▏| 6662/7211 [29:04<01:52,  4.88it/s]

Gaps (ex-reports):  92%|█████████▏| 6663/7211 [29:04<01:49,  5.00it/s]

Gaps (ex-reports):  92%|█████████▏| 6664/7211 [29:04<01:48,  5.04it/s]

Gaps (ex-reports):  92%|█████████▏| 6665/7211 [29:04<01:48,  5.03it/s]

Gaps (ex-reports):  92%|█████████▏| 6666/7211 [29:05<01:48,  5.02it/s]

Gaps (ex-reports):  92%|█████████▏| 6667/7211 [29:05<01:50,  4.90it/s]

Gaps (ex-reports):  92%|█████████▏| 6668/7211 [29:05<01:50,  4.90it/s]

Gaps (ex-reports):  92%|█████████▏| 6669/7211 [29:05<01:53,  4.79it/s]

Gaps (ex-reports):  92%|█████████▏| 6670/7211 [29:05<01:51,  4.85it/s]

Gaps (ex-reports):  93%|█████████▎| 6671/7211 [29:06<01:52,  4.80it/s]

Gaps (ex-reports):  93%|█████████▎| 6672/7211 [29:06<01:55,  4.66it/s]

Gaps (ex-reports):  93%|█████████▎| 6673/7211 [29:06<01:54,  4.69it/s]

Gaps (ex-reports):  93%|█████████▎| 6674/7211 [29:06<02:06,  4.25it/s]

Gaps (ex-reports):  93%|█████████▎| 6675/7211 [29:07<02:01,  4.43it/s]

Gaps (ex-reports):  93%|█████████▎| 6676/7211 [29:07<01:59,  4.49it/s]

Gaps (ex-reports):  93%|█████████▎| 6677/7211 [29:07<01:54,  4.65it/s]

Gaps (ex-reports):  93%|█████████▎| 6678/7211 [29:07<02:37,  3.38it/s]

Gaps (ex-reports):  93%|█████████▎| 6679/7211 [29:08<02:22,  3.74it/s]

Gaps (ex-reports):  93%|█████████▎| 6680/7211 [29:08<02:11,  4.03it/s]

Gaps (ex-reports):  93%|█████████▎| 6681/7211 [29:08<02:04,  4.26it/s]

Gaps (ex-reports):  93%|█████████▎| 6682/7211 [29:08<01:58,  4.45it/s]

Gaps (ex-reports):  93%|█████████▎| 6683/7211 [29:08<01:55,  4.58it/s]

Gaps (ex-reports):  93%|█████████▎| 6684/7211 [29:09<01:52,  4.69it/s]

Gaps (ex-reports):  93%|█████████▎| 6685/7211 [29:09<01:52,  4.69it/s]

Gaps (ex-reports):  93%|█████████▎| 6686/7211 [29:09<01:50,  4.76it/s]

Gaps (ex-reports):  93%|█████████▎| 6687/7211 [29:09<01:50,  4.74it/s]

Gaps (ex-reports):  93%|█████████▎| 6688/7211 [29:10<01:50,  4.74it/s]

Gaps (ex-reports):  93%|█████████▎| 6689/7211 [29:10<01:48,  4.79it/s]

Gaps (ex-reports):  93%|█████████▎| 6690/7211 [29:10<01:45,  4.92it/s]

Gaps (ex-reports):  93%|█████████▎| 6691/7211 [29:10<01:46,  4.90it/s]

Gaps (ex-reports):  93%|█████████▎| 6692/7211 [29:10<01:44,  4.97it/s]

Gaps (ex-reports):  93%|█████████▎| 6693/7211 [29:11<01:43,  5.02it/s]

Gaps (ex-reports):  93%|█████████▎| 6694/7211 [29:11<01:42,  5.07it/s]

Gaps (ex-reports):  93%|█████████▎| 6695/7211 [29:11<01:43,  4.99it/s]

Gaps (ex-reports):  93%|█████████▎| 6696/7211 [29:11<01:44,  4.94it/s]

Gaps (ex-reports):  93%|█████████▎| 6697/7211 [29:11<01:45,  4.89it/s]

Gaps (ex-reports):  93%|█████████▎| 6698/7211 [29:12<01:43,  4.96it/s]

Gaps (ex-reports):  93%|█████████▎| 6699/7211 [29:12<01:43,  4.93it/s]

Gaps (ex-reports):  93%|█████████▎| 6700/7211 [29:12<01:42,  5.01it/s]

Gaps (ex-reports):  93%|█████████▎| 6701/7211 [29:12<01:40,  5.07it/s]

Gaps (ex-reports):  93%|█████████▎| 6702/7211 [29:12<01:39,  5.12it/s]

Gaps (ex-reports):  93%|█████████▎| 6703/7211 [29:13<01:44,  4.84it/s]

Gaps (ex-reports):  93%|█████████▎| 6704/7211 [29:13<01:43,  4.89it/s]

Gaps (ex-reports):  93%|█████████▎| 6705/7211 [29:13<01:44,  4.85it/s]

Gaps (ex-reports):  93%|█████████▎| 6706/7211 [29:13<01:41,  4.98it/s]

Gaps (ex-reports):  93%|█████████▎| 6707/7211 [29:13<01:40,  5.01it/s]

Gaps (ex-reports):  93%|█████████▎| 6708/7211 [29:14<01:41,  4.95it/s]

Gaps (ex-reports):  93%|█████████▎| 6709/7211 [29:14<01:41,  4.94it/s]

Gaps (ex-reports):  93%|█████████▎| 6710/7211 [29:14<02:15,  3.70it/s]

Gaps (ex-reports):  93%|█████████▎| 6711/7211 [29:14<02:03,  4.05it/s]

Gaps (ex-reports):  93%|█████████▎| 6712/7211 [29:15<01:57,  4.25it/s]

Gaps (ex-reports):  93%|█████████▎| 6713/7211 [29:15<01:51,  4.48it/s]

Gaps (ex-reports):  93%|█████████▎| 6714/7211 [29:15<01:48,  4.58it/s]

Gaps (ex-reports):  93%|█████████▎| 6715/7211 [29:15<01:44,  4.75it/s]

Gaps (ex-reports):  93%|█████████▎| 6716/7211 [29:15<01:41,  4.90it/s]

Gaps (ex-reports):  93%|█████████▎| 6717/7211 [29:16<01:44,  4.75it/s]

Gaps (ex-reports):  93%|█████████▎| 6718/7211 [29:16<01:43,  4.78it/s]

Gaps (ex-reports):  93%|█████████▎| 6719/7211 [29:16<01:40,  4.87it/s]

Gaps (ex-reports):  93%|█████████▎| 6720/7211 [29:16<01:40,  4.88it/s]

Gaps (ex-reports):  93%|█████████▎| 6721/7211 [29:16<01:38,  4.95it/s]

Gaps (ex-reports):  93%|█████████▎| 6722/7211 [29:17<01:39,  4.92it/s]

Gaps (ex-reports):  93%|█████████▎| 6723/7211 [29:17<01:37,  5.00it/s]

Gaps (ex-reports):  93%|█████████▎| 6724/7211 [29:17<01:36,  5.06it/s]

Gaps (ex-reports):  93%|█████████▎| 6725/7211 [29:17<01:35,  5.11it/s]

Gaps (ex-reports):  93%|█████████▎| 6726/7211 [29:17<01:34,  5.13it/s]

Gaps (ex-reports):  93%|█████████▎| 6727/7211 [29:18<01:35,  5.05it/s]

Gaps (ex-reports):  93%|█████████▎| 6728/7211 [29:18<01:35,  5.07it/s]

Gaps (ex-reports):  93%|█████████▎| 6729/7211 [29:18<01:36,  4.99it/s]

Gaps (ex-reports):  93%|█████████▎| 6730/7211 [29:18<01:37,  4.94it/s]

Gaps (ex-reports):  93%|█████████▎| 6731/7211 [29:18<01:35,  5.02it/s]

Gaps (ex-reports):  93%|█████████▎| 6732/7211 [29:19<01:35,  4.99it/s]

Gaps (ex-reports):  93%|█████████▎| 6733/7211 [29:19<01:35,  5.01it/s]

Gaps (ex-reports):  93%|█████████▎| 6734/7211 [29:19<01:36,  4.94it/s]

Gaps (ex-reports):  93%|█████████▎| 6735/7211 [29:22<09:10,  1.16s/it]

Gaps (ex-reports):  93%|█████████▎| 6736/7211 [29:23<06:53,  1.15it/s]

Gaps (ex-reports):  93%|█████████▎| 6737/7211 [29:23<05:18,  1.49it/s]

Gaps (ex-reports):  93%|█████████▎| 6738/7211 [29:23<04:11,  1.88it/s]

Gaps (ex-reports):  93%|█████████▎| 6739/7211 [29:23<03:25,  2.30it/s]

Gaps (ex-reports):  93%|█████████▎| 6740/7211 [29:23<02:52,  2.73it/s]

Gaps (ex-reports):  93%|█████████▎| 6741/7211 [29:24<02:30,  3.12it/s]

Gaps (ex-reports):  93%|█████████▎| 6742/7211 [29:24<02:13,  3.52it/s]

Gaps (ex-reports):  94%|█████████▎| 6743/7211 [29:24<02:00,  3.87it/s]

Gaps (ex-reports):  94%|█████████▎| 6744/7211 [29:24<01:50,  4.21it/s]

Gaps (ex-reports):  94%|█████████▎| 6745/7211 [29:24<01:46,  4.36it/s]

Gaps (ex-reports):  94%|█████████▎| 6746/7211 [29:25<01:43,  4.49it/s]

Gaps (ex-reports):  94%|█████████▎| 6747/7211 [29:25<01:39,  4.67it/s]

Gaps (ex-reports):  94%|█████████▎| 6748/7211 [29:25<01:39,  4.65it/s]

Gaps (ex-reports):  94%|█████████▎| 6749/7211 [29:25<01:36,  4.77it/s]

Gaps (ex-reports):  94%|█████████▎| 6750/7211 [29:25<01:35,  4.85it/s]

Gaps (ex-reports):  94%|█████████▎| 6751/7211 [29:26<01:36,  4.75it/s]

Gaps (ex-reports):  94%|█████████▎| 6752/7211 [29:26<01:37,  4.70it/s]

Gaps (ex-reports):  94%|█████████▎| 6753/7211 [29:26<01:36,  4.74it/s]

Gaps (ex-reports):  94%|█████████▎| 6754/7211 [29:26<01:35,  4.79it/s]

Gaps (ex-reports):  94%|█████████▎| 6755/7211 [29:26<01:35,  4.77it/s]

Gaps (ex-reports):  94%|█████████▎| 6756/7211 [29:27<01:33,  4.86it/s]

Gaps (ex-reports):  94%|█████████▎| 6757/7211 [29:27<01:34,  4.83it/s]

Gaps (ex-reports):  94%|█████████▎| 6758/7211 [29:27<01:31,  4.95it/s]

Gaps (ex-reports):  94%|█████████▎| 6759/7211 [29:27<01:29,  5.03it/s]

Gaps (ex-reports):  94%|█████████▎| 6760/7211 [29:27<01:28,  5.10it/s]

Gaps (ex-reports):  94%|█████████▍| 6761/7211 [29:28<01:27,  5.12it/s]

Gaps (ex-reports):  94%|█████████▍| 6762/7211 [29:28<01:30,  4.95it/s]

Gaps (ex-reports):  94%|█████████▍| 6763/7211 [29:28<01:31,  4.88it/s]

Gaps (ex-reports):  94%|█████████▍| 6764/7211 [29:28<01:31,  4.91it/s]

Gaps (ex-reports):  94%|█████████▍| 6765/7211 [29:28<01:30,  4.93it/s]

Gaps (ex-reports):  94%|█████████▍| 6766/7211 [29:29<01:31,  4.87it/s]

Gaps (ex-reports):  94%|█████████▍| 6767/7211 [29:29<01:31,  4.87it/s]

Gaps (ex-reports):  94%|█████████▍| 6768/7211 [29:29<01:29,  4.96it/s]

Gaps (ex-reports):  94%|█████████▍| 6769/7211 [29:29<01:28,  4.99it/s]

Gaps (ex-reports):  94%|█████████▍| 6770/7211 [29:29<01:28,  5.01it/s]

Gaps (ex-reports):  94%|█████████▍| 6771/7211 [29:30<01:27,  5.05it/s]

Gaps (ex-reports):  94%|█████████▍| 6772/7211 [29:30<01:26,  5.07it/s]

Gaps (ex-reports):  94%|█████████▍| 6773/7211 [29:30<01:28,  4.98it/s]

Gaps (ex-reports):  94%|█████████▍| 6774/7211 [29:30<01:28,  4.96it/s]

Gaps (ex-reports):  94%|█████████▍| 6775/7211 [29:30<01:28,  4.95it/s]

Gaps (ex-reports):  94%|█████████▍| 6776/7211 [29:31<01:26,  5.01it/s]

Gaps (ex-reports):  94%|█████████▍| 6777/7211 [29:31<01:25,  5.05it/s]

Gaps (ex-reports):  94%|█████████▍| 6778/7211 [29:31<01:24,  5.10it/s]

Gaps (ex-reports):  94%|█████████▍| 6779/7211 [29:31<01:25,  5.04it/s]

Gaps (ex-reports):  94%|█████████▍| 6780/7211 [29:31<01:25,  5.04it/s]

Gaps (ex-reports):  94%|█████████▍| 6781/7211 [29:32<01:24,  5.10it/s]

Gaps (ex-reports):  94%|█████████▍| 6782/7211 [29:32<01:25,  5.00it/s]

Gaps (ex-reports):  94%|█████████▍| 6783/7211 [29:32<01:29,  4.76it/s]

Gaps (ex-reports):  94%|█████████▍| 6784/7211 [29:32<01:28,  4.81it/s]

Gaps (ex-reports):  94%|█████████▍| 6785/7211 [29:33<01:28,  4.82it/s]

Gaps (ex-reports):  94%|█████████▍| 6786/7211 [29:33<01:29,  4.74it/s]

Gaps (ex-reports):  94%|█████████▍| 6787/7211 [29:33<01:27,  4.87it/s]

Gaps (ex-reports):  94%|█████████▍| 6788/7211 [29:33<01:25,  4.93it/s]

Gaps (ex-reports):  94%|█████████▍| 6789/7211 [29:33<01:24,  4.99it/s]

Gaps (ex-reports):  94%|█████████▍| 6790/7211 [29:34<01:25,  4.94it/s]

Gaps (ex-reports):  94%|█████████▍| 6791/7211 [29:34<01:26,  4.88it/s]

Gaps (ex-reports):  94%|█████████▍| 6792/7211 [29:34<01:25,  4.88it/s]

Gaps (ex-reports):  94%|█████████▍| 6793/7211 [29:34<01:25,  4.87it/s]

Gaps (ex-reports):  94%|█████████▍| 6794/7211 [29:34<01:24,  4.93it/s]

Gaps (ex-reports):  94%|█████████▍| 6795/7211 [29:35<01:25,  4.86it/s]

Gaps (ex-reports):  94%|█████████▍| 6796/7211 [29:35<01:24,  4.93it/s]

Gaps (ex-reports):  94%|█████████▍| 6797/7211 [29:35<01:23,  4.98it/s]

Gaps (ex-reports):  94%|█████████▍| 6798/7211 [29:35<01:24,  4.89it/s]

Gaps (ex-reports):  94%|█████████▍| 6799/7211 [29:35<01:23,  4.93it/s]

Gaps (ex-reports):  94%|█████████▍| 6800/7211 [29:36<01:23,  4.93it/s]

Gaps (ex-reports):  94%|█████████▍| 6801/7211 [29:36<01:22,  4.97it/s]

Gaps (ex-reports):  94%|█████████▍| 6802/7211 [29:36<01:22,  4.98it/s]

Gaps (ex-reports):  94%|█████████▍| 6803/7211 [29:36<01:21,  5.00it/s]

Gaps (ex-reports):  94%|█████████▍| 6804/7211 [29:36<01:21,  4.99it/s]

Gaps (ex-reports):  94%|█████████▍| 6805/7211 [29:37<01:21,  4.96it/s]

Gaps (ex-reports):  94%|█████████▍| 6806/7211 [29:37<01:20,  5.04it/s]

Gaps (ex-reports):  94%|█████████▍| 6807/7211 [29:37<01:19,  5.07it/s]

Gaps (ex-reports):  94%|█████████▍| 6808/7211 [29:37<01:20,  5.02it/s]

Gaps (ex-reports):  94%|█████████▍| 6809/7211 [29:37<01:19,  5.08it/s]

Gaps (ex-reports):  94%|█████████▍| 6810/7211 [29:38<01:18,  5.08it/s]

Gaps (ex-reports):  94%|█████████▍| 6811/7211 [29:38<01:19,  5.02it/s]

Gaps (ex-reports):  94%|█████████▍| 6812/7211 [29:38<01:18,  5.07it/s]

Gaps (ex-reports):  94%|█████████▍| 6813/7211 [29:38<01:16,  5.17it/s]

Gaps (ex-reports):  94%|█████████▍| 6814/7211 [29:38<01:17,  5.13it/s]

Gaps (ex-reports):  95%|█████████▍| 6815/7211 [29:39<01:18,  5.06it/s]

Gaps (ex-reports):  95%|█████████▍| 6816/7211 [29:39<01:17,  5.08it/s]

Gaps (ex-reports):  95%|█████████▍| 6817/7211 [29:39<01:17,  5.08it/s]

Gaps (ex-reports):  95%|█████████▍| 6818/7211 [29:40<03:17,  1.99it/s]

Gaps (ex-reports):  95%|█████████▍| 6819/7211 [29:40<02:42,  2.41it/s]

Gaps (ex-reports):  95%|█████████▍| 6820/7211 [29:41<02:17,  2.85it/s]

Gaps (ex-reports):  95%|█████████▍| 6821/7211 [29:41<01:59,  3.26it/s]

Gaps (ex-reports):  95%|█████████▍| 6822/7211 [29:41<01:48,  3.59it/s]

Gaps (ex-reports):  95%|█████████▍| 6823/7211 [29:41<01:41,  3.83it/s]

Gaps (ex-reports):  95%|█████████▍| 6824/7211 [29:45<09:04,  1.41s/it]

Gaps (ex-reports):  95%|█████████▍| 6825/7211 [29:46<06:51,  1.07s/it]

Gaps (ex-reports):  95%|█████████▍| 6826/7211 [29:46<05:09,  1.25it/s]

Gaps (ex-reports):  95%|█████████▍| 6827/7211 [29:46<03:58,  1.61it/s]

Gaps (ex-reports):  95%|█████████▍| 6828/7211 [29:46<03:08,  2.03it/s]

Gaps (ex-reports):  95%|█████████▍| 6829/7211 [29:46<02:39,  2.40it/s]

Gaps (ex-reports):  95%|█████████▍| 6830/7211 [29:47<02:14,  2.83it/s]

Gaps (ex-reports):  95%|█████████▍| 6831/7211 [29:47<01:57,  3.24it/s]

Gaps (ex-reports):  95%|█████████▍| 6832/7211 [29:47<01:43,  3.66it/s]

Gaps (ex-reports):  95%|█████████▍| 6833/7211 [29:47<01:36,  3.92it/s]

Gaps (ex-reports):  95%|█████████▍| 6834/7211 [29:47<01:30,  4.17it/s]

Gaps (ex-reports):  95%|█████████▍| 6835/7211 [29:48<01:25,  4.37it/s]

Gaps (ex-reports):  95%|█████████▍| 6836/7211 [29:48<01:22,  4.55it/s]

Gaps (ex-reports):  95%|█████████▍| 6837/7211 [29:48<01:22,  4.55it/s]

Gaps (ex-reports):  95%|█████████▍| 6838/7211 [29:48<01:19,  4.67it/s]

Gaps (ex-reports):  95%|█████████▍| 6839/7211 [29:48<01:17,  4.78it/s]

Gaps (ex-reports):  95%|█████████▍| 6840/7211 [29:49<01:15,  4.91it/s]

Gaps (ex-reports):  95%|█████████▍| 6841/7211 [29:49<01:14,  4.95it/s]

Gaps (ex-reports):  95%|█████████▍| 6842/7211 [29:49<01:14,  4.94it/s]

Gaps (ex-reports):  95%|█████████▍| 6843/7211 [29:49<01:15,  4.86it/s]

Gaps (ex-reports):  95%|█████████▍| 6844/7211 [29:49<01:14,  4.96it/s]

Gaps (ex-reports):  95%|█████████▍| 6845/7211 [29:50<01:13,  5.01it/s]

Gaps (ex-reports):  95%|█████████▍| 6846/7211 [29:50<01:13,  4.98it/s]

Gaps (ex-reports):  95%|█████████▍| 6847/7211 [29:50<01:15,  4.80it/s]

Gaps (ex-reports):  95%|█████████▍| 6848/7211 [29:50<01:13,  4.91it/s]

Gaps (ex-reports):  95%|█████████▍| 6849/7211 [29:50<01:12,  4.96it/s]

Gaps (ex-reports):  95%|█████████▍| 6850/7211 [29:51<01:13,  4.89it/s]

Gaps (ex-reports):  95%|█████████▌| 6851/7211 [29:51<01:11,  5.00it/s]

Gaps (ex-reports):  95%|█████████▌| 6852/7211 [29:56<10:37,  1.78s/it]

Gaps (ex-reports):  95%|█████████▌| 6853/7211 [29:56<07:45,  1.30s/it]

Gaps (ex-reports):  95%|█████████▌| 6854/7211 [29:57<05:48,  1.03it/s]

Gaps (ex-reports):  95%|█████████▌| 6855/7211 [29:57<04:26,  1.34it/s]

Gaps (ex-reports):  95%|█████████▌| 6856/7211 [29:57<03:31,  1.68it/s]

Gaps (ex-reports):  95%|█████████▌| 6857/7211 [29:57<02:49,  2.09it/s]

Gaps (ex-reports):  95%|█████████▌| 6858/7211 [29:58<02:23,  2.46it/s]

Gaps (ex-reports):  95%|█████████▌| 6859/7211 [29:58<02:00,  2.92it/s]

Gaps (ex-reports):  95%|█████████▌| 6860/7211 [29:58<01:44,  3.36it/s]

Gaps (ex-reports):  95%|█████████▌| 6861/7211 [29:58<01:33,  3.73it/s]

Gaps (ex-reports):  95%|█████████▌| 6862/7211 [29:58<01:26,  4.05it/s]

Gaps (ex-reports):  95%|█████████▌| 6863/7211 [29:59<01:20,  4.33it/s]

Gaps (ex-reports):  95%|█████████▌| 6864/7211 [29:59<01:16,  4.56it/s]

Gaps (ex-reports):  95%|█████████▌| 6865/7211 [29:59<01:13,  4.73it/s]

Gaps (ex-reports):  95%|█████████▌| 6866/7211 [29:59<01:12,  4.76it/s]

Gaps (ex-reports):  95%|█████████▌| 6867/7211 [29:59<01:13,  4.68it/s]

Gaps (ex-reports):  95%|█████████▌| 6868/7211 [30:00<01:13,  4.69it/s]

Gaps (ex-reports):  95%|█████████▌| 6869/7211 [30:00<01:12,  4.73it/s]

Gaps (ex-reports):  95%|█████████▌| 6870/7211 [30:00<01:13,  4.64it/s]

Gaps (ex-reports):  95%|█████████▌| 6871/7211 [30:00<01:13,  4.65it/s]

Gaps (ex-reports):  95%|█████████▌| 6872/7211 [30:00<01:11,  4.73it/s]

Gaps (ex-reports):  95%|█████████▌| 6873/7211 [30:01<01:10,  4.76it/s]

Gaps (ex-reports):  95%|█████████▌| 6874/7211 [30:01<01:11,  4.70it/s]

Gaps (ex-reports):  95%|█████████▌| 6875/7211 [30:01<01:10,  4.76it/s]

Gaps (ex-reports):  95%|█████████▌| 6876/7211 [30:01<01:10,  4.77it/s]

Gaps (ex-reports):  95%|█████████▌| 6877/7211 [30:01<01:09,  4.82it/s]

Gaps (ex-reports):  95%|█████████▌| 6878/7211 [30:02<01:08,  4.84it/s]

Gaps (ex-reports):  95%|█████████▌| 6879/7211 [30:02<01:07,  4.90it/s]

Gaps (ex-reports):  95%|█████████▌| 6880/7211 [30:02<01:07,  4.87it/s]

Gaps (ex-reports):  95%|█████████▌| 6881/7211 [30:02<01:07,  4.89it/s]

Gaps (ex-reports):  95%|█████████▌| 6882/7211 [30:02<01:06,  4.98it/s]

Gaps (ex-reports):  95%|█████████▌| 6883/7211 [30:03<01:06,  4.91it/s]

Gaps (ex-reports):  95%|█████████▌| 6884/7211 [30:03<01:06,  4.89it/s]

Gaps (ex-reports):  95%|█████████▌| 6885/7211 [30:03<01:05,  4.96it/s]

Gaps (ex-reports):  95%|█████████▌| 6886/7211 [30:03<01:05,  4.94it/s]

Gaps (ex-reports):  96%|█████████▌| 6887/7211 [30:03<01:04,  5.01it/s]

Gaps (ex-reports):  96%|█████████▌| 6888/7211 [30:04<01:05,  4.94it/s]

Gaps (ex-reports):  96%|█████████▌| 6889/7211 [30:04<01:05,  4.94it/s]

Gaps (ex-reports):  96%|█████████▌| 6890/7211 [30:04<01:05,  4.90it/s]

Gaps (ex-reports):  96%|█████████▌| 6891/7211 [30:04<01:04,  4.97it/s]

Gaps (ex-reports):  96%|█████████▌| 6892/7211 [30:04<01:03,  5.05it/s]

Gaps (ex-reports):  96%|█████████▌| 6893/7211 [30:05<01:03,  5.03it/s]

Gaps (ex-reports):  96%|█████████▌| 6894/7211 [30:05<01:03,  5.01it/s]

Gaps (ex-reports):  96%|█████████▌| 6895/7211 [30:05<01:02,  5.05it/s]

Gaps (ex-reports):  96%|█████████▌| 6896/7211 [30:05<01:01,  5.13it/s]

Gaps (ex-reports):  96%|█████████▌| 6897/7211 [30:05<01:02,  5.03it/s]

Gaps (ex-reports):  96%|█████████▌| 6898/7211 [30:06<01:02,  5.05it/s]

Gaps (ex-reports):  96%|█████████▌| 6899/7211 [30:06<01:02,  5.01it/s]

Gaps (ex-reports):  96%|█████████▌| 6900/7211 [30:06<01:01,  5.03it/s]

Gaps (ex-reports):  96%|█████████▌| 6901/7211 [30:06<01:02,  4.97it/s]

Gaps (ex-reports):  96%|█████████▌| 6902/7211 [30:06<01:03,  4.89it/s]

Gaps (ex-reports):  96%|█████████▌| 6903/7211 [30:07<01:03,  4.86it/s]

Gaps (ex-reports):  96%|█████████▌| 6904/7211 [30:07<01:02,  4.89it/s]

Gaps (ex-reports):  96%|█████████▌| 6905/7211 [30:07<01:02,  4.91it/s]

Gaps (ex-reports):  96%|█████████▌| 6906/7211 [30:07<01:01,  4.95it/s]

Gaps (ex-reports):  96%|█████████▌| 6907/7211 [30:07<01:00,  5.02it/s]

Gaps (ex-reports):  96%|█████████▌| 6908/7211 [30:08<01:00,  5.05it/s]

Gaps (ex-reports):  96%|█████████▌| 6909/7211 [30:08<00:59,  5.05it/s]

Gaps (ex-reports):  96%|█████████▌| 6910/7211 [30:08<01:00,  4.97it/s]

Gaps (ex-reports):  96%|█████████▌| 6911/7211 [30:08<01:00,  4.99it/s]

Gaps (ex-reports):  96%|█████████▌| 6912/7211 [30:09<01:01,  4.85it/s]

Gaps (ex-reports):  96%|█████████▌| 6913/7211 [30:09<01:00,  4.90it/s]

Gaps (ex-reports):  96%|█████████▌| 6914/7211 [30:09<01:01,  4.85it/s]

Gaps (ex-reports):  96%|█████████▌| 6915/7211 [30:09<01:00,  4.91it/s]

Gaps (ex-reports):  96%|█████████▌| 6916/7211 [30:09<01:00,  4.85it/s]

Gaps (ex-reports):  96%|█████████▌| 6917/7211 [30:10<00:59,  4.93it/s]

Gaps (ex-reports):  96%|█████████▌| 6918/7211 [30:12<04:26,  1.10it/s]

Gaps (ex-reports):  96%|█████████▌| 6919/7211 [30:12<03:23,  1.44it/s]

Gaps (ex-reports):  96%|█████████▌| 6920/7211 [30:12<02:38,  1.83it/s]

Gaps (ex-reports):  96%|█████████▌| 6921/7211 [30:13<02:07,  2.27it/s]

Gaps (ex-reports):  96%|█████████▌| 6922/7211 [30:13<01:47,  2.68it/s]

Gaps (ex-reports):  96%|█████████▌| 6923/7211 [30:13<01:33,  3.09it/s]

Gaps (ex-reports):  96%|█████████▌| 6924/7211 [30:13<01:22,  3.49it/s]

Gaps (ex-reports):  96%|█████████▌| 6925/7211 [30:13<01:14,  3.84it/s]

Gaps (ex-reports):  96%|█████████▌| 6926/7211 [30:14<01:09,  4.11it/s]

Gaps (ex-reports):  96%|█████████▌| 6927/7211 [30:14<01:06,  4.29it/s]

Gaps (ex-reports):  96%|█████████▌| 6928/7211 [30:14<01:03,  4.43it/s]

Gaps (ex-reports):  96%|█████████▌| 6929/7211 [30:14<01:03,  4.47it/s]

Gaps (ex-reports):  96%|█████████▌| 6930/7211 [30:15<01:01,  4.55it/s]

Gaps (ex-reports):  96%|█████████▌| 6931/7211 [30:15<01:00,  4.64it/s]

Gaps (ex-reports):  96%|█████████▌| 6932/7211 [30:15<00:58,  4.78it/s]

Gaps (ex-reports):  96%|█████████▌| 6933/7211 [30:15<00:57,  4.84it/s]

Gaps (ex-reports):  96%|█████████▌| 6934/7211 [30:15<00:56,  4.88it/s]

Gaps (ex-reports):  96%|█████████▌| 6935/7211 [30:16<00:55,  4.95it/s]

Gaps (ex-reports):  96%|█████████▌| 6936/7211 [30:16<00:56,  4.89it/s]

Gaps (ex-reports):  96%|█████████▌| 6937/7211 [30:16<00:55,  4.92it/s]

Gaps (ex-reports):  96%|█████████▌| 6938/7211 [30:16<00:55,  4.92it/s]

Gaps (ex-reports):  96%|█████████▌| 6939/7211 [30:16<00:54,  5.02it/s]

Gaps (ex-reports):  96%|█████████▌| 6940/7211 [30:17<00:54,  4.99it/s]

Gaps (ex-reports):  96%|█████████▋| 6941/7211 [30:17<00:53,  5.09it/s]

Gaps (ex-reports):  96%|█████████▋| 6942/7211 [30:17<00:54,  4.93it/s]

Gaps (ex-reports):  96%|█████████▋| 6943/7211 [30:17<00:54,  4.90it/s]

Gaps (ex-reports):  96%|█████████▋| 6944/7211 [30:17<00:53,  4.98it/s]

Gaps (ex-reports):  96%|█████████▋| 6945/7211 [30:18<00:53,  5.00it/s]

Gaps (ex-reports):  96%|█████████▋| 6946/7211 [30:18<00:53,  4.97it/s]

Gaps (ex-reports):  96%|█████████▋| 6947/7211 [30:18<00:52,  5.01it/s]

Gaps (ex-reports):  96%|█████████▋| 6948/7211 [30:18<00:52,  4.97it/s]

Gaps (ex-reports):  96%|█████████▋| 6949/7211 [30:18<00:52,  4.95it/s]

Gaps (ex-reports):  96%|█████████▋| 6950/7211 [30:19<00:52,  4.97it/s]

Gaps (ex-reports):  96%|█████████▋| 6951/7211 [30:19<00:52,  4.96it/s]

Gaps (ex-reports):  96%|█████████▋| 6952/7211 [30:19<00:52,  4.92it/s]

Gaps (ex-reports):  96%|█████████▋| 6953/7211 [30:19<00:51,  4.98it/s]

Gaps (ex-reports):  96%|█████████▋| 6954/7211 [30:19<00:51,  4.96it/s]

Gaps (ex-reports):  96%|█████████▋| 6955/7211 [30:20<00:51,  4.99it/s]

Gaps (ex-reports):  96%|█████████▋| 6956/7211 [30:23<05:21,  1.26s/it]

Gaps (ex-reports):  96%|█████████▋| 6957/7211 [30:24<04:00,  1.06it/s]

Gaps (ex-reports):  96%|█████████▋| 6958/7211 [30:24<03:03,  1.38it/s]

Gaps (ex-reports):  97%|█████████▋| 6959/7211 [30:24<02:22,  1.77it/s]

Gaps (ex-reports):  97%|█████████▋| 6960/7211 [30:24<01:56,  2.16it/s]

Gaps (ex-reports):  97%|█████████▋| 6961/7211 [30:24<01:35,  2.61it/s]

Gaps (ex-reports):  97%|█████████▋| 6962/7211 [30:25<01:22,  3.00it/s]

Gaps (ex-reports):  97%|█████████▋| 6963/7211 [30:25<01:13,  3.39it/s]

Gaps (ex-reports):  97%|█████████▋| 6964/7211 [30:25<01:06,  3.74it/s]

Gaps (ex-reports):  97%|█████████▋| 6965/7211 [30:25<01:00,  4.04it/s]

Gaps (ex-reports):  97%|█████████▋| 6966/7211 [30:25<00:58,  4.21it/s]

Gaps (ex-reports):  97%|█████████▋| 6967/7211 [30:26<00:55,  4.39it/s]

Gaps (ex-reports):  97%|█████████▋| 6968/7211 [30:26<00:53,  4.52it/s]

Gaps (ex-reports):  97%|█████████▋| 6969/7211 [30:26<00:51,  4.67it/s]

Gaps (ex-reports):  97%|█████████▋| 6970/7211 [30:26<00:50,  4.74it/s]

Gaps (ex-reports):  97%|█████████▋| 6971/7211 [30:26<00:49,  4.87it/s]

Gaps (ex-reports):  97%|█████████▋| 6972/7211 [30:27<00:48,  4.97it/s]

Gaps (ex-reports):  97%|█████████▋| 6973/7211 [30:27<00:47,  5.03it/s]

Gaps (ex-reports):  97%|█████████▋| 6974/7211 [30:27<00:46,  5.08it/s]

Gaps (ex-reports):  97%|█████████▋| 6975/7211 [30:27<00:47,  5.01it/s]

Gaps (ex-reports):  97%|█████████▋| 6976/7211 [30:27<00:46,  5.02it/s]

Gaps (ex-reports):  97%|█████████▋| 6977/7211 [30:28<00:47,  4.93it/s]

Gaps (ex-reports):  97%|█████████▋| 6978/7211 [30:28<00:47,  4.89it/s]

Gaps (ex-reports):  97%|█████████▋| 6979/7211 [30:28<00:48,  4.79it/s]

Gaps (ex-reports):  97%|█████████▋| 6980/7211 [30:32<04:40,  1.22s/it]

Gaps (ex-reports):  97%|█████████▋| 6981/7211 [30:32<03:30,  1.09it/s]

Gaps (ex-reports):  97%|█████████▋| 6982/7211 [30:32<02:40,  1.43it/s]

Gaps (ex-reports):  97%|█████████▋| 6983/7211 [30:32<02:06,  1.80it/s]

Gaps (ex-reports):  97%|█████████▋| 6984/7211 [30:32<01:42,  2.21it/s]

Gaps (ex-reports):  97%|█████████▋| 6985/7211 [30:33<01:25,  2.64it/s]

Gaps (ex-reports):  97%|█████████▋| 6986/7211 [30:33<01:13,  3.06it/s]

Gaps (ex-reports):  97%|█████████▋| 6987/7211 [30:33<01:04,  3.45it/s]

Gaps (ex-reports):  97%|█████████▋| 6988/7211 [30:33<00:59,  3.75it/s]

Gaps (ex-reports):  97%|█████████▋| 6989/7211 [30:33<00:54,  4.05it/s]

Gaps (ex-reports):  97%|█████████▋| 6990/7211 [30:34<00:51,  4.32it/s]

Gaps (ex-reports):  97%|█████████▋| 6991/7211 [30:34<00:49,  4.41it/s]

Gaps (ex-reports):  97%|█████████▋| 6992/7211 [30:34<00:48,  4.53it/s]

Gaps (ex-reports):  97%|█████████▋| 6993/7211 [30:34<00:47,  4.56it/s]

Gaps (ex-reports):  97%|█████████▋| 6994/7211 [30:34<00:45,  4.72it/s]

Gaps (ex-reports):  97%|█████████▋| 6995/7211 [30:35<00:45,  4.78it/s]

Gaps (ex-reports):  97%|█████████▋| 6996/7211 [30:35<00:45,  4.77it/s]

Gaps (ex-reports):  97%|█████████▋| 6997/7211 [30:35<00:43,  4.86it/s]

Gaps (ex-reports):  97%|█████████▋| 6998/7211 [30:35<00:43,  4.86it/s]

Gaps (ex-reports):  97%|█████████▋| 6999/7211 [30:35<00:44,  4.81it/s]

Gaps (ex-reports):  97%|█████████▋| 7000/7211 [30:36<00:43,  4.85it/s]

Gaps (ex-reports):  97%|█████████▋| 7001/7211 [30:36<00:43,  4.83it/s]

Gaps (ex-reports):  97%|█████████▋| 7002/7211 [30:40<04:34,  1.31s/it]

Gaps (ex-reports):  97%|█████████▋| 7003/7211 [30:40<03:23,  1.02it/s]

Gaps (ex-reports):  97%|█████████▋| 7004/7211 [30:40<02:35,  1.34it/s]

Gaps (ex-reports):  97%|█████████▋| 7005/7211 [30:40<02:00,  1.71it/s]

Gaps (ex-reports):  97%|█████████▋| 7006/7211 [30:41<01:37,  2.10it/s]

Gaps (ex-reports):  97%|█████████▋| 7007/7211 [30:41<01:21,  2.51it/s]

Gaps (ex-reports):  97%|█████████▋| 7008/7211 [30:41<01:09,  2.91it/s]

Gaps (ex-reports):  97%|█████████▋| 7009/7211 [30:41<01:00,  3.35it/s]

Gaps (ex-reports):  97%|█████████▋| 7010/7211 [30:41<00:54,  3.71it/s]

Gaps (ex-reports):  97%|█████████▋| 7011/7211 [30:42<00:50,  3.97it/s]

Gaps (ex-reports):  97%|█████████▋| 7012/7211 [30:42<00:46,  4.25it/s]

Gaps (ex-reports):  97%|█████████▋| 7013/7211 [30:42<00:44,  4.43it/s]

Gaps (ex-reports):  97%|█████████▋| 7014/7211 [30:42<00:43,  4.50it/s]

Gaps (ex-reports):  97%|█████████▋| 7015/7211 [30:42<00:42,  4.64it/s]

Gaps (ex-reports):  97%|█████████▋| 7016/7211 [30:43<00:41,  4.70it/s]

Gaps (ex-reports):  97%|█████████▋| 7017/7211 [30:43<00:40,  4.73it/s]

Gaps (ex-reports):  97%|█████████▋| 7018/7211 [30:43<00:41,  4.60it/s]

Gaps (ex-reports):  97%|█████████▋| 7019/7211 [30:43<00:41,  4.66it/s]

Gaps (ex-reports):  97%|█████████▋| 7020/7211 [30:44<00:40,  4.70it/s]

Gaps (ex-reports):  97%|█████████▋| 7021/7211 [30:44<00:39,  4.83it/s]

Gaps (ex-reports):  97%|█████████▋| 7022/7211 [30:44<00:39,  4.85it/s]

Gaps (ex-reports):  97%|█████████▋| 7023/7211 [30:44<00:38,  4.95it/s]

Gaps (ex-reports):  97%|█████████▋| 7024/7211 [30:44<00:37,  4.92it/s]

Gaps (ex-reports):  97%|█████████▋| 7025/7211 [30:45<00:37,  4.93it/s]

Gaps (ex-reports):  97%|█████████▋| 7026/7211 [30:45<00:36,  5.03it/s]

Gaps (ex-reports):  97%|█████████▋| 7027/7211 [30:45<00:37,  4.91it/s]

Gaps (ex-reports):  97%|█████████▋| 7028/7211 [30:45<00:36,  4.98it/s]

Gaps (ex-reports):  97%|█████████▋| 7029/7211 [30:45<00:37,  4.86it/s]

Gaps (ex-reports):  97%|█████████▋| 7030/7211 [30:46<00:38,  4.71it/s]

Gaps (ex-reports):  98%|█████████▊| 7031/7211 [30:46<00:37,  4.76it/s]

Gaps (ex-reports):  98%|█████████▊| 7032/7211 [30:46<00:37,  4.76it/s]

Gaps (ex-reports):  98%|█████████▊| 7033/7211 [30:46<00:36,  4.86it/s]

Gaps (ex-reports):  98%|█████████▊| 7034/7211 [30:46<00:36,  4.82it/s]

Gaps (ex-reports):  98%|█████████▊| 7035/7211 [30:47<00:36,  4.84it/s]

Gaps (ex-reports):  98%|█████████▊| 7036/7211 [30:47<00:36,  4.85it/s]

Gaps (ex-reports):  98%|█████████▊| 7037/7211 [30:47<00:38,  4.54it/s]

Gaps (ex-reports):  98%|█████████▊| 7038/7211 [30:47<00:36,  4.69it/s]

Gaps (ex-reports):  98%|█████████▊| 7039/7211 [30:47<00:35,  4.85it/s]

Gaps (ex-reports):  98%|█████████▊| 7040/7211 [30:48<00:35,  4.84it/s]

Gaps (ex-reports):  98%|█████████▊| 7041/7211 [30:48<00:34,  4.88it/s]

Gaps (ex-reports):  98%|█████████▊| 7042/7211 [30:48<00:34,  4.95it/s]

Gaps (ex-reports):  98%|█████████▊| 7043/7211 [30:48<00:33,  4.99it/s]

Gaps (ex-reports):  98%|█████████▊| 7044/7211 [30:48<00:33,  4.95it/s]

Gaps (ex-reports):  98%|█████████▊| 7045/7211 [30:49<00:33,  5.00it/s]

Gaps (ex-reports):  98%|█████████▊| 7046/7211 [30:49<00:33,  4.96it/s]

Gaps (ex-reports):  98%|█████████▊| 7047/7211 [30:49<00:33,  4.90it/s]

Gaps (ex-reports):  98%|█████████▊| 7048/7211 [30:49<00:33,  4.89it/s]

Gaps (ex-reports):  98%|█████████▊| 7049/7211 [30:49<00:32,  4.98it/s]

Gaps (ex-reports):  98%|█████████▊| 7050/7211 [30:50<00:31,  5.03it/s]

Gaps (ex-reports):  98%|█████████▊| 7051/7211 [30:50<00:31,  5.08it/s]

Gaps (ex-reports):  98%|█████████▊| 7052/7211 [30:50<00:31,  5.08it/s]

Gaps (ex-reports):  98%|█████████▊| 7053/7211 [30:50<00:31,  5.05it/s]

Gaps (ex-reports):  98%|█████████▊| 7054/7211 [30:50<00:31,  5.04it/s]

Gaps (ex-reports):  98%|█████████▊| 7055/7211 [30:51<00:31,  4.98it/s]

Gaps (ex-reports):  98%|█████████▊| 7056/7211 [30:51<00:30,  5.06it/s]

Gaps (ex-reports):  98%|█████████▊| 7057/7211 [30:51<00:31,  4.89it/s]

Gaps (ex-reports):  98%|█████████▊| 7058/7211 [30:51<00:30,  4.96it/s]

Gaps (ex-reports):  98%|█████████▊| 7059/7211 [30:51<00:30,  5.05it/s]

Gaps (ex-reports):  98%|█████████▊| 7060/7211 [30:52<00:29,  5.06it/s]

Gaps (ex-reports):  98%|█████████▊| 7061/7211 [30:52<00:30,  4.98it/s]

Gaps (ex-reports):  98%|█████████▊| 7062/7211 [30:52<00:30,  4.85it/s]

Gaps (ex-reports):  98%|█████████▊| 7063/7211 [30:52<00:30,  4.89it/s]

Gaps (ex-reports):  98%|█████████▊| 7064/7211 [30:52<00:30,  4.83it/s]

Gaps (ex-reports):  98%|█████████▊| 7065/7211 [30:53<00:30,  4.85it/s]

Gaps (ex-reports):  98%|█████████▊| 7066/7211 [30:53<00:30,  4.83it/s]

Gaps (ex-reports):  98%|█████████▊| 7067/7211 [30:53<00:30,  4.78it/s]

Gaps (ex-reports):  98%|█████████▊| 7068/7211 [30:53<00:29,  4.79it/s]

Gaps (ex-reports):  98%|█████████▊| 7069/7211 [30:54<00:29,  4.82it/s]

Gaps (ex-reports):  98%|█████████▊| 7070/7211 [30:54<00:29,  4.85it/s]

Gaps (ex-reports):  98%|█████████▊| 7071/7211 [30:54<00:28,  4.86it/s]

Gaps (ex-reports):  98%|█████████▊| 7072/7211 [30:54<00:28,  4.86it/s]

Gaps (ex-reports):  98%|█████████▊| 7073/7211 [30:54<00:28,  4.81it/s]

Gaps (ex-reports):  98%|█████████▊| 7074/7211 [30:55<00:28,  4.85it/s]

Gaps (ex-reports):  98%|█████████▊| 7075/7211 [30:55<00:27,  4.96it/s]

Gaps (ex-reports):  98%|█████████▊| 7076/7211 [30:55<00:27,  4.97it/s]

Gaps (ex-reports):  98%|█████████▊| 7077/7211 [30:55<00:27,  4.94it/s]

Gaps (ex-reports):  98%|█████████▊| 7078/7211 [30:55<00:27,  4.89it/s]

Gaps (ex-reports):  98%|█████████▊| 7079/7211 [30:56<00:26,  4.95it/s]

Gaps (ex-reports):  98%|█████████▊| 7080/7211 [30:56<00:26,  4.86it/s]

Gaps (ex-reports):  98%|█████████▊| 7081/7211 [30:56<00:27,  4.78it/s]

Gaps (ex-reports):  98%|█████████▊| 7082/7211 [30:56<00:29,  4.31it/s]

Gaps (ex-reports):  98%|█████████▊| 7083/7211 [30:57<00:31,  4.08it/s]

Gaps (ex-reports):  98%|█████████▊| 7084/7211 [30:57<00:31,  3.98it/s]

Gaps (ex-reports):  98%|█████████▊| 7085/7211 [30:57<00:31,  4.04it/s]

Gaps (ex-reports):  98%|█████████▊| 7086/7211 [30:57<00:29,  4.30it/s]

Gaps (ex-reports):  98%|█████████▊| 7087/7211 [30:57<00:27,  4.48it/s]

Gaps (ex-reports):  98%|█████████▊| 7088/7211 [30:58<00:26,  4.63it/s]

Gaps (ex-reports):  98%|█████████▊| 7089/7211 [30:58<00:25,  4.72it/s]

Gaps (ex-reports):  98%|█████████▊| 7090/7211 [30:58<00:24,  4.87it/s]

Gaps (ex-reports):  98%|█████████▊| 7091/7211 [30:58<00:24,  4.94it/s]

Gaps (ex-reports):  98%|█████████▊| 7092/7211 [30:58<00:24,  4.87it/s]

Gaps (ex-reports):  98%|█████████▊| 7093/7211 [30:59<00:24,  4.89it/s]

Gaps (ex-reports):  98%|█████████▊| 7094/7211 [30:59<00:23,  4.97it/s]

Gaps (ex-reports):  98%|█████████▊| 7095/7211 [30:59<00:23,  5.04it/s]

Gaps (ex-reports):  98%|█████████▊| 7096/7211 [30:59<00:22,  5.08it/s]

Gaps (ex-reports):  98%|█████████▊| 7097/7211 [30:59<00:22,  4.98it/s]

Gaps (ex-reports):  98%|█████████▊| 7098/7211 [31:00<00:22,  4.94it/s]

Gaps (ex-reports):  98%|█████████▊| 7099/7211 [31:00<00:22,  5.00it/s]

Gaps (ex-reports):  98%|█████████▊| 7100/7211 [31:00<00:22,  4.98it/s]

Gaps (ex-reports):  98%|█████████▊| 7101/7211 [31:00<00:21,  5.02it/s]

Gaps (ex-reports):  98%|█████████▊| 7102/7211 [31:00<00:21,  5.02it/s]

Gaps (ex-reports):  99%|█████████▊| 7103/7211 [31:01<00:21,  5.00it/s]

Gaps (ex-reports):  99%|█████████▊| 7104/7211 [31:01<00:21,  4.93it/s]

Gaps (ex-reports):  99%|█████████▊| 7105/7211 [31:01<00:21,  4.86it/s]

Gaps (ex-reports):  99%|█████████▊| 7106/7211 [31:01<00:21,  4.86it/s]

Gaps (ex-reports):  99%|█████████▊| 7107/7211 [31:01<00:21,  4.81it/s]

Gaps (ex-reports):  99%|█████████▊| 7108/7211 [31:02<00:21,  4.83it/s]

Gaps (ex-reports):  99%|█████████▊| 7109/7211 [31:02<00:20,  4.90it/s]

Gaps (ex-reports):  99%|█████████▊| 7110/7211 [31:02<00:20,  4.89it/s]

Gaps (ex-reports):  99%|█████████▊| 7111/7211 [31:02<00:20,  4.90it/s]

Gaps (ex-reports):  99%|█████████▊| 7112/7211 [31:03<00:20,  4.90it/s]

Gaps (ex-reports):  99%|█████████▊| 7113/7211 [31:03<00:19,  5.01it/s]

Gaps (ex-reports):  99%|█████████▊| 7114/7211 [31:03<00:19,  5.00it/s]

Gaps (ex-reports):  99%|█████████▊| 7115/7211 [31:03<00:19,  4.92it/s]

Gaps (ex-reports):  99%|█████████▊| 7116/7211 [31:03<00:19,  4.87it/s]

Gaps (ex-reports):  99%|█████████▊| 7117/7211 [31:04<00:19,  4.91it/s]

Gaps (ex-reports):  99%|█████████▊| 7118/7211 [31:04<00:19,  4.89it/s]

Gaps (ex-reports):  99%|█████████▊| 7119/7211 [31:04<00:19,  4.82it/s]

Gaps (ex-reports):  99%|█████████▊| 7120/7211 [31:04<00:19,  4.75it/s]

Gaps (ex-reports):  99%|█████████▉| 7121/7211 [31:04<00:18,  4.84it/s]

Gaps (ex-reports):  99%|█████████▉| 7122/7211 [31:05<00:18,  4.69it/s]

Gaps (ex-reports):  99%|█████████▉| 7123/7211 [31:05<00:18,  4.73it/s]

Gaps (ex-reports):  99%|█████████▉| 7124/7211 [31:05<00:17,  4.90it/s]

Gaps (ex-reports):  99%|█████████▉| 7125/7211 [31:05<00:17,  4.96it/s]

Gaps (ex-reports):  99%|█████████▉| 7126/7211 [31:05<00:16,  5.07it/s]

Gaps (ex-reports):  99%|█████████▉| 7127/7211 [31:06<00:16,  5.01it/s]

Gaps (ex-reports):  99%|█████████▉| 7128/7211 [31:06<00:16,  4.98it/s]

Gaps (ex-reports):  99%|█████████▉| 7129/7211 [31:06<00:16,  5.02it/s]

Gaps (ex-reports):  99%|█████████▉| 7130/7211 [31:06<00:16,  4.96it/s]

Gaps (ex-reports):  99%|█████████▉| 7131/7211 [31:06<00:19,  4.21it/s]

Gaps (ex-reports):  99%|█████████▉| 7132/7211 [31:07<00:17,  4.41it/s]

Gaps (ex-reports):  99%|█████████▉| 7133/7211 [31:07<00:17,  4.49it/s]

Gaps (ex-reports):  99%|█████████▉| 7134/7211 [31:07<00:17,  4.52it/s]

Gaps (ex-reports):  99%|█████████▉| 7135/7211 [31:07<00:16,  4.59it/s]

Gaps (ex-reports):  99%|█████████▉| 7136/7211 [31:08<00:15,  4.69it/s]

Gaps (ex-reports):  99%|█████████▉| 7137/7211 [31:08<00:15,  4.67it/s]

Gaps (ex-reports):  99%|█████████▉| 7138/7211 [31:08<00:15,  4.79it/s]

Gaps (ex-reports):  99%|█████████▉| 7139/7211 [31:08<00:14,  4.96it/s]

Gaps (ex-reports):  99%|█████████▉| 7140/7211 [31:08<00:14,  4.91it/s]

Gaps (ex-reports):  99%|█████████▉| 7141/7211 [31:09<00:14,  4.92it/s]

Gaps (ex-reports):  99%|█████████▉| 7142/7211 [31:09<00:14,  4.86it/s]

Gaps (ex-reports):  99%|█████████▉| 7143/7211 [31:09<00:13,  4.95it/s]

Gaps (ex-reports):  99%|█████████▉| 7144/7211 [31:09<00:13,  4.87it/s]

Gaps (ex-reports):  99%|█████████▉| 7145/7211 [31:09<00:13,  4.85it/s]

Gaps (ex-reports):  99%|█████████▉| 7146/7211 [31:10<00:13,  4.86it/s]

Gaps (ex-reports):  99%|█████████▉| 7147/7211 [31:10<00:13,  4.86it/s]

Gaps (ex-reports):  99%|█████████▉| 7148/7211 [31:10<00:13,  4.83it/s]

Gaps (ex-reports):  99%|█████████▉| 7149/7211 [31:10<00:12,  4.83it/s]

Gaps (ex-reports):  99%|█████████▉| 7150/7211 [31:10<00:12,  4.84it/s]

Gaps (ex-reports):  99%|█████████▉| 7151/7211 [31:11<00:12,  4.84it/s]

Gaps (ex-reports):  99%|█████████▉| 7152/7211 [31:11<00:12,  4.78it/s]

Gaps (ex-reports):  99%|█████████▉| 7153/7211 [31:11<00:11,  4.89it/s]

Gaps (ex-reports):  99%|█████████▉| 7154/7211 [31:11<00:11,  4.96it/s]

Gaps (ex-reports):  99%|█████████▉| 7155/7211 [31:11<00:11,  4.94it/s]

Gaps (ex-reports):  99%|█████████▉| 7156/7211 [31:12<00:10,  5.01it/s]

Gaps (ex-reports):  99%|█████████▉| 7157/7211 [31:12<00:11,  4.88it/s]

Gaps (ex-reports):  99%|█████████▉| 7158/7211 [31:12<00:10,  4.91it/s]

Gaps (ex-reports):  99%|█████████▉| 7159/7211 [31:12<00:10,  4.91it/s]

Gaps (ex-reports):  99%|█████████▉| 7160/7211 [31:12<00:10,  4.98it/s]

Gaps (ex-reports):  99%|█████████▉| 7161/7211 [31:13<00:10,  4.93it/s]

Gaps (ex-reports):  99%|█████████▉| 7162/7211 [31:13<00:10,  4.87it/s]

Gaps (ex-reports):  99%|█████████▉| 7163/7211 [31:13<00:09,  4.99it/s]

Gaps (ex-reports):  99%|█████████▉| 7164/7211 [31:13<00:09,  5.04it/s]

Gaps (ex-reports):  99%|█████████▉| 7165/7211 [31:13<00:09,  4.85it/s]

Gaps (ex-reports):  99%|█████████▉| 7166/7211 [31:14<00:09,  4.88it/s]

Gaps (ex-reports):  99%|█████████▉| 7167/7211 [31:14<00:08,  4.94it/s]

Gaps (ex-reports):  99%|█████████▉| 7168/7211 [31:14<00:08,  4.93it/s]

Gaps (ex-reports):  99%|█████████▉| 7169/7211 [31:14<00:08,  4.90it/s]

Gaps (ex-reports):  99%|█████████▉| 7170/7211 [31:14<00:08,  4.98it/s]

Gaps (ex-reports):  99%|█████████▉| 7171/7211 [31:15<00:07,  5.02it/s]

Gaps (ex-reports):  99%|█████████▉| 7172/7211 [31:15<00:07,  4.92it/s]

Gaps (ex-reports):  99%|█████████▉| 7173/7211 [31:15<00:07,  4.92it/s]

Gaps (ex-reports):  99%|█████████▉| 7174/7211 [31:15<00:07,  4.96it/s]

Gaps (ex-reports): 100%|█████████▉| 7175/7211 [31:15<00:07,  4.87it/s]

Gaps (ex-reports): 100%|█████████▉| 7176/7211 [31:16<00:07,  4.92it/s]

Gaps (ex-reports): 100%|█████████▉| 7177/7211 [31:16<00:06,  4.94it/s]

Gaps (ex-reports): 100%|█████████▉| 7178/7211 [31:16<00:06,  4.94it/s]

Gaps (ex-reports): 100%|█████████▉| 7179/7211 [31:16<00:06,  4.89it/s]

Gaps (ex-reports): 100%|█████████▉| 7180/7211 [31:16<00:06,  4.92it/s]

Gaps (ex-reports): 100%|█████████▉| 7181/7211 [31:17<00:06,  4.97it/s]

Gaps (ex-reports): 100%|█████████▉| 7182/7211 [31:17<00:05,  5.02it/s]

Gaps (ex-reports): 100%|█████████▉| 7183/7211 [31:17<00:05,  5.02it/s]

Gaps (ex-reports): 100%|█████████▉| 7184/7211 [31:17<00:05,  4.98it/s]

Gaps (ex-reports): 100%|█████████▉| 7185/7211 [31:17<00:05,  5.12it/s]

Gaps (ex-reports): 100%|█████████▉| 7186/7211 [31:18<00:04,  5.03it/s]

Gaps (ex-reports): 100%|█████████▉| 7187/7211 [31:18<00:04,  5.06it/s]

Gaps (ex-reports): 100%|█████████▉| 7188/7211 [31:18<00:04,  5.08it/s]

Gaps (ex-reports): 100%|█████████▉| 7189/7211 [31:18<00:04,  5.04it/s]

Gaps (ex-reports): 100%|█████████▉| 7190/7211 [31:18<00:04,  4.98it/s]

Gaps (ex-reports): 100%|█████████▉| 7191/7211 [31:19<00:03,  5.02it/s]

Gaps (ex-reports): 100%|█████████▉| 7192/7211 [31:19<00:03,  4.99it/s]

Gaps (ex-reports): 100%|█████████▉| 7193/7211 [31:19<00:03,  4.92it/s]

Gaps (ex-reports): 100%|█████████▉| 7194/7211 [31:19<00:03,  5.00it/s]

Gaps (ex-reports): 100%|█████████▉| 7195/7211 [31:19<00:03,  4.94it/s]

Gaps (ex-reports): 100%|█████████▉| 7196/7211 [31:20<00:03,  4.93it/s]

Gaps (ex-reports): 100%|█████████▉| 7197/7211 [31:20<00:02,  4.85it/s]

Gaps (ex-reports): 100%|█████████▉| 7198/7211 [31:20<00:02,  4.82it/s]

Gaps (ex-reports): 100%|█████████▉| 7199/7211 [31:20<00:02,  4.78it/s]

Gaps (ex-reports): 100%|█████████▉| 7200/7211 [31:21<00:02,  4.84it/s]

Gaps (ex-reports): 100%|█████████▉| 7201/7211 [31:21<00:02,  4.84it/s]

Gaps (ex-reports): 100%|█████████▉| 7202/7211 [31:21<00:01,  4.92it/s]

Gaps (ex-reports): 100%|█████████▉| 7203/7211 [31:21<00:01,  4.92it/s]

Gaps (ex-reports): 100%|█████████▉| 7204/7211 [31:21<00:01,  4.79it/s]

Gaps (ex-reports): 100%|█████████▉| 7205/7211 [31:22<00:01,  4.86it/s]

Gaps (ex-reports): 100%|█████████▉| 7206/7211 [31:22<00:01,  4.87it/s]

Gaps (ex-reports): 100%|█████████▉| 7207/7211 [31:22<00:00,  4.86it/s]

Gaps (ex-reports): 100%|█████████▉| 7208/7211 [31:22<00:00,  4.94it/s]

Gaps (ex-reports): 100%|█████████▉| 7209/7211 [31:22<00:00,  4.93it/s]

Gaps (ex-reports): 100%|█████████▉| 7210/7211 [31:23<00:00,  4.95it/s]

Gaps (ex-reports): 100%|██████████| 7211/7211 [31:23<00:00,  4.88it/s]

Gaps (ex-reports): 100%|██████████| 7211/7211 [31:23<00:00,  3.83it/s]

Rows in gaps (without report days): 444079

In [45]:
sigma_daily = add_rolling_sigma_cap(
    df=df_gaps_all,
    value_col="gap",
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.95,
    min_periods=20,
)

sigma_col = "gap_sigma_20d_cap"

# Use latest available rolling sigma per ticker
std_by_ticker = (
    sigma_daily.dropna(subset=[sigma_col])
    .sort_values(["ticker", "date"])
    .groupby("ticker", as_index=False)
    .tail(1)[["ticker", sigma_col]]
    .rename(columns={sigma_col: "sigma"})
    .reset_index(drop=True)
)

print("Tickers with sigma:", len(std_by_ticker))
std_by_ticker.head()

Tickers with sigma: 7074

  ticker     sigma
0      A  0.923970
1     AA  1.817540
2   AAAU  1.051167
3   AACG  2.756975
4    AAL  1.716729

In [46]:
std_by_ticker

     ticker     sigma
0         A  0.923970
1        AA  1.817540
2      AAAU  1.051167
3      AACG  2.756975
4       AAL  1.716729
...     ...       ...
7069   ZVOL  0.475506
7070   ZVRA  0.937181
7071    ZWS  0.720446
7072   ZYBT  3.070491
7073   ZYME  0.837959

[7074 rows x 2 columns]

In [47]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    # знайдемо колонки гнучко
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"]  = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker зі скріна
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%" або "pct_vs_prev_close"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet та зберігає новий файл.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    # вихідний шлях
    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    # підготовка мапи sigma
    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)

    # запис у тимчасовий файл → атомарна заміна
    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}")
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(sigma_map, on="ticker", how="left", validate="m:1")

        # розташувати 'sigma' за бажанням
        if insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("sigma")
            idx = cols.index(insert_before)
            cols = cols[:idx] + ["sigma"] + cols[idx:]
            merged = merged[cols]
        else:
            base_cols = [c for c in merged.columns if c != "sigma"]
            merged = merged[base_cols + ["sigma"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # атомарна заміна
    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [48]:
# std_by_ticker columns: ['ticker', 'sigma']
sigma_out_path = add_sigma_by_ticker_to_parquet(
    base_path=str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    sigma_df=std_by_ticker,
    insert_before=None,
)

# Validation: output parquet must contain sigma matching std_by_ticker
check_df = pd.read_parquet(sigma_out_path, columns=["ticker", "sigma"])
if "sigma" not in check_df.columns:
    raise KeyError("Column 'sigma' is missing in parquet after merge")

file_sigma = (
    check_df.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

exp_sigma = (
    std_by_ticker.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

common = file_sigma.index.intersection(exp_sigma.index)
if len(common) == 0:
    raise ValueError("No common tickers to validate sigma between std_by_ticker and parquet")

diff = (file_sigma.loc[common] - exp_sigma.loc[common]).abs()
max_diff = float(diff.max()) if len(diff) else 0.0
print("sigma_out_path:", sigma_out_path)
print("tickers in std_by_ticker:", len(exp_sigma))
print("tickers checked in parquet:", len(common))
print("max |file_sigma - expected_sigma|:", max_diff)

▶️ START merge sigma → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000  elapsed=17.5s

[batch   10] rows=20,000,000  elapsed=35.5s

[batch   15] rows=30,000,000  elapsed=53.0s

[batch   20] rows=40,000,000  elapsed=70.3s

[batch   25] rows=50,000,000  elapsed=88.0s

[batch   30] rows=60,000,000  elapsed=105.5s

[batch   35] rows=70,000,000  elapsed=122.2s

[batch   40] rows=80,000,000  elapsed=140.1s

[batch   45] rows=90,000,000  elapsed=157.8s

[batch   50] rows=100,000,000  elapsed=175.0s

[batch   55] rows=110,000,000  elapsed=192.5s

✅ DONE rows=117,495,650 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  in 206.0s

sigma_out_path: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
tickers in std_by_ticker: 7074
tickers checked in parquet: 7073
max |file_sigma - expected_sigma|: 4.999684005690952e-07

In [49]:
peek_parquet(str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"), n=21150)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 117,495,650
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 0/21150
NaN у 'corr' (у прев'ю): 0/21150
NaN у 'beta' (у прев'ю): 0/21150

Перші рядки:

      ticker                  dt           o           h           l           c          v        date    open  prev_close  Stack% bench    corr    beta  Bench%     sigma
0          A 2026-03-06 09:30:00  116.660004  116.660004  116.160004  116.160004    14743.0  2026-03-06  116.66      118.13   -1.24   IWM  0.7442  0.6533   -2.07  0.923970
1          A 2026-03-06 09:31:00  116.555000  116.555000  116.547501  116.555000      697.0  2026-03-06  116.66      118.13   -1.33   IWM  0.7442  0.6533   -2.20  0.923970
2          A 2026-03-06 09:32:00  116.502502  116.550003  116.050003  116.550003     1952.0  2026-03-06  116.66      118.13   -1.38   IWM  0.7442  0.6533   -2.17  0.923970
3          A 2026-03-06 09:33:00  116.464996  116.464996  116.464996  116.464996      200.0  2026-03-06  116.66      118.13   -1.41   IWM  0.7442  0.6533   -2.10  0.923970
4          A 2026-03-06 09:34:00  116.250000  116.250000  116.250000  116.250000      400.0  2026-03-06  116.66      118.13   -1.59   IWM  0.7442  0.6533   -2.24  0.923970
5          A 2026-03-06 09:35:00  116.349998  116.470001  116.160004  116.290001     3634.0  2026-03-06  116.66      118.13   -1.51   IWM  0.7442  0.6533   -2.11  0.923970
6          A 2026-03-06 09:36:00  116.040001  116.040001  116.010002  116.010002      500.0  2026-03-06  116.66      118.13   -1.77   IWM  0.7442  0.6533   -2.46  0.923970
7          A 2026-03-06 09:37:00  116.044998  116.135002  116.000000  116.000000     1200.0  2026-03-06  116.66      118.13   -1.77   IWM  0.7442  0.6533   -2.41  0.923970
8          A 2026-03-06 09:38:00  116.190002  116.190002  115.974998  116.059998      950.0  2026-03-06  116.66      118.13   -1.64   IWM  0.7442  0.6533   -2.43  0.923970
9          A 2026-03-06 09:39:00  115.839996  116.000000  115.589996  115.589996     3220.0  2026-03-06  116.66      118.13   -1.94   IWM  0.7442  0.6533   -2.31  0.923970
10         A 2026-03-06 09:40:00  115.775002  115.775002  115.775002  115.775002      250.0  2026-03-06  116.66      118.13   -1.99   IWM  0.7442  0.6533   -2.39  0.923970
11         A 2026-03-06 09:41:00  115.529999  115.705002  115.500000  115.665001     1176.0  2026-03-06  116.66      118.13   -2.20   IWM  0.7442  0.6533   -2.49  0.923970
12         A 2026-03-06 09:42:00  115.769997  115.769997  115.599998  115.599998      600.0  2026-03-06  116.66      118.13   -2.00   IWM  0.7442  0.6533   -2.39  0.923970
13         A 2026-03-06 09:43:00  115.635002  115.800003  115.635002  115.699997      500.0  2026-03-06  116.66      118.13   -2.11   IWM  0.7442  0.6533   -2.45  0.923970
14         A 2026-03-06 09:44:00  115.790001  115.830002  115.720001  115.750000      850.0  2026-03-06  116.66      118.13   -1.98   IWM  0.7442  0.6533   -2.30  0.923970
15         A 2026-03-06 09:45:00  115.610001  115.650002  115.610001  115.629997      300.0  2026-03-06  116.66      118.13   -2.13   IWM  0.7442  0.6533   -2.28  0.923970
16         A 2026-03-06 09:46:00  115.489998  115.519997  115.489998  115.519997      931.0  2026-03-06  116.66      118.13   -2.23   IWM  0.7442  0.6533   -2.23  0.923970
17         A 2026-03-06 09:47:00  115.510002  115.660004  115.510002  115.660004     1153.0  2026-03-06  116.66      118.13   -2.22   IWM  0.7442  0.6533   -2.32  0.923970
18         A 2026-03-06 09:48:00  115.665001  115.665001  115.665001  115.665001     1833.0  2026-03-06  116.66      118.13   -2.09   IWM  0.7442  0.6533   -2.31  0.923970
19         A 2026-03-06 09:49:00  115.669998  115.669998  115.669998  115.669998      600.0  2026-03-06  116.66      118.13   -2.08   IWM  0.7442  0.6533   -2.22  0.923970
20         A 2026-03-06 09:50:00  115.669998  115.669998  115.625000  115.665001     2400.0  2026-03-06  116.66      118.13   -2.08   IWM  0.7442  0.6533   -2.25  0.923970
21         A 2026-03-06 09:51:00  115.680000  116.032799  115.680000  115.809998     2183.0  2026-03-06  116.66      118.13   -2.07   IWM  0.7442  0.6533   -2.19  0.923970
22         A 2026-03-06 09:52:00  115.639999  115.639999  115.529999  115.529999      563.0  2026-03-06  116.66      118.13   -2.11   IWM  0.7442  0.6533   -2.14  0.923970
23         A 2026-03-06 09:53:00  115.379997  115.389999  115.279999  115.334999     1300.0  2026-03-06  116.66      118.13   -2.33   IWM  0.7442  0.6533   -2.35  0.923970
24         A 2026-03-06 09:55:00  115.315002  115.449997  115.315002  115.360001    14537.0  2026-03-06  116.66      118.13   -2.38   IWM  0.7442  0.6533   -2.40  0.923970
25         A 2026-03-06 09:56:00  115.360001  115.550003  115.360001  115.535004     5263.0  2026-03-06  116.66      118.13   -2.34   IWM  0.7442  0.6533   -2.46  0.923970
26         A 2026-03-06 09:57:00  115.519997  115.519997  115.230003  115.230003     4300.0  2026-03-06  116.66      118.13   -2.21   IWM  0.7442  0.6533   -2.41  0.923970
27         A 2026-03-06 09:58:00  115.339996  115.339996  115.339996  115.339996      100.0  2026-03-06  116.66      118.13   -2.36   IWM  0.7442  0.6533   -2.51  0.923970
28         A 2026-03-06 10:00:00  115.440002  115.820000  115.440002  115.820000     1393.0  2026-03-06  116.66      118.13   -2.28   IWM  0.7442  0.6533   -2.51  0.923970
29         A 2026-03-06 10:01:00  115.779999  115.779999  115.779999  115.779999      100.0  2026-03-06  116.66      118.13   -1.99   IWM  0.7442  0.6533   -2.16  0.923970
30         A 2026-03-06 10:02:00  115.860001  115.959999  115.779999  115.779999      739.0  2026-03-06  116.66      118.13   -1.92   IWM  0.7442  0.6533   -2.13  0.923970
31         A 2026-03-06 10:03:00  115.800003  115.809998  115.589996  115.637497     2800.0  2026-03-06  116.66      118.13   -1.97   IWM  0.7442  0.6533   -2.06  0.923970
32         A 2026-03-06 10:04:00  115.589996  115.790001  115.589996  115.790001     1383.0  2026-03-06  116.66      118.13   -2.15   IWM  0.7442  0.6533   -2.12  0.923970
33         A 2026-03-06 10:05:00  115.690002  115.690002  115.595001  115.595001      300.0  2026-03-06  116.66      118.13   -2.07   IWM  0.7442  0.6533   -1.96  0.923970
34         A 2026-03-06 10:06:00  115.595001  115.680000  115.595001  115.605003      615.0  2026-03-06  116.66      118.13   -2.15   IWM  0.7442  0.6533   -2.17  0.923970
35         A 2026-03-06 10:07:00  115.650002  115.709999  115.625000  115.669998     1300.0  2026-03-06  116.66      118.13   -2.10   IWM  0.7442  0.6533   -2.05  0.923970
36         A 2026-03-06 10:08:00  115.580002  115.879997  115.570000  115.690002     2236.0  2026-03-06  116.66      118.13   -2.16   IWM  0.7442  0.6533   -2.20  0.923970
37         A 2026-03-06 10:09:00  115.669998  115.669998  115.480003  115.580002     3434.0  2026-03-06  116.66      118.13   -2.08   IWM  0.7442  0.6533   -2.15  0.923970
38         A 2026-03-06 10:10:00  115.614998  115.614998  115.614998  115.614998      100.0  2026-03-06  116.66      118.13   -2.13   IWM  0.7442  0.6533   -2.30  0.923970
39         A 2026-03-06 10:11:00  115.760002  115.769997  115.750000  115.760002      400.0  2026-03-06  116.66      118.13   -2.01   IWM  0.7442  0.6533   -2.26  0.923970
40         A 2026-03-06 10:12:00  115.669998  115.669998  115.669998  115.669998      200.0  2026-03-06  116.66      118.13   -2.08   IWM  0.7442  0.6533   -2.03  0.923970
41         A 2026-03-06 10:13:00  115.769997  115.800003  115.745003  115.790001      900.0  2026-03-06  116.66      118.13   -2.00   IWM  0.7442  0.6533   -1.98  0.923970
42         A 2026-03-06 10:14:00  115.629997  115.760002  115.629997  115.760002      900.0  2026-03-06  116.66      118.13   -2.12   IWM  0.7442  0.6533   -1.84  0.923970
43         A 2026-03-06 10:15:00  115.809998  115.809998  115.760002  115.809998      700.0  2026-03-06  116.66      118.13   -1.96   IWM  0.7442  0.6533   -1.84  0.923970
44         A 2026-03-06 10:16:00  115.709999  115.709999  115.709999  115.709999      139.0  2026-03-06  116.66      118.13   -2.05   IWM  0.7442  0.6533   -1.76  0.923970
45         A 2026-03-06 10:18:00  115.800003  115.800003  115.709999  115.730003     1184.0  2026-03-06  116.66      118.13   -1.97   IWM  0.7442  0.6533   -1.75  0.923970
46         A 2026-03-06 10:19:00  115.754997  115.754997  115.519997  115.589996     1522.0  2026-03-06  116.66      118.13   -2.01   IWM  0.7442  0.6533   -1.69  0.923970
47         A 2026-03-06 10:20:00  115.529999  115.540001  115.529999  115.529999     1221.0  2026-03-06  116.66      118.13   -2.20   IWM  0.7442  0.6533   -1.67  0.923970
48         A 2026-03-06 10:21:00  115.540001  115.650002  115.529999  115.650002      500.0  2026-03-06  116.66      118.13   -2.19   IWM  0.7442  0.6533   -1.72  0.923970
49         A 2026-03-06 10:22:00  115.690002  115.690002  115.580002  115.580002      200.0  2026-03-06  116.66      118.13   -2.07   IWM  0.7442  0.6533   -1.64  0.923970
50         A 2026-03-06 10:23:00  115.754997  115.900002  115.754997  115.805000     1200.0  2026-03-06  116.66      118.13   -2.01   IWM  0.7442  0.6533   -1.62  0.923970
51         A 2026-03-06 10:24:00  115.870003  115.870003  115.849998  115.855003      425.0  2026-03-06  116.66      118.13   -1.91   IWM  0.7442  0.6533   -1.63  0.923970
52         A 2026-03-06 10:25:00  115.855003  115.855003  115.855003  115.855003      600.0  2026-03-06  116.66      118.13   -1.93   IWM  0.7442  0.6533   -1.64  0.923970
53         A 2026-03-06 10:26:00  115.860001  115.860001  115.860001  115.860001      800.0  2026-03-06  116.66      118.13   -1.92   IWM  0.7442  0.6533   -1.64  0.923970
54         A 2026-03-06 10:27:00  115.870003  116.070000  115.870003  116.000000     1000.0  2026-03-06  116.66      118.13   -1.91   IWM  0.7442  0.6533   -1.72  0.923970
55         A 2026-03-06 10:29:00  115.910004  115.910004  115.660004  115.809998    66091.0  2026-03-06  116.66      118.13   -1.88   IWM  0.7442  0.6533   -1.71  0.923970
56         A 2026-03-06 10:30:00  115.930000  115.985001  115.930000  115.970001     1532.0  2026-03-06  116.66      118.13   -1.86   IWM  0.7442  0.6533   -1.69  0.923970
57         A 2026-03-06 10:31:00  116.015900  116.080002  116.010002  116.019997     1016.0  2026-03-06  116.66      118.13   -1.79   IWM  0.7442  0.6533   -1.65  0.923970
58         A 2026-03-06 10:33:00  116.065002  116.160004  115.910004  116.160004     1482.0  2026-03-06  116.66      118.13   -1.75   IWM  0.7442  0.6533   -1.54  0.923970
59         A 2026-03-06 10:35:00  116.099998  116.264999  116.099998  116.264999     1326.0  2026-03-06  116.66      118.13   -1.72   IWM  0.7442  0.6533   -1.58  0.923970
60         A 2026-03-06 10:36:00  116.260002  116.364998  116.260002  116.364998      600.0  2026-03-06  116.66      118.13   -1.58   IWM  0.7442  0.6533   -1.46  0.923970
61         A 2026-03-06 10:37:00  116.370003  116.375000  116.260002  116.349998      750.0  2026-03-06  116.66      118.13   -1.49   IWM  0.7442  0.6533   -1.40  0.923970
62         A 2026-03-06 10:38:00  116.370003  116.519997  116.370003  116.404999      625.0  2026-03-06  116.66      118.13   -1.49   IWM  0.7442  0.6533   -1.39  0.923970
63         A 2026-03-06 10:39:00  116.400002  116.410004  116.370003  116.410004      800.0  2026-03-06  116.66      118.13   -1.46   IWM  0.7442  0.6533   -1.43  0.923970
64         A 2026-03-06 10:40:00  116.410004  116.410004  116.300003  116.300003     1300.0  2026-03-06  116.66      118.13   -1.46   IWM  0.7442  0.6533   -1.50  0.923970
65         A 2026-03-06 10:41:00  116.290001  116.330002  116.279999  116.324997     1435.0  2026-03-06  116.66      118.13   -1.56   IWM  0.7442  0.6533   -1.59  0.923970
66         A 2026-03-06 10:42:00  116.250000  116.324997  116.199997  116.320000     1402.0  2026-03-06  116.66      118.13   -1.59   IWM  0.7442  0.6533   -1.65  0.923970
67         A 2026-03-06 10:43:00  116.239998  116.250000  116.239998  116.245003     1547.0  2026-03-06  116.66      118.13   -1.60   IWM  0.7442  0.6533   -1.67  0.923970
68         A 2026-03-06 10:44:00  116.260002  116.260002  116.150002  116.180000     1500.0  2026-03-06  116.66      118.13   -1.58   IWM  0.7442  0.6533   -1.67  0.923970
69         A 2026-03-06 10:45:00  116.080002  116.154999  115.989998  115.989998     1160.0  2026-03-06  116.66      118.13   -1.74   IWM  0.7442  0.6533   -1.63  0.923970
70         A 2026-03-06 10:46:00  115.940002  116.019997  115.889999  116.014999     1158.0  2026-03-06  116.66      118.13   -1.85   IWM  0.7442  0.6533   -1.68  0.923970
71         A 2026-03-06 10:47:00  115.989998  115.989998  115.989998  115.989998      100.0  2026-03-06  116.66      118.13   -1.81   IWM  0.7442  0.6533   -1.74  0.923970
72         A 2026-03-06 10:48:00  115.985001  116.175003  115.985001  116.120003     1100.0  2026-03-06  116.66      118.13   -1.82   IWM  0.7442  0.6533   -1.73  0.923970
73         A 2026-03-06 10:49:00  116.099998  116.099998  116.099998  116.099998      100.0  2026-03-06  116.66      118.13   -1.72   IWM  0.7442  0.6533   -1.80  0.923970
74         A 2026-03-06 10:50:00  116.084999  116.084999  115.985001  116.000000      600.0  2026-03-06  116.66      118.13   -1.73   IWM  0.7442  0.6533   -1.82  0.923970
75         A 2026-03-06 10:51:00  116.000000  116.000000  115.919998  115.919998      370.0  2026-03-06  116.66      118.13   -1.80   IWM  0.7442  0.6533   -1.99  0.923970
76         A 2026-03-06 10:52:00  115.889999  115.889999  115.800003  115.809998     3365.0  2026-03-06  116.66      118.13   -1.90   IWM  0.7442  0.6533   -2.10  0.923970
77         A 2026-03-06 10:53:00  115.830002  115.919998  115.820000  115.845001     1220.0  2026-03-06  116.66      118.13   -1.95   IWM  0.7442  0.6533   -2.24  0.923970
78         A 2026-03-06 10:54:00  115.930000  115.930000  115.849998  115.885002     1038.0  2026-03-06  116.66      118.13   -1.86   IWM  0.7442  0.6533   -2.15  0.923970
79         A 2026-03-06 10:55:00  115.940002  116.175003  115.930000  116.089996     1472.0  2026-03-06  116.66      118.13   -1.85   IWM  0.7442  0.6533   -2.08  0.923970
80         A 2026-03-06 10:56:00  116.180000  116.260002  116.180000  116.260002     1600.0  2026-03-06  116.66      118.13   -1.65   IWM  0.7442  0.6533   -1.77  0.923970
81         A 2026-03-06 10:57:00  116.264999  116.264999  116.264999  116.264999      100.0  2026-03-06  116.66      118.13   -1.58   IWM  0.7442  0.6533   -1.62  0.923970
82         A 2026-03-06 10:58:00  116.209999  116.239998  116.129997  116.129997     1500.0  2026-03-06  116.66      118.13   -1.63   IWM  0.7442  0.6533   -1.65  0.923970
83         A 2026-03-06 10:59:00  116.235001  116.260002  116.180000  116.260002      700.0  2026-03-06  116.66      118.13   -1.60   IWM  0.7442  0.6533   -1.68  0.923970
84         A 2026-03-06 11:00:00  116.260002  116.489998  116.239998  116.440002     4059.0  2026-03-06  116.66      118.13   -1.58   IWM  0.7442  0.6533   -1.71  0.923970
85         A 2026-03-06 11:01:00  116.449997  116.569000  116.449997  116.569000     2593.0  2026-03-06  116.66      118.13   -1.42   IWM  0.7442  0.6533   -1.59  0.923970
86         A 2026-03-06 11:02:00  116.480003  116.589996  116.480003  116.500000     2525.0  2026-03-06  116.66      118.13   -1.40   IWM  0.7442  0.6533   -1.62  0.923970
87         A 2026-03-06 11:03:00  116.430000  116.555000  116.400002  116.485001     1000.0  2026-03-06  116.66      118.13   -1.44   IWM  0.7442  0.6533   -1.65  0.923970
88         A 2026-03-06 11:04:00  116.485001  116.660004  116.431999  116.580002     3975.0  2026-03-06  116.66      118.13   -1.39   IWM  0.7442  0.6533   -1.63  0.923970
89         A 2026-03-06 11:05:00  116.500000  116.574997  116.459999  116.459999     1200.0  2026-03-06  116.66      118.13   -1.38   IWM  0.7442  0.6533   -1.56  0.923970
90         A 2026-03-06 11:06:00  116.605003  116.605003  116.389999  116.389999     1200.0  2026-03-06  116.66      118.13   -1.29   IWM  0.7442  0.6533   -1.58  0.923970
91         A 2026-03-06 11:07:00  116.459999  116.464996  116.349998  116.349998      701.0  2026-03-06  116.66      118.13   -1.41   IWM  0.7442  0.6533   -1.71  0.923970
92         A 2026-03-06 11:08:00  116.349998  116.434998  116.349998  116.434998      519.0  2026-03-06  116.66      118.13   -1.51   IWM  0.7442  0.6533   -1.76  0.923970
93         A 2026-03-06 11:09:00  116.349998  116.449997  116.339996  116.339996     1250.0  2026-03-06  116.66      118.13   -1.51   IWM  0.7442  0.6533   -1.85  0.923970
94         A 2026-03-06 11:10:00  116.339996  116.437302  116.320000  116.410004     1211.0  2026-03-06  116.66      118.13   -1.52   IWM  0.7442  0.6533   -1.80  0.923970
95         A 2026-03-06 11:11:00  116.300003  116.410004  116.239998  116.320000     1251.0  2026-03-06  116.66      118.13   -1.55   IWM  0.7442  0.6533   -1.87  0.923970
96         A 2026-03-06 11:12:00  116.220001  116.330002  116.209999  116.260002      900.0  2026-03-06  116.66      118.13   -1.62   IWM  0.7442  0.6533   -1.97  0.923970
97         A 2026-03-06 11:13:00  116.339996  116.394997  116.309998  116.320000     3945.0  2026-03-06  116.66      118.13   -1.52   IWM  0.7442  0.6533   -2.07  0.923970
98         A 2026-03-06 11:14:00  116.389999  116.394997  116.290001  116.290001      500.0  2026-03-06  116.66      118.13   -1.47   IWM  0.7442  0.6533   -2.01  0.923970
99         A 2026-03-06 11:15:00  116.330002  116.349998  116.180000  116.349998     2346.0  2026-03-06  116.66      118.13   -1.52   IWM  0.7442  0.6533   -2.07  0.923970
100        A 2026-03-06 11:16:00  116.440002  116.510002  116.404999  116.510002     4151.0  2026-03-06  116.66      118.13   -1.43   IWM  0.7442  0.6533   -2.01  0.923970
101        A 2026-03-06 11:17:00  116.434998  116.434998  116.330002  116.330002      800.0  2026-03-06  116.66      118.13   -1.43   IWM  0.7442  0.6533   -1.99  0.923970
102        A 2026-03-06 11:18:00  116.330002  116.379997  116.330002  116.334999      666.0  2026-03-06  116.66      118.13   -1.52   IWM  0.7442  0.6533   -2.05  0.923970
103        A 2026-03-06 11:19:00  116.309998  116.320000  116.309998  116.320000      300.0  2026-03-06  116.66      118.13   -1.54   IWM  0.7442  0.6533   -1.99  0.923970
104        A 2026-03-06 11:20:00  116.370003  116.379898  116.269997  116.269997      631.0  2026-03-06  116.66      118.13   -1.49   IWM  0.7442  0.6533   -1.93  0.923970
105        A 2026-03-06 11:21:00  116.309998  116.400002  116.309998  116.320000     6200.0  2026-03-06  116.66      118.13   -1.54   IWM  0.7442  0.6533   -2.00  0.923970
106        A 2026-03-06 11:22:00  116.385002  116.385002  116.160004  116.220001     2390.0  2026-03-06  116.66      118.13   -1.48   IWM  0.7442  0.6533   -2.08  0.923970
107        A 2026-03-06 11:23:00  116.150002  116.182503  116.150002  116.165001      400.0  2026-03-06  116.66      118.13   -1.68   IWM  0.7442  0.6533   -2.13  0.923970
108        A 2026-03-06 11:24:00  116.169998  116.339996  116.169998  116.339996     1422.0  2026-03-06  116.66      118.13   -1.66   IWM  0.7442  0.6533   -2.13  0.923970
109        A 2026-03-06 11:25:00  116.410004  116.410004  116.410004  116.410004      200.0  2026-03-06  116.66      118.13   -1.46   IWM  0.7442  0.6533   -1.98  0.923970
110        A 2026-03-06 11:26:00  116.410004  116.410004  116.330002  116.345001      900.0  2026-03-06  116.66      118.13   -1.46   IWM  0.7442  0.6533   -2.05  0.923970
111        A 2026-03-06 11:27:00  116.345001  116.419998  116.199997  116.230003     2600.0  2026-03-06  116.66      118.13   -1.51   IWM  0.7442  0.6533   -2.07  0.923970
112        A 2026-03-06 11:28:00  116.230003  116.309998  116.230003  116.275002      500.0  2026-03-06  116.66      118.13   -1.61   IWM  0.7442  0.6533   -2.09  0.923970
113        A 2026-03-06 11:29:00  116.275002  116.300003  116.269997  116.290001      900.0  2026-03-06  116.66      118.13   -1.57   IWM  0.7442  0.6533   -2.10  0.923970
114        A 2026-03-06 11:30:00  116.324997  116.324997  116.129997  116.129997      900.0  2026-03-06  116.66      118.13   -1.53   IWM  0.7442  0.6533   -2.02  0.923970

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,A,2026-03-06 09:30:00,116.660004,116.660004,116.160004,116.160004,14743.0,2026-03-06,116.66,118.13,-1.24,IWM,0.7442,0.6533,-2.07,0.92397
1,A,2026-03-06 09:31:00,116.555000,116.555000,116.547501,116.555000,697.0,2026-03-06,116.66,118.13,-1.33,IWM,0.7442,0.6533,-2.20,0.92397
2,A,2026-03-06 09:32:00,116.502502,116.550003,116.050003,116.550003,1952.0,2026-03-06,116.66,118.13,-1.38,IWM,0.7442,0.6533,-2.17,0.92397
3,A,2026-03-06 09:33:00,116.464996,116.464996,116.464996,116.464996,200.0,2026-03-06,116.66,118.13,-1.41,IWM,0.7442,0.6533,-2.10,0.92397
4,A,2026-03-06 09:34:00,116.250000,116.250000,116.250000,116.250000,400.0,2026-03-06,116.66,118.13,-1.59,IWM,0.7442,0.6533,-2.24,0.92397
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,AAOI,2026-03-10 09:37:00,119.660004,120.290001,119.129997,119.550003,97928.0,2026-03-10,112.34,110.62,8.17,SOXX,0.7349,1.1760,0.65,3.71330
21146,AAOI,2026-03-10 09:38:00,119.610001,121.199997,119.003899,121.199997,77890.0,2026-03-10,112.34,110.62,8.13,SOXX,0.7349,1.1760,0.66,3.71330
21147,AAOI,2026-03-10 09:39:00,121.010002,121.749901,120.130096,121.220001,114636.0,2026-03-10,112.34,110.62,9.39,SOXX,0.7349,1.1760,0.97,3.71330
21148,AAOI,2026-03-10 09:40:00,120.989998,122.180000,120.699997,121.135696,101385.0,2026-03-10,112.34,110.62,9.37,SOXX,0.7349,1.1760,1.01,3.71330
21149,AAOI,2026-03-10 09:41:00,121.410004,122.180000,120.199997,121.330002,68542.0,2026-03-10,112.34,110.62,9.75,SOXX,0.7349,1.1760,1.06,3.71330

In [50]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
except Exception:
    pa = pq = ds = None


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    roundtrip_pandas: bool = True,   # найнадійніше для sort_values
    log_every: int = 200,
):
    """
    Rewrites input parquet into output parquet in strict physical order:
      ticker A→Z, then (date, dt) within each ticker (or dt only).
    Uses dataset scanning per ticker to avoid global in-memory sort.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")

    # Discover columns
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    has_date = ("date" in schema_names)
    has_dt   = ("dt" in schema_names)

    # get unique tickers (safe, but could be heavy; acceptable for your use-case)
    tickers_tbl = dataset.to_table(columns=["ticker"])
    tickers = sorted(pd.unique(tickers_tbl.column("ticker").to_pandas().astype(str)))
    del tickers_tbl
    gc.collect()

    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    writer = None
    total_written = 0
    t0 = time.time()

    print(f"▶ SORT: {input_path} → {output_path} | tickers={len(tickers):,} | has_date={has_date} has_dt={has_dt}")

    try:
        for i, tk in enumerate(tickers, 1):
            # Filter rows for this ticker
            filt = (ds.field("ticker") == tk)
            table = dataset.to_table(filter=filt)
            if table.num_rows == 0:
                continue

            if roundtrip_pandas:
                df = table.to_pandas()
                # Ensure date exists if needed
                if has_date:
                    # keep as-is; assume date is string 'YYYY-MM-DD'
                    pass
                elif has_dt and ("date" not in df.columns):
                    # If no date column exists, optionally derive it (not required for sort)
                    pass

                if has_date and has_dt and {"date", "dt"}.issubset(df.columns):
                    df.sort_values(["date", "dt"], kind="mergesort", inplace=True)
                elif has_dt and "dt" in df.columns:
                    df.sort_values(["dt"], kind="mergesort", inplace=True)
                else:
                    # fallback: stable sort by all columns
                    df.sort_values(list(df.columns), kind="mergesort", inplace=True)

                out_table = pa.Table.from_pandas(df, preserve_index=False)
                del df
            else:
                # Arrow-only fallback (less flexible)
                out_table = table

            if writer is None:
                writer = pq.ParquetWriter(tmp_out, out_table.schema, compression=compression)

            writer.write_table(out_table)
            total_written += out_table.num_rows

            if (i % log_every) == 0:
                print(f"  [{i:>6}/{len(tickers):,}] {tk}  written={total_written:,}  elapsed={time.time()-t0:,.1f}s")

            del table, out_table
            gc.collect()

    finally:
        if writer is not None:
            writer.close()

    # atomic replace
    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)

    print(f"✅ SORT DONE: {total_written:,} rows → {output_path} | time={time.time()-t0:,.1f}s")
    return output_path


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # використовується як batch_rows для Parquet
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,      # NEW: rewrite final sorted
) -> str:
    """
    Parquet-версія.
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.
    Працює потоково.

    NEW:
      - якщо sort_final_by_ticker=True, то фінальний output_path буде фізично
        відсортований: ticker A→Z, всередині тикера date,dt (або dt).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    batch_rows = chunksize

    # 1) write unsorted tmp parquet
    tmp_unsorted = output_path + f".tmp_unsorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_unsorted):
        os.remove(tmp_unsorted)

    pf = pq.ParquetFile(input_path)
    writer = None
    total = 0

    print(f"▶ START (Parquet): {input_path}  →  {output_path} | batch_rows≈{batch_rows:,}")

    for bi, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # гнучке визначення колонок
        names = {c.lower().strip(): c for c in df.columns}
        stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
        bench_col = names.get("bench%")
        beta_col  = names.get("beta")
        sigma_col = names.get("sigma")

        need = {
            "stack%/pct_vs_prev_close": stack_col,
            "bench%": bench_col,
            "beta": beta_col,
            "sigma": sigma_col,
        }
        missing = [k for k, v in need.items() if v is None]
        if missing:
            raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

        # приберемо старі результати, якщо були
        for col in ("t_p", "deviation", "dev_sig"):
            if col in df.columns:
                del df[col]

        # числові типи
        df[stack_col] = pd.to_numeric(df[stack_col], errors="coerce")
        df[bench_col] = pd.to_numeric(df[bench_col], errors="coerce")
        df[beta_col]  = pd.to_numeric(df[beta_col],  errors="coerce")
        df[sigma_col] = pd.to_numeric(df[sigma_col], errors="coerce")

        # обчислення
        tp  = df[stack_col] * df[beta_col]
        dev = tp - df[bench_col]
        denom = df[sigma_col].replace({0: np.nan})
        dsg = dev / denom

        # округлення
        if round_tp_dev is not None:
            tp  = tp.round(round_tp_dev)
            dev = dev.round(round_tp_dev)
        if round_devsig is not None:
            dsg = dsg.round(round_devsig)

        # додати в кінець
        df["t_p"] = tp
        df["deviation"] = dev
        df["dev_sig"] = dsg

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_unsorted, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if bi % 5 == 0:
            print(f"[batch {bi:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # 2) sort & finalize
    if sort_final_by_ticker:
        # rewrite sorted to output_path
        _write_final_sorted_alphabetical(
            tmp_unsorted,
            output_path,
            compression=compression,
            roundtrip_pandas=True,
            log_every=200,
        )
        # cleanup unsorted tmp
        try:
            os.remove(tmp_unsorted)
        except Exception:
            pass
    else:
        # atomic replace unsorted as final
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_unsorted, output_path)

    print(f"✅ DONE: {total:,} rows → {output_path} | total_time={time.time()-t0:,.1f}s")
    return output_path

In [51]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (Parquet): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\final.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=9.6s

[batch   10] rows=20,000,000  elapsed=19.3s

[batch   15] rows=30,000,000  elapsed=29.2s

[batch   20] rows=40,000,000  elapsed=39.1s

[batch   25] rows=50,000,000  elapsed=48.7s

[batch   30] rows=60,000,000  elapsed=58.6s

[batch   35] rows=70,000,000  elapsed=68.8s

[batch   40] rows=80,000,000  elapsed=78.9s

[batch   45] rows=90,000,000  elapsed=88.6s

[batch   50] rows=100,000,000  elapsed=98.8s

[batch   55] rows=110,000,000  elapsed=108.9s

▶ SORT: C:\datum-api-examples-main\OriON\CRACEN\final.parquet.tmp_unsorted_12924_1780815744 → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | tickers=7,600 | has_date=True has_dt=True

  [   200/7,600] AIB  written=3,241,376  elapsed=268.7s

  [   400/7,600] ANY  written=6,493,958  elapsed=542.1s

  [   600/7,600] AUTL  written=9,758,560  elapsed=816.1s

  [   800/7,600] BENFW  written=12,712,224  elapsed=1,091.2s

  [  1000/7,600] BON  written=15,657,853  elapsed=1,365.0s

  [  1200/7,600] CARD  written=18,531,328  elapsed=1,638.3s

  [  1400/7,600] CIVB  written=21,511,462  elapsed=1,915.4s

  [  1600/7,600] CRBP  written=24,539,470  elapsed=2,193.3s

  [  1800/7,600] DBMF  written=27,959,539  elapsed=2,469.4s

  [  2000/7,600] DTH  written=30,950,883  elapsed=2,743.4s

  [  2200/7,600] ENVA  written=33,711,447  elapsed=3,019.0s

  [  2400/7,600] FAST  written=36,990,248  elapsed=3,295.2s

  [  2600/7,600] FOLD  written=39,891,144  elapsed=3,572.1s

  [  2800/7,600] GGAL  written=42,838,927  elapsed=3,848.9s

  [  3000/7,600] GTY  written=45,888,924  elapsed=4,126.7s

  [  3200/7,600] HTBK  written=48,720,238  elapsed=4,400.5s

  [  3400/7,600] ILMN  written=51,526,242  elapsed=4,674.7s

  [  3600/7,600] IWF  written=54,691,704  elapsed=4,945.4s

  [  3800/7,600] KLC  written=57,602,746  elapsed=5,204.7s

  [  4000/7,600] LINE  written=60,545,374  elapsed=5,454.4s

  [  4200/7,600] MCFT  written=63,508,654  elapsed=5,693.6s

  [  4400/7,600] MRNX  written=66,430,327  elapsed=5,922.7s

  [  4600/7,600] NEU  written=69,745,428  elapsed=6,137.4s

  [  4800/7,600] NWBI  written=73,070,487  elapsed=6,353.5s

  [  5000/7,600] OSRH  written=76,128,609  elapsed=6,570.7s

  [  5200/7,600] PJT  written=79,275,045  elapsed=6,786.0s

  [  5400/7,600] PXED  written=82,384,760  elapsed=7,002.1s

  [  5600/7,600] REXC  written=85,448,666  elapsed=7,217.3s

  [  5800/7,600] SANM  written=88,774,924  elapsed=7,431.4s

  [  6000/7,600] SIVR  written=92,213,412  elapsed=7,644.9s

  [  6200/7,600] SPHD  written=95,697,412  elapsed=7,858.3s

  [  6400/7,600] SYBT  written=99,027,950  elapsed=8,068.9s

  [  6600/7,600] TNDM  written=102,097,645  elapsed=8,278.0s

  [  6800/7,600] UBFO  written=105,397,392  elapsed=8,488.9s

  [  7000/7,600] VDC  written=108,479,502  elapsed=8,697.8s

  [  7200/7,600] WABC  written=112,031,889  elapsed=8,897.6s

  [  7400/7,600] XHLF  written=114,747,629  elapsed=9,090.9s

  [  7600/7,600] ZYME  written=117,495,650  elapsed=9,284.9s

✅ SORT DONE: 117,495,650 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | time=9,285.2s

✅ DONE: 117,495,650 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=9,414.3s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'