In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2026-05-10 00:00:00
end   = 2026-08-10 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2026-05-10
end_date_str   = 2026-08-10

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker       value
0      A    55324.53
1     AA  1284291.18
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 13452

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,market_cap',
    'active': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
tickers_df = tickers_df.dropna()

# --- крок 3: додаємо потрібні колонки у df_filtered
TICKERS = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(TICKERS):,} рядків")
TICKERS.head()

Після фільтрації залишилось: 7,269 рядків

  ticker       value                         lvl3  market_cap
0      A    55324.53  Medical Equipment & Devices     42003.0
1     AA  1284291.18              Metals & Mining     13625.0
2   AAAU   266002.14                          NaN         NaN
3   AACG       22.42                     Software        37.0
4   AADX    42349.92          Aerospace & Defense      3674.0

In [7]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [8]:
unique_lvl2 = get_unique_lvl2(TICKERS)
unique_lvl2

🔹 Знайдено 59 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Elec & Gas Marketing & Trading',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [9]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "IBIT"],
    "Banking": ["XLF", "KRE", "IBIT"],
    "Institutional Financial Svcs": ["XLF", "IBIT"],
    "Insurance": ["XLF"],
    "Specialty Finance": ["XLF", "IBIT"],

    # --- Tech / Internet / Growth ---
    "Software": ["IGV"],
    "IT Services": ["QQQ"],
    "Semiconductors": ["SOXX", "DRAM"],
    "Technology Hardware": ["QQQ", "SOXX"],
    "Internet Media & Services": ["QQQ", "KWEB", "FXI"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "XRT"],
    "Cable & Satellite": ["SPY", "IWM"],
    "Telecommunications": ["QQQ"],
    "Publishing & Broadcasting": ["QQQ"],
    "Entertainment Content": ["QQQ", "ARKK"],
    "Advertising & Marketing": ["QQQ"],

    # --- Industrials ---
    "Aerospace & Defense": ["NASA", "ITA"],
    "Diversified Industrials": ["XLB", "IWM"],
    "Industrial Intermediate Prod": ["XLB", "IWM"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["XLB", "IWM"],
    "Machinery": ["XLB", "IWM"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["XLB", "IWM"],
    "Electrical Equipment": ["QQQ", "XLB"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XOP", "XLE", "UNG"],
    "Oil & Gas Supply Chain": ["XOP", "XLE", "UNG"],
    "Elec & Gas Marketing & Trading": ["XLU", "XLE"],
    "Electric Utilities": ["XLU"],
    "Gas & Water Utilities": ["XLU"],
    "Renewable Energy": ["XLE", "ARKK"],
    "Chemicals": ["XLB", "URA"],
    "Metals & Mining": ["GDX", "FCX", "COPX", "URA", "SLV"],
    "Steel": ["XLB", "GDX"],
    "Construction Materials": ["XLB", "IWM"],
    "Forestry, Paper & Wood Products": ["XLB", "IWM"],

    # --- Health Care ---
    "Biotech & Pharma": ["XBI"],
    "Medical Equipment & Devices": ["XLV"],
    "Health Care Facilities & Svcs": ["XLV", "IWM"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["XLP"],
    "Beverages": ["XLP"],
    "Household Products": ["XLP"],
    "Tobacco & Cannabis": ["XLP"],
    "Retail - Consumer Staples": ["XLP", "XRT"],
    "Wholesale - Consumer Staples": ["XLP"],

    "Retail - Discretionary": ["XRT", "IWM", "SPY"],
    "Wholesale - Discretionary": ["XRT", "IWM"],
    "Consumer Services": ["IWM", "SPY"],
    "Leisure Facilities & Services": ["IWM", "SPY"],
    "Leisure Products": ["XRT", "IWM"],
    "Apparel & Textile Products": ["XRT", "IWM"],
    "Automotive": ["QQQ", "IWM"],
    "Home & Office Products": ["XRT", "IWM"],
    "Home Construction": ["XLB", "IWM"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [10]:
# ------------------------------------------------

In [11]:
import numpy as np
import pandas as pd


def calc_corr_beta_from_joined_gaps(df_pair: pd.DataFrame, x_col: str = "gap_x", y_col: str = "gap_y"):
    """
    Local corr/beta calculation without /calculations/corr_beta API.

    corr = Pearson(x, y)
    beta = cov(x, y) / var(y)
    """
    d = df_pair[[x_col, y_col]].copy()
    d[x_col] = pd.to_numeric(d[x_col], errors="coerce")
    d[y_col] = pd.to_numeric(d[y_col], errors="coerce")
    d = d.dropna()

    n = len(d)
    if n < 2:
        return np.nan, np.nan, n

    var_y = float(d[y_col].var(ddof=1))
    corr = float(d[x_col].corr(d[y_col]))

    if np.isnan(var_y) or var_y == 0:
        return corr, np.nan, n

    cov_xy = float(d[[x_col, y_col]].cov(ddof=1).iloc[0, 1])
    beta = cov_xy / var_y
    return corr, beta, n


def corr_beta_best_match_from_gaps(
    stock_gap_df: pd.DataFrame,
    etf_gap_df: pd.DataFrame,
    x_tickers,
    y_tickers,
    *,
    min_overlap: int = 20,
    output_path: str = None,
):
    """
    Pick best Y per X using local gaps.

    stock_gap_df: ['ticker','date','gap']
    etf_gap_df:   ['ticker','date','gap']
    """
    sx = stock_gap_df.copy()
    sy = etf_gap_df.copy()

    for df in (sx, sy):
        if not {"ticker", "date", "gap"}.issubset(df.columns):
            raise KeyError("Expected columns ['ticker','date','gap'] in gap data")
        df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.strftime("%Y-%m-%d")
        df["gap"] = pd.to_numeric(df["gap"], errors="coerce")

    s_map = {t: g[["date", "gap"]].copy() for t, g in sx.groupby("ticker")}
    e_map = {t: g[["date", "gap"]].copy() for t, g in sy.groupby("ticker")}

    rows_all = []
    rows_best = []

    for x in [str(v).upper() for v in x_tickers]:
        g_x = s_map.get(x)
        if g_x is None or g_x.empty:
            continue

        best = None
        for y in [str(v).upper() for v in y_tickers]:
            g_y = e_map.get(y)
            if g_y is None or g_y.empty:
                continue

            m = g_x.merge(g_y, on="date", how="inner", suffixes=("_x", "_y")).dropna()
            corr, beta, n = calc_corr_beta_from_joined_gaps(m, x_col="gap_x", y_col="gap_y")
            if n < int(min_overlap) or pd.isna(corr):
                continue

            row = {
                "x_ticker": x,
                "y_ticker": y,
                "corr": corr,
                "beta": beta,
                "n_overlap": n,
            }
            rows_all.append(row)
            if best is None or row["corr"] > best["corr"]:
                best = row

        if best is not None:
            rows_best.append({
                "x_ticker": best["x_ticker"],
                "best_y_ticker": best["y_ticker"],
                "best_corr": best["corr"],
                "beta_with_best": best["beta"],
                "n_overlap": best["n_overlap"],
            })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "n_overlap"])

    if output_path:
        df_pairs.to_csv(output_path, index=False)

    return df_all, df_pairs

In [12]:
def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
    start_date=None,
    end_date=None,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
):
    import numpy as np
    import pandas as pd
    from concurrent.futures import ThreadPoolExecutor

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]
    if start_date is None:
        start_date = globals().get("start_date_str")
    if end_date is None:
        end_date = globals().get("end_date_str")
    if not start_date or not end_date:
        raise ValueError("Provide start_date/end_date or define start_date_str/end_date_str")
    if sector_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{sector_col}' column")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{ticker_col}' column")

    s_date, e_date = str(start_date)[:10], str(end_date)[:10]

    def _pick_col(df, candidates):
        cols_l = {c.lower().strip(): c for c in df.columns}
        return next((cols_l[c.lower()] for c in candidates if c.lower() in cols_l), None)

    def _fetch_gap(t):
        try:
            dfg = DatumApi.data_request("/daily/gaps", {
                "ticker": t, "start_date": s_date, "end_date": e_date, "format": "json_records",
            })
            if dfg is None or dfg.empty:
                return None
            dcol = _pick_col(dfg, ["date", "move_date", "dt", "datetime", "day"])
            if dcol is None or "gap" not in dfg.columns:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(dfg[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
                "gap": pd.to_numeric(dfg["gap"], errors="coerce"),
            }).dropna()
            return out if not out.empty else None
        except Exception as ex:
            print(f"WARN gaps fail {t}: {ex}")
            return None

    def _fetch_report(t):
        try:
            rep = DatumApi.data_request("/reports", {
                "ticker": t, "start_move_date": s_date, "end_move_date": e_date,
            })
            if rep is None or rep.empty:
                return None
            dcol = _pick_col(rep, ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"])
            if dcol is None:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(rep[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
            }).dropna().sort_values("date").tail(int(last_n_reports))
            return out if not out.empty else None
        except Exception as ex:
            print(f"WARN reports fail {t}: {ex}")
            return None

    # ── prepare ──────────────────────────────────────────────────────────────
    df_clean = tickers_df[[ticker_col, sector_col]].drop_duplicates().copy()
    df_clean[ticker_col] = df_clean[ticker_col].astype(str).str.strip().str.upper()
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)

    stocks = sorted(df_clean[ticker_col].dropna().unique())
    etf_candidates = set(fallback_etfs)
    for sec in df_clean[sector_col].unique():
        etf_candidates.update(sector_to_etf.get(sec, fallback_etfs) or fallback_etfs)
    etf_candidates = sorted(str(x).upper() for x in etf_candidates)

    print(f"START gaps: stocks={len(stocks)} etfs={len(etf_candidates)} window={s_date}..{e_date}")

    # ── parallel fetch: all gaps + reports in one pool ────────────────────────
    all_gap_tickers = sorted(set(stocks) | set(etf_candidates))
    with ThreadPoolExecutor(max_workers=min(64, len(all_gap_tickers) + len(stocks))) as ex:
        gap_futs  = {t: ex.submit(_fetch_gap,    t) for t in all_gap_tickers}
        rep_futs  = {t: ex.submit(_fetch_report, t) for t in stocks}

    gap_res = {t: f.result() for t, f in gap_futs.items()}
    rep_res = {t: f.result() for t, f in rep_futs.items()}

    def _concat(parts, cols):
        valid = [p for p in parts if p is not None]
        return pd.concat(valid, ignore_index=True) if valid else pd.DataFrame(columns=cols)

    stock_gaps = _concat([gap_res.get(t) for t in stocks],         ["ticker", "date", "gap"])
    etf_gaps   = _concat([gap_res.get(t) for t in etf_candidates], ["ticker", "date", "gap"])
    reports    = _concat([rep_res.get(t) for t in stocks],          ["ticker", "date"]).drop_duplicates()

    # ── exclude report days ──────────────────────────────────────────────────
    if not reports.empty and not stock_gaps.empty:
        m = stock_gaps.merge(reports.assign(_rep=1), on=["ticker", "date"], how="left")
        stock_gaps = m[m["_rep"].isna()][["ticker", "date", "gap"]].copy()

    # ── drop anomalies (vectorised) ──────────────────────────────────────────
    if not stock_gaps.empty:
        stock_gaps["gap"] = pd.to_numeric(stock_gaps["gap"], errors="coerce")
        abs_gap = stock_gaps["gap"].abs()
        cnts = stock_gaps.groupby("ticker")["gap"].transform("count")
        eligible = cnts >= min_hist_for_cap
        if eligible.any():
            caps = (stock_gaps[eligible]
                    .groupby("ticker")["gap"]
                    .agg(lambda x: np.quantile(x.abs(), cap_q)))
            cap_mapped = stock_gaps["ticker"].map(caps)
            stock_gaps = stock_gaps[(~eligible) | (abs_gap <= cap_mapped)].reset_index(drop=True)

    # ── build ETF numpy matrix: rows=dates, cols=etfs ───────────────────────
    if not etf_gaps.empty:
        etf_pivot = etf_gaps.pivot_table(index="date", columns="ticker", values="gap", aggfunc="first")
        date_to_row = {d: i for i, d in enumerate(etf_pivot.index)}
        etf_to_col  = {c: i for i, c in enumerate(etf_pivot.columns)}
        etf_arr     = etf_pivot.to_numpy(dtype=float)
    else:
        date_to_row = {}; etf_to_col = {}; etf_arr = np.empty((0, 0))

    stock_map = (
        {t: g.set_index("date")["gap"] for t, g in stock_gaps.groupby("ticker")}
        if not stock_gaps.empty else {}
    )

    # ── corr/beta loop ───────────────────────────────────────────────────────
    rows_all = []
    rows_best = []
    sectors_with_fallback = []

    for sec in sorted(df_clean[sector_col].unique()):
        etfs_raw = sector_to_etf.get(sec)
        if not etfs_raw:
            etfs_raw = list(fallback_etfs)
            sectors_with_fallback.append(sec)
        etfs = [str(e).upper() for e in etfs_raw]
        etfs_ok  = [e for e in etfs if e in etf_to_col]
        col_idxs = [etf_to_col[e] for e in etfs_ok]
        if not col_idxs:
            continue

        for st in sorted(df_clean.loc[df_clean[sector_col] == sec, ticker_col].unique()):
            sx = stock_map.get(st)
            if sx is None or sx.empty:
                continue

            st_dates = [d for d in sx.index if d in date_to_row]
            if not st_dates:
                continue

            row_idxs = [date_to_row[d] for d in st_dates]
            x_vals   = sx[st_dates].to_numpy(dtype=float)
            y_mat    = etf_arr[np.ix_(row_idxs, col_idxs)]   # (n_dates, n_etfs)
            valid_x  = ~np.isnan(x_vals)

            best_corr = -np.inf
            best_etf  = None
            best_beta = np.nan
            best_n    = 0

            for j, etf in enumerate(etfs_ok):
                mask = valid_x & ~np.isnan(y_mat[:, j])
                n = int(mask.sum())
                if n < min_overlap:
                    continue

                xv = x_vals[mask];  yv = y_mat[mask, j]
                xc = xv - xv.mean(); yc = yv - yv.mean()
                var_y = float((yc * yc).sum() / (n - 1))
                if var_y == 0 or np.isnan(var_y):
                    continue
                cov_xy = float((xc * yc).sum() / (n - 1))
                std_x  = float(np.sqrt((xc * xc).sum() / (n - 1)))
                if std_x == 0:
                    continue
                corr = cov_xy / (std_x * np.sqrt(var_y))
                beta = cov_xy / var_y

                rows_all.append({"x_ticker": st, "y_ticker": etf, "corr": corr, "beta": beta, "lvl3": sec, "n_overlap": n})

                if corr > best_corr:
                    best_corr, best_etf, best_beta, best_n = corr, etf, beta, n

            if best_etf is not None:
                rows_best.append({"x_ticker": st, "best_y_ticker": best_etf, "best_corr": best_corr,
                                  "beta_with_best": best_beta, "lvl3": sec, "n_overlap": best_n})

    # ── output ───────────────────────────────────────────────────────────────
    df_all   = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best) if rows_best else pd.DataFrame(
        columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "lvl3", "n_overlap"])

    df_pairs.to_csv(output_path, index=False)
    df_bench = df_pairs.rename(columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"})[["ticker", "benchmark"]]
    df_bench.to_csv(bench_path, index=False)

    print(f"DONE pairs: {len(df_pairs)} -> {output_path}")
    print(f"DONE bench map: {len(df_bench)} -> {bench_path}")
    if sectors_with_fallback:
        print("Fallback ETF used for sectors:", ", ".join(map(str, sectors_with_fallback[:20])))

    return df_all, df_pairs

In [13]:
# Local corr/beta: stock gaps vs ETF gaps, excluding report days and stock outliers
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=TICKERS,
    sector_to_etf=sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path=str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path=str(WORK_DIR / "ticker_bench_.csv"),
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
)

# Prepare parquet for downstream merge (cell 31)
corr_beta_pairs = df_pairs.rename(columns={
    "best_y_ticker": "y_ticker",
    "best_corr": "corr",
    "beta_with_best": "beta",
})[["x_ticker", "y_ticker", "corr", "beta"]].copy()

corr_beta_pairs.to_parquet(str(WORK_DIR / "corr_beta_pairs.parquet"), index=False)

print(df_all.head())
print("Rows in raw stock-etf pairs:", len(df_all))
print(df_pairs.head())
print("Saved:", str(WORK_DIR / "corr_beta_pairs.parquet"))

START gaps: stocks=7269 etfs=28 window=2026-05-10..2026-08-10

WARN gaps fail SLAI: 404 Client Error: Not Found for url: https://api.datum-rd.com/daily/gaps?ticker=SLAI&start_date=2026-05-10&end_date=2026-08-10&format=json_records

DONE pairs: 7127 -> C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
DONE bench map: 7127 -> C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv
Fallback ETF used for sectors: UNKNOWN

  x_ticker y_ticker      corr      beta                     lvl3  n_overlap
0      ADV      QQQ  0.207144  0.137478  Advertising & Marketing         49
1     AEHL      QQQ  0.151274  0.360535  Advertising & Marketing         49
2      APP      QQQ  0.008549  0.009230  Advertising & Marketing         49
3     AREN      QQQ -0.051993 -0.087405  Advertising & Marketing         50
4     BAOS      QQQ  0.140985  0.265564  Advertising & Marketing         50
Rows in raw stock-etf pairs: 15922
  x_ticker best_y_ticker  best_corr  beta_with_best                     lvl3  \
0      ADV           QQQ   0.207144        0.137478  Advertising & Marketing
1     AEHL           QQQ   0.151274        0.360535  Advertising & Marketing
2      APP           QQQ   0.008549        0.009230  Advertising & Marketing
3     AREN           QQQ  -0.051993       -0.087405  Advertising & Marketing
4     BAOS           QQQ   0.140985        0.265564  Advertising & Marketing

   n_overlap
0         49
1         49
2         49
3         50
4         50
Saved: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [14]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [15]:
TICKERS

     ticker       value                         lvl3  market_cap
0         A    55324.53  Medical Equipment & Devices     42003.0
1        AA  1284291.18              Metals & Mining     13625.0
2      AAAU   266002.14                          NaN         NaN
3      AACG       22.42                     Software        37.0
4      AADX    42349.92          Aerospace & Defense      3674.0
...     ...         ...                          ...         ...
7264   ZVOL     1954.07                          NaN         NaN
7265   ZVRA    30901.77             Biotech & Pharma       681.0
7266    ZWS     3395.66                    Machinery      8469.0
7267   ZYBT      275.58             Biotech & Pharma        53.0
7268   ZYME   135021.83             Biotech & Pharma      1727.0

[7269 rows x 4 columns]

In [16]:
import pandas as pd

# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]


# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

   ticker
0    ARKK
1    COPX
2    DRAM
3     FCX
4     FXI
5     GDX
6    IBIT
7     IGV
8     ITA
9     IWM
10    KRE
11   KWEB
12   NASA
13    QQQ
14    SLV
15   SOXX
16    SPY
17    UNG
18    URA
19    XBI
20    XLB
21    XLE
22    XLF
23    XLP
24    XLU
25    XLV
26    XOP
27    XRT

In [17]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=TICKERS,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=16,
    parallel_tickers=True,
    max_workers_tickers=16,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 7269 тікерів (пропущено 0 по старому маніфесту) | 2026-05-10 00:00:00 → 2026-08-10 23:59:59 | interval=1 | next batch #13012 | run=7535a732

   workers: tickers=16, chunks=16 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-05-10 → 2026-08-08 (91 днів)

   📈 обробляються дні: 2026-08-09 → 2026-08-10 (2 днів)

   psutil · старт · 🧠 RAM: 348.5 MB

[10/7269] ✓ AADX: 379 рядків |   0.14% | ETA 20:14

[20/7269] ✓ AAT: 201 рядків |   0.28% | ETA 17:00

[30/7269] ✓ AAUC: 312 рядків |   0.41% | ETA 16:11

[40/7269] ✓ ABT: 415 рядків |   0.55% | ETA 15:36

[50/7269] – ABVE: empty |   0.69% | ETA 15:17

   • RAM · 🧠 RAM: 366.9 MB

   ⏳ перед flush · 🧠 RAM: 366.9 MB

💾 batch 13012 → 17,360 рядків (всього 17,360 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13012.csv.gz

   ✅ після flush · 🧠 RAM: 370.2 MB

[60/7269] ✓ ACET: 122 рядків |   0.83% | ETA 16:13

[70/7269] ✓ ACGL: 360 рядків |   0.96% | ETA 15:54

[80/7269] ✓ ACRS: 367 рядків |   1.10% | ETA 15:40

[90/7269] ✓ ACWI: 395 рядків |   1.24% | ETA 15:27

[100/7269] ✓ ADGM: 374 рядків |   1.38% | ETA 15:18

   • RAM · 🧠 RAM: 373.2 MB

   ⏳ перед flush · 🧠 RAM: 373.3 MB

💾 batch 13013 → 13,033 рядків (всього 30,393 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13013.csv.gz

   ✅ після flush · 🧠 RAM: 376.3 MB

[110/7269] ✓ ADNT: 301 рядків |   1.51% | ETA 15:55

[120/7269] ✓ AEC: 102 рядків |   1.65% | ETA 15:43

[130/7269] ✓ AEHG: 213 рядків |   1.79% | ETA 15:33

[140/7269] ✓ AEYE: 103 рядків |   1.93% | ETA 15:18

[150/7269] ✓ AFJK: 28 рядків |   2.06% | ETA 14:56

   • RAM · 🧠 RAM: 378.2 MB

   ⏳ перед flush · 🧠 RAM: 378.2 MB

💾 batch 13014 → 12,729 рядків (всього 43,122 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13014.csv.gz

   ✅ після flush · 🧠 RAM: 379.5 MB

[160/7269] ✓ AGI: 472 рядків |   2.20% | ETA 14:49

[170/7269] ✓ AGIG: 65 рядків |   2.34% | ETA 14:41

[180/7269] ✓ AIAI: 183 рядків |   2.48% | ETA 14:36

[190/7269] ✓ AIFC: 359 рядків |   2.61% | ETA 14:34

[200/7269] ✓ AIOS: 15 рядків |   2.75% | ETA 14:33

   • RAM · 🧠 RAM: 382.1 MB

   ⏳ перед flush · 🧠 RAM: 382.1 MB

💾 batch 13015 → 10,517 рядків (всього 53,639 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13015.csv.gz

   ✅ після flush · 🧠 RAM: 384.7 MB

[210/7269] ✓ AIPO: 466 рядків |   2.89% | ETA 14:42

[220/7269] ✓ AIRO: 291 рядків |   3.03% | ETA 14:38

[230/7269] ✓ AKAM: 497 рядків |   3.16% | ETA 14:35

[240/7269] ✓ ALC: 434 рядків |   3.30% | ETA 14:31

[250/7269] ✓ ALKS: 309 рядків |   3.44% | ETA 14:27

   • RAM · 🧠 RAM: 388.2 MB

   ⏳ перед flush · 🧠 RAM: 388.2 MB

💾 batch 13016 → 12,754 рядків (всього 66,393 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13016.csv.gz

   ✅ після flush · 🧠 RAM: 389.6 MB

[260/7269] ✓ ALMR: 214 рядків |   3.58% | ETA 14:37

[270/7269] ✓ ALM: 564 рядків |   3.71% | ETA 14:36

[280/7269] ✓ ALZN: 36 рядків |   3.85% | ETA 14:34

[290/7269] ✓ AMBP: 338 рядків |   3.99% | ETA 14:32

[300/7269] ✓ AMDW: 106 рядків |   4.13% | ETA 14:28

   • RAM · 🧠 RAM: 392.1 MB

   ⏳ перед flush · 🧠 RAM: 392.1 MB

💾 batch 13017 → 14,574 рядків (всього 80,967 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13017.csv.gz

   ✅ після flush · 🧠 RAM: 393.9 MB

[310/7269] ✓ AMH: 371 рядків |   4.26% | ETA 14:32

[320/7269] ✓ AMLX: 335 рядків |   4.40% | ETA 14:29

[330/7269] ✓ AMST: 65 рядків |   4.54% | ETA 14:28

[340/7269] ✓ AMTX: 276 рядків |   4.68% | ETA 14:30

[350/7269] ✓ AMZY: 212 рядків |   4.81% | ETA 14:28

   • RAM · 🧠 RAM: 400.3 MB

   ⏳ перед flush · 🧠 RAM: 400.3 MB

💾 batch 13018 → 12,823 рядків (всього 93,790 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13018.csv.gz

   ✅ після flush · 🧠 RAM: 401.3 MB

[360/7269] ✓ ANGO: 244 рядків |   4.95% | ETA 14:33

[370/7269] ✓ ANIK: 134 рядків |   5.09% | ETA 14:31

[380/7269] ✓ AOMR: 96 рядків |   5.23% | ETA 14:30

[390/7269] ✓ APD: 386 рядків |   5.37% | ETA 14:26

[400/7269] ✓ APLX: 377 рядків |   5.50% | ETA 14:25

   • RAM · 🧠 RAM: 403.1 MB

   ⏳ перед flush · 🧠 RAM: 403.1 MB

💾 batch 13019 → 12,053 рядків (всього 105,843 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13019.csv.gz

   ✅ після flush · 🧠 RAM: 405.4 MB

[410/7269] ✓ APP: 927 рядків |   5.64% | ETA 14:31

[420/7269] ✓ AQMS: 34 рядків |   5.78% | ETA 14:29

[430/7269] ✓ ARBB: 1 рядків |   5.92% | ETA 14:25

[440/7269] ✓ AREN: 213 рядків |   6.05% | ETA 14:24

[450/7269] ✓ ARES: 382 рядків |   6.19% | ETA 14:22

   • RAM · 🧠 RAM: 406.9 MB

   ⏳ перед flush · 🧠 RAM: 407.1 MB

💾 batch 13020 → 13,939 рядків (всього 119,782 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13020.csv.gz

   ✅ після flush · 🧠 RAM: 409.1 MB

[460/7269] ✓ ARMG: 382 рядків |   6.33% | ETA 14:29

[470/7269] ✓ ARR: 468 рядків |   6.47% | ETA 14:28

[480/7269] ✓ ARTL: 77 рядків |   6.60% | ETA 14:27

[490/7269] ✓ ASEA: 23 рядків |   6.74% | ETA 14:25

[500/7269] ✓ ASO: 348 рядків |   6.88% | ETA 14:24

   • RAM · 🧠 RAM: 411.0 MB

   ⏳ перед flush · 🧠 RAM: 411.0 MB

💾 batch 13021 → 12,632 рядків (всього 132,414 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13021.csv.gz

   ✅ після flush · 🧠 RAM: 411.8 MB

[510/7269] ✓ ASTE: 202 рядків |   7.02% | ETA 14:27

[520/7269] ✓ ASUP: 27 рядків |   7.15% | ETA 14:26

[530/7269] ✓ ATI: 386 рядків |   7.29% | ETA 14:24

[540/7269] ✓ ATLO: 46 рядків |   7.43% | ETA 14:21

[550/7269] ✓ ATRO: 284 рядків |   7.57% | ETA 14:20

   • RAM · 🧠 RAM: 414.0 MB

   ⏳ перед flush · 🧠 RAM: 414.1 MB

💾 batch 13022 → 13,135 рядків (всього 145,549 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13022.csv.gz

   ✅ після flush · 🧠 RAM: 414.8 MB

[560/7269] ✓ ATTO: 219 рядків |   7.70% | ETA 14:24

[570/7269] ✓ AUTL: 436 рядків |   7.84% | ETA 14:21

[580/7269] ✓ AVAV: 566 рядків |   7.98% | ETA 14:19

[590/7269] ✓ AVGW: 52 рядків |   8.12% | ETA 14:18

[600/7269] ✓ AVO: 268 рядків |   8.25% | ETA 14:15

   • RAM · 🧠 RAM: 416.8 MB

   ⏳ перед flush · 🧠 RAM: 416.8 MB

💾 batch 13023 → 12,249 рядків (всього 157,798 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13023.csv.gz

   ✅ після flush · 🧠 RAM: 418.9 MB

[610/7269] ✓ AVX: 15 рядків |   8.39% | ETA 14:18

[620/7269] – AXIA: empty |   8.53% | ETA 14:17

[630/7269] ✓ AXP: 431 рядків |   8.67% | ETA 14:15

[640/7269] ✓ AYI: 260 рядків |   8.80% | ETA 14:13

[650/7269] ✓ AZO: 333 рядків |   8.94% | ETA 14:12

   • RAM · 🧠 RAM: 421.8 MB

   ⏳ перед flush · 🧠 RAM: 421.8 MB

💾 batch 13024 → 14,620 рядків (всього 172,418 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13024.csv.gz

   ✅ після flush · 🧠 RAM: 422.8 MB

[660/7269] ✓ BABX: 367 рядків |   9.08% | ETA 14:14

[670/7269] ✓ BANC: 387 рядків |   9.22% | ETA 14:13

[680/7269] ✓ BATT: 56 рядків |   9.35% | ETA 14:11

[690/7269] ✓ BBBY: 399 рядків |   9.49% | ETA 14:10

[700/7269] ✓ BBLU: 60 рядків |   9.63% | ETA 14:09

   • RAM · 🧠 RAM: 425.4 MB

   ⏳ перед flush · 🧠 RAM: 425.6 MB

💾 batch 13025 → 13,223 рядків (всього 185,641 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13025.csv.gz

   ✅ після flush · 🧠 RAM: 426.5 MB

[710/7269] ✓ BBOT: 188 рядків |   9.77% | ETA 14:11

[720/7269] ✓ BCHT: 20 рядків |   9.91% | ETA 14:09

[730/7269] ✓ BCPC: 104 рядків |  10.04% | ETA 14:09

[740/7269] ✓ BDJ: 241 рядків |  10.18% | ETA 14:07

[750/7269] ✓ BEG: 213 рядків |  10.32% | ETA 14:06

   • RAM · 🧠 RAM: 428.4 MB

   ⏳ перед flush · 🧠 RAM: 428.4 MB

💾 batch 13026 → 9,786 рядків (всього 195,427 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13026.csv.gz

   ✅ після flush · 🧠 RAM: 429.7 MB

[760/7269] ✓ BENF: 30 рядків |  10.46% | ETA 14:08

[770/7269] ✓ BEX: 548 рядків |  10.59% | ETA 14:06

[780/7269] ✓ BGI: 49 рядків |  10.73% | ETA 14:05

[790/7269] ✓ BGSF: 13 рядків |  10.87% | ETA 14:03

[800/7269] ✓ BIAF: 324 рядків |  11.01% | ETA 14:01

   • RAM · 🧠 RAM: 431.5 MB

   ⏳ перед flush · 🧠 RAM: 431.5 MB

💾 batch 13027 → 10,042 рядків (всього 205,469 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13027.csv.gz

   ✅ після flush · 🧠 RAM: 433.7 MB

[810/7269] ✓ BIOA: 277 рядків |  11.14% | ETA 14:04

[820/7269] ✓ BIP: 350 рядків |  11.28% | ETA 14:03

[830/7269] ✓ BITI: 425 рядків |  11.42% | ETA 14:01

[840/7269] ✓ BIZD: 355 рядків |  11.56% | ETA 14:00

[850/7269] ✓ BKH: 338 рядків |  11.69% | ETA 13:59

   • RAM · 🧠 RAM: 436.5 MB

   ⏳ перед flush · 🧠 RAM: 436.5 MB

💾 batch 13028 → 13,823 рядків (всього 219,292 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13028.csv.gz

   ✅ після flush · 🧠 RAM: 437.3 MB

[860/7269] – BLCN: empty |  11.83% | ETA 13:58

[870/7269] ✓ BLIN: 61 рядків |  11.97% | ETA 13:57

[880/7269] ✓ BLV: 360 рядків |  12.11% | ETA 13:56

[890/7269] ✓ BMM: 283 рядків |  12.24% | ETA 13:55

[900/7269] ✓ BMRA: 12 рядків |  12.38% | ETA 13:54

   • RAM · 🧠 RAM: 439.1 MB

   ⏳ перед flush · 🧠 RAM: 439.3 MB

💾 batch 13029 → 13,823 рядків (всього 233,115 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13029.csv.gz

   ✅ після flush · 🧠 RAM: 440.0 MB

[910/7269] ✓ BNR: 30 рядків |  12.52% | ETA 13:55

[920/7269] – BNZI: empty |  12.66% | ETA 13:54

[930/7269] ✓ BOKF: 135 рядків |  12.79% | ETA 13:53

[940/7269] ✓ BOT: 221 рядків |  12.93% | ETA 13:51

[950/7269] ✓ BPRN: 62 рядків |  13.07% | ETA 13:50

   • RAM · 🧠 RAM: 441.0 MB

   ⏳ перед flush · 🧠 RAM: 441.0 MB

💾 batch 13030 → 9,976 рядків (всього 243,091 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13030.csv.gz

   ✅ після flush · 🧠 RAM: 441.8 MB

[960/7269] ✓ BRBR: 389 рядків |  13.21% | ETA 13:52

[970/7269] ✓ BRR: 344 рядків |  13.34% | ETA 13:51

[980/7269] ✓ BRZE: 397 рядків |  13.48% | ETA 13:49

[990/7269] ✓ BSEM: 81 рядків |  13.62% | ETA 13:48

[1000/7269] ✓ BTAL: 232 рядків |  13.76% | ETA 13:47

   • RAM · 🧠 RAM: 440.5 MB

   ⏳ перед flush · 🧠 RAM: 440.5 MB

💾 batch 13031 → 10,502 рядків (всього 253,593 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13031.csv.gz

   ✅ після flush · 🧠 RAM: 441.7 MB

[1010/7269] ✓ BTCT: 190 рядків |  13.89% | ETA 13:48

[1020/7269] ✓ BTE: 403 рядків |  14.03% | ETA 13:46

[1030/7269] ✓ BTOC: 55 рядків |  14.17% | ETA 13:44

[1040/7269] – BU: empty |  14.31% | ETA 13:43

[1050/7269] ✓ BV: 329 рядків |  14.44% | ETA 13:42

   • RAM · 🧠 RAM: 440.6 MB

   ⏳ перед flush · 🧠 RAM: 440.6 MB

💾 batch 13032 → 11,955 рядків (всього 265,548 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13032.csv.gz

   ✅ після flush · 🧠 RAM: 445.9 MB

[1060/7269] ✓ BWB: 164 рядків |  14.58% | ETA 13:46

[1070/7269] ✓ BY: 161 рядків |  14.72% | ETA 13:45

[1080/7269] ✓ BZ: 432 рядків |  14.86% | ETA 13:44

[1090/7269] ✓ CABZ: 1 рядків |  15.00% | ETA 13:42

[1100/7269] ✓ CAF: 10 рядків |  15.13% | ETA 13:41

   • RAM · 🧠 RAM: 446.4 MB

   ⏳ перед flush · 🧠 RAM: 446.4 MB

💾 batch 13033 → 11,926 рядків (всього 277,474 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13033.csv.gz

   ✅ після flush · 🧠 RAM: 446.7 MB

[1110/7269] ✓ CALX: 293 рядків |  15.27% | ETA 13:44

[1120/7269] ✓ CAMT: 410 рядків |  15.41% | ETA 13:43

[1130/7269] ✓ CASS: 48 рядків |  15.55% | ETA 13:41

[1140/7269] ✓ CBIO: 174 рядків |  15.68% | ETA 13:40

[1150/7269] ✓ CBRL: 372 рядків |  15.82% | ETA 13:39

   • RAM · 🧠 RAM: 448.4 MB

   ⏳ перед flush · 🧠 RAM: 448.5 MB

💾 batch 13034 → 12,883 рядків (всього 290,357 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13034.csv.gz

   ✅ після flush · 🧠 RAM: 448.9 MB

[1160/7269] ✓ CC: 426 рядків |  15.96% | ETA 13:41

[1170/7269] ✓ CCEP: 400 рядків |  16.10% | ETA 13:39

[1180/7269] – CCRN: empty |  16.23% | ETA 13:38

[1190/7269] ✓ CDIO: 25 рядків |  16.37% | ETA 13:37

[1200/7269] ✓ CDT: 56 рядків |  16.51% | ETA 13:35

   • RAM · 🧠 RAM: 450.0 MB

   ⏳ перед flush · 🧠 RAM: 450.0 MB

💾 batch 13035 → 12,573 рядків (всього 302,930 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13035.csv.gz

   ✅ після flush · 🧠 RAM: 450.3 MB

[1210/7269] ✓ CELC: 233 рядків |  16.65% | ETA 13:36

[1220/7269] ✓ CEPU: 240 рядків |  16.78% | ETA 13:34

[1230/7269] ✓ CEVA: 495 рядків |  16.92% | ETA 13:33

[1240/7269] ✓ CFR: 248 рядків |  17.06% | ETA 13:31

[1250/7269] ✓ CGMS: 353 рядків |  17.20% | ETA 13:30

   • RAM · 🧠 RAM: 451.5 MB

   ⏳ перед flush · 🧠 RAM: 451.5 MB

💾 batch 13036 → 14,588 рядків (всього 317,518 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13036.csv.gz

   ✅ після flush · 🧠 RAM: 453.0 MB

[1260/7269] ✓ CHAI: 277 рядків |  17.33% | ETA 13:33

[1270/7269] ✓ CHGG: 296 рядків |  17.47% | ETA 13:31

[1280/7269] ✓ CHPX: 45 рядків |  17.61% | ETA 13:30

[1290/7269] ✓ CHW: 171 рядків |  17.75% | ETA 13:29

[1300/7269] ✓ CIF: 384 рядків |  17.88% | ETA 13:28

   • RAM · 🧠 RAM: 453.7 MB

   ⏳ перед flush · 🧠 RAM: 453.7 MB

💾 batch 13037 → 11,496 рядків (всього 329,014 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13037.csv.gz

   ✅ після flush · 🧠 RAM: 454.5 MB

[1310/7269] ✓ CIG.C: 9 рядків |  18.02% | ETA 13:29

[1320/7269] ✓ CJMB: 240 рядків |  18.16% | ETA 13:30

[1330/7269] ✓ CLBT: 344 рядків |  18.30% | ETA 13:29

[1340/7269] ✓ CLNE: 435 рядків |  18.43% | ETA 13:28

[1350/7269] ✓ CLOU: 294 рядків |  18.57% | ETA 13:27

   • RAM · 🧠 RAM: 450.8 MB

   ⏳ перед flush · 🧠 RAM: 450.8 MB

💾 batch 13038 → 12,234 рядків (всього 341,248 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13038.csv.gz

   ✅ після flush · 🧠 RAM: 451.9 MB

[1360/7269] ✓ CLW: 147 рядків |  18.71% | ETA 13:28

[1370/7269] ✓ CMC: 368 рядків |  18.85% | ETA 13:27

[1380/7269] ✓ CMG: 539 рядків |  18.98% | ETA 13:27

[1390/7269] ✓ CNC: 405 рядків |  19.12% | ETA 13:27

[1400/7269] ✓ CNL: 71 рядків |  19.26% | ETA 13:26

   • RAM · 🧠 RAM: 453.7 MB

   ⏳ перед flush · 🧠 RAM: 453.7 MB

💾 batch 13039 → 12,651 рядків (всього 353,899 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13039.csv.gz

   ✅ після flush · 🧠 RAM: 454.6 MB

[1410/7269] ✓ CNSY: 65 рядків |  19.40% | ETA 13:27

[1420/7269] ✓ CNVS: 142 рядків |  19.54% | ETA 13:27

[1430/7269] ✓ COE: 37 рядків |  19.67% | ETA 13:26

[1440/7269] ✓ COIG: 79 рядків |  19.81% | ETA 13:25

[1450/7269] ✓ COLO: 152 рядків |  19.95% | ETA 13:24

   • RAM · 🧠 RAM: 449.9 MB

   ⏳ перед flush · 🧠 RAM: 449.9 MB

💾 batch 13040 → 11,482 рядків (всього 365,381 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13040.csv.gz

   ✅ після flush · 🧠 RAM: 451.0 MB

[1460/7269] ✓ CONX: 71 рядків |  20.09% | ETA 13:25

[1470/7269] ✓ CORZW: 48 рядків |  20.22% | ETA 13:25

[1480/7269] ✓ COTG: 48 рядків |  20.36% | ETA 13:24

[1490/7269] ✓ COZX: 30 рядків |  20.50% | ETA 13:22

[1500/7269] ✓ CPXR: 10 рядків |  20.64% | ETA 13:21

   • RAM · 🧠 RAM: 450.3 MB

   ⏳ перед flush · 🧠 RAM: 450.5 MB

💾 batch 13041 → 12,666 рядків (всього 378,047 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13041.csv.gz

   ✅ після flush · 🧠 RAM: 451.2 MB

[1510/7269] ✓ CR: 147 рядків |  20.77% | ETA 13:21

[1520/7269] ✓ CRCD: 311 рядків |  20.91% | ETA 13:20

[1530/7269] ✓ CRGO: 11 рядків |  21.05% | ETA 13:19

[1540/7269] ✓ CRML: 737 рядків |  21.19% | ETA 13:18

[1550/7269] ✓ CRNX: 353 рядків |  21.32% | ETA 13:17

   • RAM · 🧠 RAM: 450.9 MB

   ⏳ перед flush · 🧠 RAM: 450.9 MB

💾 batch 13042 → 16,781 рядків (всього 394,828 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13042.csv.gz

   ✅ після flush · 🧠 RAM: 452.2 MB

[1560/7269] ✓ CRUX: 104 рядків |  21.46% | ETA 13:17

[1570/7269] ✓ CSCO: 675 рядків |  21.60% | ETA 13:16

[1580/7269] ✓ CSTE: 117 рядків |  21.74% | ETA 13:15

[1590/7269] ✓ CSWC: 295 рядків |  21.87% | ETA 13:14

[1600/7269] ✓ CTM: 374 рядків |  22.01% | ETA 13:13

   • RAM · 🧠 RAM: 435.6 MB

   ⏳ перед flush · 🧠 RAM: 435.6 MB

💾 batch 13043 → 13,740 рядків (всього 408,568 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13043.csv.gz

   ✅ після flush · 🧠 RAM: 436.8 MB

[1610/7269] ✓ CUBI: 145 рядків |  22.15% | ETA 13:14

[1620/7269] ✓ CURE: 94 рядків |  22.29% | ETA 13:13

[1630/7269] ✓ CVLG: 164 рядків |  22.42% | ETA 13:12

[1640/7269] ✓ CW: 352 рядків |  22.56% | ETA 13:10

[1650/7269] ✓ CWEN: 365 рядків |  22.70% | ETA 13:09

   • RAM · 🧠 RAM: 428.5 MB

   ⏳ перед flush · 🧠 RAM: 428.5 MB

💾 batch 13044 → 10,534 рядків (всього 419,102 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13044.csv.gz

   ✅ після flush · 🧠 RAM: 429.4 MB

[1660/7269] ✓ CWH: 351 рядків |  22.84% | ETA 13:10

[1670/7269] ✓ CYH: 302 рядків |  22.97% | ETA 13:09

[1680/7269] ✓ CYTK: 365 рядків |  23.11% | ETA 13:08

[1690/7269] ✓ DAVA: 149 рядків |  23.25% | ETA 13:06

[1700/7269] ✓ DBRG: 271 рядків |  23.39% | ETA 13:05

   • RAM · 🧠 RAM: 429.3 MB

   ⏳ перед flush · 🧠 RAM: 429.3 MB

💾 batch 13045 → 11,712 рядків (всього 430,814 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13045.csv.gz

   ✅ після flush · 🧠 RAM: 429.5 MB

[1710/7269] ✓ DBX: 403 рядків |  23.52% | ETA 13:05

[1720/7269] ✓ DCI: 271 рядків |  23.66% | ETA 13:04

[1730/7269] ✓ DEC: 327 рядків |  23.80% | ETA 13:03

[1740/7269] ✓ DFAR: 353 рядків |  23.94% | ETA 13:02

[1750/7269] ✓ DFDV: 219 рядків |  24.07% | ETA 13:01

   • RAM · 🧠 RAM: 428.6 MB

   ⏳ перед flush · 🧠 RAM: 428.6 MB

💾 batch 13046 → 12,512 рядків (всього 443,326 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13046.csv.gz

   ✅ після flush · 🧠 RAM: 428.7 MB

[1760/7269] ✓ DFSD: 220 рядків |  24.21% | ETA 13:02

[1770/7269] ✓ DH: 164 рядків |  24.35% | ETA 13:01

[1780/7269] ✓ DIG: 91 рядків |  24.49% | ETA 12:59

[1790/7269] ✓ DIPS: 8 рядків |  24.63% | ETA 12:59

[1800/7269] ✓ DKI: 814 рядків |  24.76% | ETA 12:59

   • RAM · 🧠 RAM: 423.9 MB

   ⏳ перед flush · 🧠 RAM: 423.9 MB

💾 batch 13047 → 13,491 рядків (всього 456,817 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13047.csv.gz

   ✅ після flush · 🧠 RAM: 425.8 MB

[1810/7269] ✓ DLX: 238 рядків |  24.90% | ETA 13:00

[1820/7269] ✓ DNOW: 394 рядків |  25.04% | ETA 12:59

[1830/7269] ✓ DOCN: 406 рядків |  25.18% | ETA 12:58

[1840/7269] ✓ DOUG: 166 рядків |  25.31% | ETA 12:57

[1850/7269] ✓ DPZ: 402 рядків |  25.45% | ETA 12:57

   • RAM · 🧠 RAM: 423.9 MB

   ⏳ перед flush · 🧠 RAM: 423.9 MB

💾 batch 13048 → 12,463 рядків (всього 469,280 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13048.csv.gz

   ✅ після flush · 🧠 RAM: 424.6 MB

[1860/7269] ✓ DRIP: 410 рядків |  25.59% | ETA 12:57

[1870/7269] ✓ DRMA: 42 рядків |  25.73% | ETA 12:56

[1880/7269] ✓ DTCR: 350 рядків |  25.86% | ETA 12:55

[1890/7269] ✓ DTSS: 319 рядків |  26.00% | ETA 12:54

[1900/7269] ✓ DV: 409 рядків |  26.14% | ETA 12:53

   • RAM · 🧠 RAM: 420.5 MB

   ⏳ перед flush · 🧠 RAM: 420.5 MB

💾 batch 13049 → 11,379 рядків (всього 480,659 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13049.csv.gz

   ✅ після flush · 🧠 RAM: 421.4 MB

[1910/7269] ✓ DVYE: 217 рядків |  26.28% | ETA 12:54

[1920/7269] ✓ DZZ: 6 рядків |  26.41% | ETA 12:53

[1930/7269] – EA: empty |  26.55% | ETA 12:52

[1940/7269] ✓ EBND: 321 рядків |  26.69% | ETA 12:51

[1950/7269] ✓ ECHX: 117 рядків |  26.83% | ETA 12:50

   • RAM · 🧠 RAM: 418.8 MB

   ⏳ перед flush · 🧠 RAM: 418.9 MB

💾 batch 13050 → 11,605 рядків (всього 492,264 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13050.csv.gz

   ✅ після flush · 🧠 RAM: 419.3 MB

[1960/7269] ✓ EDC: 58 рядків |  26.96% | ETA 12:50

[1970/7269] ✓ EEMA: 49 рядків |  27.10% | ETA 12:50

[1980/7269] ✓ EFAA: 90 рядків |  27.24% | ETA 12:49

[1990/7269] ✓ EET: 23 рядків |  27.38% | ETA 12:48

[2000/7269] ✓ EGY: 320 рядків |  27.51% | ETA 12:48

   • RAM · 🧠 RAM: 416.3 MB

   ⏳ перед flush · 🧠 RAM: 416.3 MB

💾 batch 13051 → 9,195 рядків (всього 501,459 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13051.csv.gz

   ✅ після flush · 🧠 RAM: 417.8 MB

[2010/7269] ✓ EH: 352 рядків |  27.65% | ETA 12:50

[2020/7269] ✓ ELAN: 444 рядків |  27.79% | ETA 12:49

[2030/7269] ✓ ELPC: 280 рядків |  27.93% | ETA 12:48

[2040/7269] ✓ ELWT: 15 рядків |  28.06% | ETA 12:47

[2050/7269] ✓ EMN: 330 рядків |  28.20% | ETA 12:46

   • RAM · 🧠 RAM: 421.0 MB

   ⏳ перед flush · 🧠 RAM: 421.0 MB

💾 batch 13052 → 10,963 рядків (всього 512,422 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13052.csv.gz

   ✅ після flush · 🧠 RAM: 421.6 MB

[2060/7269] ✓ ENOV: 364 рядків |  28.34% | ETA 12:48

[2070/7269] ✓ ENSC: 980 рядків |  28.48% | ETA 12:48

[2080/7269] ✓ EONR: 181 рядків |  28.61% | ETA 12:48

[2090/7269] ✓ EPHE: 164 рядків |  28.75% | ETA 12:47

[2100/7269] ✓ EPSM: 28 рядків |  28.89% | ETA 12:48

   • RAM · 🧠 RAM: 407.3 MB

   ⏳ перед flush · 🧠 RAM: 407.3 MB

💾 batch 13053 → 12,866 рядків (всього 525,288 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13053.csv.gz

   ✅ після flush · 🧠 RAM: 407.8 MB

[2110/7269] ✓ EQR: 382 рядків |  29.03% | ETA 12:48

[2120/7269] ✓ ERO: 446 рядків |  29.16% | ETA 12:49

[2130/7269] ✓ ESI: 370 рядків |  29.30% | ETA 12:48

[2140/7269] ✓ ETG: 174 рядків |  29.44% | ETA 12:47

[2150/7269] ✓ ETHU: 992 рядків |  29.58% | ETA 12:47

   • RAM · 🧠 RAM: 399.2 MB

   ⏳ перед flush · 🧠 RAM: 399.2 MB

💾 batch 13054 → 13,379 рядків (всього 538,667 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13054.csv.gz

   ✅ після flush · 🧠 RAM: 399.7 MB

[2160/7269] ✓ ETR: 380 рядків |  29.72% | ETA 12:48

[2170/7269] ✓ EUV: 492 рядків |  29.85% | ETA 12:48

[2180/7269] ✓ EVGN: 600 рядків |  29.99% | ETA 12:47

[2190/7269] ✓ EVSM: 76 рядків |  30.13% | ETA 12:46

[2200/7269] ✓ EWJV: 81 рядків |  30.27% | ETA 12:46

   • RAM · 🧠 RAM: 402.3 MB

   ⏳ перед flush · 🧠 RAM: 402.3 MB

💾 batch 13055 → 12,219 рядків (всього 550,886 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13055.csv.gz

   ✅ після flush · 🧠 RAM: 404.5 MB

[2210/7269] ✓ EWU: 332 рядків |  30.40% | ETA 12:47

[2220/7269] ✓ EXK: 498 рядків |  30.54% | ETA 12:46

[2230/7269] ✓ EXTR: 381 рядків |  30.68% | ETA 12:45

[2240/7269] ✓ F: 676 рядків |  30.82% | ETA 12:45

[2250/7269] ✓ FANG: 392 рядків |  30.95% | ETA 12:44

   • RAM · 🧠 RAM: 407.8 MB

   ⏳ перед flush · 🧠 RAM: 407.8 MB

💾 batch 13056 → 14,418 рядків (всього 565,304 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13056.csv.gz

   ✅ після flush · 🧠 RAM: 409.8 MB

[2260/7269] ✓ FBIZ: 45 рядків |  31.09% | ETA 12:45

[2270/7269] ✓ FBRT: 300 рядків |  31.23% | ETA 12:44

[2280/7269] ✓ FCG: 367 рядків |  31.37% | ETA 12:43

[2290/7269] ✓ FDD: 112 рядків |  31.50% | ETA 12:42

[2300/7269] ✓ FDT: 97 рядків |  31.64% | ETA 12:41

   • RAM · 🧠 RAM: 411.9 MB

   ⏳ перед flush · 🧠 RAM: 411.9 MB

💾 batch 13057 → 10,369 рядків (всього 575,673 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13057.csv.gz

   ✅ після flush · 🧠 RAM: 413.0 MB

[2310/7269] ✓ FDXF: 325 рядків |  31.78% | ETA 12:41

[2320/7269] ✓ FERG: 397 рядків |  31.92% | ETA 12:41

[2330/7269] – FFIC: empty |  32.05% | ETA 12:40

[2340/7269] ✓ FG: 305 рядків |  32.19% | ETA 12:39

[2350/7269] ✓ FIDU: 86 рядків |  32.33% | ETA 12:38

   • RAM · 🧠 RAM: 407.6 MB

   ⏳ перед flush · 🧠 RAM: 407.7 MB

💾 batch 13058 → 12,080 рядків (всього 587,753 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13058.csv.gz

   ✅ після flush · 🧠 RAM: 409.1 MB

[2360/7269] ✓ FINX: 42 рядків |  32.47% | ETA 12:39

[2370/7269] – FIVY: empty |  32.60% | ETA 12:38

[2380/7269] ✓ FLG: 390 рядків |  32.74% | ETA 12:37

[2390/7269] ✓ FLOC: 306 рядків |  32.88% | ETA 12:36

[2400/7269] ✓ FLR: 411 рядків |  33.02% | ETA 12:36

   • RAM · 🧠 RAM: 408.4 MB

   ⏳ перед flush · 🧠 RAM: 408.4 MB

💾 batch 13059 → 12,802 рядків (всього 600,555 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13059.csv.gz

   ✅ після flush · 🧠 RAM: 410.1 MB

[2410/7269] ✓ FMC: 402 рядків |  33.15% | ETA 12:36

[2420/7269] ✓ FND: 377 рядків |  33.29% | ETA 12:35

[2430/7269] ✓ FNGU: 634 рядків |  33.43% | ETA 12:34

[2440/7269] – FONR: empty |  33.57% | ETA 12:32

[2450/7269] ✓ FOXY: 67 рядків |  33.70% | ETA 12:31

   • RAM · 🧠 RAM: 406.8 MB

   ⏳ перед flush · 🧠 RAM: 406.8 MB

💾 batch 13060 → 10,340 рядків (всього 610,895 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13060.csv.gz

   ✅ після flush · 🧠 RAM: 408.6 MB

[2460/7269] ✓ FPX: 40 рядків |  33.84% | ETA 12:31

[2470/7269] ✓ FRMI: 661 рядків |  33.98% | ETA 12:30

[2480/7269] ✓ FRT: 288 рядків |  34.12% | ETA 12:29

[2490/7269] ✓ FSLR: 462 рядків |  34.26% | ETA 12:28

[2500/7269] ✓ FTDR: 292 рядків |  34.39% | ETA 12:27

   • RAM · 🧠 RAM: 408.2 MB

   ⏳ перед flush · 🧠 RAM: 408.2 MB

💾 batch 13061 → 11,839 рядків (всього 622,734 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13061.csv.gz

   ✅ після flush · 🧠 RAM: 410.8 MB

[2510/7269] ✓ FTEC: 241 рядків |  34.53% | ETA 12:27

[2520/7269] ✓ FTRK: 85 рядків |  34.67% | ETA 12:25

[2530/7269] ✓ FURY: 135 рядків |  34.81% | ETA 12:24

[2540/7269] ✓ FWONA: 144 рядків |  34.94% | ETA 12:23

[2550/7269] ✓ FXN: 303 рядків |  35.08% | ETA 12:22

   • RAM · 🧠 RAM: 412.0 MB

   ⏳ перед flush · 🧠 RAM: 412.0 MB

💾 batch 13062 → 10,573 рядків (всього 633,307 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13062.csv.gz

   ✅ після flush · 🧠 RAM: 414.0 MB

[2560/7269] ✓ GANX: 186 рядків |  35.22% | ETA 12:22

[2570/7269] ✓ GBIL: 262 рядків |  35.36% | ETA 12:21

[2580/7269] ✓ GCT: 321 рядків |  35.49% | ETA 12:20

[2590/7269] ✓ GDDY: 388 рядків |  35.63% | ETA 12:19

[2600/7269] ✓ GDV: 132 рядків |  35.77% | ETA 12:18

   • RAM · 🧠 RAM: 416.8 MB

   ⏳ перед flush · 🧠 RAM: 416.8 MB

💾 batch 13063 → 12,247 рядків (всього 645,554 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13063.csv.gz

   ✅ після flush · 🧠 RAM: 422.2 MB

[2610/7269] ✓ GE: 432 рядків |  35.91% | ETA 12:18

[2620/7269] ✓ GENI: 402 рядків |  36.04% | ETA 12:17

[2630/7269] ✓ GEVG: 23 рядків |  36.18% | ETA 12:16

[2640/7269] ✓ GGG: 328 рядків |  36.32% | ETA 12:16

[2650/7269] ✓ GGLL: 629 рядків |  36.46% | ETA 12:15

   • RAM · 🧠 RAM: 415.8 MB

   ⏳ перед flush · 🧠 RAM: 415.8 MB

💾 batch 13064 → 14,461 рядків (всього 660,015 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13064.csv.gz

   ✅ після flush · 🧠 RAM: 418.3 MB

[2660/7269] – GIG: empty |  36.59% | ETA 12:15

[2670/7269] ✓ GLAD: 145 рядків |  36.73% | ETA 12:14

[2680/7269] – GLDY: empty |  36.87% | ETA 12:13

[2690/7269] ✓ GLIBA: 89 рядків |  37.01% | ETA 12:12

[2700/7269] ✓ GM: 421 рядків |  37.14% | ETA 12:11

   • RAM · 🧠 RAM: 409.4 MB

   ⏳ перед flush · 🧠 RAM: 409.6 MB

💾 batch 13065 → 11,697 рядків (всього 671,712 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13065.csv.gz

   ✅ після flush · 🧠 RAM: 411.6 MB

[2710/7269] ✓ GMM: 93 рядків |  37.28% | ETA 12:10

[2720/7269] ✓ GNR: 173 рядків |  37.42% | ETA 12:09

[2730/7269] – GOCOQ: empty |  37.56% | ETA 12:07

[2740/7269] ✓ GOOD: 224 рядків |  37.69% | ETA 12:06

[2750/7269] ✓ GOOX: 114 рядків |  37.83% | ETA 12:04

   • RAM · 🧠 RAM: 406.8 MB

   ⏳ перед flush · 🧠 RAM: 406.8 MB

💾 batch 13066 → 13,287 рядків (всього 684,999 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13066.csv.gz

   ✅ після flush · 🧠 RAM: 407.7 MB

[2760/7269] ✓ GOOW: 65 рядків |  37.97% | ETA 12:03

[2770/7269] ✓ GPT: 4 рядків |  38.11% | ETA 12:02

[2780/7269] ✓ GRAL: 346 рядків |  38.24% | ETA 12:01

[2790/7269] ✓ GRNI: 33 рядків |  38.38% | ETA 11:59

[2800/7269] ✓ GRSD: 155 рядків |  38.52% | ETA 11:58

   • RAM · 🧠 RAM: 410.5 MB

   ⏳ перед flush · 🧠 RAM: 410.5 MB

💾 batch 13067 → 12,128 рядків (всього 697,127 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13067.csv.gz

   ✅ після flush · 🧠 RAM: 412.4 MB

[2810/7269] ✓ GSK: 478 рядків |  38.66% | ETA 11:57

[2820/7269] ✓ GT: 451 рядків |  38.79% | ETA 11:55

[2830/7269] ✓ GTY: 200 рядків |  38.93% | ETA 11:54

[2840/7269] ✓ GVA: 276 рядків |  39.07% | ETA 11:52

[2850/7269] ✓ GXAI: 130 рядків |  39.21% | ETA 11:51

   • RAM · 🧠 RAM: 414.7 MB

   ⏳ перед flush · 🧠 RAM: 414.8 MB

💾 batch 13068 → 12,155 рядків (всього 709,282 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13068.csv.gz

   ✅ після flush · 🧠 RAM: 417.6 MB

[2860/7269] ✓ HAL: 442 рядків |  39.35% | ETA 11:50

[2870/7269] ✓ HBM: 474 рядків |  39.48% | ETA 11:49

[2880/7269] – HCHL: empty |  39.62% | ETA 11:47

[2890/7269] ✓ HCWB: 45 рядків |  39.76% | ETA 11:46

[2900/7269] ✓ HELE: 193 рядків |  39.90% | ETA 11:44

   • RAM · 🧠 RAM: 416.0 MB

   ⏳ перед flush · 🧠 RAM: 416.0 MB

💾 batch 13069 → 12,147 рядків (всього 721,429 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13069.csv.gz

   ✅ після flush · 🧠 RAM: 416.6 MB

[2910/7269] ✓ HFWA: 222 рядків |  40.03% | ETA 11:43

[2920/7269] ✓ HIHO: 148 рядків |  40.17% | ETA 11:42

[2930/7269] ✓ HKPD: 17 рядків |  40.31% | ETA 11:41

[2940/7269] ✓ HLP: 41 рядків |  40.45% | ETA 11:39

[2950/7269] ✓ HMN: 149 рядків |  40.58% | ETA 11:38

   • RAM · 🧠 RAM: 415.8 MB

   ⏳ перед flush · 🧠 RAM: 415.8 MB

💾 batch 13070 → 12,603 рядків (всього 734,032 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13070.csv.gz

   ✅ після flush · 🧠 RAM: 418.1 MB

[2960/7269] ✓ HOFT: 35 рядків |  40.72% | ETA 11:37

[2970/7269] – HONAV: empty |  40.86% | ETA 11:36

[2980/7269] ✓ HOPE: 278 рядків |  41.00% | ETA 11:34

[2990/7269] ✓ HPQ: 479 рядків |  41.13% | ETA 11:33

[3000/7269] ✓ HSDT: 155 рядків |  41.27% | ETA 11:31

   • RAM · 🧠 RAM: 414.0 MB

   ⏳ перед flush · 🧠 RAM: 414.0 MB

💾 batch 13071 → 11,637 рядків (всього 745,669 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13071.csv.gz

   ✅ після flush · 🧠 RAM: 416.4 MB

[3010/7269] ✓ HSAI: 430 рядків |  41.41% | ETA 11:31

[3020/7269] ✓ HTHT: 395 рядків |  41.55% | ETA 11:29

[3030/7269] ✓ HUBS: 468 рядків |  41.68% | ETA 11:28

[3040/7269] ✓ HUTG: 73 рядків |  41.82% | ETA 11:26

[3050/7269] ✓ HWC: 287 рядків |  41.96% | ETA 11:25

   • RAM · 🧠 RAM: 417.5 MB

   ⏳ перед flush · 🧠 RAM: 417.5 MB

💾 batch 13072 → 14,741 рядків (всього 760,410 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13072.csv.gz

   ✅ після flush · 🧠 RAM: 420.9 MB

[3060/7269] ✓ HYFT: 232 рядків |  42.10% | ETA 11:24

[3070/7269] ✓ IAG: 490 рядків |  42.23% | ETA 11:22

[3080/7269] ✓ IAUM: 563 рядків |  42.37% | ETA 11:21

[3090/7269] ✓ IBO: 46 рядків |  42.51% | ETA 11:19

[3100/7269] ✓ IBIT: 1,044 рядків |  42.65% | ETA 11:18

   • RAM · 🧠 RAM: 421.4 MB

   ⏳ перед flush · 🧠 RAM: 421.4 MB

💾 batch 13073 → 13,753 рядків (всього 774,163 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13073.csv.gz

   ✅ після flush · 🧠 RAM: 423.5 MB

[3110/7269] ✓ ICON: 27 рядків |  42.78% | ETA 11:17

[3120/7269] ✓ IDEQ: 175 рядків |  42.92% | ETA 11:16

[3130/7269] ✓ IDN: 147 рядків |  43.06% | ETA 11:14

[3140/7269] ✓ IDVO: 269 рядків |  43.20% | ETA 11:13

[3150/7269] ✓ IEP: 386 рядків |  43.33% | ETA 11:12

   • RAM · 🧠 RAM: 427.2 MB

   ⏳ перед flush · 🧠 RAM: 427.2 MB

💾 batch 13074 → 17,358 рядків (всього 791,521 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13074.csv.gz

   ✅ після flush · 🧠 RAM: 431.0 MB

[3160/7269] ✓ IGF: 347 рядків |  43.47% | ETA 11:11

[3170/7269] ✓ IGR: 285 рядків |  43.61% | ETA 11:10

[3180/7269] ✓ IHT: 23 рядків |  43.75% | ETA 11:08

[3190/7269] ✓ IJK: 167 рядків |  43.88% | ETA 11:07

[3200/7269] ✓ IMKTA: 101 рядків |  44.02% | ETA 11:05

   • RAM · 🧠 RAM: 432.3 MB

   ⏳ перед flush · 🧠 RAM: 432.3 MB

💾 batch 13075 → 10,987 рядків (всього 802,508 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13075.csv.gz

   ✅ після flush · 🧠 RAM: 431.7 MB

[3210/7269] ✓ IMNN: 62 рядків |  44.16% | ETA 11:04

[3220/7269] ✓ INBK: 61 рядків |  44.30% | ETA 11:03

[3230/7269] ✓ INDY: 160 рядків |  44.44% | ETA 11:01

[3240/7269] ✓ INHD: 1,136 рядків |  44.57% | ETA 11:00

[3250/7269] ✓ INN: 328 рядків |  44.71% | ETA 10:59

   • RAM · 🧠 RAM: 425.7 MB

   ⏳ перед flush · 🧠 RAM: 425.7 MB

💾 batch 13076 → 11,622 рядків (всього 814,130 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13076.csv.gz

   ✅ після flush · 🧠 RAM: 427.8 MB

[3260/7269] ✓ INSG: 310 рядків |  44.85% | ETA 10:58

[3270/7269] ✓ INTC: 1,406 рядків |  44.99% | ETA 10:56

[3280/7269] ✓ INYY: 63 рядків |  45.12% | ETA 10:55

[3290/7269] ✓ IONX: 350 рядків |  45.26% | ETA 10:53

[3300/7269] ✓ IP: 393 рядків |  45.40% | ETA 10:52

   • RAM · 🧠 RAM: 418.4 MB

   ⏳ перед flush · 🧠 RAM: 418.4 MB

💾 batch 13077 → 16,167 рядків (всього 830,297 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13077.csv.gz

   ✅ після flush · 🧠 RAM: 419.1 MB

[3310/7269] ✓ IPWR: 172 рядків |  45.54% | ETA 10:51

[3320/7269] ✓ IQMX: 193 рядків |  45.67% | ETA 10:49

[3330/7269] ✓ IRS: 141 рядків |  45.81% | ETA 10:48

[3340/7269] ✓ ISPY: 69 рядків |  45.95% | ETA 10:46

[3350/7269] ✓ ITOC: 22 рядків |  46.09% | ETA 10:45

   • RAM · 🧠 RAM: 420.4 MB

   ⏳ перед flush · 🧠 RAM: 420.4 MB

💾 batch 13078 → 12,035 рядків (всього 842,332 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13078.csv.gz

   ✅ після flush · 🧠 RAM: 422.4 MB

[3360/7269] ✓ ITW: 376 рядків |  46.22% | ETA 10:44

[3370/7269] ✓ IUSG: 309 рядків |  46.36% | ETA 10:42

[3380/7269] ✓ IWD: 374 рядків |  46.50% | ETA 10:41

[3390/7269] ✓ IWR: 362 рядків |  46.64% | ETA 10:39

[3400/7269] ✓ IXUS: 360 рядків |  46.77% | ETA 10:38

   • RAM · 🧠 RAM: 427.1 MB

   ⏳ перед flush · 🧠 RAM: 427.2 MB

💾 batch 13079 → 13,833 рядків (всього 856,165 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13079.csv.gz

   ✅ після flush · 🧠 RAM: 430.1 MB

[3410/7269] ✓ IZEA: 38 рядків |  46.91% | ETA 10:37

[3420/7269] ✓ JAGU: 53 рядків |  47.05% | ETA 10:36

[3430/7269] ✓ JBHT: 257 рядків |  47.19% | ETA 10:34

[3440/7269] ✓ JDZG: 212 рядків |  47.32% | ETA 10:33

[3450/7269] ✓ JD: 525 рядків |  47.46% | ETA 10:31

   • RAM · 🧠 RAM: 430.9 MB

   ⏳ перед flush · 🧠 RAM: 430.9 MB

💾 batch 13080 → 12,481 рядків (всього 868,646 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13080.csv.gz

   ✅ після flush · 🧠 RAM: 432.4 MB

[3460/7269] – JHG: empty |  47.60% | ETA 10:30

[3470/7269] ✓ JMSB: 57 рядків |  47.74% | ETA 10:29

[3480/7269] ✓ JNUG: 324 рядків |  47.87% | ETA 10:27

[3490/7269] ✓ JPLD: 261 рядків |  48.01% | ETA 10:26

[3500/7269] ✓ JPO: 38 рядків |  48.15% | ETA 10:24

   • RAM · 🧠 RAM: 429.5 MB

   ⏳ перед flush · 🧠 RAM: 429.5 MB

💾 batch 13081 → 11,149 рядків (всього 879,795 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13081.csv.gz

   ✅ після flush · 🧠 RAM: 431.8 MB

[3510/7269] ✓ KAI: 119 рядків |  48.29% | ETA 10:23

[3520/7269] – KALV: empty |  48.42% | ETA 10:22

[3530/7269] ✓ KBWY: 203 рядків |  48.56% | ETA 10:20

[3540/7269] ✓ KELYA: 220 рядків |  48.70% | ETA 10:18

[3550/7269] ✓ KEX: 274 рядків |  48.84% | ETA 10:17

   • RAM · 🧠 RAM: 430.1 MB

   ⏳ перед flush · 🧠 RAM: 430.1 MB

💾 batch 13082 → 9,414 рядків (всього 889,209 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13082.csv.gz

   ✅ після flush · 🧠 RAM: 431.2 MB

[3560/7269] ✓ KIM: 389 рядків |  48.98% | ETA 10:16

[3570/7269] ✓ KLIC: 390 рядків |  49.11% | ETA 10:14

[3580/7269] ✓ KMEM: 90 рядків |  49.25% | ETA 10:13

[3590/7269] ✓ KN: 244 рядків |  49.39% | ETA 10:11

[3600/7269] ✓ KODK: 314 рядків |  49.53% | ETA 10:10

   • RAM · 🧠 RAM: 431.9 MB

   ⏳ перед flush · 🧠 RAM: 432.0 MB

💾 batch 13083 → 13,087 рядків (всього 902,296 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13083.csv.gz

   ✅ після flush · 🧠 RAM: 434.9 MB

[3610/7269] ✓ KPDD: 63 рядків |  49.66% | ETA 10:09

[3620/7269] ✓ KRMD: 151 рядків |  49.80% | ETA 10:07

[3630/7269] ✓ KRUS: 92 рядків |  49.94% | ETA 10:06

[3640/7269] ✓ KSPI: 360 рядків |  50.08% | ETA 10:04

[3650/7269] ✓ KVHI: 168 рядків |  50.21% | ETA 10:03

   • RAM · 🧠 RAM: 434.2 MB

   ⏳ перед flush · 🧠 RAM: 434.2 MB

💾 batch 13084 → 13,525 рядків (всього 915,821 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13084.csv.gz

   ✅ після flush · 🧠 RAM: 436.7 MB

[3660/7269] ✓ KWEB: 529 рядків |  50.35% | ETA 10:02

[3670/7269] ✓ LABX: 392 рядків |  50.49% | ETA 10:00

[3680/7269] ✓ LAES: 740 рядків |  50.63% | ETA 09:59

[3690/7269] ✓ LBRDA: 178 рядків |  50.76% | ETA 09:57

[3700/7269] ✓ LCID: 576 рядків |  50.90% | ETA 09:56

   • RAM · 🧠 RAM: 439.4 MB

   ⏳ перед flush · 🧠 RAM: 439.5 MB

💾 batch 13085 → 13,397 рядків (всього 929,218 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13085.csv.gz

   ✅ після flush · 🧠 RAM: 441.7 MB

[3710/7269] ✓ LEE: 30 рядків |  51.04% | ETA 09:55

[3720/7269] ✓ LEXX: 12 рядків |  51.18% | ETA 09:53

[3730/7269] ✓ LFTO: 282 рядків |  51.31% | ETA 09:52

[3740/7269] ✓ LGND: 131 рядків |  51.45% | ETA 09:50

[3750/7269] ✓ LIDR: 365 рядків |  51.59% | ETA 09:49

   • RAM · 🧠 RAM: 445.3 MB

   ⏳ перед flush · 🧠 RAM: 445.4 MB

💾 batch 13086 → 10,778 рядків (всього 939,996 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13086.csv.gz

   ✅ після flush · 🧠 RAM: 452.0 MB

[3760/7269] ✓ LINC: 432 рядків |  51.73% | ETA 09:48

[3770/7269] ✓ LITX: 961 рядків |  51.86% | ETA 09:46

[3780/7269] ✓ LLYVA: 75 рядків |  52.00% | ETA 09:45

[3790/7269] – LMFA: empty |  52.14% | ETA 09:43

[3800/7269] ✓ LNT: 389 рядків |  52.28% | ETA 09:42

   • RAM · 🧠 RAM: 439.8 MB

   ⏳ перед flush · 🧠 RAM: 439.8 MB

💾 batch 13087 → 12,982 рядків (всього 952,978 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13087.csv.gz

   ✅ після flush · 🧠 RAM: 440.7 MB

[3810/7269] ✓ LOB: 134 рядків |  52.41% | ETA 09:40

[3820/7269] ✓ LOW: 407 рядків |  52.55% | ETA 09:39

[3830/7269] ✓ LPSN: 178 рядків |  52.69% | ETA 09:37

[3840/7269] ✓ LRHC: 548 рядків |  52.83% | ETA 09:36

[3850/7269] ✓ LTCC: 8 рядків |  52.96% | ETA 09:34

   • RAM · 🧠 RAM: 434.8 MB

   ⏳ перед flush · 🧠 RAM: 434.8 MB

💾 batch 13088 → 9,906 рядків (всього 962,884 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13088.csv.gz

   ✅ після flush · 🧠 RAM: 435.3 MB

[3860/7269] ✓ LUCY: 130 рядків |  53.10% | ETA 09:33

[3870/7269] ✓ LUXE: 52 рядків |  53.24% | ETA 09:32

[3880/7269] ✓ LVHI: 372 рядків |  53.38% | ETA 09:30

[3890/7269] ✓ LYEL: 151 рядків |  53.51% | ETA 09:28

[3900/7269] ✓ MAGX: 78 рядків |  53.65% | ETA 09:27

   • RAM · 🧠 RAM: 423.0 MB

   ⏳ перед flush · 🧠 RAM: 423.0 MB

💾 batch 13089 → 15,570 рядків (всього 978,454 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13089.csv.gz

   ✅ після flush · 🧠 RAM: 423.6 MB

[3910/7269] ✓ MAIA: 225 рядків |  53.79% | ETA 09:25

[3920/7269] ✓ MARS: 69 рядків |  53.93% | ETA 09:23

[3930/7269] ✓ MAT: 393 рядків |  54.07% | ETA 09:22

[3940/7269] ✓ MBIO: 27 рядків |  54.20% | ETA 09:20

[3950/7269] ✓ MCD: 589 рядків |  54.34% | ETA 09:18

   • RAM · 🧠 RAM: 424.4 MB

   ⏳ перед flush · 🧠 RAM: 424.4 MB

💾 batch 13090 → 12,718 рядків (всього 991,172 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13090.csv.gz

   ✅ після flush · 🧠 RAM: 424.8 MB

[3960/7269] ✓ MBRX: 367 рядків |  54.48% | ETA 09:16

[3970/7269] ✓ MCS: 190 рядків |  54.62% | ETA 09:15

[3980/7269] ✓ MDIA: 29 рядків |  54.75% | ETA 09:13

[3990/7269] ✓ MEDP: 238 рядків |  54.89% | ETA 09:11

[4000/7269] ✓ METC: 389 рядків |  55.03% | ETA 09:09

   • RAM · 🧠 RAM: 425.5 MB

   ⏳ перед flush · 🧠 RAM: 425.5 MB

💾 batch 13091 → 10,901 рядків (всього 1,002,073 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13091.csv.gz

   ✅ після flush · 🧠 RAM: 425.9 MB

[4010/7269] ✓ MFC: 388 рядків |  55.17% | ETA 09:07

[4020/7269] ✓ MGA: 332 рядків |  55.30% | ETA 09:06

[4030/7269] ✓ MGPI: 187 рядків |  55.44% | ETA 09:04

[4040/7269] ✓ MGX: 147 рядків |  55.58% | ETA 09:02

[4050/7269] ✓ MINE: 78 рядків |  55.72% | ETA 09:00

   • RAM · 🧠 RAM: 424.7 MB

   ⏳ перед flush · 🧠 RAM: 424.7 MB

💾 batch 13092 → 11,538 рядків (всього 1,013,611 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13092.csv.gz

   ✅ після flush · 🧠 RAM: 425.1 MB

[4060/7269] ✓ MITK: 365 рядків |  55.85% | ETA 08:59

[4070/7269] ✓ MLAB: 60 рядків |  55.99% | ETA 08:57

[4080/7269] ✓ MLPI: 304 рядків |  56.13% | ETA 08:55

[4090/7269] ✓ MMS: 295 рядків |  56.27% | ETA 08:53

[4100/7269] ✓ MNSB: 20 рядків |  56.40% | ETA 08:52

   • RAM · 🧠 RAM: 422.9 MB

   ⏳ перед flush · 🧠 RAM: 422.9 MB

💾 batch 13093 → 10,989 рядків (всього 1,024,600 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13093.csv.gz

   ✅ після flush · 🧠 RAM: 423.3 MB

[4110/7269] ✓ MNTK: 139 рядків |  56.54% | ETA 08:50

[4120/7269] ✓ MOO: 140 рядків |  56.68% | ETA 08:48

[4130/7269] ✓ MPLT: 320 рядків |  56.82% | ETA 08:46

[4140/7269] – MPX: empty |  56.95% | ETA 08:45

[4150/7269] ✓ MRDN: 113 рядків |  57.09% | ETA 08:43

   • RAM · 🧠 RAM: 420.5 MB

   ⏳ перед flush · 🧠 RAM: 420.5 MB

💾 batch 13094 → 12,012 рядків (всього 1,036,612 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13094.csv.gz

   ✅ після flush · 🧠 RAM: 421.0 MB

[4160/7269] ✓ MRTN: 242 рядків |  57.23% | ETA 08:41

[4170/7269] ✓ MSA: 140 рядків |  57.37% | ETA 08:39

[4180/7269] ✓ MSFO: 72 рядків |  57.50% | ETA 08:38

[4190/7269] ✓ MSGY: 246 рядків |  57.64% | ETA 08:36

[4200/7269] ✓ MSTP: 42 рядків |  57.78% | ETA 08:34

   • RAM · 🧠 RAM: 419.2 MB

   ⏳ перед flush · 🧠 RAM: 419.2 MB

💾 batch 13095 → 11,891 рядків (всього 1,048,503 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13095.csv.gz

   ✅ після flush · 🧠 RAM: 419.6 MB

[4210/7269] ✓ MTBA: 112 рядків |  57.92% | ETA 08:33

[4220/7269] ✓ MTD: 371 рядків |  58.05% | ETA 08:31

[4230/7269] ✓ MTUS: 175 рядків |  58.19% | ETA 08:29

[4240/7269] ✓ MTW: 292 рядків |  58.33% | ETA 08:27

[4250/7269] ✓ MUYY: 48 рядків |  58.47% | ETA 08:26

   • RAM · 🧠 RAM: 418.1 MB

   ⏳ перед flush · 🧠 RAM: 418.1 MB

💾 batch 13096 → 18,526 рядків (всього 1,067,029 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13096.csv.gz

   ✅ після flush · 🧠 RAM: 419.5 MB

[4260/7269] ✓ MYE: 241 рядків |  58.61% | ETA 08:24

[4270/7269] ✓ MYO: 275 рядків |  58.74% | ETA 08:22

[4280/7269] ✓ NAIL: 401 рядків |  58.88% | ETA 08:20

[4290/7269] ✓ NB: 496 рядків |  59.02% | ETA 08:19

[4300/7269] ✓ NATR: 200 рядків |  59.16% | ETA 08:17

   • RAM · 🧠 RAM: 420.8 MB

   ⏳ перед flush · 🧠 RAM: 420.8 MB

💾 batch 13097 → 15,560 рядків (всього 1,082,589 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13097.csv.gz

   ✅ після flush · 🧠 RAM: 421.4 MB

[4310/7269] ✓ NCEL: 21 рядків |  59.29% | ETA 08:15

[4320/7269] ✓ NCNA: 38 рядків |  59.43% | ETA 08:14

[4330/7269] ✓ NEE: 466 рядків |  59.57% | ETA 08:12

[4340/7269] ✓ NEOV: 288 рядків |  59.71% | ETA 08:10

[4350/7269] ✓ NEXR: 284 рядків |  59.84% | ETA 08:08

   • RAM · 🧠 RAM: 422.4 MB

   ⏳ перед flush · 🧠 RAM: 422.4 MB

💾 batch 13098 → 11,467 рядків (всього 1,094,056 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13098.csv.gz

   ✅ після flush · 🧠 RAM: 423.0 MB

[4360/7269] ✓ NFGC: 299 рядків |  59.98% | ETA 08:07

[4370/7269] ✓ NHC: 90 рядків |  60.12% | ETA 08:05

[4380/7269] ✓ NHP: 288 рядків |  60.26% | ETA 08:03

[4390/7269] ✓ NKLR: 153 рядків |  60.39% | ETA 08:01

[4400/7269] ✓ NKTX: 232 рядків |  60.53% | ETA 08:00

   • RAM · 🧠 RAM: 419.8 MB

   ⏳ перед flush · 🧠 RAM: 419.8 MB

💾 batch 13099 → 11,097 рядків (всього 1,105,153 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13099.csv.gz

   ✅ після flush · 🧠 RAM: 420.2 MB

[4410/7269] ✓ NMR: 317 рядків |  60.67% | ETA 07:58

[4420/7269] ✓ NNDM: 402 рядків |  60.81% | ETA 07:56

[4430/7269] ✓ NOWL: 723 рядків |  60.94% | ETA 07:55

[4440/7269] ✓ NPWR: 223 рядків |  61.08% | ETA 07:53

[4450/7269] ✓ NRG: 422 рядків |  61.22% | ETA 07:51

   • RAM · 🧠 RAM: 410.4 MB

   ⏳ перед flush · 🧠 RAM: 410.4 MB

💾 batch 13100 → 13,146 рядків (всього 1,118,299 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13100.csv.gz

   ✅ після flush · 🧠 RAM: 410.9 MB

[4460/7269] ✓ NRO: 129 рядків |  61.36% | ETA 07:50

[4470/7269] ✓ NTCL: 51 рядків |  61.49% | ETA 07:48

[4480/7269] ✓ NTR: 403 рядків |  61.63% | ETA 07:46

[4490/7269] ✓ NUKZ: 97 рядків |  61.77% | ETA 07:44

[4500/7269] – NVA_20260602: empty |  61.91% | ETA 07:43

   • RAM · 🧠 RAM: 403.2 MB

   ⏳ перед flush · 🧠 RAM: 403.2 MB

💾 batch 13101 → 11,391 рядків (всього 1,129,690 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13101.csv.gz

   ✅ після flush · 🧠 RAM: 403.7 MB

[4510/7269] ✓ NVDS: 217 рядків |  62.04% | ETA 07:41

[4520/7269] ✓ NVII: 136 рядків |  62.18% | ETA 07:39

[4530/7269] ✓ NVS: 371 рядків |  62.32% | ETA 07:38

[4540/7269] ✓ NVTX: 320 рядків |  62.46% | ETA 07:36

[4550/7269] ✓ NXDR: 373 рядків |  62.59% | ETA 07:34

   • RAM · 🧠 RAM: 393.2 MB

   ⏳ перед flush · 🧠 RAM: 393.2 MB

💾 batch 13102 → 15,558 рядків (всього 1,145,248 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13102.csv.gz

   ✅ після flush · 🧠 RAM: 390.8 MB

[4560/7269] ✓ NXTC: 486 рядків |  62.73% | ETA 07:32

[4570/7269] ✓ NYXH: 84 рядків |  62.87% | ETA 07:31

[4580/7269] ✓ OBT: 64 рядків |  63.01% | ETA 07:29

[4590/7269] ✓ ODFL: 376 рядків |  63.14% | ETA 07:27

[4600/7269] ✓ ODTX: 81 рядків |  63.28% | ETA 07:25

   • RAM · 🧠 RAM: 383.4 MB

   ⏳ перед flush · 🧠 RAM: 383.4 MB

💾 batch 13103 → 10,848 рядків (всього 1,156,096 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13103.csv.gz

   ✅ після flush · 🧠 RAM: 383.9 MB

[4610/7269] ✓ OGEN: 37 рядків |  63.42% | ETA 07:24

[4620/7269] ✓ OILK: 101 рядків |  63.56% | ETA 07:22

[4630/7269] ✓ OKLL: 843 рядків |  63.70% | ETA 07:20

[4640/7269] ✓ OLMA: 336 рядків |  63.83% | ETA 07:19

[4650/7269] ✓ ONC: 454 рядків |  63.97% | ETA 07:17

   • RAM · 🧠 RAM: 384.8 MB

   ⏳ перед flush · 🧠 RAM: 384.8 MB

💾 batch 13104 → 13,455 рядків (всього 1,169,551 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13104.csv.gz

   ✅ після flush · 🧠 RAM: 385.3 MB

[4660/7269] ✓ ONEG: 33 рядків |  64.11% | ETA 07:15

[4670/7269] ✓ OOMA: 188 рядків |  64.25% | ETA 07:14

[4680/7269] ✓ OPBK: 54 рядків |  64.38% | ETA 07:12

[4690/7269] ✓ OPTH: 23 рядків |  64.52% | ETA 07:10

[4700/7269] ✓ ORA: 357 рядків |  64.66% | ETA 07:08

   • RAM · 🧠 RAM: 383.1 MB

   ⏳ перед flush · 🧠 RAM: 383.1 MB

💾 batch 13105 → 13,451 рядків (всього 1,183,002 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13105.csv.gz

   ✅ після flush · 🧠 RAM: 383.7 MB

[4710/7269] ✓ ORIC: 351 рядків |  64.80% | ETA 07:07

[4720/7269] ✓ ORN: 278 рядків |  64.93% | ETA 07:05

[4730/7269] ✓ OSCR: 549 рядків |  65.07% | ETA 07:03

[4740/7269] ✓ OTF: 373 рядків |  65.21% | ETA 07:02

[4750/7269] ✓ OVBC: 90 рядків |  65.35% | ETA 07:00

   • RAM · 🧠 RAM: 368.9 MB

   ⏳ перед flush · 🧠 RAM: 368.9 MB

💾 batch 13106 → 13,228 рядків (всього 1,196,230 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13106.csv.gz

   ✅ після flush · 🧠 RAM: 369.5 MB

[4760/7269] ✓ OXBR: 10 рядків |  65.48% | ETA 06:58

[4770/7269] – PAAU: empty |  65.62% | ETA 06:57

[4780/7269] ✓ PALU: 175 рядків |  65.76% | ETA 06:55

[4790/7269] ✓ PAVE: 409 рядків |  65.90% | ETA 06:53

[4800/7269] ✓ PAXS: 230 рядків |  66.03% | ETA 06:51

   • RAM · 🧠 RAM: 365.4 MB

   ⏳ перед flush · 🧠 RAM: 365.4 MB

💾 batch 13107 → 12,431 рядків (всього 1,208,661 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13107.csv.gz

   ✅ після flush · 🧠 RAM: 367.0 MB

[4810/7269] ✓ PAYX: 385 рядків |  66.17% | ETA 06:50

[4820/7269] ✓ PBI: 319 рядків |  66.31% | ETA 06:48

[4830/7269] ✓ PBYI: 240 рядків |  66.45% | ETA 06:46

[4840/7269] ✓ PDC: 33 рядків |  66.58% | ETA 06:45

[4850/7269] ✓ PDLB: 63 рядків |  66.72% | ETA 06:43

   • RAM · 🧠 RAM: 359.4 MB

   ⏳ перед flush · 🧠 RAM: 359.4 MB

💾 batch 13108 → 12,332 рядків (всього 1,220,993 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13108.csv.gz

   ✅ після flush · 🧠 RAM: 360.0 MB

[4860/7269] ✓ PDYN: 406 рядків |  66.86% | ETA 06:41

[4870/7269] ✓ PERI: 373 рядків |  67.00% | ETA 06:40

[4880/7269] ✓ PFE: 809 рядків |  67.13% | ETA 06:38

[4890/7269] ✓ PFLT: 360 рядків |  67.27% | ETA 06:36

[4900/7269] ✓ PHAR: 40 рядків |  67.41% | ETA 06:35

   • RAM · 🧠 RAM: 357.3 MB

   ⏳ перед flush · 🧠 RAM: 357.3 MB

💾 batch 13109 → 12,862 рядків (всього 1,233,855 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13109.csv.gz

   ✅ після flush · 🧠 RAM: 357.9 MB

[4910/7269] ✓ PHOE: 59 рядків |  67.55% | ETA 06:33

[4920/7269] ✓ PICK: 336 рядків |  67.68% | ETA 06:31

[4930/7269] ✓ PILL: 49 рядків |  67.82% | ETA 06:30

[4940/7269] ✓ PLAG: 89 рядків |  67.96% | ETA 06:28

[4950/7269] ✓ PLD: 407 рядків |  68.10% | ETA 06:26

   • RAM · 🧠 RAM: 356.1 MB

   ⏳ перед flush · 🧠 RAM: 356.1 MB

💾 batch 13110 → 12,253 рядків (всього 1,246,108 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13110.csv.gz

   ✅ після flush · 🧠 RAM: 356.7 MB

[4960/7269] ✓ PLTU: 831 рядків |  68.23% | ETA 06:25

[4970/7269] ✓ PLUG: 1,271 рядків |  68.37% | ETA 06:23

[4980/7269] ✓ PMEC: 17 рядків |  68.51% | ETA 06:21

[4990/7269] ✓ PNAQ.U: 368 рядків |  68.65% | ETA 06:19

[5000/7269] ✓ PNNT: 286 рядків |  68.79% | ETA 06:18

   • RAM · 🧠 RAM: 358.1 MB

   ⏳ перед flush · 🧠 RAM: 358.1 MB

💾 batch 13111 → 12,639 рядків (всього 1,258,747 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13111.csv.gz

   ✅ після flush · 🧠 RAM: 358.8 MB

[5010/7269] ✓ POR: 318 рядків |  68.92% | ETA 06:16

[5020/7269] ✓ PPH: 171 рядків |  69.06% | ETA 06:14

[5030/7269] ✓ PRAX: 334 рядків |  69.20% | ETA 06:13

[5040/7269] ✓ PRGS: 202 рядків |  69.34% | ETA 06:11

[5050/7269] ✓ PROF: 59 рядків |  69.47% | ETA 06:09

   • RAM · 🧠 RAM: 360.0 MB

   ⏳ перед flush · 🧠 RAM: 360.0 MB

💾 batch 13112 → 12,923 рядків (всього 1,271,670 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13112.csv.gz

   ✅ після flush · 🧠 RAM: 360.6 MB

[5060/7269] ✓ PRTH: 267 рядків |  69.61% | ETA 06:08

[5070/7269] ✓ PSCE: 28 рядків |  69.75% | ETA 06:06

[5080/7269] ✓ PSI: 254 рядків |  69.89% | ETA 06:04

[5090/7269] ✓ PSNYW: 198 рядків |  70.02% | ETA 06:02

[5100/7269] ✓ PTIR: 767 рядків |  70.16% | ETA 06:01

   • RAM · 🧠 RAM: 357.0 MB

   ⏳ перед flush · 🧠 RAM: 357.0 MB

💾 batch 13113 → 11,664 рядків (всього 1,283,334 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13113.csv.gz

   ✅ після flush · 🧠 RAM: 357.7 MB

[5110/7269] ✓ PULM: 5 рядків |  70.30% | ETA 05:59

[5120/7269] ✓ PULS: 395 рядків |  70.44% | ETA 05:57

[5130/7269] ✓ PYXS: 357 рядків |  70.57% | ETA 05:56

[5140/7269] ✓ QBTZ: 409 рядків |  70.71% | ETA 05:54

[5150/7269] ✓ QDVO: 263 рядків |  70.85% | ETA 05:52

   • RAM · 🧠 RAM: 353.3 MB

   ⏳ перед flush · 🧠 RAM: 353.3 MB

💾 batch 13114 → 11,980 рядків (всього 1,295,314 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13114.csv.gz

   ✅ після flush · 🧠 RAM: 354.8 MB

[5160/7269] ✓ QH: 46 рядків |  70.99% | ETA 05:51

[5170/7269] ✓ QLYS: 319 рядків |  71.12% | ETA 05:49

[5180/7269] ✓ QQQD: 40 рядків |  71.26% | ETA 05:47

[5190/7269] ✓ QQQX: 97 рядків |  71.40% | ETA 05:46

[5200/7269] ✓ QSU: 95 рядків |  71.54% | ETA 05:44

   • RAM · 🧠 RAM: 346.2 MB

   ⏳ перед flush · 🧠 RAM: 346.2 MB

💾 batch 13115 → 13,740 рядків (всього 1,309,054 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13115.csv.gz

   ✅ після flush · 🧠 RAM: 346.9 MB

[5210/7269] ✓ QTRX: 461 рядків |  71.67% | ETA 05:42

[5220/7269] ✓ QXO: 474 рядків |  71.81% | ETA 05:41

[5230/7269] ✓ RAML: 10 рядків |  71.95% | ETA 05:39

[5240/7269] ✓ RBB: 113 рядків |  72.09% | ETA 05:37

[5250/7269] ✓ RBLU: 276 рядків |  72.22% | ETA 05:36

   • RAM · 🧠 RAM: 348.1 MB

   ⏳ перед flush · 🧠 RAM: 348.1 MB

💾 batch 13116 → 12,459 рядків (всього 1,321,513 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13116.csv.gz

   ✅ після flush · 🧠 RAM: 348.7 MB

[5260/7269] ✓ RCI: 376 рядків |  72.36% | ETA 05:34

[5270/7269] ✓ RDHL: 44 рядків |  72.50% | ETA 05:32

[5280/7269] ✓ RDVT: 208 рядків |  72.64% | ETA 05:31

[5290/7269] ✓ RDY: 365 рядків |  72.77% | ETA 05:29

[5300/7269] ✓ REF: 198 рядків |  72.91% | ETA 05:27

   • RAM · 🧠 RAM: 350.0 MB

   ⏳ перед flush · 🧠 RAM: 350.0 MB

💾 batch 13117 → 14,974 рядків (всього 1,336,487 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13117.csv.gz

   ✅ після flush · 🧠 RAM: 350.8 MB

[5310/7269] ✓ REPL: 547 рядків |  73.05% | ETA 05:26

[5320/7269] ✓ REZ: 61 рядків |  73.19% | ETA 05:24

[5330/7269] ✓ RFIL: 212 рядків |  73.33% | ETA 05:22

[5340/7269] ✓ RGTZ: 542 рядків |  73.46% | ETA 05:20

[5350/7269] ✓ RIG: 515 рядків |  73.60% | ETA 05:19

   • RAM · 🧠 RAM: 351.8 MB

   ⏳ перед flush · 🧠 RAM: 351.8 MB

💾 batch 13118 → 12,532 рядків (всього 1,349,019 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13118.csv.gz

   ✅ після flush · 🧠 RAM: 352.3 MB

[5360/7269] ✓ RIVN: 694 рядків |  73.74% | ETA 05:17

[5370/7269] ✓ RKX: 42 рядків |  73.88% | ETA 05:15

[5380/7269] ✓ RMBC: 3 рядків |  74.01% | ETA 05:14

[5390/7269] ✓ RMTI: 133 рядків |  74.15% | ETA 05:12

[5400/7269] ✓ RNXT: 99 рядків |  74.29% | ETA 05:10

   • RAM · 🧠 RAM: 352.2 MB

   ⏳ перед flush · 🧠 RAM: 352.2 MB

💾 batch 13119 → 14,811 рядків (всього 1,363,830 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13119.csv.gz

   ✅ після flush · 🧠 RAM: 353.0 MB

[5410/7269] ✓ ROG: 89 рядків |  74.43% | ETA 05:09

[5420/7269] ✓ RONB: 267 рядків |  74.56% | ETA 05:07

[5430/7269] ✓ RPRX: 396 рядків |  74.70% | ETA 05:05

[5440/7269] ✓ RRX: 357 рядків |  74.84% | ETA 05:04

[5450/7269] ✓ RSVR: 28 рядків |  74.98% | ETA 05:02

   • RAM · 🧠 RAM: 351.9 MB

   ⏳ перед flush · 🧠 RAM: 351.9 MB

💾 batch 13120 → 11,635 рядків (всього 1,375,465 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13120.csv.gz

   ✅ після flush · 🧠 RAM: 352.4 MB

[5460/7269] ✓ RUN: 567 рядків |  75.11% | ETA 05:00

[5470/7269] – RVYL: empty |  75.25% | ETA 04:59

[5480/7269] ✓ RWM: 258 рядків |  75.39% | ETA 04:57

[5490/7269] ✓ RYOJ: 104 рядків |  75.53% | ETA 04:55

[5500/7269] ✓ S: 470 рядків |  75.66% | ETA 04:54

   • RAM · 🧠 RAM: 349.8 MB

   ⏳ перед flush · 🧠 RAM: 349.8 MB

💾 batch 13121 → 13,128 рядків (всього 1,388,593 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13121.csv.gz

   ✅ після flush · 🧠 RAM: 350.4 MB

[5510/7269] ✓ SAIC: 218 рядків |  75.80% | ETA 04:52

[5520/7269] ✓ SAN: 429 рядків |  75.94% | ETA 04:50

[5530/7269] ✓ SBEV: 208 рядків |  76.08% | ETA 04:49

[5540/7269] ✓ SBSI: 83 рядків |  76.21% | ETA 04:47

[5550/7269] ✓ SCHC: 210 рядків |  76.35% | ETA 04:45

   • RAM · 🧠 RAM: 350.7 MB

   ⏳ перед flush · 🧠 RAM: 350.7 MB

💾 batch 13122 → 12,834 рядків (всього 1,401,427 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13122.csv.gz

   ✅ після flush · 🧠 RAM: 351.4 MB

[5560/7269] ✓ SCHH: 384 рядків |  76.49% | ETA 04:44

[5570/7269] ✓ SCHW: 403 рядків |  76.63% | ETA 04:42

[5580/7269] ✓ SCUS: 66 рядків |  76.76% | ETA 04:40

[5590/7269] ✓ SCZ: 331 рядків |  76.90% | ETA 04:39

[5600/7269] ✓ SDTY: 24 рядків |  77.04% | ETA 04:37

   • RAM · 🧠 RAM: 350.0 MB

   ⏳ перед flush · 🧠 RAM: 350.0 MB

💾 batch 13123 → 13,663 рядків (всього 1,415,090 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13123.csv.gz

   ✅ після flush · 🧠 RAM: 350.6 MB

[5610/7269] ✓ SEER: 116 рядків |  77.18% | ETA 04:35

[5620/7269] ✓ SENS: 369 рядків |  77.31% | ETA 04:34

[5630/7269] ✓ SF: 352 рядків |  77.45% | ETA 04:32

[5640/7269] ✓ SFM: 383 рядків |  77.59% | ETA 04:30

[5650/7269] ✓ SGRT: 25 рядків |  77.73% | ETA 04:28

   • RAM · 🧠 RAM: 351.7 MB

   ⏳ перед flush · 🧠 RAM: 351.7 MB

💾 batch 13124 → 10,870 рядків (всього 1,425,960 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13124.csv.gz

   ✅ після flush · 🧠 RAM: 352.3 MB

[5660/7269] ✓ SHC: 375 рядків |  77.86% | ETA 04:27

[5670/7269] ✓ SHG: 179 рядків |  78.00% | ETA 04:25

[5680/7269] ✓ SHPU: 112 рядків |  78.14% | ETA 04:23

[5690/7269] ✓ SID: 325 рядків |  78.28% | ETA 04:22

[5700/7269] ✓ SIMX: 41 рядків |  78.42% | ETA 04:20

   • RAM · 🧠 RAM: 352.8 MB

   ⏳ перед flush · 🧠 RAM: 352.8 MB

💾 batch 13125 → 14,693 рядків (всього 1,440,653 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13125.csv.gz

   ✅ після flush · 🧠 RAM: 353.5 MB

[5710/7269] ✓ SIVR: 503 рядків |  78.55% | ETA 04:19

[5720/7269] ✓ SKHN: 32 рядків |  78.69% | ETA 04:17

[5730/7269] ✓ SKHX: 857 рядків |  78.83% | ETA 04:15

[5740/7269] ✓ SKYX: 332 рядків |  78.97% | ETA 04:14

[5750/7269] ✓ SLE: 21 рядків |  79.10% | ETA 04:12

   • RAM · 🧠 RAM: 354.5 MB

   ⏳ перед flush · 🧠 RAM: 354.5 MB

💾 batch 13126 → 15,544 рядків (всього 1,456,197 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13126.csv.gz

   ✅ після flush · 🧠 RAM: 355.9 MB

[5760/7269] ✓ SLND: 220 рядків |  79.24% | ETA 04:10

[5770/7269] ✓ SLP: 184 рядків |  79.38% | ETA 04:09

[5780/7269] ✓ SLVX: 60 рядків |  79.52% | ETA 04:07

[5790/7269] ✓ SMCY: 363 рядків |  79.65% | ETA 04:05

[5800/7269] ✓ SMHD: 10 рядків |  79.79% | ETA 04:03

   • RAM · 🧠 RAM: 353.3 MB

   ⏳ перед flush · 🧠 RAM: 353.3 MB

💾 batch 13127 → 14,577 рядків (всього 1,470,774 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13127.csv.gz

   ✅ після flush · 🧠 RAM: 354.0 MB

[5810/7269] ✓ SMRT: 313 рядків |  79.93% | ETA 04:02

[5820/7269] ✓ SMYY: 29 рядків |  80.07% | ETA 04:00

[5830/7269] ✓ SNAG: 16 рядків |  80.20% | ETA 03:58

[5840/7269] ✓ SNDQ: 1,077 рядків |  80.34% | ETA 03:57

[5850/7269] ✓ SNOU: 91 рядків |  80.48% | ETA 03:55

   • RAM · 🧠 RAM: 344.0 MB

   ⏳ перед flush · 🧠 RAM: 344.0 MB

💾 batch 13128 → 15,906 рядків (всього 1,486,680 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13128.csv.gz

   ✅ після flush · 🧠 RAM: 344.8 MB

[5860/7269] ✓ SNXX: 941 рядків |  80.62% | ETA 03:54

[5870/7269] ✓ SOFA: 48 рядків |  80.75% | ETA 03:52

[5880/7269] ✓ SONM: 11 рядків |  80.89% | ETA 03:50

[5890/7269] ✓ SOUX: 176 рядків |  81.03% | ETA 03:48

[5900/7269] ✓ SPAX: 840 рядків |  81.17% | ETA 03:47

   • RAM · 🧠 RAM: 346.4 MB

   ⏳ перед flush · 🧠 RAM: 346.4 MB

💾 batch 13129 → 18,265 рядків (всього 1,504,945 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13129.csv.gz

   ✅ після flush · 🧠 RAM: 347.8 MB

[5910/7269] ✓ SPCU: 761 рядків |  81.30% | ETA 03:45

[5920/7269] ✓ SPGP: 92 рядків |  81.44% | ETA 03:44

[5930/7269] ✓ SPIB: 358 рядків |  81.58% | ETA 03:42

[5940/7269] ✓ SPPL: 24 рядків |  81.72% | ETA 03:40

[5950/7269] ✓ SPRY: 339 рядків |  81.85% | ETA 03:38

   • RAM · 🧠 RAM: 349.4 MB

   ⏳ перед flush · 🧠 RAM: 349.4 MB

💾 batch 13130 → 15,686 рядків (всього 1,520,631 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13130.csv.gz

   ✅ після flush · 🧠 RAM: 350.1 MB

[5960/7269] ✓ SPTS: 233 рядків |  81.99% | ETA 03:37

[5970/7269] ✓ SPXU: 551 рядків |  82.13% | ETA 03:35

[5980/7269] ✓ SPYV: 397 рядків |  82.27% | ETA 03:33

[5990/7269] ✓ SRFM: 582 рядків |  82.40% | ETA 03:32

[6000/7269] ✓ SRTS: 20 рядків |  82.54% | ETA 03:30

   • RAM · 🧠 RAM: 351.3 MB

   ⏳ перед flush · 🧠 RAM: 351.3 MB

💾 batch 13131 → 15,914 рядків (всього 1,536,545 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13131.csv.gz

   ✅ після flush · 🧠 RAM: 352.0 MB

[6010/7269] ✓ SSNC: 340 рядків |  82.68% | ETA 03:28

[6020/7269] ✓ STAK: 481 рядків |  82.82% | ETA 03:27

[6030/7269] ✓ STEM: 176 рядків |  82.96% | ETA 03:25

[6040/7269] ✓ STI: 650 рядків |  83.09% | ETA 03:23

[6050/7269] ✓ STN: 222 рядків |  83.23% | ETA 03:22

   • RAM · 🧠 RAM: 350.9 MB

   ⏳ перед flush · 🧠 RAM: 350.9 MB

💾 batch 13132 → 14,509 рядків (всього 1,551,054 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13132.csv.gz

   ✅ після flush · 🧠 RAM: 351.6 MB

[6060/7269] ✓ STRR: 5 рядків |  83.37% | ETA 03:20

[6070/7269] ✓ STWD: 397 рядків |  83.51% | ETA 03:18

[6080/7269] ✓ SUI: 343 рядків |  83.64% | ETA 03:17

[6090/7269] ✓ SUNE: 129 рядків |  83.78% | ETA 03:15

[6100/7269] ✓ SUNB: 369 рядків |  83.92% | ETA 03:13

   • RAM · 🧠 RAM: 351.5 MB

   ⏳ перед flush · 🧠 RAM: 351.5 MB

💾 batch 13133 → 12,442 рядків (всього 1,563,496 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13133.csv.gz

   ✅ після flush · 🧠 RAM: 352.0 MB

[6110/7269] ✓ SWBI: 224 рядків |  84.06% | ETA 03:12

[6120/7269] ✓ SXI: 157 рядків |  84.19% | ETA 03:10

[6130/7269] ✓ SYF: 386 рядків |  84.33% | ETA 03:08

[6140/7269] ✓ TAN: 337 рядків |  84.47% | ETA 03:07

[6150/7269] ✓ TARA: 228 рядків |  84.61% | ETA 03:05

   • RAM · 🧠 RAM: 352.1 MB

   ⏳ перед flush · 🧠 RAM: 352.1 MB

💾 batch 13134 → 11,582 рядків (всього 1,575,078 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13134.csv.gz

   ✅ після flush · 🧠 RAM: 352.6 MB

[6160/7269] ✓ TBPH: 224 рядків |  84.74% | ETA 03:04

[6170/7269] ✓ TCBX: 73 рядків |  84.88% | ETA 03:02

[6180/7269] ✓ TCRX: 195 рядків |  85.02% | ETA 03:00

[6190/7269] ✓ TDOC: 403 рядків |  85.16% | ETA 02:59

[6200/7269] ✓ TELO: 105 рядків |  85.29% | ETA 02:57

   • RAM · 🧠 RAM: 351.9 MB

   ⏳ перед flush · 🧠 RAM: 351.9 MB

💾 batch 13135 → 11,232 рядків (всього 1,586,310 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13135.csv.gz

   ✅ після flush · 🧠 RAM: 351.6 MB

[6210/7269] ✓ TEN: 165 рядків |  85.43% | ETA 02:55

[6220/7269] ✓ TENX: 816 рядків |  85.57% | ETA 02:54

[6230/7269] ✓ TGB: 427 рядків |  85.71% | ETA 02:52

[6240/7269] ✓ TH: 368 рядків |  85.84% | ETA 02:50

[6250/7269] ✓ THRM: 179 рядків |  85.98% | ETA 02:49

   • RAM · 🧠 RAM: 352.9 MB

   ⏳ перед flush · 🧠 RAM: 352.9 MB

💾 batch 13136 → 13,004 рядків (всього 1,599,314 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13136.csv.gz

   ✅ після flush · 🧠 RAM: 353.5 MB

[6260/7269] ✓ TIGO: 357 рядків |  86.12% | ETA 02:47

[6270/7269] ✓ TKNO: 137 рядків |  86.26% | ETA 02:45

[6280/7269] ✓ TLIH: 7 рядків |  86.39% | ETA 02:44

[6290/7269] ✓ TLTP: 33 рядків |  86.53% | ETA 02:42

[6300/7269] ✓ TME: 484 рядків |  86.67% | ETA 02:40

   • RAM · 🧠 RAM: 354.6 MB

   ⏳ перед flush · 🧠 RAM: 354.6 MB

💾 batch 13137 → 10,853 рядків (всього 1,610,167 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13137.csv.gz

   ✅ після flush · 🧠 RAM: 355.1 MB

[6310/7269] ✓ TNDM: 403 рядків |  86.81% | ETA 02:39

[6320/7269] ✓ TNON: 172 рядків |  86.94% | ETA 02:37

[6330/7269] ✓ TORO: 53 рядків |  87.08% | ETA 02:35

[6340/7269] ✓ TP: 200 рядків |  87.22% | ETA 02:34

[6350/7269] ✓ TRAK: 58 рядків |  87.36% | ETA 02:32

   • RAM · 🧠 RAM: 353.4 MB

   ⏳ перед flush · 🧠 RAM: 353.4 MB

💾 batch 13138 → 12,396 рядків (всього 1,622,563 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13138.csv.gz

   ✅ після flush · 🧠 RAM: 354.0 MB

[6360/7269] ✓ TRI: 374 рядків |  87.49% | ETA 02:30

[6370/7269] ✓ TRN: 271 рядків |  87.63% | ETA 02:29

[6380/7269] ✓ TRTX: 259 рядків |  87.77% | ETA 02:27

[6390/7269] ✓ TSAT: 228 рядків |  87.91% | ETA 02:25

[6400/7269] ✓ TSL: 249 рядків |  88.05% | ETA 02:24

   • RAM · 🧠 RAM: 351.7 MB

   ⏳ перед flush · 🧠 RAM: 351.7 MB

💾 batch 13139 → 12,871 рядків (всього 1,635,434 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13139.csv.gz

   ✅ після flush · 🧠 RAM: 350.9 MB

[6410/7269] ✓ TSLL: 1,179 рядків |  88.18% | ETA 02:22

[6420/7269] ✓ TSNF: 8 рядків |  88.32% | ETA 02:20

[6430/7269] ✓ TSXU: 84 рядків |  88.46% | ETA 02:19

[6440/7269] ✓ TTDU: 479 рядків |  88.60% | ETA 02:17

[6450/7269] ✓ TTXU: 11 рядків |  88.73% | ETA 02:15

   • RAM · 🧠 RAM: 351.8 MB

   ⏳ перед flush · 🧠 RAM: 351.8 MB

💾 batch 13140 → 18,965 рядків (всього 1,654,399 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13140.csv.gz

   ✅ після flush · 🧠 RAM: 354.2 MB

[6460/7269] ✓ TVGNW: 36 рядків |  88.87% | ETA 02:14

[6470/7269] ✓ TWM: 240 рядків |  89.01% | ETA 02:12

[6480/7269] ✓ TXXD: 22 рядків |  89.15% | ETA 02:10

[6490/7269] – TYG/R: empty |  89.28% | ETA 02:09

[6500/7269] ✓ UA: 387 рядків |  89.42% | ETA 02:07

   • RAM · 🧠 RAM: 344.3 MB

   ⏳ перед flush · 🧠 RAM: 344.3 MB

💾 batch 13141 → 10,583 рядків (всього 1,664,982 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13141.csv.gz

   ✅ після flush · 🧠 RAM: 344.9 MB

[6510/7269] ✓ UBS: 387 рядків |  89.56% | ETA 02:05

[6520/7269] ✓ UECG: 49 рядків |  89.70% | ETA 02:04

[6530/7269] ✓ UFOX: 38 рядків |  89.83% | ETA 02:02

[6540/7269] – UGRO: empty |  89.97% | ETA 02:00

[6550/7269] ✓ ULTA: 370 рядків |  90.11% | ETA 01:59

   • RAM · 🧠 RAM: 344.9 MB

   ⏳ перед flush · 🧠 RAM: 344.9 MB

💾 batch 13142 → 11,624 рядків (всього 1,676,606 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13142.csv.gz

   ✅ після flush · 🧠 RAM: 345.5 MB

[6560/7269] ✓ UMH: 282 рядків |  90.25% | ETA 01:57

[6570/7269] ✓ UNHW: 4 рядків |  90.38% | ETA 01:55

[6580/7269] ✓ UPRO: 737 рядків |  90.52% | ETA 01:54

[6590/7269] ✓ URAN: 8 рядків |  90.66% | ETA 01:52

[6600/7269] ✓ URTH: 271 рядків |  90.80% | ETA 01:50

   • RAM · 🧠 RAM: 346.7 MB

   ⏳ перед flush · 🧠 RAM: 346.7 MB

💾 batch 13143 → 12,494 рядків (всього 1,689,100 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13143.csv.gz

   ✅ після flush · 🧠 RAM: 347.4 MB

[6610/7269] ✓ USAS: 460 рядків |  90.93% | ETA 01:49

[6620/7269] ✓ USEA: 56 рядків |  91.07% | ETA 01:47

[6630/7269] ✓ USMV: 377 рядків |  91.21% | ETA 01:45

[6640/7269] ✓ UTF: 215 рядків |  91.35% | ETA 01:44

[6650/7269] ✓ UTZ: 396 рядків |  91.48% | ETA 01:42

   • RAM · 🧠 RAM: 348.1 MB

   ⏳ перед flush · 🧠 RAM: 348.1 MB

💾 batch 13144 → 11,617 рядків (всього 1,700,717 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13144.csv.gz

   ✅ після flush · 🧠 RAM: 348.6 MB

[6660/7269] ✓ UXRP: 86 рядків |  91.62% | ETA 01:41

[6670/7269] ✓ VAC: 279 рядків |  91.76% | ETA 01:39

[6680/7269] ✓ VBR: 255 рядків |  91.90% | ETA 01:37

[6690/7269] ✓ VCIG: 292 рядків |  92.03% | ETA 01:36

[6700/7269] ✓ VELL: 136 рядків |  92.17% | ETA 01:34

   • RAM · 🧠 RAM: 347.7 MB

   ⏳ перед flush · 🧠 RAM: 347.7 MB

💾 batch 13145 → 13,184 рядків (всього 1,713,901 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13145.csv.gz

   ✅ після flush · 🧠 RAM: 348.4 MB

[6710/7269] ✓ VFC: 400 рядків |  92.31% | ETA 01:32

[6720/7269] ✓ VFF: 483 рядків |  92.45% | ETA 01:31

[6730/7269] ✓ VGLT: 397 рядків |  92.58% | ETA 01:29

[6740/7269] ✓ VIDA: 58 рядків |  92.72% | ETA 01:27

[6750/7269] ✓ VIS: 157 рядків |  92.86% | ETA 01:26

   • RAM · 🧠 RAM: 348.8 MB

   ⏳ перед flush · 🧠 RAM: 348.8 MB

💾 batch 13146 → 14,680 рядків (всього 1,728,581 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13146.csv.gz

   ✅ після flush · 🧠 RAM: 349.4 MB

[6760/7269] ✓ VIXY: 414 рядків |  93.00% | ETA 01:24

[6770/7269] ✓ VMET: 196 рядків |  93.14% | ETA 01:22

[6780/7269] ✓ VNM: 170 рядків |  93.27% | ETA 01:21

[6790/7269] ✓ VOO: 1,049 рядків |  93.41% | ETA 01:19

[6800/7269] ✓ VPG: 374 рядків |  93.55% | ETA 01:17

   • RAM · 🧠 RAM: 349.6 MB

   ⏳ перед flush · 🧠 RAM: 349.6 MB

💾 batch 13147 → 15,572 рядків (всього 1,744,153 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13147.csv.gz

   ✅ після flush · 🧠 RAM: 350.3 MB

[6810/7269] ✓ VOYA: 342 рядків |  93.69% | ETA 01:16

[6820/7269] ✓ VREX: 521 рядків |  93.82% | ETA 01:14

[6830/7269] ✓ VSAT: 386 рядків |  93.96% | ETA 01:12

[6840/7269] ✓ VSS: 173 рядків |  94.10% | ETA 01:11

[6850/7269] ✓ VTI: 578 рядків |  94.24% | ETA 01:09

   • RAM · 🧠 RAM: 351.1 MB

   ⏳ перед flush · 🧠 RAM: 351.1 MB

💾 batch 13148 → 13,907 рядків (всього 1,758,060 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13148.csv.gz

   ✅ після flush · 🧠 RAM: 351.8 MB

[6860/7269] ✓ VTR: 380 рядків |  94.37% | ETA 01:07

[6870/7269] ✓ VWOB: 294 рядків |  94.51% | ETA 01:06

[6880/7269] ✓ VXX: 561 рядків |  94.65% | ETA 01:04

[6890/7269] – WAI: empty |  94.79% | ETA 01:02

[6900/7269] ✓ WAVE: 19 рядків |  94.92% | ETA 01:01

   • RAM · 🧠 RAM: 353.3 MB

   ⏳ перед flush · 🧠 RAM: 353.3 MB

💾 batch 13149 → 14,128 рядків (всього 1,772,188 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13149.csv.gz

   ✅ після flush · 🧠 RAM: 354.0 MB

[6910/7269] ✓ WCT: 25 рядків |  95.06% | ETA 00:59

[6920/7269] ✓ WDH: 65 рядків |  95.20% | ETA 00:57

[6930/7269] ✓ WEEI: 88 рядків |  95.34% | ETA 00:56

[6940/7269] ✓ WEYS: 59 рядків |  95.47% | ETA 00:54

[6950/7269] ✓ WHF: 107 рядків |  95.61% | ETA 00:52

   • RAM · 🧠 RAM: 355.3 MB

   ⏳ перед flush · 🧠 RAM: 355.3 MB

💾 batch 13150 → 12,434 рядків (всього 1,784,622 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13150.csv.gz

   ✅ після flush · 🧠 RAM: 356.9 MB

[6960/7269] ✓ WHWK: 273 рядків |  95.75% | ETA 00:51

[6970/7269] ✓ WLDS: 377 рядків |  95.89% | ETA 00:49

[6980/7269] ✓ WMS: 301 рядків |  96.02% | ETA 00:47

[6990/7269] ✓ WOR: 85 рядків |  96.16% | ETA 00:46

[7000/7269] ✓ WS: 99 рядків |  96.30% | ETA 00:44

   • RAM · 🧠 RAM: 353.2 MB

   ⏳ перед flush · 🧠 RAM: 353.2 MB

💾 batch 13151 → 12,790 рядків (всього 1,797,412 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13151.csv.gz

   ✅ після flush · 🧠 RAM: 353.8 MB

[7010/7269] – WSR: empty |  96.44% | ETA 00:42

[7020/7269] ✓ WTID: 177 рядків |  96.57% | ETA 00:41

[7030/7269] – WTO: empty |  96.71% | ETA 00:39

[7040/7269] ✓ WY: 398 рядків |  96.85% | ETA 00:37

[7050/7269] ✓ XAR: 330 рядків |  96.99% | ETA 00:36

   • RAM · 🧠 RAM: 349.0 MB

   ⏳ перед flush · 🧠 RAM: 349.0 MB

💾 batch 13152 → 13,596 рядків (всього 1,811,008 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13152.csv.gz

   ✅ після flush · 🧠 RAM: 349.7 MB

[7060/7269] ✓ XCUR: 48 рядків |  97.12% | ETA 00:34

[7070/7269] ✓ XGN: 197 рядків |  97.26% | ETA 00:33

[7080/7269] ✓ XLF: 502 рядків |  97.40% | ETA 00:31

[7090/7269] ✓ XLU: 480 рядків |  97.54% | ETA 00:29

[7100/7269] ✓ XNCR: 358 рядків |  97.68% | ETA 00:28

   • RAM · 🧠 RAM: 352.4 MB

   ⏳ перед flush · 🧠 RAM: 352.4 MB

💾 batch 13153 → 37,054 рядків (всього 1,848,062 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13153.csv.gz

   ✅ після flush · 🧠 RAM: 353.9 MB

[7110/7269] ✓ XOP: 507 рядків |  97.81% | ETA 00:26

[7120/7269] ✓ XPEL: 175 рядків |  97.95% | ETA 00:24

[7130/7269] ✓ XRP: 301 рядків |  98.09% | ETA 00:23

[7140/7269] ✓ XRTX: 6 рядків |  98.23% | ETA 00:21

[7150/7269] ✓ XSD: 162 рядків |  98.36% | ETA 00:19

   • RAM · 🧠 RAM: 347.4 MB

   ⏳ перед flush · 🧠 RAM: 347.4 MB

💾 batch 13154 → 9,297 рядків (всього 1,857,359 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13154.csv.gz

   ✅ після flush · 🧠 RAM: 347.7 MB

[7160/7269] ✓ XXRP: 193 рядків |  98.50% | ETA 00:18

[7170/7269] ✓ XZO: 125 рядків |  98.64% | ETA 00:16

[7180/7269] ✓ YCL: 46 рядків |  98.78% | ETA 00:14

[7190/7269] ✓ YETH: 84 рядків |  98.91% | ETA 00:13

[7200/7269] ✓ YMAX: 362 рядків |  99.05% | ETA 00:11

   • RAM · 🧠 RAM: 348.3 MB

   ⏳ перед flush · 🧠 RAM: 348.3 MB

💾 batch 13155 → 7,983 рядків (всього 1,865,342 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13155.csv.gz

   ✅ після flush · 🧠 RAM: 348.7 MB

[7210/7269] ✓ YSPY: 20 рядків |  99.19% | ETA 00:09

[7220/7269] ✓ YYAI: 1,430 рядків |  99.33% | ETA 00:08

[7230/7269] ✓ ZDGE: 42 рядків |  99.46% | ETA 00:06

[7240/7269] ✓ ZG: 376 рядків |  99.60% | ETA 00:04

[7250/7269] ✓ ZNB: 262 рядків |  99.74% | ETA 00:03

   • RAM · 🧠 RAM: 350.3 MB

   ⏳ перед flush · 🧠 RAM: 350.3 MB

💾 batch 13156 → 15,423 рядків (всього 1,880,765 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13156.csv.gz

   ✅ після flush · 🧠 RAM: 351.0 MB

[7260/7269] ✓ ZTG: 266 рядків |  99.88% | ETA 00:01

[7269/7269] ✓ ZYBT: 461 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 353.3 MB

💾 batch 13157 → 5,419 рядків (всього 1,886,184 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_13157.csv.gz

   ✅ після flush · 🧠 RAM: 353.9 MB

   🔚 фінал · 🧠 RAM: 353.9 MB

🏁 Готово. Нових рядків: 1,886,184 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 20:06

In [18]:
# ================== FAST LOCAL POST-PROCESSING (no API calls) ==================
# Читання батчів робить pyarrow (нативний багатопотоковий CSV-парсер) замість
# pandas.read_csv, а premarket-фільтр і денні open/close рахуються за ОДИН прохід
# по gz-файлах замість двох.
import os, gc, glob, time, threading
from typing import Optional, List, Tuple

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.csv as pacsv
import pyarrow.compute as pc
import pyarrow.dataset as pads
from concurrent.futures import ThreadPoolExecutor

_INTRADAY_COLS = ["ticker", "dt", "o", "h", "l", "c", "v"]

# Парсимо у float64, щоб денні open/close збігалися з попередньою (pandas) реалізацією
# біт у біт; premarket-рядки перед записом кастимо назад у float32 — стара схема на диску.
_INTRADAY_TYPES = {
    "ticker": pa.string(), "dt": pa.string(),
    "o": pa.float64(), "h": pa.float64(), "l": pa.float64(),
    "c": pa.float64(), "v": pa.float64(),
}
_PREMARKET_SCHEMA = pa.schema([
    ("ticker", pa.string()), ("dt", pa.string()),
    ("o", pa.float32()), ("h", pa.float32()), ("l", pa.float32()),
    ("c", pa.float32()), ("v", pa.float32()),
])


# ---------- спільні хелпери для мерджів по тікеру (використовують клітинки 28/40/44) ----------
def _ticker_codes(s: pd.Series):
    """Факторизує колонку тікерів і нормалізує (strip+upper) ЛИШЕ унікальні значення.

    Повертає (codes, categories); codes[i] == -1 означає null. Сенс у тому, щоб
    strip/upper і словниковий пошук виконувались над ~10^3 унікальними тікерами,
    а не над ~10^6 рядками батча.
    """
    cat = s.astype("category")
    cats = pd.Index(cat.cat.categories.astype(str)).str.strip().str.upper()
    return cat.cat.codes.to_numpy(), cats


def _expand(values: np.ndarray, codes: np.ndarray, fill):
    """Розгортає масив «на категорію» назад «на рядок»; де codes == -1 ставить fill."""
    out = np.empty(codes.shape, dtype=values.dtype if values.dtype != object else object)
    valid = codes >= 0
    out[valid] = values[codes[valid]]
    if (~valid).any():
        out[~valid] = fill
    return out


def _map_by_ticker(codes: np.ndarray, cats: pd.Index, mapping: dict, numeric: bool):
    vals = cats.map(mapping)
    if numeric:
        vals = pd.to_numeric(pd.Series(vals), errors="coerce").to_numpy(dtype="float64")
        return _expand(vals, codes, np.nan)
    vals = np.asarray(pd.Series(vals).astype(object).to_numpy(), dtype=object)
    return _expand(vals, codes, None)


# ---------- читання intraday-батчів ----------
def _open_intraday_csv(path: str, block_size: int):
    return pacsv.open_csv(
        path,
        read_options=pacsv.ReadOptions(use_threads=True, block_size=block_size),
        convert_options=pacsv.ConvertOptions(
            include_columns=_INTRADAY_COLS, column_types=_INTRADAY_TYPES
        ),
    )


def _time_date_mask(dt_arr, start_time, end_time, date_min, date_max):
    t = pc.utf8_slice_codeunits(dt_arr, 11, 19)
    mask = pc.and_(pc.greater_equal(t, start_time), pc.less_equal(t, end_time))
    if date_min is not None or date_max is not None:
        d = pc.utf8_slice_codeunits(dt_arr, 0, 10)
        if date_min is not None:
            mask = pc.and_(mask, pc.greater_equal(d, date_min))
        if date_max is not None:
            mask = pc.and_(mask, pc.less_equal(d, date_max))
    return mask


def _oc_from_table(tbl: pa.Table) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Перший open у вікні 09:30–09:35 і останній close у 15:55–15:59 на (ticker, date)."""
    OPEN_FROM, OPEN_TO = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    hhmm = pc.utf8_slice_codeunits(tbl.column("dt"), 11, 16)
    m_o = pc.and_(pc.and_(pc.greater_equal(hhmm, OPEN_FROM), pc.less_equal(hhmm, OPEN_TO)),
                  pc.is_valid(tbl.column("o")))
    m_c = pc.and_(pc.and_(pc.greater_equal(hhmm, CLOSE_FROM), pc.less_equal(hhmm, CLOSE_TO)),
                  pc.is_valid(tbl.column("c")))

    def _reduce(mask, val_col, keep):
        sub = tbl.select(["ticker", "dt", val_col]).filter(mask)
        if sub.num_rows == 0:
            return pd.DataFrame(columns=["ticker", "date", "dt", val_col])
        d = sub.to_pandas()
        d["date"] = d["dt"].str.slice(0, 10)
        d = d.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep=keep)
        return d[["ticker", "date", "dt", val_col]]

    return _reduce(m_o, "o", "first"), _reduce(m_c, "c", "last")


def _finalize_oc(open_parts: List[pd.DataFrame], close_parts: List[pd.DataFrame]) -> pd.DataFrame:
    opens = (pd.concat(open_parts, ignore_index=True) if open_parts
             else pd.DataFrame(columns=["ticker", "date", "dt", "o"]))
    closes = (pd.concat(close_parts, ignore_index=True) if close_parts
              else pd.DataFrame(columns=["ticker", "date", "dt", "c"]))
    if len(opens):
        opens = opens.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="first")
    if len(closes):
        closes = closes.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="last")
    opens = opens[["ticker", "date", "o"]].rename(columns={"o": "open"})
    closes = closes[["ticker", "date", "c"]].rename(columns={"c": "close"})

    out = (opens.merge(closes, on=["ticker", "date"], how="outer")
                .sort_values(["ticker", "date"], kind="stable").reset_index(drop=True))
    out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)
    return out


def collect_premarket_and_oc(
    folder: str,
    out_path: str,
    oc_out_path: Optional[str] = None,
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    build_oc: bool = True,
    max_workers: int = 4,
    block_size: int = 64 << 20,
    compression: str = "snappy",
    sort_chunk: bool = True,
    verbose: bool = True,
):
    """ОДИН прохід по {folder}/{pattern}: пише відфільтровані рядки у out_path і
    (опційно) денні open/close у oc_out_path.

    Замінює пару collect_premarket_by_day_stream + build_oc_from_intraday_folder,
    які раніше читали й розтискали ті самі gz-файли двічі.

    Порядок рядків МІЖ файлами недетермінований (файли читаються паралельно).
    Це безпечно: усі наступні кроки — мерджі по ключах, а фінальний файл
    фізично сортується у клітинці 47. Для точного старого порядку — max_workers=1.
    """
    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    if os.path.exists(out_path):
        os.remove(out_path)

    t0 = time.time()
    lock = threading.Lock()
    state = {"writer": None, "in": 0, "out": 0, "files": 0}
    open_parts: List[pd.DataFrame] = []
    close_parts: List[pd.DataFrame] = []

    def _handle(path: str):
        reader = _open_intraday_csv(path, block_size)
        loc_open, loc_close = [], []
        n_in = n_out = 0
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            tbl = pa.Table.from_batches([rb])
            n_in += tbl.num_rows

            if build_oc:
                o_df, c_df = _oc_from_table(tbl)
                if len(o_df):
                    loc_open.append(o_df)
                if len(c_df):
                    loc_close.append(c_df)

            cut = tbl.filter(_time_date_mask(tbl.column("dt"), start_time, end_time,
                                             date_min, date_max))
            if cut.num_rows:
                cut = cut.cast(_PREMARKET_SCHEMA)
                if sort_chunk:
                    cut = cut.sort_by([("ticker", "ascending"), ("dt", "ascending")])
                n_out += cut.num_rows
                with lock:
                    if state["writer"] is None:
                        state["writer"] = pq.ParquetWriter(out_path, cut.schema,
                                                           compression=compression)
                    state["writer"].write_table(cut)

        with lock:
            state["in"] += n_in
            state["out"] += n_out
            state["files"] += 1
            open_parts.extend(loc_open)
            close_parts.extend(loc_close)
            if verbose:
                print(f"  [{state['files']}/{len(files)}] {os.path.basename(path)}  "
                      f"in={state['in']:,} out={state['out']:,} "
                      f"elapsed={time.time()-t0:,.1f}s", flush=True)

    rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]" if (date_min or date_max) else ""
    if verbose:
        print(f"▶️ START: {folder}/{pattern} → {out_path}  files={len(files)} "
              f"workers={max_workers}{rng_str}", flush=True)
    try:
        if max_workers and max_workers > 1:
            with ThreadPoolExecutor(max_workers=max_workers) as ex:
                list(ex.map(_handle, files))
        else:
            for p in files:
                _handle(p)
    finally:
        if state["writer"] is not None:
            state["writer"].close()

    df_oc = None
    if build_oc:
        df_oc = _finalize_oc(open_parts, close_parts)
        if oc_out_path:
            os.makedirs(os.path.dirname(oc_out_path) or ".", exist_ok=True)
            df_oc.to_parquet(oc_out_path, index=False)

    if verbose:
        print(f"✅ DONE  in={state['in']:,} → out={state['out']:,}  to {out_path}  "
              f"in {time.time()-t0:,.1f}s", flush=True)
    return out_path, df_oc


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,
    date_max: Optional[str] = None,
    aggregate: bool = False,
    chunksize: int = 200_000,          # лишено для сумісності виклику; pyarrow керує блоками сам
    compression: str = "snappy",
    log_every: int = 5,                # лишено для сумісності виклику
    sort_chunk: bool = True,
    max_workers: int = 4,
    verbose: bool = True,
):
    """Тонка обгортка над collect_premarket_and_oc (build_oc=False) — щоб старі
    виклики працювали без змін."""
    if aggregate:
        raise NotImplementedError("aggregate=True у цьому пайплайні не використовується")
    path, _ = collect_premarket_and_oc(
        folder, out_path, oc_out_path=None, pattern=pattern,
        start_time=start_time, end_time=end_time,
        date_min=date_min, date_max=date_max, build_oc=False,
        max_workers=max_workers, compression=compression,
        sort_chunk=sort_chunk, verbose=verbose,
    )
    return path

In [19]:
# Один прохід по gz-батчах: одразу і premarket-рядки, і денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,
    date_max=end_date_str,
    build_oc=True,
    max_workers=4,
)
print(df_oc.head())

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  files=13157 workers=4  date=[2026-05-10..2026-08-10]

  [1/13157] intraday_0004.csv.gz  in=743,028 out=0 elapsed=2.9s

  [2/13157] intraday_0003.csv.gz  in=1,470,913 out=0 elapsed=2.9s

  [3/13157] intraday_0002.csv.gz  in=2,357,625 out=0 elapsed=2.9s

  [4/13157] intraday_0001.csv.gz  in=3,333,452 out=0 elapsed=2.9s

  [5/13157] intraday_0007.csv.gz  in=4,094,033 out=0 elapsed=5.3s

  [6/13157] intraday_0008.csv.gz  in=4,903,597 out=0 elapsed=5.5s

  [7/13157] intraday_0005.csv.gz  in=5,777,588 out=0 elapsed=5.6s

  [8/13157] intraday_0006.csv.gz  in=6,732,671 out=0 elapsed=5.6s

  [9/13157] intraday_0009.csv.gz  in=7,672,497 out=0 elapsed=7.7s

  [10/13157] intraday_0011.csv.gz  in=8,411,136 out=0 elapsed=8.0s

  [11/13157] intraday_0010.csv.gz  in=9,348,724 out=0 elapsed=8.3s

  [12/13157] intraday_0012.csv.gz  in=10,202,410 out=0 elapsed=8.3s

  [13/13157] intraday_0014.csv.gz  in=10,867,729 out=0 elapsed=8.9s

  [14/13157] intraday_0015.csv.gz  in=11,471,803 out=0 elapsed=9.1s

  [15/13157] intraday_0013.csv.gz  in=12,333,647 out=0 elapsed=9.1s

  [16/13157] intraday_0016.csv.gz  in=13,369,434 out=0 elapsed=9.9s

  [17/13157] intraday_0018.csv.gz  in=14,058,532 out=0 elapsed=10.4s

  [18/13157] intraday_0019.csv.gz  in=14,795,001 out=0 elapsed=10.5s

  [19/13157] intraday_0017.csv.gz  in=15,723,943 out=0 elapsed=10.7s

  [20/13157] intraday_0020.csv.gz  in=16,555,781 out=0 elapsed=11.4s

  [21/13157] intraday_0022.csv.gz  in=17,287,747 out=0 elapsed=11.7s

  [22/13157] intraday_0021.csv.gz  in=18,114,555 out=0 elapsed=11.7s

  [23/13157] intraday_0023.csv.gz  in=18,895,557 out=0 elapsed=12.6s

  [24/13157] intraday_0024.csv.gz  in=19,686,597 out=0 elapsed=14.2s

  [25/13157] intraday_0025.csv.gz  in=20,416,242 out=0 elapsed=14.4s

  [26/13157] intraday_0027.csv.gz  in=21,080,210 out=0 elapsed=14.5s

  [27/13157] intraday_0026.csv.gz  in=21,935,669 out=0 elapsed=14.6s

  [28/13157] intraday_0031.csv.gz  in=22,669,679 out=0 elapsed=17.0s

  [29/13157] intraday_0030.csv.gz  in=23,589,509 out=0 elapsed=17.3s

  [30/13157] intraday_0029.csv.gz  in=24,536,026 out=0 elapsed=17.4s

  [31/13157] intraday_0028.csv.gz  in=25,543,444 out=0 elapsed=17.4s

  [32/13157] intraday_0032.csv.gz  in=26,359,346 out=0 elapsed=19.9s

  [33/13157] intraday_0034.csv.gz  in=27,046,628 out=0 elapsed=19.9s

  [34/13157] intraday_0035.csv.gz  in=27,865,784 out=0 elapsed=20.0s

  [35/13157] intraday_0033.csv.gz  in=28,741,745 out=0 elapsed=20.2s

  [36/13157] intraday_0037.csv.gz  in=29,414,856 out=0 elapsed=21.8s

  [37/13157] intraday_0038.csv.gz  in=30,104,913 out=0 elapsed=21.8s

  [38/13157] intraday_0036.csv.gz  in=30,924,778 out=0 elapsed=22.0s

  [39/13157] intraday_0039.csv.gz  in=31,684,289 out=0 elapsed=22.0s

  [40/13157] intraday_0040.csv.gz  in=32,407,718 out=0 elapsed=23.2s

  [41/13157] intraday_0041.csv.gz  in=33,301,794 out=0 elapsed=23.5s

  [42/13157] intraday_0043.csv.gz  in=34,013,644 out=0 elapsed=23.7s

  [43/13157] intraday_0042.csv.gz  in=34,960,739 out=0 elapsed=24.1s

  [44/13157] intraday_0044.csv.gz  in=35,766,274 out=0 elapsed=26.1s

  [45/13157] intraday_0045.csv.gz  in=36,568,713 out=0 elapsed=26.1s

  [46/13157] intraday_0046.csv.gz  in=37,383,804 out=0 elapsed=26.3s

  [47/13157] intraday_0047.csv.gz  in=38,250,311 out=0 elapsed=27.2s

  [48/13157] intraday_0048.csv.gz  in=38,906,436 out=0 elapsed=28.0s

  [49/13157] intraday_0050.csv.gz  in=39,739,068 out=0 elapsed=28.5s

  [50/13157] intraday_0051.csv.gz  in=40,468,859 out=0 elapsed=28.5s

  [51/13157] intraday_0049.csv.gz  in=41,414,383 out=0 elapsed=28.6s

  [52/13157] intraday_0052.csv.gz  in=42,279,351 out=0 elapsed=29.3s

  [53/13157] intraday_0053.csv.gz  in=42,998,896 out=0 elapsed=29.6s

  [54/13157] intraday_0054.csv.gz  in=43,729,514 out=0 elapsed=29.7s

  [55/13157] intraday_0055.csv.gz  in=44,542,383 out=0 elapsed=29.9s

  [56/13157] intraday_0056.csv.gz  in=45,360,329 out=0 elapsed=31.1s

  [57/13157] intraday_0057.csv.gz  in=46,118,655 out=0 elapsed=32.4s

  [58/13157] intraday_0058.csv.gz  in=46,830,377 out=0 elapsed=32.6s

  [59/13157] intraday_0059.csv.gz  in=47,587,522 out=0 elapsed=32.6s

  [60/13157] intraday_0060.csv.gz  in=48,264,439 out=0 elapsed=33.9s

  [61/13157] intraday_0062.csv.gz  in=49,011,023 out=0 elapsed=36.1s

  [62/13157] intraday_0061.csv.gz  in=50,022,323 out=0 elapsed=36.4s

  [63/13157] intraday_0063.csv.gz  in=50,975,856 out=0 elapsed=36.5s

  [64/13157] intraday_0064.csv.gz  in=51,861,073 out=0 elapsed=36.7s

  [65/13157] intraday_0065.csv.gz  in=52,657,022 out=0 elapsed=38.0s

  [66/13157] intraday_0066.csv.gz  in=53,344,110 out=0 elapsed=38.1s

  [67/13157] intraday_0067.csv.gz  in=54,114,222 out=0 elapsed=38.2s

  [68/13157] intraday_0068.csv.gz  in=54,938,820 out=0 elapsed=38.4s

  [69/13157] intraday_0070.csv.gz  in=55,597,571 out=0 elapsed=39.5s

  [70/13157] intraday_0071.csv.gz  in=56,235,581 out=0 elapsed=39.6s

  [71/13157] intraday_0069.csv.gz  in=57,135,058 out=0 elapsed=39.7s

  [72/13157] intraday_0072.csv.gz  in=57,879,667 out=0 elapsed=39.8s

  [73/13157] intraday_0073.csv.gz  in=58,674,810 out=0 elapsed=41.6s

  [74/13157] intraday_0074.csv.gz  in=59,409,405 out=0 elapsed=41.7s

  [75/13157] intraday_0075.csv.gz  in=60,167,330 out=0 elapsed=41.8s

  [76/13157] intraday_0076.csv.gz  in=60,866,670 out=0 elapsed=41.8s

  [77/13157] intraday_0077.csv.gz  in=61,676,095 out=0 elapsed=43.0s

  [78/13157] intraday_0080.csv.gz  in=62,376,615 out=0 elapsed=43.3s

  [79/13157] intraday_0078.csv.gz  in=63,437,209 out=0 elapsed=43.5s

  [80/13157] intraday_0079.csv.gz  in=64,355,814 out=0 elapsed=43.5s

  [81/13157] intraday_0081.csv.gz  in=65,173,353 out=0 elapsed=45.0s

  [82/13157] intraday_0082.csv.gz  in=65,962,271 out=0 elapsed=46.9s

  [83/13157] intraday_0083.csv.gz  in=66,748,390 out=0 elapsed=46.9s

  [84/13157] intraday_0085.csv.gz  in=67,522,552 out=0 elapsed=47.0s

  [85/13157] intraday_0084.csv.gz  in=68,693,048 out=0 elapsed=47.3s

  [86/13157] intraday_0086.csv.gz  in=69,620,846 out=0 elapsed=49.8s

  [87/13157] intraday_0088.csv.gz  in=70,453,902 out=0 elapsed=49.8s

  [88/13157] intraday_0087.csv.gz  in=71,397,243 out=0 elapsed=49.9s

  [89/13157] intraday_0089.csv.gz  in=72,281,904 out=0 elapsed=49.9s

  [90/13157] intraday_0090.csv.gz  in=73,069,473 out=0 elapsed=51.9s

  [91/13157] intraday_0093.csv.gz  in=73,885,132 out=0 elapsed=52.0s

  [92/13157] intraday_0092.csv.gz  in=74,717,770 out=0 elapsed=52.0s

  [93/13157] intraday_0091.csv.gz  in=75,647,498 out=0 elapsed=52.0s

  [94/13157] intraday_0097.csv.gz  in=76,419,878 out=0 elapsed=53.5s

  [95/13157] intraday_0094.csv.gz  in=77,301,118 out=0 elapsed=53.6s

  [96/13157] intraday_0095.csv.gz  in=78,151,154 out=0 elapsed=53.6s

  [97/13157] intraday_0096.csv.gz  in=79,032,923 out=0 elapsed=53.6s

  [98/13157] intraday_0098.csv.gz  in=79,802,827 out=0 elapsed=55.0s

  [99/13157] intraday_0100.csv.gz  in=80,600,542 out=0 elapsed=55.2s

  [100/13157] intraday_0101.csv.gz  in=81,532,270 out=0 elapsed=55.4s

  [101/13157] intraday_0099.csv.gz  in=82,593,388 out=0 elapsed=55.5s

  [102/13157] intraday_0102.csv.gz  in=83,527,121 out=0 elapsed=56.7s

  [103/13157] intraday_0103.csv.gz  in=84,317,945 out=0 elapsed=57.1s

  [104/13157] intraday_0104.csv.gz  in=85,159,844 out=0 elapsed=57.4s

  [105/13157] intraday_0105.csv.gz  in=86,032,104 out=0 elapsed=58.1s

  [106/13157] intraday_0106.csv.gz  in=86,821,848 out=0 elapsed=58.2s

  [107/13157] intraday_0108.csv.gz  in=87,616,449 out=0 elapsed=58.8s

  [108/13157] intraday_0107.csv.gz  in=88,679,847 out=0 elapsed=59.4s

  [109/13157] intraday_0111.csv.gz  in=89,466,879 out=0 elapsed=60.8s

  [110/13157] intraday_0109.csv.gz  in=90,406,263 out=0 elapsed=61.0s

  [111/13157] intraday_0110.csv.gz  in=91,427,941 out=0 elapsed=61.1s

  [112/13157] intraday_0112.csv.gz  in=92,259,949 out=0 elapsed=61.3s

  [113/13157] intraday_0113.csv.gz  in=93,022,660 out=0 elapsed=62.4s

  [114/13157] intraday_0114.csv.gz  in=93,859,984 out=0 elapsed=62.7s

  [115/13157] intraday_0115.csv.gz  in=94,616,153 out=0 elapsed=62.8s

  [116/13157] intraday_0116.csv.gz  in=95,564,921 out=0 elapsed=64.2s

  [117/13157] intraday_0117.csv.gz  in=96,350,237 out=0 elapsed=64.7s

  [118/13157] intraday_0119.csv.gz  in=97,075,034 out=0 elapsed=64.7s

  [119/13157] intraday_0118.csv.gz  in=98,245,742 out=0 elapsed=65.1s

  [120/13157] intraday_0120.csv.gz  in=99,105,343 out=0 elapsed=65.2s

  [121/13157] intraday_0122.csv.gz  in=99,893,843 out=0 elapsed=65.4s

  [122/13157] intraday_0121.csv.gz  in=100,938,876 out=0 elapsed=65.6s

  [123/13157] intraday_0123.csv.gz  in=101,790,604 out=0 elapsed=66.4s

  [124/13157] intraday_0124.csv.gz  in=102,767,055 out=0 elapsed=66.8s

  [125/13157] intraday_0125.csv.gz  in=103,648,833 out=0 elapsed=66.9s

  [126/13157] intraday_0126.csv.gz  in=104,596,744 out=0 elapsed=66.9s

  [127/13157] intraday_0127.csv.gz  in=105,314,012 out=0 elapsed=67.1s

  [128/13157] intraday_0128.csv.gz  in=106,066,285 out=0 elapsed=68.2s

  [129/13157] intraday_0129.csv.gz  in=106,926,182 out=0 elapsed=68.7s

  [130/13157] intraday_0131.csv.gz  in=107,680,974 out=0 elapsed=68.7s

  [131/13157] intraday_0130.csv.gz  in=108,503,257 out=0 elapsed=68.7s

  [132/13157] intraday_0135.csv.gz  in=108,519,615 out=0 elapsed=68.9s

  [133/13157] intraday_0132.csv.gz  in=109,181,891 out=0 elapsed=68.9s

  [134/13157] intraday_0134.csv.gz  in=109,230,042 out=0 elapsed=68.9s

  [135/13157] intraday_0136.csv.gz  in=109,248,732 out=0 elapsed=68.9s

  [136/13157] intraday_0137.csv.gz  in=109,260,783 out=0 elapsed=69.0s

  [137/13157] intraday_0138.csv.gz  in=109,273,313 out=0 elapsed=69.0s

  [138/13157] intraday_0139.csv.gz  in=109,286,997 out=0 elapsed=69.0s

  [139/13157] intraday_0141.csv.gz  in=109,299,583 out=0 elapsed=69.1s

  [140/13157] intraday_0140.csv.gz  in=109,314,490 out=0 elapsed=69.1s

  [141/13157] intraday_0142.csv.gz  in=109,328,468 out=0 elapsed=69.1s

  [142/13157] intraday_0143.csv.gz  in=109,343,799 out=0 elapsed=69.2s

  [143/13157] intraday_0145.csv.gz  in=109,359,005 out=0 elapsed=69.2s

  [144/13157] intraday_0144.csv.gz  in=109,391,725 out=0 elapsed=69.2s

  [145/13157] intraday_0148.csv.gz  in=109,403,025 out=0 elapsed=69.2s

  [146/13157] intraday_0147.csv.gz  in=109,417,998 out=0 elapsed=69.2s

  [147/13157] intraday_0146.csv.gz  in=109,449,779 out=0 elapsed=69.2s

  [148/13157] intraday_0149.csv.gz  in=109,461,076 out=0 elapsed=69.3s

  [149/13157] intraday_0150.csv.gz  in=109,477,550 out=0 elapsed=69.3s

  [150/13157] intraday_0151.csv.gz  in=109,493,543 out=0 elapsed=69.3s

  [151/13157] intraday_0152.csv.gz  in=109,505,698 out=0 elapsed=69.5s

  [152/13157] intraday_0153.csv.gz  in=109,517,425 out=0 elapsed=69.5s

  [153/13157] intraday_0154.csv.gz  in=109,532,249 out=0 elapsed=69.5s

  [154/13157] intraday_0156.csv.gz  in=109,545,610 out=0 elapsed=69.6s

  [155/13157] intraday_0155.csv.gz  in=109,561,190 out=0 elapsed=69.6s

  [156/13157] intraday_0157.csv.gz  in=109,573,389 out=0 elapsed=69.6s

  [157/13157] intraday_0159.csv.gz  in=109,585,001 out=0 elapsed=69.8s

  [158/13157] intraday_0160.csv.gz  in=109,597,440 out=0 elapsed=69.8s

  [159/13157] intraday_0158.csv.gz  in=109,627,373 out=0 elapsed=69.8s

  [160/13157] intraday_0161.csv.gz  in=109,639,687 out=0 elapsed=69.8s

  [161/13157] intraday_0162.csv.gz  in=109,656,973 out=0 elapsed=70.0s

  [162/13157] intraday_0164.csv.gz  in=109,672,164 out=0 elapsed=70.0s

  [163/13157] intraday_0163.csv.gz  in=109,689,370 out=0 elapsed=70.0s

  [164/13157] intraday_0165.csv.gz  in=109,701,993 out=0 elapsed=70.0s

  [165/13157] intraday_0166.csv.gz  in=109,715,603 out=0 elapsed=70.1s

  [166/13157] intraday_0168.csv.gz  in=109,726,460 out=0 elapsed=70.1s

  [167/13157] intraday_0167.csv.gz  in=109,747,301 out=0 elapsed=70.1s

  [168/13157] intraday_0170.csv.gz  in=109,762,841 out=0 elapsed=70.3s

  [169/13157] intraday_0169.csv.gz  in=109,777,172 out=0 elapsed=70.3s

  [170/13157] intraday_0172.csv.gz  in=109,787,906 out=0 elapsed=70.3s

  [171/13157] intraday_0171.csv.gz  in=109,799,327 out=0 elapsed=70.3s

  [172/13157] intraday_0173.csv.gz  in=109,812,165 out=0 elapsed=70.3s

  [173/13157] intraday_0175.csv.gz  in=109,826,539 out=0 elapsed=70.3s

  [174/13157] intraday_0174.csv.gz  in=109,839,343 out=0 elapsed=70.3s

  [175/13157] intraday_0177.csv.gz  in=109,854,294 out=0 elapsed=70.4s

  [176/13157] intraday_0176.csv.gz  in=109,871,176 out=0 elapsed=70.4s

  [177/13157] intraday_0178.csv.gz  in=109,885,119 out=0 elapsed=70.4s

  [178/13157] intraday_0179.csv.gz  in=109,898,823 out=0 elapsed=70.4s

  [179/13157] intraday_0180.csv.gz  in=109,912,556 out=0 elapsed=70.4s

  [180/13157] intraday_0182.csv.gz  in=109,925,048 out=0 elapsed=70.5s

  [181/13157] intraday_0181.csv.gz  in=109,955,862 out=0 elapsed=70.5s

  [182/13157] intraday_0183.csv.gz  in=109,973,406 out=0 elapsed=70.5s

  [183/13157] intraday_0184.csv.gz  in=109,989,635 out=0 elapsed=70.5s

  [184/13157] intraday_0133.csv.gz  in=110,770,536 out=0 elapsed=70.5s

  [185/13157] intraday_0185.csv.gz  in=110,784,589 out=0 elapsed=70.5s

  [186/13157] intraday_0186.csv.gz  in=110,799,047 out=0 elapsed=70.5s

  [187/13157] intraday_0187.csv.gz  in=110,812,773 out=0 elapsed=70.5s

  [188/13157] intraday_0190.csv.gz  in=110,826,481 out=0 elapsed=70.6s

  [189/13157] intraday_0189.csv.gz  in=110,839,626 out=0 elapsed=70.6s

  [190/13157] intraday_0191.csv.gz  in=110,854,091 out=0 elapsed=70.6s

  [191/13157] intraday_0188.csv.gz  in=110,877,560 out=0 elapsed=70.6s

  [192/13157] intraday_0193.csv.gz  in=110,889,471 out=0 elapsed=70.6s

  [193/13157] intraday_0194.csv.gz  in=110,899,606 out=0 elapsed=70.6s

  [194/13157] intraday_0192.csv.gz  in=110,911,659 out=0 elapsed=70.6s

  [195/13157] intraday_0195.csv.gz  in=110,926,310 out=0 elapsed=70.6s

  [196/13157] intraday_0196.csv.gz  in=110,938,931 out=0 elapsed=70.7s

  [197/13157] intraday_0199.csv.gz  in=110,953,711 out=0 elapsed=70.7s

  [198/13157] intraday_0198.csv.gz  in=110,969,133 out=0 elapsed=70.7s

  [199/13157] intraday_0197.csv.gz  in=110,983,625 out=0 elapsed=70.7s

  [200/13157] intraday_0200.csv.gz  in=110,995,048 out=0 elapsed=70.7s

  [201/13157] intraday_0202.csv.gz  in=111,009,575 out=0 elapsed=70.7s

  [202/13157] intraday_0201.csv.gz  in=111,023,231 out=0 elapsed=70.7s

  [203/13157] intraday_0203.csv.gz  in=111,036,171 out=0 elapsed=70.7s

  [204/13157] intraday_0205.csv.gz  in=111,046,722 out=0 elapsed=70.7s

  [205/13157] intraday_0206.csv.gz  in=111,059,962 out=0 elapsed=70.8s

  [206/13157] intraday_0204.csv.gz  in=111,071,031 out=0 elapsed=70.8s

  [207/13157] intraday_0207.csv.gz  in=111,084,627 out=0 elapsed=70.8s

  [208/13157] intraday_0208.csv.gz  in=111,096,777 out=0 elapsed=70.8s

  [209/13157] intraday_0209.csv.gz  in=111,109,213 out=0 elapsed=70.8s

  [210/13157] intraday_0210.csv.gz  in=111,120,563 out=0 elapsed=70.8s

  [211/13157] intraday_0213.csv.gz  in=111,135,033 out=0 elapsed=70.8s

  [212/13157] intraday_0212.csv.gz  in=111,155,090 out=0 elapsed=70.8s

  [213/13157] intraday_0211.csv.gz  in=111,170,551 out=0 elapsed=70.8s

  [214/13157] intraday_0214.csv.gz  in=111,183,384 out=0 elapsed=70.8s

  [215/13157] intraday_0217.csv.gz  in=111,196,909 out=0 elapsed=70.9s

  [216/13157] intraday_0216.csv.gz  in=111,211,177 out=0 elapsed=71.0s

  [217/13157] intraday_0215.csv.gz  in=111,225,093 out=0 elapsed=71.0s

  [218/13157] intraday_0218.csv.gz  in=111,244,102 out=0 elapsed=71.0s

  [219/13157] intraday_0220.csv.gz  in=111,259,305 out=0 elapsed=71.1s

  [220/13157] intraday_0219.csv.gz  in=111,271,333 out=0 elapsed=71.1s

  [221/13157] intraday_0222.csv.gz  in=111,285,845 out=0 elapsed=71.1s

  [222/13157] intraday_0221.csv.gz  in=111,302,939 out=0 elapsed=71.1s

  [223/13157] intraday_0224.csv.gz  in=111,316,587 out=0 elapsed=71.2s

  [224/13157] intraday_0226.csv.gz  in=111,329,742 out=0 elapsed=71.2s

  [225/13157] intraday_0225.csv.gz  in=111,344,183 out=0 elapsed=71.2s

  [226/13157] intraday_0223.csv.gz  in=111,358,887 out=0 elapsed=71.2s

  [227/13157] intraday_0228.csv.gz  in=111,375,321 out=0 elapsed=71.2s

  [228/13157] intraday_0227.csv.gz  in=111,389,838 out=0 elapsed=71.2s

  [229/13157] intraday_0229.csv.gz  in=111,403,698 out=0 elapsed=71.3s

  [230/13157] intraday_0230.csv.gz  in=111,418,264 out=0 elapsed=71.3s

  [231/13157] intraday_0231.csv.gz  in=111,430,225 out=0 elapsed=71.3s

  [232/13157] intraday_0232.csv.gz  in=111,444,220 out=0 elapsed=71.3s

  [233/13157] intraday_0234.csv.gz  in=111,459,020 out=0 elapsed=71.4s

  [234/13157] intraday_0235.csv.gz  in=111,473,640 out=0 elapsed=71.4s

  [235/13157] intraday_0236.csv.gz  in=111,490,559 out=0 elapsed=71.5s

  [236/13157] intraday_0233.csv.gz  in=111,507,721 out=0 elapsed=71.5s

  [237/13157] intraday_0237.csv.gz  in=111,520,281 out=0 elapsed=71.6s

  [238/13157] intraday_0239.csv.gz  in=111,536,992 out=0 elapsed=71.6s

  [239/13157] intraday_0240.csv.gz  in=111,551,382 out=0 elapsed=71.6s

  [240/13157] intraday_0238.csv.gz  in=111,568,283 out=0 elapsed=71.6s

  [241/13157] intraday_0242.csv.gz  in=111,581,855 out=0 elapsed=71.8s

  [242/13157] intraday_0244.csv.gz  in=111,598,511 out=0 elapsed=71.8s

  [243/13157] intraday_0241.csv.gz  in=111,615,055 out=0 elapsed=71.8s

  [244/13157] intraday_0243.csv.gz  in=111,641,791 out=0 elapsed=71.8s

  [245/13157] intraday_0245.csv.gz  in=111,654,087 out=0 elapsed=71.8s

  [246/13157] intraday_0247.csv.gz  in=111,668,111 out=0 elapsed=71.9s

  [247/13157] intraday_0248.csv.gz  in=111,681,670 out=0 elapsed=71.9s

  [248/13157] intraday_0246.csv.gz  in=111,697,128 out=0 elapsed=71.9s

  [249/13157] intraday_0251.csv.gz  in=111,710,264 out=0 elapsed=71.9s

  [250/13157] intraday_0250.csv.gz  in=111,725,966 out=0 elapsed=71.9s

  [251/13157] intraday_0249.csv.gz  in=111,741,334 out=0 elapsed=71.9s

  [252/13157] intraday_0252.csv.gz  in=111,762,442 out=0 elapsed=71.9s

  [253/13157] intraday_0253.csv.gz  in=111,775,789 out=0 elapsed=72.1s

  [254/13157] intraday_0254.csv.gz  in=111,790,210 out=0 elapsed=72.1s

  [255/13157] intraday_0255.csv.gz  in=111,808,314 out=0 elapsed=72.1s

  [256/13157] intraday_0256.csv.gz  in=111,824,019 out=0 elapsed=72.1s

  [257/13157] intraday_0257.csv.gz  in=111,839,272 out=0 elapsed=72.1s

  [258/13157] intraday_0258.csv.gz  in=111,855,418 out=0 elapsed=72.1s

  [259/13157] intraday_0259.csv.gz  in=111,870,028 out=0 elapsed=72.1s

  [260/13157] intraday_0260.csv.gz  in=111,886,263 out=0 elapsed=72.2s

  [261/13157] intraday_0261.csv.gz  in=111,900,357 out=0 elapsed=72.2s

  [262/13157] intraday_0262.csv.gz  in=111,912,297 out=0 elapsed=72.2s

  [263/13157] intraday_0263.csv.gz  in=111,926,807 out=0 elapsed=72.2s

  [264/13157] intraday_0264.csv.gz  in=111,940,725 out=0 elapsed=72.2s

  [265/13157] intraday_0265.csv.gz  in=111,955,763 out=0 elapsed=72.2s

  [266/13157] intraday_0268.csv.gz  in=111,956,117 out=0 elapsed=72.4s

  [267/13157] intraday_0266.csv.gz  in=111,965,040 out=0 elapsed=72.4s

  [268/13157] intraday_0267.csv.gz  in=111,978,303 out=0 elapsed=72.4s

  [269/13157] intraday_0271.csv.gz  in=112,194,521 out=0 elapsed=73.4s

  [270/13157] intraday_0272.csv.gz  in=112,427,225 out=0 elapsed=73.4s

  [271/13157] intraday_0270.csv.gz  in=112,691,292 out=0 elapsed=73.5s

  [272/13157] intraday_0269.csv.gz  in=112,987,663 out=0 elapsed=73.5s

  [273/13157] intraday_0273.csv.gz  in=113,246,304 out=0 elapsed=74.0s

  [274/13157] intraday_0275.csv.gz  in=113,479,352 out=0 elapsed=74.0s

  [275/13157] intraday_0274.csv.gz  in=113,760,473 out=0 elapsed=74.1s

  [276/13157] intraday_0276.csv.gz  in=114,011,989 out=0 elapsed=74.1s

  [277/13157] intraday_0278.csv.gz  in=114,258,113 out=0 elapsed=74.6s

  [278/13157] intraday_0277.csv.gz  in=114,559,277 out=0 elapsed=74.6s

  [279/13157] intraday_0279.csv.gz  in=114,801,886 out=0 elapsed=74.6s

  [280/13157] intraday_0280.csv.gz  in=115,056,079 out=0 elapsed=74.7s

  [281/13157] intraday_0282.csv.gz  in=115,248,860 out=0 elapsed=75.3s

  [282/13157] intraday_0283.csv.gz  in=115,448,136 out=0 elapsed=75.4s

  [283/13157] intraday_0286.csv.gz  in=115,486,870 out=0 elapsed=75.4s

  [284/13157] intraday_0281.csv.gz  in=115,748,047 out=0 elapsed=75.5s

  [285/13157] intraday_0284.csv.gz  in=116,043,246 out=0 elapsed=75.5s

  [286/13157] intraday_0285.csv.gz  in=116,298,084 out=0 elapsed=76.1s

  [287/13157] intraday_0287.csv.gz  in=116,525,928 out=0 elapsed=76.2s

  [288/13157] intraday_0288.csv.gz  in=116,746,745 out=0 elapsed=76.2s

  [289/13157] intraday_0289.csv.gz  in=116,965,439 out=0 elapsed=76.2s

  [290/13157] intraday_0290.csv.gz  in=117,225,315 out=0 elapsed=76.7s

  [291/13157] intraday_0291.csv.gz  in=117,445,345 out=0 elapsed=76.8s

  [292/13157] intraday_0293.csv.gz  in=117,688,081 out=0 elapsed=76.8s

  [293/13157] intraday_0292.csv.gz  in=117,927,992 out=0 elapsed=76.8s

  [294/13157] intraday_0294.csv.gz  in=118,143,729 out=0 elapsed=77.0s

  [295/13157] intraday_0295.csv.gz  in=118,357,943 out=0 elapsed=77.0s

  [296/13157] intraday_0296.csv.gz  in=118,563,185 out=0 elapsed=77.1s

  [297/13157] intraday_0297.csv.gz  in=118,843,298 out=0 elapsed=77.1s

  [298/13157] intraday_0298.csv.gz  in=119,126,473 out=0 elapsed=77.4s

  [299/13157] intraday_0300.csv.gz  in=119,350,117 out=0 elapsed=77.4s

  [300/13157] intraday_0301.csv.gz  in=119,570,005 out=0 elapsed=77.4s

  [301/13157] intraday_0299.csv.gz  in=119,831,995 out=0 elapsed=77.4s

  [302/13157] intraday_0302.csv.gz  in=119,886,957 out=0 elapsed=77.4s

  [303/13157] intraday_0304.csv.gz  in=120,123,356 out=0 elapsed=77.9s

  [304/13157] intraday_0305.csv.gz  in=120,358,027 out=0 elapsed=77.9s

  [305/13157] intraday_0306.csv.gz  in=120,604,925 out=0 elapsed=77.9s

  [306/13157] intraday_0303.csv.gz  in=120,902,289 out=0 elapsed=77.9s

  [307/13157] intraday_0307.csv.gz  in=121,125,738 out=0 elapsed=78.5s

  [308/13157] intraday_0310.csv.gz  in=121,346,944 out=0 elapsed=78.7s

  [309/13157] intraday_0308.csv.gz  in=121,572,408 out=0 elapsed=78.7s

  [310/13157] intraday_0309.csv.gz  in=121,811,036 out=0 elapsed=78.7s

  [311/13157] intraday_0311.csv.gz  in=122,090,746 out=0 elapsed=78.9s

  [312/13157] intraday_0313.csv.gz  in=122,328,043 out=0 elapsed=79.0s

  [313/13157] intraday_0314.csv.gz  in=122,589,076 out=0 elapsed=79.1s

  [314/13157] intraday_0312.csv.gz  in=122,890,640 out=0 elapsed=79.1s

  [315/13157] intraday_0315.csv.gz  in=123,155,037 out=0 elapsed=79.2s

  [316/13157] intraday_0316.csv.gz  in=123,403,821 out=0 elapsed=79.3s

  [317/13157] intraday_0317.csv.gz  in=123,666,559 out=0 elapsed=79.3s

  [318/13157] intraday_0318.csv.gz  in=123,900,660 out=0 elapsed=79.4s

  [319/13157] intraday_0319.csv.gz  in=124,176,134 out=0 elapsed=79.6s

  [320/13157] intraday_0320.csv.gz  in=124,416,353 out=0 elapsed=79.6s

  [321/13157] intraday_0321.csv.gz  in=124,669,219 out=0 elapsed=79.6s

  [322/13157] intraday_0322.csv.gz  in=124,909,648 out=0 elapsed=79.7s

  [323/13157] intraday_0323.csv.gz  in=125,155,264 out=0 elapsed=79.9s

  [324/13157] intraday_0324.csv.gz  in=125,389,255 out=0 elapsed=79.9s

  [325/13157] intraday_0325.csv.gz  in=125,649,135 out=0 elapsed=80.0s

  [326/13157] intraday_0326.csv.gz  in=125,911,356 out=0 elapsed=80.0s

  [327/13157] intraday_0327.csv.gz  in=126,118,825 out=0 elapsed=80.5s

  [328/13157] intraday_0330.csv.gz  in=126,315,329 out=0 elapsed=80.8s

  [329/13157] intraday_0329.csv.gz  in=126,524,157 out=0 elapsed=80.9s

  [330/13157] intraday_0328.csv.gz  in=126,779,582 out=0 elapsed=80.9s

  [331/13157] intraday_0331.csv.gz  in=127,046,519 out=0 elapsed=81.4s

  [332/13157] intraday_0333.csv.gz  in=127,253,545 out=0 elapsed=81.8s

  [333/13157] intraday_0332.csv.gz  in=127,538,683 out=0 elapsed=81.8s

  [334/13157] intraday_0334.csv.gz  in=127,816,232 out=0 elapsed=81.9s

  [335/13157] intraday_0335.csv.gz  in=128,092,776 out=0 elapsed=81.9s

  [336/13157] intraday_0336.csv.gz  in=128,295,496 out=0 elapsed=82.1s

  [337/13157] intraday_0337.csv.gz  in=128,525,452 out=0 elapsed=82.1s

  [338/13157] intraday_0338.csv.gz  in=128,783,286 out=0 elapsed=82.2s

  [339/13157] intraday_0339.csv.gz  in=129,042,667 out=0 elapsed=82.2s

  [340/13157] intraday_0340.csv.gz  in=129,240,852 out=0 elapsed=82.4s

  [341/13157] intraday_0341.csv.gz  in=129,458,823 out=0 elapsed=82.5s

  [342/13157] intraday_0342.csv.gz  in=129,667,620 out=0 elapsed=82.5s

  [343/13157] intraday_0343.csv.gz  in=129,899,349 out=0 elapsed=82.6s

  [344/13157] intraday_0346.csv.gz  in=130,081,697 out=0 elapsed=82.9s

  [345/13157] intraday_0345.csv.gz  in=130,320,268 out=0 elapsed=83.0s

  [346/13157] intraday_0344.csv.gz  in=130,559,285 out=0 elapsed=83.0s

  [347/13157] intraday_0347.csv.gz  in=130,772,959 out=0 elapsed=83.0s

  [348/13157] intraday_0348.csv.gz  in=131,024,833 out=0 elapsed=83.8s

  [349/13157] intraday_0351.csv.gz  in=131,251,197 out=0 elapsed=84.0s

  [350/13157] intraday_0350.csv.gz  in=131,487,660 out=0 elapsed=84.0s

  [351/13157] intraday_0349.csv.gz  in=131,797,285 out=0 elapsed=84.0s

  [352/13157] intraday_0352.csv.gz  in=132,033,883 out=0 elapsed=84.1s

  [353/13157] intraday_0354.csv.gz  in=132,264,196 out=0 elapsed=84.4s

  [354/13157] intraday_0353.csv.gz  in=132,523,180 out=0 elapsed=84.4s

  [355/13157] intraday_0356.csv.gz  in=132,764,167 out=0 elapsed=84.8s

  [356/13157] intraday_0355.csv.gz  in=133,077,260 out=0 elapsed=85.3s

  [357/13157] intraday_0358.csv.gz  in=133,361,149 out=0 elapsed=85.6s

  [358/13157] intraday_0357.csv.gz  in=133,649,154 out=0 elapsed=85.6s

  [359/13157] intraday_0359.csv.gz  in=133,915,035 out=0 elapsed=85.6s

  [360/13157] intraday_0360.csv.gz  in=134,168,226 out=0 elapsed=85.7s

  [361/13157] intraday_0361.csv.gz  in=134,407,423 out=0 elapsed=86.8s

  [362/13157] intraday_0363.csv.gz  in=134,653,394 out=0 elapsed=86.8s

  [363/13157] intraday_0364.csv.gz  in=134,899,662 out=0 elapsed=86.8s

  [364/13157] intraday_0362.csv.gz  in=135,155,263 out=0 elapsed=86.8s

  [365/13157] intraday_0365.csv.gz  in=135,380,830 out=0 elapsed=87.7s

  [366/13157] intraday_0368.csv.gz  in=135,614,304 out=0 elapsed=87.7s

  [367/13157] intraday_0366.csv.gz  in=135,878,241 out=0 elapsed=87.7s

  [368/13157] intraday_0367.csv.gz  in=136,162,187 out=0 elapsed=87.8s

  [369/13157] intraday_0369.csv.gz  in=136,435,160 out=0 elapsed=88.9s

  [370/13157] intraday_0371.csv.gz  in=136,707,812 out=0 elapsed=88.9s

  [371/13157] intraday_0372.csv.gz  in=136,974,668 out=0 elapsed=89.0s

  [372/13157] intraday_0370.csv.gz  in=137,296,332 out=0 elapsed=89.0s

  [373/13157] intraday_0375.csv.gz  in=137,499,671 out=0 elapsed=89.9s

  [374/13157] intraday_0374.csv.gz  in=137,769,708 out=0 elapsed=90.1s

  [375/13157] intraday_0373.csv.gz  in=138,017,550 out=0 elapsed=90.1s

  [376/13157] intraday_0376.csv.gz  in=138,328,425 out=0 elapsed=90.2s

  [377/13157] intraday_0377.csv.gz  in=138,565,665 out=0 elapsed=90.2s

  [378/13157] intraday_0379.csv.gz  in=138,818,657 out=0 elapsed=90.8s

  [379/13157] intraday_0378.csv.gz  in=139,087,787 out=0 elapsed=90.9s

  [380/13157] intraday_0381.csv.gz  in=139,361,407 out=0 elapsed=90.9s

  [381/13157] intraday_0380.csv.gz  in=139,648,162 out=0 elapsed=90.9s

  [382/13157] intraday_0382.csv.gz  in=139,904,999 out=0 elapsed=91.3s

  [383/13157] intraday_0383.csv.gz  in=140,179,278 out=0 elapsed=91.3s

  [384/13157] intraday_0385.csv.gz  in=140,391,955 out=0 elapsed=91.3s

  [385/13157] intraday_0384.csv.gz  in=140,640,779 out=0 elapsed=91.3s

  [386/13157] intraday_0386.csv.gz  in=140,878,294 out=0 elapsed=91.8s

  [387/13157] intraday_0388.csv.gz  in=141,130,561 out=0 elapsed=91.9s

  [388/13157] intraday_0387.csv.gz  in=141,399,520 out=0 elapsed=91.9s

  [389/13157] intraday_0389.csv.gz  in=141,725,055 out=0 elapsed=92.0s

  [390/13157] intraday_0390.csv.gz  in=141,949,153 out=0 elapsed=92.4s

  [391/13157] intraday_0391.csv.gz  in=142,203,569 out=0 elapsed=92.9s

  [392/13157] intraday_0392.csv.gz  in=142,457,409 out=0 elapsed=92.9s

  [393/13157] intraday_0393.csv.gz  in=142,721,977 out=0 elapsed=93.0s

  [394/13157] intraday_0394.csv.gz  in=142,966,664 out=0 elapsed=93.0s

  [395/13157] intraday_0395.csv.gz  in=143,253,685 out=0 elapsed=93.7s

  [396/13157] intraday_0397.csv.gz  in=143,499,019 out=0 elapsed=94.0s

  [397/13157] intraday_0398.csv.gz  in=143,756,028 out=0 elapsed=94.1s

  [398/13157] intraday_0396.csv.gz  in=144,034,957 out=0 elapsed=94.1s

  [399/13157] intraday_0399.csv.gz  in=144,258,829 out=0 elapsed=94.3s

  [400/13157] intraday_0401.csv.gz  in=144,456,402 out=0 elapsed=94.4s

  [401/13157] intraday_0400.csv.gz  in=144,678,165 out=0 elapsed=94.4s

  [402/13157] intraday_0402.csv.gz  in=144,938,220 out=0 elapsed=94.4s

  [403/13157] intraday_0406.csv.gz  in=144,952,932 out=0 elapsed=94.5s

  [404/13157] intraday_0407.csv.gz  in=144,977,359 out=0 elapsed=94.5s

  [405/13157] intraday_0408.csv.gz  in=144,989,626 out=0 elapsed=94.6s

  [406/13157] intraday_0409.csv.gz  in=145,002,992 out=0 elapsed=94.6s

  [407/13157] intraday_0403.csv.gz  in=145,216,313 out=0 elapsed=94.6s

  [408/13157] intraday_0404.csv.gz  in=145,377,611 out=0 elapsed=94.6s

  [409/13157] intraday_0410.csv.gz  in=145,392,730 out=0 elapsed=94.6s

  [410/13157] intraday_0411.csv.gz  in=145,408,587 out=0 elapsed=94.6s

  [411/13157] intraday_0412.csv.gz  in=145,419,651 out=0 elapsed=94.7s

  [412/13157] intraday_0414.csv.gz  in=145,434,222 out=0 elapsed=94.7s

  [413/13157] intraday_0413.csv.gz  in=145,447,206 out=0 elapsed=94.7s

  [414/13157] intraday_0416.csv.gz  in=145,458,604 out=0 elapsed=94.7s

  [415/13157] intraday_0415.csv.gz  in=145,471,403 out=0 elapsed=94.7s

  [416/13157] intraday_0405.csv.gz  in=145,695,807 out=0 elapsed=94.7s

  [417/13157] intraday_0417.csv.gz  in=145,709,282 out=0 elapsed=94.7s

  [418/13157] intraday_0418.csv.gz  in=145,723,588 out=0 elapsed=94.7s

  [419/13157] intraday_0419.csv.gz  in=145,734,865 out=0 elapsed=94.8s

  [420/13157] intraday_0420.csv.gz  in=145,746,540 out=0 elapsed=94.8s

  [421/13157] intraday_0421.csv.gz  in=145,761,843 out=0 elapsed=94.8s

  [422/13157] intraday_0422.csv.gz  in=145,775,162 out=0 elapsed=94.8s

  [423/13157] intraday_0423.csv.gz  in=145,786,663 out=0 elapsed=94.8s

  [424/13157] intraday_0424.csv.gz  in=145,797,862 out=0 elapsed=94.8s

  [425/13157] intraday_0425.csv.gz  in=145,809,626 out=0 elapsed=94.8s

  [426/13157] intraday_0426.csv.gz  in=145,821,626 out=0 elapsed=94.8s

  [427/13157] intraday_0427.csv.gz  in=145,833,678 out=0 elapsed=94.8s

  [428/13157] intraday_0429.csv.gz  in=145,846,736 out=0 elapsed=94.9s

  [429/13157] intraday_0428.csv.gz  in=145,859,925 out=0 elapsed=94.9s

  [430/13157] intraday_0430.csv.gz  in=145,870,744 out=0 elapsed=94.9s

  [431/13157] intraday_0431.csv.gz  in=145,882,155 out=0 elapsed=94.9s

  [432/13157] intraday_0432.csv.gz  in=145,893,068 out=0 elapsed=94.9s

  [433/13157] intraday_0433.csv.gz  in=145,907,644 out=0 elapsed=94.9s

  [434/13157] intraday_0434.csv.gz  in=145,923,420 out=0 elapsed=94.9s

  [435/13157] intraday_0435.csv.gz  in=145,939,651 out=0 elapsed=94.9s

  [436/13157] intraday_0436.csv.gz  in=145,951,958 out=0 elapsed=94.9s

  [437/13157] intraday_0440.csv.gz  in=145,964,214 out=0 elapsed=95.0s

  [438/13157] intraday_0437.csv.gz  in=145,976,204 out=0 elapsed=95.0s

  [439/13157] intraday_0439.csv.gz  in=145,994,024 out=0 elapsed=95.0s

  [440/13157] intraday_0438.csv.gz  in=146,007,004 out=0 elapsed=95.0s

  [441/13157] intraday_0441.csv.gz  in=146,018,926 out=0 elapsed=95.0s

  [442/13157] intraday_0442.csv.gz  in=146,032,539 out=0 elapsed=95.0s

  [443/13157] intraday_0444.csv.gz  in=146,044,881 out=0 elapsed=95.0s

  [444/13157] intraday_0443.csv.gz  in=146,056,615 out=0 elapsed=95.0s

  [445/13157] intraday_0446.csv.gz  in=146,070,179 out=0 elapsed=95.1s

  [446/13157] intraday_0448.csv.gz  in=146,083,695 out=0 elapsed=95.1s

  [447/13157] intraday_0447.csv.gz  in=146,097,867 out=0 elapsed=95.1s

  [448/13157] intraday_0445.csv.gz  in=146,112,265 out=0 elapsed=95.1s

  [449/13157] intraday_0451.csv.gz  in=146,124,850 out=0 elapsed=95.1s

  [450/13157] intraday_0450.csv.gz  in=146,138,212 out=0 elapsed=95.1s

  [451/13157] intraday_0452.csv.gz  in=146,156,689 out=0 elapsed=95.2s

  [452/13157] intraday_0449.csv.gz  in=146,194,390 out=0 elapsed=95.2s

  [453/13157] intraday_0453.csv.gz  in=146,206,987 out=0 elapsed=95.2s

  [454/13157] intraday_0454.csv.gz  in=146,219,751 out=0 elapsed=95.2s

  [455/13157] intraday_0456.csv.gz  in=146,232,043 out=0 elapsed=95.2s

  [456/13157] intraday_0455.csv.gz  in=146,255,603 out=0 elapsed=95.2s

  [457/13157] intraday_0457.csv.gz  in=146,269,716 out=0 elapsed=95.3s

  [458/13157] intraday_0459.csv.gz  in=146,283,066 out=0 elapsed=95.3s

  [459/13157] intraday_0458.csv.gz  in=146,296,147 out=0 elapsed=95.3s

  [460/13157] intraday_0460.csv.gz  in=146,311,892 out=0 elapsed=95.3s

  [461/13157] intraday_0462.csv.gz  in=146,325,476 out=0 elapsed=95.3s

  [462/13157] intraday_0461.csv.gz  in=146,337,792 out=0 elapsed=95.3s

  [463/13157] intraday_0464.csv.gz  in=146,349,560 out=0 elapsed=95.3s

  [464/13157] intraday_0463.csv.gz  in=146,362,048 out=0 elapsed=95.3s

  [465/13157] intraday_0466.csv.gz  in=146,374,668 out=0 elapsed=95.4s

  [466/13157] intraday_0467.csv.gz  in=146,391,937 out=0 elapsed=95.4s

  [467/13157] intraday_0468.csv.gz  in=146,403,900 out=0 elapsed=95.4s

  [468/13157] intraday_0465.csv.gz  in=146,429,806 out=0 elapsed=95.4s

  [469/13157] intraday_0472.csv.gz  in=146,441,752 out=0 elapsed=95.6s

  [470/13157] intraday_0471.csv.gz  in=146,454,378 out=0 elapsed=95.6s

  [471/13157] intraday_0469.csv.gz  in=146,469,015 out=0 elapsed=95.6s

  [472/13157] intraday_0470.csv.gz  in=146,483,702 out=0 elapsed=95.6s

  [473/13157] intraday_0474.csv.gz  in=146,496,698 out=0 elapsed=95.7s

  [474/13157] intraday_0473.csv.gz  in=146,508,636 out=0 elapsed=95.8s

  [475/13157] intraday_0475.csv.gz  in=146,521,728 out=0 elapsed=95.8s

  [476/13157] intraday_0476.csv.gz  in=146,533,238 out=0 elapsed=95.8s

  [477/13157] intraday_0477.csv.gz  in=146,542,494 out=0 elapsed=95.9s

  [478/13157] intraday_0480.csv.gz  in=146,554,216 out=0 elapsed=95.9s

  [479/13157] intraday_0479.csv.gz  in=146,567,233 out=0 elapsed=95.9s

  [480/13157] intraday_0478.csv.gz  in=146,579,673 out=0 elapsed=95.9s

  [481/13157] intraday_0481.csv.gz  in=146,591,926 out=0 elapsed=95.9s

  [482/13157] intraday_0484.csv.gz  in=146,603,907 out=0 elapsed=96.1s

  [483/13157] intraday_0483.csv.gz  in=146,614,586 out=0 elapsed=96.1s

  [484/13157] intraday_0482.csv.gz  in=146,625,831 out=0 elapsed=96.1s

  [485/13157] intraday_0486.csv.gz  in=146,637,692 out=0 elapsed=96.2s

  [486/13157] intraday_0485.csv.gz  in=146,655,077 out=0 elapsed=96.2s

  [487/13157] intraday_0487.csv.gz  in=146,665,512 out=0 elapsed=96.2s

  [488/13157] intraday_0488.csv.gz  in=146,679,315 out=0 elapsed=96.2s

  [489/13157] intraday_0491.csv.gz  in=146,694,182 out=0 elapsed=96.4s

  [490/13157] intraday_0489.csv.gz  in=146,706,683 out=0 elapsed=96.4s

  [491/13157] intraday_0490.csv.gz  in=146,724,538 out=0 elapsed=96.4s

  [492/13157] intraday_0492.csv.gz  in=146,738,727 out=0 elapsed=96.4s

  [493/13157] intraday_0493.csv.gz  in=146,752,962 out=0 elapsed=96.5s

  [494/13157] intraday_0495.csv.gz  in=146,766,539 out=0 elapsed=96.5s

  [495/13157] intraday_0494.csv.gz  in=146,781,319 out=0 elapsed=96.5s

  [496/13157] intraday_0496.csv.gz  in=146,796,225 out=0 elapsed=96.5s

  [497/13157] intraday_0499.csv.gz  in=146,807,540 out=0 elapsed=96.6s

  [498/13157] intraday_0498.csv.gz  in=146,820,728 out=0 elapsed=96.6s

  [499/13157] intraday_0497.csv.gz  in=146,840,301 out=0 elapsed=96.6s

  [500/13157] intraday_0500.csv.gz  in=146,860,626 out=0 elapsed=96.6s

  [501/13157] intraday_0502.csv.gz  in=146,877,748 out=0 elapsed=96.6s

  [502/13157] intraday_0501.csv.gz  in=146,896,886 out=0 elapsed=96.6s

  [503/13157] intraday_0504.csv.gz  in=146,909,552 out=0 elapsed=96.6s

  [504/13157] intraday_0503.csv.gz  in=146,923,190 out=0 elapsed=96.6s

  [505/13157] intraday_0505.csv.gz  in=146,938,528 out=0 elapsed=96.6s

  [506/13157] intraday_0507.csv.gz  in=146,954,063 out=0 elapsed=96.6s

  [507/13157] intraday_0506.csv.gz  in=146,990,344 out=0 elapsed=96.7s

  [508/13157] intraday_0508.csv.gz  in=147,019,489 out=0 elapsed=96.7s

  [509/13157] intraday_0511.csv.gz  in=147,033,248 out=0 elapsed=96.7s

  [510/13157] intraday_0510.csv.gz  in=147,044,615 out=0 elapsed=96.7s

  [511/13157] intraday_0509.csv.gz  in=147,060,675 out=0 elapsed=96.7s

  [512/13157] intraday_0512.csv.gz  in=147,077,697 out=0 elapsed=96.7s

  [513/13157] intraday_0515.csv.gz  in=147,092,499 out=0 elapsed=96.7s

  [514/13157] intraday_0514.csv.gz  in=147,110,206 out=0 elapsed=96.7s

  [515/13157] intraday_0513.csv.gz  in=147,122,880 out=0 elapsed=96.7s

  [516/13157] intraday_0516.csv.gz  in=147,137,901 out=0 elapsed=96.8s

  [517/13157] intraday_0518.csv.gz  in=147,150,061 out=0 elapsed=96.8s

  [518/13157] intraday_0519.csv.gz  in=147,163,669 out=0 elapsed=96.8s

  [519/13157] intraday_0517.csv.gz  in=147,180,329 out=0 elapsed=96.8s

  [520/13157] intraday_0521.csv.gz  in=147,193,289 out=0 elapsed=96.9s

  [521/13157] intraday_0523.csv.gz  in=147,208,101 out=0 elapsed=96.9s

  [522/13157] intraday_0520.csv.gz  in=147,219,410 out=0 elapsed=96.9s

  [523/13157] intraday_0522.csv.gz  in=147,232,671 out=0 elapsed=96.9s

  [524/13157] intraday_0524.csv.gz  in=147,245,780 out=0 elapsed=96.9s

  [525/13157] intraday_0526.csv.gz  in=147,258,699 out=0 elapsed=96.9s

  [526/13157] intraday_0525.csv.gz  in=147,274,492 out=0 elapsed=96.9s

  [527/13157] intraday_0527.csv.gz  in=147,287,469 out=0 elapsed=96.9s

  [528/13157] intraday_0530.csv.gz  in=147,301,758 out=0 elapsed=97.0s

  [529/13157] intraday_0529.csv.gz  in=147,314,103 out=0 elapsed=97.0s

  [530/13157] intraday_0528.csv.gz  in=147,331,059 out=0 elapsed=97.0s

  [531/13157] intraday_0531.csv.gz  in=147,347,109 out=0 elapsed=97.0s

  [532/13157] intraday_0532.csv.gz  in=147,361,302 out=0 elapsed=97.0s

  [533/13157] intraday_0533.csv.gz  in=147,376,091 out=0 elapsed=97.1s

  [534/13157] intraday_0534.csv.gz  in=147,390,514 out=0 elapsed=97.1s

  [535/13157] intraday_0535.csv.gz  in=147,401,061 out=0 elapsed=97.1s

  [536/13157] intraday_0536.csv.gz  in=147,412,623 out=0 elapsed=97.1s

  [537/13157] intraday_0537.csv.gz  in=147,423,684 out=0 elapsed=97.1s

  [538/13157] intraday_0539.csv.gz  in=147,434,680 out=0 elapsed=97.1s

  [539/13157] intraday_0538.csv.gz  in=147,448,480 out=0 elapsed=97.1s

  [540/13157] intraday_0541.csv.gz  in=147,456,974 out=0 elapsed=97.2s

  [541/13157] intraday_0540.csv.gz  in=147,466,999 out=0 elapsed=97.2s

  [542/13157] intraday_0543.csv.gz  in=147,496,589 out=0 elapsed=97.2s

  [543/13157] intraday_0544.csv.gz  in=147,523,470 out=0 elapsed=97.2s

  [544/13157] intraday_0542.csv.gz  in=147,565,316 out=0 elapsed=97.2s

  [545/13157] intraday_0545.csv.gz  in=147,606,543 out=0 elapsed=97.3s

  [546/13157] intraday_0548.csv.gz  in=147,630,483 out=0 elapsed=97.3s

  [547/13157] intraday_0549.csv.gz  in=147,658,073 out=0 elapsed=97.3s

  [548/13157] intraday_0546.csv.gz  in=147,689,491 out=0 elapsed=97.3s

  [549/13157] intraday_0547.csv.gz  in=147,723,194 out=0 elapsed=97.3s

  [550/13157] intraday_0552.csv.gz  in=147,747,233 out=0 elapsed=97.5s

  [551/13157] intraday_0550.csv.gz  in=147,776,750 out=0 elapsed=97.5s

  [552/13157] intraday_0553.csv.gz  in=147,805,298 out=0 elapsed=97.6s

  [553/13157] intraday_0551.csv.gz  in=147,832,832 out=0 elapsed=97.6s

  [554/13157] intraday_0555.csv.gz  in=147,855,311 out=0 elapsed=97.6s

  [555/13157] intraday_0554.csv.gz  in=147,886,316 out=0 elapsed=97.6s

  [556/13157] intraday_0556.csv.gz  in=147,910,090 out=0 elapsed=97.8s

  [557/13157] intraday_0558.csv.gz  in=147,938,681 out=0 elapsed=97.8s

  [558/13157] intraday_0559.csv.gz  in=147,965,554 out=0 elapsed=97.8s

  [559/13157] intraday_0557.csv.gz  in=147,997,082 out=0 elapsed=97.8s

  [560/13157] intraday_0560.csv.gz  in=148,020,950 out=0 elapsed=98.0s

  [561/13157] intraday_0562.csv.gz  in=148,046,013 out=0 elapsed=98.0s

  [562/13157] intraday_0561.csv.gz  in=148,073,086 out=0 elapsed=98.0s

  [563/13157] intraday_0563.csv.gz  in=148,097,855 out=0 elapsed=98.0s

  [564/13157] intraday_0566.csv.gz  in=148,121,408 out=0 elapsed=98.0s

  [565/13157] intraday_0565.csv.gz  in=148,148,661 out=0 elapsed=98.0s

  [566/13157] intraday_0564.csv.gz  in=148,175,781 out=0 elapsed=98.0s

  [567/13157] intraday_0567.csv.gz  in=148,198,952 out=0 elapsed=98.0s

  [568/13157] intraday_0568.csv.gz  in=148,219,961 out=0 elapsed=98.1s

  [569/13157] intraday_0569.csv.gz  in=148,251,292 out=0 elapsed=98.1s

  [570/13157] intraday_0570.csv.gz  in=148,284,544 out=0 elapsed=98.1s

  [571/13157] intraday_0572.csv.gz  in=148,308,858 out=0 elapsed=98.1s

  [572/13157] intraday_0571.csv.gz  in=148,341,303 out=0 elapsed=98.1s

  [573/13157] intraday_0573.csv.gz  in=148,367,608 out=0 elapsed=98.1s

  [574/13157] intraday_0574.csv.gz  in=148,395,071 out=0 elapsed=98.1s

  [575/13157] intraday_0577.csv.gz  in=148,420,604 out=0 elapsed=98.2s

  [576/13157] intraday_0578.csv.gz  in=148,452,628 out=0 elapsed=98.2s

  [577/13157] intraday_0576.csv.gz  in=148,483,393 out=0 elapsed=98.2s

  [578/13157] intraday_0575.csv.gz  in=148,517,233 out=0 elapsed=98.2s

  [579/13157] intraday_0580.csv.gz  in=148,543,926 out=0 elapsed=98.4s

  [580/13157] intraday_0581.csv.gz  in=148,576,672 out=0 elapsed=98.4s

  [581/13157] intraday_0582.csv.gz  in=148,607,706 out=0 elapsed=98.4s

  [582/13157] intraday_0579.csv.gz  in=148,659,685 out=0 elapsed=98.4s

  [583/13157] intraday_0585.csv.gz  in=148,685,737 out=0 elapsed=98.4s

  [584/13157] intraday_0583.csv.gz  in=148,714,730 out=0 elapsed=98.5s

  [585/13157] intraday_0584.csv.gz  in=148,745,268 out=0 elapsed=98.5s

  [586/13157] intraday_0587.csv.gz  in=148,771,206 out=0 elapsed=98.6s

  [587/13157] intraday_0586.csv.gz  in=148,798,828 out=0 elapsed=98.6s

  [588/13157] intraday_0589.csv.gz  in=148,827,976 out=0 elapsed=98.6s

  [589/13157] intraday_0592.csv.gz  in=148,855,456 out=0 elapsed=98.8s

  [590/13157] intraday_0590.csv.gz  in=148,886,394 out=0 elapsed=98.8s

  [591/13157] intraday_0591.csv.gz  in=148,914,209 out=0 elapsed=98.8s

  [592/13157] intraday_0588.csv.gz  in=148,966,176 out=0 elapsed=98.8s

  [593/13157] intraday_0594.csv.gz  in=148,992,313 out=0 elapsed=98.9s

  [594/13157] intraday_0593.csv.gz  in=149,028,521 out=0 elapsed=98.9s

  [595/13157] intraday_0595.csv.gz  in=149,055,519 out=0 elapsed=98.9s

  [596/13157] intraday_0596.csv.gz  in=149,080,692 out=0 elapsed=98.9s

  [597/13157] intraday_0597.csv.gz  in=149,107,419 out=0 elapsed=99.0s

  [598/13157] intraday_0598.csv.gz  in=149,135,059 out=0 elapsed=99.0s

  [599/13157] intraday_0600.csv.gz  in=149,159,346 out=0 elapsed=99.0s

  [600/13157] intraday_0599.csv.gz  in=149,185,832 out=0 elapsed=99.0s

  [601/13157] intraday_0601.csv.gz  in=149,210,192 out=0 elapsed=99.0s

  [602/13157] intraday_0602.csv.gz  in=149,232,632 out=0 elapsed=99.0s

  [603/13157] intraday_0604.csv.gz  in=149,258,376 out=0 elapsed=99.0s

  [604/13157] intraday_0603.csv.gz  in=149,292,076 out=0 elapsed=99.0s

  [605/13157] intraday_0608.csv.gz  in=149,314,870 out=0 elapsed=99.1s

  [606/13157] intraday_0605.csv.gz  in=149,343,387 out=0 elapsed=99.1s

  [607/13157] intraday_0606.csv.gz  in=149,375,298 out=0 elapsed=99.1s

  [608/13157] intraday_0607.csv.gz  in=149,423,867 out=0 elapsed=99.1s

  [609/13157] intraday_0609.csv.gz  in=149,449,906 out=0 elapsed=99.1s

  [610/13157] intraday_0613.csv.gz  in=149,471,422 out=0 elapsed=99.2s

  [611/13157] intraday_0610.csv.gz  in=149,497,278 out=0 elapsed=99.2s

  [612/13157] intraday_0611.csv.gz  in=149,527,026 out=0 elapsed=99.2s

  [613/13157] intraday_0612.csv.gz  in=149,549,726 out=0 elapsed=99.2s

  [614/13157] intraday_0614.csv.gz  in=149,575,053 out=0 elapsed=99.2s

  [615/13157] intraday_0616.csv.gz  in=149,599,717 out=0 elapsed=99.2s

  [616/13157] intraday_0615.csv.gz  in=149,634,484 out=0 elapsed=99.2s

  [617/13157] intraday_0617.csv.gz  in=149,663,849 out=0 elapsed=99.2s

  [618/13157] intraday_0618.csv.gz  in=149,684,038 out=0 elapsed=99.2s

  [619/13157] intraday_0619.csv.gz  in=149,706,447 out=0 elapsed=99.3s

  [620/13157] intraday_0621.csv.gz  in=149,740,849 out=0 elapsed=99.3s

  [621/13157] intraday_0620.csv.gz  in=149,776,338 out=0 elapsed=99.3s

  [622/13157] intraday_0622.csv.gz  in=149,803,181 out=0 elapsed=99.3s

  [623/13157] intraday_0625.csv.gz  in=149,832,268 out=0 elapsed=99.3s

  [624/13157] intraday_0623.csv.gz  in=149,858,646 out=0 elapsed=99.3s

  [625/13157] intraday_0624.csv.gz  in=149,888,290 out=0 elapsed=99.3s

  [626/13157] intraday_0626.csv.gz  in=149,918,669 out=0 elapsed=99.4s

  [627/13157] intraday_0627.csv.gz  in=149,952,541 out=0 elapsed=99.4s

  [628/13157] intraday_0629.csv.gz  in=149,986,473 out=0 elapsed=99.4s

  [629/13157] intraday_0628.csv.gz  in=150,021,198 out=0 elapsed=99.4s

  [630/13157] intraday_0630.csv.gz  in=150,051,815 out=0 elapsed=99.4s

  [631/13157] intraday_0631.csv.gz  in=150,082,344 out=0 elapsed=99.4s

  [632/13157] intraday_0632.csv.gz  in=150,109,334 out=0 elapsed=99.4s

  [633/13157] intraday_0633.csv.gz  in=150,137,613 out=0 elapsed=99.4s

  [634/13157] intraday_0636.csv.gz  in=150,162,253 out=0 elapsed=99.5s

  [635/13157] intraday_0635.csv.gz  in=150,190,543 out=0 elapsed=99.5s

  [636/13157] intraday_0634.csv.gz  in=150,223,517 out=0 elapsed=99.5s

  [637/13157] intraday_0637.csv.gz  in=150,254,101 out=0 elapsed=99.5s

  [638/13157] intraday_0638.csv.gz  in=150,287,667 out=0 elapsed=99.5s

  [639/13157] intraday_0639.csv.gz  in=150,316,577 out=0 elapsed=99.5s

  [640/13157] intraday_0640.csv.gz  in=150,344,888 out=0 elapsed=99.5s

  [641/13157] intraday_0641.csv.gz  in=150,374,658 out=0 elapsed=99.5s

  [642/13157] intraday_0644.csv.gz  in=150,405,730 out=0 elapsed=99.6s

  [643/13157] intraday_0642.csv.gz  in=150,437,351 out=0 elapsed=99.6s

  [644/13157] intraday_0643.csv.gz  in=150,471,135 out=0 elapsed=99.6s

  [645/13157] intraday_0645.csv.gz  in=150,504,092 out=0 elapsed=99.6s

  [646/13157] intraday_0647.csv.gz  in=150,533,207 out=0 elapsed=99.7s

  [647/13157] intraday_0648.csv.gz  in=150,562,373 out=0 elapsed=99.7s

  [648/13157] intraday_0646.csv.gz  in=150,588,431 out=0 elapsed=99.7s

  [649/13157] intraday_0649.csv.gz  in=150,616,816 out=0 elapsed=99.7s

  [650/13157] intraday_0650.csv.gz  in=150,647,955 out=0 elapsed=99.7s

  [651/13157] intraday_0651.csv.gz  in=150,672,868 out=0 elapsed=99.7s

  [652/13157] intraday_0654.csv.gz  in=150,700,040 out=0 elapsed=99.8s

  [653/13157] intraday_0652.csv.gz  in=150,732,794 out=0 elapsed=99.8s

  [654/13157] intraday_0653.csv.gz  in=150,767,795 out=0 elapsed=99.8s

  [655/13157] intraday_0655.csv.gz  in=150,796,374 out=0 elapsed=99.8s

  [656/13157] intraday_0657.csv.gz  in=150,823,361 out=0 elapsed=99.8s

  [657/13157] intraday_0658.csv.gz  in=150,848,941 out=0 elapsed=99.8s

  [658/13157] intraday_0656.csv.gz  in=150,880,261 out=0 elapsed=99.8s

  [659/13157] intraday_0659.csv.gz  in=150,912,920 out=0 elapsed=99.9s

  [660/13157] intraday_0662.csv.gz  in=150,939,592 out=0 elapsed=99.9s

  [661/13157] intraday_0660.csv.gz  in=150,967,623 out=0 elapsed=99.9s

  [662/13157] intraday_0663.csv.gz  in=150,997,830 out=0 elapsed=99.9s

  [663/13157] intraday_0665.csv.gz  in=151,027,628 out=0 elapsed=100.0s

  [664/13157] intraday_0664.csv.gz  in=151,059,866 out=0 elapsed=100.0s

  [665/13157] intraday_0661.csv.gz  in=151,112,109 out=0 elapsed=100.0s

  [666/13157] intraday_0666.csv.gz  in=151,145,019 out=0 elapsed=100.0s

  [667/13157] intraday_0668.csv.gz  in=151,173,904 out=0 elapsed=100.0s

  [668/13157] intraday_0669.csv.gz  in=151,202,848 out=0 elapsed=100.1s

  [669/13157] intraday_0667.csv.gz  in=151,238,489 out=0 elapsed=100.1s

  [670/13157] intraday_0670.csv.gz  in=151,268,576 out=0 elapsed=100.1s

  [671/13157] intraday_0671.csv.gz  in=151,301,299 out=0 elapsed=100.1s

  [672/13157] intraday_0673.csv.gz  in=151,324,654 out=0 elapsed=100.3s

  [673/13157] intraday_0672.csv.gz  in=151,354,334 out=0 elapsed=100.3s

  [674/13157] intraday_0675.csv.gz  in=151,374,813 out=0 elapsed=100.3s

  [675/13157] intraday_0674.csv.gz  in=151,406,524 out=0 elapsed=100.3s

  [676/13157] intraday_0677.csv.gz  in=151,424,757 out=0 elapsed=100.6s

  [677/13157] intraday_0676.csv.gz  in=151,447,334 out=0 elapsed=100.6s

  [678/13157] intraday_0680.csv.gz  in=151,574,848 out=0 elapsed=101.7s

  [679/13157] intraday_0681.csv.gz  in=151,694,372 out=0 elapsed=101.9s

  [680/13157] intraday_0679.csv.gz  in=151,854,187 out=0 elapsed=101.9s

  [681/13157] intraday_0678.csv.gz  in=152,035,572 out=0 elapsed=101.9s

  [682/13157] intraday_0684.csv.gz  in=152,155,614 out=0 elapsed=102.2s

  [683/13157] intraday_0685.csv.gz  in=152,287,931 out=0 elapsed=102.3s

  [684/13157] intraday_0682.csv.gz  in=152,436,248 out=0 elapsed=102.3s

  [685/13157] intraday_0683.csv.gz  in=152,597,012 out=0 elapsed=102.3s

  [686/13157] intraday_0688.csv.gz  in=152,724,884 out=0 elapsed=102.6s

  [687/13157] intraday_0686.csv.gz  in=152,869,650 out=0 elapsed=102.6s

  [688/13157] intraday_0687.csv.gz  in=153,012,576 out=0 elapsed=102.6s

  [689/13157] intraday_0689.csv.gz  in=153,154,517 out=0 elapsed=102.6s

  [690/13157] intraday_0692.csv.gz  in=153,255,887 out=0 elapsed=103.0s

  [691/13157] intraday_0691.csv.gz  in=153,383,278 out=0 elapsed=103.0s

  [692/13157] intraday_0690.csv.gz  in=153,542,476 out=0 elapsed=103.1s

  [693/13157] intraday_0693.csv.gz  in=153,725,767 out=0 elapsed=103.1s

  [694/13157] intraday_0694.csv.gz  in=153,864,268 out=0 elapsed=103.3s

  [695/13157] intraday_0695.csv.gz  in=153,997,703 out=0 elapsed=103.3s

  [696/13157] intraday_0696.csv.gz  in=154,134,404 out=0 elapsed=103.4s

  [697/13157] intraday_0697.csv.gz  in=154,268,443 out=0 elapsed=103.4s

  [698/13157] intraday_0698.csv.gz  in=154,406,877 out=0 elapsed=103.6s

  [699/13157] intraday_0700.csv.gz  in=154,534,389 out=0 elapsed=103.8s

  [700/13157] intraday_0699.csv.gz  in=154,667,673 out=0 elapsed=103.9s

  [701/13157] intraday_0702.csv.gz  in=154,807,028 out=0 elapsed=104.0s

  [702/13157] intraday_0704.csv.gz  in=154,924,870 out=0 elapsed=104.0s

  [703/13157] intraday_0701.csv.gz  in=155,113,959 out=0 elapsed=104.0s

  [704/13157] intraday_0703.csv.gz  in=155,240,129 out=0 elapsed=104.0s

  [705/13157] intraday_0708.csv.gz  in=155,360,634 out=0 elapsed=104.3s

  [706/13157] intraday_0705.csv.gz  in=155,522,748 out=0 elapsed=104.4s

  [707/13157] intraday_0707.csv.gz  in=155,681,342 out=0 elapsed=104.4s

  [708/13157] intraday_0706.csv.gz  in=155,861,235 out=0 elapsed=104.4s

  [709/13157] intraday_0709.csv.gz  in=155,997,571 out=0 elapsed=104.6s

  [710/13157] intraday_0710.csv.gz  in=156,136,449 out=0 elapsed=104.6s

  [711/13157] intraday_0712.csv.gz  in=156,273,222 out=0 elapsed=104.6s

  [712/13157] intraday_0711.csv.gz  in=156,496,706 out=0 elapsed=104.7s

  [713/13157] intraday_0713.csv.gz  in=156,619,873 out=0 elapsed=104.7s

  [714/13157] intraday_0715.csv.gz  in=156,754,514 out=0 elapsed=104.8s

  [715/13157] intraday_0714.csv.gz  in=156,903,093 out=0 elapsed=104.8s

  [716/13157] intraday_0716.csv.gz  in=157,041,253 out=0 elapsed=105.0s

  [717/13157] intraday_0717.csv.gz  in=157,196,573 out=0 elapsed=105.0s

  [718/13157] intraday_0719.csv.gz  in=157,329,992 out=0 elapsed=105.1s

  [719/13157] intraday_0718.csv.gz  in=157,478,345 out=0 elapsed=105.1s

  [720/13157] intraday_0721.csv.gz  in=157,602,475 out=0 elapsed=105.4s

  [721/13157] intraday_0722.csv.gz  in=157,724,517 out=0 elapsed=105.4s

  [722/13157] intraday_0720.csv.gz  in=157,888,287 out=0 elapsed=105.4s

  [723/13157] intraday_0723.csv.gz  in=158,046,991 out=0 elapsed=105.4s

  [724/13157] intraday_0724.csv.gz  in=158,185,787 out=0 elapsed=105.7s

  [725/13157] intraday_0725.csv.gz  in=158,327,072 out=0 elapsed=105.7s

  [726/13157] intraday_0726.csv.gz  in=158,468,376 out=0 elapsed=105.7s

  [727/13157] intraday_0727.csv.gz  in=158,616,553 out=0 elapsed=105.8s

  [728/13157] intraday_0730.csv.gz  in=158,652,357 out=0 elapsed=105.8s

  [729/13157] intraday_0728.csv.gz  in=158,785,668 out=0 elapsed=105.9s

  [730/13157] intraday_0729.csv.gz  in=158,897,969 out=0 elapsed=105.9s

  [731/13157] intraday_0731.csv.gz  in=159,046,471 out=0 elapsed=105.9s

  [732/13157] intraday_0732.csv.gz  in=159,182,736 out=0 elapsed=106.0s

  [733/13157] intraday_0733.csv.gz  in=159,312,419 out=0 elapsed=106.2s

  [734/13157] intraday_0734.csv.gz  in=159,445,206 out=0 elapsed=106.2s

  [735/13157] intraday_0736.csv.gz  in=159,565,824 out=0 elapsed=106.2s

  [736/13157] intraday_0735.csv.gz  in=159,729,226 out=0 elapsed=106.2s

  [737/13157] intraday_0738.csv.gz  in=159,848,715 out=0 elapsed=106.4s

  [738/13157] intraday_0737.csv.gz  in=159,994,738 out=0 elapsed=106.4s

  [739/13157] intraday_0739.csv.gz  in=160,108,715 out=0 elapsed=106.4s

  [740/13157] intraday_0740.csv.gz  in=160,251,867 out=0 elapsed=106.5s

  [741/13157] intraday_0741.csv.gz  in=160,398,732 out=0 elapsed=106.9s

  [742/13157] intraday_0742.csv.gz  in=160,541,414 out=0 elapsed=106.9s

  [743/13157] intraday_0743.csv.gz  in=160,694,567 out=0 elapsed=106.9s

  [744/13157] intraday_0744.csv.gz  in=160,847,878 out=0 elapsed=106.9s

  [745/13157] intraday_0747.csv.gz  in=160,988,581 out=0 elapsed=108.1s

  [746/13157] intraday_0748.csv.gz  in=161,127,084 out=0 elapsed=108.1s

  [747/13157] intraday_0746.csv.gz  in=161,260,817 out=0 elapsed=108.1s

  [748/13157] intraday_0745.csv.gz  in=161,413,941 out=0 elapsed=108.1s

  [749/13157] intraday_0749.csv.gz  in=161,530,783 out=0 elapsed=108.7s

  [750/13157] intraday_0751.csv.gz  in=161,642,263 out=0 elapsed=108.7s

  [751/13157] intraday_0750.csv.gz  in=161,769,784 out=0 elapsed=108.8s

  [752/13157] intraday_0752.csv.gz  in=161,904,477 out=0 elapsed=108.8s

  [753/13157] intraday_0753.csv.gz  in=162,036,013 out=0 elapsed=109.2s

  [754/13157] intraday_0756.csv.gz  in=162,141,237 out=0 elapsed=109.3s

  [755/13157] intraday_0754.csv.gz  in=162,278,315 out=0 elapsed=109.4s

  [756/13157] intraday_0755.csv.gz  in=162,402,013 out=0 elapsed=109.4s

  [757/13157] intraday_0757.csv.gz  in=162,533,048 out=0 elapsed=109.6s

  [758/13157] intraday_0760.csv.gz  in=162,666,525 out=0 elapsed=109.7s

  [759/13157] intraday_0759.csv.gz  in=162,825,403 out=0 elapsed=109.7s

  [760/13157] intraday_0758.csv.gz  in=162,999,521 out=0 elapsed=109.7s

  [761/13157] intraday_0761.csv.gz  in=163,114,446 out=0 elapsed=109.8s

  [762/13157] intraday_0762.csv.gz  in=163,249,987 out=0 elapsed=109.9s

  [763/13157] intraday_0763.csv.gz  in=163,397,708 out=0 elapsed=110.0s

  [764/13157] intraday_0765.csv.gz  in=163,533,935 out=0 elapsed=110.0s

  [765/13157] intraday_0764.csv.gz  in=163,688,782 out=0 elapsed=110.1s

  [766/13157] intraday_0766.csv.gz  in=163,846,217 out=0 elapsed=110.1s

  [767/13157] intraday_0767.csv.gz  in=163,993,651 out=0 elapsed=110.2s

  [768/13157] intraday_0768.csv.gz  in=164,150,804 out=0 elapsed=110.6s

  [769/13157] intraday_0769.csv.gz  in=164,303,234 out=0 elapsed=111.0s

  [770/13157] intraday_0770.csv.gz  in=164,436,536 out=0 elapsed=111.0s

  [771/13157] intraday_0771.csv.gz  in=164,570,092 out=0 elapsed=111.1s

  [772/13157] intraday_0772.csv.gz  in=164,716,922 out=0 elapsed=111.7s

  [773/13157] intraday_0773.csv.gz  in=164,847,419 out=0 elapsed=111.9s

  [774/13157] intraday_0775.csv.gz  in=164,977,612 out=0 elapsed=112.1s

  [775/13157] intraday_0774.csv.gz  in=165,118,612 out=0 elapsed=112.1s

  [776/13157] intraday_0776.csv.gz  in=165,285,102 out=0 elapsed=112.3s

  [777/13157] intraday_0777.csv.gz  in=165,422,237 out=0 elapsed=112.3s

  [778/13157] intraday_0778.csv.gz  in=165,571,124 out=0 elapsed=112.5s

  [779/13157] intraday_0779.csv.gz  in=165,730,454 out=0 elapsed=112.5s

  [780/13157] intraday_0781.csv.gz  in=165,867,162 out=0 elapsed=112.5s

  [781/13157] intraday_0780.csv.gz  in=165,998,218 out=0 elapsed=112.5s

  [782/13157] intraday_0785.csv.gz  in=166,131,097 out=0 elapsed=112.9s

  [783/13157] intraday_0784.csv.gz  in=166,270,174 out=0 elapsed=113.0s

  [784/13157] intraday_0783.csv.gz  in=166,426,924 out=0 elapsed=113.0s

  [785/13157] intraday_0782.csv.gz  in=166,594,735 out=0 elapsed=113.0s

  [786/13157] intraday_0786.csv.gz  in=166,733,614 out=0 elapsed=113.1s

  [787/13157] intraday_0789.csv.gz  in=166,797,967 out=0 elapsed=113.1s

  [788/13157] intraday_0787.csv.gz  in=166,929,889 out=0 elapsed=113.2s

  [789/13157] intraday_0788.csv.gz  in=167,078,657 out=0 elapsed=113.2s

  [790/13157] intraday_0792.csv.gz  in=167,244,296 out=0 elapsed=113.4s

  [791/13157] intraday_0790.csv.gz  in=167,410,412 out=0 elapsed=113.4s

  [792/13157] intraday_0791.csv.gz  in=167,571,437 out=0 elapsed=113.4s

  [793/13157] intraday_0793.csv.gz  in=167,710,769 out=0 elapsed=113.4s

  [794/13157] intraday_0795.csv.gz  in=167,843,169 out=0 elapsed=113.7s

  [795/13157] intraday_0796.csv.gz  in=167,967,788 out=0 elapsed=113.7s

  [796/13157] intraday_0794.csv.gz  in=168,118,552 out=0 elapsed=113.7s

  [797/13157] intraday_0797.csv.gz  in=168,273,090 out=0 elapsed=113.7s

  [798/13157] intraday_0798.csv.gz  in=168,419,998 out=0 elapsed=113.9s

  [799/13157] intraday_0800.csv.gz  in=168,564,380 out=0 elapsed=114.0s

  [800/13157] intraday_0799.csv.gz  in=168,732,695 out=0 elapsed=114.0s

  [801/13157] intraday_0801.csv.gz  in=168,875,476 out=0 elapsed=114.0s

  [802/13157] intraday_0802.csv.gz  in=169,018,762 out=0 elapsed=114.2s

  [803/13157] intraday_0804.csv.gz  in=169,159,481 out=0 elapsed=114.2s

  [804/13157] intraday_0803.csv.gz  in=169,326,594 out=0 elapsed=114.3s

  [805/13157] intraday_0805.csv.gz  in=169,500,098 out=0 elapsed=114.3s

  [806/13157] intraday_0806.csv.gz  in=169,648,754 out=0 elapsed=114.4s

  [807/13157] intraday_0807.csv.gz  in=169,786,706 out=0 elapsed=114.5s

  [808/13157] intraday_0809.csv.gz  in=169,913,759 out=0 elapsed=114.9s

  [809/13157] intraday_0808.csv.gz  in=170,069,026 out=0 elapsed=114.9s

  [810/13157] intraday_0810.csv.gz  in=170,199,485 out=0 elapsed=114.9s

  [811/13157] intraday_0811.csv.gz  in=170,333,352 out=0 elapsed=114.9s

  [812/13157] intraday_0813.csv.gz  in=170,436,393 out=0 elapsed=115.1s

  [813/13157] intraday_0812.csv.gz  in=170,569,218 out=0 elapsed=115.1s

  [814/13157] intraday_0817.csv.gz  in=170,583,417 out=0 elapsed=115.1s

  [815/13157] intraday_0816.csv.gz  in=170,622,032 out=0 elapsed=115.1s

  [816/13157] intraday_0814.csv.gz  in=170,719,341 out=0 elapsed=115.1s

  [817/13157] intraday_0818.csv.gz  in=170,733,336 out=0 elapsed=115.2s

  [818/13157] intraday_0819.csv.gz  in=170,745,538 out=0 elapsed=115.2s

  [819/13157] intraday_0815.csv.gz  in=170,856,718 out=0 elapsed=115.2s

  [820/13157] intraday_0820.csv.gz  in=170,873,117 out=0 elapsed=115.2s

  [821/13157] intraday_0823.csv.gz  in=170,883,933 out=0 elapsed=115.2s

  [822/13157] intraday_0822.csv.gz  in=170,897,980 out=0 elapsed=115.2s

  [823/13157] intraday_0821.csv.gz  in=170,912,904 out=0 elapsed=115.2s

  [824/13157] intraday_0824.csv.gz  in=170,934,292 out=0 elapsed=115.2s

  [825/13157] intraday_0827.csv.gz  in=170,943,913 out=0 elapsed=115.3s

  [826/13157] intraday_0826.csv.gz  in=170,957,300 out=0 elapsed=115.3s

  [827/13157] intraday_0825.csv.gz  in=170,974,625 out=0 elapsed=115.3s

  [828/13157] intraday_0828.csv.gz  in=171,001,614 out=0 elapsed=115.3s

  [829/13157] intraday_0830.csv.gz  in=171,011,768 out=0 elapsed=115.3s

  [830/13157] intraday_0831.csv.gz  in=171,021,291 out=0 elapsed=115.3s

  [831/13157] intraday_0829.csv.gz  in=171,034,647 out=0 elapsed=115.3s

  [832/13157] intraday_0832.csv.gz  in=171,048,427 out=0 elapsed=115.3s

  [833/13157] intraday_0834.csv.gz  in=171,061,254 out=0 elapsed=115.4s

  [834/13157] intraday_0835.csv.gz  in=171,072,575 out=0 elapsed=115.4s

  [835/13157] intraday_0833.csv.gz  in=171,085,053 out=0 elapsed=115.4s

  [836/13157] intraday_0836.csv.gz  in=171,100,482 out=0 elapsed=115.4s

  [837/13157] intraday_0839.csv.gz  in=171,112,343 out=0 elapsed=115.4s

  [838/13157] intraday_0838.csv.gz  in=171,125,452 out=0 elapsed=115.4s

  [839/13157] intraday_0840.csv.gz  in=171,138,152 out=0 elapsed=115.4s

  [840/13157] intraday_0837.csv.gz  in=171,150,913 out=0 elapsed=115.4s

  [841/13157] intraday_0842.csv.gz  in=171,161,481 out=0 elapsed=115.5s

  [842/13157] intraday_0843.csv.gz  in=171,173,749 out=0 elapsed=115.5s

  [843/13157] intraday_0844.csv.gz  in=171,187,349 out=0 elapsed=115.5s

  [844/13157] intraday_0841.csv.gz  in=171,207,678 out=0 elapsed=115.5s

  [845/13157] intraday_0848.csv.gz  in=171,220,822 out=0 elapsed=115.6s

  [846/13157] intraday_0847.csv.gz  in=171,233,156 out=0 elapsed=115.6s

  [847/13157] intraday_0846.csv.gz  in=171,247,417 out=0 elapsed=115.6s

  [848/13157] intraday_0845.csv.gz  in=171,262,538 out=0 elapsed=115.6s

  [849/13157] intraday_0850.csv.gz  in=171,275,169 out=0 elapsed=115.6s

  [850/13157] intraday_0851.csv.gz  in=171,286,737 out=0 elapsed=115.6s

  [851/13157] intraday_0849.csv.gz  in=171,299,233 out=0 elapsed=115.6s

  [852/13157] intraday_0852.csv.gz  in=171,321,977 out=0 elapsed=115.6s

  [853/13157] intraday_0854.csv.gz  in=171,333,049 out=0 elapsed=115.7s

  [854/13157] intraday_0853.csv.gz  in=171,344,863 out=0 elapsed=115.7s

  [855/13157] intraday_0856.csv.gz  in=171,357,530 out=0 elapsed=115.7s

  [856/13157] intraday_0855.csv.gz  in=171,379,672 out=0 elapsed=115.7s

  [857/13157] intraday_0857.csv.gz  in=171,392,578 out=0 elapsed=115.8s

  [858/13157] intraday_0858.csv.gz  in=171,405,058 out=0 elapsed=115.8s

  [859/13157] intraday_0859.csv.gz  in=171,419,692 out=0 elapsed=115.8s

  [860/13157] intraday_0860.csv.gz  in=171,431,803 out=0 elapsed=115.8s

  [861/13157] intraday_0861.csv.gz  in=171,443,753 out=0 elapsed=115.9s

  [862/13157] intraday_0864.csv.gz  in=171,457,548 out=0 elapsed=116.0s

  [863/13157] intraday_0863.csv.gz  in=171,469,951 out=0 elapsed=116.0s

  [864/13157] intraday_0862.csv.gz  in=171,482,017 out=0 elapsed=116.0s

  [865/13157] intraday_0866.csv.gz  in=171,493,692 out=0 elapsed=116.0s

  [866/13157] intraday_0867.csv.gz  in=171,509,075 out=0 elapsed=116.0s

  [867/13157] intraday_0868.csv.gz  in=171,518,757 out=0 elapsed=116.0s

  [868/13157] intraday_0865.csv.gz  in=171,535,560 out=0 elapsed=116.0s

  [869/13157] intraday_0871.csv.gz  in=171,546,311 out=0 elapsed=116.1s

  [870/13157] intraday_0869.csv.gz  in=171,559,111 out=0 elapsed=116.1s

  [871/13157] intraday_0870.csv.gz  in=171,570,872 out=0 elapsed=116.1s

  [872/13157] intraday_0872.csv.gz  in=171,582,750 out=0 elapsed=116.1s

  [873/13157] intraday_0873.csv.gz  in=171,595,221 out=0 elapsed=116.1s

  [874/13157] intraday_0874.csv.gz  in=171,608,084 out=0 elapsed=116.2s

  [875/13157] intraday_0876.csv.gz  in=171,618,708 out=0 elapsed=116.2s

  [876/13157] intraday_0875.csv.gz  in=171,630,652 out=0 elapsed=116.2s

  [877/13157] intraday_0877.csv.gz  in=171,640,867 out=0 elapsed=116.2s

  [878/13157] intraday_0879.csv.gz  in=171,653,906 out=0 elapsed=116.3s

  [879/13157] intraday_0878.csv.gz  in=171,664,546 out=0 elapsed=116.3s

  [880/13157] intraday_0880.csv.gz  in=171,677,195 out=0 elapsed=116.3s

  [881/13157] intraday_0881.csv.gz  in=171,692,003 out=0 elapsed=116.3s

  [882/13157] intraday_0884.csv.gz  in=171,702,657 out=0 elapsed=116.5s

  [883/13157] intraday_0885.csv.gz  in=171,714,906 out=0 elapsed=116.5s

  [884/13157] intraday_0882.csv.gz  in=171,728,332 out=0 elapsed=116.5s

  [885/13157] intraday_0883.csv.gz  in=171,739,848 out=0 elapsed=116.5s

  [886/13157] intraday_0886.csv.gz  in=171,751,580 out=0 elapsed=116.7s

  [887/13157] intraday_0889.csv.gz  in=171,763,321 out=0 elapsed=116.7s

  [888/13157] intraday_0887.csv.gz  in=171,776,207 out=0 elapsed=116.7s

  [889/13157] intraday_0888.csv.gz  in=171,788,961 out=0 elapsed=116.7s

  [890/13157] intraday_0890.csv.gz  in=171,800,237 out=0 elapsed=116.8s

  [891/13157] intraday_0891.csv.gz  in=171,812,341 out=0 elapsed=116.8s

  [892/13157] intraday_0892.csv.gz  in=171,823,805 out=0 elapsed=116.8s

  [893/13157] intraday_0893.csv.gz  in=171,834,942 out=0 elapsed=116.8s

  [894/13157] intraday_0895.csv.gz  in=171,845,734 out=0 elapsed=116.8s

  [895/13157] intraday_0896.csv.gz  in=171,856,866 out=0 elapsed=116.8s

  [896/13157] intraday_0894.csv.gz  in=171,866,627 out=0 elapsed=116.8s

  [897/13157] intraday_0898.csv.gz  in=171,879,586 out=0 elapsed=116.9s

  [898/13157] intraday_0897.csv.gz  in=171,895,642 out=0 elapsed=116.9s

  [899/13157] intraday_0899.csv.gz  in=171,906,820 out=0 elapsed=116.9s

  [900/13157] intraday_0900.csv.gz  in=171,918,523 out=0 elapsed=116.9s

  [901/13157] intraday_0902.csv.gz  in=171,931,127 out=0 elapsed=117.0s

  [902/13157] intraday_0904.csv.gz  in=171,943,568 out=0 elapsed=117.0s

  [903/13157] intraday_0901.csv.gz  in=171,956,075 out=0 elapsed=117.0s

  [904/13157] intraday_0903.csv.gz  in=171,970,669 out=0 elapsed=117.0s

  [905/13157] intraday_0907.csv.gz  in=171,983,062 out=0 elapsed=117.1s

  [906/13157] intraday_0906.csv.gz  in=171,997,395 out=0 elapsed=117.1s

  [907/13157] intraday_0908.csv.gz  in=172,010,626 out=0 elapsed=117.1s

  [908/13157] intraday_0905.csv.gz  in=172,025,210 out=0 elapsed=117.1s

  [909/13157] intraday_0909.csv.gz  in=172,037,663 out=0 elapsed=117.1s

  [910/13157] intraday_0910.csv.gz  in=172,050,205 out=0 elapsed=117.1s

  [911/13157] intraday_0911.csv.gz  in=172,062,369 out=0 elapsed=117.1s

  [912/13157] intraday_0912.csv.gz  in=172,074,088 out=0 elapsed=117.1s

  [913/13157] intraday_0913.csv.gz  in=172,087,236 out=0 elapsed=117.1s

  [914/13157] intraday_0914.csv.gz  in=172,098,538 out=0 elapsed=117.1s

  [915/13157] intraday_0916.csv.gz  in=172,109,680 out=0 elapsed=117.2s

  [916/13157] intraday_0917.csv.gz  in=172,122,186 out=0 elapsed=117.2s

  [917/13157] intraday_0915.csv.gz  in=172,134,361 out=0 elapsed=117.2s

  [918/13157] intraday_0919.csv.gz  in=172,145,932 out=0 elapsed=117.2s

  [919/13157] intraday_0918.csv.gz  in=172,158,436 out=0 elapsed=117.2s

  [920/13157] intraday_0921.csv.gz  in=172,172,848 out=0 elapsed=117.2s

  [921/13157] intraday_0920.csv.gz  in=172,185,852 out=0 elapsed=117.2s

  [922/13157] intraday_0922.csv.gz  in=172,198,803 out=0 elapsed=117.2s

  [923/13157] intraday_0923.csv.gz  in=172,209,928 out=0 elapsed=117.3s

  [924/13157] intraday_0925.csv.gz  in=172,223,913 out=0 elapsed=117.3s

  [925/13157] intraday_0924.csv.gz  in=172,236,557 out=0 elapsed=117.3s

  [926/13157] intraday_0929.csv.gz  in=172,250,293 out=0 elapsed=117.3s

  [927/13157] intraday_0927.csv.gz  in=172,262,285 out=0 elapsed=117.3s

  [928/13157] intraday_0928.csv.gz  in=172,275,944 out=0 elapsed=117.3s

  [929/13157] intraday_0926.csv.gz  in=172,288,263 out=0 elapsed=117.3s

  [930/13157] intraday_0930.csv.gz  in=172,300,820 out=0 elapsed=117.3s

  [931/13157] intraday_0931.csv.gz  in=172,314,019 out=0 elapsed=117.4s

  [932/13157] intraday_0932.csv.gz  in=172,327,186 out=0 elapsed=117.4s

  [933/13157] intraday_0933.csv.gz  in=172,337,937 out=0 elapsed=117.4s

  [934/13157] intraday_0934.csv.gz  in=172,348,617 out=0 elapsed=117.4s

  [935/13157] intraday_0936.csv.gz  in=172,361,570 out=0 elapsed=117.4s

  [936/13157] intraday_0935.csv.gz  in=172,375,984 out=0 elapsed=117.4s

  [937/13157] intraday_0937.csv.gz  in=172,391,434 out=0 elapsed=117.4s

  [938/13157] intraday_0938.csv.gz  in=172,403,487 out=0 elapsed=117.4s

  [939/13157] intraday_0940.csv.gz  in=172,415,056 out=0 elapsed=117.4s

  [940/13157] intraday_0939.csv.gz  in=172,428,760 out=0 elapsed=117.4s

  [941/13157] intraday_0941.csv.gz  in=172,441,679 out=0 elapsed=117.5s

  [942/13157] intraday_0942.csv.gz  in=172,456,071 out=0 elapsed=117.5s

  [943/13157] intraday_0943.csv.gz  in=172,477,337 out=0 elapsed=117.5s

  [944/13157] intraday_0944.csv.gz  in=172,491,366 out=0 elapsed=117.5s

  [945/13157] intraday_0946.csv.gz  in=172,505,217 out=0 elapsed=117.7s

  [946/13157] intraday_0945.csv.gz  in=172,517,214 out=0 elapsed=117.7s

  [947/13157] intraday_0948.csv.gz  in=172,529,163 out=0 elapsed=117.7s

  [948/13157] intraday_0947.csv.gz  in=172,539,630 out=0 elapsed=117.7s

  [949/13157] intraday_0950.csv.gz  in=172,551,496 out=0 elapsed=117.8s

  [950/13157] intraday_0952.csv.gz  in=172,559,987 out=0 elapsed=117.8s

  [951/13157] intraday_0951.csv.gz  in=172,568,376 out=0 elapsed=117.8s

  [952/13157] intraday_0949.csv.gz  in=172,580,367 out=0 elapsed=117.8s

  [953/13157] intraday_0954.csv.gz  in=172,582,607 out=0 elapsed=118.0s

  [954/13157] intraday_0953.csv.gz  in=172,594,176 out=0 elapsed=118.0s

  [955/13157] intraday_0956.csv.gz  in=172,608,443 out=0 elapsed=118.0s

  [956/13157] intraday_0957.csv.gz  in=172,620,130 out=0 elapsed=118.0s

  [957/13157] intraday_0955.csv.gz  in=172,635,211 out=0 elapsed=118.0s

  [958/13157] intraday_0958.csv.gz  in=172,657,646 out=0 elapsed=118.1s

  [959/13157] intraday_0960.csv.gz  in=172,672,157 out=0 elapsed=118.1s

  [960/13157] intraday_0959.csv.gz  in=172,686,888 out=0 elapsed=118.1s

  [961/13157] intraday_0961.csv.gz  in=172,703,954 out=0 elapsed=118.1s

  [962/13157] intraday_0962.csv.gz  in=172,716,282 out=0 elapsed=118.2s

  [963/13157] intraday_0965.csv.gz  in=172,730,070 out=0 elapsed=118.3s

  [964/13157] intraday_0963.csv.gz  in=172,743,455 out=0 elapsed=118.3s

  [965/13157] intraday_0964.csv.gz  in=172,758,327 out=0 elapsed=118.3s

  [966/13157] intraday_0969.csv.gz  in=172,768,470 out=0 elapsed=118.4s

  [967/13157] intraday_0968.csv.gz  in=172,780,641 out=0 elapsed=118.5s

  [968/13157] intraday_0967.csv.gz  in=172,794,619 out=0 elapsed=118.5s

  [969/13157] intraday_0966.csv.gz  in=172,816,729 out=0 elapsed=118.5s

  [970/13157] intraday_0971.csv.gz  in=172,828,749 out=0 elapsed=118.5s

  [971/13157] intraday_0970.csv.gz  in=172,842,612 out=0 elapsed=118.5s

  [972/13157] intraday_0973.csv.gz  in=172,863,132 out=0 elapsed=118.6s

  [973/13157] intraday_0972.csv.gz  in=172,876,609 out=0 elapsed=118.6s

  [974/13157] intraday_0977.csv.gz  in=172,888,533 out=0 elapsed=118.6s

  [975/13157] intraday_0974.csv.gz  in=172,900,168 out=0 elapsed=118.6s

  [976/13157] intraday_0976.csv.gz  in=172,912,465 out=0 elapsed=118.6s

  [977/13157] intraday_0975.csv.gz  in=172,937,964 out=0 elapsed=118.6s

  [978/13157] intraday_0978.csv.gz  in=172,951,142 out=0 elapsed=118.6s

  [979/13157] intraday_0982.csv.gz  in=172,964,309 out=0 elapsed=118.7s

  [980/13157] intraday_0981.csv.gz  in=172,977,440 out=0 elapsed=118.7s

  [981/13157] intraday_0980.csv.gz  in=172,988,287 out=0 elapsed=118.7s

  [982/13157] intraday_0985.csv.gz  in=173,000,779 out=0 elapsed=118.9s

  [983/13157] intraday_0984.csv.gz  in=173,015,430 out=0 elapsed=118.9s

  [984/13157] intraday_0983.csv.gz  in=173,031,205 out=0 elapsed=118.9s

  [985/13157] intraday_0979.csv.gz  in=173,080,108 out=0 elapsed=118.9s

  [986/13157] intraday_0986.csv.gz  in=173,092,348 out=0 elapsed=118.9s

  [987/13157] intraday_0988.csv.gz  in=173,105,709 out=0 elapsed=119.0s

  [988/13157] intraday_0989.csv.gz  in=173,117,385 out=0 elapsed=119.1s

  [989/13157] intraday_0990.csv.gz  in=173,129,002 out=0 elapsed=119.1s

  [990/13157] intraday_0991.csv.gz  in=173,142,111 out=0 elapsed=119.1s

  [991/13157] intraday_0993.csv.gz  in=173,153,501 out=0 elapsed=119.1s

  [992/13157] intraday_0992.csv.gz  in=173,164,286 out=0 elapsed=119.1s

  [993/13157] intraday_0987.csv.gz  in=173,196,319 out=0 elapsed=119.2s

  [994/13157] intraday_0994.csv.gz  in=173,210,070 out=0 elapsed=119.2s

  [995/13157] intraday_0996.csv.gz  in=173,223,798 out=0 elapsed=119.2s

  [996/13157] intraday_0995.csv.gz  in=173,235,726 out=0 elapsed=119.2s

  [997/13157] intraday_0997.csv.gz  in=173,251,622 out=0 elapsed=119.2s

  [998/13157] intraday_0998.csv.gz  in=173,262,519 out=0 elapsed=119.2s

  [999/13157] intraday_0999.csv.gz  in=173,274,768 out=0 elapsed=119.3s

  [1000/13157] intraday_1000.csv.gz  in=173,287,073 out=0 elapsed=119.3s

  [1001/13157] intraday_10002.csv.gz  in=173,299,372 out=12,299 elapsed=119.9s

  [1002/13157] intraday_10003.csv.gz  in=173,312,279 out=25,206 elapsed=119.9s

  [1003/13157] intraday_10000.csv.gz  in=173,323,613 out=36,370 elapsed=119.9s

  [1004/13157] intraday_10001.csv.gz  in=173,337,308 out=50,065 elapsed=119.9s

  [1005/13157] intraday_10005.csv.gz  in=173,351,663 out=64,420 elapsed=120.2s

  [1006/13157] intraday_10007.csv.gz  in=173,367,034 out=79,791 elapsed=120.2s

  [1007/13157] intraday_10008.csv.gz  in=173,380,689 out=93,446 elapsed=120.2s

  [1008/13157] intraday_10006.csv.gz  in=173,399,791 out=112,548 elapsed=120.2s

  [1009/13157] intraday_10004.csv.gz  in=173,416,844 out=129,601 elapsed=120.2s

  [1010/13157] intraday_1001.csv.gz  in=173,432,337 out=129,601 elapsed=120.5s

  [1011/13157] intraday_10009.csv.gz  in=173,445,201 out=142,465 elapsed=120.5s

  [1012/13157] intraday_10011.csv.gz  in=173,455,724 out=152,988 elapsed=120.5s

  [1013/13157] intraday_10010.csv.gz  in=173,468,274 out=165,538 elapsed=120.5s

  [1014/13157] intraday_10012.csv.gz  in=173,481,818 out=179,082 elapsed=120.6s

  [1015/13157] intraday_10015.csv.gz  in=173,495,696 out=192,960 elapsed=120.6s

  [1016/13157] intraday_10013.csv.gz  in=173,506,135 out=203,399 elapsed=120.6s

  [1017/13157] intraday_10014.csv.gz  in=173,520,633 out=217,897 elapsed=120.6s

  [1018/13157] intraday_10019.csv.gz  in=173,533,883 out=231,147 elapsed=120.7s

  [1019/13157] intraday_10017.csv.gz  in=173,545,111 out=242,375 elapsed=120.7s

  [1020/13157] intraday_10018.csv.gz  in=173,555,993 out=253,257 elapsed=120.7s

  [1021/13157] intraday_10016.csv.gz  in=173,572,270 out=269,534 elapsed=120.7s

  [1022/13157] intraday_1002.csv.gz  in=173,584,284 out=269,534 elapsed=120.7s

  [1023/13157] intraday_10021.csv.gz  in=173,594,676 out=279,926 elapsed=120.8s

  [1024/13157] intraday_10020.csv.gz  in=173,606,839 out=292,089 elapsed=120.8s

  [1025/13157] intraday_10023.csv.gz  in=173,621,192 out=306,442 elapsed=120.8s

  [1026/13157] intraday_10022.csv.gz  in=173,636,830 out=322,080 elapsed=120.8s

  [1027/13157] intraday_10024.csv.gz  in=173,650,340 out=335,590 elapsed=120.8s

  [1028/13157] intraday_10027.csv.gz  in=173,661,578 out=346,828 elapsed=120.8s

  [1029/13157] intraday_10026.csv.gz  in=173,672,972 out=358,222 elapsed=120.9s

  [1030/13157] intraday_10025.csv.gz  in=173,689,424 out=374,674 elapsed=120.9s

  [1031/13157] intraday_10028.csv.gz  in=173,702,370 out=387,620 elapsed=120.9s

  [1032/13157] intraday_1003.csv.gz  in=173,713,444 out=387,620 elapsed=120.9s

  [1033/13157] intraday_10031.csv.gz  in=173,721,409 out=395,585 elapsed=120.9s

  [1034/13157] intraday_10030.csv.gz  in=173,734,444 out=408,620 elapsed=120.9s

  [1035/13157] intraday_10029.csv.gz  in=173,745,417 out=419,593 elapsed=120.9s

  [1036/13157] intraday_10032.csv.gz  in=173,756,598 out=430,774 elapsed=120.9s

  [1037/13157] intraday_10033.csv.gz  in=173,765,209 out=439,385 elapsed=121.0s

  [1038/13157] intraday_10035.csv.gz  in=173,776,918 out=451,094 elapsed=121.0s

  [1039/13157] intraday_10034.csv.gz  in=173,791,702 out=465,878 elapsed=121.0s

  [1040/13157] intraday_10036.csv.gz  in=173,803,469 out=477,645 elapsed=121.0s

  [1041/13157] intraday_10037.csv.gz  in=173,813,914 out=488,090 elapsed=121.0s

  [1042/13157] intraday_10038.csv.gz  in=173,825,913 out=500,089 elapsed=121.1s

  [1043/13157] intraday_10041.csv.gz  in=173,836,692 out=510,868 elapsed=121.1s

  [1044/13157] intraday_10039.csv.gz  in=173,851,825 out=526,001 elapsed=121.1s

  [1045/13157] intraday_10040.csv.gz  in=173,866,795 out=540,971 elapsed=121.1s

  [1046/13157] intraday_1004.csv.gz  in=173,880,973 out=540,971 elapsed=121.1s

  [1047/13157] intraday_10045.csv.gz  in=173,892,963 out=552,961 elapsed=121.2s

  [1048/13157] intraday_10043.csv.gz  in=173,907,528 out=567,526 elapsed=121.2s

  [1049/13157] intraday_10044.csv.gz  in=173,920,558 out=580,556 elapsed=121.2s

  [1050/13157] intraday_10042.csv.gz  in=173,934,968 out=594,923 elapsed=121.2s

  [1051/13157] intraday_10046.csv.gz  in=173,948,577 out=608,532 elapsed=121.2s

  [1052/13157] intraday_1005.csv.gz  in=173,960,708 out=608,532 elapsed=121.2s

  [1053/13157] intraday_10048.csv.gz  in=173,971,133 out=618,957 elapsed=121.3s

  [1054/13157] intraday_10049.csv.gz  in=173,982,722 out=630,546 elapsed=121.3s

  [1055/13157] intraday_10047.csv.gz  in=173,996,009 out=643,833 elapsed=121.3s

  [1056/13157] intraday_10050.csv.gz  in=174,007,014 out=654,838 elapsed=121.3s

  [1057/13157] intraday_10052.csv.gz  in=174,017,897 out=665,721 elapsed=121.3s

  [1058/13157] intraday_10053.csv.gz  in=174,028,703 out=676,527 elapsed=121.3s

  [1059/13157] intraday_10051.csv.gz  in=174,044,240 out=692,064 elapsed=121.3s

  [1060/13157] intraday_10054.csv.gz  in=174,056,999 out=704,823 elapsed=121.4s

  [1061/13157] intraday_10055.csv.gz  in=174,070,268 out=718,092 elapsed=121.4s

  [1062/13157] intraday_10056.csv.gz  in=174,084,047 out=731,871 elapsed=121.4s

  [1063/13157] intraday_10057.csv.gz  in=174,096,010 out=743,834 elapsed=121.4s

  [1064/13157] intraday_1006.csv.gz  in=174,107,603 out=743,834 elapsed=121.4s

  [1065/13157] intraday_10058.csv.gz  in=174,121,727 out=757,958 elapsed=121.4s

  [1066/13157] intraday_10059.csv.gz  in=174,135,744 out=771,620 elapsed=121.4s

  [1067/13157] intraday_10060.csv.gz  in=174,147,864 out=783,740 elapsed=121.4s

  [1068/13157] intraday_10061.csv.gz  in=174,159,004 out=794,880 elapsed=121.5s

  [1069/13157] intraday_10062.csv.gz  in=174,169,216 out=805,092 elapsed=121.5s

  [1070/13157] intraday_10063.csv.gz  in=174,182,840 out=818,716 elapsed=121.5s

  [1071/13157] intraday_10065.csv.gz  in=174,197,597 out=833,473 elapsed=121.5s

  [1072/13157] intraday_10064.csv.gz  in=174,211,545 out=847,421 elapsed=121.5s

  [1073/13157] intraday_10067.csv.gz  in=174,222,754 out=858,630 elapsed=121.6s

  [1074/13157] intraday_10068.csv.gz  in=174,234,506 out=870,382 elapsed=121.6s

  [1075/13157] intraday_10069.csv.gz  in=174,248,438 out=884,314 elapsed=121.6s

  [1076/13157] intraday_10066.csv.gz  in=174,265,819 out=900,462 elapsed=121.6s

  [1077/13157] intraday_1007.csv.gz  in=174,277,560 out=900,462 elapsed=121.6s

  [1078/13157] intraday_10070.csv.gz  in=174,288,874 out=911,776 elapsed=121.7s

  [1079/13157] intraday_10071.csv.gz  in=174,302,221 out=925,123 elapsed=121.7s

  [1080/13157] intraday_10072.csv.gz  in=174,313,102 out=936,004 elapsed=121.7s

  [1081/13157] intraday_10073.csv.gz  in=174,325,425 out=948,327 elapsed=121.7s

  [1082/13157] intraday_10074.csv.gz  in=174,337,182 out=960,084 elapsed=121.8s

  [1083/13157] intraday_10075.csv.gz  in=174,349,131 out=972,033 elapsed=122.0s

  [1084/13157] intraday_10077.csv.gz  in=174,361,644 out=984,546 elapsed=122.0s

  [1085/13157] intraday_10076.csv.gz  in=174,374,462 out=997,364 elapsed=122.0s

  [1086/13157] intraday_10078.csv.gz  in=174,386,686 out=1,009,588 elapsed=122.0s

  [1087/13157] intraday_1008.csv.gz  in=174,399,270 out=1,009,588 elapsed=122.2s

  [1088/13157] intraday_10080.csv.gz  in=174,411,024 out=1,021,342 elapsed=122.2s

  [1089/13157] intraday_10079.csv.gz  in=174,424,526 out=1,034,844 elapsed=122.2s

  [1090/13157] intraday_10081.csv.gz  in=174,435,760 out=1,046,078 elapsed=122.2s

  [1091/13157] intraday_10082.csv.gz  in=174,448,352 out=1,058,670 elapsed=122.3s

  [1092/13157] intraday_10083.csv.gz  in=174,459,564 out=1,069,882 elapsed=122.3s

  [1093/13157] intraday_10084.csv.gz  in=174,470,737 out=1,081,055 elapsed=122.3s

  [1094/13157] intraday_10085.csv.gz  in=174,482,074 out=1,092,392 elapsed=122.3s

  [1095/13157] intraday_10086.csv.gz  in=174,495,205 out=1,105,360 elapsed=122.4s

  [1096/13157] intraday_10087.csv.gz  in=174,507,203 out=1,117,309 elapsed=122.4s

  [1097/13157] intraday_10089.csv.gz  in=174,518,956 out=1,129,062 elapsed=122.4s

  [1098/13157] intraday_1009.csv.gz  in=174,531,443 out=1,129,062 elapsed=122.4s

  [1099/13157] intraday_10088.csv.gz  in=174,548,204 out=1,145,823 elapsed=122.4s

  [1100/13157] intraday_10090.csv.gz  in=174,560,505 out=1,158,124 elapsed=122.4s

  [1101/13157] intraday_10092.csv.gz  in=174,572,076 out=1,169,695 elapsed=122.4s

  [1102/13157] intraday_10091.csv.gz  in=174,591,151 out=1,187,716 elapsed=122.5s

  [1103/13157] intraday_10093.csv.gz  in=174,602,807 out=1,199,372 elapsed=122.5s

  [1104/13157] intraday_10094.csv.gz  in=174,615,731 out=1,212,296 elapsed=122.5s

  [1105/13157] intraday_10095.csv.gz  in=174,627,995 out=1,224,560 elapsed=122.5s

  [1106/13157] intraday_10098.csv.gz  in=174,639,716 out=1,236,281 elapsed=122.5s

  [1107/13157] intraday_10099.csv.gz  in=174,650,100 out=1,246,665 elapsed=122.5s

  [1108/13157] intraday_10096.csv.gz  in=174,662,097 out=1,258,662 elapsed=122.5s

  [1109/13157] intraday_10097.csv.gz  in=174,674,900 out=1,271,465 elapsed=122.5s

  [1110/13157] intraday_1010.csv.gz  in=174,686,259 out=1,271,465 elapsed=122.5s

  [1111/13157] intraday_10100.csv.gz  in=174,701,061 out=1,286,267 elapsed=122.6s

  [1112/13157] intraday_10102.csv.gz  in=174,715,299 out=1,300,505 elapsed=122.7s

  [1113/13157] intraday_10101.csv.gz  in=174,727,209 out=1,312,415 elapsed=122.7s

  [1114/13157] intraday_10103.csv.gz  in=174,744,186 out=1,329,015 elapsed=122.7s

  [1115/13157] intraday_10104.csv.gz  in=174,757,104 out=1,341,933 elapsed=122.7s

  [1116/13157] intraday_10105.csv.gz  in=174,766,605 out=1,351,434 elapsed=122.7s

  [1117/13157] intraday_10106.csv.gz  in=174,779,150 out=1,363,979 elapsed=122.7s

  [1118/13157] intraday_10107.csv.gz  in=174,791,625 out=1,376,454 elapsed=122.8s

  [1119/13157] intraday_1011.csv.gz  in=174,805,640 out=1,376,454 elapsed=122.9s

  [1120/13157] intraday_10108.csv.gz  in=174,819,377 out=1,390,191 elapsed=122.9s

  [1121/13157] intraday_10111.csv.gz  in=174,829,908 out=1,400,722 elapsed=122.9s

  [1122/13157] intraday_10109.csv.gz  in=174,843,441 out=1,414,255 elapsed=122.9s

  [1123/13157] intraday_10110.csv.gz  in=174,856,747 out=1,427,561 elapsed=122.9s

  [1124/13157] intraday_10112.csv.gz  in=174,869,634 out=1,440,448 elapsed=122.9s

  [1125/13157] intraday_10113.csv.gz  in=174,880,777 out=1,451,591 elapsed=123.0s

  [1126/13157] intraday_10116.csv.gz  in=174,890,197 out=1,461,011 elapsed=123.0s

  [1127/13157] intraday_10114.csv.gz  in=174,902,129 out=1,472,943 elapsed=123.0s

  [1128/13157] intraday_10117.csv.gz  in=174,913,166 out=1,483,980 elapsed=123.0s

  [1129/13157] intraday_10115.csv.gz  in=174,924,577 out=1,495,391 elapsed=123.0s

  [1130/13157] intraday_10118.csv.gz  in=174,937,686 out=1,508,500 elapsed=123.3s

  [1131/13157] intraday_1012.csv.gz  in=174,950,266 out=1,508,500 elapsed=123.3s

  [1132/13157] intraday_10120.csv.gz  in=174,963,367 out=1,521,601 elapsed=123.3s

  [1133/13157] intraday_10119.csv.gz  in=174,980,833 out=1,539,067 elapsed=123.3s

  [1134/13157] intraday_10121.csv.gz  in=174,993,414 out=1,551,648 elapsed=123.4s

  [1135/13157] intraday_10124.csv.gz  in=175,005,537 out=1,563,771 elapsed=123.5s

  [1136/13157] intraday_10122.csv.gz  in=175,020,314 out=1,578,048 elapsed=123.5s

  [1137/13157] intraday_10123.csv.gz  in=175,035,241 out=1,592,975 elapsed=123.5s

  [1138/13157] intraday_10125.csv.gz  in=175,050,846 out=1,608,580 elapsed=123.5s

  [1139/13157] intraday_10126.csv.gz  in=175,061,503 out=1,619,237 elapsed=123.5s

  [1140/13157] intraday_10127.csv.gz  in=175,073,360 out=1,631,094 elapsed=123.5s

  [1141/13157] intraday_10128.csv.gz  in=175,086,727 out=1,644,461 elapsed=123.5s

  [1142/13157] intraday_1013.csv.gz  in=175,098,511 out=1,644,461 elapsed=123.7s

  [1143/13157] intraday_10129.csv.gz  in=175,111,971 out=1,657,921 elapsed=123.7s

  [1144/13157] intraday_10130.csv.gz  in=175,124,483 out=1,670,433 elapsed=123.7s

  [1145/13157] intraday_10131.csv.gz  in=175,136,810 out=1,682,760 elapsed=123.7s

  [1146/13157] intraday_10133.csv.gz  in=175,149,040 out=1,694,990 elapsed=123.8s

  [1147/13157] intraday_10132.csv.gz  in=175,161,959 out=1,707,909 elapsed=123.8s

  [1148/13157] intraday_10134.csv.gz  in=175,174,754 out=1,720,704 elapsed=123.8s

  [1149/13157] intraday_10135.csv.gz  in=175,187,272 out=1,733,222 elapsed=123.8s

  [1150/13157] intraday_10136.csv.gz  in=175,198,152 out=1,744,102 elapsed=123.8s

  [1151/13157] intraday_10138.csv.gz  in=175,211,869 out=1,757,819 elapsed=123.9s

  [1152/13157] intraday_10139.csv.gz  in=175,225,840 out=1,771,790 elapsed=123.9s

  [1153/13157] intraday_10137.csv.gz  in=175,238,312 out=1,784,262 elapsed=123.9s

  [1154/13157] intraday_1014.csv.gz  in=175,250,734 out=1,784,262 elapsed=123.9s

  [1155/13157] intraday_10140.csv.gz  in=175,263,520 out=1,797,048 elapsed=123.9s

  [1156/13157] intraday_10141.csv.gz  in=175,274,722 out=1,808,250 elapsed=124.0s

  [1157/13157] intraday_10142.csv.gz  in=175,289,424 out=1,822,952 elapsed=124.0s

  [1158/13157] intraday_10143.csv.gz  in=175,302,143 out=1,835,671 elapsed=124.0s

  [1159/13157] intraday_10144.csv.gz  in=175,304,744 out=1,838,272 elapsed=124.0s

  [1160/13157] intraday_10148.csv.gz  in=175,372,740 out=1,906,268 elapsed=124.3s

  [1161/13157] intraday_10146.csv.gz  in=175,452,998 out=1,986,526 elapsed=124.3s

  [1162/13157] intraday_10147.csv.gz  in=175,543,695 out=2,077,223 elapsed=124.3s

  [1163/13157] intraday_10145.csv.gz  in=175,646,836 out=2,180,364 elapsed=124.3s

  [1164/13157] intraday_1015.csv.gz  in=175,658,448 out=2,180,364 elapsed=124.8s

  [1165/13157] intraday_10152.csv.gz  in=175,740,391 out=2,262,307 elapsed=125.1s

  [1166/13157] intraday_10149.csv.gz  in=175,824,633 out=2,346,549 elapsed=125.2s

  [1167/13157] intraday_10150.csv.gz  in=175,919,447 out=2,441,363 elapsed=125.2s

  [1168/13157] intraday_10151.csv.gz  in=176,024,115 out=2,546,031 elapsed=125.2s

  [1169/13157] intraday_10153.csv.gz  in=176,106,851 out=2,628,767 elapsed=125.4s

  [1170/13157] intraday_10156.csv.gz  in=176,183,637 out=2,705,553 elapsed=125.5s

  [1171/13157] intraday_10154.csv.gz  in=176,279,426 out=2,801,342 elapsed=125.5s

  [1172/13157] intraday_10155.csv.gz  in=176,368,566 out=2,890,482 elapsed=125.5s

  [1173/13157] intraday_10158.csv.gz  in=176,471,030 out=2,992,946 elapsed=125.6s

  [1174/13157] intraday_10157.csv.gz  in=176,578,528 out=3,100,444 elapsed=125.6s

  [1175/13157] intraday_1016.csv.gz  in=176,588,736 out=3,100,444 elapsed=125.7s

  [1176/13157] intraday_10159.csv.gz  in=176,668,116 out=3,179,824 elapsed=125.9s

  [1177/13157] intraday_10160.csv.gz  in=176,745,607 out=3,257,315 elapsed=125.9s

  [1178/13157] intraday_10161.csv.gz  in=176,836,371 out=3,348,079 elapsed=125.9s

  [1179/13157] intraday_10162.csv.gz  in=176,935,275 out=3,446,983 elapsed=126.0s

  [1180/13157] intraday_10163.csv.gz  in=177,018,870 out=3,530,578 elapsed=127.0s

  [1181/13157] intraday_10164.csv.gz  in=177,097,805 out=3,609,513 elapsed=127.0s

  [1182/13157] intraday_10165.csv.gz  in=177,173,337 out=3,685,045 elapsed=127.0s

  [1183/13157] intraday_10166.csv.gz  in=177,271,566 out=3,783,274 elapsed=127.0s

  [1184/13157] intraday_1017.csv.gz  in=177,285,786 out=3,783,274 elapsed=127.1s

  [1185/13157] intraday_10168.csv.gz  in=177,375,930 out=3,873,418 elapsed=127.4s

  [1186/13157] intraday_10169.csv.gz  in=177,467,442 out=3,964,930 elapsed=127.5s

  [1187/13157] intraday_10167.csv.gz  in=177,556,583 out=4,054,071 elapsed=127.5s

  [1188/13157] intraday_10170.csv.gz  in=177,640,495 out=4,137,983 elapsed=127.5s

  [1189/13157] intraday_10171.csv.gz  in=177,737,143 out=4,234,631 elapsed=127.5s

  [1190/13157] intraday_10173.csv.gz  in=177,806,754 out=4,304,242 elapsed=127.6s

  [1191/13157] intraday_10172.csv.gz  in=177,892,985 out=4,390,473 elapsed=127.6s

  [1192/13157] intraday_10174.csv.gz  in=177,987,050 out=4,484,538 elapsed=127.8s

  [1193/13157] intraday_10175.csv.gz  in=178,102,049 out=4,599,537 elapsed=127.8s

  [1194/13157] intraday_10177.csv.gz  in=178,175,405 out=4,672,893 elapsed=127.8s

  [1195/13157] intraday_10176.csv.gz  in=178,273,362 out=4,770,850 elapsed=127.8s

  [1196/13157] intraday_1018.csv.gz  in=178,284,746 out=4,770,850 elapsed=127.9s

  [1197/13157] intraday_10178.csv.gz  in=178,359,259 out=4,845,363 elapsed=128.2s

  [1198/13157] intraday_10180.csv.gz  in=178,446,581 out=4,932,685 elapsed=128.2s

  [1199/13157] intraday_10179.csv.gz  in=178,531,134 out=5,017,238 elapsed=128.3s

  [1200/13157] intraday_10181.csv.gz  in=178,609,433 out=5,095,537 elapsed=128.3s

  [1201/13157] intraday_10183.csv.gz  in=178,684,777 out=5,170,881 elapsed=128.4s

  [1202/13157] intraday_10182.csv.gz  in=178,782,131 out=5,268,235 elapsed=128.4s

  [1203/13157] intraday_10184.csv.gz  in=178,856,302 out=5,342,406 elapsed=128.4s

  [1204/13157] intraday_10185.csv.gz  in=178,941,200 out=5,427,304 elapsed=128.5s

  [1205/13157] intraday_10186.csv.gz  in=179,030,280 out=5,516,384 elapsed=128.6s

  [1206/13157] intraday_10187.csv.gz  in=179,118,921 out=5,605,025 elapsed=128.6s

  [1207/13157] intraday_10188.csv.gz  in=179,201,195 out=5,687,299 elapsed=128.6s

  [1208/13157] intraday_1019.csv.gz  in=179,215,109 out=5,687,299 elapsed=128.9s

  [1209/13157] intraday_10190.csv.gz  in=179,313,214 out=5,785,404 elapsed=129.3s

  [1210/13157] intraday_10189.csv.gz  in=179,404,199 out=5,876,389 elapsed=129.3s

  [1211/13157] intraday_10192.csv.gz  in=179,485,785 out=5,957,975 elapsed=129.3s

  [1212/13157] intraday_10191.csv.gz  in=179,558,761 out=6,030,951 elapsed=129.3s

  [1213/13157] intraday_10194.csv.gz  in=179,631,331 out=6,103,521 elapsed=129.5s

  [1214/13157] intraday_10196.csv.gz  in=179,707,573 out=6,179,763 elapsed=129.6s

  [1215/13157] intraday_10195.csv.gz  in=179,790,487 out=6,262,677 elapsed=129.6s

  [1216/13157] intraday_10193.csv.gz  in=179,873,334 out=6,345,524 elapsed=129.6s

  [1217/13157] intraday_1020.csv.gz  in=179,886,710 out=6,345,524 elapsed=129.7s

  [1218/13157] intraday_10197.csv.gz  in=179,967,131 out=6,425,945 elapsed=129.8s

  [1219/13157] intraday_10200.csv.gz  in=180,044,273 out=6,503,087 elapsed=129.9s

  [1220/13157] intraday_10198.csv.gz  in=180,140,224 out=6,599,038 elapsed=129.9s

  [1221/13157] intraday_10199.csv.gz  in=180,219,078 out=6,677,892 elapsed=129.9s

  [1222/13157] intraday_10201.csv.gz  in=180,320,540 out=6,779,354 elapsed=130.0s

  [1223/13157] intraday_10204.csv.gz  in=180,397,846 out=6,856,660 elapsed=130.2s

  [1224/13157] intraday_10202.csv.gz  in=180,481,986 out=6,940,800 elapsed=130.2s

  [1225/13157] intraday_10205.csv.gz  in=180,570,012 out=7,028,826 elapsed=130.2s

  [1226/13157] intraday_10203.csv.gz  in=180,648,610 out=7,107,424 elapsed=130.2s

  [1227/13157] intraday_10206.csv.gz  in=180,725,971 out=7,184,785 elapsed=130.3s

  [1228/13157] intraday_10207.csv.gz  in=180,799,011 out=7,257,825 elapsed=130.3s

  [1229/13157] intraday_10209.csv.gz  in=180,877,592 out=7,336,406 elapsed=130.4s

  [1230/13157] intraday_1021.csv.gz  in=180,890,694 out=7,336,406 elapsed=130.4s

  [1231/13157] intraday_10208.csv.gz  in=180,978,301 out=7,424,013 elapsed=130.4s

  [1232/13157] intraday_10210.csv.gz  in=181,052,594 out=7,498,306 elapsed=130.5s

  [1233/13157] intraday_10212.csv.gz  in=181,146,612 out=7,592,324 elapsed=130.8s

  [1234/13157] intraday_10214.csv.gz  in=181,226,231 out=7,671,943 elapsed=130.9s

  [1235/13157] intraday_10211.csv.gz  in=181,341,598 out=7,787,310 elapsed=131.0s

  [1236/13157] intraday_10215.csv.gz  in=181,436,914 out=7,882,626 elapsed=131.0s

  [1237/13157] intraday_10213.csv.gz  in=181,538,956 out=7,984,668 elapsed=131.0s

  [1238/13157] intraday_10216.csv.gz  in=181,611,320 out=8,057,032 elapsed=131.2s

  [1239/13157] intraday_1022.csv.gz  in=181,622,050 out=8,057,032 elapsed=131.2s

  [1240/13157] intraday_10218.csv.gz  in=181,703,234 out=8,138,216 elapsed=131.6s

  [1241/13157] intraday_10217.csv.gz  in=181,795,908 out=8,230,890 elapsed=131.8s

  [1242/13157] intraday_10219.csv.gz  in=181,886,623 out=8,321,605 elapsed=131.8s

  [1243/13157] intraday_10220.csv.gz  in=181,961,528 out=8,396,510 elapsed=131.8s

  [1244/13157] intraday_10221.csv.gz  in=182,062,513 out=8,497,495 elapsed=131.8s

  [1245/13157] intraday_10225.csv.gz  in=182,142,865 out=8,577,847 elapsed=132.2s

  [1246/13157] intraday_10224.csv.gz  in=182,221,006 out=8,655,988 elapsed=132.2s

  [1247/13157] intraday_10222.csv.gz  in=182,304,398 out=8,739,380 elapsed=132.2s

  [1248/13157] intraday_10223.csv.gz  in=182,398,973 out=8,833,955 elapsed=132.3s

  [1249/13157] intraday_10227.csv.gz  in=182,461,268 out=8,896,250 elapsed=132.8s

  [1250/13157] intraday_10226.csv.gz  in=182,538,188 out=8,973,170 elapsed=132.9s

  [1251/13157] intraday_10229.csv.gz  in=182,628,409 out=9,063,391 elapsed=132.9s

  [1252/13157] intraday_1023.csv.gz  in=182,641,718 out=9,063,391 elapsed=132.9s

  [1253/13157] intraday_10228.csv.gz  in=182,716,973 out=9,138,646 elapsed=132.9s

  [1254/13157] intraday_10233.csv.gz  in=182,790,005 out=9,211,678 elapsed=133.2s

  [1255/13157] intraday_10232.csv.gz  in=182,881,371 out=9,303,044 elapsed=133.3s

  [1256/13157] intraday_10231.csv.gz  in=182,996,678 out=9,418,351 elapsed=133.5s

  [1257/13157] intraday_10230.csv.gz  in=183,109,757 out=9,531,430 elapsed=133.5s

  [1258/13157] intraday_10235.csv.gz  in=183,198,212 out=9,619,885 elapsed=133.5s

  [1259/13157] intraday_10234.csv.gz  in=183,296,465 out=9,718,138 elapsed=133.6s

  [1260/13157] intraday_10237.csv.gz  in=183,376,816 out=9,798,489 elapsed=133.7s

  [1261/13157] intraday_10238.csv.gz  in=183,457,819 out=9,879,492 elapsed=133.7s

  [1262/13157] intraday_1024.csv.gz  in=183,469,755 out=9,879,492 elapsed=133.8s

  [1263/13157] intraday_10236.csv.gz  in=183,575,279 out=9,985,016 elapsed=133.8s

  [1264/13157] intraday_10239.csv.gz  in=183,675,534 out=10,085,271 elapsed=133.8s

  [1265/13157] intraday_10240.csv.gz  in=183,764,000 out=10,173,737 elapsed=133.9s

  [1266/13157] intraday_10242.csv.gz  in=183,848,708 out=10,258,445 elapsed=134.2s

  [1267/13157] intraday_10241.csv.gz  in=183,939,998 out=10,349,735 elapsed=134.2s

  [1268/13157] intraday_10244.csv.gz  in=184,029,411 out=10,439,148 elapsed=134.3s

  [1269/13157] intraday_10243.csv.gz  in=184,116,987 out=10,526,724 elapsed=134.3s

  [1270/13157] intraday_10247.csv.gz  in=184,190,790 out=10,600,527 elapsed=134.7s

  [1271/13157] intraday_10246.csv.gz  in=184,284,840 out=10,694,577 elapsed=134.8s

  [1272/13157] intraday_10248.csv.gz  in=184,372,439 out=10,782,176 elapsed=134.8s

  [1273/13157] intraday_10245.csv.gz  in=184,462,634 out=10,872,371 elapsed=134.8s

  [1274/13157] intraday_1025.csv.gz  in=184,497,338 out=10,872,371 elapsed=134.8s

  [1275/13157] intraday_10249.csv.gz  in=184,588,888 out=10,963,921 elapsed=134.8s

  [1276/13157] intraday_10251.csv.gz  in=184,675,075 out=11,050,108 elapsed=135.0s

  [1277/13157] intraday_10250.csv.gz  in=184,770,845 out=11,145,878 elapsed=135.1s

  [1278/13157] intraday_10252.csv.gz  in=184,853,516 out=11,228,549 elapsed=135.1s

  [1279/13157] intraday_10253.csv.gz  in=184,964,671 out=11,339,704 elapsed=135.1s

  [1280/13157] intraday_10254.csv.gz  in=185,043,773 out=11,418,806 elapsed=135.3s

  [1281/13157] intraday_10255.csv.gz  in=185,128,272 out=11,503,305 elapsed=135.3s

  [1282/13157] intraday_10256.csv.gz  in=185,224,692 out=11,599,725 elapsed=135.9s

  [1283/13157] intraday_1026.csv.gz  in=185,236,273 out=11,599,725 elapsed=136.1s

  [1284/13157] intraday_10257.csv.gz  in=185,335,351 out=11,698,803 elapsed=136.2s

  [1285/13157] intraday_10258.csv.gz  in=185,423,611 out=11,787,063 elapsed=136.2s

  [1286/13157] intraday_10259.csv.gz  in=185,518,466 out=11,881,918 elapsed=136.3s

  [1287/13157] intraday_10260.csv.gz  in=185,601,650 out=11,965,102 elapsed=136.3s

  [1288/13157] intraday_10261.csv.gz  in=185,686,507 out=12,049,959 elapsed=136.4s

  [1289/13157] intraday_10262.csv.gz  in=185,785,713 out=12,149,165 elapsed=136.4s

  [1290/13157] intraday_10265.csv.gz  in=185,889,355 out=12,252,807 elapsed=136.5s

  [1291/13157] intraday_10263.csv.gz  in=186,005,934 out=12,369,386 elapsed=136.5s

  [1292/13157] intraday_10266.csv.gz  in=186,104,372 out=12,467,824 elapsed=136.6s

  [1293/13157] intraday_10264.csv.gz  in=186,239,622 out=12,603,074 elapsed=136.6s

  [1294/13157] intraday_1027.csv.gz  in=186,251,957 out=12,603,074 elapsed=136.7s

  [1295/13157] intraday_10267.csv.gz  in=186,327,889 out=12,679,006 elapsed=136.7s

  [1296/13157] intraday_10268.csv.gz  in=186,419,031 out=12,770,148 elapsed=136.7s

  [1297/13157] intraday_10269.csv.gz  in=186,494,597 out=12,845,714 elapsed=136.7s

  [1298/13157] intraday_10271.csv.gz  in=186,567,903 out=12,919,020 elapsed=137.4s

  [1299/13157] intraday_10270.csv.gz  in=186,670,937 out=13,022,054 elapsed=137.5s

  [1300/13157] intraday_10273.csv.gz  in=186,762,094 out=13,113,211 elapsed=137.5s

  [1301/13157] intraday_10272.csv.gz  in=186,856,537 out=13,207,654 elapsed=137.5s

  [1302/13157] intraday_10274.csv.gz  in=186,968,075 out=13,319,192 elapsed=137.5s

  [1303/13157] intraday_10275.csv.gz  in=187,041,830 out=13,392,947 elapsed=137.6s

  [1304/13157] intraday_10276.csv.gz  in=187,124,059 out=13,475,176 elapsed=137.8s

  [1305/13157] intraday_1028.csv.gz  in=187,135,831 out=13,475,176 elapsed=137.9s

  [1306/13157] intraday_10278.csv.gz  in=187,226,770 out=13,566,115 elapsed=137.9s

  [1307/13157] intraday_10277.csv.gz  in=187,304,715 out=13,644,060 elapsed=137.9s

  [1308/13157] intraday_10279.csv.gz  in=187,386,833 out=13,726,178 elapsed=137.9s

  [1309/13157] intraday_10280.csv.gz  in=187,484,710 out=13,824,055 elapsed=138.1s

  [1310/13157] intraday_10281.csv.gz  in=187,595,459 out=13,934,804 elapsed=138.1s

  [1311/13157] intraday_10282.csv.gz  in=187,689,067 out=14,028,412 elapsed=138.2s

  [1312/13157] intraday_10283.csv.gz  in=187,797,424 out=14,136,769 elapsed=138.4s

  [1313/13157] intraday_10284.csv.gz  in=187,871,229 out=14,210,574 elapsed=139.2s

  [1314/13157] intraday_10287.csv.gz  in=187,947,717 out=14,287,062 elapsed=139.3s

  [1315/13157] intraday_10285.csv.gz  in=188,035,902 out=14,375,247 elapsed=139.3s

  [1316/13157] intraday_10286.csv.gz  in=188,133,461 out=14,472,806 elapsed=139.3s

  [1317/13157] intraday_1029.csv.gz  in=188,145,189 out=14,472,806 elapsed=139.4s

  [1318/13157] intraday_10288.csv.gz  in=188,260,016 out=14,587,633 elapsed=139.5s

  [1319/13157] intraday_10292.csv.gz  in=188,274,080 out=14,601,697 elapsed=139.8s

  [1320/13157] intraday_10289.csv.gz  in=188,335,624 out=14,663,241 elapsed=140.0s

  [1321/13157] intraday_10293.csv.gz  in=188,347,682 out=14,675,299 elapsed=140.3s

  [1322/13157] intraday_10290.csv.gz  in=188,427,852 out=14,755,469 elapsed=140.4s

  [1323/13157] intraday_10295.csv.gz  in=188,437,767 out=14,765,384 elapsed=141.1s

  [1324/13157] intraday_10294.csv.gz  in=188,453,262 out=14,780,879 elapsed=141.1s

  [1325/13157] intraday_10296.csv.gz  in=188,464,836 out=14,792,453 elapsed=141.1s

  [1326/13157] intraday_10297.csv.gz  in=188,478,308 out=14,805,925 elapsed=141.1s

  [1327/13157] intraday_10299.csv.gz  in=188,488,570 out=14,816,187 elapsed=141.1s

  [1328/13157] intraday_10298.csv.gz  in=188,501,498 out=14,829,115 elapsed=141.2s

  [1329/13157] intraday_10291.csv.gz  in=188,569,850 out=14,897,467 elapsed=141.2s

  [1330/13157] intraday_1030.csv.gz  in=188,581,890 out=14,897,467 elapsed=141.2s

  [1331/13157] intraday_10301.csv.gz  in=188,595,562 out=14,911,139 elapsed=141.2s

  [1332/13157] intraday_10300.csv.gz  in=188,606,985 out=14,922,562 elapsed=141.2s

  [1333/13157] intraday_10302.csv.gz  in=188,618,654 out=14,934,231 elapsed=141.2s

  [1334/13157] intraday_10303.csv.gz  in=188,629,492 out=14,945,069 elapsed=141.2s

  [1335/13157] intraday_10307.csv.gz  in=188,640,198 out=14,955,775 elapsed=141.3s

  [1336/13157] intraday_10305.csv.gz  in=188,653,416 out=14,968,993 elapsed=141.3s

  [1337/13157] intraday_10304.csv.gz  in=188,665,839 out=14,981,416 elapsed=141.3s

  [1338/13157] intraday_10306.csv.gz  in=188,675,244 out=14,990,821 elapsed=141.3s

  [1339/13157] intraday_1031.csv.gz  in=188,695,234 out=14,990,821 elapsed=141.4s

  [1340/13157] intraday_10309.csv.gz  in=188,708,288 out=15,003,875 elapsed=141.4s

  [1341/13157] intraday_10308.csv.gz  in=188,721,100 out=15,016,687 elapsed=141.4s

  [1342/13157] intraday_10310.csv.gz  in=188,732,815 out=15,028,402 elapsed=141.4s

  [1343/13157] intraday_10312.csv.gz  in=188,743,776 out=15,039,363 elapsed=141.4s

  [1344/13157] intraday_10311.csv.gz  in=188,754,760 out=15,050,347 elapsed=141.4s

  [1345/13157] intraday_10314.csv.gz  in=188,767,232 out=15,062,819 elapsed=141.4s

  [1346/13157] intraday_10313.csv.gz  in=188,780,661 out=15,076,248 elapsed=141.5s

  [1347/13157] intraday_10315.csv.gz  in=188,792,750 out=15,088,337 elapsed=141.5s

  [1348/13157] intraday_10317.csv.gz  in=188,803,535 out=15,099,122 elapsed=141.5s

  [1349/13157] intraday_10318.csv.gz  in=188,814,782 out=15,110,369 elapsed=141.5s

  [1350/13157] intraday_10316.csv.gz  in=188,826,476 out=15,122,063 elapsed=141.5s

  [1351/13157] intraday_1032.csv.gz  in=188,836,584 out=15,122,063 elapsed=141.5s

  [1352/13157] intraday_10319.csv.gz  in=188,847,949 out=15,133,428 elapsed=141.6s

  [1353/13157] intraday_10321.csv.gz  in=188,860,355 out=15,145,834 elapsed=141.6s

  [1354/13157] intraday_10320.csv.gz  in=188,871,230 out=15,156,709 elapsed=141.6s

  [1355/13157] intraday_10323.csv.gz  in=188,885,675 out=15,171,154 elapsed=141.6s

  [1356/13157] intraday_10322.csv.gz  in=188,900,017 out=15,185,496 elapsed=141.6s

  [1357/13157] intraday_10324.csv.gz  in=188,909,570 out=15,195,049 elapsed=141.6s

  [1358/13157] intraday_10325.csv.gz  in=188,919,534 out=15,205,013 elapsed=141.7s

  [1359/13157] intraday_10326.csv.gz  in=188,930,923 out=15,216,402 elapsed=141.7s

  [1360/13157] intraday_10327.csv.gz  in=188,942,860 out=15,228,339 elapsed=141.7s

  [1361/13157] intraday_10328.csv.gz  in=188,953,908 out=15,239,387 elapsed=141.7s

  [1362/13157] intraday_10329.csv.gz  in=188,965,141 out=15,250,620 elapsed=141.7s

  [1363/13157] intraday_1033.csv.gz  in=188,976,686 out=15,250,620 elapsed=141.7s

  [1364/13157] intraday_10330.csv.gz  in=188,987,032 out=15,260,966 elapsed=141.7s

  [1365/13157] intraday_10331.csv.gz  in=188,996,876 out=15,270,810 elapsed=141.8s

  [1366/13157] intraday_10333.csv.gz  in=189,008,354 out=15,282,288 elapsed=141.8s

  [1367/13157] intraday_10332.csv.gz  in=189,019,146 out=15,293,080 elapsed=141.8s

  [1368/13157] intraday_10334.csv.gz  in=189,032,417 out=15,306,351 elapsed=141.8s

  [1369/13157] intraday_10336.csv.gz  in=189,045,567 out=15,319,501 elapsed=142.0s

  [1370/13157] intraday_10338.csv.gz  in=189,055,715 out=15,329,649 elapsed=142.0s

  [1371/13157] intraday_10335.csv.gz  in=189,066,419 out=15,340,353 elapsed=142.0s

  [1372/13157] intraday_10337.csv.gz  in=189,079,317 out=15,353,251 elapsed=142.0s

  [1373/13157] intraday_1034.csv.gz  in=189,090,714 out=15,353,251 elapsed=142.2s

  [1374/13157] intraday_10339.csv.gz  in=189,104,555 out=15,367,092 elapsed=142.2s

  [1375/13157] intraday_10340.csv.gz  in=189,116,343 out=15,378,880 elapsed=142.2s

  [1376/13157] intraday_10341.csv.gz  in=189,126,157 out=15,388,694 elapsed=142.2s

  [1377/13157] intraday_10344.csv.gz  in=189,136,288 out=15,398,825 elapsed=142.4s

  [1378/13157] intraday_10342.csv.gz  in=189,147,466 out=15,410,003 elapsed=142.4s

  [1379/13157] intraday_10343.csv.gz  in=189,158,176 out=15,420,713 elapsed=142.7s

  [1380/13157] intraday_10345.csv.gz  in=189,170,240 out=15,432,777 elapsed=142.7s

  [1381/13157] intraday_10346.csv.gz  in=189,181,511 out=15,444,048 elapsed=142.7s

  [1382/13157] intraday_10347.csv.gz  in=189,192,631 out=15,455,168 elapsed=142.8s

  [1383/13157] intraday_10348.csv.gz  in=189,204,668 out=15,467,205 elapsed=142.9s

  [1384/13157] intraday_1035.csv.gz  in=189,219,920 out=15,467,205 elapsed=142.9s

  [1385/13157] intraday_10349.csv.gz  in=189,230,735 out=15,478,020 elapsed=142.9s

  [1386/13157] intraday_10350.csv.gz  in=189,242,040 out=15,489,325 elapsed=143.3s

  [1387/13157] intraday_10351.csv.gz  in=189,252,102 out=15,499,387 elapsed=143.3s

  [1388/13157] intraday_10353.csv.gz  in=189,262,051 out=15,509,336 elapsed=143.3s

  [1389/13157] intraday_10352.csv.gz  in=189,273,565 out=15,520,850 elapsed=143.4s

  [1390/13157] intraday_10356.csv.gz  in=189,284,096 out=15,531,381 elapsed=143.5s

  [1391/13157] intraday_10355.csv.gz  in=189,296,572 out=15,543,857 elapsed=143.5s

  [1392/13157] intraday_10354.csv.gz  in=189,308,623 out=15,555,908 elapsed=143.5s

  [1393/13157] intraday_10357.csv.gz  in=189,326,487 out=15,573,772 elapsed=143.5s

  [1394/13157] intraday_10358.csv.gz  in=189,340,638 out=15,587,923 elapsed=143.5s

  [1395/13157] intraday_10359.csv.gz  in=189,353,256 out=15,600,541 elapsed=143.6s

  [1396/13157] intraday_10361.csv.gz  in=189,364,781 out=15,612,066 elapsed=143.6s

  [1397/13157] intraday_10360.csv.gz  in=189,378,006 out=15,625,291 elapsed=143.6s

  [1398/13157] intraday_1036.csv.gz  in=189,402,208 out=15,625,291 elapsed=143.6s

  [1399/13157] intraday_10362.csv.gz  in=189,414,073 out=15,637,156 elapsed=143.6s

  [1400/13157] intraday_10363.csv.gz  in=189,423,970 out=15,647,053 elapsed=143.6s

  [1401/13157] intraday_10365.csv.gz  in=189,435,852 out=15,658,935 elapsed=143.7s

  [1402/13157] intraday_10364.csv.gz  in=189,446,829 out=15,669,912 elapsed=143.7s

  [1403/13157] intraday_10367.csv.gz  in=189,458,993 out=15,682,076 elapsed=143.8s

  [1404/13157] intraday_10366.csv.gz  in=189,471,095 out=15,694,178 elapsed=143.8s

  [1405/13157] intraday_10369.csv.gz  in=189,480,979 out=15,704,062 elapsed=143.8s

  [1406/13157] intraday_10368.csv.gz  in=189,492,194 out=15,715,277 elapsed=143.8s

  [1407/13157] intraday_1037.csv.gz  in=189,504,725 out=15,715,277 elapsed=143.8s

  [1408/13157] intraday_10370.csv.gz  in=189,516,956 out=15,727,508 elapsed=143.8s

  [1409/13157] intraday_10373.csv.gz  in=189,527,709 out=15,738,261 elapsed=143.9s

  [1410/13157] intraday_10372.csv.gz  in=189,538,997 out=15,749,549 elapsed=143.9s

  [1411/13157] intraday_10374.csv.gz  in=189,547,793 out=15,758,345 elapsed=143.9s

  [1412/13157] intraday_10371.csv.gz  in=189,558,451 out=15,769,003 elapsed=143.9s

  [1413/13157] intraday_10375.csv.gz  in=189,568,565 out=15,779,117 elapsed=143.9s

  [1414/13157] intraday_10376.csv.gz  in=189,580,448 out=15,791,000 elapsed=143.9s

  [1415/13157] intraday_10377.csv.gz  in=189,596,045 out=15,806,597 elapsed=144.0s

  [1416/13157] intraday_10378.csv.gz  in=189,609,647 out=15,820,199 elapsed=144.0s

  [1417/13157] intraday_10379.csv.gz  in=189,621,410 out=15,831,962 elapsed=144.0s

  [1418/13157] intraday_1038.csv.gz  in=189,633,115 out=15,831,962 elapsed=144.0s

  [1419/13157] intraday_10380.csv.gz  in=189,642,668 out=15,841,515 elapsed=144.0s

  [1420/13157] intraday_10381.csv.gz  in=189,656,437 out=15,855,284 elapsed=144.0s

  [1421/13157] intraday_10383.csv.gz  in=189,670,221 out=15,869,068 elapsed=144.1s

  [1422/13157] intraday_10382.csv.gz  in=189,680,840 out=15,879,687 elapsed=144.1s

  [1423/13157] intraday_10385.csv.gz  in=189,691,780 out=15,890,627 elapsed=144.1s

  [1424/13157] intraday_10384.csv.gz  in=189,704,206 out=15,903,053 elapsed=144.1s

  [1425/13157] intraday_10386.csv.gz  in=189,716,745 out=15,915,592 elapsed=144.1s

  [1426/13157] intraday_10387.csv.gz  in=189,729,601 out=15,928,448 elapsed=144.1s

  [1427/13157] intraday_10388.csv.gz  in=189,742,115 out=15,940,962 elapsed=144.3s

  [1428/13157] intraday_1039.csv.gz  in=189,755,139 out=15,940,962 elapsed=144.3s

  [1429/13157] intraday_10390.csv.gz  in=189,767,512 out=15,953,335 elapsed=144.3s

  [1430/13157] intraday_10389.csv.gz  in=189,779,387 out=15,965,210 elapsed=144.3s

  [1431/13157] intraday_10394.csv.gz  in=189,789,599 out=15,975,422 elapsed=144.4s

  [1432/13157] intraday_10392.csv.gz  in=189,801,534 out=15,987,357 elapsed=144.6s

  [1433/13157] intraday_10391.csv.gz  in=189,812,612 out=15,998,435 elapsed=144.6s

  [1434/13157] intraday_10393.csv.gz  in=189,825,216 out=16,011,039 elapsed=144.6s

  [1435/13157] intraday_10395.csv.gz  in=189,836,666 out=16,022,489 elapsed=144.6s

  [1436/13157] intraday_10397.csv.gz  in=189,848,280 out=16,034,103 elapsed=144.9s

  [1437/13157] intraday_10396.csv.gz  in=189,860,975 out=16,046,798 elapsed=144.9s

  [1438/13157] intraday_10399.csv.gz  in=189,871,251 out=16,057,074 elapsed=144.9s

  [1439/13157] intraday_10398.csv.gz  in=189,883,013 out=16,068,836 elapsed=144.9s

  [1440/13157] intraday_1040.csv.gz  in=189,895,412 out=16,068,836 elapsed=145.1s

  [1441/13157] intraday_10400.csv.gz  in=189,910,843 out=16,084,267 elapsed=145.1s

  [1442/13157] intraday_10402.csv.gz  in=189,922,519 out=16,095,943 elapsed=145.1s

  [1443/13157] intraday_10401.csv.gz  in=189,931,805 out=16,105,229 elapsed=145.1s

  [1444/13157] intraday_10404.csv.gz  in=189,944,979 out=16,118,403 elapsed=145.2s

  [1445/13157] intraday_10406.csv.gz  in=189,960,046 out=16,133,470 elapsed=145.2s

  [1446/13157] intraday_10403.csv.gz  in=189,980,366 out=16,153,790 elapsed=145.2s

  [1447/13157] intraday_10405.csv.gz  in=189,990,426 out=16,163,850 elapsed=145.2s

  [1448/13157] intraday_10407.csv.gz  in=190,003,378 out=16,176,802 elapsed=145.2s

  [1449/13157] intraday_10408.csv.gz  in=190,014,957 out=16,188,381 elapsed=145.5s

  [1450/13157] intraday_1041.csv.gz  in=190,030,242 out=16,188,381 elapsed=145.5s

  [1451/13157] intraday_10410.csv.gz  in=190,045,310 out=16,203,449 elapsed=145.5s

  [1452/13157] intraday_10409.csv.gz  in=190,060,426 out=16,218,565 elapsed=145.5s

  [1453/13157] intraday_10411.csv.gz  in=190,077,193 out=16,235,332 elapsed=145.5s

  [1454/13157] intraday_10412.csv.gz  in=190,091,577 out=16,249,716 elapsed=145.5s

  [1455/13157] intraday_10414.csv.gz  in=190,101,868 out=16,260,007 elapsed=145.5s

  [1456/13157] intraday_10413.csv.gz  in=190,115,831 out=16,273,970 elapsed=145.5s

  [1457/13157] intraday_10415.csv.gz  in=190,127,352 out=16,285,491 elapsed=145.6s

  [1458/13157] intraday_10416.csv.gz  in=190,138,032 out=16,296,171 elapsed=145.6s

  [1459/13157] intraday_10417.csv.gz  in=190,150,246 out=16,308,385 elapsed=145.6s

  [1460/13157] intraday_1042.csv.gz  in=190,162,259 out=16,308,385 elapsed=145.7s

  [1461/13157] intraday_10418.csv.gz  in=190,173,082 out=16,319,208 elapsed=145.7s

  [1462/13157] intraday_10419.csv.gz  in=190,185,728 out=16,331,854 elapsed=145.7s

  [1463/13157] intraday_10420.csv.gz  in=190,198,732 out=16,344,858 elapsed=145.7s

  [1464/13157] intraday_10421.csv.gz  in=190,212,555 out=16,358,681 elapsed=145.7s

  [1465/13157] intraday_10422.csv.gz  in=190,223,133 out=16,369,259 elapsed=145.8s

  [1466/13157] intraday_10423.csv.gz  in=190,234,082 out=16,380,208 elapsed=145.8s

  [1467/13157] intraday_10424.csv.gz  in=190,244,951 out=16,391,077 elapsed=145.8s

  [1468/13157] intraday_10425.csv.gz  in=190,256,265 out=16,402,391 elapsed=145.8s

  [1469/13157] intraday_10426.csv.gz  in=190,267,065 out=16,413,191 elapsed=145.8s

  [1470/13157] intraday_10429.csv.gz  in=190,279,764 out=16,425,890 elapsed=145.8s

  [1471/13157] intraday_10427.csv.gz  in=190,294,215 out=16,440,341 elapsed=145.8s

  [1472/13157] intraday_10428.csv.gz  in=190,309,957 out=16,456,083 elapsed=145.8s

  [1473/13157] intraday_1043.csv.gz  in=190,326,010 out=16,456,083 elapsed=146.0s

  [1474/13157] intraday_10430.csv.gz  in=190,341,261 out=16,471,334 elapsed=146.0s

  [1475/13157] intraday_10432.csv.gz  in=190,352,179 out=16,482,252 elapsed=146.0s

  [1476/13157] intraday_10431.csv.gz  in=190,363,283 out=16,493,356 elapsed=146.0s

  [1477/13157] intraday_10436.csv.gz  in=190,372,117 out=16,502,190 elapsed=146.1s

  [1478/13157] intraday_10434.csv.gz  in=190,382,128 out=16,512,201 elapsed=146.2s

  [1479/13157] intraday_10435.csv.gz  in=190,394,716 out=16,524,789 elapsed=146.2s

  [1480/13157] intraday_10433.csv.gz  in=190,407,256 out=16,537,329 elapsed=146.2s

  [1481/13157] intraday_10437.csv.gz  in=190,417,986 out=16,548,059 elapsed=146.3s

  [1482/13157] intraday_10438.csv.gz  in=190,426,352 out=16,556,425 elapsed=146.6s

  [1483/13157] intraday_1044.csv.gz  in=190,440,522 out=16,556,425 elapsed=146.7s

  [1484/13157] intraday_10439.csv.gz  in=190,454,999 out=16,570,902 elapsed=146.8s

  [1485/13157] intraday_10440.csv.gz  in=190,467,263 out=16,583,166 elapsed=146.8s

  [1486/13157] intraday_10441.csv.gz  in=190,480,356 out=16,596,259 elapsed=146.8s

  [1487/13157] intraday_10444.csv.gz  in=190,494,660 out=16,610,563 elapsed=146.9s

  [1488/13157] intraday_10442.csv.gz  in=190,504,134 out=16,620,037 elapsed=146.9s

  [1489/13157] intraday_10443.csv.gz  in=190,515,555 out=16,631,458 elapsed=146.9s

  [1490/13157] intraday_10445.csv.gz  in=190,528,567 out=16,644,470 elapsed=146.9s

  [1491/13157] intraday_10446.csv.gz  in=190,540,326 out=16,656,229 elapsed=147.0s

  [1492/13157] intraday_10449.csv.gz  in=190,554,435 out=16,670,338 elapsed=147.0s

  [1493/13157] intraday_10447.csv.gz  in=190,565,609 out=16,681,512 elapsed=147.0s

  [1494/13157] intraday_10448.csv.gz  in=190,579,035 out=16,694,938 elapsed=147.0s

  [1495/13157] intraday_1045.csv.gz  in=190,593,370 out=16,694,938 elapsed=147.1s

  [1496/13157] intraday_10450.csv.gz  in=190,605,078 out=16,706,646 elapsed=147.2s

  [1497/13157] intraday_10452.csv.gz  in=190,619,233 out=16,720,801 elapsed=147.2s

  [1498/13157] intraday_10451.csv.gz  in=190,631,584 out=16,733,152 elapsed=147.2s

  [1499/13157] intraday_10453.csv.gz  in=190,641,555 out=16,743,123 elapsed=147.2s

  [1500/13157] intraday_10454.csv.gz  in=190,651,958 out=16,753,526 elapsed=147.2s

  [1501/13157] intraday_10455.csv.gz  in=190,664,580 out=16,766,148 elapsed=147.2s

  [1502/13157] intraday_10457.csv.gz  in=190,676,207 out=16,777,775 elapsed=147.3s

  [1503/13157] intraday_10456.csv.gz  in=190,690,050 out=16,791,618 elapsed=147.3s

  [1504/13157] intraday_10458.csv.gz  in=190,700,110 out=16,801,678 elapsed=147.3s

  [1505/13157] intraday_10459.csv.gz  in=190,710,999 out=16,812,567 elapsed=147.3s

  [1506/13157] intraday_1046.csv.gz  in=190,723,721 out=16,812,567 elapsed=147.3s

  [1507/13157] intraday_10460.csv.gz  in=190,737,368 out=16,826,214 elapsed=147.3s

  [1508/13157] intraday_10461.csv.gz  in=190,749,492 out=16,838,338 elapsed=147.3s

  [1509/13157] intraday_10463.csv.gz  in=190,761,174 out=16,850,020 elapsed=147.4s

  [1510/13157] intraday_10462.csv.gz  in=190,773,305 out=16,862,151 elapsed=147.4s

  [1511/13157] intraday_10465.csv.gz  in=190,784,503 out=16,873,349 elapsed=147.4s

  [1512/13157] intraday_10464.csv.gz  in=190,795,768 out=16,884,614 elapsed=147.4s

  [1513/13157] intraday_10467.csv.gz  in=190,807,460 out=16,896,306 elapsed=147.5s

  [1514/13157] intraday_10466.csv.gz  in=190,819,138 out=16,907,984 elapsed=147.5s

  [1515/13157] intraday_10469.csv.gz  in=190,834,254 out=16,923,100 elapsed=147.6s

  [1516/13157] intraday_10468.csv.gz  in=190,846,577 out=16,935,423 elapsed=147.6s

  [1517/13157] intraday_10471.csv.gz  in=190,856,387 out=16,945,233 elapsed=148.1s

  [1518/13157] intraday_10470.csv.gz  in=190,868,428 out=16,957,274 elapsed=148.1s

  [1519/13157] intraday_1047.csv.gz  in=190,884,844 out=16,957,274 elapsed=148.1s

  [1520/13157] intraday_10472.csv.gz  in=190,895,719 out=16,968,149 elapsed=148.1s

  [1521/13157] intraday_10474.csv.gz  in=190,908,942 out=16,981,372 elapsed=148.3s

  [1522/13157] intraday_10475.csv.gz  in=190,920,541 out=16,992,971 elapsed=148.4s

  [1523/13157] intraday_10476.csv.gz  in=190,933,544 out=17,005,974 elapsed=148.4s

  [1524/13157] intraday_10473.csv.gz  in=190,945,837 out=17,018,267 elapsed=148.4s

  [1525/13157] intraday_10477.csv.gz  in=190,955,640 out=17,028,070 elapsed=148.4s

  [1526/13157] intraday_10478.csv.gz  in=190,964,740 out=17,037,170 elapsed=148.4s

  [1527/13157] intraday_1048.csv.gz  in=190,976,486 out=17,037,170 elapsed=148.4s

  [1528/13157] intraday_10479.csv.gz  in=190,987,267 out=17,047,951 elapsed=148.4s

  [1529/13157] intraday_10480.csv.gz  in=190,999,633 out=17,060,317 elapsed=148.5s

  [1530/13157] intraday_10482.csv.gz  in=191,011,439 out=17,072,123 elapsed=148.5s

  [1531/13157] intraday_10483.csv.gz  in=191,023,804 out=17,084,488 elapsed=148.6s

  [1532/13157] intraday_10481.csv.gz  in=191,038,087 out=17,098,771 elapsed=148.6s

  [1533/13157] intraday_10484.csv.gz  in=191,051,320 out=17,112,004 elapsed=148.6s

  [1534/13157] intraday_10486.csv.gz  in=191,063,310 out=17,123,994 elapsed=148.6s

  [1535/13157] intraday_10487.csv.gz  in=191,074,334 out=17,135,018 elapsed=148.7s

  [1536/13157] intraday_10488.csv.gz  in=191,085,177 out=17,145,861 elapsed=148.7s

  [1537/13157] intraday_10485.csv.gz  in=191,097,044 out=17,157,728 elapsed=148.8s

  [1538/13157] intraday_10489.csv.gz  in=191,111,790 out=17,172,474 elapsed=148.8s

  [1539/13157] intraday_1049.csv.gz  in=191,124,073 out=17,172,474 elapsed=148.8s

  [1540/13157] intraday_10490.csv.gz  in=191,135,386 out=17,183,787 elapsed=148.8s

  [1541/13157] intraday_10491.csv.gz  in=191,146,905 out=17,195,306 elapsed=148.9s

  [1542/13157] intraday_10494.csv.gz  in=191,160,648 out=17,209,049 elapsed=148.9s

  [1543/13157] intraday_10493.csv.gz  in=191,172,870 out=17,221,271 elapsed=149.0s

  [1544/13157] intraday_10492.csv.gz  in=191,184,131 out=17,232,532 elapsed=149.0s

  [1545/13157] intraday_10495.csv.gz  in=191,195,455 out=17,243,856 elapsed=149.0s

  [1546/13157] intraday_10496.csv.gz  in=191,207,953 out=17,256,354 elapsed=149.1s

  [1547/13157] intraday_10498.csv.gz  in=191,218,622 out=17,267,023 elapsed=149.1s

  [1548/13157] intraday_10499.csv.gz  in=191,230,928 out=17,279,329 elapsed=149.1s

  [1549/13157] intraday_10497.csv.gz  in=191,242,310 out=17,290,711 elapsed=149.1s

  [1550/13157] intraday_1050.csv.gz  in=191,254,843 out=17,290,711 elapsed=149.1s

  [1551/13157] intraday_10502.csv.gz  in=191,265,051 out=17,300,919 elapsed=149.2s

  [1552/13157] intraday_10500.csv.gz  in=191,275,832 out=17,311,700 elapsed=149.2s

  [1553/13157] intraday_10501.csv.gz  in=191,289,829 out=17,325,697 elapsed=149.2s

  [1554/13157] intraday_10503.csv.gz  in=191,300,921 out=17,336,789 elapsed=149.2s

  [1555/13157] intraday_10504.csv.gz  in=191,311,306 out=17,347,174 elapsed=149.4s

  [1556/13157] intraday_10507.csv.gz  in=191,324,719 out=17,360,587 elapsed=149.4s

  [1557/13157] intraday_10506.csv.gz  in=191,338,045 out=17,373,913 elapsed=149.4s

  [1558/13157] intraday_10505.csv.gz  in=191,353,372 out=17,389,240 elapsed=149.4s

  [1559/13157] intraday_10508.csv.gz  in=191,366,201 out=17,402,069 elapsed=149.6s

  [1560/13157] intraday_1051.csv.gz  in=191,379,131 out=17,402,069 elapsed=149.6s

  [1561/13157] intraday_10510.csv.gz  in=191,390,654 out=17,413,592 elapsed=149.6s

  [1562/13157] intraday_10509.csv.gz  in=191,402,922 out=17,425,860 elapsed=149.6s

  [1563/13157] intraday_10511.csv.gz  in=191,414,362 out=17,437,300 elapsed=149.6s

  [1564/13157] intraday_10512.csv.gz  in=191,427,095 out=17,450,033 elapsed=149.7s

  [1565/13157] intraday_10514.csv.gz  in=191,439,560 out=17,462,498 elapsed=149.7s

  [1566/13157] intraday_10513.csv.gz  in=191,453,662 out=17,476,600 elapsed=149.7s

  [1567/13157] intraday_10515.csv.gz  in=191,466,019 out=17,488,957 elapsed=149.7s

  [1568/13157] intraday_10516.csv.gz  in=191,476,461 out=17,499,399 elapsed=149.7s

  [1569/13157] intraday_10518.csv.gz  in=191,487,206 out=17,510,144 elapsed=149.7s

  [1570/13157] intraday_10517.csv.gz  in=191,500,361 out=17,523,299 elapsed=149.7s

  [1571/13157] intraday_10521.csv.gz  in=191,509,601 out=17,532,539 elapsed=149.8s

  [1572/13157] intraday_10519.csv.gz  in=191,526,376 out=17,549,314 elapsed=149.8s

  [1573/13157] intraday_1052.csv.gz  in=191,537,716 out=17,549,314 elapsed=149.8s

  [1574/13157] intraday_10520.csv.gz  in=191,548,793 out=17,560,391 elapsed=149.8s

  [1575/13157] intraday_10522.csv.gz  in=191,558,748 out=17,570,346 elapsed=149.8s

  [1576/13157] intraday_10523.csv.gz  in=191,571,999 out=17,583,597 elapsed=149.8s

  [1577/13157] intraday_10526.csv.gz  in=191,583,042 out=17,594,640 elapsed=149.8s

  [1578/13157] intraday_10525.csv.gz  in=191,596,593 out=17,608,191 elapsed=149.8s

  [1579/13157] intraday_10524.csv.gz  in=191,613,474 out=17,625,072 elapsed=149.8s

  [1580/13157] intraday_10527.csv.gz  in=191,625,063 out=17,636,661 elapsed=149.9s

  [1581/13157] intraday_10529.csv.gz  in=191,636,561 out=17,648,159 elapsed=149.9s

  [1582/13157] intraday_1053.csv.gz  in=191,662,022 out=17,648,159 elapsed=149.9s

  [1583/13157] intraday_10528.csv.gz  in=191,674,376 out=17,660,513 elapsed=149.9s

  [1584/13157] intraday_10530.csv.gz  in=191,689,716 out=17,675,853 elapsed=150.0s

  [1585/13157] intraday_10531.csv.gz  in=191,702,121 out=17,688,258 elapsed=150.0s

  [1586/13157] intraday_10532.csv.gz  in=191,712,691 out=17,698,828 elapsed=150.0s

  [1587/13157] intraday_10533.csv.gz  in=191,724,144 out=17,710,281 elapsed=150.0s

  [1588/13157] intraday_10534.csv.gz  in=191,738,420 out=17,724,557 elapsed=150.0s

  [1589/13157] intraday_10536.csv.gz  in=191,749,882 out=17,736,019 elapsed=150.0s

  [1590/13157] intraday_10535.csv.gz  in=191,762,218 out=17,748,355 elapsed=150.1s

  [1591/13157] intraday_10537.csv.gz  in=191,774,898 out=17,761,035 elapsed=150.1s

  [1592/13157] intraday_10538.csv.gz  in=191,787,103 out=17,773,240 elapsed=150.1s

  [1593/13157] intraday_10539.csv.gz  in=191,799,226 out=17,785,363 elapsed=150.1s

  [1594/13157] intraday_1054.csv.gz  in=191,811,004 out=17,785,363 elapsed=150.1s

  [1595/13157] intraday_10540.csv.gz  in=191,823,346 out=17,797,705 elapsed=150.1s

  [1596/13157] intraday_10541.csv.gz  in=191,833,411 out=17,807,770 elapsed=150.1s

  [1597/13157] intraday_10544.csv.gz  in=191,846,679 out=17,821,038 elapsed=150.1s

  [1598/13157] intraday_10542.csv.gz  in=191,860,374 out=17,834,733 elapsed=150.2s

  [1599/13157] intraday_10543.csv.gz  in=191,873,765 out=17,848,124 elapsed=150.2s

  [1600/13157] intraday_10545.csv.gz  in=191,885,759 out=17,860,118 elapsed=150.2s

  [1601/13157] intraday_10546.csv.gz  in=191,895,529 out=17,869,888 elapsed=150.2s

  [1602/13157] intraday_10549.csv.gz  in=191,907,224 out=17,881,583 elapsed=150.2s

  [1603/13157] intraday_10548.csv.gz  in=191,918,342 out=17,892,701 elapsed=150.2s

  [1604/13157] intraday_10547.csv.gz  in=191,934,020 out=17,908,379 elapsed=150.2s

  [1605/13157] intraday_1055.csv.gz  in=191,945,961 out=17,908,379 elapsed=150.2s

  [1606/13157] intraday_10550.csv.gz  in=191,959,255 out=17,921,673 elapsed=150.3s

  [1607/13157] intraday_10552.csv.gz  in=191,969,743 out=17,932,161 elapsed=150.3s

  [1608/13157] intraday_10553.csv.gz  in=191,983,789 out=17,946,207 elapsed=150.3s

  [1609/13157] intraday_10551.csv.gz  in=191,997,209 out=17,959,627 elapsed=150.3s

  [1610/13157] intraday_10554.csv.gz  in=192,014,320 out=17,976,738 elapsed=150.3s

  [1611/13157] intraday_10555.csv.gz  in=192,026,119 out=17,988,537 elapsed=150.3s

  [1612/13157] intraday_10557.csv.gz  in=192,040,514 out=18,002,932 elapsed=150.5s

  [1613/13157] intraday_10558.csv.gz  in=192,058,098 out=18,020,516 elapsed=150.5s

  [1614/13157] intraday_10556.csv.gz  in=192,073,305 out=18,035,723 elapsed=150.5s

  [1615/13157] intraday_10559.csv.gz  in=192,087,964 out=18,050,382 elapsed=150.5s

  [1616/13157] intraday_10560.csv.gz  in=192,105,170 out=18,067,588 elapsed=150.6s

  [1617/13157] intraday_10562.csv.gz  in=192,116,986 out=18,079,404 elapsed=150.6s

  [1618/13157] intraday_1056.csv.gz  in=192,133,367 out=18,079,404 elapsed=150.6s

  [1619/13157] intraday_10561.csv.gz  in=192,144,919 out=18,090,956 elapsed=150.6s

  [1620/13157] intraday_10564.csv.gz  in=192,158,311 out=18,104,348 elapsed=150.7s

  [1621/13157] intraday_10563.csv.gz  in=192,177,119 out=18,123,156 elapsed=150.7s

  [1622/13157] intraday_10566.csv.gz  in=192,189,053 out=18,135,090 elapsed=150.8s

  [1623/13157] intraday_10565.csv.gz  in=192,200,124 out=18,146,161 elapsed=150.8s

  [1624/13157] intraday_10567.csv.gz  in=192,212,373 out=18,158,410 elapsed=150.8s

  [1625/13157] intraday_10569.csv.gz  in=192,222,452 out=18,168,489 elapsed=150.8s

  [1626/13157] intraday_10568.csv.gz  in=192,237,880 out=18,183,917 elapsed=150.8s

  [1627/13157] intraday_10570.csv.gz  in=192,248,931 out=18,194,968 elapsed=150.8s

  [1628/13157] intraday_1057.csv.gz  in=192,259,039 out=18,194,968 elapsed=150.8s

  [1629/13157] intraday_10571.csv.gz  in=192,271,326 out=18,207,255 elapsed=150.9s

  [1630/13157] intraday_10572.csv.gz  in=192,283,061 out=18,218,990 elapsed=150.9s

  [1631/13157] intraday_10573.csv.gz  in=192,294,038 out=18,229,967 elapsed=151.0s

  [1632/13157] intraday_10575.csv.gz  in=192,310,007 out=18,245,936 elapsed=151.0s

  [1633/13157] intraday_10574.csv.gz  in=192,325,550 out=18,261,479 elapsed=151.0s

  [1634/13157] intraday_10576.csv.gz  in=192,339,120 out=18,275,049 elapsed=151.0s

  [1635/13157] intraday_10578.csv.gz  in=192,350,428 out=18,286,357 elapsed=151.1s

  [1636/13157] intraday_1058.csv.gz  in=192,363,597 out=18,286,357 elapsed=151.1s

  [1637/13157] intraday_10579.csv.gz  in=192,374,502 out=18,297,262 elapsed=151.2s

  [1638/13157] intraday_10577.csv.gz  in=192,390,464 out=18,313,224 elapsed=151.2s

  [1639/13157] intraday_10580.csv.gz  in=192,403,154 out=18,325,914 elapsed=151.3s

  [1640/13157] intraday_10583.csv.gz  in=192,410,983 out=18,333,743 elapsed=151.3s

  [1641/13157] intraday_10581.csv.gz  in=192,422,560 out=18,345,320 elapsed=151.3s

  [1642/13157] intraday_10582.csv.gz  in=192,432,324 out=18,355,084 elapsed=151.3s

  [1643/13157] intraday_10584.csv.gz  in=192,442,942 out=18,365,702 elapsed=151.3s

  [1644/13157] intraday_10585.csv.gz  in=192,449,461 out=18,372,221 elapsed=151.3s

  [1645/13157] intraday_10587.csv.gz  in=192,462,067 out=18,384,827 elapsed=151.3s

  [1646/13157] intraday_10588.csv.gz  in=192,473,548 out=18,396,308 elapsed=151.4s

  [1647/13157] intraday_1059.csv.gz  in=192,496,365 out=18,396,308 elapsed=151.4s

  [1648/13157] intraday_10586.csv.gz  in=192,511,054 out=18,410,997 elapsed=151.4s

  [1649/13157] intraday_10589.csv.gz  in=192,520,541 out=18,420,484 elapsed=151.4s

  [1650/13157] intraday_10592.csv.gz  in=192,534,772 out=18,434,715 elapsed=151.5s

  [1651/13157] intraday_10590.csv.gz  in=192,546,391 out=18,446,334 elapsed=151.5s

  [1652/13157] intraday_10591.csv.gz  in=192,560,255 out=18,460,198 elapsed=151.5s

  [1653/13157] intraday_10593.csv.gz  in=192,571,033 out=18,470,976 elapsed=151.5s

  [1654/13157] intraday_10595.csv.gz  in=192,584,566 out=18,484,509 elapsed=151.5s

  [1655/13157] intraday_10594.csv.gz  in=192,595,813 out=18,495,756 elapsed=151.5s

  [1656/13157] intraday_10596.csv.gz  in=192,609,901 out=18,509,844 elapsed=151.5s

  [1657/13157] intraday_10597.csv.gz  in=192,621,978 out=18,521,921 elapsed=151.5s

  [1658/13157] intraday_10598.csv.gz  in=192,636,878 out=18,536,821 elapsed=151.6s

  [1659/13157] intraday_1060.csv.gz  in=192,651,775 out=18,536,821 elapsed=151.6s

  [1660/13157] intraday_10600.csv.gz  in=192,661,443 out=18,546,489 elapsed=151.6s

  [1661/13157] intraday_10599.csv.gz  in=192,674,486 out=18,559,532 elapsed=151.6s

  [1662/13157] intraday_10601.csv.gz  in=192,684,453 out=18,569,499 elapsed=151.6s

  [1663/13157] intraday_10602.csv.gz  in=192,696,400 out=18,581,446 elapsed=151.6s

  [1664/13157] intraday_10603.csv.gz  in=192,708,930 out=18,593,976 elapsed=151.6s

  [1665/13157] intraday_10604.csv.gz  in=192,720,002 out=18,605,048 elapsed=151.7s

  [1666/13157] intraday_10605.csv.gz  in=192,730,468 out=18,615,514 elapsed=151.9s

  [1667/13157] intraday_10606.csv.gz  in=192,741,091 out=18,626,137 elapsed=151.9s

  [1668/13157] intraday_10607.csv.gz  in=192,755,504 out=18,640,550 elapsed=151.9s

  [1669/13157] intraday_10608.csv.gz  in=192,768,018 out=18,653,064 elapsed=152.0s

  [1670/13157] intraday_10609.csv.gz  in=192,779,613 out=18,664,659 elapsed=152.1s

  [1671/13157] intraday_1061.csv.gz  in=192,791,539 out=18,664,659 elapsed=152.1s

  [1672/13157] intraday_10610.csv.gz  in=192,804,805 out=18,677,925 elapsed=152.1s

  [1673/13157] intraday_10611.csv.gz  in=192,815,899 out=18,689,019 elapsed=152.1s

  [1674/13157] intraday_10612.csv.gz  in=192,828,066 out=18,701,186 elapsed=152.2s

  [1675/13157] intraday_10613.csv.gz  in=192,839,907 out=18,713,027 elapsed=152.2s

  [1676/13157] intraday_10615.csv.gz  in=192,851,711 out=18,724,831 elapsed=152.2s

  [1677/13157] intraday_10614.csv.gz  in=192,863,475 out=18,736,595 elapsed=152.2s

  [1678/13157] intraday_10618.csv.gz  in=192,873,116 out=18,746,236 elapsed=152.3s

  [1679/13157] intraday_10619.csv.gz  in=192,884,316 out=18,757,436 elapsed=152.3s

  [1680/13157] intraday_10616.csv.gz  in=192,899,592 out=18,772,712 elapsed=152.3s

  [1681/13157] intraday_10617.csv.gz  in=192,911,489 out=18,784,609 elapsed=152.3s

  [1682/13157] intraday_1062.csv.gz  in=192,924,982 out=18,784,609 elapsed=152.3s

  [1683/13157] intraday_10620.csv.gz  in=192,936,672 out=18,796,299 elapsed=152.4s

  [1684/13157] intraday_10622.csv.gz  in=192,948,523 out=18,808,150 elapsed=152.4s

  [1685/13157] intraday_10621.csv.gz  in=192,960,101 out=18,819,728 elapsed=152.4s

  [1686/13157] intraday_10625.csv.gz  in=192,970,098 out=18,829,725 elapsed=152.4s

  [1687/13157] intraday_10623.csv.gz  in=192,981,699 out=18,841,326 elapsed=152.4s

  [1688/13157] intraday_10626.csv.gz  in=192,992,688 out=18,852,315 elapsed=152.4s

  [1689/13157] intraday_10624.csv.gz  in=193,003,744 out=18,863,371 elapsed=152.4s

  [1690/13157] intraday_10629.csv.gz  in=193,015,178 out=18,874,805 elapsed=152.5s

  [1691/13157] intraday_1063.csv.gz  in=193,027,424 out=18,874,805 elapsed=152.5s

  [1692/13157] intraday_10627.csv.gz  in=193,039,597 out=18,886,978 elapsed=152.5s

  [1693/13157] intraday_10628.csv.gz  in=193,053,148 out=18,900,529 elapsed=152.5s

  [1694/13157] intraday_10630.csv.gz  in=193,066,757 out=18,914,138 elapsed=152.5s

  [1695/13157] intraday_10632.csv.gz  in=193,076,948 out=18,924,329 elapsed=152.6s

  [1696/13157] intraday_10631.csv.gz  in=193,089,114 out=18,936,495 elapsed=152.6s

  [1697/13157] intraday_10633.csv.gz  in=193,100,961 out=18,948,342 elapsed=152.6s

  [1698/13157] intraday_10634.csv.gz  in=193,112,303 out=18,959,684 elapsed=152.6s

  [1699/13157] intraday_10635.csv.gz  in=193,122,352 out=18,969,733 elapsed=152.7s

  [1700/13157] intraday_10638.csv.gz  in=193,133,850 out=18,981,231 elapsed=152.7s

  [1701/13157] intraday_10636.csv.gz  in=193,144,878 out=18,992,259 elapsed=152.7s

  [1702/13157] intraday_10637.csv.gz  in=193,156,016 out=19,003,397 elapsed=152.7s

  [1703/13157] intraday_1064.csv.gz  in=193,168,673 out=19,003,397 elapsed=152.8s

  [1704/13157] intraday_10639.csv.gz  in=193,180,748 out=19,015,472 elapsed=152.8s

  [1705/13157] intraday_10641.csv.gz  in=193,190,876 out=19,025,600 elapsed=152.8s

  [1706/13157] intraday_10640.csv.gz  in=193,207,136 out=19,041,860 elapsed=152.8s

  [1707/13157] intraday_10642.csv.gz  in=193,220,454 out=19,055,178 elapsed=153.0s

  [1708/13157] intraday_10643.csv.gz  in=193,232,262 out=19,066,986 elapsed=153.0s

  [1709/13157] intraday_10645.csv.gz  in=193,243,910 out=19,078,634 elapsed=153.0s

  [1710/13157] intraday_10644.csv.gz  in=193,254,212 out=19,088,936 elapsed=153.0s

  [1711/13157] intraday_10649.csv.gz  in=193,264,678 out=19,099,402 elapsed=153.1s

  [1712/13157] intraday_10646.csv.gz  in=193,277,211 out=19,111,935 elapsed=153.1s

  [1713/13157] intraday_10647.csv.gz  in=193,287,056 out=19,121,780 elapsed=153.4s

  [1714/13157] intraday_1065.csv.gz  in=193,298,876 out=19,121,780 elapsed=153.4s

  [1715/13157] intraday_10648.csv.gz  in=193,312,841 out=19,135,745 elapsed=153.4s

  [1716/13157] intraday_10651.csv.gz  in=193,322,746 out=19,145,650 elapsed=153.5s

  [1717/13157] intraday_10650.csv.gz  in=193,334,023 out=19,156,927 elapsed=153.5s

  [1718/13157] intraday_10653.csv.gz  in=193,348,432 out=19,171,336 elapsed=153.5s

  [1719/13157] intraday_10652.csv.gz  in=193,362,194 out=19,185,098 elapsed=153.6s

  [1720/13157] intraday_10656.csv.gz  in=193,375,643 out=19,198,547 elapsed=153.8s

  [1721/13157] intraday_10657.csv.gz  in=193,388,455 out=19,211,359 elapsed=153.8s

  [1722/13157] intraday_10654.csv.gz  in=193,402,511 out=19,225,415 elapsed=153.8s

  [1723/13157] intraday_10655.csv.gz  in=193,413,663 out=19,236,567 elapsed=153.8s

  [1724/13157] intraday_10658.csv.gz  in=193,425,700 out=19,248,604 elapsed=153.8s

  [1725/13157] intraday_10661.csv.gz  in=193,437,002 out=19,259,906 elapsed=153.9s

  [1726/13157] intraday_10659.csv.gz  in=193,449,802 out=19,272,706 elapsed=153.9s

  [1727/13157] intraday_1066.csv.gz  in=193,464,481 out=19,272,706 elapsed=153.9s

  [1728/13157] intraday_10660.csv.gz  in=193,477,250 out=19,285,475 elapsed=153.9s

  [1729/13157] intraday_10662.csv.gz  in=193,488,414 out=19,296,639 elapsed=154.1s

  [1730/13157] intraday_10664.csv.gz  in=193,501,754 out=19,309,979 elapsed=154.1s

  [1731/13157] intraday_10663.csv.gz  in=193,512,112 out=19,320,337 elapsed=154.1s

  [1732/13157] intraday_10665.csv.gz  in=193,523,263 out=19,331,488 elapsed=154.1s

  [1733/13157] intraday_10666.csv.gz  in=193,534,241 out=19,342,466 elapsed=154.1s

  [1734/13157] intraday_10669.csv.gz  in=193,544,604 out=19,352,829 elapsed=154.2s

  [1735/13157] intraday_10668.csv.gz  in=193,553,430 out=19,361,655 elapsed=154.2s

  [1736/13157] intraday_10667.csv.gz  in=193,563,317 out=19,371,542 elapsed=154.2s

  [1737/13157] intraday_1067.csv.gz  in=193,575,117 out=19,371,542 elapsed=154.2s

  [1738/13157] intraday_10670.csv.gz  in=193,587,964 out=19,384,389 elapsed=154.2s

  [1739/13157] intraday_10673.csv.gz  in=193,599,253 out=19,395,678 elapsed=154.3s

  [1740/13157] intraday_10671.csv.gz  in=193,616,488 out=19,412,913 elapsed=154.3s

  [1741/13157] intraday_10674.csv.gz  in=193,627,678 out=19,424,103 elapsed=154.3s

  [1742/13157] intraday_10672.csv.gz  in=193,640,769 out=19,437,194 elapsed=154.3s

  [1743/13157] intraday_10675.csv.gz  in=193,653,839 out=19,450,264 elapsed=154.3s

  [1744/13157] intraday_10676.csv.gz  in=193,665,237 out=19,461,662 elapsed=154.3s

  [1745/13157] intraday_10677.csv.gz  in=193,679,459 out=19,475,884 elapsed=154.3s

  [1746/13157] intraday_10678.csv.gz  in=193,690,330 out=19,486,755 elapsed=154.4s

  [1747/13157] intraday_1068.csv.gz  in=193,707,393 out=19,486,755 elapsed=154.4s

  [1748/13157] intraday_10679.csv.gz  in=193,719,334 out=19,498,696 elapsed=154.4s

  [1749/13157] intraday_10680.csv.gz  in=193,730,541 out=19,509,903 elapsed=154.4s

  [1750/13157] intraday_10683.csv.gz  in=193,742,802 out=19,522,164 elapsed=155.0s

  [1751/13157] intraday_10681.csv.gz  in=193,755,938 out=19,535,300 elapsed=155.0s

  [1752/13157] intraday_10682.csv.gz  in=193,768,917 out=19,548,279 elapsed=155.0s

  [1753/13157] intraday_10684.csv.gz  in=193,781,291 out=19,560,653 elapsed=155.0s

  [1754/13157] intraday_10687.csv.gz  in=193,793,796 out=19,573,158 elapsed=155.4s

  [1755/13157] intraday_10686.csv.gz  in=193,805,295 out=19,584,657 elapsed=155.4s

  [1756/13157] intraday_10685.csv.gz  in=193,816,699 out=19,596,061 elapsed=155.6s

  [1757/13157] intraday_1069.csv.gz  in=193,829,634 out=19,596,061 elapsed=155.7s

  [1758/13157] intraday_10688.csv.gz  in=193,840,443 out=19,606,870 elapsed=155.7s

  [1759/13157] intraday_10692.csv.gz  in=193,851,350 out=19,617,777 elapsed=155.8s

  [1760/13157] intraday_10689.csv.gz  in=193,862,709 out=19,629,136 elapsed=155.8s

  [1761/13157] intraday_10691.csv.gz  in=193,875,750 out=19,642,177 elapsed=155.9s

  [1762/13157] intraday_10690.csv.gz  in=193,893,905 out=19,660,332 elapsed=156.0s

  [1763/13157] intraday_10693.csv.gz  in=193,905,003 out=19,671,430 elapsed=156.2s

  [1764/13157] intraday_10695.csv.gz  in=193,916,121 out=19,682,548 elapsed=156.2s

  [1765/13157] intraday_10694.csv.gz  in=193,930,799 out=19,697,226 elapsed=156.6s

  [1766/13157] intraday_10696.csv.gz  in=193,943,208 out=19,709,635 elapsed=156.7s

  [1767/13157] intraday_10697.csv.gz  in=193,955,324 out=19,721,751 elapsed=156.8s

  [1768/13157] intraday_10698.csv.gz  in=193,968,370 out=19,734,797 elapsed=156.8s

  [1769/13157] intraday_10699.csv.gz  in=193,978,838 out=19,745,265 elapsed=157.1s

  [1770/13157] intraday_10700.csv.gz  in=193,994,145 out=19,760,572 elapsed=157.5s

  [1771/13157] intraday_1070.csv.gz  in=194,009,802 out=19,760,572 elapsed=157.5s

  [1772/13157] intraday_10701.csv.gz  in=194,024,968 out=19,775,738 elapsed=157.5s

  [1773/13157] intraday_10702.csv.gz  in=194,037,499 out=19,788,269 elapsed=157.7s

  [1774/13157] intraday_10703.csv.gz  in=194,050,795 out=19,801,565 elapsed=157.8s

  [1775/13157] intraday_10707.csv.gz  in=194,064,559 out=19,815,329 elapsed=158.4s

  [1776/13157] intraday_10706.csv.gz  in=194,078,477 out=19,829,247 elapsed=158.4s

  [1777/13157] intraday_10704.csv.gz  in=194,094,033 out=19,844,803 elapsed=158.4s

  [1778/13157] intraday_10705.csv.gz  in=194,111,230 out=19,862,000 elapsed=158.4s

  [1779/13157] intraday_1071.csv.gz  in=194,121,152 out=19,862,000 elapsed=159.1s

  [1780/13157] intraday_10708.csv.gz  in=194,133,092 out=19,873,940 elapsed=159.7s

  [1781/13157] intraday_10710.csv.gz  in=194,142,869 out=19,883,717 elapsed=159.7s

  [1782/13157] intraday_10709.csv.gz  in=194,154,172 out=19,895,020 elapsed=159.8s

  [1783/13157] intraday_10711.csv.gz  in=194,166,657 out=19,907,505 elapsed=160.1s

  [1784/13157] intraday_10712.csv.gz  in=194,178,008 out=19,918,856 elapsed=160.3s

  [1785/13157] intraday_10713.csv.gz  in=194,190,629 out=19,931,477 elapsed=160.4s

  [1786/13157] intraday_10714.csv.gz  in=194,202,790 out=19,943,638 elapsed=160.4s

  [1787/13157] intraday_10715.csv.gz  in=194,217,638 out=19,958,486 elapsed=160.4s

  [1788/13157] intraday_10716.csv.gz  in=194,228,215 out=19,969,063 elapsed=160.4s

  [1789/13157] intraday_10717.csv.gz  in=194,239,198 out=19,980,046 elapsed=160.5s

  [1790/13157] intraday_10718.csv.gz  in=194,251,767 out=19,992,615 elapsed=160.6s

  [1791/13157] intraday_10719.csv.gz  in=194,263,025 out=20,003,873 elapsed=160.6s

  [1792/13157] intraday_1072.csv.gz  in=194,289,774 out=20,003,873 elapsed=160.8s

  [1793/13157] intraday_10720.csv.gz  in=194,301,410 out=20,015,509 elapsed=160.8s

  [1794/13157] intraday_10721.csv.gz  in=194,316,292 out=20,030,391 elapsed=160.8s

  [1795/13157] intraday_10722.csv.gz  in=194,331,243 out=20,045,342 elapsed=160.8s

  [1796/13157] intraday_10723.csv.gz  in=194,345,545 out=20,059,644 elapsed=160.9s

  [1797/13157] intraday_10724.csv.gz  in=194,361,273 out=20,075,372 elapsed=160.9s

  [1798/13157] intraday_10725.csv.gz  in=194,372,599 out=20,086,698 elapsed=160.9s

  [1799/13157] intraday_10726.csv.gz  in=194,383,023 out=20,097,122 elapsed=160.9s

  [1800/13157] intraday_10727.csv.gz  in=194,396,349 out=20,110,448 elapsed=161.0s

  [1801/13157] intraday_10728.csv.gz  in=194,407,066 out=20,121,165 elapsed=161.1s

  [1802/13157] intraday_1073.csv.gz  in=194,418,157 out=20,121,165 elapsed=161.1s

  [1803/13157] intraday_10730.csv.gz  in=194,424,376 out=20,127,384 elapsed=161.1s

  [1804/13157] intraday_10729.csv.gz  in=194,434,425 out=20,137,433 elapsed=161.1s

  [1805/13157] intraday_10734.csv.gz  in=194,434,426 out=20,137,434 elapsed=161.1s

  [1806/13157] intraday_10733.csv.gz  in=194,434,432 out=20,137,440 elapsed=161.1s

  [1807/13157] intraday_10736.csv.gz  in=194,434,436 out=20,137,444 elapsed=161.1s

  [1808/13157] intraday_10735.csv.gz  in=194,434,439 out=20,137,447 elapsed=161.1s

  [1809/13157] intraday_10737.csv.gz  in=194,434,446 out=20,137,454 elapsed=161.1s

  [1810/13157] intraday_10738.csv.gz  in=194,434,448 out=20,137,456 elapsed=161.1s

  [1811/13157] intraday_10739.csv.gz  in=194,434,449 out=20,137,457 elapsed=161.1s

  [1812/13157] intraday_10740.csv.gz  in=194,434,454 out=20,137,462 elapsed=161.1s

  [1813/13157] intraday_10741.csv.gz  in=194,434,457 out=20,137,465 elapsed=161.1s

  [1814/13157] intraday_10742.csv.gz  in=194,434,460 out=20,137,468 elapsed=161.1s

  [1815/13157] intraday_10743.csv.gz  in=194,434,463 out=20,137,471 elapsed=161.1s

  [1816/13157] intraday_10744.csv.gz  in=194,434,465 out=20,137,473 elapsed=161.1s

  [1817/13157] intraday_10745.csv.gz  in=194,436,721 out=20,139,729 elapsed=161.1s

  [1818/13157] intraday_10746.csv.gz  in=194,436,726 out=20,139,734 elapsed=161.2s

  [1819/13157] intraday_10731.csv.gz  in=194,446,309 out=20,149,317 elapsed=161.2s

  [1820/13157] intraday_10747.csv.gz  in=194,446,311 out=20,149,319 elapsed=161.2s

  [1821/13157] intraday_1074.csv.gz  in=194,462,752 out=20,149,319 elapsed=161.2s

  [1822/13157] intraday_10748.csv.gz  in=194,462,753 out=20,149,320 elapsed=161.2s

  [1823/13157] intraday_10749.csv.gz  in=194,462,755 out=20,149,322 elapsed=161.2s

  [1824/13157] intraday_10732.csv.gz  in=194,470,978 out=20,157,545 elapsed=161.2s

  [1825/13157] intraday_10750.csv.gz  in=194,470,980 out=20,157,547 elapsed=161.2s

  [1826/13157] intraday_10751.csv.gz  in=194,470,983 out=20,157,550 elapsed=161.2s

  [1827/13157] intraday_10752.csv.gz  in=194,470,984 out=20,157,551 elapsed=161.2s

  [1828/13157] intraday_10754.csv.gz  in=194,470,985 out=20,157,552 elapsed=161.2s

  [1829/13157] intraday_10753.csv.gz  in=194,471,153 out=20,157,720 elapsed=161.2s

  [1830/13157] intraday_1075.csv.gz  in=194,484,401 out=20,157,720 elapsed=161.2s

  [1831/13157] intraday_10755.csv.gz  in=194,484,402 out=20,157,721 elapsed=161.2s

  [1832/13157] intraday_10756.csv.gz  in=194,484,404 out=20,157,723 elapsed=161.2s

  [1833/13157] intraday_10757.csv.gz  in=194,484,407 out=20,157,726 elapsed=161.2s

  [1834/13157] intraday_10759.csv.gz  in=194,484,408 out=20,157,727 elapsed=161.2s

  [1835/13157] intraday_10761.csv.gz  in=194,484,411 out=20,157,730 elapsed=161.2s

  [1836/13157] intraday_10760.csv.gz  in=194,484,412 out=20,157,731 elapsed=161.3s

  [1837/13157] intraday_10762.csv.gz  in=194,484,414 out=20,157,733 elapsed=161.3s

  [1838/13157] intraday_10763.csv.gz  in=194,484,415 out=20,157,734 elapsed=161.3s

  [1839/13157] intraday_10765.csv.gz  in=194,484,416 out=20,157,735 elapsed=161.3s

  [1840/13157] intraday_10764.csv.gz  in=194,484,417 out=20,157,736 elapsed=161.3s

  [1841/13157] intraday_10766.csv.gz  in=194,484,418 out=20,157,737 elapsed=161.3s

  [1842/13157] intraday_10767.csv.gz  in=194,484,420 out=20,157,739 elapsed=161.3s

  [1843/13157] intraday_10768.csv.gz  in=194,484,440 out=20,157,759 elapsed=161.3s

  [1844/13157] intraday_10758.csv.gz  in=194,484,691 out=20,158,010 elapsed=161.3s

  [1845/13157] intraday_10770.csv.gz  in=194,484,695 out=20,158,014 elapsed=161.3s

  [1846/13157] intraday_10771.csv.gz  in=194,484,696 out=20,158,015 elapsed=161.3s

  [1847/13157] intraday_10769.csv.gz  in=194,487,749 out=20,161,068 elapsed=161.3s

  [1848/13157] intraday_10773.csv.gz  in=194,487,750 out=20,161,069 elapsed=161.3s

  [1849/13157] intraday_10772.csv.gz  in=194,487,751 out=20,161,070 elapsed=161.3s

  [1850/13157] intraday_10774.csv.gz  in=194,487,752 out=20,161,071 elapsed=161.3s

  [1851/13157] intraday_10775.csv.gz  in=194,487,758 out=20,161,077 elapsed=161.3s

  [1852/13157] intraday_10777.csv.gz  in=194,487,759 out=20,161,078 elapsed=161.3s

  [1853/13157] intraday_10776.csv.gz  in=194,487,763 out=20,161,082 elapsed=161.3s

  [1854/13157] intraday_10779.csv.gz  in=194,487,765 out=20,161,084 elapsed=161.4s

  [1855/13157] intraday_10778.csv.gz  in=194,487,769 out=20,161,088 elapsed=161.4s

  [1856/13157] intraday_10780.csv.gz  in=194,487,771 out=20,161,090 elapsed=161.4s

  [1857/13157] intraday_10781.csv.gz  in=194,487,772 out=20,161,091 elapsed=161.4s

  [1858/13157] intraday_10782.csv.gz  in=194,487,776 out=20,161,095 elapsed=161.4s

  [1859/13157] intraday_10783.csv.gz  in=194,487,777 out=20,161,096 elapsed=161.4s

  [1860/13157] intraday_10784.csv.gz  in=194,487,781 out=20,161,100 elapsed=161.4s

  [1861/13157] intraday_10785.csv.gz  in=194,487,782 out=20,161,101 elapsed=161.4s

  [1862/13157] intraday_10786.csv.gz  in=194,487,783 out=20,161,102 elapsed=161.4s

  [1863/13157] intraday_10787.csv.gz  in=194,487,825 out=20,161,144 elapsed=161.4s

  [1864/13157] intraday_10788.csv.gz  in=194,487,832 out=20,161,151 elapsed=161.4s

  [1865/13157] intraday_10789.csv.gz  in=194,487,836 out=20,161,155 elapsed=161.5s

  [1866/13157] intraday_1076.csv.gz  in=194,503,130 out=20,161,155 elapsed=161.6s

  [1867/13157] intraday_10790.csv.gz  in=194,503,132 out=20,161,157 elapsed=161.7s

  [1868/13157] intraday_1077.csv.gz  in=194,516,176 out=20,161,157 elapsed=161.7s

  [1869/13157] intraday_10791.csv.gz  in=194,516,181 out=20,161,162 elapsed=161.7s

  [1870/13157] intraday_10793.csv.gz  in=194,516,182 out=20,161,163 elapsed=161.7s

  [1871/13157] intraday_10794.csv.gz  in=194,516,185 out=20,161,166 elapsed=161.7s

  [1872/13157] intraday_10795.csv.gz  in=194,516,189 out=20,161,170 elapsed=161.7s

  [1873/13157] intraday_10796.csv.gz  in=194,516,190 out=20,161,171 elapsed=161.7s

  [1874/13157] intraday_10797.csv.gz  in=194,516,191 out=20,161,172 elapsed=161.7s

  [1875/13157] intraday_1078.csv.gz  in=194,528,913 out=20,161,172 elapsed=161.7s

  [1876/13157] intraday_10798.csv.gz  in=194,528,915 out=20,161,174 elapsed=161.7s

  [1877/13157] intraday_10799.csv.gz  in=194,528,917 out=20,161,176 elapsed=161.7s

  [1878/13157] intraday_10800.csv.gz  in=194,528,919 out=20,161,178 elapsed=161.7s

  [1879/13157] intraday_10801.csv.gz  in=194,528,921 out=20,161,180 elapsed=161.7s

  [1880/13157] intraday_10802.csv.gz  in=194,528,922 out=20,161,181 elapsed=161.7s

  [1881/13157] intraday_10803.csv.gz  in=194,528,925 out=20,161,184 elapsed=161.7s

  [1882/13157] intraday_10792.csv.gz  in=194,531,125 out=20,163,384 elapsed=161.7s

  [1883/13157] intraday_10805.csv.gz  in=194,531,128 out=20,163,387 elapsed=161.7s

  [1884/13157] intraday_10806.csv.gz  in=194,531,131 out=20,163,390 elapsed=161.7s

  [1885/13157] intraday_10807.csv.gz  in=194,531,132 out=20,163,391 elapsed=161.7s

  [1886/13157] intraday_10808.csv.gz  in=194,531,135 out=20,163,394 elapsed=161.7s

  [1887/13157] intraday_10809.csv.gz  in=194,531,136 out=20,163,395 elapsed=161.7s

  [1888/13157] intraday_10804.csv.gz  in=194,531,237 out=20,163,496 elapsed=161.9s

  [1889/13157] intraday_1080.csv.gz  in=194,544,144 out=20,163,496 elapsed=161.9s

  [1890/13157] intraday_1079.csv.gz  in=194,559,760 out=20,163,496 elapsed=161.9s

  [1891/13157] intraday_1081.csv.gz  in=194,572,966 out=20,163,496 elapsed=161.9s

  [1892/13157] intraday_10812.csv.gz  in=194,572,968 out=20,163,498 elapsed=161.9s

  [1893/13157] intraday_10811.csv.gz  in=194,572,971 out=20,163,501 elapsed=161.9s

  [1894/13157] intraday_10815.csv.gz  in=194,572,974 out=20,163,504 elapsed=161.9s

  [1895/13157] intraday_10813.csv.gz  in=194,572,977 out=20,163,507 elapsed=161.9s

  [1896/13157] intraday_10810.csv.gz  in=194,579,664 out=20,170,194 elapsed=162.0s

  [1897/13157] intraday_10814.csv.gz  in=194,579,976 out=20,170,506 elapsed=162.0s

  [1898/13157] intraday_10818.csv.gz  in=194,579,979 out=20,170,509 elapsed=162.0s

  [1899/13157] intraday_10819.csv.gz  in=194,579,987 out=20,170,517 elapsed=162.0s

  [1900/13157] intraday_10817.csv.gz  in=194,580,035 out=20,170,565 elapsed=162.0s

  [1901/13157] intraday_10816.csv.gz  in=194,583,656 out=20,174,186 elapsed=162.0s

  [1902/13157] intraday_10820.csv.gz  in=194,583,657 out=20,174,187 elapsed=162.0s

  [1903/13157] intraday_10821.csv.gz  in=194,583,658 out=20,174,188 elapsed=162.0s

  [1904/13157] intraday_10822.csv.gz  in=194,583,758 out=20,174,288 elapsed=162.0s

  [1905/13157] intraday_10824.csv.gz  in=194,583,763 out=20,174,293 elapsed=162.0s

  [1906/13157] intraday_1082.csv.gz  in=194,604,858 out=20,174,293 elapsed=162.0s

  [1907/13157] intraday_10823.csv.gz  in=194,604,861 out=20,174,296 elapsed=162.0s

  [1908/13157] intraday_10825.csv.gz  in=194,604,868 out=20,174,303 elapsed=162.0s

  [1909/13157] intraday_10826.csv.gz  in=194,604,881 out=20,174,316 elapsed=162.0s

  [1910/13157] intraday_10829.csv.gz  in=194,604,886 out=20,174,321 elapsed=162.0s

  [1911/13157] intraday_10827.csv.gz  in=194,604,888 out=20,174,323 elapsed=162.0s

  [1912/13157] intraday_10828.csv.gz  in=194,604,926 out=20,174,361 elapsed=162.0s

  [1913/13157] intraday_10830.csv.gz  in=194,604,933 out=20,174,368 elapsed=162.0s

  [1914/13157] intraday_10832.csv.gz  in=194,604,937 out=20,174,372 elapsed=162.0s

  [1915/13157] intraday_10831.csv.gz  in=194,604,943 out=20,174,378 elapsed=162.0s

  [1916/13157] intraday_10833.csv.gz  in=194,604,951 out=20,174,386 elapsed=162.1s

  [1917/13157] intraday_1083.csv.gz  in=194,618,847 out=20,174,386 elapsed=162.1s

  [1918/13157] intraday_10834.csv.gz  in=194,621,392 out=20,176,931 elapsed=162.1s

  [1919/13157] intraday_10835.csv.gz  in=194,621,653 out=20,177,192 elapsed=162.1s

  [1920/13157] intraday_10836.csv.gz  in=194,621,656 out=20,177,195 elapsed=162.1s

  [1921/13157] intraday_10837.csv.gz  in=194,621,658 out=20,177,197 elapsed=162.1s

  [1922/13157] intraday_10838.csv.gz  in=194,621,662 out=20,177,201 elapsed=162.1s

  [1923/13157] intraday_10839.csv.gz  in=194,621,695 out=20,177,234 elapsed=162.1s

  [1924/13157] intraday_10840.csv.gz  in=194,621,698 out=20,177,237 elapsed=162.1s

  [1925/13157] intraday_10841.csv.gz  in=194,621,699 out=20,177,238 elapsed=162.1s

  [1926/13157] intraday_10843.csv.gz  in=194,621,701 out=20,177,240 elapsed=162.1s

  [1927/13157] intraday_10842.csv.gz  in=194,621,710 out=20,177,249 elapsed=162.1s

  [1928/13157] intraday_1084.csv.gz  in=194,634,903 out=20,177,249 elapsed=162.1s

  [1929/13157] intraday_10845.csv.gz  in=194,634,908 out=20,177,254 elapsed=162.1s

  [1930/13157] intraday_10846.csv.gz  in=194,634,912 out=20,177,258 elapsed=162.1s

  [1931/13157] intraday_10847.csv.gz  in=194,634,916 out=20,177,262 elapsed=162.1s

  [1932/13157] intraday_10848.csv.gz  in=194,634,919 out=20,177,265 elapsed=162.1s

  [1933/13157] intraday_10844.csv.gz  in=194,635,237 out=20,177,583 elapsed=162.1s

  [1934/13157] intraday_10849.csv.gz  in=194,635,240 out=20,177,586 elapsed=162.1s

  [1935/13157] intraday_10850.csv.gz  in=194,635,243 out=20,177,589 elapsed=162.1s

  [1936/13157] intraday_10851.csv.gz  in=194,635,246 out=20,177,592 elapsed=162.1s

  [1937/13157] intraday_10852.csv.gz  in=194,635,261 out=20,177,607 elapsed=162.1s

  [1938/13157] intraday_10854.csv.gz  in=194,635,262 out=20,177,608 elapsed=162.2s

  [1939/13157] intraday_10853.csv.gz  in=194,635,266 out=20,177,612 elapsed=162.2s

  [1940/13157] intraday_10856.csv.gz  in=194,635,268 out=20,177,614 elapsed=162.2s

  [1941/13157] intraday_10855.csv.gz  in=194,635,273 out=20,177,619 elapsed=162.2s

  [1942/13157] intraday_10858.csv.gz  in=194,635,274 out=20,177,620 elapsed=162.2s

  [1943/13157] intraday_1085.csv.gz  in=194,648,447 out=20,177,620 elapsed=162.2s

  [1944/13157] intraday_10857.csv.gz  in=194,649,023 out=20,178,196 elapsed=162.2s

  [1945/13157] intraday_10859.csv.gz  in=194,649,682 out=20,178,855 elapsed=162.2s

  [1946/13157] intraday_10862.csv.gz  in=194,649,697 out=20,178,870 elapsed=162.2s

  [1947/13157] intraday_10861.csv.gz  in=194,649,997 out=20,179,170 elapsed=162.2s

  [1948/13157] intraday_10860.csv.gz  in=194,650,090 out=20,179,263 elapsed=162.2s

  [1949/13157] intraday_10863.csv.gz  in=194,650,108 out=20,179,281 elapsed=162.2s

  [1950/13157] intraday_1086.csv.gz  in=194,660,575 out=20,179,281 elapsed=162.2s

  [1951/13157] intraday_10864.csv.gz  in=194,661,350 out=20,180,056 elapsed=162.2s

  [1952/13157] intraday_10865.csv.gz  in=194,661,491 out=20,180,197 elapsed=162.2s

  [1953/13157] intraday_10866.csv.gz  in=194,662,583 out=20,181,289 elapsed=162.3s

  [1954/13157] intraday_10867.csv.gz  in=194,662,776 out=20,181,482 elapsed=162.3s

  [1955/13157] intraday_10869.csv.gz  in=194,663,190 out=20,181,896 elapsed=162.3s

  [1956/13157] intraday_10868.csv.gz  in=194,665,424 out=20,184,130 elapsed=162.3s

  [1957/13157] intraday_10871.csv.gz  in=194,665,666 out=20,184,372 elapsed=162.3s

  [1958/13157] intraday_10872.csv.gz  in=194,665,772 out=20,184,478 elapsed=162.3s

  [1959/13157] intraday_1087.csv.gz  in=194,679,067 out=20,184,478 elapsed=162.3s

  [1960/13157] intraday_10875.csv.gz  in=194,679,076 out=20,184,487 elapsed=162.3s

  [1961/13157] intraday_10873.csv.gz  in=194,679,151 out=20,184,562 elapsed=162.3s

  [1962/13157] intraday_10874.csv.gz  in=194,679,756 out=20,185,167 elapsed=162.3s

  [1963/13157] intraday_10876.csv.gz  in=194,683,451 out=20,188,862 elapsed=162.3s

  [1964/13157] intraday_10877.csv.gz  in=194,683,572 out=20,188,983 elapsed=162.3s

  [1965/13157] intraday_10879.csv.gz  in=194,683,665 out=20,189,076 elapsed=162.3s

  [1966/13157] intraday_10878.csv.gz  in=194,683,938 out=20,189,349 elapsed=162.3s

  [1967/13157] intraday_10880.csv.gz  in=194,683,982 out=20,189,393 elapsed=162.4s

  [1968/13157] intraday_1088.csv.gz  in=194,696,187 out=20,189,393 elapsed=162.4s

  [1969/13157] intraday_10870.csv.gz  in=194,709,084 out=20,202,290 elapsed=162.4s

  [1970/13157] intraday_10884.csv.gz  in=194,709,103 out=20,202,309 elapsed=162.4s

  [1971/13157] intraday_10883.csv.gz  in=194,709,503 out=20,202,709 elapsed=162.4s

  [1972/13157] intraday_10885.csv.gz  in=194,709,622 out=20,202,828 elapsed=162.4s

  [1973/13157] intraday_10881.csv.gz  in=194,710,899 out=20,204,105 elapsed=162.4s

  [1974/13157] intraday_10886.csv.gz  in=194,710,912 out=20,204,118 elapsed=162.4s

  [1975/13157] intraday_10882.csv.gz  in=194,714,385 out=20,207,591 elapsed=162.4s

  [1976/13157] intraday_10888.csv.gz  in=194,714,946 out=20,208,152 elapsed=162.5s

  [1977/13157] intraday_10887.csv.gz  in=194,715,047 out=20,208,253 elapsed=162.5s

  [1978/13157] intraday_10889.csv.gz  in=194,715,173 out=20,208,379 elapsed=162.5s

  [1979/13157] intraday_1089.csv.gz  in=194,726,057 out=20,208,379 elapsed=162.5s

  [1980/13157] intraday_10890.csv.gz  in=194,726,199 out=20,208,521 elapsed=162.5s

  [1981/13157] intraday_10892.csv.gz  in=194,726,344 out=20,208,666 elapsed=162.5s

  [1982/13157] intraday_10891.csv.gz  in=194,726,655 out=20,208,977 elapsed=162.5s

  [1983/13157] intraday_10893.csv.gz  in=194,726,791 out=20,209,113 elapsed=162.5s

  [1984/13157] intraday_10894.csv.gz  in=194,726,882 out=20,209,204 elapsed=162.5s

  [1985/13157] intraday_10896.csv.gz  in=194,726,908 out=20,209,230 elapsed=162.5s

  [1986/13157] intraday_10897.csv.gz  in=194,727,052 out=20,209,374 elapsed=162.5s

  [1987/13157] intraday_10895.csv.gz  in=194,727,316 out=20,209,638 elapsed=162.5s

  [1988/13157] intraday_10898.csv.gz  in=194,729,147 out=20,211,469 elapsed=162.6s

  [1989/13157] intraday_10899.csv.gz  in=194,729,450 out=20,211,772 elapsed=162.6s

  [1990/13157] intraday_1090.csv.gz  in=194,737,255 out=20,211,772 elapsed=162.6s

  [1991/13157] intraday_10900.csv.gz  in=194,737,289 out=20,211,806 elapsed=162.6s

  [1992/13157] intraday_10904.csv.gz  in=194,737,291 out=20,211,808 elapsed=162.6s

  [1993/13157] intraday_10902.csv.gz  in=194,737,321 out=20,211,838 elapsed=162.6s

  [1994/13157] intraday_10903.csv.gz  in=194,737,333 out=20,211,850 elapsed=162.6s

  [1995/13157] intraday_10905.csv.gz  in=194,737,342 out=20,211,859 elapsed=162.6s

  [1996/13157] intraday_10901.csv.gz  in=194,738,208 out=20,212,725 elapsed=163.0s

  [1997/13157] intraday_10907.csv.gz  in=194,738,910 out=20,213,427 elapsed=163.0s

  [1998/13157] intraday_10909.csv.gz  in=194,738,919 out=20,213,436 elapsed=163.0s

  [1999/13157] intraday_10906.csv.gz  in=194,739,097 out=20,213,614 elapsed=163.4s

  [2000/13157] intraday_10910.csv.gz  in=194,739,152 out=20,213,669 elapsed=163.4s

  [2001/13157] intraday_10908.csv.gz  in=194,741,333 out=20,215,850 elapsed=163.4s

  [2002/13157] intraday_1091.csv.gz  in=194,753,787 out=20,215,850 elapsed=163.4s

  [2003/13157] intraday_10911.csv.gz  in=194,769,752 out=20,231,815 elapsed=163.7s

  [2004/13157] intraday_10914.csv.gz  in=194,779,954 out=20,242,017 elapsed=163.8s

  [2005/13157] intraday_10912.csv.gz  in=194,791,616 out=20,253,679 elapsed=163.8s

  [2006/13157] intraday_10915.csv.gz  in=194,803,542 out=20,265,605 elapsed=163.9s

  [2007/13157] intraday_10913.csv.gz  in=194,817,387 out=20,279,450 elapsed=163.9s

  [2008/13157] intraday_10916.csv.gz  in=194,831,278 out=20,293,341 elapsed=163.9s

  [2009/13157] intraday_10918.csv.gz  in=194,842,377 out=20,304,440 elapsed=163.9s

  [2010/13157] intraday_10919.csv.gz  in=194,853,479 out=20,315,542 elapsed=163.9s

  [2011/13157] intraday_1092.csv.gz  in=194,859,790 out=20,315,542 elapsed=163.9s

  [2012/13157] intraday_10917.csv.gz  in=194,874,308 out=20,330,060 elapsed=163.9s

  [2013/13157] intraday_10922.csv.gz  in=194,885,131 out=20,340,883 elapsed=164.0s

  [2014/13157] intraday_10921.csv.gz  in=194,898,057 out=20,353,809 elapsed=164.0s

  [2015/13157] intraday_10920.csv.gz  in=194,911,528 out=20,367,280 elapsed=164.0s

  [2016/13157] intraday_10923.csv.gz  in=194,924,696 out=20,380,448 elapsed=164.0s

  [2017/13157] intraday_10925.csv.gz  in=194,933,936 out=20,389,688 elapsed=164.2s

  [2018/13157] intraday_10927.csv.gz  in=194,948,232 out=20,403,984 elapsed=164.3s

  [2019/13157] intraday_10926.csv.gz  in=194,958,382 out=20,414,134 elapsed=164.3s

  [2020/13157] intraday_10924.csv.gz  in=194,973,460 out=20,429,212 elapsed=164.3s

  [2021/13157] intraday_10928.csv.gz  in=194,987,891 out=20,443,643 elapsed=164.3s

  [2022/13157] intraday_10929.csv.gz  in=195,000,206 out=20,455,958 elapsed=164.3s

  [2023/13157] intraday_10930.csv.gz  in=195,010,550 out=20,466,302 elapsed=164.5s

  [2024/13157] intraday_1093.csv.gz  in=195,025,419 out=20,466,302 elapsed=164.5s

  [2025/13157] intraday_10932.csv.gz  in=195,042,065 out=20,482,948 elapsed=164.5s

  [2026/13157] intraday_10931.csv.gz  in=195,053,385 out=20,494,268 elapsed=164.6s

  [2027/13157] intraday_10934.csv.gz  in=195,066,015 out=20,506,898 elapsed=164.6s

  [2028/13157] intraday_10933.csv.gz  in=195,077,482 out=20,518,365 elapsed=164.6s

  [2029/13157] intraday_10935.csv.gz  in=195,089,998 out=20,530,881 elapsed=164.6s

  [2030/13157] intraday_10936.csv.gz  in=195,100,659 out=20,541,542 elapsed=164.6s

  [2031/13157] intraday_10937.csv.gz  in=195,123,385 out=20,564,268 elapsed=164.7s

  [2032/13157] intraday_10939.csv.gz  in=195,133,849 out=20,574,732 elapsed=164.7s

  [2033/13157] intraday_1094.csv.gz  in=195,148,637 out=20,574,732 elapsed=164.7s

  [2034/13157] intraday_10938.csv.gz  in=195,159,395 out=20,585,490 elapsed=164.8s

  [2035/13157] intraday_10940.csv.gz  in=195,172,591 out=20,598,686 elapsed=164.8s

  [2036/13157] intraday_10941.csv.gz  in=195,187,708 out=20,613,803 elapsed=164.8s

  [2037/13157] intraday_10942.csv.gz  in=195,201,341 out=20,627,436 elapsed=164.8s

  [2038/13157] intraday_10943.csv.gz  in=195,210,527 out=20,636,622 elapsed=164.8s

  [2039/13157] intraday_10944.csv.gz  in=195,221,468 out=20,647,563 elapsed=165.0s

  [2040/13157] intraday_10945.csv.gz  in=195,235,083 out=20,661,178 elapsed=165.0s

  [2041/13157] intraday_10946.csv.gz  in=195,246,024 out=20,672,119 elapsed=165.0s

  [2042/13157] intraday_10947.csv.gz  in=195,256,968 out=20,683,063 elapsed=165.0s

  [2043/13157] intraday_1095.csv.gz  in=195,268,907 out=20,683,063 elapsed=165.1s

  [2044/13157] intraday_10949.csv.gz  in=195,279,407 out=20,693,563 elapsed=165.1s

  [2045/13157] intraday_10950.csv.gz  in=195,289,345 out=20,703,501 elapsed=165.2s

  [2046/13157] intraday_10948.csv.gz  in=195,301,260 out=20,715,416 elapsed=165.2s

  [2047/13157] intraday_10952.csv.gz  in=195,311,885 out=20,726,041 elapsed=165.2s

  [2048/13157] intraday_10951.csv.gz  in=195,321,776 out=20,735,932 elapsed=165.2s

  [2049/13157] intraday_10953.csv.gz  in=195,335,037 out=20,749,193 elapsed=165.2s

  [2050/13157] intraday_10956.csv.gz  in=195,346,343 out=20,760,499 elapsed=165.2s

  [2051/13157] intraday_10955.csv.gz  in=195,360,619 out=20,774,775 elapsed=165.3s

  [2052/13157] intraday_10954.csv.gz  in=195,372,863 out=20,787,019 elapsed=165.3s

  [2053/13157] intraday_1096.csv.gz  in=195,384,437 out=20,787,019 elapsed=165.3s

  [2054/13157] intraday_10957.csv.gz  in=195,394,747 out=20,797,329 elapsed=165.3s

  [2055/13157] intraday_10959.csv.gz  in=195,406,230 out=20,808,812 elapsed=165.3s

  [2056/13157] intraday_10958.csv.gz  in=195,417,949 out=20,820,531 elapsed=165.3s

  [2057/13157] intraday_10961.csv.gz  in=195,429,246 out=20,831,828 elapsed=165.4s

  [2058/13157] intraday_10962.csv.gz  in=195,439,651 out=20,842,233 elapsed=165.4s

  [2059/13157] intraday_10963.csv.gz  in=195,451,297 out=20,853,879 elapsed=165.4s

  [2060/13157] intraday_10964.csv.gz  in=195,462,415 out=20,864,997 elapsed=165.4s

  [2061/13157] intraday_10960.csv.gz  in=195,472,037 out=20,874,619 elapsed=165.4s

  [2062/13157] intraday_10965.csv.gz  in=195,485,603 out=20,888,185 elapsed=165.4s

  [2063/13157] intraday_10967.csv.gz  in=195,499,018 out=20,901,600 elapsed=165.5s

  [2064/13157] intraday_10969.csv.gz  in=195,508,545 out=20,911,127 elapsed=165.6s

  [2065/13157] intraday_10966.csv.gz  in=195,521,625 out=20,924,207 elapsed=165.6s

  [2066/13157] intraday_10968.csv.gz  in=195,549,112 out=20,951,694 elapsed=165.6s

  [2067/13157] intraday_1097.csv.gz  in=195,564,167 out=20,951,694 elapsed=165.7s

  [2068/13157] intraday_10970.csv.gz  in=195,576,398 out=20,963,925 elapsed=165.7s

  [2069/13157] intraday_10972.csv.gz  in=195,586,498 out=20,974,025 elapsed=165.8s

  [2070/13157] intraday_10973.csv.gz  in=195,599,554 out=20,987,081 elapsed=165.8s

  [2071/13157] intraday_10971.csv.gz  in=195,612,234 out=20,999,761 elapsed=165.8s

  [2072/13157] intraday_10974.csv.gz  in=195,623,176 out=21,010,703 elapsed=165.9s

  [2073/13157] intraday_10975.csv.gz  in=195,633,783 out=21,021,310 elapsed=165.9s

  [2074/13157] intraday_10976.csv.gz  in=195,644,289 out=21,031,816 elapsed=165.9s

  [2075/13157] intraday_10977.csv.gz  in=195,659,010 out=21,046,537 elapsed=165.9s

  [2076/13157] intraday_10980.csv.gz  in=195,671,231 out=21,058,758 elapsed=166.1s

  [2077/13157] intraday_1098.csv.gz  in=195,685,775 out=21,058,758 elapsed=166.2s

  [2078/13157] intraday_10979.csv.gz  in=195,698,887 out=21,071,870 elapsed=166.2s

  [2079/13157] intraday_10978.csv.gz  in=195,715,464 out=21,088,447 elapsed=166.2s

  [2080/13157] intraday_10981.csv.gz  in=195,727,336 out=21,100,319 elapsed=166.2s

  [2081/13157] intraday_10982.csv.gz  in=195,738,435 out=21,111,418 elapsed=166.2s

  [2082/13157] intraday_10983.csv.gz  in=195,750,840 out=21,123,823 elapsed=166.2s

  [2083/13157] intraday_10985.csv.gz  in=195,763,224 out=21,136,207 elapsed=166.4s

  [2084/13157] intraday_10984.csv.gz  in=195,778,235 out=21,151,218 elapsed=166.5s

  [2085/13157] intraday_10986.csv.gz  in=195,788,900 out=21,161,883 elapsed=166.5s

  [2086/13157] intraday_10987.csv.gz  in=195,801,706 out=21,174,689 elapsed=166.5s

  [2087/13157] intraday_1099.csv.gz  in=195,813,562 out=21,174,689 elapsed=166.5s

  [2088/13157] intraday_10988.csv.gz  in=195,824,079 out=21,185,206 elapsed=166.5s

  [2089/13157] intraday_10990.csv.gz  in=195,834,197 out=21,195,324 elapsed=166.6s

  [2090/13157] intraday_10989.csv.gz  in=195,847,436 out=21,208,563 elapsed=166.6s

  [2091/13157] intraday_10993.csv.gz  in=195,856,113 out=21,217,240 elapsed=166.8s

  [2092/13157] intraday_10991.csv.gz  in=195,868,214 out=21,229,341 elapsed=166.9s

  [2093/13157] intraday_10992.csv.gz  in=195,885,108 out=21,246,235 elapsed=166.9s

  [2094/13157] intraday_10994.csv.gz  in=195,896,714 out=21,257,841 elapsed=166.9s

  [2095/13157] intraday_10995.csv.gz  in=195,909,785 out=21,270,912 elapsed=167.0s

  [2096/13157] intraday_10998.csv.gz  in=195,921,444 out=21,282,571 elapsed=167.0s

  [2097/13157] intraday_10996.csv.gz  in=195,943,558 out=21,304,685 elapsed=167.0s

  [2098/13157] intraday_1100.csv.gz  in=195,956,238 out=21,304,685 elapsed=167.1s

  [2099/13157] intraday_10997.csv.gz  in=195,967,490 out=21,315,937 elapsed=167.1s

  [2100/13157] intraday_10999.csv.gz  in=195,983,560 out=21,332,007 elapsed=167.1s

  [2101/13157] intraday_11000.csv.gz  in=195,997,140 out=21,345,587 elapsed=167.2s

  [2102/13157] intraday_11003.csv.gz  in=196,008,312 out=21,356,759 elapsed=167.3s

  [2103/13157] intraday_11001.csv.gz  in=196,019,187 out=21,367,634 elapsed=167.3s

  [2104/13157] intraday_11002.csv.gz  in=196,035,121 out=21,383,568 elapsed=167.4s

  [2105/13157] intraday_11007.csv.gz  in=196,048,044 out=21,396,491 elapsed=167.4s

  [2106/13157] intraday_11006.csv.gz  in=196,061,359 out=21,409,806 elapsed=167.6s

  [2107/13157] intraday_11005.csv.gz  in=196,074,112 out=21,422,559 elapsed=167.6s

  [2108/13157] intraday_11008.csv.gz  in=196,085,332 out=21,433,779 elapsed=167.6s

  [2109/13157] intraday_11004.csv.gz  in=196,111,150 out=21,459,597 elapsed=167.7s

  [2110/13157] intraday_11009.csv.gz  in=196,124,476 out=21,472,923 elapsed=167.7s

  [2111/13157] intraday_1101.csv.gz  in=196,138,657 out=21,472,923 elapsed=167.7s

  [2112/13157] intraday_11010.csv.gz  in=196,150,327 out=21,484,593 elapsed=167.7s

  [2113/13157] intraday_11011.csv.gz  in=196,162,485 out=21,496,751 elapsed=167.7s

  [2114/13157] intraday_11013.csv.gz  in=196,173,609 out=21,507,875 elapsed=167.7s

  [2115/13157] intraday_11014.csv.gz  in=196,185,712 out=21,519,978 elapsed=167.8s

  [2116/13157] intraday_11012.csv.gz  in=196,197,830 out=21,532,096 elapsed=167.8s

  [2117/13157] intraday_11015.csv.gz  in=196,212,256 out=21,546,522 elapsed=167.8s

  [2118/13157] intraday_11016.csv.gz  in=196,224,591 out=21,558,857 elapsed=167.8s

  [2119/13157] intraday_11017.csv.gz  in=196,236,357 out=21,570,623 elapsed=167.8s

  [2120/13157] intraday_1102.csv.gz  in=196,251,206 out=21,570,623 elapsed=167.8s

  [2121/13157] intraday_11018.csv.gz  in=196,263,625 out=21,583,042 elapsed=167.9s

  [2122/13157] intraday_11019.csv.gz  in=196,277,312 out=21,596,729 elapsed=167.9s

  [2123/13157] intraday_11020.csv.gz  in=196,289,202 out=21,608,619 elapsed=167.9s

  [2124/13157] intraday_11022.csv.gz  in=196,299,849 out=21,619,266 elapsed=167.9s

  [2125/13157] intraday_11023.csv.gz  in=196,313,402 out=21,632,819 elapsed=167.9s

  [2126/13157] intraday_11024.csv.gz  in=196,325,352 out=21,644,769 elapsed=168.0s

  [2127/13157] intraday_11021.csv.gz  in=196,338,716 out=21,658,133 elapsed=168.0s

  [2128/13157] intraday_11025.csv.gz  in=196,352,312 out=21,671,729 elapsed=168.0s

  [2129/13157] intraday_11026.csv.gz  in=196,373,880 out=21,693,297 elapsed=168.0s

  [2130/13157] intraday_1103.csv.gz  in=196,384,602 out=21,693,297 elapsed=168.4s

  [2131/13157] intraday_11027.csv.gz  in=196,400,371 out=21,709,066 elapsed=168.4s

  [2132/13157] intraday_11028.csv.gz  in=196,416,115 out=21,724,810 elapsed=168.7s

  [2133/13157] intraday_11029.csv.gz  in=196,431,363 out=21,740,058 elapsed=168.7s

  [2134/13157] intraday_11032.csv.gz  in=196,444,762 out=21,753,457 elapsed=169.3s

  [2135/13157] intraday_11033.csv.gz  in=196,456,791 out=21,765,486 elapsed=169.3s

  [2136/13157] intraday_11030.csv.gz  in=196,473,370 out=21,782,065 elapsed=169.3s

  [2137/13157] intraday_11031.csv.gz  in=196,490,462 out=21,799,157 elapsed=169.3s

  [2138/13157] intraday_11035.csv.gz  in=196,500,867 out=21,809,562 elapsed=169.4s

  [2139/13157] intraday_11034.csv.gz  in=196,511,987 out=21,820,682 elapsed=169.4s

  [2140/13157] intraday_11037.csv.gz  in=196,522,678 out=21,831,373 elapsed=169.4s

  [2141/13157] intraday_11036.csv.gz  in=196,536,094 out=21,844,789 elapsed=169.4s

  [2142/13157] intraday_1104.csv.gz  in=196,548,779 out=21,844,789 elapsed=169.6s

  [2143/13157] intraday_11038.csv.gz  in=196,561,769 out=21,857,779 elapsed=169.6s

  [2144/13157] intraday_11039.csv.gz  in=196,575,204 out=21,871,214 elapsed=169.6s

  [2145/13157] intraday_11040.csv.gz  in=196,591,853 out=21,887,863 elapsed=169.7s

  [2146/13157] intraday_11043.csv.gz  in=196,604,557 out=21,900,567 elapsed=169.8s

  [2147/13157] intraday_11041.csv.gz  in=196,614,785 out=21,910,795 elapsed=170.2s

  [2148/13157] intraday_11042.csv.gz  in=196,625,020 out=21,921,030 elapsed=170.2s

  [2149/13157] intraday_11044.csv.gz  in=196,636,694 out=21,932,704 elapsed=170.4s

  [2150/13157] intraday_11045.csv.gz  in=196,648,038 out=21,944,048 elapsed=170.5s

  [2151/13157] intraday_11046.csv.gz  in=196,663,993 out=21,960,003 elapsed=170.5s

  [2152/13157] intraday_11048.csv.gz  in=196,677,578 out=21,973,588 elapsed=170.5s

  [2153/13157] intraday_11047.csv.gz  in=196,693,462 out=21,989,472 elapsed=170.5s

  [2154/13157] intraday_11049.csv.gz  in=196,708,220 out=22,004,230 elapsed=170.7s

  [2155/13157] intraday_1105.csv.gz  in=196,723,537 out=22,004,230 elapsed=170.7s

  [2156/13157] intraday_11050.csv.gz  in=196,734,744 out=22,015,437 elapsed=170.7s

  [2157/13157] intraday_11051.csv.gz  in=196,746,548 out=22,027,241 elapsed=170.7s

  [2158/13157] intraday_11053.csv.gz  in=196,758,935 out=22,039,628 elapsed=170.7s

  [2159/13157] intraday_11052.csv.gz  in=196,771,048 out=22,051,741 elapsed=170.7s

  [2160/13157] intraday_11054.csv.gz  in=196,780,795 out=22,061,488 elapsed=171.0s

  [2161/13157] intraday_11055.csv.gz  in=196,787,001 out=22,067,694 elapsed=171.0s

  [2162/13157] intraday_11057.csv.gz  in=196,793,217 out=22,073,910 elapsed=171.0s

  [2163/13157] intraday_11056.csv.gz  in=196,803,809 out=22,084,502 elapsed=171.0s

  [2164/13157] intraday_11059.csv.gz  in=196,814,831 out=22,095,524 elapsed=171.0s

  [2165/13157] intraday_1106.csv.gz  in=196,826,209 out=22,095,524 elapsed=171.1s

  [2166/13157] intraday_11061.csv.gz  in=196,836,546 out=22,105,861 elapsed=171.1s

  [2167/13157] intraday_11058.csv.gz  in=196,850,579 out=22,119,894 elapsed=171.1s

  [2168/13157] intraday_11060.csv.gz  in=196,864,775 out=22,134,090 elapsed=171.1s

  [2169/13157] intraday_11062.csv.gz  in=196,876,602 out=22,145,917 elapsed=171.1s

  [2170/13157] intraday_11063.csv.gz  in=196,889,235 out=22,158,550 elapsed=171.1s

  [2171/13157] intraday_11066.csv.gz  in=196,900,533 out=22,169,848 elapsed=171.2s

  [2172/13157] intraday_11065.csv.gz  in=196,910,946 out=22,180,261 elapsed=171.2s

  [2173/13157] intraday_11064.csv.gz  in=196,924,369 out=22,193,684 elapsed=171.2s

  [2174/13157] intraday_11067.csv.gz  in=196,937,330 out=22,206,645 elapsed=171.2s

  [2175/13157] intraday_1107.csv.gz  in=196,947,494 out=22,206,645 elapsed=171.2s

  [2176/13157] intraday_11068.csv.gz  in=196,960,003 out=22,219,154 elapsed=171.2s

  [2177/13157] intraday_11069.csv.gz  in=196,970,341 out=22,229,492 elapsed=171.2s

  [2178/13157] intraday_11070.csv.gz  in=196,982,600 out=22,241,751 elapsed=171.3s

  [2179/13157] intraday_11073.csv.gz  in=196,993,031 out=22,252,182 elapsed=171.3s

  [2180/13157] intraday_11072.csv.gz  in=197,003,540 out=22,262,691 elapsed=171.3s

  [2181/13157] intraday_11071.csv.gz  in=197,016,252 out=22,275,403 elapsed=171.3s

  [2182/13157] intraday_11077.csv.gz  in=197,026,010 out=22,285,161 elapsed=171.4s

  [2183/13157] intraday_11074.csv.gz  in=197,039,211 out=22,298,362 elapsed=171.4s

  [2184/13157] intraday_11075.csv.gz  in=197,051,520 out=22,310,671 elapsed=171.4s

  [2185/13157] intraday_11076.csv.gz  in=197,063,688 out=22,322,839 elapsed=171.4s

  [2186/13157] intraday_11078.csv.gz  in=197,075,025 out=22,334,176 elapsed=171.4s

  [2187/13157] intraday_1108.csv.gz  in=197,088,079 out=22,334,176 elapsed=171.5s

  [2188/13157] intraday_11079.csv.gz  in=197,099,154 out=22,345,251 elapsed=171.5s

  [2189/13157] intraday_11081.csv.gz  in=197,110,952 out=22,357,049 elapsed=171.5s

  [2190/13157] intraday_11080.csv.gz  in=197,123,160 out=22,369,257 elapsed=171.5s

  [2191/13157] intraday_11083.csv.gz  in=197,134,229 out=22,380,326 elapsed=171.5s

  [2192/13157] intraday_11082.csv.gz  in=197,147,180 out=22,393,277 elapsed=171.5s

  [2193/13157] intraday_11085.csv.gz  in=197,157,897 out=22,403,994 elapsed=171.6s

  [2194/13157] intraday_11084.csv.gz  in=197,171,120 out=22,417,217 elapsed=171.6s

  [2195/13157] intraday_11086.csv.gz  in=197,181,362 out=22,427,459 elapsed=171.6s

  [2196/13157] intraday_11087.csv.gz  in=197,194,662 out=22,440,759 elapsed=171.6s

  [2197/13157] intraday_11088.csv.gz  in=197,209,464 out=22,455,561 elapsed=171.6s

  [2198/13157] intraday_11089.csv.gz  in=197,222,850 out=22,468,947 elapsed=171.6s

  [2199/13157] intraday_1109.csv.gz  in=197,235,501 out=22,468,947 elapsed=171.6s

  [2200/13157] intraday_11090.csv.gz  in=197,244,830 out=22,478,276 elapsed=171.6s

  [2201/13157] intraday_11091.csv.gz  in=197,254,308 out=22,487,754 elapsed=171.7s

  [2202/13157] intraday_11092.csv.gz  in=197,266,001 out=22,499,447 elapsed=171.7s

  [2203/13157] intraday_11093.csv.gz  in=197,278,927 out=22,512,373 elapsed=171.7s

  [2204/13157] intraday_11094.csv.gz  in=197,289,094 out=22,522,540 elapsed=171.7s

  [2205/13157] intraday_11095.csv.gz  in=197,300,211 out=22,533,657 elapsed=171.9s

  [2206/13157] intraday_11097.csv.gz  in=197,309,056 out=22,542,502 elapsed=171.9s

  [2207/13157] intraday_11098.csv.gz  in=197,319,047 out=22,552,493 elapsed=171.9s

  [2208/13157] intraday_1110.csv.gz  in=197,338,857 out=22,552,493 elapsed=172.0s

  [2209/13157] intraday_11096.csv.gz  in=197,350,004 out=22,563,640 elapsed=172.1s

  [2210/13157] intraday_11100.csv.gz  in=197,363,193 out=22,576,829 elapsed=172.1s

  [2211/13157] intraday_11099.csv.gz  in=197,373,711 out=22,587,347 elapsed=172.1s

  [2212/13157] intraday_11102.csv.gz  in=197,386,487 out=22,600,123 elapsed=172.3s

  [2213/13157] intraday_11101.csv.gz  in=197,399,364 out=22,613,000 elapsed=172.3s

  [2214/13157] intraday_11104.csv.gz  in=197,409,426 out=22,623,062 elapsed=172.4s

  [2215/13157] intraday_11103.csv.gz  in=197,421,528 out=22,635,164 elapsed=172.4s

  [2216/13157] intraday_11106.csv.gz  in=197,433,784 out=22,647,420 elapsed=172.4s

  [2217/13157] intraday_11105.csv.gz  in=197,445,117 out=22,658,753 elapsed=172.6s

  [2218/13157] intraday_11109.csv.gz  in=197,455,726 out=22,669,362 elapsed=172.6s

  [2219/13157] intraday_11108.csv.gz  in=197,467,242 out=22,680,878 elapsed=172.6s

  [2220/13157] intraday_11107.csv.gz  in=197,475,447 out=22,689,083 elapsed=172.6s

  [2221/13157] intraday_11110.csv.gz  in=197,486,147 out=22,699,783 elapsed=172.6s

  [2222/13157] intraday_1111.csv.gz  in=197,497,797 out=22,699,783 elapsed=172.7s

  [2223/13157] intraday_11111.csv.gz  in=197,509,990 out=22,711,976 elapsed=172.7s

  [2224/13157] intraday_11112.csv.gz  in=197,522,306 out=22,724,292 elapsed=172.7s

  [2225/13157] intraday_11113.csv.gz  in=197,534,155 out=22,736,141 elapsed=172.7s

  [2226/13157] intraday_11116.csv.gz  in=197,543,304 out=22,745,290 elapsed=172.7s

  [2227/13157] intraday_11114.csv.gz  in=197,555,395 out=22,757,381 elapsed=172.7s

  [2228/13157] intraday_11119.csv.gz  in=197,565,876 out=22,767,862 elapsed=172.8s

  [2229/13157] intraday_11115.csv.gz  in=197,578,618 out=22,780,604 elapsed=172.8s

  [2230/13157] intraday_11117.csv.gz  in=197,591,630 out=22,793,616 elapsed=172.8s

  [2231/13157] intraday_1112.csv.gz  in=197,602,844 out=22,793,616 elapsed=172.9s

  [2232/13157] intraday_11118.csv.gz  in=197,614,472 out=22,805,244 elapsed=172.9s

  [2233/13157] intraday_11120.csv.gz  in=197,626,390 out=22,817,162 elapsed=172.9s

  [2234/13157] intraday_11121.csv.gz  in=197,636,720 out=22,827,492 elapsed=172.9s

  [2235/13157] intraday_11122.csv.gz  in=197,646,271 out=22,837,043 elapsed=172.9s

  [2236/13157] intraday_11123.csv.gz  in=197,657,164 out=22,847,936 elapsed=172.9s

  [2237/13157] intraday_11126.csv.gz  in=197,670,273 out=22,861,045 elapsed=173.1s

  [2238/13157] intraday_11125.csv.gz  in=197,682,923 out=22,873,695 elapsed=173.1s

  [2239/13157] intraday_11124.csv.gz  in=197,698,870 out=22,889,642 elapsed=173.1s

  [2240/13157] intraday_11127.csv.gz  in=197,710,324 out=22,901,096 elapsed=173.1s

  [2241/13157] intraday_11128.csv.gz  in=197,721,748 out=22,912,520 elapsed=173.1s

  [2242/13157] intraday_1113.csv.gz  in=197,739,325 out=22,912,520 elapsed=173.3s

  [2243/13157] intraday_11131.csv.gz  in=197,752,291 out=22,925,486 elapsed=173.3s

  [2244/13157] intraday_11130.csv.gz  in=197,763,781 out=22,936,976 elapsed=173.3s

  [2245/13157] intraday_11129.csv.gz  in=197,774,871 out=22,948,066 elapsed=173.3s

  [2246/13157] intraday_11133.csv.gz  in=197,785,420 out=22,958,615 elapsed=173.4s

  [2247/13157] intraday_11132.csv.gz  in=197,798,214 out=22,971,409 elapsed=173.4s

  [2248/13157] intraday_11134.csv.gz  in=197,808,137 out=22,981,332 elapsed=173.4s

  [2249/13157] intraday_11135.csv.gz  in=197,819,243 out=22,992,438 elapsed=173.4s

  [2250/13157] intraday_11136.csv.gz  in=197,832,492 out=23,005,687 elapsed=173.4s

  [2251/13157] intraday_11137.csv.gz  in=197,842,332 out=23,015,527 elapsed=173.4s

  [2252/13157] intraday_1114.csv.gz  in=197,855,247 out=23,015,527 elapsed=173.7s

  [2253/13157] intraday_11139.csv.gz  in=197,863,725 out=23,024,005 elapsed=173.7s

  [2254/13157] intraday_11138.csv.gz  in=197,873,909 out=23,034,189 elapsed=173.7s

  [2255/13157] intraday_11140.csv.gz  in=197,883,166 out=23,043,446 elapsed=173.7s

  [2256/13157] intraday_11141.csv.gz  in=197,895,164 out=23,055,444 elapsed=173.7s

  [2257/13157] intraday_11145.csv.gz  in=197,905,837 out=23,066,117 elapsed=173.9s

  [2258/13157] intraday_11142.csv.gz  in=197,920,402 out=23,080,682 elapsed=174.0s

  [2259/13157] intraday_11144.csv.gz  in=197,932,559 out=23,092,839 elapsed=174.0s

  [2260/13157] intraday_11146.csv.gz  in=197,943,865 out=23,104,145 elapsed=174.2s

  [2261/13157] intraday_11147.csv.gz  in=197,956,698 out=23,116,978 elapsed=174.2s

  [2262/13157] intraday_11143.csv.gz  in=197,972,953 out=23,133,233 elapsed=174.2s

  [2263/13157] intraday_1115.csv.gz  in=197,985,907 out=23,133,233 elapsed=174.2s

  [2264/13157] intraday_11148.csv.gz  in=197,996,982 out=23,144,308 elapsed=174.2s

  [2265/13157] intraday_11150.csv.gz  in=198,007,688 out=23,155,014 elapsed=174.3s

  [2266/13157] intraday_11152.csv.gz  in=198,019,621 out=23,166,947 elapsed=174.3s

  [2267/13157] intraday_11149.csv.gz  in=198,033,266 out=23,180,592 elapsed=174.3s

  [2268/13157] intraday_11151.csv.gz  in=198,046,966 out=23,194,292 elapsed=174.3s

  [2269/13157] intraday_11156.csv.gz  in=198,059,960 out=23,207,286 elapsed=174.5s

  [2270/13157] intraday_11154.csv.gz  in=198,072,591 out=23,219,917 elapsed=174.5s

  [2271/13157] intraday_11155.csv.gz  in=198,083,332 out=23,230,658 elapsed=174.5s

  [2272/13157] intraday_11153.csv.gz  in=198,095,464 out=23,242,790 elapsed=174.5s

  [2273/13157] intraday_11159.csv.gz  in=198,105,631 out=23,252,957 elapsed=174.6s

  [2274/13157] intraday_1116.csv.gz  in=198,118,606 out=23,252,957 elapsed=174.6s

  [2275/13157] intraday_11157.csv.gz  in=198,128,883 out=23,263,234 elapsed=174.6s

  [2276/13157] intraday_11158.csv.gz  in=198,140,433 out=23,274,784 elapsed=174.6s

  [2277/13157] intraday_11161.csv.gz  in=198,152,814 out=23,287,165 elapsed=174.7s

  [2278/13157] intraday_11160.csv.gz  in=198,164,691 out=23,299,042 elapsed=174.7s

  [2279/13157] intraday_11162.csv.gz  in=198,177,083 out=23,311,434 elapsed=174.7s

  [2280/13157] intraday_11163.csv.gz  in=198,187,407 out=23,321,758 elapsed=174.7s

  [2281/13157] intraday_11165.csv.gz  in=198,199,287 out=23,333,638 elapsed=174.7s

  [2282/13157] intraday_11164.csv.gz  in=198,212,260 out=23,346,611 elapsed=174.8s

  [2283/13157] intraday_11168.csv.gz  in=198,224,588 out=23,358,939 elapsed=174.8s

  [2284/13157] intraday_11166.csv.gz  in=198,237,524 out=23,371,875 elapsed=174.8s

  [2285/13157] intraday_11167.csv.gz  in=198,248,886 out=23,383,237 elapsed=174.9s

  [2286/13157] intraday_1117.csv.gz  in=198,260,911 out=23,383,237 elapsed=174.9s

  [2287/13157] intraday_11169.csv.gz  in=198,274,251 out=23,396,577 elapsed=174.9s

  [2288/13157] intraday_11170.csv.gz  in=198,285,828 out=23,408,154 elapsed=174.9s

  [2289/13157] intraday_11171.csv.gz  in=198,295,918 out=23,418,244 elapsed=175.0s

  [2290/13157] intraday_11172.csv.gz  in=198,308,883 out=23,431,209 elapsed=175.0s

  [2291/13157] intraday_11174.csv.gz  in=198,323,201 out=23,445,527 elapsed=175.0s

  [2292/13157] intraday_11173.csv.gz  in=198,340,661 out=23,462,987 elapsed=175.0s

  [2293/13157] intraday_11175.csv.gz  in=198,354,758 out=23,477,084 elapsed=175.0s

  [2294/13157] intraday_11176.csv.gz  in=198,370,655 out=23,492,981 elapsed=175.1s

  [2295/13157] intraday_11177.csv.gz  in=198,383,335 out=23,505,661 elapsed=175.1s

  [2296/13157] intraday_1118.csv.gz  in=198,393,904 out=23,505,661 elapsed=175.1s

  [2297/13157] intraday_11178.csv.gz  in=198,407,828 out=23,519,585 elapsed=175.1s

  [2298/13157] intraday_11179.csv.gz  in=198,420,182 out=23,531,939 elapsed=175.1s

  [2299/13157] intraday_11180.csv.gz  in=198,432,250 out=23,544,007 elapsed=175.1s

  [2300/13157] intraday_11181.csv.gz  in=198,443,040 out=23,554,797 elapsed=175.2s

  [2301/13157] intraday_11183.csv.gz  in=198,453,900 out=23,565,657 elapsed=175.2s

  [2302/13157] intraday_11182.csv.gz  in=198,465,084 out=23,576,841 elapsed=175.2s

  [2303/13157] intraday_11184.csv.gz  in=198,477,240 out=23,588,997 elapsed=175.2s

  [2304/13157] intraday_11185.csv.gz  in=198,488,782 out=23,600,539 elapsed=175.2s

  [2305/13157] intraday_11186.csv.gz  in=198,502,953 out=23,614,710 elapsed=175.2s

  [2306/13157] intraday_1119.csv.gz  in=198,516,550 out=23,614,710 elapsed=175.3s

  [2307/13157] intraday_11187.csv.gz  in=198,526,925 out=23,625,085 elapsed=175.3s

  [2308/13157] intraday_11188.csv.gz  in=198,537,464 out=23,635,624 elapsed=175.3s

  [2309/13157] intraday_11189.csv.gz  in=198,548,301 out=23,646,461 elapsed=175.3s

  [2310/13157] intraday_11190.csv.gz  in=198,560,060 out=23,658,220 elapsed=175.4s

  [2311/13157] intraday_11191.csv.gz  in=198,570,222 out=23,668,382 elapsed=175.4s

  [2312/13157] intraday_11192.csv.gz  in=198,584,442 out=23,682,602 elapsed=175.5s

  [2313/13157] intraday_11194.csv.gz  in=198,598,314 out=23,696,474 elapsed=175.6s

  [2314/13157] intraday_11196.csv.gz  in=198,611,387 out=23,709,547 elapsed=175.6s

  [2315/13157] intraday_11195.csv.gz  in=198,625,255 out=23,723,415 elapsed=175.6s

  [2316/13157] intraday_11193.csv.gz  in=198,640,264 out=23,738,424 elapsed=175.7s

  [2317/13157] intraday_11199.csv.gz  in=198,650,354 out=23,748,514 elapsed=175.8s

  [2318/13157] intraday_11198.csv.gz  in=198,662,396 out=23,760,556 elapsed=175.8s

  [2319/13157] intraday_11197.csv.gz  in=198,673,673 out=23,771,833 elapsed=175.9s

  [2320/13157] intraday_1120.csv.gz  in=198,687,522 out=23,771,833 elapsed=175.9s

  [2321/13157] intraday_11200.csv.gz  in=198,700,043 out=23,784,354 elapsed=175.9s

  [2322/13157] intraday_11201.csv.gz  in=198,707,115 out=23,791,426 elapsed=175.9s

  [2323/13157] intraday_11204.csv.gz  in=198,708,489 out=23,792,800 elapsed=175.9s

  [2324/13157] intraday_11202.csv.gz  in=198,715,150 out=23,799,461 elapsed=175.9s

  [2325/13157] intraday_11203.csv.gz  in=198,727,577 out=23,811,888 elapsed=175.9s

  [2326/13157] intraday_11205.csv.gz  in=198,736,239 out=23,820,550 elapsed=175.9s

  [2327/13157] intraday_11206.csv.gz  in=198,741,356 out=23,825,667 elapsed=175.9s

  [2328/13157] intraday_11207.csv.gz  in=198,750,132 out=23,834,443 elapsed=176.0s

  [2329/13157] intraday_11208.csv.gz  in=198,763,823 out=23,848,134 elapsed=176.0s

  [2330/13157] intraday_1121.csv.gz  in=198,779,031 out=23,848,134 elapsed=176.0s

  [2331/13157] intraday_11209.csv.gz  in=198,789,454 out=23,858,557 elapsed=176.0s

  [2332/13157] intraday_11211.csv.gz  in=198,799,021 out=23,868,124 elapsed=176.0s

  [2333/13157] intraday_11210.csv.gz  in=198,814,040 out=23,883,143 elapsed=176.0s

  [2334/13157] intraday_11212.csv.gz  in=198,824,910 out=23,894,013 elapsed=176.1s

  [2335/13157] intraday_11213.csv.gz  in=198,837,255 out=23,906,358 elapsed=176.1s

  [2336/13157] intraday_11214.csv.gz  in=198,850,845 out=23,919,948 elapsed=176.1s

  [2337/13157] intraday_11216.csv.gz  in=198,862,713 out=23,931,816 elapsed=176.1s

  [2338/13157] intraday_11215.csv.gz  in=198,871,773 out=23,940,876 elapsed=176.1s

  [2339/13157] intraday_11217.csv.gz  in=198,884,449 out=23,953,552 elapsed=176.1s

  [2340/13157] intraday_11218.csv.gz  in=198,896,775 out=23,965,878 elapsed=176.1s

  [2341/13157] intraday_11219.csv.gz  in=198,906,602 out=23,975,705 elapsed=176.2s

  [2342/13157] intraday_1122.csv.gz  in=198,922,545 out=23,975,705 elapsed=176.2s

  [2343/13157] intraday_11220.csv.gz  in=198,938,367 out=23,991,527 elapsed=176.2s

  [2344/13157] intraday_11221.csv.gz  in=198,950,211 out=24,003,371 elapsed=176.2s

  [2345/13157] intraday_11223.csv.gz  in=198,961,181 out=24,014,341 elapsed=176.2s

  [2346/13157] intraday_11222.csv.gz  in=198,970,754 out=24,023,914 elapsed=176.2s

  [2347/13157] intraday_11224.csv.gz  in=198,981,854 out=24,035,014 elapsed=176.2s

  [2348/13157] intraday_11225.csv.gz  in=198,994,572 out=24,047,732 elapsed=176.2s

  [2349/13157] intraday_11226.csv.gz  in=199,006,037 out=24,059,197 elapsed=176.3s

  [2350/13157] intraday_1123.csv.gz  in=199,019,325 out=24,059,197 elapsed=176.3s

  [2351/13157] intraday_11227.csv.gz  in=199,029,001 out=24,068,873 elapsed=176.4s

  [2352/13157] intraday_11228.csv.gz  in=199,044,885 out=24,084,757 elapsed=176.4s

  [2353/13157] intraday_11229.csv.gz  in=199,056,901 out=24,096,773 elapsed=176.4s

  [2354/13157] intraday_11231.csv.gz  in=199,068,818 out=24,108,690 elapsed=176.4s

  [2355/13157] intraday_11230.csv.gz  in=199,081,360 out=24,121,232 elapsed=176.4s

  [2356/13157] intraday_11232.csv.gz  in=199,093,684 out=24,133,556 elapsed=176.4s

  [2357/13157] intraday_11233.csv.gz  in=199,105,785 out=24,145,657 elapsed=176.4s

  [2358/13157] intraday_11235.csv.gz  in=199,116,275 out=24,156,147 elapsed=176.5s

  [2359/13157] intraday_11237.csv.gz  in=199,128,974 out=24,168,846 elapsed=176.5s

  [2360/13157] intraday_11234.csv.gz  in=199,139,730 out=24,179,602 elapsed=176.5s

  [2361/13157] intraday_11236.csv.gz  in=199,149,735 out=24,189,607 elapsed=176.5s

  [2362/13157] intraday_1124.csv.gz  in=199,162,073 out=24,189,607 elapsed=176.6s

  [2363/13157] intraday_11238.csv.gz  in=199,176,764 out=24,204,298 elapsed=176.6s

  [2364/13157] intraday_11240.csv.gz  in=199,186,222 out=24,213,756 elapsed=176.6s

  [2365/13157] intraday_11239.csv.gz  in=199,198,766 out=24,226,300 elapsed=176.6s

  [2366/13157] intraday_11241.csv.gz  in=199,208,900 out=24,236,434 elapsed=176.6s

  [2367/13157] intraday_11242.csv.gz  in=199,220,902 out=24,248,436 elapsed=176.6s

  [2368/13157] intraday_11244.csv.gz  in=199,231,001 out=24,258,535 elapsed=176.6s

  [2369/13157] intraday_11243.csv.gz  in=199,243,201 out=24,270,735 elapsed=176.6s

  [2370/13157] intraday_11245.csv.gz  in=199,254,645 out=24,282,179 elapsed=176.6s

  [2371/13157] intraday_11247.csv.gz  in=199,264,540 out=24,292,074 elapsed=176.7s

  [2372/13157] intraday_11246.csv.gz  in=199,275,662 out=24,303,196 elapsed=176.7s

  [2373/13157] intraday_11248.csv.gz  in=199,284,860 out=24,312,394 elapsed=176.7s

  [2374/13157] intraday_11249.csv.gz  in=199,295,829 out=24,323,363 elapsed=176.7s

  [2375/13157] intraday_1125.csv.gz  in=199,308,498 out=24,323,363 elapsed=176.9s

  [2376/13157] intraday_11250.csv.gz  in=199,320,942 out=24,335,807 elapsed=176.9s

  [2377/13157] intraday_11251.csv.gz  in=199,331,588 out=24,346,453 elapsed=176.9s

  [2378/13157] intraday_11252.csv.gz  in=199,345,169 out=24,360,034 elapsed=176.9s

  [2379/13157] intraday_11253.csv.gz  in=199,356,958 out=24,371,823 elapsed=176.9s

  [2380/13157] intraday_11254.csv.gz  in=199,366,992 out=24,381,857 elapsed=177.0s

  [2381/13157] intraday_11256.csv.gz  in=199,378,608 out=24,393,473 elapsed=177.0s

  [2382/13157] intraday_11255.csv.gz  in=199,389,336 out=24,404,201 elapsed=177.0s

  [2383/13157] intraday_11257.csv.gz  in=199,398,383 out=24,413,248 elapsed=177.0s

  [2384/13157] intraday_11258.csv.gz  in=199,413,721 out=24,428,586 elapsed=177.0s

  [2385/13157] intraday_11259.csv.gz  in=199,424,364 out=24,439,229 elapsed=177.0s

  [2386/13157] intraday_1126.csv.gz  in=199,438,548 out=24,439,229 elapsed=177.0s

  [2387/13157] intraday_11260.csv.gz  in=199,449,933 out=24,450,614 elapsed=177.1s

  [2388/13157] intraday_11262.csv.gz  in=199,460,776 out=24,461,457 elapsed=177.1s

  [2389/13157] intraday_11263.csv.gz  in=199,474,568 out=24,475,249 elapsed=177.1s

  [2390/13157] intraday_11261.csv.gz  in=199,486,351 out=24,487,032 elapsed=177.1s

  [2391/13157] intraday_11264.csv.gz  in=199,499,031 out=24,499,712 elapsed=177.1s

  [2392/13157] intraday_11265.csv.gz  in=199,510,940 out=24,511,621 elapsed=177.2s

  [2393/13157] intraday_11267.csv.gz  in=199,523,071 out=24,523,752 elapsed=177.2s

  [2394/13157] intraday_11266.csv.gz  in=199,532,727 out=24,533,408 elapsed=177.2s

  [2395/13157] intraday_11268.csv.gz  in=199,544,820 out=24,545,501 elapsed=177.2s

  [2396/13157] intraday_1127.csv.gz  in=199,556,760 out=24,545,501 elapsed=177.2s

  [2397/13157] intraday_11270.csv.gz  in=199,574,655 out=24,563,396 elapsed=177.3s

  [2398/13157] intraday_11269.csv.gz  in=199,584,714 out=24,573,455 elapsed=177.3s

  [2399/13157] intraday_11272.csv.gz  in=199,594,329 out=24,583,070 elapsed=177.3s

  [2400/13157] intraday_11273.csv.gz  in=199,608,595 out=24,597,336 elapsed=177.4s

  [2401/13157] intraday_11271.csv.gz  in=199,619,211 out=24,607,952 elapsed=177.4s

  [2402/13157] intraday_11275.csv.gz  in=199,629,534 out=24,618,275 elapsed=177.4s

  [2403/13157] intraday_11277.csv.gz  in=199,640,986 out=24,629,727 elapsed=177.4s

  [2404/13157] intraday_11274.csv.gz  in=199,654,926 out=24,643,667 elapsed=177.4s

  [2405/13157] intraday_1128.csv.gz  in=199,673,306 out=24,643,667 elapsed=177.5s

  [2406/13157] intraday_11276.csv.gz  in=199,686,598 out=24,656,959 elapsed=177.5s

  [2407/13157] intraday_11278.csv.gz  in=199,697,617 out=24,667,978 elapsed=177.5s

  [2408/13157] intraday_11279.csv.gz  in=199,710,236 out=24,680,597 elapsed=177.5s

  [2409/13157] intraday_11282.csv.gz  in=199,723,826 out=24,694,187 elapsed=178.0s

  [2410/13157] intraday_11280.csv.gz  in=199,735,632 out=24,705,993 elapsed=178.0s

  [2411/13157] intraday_11281.csv.gz  in=199,750,169 out=24,720,530 elapsed=178.0s

  [2412/13157] intraday_11283.csv.gz  in=199,761,684 out=24,732,045 elapsed=178.0s

  [2413/13157] intraday_11284.csv.gz  in=199,771,606 out=24,741,967 elapsed=178.0s

  [2414/13157] intraday_11287.csv.gz  in=199,781,476 out=24,751,837 elapsed=178.0s

  [2415/13157] intraday_11285.csv.gz  in=199,791,247 out=24,761,608 elapsed=178.0s

  [2416/13157] intraday_11286.csv.gz  in=199,804,435 out=24,774,796 elapsed=178.0s

  [2417/13157] intraday_11288.csv.gz  in=199,815,214 out=24,785,575 elapsed=178.0s

  [2418/13157] intraday_1129.csv.gz  in=199,828,525 out=24,785,575 elapsed=178.0s

  [2419/13157] intraday_11289.csv.gz  in=199,836,881 out=24,793,931 elapsed=178.1s

  [2420/13157] intraday_11290.csv.gz  in=199,846,110 out=24,803,160 elapsed=178.1s

  [2421/13157] intraday_11291.csv.gz  in=199,856,929 out=24,813,979 elapsed=178.1s

  [2422/13157] intraday_11292.csv.gz  in=199,870,993 out=24,828,043 elapsed=178.2s

  [2423/13157] intraday_11294.csv.gz  in=199,883,077 out=24,840,127 elapsed=178.2s

  [2424/13157] intraday_11293.csv.gz  in=199,899,891 out=24,856,941 elapsed=178.2s

  [2425/13157] intraday_11295.csv.gz  in=199,910,077 out=24,867,127 elapsed=178.4s

  [2426/13157] intraday_11296.csv.gz  in=199,921,257 out=24,878,307 elapsed=178.4s

  [2427/13157] intraday_11297.csv.gz  in=199,934,169 out=24,891,219 elapsed=178.4s

  [2428/13157] intraday_11298.csv.gz  in=199,945,267 out=24,902,317 elapsed=178.4s

  [2429/13157] intraday_11300.csv.gz  in=199,955,226 out=24,912,276 elapsed=178.6s

  [2430/13157] intraday_1130.csv.gz  in=199,967,488 out=24,912,276 elapsed=178.6s

  [2431/13157] intraday_11301.csv.gz  in=199,983,454 out=24,928,242 elapsed=178.6s

  [2432/13157] intraday_11299.csv.gz  in=199,996,584 out=24,941,372 elapsed=178.6s

  [2433/13157] intraday_11302.csv.gz  in=200,007,425 out=24,952,213 elapsed=178.8s

  [2434/13157] intraday_11305.csv.gz  in=200,018,829 out=24,963,617 elapsed=178.8s

  [2435/13157] intraday_11303.csv.gz  in=200,029,938 out=24,974,726 elapsed=178.8s

  [2436/13157] intraday_11304.csv.gz  in=200,043,722 out=24,988,510 elapsed=178.8s

  [2437/13157] intraday_11306.csv.gz  in=200,055,491 out=25,000,279 elapsed=178.8s

  [2438/13157] intraday_11307.csv.gz  in=200,065,601 out=25,010,389 elapsed=178.9s

  [2439/13157] intraday_11308.csv.gz  in=200,077,649 out=25,022,437 elapsed=178.9s

  [2440/13157] intraday_11309.csv.gz  in=200,087,360 out=25,032,148 elapsed=179.2s

  [2441/13157] intraday_1131.csv.gz  in=200,099,058 out=25,032,148 elapsed=179.2s

  [2442/13157] intraday_11310.csv.gz  in=200,111,080 out=25,044,170 elapsed=179.3s

  [2443/13157] intraday_11311.csv.gz  in=200,122,395 out=25,055,485 elapsed=179.3s

  [2444/13157] intraday_11315.csv.gz  in=200,135,171 out=25,068,261 elapsed=179.4s

  [2445/13157] intraday_11312.csv.gz  in=200,148,150 out=25,081,240 elapsed=179.4s

  [2446/13157] intraday_11313.csv.gz  in=200,159,548 out=25,092,638 elapsed=179.4s

  [2447/13157] intraday_11314.csv.gz  in=200,171,150 out=25,104,240 elapsed=179.4s

  [2448/13157] intraday_11318.csv.gz  in=200,183,587 out=25,116,677 elapsed=179.8s

  [2449/13157] intraday_11316.csv.gz  in=200,195,515 out=25,128,605 elapsed=179.8s

  [2450/13157] intraday_11317.csv.gz  in=200,206,663 out=25,139,753 elapsed=179.8s

  [2451/13157] intraday_1132.csv.gz  in=200,220,380 out=25,139,753 elapsed=179.8s

  [2452/13157] intraday_11319.csv.gz  in=200,233,467 out=25,152,840 elapsed=179.8s

  [2453/13157] intraday_11321.csv.gz  in=200,243,924 out=25,163,297 elapsed=179.8s

  [2454/13157] intraday_11322.csv.gz  in=200,256,040 out=25,175,413 elapsed=179.8s

  [2455/13157] intraday_11320.csv.gz  in=200,267,330 out=25,186,703 elapsed=179.8s

  [2456/13157] intraday_11323.csv.gz  in=200,284,260 out=25,203,633 elapsed=179.9s

  [2457/13157] intraday_11325.csv.gz  in=200,297,868 out=25,217,241 elapsed=179.9s

  [2458/13157] intraday_11326.csv.gz  in=200,314,558 out=25,233,931 elapsed=179.9s

  [2459/13157] intraday_11324.csv.gz  in=200,329,736 out=25,249,109 elapsed=179.9s

  [2460/13157] intraday_11327.csv.gz  in=200,341,728 out=25,261,101 elapsed=179.9s

  [2461/13157] intraday_11329.csv.gz  in=200,353,145 out=25,272,518 elapsed=179.9s

  [2462/13157] intraday_1133.csv.gz  in=200,366,749 out=25,272,518 elapsed=180.0s

  [2463/13157] intraday_11328.csv.gz  in=200,382,000 out=25,287,769 elapsed=180.0s

  [2464/13157] intraday_11331.csv.gz  in=200,393,547 out=25,299,316 elapsed=180.0s

  [2465/13157] intraday_11330.csv.gz  in=200,404,770 out=25,310,539 elapsed=180.1s

  [2466/13157] intraday_11333.csv.gz  in=200,415,427 out=25,321,196 elapsed=180.1s

  [2467/13157] intraday_11332.csv.gz  in=200,428,181 out=25,333,950 elapsed=180.1s

  [2468/13157] intraday_11337.csv.gz  in=200,440,813 out=25,346,582 elapsed=180.1s

  [2469/13157] intraday_11335.csv.gz  in=200,452,128 out=25,357,897 elapsed=180.1s

  [2470/13157] intraday_11334.csv.gz  in=200,464,002 out=25,369,771 elapsed=180.1s

  [2471/13157] intraday_11336.csv.gz  in=200,478,450 out=25,384,219 elapsed=180.1s

  [2472/13157] intraday_11338.csv.gz  in=200,489,682 out=25,395,451 elapsed=180.2s

  [2473/13157] intraday_1134.csv.gz  in=200,515,183 out=25,395,451 elapsed=180.3s

  [2474/13157] intraday_11340.csv.gz  in=200,527,050 out=25,407,318 elapsed=180.3s

  [2475/13157] intraday_11339.csv.gz  in=200,537,858 out=25,418,126 elapsed=180.3s

  [2476/13157] intraday_11342.csv.gz  in=200,550,434 out=25,430,702 elapsed=180.7s

  [2477/13157] intraday_11341.csv.gz  in=200,562,875 out=25,443,143 elapsed=180.8s

  [2478/13157] intraday_11343.csv.gz  in=200,577,383 out=25,457,651 elapsed=181.1s

  [2479/13157] intraday_11344.csv.gz  in=200,596,659 out=25,476,927 elapsed=181.2s

  [2480/13157] intraday_11345.csv.gz  in=200,610,516 out=25,490,784 elapsed=181.3s

  [2481/13157] intraday_11348.csv.gz  in=200,621,684 out=25,501,952 elapsed=181.3s

  [2482/13157] intraday_11346.csv.gz  in=200,637,011 out=25,517,279 elapsed=181.3s

  [2483/13157] intraday_11347.csv.gz  in=200,649,124 out=25,529,392 elapsed=181.3s

  [2484/13157] intraday_11349.csv.gz  in=200,662,455 out=25,542,723 elapsed=181.3s

  [2485/13157] intraday_11351.csv.gz  in=200,672,301 out=25,552,569 elapsed=181.4s

  [2486/13157] intraday_11352.csv.gz  in=200,679,113 out=25,559,381 elapsed=181.4s

  [2487/13157] intraday_11350.csv.gz  in=200,690,605 out=25,570,873 elapsed=181.4s

  [2488/13157] intraday_1135.csv.gz  in=200,706,649 out=25,570,873 elapsed=181.4s

  [2489/13157] intraday_11353.csv.gz  in=200,717,771 out=25,581,995 elapsed=181.4s

  [2490/13157] intraday_11354.csv.gz  in=200,724,974 out=25,589,198 elapsed=181.4s

  [2491/13157] intraday_11358.csv.gz  in=200,734,274 out=25,598,498 elapsed=181.5s

  [2492/13157] intraday_11355.csv.gz  in=200,748,006 out=25,612,230 elapsed=181.5s

  [2493/13157] intraday_11357.csv.gz  in=200,761,777 out=25,626,001 elapsed=181.5s

  [2494/13157] intraday_11356.csv.gz  in=200,773,508 out=25,637,732 elapsed=181.5s

  [2495/13157] intraday_1136.csv.gz  in=200,784,961 out=25,637,732 elapsed=181.6s

  [2496/13157] intraday_11359.csv.gz  in=200,795,824 out=25,648,595 elapsed=181.6s

  [2497/13157] intraday_11362.csv.gz  in=200,806,545 out=25,659,316 elapsed=181.7s

  [2498/13157] intraday_11360.csv.gz  in=200,819,624 out=25,672,395 elapsed=181.7s

  [2499/13157] intraday_11363.csv.gz  in=200,830,782 out=25,683,553 elapsed=181.7s

  [2500/13157] intraday_11361.csv.gz  in=200,844,342 out=25,697,113 elapsed=181.7s

  [2501/13157] intraday_11366.csv.gz  in=200,854,555 out=25,707,326 elapsed=182.3s

  [2502/13157] intraday_11364.csv.gz  in=200,867,435 out=25,720,206 elapsed=182.3s

  [2503/13157] intraday_11367.csv.gz  in=200,880,146 out=25,732,917 elapsed=182.3s

  [2504/13157] intraday_11369.csv.gz  in=200,889,026 out=25,741,797 elapsed=182.5s

  [2505/13157] intraday_1137.csv.gz  in=200,902,789 out=25,741,797 elapsed=182.5s

  [2506/13157] intraday_11365.csv.gz  in=200,915,017 out=25,754,025 elapsed=182.5s

  [2507/13157] intraday_11368.csv.gz  in=200,927,677 out=25,766,685 elapsed=182.5s

  [2508/13157] intraday_11372.csv.gz  in=200,940,650 out=25,779,658 elapsed=182.7s

  [2509/13157] intraday_11370.csv.gz  in=200,950,151 out=25,789,159 elapsed=182.7s

  [2510/13157] intraday_11371.csv.gz  in=200,962,489 out=25,801,497 elapsed=182.7s

  [2511/13157] intraday_11373.csv.gz  in=200,973,129 out=25,812,137 elapsed=182.9s

  [2512/13157] intraday_11376.csv.gz  in=200,985,692 out=25,824,700 elapsed=182.9s

  [2513/13157] intraday_11374.csv.gz  in=201,008,455 out=25,847,463 elapsed=182.9s

  [2514/13157] intraday_11377.csv.gz  in=201,025,512 out=25,864,520 elapsed=183.1s

  [2515/13157] intraday_11378.csv.gz  in=201,036,618 out=25,875,626 elapsed=183.1s

  [2516/13157] intraday_11375.csv.gz  in=201,046,674 out=25,885,682 elapsed=183.1s

  [2517/13157] intraday_1138.csv.gz  in=201,058,122 out=25,885,682 elapsed=183.3s

  [2518/13157] intraday_11379.csv.gz  in=201,071,228 out=25,898,788 elapsed=183.3s

  [2519/13157] intraday_11380.csv.gz  in=201,083,055 out=25,910,615 elapsed=183.3s

  [2520/13157] intraday_11381.csv.gz  in=201,095,329 out=25,922,889 elapsed=183.7s

  [2521/13157] intraday_11384.csv.gz  in=201,107,474 out=25,935,034 elapsed=183.8s

  [2522/13157] intraday_11382.csv.gz  in=201,118,147 out=25,945,707 elapsed=183.9s

  [2523/13157] intraday_11385.csv.gz  in=201,133,111 out=25,960,671 elapsed=184.0s

  [2524/13157] intraday_11383.csv.gz  in=201,142,980 out=25,970,540 elapsed=184.0s

  [2525/13157] intraday_11387.csv.gz  in=201,152,673 out=25,980,233 elapsed=184.0s

  [2526/13157] intraday_11386.csv.gz  in=201,165,905 out=25,993,465 elapsed=184.0s

  [2527/13157] intraday_1139.csv.gz  in=201,178,106 out=25,993,465 elapsed=184.0s

  [2528/13157] intraday_11388.csv.gz  in=201,188,308 out=26,003,667 elapsed=184.0s

  [2529/13157] intraday_11389.csv.gz  in=201,200,951 out=26,016,310 elapsed=184.0s

  [2530/13157] intraday_11390.csv.gz  in=201,212,389 out=26,027,748 elapsed=184.1s

  [2531/13157] intraday_11391.csv.gz  in=201,223,291 out=26,038,650 elapsed=184.1s

  [2532/13157] intraday_11392.csv.gz  in=201,234,799 out=26,050,158 elapsed=184.1s

  [2533/13157] intraday_11393.csv.gz  in=201,248,362 out=26,063,721 elapsed=184.1s

  [2534/13157] intraday_11395.csv.gz  in=201,260,066 out=26,075,425 elapsed=184.1s

  [2535/13157] intraday_11394.csv.gz  in=201,269,868 out=26,085,227 elapsed=184.2s

  [2536/13157] intraday_11396.csv.gz  in=201,280,543 out=26,095,902 elapsed=184.2s

  [2537/13157] intraday_11397.csv.gz  in=201,293,275 out=26,108,634 elapsed=184.2s

  [2538/13157] intraday_1140.csv.gz  in=201,306,432 out=26,108,634 elapsed=184.2s

  [2539/13157] intraday_11400.csv.gz  in=201,318,750 out=26,120,952 elapsed=184.2s

  [2540/13157] intraday_11398.csv.gz  in=201,329,456 out=26,131,658 elapsed=184.2s

  [2541/13157] intraday_11399.csv.gz  in=201,342,686 out=26,144,888 elapsed=184.2s

  [2542/13157] intraday_11401.csv.gz  in=201,353,878 out=26,156,080 elapsed=184.3s

  [2543/13157] intraday_11402.csv.gz  in=201,364,612 out=26,166,814 elapsed=184.3s

  [2544/13157] intraday_11404.csv.gz  in=201,373,580 out=26,175,782 elapsed=184.3s

  [2545/13157] intraday_11403.csv.gz  in=201,385,438 out=26,187,640 elapsed=184.3s

  [2546/13157] intraday_11407.csv.gz  in=201,395,809 out=26,198,011 elapsed=184.4s

  [2547/13157] intraday_11406.csv.gz  in=201,406,225 out=26,208,427 elapsed=184.4s

  [2548/13157] intraday_11408.csv.gz  in=201,418,874 out=26,221,076 elapsed=184.4s

  [2549/13157] intraday_11405.csv.gz  in=201,431,341 out=26,233,543 elapsed=184.4s

  [2550/13157] intraday_11410.csv.gz  in=201,445,114 out=26,247,316 elapsed=184.5s

  [2551/13157] intraday_1141.csv.gz  in=201,455,911 out=26,247,316 elapsed=184.6s

  [2552/13157] intraday_11411.csv.gz  in=201,468,435 out=26,259,840 elapsed=184.7s

  [2553/13157] intraday_11409.csv.gz  in=201,479,295 out=26,270,700 elapsed=184.7s

  [2554/13157] intraday_11414.csv.gz  in=201,491,435 out=26,282,840 elapsed=184.8s

  [2555/13157] intraday_11412.csv.gz  in=201,504,356 out=26,295,761 elapsed=184.8s

  [2556/13157] intraday_11413.csv.gz  in=201,514,733 out=26,306,138 elapsed=184.8s

  [2557/13157] intraday_11415.csv.gz  in=201,525,578 out=26,316,983 elapsed=184.8s

  [2558/13157] intraday_11417.csv.gz  in=201,537,588 out=26,328,993 elapsed=184.8s

  [2559/13157] intraday_11416.csv.gz  in=201,548,569 out=26,339,974 elapsed=184.8s

  [2560/13157] intraday_11418.csv.gz  in=201,559,451 out=26,350,856 elapsed=184.8s

  [2561/13157] intraday_11419.csv.gz  in=201,569,016 out=26,360,421 elapsed=184.9s

  [2562/13157] intraday_1142.csv.gz  in=201,580,681 out=26,360,421 elapsed=184.9s

  [2563/13157] intraday_11420.csv.gz  in=201,593,507 out=26,373,247 elapsed=184.9s

  [2564/13157] intraday_11421.csv.gz  in=201,607,930 out=26,387,670 elapsed=184.9s

  [2565/13157] intraday_11422.csv.gz  in=201,620,170 out=26,399,910 elapsed=184.9s

  [2566/13157] intraday_11425.csv.gz  in=201,633,764 out=26,413,504 elapsed=185.0s

  [2567/13157] intraday_11423.csv.gz  in=201,646,976 out=26,426,716 elapsed=185.1s

  [2568/13157] intraday_11424.csv.gz  in=201,659,730 out=26,439,470 elapsed=185.1s

  [2569/13157] intraday_11426.csv.gz  in=201,671,472 out=26,451,212 elapsed=185.1s

  [2570/13157] intraday_11429.csv.gz  in=201,684,650 out=26,464,390 elapsed=185.2s

  [2571/13157] intraday_11428.csv.gz  in=201,697,843 out=26,477,583 elapsed=185.2s

  [2572/13157] intraday_11427.csv.gz  in=201,709,733 out=26,489,473 elapsed=185.2s

  [2573/13157] intraday_1143.csv.gz  in=201,725,093 out=26,489,473 elapsed=185.2s

  [2574/13157] intraday_11431.csv.gz  in=201,735,969 out=26,500,349 elapsed=185.2s

  [2575/13157] intraday_11432.csv.gz  in=201,746,642 out=26,511,022 elapsed=185.3s

  [2576/13157] intraday_11430.csv.gz  in=201,758,790 out=26,523,170 elapsed=185.3s

  [2577/13157] intraday_11433.csv.gz  in=201,772,399 out=26,536,779 elapsed=185.3s

  [2578/13157] intraday_11434.csv.gz  in=201,783,029 out=26,547,409 elapsed=185.3s

  [2579/13157] intraday_11435.csv.gz  in=201,793,928 out=26,558,308 elapsed=185.3s

  [2580/13157] intraday_11436.csv.gz  in=201,802,710 out=26,567,090 elapsed=185.3s

  [2581/13157] intraday_11437.csv.gz  in=201,812,048 out=26,576,428 elapsed=185.4s

  [2582/13157] intraday_1144.csv.gz  in=201,825,260 out=26,576,428 elapsed=185.4s

  [2583/13157] intraday_11438.csv.gz  in=201,835,809 out=26,586,977 elapsed=185.4s

  [2584/13157] intraday_11439.csv.gz  in=201,848,735 out=26,599,903 elapsed=185.4s

  [2585/13157] intraday_11441.csv.gz  in=201,860,731 out=26,611,899 elapsed=185.5s

  [2586/13157] intraday_11442.csv.gz  in=201,871,500 out=26,622,668 elapsed=185.5s

  [2587/13157] intraday_11443.csv.gz  in=201,882,332 out=26,633,500 elapsed=185.5s

  [2588/13157] intraday_11440.csv.gz  in=201,903,262 out=26,654,430 elapsed=185.5s

  [2589/13157] intraday_11447.csv.gz  in=201,912,627 out=26,663,795 elapsed=185.6s

  [2590/13157] intraday_11445.csv.gz  in=201,923,214 out=26,674,382 elapsed=185.8s

  [2591/13157] intraday_11444.csv.gz  in=201,936,917 out=26,688,085 elapsed=185.8s

  [2592/13157] intraday_11446.csv.gz  in=201,951,744 out=26,702,912 elapsed=185.8s

  [2593/13157] intraday_11448.csv.gz  in=201,965,193 out=26,716,361 elapsed=186.1s

  [2594/13157] intraday_1145.csv.gz  in=201,975,982 out=26,716,361 elapsed=186.2s

  [2595/13157] intraday_11450.csv.gz  in=201,989,003 out=26,729,382 elapsed=186.3s

  [2596/13157] intraday_11449.csv.gz  in=202,001,120 out=26,741,499 elapsed=186.4s

  [2597/13157] intraday_11451.csv.gz  in=202,014,733 out=26,755,112 elapsed=186.4s

  [2598/13157] intraday_11452.csv.gz  in=202,025,829 out=26,766,208 elapsed=186.5s

  [2599/13157] intraday_11454.csv.gz  in=202,037,097 out=26,777,476 elapsed=186.8s

  [2600/13157] intraday_11453.csv.gz  in=202,053,094 out=26,793,473 elapsed=186.8s

  [2601/13157] intraday_11455.csv.gz  in=202,063,933 out=26,804,312 elapsed=187.4s

  [2602/13157] intraday_11456.csv.gz  in=202,075,645 out=26,816,024 elapsed=187.4s

  [2603/13157] intraday_11458.csv.gz  in=202,087,156 out=26,827,535 elapsed=187.7s

  [2604/13157] intraday_11457.csv.gz  in=202,097,510 out=26,837,889 elapsed=187.8s

  [2605/13157] intraday_1146.csv.gz  in=202,111,712 out=26,837,889 elapsed=187.8s

  [2606/13157] intraday_11459.csv.gz  in=202,124,813 out=26,850,990 elapsed=187.8s

  [2607/13157] intraday_11461.csv.gz  in=202,136,048 out=26,862,225 elapsed=187.8s

  [2608/13157] intraday_11460.csv.gz  in=202,147,896 out=26,874,073 elapsed=187.9s

  [2609/13157] intraday_11462.csv.gz  in=202,160,321 out=26,886,498 elapsed=187.9s

  [2610/13157] intraday_11464.csv.gz  in=202,172,139 out=26,898,316 elapsed=187.9s

  [2611/13157] intraday_11463.csv.gz  in=202,184,814 out=26,910,991 elapsed=187.9s

  [2612/13157] intraday_11466.csv.gz  in=202,197,361 out=26,923,538 elapsed=187.9s

  [2613/13157] intraday_11465.csv.gz  in=202,210,098 out=26,936,275 elapsed=188.0s

  [2614/13157] intraday_11467.csv.gz  in=202,222,801 out=26,948,978 elapsed=188.0s

  [2615/13157] intraday_11469.csv.gz  in=202,236,638 out=26,962,815 elapsed=188.0s

  [2616/13157] intraday_11468.csv.gz  in=202,245,997 out=26,972,174 elapsed=188.0s

  [2617/13157] intraday_1147.csv.gz  in=202,257,708 out=26,972,174 elapsed=188.1s

  [2618/13157] intraday_11471.csv.gz  in=202,271,328 out=26,985,794 elapsed=188.1s

  [2619/13157] intraday_11472.csv.gz  in=202,285,516 out=26,999,982 elapsed=188.1s

  [2620/13157] intraday_11470.csv.gz  in=202,302,572 out=27,017,038 elapsed=188.1s

  [2621/13157] intraday_11473.csv.gz  in=202,317,686 out=27,032,152 elapsed=188.2s

  [2622/13157] intraday_11475.csv.gz  in=202,332,748 out=27,047,214 elapsed=188.2s

  [2623/13157] intraday_11474.csv.gz  in=202,346,810 out=27,061,276 elapsed=188.2s

  [2624/13157] intraday_11477.csv.gz  in=202,358,394 out=27,072,860 elapsed=188.2s

  [2625/13157] intraday_11476.csv.gz  in=202,371,554 out=27,086,020 elapsed=188.2s

  [2626/13157] intraday_11479.csv.gz  in=202,383,125 out=27,097,591 elapsed=188.3s

  [2627/13157] intraday_11480.csv.gz  in=202,394,282 out=27,108,748 elapsed=188.3s

  [2628/13157] intraday_1148.csv.gz  in=202,405,550 out=27,108,748 elapsed=188.3s

  [2629/13157] intraday_11478.csv.gz  in=202,418,493 out=27,121,691 elapsed=188.3s

  [2630/13157] intraday_11481.csv.gz  in=202,430,518 out=27,133,716 elapsed=188.3s

  [2631/13157] intraday_11482.csv.gz  in=202,443,347 out=27,146,545 elapsed=188.4s

  [2632/13157] intraday_11483.csv.gz  in=202,459,176 out=27,162,374 elapsed=188.4s

  [2633/13157] intraday_11485.csv.gz  in=202,470,432 out=27,173,630 elapsed=188.4s

  [2634/13157] intraday_11486.csv.gz  in=202,480,692 out=27,183,890 elapsed=188.4s

  [2635/13157] intraday_11487.csv.gz  in=202,493,548 out=27,196,746 elapsed=188.4s

  [2636/13157] intraday_11484.csv.gz  in=202,506,357 out=27,209,555 elapsed=188.5s

  [2637/13157] intraday_11488.csv.gz  in=202,517,229 out=27,220,427 elapsed=188.5s

  [2638/13157] intraday_11489.csv.gz  in=202,529,049 out=27,232,247 elapsed=188.5s

  [2639/13157] intraday_1149.csv.gz  in=202,543,232 out=27,232,247 elapsed=188.5s

  [2640/13157] intraday_11491.csv.gz  in=202,556,255 out=27,245,270 elapsed=188.5s

  [2641/13157] intraday_11490.csv.gz  in=202,571,507 out=27,260,522 elapsed=188.5s

  [2642/13157] intraday_11492.csv.gz  in=202,584,939 out=27,273,954 elapsed=188.5s

  [2643/13157] intraday_11495.csv.gz  in=202,598,006 out=27,287,021 elapsed=188.9s

  [2644/13157] intraday_11496.csv.gz  in=202,608,277 out=27,297,292 elapsed=188.9s

  [2645/13157] intraday_11493.csv.gz  in=202,623,036 out=27,312,051 elapsed=188.9s

  [2646/13157] intraday_11494.csv.gz  in=202,634,377 out=27,323,392 elapsed=188.9s

  [2647/13157] intraday_11498.csv.gz  in=202,641,792 out=27,330,807 elapsed=188.9s

  [2648/13157] intraday_11497.csv.gz  in=202,654,747 out=27,343,762 elapsed=188.9s

  [2649/13157] intraday_11499.csv.gz  in=202,661,856 out=27,350,871 elapsed=188.9s

  [2650/13157] intraday_11501.csv.gz  in=202,664,890 out=27,353,905 elapsed=189.0s

  [2651/13157] intraday_1150.csv.gz  in=202,676,521 out=27,353,905 elapsed=189.0s

  [2652/13157] intraday_11500.csv.gz  in=202,688,575 out=27,365,959 elapsed=189.0s

  [2653/13157] intraday_11502.csv.gz  in=202,695,424 out=27,372,808 elapsed=189.0s

  [2654/13157] intraday_11506.csv.gz  in=202,704,335 out=27,381,719 elapsed=189.0s

  [2655/13157] intraday_11505.csv.gz  in=202,716,995 out=27,394,379 elapsed=189.1s

  [2656/13157] intraday_11503.csv.gz  in=202,729,967 out=27,407,351 elapsed=189.1s

  [2657/13157] intraday_11504.csv.gz  in=202,741,950 out=27,419,334 elapsed=189.1s

  [2658/13157] intraday_1151.csv.gz  in=202,754,978 out=27,419,334 elapsed=189.1s

  [2659/13157] intraday_11509.csv.gz  in=202,768,952 out=27,433,308 elapsed=189.1s

  [2660/13157] intraday_11507.csv.gz  in=202,779,995 out=27,444,351 elapsed=189.2s

  [2661/13157] intraday_11511.csv.gz  in=202,790,669 out=27,455,025 elapsed=189.2s

  [2662/13157] intraday_11508.csv.gz  in=202,802,947 out=27,467,303 elapsed=189.2s

  [2663/13157] intraday_11512.csv.gz  in=202,815,492 out=27,479,848 elapsed=189.3s

  [2664/13157] intraday_11510.csv.gz  in=202,826,622 out=27,490,978 elapsed=189.3s

  [2665/13157] intraday_11513.csv.gz  in=202,837,688 out=27,502,044 elapsed=189.4s

  [2666/13157] intraday_11514.csv.gz  in=202,849,136 out=27,513,492 elapsed=189.4s

  [2667/13157] intraday_11515.csv.gz  in=202,860,917 out=27,525,273 elapsed=189.4s

  [2668/13157] intraday_11518.csv.gz  in=202,870,660 out=27,535,016 elapsed=189.5s

  [2669/13157] intraday_11519.csv.gz  in=202,882,674 out=27,547,030 elapsed=189.5s

  [2670/13157] intraday_11516.csv.gz  in=202,893,979 out=27,558,335 elapsed=189.5s

  [2671/13157] intraday_11517.csv.gz  in=202,902,934 out=27,567,290 elapsed=189.5s

  [2672/13157] intraday_11520.csv.gz  in=202,914,546 out=27,578,902 elapsed=189.6s

  [2673/13157] intraday_11521.csv.gz  in=202,925,893 out=27,590,249 elapsed=189.6s

  [2674/13157] intraday_1152.csv.gz  in=202,952,580 out=27,590,249 elapsed=189.6s

  [2675/13157] intraday_11522.csv.gz  in=202,962,377 out=27,600,046 elapsed=189.6s

  [2676/13157] intraday_11524.csv.gz  in=202,972,933 out=27,610,602 elapsed=189.7s

  [2677/13157] intraday_11525.csv.gz  in=202,984,792 out=27,622,461 elapsed=189.7s

  [2678/13157] intraday_11526.csv.gz  in=202,995,297 out=27,632,966 elapsed=189.7s

  [2679/13157] intraday_11523.csv.gz  in=203,006,609 out=27,644,278 elapsed=189.7s

  [2680/13157] intraday_11528.csv.gz  in=203,017,365 out=27,655,034 elapsed=189.7s

  [2681/13157] intraday_11527.csv.gz  in=203,029,584 out=27,667,253 elapsed=189.8s

  [2682/13157] intraday_1153.csv.gz  in=203,042,192 out=27,667,253 elapsed=189.8s

  [2683/13157] intraday_11529.csv.gz  in=203,054,126 out=27,679,187 elapsed=189.8s

  [2684/13157] intraday_11531.csv.gz  in=203,063,410 out=27,688,471 elapsed=189.8s

  [2685/13157] intraday_11530.csv.gz  in=203,074,600 out=27,699,661 elapsed=189.8s

  [2686/13157] intraday_11535.csv.gz  in=203,074,797 out=27,699,858 elapsed=189.9s

  [2687/13157] intraday_11532.csv.gz  in=203,086,798 out=27,711,859 elapsed=189.9s

  [2688/13157] intraday_11533.csv.gz  in=203,100,813 out=27,725,874 elapsed=189.9s

  [2689/13157] intraday_11538.csv.gz  in=203,100,848 out=27,725,909 elapsed=189.9s

  [2690/13157] intraday_11539.csv.gz  in=203,101,122 out=27,726,183 elapsed=190.0s

  [2691/13157] intraday_11537.csv.gz  in=203,101,193 out=27,726,254 elapsed=190.0s

  [2692/13157] intraday_11534.csv.gz  in=203,112,726 out=27,737,787 elapsed=190.0s

  [2693/13157] intraday_11536.csv.gz  in=203,113,119 out=27,738,180 elapsed=190.0s

  [2694/13157] intraday_11540.csv.gz  in=203,113,124 out=27,738,185 elapsed=190.0s

  [2695/13157] intraday_11541.csv.gz  in=203,113,152 out=27,738,213 elapsed=190.0s

  [2696/13157] intraday_11542.csv.gz  in=203,113,227 out=27,738,288 elapsed=190.0s

  [2697/13157] intraday_11543.csv.gz  in=203,120,953 out=27,746,014 elapsed=190.0s

  [2698/13157] intraday_1154.csv.gz  in=203,131,501 out=27,746,014 elapsed=190.0s

  [2699/13157] intraday_11544.csv.gz  in=203,141,993 out=27,756,506 elapsed=190.1s

  [2700/13157] intraday_11545.csv.gz  in=203,153,552 out=27,768,065 elapsed=190.1s

  [2701/13157] intraday_11547.csv.gz  in=203,163,665 out=27,778,178 elapsed=190.1s

  [2702/13157] intraday_11548.csv.gz  in=203,175,366 out=27,789,879 elapsed=190.2s

  [2703/13157] intraday_11549.csv.gz  in=203,184,372 out=27,798,885 elapsed=190.2s

  [2704/13157] intraday_1155.csv.gz  in=203,197,714 out=27,798,885 elapsed=190.2s

  [2705/13157] intraday_11550.csv.gz  in=203,207,869 out=27,809,040 elapsed=190.2s

  [2706/13157] intraday_11551.csv.gz  in=203,218,539 out=27,819,710 elapsed=190.3s

  [2707/13157] intraday_11552.csv.gz  in=203,229,151 out=27,830,322 elapsed=190.3s

  [2708/13157] intraday_11553.csv.gz  in=203,241,576 out=27,842,747 elapsed=190.3s

  [2709/13157] intraday_11554.csv.gz  in=203,252,180 out=27,853,351 elapsed=190.3s

  [2710/13157] intraday_11546.csv.gz  in=203,287,750 out=27,888,921 elapsed=190.3s

  [2711/13157] intraday_11555.csv.gz  in=203,298,843 out=27,900,014 elapsed=190.3s

  [2712/13157] intraday_11556.csv.gz  in=203,312,067 out=27,913,238 elapsed=190.4s

  [2713/13157] intraday_11557.csv.gz  in=203,321,619 out=27,922,790 elapsed=190.4s

  [2714/13157] intraday_1156.csv.gz  in=203,333,572 out=27,922,790 elapsed=190.4s

  [2715/13157] intraday_11558.csv.gz  in=203,344,022 out=27,933,240 elapsed=190.4s

  [2716/13157] intraday_11559.csv.gz  in=203,355,506 out=27,944,724 elapsed=190.4s

  [2717/13157] intraday_11560.csv.gz  in=203,365,654 out=27,954,872 elapsed=190.4s

  [2718/13157] intraday_11563.csv.gz  in=203,374,380 out=27,963,598 elapsed=190.4s

  [2719/13157] intraday_11562.csv.gz  in=203,384,887 out=27,974,105 elapsed=190.6s

  [2720/13157] intraday_11561.csv.gz  in=203,407,833 out=27,997,051 elapsed=190.6s

  [2721/13157] intraday_11565.csv.gz  in=203,419,042 out=28,008,260 elapsed=190.7s

  [2722/13157] intraday_11564.csv.gz  in=203,430,592 out=28,019,810 elapsed=190.7s

  [2723/13157] intraday_11566.csv.gz  in=203,441,222 out=28,030,440 elapsed=190.8s

  [2724/13157] intraday_11567.csv.gz  in=203,452,839 out=28,042,057 elapsed=190.8s

  [2725/13157] intraday_11568.csv.gz  in=203,464,580 out=28,053,798 elapsed=190.8s

  [2726/13157] intraday_11569.csv.gz  in=203,475,074 out=28,064,292 elapsed=190.9s

  [2727/13157] intraday_11570.csv.gz  in=203,486,566 out=28,075,784 elapsed=190.9s

  [2728/13157] intraday_1157.csv.gz  in=203,498,980 out=28,075,784 elapsed=190.9s

  [2729/13157] intraday_11571.csv.gz  in=203,511,019 out=28,087,823 elapsed=190.9s

  [2730/13157] intraday_11572.csv.gz  in=203,521,007 out=28,097,811 elapsed=191.0s

  [2731/13157] intraday_11576.csv.gz  in=203,530,553 out=28,107,357 elapsed=191.1s

  [2732/13157] intraday_11573.csv.gz  in=203,542,735 out=28,119,539 elapsed=191.1s

  [2733/13157] intraday_11575.csv.gz  in=203,556,016 out=28,132,820 elapsed=191.1s

  [2734/13157] intraday_11574.csv.gz  in=203,566,016 out=28,142,820 elapsed=191.1s

  [2735/13157] intraday_11577.csv.gz  in=203,579,564 out=28,156,368 elapsed=191.2s

  [2736/13157] intraday_1158.csv.gz  in=203,596,747 out=28,156,368 elapsed=191.2s

  [2737/13157] intraday_11579.csv.gz  in=203,610,367 out=28,169,988 elapsed=191.2s

  [2738/13157] intraday_11578.csv.gz  in=203,626,417 out=28,186,038 elapsed=191.2s

  [2739/13157] intraday_11582.csv.gz  in=203,636,317 out=28,195,938 elapsed=191.4s

  [2740/13157] intraday_11581.csv.gz  in=203,648,060 out=28,207,681 elapsed=191.4s

  [2741/13157] intraday_11583.csv.gz  in=203,659,486 out=28,219,107 elapsed=191.4s

  [2742/13157] intraday_11580.csv.gz  in=203,672,163 out=28,231,784 elapsed=191.4s

  [2743/13157] intraday_11584.csv.gz  in=203,683,971 out=28,243,592 elapsed=191.5s

  [2744/13157] intraday_11587.csv.gz  in=203,694,630 out=28,254,251 elapsed=191.5s

  [2745/13157] intraday_11586.csv.gz  in=203,706,465 out=28,266,086 elapsed=191.5s

  [2746/13157] intraday_11588.csv.gz  in=203,716,142 out=28,275,763 elapsed=191.6s

  [2747/13157] intraday_1159.csv.gz  in=203,731,803 out=28,275,763 elapsed=191.6s

  [2748/13157] intraday_11585.csv.gz  in=203,743,179 out=28,287,139 elapsed=191.6s

  [2749/13157] intraday_11589.csv.gz  in=203,756,646 out=28,300,606 elapsed=191.6s

  [2750/13157] intraday_11590.csv.gz  in=203,766,005 out=28,309,965 elapsed=191.7s

  [2751/13157] intraday_11592.csv.gz  in=203,775,683 out=28,319,643 elapsed=191.7s

  [2752/13157] intraday_11591.csv.gz  in=203,786,694 out=28,330,654 elapsed=191.7s

  [2753/13157] intraday_11593.csv.gz  in=203,794,340 out=28,338,300 elapsed=191.8s

  [2754/13157] intraday_11594.csv.gz  in=203,805,593 out=28,349,553 elapsed=191.8s

  [2755/13157] intraday_11595.csv.gz  in=203,816,659 out=28,360,619 elapsed=191.8s

  [2756/13157] intraday_11596.csv.gz  in=203,832,026 out=28,375,986 elapsed=191.8s

  [2757/13157] intraday_1160.csv.gz  in=203,841,562 out=28,375,986 elapsed=192.0s

  [2758/13157] intraday_11599.csv.gz  in=203,850,882 out=28,385,306 elapsed=192.1s

  [2759/13157] intraday_11597.csv.gz  in=203,863,783 out=28,398,207 elapsed=192.1s

  [2760/13157] intraday_11598.csv.gz  in=203,875,988 out=28,410,412 elapsed=192.1s

  [2761/13157] intraday_11600.csv.gz  in=203,889,570 out=28,423,994 elapsed=192.1s

  [2762/13157] intraday_11601.csv.gz  in=203,899,647 out=28,434,071 elapsed=192.1s

  [2763/13157] intraday_11603.csv.gz  in=203,910,117 out=28,444,541 elapsed=192.1s

  [2764/13157] intraday_11604.csv.gz  in=203,921,948 out=28,456,372 elapsed=192.2s

  [2765/13157] intraday_11602.csv.gz  in=203,934,798 out=28,469,222 elapsed=192.2s

  [2766/13157] intraday_11605.csv.gz  in=203,945,763 out=28,480,187 elapsed=192.2s

  [2767/13157] intraday_11606.csv.gz  in=203,958,453 out=28,492,877 elapsed=192.2s

  [2768/13157] intraday_11608.csv.gz  in=203,970,393 out=28,504,817 elapsed=192.2s

  [2769/13157] intraday_1161.csv.gz  in=203,982,517 out=28,504,817 elapsed=192.3s

  [2770/13157] intraday_11610.csv.gz  in=203,993,969 out=28,516,269 elapsed=192.3s

  [2771/13157] intraday_11607.csv.gz  in=204,005,903 out=28,528,203 elapsed=192.3s

  [2772/13157] intraday_11613.csv.gz  in=204,015,562 out=28,537,862 elapsed=192.4s

  [2773/13157] intraday_11612.csv.gz  in=204,026,760 out=28,549,060 elapsed=192.4s

  [2774/13157] intraday_11609.csv.gz  in=204,039,977 out=28,562,277 elapsed=192.4s

  [2775/13157] intraday_11611.csv.gz  in=204,049,673 out=28,571,973 elapsed=192.4s

  [2776/13157] intraday_11616.csv.gz  in=204,061,460 out=28,583,760 elapsed=192.5s

  [2777/13157] intraday_11617.csv.gz  in=204,072,334 out=28,594,634 elapsed=192.5s

  [2778/13157] intraday_11614.csv.gz  in=204,083,375 out=28,605,675 elapsed=192.5s

  [2779/13157] intraday_11615.csv.gz  in=204,097,073 out=28,619,373 elapsed=192.5s

  [2780/13157] intraday_1162.csv.gz  in=204,110,502 out=28,619,373 elapsed=192.7s

  [2781/13157] intraday_11618.csv.gz  in=204,122,967 out=28,631,838 elapsed=192.7s

  [2782/13157] intraday_11619.csv.gz  in=204,136,618 out=28,645,489 elapsed=192.7s

  [2783/13157] intraday_11620.csv.gz  in=204,147,190 out=28,656,061 elapsed=192.7s

  [2784/13157] intraday_11621.csv.gz  in=204,158,237 out=28,667,108 elapsed=192.9s

  [2785/13157] intraday_11624.csv.gz  in=204,167,818 out=28,676,689 elapsed=192.9s

  [2786/13157] intraday_11622.csv.gz  in=204,180,195 out=28,689,066 elapsed=192.9s

  [2787/13157] intraday_11623.csv.gz  in=204,193,968 out=28,702,839 elapsed=192.9s

  [2788/13157] intraday_11627.csv.gz  in=204,206,342 out=28,715,213 elapsed=193.0s

  [2789/13157] intraday_11628.csv.gz  in=204,218,977 out=28,727,848 elapsed=193.2s

  [2790/13157] intraday_11625.csv.gz  in=204,231,905 out=28,740,776 elapsed=193.2s

  [2791/13157] intraday_11626.csv.gz  in=204,246,760 out=28,755,631 elapsed=193.2s

  [2792/13157] intraday_11629.csv.gz  in=204,260,781 out=28,769,652 elapsed=193.3s

  [2793/13157] intraday_1163.csv.gz  in=204,274,917 out=28,769,652 elapsed=193.4s

  [2794/13157] intraday_11630.csv.gz  in=204,291,245 out=28,785,980 elapsed=193.4s

  [2795/13157] intraday_11632.csv.gz  in=204,304,124 out=28,798,859 elapsed=193.5s

  [2796/13157] intraday_11631.csv.gz  in=204,318,472 out=28,813,207 elapsed=193.5s

  [2797/13157] intraday_11633.csv.gz  in=204,329,270 out=28,824,005 elapsed=193.5s

  [2798/13157] intraday_11634.csv.gz  in=204,340,943 out=28,835,678 elapsed=193.5s

  [2799/13157] intraday_11635.csv.gz  in=204,352,498 out=28,847,233 elapsed=193.7s

  [2800/13157] intraday_11636.csv.gz  in=204,364,861 out=28,859,596 elapsed=193.7s

  [2801/13157] intraday_11638.csv.gz  in=204,376,942 out=28,871,677 elapsed=193.7s

  [2802/13157] intraday_11637.csv.gz  in=204,387,307 out=28,882,042 elapsed=193.7s

  [2803/13157] intraday_1164.csv.gz  in=204,397,915 out=28,882,042 elapsed=193.7s

  [2804/13157] intraday_11639.csv.gz  in=204,410,313 out=28,894,440 elapsed=193.8s

  [2805/13157] intraday_11641.csv.gz  in=204,423,181 out=28,907,308 elapsed=193.8s

  [2806/13157] intraday_11640.csv.gz  in=204,437,926 out=28,922,053 elapsed=193.8s

  [2807/13157] intraday_11642.csv.gz  in=204,448,281 out=28,932,408 elapsed=193.8s

  [2808/13157] intraday_11644.csv.gz  in=204,459,336 out=28,943,463 elapsed=193.8s

  [2809/13157] intraday_11643.csv.gz  in=204,470,225 out=28,954,352 elapsed=193.9s

  [2810/13157] intraday_11646.csv.gz  in=204,483,776 out=28,967,903 elapsed=193.9s

  [2811/13157] intraday_11647.csv.gz  in=204,497,949 out=28,982,076 elapsed=193.9s

  [2812/13157] intraday_11645.csv.gz  in=204,508,923 out=28,993,050 elapsed=193.9s

  [2813/13157] intraday_11648.csv.gz  in=204,521,157 out=29,005,284 elapsed=193.9s

  [2814/13157] intraday_11649.csv.gz  in=204,536,918 out=29,021,045 elapsed=193.9s

  [2815/13157] intraday_1165.csv.gz  in=204,551,221 out=29,021,045 elapsed=193.9s

  [2816/13157] intraday_11651.csv.gz  in=204,564,163 out=29,033,987 elapsed=194.0s

  [2817/13157] intraday_11650.csv.gz  in=204,575,570 out=29,045,394 elapsed=194.0s

  [2818/13157] intraday_11652.csv.gz  in=204,592,542 out=29,062,366 elapsed=194.5s

  [2819/13157] intraday_11655.csv.gz  in=204,601,409 out=29,071,233 elapsed=194.5s

  [2820/13157] intraday_11654.csv.gz  in=204,612,193 out=29,082,017 elapsed=194.5s

  [2821/13157] intraday_11658.csv.gz  in=204,612,322 out=29,082,146 elapsed=194.5s

  [2822/13157] intraday_11656.csv.gz  in=204,620,496 out=29,090,320 elapsed=194.7s

  [2823/13157] intraday_11657.csv.gz  in=204,630,966 out=29,100,790 elapsed=194.9s

  [2824/13157] intraday_11653.csv.gz  in=204,641,044 out=29,110,868 elapsed=194.9s

  [2825/13157] intraday_1166.csv.gz  in=204,652,093 out=29,110,868 elapsed=194.9s

  [2826/13157] intraday_11659.csv.gz  in=204,665,087 out=29,123,862 elapsed=194.9s

  [2827/13157] intraday_11662.csv.gz  in=204,674,818 out=29,133,593 elapsed=195.1s

  [2828/13157] intraday_11660.csv.gz  in=204,686,731 out=29,145,506 elapsed=195.1s

  [2829/13157] intraday_11661.csv.gz  in=204,700,113 out=29,158,888 elapsed=195.1s

  [2830/13157] intraday_11663.csv.gz  in=204,710,578 out=29,169,353 elapsed=195.2s

  [2831/13157] intraday_11664.csv.gz  in=204,723,544 out=29,182,319 elapsed=195.2s

  [2832/13157] intraday_11665.csv.gz  in=204,737,965 out=29,196,740 elapsed=195.2s

  [2833/13157] intraday_11666.csv.gz  in=204,748,893 out=29,207,668 elapsed=195.5s

  [2834/13157] intraday_11669.csv.gz  in=204,760,968 out=29,219,743 elapsed=195.5s

  [2835/13157] intraday_11667.csv.gz  in=204,772,309 out=29,231,084 elapsed=195.5s

  [2836/13157] intraday_11668.csv.gz  in=204,784,557 out=29,243,332 elapsed=195.5s

  [2837/13157] intraday_1167.csv.gz  in=204,796,897 out=29,243,332 elapsed=195.6s

  [2838/13157] intraday_11670.csv.gz  in=204,807,471 out=29,253,906 elapsed=195.6s

  [2839/13157] intraday_11672.csv.gz  in=204,819,448 out=29,265,883 elapsed=195.7s

  [2840/13157] intraday_11671.csv.gz  in=204,831,632 out=29,278,067 elapsed=195.7s

  [2841/13157] intraday_11673.csv.gz  in=204,841,581 out=29,288,016 elapsed=195.7s

  [2842/13157] intraday_11674.csv.gz  in=204,850,760 out=29,297,195 elapsed=195.7s

  [2843/13157] intraday_11677.csv.gz  in=204,862,390 out=29,308,825 elapsed=195.7s

  [2844/13157] intraday_11675.csv.gz  in=204,874,255 out=29,320,690 elapsed=195.7s

  [2845/13157] intraday_11676.csv.gz  in=204,887,774 out=29,334,209 elapsed=195.7s

  [2846/13157] intraday_1168.csv.gz  in=204,899,631 out=29,334,209 elapsed=195.8s

  [2847/13157] intraday_11678.csv.gz  in=204,909,966 out=29,344,544 elapsed=195.8s

  [2848/13157] intraday_11679.csv.gz  in=204,920,660 out=29,355,238 elapsed=195.8s

  [2849/13157] intraday_11682.csv.gz  in=204,932,276 out=29,366,854 elapsed=195.8s

  [2850/13157] intraday_11681.csv.gz  in=204,944,878 out=29,379,456 elapsed=195.8s

  [2851/13157] intraday_11680.csv.gz  in=204,956,781 out=29,391,359 elapsed=195.8s

  [2852/13157] intraday_11683.csv.gz  in=204,969,048 out=29,403,626 elapsed=195.8s

  [2853/13157] intraday_11684.csv.gz  in=204,979,975 out=29,414,553 elapsed=195.9s

  [2854/13157] intraday_11685.csv.gz  in=204,992,177 out=29,426,755 elapsed=195.9s

  [2855/13157] intraday_11687.csv.gz  in=205,002,012 out=29,436,590 elapsed=195.9s

  [2856/13157] intraday_11686.csv.gz  in=205,012,401 out=29,446,979 elapsed=195.9s

  [2857/13157] intraday_1169.csv.gz  in=205,026,220 out=29,446,979 elapsed=195.9s

  [2858/13157] intraday_11688.csv.gz  in=205,038,704 out=29,459,463 elapsed=195.9s

  [2859/13157] intraday_11691.csv.gz  in=205,048,437 out=29,469,196 elapsed=196.0s

  [2860/13157] intraday_11690.csv.gz  in=205,061,151 out=29,481,910 elapsed=196.0s

  [2861/13157] intraday_11689.csv.gz  in=205,074,611 out=29,495,370 elapsed=196.0s

  [2862/13157] intraday_11692.csv.gz  in=205,084,855 out=29,505,614 elapsed=196.0s

  [2863/13157] intraday_11693.csv.gz  in=205,096,725 out=29,517,484 elapsed=196.1s

  [2864/13157] intraday_11696.csv.gz  in=205,108,076 out=29,528,835 elapsed=196.1s

  [2865/13157] intraday_11694.csv.gz  in=205,121,689 out=29,542,448 elapsed=196.1s

  [2866/13157] intraday_11695.csv.gz  in=205,132,267 out=29,553,026 elapsed=196.1s

  [2867/13157] intraday_1170.csv.gz  in=205,142,703 out=29,553,026 elapsed=196.2s

  [2868/13157] intraday_11699.csv.gz  in=205,152,938 out=29,563,261 elapsed=196.2s

  [2869/13157] intraday_11697.csv.gz  in=205,162,730 out=29,573,053 elapsed=196.2s

  [2870/13157] intraday_11698.csv.gz  in=205,173,622 out=29,583,945 elapsed=196.2s

  [2871/13157] intraday_11703.csv.gz  in=205,185,343 out=29,595,666 elapsed=196.3s

  [2872/13157] intraday_11700.csv.gz  in=205,196,633 out=29,606,956 elapsed=196.3s

  [2873/13157] intraday_11705.csv.gz  in=205,206,443 out=29,616,766 elapsed=196.4s

  [2874/13157] intraday_11702.csv.gz  in=205,217,766 out=29,628,089 elapsed=196.4s

  [2875/13157] intraday_11704.csv.gz  in=205,230,497 out=29,640,820 elapsed=196.4s

  [2876/13157] intraday_11701.csv.gz  in=205,243,408 out=29,653,731 elapsed=196.4s

  [2877/13157] intraday_11707.csv.gz  in=205,254,152 out=29,664,475 elapsed=196.4s

  [2878/13157] intraday_11706.csv.gz  in=205,265,972 out=29,676,295 elapsed=196.4s

  [2879/13157] intraday_1171.csv.gz  in=205,276,698 out=29,676,295 elapsed=196.5s

  [2880/13157] intraday_11708.csv.gz  in=205,287,256 out=29,686,853 elapsed=196.5s

  [2881/13157] intraday_11710.csv.gz  in=205,297,198 out=29,696,795 elapsed=196.6s

  [2882/13157] intraday_11709.csv.gz  in=205,308,631 out=29,708,228 elapsed=196.6s

  [2883/13157] intraday_11711.csv.gz  in=205,318,441 out=29,718,038 elapsed=196.6s

  [2884/13157] intraday_11712.csv.gz  in=205,330,569 out=29,730,166 elapsed=196.6s

  [2885/13157] intraday_11714.csv.gz  in=205,341,082 out=29,740,679 elapsed=196.7s

  [2886/13157] intraday_11713.csv.gz  in=205,353,212 out=29,752,809 elapsed=196.7s

  [2887/13157] intraday_11715.csv.gz  in=205,365,162 out=29,764,759 elapsed=196.9s

  [2888/13157] intraday_11716.csv.gz  in=205,376,735 out=29,776,332 elapsed=196.9s

  [2889/13157] intraday_1172.csv.gz  in=205,390,997 out=29,776,332 elapsed=197.2s

  [2890/13157] intraday_11719.csv.gz  in=205,403,019 out=29,788,354 elapsed=197.2s

  [2891/13157] intraday_11717.csv.gz  in=205,413,623 out=29,798,958 elapsed=197.2s

  [2892/13157] intraday_11722.csv.gz  in=205,424,191 out=29,809,526 elapsed=197.2s

  [2893/13157] intraday_11720.csv.gz  in=205,435,709 out=29,821,044 elapsed=197.2s

  [2894/13157] intraday_11718.csv.gz  in=205,447,646 out=29,832,981 elapsed=197.2s

  [2895/13157] intraday_11721.csv.gz  in=205,459,331 out=29,844,666 elapsed=197.2s

  [2896/13157] intraday_11724.csv.gz  in=205,469,639 out=29,854,974 elapsed=197.3s

  [2897/13157] intraday_11723.csv.gz  in=205,480,382 out=29,865,717 elapsed=197.3s

  [2898/13157] intraday_11726.csv.gz  in=205,492,283 out=29,877,618 elapsed=197.3s

  [2899/13157] intraday_11725.csv.gz  in=205,506,276 out=29,891,611 elapsed=197.4s

  [2900/13157] intraday_11728.csv.gz  in=205,518,351 out=29,903,686 elapsed=197.4s

  [2901/13157] intraday_11727.csv.gz  in=205,532,378 out=29,917,713 elapsed=197.4s

  [2902/13157] intraday_11729.csv.gz  in=205,543,053 out=29,928,388 elapsed=197.4s

  [2903/13157] intraday_11731.csv.gz  in=205,554,658 out=29,939,993 elapsed=197.5s

  [2904/13157] intraday_1173.csv.gz  in=205,569,496 out=29,939,993 elapsed=197.5s

  [2905/13157] intraday_11730.csv.gz  in=205,579,775 out=29,950,272 elapsed=197.5s

  [2906/13157] intraday_11732.csv.gz  in=205,592,919 out=29,963,416 elapsed=197.5s

  [2907/13157] intraday_11733.csv.gz  in=205,605,977 out=29,976,474 elapsed=197.5s

  [2908/13157] intraday_11735.csv.gz  in=205,617,271 out=29,987,768 elapsed=197.5s

  [2909/13157] intraday_11734.csv.gz  in=205,628,769 out=29,999,266 elapsed=197.5s

  [2910/13157] intraday_11736.csv.gz  in=205,638,744 out=30,009,241 elapsed=197.5s

  [2911/13157] intraday_1174.csv.gz  in=205,651,416 out=30,009,241 elapsed=197.6s

  [2912/13157] intraday_11739.csv.gz  in=205,661,944 out=30,019,769 elapsed=197.6s

  [2913/13157] intraday_11738.csv.gz  in=205,672,207 out=30,030,032 elapsed=197.6s

  [2914/13157] intraday_11741.csv.gz  in=205,680,652 out=30,038,477 elapsed=197.7s

  [2915/13157] intraday_11737.csv.gz  in=205,694,625 out=30,052,450 elapsed=197.7s

  [2916/13157] intraday_11744.csv.gz  in=205,711,889 out=30,069,714 elapsed=197.8s

  [2917/13157] intraday_11740.csv.gz  in=205,721,867 out=30,079,692 elapsed=197.8s

  [2918/13157] intraday_11742.csv.gz  in=205,732,968 out=30,090,793 elapsed=197.8s

  [2919/13157] intraday_11745.csv.gz  in=205,744,995 out=30,102,820 elapsed=197.9s

  [2920/13157] intraday_11747.csv.gz  in=205,755,105 out=30,112,930 elapsed=198.0s

  [2921/13157] intraday_11743.csv.gz  in=205,767,027 out=30,124,852 elapsed=198.0s

  [2922/13157] intraday_11746.csv.gz  in=205,779,145 out=30,136,970 elapsed=198.4s

  [2923/13157] intraday_1175.csv.gz  in=205,791,234 out=30,136,970 elapsed=198.5s

  [2924/13157] intraday_11749.csv.gz  in=205,800,762 out=30,146,498 elapsed=198.5s

  [2925/13157] intraday_11748.csv.gz  in=205,814,556 out=30,160,292 elapsed=198.6s

  [2926/13157] intraday_11750.csv.gz  in=205,827,491 out=30,173,227 elapsed=198.7s

  [2927/13157] intraday_11751.csv.gz  in=205,838,769 out=30,184,505 elapsed=199.0s

  [2928/13157] intraday_11752.csv.gz  in=205,849,258 out=30,194,994 elapsed=199.0s

  [2929/13157] intraday_11753.csv.gz  in=205,861,050 out=30,206,786 elapsed=199.4s

  [2930/13157] intraday_11754.csv.gz  in=205,874,601 out=30,220,337 elapsed=199.5s

  [2931/13157] intraday_11755.csv.gz  in=205,887,365 out=30,233,101 elapsed=199.5s

  [2932/13157] intraday_11756.csv.gz  in=205,899,036 out=30,244,772 elapsed=199.6s

  [2933/13157] intraday_11757.csv.gz  in=205,911,122 out=30,256,858 elapsed=199.8s

  [2934/13157] intraday_11759.csv.gz  in=205,921,570 out=30,267,306 elapsed=199.9s

  [2935/13157] intraday_11758.csv.gz  in=205,932,951 out=30,278,687 elapsed=199.9s

  [2936/13157] intraday_1176.csv.gz  in=205,945,989 out=30,278,687 elapsed=199.9s

  [2937/13157] intraday_11760.csv.gz  in=205,957,596 out=30,290,294 elapsed=200.2s

  [2938/13157] intraday_11761.csv.gz  in=205,967,110 out=30,299,808 elapsed=200.2s

  [2939/13157] intraday_11762.csv.gz  in=205,978,895 out=30,311,593 elapsed=200.8s

  [2940/13157] intraday_11763.csv.gz  in=205,991,792 out=30,324,490 elapsed=200.8s

  [2941/13157] intraday_11765.csv.gz  in=206,003,008 out=30,335,706 elapsed=200.9s

  [2942/13157] intraday_11764.csv.gz  in=206,015,270 out=30,347,968 elapsed=200.9s

  [2943/13157] intraday_11766.csv.gz  in=206,025,292 out=30,357,990 elapsed=201.1s

  [2944/13157] intraday_11767.csv.gz  in=206,039,376 out=30,372,074 elapsed=201.1s

  [2945/13157] intraday_11768.csv.gz  in=206,049,521 out=30,382,219 elapsed=201.1s

  [2946/13157] intraday_11769.csv.gz  in=206,061,387 out=30,394,085 elapsed=201.2s

  [2947/13157] intraday_1177.csv.gz  in=206,073,460 out=30,394,085 elapsed=201.2s

  [2948/13157] intraday_11770.csv.gz  in=206,086,209 out=30,406,834 elapsed=201.2s

  [2949/13157] intraday_11771.csv.gz  in=206,099,719 out=30,420,344 elapsed=201.4s

  [2950/13157] intraday_11772.csv.gz  in=206,110,189 out=30,430,814 elapsed=201.4s

  [2951/13157] intraday_11773.csv.gz  in=206,123,426 out=30,444,051 elapsed=201.4s

  [2952/13157] intraday_11775.csv.gz  in=206,135,226 out=30,455,851 elapsed=201.4s

  [2953/13157] intraday_11774.csv.gz  in=206,150,840 out=30,471,465 elapsed=201.5s

  [2954/13157] intraday_11777.csv.gz  in=206,164,176 out=30,484,801 elapsed=201.5s

  [2955/13157] intraday_11776.csv.gz  in=206,178,339 out=30,498,964 elapsed=201.6s

  [2956/13157] intraday_1178.csv.gz  in=206,191,897 out=30,498,964 elapsed=201.6s

  [2957/13157] intraday_11778.csv.gz  in=206,208,000 out=30,515,067 elapsed=201.6s

  [2958/13157] intraday_11779.csv.gz  in=206,221,670 out=30,528,737 elapsed=201.6s

  [2959/13157] intraday_11780.csv.gz  in=206,236,141 out=30,543,208 elapsed=201.7s

  [2960/13157] intraday_11781.csv.gz  in=206,246,871 out=30,553,938 elapsed=201.7s

  [2961/13157] intraday_11782.csv.gz  in=206,259,920 out=30,566,987 elapsed=201.7s

  [2962/13157] intraday_11785.csv.gz  in=206,270,644 out=30,577,711 elapsed=201.7s

  [2963/13157] intraday_11786.csv.gz  in=206,281,482 out=30,588,549 elapsed=201.7s

  [2964/13157] intraday_11784.csv.gz  in=206,293,445 out=30,600,512 elapsed=201.7s

  [2965/13157] intraday_11783.csv.gz  in=206,304,757 out=30,611,824 elapsed=201.7s

  [2966/13157] intraday_11787.csv.gz  in=206,317,895 out=30,624,962 elapsed=201.8s

  [2967/13157] intraday_11789.csv.gz  in=206,328,368 out=30,635,435 elapsed=201.8s

  [2968/13157] intraday_11788.csv.gz  in=206,342,089 out=30,649,156 elapsed=201.8s

  [2969/13157] intraday_1179.csv.gz  in=206,357,908 out=30,649,156 elapsed=201.8s

  [2970/13157] intraday_11790.csv.gz  in=206,368,692 out=30,659,940 elapsed=201.8s

  [2971/13157] intraday_11791.csv.gz  in=206,380,249 out=30,671,497 elapsed=201.8s

  [2972/13157] intraday_11792.csv.gz  in=206,392,019 out=30,683,267 elapsed=201.8s

  [2973/13157] intraday_11793.csv.gz  in=206,402,094 out=30,693,342 elapsed=201.8s

  [2974/13157] intraday_11794.csv.gz  in=206,416,535 out=30,707,783 elapsed=201.9s

  [2975/13157] intraday_11796.csv.gz  in=206,429,004 out=30,720,252 elapsed=201.9s

  [2976/13157] intraday_11795.csv.gz  in=206,444,067 out=30,735,315 elapsed=201.9s

  [2977/13157] intraday_11797.csv.gz  in=206,459,750 out=30,750,998 elapsed=201.9s

  [2978/13157] intraday_11798.csv.gz  in=206,470,762 out=30,762,010 elapsed=202.0s

  [2979/13157] intraday_11800.csv.gz  in=206,483,577 out=30,774,825 elapsed=202.0s

  [2980/13157] intraday_1180.csv.gz  in=206,503,195 out=30,774,825 elapsed=202.0s

  [2981/13157] intraday_11799.csv.gz  in=206,515,151 out=30,786,781 elapsed=202.0s

  [2982/13157] intraday_11801.csv.gz  in=206,524,725 out=30,796,355 elapsed=202.0s

  [2983/13157] intraday_11803.csv.gz  in=206,530,796 out=30,802,426 elapsed=202.1s

  [2984/13157] intraday_11805.csv.gz  in=206,539,788 out=30,811,418 elapsed=202.1s

  [2985/13157] intraday_11804.csv.gz  in=206,549,429 out=30,821,059 elapsed=202.1s

  [2986/13157] intraday_11802.csv.gz  in=206,561,059 out=30,832,689 elapsed=202.2s

  [2987/13157] intraday_11808.csv.gz  in=206,574,197 out=30,845,827 elapsed=202.3s

  [2988/13157] intraday_11807.csv.gz  in=206,588,191 out=30,859,821 elapsed=202.3s

  [2989/13157] intraday_11809.csv.gz  in=206,600,763 out=30,872,393 elapsed=202.3s

  [2990/13157] intraday_11806.csv.gz  in=206,623,904 out=30,895,534 elapsed=202.3s

  [2991/13157] intraday_11810.csv.gz  in=206,633,343 out=30,904,973 elapsed=202.4s

  [2992/13157] intraday_1181.csv.gz  in=206,647,883 out=30,904,973 elapsed=202.4s

  [2993/13157] intraday_11811.csv.gz  in=206,659,431 out=30,916,521 elapsed=202.4s

  [2994/13157] intraday_11812.csv.gz  in=206,673,261 out=30,930,351 elapsed=202.4s

  [2995/13157] intraday_11814.csv.gz  in=206,684,989 out=30,942,079 elapsed=202.4s

  [2996/13157] intraday_11813.csv.gz  in=206,699,256 out=30,956,346 elapsed=202.5s

  [2997/13157] intraday_11815.csv.gz  in=206,711,354 out=30,968,444 elapsed=202.5s

  [2998/13157] intraday_11816.csv.gz  in=206,724,259 out=30,981,349 elapsed=202.6s

  [2999/13157] intraday_11817.csv.gz  in=206,736,833 out=30,993,923 elapsed=202.6s

  [3000/13157] intraday_11818.csv.gz  in=206,747,634 out=31,004,724 elapsed=202.6s

  [3001/13157] intraday_11819.csv.gz  in=206,761,026 out=31,018,116 elapsed=202.7s

  [3002/13157] intraday_1182.csv.gz  in=206,775,682 out=31,018,116 elapsed=202.7s

  [3003/13157] intraday_11821.csv.gz  in=206,784,942 out=31,027,376 elapsed=202.7s

  [3004/13157] intraday_11820.csv.gz  in=206,797,687 out=31,040,121 elapsed=202.8s

  [3005/13157] intraday_11824.csv.gz  in=206,812,396 out=31,054,830 elapsed=202.8s

  [3006/13157] intraday_11823.csv.gz  in=206,826,088 out=31,068,522 elapsed=202.8s

  [3007/13157] intraday_11822.csv.gz  in=206,837,460 out=31,079,894 elapsed=202.8s

  [3008/13157] intraday_11828.csv.gz  in=206,849,950 out=31,092,384 elapsed=203.0s

  [3009/13157] intraday_11826.csv.gz  in=206,860,236 out=31,102,670 elapsed=203.0s

  [3010/13157] intraday_11827.csv.gz  in=206,870,971 out=31,113,405 elapsed=203.0s

  [3011/13157] intraday_11825.csv.gz  in=206,881,265 out=31,123,699 elapsed=203.1s

  [3012/13157] intraday_11830.csv.gz  in=206,893,102 out=31,135,536 elapsed=203.2s

  [3013/13157] intraday_1183.csv.gz  in=206,908,105 out=31,135,536 elapsed=203.2s

  [3014/13157] intraday_11831.csv.gz  in=206,921,387 out=31,148,818 elapsed=203.2s

  [3015/13157] intraday_11829.csv.gz  in=206,933,754 out=31,161,185 elapsed=203.3s

  [3016/13157] intraday_11834.csv.gz  in=206,945,701 out=31,173,132 elapsed=203.3s

  [3017/13157] intraday_11833.csv.gz  in=206,957,470 out=31,184,901 elapsed=203.5s

  [3018/13157] intraday_11832.csv.gz  in=206,969,081 out=31,196,512 elapsed=203.5s

  [3019/13157] intraday_11835.csv.gz  in=206,979,142 out=31,206,573 elapsed=203.7s

  [3020/13157] intraday_11836.csv.gz  in=206,991,893 out=31,219,324 elapsed=203.7s

  [3021/13157] intraday_1184.csv.gz  in=207,005,639 out=31,219,324 elapsed=203.9s

  [3022/13157] intraday_11838.csv.gz  in=207,018,680 out=31,232,365 elapsed=203.9s

  [3023/13157] intraday_11837.csv.gz  in=207,032,329 out=31,246,014 elapsed=204.0s

  [3024/13157] intraday_11839.csv.gz  in=207,042,635 out=31,256,320 elapsed=204.0s

  [3025/13157] intraday_11843.csv.gz  in=207,054,499 out=31,268,184 elapsed=204.3s

  [3026/13157] intraday_11840.csv.gz  in=207,066,068 out=31,279,753 elapsed=204.3s

  [3027/13157] intraday_11842.csv.gz  in=207,079,045 out=31,292,730 elapsed=204.3s

  [3028/13157] intraday_11841.csv.gz  in=207,091,519 out=31,305,204 elapsed=204.3s

  [3029/13157] intraday_11847.csv.gz  in=207,103,098 out=31,316,783 elapsed=204.4s

  [3030/13157] intraday_11846.csv.gz  in=207,113,948 out=31,327,633 elapsed=204.4s

  [3031/13157] intraday_11845.csv.gz  in=207,124,678 out=31,338,363 elapsed=204.4s

  [3032/13157] intraday_11848.csv.gz  in=207,138,178 out=31,351,863 elapsed=204.4s

  [3033/13157] intraday_11849.csv.gz  in=207,148,725 out=31,362,410 elapsed=204.4s

  [3034/13157] intraday_11844.csv.gz  in=207,159,507 out=31,373,192 elapsed=204.4s

  [3035/13157] intraday_1185.csv.gz  in=207,171,770 out=31,373,192 elapsed=204.5s

  [3036/13157] intraday_11851.csv.gz  in=207,185,836 out=31,387,258 elapsed=204.6s

  [3037/13157] intraday_11850.csv.gz  in=207,198,308 out=31,399,730 elapsed=204.6s

  [3038/13157] intraday_11852.csv.gz  in=207,210,171 out=31,411,593 elapsed=204.6s

  [3039/13157] intraday_11853.csv.gz  in=207,221,755 out=31,423,177 elapsed=204.8s

  [3040/13157] intraday_11856.csv.gz  in=207,232,088 out=31,433,510 elapsed=204.9s

  [3041/13157] intraday_11855.csv.gz  in=207,244,147 out=31,445,569 elapsed=204.9s

  [3042/13157] intraday_11854.csv.gz  in=207,256,093 out=31,457,515 elapsed=204.9s

  [3043/13157] intraday_11858.csv.gz  in=207,265,285 out=31,466,707 elapsed=205.4s

  [3044/13157] intraday_11857.csv.gz  in=207,277,351 out=31,478,773 elapsed=205.4s

  [3045/13157] intraday_11859.csv.gz  in=207,288,385 out=31,489,807 elapsed=205.5s

  [3046/13157] intraday_1186.csv.gz  in=207,309,947 out=31,489,807 elapsed=205.5s

  [3047/13157] intraday_11860.csv.gz  in=207,320,425 out=31,500,285 elapsed=205.5s

  [3048/13157] intraday_11861.csv.gz  in=207,333,923 out=31,513,783 elapsed=205.5s

  [3049/13157] intraday_11862.csv.gz  in=207,346,974 out=31,526,834 elapsed=205.6s

  [3050/13157] intraday_11863.csv.gz  in=207,358,559 out=31,538,419 elapsed=205.6s

  [3051/13157] intraday_11864.csv.gz  in=207,370,894 out=31,550,754 elapsed=205.6s

  [3052/13157] intraday_11865.csv.gz  in=207,381,467 out=31,561,327 elapsed=205.6s

  [3053/13157] intraday_11866.csv.gz  in=207,392,820 out=31,572,680 elapsed=205.6s

  [3054/13157] intraday_1187.csv.gz  in=207,406,925 out=31,572,680 elapsed=205.7s

  [3055/13157] intraday_11869.csv.gz  in=207,418,193 out=31,583,948 elapsed=205.7s

  [3056/13157] intraday_11868.csv.gz  in=207,428,790 out=31,594,545 elapsed=205.7s

  [3057/13157] intraday_11867.csv.gz  in=207,441,249 out=31,607,004 elapsed=205.7s

  [3058/13157] intraday_11870.csv.gz  in=207,453,810 out=31,619,565 elapsed=205.8s

  [3059/13157] intraday_11871.csv.gz  in=207,463,234 out=31,628,989 elapsed=205.8s

  [3060/13157] intraday_11874.csv.gz  in=207,474,663 out=31,640,418 elapsed=205.8s

  [3061/13157] intraday_11873.csv.gz  in=207,489,319 out=31,655,074 elapsed=205.8s

  [3062/13157] intraday_11875.csv.gz  in=207,503,069 out=31,668,824 elapsed=205.8s

  [3063/13157] intraday_11872.csv.gz  in=207,517,434 out=31,683,189 elapsed=205.8s

  [3064/13157] intraday_11877.csv.gz  in=207,527,022 out=31,692,777 elapsed=205.9s

  [3065/13157] intraday_11876.csv.gz  in=207,537,462 out=31,703,217 elapsed=205.9s

  [3066/13157] intraday_11878.csv.gz  in=207,551,155 out=31,716,910 elapsed=205.9s

  [3067/13157] intraday_11879.csv.gz  in=207,563,983 out=31,729,738 elapsed=205.9s

  [3068/13157] intraday_1188.csv.gz  in=207,575,896 out=31,729,738 elapsed=206.0s

  [3069/13157] intraday_11881.csv.gz  in=207,589,266 out=31,743,108 elapsed=206.0s

  [3070/13157] intraday_11882.csv.gz  in=207,602,241 out=31,756,083 elapsed=206.0s

  [3071/13157] intraday_11880.csv.gz  in=207,613,854 out=31,767,696 elapsed=206.0s

  [3072/13157] intraday_11883.csv.gz  in=207,623,373 out=31,777,215 elapsed=206.0s

  [3073/13157] intraday_11884.csv.gz  in=207,635,088 out=31,788,930 elapsed=206.1s

  [3074/13157] intraday_11886.csv.gz  in=207,645,452 out=31,799,294 elapsed=206.1s

  [3075/13157] intraday_11888.csv.gz  in=207,654,142 out=31,807,984 elapsed=206.1s

  [3076/13157] intraday_11885.csv.gz  in=207,667,567 out=31,821,409 elapsed=206.1s

  [3077/13157] intraday_11887.csv.gz  in=207,677,133 out=31,830,975 elapsed=206.2s

  [3078/13157] intraday_1189.csv.gz  in=207,690,286 out=31,830,975 elapsed=206.2s

  [3079/13157] intraday_11890.csv.gz  in=207,703,037 out=31,843,726 elapsed=206.2s

  [3080/13157] intraday_11889.csv.gz  in=207,714,156 out=31,854,845 elapsed=206.2s

  [3081/13157] intraday_11894.csv.gz  in=207,725,513 out=31,866,202 elapsed=206.7s

  [3082/13157] intraday_11891.csv.gz  in=207,739,583 out=31,880,272 elapsed=206.7s

  [3083/13157] intraday_11893.csv.gz  in=207,751,704 out=31,892,393 elapsed=206.7s

  [3084/13157] intraday_11892.csv.gz  in=207,768,052 out=31,908,741 elapsed=206.7s

  [3085/13157] intraday_11895.csv.gz  in=207,779,459 out=31,920,148 elapsed=206.8s

  [3086/13157] intraday_11896.csv.gz  in=207,791,719 out=31,932,408 elapsed=206.9s

  [3087/13157] intraday_11898.csv.gz  in=207,802,857 out=31,943,546 elapsed=206.9s

  [3088/13157] intraday_11897.csv.gz  in=207,816,860 out=31,957,549 elapsed=206.9s

  [3089/13157] intraday_11899.csv.gz  in=207,827,878 out=31,968,567 elapsed=206.9s

  [3090/13157] intraday_1190.csv.gz  in=207,840,106 out=31,968,567 elapsed=207.0s

  [3091/13157] intraday_11901.csv.gz  in=207,852,754 out=31,981,215 elapsed=207.0s

  [3092/13157] intraday_11902.csv.gz  in=207,865,272 out=31,993,733 elapsed=207.0s

  [3093/13157] intraday_11900.csv.gz  in=207,879,134 out=32,007,595 elapsed=207.0s

  [3094/13157] intraday_11903.csv.gz  in=207,891,426 out=32,019,887 elapsed=207.2s

  [3095/13157] intraday_11906.csv.gz  in=207,903,419 out=32,031,880 elapsed=207.3s

  [3096/13157] intraday_11905.csv.gz  in=207,915,699 out=32,044,160 elapsed=207.3s

  [3097/13157] intraday_11904.csv.gz  in=207,927,459 out=32,055,920 elapsed=207.3s

  [3098/13157] intraday_11907.csv.gz  in=207,940,044 out=32,068,505 elapsed=207.3s

  [3099/13157] intraday_11908.csv.gz  in=207,951,043 out=32,079,504 elapsed=207.4s

  [3100/13157] intraday_11909.csv.gz  in=207,963,631 out=32,092,092 elapsed=207.4s

  [3101/13157] intraday_1191.csv.gz  in=207,976,089 out=32,092,092 elapsed=207.4s

  [3102/13157] intraday_11910.csv.gz  in=207,989,553 out=32,105,556 elapsed=207.4s

  [3103/13157] intraday_11912.csv.gz  in=208,001,236 out=32,117,239 elapsed=207.5s

  [3104/13157] intraday_11911.csv.gz  in=208,013,051 out=32,129,054 elapsed=207.5s

  [3105/13157] intraday_11913.csv.gz  in=208,024,274 out=32,140,277 elapsed=207.6s

  [3106/13157] intraday_11916.csv.gz  in=208,035,684 out=32,151,687 elapsed=207.7s

  [3107/13157] intraday_11915.csv.gz  in=208,045,937 out=32,161,940 elapsed=208.1s

  [3108/13157] intraday_11914.csv.gz  in=208,060,395 out=32,176,398 elapsed=208.1s

  [3109/13157] intraday_11917.csv.gz  in=208,074,172 out=32,190,175 elapsed=208.3s

  [3110/13157] intraday_11918.csv.gz  in=208,087,800 out=32,203,803 elapsed=208.3s

  [3111/13157] intraday_11919.csv.gz  in=208,097,958 out=32,213,961 elapsed=208.5s

  [3112/13157] intraday_1192.csv.gz  in=208,110,192 out=32,213,961 elapsed=208.6s

  [3113/13157] intraday_11920.csv.gz  in=208,122,993 out=32,226,762 elapsed=208.7s

  [3114/13157] intraday_11921.csv.gz  in=208,137,540 out=32,241,309 elapsed=208.9s

  [3115/13157] intraday_11923.csv.gz  in=208,150,363 out=32,254,132 elapsed=208.9s

  [3116/13157] intraday_11924.csv.gz  in=208,165,153 out=32,268,922 elapsed=208.9s

  [3117/13157] intraday_11922.csv.gz  in=208,179,512 out=32,283,281 elapsed=208.9s

  [3118/13157] intraday_11928.csv.gz  in=208,191,334 out=32,295,103 elapsed=209.3s

  [3119/13157] intraday_11925.csv.gz  in=208,208,524 out=32,312,293 elapsed=209.3s

  [3120/13157] intraday_11926.csv.gz  in=208,222,519 out=32,326,288 elapsed=209.3s

  [3121/13157] intraday_11927.csv.gz  in=208,236,434 out=32,340,203 elapsed=209.3s

  [3122/13157] intraday_11929.csv.gz  in=208,249,067 out=32,352,836 elapsed=209.5s

  [3123/13157] intraday_1193.csv.gz  in=208,261,050 out=32,352,836 elapsed=209.5s

  [3124/13157] intraday_11930.csv.gz  in=208,273,607 out=32,365,393 elapsed=209.5s

  [3125/13157] intraday_11931.csv.gz  in=208,286,106 out=32,377,892 elapsed=209.5s

  [3126/13157] intraday_11932.csv.gz  in=208,297,551 out=32,389,337 elapsed=209.6s

  [3127/13157] intraday_11934.csv.gz  in=208,309,572 out=32,401,358 elapsed=209.6s

  [3128/13157] intraday_11935.csv.gz  in=208,324,704 out=32,416,490 elapsed=209.6s

  [3129/13157] intraday_11933.csv.gz  in=208,337,586 out=32,429,372 elapsed=209.6s

  [3130/13157] intraday_11936.csv.gz  in=208,347,793 out=32,439,579 elapsed=209.6s

  [3131/13157] intraday_11937.csv.gz  in=208,359,064 out=32,450,850 elapsed=209.7s

  [3132/13157] intraday_11938.csv.gz  in=208,370,369 out=32,462,155 elapsed=209.7s

  [3133/13157] intraday_1194.csv.gz  in=208,388,060 out=32,462,155 elapsed=209.7s

  [3134/13157] intraday_11939.csv.gz  in=208,399,840 out=32,473,935 elapsed=209.7s

  [3135/13157] intraday_11940.csv.gz  in=208,410,845 out=32,484,940 elapsed=209.8s

  [3136/13157] intraday_11943.csv.gz  in=208,424,459 out=32,498,554 elapsed=209.8s

  [3137/13157] intraday_11941.csv.gz  in=208,437,601 out=32,511,696 elapsed=209.8s

  [3138/13157] intraday_11942.csv.gz  in=208,452,515 out=32,526,610 elapsed=209.8s

  [3139/13157] intraday_11945.csv.gz  in=208,464,868 out=32,538,963 elapsed=209.9s

  [3140/13157] intraday_11946.csv.gz  in=208,476,394 out=32,550,489 elapsed=209.9s

  [3141/13157] intraday_11947.csv.gz  in=208,488,775 out=32,562,870 elapsed=210.1s

  [3142/13157] intraday_11944.csv.gz  in=208,504,406 out=32,578,501 elapsed=210.1s

  [3143/13157] intraday_11948.csv.gz  in=208,515,163 out=32,589,258 elapsed=210.1s

  [3144/13157] intraday_1195.csv.gz  in=208,525,006 out=32,589,258 elapsed=210.2s

  [3145/13157] intraday_11950.csv.gz  in=208,531,543 out=32,595,795 elapsed=210.2s

  [3146/13157] intraday_11949.csv.gz  in=208,544,007 out=32,608,259 elapsed=210.2s

  [3147/13157] intraday_11952.csv.gz  in=208,555,077 out=32,619,329 elapsed=210.3s

  [3148/13157] intraday_11951.csv.gz  in=208,567,633 out=32,631,885 elapsed=210.3s

  [3149/13157] intraday_11953.csv.gz  in=208,583,248 out=32,647,500 elapsed=210.3s

  [3150/13157] intraday_11955.csv.gz  in=208,596,355 out=32,660,607 elapsed=210.4s

  [3151/13157] intraday_11956.csv.gz  in=208,607,453 out=32,671,705 elapsed=210.4s

  [3152/13157] intraday_11957.csv.gz  in=208,619,414 out=32,683,666 elapsed=210.4s

  [3153/13157] intraday_11954.csv.gz  in=208,632,610 out=32,696,862 elapsed=210.4s

  [3154/13157] intraday_11960.csv.gz  in=208,644,057 out=32,708,309 elapsed=210.5s

  [3155/13157] intraday_11958.csv.gz  in=208,658,721 out=32,722,973 elapsed=210.5s

  [3156/13157] intraday_1196.csv.gz  in=208,678,604 out=32,722,973 elapsed=210.6s

  [3157/13157] intraday_11959.csv.gz  in=208,695,078 out=32,739,447 elapsed=210.6s

  [3158/13157] intraday_11961.csv.gz  in=208,707,088 out=32,751,457 elapsed=210.7s

  [3159/13157] intraday_11962.csv.gz  in=208,720,958 out=32,765,327 elapsed=210.7s

  [3160/13157] intraday_11963.csv.gz  in=208,734,068 out=32,778,437 elapsed=210.7s

  [3161/13157] intraday_11964.csv.gz  in=208,745,424 out=32,789,793 elapsed=210.7s

  [3162/13157] intraday_11965.csv.gz  in=208,758,755 out=32,803,124 elapsed=210.8s

  [3163/13157] intraday_11967.csv.gz  in=208,768,636 out=32,813,005 elapsed=210.8s

  [3164/13157] intraday_11968.csv.gz  in=208,779,945 out=32,824,314 elapsed=210.8s

  [3165/13157] intraday_11970.csv.gz  in=208,793,178 out=32,837,547 elapsed=210.9s

  [3166/13157] intraday_11966.csv.gz  in=208,805,720 out=32,850,089 elapsed=210.9s

  [3167/13157] intraday_1197.csv.gz  in=208,820,908 out=32,850,089 elapsed=210.9s

  [3168/13157] intraday_11969.csv.gz  in=208,834,834 out=32,864,015 elapsed=210.9s

  [3169/13157] intraday_11972.csv.gz  in=208,846,157 out=32,875,338 elapsed=211.1s

  [3170/13157] intraday_11971.csv.gz  in=208,858,586 out=32,887,767 elapsed=211.1s

  [3171/13157] intraday_11974.csv.gz  in=208,870,697 out=32,899,878 elapsed=211.1s

  [3172/13157] intraday_11973.csv.gz  in=208,881,412 out=32,910,593 elapsed=211.2s

  [3173/13157] intraday_11977.csv.gz  in=208,893,760 out=32,922,941 elapsed=211.2s

  [3174/13157] intraday_11975.csv.gz  in=208,906,766 out=32,935,947 elapsed=211.2s

  [3175/13157] intraday_11976.csv.gz  in=208,919,831 out=32,949,012 elapsed=211.2s

  [3176/13157] intraday_11978.csv.gz  in=208,931,890 out=32,961,071 elapsed=211.3s

  [3177/13157] intraday_11979.csv.gz  in=208,943,685 out=32,972,866 elapsed=211.3s

  [3178/13157] intraday_1198.csv.gz  in=208,959,137 out=32,972,866 elapsed=211.4s

  [3179/13157] intraday_11982.csv.gz  in=208,972,125 out=32,985,854 elapsed=211.4s

  [3180/13157] intraday_11981.csv.gz  in=208,983,582 out=32,997,311 elapsed=211.5s

  [3181/13157] intraday_11983.csv.gz  in=208,997,980 out=33,011,709 elapsed=211.5s

  [3182/13157] intraday_11980.csv.gz  in=209,017,017 out=33,030,746 elapsed=211.5s

  [3183/13157] intraday_11984.csv.gz  in=209,030,441 out=33,044,170 elapsed=211.5s

  [3184/13157] intraday_11986.csv.gz  in=209,042,924 out=33,056,653 elapsed=211.6s

  [3185/13157] intraday_11985.csv.gz  in=209,053,209 out=33,066,938 elapsed=211.6s

  [3186/13157] intraday_11987.csv.gz  in=209,066,519 out=33,080,248 elapsed=211.6s

  [3187/13157] intraday_1199.csv.gz  in=209,080,231 out=33,080,248 elapsed=211.6s

  [3188/13157] intraday_11989.csv.gz  in=209,092,584 out=33,092,601 elapsed=211.6s

  [3189/13157] intraday_11988.csv.gz  in=209,106,154 out=33,106,171 elapsed=211.6s

  [3190/13157] intraday_11992.csv.gz  in=209,118,453 out=33,118,470 elapsed=211.8s

  [3191/13157] intraday_11991.csv.gz  in=209,129,839 out=33,129,856 elapsed=211.8s

  [3192/13157] intraday_11993.csv.gz  in=209,141,130 out=33,141,147 elapsed=211.8s

  [3193/13157] intraday_11990.csv.gz  in=209,152,242 out=33,152,259 elapsed=211.9s

  [3194/13157] intraday_11994.csv.gz  in=209,164,519 out=33,164,536 elapsed=211.9s

  [3195/13157] intraday_11996.csv.gz  in=209,176,569 out=33,176,586 elapsed=211.9s

  [3196/13157] intraday_11995.csv.gz  in=209,190,096 out=33,190,113 elapsed=211.9s

  [3197/13157] intraday_11998.csv.gz  in=209,202,359 out=33,202,376 elapsed=211.9s

  [3198/13157] intraday_11999.csv.gz  in=209,214,260 out=33,214,277 elapsed=211.9s

  [3199/13157] intraday_1200.csv.gz  in=209,237,516 out=33,214,277 elapsed=212.0s

  [3200/13157] intraday_12000.csv.gz  in=209,250,003 out=33,226,764 elapsed=212.0s

  [3201/13157] intraday_11997.csv.gz  in=209,266,589 out=33,243,350 elapsed=212.0s

  [3202/13157] intraday_12003.csv.gz  in=209,279,240 out=33,256,001 elapsed=212.0s

  [3203/13157] intraday_12002.csv.gz  in=209,289,413 out=33,266,174 elapsed=212.0s

  [3204/13157] intraday_12001.csv.gz  in=209,301,994 out=33,278,755 elapsed=212.0s

  [3205/13157] intraday_12004.csv.gz  in=209,312,779 out=33,289,540 elapsed=212.0s

  [3206/13157] intraday_12005.csv.gz  in=209,323,494 out=33,300,255 elapsed=212.0s

  [3207/13157] intraday_12006.csv.gz  in=209,336,323 out=33,313,084 elapsed=212.1s

  [3208/13157] intraday_12007.csv.gz  in=209,349,876 out=33,326,637 elapsed=212.1s

  [3209/13157] intraday_12008.csv.gz  in=209,362,220 out=33,338,981 elapsed=212.1s

  [3210/13157] intraday_1201.csv.gz  in=209,375,350 out=33,338,981 elapsed=212.1s

  [3211/13157] intraday_12009.csv.gz  in=209,388,192 out=33,351,823 elapsed=212.1s

  [3212/13157] intraday_12010.csv.gz  in=209,401,071 out=33,364,702 elapsed=212.2s

  [3213/13157] intraday_12011.csv.gz  in=209,411,445 out=33,375,076 elapsed=212.2s

  [3214/13157] intraday_12012.csv.gz  in=209,423,480 out=33,387,111 elapsed=212.2s

  [3215/13157] intraday_12014.csv.gz  in=209,434,886 out=33,398,517 elapsed=212.2s

  [3216/13157] intraday_12013.csv.gz  in=209,447,465 out=33,411,096 elapsed=212.2s

  [3217/13157] intraday_12015.csv.gz  in=209,459,444 out=33,423,075 elapsed=212.2s

  [3218/13157] intraday_12016.csv.gz  in=209,471,344 out=33,434,975 elapsed=212.4s

  [3219/13157] intraday_12017.csv.gz  in=209,481,183 out=33,444,814 elapsed=212.4s

  [3220/13157] intraday_12018.csv.gz  in=209,492,432 out=33,456,063 elapsed=212.5s

  [3221/13157] intraday_12019.csv.gz  in=209,514,694 out=33,478,325 elapsed=212.5s

  [3222/13157] intraday_1202.csv.gz  in=209,528,204 out=33,478,325 elapsed=212.7s

  [3223/13157] intraday_12020.csv.gz  in=209,541,855 out=33,491,976 elapsed=212.7s

  [3224/13157] intraday_12021.csv.gz  in=209,556,052 out=33,506,173 elapsed=212.7s

  [3225/13157] intraday_12022.csv.gz  in=209,568,497 out=33,518,618 elapsed=212.7s

  [3226/13157] intraday_12026.csv.gz  in=209,581,054 out=33,531,175 elapsed=213.0s

  [3227/13157] intraday_12025.csv.gz  in=209,593,912 out=33,544,033 elapsed=213.0s

  [3228/13157] intraday_12024.csv.gz  in=209,605,799 out=33,555,920 elapsed=213.0s

  [3229/13157] intraday_12023.csv.gz  in=209,616,120 out=33,566,241 elapsed=213.0s

  [3230/13157] intraday_12027.csv.gz  in=209,630,256 out=33,580,377 elapsed=213.0s

  [3231/13157] intraday_12028.csv.gz  in=209,642,574 out=33,592,695 elapsed=213.0s

  [3232/13157] intraday_12029.csv.gz  in=209,653,430 out=33,603,551 elapsed=213.2s

  [3233/13157] intraday_1203.csv.gz  in=209,666,902 out=33,603,551 elapsed=213.3s

  [3234/13157] intraday_12030.csv.gz  in=209,677,742 out=33,614,391 elapsed=213.3s

  [3235/13157] intraday_12031.csv.gz  in=209,691,451 out=33,628,100 elapsed=213.3s

  [3236/13157] intraday_12034.csv.gz  in=209,702,013 out=33,638,662 elapsed=213.3s

  [3237/13157] intraday_12032.csv.gz  in=209,714,084 out=33,650,733 elapsed=213.3s

  [3238/13157] intraday_12033.csv.gz  in=209,725,901 out=33,662,550 elapsed=213.3s

  [3239/13157] intraday_12035.csv.gz  in=209,735,497 out=33,672,146 elapsed=213.3s

  [3240/13157] intraday_12036.csv.gz  in=209,747,534 out=33,684,183 elapsed=213.4s

  [3241/13157] intraday_12037.csv.gz  in=209,763,158 out=33,699,807 elapsed=213.5s

  [3242/13157] intraday_12039.csv.gz  in=209,776,340 out=33,712,989 elapsed=213.5s

  [3243/13157] intraday_1204.csv.gz  in=209,787,435 out=33,712,989 elapsed=213.5s

  [3244/13157] intraday_12038.csv.gz  in=209,806,090 out=33,731,644 elapsed=213.5s

  [3245/13157] intraday_12040.csv.gz  in=209,817,883 out=33,743,437 elapsed=213.5s

  [3246/13157] intraday_12041.csv.gz  in=209,828,326 out=33,753,880 elapsed=213.5s

  [3247/13157] intraday_12042.csv.gz  in=209,842,147 out=33,767,701 elapsed=213.5s

  [3248/13157] intraday_12043.csv.gz  in=209,853,187 out=33,778,741 elapsed=213.6s

  [3249/13157] intraday_12045.csv.gz  in=209,863,498 out=33,789,052 elapsed=213.6s

  [3250/13157] intraday_12046.csv.gz  in=209,875,406 out=33,800,960 elapsed=213.7s

  [3251/13157] intraday_12044.csv.gz  in=209,890,853 out=33,816,407 elapsed=213.7s

  [3252/13157] intraday_12047.csv.gz  in=209,905,151 out=33,830,705 elapsed=213.7s

  [3253/13157] intraday_12048.csv.gz  in=209,919,100 out=33,844,654 elapsed=213.7s

  [3254/13157] intraday_12049.csv.gz  in=209,931,736 out=33,857,290 elapsed=213.7s

  [3255/13157] intraday_1205.csv.gz  in=209,945,820 out=33,857,290 elapsed=213.7s

  [3256/13157] intraday_12050.csv.gz  in=209,958,429 out=33,869,899 elapsed=213.7s

  [3257/13157] intraday_12051.csv.gz  in=209,971,505 out=33,882,975 elapsed=213.8s

  [3258/13157] intraday_12052.csv.gz  in=209,982,484 out=33,893,954 elapsed=213.8s

  [3259/13157] intraday_12055.csv.gz  in=209,994,501 out=33,905,971 elapsed=213.9s

  [3260/13157] intraday_12054.csv.gz  in=210,007,878 out=33,919,348 elapsed=213.9s

  [3261/13157] intraday_12053.csv.gz  in=210,018,871 out=33,930,341 elapsed=213.9s

  [3262/13157] intraday_12057.csv.gz  in=210,032,407 out=33,943,877 elapsed=213.9s

  [3263/13157] intraday_12056.csv.gz  in=210,044,646 out=33,956,116 elapsed=213.9s

  [3264/13157] intraday_12058.csv.gz  in=210,057,080 out=33,968,550 elapsed=213.9s

  [3265/13157] intraday_12060.csv.gz  in=210,070,136 out=33,981,606 elapsed=214.0s

  [3266/13157] intraday_1206.csv.gz  in=210,087,804 out=33,981,606 elapsed=214.0s

  [3267/13157] intraday_12061.csv.gz  in=210,101,498 out=33,995,300 elapsed=214.0s

  [3268/13157] intraday_12059.csv.gz  in=210,113,322 out=34,007,124 elapsed=214.0s

  [3269/13157] intraday_12063.csv.gz  in=210,125,649 out=34,019,451 elapsed=214.0s

  [3270/13157] intraday_12064.csv.gz  in=210,139,072 out=34,032,874 elapsed=214.0s

  [3271/13157] intraday_12062.csv.gz  in=210,151,299 out=34,045,101 elapsed=214.1s

  [3272/13157] intraday_12065.csv.gz  in=210,165,103 out=34,058,905 elapsed=214.1s

  [3273/13157] intraday_12066.csv.gz  in=210,175,978 out=34,069,780 elapsed=214.2s

  [3274/13157] intraday_12067.csv.gz  in=210,190,249 out=34,084,051 elapsed=214.2s

  [3275/13157] intraday_12069.csv.gz  in=210,203,795 out=34,097,597 elapsed=214.2s

  [3276/13157] intraday_1207.csv.gz  in=210,216,274 out=34,097,597 elapsed=214.5s

  [3277/13157] intraday_12068.csv.gz  in=210,234,461 out=34,115,784 elapsed=214.6s

  [3278/13157] intraday_12071.csv.gz  in=210,251,387 out=34,132,710 elapsed=214.6s

  [3279/13157] intraday_12070.csv.gz  in=210,266,489 out=34,147,812 elapsed=214.7s

  [3280/13157] intraday_12074.csv.gz  in=210,281,972 out=34,163,295 elapsed=214.7s

  [3281/13157] intraday_12073.csv.gz  in=210,297,532 out=34,178,855 elapsed=214.7s

  [3282/13157] intraday_12076.csv.gz  in=210,310,610 out=34,191,933 elapsed=214.9s

  [3283/13157] intraday_12077.csv.gz  in=210,322,741 out=34,204,064 elapsed=214.9s

  [3284/13157] intraday_12075.csv.gz  in=210,335,095 out=34,216,418 elapsed=214.9s

  [3285/13157] intraday_12072.csv.gz  in=210,349,982 out=34,231,305 elapsed=214.9s

  [3286/13157] intraday_12078.csv.gz  in=210,362,049 out=34,243,372 elapsed=215.1s

  [3287/13157] intraday_12079.csv.gz  in=210,373,950 out=34,255,273 elapsed=215.1s

  [3288/13157] intraday_12080.csv.gz  in=210,386,487 out=34,267,810 elapsed=215.1s

  [3289/13157] intraday_1208.csv.gz  in=210,411,414 out=34,267,810 elapsed=215.1s

  [3290/13157] intraday_12081.csv.gz  in=210,424,427 out=34,280,823 elapsed=215.3s

  [3291/13157] intraday_12083.csv.gz  in=210,436,328 out=34,292,724 elapsed=215.3s

  [3292/13157] intraday_12082.csv.gz  in=210,451,538 out=34,307,934 elapsed=215.3s

  [3293/13157] intraday_12084.csv.gz  in=210,462,154 out=34,318,550 elapsed=215.3s

  [3294/13157] intraday_12087.csv.gz  in=210,474,942 out=34,331,338 elapsed=215.3s

  [3295/13157] intraday_12086.csv.gz  in=210,485,612 out=34,342,008 elapsed=215.3s

  [3296/13157] intraday_12085.csv.gz  in=210,498,683 out=34,355,079 elapsed=215.3s

  [3297/13157] intraday_12088.csv.gz  in=210,512,976 out=34,369,372 elapsed=215.4s

  [3298/13157] intraday_12089.csv.gz  in=210,528,611 out=34,385,007 elapsed=215.4s

  [3299/13157] intraday_1209.csv.gz  in=210,545,934 out=34,385,007 elapsed=215.4s

  [3300/13157] intraday_12090.csv.gz  in=210,560,042 out=34,399,115 elapsed=215.4s

  [3301/13157] intraday_12093.csv.gz  in=210,572,908 out=34,411,981 elapsed=215.4s

  [3302/13157] intraday_12094.csv.gz  in=210,584,741 out=34,423,814 elapsed=215.4s

  [3303/13157] intraday_12092.csv.gz  in=210,596,826 out=34,435,899 elapsed=215.5s

  [3304/13157] intraday_12091.csv.gz  in=210,611,162 out=34,450,235 elapsed=215.5s

  [3305/13157] intraday_12096.csv.gz  in=210,620,115 out=34,459,188 elapsed=215.5s

  [3306/13157] intraday_12095.csv.gz  in=210,635,748 out=34,474,821 elapsed=215.5s

  [3307/13157] intraday_12097.csv.gz  in=210,642,871 out=34,481,944 elapsed=215.7s

  [3308/13157] intraday_12098.csv.gz  in=210,654,864 out=34,493,937 elapsed=215.7s

  [3309/13157] intraday_1210.csv.gz  in=210,687,301 out=34,493,937 elapsed=215.7s

  [3310/13157] intraday_12099.csv.gz  in=210,693,168 out=34,499,804 elapsed=215.7s

  [3311/13157] intraday_12101.csv.gz  in=210,952,363 out=34,684,610 elapsed=216.6s

  [3312/13157] intraday_12102.csv.gz  in=211,252,826 out=34,901,107 elapsed=216.6s

  [3313/13157] intraday_12103.csv.gz  in=211,492,811 out=35,071,326 elapsed=216.6s

  [3314/13157] intraday_12100.csv.gz  in=211,820,512 out=35,305,954 elapsed=216.7s

  [3315/13157] intraday_12105.csv.gz  in=212,134,721 out=35,533,855 elapsed=217.7s

  [3316/13157] intraday_12107.csv.gz  in=212,404,302 out=35,722,952 elapsed=217.7s

  [3317/13157] intraday_12106.csv.gz  in=212,731,936 out=35,957,818 elapsed=217.7s

  [3318/13157] intraday_12104.csv.gz  in=213,052,933 out=36,186,554 elapsed=217.7s

  [3319/13157] intraday_1211.csv.gz  in=213,064,749 out=36,186,554 elapsed=217.8s

  [3320/13157] intraday_12108.csv.gz  in=213,365,675 out=36,397,490 elapsed=219.2s

  [3321/13157] intraday_12109.csv.gz  in=213,663,648 out=36,608,049 elapsed=219.3s

  [3322/13157] intraday_12111.csv.gz  in=213,940,481 out=36,807,368 elapsed=219.3s

  [3323/13157] intraday_12110.csv.gz  in=214,254,888 out=37,034,840 elapsed=219.3s

  [3324/13157] intraday_12114.csv.gz  in=214,469,781 out=37,187,924 elapsed=220.3s

  [3325/13157] intraday_12112.csv.gz  in=214,733,480 out=37,378,241 elapsed=220.5s

  [3326/13157] intraday_12115.csv.gz  in=214,964,170 out=37,545,503 elapsed=220.5s

  [3327/13157] intraday_12113.csv.gz  in=215,251,420 out=37,751,330 elapsed=220.6s

  [3328/13157] intraday_12116.csv.gz  in=215,572,984 out=37,981,053 elapsed=220.8s

  [3329/13157] intraday_1212.csv.gz  in=215,588,821 out=37,981,053 elapsed=220.9s

  [3330/13157] intraday_12119.csv.gz  in=215,813,757 out=38,141,330 elapsed=220.9s

  [3331/13157] intraday_12118.csv.gz  in=216,066,121 out=38,324,811 elapsed=221.1s

  [3332/13157] intraday_12117.csv.gz  in=216,363,515 out=38,535,344 elapsed=221.1s

  [3333/13157] intraday_12120.csv.gz  in=216,642,107 out=38,736,405 elapsed=222.6s

  [3334/13157] intraday_12121.csv.gz  in=216,908,945 out=38,928,130 elapsed=225.6s

  [3335/13157] intraday_12122.csv.gz  in=217,160,061 out=39,110,568 elapsed=225.7s

  [3336/13157] intraday_12124.csv.gz  in=217,439,629 out=39,310,121 elapsed=225.8s

  [3337/13157] intraday_12123.csv.gz  in=217,720,659 out=39,519,435 elapsed=225.8s

  [3338/13157] intraday_12125.csv.gz  in=217,970,495 out=39,695,325 elapsed=226.3s

  [3339/13157] intraday_12126.csv.gz  in=218,194,535 out=39,855,016 elapsed=226.3s

  [3340/13157] intraday_12128.csv.gz  in=218,446,277 out=40,033,691 elapsed=226.4s

  [3341/13157] intraday_1213.csv.gz  in=218,467,966 out=40,033,691 elapsed=226.5s

  [3342/13157] intraday_12127.csv.gz  in=218,733,193 out=40,224,104 elapsed=226.5s

  [3343/13157] intraday_12132.csv.gz  in=218,965,852 out=40,385,619 elapsed=227.5s

  [3344/13157] intraday_12129.csv.gz  in=219,258,152 out=40,595,872 elapsed=227.5s

  [3345/13157] intraday_12131.csv.gz  in=219,530,495 out=40,790,122 elapsed=227.6s

  [3346/13157] intraday_12130.csv.gz  in=219,916,195 out=41,063,854 elapsed=227.6s

  [3347/13157] intraday_12134.csv.gz  in=220,208,805 out=41,271,566 elapsed=228.9s

  [3348/13157] intraday_12136.csv.gz  in=220,465,296 out=41,456,018 elapsed=229.0s

  [3349/13157] intraday_12133.csv.gz  in=220,763,867 out=41,667,506 elapsed=229.0s

  [3350/13157] intraday_12135.csv.gz  in=221,017,636 out=41,847,021 elapsed=229.2s

  [3351/13157] intraday_1214.csv.gz  in=221,033,314 out=41,847,021 elapsed=229.3s

  [3352/13157] intraday_12137.csv.gz  in=221,257,801 out=42,006,505 elapsed=229.3s

  [3353/13157] intraday_12139.csv.gz  in=221,484,570 out=42,172,237 elapsed=229.7s

  [3354/13157] intraday_12140.csv.gz  in=221,729,407 out=42,345,411 elapsed=230.1s

  [3355/13157] intraday_12141.csv.gz  in=222,000,562 out=42,540,540 elapsed=230.1s

  [3356/13157] intraday_12138.csv.gz  in=222,291,389 out=42,752,054 elapsed=230.1s

  [3357/13157] intraday_12142.csv.gz  in=222,558,052 out=42,941,242 elapsed=230.3s

  [3358/13157] intraday_12143.csv.gz  in=222,834,841 out=43,137,792 elapsed=231.2s

  [3359/13157] intraday_12144.csv.gz  in=223,139,207 out=43,354,606 elapsed=231.5s

  [3360/13157] intraday_12145.csv.gz  in=223,382,869 out=43,528,446 elapsed=231.5s

  [3361/13157] intraday_12146.csv.gz  in=223,626,012 out=43,703,730 elapsed=232.0s

  [3362/13157] intraday_12148.csv.gz  in=223,843,653 out=43,858,910 elapsed=232.1s

  [3363/13157] intraday_12149.csv.gz  in=224,082,721 out=44,033,077 elapsed=232.1s

  [3364/13157] intraday_12147.csv.gz  in=224,372,626 out=44,240,290 elapsed=232.1s

  [3365/13157] intraday_1215.csv.gz  in=224,385,444 out=44,240,290 elapsed=232.1s

  [3366/13157] intraday_12150.csv.gz  in=224,629,207 out=44,414,922 elapsed=232.9s

  [3367/13157] intraday_12152.csv.gz  in=224,965,887 out=44,659,726 elapsed=233.1s

  [3368/13157] intraday_12154.csv.gz  in=225,218,785 out=44,842,645 elapsed=233.3s

  [3369/13157] intraday_12151.csv.gz  in=225,438,652 out=44,997,811 elapsed=234.2s

  [3370/13157] intraday_12153.csv.gz  in=225,680,141 out=45,171,122 elapsed=235.0s

  [3371/13157] intraday_12156.csv.gz  in=225,962,832 out=45,373,139 elapsed=235.1s

  [3372/13157] intraday_12157.csv.gz  in=226,215,956 out=45,560,885 elapsed=235.8s

  [3373/13157] intraday_1216.csv.gz  in=226,230,375 out=45,560,885 elapsed=235.9s

  [3374/13157] intraday_12158.csv.gz  in=226,500,291 out=45,761,406 elapsed=236.1s

  [3375/13157] intraday_12155.csv.gz  in=226,807,839 out=45,982,927 elapsed=236.4s

  [3376/13157] intraday_12161.csv.gz  in=227,045,723 out=46,154,331 elapsed=237.3s

  [3377/13157] intraday_12159.csv.gz  in=227,290,102 out=46,328,941 elapsed=237.5s

  [3378/13157] intraday_12162.csv.gz  in=227,542,114 out=46,511,413 elapsed=237.5s

  [3379/13157] intraday_12160.csv.gz  in=227,847,719 out=46,732,870 elapsed=237.5s

  [3380/13157] intraday_12163.csv.gz  in=228,099,372 out=46,912,203 elapsed=237.7s

  [3381/13157] intraday_12165.csv.gz  in=228,405,142 out=47,135,307 elapsed=239.0s

  [3382/13157] intraday_12164.csv.gz  in=228,626,606 out=47,292,389 elapsed=239.0s

  [3383/13157] intraday_12166.csv.gz  in=228,930,578 out=47,511,947 elapsed=239.2s

  [3384/13157] intraday_12167.csv.gz  in=229,203,065 out=47,706,340 elapsed=239.2s

  [3385/13157] intraday_1217.csv.gz  in=229,217,505 out=47,706,340 elapsed=239.2s

  [3386/13157] intraday_12169.csv.gz  in=229,482,264 out=47,895,459 elapsed=239.7s

  [3387/13157] intraday_12168.csv.gz  in=229,750,975 out=48,087,214 elapsed=239.8s

  [3388/13157] intraday_12170.csv.gz  in=229,956,041 out=48,236,388 elapsed=239.8s

  [3389/13157] intraday_12172.csv.gz  in=230,213,790 out=48,422,666 elapsed=240.9s

  [3390/13157] intraday_12171.csv.gz  in=230,486,328 out=48,618,641 elapsed=241.1s

  [3391/13157] intraday_12174.csv.gz  in=230,757,237 out=48,813,885 elapsed=241.1s

  [3392/13157] intraday_12173.csv.gz  in=231,031,301 out=49,012,722 elapsed=241.1s

  [3393/13157] intraday_12175.csv.gz  in=231,276,048 out=49,191,366 elapsed=242.4s

  [3394/13157] intraday_12178.csv.gz  in=231,546,355 out=49,382,360 elapsed=242.7s

  [3395/13157] intraday_12177.csv.gz  in=231,810,483 out=49,574,537 elapsed=242.7s

  [3396/13157] intraday_1218.csv.gz  in=231,832,765 out=49,574,537 elapsed=242.8s

  [3397/13157] intraday_12179.csv.gz  in=232,092,193 out=49,760,315 elapsed=242.9s

  [3398/13157] intraday_12176.csv.gz  in=232,341,082 out=49,939,031 elapsed=242.9s

  [3399/13157] intraday_12181.csv.gz  in=232,535,300 out=50,078,386 elapsed=243.3s

  [3400/13157] intraday_12180.csv.gz  in=232,807,775 out=50,277,824 elapsed=243.5s

  [3401/13157] intraday_12182.csv.gz  in=233,053,758 out=50,455,316 elapsed=243.5s

  [3402/13157] intraday_12183.csv.gz  in=233,325,233 out=50,651,015 elapsed=243.5s

  [3403/13157] intraday_12187.csv.gz  in=233,591,009 out=50,840,163 elapsed=244.6s

  [3404/13157] intraday_12186.csv.gz  in=233,879,537 out=51,053,685 elapsed=244.7s

  [3405/13157] intraday_12185.csv.gz  in=234,207,133 out=51,297,864 elapsed=244.9s

  [3406/13157] intraday_12184.csv.gz  in=234,582,935 out=51,567,464 elapsed=244.9s

  [3407/13157] intraday_1219.csv.gz  in=234,596,994 out=51,567,464 elapsed=244.9s

  [3408/13157] intraday_12188.csv.gz  in=234,867,329 out=51,761,207 elapsed=245.0s

  [3409/13157] intraday_12189.csv.gz  in=235,149,352 out=51,963,395 elapsed=245.9s

  [3410/13157] intraday_12192.csv.gz  in=235,404,902 out=52,149,290 elapsed=246.2s

  [3411/13157] intraday_12191.csv.gz  in=235,652,361 out=52,325,860 elapsed=246.3s

  [3412/13157] intraday_12190.csv.gz  in=236,002,200 out=52,579,578 elapsed=246.8s

  [3413/13157] intraday_12193.csv.gz  in=236,303,666 out=52,795,643 elapsed=246.9s

  [3414/13157] intraday_12194.csv.gz  in=236,603,410 out=53,008,937 elapsed=246.9s

  [3415/13157] intraday_12195.csv.gz  in=236,903,274 out=53,221,410 elapsed=246.9s

  [3416/13157] intraday_12197.csv.gz  in=237,166,314 out=53,413,294 elapsed=248.6s

  [3417/13157] intraday_12196.csv.gz  in=237,421,882 out=53,596,504 elapsed=248.6s

  [3418/13157] intraday_12199.csv.gz  in=237,664,182 out=53,766,293 elapsed=248.6s

  [3419/13157] intraday_12198.csv.gz  in=237,934,412 out=53,961,191 elapsed=248.7s

  [3420/13157] intraday_1220.csv.gz  in=237,955,374 out=53,961,191 elapsed=248.8s

  [3421/13157] intraday_12201.csv.gz  in=238,183,873 out=54,124,449 elapsed=249.9s

  [3422/13157] intraday_12202.csv.gz  in=238,471,108 out=54,329,878 elapsed=250.1s

  [3423/13157] intraday_12203.csv.gz  in=238,785,210 out=54,558,775 elapsed=250.1s

  [3424/13157] intraday_12200.csv.gz  in=239,120,049 out=54,798,388 elapsed=250.1s

  [3425/13157] intraday_12205.csv.gz  in=239,351,960 out=54,964,904 elapsed=251.2s

  [3426/13157] intraday_12206.csv.gz  in=239,625,461 out=55,160,645 elapsed=251.2s

  [3427/13157] intraday_12204.csv.gz  in=239,920,235 out=55,382,178 elapsed=251.3s

  [3428/13157] intraday_12207.csv.gz  in=240,253,326 out=55,628,493 elapsed=251.3s

  [3429/13157] intraday_1221.csv.gz  in=240,268,815 out=55,628,493 elapsed=251.3s

  [3430/13157] intraday_12209.csv.gz  in=240,521,291 out=55,812,004 elapsed=251.8s

  [3431/13157] intraday_12208.csv.gz  in=240,788,048 out=55,998,560 elapsed=251.9s

  [3432/13157] intraday_12210.csv.gz  in=241,121,091 out=56,239,941 elapsed=252.1s

  [3433/13157] intraday_12211.csv.gz  in=241,439,349 out=56,471,766 elapsed=252.1s

  [3434/13157] intraday_12212.csv.gz  in=241,706,007 out=56,659,118 elapsed=253.8s

  [3435/13157] intraday_12213.csv.gz  in=241,982,222 out=56,855,814 elapsed=253.9s

  [3436/13157] intraday_12215.csv.gz  in=242,222,900 out=57,025,143 elapsed=253.9s

  [3437/13157] intraday_12214.csv.gz  in=242,491,876 out=57,219,177 elapsed=253.9s

  [3438/13157] intraday_12216.csv.gz  in=242,821,382 out=57,450,286 elapsed=255.7s

  [3439/13157] intraday_12218.csv.gz  in=243,115,290 out=57,663,596 elapsed=255.8s

  [3440/13157] intraday_12219.csv.gz  in=243,412,976 out=57,877,542 elapsed=255.8s

  [3441/13157] intraday_1222.csv.gz  in=243,425,104 out=57,877,542 elapsed=255.8s

  [3442/13157] intraday_12217.csv.gz  in=243,765,136 out=58,120,309 elapsed=255.8s

  [3443/13157] intraday_12223.csv.gz  in=243,995,832 out=58,287,767 elapsed=257.7s

  [3444/13157] intraday_12221.csv.gz  in=244,226,190 out=58,454,443 elapsed=257.9s

  [3445/13157] intraday_12222.csv.gz  in=244,493,374 out=58,645,613 elapsed=257.9s

  [3446/13157] intraday_12220.csv.gz  in=244,833,073 out=58,887,051 elapsed=258.3s

  [3447/13157] intraday_12224.csv.gz  in=245,139,181 out=59,108,909 elapsed=259.7s

  [3448/13157] intraday_12225.csv.gz  in=245,373,590 out=59,279,311 elapsed=260.4s

  [3449/13157] intraday_12226.csv.gz  in=245,683,492 out=59,502,780 elapsed=261.7s

  [3450/13157] intraday_1223.csv.gz  in=245,696,953 out=59,502,780 elapsed=261.8s

  [3451/13157] intraday_12229.csv.gz  in=245,952,641 out=59,684,968 elapsed=261.8s

  [3452/13157] intraday_12227.csv.gz  in=246,230,009 out=59,882,512 elapsed=261.9s

  [3453/13157] intraday_12230.csv.gz  in=246,492,461 out=60,066,335 elapsed=262.6s

  [3454/13157] intraday_12231.csv.gz  in=246,754,712 out=60,253,904 elapsed=262.7s

  [3455/13157] intraday_12232.csv.gz  in=247,073,985 out=60,479,758 elapsed=262.7s

  [3456/13157] intraday_12233.csv.gz  in=247,309,838 out=60,649,792 elapsed=263.2s

  [3457/13157] intraday_12228.csv.gz  in=247,648,535 out=60,894,162 elapsed=263.3s

  [3458/13157] intraday_12234.csv.gz  in=247,921,041 out=61,089,290 elapsed=263.3s

  [3459/13157] intraday_12235.csv.gz  in=248,242,467 out=61,322,817 elapsed=263.4s

  [3460/13157] intraday_12236.csv.gz  in=248,535,824 out=61,534,093 elapsed=264.5s

  [3461/13157] intraday_12238.csv.gz  in=248,791,316 out=61,715,825 elapsed=264.5s

  [3462/13157] intraday_1224.csv.gz  in=248,803,244 out=61,715,825 elapsed=264.5s

  [3463/13157] intraday_12239.csv.gz  in=249,052,004 out=61,894,233 elapsed=264.6s

  [3464/13157] intraday_12237.csv.gz  in=249,374,765 out=62,128,434 elapsed=264.7s

  [3465/13157] intraday_12241.csv.gz  in=249,625,485 out=62,307,304 elapsed=265.5s

  [3466/13157] intraday_12244.csv.gz  in=249,821,552 out=62,450,971 elapsed=265.9s

  [3467/13157] intraday_12243.csv.gz  in=250,029,645 out=62,594,178 elapsed=265.9s

  [3468/13157] intraday_12240.csv.gz  in=250,307,245 out=62,800,182 elapsed=266.0s

  [3469/13157] intraday_12242.csv.gz  in=250,602,516 out=63,011,455 elapsed=266.0s

  [3470/13157] intraday_12246.csv.gz  in=250,606,302 out=63,014,140 elapsed=266.0s

  [3471/13157] intraday_12247.csv.gz  in=250,608,717 out=63,016,181 elapsed=266.0s

  [3472/13157] intraday_12248.csv.gz  in=250,609,952 out=63,017,133 elapsed=266.0s

  [3473/13157] intraday_1225.csv.gz  in=250,622,793 out=63,017,133 elapsed=266.1s

  [3474/13157] intraday_12250.csv.gz  in=250,630,884 out=63,024,540 elapsed=266.1s

  [3475/13157] intraday_12249.csv.gz  in=250,635,593 out=63,028,189 elapsed=266.1s

  [3476/13157] intraday_12252.csv.gz  in=250,636,588 out=63,029,163 elapsed=266.4s

  [3477/13157] intraday_12251.csv.gz  in=250,637,107 out=63,029,572 elapsed=266.4s

  [3478/13157] intraday_12255.csv.gz  in=250,637,324 out=63,029,744 elapsed=266.4s

  [3479/13157] intraday_12254.csv.gz  in=250,640,384 out=63,032,326 elapsed=266.5s

  [3480/13157] intraday_12257.csv.gz  in=250,641,274 out=63,033,007 elapsed=266.5s

  [3481/13157] intraday_12256.csv.gz  in=250,642,924 out=63,034,320 elapsed=266.5s

  [3482/13157] intraday_12253.csv.gz  in=250,655,726 out=63,045,474 elapsed=266.5s

  [3483/13157] intraday_12259.csv.gz  in=250,655,841 out=63,045,549 elapsed=266.7s

  [3484/13157] intraday_1226.csv.gz  in=250,666,469 out=63,045,549 elapsed=266.7s

  [3485/13157] intraday_12258.csv.gz  in=250,668,891 out=63,047,341 elapsed=266.7s

  [3486/13157] intraday_12245.csv.gz  in=250,943,002 out=63,247,769 elapsed=266.7s

  [3487/13157] intraday_12260.csv.gz  in=250,943,267 out=63,248,014 elapsed=266.8s

  [3488/13157] intraday_12261.csv.gz  in=250,944,107 out=63,248,581 elapsed=266.8s

  [3489/13157] intraday_12264.csv.gz  in=250,944,197 out=63,248,644 elapsed=266.8s

  [3490/13157] intraday_12262.csv.gz  in=250,945,415 out=63,249,679 elapsed=266.9s

  [3491/13157] intraday_12263.csv.gz  in=250,951,802 out=63,255,100 elapsed=266.9s

  [3492/13157] intraday_12265.csv.gz  in=250,953,650 out=63,256,820 elapsed=266.9s

  [3493/13157] intraday_12266.csv.gz  in=250,956,829 out=63,259,108 elapsed=266.9s

  [3494/13157] intraday_12267.csv.gz  in=250,957,297 out=63,259,108 elapsed=266.9s

  [3495/13157] intraday_12268.csv.gz  in=250,960,177 out=63,261,259 elapsed=266.9s

  [3496/13157] intraday_12269.csv.gz  in=250,963,823 out=63,264,280 elapsed=266.9s

  [3497/13157] intraday_12270.csv.gz  in=250,965,549 out=63,265,639 elapsed=267.0s

  [3498/13157] intraday_12272.csv.gz  in=250,967,778 out=63,267,485 elapsed=267.1s

  [3499/13157] intraday_12271.csv.gz  in=250,974,609 out=63,273,945 elapsed=267.1s

  [3500/13157] intraday_1227.csv.gz  in=250,988,840 out=63,273,945 elapsed=267.1s

  [3501/13157] intraday_12274.csv.gz  in=250,989,399 out=63,274,382 elapsed=267.1s

  [3502/13157] intraday_12273.csv.gz  in=250,994,258 out=63,277,807 elapsed=267.1s

  [3503/13157] intraday_12275.csv.gz  in=250,994,745 out=63,278,147 elapsed=267.1s

  [3504/13157] intraday_12278.csv.gz  in=251,007,157 out=63,290,559 elapsed=267.2s

  [3505/13157] intraday_12279.csv.gz  in=251,017,509 out=63,300,911 elapsed=267.2s

  [3506/13157] intraday_12277.csv.gz  in=251,030,649 out=63,314,051 elapsed=267.2s

  [3507/13157] intraday_12276.csv.gz  in=251,047,083 out=63,330,485 elapsed=267.2s

  [3508/13157] intraday_1228.csv.gz  in=251,055,347 out=63,330,485 elapsed=267.3s

  [3509/13157] intraday_12280.csv.gz  in=251,067,663 out=63,342,801 elapsed=267.3s

  [3510/13157] intraday_12281.csv.gz  in=251,082,854 out=63,357,992 elapsed=267.3s

  [3511/13157] intraday_12282.csv.gz  in=251,097,079 out=63,372,217 elapsed=267.3s

  [3512/13157] intraday_12284.csv.gz  in=251,110,118 out=63,385,256 elapsed=267.4s

  [3513/13157] intraday_12283.csv.gz  in=251,122,989 out=63,398,127 elapsed=267.4s

  [3514/13157] intraday_12286.csv.gz  in=251,135,249 out=63,410,387 elapsed=267.4s

  [3515/13157] intraday_12285.csv.gz  in=251,148,219 out=63,423,357 elapsed=267.4s

  [3516/13157] intraday_1229.csv.gz  in=251,158,916 out=63,423,357 elapsed=267.4s

  [3517/13157] intraday_12287.csv.gz  in=251,170,753 out=63,435,194 elapsed=267.5s

  [3518/13157] intraday_12289.csv.gz  in=251,184,830 out=63,449,271 elapsed=267.5s

  [3519/13157] intraday_12288.csv.gz  in=251,199,030 out=63,463,471 elapsed=267.5s

  [3520/13157] intraday_12290.csv.gz  in=251,209,547 out=63,473,988 elapsed=267.5s

  [3521/13157] intraday_12291.csv.gz  in=251,219,712 out=63,484,153 elapsed=267.6s

  [3522/13157] intraday_12292.csv.gz  in=251,234,045 out=63,498,486 elapsed=267.6s

  [3523/13157] intraday_12293.csv.gz  in=251,246,628 out=63,511,069 elapsed=267.6s

  [3524/13157] intraday_12294.csv.gz  in=251,258,187 out=63,522,628 elapsed=267.6s

  [3525/13157] intraday_12295.csv.gz  in=251,269,475 out=63,533,916 elapsed=267.8s

  [3526/13157] intraday_12297.csv.gz  in=251,282,097 out=63,546,538 elapsed=267.8s

  [3527/13157] intraday_12296.csv.gz  in=251,292,955 out=63,557,396 elapsed=267.8s

  [3528/13157] intraday_12298.csv.gz  in=251,306,372 out=63,570,813 elapsed=267.8s

  [3529/13157] intraday_12299.csv.gz  in=251,317,441 out=63,581,882 elapsed=267.9s

  [3530/13157] intraday_1230.csv.gz  in=251,329,037 out=63,581,882 elapsed=267.9s

  [3531/13157] intraday_12301.csv.gz  in=251,340,444 out=63,593,289 elapsed=267.9s

  [3532/13157] intraday_12300.csv.gz  in=251,352,971 out=63,605,816 elapsed=267.9s

  [3533/13157] intraday_12304.csv.gz  in=251,364,740 out=63,617,585 elapsed=268.0s

  [3534/13157] intraday_12303.csv.gz  in=251,376,369 out=63,629,214 elapsed=268.0s

  [3535/13157] intraday_12302.csv.gz  in=251,389,006 out=63,641,851 elapsed=268.0s

  [3536/13157] intraday_12305.csv.gz  in=251,402,168 out=63,655,013 elapsed=268.0s

  [3537/13157] intraday_12308.csv.gz  in=251,412,384 out=63,665,229 elapsed=268.1s

  [3538/13157] intraday_12309.csv.gz  in=251,426,509 out=63,679,354 elapsed=268.1s

  [3539/13157] intraday_12306.csv.gz  in=251,441,515 out=63,694,360 elapsed=268.1s

  [3540/13157] intraday_12307.csv.gz  in=251,454,947 out=63,707,792 elapsed=268.1s

  [3541/13157] intraday_12311.csv.gz  in=251,468,539 out=63,721,384 elapsed=268.2s

  [3542/13157] intraday_1231.csv.gz  in=251,483,818 out=63,721,384 elapsed=268.2s

  [3543/13157] intraday_12312.csv.gz  in=251,496,226 out=63,733,792 elapsed=268.2s

  [3544/13157] intraday_12310.csv.gz  in=251,509,522 out=63,747,088 elapsed=268.2s

  [3545/13157] intraday_12315.csv.gz  in=251,519,070 out=63,756,636 elapsed=268.4s

  [3546/13157] intraday_12314.csv.gz  in=251,531,623 out=63,769,189 elapsed=268.4s

  [3547/13157] intraday_12316.csv.gz  in=251,542,179 out=63,779,745 elapsed=268.4s

  [3548/13157] intraday_12313.csv.gz  in=251,552,215 out=63,789,781 elapsed=268.4s

  [3549/13157] intraday_12317.csv.gz  in=251,565,546 out=63,803,112 elapsed=268.5s

  [3550/13157] intraday_12319.csv.gz  in=251,577,529 out=63,815,095 elapsed=268.5s

  [3551/13157] intraday_12318.csv.gz  in=251,589,826 out=63,827,392 elapsed=268.5s

  [3552/13157] intraday_1232.csv.gz  in=251,604,339 out=63,827,392 elapsed=268.5s

  [3553/13157] intraday_12320.csv.gz  in=251,617,915 out=63,840,968 elapsed=268.5s

  [3554/13157] intraday_12321.csv.gz  in=251,630,692 out=63,853,745 elapsed=268.5s

  [3555/13157] intraday_12323.csv.gz  in=251,643,079 out=63,866,132 elapsed=268.7s

  [3556/13157] intraday_12322.csv.gz  in=251,655,392 out=63,878,445 elapsed=268.7s

  [3557/13157] intraday_12324.csv.gz  in=251,670,015 out=63,893,068 elapsed=268.7s

  [3558/13157] intraday_12325.csv.gz  in=251,680,153 out=63,903,206 elapsed=268.7s

  [3559/13157] intraday_12326.csv.gz  in=251,692,034 out=63,915,087 elapsed=268.7s

  [3560/13157] intraday_12327.csv.gz  in=251,701,098 out=63,924,151 elapsed=268.9s

  [3561/13157] intraday_1233.csv.gz  in=251,712,299 out=63,924,151 elapsed=268.9s

  [3562/13157] intraday_12329.csv.gz  in=251,722,654 out=63,934,506 elapsed=269.0s

  [3563/13157] intraday_12328.csv.gz  in=251,736,412 out=63,948,264 elapsed=269.0s

  [3564/13157] intraday_12330.csv.gz  in=251,749,008 out=63,960,860 elapsed=269.6s

  [3565/13157] intraday_12332.csv.gz  in=251,761,274 out=63,973,126 elapsed=269.7s

  [3566/13157] intraday_12331.csv.gz  in=251,775,622 out=63,987,474 elapsed=269.7s

  [3567/13157] intraday_12333.csv.gz  in=251,786,940 out=63,998,792 elapsed=269.7s

  [3568/13157] intraday_12334.csv.gz  in=251,797,691 out=64,009,543 elapsed=270.2s

  [3569/13157] intraday_12335.csv.gz  in=251,809,789 out=64,021,641 elapsed=270.2s

  [3570/13157] intraday_12336.csv.gz  in=251,821,673 out=64,033,525 elapsed=270.2s

  [3571/13157] intraday_12337.csv.gz  in=251,834,168 out=64,046,020 elapsed=270.2s

  [3572/13157] intraday_1234.csv.gz  in=251,845,466 out=64,046,020 elapsed=270.3s

  [3573/13157] intraday_12338.csv.gz  in=251,856,683 out=64,057,237 elapsed=270.3s

  [3574/13157] intraday_12339.csv.gz  in=251,869,147 out=64,069,701 elapsed=270.4s

  [3575/13157] intraday_12340.csv.gz  in=251,878,482 out=64,079,036 elapsed=270.4s

  [3576/13157] intraday_12341.csv.gz  in=251,893,228 out=64,093,782 elapsed=270.6s

  [3577/13157] intraday_12342.csv.gz  in=251,908,653 out=64,109,207 elapsed=270.6s

  [3578/13157] intraday_12344.csv.gz  in=251,922,466 out=64,123,020 elapsed=270.6s

  [3579/13157] intraday_12343.csv.gz  in=251,934,528 out=64,135,082 elapsed=270.7s

  [3580/13157] intraday_12348.csv.gz  in=251,947,437 out=64,147,991 elapsed=270.8s

  [3581/13157] intraday_12346.csv.gz  in=251,957,553 out=64,158,107 elapsed=270.8s

  [3582/13157] intraday_12347.csv.gz  in=251,971,005 out=64,171,559 elapsed=270.8s

  [3583/13157] intraday_12345.csv.gz  in=251,983,478 out=64,184,032 elapsed=270.8s

  [3584/13157] intraday_12349.csv.gz  in=251,996,245 out=64,196,799 elapsed=270.9s

  [3585/13157] intraday_1235.csv.gz  in=252,010,748 out=64,196,799 elapsed=270.9s

  [3586/13157] intraday_12351.csv.gz  in=252,022,612 out=64,208,663 elapsed=270.9s

  [3587/13157] intraday_12350.csv.gz  in=252,036,277 out=64,222,328 elapsed=270.9s

  [3588/13157] intraday_12352.csv.gz  in=252,047,502 out=64,233,553 elapsed=270.9s

  [3589/13157] intraday_12353.csv.gz  in=252,058,814 out=64,244,865 elapsed=270.9s

  [3590/13157] intraday_12355.csv.gz  in=252,071,029 out=64,257,080 elapsed=271.0s

  [3591/13157] intraday_12354.csv.gz  in=252,084,647 out=64,270,698 elapsed=271.0s

  [3592/13157] intraday_12358.csv.gz  in=252,095,914 out=64,281,965 elapsed=271.0s

  [3593/13157] intraday_12359.csv.gz  in=252,108,148 out=64,294,199 elapsed=271.0s

  [3594/13157] intraday_12356.csv.gz  in=252,119,894 out=64,305,945 elapsed=271.0s

  [3595/13157] intraday_12357.csv.gz  in=252,131,448 out=64,317,499 elapsed=271.0s

  [3596/13157] intraday_1236.csv.gz  in=252,145,501 out=64,317,499 elapsed=271.1s

  [3597/13157] intraday_12362.csv.gz  in=252,158,812 out=64,330,810 elapsed=271.1s

  [3598/13157] intraday_12363.csv.gz  in=252,170,747 out=64,342,745 elapsed=271.1s

  [3599/13157] intraday_12360.csv.gz  in=252,186,496 out=64,358,494 elapsed=271.1s

  [3600/13157] intraday_12361.csv.gz  in=252,203,885 out=64,375,883 elapsed=271.1s

  [3601/13157] intraday_12364.csv.gz  in=252,215,396 out=64,387,394 elapsed=271.1s

  [3602/13157] intraday_12365.csv.gz  in=252,227,796 out=64,399,794 elapsed=271.2s

  [3603/13157] intraday_12366.csv.gz  in=252,242,564 out=64,414,562 elapsed=271.2s

  [3604/13157] intraday_12367.csv.gz  in=252,253,320 out=64,425,318 elapsed=271.2s

  [3605/13157] intraday_1237.csv.gz  in=252,265,635 out=64,425,318 elapsed=271.2s

  [3606/13157] intraday_12369.csv.gz  in=252,281,124 out=64,440,807 elapsed=271.2s

  [3607/13157] intraday_12370.csv.gz  in=252,293,557 out=64,453,240 elapsed=271.2s

  [3608/13157] intraday_12368.csv.gz  in=252,304,549 out=64,464,232 elapsed=271.2s

  [3609/13157] intraday_12372.csv.gz  in=252,317,448 out=64,477,131 elapsed=271.3s

  [3610/13157] intraday_12371.csv.gz  in=252,329,964 out=64,489,647 elapsed=271.3s

  [3611/13157] intraday_12373.csv.gz  in=252,341,092 out=64,500,775 elapsed=271.3s

  [3612/13157] intraday_12374.csv.gz  in=252,353,981 out=64,513,664 elapsed=271.3s

  [3613/13157] intraday_12376.csv.gz  in=252,365,636 out=64,525,319 elapsed=271.4s

  [3614/13157] intraday_12375.csv.gz  in=252,379,102 out=64,538,785 elapsed=271.4s

  [3615/13157] intraday_12377.csv.gz  in=252,390,012 out=64,549,695 elapsed=271.4s

  [3616/13157] intraday_12378.csv.gz  in=252,403,584 out=64,563,267 elapsed=271.4s

  [3617/13157] intraday_12379.csv.gz  in=252,417,348 out=64,577,031 elapsed=271.4s

  [3618/13157] intraday_12381.csv.gz  in=252,430,027 out=64,589,710 elapsed=271.5s

  [3619/13157] intraday_1238.csv.gz  in=252,442,127 out=64,589,710 elapsed=271.5s

  [3620/13157] intraday_12380.csv.gz  in=252,456,847 out=64,604,229 elapsed=271.5s

  [3621/13157] intraday_12384.csv.gz  in=252,467,866 out=64,615,248 elapsed=271.5s

  [3622/13157] intraday_12382.csv.gz  in=252,480,884 out=64,628,266 elapsed=271.5s

  [3623/13157] intraday_12383.csv.gz  in=252,496,233 out=64,643,615 elapsed=271.5s

  [3624/13157] intraday_12385.csv.gz  in=252,508,683 out=64,656,065 elapsed=271.5s

  [3625/13157] intraday_12386.csv.gz  in=252,522,842 out=64,670,224 elapsed=271.5s

  [3626/13157] intraday_12387.csv.gz  in=252,537,933 out=64,685,315 elapsed=271.6s

  [3627/13157] intraday_12388.csv.gz  in=252,549,718 out=64,697,100 elapsed=271.6s

  [3628/13157] intraday_1239.csv.gz  in=252,564,426 out=64,697,100 elapsed=271.6s

  [3629/13157] intraday_12389.csv.gz  in=252,577,723 out=64,710,397 elapsed=271.6s

  [3630/13157] intraday_12392.csv.gz  in=252,591,731 out=64,724,405 elapsed=271.6s

  [3631/13157] intraday_12391.csv.gz  in=252,604,962 out=64,737,636 elapsed=271.7s

  [3632/13157] intraday_12390.csv.gz  in=252,620,401 out=64,753,075 elapsed=271.7s

  [3633/13157] intraday_12395.csv.gz  in=252,633,985 out=64,766,659 elapsed=271.9s

  [3634/13157] intraday_12393.csv.gz  in=252,650,315 out=64,782,989 elapsed=271.9s

  [3635/13157] intraday_12394.csv.gz  in=252,668,907 out=64,801,581 elapsed=271.9s

  [3636/13157] intraday_12396.csv.gz  in=252,685,433 out=64,818,107 elapsed=271.9s

  [3637/13157] intraday_1240.csv.gz  in=252,699,491 out=64,818,107 elapsed=272.0s

  [3638/13157] intraday_12398.csv.gz  in=252,711,811 out=64,830,427 elapsed=272.0s

  [3639/13157] intraday_12399.csv.gz  in=252,724,403 out=64,843,019 elapsed=272.0s

  [3640/13157] intraday_12400.csv.gz  in=252,736,835 out=64,855,451 elapsed=272.1s

  [3641/13157] intraday_12401.csv.gz  in=252,747,713 out=64,866,329 elapsed=272.1s

  [3642/13157] intraday_12397.csv.gz  in=252,782,233 out=64,899,134 elapsed=272.1s

  [3643/13157] intraday_12402.csv.gz  in=252,795,345 out=64,912,246 elapsed=272.3s

  [3644/13157] intraday_12403.csv.gz  in=252,807,016 out=64,923,917 elapsed=272.3s

  [3645/13157] intraday_12404.csv.gz  in=252,822,870 out=64,939,771 elapsed=272.3s

  [3646/13157] intraday_12408.csv.gz  in=252,837,186 out=64,954,087 elapsed=272.3s

  [3647/13157] intraday_12406.csv.gz  in=252,848,447 out=64,965,348 elapsed=272.4s

  [3648/13157] intraday_12407.csv.gz  in=252,860,150 out=64,977,051 elapsed=272.4s

  [3649/13157] intraday_12405.csv.gz  in=252,870,711 out=64,987,612 elapsed=272.4s

  [3650/13157] intraday_12409.csv.gz  in=252,881,309 out=64,998,210 elapsed=272.4s

  [3651/13157] intraday_1241.csv.gz  in=252,891,080 out=64,998,210 elapsed=272.4s

  [3652/13157] intraday_12411.csv.gz  in=252,905,715 out=65,012,845 elapsed=272.4s

  [3653/13157] intraday_12410.csv.gz  in=252,919,435 out=65,026,565 elapsed=272.4s

  [3654/13157] intraday_12412.csv.gz  in=252,933,737 out=65,040,867 elapsed=272.4s

  [3655/13157] intraday_12414.csv.gz  in=252,947,982 out=65,055,112 elapsed=272.5s

  [3656/13157] intraday_12415.csv.gz  in=252,959,698 out=65,066,828 elapsed=272.5s

  [3657/13157] intraday_12413.csv.gz  in=252,973,648 out=65,080,778 elapsed=272.5s

  [3658/13157] intraday_12416.csv.gz  in=252,986,268 out=65,093,398 elapsed=272.5s

  [3659/13157] intraday_12419.csv.gz  in=252,994,303 out=65,101,433 elapsed=272.5s

  [3660/13157] intraday_12418.csv.gz  in=253,007,399 out=65,114,529 elapsed=272.5s

  [3661/13157] intraday_12417.csv.gz  in=253,017,733 out=65,124,863 elapsed=272.5s

  [3662/13157] intraday_12420.csv.gz  in=253,025,345 out=65,132,475 elapsed=272.6s

  [3663/13157] intraday_12422.csv.gz  in=253,028,958 out=65,136,088 elapsed=272.6s

  [3664/13157] intraday_1242.csv.gz  in=253,043,944 out=65,136,088 elapsed=272.6s

  [3665/13157] intraday_12421.csv.gz  in=253,057,505 out=65,149,649 elapsed=272.6s

  [3666/13157] intraday_12424.csv.gz  in=253,070,389 out=65,162,533 elapsed=272.6s

  [3667/13157] intraday_12426.csv.gz  in=253,082,631 out=65,174,548 elapsed=272.7s

  [3668/13157] intraday_12425.csv.gz  in=253,097,024 out=65,188,941 elapsed=272.7s

  [3669/13157] intraday_12423.csv.gz  in=253,115,109 out=65,207,026 elapsed=272.7s

  [3670/13157] intraday_12427.csv.gz  in=253,127,389 out=65,219,306 elapsed=272.9s

  [3671/13157] intraday_1243.csv.gz  in=253,142,659 out=65,219,306 elapsed=272.9s

  [3672/13157] intraday_12429.csv.gz  in=253,161,827 out=65,238,474 elapsed=272.9s

  [3673/13157] intraday_12428.csv.gz  in=253,176,682 out=65,253,329 elapsed=272.9s

  [3674/13157] intraday_12430.csv.gz  in=253,188,243 out=65,264,890 elapsed=272.9s

  [3675/13157] intraday_12433.csv.gz  in=253,201,632 out=65,278,279 elapsed=272.9s

  [3676/13157] intraday_12431.csv.gz  in=253,215,573 out=65,292,220 elapsed=272.9s

  [3677/13157] intraday_12432.csv.gz  in=253,229,838 out=65,306,485 elapsed=273.0s

  [3678/13157] intraday_12434.csv.gz  in=253,242,928 out=65,319,575 elapsed=273.0s

  [3679/13157] intraday_12435.csv.gz  in=253,257,019 out=65,333,666 elapsed=273.0s

  [3680/13157] intraday_12436.csv.gz  in=253,271,194 out=65,347,841 elapsed=273.0s

  [3681/13157] intraday_1244.csv.gz  in=253,282,251 out=65,347,841 elapsed=273.1s

  [3682/13157] intraday_12438.csv.gz  in=253,295,126 out=65,360,473 elapsed=273.1s

  [3683/13157] intraday_12437.csv.gz  in=253,317,398 out=65,381,758 elapsed=273.2s

  [3684/13157] intraday_12439.csv.gz  in=253,332,154 out=65,396,458 elapsed=273.2s

  [3685/13157] intraday_12442.csv.gz  in=253,342,794 out=65,407,098 elapsed=273.2s

  [3686/13157] intraday_12440.csv.gz  in=253,356,390 out=65,420,694 elapsed=273.3s

  [3687/13157] intraday_12441.csv.gz  in=253,367,214 out=65,431,518 elapsed=273.3s

  [3688/13157] intraday_12443.csv.gz  in=253,378,660 out=65,442,964 elapsed=273.3s

  [3689/13157] intraday_12446.csv.gz  in=253,390,983 out=65,455,287 elapsed=273.3s

  [3690/13157] intraday_12447.csv.gz  in=253,403,821 out=65,468,125 elapsed=273.3s

  [3691/13157] intraday_12444.csv.gz  in=253,416,625 out=65,480,929 elapsed=273.3s

  [3692/13157] intraday_12445.csv.gz  in=253,429,188 out=65,493,492 elapsed=273.3s

  [3693/13157] intraday_12450.csv.gz  in=253,441,183 out=65,505,487 elapsed=273.4s

  [3694/13157] intraday_1245.csv.gz  in=253,451,864 out=65,505,487 elapsed=273.4s

  [3695/13157] intraday_12449.csv.gz  in=253,465,379 out=65,519,002 elapsed=273.4s

  [3696/13157] intraday_12448.csv.gz  in=253,477,210 out=65,530,833 elapsed=273.5s

  [3697/13157] intraday_12453.csv.gz  in=253,493,328 out=65,546,951 elapsed=273.5s

  [3698/13157] intraday_12451.csv.gz  in=253,505,239 out=65,558,862 elapsed=273.5s

  [3699/13157] intraday_12452.csv.gz  in=253,518,670 out=65,572,293 elapsed=273.5s

  [3700/13157] intraday_12454.csv.gz  in=253,532,816 out=65,586,439 elapsed=273.6s

  [3701/13157] intraday_12455.csv.gz  in=253,543,320 out=65,596,943 elapsed=273.6s

  [3702/13157] intraday_12456.csv.gz  in=253,558,192 out=65,611,815 elapsed=273.6s

  [3703/13157] intraday_12457.csv.gz  in=253,574,238 out=65,627,769 elapsed=273.6s

  [3704/13157] intraday_1246.csv.gz  in=253,585,769 out=65,627,769 elapsed=273.6s

  [3705/13157] intraday_12458.csv.gz  in=253,600,056 out=65,642,056 elapsed=273.7s

  [3706/13157] intraday_12459.csv.gz  in=253,611,996 out=65,653,996 elapsed=273.7s

  [3707/13157] intraday_12460.csv.gz  in=253,623,532 out=65,665,532 elapsed=273.7s

  [3708/13157] intraday_12461.csv.gz  in=253,635,942 out=65,677,942 elapsed=273.7s

  [3709/13157] intraday_12463.csv.gz  in=253,647,324 out=65,689,324 elapsed=273.7s

  [3710/13157] intraday_12464.csv.gz  in=253,662,410 out=65,704,410 elapsed=273.7s

  [3711/13157] intraday_12462.csv.gz  in=253,673,500 out=65,715,500 elapsed=273.7s

  [3712/13157] intraday_12465.csv.gz  in=253,685,521 out=65,727,521 elapsed=273.9s

  [3713/13157] intraday_12466.csv.gz  in=253,698,613 out=65,740,613 elapsed=273.9s

  [3714/13157] intraday_12467.csv.gz  in=253,714,007 out=65,756,007 elapsed=273.9s

  [3715/13157] intraday_12468.csv.gz  in=253,726,174 out=65,768,174 elapsed=273.9s

  [3716/13157] intraday_12469.csv.gz  in=253,738,980 out=65,780,980 elapsed=274.0s

  [3717/13157] intraday_1247.csv.gz  in=253,751,964 out=65,780,980 elapsed=274.2s

  [3718/13157] intraday_12470.csv.gz  in=253,763,493 out=65,792,509 elapsed=274.2s

  [3719/13157] intraday_12471.csv.gz  in=253,777,145 out=65,806,161 elapsed=274.2s

  [3720/13157] intraday_12472.csv.gz  in=253,792,727 out=65,820,767 elapsed=274.2s

  [3721/13157] intraday_12473.csv.gz  in=253,805,477 out=65,833,517 elapsed=274.2s

  [3722/13157] intraday_12474.csv.gz  in=253,816,043 out=65,844,083 elapsed=274.2s

  [3723/13157] intraday_12475.csv.gz  in=253,828,892 out=65,856,932 elapsed=274.2s

  [3724/13157] intraday_12476.csv.gz  in=253,841,338 out=65,869,378 elapsed=274.2s

  [3725/13157] intraday_12479.csv.gz  in=253,851,923 out=65,879,963 elapsed=274.3s

  [3726/13157] intraday_1248.csv.gz  in=253,864,978 out=65,879,963 elapsed=274.3s

  [3727/13157] intraday_12478.csv.gz  in=253,879,739 out=65,894,724 elapsed=274.3s

  [3728/13157] intraday_12477.csv.gz  in=253,892,285 out=65,907,270 elapsed=274.3s

  [3729/13157] intraday_12480.csv.gz  in=253,903,872 out=65,918,857 elapsed=274.3s

  [3730/13157] intraday_12481.csv.gz  in=253,914,944 out=65,929,929 elapsed=274.3s

  [3731/13157] intraday_12482.csv.gz  in=253,927,871 out=65,942,856 elapsed=274.4s

  [3732/13157] intraday_12484.csv.gz  in=253,940,037 out=65,955,022 elapsed=274.4s

  [3733/13157] intraday_12483.csv.gz  in=253,952,252 out=65,967,237 elapsed=274.4s

  [3734/13157] intraday_12485.csv.gz  in=253,965,378 out=65,980,363 elapsed=274.4s

  [3735/13157] intraday_12487.csv.gz  in=253,975,991 out=65,990,976 elapsed=274.8s

  [3736/13157] intraday_12488.csv.gz  in=253,989,443 out=66,004,428 elapsed=274.8s

  [3737/13157] intraday_12486.csv.gz  in=254,001,546 out=66,016,531 elapsed=274.8s

  [3738/13157] intraday_12489.csv.gz  in=254,017,325 out=66,032,310 elapsed=274.8s

  [3739/13157] intraday_1249.csv.gz  in=254,028,934 out=66,032,310 elapsed=275.0s

  [3740/13157] intraday_12491.csv.gz  in=254,043,526 out=66,046,902 elapsed=275.1s

  [3741/13157] intraday_12490.csv.gz  in=254,057,384 out=66,060,760 elapsed=275.1s

  [3742/13157] intraday_12492.csv.gz  in=254,070,229 out=66,073,605 elapsed=275.1s

  [3743/13157] intraday_12493.csv.gz  in=254,081,653 out=66,085,029 elapsed=275.2s

  [3744/13157] intraday_12494.csv.gz  in=254,093,749 out=66,097,125 elapsed=275.2s

  [3745/13157] intraday_12496.csv.gz  in=254,106,682 out=66,110,058 elapsed=275.4s

  [3746/13157] intraday_12497.csv.gz  in=254,120,646 out=66,124,022 elapsed=275.4s

  [3747/13157] intraday_12498.csv.gz  in=254,132,280 out=66,135,656 elapsed=275.4s

  [3748/13157] intraday_12495.csv.gz  in=254,146,294 out=66,149,670 elapsed=275.4s

  [3749/13157] intraday_12500.csv.gz  in=254,157,813 out=66,161,189 elapsed=275.5s

  [3750/13157] intraday_1250.csv.gz  in=254,168,622 out=66,161,189 elapsed=275.5s

  [3751/13157] intraday_12501.csv.gz  in=254,183,334 out=66,175,901 elapsed=275.6s

  [3752/13157] intraday_12499.csv.gz  in=254,196,348 out=66,188,915 elapsed=275.6s

  [3753/13157] intraday_12502.csv.gz  in=254,208,103 out=66,200,670 elapsed=275.6s

  [3754/13157] intraday_12504.csv.gz  in=254,219,603 out=66,212,170 elapsed=275.7s

  [3755/13157] intraday_12505.csv.gz  in=254,230,578 out=66,223,145 elapsed=275.7s

  [3756/13157] intraday_12503.csv.gz  in=254,243,288 out=66,235,855 elapsed=275.7s

  [3757/13157] intraday_12506.csv.gz  in=254,256,149 out=66,248,716 elapsed=275.7s

  [3758/13157] intraday_1251.csv.gz  in=254,268,983 out=66,248,716 elapsed=275.7s

  [3759/13157] intraday_12507.csv.gz  in=254,284,054 out=66,263,787 elapsed=275.7s

  [3760/13157] intraday_12509.csv.gz  in=254,298,295 out=66,278,028 elapsed=275.8s

  [3761/13157] intraday_12510.csv.gz  in=254,309,375 out=66,289,108 elapsed=275.8s

  [3762/13157] intraday_12511.csv.gz  in=254,321,538 out=66,301,271 elapsed=275.8s

  [3763/13157] intraday_12513.csv.gz  in=254,333,533 out=66,313,266 elapsed=275.9s

  [3764/13157] intraday_12512.csv.gz  in=254,346,831 out=66,326,564 elapsed=275.9s

  [3765/13157] intraday_12514.csv.gz  in=254,362,107 out=66,341,840 elapsed=275.9s

  [3766/13157] intraday_12508.csv.gz  in=254,380,097 out=66,359,830 elapsed=275.9s

  [3767/13157] intraday_12515.csv.gz  in=254,391,670 out=66,371,403 elapsed=275.9s

  [3768/13157] intraday_12518.csv.gz  in=254,402,984 out=66,382,717 elapsed=276.0s

  [3769/13157] intraday_12519.csv.gz  in=254,416,303 out=66,396,036 elapsed=276.0s

  [3770/13157] intraday_12517.csv.gz  in=254,430,665 out=66,410,398 elapsed=276.0s

  [3771/13157] intraday_12516.csv.gz  in=254,446,421 out=66,426,154 elapsed=276.0s

  [3772/13157] intraday_1252.csv.gz  in=254,458,389 out=66,426,154 elapsed=276.0s

  [3773/13157] intraday_12520.csv.gz  in=254,469,947 out=66,437,712 elapsed=276.0s

  [3774/13157] intraday_12521.csv.gz  in=254,483,931 out=66,451,696 elapsed=276.2s

  [3775/13157] intraday_12524.csv.gz  in=254,496,120 out=66,463,885 elapsed=276.2s

  [3776/13157] intraday_12522.csv.gz  in=254,507,370 out=66,475,135 elapsed=276.2s

  [3777/13157] intraday_12523.csv.gz  in=254,522,162 out=66,489,927 elapsed=276.2s

  [3778/13157] intraday_12526.csv.gz  in=254,535,455 out=66,503,220 elapsed=276.3s

  [3779/13157] intraday_12525.csv.gz  in=254,548,212 out=66,515,977 elapsed=276.3s

  [3780/13157] intraday_12528.csv.gz  in=254,562,763 out=66,530,528 elapsed=276.3s

  [3781/13157] intraday_12527.csv.gz  in=254,577,617 out=66,545,382 elapsed=276.3s

  [3782/13157] intraday_12529.csv.gz  in=254,589,977 out=66,557,742 elapsed=276.4s

  [3783/13157] intraday_1253.csv.gz  in=254,602,758 out=66,557,742 elapsed=276.4s

  [3784/13157] intraday_12530.csv.gz  in=254,615,596 out=66,570,580 elapsed=276.4s

  [3785/13157] intraday_12531.csv.gz  in=254,630,224 out=66,585,208 elapsed=276.4s

  [3786/13157] intraday_12532.csv.gz  in=254,642,223 out=66,597,207 elapsed=276.4s

  [3787/13157] intraday_12533.csv.gz  in=254,656,539 out=66,611,523 elapsed=276.4s

  [3788/13157] intraday_12535.csv.gz  in=254,669,419 out=66,624,403 elapsed=276.5s

  [3789/13157] intraday_12534.csv.gz  in=254,684,241 out=66,639,225 elapsed=276.5s

  [3790/13157] intraday_12536.csv.gz  in=254,696,724 out=66,651,708 elapsed=276.5s

  [3791/13157] intraday_12539.csv.gz  in=254,709,606 out=66,664,590 elapsed=276.5s

  [3792/13157] intraday_12537.csv.gz  in=254,723,654 out=66,678,638 elapsed=276.5s

  [3793/13157] intraday_12538.csv.gz  in=254,740,585 out=66,695,569 elapsed=276.5s

  [3794/13157] intraday_1254.csv.gz  in=254,753,134 out=66,695,569 elapsed=276.6s

  [3795/13157] intraday_12540.csv.gz  in=254,769,143 out=66,711,578 elapsed=276.6s

  [3796/13157] intraday_12541.csv.gz  in=254,788,764 out=66,731,199 elapsed=276.6s

  [3797/13157] intraday_12544.csv.gz  in=254,801,796 out=66,744,231 elapsed=276.6s

  [3798/13157] intraday_12542.csv.gz  in=254,816,872 out=66,759,307 elapsed=276.6s

  [3799/13157] intraday_12543.csv.gz  in=254,834,600 out=66,777,035 elapsed=276.6s

  [3800/13157] intraday_12545.csv.gz  in=254,846,858 out=66,789,293 elapsed=276.6s

  [3801/13157] intraday_12546.csv.gz  in=254,859,642 out=66,802,077 elapsed=276.7s

  [3802/13157] intraday_12547.csv.gz  in=254,872,367 out=66,814,802 elapsed=276.7s

  [3803/13157] intraday_1255.csv.gz  in=254,884,860 out=66,814,802 elapsed=276.7s

  [3804/13157] intraday_12548.csv.gz  in=254,897,041 out=66,826,983 elapsed=276.7s

  [3805/13157] intraday_12549.csv.gz  in=254,908,885 out=66,838,827 elapsed=276.7s

  [3806/13157] intraday_12550.csv.gz  in=254,923,075 out=66,853,017 elapsed=276.9s

  [3807/13157] intraday_12552.csv.gz  in=254,936,680 out=66,866,622 elapsed=276.9s

  [3808/13157] intraday_12553.csv.gz  in=254,948,430 out=66,878,372 elapsed=276.9s

  [3809/13157] intraday_12551.csv.gz  in=254,963,285 out=66,893,227 elapsed=276.9s

  [3810/13157] intraday_12556.csv.gz  in=254,974,794 out=66,904,736 elapsed=277.0s

  [3811/13157] intraday_12555.csv.gz  in=254,989,423 out=66,919,365 elapsed=277.0s

  [3812/13157] intraday_12554.csv.gz  in=255,000,711 out=66,930,653 elapsed=277.1s

  [3813/13157] intraday_12558.csv.gz  in=255,015,631 out=66,945,573 elapsed=277.1s

  [3814/13157] intraday_12557.csv.gz  in=255,028,613 out=66,958,555 elapsed=277.1s

  [3815/13157] intraday_12559.csv.gz  in=255,044,108 out=66,974,050 elapsed=277.1s

  [3816/13157] intraday_12561.csv.gz  in=255,060,199 out=66,990,141 elapsed=277.2s

  [3817/13157] intraday_1256.csv.gz  in=255,079,763 out=66,990,141 elapsed=277.2s

  [3818/13157] intraday_12562.csv.gz  in=255,091,389 out=67,001,767 elapsed=277.2s

  [3819/13157] intraday_12560.csv.gz  in=255,105,323 out=67,015,701 elapsed=277.2s

  [3820/13157] intraday_12563.csv.gz  in=255,118,242 out=67,028,620 elapsed=277.3s

  [3821/13157] intraday_12564.csv.gz  in=255,130,226 out=67,040,604 elapsed=277.3s

  [3822/13157] intraday_12565.csv.gz  in=255,142,225 out=67,052,603 elapsed=277.3s

  [3823/13157] intraday_12566.csv.gz  in=255,152,359 out=67,062,737 elapsed=277.3s

  [3824/13157] intraday_12567.csv.gz  in=255,159,094 out=67,069,472 elapsed=277.3s

  [3825/13157] intraday_12569.csv.gz  in=255,165,232 out=67,075,610 elapsed=277.3s

  [3826/13157] intraday_1257.csv.gz  in=255,182,802 out=67,075,610 elapsed=277.3s

  [3827/13157] intraday_12568.csv.gz  in=255,196,915 out=67,089,723 elapsed=277.3s

  [3828/13157] intraday_12571.csv.gz  in=255,209,806 out=67,102,614 elapsed=277.4s

  [3829/13157] intraday_12573.csv.gz  in=255,220,942 out=67,113,750 elapsed=277.4s

  [3830/13157] intraday_12572.csv.gz  in=255,234,526 out=67,127,334 elapsed=277.4s

  [3831/13157] intraday_12570.csv.gz  in=255,251,980 out=67,144,788 elapsed=277.4s

  [3832/13157] intraday_12575.csv.gz  in=255,266,235 out=67,159,043 elapsed=277.5s

  [3833/13157] intraday_12577.csv.gz  in=255,279,083 out=67,171,891 elapsed=277.5s

  [3834/13157] intraday_12574.csv.gz  in=255,290,717 out=67,183,525 elapsed=277.5s

  [3835/13157] intraday_12576.csv.gz  in=255,307,762 out=67,200,570 elapsed=277.5s

  [3836/13157] intraday_12578.csv.gz  in=255,320,746 out=67,213,554 elapsed=277.5s

  [3837/13157] intraday_12581.csv.gz  in=255,332,412 out=67,225,220 elapsed=277.6s

  [3838/13157] intraday_1258.csv.gz  in=255,345,248 out=67,225,220 elapsed=277.6s

  [3839/13157] intraday_12579.csv.gz  in=255,359,057 out=67,239,029 elapsed=277.6s

  [3840/13157] intraday_12580.csv.gz  in=255,372,294 out=67,252,266 elapsed=277.6s

  [3841/13157] intraday_12582.csv.gz  in=255,387,063 out=67,267,035 elapsed=277.6s

  [3842/13157] intraday_12585.csv.gz  in=255,398,133 out=67,278,105 elapsed=277.6s

  [3843/13157] intraday_12584.csv.gz  in=255,407,913 out=67,287,885 elapsed=277.6s

  [3844/13157] intraday_12583.csv.gz  in=255,421,356 out=67,301,328 elapsed=277.6s

  [3845/13157] intraday_12589.csv.gz  in=255,431,921 out=67,311,893 elapsed=277.8s

  [3846/13157] intraday_12586.csv.gz  in=255,446,965 out=67,326,937 elapsed=277.8s

  [3847/13157] intraday_12587.csv.gz  in=255,460,199 out=67,340,171 elapsed=277.8s

  [3848/13157] intraday_12588.csv.gz  in=255,470,106 out=67,350,078 elapsed=277.8s

  [3849/13157] intraday_1259.csv.gz  in=255,483,550 out=67,350,078 elapsed=278.0s

  [3850/13157] intraday_12591.csv.gz  in=255,495,895 out=67,362,423 elapsed=278.0s

  [3851/13157] intraday_12590.csv.gz  in=255,506,950 out=67,373,478 elapsed=278.0s

  [3852/13157] intraday_12595.csv.gz  in=255,518,112 out=67,384,640 elapsed=278.1s

  [3853/13157] intraday_12592.csv.gz  in=255,530,099 out=67,396,627 elapsed=278.1s

  [3854/13157] intraday_12593.csv.gz  in=255,542,120 out=67,408,648 elapsed=278.1s

  [3855/13157] intraday_12594.csv.gz  in=255,556,185 out=67,422,713 elapsed=278.1s

  [3856/13157] intraday_12596.csv.gz  in=255,568,060 out=67,434,588 elapsed=278.2s

  [3857/13157] intraday_12598.csv.gz  in=255,579,892 out=67,446,420 elapsed=278.3s

  [3858/13157] intraday_12597.csv.gz  in=255,592,645 out=67,459,173 elapsed=278.3s

  [3859/13157] intraday_12599.csv.gz  in=255,605,875 out=67,472,403 elapsed=278.3s

  [3860/13157] intraday_12601.csv.gz  in=255,619,164 out=67,485,692 elapsed=278.3s

  [3861/13157] intraday_1260.csv.gz  in=255,634,361 out=67,485,692 elapsed=278.3s

  [3862/13157] intraday_12602.csv.gz  in=255,644,404 out=67,495,735 elapsed=278.3s

  [3863/13157] intraday_12600.csv.gz  in=255,660,431 out=67,511,762 elapsed=278.3s

  [3864/13157] intraday_12603.csv.gz  in=255,673,643 out=67,524,974 elapsed=278.4s

  [3865/13157] intraday_12605.csv.gz  in=255,687,056 out=67,538,387 elapsed=278.4s

  [3866/13157] intraday_12604.csv.gz  in=255,699,993 out=67,551,324 elapsed=278.4s

  [3867/13157] intraday_12606.csv.gz  in=255,712,617 out=67,563,948 elapsed=278.4s

  [3868/13157] intraday_12607.csv.gz  in=255,723,325 out=67,574,656 elapsed=278.6s

  [3869/13157] intraday_12609.csv.gz  in=255,733,848 out=67,585,111 elapsed=278.7s

  [3870/13157] intraday_12608.csv.gz  in=255,750,236 out=67,600,640 elapsed=278.7s

  [3871/13157] intraday_1261.csv.gz  in=255,763,546 out=67,600,640 elapsed=278.7s

  [3872/13157] intraday_12610.csv.gz  in=255,775,487 out=67,612,581 elapsed=278.7s

  [3873/13157] intraday_12611.csv.gz  in=255,789,638 out=67,626,732 elapsed=278.7s

  [3874/13157] intraday_12612.csv.gz  in=255,800,781 out=67,637,875 elapsed=278.7s

  [3875/13157] intraday_12613.csv.gz  in=255,822,549 out=67,659,099 elapsed=278.7s

  [3876/13157] intraday_12615.csv.gz  in=255,835,137 out=67,671,687 elapsed=278.8s

  [3877/13157] intraday_12614.csv.gz  in=255,849,330 out=67,685,880 elapsed=278.8s

  [3878/13157] intraday_12616.csv.gz  in=255,860,488 out=67,697,038 elapsed=278.8s

  [3879/13157] intraday_12617.csv.gz  in=255,872,070 out=67,708,620 elapsed=278.8s

  [3880/13157] intraday_12618.csv.gz  in=255,885,394 out=67,721,944 elapsed=278.8s

  [3881/13157] intraday_1262.csv.gz  in=255,897,470 out=67,721,944 elapsed=278.9s

  [3882/13157] intraday_12621.csv.gz  in=255,907,537 out=67,732,011 elapsed=278.9s

  [3883/13157] intraday_12619.csv.gz  in=255,918,143 out=67,742,617 elapsed=278.9s

  [3884/13157] intraday_12620.csv.gz  in=255,951,025 out=67,774,216 elapsed=278.9s

  [3885/13157] intraday_12622.csv.gz  in=255,965,767 out=67,788,958 elapsed=278.9s

  [3886/13157] intraday_12623.csv.gz  in=255,978,738 out=67,801,929 elapsed=279.0s

  [3887/13157] intraday_12624.csv.gz  in=255,991,024 out=67,814,215 elapsed=279.0s

  [3888/13157] intraday_12625.csv.gz  in=256,004,822 out=67,828,013 elapsed=279.0s

  [3889/13157] intraday_12626.csv.gz  in=256,016,120 out=67,839,311 elapsed=279.0s

  [3890/13157] intraday_12627.csv.gz  in=256,027,793 out=67,850,984 elapsed=279.0s

  [3891/13157] intraday_1263.csv.gz  in=256,041,090 out=67,850,984 elapsed=279.0s

  [3892/13157] intraday_12628.csv.gz  in=256,051,375 out=67,861,269 elapsed=279.1s

  [3893/13157] intraday_12629.csv.gz  in=256,065,592 out=67,875,267 elapsed=279.1s

  [3894/13157] intraday_12630.csv.gz  in=256,077,241 out=67,886,916 elapsed=279.1s

  [3895/13157] intraday_12631.csv.gz  in=256,090,591 out=67,900,201 elapsed=279.1s

  [3896/13157] intraday_12633.csv.gz  in=256,103,233 out=67,912,843 elapsed=279.1s

  [3897/13157] intraday_12632.csv.gz  in=256,125,364 out=67,934,392 elapsed=279.1s

  [3898/13157] intraday_12634.csv.gz  in=256,134,565 out=67,943,593 elapsed=279.1s

  [3899/13157] intraday_12635.csv.gz  in=256,148,863 out=67,957,891 elapsed=279.2s

  [3900/13157] intraday_12637.csv.gz  in=256,162,093 out=67,971,121 elapsed=279.2s

  [3901/13157] intraday_12638.csv.gz  in=256,175,642 out=67,984,670 elapsed=279.2s

  [3902/13157] intraday_12636.csv.gz  in=256,190,474 out=67,999,502 elapsed=279.2s

  [3903/13157] intraday_12639.csv.gz  in=256,204,606 out=68,013,634 elapsed=279.2s

  [3904/13157] intraday_1264.csv.gz  in=256,219,180 out=68,013,634 elapsed=279.3s

  [3905/13157] intraday_12641.csv.gz  in=256,231,399 out=68,025,827 elapsed=279.3s

  [3906/13157] intraday_12640.csv.gz  in=256,241,714 out=68,036,142 elapsed=279.3s

  [3907/13157] intraday_12642.csv.gz  in=256,255,362 out=68,049,790 elapsed=279.3s

  [3908/13157] intraday_12645.csv.gz  in=256,266,312 out=68,060,740 elapsed=279.3s

  [3909/13157] intraday_12644.csv.gz  in=256,279,966 out=68,074,092 elapsed=279.3s

  [3910/13157] intraday_12643.csv.gz  in=256,292,343 out=68,086,469 elapsed=279.4s

  [3911/13157] intraday_12647.csv.gz  in=256,303,565 out=68,097,691 elapsed=279.4s

  [3912/13157] intraday_12646.csv.gz  in=256,315,866 out=68,109,992 elapsed=279.4s

  [3913/13157] intraday_12648.csv.gz  in=256,329,381 out=68,123,507 elapsed=279.4s

  [3914/13157] intraday_12649.csv.gz  in=256,340,313 out=68,134,439 elapsed=279.4s

  [3915/13157] intraday_1265.csv.gz  in=256,351,909 out=68,134,439 elapsed=279.4s

  [3916/13157] intraday_12651.csv.gz  in=256,362,794 out=68,145,324 elapsed=279.5s

  [3917/13157] intraday_12650.csv.gz  in=256,375,588 out=68,158,118 elapsed=279.5s

  [3918/13157] intraday_12652.csv.gz  in=256,385,471 out=68,168,001 elapsed=279.5s

  [3919/13157] intraday_12653.csv.gz  in=256,399,431 out=68,181,961 elapsed=279.6s

  [3920/13157] intraday_12654.csv.gz  in=256,413,134 out=68,195,664 elapsed=279.6s

  [3921/13157] intraday_12656.csv.gz  in=256,426,490 out=68,209,020 elapsed=279.6s

  [3922/13157] intraday_12655.csv.gz  in=256,442,333 out=68,224,863 elapsed=279.6s

  [3923/13157] intraday_12657.csv.gz  in=256,460,843 out=68,242,904 elapsed=279.7s

  [3924/13157] intraday_12659.csv.gz  in=256,474,235 out=68,256,296 elapsed=279.7s

  [3925/13157] intraday_1266.csv.gz  in=256,489,010 out=68,256,296 elapsed=279.7s

  [3926/13157] intraday_12661.csv.gz  in=256,502,406 out=68,269,692 elapsed=279.7s

  [3927/13157] intraday_12660.csv.gz  in=256,516,813 out=68,284,099 elapsed=279.8s

  [3928/13157] intraday_12662.csv.gz  in=256,528,050 out=68,295,336 elapsed=279.8s

  [3929/13157] intraday_12658.csv.gz  in=256,539,149 out=68,306,435 elapsed=279.8s

  [3930/13157] intraday_12664.csv.gz  in=256,552,893 out=68,320,179 elapsed=279.8s

  [3931/13157] intraday_12663.csv.gz  in=256,568,300 out=68,335,586 elapsed=279.8s

  [3932/13157] intraday_12665.csv.gz  in=256,579,228 out=68,346,514 elapsed=279.8s

  [3933/13157] intraday_12666.csv.gz  in=256,593,054 out=68,360,340 elapsed=279.8s

  [3934/13157] intraday_1267.csv.gz  in=256,605,374 out=68,360,340 elapsed=279.9s

  [3935/13157] intraday_12667.csv.gz  in=256,616,160 out=68,371,126 elapsed=280.0s

  [3936/13157] intraday_12669.csv.gz  in=256,627,614 out=68,382,580 elapsed=280.0s

  [3937/13157] intraday_12668.csv.gz  in=256,640,216 out=68,395,182 elapsed=280.0s

  [3938/13157] intraday_12670.csv.gz  in=256,652,522 out=68,407,488 elapsed=280.0s

  [3939/13157] intraday_12672.csv.gz  in=256,664,422 out=68,419,388 elapsed=280.1s

  [3940/13157] intraday_12671.csv.gz  in=256,676,617 out=68,431,583 elapsed=280.1s

  [3941/13157] intraday_12673.csv.gz  in=256,690,876 out=68,445,842 elapsed=280.1s

  [3942/13157] intraday_12674.csv.gz  in=256,703,588 out=68,458,554 elapsed=280.1s

  [3943/13157] intraday_12676.csv.gz  in=256,715,884 out=68,470,850 elapsed=280.1s

  [3944/13157] intraday_12675.csv.gz  in=256,729,834 out=68,484,800 elapsed=280.1s

  [3945/13157] intraday_12678.csv.gz  in=256,742,719 out=68,497,685 elapsed=280.1s

  [3946/13157] intraday_12677.csv.gz  in=256,757,037 out=68,512,003 elapsed=280.1s

  [3947/13157] intraday_1268.csv.gz  in=256,768,168 out=68,512,003 elapsed=280.2s

  [3948/13157] intraday_12679.csv.gz  in=256,779,591 out=68,523,426 elapsed=280.3s

  [3949/13157] intraday_12681.csv.gz  in=256,794,351 out=68,538,186 elapsed=280.3s

  [3950/13157] intraday_12680.csv.gz  in=256,808,387 out=68,552,222 elapsed=280.3s

  [3951/13157] intraday_12683.csv.gz  in=256,820,741 out=68,564,576 elapsed=280.4s

  [3952/13157] intraday_12684.csv.gz  in=256,835,860 out=68,579,695 elapsed=280.4s

  [3953/13157] intraday_12685.csv.gz  in=256,851,015 out=68,594,850 elapsed=280.4s

  [3954/13157] intraday_12682.csv.gz  in=256,863,880 out=68,607,715 elapsed=280.5s

  [3955/13157] intraday_12686.csv.gz  in=256,877,607 out=68,621,442 elapsed=280.6s

  [3956/13157] intraday_12687.csv.gz  in=256,893,945 out=68,637,780 elapsed=280.6s

  [3957/13157] intraday_12689.csv.gz  in=256,906,845 out=68,650,680 elapsed=280.6s

  [3958/13157] intraday_1269.csv.gz  in=256,918,082 out=68,650,680 elapsed=280.6s

  [3959/13157] intraday_12688.csv.gz  in=256,939,211 out=68,671,809 elapsed=280.6s

  [3960/13157] intraday_12690.csv.gz  in=256,955,293 out=68,687,891 elapsed=280.7s

  [3961/13157] intraday_12691.csv.gz  in=256,968,534 out=68,701,132 elapsed=280.7s

  [3962/13157] intraday_12692.csv.gz  in=256,980,985 out=68,713,583 elapsed=280.7s

  [3963/13157] intraday_12694.csv.gz  in=256,993,306 out=68,725,904 elapsed=280.7s

  [3964/13157] intraday_12696.csv.gz  in=257,005,179 out=68,737,777 elapsed=280.7s

  [3965/13157] intraday_12697.csv.gz  in=257,017,730 out=68,750,328 elapsed=280.8s

  [3966/13157] intraday_12695.csv.gz  in=257,029,677 out=68,762,275 elapsed=280.8s

  [3967/13157] intraday_12693.csv.gz  in=257,046,913 out=68,779,148 elapsed=280.8s

  [3968/13157] intraday_12698.csv.gz  in=257,060,900 out=68,793,135 elapsed=280.8s

  [3969/13157] intraday_1270.csv.gz  in=257,071,656 out=68,793,135 elapsed=280.8s

  [3970/13157] intraday_12699.csv.gz  in=257,085,186 out=68,806,665 elapsed=280.8s

  [3971/13157] intraday_12701.csv.gz  in=257,096,433 out=68,817,912 elapsed=280.8s

  [3972/13157] intraday_12700.csv.gz  in=257,108,657 out=68,830,136 elapsed=280.9s

  [3973/13157] intraday_12703.csv.gz  in=257,120,788 out=68,842,267 elapsed=280.9s

  [3974/13157] intraday_12704.csv.gz  in=257,132,635 out=68,854,114 elapsed=280.9s

  [3975/13157] intraday_12702.csv.gz  in=257,146,273 out=68,867,752 elapsed=280.9s

  [3976/13157] intraday_12705.csv.gz  in=257,160,829 out=68,882,308 elapsed=280.9s

  [3977/13157] intraday_12709.csv.gz  in=257,172,481 out=68,893,960 elapsed=281.1s

  [3978/13157] intraday_12708.csv.gz  in=257,188,252 out=68,909,731 elapsed=281.1s

  [3979/13157] intraday_12706.csv.gz  in=257,204,624 out=68,926,103 elapsed=281.1s

  [3980/13157] intraday_12707.csv.gz  in=257,218,350 out=68,939,829 elapsed=281.1s

  [3981/13157] intraday_12710.csv.gz  in=257,230,704 out=68,952,183 elapsed=281.4s

  [3982/13157] intraday_12711.csv.gz  in=257,241,396 out=68,962,875 elapsed=281.4s

  [3983/13157] intraday_1271.csv.gz  in=257,264,947 out=68,962,875 elapsed=281.4s

  [3984/13157] intraday_12712.csv.gz  in=257,277,521 out=68,975,449 elapsed=281.4s

  [3985/13157] intraday_12716.csv.gz  in=257,284,288 out=68,982,216 elapsed=281.5s

  [3986/13157] intraday_12715.csv.gz  in=257,299,051 out=68,996,979 elapsed=281.5s

  [3987/13157] intraday_12714.csv.gz  in=257,305,164 out=69,003,092 elapsed=281.5s

  [3988/13157] intraday_12713.csv.gz  in=257,315,237 out=69,013,165 elapsed=281.5s

  [3989/13157] intraday_12719.csv.gz  in=257,327,972 out=69,025,900 elapsed=281.5s

  [3990/13157] intraday_1272.csv.gz  in=257,341,168 out=69,025,900 elapsed=281.6s

  [3991/13157] intraday_12718.csv.gz  in=257,355,078 out=69,039,810 elapsed=281.6s

  [3992/13157] intraday_12717.csv.gz  in=257,371,457 out=69,056,189 elapsed=281.6s

  [3993/13157] intraday_12720.csv.gz  in=257,381,395 out=69,066,127 elapsed=281.6s

  [3994/13157] intraday_12723.csv.gz  in=257,396,795 out=69,081,527 elapsed=281.6s

  [3995/13157] intraday_12722.csv.gz  in=257,410,116 out=69,094,848 elapsed=281.7s

  [3996/13157] intraday_12725.csv.gz  in=257,424,010 out=69,108,742 elapsed=281.7s

  [3997/13157] intraday_12724.csv.gz  in=257,434,465 out=69,119,197 elapsed=281.7s

  [3998/13157] intraday_12721.csv.gz  in=257,446,939 out=69,131,671 elapsed=281.7s

  [3999/13157] intraday_12726.csv.gz  in=257,459,982 out=69,144,714 elapsed=281.7s

  [4000/13157] intraday_1273.csv.gz  in=257,478,057 out=69,144,714 elapsed=281.8s

  [4001/13157] intraday_12728.csv.gz  in=257,489,695 out=69,156,352 elapsed=281.8s

  [4002/13157] intraday_12729.csv.gz  in=257,515,937 out=69,181,860 elapsed=281.8s

  [4003/13157] intraday_12732.csv.gz  in=257,525,199 out=69,191,122 elapsed=281.9s

  [4004/13157] intraday_12730.csv.gz  in=257,538,139 out=69,204,062 elapsed=281.9s

  [4005/13157] intraday_12727.csv.gz  in=257,550,585 out=69,216,508 elapsed=281.9s

  [4006/13157] intraday_12731.csv.gz  in=257,560,580 out=69,226,503 elapsed=281.9s

  [4007/13157] intraday_12733.csv.gz  in=257,574,909 out=69,240,832 elapsed=282.0s

  [4008/13157] intraday_12736.csv.gz  in=257,585,990 out=69,251,913 elapsed=282.0s

  [4009/13157] intraday_12735.csv.gz  in=257,596,168 out=69,262,091 elapsed=282.0s

  [4010/13157] intraday_12734.csv.gz  in=257,608,403 out=69,274,326 elapsed=282.0s

  [4011/13157] intraday_12737.csv.gz  in=257,618,764 out=69,284,687 elapsed=282.0s

  [4012/13157] intraday_12738.csv.gz  in=257,630,827 out=69,296,746 elapsed=282.2s

  [4013/13157] intraday_12739.csv.gz  in=257,643,134 out=69,309,053 elapsed=282.2s

  [4014/13157] intraday_1274.csv.gz  in=257,659,354 out=69,309,053 elapsed=282.2s

  [4015/13157] intraday_12740.csv.gz  in=257,670,784 out=69,320,483 elapsed=282.2s

  [4016/13157] intraday_12744.csv.gz  in=257,683,582 out=69,333,281 elapsed=282.4s

  [4017/13157] intraday_12742.csv.gz  in=257,694,787 out=69,344,476 elapsed=282.4s

  [4018/13157] intraday_12743.csv.gz  in=257,707,535 out=69,357,224 elapsed=282.6s

  [4019/13157] intraday_12746.csv.gz  in=257,721,128 out=69,370,817 elapsed=282.6s

  [4020/13157] intraday_12741.csv.gz  in=257,736,365 out=69,386,054 elapsed=282.6s

  [4021/13157] intraday_12745.csv.gz  in=257,748,046 out=69,397,735 elapsed=282.9s

  [4022/13157] intraday_12749.csv.gz  in=257,758,465 out=69,408,154 elapsed=282.9s

  [4023/13157] intraday_12748.csv.gz  in=257,771,788 out=69,421,477 elapsed=282.9s

  [4024/13157] intraday_1275.csv.gz  in=257,783,338 out=69,421,477 elapsed=283.0s

  [4025/13157] intraday_12747.csv.gz  in=257,800,535 out=69,438,354 elapsed=283.0s

  [4026/13157] intraday_12750.csv.gz  in=257,813,324 out=69,451,143 elapsed=283.0s

  [4027/13157] intraday_12751.csv.gz  in=257,826,405 out=69,464,224 elapsed=283.0s

  [4028/13157] intraday_12752.csv.gz  in=257,839,814 out=69,477,633 elapsed=283.0s

  [4029/13157] intraday_12754.csv.gz  in=257,850,396 out=69,488,215 elapsed=283.2s

  [4030/13157] intraday_12755.csv.gz  in=257,861,738 out=69,499,557 elapsed=283.2s

  [4031/13157] intraday_12753.csv.gz  in=257,874,439 out=69,512,258 elapsed=283.2s

  [4032/13157] intraday_12756.csv.gz  in=257,884,470 out=69,522,289 elapsed=283.2s

  [4033/13157] intraday_12759.csv.gz  in=257,895,661 out=69,533,480 elapsed=283.4s

  [4034/13157] intraday_1276.csv.gz  in=257,908,488 out=69,533,480 elapsed=283.4s

  [4035/13157] intraday_12757.csv.gz  in=257,919,151 out=69,544,143 elapsed=283.4s

  [4036/13157] intraday_12758.csv.gz  in=257,932,551 out=69,557,543 elapsed=283.6s

  [4037/13157] intraday_12762.csv.gz  in=257,944,038 out=69,569,030 elapsed=283.6s

  [4038/13157] intraday_12760.csv.gz  in=257,956,413 out=69,581,405 elapsed=283.7s

  [4039/13157] intraday_12761.csv.gz  in=257,970,606 out=69,595,598 elapsed=283.7s

  [4040/13157] intraday_12763.csv.gz  in=257,981,825 out=69,606,817 elapsed=283.8s

  [4041/13157] intraday_12764.csv.gz  in=257,993,942 out=69,618,185 elapsed=283.8s

  [4042/13157] intraday_12766.csv.gz  in=258,004,405 out=69,628,648 elapsed=283.8s

  [4043/13157] intraday_12765.csv.gz  in=258,016,683 out=69,640,926 elapsed=284.2s

  [4044/13157] intraday_12767.csv.gz  in=258,028,361 out=69,652,604 elapsed=284.5s

  [4045/13157] intraday_1277.csv.gz  in=258,040,290 out=69,652,604 elapsed=284.5s

  [4046/13157] intraday_12768.csv.gz  in=258,051,283 out=69,663,597 elapsed=284.5s

  [4047/13157] intraday_12769.csv.gz  in=258,064,537 out=69,676,822 elapsed=284.5s

  [4048/13157] intraday_12772.csv.gz  in=258,078,273 out=69,690,558 elapsed=284.6s

  [4049/13157] intraday_12770.csv.gz  in=258,090,210 out=69,702,495 elapsed=284.6s

  [4050/13157] intraday_12773.csv.gz  in=258,101,017 out=69,713,302 elapsed=284.8s

  [4051/13157] intraday_12771.csv.gz  in=258,112,774 out=69,725,059 elapsed=284.8s

  [4052/13157] intraday_12775.csv.gz  in=258,122,667 out=69,734,952 elapsed=284.8s

  [4053/13157] intraday_12774.csv.gz  in=258,134,757 out=69,747,042 elapsed=285.3s

  [4054/13157] intraday_12776.csv.gz  in=258,146,379 out=69,758,664 elapsed=285.5s

  [4055/13157] intraday_12777.csv.gz  in=258,159,841 out=69,772,126 elapsed=285.5s

  [4056/13157] intraday_12778.csv.gz  in=258,170,837 out=69,783,122 elapsed=285.9s

  [4057/13157] intraday_12779.csv.gz  in=258,182,611 out=69,794,896 elapsed=286.2s

  [4058/13157] intraday_1278.csv.gz  in=258,195,271 out=69,794,896 elapsed=286.3s

  [4059/13157] intraday_12781.csv.gz  in=258,204,167 out=69,803,792 elapsed=286.3s

  [4060/13157] intraday_12780.csv.gz  in=258,216,025 out=69,815,650 elapsed=286.3s

  [4061/13157] intraday_12784.csv.gz  in=258,229,250 out=69,828,875 elapsed=286.4s

  [4062/13157] intraday_12782.csv.gz  in=258,242,716 out=69,842,341 elapsed=286.4s

  [4063/13157] intraday_12783.csv.gz  in=258,256,496 out=69,856,121 elapsed=286.4s

  [4064/13157] intraday_12785.csv.gz  in=258,269,933 out=69,869,558 elapsed=286.5s

  [4065/13157] intraday_12787.csv.gz  in=258,280,562 out=69,880,187 elapsed=286.5s

  [4066/13157] intraday_12788.csv.gz  in=258,292,397 out=69,892,022 elapsed=286.5s

  [4067/13157] intraday_1279.csv.gz  in=258,304,308 out=69,892,022 elapsed=286.5s

  [4068/13157] intraday_12786.csv.gz  in=258,320,250 out=69,907,831 elapsed=286.6s

  [4069/13157] intraday_12789.csv.gz  in=258,332,726 out=69,920,307 elapsed=286.6s

  [4070/13157] intraday_12790.csv.gz  in=258,344,329 out=69,931,910 elapsed=286.9s

  [4071/13157] intraday_12792.csv.gz  in=258,356,405 out=69,943,986 elapsed=287.4s

  [4072/13157] intraday_12794.csv.gz  in=258,366,349 out=69,953,930 elapsed=287.4s

  [4073/13157] intraday_12791.csv.gz  in=258,379,863 out=69,967,444 elapsed=287.4s

  [4074/13157] intraday_12793.csv.gz  in=258,396,320 out=69,983,749 elapsed=287.4s

  [4075/13157] intraday_12795.csv.gz  in=258,409,744 out=69,997,173 elapsed=287.4s

  [4076/13157] intraday_12796.csv.gz  in=258,420,981 out=70,008,410 elapsed=287.4s

  [4077/13157] intraday_12797.csv.gz  in=258,432,612 out=70,020,041 elapsed=287.5s

  [4078/13157] intraday_1280.csv.gz  in=258,443,413 out=70,020,041 elapsed=287.5s

  [4079/13157] intraday_12798.csv.gz  in=258,454,940 out=70,031,568 elapsed=287.5s

  [4080/13157] intraday_12799.csv.gz  in=258,465,121 out=70,041,749 elapsed=287.5s

  [4081/13157] intraday_12800.csv.gz  in=258,478,137 out=70,054,765 elapsed=287.5s

  [4082/13157] intraday_12803.csv.gz  in=258,491,847 out=70,068,475 elapsed=287.6s

  [4083/13157] intraday_12804.csv.gz  in=258,503,837 out=70,080,465 elapsed=287.6s

  [4084/13157] intraday_12801.csv.gz  in=258,516,518 out=70,093,146 elapsed=287.6s

  [4085/13157] intraday_12802.csv.gz  in=258,532,974 out=70,109,602 elapsed=287.6s

  [4086/13157] intraday_12805.csv.gz  in=258,543,342 out=70,119,970 elapsed=287.6s

  [4087/13157] intraday_12806.csv.gz  in=258,555,732 out=70,132,360 elapsed=287.7s

  [4088/13157] intraday_12808.csv.gz  in=258,570,142 out=70,146,770 elapsed=287.7s

  [4089/13157] intraday_12807.csv.gz  in=258,582,733 out=70,159,361 elapsed=287.7s

  [4090/13157] intraday_12809.csv.gz  in=258,594,652 out=70,171,207 elapsed=287.7s

  [4091/13157] intraday_12810.csv.gz  in=258,608,860 out=70,185,415 elapsed=287.8s

  [4092/13157] intraday_1281.csv.gz  in=258,623,481 out=70,185,415 elapsed=287.8s

  [4093/13157] intraday_12811.csv.gz  in=258,637,427 out=70,199,361 elapsed=287.8s

  [4094/13157] intraday_12812.csv.gz  in=258,649,450 out=70,211,384 elapsed=287.9s

  [4095/13157] intraday_12815.csv.gz  in=258,662,840 out=70,224,774 elapsed=287.9s

  [4096/13157] intraday_12814.csv.gz  in=258,675,356 out=70,237,290 elapsed=287.9s

  [4097/13157] intraday_12813.csv.gz  in=258,702,662 out=70,263,099 elapsed=287.9s

  [4098/13157] intraday_12816.csv.gz  in=258,711,938 out=70,272,375 elapsed=288.0s

  [4099/13157] intraday_12819.csv.gz  in=258,724,345 out=70,284,782 elapsed=288.0s

  [4100/13157] intraday_1282.csv.gz  in=258,735,724 out=70,284,782 elapsed=288.1s

  [4101/13157] intraday_12818.csv.gz  in=258,746,754 out=70,295,812 elapsed=288.1s

  [4102/13157] intraday_12817.csv.gz  in=258,759,078 out=70,308,136 elapsed=288.1s

  [4103/13157] intraday_12820.csv.gz  in=258,773,222 out=70,322,280 elapsed=288.1s

  [4104/13157] intraday_12821.csv.gz  in=258,785,056 out=70,334,114 elapsed=288.2s

  [4105/13157] intraday_12822.csv.gz  in=258,799,640 out=70,348,698 elapsed=288.2s

  [4106/13157] intraday_12824.csv.gz  in=258,815,776 out=70,364,643 elapsed=288.2s

  [4107/13157] intraday_12823.csv.gz  in=258,828,385 out=70,377,252 elapsed=288.2s

  [4108/13157] intraday_12825.csv.gz  in=258,840,530 out=70,389,397 elapsed=288.3s

  [4109/13157] intraday_12826.csv.gz  in=258,852,525 out=70,401,392 elapsed=288.3s

  [4110/13157] intraday_12827.csv.gz  in=258,865,415 out=70,414,282 elapsed=288.3s

  [4111/13157] intraday_1283.csv.gz  in=258,877,286 out=70,414,282 elapsed=288.3s

  [4112/13157] intraday_12830.csv.gz  in=258,890,071 out=70,427,067 elapsed=288.4s

  [4113/13157] intraday_12829.csv.gz  in=258,902,192 out=70,439,188 elapsed=288.4s

  [4114/13157] intraday_12828.csv.gz  in=258,916,397 out=70,453,393 elapsed=288.4s

  [4115/13157] intraday_12832.csv.gz  in=258,930,470 out=70,467,466 elapsed=288.4s

  [4116/13157] intraday_12831.csv.gz  in=258,944,552 out=70,481,548 elapsed=288.4s

  [4117/13157] intraday_12833.csv.gz  in=258,956,403 out=70,493,399 elapsed=288.4s

  [4118/13157] intraday_12834.csv.gz  in=258,971,670 out=70,508,666 elapsed=288.4s

  [4119/13157] intraday_12838.csv.gz  in=258,983,948 out=70,520,944 elapsed=288.5s

  [4120/13157] intraday_12836.csv.gz  in=258,996,871 out=70,533,867 elapsed=288.5s

  [4121/13157] intraday_12835.csv.gz  in=259,016,290 out=70,553,286 elapsed=288.5s

  [4122/13157] intraday_12837.csv.gz  in=259,031,411 out=70,568,407 elapsed=288.5s

  [4123/13157] intraday_12839.csv.gz  in=259,043,801 out=70,580,797 elapsed=288.5s

  [4124/13157] intraday_1284.csv.gz  in=259,055,675 out=70,580,797 elapsed=288.5s

  [4125/13157] intraday_12840.csv.gz  in=259,068,620 out=70,593,742 elapsed=288.5s

  [4126/13157] intraday_12842.csv.gz  in=259,079,128 out=70,604,250 elapsed=288.6s

  [4127/13157] intraday_12843.csv.gz  in=259,091,678 out=70,616,747 elapsed=288.7s

  [4128/13157] intraday_12841.csv.gz  in=259,104,371 out=70,629,440 elapsed=288.7s

  [4129/13157] intraday_12844.csv.gz  in=259,116,572 out=70,641,641 elapsed=288.7s

  [4130/13157] intraday_12845.csv.gz  in=259,130,058 out=70,655,127 elapsed=288.7s

  [4131/13157] intraday_12847.csv.gz  in=259,141,102 out=70,666,171 elapsed=288.7s

  [4132/13157] intraday_12848.csv.gz  in=259,151,967 out=70,677,036 elapsed=288.7s

  [4133/13157] intraday_12846.csv.gz  in=259,165,084 out=70,690,093 elapsed=288.7s

  [4134/13157] intraday_1285.csv.gz  in=259,178,238 out=70,690,093 elapsed=288.8s

  [4135/13157] intraday_12849.csv.gz  in=259,190,658 out=70,702,513 elapsed=288.9s

  [4136/13157] intraday_12850.csv.gz  in=259,201,123 out=70,712,978 elapsed=288.9s

  [4137/13157] intraday_12851.csv.gz  in=259,214,030 out=70,725,885 elapsed=288.9s

  [4138/13157] intraday_12852.csv.gz  in=259,228,361 out=70,740,216 elapsed=289.0s

  [4139/13157] intraday_12853.csv.gz  in=259,243,583 out=70,755,438 elapsed=289.0s

  [4140/13157] intraday_12855.csv.gz  in=259,256,725 out=70,768,580 elapsed=289.0s

  [4141/13157] intraday_12854.csv.gz  in=259,269,888 out=70,781,743 elapsed=289.0s

  [4142/13157] intraday_12856.csv.gz  in=259,282,057 out=70,793,912 elapsed=289.1s

  [4143/13157] intraday_12859.csv.gz  in=259,295,400 out=70,807,255 elapsed=289.1s

  [4144/13157] intraday_12858.csv.gz  in=259,307,125 out=70,818,980 elapsed=289.1s

  [4145/13157] intraday_12857.csv.gz  in=259,321,768 out=70,833,236 elapsed=289.1s

  [4146/13157] intraday_12860.csv.gz  in=259,331,209 out=70,842,677 elapsed=289.2s

  [4147/13157] intraday_12861.csv.gz  in=259,338,375 out=70,849,843 elapsed=289.2s

  [4148/13157] intraday_12862.csv.gz  in=259,352,201 out=70,863,669 elapsed=289.3s

  [4149/13157] intraday_1286.csv.gz  in=259,385,015 out=70,863,669 elapsed=289.3s

  [4150/13157] intraday_12863.csv.gz  in=259,391,221 out=70,869,875 elapsed=289.6s

  [4151/13157] intraday_12864.csv.gz  in=259,406,739 out=70,885,393 elapsed=289.8s

  [4152/13157] intraday_12866.csv.gz  in=259,418,703 out=70,897,357 elapsed=289.9s

  [4153/13157] intraday_12867.csv.gz  in=259,429,740 out=70,908,394 elapsed=289.9s

  [4154/13157] intraday_12868.csv.gz  in=259,441,248 out=70,919,902 elapsed=289.9s

  [4155/13157] intraday_12865.csv.gz  in=259,453,896 out=70,932,550 elapsed=289.9s

  [4156/13157] intraday_12869.csv.gz  in=259,467,152 out=70,945,806 elapsed=290.0s

  [4157/13157] intraday_1287.csv.gz  in=259,488,026 out=70,945,806 elapsed=290.0s

  [4158/13157] intraday_12871.csv.gz  in=259,498,596 out=70,956,376 elapsed=290.0s

  [4159/13157] intraday_12870.csv.gz  in=259,511,346 out=70,969,126 elapsed=290.1s

  [4160/13157] intraday_12872.csv.gz  in=259,524,719 out=70,982,499 elapsed=290.1s

  [4161/13157] intraday_12873.csv.gz  in=259,538,498 out=70,996,278 elapsed=290.1s

  [4162/13157] intraday_12874.csv.gz  in=259,550,059 out=71,007,839 elapsed=290.1s

  [4163/13157] intraday_12875.csv.gz  in=259,561,968 out=71,019,748 elapsed=290.1s

  [4164/13157] intraday_12878.csv.gz  in=259,571,120 out=71,028,900 elapsed=290.1s

  [4165/13157] intraday_12879.csv.gz  in=259,581,186 out=71,038,966 elapsed=290.1s

  [4166/13157] intraday_12877.csv.gz  in=259,594,418 out=71,052,198 elapsed=290.1s

  [4167/13157] intraday_1288.csv.gz  in=259,607,700 out=71,052,198 elapsed=290.2s

  [4168/13157] intraday_12876.csv.gz  in=259,643,396 out=71,087,146 elapsed=290.2s

  [4169/13157] intraday_12881.csv.gz  in=259,656,650 out=71,100,400 elapsed=290.2s

  [4170/13157] intraday_12882.csv.gz  in=259,666,365 out=71,110,115 elapsed=290.2s

  [4171/13157] intraday_12880.csv.gz  in=259,679,585 out=71,123,335 elapsed=290.2s

  [4172/13157] intraday_12883.csv.gz  in=259,690,328 out=71,134,078 elapsed=290.2s

  [4173/13157] intraday_12884.csv.gz  in=259,701,365 out=71,145,115 elapsed=290.2s

  [4174/13157] intraday_12885.csv.gz  in=259,713,372 out=71,157,122 elapsed=290.3s

  [4175/13157] intraday_12888.csv.gz  in=259,727,144 out=71,170,894 elapsed=290.3s

  [4176/13157] intraday_12887.csv.gz  in=259,738,694 out=71,182,444 elapsed=290.3s

  [4177/13157] intraday_12886.csv.gz  in=259,750,522 out=71,194,272 elapsed=290.4s

  [4178/13157] intraday_1289.csv.gz  in=259,764,839 out=71,194,272 elapsed=290.4s

  [4179/13157] intraday_12890.csv.gz  in=259,777,483 out=71,206,916 elapsed=290.4s

  [4180/13157] intraday_12889.csv.gz  in=259,796,089 out=71,225,308 elapsed=290.4s

  [4181/13157] intraday_12892.csv.gz  in=259,805,548 out=71,234,767 elapsed=290.5s

  [4182/13157] intraday_12893.csv.gz  in=259,819,565 out=71,248,784 elapsed=290.5s

  [4183/13157] intraday_12891.csv.gz  in=259,832,044 out=71,261,263 elapsed=290.5s

  [4184/13157] intraday_12894.csv.gz  in=259,846,077 out=71,275,296 elapsed=290.5s

  [4185/13157] intraday_12895.csv.gz  in=259,859,072 out=71,288,291 elapsed=290.6s

  [4186/13157] intraday_12898.csv.gz  in=259,870,723 out=71,299,942 elapsed=290.6s

  [4187/13157] intraday_12899.csv.gz  in=259,883,654 out=71,312,873 elapsed=290.6s

  [4188/13157] intraday_12896.csv.gz  in=259,893,477 out=71,322,696 elapsed=290.6s

  [4189/13157] intraday_1290.csv.gz  in=259,907,419 out=71,322,696 elapsed=290.7s

  [4190/13157] intraday_12897.csv.gz  in=259,920,160 out=71,335,437 elapsed=290.7s

  [4191/13157] intraday_12900.csv.gz  in=259,932,415 out=71,347,692 elapsed=290.7s

  [4192/13157] intraday_12901.csv.gz  in=259,943,786 out=71,359,063 elapsed=290.7s

  [4193/13157] intraday_12903.csv.gz  in=259,953,456 out=71,368,733 elapsed=290.8s

  [4194/13157] intraday_12905.csv.gz  in=259,965,843 out=71,381,120 elapsed=291.2s

  [4195/13157] intraday_12904.csv.gz  in=259,976,222 out=71,391,499 elapsed=291.2s

  [4196/13157] intraday_12906.csv.gz  in=259,987,934 out=71,403,211 elapsed=291.3s

  [4197/13157] intraday_12902.csv.gz  in=259,998,664 out=71,413,941 elapsed=291.3s

  [4198/13157] intraday_12907.csv.gz  in=260,011,024 out=71,426,301 elapsed=291.5s

  [4199/13157] intraday_12908.csv.gz  in=260,024,600 out=71,439,877 elapsed=291.9s

  [4200/13157] intraday_12909.csv.gz  in=260,035,234 out=71,450,511 elapsed=292.2s

  [4201/13157] intraday_1291.csv.gz  in=260,054,730 out=71,450,511 elapsed=292.2s

  [4202/13157] intraday_12910.csv.gz  in=260,066,281 out=71,462,062 elapsed=292.2s

  [4203/13157] intraday_12911.csv.gz  in=260,077,040 out=71,472,821 elapsed=292.2s

  [4204/13157] intraday_12915.csv.gz  in=260,087,422 out=71,483,203 elapsed=292.3s

  [4205/13157] intraday_12913.csv.gz  in=260,097,740 out=71,493,521 elapsed=292.3s

  [4206/13157] intraday_12914.csv.gz  in=260,109,462 out=71,505,243 elapsed=292.3s

  [4207/13157] intraday_12912.csv.gz  in=260,121,868 out=71,517,649 elapsed=292.3s

  [4208/13157] intraday_12917.csv.gz  in=260,133,113 out=71,528,893 elapsed=292.4s

  [4209/13157] intraday_12916.csv.gz  in=260,146,539 out=71,542,319 elapsed=292.4s

  [4210/13157] intraday_1292.csv.gz  in=260,156,530 out=71,542,319 elapsed=292.4s

  [4211/13157] intraday_12918.csv.gz  in=260,168,957 out=71,554,746 elapsed=292.4s

  [4212/13157] intraday_12919.csv.gz  in=260,181,686 out=71,567,475 elapsed=292.4s

  [4213/13157] intraday_12920.csv.gz  in=260,192,288 out=71,578,077 elapsed=292.4s

  [4214/13157] intraday_12922.csv.gz  in=260,203,068 out=71,588,857 elapsed=292.4s

  [4215/13157] intraday_12923.csv.gz  in=260,214,833 out=71,600,622 elapsed=292.4s

  [4216/13157] intraday_12924.csv.gz  in=260,226,399 out=71,612,188 elapsed=292.5s

  [4217/13157] intraday_12921.csv.gz  in=260,237,122 out=71,622,911 elapsed=292.5s

  [4218/13157] intraday_12925.csv.gz  in=260,248,970 out=71,634,759 elapsed=292.5s

  [4219/13157] intraday_12928.csv.gz  in=260,257,906 out=71,643,695 elapsed=292.5s

  [4220/13157] intraday_12926.csv.gz  in=260,269,326 out=71,655,115 elapsed=292.6s

  [4221/13157] intraday_12927.csv.gz  in=260,281,230 out=71,667,019 elapsed=292.6s

  [4222/13157] intraday_12929.csv.gz  in=260,293,842 out=71,679,631 elapsed=292.6s

  [4223/13157] intraday_1293.csv.gz  in=260,305,936 out=71,679,631 elapsed=292.6s

  [4224/13157] intraday_12930.csv.gz  in=260,319,540 out=71,693,235 elapsed=292.6s

  [4225/13157] intraday_12932.csv.gz  in=260,332,515 out=71,706,210 elapsed=292.6s

  [4226/13157] intraday_12931.csv.gz  in=260,344,310 out=71,718,005 elapsed=292.6s

  [4227/13157] intraday_12933.csv.gz  in=260,355,849 out=71,729,544 elapsed=292.7s

  [4228/13157] intraday_12934.csv.gz  in=260,365,070 out=71,738,765 elapsed=292.7s

  [4229/13157] intraday_12936.csv.gz  in=260,377,094 out=71,750,789 elapsed=292.7s

  [4230/13157] intraday_12935.csv.gz  in=260,389,066 out=71,762,761 elapsed=292.7s

  [4231/13157] intraday_12937.csv.gz  in=260,400,977 out=71,774,672 elapsed=292.7s

  [4232/13157] intraday_12938.csv.gz  in=260,413,306 out=71,787,001 elapsed=292.7s

  [4233/13157] intraday_1294.csv.gz  in=260,425,746 out=71,787,001 elapsed=292.8s

  [4234/13157] intraday_12939.csv.gz  in=260,437,723 out=71,798,978 elapsed=292.8s

  [4235/13157] intraday_12940.csv.gz  in=260,447,053 out=71,808,308 elapsed=292.8s

  [4236/13157] intraday_12941.csv.gz  in=260,458,303 out=71,819,558 elapsed=292.8s

  [4237/13157] intraday_12942.csv.gz  in=260,472,760 out=71,834,015 elapsed=292.8s

  [4238/13157] intraday_12945.csv.gz  in=260,482,526 out=71,843,781 elapsed=292.9s

  [4239/13157] intraday_12944.csv.gz  in=260,493,797 out=71,855,052 elapsed=292.9s

  [4240/13157] intraday_12943.csv.gz  in=260,505,703 out=71,866,958 elapsed=292.9s

  [4241/13157] intraday_12946.csv.gz  in=260,516,376 out=71,877,631 elapsed=292.9s

  [4242/13157] intraday_12947.csv.gz  in=260,528,527 out=71,889,782 elapsed=292.9s

  [4243/13157] intraday_1295.csv.gz  in=260,540,984 out=71,889,782 elapsed=293.0s

  [4244/13157] intraday_12948.csv.gz  in=260,553,862 out=71,902,660 elapsed=293.1s

  [4245/13157] intraday_12950.csv.gz  in=260,568,395 out=71,917,193 elapsed=293.1s

  [4246/13157] intraday_12949.csv.gz  in=260,583,013 out=71,931,811 elapsed=293.1s

  [4247/13157] intraday_12952.csv.gz  in=260,594,485 out=71,943,283 elapsed=293.2s

  [4248/13157] intraday_12951.csv.gz  in=260,606,129 out=71,954,927 elapsed=293.2s

  [4249/13157] intraday_12953.csv.gz  in=260,617,172 out=71,965,970 elapsed=293.2s

  [4250/13157] intraday_12956.csv.gz  in=260,627,577 out=71,976,375 elapsed=293.3s

  [4251/13157] intraday_12954.csv.gz  in=260,641,493 out=71,990,291 elapsed=293.3s

  [4252/13157] intraday_12957.csv.gz  in=260,657,234 out=72,006,032 elapsed=293.3s

  [4253/13157] intraday_12955.csv.gz  in=260,669,165 out=72,017,963 elapsed=293.3s

  [4254/13157] intraday_12959.csv.gz  in=260,681,327 out=72,030,125 elapsed=293.5s

  [4255/13157] intraday_1296.csv.gz  in=260,698,165 out=72,030,125 elapsed=293.7s

  [4256/13157] intraday_12958.csv.gz  in=260,709,228 out=72,041,188 elapsed=293.7s

  [4257/13157] intraday_12960.csv.gz  in=260,721,439 out=72,053,399 elapsed=293.7s

  [4258/13157] intraday_12964.csv.gz  in=260,731,751 out=72,063,711 elapsed=293.8s

  [4259/13157] intraday_12962.csv.gz  in=260,743,570 out=72,075,530 elapsed=293.8s

  [4260/13157] intraday_12963.csv.gz  in=260,755,382 out=72,087,342 elapsed=293.8s

  [4261/13157] intraday_12961.csv.gz  in=260,767,234 out=72,099,194 elapsed=293.9s

  [4262/13157] intraday_12967.csv.gz  in=260,779,064 out=72,111,024 elapsed=293.9s

  [4263/13157] intraday_12965.csv.gz  in=260,790,024 out=72,121,984 elapsed=293.9s

  [4264/13157] intraday_12966.csv.gz  in=260,802,642 out=72,134,602 elapsed=293.9s

  [4265/13157] intraday_12968.csv.gz  in=260,813,730 out=72,145,690 elapsed=293.9s

  [4266/13157] intraday_12970.csv.gz  in=260,825,374 out=72,157,334 elapsed=293.9s

  [4267/13157] intraday_1297.csv.gz  in=260,846,229 out=72,157,334 elapsed=293.9s

  [4268/13157] intraday_12969.csv.gz  in=260,860,158 out=72,171,263 elapsed=293.9s

  [4269/13157] intraday_12973.csv.gz  in=260,876,868 out=72,187,823 elapsed=294.0s

  [4270/13157] intraday_12972.csv.gz  in=260,887,192 out=72,198,147 elapsed=294.0s

  [4271/13157] intraday_12971.csv.gz  in=260,902,469 out=72,213,424 elapsed=294.0s

  [4272/13157] intraday_12974.csv.gz  in=260,916,571 out=72,227,526 elapsed=294.0s

  [4273/13157] intraday_12975.csv.gz  in=260,930,822 out=72,241,777 elapsed=294.0s

  [4274/13157] intraday_12976.csv.gz  in=260,941,344 out=72,252,299 elapsed=294.0s

  [4275/13157] intraday_12977.csv.gz  in=260,954,017 out=72,264,972 elapsed=294.0s

  [4276/13157] intraday_12978.csv.gz  in=260,967,994 out=72,278,949 elapsed=294.0s

  [4277/13157] intraday_12979.csv.gz  in=260,982,068 out=72,293,023 elapsed=294.1s

  [4278/13157] intraday_1298.csv.gz  in=261,000,957 out=72,293,023 elapsed=294.1s

  [4279/13157] intraday_12980.csv.gz  in=261,013,580 out=72,305,646 elapsed=294.1s

  [4280/13157] intraday_12981.csv.gz  in=261,027,760 out=72,319,826 elapsed=294.1s

  [4281/13157] intraday_12985.csv.gz  in=261,037,641 out=72,329,707 elapsed=294.2s

  [4282/13157] intraday_12983.csv.gz  in=261,049,568 out=72,341,634 elapsed=294.2s

  [4283/13157] intraday_12984.csv.gz  in=261,064,982 out=72,357,048 elapsed=294.3s

  [4284/13157] intraday_12982.csv.gz  in=261,083,343 out=72,375,409 elapsed=294.3s

  [4285/13157] intraday_12987.csv.gz  in=261,095,373 out=72,387,439 elapsed=294.3s

  [4286/13157] intraday_12986.csv.gz  in=261,108,927 out=72,400,993 elapsed=294.3s

  [4287/13157] intraday_12988.csv.gz  in=261,121,434 out=72,413,500 elapsed=294.3s

  [4288/13157] intraday_12989.csv.gz  in=261,132,229 out=72,424,295 elapsed=294.3s

  [4289/13157] intraday_12991.csv.gz  in=261,143,807 out=72,435,873 elapsed=294.4s

  [4290/13157] intraday_1299.csv.gz  in=261,158,415 out=72,435,873 elapsed=294.4s

  [4291/13157] intraday_12990.csv.gz  in=261,170,068 out=72,447,526 elapsed=294.4s

  [4292/13157] intraday_12992.csv.gz  in=261,183,126 out=72,460,584 elapsed=294.4s

  [4293/13157] intraday_12994.csv.gz  in=261,195,497 out=72,472,955 elapsed=294.5s

  [4294/13157] intraday_12993.csv.gz  in=261,207,182 out=72,484,640 elapsed=294.5s

  [4295/13157] intraday_12996.csv.gz  in=261,220,733 out=72,498,191 elapsed=294.5s

  [4296/13157] intraday_12995.csv.gz  in=261,230,745 out=72,508,203 elapsed=294.5s

  [4297/13157] intraday_12997.csv.gz  in=261,240,907 out=72,518,365 elapsed=294.6s

  [4298/13157] intraday_1300.csv.gz  in=261,253,416 out=72,518,365 elapsed=294.6s

  [4299/13157] intraday_12999.csv.gz  in=261,267,255 out=72,532,204 elapsed=294.6s

  [4300/13157] intraday_12998.csv.gz  in=261,280,408 out=72,545,357 elapsed=294.6s

  [4301/13157] intraday_13000.csv.gz  in=261,294,911 out=72,559,860 elapsed=294.7s

  [4302/13157] intraday_13002.csv.gz  in=261,308,246 out=72,573,195 elapsed=294.7s

  [4303/13157] intraday_13001.csv.gz  in=261,321,789 out=72,586,738 elapsed=294.7s

  [4304/13157] intraday_13003.csv.gz  in=261,333,142 out=72,598,091 elapsed=294.7s

  [4305/13157] intraday_13007.csv.gz  in=261,341,872 out=72,606,821 elapsed=294.7s

  [4306/13157] intraday_13005.csv.gz  in=261,352,874 out=72,617,823 elapsed=294.7s

  [4307/13157] intraday_13006.csv.gz  in=261,366,209 out=72,631,158 elapsed=294.7s

  [4308/13157] intraday_13004.csv.gz  in=261,378,627 out=72,643,576 elapsed=294.7s

  [4309/13157] intraday_13010.csv.gz  in=261,382,501 out=72,647,450 elapsed=294.8s

  [4310/13157] intraday_13008.csv.gz  in=261,390,138 out=72,655,087 elapsed=294.8s

  [4311/13157] intraday_1301.csv.gz  in=261,402,638 out=72,655,087 elapsed=294.8s

  [4312/13157] intraday_13011.csv.gz  in=261,403,358 out=72,655,806 elapsed=294.8s

  [4313/13157] intraday_13009.csv.gz  in=261,417,107 out=72,669,555 elapsed=294.8s

  [4314/13157] intraday_13012.csv.gz  in=261,434,467 out=72,686,915 elapsed=294.8s

  [4315/13157] intraday_13013.csv.gz  in=261,447,500 out=72,699,948 elapsed=294.8s

  [4316/13157] intraday_13014.csv.gz  in=261,460,229 out=72,712,677 elapsed=294.8s

  [4317/13157] intraday_13015.csv.gz  in=261,470,746 out=72,723,194 elapsed=294.8s

  [4318/13157] intraday_13017.csv.gz  in=261,485,320 out=72,737,768 elapsed=294.9s

  [4319/13157] intraday_13016.csv.gz  in=261,498,074 out=72,750,522 elapsed=294.9s

  [4320/13157] intraday_13019.csv.gz  in=261,510,127 out=72,762,575 elapsed=294.9s

  [4321/13157] intraday_13018.csv.gz  in=261,522,950 out=72,775,398 elapsed=294.9s

  [4322/13157] intraday_13020.csv.gz  in=261,536,889 out=72,789,337 elapsed=294.9s

  [4323/13157] intraday_13021.csv.gz  in=261,549,521 out=72,801,969 elapsed=294.9s

  [4324/13157] intraday_13023.csv.gz  in=261,561,770 out=72,814,218 elapsed=294.9s

  [4325/13157] intraday_13022.csv.gz  in=261,574,905 out=72,827,353 elapsed=294.9s

  [4326/13157] intraday_13024.csv.gz  in=261,589,525 out=72,841,973 elapsed=295.0s

  [4327/13157] intraday_13025.csv.gz  in=261,602,748 out=72,855,196 elapsed=295.0s

  [4328/13157] intraday_13026.csv.gz  in=261,612,534 out=72,864,982 elapsed=295.0s

  [4329/13157] intraday_13027.csv.gz  in=261,622,576 out=72,875,024 elapsed=295.0s

  [4330/13157] intraday_13028.csv.gz  in=261,636,399 out=72,888,847 elapsed=295.0s

  [4331/13157] intraday_1302.csv.gz  in=261,649,646 out=72,888,847 elapsed=295.0s

  [4332/13157] intraday_13029.csv.gz  in=261,663,469 out=72,902,670 elapsed=295.0s

  [4333/13157] intraday_13030.csv.gz  in=261,673,445 out=72,912,646 elapsed=295.0s

  [4334/13157] intraday_13031.csv.gz  in=261,683,947 out=72,923,148 elapsed=295.0s

  [4335/13157] intraday_13032.csv.gz  in=261,695,902 out=72,935,103 elapsed=295.1s

  [4336/13157] intraday_13033.csv.gz  in=261,707,828 out=72,947,029 elapsed=295.1s

  [4337/13157] intraday_13034.csv.gz  in=261,720,711 out=72,959,912 elapsed=295.1s

  [4338/13157] intraday_13036.csv.gz  in=261,735,299 out=72,974,500 elapsed=295.1s

  [4339/13157] intraday_13035.csv.gz  in=261,747,872 out=72,987,073 elapsed=295.1s

  [4340/13157] intraday_13037.csv.gz  in=261,759,368 out=72,998,569 elapsed=295.1s

  [4341/13157] intraday_1303.csv.gz  in=261,772,036 out=72,998,569 elapsed=295.1s

  [4342/13157] intraday_13038.csv.gz  in=261,784,270 out=73,010,803 elapsed=295.1s

  [4343/13157] intraday_13039.csv.gz  in=261,796,921 out=73,023,454 elapsed=295.1s

  [4344/13157] intraday_13040.csv.gz  in=261,808,403 out=73,034,936 elapsed=295.2s

  [4345/13157] intraday_13041.csv.gz  in=261,821,069 out=73,047,602 elapsed=295.2s

  [4346/13157] intraday_13042.csv.gz  in=261,837,850 out=73,064,383 elapsed=295.2s

  [4347/13157] intraday_13043.csv.gz  in=261,851,590 out=73,078,123 elapsed=295.2s

  [4348/13157] intraday_13044.csv.gz  in=261,862,124 out=73,088,657 elapsed=295.2s

  [4349/13157] intraday_13045.csv.gz  in=261,873,836 out=73,100,369 elapsed=295.2s

  [4350/13157] intraday_13046.csv.gz  in=261,886,348 out=73,112,881 elapsed=295.2s

  [4351/13157] intraday_13048.csv.gz  in=261,898,811 out=73,125,344 elapsed=295.3s

  [4352/13157] intraday_13047.csv.gz  in=261,912,302 out=73,138,835 elapsed=295.3s

  [4353/13157] intraday_13049.csv.gz  in=261,923,681 out=73,150,214 elapsed=295.3s

  [4354/13157] intraday_13050.csv.gz  in=261,935,286 out=73,161,819 elapsed=295.3s

  [4355/13157] intraday_13051.csv.gz  in=261,944,481 out=73,171,014 elapsed=295.3s

  [4356/13157] intraday_13052.csv.gz  in=261,955,444 out=73,181,977 elapsed=295.3s

  [4357/13157] intraday_13053.csv.gz  in=261,968,310 out=73,194,843 elapsed=295.3s

  [4358/13157] intraday_13054.csv.gz  in=261,981,689 out=73,208,222 elapsed=295.4s

  [4359/13157] intraday_13055.csv.gz  in=261,993,908 out=73,220,441 elapsed=295.4s

  [4360/13157] intraday_13056.csv.gz  in=262,008,326 out=73,234,859 elapsed=295.4s

  [4361/13157] intraday_13057.csv.gz  in=262,018,695 out=73,245,228 elapsed=295.4s

  [4362/13157] intraday_13058.csv.gz  in=262,030,775 out=73,257,308 elapsed=295.4s

  [4363/13157] intraday_13059.csv.gz  in=262,043,577 out=73,270,110 elapsed=295.4s

  [4364/13157] intraday_1305.csv.gz  in=262,055,351 out=73,270,110 elapsed=295.5s

  [4365/13157] intraday_1304.csv.gz  in=262,066,525 out=73,270,110 elapsed=295.5s

  [4366/13157] intraday_13060.csv.gz  in=262,076,865 out=73,280,450 elapsed=295.5s

  [4367/13157] intraday_13062.csv.gz  in=262,087,438 out=73,291,023 elapsed=295.5s

  [4368/13157] intraday_13061.csv.gz  in=262,099,277 out=73,302,862 elapsed=295.5s

  [4369/13157] intraday_13063.csv.gz  in=262,111,524 out=73,315,109 elapsed=295.5s

  [4370/13157] intraday_13064.csv.gz  in=262,125,985 out=73,329,570 elapsed=295.5s

  [4371/13157] intraday_13065.csv.gz  in=262,137,682 out=73,341,267 elapsed=295.5s

  [4372/13157] intraday_13066.csv.gz  in=262,150,969 out=73,354,554 elapsed=295.5s

  [4373/13157] intraday_13068.csv.gz  in=262,163,124 out=73,366,709 elapsed=295.6s

  [4374/13157] intraday_13067.csv.gz  in=262,175,252 out=73,378,837 elapsed=295.6s

  [4375/13157] intraday_13069.csv.gz  in=262,187,399 out=73,390,984 elapsed=295.6s

  [4376/13157] intraday_13070.csv.gz  in=262,200,002 out=73,403,587 elapsed=295.6s

  [4377/13157] intraday_13071.csv.gz  in=262,211,639 out=73,415,224 elapsed=295.6s

  [4378/13157] intraday_13072.csv.gz  in=262,226,380 out=73,429,965 elapsed=295.6s

  [4379/13157] intraday_13073.csv.gz  in=262,240,133 out=73,443,718 elapsed=295.6s

  [4380/13157] intraday_13074.csv.gz  in=262,257,491 out=73,461,076 elapsed=295.7s

  [4381/13157] intraday_13075.csv.gz  in=262,268,478 out=73,472,063 elapsed=295.7s

  [4382/13157] intraday_13076.csv.gz  in=262,280,100 out=73,483,685 elapsed=295.7s

  [4383/13157] intraday_13077.csv.gz  in=262,296,267 out=73,499,852 elapsed=295.7s

  [4384/13157] intraday_13078.csv.gz  in=262,308,302 out=73,511,887 elapsed=295.7s

  [4385/13157] intraday_13079.csv.gz  in=262,322,135 out=73,525,720 elapsed=295.7s

  [4386/13157] intraday_1306.csv.gz  in=262,333,994 out=73,525,720 elapsed=295.7s

  [4387/13157] intraday_13080.csv.gz  in=262,346,475 out=73,538,201 elapsed=295.8s

  [4388/13157] intraday_1307.csv.gz  in=262,358,590 out=73,538,201 elapsed=295.8s

  [4389/13157] intraday_13081.csv.gz  in=262,369,739 out=73,549,350 elapsed=295.8s

  [4390/13157] intraday_13082.csv.gz  in=262,379,153 out=73,558,764 elapsed=295.8s

  [4391/13157] intraday_13084.csv.gz  in=262,392,678 out=73,572,289 elapsed=295.8s

  [4392/13157] intraday_13083.csv.gz  in=262,405,765 out=73,585,376 elapsed=295.8s

  [4393/13157] intraday_13085.csv.gz  in=262,419,162 out=73,598,773 elapsed=295.8s

  [4394/13157] intraday_13086.csv.gz  in=262,429,940 out=73,609,551 elapsed=295.8s

  [4395/13157] intraday_13087.csv.gz  in=262,442,922 out=73,622,533 elapsed=295.9s

  [4396/13157] intraday_13088.csv.gz  in=262,452,828 out=73,632,439 elapsed=295.9s

  [4397/13157] intraday_13089.csv.gz  in=262,468,398 out=73,648,009 elapsed=295.9s

  [4398/13157] intraday_13090.csv.gz  in=262,481,116 out=73,660,727 elapsed=295.9s

  [4399/13157] intraday_13091.csv.gz  in=262,492,017 out=73,671,628 elapsed=295.9s

  [4400/13157] intraday_13092.csv.gz  in=262,503,555 out=73,683,166 elapsed=295.9s

  [4401/13157] intraday_13093.csv.gz  in=262,514,544 out=73,694,155 elapsed=295.9s

  [4402/13157] intraday_13094.csv.gz  in=262,526,556 out=73,706,167 elapsed=296.0s

  [4403/13157] intraday_1308.csv.gz  in=262,538,441 out=73,706,167 elapsed=296.0s

  [4404/13157] intraday_13095.csv.gz  in=262,550,332 out=73,718,058 elapsed=296.0s

  [4405/13157] intraday_13096.csv.gz  in=262,568,858 out=73,736,584 elapsed=296.0s

  [4406/13157] intraday_13098.csv.gz  in=262,580,325 out=73,748,051 elapsed=296.0s

  [4407/13157] intraday_13097.csv.gz  in=262,595,885 out=73,763,611 elapsed=296.0s

  [4408/13157] intraday_13099.csv.gz  in=262,606,982 out=73,774,708 elapsed=296.0s

  [4409/13157] intraday_13100.csv.gz  in=262,620,128 out=73,787,854 elapsed=296.1s

  [4410/13157] intraday_13101.csv.gz  in=262,631,519 out=73,799,245 elapsed=296.1s

  [4411/13157] intraday_13102.csv.gz  in=262,647,077 out=73,814,803 elapsed=296.1s

  [4412/13157] intraday_13103.csv.gz  in=262,657,925 out=73,825,651 elapsed=296.1s

  [4413/13157] intraday_13104.csv.gz  in=262,671,380 out=73,839,106 elapsed=296.2s

  [4414/13157] intraday_1309.csv.gz  in=262,682,112 out=73,839,106 elapsed=296.2s

  [4415/13157] intraday_13105.csv.gz  in=262,695,563 out=73,852,557 elapsed=296.2s

  [4416/13157] intraday_13106.csv.gz  in=262,708,791 out=73,865,785 elapsed=296.2s

  [4417/13157] intraday_13108.csv.gz  in=262,721,123 out=73,878,117 elapsed=296.2s

  [4418/13157] intraday_13107.csv.gz  in=262,733,554 out=73,890,548 elapsed=296.2s

  [4419/13157] intraday_1310.csv.gz  in=262,745,201 out=73,890,548 elapsed=296.2s

  [4420/13157] intraday_13109.csv.gz  in=262,758,063 out=73,903,410 elapsed=296.2s

  [4421/13157] intraday_13110.csv.gz  in=262,770,316 out=73,915,663 elapsed=296.2s

  [4422/13157] intraday_13112.csv.gz  in=262,783,239 out=73,928,586 elapsed=296.3s

  [4423/13157] intraday_13111.csv.gz  in=262,795,878 out=73,941,225 elapsed=296.3s

  [4424/13157] intraday_13114.csv.gz  in=262,807,858 out=73,953,205 elapsed=296.3s

  [4425/13157] intraday_13113.csv.gz  in=262,819,522 out=73,964,869 elapsed=296.3s

  [4426/13157] intraday_13115.csv.gz  in=262,833,262 out=73,978,609 elapsed=296.3s

  [4427/13157] intraday_13116.csv.gz  in=262,845,721 out=73,991,068 elapsed=296.3s

  [4428/13157] intraday_13117.csv.gz  in=262,860,695 out=74,006,042 elapsed=296.3s

  [4429/13157] intraday_13118.csv.gz  in=262,873,227 out=74,018,574 elapsed=296.3s

  [4430/13157] intraday_13119.csv.gz  in=262,888,038 out=74,033,385 elapsed=296.3s

  [4431/13157] intraday_13121.csv.gz  in=262,901,166 out=74,046,513 elapsed=296.4s

  [4432/13157] intraday_13120.csv.gz  in=262,912,801 out=74,058,148 elapsed=296.4s

  [4433/13157] intraday_13122.csv.gz  in=262,925,635 out=74,070,982 elapsed=296.4s

  [4434/13157] intraday_13123.csv.gz  in=262,939,298 out=74,084,645 elapsed=296.4s

  [4435/13157] intraday_13124.csv.gz  in=262,950,168 out=74,095,515 elapsed=296.4s

  [4436/13157] intraday_13125.csv.gz  in=262,964,861 out=74,110,208 elapsed=296.4s

  [4437/13157] intraday_13126.csv.gz  in=262,980,405 out=74,125,752 elapsed=296.5s

  [4438/13157] intraday_13127.csv.gz  in=262,994,982 out=74,140,329 elapsed=296.5s

  [4439/13157] intraday_13128.csv.gz  in=263,010,888 out=74,156,235 elapsed=296.5s

  [4440/13157] intraday_13129.csv.gz  in=263,029,153 out=74,174,500 elapsed=296.5s

  [4441/13157] intraday_13130.csv.gz  in=263,044,839 out=74,190,186 elapsed=296.5s

  [4442/13157] intraday_13131.csv.gz  in=263,060,753 out=74,206,100 elapsed=296.5s

  [4443/13157] intraday_13132.csv.gz  in=263,075,262 out=74,220,609 elapsed=296.6s

  [4444/13157] intraday_13133.csv.gz  in=263,087,704 out=74,233,051 elapsed=296.6s

  [4445/13157] intraday_1311.csv.gz  in=263,099,154 out=74,233,051 elapsed=296.6s

  [4446/13157] intraday_1312.csv.gz  in=263,116,398 out=74,233,051 elapsed=296.6s

  [4447/13157] intraday_1313.csv.gz  in=263,127,694 out=74,233,051 elapsed=296.6s

  [4448/13157] intraday_13134.csv.gz  in=263,139,276 out=74,244,633 elapsed=296.6s

  [4449/13157] intraday_13135.csv.gz  in=263,150,508 out=74,255,865 elapsed=296.6s

  [4450/13157] intraday_13136.csv.gz  in=263,163,512 out=74,268,869 elapsed=296.7s

  [4451/13157] intraday_13137.csv.gz  in=263,174,365 out=74,279,722 elapsed=296.7s

  [4452/13157] intraday_13138.csv.gz  in=263,186,761 out=74,292,118 elapsed=296.7s

  [4453/13157] intraday_13139.csv.gz  in=263,199,632 out=74,304,989 elapsed=296.7s

  [4454/13157] intraday_1314.csv.gz  in=263,209,179 out=74,304,989 elapsed=296.7s

  [4455/13157] intraday_13140.csv.gz  in=263,228,144 out=74,323,954 elapsed=296.7s

  [4456/13157] intraday_13141.csv.gz  in=263,238,727 out=74,334,537 elapsed=296.7s

  [4457/13157] intraday_13142.csv.gz  in=263,250,351 out=74,346,161 elapsed=296.7s

  [4458/13157] intraday_13144.csv.gz  in=263,261,968 out=74,357,778 elapsed=296.7s

  [4459/13157] intraday_13145.csv.gz  in=263,275,152 out=74,370,962 elapsed=296.8s

  [4460/13157] intraday_13146.csv.gz  in=263,289,832 out=74,385,642 elapsed=296.8s

  [4461/13157] intraday_13143.csv.gz  in=263,302,326 out=74,398,136 elapsed=296.8s

  [4462/13157] intraday_13148.csv.gz  in=263,316,233 out=74,412,043 elapsed=296.8s

  [4463/13157] intraday_13147.csv.gz  in=263,331,805 out=74,427,615 elapsed=296.8s

  [4464/13157] intraday_13149.csv.gz  in=263,345,933 out=74,441,743 elapsed=296.8s

  [4465/13157] intraday_13150.csv.gz  in=263,358,367 out=74,454,177 elapsed=296.8s

  [4466/13157] intraday_1315.csv.gz  in=263,370,226 out=74,454,177 elapsed=296.8s

  [4467/13157] intraday_13151.csv.gz  in=263,383,016 out=74,466,967 elapsed=296.9s

  [4468/13157] intraday_13152.csv.gz  in=263,396,612 out=74,480,563 elapsed=296.9s

  [4469/13157] intraday_13154.csv.gz  in=263,405,909 out=74,489,860 elapsed=296.9s

  [4470/13157] intraday_13153.csv.gz  in=263,442,963 out=74,526,914 elapsed=296.9s

  [4471/13157] intraday_13155.csv.gz  in=263,450,946 out=74,534,897 elapsed=296.9s

  [4472/13157] intraday_13157.csv.gz  in=263,456,365 out=74,540,316 elapsed=296.9s

  [4473/13157] intraday_13156.csv.gz  in=263,471,788 out=74,555,739 elapsed=296.9s

  [4474/13157] intraday_1316.csv.gz  in=263,484,666 out=74,555,739 elapsed=297.0s

  [4475/13157] intraday_1318.csv.gz  in=263,498,660 out=74,555,739 elapsed=297.0s

  [4476/13157] intraday_1317.csv.gz  in=263,513,676 out=74,555,739 elapsed=297.0s

  [4477/13157] intraday_1319.csv.gz  in=263,526,565 out=74,555,739 elapsed=297.0s

  [4478/13157] intraday_1323.csv.gz  in=263,539,727 out=74,555,739 elapsed=297.0s

  [4479/13157] intraday_1321.csv.gz  in=263,553,599 out=74,555,739 elapsed=297.0s

  [4480/13157] intraday_1320.csv.gz  in=263,566,794 out=74,555,739 elapsed=297.0s

  [4481/13157] intraday_1322.csv.gz  in=263,580,333 out=74,555,739 elapsed=297.0s

  [4482/13157] intraday_1325.csv.gz  in=263,591,218 out=74,555,739 elapsed=297.1s

  [4483/13157] intraday_1324.csv.gz  in=263,604,597 out=74,555,739 elapsed=297.1s

  [4484/13157] intraday_1326.csv.gz  in=263,616,833 out=74,555,739 elapsed=297.1s

  [4485/13157] intraday_1327.csv.gz  in=263,630,017 out=74,555,739 elapsed=297.1s

  [4486/13157] intraday_1330.csv.gz  in=263,643,099 out=74,555,739 elapsed=297.1s

  [4487/13157] intraday_1328.csv.gz  in=263,656,755 out=74,555,739 elapsed=297.1s

  [4488/13157] intraday_1329.csv.gz  in=263,667,718 out=74,555,739 elapsed=297.1s

  [4489/13157] intraday_1331.csv.gz  in=263,686,761 out=74,555,739 elapsed=297.1s

  [4490/13157] intraday_1332.csv.gz  in=263,698,439 out=74,555,739 elapsed=297.2s

  [4491/13157] intraday_1333.csv.gz  in=263,713,616 out=74,555,739 elapsed=297.2s

  [4492/13157] intraday_1334.csv.gz  in=263,725,829 out=74,555,739 elapsed=297.2s

  [4493/13157] intraday_1335.csv.gz  in=263,737,855 out=74,555,739 elapsed=297.2s

  [4494/13157] intraday_1336.csv.gz  in=263,751,834 out=74,555,739 elapsed=297.2s

  [4495/13157] intraday_1337.csv.gz  in=263,766,702 out=74,555,739 elapsed=297.2s

  [4496/13157] intraday_1338.csv.gz  in=263,779,322 out=74,555,739 elapsed=297.2s

  [4497/13157] intraday_1339.csv.gz  in=263,793,564 out=74,555,739 elapsed=297.2s

  [4498/13157] intraday_1340.csv.gz  in=263,805,494 out=74,555,739 elapsed=297.3s

  [4499/13157] intraday_1342.csv.gz  in=263,816,992 out=74,555,739 elapsed=297.3s

  [4500/13157] intraday_1343.csv.gz  in=263,830,231 out=74,555,739 elapsed=297.3s

  [4501/13157] intraday_1345.csv.gz  in=263,844,575 out=74,555,739 elapsed=297.3s

  [4502/13157] intraday_1341.csv.gz  in=263,860,735 out=74,555,739 elapsed=297.3s

  [4503/13157] intraday_1344.csv.gz  in=263,875,991 out=74,555,739 elapsed=297.3s

  [4504/13157] intraday_1346.csv.gz  in=263,888,541 out=74,555,739 elapsed=297.4s

  [4505/13157] intraday_1348.csv.gz  in=263,899,419 out=74,555,739 elapsed=297.4s

  [4506/13157] intraday_1347.csv.gz  in=263,914,787 out=74,555,739 elapsed=297.4s

  [4507/13157] intraday_1349.csv.gz  in=263,927,069 out=74,555,739 elapsed=297.4s

  [4508/13157] intraday_1350.csv.gz  in=263,938,505 out=74,555,739 elapsed=297.4s

  [4509/13157] intraday_1351.csv.gz  in=263,953,731 out=74,555,739 elapsed=297.4s

  [4510/13157] intraday_1352.csv.gz  in=263,967,213 out=74,555,739 elapsed=297.4s

  [4511/13157] intraday_1353.csv.gz  in=263,983,539 out=74,555,739 elapsed=297.5s

  [4512/13157] intraday_1354.csv.gz  in=263,996,859 out=74,555,739 elapsed=297.5s

  [4513/13157] intraday_1355.csv.gz  in=264,009,364 out=74,555,739 elapsed=297.5s

  [4514/13157] intraday_1356.csv.gz  in=264,024,552 out=74,555,739 elapsed=297.5s

  [4515/13157] intraday_1357.csv.gz  in=264,037,932 out=74,555,739 elapsed=297.5s

  [4516/13157] intraday_1358.csv.gz  in=264,051,240 out=74,555,739 elapsed=297.5s

  [4517/13157] intraday_1359.csv.gz  in=264,066,976 out=74,555,739 elapsed=297.9s

  [4518/13157] intraday_1360.csv.gz  in=264,081,350 out=74,555,739 elapsed=297.9s

  [4519/13157] intraday_1361.csv.gz  in=264,095,795 out=74,555,739 elapsed=297.9s

  [4520/13157] intraday_1362.csv.gz  in=264,108,215 out=74,555,739 elapsed=298.1s

  [4521/13157] intraday_1363.csv.gz  in=264,118,845 out=74,555,739 elapsed=298.3s

  [4522/13157] intraday_1364.csv.gz  in=264,131,960 out=74,555,739 elapsed=298.3s

  [4523/13157] intraday_1365.csv.gz  in=264,143,504 out=74,555,739 elapsed=298.4s

  [4524/13157] intraday_1367.csv.gz  in=264,151,392 out=74,555,739 elapsed=298.4s

  [4525/13157] intraday_1370.csv.gz  in=264,151,444 out=74,555,739 elapsed=298.4s

  [4526/13157] intraday_1366.csv.gz  in=264,163,702 out=74,555,739 elapsed=298.5s

  [4527/13157] intraday_1369.csv.gz  in=264,171,224 out=74,555,739 elapsed=298.5s

  [4528/13157] intraday_1368.csv.gz  in=264,182,283 out=74,555,739 elapsed=298.5s

  [4529/13157] intraday_1373.csv.gz  in=264,182,329 out=74,555,739 elapsed=298.5s

  [4530/13157] intraday_1372.csv.gz  in=264,182,347 out=74,555,739 elapsed=298.5s

  [4531/13157] intraday_1374.csv.gz  in=264,182,351 out=74,555,739 elapsed=298.5s

  [4532/13157] intraday_1371.csv.gz  in=264,182,576 out=74,555,739 elapsed=298.5s

  [4533/13157] intraday_1375.csv.gz  in=264,182,638 out=74,555,739 elapsed=298.5s

  [4534/13157] intraday_1376.csv.gz  in=264,182,724 out=74,555,739 elapsed=298.5s

  [4535/13157] intraday_1377.csv.gz  in=264,183,608 out=74,555,739 elapsed=298.5s

  [4536/13157] intraday_1379.csv.gz  in=264,198,222 out=74,555,739 elapsed=298.5s

  [4537/13157] intraday_1381.csv.gz  in=264,213,128 out=74,555,739 elapsed=298.5s

  [4538/13157] intraday_1380.csv.gz  in=264,226,089 out=74,555,739 elapsed=298.5s

  [4539/13157] intraday_1378.csv.gz  in=264,242,471 out=74,555,739 elapsed=298.5s

  [4540/13157] intraday_1385.csv.gz  in=264,255,817 out=74,555,739 elapsed=298.6s

  [4541/13157] intraday_1384.csv.gz  in=264,269,293 out=74,555,739 elapsed=298.6s

  [4542/13157] intraday_1383.csv.gz  in=264,284,213 out=74,555,739 elapsed=298.6s

  [4543/13157] intraday_1382.csv.gz  in=264,298,763 out=74,555,739 elapsed=298.6s

  [4544/13157] intraday_1387.csv.gz  in=264,314,070 out=74,555,739 elapsed=298.6s

  [4545/13157] intraday_1389.csv.gz  in=264,326,893 out=74,555,739 elapsed=298.6s

  [4546/13157] intraday_1386.csv.gz  in=264,341,320 out=74,555,739 elapsed=298.7s

  [4547/13157] intraday_1388.csv.gz  in=264,351,710 out=74,555,739 elapsed=298.7s

  [4548/13157] intraday_1391.csv.gz  in=264,363,423 out=74,555,739 elapsed=298.7s

  [4549/13157] intraday_1392.csv.gz  in=264,374,374 out=74,555,739 elapsed=298.7s

  [4550/13157] intraday_1390.csv.gz  in=264,389,824 out=74,555,739 elapsed=298.7s

  [4551/13157] intraday_1393.csv.gz  in=264,404,088 out=74,555,739 elapsed=298.7s

  [4552/13157] intraday_1396.csv.gz  in=264,416,834 out=74,555,739 elapsed=298.8s

  [4553/13157] intraday_1394.csv.gz  in=264,430,033 out=74,555,739 elapsed=298.8s

  [4554/13157] intraday_1395.csv.gz  in=264,443,664 out=74,555,739 elapsed=298.8s

  [4555/13157] intraday_1397.csv.gz  in=264,455,386 out=74,555,739 elapsed=298.8s

  [4556/13157] intraday_1399.csv.gz  in=264,468,132 out=74,555,739 elapsed=298.8s

  [4557/13157] intraday_1398.csv.gz  in=264,482,037 out=74,555,739 elapsed=298.8s

  [4558/13157] intraday_1400.csv.gz  in=264,501,444 out=74,555,739 elapsed=298.8s

  [4559/13157] intraday_1401.csv.gz  in=264,515,200 out=74,555,739 elapsed=298.8s

  [4560/13157] intraday_1402.csv.gz  in=264,528,120 out=74,555,739 elapsed=299.0s

  [4561/13157] intraday_1403.csv.gz  in=264,539,205 out=74,555,739 elapsed=299.1s

  [4562/13157] intraday_1405.csv.gz  in=264,556,148 out=74,555,739 elapsed=299.2s

  [4563/13157] intraday_1404.csv.gz  in=264,571,420 out=74,555,739 elapsed=299.2s

  [4564/13157] intraday_1406.csv.gz  in=264,587,168 out=74,555,739 elapsed=299.5s

  [4565/13157] intraday_1407.csv.gz  in=264,602,290 out=74,555,739 elapsed=299.5s

  [4566/13157] intraday_1408.csv.gz  in=264,615,882 out=74,555,739 elapsed=299.5s

  [4567/13157] intraday_1409.csv.gz  in=264,628,542 out=74,555,739 elapsed=299.5s

  [4568/13157] intraday_1410.csv.gz  in=264,641,742 out=74,555,739 elapsed=299.8s

  [4569/13157] intraday_1412.csv.gz  in=264,653,746 out=74,555,739 elapsed=299.9s

  [4570/13157] intraday_1413.csv.gz  in=264,667,488 out=74,555,739 elapsed=299.9s

  [4571/13157] intraday_1411.csv.gz  in=264,681,323 out=74,555,739 elapsed=299.9s

  [4572/13157] intraday_1414.csv.gz  in=264,694,384 out=74,555,739 elapsed=299.9s

  [4573/13157] intraday_1416.csv.gz  in=264,706,204 out=74,555,739 elapsed=299.9s

  [4574/13157] intraday_1417.csv.gz  in=264,719,675 out=74,555,739 elapsed=299.9s

  [4575/13157] intraday_1415.csv.gz  in=264,731,854 out=74,555,739 elapsed=299.9s

  [4576/13157] intraday_1421.csv.gz  in=264,743,977 out=74,555,739 elapsed=300.0s

  [4577/13157] intraday_1419.csv.gz  in=264,757,873 out=74,555,739 elapsed=300.0s

  [4578/13157] intraday_1418.csv.gz  in=264,772,361 out=74,555,739 elapsed=300.0s

  [4579/13157] intraday_1420.csv.gz  in=264,788,490 out=74,555,739 elapsed=300.0s

  [4580/13157] intraday_1422.csv.gz  in=264,802,279 out=74,555,739 elapsed=300.1s

  [4581/13157] intraday_1424.csv.gz  in=264,815,752 out=74,555,739 elapsed=300.1s

  [4582/13157] intraday_1423.csv.gz  in=264,830,831 out=74,555,739 elapsed=300.1s

  [4583/13157] intraday_1425.csv.gz  in=264,844,351 out=74,555,739 elapsed=300.1s

  [4584/13157] intraday_1426.csv.gz  in=264,856,365 out=74,555,739 elapsed=300.1s

  [4585/13157] intraday_1427.csv.gz  in=264,867,580 out=74,555,739 elapsed=300.1s

  [4586/13157] intraday_1428.csv.gz  in=264,883,669 out=74,555,739 elapsed=300.2s

  [4587/13157] intraday_1429.csv.gz  in=264,903,579 out=74,555,739 elapsed=300.2s

  [4588/13157] intraday_1431.csv.gz  in=264,917,682 out=74,555,739 elapsed=300.2s

  [4589/13157] intraday_1430.csv.gz  in=264,929,824 out=74,555,739 elapsed=300.2s

  [4590/13157] intraday_1432.csv.gz  in=264,942,852 out=74,555,739 elapsed=300.2s

  [4591/13157] intraday_1433.csv.gz  in=264,954,494 out=74,555,739 elapsed=300.3s

  [4592/13157] intraday_1434.csv.gz  in=264,968,749 out=74,555,739 elapsed=300.4s

  [4593/13157] intraday_1435.csv.gz  in=264,982,503 out=74,555,739 elapsed=300.4s

  [4594/13157] intraday_1436.csv.gz  in=264,994,426 out=74,555,739 elapsed=300.5s

  [4595/13157] intraday_1438.csv.gz  in=265,007,336 out=74,555,739 elapsed=300.5s

  [4596/13157] intraday_1437.csv.gz  in=265,022,046 out=74,555,739 elapsed=300.5s

  [4597/13157] intraday_1439.csv.gz  in=265,032,053 out=74,555,739 elapsed=300.5s

  [4598/13157] intraday_1440.csv.gz  in=265,045,967 out=74,555,739 elapsed=300.5s

  [4599/13157] intraday_1443.csv.gz  in=265,060,926 out=74,555,739 elapsed=300.6s

  [4600/13157] intraday_1442.csv.gz  in=265,072,346 out=74,555,739 elapsed=300.6s

  [4601/13157] intraday_1441.csv.gz  in=265,086,884 out=74,555,739 elapsed=300.6s

  [4602/13157] intraday_1445.csv.gz  in=265,097,575 out=74,555,739 elapsed=300.6s

  [4603/13157] intraday_1446.csv.gz  in=265,110,195 out=74,555,739 elapsed=300.6s

  [4604/13157] intraday_1444.csv.gz  in=265,124,306 out=74,555,739 elapsed=300.6s

  [4605/13157] intraday_1447.csv.gz  in=265,137,272 out=74,555,739 elapsed=300.6s

  [4606/13157] intraday_1449.csv.gz  in=265,148,870 out=74,555,739 elapsed=300.7s

  [4607/13157] intraday_1448.csv.gz  in=265,162,895 out=74,555,739 elapsed=300.7s

  [4608/13157] intraday_1450.csv.gz  in=265,182,129 out=74,555,739 elapsed=300.8s

  [4609/13157] intraday_1451.csv.gz  in=265,194,496 out=74,555,739 elapsed=300.8s

  [4610/13157] intraday_1452.csv.gz  in=265,206,968 out=74,555,739 elapsed=300.8s

  [4611/13157] intraday_1453.csv.gz  in=265,219,471 out=74,555,739 elapsed=300.8s

  [4612/13157] intraday_1455.csv.gz  in=265,231,712 out=74,555,739 elapsed=301.0s

  [4613/13157] intraday_1454.csv.gz  in=265,244,456 out=74,555,739 elapsed=301.0s

  [4614/13157] intraday_1456.csv.gz  in=265,255,564 out=74,555,739 elapsed=301.0s

  [4615/13157] intraday_1457.csv.gz  in=265,268,127 out=74,555,739 elapsed=301.0s

  [4616/13157] intraday_1458.csv.gz  in=265,281,009 out=74,555,739 elapsed=301.1s

  [4617/13157] intraday_1460.csv.gz  in=265,292,886 out=74,555,739 elapsed=301.3s

  [4618/13157] intraday_1461.csv.gz  in=265,304,436 out=74,555,739 elapsed=301.3s

  [4619/13157] intraday_1462.csv.gz  in=265,316,668 out=74,555,739 elapsed=301.3s

  [4620/13157] intraday_1459.csv.gz  in=265,333,724 out=74,555,739 elapsed=301.3s

  [4621/13157] intraday_1463.csv.gz  in=265,346,910 out=74,555,739 elapsed=301.3s

  [4622/13157] intraday_1465.csv.gz  in=265,360,243 out=74,555,739 elapsed=301.3s

  [4623/13157] intraday_1466.csv.gz  in=265,374,592 out=74,555,739 elapsed=301.4s

  [4624/13157] intraday_1464.csv.gz  in=265,391,286 out=74,555,739 elapsed=301.4s

  [4625/13157] intraday_1467.csv.gz  in=265,406,604 out=74,555,739 elapsed=301.4s

  [4626/13157] intraday_1468.csv.gz  in=265,422,475 out=74,555,739 elapsed=301.4s

  [4627/13157] intraday_1469.csv.gz  in=265,437,072 out=74,555,739 elapsed=301.4s

  [4628/13157] intraday_1470.csv.gz  in=265,450,921 out=74,555,739 elapsed=301.4s

  [4629/13157] intraday_1471.csv.gz  in=265,464,769 out=74,555,739 elapsed=301.4s

  [4630/13157] intraday_1475.csv.gz  in=265,478,943 out=74,555,739 elapsed=301.6s

  [4631/13157] intraday_1473.csv.gz  in=265,490,590 out=74,555,739 elapsed=301.6s

  [4632/13157] intraday_1472.csv.gz  in=265,503,905 out=74,555,739 elapsed=301.6s

  [4633/13157] intraday_1474.csv.gz  in=265,516,421 out=74,555,739 elapsed=301.6s

  [4634/13157] intraday_1476.csv.gz  in=265,529,204 out=74,555,739 elapsed=301.8s

  [4635/13157] intraday_1477.csv.gz  in=265,543,219 out=74,555,739 elapsed=301.8s

  [4636/13157] intraday_1478.csv.gz  in=265,555,755 out=74,555,739 elapsed=301.8s

  [4637/13157] intraday_1479.csv.gz  in=265,568,713 out=74,555,739 elapsed=301.8s

  [4638/13157] intraday_1480.csv.gz  in=265,582,116 out=74,555,739 elapsed=301.9s

  [4639/13157] intraday_1481.csv.gz  in=265,595,114 out=74,555,739 elapsed=301.9s

  [4640/13157] intraday_1482.csv.gz  in=265,609,497 out=74,555,739 elapsed=301.9s

  [4641/13157] intraday_1483.csv.gz  in=265,624,551 out=74,555,739 elapsed=301.9s

  [4642/13157] intraday_1485.csv.gz  in=265,638,289 out=74,555,739 elapsed=302.0s

  [4643/13157] intraday_1487.csv.gz  in=265,651,255 out=74,555,739 elapsed=302.0s

  [4644/13157] intraday_1486.csv.gz  in=265,665,943 out=74,555,739 elapsed=302.0s

  [4645/13157] intraday_1484.csv.gz  in=265,680,528 out=74,555,739 elapsed=302.0s

  [4646/13157] intraday_1489.csv.gz  in=265,692,945 out=74,555,739 elapsed=302.0s

  [4647/13157] intraday_1490.csv.gz  in=265,707,358 out=74,555,739 elapsed=302.1s

  [4648/13157] intraday_1488.csv.gz  in=265,723,516 out=74,555,739 elapsed=302.1s

  [4649/13157] intraday_1491.csv.gz  in=265,739,988 out=74,555,739 elapsed=302.1s

  [4650/13157] intraday_1492.csv.gz  in=265,753,653 out=74,555,739 elapsed=302.1s

  [4651/13157] intraday_1494.csv.gz  in=265,769,320 out=74,555,739 elapsed=302.1s

  [4652/13157] intraday_1495.csv.gz  in=265,780,496 out=74,555,739 elapsed=302.1s

  [4653/13157] intraday_1493.csv.gz  in=265,794,530 out=74,555,739 elapsed=302.1s

  [4654/13157] intraday_1496.csv.gz  in=265,806,919 out=74,555,739 elapsed=302.1s

  [4655/13157] intraday_1498.csv.gz  in=265,822,197 out=74,555,739 elapsed=302.2s

  [4656/13157] intraday_1499.csv.gz  in=265,838,370 out=74,555,739 elapsed=302.2s

  [4657/13157] intraday_1497.csv.gz  in=265,862,964 out=74,555,739 elapsed=302.2s

  [4658/13157] intraday_1500.csv.gz  in=265,877,824 out=74,555,739 elapsed=302.2s

  [4659/13157] intraday_1501.csv.gz  in=265,892,910 out=74,555,739 elapsed=302.3s

  [4660/13157] intraday_1502.csv.gz  in=265,908,014 out=74,555,739 elapsed=302.3s

  [4661/13157] intraday_1504.csv.gz  in=265,921,985 out=74,555,739 elapsed=302.3s

  [4662/13157] intraday_1503.csv.gz  in=265,937,035 out=74,555,739 elapsed=302.3s

  [4663/13157] intraday_1505.csv.gz  in=265,953,550 out=74,555,739 elapsed=302.3s

  [4664/13157] intraday_1506.csv.gz  in=265,969,808 out=74,555,739 elapsed=302.3s

  [4665/13157] intraday_1507.csv.gz  in=265,983,162 out=74,555,739 elapsed=302.3s

  [4666/13157] intraday_1509.csv.gz  in=265,994,881 out=74,555,739 elapsed=302.4s

  [4667/13157] intraday_1510.csv.gz  in=266,006,280 out=74,555,739 elapsed=302.4s

  [4668/13157] intraday_1513.csv.gz  in=266,017,160 out=74,555,739 elapsed=302.5s

  [4669/13157] intraday_1508.csv.gz  in=266,032,664 out=74,555,739 elapsed=302.5s

  [4670/13157] intraday_1512.csv.gz  in=266,045,321 out=74,555,739 elapsed=302.5s

  [4671/13157] intraday_1511.csv.gz  in=266,059,954 out=74,555,739 elapsed=302.5s

  [4672/13157] intraday_1514.csv.gz  in=266,068,801 out=74,555,739 elapsed=302.6s

  [4673/13157] intraday_1516.csv.gz  in=266,074,867 out=74,555,739 elapsed=302.6s

  [4674/13157] intraday_1515.csv.gz  in=266,085,726 out=74,555,739 elapsed=302.6s

  [4675/13157] intraday_1517.csv.gz  in=266,100,978 out=74,555,739 elapsed=302.6s

  [4676/13157] intraday_1518.csv.gz  in=266,115,092 out=74,555,739 elapsed=302.6s

  [4677/13157] intraday_1521.csv.gz  in=266,128,703 out=74,555,739 elapsed=302.7s

  [4678/13157] intraday_1520.csv.gz  in=266,140,796 out=74,555,739 elapsed=302.7s

  [4679/13157] intraday_1519.csv.gz  in=266,152,727 out=74,555,739 elapsed=302.7s

  [4680/13157] intraday_1522.csv.gz  in=266,166,306 out=74,555,739 elapsed=302.7s

  [4681/13157] intraday_1523.csv.gz  in=266,178,830 out=74,555,739 elapsed=302.7s

  [4682/13157] intraday_1524.csv.gz  in=266,191,223 out=74,555,739 elapsed=302.8s

  [4683/13157] intraday_1525.csv.gz  in=266,204,704 out=74,555,739 elapsed=302.8s

  [4684/13157] intraday_1527.csv.gz  in=266,213,742 out=74,555,739 elapsed=302.8s

  [4685/13157] intraday_1528.csv.gz  in=266,225,500 out=74,555,739 elapsed=302.8s

  [4686/13157] intraday_1526.csv.gz  in=266,239,458 out=74,555,739 elapsed=302.8s

  [4687/13157] intraday_1529.csv.gz  in=266,253,680 out=74,555,739 elapsed=302.8s

  [4688/13157] intraday_1530.csv.gz  in=266,264,545 out=74,555,739 elapsed=302.8s

  [4689/13157] intraday_1531.csv.gz  in=266,274,369 out=74,555,739 elapsed=302.9s

  [4690/13157] intraday_1533.csv.gz  in=266,285,822 out=74,555,739 elapsed=302.9s

  [4691/13157] intraday_1532.csv.gz  in=266,299,526 out=74,555,739 elapsed=302.9s

  [4692/13157] intraday_1534.csv.gz  in=266,311,730 out=74,555,739 elapsed=302.9s

  [4693/13157] intraday_1536.csv.gz  in=266,323,155 out=74,555,739 elapsed=302.9s

  [4694/13157] intraday_1535.csv.gz  in=266,335,011 out=74,555,739 elapsed=302.9s

  [4695/13157] intraday_1537.csv.gz  in=266,347,045 out=74,555,739 elapsed=302.9s

  [4696/13157] intraday_1538.csv.gz  in=266,358,915 out=74,555,739 elapsed=303.0s

  [4697/13157] intraday_1539.csv.gz  in=266,371,092 out=74,555,739 elapsed=303.0s

  [4698/13157] intraday_1540.csv.gz  in=266,385,177 out=74,555,739 elapsed=303.0s

  [4699/13157] intraday_1541.csv.gz  in=266,396,003 out=74,555,739 elapsed=303.0s

  [4700/13157] intraday_1542.csv.gz  in=266,406,293 out=74,555,739 elapsed=303.0s

  [4701/13157] intraday_1543.csv.gz  in=266,419,944 out=74,555,739 elapsed=303.2s

  [4702/13157] intraday_1544.csv.gz  in=266,433,058 out=74,555,739 elapsed=303.2s

  [4703/13157] intraday_1546.csv.gz  in=266,447,407 out=74,555,739 elapsed=303.2s

  [4704/13157] intraday_1545.csv.gz  in=266,462,233 out=74,555,739 elapsed=303.2s

  [4705/13157] intraday_1548.csv.gz  in=266,474,269 out=74,555,739 elapsed=303.3s

  [4706/13157] intraday_1549.csv.gz  in=266,485,867 out=74,555,739 elapsed=303.3s

  [4707/13157] intraday_1547.csv.gz  in=266,497,794 out=74,555,739 elapsed=303.3s

  [4708/13157] intraday_1553.csv.gz  in=266,509,607 out=74,555,739 elapsed=303.5s

  [4709/13157] intraday_1551.csv.gz  in=266,520,520 out=74,555,739 elapsed=303.5s

  [4710/13157] intraday_1552.csv.gz  in=266,532,991 out=74,555,739 elapsed=303.5s

  [4711/13157] intraday_1556.csv.gz  in=266,545,002 out=74,555,739 elapsed=303.6s

  [4712/13157] intraday_1555.csv.gz  in=266,557,817 out=74,555,739 elapsed=303.6s

  [4713/13157] intraday_1554.csv.gz  in=266,569,615 out=74,555,739 elapsed=303.6s

  [4714/13157] intraday_1550.csv.gz  in=266,603,838 out=74,555,739 elapsed=303.6s

  [4715/13157] intraday_1557.csv.gz  in=266,616,835 out=74,555,739 elapsed=303.6s

  [4716/13157] intraday_1558.csv.gz  in=266,629,425 out=74,555,739 elapsed=303.6s

  [4717/13157] intraday_1560.csv.gz  in=266,640,573 out=74,555,739 elapsed=303.7s

  [4718/13157] intraday_1562.csv.gz  in=266,651,209 out=74,555,739 elapsed=303.7s

  [4719/13157] intraday_1561.csv.gz  in=266,665,044 out=74,555,739 elapsed=303.7s

  [4720/13157] intraday_1559.csv.gz  in=266,680,147 out=74,555,739 elapsed=303.7s

  [4721/13157] intraday_1563.csv.gz  in=266,692,196 out=74,555,739 elapsed=303.7s

  [4722/13157] intraday_1565.csv.gz  in=266,702,476 out=74,555,739 elapsed=303.8s

  [4723/13157] intraday_1564.csv.gz  in=266,715,083 out=74,555,739 elapsed=303.8s

  [4724/13157] intraday_1566.csv.gz  in=266,728,432 out=74,555,739 elapsed=303.8s

  [4725/13157] intraday_1569.csv.gz  in=266,740,121 out=74,555,739 elapsed=303.8s

  [4726/13157] intraday_1568.csv.gz  in=266,752,176 out=74,555,739 elapsed=303.8s

  [4727/13157] intraday_1567.csv.gz  in=266,767,362 out=74,555,739 elapsed=303.8s

  [4728/13157] intraday_1570.csv.gz  in=266,780,069 out=74,555,739 elapsed=303.8s

  [4729/13157] intraday_1571.csv.gz  in=266,792,552 out=74,555,739 elapsed=303.9s

  [4730/13157] intraday_1572.csv.gz  in=266,804,082 out=74,555,739 elapsed=303.9s

  [4731/13157] intraday_1573.csv.gz  in=266,816,924 out=74,555,739 elapsed=303.9s

  [4732/13157] intraday_1574.csv.gz  in=266,829,796 out=74,555,739 elapsed=303.9s

  [4733/13157] intraday_1578.csv.gz  in=266,839,209 out=74,555,739 elapsed=304.0s

  [4734/13157] intraday_1576.csv.gz  in=266,851,875 out=74,555,739 elapsed=304.0s

  [4735/13157] intraday_1577.csv.gz  in=266,864,192 out=74,555,739 elapsed=304.0s

  [4736/13157] intraday_1575.csv.gz  in=266,891,127 out=74,555,739 elapsed=304.0s

  [4737/13157] intraday_1579.csv.gz  in=266,903,358 out=74,555,739 elapsed=304.0s

  [4738/13157] intraday_1580.csv.gz  in=266,916,964 out=74,555,739 elapsed=304.0s

  [4739/13157] intraday_1581.csv.gz  in=266,927,526 out=74,555,739 elapsed=304.1s

  [4740/13157] intraday_1582.csv.gz  in=266,941,520 out=74,555,739 elapsed=304.1s

  [4741/13157] intraday_1586.csv.gz  in=266,953,891 out=74,555,739 elapsed=304.2s

  [4742/13157] intraday_1584.csv.gz  in=266,967,807 out=74,555,739 elapsed=304.2s

  [4743/13157] intraday_1585.csv.gz  in=266,978,976 out=74,555,739 elapsed=304.2s

  [4744/13157] intraday_1583.csv.gz  in=266,992,638 out=74,555,739 elapsed=304.2s

  [4745/13157] intraday_1588.csv.gz  in=267,004,032 out=74,555,739 elapsed=304.2s

  [4746/13157] intraday_1589.csv.gz  in=267,015,554 out=74,555,739 elapsed=304.2s

  [4747/13157] intraday_1587.csv.gz  in=267,028,160 out=74,555,739 elapsed=304.2s

  [4748/13157] intraday_1590.csv.gz  in=267,039,656 out=74,555,739 elapsed=304.2s

  [4749/13157] intraday_1592.csv.gz  in=267,051,093 out=74,555,739 elapsed=304.2s

  [4750/13157] intraday_1591.csv.gz  in=267,063,113 out=74,555,739 elapsed=304.2s

  [4751/13157] intraday_1593.csv.gz  in=267,075,032 out=74,555,739 elapsed=304.2s

  [4752/13157] intraday_1594.csv.gz  in=267,086,267 out=74,555,739 elapsed=304.2s

  [4753/13157] intraday_1595.csv.gz  in=267,096,416 out=74,555,739 elapsed=304.3s

  [4754/13157] intraday_1596.csv.gz  in=267,108,165 out=74,555,739 elapsed=304.3s

  [4755/13157] intraday_1597.csv.gz  in=267,120,296 out=74,555,739 elapsed=304.3s

  [4756/13157] intraday_1598.csv.gz  in=267,135,886 out=74,555,739 elapsed=304.3s

  [4757/13157] intraday_1600.csv.gz  in=267,145,971 out=74,555,739 elapsed=304.3s

  [4758/13157] intraday_1601.csv.gz  in=267,157,338 out=74,555,739 elapsed=304.4s

  [4759/13157] intraday_1602.csv.gz  in=267,169,623 out=74,555,739 elapsed=304.4s

  [4760/13157] intraday_1599.csv.gz  in=267,195,405 out=74,555,739 elapsed=304.4s

  [4761/13157] intraday_1605.csv.gz  in=267,209,187 out=74,555,739 elapsed=304.8s

  [4762/13157] intraday_1603.csv.gz  in=267,224,413 out=74,555,739 elapsed=304.8s

  [4763/13157] intraday_1604.csv.gz  in=267,236,815 out=74,555,739 elapsed=304.8s

  [4764/13157] intraday_1606.csv.gz  in=267,249,800 out=74,555,739 elapsed=305.0s

  [4765/13157] intraday_1607.csv.gz  in=267,264,013 out=74,555,739 elapsed=305.7s

  [4766/13157] intraday_1609.csv.gz  in=267,277,130 out=74,555,739 elapsed=306.0s

  [4767/13157] intraday_1610.csv.gz  in=267,290,029 out=74,555,739 elapsed=306.0s

  [4768/13157] intraday_1608.csv.gz  in=267,304,090 out=74,555,739 elapsed=306.0s

  [4769/13157] intraday_1611.csv.gz  in=267,315,754 out=74,555,739 elapsed=306.0s

  [4770/13157] intraday_1612.csv.gz  in=267,326,856 out=74,555,739 elapsed=306.1s

  [4771/13157] intraday_1613.csv.gz  in=267,342,166 out=74,555,739 elapsed=306.1s

  [4772/13157] intraday_1614.csv.gz  in=267,356,458 out=74,555,739 elapsed=306.1s

  [4773/13157] intraday_1615.csv.gz  in=267,367,835 out=74,555,739 elapsed=306.1s

  [4774/13157] intraday_1616.csv.gz  in=267,380,126 out=74,555,739 elapsed=306.3s

  [4775/13157] intraday_1619.csv.gz  in=267,392,568 out=74,555,739 elapsed=306.3s

  [4776/13157] intraday_1618.csv.gz  in=267,404,735 out=74,555,739 elapsed=306.3s

  [4777/13157] intraday_1617.csv.gz  in=267,416,981 out=74,555,739 elapsed=306.3s

  [4778/13157] intraday_1622.csv.gz  in=267,429,975 out=74,555,739 elapsed=306.5s

  [4779/13157] intraday_1620.csv.gz  in=267,442,221 out=74,555,739 elapsed=306.5s

  [4780/13157] intraday_1621.csv.gz  in=267,455,388 out=74,555,739 elapsed=306.5s

  [4781/13157] intraday_1623.csv.gz  in=267,470,058 out=74,555,739 elapsed=306.5s

  [4782/13157] intraday_1626.csv.gz  in=267,483,654 out=74,555,739 elapsed=306.8s

  [4783/13157] intraday_1625.csv.gz  in=267,497,929 out=74,555,739 elapsed=306.8s

  [4784/13157] intraday_1624.csv.gz  in=267,509,379 out=74,555,739 elapsed=306.8s

  [4785/13157] intraday_1629.csv.gz  in=267,522,786 out=74,555,739 elapsed=307.0s

  [4786/13157] intraday_1628.csv.gz  in=267,534,014 out=74,555,739 elapsed=307.0s

  [4787/13157] intraday_1627.csv.gz  in=267,551,403 out=74,555,739 elapsed=307.0s

  [4788/13157] intraday_1630.csv.gz  in=267,567,392 out=74,555,739 elapsed=307.1s

  [4789/13157] intraday_1632.csv.gz  in=267,580,435 out=74,555,739 elapsed=307.4s

  [4790/13157] intraday_1631.csv.gz  in=267,593,174 out=74,555,739 elapsed=307.6s

  [4791/13157] intraday_1633.csv.gz  in=267,608,047 out=74,555,739 elapsed=307.9s

  [4792/13157] intraday_1634.csv.gz  in=267,618,688 out=74,555,739 elapsed=307.9s

  [4793/13157] intraday_1635.csv.gz  in=267,630,611 out=74,555,739 elapsed=307.9s

  [4794/13157] intraday_1636.csv.gz  in=267,643,157 out=74,555,739 elapsed=308.1s

  [4795/13157] intraday_1637.csv.gz  in=267,657,357 out=74,555,739 elapsed=308.2s

  [4796/13157] intraday_1639.csv.gz  in=267,670,585 out=74,555,739 elapsed=308.3s

  [4797/13157] intraday_1640.csv.gz  in=267,684,525 out=74,555,739 elapsed=308.4s

  [4798/13157] intraday_1642.csv.gz  in=267,697,699 out=74,555,739 elapsed=308.4s

  [4799/13157] intraday_1638.csv.gz  in=267,713,280 out=74,555,739 elapsed=308.4s

  [4800/13157] intraday_1641.csv.gz  in=267,727,380 out=74,555,739 elapsed=308.4s

  [4801/13157] intraday_1643.csv.gz  in=267,739,784 out=74,555,739 elapsed=308.7s

  [4802/13157] intraday_1646.csv.gz  in=267,752,091 out=74,555,739 elapsed=308.7s

  [4803/13157] intraday_1645.csv.gz  in=267,767,524 out=74,555,739 elapsed=308.7s

  [4804/13157] intraday_1644.csv.gz  in=267,783,582 out=74,555,739 elapsed=308.7s

  [4805/13157] intraday_1650.csv.gz  in=267,795,779 out=74,555,739 elapsed=308.8s

  [4806/13157] intraday_1647.csv.gz  in=267,810,719 out=74,555,739 elapsed=308.8s

  [4807/13157] intraday_1648.csv.gz  in=267,821,611 out=74,555,739 elapsed=308.8s

  [4808/13157] intraday_1649.csv.gz  in=267,833,077 out=74,555,739 elapsed=308.8s

  [4809/13157] intraday_1653.csv.gz  in=267,841,391 out=74,555,739 elapsed=308.9s

  [4810/13157] intraday_1654.csv.gz  in=267,852,348 out=74,555,739 elapsed=308.9s

  [4811/13157] intraday_1652.csv.gz  in=267,862,044 out=74,555,739 elapsed=308.9s

  [4812/13157] intraday_1651.csv.gz  in=267,873,673 out=74,555,739 elapsed=308.9s

  [4813/13157] intraday_1655.csv.gz  in=267,877,753 out=74,555,739 elapsed=309.0s

  [4814/13157] intraday_1657.csv.gz  in=267,891,884 out=74,555,739 elapsed=309.0s

  [4815/13157] intraday_1656.csv.gz  in=267,906,336 out=74,555,739 elapsed=309.0s

  [4816/13157] intraday_1658.csv.gz  in=267,918,202 out=74,555,739 elapsed=309.0s

  [4817/13157] intraday_1659.csv.gz  in=267,929,493 out=74,555,739 elapsed=309.0s

  [4818/13157] intraday_1663.csv.gz  in=267,941,548 out=74,555,739 elapsed=309.0s

  [4819/13157] intraday_1660.csv.gz  in=267,955,100 out=74,555,739 elapsed=309.1s

  [4820/13157] intraday_1661.csv.gz  in=267,968,811 out=74,555,739 elapsed=309.1s

  [4821/13157] intraday_1662.csv.gz  in=267,981,168 out=74,555,739 elapsed=309.1s

  [4822/13157] intraday_1666.csv.gz  in=267,990,458 out=74,555,739 elapsed=309.1s

  [4823/13157] intraday_1664.csv.gz  in=268,004,323 out=74,555,739 elapsed=309.1s

  [4824/13157] intraday_1667.csv.gz  in=268,016,039 out=74,555,739 elapsed=309.1s

  [4825/13157] intraday_1665.csv.gz  in=268,030,251 out=74,555,739 elapsed=309.1s

  [4826/13157] intraday_1669.csv.gz  in=268,041,101 out=74,555,739 elapsed=309.2s

  [4827/13157] intraday_1671.csv.gz  in=268,054,660 out=74,555,739 elapsed=309.2s

  [4828/13157] intraday_1668.csv.gz  in=268,073,715 out=74,555,739 elapsed=309.2s

  [4829/13157] intraday_1670.csv.gz  in=268,083,319 out=74,555,739 elapsed=309.2s

  [4830/13157] intraday_1673.csv.gz  in=268,095,440 out=74,555,739 elapsed=309.3s

  [4831/13157] intraday_1672.csv.gz  in=268,106,820 out=74,555,739 elapsed=309.3s

  [4832/13157] intraday_1675.csv.gz  in=268,118,702 out=74,555,739 elapsed=309.3s

  [4833/13157] intraday_1674.csv.gz  in=268,130,348 out=74,555,739 elapsed=309.3s

  [4834/13157] intraday_1676.csv.gz  in=268,143,679 out=74,555,739 elapsed=309.4s

  [4835/13157] intraday_1677.csv.gz  in=268,155,430 out=74,555,739 elapsed=309.4s

  [4836/13157] intraday_1678.csv.gz  in=268,168,084 out=74,555,739 elapsed=309.4s

  [4837/13157] intraday_1680.csv.gz  in=268,179,214 out=74,555,739 elapsed=309.4s

  [4838/13157] intraday_1679.csv.gz  in=268,202,577 out=74,555,739 elapsed=309.4s

  [4839/13157] intraday_1681.csv.gz  in=268,212,387 out=74,555,739 elapsed=309.5s

  [4840/13157] intraday_1682.csv.gz  in=268,225,107 out=74,555,739 elapsed=309.5s

  [4841/13157] intraday_1683.csv.gz  in=268,237,650 out=74,555,739 elapsed=309.5s

  [4842/13157] intraday_1684.csv.gz  in=268,257,649 out=74,555,739 elapsed=309.6s

  [4843/13157] intraday_1686.csv.gz  in=268,269,296 out=74,555,739 elapsed=309.6s

  [4844/13157] intraday_1685.csv.gz  in=268,282,998 out=74,555,739 elapsed=309.6s

  [4845/13157] intraday_1688.csv.gz  in=268,294,467 out=74,555,739 elapsed=309.8s

  [4846/13157] intraday_1689.csv.gz  in=268,307,367 out=74,555,739 elapsed=309.8s

  [4847/13157] intraday_1690.csv.gz  in=268,317,917 out=74,555,739 elapsed=309.8s

  [4848/13157] intraday_1687.csv.gz  in=268,338,007 out=74,555,739 elapsed=309.8s

  [4849/13157] intraday_1691.csv.gz  in=268,350,829 out=74,555,739 elapsed=310.1s

  [4850/13157] intraday_1693.csv.gz  in=268,361,660 out=74,555,739 elapsed=310.1s

  [4851/13157] intraday_1692.csv.gz  in=268,373,731 out=74,555,739 elapsed=310.2s

  [4852/13157] intraday_1694.csv.gz  in=268,397,000 out=74,555,739 elapsed=310.2s

  [4853/13157] intraday_1697.csv.gz  in=268,408,986 out=74,555,739 elapsed=310.2s

  [4854/13157] intraday_1696.csv.gz  in=268,421,870 out=74,555,739 elapsed=310.2s

  [4855/13157] intraday_1695.csv.gz  in=268,436,970 out=74,555,739 elapsed=310.2s

  [4856/13157] intraday_1698.csv.gz  in=268,452,093 out=74,555,739 elapsed=310.2s

  [4857/13157] intraday_1699.csv.gz  in=268,464,102 out=74,555,739 elapsed=310.3s

  [4858/13157] intraday_1701.csv.gz  in=268,475,293 out=74,555,739 elapsed=310.3s

  [4859/13157] intraday_1702.csv.gz  in=268,487,458 out=74,555,739 elapsed=310.3s

  [4860/13157] intraday_1703.csv.gz  in=268,499,488 out=74,555,739 elapsed=310.3s

  [4861/13157] intraday_1700.csv.gz  in=268,526,129 out=74,555,739 elapsed=310.3s

  [4862/13157] intraday_1704.csv.gz  in=268,536,566 out=74,555,739 elapsed=310.3s

  [4863/13157] intraday_1705.csv.gz  in=268,546,179 out=74,555,739 elapsed=310.3s

  [4864/13157] intraday_1706.csv.gz  in=268,561,033 out=74,555,739 elapsed=310.3s

  [4865/13157] intraday_1707.csv.gz  in=268,572,191 out=74,555,739 elapsed=310.3s

  [4866/13157] intraday_1708.csv.gz  in=268,583,644 out=74,555,739 elapsed=310.4s

  [4867/13157] intraday_1709.csv.gz  in=268,595,477 out=74,555,739 elapsed=310.4s

  [4868/13157] intraday_1710.csv.gz  in=268,608,162 out=74,555,739 elapsed=310.4s

  [4869/13157] intraday_1711.csv.gz  in=268,627,587 out=74,555,739 elapsed=310.4s

  [4870/13157] intraday_1712.csv.gz  in=268,639,499 out=74,555,739 elapsed=310.5s

  [4871/13157] intraday_1714.csv.gz  in=268,650,435 out=74,555,739 elapsed=310.5s

  [4872/13157] intraday_1713.csv.gz  in=268,663,386 out=74,555,739 elapsed=310.5s

  [4873/13157] intraday_1715.csv.gz  in=268,676,644 out=74,555,739 elapsed=310.5s

  [4874/13157] intraday_1717.csv.gz  in=268,687,022 out=74,555,739 elapsed=310.5s

  [4875/13157] intraday_1716.csv.gz  in=268,698,298 out=74,555,739 elapsed=310.5s

  [4876/13157] intraday_1718.csv.gz  in=268,713,798 out=74,555,739 elapsed=310.5s

  [4877/13157] intraday_1719.csv.gz  in=268,726,937 out=74,555,739 elapsed=310.5s

  [4878/13157] intraday_1720.csv.gz  in=268,739,511 out=74,555,739 elapsed=310.6s

  [4879/13157] intraday_1723.csv.gz  in=268,748,657 out=74,555,739 elapsed=310.6s

  [4880/13157] intraday_1724.csv.gz  in=268,760,759 out=74,555,739 elapsed=310.6s

  [4881/13157] intraday_1722.csv.gz  in=268,773,995 out=74,555,739 elapsed=310.6s

  [4882/13157] intraday_1721.csv.gz  in=268,788,210 out=74,555,739 elapsed=310.6s

  [4883/13157] intraday_1725.csv.gz  in=268,800,196 out=74,555,739 elapsed=310.7s

  [4884/13157] intraday_1726.csv.gz  in=268,812,742 out=74,555,739 elapsed=310.7s

  [4885/13157] intraday_1728.csv.gz  in=268,823,438 out=74,555,739 elapsed=310.7s

  [4886/13157] intraday_1727.csv.gz  in=268,835,335 out=74,555,739 elapsed=310.7s

  [4887/13157] intraday_1729.csv.gz  in=268,847,451 out=74,555,739 elapsed=310.9s

  [4888/13157] intraday_1732.csv.gz  in=268,859,554 out=74,555,739 elapsed=310.9s

  [4889/13157] intraday_1730.csv.gz  in=268,870,830 out=74,555,739 elapsed=310.9s

  [4890/13157] intraday_1731.csv.gz  in=268,882,234 out=74,555,739 elapsed=310.9s

  [4891/13157] intraday_1734.csv.gz  in=268,892,324 out=74,555,739 elapsed=310.9s

  [4892/13157] intraday_1736.csv.gz  in=268,903,924 out=74,555,739 elapsed=311.0s

  [4893/13157] intraday_1735.csv.gz  in=268,915,130 out=74,555,739 elapsed=311.0s

  [4894/13157] intraday_1733.csv.gz  in=268,928,117 out=74,555,739 elapsed=311.0s

  [4895/13157] intraday_1739.csv.gz  in=268,937,690 out=74,555,739 elapsed=311.1s

  [4896/13157] intraday_1740.csv.gz  in=268,948,507 out=74,555,739 elapsed=311.1s

  [4897/13157] intraday_1738.csv.gz  in=268,959,559 out=74,555,739 elapsed=311.1s

  [4898/13157] intraday_1737.csv.gz  in=268,975,288 out=74,555,739 elapsed=311.1s

  [4899/13157] intraday_1741.csv.gz  in=268,987,808 out=74,555,739 elapsed=311.2s

  [4900/13157] intraday_1743.csv.gz  in=269,001,401 out=74,555,739 elapsed=311.2s

  [4901/13157] intraday_1744.csv.gz  in=269,014,199 out=74,555,739 elapsed=311.3s

  [4902/13157] intraday_1745.csv.gz  in=269,027,134 out=74,555,739 elapsed=311.3s

  [4903/13157] intraday_1742.csv.gz  in=269,043,814 out=74,555,739 elapsed=311.3s

  [4904/13157] intraday_1746.csv.gz  in=269,057,646 out=74,555,739 elapsed=311.3s

  [4905/13157] intraday_1748.csv.gz  in=269,071,638 out=74,555,739 elapsed=311.3s

  [4906/13157] intraday_1747.csv.gz  in=269,085,274 out=74,555,739 elapsed=311.3s

  [4907/13157] intraday_1749.csv.gz  in=269,104,587 out=74,555,739 elapsed=311.3s

  [4908/13157] intraday_1751.csv.gz  in=269,116,147 out=74,555,739 elapsed=311.3s

  [4909/13157] intraday_1750.csv.gz  in=269,126,670 out=74,555,739 elapsed=311.3s

  [4910/13157] intraday_1752.csv.gz  in=269,138,103 out=74,555,739 elapsed=311.3s

  [4911/13157] intraday_1754.csv.gz  in=269,148,701 out=74,555,739 elapsed=311.4s

  [4912/13157] intraday_1753.csv.gz  in=269,162,349 out=74,555,739 elapsed=311.4s

  [4913/13157] intraday_1756.csv.gz  in=269,174,207 out=74,555,739 elapsed=311.4s

  [4914/13157] intraday_1757.csv.gz  in=269,185,603 out=74,555,739 elapsed=311.4s

  [4915/13157] intraday_1755.csv.gz  in=269,198,156 out=74,555,739 elapsed=311.4s

  [4916/13157] intraday_1758.csv.gz  in=269,212,827 out=74,555,739 elapsed=311.4s

  [4917/13157] intraday_1759.csv.gz  in=269,224,051 out=74,555,739 elapsed=311.5s

  [4918/13157] intraday_1760.csv.gz  in=269,241,258 out=74,555,739 elapsed=311.5s

  [4919/13157] intraday_1762.csv.gz  in=269,254,757 out=74,555,739 elapsed=311.5s

  [4920/13157] intraday_1761.csv.gz  in=269,268,760 out=74,555,739 elapsed=311.5s

  [4921/13157] intraday_1763.csv.gz  in=269,303,362 out=74,555,739 elapsed=311.5s

  [4922/13157] intraday_1765.csv.gz  in=269,315,601 out=74,555,739 elapsed=311.5s

  [4923/13157] intraday_1764.csv.gz  in=269,329,454 out=74,555,739 elapsed=311.5s

  [4924/13157] intraday_1766.csv.gz  in=269,342,387 out=74,555,739 elapsed=311.5s

  [4925/13157] intraday_1767.csv.gz  in=269,353,175 out=74,555,739 elapsed=311.5s

  [4926/13157] intraday_1768.csv.gz  in=269,366,490 out=74,555,739 elapsed=311.6s

  [4927/13157] intraday_1771.csv.gz  in=269,378,902 out=74,555,739 elapsed=311.6s

  [4928/13157] intraday_1770.csv.gz  in=269,397,023 out=74,555,739 elapsed=311.6s

  [4929/13157] intraday_1769.csv.gz  in=269,409,352 out=74,555,739 elapsed=311.6s

  [4930/13157] intraday_1772.csv.gz  in=269,422,326 out=74,555,739 elapsed=311.7s

  [4931/13157] intraday_1773.csv.gz  in=269,434,475 out=74,555,739 elapsed=311.7s

  [4932/13157] intraday_1775.csv.gz  in=269,444,832 out=74,555,739 elapsed=311.7s

  [4933/13157] intraday_1774.csv.gz  in=269,457,819 out=74,555,739 elapsed=311.7s

  [4934/13157] intraday_1777.csv.gz  in=269,471,760 out=74,555,739 elapsed=311.7s

  [4935/13157] intraday_1779.csv.gz  in=269,491,640 out=74,555,739 elapsed=311.7s

  [4936/13157] intraday_1778.csv.gz  in=269,507,060 out=74,555,739 elapsed=311.7s

  [4937/13157] intraday_1776.csv.gz  in=269,523,873 out=74,555,739 elapsed=311.7s

  [4938/13157] intraday_1780.csv.gz  in=269,537,742 out=74,555,739 elapsed=311.7s

  [4939/13157] intraday_1781.csv.gz  in=269,551,197 out=74,555,739 elapsed=311.7s

  [4940/13157] intraday_1783.csv.gz  in=269,564,411 out=74,555,739 elapsed=311.8s

  [4941/13157] intraday_1782.csv.gz  in=269,582,922 out=74,555,739 elapsed=311.8s

  [4942/13157] intraday_1786.csv.gz  in=269,595,042 out=74,555,739 elapsed=311.8s

  [4943/13157] intraday_1784.csv.gz  in=269,611,381 out=74,555,739 elapsed=311.8s

  [4944/13157] intraday_1785.csv.gz  in=269,624,677 out=74,555,739 elapsed=311.8s

  [4945/13157] intraday_1787.csv.gz  in=269,637,754 out=74,555,739 elapsed=311.8s

  [4946/13157] intraday_1788.csv.gz  in=269,647,754 out=74,555,739 elapsed=311.8s

  [4947/13157] intraday_1789.csv.gz  in=269,660,748 out=74,555,739 elapsed=311.8s

  [4948/13157] intraday_1791.csv.gz  in=269,672,354 out=74,555,739 elapsed=311.8s

  [4949/13157] intraday_1790.csv.gz  in=269,683,079 out=74,555,739 elapsed=311.9s

  [4950/13157] intraday_1792.csv.gz  in=269,690,632 out=74,555,739 elapsed=311.9s

  [4951/13157] intraday_1794.csv.gz  in=269,697,016 out=74,555,739 elapsed=311.9s

  [4952/13157] intraday_1793.csv.gz  in=269,707,748 out=74,555,739 elapsed=311.9s

  [4953/13157] intraday_1798.csv.gz  in=269,719,147 out=74,555,739 elapsed=311.9s

  [4954/13157] intraday_1795.csv.gz  in=269,734,013 out=74,555,739 elapsed=311.9s

  [4955/13157] intraday_1796.csv.gz  in=269,747,254 out=74,555,739 elapsed=311.9s

  [4956/13157] intraday_1797.csv.gz  in=269,759,433 out=74,555,739 elapsed=311.9s

  [4957/13157] intraday_1800.csv.gz  in=269,774,046 out=74,555,739 elapsed=312.0s

  [4958/13157] intraday_1799.csv.gz  in=269,786,908 out=74,555,739 elapsed=312.0s

  [4959/13157] intraday_1801.csv.gz  in=269,799,201 out=74,555,739 elapsed=312.0s

  [4960/13157] intraday_1802.csv.gz  in=269,811,382 out=74,555,739 elapsed=312.0s

  [4961/13157] intraday_1803.csv.gz  in=269,824,983 out=74,555,739 elapsed=312.0s

  [4962/13157] intraday_1804.csv.gz  in=269,839,332 out=74,555,739 elapsed=312.1s

  [4963/13157] intraday_1805.csv.gz  in=269,848,249 out=74,555,739 elapsed=312.1s

  [4964/13157] intraday_1806.csv.gz  in=269,860,390 out=74,555,739 elapsed=312.1s

  [4965/13157] intraday_1807.csv.gz  in=269,873,604 out=74,555,739 elapsed=312.1s

  [4966/13157] intraday_1809.csv.gz  in=269,883,819 out=74,555,739 elapsed=312.1s

  [4967/13157] intraday_1808.csv.gz  in=269,894,327 out=74,555,739 elapsed=312.1s

  [4968/13157] intraday_1811.csv.gz  in=269,906,831 out=74,555,739 elapsed=312.1s

  [4969/13157] intraday_1810.csv.gz  in=269,919,115 out=74,555,739 elapsed=312.1s

  [4970/13157] intraday_1813.csv.gz  in=269,930,841 out=74,555,739 elapsed=312.4s

  [4971/13157] intraday_1814.csv.gz  in=269,942,659 out=74,555,739 elapsed=312.4s

  [4972/13157] intraday_1815.csv.gz  in=269,961,787 out=74,555,739 elapsed=312.4s

  [4973/13157] intraday_1812.csv.gz  in=269,973,708 out=74,555,739 elapsed=312.4s

  [4974/13157] intraday_1817.csv.gz  in=269,987,533 out=74,555,739 elapsed=312.7s

  [4975/13157] intraday_1818.csv.gz  in=270,000,198 out=74,555,739 elapsed=312.7s

  [4976/13157] intraday_1819.csv.gz  in=270,012,677 out=74,555,739 elapsed=312.7s

  [4977/13157] intraday_1816.csv.gz  in=270,032,645 out=74,555,739 elapsed=312.7s

  [4978/13157] intraday_1820.csv.gz  in=270,041,488 out=74,555,739 elapsed=312.8s

  [4979/13157] intraday_1821.csv.gz  in=270,053,775 out=74,555,739 elapsed=312.9s

  [4980/13157] intraday_1822.csv.gz  in=270,065,452 out=74,555,739 elapsed=312.9s

  [4981/13157] intraday_1823.csv.gz  in=270,078,317 out=74,555,739 elapsed=313.0s

  [4982/13157] intraday_1824.csv.gz  in=270,093,475 out=74,555,739 elapsed=313.0s

  [4983/13157] intraday_1826.csv.gz  in=270,104,037 out=74,555,739 elapsed=313.2s

  [4984/13157] intraday_1825.csv.gz  in=270,116,375 out=74,555,739 elapsed=313.2s

  [4985/13157] intraday_1827.csv.gz  in=270,130,858 out=74,555,739 elapsed=313.2s

  [4986/13157] intraday_1828.csv.gz  in=270,143,167 out=74,555,739 elapsed=313.2s

  [4987/13157] intraday_1829.csv.gz  in=270,154,107 out=74,555,739 elapsed=313.2s

  [4988/13157] intraday_1830.csv.gz  in=270,166,344 out=74,555,739 elapsed=313.3s

  [4989/13157] intraday_1831.csv.gz  in=270,177,668 out=74,555,739 elapsed=313.3s

  [4990/13157] intraday_1834.csv.gz  in=270,188,034 out=74,555,739 elapsed=313.3s

  [4991/13157] intraday_1832.csv.gz  in=270,199,715 out=74,555,739 elapsed=313.3s

  [4992/13157] intraday_1833.csv.gz  in=270,211,913 out=74,555,739 elapsed=313.3s

  [4993/13157] intraday_1835.csv.gz  in=270,226,126 out=74,555,739 elapsed=313.3s

  [4994/13157] intraday_1837.csv.gz  in=270,239,470 out=74,555,739 elapsed=313.5s

  [4995/13157] intraday_1838.csv.gz  in=270,251,611 out=74,555,739 elapsed=313.5s

  [4996/13157] intraday_1836.csv.gz  in=270,263,912 out=74,555,739 elapsed=313.5s

  [4997/13157] intraday_1842.csv.gz  in=270,276,315 out=74,555,739 elapsed=313.7s

  [4998/13157] intraday_1841.csv.gz  in=270,287,061 out=74,555,739 elapsed=313.7s

  [4999/13157] intraday_1840.csv.gz  in=270,299,996 out=74,555,739 elapsed=313.7s

  [5000/13157] intraday_1839.csv.gz  in=270,324,012 out=74,555,739 elapsed=313.7s

  [5001/13157] intraday_1843.csv.gz  in=270,335,419 out=74,555,739 elapsed=313.9s

  [5002/13157] intraday_1844.csv.gz  in=270,349,647 out=74,555,739 elapsed=313.9s

  [5003/13157] intraday_1846.csv.gz  in=270,364,230 out=74,555,739 elapsed=314.0s

  [5004/13157] intraday_1845.csv.gz  in=270,379,427 out=74,555,739 elapsed=314.0s

  [5005/13157] intraday_1847.csv.gz  in=270,389,833 out=74,555,739 elapsed=314.2s

  [5006/13157] intraday_1850.csv.gz  in=270,401,857 out=74,555,739 elapsed=314.2s

  [5007/13157] intraday_1849.csv.gz  in=270,414,682 out=74,555,739 elapsed=314.3s

  [5008/13157] intraday_1848.csv.gz  in=270,427,848 out=74,555,739 elapsed=314.3s

  [5009/13157] intraday_1851.csv.gz  in=270,438,378 out=74,555,739 elapsed=314.3s

  [5010/13157] intraday_1852.csv.gz  in=270,450,941 out=74,555,739 elapsed=314.4s

  [5011/13157] intraday_1855.csv.gz  in=270,462,553 out=74,555,739 elapsed=314.4s

  [5012/13157] intraday_1853.csv.gz  in=270,474,720 out=74,555,739 elapsed=314.4s

  [5013/13157] intraday_1854.csv.gz  in=270,499,763 out=74,555,739 elapsed=314.4s

  [5014/13157] intraday_1857.csv.gz  in=270,511,231 out=74,555,739 elapsed=314.6s

  [5015/13157] intraday_1858.csv.gz  in=270,524,040 out=74,555,739 elapsed=314.6s

  [5016/13157] intraday_1859.csv.gz  in=270,536,569 out=74,555,739 elapsed=314.6s

  [5017/13157] intraday_1856.csv.gz  in=270,556,833 out=74,555,739 elapsed=314.6s

  [5018/13157] intraday_1861.csv.gz  in=270,569,808 out=74,555,739 elapsed=314.9s

  [5019/13157] intraday_1862.csv.gz  in=270,581,812 out=74,555,739 elapsed=314.9s

  [5020/13157] intraday_1863.csv.gz  in=270,592,192 out=74,555,739 elapsed=314.9s

  [5021/13157] intraday_1860.csv.gz  in=270,606,587 out=74,555,739 elapsed=314.9s

  [5022/13157] intraday_1867.csv.gz  in=270,616,435 out=74,555,739 elapsed=315.0s

  [5023/13157] intraday_1864.csv.gz  in=270,628,462 out=74,555,739 elapsed=315.0s

  [5024/13157] intraday_1865.csv.gz  in=270,639,751 out=74,555,739 elapsed=315.0s

  [5025/13157] intraday_1866.csv.gz  in=270,664,010 out=74,555,739 elapsed=315.0s

  [5026/13157] intraday_1869.csv.gz  in=270,674,712 out=74,555,739 elapsed=315.1s

  [5027/13157] intraday_1871.csv.gz  in=270,685,303 out=74,555,739 elapsed=315.1s

  [5028/13157] intraday_1868.csv.gz  in=270,696,782 out=74,555,739 elapsed=315.1s

  [5029/13157] intraday_1870.csv.gz  in=270,709,936 out=74,555,739 elapsed=315.1s

  [5030/13157] intraday_1873.csv.gz  in=270,720,660 out=74,555,739 elapsed=315.1s

  [5031/13157] intraday_1875.csv.gz  in=270,732,071 out=74,555,739 elapsed=315.1s

  [5032/13157] intraday_1872.csv.gz  in=270,745,257 out=74,555,739 elapsed=315.1s

  [5033/13157] intraday_1874.csv.gz  in=270,756,556 out=74,555,739 elapsed=315.1s

  [5034/13157] intraday_1877.csv.gz  in=270,768,419 out=74,555,739 elapsed=315.2s

  [5035/13157] intraday_1876.csv.gz  in=270,781,583 out=74,555,739 elapsed=315.2s

  [5036/13157] intraday_1879.csv.gz  in=270,791,272 out=74,555,739 elapsed=315.2s

  [5037/13157] intraday_1878.csv.gz  in=270,802,928 out=74,555,739 elapsed=315.2s

  [5038/13157] intraday_1881.csv.gz  in=270,814,827 out=74,555,739 elapsed=315.2s

  [5039/13157] intraday_1880.csv.gz  in=270,832,666 out=74,555,739 elapsed=315.2s

  [5040/13157] intraday_1883.csv.gz  in=270,844,383 out=74,555,739 elapsed=315.3s

  [5041/13157] intraday_1882.csv.gz  in=270,859,092 out=74,555,739 elapsed=315.3s

  [5042/13157] intraday_1886.csv.gz  in=270,872,106 out=74,555,739 elapsed=315.3s

  [5043/13157] intraday_1884.csv.gz  in=270,885,981 out=74,555,739 elapsed=315.4s

  [5044/13157] intraday_1887.csv.gz  in=270,898,728 out=74,555,739 elapsed=315.4s

  [5045/13157] intraday_1885.csv.gz  in=270,912,272 out=74,555,739 elapsed=315.4s

  [5046/13157] intraday_1888.csv.gz  in=270,924,516 out=74,555,739 elapsed=315.4s

  [5047/13157] intraday_1889.csv.gz  in=270,935,838 out=74,555,739 elapsed=315.4s

  [5048/13157] intraday_1890.csv.gz  in=270,946,688 out=74,555,739 elapsed=315.4s

  [5049/13157] intraday_1891.csv.gz  in=270,958,317 out=74,555,739 elapsed=315.4s

  [5050/13157] intraday_1892.csv.gz  in=270,970,840 out=74,555,739 elapsed=315.4s

  [5051/13157] intraday_1893.csv.gz  in=270,982,083 out=74,555,739 elapsed=315.5s

  [5052/13157] intraday_1894.csv.gz  in=270,993,884 out=74,555,739 elapsed=315.5s

  [5053/13157] intraday_1895.csv.gz  in=271,006,116 out=74,555,739 elapsed=315.5s

  [5054/13157] intraday_1897.csv.gz  in=271,018,463 out=74,555,739 elapsed=315.5s

  [5055/13157] intraday_1896.csv.gz  in=271,030,332 out=74,555,739 elapsed=315.5s

  [5056/13157] intraday_1898.csv.gz  in=271,042,513 out=74,555,739 elapsed=315.5s

  [5057/13157] intraday_1899.csv.gz  in=271,068,237 out=74,555,739 elapsed=315.5s

  [5058/13157] intraday_1900.csv.gz  in=271,081,869 out=74,555,739 elapsed=315.5s

  [5059/13157] intraday_1901.csv.gz  in=271,096,699 out=74,555,739 elapsed=315.6s

  [5060/13157] intraday_1902.csv.gz  in=271,108,453 out=74,555,739 elapsed=315.6s

  [5061/13157] intraday_1903.csv.gz  in=271,131,820 out=74,555,739 elapsed=315.6s

  [5062/13157] intraday_1904.csv.gz  in=271,144,490 out=74,555,739 elapsed=315.6s

  [5063/13157] intraday_1906.csv.gz  in=271,157,458 out=74,555,739 elapsed=315.6s

  [5064/13157] intraday_1907.csv.gz  in=271,169,960 out=74,555,739 elapsed=315.6s

  [5065/13157] intraday_1905.csv.gz  in=271,190,208 out=74,555,739 elapsed=315.6s

  [5066/13157] intraday_1908.csv.gz  in=271,203,528 out=74,555,739 elapsed=315.6s

  [5067/13157] intraday_1910.csv.gz  in=271,215,412 out=74,555,739 elapsed=315.7s

  [5068/13157] intraday_1909.csv.gz  in=271,232,425 out=74,555,739 elapsed=315.7s

  [5069/13157] intraday_1911.csv.gz  in=271,245,569 out=74,555,739 elapsed=315.7s

  [5070/13157] intraday_1912.csv.gz  in=271,258,683 out=74,555,739 elapsed=315.7s

  [5071/13157] intraday_1913.csv.gz  in=271,270,121 out=74,555,739 elapsed=315.7s

  [5072/13157] intraday_1914.csv.gz  in=271,280,647 out=74,555,739 elapsed=315.7s

  [5073/13157] intraday_1916.csv.gz  in=271,293,700 out=74,555,739 elapsed=315.7s

  [5074/13157] intraday_1915.csv.gz  in=271,307,604 out=74,555,739 elapsed=315.7s

  [5075/13157] intraday_1918.csv.gz  in=271,320,055 out=74,555,739 elapsed=315.8s

  [5076/13157] intraday_1917.csv.gz  in=271,342,078 out=74,555,739 elapsed=315.8s

  [5077/13157] intraday_1919.csv.gz  in=271,357,658 out=74,555,739 elapsed=315.8s

  [5078/13157] intraday_1921.csv.gz  in=271,370,746 out=74,555,739 elapsed=315.8s

  [5079/13157] intraday_1920.csv.gz  in=271,384,353 out=74,555,739 elapsed=315.8s

  [5080/13157] intraday_1925.csv.gz  in=271,398,299 out=74,555,739 elapsed=315.8s

  [5081/13157] intraday_1924.csv.gz  in=271,413,333 out=74,555,739 elapsed=315.8s

  [5082/13157] intraday_1922.csv.gz  in=271,433,108 out=74,555,739 elapsed=315.9s

  [5083/13157] intraday_1923.csv.gz  in=271,448,419 out=74,555,739 elapsed=315.9s

  [5084/13157] intraday_1927.csv.gz  in=271,459,319 out=74,555,739 elapsed=315.9s

  [5085/13157] intraday_1929.csv.gz  in=271,472,078 out=74,555,739 elapsed=315.9s

  [5086/13157] intraday_1926.csv.gz  in=271,486,945 out=74,555,739 elapsed=315.9s

  [5087/13157] intraday_1928.csv.gz  in=271,497,968 out=74,555,739 elapsed=315.9s

  [5088/13157] intraday_1931.csv.gz  in=271,507,380 out=74,555,739 elapsed=315.9s

  [5089/13157] intraday_1930.csv.gz  in=271,519,048 out=74,555,739 elapsed=315.9s

  [5090/13157] intraday_1932.csv.gz  in=271,528,025 out=74,555,739 elapsed=316.0s

  [5091/13157] intraday_1933.csv.gz  in=271,537,927 out=74,555,739 elapsed=316.0s

  [5092/13157] intraday_1934.csv.gz  in=271,542,518 out=74,555,739 elapsed=316.0s

  [5093/13157] intraday_1936.csv.gz  in=271,556,367 out=74,555,739 elapsed=316.0s

  [5094/13157] intraday_1935.csv.gz  in=271,571,243 out=74,555,739 elapsed=316.0s

  [5095/13157] intraday_1937.csv.gz  in=271,583,282 out=74,555,739 elapsed=316.0s

  [5096/13157] intraday_1938.csv.gz  in=271,594,868 out=74,555,739 elapsed=316.0s

  [5097/13157] intraday_1939.csv.gz  in=271,608,186 out=74,555,739 elapsed=316.1s

  [5098/13157] intraday_1941.csv.gz  in=271,620,525 out=74,555,739 elapsed=316.1s

  [5099/13157] intraday_1940.csv.gz  in=271,635,053 out=74,555,739 elapsed=316.1s

  [5100/13157] intraday_1942.csv.gz  in=271,647,239 out=74,555,739 elapsed=316.1s

  [5101/13157] intraday_1943.csv.gz  in=271,661,300 out=74,555,739 elapsed=316.1s

  [5102/13157] intraday_1945.csv.gz  in=271,670,245 out=74,555,739 elapsed=316.1s

  [5103/13157] intraday_1944.csv.gz  in=271,685,963 out=74,555,739 elapsed=316.1s

  [5104/13157] intraday_1946.csv.gz  in=271,703,268 out=74,555,739 elapsed=316.1s

  [5105/13157] intraday_1949.csv.gz  in=271,713,935 out=74,555,739 elapsed=316.2s

  [5106/13157] intraday_1950.csv.gz  in=271,726,977 out=74,555,739 elapsed=316.2s

  [5107/13157] intraday_1947.csv.gz  in=271,740,695 out=74,555,739 elapsed=316.2s

  [5108/13157] intraday_1948.csv.gz  in=271,756,095 out=74,555,739 elapsed=316.2s

  [5109/13157] intraday_1952.csv.gz  in=271,768,589 out=74,555,739 elapsed=316.3s

  [5110/13157] intraday_1953.csv.gz  in=271,782,511 out=74,555,739 elapsed=316.3s

  [5111/13157] intraday_1951.csv.gz  in=271,801,289 out=74,555,739 elapsed=316.3s

  [5112/13157] intraday_1954.csv.gz  in=271,813,625 out=74,555,739 elapsed=316.3s

  [5113/13157] intraday_1957.csv.gz  in=271,828,620 out=74,555,739 elapsed=316.3s

  [5114/13157] intraday_1956.csv.gz  in=271,840,358 out=74,555,739 elapsed=316.3s

  [5115/13157] intraday_1958.csv.gz  in=271,858,022 out=74,555,739 elapsed=316.3s

  [5116/13157] intraday_1955.csv.gz  in=271,871,393 out=74,555,739 elapsed=316.3s

  [5117/13157] intraday_1961.csv.gz  in=271,883,544 out=74,555,739 elapsed=316.4s

  [5118/13157] intraday_1959.csv.gz  in=271,895,834 out=74,555,739 elapsed=316.4s

  [5119/13157] intraday_1962.csv.gz  in=271,907,582 out=74,555,739 elapsed=316.4s

  [5120/13157] intraday_1960.csv.gz  in=271,918,219 out=74,555,739 elapsed=316.4s

  [5121/13157] intraday_1963.csv.gz  in=271,931,073 out=74,555,739 elapsed=316.4s

  [5122/13157] intraday_1967.csv.gz  in=271,942,387 out=74,555,739 elapsed=316.5s

  [5123/13157] intraday_1964.csv.gz  in=271,957,068 out=74,555,739 elapsed=316.5s

  [5124/13157] intraday_1965.csv.gz  in=271,970,823 out=74,555,739 elapsed=316.5s

  [5125/13157] intraday_1966.csv.gz  in=271,982,058 out=74,555,739 elapsed=316.5s

  [5126/13157] intraday_1968.csv.gz  in=271,995,480 out=74,555,739 elapsed=316.6s

  [5127/13157] intraday_1971.csv.gz  in=272,005,920 out=74,555,739 elapsed=316.6s

  [5128/13157] intraday_1970.csv.gz  in=272,018,880 out=74,555,739 elapsed=316.6s

  [5129/13157] intraday_1969.csv.gz  in=272,029,809 out=74,555,739 elapsed=316.6s

  [5130/13157] intraday_1972.csv.gz  in=272,041,207 out=74,555,739 elapsed=316.6s

  [5131/13157] intraday_1974.csv.gz  in=272,052,085 out=74,555,739 elapsed=316.6s

  [5132/13157] intraday_1975.csv.gz  in=272,067,166 out=74,555,739 elapsed=316.6s

  [5133/13157] intraday_1973.csv.gz  in=272,080,777 out=74,555,739 elapsed=316.6s

  [5134/13157] intraday_1978.csv.gz  in=272,093,673 out=74,555,739 elapsed=317.0s

  [5135/13157] intraday_1976.csv.gz  in=272,106,403 out=74,555,739 elapsed=317.0s

  [5136/13157] intraday_1977.csv.gz  in=272,118,482 out=74,555,739 elapsed=317.0s

  [5137/13157] intraday_1979.csv.gz  in=272,131,176 out=74,555,739 elapsed=317.1s

  [5138/13157] intraday_1980.csv.gz  in=272,144,140 out=74,555,739 elapsed=317.5s

  [5139/13157] intraday_1981.csv.gz  in=272,155,158 out=74,555,739 elapsed=317.5s

  [5140/13157] intraday_1983.csv.gz  in=272,167,636 out=74,555,739 elapsed=317.5s

  [5141/13157] intraday_1985.csv.gz  in=272,179,619 out=74,555,739 elapsed=317.9s

  [5142/13157] intraday_1984.csv.gz  in=272,194,270 out=74,555,739 elapsed=317.9s

  [5143/13157] intraday_1986.csv.gz  in=272,206,814 out=74,555,739 elapsed=318.0s

  [5144/13157] intraday_1982.csv.gz  in=272,239,530 out=74,555,739 elapsed=318.0s

  [5145/13157] intraday_1987.csv.gz  in=272,251,832 out=74,555,739 elapsed=318.3s

  [5146/13157] intraday_1988.csv.gz  in=272,265,125 out=74,555,739 elapsed=318.5s

  [5147/13157] intraday_1989.csv.gz  in=272,277,571 out=74,555,739 elapsed=318.5s

  [5148/13157] intraday_1990.csv.gz  in=272,290,024 out=74,555,739 elapsed=318.6s

  [5149/13157] intraday_1991.csv.gz  in=272,301,065 out=74,555,739 elapsed=318.6s

  [5150/13157] intraday_1992.csv.gz  in=272,314,123 out=74,555,739 elapsed=318.6s

  [5151/13157] intraday_1993.csv.gz  in=272,327,155 out=74,555,739 elapsed=318.7s

  [5152/13157] intraday_1994.csv.gz  in=272,339,570 out=74,555,739 elapsed=318.7s

  [5153/13157] intraday_1996.csv.gz  in=272,350,297 out=74,555,739 elapsed=318.7s

  [5154/13157] intraday_1995.csv.gz  in=272,361,736 out=74,555,739 elapsed=318.7s

  [5155/13157] intraday_1997.csv.gz  in=272,371,802 out=74,555,739 elapsed=318.8s

  [5156/13157] intraday_2000.csv.gz  in=272,385,479 out=74,555,739 elapsed=318.8s

  [5157/13157] intraday_1999.csv.gz  in=272,397,214 out=74,555,739 elapsed=318.8s

  [5158/13157] intraday_1998.csv.gz  in=272,410,928 out=74,555,739 elapsed=318.8s

  [5159/13157] intraday_2003.csv.gz  in=272,420,826 out=74,555,739 elapsed=318.9s

  [5160/13157] intraday_2001.csv.gz  in=272,434,474 out=74,555,739 elapsed=318.9s

  [5161/13157] intraday_2002.csv.gz  in=272,451,386 out=74,555,739 elapsed=318.9s

  [5162/13157] intraday_2004.csv.gz  in=272,464,354 out=74,555,739 elapsed=318.9s

  [5163/13157] intraday_2005.csv.gz  in=272,475,843 out=74,555,739 elapsed=319.0s

  [5164/13157] intraday_2008.csv.gz  in=272,488,185 out=74,555,739 elapsed=319.0s

  [5165/13157] intraday_2006.csv.gz  in=272,501,044 out=74,555,739 elapsed=319.0s

  [5166/13157] intraday_2007.csv.gz  in=272,510,925 out=74,555,739 elapsed=319.0s

  [5167/13157] intraday_2009.csv.gz  in=272,521,802 out=74,555,739 elapsed=319.0s

  [5168/13157] intraday_2011.csv.gz  in=272,532,764 out=74,555,739 elapsed=319.0s

  [5169/13157] intraday_2010.csv.gz  in=272,545,023 out=74,555,739 elapsed=319.1s

  [5170/13157] intraday_2013.csv.gz  in=272,556,440 out=74,555,739 elapsed=319.1s

  [5171/13157] intraday_2014.csv.gz  in=272,567,458 out=74,555,739 elapsed=319.1s

  [5172/13157] intraday_2012.csv.gz  in=272,580,998 out=74,555,739 elapsed=319.1s

  [5173/13157] intraday_2015.csv.gz  in=272,592,133 out=74,555,739 elapsed=319.1s

  [5174/13157] intraday_2018.csv.gz  in=272,604,099 out=74,555,739 elapsed=319.2s

  [5175/13157] intraday_2017.csv.gz  in=272,615,489 out=74,555,739 elapsed=319.2s

  [5176/13157] intraday_2016.csv.gz  in=272,630,496 out=74,555,739 elapsed=319.2s

  [5177/13157] intraday_2019.csv.gz  in=272,641,503 out=74,555,739 elapsed=319.3s

  [5178/13157] intraday_2020.csv.gz  in=272,653,320 out=74,555,739 elapsed=319.3s

  [5179/13157] intraday_2021.csv.gz  in=272,665,627 out=74,555,739 elapsed=319.3s

  [5180/13157] intraday_2022.csv.gz  in=272,681,156 out=74,555,739 elapsed=319.3s

  [5181/13157] intraday_2023.csv.gz  in=272,692,240 out=74,555,739 elapsed=319.4s

  [5182/13157] intraday_2026.csv.gz  in=272,706,388 out=74,555,739 elapsed=319.4s

  [5183/13157] intraday_2024.csv.gz  in=272,720,926 out=74,555,739 elapsed=319.4s

  [5184/13157] intraday_2025.csv.gz  in=272,735,987 out=74,555,739 elapsed=319.4s

  [5185/13157] intraday_2030.csv.gz  in=272,748,258 out=74,555,739 elapsed=319.4s

  [5186/13157] intraday_2027.csv.gz  in=272,762,483 out=74,555,739 elapsed=319.5s

  [5187/13157] intraday_2029.csv.gz  in=272,774,528 out=74,555,739 elapsed=319.5s

  [5188/13157] intraday_2028.csv.gz  in=272,788,046 out=74,555,739 elapsed=319.5s

  [5189/13157] intraday_2031.csv.gz  in=272,798,769 out=74,555,739 elapsed=319.6s

  [5190/13157] intraday_2032.csv.gz  in=272,810,609 out=74,555,739 elapsed=319.6s

  [5191/13157] intraday_2033.csv.gz  in=272,822,122 out=74,555,739 elapsed=319.6s

  [5192/13157] intraday_2035.csv.gz  in=272,833,058 out=74,555,739 elapsed=319.6s

  [5193/13157] intraday_2034.csv.gz  in=272,847,168 out=74,555,739 elapsed=319.7s

  [5194/13157] intraday_2036.csv.gz  in=272,860,051 out=74,555,739 elapsed=319.7s

  [5195/13157] intraday_2038.csv.gz  in=272,873,441 out=74,555,739 elapsed=319.7s

  [5196/13157] intraday_2037.csv.gz  in=272,885,831 out=74,555,739 elapsed=319.7s

  [5197/13157] intraday_2039.csv.gz  in=272,904,052 out=74,555,739 elapsed=319.7s

  [5198/13157] intraday_2041.csv.gz  in=272,918,886 out=74,555,739 elapsed=319.7s

  [5199/13157] intraday_2040.csv.gz  in=272,932,853 out=74,555,739 elapsed=319.7s

  [5200/13157] intraday_2042.csv.gz  in=272,946,250 out=74,555,739 elapsed=319.7s

  [5201/13157] intraday_2044.csv.gz  in=272,959,622 out=74,555,739 elapsed=319.9s

  [5202/13157] intraday_2043.csv.gz  in=272,972,046 out=74,555,739 elapsed=319.9s

  [5203/13157] intraday_2046.csv.gz  in=272,985,004 out=74,555,739 elapsed=319.9s

  [5204/13157] intraday_2045.csv.gz  in=272,996,784 out=74,555,739 elapsed=319.9s

  [5205/13157] intraday_2050.csv.gz  in=273,009,602 out=74,555,739 elapsed=320.1s

  [5206/13157] intraday_2047.csv.gz  in=273,022,154 out=74,555,739 elapsed=320.1s

  [5207/13157] intraday_2049.csv.gz  in=273,037,904 out=74,555,739 elapsed=320.1s

  [5208/13157] intraday_2048.csv.gz  in=273,052,980 out=74,555,739 elapsed=320.1s

  [5209/13157] intraday_2051.csv.gz  in=273,065,526 out=74,555,739 elapsed=320.3s

  [5210/13157] intraday_2053.csv.gz  in=273,076,557 out=74,555,739 elapsed=320.3s

  [5211/13157] intraday_2054.csv.gz  in=273,088,552 out=74,555,739 elapsed=320.3s

  [5212/13157] intraday_2052.csv.gz  in=273,109,529 out=74,555,739 elapsed=320.3s

  [5213/13157] intraday_2056.csv.gz  in=273,124,842 out=74,555,739 elapsed=320.4s

  [5214/13157] intraday_2057.csv.gz  in=273,137,899 out=74,555,739 elapsed=320.4s

  [5215/13157] intraday_2055.csv.gz  in=273,149,560 out=74,555,739 elapsed=320.4s

  [5216/13157] intraday_2058.csv.gz  in=273,164,876 out=74,555,739 elapsed=320.4s

  [5217/13157] intraday_2059.csv.gz  in=273,177,273 out=74,555,739 elapsed=320.5s

  [5218/13157] intraday_2061.csv.gz  in=273,191,687 out=74,555,739 elapsed=320.5s

  [5219/13157] intraday_2060.csv.gz  in=273,205,054 out=74,555,739 elapsed=320.5s

  [5220/13157] intraday_2062.csv.gz  in=273,217,565 out=74,555,739 elapsed=320.6s

  [5221/13157] intraday_2065.csv.gz  in=273,232,752 out=74,555,739 elapsed=320.6s

  [5222/13157] intraday_2064.csv.gz  in=273,247,784 out=74,555,739 elapsed=320.6s

  [5223/13157] intraday_2063.csv.gz  in=273,262,305 out=74,555,739 elapsed=320.6s

  [5224/13157] intraday_2067.csv.gz  in=273,274,277 out=74,555,739 elapsed=320.7s

  [5225/13157] intraday_2066.csv.gz  in=273,287,746 out=74,555,739 elapsed=320.7s

  [5226/13157] intraday_2068.csv.gz  in=273,303,908 out=74,555,739 elapsed=320.7s

  [5227/13157] intraday_2072.csv.gz  in=273,311,535 out=74,555,739 elapsed=320.7s

  [5228/13157] intraday_2071.csv.gz  in=273,326,915 out=74,555,739 elapsed=320.7s

  [5229/13157] intraday_2069.csv.gz  in=273,340,053 out=74,555,739 elapsed=320.7s

  [5230/13157] intraday_2070.csv.gz  in=273,352,431 out=74,555,739 elapsed=320.7s

  [5231/13157] intraday_2074.csv.gz  in=273,358,548 out=74,555,739 elapsed=320.8s

  [5232/13157] intraday_2073.csv.gz  in=273,369,513 out=74,555,739 elapsed=320.8s

  [5233/13157] intraday_2076.csv.gz  in=273,384,069 out=74,555,739 elapsed=320.8s

  [5234/13157] intraday_2075.csv.gz  in=273,398,861 out=74,555,739 elapsed=320.8s

  [5235/13157] intraday_2077.csv.gz  in=273,410,843 out=74,555,739 elapsed=320.8s

  [5236/13157] intraday_2078.csv.gz  in=273,421,701 out=74,555,739 elapsed=320.9s

  [5237/13157] intraday_2079.csv.gz  in=273,435,778 out=74,555,739 elapsed=320.9s

  [5238/13157] intraday_2080.csv.gz  in=273,450,173 out=74,555,739 elapsed=320.9s

  [5239/13157] intraday_2081.csv.gz  in=273,462,416 out=74,555,739 elapsed=320.9s

  [5240/13157] intraday_2082.csv.gz  in=273,475,267 out=74,555,739 elapsed=320.9s

  [5241/13157] intraday_2085.csv.gz  in=273,485,185 out=74,555,739 elapsed=320.9s

  [5242/13157] intraday_2083.csv.gz  in=273,499,605 out=74,555,739 elapsed=320.9s

  [5243/13157] intraday_2086.csv.gz  in=273,511,396 out=74,555,739 elapsed=320.9s

  [5244/13157] intraday_2084.csv.gz  in=273,526,712 out=74,555,739 elapsed=320.9s

  [5245/13157] intraday_2088.csv.gz  in=273,537,981 out=74,555,739 elapsed=321.0s

  [5246/13157] intraday_2087.csv.gz  in=273,551,717 out=74,555,739 elapsed=321.0s

  [5247/13157] intraday_2089.csv.gz  in=273,562,963 out=74,555,739 elapsed=321.0s

  [5248/13157] intraday_2090.csv.gz  in=273,575,569 out=74,555,739 elapsed=321.0s

  [5249/13157] intraday_2093.csv.gz  in=273,587,749 out=74,555,739 elapsed=321.1s

  [5250/13157] intraday_2094.csv.gz  in=273,599,974 out=74,555,739 elapsed=321.1s

  [5251/13157] intraday_2092.csv.gz  in=273,612,705 out=74,555,739 elapsed=321.1s

  [5252/13157] intraday_2091.csv.gz  in=273,625,276 out=74,555,739 elapsed=321.1s

  [5253/13157] intraday_2097.csv.gz  in=273,637,662 out=74,555,739 elapsed=321.2s

  [5254/13157] intraday_2096.csv.gz  in=273,649,987 out=74,555,739 elapsed=321.2s

  [5255/13157] intraday_2098.csv.gz  in=273,662,493 out=74,555,739 elapsed=321.2s

  [5256/13157] intraday_2095.csv.gz  in=273,675,995 out=74,555,739 elapsed=321.2s

  [5257/13157] intraday_2100.csv.gz  in=273,685,251 out=74,555,739 elapsed=321.3s

  [5258/13157] intraday_2099.csv.gz  in=273,697,742 out=74,555,739 elapsed=321.3s

  [5259/13157] intraday_2101.csv.gz  in=273,709,971 out=74,555,739 elapsed=321.3s

  [5260/13157] intraday_2102.csv.gz  in=273,722,518 out=74,555,739 elapsed=321.3s

  [5261/13157] intraday_2103.csv.gz  in=273,736,039 out=74,555,739 elapsed=321.3s

  [5262/13157] intraday_2104.csv.gz  in=273,751,011 out=74,555,739 elapsed=321.3s

  [5263/13157] intraday_2105.csv.gz  in=273,763,348 out=74,555,739 elapsed=321.4s

  [5264/13157] intraday_2108.csv.gz  in=273,776,215 out=74,555,739 elapsed=321.4s

  [5265/13157] intraday_2107.csv.gz  in=273,788,511 out=74,555,739 elapsed=321.4s

  [5266/13157] intraday_2106.csv.gz  in=273,800,185 out=74,555,739 elapsed=321.5s

  [5267/13157] intraday_2109.csv.gz  in=273,811,302 out=74,555,739 elapsed=321.5s

  [5268/13157] intraday_2111.csv.gz  in=273,822,667 out=74,555,739 elapsed=321.5s

  [5269/13157] intraday_2112.csv.gz  in=273,833,854 out=74,555,739 elapsed=321.5s

  [5270/13157] intraday_2110.csv.gz  in=273,846,872 out=74,555,739 elapsed=321.5s

  [5271/13157] intraday_2113.csv.gz  in=273,859,645 out=74,555,739 elapsed=321.5s

  [5272/13157] intraday_2114.csv.gz  in=273,871,594 out=74,555,739 elapsed=321.6s

  [5273/13157] intraday_2115.csv.gz  in=273,886,335 out=74,555,739 elapsed=321.6s

  [5274/13157] intraday_2116.csv.gz  in=273,898,406 out=74,555,739 elapsed=321.6s

  [5275/13157] intraday_2117.csv.gz  in=273,912,582 out=74,555,739 elapsed=321.6s

  [5276/13157] intraday_2121.csv.gz  in=273,923,685 out=74,555,739 elapsed=321.6s

  [5277/13157] intraday_2118.csv.gz  in=273,936,461 out=74,555,739 elapsed=321.6s

  [5278/13157] intraday_2120.csv.gz  in=273,949,489 out=74,555,739 elapsed=321.6s

  [5279/13157] intraday_2119.csv.gz  in=273,962,262 out=74,555,739 elapsed=321.6s

  [5280/13157] intraday_2122.csv.gz  in=273,974,662 out=74,555,739 elapsed=321.7s

  [5281/13157] intraday_2124.csv.gz  in=273,985,221 out=74,555,739 elapsed=321.8s

  [5282/13157] intraday_2123.csv.gz  in=273,997,563 out=74,555,739 elapsed=321.8s

  [5283/13157] intraday_2125.csv.gz  in=274,011,073 out=74,555,739 elapsed=321.8s

  [5284/13157] intraday_2127.csv.gz  in=274,022,107 out=74,555,739 elapsed=321.8s

  [5285/13157] intraday_2126.csv.gz  in=274,034,210 out=74,555,739 elapsed=321.8s

  [5286/13157] intraday_2128.csv.gz  in=274,046,660 out=74,555,739 elapsed=321.8s

  [5287/13157] intraday_2131.csv.gz  in=274,058,342 out=74,555,739 elapsed=321.9s

  [5288/13157] intraday_2130.csv.gz  in=274,070,151 out=74,555,739 elapsed=321.9s

  [5289/13157] intraday_2129.csv.gz  in=274,084,111 out=74,555,739 elapsed=321.9s

  [5290/13157] intraday_2133.csv.gz  in=274,095,891 out=74,555,739 elapsed=322.0s

  [5291/13157] intraday_2135.csv.gz  in=274,108,442 out=74,555,739 elapsed=322.1s

  [5292/13157] intraday_2134.csv.gz  in=274,121,299 out=74,555,739 elapsed=322.1s

  [5293/13157] intraday_2132.csv.gz  in=274,135,329 out=74,555,739 elapsed=322.1s

  [5294/13157] intraday_2136.csv.gz  in=274,146,192 out=74,555,739 elapsed=322.2s

  [5295/13157] intraday_2139.csv.gz  in=274,160,005 out=74,555,739 elapsed=322.2s

  [5296/13157] intraday_2137.csv.gz  in=274,170,620 out=74,555,739 elapsed=322.2s

  [5297/13157] intraday_2138.csv.gz  in=274,183,985 out=74,555,739 elapsed=322.2s

  [5298/13157] intraday_2142.csv.gz  in=274,194,593 out=74,555,739 elapsed=322.2s

  [5299/13157] intraday_2141.csv.gz  in=274,208,992 out=74,555,739 elapsed=322.2s

  [5300/13157] intraday_2140.csv.gz  in=274,223,764 out=74,555,739 elapsed=322.3s

  [5301/13157] intraday_2143.csv.gz  in=274,235,655 out=74,555,739 elapsed=322.3s

  [5302/13157] intraday_2145.csv.gz  in=274,248,084 out=74,555,739 elapsed=322.3s

  [5303/13157] intraday_2144.csv.gz  in=274,259,573 out=74,555,739 elapsed=322.3s

  [5304/13157] intraday_2146.csv.gz  in=274,273,566 out=74,555,739 elapsed=322.3s

  [5305/13157] intraday_2147.csv.gz  in=274,284,990 out=74,555,739 elapsed=322.3s

  [5306/13157] intraday_2148.csv.gz  in=274,296,398 out=74,555,739 elapsed=322.4s

  [5307/13157] intraday_2149.csv.gz  in=274,308,245 out=74,555,739 elapsed=322.4s

  [5308/13157] intraday_2151.csv.gz  in=274,319,638 out=74,555,739 elapsed=322.4s

  [5309/13157] intraday_2150.csv.gz  in=274,332,530 out=74,555,739 elapsed=322.4s

  [5310/13157] intraday_2153.csv.gz  in=274,343,435 out=74,555,739 elapsed=322.5s

  [5311/13157] intraday_2155.csv.gz  in=274,355,595 out=74,555,739 elapsed=322.5s

  [5312/13157] intraday_2152.csv.gz  in=274,368,603 out=74,555,739 elapsed=322.5s

  [5313/13157] intraday_2154.csv.gz  in=274,380,305 out=74,555,739 elapsed=322.5s

  [5314/13157] intraday_2157.csv.gz  in=274,390,912 out=74,555,739 elapsed=322.5s

  [5315/13157] intraday_2159.csv.gz  in=274,400,703 out=74,555,739 elapsed=322.5s

  [5316/13157] intraday_2158.csv.gz  in=274,412,802 out=74,555,739 elapsed=322.5s

  [5317/13157] intraday_2156.csv.gz  in=274,428,592 out=74,555,739 elapsed=322.6s

  [5318/13157] intraday_2161.csv.gz  in=274,440,269 out=74,555,739 elapsed=322.7s

  [5319/13157] intraday_2160.csv.gz  in=274,454,655 out=74,555,739 elapsed=322.7s

  [5320/13157] intraday_2163.csv.gz  in=274,466,949 out=74,555,739 elapsed=322.7s

  [5321/13157] intraday_2162.csv.gz  in=274,483,001 out=74,555,739 elapsed=322.7s

  [5322/13157] intraday_2165.csv.gz  in=274,496,430 out=74,555,739 elapsed=322.7s

  [5323/13157] intraday_2164.csv.gz  in=274,511,180 out=74,555,739 elapsed=322.7s

  [5324/13157] intraday_2167.csv.gz  in=274,524,819 out=74,555,739 elapsed=322.7s

  [5325/13157] intraday_2166.csv.gz  in=274,539,429 out=74,555,739 elapsed=322.7s

  [5326/13157] intraday_2170.csv.gz  in=274,551,479 out=74,555,739 elapsed=322.8s

  [5327/13157] intraday_2169.csv.gz  in=274,563,829 out=74,555,739 elapsed=322.8s

  [5328/13157] intraday_2168.csv.gz  in=274,576,260 out=74,555,739 elapsed=322.8s

  [5329/13157] intraday_2171.csv.gz  in=274,589,160 out=74,555,739 elapsed=322.8s

  [5330/13157] intraday_2172.csv.gz  in=274,601,784 out=74,555,739 elapsed=323.0s

  [5331/13157] intraday_2174.csv.gz  in=274,616,642 out=74,555,739 elapsed=323.0s

  [5332/13157] intraday_2175.csv.gz  in=274,628,922 out=74,555,739 elapsed=323.0s

  [5333/13157] intraday_2173.csv.gz  in=274,640,352 out=74,555,739 elapsed=323.0s

  [5334/13157] intraday_2176.csv.gz  in=274,651,940 out=74,555,739 elapsed=323.1s

  [5335/13157] intraday_2178.csv.gz  in=274,662,265 out=74,555,739 elapsed=323.1s

  [5336/13157] intraday_2179.csv.gz  in=274,675,271 out=74,555,739 elapsed=323.1s

  [5337/13157] intraday_2177.csv.gz  in=274,690,692 out=74,555,739 elapsed=323.1s

  [5338/13157] intraday_2182.csv.gz  in=274,703,590 out=74,555,739 elapsed=323.3s

  [5339/13157] intraday_2180.csv.gz  in=274,717,986 out=74,555,739 elapsed=323.3s

  [5340/13157] intraday_2183.csv.gz  in=274,731,507 out=74,555,739 elapsed=323.3s

  [5341/13157] intraday_2181.csv.gz  in=274,746,485 out=74,555,739 elapsed=323.3s

  [5342/13157] intraday_2185.csv.gz  in=274,759,559 out=74,555,739 elapsed=323.3s

  [5343/13157] intraday_2184.csv.gz  in=274,771,552 out=74,555,739 elapsed=323.3s

  [5344/13157] intraday_2186.csv.gz  in=274,783,697 out=74,555,739 elapsed=323.3s

  [5345/13157] intraday_2187.csv.gz  in=274,797,914 out=74,555,739 elapsed=323.3s

  [5346/13157] intraday_2188.csv.gz  in=274,809,748 out=74,555,739 elapsed=323.4s

  [5347/13157] intraday_2190.csv.gz  in=274,822,170 out=74,555,739 elapsed=323.4s

  [5348/13157] intraday_2191.csv.gz  in=274,836,646 out=74,555,739 elapsed=323.4s

  [5349/13157] intraday_2189.csv.gz  in=274,853,288 out=74,555,739 elapsed=323.4s

  [5350/13157] intraday_2193.csv.gz  in=274,865,966 out=74,555,739 elapsed=323.5s

  [5351/13157] intraday_2192.csv.gz  in=274,878,090 out=74,555,739 elapsed=323.5s

  [5352/13157] intraday_2195.csv.gz  in=274,892,779 out=74,555,739 elapsed=323.5s

  [5353/13157] intraday_2194.csv.gz  in=274,903,675 out=74,555,739 elapsed=323.5s

  [5354/13157] intraday_2196.csv.gz  in=274,916,948 out=74,555,739 elapsed=323.5s

  [5355/13157] intraday_2197.csv.gz  in=274,932,520 out=74,555,739 elapsed=323.5s

  [5356/13157] intraday_2198.csv.gz  in=274,944,780 out=74,555,739 elapsed=323.5s

  [5357/13157] intraday_2199.csv.gz  in=274,959,616 out=74,555,739 elapsed=323.5s

  [5358/13157] intraday_2200.csv.gz  in=274,972,866 out=74,555,739 elapsed=323.6s

  [5359/13157] intraday_2202.csv.gz  in=274,987,232 out=74,555,739 elapsed=323.6s

  [5360/13157] intraday_2203.csv.gz  in=275,002,771 out=74,555,739 elapsed=323.6s

  [5361/13157] intraday_2201.csv.gz  in=275,016,180 out=74,555,739 elapsed=323.6s

  [5362/13157] intraday_2207.csv.gz  in=275,027,851 out=74,555,739 elapsed=323.7s

  [5363/13157] intraday_2206.csv.gz  in=275,041,784 out=74,555,739 elapsed=323.7s

  [5364/13157] intraday_2204.csv.gz  in=275,056,047 out=74,555,739 elapsed=323.7s

  [5365/13157] intraday_2205.csv.gz  in=275,070,186 out=74,555,739 elapsed=323.7s

  [5366/13157] intraday_2210.csv.gz  in=275,084,881 out=74,555,739 elapsed=323.7s

  [5367/13157] intraday_2211.csv.gz  in=275,093,014 out=74,555,739 elapsed=323.8s

  [5368/13157] intraday_2208.csv.gz  in=275,105,712 out=74,555,739 elapsed=323.8s

  [5369/13157] intraday_2209.csv.gz  in=275,116,299 out=74,555,739 elapsed=323.8s

  [5370/13157] intraday_2212.csv.gz  in=275,125,884 out=74,555,739 elapsed=323.8s

  [5371/13157] intraday_2213.csv.gz  in=275,135,852 out=74,555,739 elapsed=323.8s

  [5372/13157] intraday_2215.csv.gz  in=275,149,698 out=74,555,739 elapsed=323.8s

  [5373/13157] intraday_2216.csv.gz  in=275,161,971 out=74,555,739 elapsed=323.8s

  [5374/13157] intraday_2214.csv.gz  in=275,177,248 out=74,555,739 elapsed=323.8s

  [5375/13157] intraday_2217.csv.gz  in=275,188,386 out=74,555,739 elapsed=323.9s

  [5376/13157] intraday_2218.csv.gz  in=275,202,192 out=74,555,739 elapsed=323.9s

  [5377/13157] intraday_2220.csv.gz  in=275,214,924 out=74,555,739 elapsed=323.9s

  [5378/13157] intraday_2221.csv.gz  in=275,227,705 out=74,555,739 elapsed=323.9s

  [5379/13157] intraday_2219.csv.gz  in=275,242,016 out=74,555,739 elapsed=323.9s

  [5380/13157] intraday_2222.csv.gz  in=275,256,329 out=74,555,739 elapsed=323.9s

  [5381/13157] intraday_2224.csv.gz  in=275,265,876 out=74,555,739 elapsed=323.9s

  [5382/13157] intraday_2225.csv.gz  in=275,277,630 out=74,555,739 elapsed=323.9s

  [5383/13157] intraday_2223.csv.gz  in=275,292,630 out=74,555,739 elapsed=323.9s

  [5384/13157] intraday_2226.csv.gz  in=275,306,881 out=74,555,739 elapsed=324.0s

  [5385/13157] intraday_2230.csv.gz  in=275,320,229 out=74,555,739 elapsed=324.0s

  [5386/13157] intraday_2229.csv.gz  in=275,332,851 out=74,555,739 elapsed=324.0s

  [5387/13157] intraday_2228.csv.gz  in=275,344,726 out=74,555,739 elapsed=324.0s

  [5388/13157] intraday_2227.csv.gz  in=275,362,363 out=74,555,739 elapsed=324.0s

  [5389/13157] intraday_2231.csv.gz  in=275,374,947 out=74,555,739 elapsed=324.0s

  [5390/13157] intraday_2234.csv.gz  in=275,388,234 out=74,555,739 elapsed=324.0s

  [5391/13157] intraday_2233.csv.gz  in=275,400,708 out=74,555,739 elapsed=324.1s

  [5392/13157] intraday_2232.csv.gz  in=275,420,685 out=74,555,739 elapsed=324.1s

  [5393/13157] intraday_2237.csv.gz  in=275,434,031 out=74,555,739 elapsed=324.1s

  [5394/13157] intraday_2238.csv.gz  in=275,446,690 out=74,555,739 elapsed=324.1s

  [5395/13157] intraday_2235.csv.gz  in=275,459,287 out=74,555,739 elapsed=324.1s

  [5396/13157] intraday_2236.csv.gz  in=275,471,968 out=74,555,739 elapsed=324.1s

  [5397/13157] intraday_2240.csv.gz  in=275,484,978 out=74,555,739 elapsed=324.2s

  [5398/13157] intraday_2242.csv.gz  in=275,496,943 out=74,555,739 elapsed=324.2s

  [5399/13157] intraday_2241.csv.gz  in=275,514,047 out=74,555,739 elapsed=324.2s

  [5400/13157] intraday_2239.csv.gz  in=275,523,135 out=74,555,739 elapsed=324.2s

  [5401/13157] intraday_2246.csv.gz  in=275,536,142 out=74,555,739 elapsed=324.3s

  [5402/13157] intraday_2244.csv.gz  in=275,550,727 out=74,555,739 elapsed=324.3s

  [5403/13157] intraday_2245.csv.gz  in=275,563,061 out=74,555,739 elapsed=324.3s

  [5404/13157] intraday_2243.csv.gz  in=275,577,608 out=74,555,739 elapsed=324.3s

  [5405/13157] intraday_2248.csv.gz  in=275,588,779 out=74,555,739 elapsed=324.3s

  [5406/13157] intraday_2247.csv.gz  in=275,602,012 out=74,555,739 elapsed=324.3s

  [5407/13157] intraday_2249.csv.gz  in=275,615,172 out=74,555,739 elapsed=324.3s

  [5408/13157] intraday_2250.csv.gz  in=275,626,752 out=74,555,739 elapsed=324.3s

  [5409/13157] intraday_2251.csv.gz  in=275,637,852 out=74,555,739 elapsed=324.4s

  [5410/13157] intraday_2254.csv.gz  in=275,652,459 out=74,555,739 elapsed=324.4s

  [5411/13157] intraday_2253.csv.gz  in=275,663,131 out=74,555,739 elapsed=324.4s

  [5412/13157] intraday_2252.csv.gz  in=275,678,259 out=74,555,739 elapsed=324.4s

  [5413/13157] intraday_2255.csv.gz  in=275,691,060 out=74,555,739 elapsed=324.5s

  [5414/13157] intraday_2256.csv.gz  in=275,705,105 out=74,555,739 elapsed=324.5s

  [5415/13157] intraday_2257.csv.gz  in=275,717,721 out=74,555,739 elapsed=324.5s

  [5416/13157] intraday_2258.csv.gz  in=275,730,178 out=74,555,739 elapsed=324.5s

  [5417/13157] intraday_2259.csv.gz  in=275,743,570 out=74,555,739 elapsed=324.6s

  [5418/13157] intraday_2261.csv.gz  in=275,756,235 out=74,555,739 elapsed=324.6s

  [5419/13157] intraday_2260.csv.gz  in=275,767,342 out=74,555,739 elapsed=324.6s

  [5420/13157] intraday_2262.csv.gz  in=275,783,886 out=74,555,739 elapsed=324.6s

  [5421/13157] intraday_2263.csv.gz  in=275,794,688 out=74,555,739 elapsed=324.6s

  [5422/13157] intraday_2265.csv.gz  in=275,806,566 out=74,555,739 elapsed=324.6s

  [5423/13157] intraday_2266.csv.gz  in=275,817,669 out=74,555,739 elapsed=324.6s

  [5424/13157] intraday_2264.csv.gz  in=275,830,272 out=74,555,739 elapsed=324.7s

  [5425/13157] intraday_2269.csv.gz  in=275,841,536 out=74,555,739 elapsed=324.7s

  [5426/13157] intraday_2267.csv.gz  in=275,854,851 out=74,555,739 elapsed=324.7s

  [5427/13157] intraday_2268.csv.gz  in=275,868,926 out=74,555,739 elapsed=324.7s

  [5428/13157] intraday_2270.csv.gz  in=275,880,126 out=74,555,739 elapsed=324.7s

  [5429/13157] intraday_2272.csv.gz  in=275,893,171 out=74,555,739 elapsed=324.8s

  [5430/13157] intraday_2274.csv.gz  in=275,905,293 out=74,555,739 elapsed=324.8s

  [5431/13157] intraday_2273.csv.gz  in=275,918,416 out=74,555,739 elapsed=324.8s

  [5432/13157] intraday_2271.csv.gz  in=275,931,597 out=74,555,739 elapsed=324.8s

  [5433/13157] intraday_2276.csv.gz  in=275,941,833 out=74,555,739 elapsed=324.9s

  [5434/13157] intraday_2275.csv.gz  in=275,953,624 out=74,555,739 elapsed=324.9s

  [5435/13157] intraday_2278.csv.gz  in=275,966,227 out=74,555,739 elapsed=324.9s

  [5436/13157] intraday_2277.csv.gz  in=275,980,450 out=74,555,739 elapsed=324.9s

  [5437/13157] intraday_2281.csv.gz  in=275,991,597 out=74,555,739 elapsed=325.0s

  [5438/13157] intraday_2279.csv.gz  in=276,007,603 out=74,555,739 elapsed=325.0s

  [5439/13157] intraday_2280.csv.gz  in=276,022,450 out=74,555,739 elapsed=325.0s

  [5440/13157] intraday_2282.csv.gz  in=276,034,384 out=74,555,739 elapsed=325.0s

  [5441/13157] intraday_2283.csv.gz  in=276,046,420 out=74,555,739 elapsed=325.0s

  [5442/13157] intraday_2286.csv.gz  in=276,057,225 out=74,555,739 elapsed=325.0s

  [5443/13157] intraday_2284.csv.gz  in=276,069,974 out=74,555,739 elapsed=325.0s

  [5444/13157] intraday_2285.csv.gz  in=276,085,014 out=74,555,739 elapsed=325.1s

  [5445/13157] intraday_2288.csv.gz  in=276,096,716 out=74,555,739 elapsed=325.1s

  [5446/13157] intraday_2287.csv.gz  in=276,112,320 out=74,555,739 elapsed=325.1s

  [5447/13157] intraday_2290.csv.gz  in=276,123,728 out=74,555,739 elapsed=325.1s

  [5448/13157] intraday_2289.csv.gz  in=276,137,940 out=74,555,739 elapsed=325.1s

  [5449/13157] intraday_2294.csv.gz  in=276,150,325 out=74,555,739 elapsed=325.2s

  [5450/13157] intraday_2293.csv.gz  in=276,162,092 out=74,555,739 elapsed=325.2s

  [5451/13157] intraday_2291.csv.gz  in=276,175,455 out=74,555,739 elapsed=325.2s

  [5452/13157] intraday_2292.csv.gz  in=276,185,868 out=74,555,739 elapsed=325.2s

  [5453/13157] intraday_2298.csv.gz  in=276,195,856 out=74,555,739 elapsed=325.2s

  [5454/13157] intraday_2295.csv.gz  in=276,209,498 out=74,555,739 elapsed=325.3s

  [5455/13157] intraday_2296.csv.gz  in=276,222,660 out=74,555,739 elapsed=325.3s

  [5456/13157] intraday_2297.csv.gz  in=276,235,909 out=74,555,739 elapsed=325.3s

  [5457/13157] intraday_2300.csv.gz  in=276,247,794 out=74,555,739 elapsed=325.3s

  [5458/13157] intraday_2301.csv.gz  in=276,263,672 out=74,555,739 elapsed=325.3s

  [5459/13157] intraday_2299.csv.gz  in=276,285,599 out=74,555,739 elapsed=325.3s

  [5460/13157] intraday_2302.csv.gz  in=276,306,482 out=74,555,739 elapsed=325.3s

  [5461/13157] intraday_2304.csv.gz  in=276,318,961 out=74,555,739 elapsed=325.4s

  [5462/13157] intraday_2303.csv.gz  in=276,334,560 out=74,555,739 elapsed=325.4s

  [5463/13157] intraday_2306.csv.gz  in=276,347,919 out=74,555,739 elapsed=325.4s

  [5464/13157] intraday_2305.csv.gz  in=276,362,080 out=74,555,739 elapsed=325.4s

  [5465/13157] intraday_2309.csv.gz  in=276,374,760 out=74,555,739 elapsed=325.4s

  [5466/13157] intraday_2307.csv.gz  in=276,389,550 out=74,555,739 elapsed=325.4s

  [5467/13157] intraday_2308.csv.gz  in=276,401,672 out=74,555,739 elapsed=325.4s

  [5468/13157] intraday_2310.csv.gz  in=276,415,104 out=74,555,739 elapsed=325.4s

  [5469/13157] intraday_2312.csv.gz  in=276,426,859 out=74,555,739 elapsed=325.5s

  [5470/13157] intraday_2311.csv.gz  in=276,440,279 out=74,555,739 elapsed=325.5s

  [5471/13157] intraday_2314.csv.gz  in=276,455,668 out=74,555,739 elapsed=325.5s

  [5472/13157] intraday_2313.csv.gz  in=276,468,917 out=74,555,739 elapsed=325.5s

  [5473/13157] intraday_2317.csv.gz  in=276,481,379 out=74,555,739 elapsed=325.5s

  [5474/13157] intraday_2315.csv.gz  in=276,493,285 out=74,555,739 elapsed=325.6s

  [5475/13157] intraday_2318.csv.gz  in=276,505,446 out=74,555,739 elapsed=325.6s

  [5476/13157] intraday_2316.csv.gz  in=276,518,537 out=74,555,739 elapsed=325.6s

  [5477/13157] intraday_2320.csv.gz  in=276,534,104 out=74,555,739 elapsed=325.7s

  [5478/13157] intraday_2321.csv.gz  in=276,547,129 out=74,555,739 elapsed=325.7s

  [5479/13157] intraday_2322.csv.gz  in=276,560,366 out=74,555,739 elapsed=325.7s

  [5480/13157] intraday_2319.csv.gz  in=276,574,994 out=74,555,739 elapsed=325.7s

  [5481/13157] intraday_2323.csv.gz  in=276,588,366 out=74,555,739 elapsed=325.8s

  [5482/13157] intraday_2325.csv.gz  in=276,600,888 out=74,555,739 elapsed=325.8s

  [5483/13157] intraday_2324.csv.gz  in=276,613,186 out=74,555,739 elapsed=325.8s

  [5484/13157] intraday_2326.csv.gz  in=276,626,527 out=74,555,739 elapsed=325.8s

  [5485/13157] intraday_2329.csv.gz  in=276,639,213 out=74,555,739 elapsed=325.9s

  [5486/13157] intraday_2327.csv.gz  in=276,654,291 out=74,555,739 elapsed=325.9s

  [5487/13157] intraday_2328.csv.gz  in=276,670,779 out=74,555,739 elapsed=325.9s

  [5488/13157] intraday_2330.csv.gz  in=276,684,585 out=74,555,739 elapsed=326.0s

  [5489/13157] intraday_2331.csv.gz  in=276,697,574 out=74,555,739 elapsed=326.0s

  [5490/13157] intraday_2332.csv.gz  in=276,709,617 out=74,555,739 elapsed=326.0s

  [5491/13157] intraday_2333.csv.gz  in=276,721,432 out=74,555,739 elapsed=326.0s

  [5492/13157] intraday_2335.csv.gz  in=276,734,056 out=74,555,739 elapsed=326.0s

  [5493/13157] intraday_2334.csv.gz  in=276,752,071 out=74,555,739 elapsed=326.0s

  [5494/13157] intraday_2336.csv.gz  in=276,768,738 out=74,555,739 elapsed=326.1s

  [5495/13157] intraday_2338.csv.gz  in=276,784,030 out=74,555,739 elapsed=326.1s

  [5496/13157] intraday_2337.csv.gz  in=276,795,137 out=74,555,739 elapsed=326.1s

  [5497/13157] intraday_2339.csv.gz  in=276,807,537 out=74,555,739 elapsed=326.1s

  [5498/13157] intraday_2343.csv.gz  in=276,822,054 out=74,555,739 elapsed=326.3s

  [5499/13157] intraday_2341.csv.gz  in=276,835,393 out=74,555,739 elapsed=326.3s

  [5500/13157] intraday_2340.csv.gz  in=276,849,776 out=74,555,739 elapsed=326.3s

  [5501/13157] intraday_2342.csv.gz  in=276,870,993 out=74,555,739 elapsed=326.3s

  [5502/13157] intraday_2347.csv.gz  in=276,882,618 out=74,555,739 elapsed=326.4s

  [5503/13157] intraday_2346.csv.gz  in=276,894,216 out=74,555,739 elapsed=326.5s

  [5504/13157] intraday_2345.csv.gz  in=276,909,159 out=74,555,739 elapsed=326.5s

  [5505/13157] intraday_2344.csv.gz  in=276,923,122 out=74,555,739 elapsed=326.5s

  [5506/13157] intraday_2348.csv.gz  in=276,936,688 out=74,555,739 elapsed=326.5s

  [5507/13157] intraday_2351.csv.gz  in=276,945,635 out=74,555,739 elapsed=326.8s

  [5508/13157] intraday_2350.csv.gz  in=276,954,701 out=74,555,739 elapsed=326.8s

  [5509/13157] intraday_2353.csv.gz  in=276,956,110 out=74,555,739 elapsed=326.9s

  [5510/13157] intraday_2349.csv.gz  in=276,969,956 out=74,555,739 elapsed=327.0s

  [5511/13157] intraday_2352.csv.gz  in=276,981,819 out=74,555,739 elapsed=327.0s

  [5512/13157] intraday_2354.csv.gz  in=276,998,186 out=74,555,739 elapsed=327.0s

  [5513/13157] intraday_2357.csv.gz  in=277,009,437 out=74,555,739 elapsed=327.2s

  [5514/13157] intraday_2356.csv.gz  in=277,021,999 out=74,555,739 elapsed=327.2s

  [5515/13157] intraday_2355.csv.gz  in=277,036,093 out=74,555,739 elapsed=327.2s

  [5516/13157] intraday_2358.csv.gz  in=277,051,142 out=74,555,739 elapsed=327.2s

  [5517/13157] intraday_2360.csv.gz  in=277,064,110 out=74,555,739 elapsed=327.3s

  [5518/13157] intraday_2361.csv.gz  in=277,076,800 out=74,555,739 elapsed=327.3s

  [5519/13157] intraday_2362.csv.gz  in=277,094,569 out=74,555,739 elapsed=327.3s

  [5520/13157] intraday_2359.csv.gz  in=277,116,372 out=74,555,739 elapsed=327.3s

  [5521/13157] intraday_2364.csv.gz  in=277,126,187 out=74,555,739 elapsed=327.4s

  [5522/13157] intraday_2365.csv.gz  in=277,138,834 out=74,555,739 elapsed=327.4s

  [5523/13157] intraday_2363.csv.gz  in=277,153,911 out=74,555,739 elapsed=327.4s

  [5524/13157] intraday_2366.csv.gz  in=277,167,838 out=74,555,739 elapsed=327.4s

  [5525/13157] intraday_2367.csv.gz  in=277,178,503 out=74,555,739 elapsed=327.5s

  [5526/13157] intraday_2369.csv.gz  in=277,191,064 out=74,555,739 elapsed=327.6s

  [5527/13157] intraday_2370.csv.gz  in=277,204,122 out=74,555,739 elapsed=327.6s

  [5528/13157] intraday_2368.csv.gz  in=277,215,585 out=74,555,739 elapsed=327.6s

  [5529/13157] intraday_2373.csv.gz  in=277,227,651 out=74,555,739 elapsed=327.7s

  [5530/13157] intraday_2372.csv.gz  in=277,238,566 out=74,555,739 elapsed=327.7s

  [5531/13157] intraday_2371.csv.gz  in=277,251,119 out=74,555,739 elapsed=327.7s

  [5532/13157] intraday_2374.csv.gz  in=277,265,184 out=74,555,739 elapsed=327.7s

  [5533/13157] intraday_2376.csv.gz  in=277,277,563 out=74,555,739 elapsed=327.8s

  [5534/13157] intraday_2378.csv.gz  in=277,290,489 out=74,555,739 elapsed=327.8s

  [5535/13157] intraday_2375.csv.gz  in=277,302,521 out=74,555,739 elapsed=327.8s

  [5536/13157] intraday_2377.csv.gz  in=277,320,800 out=74,555,739 elapsed=327.8s

  [5537/13157] intraday_2379.csv.gz  in=277,330,285 out=74,555,739 elapsed=327.8s

  [5538/13157] intraday_2382.csv.gz  in=277,343,750 out=74,555,739 elapsed=327.8s

  [5539/13157] intraday_2381.csv.gz  in=277,359,883 out=74,555,739 elapsed=327.8s

  [5540/13157] intraday_2380.csv.gz  in=277,372,245 out=74,555,739 elapsed=327.8s

  [5541/13157] intraday_2383.csv.gz  in=277,387,570 out=74,555,739 elapsed=327.9s

  [5542/13157] intraday_2385.csv.gz  in=277,399,628 out=74,555,739 elapsed=327.9s

  [5543/13157] intraday_2386.csv.gz  in=277,411,930 out=74,555,739 elapsed=327.9s

  [5544/13157] intraday_2384.csv.gz  in=277,426,447 out=74,555,739 elapsed=327.9s

  [5545/13157] intraday_2388.csv.gz  in=277,438,074 out=74,555,739 elapsed=328.0s

  [5546/13157] intraday_2387.csv.gz  in=277,461,350 out=74,555,739 elapsed=328.0s

  [5547/13157] intraday_2389.csv.gz  in=277,473,647 out=74,555,739 elapsed=328.0s

  [5548/13157] intraday_2390.csv.gz  in=277,485,343 out=74,555,739 elapsed=328.0s

  [5549/13157] intraday_2391.csv.gz  in=277,496,740 out=74,555,739 elapsed=328.0s

  [5550/13157] intraday_2392.csv.gz  in=277,508,419 out=74,555,739 elapsed=328.1s

  [5551/13157] intraday_2394.csv.gz  in=277,522,801 out=74,555,739 elapsed=328.1s

  [5552/13157] intraday_2393.csv.gz  in=277,534,747 out=74,555,739 elapsed=328.1s

  [5553/13157] intraday_2395.csv.gz  in=277,548,747 out=74,555,739 elapsed=328.1s

  [5554/13157] intraday_2396.csv.gz  in=277,560,984 out=74,555,739 elapsed=328.2s

  [5555/13157] intraday_2399.csv.gz  in=277,574,664 out=74,555,739 elapsed=328.2s

  [5556/13157] intraday_2397.csv.gz  in=277,588,338 out=74,555,739 elapsed=328.2s

  [5557/13157] intraday_2398.csv.gz  in=277,603,696 out=74,555,739 elapsed=328.2s

  [5558/13157] intraday_2402.csv.gz  in=277,615,796 out=74,555,739 elapsed=328.3s

  [5559/13157] intraday_2403.csv.gz  in=277,628,003 out=74,555,739 elapsed=328.3s

  [5560/13157] intraday_2401.csv.gz  in=277,648,547 out=74,555,739 elapsed=328.3s

  [5561/13157] intraday_2400.csv.gz  in=277,665,832 out=74,555,739 elapsed=328.3s

  [5562/13157] intraday_2405.csv.gz  in=277,678,010 out=74,555,739 elapsed=328.3s

  [5563/13157] intraday_2407.csv.gz  in=277,691,651 out=74,555,739 elapsed=328.3s

  [5564/13157] intraday_2406.csv.gz  in=277,703,442 out=74,555,739 elapsed=328.3s

  [5565/13157] intraday_2404.csv.gz  in=277,723,806 out=74,555,739 elapsed=328.3s

  [5566/13157] intraday_2409.csv.gz  in=277,737,106 out=74,555,739 elapsed=328.5s

  [5567/13157] intraday_2411.csv.gz  in=277,750,813 out=74,555,739 elapsed=328.5s

  [5568/13157] intraday_2408.csv.gz  in=277,766,983 out=74,555,739 elapsed=328.5s

  [5569/13157] intraday_2410.csv.gz  in=277,787,121 out=74,555,739 elapsed=328.5s

  [5570/13157] intraday_2412.csv.gz  in=277,799,754 out=74,555,739 elapsed=328.7s

  [5571/13157] intraday_2413.csv.gz  in=277,813,154 out=74,555,739 elapsed=328.7s

  [5572/13157] intraday_2414.csv.gz  in=277,828,191 out=74,555,739 elapsed=328.7s

  [5573/13157] intraday_2415.csv.gz  in=277,840,728 out=74,555,739 elapsed=328.7s

  [5574/13157] intraday_2418.csv.gz  in=277,854,914 out=74,555,739 elapsed=328.9s

  [5575/13157] intraday_2419.csv.gz  in=277,869,294 out=74,555,739 elapsed=328.9s

  [5576/13157] intraday_2417.csv.gz  in=277,897,813 out=74,555,739 elapsed=328.9s

  [5577/13157] intraday_2416.csv.gz  in=277,918,066 out=74,555,739 elapsed=328.9s

  [5578/13157] intraday_2420.csv.gz  in=277,932,521 out=74,555,739 elapsed=329.0s

  [5579/13157] intraday_2422.csv.gz  in=277,942,491 out=74,555,739 elapsed=329.0s

  [5580/13157] intraday_2423.csv.gz  in=277,954,470 out=74,555,739 elapsed=329.0s

  [5581/13157] intraday_2421.csv.gz  in=277,970,097 out=74,555,739 elapsed=329.0s

  [5582/13157] intraday_2426.csv.gz  in=277,979,630 out=74,555,739 elapsed=329.1s

  [5583/13157] intraday_2424.csv.gz  in=277,992,241 out=74,555,739 elapsed=329.1s

  [5584/13157] intraday_2427.csv.gz  in=278,004,706 out=74,555,739 elapsed=329.2s

  [5585/13157] intraday_2425.csv.gz  in=278,019,353 out=74,555,739 elapsed=329.2s

  [5586/13157] intraday_2428.csv.gz  in=278,030,166 out=74,555,739 elapsed=329.2s

  [5587/13157] intraday_2431.csv.gz  in=278,042,539 out=74,555,739 elapsed=329.2s

  [5588/13157] intraday_2430.csv.gz  in=278,054,683 out=74,555,739 elapsed=329.2s

  [5589/13157] intraday_2432.csv.gz  in=278,066,257 out=74,555,739 elapsed=329.2s

  [5590/13157] intraday_2429.csv.gz  in=278,082,843 out=74,555,739 elapsed=329.2s

  [5591/13157] intraday_2433.csv.gz  in=278,093,579 out=74,555,739 elapsed=329.3s

  [5592/13157] intraday_2434.csv.gz  in=278,104,929 out=74,555,739 elapsed=329.3s

  [5593/13157] intraday_2437.csv.gz  in=278,117,582 out=74,555,739 elapsed=329.3s

  [5594/13157] intraday_2435.csv.gz  in=278,132,232 out=74,555,739 elapsed=329.3s

  [5595/13157] intraday_2436.csv.gz  in=278,157,521 out=74,555,739 elapsed=329.3s

  [5596/13157] intraday_2438.csv.gz  in=278,169,862 out=74,555,739 elapsed=329.3s

  [5597/13157] intraday_2439.csv.gz  in=278,181,215 out=74,555,739 elapsed=329.3s

  [5598/13157] intraday_2440.csv.gz  in=278,193,564 out=74,555,739 elapsed=329.3s

  [5599/13157] intraday_2442.csv.gz  in=278,206,318 out=74,555,739 elapsed=329.3s

  [5600/13157] intraday_2441.csv.gz  in=278,221,051 out=74,555,739 elapsed=329.3s

  [5601/13157] intraday_2446.csv.gz  in=278,235,049 out=74,555,739 elapsed=329.4s

  [5602/13157] intraday_2443.csv.gz  in=278,248,781 out=74,555,739 elapsed=329.4s

  [5603/13157] intraday_2444.csv.gz  in=278,261,639 out=74,555,739 elapsed=329.4s

  [5604/13157] intraday_2445.csv.gz  in=278,276,072 out=74,555,739 elapsed=329.4s

  [5605/13157] intraday_2447.csv.gz  in=278,290,704 out=74,555,739 elapsed=329.4s

  [5606/13157] intraday_2448.csv.gz  in=278,304,609 out=74,555,739 elapsed=329.4s

  [5607/13157] intraday_2450.csv.gz  in=278,317,258 out=74,555,739 elapsed=329.5s

  [5608/13157] intraday_2449.csv.gz  in=278,328,659 out=74,555,739 elapsed=329.5s

  [5609/13157] intraday_2451.csv.gz  in=278,342,575 out=74,555,739 elapsed=329.5s

  [5610/13157] intraday_2453.csv.gz  in=278,353,865 out=74,555,739 elapsed=329.6s

  [5611/13157] intraday_2452.csv.gz  in=278,367,168 out=74,555,739 elapsed=329.6s

  [5612/13157] intraday_2454.csv.gz  in=278,381,006 out=74,555,739 elapsed=329.6s

  [5613/13157] intraday_2455.csv.gz  in=278,396,133 out=74,555,739 elapsed=329.6s

  [5614/13157] intraday_2456.csv.gz  in=278,411,088 out=74,555,739 elapsed=329.7s

  [5615/13157] intraday_2458.csv.gz  in=278,421,322 out=74,555,739 elapsed=329.7s

  [5616/13157] intraday_2459.csv.gz  in=278,434,089 out=74,555,739 elapsed=329.7s

  [5617/13157] intraday_2457.csv.gz  in=278,450,352 out=74,555,739 elapsed=329.7s

  [5618/13157] intraday_2462.csv.gz  in=278,463,732 out=74,555,739 elapsed=329.9s

  [5619/13157] intraday_2460.csv.gz  in=278,477,892 out=74,555,739 elapsed=329.9s

  [5620/13157] intraday_2463.csv.gz  in=278,492,325 out=74,555,739 elapsed=329.9s

  [5621/13157] intraday_2461.csv.gz  in=278,507,261 out=74,555,739 elapsed=329.9s

  [5622/13157] intraday_2465.csv.gz  in=278,520,693 out=74,555,739 elapsed=330.1s

  [5623/13157] intraday_2466.csv.gz  in=278,533,742 out=74,555,739 elapsed=330.1s

  [5624/13157] intraday_2464.csv.gz  in=278,545,921 out=74,555,739 elapsed=330.1s

  [5625/13157] intraday_2467.csv.gz  in=278,560,250 out=74,555,739 elapsed=330.1s

  [5626/13157] intraday_2468.csv.gz  in=278,572,070 out=74,555,739 elapsed=330.3s

  [5627/13157] intraday_2470.csv.gz  in=278,584,538 out=74,555,739 elapsed=330.3s

  [5628/13157] intraday_2469.csv.gz  in=278,601,766 out=74,555,739 elapsed=330.3s

  [5629/13157] intraday_2471.csv.gz  in=278,615,979 out=74,555,739 elapsed=330.3s

  [5630/13157] intraday_2472.csv.gz  in=278,631,604 out=74,555,739 elapsed=330.5s

  [5631/13157] intraday_2473.csv.gz  in=278,644,711 out=74,555,739 elapsed=330.5s

  [5632/13157] intraday_2474.csv.gz  in=278,655,670 out=74,555,739 elapsed=330.5s

  [5633/13157] intraday_2475.csv.gz  in=278,670,168 out=74,555,739 elapsed=330.5s

  [5634/13157] intraday_2478.csv.gz  in=278,682,114 out=74,555,739 elapsed=330.5s

  [5635/13157] intraday_2479.csv.gz  in=278,696,216 out=74,555,739 elapsed=330.5s

  [5636/13157] intraday_2477.csv.gz  in=278,712,350 out=74,555,739 elapsed=330.5s

  [5637/13157] intraday_2476.csv.gz  in=278,725,714 out=74,555,739 elapsed=330.5s

  [5638/13157] intraday_2480.csv.gz  in=278,739,695 out=74,555,739 elapsed=330.6s

  [5639/13157] intraday_2481.csv.gz  in=278,755,229 out=74,555,739 elapsed=330.6s

  [5640/13157] intraday_2482.csv.gz  in=278,769,513 out=74,555,739 elapsed=330.6s

  [5641/13157] intraday_2483.csv.gz  in=278,784,415 out=74,555,739 elapsed=330.6s

  [5642/13157] intraday_2487.csv.gz  in=278,796,204 out=74,555,739 elapsed=330.6s

  [5643/13157] intraday_2485.csv.gz  in=278,809,579 out=74,555,739 elapsed=330.6s

  [5644/13157] intraday_2484.csv.gz  in=278,825,391 out=74,555,739 elapsed=330.6s

  [5645/13157] intraday_2486.csv.gz  in=278,839,748 out=74,555,739 elapsed=330.7s

  [5646/13157] intraday_2488.csv.gz  in=278,851,964 out=74,555,739 elapsed=330.7s

  [5647/13157] intraday_2491.csv.gz  in=278,860,681 out=74,555,739 elapsed=330.7s

  [5648/13157] intraday_2489.csv.gz  in=278,872,486 out=74,555,739 elapsed=330.7s

  [5649/13157] intraday_2490.csv.gz  in=278,887,161 out=74,555,739 elapsed=330.7s

  [5650/13157] intraday_2492.csv.gz  in=278,895,223 out=74,555,739 elapsed=330.7s

  [5651/13157] intraday_2493.csv.gz  in=278,906,712 out=74,555,739 elapsed=330.7s

  [5652/13157] intraday_2495.csv.gz  in=278,920,627 out=74,555,739 elapsed=330.7s

  [5653/13157] intraday_2496.csv.gz  in=278,932,440 out=74,555,739 elapsed=330.7s

  [5654/13157] intraday_2494.csv.gz  in=278,947,737 out=74,555,739 elapsed=330.7s

  [5655/13157] intraday_2497.csv.gz  in=278,958,726 out=74,555,739 elapsed=330.8s

  [5656/13157] intraday_2498.csv.gz  in=278,973,470 out=74,555,739 elapsed=330.8s

  [5657/13157] intraday_2500.csv.gz  in=278,985,920 out=74,555,739 elapsed=330.8s

  [5658/13157] intraday_2499.csv.gz  in=278,999,823 out=74,555,739 elapsed=330.8s

  [5659/13157] intraday_2501.csv.gz  in=279,011,683 out=74,555,739 elapsed=330.8s

  [5660/13157] intraday_2504.csv.gz  in=279,020,772 out=74,555,739 elapsed=330.8s

  [5661/13157] intraday_2502.csv.gz  in=279,034,131 out=74,555,739 elapsed=330.8s

  [5662/13157] intraday_2503.csv.gz  in=279,048,555 out=74,555,739 elapsed=330.8s

  [5663/13157] intraday_2505.csv.gz  in=279,059,721 out=74,555,739 elapsed=331.0s

  [5664/13157] intraday_2507.csv.gz  in=279,070,461 out=74,555,739 elapsed=331.0s

  [5665/13157] intraday_2508.csv.gz  in=279,081,797 out=74,555,739 elapsed=331.0s

  [5666/13157] intraday_2506.csv.gz  in=279,094,731 out=74,555,739 elapsed=331.0s

  [5667/13157] intraday_2509.csv.gz  in=279,106,616 out=74,555,739 elapsed=331.0s

  [5668/13157] intraday_2511.csv.gz  in=279,118,625 out=74,555,739 elapsed=331.0s

  [5669/13157] intraday_2510.csv.gz  in=279,130,751 out=74,555,739 elapsed=331.0s

  [5670/13157] intraday_2512.csv.gz  in=279,142,507 out=74,555,739 elapsed=331.2s

  [5671/13157] intraday_2514.csv.gz  in=279,155,553 out=74,555,739 elapsed=331.2s

  [5672/13157] intraday_2515.csv.gz  in=279,167,284 out=74,555,739 elapsed=331.2s

  [5673/13157] intraday_2513.csv.gz  in=279,178,561 out=74,555,739 elapsed=331.2s

  [5674/13157] intraday_2519.csv.gz  in=279,187,378 out=74,555,739 elapsed=331.3s

  [5675/13157] intraday_2517.csv.gz  in=279,199,964 out=74,555,739 elapsed=331.4s

  [5676/13157] intraday_2516.csv.gz  in=279,212,095 out=74,555,739 elapsed=331.4s

  [5677/13157] intraday_2518.csv.gz  in=279,223,990 out=74,555,739 elapsed=331.4s

  [5678/13157] intraday_2520.csv.gz  in=279,235,826 out=74,555,739 elapsed=331.4s

  [5679/13157] intraday_2523.csv.gz  in=279,250,301 out=74,555,739 elapsed=331.4s

  [5680/13157] intraday_2522.csv.gz  in=279,262,700 out=74,555,739 elapsed=331.4s

  [5681/13157] intraday_2524.csv.gz  in=279,276,071 out=74,555,739 elapsed=331.4s

  [5682/13157] intraday_2521.csv.gz  in=279,289,542 out=74,555,739 elapsed=331.4s

  [5683/13157] intraday_2526.csv.gz  in=279,302,207 out=74,555,739 elapsed=331.5s

  [5684/13157] intraday_2525.csv.gz  in=279,313,578 out=74,555,739 elapsed=331.5s

  [5685/13157] intraday_2527.csv.gz  in=279,326,409 out=74,555,739 elapsed=331.5s

  [5686/13157] intraday_2528.csv.gz  in=279,337,529 out=74,555,739 elapsed=331.5s

  [5687/13157] intraday_2529.csv.gz  in=279,350,615 out=74,555,739 elapsed=331.5s

  [5688/13157] intraday_2530.csv.gz  in=279,362,167 out=74,555,739 elapsed=331.5s

  [5689/13157] intraday_2532.csv.gz  in=279,374,440 out=74,555,739 elapsed=331.5s

  [5690/13157] intraday_2531.csv.gz  in=279,384,817 out=74,555,739 elapsed=331.5s

  [5691/13157] intraday_2533.csv.gz  in=279,394,770 out=74,555,739 elapsed=331.6s

  [5692/13157] intraday_2534.csv.gz  in=279,409,832 out=74,555,739 elapsed=331.6s

  [5693/13157] intraday_2535.csv.gz  in=279,421,985 out=74,555,739 elapsed=331.6s

  [5694/13157] intraday_2536.csv.gz  in=279,436,331 out=74,555,739 elapsed=331.6s

  [5695/13157] intraday_2537.csv.gz  in=279,448,116 out=74,555,739 elapsed=331.6s

  [5696/13157] intraday_2538.csv.gz  in=279,460,401 out=74,555,739 elapsed=331.6s

  [5697/13157] intraday_2539.csv.gz  in=279,472,454 out=74,555,739 elapsed=331.6s

  [5698/13157] intraday_2540.csv.gz  in=279,482,713 out=74,555,739 elapsed=331.6s

  [5699/13157] intraday_2541.csv.gz  in=279,494,822 out=74,555,739 elapsed=331.7s

  [5700/13157] intraday_2543.csv.gz  in=279,505,022 out=74,555,739 elapsed=331.7s

  [5701/13157] intraday_2542.csv.gz  in=279,517,119 out=74,555,739 elapsed=331.7s

  [5702/13157] intraday_2544.csv.gz  in=279,530,154 out=74,555,739 elapsed=331.7s

  [5703/13157] intraday_2546.csv.gz  in=279,541,518 out=74,555,739 elapsed=331.8s

  [5704/13157] intraday_2545.csv.gz  in=279,552,428 out=74,555,739 elapsed=331.8s

  [5705/13157] intraday_2547.csv.gz  in=279,566,039 out=74,555,739 elapsed=331.8s

  [5706/13157] intraday_2548.csv.gz  in=279,580,035 out=74,555,739 elapsed=331.8s

  [5707/13157] intraday_2549.csv.gz  in=279,590,942 out=74,555,739 elapsed=331.8s

  [5708/13157] intraday_2552.csv.gz  in=279,604,481 out=74,555,739 elapsed=331.8s

  [5709/13157] intraday_2550.csv.gz  in=279,615,484 out=74,555,739 elapsed=331.8s

  [5710/13157] intraday_2551.csv.gz  in=279,628,886 out=74,555,739 elapsed=331.8s

  [5711/13157] intraday_2553.csv.gz  in=279,641,330 out=74,555,739 elapsed=331.9s

  [5712/13157] intraday_2554.csv.gz  in=279,652,094 out=74,555,739 elapsed=331.9s

  [5713/13157] intraday_2555.csv.gz  in=279,663,029 out=74,555,739 elapsed=331.9s

  [5714/13157] intraday_2556.csv.gz  in=279,672,915 out=74,555,739 elapsed=331.9s

  [5715/13157] intraday_2557.csv.gz  in=279,687,371 out=74,555,739 elapsed=331.9s

  [5716/13157] intraday_2558.csv.gz  in=279,699,192 out=74,555,739 elapsed=332.0s

  [5717/13157] intraday_2560.csv.gz  in=279,712,183 out=74,555,739 elapsed=332.0s

  [5718/13157] intraday_2559.csv.gz  in=279,725,262 out=74,555,739 elapsed=332.0s

  [5719/13157] intraday_2561.csv.gz  in=279,736,718 out=74,555,739 elapsed=332.0s

  [5720/13157] intraday_2562.csv.gz  in=279,748,339 out=74,555,739 elapsed=332.0s

  [5721/13157] intraday_2564.csv.gz  in=279,758,920 out=74,555,739 elapsed=332.0s

  [5722/13157] intraday_2563.csv.gz  in=279,771,456 out=74,555,739 elapsed=332.0s

  [5723/13157] intraday_2566.csv.gz  in=279,781,166 out=74,555,739 elapsed=332.0s

  [5724/13157] intraday_2565.csv.gz  in=279,793,815 out=74,555,739 elapsed=332.1s

  [5725/13157] intraday_2567.csv.gz  in=279,805,460 out=74,555,739 elapsed=332.1s

  [5726/13157] intraday_2568.csv.gz  in=279,817,758 out=74,555,739 elapsed=332.1s

  [5727/13157] intraday_2569.csv.gz  in=279,829,444 out=74,555,739 elapsed=332.1s

  [5728/13157] intraday_2570.csv.gz  in=279,841,123 out=74,555,739 elapsed=332.1s

  [5729/13157] intraday_2572.csv.gz  in=279,851,451 out=74,555,739 elapsed=332.1s

  [5730/13157] intraday_2571.csv.gz  in=279,863,642 out=74,555,739 elapsed=332.2s

  [5731/13157] intraday_2573.csv.gz  in=279,874,809 out=74,555,739 elapsed=332.2s

  [5732/13157] intraday_2574.csv.gz  in=279,886,595 out=74,555,739 elapsed=332.2s

  [5733/13157] intraday_2575.csv.gz  in=279,901,062 out=74,555,739 elapsed=332.2s

  [5734/13157] intraday_2577.csv.gz  in=279,913,449 out=74,555,739 elapsed=332.2s

  [5735/13157] intraday_2576.csv.gz  in=279,925,196 out=74,555,739 elapsed=332.2s

  [5736/13157] intraday_2578.csv.gz  in=279,937,724 out=74,555,739 elapsed=332.3s

  [5737/13157] intraday_2579.csv.gz  in=279,949,461 out=74,555,739 elapsed=332.3s

  [5738/13157] intraday_2580.csv.gz  in=279,961,878 out=74,555,739 elapsed=332.3s

  [5739/13157] intraday_2582.csv.gz  in=279,972,526 out=74,555,739 elapsed=332.3s

  [5740/13157] intraday_2581.csv.gz  in=279,987,810 out=74,555,739 elapsed=332.3s

  [5741/13157] intraday_2584.csv.gz  in=280,000,459 out=74,555,739 elapsed=332.5s

  [5742/13157] intraday_2585.csv.gz  in=280,013,886 out=74,555,739 elapsed=332.5s

  [5743/13157] intraday_2586.csv.gz  in=280,027,606 out=74,555,739 elapsed=332.5s

  [5744/13157] intraday_2583.csv.gz  in=280,042,073 out=74,555,739 elapsed=332.5s

  [5745/13157] intraday_2589.csv.gz  in=280,054,522 out=74,555,739 elapsed=332.8s

  [5746/13157] intraday_2587.csv.gz  in=280,067,341 out=74,555,739 elapsed=332.8s

  [5747/13157] intraday_2588.csv.gz  in=280,079,470 out=74,555,739 elapsed=332.8s

  [5748/13157] intraday_2590.csv.gz  in=280,090,022 out=74,555,739 elapsed=332.8s

  [5749/13157] intraday_2592.csv.gz  in=280,101,092 out=74,555,739 elapsed=333.1s

  [5750/13157] intraday_2591.csv.gz  in=280,112,618 out=74,555,739 elapsed=333.1s

  [5751/13157] intraday_2593.csv.gz  in=280,125,900 out=74,555,739 elapsed=333.1s

  [5752/13157] intraday_2594.csv.gz  in=280,136,951 out=74,555,739 elapsed=333.1s

  [5753/13157] intraday_2598.csv.gz  in=280,148,049 out=74,555,739 elapsed=333.3s

  [5754/13157] intraday_2595.csv.gz  in=280,161,193 out=74,555,739 elapsed=333.3s

  [5755/13157] intraday_2596.csv.gz  in=280,173,392 out=74,555,739 elapsed=333.3s

  [5756/13157] intraday_2597.csv.gz  in=280,186,904 out=74,555,739 elapsed=333.3s

  [5757/13157] intraday_2600.csv.gz  in=280,201,676 out=74,555,739 elapsed=333.5s

  [5758/13157] intraday_2599.csv.gz  in=280,214,569 out=74,555,739 elapsed=333.5s

  [5759/13157] intraday_2601.csv.gz  in=280,228,320 out=74,555,739 elapsed=333.5s

  [5760/13157] intraday_2602.csv.gz  in=280,241,593 out=74,555,739 elapsed=333.5s

  [5761/13157] intraday_2603.csv.gz  in=280,255,156 out=74,555,739 elapsed=333.6s

  [5762/13157] intraday_2604.csv.gz  in=280,267,073 out=74,555,739 elapsed=333.6s

  [5763/13157] intraday_2605.csv.gz  in=280,279,672 out=74,555,739 elapsed=333.6s

  [5764/13157] intraday_2606.csv.gz  in=280,292,886 out=74,555,739 elapsed=333.6s

  [5765/13157] intraday_2607.csv.gz  in=280,305,458 out=74,555,739 elapsed=333.7s

  [5766/13157] intraday_2609.csv.gz  in=280,319,077 out=74,555,739 elapsed=333.7s

  [5767/13157] intraday_2610.csv.gz  in=280,331,802 out=74,555,739 elapsed=333.8s

  [5768/13157] intraday_2608.csv.gz  in=280,347,554 out=74,555,739 elapsed=333.8s

  [5769/13157] intraday_2611.csv.gz  in=280,361,587 out=74,555,739 elapsed=333.8s

  [5770/13157] intraday_2612.csv.gz  in=280,371,438 out=74,555,739 elapsed=333.8s

  [5771/13157] intraday_2614.csv.gz  in=280,382,246 out=74,555,739 elapsed=333.8s

  [5772/13157] intraday_2613.csv.gz  in=280,394,842 out=74,555,739 elapsed=333.8s

  [5773/13157] intraday_2615.csv.gz  in=280,409,283 out=74,555,739 elapsed=333.9s

  [5774/13157] intraday_2616.csv.gz  in=280,423,069 out=74,555,739 elapsed=333.9s

  [5775/13157] intraday_2618.csv.gz  in=280,435,010 out=74,555,739 elapsed=333.9s

  [5776/13157] intraday_2617.csv.gz  in=280,451,136 out=74,555,739 elapsed=333.9s

  [5777/13157] intraday_2621.csv.gz  in=280,464,752 out=74,555,739 elapsed=333.9s

  [5778/13157] intraday_2619.csv.gz  in=280,478,693 out=74,555,739 elapsed=334.0s

  [5779/13157] intraday_2622.csv.gz  in=280,491,787 out=74,555,739 elapsed=334.0s

  [5780/13157] intraday_2620.csv.gz  in=280,505,387 out=74,555,739 elapsed=334.0s

  [5781/13157] intraday_2625.csv.gz  in=280,518,980 out=74,555,739 elapsed=334.0s

  [5782/13157] intraday_2623.csv.gz  in=280,534,574 out=74,555,739 elapsed=334.0s

  [5783/13157] intraday_2626.csv.gz  in=280,547,428 out=74,555,739 elapsed=334.0s

  [5784/13157] intraday_2627.csv.gz  in=280,557,333 out=74,555,739 elapsed=334.0s

  [5785/13157] intraday_2624.csv.gz  in=280,571,674 out=74,555,739 elapsed=334.1s

  [5786/13157] intraday_2630.csv.gz  in=280,583,551 out=74,555,739 elapsed=334.1s

  [5787/13157] intraday_2628.csv.gz  in=280,596,368 out=74,555,739 elapsed=334.1s

  [5788/13157] intraday_2629.csv.gz  in=280,608,524 out=74,555,739 elapsed=334.1s

  [5789/13157] intraday_2631.csv.gz  in=280,615,595 out=74,555,739 elapsed=334.1s

  [5790/13157] intraday_2632.csv.gz  in=280,625,858 out=74,555,739 elapsed=334.1s

  [5791/13157] intraday_2633.csv.gz  in=280,631,881 out=74,555,739 elapsed=334.1s

  [5792/13157] intraday_2634.csv.gz  in=280,634,082 out=74,555,739 elapsed=334.1s

  [5793/13157] intraday_2635.csv.gz  in=280,634,207 out=74,555,739 elapsed=334.1s

  [5794/13157] intraday_2637.csv.gz  in=280,634,431 out=74,555,739 elapsed=334.2s

  [5795/13157] intraday_2638.csv.gz  in=280,634,512 out=74,555,739 elapsed=334.2s

  [5796/13157] intraday_2636.csv.gz  in=280,646,974 out=74,555,739 elapsed=334.2s

  [5797/13157] intraday_2641.csv.gz  in=280,647,007 out=74,555,739 elapsed=334.2s

  [5798/13157] intraday_2639.csv.gz  in=280,647,118 out=74,555,739 elapsed=334.2s

  [5799/13157] intraday_2640.csv.gz  in=280,653,607 out=74,555,739 elapsed=334.2s

  [5800/13157] intraday_2642.csv.gz  in=280,653,618 out=74,555,739 elapsed=334.2s

  [5801/13157] intraday_2643.csv.gz  in=280,653,630 out=74,555,739 elapsed=334.2s

  [5802/13157] intraday_2644.csv.gz  in=280,653,672 out=74,555,739 elapsed=334.2s

  [5803/13157] intraday_2645.csv.gz  in=280,654,448 out=74,555,739 elapsed=334.2s

  [5804/13157] intraday_2648.csv.gz  in=280,654,492 out=74,555,739 elapsed=334.3s

  [5805/13157] intraday_2646.csv.gz  in=280,654,563 out=74,555,739 elapsed=334.3s

  [5806/13157] intraday_2647.csv.gz  in=280,665,706 out=74,555,739 elapsed=334.3s

  [5807/13157] intraday_2649.csv.gz  in=280,665,735 out=74,555,739 elapsed=334.3s

  [5808/13157] intraday_2652.csv.gz  in=280,665,750 out=74,555,739 elapsed=334.3s

  [5809/13157] intraday_2651.csv.gz  in=280,665,837 out=74,555,739 elapsed=334.3s

  [5810/13157] intraday_2654.csv.gz  in=280,666,168 out=74,555,739 elapsed=334.3s

  [5811/13157] intraday_2653.csv.gz  in=280,672,022 out=74,555,739 elapsed=334.3s

  [5812/13157] intraday_2650.csv.gz  in=280,686,682 out=74,555,739 elapsed=334.3s

  [5813/13157] intraday_2655.csv.gz  in=280,686,848 out=74,555,739 elapsed=334.3s

  [5814/13157] intraday_2659.csv.gz  in=280,686,871 out=74,555,739 elapsed=334.3s

  [5815/13157] intraday_2657.csv.gz  in=280,690,071 out=74,555,739 elapsed=334.3s

  [5816/13157] intraday_2656.csv.gz  in=280,692,016 out=74,555,739 elapsed=334.3s

  [5817/13157] intraday_2658.csv.gz  in=280,696,176 out=74,555,739 elapsed=334.3s

  [5818/13157] intraday_2663.csv.gz  in=280,696,336 out=74,555,739 elapsed=334.4s

  [5819/13157] intraday_2662.csv.gz  in=280,696,379 out=74,555,739 elapsed=334.4s

  [5820/13157] intraday_2660.csv.gz  in=280,699,857 out=74,555,739 elapsed=334.4s

  [5821/13157] intraday_2664.csv.gz  in=280,699,945 out=74,555,739 elapsed=334.4s

  [5822/13157] intraday_2661.csv.gz  in=280,708,620 out=74,555,739 elapsed=334.4s

  [5823/13157] intraday_2668.csv.gz  in=280,718,921 out=74,555,739 elapsed=334.5s

  [5824/13157] intraday_2666.csv.gz  in=280,732,223 out=74,555,739 elapsed=334.5s

  [5825/13157] intraday_2667.csv.gz  in=280,744,675 out=74,555,739 elapsed=334.5s

  [5826/13157] intraday_2665.csv.gz  in=280,759,509 out=74,555,739 elapsed=334.5s

  [5827/13157] intraday_2669.csv.gz  in=280,773,414 out=74,555,739 elapsed=334.5s

  [5828/13157] intraday_2671.csv.gz  in=280,784,857 out=74,555,739 elapsed=334.5s

  [5829/13157] intraday_2670.csv.gz  in=280,798,086 out=74,555,739 elapsed=334.5s

  [5830/13157] intraday_2673.csv.gz  in=280,810,852 out=74,555,739 elapsed=334.5s

  [5831/13157] intraday_2674.csv.gz  in=280,824,069 out=74,555,739 elapsed=334.5s

  [5832/13157] intraday_2672.csv.gz  in=280,838,106 out=74,555,739 elapsed=334.6s

  [5833/13157] intraday_2675.csv.gz  in=280,846,784 out=74,555,739 elapsed=334.6s

  [5834/13157] intraday_2676.csv.gz  in=280,858,246 out=74,555,739 elapsed=334.6s

  [5835/13157] intraday_2679.csv.gz  in=280,868,786 out=74,555,739 elapsed=334.6s

  [5836/13157] intraday_2677.csv.gz  in=280,879,789 out=74,555,739 elapsed=334.6s

  [5837/13157] intraday_2678.csv.gz  in=280,896,651 out=74,555,739 elapsed=334.6s

  [5838/13157] intraday_2680.csv.gz  in=280,906,524 out=74,555,739 elapsed=334.6s

  [5839/13157] intraday_2681.csv.gz  in=280,918,848 out=74,555,739 elapsed=334.7s

  [5840/13157] intraday_2682.csv.gz  in=280,930,534 out=74,555,739 elapsed=334.7s

  [5841/13157] intraday_2683.csv.gz  in=280,940,792 out=74,555,739 elapsed=334.7s

  [5842/13157] intraday_2685.csv.gz  in=280,952,715 out=74,555,739 elapsed=334.7s

  [5843/13157] intraday_2687.csv.gz  in=280,964,037 out=74,555,739 elapsed=334.7s

  [5844/13157] intraday_2684.csv.gz  in=280,977,027 out=74,555,739 elapsed=334.7s

  [5845/13157] intraday_2686.csv.gz  in=280,989,382 out=74,555,739 elapsed=334.7s

  [5846/13157] intraday_2688.csv.gz  in=281,000,349 out=74,555,739 elapsed=334.7s

  [5847/13157] intraday_2690.csv.gz  in=281,009,846 out=74,555,739 elapsed=334.8s

  [5848/13157] intraday_2691.csv.gz  in=281,021,636 out=74,555,739 elapsed=334.8s

  [5849/13157] intraday_2689.csv.gz  in=281,032,881 out=74,555,739 elapsed=334.8s

  [5850/13157] intraday_2694.csv.gz  in=281,046,532 out=74,555,739 elapsed=334.8s

  [5851/13157] intraday_2695.csv.gz  in=281,059,180 out=74,555,739 elapsed=334.8s

  [5852/13157] intraday_2693.csv.gz  in=281,071,411 out=74,555,739 elapsed=334.8s

  [5853/13157] intraday_2692.csv.gz  in=281,083,199 out=74,555,739 elapsed=334.8s

  [5854/13157] intraday_2696.csv.gz  in=281,093,945 out=74,555,739 elapsed=334.9s

  [5855/13157] intraday_2698.csv.gz  in=281,106,631 out=74,555,739 elapsed=334.9s

  [5856/13157] intraday_2699.csv.gz  in=281,117,440 out=74,555,739 elapsed=334.9s

  [5857/13157] intraday_2697.csv.gz  in=281,129,267 out=74,555,739 elapsed=334.9s

  [5858/13157] intraday_2701.csv.gz  in=281,138,168 out=74,555,739 elapsed=335.0s

  [5859/13157] intraday_2700.csv.gz  in=281,151,574 out=74,555,739 elapsed=335.0s

  [5860/13157] intraday_2703.csv.gz  in=281,161,212 out=74,555,739 elapsed=335.0s

  [5861/13157] intraday_2702.csv.gz  in=281,172,528 out=74,555,739 elapsed=335.0s

  [5862/13157] intraday_2704.csv.gz  in=281,183,723 out=74,555,739 elapsed=335.0s

  [5863/13157] intraday_2705.csv.gz  in=281,196,227 out=74,555,739 elapsed=335.1s

  [5864/13157] intraday_2708.csv.gz  in=281,209,070 out=74,555,739 elapsed=335.2s

  [5865/13157] intraday_2707.csv.gz  in=281,225,042 out=74,555,739 elapsed=335.2s

  [5866/13157] intraday_2706.csv.gz  in=281,238,356 out=74,555,739 elapsed=335.2s

  [5867/13157] intraday_2709.csv.gz  in=281,249,521 out=74,555,739 elapsed=335.2s

  [5868/13157] intraday_2710.csv.gz  in=281,260,361 out=74,555,739 elapsed=335.3s

  [5869/13157] intraday_2711.csv.gz  in=281,271,854 out=74,555,739 elapsed=335.3s

  [5870/13157] intraday_2712.csv.gz  in=281,298,857 out=74,555,739 elapsed=335.3s

  [5871/13157] intraday_2713.csv.gz  in=281,310,189 out=74,555,739 elapsed=335.3s

  [5872/13157] intraday_2714.csv.gz  in=281,319,889 out=74,555,739 elapsed=335.4s

  [5873/13157] intraday_2716.csv.gz  in=281,329,833 out=74,555,739 elapsed=335.4s

  [5874/13157] intraday_2717.csv.gz  in=281,344,456 out=74,555,739 elapsed=335.4s

  [5875/13157] intraday_2715.csv.gz  in=281,355,635 out=74,555,739 elapsed=335.4s

  [5876/13157] intraday_2718.csv.gz  in=281,366,026 out=74,555,739 elapsed=335.4s

  [5877/13157] intraday_2719.csv.gz  in=281,378,563 out=74,555,739 elapsed=335.4s

  [5878/13157] intraday_2721.csv.gz  in=281,387,479 out=74,555,739 elapsed=335.4s

  [5879/13157] intraday_2720.csv.gz  in=281,399,422 out=74,555,739 elapsed=335.4s

  [5880/13157] intraday_2723.csv.gz  in=281,411,093 out=74,555,739 elapsed=335.4s

  [5881/13157] intraday_2722.csv.gz  in=281,423,497 out=74,555,739 elapsed=335.4s

  [5882/13157] intraday_2724.csv.gz  in=281,437,827 out=74,555,739 elapsed=335.5s

  [5883/13157] intraday_2727.csv.gz  in=281,447,239 out=74,555,739 elapsed=335.5s

  [5884/13157] intraday_2725.csv.gz  in=281,458,277 out=74,555,739 elapsed=335.5s

  [5885/13157] intraday_2726.csv.gz  in=281,469,685 out=74,555,739 elapsed=335.5s

  [5886/13157] intraday_2731.csv.gz  in=281,483,066 out=74,555,739 elapsed=335.5s

  [5887/13157] intraday_2730.csv.gz  in=281,492,672 out=74,555,739 elapsed=335.5s

  [5888/13157] intraday_2728.csv.gz  in=281,504,412 out=74,555,739 elapsed=335.5s

  [5889/13157] intraday_2729.csv.gz  in=281,518,619 out=74,555,739 elapsed=335.6s

  [5890/13157] intraday_2732.csv.gz  in=281,531,228 out=74,555,739 elapsed=335.6s

  [5891/13157] intraday_2733.csv.gz  in=281,540,459 out=74,555,739 elapsed=335.6s

  [5892/13157] intraday_2735.csv.gz  in=281,551,678 out=74,555,739 elapsed=335.6s

  [5893/13157] intraday_2734.csv.gz  in=281,574,895 out=74,555,739 elapsed=335.6s

  [5894/13157] intraday_2738.csv.gz  in=281,585,469 out=74,555,739 elapsed=335.6s

  [5895/13157] intraday_2737.csv.gz  in=281,595,177 out=74,555,739 elapsed=335.6s

  [5896/13157] intraday_2736.csv.gz  in=281,607,293 out=74,555,739 elapsed=335.6s

  [5897/13157] intraday_2739.csv.gz  in=281,618,370 out=74,555,739 elapsed=335.6s

  [5898/13157] intraday_2740.csv.gz  in=281,629,423 out=74,555,739 elapsed=335.7s

  [5899/13157] intraday_2742.csv.gz  in=281,640,857 out=74,555,739 elapsed=335.7s

  [5900/13157] intraday_2741.csv.gz  in=281,652,524 out=74,555,739 elapsed=335.7s

  [5901/13157] intraday_2743.csv.gz  in=281,664,202 out=74,555,739 elapsed=335.8s

  [5902/13157] intraday_2745.csv.gz  in=281,674,570 out=74,555,739 elapsed=335.8s

  [5903/13157] intraday_2744.csv.gz  in=281,684,786 out=74,555,739 elapsed=335.8s

  [5904/13157] intraday_2746.csv.gz  in=281,697,631 out=74,555,739 elapsed=335.8s

  [5905/13157] intraday_2747.csv.gz  in=281,712,313 out=74,555,739 elapsed=335.8s

  [5906/13157] intraday_2749.csv.gz  in=281,721,104 out=74,555,739 elapsed=335.8s

  [5907/13157] intraday_2748.csv.gz  in=281,732,119 out=74,555,739 elapsed=335.8s

  [5908/13157] intraday_2751.csv.gz  in=281,743,914 out=74,555,739 elapsed=335.9s

  [5909/13157] intraday_2750.csv.gz  in=281,754,320 out=74,555,739 elapsed=335.9s

  [5910/13157] intraday_2753.csv.gz  in=281,767,952 out=74,555,739 elapsed=335.9s

  [5911/13157] intraday_2752.csv.gz  in=281,779,957 out=74,555,739 elapsed=335.9s

  [5912/13157] intraday_2754.csv.gz  in=281,791,425 out=74,555,739 elapsed=335.9s

  [5913/13157] intraday_2756.csv.gz  in=281,803,475 out=74,555,739 elapsed=335.9s

  [5914/13157] intraday_2755.csv.gz  in=281,816,053 out=74,555,739 elapsed=335.9s

  [5915/13157] intraday_2757.csv.gz  in=281,828,992 out=74,555,739 elapsed=335.9s

  [5916/13157] intraday_2758.csv.gz  in=281,840,779 out=74,555,739 elapsed=336.0s

  [5917/13157] intraday_2759.csv.gz  in=281,852,379 out=74,555,739 elapsed=336.0s

  [5918/13157] intraday_2760.csv.gz  in=281,864,544 out=74,555,739 elapsed=336.0s

  [5919/13157] intraday_2761.csv.gz  in=281,875,646 out=74,555,739 elapsed=336.0s

  [5920/13157] intraday_2762.csv.gz  in=281,887,494 out=74,555,739 elapsed=336.1s

  [5921/13157] intraday_2763.csv.gz  in=281,899,185 out=74,555,739 elapsed=336.1s

  [5922/13157] intraday_2765.csv.gz  in=281,911,243 out=74,555,739 elapsed=336.1s

  [5923/13157] intraday_2764.csv.gz  in=281,921,187 out=74,555,739 elapsed=336.1s

  [5924/13157] intraday_2769.csv.gz  in=281,930,546 out=74,555,739 elapsed=336.2s

  [5925/13157] intraday_2767.csv.gz  in=281,941,996 out=74,555,739 elapsed=336.2s

  [5926/13157] intraday_2766.csv.gz  in=281,952,544 out=74,555,739 elapsed=336.2s

  [5927/13157] intraday_2768.csv.gz  in=281,966,093 out=74,555,739 elapsed=336.2s

  [5928/13157] intraday_2773.csv.gz  in=281,978,656 out=74,555,739 elapsed=336.2s

  [5929/13157] intraday_2771.csv.gz  in=281,993,075 out=74,555,739 elapsed=336.2s

  [5930/13157] intraday_2770.csv.gz  in=282,008,721 out=74,555,739 elapsed=336.2s

  [5931/13157] intraday_2772.csv.gz  in=282,022,535 out=74,555,739 elapsed=336.2s

  [5932/13157] intraday_2775.csv.gz  in=282,034,318 out=74,555,739 elapsed=336.4s

  [5933/13157] intraday_2776.csv.gz  in=282,047,029 out=74,555,739 elapsed=336.4s

  [5934/13157] intraday_2774.csv.gz  in=282,059,175 out=74,555,739 elapsed=336.4s

  [5935/13157] intraday_2777.csv.gz  in=282,080,617 out=74,555,739 elapsed=336.4s

  [5936/13157] intraday_2778.csv.gz  in=282,091,562 out=74,555,739 elapsed=336.5s

  [5937/13157] intraday_2781.csv.gz  in=282,103,603 out=74,555,739 elapsed=336.5s

  [5938/13157] intraday_2779.csv.gz  in=282,116,546 out=74,555,739 elapsed=336.5s

  [5939/13157] intraday_2780.csv.gz  in=282,132,055 out=74,555,739 elapsed=336.6s

  [5940/13157] intraday_2782.csv.gz  in=282,144,963 out=74,555,739 elapsed=336.6s

  [5941/13157] intraday_2784.csv.gz  in=282,156,563 out=74,555,739 elapsed=336.6s

  [5942/13157] intraday_2783.csv.gz  in=282,167,905 out=74,555,739 elapsed=336.6s

  [5943/13157] intraday_2785.csv.gz  in=282,179,549 out=74,555,739 elapsed=336.6s

  [5944/13157] intraday_2786.csv.gz  in=282,192,829 out=74,555,739 elapsed=336.7s

  [5945/13157] intraday_2787.csv.gz  in=282,205,062 out=74,555,739 elapsed=336.7s

  [5946/13157] intraday_2789.csv.gz  in=282,215,581 out=74,555,739 elapsed=336.7s

  [5947/13157] intraday_2788.csv.gz  in=282,231,453 out=74,555,739 elapsed=336.7s

  [5948/13157] intraday_2790.csv.gz  in=282,243,890 out=74,555,739 elapsed=336.8s

  [5949/13157] intraday_2793.csv.gz  in=282,255,096 out=74,555,739 elapsed=336.8s

  [5950/13157] intraday_2791.csv.gz  in=282,267,090 out=74,555,739 elapsed=336.8s

  [5951/13157] intraday_2792.csv.gz  in=282,280,019 out=74,555,739 elapsed=336.8s

  [5952/13157] intraday_2794.csv.gz  in=282,295,154 out=74,555,739 elapsed=336.8s

  [5953/13157] intraday_2797.csv.gz  in=282,308,700 out=74,555,739 elapsed=336.9s

  [5954/13157] intraday_2798.csv.gz  in=282,319,667 out=74,555,739 elapsed=336.9s

  [5955/13157] intraday_2796.csv.gz  in=282,332,773 out=74,555,739 elapsed=336.9s

  [5956/13157] intraday_2795.csv.gz  in=282,349,577 out=74,555,739 elapsed=336.9s

  [5957/13157] intraday_2799.csv.gz  in=282,359,656 out=74,555,739 elapsed=337.0s

  [5958/13157] intraday_2801.csv.gz  in=282,371,711 out=74,555,739 elapsed=337.0s

  [5959/13157] intraday_2802.csv.gz  in=282,379,652 out=74,555,739 elapsed=337.0s

  [5960/13157] intraday_2800.csv.gz  in=282,391,501 out=74,555,739 elapsed=337.0s

  [5961/13157] intraday_2803.csv.gz  in=282,399,809 out=74,555,739 elapsed=337.1s

  [5962/13157] intraday_2805.csv.gz  in=282,402,072 out=74,555,739 elapsed=337.1s

  [5963/13157] intraday_2804.csv.gz  in=282,413,015 out=74,555,739 elapsed=337.2s

  [5964/13157] intraday_2807.csv.gz  in=282,427,881 out=74,555,739 elapsed=337.2s

  [5965/13157] intraday_2806.csv.gz  in=282,443,450 out=74,555,739 elapsed=337.2s

  [5966/13157] intraday_2808.csv.gz  in=282,456,584 out=74,555,739 elapsed=337.3s

  [5967/13157] intraday_2809.csv.gz  in=282,467,365 out=74,555,739 elapsed=337.3s

  [5968/13157] intraday_2810.csv.gz  in=282,482,184 out=74,555,739 elapsed=337.3s

  [5969/13157] intraday_2811.csv.gz  in=282,495,921 out=74,555,739 elapsed=337.3s

  [5970/13157] intraday_2812.csv.gz  in=282,508,505 out=74,555,739 elapsed=337.3s

  [5971/13157] intraday_2813.csv.gz  in=282,520,537 out=74,555,739 elapsed=337.5s

  [5972/13157] intraday_2816.csv.gz  in=282,529,517 out=74,555,739 elapsed=337.5s

  [5973/13157] intraday_2814.csv.gz  in=282,543,538 out=74,555,739 elapsed=337.5s

  [5974/13157] intraday_2815.csv.gz  in=282,557,491 out=74,555,739 elapsed=337.5s

  [5975/13157] intraday_2819.csv.gz  in=282,568,533 out=74,555,739 elapsed=337.6s

  [5976/13157] intraday_2820.csv.gz  in=282,579,555 out=74,555,739 elapsed=337.6s

  [5977/13157] intraday_2817.csv.gz  in=282,592,693 out=74,555,739 elapsed=337.6s

  [5978/13157] intraday_2818.csv.gz  in=282,604,980 out=74,555,739 elapsed=337.6s

  [5979/13157] intraday_2823.csv.gz  in=282,617,280 out=74,555,739 elapsed=337.9s

  [5980/13157] intraday_2821.csv.gz  in=282,628,421 out=74,555,739 elapsed=337.9s

  [5981/13157] intraday_2824.csv.gz  in=282,639,178 out=74,555,739 elapsed=337.9s

  [5982/13157] intraday_2822.csv.gz  in=282,652,059 out=74,555,739 elapsed=337.9s

  [5983/13157] intraday_2827.csv.gz  in=282,663,971 out=74,555,739 elapsed=338.0s

  [5984/13157] intraday_2825.csv.gz  in=282,676,816 out=74,555,739 elapsed=338.0s

  [5985/13157] intraday_2826.csv.gz  in=282,689,669 out=74,555,739 elapsed=338.0s

  [5986/13157] intraday_2828.csv.gz  in=282,702,196 out=74,555,739 elapsed=338.0s

  [5987/13157] intraday_2831.csv.gz  in=282,711,976 out=74,555,739 elapsed=338.1s

  [5988/13157] intraday_2829.csv.gz  in=282,724,878 out=74,555,739 elapsed=338.2s

  [5989/13157] intraday_2832.csv.gz  in=282,736,787 out=74,555,739 elapsed=338.2s

  [5990/13157] intraday_2830.csv.gz  in=282,757,959 out=74,555,739 elapsed=338.2s

  [5991/13157] intraday_2833.csv.gz  in=282,770,186 out=74,555,739 elapsed=338.2s

  [5992/13157] intraday_2836.csv.gz  in=282,783,640 out=74,555,739 elapsed=338.3s

  [5993/13157] intraday_2835.csv.gz  in=282,797,832 out=74,555,739 elapsed=338.3s

  [5994/13157] intraday_2834.csv.gz  in=282,816,824 out=74,555,739 elapsed=338.3s

  [5995/13157] intraday_2839.csv.gz  in=282,829,861 out=74,555,739 elapsed=338.4s

  [5996/13157] intraday_2838.csv.gz  in=282,842,706 out=74,555,739 elapsed=338.4s

  [5997/13157] intraday_2837.csv.gz  in=282,856,033 out=74,555,739 elapsed=338.4s

  [5998/13157] intraday_2843.csv.gz  in=282,866,554 out=74,555,739 elapsed=338.7s

  [5999/13157] intraday_2842.csv.gz  in=282,876,874 out=74,555,739 elapsed=338.7s

  [6000/13157] intraday_2841.csv.gz  in=282,889,565 out=74,555,739 elapsed=338.7s

  [6001/13157] intraday_2840.csv.gz  in=282,918,745 out=74,555,739 elapsed=338.7s

  [6002/13157] intraday_2845.csv.gz  in=282,929,552 out=74,555,739 elapsed=338.9s

  [6003/13157] intraday_2847.csv.gz  in=282,943,049 out=74,555,739 elapsed=338.9s

  [6004/13157] intraday_2844.csv.gz  in=282,954,017 out=74,555,739 elapsed=338.9s

  [6005/13157] intraday_2846.csv.gz  in=282,968,223 out=74,555,739 elapsed=338.9s

  [6006/13157] intraday_2848.csv.gz  in=282,980,198 out=74,555,739 elapsed=339.1s

  [6007/13157] intraday_2849.csv.gz  in=282,994,117 out=74,555,739 elapsed=339.1s

  [6008/13157] intraday_2851.csv.gz  in=283,010,721 out=74,555,739 elapsed=339.1s

  [6009/13157] intraday_2853.csv.gz  in=283,022,104 out=74,555,739 elapsed=339.1s

  [6010/13157] intraday_2852.csv.gz  in=283,033,167 out=74,555,739 elapsed=339.2s

  [6011/13157] intraday_2854.csv.gz  in=283,045,427 out=74,555,739 elapsed=339.2s

  [6012/13157] intraday_2850.csv.gz  in=283,072,828 out=74,555,739 elapsed=339.2s

  [6013/13157] intraday_2856.csv.gz  in=283,084,894 out=74,555,739 elapsed=339.2s

  [6014/13157] intraday_2858.csv.gz  in=283,104,326 out=74,555,739 elapsed=339.2s

  [6015/13157] intraday_2855.csv.gz  in=283,114,948 out=74,555,739 elapsed=339.2s

  [6016/13157] intraday_2857.csv.gz  in=283,125,561 out=74,555,739 elapsed=339.2s

  [6017/13157] intraday_2862.csv.gz  in=283,135,405 out=74,555,739 elapsed=339.3s

  [6018/13157] intraday_2861.csv.gz  in=283,147,318 out=74,555,739 elapsed=339.3s

  [6019/13157] intraday_2859.csv.gz  in=283,158,502 out=74,555,739 elapsed=339.3s

  [6020/13157] intraday_2860.csv.gz  in=283,171,134 out=74,555,739 elapsed=339.3s

  [6021/13157] intraday_2866.csv.gz  in=283,183,597 out=74,555,739 elapsed=339.4s

  [6022/13157] intraday_2863.csv.gz  in=283,196,301 out=74,555,739 elapsed=339.4s

  [6023/13157] intraday_2865.csv.gz  in=283,209,280 out=74,555,739 elapsed=339.4s

  [6024/13157] intraday_2864.csv.gz  in=283,221,903 out=74,555,739 elapsed=339.4s

  [6025/13157] intraday_2867.csv.gz  in=283,233,296 out=74,555,739 elapsed=339.4s

  [6026/13157] intraday_2868.csv.gz  in=283,242,868 out=74,555,739 elapsed=339.4s

  [6027/13157] intraday_2869.csv.gz  in=283,255,350 out=74,555,739 elapsed=339.4s

  [6028/13157] intraday_2870.csv.gz  in=283,270,619 out=74,555,739 elapsed=339.4s

  [6029/13157] intraday_2871.csv.gz  in=283,280,861 out=74,555,739 elapsed=339.5s

  [6030/13157] intraday_2874.csv.gz  in=283,290,762 out=74,555,739 elapsed=339.7s

  [6031/13157] intraday_2872.csv.gz  in=283,304,733 out=74,555,739 elapsed=339.7s

  [6032/13157] intraday_2873.csv.gz  in=283,320,069 out=74,555,739 elapsed=339.8s

  [6033/13157] intraday_2875.csv.gz  in=283,332,387 out=74,555,739 elapsed=339.8s

  [6034/13157] intraday_2877.csv.gz  in=283,344,994 out=74,555,739 elapsed=339.8s

  [6035/13157] intraday_2876.csv.gz  in=283,358,176 out=74,555,739 elapsed=339.8s

  [6036/13157] intraday_2878.csv.gz  in=283,368,734 out=74,555,739 elapsed=339.9s

  [6037/13157] intraday_2879.csv.gz  in=283,379,964 out=74,555,739 elapsed=340.0s

  [6038/13157] intraday_2882.csv.gz  in=283,391,973 out=74,555,739 elapsed=340.0s

  [6039/13157] intraday_2881.csv.gz  in=283,404,150 out=74,555,739 elapsed=340.0s

  [6040/13157] intraday_2880.csv.gz  in=283,420,872 out=74,555,739 elapsed=340.0s

  [6041/13157] intraday_2883.csv.gz  in=283,432,890 out=74,555,739 elapsed=340.2s

  [6042/13157] intraday_2885.csv.gz  in=283,443,461 out=74,555,739 elapsed=340.2s

  [6043/13157] intraday_2884.csv.gz  in=283,456,420 out=74,555,739 elapsed=340.2s

  [6044/13157] intraday_2886.csv.gz  in=283,467,094 out=74,555,739 elapsed=340.2s

  [6045/13157] intraday_2887.csv.gz  in=283,479,601 out=74,555,739 elapsed=340.3s

  [6046/13157] intraday_2890.csv.gz  in=283,490,238 out=74,555,739 elapsed=340.4s

  [6047/13157] intraday_2888.csv.gz  in=283,506,984 out=74,555,739 elapsed=340.4s

  [6048/13157] intraday_2889.csv.gz  in=283,517,490 out=74,555,739 elapsed=340.4s

  [6049/13157] intraday_2891.csv.gz  in=283,527,971 out=74,555,739 elapsed=340.4s

  [6050/13157] intraday_2893.csv.gz  in=283,539,306 out=74,555,739 elapsed=340.4s

  [6051/13157] intraday_2894.csv.gz  in=283,554,858 out=74,555,739 elapsed=340.4s

  [6052/13157] intraday_2892.csv.gz  in=283,567,376 out=74,555,739 elapsed=340.4s

  [6053/13157] intraday_2895.csv.gz  in=283,578,632 out=74,555,739 elapsed=340.4s

  [6054/13157] intraday_2896.csv.gz  in=283,591,842 out=74,555,739 elapsed=340.4s

  [6055/13157] intraday_2897.csv.gz  in=283,605,287 out=74,555,739 elapsed=340.5s

  [6056/13157] intraday_2898.csv.gz  in=283,632,480 out=74,555,739 elapsed=340.5s

  [6057/13157] intraday_2899.csv.gz  in=283,644,582 out=74,555,739 elapsed=340.5s

  [6058/13157] intraday_2900.csv.gz  in=283,656,988 out=74,555,739 elapsed=340.5s

  [6059/13157] intraday_2902.csv.gz  in=283,671,729 out=74,555,739 elapsed=340.5s

  [6060/13157] intraday_2901.csv.gz  in=283,696,038 out=74,555,739 elapsed=340.5s

  [6061/13157] intraday_2903.csv.gz  in=283,708,744 out=74,555,739 elapsed=340.5s

  [6062/13157] intraday_2905.csv.gz  in=283,719,551 out=74,555,739 elapsed=340.5s

  [6063/13157] intraday_2904.csv.gz  in=283,733,564 out=74,555,739 elapsed=340.6s

  [6064/13157] intraday_2906.csv.gz  in=283,746,028 out=74,555,739 elapsed=340.6s

  [6065/13157] intraday_2907.csv.gz  in=283,757,910 out=74,555,739 elapsed=340.6s

  [6066/13157] intraday_2910.csv.gz  in=283,768,573 out=74,555,739 elapsed=340.6s

  [6067/13157] intraday_2911.csv.gz  in=283,779,794 out=74,555,739 elapsed=340.6s

  [6068/13157] intraday_2909.csv.gz  in=283,793,052 out=74,555,739 elapsed=340.6s

  [6069/13157] intraday_2908.csv.gz  in=283,817,776 out=74,555,739 elapsed=340.7s

  [6070/13157] intraday_2912.csv.gz  in=283,831,936 out=74,555,739 elapsed=340.7s

  [6071/13157] intraday_2913.csv.gz  in=283,847,096 out=74,555,739 elapsed=340.7s

  [6072/13157] intraday_2914.csv.gz  in=283,859,929 out=74,555,739 elapsed=340.7s

  [6073/13157] intraday_2915.csv.gz  in=283,872,600 out=74,555,739 elapsed=340.7s

  [6074/13157] intraday_2916.csv.gz  in=283,886,588 out=74,555,739 elapsed=340.8s

  [6075/13157] intraday_2919.csv.gz  in=283,898,826 out=74,555,739 elapsed=340.8s

  [6076/13157] intraday_2918.csv.gz  in=283,912,134 out=74,555,739 elapsed=340.8s

  [6077/13157] intraday_2917.csv.gz  in=283,925,491 out=74,555,739 elapsed=340.8s

  [6078/13157] intraday_2920.csv.gz  in=283,939,927 out=74,555,739 elapsed=340.8s

  [6079/13157] intraday_2923.csv.gz  in=283,953,055 out=74,555,739 elapsed=340.8s

  [6080/13157] intraday_2922.csv.gz  in=283,965,840 out=74,555,739 elapsed=340.8s

  [6081/13157] intraday_2921.csv.gz  in=283,987,238 out=74,555,739 elapsed=340.8s

  [6082/13157] intraday_2925.csv.gz  in=283,999,734 out=74,555,739 elapsed=340.9s

  [6083/13157] intraday_2924.csv.gz  in=284,012,157 out=74,555,739 elapsed=340.9s

  [6084/13157] intraday_2926.csv.gz  in=284,023,493 out=74,555,739 elapsed=340.9s

  [6085/13157] intraday_2927.csv.gz  in=284,037,335 out=74,555,739 elapsed=340.9s

  [6086/13157] intraday_2930.csv.gz  in=284,049,713 out=74,555,739 elapsed=341.0s

  [6087/13157] intraday_2928.csv.gz  in=284,062,722 out=74,555,739 elapsed=341.0s

  [6088/13157] intraday_2929.csv.gz  in=284,079,371 out=74,555,739 elapsed=341.0s

  [6089/13157] intraday_2933.csv.gz  in=284,091,816 out=74,555,739 elapsed=341.1s

  [6090/13157] intraday_2932.csv.gz  in=284,105,502 out=74,555,739 elapsed=341.1s

  [6091/13157] intraday_2934.csv.gz  in=284,118,387 out=74,555,739 elapsed=341.2s

  [6092/13157] intraday_2931.csv.gz  in=284,132,252 out=74,555,739 elapsed=341.2s

  [6093/13157] intraday_2937.csv.gz  in=284,145,672 out=74,555,739 elapsed=341.4s

  [6094/13157] intraday_2938.csv.gz  in=284,160,199 out=74,555,739 elapsed=341.4s

  [6095/13157] intraday_2936.csv.gz  in=284,175,327 out=74,555,739 elapsed=341.4s

  [6096/13157] intraday_2935.csv.gz  in=284,197,438 out=74,555,739 elapsed=341.4s

  [6097/13157] intraday_2941.csv.gz  in=284,210,380 out=74,555,739 elapsed=341.6s

  [6098/13157] intraday_2940.csv.gz  in=284,221,606 out=74,555,739 elapsed=341.6s

  [6099/13157] intraday_2939.csv.gz  in=284,232,612 out=74,555,739 elapsed=341.6s

  [6100/13157] intraday_2942.csv.gz  in=284,244,540 out=74,555,739 elapsed=341.6s

  [6101/13157] intraday_2943.csv.gz  in=284,255,487 out=74,555,739 elapsed=341.6s

  [6102/13157] intraday_2946.csv.gz  in=284,261,638 out=74,555,739 elapsed=341.7s

  [6103/13157] intraday_2944.csv.gz  in=284,269,097 out=74,555,739 elapsed=341.7s

  [6104/13157] intraday_2945.csv.gz  in=284,278,594 out=74,555,739 elapsed=341.7s

  [6105/13157] intraday_2947.csv.gz  in=284,295,348 out=74,555,739 elapsed=341.7s

  [6106/13157] intraday_2949.csv.gz  in=284,309,287 out=74,555,739 elapsed=341.7s

  [6107/13157] intraday_2950.csv.gz  in=284,320,328 out=74,555,739 elapsed=341.8s

  [6108/13157] intraday_2951.csv.gz  in=284,335,410 out=74,555,739 elapsed=341.8s

  [6109/13157] intraday_2948.csv.gz  in=284,350,540 out=74,555,739 elapsed=341.8s

  [6110/13157] intraday_2953.csv.gz  in=284,363,678 out=74,555,739 elapsed=341.8s

  [6111/13157] intraday_2954.csv.gz  in=284,376,906 out=74,555,739 elapsed=341.8s

  [6112/13157] intraday_2952.csv.gz  in=284,391,790 out=74,555,739 elapsed=341.8s

  [6113/13157] intraday_2955.csv.gz  in=284,406,660 out=74,555,739 elapsed=341.8s

  [6114/13157] intraday_2957.csv.gz  in=284,416,637 out=74,555,739 elapsed=341.8s

  [6115/13157] intraday_2959.csv.gz  in=284,430,326 out=74,555,739 elapsed=341.9s

  [6116/13157] intraday_2956.csv.gz  in=284,444,896 out=74,555,739 elapsed=341.9s

  [6117/13157] intraday_2958.csv.gz  in=284,458,871 out=74,555,739 elapsed=341.9s

  [6118/13157] intraday_2960.csv.gz  in=284,471,342 out=74,555,739 elapsed=341.9s

  [6119/13157] intraday_2961.csv.gz  in=284,482,785 out=74,555,739 elapsed=341.9s

  [6120/13157] intraday_2963.csv.gz  in=284,496,884 out=74,555,739 elapsed=341.9s

  [6121/13157] intraday_2962.csv.gz  in=284,508,277 out=74,555,739 elapsed=341.9s

  [6122/13157] intraday_2964.csv.gz  in=284,521,235 out=74,555,739 elapsed=341.9s

  [6123/13157] intraday_2965.csv.gz  in=284,532,430 out=74,555,739 elapsed=342.0s

  [6124/13157] intraday_2967.csv.gz  in=284,546,472 out=74,555,739 elapsed=342.0s

  [6125/13157] intraday_2966.csv.gz  in=284,559,521 out=74,555,739 elapsed=342.0s

  [6126/13157] intraday_2968.csv.gz  in=284,571,764 out=74,555,739 elapsed=342.0s

  [6127/13157] intraday_2969.csv.gz  in=284,584,456 out=74,555,739 elapsed=342.0s

  [6128/13157] intraday_2971.csv.gz  in=284,596,957 out=74,555,739 elapsed=342.0s

  [6129/13157] intraday_2972.csv.gz  in=284,607,515 out=74,555,739 elapsed=342.1s

  [6130/13157] intraday_2970.csv.gz  in=284,625,752 out=74,555,739 elapsed=342.1s

  [6131/13157] intraday_2973.csv.gz  in=284,638,843 out=74,555,739 elapsed=342.1s

  [6132/13157] intraday_2975.csv.gz  in=284,652,432 out=74,555,739 elapsed=342.1s

  [6133/13157] intraday_2976.csv.gz  in=284,668,308 out=74,555,739 elapsed=342.1s

  [6134/13157] intraday_2974.csv.gz  in=284,681,029 out=74,555,739 elapsed=342.1s

  [6135/13157] intraday_2977.csv.gz  in=284,695,113 out=74,555,739 elapsed=342.2s

  [6136/13157] intraday_2978.csv.gz  in=284,708,775 out=74,555,739 elapsed=342.2s

  [6137/13157] intraday_2979.csv.gz  in=284,723,733 out=74,555,739 elapsed=342.2s

  [6138/13157] intraday_2980.csv.gz  in=284,754,691 out=74,555,739 elapsed=342.2s

  [6139/13157] intraday_2983.csv.gz  in=284,765,273 out=74,555,739 elapsed=342.2s

  [6140/13157] intraday_2981.csv.gz  in=284,781,158 out=74,555,739 elapsed=342.3s

  [6141/13157] intraday_2982.csv.gz  in=284,798,833 out=74,555,739 elapsed=342.3s

  [6142/13157] intraday_2984.csv.gz  in=284,811,683 out=74,555,739 elapsed=342.3s

  [6143/13157] intraday_2985.csv.gz  in=284,823,982 out=74,555,739 elapsed=342.3s

  [6144/13157] intraday_2988.csv.gz  in=284,838,075 out=74,555,739 elapsed=342.3s

  [6145/13157] intraday_2986.csv.gz  in=284,850,545 out=74,555,739 elapsed=342.3s

  [6146/13157] intraday_2987.csv.gz  in=284,865,076 out=74,555,739 elapsed=342.3s

  [6147/13157] intraday_2989.csv.gz  in=284,877,249 out=74,555,739 elapsed=342.3s

  [6148/13157] intraday_2991.csv.gz  in=284,888,938 out=74,555,739 elapsed=342.4s

  [6149/13157] intraday_2993.csv.gz  in=284,901,166 out=74,555,739 elapsed=342.4s

  [6150/13157] intraday_2992.csv.gz  in=284,914,494 out=74,555,739 elapsed=342.4s

  [6151/13157] intraday_2990.csv.gz  in=284,929,037 out=74,555,739 elapsed=342.5s

  [6152/13157] intraday_2994.csv.gz  in=284,941,161 out=74,555,739 elapsed=342.5s

  [6153/13157] intraday_2995.csv.gz  in=284,953,741 out=74,555,739 elapsed=342.5s

  [6154/13157] intraday_2997.csv.gz  in=284,966,747 out=74,555,739 elapsed=342.5s

  [6155/13157] intraday_2996.csv.gz  in=284,978,354 out=74,555,739 elapsed=342.5s

  [6156/13157] intraday_3001.csv.gz  in=284,992,230 out=74,555,739 elapsed=342.6s

  [6157/13157] intraday_2999.csv.gz  in=285,004,812 out=74,555,739 elapsed=342.6s

  [6158/13157] intraday_2998.csv.gz  in=285,017,092 out=74,555,739 elapsed=342.6s

  [6159/13157] intraday_3000.csv.gz  in=285,029,163 out=74,555,739 elapsed=342.6s

  [6160/13157] intraday_3002.csv.gz  in=285,041,702 out=74,555,739 elapsed=342.6s

  [6161/13157] intraday_3003.csv.gz  in=285,052,681 out=74,555,739 elapsed=342.6s

  [6162/13157] intraday_3004.csv.gz  in=285,066,705 out=74,555,739 elapsed=342.7s

  [6163/13157] intraday_3007.csv.gz  in=285,079,387 out=74,555,739 elapsed=342.7s

  [6164/13157] intraday_3005.csv.gz  in=285,093,357 out=74,555,739 elapsed=342.7s

  [6165/13157] intraday_3006.csv.gz  in=285,106,130 out=74,555,739 elapsed=342.7s

  [6166/13157] intraday_3010.csv.gz  in=285,119,177 out=74,555,739 elapsed=342.8s

  [6167/13157] intraday_3009.csv.gz  in=285,129,305 out=74,555,739 elapsed=342.8s

  [6168/13157] intraday_3008.csv.gz  in=285,141,640 out=74,555,739 elapsed=342.8s

  [6169/13157] intraday_3011.csv.gz  in=285,158,177 out=74,555,739 elapsed=342.8s

  [6170/13157] intraday_3014.csv.gz  in=285,172,991 out=74,555,739 elapsed=343.0s

  [6171/13157] intraday_3013.csv.gz  in=285,186,732 out=74,555,739 elapsed=343.0s

  [6172/13157] intraday_3015.csv.gz  in=285,196,100 out=74,555,739 elapsed=343.0s

  [6173/13157] intraday_3012.csv.gz  in=285,207,097 out=74,555,739 elapsed=343.0s

  [6174/13157] intraday_3019.csv.gz  in=285,217,967 out=74,555,739 elapsed=343.1s

  [6175/13157] intraday_3018.csv.gz  in=285,232,166 out=74,555,739 elapsed=343.1s

  [6176/13157] intraday_3016.csv.gz  in=285,245,994 out=74,555,739 elapsed=343.1s

  [6177/13157] intraday_3017.csv.gz  in=285,259,379 out=74,555,739 elapsed=343.1s

  [6178/13157] intraday_3022.csv.gz  in=285,272,371 out=74,555,739 elapsed=343.1s

  [6179/13157] intraday_3020.csv.gz  in=285,283,884 out=74,555,739 elapsed=343.1s

  [6180/13157] intraday_3021.csv.gz  in=285,295,969 out=74,555,739 elapsed=343.1s

  [6181/13157] intraday_3023.csv.gz  in=285,309,454 out=74,555,739 elapsed=343.1s

  [6182/13157] intraday_3027.csv.gz  in=285,320,422 out=74,555,739 elapsed=343.2s

  [6183/13157] intraday_3025.csv.gz  in=285,334,371 out=74,555,739 elapsed=343.2s

  [6184/13157] intraday_3026.csv.gz  in=285,345,180 out=74,555,739 elapsed=343.2s

  [6185/13157] intraday_3024.csv.gz  in=285,357,346 out=74,555,739 elapsed=343.2s

  [6186/13157] intraday_3028.csv.gz  in=285,371,047 out=74,555,739 elapsed=343.3s

  [6187/13157] intraday_3030.csv.gz  in=285,382,165 out=74,555,739 elapsed=343.3s

  [6188/13157] intraday_3029.csv.gz  in=285,399,542 out=74,555,739 elapsed=343.3s

  [6189/13157] intraday_3031.csv.gz  in=285,411,285 out=74,555,739 elapsed=343.3s

  [6190/13157] intraday_3032.csv.gz  in=285,421,843 out=74,555,739 elapsed=343.4s

  [6191/13157] intraday_3033.csv.gz  in=285,435,660 out=74,555,739 elapsed=343.4s

  [6192/13157] intraday_3034.csv.gz  in=285,447,970 out=74,555,739 elapsed=343.4s

  [6193/13157] intraday_3035.csv.gz  in=285,478,087 out=74,555,739 elapsed=343.4s

  [6194/13157] intraday_3039.csv.gz  in=285,493,048 out=74,555,739 elapsed=343.6s

  [6195/13157] intraday_3038.csv.gz  in=285,506,588 out=74,555,739 elapsed=343.6s

  [6196/13157] intraday_3037.csv.gz  in=285,523,000 out=74,555,739 elapsed=343.6s

  [6197/13157] intraday_3036.csv.gz  in=285,546,661 out=74,555,739 elapsed=343.6s

  [6198/13157] intraday_3040.csv.gz  in=285,559,938 out=74,555,739 elapsed=343.7s

  [6199/13157] intraday_3041.csv.gz  in=285,573,265 out=74,555,739 elapsed=343.7s

  [6200/13157] intraday_3043.csv.gz  in=285,585,990 out=74,555,739 elapsed=343.8s

  [6201/13157] intraday_3042.csv.gz  in=285,600,803 out=74,555,739 elapsed=343.8s

  [6202/13157] intraday_3044.csv.gz  in=285,613,852 out=74,555,739 elapsed=343.8s

  [6203/13157] intraday_3046.csv.gz  in=285,626,667 out=74,555,739 elapsed=343.8s

  [6204/13157] intraday_3047.csv.gz  in=285,639,141 out=74,555,739 elapsed=343.8s

  [6205/13157] intraday_3045.csv.gz  in=285,652,209 out=74,555,739 elapsed=343.8s

  [6206/13157] intraday_3048.csv.gz  in=285,665,259 out=74,555,739 elapsed=343.8s

  [6207/13157] intraday_3049.csv.gz  in=285,678,383 out=74,555,739 elapsed=343.8s

  [6208/13157] intraday_3050.csv.gz  in=285,691,961 out=74,555,739 elapsed=343.9s

  [6209/13157] intraday_3051.csv.gz  in=285,704,428 out=74,555,739 elapsed=343.9s

  [6210/13157] intraday_3052.csv.gz  in=285,716,555 out=74,555,739 elapsed=343.9s

  [6211/13157] intraday_3053.csv.gz  in=285,731,780 out=74,555,739 elapsed=343.9s

  [6212/13157] intraday_3054.csv.gz  in=285,747,135 out=74,555,739 elapsed=343.9s

  [6213/13157] intraday_3055.csv.gz  in=285,764,371 out=74,555,739 elapsed=343.9s

  [6214/13157] intraday_3058.csv.gz  in=285,778,546 out=74,555,739 elapsed=344.0s

  [6215/13157] intraday_3056.csv.gz  in=285,791,763 out=74,555,739 elapsed=344.0s

  [6216/13157] intraday_3057.csv.gz  in=285,806,232 out=74,555,739 elapsed=344.0s

  [6217/13157] intraday_3059.csv.gz  in=285,820,082 out=74,555,739 elapsed=344.0s

  [6218/13157] intraday_3060.csv.gz  in=285,833,627 out=74,555,739 elapsed=344.0s

  [6219/13157] intraday_3061.csv.gz  in=285,847,910 out=74,555,739 elapsed=344.0s

  [6220/13157] intraday_3063.csv.gz  in=285,860,780 out=74,555,739 elapsed=344.0s

  [6221/13157] intraday_3062.csv.gz  in=285,877,682 out=74,555,739 elapsed=344.0s

  [6222/13157] intraday_3064.csv.gz  in=285,892,506 out=74,555,739 elapsed=344.1s

  [6223/13157] intraday_3066.csv.gz  in=285,906,107 out=74,555,739 elapsed=344.1s

  [6224/13157] intraday_3065.csv.gz  in=285,919,740 out=74,555,739 elapsed=344.1s

  [6225/13157] intraday_3067.csv.gz  in=285,931,459 out=74,555,739 elapsed=344.1s

  [6226/13157] intraday_3068.csv.gz  in=285,944,593 out=74,555,739 elapsed=344.1s

  [6227/13157] intraday_3070.csv.gz  in=285,960,487 out=74,555,739 elapsed=344.1s

  [6228/13157] intraday_3069.csv.gz  in=285,976,917 out=74,555,739 elapsed=344.1s

  [6229/13157] intraday_3071.csv.gz  in=285,991,571 out=74,555,739 elapsed=344.1s

  [6230/13157] intraday_3072.csv.gz  in=286,005,203 out=74,555,739 elapsed=344.2s

  [6231/13157] intraday_3075.csv.gz  in=286,018,637 out=74,555,739 elapsed=344.2s

  [6232/13157] intraday_3074.csv.gz  in=286,033,201 out=74,555,739 elapsed=344.2s

  [6233/13157] intraday_3073.csv.gz  in=286,048,162 out=74,555,739 elapsed=344.2s

  [6234/13157] intraday_3076.csv.gz  in=286,062,845 out=74,555,739 elapsed=344.3s

  [6235/13157] intraday_3078.csv.gz  in=286,077,933 out=74,555,739 elapsed=344.3s

  [6236/13157] intraday_3077.csv.gz  in=286,093,471 out=74,555,739 elapsed=344.3s

  [6237/13157] intraday_3079.csv.gz  in=286,110,344 out=74,555,739 elapsed=344.3s

  [6238/13157] intraday_3081.csv.gz  in=286,121,072 out=74,555,739 elapsed=344.4s

  [6239/13157] intraday_3082.csv.gz  in=286,134,526 out=74,555,739 elapsed=344.4s

  [6240/13157] intraday_3080.csv.gz  in=286,147,477 out=74,555,739 elapsed=344.4s

  [6241/13157] intraday_3083.csv.gz  in=286,159,689 out=74,555,739 elapsed=344.4s

  [6242/13157] intraday_3087.csv.gz  in=286,166,651 out=74,555,739 elapsed=344.7s

  [6243/13157] intraday_3086.csv.gz  in=286,177,326 out=74,555,739 elapsed=344.7s

  [6244/13157] intraday_3084.csv.gz  in=286,189,818 out=74,555,739 elapsed=344.7s

  [6245/13157] intraday_3085.csv.gz  in=286,197,951 out=74,555,739 elapsed=344.7s

  [6246/13157] intraday_3088.csv.gz  in=286,212,278 out=74,555,739 elapsed=344.8s

  [6247/13157] intraday_3090.csv.gz  in=286,224,590 out=74,555,739 elapsed=344.8s

  [6248/13157] intraday_3091.csv.gz  in=286,234,837 out=74,555,739 elapsed=344.8s

  [6249/13157] intraday_3089.csv.gz  in=286,249,070 out=74,555,739 elapsed=344.8s

  [6250/13157] intraday_3093.csv.gz  in=286,263,352 out=74,555,739 elapsed=344.9s

  [6251/13157] intraday_3094.csv.gz  in=286,275,840 out=74,555,739 elapsed=344.9s

  [6252/13157] intraday_3092.csv.gz  in=286,292,537 out=74,555,739 elapsed=344.9s

  [6253/13157] intraday_3095.csv.gz  in=286,304,681 out=74,555,739 elapsed=344.9s

  [6254/13157] intraday_3098.csv.gz  in=286,314,418 out=74,555,739 elapsed=345.0s

  [6255/13157] intraday_3096.csv.gz  in=286,327,800 out=74,555,739 elapsed=345.0s

  [6256/13157] intraday_3099.csv.gz  in=286,339,823 out=74,555,739 elapsed=345.0s

  [6257/13157] intraday_3097.csv.gz  in=286,353,179 out=74,555,739 elapsed=345.0s

  [6258/13157] intraday_3100.csv.gz  in=286,365,668 out=74,555,739 elapsed=345.0s

  [6259/13157] intraday_3104.csv.gz  in=286,378,962 out=74,555,739 elapsed=345.1s

  [6260/13157] intraday_3101.csv.gz  in=286,391,137 out=74,555,739 elapsed=345.1s

  [6261/13157] intraday_3102.csv.gz  in=286,402,238 out=74,555,739 elapsed=345.1s

  [6262/13157] intraday_3103.csv.gz  in=286,412,315 out=74,555,739 elapsed=345.1s

  [6263/13157] intraday_3107.csv.gz  in=286,424,012 out=74,555,739 elapsed=345.1s

  [6264/13157] intraday_3108.csv.gz  in=286,437,160 out=74,555,739 elapsed=345.1s

  [6265/13157] intraday_3106.csv.gz  in=286,447,652 out=74,555,739 elapsed=345.1s

  [6266/13157] intraday_3105.csv.gz  in=286,459,546 out=74,555,739 elapsed=345.1s

  [6267/13157] intraday_3109.csv.gz  in=286,470,646 out=74,555,739 elapsed=345.2s

  [6268/13157] intraday_3110.csv.gz  in=286,483,467 out=74,555,739 elapsed=345.3s

  [6269/13157] intraday_3111.csv.gz  in=286,496,491 out=74,555,739 elapsed=345.3s

  [6270/13157] intraday_3112.csv.gz  in=286,509,051 out=74,555,739 elapsed=345.3s

  [6271/13157] intraday_3113.csv.gz  in=286,519,058 out=74,555,739 elapsed=345.3s

  [6272/13157] intraday_3115.csv.gz  in=286,531,600 out=74,555,739 elapsed=345.3s

  [6273/13157] intraday_3116.csv.gz  in=286,543,578 out=74,555,739 elapsed=345.4s

  [6274/13157] intraday_3114.csv.gz  in=286,555,500 out=74,555,739 elapsed=345.4s

  [6275/13157] intraday_3117.csv.gz  in=286,569,755 out=74,555,739 elapsed=345.4s

  [6276/13157] intraday_3118.csv.gz  in=286,583,090 out=74,555,739 elapsed=345.4s

  [6277/13157] intraday_3119.csv.gz  in=286,595,909 out=74,555,739 elapsed=345.4s

  [6278/13157] intraday_3120.csv.gz  in=286,607,767 out=74,555,739 elapsed=345.4s

  [6279/13157] intraday_3121.csv.gz  in=286,620,745 out=74,555,739 elapsed=345.4s

  [6280/13157] intraday_3122.csv.gz  in=286,632,915 out=74,555,739 elapsed=345.5s

  [6281/13157] intraday_3125.csv.gz  in=286,643,728 out=74,555,739 elapsed=345.5s

  [6282/13157] intraday_3123.csv.gz  in=286,656,634 out=74,555,739 elapsed=345.5s

  [6283/13157] intraday_3124.csv.gz  in=286,667,127 out=74,555,739 elapsed=345.5s

  [6284/13157] intraday_3126.csv.gz  in=286,677,581 out=74,555,739 elapsed=345.5s

  [6285/13157] intraday_3128.csv.gz  in=286,690,962 out=74,555,739 elapsed=345.5s

  [6286/13157] intraday_3127.csv.gz  in=286,708,275 out=74,555,739 elapsed=345.5s

  [6287/13157] intraday_3129.csv.gz  in=286,721,616 out=74,555,739 elapsed=345.5s

  [6288/13157] intraday_3130.csv.gz  in=286,733,104 out=74,555,739 elapsed=345.6s

  [6289/13157] intraday_3133.csv.gz  in=286,745,420 out=74,555,739 elapsed=345.6s

  [6290/13157] intraday_3131.csv.gz  in=286,758,326 out=74,555,739 elapsed=345.6s

  [6291/13157] intraday_3132.csv.gz  in=286,769,240 out=74,555,739 elapsed=345.6s

  [6292/13157] intraday_3134.csv.gz  in=286,781,103 out=74,555,739 elapsed=345.6s

  [6293/13157] intraday_3135.csv.gz  in=286,791,912 out=74,555,739 elapsed=345.6s

  [6294/13157] intraday_3137.csv.gz  in=286,802,683 out=74,555,739 elapsed=345.7s

  [6295/13157] intraday_3138.csv.gz  in=286,814,862 out=74,555,739 elapsed=345.7s

  [6296/13157] intraday_3136.csv.gz  in=286,826,999 out=74,555,739 elapsed=345.7s

  [6297/13157] intraday_3141.csv.gz  in=286,836,987 out=74,555,739 elapsed=345.7s

  [6298/13157] intraday_3139.csv.gz  in=286,847,528 out=74,555,739 elapsed=345.7s

  [6299/13157] intraday_3142.csv.gz  in=286,860,572 out=74,555,739 elapsed=345.7s

  [6300/13157] intraday_3140.csv.gz  in=286,874,578 out=74,555,739 elapsed=345.7s

  [6301/13157] intraday_3144.csv.gz  in=286,885,510 out=74,555,739 elapsed=345.8s

  [6302/13157] intraday_3146.csv.gz  in=286,897,557 out=74,555,739 elapsed=345.8s

  [6303/13157] intraday_3143.csv.gz  in=286,910,362 out=74,555,739 elapsed=345.8s

  [6304/13157] intraday_3145.csv.gz  in=286,922,348 out=74,555,739 elapsed=345.8s

  [6305/13157] intraday_3147.csv.gz  in=286,933,918 out=74,555,739 elapsed=345.9s

  [6306/13157] intraday_3149.csv.gz  in=286,946,145 out=74,555,739 elapsed=345.9s

  [6307/13157] intraday_3148.csv.gz  in=286,957,735 out=74,555,739 elapsed=345.9s

  [6308/13157] intraday_3150.csv.gz  in=286,967,343 out=74,555,739 elapsed=345.9s

  [6309/13157] intraday_3153.csv.gz  in=286,978,434 out=74,555,739 elapsed=346.0s

  [6310/13157] intraday_3154.csv.gz  in=286,992,113 out=74,555,739 elapsed=346.0s

  [6311/13157] intraday_3151.csv.gz  in=287,004,158 out=74,555,739 elapsed=346.0s

  [6312/13157] intraday_3152.csv.gz  in=287,017,888 out=74,555,739 elapsed=346.0s

  [6313/13157] intraday_3155.csv.gz  in=287,031,003 out=74,555,739 elapsed=346.2s

  [6314/13157] intraday_3156.csv.gz  in=287,039,439 out=74,555,739 elapsed=346.2s

  [6315/13157] intraday_3158.csv.gz  in=287,051,430 out=74,555,739 elapsed=346.2s

  [6316/13157] intraday_3157.csv.gz  in=287,064,311 out=74,555,739 elapsed=346.2s

  [6317/13157] intraday_3159.csv.gz  in=287,076,185 out=74,555,739 elapsed=346.2s

  [6318/13157] intraday_3160.csv.gz  in=287,087,082 out=74,555,739 elapsed=346.2s

  [6319/13157] intraday_3162.csv.gz  in=287,097,595 out=74,555,739 elapsed=346.3s

  [6320/13157] intraday_3161.csv.gz  in=287,108,221 out=74,555,739 elapsed=346.3s

  [6321/13157] intraday_3164.csv.gz  in=287,120,802 out=74,555,739 elapsed=346.3s

  [6322/13157] intraday_3163.csv.gz  in=287,131,378 out=74,555,739 elapsed=346.3s

  [6323/13157] intraday_3167.csv.gz  in=287,142,332 out=74,555,739 elapsed=346.4s

  [6324/13157] intraday_3166.csv.gz  in=287,154,647 out=74,555,739 elapsed=346.4s

  [6325/13157] intraday_3168.csv.gz  in=287,164,947 out=74,555,739 elapsed=346.4s

  [6326/13157] intraday_3165.csv.gz  in=287,176,411 out=74,555,739 elapsed=346.4s

  [6327/13157] intraday_3171.csv.gz  in=287,185,714 out=74,555,739 elapsed=346.4s

  [6328/13157] intraday_3172.csv.gz  in=287,198,127 out=74,555,739 elapsed=346.5s

  [6329/13157] intraday_3169.csv.gz  in=287,211,624 out=74,555,739 elapsed=346.5s

  [6330/13157] intraday_3170.csv.gz  in=287,227,252 out=74,555,739 elapsed=346.5s

  [6331/13157] intraday_3173.csv.gz  in=287,236,974 out=74,555,739 elapsed=346.5s

  [6332/13157] intraday_3174.csv.gz  in=287,252,671 out=74,555,739 elapsed=346.5s

  [6333/13157] intraday_3177.csv.gz  in=287,264,023 out=74,555,739 elapsed=346.5s

  [6334/13157] intraday_3176.csv.gz  in=287,278,336 out=74,555,739 elapsed=346.5s

  [6335/13157] intraday_3175.csv.gz  in=287,289,244 out=74,555,739 elapsed=346.5s

  [6336/13157] intraday_3179.csv.gz  in=287,301,111 out=74,555,739 elapsed=346.5s

  [6337/13157] intraday_3181.csv.gz  in=287,313,497 out=74,555,739 elapsed=346.6s

  [6338/13157] intraday_3180.csv.gz  in=287,327,136 out=74,555,739 elapsed=346.6s

  [6339/13157] intraday_3178.csv.gz  in=287,342,461 out=74,555,739 elapsed=346.6s

  [6340/13157] intraday_3182.csv.gz  in=287,353,772 out=74,555,739 elapsed=346.6s

  [6341/13157] intraday_3183.csv.gz  in=287,365,920 out=74,555,739 elapsed=346.6s

  [6342/13157] intraday_3184.csv.gz  in=287,379,583 out=74,555,739 elapsed=346.6s

  [6343/13157] intraday_3185.csv.gz  in=287,390,947 out=74,555,739 elapsed=346.6s

  [6344/13157] intraday_3186.csv.gz  in=287,402,777 out=74,555,739 elapsed=346.6s

  [6345/13157] intraday_3187.csv.gz  in=287,414,575 out=74,555,739 elapsed=346.6s

  [6346/13157] intraday_3188.csv.gz  in=287,426,472 out=74,555,739 elapsed=346.7s

  [6347/13157] intraday_3189.csv.gz  in=287,437,410 out=74,555,739 elapsed=346.7s

  [6348/13157] intraday_3191.csv.gz  in=287,449,838 out=74,555,739 elapsed=346.7s

  [6349/13157] intraday_3190.csv.gz  in=287,462,558 out=74,555,739 elapsed=346.7s

  [6350/13157] intraday_3194.csv.gz  in=287,476,019 out=74,555,739 elapsed=346.7s

  [6351/13157] intraday_3192.csv.gz  in=287,496,551 out=74,555,739 elapsed=346.8s

  [6352/13157] intraday_3193.csv.gz  in=287,507,948 out=74,555,739 elapsed=346.8s

  [6353/13157] intraday_3195.csv.gz  in=287,521,872 out=74,555,739 elapsed=346.8s

  [6354/13157] intraday_3196.csv.gz  in=287,533,553 out=74,555,739 elapsed=346.8s

  [6355/13157] intraday_3197.csv.gz  in=287,546,165 out=74,555,739 elapsed=346.8s

  [6356/13157] intraday_3198.csv.gz  in=287,559,133 out=74,555,739 elapsed=346.8s

  [6357/13157] intraday_3199.csv.gz  in=287,570,842 out=74,555,739 elapsed=346.8s

  [6358/13157] intraday_3200.csv.gz  in=287,583,777 out=74,555,739 elapsed=346.9s

  [6359/13157] intraday_3202.csv.gz  in=287,597,197 out=74,555,739 elapsed=346.9s

  [6360/13157] intraday_3203.csv.gz  in=287,612,066 out=74,555,739 elapsed=346.9s

  [6361/13157] intraday_3201.csv.gz  in=287,624,757 out=74,555,739 elapsed=346.9s

  [6362/13157] intraday_3204.csv.gz  in=287,638,291 out=74,555,739 elapsed=346.9s

  [6363/13157] intraday_3205.csv.gz  in=287,649,956 out=74,555,739 elapsed=346.9s

  [6364/13157] intraday_3207.csv.gz  in=287,661,608 out=74,555,739 elapsed=346.9s

  [6365/13157] intraday_3206.csv.gz  in=287,674,302 out=74,555,739 elapsed=346.9s

  [6366/13157] intraday_3208.csv.gz  in=287,685,718 out=74,555,739 elapsed=347.0s

  [6367/13157] intraday_3209.csv.gz  in=287,697,395 out=74,555,739 elapsed=347.0s

  [6368/13157] intraday_3211.csv.gz  in=287,710,736 out=74,555,739 elapsed=347.0s

  [6369/13157] intraday_3210.csv.gz  in=287,734,730 out=74,555,739 elapsed=347.0s

  [6370/13157] intraday_3212.csv.gz  in=287,749,481 out=74,555,739 elapsed=347.0s

  [6371/13157] intraday_3214.csv.gz  in=287,762,445 out=74,555,739 elapsed=347.0s

  [6372/13157] intraday_3213.csv.gz  in=287,773,603 out=74,555,739 elapsed=347.0s

  [6373/13157] intraday_3215.csv.gz  in=287,786,325 out=74,555,739 elapsed=347.0s

  [6374/13157] intraday_3217.csv.gz  in=287,799,360 out=74,555,739 elapsed=347.1s

  [6375/13157] intraday_3216.csv.gz  in=287,811,775 out=74,555,739 elapsed=347.1s

  [6376/13157] intraday_3219.csv.gz  in=287,825,275 out=74,555,739 elapsed=347.1s

  [6377/13157] intraday_3218.csv.gz  in=287,840,602 out=74,555,739 elapsed=347.1s

  [6378/13157] intraday_3221.csv.gz  in=287,853,284 out=74,555,739 elapsed=347.2s

  [6379/13157] intraday_3220.csv.gz  in=287,866,527 out=74,555,739 elapsed=347.2s

  [6380/13157] intraday_3223.csv.gz  in=287,878,985 out=74,555,739 elapsed=347.2s

  [6381/13157] intraday_3222.csv.gz  in=287,890,251 out=74,555,739 elapsed=347.2s

  [6382/13157] intraday_3224.csv.gz  in=287,900,057 out=74,555,739 elapsed=347.2s

  [6383/13157] intraday_3227.csv.gz  in=287,910,398 out=74,555,739 elapsed=347.2s

  [6384/13157] intraday_3226.csv.gz  in=287,916,989 out=74,555,739 elapsed=347.2s

  [6385/13157] intraday_3225.csv.gz  in=287,930,731 out=74,555,739 elapsed=347.2s

  [6386/13157] intraday_3228.csv.gz  in=287,939,150 out=74,555,739 elapsed=347.2s

  [6387/13157] intraday_3229.csv.gz  in=287,953,504 out=74,555,739 elapsed=347.2s

  [6388/13157] intraday_3232.csv.gz  in=287,963,401 out=74,555,739 elapsed=347.3s

  [6389/13157] intraday_3230.csv.gz  in=287,976,886 out=74,555,739 elapsed=347.3s

  [6390/13157] intraday_3231.csv.gz  in=287,988,551 out=74,555,739 elapsed=347.3s

  [6391/13157] intraday_3233.csv.gz  in=288,002,578 out=74,555,739 elapsed=347.3s

  [6392/13157] intraday_3234.csv.gz  in=288,016,554 out=74,555,739 elapsed=347.3s

  [6393/13157] intraday_3235.csv.gz  in=288,028,985 out=74,555,739 elapsed=347.4s

  [6394/13157] intraday_3237.csv.gz  in=288,041,934 out=74,555,739 elapsed=347.4s

  [6395/13157] intraday_3236.csv.gz  in=288,053,727 out=74,555,739 elapsed=347.4s

  [6396/13157] intraday_3239.csv.gz  in=288,063,187 out=74,555,739 elapsed=347.4s

  [6397/13157] intraday_3238.csv.gz  in=288,075,828 out=74,555,739 elapsed=347.4s

  [6398/13157] intraday_3241.csv.gz  in=288,087,754 out=74,555,739 elapsed=347.4s

  [6399/13157] intraday_3240.csv.gz  in=288,099,922 out=74,555,739 elapsed=347.4s

  [6400/13157] intraday_3242.csv.gz  in=288,111,526 out=74,555,739 elapsed=347.5s

  [6401/13157] intraday_3243.csv.gz  in=288,122,785 out=74,555,739 elapsed=347.5s

  [6402/13157] intraday_3245.csv.gz  in=288,135,633 out=74,555,739 elapsed=347.5s

  [6403/13157] intraday_3244.csv.gz  in=288,151,656 out=74,555,739 elapsed=347.5s

  [6404/13157] intraday_3246.csv.gz  in=288,162,896 out=74,555,739 elapsed=347.5s

  [6405/13157] intraday_3247.csv.gz  in=288,173,057 out=74,555,739 elapsed=347.5s

  [6406/13157] intraday_3248.csv.gz  in=288,184,438 out=74,555,739 elapsed=347.5s

  [6407/13157] intraday_3249.csv.gz  in=288,197,287 out=74,555,739 elapsed=347.5s

  [6408/13157] intraday_3250.csv.gz  in=288,208,470 out=74,555,739 elapsed=347.6s

  [6409/13157] intraday_3252.csv.gz  in=288,220,831 out=74,555,739 elapsed=347.6s

  [6410/13157] intraday_3251.csv.gz  in=288,232,544 out=74,555,739 elapsed=347.6s

  [6411/13157] intraday_3253.csv.gz  in=288,244,602 out=74,555,739 elapsed=347.6s

  [6412/13157] intraday_3254.csv.gz  in=288,258,657 out=74,555,739 elapsed=347.7s

  [6413/13157] intraday_3257.csv.gz  in=288,269,997 out=74,555,739 elapsed=347.7s

  [6414/13157] intraday_3255.csv.gz  in=288,281,967 out=74,555,739 elapsed=347.7s

  [6415/13157] intraday_3256.csv.gz  in=288,294,870 out=74,555,739 elapsed=347.7s

  [6416/13157] intraday_3258.csv.gz  in=288,309,782 out=74,555,739 elapsed=347.7s

  [6417/13157] intraday_3261.csv.gz  in=288,320,440 out=74,555,739 elapsed=347.8s

  [6418/13157] intraday_3259.csv.gz  in=288,334,193 out=74,555,739 elapsed=347.8s

  [6419/13157] intraday_3262.csv.gz  in=288,346,136 out=74,555,739 elapsed=347.8s

  [6420/13157] intraday_3260.csv.gz  in=288,359,235 out=74,555,739 elapsed=347.8s

  [6421/13157] intraday_3263.csv.gz  in=288,371,407 out=74,555,739 elapsed=347.8s

  [6422/13157] intraday_3266.csv.gz  in=288,382,211 out=74,555,739 elapsed=347.8s

  [6423/13157] intraday_3265.csv.gz  in=288,396,602 out=74,555,739 elapsed=347.8s

  [6424/13157] intraday_3264.csv.gz  in=288,409,151 out=74,555,739 elapsed=347.8s

  [6425/13157] intraday_3267.csv.gz  in=288,424,750 out=74,555,739 elapsed=347.9s

  [6426/13157] intraday_3270.csv.gz  in=288,437,212 out=74,555,739 elapsed=347.9s

  [6427/13157] intraday_3269.csv.gz  in=288,450,749 out=74,555,739 elapsed=347.9s

  [6428/13157] intraday_3268.csv.gz  in=288,461,395 out=74,555,739 elapsed=347.9s

  [6429/13157] intraday_3274.csv.gz  in=288,472,613 out=74,555,739 elapsed=348.1s

  [6430/13157] intraday_3271.csv.gz  in=288,483,130 out=74,555,739 elapsed=348.1s

  [6431/13157] intraday_3272.csv.gz  in=288,495,745 out=74,555,739 elapsed=348.1s

  [6432/13157] intraday_3273.csv.gz  in=288,505,884 out=74,555,739 elapsed=348.1s

  [6433/13157] intraday_3276.csv.gz  in=288,516,359 out=74,555,739 elapsed=348.1s

  [6434/13157] intraday_3275.csv.gz  in=288,528,140 out=74,555,739 elapsed=348.1s

  [6435/13157] intraday_3278.csv.gz  in=288,539,046 out=74,555,739 elapsed=348.1s

  [6436/13157] intraday_3277.csv.gz  in=288,556,450 out=74,555,739 elapsed=348.1s

  [6437/13157] intraday_3280.csv.gz  in=288,567,228 out=74,555,739 elapsed=348.2s

  [6438/13157] intraday_3279.csv.gz  in=288,578,192 out=74,555,739 elapsed=348.2s

  [6439/13157] intraday_3282.csv.gz  in=288,587,665 out=74,555,739 elapsed=348.2s

  [6440/13157] intraday_3281.csv.gz  in=288,600,331 out=74,555,739 elapsed=348.2s

  [6441/13157] intraday_3283.csv.gz  in=288,614,806 out=74,555,739 elapsed=348.2s

  [6442/13157] intraday_3284.csv.gz  in=288,625,340 out=74,555,739 elapsed=348.2s

  [6443/13157] intraday_3285.csv.gz  in=288,635,187 out=74,555,739 elapsed=348.3s

  [6444/13157] intraday_3287.csv.gz  in=288,647,000 out=74,555,739 elapsed=348.3s

  [6445/13157] intraday_3286.csv.gz  in=288,658,414 out=74,555,739 elapsed=348.3s

  [6446/13157] intraday_3288.csv.gz  in=288,669,200 out=74,555,739 elapsed=348.3s

  [6447/13157] intraday_3291.csv.gz  in=288,678,759 out=74,555,739 elapsed=348.4s

  [6448/13157] intraday_3290.csv.gz  in=288,689,954 out=74,555,739 elapsed=348.5s

  [6449/13157] intraday_3292.csv.gz  in=288,701,994 out=74,555,739 elapsed=348.5s

  [6450/13157] intraday_3293.csv.gz  in=288,715,174 out=74,555,739 elapsed=348.5s

  [6451/13157] intraday_3289.csv.gz  in=288,738,239 out=74,555,739 elapsed=348.5s

  [6452/13157] intraday_3294.csv.gz  in=288,755,741 out=74,555,739 elapsed=348.5s

  [6453/13157] intraday_3295.csv.gz  in=288,768,450 out=74,555,739 elapsed=348.7s

  [6454/13157] intraday_3297.csv.gz  in=288,777,891 out=74,555,739 elapsed=348.7s

  [6455/13157] intraday_3296.csv.gz  in=288,790,901 out=74,555,739 elapsed=348.7s

  [6456/13157] intraday_3298.csv.gz  in=288,802,417 out=74,555,739 elapsed=348.7s

  [6457/13157] intraday_3299.csv.gz  in=288,813,176 out=74,555,739 elapsed=348.8s

  [6458/13157] intraday_3300.csv.gz  in=288,824,728 out=74,555,739 elapsed=348.8s

  [6459/13157] intraday_3302.csv.gz  in=288,836,072 out=74,555,739 elapsed=348.8s

  [6460/13157] intraday_3301.csv.gz  in=288,847,479 out=74,555,739 elapsed=348.8s

  [6461/13157] intraday_3303.csv.gz  in=288,857,325 out=74,555,739 elapsed=348.8s

  [6462/13157] intraday_3304.csv.gz  in=288,868,430 out=74,555,739 elapsed=349.0s

  [6463/13157] intraday_3306.csv.gz  in=288,879,528 out=74,555,739 elapsed=349.0s

  [6464/13157] intraday_3307.csv.gz  in=288,891,451 out=74,555,739 elapsed=349.0s

  [6465/13157] intraday_3305.csv.gz  in=288,904,133 out=74,555,739 elapsed=349.0s

  [6466/13157] intraday_3308.csv.gz  in=288,913,518 out=74,555,739 elapsed=349.0s

  [6467/13157] intraday_3312.csv.gz  in=288,923,647 out=74,555,739 elapsed=349.1s

  [6468/13157] intraday_3309.csv.gz  in=288,934,226 out=74,555,739 elapsed=349.1s

  [6469/13157] intraday_3311.csv.gz  in=288,948,333 out=74,555,739 elapsed=349.1s

  [6470/13157] intraday_3310.csv.gz  in=288,961,011 out=74,555,739 elapsed=349.2s

  [6471/13157] intraday_3314.csv.gz  in=288,970,347 out=74,555,739 elapsed=349.3s

  [6472/13157] intraday_3313.csv.gz  in=288,981,602 out=74,555,739 elapsed=349.3s

  [6473/13157] intraday_3315.csv.gz  in=288,994,877 out=74,555,739 elapsed=349.3s

  [6474/13157] intraday_3316.csv.gz  in=289,006,348 out=74,555,739 elapsed=349.3s

  [6475/13157] intraday_3319.csv.gz  in=289,020,818 out=74,555,739 elapsed=349.3s

  [6476/13157] intraday_3318.csv.gz  in=289,031,876 out=74,555,739 elapsed=349.4s

  [6477/13157] intraday_3317.csv.gz  in=289,046,545 out=74,555,739 elapsed=349.4s

  [6478/13157] intraday_3320.csv.gz  in=289,059,511 out=74,555,739 elapsed=349.4s

  [6479/13157] intraday_3324.csv.gz  in=289,071,019 out=74,555,739 elapsed=349.4s

  [6480/13157] intraday_3323.csv.gz  in=289,081,346 out=74,555,739 elapsed=349.4s

  [6481/13157] intraday_3322.csv.gz  in=289,094,056 out=74,555,739 elapsed=349.4s

  [6482/13157] intraday_3321.csv.gz  in=289,106,757 out=74,555,739 elapsed=349.4s

  [6483/13157] intraday_3327.csv.gz  in=289,117,414 out=74,555,739 elapsed=349.4s

  [6484/13157] intraday_3326.csv.gz  in=289,128,190 out=74,555,739 elapsed=349.5s

  [6485/13157] intraday_3325.csv.gz  in=289,142,565 out=74,555,739 elapsed=349.5s

  [6486/13157] intraday_3328.csv.gz  in=289,154,144 out=74,555,739 elapsed=349.5s

  [6487/13157] intraday_3329.csv.gz  in=289,166,524 out=74,555,739 elapsed=349.6s

  [6488/13157] intraday_3332.csv.gz  in=289,178,169 out=74,555,739 elapsed=349.6s

  [6489/13157] intraday_3331.csv.gz  in=289,189,999 out=74,555,739 elapsed=349.6s

  [6490/13157] intraday_3333.csv.gz  in=289,201,531 out=74,555,739 elapsed=349.6s

  [6491/13157] intraday_3330.csv.gz  in=289,213,343 out=74,555,739 elapsed=349.6s

  [6492/13157] intraday_3334.csv.gz  in=289,223,999 out=74,555,739 elapsed=349.7s

  [6493/13157] intraday_3335.csv.gz  in=289,237,778 out=74,555,739 elapsed=349.7s

  [6494/13157] intraday_3336.csv.gz  in=289,251,195 out=74,555,739 elapsed=349.7s

  [6495/13157] intraday_3337.csv.gz  in=289,262,628 out=74,555,739 elapsed=349.7s

  [6496/13157] intraday_3338.csv.gz  in=289,274,693 out=74,555,739 elapsed=349.7s

  [6497/13157] intraday_3339.csv.gz  in=289,291,069 out=74,555,739 elapsed=349.7s

  [6498/13157] intraday_3340.csv.gz  in=289,302,317 out=74,555,739 elapsed=349.7s

  [6499/13157] intraday_3341.csv.gz  in=289,314,742 out=74,555,739 elapsed=349.7s

  [6500/13157] intraday_3342.csv.gz  in=289,328,030 out=74,555,739 elapsed=349.8s

  [6501/13157] intraday_3345.csv.gz  in=289,341,929 out=74,555,739 elapsed=349.8s

  [6502/13157] intraday_3343.csv.gz  in=289,354,315 out=74,555,739 elapsed=349.8s

  [6503/13157] intraday_3344.csv.gz  in=289,369,180 out=74,555,739 elapsed=349.8s

  [6504/13157] intraday_3347.csv.gz  in=289,381,814 out=74,555,739 elapsed=349.8s

  [6505/13157] intraday_3346.csv.gz  in=289,393,801 out=74,555,739 elapsed=349.8s

  [6506/13157] intraday_3348.csv.gz  in=289,406,663 out=74,555,739 elapsed=349.9s

  [6507/13157] intraday_3349.csv.gz  in=289,425,371 out=74,555,739 elapsed=349.9s

  [6508/13157] intraday_3350.csv.gz  in=289,435,385 out=74,555,739 elapsed=349.9s

  [6509/13157] intraday_3351.csv.gz  in=289,448,732 out=74,555,739 elapsed=349.9s

  [6510/13157] intraday_3352.csv.gz  in=289,461,245 out=74,555,739 elapsed=349.9s

  [6511/13157] intraday_3353.csv.gz  in=289,477,148 out=74,555,739 elapsed=350.1s

  [6512/13157] intraday_3356.csv.gz  in=289,489,977 out=74,555,739 elapsed=350.1s

  [6513/13157] intraday_3355.csv.gz  in=289,501,484 out=74,555,739 elapsed=350.1s

  [6514/13157] intraday_3354.csv.gz  in=289,512,938 out=74,555,739 elapsed=350.1s

  [6515/13157] intraday_3357.csv.gz  in=289,525,475 out=74,555,739 elapsed=350.2s

  [6516/13157] intraday_3358.csv.gz  in=289,537,777 out=74,555,739 elapsed=350.2s

  [6517/13157] intraday_3360.csv.gz  in=289,550,570 out=74,555,739 elapsed=350.2s

  [6518/13157] intraday_3359.csv.gz  in=289,565,334 out=74,555,739 elapsed=350.2s

  [6519/13157] intraday_3362.csv.gz  in=289,578,290 out=74,555,739 elapsed=350.3s

  [6520/13157] intraday_3363.csv.gz  in=289,589,092 out=74,555,739 elapsed=350.3s

  [6521/13157] intraday_3361.csv.gz  in=289,601,708 out=74,555,739 elapsed=350.3s

  [6522/13157] intraday_3364.csv.gz  in=289,617,922 out=74,555,739 elapsed=350.3s

  [6523/13157] intraday_3365.csv.gz  in=289,627,554 out=74,555,739 elapsed=350.4s

  [6524/13157] intraday_3366.csv.gz  in=289,640,760 out=74,555,739 elapsed=350.4s

  [6525/13157] intraday_3368.csv.gz  in=289,650,333 out=74,555,739 elapsed=350.4s

  [6526/13157] intraday_3367.csv.gz  in=289,657,010 out=74,555,739 elapsed=350.4s

  [6527/13157] intraday_3372.csv.gz  in=289,668,577 out=74,555,739 elapsed=350.7s

  [6528/13157] intraday_3369.csv.gz  in=289,678,945 out=74,555,739 elapsed=350.7s

  [6529/13157] intraday_3371.csv.gz  in=289,692,724 out=74,555,739 elapsed=350.7s

  [6530/13157] intraday_3370.csv.gz  in=289,707,592 out=74,555,739 elapsed=350.7s

  [6531/13157] intraday_3373.csv.gz  in=289,717,936 out=74,555,739 elapsed=351.0s

  [6532/13157] intraday_3374.csv.gz  in=289,732,517 out=74,555,739 elapsed=351.0s

  [6533/13157] intraday_3375.csv.gz  in=289,747,103 out=74,555,739 elapsed=351.0s

  [6534/13157] intraday_3376.csv.gz  in=289,759,870 out=74,555,739 elapsed=351.1s

  [6535/13157] intraday_3380.csv.gz  in=289,769,457 out=74,555,739 elapsed=351.1s

  [6536/13157] intraday_3378.csv.gz  in=289,783,140 out=74,555,739 elapsed=351.3s

  [6537/13157] intraday_3377.csv.gz  in=289,795,307 out=74,555,739 elapsed=351.3s

  [6538/13157] intraday_3379.csv.gz  in=289,808,856 out=74,555,739 elapsed=351.3s

  [6539/13157] intraday_3381.csv.gz  in=289,820,716 out=74,555,739 elapsed=351.3s

  [6540/13157] intraday_3383.csv.gz  in=289,830,900 out=74,555,739 elapsed=351.5s

  [6541/13157] intraday_3384.csv.gz  in=289,842,666 out=74,555,739 elapsed=351.5s

  [6542/13157] intraday_3382.csv.gz  in=289,855,461 out=74,555,739 elapsed=351.5s

  [6543/13157] intraday_3385.csv.gz  in=289,866,792 out=74,555,739 elapsed=351.5s

  [6544/13157] intraday_3387.csv.gz  in=289,878,947 out=74,555,739 elapsed=351.6s

  [6545/13157] intraday_3388.csv.gz  in=289,890,515 out=74,555,739 elapsed=351.6s

  [6546/13157] intraday_3389.csv.gz  in=289,902,911 out=74,555,739 elapsed=351.6s

  [6547/13157] intraday_3386.csv.gz  in=289,915,400 out=74,555,739 elapsed=351.6s

  [6548/13157] intraday_3391.csv.gz  in=289,926,770 out=74,555,739 elapsed=351.7s

  [6549/13157] intraday_3392.csv.gz  in=289,938,922 out=74,555,739 elapsed=351.7s

  [6550/13157] intraday_3393.csv.gz  in=289,951,648 out=74,555,739 elapsed=351.7s

  [6551/13157] intraday_3390.csv.gz  in=289,964,431 out=74,555,739 elapsed=351.7s

  [6552/13157] intraday_3395.csv.gz  in=289,975,586 out=74,555,739 elapsed=351.7s

  [6553/13157] intraday_3394.csv.gz  in=289,987,497 out=74,555,739 elapsed=351.7s

  [6554/13157] intraday_3396.csv.gz  in=289,999,175 out=74,555,739 elapsed=351.7s

  [6555/13157] intraday_3397.csv.gz  in=290,011,966 out=74,555,739 elapsed=351.7s

  [6556/13157] intraday_3399.csv.gz  in=290,028,294 out=74,555,739 elapsed=351.8s

  [6557/13157] intraday_3400.csv.gz  in=290,040,658 out=74,555,739 elapsed=351.8s

  [6558/13157] intraday_3401.csv.gz  in=290,053,235 out=74,555,739 elapsed=351.8s

  [6559/13157] intraday_3398.csv.gz  in=290,067,308 out=74,555,739 elapsed=351.8s

  [6560/13157] intraday_3403.csv.gz  in=290,080,418 out=74,555,739 elapsed=351.9s

  [6561/13157] intraday_3402.csv.gz  in=290,092,285 out=74,555,739 elapsed=351.9s

  [6562/13157] intraday_3404.csv.gz  in=290,105,000 out=74,555,739 elapsed=352.0s

  [6563/13157] intraday_3405.csv.gz  in=290,117,228 out=74,555,739 elapsed=352.0s

  [6564/13157] intraday_3407.csv.gz  in=290,127,034 out=74,555,739 elapsed=352.0s

  [6565/13157] intraday_3406.csv.gz  in=290,137,999 out=74,555,739 elapsed=352.0s

  [6566/13157] intraday_3409.csv.gz  in=290,147,574 out=74,555,739 elapsed=352.1s

  [6567/13157] intraday_3408.csv.gz  in=290,159,193 out=74,555,739 elapsed=352.1s

  [6568/13157] intraday_3410.csv.gz  in=290,173,683 out=74,555,739 elapsed=352.1s

  [6569/13157] intraday_3411.csv.gz  in=290,186,277 out=74,555,739 elapsed=352.1s

  [6570/13157] intraday_3412.csv.gz  in=290,198,905 out=74,555,739 elapsed=352.2s

  [6571/13157] intraday_3413.csv.gz  in=290,210,337 out=74,555,739 elapsed=352.2s

  [6572/13157] intraday_3415.csv.gz  in=290,223,288 out=74,555,739 elapsed=352.2s

  [6573/13157] intraday_3414.csv.gz  in=290,233,935 out=74,555,739 elapsed=352.2s

  [6574/13157] intraday_3416.csv.gz  in=290,244,503 out=74,555,739 elapsed=352.3s

  [6575/13157] intraday_3418.csv.gz  in=290,256,440 out=74,555,739 elapsed=352.3s

  [6576/13157] intraday_3419.csv.gz  in=290,267,990 out=74,555,739 elapsed=352.3s

  [6577/13157] intraday_3417.csv.gz  in=290,278,503 out=74,555,739 elapsed=352.3s

  [6578/13157] intraday_3422.csv.gz  in=290,288,136 out=74,555,739 elapsed=352.3s

  [6579/13157] intraday_3421.csv.gz  in=290,300,102 out=74,555,739 elapsed=352.3s

  [6580/13157] intraday_3420.csv.gz  in=290,311,440 out=74,555,739 elapsed=352.3s

  [6581/13157] intraday_3423.csv.gz  in=290,324,902 out=74,555,739 elapsed=352.3s

  [6582/13157] intraday_3424.csv.gz  in=290,336,552 out=74,555,739 elapsed=352.4s

  [6583/13157] intraday_3425.csv.gz  in=290,347,165 out=74,555,739 elapsed=352.4s

  [6584/13157] intraday_3426.csv.gz  in=290,357,057 out=74,555,739 elapsed=352.4s

  [6585/13157] intraday_3427.csv.gz  in=290,369,200 out=74,555,739 elapsed=352.4s

  [6586/13157] intraday_3428.csv.gz  in=290,382,213 out=74,555,739 elapsed=352.4s

  [6587/13157] intraday_3429.csv.gz  in=290,393,438 out=74,555,739 elapsed=352.4s

  [6588/13157] intraday_3431.csv.gz  in=290,405,973 out=74,555,739 elapsed=352.4s

  [6589/13157] intraday_3430.csv.gz  in=290,417,142 out=74,555,739 elapsed=352.4s

  [6590/13157] intraday_3432.csv.gz  in=290,426,673 out=74,555,739 elapsed=352.5s

  [6591/13157] intraday_3435.csv.gz  in=290,437,116 out=74,555,739 elapsed=352.5s

  [6592/13157] intraday_3434.csv.gz  in=290,451,115 out=74,555,739 elapsed=352.5s

  [6593/13157] intraday_3433.csv.gz  in=290,465,065 out=74,555,739 elapsed=352.5s

  [6594/13157] intraday_3437.csv.gz  in=290,478,273 out=74,555,739 elapsed=352.5s

  [6595/13157] intraday_3438.csv.gz  in=290,487,707 out=74,555,739 elapsed=352.5s

  [6596/13157] intraday_3436.csv.gz  in=290,500,944 out=74,555,739 elapsed=352.5s

  [6597/13157] intraday_3439.csv.gz  in=290,512,154 out=74,555,739 elapsed=352.5s

  [6598/13157] intraday_3443.csv.gz  in=290,523,510 out=74,555,739 elapsed=352.6s

  [6599/13157] intraday_3442.csv.gz  in=290,532,585 out=74,555,739 elapsed=352.6s

  [6600/13157] intraday_3441.csv.gz  in=290,546,025 out=74,555,739 elapsed=352.6s

  [6601/13157] intraday_3440.csv.gz  in=290,557,576 out=74,555,739 elapsed=352.6s

  [6602/13157] intraday_3446.csv.gz  in=290,569,726 out=74,555,739 elapsed=352.6s

  [6603/13157] intraday_3444.csv.gz  in=290,580,810 out=74,555,739 elapsed=352.6s

  [6604/13157] intraday_3447.csv.gz  in=290,593,465 out=74,555,739 elapsed=352.6s

  [6605/13157] intraday_3445.csv.gz  in=290,605,639 out=74,555,739 elapsed=352.6s

  [6606/13157] intraday_3449.csv.gz  in=290,615,124 out=74,555,739 elapsed=352.7s

  [6607/13157] intraday_3450.csv.gz  in=290,625,864 out=74,555,739 elapsed=352.7s

  [6608/13157] intraday_3448.csv.gz  in=290,636,378 out=74,555,739 elapsed=352.7s

  [6609/13157] intraday_3453.csv.gz  in=290,647,812 out=74,555,739 elapsed=352.8s

  [6610/13157] intraday_3451.csv.gz  in=290,663,752 out=74,555,739 elapsed=352.8s

  [6611/13157] intraday_3454.csv.gz  in=290,674,308 out=74,555,739 elapsed=352.8s

  [6612/13157] intraday_3452.csv.gz  in=290,687,062 out=74,555,739 elapsed=352.8s

  [6613/13157] intraday_3456.csv.gz  in=290,699,355 out=74,555,739 elapsed=352.8s

  [6614/13157] intraday_3458.csv.gz  in=290,711,853 out=74,555,739 elapsed=352.8s

  [6615/13157] intraday_3457.csv.gz  in=290,725,626 out=74,555,739 elapsed=352.8s

  [6616/13157] intraday_3455.csv.gz  in=290,736,093 out=74,555,739 elapsed=352.8s

  [6617/13157] intraday_3459.csv.gz  in=290,748,845 out=74,555,739 elapsed=352.9s

  [6618/13157] intraday_3462.csv.gz  in=290,762,187 out=74,555,739 elapsed=352.9s

  [6619/13157] intraday_3460.csv.gz  in=290,776,356 out=74,555,739 elapsed=352.9s

  [6620/13157] intraday_3461.csv.gz  in=290,789,888 out=74,555,739 elapsed=352.9s

  [6621/13157] intraday_3463.csv.gz  in=290,801,685 out=74,555,739 elapsed=352.9s

  [6622/13157] intraday_3466.csv.gz  in=290,815,103 out=74,555,739 elapsed=353.0s

  [6623/13157] intraday_3465.csv.gz  in=290,825,655 out=74,555,739 elapsed=353.0s

  [6624/13157] intraday_3464.csv.gz  in=290,838,261 out=74,555,739 elapsed=353.0s

  [6625/13157] intraday_3468.csv.gz  in=290,850,981 out=74,555,739 elapsed=353.1s

  [6626/13157] intraday_3469.csv.gz  in=290,861,192 out=74,555,739 elapsed=353.1s

  [6627/13157] intraday_3470.csv.gz  in=290,874,038 out=74,555,739 elapsed=353.1s

  [6628/13157] intraday_3467.csv.gz  in=290,885,755 out=74,555,739 elapsed=353.1s

  [6629/13157] intraday_3471.csv.gz  in=290,898,107 out=74,555,739 elapsed=353.3s

  [6630/13157] intraday_3472.csv.gz  in=290,910,821 out=74,555,739 elapsed=353.3s

  [6631/13157] intraday_3474.csv.gz  in=290,922,175 out=74,555,739 elapsed=353.3s

  [6632/13157] intraday_3473.csv.gz  in=290,936,261 out=74,555,739 elapsed=353.3s

  [6633/13157] intraday_3478.csv.gz  in=290,948,461 out=74,555,739 elapsed=353.4s

  [6634/13157] intraday_3475.csv.gz  in=290,960,504 out=74,555,739 elapsed=353.4s

  [6635/13157] intraday_3477.csv.gz  in=290,974,446 out=74,555,739 elapsed=353.4s

  [6636/13157] intraday_3476.csv.gz  in=290,989,432 out=74,555,739 elapsed=353.4s

  [6637/13157] intraday_3479.csv.gz  in=291,002,095 out=74,555,739 elapsed=353.4s

  [6638/13157] intraday_3480.csv.gz  in=291,014,493 out=74,555,739 elapsed=353.4s

  [6639/13157] intraday_3481.csv.gz  in=291,026,909 out=74,555,739 elapsed=353.4s

  [6640/13157] intraday_3482.csv.gz  in=291,040,492 out=74,555,739 elapsed=353.4s

  [6641/13157] intraday_3483.csv.gz  in=291,055,347 out=74,555,739 elapsed=353.4s

  [6642/13157] intraday_3484.csv.gz  in=291,067,111 out=74,555,739 elapsed=353.4s

  [6643/13157] intraday_3488.csv.gz  in=291,078,221 out=74,555,739 elapsed=353.7s

  [6644/13157] intraday_3486.csv.gz  in=291,090,231 out=74,555,739 elapsed=353.7s

  [6645/13157] intraday_3487.csv.gz  in=291,102,689 out=74,555,739 elapsed=353.7s

  [6646/13157] intraday_3485.csv.gz  in=291,118,919 out=74,555,739 elapsed=353.7s

  [6647/13157] intraday_3490.csv.gz  in=291,129,117 out=74,555,739 elapsed=353.8s

  [6648/13157] intraday_3491.csv.gz  in=291,143,885 out=74,555,739 elapsed=354.0s

  [6649/13157] intraday_3492.csv.gz  in=291,156,434 out=74,555,739 elapsed=354.0s

  [6650/13157] intraday_3489.csv.gz  in=291,169,421 out=74,555,739 elapsed=354.0s

  [6651/13157] intraday_3493.csv.gz  in=291,183,905 out=74,555,739 elapsed=354.0s

  [6652/13157] intraday_3494.csv.gz  in=291,196,369 out=74,555,739 elapsed=354.0s

  [6653/13157] intraday_3495.csv.gz  in=291,209,368 out=74,555,739 elapsed=354.1s

  [6654/13157] intraday_3496.csv.gz  in=291,221,805 out=74,555,739 elapsed=354.1s

  [6655/13157] intraday_3497.csv.gz  in=291,234,935 out=74,555,739 elapsed=354.1s

  [6656/13157] intraday_3498.csv.gz  in=291,247,576 out=74,555,739 elapsed=354.1s

  [6657/13157] intraday_3500.csv.gz  in=291,262,166 out=74,555,739 elapsed=354.1s

  [6658/13157] intraday_3499.csv.gz  in=291,276,747 out=74,555,739 elapsed=354.1s

  [6659/13157] intraday_3502.csv.gz  in=291,290,114 out=74,555,739 elapsed=354.2s

  [6660/13157] intraday_3503.csv.gz  in=291,301,844 out=74,555,739 elapsed=354.2s

  [6661/13157] intraday_3504.csv.gz  in=291,312,522 out=74,555,739 elapsed=354.2s

  [6662/13157] intraday_3501.csv.gz  in=291,325,668 out=74,555,739 elapsed=354.2s

  [6663/13157] intraday_3507.csv.gz  in=291,334,054 out=74,555,739 elapsed=354.3s

  [6664/13157] intraday_3506.csv.gz  in=291,347,165 out=74,555,739 elapsed=354.3s

  [6665/13157] intraday_3508.csv.gz  in=291,355,904 out=74,555,739 elapsed=354.3s

  [6666/13157] intraday_3505.csv.gz  in=291,367,743 out=74,555,739 elapsed=354.3s

  [6667/13157] intraday_3511.csv.gz  in=291,381,140 out=74,555,739 elapsed=354.5s

  [6668/13157] intraday_3510.csv.gz  in=291,395,347 out=74,555,739 elapsed=354.5s

  [6669/13157] intraday_3512.csv.gz  in=291,407,641 out=74,555,739 elapsed=354.5s

  [6670/13157] intraday_3509.csv.gz  in=291,420,162 out=74,555,739 elapsed=354.5s

  [6671/13157] intraday_3513.csv.gz  in=291,430,150 out=74,555,739 elapsed=354.5s

  [6672/13157] intraday_3515.csv.gz  in=291,443,748 out=74,555,739 elapsed=354.5s

  [6673/13157] intraday_3516.csv.gz  in=291,456,344 out=74,555,739 elapsed=354.5s

  [6674/13157] intraday_3514.csv.gz  in=291,469,858 out=74,555,739 elapsed=354.5s

  [6675/13157] intraday_3517.csv.gz  in=291,481,887 out=74,555,739 elapsed=354.5s

  [6676/13157] intraday_3520.csv.gz  in=291,491,131 out=74,555,739 elapsed=354.6s

  [6677/13157] intraday_3521.csv.gz  in=291,503,568 out=74,555,739 elapsed=354.6s

  [6678/13157] intraday_3518.csv.gz  in=291,517,856 out=74,555,739 elapsed=354.6s

  [6679/13157] intraday_3519.csv.gz  in=291,531,206 out=74,555,739 elapsed=354.6s

  [6680/13157] intraday_3524.csv.gz  in=291,543,111 out=74,555,739 elapsed=354.7s

  [6681/13157] intraday_3522.csv.gz  in=291,555,286 out=74,555,739 elapsed=354.7s

  [6682/13157] intraday_3523.csv.gz  in=291,565,791 out=74,555,739 elapsed=354.7s

  [6683/13157] intraday_3525.csv.gz  in=291,577,125 out=74,555,739 elapsed=354.7s

  [6684/13157] intraday_3529.csv.gz  in=291,590,239 out=74,555,739 elapsed=354.8s

  [6685/13157] intraday_3528.csv.gz  in=291,601,961 out=74,555,739 elapsed=354.8s

  [6686/13157] intraday_3526.csv.gz  in=291,614,656 out=74,555,739 elapsed=354.8s

  [6687/13157] intraday_3527.csv.gz  in=291,627,017 out=74,555,739 elapsed=354.8s

  [6688/13157] intraday_3532.csv.gz  in=291,638,367 out=74,555,739 elapsed=354.9s

  [6689/13157] intraday_3530.csv.gz  in=291,651,292 out=74,555,739 elapsed=354.9s

  [6690/13157] intraday_3531.csv.gz  in=291,662,672 out=74,555,739 elapsed=354.9s

  [6691/13157] intraday_3533.csv.gz  in=291,675,656 out=74,555,739 elapsed=354.9s

  [6692/13157] intraday_3536.csv.gz  in=291,687,866 out=74,555,739 elapsed=354.9s

  [6693/13157] intraday_3534.csv.gz  in=291,700,269 out=74,555,739 elapsed=354.9s

  [6694/13157] intraday_3535.csv.gz  in=291,710,874 out=74,555,739 elapsed=354.9s

  [6695/13157] intraday_3537.csv.gz  in=291,723,206 out=74,555,739 elapsed=354.9s

  [6696/13157] intraday_3538.csv.gz  in=291,737,348 out=74,555,739 elapsed=355.0s

  [6697/13157] intraday_3539.csv.gz  in=291,751,624 out=74,555,739 elapsed=355.0s

  [6698/13157] intraday_3540.csv.gz  in=291,764,695 out=74,555,739 elapsed=355.0s

  [6699/13157] intraday_3541.csv.gz  in=291,776,269 out=74,555,739 elapsed=355.0s

  [6700/13157] intraday_3542.csv.gz  in=291,787,719 out=74,555,739 elapsed=355.1s

  [6701/13157] intraday_3545.csv.gz  in=291,800,043 out=74,555,739 elapsed=355.1s

  [6702/13157] intraday_3544.csv.gz  in=291,811,562 out=74,555,739 elapsed=355.1s

  [6703/13157] intraday_3543.csv.gz  in=291,824,151 out=74,555,739 elapsed=355.1s

  [6704/13157] intraday_3546.csv.gz  in=291,835,020 out=74,555,739 elapsed=355.1s

  [6705/13157] intraday_3547.csv.gz  in=291,845,707 out=74,555,739 elapsed=355.2s

  [6706/13157] intraday_3548.csv.gz  in=291,856,677 out=74,555,739 elapsed=355.2s

  [6707/13157] intraday_3549.csv.gz  in=291,866,995 out=74,555,739 elapsed=355.2s

  [6708/13157] intraday_3550.csv.gz  in=291,880,868 out=74,555,739 elapsed=355.2s

  [6709/13157] intraday_3552.csv.gz  in=291,894,438 out=74,555,739 elapsed=355.4s

  [6710/13157] intraday_3551.csv.gz  in=291,906,704 out=74,555,739 elapsed=355.4s

  [6711/13157] intraday_3554.csv.gz  in=291,918,041 out=74,555,739 elapsed=355.4s

  [6712/13157] intraday_3553.csv.gz  in=291,929,322 out=74,555,739 elapsed=355.4s

  [6713/13157] intraday_3555.csv.gz  in=291,941,976 out=74,555,739 elapsed=355.5s

  [6714/13157] intraday_3557.csv.gz  in=291,953,760 out=74,555,739 elapsed=355.5s

  [6715/13157] intraday_3556.csv.gz  in=291,963,952 out=74,555,739 elapsed=355.5s

  [6716/13157] intraday_3558.csv.gz  in=291,975,798 out=74,555,739 elapsed=355.5s

  [6717/13157] intraday_3559.csv.gz  in=291,986,179 out=74,555,739 elapsed=355.7s

  [6718/13157] intraday_3560.csv.gz  in=291,997,606 out=74,555,739 elapsed=355.7s

  [6719/13157] intraday_3561.csv.gz  in=292,008,502 out=74,555,739 elapsed=355.7s

  [6720/13157] intraday_3562.csv.gz  in=292,018,915 out=74,555,739 elapsed=355.7s

  [6721/13157] intraday_3563.csv.gz  in=292,031,757 out=74,555,739 elapsed=355.7s

  [6722/13157] intraday_3564.csv.gz  in=292,044,081 out=74,555,739 elapsed=355.8s

  [6723/13157] intraday_3565.csv.gz  in=292,054,517 out=74,555,739 elapsed=355.8s

  [6724/13157] intraday_3567.csv.gz  in=292,068,305 out=74,555,739 elapsed=355.9s

  [6725/13157] intraday_3566.csv.gz  in=292,077,814 out=74,555,739 elapsed=355.9s

  [6726/13157] intraday_3570.csv.gz  in=292,089,922 out=74,555,739 elapsed=355.9s

  [6727/13157] intraday_3569.csv.gz  in=292,101,104 out=74,555,739 elapsed=355.9s

  [6728/13157] intraday_3568.csv.gz  in=292,114,403 out=74,555,739 elapsed=355.9s

  [6729/13157] intraday_3571.csv.gz  in=292,125,815 out=74,555,739 elapsed=355.9s

  [6730/13157] intraday_3572.csv.gz  in=292,136,139 out=74,555,739 elapsed=355.9s

  [6731/13157] intraday_3573.csv.gz  in=292,149,501 out=74,555,739 elapsed=356.0s

  [6732/13157] intraday_3576.csv.gz  in=292,162,193 out=74,555,739 elapsed=356.0s

  [6733/13157] intraday_3574.csv.gz  in=292,175,028 out=74,555,739 elapsed=356.0s

  [6734/13157] intraday_3575.csv.gz  in=292,187,560 out=74,555,739 elapsed=356.0s

  [6735/13157] intraday_3577.csv.gz  in=292,198,079 out=74,555,739 elapsed=356.0s

  [6736/13157] intraday_3578.csv.gz  in=292,208,370 out=74,555,739 elapsed=356.2s

  [6737/13157] intraday_3580.csv.gz  in=292,219,227 out=74,555,739 elapsed=356.2s

  [6738/13157] intraday_3581.csv.gz  in=292,232,519 out=74,555,739 elapsed=356.2s

  [6739/13157] intraday_3582.csv.gz  in=292,242,775 out=74,555,739 elapsed=356.2s

  [6740/13157] intraday_3579.csv.gz  in=292,254,610 out=74,555,739 elapsed=356.2s

  [6741/13157] intraday_3584.csv.gz  in=292,265,300 out=74,555,739 elapsed=356.4s

  [6742/13157] intraday_3583.csv.gz  in=292,275,033 out=74,555,739 elapsed=356.4s

  [6743/13157] intraday_3585.csv.gz  in=292,287,758 out=74,555,739 elapsed=356.4s

  [6744/13157] intraday_3586.csv.gz  in=292,299,642 out=74,555,739 elapsed=356.4s

  [6745/13157] intraday_3589.csv.gz  in=292,311,150 out=74,555,739 elapsed=356.5s

  [6746/13157] intraday_3588.csv.gz  in=292,322,575 out=74,555,739 elapsed=356.5s

  [6747/13157] intraday_3590.csv.gz  in=292,333,791 out=74,555,739 elapsed=356.5s

  [6748/13157] intraday_3587.csv.gz  in=292,346,592 out=74,555,739 elapsed=356.5s

  [6749/13157] intraday_3593.csv.gz  in=292,357,451 out=74,555,739 elapsed=356.7s

  [6750/13157] intraday_3594.csv.gz  in=292,367,786 out=74,555,739 elapsed=356.7s

  [6751/13157] intraday_3592.csv.gz  in=292,380,185 out=74,555,739 elapsed=356.7s

  [6752/13157] intraday_3591.csv.gz  in=292,393,865 out=74,555,739 elapsed=356.7s

  [6753/13157] intraday_3595.csv.gz  in=292,405,867 out=74,555,739 elapsed=356.9s

  [6754/13157] intraday_3598.csv.gz  in=292,416,596 out=74,555,739 elapsed=356.9s

  [6755/13157] intraday_3597.csv.gz  in=292,431,706 out=74,555,739 elapsed=356.9s

  [6756/13157] intraday_3596.csv.gz  in=292,444,090 out=74,555,739 elapsed=356.9s

  [6757/13157] intraday_3599.csv.gz  in=292,461,398 out=74,555,739 elapsed=357.0s

  [6758/13157] intraday_3601.csv.gz  in=292,475,669 out=74,555,739 elapsed=357.1s

  [6759/13157] intraday_3600.csv.gz  in=292,488,829 out=74,555,739 elapsed=357.1s

  [6760/13157] intraday_3602.csv.gz  in=292,501,829 out=74,555,739 elapsed=357.1s

  [6761/13157] intraday_3603.csv.gz  in=292,513,211 out=74,555,739 elapsed=357.1s

  [6762/13157] intraday_3604.csv.gz  in=292,524,673 out=74,555,739 elapsed=357.1s

  [6763/13157] intraday_3605.csv.gz  in=292,536,920 out=74,555,739 elapsed=357.1s

  [6764/13157] intraday_3606.csv.gz  in=292,555,594 out=74,555,739 elapsed=357.1s

  [6765/13157] intraday_3607.csv.gz  in=292,566,816 out=74,555,739 elapsed=357.2s

  [6766/13157] intraday_3608.csv.gz  in=292,578,892 out=74,555,739 elapsed=357.2s

  [6767/13157] intraday_3610.csv.gz  in=292,590,020 out=74,555,739 elapsed=357.2s

  [6768/13157] intraday_3609.csv.gz  in=292,602,695 out=74,555,739 elapsed=357.2s

  [6769/13157] intraday_3613.csv.gz  in=292,615,928 out=74,555,739 elapsed=357.3s

  [6770/13157] intraday_3614.csv.gz  in=292,628,588 out=74,555,739 elapsed=357.3s

  [6771/13157] intraday_3612.csv.gz  in=292,640,720 out=74,555,739 elapsed=357.3s

  [6772/13157] intraday_3611.csv.gz  in=292,654,570 out=74,555,739 elapsed=357.3s

  [6773/13157] intraday_3615.csv.gz  in=292,667,171 out=74,555,739 elapsed=357.3s

  [6774/13157] intraday_3618.csv.gz  in=292,678,541 out=74,555,739 elapsed=357.3s

  [6775/13157] intraday_3616.csv.gz  in=292,692,665 out=74,555,739 elapsed=357.3s

  [6776/13157] intraday_3617.csv.gz  in=292,705,632 out=74,555,739 elapsed=357.3s

  [6777/13157] intraday_3621.csv.gz  in=292,718,265 out=74,555,739 elapsed=357.4s

  [6778/13157] intraday_3620.csv.gz  in=292,730,068 out=74,555,739 elapsed=357.4s

  [6779/13157] intraday_3619.csv.gz  in=292,743,574 out=74,555,739 elapsed=357.4s

  [6780/13157] intraday_3622.csv.gz  in=292,757,673 out=74,555,739 elapsed=357.4s

  [6781/13157] intraday_3625.csv.gz  in=292,771,572 out=74,555,739 elapsed=357.5s

  [6782/13157] intraday_3623.csv.gz  in=292,785,162 out=74,555,739 elapsed=357.5s

  [6783/13157] intraday_3626.csv.gz  in=292,797,696 out=74,555,739 elapsed=357.5s

  [6784/13157] intraday_3624.csv.gz  in=292,811,222 out=74,555,739 elapsed=357.5s

  [6785/13157] intraday_3630.csv.gz  in=292,820,837 out=74,555,739 elapsed=357.7s

  [6786/13157] intraday_3627.csv.gz  in=292,832,803 out=74,555,739 elapsed=357.7s

  [6787/13157] intraday_3628.csv.gz  in=292,843,650 out=74,555,739 elapsed=357.7s

  [6788/13157] intraday_3629.csv.gz  in=292,856,330 out=74,555,739 elapsed=357.7s

  [6789/13157] intraday_3631.csv.gz  in=292,869,214 out=74,555,739 elapsed=357.7s

  [6790/13157] intraday_3634.csv.gz  in=292,880,267 out=74,555,739 elapsed=357.8s

  [6791/13157] intraday_3632.csv.gz  in=292,893,113 out=74,555,739 elapsed=357.8s

  [6792/13157] intraday_3635.csv.gz  in=292,906,013 out=74,555,739 elapsed=357.8s

  [6793/13157] intraday_3633.csv.gz  in=292,924,523 out=74,555,739 elapsed=357.8s

  [6794/13157] intraday_3637.csv.gz  in=292,936,291 out=74,555,739 elapsed=357.8s

  [6795/13157] intraday_3639.csv.gz  in=292,954,161 out=74,555,739 elapsed=357.8s

  [6796/13157] intraday_3638.csv.gz  in=292,967,738 out=74,555,739 elapsed=357.8s

  [6797/13157] intraday_3636.csv.gz  in=292,980,478 out=74,555,739 elapsed=357.8s

  [6798/13157] intraday_3640.csv.gz  in=292,994,531 out=74,555,739 elapsed=357.9s

  [6799/13157] intraday_3642.csv.gz  in=293,007,194 out=74,555,739 elapsed=357.9s

  [6800/13157] intraday_3641.csv.gz  in=293,019,954 out=74,555,739 elapsed=357.9s

  [6801/13157] intraday_3643.csv.gz  in=293,031,170 out=74,555,739 elapsed=357.9s

  [6802/13157] intraday_3644.csv.gz  in=293,042,672 out=74,555,739 elapsed=357.9s

  [6803/13157] intraday_3645.csv.gz  in=293,053,721 out=74,555,739 elapsed=357.9s

  [6804/13157] intraday_3646.csv.gz  in=293,067,300 out=74,555,739 elapsed=357.9s

  [6805/13157] intraday_3647.csv.gz  in=293,076,167 out=74,555,739 elapsed=357.9s

  [6806/13157] intraday_3648.csv.gz  in=293,084,632 out=74,555,739 elapsed=358.0s

  [6807/13157] intraday_3649.csv.gz  in=293,094,706 out=74,555,739 elapsed=358.0s

  [6808/13157] intraday_3651.csv.gz  in=293,108,882 out=74,555,739 elapsed=358.0s

  [6809/13157] intraday_3650.csv.gz  in=293,124,080 out=74,555,739 elapsed=358.0s

  [6810/13157] intraday_3652.csv.gz  in=293,137,419 out=74,555,739 elapsed=358.1s

  [6811/13157] intraday_3653.csv.gz  in=293,147,820 out=74,555,739 elapsed=358.1s

  [6812/13157] intraday_3654.csv.gz  in=293,162,543 out=74,555,739 elapsed=358.1s

  [6813/13157] intraday_3655.csv.gz  in=293,176,972 out=74,555,739 elapsed=358.1s

  [6814/13157] intraday_3659.csv.gz  in=293,192,080 out=74,555,739 elapsed=358.3s

  [6815/13157] intraday_3657.csv.gz  in=293,204,663 out=74,555,739 elapsed=358.3s

  [6816/13157] intraday_3656.csv.gz  in=293,220,725 out=74,555,739 elapsed=358.3s

  [6817/13157] intraday_3658.csv.gz  in=293,234,783 out=74,555,739 elapsed=358.3s

  [6818/13157] intraday_3660.csv.gz  in=293,244,474 out=74,555,739 elapsed=358.5s

  [6819/13157] intraday_3663.csv.gz  in=293,255,208 out=74,555,739 elapsed=358.5s

  [6820/13157] intraday_3662.csv.gz  in=293,268,162 out=74,555,739 elapsed=358.5s

  [6821/13157] intraday_3661.csv.gz  in=293,280,732 out=74,555,739 elapsed=358.5s

  [6822/13157] intraday_3664.csv.gz  in=293,292,680 out=74,555,739 elapsed=358.6s

  [6823/13157] intraday_3665.csv.gz  in=293,304,288 out=74,555,739 elapsed=358.6s

  [6824/13157] intraday_3666.csv.gz  in=293,317,168 out=74,555,739 elapsed=358.6s

  [6825/13157] intraday_3667.csv.gz  in=293,330,153 out=74,555,739 elapsed=358.7s

  [6826/13157] intraday_3668.csv.gz  in=293,340,956 out=74,555,739 elapsed=358.7s

  [6827/13157] intraday_3670.csv.gz  in=293,355,005 out=74,555,739 elapsed=358.8s

  [6828/13157] intraday_3671.csv.gz  in=293,366,332 out=74,555,739 elapsed=358.8s

  [6829/13157] intraday_3669.csv.gz  in=293,379,593 out=74,555,739 elapsed=358.8s

  [6830/13157] intraday_3672.csv.gz  in=293,391,897 out=74,555,739 elapsed=358.8s

  [6831/13157] intraday_3675.csv.gz  in=293,402,878 out=74,555,739 elapsed=358.8s

  [6832/13157] intraday_3674.csv.gz  in=293,415,379 out=74,555,739 elapsed=358.8s

  [6833/13157] intraday_3676.csv.gz  in=293,427,991 out=74,555,739 elapsed=358.8s

  [6834/13157] intraday_3673.csv.gz  in=293,440,170 out=74,555,739 elapsed=358.8s

  [6835/13157] intraday_3680.csv.gz  in=293,456,608 out=74,555,739 elapsed=358.9s

  [6836/13157] intraday_3677.csv.gz  in=293,469,378 out=74,555,739 elapsed=358.9s

  [6837/13157] intraday_3678.csv.gz  in=293,483,707 out=74,555,739 elapsed=358.9s

  [6838/13157] intraday_3679.csv.gz  in=293,500,190 out=74,555,739 elapsed=358.9s

  [6839/13157] intraday_3682.csv.gz  in=293,511,750 out=74,555,739 elapsed=358.9s

  [6840/13157] intraday_3684.csv.gz  in=293,523,526 out=74,555,739 elapsed=359.0s

  [6841/13157] intraday_3683.csv.gz  in=293,536,143 out=74,555,739 elapsed=359.0s

  [6842/13157] intraday_3681.csv.gz  in=293,547,116 out=74,555,739 elapsed=359.0s

  [6843/13157] intraday_3687.csv.gz  in=293,556,822 out=74,555,739 elapsed=359.1s

  [6844/13157] intraday_3685.csv.gz  in=293,569,878 out=74,555,739 elapsed=359.1s

  [6845/13157] intraday_3686.csv.gz  in=293,584,516 out=74,555,739 elapsed=359.1s

  [6846/13157] intraday_3688.csv.gz  in=293,597,833 out=74,555,739 elapsed=359.1s

  [6847/13157] intraday_3689.csv.gz  in=293,608,259 out=74,555,739 elapsed=359.2s

  [6848/13157] intraday_3692.csv.gz  in=293,620,271 out=74,555,739 elapsed=359.2s

  [6849/13157] intraday_3691.csv.gz  in=293,632,612 out=74,555,739 elapsed=359.2s

  [6850/13157] intraday_3690.csv.gz  in=293,646,347 out=74,555,739 elapsed=359.2s

  [6851/13157] intraday_3694.csv.gz  in=293,657,590 out=74,555,739 elapsed=359.2s

  [6852/13157] intraday_3693.csv.gz  in=293,669,268 out=74,555,739 elapsed=359.2s

  [6853/13157] intraday_3696.csv.gz  in=293,680,087 out=74,555,739 elapsed=359.3s

  [6854/13157] intraday_3695.csv.gz  in=293,693,345 out=74,555,739 elapsed=359.3s

  [6855/13157] intraday_3698.csv.gz  in=293,705,455 out=74,555,739 elapsed=359.3s

  [6856/13157] intraday_3697.csv.gz  in=293,717,615 out=74,555,739 elapsed=359.3s

  [6857/13157] intraday_3699.csv.gz  in=293,728,879 out=74,555,739 elapsed=359.3s

  [6858/13157] intraday_3700.csv.gz  in=293,740,829 out=74,555,739 elapsed=359.3s

  [6859/13157] intraday_3702.csv.gz  in=293,750,738 out=74,555,739 elapsed=359.4s

  [6860/13157] intraday_3703.csv.gz  in=293,764,388 out=74,555,739 elapsed=359.4s

  [6861/13157] intraday_3701.csv.gz  in=293,778,967 out=74,555,739 elapsed=359.4s

  [6862/13157] intraday_3704.csv.gz  in=293,790,579 out=74,555,739 elapsed=359.4s

  [6863/13157] intraday_3706.csv.gz  in=293,801,457 out=74,555,739 elapsed=359.5s

  [6864/13157] intraday_3705.csv.gz  in=293,812,319 out=74,555,739 elapsed=359.5s

  [6865/13157] intraday_3708.csv.gz  in=293,825,619 out=74,555,739 elapsed=359.5s

  [6866/13157] intraday_3707.csv.gz  in=293,840,384 out=74,555,739 elapsed=359.5s

  [6867/13157] intraday_3712.csv.gz  in=293,850,530 out=74,555,739 elapsed=359.7s

  [6868/13157] intraday_3710.csv.gz  in=293,861,543 out=74,555,739 elapsed=359.7s

  [6869/13157] intraday_3709.csv.gz  in=293,873,338 out=74,555,739 elapsed=359.7s

  [6870/13157] intraday_3711.csv.gz  in=293,895,833 out=74,555,739 elapsed=359.7s

  [6871/13157] intraday_3714.csv.gz  in=293,909,171 out=74,555,739 elapsed=359.7s

  [6872/13157] intraday_3715.csv.gz  in=293,921,674 out=74,555,739 elapsed=359.7s

  [6873/13157] intraday_3716.csv.gz  in=293,933,846 out=74,555,739 elapsed=359.7s

  [6874/13157] intraday_3713.csv.gz  in=293,950,569 out=74,555,739 elapsed=359.7s

  [6875/13157] intraday_3718.csv.gz  in=293,960,465 out=74,555,739 elapsed=359.8s

  [6876/13157] intraday_3717.csv.gz  in=293,976,211 out=74,555,739 elapsed=359.8s

  [6877/13157] intraday_3719.csv.gz  in=293,988,256 out=74,555,739 elapsed=359.9s

  [6878/13157] intraday_3720.csv.gz  in=294,000,056 out=74,555,739 elapsed=359.9s

  [6879/13157] intraday_3721.csv.gz  in=294,013,348 out=74,555,739 elapsed=359.9s

  [6880/13157] intraday_3723.csv.gz  in=294,025,500 out=74,555,739 elapsed=359.9s

  [6881/13157] intraday_3722.csv.gz  in=294,035,931 out=74,555,739 elapsed=359.9s

  [6882/13157] intraday_3725.csv.gz  in=294,048,831 out=74,555,739 elapsed=359.9s

  [6883/13157] intraday_3724.csv.gz  in=294,060,799 out=74,555,739 elapsed=359.9s

  [6884/13157] intraday_3728.csv.gz  in=294,073,208 out=74,555,739 elapsed=360.0s

  [6885/13157] intraday_3727.csv.gz  in=294,086,831 out=74,555,739 elapsed=360.0s

  [6886/13157] intraday_3729.csv.gz  in=294,100,322 out=74,555,739 elapsed=360.0s

  [6887/13157] intraday_3726.csv.gz  in=294,112,776 out=74,555,739 elapsed=360.0s

  [6888/13157] intraday_3730.csv.gz  in=294,123,190 out=74,555,739 elapsed=360.0s

  [6889/13157] intraday_3732.csv.gz  in=294,135,688 out=74,555,739 elapsed=360.0s

  [6890/13157] intraday_3733.csv.gz  in=294,147,782 out=74,555,739 elapsed=360.0s

  [6891/13157] intraday_3731.csv.gz  in=294,164,287 out=74,555,739 elapsed=360.1s

  [6892/13157] intraday_3734.csv.gz  in=294,175,087 out=74,555,739 elapsed=360.1s

  [6893/13157] intraday_3735.csv.gz  in=294,187,021 out=74,555,739 elapsed=360.1s

  [6894/13157] intraday_3736.csv.gz  in=294,201,006 out=74,555,739 elapsed=360.1s

  [6895/13157] intraday_3737.csv.gz  in=294,215,767 out=74,555,739 elapsed=360.1s

  [6896/13157] intraday_3739.csv.gz  in=294,226,559 out=74,555,739 elapsed=360.2s

  [6897/13157] intraday_3740.csv.gz  in=294,242,367 out=74,555,739 elapsed=360.2s

  [6898/13157] intraday_3741.csv.gz  in=294,256,615 out=74,555,739 elapsed=360.2s

  [6899/13157] intraday_3738.csv.gz  in=294,270,676 out=74,555,739 elapsed=360.2s

  [6900/13157] intraday_3742.csv.gz  in=294,284,739 out=74,555,739 elapsed=360.3s

  [6901/13157] intraday_3745.csv.gz  in=294,296,527 out=74,555,739 elapsed=360.3s

  [6902/13157] intraday_3743.csv.gz  in=294,308,350 out=74,555,739 elapsed=360.3s

  [6903/13157] intraday_3744.csv.gz  in=294,321,101 out=74,555,739 elapsed=360.3s

  [6904/13157] intraday_3747.csv.gz  in=294,333,560 out=74,555,739 elapsed=360.5s

  [6905/13157] intraday_3746.csv.gz  in=294,346,783 out=74,555,739 elapsed=360.5s

  [6906/13157] intraday_3748.csv.gz  in=294,358,733 out=74,555,739 elapsed=360.5s

  [6907/13157] intraday_3749.csv.gz  in=294,373,999 out=74,555,739 elapsed=360.5s

  [6908/13157] intraday_3750.csv.gz  in=294,387,523 out=74,555,739 elapsed=360.7s

  [6909/13157] intraday_3752.csv.gz  in=294,400,427 out=74,555,739 elapsed=360.7s

  [6910/13157] intraday_3751.csv.gz  in=294,413,952 out=74,555,739 elapsed=360.7s

  [6911/13157] intraday_3753.csv.gz  in=294,429,752 out=74,555,739 elapsed=360.7s

  [6912/13157] intraday_3754.csv.gz  in=294,441,658 out=74,555,739 elapsed=360.9s

  [6913/13157] intraday_3757.csv.gz  in=294,455,818 out=74,555,739 elapsed=360.9s

  [6914/13157] intraday_3755.csv.gz  in=294,469,871 out=74,555,739 elapsed=360.9s

  [6915/13157] intraday_3756.csv.gz  in=294,484,698 out=74,555,739 elapsed=360.9s

  [6916/13157] intraday_3759.csv.gz  in=294,497,115 out=74,555,739 elapsed=361.0s

  [6917/13157] intraday_3758.csv.gz  in=294,509,647 out=74,555,739 elapsed=361.0s

  [6918/13157] intraday_3760.csv.gz  in=294,533,509 out=74,555,739 elapsed=361.0s

  [6919/13157] intraday_3761.csv.gz  in=294,546,024 out=74,555,739 elapsed=361.0s

  [6920/13157] intraday_3764.csv.gz  in=294,560,343 out=74,555,739 elapsed=361.2s

  [6921/13157] intraday_3763.csv.gz  in=294,577,538 out=74,555,739 elapsed=361.2s

  [6922/13157] intraday_3762.csv.gz  in=294,593,066 out=74,555,739 elapsed=361.2s

  [6923/13157] intraday_3765.csv.gz  in=294,608,464 out=74,555,739 elapsed=361.2s

  [6924/13157] intraday_3767.csv.gz  in=294,622,122 out=74,555,739 elapsed=361.3s

  [6925/13157] intraday_3768.csv.gz  in=294,634,254 out=74,555,739 elapsed=361.4s

  [6926/13157] intraday_3766.csv.gz  in=294,653,612 out=74,555,739 elapsed=361.4s

  [6927/13157] intraday_3769.csv.gz  in=294,671,261 out=74,555,739 elapsed=361.4s

  [6928/13157] intraday_3770.csv.gz  in=294,682,605 out=74,555,739 elapsed=361.4s

  [6929/13157] intraday_3771.csv.gz  in=294,695,154 out=74,555,739 elapsed=361.4s

  [6930/13157] intraday_3773.csv.gz  in=294,707,921 out=74,555,739 elapsed=361.4s

  [6931/13157] intraday_3772.csv.gz  in=294,720,996 out=74,555,739 elapsed=361.4s

  [6932/13157] intraday_3774.csv.gz  in=294,736,417 out=74,555,739 elapsed=361.4s

  [6933/13157] intraday_3775.csv.gz  in=294,748,562 out=74,555,739 elapsed=361.5s

  [6934/13157] intraday_3776.csv.gz  in=294,760,987 out=74,555,739 elapsed=361.5s

  [6935/13157] intraday_3778.csv.gz  in=294,773,281 out=74,555,739 elapsed=361.5s

  [6936/13157] intraday_3777.csv.gz  in=294,787,019 out=74,555,739 elapsed=361.5s

  [6937/13157] intraday_3781.csv.gz  in=294,800,904 out=74,555,739 elapsed=361.5s

  [6938/13157] intraday_3780.csv.gz  in=294,815,580 out=74,555,739 elapsed=361.6s

  [6939/13157] intraday_3779.csv.gz  in=294,828,288 out=74,555,739 elapsed=361.6s

  [6940/13157] intraday_3782.csv.gz  in=294,841,837 out=74,555,739 elapsed=361.6s

  [6941/13157] intraday_3783.csv.gz  in=294,854,498 out=74,555,739 elapsed=361.6s

  [6942/13157] intraday_3784.csv.gz  in=294,866,018 out=74,555,739 elapsed=361.6s

  [6943/13157] intraday_3785.csv.gz  in=294,877,763 out=74,555,739 elapsed=361.6s

  [6944/13157] intraday_3787.csv.gz  in=294,891,944 out=74,555,739 elapsed=361.6s

  [6945/13157] intraday_3786.csv.gz  in=294,903,170 out=74,555,739 elapsed=361.6s

  [6946/13157] intraday_3788.csv.gz  in=294,910,405 out=74,555,739 elapsed=361.7s

  [6947/13157] intraday_3790.csv.gz  in=294,918,784 out=74,555,739 elapsed=361.7s

  [6948/13157] intraday_3789.csv.gz  in=294,930,356 out=74,555,739 elapsed=361.7s

  [6949/13157] intraday_3791.csv.gz  in=294,945,844 out=74,555,739 elapsed=361.7s

  [6950/13157] intraday_3792.csv.gz  in=294,961,037 out=74,555,739 elapsed=361.7s

  [6951/13157] intraday_3793.csv.gz  in=294,973,830 out=74,555,739 elapsed=361.7s

  [6952/13157] intraday_3796.csv.gz  in=294,988,288 out=74,555,739 elapsed=361.7s

  [6953/13157] intraday_3794.csv.gz  in=294,998,451 out=74,555,739 elapsed=361.7s

  [6954/13157] intraday_3795.csv.gz  in=295,014,437 out=74,555,739 elapsed=361.7s

  [6955/13157] intraday_3797.csv.gz  in=295,026,864 out=74,555,739 elapsed=361.8s

  [6956/13157] intraday_3799.csv.gz  in=295,041,654 out=74,555,739 elapsed=361.8s

  [6957/13157] intraday_3798.csv.gz  in=295,053,578 out=74,555,739 elapsed=361.8s

  [6958/13157] intraday_3800.csv.gz  in=295,068,992 out=74,555,739 elapsed=361.8s

  [6959/13157] intraday_3801.csv.gz  in=295,078,838 out=74,555,739 elapsed=361.8s

  [6960/13157] intraday_3802.csv.gz  in=295,090,595 out=74,555,739 elapsed=361.9s

  [6961/13157] intraday_3804.csv.gz  in=295,101,002 out=74,555,739 elapsed=362.0s

  [6962/13157] intraday_3803.csv.gz  in=295,114,163 out=74,555,739 elapsed=362.0s

  [6963/13157] intraday_3805.csv.gz  in=295,125,555 out=74,555,739 elapsed=362.0s

  [6964/13157] intraday_3806.csv.gz  in=295,137,116 out=74,555,739 elapsed=362.1s

  [6965/13157] intraday_3809.csv.gz  in=295,147,673 out=74,555,739 elapsed=362.1s

  [6966/13157] intraday_3808.csv.gz  in=295,160,881 out=74,555,739 elapsed=362.1s

  [6967/13157] intraday_3807.csv.gz  in=295,173,950 out=74,555,739 elapsed=362.1s

  [6968/13157] intraday_3812.csv.gz  in=295,185,854 out=74,555,739 elapsed=362.1s

  [6969/13157] intraday_3810.csv.gz  in=295,198,820 out=74,555,739 elapsed=362.1s

  [6970/13157] intraday_3813.csv.gz  in=295,210,959 out=74,555,739 elapsed=362.1s

  [6971/13157] intraday_3811.csv.gz  in=295,225,412 out=74,555,739 elapsed=362.1s

  [6972/13157] intraday_3817.csv.gz  in=295,238,402 out=74,555,739 elapsed=362.2s

  [6973/13157] intraday_3816.csv.gz  in=295,247,965 out=74,555,739 elapsed=362.2s

  [6974/13157] intraday_3815.csv.gz  in=295,260,408 out=74,555,739 elapsed=362.2s

  [6975/13157] intraday_3814.csv.gz  in=295,272,528 out=74,555,739 elapsed=362.2s

  [6976/13157] intraday_3818.csv.gz  in=295,285,372 out=74,555,739 elapsed=362.2s

  [6977/13157] intraday_3820.csv.gz  in=295,300,235 out=74,555,739 elapsed=362.2s

  [6978/13157] intraday_3821.csv.gz  in=295,315,312 out=74,555,739 elapsed=362.2s

  [6979/13157] intraday_3819.csv.gz  in=295,334,956 out=74,555,739 elapsed=362.2s

  [6980/13157] intraday_3822.csv.gz  in=295,346,865 out=74,555,739 elapsed=362.3s

  [6981/13157] intraday_3825.csv.gz  in=295,358,486 out=74,555,739 elapsed=362.3s

  [6982/13157] intraday_3823.csv.gz  in=295,370,731 out=74,555,739 elapsed=362.3s

  [6983/13157] intraday_3826.csv.gz  in=295,384,297 out=74,555,739 elapsed=362.3s

  [6984/13157] intraday_3824.csv.gz  in=295,397,644 out=74,555,739 elapsed=362.3s

  [6985/13157] intraday_3828.csv.gz  in=295,408,242 out=74,555,739 elapsed=362.3s

  [6986/13157] intraday_3827.csv.gz  in=295,418,620 out=74,555,739 elapsed=362.3s

  [6987/13157] intraday_3830.csv.gz  in=295,428,637 out=74,555,739 elapsed=362.3s

  [6988/13157] intraday_3829.csv.gz  in=295,440,073 out=74,555,739 elapsed=362.3s

  [6989/13157] intraday_3834.csv.gz  in=295,451,928 out=74,555,739 elapsed=362.4s

  [6990/13157] intraday_3832.csv.gz  in=295,464,097 out=74,555,739 elapsed=362.4s

  [6991/13157] intraday_3831.csv.gz  in=295,478,768 out=74,555,739 elapsed=362.4s

  [6992/13157] intraday_3833.csv.gz  in=295,500,789 out=74,555,739 elapsed=362.4s

  [6993/13157] intraday_3835.csv.gz  in=295,511,946 out=74,555,739 elapsed=362.4s

  [6994/13157] intraday_3837.csv.gz  in=295,523,142 out=74,555,739 elapsed=362.4s

  [6995/13157] intraday_3836.csv.gz  in=295,536,271 out=74,555,739 elapsed=362.4s

  [6996/13157] intraday_3841.csv.gz  in=295,547,357 out=74,555,739 elapsed=362.5s

  [6997/13157] intraday_3838.csv.gz  in=295,559,635 out=74,555,739 elapsed=362.5s

  [6998/13157] intraday_3840.csv.gz  in=295,570,740 out=74,555,739 elapsed=362.5s

  [6999/13157] intraday_3839.csv.gz  in=295,586,090 out=74,555,739 elapsed=362.5s

  [7000/13157] intraday_3843.csv.gz  in=295,596,905 out=74,555,739 elapsed=362.5s

  [7001/13157] intraday_3842.csv.gz  in=295,608,735 out=74,555,739 elapsed=362.5s

  [7002/13157] intraday_3845.csv.gz  in=295,621,687 out=74,555,739 elapsed=362.5s

  [7003/13157] intraday_3844.csv.gz  in=295,633,755 out=74,555,739 elapsed=362.5s

  [7004/13157] intraday_3846.csv.gz  in=295,645,136 out=74,555,739 elapsed=362.6s

  [7005/13157] intraday_3847.csv.gz  in=295,655,682 out=74,555,739 elapsed=362.6s

  [7006/13157] intraday_3848.csv.gz  in=295,669,567 out=74,555,739 elapsed=362.6s

  [7007/13157] intraday_3849.csv.gz  in=295,683,267 out=74,555,739 elapsed=362.6s

  [7008/13157] intraday_3851.csv.gz  in=295,694,343 out=74,555,739 elapsed=362.6s

  [7009/13157] intraday_3850.csv.gz  in=295,711,809 out=74,555,739 elapsed=362.7s

  [7010/13157] intraday_3853.csv.gz  in=295,723,384 out=74,555,739 elapsed=362.7s

  [7011/13157] intraday_3852.csv.gz  in=295,736,153 out=74,555,739 elapsed=362.7s

  [7012/13157] intraday_3856.csv.gz  in=295,747,458 out=74,555,739 elapsed=362.7s

  [7013/13157] intraday_3855.csv.gz  in=295,763,123 out=74,555,739 elapsed=362.7s

  [7014/13157] intraday_3857.csv.gz  in=295,776,392 out=74,555,739 elapsed=362.7s

  [7015/13157] intraday_3854.csv.gz  in=295,791,072 out=74,555,739 elapsed=362.7s

  [7016/13157] intraday_3858.csv.gz  in=295,804,180 out=74,555,739 elapsed=362.8s

  [7017/13157] intraday_3860.csv.gz  in=295,815,469 out=74,555,739 elapsed=362.8s

  [7018/13157] intraday_3861.csv.gz  in=295,826,967 out=74,555,739 elapsed=362.8s

  [7019/13157] intraday_3859.csv.gz  in=295,837,304 out=74,555,739 elapsed=362.8s

  [7020/13157] intraday_3862.csv.gz  in=295,850,851 out=74,555,739 elapsed=362.8s

  [7021/13157] intraday_3864.csv.gz  in=295,863,312 out=74,555,739 elapsed=362.8s

  [7022/13157] intraday_3865.csv.gz  in=295,874,728 out=74,555,739 elapsed=362.9s

  [7023/13157] intraday_3863.csv.gz  in=295,884,776 out=74,555,739 elapsed=362.9s

  [7024/13157] intraday_3866.csv.gz  in=295,897,647 out=74,555,739 elapsed=362.9s

  [7025/13157] intraday_3867.csv.gz  in=295,910,908 out=74,555,739 elapsed=362.9s

  [7026/13157] intraday_3869.csv.gz  in=295,922,617 out=74,555,739 elapsed=362.9s

  [7027/13157] intraday_3868.csv.gz  in=295,935,742 out=74,555,739 elapsed=362.9s

  [7028/13157] intraday_3870.csv.gz  in=295,946,815 out=74,555,739 elapsed=363.0s

  [7029/13157] intraday_3871.csv.gz  in=295,957,326 out=74,555,739 elapsed=363.0s

  [7030/13157] intraday_3873.csv.gz  in=295,977,106 out=74,555,739 elapsed=363.0s

  [7031/13157] intraday_3872.csv.gz  in=295,994,473 out=74,555,739 elapsed=363.0s

  [7032/13157] intraday_3874.csv.gz  in=296,006,912 out=74,555,739 elapsed=363.0s

  [7033/13157] intraday_3876.csv.gz  in=296,019,744 out=74,555,739 elapsed=363.1s

  [7034/13157] intraday_3875.csv.gz  in=296,030,188 out=74,555,739 elapsed=363.2s

  [7035/13157] intraday_3877.csv.gz  in=296,043,921 out=74,555,739 elapsed=363.2s

  [7036/13157] intraday_3878.csv.gz  in=296,058,527 out=74,555,739 elapsed=363.2s

  [7037/13157] intraday_3880.csv.gz  in=296,069,543 out=74,555,739 elapsed=363.3s

  [7038/13157] intraday_3879.csv.gz  in=296,083,245 out=74,555,739 elapsed=363.3s

  [7039/13157] intraday_3882.csv.gz  in=296,098,100 out=74,555,739 elapsed=363.3s

  [7040/13157] intraday_3881.csv.gz  in=296,119,871 out=74,555,739 elapsed=363.3s

  [7041/13157] intraday_3884.csv.gz  in=296,131,905 out=74,555,739 elapsed=363.4s

  [7042/13157] intraday_3885.csv.gz  in=296,144,058 out=74,555,739 elapsed=363.4s

  [7043/13157] intraday_3886.csv.gz  in=296,155,780 out=74,555,739 elapsed=363.4s

  [7044/13157] intraday_3883.csv.gz  in=296,171,966 out=74,555,739 elapsed=363.4s

  [7045/13157] intraday_3887.csv.gz  in=296,185,418 out=74,555,739 elapsed=363.4s

  [7046/13157] intraday_3888.csv.gz  in=296,197,597 out=74,555,739 elapsed=363.4s

  [7047/13157] intraday_3891.csv.gz  in=296,211,793 out=74,555,739 elapsed=363.4s

  [7048/13157] intraday_3889.csv.gz  in=296,224,295 out=74,555,739 elapsed=363.4s

  [7049/13157] intraday_3890.csv.gz  in=296,237,039 out=74,555,739 elapsed=363.5s

  [7050/13157] intraday_3895.csv.gz  in=296,248,514 out=74,555,739 elapsed=363.5s

  [7051/13157] intraday_3892.csv.gz  in=296,263,055 out=74,555,739 elapsed=363.5s

  [7052/13157] intraday_3894.csv.gz  in=296,279,673 out=74,555,739 elapsed=363.5s

  [7053/13157] intraday_3893.csv.gz  in=296,293,192 out=74,555,739 elapsed=363.5s

  [7054/13157] intraday_3896.csv.gz  in=296,305,357 out=74,555,739 elapsed=363.6s

  [7055/13157] intraday_3897.csv.gz  in=296,320,612 out=74,555,739 elapsed=363.6s

  [7056/13157] intraday_3899.csv.gz  in=296,331,596 out=74,555,739 elapsed=363.6s

  [7057/13157] intraday_3898.csv.gz  in=296,346,296 out=74,555,739 elapsed=363.6s

  [7058/13157] intraday_3900.csv.gz  in=296,360,581 out=74,555,739 elapsed=363.6s

  [7059/13157] intraday_3901.csv.gz  in=296,373,119 out=74,555,739 elapsed=363.6s

  [7060/13157] intraday_3903.csv.gz  in=296,388,080 out=74,555,739 elapsed=363.6s

  [7061/13157] intraday_3902.csv.gz  in=296,401,003 out=74,555,739 elapsed=363.6s

  [7062/13157] intraday_3907.csv.gz  in=296,412,407 out=74,555,739 elapsed=363.7s

  [7063/13157] intraday_3906.csv.gz  in=296,427,862 out=74,555,739 elapsed=363.7s

  [7064/13157] intraday_3904.csv.gz  in=296,441,962 out=74,555,739 elapsed=363.7s

  [7065/13157] intraday_3905.csv.gz  in=296,459,007 out=74,555,739 elapsed=363.7s

  [7066/13157] intraday_3911.csv.gz  in=296,470,157 out=74,555,739 elapsed=363.8s

  [7067/13157] intraday_3909.csv.gz  in=296,482,669 out=74,555,739 elapsed=363.8s

  [7068/13157] intraday_3908.csv.gz  in=296,496,054 out=74,555,739 elapsed=363.8s

  [7069/13157] intraday_3910.csv.gz  in=296,507,876 out=74,555,739 elapsed=363.8s

  [7070/13157] intraday_3912.csv.gz  in=296,519,691 out=74,555,739 elapsed=363.8s

  [7071/13157] intraday_3913.csv.gz  in=296,533,451 out=74,555,739 elapsed=363.8s

  [7072/13157] intraday_3914.csv.gz  in=296,546,116 out=74,555,739 elapsed=363.8s

  [7073/13157] intraday_3915.csv.gz  in=296,562,813 out=74,555,739 elapsed=363.8s

  [7074/13157] intraday_3919.csv.gz  in=296,574,671 out=74,555,739 elapsed=363.9s

  [7075/13157] intraday_3916.csv.gz  in=296,586,448 out=74,555,739 elapsed=363.9s

  [7076/13157] intraday_3918.csv.gz  in=296,599,742 out=74,555,739 elapsed=363.9s

  [7077/13157] intraday_3917.csv.gz  in=296,612,124 out=74,555,739 elapsed=363.9s

  [7078/13157] intraday_3920.csv.gz  in=296,624,537 out=74,555,739 elapsed=363.9s

  [7079/13157] intraday_3921.csv.gz  in=296,639,286 out=74,555,739 elapsed=363.9s

  [7080/13157] intraday_3925.csv.gz  in=296,651,050 out=74,555,739 elapsed=364.0s

  [7081/13157] intraday_3924.csv.gz  in=296,664,269 out=74,555,739 elapsed=364.0s

  [7082/13157] intraday_3922.csv.gz  in=296,677,759 out=74,555,739 elapsed=364.0s

  [7083/13157] intraday_3923.csv.gz  in=296,691,430 out=74,555,739 elapsed=364.0s

  [7084/13157] intraday_3926.csv.gz  in=296,704,714 out=74,555,739 elapsed=364.0s

  [7085/13157] intraday_3927.csv.gz  in=296,715,292 out=74,555,739 elapsed=364.0s

  [7086/13157] intraday_3929.csv.gz  in=296,723,761 out=74,555,739 elapsed=364.0s

  [7087/13157] intraday_3928.csv.gz  in=296,737,709 out=74,555,739 elapsed=364.0s

  [7088/13157] intraday_3930.csv.gz  in=296,747,189 out=74,555,739 elapsed=364.0s

  [7089/13157] intraday_3931.csv.gz  in=296,758,133 out=74,555,739 elapsed=364.0s

  [7090/13157] intraday_3933.csv.gz  in=296,772,792 out=74,555,739 elapsed=364.0s

  [7091/13157] intraday_3932.csv.gz  in=296,789,111 out=74,555,739 elapsed=364.0s

  [7092/13157] intraday_3934.csv.gz  in=296,802,082 out=74,555,739 elapsed=364.1s

  [7093/13157] intraday_3935.csv.gz  in=296,812,754 out=74,555,739 elapsed=364.1s

  [7094/13157] intraday_3936.csv.gz  in=296,827,944 out=74,555,739 elapsed=364.1s

  [7095/13157] intraday_3937.csv.gz  in=296,842,767 out=74,555,739 elapsed=364.1s

  [7096/13157] intraday_3938.csv.gz  in=296,855,572 out=74,555,739 elapsed=364.1s

  [7097/13157] intraday_3939.csv.gz  in=296,868,519 out=74,555,739 elapsed=364.1s

  [7098/13157] intraday_3942.csv.gz  in=296,878,502 out=74,555,739 elapsed=364.1s

  [7099/13157] intraday_3940.csv.gz  in=296,893,403 out=74,555,739 elapsed=364.1s

  [7100/13157] intraday_3941.csv.gz  in=296,909,412 out=74,555,739 elapsed=364.2s

  [7101/13157] intraday_3943.csv.gz  in=296,923,019 out=74,555,739 elapsed=364.2s

  [7102/13157] intraday_3944.csv.gz  in=296,936,342 out=74,555,739 elapsed=364.3s

  [7103/13157] intraday_3945.csv.gz  in=296,948,361 out=74,555,739 elapsed=364.3s

  [7104/13157] intraday_3946.csv.gz  in=296,959,508 out=74,555,739 elapsed=364.3s

  [7105/13157] intraday_3947.csv.gz  in=296,972,717 out=74,555,739 elapsed=364.3s

  [7106/13157] intraday_3948.csv.gz  in=296,984,974 out=74,555,739 elapsed=364.6s

  [7107/13157] intraday_3950.csv.gz  in=296,997,158 out=74,555,739 elapsed=364.6s

  [7108/13157] intraday_3951.csv.gz  in=297,011,494 out=74,555,739 elapsed=364.6s

  [7109/13157] intraday_3949.csv.gz  in=297,024,916 out=74,555,739 elapsed=364.6s

  [7110/13157] intraday_3952.csv.gz  in=297,038,831 out=74,555,739 elapsed=364.8s

  [7111/13157] intraday_3954.csv.gz  in=297,051,423 out=74,555,739 elapsed=364.8s

  [7112/13157] intraday_3955.csv.gz  in=297,064,515 out=74,555,739 elapsed=364.8s

  [7113/13157] intraday_3956.csv.gz  in=297,076,818 out=74,555,739 elapsed=364.8s

  [7114/13157] intraday_3953.csv.gz  in=297,090,070 out=74,555,739 elapsed=364.8s

  [7115/13157] intraday_3957.csv.gz  in=297,100,687 out=74,555,739 elapsed=364.9s

  [7116/13157] intraday_3958.csv.gz  in=297,113,610 out=74,555,739 elapsed=364.9s

  [7117/13157] intraday_3959.csv.gz  in=297,127,480 out=74,555,739 elapsed=364.9s

  [7118/13157] intraday_3961.csv.gz  in=297,143,195 out=74,555,739 elapsed=364.9s

  [7119/13157] intraday_3960.csv.gz  in=297,157,783 out=74,555,739 elapsed=364.9s

  [7120/13157] intraday_3963.csv.gz  in=297,169,909 out=74,555,739 elapsed=364.9s

  [7121/13157] intraday_3962.csv.gz  in=297,183,499 out=74,555,739 elapsed=364.9s

  [7122/13157] intraday_3964.csv.gz  in=297,196,749 out=74,555,739 elapsed=365.0s

  [7123/13157] intraday_3965.csv.gz  in=297,211,450 out=74,555,739 elapsed=365.0s

  [7124/13157] intraday_3966.csv.gz  in=297,223,178 out=74,555,739 elapsed=365.0s

  [7125/13157] intraday_3969.csv.gz  in=297,234,378 out=74,555,739 elapsed=365.0s

  [7126/13157] intraday_3968.csv.gz  in=297,246,073 out=74,555,739 elapsed=365.0s

  [7127/13157] intraday_3967.csv.gz  in=297,259,412 out=74,555,739 elapsed=365.0s

  [7128/13157] intraday_3971.csv.gz  in=297,272,598 out=74,555,739 elapsed=365.0s

  [7129/13157] intraday_3970.csv.gz  in=297,284,441 out=74,555,739 elapsed=365.0s

  [7130/13157] intraday_3972.csv.gz  in=297,297,413 out=74,555,739 elapsed=365.0s

  [7131/13157] intraday_3973.csv.gz  in=297,310,394 out=74,555,739 elapsed=365.1s

  [7132/13157] intraday_3975.csv.gz  in=297,322,400 out=74,555,739 elapsed=365.1s

  [7133/13157] intraday_3976.csv.gz  in=297,335,478 out=74,555,739 elapsed=365.1s

  [7134/13157] intraday_3974.csv.gz  in=297,349,269 out=74,555,739 elapsed=365.1s

  [7135/13157] intraday_3977.csv.gz  in=297,361,852 out=74,555,739 elapsed=365.1s

  [7136/13157] intraday_3978.csv.gz  in=297,373,529 out=74,555,739 elapsed=365.1s

  [7137/13157] intraday_3980.csv.gz  in=297,385,424 out=74,555,739 elapsed=365.1s

  [7138/13157] intraday_3979.csv.gz  in=297,398,245 out=74,555,739 elapsed=365.1s

  [7139/13157] intraday_3981.csv.gz  in=297,408,900 out=74,555,739 elapsed=365.1s

  [7140/13157] intraday_3983.csv.gz  in=297,419,579 out=74,555,739 elapsed=365.2s

  [7141/13157] intraday_3982.csv.gz  in=297,433,266 out=74,555,739 elapsed=365.2s

  [7142/13157] intraday_3984.csv.gz  in=297,444,305 out=74,555,739 elapsed=365.2s

  [7143/13157] intraday_3985.csv.gz  in=297,458,422 out=74,555,739 elapsed=365.2s

  [7144/13157] intraday_3988.csv.gz  in=297,469,435 out=74,555,739 elapsed=365.2s

  [7145/13157] intraday_3986.csv.gz  in=297,481,723 out=74,555,739 elapsed=365.2s

  [7146/13157] intraday_3987.csv.gz  in=297,493,994 out=74,555,739 elapsed=365.2s

  [7147/13157] intraday_3989.csv.gz  in=297,509,163 out=74,555,739 elapsed=365.2s

  [7148/13157] intraday_3990.csv.gz  in=297,521,689 out=74,555,739 elapsed=365.3s

  [7149/13157] intraday_3993.csv.gz  in=297,534,669 out=74,555,739 elapsed=365.3s

  [7150/13157] intraday_3991.csv.gz  in=297,547,147 out=74,555,739 elapsed=365.3s

  [7151/13157] intraday_3992.csv.gz  in=297,560,113 out=74,555,739 elapsed=365.3s

  [7152/13157] intraday_3994.csv.gz  in=297,572,097 out=74,555,739 elapsed=365.4s

  [7153/13157] intraday_3996.csv.gz  in=297,586,393 out=74,555,739 elapsed=365.4s

  [7154/13157] intraday_3995.csv.gz  in=297,601,327 out=74,555,739 elapsed=365.4s

  [7155/13157] intraday_3997.csv.gz  in=297,614,739 out=74,555,739 elapsed=365.4s

  [7156/13157] intraday_3998.csv.gz  in=297,628,211 out=74,555,739 elapsed=365.4s

  [7157/13157] intraday_3999.csv.gz  in=297,638,948 out=74,555,739 elapsed=365.5s

  [7158/13157] intraday_4002.csv.gz  in=297,651,754 out=74,555,739 elapsed=365.5s

  [7159/13157] intraday_4001.csv.gz  in=297,663,192 out=74,555,739 elapsed=365.5s

  [7160/13157] intraday_4000.csv.gz  in=297,675,908 out=74,555,739 elapsed=365.5s

  [7161/13157] intraday_4003.csv.gz  in=297,690,148 out=74,555,739 elapsed=365.5s

  [7162/13157] intraday_4005.csv.gz  in=297,700,009 out=74,555,739 elapsed=365.5s

  [7163/13157] intraday_4004.csv.gz  in=297,712,257 out=74,555,739 elapsed=365.5s

  [7164/13157] intraday_4008.csv.gz  in=297,724,293 out=74,555,739 elapsed=365.5s

  [7165/13157] intraday_4006.csv.gz  in=297,736,700 out=74,555,739 elapsed=365.5s

  [7166/13157] intraday_4007.csv.gz  in=297,752,368 out=74,555,739 elapsed=365.5s

  [7167/13157] intraday_4010.csv.gz  in=297,763,719 out=74,555,739 elapsed=365.7s

  [7168/13157] intraday_4009.csv.gz  in=297,776,169 out=74,555,739 elapsed=365.7s

  [7169/13157] intraday_4012.csv.gz  in=297,790,184 out=74,555,739 elapsed=365.7s

  [7170/13157] intraday_4011.csv.gz  in=297,802,179 out=74,555,739 elapsed=365.7s

  [7171/13157] intraday_4014.csv.gz  in=297,814,250 out=74,555,739 elapsed=366.0s

  [7172/13157] intraday_4013.csv.gz  in=297,830,243 out=74,555,739 elapsed=366.0s

  [7173/13157] intraday_4015.csv.gz  in=297,842,148 out=74,555,739 elapsed=366.0s

  [7174/13157] intraday_4016.csv.gz  in=297,853,870 out=74,555,739 elapsed=366.0s

  [7175/13157] intraday_4019.csv.gz  in=297,868,756 out=74,555,739 elapsed=366.2s

  [7176/13157] intraday_4020.csv.gz  in=297,879,746 out=74,555,739 elapsed=366.2s

  [7177/13157] intraday_4017.csv.gz  in=297,893,843 out=74,555,739 elapsed=366.2s

  [7178/13157] intraday_4018.csv.gz  in=297,908,535 out=74,555,739 elapsed=366.2s

  [7179/13157] intraday_4021.csv.gz  in=297,923,079 out=74,555,739 elapsed=366.3s

  [7180/13157] intraday_4023.csv.gz  in=297,936,905 out=74,555,739 elapsed=366.4s

  [7181/13157] intraday_4024.csv.gz  in=297,951,903 out=74,555,739 elapsed=366.4s

  [7182/13157] intraday_4025.csv.gz  in=297,964,030 out=74,555,739 elapsed=366.4s

  [7183/13157] intraday_4022.csv.gz  in=297,980,353 out=74,555,739 elapsed=366.4s

  [7184/13157] intraday_4026.csv.gz  in=297,992,690 out=74,555,739 elapsed=366.5s

  [7185/13157] intraday_4027.csv.gz  in=298,005,941 out=74,555,739 elapsed=366.5s

  [7186/13157] intraday_4029.csv.gz  in=298,018,124 out=74,555,739 elapsed=366.5s

  [7187/13157] intraday_4028.csv.gz  in=298,030,089 out=74,555,739 elapsed=366.5s

  [7188/13157] intraday_4032.csv.gz  in=298,044,064 out=74,555,739 elapsed=366.7s

  [7189/13157] intraday_4030.csv.gz  in=298,055,671 out=74,555,739 elapsed=366.7s

  [7190/13157] intraday_4031.csv.gz  in=298,069,626 out=74,555,739 elapsed=366.7s

  [7191/13157] intraday_4033.csv.gz  in=298,082,972 out=74,555,739 elapsed=366.7s

  [7192/13157] intraday_4034.csv.gz  in=298,095,910 out=74,555,739 elapsed=366.9s

  [7193/13157] intraday_4036.csv.gz  in=298,109,363 out=74,555,739 elapsed=366.9s

  [7194/13157] intraday_4037.csv.gz  in=298,122,615 out=74,555,739 elapsed=366.9s

  [7195/13157] intraday_4035.csv.gz  in=298,136,522 out=74,555,739 elapsed=366.9s

  [7196/13157] intraday_4040.csv.gz  in=298,148,455 out=74,555,739 elapsed=367.0s

  [7197/13157] intraday_4039.csv.gz  in=298,162,651 out=74,555,739 elapsed=367.0s

  [7198/13157] intraday_4041.csv.gz  in=298,176,996 out=74,555,739 elapsed=367.0s

  [7199/13157] intraday_4038.csv.gz  in=298,191,603 out=74,555,739 elapsed=367.0s

  [7200/13157] intraday_4042.csv.gz  in=298,203,950 out=74,555,739 elapsed=367.2s

  [7201/13157] intraday_4043.csv.gz  in=298,217,878 out=74,555,739 elapsed=367.2s

  [7202/13157] intraday_4045.csv.gz  in=298,232,839 out=74,555,739 elapsed=367.3s

  [7203/13157] intraday_4044.csv.gz  in=298,249,045 out=74,555,739 elapsed=367.3s

  [7204/13157] intraday_4046.csv.gz  in=298,262,468 out=74,555,739 elapsed=367.3s

  [7205/13157] intraday_4048.csv.gz  in=298,274,726 out=74,555,739 elapsed=367.3s

  [7206/13157] intraday_4047.csv.gz  in=298,290,775 out=74,555,739 elapsed=367.3s

  [7207/13157] intraday_4049.csv.gz  in=298,303,745 out=74,555,739 elapsed=367.3s

  [7208/13157] intraday_4050.csv.gz  in=298,314,832 out=74,555,739 elapsed=367.3s

  [7209/13157] intraday_4051.csv.gz  in=298,329,065 out=74,555,739 elapsed=367.4s

  [7210/13157] intraday_4052.csv.gz  in=298,339,592 out=74,555,739 elapsed=367.4s

  [7211/13157] intraday_4053.csv.gz  in=298,353,149 out=74,555,739 elapsed=367.4s

  [7212/13157] intraday_4054.csv.gz  in=298,366,691 out=74,555,739 elapsed=367.4s

  [7213/13157] intraday_4056.csv.gz  in=298,378,225 out=74,555,739 elapsed=367.4s

  [7214/13157] intraday_4057.csv.gz  in=298,391,660 out=74,555,739 elapsed=367.4s

  [7215/13157] intraday_4058.csv.gz  in=298,405,052 out=74,555,739 elapsed=367.4s

  [7216/13157] intraday_4055.csv.gz  in=298,421,729 out=74,555,739 elapsed=367.4s

  [7217/13157] intraday_4059.csv.gz  in=298,434,194 out=74,555,739 elapsed=367.5s

  [7218/13157] intraday_4060.csv.gz  in=298,448,543 out=74,555,739 elapsed=367.5s

  [7219/13157] intraday_4061.csv.gz  in=298,463,408 out=74,555,739 elapsed=367.5s

  [7220/13157] intraday_4062.csv.gz  in=298,478,230 out=74,555,739 elapsed=367.5s

  [7221/13157] intraday_4063.csv.gz  in=298,491,322 out=74,555,739 elapsed=367.5s

  [7222/13157] intraday_4065.csv.gz  in=298,502,844 out=74,555,739 elapsed=367.6s

  [7223/13157] intraday_4064.csv.gz  in=298,516,459 out=74,555,739 elapsed=367.6s

  [7224/13157] intraday_4066.csv.gz  in=298,528,850 out=74,555,739 elapsed=367.6s

  [7225/13157] intraday_4067.csv.gz  in=298,541,612 out=74,555,739 elapsed=367.6s

  [7226/13157] intraday_4068.csv.gz  in=298,556,306 out=74,555,739 elapsed=367.6s

  [7227/13157] intraday_4070.csv.gz  in=298,565,066 out=74,555,739 elapsed=367.6s

  [7228/13157] intraday_4071.csv.gz  in=298,576,935 out=74,555,739 elapsed=367.6s

  [7229/13157] intraday_4069.csv.gz  in=298,586,607 out=74,555,739 elapsed=367.6s

  [7230/13157] intraday_4074.csv.gz  in=298,586,645 out=74,555,739 elapsed=367.6s

  [7231/13157] intraday_4072.csv.gz  in=298,586,718 out=74,555,739 elapsed=367.6s

  [7232/13157] intraday_4075.csv.gz  in=298,586,846 out=74,555,739 elapsed=367.7s

  [7233/13157] intraday_4076.csv.gz  in=298,586,877 out=74,555,739 elapsed=367.7s

  [7234/13157] intraday_4073.csv.gz  in=298,587,922 out=74,555,739 elapsed=367.7s

  [7235/13157] intraday_4077.csv.gz  in=298,588,531 out=74,555,739 elapsed=367.7s

  [7236/13157] intraday_4080.csv.gz  in=298,588,560 out=74,555,739 elapsed=367.7s

  [7237/13157] intraday_4079.csv.gz  in=298,588,639 out=74,555,739 elapsed=367.7s

  [7238/13157] intraday_4078.csv.gz  in=298,588,791 out=74,555,739 elapsed=367.7s

  [7239/13157] intraday_4082.csv.gz  in=298,588,803 out=74,555,739 elapsed=367.7s

  [7240/13157] intraday_4081.csv.gz  in=298,589,831 out=74,555,739 elapsed=367.7s

  [7241/13157] intraday_4083.csv.gz  in=298,589,839 out=74,555,739 elapsed=367.7s

  [7242/13157] intraday_4086.csv.gz  in=298,589,872 out=74,555,739 elapsed=367.7s

  [7243/13157] intraday_4087.csv.gz  in=298,590,433 out=74,555,739 elapsed=367.8s

  [7244/13157] intraday_4084.csv.gz  in=298,591,158 out=74,555,739 elapsed=367.8s

  [7245/13157] intraday_4085.csv.gz  in=298,591,261 out=74,555,739 elapsed=367.8s

  [7246/13157] intraday_4088.csv.gz  in=298,595,589 out=74,555,739 elapsed=367.8s

  [7247/13157] intraday_4090.csv.gz  in=298,595,736 out=74,555,739 elapsed=367.8s

  [7248/13157] intraday_4089.csv.gz  in=298,604,616 out=74,555,739 elapsed=367.8s

  [7249/13157] intraday_4092.csv.gz  in=298,604,693 out=74,555,739 elapsed=367.8s

  [7250/13157] intraday_4091.csv.gz  in=298,605,222 out=74,555,739 elapsed=367.8s

  [7251/13157] intraday_4093.csv.gz  in=298,605,286 out=74,555,739 elapsed=367.9s

  [7252/13157] intraday_4095.csv.gz  in=298,605,399 out=74,555,739 elapsed=367.9s

  [7253/13157] intraday_4096.csv.gz  in=298,605,472 out=74,555,739 elapsed=367.9s

  [7254/13157] intraday_4094.csv.gz  in=298,606,670 out=74,555,739 elapsed=367.9s

  [7255/13157] intraday_4097.csv.gz  in=298,613,116 out=74,555,739 elapsed=367.9s

  [7256/13157] intraday_4098.csv.gz  in=298,613,135 out=74,555,739 elapsed=367.9s

  [7257/13157] intraday_4099.csv.gz  in=298,614,086 out=74,555,739 elapsed=367.9s

  [7258/13157] intraday_4102.csv.gz  in=298,614,882 out=74,555,739 elapsed=368.1s

  [7259/13157] intraday_4100.csv.gz  in=298,621,316 out=74,555,739 elapsed=368.1s

  [7260/13157] intraday_4101.csv.gz  in=298,621,472 out=74,555,739 elapsed=368.1s

  [7261/13157] intraday_4104.csv.gz  in=298,621,504 out=74,555,739 elapsed=368.1s

  [7262/13157] intraday_4103.csv.gz  in=298,623,989 out=74,555,739 elapsed=368.1s

  [7263/13157] intraday_4105.csv.gz  in=298,624,103 out=74,555,739 elapsed=368.1s

  [7264/13157] intraday_4106.csv.gz  in=298,624,142 out=74,555,739 elapsed=368.1s

  [7265/13157] intraday_4108.csv.gz  in=298,624,555 out=74,555,739 elapsed=368.1s

  [7266/13157] intraday_4109.csv.gz  in=298,624,691 out=74,555,739 elapsed=368.1s

  [7267/13157] intraday_4107.csv.gz  in=298,632,461 out=74,555,739 elapsed=368.1s

  [7268/13157] intraday_4110.csv.gz  in=298,632,597 out=74,555,739 elapsed=368.1s

  [7269/13157] intraday_4111.csv.gz  in=298,632,692 out=74,555,739 elapsed=368.1s

  [7270/13157] intraday_4113.csv.gz  in=298,632,831 out=74,555,739 elapsed=368.1s

  [7271/13157] intraday_4114.csv.gz  in=298,632,899 out=74,555,739 elapsed=368.1s

  [7272/13157] intraday_4112.csv.gz  in=298,633,162 out=74,555,739 elapsed=368.1s

  [7273/13157] intraday_4115.csv.gz  in=298,648,732 out=74,555,739 elapsed=368.1s

  [7274/13157] intraday_4118.csv.gz  in=298,659,000 out=74,555,739 elapsed=368.2s

  [7275/13157] intraday_4117.csv.gz  in=298,671,973 out=74,555,739 elapsed=368.3s

  [7276/13157] intraday_4116.csv.gz  in=298,686,864 out=74,555,739 elapsed=368.3s

  [7277/13157] intraday_4119.csv.gz  in=298,701,472 out=74,555,739 elapsed=368.3s

  [7278/13157] intraday_4121.csv.gz  in=298,713,645 out=74,555,739 elapsed=368.3s

  [7279/13157] intraday_4120.csv.gz  in=298,728,095 out=74,555,739 elapsed=368.3s

  [7280/13157] intraday_4122.csv.gz  in=298,739,983 out=74,555,739 elapsed=368.3s

  [7281/13157] intraday_4123.csv.gz  in=298,754,276 out=74,555,739 elapsed=368.3s

  [7282/13157] intraday_4125.csv.gz  in=298,764,947 out=74,555,739 elapsed=368.3s

  [7283/13157] intraday_4127.csv.gz  in=298,776,488 out=74,555,739 elapsed=368.4s

  [7284/13157] intraday_4128.csv.gz  in=298,788,030 out=74,555,739 elapsed=368.4s

  [7285/13157] intraday_4126.csv.gz  in=298,802,047 out=74,555,739 elapsed=368.4s

  [7286/13157] intraday_4124.csv.gz  in=298,817,555 out=74,555,739 elapsed=368.4s

  [7287/13157] intraday_4129.csv.gz  in=298,828,544 out=74,555,739 elapsed=368.5s

  [7288/13157] intraday_4130.csv.gz  in=298,839,911 out=74,555,739 elapsed=368.5s

  [7289/13157] intraday_4132.csv.gz  in=298,853,879 out=74,555,739 elapsed=368.5s

  [7290/13157] intraday_4131.csv.gz  in=298,867,655 out=74,555,739 elapsed=368.5s

  [7291/13157] intraday_4133.csv.gz  in=298,878,362 out=74,555,739 elapsed=368.6s

  [7292/13157] intraday_4134.csv.gz  in=298,891,085 out=74,555,739 elapsed=368.6s

  [7293/13157] intraday_4136.csv.gz  in=298,903,502 out=74,555,739 elapsed=368.6s

  [7294/13157] intraday_4135.csv.gz  in=298,917,663 out=74,555,739 elapsed=368.7s

  [7295/13157] intraday_4137.csv.gz  in=298,929,299 out=74,555,739 elapsed=368.8s

  [7296/13157] intraday_4140.csv.gz  in=298,939,103 out=74,555,739 elapsed=368.8s

  [7297/13157] intraday_4139.csv.gz  in=298,950,653 out=74,555,739 elapsed=368.8s

  [7298/13157] intraday_4138.csv.gz  in=298,962,996 out=74,555,739 elapsed=368.8s

  [7299/13157] intraday_4141.csv.gz  in=298,976,090 out=74,555,739 elapsed=368.9s

  [7300/13157] intraday_4142.csv.gz  in=298,988,738 out=74,555,739 elapsed=368.9s

  [7301/13157] intraday_4143.csv.gz  in=299,000,998 out=74,555,739 elapsed=368.9s

  [7302/13157] intraday_4145.csv.gz  in=299,015,610 out=74,555,739 elapsed=368.9s

  [7303/13157] intraday_4144.csv.gz  in=299,031,100 out=74,555,739 elapsed=368.9s

  [7304/13157] intraday_4146.csv.gz  in=299,043,187 out=74,555,739 elapsed=369.0s

  [7305/13157] intraday_4147.csv.gz  in=299,055,134 out=74,555,739 elapsed=369.1s

  [7306/13157] intraday_4149.csv.gz  in=299,067,092 out=74,555,739 elapsed=369.1s

  [7307/13157] intraday_4148.csv.gz  in=299,080,259 out=74,555,739 elapsed=369.1s

  [7308/13157] intraday_4151.csv.gz  in=299,090,431 out=74,555,739 elapsed=369.1s

  [7309/13157] intraday_4150.csv.gz  in=299,103,417 out=74,555,739 elapsed=369.1s

  [7310/13157] intraday_4152.csv.gz  in=299,114,481 out=74,555,739 elapsed=369.1s

  [7311/13157] intraday_4153.csv.gz  in=299,126,765 out=74,555,739 elapsed=369.1s

  [7312/13157] intraday_4154.csv.gz  in=299,136,499 out=74,555,739 elapsed=369.2s

  [7313/13157] intraday_4156.csv.gz  in=299,149,372 out=74,555,739 elapsed=369.2s

  [7314/13157] intraday_4155.csv.gz  in=299,163,869 out=74,555,739 elapsed=369.2s

  [7315/13157] intraday_4157.csv.gz  in=299,175,976 out=74,555,739 elapsed=369.2s

  [7316/13157] intraday_4158.csv.gz  in=299,187,211 out=74,555,739 elapsed=369.3s

  [7317/13157] intraday_4159.csv.gz  in=299,198,804 out=74,555,739 elapsed=369.3s

  [7318/13157] intraday_4161.csv.gz  in=299,209,649 out=74,555,739 elapsed=369.3s

  [7319/13157] intraday_4160.csv.gz  in=299,222,527 out=74,555,739 elapsed=369.3s

  [7320/13157] intraday_4162.csv.gz  in=299,234,489 out=74,555,739 elapsed=369.3s

  [7321/13157] intraday_4163.csv.gz  in=299,245,862 out=74,555,739 elapsed=369.4s

  [7322/13157] intraday_4165.csv.gz  in=299,257,097 out=74,555,739 elapsed=369.4s

  [7323/13157] intraday_4164.csv.gz  in=299,267,823 out=74,555,739 elapsed=369.4s

  [7324/13157] intraday_4166.csv.gz  in=299,279,192 out=74,555,739 elapsed=369.4s

  [7325/13157] intraday_4167.csv.gz  in=299,290,463 out=74,555,739 elapsed=369.4s

  [7326/13157] intraday_4170.csv.gz  in=299,301,035 out=74,555,739 elapsed=369.4s

  [7327/13157] intraday_4168.csv.gz  in=299,314,371 out=74,555,739 elapsed=369.4s

  [7328/13157] intraday_4169.csv.gz  in=299,326,679 out=74,555,739 elapsed=369.4s

  [7329/13157] intraday_4172.csv.gz  in=299,340,140 out=74,555,739 elapsed=369.5s

  [7330/13157] intraday_4171.csv.gz  in=299,350,657 out=74,555,739 elapsed=369.5s

  [7331/13157] intraday_4174.csv.gz  in=299,361,971 out=74,555,739 elapsed=369.5s

  [7332/13157] intraday_4173.csv.gz  in=299,374,179 out=74,555,739 elapsed=369.5s

  [7333/13157] intraday_4177.csv.gz  in=299,385,927 out=74,555,739 elapsed=369.6s

  [7334/13157] intraday_4176.csv.gz  in=299,397,341 out=74,555,739 elapsed=369.6s

  [7335/13157] intraday_4175.csv.gz  in=299,408,760 out=74,555,739 elapsed=369.6s

  [7336/13157] intraday_4178.csv.gz  in=299,424,147 out=74,555,739 elapsed=369.6s

  [7337/13157] intraday_4180.csv.gz  in=299,436,113 out=74,555,739 elapsed=369.7s

  [7338/13157] intraday_4182.csv.gz  in=299,448,420 out=74,555,739 elapsed=369.7s

  [7339/13157] intraday_4179.csv.gz  in=299,461,480 out=74,555,739 elapsed=369.7s

  [7340/13157] intraday_4181.csv.gz  in=299,472,986 out=74,555,739 elapsed=369.7s

  [7341/13157] intraday_4183.csv.gz  in=299,482,984 out=74,555,739 elapsed=369.8s

  [7342/13157] intraday_4185.csv.gz  in=299,494,458 out=74,555,739 elapsed=369.8s

  [7343/13157] intraday_4184.csv.gz  in=299,506,548 out=74,555,739 elapsed=369.9s

  [7344/13157] intraday_4186.csv.gz  in=299,520,104 out=74,555,739 elapsed=369.9s

  [7345/13157] intraday_4187.csv.gz  in=299,529,888 out=74,555,739 elapsed=369.9s

  [7346/13157] intraday_4189.csv.gz  in=299,540,095 out=74,555,739 elapsed=369.9s

  [7347/13157] intraday_4188.csv.gz  in=299,550,928 out=74,555,739 elapsed=369.9s

  [7348/13157] intraday_4190.csv.gz  in=299,565,217 out=74,555,739 elapsed=369.9s

  [7349/13157] intraday_4191.csv.gz  in=299,577,023 out=74,555,739 elapsed=369.9s

  [7350/13157] intraday_4192.csv.gz  in=299,590,239 out=74,555,739 elapsed=370.0s

  [7351/13157] intraday_4194.csv.gz  in=299,601,001 out=74,555,739 elapsed=370.0s

  [7352/13157] intraday_4193.csv.gz  in=299,611,323 out=74,555,739 elapsed=370.0s

  [7353/13157] intraday_4195.csv.gz  in=299,623,195 out=74,555,739 elapsed=370.0s

  [7354/13157] intraday_4198.csv.gz  in=299,634,566 out=74,555,739 elapsed=370.1s

  [7355/13157] intraday_4197.csv.gz  in=299,646,087 out=74,555,739 elapsed=370.1s

  [7356/13157] intraday_4196.csv.gz  in=299,662,494 out=74,555,739 elapsed=370.1s

  [7357/13157] intraday_4199.csv.gz  in=299,674,120 out=74,555,739 elapsed=370.1s

  [7358/13157] intraday_4200.csv.gz  in=299,684,799 out=74,555,739 elapsed=370.2s

  [7359/13157] intraday_4201.csv.gz  in=299,698,150 out=74,555,739 elapsed=370.2s

  [7360/13157] intraday_4203.csv.gz  in=299,709,990 out=74,555,739 elapsed=370.2s

  [7361/13157] intraday_4202.csv.gz  in=299,725,037 out=74,555,739 elapsed=370.2s

  [7362/13157] intraday_4206.csv.gz  in=299,738,456 out=74,555,739 elapsed=370.2s

  [7363/13157] intraday_4204.csv.gz  in=299,751,833 out=74,555,739 elapsed=370.2s

  [7364/13157] intraday_4205.csv.gz  in=299,764,997 out=74,555,739 elapsed=370.2s

  [7365/13157] intraday_4209.csv.gz  in=299,776,830 out=74,555,739 elapsed=370.3s

  [7366/13157] intraday_4208.csv.gz  in=299,789,882 out=74,555,739 elapsed=370.3s

  [7367/13157] intraday_4210.csv.gz  in=299,800,823 out=74,555,739 elapsed=370.3s

  [7368/13157] intraday_4207.csv.gz  in=299,823,286 out=74,555,739 elapsed=370.3s

  [7369/13157] intraday_4211.csv.gz  in=299,835,213 out=74,555,739 elapsed=370.3s

  [7370/13157] intraday_4212.csv.gz  in=299,846,981 out=74,555,739 elapsed=370.3s

  [7371/13157] intraday_4213.csv.gz  in=299,858,935 out=74,555,739 elapsed=370.3s

  [7372/13157] intraday_4214.csv.gz  in=299,870,567 out=74,555,739 elapsed=370.3s

  [7373/13157] intraday_4216.csv.gz  in=299,882,548 out=74,555,739 elapsed=370.3s

  [7374/13157] intraday_4215.csv.gz  in=299,895,834 out=74,555,739 elapsed=370.3s

  [7375/13157] intraday_4219.csv.gz  in=299,906,913 out=74,555,739 elapsed=370.5s

  [7376/13157] intraday_4217.csv.gz  in=299,919,399 out=74,555,739 elapsed=370.5s

  [7377/13157] intraday_4220.csv.gz  in=299,930,257 out=74,555,739 elapsed=370.5s

  [7378/13157] intraday_4218.csv.gz  in=299,945,659 out=74,555,739 elapsed=370.5s

  [7379/13157] intraday_4223.csv.gz  in=299,957,380 out=74,555,739 elapsed=370.5s

  [7380/13157] intraday_4221.csv.gz  in=299,971,855 out=74,555,739 elapsed=370.5s

  [7381/13157] intraday_4222.csv.gz  in=299,986,573 out=74,555,739 elapsed=370.6s

  [7382/13157] intraday_4224.csv.gz  in=299,999,557 out=74,555,739 elapsed=370.6s

  [7383/13157] intraday_4225.csv.gz  in=300,012,945 out=74,555,739 elapsed=370.6s

  [7384/13157] intraday_4226.csv.gz  in=300,024,913 out=74,555,739 elapsed=370.6s

  [7385/13157] intraday_4227.csv.gz  in=300,040,426 out=74,555,739 elapsed=370.6s

  [7386/13157] intraday_4228.csv.gz  in=300,053,817 out=74,555,739 elapsed=370.6s

  [7387/13157] intraday_4229.csv.gz  in=300,067,213 out=74,555,739 elapsed=370.6s

  [7388/13157] intraday_4231.csv.gz  in=300,079,894 out=74,555,739 elapsed=370.6s

  [7389/13157] intraday_4232.csv.gz  in=300,092,038 out=74,555,739 elapsed=370.6s

  [7390/13157] intraday_4230.csv.gz  in=300,108,421 out=74,555,739 elapsed=370.6s

  [7391/13157] intraday_4233.csv.gz  in=300,119,412 out=74,555,739 elapsed=370.7s

  [7392/13157] intraday_4234.csv.gz  in=300,130,784 out=74,555,739 elapsed=370.7s

  [7393/13157] intraday_4236.csv.gz  in=300,143,800 out=74,555,739 elapsed=370.7s

  [7394/13157] intraday_4235.csv.gz  in=300,155,322 out=74,555,739 elapsed=370.7s

  [7395/13157] intraday_4237.csv.gz  in=300,167,612 out=74,555,739 elapsed=370.8s

  [7396/13157] intraday_4238.csv.gz  in=300,183,161 out=74,555,739 elapsed=370.8s

  [7397/13157] intraday_4239.csv.gz  in=300,195,958 out=74,555,739 elapsed=370.8s

  [7398/13157] intraday_4240.csv.gz  in=300,209,400 out=74,555,739 elapsed=370.8s

  [7399/13157] intraday_4242.csv.gz  in=300,222,876 out=74,555,739 elapsed=370.9s

  [7400/13157] intraday_4243.csv.gz  in=300,234,778 out=74,555,739 elapsed=370.9s

  [7401/13157] intraday_4241.csv.gz  in=300,247,268 out=74,555,739 elapsed=370.9s

  [7402/13157] intraday_4244.csv.gz  in=300,259,868 out=74,555,739 elapsed=370.9s

  [7403/13157] intraday_4248.csv.gz  in=300,271,769 out=74,555,739 elapsed=371.0s

  [7404/13157] intraday_4245.csv.gz  in=300,286,143 out=74,555,739 elapsed=371.0s

  [7405/13157] intraday_4246.csv.gz  in=300,300,257 out=74,555,739 elapsed=371.0s

  [7406/13157] intraday_4247.csv.gz  in=300,313,386 out=74,555,739 elapsed=371.1s

  [7407/13157] intraday_4249.csv.gz  in=300,323,692 out=74,555,739 elapsed=371.1s

  [7408/13157] intraday_4251.csv.gz  in=300,335,099 out=74,555,739 elapsed=371.1s

  [7409/13157] intraday_4252.csv.gz  in=300,347,566 out=74,555,739 elapsed=371.1s

  [7410/13157] intraday_4250.csv.gz  in=300,360,488 out=74,555,739 elapsed=371.1s

  [7411/13157] intraday_4253.csv.gz  in=300,368,075 out=74,555,739 elapsed=371.1s

  [7412/13157] intraday_4255.csv.gz  in=300,375,334 out=74,555,739 elapsed=371.2s

  [7413/13157] intraday_4254.csv.gz  in=300,385,639 out=74,555,739 elapsed=371.2s

  [7414/13157] intraday_4257.csv.gz  in=300,399,658 out=74,555,739 elapsed=371.2s

  [7415/13157] intraday_4256.csv.gz  in=300,415,441 out=74,555,739 elapsed=371.2s

  [7416/13157] intraday_4258.csv.gz  in=300,427,904 out=74,555,739 elapsed=371.2s

  [7417/13157] intraday_4261.csv.gz  in=300,442,303 out=74,555,739 elapsed=371.2s

  [7418/13157] intraday_4260.csv.gz  in=300,457,229 out=74,555,739 elapsed=371.3s

  [7419/13157] intraday_4259.csv.gz  in=300,467,377 out=74,555,739 elapsed=371.3s

  [7420/13157] intraday_4262.csv.gz  in=300,479,897 out=74,555,739 elapsed=371.3s

  [7421/13157] intraday_4265.csv.gz  in=300,495,587 out=74,555,739 elapsed=371.3s

  [7422/13157] intraday_4263.csv.gz  in=300,507,797 out=74,555,739 elapsed=371.3s

  [7423/13157] intraday_4264.csv.gz  in=300,522,282 out=74,555,739 elapsed=371.3s

  [7424/13157] intraday_4266.csv.gz  in=300,533,470 out=74,555,739 elapsed=371.3s

  [7425/13157] intraday_4269.csv.gz  in=300,545,482 out=74,555,739 elapsed=371.4s

  [7426/13157] intraday_4267.csv.gz  in=300,558,559 out=74,555,739 elapsed=371.4s

  [7427/13157] intraday_4268.csv.gz  in=300,570,920 out=74,555,739 elapsed=371.4s

  [7428/13157] intraday_4270.csv.gz  in=300,582,182 out=74,555,739 elapsed=371.4s

  [7429/13157] intraday_4271.csv.gz  in=300,593,678 out=74,555,739 elapsed=371.4s

  [7430/13157] intraday_4272.csv.gz  in=300,608,067 out=74,555,739 elapsed=371.4s

  [7431/13157] intraday_4273.csv.gz  in=300,621,252 out=74,555,739 elapsed=371.4s

  [7432/13157] intraday_4276.csv.gz  in=300,635,366 out=74,555,739 elapsed=371.5s

  [7433/13157] intraday_4274.csv.gz  in=300,645,702 out=74,555,739 elapsed=371.5s

  [7434/13157] intraday_4275.csv.gz  in=300,658,455 out=74,555,739 elapsed=371.5s

  [7435/13157] intraday_4277.csv.gz  in=300,671,372 out=74,555,739 elapsed=371.6s

  [7436/13157] intraday_4279.csv.gz  in=300,684,055 out=74,555,739 elapsed=371.6s

  [7437/13157] intraday_4280.csv.gz  in=300,696,431 out=74,555,739 elapsed=371.6s

  [7438/13157] intraday_4278.csv.gz  in=300,708,590 out=74,555,739 elapsed=371.6s

  [7439/13157] intraday_4281.csv.gz  in=300,719,771 out=74,555,739 elapsed=371.6s

  [7440/13157] intraday_4283.csv.gz  in=300,732,861 out=74,555,739 elapsed=371.6s

  [7441/13157] intraday_4282.csv.gz  in=300,746,371 out=74,555,739 elapsed=371.6s

  [7442/13157] intraday_4285.csv.gz  in=300,760,761 out=74,555,739 elapsed=371.6s

  [7443/13157] intraday_4284.csv.gz  in=300,774,739 out=74,555,739 elapsed=371.6s

  [7444/13157] intraday_4288.csv.gz  in=300,786,986 out=74,555,739 elapsed=371.7s

  [7445/13157] intraday_4286.csv.gz  in=300,800,870 out=74,555,739 elapsed=371.7s

  [7446/13157] intraday_4287.csv.gz  in=300,811,957 out=74,555,739 elapsed=371.7s

  [7447/13157] intraday_4289.csv.gz  in=300,825,173 out=74,555,739 elapsed=371.7s

  [7448/13157] intraday_4290.csv.gz  in=300,837,035 out=74,555,739 elapsed=371.7s

  [7449/13157] intraday_4291.csv.gz  in=300,849,161 out=74,555,739 elapsed=371.7s

  [7450/13157] intraday_4292.csv.gz  in=300,860,791 out=74,555,739 elapsed=371.7s

  [7451/13157] intraday_4293.csv.gz  in=300,874,049 out=74,555,739 elapsed=371.7s

  [7452/13157] intraday_4294.csv.gz  in=300,885,660 out=74,555,739 elapsed=371.8s

  [7453/13157] intraday_4297.csv.gz  in=300,896,828 out=74,555,739 elapsed=371.8s

  [7454/13157] intraday_4295.csv.gz  in=300,908,343 out=74,555,739 elapsed=371.8s

  [7455/13157] intraday_4296.csv.gz  in=300,921,940 out=74,555,739 elapsed=371.8s

  [7456/13157] intraday_4298.csv.gz  in=300,935,488 out=74,555,739 elapsed=371.9s

  [7457/13157] intraday_4301.csv.gz  in=300,948,095 out=74,555,739 elapsed=371.9s

  [7458/13157] intraday_4300.csv.gz  in=300,960,797 out=74,555,739 elapsed=371.9s

  [7459/13157] intraday_4299.csv.gz  in=300,972,106 out=74,555,739 elapsed=371.9s

  [7460/13157] intraday_4302.csv.gz  in=300,983,308 out=74,555,739 elapsed=371.9s

  [7461/13157] intraday_4305.csv.gz  in=300,992,836 out=74,555,739 elapsed=371.9s

  [7462/13157] intraday_4303.csv.gz  in=301,005,333 out=74,555,739 elapsed=371.9s

  [7463/13157] intraday_4304.csv.gz  in=301,016,603 out=74,555,739 elapsed=371.9s

  [7464/13157] intraday_4306.csv.gz  in=301,030,288 out=74,555,739 elapsed=371.9s

  [7465/13157] intraday_4308.csv.gz  in=301,041,604 out=74,555,739 elapsed=372.0s

  [7466/13157] intraday_4309.csv.gz  in=301,054,613 out=74,555,739 elapsed=372.0s

  [7467/13157] intraday_4307.csv.gz  in=301,065,857 out=74,555,739 elapsed=372.0s

  [7468/13157] intraday_4311.csv.gz  in=301,076,771 out=74,555,739 elapsed=372.0s

  [7469/13157] intraday_4310.csv.gz  in=301,089,209 out=74,555,739 elapsed=372.0s

  [7470/13157] intraday_4312.csv.gz  in=301,099,918 out=74,555,739 elapsed=372.0s

  [7471/13157] intraday_4313.csv.gz  in=301,114,226 out=74,555,739 elapsed=372.0s

  [7472/13157] intraday_4314.csv.gz  in=301,126,574 out=74,555,739 elapsed=372.1s

  [7473/13157] intraday_4315.csv.gz  in=301,138,840 out=74,555,739 elapsed=372.1s

  [7474/13157] intraday_4317.csv.gz  in=301,150,732 out=74,555,739 elapsed=372.1s

  [7475/13157] intraday_4316.csv.gz  in=301,161,668 out=74,555,739 elapsed=372.1s

  [7476/13157] intraday_4318.csv.gz  in=301,172,866 out=74,555,739 elapsed=372.1s

  [7477/13157] intraday_4321.csv.gz  in=301,186,046 out=74,555,739 elapsed=372.2s

  [7478/13157] intraday_4319.csv.gz  in=301,200,546 out=74,555,739 elapsed=372.2s

  [7479/13157] intraday_4320.csv.gz  in=301,213,159 out=74,555,739 elapsed=372.2s

  [7480/13157] intraday_4322.csv.gz  in=301,225,579 out=74,555,739 elapsed=372.2s

  [7481/13157] intraday_4324.csv.gz  in=301,236,714 out=74,555,739 elapsed=372.2s

  [7482/13157] intraday_4325.csv.gz  in=301,248,233 out=74,555,739 elapsed=372.2s

  [7483/13157] intraday_4326.csv.gz  in=301,259,067 out=74,555,739 elapsed=372.2s

  [7484/13157] intraday_4323.csv.gz  in=301,275,745 out=74,555,739 elapsed=372.2s

  [7485/13157] intraday_4327.csv.gz  in=301,289,417 out=74,555,739 elapsed=372.2s

  [7486/13157] intraday_4328.csv.gz  in=301,300,311 out=74,555,739 elapsed=372.3s

  [7487/13157] intraday_4329.csv.gz  in=301,310,801 out=74,555,739 elapsed=372.3s

  [7488/13157] intraday_4330.csv.gz  in=301,323,100 out=74,555,739 elapsed=372.3s

  [7489/13157] intraday_4331.csv.gz  in=301,337,064 out=74,555,739 elapsed=372.3s

  [7490/13157] intraday_4332.csv.gz  in=301,348,125 out=74,555,739 elapsed=372.3s

  [7491/13157] intraday_4335.csv.gz  in=301,360,263 out=74,555,739 elapsed=372.3s

  [7492/13157] intraday_4333.csv.gz  in=301,372,176 out=74,555,739 elapsed=372.3s

  [7493/13157] intraday_4334.csv.gz  in=301,382,647 out=74,555,739 elapsed=372.3s

  [7494/13157] intraday_4339.csv.gz  in=301,393,534 out=74,555,739 elapsed=372.5s

  [7495/13157] intraday_4336.csv.gz  in=301,406,591 out=74,555,739 elapsed=372.5s

  [7496/13157] intraday_4337.csv.gz  in=301,421,698 out=74,555,739 elapsed=372.5s

  [7497/13157] intraday_4338.csv.gz  in=301,433,006 out=74,555,739 elapsed=372.5s

  [7498/13157] intraday_4340.csv.gz  in=301,443,748 out=74,555,739 elapsed=372.5s

  [7499/13157] intraday_4341.csv.gz  in=301,456,886 out=74,555,739 elapsed=372.5s

  [7500/13157] intraday_4342.csv.gz  in=301,469,926 out=74,555,739 elapsed=372.5s

  [7501/13157] intraday_4343.csv.gz  in=301,484,982 out=74,555,739 elapsed=372.5s

  [7502/13157] intraday_4344.csv.gz  in=301,495,951 out=74,555,739 elapsed=372.6s

  [7503/13157] intraday_4345.csv.gz  in=301,510,049 out=74,555,739 elapsed=372.6s

  [7504/13157] intraday_4347.csv.gz  in=301,524,630 out=74,555,739 elapsed=372.6s

  [7505/13157] intraday_4346.csv.gz  in=301,538,307 out=74,555,739 elapsed=372.6s

  [7506/13157] intraday_4348.csv.gz  in=301,553,451 out=74,555,739 elapsed=372.6s

  [7507/13157] intraday_4351.csv.gz  in=301,566,010 out=74,555,739 elapsed=372.7s

  [7508/13157] intraday_4350.csv.gz  in=301,577,532 out=74,555,739 elapsed=372.7s

  [7509/13157] intraday_4352.csv.gz  in=301,588,346 out=74,555,739 elapsed=372.7s

  [7510/13157] intraday_4349.csv.gz  in=301,601,081 out=74,555,739 elapsed=372.7s

  [7511/13157] intraday_4353.csv.gz  in=301,612,122 out=74,555,739 elapsed=372.7s

  [7512/13157] intraday_4354.csv.gz  in=301,623,861 out=74,555,739 elapsed=372.7s

  [7513/13157] intraday_4356.csv.gz  in=301,636,652 out=74,555,739 elapsed=372.7s

  [7514/13157] intraday_4355.csv.gz  in=301,649,713 out=74,555,739 elapsed=372.7s

  [7515/13157] intraday_4357.csv.gz  in=301,661,786 out=74,555,739 elapsed=372.8s

  [7516/13157] intraday_4359.csv.gz  in=301,675,130 out=74,555,739 elapsed=372.8s

  [7517/13157] intraday_4360.csv.gz  in=301,687,795 out=74,555,739 elapsed=372.8s

  [7518/13157] intraday_4358.csv.gz  in=301,700,483 out=74,555,739 elapsed=372.8s

  [7519/13157] intraday_4361.csv.gz  in=301,713,389 out=74,555,739 elapsed=372.8s

  [7520/13157] intraday_4364.csv.gz  in=301,724,959 out=74,555,739 elapsed=373.0s

  [7521/13157] intraday_4362.csv.gz  in=301,737,832 out=74,555,739 elapsed=373.0s

  [7522/13157] intraday_4363.csv.gz  in=301,751,790 out=74,555,739 elapsed=373.0s

  [7523/13157] intraday_4365.csv.gz  in=301,767,029 out=74,555,739 elapsed=373.0s

  [7524/13157] intraday_4369.csv.gz  in=301,781,287 out=74,555,739 elapsed=373.1s

  [7525/13157] intraday_4366.csv.gz  in=301,793,723 out=74,555,739 elapsed=373.1s

  [7526/13157] intraday_4368.csv.gz  in=301,807,350 out=74,555,739 elapsed=373.1s

  [7527/13157] intraday_4367.csv.gz  in=301,820,895 out=74,555,739 elapsed=373.2s

  [7528/13157] intraday_4370.csv.gz  in=301,834,891 out=74,555,739 elapsed=373.2s

  [7529/13157] intraday_4373.csv.gz  in=301,846,687 out=74,555,739 elapsed=373.2s

  [7530/13157] intraday_4371.csv.gz  in=301,862,186 out=74,555,739 elapsed=373.2s

  [7531/13157] intraday_4372.csv.gz  in=301,882,637 out=74,555,739 elapsed=373.2s

  [7532/13157] intraday_4376.csv.gz  in=301,892,268 out=74,555,739 elapsed=373.3s

  [7533/13157] intraday_4374.csv.gz  in=301,902,818 out=74,555,739 elapsed=373.3s

  [7534/13157] intraday_4375.csv.gz  in=301,916,677 out=74,555,739 elapsed=373.3s

  [7535/13157] intraday_4377.csv.gz  in=301,930,018 out=74,555,739 elapsed=373.3s

  [7536/13157] intraday_4378.csv.gz  in=301,942,920 out=74,555,739 elapsed=373.3s

  [7537/13157] intraday_4380.csv.gz  in=301,954,974 out=74,555,739 elapsed=373.3s

  [7538/13157] intraday_4381.csv.gz  in=301,967,825 out=74,555,739 elapsed=373.3s

  [7539/13157] intraday_4382.csv.gz  in=301,981,137 out=74,555,739 elapsed=373.3s

  [7540/13157] intraday_4379.csv.gz  in=301,995,925 out=74,555,739 elapsed=373.3s

  [7541/13157] intraday_4384.csv.gz  in=302,007,807 out=74,555,739 elapsed=373.5s

  [7542/13157] intraday_4383.csv.gz  in=302,021,018 out=74,555,739 elapsed=373.5s

  [7543/13157] intraday_4385.csv.gz  in=302,035,440 out=74,555,739 elapsed=373.5s

  [7544/13157] intraday_4386.csv.gz  in=302,050,422 out=74,555,739 elapsed=373.5s

  [7545/13157] intraday_4390.csv.gz  in=302,061,665 out=74,555,739 elapsed=373.8s

  [7546/13157] intraday_4389.csv.gz  in=302,072,707 out=74,555,739 elapsed=373.8s

  [7547/13157] intraday_4388.csv.gz  in=302,086,960 out=74,555,739 elapsed=373.8s

  [7548/13157] intraday_4387.csv.gz  in=302,099,316 out=74,555,739 elapsed=373.8s

  [7549/13157] intraday_4394.csv.gz  in=302,107,617 out=74,555,739 elapsed=373.9s

  [7550/13157] intraday_4392.csv.gz  in=302,120,669 out=74,555,739 elapsed=374.0s

  [7551/13157] intraday_4393.csv.gz  in=302,129,547 out=74,555,739 elapsed=374.0s

  [7552/13157] intraday_4391.csv.gz  in=302,142,372 out=74,555,739 elapsed=374.0s

  [7553/13157] intraday_4396.csv.gz  in=302,143,694 out=74,555,739 elapsed=374.0s

  [7554/13157] intraday_4395.csv.gz  in=302,155,491 out=74,555,739 elapsed=374.1s

  [7555/13157] intraday_4398.csv.gz  in=302,170,340 out=74,555,739 elapsed=374.1s

  [7556/13157] intraday_4397.csv.gz  in=302,185,254 out=74,555,739 elapsed=374.1s

  [7557/13157] intraday_4399.csv.gz  in=302,197,919 out=74,555,739 elapsed=374.1s

  [7558/13157] intraday_4400.csv.gz  in=302,208,610 out=74,555,739 elapsed=374.1s

  [7559/13157] intraday_4401.csv.gz  in=302,223,795 out=74,555,739 elapsed=374.1s

  [7560/13157] intraday_4402.csv.gz  in=302,238,504 out=74,555,739 elapsed=374.1s

  [7561/13157] intraday_4403.csv.gz  in=302,251,157 out=74,555,739 elapsed=374.2s

  [7562/13157] intraday_4404.csv.gz  in=302,262,411 out=74,555,739 elapsed=374.2s

  [7563/13157] intraday_4405.csv.gz  in=302,276,165 out=74,555,739 elapsed=374.2s

  [7564/13157] intraday_4408.csv.gz  in=302,288,865 out=74,555,739 elapsed=374.2s

  [7565/13157] intraday_4406.csv.gz  in=302,304,548 out=74,555,739 elapsed=374.2s

  [7566/13157] intraday_4407.csv.gz  in=302,314,511 out=74,555,739 elapsed=374.2s

  [7567/13157] intraday_4409.csv.gz  in=302,328,728 out=74,555,739 elapsed=374.2s

  [7568/13157] intraday_4411.csv.gz  in=302,339,668 out=74,555,739 elapsed=374.2s

  [7569/13157] intraday_4410.csv.gz  in=302,352,438 out=74,555,739 elapsed=374.2s

  [7570/13157] intraday_4412.csv.gz  in=302,363,882 out=74,555,739 elapsed=374.3s

  [7571/13157] intraday_4415.csv.gz  in=302,375,058 out=74,555,739 elapsed=374.3s

  [7572/13157] intraday_4414.csv.gz  in=302,388,117 out=74,555,739 elapsed=374.3s

  [7573/13157] intraday_4413.csv.gz  in=302,401,370 out=74,555,739 elapsed=374.3s

  [7574/13157] intraday_4416.csv.gz  in=302,414,668 out=74,555,739 elapsed=374.3s

  [7575/13157] intraday_4417.csv.gz  in=302,428,127 out=74,555,739 elapsed=374.4s

  [7576/13157] intraday_4419.csv.gz  in=302,439,761 out=74,555,739 elapsed=374.4s

  [7577/13157] intraday_4418.csv.gz  in=302,451,875 out=74,555,739 elapsed=374.4s

  [7578/13157] intraday_4420.csv.gz  in=302,464,575 out=74,555,739 elapsed=374.4s

  [7579/13157] intraday_4422.csv.gz  in=302,474,905 out=74,555,739 elapsed=374.4s

  [7580/13157] intraday_4424.csv.gz  in=302,487,288 out=74,555,739 elapsed=374.4s

  [7581/13157] intraday_4421.csv.gz  in=302,499,254 out=74,555,739 elapsed=374.4s

  [7582/13157] intraday_4423.csv.gz  in=302,512,169 out=74,555,739 elapsed=374.4s

  [7583/13157] intraday_4425.csv.gz  in=302,526,418 out=74,555,739 elapsed=374.6s

  [7584/13157] intraday_4427.csv.gz  in=302,540,086 out=74,555,739 elapsed=374.6s

  [7585/13157] intraday_4426.csv.gz  in=302,555,585 out=74,555,739 elapsed=374.6s

  [7586/13157] intraday_4428.csv.gz  in=302,567,159 out=74,555,739 elapsed=374.6s

  [7587/13157] intraday_4430.csv.gz  in=302,580,280 out=74,555,739 elapsed=374.8s

  [7588/13157] intraday_4429.csv.gz  in=302,592,445 out=74,555,739 elapsed=374.8s

  [7589/13157] intraday_4431.csv.gz  in=302,603,890 out=74,555,739 elapsed=374.8s

  [7590/13157] intraday_4432.csv.gz  in=302,615,943 out=74,555,739 elapsed=374.8s

  [7591/13157] intraday_4433.csv.gz  in=302,626,787 out=74,555,739 elapsed=374.9s

  [7592/13157] intraday_4434.csv.gz  in=302,637,747 out=74,555,739 elapsed=375.0s

  [7593/13157] intraday_4435.csv.gz  in=302,648,651 out=74,555,739 elapsed=375.0s

  [7594/13157] intraday_4436.csv.gz  in=302,660,910 out=74,555,739 elapsed=375.0s

  [7595/13157] intraday_4438.csv.gz  in=302,672,515 out=74,555,739 elapsed=375.1s

  [7596/13157] intraday_4439.csv.gz  in=302,685,603 out=74,555,739 elapsed=375.1s

  [7597/13157] intraday_4440.csv.gz  in=302,696,576 out=74,555,739 elapsed=375.1s

  [7598/13157] intraday_4437.csv.gz  in=302,715,189 out=74,555,739 elapsed=375.1s

  [7599/13157] intraday_4441.csv.gz  in=302,727,062 out=74,555,739 elapsed=375.2s

  [7600/13157] intraday_4444.csv.gz  in=302,739,452 out=74,555,739 elapsed=375.4s

  [7601/13157] intraday_4443.csv.gz  in=302,750,454 out=74,555,739 elapsed=375.4s

  [7602/13157] intraday_4442.csv.gz  in=302,763,175 out=74,555,739 elapsed=375.4s

  [7603/13157] intraday_4445.csv.gz  in=302,777,053 out=74,555,739 elapsed=375.5s

  [7604/13157] intraday_4446.csv.gz  in=302,786,990 out=74,555,739 elapsed=375.5s

  [7605/13157] intraday_4447.csv.gz  in=302,800,192 out=74,555,739 elapsed=375.5s

  [7606/13157] intraday_4448.csv.gz  in=302,811,102 out=74,555,739 elapsed=375.5s

  [7607/13157] intraday_4451.csv.gz  in=302,823,967 out=74,555,739 elapsed=375.5s

  [7608/13157] intraday_4452.csv.gz  in=302,835,521 out=74,555,739 elapsed=375.5s

  [7609/13157] intraday_4450.csv.gz  in=302,848,592 out=74,555,739 elapsed=375.5s

  [7610/13157] intraday_4449.csv.gz  in=302,859,651 out=74,555,739 elapsed=375.5s

  [7611/13157] intraday_4453.csv.gz  in=302,869,776 out=74,555,739 elapsed=375.6s

  [7612/13157] intraday_4455.csv.gz  in=302,881,631 out=74,555,739 elapsed=375.6s

  [7613/13157] intraday_4456.csv.gz  in=302,893,712 out=74,555,739 elapsed=375.6s

  [7614/13157] intraday_4454.csv.gz  in=302,907,306 out=74,555,739 elapsed=375.6s

  [7615/13157] intraday_4457.csv.gz  in=302,918,071 out=74,555,739 elapsed=375.6s

  [7616/13157] intraday_4458.csv.gz  in=302,929,875 out=74,555,739 elapsed=375.6s

  [7617/13157] intraday_4459.csv.gz  in=302,940,967 out=74,555,739 elapsed=375.6s

  [7618/13157] intraday_4460.csv.gz  in=302,954,782 out=74,555,739 elapsed=375.6s

  [7619/13157] intraday_4461.csv.gz  in=302,967,638 out=74,555,739 elapsed=375.7s

  [7620/13157] intraday_4463.csv.gz  in=302,979,866 out=74,555,739 elapsed=375.7s

  [7621/13157] intraday_4462.csv.gz  in=302,993,217 out=74,555,739 elapsed=375.7s

  [7622/13157] intraday_4464.csv.gz  in=303,004,026 out=74,555,739 elapsed=375.7s

  [7623/13157] intraday_4465.csv.gz  in=303,015,485 out=74,555,739 elapsed=375.7s

  [7624/13157] intraday_4466.csv.gz  in=303,027,058 out=74,555,739 elapsed=375.8s

  [7625/13157] intraday_4467.csv.gz  in=303,038,425 out=74,555,739 elapsed=375.8s

  [7626/13157] intraday_4468.csv.gz  in=303,051,466 out=74,555,739 elapsed=375.8s

  [7627/13157] intraday_4469.csv.gz  in=303,062,401 out=74,555,739 elapsed=375.8s

  [7628/13157] intraday_4470.csv.gz  in=303,072,351 out=74,555,739 elapsed=376.0s

  [7629/13157] intraday_4471.csv.gz  in=303,084,523 out=74,555,739 elapsed=376.0s

  [7630/13157] intraday_4473.csv.gz  in=303,095,024 out=74,555,739 elapsed=376.0s

  [7631/13157] intraday_4472.csv.gz  in=303,110,111 out=74,555,739 elapsed=376.0s

  [7632/13157] intraday_4474.csv.gz  in=303,122,141 out=74,555,739 elapsed=376.1s

  [7633/13157] intraday_4475.csv.gz  in=303,132,144 out=74,555,739 elapsed=376.2s

  [7634/13157] intraday_4476.csv.gz  in=303,143,501 out=74,555,739 elapsed=376.2s

  [7635/13157] intraday_4477.csv.gz  in=303,156,781 out=74,555,739 elapsed=376.2s

  [7636/13157] intraday_4478.csv.gz  in=303,172,049 out=74,555,739 elapsed=376.2s

  [7637/13157] intraday_4479.csv.gz  in=303,183,302 out=74,555,739 elapsed=376.3s

  [7638/13157] intraday_4482.csv.gz  in=303,196,619 out=74,555,739 elapsed=376.4s

  [7639/13157] intraday_4480.csv.gz  in=303,207,687 out=74,555,739 elapsed=376.4s

  [7640/13157] intraday_4483.csv.gz  in=303,220,962 out=74,555,739 elapsed=376.4s

  [7641/13157] intraday_4481.csv.gz  in=303,239,599 out=74,555,739 elapsed=376.4s

  [7642/13157] intraday_4486.csv.gz  in=303,254,217 out=74,555,739 elapsed=376.5s

  [7643/13157] intraday_4485.csv.gz  in=303,264,762 out=74,555,739 elapsed=376.5s

  [7644/13157] intraday_4487.csv.gz  in=303,277,802 out=74,555,739 elapsed=376.5s

  [7645/13157] intraday_4484.csv.gz  in=303,292,750 out=74,555,739 elapsed=376.5s

  [7646/13157] intraday_4491.csv.gz  in=303,304,238 out=74,555,739 elapsed=376.6s

  [7647/13157] intraday_4489.csv.gz  in=303,317,257 out=74,555,739 elapsed=376.6s

  [7648/13157] intraday_4490.csv.gz  in=303,329,522 out=74,555,739 elapsed=376.6s

  [7649/13157] intraday_4488.csv.gz  in=303,344,117 out=74,555,739 elapsed=376.6s

  [7650/13157] intraday_4492.csv.gz  in=303,355,867 out=74,555,739 elapsed=376.6s

  [7651/13157] intraday_4493.csv.gz  in=303,367,142 out=74,555,739 elapsed=376.6s

  [7652/13157] intraday_4494.csv.gz  in=303,378,137 out=74,555,739 elapsed=376.6s

  [7653/13157] intraday_4495.csv.gz  in=303,390,140 out=74,555,739 elapsed=376.6s

  [7654/13157] intraday_4496.csv.gz  in=303,401,276 out=74,555,739 elapsed=376.7s

  [7655/13157] intraday_4497.csv.gz  in=303,414,482 out=74,555,739 elapsed=376.7s

  [7656/13157] intraday_4498.csv.gz  in=303,426,553 out=74,555,739 elapsed=376.7s

  [7657/13157] intraday_4499.csv.gz  in=303,439,302 out=74,555,739 elapsed=376.7s

  [7658/13157] intraday_4500.csv.gz  in=303,452,299 out=74,555,739 elapsed=376.7s

  [7659/13157] intraday_4501.csv.gz  in=303,465,386 out=74,555,739 elapsed=376.7s

  [7660/13157] intraday_4504.csv.gz  in=303,479,516 out=74,555,739 elapsed=376.8s

  [7661/13157] intraday_4502.csv.gz  in=303,497,022 out=74,555,739 elapsed=376.8s

  [7662/13157] intraday_4503.csv.gz  in=303,510,115 out=74,555,739 elapsed=376.8s

  [7663/13157] intraday_4505.csv.gz  in=303,520,690 out=74,555,739 elapsed=376.8s

  [7664/13157] intraday_4507.csv.gz  in=303,532,710 out=74,555,739 elapsed=376.8s

  [7665/13157] intraday_4508.csv.gz  in=303,546,504 out=74,555,739 elapsed=376.8s

  [7666/13157] intraday_4506.csv.gz  in=303,561,314 out=74,555,739 elapsed=376.9s

  [7667/13157] intraday_4509.csv.gz  in=303,574,966 out=74,555,739 elapsed=377.0s

  [7668/13157] intraday_4512.csv.gz  in=303,590,805 out=74,555,739 elapsed=377.0s

  [7669/13157] intraday_4510.csv.gz  in=303,604,990 out=74,555,739 elapsed=377.0s

  [7670/13157] intraday_4511.csv.gz  in=303,617,653 out=74,555,739 elapsed=377.0s

  [7671/13157] intraday_4513.csv.gz  in=303,630,411 out=74,555,739 elapsed=377.0s

  [7672/13157] intraday_4514.csv.gz  in=303,641,959 out=74,555,739 elapsed=377.2s

  [7673/13157] intraday_4515.csv.gz  in=303,653,223 out=74,555,739 elapsed=377.2s

  [7674/13157] intraday_4516.csv.gz  in=303,667,427 out=74,555,739 elapsed=377.2s

  [7675/13157] intraday_4517.csv.gz  in=303,677,426 out=74,555,739 elapsed=377.2s

  [7676/13157] intraday_4521.csv.gz  in=303,688,433 out=74,555,739 elapsed=377.4s

  [7677/13157] intraday_4519.csv.gz  in=303,702,359 out=74,555,739 elapsed=377.4s

  [7678/13157] intraday_4518.csv.gz  in=303,716,463 out=74,555,739 elapsed=377.4s

  [7679/13157] intraday_4520.csv.gz  in=303,733,155 out=74,555,739 elapsed=377.4s

  [7680/13157] intraday_4522.csv.gz  in=303,746,007 out=74,555,739 elapsed=377.4s

  [7681/13157] intraday_4525.csv.gz  in=303,757,755 out=74,555,739 elapsed=377.6s

  [7682/13157] intraday_4523.csv.gz  in=303,770,986 out=74,555,739 elapsed=377.6s

  [7683/13157] intraday_4526.csv.gz  in=303,785,425 out=74,555,739 elapsed=377.6s

  [7684/13157] intraday_4524.csv.gz  in=303,797,409 out=74,555,739 elapsed=377.6s

  [7685/13157] intraday_4530.csv.gz  in=303,808,609 out=74,555,739 elapsed=377.8s

  [7686/13157] intraday_4528.csv.gz  in=303,821,153 out=74,555,739 elapsed=377.8s

  [7687/13157] intraday_4529.csv.gz  in=303,834,907 out=74,555,739 elapsed=377.8s

  [7688/13157] intraday_4527.csv.gz  in=303,850,078 out=74,555,739 elapsed=377.8s

  [7689/13157] intraday_4534.csv.gz  in=303,859,056 out=74,555,739 elapsed=377.9s

  [7690/13157] intraday_4533.csv.gz  in=303,871,806 out=74,555,739 elapsed=377.9s

  [7691/13157] intraday_4531.csv.gz  in=303,883,011 out=74,555,739 elapsed=377.9s

  [7692/13157] intraday_4532.csv.gz  in=303,895,339 out=74,555,739 elapsed=377.9s

  [7693/13157] intraday_4535.csv.gz  in=303,904,198 out=74,555,739 elapsed=378.0s

  [7694/13157] intraday_4537.csv.gz  in=303,904,507 out=74,555,739 elapsed=378.0s

  [7695/13157] intraday_4539.csv.gz  in=303,918,396 out=74,555,739 elapsed=378.0s

  [7696/13157] intraday_4536.csv.gz  in=303,930,211 out=74,555,739 elapsed=378.0s

  [7697/13157] intraday_4538.csv.gz  in=303,945,398 out=74,555,739 elapsed=378.0s

  [7698/13157] intraday_4540.csv.gz  in=303,957,781 out=74,555,739 elapsed=378.0s

  [7699/13157] intraday_4541.csv.gz  in=303,968,327 out=74,555,739 elapsed=378.2s

  [7700/13157] intraday_4542.csv.gz  in=303,983,527 out=74,555,739 elapsed=378.2s

  [7701/13157] intraday_4544.csv.gz  in=303,997,499 out=74,555,739 elapsed=378.2s

  [7702/13157] intraday_4543.csv.gz  in=304,019,260 out=74,555,739 elapsed=378.2s

  [7703/13157] intraday_4548.csv.gz  in=304,029,746 out=74,555,739 elapsed=378.3s

  [7704/13157] intraday_4545.csv.gz  in=304,042,480 out=74,555,739 elapsed=378.3s

  [7705/13157] intraday_4546.csv.gz  in=304,055,992 out=74,555,739 elapsed=378.3s

  [7706/13157] intraday_4547.csv.gz  in=304,071,126 out=74,555,739 elapsed=378.4s

  [7707/13157] intraday_4549.csv.gz  in=304,083,725 out=74,555,739 elapsed=378.4s

  [7708/13157] intraday_4550.csv.gz  in=304,096,302 out=74,555,739 elapsed=378.4s

  [7709/13157] intraday_4552.csv.gz  in=304,107,081 out=74,555,739 elapsed=378.4s

  [7710/13157] intraday_4551.csv.gz  in=304,118,266 out=74,555,739 elapsed=378.4s

  [7711/13157] intraday_4553.csv.gz  in=304,129,235 out=74,555,739 elapsed=378.4s

  [7712/13157] intraday_4554.csv.gz  in=304,142,366 out=74,555,739 elapsed=378.4s

  [7713/13157] intraday_4555.csv.gz  in=304,155,080 out=74,555,739 elapsed=378.5s

  [7714/13157] intraday_4556.csv.gz  in=304,165,788 out=74,555,739 elapsed=378.5s

  [7715/13157] intraday_4557.csv.gz  in=304,178,137 out=74,555,739 elapsed=378.5s

  [7716/13157] intraday_4558.csv.gz  in=304,191,406 out=74,555,739 elapsed=378.5s

  [7717/13157] intraday_4559.csv.gz  in=304,204,537 out=74,555,739 elapsed=378.5s

  [7718/13157] intraday_4560.csv.gz  in=304,216,818 out=74,555,739 elapsed=378.5s

  [7719/13157] intraday_4563.csv.gz  in=304,227,584 out=74,555,739 elapsed=378.5s

  [7720/13157] intraday_4562.csv.gz  in=304,238,951 out=74,555,739 elapsed=378.5s

  [7721/13157] intraday_4561.csv.gz  in=304,253,447 out=74,555,739 elapsed=378.5s

  [7722/13157] intraday_4564.csv.gz  in=304,265,854 out=74,555,739 elapsed=378.5s

  [7723/13157] intraday_4565.csv.gz  in=304,278,289 out=74,555,739 elapsed=378.6s

  [7724/13157] intraday_4568.csv.gz  in=304,291,248 out=74,555,739 elapsed=378.6s

  [7725/13157] intraday_4566.csv.gz  in=304,305,592 out=74,555,739 elapsed=378.6s

  [7726/13157] intraday_4570.csv.gz  in=304,317,077 out=74,555,739 elapsed=378.6s

  [7727/13157] intraday_4567.csv.gz  in=304,332,031 out=74,555,739 elapsed=378.6s

  [7728/13157] intraday_4571.csv.gz  in=304,345,905 out=74,555,739 elapsed=378.6s

  [7729/13157] intraday_4569.csv.gz  in=304,357,368 out=74,555,739 elapsed=378.6s

  [7730/13157] intraday_4572.csv.gz  in=304,367,951 out=74,555,739 elapsed=378.7s

  [7731/13157] intraday_4575.csv.gz  in=304,378,524 out=74,555,739 elapsed=378.7s

  [7732/13157] intraday_4573.csv.gz  in=304,391,469 out=74,555,739 elapsed=378.7s

  [7733/13157] intraday_4574.csv.gz  in=304,402,338 out=74,555,739 elapsed=378.7s

  [7734/13157] intraday_4576.csv.gz  in=304,414,156 out=74,555,739 elapsed=378.8s

  [7735/13157] intraday_4579.csv.gz  in=304,427,041 out=74,555,739 elapsed=378.9s

  [7736/13157] intraday_4577.csv.gz  in=304,439,099 out=74,555,739 elapsed=378.9s

  [7737/13157] intraday_4578.csv.gz  in=304,451,120 out=74,555,739 elapsed=378.9s

  [7738/13157] intraday_4580.csv.gz  in=304,464,985 out=74,555,739 elapsed=378.9s

  [7739/13157] intraday_4582.csv.gz  in=304,478,944 out=74,555,739 elapsed=379.0s

  [7740/13157] intraday_4581.csv.gz  in=304,489,827 out=74,555,739 elapsed=379.0s

  [7741/13157] intraday_4583.csv.gz  in=304,501,532 out=74,555,739 elapsed=379.0s

  [7742/13157] intraday_4584.csv.gz  in=304,512,684 out=74,555,739 elapsed=379.0s

  [7743/13157] intraday_4585.csv.gz  in=304,524,768 out=74,555,739 elapsed=379.0s

  [7744/13157] intraday_4587.csv.gz  in=304,534,376 out=74,555,739 elapsed=379.0s

  [7745/13157] intraday_4586.csv.gz  in=304,545,496 out=74,555,739 elapsed=379.1s

  [7746/13157] intraday_4588.csv.gz  in=304,559,590 out=74,555,739 elapsed=379.1s

  [7747/13157] intraday_4589.csv.gz  in=304,569,414 out=74,555,739 elapsed=379.2s

  [7748/13157] intraday_4592.csv.gz  in=304,581,348 out=74,555,739 elapsed=379.3s

  [7749/13157] intraday_4590.csv.gz  in=304,593,109 out=74,555,739 elapsed=379.3s

  [7750/13157] intraday_4591.csv.gz  in=304,604,616 out=74,555,739 elapsed=379.3s

  [7751/13157] intraday_4593.csv.gz  in=304,616,226 out=74,555,739 elapsed=379.3s

  [7752/13157] intraday_4597.csv.gz  in=304,628,565 out=74,555,739 elapsed=379.5s

  [7753/13157] intraday_4596.csv.gz  in=304,639,274 out=74,555,739 elapsed=379.5s

  [7754/13157] intraday_4594.csv.gz  in=304,649,648 out=74,555,739 elapsed=379.5s

  [7755/13157] intraday_4595.csv.gz  in=304,665,586 out=74,555,739 elapsed=379.5s

  [7756/13157] intraday_4600.csv.gz  in=304,676,780 out=74,555,739 elapsed=379.6s

  [7757/13157] intraday_4598.csv.gz  in=304,687,954 out=74,555,739 elapsed=379.6s

  [7758/13157] intraday_4599.csv.gz  in=304,708,609 out=74,555,739 elapsed=379.6s

  [7759/13157] intraday_4601.csv.gz  in=304,722,578 out=74,555,739 elapsed=379.6s

  [7760/13157] intraday_4602.csv.gz  in=304,736,033 out=74,555,739 elapsed=379.6s

  [7761/13157] intraday_4605.csv.gz  in=304,745,785 out=74,555,739 elapsed=379.6s

  [7762/13157] intraday_4603.csv.gz  in=304,759,344 out=74,555,739 elapsed=379.7s

  [7763/13157] intraday_4604.csv.gz  in=304,771,437 out=74,555,739 elapsed=379.7s

  [7764/13157] intraday_4608.csv.gz  in=304,783,712 out=74,555,739 elapsed=379.7s

  [7765/13157] intraday_4607.csv.gz  in=304,794,838 out=74,555,739 elapsed=379.7s

  [7766/13157] intraday_4606.csv.gz  in=304,818,699 out=74,555,739 elapsed=379.8s

  [7767/13157] intraday_4609.csv.gz  in=304,831,380 out=74,555,739 elapsed=379.9s

  [7768/13157] intraday_4610.csv.gz  in=304,843,077 out=74,555,739 elapsed=379.9s

  [7769/13157] intraday_4611.csv.gz  in=304,853,089 out=74,555,739 elapsed=379.9s

  [7770/13157] intraday_4612.csv.gz  in=304,865,119 out=74,555,739 elapsed=379.9s

  [7771/13157] intraday_4613.csv.gz  in=304,879,522 out=74,555,739 elapsed=380.0s

  [7772/13157] intraday_4616.csv.gz  in=304,889,852 out=74,555,739 elapsed=380.0s

  [7773/13157] intraday_4614.csv.gz  in=304,901,332 out=74,555,739 elapsed=380.0s

  [7774/13157] intraday_4615.csv.gz  in=304,913,806 out=74,555,739 elapsed=380.0s

  [7775/13157] intraday_4617.csv.gz  in=304,925,253 out=74,555,739 elapsed=380.2s

  [7776/13157] intraday_4620.csv.gz  in=304,938,323 out=74,555,739 elapsed=380.2s

  [7777/13157] intraday_4619.csv.gz  in=304,955,354 out=74,555,739 elapsed=380.2s

  [7778/13157] intraday_4618.csv.gz  in=304,968,096 out=74,555,739 elapsed=380.2s

  [7779/13157] intraday_4621.csv.gz  in=304,979,454 out=74,555,739 elapsed=380.3s

  [7780/13157] intraday_4622.csv.gz  in=304,989,897 out=74,555,739 elapsed=380.3s

  [7781/13157] intraday_4623.csv.gz  in=305,003,930 out=74,555,739 elapsed=380.3s

  [7782/13157] intraday_4624.csv.gz  in=305,018,692 out=74,555,739 elapsed=380.3s

  [7783/13157] intraday_4625.csv.gz  in=305,033,131 out=74,555,739 elapsed=380.3s

  [7784/13157] intraday_4626.csv.gz  in=305,043,913 out=74,555,739 elapsed=380.4s

  [7785/13157] intraday_4629.csv.gz  in=305,061,389 out=74,555,739 elapsed=380.4s

  [7786/13157] intraday_4628.csv.gz  in=305,075,313 out=74,555,739 elapsed=380.4s

  [7787/13157] intraday_4627.csv.gz  in=305,091,970 out=74,555,739 elapsed=380.4s

  [7788/13157] intraday_4631.csv.gz  in=305,103,997 out=74,555,739 elapsed=380.4s

  [7789/13157] intraday_4630.csv.gz  in=305,118,061 out=74,555,739 elapsed=380.4s

  [7790/13157] intraday_4632.csv.gz  in=305,129,616 out=74,555,739 elapsed=380.4s

  [7791/13157] intraday_4633.csv.gz  in=305,141,799 out=74,555,739 elapsed=380.4s

  [7792/13157] intraday_4634.csv.gz  in=305,153,020 out=74,555,739 elapsed=380.5s

  [7793/13157] intraday_4635.csv.gz  in=305,164,409 out=74,555,739 elapsed=380.5s

  [7794/13157] intraday_4637.csv.gz  in=305,176,721 out=74,555,739 elapsed=380.5s

  [7795/13157] intraday_4636.csv.gz  in=305,188,087 out=74,555,739 elapsed=380.5s

  [7796/13157] intraday_4639.csv.gz  in=305,200,254 out=74,555,739 elapsed=380.5s

  [7797/13157] intraday_4638.csv.gz  in=305,216,685 out=74,555,739 elapsed=380.5s

  [7798/13157] intraday_4643.csv.gz  in=305,229,190 out=74,555,739 elapsed=380.5s

  [7799/13157] intraday_4642.csv.gz  in=305,241,738 out=74,555,739 elapsed=380.5s

  [7800/13157] intraday_4640.csv.gz  in=305,255,412 out=74,555,739 elapsed=380.5s

  [7801/13157] intraday_4641.csv.gz  in=305,268,184 out=74,555,739 elapsed=380.5s

  [7802/13157] intraday_4647.csv.gz  in=305,282,356 out=74,555,739 elapsed=380.6s

  [7803/13157] intraday_4646.csv.gz  in=305,293,881 out=74,555,739 elapsed=380.6s

  [7804/13157] intraday_4645.csv.gz  in=305,306,936 out=74,555,739 elapsed=380.6s

  [7805/13157] intraday_4644.csv.gz  in=305,320,769 out=74,555,739 elapsed=380.6s

  [7806/13157] intraday_4648.csv.gz  in=305,334,011 out=74,555,739 elapsed=380.6s

  [7807/13157] intraday_4650.csv.gz  in=305,348,395 out=74,555,739 elapsed=380.7s

  [7808/13157] intraday_4649.csv.gz  in=305,363,190 out=74,555,739 elapsed=380.7s

  [7809/13157] intraday_4651.csv.gz  in=305,376,193 out=74,555,739 elapsed=380.7s

  [7810/13157] intraday_4653.csv.gz  in=305,390,561 out=74,555,739 elapsed=380.7s

  [7811/13157] intraday_4652.csv.gz  in=305,405,242 out=74,555,739 elapsed=380.7s

  [7812/13157] intraday_4655.csv.gz  in=305,416,849 out=74,555,739 elapsed=380.7s

  [7813/13157] intraday_4654.csv.gz  in=305,429,838 out=74,555,739 elapsed=380.7s

  [7814/13157] intraday_4656.csv.gz  in=305,440,189 out=74,555,739 elapsed=380.8s

  [7815/13157] intraday_4658.csv.gz  in=305,451,636 out=74,555,739 elapsed=380.8s

  [7816/13157] intraday_4659.csv.gz  in=305,466,136 out=74,555,739 elapsed=380.8s

  [7817/13157] intraday_4657.csv.gz  in=305,479,136 out=74,555,739 elapsed=380.8s

  [7818/13157] intraday_4660.csv.gz  in=305,492,776 out=74,555,739 elapsed=380.9s

  [7819/13157] intraday_4662.csv.gz  in=305,504,885 out=74,555,739 elapsed=380.9s

  [7820/13157] intraday_4661.csv.gz  in=305,522,314 out=74,555,739 elapsed=380.9s

  [7821/13157] intraday_4663.csv.gz  in=305,535,883 out=74,555,739 elapsed=380.9s

  [7822/13157] intraday_4665.csv.gz  in=305,547,265 out=74,555,739 elapsed=380.9s

  [7823/13157] intraday_4666.csv.gz  in=305,560,070 out=74,555,739 elapsed=380.9s

  [7824/13157] intraday_4664.csv.gz  in=305,573,512 out=74,555,739 elapsed=381.0s

  [7825/13157] intraday_4667.csv.gz  in=305,588,561 out=74,555,739 elapsed=381.0s

  [7826/13157] intraday_4669.csv.gz  in=305,601,236 out=74,555,739 elapsed=381.0s

  [7827/13157] intraday_4668.csv.gz  in=305,615,423 out=74,555,739 elapsed=381.0s

  [7828/13157] intraday_4671.csv.gz  in=305,626,282 out=74,555,739 elapsed=381.0s

  [7829/13157] intraday_4670.csv.gz  in=305,642,849 out=74,555,739 elapsed=381.0s

  [7830/13157] intraday_4675.csv.gz  in=305,652,048 out=74,555,739 elapsed=381.0s

  [7831/13157] intraday_4672.csv.gz  in=305,663,388 out=74,555,739 elapsed=381.0s

  [7832/13157] intraday_4673.csv.gz  in=305,674,983 out=74,555,739 elapsed=381.1s

  [7833/13157] intraday_4674.csv.gz  in=305,688,391 out=74,555,739 elapsed=381.1s

  [7834/13157] intraday_4676.csv.gz  in=305,702,676 out=74,555,739 elapsed=381.1s

  [7835/13157] intraday_4678.csv.gz  in=305,702,948 out=74,555,739 elapsed=381.1s

  [7836/13157] intraday_4677.csv.gz  in=305,714,411 out=74,555,739 elapsed=381.1s

  [7837/13157] intraday_4679.csv.gz  in=305,728,714 out=74,555,739 elapsed=381.1s

  [7838/13157] intraday_4680.csv.gz  in=305,742,481 out=74,555,739 elapsed=381.1s

  [7839/13157] intraday_4681.csv.gz  in=305,754,294 out=74,555,739 elapsed=381.1s

  [7840/13157] intraday_4682.csv.gz  in=305,764,097 out=74,555,739 elapsed=381.2s

  [7841/13157] intraday_4685.csv.gz  in=305,776,227 out=74,555,739 elapsed=381.2s

  [7842/13157] intraday_4684.csv.gz  in=305,792,403 out=74,555,739 elapsed=381.2s

  [7843/13157] intraday_4683.csv.gz  in=305,807,358 out=74,555,739 elapsed=381.2s

  [7844/13157] intraday_4686.csv.gz  in=305,819,672 out=74,555,739 elapsed=381.2s

  [7845/13157] intraday_4689.csv.gz  in=305,830,320 out=74,555,739 elapsed=381.2s

  [7846/13157] intraday_4688.csv.gz  in=305,844,281 out=74,555,739 elapsed=381.2s

  [7847/13157] intraday_4687.csv.gz  in=305,857,831 out=74,555,739 elapsed=381.3s

  [7848/13157] intraday_4690.csv.gz  in=305,869,654 out=74,555,739 elapsed=381.3s

  [7849/13157] intraday_4692.csv.gz  in=305,879,781 out=74,555,739 elapsed=381.3s

  [7850/13157] intraday_4693.csv.gz  in=305,890,410 out=74,555,739 elapsed=381.3s

  [7851/13157] intraday_4691.csv.gz  in=305,903,521 out=74,555,739 elapsed=381.3s

  [7852/13157] intraday_4696.csv.gz  in=305,915,716 out=74,555,739 elapsed=381.4s

  [7853/13157] intraday_4694.csv.gz  in=305,925,629 out=74,555,739 elapsed=381.4s

  [7854/13157] intraday_4697.csv.gz  in=305,935,601 out=74,555,739 elapsed=381.4s

  [7855/13157] intraday_4695.csv.gz  in=305,948,658 out=74,555,739 elapsed=381.4s

  [7856/13157] intraday_4699.csv.gz  in=305,961,544 out=74,555,739 elapsed=381.4s

  [7857/13157] intraday_4698.csv.gz  in=305,973,494 out=74,555,739 elapsed=381.5s

  [7858/13157] intraday_4701.csv.gz  in=305,987,452 out=74,555,739 elapsed=381.5s

  [7859/13157] intraday_4700.csv.gz  in=306,000,695 out=74,555,739 elapsed=381.5s

  [7860/13157] intraday_4702.csv.gz  in=306,012,492 out=74,555,739 elapsed=381.5s

  [7861/13157] intraday_4703.csv.gz  in=306,024,316 out=74,555,739 elapsed=381.5s

  [7862/13157] intraday_4704.csv.gz  in=306,034,325 out=74,555,739 elapsed=381.5s

  [7863/13157] intraday_4705.csv.gz  in=306,046,461 out=74,555,739 elapsed=381.5s

  [7864/13157] intraday_4707.csv.gz  in=306,059,035 out=74,555,739 elapsed=381.7s

  [7865/13157] intraday_4706.csv.gz  in=306,075,094 out=74,555,739 elapsed=381.7s

  [7866/13157] intraday_4708.csv.gz  in=306,088,931 out=74,555,739 elapsed=381.7s

  [7867/13157] intraday_4709.csv.gz  in=306,103,721 out=74,555,739 elapsed=381.7s

  [7868/13157] intraday_4710.csv.gz  in=306,114,671 out=74,555,739 elapsed=381.7s

  [7869/13157] intraday_4711.csv.gz  in=306,125,483 out=74,555,739 elapsed=381.7s

  [7870/13157] intraday_4712.csv.gz  in=306,138,106 out=74,555,739 elapsed=381.7s

  [7871/13157] intraday_4713.csv.gz  in=306,164,165 out=74,555,739 elapsed=381.7s

  [7872/13157] intraday_4714.csv.gz  in=306,176,463 out=74,555,739 elapsed=381.7s

  [7873/13157] intraday_4715.csv.gz  in=306,186,543 out=74,555,739 elapsed=381.8s

  [7874/13157] intraday_4716.csv.gz  in=306,197,259 out=74,555,739 elapsed=381.8s

  [7875/13157] intraday_4718.csv.gz  in=306,208,763 out=74,555,739 elapsed=381.8s

  [7876/13157] intraday_4719.csv.gz  in=306,222,295 out=74,555,739 elapsed=381.8s

  [7877/13157] intraday_4721.csv.gz  in=306,234,350 out=74,555,739 elapsed=381.8s

  [7878/13157] intraday_4717.csv.gz  in=306,264,698 out=74,555,739 elapsed=381.8s

  [7879/13157] intraday_4720.csv.gz  in=306,286,164 out=74,555,739 elapsed=381.8s

  [7880/13157] intraday_4722.csv.gz  in=306,297,183 out=74,555,739 elapsed=381.9s

  [7881/13157] intraday_4723.csv.gz  in=306,308,527 out=74,555,739 elapsed=381.9s

  [7882/13157] intraday_4724.csv.gz  in=306,321,420 out=74,555,739 elapsed=381.9s

  [7883/13157] intraday_4725.csv.gz  in=306,331,475 out=74,555,739 elapsed=381.9s

  [7884/13157] intraday_4728.csv.gz  in=306,341,007 out=74,555,739 elapsed=381.9s

  [7885/13157] intraday_4726.csv.gz  in=306,352,442 out=74,555,739 elapsed=381.9s

  [7886/13157] intraday_4729.csv.gz  in=306,363,601 out=74,555,739 elapsed=381.9s

  [7887/13157] intraday_4727.csv.gz  in=306,374,864 out=74,555,739 elapsed=381.9s

  [7888/13157] intraday_4732.csv.gz  in=306,387,366 out=74,555,739 elapsed=382.0s

  [7889/13157] intraday_4730.csv.gz  in=306,398,805 out=74,555,739 elapsed=382.0s

  [7890/13157] intraday_4731.csv.gz  in=306,414,520 out=74,555,739 elapsed=382.0s

  [7891/13157] intraday_4733.csv.gz  in=306,426,577 out=74,555,739 elapsed=382.0s

  [7892/13157] intraday_4734.csv.gz  in=306,436,258 out=74,555,739 elapsed=382.0s

  [7893/13157] intraday_4735.csv.gz  in=306,447,072 out=74,555,739 elapsed=382.0s

  [7894/13157] intraday_4736.csv.gz  in=306,459,017 out=74,555,739 elapsed=382.0s

  [7895/13157] intraday_4737.csv.gz  in=306,471,489 out=74,555,739 elapsed=382.0s

  [7896/13157] intraday_4740.csv.gz  in=306,483,525 out=74,555,739 elapsed=382.1s

  [7897/13157] intraday_4738.csv.gz  in=306,495,325 out=74,555,739 elapsed=382.1s

  [7898/13157] intraday_4741.csv.gz  in=306,505,748 out=74,555,739 elapsed=382.1s

  [7899/13157] intraday_4739.csv.gz  in=306,518,038 out=74,555,739 elapsed=382.1s

  [7900/13157] intraday_4745.csv.gz  in=306,529,060 out=74,555,739 elapsed=382.2s

  [7901/13157] intraday_4742.csv.gz  in=306,544,624 out=74,555,739 elapsed=382.2s

  [7902/13157] intraday_4744.csv.gz  in=306,557,900 out=74,555,739 elapsed=382.2s

  [7903/13157] intraday_4743.csv.gz  in=306,571,109 out=74,555,739 elapsed=382.2s

  [7904/13157] intraday_4746.csv.gz  in=306,582,595 out=74,555,739 elapsed=382.2s

  [7905/13157] intraday_4747.csv.gz  in=306,592,091 out=74,555,739 elapsed=382.2s

  [7906/13157] intraday_4748.csv.gz  in=306,604,305 out=74,555,739 elapsed=382.2s

  [7907/13157] intraday_4749.csv.gz  in=306,615,616 out=74,555,739 elapsed=382.3s

  [7908/13157] intraday_4750.csv.gz  in=306,628,933 out=74,555,739 elapsed=382.3s

  [7909/13157] intraday_4751.csv.gz  in=306,639,525 out=74,555,739 elapsed=382.3s

  [7910/13157] intraday_4752.csv.gz  in=306,650,585 out=74,555,739 elapsed=382.3s

  [7911/13157] intraday_4753.csv.gz  in=306,661,030 out=74,555,739 elapsed=382.3s

  [7912/13157] intraday_4754.csv.gz  in=306,674,537 out=74,555,739 elapsed=382.3s

  [7913/13157] intraday_4755.csv.gz  in=306,686,426 out=74,555,739 elapsed=382.3s

  [7914/13157] intraday_4756.csv.gz  in=306,699,216 out=74,555,739 elapsed=382.4s

  [7915/13157] intraday_4757.csv.gz  in=306,709,444 out=74,555,739 elapsed=382.4s

  [7916/13157] intraday_4758.csv.gz  in=306,719,319 out=74,555,739 elapsed=382.4s

  [7917/13157] intraday_4759.csv.gz  in=306,730,557 out=74,555,739 elapsed=382.4s

  [7918/13157] intraday_4762.csv.gz  in=306,741,974 out=74,555,739 elapsed=382.4s

  [7919/13157] intraday_4761.csv.gz  in=306,756,261 out=74,555,739 elapsed=382.4s

  [7920/13157] intraday_4760.csv.gz  in=306,772,157 out=74,555,739 elapsed=382.4s

  [7921/13157] intraday_4763.csv.gz  in=306,783,144 out=74,555,739 elapsed=382.4s

  [7922/13157] intraday_4764.csv.gz  in=306,793,232 out=74,555,739 elapsed=382.4s

  [7923/13157] intraday_4765.csv.gz  in=306,806,411 out=74,555,739 elapsed=382.5s

  [7924/13157] intraday_4767.csv.gz  in=306,818,530 out=74,555,739 elapsed=382.5s

  [7925/13157] intraday_4766.csv.gz  in=306,834,151 out=74,555,739 elapsed=382.5s

  [7926/13157] intraday_4768.csv.gz  in=306,847,961 out=74,555,739 elapsed=382.5s

  [7927/13157] intraday_4769.csv.gz  in=306,860,646 out=74,555,739 elapsed=382.6s

  [7928/13157] intraday_4770.csv.gz  in=306,873,748 out=74,555,739 elapsed=382.6s

  [7929/13157] intraday_4772.csv.gz  in=306,885,976 out=74,555,739 elapsed=382.6s

  [7930/13157] intraday_4771.csv.gz  in=306,902,995 out=74,555,739 elapsed=382.6s

  [7931/13157] intraday_4774.csv.gz  in=306,913,671 out=74,555,739 elapsed=382.6s

  [7932/13157] intraday_4775.csv.gz  in=306,924,601 out=74,555,739 elapsed=382.6s

  [7933/13157] intraday_4776.csv.gz  in=306,936,830 out=74,555,739 elapsed=382.6s

  [7934/13157] intraday_4773.csv.gz  in=306,956,487 out=74,555,739 elapsed=382.6s

  [7935/13157] intraday_4777.csv.gz  in=306,967,718 out=74,555,739 elapsed=382.7s

  [7936/13157] intraday_4779.csv.gz  in=306,981,776 out=74,555,739 elapsed=382.7s

  [7937/13157] intraday_4778.csv.gz  in=306,993,467 out=74,555,739 elapsed=382.7s

  [7938/13157] intraday_4782.csv.gz  in=307,008,114 out=74,555,739 elapsed=382.9s

  [7939/13157] intraday_4780.csv.gz  in=307,030,111 out=74,555,739 elapsed=382.9s

  [7940/13157] intraday_4783.csv.gz  in=307,040,544 out=74,555,739 elapsed=382.9s

  [7941/13157] intraday_4781.csv.gz  in=307,069,182 out=74,555,739 elapsed=382.9s

  [7942/13157] intraday_4785.csv.gz  in=307,082,051 out=74,555,739 elapsed=383.1s

  [7943/13157] intraday_4784.csv.gz  in=307,093,975 out=74,555,739 elapsed=383.1s

  [7944/13157] intraday_4786.csv.gz  in=307,108,272 out=74,555,739 elapsed=383.1s

  [7945/13157] intraday_4787.csv.gz  in=307,120,243 out=74,555,739 elapsed=383.1s

  [7946/13157] intraday_4791.csv.gz  in=307,135,179 out=74,555,739 elapsed=383.3s

  [7947/13157] intraday_4788.csv.gz  in=307,148,061 out=74,555,739 elapsed=383.3s

  [7948/13157] intraday_4789.csv.gz  in=307,161,018 out=74,555,739 elapsed=383.3s

  [7949/13157] intraday_4790.csv.gz  in=307,174,747 out=74,555,739 elapsed=383.3s

  [7950/13157] intraday_4793.csv.gz  in=307,185,614 out=74,555,739 elapsed=383.5s

  [7951/13157] intraday_4795.csv.gz  in=307,197,862 out=74,555,739 elapsed=383.7s

  [7952/13157] intraday_4792.csv.gz  in=307,211,592 out=74,555,739 elapsed=383.7s

  [7953/13157] intraday_4796.csv.gz  in=307,223,318 out=74,555,739 elapsed=383.7s

  [7954/13157] intraday_4794.csv.gz  in=307,239,122 out=74,555,739 elapsed=383.7s

  [7955/13157] intraday_4797.csv.gz  in=307,249,654 out=74,555,739 elapsed=383.8s

  [7956/13157] intraday_4799.csv.gz  in=307,263,634 out=74,555,739 elapsed=384.0s

  [7957/13157] intraday_4800.csv.gz  in=307,277,223 out=74,555,739 elapsed=384.0s

  [7958/13157] intraday_4798.csv.gz  in=307,289,076 out=74,555,739 elapsed=384.0s

  [7959/13157] intraday_4803.csv.gz  in=307,300,450 out=74,555,739 elapsed=384.2s

  [7960/13157] intraday_4804.csv.gz  in=307,313,312 out=74,555,739 elapsed=384.2s

  [7961/13157] intraday_4802.csv.gz  in=307,330,701 out=74,555,739 elapsed=384.3s

  [7962/13157] intraday_4801.csv.gz  in=307,357,661 out=74,555,739 elapsed=384.3s

  [7963/13157] intraday_4805.csv.gz  in=307,368,625 out=74,555,739 elapsed=384.4s

  [7964/13157] intraday_4807.csv.gz  in=307,379,063 out=74,555,739 elapsed=384.5s

  [7965/13157] intraday_4808.csv.gz  in=307,392,019 out=74,555,739 elapsed=384.5s

  [7966/13157] intraday_4806.csv.gz  in=307,404,917 out=74,555,739 elapsed=384.5s

  [7967/13157] intraday_4809.csv.gz  in=307,419,224 out=74,555,739 elapsed=384.5s

  [7968/13157] intraday_4810.csv.gz  in=307,432,380 out=74,555,739 elapsed=384.5s

  [7969/13157] intraday_4813.csv.gz  in=307,444,187 out=74,555,739 elapsed=384.6s

  [7970/13157] intraday_4812.csv.gz  in=307,455,292 out=74,555,739 elapsed=384.6s

  [7971/13157] intraday_4811.csv.gz  in=307,468,615 out=74,555,739 elapsed=384.6s

  [7972/13157] intraday_4814.csv.gz  in=307,480,782 out=74,555,739 elapsed=384.6s

  [7973/13157] intraday_4817.csv.gz  in=307,488,644 out=74,555,739 elapsed=384.6s

  [7974/13157] intraday_4815.csv.gz  in=307,500,012 out=74,555,739 elapsed=384.6s

  [7975/13157] intraday_4816.csv.gz  in=307,511,133 out=74,555,739 elapsed=384.6s

  [7976/13157] intraday_4818.csv.gz  in=307,520,739 out=74,555,739 elapsed=384.7s

  [7977/13157] intraday_4819.csv.gz  in=307,534,505 out=74,555,739 elapsed=384.7s

  [7978/13157] intraday_4820.csv.gz  in=307,550,061 out=74,555,739 elapsed=384.7s

  [7979/13157] intraday_4821.csv.gz  in=307,564,233 out=74,555,739 elapsed=384.7s

  [7980/13157] intraday_4823.csv.gz  in=307,573,691 out=74,555,739 elapsed=384.7s

  [7981/13157] intraday_4822.csv.gz  in=307,586,166 out=74,555,739 elapsed=384.7s

  [7982/13157] intraday_4824.csv.gz  in=307,600,999 out=74,555,739 elapsed=384.7s

  [7983/13157] intraday_4825.csv.gz  in=307,617,094 out=74,555,739 elapsed=384.8s

  [7984/13157] intraday_4826.csv.gz  in=307,629,415 out=74,555,739 elapsed=384.9s

  [7985/13157] intraday_4827.csv.gz  in=307,640,806 out=74,555,739 elapsed=384.9s

  [7986/13157] intraday_4828.csv.gz  in=307,655,126 out=74,555,739 elapsed=384.9s

  [7987/13157] intraday_4829.csv.gz  in=307,668,833 out=74,555,739 elapsed=384.9s

  [7988/13157] intraday_4831.csv.gz  in=307,680,924 out=74,555,739 elapsed=384.9s

  [7989/13157] intraday_4830.csv.gz  in=307,691,449 out=74,555,739 elapsed=385.0s

  [7990/13157] intraday_4832.csv.gz  in=307,703,691 out=74,555,739 elapsed=385.0s

  [7991/13157] intraday_4835.csv.gz  in=307,714,043 out=74,555,739 elapsed=385.1s

  [7992/13157] intraday_4834.csv.gz  in=307,724,805 out=74,555,739 elapsed=385.1s

  [7993/13157] intraday_4833.csv.gz  in=307,738,581 out=74,555,739 elapsed=385.1s

  [7994/13157] intraday_4837.csv.gz  in=307,750,553 out=74,555,739 elapsed=385.2s

  [7995/13157] intraday_4838.csv.gz  in=307,760,734 out=74,555,739 elapsed=385.2s

  [7996/13157] intraday_4839.csv.gz  in=307,772,352 out=74,555,739 elapsed=385.2s

  [7997/13157] intraday_4836.csv.gz  in=307,785,432 out=74,555,739 elapsed=385.2s

  [7998/13157] intraday_4843.csv.gz  in=307,797,761 out=74,555,739 elapsed=385.4s

  [7999/13157] intraday_4840.csv.gz  in=307,810,981 out=74,555,739 elapsed=385.4s

  [8000/13157] intraday_4842.csv.gz  in=307,822,345 out=74,555,739 elapsed=385.4s

  [8001/13157] intraday_4841.csv.gz  in=307,835,441 out=74,555,739 elapsed=385.4s

  [8002/13157] intraday_4845.csv.gz  in=307,845,110 out=74,555,739 elapsed=385.5s

  [8003/13157] intraday_4847.csv.gz  in=307,856,756 out=74,555,739 elapsed=385.5s

  [8004/13157] intraday_4846.csv.gz  in=307,869,749 out=74,555,739 elapsed=385.5s

  [8005/13157] intraday_4848.csv.gz  in=307,881,907 out=74,555,739 elapsed=385.6s

  [8006/13157] intraday_4849.csv.gz  in=307,896,988 out=74,555,739 elapsed=385.6s

  [8007/13157] intraday_4850.csv.gz  in=307,911,650 out=74,555,739 elapsed=385.6s

  [8008/13157] intraday_4844.csv.gz  in=307,943,905 out=74,555,739 elapsed=385.6s

  [8009/13157] intraday_4851.csv.gz  in=307,955,051 out=74,555,739 elapsed=385.6s

  [8010/13157] intraday_4852.csv.gz  in=307,966,148 out=74,555,739 elapsed=385.6s

  [8011/13157] intraday_4853.csv.gz  in=307,978,478 out=74,555,739 elapsed=385.6s

  [8012/13157] intraday_4854.csv.gz  in=307,990,761 out=74,555,739 elapsed=385.6s

  [8013/13157] intraday_4856.csv.gz  in=308,000,425 out=74,555,739 elapsed=385.6s

  [8014/13157] intraday_4857.csv.gz  in=308,011,573 out=74,555,739 elapsed=385.7s

  [8015/13157] intraday_4858.csv.gz  in=308,022,869 out=74,555,739 elapsed=385.8s

  [8016/13157] intraday_4859.csv.gz  in=308,033,872 out=74,555,739 elapsed=385.8s

  [8017/13157] intraday_4855.csv.gz  in=308,058,672 out=74,555,739 elapsed=385.8s

  [8018/13157] intraday_4860.csv.gz  in=308,072,694 out=74,555,739 elapsed=385.8s

  [8019/13157] intraday_4863.csv.gz  in=308,083,651 out=74,555,739 elapsed=385.8s

  [8020/13157] intraday_4862.csv.gz  in=308,095,262 out=74,555,739 elapsed=385.8s

  [8021/13157] intraday_4861.csv.gz  in=308,107,576 out=74,555,739 elapsed=385.8s

  [8022/13157] intraday_4864.csv.gz  in=308,118,918 out=74,555,739 elapsed=385.8s

  [8023/13157] intraday_4866.csv.gz  in=308,128,864 out=74,555,739 elapsed=385.8s

  [8024/13157] intraday_4867.csv.gz  in=308,139,594 out=74,555,739 elapsed=385.9s

  [8025/13157] intraday_4865.csv.gz  in=308,158,816 out=74,555,739 elapsed=385.9s

  [8026/13157] intraday_4868.csv.gz  in=308,170,826 out=74,555,739 elapsed=385.9s

  [8027/13157] intraday_4869.csv.gz  in=308,180,141 out=74,555,739 elapsed=385.9s

  [8028/13157] intraday_4871.csv.gz  in=308,190,901 out=74,555,739 elapsed=386.0s

  [8029/13157] intraday_4873.csv.gz  in=308,204,935 out=74,555,739 elapsed=386.0s

  [8030/13157] intraday_4872.csv.gz  in=308,220,406 out=74,555,739 elapsed=386.0s

  [8031/13157] intraday_4870.csv.gz  in=308,231,884 out=74,555,739 elapsed=386.0s

  [8032/13157] intraday_4875.csv.gz  in=308,241,766 out=74,555,739 elapsed=386.3s

  [8033/13157] intraday_4874.csv.gz  in=308,253,443 out=74,555,739 elapsed=386.3s

  [8034/13157] intraday_4876.csv.gz  in=308,264,154 out=74,555,739 elapsed=386.3s

  [8035/13157] intraday_4877.csv.gz  in=308,277,063 out=74,555,739 elapsed=386.3s

  [8036/13157] intraday_4878.csv.gz  in=308,289,869 out=74,555,739 elapsed=386.5s

  [8037/13157] intraday_4879.csv.gz  in=308,301,277 out=74,555,739 elapsed=386.5s

  [8038/13157] intraday_4881.csv.gz  in=308,312,442 out=74,555,739 elapsed=386.5s

  [8039/13157] intraday_4880.csv.gz  in=308,323,276 out=74,555,739 elapsed=386.5s

  [8040/13157] intraday_4882.csv.gz  in=308,337,761 out=74,555,739 elapsed=386.5s

  [8041/13157] intraday_4884.csv.gz  in=308,350,856 out=74,555,739 elapsed=386.6s

  [8042/13157] intraday_4885.csv.gz  in=308,363,254 out=74,555,739 elapsed=386.6s

  [8043/13157] intraday_4886.csv.gz  in=308,374,685 out=74,555,739 elapsed=386.6s

  [8044/13157] intraday_4883.csv.gz  in=308,389,483 out=74,555,739 elapsed=386.6s

  [8045/13157] intraday_4887.csv.gz  in=308,400,662 out=74,555,739 elapsed=386.6s

  [8046/13157] intraday_4889.csv.gz  in=308,412,947 out=74,555,739 elapsed=386.6s

  [8047/13157] intraday_4888.csv.gz  in=308,424,210 out=74,555,739 elapsed=386.6s

  [8048/13157] intraday_4890.csv.gz  in=308,435,772 out=74,555,739 elapsed=386.6s

  [8049/13157] intraday_4891.csv.gz  in=308,449,126 out=74,555,739 elapsed=386.8s

  [8050/13157] intraday_4892.csv.gz  in=308,459,827 out=74,555,739 elapsed=386.8s

  [8051/13157] intraday_4895.csv.gz  in=308,473,315 out=74,555,739 elapsed=386.8s

  [8052/13157] intraday_4894.csv.gz  in=308,483,784 out=74,555,739 elapsed=386.8s

  [8053/13157] intraday_4893.csv.gz  in=308,495,294 out=74,555,739 elapsed=386.8s

  [8054/13157] intraday_4896.csv.gz  in=308,506,713 out=74,555,739 elapsed=386.9s

  [8055/13157] intraday_4897.csv.gz  in=308,518,846 out=74,555,739 elapsed=386.9s

  [8056/13157] intraday_4899.csv.gz  in=308,529,526 out=74,555,739 elapsed=386.9s

  [8057/13157] intraday_4898.csv.gz  in=308,540,176 out=74,555,739 elapsed=386.9s

  [8058/13157] intraday_4900.csv.gz  in=308,551,745 out=74,555,739 elapsed=387.1s

  [8059/13157] intraday_4903.csv.gz  in=308,562,658 out=74,555,739 elapsed=387.1s

  [8060/13157] intraday_4902.csv.gz  in=308,575,591 out=74,555,739 elapsed=387.1s

  [8061/13157] intraday_4901.csv.gz  in=308,591,340 out=74,555,739 elapsed=387.1s

  [8062/13157] intraday_4905.csv.gz  in=308,602,682 out=74,555,739 elapsed=387.1s

  [8063/13157] intraday_4904.csv.gz  in=308,613,959 out=74,555,739 elapsed=387.1s

  [8064/13157] intraday_4906.csv.gz  in=308,628,240 out=74,555,739 elapsed=387.1s

  [8065/13157] intraday_4907.csv.gz  in=308,644,045 out=74,555,739 elapsed=387.2s

  [8066/13157] intraday_4908.csv.gz  in=308,655,337 out=74,555,739 elapsed=387.2s

  [8067/13157] intraday_4911.csv.gz  in=308,669,655 out=74,555,739 elapsed=387.2s

  [8068/13157] intraday_4910.csv.gz  in=308,683,893 out=74,555,739 elapsed=387.2s

  [8069/13157] intraday_4909.csv.gz  in=308,698,198 out=74,555,739 elapsed=387.2s

  [8070/13157] intraday_4912.csv.gz  in=308,710,858 out=74,555,739 elapsed=387.2s

  [8071/13157] intraday_4915.csv.gz  in=308,720,712 out=74,555,739 elapsed=387.3s

  [8072/13157] intraday_4913.csv.gz  in=308,732,624 out=74,555,739 elapsed=387.4s

  [8073/13157] intraday_4916.csv.gz  in=308,745,632 out=74,555,739 elapsed=387.4s

  [8074/13157] intraday_4914.csv.gz  in=308,757,931 out=74,555,739 elapsed=387.4s

  [8075/13157] intraday_4917.csv.gz  in=308,768,571 out=74,555,739 elapsed=387.4s

  [8076/13157] intraday_4918.csv.gz  in=308,780,344 out=74,555,739 elapsed=387.4s

  [8077/13157] intraday_4919.csv.gz  in=308,793,652 out=74,555,739 elapsed=387.4s

  [8078/13157] intraday_4920.csv.gz  in=308,806,380 out=74,555,739 elapsed=387.4s

  [8079/13157] intraday_4921.csv.gz  in=308,822,488 out=74,555,739 elapsed=387.4s

  [8080/13157] intraday_4922.csv.gz  in=308,833,423 out=74,555,739 elapsed=387.5s

  [8081/13157] intraday_4925.csv.gz  in=308,845,422 out=74,555,739 elapsed=387.6s

  [8082/13157] intraday_4923.csv.gz  in=308,860,898 out=74,555,739 elapsed=387.6s

  [8083/13157] intraday_4924.csv.gz  in=308,872,015 out=74,555,739 elapsed=387.6s

  [8084/13157] intraday_4926.csv.gz  in=308,885,541 out=74,555,739 elapsed=387.6s

  [8085/13157] intraday_4930.csv.gz  in=308,899,014 out=74,555,739 elapsed=387.7s

  [8086/13157] intraday_4929.csv.gz  in=308,912,938 out=74,555,739 elapsed=387.7s

  [8087/13157] intraday_4927.csv.gz  in=308,927,021 out=74,555,739 elapsed=387.7s

  [8088/13157] intraday_4928.csv.gz  in=308,938,918 out=74,555,739 elapsed=387.7s

  [8089/13157] intraday_4931.csv.gz  in=308,952,202 out=74,555,739 elapsed=387.8s

  [8090/13157] intraday_4934.csv.gz  in=308,963,775 out=74,555,739 elapsed=387.8s

  [8091/13157] intraday_4933.csv.gz  in=308,978,387 out=74,555,739 elapsed=387.8s

  [8092/13157] intraday_4932.csv.gz  in=309,000,249 out=74,555,739 elapsed=387.8s

  [8093/13157] intraday_4936.csv.gz  in=309,011,902 out=74,555,739 elapsed=387.9s

  [8094/13157] intraday_4937.csv.gz  in=309,023,651 out=74,555,739 elapsed=387.9s

  [8095/13157] intraday_4935.csv.gz  in=309,039,221 out=74,555,739 elapsed=387.9s

  [8096/13157] intraday_4938.csv.gz  in=309,049,686 out=74,555,739 elapsed=387.9s

  [8097/13157] intraday_4939.csv.gz  in=309,062,661 out=74,555,739 elapsed=388.0s

  [8098/13157] intraday_4940.csv.gz  in=309,073,409 out=74,555,739 elapsed=388.0s

  [8099/13157] intraday_4942.csv.gz  in=309,086,116 out=74,555,739 elapsed=388.0s

  [8100/13157] intraday_4941.csv.gz  in=309,099,616 out=74,555,739 elapsed=388.0s

  [8101/13157] intraday_4944.csv.gz  in=309,110,947 out=74,555,739 elapsed=388.0s

  [8102/13157] intraday_4945.csv.gz  in=309,123,264 out=74,555,739 elapsed=388.0s

  [8103/13157] intraday_4943.csv.gz  in=309,139,755 out=74,555,739 elapsed=388.0s

  [8104/13157] intraday_4946.csv.gz  in=309,164,768 out=74,555,739 elapsed=388.0s

  [8105/13157] intraday_4948.csv.gz  in=309,175,661 out=74,555,739 elapsed=388.1s

  [8106/13157] intraday_4949.csv.gz  in=309,189,407 out=74,555,739 elapsed=388.1s

  [8107/13157] intraday_4947.csv.gz  in=309,203,573 out=74,555,739 elapsed=388.1s

  [8108/13157] intraday_4950.csv.gz  in=309,218,665 out=74,555,739 elapsed=388.1s

  [8109/13157] intraday_4951.csv.gz  in=309,231,792 out=74,555,739 elapsed=388.2s

  [8110/13157] intraday_4953.csv.gz  in=309,242,412 out=74,555,739 elapsed=388.2s

  [8111/13157] intraday_4952.csv.gz  in=309,256,677 out=74,555,739 elapsed=388.2s

  [8112/13157] intraday_4954.csv.gz  in=309,268,399 out=74,555,739 elapsed=388.2s

  [8113/13157] intraday_4957.csv.gz  in=309,277,954 out=74,555,739 elapsed=388.3s

  [8114/13157] intraday_4955.csv.gz  in=309,291,250 out=74,555,739 elapsed=388.3s

  [8115/13157] intraday_4958.csv.gz  in=309,300,396 out=74,555,739 elapsed=388.3s

  [8116/13157] intraday_4956.csv.gz  in=309,313,631 out=74,555,739 elapsed=388.3s

  [8117/13157] intraday_4960.csv.gz  in=309,320,310 out=74,555,739 elapsed=388.3s

  [8118/13157] intraday_4959.csv.gz  in=309,330,709 out=74,555,739 elapsed=388.3s

  [8119/13157] intraday_4962.csv.gz  in=309,500,598 out=74,597,612 elapsed=389.1s

  [8120/13157] intraday_4964.csv.gz  in=309,673,293 out=74,633,047 elapsed=389.2s

  [8121/13157] intraday_4963.csv.gz  in=309,836,853 out=74,677,491 elapsed=389.3s

  [8122/13157] intraday_4961.csv.gz  in=310,039,853 out=74,729,881 elapsed=389.4s

  [8123/13157] intraday_4965.csv.gz  in=310,226,732 out=74,774,605 elapsed=389.9s

  [8124/13157] intraday_4968.csv.gz  in=310,381,655 out=74,814,764 elapsed=390.0s

  [8125/13157] intraday_4966.csv.gz  in=310,587,983 out=74,870,744 elapsed=390.0s

  [8126/13157] intraday_4967.csv.gz  in=310,773,789 out=74,916,046 elapsed=390.0s

  [8127/13157] intraday_4969.csv.gz  in=310,953,932 out=74,961,251 elapsed=390.3s

  [8128/13157] intraday_4972.csv.gz  in=311,111,621 out=75,000,961 elapsed=391.0s

  [8129/13157] intraday_4971.csv.gz  in=311,288,230 out=75,047,466 elapsed=391.2s

  [8130/13157] intraday_4970.csv.gz  in=311,460,467 out=75,090,843 elapsed=391.2s

  [8131/13157] intraday_4973.csv.gz  in=311,618,584 out=75,133,580 elapsed=391.3s

  [8132/13157] intraday_4974.csv.gz  in=311,766,430 out=75,169,478 elapsed=391.4s

  [8133/13157] intraday_4975.csv.gz  in=311,899,002 out=75,202,891 elapsed=391.5s

  [8134/13157] intraday_4976.csv.gz  in=312,017,258 out=75,230,936 elapsed=391.5s

  [8135/13157] intraday_4977.csv.gz  in=312,208,049 out=75,279,349 elapsed=391.6s

  [8136/13157] intraday_4978.csv.gz  in=312,380,102 out=75,320,261 elapsed=391.6s

  [8137/13157] intraday_4979.csv.gz  in=312,511,485 out=75,355,447 elapsed=392.3s

  [8138/13157] intraday_4981.csv.gz  in=312,658,607 out=75,393,991 elapsed=392.3s

  [8139/13157] intraday_4980.csv.gz  in=312,822,491 out=75,430,973 elapsed=392.4s

  [8140/13157] intraday_4982.csv.gz  in=312,998,842 out=75,475,930 elapsed=392.4s

  [8141/13157] intraday_4983.csv.gz  in=313,137,954 out=75,508,310 elapsed=392.6s

  [8142/13157] intraday_4984.csv.gz  in=313,289,388 out=75,549,291 elapsed=392.8s

  [8143/13157] intraday_4986.csv.gz  in=313,436,164 out=75,584,672 elapsed=393.0s

  [8144/13157] intraday_4985.csv.gz  in=313,597,911 out=75,626,787 elapsed=393.0s

  [8145/13157] intraday_4988.csv.gz  in=313,743,905 out=75,663,299 elapsed=393.3s

  [8146/13157] intraday_4987.csv.gz  in=313,904,405 out=75,703,584 elapsed=393.3s

  [8147/13157] intraday_4990.csv.gz  in=314,096,558 out=75,755,595 elapsed=394.9s

  [8148/13157] intraday_4989.csv.gz  in=314,279,030 out=75,804,237 elapsed=394.9s

  [8149/13157] intraday_4992.csv.gz  in=314,430,655 out=75,840,127 elapsed=395.0s

  [8150/13157] intraday_4991.csv.gz  in=314,624,903 out=75,891,933 elapsed=395.1s

  [8151/13157] intraday_4993.csv.gz  in=314,776,401 out=75,928,694 elapsed=395.3s

  [8152/13157] intraday_4994.csv.gz  in=314,925,234 out=75,967,513 elapsed=395.3s

  [8153/13157] intraday_4996.csv.gz  in=315,066,120 out=76,003,589 elapsed=395.3s

  [8154/13157] intraday_4995.csv.gz  in=315,244,891 out=76,050,206 elapsed=395.4s

  [8155/13157] intraday_4999.csv.gz  in=315,372,281 out=76,082,279 elapsed=395.7s

  [8156/13157] intraday_5000.csv.gz  in=315,511,843 out=76,117,929 elapsed=396.2s

  [8157/13157] intraday_4998.csv.gz  in=315,665,987 out=76,157,924 elapsed=396.3s

  [8158/13157] intraday_4997.csv.gz  in=315,823,940 out=76,198,831 elapsed=396.3s

  [8159/13157] intraday_5001.csv.gz  in=315,985,121 out=76,241,438 elapsed=397.1s

  [8160/13157] intraday_5002.csv.gz  in=316,137,636 out=76,280,207 elapsed=397.6s

  [8161/13157] intraday_5003.csv.gz  in=316,294,586 out=76,320,005 elapsed=397.6s

  [8162/13157] intraday_5004.csv.gz  in=316,467,147 out=76,363,461 elapsed=397.7s

  [8163/13157] intraday_5005.csv.gz  in=316,633,080 out=76,406,732 elapsed=398.0s

  [8164/13157] intraday_5007.csv.gz  in=316,772,659 out=76,442,580 elapsed=398.4s

  [8165/13157] intraday_5008.csv.gz  in=316,916,899 out=76,480,781 elapsed=398.4s

  [8166/13157] intraday_5006.csv.gz  in=317,073,248 out=76,521,679 elapsed=398.4s

  [8167/13157] intraday_5009.csv.gz  in=317,232,967 out=76,561,907 elapsed=398.5s

  [8168/13157] intraday_5010.csv.gz  in=317,365,966 out=76,596,116 elapsed=398.9s

  [8169/13157] intraday_5013.csv.gz  in=317,497,115 out=76,628,207 elapsed=399.1s

  [8170/13157] intraday_5011.csv.gz  in=317,637,304 out=76,665,492 elapsed=399.1s

  [8171/13157] intraday_5012.csv.gz  in=317,840,343 out=76,712,773 elapsed=399.3s

  [8172/13157] intraday_5016.csv.gz  in=317,999,728 out=76,756,365 elapsed=399.4s

  [8173/13157] intraday_5014.csv.gz  in=318,155,422 out=76,798,005 elapsed=399.4s

  [8174/13157] intraday_5015.csv.gz  in=318,318,739 out=76,839,884 elapsed=399.4s

  [8175/13157] intraday_5017.csv.gz  in=318,461,155 out=76,878,683 elapsed=399.4s

  [8176/13157] intraday_5020.csv.gz  in=318,607,325 out=76,915,590 elapsed=399.8s

  [8177/13157] intraday_5018.csv.gz  in=318,759,552 out=76,958,715 elapsed=399.8s

  [8178/13157] intraday_5021.csv.gz  in=318,922,189 out=77,001,031 elapsed=399.8s

  [8179/13157] intraday_5019.csv.gz  in=319,095,920 out=77,046,482 elapsed=399.8s

  [8180/13157] intraday_5024.csv.gz  in=319,229,148 out=77,080,457 elapsed=400.3s

  [8181/13157] intraday_5023.csv.gz  in=319,366,735 out=77,112,810 elapsed=400.3s

  [8182/13157] intraday_5022.csv.gz  in=319,510,613 out=77,147,866 elapsed=400.3s

  [8183/13157] intraday_5025.csv.gz  in=319,702,281 out=77,199,413 elapsed=400.4s

  [8184/13157] intraday_5028.csv.gz  in=319,854,151 out=77,237,278 elapsed=400.8s

  [8185/13157] intraday_5027.csv.gz  in=320,025,194 out=77,280,966 elapsed=400.8s

  [8186/13157] intraday_5026.csv.gz  in=320,194,671 out=77,325,582 elapsed=400.8s

  [8187/13157] intraday_5029.csv.gz  in=320,344,933 out=77,357,572 elapsed=400.8s

  [8188/13157] intraday_5032.csv.gz  in=320,483,683 out=77,394,661 elapsed=401.5s

  [8189/13157] intraday_5030.csv.gz  in=320,635,310 out=77,434,070 elapsed=401.5s

  [8190/13157] intraday_5031.csv.gz  in=320,787,643 out=77,474,149 elapsed=401.5s

  [8191/13157] intraday_5033.csv.gz  in=320,958,660 out=77,516,787 elapsed=401.5s

  [8192/13157] intraday_5034.csv.gz  in=321,098,967 out=77,555,062 elapsed=402.1s

  [8193/13157] intraday_5036.csv.gz  in=321,242,081 out=77,592,203 elapsed=402.2s

  [8194/13157] intraday_5035.csv.gz  in=321,402,005 out=77,631,858 elapsed=402.2s

  [8195/13157] intraday_5037.csv.gz  in=321,558,608 out=77,671,624 elapsed=402.2s

  [8196/13157] intraday_5038.csv.gz  in=321,708,123 out=77,708,379 elapsed=402.6s

  [8197/13157] intraday_5040.csv.gz  in=321,830,265 out=77,739,557 elapsed=402.6s

  [8198/13157] intraday_5039.csv.gz  in=321,995,812 out=77,784,857 elapsed=402.6s

  [8199/13157] intraday_5041.csv.gz  in=322,142,309 out=77,824,078 elapsed=402.6s

  [8200/13157] intraday_5042.csv.gz  in=322,292,656 out=77,865,180 elapsed=403.4s

  [8201/13157] intraday_5045.csv.gz  in=322,455,822 out=77,906,572 elapsed=403.5s

  [8202/13157] intraday_5043.csv.gz  in=322,663,337 out=77,960,062 elapsed=403.5s

  [8203/13157] intraday_5044.csv.gz  in=322,842,859 out=78,007,711 elapsed=403.5s

  [8204/13157] intraday_5046.csv.gz  in=322,993,297 out=78,046,737 elapsed=404.0s

  [8205/13157] intraday_5047.csv.gz  in=323,138,951 out=78,083,761 elapsed=404.0s

  [8206/13157] intraday_5048.csv.gz  in=323,317,378 out=78,128,817 elapsed=404.0s

  [8207/13157] intraday_5049.csv.gz  in=323,527,658 out=78,184,649 elapsed=404.0s

  [8208/13157] intraday_5050.csv.gz  in=323,670,444 out=78,221,611 elapsed=404.5s

  [8209/13157] intraday_5051.csv.gz  in=323,843,623 out=78,266,500 elapsed=404.5s

  [8210/13157] intraday_5052.csv.gz  in=324,017,792 out=78,307,436 elapsed=404.5s

  [8211/13157] intraday_5053.csv.gz  in=324,197,747 out=78,352,519 elapsed=404.6s

  [8212/13157] intraday_5057.csv.gz  in=324,336,653 out=78,385,612 elapsed=404.9s

  [8213/13157] intraday_5055.csv.gz  in=324,490,333 out=78,424,846 elapsed=404.9s

  [8214/13157] intraday_5056.csv.gz  in=324,650,918 out=78,467,085 elapsed=405.0s

  [8215/13157] intraday_5054.csv.gz  in=324,822,252 out=78,512,052 elapsed=405.0s

  [8216/13157] intraday_5059.csv.gz  in=324,972,867 out=78,551,814 elapsed=405.8s

  [8217/13157] intraday_5058.csv.gz  in=325,164,037 out=78,604,239 elapsed=405.8s

  [8218/13157] intraday_5060.csv.gz  in=325,329,116 out=78,645,787 elapsed=405.8s

  [8219/13157] intraday_5061.csv.gz  in=325,499,928 out=78,690,083 elapsed=405.9s

  [8220/13157] intraday_5063.csv.gz  in=325,641,259 out=78,726,326 elapsed=406.5s

  [8221/13157] intraday_5062.csv.gz  in=325,820,864 out=78,777,049 elapsed=406.6s

  [8222/13157] intraday_5064.csv.gz  in=325,981,319 out=78,818,497 elapsed=406.6s

  [8223/13157] intraday_5065.csv.gz  in=326,179,754 out=78,874,495 elapsed=406.6s

  [8224/13157] intraday_5066.csv.gz  in=326,321,521 out=78,909,056 elapsed=407.5s

  [8225/13157] intraday_5067.csv.gz  in=326,471,482 out=78,948,298 elapsed=407.5s

  [8226/13157] intraday_5069.csv.gz  in=326,648,188 out=78,992,224 elapsed=407.6s

  [8227/13157] intraday_5068.csv.gz  in=326,848,871 out=79,042,083 elapsed=407.6s

  [8228/13157] intraday_5070.csv.gz  in=326,994,521 out=79,077,382 elapsed=407.9s

  [8229/13157] intraday_5071.csv.gz  in=327,161,519 out=79,119,257 elapsed=407.9s

  [8230/13157] intraday_5073.csv.gz  in=327,323,143 out=79,161,928 elapsed=408.0s

  [8231/13157] intraday_5072.csv.gz  in=327,496,834 out=79,206,021 elapsed=408.0s

  [8232/13157] intraday_5074.csv.gz  in=327,714,907 out=79,261,919 elapsed=408.6s

  [8233/13157] intraday_5075.csv.gz  in=327,885,929 out=79,306,710 elapsed=408.7s

  [8234/13157] intraday_5076.csv.gz  in=328,076,483 out=79,356,472 elapsed=408.8s

  [8235/13157] intraday_5077.csv.gz  in=328,278,952 out=79,408,906 elapsed=408.8s

  [8236/13157] intraday_5078.csv.gz  in=328,448,369 out=79,452,407 elapsed=409.2s

  [8237/13157] intraday_5080.csv.gz  in=328,591,940 out=79,490,100 elapsed=409.7s

  [8238/13157] intraday_5081.csv.gz  in=328,748,442 out=79,529,431 elapsed=409.7s

  [8239/13157] intraday_5079.csv.gz  in=328,904,743 out=79,567,264 elapsed=409.8s

  [8240/13157] intraday_5082.csv.gz  in=329,047,243 out=79,602,157 elapsed=409.8s

  [8241/13157] intraday_5083.csv.gz  in=329,206,486 out=79,643,557 elapsed=410.2s

  [8242/13157] intraday_5084.csv.gz  in=329,372,189 out=79,685,746 elapsed=410.2s

  [8243/13157] intraday_5085.csv.gz  in=329,547,084 out=79,731,483 elapsed=410.3s

  [8244/13157] intraday_5086.csv.gz  in=329,736,274 out=79,782,901 elapsed=410.5s

  [8245/13157] intraday_5088.csv.gz  in=329,893,434 out=79,821,010 elapsed=411.1s

  [8246/13157] intraday_5087.csv.gz  in=330,050,936 out=79,860,716 elapsed=411.1s

  [8247/13157] intraday_5089.csv.gz  in=330,221,943 out=79,905,000 elapsed=411.2s

  [8248/13157] intraday_5090.csv.gz  in=330,381,408 out=79,946,056 elapsed=411.2s

  [8249/13157] intraday_5091.csv.gz  in=330,541,813 out=79,986,727 elapsed=411.7s

  [8250/13157] intraday_5092.csv.gz  in=330,727,402 out=80,034,594 elapsed=411.8s

  [8251/13157] intraday_5094.csv.gz  in=330,899,989 out=80,078,592 elapsed=411.8s

  [8252/13157] intraday_5093.csv.gz  in=331,063,070 out=80,121,936 elapsed=411.8s

  [8253/13157] intraday_5095.csv.gz  in=331,226,571 out=80,162,962 elapsed=412.0s

  [8254/13157] intraday_5096.csv.gz  in=331,361,273 out=80,198,553 elapsed=412.1s

  [8255/13157] intraday_5097.csv.gz  in=331,508,788 out=80,240,638 elapsed=412.1s

  [8256/13157] intraday_5098.csv.gz  in=331,656,478 out=80,277,687 elapsed=412.1s

  [8257/13157] intraday_5099.csv.gz  in=331,836,432 out=80,325,822 elapsed=412.4s

  [8258/13157] intraday_5100.csv.gz  in=331,945,207 out=80,351,698 elapsed=412.5s

  [8259/13157] intraday_5102.csv.gz  in=332,057,996 out=80,381,254 elapsed=412.5s

  [8260/13157] intraday_5101.csv.gz  in=332,171,957 out=80,412,650 elapsed=412.5s

  [8261/13157] intraday_5103.csv.gz  in=332,187,335 out=80,428,028 elapsed=412.5s

  [8262/13157] intraday_5107.csv.gz  in=332,200,727 out=80,441,420 elapsed=412.6s

  [8263/13157] intraday_5106.csv.gz  in=332,211,900 out=80,452,593 elapsed=412.6s

  [8264/13157] intraday_5104.csv.gz  in=332,224,220 out=80,464,913 elapsed=412.6s

  [8265/13157] intraday_5105.csv.gz  in=332,238,085 out=80,478,778 elapsed=412.6s

  [8266/13157] intraday_5108.csv.gz  in=332,254,751 out=80,495,444 elapsed=412.7s

  [8267/13157] intraday_5109.csv.gz  in=332,268,451 out=80,509,144 elapsed=412.7s

  [8268/13157] intraday_5110.csv.gz  in=332,280,092 out=80,520,785 elapsed=412.7s

  [8269/13157] intraday_5111.csv.gz  in=332,293,990 out=80,534,683 elapsed=412.7s

  [8270/13157] intraday_5112.csv.gz  in=332,307,332 out=80,548,025 elapsed=412.9s

  [8271/13157] intraday_5114.csv.gz  in=332,320,469 out=80,561,162 elapsed=412.9s

  [8272/13157] intraday_5113.csv.gz  in=332,334,401 out=80,575,094 elapsed=412.9s

  [8273/13157] intraday_5115.csv.gz  in=332,347,384 out=80,588,077 elapsed=412.9s

  [8274/13157] intraday_5117.csv.gz  in=332,357,483 out=80,598,176 elapsed=413.0s

  [8275/13157] intraday_5119.csv.gz  in=332,377,715 out=80,612,771 elapsed=413.0s

  [8276/13157] intraday_5116.csv.gz  in=332,388,731 out=80,623,787 elapsed=413.0s

  [8277/13157] intraday_5118.csv.gz  in=332,398,139 out=80,633,195 elapsed=413.0s

  [8278/13157] intraday_5120.csv.gz  in=332,411,420 out=80,646,476 elapsed=413.2s

  [8279/13157] intraday_5121.csv.gz  in=332,424,031 out=80,659,087 elapsed=413.2s

  [8280/13157] intraday_5122.csv.gz  in=332,435,921 out=80,670,977 elapsed=413.2s

  [8281/13157] intraday_5123.csv.gz  in=332,457,344 out=80,683,460 elapsed=413.2s

  [8282/13157] intraday_5127.csv.gz  in=332,470,463 out=80,696,579 elapsed=413.6s

  [8283/13157] intraday_5126.csv.gz  in=332,482,551 out=80,708,667 elapsed=413.6s

  [8284/13157] intraday_5125.csv.gz  in=332,493,639 out=80,719,755 elapsed=413.6s

  [8285/13157] intraday_5124.csv.gz  in=332,507,490 out=80,733,606 elapsed=413.6s

  [8286/13157] intraday_5128.csv.gz  in=332,518,790 out=80,744,906 elapsed=413.7s

  [8287/13157] intraday_5129.csv.gz  in=332,531,113 out=80,757,229 elapsed=413.7s

  [8288/13157] intraday_5130.csv.gz  in=332,543,138 out=80,768,768 elapsed=413.7s

  [8289/13157] intraday_5134.csv.gz  in=332,554,052 out=80,779,682 elapsed=413.8s

  [8290/13157] intraday_5131.csv.gz  in=332,567,960 out=80,793,590 elapsed=413.8s

  [8291/13157] intraday_5133.csv.gz  in=332,584,028 out=80,809,658 elapsed=413.8s

  [8292/13157] intraday_5132.csv.gz  in=332,599,036 out=80,824,666 elapsed=413.8s

  [8293/13157] intraday_5136.csv.gz  in=332,611,169 out=80,836,799 elapsed=413.8s

  [8294/13157] intraday_5135.csv.gz  in=332,623,505 out=80,849,135 elapsed=413.8s

  [8295/13157] intraday_5137.csv.gz  in=332,638,775 out=80,864,405 elapsed=413.8s

  [8296/13157] intraday_5138.csv.gz  in=332,649,666 out=80,875,296 elapsed=413.8s

  [8297/13157] intraday_5140.csv.gz  in=332,662,567 out=80,887,966 elapsed=414.0s

  [8298/13157] intraday_5139.csv.gz  in=332,675,301 out=80,900,700 elapsed=414.0s

  [8299/13157] intraday_5142.csv.gz  in=332,687,944 out=80,912,595 elapsed=414.0s

  [8300/13157] intraday_5141.csv.gz  in=332,710,767 out=80,924,077 elapsed=414.0s

  [8301/13157] intraday_5143.csv.gz  in=332,723,650 out=80,936,960 elapsed=414.2s

  [8302/13157] intraday_5146.csv.gz  in=332,736,461 out=80,949,771 elapsed=414.2s

  [8303/13157] intraday_5144.csv.gz  in=332,748,407 out=80,961,717 elapsed=414.2s

  [8304/13157] intraday_5145.csv.gz  in=332,761,693 out=80,975,003 elapsed=414.2s

  [8305/13157] intraday_5148.csv.gz  in=332,774,738 out=80,988,048 elapsed=414.4s

  [8306/13157] intraday_5147.csv.gz  in=332,788,311 out=81,001,621 elapsed=414.5s

  [8307/13157] intraday_5149.csv.gz  in=332,800,110 out=81,013,420 elapsed=414.5s

  [8308/13157] intraday_5150.csv.gz  in=332,812,124 out=81,025,434 elapsed=414.5s

  [8309/13157] intraday_5151.csv.gz  in=332,825,885 out=81,039,195 elapsed=414.5s

  [8310/13157] intraday_5153.csv.gz  in=332,837,303 out=81,050,613 elapsed=414.6s

  [8311/13157] intraday_5155.csv.gz  in=332,847,943 out=81,060,465 elapsed=414.6s

  [8312/13157] intraday_5152.csv.gz  in=332,858,845 out=81,071,367 elapsed=414.6s

  [8313/13157] intraday_5154.csv.gz  in=332,872,832 out=81,085,354 elapsed=414.6s

  [8314/13157] intraday_5156.csv.gz  in=332,884,923 out=81,097,325 elapsed=414.7s

  [8315/13157] intraday_5158.csv.gz  in=332,898,681 out=81,111,083 elapsed=414.7s

  [8316/13157] intraday_5157.csv.gz  in=332,912,069 out=81,124,471 elapsed=414.7s

  [8317/13157] intraday_5162.csv.gz  in=332,924,000 out=81,136,402 elapsed=414.7s

  [8318/13157] intraday_5159.csv.gz  in=332,937,405 out=81,149,807 elapsed=414.8s

  [8319/13157] intraday_5160.csv.gz  in=332,949,552 out=81,161,954 elapsed=414.8s

  [8320/13157] intraday_5161.csv.gz  in=332,963,169 out=81,175,571 elapsed=414.8s

  [8321/13157] intraday_5163.csv.gz  in=332,976,131 out=81,188,533 elapsed=415.0s

  [8322/13157] intraday_5164.csv.gz  in=332,987,553 out=81,199,955 elapsed=415.0s

  [8323/13157] intraday_5166.csv.gz  in=332,998,737 out=81,211,139 elapsed=415.1s

  [8324/13157] intraday_5165.csv.gz  in=333,009,471 out=81,221,873 elapsed=415.1s

  [8325/13157] intraday_5168.csv.gz  in=333,022,085 out=81,234,487 elapsed=415.1s

  [8326/13157] intraday_5167.csv.gz  in=333,038,544 out=81,250,946 elapsed=415.1s

  [8327/13157] intraday_5171.csv.gz  in=333,048,437 out=81,260,839 elapsed=415.2s

  [8328/13157] intraday_5169.csv.gz  in=333,062,209 out=81,274,611 elapsed=415.3s

  [8329/13157] intraday_5172.csv.gz  in=333,073,844 out=81,286,246 elapsed=415.4s

  [8330/13157] intraday_5173.csv.gz  in=333,086,031 out=81,298,433 elapsed=415.4s

  [8331/13157] intraday_5170.csv.gz  in=333,097,969 out=81,310,371 elapsed=415.4s

  [8332/13157] intraday_5175.csv.gz  in=333,111,465 out=81,323,867 elapsed=415.5s

  [8333/13157] intraday_5174.csv.gz  in=333,123,943 out=81,336,345 elapsed=415.5s

  [8334/13157] intraday_5176.csv.gz  in=333,136,749 out=81,349,151 elapsed=415.5s

  [8335/13157] intraday_5177.csv.gz  in=333,149,844 out=81,362,246 elapsed=415.5s

  [8336/13157] intraday_5180.csv.gz  in=333,161,533 out=81,373,935 elapsed=415.5s

  [8337/13157] intraday_5179.csv.gz  in=333,174,659 out=81,387,061 elapsed=415.5s

  [8338/13157] intraday_5181.csv.gz  in=333,187,599 out=81,400,001 elapsed=415.5s

  [8339/13157] intraday_5178.csv.gz  in=333,202,384 out=81,411,390 elapsed=415.5s

  [8340/13157] intraday_5182.csv.gz  in=333,212,541 out=81,421,547 elapsed=415.6s

  [8341/13157] intraday_5183.csv.gz  in=333,224,634 out=81,433,640 elapsed=415.6s

  [8342/13157] intraday_5184.csv.gz  in=333,237,217 out=81,446,223 elapsed=415.6s

  [8343/13157] intraday_5185.csv.gz  in=333,252,526 out=81,461,532 elapsed=415.6s

  [8344/13157] intraday_5186.csv.gz  in=333,266,267 out=81,475,273 elapsed=415.6s

  [8345/13157] intraday_5187.csv.gz  in=333,278,704 out=81,487,710 elapsed=415.8s

  [8346/13157] intraday_5190.csv.gz  in=333,292,525 out=81,501,531 elapsed=415.8s

  [8347/13157] intraday_5189.csv.gz  in=333,303,679 out=81,512,685 elapsed=415.8s

  [8348/13157] intraday_5188.csv.gz  in=333,315,242 out=81,524,006 elapsed=415.8s

  [8349/13157] intraday_5192.csv.gz  in=333,326,664 out=81,535,428 elapsed=415.9s

  [8350/13157] intraday_5194.csv.gz  in=333,340,300 out=81,549,064 elapsed=415.9s

  [8351/13157] intraday_5193.csv.gz  in=333,354,055 out=81,562,819 elapsed=415.9s

  [8352/13157] intraday_5191.csv.gz  in=333,371,457 out=81,580,221 elapsed=415.9s

  [8353/13157] intraday_5195.csv.gz  in=333,385,879 out=81,594,643 elapsed=415.9s

  [8354/13157] intraday_5196.csv.gz  in=333,399,270 out=81,608,034 elapsed=416.0s

  [8355/13157] intraday_5197.csv.gz  in=333,415,783 out=81,621,455 elapsed=416.0s

  [8356/13157] intraday_5199.csv.gz  in=333,426,093 out=81,631,765 elapsed=416.0s

  [8357/13157] intraday_5201.csv.gz  in=333,439,089 out=81,644,761 elapsed=416.0s

  [8358/13157] intraday_5198.csv.gz  in=333,451,997 out=81,657,669 elapsed=416.0s

  [8359/13157] intraday_5200.csv.gz  in=333,466,150 out=81,671,822 elapsed=416.0s

  [8360/13157] intraday_5202.csv.gz  in=333,478,955 out=81,684,627 elapsed=416.1s

  [8361/13157] intraday_5203.csv.gz  in=333,492,120 out=81,697,792 elapsed=416.1s

  [8362/13157] intraday_5204.csv.gz  in=333,507,321 out=81,712,993 elapsed=416.1s

  [8363/13157] intraday_5205.csv.gz  in=333,518,068 out=81,723,740 elapsed=416.1s

  [8364/13157] intraday_5206.csv.gz  in=333,531,180 out=81,736,852 elapsed=416.1s

  [8365/13157] intraday_5209.csv.gz  in=333,543,424 out=81,749,096 elapsed=416.5s

  [8366/13157] intraday_5207.csv.gz  in=333,560,775 out=81,765,215 elapsed=416.5s

  [8367/13157] intraday_5208.csv.gz  in=333,570,863 out=81,775,303 elapsed=416.5s

  [8368/13157] intraday_5210.csv.gz  in=333,586,169 out=81,790,331 elapsed=416.5s

  [8369/13157] intraday_5211.csv.gz  in=333,600,234 out=81,804,396 elapsed=416.5s

  [8370/13157] intraday_5213.csv.gz  in=333,612,921 out=81,817,083 elapsed=416.5s

  [8371/13157] intraday_5212.csv.gz  in=333,624,281 out=81,828,443 elapsed=416.5s

  [8372/13157] intraday_5214.csv.gz  in=333,637,369 out=81,841,531 elapsed=416.6s

  [8373/13157] intraday_5215.csv.gz  in=333,650,105 out=81,854,267 elapsed=416.6s

  [8374/13157] intraday_5217.csv.gz  in=333,663,028 out=81,867,190 elapsed=416.7s

  [8375/13157] intraday_5218.csv.gz  in=333,677,443 out=81,881,605 elapsed=416.7s

  [8376/13157] intraday_5216.csv.gz  in=333,694,498 out=81,897,966 elapsed=416.7s

  [8377/13157] intraday_5220.csv.gz  in=333,708,705 out=81,912,173 elapsed=416.7s

  [8378/13157] intraday_5219.csv.gz  in=333,724,299 out=81,927,767 elapsed=416.7s

  [8379/13157] intraday_5222.csv.gz  in=333,735,707 out=81,939,175 elapsed=416.8s

  [8380/13157] intraday_5224.csv.gz  in=333,746,515 out=81,949,983 elapsed=416.9s

  [8381/13157] intraday_5223.csv.gz  in=333,758,722 out=81,962,050 elapsed=416.9s

  [8382/13157] intraday_5221.csv.gz  in=333,770,540 out=81,973,868 elapsed=416.9s

  [8383/13157] intraday_5225.csv.gz  in=333,783,244 out=81,986,572 elapsed=416.9s

  [8384/13157] intraday_5226.csv.gz  in=333,796,087 out=81,999,415 elapsed=416.9s

  [8385/13157] intraday_5228.csv.gz  in=333,811,674 out=82,015,002 elapsed=416.9s

  [8386/13157] intraday_5227.csv.gz  in=333,831,325 out=82,029,396 elapsed=416.9s

  [8387/13157] intraday_5230.csv.gz  in=333,843,150 out=82,041,221 elapsed=416.9s

  [8388/13157] intraday_5229.csv.gz  in=333,854,802 out=82,052,873 elapsed=417.0s

  [8389/13157] intraday_5232.csv.gz  in=333,866,834 out=82,064,905 elapsed=417.0s

  [8390/13157] intraday_5231.csv.gz  in=333,880,577 out=82,078,648 elapsed=417.0s

  [8391/13157] intraday_5235.csv.gz  in=333,893,836 out=82,091,907 elapsed=417.0s

  [8392/13157] intraday_5233.csv.gz  in=333,906,088 out=82,104,159 elapsed=417.0s

  [8393/13157] intraday_5236.csv.gz  in=333,920,195 out=82,117,894 elapsed=417.0s

  [8394/13157] intraday_5234.csv.gz  in=333,935,609 out=82,133,308 elapsed=417.0s

  [8395/13157] intraday_5239.csv.gz  in=333,949,199 out=82,146,898 elapsed=417.1s

  [8396/13157] intraday_5237.csv.gz  in=333,961,570 out=82,159,269 elapsed=417.1s

  [8397/13157] intraday_5238.csv.gz  in=333,974,893 out=82,171,072 elapsed=417.1s

  [8398/13157] intraday_5240.csv.gz  in=333,986,816 out=82,182,642 elapsed=417.1s

  [8399/13157] intraday_5242.csv.gz  in=333,995,654 out=82,191,480 elapsed=417.1s

  [8400/13157] intraday_5243.csv.gz  in=334,007,437 out=82,203,263 elapsed=417.2s

  [8401/13157] intraday_5241.csv.gz  in=334,021,922 out=82,217,099 elapsed=417.2s

  [8402/13157] intraday_5244.csv.gz  in=334,030,925 out=82,226,102 elapsed=417.2s

  [8403/13157] intraday_5245.csv.gz  in=334,047,160 out=82,242,337 elapsed=417.2s

  [8404/13157] intraday_5248.csv.gz  in=334,058,413 out=82,253,590 elapsed=417.2s

  [8405/13157] intraday_5246.csv.gz  in=334,071,582 out=82,266,759 elapsed=417.3s

  [8406/13157] intraday_5249.csv.gz  in=334,084,910 out=82,280,087 elapsed=417.3s

  [8407/13157] intraday_5247.csv.gz  in=334,099,568 out=82,294,745 elapsed=417.3s

  [8408/13157] intraday_5250.csv.gz  in=334,116,603 out=82,311,780 elapsed=417.4s

  [8409/13157] intraday_5251.csv.gz  in=334,130,746 out=82,325,923 elapsed=417.4s

  [8410/13157] intraday_5252.csv.gz  in=334,142,868 out=82,338,045 elapsed=417.4s

  [8411/13157] intraday_5253.csv.gz  in=334,157,205 out=82,352,382 elapsed=417.4s

  [8412/13157] intraday_5255.csv.gz  in=334,170,998 out=82,366,175 elapsed=417.4s

  [8413/13157] intraday_5254.csv.gz  in=334,184,782 out=82,379,959 elapsed=417.4s

  [8414/13157] intraday_5256.csv.gz  in=334,198,581 out=82,393,758 elapsed=417.4s

  [8415/13157] intraday_5257.csv.gz  in=334,211,790 out=82,406,967 elapsed=417.4s

  [8416/13157] intraday_5258.csv.gz  in=334,223,951 out=82,419,128 elapsed=417.4s

  [8417/13157] intraday_5260.csv.gz  in=334,233,858 out=82,429,035 elapsed=417.5s

  [8418/13157] intraday_5259.csv.gz  in=334,245,166 out=82,440,343 elapsed=417.5s

  [8419/13157] intraday_5261.csv.gz  in=334,260,651 out=82,455,828 elapsed=417.5s

  [8420/13157] intraday_5262.csv.gz  in=334,274,093 out=82,469,270 elapsed=417.5s

  [8421/13157] intraday_5265.csv.gz  in=334,286,578 out=82,481,755 elapsed=417.9s

  [8422/13157] intraday_5263.csv.gz  in=334,298,288 out=82,493,465 elapsed=417.9s

  [8423/13157] intraday_5266.csv.gz  in=334,312,318 out=82,507,495 elapsed=417.9s

  [8424/13157] intraday_5264.csv.gz  in=334,324,700 out=82,519,877 elapsed=417.9s

  [8425/13157] intraday_5269.csv.gz  in=334,337,836 out=82,533,013 elapsed=418.0s

  [8426/13157] intraday_5267.csv.gz  in=334,349,531 out=82,544,708 elapsed=418.0s

  [8427/13157] intraday_5270.csv.gz  in=334,360,802 out=82,555,979 elapsed=418.0s

  [8428/13157] intraday_5268.csv.gz  in=334,373,405 out=82,568,582 elapsed=418.0s

  [8429/13157] intraday_5272.csv.gz  in=334,384,494 out=82,579,671 elapsed=418.0s

  [8430/13157] intraday_5271.csv.gz  in=334,396,664 out=82,591,841 elapsed=418.1s

  [8431/13157] intraday_5274.csv.gz  in=334,411,481 out=82,606,658 elapsed=418.1s

  [8432/13157] intraday_5273.csv.gz  in=334,426,660 out=82,621,837 elapsed=418.1s

  [8433/13157] intraday_5278.csv.gz  in=334,438,969 out=82,634,146 elapsed=418.1s

  [8434/13157] intraday_5276.csv.gz  in=334,450,290 out=82,645,467 elapsed=418.1s

  [8435/13157] intraday_5275.csv.gz  in=334,466,900 out=82,662,077 elapsed=418.1s

  [8436/13157] intraday_5277.csv.gz  in=334,479,117 out=82,674,294 elapsed=418.1s

  [8437/13157] intraday_5279.csv.gz  in=334,494,147 out=82,689,324 elapsed=418.2s

  [8438/13157] intraday_5280.csv.gz  in=334,505,125 out=82,700,302 elapsed=418.2s

  [8439/13157] intraday_5281.csv.gz  in=334,517,811 out=82,712,988 elapsed=418.2s

  [8440/13157] intraday_5282.csv.gz  in=334,531,010 out=82,726,187 elapsed=418.2s

  [8441/13157] intraday_5283.csv.gz  in=334,542,029 out=82,737,206 elapsed=418.2s

  [8442/13157] intraday_5284.csv.gz  in=334,553,968 out=82,749,145 elapsed=418.2s

  [8443/13157] intraday_5285.csv.gz  in=334,566,982 out=82,762,159 elapsed=418.2s

  [8444/13157] intraday_5286.csv.gz  in=334,579,529 out=82,774,706 elapsed=418.2s

  [8445/13157] intraday_5288.csv.gz  in=334,593,115 out=82,788,292 elapsed=418.3s

  [8446/13157] intraday_5287.csv.gz  in=334,606,860 out=82,802,037 elapsed=418.3s

  [8447/13157] intraday_5290.csv.gz  in=334,620,188 out=82,815,365 elapsed=418.3s

  [8448/13157] intraday_5289.csv.gz  in=334,633,413 out=82,828,590 elapsed=418.3s

  [8449/13157] intraday_5292.csv.gz  in=334,645,654 out=82,840,831 elapsed=418.3s

  [8450/13157] intraday_5291.csv.gz  in=334,658,200 out=82,853,377 elapsed=418.3s

  [8451/13157] intraday_5293.csv.gz  in=334,671,727 out=82,866,904 elapsed=418.4s

  [8452/13157] intraday_5294.csv.gz  in=334,682,809 out=82,877,986 elapsed=418.4s

  [8453/13157] intraday_5295.csv.gz  in=334,694,898 out=82,890,075 elapsed=418.4s

  [8454/13157] intraday_5296.csv.gz  in=334,711,441 out=82,906,618 elapsed=418.4s

  [8455/13157] intraday_5297.csv.gz  in=334,721,092 out=82,916,269 elapsed=418.4s

  [8456/13157] intraday_5298.csv.gz  in=334,732,707 out=82,927,884 elapsed=418.4s

  [8457/13157] intraday_5299.csv.gz  in=334,746,329 out=82,941,506 elapsed=418.4s

  [8458/13157] intraday_5300.csv.gz  in=334,759,591 out=82,954,768 elapsed=418.5s

  [8459/13157] intraday_5303.csv.gz  in=334,773,289 out=82,968,466 elapsed=418.5s

  [8460/13157] intraday_5301.csv.gz  in=334,787,506 out=82,982,683 elapsed=418.5s

  [8461/13157] intraday_5302.csv.gz  in=334,799,375 out=82,994,552 elapsed=418.5s

  [8462/13157] intraday_5304.csv.gz  in=334,811,325 out=83,006,502 elapsed=418.6s

  [8463/13157] intraday_5307.csv.gz  in=334,822,624 out=83,017,801 elapsed=418.6s

  [8464/13157] intraday_5306.csv.gz  in=334,834,625 out=83,029,802 elapsed=418.6s

  [8465/13157] intraday_5305.csv.gz  in=334,847,295 out=83,042,472 elapsed=418.6s

  [8466/13157] intraday_5308.csv.gz  in=334,857,912 out=83,053,089 elapsed=418.6s

  [8467/13157] intraday_5309.csv.gz  in=334,873,964 out=83,069,141 elapsed=418.7s

  [8468/13157] intraday_5311.csv.gz  in=334,888,153 out=83,083,330 elapsed=418.7s

  [8469/13157] intraday_5310.csv.gz  in=334,901,919 out=83,097,096 elapsed=418.7s

  [8470/13157] intraday_5312.csv.gz  in=334,913,976 out=83,109,153 elapsed=418.7s

  [8471/13157] intraday_5315.csv.gz  in=334,926,630 out=83,121,807 elapsed=418.9s

  [8472/13157] intraday_5314.csv.gz  in=334,938,725 out=83,133,902 elapsed=418.9s

  [8473/13157] intraday_5316.csv.gz  in=334,950,615 out=83,145,792 elapsed=418.9s

  [8474/13157] intraday_5313.csv.gz  in=334,961,224 out=83,156,401 elapsed=418.9s

  [8475/13157] intraday_5320.csv.gz  in=334,972,371 out=83,167,548 elapsed=419.6s

  [8476/13157] intraday_5317.csv.gz  in=334,985,622 out=83,180,799 elapsed=419.6s

  [8477/13157] intraday_5318.csv.gz  in=334,997,977 out=83,193,154 elapsed=419.6s

  [8478/13157] intraday_5319.csv.gz  in=335,010,882 out=83,206,059 elapsed=419.6s

  [8479/13157] intraday_5322.csv.gz  in=335,022,482 out=83,217,659 elapsed=419.6s

  [8480/13157] intraday_5323.csv.gz  in=335,035,401 out=83,230,578 elapsed=419.6s

  [8481/13157] intraday_5324.csv.gz  in=335,045,963 out=83,241,140 elapsed=419.7s

  [8482/13157] intraday_5321.csv.gz  in=335,060,017 out=83,255,194 elapsed=419.7s

  [8483/13157] intraday_5325.csv.gz  in=335,073,079 out=83,268,256 elapsed=419.7s

  [8484/13157] intraday_5328.csv.gz  in=335,087,382 out=83,282,559 elapsed=419.7s

  [8485/13157] intraday_5326.csv.gz  in=335,100,464 out=83,295,641 elapsed=419.7s

  [8486/13157] intraday_5327.csv.gz  in=335,116,610 out=83,311,787 elapsed=419.7s

  [8487/13157] intraday_5330.csv.gz  in=335,128,359 out=83,323,536 elapsed=419.8s

  [8488/13157] intraday_5332.csv.gz  in=335,142,417 out=83,337,594 elapsed=419.9s

  [8489/13157] intraday_5331.csv.gz  in=335,154,116 out=83,349,293 elapsed=419.9s

  [8490/13157] intraday_5329.csv.gz  in=335,167,123 out=83,362,300 elapsed=419.9s

  [8491/13157] intraday_5335.csv.gz  in=335,180,902 out=83,376,079 elapsed=419.9s

  [8492/13157] intraday_5334.csv.gz  in=335,192,788 out=83,387,965 elapsed=419.9s

  [8493/13157] intraday_5333.csv.gz  in=335,210,796 out=83,405,973 elapsed=419.9s

  [8494/13157] intraday_5336.csv.gz  in=335,223,546 out=83,418,723 elapsed=419.9s

  [8495/13157] intraday_5337.csv.gz  in=335,238,178 out=83,433,355 elapsed=420.0s

  [8496/13157] intraday_5339.csv.gz  in=335,250,584 out=83,445,761 elapsed=420.0s

  [8497/13157] intraday_5340.csv.gz  in=335,264,151 out=83,459,328 elapsed=420.0s

  [8498/13157] intraday_5338.csv.gz  in=335,278,410 out=83,473,587 elapsed=420.0s

  [8499/13157] intraday_5341.csv.gz  in=335,290,189 out=83,485,366 elapsed=420.0s

  [8500/13157] intraday_5344.csv.gz  in=335,303,179 out=83,498,356 elapsed=420.1s

  [8501/13157] intraday_5342.csv.gz  in=335,317,417 out=83,512,594 elapsed=420.1s

  [8502/13157] intraday_5343.csv.gz  in=335,330,251 out=83,525,428 elapsed=420.1s

  [8503/13157] intraday_5345.csv.gz  in=335,343,502 out=83,538,679 elapsed=420.1s

  [8504/13157] intraday_5347.csv.gz  in=335,354,812 out=83,549,989 elapsed=420.1s

  [8505/13157] intraday_5346.csv.gz  in=335,370,593 out=83,565,770 elapsed=420.1s

  [8506/13157] intraday_5349.csv.gz  in=335,387,021 out=83,582,198 elapsed=420.2s

  [8507/13157] intraday_5348.csv.gz  in=335,400,253 out=83,595,430 elapsed=420.2s

  [8508/13157] intraday_5350.csv.gz  in=335,411,159 out=83,606,336 elapsed=420.2s

  [8509/13157] intraday_5351.csv.gz  in=335,423,325 out=83,618,502 elapsed=420.2s

  [8510/13157] intraday_5353.csv.gz  in=335,438,213 out=83,633,390 elapsed=420.5s

  [8511/13157] intraday_5354.csv.gz  in=335,450,588 out=83,645,765 elapsed=420.5s

  [8512/13157] intraday_5352.csv.gz  in=335,466,094 out=83,661,271 elapsed=420.5s

  [8513/13157] intraday_5355.csv.gz  in=335,479,671 out=83,674,848 elapsed=420.9s

  [8514/13157] intraday_5357.csv.gz  in=335,494,713 out=83,689,890 elapsed=420.9s

  [8515/13157] intraday_5356.csv.gz  in=335,508,991 out=83,704,168 elapsed=420.9s

  [8516/13157] intraday_5358.csv.gz  in=335,524,895 out=83,720,072 elapsed=421.0s

  [8517/13157] intraday_5361.csv.gz  in=335,541,853 out=83,737,030 elapsed=421.1s

  [8518/13157] intraday_5359.csv.gz  in=335,556,369 out=83,751,546 elapsed=421.1s

  [8519/13157] intraday_5362.csv.gz  in=335,570,365 out=83,765,542 elapsed=421.1s

  [8520/13157] intraday_5360.csv.gz  in=335,584,480 out=83,779,657 elapsed=421.1s

  [8521/13157] intraday_5364.csv.gz  in=335,596,446 out=83,791,623 elapsed=421.3s

  [8522/13157] intraday_5365.csv.gz  in=335,609,749 out=83,804,926 elapsed=421.3s

  [8523/13157] intraday_5363.csv.gz  in=335,622,611 out=83,817,788 elapsed=421.3s

  [8524/13157] intraday_5366.csv.gz  in=335,633,741 out=83,828,918 elapsed=421.3s

  [8525/13157] intraday_5369.csv.gz  in=335,648,085 out=83,843,262 elapsed=421.5s

  [8526/13157] intraday_5368.csv.gz  in=335,661,807 out=83,856,984 elapsed=421.5s

  [8527/13157] intraday_5367.csv.gz  in=335,675,571 out=83,870,748 elapsed=421.5s

  [8528/13157] intraday_5370.csv.gz  in=335,691,652 out=83,886,829 elapsed=421.5s

  [8529/13157] intraday_5372.csv.gz  in=335,703,876 out=83,899,053 elapsed=421.6s

  [8530/13157] intraday_5371.csv.gz  in=335,716,556 out=83,911,733 elapsed=421.6s

  [8531/13157] intraday_5373.csv.gz  in=335,731,163 out=83,926,340 elapsed=421.6s

  [8532/13157] intraday_5374.csv.gz  in=335,743,899 out=83,939,076 elapsed=421.6s

  [8533/13157] intraday_5375.csv.gz  in=335,756,416 out=83,951,593 elapsed=421.7s

  [8534/13157] intraday_5378.csv.gz  in=335,769,985 out=83,965,162 elapsed=421.8s

  [8535/13157] intraday_5377.csv.gz  in=335,784,115 out=83,979,292 elapsed=421.8s

  [8536/13157] intraday_5376.csv.gz  in=335,799,961 out=83,995,138 elapsed=421.8s

  [8537/13157] intraday_5379.csv.gz  in=335,812,873 out=84,008,050 elapsed=421.8s

  [8538/13157] intraday_5380.csv.gz  in=335,823,823 out=84,019,000 elapsed=421.9s

  [8539/13157] intraday_5382.csv.gz  in=335,835,479 out=84,030,656 elapsed=421.9s

  [8540/13157] intraday_5381.csv.gz  in=335,849,180 out=84,044,357 elapsed=421.9s

  [8541/13157] intraday_5383.csv.gz  in=335,863,633 out=84,058,810 elapsed=421.9s

  [8542/13157] intraday_5384.csv.gz  in=335,872,505 out=84,067,682 elapsed=421.9s

  [8543/13157] intraday_5385.csv.gz  in=335,884,025 out=84,079,202 elapsed=421.9s

  [8544/13157] intraday_5388.csv.gz  in=335,884,825 out=84,080,002 elapsed=421.9s

  [8545/13157] intraday_5387.csv.gz  in=335,885,380 out=84,080,557 elapsed=421.9s

  [8546/13157] intraday_5386.csv.gz  in=335,894,938 out=84,090,115 elapsed=421.9s

  [8547/13157] intraday_5389.csv.gz  in=335,896,712 out=84,091,889 elapsed=421.9s

  [8548/13157] intraday_5390.csv.gz  in=335,897,316 out=84,092,493 elapsed=422.0s

  [8549/13157] intraday_5393.csv.gz  in=335,897,671 out=84,092,848 elapsed=422.0s

  [8550/13157] intraday_5392.csv.gz  in=335,898,429 out=84,092,966 elapsed=422.0s

  [8551/13157] intraday_5391.csv.gz  in=335,898,596 out=84,093,133 elapsed=422.0s

  [8552/13157] intraday_5394.csv.gz  in=335,898,989 out=84,093,526 elapsed=422.0s

  [8553/13157] intraday_5395.csv.gz  in=335,899,019 out=84,093,556 elapsed=422.0s

  [8554/13157] intraday_5396.csv.gz  in=335,899,053 out=84,093,588 elapsed=422.0s

  [8555/13157] intraday_5398.csv.gz  in=335,912,232 out=84,106,767 elapsed=422.1s

  [8556/13157] intraday_5400.csv.gz  in=335,924,500 out=84,118,474 elapsed=422.1s

  [8557/13157] intraday_5397.csv.gz  in=335,940,246 out=84,133,899 elapsed=422.1s

  [8558/13157] intraday_5399.csv.gz  in=335,953,672 out=84,147,325 elapsed=422.1s

  [8559/13157] intraday_5401.csv.gz  in=335,966,459 out=84,160,112 elapsed=422.1s

  [8560/13157] intraday_5404.csv.gz  in=335,978,241 out=84,171,894 elapsed=422.1s

  [8561/13157] intraday_5403.csv.gz  in=335,992,688 out=84,186,341 elapsed=422.1s

  [8562/13157] intraday_5402.csv.gz  in=336,007,956 out=84,201,609 elapsed=422.1s

  [8563/13157] intraday_5405.csv.gz  in=336,021,969 out=84,215,622 elapsed=422.2s

  [8564/13157] intraday_5407.csv.gz  in=336,036,225 out=84,229,878 elapsed=422.2s

  [8565/13157] intraday_5406.csv.gz  in=336,050,815 out=84,244,468 elapsed=422.3s

  [8566/13157] intraday_5408.csv.gz  in=336,064,550 out=84,258,203 elapsed=422.3s

  [8567/13157] intraday_5409.csv.gz  in=336,076,628 out=84,270,281 elapsed=422.4s

  [8568/13157] intraday_5412.csv.gz  in=336,086,087 out=84,279,740 elapsed=422.4s

  [8569/13157] intraday_5411.csv.gz  in=336,096,701 out=84,290,354 elapsed=422.4s

  [8570/13157] intraday_5410.csv.gz  in=336,108,988 out=84,302,641 elapsed=422.4s

  [8571/13157] intraday_5415.csv.gz  in=336,120,608 out=84,314,261 elapsed=422.7s

  [8572/13157] intraday_5416.csv.gz  in=336,132,713 out=84,326,366 elapsed=422.7s

  [8573/13157] intraday_5414.csv.gz  in=336,146,421 out=84,340,074 elapsed=422.7s

  [8574/13157] intraday_5413.csv.gz  in=336,161,878 out=84,355,531 elapsed=422.7s

  [8575/13157] intraday_5417.csv.gz  in=336,175,114 out=84,368,767 elapsed=422.9s

  [8576/13157] intraday_5420.csv.gz  in=336,187,564 out=84,381,217 elapsed=422.9s

  [8577/13157] intraday_5418.csv.gz  in=336,201,188 out=84,394,841 elapsed=423.0s

  [8578/13157] intraday_5419.csv.gz  in=336,214,471 out=84,408,124 elapsed=423.0s

  [8579/13157] intraday_5421.csv.gz  in=336,227,967 out=84,421,620 elapsed=423.0s

  [8580/13157] intraday_5422.csv.gz  in=336,239,127 out=84,432,780 elapsed=423.5s

  [8581/13157] intraday_5423.csv.gz  in=336,251,590 out=84,445,243 elapsed=423.5s

  [8582/13157] intraday_5424.csv.gz  in=336,263,030 out=84,456,683 elapsed=423.5s

  [8583/13157] intraday_5425.csv.gz  in=336,277,438 out=84,471,091 elapsed=423.5s

  [8584/13157] intraday_5426.csv.gz  in=336,292,591 out=84,486,244 elapsed=423.7s

  [8585/13157] intraday_5429.csv.gz  in=336,304,542 out=84,498,195 elapsed=423.7s

  [8586/13157] intraday_5428.csv.gz  in=336,316,121 out=84,509,774 elapsed=423.7s

  [8587/13157] intraday_5427.csv.gz  in=336,331,505 out=84,525,158 elapsed=423.7s

  [8588/13157] intraday_5432.csv.gz  in=336,342,424 out=84,536,077 elapsed=423.8s

  [8589/13157] intraday_5430.csv.gz  in=336,354,811 out=84,548,464 elapsed=423.8s

  [8590/13157] intraday_5433.csv.gz  in=336,367,441 out=84,561,094 elapsed=423.8s

  [8591/13157] intraday_5431.csv.gz  in=336,381,933 out=84,575,586 elapsed=423.8s

  [8592/13157] intraday_5434.csv.gz  in=336,395,021 out=84,588,517 elapsed=423.8s

  [8593/13157] intraday_5435.csv.gz  in=336,405,918 out=84,599,414 elapsed=423.9s

  [8594/13157] intraday_5436.csv.gz  in=336,416,986 out=84,610,482 elapsed=423.9s

  [8595/13157] intraday_5437.csv.gz  in=336,430,151 out=84,623,647 elapsed=423.9s

  [8596/13157] intraday_5440.csv.gz  in=336,443,500 out=84,636,996 elapsed=423.9s

  [8597/13157] intraday_5439.csv.gz  in=336,457,253 out=84,650,749 elapsed=423.9s

  [8598/13157] intraday_5438.csv.gz  in=336,470,334 out=84,663,830 elapsed=423.9s

  [8599/13157] intraday_5441.csv.gz  in=336,483,972 out=84,677,468 elapsed=423.9s

  [8600/13157] intraday_5442.csv.gz  in=336,496,321 out=84,689,817 elapsed=424.0s

  [8601/13157] intraday_5443.csv.gz  in=336,508,554 out=84,702,050 elapsed=424.0s

  [8602/13157] intraday_5444.csv.gz  in=336,520,186 out=84,713,682 elapsed=424.0s

  [8603/13157] intraday_5445.csv.gz  in=336,532,789 out=84,726,285 elapsed=424.0s

  [8604/13157] intraday_5446.csv.gz  in=336,544,009 out=84,737,505 elapsed=424.0s

  [8605/13157] intraday_5447.csv.gz  in=336,555,968 out=84,749,464 elapsed=424.1s

  [8606/13157] intraday_5448.csv.gz  in=336,571,143 out=84,764,639 elapsed=424.1s

  [8607/13157] intraday_5449.csv.gz  in=336,580,865 out=84,774,361 elapsed=424.1s

  [8608/13157] intraday_5450.csv.gz  in=336,592,607 out=84,786,103 elapsed=424.1s

  [8609/13157] intraday_5453.csv.gz  in=336,607,542 out=84,801,038 elapsed=424.2s

  [8610/13157] intraday_5452.csv.gz  in=336,629,439 out=84,814,635 elapsed=424.2s

  [8611/13157] intraday_5451.csv.gz  in=336,643,719 out=84,828,915 elapsed=424.2s

  [8612/13157] intraday_5454.csv.gz  in=336,656,101 out=84,841,297 elapsed=424.2s

  [8613/13157] intraday_5455.csv.gz  in=336,669,354 out=84,854,550 elapsed=424.2s

  [8614/13157] intraday_5458.csv.gz  in=336,681,029 out=84,866,225 elapsed=424.2s

  [8615/13157] intraday_5456.csv.gz  in=336,694,014 out=84,877,626 elapsed=424.2s

  [8616/13157] intraday_5457.csv.gz  in=336,707,061 out=84,890,673 elapsed=424.2s

  [8617/13157] intraday_5459.csv.gz  in=336,717,839 out=84,901,451 elapsed=424.2s

  [8618/13157] intraday_5460.csv.gz  in=336,728,246 out=84,911,858 elapsed=424.2s

  [8619/13157] intraday_5461.csv.gz  in=336,743,401 out=84,927,013 elapsed=424.3s

  [8620/13157] intraday_5463.csv.gz  in=336,757,913 out=84,941,525 elapsed=424.3s

  [8621/13157] intraday_5462.csv.gz  in=336,771,357 out=84,954,969 elapsed=424.3s

  [8622/13157] intraday_5464.csv.gz  in=336,783,243 out=84,966,855 elapsed=424.3s

  [8623/13157] intraday_5465.csv.gz  in=336,793,403 out=84,977,015 elapsed=424.7s

  [8624/13157] intraday_5466.csv.gz  in=336,805,143 out=84,988,755 elapsed=424.9s

  [8625/13157] intraday_5467.csv.gz  in=336,817,593 out=85,001,205 elapsed=424.9s

  [8626/13157] intraday_5468.csv.gz  in=336,829,512 out=85,013,124 elapsed=424.9s

  [8627/13157] intraday_5470.csv.gz  in=336,841,172 out=85,024,784 elapsed=425.0s

  [8628/13157] intraday_5471.csv.gz  in=336,852,803 out=85,036,415 elapsed=425.1s

  [8629/13157] intraday_5473.csv.gz  in=336,866,410 out=85,050,022 elapsed=425.1s

  [8630/13157] intraday_5469.csv.gz  in=336,880,335 out=85,063,947 elapsed=425.1s

  [8631/13157] intraday_5472.csv.gz  in=336,892,094 out=85,075,706 elapsed=425.1s

  [8632/13157] intraday_5476.csv.gz  in=336,902,145 out=85,085,757 elapsed=425.3s

  [8633/13157] intraday_5477.csv.gz  in=336,915,304 out=85,098,916 elapsed=425.3s

  [8634/13157] intraday_5474.csv.gz  in=336,926,738 out=85,110,350 elapsed=425.3s

  [8635/13157] intraday_5475.csv.gz  in=336,940,007 out=85,123,555 elapsed=425.3s

  [8636/13157] intraday_5478.csv.gz  in=336,952,049 out=85,135,597 elapsed=425.3s

  [8637/13157] intraday_5481.csv.gz  in=336,964,403 out=85,147,951 elapsed=425.4s

  [8638/13157] intraday_5479.csv.gz  in=336,980,588 out=85,164,136 elapsed=425.4s

  [8639/13157] intraday_5480.csv.gz  in=336,994,212 out=85,177,760 elapsed=425.4s

  [8640/13157] intraday_5482.csv.gz  in=337,005,909 out=85,189,457 elapsed=425.4s

  [8641/13157] intraday_5484.csv.gz  in=337,020,067 out=85,203,615 elapsed=425.4s

  [8642/13157] intraday_5483.csv.gz  in=337,031,751 out=85,215,299 elapsed=425.4s

  [8643/13157] intraday_5485.csv.gz  in=337,051,031 out=85,232,576 elapsed=425.4s

  [8644/13157] intraday_5486.csv.gz  in=337,063,167 out=85,244,712 elapsed=425.4s

  [8645/13157] intraday_5488.csv.gz  in=337,076,389 out=85,257,934 elapsed=425.6s

  [8646/13157] intraday_5490.csv.gz  in=337,090,155 out=85,271,700 elapsed=425.6s

  [8647/13157] intraday_5489.csv.gz  in=337,104,291 out=85,285,836 elapsed=425.6s

  [8648/13157] intraday_5487.csv.gz  in=337,117,850 out=85,299,395 elapsed=425.6s

  [8649/13157] intraday_5491.csv.gz  in=337,130,189 out=85,311,734 elapsed=425.7s

  [8650/13157] intraday_5492.csv.gz  in=337,143,433 out=85,324,978 elapsed=425.8s

  [8651/13157] intraday_5493.csv.gz  in=337,154,835 out=85,336,380 elapsed=425.9s

  [8652/13157] intraday_5494.csv.gz  in=337,169,301 out=85,350,846 elapsed=426.2s

  [8653/13157] intraday_5496.csv.gz  in=337,182,649 out=85,364,194 elapsed=426.8s

  [8654/13157] intraday_5495.csv.gz  in=337,195,172 out=85,376,717 elapsed=426.8s

  [8655/13157] intraday_5498.csv.gz  in=337,210,436 out=85,391,981 elapsed=426.8s

  [8656/13157] intraday_5497.csv.gz  in=337,241,163 out=85,406,474 elapsed=426.8s

  [8657/13157] intraday_5500.csv.gz  in=337,254,282 out=85,419,593 elapsed=427.0s

  [8658/13157] intraday_5499.csv.gz  in=337,265,788 out=85,431,099 elapsed=427.0s

  [8659/13157] intraday_5502.csv.gz  in=337,276,892 out=85,442,203 elapsed=427.0s

  [8660/13157] intraday_5501.csv.gz  in=337,293,420 out=85,458,731 elapsed=427.3s

  [8661/13157] intraday_5503.csv.gz  in=337,305,654 out=85,470,965 elapsed=427.3s

  [8662/13157] intraday_5504.csv.gz  in=337,321,936 out=85,487,247 elapsed=427.4s

  [8663/13157] intraday_5505.csv.gz  in=337,336,725 out=85,502,036 elapsed=427.4s

  [8664/13157] intraday_5507.csv.gz  in=337,350,333 out=85,515,644 elapsed=427.5s

  [8665/13157] intraday_5508.csv.gz  in=337,363,974 out=85,529,285 elapsed=427.5s

  [8666/13157] intraday_5506.csv.gz  in=337,376,319 out=85,541,630 elapsed=427.5s

  [8667/13157] intraday_5509.csv.gz  in=337,389,314 out=85,554,625 elapsed=427.6s

  [8668/13157] intraday_5511.csv.gz  in=337,402,253 out=85,567,564 elapsed=427.7s

  [8669/13157] intraday_5513.csv.gz  in=337,418,598 out=85,583,909 elapsed=427.8s

  [8670/13157] intraday_5510.csv.gz  in=337,434,991 out=85,600,302 elapsed=427.8s

  [8671/13157] intraday_5512.csv.gz  in=337,449,920 out=85,615,231 elapsed=427.8s

  [8672/13157] intraday_5514.csv.gz  in=337,463,908 out=85,629,219 elapsed=427.8s

  [8673/13157] intraday_5516.csv.gz  in=337,474,948 out=85,640,259 elapsed=428.0s

  [8674/13157] intraday_5518.csv.gz  in=337,485,870 out=85,651,181 elapsed=428.0s

  [8675/13157] intraday_5515.csv.gz  in=337,498,027 out=85,663,338 elapsed=428.0s

  [8676/13157] intraday_5517.csv.gz  in=337,512,579 out=85,677,890 elapsed=428.0s

  [8677/13157] intraday_5520.csv.gz  in=337,525,465 out=85,690,776 elapsed=428.1s

  [8678/13157] intraday_5522.csv.gz  in=337,538,515 out=85,703,826 elapsed=428.1s

  [8679/13157] intraday_5521.csv.gz  in=337,554,985 out=85,720,296 elapsed=428.1s

  [8680/13157] intraday_5519.csv.gz  in=337,568,427 out=85,733,738 elapsed=428.1s

  [8681/13157] intraday_5524.csv.gz  in=337,581,576 out=85,746,887 elapsed=428.1s

  [8682/13157] intraday_5523.csv.gz  in=337,594,327 out=85,759,638 elapsed=428.1s

  [8683/13157] intraday_5525.csv.gz  in=337,607,914 out=85,773,225 elapsed=428.2s

  [8684/13157] intraday_5526.csv.gz  in=337,623,336 out=85,786,423 elapsed=428.2s

  [8685/13157] intraday_5527.csv.gz  in=337,636,417 out=85,799,504 elapsed=428.2s

  [8686/13157] intraday_5528.csv.gz  in=337,651,263 out=85,814,350 elapsed=428.2s

  [8687/13157] intraday_5529.csv.gz  in=337,666,118 out=85,829,205 elapsed=428.2s

  [8688/13157] intraday_5531.csv.gz  in=337,677,414 out=85,840,501 elapsed=428.3s

  [8689/13157] intraday_5530.csv.gz  in=337,692,621 out=85,855,708 elapsed=428.3s

  [8690/13157] intraday_5533.csv.gz  in=337,706,389 out=85,869,476 elapsed=428.3s

  [8691/13157] intraday_5532.csv.gz  in=337,718,168 out=85,881,255 elapsed=428.3s

  [8692/13157] intraday_5534.csv.gz  in=337,730,348 out=85,893,435 elapsed=428.3s

  [8693/13157] intraday_5537.csv.gz  in=337,741,969 out=85,905,056 elapsed=428.4s

  [8694/13157] intraday_5536.csv.gz  in=337,749,584 out=85,912,671 elapsed=428.4s

  [8695/13157] intraday_5535.csv.gz  in=337,783,266 out=85,928,307 elapsed=428.4s

  [8696/13157] intraday_5538.csv.gz  in=337,791,884 out=85,936,925 elapsed=428.4s

  [8697/13157] intraday_5540.csv.gz  in=337,805,170 out=85,950,211 elapsed=428.4s

  [8698/13157] intraday_5539.csv.gz  in=337,819,597 out=85,964,638 elapsed=428.4s

  [8699/13157] intraday_5542.csv.gz  in=337,831,180 out=85,976,221 elapsed=428.4s

  [8700/13157] intraday_5541.csv.gz  in=337,843,575 out=85,988,616 elapsed=428.4s

  [8701/13157] intraday_5543.csv.gz  in=337,855,891 out=86,000,932 elapsed=428.5s

  [8702/13157] intraday_5546.csv.gz  in=337,867,417 out=86,012,458 elapsed=428.5s

  [8703/13157] intraday_5544.csv.gz  in=337,882,612 out=86,027,653 elapsed=428.5s

  [8704/13157] intraday_5545.csv.gz  in=337,898,036 out=86,043,077 elapsed=428.7s

  [8705/13157] intraday_5547.csv.gz  in=337,910,882 out=86,055,923 elapsed=428.7s

  [8706/13157] intraday_5548.csv.gz  in=337,924,453 out=86,069,494 elapsed=428.7s

  [8707/13157] intraday_5549.csv.gz  in=337,937,799 out=86,082,840 elapsed=428.7s

  [8708/13157] intraday_5550.csv.gz  in=337,954,746 out=86,096,397 elapsed=428.8s

  [8709/13157] intraday_5554.csv.gz  in=337,963,739 out=86,105,390 elapsed=428.8s

  [8710/13157] intraday_5553.csv.gz  in=337,973,908 out=86,115,559 elapsed=428.8s

  [8711/13157] intraday_5551.csv.gz  in=337,985,876 out=86,127,527 elapsed=428.8s

  [8712/13157] intraday_5552.csv.gz  in=337,997,395 out=86,139,046 elapsed=428.8s

  [8713/13157] intraday_5555.csv.gz  in=338,011,699 out=86,153,350 elapsed=428.9s

  [8714/13157] intraday_5557.csv.gz  in=338,021,937 out=86,163,588 elapsed=428.9s

  [8715/13157] intraday_5558.csv.gz  in=338,033,158 out=86,174,809 elapsed=428.9s

  [8716/13157] intraday_5556.csv.gz  in=338,046,675 out=86,188,326 elapsed=428.9s

  [8717/13157] intraday_5559.csv.gz  in=338,058,703 out=86,200,354 elapsed=429.1s

  [8718/13157] intraday_5561.csv.gz  in=338,071,232 out=86,212,377 elapsed=429.1s

  [8719/13157] intraday_5562.csv.gz  in=338,083,562 out=86,224,707 elapsed=429.1s

  [8720/13157] intraday_5560.csv.gz  in=338,097,322 out=86,238,467 elapsed=429.1s

  [8721/13157] intraday_5563.csv.gz  in=338,111,034 out=86,252,179 elapsed=429.2s

  [8722/13157] intraday_5566.csv.gz  in=338,122,560 out=86,263,705 elapsed=429.2s

  [8723/13157] intraday_5564.csv.gz  in=338,133,624 out=86,274,769 elapsed=429.2s

  [8724/13157] intraday_5565.csv.gz  in=338,146,018 out=86,287,163 elapsed=429.2s

  [8725/13157] intraday_5567.csv.gz  in=338,159,044 out=86,300,189 elapsed=429.2s

  [8726/13157] intraday_5569.csv.gz  in=338,173,947 out=86,315,092 elapsed=429.3s

  [8727/13157] intraday_5570.csv.gz  in=338,184,681 out=86,325,826 elapsed=429.3s

  [8728/13157] intraday_5568.csv.gz  in=338,199,555 out=86,340,700 elapsed=429.3s

  [8729/13157] intraday_5571.csv.gz  in=338,211,205 out=86,352,350 elapsed=429.3s

  [8730/13157] intraday_5573.csv.gz  in=338,225,053 out=86,366,198 elapsed=429.3s

  [8731/13157] intraday_5574.csv.gz  in=338,246,706 out=86,377,711 elapsed=429.3s

  [8732/13157] intraday_5572.csv.gz  in=338,258,788 out=86,389,793 elapsed=429.4s

  [8733/13157] intraday_5575.csv.gz  in=338,270,567 out=86,401,572 elapsed=429.4s

  [8734/13157] intraday_5576.csv.gz  in=338,282,251 out=86,413,256 elapsed=429.4s

  [8735/13157] intraday_5577.csv.gz  in=338,292,917 out=86,423,922 elapsed=429.4s

  [8736/13157] intraday_5578.csv.gz  in=338,303,971 out=86,434,976 elapsed=429.4s

  [8737/13157] intraday_5579.csv.gz  in=338,320,526 out=86,449,867 elapsed=429.5s

  [8738/13157] intraday_5580.csv.gz  in=338,332,889 out=86,462,230 elapsed=429.5s

  [8739/13157] intraday_5581.csv.gz  in=338,345,097 out=86,474,438 elapsed=429.5s

  [8740/13157] intraday_5582.csv.gz  in=338,358,892 out=86,488,233 elapsed=429.5s

  [8741/13157] intraday_5584.csv.gz  in=338,370,781 out=86,500,122 elapsed=429.6s

  [8742/13157] intraday_5585.csv.gz  in=338,382,606 out=86,511,947 elapsed=429.6s

  [8743/13157] intraday_5583.csv.gz  in=338,395,265 out=86,524,606 elapsed=429.6s

  [8744/13157] intraday_5586.csv.gz  in=338,406,627 out=86,535,968 elapsed=429.6s

  [8745/13157] intraday_5587.csv.gz  in=338,418,682 out=86,547,882 elapsed=429.6s

  [8746/13157] intraday_5588.csv.gz  in=338,429,851 out=86,559,051 elapsed=429.6s

  [8747/13157] intraday_5589.csv.gz  in=338,441,171 out=86,570,371 elapsed=429.6s

  [8748/13157] intraday_5590.csv.gz  in=338,455,092 out=86,584,292 elapsed=429.7s

  [8749/13157] intraday_5591.csv.gz  in=338,465,278 out=86,594,478 elapsed=429.7s

  [8750/13157] intraday_5592.csv.gz  in=338,475,318 out=86,604,518 elapsed=429.7s

  [8751/13157] intraday_5593.csv.gz  in=338,489,720 out=86,618,920 elapsed=429.7s

  [8752/13157] intraday_5594.csv.gz  in=338,501,950 out=86,631,150 elapsed=430.3s

  [8753/13157] intraday_5597.csv.gz  in=338,514,701 out=86,643,901 elapsed=430.4s

  [8754/13157] intraday_5596.csv.gz  in=338,526,490 out=86,655,690 elapsed=430.4s

  [8755/13157] intraday_5598.csv.gz  in=338,538,777 out=86,667,977 elapsed=430.4s

  [8756/13157] intraday_5595.csv.gz  in=338,552,906 out=86,682,106 elapsed=430.4s

  [8757/13157] intraday_5599.csv.gz  in=338,565,496 out=86,694,696 elapsed=430.4s

  [8758/13157] intraday_5600.csv.gz  in=338,576,995 out=86,706,195 elapsed=430.5s

  [8759/13157] intraday_5601.csv.gz  in=338,587,733 out=86,716,933 elapsed=430.5s

  [8760/13157] intraday_5602.csv.gz  in=338,598,455 out=86,727,655 elapsed=430.5s

  [8761/13157] intraday_5604.csv.gz  in=338,611,498 out=86,740,698 elapsed=430.5s

  [8762/13157] intraday_5603.csv.gz  in=338,626,048 out=86,755,248 elapsed=430.5s

  [8763/13157] intraday_5607.csv.gz  in=338,635,724 out=86,764,810 elapsed=430.7s

  [8764/13157] intraday_5605.csv.gz  in=338,649,768 out=86,778,854 elapsed=430.7s

  [8765/13157] intraday_5606.csv.gz  in=338,661,889 out=86,790,975 elapsed=430.7s

  [8766/13157] intraday_5608.csv.gz  in=338,673,404 out=86,802,476 elapsed=430.7s

  [8767/13157] intraday_5609.csv.gz  in=338,685,102 out=86,814,174 elapsed=430.7s

  [8768/13157] intraday_5612.csv.gz  in=338,696,176 out=86,825,248 elapsed=430.8s

  [8769/13157] intraday_5610.csv.gz  in=338,708,283 out=86,837,355 elapsed=430.8s

  [8770/13157] intraday_5611.csv.gz  in=338,721,715 out=86,850,787 elapsed=430.8s

  [8771/13157] intraday_5613.csv.gz  in=338,733,312 out=86,862,384 elapsed=430.8s

  [8772/13157] intraday_5615.csv.gz  in=338,746,680 out=86,875,752 elapsed=430.8s

  [8773/13157] intraday_5614.csv.gz  in=338,757,110 out=86,886,182 elapsed=430.9s

  [8774/13157] intraday_5617.csv.gz  in=338,769,744 out=86,898,816 elapsed=430.9s

  [8775/13157] intraday_5616.csv.gz  in=338,780,652 out=86,909,724 elapsed=430.9s

  [8776/13157] intraday_5618.csv.gz  in=338,791,284 out=86,920,356 elapsed=430.9s

  [8777/13157] intraday_5620.csv.gz  in=338,802,694 out=86,931,766 elapsed=430.9s

  [8778/13157] intraday_5619.csv.gz  in=338,814,335 out=86,943,407 elapsed=430.9s

  [8779/13157] intraday_5621.csv.gz  in=338,829,343 out=86,958,415 elapsed=430.9s

  [8780/13157] intraday_5623.csv.gz  in=338,841,309 out=86,970,381 elapsed=431.0s

  [8781/13157] intraday_5622.csv.gz  in=338,855,420 out=86,984,492 elapsed=431.0s

  [8782/13157] intraday_5625.csv.gz  in=338,866,534 out=86,995,606 elapsed=431.0s

  [8783/13157] intraday_5626.csv.gz  in=338,880,161 out=87,009,233 elapsed=431.0s

  [8784/13157] intraday_5624.csv.gz  in=338,892,118 out=87,021,190 elapsed=431.0s

  [8785/13157] intraday_5627.csv.gz  in=338,908,126 out=87,037,198 elapsed=431.0s

  [8786/13157] intraday_5628.csv.gz  in=338,920,069 out=87,049,141 elapsed=431.0s

  [8787/13157] intraday_5630.csv.gz  in=338,933,084 out=87,062,156 elapsed=431.1s

  [8788/13157] intraday_5631.csv.gz  in=338,946,633 out=87,075,705 elapsed=431.1s

  [8789/13157] intraday_5632.csv.gz  in=338,960,939 out=87,089,585 elapsed=431.1s

  [8790/13157] intraday_5629.csv.gz  in=338,974,148 out=87,102,794 elapsed=431.1s

  [8791/13157] intraday_5633.csv.gz  in=338,986,550 out=87,115,196 elapsed=431.1s

  [8792/13157] intraday_5635.csv.gz  in=338,998,103 out=87,126,749 elapsed=431.2s

  [8793/13157] intraday_5636.csv.gz  in=339,012,091 out=87,140,737 elapsed=431.2s

  [8794/13157] intraday_5634.csv.gz  in=339,025,071 out=87,153,717 elapsed=431.2s

  [8795/13157] intraday_5639.csv.gz  in=339,037,048 out=87,165,694 elapsed=431.6s

  [8796/13157] intraday_5638.csv.gz  in=339,049,761 out=87,178,407 elapsed=431.6s

  [8797/13157] intraday_5640.csv.gz  in=339,064,377 out=87,193,023 elapsed=431.6s

  [8798/13157] intraday_5637.csv.gz  in=339,092,087 out=87,207,159 elapsed=431.7s

  [8799/13157] intraday_5641.csv.gz  in=339,103,033 out=87,218,105 elapsed=431.9s

  [8800/13157] intraday_5642.csv.gz  in=339,115,401 out=87,230,473 elapsed=431.9s

  [8801/13157] intraday_5643.csv.gz  in=339,131,809 out=87,246,881 elapsed=431.9s

  [8802/13157] intraday_5644.csv.gz  in=339,142,506 out=87,257,578 elapsed=431.9s

  [8803/13157] intraday_5645.csv.gz  in=339,156,211 out=87,270,582 elapsed=432.0s

  [8804/13157] intraday_5646.csv.gz  in=339,172,144 out=87,286,515 elapsed=432.0s

  [8805/13157] intraday_5648.csv.gz  in=339,184,243 out=87,298,614 elapsed=432.0s

  [8806/13157] intraday_5647.csv.gz  in=339,199,182 out=87,313,553 elapsed=432.0s

  [8807/13157] intraday_5649.csv.gz  in=339,212,328 out=87,326,699 elapsed=432.0s

  [8808/13157] intraday_5653.csv.gz  in=339,225,209 out=87,339,580 elapsed=432.1s

  [8809/13157] intraday_5650.csv.gz  in=339,238,650 out=87,353,021 elapsed=432.1s

  [8810/13157] intraday_5652.csv.gz  in=339,254,399 out=87,368,770 elapsed=432.1s

  [8811/13157] intraday_5651.csv.gz  in=339,267,186 out=87,381,557 elapsed=432.1s

  [8812/13157] intraday_5656.csv.gz  in=339,280,532 out=87,394,903 elapsed=432.2s

  [8813/13157] intraday_5654.csv.gz  in=339,293,856 out=87,408,227 elapsed=432.2s

  [8814/13157] intraday_5655.csv.gz  in=339,309,432 out=87,423,803 elapsed=432.2s

  [8815/13157] intraday_5657.csv.gz  in=339,321,445 out=87,435,816 elapsed=432.2s

  [8816/13157] intraday_5658.csv.gz  in=339,332,564 out=87,446,935 elapsed=432.3s

  [8817/13157] intraday_5659.csv.gz  in=339,346,618 out=87,460,989 elapsed=432.3s

  [8818/13157] intraday_5661.csv.gz  in=339,359,938 out=87,474,309 elapsed=432.3s

  [8819/13157] intraday_5660.csv.gz  in=339,371,080 out=87,485,451 elapsed=432.3s

  [8820/13157] intraday_5662.csv.gz  in=339,383,248 out=87,497,619 elapsed=432.3s

  [8821/13157] intraday_5665.csv.gz  in=339,395,846 out=87,510,217 elapsed=432.4s

  [8822/13157] intraday_5664.csv.gz  in=339,408,091 out=87,522,462 elapsed=432.4s

  [8823/13157] intraday_5663.csv.gz  in=339,424,962 out=87,539,333 elapsed=432.4s

  [8824/13157] intraday_5666.csv.gz  in=339,436,907 out=87,551,278 elapsed=432.4s

  [8825/13157] intraday_5667.csv.gz  in=339,449,317 out=87,563,688 elapsed=432.4s

  [8826/13157] intraday_5669.csv.gz  in=339,463,005 out=87,577,376 elapsed=432.4s

  [8827/13157] intraday_5668.csv.gz  in=339,474,594 out=87,588,965 elapsed=432.4s

  [8828/13157] intraday_5670.csv.gz  in=339,488,599 out=87,602,970 elapsed=432.5s

  [8829/13157] intraday_5672.csv.gz  in=339,502,410 out=87,616,781 elapsed=432.5s

  [8830/13157] intraday_5673.csv.gz  in=339,513,387 out=87,627,758 elapsed=432.5s

  [8831/13157] intraday_5671.csv.gz  in=339,528,925 out=87,643,296 elapsed=432.5s

  [8832/13157] intraday_5675.csv.gz  in=339,542,541 out=87,656,912 elapsed=432.9s

  [8833/13157] intraday_5674.csv.gz  in=339,554,334 out=87,668,705 elapsed=432.9s

  [8834/13157] intraday_5676.csv.gz  in=339,566,544 out=87,680,915 elapsed=432.9s

  [8835/13157] intraday_5678.csv.gz  in=339,573,923 out=87,688,294 elapsed=433.0s

  [8836/13157] intraday_5679.csv.gz  in=339,585,134 out=87,699,505 elapsed=433.0s

  [8837/13157] intraday_5680.csv.gz  in=339,592,839 out=87,707,210 elapsed=433.0s

  [8838/13157] intraday_5677.csv.gz  in=339,618,537 out=87,721,729 elapsed=433.0s

  [8839/13157] intraday_5681.csv.gz  in=339,634,033 out=87,737,225 elapsed=433.0s

  [8840/13157] intraday_5682.csv.gz  in=339,647,164 out=87,750,356 elapsed=433.0s

  [8841/13157] intraday_5684.csv.gz  in=339,657,747 out=87,760,939 elapsed=433.1s

  [8842/13157] intraday_5683.csv.gz  in=339,669,985 out=87,773,177 elapsed=433.1s

  [8843/13157] intraday_5685.csv.gz  in=339,682,370 out=87,785,562 elapsed=433.1s

  [8844/13157] intraday_5686.csv.gz  in=339,697,777 out=87,800,969 elapsed=433.1s

  [8845/13157] intraday_5688.csv.gz  in=339,709,464 out=87,812,656 elapsed=433.2s

  [8846/13157] intraday_5689.csv.gz  in=339,723,099 out=87,826,291 elapsed=433.2s

  [8847/13157] intraday_5690.csv.gz  in=339,737,189 out=87,840,028 elapsed=433.2s

  [8848/13157] intraday_5687.csv.gz  in=339,752,905 out=87,855,744 elapsed=433.2s

  [8849/13157] intraday_5691.csv.gz  in=339,765,583 out=87,868,422 elapsed=433.2s

  [8850/13157] intraday_5693.csv.gz  in=339,779,765 out=87,880,865 elapsed=433.2s

  [8851/13157] intraday_5692.csv.gz  in=339,793,199 out=87,894,299 elapsed=433.3s

  [8852/13157] intraday_5694.csv.gz  in=339,804,880 out=87,905,980 elapsed=433.3s

  [8853/13157] intraday_5695.csv.gz  in=339,815,540 out=87,916,640 elapsed=433.3s

  [8854/13157] intraday_5697.csv.gz  in=339,829,320 out=87,930,420 elapsed=433.3s

  [8855/13157] intraday_5696.csv.gz  in=339,838,929 out=87,940,029 elapsed=433.3s

  [8856/13157] intraday_5698.csv.gz  in=339,851,880 out=87,952,980 elapsed=433.3s

  [8857/13157] intraday_5699.csv.gz  in=339,865,252 out=87,964,498 elapsed=433.3s

  [8858/13157] intraday_5700.csv.gz  in=339,877,312 out=87,976,558 elapsed=433.4s

  [8859/13157] intraday_5702.csv.gz  in=339,890,270 out=87,989,516 elapsed=433.4s

  [8860/13157] intraday_5701.csv.gz  in=339,902,127 out=88,001,373 elapsed=433.4s

  [8861/13157] intraday_5703.csv.gz  in=339,915,255 out=88,014,501 elapsed=433.4s

  [8862/13157] intraday_5704.csv.gz  in=339,928,109 out=88,027,355 elapsed=433.4s

  [8863/13157] intraday_5705.csv.gz  in=339,941,115 out=88,040,361 elapsed=433.5s

  [8864/13157] intraday_5708.csv.gz  in=339,953,150 out=88,052,396 elapsed=433.5s

  [8865/13157] intraday_5707.csv.gz  in=339,965,040 out=88,064,286 elapsed=433.5s

  [8866/13157] intraday_5706.csv.gz  in=339,975,903 out=88,075,149 elapsed=433.5s

  [8867/13157] intraday_5711.csv.gz  in=339,991,323 out=88,090,569 elapsed=433.6s

  [8868/13157] intraday_5709.csv.gz  in=340,005,555 out=88,104,801 elapsed=433.6s

  [8869/13157] intraday_5712.csv.gz  in=340,021,845 out=88,116,074 elapsed=433.6s

  [8870/13157] intraday_5710.csv.gz  in=340,036,873 out=88,130,238 elapsed=433.6s

  [8871/13157] intraday_5716.csv.gz  in=340,046,386 out=88,139,751 elapsed=433.6s

  [8872/13157] intraday_5713.csv.gz  in=340,058,410 out=88,151,775 elapsed=433.6s

  [8873/13157] intraday_5714.csv.gz  in=340,070,432 out=88,163,797 elapsed=433.6s

  [8874/13157] intraday_5715.csv.gz  in=340,102,413 out=88,180,585 elapsed=433.7s

  [8875/13157] intraday_5718.csv.gz  in=340,113,292 out=88,191,464 elapsed=433.7s

  [8876/13157] intraday_5717.csv.gz  in=340,127,050 out=88,205,075 elapsed=433.7s

  [8877/13157] intraday_5719.csv.gz  in=340,137,356 out=88,215,381 elapsed=433.7s

  [8878/13157] intraday_5721.csv.gz  in=340,149,894 out=88,227,919 elapsed=433.7s

  [8879/13157] intraday_5723.csv.gz  in=340,161,506 out=88,239,531 elapsed=433.7s

  [8880/13157] intraday_5720.csv.gz  in=340,172,607 out=88,250,632 elapsed=433.7s

  [8881/13157] intraday_5722.csv.gz  in=340,185,972 out=88,263,997 elapsed=433.8s

  [8882/13157] intraday_5724.csv.gz  in=340,199,449 out=88,277,474 elapsed=433.8s

  [8883/13157] intraday_5725.csv.gz  in=340,212,039 out=88,290,064 elapsed=433.8s

  [8884/13157] intraday_5726.csv.gz  in=340,224,001 out=88,302,026 elapsed=433.8s

  [8885/13157] intraday_5728.csv.gz  in=340,236,301 out=88,314,326 elapsed=433.8s

  [8886/13157] intraday_5727.csv.gz  in=340,247,708 out=88,325,733 elapsed=433.8s

  [8887/13157] intraday_5729.csv.gz  in=340,258,256 out=88,336,281 elapsed=433.9s

  [8888/13157] intraday_5730.csv.gz  in=340,271,940 out=88,348,022 elapsed=433.9s

  [8889/13157] intraday_5731.csv.gz  in=340,282,285 out=88,358,367 elapsed=433.9s

  [8890/13157] intraday_5732.csv.gz  in=340,297,498 out=88,373,580 elapsed=433.9s

  [8891/13157] intraday_5734.csv.gz  in=340,308,116 out=88,384,198 elapsed=434.1s

  [8892/13157] intraday_5736.csv.gz  in=340,321,126 out=88,397,208 elapsed=434.1s

  [8893/13157] intraday_5733.csv.gz  in=340,332,226 out=88,408,308 elapsed=434.1s

  [8894/13157] intraday_5735.csv.gz  in=340,346,697 out=88,422,779 elapsed=434.1s

  [8895/13157] intraday_5737.csv.gz  in=340,359,964 out=88,436,046 elapsed=434.2s

  [8896/13157] intraday_5739.csv.gz  in=340,373,093 out=88,449,175 elapsed=434.2s

  [8897/13157] intraday_5738.csv.gz  in=340,384,011 out=88,460,093 elapsed=434.2s

  [8898/13157] intraday_5740.csv.gz  in=340,396,404 out=88,472,486 elapsed=434.2s

  [8899/13157] intraday_5742.csv.gz  in=340,407,577 out=88,483,659 elapsed=434.3s

  [8900/13157] intraday_5744.csv.gz  in=340,418,208 out=88,494,290 elapsed=434.3s

  [8901/13157] intraday_5741.csv.gz  in=340,431,291 out=88,507,373 elapsed=434.3s

  [8902/13157] intraday_5743.csv.gz  in=340,445,717 out=88,518,585 elapsed=434.3s

  [8903/13157] intraday_5747.csv.gz  in=340,459,206 out=88,532,066 elapsed=434.5s

  [8904/13157] intraday_5748.csv.gz  in=340,472,617 out=88,545,477 elapsed=434.5s

  [8905/13157] intraday_5746.csv.gz  in=340,485,492 out=88,558,352 elapsed=434.5s

  [8906/13157] intraday_5745.csv.gz  in=340,501,330 out=88,574,190 elapsed=434.5s

  [8907/13157] intraday_5749.csv.gz  in=340,512,795 out=88,584,708 elapsed=434.6s

  [8908/13157] intraday_5751.csv.gz  in=340,524,754 out=88,596,667 elapsed=434.6s

  [8909/13157] intraday_5752.csv.gz  in=340,537,298 out=88,609,211 elapsed=434.7s

  [8910/13157] intraday_5750.csv.gz  in=340,548,909 out=88,620,822 elapsed=434.7s

  [8911/13157] intraday_5753.csv.gz  in=340,561,876 out=88,633,789 elapsed=434.7s

  [8912/13157] intraday_5754.csv.gz  in=340,572,993 out=88,644,906 elapsed=434.9s

  [8913/13157] intraday_5756.csv.gz  in=340,585,733 out=88,656,090 elapsed=434.9s

  [8914/13157] intraday_5757.csv.gz  in=340,598,830 out=88,669,187 elapsed=434.9s

  [8915/13157] intraday_5755.csv.gz  in=340,610,415 out=88,680,772 elapsed=434.9s

  [8916/13157] intraday_5760.csv.gz  in=340,620,454 out=88,690,811 elapsed=435.0s

  [8917/13157] intraday_5761.csv.gz  in=340,632,516 out=88,702,873 elapsed=435.0s

  [8918/13157] intraday_5758.csv.gz  in=340,643,184 out=88,713,541 elapsed=435.0s

  [8919/13157] intraday_5759.csv.gz  in=340,656,797 out=88,727,154 elapsed=435.0s

  [8920/13157] intraday_5762.csv.gz  in=340,669,389 out=88,739,746 elapsed=435.1s

  [8921/13157] intraday_5763.csv.gz  in=340,683,477 out=88,753,834 elapsed=435.1s

  [8922/13157] intraday_5765.csv.gz  in=340,696,612 out=88,766,969 elapsed=435.1s

  [8923/13157] intraday_5764.csv.gz  in=340,712,312 out=88,782,669 elapsed=435.1s

  [8924/13157] intraday_5767.csv.gz  in=340,723,794 out=88,794,151 elapsed=435.4s

  [8925/13157] intraday_5768.csv.gz  in=340,737,532 out=88,807,889 elapsed=435.4s

  [8926/13157] intraday_5769.csv.gz  in=340,754,158 out=88,824,515 elapsed=435.4s

  [8927/13157] intraday_5766.csv.gz  in=340,765,647 out=88,836,004 elapsed=435.4s

  [8928/13157] intraday_5772.csv.gz  in=340,778,432 out=88,848,789 elapsed=435.6s

  [8929/13157] intraday_5770.csv.gz  in=340,791,074 out=88,861,431 elapsed=435.6s

  [8930/13157] intraday_5773.csv.gz  in=340,804,554 out=88,874,911 elapsed=435.6s

  [8931/13157] intraday_5771.csv.gz  in=340,821,154 out=88,888,966 elapsed=435.6s

  [8932/13157] intraday_5776.csv.gz  in=340,833,268 out=88,901,080 elapsed=435.8s

  [8933/13157] intraday_5777.csv.gz  in=340,846,238 out=88,914,050 elapsed=435.8s

  [8934/13157] intraday_5775.csv.gz  in=340,858,592 out=88,926,404 elapsed=435.8s

  [8935/13157] intraday_5774.csv.gz  in=340,872,096 out=88,939,908 elapsed=435.8s

  [8936/13157] intraday_5778.csv.gz  in=340,884,276 out=88,952,088 elapsed=436.0s

  [8937/13157] intraday_5781.csv.gz  in=340,897,383 out=88,965,195 elapsed=436.0s

  [8938/13157] intraday_5779.csv.gz  in=340,911,292 out=88,979,104 elapsed=436.0s

  [8939/13157] intraday_5780.csv.gz  in=340,923,090 out=88,990,902 elapsed=436.0s

  [8940/13157] intraday_5783.csv.gz  in=340,935,784 out=89,003,596 elapsed=436.1s

  [8941/13157] intraday_5784.csv.gz  in=340,948,610 out=89,016,422 elapsed=436.1s

  [8942/13157] intraday_5782.csv.gz  in=340,967,501 out=89,029,959 elapsed=436.2s

  [8943/13157] intraday_5786.csv.gz  in=340,978,705 out=89,041,163 elapsed=436.2s

  [8944/13157] intraday_5787.csv.gz  in=340,992,465 out=89,054,923 elapsed=436.2s

  [8945/13157] intraday_5785.csv.gz  in=341,008,215 out=89,070,673 elapsed=436.2s

  [8946/13157] intraday_5788.csv.gz  in=341,022,728 out=89,085,186 elapsed=436.4s

  [8947/13157] intraday_5790.csv.gz  in=341,040,388 out=89,097,151 elapsed=436.4s

  [8948/13157] intraday_5789.csv.gz  in=341,055,954 out=89,112,717 elapsed=436.4s

  [8949/13157] intraday_5792.csv.gz  in=341,069,587 out=89,126,350 elapsed=436.4s

  [8950/13157] intraday_5791.csv.gz  in=341,081,921 out=89,138,684 elapsed=436.4s

  [8951/13157] intraday_5793.csv.gz  in=341,094,652 out=89,151,415 elapsed=436.4s

  [8952/13157] intraday_5794.csv.gz  in=341,108,433 out=89,165,196 elapsed=436.4s

  [8953/13157] intraday_5795.csv.gz  in=341,123,137 out=89,179,900 elapsed=436.5s

  [8954/13157] intraday_5798.csv.gz  in=341,136,724 out=89,193,487 elapsed=436.5s

  [8955/13157] intraday_5796.csv.gz  in=341,150,702 out=89,207,465 elapsed=436.5s

  [8956/13157] intraday_5797.csv.gz  in=341,165,536 out=89,222,299 elapsed=436.5s

  [8957/13157] intraday_5802.csv.gz  in=341,176,623 out=89,233,386 elapsed=436.6s

  [8958/13157] intraday_5799.csv.gz  in=341,188,871 out=89,245,634 elapsed=436.6s

  [8959/13157] intraday_5800.csv.gz  in=341,201,048 out=89,257,811 elapsed=436.6s

  [8960/13157] intraday_5801.csv.gz  in=341,214,086 out=89,270,849 elapsed=436.6s

  [8961/13157] intraday_5803.csv.gz  in=341,227,031 out=89,283,794 elapsed=437.5s

  [8962/13157] intraday_5804.csv.gz  in=341,239,466 out=89,296,229 elapsed=437.5s

  [8963/13157] intraday_5806.csv.gz  in=341,253,170 out=89,309,933 elapsed=437.6s

  [8964/13157] intraday_5805.csv.gz  in=341,267,747 out=89,324,510 elapsed=437.6s

  [8965/13157] intraday_5808.csv.gz  in=341,279,261 out=89,336,024 elapsed=437.6s

  [8966/13157] intraday_5810.csv.gz  in=341,290,817 out=89,347,580 elapsed=437.6s

  [8967/13157] intraday_5807.csv.gz  in=341,303,001 out=89,359,764 elapsed=437.6s

  [8968/13157] intraday_5809.csv.gz  in=341,316,711 out=89,373,474 elapsed=437.6s

  [8969/13157] intraday_5812.csv.gz  in=341,332,260 out=89,389,023 elapsed=437.7s

  [8970/13157] intraday_5813.csv.gz  in=341,346,467 out=89,403,230 elapsed=437.7s

  [8971/13157] intraday_5811.csv.gz  in=341,358,699 out=89,415,462 elapsed=437.7s

  [8972/13157] intraday_5814.csv.gz  in=341,373,438 out=89,428,835 elapsed=437.7s

  [8973/13157] intraday_5815.csv.gz  in=341,386,123 out=89,441,520 elapsed=437.8s

  [8974/13157] intraday_5816.csv.gz  in=341,397,541 out=89,452,938 elapsed=437.8s

  [8975/13157] intraday_5817.csv.gz  in=341,411,339 out=89,466,736 elapsed=437.8s

  [8976/13157] intraday_5818.csv.gz  in=341,422,256 out=89,477,653 elapsed=437.8s

  [8977/13157] intraday_5819.csv.gz  in=341,436,717 out=89,492,114 elapsed=437.9s

  [8978/13157] intraday_5820.csv.gz  in=341,444,163 out=89,499,560 elapsed=437.9s

  [8979/13157] intraday_5822.csv.gz  in=341,454,433 out=89,509,830 elapsed=437.9s

  [8980/13157] intraday_5821.csv.gz  in=341,463,566 out=89,518,963 elapsed=437.9s

  [8981/13157] intraday_5824.csv.gz  in=341,476,974 out=89,532,371 elapsed=438.0s

  [8982/13157] intraday_5823.csv.gz  in=341,493,010 out=89,548,407 elapsed=438.0s

  [8983/13157] intraday_5826.csv.gz  in=341,503,749 out=89,558,900 elapsed=438.2s

  [8984/13157] intraday_5825.csv.gz  in=341,515,410 out=89,570,561 elapsed=438.2s

  [8985/13157] intraday_5827.csv.gz  in=341,528,885 out=89,584,036 elapsed=438.2s

  [8986/13157] intraday_5828.csv.gz  in=341,544,679 out=89,599,830 elapsed=438.3s

  [8987/13157] intraday_5829.csv.gz  in=341,558,776 out=89,613,927 elapsed=438.4s

  [8988/13157] intraday_5832.csv.gz  in=341,572,247 out=89,627,398 elapsed=438.4s

  [8989/13157] intraday_5831.csv.gz  in=341,585,600 out=89,640,751 elapsed=438.4s

  [8990/13157] intraday_5830.csv.gz  in=341,597,192 out=89,652,343 elapsed=438.4s

  [8991/13157] intraday_5833.csv.gz  in=341,611,668 out=89,666,819 elapsed=438.6s

  [8992/13157] intraday_5834.csv.gz  in=341,625,351 out=89,680,502 elapsed=438.6s

  [8993/13157] intraday_5836.csv.gz  in=341,637,324 out=89,692,475 elapsed=438.6s

  [8994/13157] intraday_5835.csv.gz  in=341,649,440 out=89,704,591 elapsed=438.6s

  [8995/13157] intraday_5837.csv.gz  in=341,659,488 out=89,714,639 elapsed=438.7s

  [8996/13157] intraday_5838.csv.gz  in=341,676,043 out=89,725,108 elapsed=438.7s

  [8997/13157] intraday_5840.csv.gz  in=341,689,287 out=89,738,352 elapsed=438.7s

  [8998/13157] intraday_5839.csv.gz  in=341,703,282 out=89,752,347 elapsed=438.8s

  [8999/13157] intraday_5842.csv.gz  in=341,714,624 out=89,763,689 elapsed=438.8s

  [9000/13157] intraday_5844.csv.gz  in=341,727,891 out=89,776,956 elapsed=438.8s

  [9001/13157] intraday_5841.csv.gz  in=341,745,824 out=89,791,320 elapsed=438.8s

  [9002/13157] intraday_5843.csv.gz  in=341,758,210 out=89,803,706 elapsed=438.8s

  [9003/13157] intraday_5845.csv.gz  in=341,770,721 out=89,816,217 elapsed=438.8s

  [9004/13157] intraday_5846.csv.gz  in=341,782,877 out=89,828,373 elapsed=438.8s

  [9005/13157] intraday_5847.csv.gz  in=341,795,749 out=89,841,245 elapsed=438.8s

  [9006/13157] intraday_5848.csv.gz  in=341,806,804 out=89,852,300 elapsed=438.9s

  [9007/13157] intraday_5849.csv.gz  in=341,818,544 out=89,864,040 elapsed=438.9s

  [9008/13157] intraday_5850.csv.gz  in=341,830,456 out=89,875,952 elapsed=438.9s

  [9009/13157] intraday_5851.csv.gz  in=341,843,594 out=89,889,090 elapsed=438.9s

  [9010/13157] intraday_5852.csv.gz  in=341,857,569 out=89,903,065 elapsed=439.0s

  [9011/13157] intraday_5853.csv.gz  in=341,872,718 out=89,918,214 elapsed=439.0s

  [9012/13157] intraday_5855.csv.gz  in=341,884,838 out=89,930,334 elapsed=439.0s

  [9013/13157] intraday_5854.csv.gz  in=341,897,418 out=89,940,728 elapsed=439.0s

  [9014/13157] intraday_5858.csv.gz  in=341,907,943 out=89,951,253 elapsed=439.1s

  [9015/13157] intraday_5857.csv.gz  in=341,922,031 out=89,965,341 elapsed=439.1s

  [9016/13157] intraday_5859.csv.gz  in=341,934,188 out=89,977,498 elapsed=439.1s

  [9017/13157] intraday_5856.csv.gz  in=341,946,584 out=89,989,894 elapsed=439.1s

  [9018/13157] intraday_5860.csv.gz  in=341,958,153 out=90,001,463 elapsed=439.1s

  [9019/13157] intraday_5863.csv.gz  in=341,970,900 out=90,014,210 elapsed=439.2s

  [9020/13157] intraday_5862.csv.gz  in=341,981,948 out=90,025,124 elapsed=439.2s

  [9021/13157] intraday_5861.csv.gz  in=341,992,701 out=90,035,877 elapsed=439.2s

  [9022/13157] intraday_5864.csv.gz  in=342,004,599 out=90,047,775 elapsed=439.2s

  [9023/13157] intraday_5865.csv.gz  in=342,017,358 out=90,060,534 elapsed=439.2s

  [9024/13157] intraday_5866.csv.gz  in=342,030,821 out=90,073,997 elapsed=439.3s

  [9025/13157] intraday_5867.csv.gz  in=342,043,309 out=90,086,485 elapsed=439.3s

  [9026/13157] intraday_5868.csv.gz  in=342,055,530 out=90,098,706 elapsed=439.3s

  [9027/13157] intraday_5869.csv.gz  in=342,066,226 out=90,109,402 elapsed=439.9s

  [9028/13157] intraday_5871.csv.gz  in=342,077,748 out=90,120,924 elapsed=439.9s

  [9029/13157] intraday_5872.csv.gz  in=342,088,769 out=90,131,472 elapsed=439.9s

  [9030/13157] intraday_5870.csv.gz  in=342,100,322 out=90,143,025 elapsed=439.9s

  [9031/13157] intraday_5876.csv.gz  in=342,111,079 out=90,153,782 elapsed=440.0s

  [9032/13157] intraday_5873.csv.gz  in=342,122,094 out=90,164,797 elapsed=440.0s

  [9033/13157] intraday_5875.csv.gz  in=342,132,537 out=90,175,240 elapsed=440.0s

  [9034/13157] intraday_5874.csv.gz  in=342,147,026 out=90,189,729 elapsed=440.0s

  [9035/13157] intraday_5877.csv.gz  in=342,161,478 out=90,204,181 elapsed=440.1s

  [9036/13157] intraday_5878.csv.gz  in=342,174,361 out=90,217,064 elapsed=440.1s

  [9037/13157] intraday_5881.csv.gz  in=342,187,018 out=90,229,721 elapsed=440.2s

  [9038/13157] intraday_5880.csv.gz  in=342,198,779 out=90,241,482 elapsed=440.2s

  [9039/13157] intraday_5879.csv.gz  in=342,211,767 out=90,254,470 elapsed=440.2s

  [9040/13157] intraday_5882.csv.gz  in=342,224,347 out=90,267,050 elapsed=440.2s

  [9041/13157] intraday_5883.csv.gz  in=342,238,110 out=90,280,813 elapsed=440.2s

  [9042/13157] intraday_5885.csv.gz  in=342,248,454 out=90,291,157 elapsed=440.2s

  [9043/13157] intraday_5884.csv.gz  in=342,259,696 out=90,302,399 elapsed=440.2s

  [9044/13157] intraday_5886.csv.gz  in=342,271,053 out=90,313,756 elapsed=440.2s

  [9045/13157] intraday_5888.csv.gz  in=342,284,417 out=90,327,120 elapsed=440.3s

  [9046/13157] intraday_5890.csv.gz  in=342,296,903 out=90,339,606 elapsed=440.3s

  [9047/13157] intraday_5889.csv.gz  in=342,310,350 out=90,353,053 elapsed=440.3s

  [9048/13157] intraday_5887.csv.gz  in=342,325,918 out=90,368,621 elapsed=440.3s

  [9049/13157] intraday_5891.csv.gz  in=342,354,433 out=90,381,955 elapsed=440.3s

  [9050/13157] intraday_5893.csv.gz  in=342,366,036 out=90,393,558 elapsed=440.4s

  [9051/13157] intraday_5894.csv.gz  in=342,377,913 out=90,405,435 elapsed=440.4s

  [9052/13157] intraday_5892.csv.gz  in=342,397,641 out=90,417,774 elapsed=440.4s

  [9053/13157] intraday_5895.csv.gz  in=342,411,216 out=90,431,349 elapsed=440.4s

  [9054/13157] intraday_5899.csv.gz  in=342,424,940 out=90,445,073 elapsed=440.5s

  [9055/13157] intraday_5896.csv.gz  in=342,437,685 out=90,457,818 elapsed=440.5s

  [9056/13157] intraday_5897.csv.gz  in=342,449,387 out=90,469,520 elapsed=440.5s

  [9057/13157] intraday_5898.csv.gz  in=342,459,832 out=90,479,965 elapsed=440.5s

  [9058/13157] intraday_5900.csv.gz  in=342,470,888 out=90,491,021 elapsed=440.5s

  [9059/13157] intraday_5901.csv.gz  in=342,493,315 out=90,507,105 elapsed=440.6s

  [9060/13157] intraday_5902.csv.gz  in=342,502,658 out=90,516,448 elapsed=440.6s

  [9061/13157] intraday_5903.csv.gz  in=342,514,447 out=90,528,237 elapsed=440.6s

  [9062/13157] intraday_5904.csv.gz  in=342,526,965 out=90,540,755 elapsed=440.6s

  [9063/13157] intraday_5906.csv.gz  in=342,541,732 out=90,555,522 elapsed=440.6s

  [9064/13157] intraday_5907.csv.gz  in=342,555,758 out=90,569,548 elapsed=440.6s

  [9065/13157] intraday_5905.csv.gz  in=342,570,520 out=90,584,310 elapsed=440.6s

  [9066/13157] intraday_5909.csv.gz  in=342,582,847 out=90,596,637 elapsed=440.7s

  [9067/13157] intraday_5908.csv.gz  in=342,594,268 out=90,608,058 elapsed=440.7s

  [9068/13157] intraday_5910.csv.gz  in=342,607,807 out=90,621,597 elapsed=440.7s

  [9069/13157] intraday_5911.csv.gz  in=342,624,225 out=90,638,015 elapsed=440.7s

  [9070/13157] intraday_5912.csv.gz  in=342,637,341 out=90,651,131 elapsed=440.9s

  [9071/13157] intraday_5913.csv.gz  in=342,650,499 out=90,664,289 elapsed=441.0s

  [9072/13157] intraday_5915.csv.gz  in=342,665,016 out=90,678,622 elapsed=441.0s

  [9073/13157] intraday_5914.csv.gz  in=342,678,205 out=90,691,811 elapsed=441.0s

  [9074/13157] intraday_5919.csv.gz  in=342,691,149 out=90,704,755 elapsed=441.1s

  [9075/13157] intraday_5917.csv.gz  in=342,706,342 out=90,717,449 elapsed=441.1s

  [9076/13157] intraday_5916.csv.gz  in=342,719,843 out=90,730,950 elapsed=441.1s

  [9077/13157] intraday_5918.csv.gz  in=342,732,295 out=90,743,402 elapsed=441.1s

  [9078/13157] intraday_5920.csv.gz  in=342,744,267 out=90,755,374 elapsed=441.2s

  [9079/13157] intraday_5923.csv.gz  in=342,758,481 out=90,769,588 elapsed=441.2s

  [9080/13157] intraday_5921.csv.gz  in=342,773,025 out=90,783,757 elapsed=441.3s

  [9081/13157] intraday_5922.csv.gz  in=342,785,204 out=90,795,197 elapsed=441.3s

  [9082/13157] intraday_5925.csv.gz  in=342,798,712 out=90,808,705 elapsed=441.3s

  [9083/13157] intraday_5924.csv.gz  in=342,811,832 out=90,821,825 elapsed=441.3s

  [9084/13157] intraday_5926.csv.gz  in=342,829,027 out=90,834,690 elapsed=441.3s

  [9085/13157] intraday_5927.csv.gz  in=342,843,663 out=90,849,326 elapsed=441.3s

  [9086/13157] intraday_5928.csv.gz  in=342,857,297 out=90,862,960 elapsed=441.4s

  [9087/13157] intraday_5929.csv.gz  in=342,869,913 out=90,875,576 elapsed=441.4s

  [9088/13157] intraday_5930.csv.gz  in=342,883,517 out=90,889,180 elapsed=441.4s

  [9089/13157] intraday_5931.csv.gz  in=342,900,936 out=90,904,666 elapsed=441.4s

  [9090/13157] intraday_5933.csv.gz  in=342,913,047 out=90,916,777 elapsed=441.4s

  [9091/13157] intraday_5934.csv.gz  in=342,926,432 out=90,930,162 elapsed=441.4s

  [9092/13157] intraday_5932.csv.gz  in=342,938,209 out=90,941,939 elapsed=441.5s

  [9093/13157] intraday_5936.csv.gz  in=342,952,156 out=90,955,886 elapsed=441.5s

  [9094/13157] intraday_5935.csv.gz  in=342,964,267 out=90,967,997 elapsed=441.5s

  [9095/13157] intraday_5937.csv.gz  in=342,978,713 out=90,982,443 elapsed=441.5s

  [9096/13157] intraday_5938.csv.gz  in=342,993,082 out=90,996,812 elapsed=441.5s

  [9097/13157] intraday_5942.csv.gz  in=343,005,955 out=91,009,685 elapsed=441.6s

  [9098/13157] intraday_5940.csv.gz  in=343,020,322 out=91,022,844 elapsed=441.6s

  [9099/13157] intraday_5939.csv.gz  in=343,035,270 out=91,037,792 elapsed=441.6s

  [9100/13157] intraday_5941.csv.gz  in=343,047,033 out=91,049,555 elapsed=441.6s

  [9101/13157] intraday_5943.csv.gz  in=343,058,941 out=91,061,463 elapsed=441.7s

  [9102/13157] intraday_5946.csv.gz  in=343,071,454 out=91,073,976 elapsed=441.7s

  [9103/13157] intraday_5945.csv.gz  in=343,083,503 out=91,086,025 elapsed=441.7s

  [9104/13157] intraday_5944.csv.gz  in=343,095,424 out=91,097,946 elapsed=441.7s

  [9105/13157] intraday_5949.csv.gz  in=343,106,805 out=91,109,327 elapsed=441.8s

  [9106/13157] intraday_5950.csv.gz  in=343,118,591 out=91,121,113 elapsed=441.8s

  [9107/13157] intraday_5947.csv.gz  in=343,132,096 out=91,134,618 elapsed=441.8s

  [9108/13157] intraday_5948.csv.gz  in=343,147,892 out=91,150,414 elapsed=441.8s

  [9109/13157] intraday_5953.csv.gz  in=343,160,246 out=91,162,768 elapsed=441.9s

  [9110/13157] intraday_5951.csv.gz  in=343,174,147 out=91,176,669 elapsed=441.9s

  [9111/13157] intraday_5952.csv.gz  in=343,186,651 out=91,188,937 elapsed=441.9s

  [9112/13157] intraday_5954.csv.gz  in=343,203,686 out=91,204,485 elapsed=441.9s

  [9113/13157] intraday_5955.csv.gz  in=343,217,399 out=91,218,198 elapsed=442.0s

  [9114/13157] intraday_5958.csv.gz  in=343,229,411 out=91,230,210 elapsed=442.0s

  [9115/13157] intraday_5956.csv.gz  in=343,243,382 out=91,244,181 elapsed=442.0s

  [9116/13157] intraday_5957.csv.gz  in=343,255,829 out=91,256,628 elapsed=442.0s

  [9117/13157] intraday_5961.csv.gz  in=343,269,840 out=91,270,639 elapsed=442.1s

  [9118/13157] intraday_5960.csv.gz  in=343,280,783 out=91,281,582 elapsed=442.1s

  [9119/13157] intraday_5959.csv.gz  in=343,295,235 out=91,296,034 elapsed=442.1s

  [9120/13157] intraday_5962.csv.gz  in=343,304,103 out=91,304,902 elapsed=442.1s

  [9121/13157] intraday_5963.csv.gz  in=343,312,540 out=91,313,339 elapsed=442.4s

  [9122/13157] intraday_5964.csv.gz  in=343,323,354 out=91,324,153 elapsed=442.5s

  [9123/13157] intraday_5965.csv.gz  in=343,338,691 out=91,339,490 elapsed=442.6s

  [9124/13157] intraday_5966.csv.gz  in=343,357,343 out=91,352,538 elapsed=442.6s

  [9125/13157] intraday_5967.csv.gz  in=343,370,862 out=91,366,057 elapsed=442.6s

  [9126/13157] intraday_5968.csv.gz  in=343,380,972 out=91,376,167 elapsed=442.6s

  [9127/13157] intraday_5969.csv.gz  in=343,394,145 out=91,389,340 elapsed=442.7s

  [9128/13157] intraday_5971.csv.gz  in=343,408,695 out=91,403,890 elapsed=442.7s

  [9129/13157] intraday_5970.csv.gz  in=343,422,907 out=91,418,102 elapsed=442.7s

  [9130/13157] intraday_5972.csv.gz  in=343,433,195 out=91,428,390 elapsed=442.7s

  [9131/13157] intraday_5973.csv.gz  in=343,446,135 out=91,441,330 elapsed=442.8s

  [9132/13157] intraday_5974.csv.gz  in=343,460,592 out=91,455,787 elapsed=442.8s

  [9133/13157] intraday_5975.csv.gz  in=343,474,668 out=91,469,863 elapsed=442.8s

  [9134/13157] intraday_5976.csv.gz  in=343,487,271 out=91,482,053 elapsed=442.8s

  [9135/13157] intraday_5980.csv.gz  in=343,496,207 out=91,490,989 elapsed=442.9s

  [9136/13157] intraday_5978.csv.gz  in=343,508,308 out=91,503,090 elapsed=442.9s

  [9137/13157] intraday_5977.csv.gz  in=343,523,265 out=91,515,964 elapsed=442.9s

  [9138/13157] intraday_5979.csv.gz  in=343,534,160 out=91,526,859 elapsed=442.9s

  [9139/13157] intraday_5983.csv.gz  in=343,544,247 out=91,536,946 elapsed=443.0s

  [9140/13157] intraday_5984.csv.gz  in=343,562,927 out=91,550,534 elapsed=443.0s

  [9141/13157] intraday_5981.csv.gz  in=343,576,982 out=91,564,589 elapsed=443.0s

  [9142/13157] intraday_5982.csv.gz  in=343,589,763 out=91,577,370 elapsed=443.0s

  [9143/13157] intraday_5988.csv.gz  in=343,602,691 out=91,590,298 elapsed=443.0s

  [9144/13157] intraday_5986.csv.gz  in=343,616,024 out=91,603,631 elapsed=443.1s

  [9145/13157] intraday_5985.csv.gz  in=343,628,861 out=91,616,468 elapsed=443.1s

  [9146/13157] intraday_5987.csv.gz  in=343,644,728 out=91,628,883 elapsed=443.1s

  [9147/13157] intraday_5989.csv.gz  in=343,656,720 out=91,640,875 elapsed=443.1s

  [9148/13157] intraday_5991.csv.gz  in=343,667,591 out=91,651,746 elapsed=443.5s

  [9149/13157] intraday_5993.csv.gz  in=343,679,612 out=91,663,767 elapsed=443.5s

  [9150/13157] intraday_5990.csv.gz  in=343,691,253 out=91,675,103 elapsed=443.5s

  [9151/13157] intraday_5992.csv.gz  in=343,703,548 out=91,687,398 elapsed=443.5s

  [9152/13157] intraday_5997.csv.gz  in=343,714,470 out=91,698,320 elapsed=444.1s

  [9153/13157] intraday_5996.csv.gz  in=343,726,412 out=91,710,262 elapsed=444.2s

  [9154/13157] intraday_5994.csv.gz  in=343,738,177 out=91,722,027 elapsed=444.2s

  [9155/13157] intraday_5995.csv.gz  in=343,754,010 out=91,737,860 elapsed=444.2s

  [9156/13157] intraday_5998.csv.gz  in=343,766,425 out=91,750,275 elapsed=444.2s

  [9157/13157] intraday_5999.csv.gz  in=343,779,103 out=91,762,953 elapsed=444.2s

  [9158/13157] intraday_6000.csv.gz  in=343,789,791 out=91,773,641 elapsed=444.2s

  [9159/13157] intraday_6001.csv.gz  in=343,813,141 out=91,787,880 elapsed=444.2s

  [9160/13157] intraday_6002.csv.gz  in=343,822,232 out=91,796,971 elapsed=444.2s

  [9161/13157] intraday_6004.csv.gz  in=343,832,086 out=91,806,825 elapsed=444.3s

  [9162/13157] intraday_6003.csv.gz  in=343,843,914 out=91,818,653 elapsed=444.3s

  [9163/13157] intraday_6005.csv.gz  in=343,855,153 out=91,829,892 elapsed=444.3s

  [9164/13157] intraday_6006.csv.gz  in=343,868,186 out=91,842,925 elapsed=444.3s

  [9165/13157] intraday_6008.csv.gz  in=343,882,030 out=91,855,383 elapsed=444.4s

  [9166/13157] intraday_6007.csv.gz  in=343,893,859 out=91,867,212 elapsed=444.4s

  [9167/13157] intraday_6010.csv.gz  in=343,904,453 out=91,877,806 elapsed=444.4s

  [9168/13157] intraday_6009.csv.gz  in=343,923,691 out=91,892,887 elapsed=444.4s

  [9169/13157] intraday_6011.csv.gz  in=343,935,821 out=91,905,017 elapsed=444.4s

  [9170/13157] intraday_6012.csv.gz  in=343,949,250 out=91,916,915 elapsed=444.4s

  [9171/13157] intraday_6014.csv.gz  in=343,961,921 out=91,928,742 elapsed=444.5s

  [9172/13157] intraday_6013.csv.gz  in=343,975,123 out=91,939,722 elapsed=444.5s

  [9173/13157] intraday_6016.csv.gz  in=343,987,941 out=91,952,540 elapsed=444.5s

  [9174/13157] intraday_6015.csv.gz  in=343,999,527 out=91,964,126 elapsed=444.5s

  [9175/13157] intraday_6017.csv.gz  in=344,011,946 out=91,976,545 elapsed=444.6s

  [9176/13157] intraday_6018.csv.gz  in=344,023,510 out=91,988,109 elapsed=444.6s

  [9177/13157] intraday_6020.csv.gz  in=344,036,107 out=92,000,706 elapsed=444.6s

  [9178/13157] intraday_6019.csv.gz  in=344,048,833 out=92,013,432 elapsed=444.6s

  [9179/13157] intraday_6024.csv.gz  in=344,061,269 out=92,025,868 elapsed=444.7s

  [9180/13157] intraday_6021.csv.gz  in=344,073,563 out=92,038,162 elapsed=444.7s

  [9181/13157] intraday_6022.csv.gz  in=344,086,730 out=92,049,050 elapsed=444.7s

  [9182/13157] intraday_6023.csv.gz  in=344,112,599 out=92,064,056 elapsed=444.7s

  [9183/13157] intraday_6027.csv.gz  in=344,125,167 out=92,076,624 elapsed=445.2s

  [9184/13157] intraday_6028.csv.gz  in=344,134,620 out=92,086,077 elapsed=445.2s

  [9185/13157] intraday_6026.csv.gz  in=344,147,667 out=92,099,124 elapsed=445.3s

  [9186/13157] intraday_6025.csv.gz  in=344,159,427 out=92,110,884 elapsed=445.3s

  [9187/13157] intraday_6029.csv.gz  in=344,173,912 out=92,125,369 elapsed=445.4s

  [9188/13157] intraday_6030.csv.gz  in=344,189,971 out=92,141,428 elapsed=445.4s

  [9189/13157] intraday_6031.csv.gz  in=344,199,846 out=92,151,303 elapsed=445.4s

  [9190/13157] intraday_6032.csv.gz  in=344,212,418 out=92,163,875 elapsed=445.4s

  [9191/13157] intraday_6035.csv.gz  in=344,224,232 out=92,175,689 elapsed=445.5s

  [9192/13157] intraday_6034.csv.gz  in=344,234,880 out=92,186,337 elapsed=445.5s

  [9193/13157] intraday_6036.csv.gz  in=344,245,967 out=92,197,424 elapsed=445.5s

  [9194/13157] intraday_6033.csv.gz  in=344,258,364 out=92,209,821 elapsed=445.5s

  [9195/13157] intraday_6039.csv.gz  in=344,271,442 out=92,222,899 elapsed=445.7s

  [9196/13157] intraday_6040.csv.gz  in=344,280,644 out=92,232,101 elapsed=445.7s

  [9197/13157] intraday_6037.csv.gz  in=344,294,267 out=92,245,724 elapsed=445.7s

  [9198/13157] intraday_6038.csv.gz  in=344,306,152 out=92,257,609 elapsed=445.7s

  [9199/13157] intraday_6041.csv.gz  in=344,318,587 out=92,270,044 elapsed=445.8s

  [9200/13157] intraday_6044.csv.gz  in=344,330,409 out=92,281,866 elapsed=445.8s

  [9201/13157] intraday_6042.csv.gz  in=344,342,342 out=92,293,799 elapsed=445.9s

  [9202/13157] intraday_6043.csv.gz  in=344,352,698 out=92,304,155 elapsed=445.9s

  [9203/13157] intraday_6045.csv.gz  in=344,361,789 out=92,313,246 elapsed=445.9s

  [9204/13157] intraday_6046.csv.gz  in=344,372,342 out=92,323,799 elapsed=445.9s

  [9205/13157] intraday_6047.csv.gz  in=344,386,437 out=92,337,894 elapsed=445.9s

  [9206/13157] intraday_6048.csv.gz  in=344,404,022 out=92,355,479 elapsed=445.9s

  [9207/13157] intraday_6051.csv.gz  in=344,414,334 out=92,365,791 elapsed=446.0s

  [9208/13157] intraday_6050.csv.gz  in=344,426,452 out=92,377,909 elapsed=446.0s

  [9209/13157] intraday_6049.csv.gz  in=344,437,958 out=92,389,415 elapsed=446.0s

  [9210/13157] intraday_6052.csv.gz  in=344,453,583 out=92,404,931 elapsed=446.0s

  [9211/13157] intraday_6056.csv.gz  in=344,466,285 out=92,417,633 elapsed=446.1s

  [9212/13157] intraday_6053.csv.gz  in=344,477,547 out=92,428,895 elapsed=446.1s

  [9213/13157] intraday_6054.csv.gz  in=344,493,328 out=92,444,676 elapsed=446.1s

  [9214/13157] intraday_6055.csv.gz  in=344,505,091 out=92,456,439 elapsed=446.1s

  [9215/13157] intraday_6057.csv.gz  in=344,518,276 out=92,469,624 elapsed=446.1s

  [9216/13157] intraday_6059.csv.gz  in=344,530,328 out=92,481,676 elapsed=446.1s

  [9217/13157] intraday_6058.csv.gz  in=344,551,243 out=92,497,133 elapsed=446.2s

  [9218/13157] intraday_6060.csv.gz  in=344,563,970 out=92,509,860 elapsed=446.2s

  [9219/13157] intraday_6061.csv.gz  in=344,577,131 out=92,523,021 elapsed=446.5s

  [9220/13157] intraday_6064.csv.gz  in=344,589,905 out=92,535,067 elapsed=446.5s

  [9221/13157] intraday_6063.csv.gz  in=344,603,303 out=92,548,465 elapsed=446.5s

  [9222/13157] intraday_6062.csv.gz  in=344,614,968 out=92,560,130 elapsed=446.5s

  [9223/13157] intraday_6066.csv.gz  in=344,630,019 out=92,575,181 elapsed=446.6s

  [9224/13157] intraday_6067.csv.gz  in=344,645,841 out=92,591,003 elapsed=446.6s

  [9225/13157] intraday_6068.csv.gz  in=344,656,228 out=92,601,390 elapsed=446.6s

  [9226/13157] intraday_6065.csv.gz  in=344,669,025 out=92,614,187 elapsed=446.6s

  [9227/13157] intraday_6071.csv.gz  in=344,678,969 out=92,624,131 elapsed=446.7s

  [9228/13157] intraday_6072.csv.gz  in=344,690,102 out=92,635,264 elapsed=446.7s

  [9229/13157] intraday_6069.csv.gz  in=344,702,162 out=92,647,324 elapsed=446.7s

  [9230/13157] intraday_6070.csv.gz  in=344,720,555 out=92,665,717 elapsed=446.7s

  [9231/13157] intraday_6073.csv.gz  in=344,736,096 out=92,681,258 elapsed=446.8s

  [9232/13157] intraday_6076.csv.gz  in=344,748,706 out=92,693,868 elapsed=446.9s

  [9233/13157] intraday_6075.csv.gz  in=344,762,038 out=92,707,200 elapsed=446.9s

  [9234/13157] intraday_6074.csv.gz  in=344,775,414 out=92,720,576 elapsed=446.9s

  [9235/13157] intraday_6077.csv.gz  in=344,787,574 out=92,732,736 elapsed=447.0s

  [9236/13157] intraday_6079.csv.gz  in=344,802,290 out=92,747,452 elapsed=447.0s

  [9237/13157] intraday_6080.csv.gz  in=344,813,986 out=92,759,148 elapsed=447.0s

  [9238/13157] intraday_6078.csv.gz  in=344,826,250 out=92,771,412 elapsed=447.0s

  [9239/13157] intraday_6082.csv.gz  in=344,842,173 out=92,787,335 elapsed=447.2s

  [9240/13157] intraday_6083.csv.gz  in=344,854,789 out=92,799,951 elapsed=447.2s

  [9241/13157] intraday_6081.csv.gz  in=344,868,816 out=92,813,978 elapsed=447.2s

  [9242/13157] intraday_6084.csv.gz  in=344,879,878 out=92,825,040 elapsed=447.2s

  [9243/13157] intraday_6085.csv.gz  in=344,891,258 out=92,836,420 elapsed=447.3s

  [9244/13157] intraday_6087.csv.gz  in=344,902,388 out=92,847,550 elapsed=447.3s

  [9245/13157] intraday_6086.csv.gz  in=344,915,847 out=92,861,009 elapsed=447.3s

  [9246/13157] intraday_6088.csv.gz  in=344,929,271 out=92,874,433 elapsed=447.4s

  [9247/13157] intraday_6089.csv.gz  in=344,947,276 out=92,886,866 elapsed=447.4s

  [9248/13157] intraday_6090.csv.gz  in=344,963,018 out=92,902,608 elapsed=447.4s

  [9249/13157] intraday_6091.csv.gz  in=344,975,558 out=92,915,148 elapsed=447.4s

  [9250/13157] intraday_6092.csv.gz  in=344,987,092 out=92,926,682 elapsed=447.4s

  [9251/13157] intraday_6095.csv.gz  in=344,999,418 out=92,939,008 elapsed=447.5s

  [9252/13157] intraday_6096.csv.gz  in=345,011,568 out=92,951,158 elapsed=447.5s

  [9253/13157] intraday_6094.csv.gz  in=345,023,199 out=92,962,789 elapsed=447.5s

  [9254/13157] intraday_6093.csv.gz  in=345,035,293 out=92,974,883 elapsed=447.5s

  [9255/13157] intraday_6098.csv.gz  in=345,049,278 out=92,988,868 elapsed=448.0s

  [9256/13157] intraday_6097.csv.gz  in=345,068,063 out=93,004,275 elapsed=448.0s

  [9257/13157] intraday_6099.csv.gz  in=345,081,023 out=93,017,235 elapsed=448.0s

  [9258/13157] intraday_6100.csv.gz  in=345,093,221 out=93,029,433 elapsed=448.0s

  [9259/13157] intraday_6101.csv.gz  in=345,105,019 out=93,041,231 elapsed=448.0s

  [9260/13157] intraday_6103.csv.gz  in=345,116,056 out=93,052,268 elapsed=448.1s

  [9261/13157] intraday_6105.csv.gz  in=345,124,389 out=93,060,601 elapsed=448.1s

  [9262/13157] intraday_6104.csv.gz  in=345,138,983 out=93,075,195 elapsed=448.1s

  [9263/13157] intraday_6102.csv.gz  in=345,152,369 out=93,088,581 elapsed=448.1s

  [9264/13157] intraday_6109.csv.gz  in=345,152,389 out=93,088,581 elapsed=448.1s

  [9265/13157] intraday_6110.csv.gz  in=345,152,406 out=93,088,598 elapsed=448.1s

  [9266/13157] intraday_6111.csv.gz  in=345,152,421 out=93,088,613 elapsed=448.1s

  [9267/13157] intraday_6108.csv.gz  in=345,152,499 out=93,088,691 elapsed=448.1s

  [9268/13157] intraday_6112.csv.gz  in=345,155,681 out=93,089,297 elapsed=448.2s

  [9269/13157] intraday_6106.csv.gz  in=345,164,915 out=93,098,531 elapsed=448.2s

  [9270/13157] intraday_6113.csv.gz  in=345,168,545 out=93,099,258 elapsed=448.2s

  [9271/13157] intraday_6107.csv.gz  in=345,177,453 out=93,108,166 elapsed=448.2s

  [9272/13157] intraday_6115.csv.gz  in=345,182,945 out=93,108,677 elapsed=448.2s

  [9273/13157] intraday_6116.csv.gz  in=345,184,292 out=93,109,273 elapsed=448.2s

  [9274/13157] intraday_6118.csv.gz  in=345,185,561 out=93,109,814 elapsed=448.2s

  [9275/13157] intraday_6114.csv.gz  in=345,197,900 out=93,111,602 elapsed=448.2s

  [9276/13157] intraday_6117.csv.gz  in=345,198,839 out=93,112,116 elapsed=448.2s

  [9277/13157] intraday_6120.csv.gz  in=345,200,194 out=93,112,318 elapsed=448.2s

  [9278/13157] intraday_6119.csv.gz  in=345,208,286 out=93,113,563 elapsed=448.2s

  [9279/13157] intraday_6121.csv.gz  in=345,208,607 out=93,113,817 elapsed=448.3s

  [9280/13157] intraday_6122.csv.gz  in=345,208,648 out=93,113,858 elapsed=448.3s

  [9281/13157] intraday_6124.csv.gz  in=345,208,669 out=93,113,879 elapsed=448.3s

  [9282/13157] intraday_6126.csv.gz  in=345,208,783 out=93,113,993 elapsed=448.3s

  [9283/13157] intraday_6123.csv.gz  in=345,211,131 out=93,114,553 elapsed=448.3s

  [9284/13157] intraday_6125.csv.gz  in=345,211,681 out=93,114,615 elapsed=448.3s

  [9285/13157] intraday_6127.csv.gz  in=345,220,910 out=93,115,989 elapsed=448.3s

  [9286/13157] intraday_6129.csv.gz  in=345,233,727 out=93,128,806 elapsed=448.3s

  [9287/13157] intraday_6128.csv.gz  in=345,250,361 out=93,145,440 elapsed=448.3s

  [9288/13157] intraday_6131.csv.gz  in=345,261,786 out=93,156,815 elapsed=448.3s

  [9289/13157] intraday_6130.csv.gz  in=345,276,127 out=93,171,156 elapsed=448.3s

  [9290/13157] intraday_6133.csv.gz  in=345,291,312 out=93,186,341 elapsed=448.4s

  [9291/13157] intraday_6132.csv.gz  in=345,304,342 out=93,199,371 elapsed=448.4s

  [9292/13157] intraday_6134.csv.gz  in=345,321,281 out=93,216,310 elapsed=448.4s

  [9293/13157] intraday_6136.csv.gz  in=345,335,353 out=93,230,382 elapsed=448.4s

  [9294/13157] intraday_6135.csv.gz  in=345,346,671 out=93,241,700 elapsed=448.4s

  [9295/13157] intraday_6137.csv.gz  in=345,362,612 out=93,257,641 elapsed=448.4s

  [9296/13157] intraday_6138.csv.gz  in=345,377,470 out=93,272,499 elapsed=448.4s

  [9297/13157] intraday_6140.csv.gz  in=345,390,308 out=93,285,337 elapsed=448.5s

  [9298/13157] intraday_6139.csv.gz  in=345,403,712 out=93,298,741 elapsed=448.5s

  [9299/13157] intraday_6142.csv.gz  in=345,413,796 out=93,308,825 elapsed=448.5s

  [9300/13157] intraday_6141.csv.gz  in=345,426,298 out=93,321,327 elapsed=448.5s

  [9301/13157] intraday_6143.csv.gz  in=345,435,255 out=93,330,284 elapsed=448.6s

  [9302/13157] intraday_6146.csv.gz  in=345,446,340 out=93,341,369 elapsed=448.6s

  [9303/13157] intraday_6145.csv.gz  in=345,460,364 out=93,355,393 elapsed=448.6s

  [9304/13157] intraday_6144.csv.gz  in=345,474,808 out=93,369,837 elapsed=448.6s

  [9305/13157] intraday_6149.csv.gz  in=345,488,276 out=93,383,305 elapsed=448.7s

  [9306/13157] intraday_6147.csv.gz  in=345,500,598 out=93,395,627 elapsed=448.7s

  [9307/13157] intraday_6150.csv.gz  in=345,514,219 out=93,409,248 elapsed=448.7s

  [9308/13157] intraday_6148.csv.gz  in=345,542,626 out=93,426,105 elapsed=448.7s

  [9309/13157] intraday_6153.csv.gz  in=345,554,428 out=93,437,907 elapsed=448.7s

  [9310/13157] intraday_6151.csv.gz  in=345,567,755 out=93,451,234 elapsed=448.7s

  [9311/13157] intraday_6152.csv.gz  in=345,580,624 out=93,464,103 elapsed=448.7s

  [9312/13157] intraday_6154.csv.gz  in=345,591,446 out=93,474,925 elapsed=448.7s

  [9313/13157] intraday_6155.csv.gz  in=345,603,809 out=93,487,288 elapsed=448.8s

  [9314/13157] intraday_6158.csv.gz  in=345,619,138 out=93,502,617 elapsed=448.8s

  [9315/13157] intraday_6157.csv.gz  in=345,634,589 out=93,518,068 elapsed=448.8s

  [9316/13157] intraday_6156.csv.gz  in=345,648,781 out=93,532,260 elapsed=448.8s

  [9317/13157] intraday_6159.csv.gz  in=345,660,098 out=93,543,577 elapsed=448.9s

  [9318/13157] intraday_6160.csv.gz  in=345,671,883 out=93,555,362 elapsed=448.9s

  [9319/13157] intraday_6161.csv.gz  in=345,684,640 out=93,568,119 elapsed=449.0s

  [9320/13157] intraday_6162.csv.gz  in=345,699,476 out=93,582,955 elapsed=449.2s

  [9321/13157] intraday_6164.csv.gz  in=345,712,363 out=93,595,842 elapsed=449.6s

  [9322/13157] intraday_6163.csv.gz  in=345,723,736 out=93,607,215 elapsed=449.6s

  [9323/13157] intraday_6165.csv.gz  in=345,734,601 out=93,618,080 elapsed=449.6s

  [9324/13157] intraday_6166.csv.gz  in=345,746,439 out=93,629,918 elapsed=449.6s

  [9325/13157] intraday_6170.csv.gz  in=345,758,770 out=93,642,249 elapsed=449.6s

  [9326/13157] intraday_6167.csv.gz  in=345,769,539 out=93,653,018 elapsed=449.7s

  [9327/13157] intraday_6168.csv.gz  in=345,781,812 out=93,665,291 elapsed=449.7s

  [9328/13157] intraday_6169.csv.gz  in=345,795,015 out=93,678,494 elapsed=449.7s

  [9329/13157] intraday_6171.csv.gz  in=345,808,526 out=93,692,005 elapsed=449.7s

  [9330/13157] intraday_6173.csv.gz  in=345,820,388 out=93,703,867 elapsed=449.7s

  [9331/13157] intraday_6172.csv.gz  in=345,833,389 out=93,716,868 elapsed=449.7s

  [9332/13157] intraday_6174.csv.gz  in=345,846,131 out=93,729,610 elapsed=449.7s

  [9333/13157] intraday_6175.csv.gz  in=345,858,813 out=93,742,292 elapsed=449.7s

  [9334/13157] intraday_6178.csv.gz  in=345,870,727 out=93,754,206 elapsed=449.8s

  [9335/13157] intraday_6176.csv.gz  in=345,881,495 out=93,764,974 elapsed=449.8s

  [9336/13157] intraday_6179.csv.gz  in=345,895,104 out=93,778,583 elapsed=449.8s

  [9337/13157] intraday_6177.csv.gz  in=345,907,587 out=93,791,066 elapsed=449.8s

  [9338/13157] intraday_6180.csv.gz  in=345,921,044 out=93,804,523 elapsed=449.8s

  [9339/13157] intraday_6181.csv.gz  in=345,932,824 out=93,816,303 elapsed=449.8s

  [9340/13157] intraday_6183.csv.gz  in=345,945,788 out=93,829,267 elapsed=449.9s

  [9341/13157] intraday_6182.csv.gz  in=345,960,237 out=93,843,716 elapsed=449.9s

  [9342/13157] intraday_6184.csv.gz  in=345,973,001 out=93,856,480 elapsed=449.9s

  [9343/13157] intraday_6185.csv.gz  in=345,986,287 out=93,868,666 elapsed=449.9s

  [9344/13157] intraday_6187.csv.gz  in=346,000,100 out=93,882,479 elapsed=449.9s

  [9345/13157] intraday_6189.csv.gz  in=346,012,678 out=93,895,057 elapsed=449.9s

  [9346/13157] intraday_6186.csv.gz  in=346,026,947 out=93,909,326 elapsed=449.9s

  [9347/13157] intraday_6188.csv.gz  in=346,039,255 out=93,921,634 elapsed=449.9s

  [9348/13157] intraday_6191.csv.gz  in=346,049,775 out=93,932,154 elapsed=450.0s

  [9349/13157] intraday_6190.csv.gz  in=346,062,097 out=93,944,476 elapsed=450.0s

  [9350/13157] intraday_6193.csv.gz  in=346,077,014 out=93,959,393 elapsed=450.0s

  [9351/13157] intraday_6194.csv.gz  in=346,089,658 out=93,972,037 elapsed=450.0s

  [9352/13157] intraday_6192.csv.gz  in=346,104,904 out=93,987,283 elapsed=450.0s

  [9353/13157] intraday_6195.csv.gz  in=346,117,491 out=93,999,870 elapsed=450.1s

  [9354/13157] intraday_6196.csv.gz  in=346,130,153 out=94,012,532 elapsed=450.1s

  [9355/13157] intraday_6197.csv.gz  in=346,140,558 out=94,022,937 elapsed=450.1s

  [9356/13157] intraday_6198.csv.gz  in=346,153,021 out=94,035,400 elapsed=450.1s

  [9357/13157] intraday_6199.csv.gz  in=346,165,913 out=94,048,292 elapsed=450.1s

  [9358/13157] intraday_6200.csv.gz  in=346,180,068 out=94,062,447 elapsed=450.1s

  [9359/13157] intraday_6201.csv.gz  in=346,191,191 out=94,073,570 elapsed=450.2s

  [9360/13157] intraday_6202.csv.gz  in=346,204,684 out=94,087,063 elapsed=450.2s

  [9361/13157] intraday_6203.csv.gz  in=346,215,037 out=94,097,416 elapsed=450.2s

  [9362/13157] intraday_6205.csv.gz  in=346,226,336 out=94,108,715 elapsed=450.2s

  [9363/13157] intraday_6204.csv.gz  in=346,240,971 out=94,123,350 elapsed=450.2s

  [9364/13157] intraday_6207.csv.gz  in=346,250,842 out=94,133,221 elapsed=450.2s

  [9365/13157] intraday_6206.csv.gz  in=346,265,492 out=94,147,871 elapsed=450.2s

  [9366/13157] intraday_6208.csv.gz  in=346,277,024 out=94,159,403 elapsed=450.4s

  [9367/13157] intraday_6209.csv.gz  in=346,289,387 out=94,171,766 elapsed=450.4s

  [9368/13157] intraday_6212.csv.gz  in=346,302,119 out=94,184,498 elapsed=450.5s

  [9369/13157] intraday_6210.csv.gz  in=346,318,295 out=94,200,674 elapsed=450.5s

  [9370/13157] intraday_6213.csv.gz  in=346,330,662 out=94,213,041 elapsed=450.5s

  [9371/13157] intraday_6211.csv.gz  in=346,347,306 out=94,229,685 elapsed=450.5s

  [9372/13157] intraday_6214.csv.gz  in=346,359,241 out=94,241,620 elapsed=450.5s

  [9373/13157] intraday_6215.csv.gz  in=346,373,450 out=94,255,829 elapsed=450.5s

  [9374/13157] intraday_6217.csv.gz  in=346,387,663 out=94,270,042 elapsed=450.5s

  [9375/13157] intraday_6216.csv.gz  in=346,402,612 out=94,284,991 elapsed=450.5s

  [9376/13157] intraday_6218.csv.gz  in=346,414,635 out=94,297,014 elapsed=450.6s

  [9377/13157] intraday_6219.csv.gz  in=346,428,943 out=94,311,322 elapsed=450.6s

  [9378/13157] intraday_6220.csv.gz  in=346,442,639 out=94,325,018 elapsed=450.6s

  [9379/13157] intraday_6221.csv.gz  in=346,456,410 out=94,338,789 elapsed=450.6s

  [9380/13157] intraday_6224.csv.gz  in=346,469,639 out=94,352,018 elapsed=450.6s

  [9381/13157] intraday_6222.csv.gz  in=346,482,172 out=94,364,551 elapsed=450.6s

  [9382/13157] intraday_6223.csv.gz  in=346,495,277 out=94,377,656 elapsed=450.6s

  [9383/13157] intraday_6225.csv.gz  in=346,508,705 out=94,391,084 elapsed=450.6s

  [9384/13157] intraday_6227.csv.gz  in=346,520,298 out=94,402,677 elapsed=450.7s

  [9385/13157] intraday_6229.csv.gz  in=346,537,812 out=94,420,191 elapsed=450.7s

  [9386/13157] intraday_6228.csv.gz  in=346,549,315 out=94,431,694 elapsed=450.7s

  [9387/13157] intraday_6226.csv.gz  in=346,563,378 out=94,445,757 elapsed=450.7s

  [9388/13157] intraday_6230.csv.gz  in=346,577,066 out=94,459,445 elapsed=450.7s

  [9389/13157] intraday_6231.csv.gz  in=346,590,130 out=94,472,509 elapsed=450.8s

  [9390/13157] intraday_6232.csv.gz  in=346,604,804 out=94,487,183 elapsed=450.8s

  [9391/13157] intraday_6235.csv.gz  in=346,618,370 out=94,500,749 elapsed=450.8s

  [9392/13157] intraday_6233.csv.gz  in=346,633,191 out=94,515,570 elapsed=450.8s

  [9393/13157] intraday_6234.csv.gz  in=346,646,574 out=94,528,953 elapsed=450.8s

  [9394/13157] intraday_6236.csv.gz  in=346,661,471 out=94,543,850 elapsed=450.9s

  [9395/13157] intraday_6237.csv.gz  in=346,676,132 out=94,558,511 elapsed=450.9s

  [9396/13157] intraday_6238.csv.gz  in=346,687,767 out=94,570,146 elapsed=450.9s

  [9397/13157] intraday_6240.csv.gz  in=346,700,603 out=94,582,982 elapsed=451.0s

  [9398/13157] intraday_6239.csv.gz  in=346,715,955 out=94,598,334 elapsed=451.0s

  [9399/13157] intraday_6241.csv.gz  in=346,730,116 out=94,612,495 elapsed=451.1s

  [9400/13157] intraday_6242.csv.gz  in=346,745,218 out=94,627,597 elapsed=451.1s

  [9401/13157] intraday_6243.csv.gz  in=346,760,524 out=94,642,903 elapsed=451.1s

  [9402/13157] intraday_6244.csv.gz  in=346,774,797 out=94,657,176 elapsed=451.1s

  [9403/13157] intraday_6246.csv.gz  in=346,787,355 out=94,669,734 elapsed=451.1s

  [9404/13157] intraday_6245.csv.gz  in=346,801,610 out=94,683,989 elapsed=451.2s

  [9405/13157] intraday_6247.csv.gz  in=346,814,041 out=94,696,420 elapsed=451.2s

  [9406/13157] intraday_6248.csv.gz  in=346,824,897 out=94,707,276 elapsed=451.2s

  [9407/13157] intraday_6250.csv.gz  in=346,836,003 out=94,718,382 elapsed=451.2s

  [9408/13157] intraday_6249.csv.gz  in=346,851,496 out=94,733,875 elapsed=451.2s

  [9409/13157] intraday_6251.csv.gz  in=346,865,277 out=94,747,656 elapsed=451.2s

  [9410/13157] intraday_6252.csv.gz  in=346,878,765 out=94,761,144 elapsed=451.3s

  [9411/13157] intraday_6253.csv.gz  in=346,894,429 out=94,776,808 elapsed=451.3s

  [9412/13157] intraday_6254.csv.gz  in=346,905,839 out=94,788,218 elapsed=451.3s

  [9413/13157] intraday_6255.csv.gz  in=346,919,385 out=94,801,764 elapsed=451.3s

  [9414/13157] intraday_6257.csv.gz  in=346,932,218 out=94,814,597 elapsed=451.3s

  [9415/13157] intraday_6258.csv.gz  in=346,946,495 out=94,828,874 elapsed=451.3s

  [9416/13157] intraday_6256.csv.gz  in=346,959,509 out=94,841,888 elapsed=451.3s

  [9417/13157] intraday_6262.csv.gz  in=346,973,790 out=94,856,169 elapsed=451.4s

  [9418/13157] intraday_6259.csv.gz  in=346,988,793 out=94,871,172 elapsed=451.4s

  [9419/13157] intraday_6261.csv.gz  in=347,002,881 out=94,885,260 elapsed=451.4s

  [9420/13157] intraday_6260.csv.gz  in=347,017,951 out=94,900,330 elapsed=451.4s

  [9421/13157] intraday_6264.csv.gz  in=347,031,898 out=94,914,277 elapsed=451.4s

  [9422/13157] intraday_6265.csv.gz  in=347,044,274 out=94,926,653 elapsed=451.4s

  [9423/13157] intraday_6263.csv.gz  in=347,055,603 out=94,937,982 elapsed=451.5s

  [9424/13157] intraday_6266.csv.gz  in=347,069,284 out=94,951,663 elapsed=451.5s

  [9425/13157] intraday_6270.csv.gz  in=347,071,931 out=94,954,310 elapsed=451.6s

  [9426/13157] intraday_6268.csv.gz  in=347,081,255 out=94,963,634 elapsed=451.6s

  [9427/13157] intraday_6267.csv.gz  in=347,092,010 out=94,974,389 elapsed=451.6s

  [9428/13157] intraday_6269.csv.gz  in=347,103,885 out=94,986,264 elapsed=451.6s

  [9429/13157] intraday_6272.csv.gz  in=347,117,376 out=94,999,254 elapsed=452.3s

  [9430/13157] intraday_6271.csv.gz  in=347,132,973 out=95,014,851 elapsed=452.3s

  [9431/13157] intraday_6275.csv.gz  in=347,146,092 out=95,027,970 elapsed=452.4s

  [9432/13157] intraday_6274.csv.gz  in=347,173,721 out=95,041,369 elapsed=452.4s

  [9433/13157] intraday_6273.csv.gz  in=347,195,508 out=95,056,451 elapsed=452.4s

  [9434/13157] intraday_6276.csv.gz  in=347,210,107 out=95,071,050 elapsed=452.4s

  [9435/13157] intraday_6278.csv.gz  in=347,220,922 out=95,081,865 elapsed=452.4s

  [9436/13157] intraday_6279.csv.gz  in=347,235,850 out=95,096,793 elapsed=452.4s

  [9437/13157] intraday_6277.csv.gz  in=347,253,365 out=95,114,308 elapsed=452.4s

  [9438/13157] intraday_6280.csv.gz  in=347,268,313 out=95,129,256 elapsed=452.4s

  [9439/13157] intraday_6281.csv.gz  in=347,284,888 out=95,145,119 elapsed=452.5s

  [9440/13157] intraday_6283.csv.gz  in=347,297,415 out=95,157,646 elapsed=452.5s

  [9441/13157] intraday_6282.csv.gz  in=347,310,651 out=95,170,882 elapsed=452.5s

  [9442/13157] intraday_6284.csv.gz  in=347,324,054 out=95,184,285 elapsed=452.5s

  [9443/13157] intraday_6285.csv.gz  in=347,333,480 out=95,193,711 elapsed=452.5s

  [9444/13157] intraday_6286.csv.gz  in=347,342,958 out=95,203,189 elapsed=452.5s

  [9445/13157] intraday_6287.csv.gz  in=347,356,874 out=95,217,105 elapsed=452.6s

  [9446/13157] intraday_6288.csv.gz  in=347,369,874 out=95,230,105 elapsed=452.6s

  [9447/13157] intraday_6289.csv.gz  in=347,380,942 out=95,241,173 elapsed=452.6s

  [9448/13157] intraday_6290.csv.gz  in=347,394,633 out=95,254,864 elapsed=452.6s

  [9449/13157] intraday_6292.csv.gz  in=347,406,712 out=95,266,943 elapsed=452.6s

  [9450/13157] intraday_6291.csv.gz  in=347,419,360 out=95,279,591 elapsed=452.6s

  [9451/13157] intraday_6293.csv.gz  in=347,433,292 out=95,291,571 elapsed=452.6s

  [9452/13157] intraday_6295.csv.gz  in=347,446,370 out=95,304,649 elapsed=452.7s

  [9453/13157] intraday_6294.csv.gz  in=347,460,686 out=95,318,965 elapsed=452.7s

  [9454/13157] intraday_6296.csv.gz  in=347,472,650 out=95,330,929 elapsed=452.7s

  [9455/13157] intraday_6297.csv.gz  in=347,484,256 out=95,342,535 elapsed=452.7s

  [9456/13157] intraday_6298.csv.gz  in=347,498,328 out=95,354,457 elapsed=452.7s

  [9457/13157] intraday_6299.csv.gz  in=347,511,226 out=95,367,355 elapsed=452.7s

  [9458/13157] intraday_6301.csv.gz  in=347,528,187 out=95,384,316 elapsed=452.8s

  [9459/13157] intraday_6300.csv.gz  in=347,552,169 out=95,401,112 elapsed=452.8s

  [9460/13157] intraday_6303.csv.gz  in=347,562,515 out=95,411,458 elapsed=452.8s

  [9461/13157] intraday_6302.csv.gz  in=347,575,373 out=95,424,316 elapsed=452.9s

  [9462/13157] intraday_6304.csv.gz  in=347,588,203 out=95,437,146 elapsed=452.9s

  [9463/13157] intraday_6305.csv.gz  in=347,611,503 out=95,452,894 elapsed=452.9s

  [9464/13157] intraday_6307.csv.gz  in=347,623,379 out=95,464,770 elapsed=452.9s

  [9465/13157] intraday_6309.csv.gz  in=347,636,039 out=95,477,430 elapsed=452.9s

  [9466/13157] intraday_6306.csv.gz  in=347,647,919 out=95,489,307 elapsed=452.9s

  [9467/13157] intraday_6308.csv.gz  in=347,658,417 out=95,499,690 elapsed=452.9s

  [9468/13157] intraday_6311.csv.gz  in=347,669,097 out=95,510,243 elapsed=453.2s

  [9469/13157] intraday_6313.csv.gz  in=347,683,305 out=95,524,451 elapsed=453.3s

  [9470/13157] intraday_6312.csv.gz  in=347,700,371 out=95,537,213 elapsed=453.3s

  [9471/13157] intraday_6314.csv.gz  in=347,711,081 out=95,547,923 elapsed=453.3s

  [9472/13157] intraday_6310.csv.gz  in=347,732,977 out=95,560,150 elapsed=453.3s

  [9473/13157] intraday_6315.csv.gz  in=347,746,633 out=95,573,806 elapsed=453.3s

  [9474/13157] intraday_6316.csv.gz  in=347,757,091 out=95,584,264 elapsed=453.4s

  [9475/13157] intraday_6317.csv.gz  in=347,771,852 out=95,597,770 elapsed=453.4s

  [9476/13157] intraday_6318.csv.gz  in=347,785,322 out=95,611,240 elapsed=453.4s

  [9477/13157] intraday_6319.csv.gz  in=347,799,738 out=95,623,747 elapsed=453.4s

  [9478/13157] intraday_6320.csv.gz  in=347,820,814 out=95,637,371 elapsed=453.4s

  [9479/13157] intraday_6322.csv.gz  in=347,831,194 out=95,647,751 elapsed=453.4s

  [9480/13157] intraday_6321.csv.gz  in=347,842,954 out=95,659,511 elapsed=453.5s

  [9481/13157] intraday_6323.csv.gz  in=347,857,245 out=95,673,802 elapsed=453.5s

  [9482/13157] intraday_6324.csv.gz  in=347,867,720 out=95,684,277 elapsed=453.5s

  [9483/13157] intraday_6325.csv.gz  in=347,882,175 out=95,698,732 elapsed=453.7s

  [9484/13157] intraday_6326.csv.gz  in=347,895,488 out=95,712,045 elapsed=453.7s

  [9485/13157] intraday_6327.csv.gz  in=347,908,124 out=95,724,681 elapsed=453.7s

  [9486/13157] intraday_6328.csv.gz  in=347,923,695 out=95,737,660 elapsed=453.7s

  [9487/13157] intraday_6331.csv.gz  in=347,935,395 out=95,749,360 elapsed=454.0s

  [9488/13157] intraday_6329.csv.gz  in=347,948,277 out=95,762,242 elapsed=454.0s

  [9489/13157] intraday_6330.csv.gz  in=347,962,657 out=95,776,622 elapsed=454.0s

  [9490/13157] intraday_6332.csv.gz  in=347,976,883 out=95,790,848 elapsed=454.0s

  [9491/13157] intraday_6333.csv.gz  in=347,988,519 out=95,802,484 elapsed=454.1s

  [9492/13157] intraday_6334.csv.gz  in=347,998,344 out=95,812,309 elapsed=454.1s

  [9493/13157] intraday_6336.csv.gz  in=348,012,652 out=95,826,617 elapsed=454.1s

  [9494/13157] intraday_6335.csv.gz  in=348,024,426 out=95,838,391 elapsed=454.1s

  [9495/13157] intraday_6340.csv.gz  in=348,035,799 out=95,849,764 elapsed=454.2s

  [9496/13157] intraday_6337.csv.gz  in=348,050,755 out=95,864,720 elapsed=454.2s

  [9497/13157] intraday_6339.csv.gz  in=348,063,447 out=95,877,412 elapsed=454.2s

  [9498/13157] intraday_6338.csv.gz  in=348,077,302 out=95,891,267 elapsed=454.2s

  [9499/13157] intraday_6341.csv.gz  in=348,089,015 out=95,902,980 elapsed=454.2s

  [9500/13157] intraday_6342.csv.gz  in=348,100,824 out=95,914,789 elapsed=454.2s

  [9501/13157] intraday_6343.csv.gz  in=348,113,082 out=95,927,047 elapsed=454.3s

  [9502/13157] intraday_6344.csv.gz  in=348,126,320 out=95,940,285 elapsed=454.3s

  [9503/13157] intraday_6345.csv.gz  in=348,139,114 out=95,953,079 elapsed=454.6s

  [9504/13157] intraday_6346.csv.gz  in=348,150,803 out=95,964,768 elapsed=454.6s

  [9505/13157] intraday_6347.csv.gz  in=348,161,326 out=95,975,291 elapsed=454.6s

  [9506/13157] intraday_6348.csv.gz  in=348,175,371 out=95,989,336 elapsed=454.6s

  [9507/13157] intraday_6351.csv.gz  in=348,185,045 out=95,999,010 elapsed=454.7s

  [9508/13157] intraday_6349.csv.gz  in=348,196,546 out=96,010,511 elapsed=454.8s

  [9509/13157] intraday_6350.csv.gz  in=348,209,945 out=96,023,910 elapsed=454.8s

  [9510/13157] intraday_6352.csv.gz  in=348,222,349 out=96,036,314 elapsed=454.8s

  [9511/13157] intraday_6353.csv.gz  in=348,235,612 out=96,049,577 elapsed=454.8s

  [9512/13157] intraday_6354.csv.gz  in=348,250,692 out=96,064,657 elapsed=454.8s

  [9513/13157] intraday_6355.csv.gz  in=348,266,289 out=96,080,254 elapsed=454.8s

  [9514/13157] intraday_6356.csv.gz  in=348,281,952 out=96,095,917 elapsed=454.8s

  [9515/13157] intraday_6357.csv.gz  in=348,293,414 out=96,107,379 elapsed=454.8s

  [9516/13157] intraday_6358.csv.gz  in=348,306,388 out=96,120,353 elapsed=455.0s

  [9517/13157] intraday_6360.csv.gz  in=348,322,765 out=96,136,730 elapsed=455.0s

  [9518/13157] intraday_6359.csv.gz  in=348,336,292 out=96,150,257 elapsed=455.0s

  [9519/13157] intraday_6361.csv.gz  in=348,357,652 out=96,164,154 elapsed=455.0s

  [9520/13157] intraday_6362.csv.gz  in=348,370,747 out=96,177,249 elapsed=455.2s

  [9521/13157] intraday_6363.csv.gz  in=348,384,039 out=96,190,541 elapsed=455.2s

  [9522/13157] intraday_6364.csv.gz  in=348,397,908 out=96,204,410 elapsed=455.2s

  [9523/13157] intraday_6365.csv.gz  in=348,412,518 out=96,219,020 elapsed=455.2s

  [9524/13157] intraday_6369.csv.gz  in=348,424,910 out=96,231,412 elapsed=455.4s

  [9525/13157] intraday_6368.csv.gz  in=348,438,137 out=96,244,639 elapsed=455.4s

  [9526/13157] intraday_6367.csv.gz  in=348,451,081 out=96,257,583 elapsed=455.4s

  [9527/13157] intraday_6366.csv.gz  in=348,463,486 out=96,269,988 elapsed=455.5s

  [9528/13157] intraday_6373.csv.gz  in=348,478,141 out=96,284,643 elapsed=455.6s

  [9529/13157] intraday_6370.csv.gz  in=348,492,260 out=96,298,762 elapsed=455.6s

  [9530/13157] intraday_6371.csv.gz  in=348,504,146 out=96,310,648 elapsed=455.6s

  [9531/13157] intraday_6372.csv.gz  in=348,522,601 out=96,323,984 elapsed=455.6s

  [9532/13157] intraday_6374.csv.gz  in=348,536,189 out=96,337,531 elapsed=455.6s

  [9533/13157] intraday_6375.csv.gz  in=348,549,301 out=96,350,643 elapsed=455.6s

  [9534/13157] intraday_6376.csv.gz  in=348,563,672 out=96,365,014 elapsed=455.6s

  [9535/13157] intraday_6377.csv.gz  in=348,578,171 out=96,379,513 elapsed=455.6s

  [9536/13157] intraday_6379.csv.gz  in=348,591,672 out=96,392,953 elapsed=455.7s

  [9537/13157] intraday_6378.csv.gz  in=348,604,305 out=96,405,586 elapsed=455.7s

  [9538/13157] intraday_6381.csv.gz  in=348,617,635 out=96,418,916 elapsed=455.7s

  [9539/13157] intraday_6380.csv.gz  in=348,633,145 out=96,434,426 elapsed=455.7s

  [9540/13157] intraday_6382.csv.gz  in=348,644,913 out=96,446,194 elapsed=455.9s

  [9541/13157] intraday_6383.csv.gz  in=348,659,246 out=96,460,527 elapsed=455.9s

  [9542/13157] intraday_6385.csv.gz  in=348,673,589 out=96,474,870 elapsed=455.9s

  [9543/13157] intraday_6384.csv.gz  in=348,685,423 out=96,486,704 elapsed=455.9s

  [9544/13157] intraday_6387.csv.gz  in=348,700,178 out=96,501,459 elapsed=456.1s

  [9545/13157] intraday_6386.csv.gz  in=348,716,105 out=96,517,386 elapsed=456.1s

  [9546/13157] intraday_6388.csv.gz  in=348,730,798 out=96,532,079 elapsed=456.1s

  [9547/13157] intraday_6389.csv.gz  in=348,743,754 out=96,545,035 elapsed=456.1s

  [9548/13157] intraday_6392.csv.gz  in=348,754,768 out=96,556,049 elapsed=456.1s

  [9549/13157] intraday_6391.csv.gz  in=348,767,557 out=96,568,838 elapsed=456.1s

  [9550/13157] intraday_6393.csv.gz  in=348,781,359 out=96,582,640 elapsed=456.1s

  [9551/13157] intraday_6390.csv.gz  in=348,798,585 out=96,595,683 elapsed=456.1s

  [9552/13157] intraday_6394.csv.gz  in=348,810,324 out=96,607,422 elapsed=456.1s

  [9553/13157] intraday_6395.csv.gz  in=348,822,749 out=96,619,847 elapsed=456.2s

  [9554/13157] intraday_6398.csv.gz  in=348,834,401 out=96,631,499 elapsed=456.2s

  [9555/13157] intraday_6396.csv.gz  in=348,848,362 out=96,645,460 elapsed=456.2s

  [9556/13157] intraday_6397.csv.gz  in=348,874,872 out=96,662,714 elapsed=456.2s

  [9557/13157] intraday_6399.csv.gz  in=348,886,943 out=96,674,785 elapsed=456.2s

  [9558/13157] intraday_6400.csv.gz  in=348,900,244 out=96,688,086 elapsed=456.3s

  [9559/13157] intraday_6401.csv.gz  in=348,911,970 out=96,699,812 elapsed=456.3s

  [9560/13157] intraday_6402.csv.gz  in=348,927,685 out=96,715,049 elapsed=456.3s

  [9561/13157] intraday_6403.csv.gz  in=348,941,859 out=96,729,223 elapsed=456.3s

  [9562/13157] intraday_6404.csv.gz  in=348,956,598 out=96,743,962 elapsed=456.4s

  [9563/13157] intraday_6405.csv.gz  in=348,971,245 out=96,758,609 elapsed=456.4s

  [9564/13157] intraday_6406.csv.gz  in=348,985,240 out=96,772,604 elapsed=456.4s

  [9565/13157] intraday_6407.csv.gz  in=348,996,712 out=96,784,076 elapsed=456.4s

  [9566/13157] intraday_6408.csv.gz  in=349,009,516 out=96,796,880 elapsed=456.4s

  [9567/13157] intraday_6411.csv.gz  in=349,019,756 out=96,807,120 elapsed=456.5s

  [9568/13157] intraday_6410.csv.gz  in=349,032,740 out=96,819,965 elapsed=456.5s

  [9569/13157] intraday_6409.csv.gz  in=349,045,182 out=96,832,407 elapsed=456.5s

  [9570/13157] intraday_6414.csv.gz  in=349,047,865 out=96,835,090 elapsed=456.5s

  [9571/13157] intraday_6412.csv.gz  in=349,056,773 out=96,843,998 elapsed=456.5s

  [9572/13157] intraday_6415.csv.gz  in=349,073,102 out=96,860,327 elapsed=456.5s

  [9573/13157] intraday_6413.csv.gz  in=349,085,673 out=96,872,898 elapsed=456.5s

  [9574/13157] intraday_6416.csv.gz  in=349,098,574 out=96,885,799 elapsed=456.5s

  [9575/13157] intraday_6417.csv.gz  in=349,112,561 out=96,899,786 elapsed=456.6s

  [9576/13157] intraday_6418.csv.gz  in=349,123,804 out=96,911,029 elapsed=456.6s

  [9577/13157] intraday_6419.csv.gz  in=349,136,675 out=96,923,900 elapsed=456.6s

  [9578/13157] intraday_6420.csv.gz  in=349,150,953 out=96,938,178 elapsed=456.6s

  [9579/13157] intraday_6422.csv.gz  in=349,163,662 out=96,950,887 elapsed=456.7s

  [9580/13157] intraday_6423.csv.gz  in=349,177,615 out=96,964,840 elapsed=456.7s

  [9581/13157] intraday_6424.csv.gz  in=349,192,112 out=96,979,337 elapsed=456.7s

  [9582/13157] intraday_6421.csv.gz  in=349,207,146 out=96,994,371 elapsed=456.7s

  [9583/13157] intraday_6425.csv.gz  in=349,223,136 out=97,010,361 elapsed=456.7s

  [9584/13157] intraday_6426.csv.gz  in=349,236,986 out=97,024,211 elapsed=456.8s

  [9585/13157] intraday_6428.csv.gz  in=349,249,471 out=97,036,696 elapsed=456.8s

  [9586/13157] intraday_6427.csv.gz  in=349,263,189 out=97,050,414 elapsed=456.8s

  [9587/13157] intraday_6431.csv.gz  in=349,276,972 out=97,064,197 elapsed=456.8s

  [9588/13157] intraday_6429.csv.gz  in=349,287,864 out=97,075,089 elapsed=456.8s

  [9589/13157] intraday_6430.csv.gz  in=349,297,499 out=97,084,724 elapsed=456.8s

  [9590/13157] intraday_6432.csv.gz  in=349,311,440 out=97,098,665 elapsed=456.9s

  [9591/13157] intraday_6435.csv.gz  in=349,323,825 out=97,111,050 elapsed=457.1s

  [9592/13157] intraday_6436.csv.gz  in=349,336,736 out=97,123,961 elapsed=457.1s

  [9593/13157] intraday_6434.csv.gz  in=349,350,097 out=97,137,322 elapsed=457.1s

  [9594/13157] intraday_6433.csv.gz  in=349,360,515 out=97,147,740 elapsed=457.1s

  [9595/13157] intraday_6437.csv.gz  in=349,372,757 out=97,159,982 elapsed=457.8s

  [9596/13157] intraday_6440.csv.gz  in=349,384,141 out=97,171,366 elapsed=457.8s

  [9597/13157] intraday_6438.csv.gz  in=349,397,564 out=97,184,789 elapsed=457.8s

  [9598/13157] intraday_6439.csv.gz  in=349,409,897 out=97,197,122 elapsed=457.8s

  [9599/13157] intraday_6442.csv.gz  in=349,421,731 out=97,208,956 elapsed=458.0s

  [9600/13157] intraday_6441.csv.gz  in=349,433,183 out=97,220,408 elapsed=458.0s

  [9601/13157] intraday_6443.csv.gz  in=349,445,984 out=97,233,209 elapsed=458.0s

  [9602/13157] intraday_6444.csv.gz  in=349,460,465 out=97,247,690 elapsed=458.0s

  [9603/13157] intraday_6446.csv.gz  in=349,471,315 out=97,258,540 elapsed=458.0s

  [9604/13157] intraday_6447.csv.gz  in=349,482,040 out=97,269,265 elapsed=458.2s

  [9605/13157] intraday_6445.csv.gz  in=349,499,344 out=97,286,569 elapsed=458.2s

  [9606/13157] intraday_6448.csv.gz  in=349,512,449 out=97,299,674 elapsed=458.2s

  [9607/13157] intraday_6449.csv.gz  in=349,527,372 out=97,314,597 elapsed=458.2s

  [9608/13157] intraday_6450.csv.gz  in=349,539,315 out=97,326,540 elapsed=458.3s

  [9609/13157] intraday_6451.csv.gz  in=349,552,998 out=97,340,223 elapsed=458.4s

  [9610/13157] intraday_6454.csv.gz  in=349,564,134 out=97,351,359 elapsed=458.4s

  [9611/13157] intraday_6452.csv.gz  in=349,574,621 out=97,361,846 elapsed=458.4s

  [9612/13157] intraday_6453.csv.gz  in=349,587,024 out=97,374,249 elapsed=458.4s

  [9613/13157] intraday_6455.csv.gz  in=349,598,984 out=97,386,209 elapsed=459.0s

  [9614/13157] intraday_6456.csv.gz  in=349,612,195 out=97,399,420 elapsed=459.0s

  [9615/13157] intraday_6458.csv.gz  in=349,625,726 out=97,412,951 elapsed=459.0s

  [9616/13157] intraday_6457.csv.gz  in=349,638,983 out=97,426,208 elapsed=459.0s

  [9617/13157] intraday_6462.csv.gz  in=349,650,589 out=97,437,814 elapsed=459.2s

  [9618/13157] intraday_6459.csv.gz  in=349,663,610 out=97,450,835 elapsed=459.2s

  [9619/13157] intraday_6460.csv.gz  in=349,674,637 out=97,461,862 elapsed=459.2s

  [9620/13157] intraday_6461.csv.gz  in=349,687,713 out=97,474,938 elapsed=459.2s

  [9621/13157] intraday_6464.csv.gz  in=349,699,433 out=97,486,658 elapsed=459.3s

  [9622/13157] intraday_6463.csv.gz  in=349,710,445 out=97,497,670 elapsed=459.3s

  [9623/13157] intraday_6466.csv.gz  in=349,723,400 out=97,510,625 elapsed=459.3s

  [9624/13157] intraday_6465.csv.gz  in=349,735,340 out=97,522,565 elapsed=459.3s

  [9625/13157] intraday_6467.csv.gz  in=349,748,022 out=97,535,247 elapsed=459.4s

  [9626/13157] intraday_6469.csv.gz  in=349,763,018 out=97,550,243 elapsed=459.4s

  [9627/13157] intraday_6468.csv.gz  in=349,774,761 out=97,561,986 elapsed=459.4s

  [9628/13157] intraday_6471.csv.gz  in=349,786,685 out=97,573,910 elapsed=459.4s

  [9629/13157] intraday_6470.csv.gz  in=349,799,726 out=97,586,951 elapsed=459.4s

  [9630/13157] intraday_6472.csv.gz  in=349,810,715 out=97,597,940 elapsed=459.5s

  [9631/13157] intraday_6473.csv.gz  in=349,824,803 out=97,612,028 elapsed=459.5s

  [9632/13157] intraday_6477.csv.gz  in=349,837,081 out=97,624,306 elapsed=459.6s

  [9633/13157] intraday_6475.csv.gz  in=349,849,324 out=97,636,549 elapsed=459.6s

  [9634/13157] intraday_6474.csv.gz  in=349,863,862 out=97,651,087 elapsed=459.6s

  [9635/13157] intraday_6476.csv.gz  in=349,875,868 out=97,663,093 elapsed=459.6s

  [9636/13157] intraday_6480.csv.gz  in=349,892,210 out=97,679,435 elapsed=459.7s

  [9637/13157] intraday_6478.csv.gz  in=349,903,207 out=97,690,432 elapsed=459.7s

  [9638/13157] intraday_6481.csv.gz  in=349,914,741 out=97,701,966 elapsed=459.7s

  [9639/13157] intraday_6479.csv.gz  in=349,928,814 out=97,716,039 elapsed=459.7s

  [9640/13157] intraday_6485.csv.gz  in=349,940,140 out=97,727,365 elapsed=459.8s

  [9641/13157] intraday_6482.csv.gz  in=349,952,649 out=97,739,874 elapsed=459.8s

  [9642/13157] intraday_6484.csv.gz  in=349,963,227 out=97,750,452 elapsed=459.8s

  [9643/13157] intraday_6483.csv.gz  in=349,976,413 out=97,763,638 elapsed=459.8s

  [9644/13157] intraday_6488.csv.gz  in=349,987,536 out=97,774,761 elapsed=460.4s

  [9645/13157] intraday_6486.csv.gz  in=349,999,417 out=97,786,642 elapsed=460.4s

  [9646/13157] intraday_6487.csv.gz  in=350,014,241 out=97,801,466 elapsed=460.4s

  [9647/13157] intraday_6489.csv.gz  in=350,027,235 out=97,814,460 elapsed=460.4s

  [9648/13157] intraday_6492.csv.gz  in=350,039,643 out=97,826,868 elapsed=460.5s

  [9649/13157] intraday_6490.csv.gz  in=350,050,039 out=97,837,264 elapsed=460.5s

  [9650/13157] intraday_6491.csv.gz  in=350,064,170 out=97,851,395 elapsed=460.5s

  [9651/13157] intraday_6493.csv.gz  in=350,078,057 out=97,865,282 elapsed=460.5s

  [9652/13157] intraday_6494.csv.gz  in=350,088,824 out=97,876,049 elapsed=460.6s

  [9653/13157] intraday_6495.csv.gz  in=350,099,466 out=97,886,691 elapsed=460.6s

  [9654/13157] intraday_6496.csv.gz  in=350,111,818 out=97,899,043 elapsed=460.6s

  [9655/13157] intraday_6497.csv.gz  in=350,128,013 out=97,915,238 elapsed=460.6s

  [9656/13157] intraday_6499.csv.gz  in=350,142,004 out=97,929,229 elapsed=460.7s

  [9657/13157] intraday_6500.csv.gz  in=350,155,320 out=97,942,545 elapsed=460.8s

  [9658/13157] intraday_6498.csv.gz  in=350,171,802 out=97,959,027 elapsed=460.8s

  [9659/13157] intraday_6501.csv.gz  in=350,183,270 out=97,970,495 elapsed=460.8s

  [9660/13157] intraday_6504.csv.gz  in=350,197,798 out=97,985,023 elapsed=460.8s

  [9661/13157] intraday_6505.csv.gz  in=350,209,870 out=97,997,095 elapsed=460.8s

  [9662/13157] intraday_6503.csv.gz  in=350,224,125 out=98,011,350 elapsed=460.8s

  [9663/13157] intraday_6502.csv.gz  in=350,238,637 out=98,025,862 elapsed=460.8s

  [9664/13157] intraday_6508.csv.gz  in=350,252,338 out=98,039,563 elapsed=460.9s

  [9665/13157] intraday_6507.csv.gz  in=350,266,481 out=98,053,706 elapsed=460.9s

  [9666/13157] intraday_6506.csv.gz  in=350,283,114 out=98,070,339 elapsed=460.9s

  [9667/13157] intraday_6509.csv.gz  in=350,295,684 out=98,082,909 elapsed=460.9s

  [9668/13157] intraday_6512.csv.gz  in=350,310,249 out=98,097,474 elapsed=461.0s

  [9669/13157] intraday_6511.csv.gz  in=350,322,558 out=98,109,783 elapsed=461.0s

  [9670/13157] intraday_6510.csv.gz  in=350,335,946 out=98,123,171 elapsed=461.0s

  [9671/13157] intraday_6513.csv.gz  in=350,348,499 out=98,135,724 elapsed=461.0s

  [9672/13157] intraday_6514.csv.gz  in=350,361,413 out=98,148,638 elapsed=461.1s

  [9673/13157] intraday_6515.csv.gz  in=350,373,508 out=98,160,733 elapsed=461.1s

  [9674/13157] intraday_6516.csv.gz  in=350,388,564 out=98,175,789 elapsed=461.5s

  [9675/13157] intraday_6517.csv.gz  in=350,403,814 out=98,191,039 elapsed=461.5s

  [9676/13157] intraday_6518.csv.gz  in=350,417,754 out=98,204,979 elapsed=461.6s

  [9677/13157] intraday_6519.csv.gz  in=350,428,584 out=98,215,809 elapsed=461.6s

  [9678/13157] intraday_6522.csv.gz  in=350,440,171 out=98,227,396 elapsed=461.6s

  [9679/13157] intraday_6521.csv.gz  in=350,452,899 out=98,240,124 elapsed=461.6s

  [9680/13157] intraday_6523.csv.gz  in=350,467,866 out=98,255,091 elapsed=461.7s

  [9681/13157] intraday_6524.csv.gz  in=350,481,184 out=98,268,409 elapsed=461.7s

  [9682/13157] intraday_6525.csv.gz  in=350,493,156 out=98,280,381 elapsed=461.7s

  [9683/13157] intraday_6520.csv.gz  in=350,526,232 out=98,301,082 elapsed=461.7s

  [9684/13157] intraday_6526.csv.gz  in=350,541,081 out=98,315,931 elapsed=461.8s

  [9685/13157] intraday_6528.csv.gz  in=350,554,626 out=98,329,476 elapsed=461.8s

  [9686/13157] intraday_6529.csv.gz  in=350,570,596 out=98,345,446 elapsed=461.8s

  [9687/13157] intraday_6527.csv.gz  in=350,592,980 out=98,359,882 elapsed=461.8s

  [9688/13157] intraday_6530.csv.gz  in=350,609,714 out=98,376,616 elapsed=461.8s

  [9689/13157] intraday_6531.csv.gz  in=350,622,213 out=98,389,115 elapsed=461.8s

  [9690/13157] intraday_6532.csv.gz  in=350,638,116 out=98,405,018 elapsed=461.8s

  [9691/13157] intraday_6533.csv.gz  in=350,649,772 out=98,416,674 elapsed=461.9s

  [9692/13157] intraday_6534.csv.gz  in=350,662,888 out=98,429,790 elapsed=462.0s

  [9693/13157] intraday_6537.csv.gz  in=350,674,139 out=98,441,041 elapsed=462.0s

  [9694/13157] intraday_6535.csv.gz  in=350,685,424 out=98,452,326 elapsed=462.0s

  [9695/13157] intraday_6538.csv.gz  in=350,699,534 out=98,466,436 elapsed=462.0s

  [9696/13157] intraday_6536.csv.gz  in=350,714,044 out=98,480,946 elapsed=462.0s

  [9697/13157] intraday_6539.csv.gz  in=350,726,361 out=98,493,263 elapsed=462.2s

  [9698/13157] intraday_6542.csv.gz  in=350,739,101 out=98,506,003 elapsed=462.2s

  [9699/13157] intraday_6541.csv.gz  in=350,752,311 out=98,519,213 elapsed=462.2s

  [9700/13157] intraday_6540.csv.gz  in=350,767,650 out=98,534,552 elapsed=462.2s

  [9701/13157] intraday_6545.csv.gz  in=350,780,842 out=98,547,744 elapsed=462.3s

  [9702/13157] intraday_6543.csv.gz  in=350,793,913 out=98,560,815 elapsed=462.3s

  [9703/13157] intraday_6546.csv.gz  in=350,808,463 out=98,575,365 elapsed=462.3s

  [9704/13157] intraday_6544.csv.gz  in=350,820,874 out=98,587,776 elapsed=462.3s

  [9705/13157] intraday_6547.csv.gz  in=350,834,395 out=98,601,297 elapsed=462.4s

  [9706/13157] intraday_6548.csv.gz  in=350,849,388 out=98,616,290 elapsed=462.5s

  [9707/13157] intraday_6549.csv.gz  in=350,863,233 out=98,630,135 elapsed=462.5s

  [9708/13157] intraday_6550.csv.gz  in=350,874,019 out=98,640,921 elapsed=462.5s

  [9709/13157] intraday_6551.csv.gz  in=350,887,672 out=98,654,574 elapsed=462.6s

  [9710/13157] intraday_6553.csv.gz  in=350,899,440 out=98,666,342 elapsed=462.6s

  [9711/13157] intraday_6554.csv.gz  in=350,911,231 out=98,678,133 elapsed=462.9s

  [9712/13157] intraday_6552.csv.gz  in=350,924,001 out=98,690,903 elapsed=462.9s

  [9713/13157] intraday_6555.csv.gz  in=350,932,541 out=98,699,443 elapsed=462.9s

  [9714/13157] intraday_6556.csv.gz  in=350,945,127 out=98,711,669 elapsed=462.9s

  [9715/13157] intraday_6557.csv.gz  in=350,950,377 out=98,716,919 elapsed=463.0s

  [9716/13157] intraday_6560.csv.gz  in=350,963,343 out=98,729,885 elapsed=463.0s

  [9717/13157] intraday_6559.csv.gz  in=350,976,718 out=98,743,260 elapsed=463.1s

  [9718/13157] intraday_6561.csv.gz  in=350,988,206 out=98,754,748 elapsed=463.1s

  [9719/13157] intraday_6562.csv.gz  in=351,000,990 out=98,767,532 elapsed=463.1s

  [9720/13157] intraday_6558.csv.gz  in=351,020,266 out=98,784,153 elapsed=463.1s

  [9721/13157] intraday_6564.csv.gz  in=351,034,605 out=98,798,492 elapsed=463.3s

  [9722/13157] intraday_6565.csv.gz  in=351,046,657 out=98,810,544 elapsed=463.3s

  [9723/13157] intraday_6563.csv.gz  in=351,062,038 out=98,825,925 elapsed=463.3s

  [9724/13157] intraday_6566.csv.gz  in=351,079,482 out=98,840,660 elapsed=463.3s

  [9725/13157] intraday_6570.csv.gz  in=351,093,658 out=98,854,836 elapsed=463.5s

  [9726/13157] intraday_6567.csv.gz  in=351,107,491 out=98,868,669 elapsed=463.5s

  [9727/13157] intraday_6568.csv.gz  in=351,123,924 out=98,885,102 elapsed=463.5s

  [9728/13157] intraday_6569.csv.gz  in=351,137,652 out=98,898,830 elapsed=463.5s

  [9729/13157] intraday_6571.csv.gz  in=351,149,981 out=98,911,159 elapsed=463.6s

  [9730/13157] intraday_6574.csv.gz  in=351,164,235 out=98,925,413 elapsed=463.6s

  [9731/13157] intraday_6573.csv.gz  in=351,173,451 out=98,934,629 elapsed=463.6s

  [9732/13157] intraday_6572.csv.gz  in=351,183,878 out=98,945,056 elapsed=463.6s

  [9733/13157] intraday_6575.csv.gz  in=351,197,081 out=98,958,259 elapsed=463.8s

  [9734/13157] intraday_6577.csv.gz  in=351,209,819 out=98,970,997 elapsed=463.8s

  [9735/13157] intraday_6578.csv.gz  in=351,222,174 out=98,983,352 elapsed=463.8s

  [9736/13157] intraday_6576.csv.gz  in=351,234,266 out=98,995,444 elapsed=463.8s

  [9737/13157] intraday_6579.csv.gz  in=351,246,726 out=99,007,904 elapsed=463.8s

  [9738/13157] intraday_6580.csv.gz  in=351,258,748 out=99,019,926 elapsed=464.0s

  [9739/13157] intraday_6582.csv.gz  in=351,272,612 out=99,033,790 elapsed=464.0s

  [9740/13157] intraday_6583.csv.gz  in=351,293,618 out=99,047,936 elapsed=464.0s

  [9741/13157] intraday_6581.csv.gz  in=351,307,192 out=99,061,510 elapsed=464.0s

  [9742/13157] intraday_6584.csv.gz  in=351,318,752 out=99,073,070 elapsed=464.0s

  [9743/13157] intraday_6586.csv.gz  in=351,331,173 out=99,085,491 elapsed=464.0s

  [9744/13157] intraday_6587.csv.gz  in=351,343,758 out=99,098,076 elapsed=464.0s

  [9745/13157] intraday_6585.csv.gz  in=351,355,959 out=99,110,277 elapsed=464.1s

  [9746/13157] intraday_6588.csv.gz  in=351,373,609 out=99,127,927 elapsed=464.1s

  [9747/13157] intraday_6590.csv.gz  in=351,385,285 out=99,139,603 elapsed=464.1s

  [9748/13157] intraday_6589.csv.gz  in=351,398,047 out=99,152,365 elapsed=464.1s

  [9749/13157] intraday_6591.csv.gz  in=351,410,951 out=99,165,269 elapsed=464.1s

  [9750/13157] intraday_6592.csv.gz  in=351,424,759 out=99,179,077 elapsed=464.1s

  [9751/13157] intraday_6595.csv.gz  in=351,435,974 out=99,190,292 elapsed=464.2s

  [9752/13157] intraday_6594.csv.gz  in=351,450,771 out=99,205,089 elapsed=464.2s

  [9753/13157] intraday_6593.csv.gz  in=351,462,381 out=99,216,699 elapsed=464.2s

  [9754/13157] intraday_6597.csv.gz  in=351,474,594 out=99,227,623 elapsed=464.2s

  [9755/13157] intraday_6596.csv.gz  in=351,488,687 out=99,241,115 elapsed=464.2s

  [9756/13157] intraday_6598.csv.gz  in=351,501,180 out=99,253,608 elapsed=464.2s

  [9757/13157] intraday_6599.csv.gz  in=351,517,769 out=99,268,022 elapsed=464.2s

  [9758/13157] intraday_6601.csv.gz  in=351,529,038 out=99,279,291 elapsed=464.2s

  [9759/13157] intraday_6600.csv.gz  in=351,542,377 out=99,292,630 elapsed=464.3s

  [9760/13157] intraday_6602.csv.gz  in=351,556,213 out=99,306,466 elapsed=464.3s

  [9761/13157] intraday_6603.csv.gz  in=351,567,339 out=99,317,592 elapsed=464.3s

  [9762/13157] intraday_6604.csv.gz  in=351,579,714 out=99,329,967 elapsed=464.3s

  [9763/13157] intraday_6605.csv.gz  in=351,593,111 out=99,343,364 elapsed=464.4s

  [9764/13157] intraday_6607.csv.gz  in=351,604,660 out=99,354,913 elapsed=464.4s

  [9765/13157] intraday_6606.csv.gz  in=351,615,370 out=99,365,623 elapsed=464.4s

  [9766/13157] intraday_6608.csv.gz  in=351,627,158 out=99,377,411 elapsed=464.4s

  [9767/13157] intraday_6609.csv.gz  in=351,639,552 out=99,389,805 elapsed=464.4s

  [9768/13157] intraday_6610.csv.gz  in=351,652,240 out=99,402,493 elapsed=464.4s

  [9769/13157] intraday_6611.csv.gz  in=351,664,595 out=99,414,848 elapsed=464.4s

  [9770/13157] intraday_6614.csv.gz  in=351,677,483 out=99,427,736 elapsed=464.5s

  [9771/13157] intraday_6612.csv.gz  in=351,692,351 out=99,442,604 elapsed=464.5s

  [9772/13157] intraday_6613.csv.gz  in=351,706,290 out=99,456,543 elapsed=464.5s

  [9773/13157] intraday_6615.csv.gz  in=351,717,675 out=99,467,928 elapsed=464.5s

  [9774/13157] intraday_6616.csv.gz  in=351,731,705 out=99,481,958 elapsed=464.5s

  [9775/13157] intraday_6618.csv.gz  in=351,744,869 out=99,495,122 elapsed=464.5s

  [9776/13157] intraday_6617.csv.gz  in=351,759,658 out=99,509,911 elapsed=464.6s

  [9777/13157] intraday_6619.csv.gz  in=351,773,340 out=99,523,593 elapsed=464.6s

  [9778/13157] intraday_6620.csv.gz  in=351,785,023 out=99,535,276 elapsed=464.6s

  [9779/13157] intraday_6621.csv.gz  in=351,796,707 out=99,546,960 elapsed=464.6s

  [9780/13157] intraday_6624.csv.gz  in=351,809,854 out=99,560,107 elapsed=464.6s

  [9781/13157] intraday_6622.csv.gz  in=351,826,525 out=99,572,644 elapsed=464.7s

  [9782/13157] intraday_6625.csv.gz  in=351,839,763 out=99,585,882 elapsed=464.7s

  [9783/13157] intraday_6623.csv.gz  in=351,855,512 out=99,601,631 elapsed=464.7s

  [9784/13157] intraday_6626.csv.gz  in=351,868,225 out=99,614,344 elapsed=464.7s

  [9785/13157] intraday_6627.csv.gz  in=351,879,668 out=99,625,787 elapsed=464.7s

  [9786/13157] intraday_6628.csv.gz  in=351,891,932 out=99,638,051 elapsed=464.7s

  [9787/13157] intraday_6629.csv.gz  in=351,902,917 out=99,649,036 elapsed=464.7s

  [9788/13157] intraday_6631.csv.gz  in=351,915,930 out=99,662,049 elapsed=464.9s

  [9789/13157] intraday_6630.csv.gz  in=351,930,431 out=99,675,395 elapsed=464.9s

  [9790/13157] intraday_6632.csv.gz  in=351,942,483 out=99,687,447 elapsed=464.9s

  [9791/13157] intraday_6633.csv.gz  in=351,952,815 out=99,697,779 elapsed=464.9s

  [9792/13157] intraday_6636.csv.gz  in=351,964,977 out=99,709,941 elapsed=464.9s

  [9793/13157] intraday_6635.csv.gz  in=351,976,849 out=99,721,614 elapsed=464.9s

  [9794/13157] intraday_6637.csv.gz  in=351,993,573 out=99,735,235 elapsed=464.9s

  [9795/13157] intraday_6634.csv.gz  in=352,006,859 out=99,748,209 elapsed=464.9s

  [9796/13157] intraday_6638.csv.gz  in=352,016,590 out=99,757,940 elapsed=464.9s

  [9797/13157] intraday_6640.csv.gz  in=352,029,241 out=99,770,591 elapsed=465.0s

  [9798/13157] intraday_6641.csv.gz  in=352,044,985 out=99,786,335 elapsed=465.0s

  [9799/13157] intraday_6639.csv.gz  in=352,057,188 out=99,798,538 elapsed=465.0s

  [9800/13157] intraday_6642.csv.gz  in=352,071,915 out=99,813,265 elapsed=465.0s

  [9801/13157] intraday_6643.csv.gz  in=352,085,336 out=99,826,686 elapsed=465.0s

  [9802/13157] intraday_6644.csv.gz  in=352,097,744 out=99,839,094 elapsed=465.1s

  [9803/13157] intraday_6646.csv.gz  in=352,111,063 out=99,852,413 elapsed=465.1s

  [9804/13157] intraday_6645.csv.gz  in=352,125,194 out=99,866,544 elapsed=465.1s

  [9805/13157] intraday_6647.csv.gz  in=352,141,451 out=99,882,801 elapsed=465.1s

  [9806/13157] intraday_6648.csv.gz  in=352,156,402 out=99,894,557 elapsed=465.2s

  [9807/13157] intraday_6650.csv.gz  in=352,170,637 out=99,908,792 elapsed=465.3s

  [9808/13157] intraday_6651.csv.gz  in=352,184,999 out=99,923,154 elapsed=465.5s

  [9809/13157] intraday_6649.csv.gz  in=352,202,367 out=99,939,744 elapsed=465.5s

  [9810/13157] intraday_6655.csv.gz  in=352,215,519 out=99,952,896 elapsed=465.6s

  [9811/13157] intraday_6653.csv.gz  in=352,228,577 out=99,965,954 elapsed=465.6s

  [9812/13157] intraday_6654.csv.gz  in=352,241,123 out=99,978,500 elapsed=465.6s

  [9813/13157] intraday_6652.csv.gz  in=352,254,880 out=99,992,257 elapsed=465.6s

  [9814/13157] intraday_6656.csv.gz  in=352,269,054 out=100,006,431 elapsed=465.7s

  [9815/13157] intraday_6657.csv.gz  in=352,283,296 out=100,020,673 elapsed=465.7s

  [9816/13157] intraday_6659.csv.gz  in=352,296,980 out=100,034,357 elapsed=465.7s

  [9817/13157] intraday_6658.csv.gz  in=352,309,389 out=100,046,766 elapsed=465.7s

  [9818/13157] intraday_6661.csv.gz  in=352,323,481 out=100,060,858 elapsed=465.7s

  [9819/13157] intraday_6662.csv.gz  in=352,336,412 out=100,073,789 elapsed=465.7s

  [9820/13157] intraday_6660.csv.gz  in=352,351,114 out=100,088,491 elapsed=465.7s

  [9821/13157] intraday_6663.csv.gz  in=352,365,856 out=100,103,233 elapsed=465.8s

  [9822/13157] intraday_6666.csv.gz  in=352,379,583 out=100,116,960 elapsed=465.8s

  [9823/13157] intraday_6665.csv.gz  in=352,391,805 out=100,129,182 elapsed=465.8s

  [9824/13157] intraday_6664.csv.gz  in=352,407,388 out=100,144,765 elapsed=465.8s

  [9825/13157] intraday_6667.csv.gz  in=352,422,770 out=100,160,147 elapsed=465.8s

  [9826/13157] intraday_6668.csv.gz  in=352,435,825 out=100,173,202 elapsed=465.8s

  [9827/13157] intraday_6671.csv.gz  in=352,447,541 out=100,184,918 elapsed=465.9s

  [9828/13157] intraday_6670.csv.gz  in=352,462,271 out=100,199,648 elapsed=465.9s

  [9829/13157] intraday_6669.csv.gz  in=352,473,250 out=100,210,627 elapsed=465.9s

  [9830/13157] intraday_6672.csv.gz  in=352,488,360 out=100,225,737 elapsed=465.9s

  [9831/13157] intraday_6673.csv.gz  in=352,503,952 out=100,241,329 elapsed=466.0s

  [9832/13157] intraday_6676.csv.gz  in=352,516,381 out=100,253,758 elapsed=466.0s

  [9833/13157] intraday_6674.csv.gz  in=352,532,937 out=100,270,314 elapsed=466.0s

  [9834/13157] intraday_6675.csv.gz  in=352,548,045 out=100,285,422 elapsed=466.0s

  [9835/13157] intraday_6680.csv.gz  in=352,562,966 out=100,300,221 elapsed=466.1s

  [9836/13157] intraday_6678.csv.gz  in=352,574,974 out=100,312,229 elapsed=466.1s

  [9837/13157] intraday_6679.csv.gz  in=352,586,131 out=100,323,386 elapsed=466.1s

  [9838/13157] intraday_6677.csv.gz  in=352,598,400 out=100,335,655 elapsed=466.1s

  [9839/13157] intraday_6682.csv.gz  in=352,611,523 out=100,348,778 elapsed=466.1s

  [9840/13157] intraday_6683.csv.gz  in=352,624,398 out=100,361,653 elapsed=466.1s

  [9841/13157] intraday_6681.csv.gz  in=352,635,227 out=100,372,482 elapsed=466.1s

  [9842/13157] intraday_6684.csv.gz  in=352,651,018 out=100,388,273 elapsed=466.1s

  [9843/13157] intraday_6685.csv.gz  in=352,667,555 out=100,401,175 elapsed=466.2s

  [9844/13157] intraday_6686.csv.gz  in=352,680,292 out=100,413,912 elapsed=466.2s

  [9845/13157] intraday_6687.csv.gz  in=352,693,922 out=100,427,542 elapsed=466.3s

  [9846/13157] intraday_6688.csv.gz  in=352,707,870 out=100,439,318 elapsed=466.3s

  [9847/13157] intraday_6689.csv.gz  in=352,720,681 out=100,452,129 elapsed=466.3s

  [9848/13157] intraday_6690.csv.gz  in=352,734,958 out=100,466,406 elapsed=466.3s

  [9849/13157] intraday_6692.csv.gz  in=352,748,624 out=100,480,072 elapsed=466.4s

  [9850/13157] intraday_6691.csv.gz  in=352,763,028 out=100,494,476 elapsed=466.4s

  [9851/13157] intraday_6694.csv.gz  in=352,774,534 out=100,505,982 elapsed=466.4s

  [9852/13157] intraday_6693.csv.gz  in=352,788,061 out=100,519,509 elapsed=466.4s

  [9853/13157] intraday_6695.csv.gz  in=352,801,813 out=100,533,261 elapsed=466.4s

  [9854/13157] intraday_6696.csv.gz  in=352,813,726 out=100,545,174 elapsed=466.4s

  [9855/13157] intraday_6699.csv.gz  in=352,821,924 out=100,553,372 elapsed=466.4s

  [9856/13157] intraday_6697.csv.gz  in=352,834,081 out=100,565,529 elapsed=466.5s

  [9857/13157] intraday_6698.csv.gz  in=352,845,424 out=100,576,872 elapsed=466.5s

  [9858/13157] intraday_6701.csv.gz  in=352,849,196 out=100,580,644 elapsed=466.5s

  [9859/13157] intraday_6702.csv.gz  in=352,849,232 out=100,580,680 elapsed=466.5s

  [9860/13157] intraday_6705.csv.gz  in=352,849,256 out=100,580,704 elapsed=466.5s

  [9861/13157] intraday_6706.csv.gz  in=352,849,266 out=100,580,714 elapsed=466.5s

  [9862/13157] intraday_6704.csv.gz  in=352,849,961 out=100,581,409 elapsed=466.6s

  [9863/13157] intraday_6707.csv.gz  in=352,849,982 out=100,581,430 elapsed=466.6s

  [9864/13157] intraday_6703.csv.gz  in=352,850,191 out=100,581,639 elapsed=466.6s

  [9865/13157] intraday_6700.csv.gz  in=352,863,237 out=100,594,685 elapsed=466.6s

  [9866/13157] intraday_6709.csv.gz  in=352,863,240 out=100,594,688 elapsed=466.6s

  [9867/13157] intraday_6710.csv.gz  in=352,863,265 out=100,594,713 elapsed=466.6s

  [9868/13157] intraday_6708.csv.gz  in=352,863,593 out=100,594,907 elapsed=466.6s

  [9869/13157] intraday_6712.csv.gz  in=352,877,430 out=100,608,744 elapsed=467.0s

  [9870/13157] intraday_6714.csv.gz  in=352,890,175 out=100,621,489 elapsed=467.1s

  [9871/13157] intraday_6713.csv.gz  in=352,904,070 out=100,635,384 elapsed=467.1s

  [9872/13157] intraday_6711.csv.gz  in=352,921,778 out=100,653,036 elapsed=467.1s

  [9873/13157] intraday_6715.csv.gz  in=352,933,903 out=100,665,161 elapsed=467.1s

  [9874/13157] intraday_6716.csv.gz  in=352,949,485 out=100,680,743 elapsed=467.1s

  [9875/13157] intraday_6717.csv.gz  in=352,965,852 out=100,697,110 elapsed=467.1s

  [9876/13157] intraday_6718.csv.gz  in=352,978,641 out=100,709,899 elapsed=467.2s

  [9877/13157] intraday_6719.csv.gz  in=352,992,923 out=100,724,181 elapsed=467.2s

  [9878/13157] intraday_6721.csv.gz  in=353,008,878 out=100,740,136 elapsed=467.3s

  [9879/13157] intraday_6722.csv.gz  in=353,023,877 out=100,755,135 elapsed=467.3s

  [9880/13157] intraday_6720.csv.gz  in=353,038,695 out=100,769,953 elapsed=467.3s

  [9881/13157] intraday_6725.csv.gz  in=353,049,887 out=100,781,145 elapsed=467.3s

  [9882/13157] intraday_6723.csv.gz  in=353,063,522 out=100,794,780 elapsed=467.4s

  [9883/13157] intraday_6724.csv.gz  in=353,077,267 out=100,808,525 elapsed=467.4s

  [9884/13157] intraday_6726.csv.gz  in=353,090,186 out=100,818,586 elapsed=467.4s

  [9885/13157] intraday_6727.csv.gz  in=353,105,021 out=100,833,421 elapsed=467.4s

  [9886/13157] intraday_6728.csv.gz  in=353,119,503 out=100,847,903 elapsed=467.4s

  [9887/13157] intraday_6729.csv.gz  in=353,131,156 out=100,859,556 elapsed=467.4s

  [9888/13157] intraday_6731.csv.gz  in=353,143,419 out=100,871,819 elapsed=467.4s

  [9889/13157] intraday_6730.csv.gz  in=353,156,623 out=100,885,023 elapsed=467.4s

  [9890/13157] intraday_6732.csv.gz  in=353,169,913 out=100,898,313 elapsed=467.5s

  [9891/13157] intraday_6733.csv.gz  in=353,182,415 out=100,910,815 elapsed=467.6s

  [9892/13157] intraday_6734.csv.gz  in=353,196,545 out=100,924,945 elapsed=467.7s

  [9893/13157] intraday_6736.csv.gz  in=353,210,215 out=100,938,615 elapsed=467.7s

  [9894/13157] intraday_6735.csv.gz  in=353,224,365 out=100,952,765 elapsed=467.7s

  [9895/13157] intraday_6738.csv.gz  in=353,237,945 out=100,966,345 elapsed=467.8s

  [9896/13157] intraday_6737.csv.gz  in=353,249,231 out=100,977,631 elapsed=467.8s

  [9897/13157] intraday_6740.csv.gz  in=353,263,131 out=100,991,531 elapsed=467.8s

  [9898/13157] intraday_6739.csv.gz  in=353,275,920 out=101,004,320 elapsed=467.8s

  [9899/13157] intraday_6743.csv.gz  in=353,286,467 out=101,014,867 elapsed=467.9s

  [9900/13157] intraday_6742.csv.gz  in=353,301,497 out=101,029,897 elapsed=467.9s

  [9901/13157] intraday_6744.csv.gz  in=353,315,141 out=101,043,541 elapsed=467.9s

  [9902/13157] intraday_6741.csv.gz  in=353,334,180 out=101,062,580 elapsed=467.9s

  [9903/13157] intraday_6747.csv.gz  in=353,348,179 out=101,076,579 elapsed=468.0s

  [9904/13157] intraday_6746.csv.gz  in=353,368,716 out=101,092,603 elapsed=468.0s

  [9905/13157] intraday_6745.csv.gz  in=353,384,314 out=101,108,201 elapsed=468.0s

  [9906/13157] intraday_6748.csv.gz  in=353,396,610 out=101,120,497 elapsed=468.0s

  [9907/13157] intraday_6749.csv.gz  in=353,409,945 out=101,133,832 elapsed=468.1s

  [9908/13157] intraday_6751.csv.gz  in=353,421,889 out=101,145,776 elapsed=468.1s

  [9909/13157] intraday_6750.csv.gz  in=353,433,293 out=101,157,180 elapsed=468.1s

  [9910/13157] intraday_6752.csv.gz  in=353,446,184 out=101,170,071 elapsed=468.1s

  [9911/13157] intraday_6753.csv.gz  in=353,460,004 out=101,183,891 elapsed=468.2s

  [9912/13157] intraday_6755.csv.gz  in=353,473,604 out=101,197,491 elapsed=468.3s

  [9913/13157] intraday_6756.csv.gz  in=353,486,497 out=101,210,384 elapsed=468.3s

  [9914/13157] intraday_6757.csv.gz  in=353,499,418 out=101,223,305 elapsed=468.3s

  [9915/13157] intraday_6754.csv.gz  in=353,523,232 out=101,238,318 elapsed=468.3s

  [9916/13157] intraday_6758.csv.gz  in=353,538,086 out=101,253,172 elapsed=468.4s

  [9917/13157] intraday_6760.csv.gz  in=353,551,615 out=101,266,701 elapsed=468.4s

  [9918/13157] intraday_6759.csv.gz  in=353,563,881 out=101,278,967 elapsed=468.4s

  [9919/13157] intraday_6761.csv.gz  in=353,575,551 out=101,290,637 elapsed=468.4s

  [9920/13157] intraday_6763.csv.gz  in=353,590,873 out=101,305,959 elapsed=468.4s

  [9921/13157] intraday_6765.csv.gz  in=353,607,598 out=101,322,684 elapsed=468.5s

  [9922/13157] intraday_6764.csv.gz  in=353,617,732 out=101,332,818 elapsed=468.5s

  [9923/13157] intraday_6762.csv.gz  in=353,629,424 out=101,344,510 elapsed=468.5s

  [9924/13157] intraday_6766.csv.gz  in=353,643,503 out=101,358,589 elapsed=468.5s

  [9925/13157] intraday_6767.csv.gz  in=353,657,117 out=101,372,203 elapsed=468.5s

  [9926/13157] intraday_6769.csv.gz  in=353,670,854 out=101,385,940 elapsed=468.6s

  [9927/13157] intraday_6768.csv.gz  in=353,684,730 out=101,399,816 elapsed=468.6s

  [9928/13157] intraday_6771.csv.gz  in=353,698,148 out=101,413,234 elapsed=468.6s

  [9929/13157] intraday_6770.csv.gz  in=353,731,598 out=101,432,150 elapsed=468.6s

  [9930/13157] intraday_6775.csv.gz  in=353,743,567 out=101,444,119 elapsed=468.7s

  [9931/13157] intraday_6773.csv.gz  in=353,755,250 out=101,455,802 elapsed=468.7s

  [9932/13157] intraday_6774.csv.gz  in=353,767,007 out=101,467,559 elapsed=468.7s

  [9933/13157] intraday_6772.csv.gz  in=353,801,907 out=101,487,139 elapsed=468.7s

  [9934/13157] intraday_6776.csv.gz  in=353,818,389 out=101,503,621 elapsed=468.8s

  [9935/13157] intraday_6777.csv.gz  in=353,831,504 out=101,516,736 elapsed=468.8s

  [9936/13157] intraday_6778.csv.gz  in=353,846,146 out=101,531,378 elapsed=468.8s

  [9937/13157] intraday_6779.csv.gz  in=353,859,187 out=101,544,419 elapsed=468.8s

  [9938/13157] intraday_6780.csv.gz  in=353,871,040 out=101,556,272 elapsed=468.8s

  [9939/13157] intraday_6782.csv.gz  in=353,884,185 out=101,569,417 elapsed=469.0s

  [9940/13157] intraday_6781.csv.gz  in=353,895,896 out=101,581,128 elapsed=469.0s

  [9941/13157] intraday_6783.csv.gz  in=353,908,754 out=101,593,986 elapsed=469.0s

  [9942/13157] intraday_6784.csv.gz  in=353,922,112 out=101,607,344 elapsed=469.0s

  [9943/13157] intraday_6785.csv.gz  in=353,933,957 out=101,619,189 elapsed=469.0s

  [9944/13157] intraday_6788.csv.gz  in=353,947,801 out=101,633,033 elapsed=469.1s

  [9945/13157] intraday_6786.csv.gz  in=353,961,105 out=101,646,337 elapsed=469.1s

  [9946/13157] intraday_6787.csv.gz  in=353,971,910 out=101,657,142 elapsed=469.1s

  [9947/13157] intraday_6789.csv.gz  in=353,984,054 out=101,669,286 elapsed=469.2s

  [9948/13157] intraday_6792.csv.gz  in=353,995,684 out=101,680,916 elapsed=469.2s

  [9949/13157] intraday_6791.csv.gz  in=354,005,909 out=101,691,141 elapsed=469.2s

  [9950/13157] intraday_6790.csv.gz  in=354,021,023 out=101,706,255 elapsed=469.2s

  [9951/13157] intraday_6793.csv.gz  in=354,033,243 out=101,718,410 elapsed=469.2s

  [9952/13157] intraday_6795.csv.gz  in=354,049,286 out=101,734,453 elapsed=469.2s

  [9953/13157] intraday_6794.csv.gz  in=354,069,129 out=101,753,581 elapsed=469.3s

  [9954/13157] intraday_6796.csv.gz  in=354,084,307 out=101,768,759 elapsed=469.3s

  [9955/13157] intraday_6798.csv.gz  in=354,098,132 out=101,781,695 elapsed=469.3s

  [9956/13157] intraday_6797.csv.gz  in=354,111,350 out=101,794,913 elapsed=469.3s

  [9957/13157] intraday_6801.csv.gz  in=354,125,253 out=101,808,816 elapsed=469.9s

  [9958/13157] intraday_6799.csv.gz  in=354,139,839 out=101,823,402 elapsed=469.9s

  [9959/13157] intraday_6802.csv.gz  in=354,152,308 out=101,835,871 elapsed=469.9s

  [9960/13157] intraday_6800.csv.gz  in=354,168,695 out=101,852,258 elapsed=469.9s

  [9961/13157] intraday_6805.csv.gz  in=354,182,335 out=101,865,898 elapsed=470.1s

  [9962/13157] intraday_6803.csv.gz  in=354,198,847 out=101,882,410 elapsed=470.2s

  [9963/13157] intraday_6804.csv.gz  in=354,214,343 out=101,897,906 elapsed=470.2s

  [9964/13157] intraday_6806.csv.gz  in=354,228,592 out=101,912,155 elapsed=470.2s

  [9965/13157] intraday_6808.csv.gz  in=354,241,582 out=101,925,145 elapsed=470.2s

  [9966/13157] intraday_6810.csv.gz  in=354,255,653 out=101,939,216 elapsed=470.2s

  [9967/13157] intraday_6807.csv.gz  in=354,268,573 out=101,952,136 elapsed=470.2s

  [9968/13157] intraday_6809.csv.gz  in=354,283,691 out=101,967,254 elapsed=470.2s

  [9969/13157] intraday_6811.csv.gz  in=354,297,139 out=101,980,702 elapsed=470.2s

  [9970/13157] intraday_6812.csv.gz  in=354,310,674 out=101,994,237 elapsed=470.4s

  [9971/13157] intraday_6815.csv.gz  in=354,325,050 out=102,008,613 elapsed=470.4s

  [9972/13157] intraday_6814.csv.gz  in=354,339,089 out=102,022,652 elapsed=470.5s

  [9973/13157] intraday_6816.csv.gz  in=354,350,834 out=102,034,397 elapsed=470.5s

  [9974/13157] intraday_6813.csv.gz  in=354,367,510 out=102,051,073 elapsed=470.5s

  [9975/13157] intraday_6817.csv.gz  in=354,386,225 out=102,069,788 elapsed=470.5s

  [9976/13157] intraday_6818.csv.gz  in=354,399,105 out=102,082,668 elapsed=470.5s

  [9977/13157] intraday_6819.csv.gz  in=354,412,084 out=102,095,647 elapsed=470.5s

  [9978/13157] intraday_6822.csv.gz  in=354,424,827 out=102,108,390 elapsed=470.6s

  [9979/13157] intraday_6821.csv.gz  in=354,438,290 out=102,121,853 elapsed=470.7s

  [9980/13157] intraday_6820.csv.gz  in=354,454,309 out=102,137,872 elapsed=470.7s

  [9981/13157] intraday_6823.csv.gz  in=354,468,739 out=102,152,302 elapsed=470.7s

  [9982/13157] intraday_6824.csv.gz  in=354,481,866 out=102,165,429 elapsed=470.7s

  [9983/13157] intraday_6825.csv.gz  in=354,496,271 out=102,179,834 elapsed=470.7s

  [9984/13157] intraday_6826.csv.gz  in=354,513,606 out=102,197,169 elapsed=470.7s

  [9985/13157] intraday_6827.csv.gz  in=354,529,820 out=102,213,383 elapsed=470.8s

  [9986/13157] intraday_6828.csv.gz  in=354,543,426 out=102,226,989 elapsed=471.0s

  [9987/13157] intraday_6831.csv.gz  in=354,556,300 out=102,239,863 elapsed=471.0s

  [9988/13157] intraday_6830.csv.gz  in=354,571,664 out=102,253,255 elapsed=471.0s

  [9989/13157] intraday_6829.csv.gz  in=354,588,560 out=102,270,151 elapsed=471.0s

  [9990/13157] intraday_6832.csv.gz  in=354,600,271 out=102,281,862 elapsed=471.1s

  [9991/13157] intraday_6833.csv.gz  in=354,615,054 out=102,296,645 elapsed=471.1s

  [9992/13157] intraday_6834.csv.gz  in=354,626,528 out=102,308,119 elapsed=471.1s

  [9993/13157] intraday_6835.csv.gz  in=354,643,810 out=102,324,574 elapsed=471.1s

  [9994/13157] intraday_6836.csv.gz  in=354,655,948 out=102,336,712 elapsed=471.1s

  [9995/13157] intraday_6839.csv.gz  in=354,668,954 out=102,349,718 elapsed=471.2s

  [9996/13157] intraday_6837.csv.gz  in=354,685,945 out=102,366,709 elapsed=471.2s

  [9997/13157] intraday_6838.csv.gz  in=354,699,449 out=102,380,213 elapsed=471.2s

  [9998/13157] intraday_6840.csv.gz  in=354,712,602 out=102,393,366 elapsed=471.2s

  [9999/13157] intraday_6841.csv.gz  in=354,725,140 out=102,405,904 elapsed=471.3s

  [10000/13157] intraday_6842.csv.gz  in=354,737,756 out=102,418,520 elapsed=471.3s

  [10001/13157] intraday_6843.csv.gz  in=354,754,664 out=102,432,281 elapsed=471.3s

  [10002/13157] intraday_6844.csv.gz  in=354,770,141 out=102,447,758 elapsed=471.3s

  [10003/13157] intraday_6847.csv.gz  in=354,784,494 out=102,462,111 elapsed=471.5s

  [10004/13157] intraday_6845.csv.gz  in=354,799,524 out=102,477,141 elapsed=471.5s

  [10005/13157] intraday_6848.csv.gz  in=354,810,684 out=102,488,301 elapsed=471.5s

  [10006/13157] intraday_6846.csv.gz  in=354,832,369 out=102,503,780 elapsed=471.5s

  [10007/13157] intraday_6852.csv.gz  in=354,841,896 out=102,513,307 elapsed=471.7s

  [10008/13157] intraday_6849.csv.gz  in=354,856,320 out=102,527,731 elapsed=471.7s

  [10009/13157] intraday_6850.csv.gz  in=354,867,692 out=102,539,103 elapsed=471.7s

  [10010/13157] intraday_6853.csv.gz  in=354,877,914 out=102,549,325 elapsed=471.7s

  [10011/13157] intraday_6851.csv.gz  in=354,893,012 out=102,564,423 elapsed=471.7s

  [10012/13157] intraday_6854.csv.gz  in=354,905,415 out=102,576,826 elapsed=471.7s

  [10013/13157] intraday_6856.csv.gz  in=354,918,426 out=102,589,837 elapsed=471.8s

  [10014/13157] intraday_6857.csv.gz  in=354,931,667 out=102,603,078 elapsed=471.8s

  [10015/13157] intraday_6859.csv.gz  in=354,945,576 out=102,616,987 elapsed=471.9s

  [10016/13157] intraday_6858.csv.gz  in=354,956,278 out=102,627,689 elapsed=471.9s

  [10017/13157] intraday_6855.csv.gz  in=355,003,677 out=102,651,275 elapsed=471.9s

  [10018/13157] intraday_6861.csv.gz  in=355,020,093 out=102,667,691 elapsed=471.9s

  [10019/13157] intraday_6860.csv.gz  in=355,034,395 out=102,681,993 elapsed=471.9s

  [10020/13157] intraday_6862.csv.gz  in=355,047,015 out=102,694,613 elapsed=471.9s

  [10021/13157] intraday_6863.csv.gz  in=355,059,766 out=102,707,364 elapsed=471.9s

  [10022/13157] intraday_6866.csv.gz  in=355,074,680 out=102,722,278 elapsed=472.0s

  [10023/13157] intraday_6865.csv.gz  in=355,090,171 out=102,737,769 elapsed=472.0s

  [10024/13157] intraday_6864.csv.gz  in=355,105,109 out=102,752,707 elapsed=472.0s

  [10025/13157] intraday_6869.csv.gz  in=355,115,471 out=102,763,069 elapsed=472.0s

  [10026/13157] intraday_6867.csv.gz  in=355,129,272 out=102,776,870 elapsed=472.0s

  [10027/13157] intraday_6870.csv.gz  in=355,138,871 out=102,786,469 elapsed=472.1s

  [10028/13157] intraday_6868.csv.gz  in=355,152,331 out=102,799,929 elapsed=472.1s

  [10029/13157] intraday_6874.csv.gz  in=355,164,113 out=102,811,711 elapsed=472.3s

  [10030/13157] intraday_6872.csv.gz  in=355,178,300 out=102,825,898 elapsed=472.4s

  [10031/13157] intraday_6873.csv.gz  in=355,189,009 out=102,836,607 elapsed=472.4s

  [10032/13157] intraday_6871.csv.gz  in=355,204,629 out=102,852,227 elapsed=472.4s

  [10033/13157] intraday_6875.csv.gz  in=355,217,877 out=102,865,475 elapsed=472.5s

  [10034/13157] intraday_6878.csv.gz  in=355,231,351 out=102,878,949 elapsed=472.6s

  [10035/13157] intraday_6876.csv.gz  in=355,243,828 out=102,891,426 elapsed=472.6s

  [10036/13157] intraday_6877.csv.gz  in=355,254,873 out=102,902,471 elapsed=472.7s

  [10037/13157] intraday_6879.csv.gz  in=355,268,473 out=102,916,071 elapsed=472.7s

  [10038/13157] intraday_6880.csv.gz  in=355,281,035 out=102,928,633 elapsed=472.7s

  [10039/13157] intraday_6882.csv.gz  in=355,293,175 out=102,940,773 elapsed=472.7s

  [10040/13157] intraday_6881.csv.gz  in=355,305,161 out=102,952,759 elapsed=472.7s

  [10041/13157] intraday_6883.csv.gz  in=355,318,039 out=102,965,637 elapsed=472.8s

  [10042/13157] intraday_6885.csv.gz  in=355,335,804 out=102,983,402 elapsed=472.8s

  [10043/13157] intraday_6884.csv.gz  in=355,349,854 out=102,997,452 elapsed=472.8s

  [10044/13157] intraday_6887.csv.gz  in=355,360,272 out=103,007,870 elapsed=472.8s

  [10045/13157] intraday_6886.csv.gz  in=355,375,581 out=103,023,179 elapsed=472.8s

  [10046/13157] intraday_6888.csv.gz  in=355,390,094 out=103,037,692 elapsed=472.9s

  [10047/13157] intraday_6889.csv.gz  in=355,404,979 out=103,052,577 elapsed=472.9s

  [10048/13157] intraday_6890.csv.gz  in=355,417,244 out=103,064,842 elapsed=472.9s

  [10049/13157] intraday_6891.csv.gz  in=355,430,441 out=103,078,039 elapsed=472.9s

  [10050/13157] intraday_6892.csv.gz  in=355,441,297 out=103,088,895 elapsed=473.0s

  [10051/13157] intraday_6893.csv.gz  in=355,454,821 out=103,102,419 elapsed=473.0s

  [10052/13157] intraday_6894.csv.gz  in=355,465,726 out=103,113,324 elapsed=473.1s

  [10053/13157] intraday_6897.csv.gz  in=355,479,827 out=103,127,425 elapsed=473.2s

  [10054/13157] intraday_6898.csv.gz  in=355,492,917 out=103,140,515 elapsed=473.2s

  [10055/13157] intraday_6896.csv.gz  in=355,505,226 out=103,152,824 elapsed=473.2s

  [10056/13157] intraday_6895.csv.gz  in=355,516,324 out=103,163,922 elapsed=473.2s

  [10057/13157] intraday_6900.csv.gz  in=355,528,498 out=103,176,096 elapsed=473.5s

  [10058/13157] intraday_6899.csv.gz  in=355,541,840 out=103,189,438 elapsed=473.5s

  [10059/13157] intraday_6902.csv.gz  in=355,555,984 out=103,203,582 elapsed=473.6s

  [10060/13157] intraday_6901.csv.gz  in=355,567,667 out=103,215,265 elapsed=473.6s

  [10061/13157] intraday_6903.csv.gz  in=355,579,499 out=103,227,097 elapsed=473.6s

  [10062/13157] intraday_6904.csv.gz  in=355,592,381 out=103,239,979 elapsed=473.6s

  [10063/13157] intraday_6905.csv.gz  in=355,603,707 out=103,251,305 elapsed=473.6s

  [10064/13157] intraday_6906.csv.gz  in=355,614,026 out=103,261,624 elapsed=473.6s

  [10065/13157] intraday_6908.csv.gz  in=355,623,562 out=103,271,160 elapsed=473.6s

  [10066/13157] intraday_6907.csv.gz  in=355,640,206 out=103,287,804 elapsed=473.7s

  [10067/13157] intraday_6909.csv.gz  in=355,657,002 out=103,304,600 elapsed=473.7s

  [10068/13157] intraday_6910.csv.gz  in=355,670,643 out=103,318,241 elapsed=473.8s

  [10069/13157] intraday_6912.csv.gz  in=355,682,769 out=103,330,367 elapsed=473.8s

  [10070/13157] intraday_6911.csv.gz  in=355,696,703 out=103,344,301 elapsed=473.8s

  [10071/13157] intraday_6913.csv.gz  in=355,710,447 out=103,358,045 elapsed=473.8s

  [10072/13157] intraday_6915.csv.gz  in=355,723,885 out=103,371,483 elapsed=473.9s

  [10073/13157] intraday_6917.csv.gz  in=355,735,336 out=103,382,934 elapsed=473.9s

  [10074/13157] intraday_6916.csv.gz  in=355,750,284 out=103,397,882 elapsed=473.9s

  [10075/13157] intraday_6914.csv.gz  in=355,764,204 out=103,411,802 elapsed=473.9s

  [10076/13157] intraday_6918.csv.gz  in=355,775,328 out=103,422,926 elapsed=474.0s

  [10077/13157] intraday_6919.csv.gz  in=355,786,564 out=103,434,162 elapsed=474.0s

  [10078/13157] intraday_6920.csv.gz  in=355,801,648 out=103,449,246 elapsed=474.0s

  [10079/13157] intraday_6922.csv.gz  in=355,815,938 out=103,463,536 elapsed=474.1s

  [10080/13157] intraday_6921.csv.gz  in=355,828,999 out=103,476,597 elapsed=474.1s

  [10081/13157] intraday_6923.csv.gz  in=355,841,273 out=103,488,871 elapsed=474.2s

  [10082/13157] intraday_6924.csv.gz  in=355,852,762 out=103,500,360 elapsed=474.2s

  [10083/13157] intraday_6925.csv.gz  in=355,865,727 out=103,513,325 elapsed=474.4s

  [10084/13157] intraday_6926.csv.gz  in=355,878,200 out=103,525,798 elapsed=474.5s

  [10085/13157] intraday_6927.csv.gz  in=355,890,696 out=103,538,294 elapsed=474.5s

  [10086/13157] intraday_6928.csv.gz  in=355,905,143 out=103,552,741 elapsed=474.5s

  [10087/13157] intraday_6929.csv.gz  in=355,917,072 out=103,564,670 elapsed=474.5s

  [10088/13157] intraday_6930.csv.gz  in=355,930,037 out=103,577,635 elapsed=474.6s

  [10089/13157] intraday_6933.csv.gz  in=355,942,059 out=103,589,657 elapsed=474.7s

  [10090/13157] intraday_6931.csv.gz  in=355,953,072 out=103,600,670 elapsed=474.7s

  [10091/13157] intraday_6932.csv.gz  in=355,967,042 out=103,614,640 elapsed=474.7s

  [10092/13157] intraday_6935.csv.gz  in=355,976,741 out=103,624,339 elapsed=475.1s

  [10093/13157] intraday_6934.csv.gz  in=355,990,622 out=103,638,220 elapsed=475.1s

  [10094/13157] intraday_6937.csv.gz  in=356,003,964 out=103,651,562 elapsed=475.2s

  [10095/13157] intraday_6936.csv.gz  in=356,015,664 out=103,663,262 elapsed=475.2s

  [10096/13157] intraday_6938.csv.gz  in=356,032,387 out=103,679,985 elapsed=475.2s

  [10097/13157] intraday_6940.csv.gz  in=356,046,144 out=103,693,742 elapsed=475.4s

  [10098/13157] intraday_6942.csv.gz  in=356,057,948 out=103,705,546 elapsed=475.4s

  [10099/13157] intraday_6939.csv.gz  in=356,073,567 out=103,721,165 elapsed=475.4s

  [10100/13157] intraday_6941.csv.gz  in=356,086,584 out=103,734,182 elapsed=475.5s

  [10101/13157] intraday_6946.csv.gz  in=356,098,255 out=103,745,853 elapsed=475.6s

  [10102/13157] intraday_6943.csv.gz  in=356,112,595 out=103,760,193 elapsed=475.6s

  [10103/13157] intraday_6944.csv.gz  in=356,130,157 out=103,777,755 elapsed=475.6s

  [10104/13157] intraday_6945.csv.gz  in=356,161,669 out=103,794,310 elapsed=475.6s

  [10105/13157] intraday_6949.csv.gz  in=356,176,148 out=103,808,789 elapsed=475.7s

  [10106/13157] intraday_6950.csv.gz  in=356,189,718 out=103,822,359 elapsed=475.7s

  [10107/13157] intraday_6947.csv.gz  in=356,205,174 out=103,837,815 elapsed=475.7s

  [10108/13157] intraday_6948.csv.gz  in=356,220,395 out=103,853,036 elapsed=475.7s

  [10109/13157] intraday_6951.csv.gz  in=356,233,480 out=103,866,121 elapsed=475.9s

  [10110/13157] intraday_6953.csv.gz  in=356,247,750 out=103,880,391 elapsed=475.9s

  [10111/13157] intraday_6952.csv.gz  in=356,260,067 out=103,892,708 elapsed=475.9s

  [10112/13157] intraday_6954.csv.gz  in=356,274,341 out=103,906,982 elapsed=475.9s

  [10113/13157] intraday_6958.csv.gz  in=356,288,260 out=103,920,901 elapsed=476.1s

  [10114/13157] intraday_6955.csv.gz  in=356,299,496 out=103,932,137 elapsed=476.1s

  [10115/13157] intraday_6957.csv.gz  in=356,315,229 out=103,947,870 elapsed=476.1s

  [10116/13157] intraday_6956.csv.gz  in=356,328,349 out=103,960,990 elapsed=476.1s

  [10117/13157] intraday_6959.csv.gz  in=356,342,248 out=103,974,889 elapsed=476.7s

  [10118/13157] intraday_6960.csv.gz  in=356,356,031 out=103,988,539 elapsed=476.7s

  [10119/13157] intraday_6961.csv.gz  in=356,372,144 out=104,004,652 elapsed=476.7s

  [10120/13157] intraday_6962.csv.gz  in=356,384,777 out=104,017,285 elapsed=476.7s

  [10121/13157] intraday_6965.csv.gz  in=356,398,826 out=104,031,334 elapsed=476.9s

  [10122/13157] intraday_6963.csv.gz  in=356,411,847 out=104,044,355 elapsed=476.9s

  [10123/13157] intraday_6966.csv.gz  in=356,422,814 out=104,055,322 elapsed=476.9s

  [10124/13157] intraday_6964.csv.gz  in=356,438,225 out=104,070,733 elapsed=476.9s

  [10125/13157] intraday_6967.csv.gz  in=356,453,422 out=104,085,930 elapsed=476.9s

  [10126/13157] intraday_6969.csv.gz  in=356,467,405 out=104,099,913 elapsed=477.0s

  [10127/13157] intraday_6968.csv.gz  in=356,479,786 out=104,112,294 elapsed=477.0s

  [10128/13157] intraday_6970.csv.gz  in=356,495,504 out=104,128,012 elapsed=477.0s

  [10129/13157] intraday_6971.csv.gz  in=356,511,976 out=104,144,484 elapsed=477.0s

  [10130/13157] intraday_6973.csv.gz  in=356,526,080 out=104,158,588 elapsed=477.1s

  [10131/13157] intraday_6974.csv.gz  in=356,538,758 out=104,171,266 elapsed=477.1s

  [10132/13157] intraday_6972.csv.gz  in=356,553,969 out=104,186,477 elapsed=477.1s

  [10133/13157] intraday_6975.csv.gz  in=356,566,853 out=104,199,361 elapsed=477.1s

  [10134/13157] intraday_6976.csv.gz  in=356,577,605 out=104,210,113 elapsed=477.2s

  [10135/13157] intraday_6979.csv.gz  in=356,591,397 out=104,223,905 elapsed=477.2s

  [10136/13157] intraday_6978.csv.gz  in=356,602,999 out=104,235,507 elapsed=477.2s

  [10137/13157] intraday_6977.csv.gz  in=356,618,035 out=104,250,543 elapsed=477.3s

  [10138/13157] intraday_6982.csv.gz  in=356,630,311 out=104,262,819 elapsed=477.3s

  [10139/13157] intraday_6980.csv.gz  in=356,642,901 out=104,275,409 elapsed=477.3s

  [10140/13157] intraday_6981.csv.gz  in=356,658,390 out=104,290,898 elapsed=477.3s

  [10141/13157] intraday_6983.csv.gz  in=356,670,339 out=104,302,847 elapsed=477.3s

  [10142/13157] intraday_6984.csv.gz  in=356,682,637 out=104,315,145 elapsed=477.3s

  [10143/13157] intraday_6985.csv.gz  in=356,696,011 out=104,328,519 elapsed=477.3s

  [10144/13157] intraday_6986.csv.gz  in=356,707,204 out=104,339,712 elapsed=477.3s

  [10145/13157] intraday_6988.csv.gz  in=356,721,634 out=104,354,142 elapsed=477.4s

  [10146/13157] intraday_6989.csv.gz  in=356,736,555 out=104,369,063 elapsed=477.4s

  [10147/13157] intraday_6990.csv.gz  in=356,776,126 out=104,389,360 elapsed=477.4s

  [10148/13157] intraday_6991.csv.gz  in=356,787,428 out=104,400,662 elapsed=477.5s

  [10149/13157] intraday_6992.csv.gz  in=356,799,338 out=104,412,572 elapsed=477.5s

  [10150/13157] intraday_6987.csv.gz  in=356,814,894 out=104,428,128 elapsed=477.5s

  [10151/13157] intraday_6993.csv.gz  in=356,828,509 out=104,441,743 elapsed=477.6s

  [10152/13157] intraday_6996.csv.gz  in=356,838,175 out=104,451,409 elapsed=477.6s

  [10153/13157] intraday_6995.csv.gz  in=356,850,342 out=104,463,576 elapsed=477.6s

  [10154/13157] intraday_6994.csv.gz  in=356,862,725 out=104,475,959 elapsed=477.6s

  [10155/13157] intraday_6998.csv.gz  in=356,870,018 out=104,483,252 elapsed=477.7s

  [10156/13157] intraday_6997.csv.gz  in=356,883,374 out=104,496,608 elapsed=477.7s

  [10157/13157] intraday_7000.csv.gz  in=356,895,703 out=104,508,937 elapsed=477.7s

  [10158/13157] intraday_6999.csv.gz  in=356,912,242 out=104,525,476 elapsed=477.7s

  [10159/13157] intraday_7002.csv.gz  in=356,922,674 out=104,535,908 elapsed=477.8s

  [10160/13157] intraday_7001.csv.gz  in=356,936,251 out=104,549,485 elapsed=477.8s

  [10161/13157] intraday_7003.csv.gz  in=356,949,911 out=104,563,145 elapsed=477.8s

  [10162/13157] intraday_7004.csv.gz  in=356,965,063 out=104,578,297 elapsed=477.8s

  [10163/13157] intraday_7005.csv.gz  in=356,981,919 out=104,595,153 elapsed=477.9s

  [10164/13157] intraday_7007.csv.gz  in=356,995,419 out=104,608,653 elapsed=477.9s

  [10165/13157] intraday_7006.csv.gz  in=357,007,287 out=104,620,521 elapsed=477.9s

  [10166/13157] intraday_7008.csv.gz  in=357,021,500 out=104,634,734 elapsed=477.9s

  [10167/13157] intraday_7009.csv.gz  in=357,037,828 out=104,651,062 elapsed=477.9s

  [10168/13157] intraday_7010.csv.gz  in=357,053,063 out=104,666,297 elapsed=478.0s

  [10169/13157] intraday_7011.csv.gz  in=357,065,694 out=104,678,928 elapsed=478.0s

  [10170/13157] intraday_7012.csv.gz  in=357,079,601 out=104,692,835 elapsed=478.0s

  [10171/13157] intraday_7013.csv.gz  in=357,089,087 out=104,702,321 elapsed=478.0s

  [10172/13157] intraday_7017.csv.gz  in=357,101,192 out=104,714,426 elapsed=478.0s

  [10173/13157] intraday_7014.csv.gz  in=357,111,306 out=104,724,540 elapsed=478.0s

  [10174/13157] intraday_7016.csv.gz  in=357,125,356 out=104,738,590 elapsed=478.0s

  [10175/13157] intraday_7015.csv.gz  in=357,140,584 out=104,753,818 elapsed=478.0s

  [10176/13157] intraday_7018.csv.gz  in=357,151,893 out=104,765,127 elapsed=478.1s

  [10177/13157] intraday_7021.csv.gz  in=357,163,833 out=104,777,067 elapsed=478.1s

  [10178/13157] intraday_7020.csv.gz  in=357,176,492 out=104,789,726 elapsed=478.1s

  [10179/13157] intraday_7019.csv.gz  in=357,188,658 out=104,801,892 elapsed=478.1s

  [10180/13157] intraday_7022.csv.gz  in=357,201,854 out=104,815,088 elapsed=478.2s

  [10181/13157] intraday_7023.csv.gz  in=357,215,190 out=104,828,424 elapsed=478.3s

  [10182/13157] intraday_7025.csv.gz  in=357,226,736 out=104,839,970 elapsed=478.3s

  [10183/13157] intraday_7024.csv.gz  in=357,240,847 out=104,854,081 elapsed=478.3s

  [10184/13157] intraday_7026.csv.gz  in=357,253,824 out=104,867,058 elapsed=478.3s

  [10185/13157] intraday_7027.csv.gz  in=357,265,109 out=104,878,343 elapsed=478.3s

  [10186/13157] intraday_7030.csv.gz  in=357,279,874 out=104,893,108 elapsed=478.4s

  [10187/13157] intraday_7028.csv.gz  in=357,294,427 out=104,907,661 elapsed=478.4s

  [10188/13157] intraday_7031.csv.gz  in=357,305,418 out=104,918,652 elapsed=478.4s

  [10189/13157] intraday_7029.csv.gz  in=357,323,621 out=104,936,855 elapsed=478.4s

  [10190/13157] intraday_7032.csv.gz  in=357,339,309 out=104,950,436 elapsed=478.4s

  [10191/13157] intraday_7033.csv.gz  in=357,354,439 out=104,965,566 elapsed=478.4s

  [10192/13157] intraday_7035.csv.gz  in=357,366,913 out=104,978,040 elapsed=478.5s

  [10193/13157] intraday_7034.csv.gz  in=357,379,350 out=104,990,477 elapsed=478.5s

  [10194/13157] intraday_7037.csv.gz  in=357,392,188 out=105,003,315 elapsed=478.5s

  [10195/13157] intraday_7036.csv.gz  in=357,403,772 out=105,014,899 elapsed=478.5s

  [10196/13157] intraday_7038.csv.gz  in=357,414,192 out=105,025,319 elapsed=478.6s

  [10197/13157] intraday_7039.csv.gz  in=357,425,653 out=105,036,780 elapsed=478.6s

  [10198/13157] intraday_7041.csv.gz  in=357,438,408 out=105,049,535 elapsed=478.7s

  [10199/13157] intraday_7040.csv.gz  in=357,450,715 out=105,061,842 elapsed=478.7s

  [10200/13157] intraday_7043.csv.gz  in=357,464,060 out=105,075,187 elapsed=478.7s

  [10201/13157] intraday_7042.csv.gz  in=357,477,739 out=105,088,866 elapsed=478.7s

  [10202/13157] intraday_7044.csv.gz  in=357,490,464 out=105,101,591 elapsed=478.9s

  [10203/13157] intraday_7047.csv.gz  in=357,504,424 out=105,115,551 elapsed=479.0s

  [10204/13157] intraday_7046.csv.gz  in=357,516,741 out=105,127,868 elapsed=479.0s

  [10205/13157] intraday_7045.csv.gz  in=357,528,996 out=105,140,123 elapsed=479.0s

  [10206/13157] intraday_7050.csv.gz  in=357,539,131 out=105,150,258 elapsed=479.2s

  [10207/13157] intraday_7048.csv.gz  in=357,551,627 out=105,162,754 elapsed=479.4s

  [10208/13157] intraday_7049.csv.gz  in=357,563,196 out=105,174,323 elapsed=479.4s

  [10209/13157] intraday_7052.csv.gz  in=357,573,103 out=105,184,230 elapsed=479.6s

  [10210/13157] intraday_7051.csv.gz  in=357,588,473 out=105,199,600 elapsed=479.6s

  [10211/13157] intraday_7053.csv.gz  in=357,603,211 out=105,214,338 elapsed=479.6s

  [10212/13157] intraday_7054.csv.gz  in=357,618,366 out=105,229,493 elapsed=479.6s

  [10213/13157] intraday_7055.csv.gz  in=357,631,573 out=105,242,700 elapsed=479.6s

  [10214/13157] intraday_7057.csv.gz  in=357,644,582 out=105,255,709 elapsed=479.7s

  [10215/13157] intraday_7056.csv.gz  in=357,657,478 out=105,268,605 elapsed=479.7s

  [10216/13157] intraday_7058.csv.gz  in=357,671,317 out=105,282,444 elapsed=479.7s

  [10217/13157] intraday_7059.csv.gz  in=357,685,259 out=105,296,386 elapsed=479.7s

  [10218/13157] intraday_7062.csv.gz  in=357,696,937 out=105,308,064 elapsed=479.7s

  [10219/13157] intraday_7061.csv.gz  in=357,709,039 out=105,320,166 elapsed=479.7s

  [10220/13157] intraday_7060.csv.gz  in=357,722,555 out=105,333,682 elapsed=479.7s

  [10221/13157] intraday_7063.csv.gz  in=357,733,874 out=105,345,001 elapsed=479.8s

  [10222/13157] intraday_7064.csv.gz  in=357,748,969 out=105,360,096 elapsed=479.8s

  [10223/13157] intraday_7065.csv.gz  in=357,761,907 out=105,373,034 elapsed=479.8s

  [10224/13157] intraday_7066.csv.gz  in=357,776,009 out=105,387,136 elapsed=479.8s

  [10225/13157] intraday_7067.csv.gz  in=357,789,639 out=105,400,766 elapsed=479.9s

  [10226/13157] intraday_7070.csv.gz  in=357,802,511 out=105,413,638 elapsed=479.9s

  [10227/13157] intraday_7069.csv.gz  in=357,813,981 out=105,425,108 elapsed=479.9s

  [10228/13157] intraday_7068.csv.gz  in=357,835,093 out=105,438,489 elapsed=479.9s

  [10229/13157] intraday_7073.csv.gz  in=357,846,482 out=105,449,878 elapsed=480.0s

  [10230/13157] intraday_7074.csv.gz  in=357,859,606 out=105,463,002 elapsed=480.0s

  [10231/13157] intraday_7072.csv.gz  in=357,874,133 out=105,477,529 elapsed=480.0s

  [10232/13157] intraday_7071.csv.gz  in=357,887,039 out=105,490,435 elapsed=480.0s

  [10233/13157] intraday_7075.csv.gz  in=357,897,792 out=105,501,188 elapsed=480.0s

  [10234/13157] intraday_7078.csv.gz  in=357,910,403 out=105,513,799 elapsed=480.2s

  [10235/13157] intraday_7076.csv.gz  in=357,924,292 out=105,527,688 elapsed=480.2s

  [10236/13157] intraday_7079.csv.gz  in=357,939,926 out=105,539,805 elapsed=480.2s

  [10237/13157] intraday_7077.csv.gz  in=357,962,587 out=105,554,182 elapsed=480.2s

  [10238/13157] intraday_7081.csv.gz  in=357,974,028 out=105,565,623 elapsed=480.4s

  [10239/13157] intraday_7083.csv.gz  in=357,990,935 out=105,582,530 elapsed=480.4s

  [10240/13157] intraday_7082.csv.gz  in=358,008,514 out=105,600,109 elapsed=480.4s

  [10241/13157] intraday_7080.csv.gz  in=358,030,410 out=105,613,650 elapsed=480.4s

  [10242/13157] intraday_7084.csv.gz  in=358,044,815 out=105,628,055 elapsed=480.5s

  [10243/13157] intraday_7086.csv.gz  in=358,056,294 out=105,639,534 elapsed=480.6s

  [10244/13157] intraday_7085.csv.gz  in=358,068,304 out=105,651,544 elapsed=480.6s

  [10245/13157] intraday_7087.csv.gz  in=358,083,825 out=105,667,065 elapsed=480.6s

  [10246/13157] intraday_7090.csv.gz  in=358,096,709 out=105,679,133 elapsed=480.7s

  [10247/13157] intraday_7088.csv.gz  in=358,109,687 out=105,692,111 elapsed=480.7s

  [10248/13157] intraday_7089.csv.gz  in=358,125,708 out=105,708,132 elapsed=480.7s

  [10249/13157] intraday_7091.csv.gz  in=358,140,316 out=105,722,740 elapsed=480.8s

  [10250/13157] intraday_7093.csv.gz  in=358,153,373 out=105,735,797 elapsed=480.9s

  [10251/13157] intraday_7094.csv.gz  in=358,168,956 out=105,751,380 elapsed=480.9s

  [10252/13157] intraday_7095.csv.gz  in=358,195,198 out=105,768,272 elapsed=480.9s

  [10253/13157] intraday_7092.csv.gz  in=358,210,344 out=105,783,418 elapsed=480.9s

  [10254/13157] intraday_7096.csv.gz  in=358,224,156 out=105,797,230 elapsed=480.9s

  [10255/13157] intraday_7097.csv.gz  in=358,238,061 out=105,811,135 elapsed=481.0s

  [10256/13157] intraday_7098.csv.gz  in=358,251,553 out=105,824,627 elapsed=481.0s

  [10257/13157] intraday_7099.csv.gz  in=358,263,746 out=105,836,820 elapsed=481.0s

  [10258/13157] intraday_7100.csv.gz  in=358,277,580 out=105,850,654 elapsed=481.0s

  [10259/13157] intraday_7101.csv.gz  in=358,294,519 out=105,864,035 elapsed=481.0s

  [10260/13157] intraday_7103.csv.gz  in=358,306,107 out=105,875,623 elapsed=481.0s

  [10261/13157] intraday_7102.csv.gz  in=358,321,833 out=105,891,349 elapsed=481.0s

  [10262/13157] intraday_7106.csv.gz  in=358,333,665 out=105,903,181 elapsed=481.1s

  [10263/13157] intraday_7107.csv.gz  in=358,345,907 out=105,915,423 elapsed=481.2s

  [10264/13157] intraday_7104.csv.gz  in=358,358,832 out=105,928,348 elapsed=481.2s

  [10265/13157] intraday_7105.csv.gz  in=358,376,977 out=105,946,493 elapsed=481.2s

  [10266/13157] intraday_7108.csv.gz  in=358,392,894 out=105,962,410 elapsed=481.2s

  [10267/13157] intraday_7109.csv.gz  in=358,407,951 out=105,977,467 elapsed=481.2s

  [10268/13157] intraday_7110.csv.gz  in=358,420,695 out=105,990,211 elapsed=481.2s

  [10269/13157] intraday_7111.csv.gz  in=358,433,783 out=106,003,299 elapsed=481.3s

  [10270/13157] intraday_7113.csv.gz  in=358,445,735 out=106,015,251 elapsed=481.3s

  [10271/13157] intraday_7112.csv.gz  in=358,458,366 out=106,027,882 elapsed=481.3s

  [10272/13157] intraday_7114.csv.gz  in=358,476,156 out=106,045,672 elapsed=481.3s

  [10273/13157] intraday_7115.csv.gz  in=358,490,440 out=106,059,956 elapsed=481.3s

  [10274/13157] intraday_7119.csv.gz  in=358,502,446 out=106,071,962 elapsed=481.4s

  [10275/13157] intraday_7117.csv.gz  in=358,518,602 out=106,088,118 elapsed=481.4s

  [10276/13157] intraday_7116.csv.gz  in=358,533,817 out=106,103,333 elapsed=481.4s

  [10277/13157] intraday_7118.csv.gz  in=358,547,611 out=106,117,127 elapsed=481.4s

  [10278/13157] intraday_7120.csv.gz  in=358,560,051 out=106,129,567 elapsed=481.4s

  [10279/13157] intraday_7122.csv.gz  in=358,571,910 out=106,141,426 elapsed=481.4s

  [10280/13157] intraday_7121.csv.gz  in=358,585,171 out=106,154,687 elapsed=481.4s

  [10281/13157] intraday_7124.csv.gz  in=358,598,603 out=106,168,119 elapsed=481.5s

  [10282/13157] intraday_7125.csv.gz  in=358,612,633 out=106,182,149 elapsed=481.5s

  [10283/13157] intraday_7126.csv.gz  in=358,627,587 out=106,197,103 elapsed=481.5s

  [10284/13157] intraday_7123.csv.gz  in=358,663,059 out=106,215,753 elapsed=481.5s

  [10285/13157] intraday_7127.csv.gz  in=358,675,793 out=106,228,487 elapsed=482.1s

  [10286/13157] intraday_7130.csv.gz  in=358,688,212 out=106,240,906 elapsed=482.1s

  [10287/13157] intraday_7128.csv.gz  in=358,700,145 out=106,252,839 elapsed=482.1s

  [10288/13157] intraday_7129.csv.gz  in=358,714,108 out=106,266,802 elapsed=482.2s

  [10289/13157] intraday_7131.csv.gz  in=358,726,414 out=106,279,108 elapsed=482.4s

  [10290/13157] intraday_7133.csv.gz  in=358,741,712 out=106,294,406 elapsed=482.4s

  [10291/13157] intraday_7134.csv.gz  in=358,756,364 out=106,309,058 elapsed=482.4s

  [10292/13157] intraday_7132.csv.gz  in=358,771,137 out=106,323,831 elapsed=482.4s

  [10293/13157] intraday_7135.csv.gz  in=358,784,933 out=106,337,627 elapsed=482.4s

  [10294/13157] intraday_7136.csv.gz  in=358,795,969 out=106,348,663 elapsed=482.4s

  [10295/13157] intraday_7138.csv.gz  in=358,807,984 out=106,360,678 elapsed=482.4s

  [10296/13157] intraday_7137.csv.gz  in=358,821,579 out=106,374,273 elapsed=482.4s

  [10297/13157] intraday_7139.csv.gz  in=358,836,589 out=106,389,283 elapsed=482.5s

  [10298/13157] intraday_7143.csv.gz  in=358,837,230 out=106,389,924 elapsed=482.5s

  [10299/13157] intraday_7141.csv.gz  in=358,846,940 out=106,399,634 elapsed=482.5s

  [10300/13157] intraday_7140.csv.gz  in=358,856,622 out=106,408,998 elapsed=482.5s

  [10301/13157] intraday_7142.csv.gz  in=358,870,378 out=106,422,754 elapsed=482.5s

  [10302/13157] intraday_7144.csv.gz  in=358,887,255 out=106,439,631 elapsed=482.5s

  [10303/13157] intraday_7147.csv.gz  in=358,898,549 out=106,450,925 elapsed=482.6s

  [10304/13157] intraday_7146.csv.gz  in=358,911,643 out=106,464,019 elapsed=482.6s

  [10305/13157] intraday_7145.csv.gz  in=358,926,134 out=106,478,510 elapsed=482.6s

  [10306/13157] intraday_7148.csv.gz  in=358,937,756 out=106,490,132 elapsed=482.6s

  [10307/13157] intraday_7149.csv.gz  in=358,952,322 out=106,504,698 elapsed=482.6s

  [10308/13157] intraday_7152.csv.gz  in=358,965,545 out=106,517,921 elapsed=482.7s

  [10309/13157] intraday_7150.csv.gz  in=358,980,844 out=106,533,220 elapsed=482.7s

  [10310/13157] intraday_7151.csv.gz  in=358,992,837 out=106,545,213 elapsed=482.7s

  [10311/13157] intraday_7153.csv.gz  in=359,006,311 out=106,558,687 elapsed=482.8s

  [10312/13157] intraday_7156.csv.gz  in=359,019,288 out=106,571,664 elapsed=482.8s

  [10313/13157] intraday_7155.csv.gz  in=359,035,277 out=106,587,653 elapsed=482.8s

  [10314/13157] intraday_7154.csv.gz  in=359,055,089 out=106,605,954 elapsed=482.8s

  [10315/13157] intraday_7159.csv.gz  in=359,063,982 out=106,614,847 elapsed=482.8s

  [10316/13157] intraday_7158.csv.gz  in=359,073,685 out=106,624,550 elapsed=482.9s

  [10317/13157] intraday_7157.csv.gz  in=359,086,641 out=106,637,506 elapsed=482.9s

  [10318/13157] intraday_7160.csv.gz  in=359,101,570 out=106,652,435 elapsed=482.9s

  [10319/13157] intraday_7162.csv.gz  in=359,114,025 out=106,664,890 elapsed=483.1s

  [10320/13157] intraday_7164.csv.gz  in=359,126,932 out=106,677,778 elapsed=483.1s

  [10321/13157] intraday_7163.csv.gz  in=359,137,470 out=106,688,316 elapsed=483.1s

  [10322/13157] intraday_7161.csv.gz  in=359,150,807 out=106,701,653 elapsed=483.1s

  [10323/13157] intraday_7165.csv.gz  in=359,164,465 out=106,715,311 elapsed=483.4s

  [10324/13157] intraday_7166.csv.gz  in=359,175,137 out=106,725,983 elapsed=483.6s

  [10325/13157] intraday_7168.csv.gz  in=359,188,190 out=106,739,036 elapsed=483.6s

  [10326/13157] intraday_7167.csv.gz  in=359,200,731 out=106,751,577 elapsed=483.6s

  [10327/13157] intraday_7169.csv.gz  in=359,214,128 out=106,764,974 elapsed=483.6s

  [10328/13157] intraday_7170.csv.gz  in=359,224,710 out=106,775,556 elapsed=483.7s

  [10329/13157] intraday_7171.csv.gz  in=359,239,693 out=106,788,401 elapsed=483.7s

  [10330/13157] intraday_7173.csv.gz  in=359,253,021 out=106,801,729 elapsed=483.7s

  [10331/13157] intraday_7172.csv.gz  in=359,264,318 out=106,813,026 elapsed=483.7s

  [10332/13157] intraday_7175.csv.gz  in=359,277,886 out=106,826,594 elapsed=483.7s

  [10333/13157] intraday_7174.csv.gz  in=359,294,190 out=106,842,898 elapsed=483.7s

  [10334/13157] intraday_7176.csv.gz  in=359,305,833 out=106,854,541 elapsed=483.7s

  [10335/13157] intraday_7177.csv.gz  in=359,317,490 out=106,866,198 elapsed=483.8s

  [10336/13157] intraday_7179.csv.gz  in=359,328,558 out=106,877,266 elapsed=483.8s

  [10337/13157] intraday_7178.csv.gz  in=359,342,531 out=106,891,239 elapsed=483.8s

  [10338/13157] intraday_7180.csv.gz  in=359,356,810 out=106,905,518 elapsed=483.8s

  [10339/13157] intraday_7181.csv.gz  in=359,366,569 out=106,915,277 elapsed=483.8s

  [10340/13157] intraday_7182.csv.gz  in=359,378,391 out=106,927,099 elapsed=483.8s

  [10341/13157] intraday_7183.csv.gz  in=359,389,415 out=106,938,123 elapsed=483.8s

  [10342/13157] intraday_7184.csv.gz  in=359,400,737 out=106,949,445 elapsed=483.9s

  [10343/13157] intraday_7185.csv.gz  in=359,413,124 out=106,961,832 elapsed=483.9s

  [10344/13157] intraday_7186.csv.gz  in=359,428,141 out=106,976,849 elapsed=483.9s

  [10345/13157] intraday_7188.csv.gz  in=359,442,382 out=106,991,090 elapsed=483.9s

  [10346/13157] intraday_7189.csv.gz  in=359,455,034 out=107,003,742 elapsed=483.9s

  [10347/13157] intraday_7187.csv.gz  in=359,466,437 out=107,015,145 elapsed=484.0s

  [10348/13157] intraday_7190.csv.gz  in=359,477,240 out=107,025,948 elapsed=484.0s

  [10349/13157] intraday_7191.csv.gz  in=359,490,780 out=107,039,488 elapsed=484.0s

  [10350/13157] intraday_7193.csv.gz  in=359,502,502 out=107,051,210 elapsed=484.0s

  [10351/13157] intraday_7192.csv.gz  in=359,514,674 out=107,063,382 elapsed=484.0s

  [10352/13157] intraday_7194.csv.gz  in=359,525,030 out=107,073,738 elapsed=484.1s

  [10353/13157] intraday_7195.csv.gz  in=359,536,069 out=107,084,777 elapsed=484.1s

  [10354/13157] intraday_7196.csv.gz  in=359,549,694 out=107,098,402 elapsed=484.1s

  [10355/13157] intraday_7197.csv.gz  in=359,561,016 out=107,109,724 elapsed=484.1s

  [10356/13157] intraday_7200.csv.gz  in=359,574,212 out=107,122,920 elapsed=484.1s

  [10357/13157] intraday_7198.csv.gz  in=359,588,583 out=107,137,291 elapsed=484.1s

  [10358/13157] intraday_7199.csv.gz  in=359,602,331 out=107,151,039 elapsed=484.1s

  [10359/13157] intraday_7201.csv.gz  in=359,613,008 out=107,161,716 elapsed=484.1s

  [10360/13157] intraday_7203.csv.gz  in=359,627,488 out=107,176,196 elapsed=484.2s

  [10361/13157] intraday_7202.csv.gz  in=359,639,633 out=107,188,341 elapsed=484.2s

  [10362/13157] intraday_7204.csv.gz  in=359,652,722 out=107,201,430 elapsed=484.2s

  [10363/13157] intraday_7205.csv.gz  in=359,665,501 out=107,214,209 elapsed=484.2s

  [10364/13157] intraday_7206.csv.gz  in=359,676,913 out=107,225,621 elapsed=484.3s

  [10365/13157] intraday_7207.csv.gz  in=359,686,699 out=107,235,407 elapsed=484.3s

  [10366/13157] intraday_7208.csv.gz  in=359,697,472 out=107,246,180 elapsed=484.3s

  [10367/13157] intraday_7209.csv.gz  in=359,713,348 out=107,262,056 elapsed=484.3s

  [10368/13157] intraday_7211.csv.gz  in=359,726,702 out=107,275,410 elapsed=484.3s

  [10369/13157] intraday_7210.csv.gz  in=359,739,848 out=107,288,556 elapsed=484.3s

  [10370/13157] intraday_7212.csv.gz  in=359,752,107 out=107,300,815 elapsed=484.8s

  [10371/13157] intraday_7215.csv.gz  in=359,763,823 out=107,312,531 elapsed=484.8s

  [10372/13157] intraday_7213.csv.gz  in=359,781,159 out=107,326,607 elapsed=484.8s

  [10373/13157] intraday_7214.csv.gz  in=359,793,870 out=107,339,318 elapsed=484.8s

  [10374/13157] intraday_7216.csv.gz  in=359,805,336 out=107,350,784 elapsed=485.0s

  [10375/13157] intraday_7217.csv.gz  in=359,818,629 out=107,364,077 elapsed=485.0s

  [10376/13157] intraday_7219.csv.gz  in=359,832,208 out=107,376,294 elapsed=485.0s

  [10377/13157] intraday_7218.csv.gz  in=359,843,915 out=107,388,001 elapsed=485.0s

  [10378/13157] intraday_7220.csv.gz  in=359,857,091 out=107,401,177 elapsed=485.0s

  [10379/13157] intraday_7221.csv.gz  in=359,869,349 out=107,413,435 elapsed=485.2s

  [10380/13157] intraday_7224.csv.gz  in=359,880,075 out=107,423,407 elapsed=485.2s

  [10381/13157] intraday_7222.csv.gz  in=359,890,704 out=107,434,036 elapsed=485.2s

  [10382/13157] intraday_7223.csv.gz  in=359,903,817 out=107,447,149 elapsed=485.2s

  [10383/13157] intraday_7225.csv.gz  in=359,915,767 out=107,459,099 elapsed=485.4s

  [10384/13157] intraday_7226.csv.gz  in=359,928,675 out=107,472,007 elapsed=485.4s

  [10385/13157] intraday_7228.csv.gz  in=359,943,115 out=107,486,447 elapsed=485.4s

  [10386/13157] intraday_7227.csv.gz  in=359,959,355 out=107,502,687 elapsed=485.4s

  [10387/13157] intraday_7232.csv.gz  in=359,972,008 out=107,515,340 elapsed=485.5s

  [10388/13157] intraday_7231.csv.gz  in=359,983,489 out=107,526,821 elapsed=485.5s

  [10389/13157] intraday_7229.csv.gz  in=359,997,030 out=107,540,362 elapsed=485.5s

  [10390/13157] intraday_7230.csv.gz  in=360,009,541 out=107,552,873 elapsed=485.5s

  [10391/13157] intraday_7235.csv.gz  in=360,021,069 out=107,564,401 elapsed=485.5s

  [10392/13157] intraday_7236.csv.gz  in=360,034,761 out=107,578,093 elapsed=485.5s

  [10393/13157] intraday_7234.csv.gz  in=360,046,529 out=107,589,861 elapsed=485.5s

  [10394/13157] intraday_7233.csv.gz  in=360,063,442 out=107,606,774 elapsed=485.6s

  [10395/13157] intraday_7239.csv.gz  in=360,075,832 out=107,619,164 elapsed=485.7s

  [10396/13157] intraday_7237.csv.gz  in=360,089,199 out=107,632,531 elapsed=485.7s

  [10397/13157] intraday_7238.csv.gz  in=360,102,589 out=107,645,921 elapsed=485.7s

  [10398/13157] intraday_7240.csv.gz  in=360,115,150 out=107,658,482 elapsed=485.7s

  [10399/13157] intraday_7244.csv.gz  in=360,125,348 out=107,668,680 elapsed=486.1s

  [10400/13157] intraday_7241.csv.gz  in=360,136,708 out=107,680,040 elapsed=486.1s

  [10401/13157] intraday_7242.csv.gz  in=360,151,106 out=107,694,438 elapsed=486.2s

  [10402/13157] intraday_7245.csv.gz  in=360,163,685 out=107,707,017 elapsed=486.2s

  [10403/13157] intraday_7243.csv.gz  in=360,199,586 out=107,726,833 elapsed=486.2s

  [10404/13157] intraday_7246.csv.gz  in=360,214,021 out=107,741,268 elapsed=486.3s

  [10405/13157] intraday_7249.csv.gz  in=360,226,497 out=107,753,744 elapsed=486.4s

  [10406/13157] intraday_7247.csv.gz  in=360,239,369 out=107,766,616 elapsed=486.4s

  [10407/13157] intraday_7248.csv.gz  in=360,254,540 out=107,781,787 elapsed=486.4s

  [10408/13157] intraday_7251.csv.gz  in=360,267,664 out=107,794,911 elapsed=486.5s

  [10409/13157] intraday_7250.csv.gz  in=360,283,655 out=107,810,902 elapsed=486.5s

  [10410/13157] intraday_7252.csv.gz  in=360,296,683 out=107,823,930 elapsed=486.5s

  [10411/13157] intraday_7253.csv.gz  in=360,312,257 out=107,839,504 elapsed=486.5s

  [10412/13157] intraday_7256.csv.gz  in=360,327,344 out=107,854,591 elapsed=486.7s

  [10413/13157] intraday_7257.csv.gz  in=360,337,760 out=107,865,007 elapsed=486.7s

  [10414/13157] intraday_7254.csv.gz  in=360,352,269 out=107,879,516 elapsed=486.7s

  [10415/13157] intraday_7255.csv.gz  in=360,362,595 out=107,889,842 elapsed=486.7s

  [10416/13157] intraday_7258.csv.gz  in=360,377,259 out=107,904,506 elapsed=486.8s

  [10417/13157] intraday_7261.csv.gz  in=360,391,798 out=107,919,045 elapsed=486.8s

  [10418/13157] intraday_7259.csv.gz  in=360,407,907 out=107,935,154 elapsed=486.8s

  [10419/13157] intraday_7260.csv.gz  in=360,424,342 out=107,951,589 elapsed=486.8s

  [10420/13157] intraday_7262.csv.gz  in=360,439,385 out=107,966,632 elapsed=486.8s

  [10421/13157] intraday_7263.csv.gz  in=360,452,927 out=107,980,174 elapsed=486.9s

  [10422/13157] intraday_7264.csv.gz  in=360,464,077 out=107,991,324 elapsed=486.9s

  [10423/13157] intraday_7265.csv.gz  in=360,474,714 out=108,001,961 elapsed=486.9s

  [10424/13157] intraday_7266.csv.gz  in=360,489,001 out=108,016,248 elapsed=486.9s

  [10425/13157] intraday_7267.csv.gz  in=360,500,100 out=108,027,347 elapsed=486.9s

  [10426/13157] intraday_7268.csv.gz  in=360,513,324 out=108,040,571 elapsed=486.9s

  [10427/13157] intraday_7269.csv.gz  in=360,525,796 out=108,053,043 elapsed=486.9s

  [10428/13157] intraday_7272.csv.gz  in=360,538,294 out=108,065,541 elapsed=487.0s

  [10429/13157] intraday_7273.csv.gz  in=360,550,101 out=108,077,348 elapsed=487.0s

  [10430/13157] intraday_7270.csv.gz  in=360,565,355 out=108,092,602 elapsed=487.0s

  [10431/13157] intraday_7271.csv.gz  in=360,578,161 out=108,105,408 elapsed=487.0s

  [10432/13157] intraday_7275.csv.gz  in=360,590,018 out=108,117,265 elapsed=487.2s

  [10433/13157] intraday_7274.csv.gz  in=360,602,580 out=108,129,827 elapsed=487.2s

  [10434/13157] intraday_7277.csv.gz  in=360,616,642 out=108,143,889 elapsed=487.2s

  [10435/13157] intraday_7276.csv.gz  in=360,633,148 out=108,159,016 elapsed=487.2s

  [10436/13157] intraday_7281.csv.gz  in=360,644,513 out=108,170,381 elapsed=487.3s

  [10437/13157] intraday_7280.csv.gz  in=360,656,182 out=108,182,050 elapsed=487.3s

  [10438/13157] intraday_7278.csv.gz  in=360,670,012 out=108,195,880 elapsed=487.3s

  [10439/13157] intraday_7279.csv.gz  in=360,684,585 out=108,210,453 elapsed=487.3s

  [10440/13157] intraday_7285.csv.gz  in=360,692,481 out=108,218,349 elapsed=487.4s

  [10441/13157] intraday_7283.csv.gz  in=360,704,394 out=108,230,262 elapsed=487.4s

  [10442/13157] intraday_7284.csv.gz  in=360,717,054 out=108,242,922 elapsed=487.4s

  [10443/13157] intraday_7282.csv.gz  in=360,730,720 out=108,256,588 elapsed=487.4s

  [10444/13157] intraday_7287.csv.gz  in=360,737,471 out=108,263,339 elapsed=487.4s

  [10445/13157] intraday_7286.csv.gz  in=360,750,029 out=108,275,897 elapsed=487.4s

  [10446/13157] intraday_7288.csv.gz  in=360,766,425 out=108,292,293 elapsed=487.5s

  [10447/13157] intraday_7289.csv.gz  in=360,781,767 out=108,306,186 elapsed=487.5s

  [10448/13157] intraday_7291.csv.gz  in=360,793,490 out=108,317,909 elapsed=487.5s

  [10449/13157] intraday_7290.csv.gz  in=360,806,360 out=108,330,779 elapsed=487.5s

  [10450/13157] intraday_7293.csv.gz  in=360,820,554 out=108,344,960 elapsed=487.5s

  [10451/13157] intraday_7294.csv.gz  in=360,836,949 out=108,361,355 elapsed=487.6s

  [10452/13157] intraday_7292.csv.gz  in=360,849,273 out=108,373,679 elapsed=487.6s

  [10453/13157] intraday_7295.csv.gz  in=360,860,804 out=108,385,210 elapsed=487.6s

  [10454/13157] intraday_7296.csv.gz  in=360,874,792 out=108,399,198 elapsed=487.6s

  [10455/13157] intraday_7297.csv.gz  in=360,889,395 out=108,413,801 elapsed=487.6s

  [10456/13157] intraday_7298.csv.gz  in=360,905,942 out=108,428,949 elapsed=487.6s

  [10457/13157] intraday_7299.csv.gz  in=360,921,044 out=108,444,051 elapsed=487.6s

  [10458/13157] intraday_7300.csv.gz  in=360,933,900 out=108,456,907 elapsed=487.6s

  [10459/13157] intraday_7301.csv.gz  in=360,950,873 out=108,470,858 elapsed=487.6s

  [10460/13157] intraday_7302.csv.gz  in=360,961,364 out=108,481,349 elapsed=487.7s

  [10461/13157] intraday_7304.csv.gz  in=360,976,467 out=108,496,452 elapsed=487.7s

  [10462/13157] intraday_7305.csv.gz  in=360,989,695 out=108,509,680 elapsed=487.7s

  [10463/13157] intraday_7303.csv.gz  in=361,001,339 out=108,521,324 elapsed=487.7s

  [10464/13157] intraday_7306.csv.gz  in=361,013,997 out=108,533,982 elapsed=487.8s

  [10465/13157] intraday_7308.csv.gz  in=361,026,954 out=108,546,939 elapsed=487.8s

  [10466/13157] intraday_7309.csv.gz  in=361,039,965 out=108,559,950 elapsed=487.8s

  [10467/13157] intraday_7307.csv.gz  in=361,052,505 out=108,572,490 elapsed=487.8s

  [10468/13157] intraday_7310.csv.gz  in=361,065,234 out=108,585,219 elapsed=487.8s

  [10469/13157] intraday_7312.csv.gz  in=361,078,938 out=108,598,923 elapsed=487.8s

  [10470/13157] intraday_7313.csv.gz  in=361,092,465 out=108,612,450 elapsed=487.9s

  [10471/13157] intraday_7311.csv.gz  in=361,105,060 out=108,625,045 elapsed=487.9s

  [10472/13157] intraday_7314.csv.gz  in=361,115,898 out=108,635,883 elapsed=487.9s

  [10473/13157] intraday_7315.csv.gz  in=361,128,422 out=108,648,407 elapsed=487.9s

  [10474/13157] intraday_7316.csv.gz  in=361,140,433 out=108,660,418 elapsed=488.0s

  [10475/13157] intraday_7317.csv.gz  in=361,154,628 out=108,674,613 elapsed=488.0s

  [10476/13157] intraday_7318.csv.gz  in=361,170,992 out=108,690,977 elapsed=488.0s

  [10477/13157] intraday_7319.csv.gz  in=361,185,033 out=108,705,018 elapsed=488.0s

  [10478/13157] intraday_7320.csv.gz  in=361,195,026 out=108,715,011 elapsed=488.0s

  [10479/13157] intraday_7321.csv.gz  in=361,209,580 out=108,729,565 elapsed=488.1s

  [10480/13157] intraday_7323.csv.gz  in=361,222,419 out=108,742,404 elapsed=488.1s

  [10481/13157] intraday_7322.csv.gz  in=361,236,416 out=108,756,401 elapsed=488.1s

  [10482/13157] intraday_7324.csv.gz  in=361,248,944 out=108,768,929 elapsed=488.1s

  [10483/13157] intraday_7327.csv.gz  in=361,261,425 out=108,781,410 elapsed=488.2s

  [10484/13157] intraday_7328.csv.gz  in=361,272,996 out=108,792,981 elapsed=488.2s

  [10485/13157] intraday_7325.csv.gz  in=361,284,605 out=108,804,590 elapsed=488.2s

  [10486/13157] intraday_7326.csv.gz  in=361,298,253 out=108,818,238 elapsed=488.2s

  [10487/13157] intraday_7329.csv.gz  in=361,310,832 out=108,830,817 elapsed=488.2s

  [10488/13157] intraday_7330.csv.gz  in=361,323,781 out=108,843,766 elapsed=488.2s

  [10489/13157] intraday_7331.csv.gz  in=361,338,241 out=108,858,226 elapsed=488.2s

  [10490/13157] intraday_7332.csv.gz  in=361,353,196 out=108,873,181 elapsed=488.3s

  [10491/13157] intraday_7333.csv.gz  in=361,365,315 out=108,885,300 elapsed=488.3s

  [10492/13157] intraday_7335.csv.gz  in=361,378,918 out=108,898,903 elapsed=488.3s

  [10493/13157] intraday_7336.csv.gz  in=361,391,345 out=108,911,330 elapsed=488.3s

  [10494/13157] intraday_7334.csv.gz  in=361,403,616 out=108,923,601 elapsed=488.3s

  [10495/13157] intraday_7337.csv.gz  in=361,416,345 out=108,936,330 elapsed=488.4s

  [10496/13157] intraday_7338.csv.gz  in=361,427,288 out=108,947,273 elapsed=488.4s

  [10497/13157] intraday_7339.csv.gz  in=361,439,092 out=108,959,077 elapsed=488.4s

  [10498/13157] intraday_7340.csv.gz  in=361,453,933 out=108,973,918 elapsed=488.4s

  [10499/13157] intraday_7341.csv.gz  in=361,464,143 out=108,984,128 elapsed=488.8s

  [10500/13157] intraday_7343.csv.gz  in=361,477,206 out=108,997,191 elapsed=488.8s

  [10501/13157] intraday_7342.csv.gz  in=361,492,781 out=109,012,766 elapsed=488.8s

  [10502/13157] intraday_7344.csv.gz  in=361,508,129 out=109,027,115 elapsed=488.8s

  [10503/13157] intraday_7346.csv.gz  in=361,521,133 out=109,040,119 elapsed=488.8s

  [10504/13157] intraday_7348.csv.gz  in=361,534,145 out=109,053,131 elapsed=488.8s

  [10505/13157] intraday_7345.csv.gz  in=361,546,195 out=109,065,181 elapsed=488.8s

  [10506/13157] intraday_7347.csv.gz  in=361,559,486 out=109,078,472 elapsed=488.8s

  [10507/13157] intraday_7349.csv.gz  in=361,573,468 out=109,092,454 elapsed=488.9s

  [10508/13157] intraday_7350.csv.gz  in=361,585,351 out=109,104,337 elapsed=488.9s

  [10509/13157] intraday_7351.csv.gz  in=361,596,518 out=109,115,504 elapsed=488.9s

  [10510/13157] intraday_7353.csv.gz  in=361,611,738 out=109,130,724 elapsed=488.9s

  [10511/13157] intraday_7352.csv.gz  in=361,623,155 out=109,142,141 elapsed=488.9s

  [10512/13157] intraday_7354.csv.gz  in=361,636,559 out=109,155,545 elapsed=489.0s

  [10513/13157] intraday_7355.csv.gz  in=361,651,526 out=109,170,512 elapsed=489.0s

  [10514/13157] intraday_7357.csv.gz  in=361,664,196 out=109,183,182 elapsed=489.0s

  [10515/13157] intraday_7356.csv.gz  in=361,676,672 out=109,195,658 elapsed=489.0s

  [10516/13157] intraday_7358.csv.gz  in=361,687,867 out=109,206,853 elapsed=489.0s

  [10517/13157] intraday_7361.csv.gz  in=361,701,814 out=109,220,800 elapsed=489.1s

  [10518/13157] intraday_7359.csv.gz  in=361,713,837 out=109,232,823 elapsed=489.1s

  [10519/13157] intraday_7360.csv.gz  in=361,726,575 out=109,245,561 elapsed=489.1s

  [10520/13157] intraday_7362.csv.gz  in=361,738,515 out=109,257,501 elapsed=489.1s

  [10521/13157] intraday_7364.csv.gz  in=361,748,510 out=109,267,496 elapsed=489.2s

  [10522/13157] intraday_7363.csv.gz  in=361,760,445 out=109,279,431 elapsed=489.2s

  [10523/13157] intraday_7365.csv.gz  in=361,775,409 out=109,294,395 elapsed=489.2s

  [10524/13157] intraday_7366.csv.gz  in=361,787,178 out=109,306,164 elapsed=489.2s

  [10525/13157] intraday_7369.csv.gz  in=361,796,746 out=109,315,732 elapsed=489.2s

  [10526/13157] intraday_7368.csv.gz  in=361,807,645 out=109,326,631 elapsed=489.3s

  [10527/13157] intraday_7370.csv.gz  in=361,819,778 out=109,338,764 elapsed=489.3s

  [10528/13157] intraday_7367.csv.gz  in=361,831,856 out=109,350,842 elapsed=489.3s

  [10529/13157] intraday_7373.csv.gz  in=361,845,669 out=109,364,655 elapsed=489.3s

  [10530/13157] intraday_7374.csv.gz  in=361,856,216 out=109,375,202 elapsed=489.3s

  [10531/13157] intraday_7372.csv.gz  in=361,873,995 out=109,392,981 elapsed=489.3s

  [10532/13157] intraday_7371.csv.gz  in=361,891,931 out=109,410,917 elapsed=489.3s

  [10533/13157] intraday_7375.csv.gz  in=361,904,748 out=109,423,734 elapsed=489.4s

  [10534/13157] intraday_7376.csv.gz  in=361,920,054 out=109,439,040 elapsed=489.4s

  [10535/13157] intraday_7378.csv.gz  in=361,934,993 out=109,453,979 elapsed=489.4s

  [10536/13157] intraday_7379.csv.gz  in=361,949,635 out=109,466,371 elapsed=489.4s

  [10537/13157] intraday_7377.csv.gz  in=361,963,721 out=109,480,457 elapsed=489.4s

  [10538/13157] intraday_7380.csv.gz  in=361,977,222 out=109,493,958 elapsed=489.4s

  [10539/13157] intraday_7381.csv.gz  in=361,990,950 out=109,507,686 elapsed=489.4s

  [10540/13157] intraday_7383.csv.gz  in=362,004,692 out=109,521,428 elapsed=489.5s

  [10541/13157] intraday_7382.csv.gz  in=362,018,323 out=109,535,059 elapsed=489.5s

  [10542/13157] intraday_7385.csv.gz  in=362,032,086 out=109,548,822 elapsed=489.5s

  [10543/13157] intraday_7384.csv.gz  in=362,043,393 out=109,560,129 elapsed=489.5s

  [10544/13157] intraday_7386.csv.gz  in=362,056,954 out=109,573,690 elapsed=489.5s

  [10545/13157] intraday_7388.csv.gz  in=362,068,865 out=109,585,601 elapsed=489.6s

  [10546/13157] intraday_7390.csv.gz  in=362,081,605 out=109,598,341 elapsed=489.6s

  [10547/13157] intraday_7389.csv.gz  in=362,096,025 out=109,612,761 elapsed=489.6s

  [10548/13157] intraday_7387.csv.gz  in=362,109,491 out=109,626,227 elapsed=489.6s

  [10549/13157] intraday_7391.csv.gz  in=362,125,847 out=109,642,583 elapsed=489.6s

  [10550/13157] intraday_7392.csv.gz  in=362,137,913 out=109,654,649 elapsed=489.6s

  [10551/13157] intraday_7393.csv.gz  in=362,150,558 out=109,667,294 elapsed=489.7s

  [10552/13157] intraday_7394.csv.gz  in=362,167,812 out=109,684,548 elapsed=489.7s

  [10553/13157] intraday_7396.csv.gz  in=362,179,784 out=109,696,520 elapsed=489.7s

  [10554/13157] intraday_7395.csv.gz  in=362,192,924 out=109,709,660 elapsed=489.7s

  [10555/13157] intraday_7397.csv.gz  in=362,208,973 out=109,725,709 elapsed=490.2s

  [10556/13157] intraday_7398.csv.gz  in=362,224,881 out=109,741,617 elapsed=490.2s

  [10557/13157] intraday_7399.csv.gz  in=362,237,448 out=109,754,184 elapsed=490.2s

  [10558/13157] intraday_7400.csv.gz  in=362,250,791 out=109,767,527 elapsed=490.2s

  [10559/13157] intraday_7401.csv.gz  in=362,264,476 out=109,781,212 elapsed=490.4s

  [10560/13157] intraday_7404.csv.gz  in=362,279,050 out=109,795,786 elapsed=490.4s

  [10561/13157] intraday_7402.csv.gz  in=362,291,585 out=109,808,321 elapsed=490.4s

  [10562/13157] intraday_7403.csv.gz  in=362,310,623 out=109,827,359 elapsed=490.4s

  [10563/13157] intraday_7407.csv.gz  in=362,325,562 out=109,842,298 elapsed=490.5s

  [10564/13157] intraday_7408.csv.gz  in=362,338,570 out=109,855,306 elapsed=490.5s

  [10565/13157] intraday_7406.csv.gz  in=362,355,980 out=109,872,716 elapsed=490.5s

  [10566/13157] intraday_7405.csv.gz  in=362,371,216 out=109,887,952 elapsed=490.5s

  [10567/13157] intraday_7410.csv.gz  in=362,384,538 out=109,901,274 elapsed=490.5s

  [10568/13157] intraday_7409.csv.gz  in=362,396,686 out=109,913,422 elapsed=490.5s

  [10569/13157] intraday_7411.csv.gz  in=362,408,180 out=109,924,916 elapsed=490.5s

  [10570/13157] intraday_7412.csv.gz  in=362,422,291 out=109,938,580 elapsed=490.6s

  [10571/13157] intraday_7415.csv.gz  in=362,436,460 out=109,952,749 elapsed=490.6s

  [10572/13157] intraday_7413.csv.gz  in=362,449,151 out=109,965,440 elapsed=490.6s

  [10573/13157] intraday_7414.csv.gz  in=362,465,147 out=109,981,436 elapsed=490.6s

  [10574/13157] intraday_7416.csv.gz  in=362,478,736 out=109,995,025 elapsed=490.6s

  [10575/13157] intraday_7417.csv.gz  in=362,490,542 out=110,006,831 elapsed=490.7s

  [10576/13157] intraday_7419.csv.gz  in=362,502,640 out=110,018,929 elapsed=490.7s

  [10577/13157] intraday_7418.csv.gz  in=362,517,113 out=110,033,193 elapsed=490.7s

  [10578/13157] intraday_7420.csv.gz  in=362,529,978 out=110,046,058 elapsed=490.7s

  [10579/13157] intraday_7421.csv.gz  in=362,545,789 out=110,061,869 elapsed=490.7s

  [10580/13157] intraday_7422.csv.gz  in=362,560,770 out=110,076,850 elapsed=490.7s

  [10581/13157] intraday_7424.csv.gz  in=362,575,389 out=110,091,469 elapsed=490.7s

  [10582/13157] intraday_7423.csv.gz  in=362,595,500 out=110,107,776 elapsed=490.7s

  [10583/13157] intraday_7425.csv.gz  in=362,608,481 out=110,120,757 elapsed=490.8s

  [10584/13157] intraday_7427.csv.gz  in=362,619,182 out=110,131,458 elapsed=490.8s

  [10585/13157] intraday_7428.csv.gz  in=362,633,794 out=110,146,070 elapsed=490.8s

  [10586/13157] intraday_7426.csv.gz  in=362,647,402 out=110,159,678 elapsed=490.8s

  [10587/13157] intraday_7432.csv.gz  in=362,649,495 out=110,161,771 elapsed=490.9s

  [10588/13157] intraday_7430.csv.gz  in=362,658,757 out=110,171,033 elapsed=490.9s

  [10589/13157] intraday_7429.csv.gz  in=362,669,669 out=110,181,945 elapsed=490.9s

  [10590/13157] intraday_7431.csv.gz  in=362,683,188 out=110,195,464 elapsed=490.9s

  [10591/13157] intraday_7434.csv.gz  in=362,683,223 out=110,195,499 elapsed=490.9s

  [10592/13157] intraday_7435.csv.gz  in=362,683,245 out=110,195,521 elapsed=490.9s

  [10593/13157] intraday_7433.csv.gz  in=362,683,353 out=110,195,629 elapsed=490.9s

  [10594/13157] intraday_7438.csv.gz  in=362,683,396 out=110,195,672 elapsed=490.9s

  [10595/13157] intraday_7439.csv.gz  in=362,685,215 out=110,197,491 elapsed=490.9s

  [10596/13157] intraday_7436.csv.gz  in=362,693,098 out=110,199,918 elapsed=491.0s

  [10597/13157] intraday_7440.csv.gz  in=362,693,274 out=110,200,065 elapsed=491.0s

  [10598/13157] intraday_7437.csv.gz  in=362,695,786 out=110,200,961 elapsed=491.0s

  [10599/13157] intraday_7442.csv.gz  in=362,695,920 out=110,201,095 elapsed=491.0s

  [10600/13157] intraday_7441.csv.gz  in=362,700,777 out=110,202,786 elapsed=491.0s

  [10601/13157] intraday_7444.csv.gz  in=362,700,790 out=110,202,786 elapsed=491.0s

  [10602/13157] intraday_7445.csv.gz  in=362,700,813 out=110,202,809 elapsed=491.0s

  [10603/13157] intraday_7446.csv.gz  in=362,700,915 out=110,202,911 elapsed=491.0s

  [10604/13157] intraday_7447.csv.gz  in=362,701,833 out=110,203,829 elapsed=491.0s

  [10605/13157] intraday_7443.csv.gz  in=362,702,989 out=110,204,757 elapsed=491.0s

  [10606/13157] intraday_7449.csv.gz  in=362,703,152 out=110,204,920 elapsed=491.0s

  [10607/13157] intraday_7448.csv.gz  in=362,704,051 out=110,205,819 elapsed=491.0s

  [10608/13157] intraday_7451.csv.gz  in=362,704,096 out=110,205,864 elapsed=491.0s

  [10609/13157] intraday_7450.csv.gz  in=362,704,104 out=110,205,872 elapsed=491.0s

  [10610/13157] intraday_7452.csv.gz  in=362,705,440 out=110,206,759 elapsed=491.1s

  [10611/13157] intraday_7455.csv.gz  in=362,706,160 out=110,207,479 elapsed=491.1s

  [10612/13157] intraday_7454.csv.gz  in=362,710,445 out=110,209,842 elapsed=491.1s

  [10613/13157] intraday_7453.csv.gz  in=362,714,901 out=110,211,458 elapsed=491.1s

  [10614/13157] intraday_7456.csv.gz  in=362,715,218 out=110,211,775 elapsed=491.1s

  [10615/13157] intraday_7457.csv.gz  in=362,719,441 out=110,212,724 elapsed=491.1s

  [10616/13157] intraday_7458.csv.gz  in=362,719,464 out=110,212,747 elapsed=491.1s

  [10617/13157] intraday_7459.csv.gz  in=362,719,595 out=110,212,878 elapsed=491.2s

  [10618/13157] intraday_7460.csv.gz  in=362,719,806 out=110,213,089 elapsed=491.2s

  [10619/13157] intraday_7461.csv.gz  in=362,720,112 out=110,213,395 elapsed=491.2s

  [10620/13157] intraday_7463.csv.gz  in=362,723,594 out=110,216,877 elapsed=491.4s

  [10621/13157] intraday_7464.csv.gz  in=362,726,415 out=110,219,698 elapsed=491.5s

  [10622/13157] intraday_7465.csv.gz  in=362,728,828 out=110,222,111 elapsed=491.6s

  [10623/13157] intraday_7467.csv.gz  in=362,731,269 out=110,224,552 elapsed=491.7s

  [10624/13157] intraday_7466.csv.gz  in=362,733,762 out=110,227,045 elapsed=491.7s

  [10625/13157] intraday_7468.csv.gz  in=362,736,801 out=110,230,084 elapsed=491.7s

  [10626/13157] intraday_7470.csv.gz  in=362,739,040 out=110,232,323 elapsed=491.7s

  [10627/13157] intraday_7469.csv.gz  in=362,743,070 out=110,236,353 elapsed=491.7s

  [10628/13157] intraday_7471.csv.gz  in=362,745,764 out=110,239,047 elapsed=491.7s

  [10629/13157] intraday_7472.csv.gz  in=362,748,797 out=110,242,080 elapsed=491.7s

  [10630/13157] intraday_7473.csv.gz  in=362,753,065 out=110,246,203 elapsed=491.7s

  [10631/13157] intraday_7474.csv.gz  in=362,756,760 out=110,249,898 elapsed=491.7s

  [10632/13157] intraday_7462.csv.gz  in=362,788,503 out=110,262,759 elapsed=491.7s

  [10633/13157] intraday_7475.csv.gz  in=362,791,514 out=110,265,770 elapsed=491.8s

  [10634/13157] intraday_7478.csv.gz  in=362,793,602 out=110,267,858 elapsed=491.8s

  [10635/13157] intraday_7476.csv.gz  in=362,796,641 out=110,270,897 elapsed=491.8s

  [10636/13157] intraday_7477.csv.gz  in=362,799,094 out=110,273,350 elapsed=491.8s

  [10637/13157] intraday_7480.csv.gz  in=362,801,770 out=110,276,026 elapsed=491.8s

  [10638/13157] intraday_7479.csv.gz  in=362,805,046 out=110,279,302 elapsed=491.8s

  [10639/13157] intraday_7482.csv.gz  in=362,807,161 out=110,281,417 elapsed=491.8s

  [10640/13157] intraday_7481.csv.gz  in=362,809,212 out=110,283,468 elapsed=491.8s

  [10641/13157] intraday_7483.csv.gz  in=362,811,985 out=110,286,241 elapsed=491.8s

  [10642/13157] intraday_7485.csv.gz  in=362,813,677 out=110,287,933 elapsed=491.8s

  [10643/13157] intraday_7487.csv.gz  in=362,815,970 out=110,290,226 elapsed=491.8s

  [10644/13157] intraday_7484.csv.gz  in=362,819,196 out=110,293,063 elapsed=491.8s

  [10645/13157] intraday_7486.csv.gz  in=362,821,847 out=110,295,714 elapsed=491.8s

  [10646/13157] intraday_7488.csv.gz  in=362,825,056 out=110,298,468 elapsed=491.9s

  [10647/13157] intraday_7490.csv.gz  in=362,827,638 out=110,301,050 elapsed=491.9s

  [10648/13157] intraday_7489.csv.gz  in=362,830,073 out=110,303,485 elapsed=491.9s

  [10649/13157] intraday_7492.csv.gz  in=362,833,313 out=110,306,725 elapsed=491.9s

  [10650/13157] intraday_7491.csv.gz  in=362,835,884 out=110,309,296 elapsed=491.9s

  [10651/13157] intraday_7495.csv.gz  in=362,837,307 out=110,310,719 elapsed=492.0s

  [10652/13157] intraday_7496.csv.gz  in=362,840,353 out=110,313,765 elapsed=492.0s

  [10653/13157] intraday_7493.csv.gz  in=362,844,311 out=110,317,723 elapsed=492.0s

  [10654/13157] intraday_7494.csv.gz  in=362,846,762 out=110,320,174 elapsed=492.0s

  [10655/13157] intraday_7497.csv.gz  in=362,849,223 out=110,322,635 elapsed=492.0s

  [10656/13157] intraday_7498.csv.gz  in=362,851,432 out=110,324,844 elapsed=492.1s

  [10657/13157] intraday_7500.csv.gz  in=362,853,618 out=110,327,030 elapsed=492.1s

  [10658/13157] intraday_7499.csv.gz  in=362,855,908 out=110,329,320 elapsed=492.1s

  [10659/13157] intraday_7501.csv.gz  in=362,858,344 out=110,331,756 elapsed=492.1s

  [10660/13157] intraday_7503.csv.gz  in=362,860,994 out=110,334,406 elapsed=492.1s

  [10661/13157] intraday_7504.csv.gz  in=362,863,368 out=110,336,780 elapsed=492.1s

  [10662/13157] intraday_7502.csv.gz  in=362,865,353 out=110,338,765 elapsed=492.1s

  [10663/13157] intraday_7506.csv.gz  in=362,868,048 out=110,341,460 elapsed=492.2s

  [10664/13157] intraday_7505.csv.gz  in=362,870,928 out=110,344,340 elapsed=492.2s

  [10665/13157] intraday_7507.csv.gz  in=362,873,179 out=110,346,591 elapsed=492.2s

  [10666/13157] intraday_7509.csv.gz  in=362,874,580 out=110,347,992 elapsed=492.2s

  [10667/13157] intraday_7510.csv.gz  in=362,876,777 out=110,350,189 elapsed=492.2s

  [10668/13157] intraday_7508.csv.gz  in=362,878,923 out=110,352,335 elapsed=492.2s

  [10669/13157] intraday_7511.csv.gz  in=362,880,944 out=110,354,356 elapsed=492.2s

  [10670/13157] intraday_7512.csv.gz  in=362,884,480 out=110,357,095 elapsed=492.2s

  [10671/13157] intraday_7513.csv.gz  in=362,886,479 out=110,359,094 elapsed=492.2s

  [10672/13157] intraday_7514.csv.gz  in=362,888,387 out=110,361,002 elapsed=492.2s

  [10673/13157] intraday_7515.csv.gz  in=362,892,607 out=110,365,222 elapsed=492.3s

  [10674/13157] intraday_7516.csv.gz  in=362,894,981 out=110,367,596 elapsed=492.3s

  [10675/13157] intraday_7518.csv.gz  in=362,898,866 out=110,371,481 elapsed=492.3s

  [10676/13157] intraday_7517.csv.gz  in=362,905,767 out=110,377,989 elapsed=492.3s

  [10677/13157] intraday_7520.csv.gz  in=362,907,411 out=110,379,633 elapsed=492.3s

  [10678/13157] intraday_7522.csv.gz  in=362,910,065 out=110,382,287 elapsed=492.3s

  [10679/13157] intraday_7519.csv.gz  in=362,912,506 out=110,384,728 elapsed=492.3s

  [10680/13157] intraday_7521.csv.gz  in=362,915,095 out=110,387,317 elapsed=492.3s

  [10681/13157] intraday_7523.csv.gz  in=362,916,796 out=110,389,018 elapsed=492.4s

  [10682/13157] intraday_7526.csv.gz  in=362,918,453 out=110,390,675 elapsed=492.5s

  [10683/13157] intraday_7524.csv.gz  in=362,921,579 out=110,393,549 elapsed=492.5s

  [10684/13157] intraday_7525.csv.gz  in=362,923,365 out=110,395,335 elapsed=492.5s

  [10685/13157] intraday_7527.csv.gz  in=362,925,608 out=110,397,578 elapsed=492.5s

  [10686/13157] intraday_7531.csv.gz  in=362,928,246 out=110,400,216 elapsed=492.5s

  [10687/13157] intraday_7528.csv.gz  in=362,932,007 out=110,403,977 elapsed=492.5s

  [10688/13157] intraday_7529.csv.gz  in=362,935,620 out=110,407,590 elapsed=492.5s

  [10689/13157] intraday_7530.csv.gz  in=362,938,105 out=110,410,075 elapsed=492.5s

  [10690/13157] intraday_7532.csv.gz  in=362,940,570 out=110,412,540 elapsed=492.8s

  [10691/13157] intraday_7533.csv.gz  in=362,943,004 out=110,414,974 elapsed=492.8s

  [10692/13157] intraday_7535.csv.gz  in=362,945,458 out=110,417,428 elapsed=492.9s

  [10693/13157] intraday_7534.csv.gz  in=362,947,921 out=110,419,625 elapsed=492.9s

  [10694/13157] intraday_7537.csv.gz  in=362,949,870 out=110,421,574 elapsed=492.9s

  [10695/13157] intraday_7536.csv.gz  in=362,953,031 out=110,424,441 elapsed=492.9s

  [10696/13157] intraday_7538.csv.gz  in=362,956,131 out=110,427,541 elapsed=493.0s

  [10697/13157] intraday_7540.csv.gz  in=362,958,885 out=110,430,295 elapsed=493.0s

  [10698/13157] intraday_7541.csv.gz  in=362,960,989 out=110,432,399 elapsed=493.0s

  [10699/13157] intraday_7539.csv.gz  in=362,962,905 out=110,434,315 elapsed=493.0s

  [10700/13157] intraday_7543.csv.gz  in=362,965,060 out=110,436,470 elapsed=493.1s

  [10701/13157] intraday_7542.csv.gz  in=362,967,227 out=110,438,637 elapsed=493.1s

  [10702/13157] intraday_7545.csv.gz  in=362,970,002 out=110,441,412 elapsed=493.1s

  [10703/13157] intraday_7544.csv.gz  in=362,971,373 out=110,442,783 elapsed=493.1s

  [10704/13157] intraday_7547.csv.gz  in=362,977,006 out=110,448,416 elapsed=493.3s

  [10705/13157] intraday_7549.csv.gz  in=362,979,614 out=110,451,024 elapsed=493.3s

  [10706/13157] intraday_7546.csv.gz  in=362,984,868 out=110,456,278 elapsed=493.3s

  [10707/13157] intraday_7548.csv.gz  in=362,988,388 out=110,459,798 elapsed=493.3s

  [10708/13157] intraday_7552.csv.gz  in=362,991,429 out=110,462,839 elapsed=493.5s

  [10709/13157] intraday_7551.csv.gz  in=362,995,560 out=110,466,970 elapsed=493.5s

  [10710/13157] intraday_7550.csv.gz  in=362,998,227 out=110,469,637 elapsed=493.5s

  [10711/13157] intraday_7553.csv.gz  in=363,003,045 out=110,474,455 elapsed=493.5s

  [10712/13157] intraday_7554.csv.gz  in=363,005,253 out=110,476,663 elapsed=493.5s

  [10713/13157] intraday_7555.csv.gz  in=363,007,748 out=110,479,158 elapsed=493.5s

  [10714/13157] intraday_7556.csv.gz  in=363,010,862 out=110,482,272 elapsed=493.5s

  [10715/13157] intraday_7557.csv.gz  in=363,013,858 out=110,485,268 elapsed=493.5s

  [10716/13157] intraday_7558.csv.gz  in=363,016,294 out=110,487,704 elapsed=493.6s

  [10717/13157] intraday_7561.csv.gz  in=363,019,182 out=110,490,592 elapsed=493.6s

  [10718/13157] intraday_7560.csv.gz  in=363,021,713 out=110,493,123 elapsed=493.6s

  [10719/13157] intraday_7559.csv.gz  in=363,023,906 out=110,495,316 elapsed=493.6s

  [10720/13157] intraday_7562.csv.gz  in=363,028,135 out=110,499,545 elapsed=493.6s

  [10721/13157] intraday_7563.csv.gz  in=363,029,521 out=110,500,931 elapsed=493.6s

  [10722/13157] intraday_7564.csv.gz  in=363,031,705 out=110,503,115 elapsed=493.6s

  [10723/13157] intraday_7565.csv.gz  in=363,035,483 out=110,506,893 elapsed=493.6s

  [10724/13157] intraday_7566.csv.gz  in=363,040,196 out=110,511,606 elapsed=493.6s

  [10725/13157] intraday_7568.csv.gz  in=363,042,968 out=110,514,378 elapsed=493.6s

  [10726/13157] intraday_7567.csv.gz  in=363,045,084 out=110,516,494 elapsed=493.6s

  [10727/13157] intraday_7569.csv.gz  in=363,049,575 out=110,520,985 elapsed=493.6s

  [10728/13157] intraday_7571.csv.gz  in=363,051,713 out=110,523,123 elapsed=493.6s

  [10729/13157] intraday_7570.csv.gz  in=363,057,741 out=110,527,530 elapsed=493.7s

  [10730/13157] intraday_7572.csv.gz  in=363,061,262 out=110,531,051 elapsed=493.7s

  [10731/13157] intraday_7573.csv.gz  in=363,065,623 out=110,535,412 elapsed=493.7s

  [10732/13157] intraday_7575.csv.gz  in=363,068,118 out=110,537,907 elapsed=493.7s

  [10733/13157] intraday_7574.csv.gz  in=363,070,549 out=110,540,338 elapsed=493.8s

  [10734/13157] intraday_7576.csv.gz  in=363,078,067 out=110,546,035 elapsed=493.8s

  [10735/13157] intraday_7577.csv.gz  in=363,080,727 out=110,548,695 elapsed=493.8s

  [10736/13157] intraday_7579.csv.gz  in=363,083,973 out=110,551,941 elapsed=493.8s

  [10737/13157] intraday_7581.csv.gz  in=363,088,337 out=110,556,305 elapsed=493.8s

  [10738/13157] intraday_7578.csv.gz  in=363,094,835 out=110,562,803 elapsed=493.8s

  [10739/13157] intraday_7580.csv.gz  in=363,099,268 out=110,567,236 elapsed=493.8s

  [10740/13157] intraday_7582.csv.gz  in=363,102,118 out=110,570,086 elapsed=493.8s

  [10741/13157] intraday_7583.csv.gz  in=363,105,289 out=110,573,257 elapsed=493.9s

  [10742/13157] intraday_7584.csv.gz  in=363,107,411 out=110,575,379 elapsed=494.1s

  [10743/13157] intraday_7585.csv.gz  in=363,109,806 out=110,577,774 elapsed=494.1s

  [10744/13157] intraday_7587.csv.gz  in=363,111,896 out=110,579,864 elapsed=494.1s

  [10745/13157] intraday_7586.csv.gz  in=363,114,499 out=110,582,467 elapsed=494.1s

  [10746/13157] intraday_7589.csv.gz  in=363,118,454 out=110,586,422 elapsed=494.1s

  [10747/13157] intraday_7588.csv.gz  in=363,123,989 out=110,591,628 elapsed=494.1s

  [10748/13157] intraday_7590.csv.gz  in=363,128,335 out=110,595,974 elapsed=494.2s

  [10749/13157] intraday_7591.csv.gz  in=363,133,610 out=110,601,249 elapsed=494.2s

  [10750/13157] intraday_7592.csv.gz  in=363,135,552 out=110,603,191 elapsed=494.2s

  [10751/13157] intraday_7594.csv.gz  in=363,138,319 out=110,605,958 elapsed=494.2s

  [10752/13157] intraday_7593.csv.gz  in=363,141,458 out=110,609,097 elapsed=494.2s

  [10753/13157] intraday_7595.csv.gz  in=363,143,982 out=110,611,621 elapsed=494.2s

  [10754/13157] intraday_7596.csv.gz  in=363,146,901 out=110,614,540 elapsed=494.3s

  [10755/13157] intraday_7597.csv.gz  in=363,149,703 out=110,617,342 elapsed=494.3s

  [10756/13157] intraday_7598.csv.gz  in=363,152,332 out=110,619,971 elapsed=494.3s

  [10757/13157] intraday_7599.csv.gz  in=363,154,738 out=110,622,377 elapsed=494.3s

  [10758/13157] intraday_7600.csv.gz  in=363,156,589 out=110,624,228 elapsed=494.3s

  [10759/13157] intraday_7601.csv.gz  in=363,159,737 out=110,627,376 elapsed=494.3s

  [10760/13157] intraday_7602.csv.gz  in=363,161,788 out=110,629,427 elapsed=494.3s

  [10761/13157] intraday_7603.csv.gz  in=363,164,404 out=110,632,043 elapsed=494.3s

  [10762/13157] intraday_7604.csv.gz  in=363,167,341 out=110,634,980 elapsed=494.3s

  [10763/13157] intraday_7605.csv.gz  in=363,169,334 out=110,636,973 elapsed=494.3s

  [10764/13157] intraday_7608.csv.gz  in=363,169,339 out=110,636,978 elapsed=494.3s

  [10765/13157] intraday_7606.csv.gz  in=363,172,212 out=110,639,851 elapsed=494.3s

  [10766/13157] intraday_7607.csv.gz  in=363,173,344 out=110,640,983 elapsed=494.3s

  [10767/13157] intraday_7610.csv.gz  in=363,186,022 out=110,653,661 elapsed=494.4s

  [10768/13157] intraday_7611.csv.gz  in=363,199,399 out=110,667,038 elapsed=494.4s

  [10769/13157] intraday_7612.csv.gz  in=363,211,123 out=110,678,762 elapsed=494.4s

  [10770/13157] intraday_7609.csv.gz  in=363,228,991 out=110,696,630 elapsed=494.4s

  [10771/13157] intraday_7613.csv.gz  in=363,243,826 out=110,711,465 elapsed=494.5s

  [10772/13157] intraday_7615.csv.gz  in=363,257,483 out=110,725,122 elapsed=494.5s

  [10773/13157] intraday_7614.csv.gz  in=363,273,267 out=110,740,906 elapsed=494.5s

  [10774/13157] intraday_7616.csv.gz  in=363,286,947 out=110,754,586 elapsed=494.5s

  [10775/13157] intraday_7617.csv.gz  in=363,300,206 out=110,767,845 elapsed=494.6s

  [10776/13157] intraday_7618.csv.gz  in=363,314,335 out=110,781,974 elapsed=494.6s

  [10777/13157] intraday_7619.csv.gz  in=363,328,553 out=110,796,192 elapsed=494.6s

  [10778/13157] intraday_7621.csv.gz  in=363,341,834 out=110,809,473 elapsed=494.6s

  [10779/13157] intraday_7620.csv.gz  in=363,357,167 out=110,824,806 elapsed=494.6s

  [10780/13157] intraday_7623.csv.gz  in=363,368,320 out=110,835,959 elapsed=494.7s

  [10781/13157] intraday_7622.csv.gz  in=363,381,743 out=110,849,382 elapsed=494.7s

  [10782/13157] intraday_7624.csv.gz  in=363,392,503 out=110,860,142 elapsed=494.7s

  [10783/13157] intraday_7625.csv.gz  in=363,406,824 out=110,874,463 elapsed=494.7s

  [10784/13157] intraday_7627.csv.gz  in=363,419,418 out=110,887,057 elapsed=494.8s

  [10785/13157] intraday_7626.csv.gz  in=363,433,003 out=110,900,642 elapsed=494.8s

  [10786/13157] intraday_7628.csv.gz  in=363,443,541 out=110,911,180 elapsed=494.8s

  [10787/13157] intraday_7629.csv.gz  in=363,456,874 out=110,924,513 elapsed=494.8s

  [10788/13157] intraday_7633.csv.gz  in=363,470,553 out=110,938,192 elapsed=494.9s

  [10789/13157] intraday_7630.csv.gz  in=363,484,655 out=110,952,294 elapsed=494.9s

  [10790/13157] intraday_7631.csv.gz  in=363,496,102 out=110,963,741 elapsed=494.9s

  [10791/13157] intraday_7632.csv.gz  in=363,511,002 out=110,978,641 elapsed=494.9s

  [10792/13157] intraday_7636.csv.gz  in=363,523,856 out=110,991,495 elapsed=495.0s

  [10793/13157] intraday_7635.csv.gz  in=363,537,394 out=111,005,033 elapsed=495.0s

  [10794/13157] intraday_7637.csv.gz  in=363,549,906 out=111,017,545 elapsed=495.0s

  [10795/13157] intraday_7634.csv.gz  in=363,563,430 out=111,031,069 elapsed=495.1s

  [10796/13157] intraday_7640.csv.gz  in=363,576,484 out=111,044,123 elapsed=495.1s

  [10797/13157] intraday_7638.csv.gz  in=363,589,453 out=111,057,092 elapsed=495.2s

  [10798/13157] intraday_7641.csv.gz  in=363,600,607 out=111,068,246 elapsed=495.2s

  [10799/13157] intraday_7639.csv.gz  in=363,615,806 out=111,083,445 elapsed=495.2s

  [10800/13157] intraday_7642.csv.gz  in=363,630,439 out=111,098,078 elapsed=495.2s

  [10801/13157] intraday_7644.csv.gz  in=363,642,881 out=111,110,520 elapsed=495.2s

  [10802/13157] intraday_7643.csv.gz  in=363,657,269 out=111,124,908 elapsed=495.2s

  [10803/13157] intraday_7645.csv.gz  in=363,671,431 out=111,139,070 elapsed=495.2s

  [10804/13157] intraday_7647.csv.gz  in=363,683,782 out=111,151,421 elapsed=496.0s

  [10805/13157] intraday_7646.csv.gz  in=363,695,507 out=111,163,146 elapsed=496.0s

  [10806/13157] intraday_7648.csv.gz  in=363,706,071 out=111,173,710 elapsed=496.0s

  [10807/13157] intraday_7649.csv.gz  in=363,719,109 out=111,186,748 elapsed=496.0s

  [10808/13157] intraday_7651.csv.gz  in=363,732,042 out=111,199,681 elapsed=496.1s

  [10809/13157] intraday_7650.csv.gz  in=363,747,069 out=111,214,708 elapsed=496.1s

  [10810/13157] intraday_7653.csv.gz  in=363,763,342 out=111,230,937 elapsed=496.1s

  [10811/13157] intraday_7652.csv.gz  in=363,775,643 out=111,243,238 elapsed=496.1s

  [10812/13157] intraday_7657.csv.gz  in=363,788,014 out=111,255,609 elapsed=496.3s

  [10813/13157] intraday_7655.csv.gz  in=363,800,751 out=111,268,346 elapsed=496.3s

  [10814/13157] intraday_7654.csv.gz  in=363,813,421 out=111,281,016 elapsed=496.3s

  [10815/13157] intraday_7656.csv.gz  in=363,825,868 out=111,293,463 elapsed=496.3s

  [10816/13157] intraday_7659.csv.gz  in=363,837,592 out=111,305,187 elapsed=496.3s

  [10817/13157] intraday_7658.csv.gz  in=363,849,630 out=111,317,225 elapsed=496.4s

  [10818/13157] intraday_7660.csv.gz  in=363,862,867 out=111,330,462 elapsed=496.4s

  [10819/13157] intraday_7662.csv.gz  in=363,877,979 out=111,345,574 elapsed=496.4s

  [10820/13157] intraday_7661.csv.gz  in=363,890,662 out=111,358,257 elapsed=496.4s

  [10821/13157] intraday_7663.csv.gz  in=363,905,803 out=111,373,398 elapsed=496.4s

  [10822/13157] intraday_7664.csv.gz  in=363,918,444 out=111,386,039 elapsed=496.4s

  [10823/13157] intraday_7665.csv.gz  in=363,932,113 out=111,399,708 elapsed=496.4s

  [10824/13157] intraday_7666.csv.gz  in=363,942,616 out=111,410,211 elapsed=496.5s

  [10825/13157] intraday_7668.csv.gz  in=363,956,628 out=111,424,223 elapsed=496.5s

  [10826/13157] intraday_7667.csv.gz  in=363,970,774 out=111,438,369 elapsed=496.5s

  [10827/13157] intraday_7669.csv.gz  in=363,982,699 out=111,450,294 elapsed=496.5s

  [10828/13157] intraday_7673.csv.gz  in=363,995,804 out=111,463,399 elapsed=496.5s

  [10829/13157] intraday_7672.csv.gz  in=364,007,029 out=111,474,624 elapsed=496.6s

  [10830/13157] intraday_7670.csv.gz  in=364,020,722 out=111,488,317 elapsed=496.6s

  [10831/13157] intraday_7671.csv.gz  in=364,033,348 out=111,500,943 elapsed=496.6s

  [10832/13157] intraday_7674.csv.gz  in=364,047,184 out=111,514,779 elapsed=496.8s

  [10833/13157] intraday_7677.csv.gz  in=364,060,947 out=111,528,542 elapsed=496.8s

  [10834/13157] intraday_7676.csv.gz  in=364,076,250 out=111,543,845 elapsed=496.8s

  [10835/13157] intraday_7675.csv.gz  in=364,091,959 out=111,559,554 elapsed=496.8s

  [10836/13157] intraday_7678.csv.gz  in=364,103,958 out=111,571,553 elapsed=496.9s

  [10837/13157] intraday_7680.csv.gz  in=364,116,143 out=111,583,738 elapsed=496.9s

  [10838/13157] intraday_7679.csv.gz  in=364,128,114 out=111,595,709 elapsed=496.9s

  [10839/13157] intraday_7684.csv.gz  in=364,138,529 out=111,606,124 elapsed=497.0s

  [10840/13157] intraday_7682.csv.gz  in=364,152,582 out=111,620,177 elapsed=497.0s

  [10841/13157] intraday_7681.csv.gz  in=364,165,255 out=111,632,850 elapsed=497.0s

  [10842/13157] intraday_7683.csv.gz  in=364,178,128 out=111,645,723 elapsed=497.0s

  [10843/13157] intraday_7685.csv.gz  in=364,189,875 out=111,657,470 elapsed=497.0s

  [10844/13157] intraday_7687.csv.gz  in=364,200,907 out=111,668,502 elapsed=497.0s

  [10845/13157] intraday_7688.csv.gz  in=364,213,322 out=111,680,917 elapsed=497.1s

  [10846/13157] intraday_7686.csv.gz  in=364,227,284 out=111,694,879 elapsed=497.1s

  [10847/13157] intraday_7690.csv.gz  in=364,239,759 out=111,707,354 elapsed=497.1s

  [10848/13157] intraday_7689.csv.gz  in=364,250,663 out=111,718,258 elapsed=497.1s

  [10849/13157] intraday_7691.csv.gz  in=364,263,841 out=111,731,436 elapsed=497.1s

  [10850/13157] intraday_7692.csv.gz  in=364,281,627 out=111,749,222 elapsed=497.1s

  [10851/13157] intraday_7696.csv.gz  in=364,295,344 out=111,762,939 elapsed=497.2s

  [10852/13157] intraday_7694.csv.gz  in=364,309,024 out=111,776,619 elapsed=497.2s

  [10853/13157] intraday_7693.csv.gz  in=364,324,620 out=111,792,215 elapsed=497.2s

  [10854/13157] intraday_7695.csv.gz  in=364,336,337 out=111,803,932 elapsed=497.2s

  [10855/13157] intraday_7697.csv.gz  in=364,352,849 out=111,820,444 elapsed=497.2s

  [10856/13157] intraday_7698.csv.gz  in=364,369,427 out=111,837,022 elapsed=497.3s

  [10857/13157] intraday_7700.csv.gz  in=364,383,173 out=111,850,768 elapsed=497.3s

  [10858/13157] intraday_7699.csv.gz  in=364,396,867 out=111,864,462 elapsed=497.3s

  [10859/13157] intraday_7703.csv.gz  in=364,410,860 out=111,878,455 elapsed=497.4s

  [10860/13157] intraday_7701.csv.gz  in=364,424,749 out=111,892,344 elapsed=497.4s

  [10861/13157] intraday_7702.csv.gz  in=364,438,064 out=111,905,659 elapsed=497.4s

  [10862/13157] intraday_7704.csv.gz  in=364,451,626 out=111,919,221 elapsed=497.4s

  [10863/13157] intraday_7705.csv.gz  in=364,464,445 out=111,932,040 elapsed=497.6s

  [10864/13157] intraday_7708.csv.gz  in=364,478,223 out=111,945,818 elapsed=497.6s

  [10865/13157] intraday_7706.csv.gz  in=364,490,927 out=111,958,522 elapsed=497.6s

  [10866/13157] intraday_7707.csv.gz  in=364,504,703 out=111,972,298 elapsed=497.6s

  [10867/13157] intraday_7709.csv.gz  in=364,515,126 out=111,982,721 elapsed=497.7s

  [10868/13157] intraday_7711.csv.gz  in=364,530,919 out=111,998,514 elapsed=497.7s

  [10869/13157] intraday_7710.csv.gz  in=364,543,782 out=112,011,377 elapsed=497.8s

  [10870/13157] intraday_7712.csv.gz  in=364,557,613 out=112,025,208 elapsed=497.8s

  [10871/13157] intraday_7714.csv.gz  in=364,569,786 out=112,037,381 elapsed=497.8s

  [10872/13157] intraday_7715.csv.gz  in=364,586,279 out=112,053,874 elapsed=497.9s

  [10873/13157] intraday_7716.csv.gz  in=364,600,514 out=112,068,109 elapsed=497.9s

  [10874/13157] intraday_7713.csv.gz  in=364,614,726 out=112,082,321 elapsed=497.9s

  [10875/13157] intraday_7717.csv.gz  in=364,629,180 out=112,096,775 elapsed=497.9s

  [10876/13157] intraday_7718.csv.gz  in=364,644,257 out=112,111,852 elapsed=497.9s

  [10877/13157] intraday_7720.csv.gz  in=364,655,529 out=112,123,124 elapsed=498.0s

  [10878/13157] intraday_7721.csv.gz  in=364,670,442 out=112,138,037 elapsed=498.0s

  [10879/13157] intraday_7719.csv.gz  in=364,684,773 out=112,152,368 elapsed=498.0s

  [10880/13157] intraday_7722.csv.gz  in=364,697,951 out=112,165,546 elapsed=498.4s

  [10881/13157] intraday_7723.csv.gz  in=364,711,565 out=112,179,160 elapsed=498.4s

  [10882/13157] intraday_7724.csv.gz  in=364,728,694 out=112,196,289 elapsed=498.4s

  [10883/13157] intraday_7725.csv.gz  in=364,744,418 out=112,212,013 elapsed=498.4s

  [10884/13157] intraday_7726.csv.gz  in=364,760,003 out=112,227,598 elapsed=498.4s

  [10885/13157] intraday_7728.csv.gz  in=364,772,034 out=112,239,629 elapsed=498.4s

  [10886/13157] intraday_7730.csv.gz  in=364,783,550 out=112,251,145 elapsed=498.6s

  [10887/13157] intraday_7727.csv.gz  in=364,798,712 out=112,266,307 elapsed=498.6s

  [10888/13157] intraday_7729.csv.gz  in=364,813,047 out=112,280,642 elapsed=498.6s

  [10889/13157] intraday_7731.csv.gz  in=364,828,490 out=112,296,085 elapsed=498.6s

  [10890/13157] intraday_7734.csv.gz  in=364,841,455 out=112,309,050 elapsed=498.7s

  [10891/13157] intraday_7732.csv.gz  in=364,852,339 out=112,319,934 elapsed=498.7s

  [10892/13157] intraday_7736.csv.gz  in=364,864,158 out=112,331,753 elapsed=498.8s

  [10893/13157] intraday_7737.csv.gz  in=364,877,828 out=112,345,423 elapsed=498.8s

  [10894/13157] intraday_7733.csv.gz  in=364,893,005 out=112,360,600 elapsed=498.8s

  [10895/13157] intraday_7735.csv.gz  in=364,908,615 out=112,376,210 elapsed=498.8s

  [10896/13157] intraday_7738.csv.gz  in=364,921,965 out=112,389,560 elapsed=498.8s

  [10897/13157] intraday_7741.csv.gz  in=364,936,817 out=112,404,412 elapsed=498.8s

  [10898/13157] intraday_7739.csv.gz  in=364,948,804 out=112,416,399 elapsed=498.8s

  [10899/13157] intraday_7740.csv.gz  in=364,961,873 out=112,429,468 elapsed=498.8s

  [10900/13157] intraday_7742.csv.gz  in=364,976,614 out=112,444,209 elapsed=498.9s

  [10901/13157] intraday_7744.csv.gz  in=364,991,039 out=112,458,634 elapsed=498.9s

  [10902/13157] intraday_7745.csv.gz  in=365,002,750 out=112,470,345 elapsed=498.9s

  [10903/13157] intraday_7743.csv.gz  in=365,017,513 out=112,485,108 elapsed=498.9s

  [10904/13157] intraday_7747.csv.gz  in=365,031,886 out=112,499,481 elapsed=499.0s

  [10905/13157] intraday_7746.csv.gz  in=365,044,128 out=112,511,723 elapsed=499.0s

  [10906/13157] intraday_7748.csv.gz  in=365,056,929 out=112,524,524 elapsed=499.0s

  [10907/13157] intraday_7749.csv.gz  in=365,069,455 out=112,537,050 elapsed=499.0s

  [10908/13157] intraday_7750.csv.gz  in=365,078,697 out=112,546,292 elapsed=499.0s

  [10909/13157] intraday_7752.csv.gz  in=365,087,165 out=112,554,760 elapsed=499.1s

  [10910/13157] intraday_7753.csv.gz  in=365,102,908 out=112,570,503 elapsed=499.1s

  [10911/13157] intraday_7751.csv.gz  in=365,115,400 out=112,582,995 elapsed=499.1s

  [10912/13157] intraday_7754.csv.gz  in=365,128,942 out=112,596,537 elapsed=499.1s

  [10913/13157] intraday_7755.csv.gz  in=365,141,097 out=112,608,692 elapsed=499.1s

  [10914/13157] intraday_7756.csv.gz  in=365,154,237 out=112,621,832 elapsed=499.2s

  [10915/13157] intraday_7757.csv.gz  in=365,165,463 out=112,633,058 elapsed=499.2s

  [10916/13157] intraday_7759.csv.gz  in=365,182,829 out=112,650,424 elapsed=499.2s

  [10917/13157] intraday_7758.csv.gz  in=365,196,820 out=112,664,415 elapsed=499.2s

  [10918/13157] intraday_7760.csv.gz  in=365,207,607 out=112,675,202 elapsed=499.2s

  [10919/13157] intraday_7762.csv.gz  in=365,221,353 out=112,688,948 elapsed=499.2s

  [10920/13157] intraday_7761.csv.gz  in=365,234,659 out=112,702,254 elapsed=499.2s

  [10921/13157] intraday_7763.csv.gz  in=365,249,609 out=112,717,204 elapsed=499.2s

  [10922/13157] intraday_7767.csv.gz  in=365,259,733 out=112,727,328 elapsed=499.3s

  [10923/13157] intraday_7766.csv.gz  in=365,272,695 out=112,740,290 elapsed=499.3s

  [10924/13157] intraday_7765.csv.gz  in=365,286,699 out=112,754,294 elapsed=499.3s

  [10925/13157] intraday_7764.csv.gz  in=365,298,570 out=112,766,165 elapsed=499.3s

  [10926/13157] intraday_7768.csv.gz  in=365,310,966 out=112,778,561 elapsed=499.6s

  [10927/13157] intraday_7770.csv.gz  in=365,325,216 out=112,792,811 elapsed=499.6s

  [10928/13157] intraday_7771.csv.gz  in=365,336,029 out=112,803,624 elapsed=499.6s

  [10929/13157] intraday_7769.csv.gz  in=365,350,410 out=112,818,005 elapsed=499.6s

  [10930/13157] intraday_7772.csv.gz  in=365,362,585 out=112,830,180 elapsed=499.7s

  [10931/13157] intraday_7774.csv.gz  in=365,375,858 out=112,843,453 elapsed=499.7s

  [10932/13157] intraday_7773.csv.gz  in=365,387,780 out=112,855,375 elapsed=499.7s

  [10933/13157] intraday_7775.csv.gz  in=365,398,988 out=112,866,583 elapsed=499.7s

  [10934/13157] intraday_7779.csv.gz  in=365,410,576 out=112,878,171 elapsed=499.9s

  [10935/13157] intraday_7777.csv.gz  in=365,423,558 out=112,891,153 elapsed=499.9s

  [10936/13157] intraday_7778.csv.gz  in=365,439,809 out=112,907,404 elapsed=499.9s

  [10937/13157] intraday_7776.csv.gz  in=365,455,050 out=112,922,645 elapsed=499.9s

  [10938/13157] intraday_7781.csv.gz  in=365,468,295 out=112,935,604 elapsed=500.0s

  [10939/13157] intraday_7780.csv.gz  in=365,481,254 out=112,948,563 elapsed=500.0s

  [10940/13157] intraday_7782.csv.gz  in=365,493,629 out=112,960,938 elapsed=500.0s

  [10941/13157] intraday_7783.csv.gz  in=365,509,563 out=112,976,872 elapsed=500.0s

  [10942/13157] intraday_7785.csv.gz  in=365,520,057 out=112,987,366 elapsed=500.1s

  [10943/13157] intraday_7787.csv.gz  in=365,533,905 out=113,001,214 elapsed=500.1s

  [10944/13157] intraday_7786.csv.gz  in=365,546,918 out=113,014,227 elapsed=500.1s

  [10945/13157] intraday_7784.csv.gz  in=365,560,368 out=113,027,677 elapsed=500.1s

  [10946/13157] intraday_7790.csv.gz  in=365,572,504 out=113,039,813 elapsed=500.2s

  [10947/13157] intraday_7791.csv.gz  in=365,585,181 out=113,052,490 elapsed=500.2s

  [10948/13157] intraday_7788.csv.gz  in=365,597,731 out=113,065,040 elapsed=500.2s

  [10949/13157] intraday_7789.csv.gz  in=365,611,651 out=113,078,960 elapsed=500.2s

  [10950/13157] intraday_7792.csv.gz  in=365,622,748 out=113,090,057 elapsed=500.2s

  [10951/13157] intraday_7793.csv.gz  in=365,634,909 out=113,102,218 elapsed=500.2s

  [10952/13157] intraday_7794.csv.gz  in=365,648,800 out=113,115,448 elapsed=500.2s

  [10953/13157] intraday_7795.csv.gz  in=365,662,963 out=113,129,611 elapsed=500.2s

  [10954/13157] intraday_7796.csv.gz  in=365,673,784 out=113,140,432 elapsed=500.3s

  [10955/13157] intraday_7798.csv.gz  in=365,685,646 out=113,152,294 elapsed=500.3s

  [10956/13157] intraday_7797.csv.gz  in=365,701,357 out=113,168,005 elapsed=500.3s

  [10957/13157] intraday_7799.csv.gz  in=365,713,477 out=113,180,125 elapsed=500.3s

  [10958/13157] intraday_7802.csv.gz  in=365,725,509 out=113,192,157 elapsed=500.4s

  [10959/13157] intraday_7800.csv.gz  in=365,739,237 out=113,205,885 elapsed=500.4s

  [10960/13157] intraday_7803.csv.gz  in=365,751,109 out=113,217,757 elapsed=500.4s

  [10961/13157] intraday_7801.csv.gz  in=365,762,312 out=113,228,960 elapsed=500.4s

  [10962/13157] intraday_7804.csv.gz  in=365,773,757 out=113,240,405 elapsed=500.4s

  [10963/13157] intraday_7806.csv.gz  in=365,787,234 out=113,253,882 elapsed=500.5s

  [10964/13157] intraday_7805.csv.gz  in=365,802,121 out=113,268,769 elapsed=500.5s

  [10965/13157] intraday_7807.csv.gz  in=365,815,953 out=113,282,601 elapsed=500.5s

  [10966/13157] intraday_7808.csv.gz  in=365,829,879 out=113,296,527 elapsed=500.5s

  [10967/13157] intraday_7812.csv.gz  in=365,841,650 out=113,308,298 elapsed=500.6s

  [10968/13157] intraday_7809.csv.gz  in=365,854,938 out=113,321,140 elapsed=500.6s

  [10969/13157] intraday_7810.csv.gz  in=365,867,051 out=113,333,253 elapsed=500.6s

  [10970/13157] intraday_7811.csv.gz  in=365,882,035 out=113,348,237 elapsed=500.6s

  [10971/13157] intraday_7815.csv.gz  in=365,893,321 out=113,359,523 elapsed=500.9s

  [10972/13157] intraday_7816.csv.gz  in=365,905,513 out=113,371,715 elapsed=500.9s

  [10973/13157] intraday_7814.csv.gz  in=365,918,575 out=113,384,777 elapsed=500.9s

  [10974/13157] intraday_7813.csv.gz  in=365,934,012 out=113,400,214 elapsed=500.9s

  [10975/13157] intraday_7817.csv.gz  in=365,944,871 out=113,411,073 elapsed=500.9s

  [10976/13157] intraday_7818.csv.gz  in=365,958,639 out=113,424,841 elapsed=500.9s

  [10977/13157] intraday_7819.csv.gz  in=365,973,337 out=113,439,539 elapsed=501.0s

  [10978/13157] intraday_7821.csv.gz  in=365,986,087 out=113,452,289 elapsed=501.0s

  [10979/13157] intraday_7820.csv.gz  in=366,001,349 out=113,467,551 elapsed=501.0s

  [10980/13157] intraday_7822.csv.gz  in=366,012,924 out=113,479,126 elapsed=501.0s

  [10981/13157] intraday_7823.csv.gz  in=366,025,445 out=113,491,647 elapsed=501.0s

  [10982/13157] intraday_7824.csv.gz  in=366,037,047 out=113,503,249 elapsed=501.0s

  [10983/13157] intraday_7825.csv.gz  in=366,050,414 out=113,516,616 elapsed=501.0s

  [10984/13157] intraday_7826.csv.gz  in=366,064,253 out=113,530,455 elapsed=501.2s

  [10985/13157] intraday_7829.csv.gz  in=366,075,355 out=113,541,557 elapsed=501.2s

  [10986/13157] intraday_7827.csv.gz  in=366,086,961 out=113,553,163 elapsed=501.2s

  [10987/13157] intraday_7828.csv.gz  in=366,098,726 out=113,564,928 elapsed=501.2s

  [10988/13157] intraday_7831.csv.gz  in=366,109,362 out=113,575,564 elapsed=501.4s

  [10989/13157] intraday_7832.csv.gz  in=366,121,111 out=113,587,313 elapsed=501.4s

  [10990/13157] intraday_7833.csv.gz  in=366,131,880 out=113,598,082 elapsed=501.4s

  [10991/13157] intraday_7830.csv.gz  in=366,145,071 out=113,611,273 elapsed=501.4s

  [10992/13157] intraday_7834.csv.gz  in=366,158,318 out=113,623,847 elapsed=501.5s

  [10993/13157] intraday_7835.csv.gz  in=366,170,459 out=113,635,988 elapsed=501.5s

  [10994/13157] intraday_7836.csv.gz  in=366,189,230 out=113,654,759 elapsed=501.6s

  [10995/13157] intraday_7837.csv.gz  in=366,205,582 out=113,671,111 elapsed=501.6s

  [10996/13157] intraday_7838.csv.gz  in=366,218,518 out=113,684,047 elapsed=501.6s

  [10997/13157] intraday_7840.csv.gz  in=366,229,979 out=113,695,508 elapsed=501.7s

  [10998/13157] intraday_7839.csv.gz  in=366,241,815 out=113,707,344 elapsed=501.7s

  [10999/13157] intraday_7841.csv.gz  in=366,257,807 out=113,723,031 elapsed=501.8s

  [11000/13157] intraday_7844.csv.gz  in=366,269,528 out=113,734,752 elapsed=501.8s

  [11001/13157] intraday_7842.csv.gz  in=366,283,891 out=113,749,115 elapsed=501.8s

  [11002/13157] intraday_7843.csv.gz  in=366,299,179 out=113,764,403 elapsed=501.8s

  [11003/13157] intraday_7845.csv.gz  in=366,314,115 out=113,779,339 elapsed=501.9s

  [11004/13157] intraday_7847.csv.gz  in=366,326,159 out=113,791,383 elapsed=501.9s

  [11005/13157] intraday_7846.csv.gz  in=366,340,975 out=113,806,199 elapsed=501.9s

  [11006/13157] intraday_7848.csv.gz  in=366,355,786 out=113,821,010 elapsed=501.9s

  [11007/13157] intraday_7849.csv.gz  in=366,367,489 out=113,832,713 elapsed=502.0s

  [11008/13157] intraday_7852.csv.gz  in=366,380,029 out=113,845,253 elapsed=502.0s

  [11009/13157] intraday_7851.csv.gz  in=366,393,253 out=113,858,477 elapsed=502.0s

  [11010/13157] intraday_7850.csv.gz  in=366,405,956 out=113,871,180 elapsed=502.0s

  [11011/13157] intraday_7853.csv.gz  in=366,417,749 out=113,882,973 elapsed=502.0s

  [11012/13157] intraday_7855.csv.gz  in=366,429,716 out=113,894,940 elapsed=502.2s

  [11013/13157] intraday_7854.csv.gz  in=366,444,511 out=113,909,735 elapsed=502.2s

  [11014/13157] intraday_7857.csv.gz  in=366,456,092 out=113,921,316 elapsed=502.3s

  [11015/13157] intraday_7856.csv.gz  in=366,472,523 out=113,937,747 elapsed=502.6s

  [11016/13157] intraday_7860.csv.gz  in=366,487,706 out=113,951,573 elapsed=502.6s

  [11017/13157] intraday_7858.csv.gz  in=366,500,088 out=113,963,955 elapsed=502.6s

  [11018/13157] intraday_7859.csv.gz  in=366,516,847 out=113,980,714 elapsed=502.6s

  [11019/13157] intraday_7861.csv.gz  in=366,529,098 out=113,992,965 elapsed=502.7s

  [11020/13157] intraday_7864.csv.gz  in=366,539,300 out=114,003,167 elapsed=502.8s

  [11021/13157] intraday_7863.csv.gz  in=366,553,931 out=114,017,798 elapsed=502.8s

  [11022/13157] intraday_7862.csv.gz  in=366,569,679 out=114,033,546 elapsed=502.8s

  [11023/13157] intraday_7865.csv.gz  in=366,583,090 out=114,046,957 elapsed=502.8s

  [11024/13157] intraday_7866.csv.gz  in=366,596,413 out=114,060,280 elapsed=502.9s

  [11025/13157] intraday_7869.csv.gz  in=366,612,140 out=114,076,007 elapsed=502.9s

  [11026/13157] intraday_7867.csv.gz  in=366,626,811 out=114,090,678 elapsed=502.9s

  [11027/13157] intraday_7868.csv.gz  in=366,646,419 out=114,110,286 elapsed=502.9s

  [11028/13157] intraday_7870.csv.gz  in=366,659,477 out=114,123,344 elapsed=503.1s

  [11029/13157] intraday_7873.csv.gz  in=366,671,320 out=114,135,187 elapsed=503.1s

  [11030/13157] intraday_7872.csv.gz  in=366,684,711 out=114,148,578 elapsed=503.1s

  [11031/13157] intraday_7871.csv.gz  in=366,701,567 out=114,165,434 elapsed=503.1s

  [11032/13157] intraday_7874.csv.gz  in=366,713,941 out=114,177,808 elapsed=503.3s

  [11033/13157] intraday_7877.csv.gz  in=366,727,998 out=114,191,865 elapsed=503.3s

  [11034/13157] intraday_7876.csv.gz  in=366,739,382 out=114,203,249 elapsed=503.3s

  [11035/13157] intraday_7875.csv.gz  in=366,753,396 out=114,217,263 elapsed=503.3s

  [11036/13157] intraday_7878.csv.gz  in=366,765,833 out=114,229,700 elapsed=503.4s

  [11037/13157] intraday_7879.csv.gz  in=366,779,557 out=114,243,424 elapsed=503.5s

  [11038/13157] intraday_7881.csv.gz  in=366,791,141 out=114,255,008 elapsed=503.5s

  [11039/13157] intraday_7880.csv.gz  in=366,806,056 out=114,269,923 elapsed=503.5s

  [11040/13157] intraday_7882.csv.gz  in=366,819,959 out=114,283,826 elapsed=503.6s

  [11041/13157] intraday_7883.csv.gz  in=366,832,688 out=114,296,555 elapsed=503.6s

  [11042/13157] intraday_7884.csv.gz  in=366,845,133 out=114,309,000 elapsed=503.6s

  [11043/13157] intraday_7885.csv.gz  in=366,857,582 out=114,321,449 elapsed=503.6s

  [11044/13157] intraday_7886.csv.gz  in=366,872,748 out=114,336,615 elapsed=503.6s

  [11045/13157] intraday_7887.csv.gz  in=366,886,400 out=114,350,267 elapsed=503.6s

  [11046/13157] intraday_7888.csv.gz  in=366,898,614 out=114,362,481 elapsed=503.7s

  [11047/13157] intraday_7889.csv.gz  in=366,913,561 out=114,377,428 elapsed=503.7s

  [11048/13157] intraday_7891.csv.gz  in=366,926,718 out=114,390,585 elapsed=503.7s

  [11049/13157] intraday_7890.csv.gz  in=366,938,044 out=114,401,911 elapsed=503.7s

  [11050/13157] intraday_7894.csv.gz  in=366,948,288 out=114,412,155 elapsed=503.7s

  [11051/13157] intraday_7895.csv.gz  in=366,958,933 out=114,422,800 elapsed=503.8s

  [11052/13157] intraday_7892.csv.gz  in=366,970,285 out=114,434,152 elapsed=503.8s

  [11053/13157] intraday_7893.csv.gz  in=366,984,680 out=114,448,547 elapsed=503.8s

  [11054/13157] intraday_7897.csv.gz  in=366,986,341 out=114,450,208 elapsed=503.8s

  [11055/13157] intraday_7896.csv.gz  in=367,000,078 out=114,463,945 elapsed=503.8s

  [11056/13157] intraday_7898.csv.gz  in=367,017,011 out=114,476,145 elapsed=503.8s

  [11057/13157] intraday_7899.csv.gz  in=367,033,171 out=114,492,305 elapsed=503.8s

  [11058/13157] intraday_7900.csv.gz  in=367,048,550 out=114,506,761 elapsed=503.8s

  [11059/13157] intraday_7902.csv.gz  in=367,059,981 out=114,518,192 elapsed=503.9s

  [11060/13157] intraday_7904.csv.gz  in=367,074,234 out=114,532,445 elapsed=503.9s

  [11061/13157] intraday_7903.csv.gz  in=367,084,823 out=114,543,034 elapsed=503.9s

  [11062/13157] intraday_7901.csv.gz  in=367,098,079 out=114,556,290 elapsed=503.9s

  [11063/13157] intraday_7906.csv.gz  in=367,109,711 out=114,567,922 elapsed=504.1s

  [11064/13157] intraday_7907.csv.gz  in=367,123,488 out=114,581,699 elapsed=504.1s

  [11065/13157] intraday_7908.csv.gz  in=367,137,492 out=114,595,703 elapsed=504.1s

  [11066/13157] intraday_7905.csv.gz  in=367,153,116 out=114,611,327 elapsed=504.1s

  [11067/13157] intraday_7909.csv.gz  in=367,168,521 out=114,626,732 elapsed=504.1s

  [11068/13157] intraday_7911.csv.gz  in=367,182,038 out=114,640,249 elapsed=504.3s

  [11069/13157] intraday_7910.csv.gz  in=367,194,934 out=114,653,145 elapsed=504.3s

  [11070/13157] intraday_7913.csv.gz  in=367,206,046 out=114,664,257 elapsed=504.3s

  [11071/13157] intraday_7912.csv.gz  in=367,221,372 out=114,679,583 elapsed=504.4s

  [11072/13157] intraday_7914.csv.gz  in=367,231,309 out=114,689,520 elapsed=504.4s

  [11073/13157] intraday_7916.csv.gz  in=367,244,480 out=114,702,691 elapsed=504.4s

  [11074/13157] intraday_7915.csv.gz  in=367,258,742 out=114,716,953 elapsed=504.4s

  [11075/13157] intraday_7917.csv.gz  in=367,269,548 out=114,727,759 elapsed=504.4s

  [11076/13157] intraday_7918.csv.gz  in=367,280,980 out=114,739,191 elapsed=504.5s

  [11077/13157] intraday_7919.csv.gz  in=367,292,093 out=114,750,304 elapsed=504.5s

  [11078/13157] intraday_7921.csv.gz  in=367,304,203 out=114,762,414 elapsed=504.5s

  [11079/13157] intraday_7920.csv.gz  in=367,318,013 out=114,776,224 elapsed=504.5s

  [11080/13157] intraday_7923.csv.gz  in=367,332,304 out=114,790,515 elapsed=504.5s

  [11081/13157] intraday_7922.csv.gz  in=367,347,021 out=114,805,232 elapsed=504.5s

  [11082/13157] intraday_7924.csv.gz  in=367,360,782 out=114,818,993 elapsed=504.6s

  [11083/13157] intraday_7926.csv.gz  in=367,372,232 out=114,830,443 elapsed=504.6s

  [11084/13157] intraday_7927.csv.gz  in=367,384,362 out=114,842,573 elapsed=504.6s

  [11085/13157] intraday_7925.csv.gz  in=367,397,676 out=114,855,887 elapsed=504.6s

  [11086/13157] intraday_7928.csv.gz  in=367,411,927 out=114,870,138 elapsed=504.6s

  [11087/13157] intraday_7931.csv.gz  in=367,421,739 out=114,879,950 elapsed=504.7s

  [11088/13157] intraday_7930.csv.gz  in=367,434,782 out=114,892,993 elapsed=504.7s

  [11089/13157] intraday_7929.csv.gz  in=367,450,707 out=114,908,918 elapsed=504.7s

  [11090/13157] intraday_7932.csv.gz  in=367,465,196 out=114,923,407 elapsed=504.8s

  [11091/13157] intraday_7933.csv.gz  in=367,479,130 out=114,937,341 elapsed=504.8s

  [11092/13157] intraday_7934.csv.gz  in=367,490,859 out=114,949,070 elapsed=504.9s

  [11093/13157] intraday_7936.csv.gz  in=367,504,206 out=114,962,417 elapsed=504.9s

  [11094/13157] intraday_7935.csv.gz  in=367,517,349 out=114,975,560 elapsed=504.9s

  [11095/13157] intraday_7937.csv.gz  in=367,530,482 out=114,988,693 elapsed=504.9s

  [11096/13157] intraday_7938.csv.gz  in=367,541,182 out=114,999,393 elapsed=505.0s

  [11097/13157] intraday_7941.csv.gz  in=367,555,756 out=115,013,967 elapsed=505.0s

  [11098/13157] intraday_7940.csv.gz  in=367,567,954 out=115,026,165 elapsed=505.0s

  [11099/13157] intraday_7939.csv.gz  in=367,580,235 out=115,038,446 elapsed=505.0s

  [11100/13157] intraday_7942.csv.gz  in=367,592,273 out=115,050,484 elapsed=505.0s

  [11101/13157] intraday_7944.csv.gz  in=367,604,217 out=115,062,428 elapsed=505.1s

  [11102/13157] intraday_7945.csv.gz  in=367,615,475 out=115,073,686 elapsed=505.1s

  [11103/13157] intraday_7943.csv.gz  in=367,630,180 out=115,088,391 elapsed=505.1s

  [11104/13157] intraday_7949.csv.gz  in=367,643,204 out=115,101,415 elapsed=505.1s

  [11105/13157] intraday_7946.csv.gz  in=367,657,837 out=115,116,048 elapsed=505.1s

  [11106/13157] intraday_7947.csv.gz  in=367,670,301 out=115,128,512 elapsed=505.1s

  [11107/13157] intraday_7948.csv.gz  in=367,682,152 out=115,140,363 elapsed=505.1s

  [11108/13157] intraday_7951.csv.gz  in=367,695,900 out=115,154,111 elapsed=505.3s

  [11109/13157] intraday_7953.csv.gz  in=367,710,706 out=115,168,917 elapsed=505.3s

  [11110/13157] intraday_7950.csv.gz  in=367,723,374 out=115,181,585 elapsed=505.3s

  [11111/13157] intraday_7952.csv.gz  in=367,737,150 out=115,195,361 elapsed=505.3s

  [11112/13157] intraday_7954.csv.gz  in=367,749,952 out=115,208,163 elapsed=505.4s

  [11113/13157] intraday_7955.csv.gz  in=367,762,100 out=115,220,311 elapsed=505.4s

  [11114/13157] intraday_7957.csv.gz  in=367,776,407 out=115,234,618 elapsed=505.5s

  [11115/13157] intraday_7956.csv.gz  in=367,787,333 out=115,245,544 elapsed=505.5s

  [11116/13157] intraday_7960.csv.gz  in=367,800,535 out=115,258,746 elapsed=505.6s

  [11117/13157] intraday_7959.csv.gz  in=367,813,422 out=115,271,633 elapsed=505.6s

  [11118/13157] intraday_7961.csv.gz  in=367,825,426 out=115,283,637 elapsed=505.6s

  [11119/13157] intraday_7958.csv.gz  in=367,839,184 out=115,297,395 elapsed=505.6s

  [11120/13157] intraday_7963.csv.gz  in=367,850,705 out=115,308,916 elapsed=505.7s

  [11121/13157] intraday_7964.csv.gz  in=367,864,993 out=115,323,204 elapsed=505.7s

  [11122/13157] intraday_7965.csv.gz  in=367,878,648 out=115,336,859 elapsed=505.7s

  [11123/13157] intraday_7962.csv.gz  in=367,890,090 out=115,348,301 elapsed=505.7s

  [11124/13157] intraday_7966.csv.gz  in=367,903,788 out=115,361,999 elapsed=505.7s

  [11125/13157] intraday_7968.csv.gz  in=367,914,990 out=115,373,201 elapsed=505.7s

  [11126/13157] intraday_7969.csv.gz  in=367,927,652 out=115,385,863 elapsed=505.8s

  [11127/13157] intraday_7970.csv.gz  in=367,940,165 out=115,398,376 elapsed=505.8s

  [11128/13157] intraday_7967.csv.gz  in=367,955,430 out=115,412,797 elapsed=505.8s

  [11129/13157] intraday_7971.csv.gz  in=367,967,694 out=115,425,061 elapsed=505.8s

  [11130/13157] intraday_7972.csv.gz  in=367,981,697 out=115,439,064 elapsed=505.8s

  [11131/13157] intraday_7974.csv.gz  in=367,991,879 out=115,449,246 elapsed=505.8s

  [11132/13157] intraday_7973.csv.gz  in=368,004,033 out=115,461,400 elapsed=505.8s

  [11133/13157] intraday_7977.csv.gz  in=368,015,235 out=115,472,602 elapsed=505.9s

  [11134/13157] intraday_7976.csv.gz  in=368,027,134 out=115,484,501 elapsed=505.9s

  [11135/13157] intraday_7975.csv.gz  in=368,041,040 out=115,498,407 elapsed=505.9s

  [11136/13157] intraday_7978.csv.gz  in=368,056,904 out=115,512,622 elapsed=505.9s

  [11137/13157] intraday_7979.csv.gz  in=368,067,770 out=115,522,936 elapsed=506.1s

  [11138/13157] intraday_7981.csv.gz  in=368,080,916 out=115,536,082 elapsed=506.1s

  [11139/13157] intraday_7980.csv.gz  in=368,092,773 out=115,547,939 elapsed=506.1s

  [11140/13157] intraday_7982.csv.gz  in=368,109,201 out=115,564,367 elapsed=506.1s

  [11141/13157] intraday_7984.csv.gz  in=368,122,183 out=115,577,349 elapsed=506.4s

  [11142/13157] intraday_7986.csv.gz  in=368,134,482 out=115,589,648 elapsed=506.4s

  [11143/13157] intraday_7985.csv.gz  in=368,147,440 out=115,602,606 elapsed=506.4s

  [11144/13157] intraday_7983.csv.gz  in=368,163,609 out=115,618,775 elapsed=506.4s

  [11145/13157] intraday_7990.csv.gz  in=368,176,110 out=115,631,276 elapsed=506.6s

  [11146/13157] intraday_7989.csv.gz  in=368,188,385 out=115,643,551 elapsed=506.7s

  [11147/13157] intraday_7987.csv.gz  in=368,201,223 out=115,656,389 elapsed=506.7s

  [11148/13157] intraday_7988.csv.gz  in=368,217,373 out=115,672,539 elapsed=506.7s

  [11149/13157] intraday_7991.csv.gz  in=368,231,227 out=115,686,393 elapsed=506.7s

  [11150/13157] intraday_7992.csv.gz  in=368,245,986 out=115,701,152 elapsed=506.7s

  [11151/13157] intraday_7994.csv.gz  in=368,260,247 out=115,715,328 elapsed=506.7s

  [11152/13157] intraday_7995.csv.gz  in=368,272,043 out=115,727,124 elapsed=506.7s

  [11153/13157] intraday_7993.csv.gz  in=368,287,316 out=115,742,397 elapsed=506.7s

  [11154/13157] intraday_7996.csv.gz  in=368,300,148 out=115,755,229 elapsed=506.8s

  [11155/13157] intraday_7997.csv.gz  in=368,313,356 out=115,768,437 elapsed=506.8s

  [11156/13157] intraday_7999.csv.gz  in=368,325,685 out=115,780,766 elapsed=506.8s

  [11157/13157] intraday_7998.csv.gz  in=368,340,498 out=115,795,579 elapsed=506.8s

  [11158/13157] intraday_8000.csv.gz  in=368,350,798 out=115,805,879 elapsed=506.8s

  [11159/13157] intraday_8001.csv.gz  in=368,366,852 out=115,821,933 elapsed=506.8s

  [11160/13157] intraday_8002.csv.gz  in=368,380,075 out=115,835,156 elapsed=506.9s

  [11161/13157] intraday_8004.csv.gz  in=368,392,291 out=115,847,372 elapsed=506.9s

  [11162/13157] intraday_8003.csv.gz  in=368,407,262 out=115,862,334 elapsed=506.9s

  [11163/13157] intraday_8005.csv.gz  in=368,426,081 out=115,881,153 elapsed=506.9s

  [11164/13157] intraday_8006.csv.gz  in=368,439,203 out=115,894,275 elapsed=506.9s

  [11165/13157] intraday_8008.csv.gz  in=368,453,934 out=115,909,006 elapsed=506.9s

  [11166/13157] intraday_8009.csv.gz  in=368,468,342 out=115,923,414 elapsed=507.0s

  [11167/13157] intraday_8007.csv.gz  in=368,481,452 out=115,936,524 elapsed=507.0s

  [11168/13157] intraday_8010.csv.gz  in=368,493,020 out=115,948,092 elapsed=507.0s

  [11169/13157] intraday_8011.csv.gz  in=368,508,507 out=115,963,579 elapsed=507.0s

  [11170/13157] intraday_8013.csv.gz  in=368,523,455 out=115,978,527 elapsed=507.0s

  [11171/13157] intraday_8012.csv.gz  in=368,537,882 out=115,992,954 elapsed=507.0s

  [11172/13157] intraday_8014.csv.gz  in=368,553,725 out=116,008,797 elapsed=507.0s

  [11173/13157] intraday_8016.csv.gz  in=368,566,695 out=116,021,767 elapsed=507.1s

  [11174/13157] intraday_8018.csv.gz  in=368,578,605 out=116,033,677 elapsed=507.1s

  [11175/13157] intraday_8015.csv.gz  in=368,593,819 out=116,048,891 elapsed=507.1s

  [11176/13157] intraday_8019.csv.gz  in=368,607,434 out=116,061,993 elapsed=507.1s

  [11177/13157] intraday_8017.csv.gz  in=368,626,091 out=116,079,442 elapsed=507.1s

  [11178/13157] intraday_8021.csv.gz  in=368,639,749 out=116,093,100 elapsed=507.1s

  [11179/13157] intraday_8020.csv.gz  in=368,652,703 out=116,106,054 elapsed=507.1s

  [11180/13157] intraday_8022.csv.gz  in=368,663,916 out=116,117,267 elapsed=507.2s

  [11181/13157] intraday_8023.csv.gz  in=368,678,981 out=116,132,332 elapsed=507.2s

  [11182/13157] intraday_8026.csv.gz  in=368,690,785 out=116,144,136 elapsed=507.2s

  [11183/13157] intraday_8024.csv.gz  in=368,710,777 out=116,164,128 elapsed=507.2s

  [11184/13157] intraday_8025.csv.gz  in=368,727,166 out=116,180,517 elapsed=507.2s

  [11185/13157] intraday_8027.csv.gz  in=368,740,936 out=116,194,287 elapsed=507.2s

  [11186/13157] intraday_8030.csv.gz  in=368,752,743 out=116,206,094 elapsed=507.4s

  [11187/13157] intraday_8028.csv.gz  in=368,765,105 out=116,218,456 elapsed=507.4s

  [11188/13157] intraday_8031.csv.gz  in=368,779,350 out=116,232,701 elapsed=507.4s

  [11189/13157] intraday_8029.csv.gz  in=368,792,840 out=116,246,191 elapsed=507.4s

  [11190/13157] intraday_8032.csv.gz  in=368,807,571 out=116,260,922 elapsed=508.0s

  [11191/13157] intraday_8035.csv.gz  in=368,822,353 out=116,275,507 elapsed=508.1s

  [11192/13157] intraday_8034.csv.gz  in=368,837,892 out=116,291,046 elapsed=508.1s

  [11193/13157] intraday_8033.csv.gz  in=368,851,966 out=116,305,120 elapsed=508.1s

  [11194/13157] intraday_8036.csv.gz  in=368,862,251 out=116,315,405 elapsed=508.1s

  [11195/13157] intraday_8037.csv.gz  in=368,875,939 out=116,329,093 elapsed=508.1s

  [11196/13157] intraday_8038.csv.gz  in=368,887,689 out=116,340,843 elapsed=508.1s

  [11197/13157] intraday_8040.csv.gz  in=368,896,033 out=116,349,187 elapsed=508.1s

  [11198/13157] intraday_8039.csv.gz  in=368,911,442 out=116,364,596 elapsed=508.1s

  [11199/13157] intraday_8042.csv.gz  in=368,922,780 out=116,375,934 elapsed=508.2s

  [11200/13157] intraday_8043.csv.gz  in=368,932,777 out=116,381,737 elapsed=508.2s

  [11201/13157] intraday_8041.csv.gz  in=368,945,026 out=116,393,986 elapsed=508.2s

  [11202/13157] intraday_8044.csv.gz  in=368,960,126 out=116,409,086 elapsed=508.2s

  [11203/13157] intraday_8045.csv.gz  in=368,974,428 out=116,423,388 elapsed=508.3s

  [11204/13157] intraday_8047.csv.gz  in=368,985,685 out=116,434,645 elapsed=508.3s

  [11205/13157] intraday_8048.csv.gz  in=368,996,880 out=116,445,840 elapsed=508.3s

  [11206/13157] intraday_8046.csv.gz  in=369,009,788 out=116,458,748 elapsed=508.3s

  [11207/13157] intraday_8051.csv.gz  in=369,022,264 out=116,471,224 elapsed=508.4s

  [11208/13157] intraday_8052.csv.gz  in=369,035,693 out=116,484,653 elapsed=508.4s

  [11209/13157] intraday_8050.csv.gz  in=369,049,761 out=116,498,721 elapsed=508.4s

  [11210/13157] intraday_8049.csv.gz  in=369,064,505 out=116,513,465 elapsed=508.4s

  [11211/13157] intraday_8053.csv.gz  in=369,080,018 out=116,528,978 elapsed=508.4s

  [11212/13157] intraday_8056.csv.gz  in=369,093,250 out=116,542,210 elapsed=508.4s

  [11213/13157] intraday_8055.csv.gz  in=369,106,437 out=116,555,397 elapsed=508.5s

  [11214/13157] intraday_8054.csv.gz  in=369,120,755 out=116,569,715 elapsed=508.5s

  [11215/13157] intraday_8059.csv.gz  in=369,130,791 out=116,579,751 elapsed=508.5s

  [11216/13157] intraday_8057.csv.gz  in=369,144,069 out=116,593,029 elapsed=508.5s

  [11217/13157] intraday_8058.csv.gz  in=369,153,525 out=116,602,485 elapsed=508.5s

  [11218/13157] intraday_8060.csv.gz  in=369,166,875 out=116,615,835 elapsed=508.6s

  [11219/13157] intraday_8061.csv.gz  in=369,179,270 out=116,628,230 elapsed=508.6s

  [11220/13157] intraday_8062.csv.gz  in=369,189,998 out=116,638,958 elapsed=508.6s

  [11221/13157] intraday_8063.csv.gz  in=369,202,158 out=116,650,745 elapsed=508.6s

  [11222/13157] intraday_8064.csv.gz  in=369,214,181 out=116,662,768 elapsed=508.6s

  [11223/13157] intraday_8067.csv.gz  in=369,227,408 out=116,675,995 elapsed=508.7s

  [11224/13157] intraday_8066.csv.gz  in=369,239,995 out=116,688,582 elapsed=508.7s

  [11225/13157] intraday_8068.csv.gz  in=369,253,180 out=116,701,767 elapsed=508.7s

  [11226/13157] intraday_8065.csv.gz  in=369,265,733 out=116,714,320 elapsed=508.7s

  [11227/13157] intraday_8069.csv.gz  in=369,279,334 out=116,727,921 elapsed=508.8s

  [11228/13157] intraday_8071.csv.gz  in=369,290,904 out=116,739,491 elapsed=508.8s

  [11229/13157] intraday_8072.csv.gz  in=369,301,416 out=116,750,003 elapsed=508.8s

  [11230/13157] intraday_8070.csv.gz  in=369,322,956 out=116,767,741 elapsed=508.8s

  [11231/13157] intraday_8075.csv.gz  in=369,335,669 out=116,780,454 elapsed=509.4s

  [11232/13157] intraday_8073.csv.gz  in=369,349,999 out=116,794,784 elapsed=509.4s

  [11233/13157] intraday_8076.csv.gz  in=369,360,585 out=116,805,370 elapsed=509.5s

  [11234/13157] intraday_8074.csv.gz  in=369,376,775 out=116,821,560 elapsed=509.5s

  [11235/13157] intraday_8077.csv.gz  in=369,389,786 out=116,834,571 elapsed=509.5s

  [11236/13157] intraday_8078.csv.gz  in=369,409,414 out=116,852,222 elapsed=509.5s

  [11237/13157] intraday_8080.csv.gz  in=369,422,046 out=116,864,854 elapsed=509.7s

  [11238/13157] intraday_8079.csv.gz  in=369,434,528 out=116,877,201 elapsed=509.7s

  [11239/13157] intraday_8081.csv.gz  in=369,446,891 out=116,889,564 elapsed=509.7s

  [11240/13157] intraday_8082.csv.gz  in=369,459,669 out=116,902,084 elapsed=509.7s

  [11241/13157] intraday_8083.csv.gz  in=369,470,942 out=116,913,357 elapsed=509.8s

  [11242/13157] intraday_8086.csv.gz  in=369,483,560 out=116,925,975 elapsed=509.8s

  [11243/13157] intraday_8085.csv.gz  in=369,495,631 out=116,938,046 elapsed=509.8s

  [11244/13157] intraday_8084.csv.gz  in=369,506,864 out=116,949,279 elapsed=509.8s

  [11245/13157] intraday_8088.csv.gz  in=369,520,508 out=116,962,923 elapsed=509.8s

  [11246/13157] intraday_8090.csv.gz  in=369,532,209 out=116,974,624 elapsed=509.8s

  [11247/13157] intraday_8087.csv.gz  in=369,543,617 out=116,986,032 elapsed=509.8s

  [11248/13157] intraday_8089.csv.gz  in=369,554,863 out=116,997,278 elapsed=509.8s

  [11249/13157] intraday_8091.csv.gz  in=369,568,235 out=117,010,650 elapsed=509.8s

  [11250/13157] intraday_8093.csv.gz  in=369,580,472 out=117,022,887 elapsed=509.9s

  [11251/13157] intraday_8095.csv.gz  in=369,591,242 out=117,033,657 elapsed=509.9s

  [11252/13157] intraday_8092.csv.gz  in=369,603,614 out=117,046,029 elapsed=509.9s

  [11253/13157] intraday_8094.csv.gz  in=369,615,423 out=117,057,838 elapsed=509.9s

  [11254/13157] intraday_8096.csv.gz  in=369,631,160 out=117,073,575 elapsed=509.9s

  [11255/13157] intraday_8099.csv.gz  in=369,643,310 out=117,085,725 elapsed=510.0s

  [11256/13157] intraday_8097.csv.gz  in=369,654,783 out=117,097,198 elapsed=510.0s

  [11257/13157] intraday_8098.csv.gz  in=369,669,724 out=117,112,139 elapsed=510.0s

  [11258/13157] intraday_8100.csv.gz  in=369,684,245 out=117,126,660 elapsed=510.1s

  [11259/13157] intraday_8101.csv.gz  in=369,694,809 out=117,137,224 elapsed=510.1s

  [11260/13157] intraday_8102.csv.gz  in=369,707,295 out=117,149,710 elapsed=510.1s

  [11261/13157] intraday_8103.csv.gz  in=369,719,566 out=117,161,981 elapsed=510.1s

  [11262/13157] intraday_8106.csv.gz  in=369,731,396 out=117,173,725 elapsed=510.8s

  [11263/13157] intraday_8104.csv.gz  in=369,743,186 out=117,185,515 elapsed=510.8s

  [11264/13157] intraday_8105.csv.gz  in=369,755,293 out=117,197,622 elapsed=510.8s

  [11265/13157] intraday_8107.csv.gz  in=369,771,746 out=117,211,529 elapsed=510.8s

  [11266/13157] intraday_8109.csv.gz  in=369,785,172 out=117,224,955 elapsed=510.9s

  [11267/13157] intraday_8108.csv.gz  in=369,795,993 out=117,235,776 elapsed=510.9s

  [11268/13157] intraday_8110.csv.gz  in=369,809,649 out=117,249,432 elapsed=510.9s

  [11269/13157] intraday_8111.csv.gz  in=369,823,122 out=117,262,905 elapsed=510.9s

  [11270/13157] intraday_8112.csv.gz  in=369,835,820 out=117,275,603 elapsed=510.9s

  [11271/13157] intraday_8113.csv.gz  in=369,847,676 out=117,287,163 elapsed=510.9s

  [11272/13157] intraday_8114.csv.gz  in=369,860,679 out=117,299,274 elapsed=511.0s

  [11273/13157] intraday_8117.csv.gz  in=369,873,825 out=117,312,420 elapsed=511.0s

  [11274/13157] intraday_8115.csv.gz  in=369,886,800 out=117,325,395 elapsed=511.0s

  [11275/13157] intraday_8118.csv.gz  in=369,898,194 out=117,336,789 elapsed=511.0s

  [11276/13157] intraday_8116.csv.gz  in=369,910,536 out=117,349,131 elapsed=511.0s

  [11277/13157] intraday_8120.csv.gz  in=369,920,851 out=117,359,446 elapsed=511.0s

  [11278/13157] intraday_8119.csv.gz  in=369,934,999 out=117,373,236 elapsed=511.1s

  [11279/13157] intraday_8121.csv.gz  in=369,947,930 out=117,386,167 elapsed=511.1s

  [11280/13157] intraday_8122.csv.gz  in=369,959,276 out=117,397,513 elapsed=511.1s

  [11281/13157] intraday_8125.csv.gz  in=369,969,873 out=117,407,773 elapsed=511.1s

  [11282/13157] intraday_8123.csv.gz  in=369,981,539 out=117,419,439 elapsed=511.1s

  [11283/13157] intraday_8124.csv.gz  in=369,991,839 out=117,429,739 elapsed=511.1s

  [11284/13157] intraday_8126.csv.gz  in=370,003,742 out=117,441,642 elapsed=511.2s

  [11285/13157] intraday_8127.csv.gz  in=370,017,970 out=117,455,870 elapsed=511.2s

  [11286/13157] intraday_8129.csv.gz  in=370,031,547 out=117,469,447 elapsed=511.2s

  [11287/13157] intraday_8130.csv.gz  in=370,043,409 out=117,480,685 elapsed=511.2s

  [11288/13157] intraday_8131.csv.gz  in=370,054,780 out=117,492,056 elapsed=511.2s

  [11289/13157] intraday_8128.csv.gz  in=370,072,572 out=117,509,848 elapsed=511.2s

  [11290/13157] intraday_8133.csv.gz  in=370,086,107 out=117,523,383 elapsed=511.2s

  [11291/13157] intraday_8132.csv.gz  in=370,099,373 out=117,536,649 elapsed=511.2s

  [11292/13157] intraday_8135.csv.gz  in=370,111,841 out=117,549,117 elapsed=511.3s

  [11293/13157] intraday_8134.csv.gz  in=370,128,363 out=117,563,377 elapsed=511.3s

  [11294/13157] intraday_8136.csv.gz  in=370,140,803 out=117,575,817 elapsed=511.3s

  [11295/13157] intraday_8138.csv.gz  in=370,154,934 out=117,589,948 elapsed=511.3s

  [11296/13157] intraday_8139.csv.gz  in=370,169,879 out=117,604,893 elapsed=511.3s

  [11297/13157] intraday_8137.csv.gz  in=370,182,162 out=117,617,176 elapsed=511.3s

  [11298/13157] intraday_8140.csv.gz  in=370,193,251 out=117,628,265 elapsed=511.4s

  [11299/13157] intraday_8144.csv.gz  in=370,205,799 out=117,640,813 elapsed=511.4s

  [11300/13157] intraday_8143.csv.gz  in=370,220,077 out=117,655,091 elapsed=511.4s

  [11301/13157] intraday_8142.csv.gz  in=370,231,757 out=117,666,771 elapsed=511.4s

  [11302/13157] intraday_8141.csv.gz  in=370,247,650 out=117,682,570 elapsed=511.4s

  [11303/13157] intraday_8148.csv.gz  in=370,259,723 out=117,694,643 elapsed=511.5s

  [11304/13157] intraday_8147.csv.gz  in=370,273,726 out=117,708,646 elapsed=511.5s

  [11305/13157] intraday_8146.csv.gz  in=370,286,754 out=117,721,674 elapsed=511.5s

  [11306/13157] intraday_8145.csv.gz  in=370,298,617 out=117,733,537 elapsed=511.5s

  [11307/13157] intraday_8149.csv.gz  in=370,311,185 out=117,746,105 elapsed=511.5s

  [11308/13157] intraday_8152.csv.gz  in=370,325,069 out=117,759,989 elapsed=511.6s

  [11309/13157] intraday_8151.csv.gz  in=370,339,701 out=117,774,621 elapsed=511.6s

  [11310/13157] intraday_8150.csv.gz  in=370,354,024 out=117,788,944 elapsed=511.6s

  [11311/13157] intraday_8153.csv.gz  in=370,367,856 out=117,802,694 elapsed=511.6s

  [11312/13157] intraday_8155.csv.gz  in=370,379,492 out=117,814,330 elapsed=511.8s

  [11313/13157] intraday_8156.csv.gz  in=370,392,869 out=117,827,707 elapsed=511.8s

  [11314/13157] intraday_8154.csv.gz  in=370,409,221 out=117,843,858 elapsed=511.8s

  [11315/13157] intraday_8158.csv.gz  in=370,421,232 out=117,855,869 elapsed=511.8s

  [11316/13157] intraday_8157.csv.gz  in=370,435,285 out=117,869,922 elapsed=511.8s

  [11317/13157] intraday_8159.csv.gz  in=370,448,963 out=117,883,600 elapsed=511.9s

  [11318/13157] intraday_8160.csv.gz  in=370,464,498 out=117,899,135 elapsed=511.9s

  [11319/13157] intraday_8163.csv.gz  in=370,477,424 out=117,912,061 elapsed=511.9s

  [11320/13157] intraday_8164.csv.gz  in=370,490,276 out=117,924,913 elapsed=511.9s

  [11321/13157] intraday_8162.csv.gz  in=370,505,413 out=117,940,050 elapsed=511.9s

  [11322/13157] intraday_8161.csv.gz  in=370,522,069 out=117,956,706 elapsed=511.9s

  [11323/13157] intraday_8165.csv.gz  in=370,537,542 out=117,970,271 elapsed=512.0s

  [11324/13157] intraday_8166.csv.gz  in=370,548,706 out=117,981,435 elapsed=512.0s

  [11325/13157] intraday_8167.csv.gz  in=370,563,269 out=117,995,998 elapsed=512.0s

  [11326/13157] intraday_8168.csv.gz  in=370,574,080 out=118,006,809 elapsed=512.0s

  [11327/13157] intraday_8170.csv.gz  in=370,587,849 out=118,020,578 elapsed=512.0s

  [11328/13157] intraday_8169.csv.gz  in=370,602,126 out=118,034,855 elapsed=512.0s

  [11329/13157] intraday_8171.csv.gz  in=370,617,444 out=118,050,173 elapsed=512.0s

  [11330/13157] intraday_8172.csv.gz  in=370,633,606 out=118,064,953 elapsed=512.1s

  [11331/13157] intraday_8173.csv.gz  in=370,645,927 out=118,077,274 elapsed=512.1s

  [11332/13157] intraday_8175.csv.gz  in=370,657,571 out=118,088,918 elapsed=512.1s

  [11333/13157] intraday_8174.csv.gz  in=370,671,513 out=118,102,860 elapsed=512.1s

  [11334/13157] intraday_8176.csv.gz  in=370,684,542 out=118,115,889 elapsed=512.2s

  [11335/13157] intraday_8177.csv.gz  in=370,698,451 out=118,129,798 elapsed=512.2s

  [11336/13157] intraday_8179.csv.gz  in=370,712,162 out=118,143,509 elapsed=512.2s

  [11337/13157] intraday_8178.csv.gz  in=370,727,032 out=118,158,379 elapsed=512.2s

  [11338/13157] intraday_8180.csv.gz  in=370,740,555 out=118,171,902 elapsed=512.2s

  [11339/13157] intraday_8184.csv.gz  in=370,752,058 out=118,183,405 elapsed=512.3s

  [11340/13157] intraday_8182.csv.gz  in=370,764,282 out=118,195,629 elapsed=512.3s

  [11341/13157] intraday_8181.csv.gz  in=370,776,871 out=118,208,218 elapsed=512.3s

  [11342/13157] intraday_8183.csv.gz  in=370,789,964 out=118,221,311 elapsed=512.3s

  [11343/13157] intraday_8186.csv.gz  in=370,797,408 out=118,228,755 elapsed=512.4s

  [11344/13157] intraday_8185.csv.gz  in=370,808,777 out=118,240,124 elapsed=512.4s

  [11345/13157] intraday_8187.csv.gz  in=370,821,060 out=118,252,407 elapsed=512.4s

  [11346/13157] intraday_8188.csv.gz  in=370,827,740 out=118,259,087 elapsed=512.4s

  [11347/13157] intraday_8189.csv.gz  in=370,827,779 out=118,259,126 elapsed=512.4s

  [11348/13157] intraday_8190.csv.gz  in=370,831,876 out=118,261,339 elapsed=512.4s

  [11349/13157] intraday_8192.csv.gz  in=370,832,891 out=118,262,354 elapsed=512.4s

  [11350/13157] intraday_8191.csv.gz  in=370,835,379 out=118,263,635 elapsed=512.4s

  [11351/13157] intraday_8193.csv.gz  in=370,836,316 out=118,264,153 elapsed=512.4s

  [11352/13157] intraday_8196.csv.gz  in=370,836,382 out=118,264,219 elapsed=512.4s

  [11353/13157] intraday_8195.csv.gz  in=370,836,467 out=118,264,304 elapsed=512.4s

  [11354/13157] intraday_8194.csv.gz  in=370,837,097 out=118,264,934 elapsed=512.4s

  [11355/13157] intraday_8197.csv.gz  in=370,839,905 out=118,266,920 elapsed=512.5s

  [11356/13157] intraday_8198.csv.gz  in=370,840,259 out=118,267,274 elapsed=512.5s

  [11357/13157] intraday_8200.csv.gz  in=370,840,419 out=118,267,434 elapsed=512.5s

  [11358/13157] intraday_8199.csv.gz  in=370,845,031 out=118,271,996 elapsed=512.5s

  [11359/13157] intraday_8201.csv.gz  in=370,849,799 out=118,274,618 elapsed=512.5s

  [11360/13157] intraday_8204.csv.gz  in=370,849,839 out=118,274,658 elapsed=512.5s

  [11361/13157] intraday_8206.csv.gz  in=370,849,840 out=118,274,659 elapsed=512.5s

  [11362/13157] intraday_8202.csv.gz  in=370,851,163 out=118,275,428 elapsed=512.5s

  [11363/13157] intraday_8203.csv.gz  in=370,851,413 out=118,275,678 elapsed=512.5s

  [11364/13157] intraday_8205.csv.gz  in=370,862,136 out=118,282,801 elapsed=512.5s

  [11365/13157] intraday_8208.csv.gz  in=370,870,588 out=118,287,499 elapsed=512.6s

  [11366/13157] intraday_8209.csv.gz  in=370,871,171 out=118,288,014 elapsed=512.6s

  [11367/13157] intraday_8207.csv.gz  in=370,875,954 out=118,292,573 elapsed=512.6s

  [11368/13157] intraday_8210.csv.gz  in=370,876,072 out=118,292,670 elapsed=512.7s

  [11369/13157] intraday_8213.csv.gz  in=370,876,295 out=118,292,893 elapsed=512.7s

  [11370/13157] intraday_8211.csv.gz  in=370,877,273 out=118,293,607 elapsed=512.7s

  [11371/13157] intraday_8216.csv.gz  in=370,878,093 out=118,294,427 elapsed=512.8s

  [11372/13157] intraday_8215.csv.gz  in=370,878,659 out=118,294,993 elapsed=512.8s

  [11373/13157] intraday_8214.csv.gz  in=370,880,274 out=118,296,608 elapsed=512.8s

  [11374/13157] intraday_8212.csv.gz  in=370,894,170 out=118,304,220 elapsed=512.8s

  [11375/13157] intraday_8217.csv.gz  in=370,894,739 out=118,304,789 elapsed=513.0s

  [11376/13157] intraday_8218.csv.gz  in=370,895,824 out=118,305,874 elapsed=513.0s

  [11377/13157] intraday_8220.csv.gz  in=370,897,082 out=118,307,132 elapsed=513.2s

  [11378/13157] intraday_8219.csv.gz  in=370,897,860 out=118,307,910 elapsed=513.2s

  [11379/13157] intraday_8222.csv.gz  in=370,898,541 out=118,308,591 elapsed=513.3s

  [11380/13157] intraday_8221.csv.gz  in=370,899,219 out=118,309,269 elapsed=513.3s

  [11381/13157] intraday_8224.csv.gz  in=370,900,580 out=118,310,630 elapsed=513.5s

  [11382/13157] intraday_8223.csv.gz  in=370,901,569 out=118,311,619 elapsed=513.5s

  [11383/13157] intraday_8225.csv.gz  in=370,902,409 out=118,312,459 elapsed=513.5s

  [11384/13157] intraday_8226.csv.gz  in=370,903,247 out=118,313,297 elapsed=513.5s

  [11385/13157] intraday_8228.csv.gz  in=370,903,508 out=118,313,558 elapsed=513.5s

  [11386/13157] intraday_8227.csv.gz  in=370,904,572 out=118,314,622 elapsed=513.5s

  [11387/13157] intraday_8229.csv.gz  in=370,904,912 out=118,314,962 elapsed=513.5s

  [11388/13157] intraday_8232.csv.gz  in=370,905,474 out=118,315,524 elapsed=513.6s

  [11389/13157] intraday_8231.csv.gz  in=370,906,287 out=118,316,337 elapsed=513.6s

  [11390/13157] intraday_8230.csv.gz  in=370,907,089 out=118,317,139 elapsed=513.6s

  [11391/13157] intraday_8233.csv.gz  in=370,907,474 out=118,317,524 elapsed=513.6s

  [11392/13157] intraday_8234.csv.gz  in=370,908,146 out=118,318,196 elapsed=513.6s

  [11393/13157] intraday_8235.csv.gz  in=370,908,789 out=118,318,839 elapsed=513.6s

  [11394/13157] intraday_8236.csv.gz  in=370,909,178 out=118,319,228 elapsed=513.6s

  [11395/13157] intraday_8237.csv.gz  in=370,910,076 out=118,320,126 elapsed=513.6s

  [11396/13157] intraday_8238.csv.gz  in=370,910,517 out=118,320,567 elapsed=513.6s

  [11397/13157] intraday_8240.csv.gz  in=370,911,092 out=118,321,142 elapsed=513.6s

  [11398/13157] intraday_8241.csv.gz  in=370,911,287 out=118,321,337 elapsed=513.6s

  [11399/13157] intraday_8239.csv.gz  in=370,912,255 out=118,322,305 elapsed=513.6s

  [11400/13157] intraday_8244.csv.gz  in=370,913,721 out=118,323,771 elapsed=513.7s

  [11401/13157] intraday_8242.csv.gz  in=370,914,704 out=118,324,754 elapsed=513.7s

  [11402/13157] intraday_8243.csv.gz  in=370,915,794 out=118,325,844 elapsed=513.7s

  [11403/13157] intraday_8245.csv.gz  in=370,916,757 out=118,326,807 elapsed=513.7s

  [11404/13157] intraday_8248.csv.gz  in=370,917,201 out=118,327,251 elapsed=513.7s

  [11405/13157] intraday_8249.csv.gz  in=370,917,934 out=118,327,984 elapsed=513.7s

  [11406/13157] intraday_8246.csv.gz  in=370,918,484 out=118,328,534 elapsed=513.7s

  [11407/13157] intraday_8250.csv.gz  in=370,918,888 out=118,328,938 elapsed=513.7s

  [11408/13157] intraday_8247.csv.gz  in=370,919,465 out=118,329,515 elapsed=513.7s

  [11409/13157] intraday_8251.csv.gz  in=370,920,126 out=118,330,176 elapsed=513.7s

  [11410/13157] intraday_8252.csv.gz  in=370,920,677 out=118,330,727 elapsed=513.7s

  [11411/13157] intraday_8253.csv.gz  in=370,921,008 out=118,331,058 elapsed=513.7s

  [11412/13157] intraday_8255.csv.gz  in=370,921,498 out=118,331,548 elapsed=513.7s

  [11413/13157] intraday_8254.csv.gz  in=370,921,835 out=118,331,885 elapsed=513.7s

  [11414/13157] intraday_8258.csv.gz  in=370,922,400 out=118,332,450 elapsed=513.7s

  [11415/13157] intraday_8256.csv.gz  in=370,922,778 out=118,332,828 elapsed=513.7s

  [11416/13157] intraday_8257.csv.gz  in=370,923,274 out=118,333,324 elapsed=513.7s

  [11417/13157] intraday_8259.csv.gz  in=370,923,884 out=118,333,934 elapsed=513.7s

  [11418/13157] intraday_8261.csv.gz  in=370,924,403 out=118,334,453 elapsed=513.8s

  [11419/13157] intraday_8260.csv.gz  in=370,924,621 out=118,334,671 elapsed=513.8s

  [11420/13157] intraday_8263.csv.gz  in=370,924,902 out=118,334,952 elapsed=513.8s

  [11421/13157] intraday_8262.csv.gz  in=370,925,531 out=118,335,581 elapsed=513.8s

  [11422/13157] intraday_8264.csv.gz  in=370,925,858 out=118,335,908 elapsed=513.8s

  [11423/13157] intraday_8267.csv.gz  in=370,927,024 out=118,337,074 elapsed=513.8s

  [11424/13157] intraday_8266.csv.gz  in=370,928,146 out=118,338,196 elapsed=513.8s

  [11425/13157] intraday_8265.csv.gz  in=370,928,669 out=118,338,719 elapsed=513.9s

  [11426/13157] intraday_8268.csv.gz  in=370,929,581 out=118,339,631 elapsed=513.9s

  [11427/13157] intraday_8269.csv.gz  in=370,930,154 out=118,340,204 elapsed=513.9s

  [11428/13157] intraday_8271.csv.gz  in=370,930,359 out=118,340,409 elapsed=513.9s

  [11429/13157] intraday_8270.csv.gz  in=370,930,574 out=118,340,624 elapsed=513.9s

  [11430/13157] intraday_8272.csv.gz  in=370,931,545 out=118,341,595 elapsed=513.9s

  [11431/13157] intraday_8273.csv.gz  in=370,932,400 out=118,342,450 elapsed=514.0s

  [11432/13157] intraday_8276.csv.gz  in=370,932,528 out=118,342,578 elapsed=514.0s

  [11433/13157] intraday_8274.csv.gz  in=370,932,795 out=118,342,845 elapsed=514.0s

  [11434/13157] intraday_8275.csv.gz  in=370,933,762 out=118,343,812 elapsed=514.0s

  [11435/13157] intraday_8277.csv.gz  in=370,933,959 out=118,344,009 elapsed=514.0s

  [11436/13157] intraday_8278.csv.gz  in=370,934,463 out=118,344,513 elapsed=514.1s

  [11437/13157] intraday_8281.csv.gz  in=370,934,810 out=118,344,860 elapsed=514.1s

  [11438/13157] intraday_8280.csv.gz  in=370,935,937 out=118,345,987 elapsed=514.1s

  [11439/13157] intraday_8282.csv.gz  in=370,936,592 out=118,346,642 elapsed=514.1s

  [11440/13157] intraday_8279.csv.gz  in=370,938,068 out=118,348,118 elapsed=514.1s

  [11441/13157] intraday_8283.csv.gz  in=370,938,594 out=118,348,644 elapsed=514.2s

  [11442/13157] intraday_8284.csv.gz  in=370,939,038 out=118,349,088 elapsed=514.2s

  [11443/13157] intraday_8285.csv.gz  in=370,940,089 out=118,350,139 elapsed=514.2s

  [11444/13157] intraday_8286.csv.gz  in=370,940,462 out=118,350,512 elapsed=514.2s

  [11445/13157] intraday_8287.csv.gz  in=370,941,071 out=118,351,121 elapsed=514.2s

  [11446/13157] intraday_8289.csv.gz  in=370,942,106 out=118,352,156 elapsed=514.2s

  [11447/13157] intraday_8290.csv.gz  in=370,942,621 out=118,352,671 elapsed=514.2s

  [11448/13157] intraday_8288.csv.gz  in=370,943,010 out=118,353,060 elapsed=514.2s

  [11449/13157] intraday_8291.csv.gz  in=370,943,763 out=118,353,813 elapsed=514.2s

  [11450/13157] intraday_8292.csv.gz  in=370,944,418 out=118,354,468 elapsed=514.2s

  [11451/13157] intraday_8296.csv.gz  in=370,945,063 out=118,355,113 elapsed=514.2s

  [11452/13157] intraday_8295.csv.gz  in=370,945,426 out=118,355,476 elapsed=514.2s

  [11453/13157] intraday_8293.csv.gz  in=370,946,127 out=118,356,177 elapsed=514.3s

  [11454/13157] intraday_8294.csv.gz  in=370,946,225 out=118,356,275 elapsed=514.3s

  [11455/13157] intraday_8297.csv.gz  in=370,948,555 out=118,358,605 elapsed=514.3s

  [11456/13157] intraday_8299.csv.gz  in=370,949,695 out=118,359,745 elapsed=514.3s

  [11457/13157] intraday_8300.csv.gz  in=370,950,661 out=118,360,711 elapsed=514.3s

  [11458/13157] intraday_8301.csv.gz  in=370,951,136 out=118,361,186 elapsed=514.3s

  [11459/13157] intraday_8298.csv.gz  in=370,952,602 out=118,362,652 elapsed=514.3s

  [11460/13157] intraday_8302.csv.gz  in=370,953,518 out=118,363,568 elapsed=514.3s

  [11461/13157] intraday_8303.csv.gz  in=370,954,628 out=118,364,678 elapsed=514.3s

  [11462/13157] intraday_8304.csv.gz  in=370,955,960 out=118,366,010 elapsed=514.3s

  [11463/13157] intraday_8305.csv.gz  in=370,956,233 out=118,366,283 elapsed=514.3s

  [11464/13157] intraday_8306.csv.gz  in=370,957,057 out=118,367,107 elapsed=514.3s

  [11465/13157] intraday_8307.csv.gz  in=370,958,268 out=118,368,318 elapsed=514.3s

  [11466/13157] intraday_8309.csv.gz  in=370,959,031 out=118,369,081 elapsed=514.4s

  [11467/13157] intraday_8308.csv.gz  in=370,959,612 out=118,369,662 elapsed=514.4s

  [11468/13157] intraday_8310.csv.gz  in=370,960,098 out=118,370,148 elapsed=514.4s

  [11469/13157] intraday_8311.csv.gz  in=370,960,436 out=118,370,486 elapsed=514.4s

  [11470/13157] intraday_8313.csv.gz  in=370,961,418 out=118,371,468 elapsed=514.4s

  [11471/13157] intraday_8312.csv.gz  in=370,965,683 out=118,375,680 elapsed=514.4s

  [11472/13157] intraday_8315.csv.gz  in=370,966,414 out=118,376,411 elapsed=514.4s

  [11473/13157] intraday_8314.csv.gz  in=370,966,599 out=118,376,596 elapsed=514.4s

  [11474/13157] intraday_8317.csv.gz  in=370,968,330 out=118,378,327 elapsed=514.4s

  [11475/13157] intraday_8316.csv.gz  in=370,969,896 out=118,379,893 elapsed=514.4s

  [11476/13157] intraday_8318.csv.gz  in=370,970,742 out=118,380,739 elapsed=514.4s

  [11477/13157] intraday_8319.csv.gz  in=370,971,082 out=118,381,079 elapsed=514.4s

  [11478/13157] intraday_8320.csv.gz  in=370,972,920 out=118,382,917 elapsed=514.4s

  [11479/13157] intraday_8321.csv.gz  in=370,973,417 out=118,383,414 elapsed=514.4s

  [11480/13157] intraday_8322.csv.gz  in=370,973,932 out=118,383,929 elapsed=514.4s

  [11481/13157] intraday_8323.csv.gz  in=370,974,928 out=118,384,925 elapsed=514.4s

  [11482/13157] intraday_8324.csv.gz  in=370,975,532 out=118,385,529 elapsed=514.4s

  [11483/13157] intraday_8325.csv.gz  in=370,976,318 out=118,386,315 elapsed=514.4s

  [11484/13157] intraday_8327.csv.gz  in=370,977,067 out=118,387,064 elapsed=514.4s

  [11485/13157] intraday_8326.csv.gz  in=370,977,864 out=118,387,861 elapsed=514.4s

  [11486/13157] intraday_8328.csv.gz  in=370,978,966 out=118,388,963 elapsed=514.5s

  [11487/13157] intraday_8329.csv.gz  in=370,981,151 out=118,391,148 elapsed=514.6s

  [11488/13157] intraday_8330.csv.gz  in=370,982,611 out=118,392,608 elapsed=514.6s

  [11489/13157] intraday_8331.csv.gz  in=370,983,314 out=118,393,311 elapsed=514.6s

  [11490/13157] intraday_8332.csv.gz  in=370,984,696 out=118,394,693 elapsed=514.6s

  [11491/13157] intraday_8333.csv.gz  in=370,985,568 out=118,395,565 elapsed=514.6s

  [11492/13157] intraday_8335.csv.gz  in=370,985,795 out=118,395,792 elapsed=514.6s

  [11493/13157] intraday_8334.csv.gz  in=370,986,247 out=118,396,244 elapsed=514.6s

  [11494/13157] intraday_8336.csv.gz  in=370,986,770 out=118,396,767 elapsed=514.6s

  [11495/13157] intraday_8337.csv.gz  in=370,987,210 out=118,397,207 elapsed=514.7s

  [11496/13157] intraday_8338.csv.gz  in=370,987,829 out=118,397,826 elapsed=514.7s

  [11497/13157] intraday_8339.csv.gz  in=370,988,589 out=118,398,586 elapsed=514.7s

  [11498/13157] intraday_8340.csv.gz  in=370,989,570 out=118,399,567 elapsed=514.7s

  [11499/13157] intraday_8341.csv.gz  in=370,990,681 out=118,400,678 elapsed=514.8s

  [11500/13157] intraday_8342.csv.gz  in=370,991,321 out=118,401,318 elapsed=514.8s

  [11501/13157] intraday_8343.csv.gz  in=370,992,323 out=118,402,320 elapsed=514.8s

  [11502/13157] intraday_8344.csv.gz  in=370,993,242 out=118,403,239 elapsed=514.8s

  [11503/13157] intraday_8345.csv.gz  in=370,994,107 out=118,404,104 elapsed=514.8s

  [11504/13157] intraday_8347.csv.gz  in=370,994,607 out=118,404,604 elapsed=514.8s

  [11505/13157] intraday_8346.csv.gz  in=370,995,067 out=118,405,064 elapsed=514.8s

  [11506/13157] intraday_8348.csv.gz  in=370,995,485 out=118,405,482 elapsed=514.8s

  [11507/13157] intraday_8350.csv.gz  in=370,996,119 out=118,406,116 elapsed=514.8s

  [11508/13157] intraday_8349.csv.gz  in=370,997,363 out=118,407,360 elapsed=514.8s

  [11509/13157] intraday_8351.csv.gz  in=370,997,727 out=118,407,724 elapsed=514.9s

  [11510/13157] intraday_8352.csv.gz  in=370,998,528 out=118,408,525 elapsed=515.0s

  [11511/13157] intraday_8353.csv.gz  in=370,998,881 out=118,408,878 elapsed=515.0s

  [11512/13157] intraday_8354.csv.gz  in=371,000,126 out=118,410,123 elapsed=515.0s

  [11513/13157] intraday_8355.csv.gz  in=371,000,524 out=118,410,521 elapsed=515.0s

  [11514/13157] intraday_8356.csv.gz  in=371,000,906 out=118,410,903 elapsed=515.0s

  [11515/13157] intraday_8357.csv.gz  in=371,001,908 out=118,411,905 elapsed=515.0s

  [11516/13157] intraday_8358.csv.gz  in=371,001,917 out=118,411,914 elapsed=515.0s

  [11517/13157] intraday_8359.csv.gz  in=371,017,416 out=118,427,413 elapsed=515.0s

  [11518/13157] intraday_8360.csv.gz  in=371,029,904 out=118,439,901 elapsed=515.2s

  [11519/13157] intraday_8362.csv.gz  in=371,042,367 out=118,452,364 elapsed=515.2s

  [11520/13157] intraday_8363.csv.gz  in=371,055,494 out=118,465,491 elapsed=515.2s

  [11521/13157] intraday_8361.csv.gz  in=371,069,384 out=118,479,381 elapsed=515.2s

  [11522/13157] intraday_8365.csv.gz  in=371,084,778 out=118,494,775 elapsed=515.2s

  [11523/13157] intraday_8364.csv.gz  in=371,099,333 out=118,509,330 elapsed=515.2s

  [11524/13157] intraday_8366.csv.gz  in=371,111,762 out=118,521,759 elapsed=515.4s

  [11525/13157] intraday_8369.csv.gz  in=371,126,747 out=118,536,744 elapsed=515.4s

  [11526/13157] intraday_8368.csv.gz  in=371,142,339 out=118,552,336 elapsed=515.4s

  [11527/13157] intraday_8367.csv.gz  in=371,155,560 out=118,565,557 elapsed=515.4s

  [11528/13157] intraday_8370.csv.gz  in=371,169,190 out=118,579,187 elapsed=515.5s

  [11529/13157] intraday_8373.csv.gz  in=371,178,898 out=118,588,895 elapsed=515.5s

  [11530/13157] intraday_8371.csv.gz  in=371,193,471 out=118,603,468 elapsed=515.5s

  [11531/13157] intraday_8372.csv.gz  in=371,206,617 out=118,616,614 elapsed=515.5s

  [11532/13157] intraday_8374.csv.gz  in=371,217,302 out=118,627,299 elapsed=515.6s

  [11533/13157] intraday_8376.csv.gz  in=371,230,922 out=118,640,919 elapsed=515.6s

  [11534/13157] intraday_8375.csv.gz  in=371,244,721 out=118,654,718 elapsed=515.6s

  [11535/13157] intraday_8377.csv.gz  in=371,256,175 out=118,666,172 elapsed=515.6s

  [11536/13157] intraday_8378.csv.gz  in=371,268,217 out=118,678,214 elapsed=515.7s

  [11537/13157] intraday_8380.csv.gz  in=371,281,361 out=118,691,358 elapsed=515.7s

  [11538/13157] intraday_8379.csv.gz  in=371,293,941 out=118,703,938 elapsed=515.7s

  [11539/13157] intraday_8381.csv.gz  in=371,306,695 out=118,716,692 elapsed=515.7s

  [11540/13157] intraday_8382.csv.gz  in=371,321,146 out=118,731,143 elapsed=515.8s

  [11541/13157] intraday_8385.csv.gz  in=371,333,312 out=118,743,309 elapsed=515.8s

  [11542/13157] intraday_8384.csv.gz  in=371,346,497 out=118,756,494 elapsed=515.9s

  [11543/13157] intraday_8383.csv.gz  in=371,360,355 out=118,770,352 elapsed=515.9s

  [11544/13157] intraday_8386.csv.gz  in=371,373,283 out=118,783,280 elapsed=515.9s

  [11545/13157] intraday_8387.csv.gz  in=371,385,279 out=118,795,276 elapsed=515.9s

  [11546/13157] intraday_8389.csv.gz  in=371,402,136 out=118,812,133 elapsed=515.9s

  [11547/13157] intraday_8388.csv.gz  in=371,417,152 out=118,827,149 elapsed=515.9s

  [11548/13157] intraday_8390.csv.gz  in=371,430,451 out=118,840,448 elapsed=516.0s

  [11549/13157] intraday_8392.csv.gz  in=371,442,973 out=118,852,970 elapsed=516.0s

  [11550/13157] intraday_8391.csv.gz  in=371,454,777 out=118,864,774 elapsed=516.0s

  [11551/13157] intraday_8393.csv.gz  in=371,469,167 out=118,879,164 elapsed=516.0s

  [11552/13157] intraday_8394.csv.gz  in=371,481,536 out=118,891,533 elapsed=516.0s

  [11553/13157] intraday_8395.csv.gz  in=371,493,983 out=118,903,980 elapsed=516.1s

  [11554/13157] intraday_8397.csv.gz  in=371,507,441 out=118,917,438 elapsed=516.1s

  [11555/13157] intraday_8396.csv.gz  in=371,519,046 out=118,929,043 elapsed=516.1s

  [11556/13157] intraday_8398.csv.gz  in=371,529,489 out=118,939,486 elapsed=516.1s

  [11557/13157] intraday_8399.csv.gz  in=371,541,811 out=118,951,808 elapsed=516.1s

  [11558/13157] intraday_8400.csv.gz  in=371,554,394 out=118,964,391 elapsed=516.1s

  [11559/13157] intraday_8401.csv.gz  in=371,568,307 out=118,978,304 elapsed=516.1s

  [11560/13157] intraday_8402.csv.gz  in=371,580,933 out=118,990,930 elapsed=516.1s

  [11561/13157] intraday_8403.csv.gz  in=371,594,978 out=119,004,975 elapsed=516.2s

  [11562/13157] intraday_8406.csv.gz  in=371,608,792 out=119,018,789 elapsed=516.2s

  [11563/13157] intraday_8405.csv.gz  in=371,620,628 out=119,030,625 elapsed=516.2s

  [11564/13157] intraday_8404.csv.gz  in=371,631,942 out=119,041,939 elapsed=516.2s

  [11565/13157] intraday_8407.csv.gz  in=371,643,584 out=119,053,581 elapsed=516.2s

  [11566/13157] intraday_8408.csv.gz  in=371,656,550 out=119,066,547 elapsed=516.3s

  [11567/13157] intraday_8410.csv.gz  in=371,668,772 out=119,078,769 elapsed=516.3s

  [11568/13157] intraday_8409.csv.gz  in=371,680,645 out=119,090,642 elapsed=516.3s

  [11569/13157] intraday_8411.csv.gz  in=371,695,610 out=119,105,607 elapsed=516.3s

  [11570/13157] intraday_8412.csv.gz  in=371,708,329 out=119,118,326 elapsed=516.3s

  [11571/13157] intraday_8414.csv.gz  in=371,722,027 out=119,132,024 elapsed=516.3s

  [11572/13157] intraday_8413.csv.gz  in=371,736,660 out=119,146,657 elapsed=516.3s

  [11573/13157] intraday_8416.csv.gz  in=371,747,323 out=119,157,320 elapsed=516.4s

  [11574/13157] intraday_8415.csv.gz  in=371,759,095 out=119,169,092 elapsed=516.4s

  [11575/13157] intraday_8417.csv.gz  in=371,774,211 out=119,184,208 elapsed=516.4s

  [11576/13157] intraday_8418.csv.gz  in=371,787,943 out=119,197,940 elapsed=516.4s

  [11577/13157] intraday_8420.csv.gz  in=371,802,174 out=119,212,171 elapsed=516.5s

  [11578/13157] intraday_8419.csv.gz  in=371,813,998 out=119,223,995 elapsed=516.5s

  [11579/13157] intraday_8422.csv.gz  in=371,825,042 out=119,235,039 elapsed=516.5s

  [11580/13157] intraday_8421.csv.gz  in=371,836,455 out=119,246,452 elapsed=516.5s

  [11581/13157] intraday_8423.csv.gz  in=371,847,598 out=119,257,595 elapsed=516.5s

  [11582/13157] intraday_8424.csv.gz  in=371,862,017 out=119,272,014 elapsed=516.5s

  [11583/13157] intraday_8425.csv.gz  in=371,874,767 out=119,284,764 elapsed=516.5s

  [11584/13157] intraday_8426.csv.gz  in=371,889,855 out=119,299,852 elapsed=516.5s

  [11585/13157] intraday_8429.csv.gz  in=371,901,328 out=119,311,325 elapsed=516.6s

  [11586/13157] intraday_8430.csv.gz  in=371,914,425 out=119,324,422 elapsed=516.6s

  [11587/13157] intraday_8427.csv.gz  in=371,927,183 out=119,337,180 elapsed=516.6s

  [11588/13157] intraday_8428.csv.gz  in=371,938,635 out=119,348,632 elapsed=516.6s

  [11589/13157] intraday_8431.csv.gz  in=371,951,359 out=119,361,356 elapsed=516.6s

  [11590/13157] intraday_8433.csv.gz  in=371,963,135 out=119,373,132 elapsed=516.7s

  [11591/13157] intraday_8432.csv.gz  in=371,977,472 out=119,387,469 elapsed=516.7s

  [11592/13157] intraday_8434.csv.gz  in=371,987,836 out=119,397,833 elapsed=516.7s

  [11593/13157] intraday_8435.csv.gz  in=371,998,902 out=119,408,899 elapsed=516.7s

  [11594/13157] intraday_8436.csv.gz  in=372,012,790 out=119,422,787 elapsed=516.8s

  [11595/13157] intraday_8439.csv.gz  in=372,022,994 out=119,432,991 elapsed=516.8s

  [11596/13157] intraday_8437.csv.gz  in=372,033,857 out=119,443,854 elapsed=516.8s

  [11597/13157] intraday_8440.csv.gz  in=372,045,216 out=119,455,213 elapsed=516.8s

  [11598/13157] intraday_8438.csv.gz  in=372,057,892 out=119,467,889 elapsed=516.8s

  [11599/13157] intraday_8441.csv.gz  in=372,070,368 out=119,480,365 elapsed=517.0s

  [11600/13157] intraday_8444.csv.gz  in=372,083,960 out=119,493,957 elapsed=517.0s

  [11601/13157] intraday_8443.csv.gz  in=372,100,987 out=119,510,984 elapsed=517.0s

  [11602/13157] intraday_8442.csv.gz  in=372,116,802 out=119,526,799 elapsed=517.0s

  [11603/13157] intraday_8445.csv.gz  in=372,128,601 out=119,538,598 elapsed=517.3s

  [11604/13157] intraday_8446.csv.gz  in=372,140,416 out=119,550,413 elapsed=517.3s

  [11605/13157] intraday_8448.csv.gz  in=372,154,430 out=119,564,427 elapsed=517.4s

  [11606/13157] intraday_8447.csv.gz  in=372,168,985 out=119,578,982 elapsed=517.4s

  [11607/13157] intraday_8450.csv.gz  in=372,180,681 out=119,590,678 elapsed=517.4s

  [11608/13157] intraday_8452.csv.gz  in=372,194,957 out=119,604,954 elapsed=517.4s

  [11609/13157] intraday_8449.csv.gz  in=372,209,739 out=119,619,736 elapsed=517.4s

  [11610/13157] intraday_8451.csv.gz  in=372,224,114 out=119,634,111 elapsed=517.4s

  [11611/13157] intraday_8453.csv.gz  in=372,237,585 out=119,647,582 elapsed=517.4s

  [11612/13157] intraday_8454.csv.gz  in=372,251,838 out=119,661,835 elapsed=517.5s

  [11613/13157] intraday_8455.csv.gz  in=372,264,184 out=119,674,181 elapsed=517.5s

  [11614/13157] intraday_8458.csv.gz  in=372,278,443 out=119,688,440 elapsed=517.5s

  [11615/13157] intraday_8456.csv.gz  in=372,290,413 out=119,700,410 elapsed=517.5s

  [11616/13157] intraday_8457.csv.gz  in=372,303,265 out=119,713,262 elapsed=517.5s

  [11617/13157] intraday_8460.csv.gz  in=372,316,686 out=119,726,683 elapsed=517.6s

  [11618/13157] intraday_8462.csv.gz  in=372,330,506 out=119,740,503 elapsed=517.6s

  [11619/13157] intraday_8459.csv.gz  in=372,343,450 out=119,753,447 elapsed=517.6s

  [11620/13157] intraday_8461.csv.gz  in=372,358,606 out=119,768,603 elapsed=517.6s

  [11621/13157] intraday_8466.csv.gz  in=372,371,436 out=119,781,433 elapsed=517.7s

  [11622/13157] intraday_8464.csv.gz  in=372,383,708 out=119,793,705 elapsed=517.7s

  [11623/13157] intraday_8463.csv.gz  in=372,396,385 out=119,806,382 elapsed=517.7s

  [11624/13157] intraday_8465.csv.gz  in=372,415,429 out=119,825,426 elapsed=517.7s

  [11625/13157] intraday_8469.csv.gz  in=372,429,243 out=119,839,240 elapsed=517.7s

  [11626/13157] intraday_8470.csv.gz  in=372,441,244 out=119,851,241 elapsed=517.7s

  [11627/13157] intraday_8468.csv.gz  in=372,457,982 out=119,867,979 elapsed=517.7s

  [11628/13157] intraday_8467.csv.gz  in=372,471,499 out=119,881,496 elapsed=517.7s

  [11629/13157] intraday_8472.csv.gz  in=372,484,479 out=119,894,476 elapsed=517.8s

  [11630/13157] intraday_8471.csv.gz  in=372,498,795 out=119,908,792 elapsed=517.8s

  [11631/13157] intraday_8473.csv.gz  in=372,512,228 out=119,922,225 elapsed=517.8s

  [11632/13157] intraday_8474.csv.gz  in=372,531,620 out=119,941,617 elapsed=517.8s

  [11633/13157] intraday_8476.csv.gz  in=372,545,394 out=119,955,391 elapsed=517.9s

  [11634/13157] intraday_8477.csv.gz  in=372,561,821 out=119,971,818 elapsed=517.9s

  [11635/13157] intraday_8478.csv.gz  in=372,575,132 out=119,985,129 elapsed=517.9s

  [11636/13157] intraday_8475.csv.gz  in=372,589,046 out=119,999,043 elapsed=517.9s

  [11637/13157] intraday_8479.csv.gz  in=372,600,889 out=120,010,886 elapsed=517.9s

  [11638/13157] intraday_8481.csv.gz  in=372,614,073 out=120,024,070 elapsed=517.9s

  [11639/13157] intraday_8480.csv.gz  in=372,626,186 out=120,036,183 elapsed=517.9s

  [11640/13157] intraday_8482.csv.gz  in=372,637,527 out=120,047,524 elapsed=517.9s

  [11641/13157] intraday_8483.csv.gz  in=372,650,107 out=120,060,104 elapsed=517.9s

  [11642/13157] intraday_8484.csv.gz  in=372,664,096 out=120,074,093 elapsed=518.0s

  [11643/13157] intraday_8486.csv.gz  in=372,675,747 out=120,085,744 elapsed=518.0s

  [11644/13157] intraday_8487.csv.gz  in=372,689,357 out=120,099,354 elapsed=518.0s

  [11645/13157] intraday_8485.csv.gz  in=372,705,484 out=120,115,481 elapsed=518.0s

  [11646/13157] intraday_8488.csv.gz  in=372,716,646 out=120,126,643 elapsed=518.0s

  [11647/13157] intraday_8490.csv.gz  in=372,727,980 out=120,137,977 elapsed=518.0s

  [11648/13157] intraday_8492.csv.gz  in=372,742,634 out=120,152,631 elapsed=518.1s

  [11649/13157] intraday_8489.csv.gz  in=372,757,900 out=120,167,897 elapsed=518.1s

  [11650/13157] intraday_8491.csv.gz  in=372,771,475 out=120,181,472 elapsed=518.1s

  [11651/13157] intraday_8493.csv.gz  in=372,786,021 out=120,196,018 elapsed=518.1s

  [11652/13157] intraday_8496.csv.gz  in=372,798,017 out=120,208,014 elapsed=518.1s

  [11653/13157] intraday_8495.csv.gz  in=372,812,152 out=120,222,149 elapsed=518.1s

  [11654/13157] intraday_8494.csv.gz  in=372,826,529 out=120,236,526 elapsed=518.1s

  [11655/13157] intraday_8497.csv.gz  in=372,840,776 out=120,250,773 elapsed=518.1s

  [11656/13157] intraday_8498.csv.gz  in=372,852,336 out=120,262,333 elapsed=518.2s

  [11657/13157] intraday_8501.csv.gz  in=372,861,014 out=120,271,011 elapsed=518.2s

  [11658/13157] intraday_8500.csv.gz  in=372,871,434 out=120,281,431 elapsed=518.2s

  [11659/13157] intraday_8499.csv.gz  in=372,886,124 out=120,296,121 elapsed=518.2s

  [11660/13157] intraday_8503.csv.gz  in=372,887,315 out=120,297,312 elapsed=518.2s

  [11661/13157] intraday_8502.csv.gz  in=372,901,196 out=120,311,193 elapsed=518.2s

  [11662/13157] intraday_8505.csv.gz  in=372,915,359 out=120,322,760 elapsed=518.2s

  [11663/13157] intraday_8506.csv.gz  in=372,930,230 out=120,337,631 elapsed=518.2s

  [11664/13157] intraday_8504.csv.gz  in=372,976,951 out=120,368,679 elapsed=518.3s

  [11665/13157] intraday_8507.csv.gz  in=372,988,927 out=120,380,655 elapsed=518.3s

  [11666/13157] intraday_8508.csv.gz  in=373,001,856 out=120,393,584 elapsed=518.3s

  [11667/13157] intraday_8509.csv.gz  in=373,012,825 out=120,404,553 elapsed=518.3s

  [11668/13157] intraday_8510.csv.gz  in=373,025,829 out=120,417,557 elapsed=518.3s

  [11669/13157] intraday_8511.csv.gz  in=373,040,592 out=120,432,320 elapsed=518.3s

  [11670/13157] intraday_8513.csv.gz  in=373,053,321 out=120,445,049 elapsed=518.5s

  [11671/13157] intraday_8514.csv.gz  in=373,064,999 out=120,456,727 elapsed=518.5s

  [11672/13157] intraday_8515.csv.gz  in=373,079,467 out=120,471,195 elapsed=518.5s

  [11673/13157] intraday_8512.csv.gz  in=373,092,908 out=120,484,636 elapsed=518.5s

  [11674/13157] intraday_8516.csv.gz  in=373,105,824 out=120,497,552 elapsed=518.6s

  [11675/13157] intraday_8519.csv.gz  in=373,118,568 out=120,510,296 elapsed=518.6s

  [11676/13157] intraday_8517.csv.gz  in=373,131,779 out=120,523,507 elapsed=518.6s

  [11677/13157] intraday_8518.csv.gz  in=373,144,689 out=120,536,417 elapsed=518.6s

  [11678/13157] intraday_8520.csv.gz  in=373,154,178 out=120,545,906 elapsed=518.7s

  [11679/13157] intraday_8521.csv.gz  in=373,164,477 out=120,556,205 elapsed=518.7s

  [11680/13157] intraday_8523.csv.gz  in=373,176,746 out=120,568,474 elapsed=518.7s

  [11681/13157] intraday_8522.csv.gz  in=373,190,670 out=120,582,398 elapsed=518.7s

  [11682/13157] intraday_8525.csv.gz  in=373,201,337 out=120,593,065 elapsed=518.9s

  [11683/13157] intraday_8524.csv.gz  in=373,211,840 out=120,603,568 elapsed=518.9s

  [11684/13157] intraday_8527.csv.gz  in=373,224,494 out=120,616,222 elapsed=518.9s

  [11685/13157] intraday_8526.csv.gz  in=373,236,666 out=120,628,394 elapsed=518.9s

  [11686/13157] intraday_8529.csv.gz  in=373,250,097 out=120,641,825 elapsed=519.1s

  [11687/13157] intraday_8528.csv.gz  in=373,261,924 out=120,653,652 elapsed=519.1s

  [11688/13157] intraday_8530.csv.gz  in=373,274,936 out=120,666,664 elapsed=519.1s

  [11689/13157] intraday_8531.csv.gz  in=373,288,377 out=120,680,026 elapsed=519.1s

  [11690/13157] intraday_8532.csv.gz  in=373,299,696 out=120,691,345 elapsed=519.2s

  [11691/13157] intraday_8533.csv.gz  in=373,311,378 out=120,703,027 elapsed=519.2s

  [11692/13157] intraday_8534.csv.gz  in=373,323,344 out=120,714,993 elapsed=519.2s

  [11693/13157] intraday_8535.csv.gz  in=373,336,755 out=120,728,404 elapsed=519.2s

  [11694/13157] intraday_8536.csv.gz  in=373,352,306 out=120,743,955 elapsed=519.2s

  [11695/13157] intraday_8538.csv.gz  in=373,362,934 out=120,754,583 elapsed=519.3s

  [11696/13157] intraday_8537.csv.gz  in=373,377,006 out=120,768,655 elapsed=519.3s

  [11697/13157] intraday_8539.csv.gz  in=373,389,227 out=120,780,876 elapsed=519.3s

  [11698/13157] intraday_8540.csv.gz  in=373,401,860 out=120,793,509 elapsed=519.3s

  [11699/13157] intraday_8542.csv.gz  in=373,413,283 out=120,804,932 elapsed=519.4s

  [11700/13157] intraday_8543.csv.gz  in=373,423,533 out=120,815,182 elapsed=519.4s

  [11701/13157] intraday_8541.csv.gz  in=373,435,048 out=120,826,697 elapsed=519.4s

  [11702/13157] intraday_8544.csv.gz  in=373,447,534 out=120,839,183 elapsed=519.4s

  [11703/13157] intraday_8545.csv.gz  in=373,457,462 out=120,849,111 elapsed=519.4s

  [11704/13157] intraday_8546.csv.gz  in=373,468,750 out=120,860,399 elapsed=519.4s

  [11705/13157] intraday_8547.csv.gz  in=373,480,633 out=120,872,282 elapsed=519.5s

  [11706/13157] intraday_8548.csv.gz  in=373,493,575 out=120,885,224 elapsed=519.5s

  [11707/13157] intraday_8549.csv.gz  in=373,505,168 out=120,896,817 elapsed=519.5s

  [11708/13157] intraday_8550.csv.gz  in=373,518,352 out=120,910,001 elapsed=519.5s

  [11709/13157] intraday_8551.csv.gz  in=373,528,763 out=120,920,412 elapsed=519.6s

  [11710/13157] intraday_8554.csv.gz  in=373,540,493 out=120,932,142 elapsed=519.6s

  [11711/13157] intraday_8553.csv.gz  in=373,553,183 out=120,944,832 elapsed=519.6s

  [11712/13157] intraday_8552.csv.gz  in=373,564,373 out=120,956,022 elapsed=519.6s

  [11713/13157] intraday_8556.csv.gz  in=373,576,174 out=120,967,823 elapsed=519.9s

  [11714/13157] intraday_8555.csv.gz  in=373,587,489 out=120,979,138 elapsed=519.9s

  [11715/13157] intraday_8557.csv.gz  in=373,598,565 out=120,990,214 elapsed=519.9s

  [11716/13157] intraday_8558.csv.gz  in=373,612,312 out=121,003,961 elapsed=519.9s

  [11717/13157] intraday_8560.csv.gz  in=373,625,373 out=121,017,022 elapsed=520.1s

  [11718/13157] intraday_8562.csv.gz  in=373,637,119 out=121,028,768 elapsed=520.1s

  [11719/13157] intraday_8559.csv.gz  in=373,647,066 out=121,038,715 elapsed=520.1s

  [11720/13157] intraday_8561.csv.gz  in=373,660,288 out=121,051,937 elapsed=520.1s

  [11721/13157] intraday_8564.csv.gz  in=373,673,723 out=121,065,372 elapsed=520.2s

  [11722/13157] intraday_8566.csv.gz  in=373,686,354 out=121,078,003 elapsed=520.2s

  [11723/13157] intraday_8563.csv.gz  in=373,697,011 out=121,088,660 elapsed=520.2s

  [11724/13157] intraday_8565.csv.gz  in=373,708,879 out=121,100,528 elapsed=520.2s

  [11725/13157] intraday_8567.csv.gz  in=373,720,278 out=121,111,927 elapsed=520.3s

  [11726/13157] intraday_8570.csv.gz  in=373,731,595 out=121,123,244 elapsed=520.3s

  [11727/13157] intraday_8569.csv.gz  in=373,742,567 out=121,134,216 elapsed=520.3s

  [11728/13157] intraday_8568.csv.gz  in=373,753,955 out=121,145,604 elapsed=520.3s

  [11729/13157] intraday_8571.csv.gz  in=373,766,693 out=121,158,342 elapsed=520.3s

  [11730/13157] intraday_8572.csv.gz  in=373,779,232 out=121,170,881 elapsed=520.4s

  [11731/13157] intraday_8574.csv.gz  in=373,790,788 out=121,182,437 elapsed=520.4s

  [11732/13157] intraday_8575.csv.gz  in=373,802,360 out=121,194,009 elapsed=520.4s

  [11733/13157] intraday_8573.csv.gz  in=373,817,405 out=121,209,054 elapsed=520.4s

  [11734/13157] intraday_8576.csv.gz  in=373,827,184 out=121,218,833 elapsed=520.4s

  [11735/13157] intraday_8578.csv.gz  in=373,838,882 out=121,230,531 elapsed=520.5s

  [11736/13157] intraday_8577.csv.gz  in=373,851,520 out=121,243,169 elapsed=520.5s

  [11737/13157] intraday_8579.csv.gz  in=373,865,104 out=121,256,753 elapsed=520.5s

  [11738/13157] intraday_8580.csv.gz  in=373,875,525 out=121,267,174 elapsed=520.6s

  [11739/13157] intraday_8582.csv.gz  in=373,886,941 out=121,278,590 elapsed=520.6s

  [11740/13157] intraday_8581.csv.gz  in=373,898,324 out=121,289,973 elapsed=520.6s

  [11741/13157] intraday_8583.csv.gz  in=373,911,230 out=121,302,879 elapsed=520.6s

  [11742/13157] intraday_8586.csv.gz  in=373,921,687 out=121,313,336 elapsed=520.8s

  [11743/13157] intraday_8585.csv.gz  in=373,932,172 out=121,323,821 elapsed=520.8s

  [11744/13157] intraday_8584.csv.gz  in=373,943,524 out=121,335,173 elapsed=520.8s

  [11745/13157] intraday_8587.csv.gz  in=373,954,023 out=121,345,672 elapsed=520.8s

  [11746/13157] intraday_8588.csv.gz  in=373,963,864 out=121,355,513 elapsed=520.9s

  [11747/13157] intraday_8589.csv.gz  in=373,978,372 out=121,370,021 elapsed=521.0s

  [11748/13157] intraday_8591.csv.gz  in=373,992,110 out=121,383,759 elapsed=521.0s

  [11749/13157] intraday_8590.csv.gz  in=374,009,884 out=121,401,533 elapsed=521.0s

  [11750/13157] intraday_8593.csv.gz  in=374,021,517 out=121,413,166 elapsed=521.0s

  [11751/13157] intraday_8592.csv.gz  in=374,031,887 out=121,423,536 elapsed=521.0s

  [11752/13157] intraday_8595.csv.gz  in=374,043,472 out=121,435,121 elapsed=521.0s

  [11753/13157] intraday_8597.csv.gz  in=374,055,128 out=121,446,777 elapsed=521.1s

  [11754/13157] intraday_8594.csv.gz  in=374,069,452 out=121,461,101 elapsed=521.1s

  [11755/13157] intraday_8596.csv.gz  in=374,084,572 out=121,476,221 elapsed=521.1s

  [11756/13157] intraday_8600.csv.gz  in=374,098,857 out=121,490,506 elapsed=521.1s

  [11757/13157] intraday_8598.csv.gz  in=374,111,654 out=121,503,303 elapsed=521.1s

  [11758/13157] intraday_8601.csv.gz  in=374,125,232 out=121,516,881 elapsed=521.1s

  [11759/13157] intraday_8599.csv.gz  in=374,137,077 out=121,528,726 elapsed=521.1s

  [11760/13157] intraday_8602.csv.gz  in=374,149,864 out=121,541,513 elapsed=521.1s

  [11761/13157] intraday_8605.csv.gz  in=374,163,152 out=121,554,801 elapsed=521.2s

  [11762/13157] intraday_8603.csv.gz  in=374,175,530 out=121,567,179 elapsed=521.2s

  [11763/13157] intraday_8604.csv.gz  in=374,186,241 out=121,577,890 elapsed=521.2s

  [11764/13157] intraday_8606.csv.gz  in=374,198,579 out=121,590,228 elapsed=521.2s

  [11765/13157] intraday_8607.csv.gz  in=374,210,705 out=121,602,354 elapsed=521.3s

  [11766/13157] intraday_8608.csv.gz  in=374,223,131 out=121,614,780 elapsed=521.3s

  [11767/13157] intraday_8609.csv.gz  in=374,237,489 out=121,629,138 elapsed=521.3s

  [11768/13157] intraday_8610.csv.gz  in=374,248,905 out=121,640,554 elapsed=521.3s

  [11769/13157] intraday_8611.csv.gz  in=374,261,120 out=121,652,769 elapsed=521.4s

  [11770/13157] intraday_8612.csv.gz  in=374,277,094 out=121,668,743 elapsed=521.4s

  [11771/13157] intraday_8614.csv.gz  in=374,290,525 out=121,682,174 elapsed=521.4s

  [11772/13157] intraday_8613.csv.gz  in=374,302,510 out=121,694,159 elapsed=521.4s

  [11773/13157] intraday_8615.csv.gz  in=374,316,445 out=121,708,094 elapsed=521.5s

  [11774/13157] intraday_8617.csv.gz  in=374,326,741 out=121,718,390 elapsed=521.5s

  [11775/13157] intraday_8618.csv.gz  in=374,339,244 out=121,730,893 elapsed=521.5s

  [11776/13157] intraday_8616.csv.gz  in=374,354,886 out=121,746,535 elapsed=521.5s

  [11777/13157] intraday_8619.csv.gz  in=374,367,689 out=121,759,338 elapsed=521.6s

  [11778/13157] intraday_8621.csv.gz  in=374,382,127 out=121,773,776 elapsed=521.7s

  [11779/13157] intraday_8620.csv.gz  in=374,395,184 out=121,786,833 elapsed=521.7s

  [11780/13157] intraday_8622.csv.gz  in=374,411,626 out=121,803,275 elapsed=521.7s

  [11781/13157] intraday_8624.csv.gz  in=374,425,450 out=121,817,099 elapsed=521.8s

  [11782/13157] intraday_8625.csv.gz  in=374,441,040 out=121,832,689 elapsed=521.8s

  [11783/13157] intraday_8626.csv.gz  in=374,453,499 out=121,845,138 elapsed=521.8s

  [11784/13157] intraday_8623.csv.gz  in=374,482,483 out=121,874,122 elapsed=521.8s

  [11785/13157] intraday_8628.csv.gz  in=374,492,289 out=121,883,928 elapsed=521.8s

  [11786/13157] intraday_8627.csv.gz  in=374,505,702 out=121,897,341 elapsed=521.8s

  [11787/13157] intraday_8630.csv.gz  in=374,515,460 out=121,907,099 elapsed=522.0s

  [11788/13157] intraday_8631.csv.gz  in=374,528,333 out=121,919,972 elapsed=522.0s

  [11789/13157] intraday_8629.csv.gz  in=374,542,924 out=121,934,563 elapsed=522.0s

  [11790/13157] intraday_8632.csv.gz  in=374,556,048 out=121,947,687 elapsed=522.0s

  [11791/13157] intraday_8635.csv.gz  in=374,568,144 out=121,959,783 elapsed=522.2s

  [11792/13157] intraday_8633.csv.gz  in=374,582,943 out=121,974,582 elapsed=522.2s

  [11793/13157] intraday_8636.csv.gz  in=374,594,553 out=121,986,192 elapsed=522.2s

  [11794/13157] intraday_8634.csv.gz  in=374,605,726 out=121,997,365 elapsed=522.2s

  [11795/13157] intraday_8638.csv.gz  in=374,616,719 out=122,008,358 elapsed=522.3s

  [11796/13157] intraday_8637.csv.gz  in=374,628,892 out=122,020,531 elapsed=522.3s

  [11797/13157] intraday_8639.csv.gz  in=374,643,283 out=122,034,922 elapsed=522.4s

  [11798/13157] intraday_8640.csv.gz  in=374,657,924 out=122,049,563 elapsed=522.4s

  [11799/13157] intraday_8641.csv.gz  in=374,670,565 out=122,062,204 elapsed=522.4s

  [11800/13157] intraday_8642.csv.gz  in=374,685,594 out=122,077,233 elapsed=522.4s

  [11801/13157] intraday_8644.csv.gz  in=374,697,724 out=122,089,363 elapsed=522.7s

  [11802/13157] intraday_8643.csv.gz  in=374,710,413 out=122,102,052 elapsed=522.7s

  [11803/13157] intraday_8646.csv.gz  in=374,721,399 out=122,113,038 elapsed=522.7s

  [11804/13157] intraday_8645.csv.gz  in=374,735,148 out=122,126,787 elapsed=522.7s

  [11805/13157] intraday_8648.csv.gz  in=374,742,137 out=122,133,776 elapsed=522.7s

  [11806/13157] intraday_8650.csv.gz  in=374,749,923 out=122,141,562 elapsed=522.8s

  [11807/13157] intraday_8647.csv.gz  in=374,761,229 out=122,152,868 elapsed=522.8s

  [11808/13157] intraday_8649.csv.gz  in=374,772,480 out=122,164,119 elapsed=522.8s

  [11809/13157] intraday_8651.csv.gz  in=374,787,760 out=122,172,200 elapsed=522.8s

  [11810/13157] intraday_8652.csv.gz  in=374,803,231 out=122,187,671 elapsed=522.8s

  [11811/13157] intraday_8653.csv.gz  in=374,815,633 out=122,200,073 elapsed=522.9s

  [11812/13157] intraday_8654.csv.gz  in=374,828,562 out=122,213,002 elapsed=522.9s

  [11813/13157] intraday_8656.csv.gz  in=374,840,253 out=122,224,693 elapsed=522.9s

  [11814/13157] intraday_8655.csv.gz  in=374,852,620 out=122,237,060 elapsed=522.9s

  [11815/13157] intraday_8660.csv.gz  in=374,865,558 out=122,249,998 elapsed=523.0s

  [11816/13157] intraday_8657.csv.gz  in=374,880,642 out=122,265,082 elapsed=523.0s

  [11817/13157] intraday_8658.csv.gz  in=374,895,463 out=122,279,903 elapsed=523.0s

  [11818/13157] intraday_8659.csv.gz  in=374,907,341 out=122,291,781 elapsed=523.0s

  [11819/13157] intraday_8663.csv.gz  in=374,920,459 out=122,304,899 elapsed=523.0s

  [11820/13157] intraday_8664.csv.gz  in=374,934,640 out=122,319,080 elapsed=523.0s

  [11821/13157] intraday_8661.csv.gz  in=374,948,833 out=122,333,273 elapsed=523.0s

  [11822/13157] intraday_8662.csv.gz  in=374,962,925 out=122,347,365 elapsed=523.0s

  [11823/13157] intraday_8666.csv.gz  in=374,972,486 out=122,356,926 elapsed=523.1s

  [11824/13157] intraday_8668.csv.gz  in=374,986,109 out=122,370,549 elapsed=523.2s

  [11825/13157] intraday_8665.csv.gz  in=375,000,139 out=122,384,579 elapsed=523.2s

  [11826/13157] intraday_8667.csv.gz  in=375,012,027 out=122,396,467 elapsed=523.2s

  [11827/13157] intraday_8669.csv.gz  in=375,025,716 out=122,410,156 elapsed=523.2s

  [11828/13157] intraday_8670.csv.gz  in=375,037,398 out=122,421,838 elapsed=523.5s

  [11829/13157] intraday_8672.csv.gz  in=375,048,287 out=122,432,727 elapsed=523.5s

  [11830/13157] intraday_8671.csv.gz  in=375,059,929 out=122,444,369 elapsed=523.5s

  [11831/13157] intraday_8673.csv.gz  in=375,074,621 out=122,459,061 elapsed=523.5s

  [11832/13157] intraday_8677.csv.gz  in=375,087,167 out=122,471,607 elapsed=523.8s

  [11833/13157] intraday_8675.csv.gz  in=375,100,304 out=122,484,744 elapsed=523.8s

  [11834/13157] intraday_8676.csv.gz  in=375,113,940 out=122,498,380 elapsed=523.8s

  [11835/13157] intraday_8674.csv.gz  in=375,126,231 out=122,510,671 elapsed=523.8s

  [11836/13157] intraday_8678.csv.gz  in=375,139,165 out=122,523,605 elapsed=524.1s

  [11837/13157] intraday_8679.csv.gz  in=375,150,612 out=122,535,052 elapsed=524.1s

  [11838/13157] intraday_8680.csv.gz  in=375,162,686 out=122,547,126 elapsed=524.1s

  [11839/13157] intraday_8681.csv.gz  in=375,175,991 out=122,560,431 elapsed=524.1s

  [11840/13157] intraday_8684.csv.gz  in=375,186,364 out=122,570,804 elapsed=524.2s

  [11841/13157] intraday_8682.csv.gz  in=375,203,484 out=122,587,924 elapsed=524.2s

  [11842/13157] intraday_8683.csv.gz  in=375,218,011 out=122,602,451 elapsed=524.2s

  [11843/13157] intraday_8685.csv.gz  in=375,230,199 out=122,614,639 elapsed=524.2s

  [11844/13157] intraday_8687.csv.gz  in=375,241,370 out=122,625,810 elapsed=524.3s

  [11845/13157] intraday_8686.csv.gz  in=375,254,865 out=122,639,305 elapsed=524.3s

  [11846/13157] intraday_8688.csv.gz  in=375,267,165 out=122,651,605 elapsed=524.3s

  [11847/13157] intraday_8689.csv.gz  in=375,277,904 out=122,662,344 elapsed=524.4s

  [11848/13157] intraday_8691.csv.gz  in=375,288,545 out=122,672,985 elapsed=524.5s

  [11849/13157] intraday_8692.csv.gz  in=375,300,497 out=122,684,937 elapsed=524.6s

  [11850/13157] intraday_8693.csv.gz  in=375,312,424 out=122,696,864 elapsed=524.6s

  [11851/13157] intraday_8690.csv.gz  in=375,325,161 out=122,709,601 elapsed=524.6s

  [11852/13157] intraday_8695.csv.gz  in=375,337,194 out=122,721,634 elapsed=524.7s

  [11853/13157] intraday_8694.csv.gz  in=375,350,808 out=122,735,248 elapsed=524.7s

  [11854/13157] intraday_8697.csv.gz  in=375,361,676 out=122,746,116 elapsed=524.7s

  [11855/13157] intraday_8696.csv.gz  in=375,376,232 out=122,760,672 elapsed=524.7s

  [11856/13157] intraday_8698.csv.gz  in=375,388,259 out=122,772,699 elapsed=524.7s

  [11857/13157] intraday_8700.csv.gz  in=375,399,625 out=122,784,065 elapsed=524.7s

  [11858/13157] intraday_8699.csv.gz  in=375,412,976 out=122,797,416 elapsed=524.8s

  [11859/13157] intraday_8701.csv.gz  in=375,424,417 out=122,808,857 elapsed=524.8s

  [11860/13157] intraday_8702.csv.gz  in=375,436,616 out=122,821,056 elapsed=524.8s

  [11861/13157] intraday_8703.csv.gz  in=375,447,454 out=122,831,894 elapsed=524.8s

  [11862/13157] intraday_8705.csv.gz  in=375,458,958 out=122,843,398 elapsed=524.8s

  [11863/13157] intraday_8704.csv.gz  in=375,474,419 out=122,858,859 elapsed=524.8s

  [11864/13157] intraday_8707.csv.gz  in=375,487,619 out=122,872,059 elapsed=524.9s

  [11865/13157] intraday_8706.csv.gz  in=375,500,531 out=122,884,971 elapsed=524.9s

  [11866/13157] intraday_8708.csv.gz  in=375,512,344 out=122,896,784 elapsed=525.0s

  [11867/13157] intraday_8709.csv.gz  in=375,523,047 out=122,907,487 elapsed=525.0s

  [11868/13157] intraday_8713.csv.gz  in=375,536,363 out=122,920,803 elapsed=525.1s

  [11869/13157] intraday_8710.csv.gz  in=375,550,136 out=122,934,576 elapsed=525.1s

  [11870/13157] intraday_8712.csv.gz  in=375,561,623 out=122,946,063 elapsed=525.1s

  [11871/13157] intraday_8711.csv.gz  in=375,574,932 out=122,959,372 elapsed=525.1s

  [11872/13157] intraday_8714.csv.gz  in=375,586,310 out=122,970,750 elapsed=525.1s

  [11873/13157] intraday_8715.csv.gz  in=375,598,973 out=122,983,413 elapsed=525.3s

  [11874/13157] intraday_8718.csv.gz  in=375,611,944 out=122,996,384 elapsed=525.3s

  [11875/13157] intraday_8716.csv.gz  in=375,622,604 out=123,007,044 elapsed=525.3s

  [11876/13157] intraday_8717.csv.gz  in=375,637,714 out=123,022,154 elapsed=525.3s

  [11877/13157] intraday_8722.csv.gz  in=375,648,294 out=123,032,734 elapsed=525.5s

  [11878/13157] intraday_8721.csv.gz  in=375,659,719 out=123,044,159 elapsed=525.5s

  [11879/13157] intraday_8720.csv.gz  in=375,671,530 out=123,055,970 elapsed=525.5s

  [11880/13157] intraday_8719.csv.gz  in=375,689,285 out=123,073,725 elapsed=525.5s

  [11881/13157] intraday_8723.csv.gz  in=375,702,351 out=123,086,791 elapsed=525.6s

  [11882/13157] intraday_8724.csv.gz  in=375,714,753 out=123,099,193 elapsed=525.6s

  [11883/13157] intraday_8726.csv.gz  in=375,725,573 out=123,110,013 elapsed=525.6s

  [11884/13157] intraday_8725.csv.gz  in=375,739,677 out=123,124,117 elapsed=525.6s

  [11885/13157] intraday_8728.csv.gz  in=375,750,840 out=123,135,280 elapsed=525.7s

  [11886/13157] intraday_8730.csv.gz  in=375,761,193 out=123,145,633 elapsed=525.7s

  [11887/13157] intraday_8729.csv.gz  in=375,775,219 out=123,159,659 elapsed=525.7s

  [11888/13157] intraday_8727.csv.gz  in=375,787,833 out=123,172,273 elapsed=525.7s

  [11889/13157] intraday_8731.csv.gz  in=375,799,503 out=123,183,943 elapsed=525.7s

  [11890/13157] intraday_8733.csv.gz  in=375,809,905 out=123,194,345 elapsed=525.7s

  [11891/13157] intraday_8732.csv.gz  in=375,821,107 out=123,205,547 elapsed=525.7s

  [11892/13157] intraday_8734.csv.gz  in=375,832,205 out=123,216,645 elapsed=525.7s

  [11893/13157] intraday_8738.csv.gz  in=375,843,542 out=123,227,982 elapsed=525.8s

  [11894/13157] intraday_8736.csv.gz  in=375,859,629 out=123,244,069 elapsed=525.8s

  [11895/13157] intraday_8737.csv.gz  in=375,872,871 out=123,257,311 elapsed=525.8s

  [11896/13157] intraday_8735.csv.gz  in=375,888,972 out=123,273,412 elapsed=525.8s

  [11897/13157] intraday_8739.csv.gz  in=375,901,608 out=123,286,048 elapsed=525.9s

  [11898/13157] intraday_8741.csv.gz  in=375,913,682 out=123,298,122 elapsed=525.9s

  [11899/13157] intraday_8742.csv.gz  in=375,928,665 out=123,313,105 elapsed=525.9s

  [11900/13157] intraday_8740.csv.gz  in=375,942,431 out=123,326,871 elapsed=525.9s

  [11901/13157] intraday_8746.csv.gz  in=375,955,453 out=123,339,893 elapsed=525.9s

  [11902/13157] intraday_8744.csv.gz  in=375,970,065 out=123,354,505 elapsed=525.9s

  [11903/13157] intraday_8743.csv.gz  in=375,982,249 out=123,366,689 elapsed=525.9s

  [11904/13157] intraday_8745.csv.gz  in=375,995,410 out=123,379,850 elapsed=525.9s

  [11905/13157] intraday_8748.csv.gz  in=376,007,512 out=123,391,952 elapsed=526.0s

  [11906/13157] intraday_8750.csv.gz  in=376,019,535 out=123,403,975 elapsed=526.0s

  [11907/13157] intraday_8749.csv.gz  in=376,037,812 out=123,420,082 elapsed=526.0s

  [11908/13157] intraday_8747.csv.gz  in=376,051,435 out=123,433,705 elapsed=526.0s

  [11909/13157] intraday_8752.csv.gz  in=376,062,877 out=123,445,147 elapsed=526.1s

  [11910/13157] intraday_8751.csv.gz  in=376,075,775 out=123,457,162 elapsed=526.1s

  [11911/13157] intraday_8753.csv.gz  in=376,089,483 out=123,470,870 elapsed=526.1s

  [11912/13157] intraday_8754.csv.gz  in=376,101,791 out=123,483,178 elapsed=526.1s

  [11913/13157] intraday_8756.csv.gz  in=376,113,381 out=123,494,768 elapsed=526.1s

  [11914/13157] intraday_8757.csv.gz  in=376,125,974 out=123,507,361 elapsed=526.1s

  [11915/13157] intraday_8755.csv.gz  in=376,143,277 out=123,523,405 elapsed=526.1s

  [11916/13157] intraday_8759.csv.gz  in=376,155,856 out=123,535,984 elapsed=526.2s

  [11917/13157] intraday_8760.csv.gz  in=376,168,408 out=123,548,536 elapsed=526.2s

  [11918/13157] intraday_8758.csv.gz  in=376,184,216 out=123,564,344 elapsed=526.2s

  [11919/13157] intraday_8761.csv.gz  in=376,199,346 out=123,579,474 elapsed=526.2s

  [11920/13157] intraday_8763.csv.gz  in=376,210,265 out=123,590,393 elapsed=526.2s

  [11921/13157] intraday_8762.csv.gz  in=376,225,491 out=123,605,619 elapsed=526.2s

  [11922/13157] intraday_8767.csv.gz  in=376,240,806 out=123,620,934 elapsed=526.3s

  [11923/13157] intraday_8764.csv.gz  in=376,253,925 out=123,634,053 elapsed=526.3s

  [11924/13157] intraday_8765.csv.gz  in=376,266,837 out=123,646,965 elapsed=526.3s

  [11925/13157] intraday_8766.csv.gz  in=376,279,300 out=123,659,428 elapsed=526.3s

  [11926/13157] intraday_8771.csv.gz  in=376,293,670 out=123,673,798 elapsed=526.4s

  [11927/13157] intraday_8768.csv.gz  in=376,309,278 out=123,689,406 elapsed=526.4s

  [11928/13157] intraday_8770.csv.gz  in=376,324,635 out=123,704,763 elapsed=526.4s

  [11929/13157] intraday_8769.csv.gz  in=376,346,227 out=123,726,355 elapsed=526.4s

  [11930/13157] intraday_8773.csv.gz  in=376,358,679 out=123,738,807 elapsed=526.5s

  [11931/13157] intraday_8772.csv.gz  in=376,371,282 out=123,751,410 elapsed=526.5s

  [11932/13157] intraday_8774.csv.gz  in=376,381,915 out=123,762,043 elapsed=526.5s

  [11933/13157] intraday_8775.csv.gz  in=376,396,539 out=123,776,667 elapsed=526.5s

  [11934/13157] intraday_8777.csv.gz  in=376,409,337 out=123,789,465 elapsed=526.6s

  [11935/13157] intraday_8776.csv.gz  in=376,420,384 out=123,800,512 elapsed=526.6s

  [11936/13157] intraday_8778.csv.gz  in=376,434,247 out=123,814,375 elapsed=526.7s

  [11937/13157] intraday_8779.csv.gz  in=376,448,781 out=123,828,909 elapsed=526.7s

  [11938/13157] intraday_8780.csv.gz  in=376,459,944 out=123,840,072 elapsed=526.8s

  [11939/13157] intraday_8781.csv.gz  in=376,471,790 out=123,851,918 elapsed=526.8s

  [11940/13157] intraday_8782.csv.gz  in=376,483,764 out=123,863,892 elapsed=526.8s

  [11941/13157] intraday_8783.csv.gz  in=376,496,019 out=123,876,147 elapsed=526.8s

  [11942/13157] intraday_8784.csv.gz  in=376,507,607 out=123,887,735 elapsed=527.1s

  [11943/13157] intraday_8785.csv.gz  in=376,521,692 out=123,901,820 elapsed=527.1s

  [11944/13157] intraday_8787.csv.gz  in=376,535,390 out=123,915,518 elapsed=527.1s

  [11945/13157] intraday_8786.csv.gz  in=376,550,270 out=123,930,398 elapsed=527.1s

  [11946/13157] intraday_8789.csv.gz  in=376,562,542 out=123,942,670 elapsed=527.2s

  [11947/13157] intraday_8790.csv.gz  in=376,574,411 out=123,954,539 elapsed=527.3s

  [11948/13157] intraday_8791.csv.gz  in=376,588,640 out=123,968,768 elapsed=527.3s

  [11949/13157] intraday_8788.csv.gz  in=376,603,391 out=123,983,519 elapsed=527.3s

  [11950/13157] intraday_8794.csv.gz  in=376,609,996 out=123,990,124 elapsed=527.3s

  [11951/13157] intraday_8792.csv.gz  in=376,621,239 out=124,001,367 elapsed=527.3s

  [11952/13157] intraday_8795.csv.gz  in=376,634,174 out=124,014,302 elapsed=527.3s

  [11953/13157] intraday_8793.csv.gz  in=376,645,807 out=124,025,935 elapsed=527.3s

  [11954/13157] intraday_8796.csv.gz  in=376,652,465 out=124,032,593 elapsed=527.4s

  [11955/13157] intraday_8798.csv.gz  in=376,664,331 out=124,044,459 elapsed=527.4s

  [11956/13157] intraday_8799.csv.gz  in=376,678,669 out=124,058,797 elapsed=527.4s

  [11957/13157] intraday_8797.csv.gz  in=376,694,061 out=124,074,189 elapsed=527.4s

  [11958/13157] intraday_8800.csv.gz  in=376,704,459 out=124,084,587 elapsed=527.5s

  [11959/13157] intraday_8801.csv.gz  in=376,716,694 out=124,096,822 elapsed=527.5s

  [11960/13157] intraday_8804.csv.gz  in=376,728,293 out=124,108,421 elapsed=527.7s

  [11961/13157] intraday_8805.csv.gz  in=376,740,775 out=124,120,903 elapsed=527.7s

  [11962/13157] intraday_8803.csv.gz  in=376,754,958 out=124,135,086 elapsed=527.7s

  [11963/13157] intraday_8802.csv.gz  in=376,770,517 out=124,150,645 elapsed=527.7s

  [11964/13157] intraday_8806.csv.gz  in=376,785,249 out=124,165,377 elapsed=527.7s

  [11965/13157] intraday_8808.csv.gz  in=376,799,175 out=124,179,303 elapsed=527.7s

  [11966/13157] intraday_8807.csv.gz  in=376,813,440 out=124,193,465 elapsed=527.8s

  [11967/13157] intraday_8809.csv.gz  in=376,826,914 out=124,206,939 elapsed=527.9s

  [11968/13157] intraday_8811.csv.gz  in=376,836,808 out=124,216,833 elapsed=527.9s

  [11969/13157] intraday_8810.csv.gz  in=376,851,123 out=124,231,148 elapsed=528.0s

  [11970/13157] intraday_8812.csv.gz  in=376,862,961 out=124,242,986 elapsed=528.2s

  [11971/13157] intraday_8813.csv.gz  in=376,876,875 out=124,256,900 elapsed=528.2s

  [11972/13157] intraday_8814.csv.gz  in=376,889,120 out=124,269,145 elapsed=528.2s

  [11973/13157] intraday_8815.csv.gz  in=376,901,381 out=124,281,406 elapsed=528.2s

  [11974/13157] intraday_8816.csv.gz  in=376,912,577 out=124,292,602 elapsed=528.2s

  [11975/13157] intraday_8817.csv.gz  in=376,924,710 out=124,304,735 elapsed=528.3s

  [11976/13157] intraday_8818.csv.gz  in=376,938,847 out=124,318,872 elapsed=528.3s

  [11977/13157] intraday_8820.csv.gz  in=376,952,483 out=124,332,508 elapsed=528.3s

  [11978/13157] intraday_8819.csv.gz  in=376,965,257 out=124,345,282 elapsed=528.3s

  [11979/13157] intraday_8824.csv.gz  in=376,977,247 out=124,357,272 elapsed=528.3s

  [11980/13157] intraday_8821.csv.gz  in=376,990,670 out=124,370,695 elapsed=528.3s

  [11981/13157] intraday_8823.csv.gz  in=377,003,064 out=124,383,089 elapsed=528.4s

  [11982/13157] intraday_8822.csv.gz  in=377,016,368 out=124,396,393 elapsed=528.4s

  [11983/13157] intraday_8825.csv.gz  in=377,033,340 out=124,411,553 elapsed=528.4s

  [11984/13157] intraday_8826.csv.gz  in=377,047,392 out=124,425,605 elapsed=528.4s

  [11985/13157] intraday_8829.csv.gz  in=377,058,832 out=124,437,045 elapsed=528.4s

  [11986/13157] intraday_8830.csv.gz  in=377,071,267 out=124,449,480 elapsed=528.4s

  [11987/13157] intraday_8828.csv.gz  in=377,084,809 out=124,463,022 elapsed=528.4s

  [11988/13157] intraday_8827.csv.gz  in=377,100,619 out=124,478,832 elapsed=528.5s

  [11989/13157] intraday_8832.csv.gz  in=377,111,580 out=124,489,793 elapsed=528.5s

  [11990/13157] intraday_8831.csv.gz  in=377,124,499 out=124,502,712 elapsed=528.5s

  [11991/13157] intraday_8833.csv.gz  in=377,137,366 out=124,515,579 elapsed=528.5s

  [11992/13157] intraday_8834.csv.gz  in=377,148,044 out=124,526,257 elapsed=528.5s

  [11993/13157] intraday_8835.csv.gz  in=377,160,310 out=124,538,523 elapsed=528.5s

  [11994/13157] intraday_8836.csv.gz  in=377,171,363 out=124,549,576 elapsed=528.6s

  [11995/13157] intraday_8839.csv.gz  in=377,185,106 out=124,563,319 elapsed=528.6s

  [11996/13157] intraday_8837.csv.gz  in=377,196,933 out=124,575,146 elapsed=528.6s

  [11997/13157] intraday_8838.csv.gz  in=377,209,283 out=124,587,496 elapsed=528.6s

  [11998/13157] intraday_8840.csv.gz  in=377,221,380 out=124,599,593 elapsed=528.7s

  [11999/13157] intraday_8842.csv.gz  in=377,232,535 out=124,610,748 elapsed=528.7s

  [12000/13157] intraday_8841.csv.gz  in=377,246,313 out=124,624,526 elapsed=528.7s

  [12001/13157] intraday_8843.csv.gz  in=377,257,426 out=124,635,639 elapsed=528.7s

  [12002/13157] intraday_8846.csv.gz  in=377,269,180 out=124,647,393 elapsed=528.8s

  [12003/13157] intraday_8847.csv.gz  in=377,281,217 out=124,659,430 elapsed=528.8s

  [12004/13157] intraday_8845.csv.gz  in=377,291,728 out=124,669,941 elapsed=528.8s

  [12005/13157] intraday_8844.csv.gz  in=377,305,362 out=124,683,575 elapsed=528.8s

  [12006/13157] intraday_8848.csv.gz  in=377,316,779 out=124,694,992 elapsed=528.8s

  [12007/13157] intraday_8851.csv.gz  in=377,330,166 out=124,708,379 elapsed=528.9s

  [12008/13157] intraday_8850.csv.gz  in=377,343,590 out=124,720,891 elapsed=528.9s

  [12009/13157] intraday_8849.csv.gz  in=377,359,472 out=124,736,773 elapsed=528.9s

  [12010/13157] intraday_8852.csv.gz  in=377,379,007 out=124,754,028 elapsed=528.9s

  [12011/13157] intraday_8854.csv.gz  in=377,390,139 out=124,765,160 elapsed=529.0s

  [12012/13157] intraday_8853.csv.gz  in=377,404,217 out=124,778,955 elapsed=529.0s

  [12013/13157] intraday_8856.csv.gz  in=377,416,915 out=124,791,653 elapsed=529.1s

  [12014/13157] intraday_8855.csv.gz  in=377,429,123 out=124,803,861 elapsed=529.1s

  [12015/13157] intraday_8857.csv.gz  in=377,441,557 out=124,816,295 elapsed=529.1s

  [12016/13157] intraday_8860.csv.gz  in=377,454,319 out=124,829,057 elapsed=529.1s

  [12017/13157] intraday_8858.csv.gz  in=377,471,280 out=124,846,018 elapsed=529.1s

  [12018/13157] intraday_8859.csv.gz  in=377,482,340 out=124,857,078 elapsed=529.2s

  [12019/13157] intraday_8861.csv.gz  in=377,493,211 out=124,867,949 elapsed=529.2s

  [12020/13157] intraday_8862.csv.gz  in=377,508,588 out=124,883,326 elapsed=529.2s

  [12021/13157] intraday_8863.csv.gz  in=377,520,647 out=124,895,385 elapsed=529.2s

  [12022/13157] intraday_8865.csv.gz  in=377,534,277 out=124,909,015 elapsed=529.2s

  [12023/13157] intraday_8864.csv.gz  in=377,548,260 out=124,922,998 elapsed=529.3s

  [12024/13157] intraday_8866.csv.gz  in=377,559,407 out=124,934,145 elapsed=529.3s

  [12025/13157] intraday_8867.csv.gz  in=377,568,684 out=124,943,422 elapsed=529.3s

  [12026/13157] intraday_8868.csv.gz  in=377,580,680 out=124,955,418 elapsed=529.3s

  [12027/13157] intraday_8869.csv.gz  in=377,593,770 out=124,968,508 elapsed=529.4s

  [12028/13157] intraday_8872.csv.gz  in=377,606,508 out=124,981,246 elapsed=529.4s

  [12029/13157] intraday_8870.csv.gz  in=377,620,315 out=124,995,053 elapsed=529.4s

  [12030/13157] intraday_8871.csv.gz  in=377,634,848 out=125,008,709 elapsed=529.4s

  [12031/13157] intraday_8873.csv.gz  in=377,648,059 out=125,021,920 elapsed=529.4s

  [12032/13157] intraday_8875.csv.gz  in=377,658,769 out=125,032,630 elapsed=529.4s

  [12033/13157] intraday_8874.csv.gz  in=377,672,426 out=125,046,287 elapsed=529.4s

  [12034/13157] intraday_8876.csv.gz  in=377,684,141 out=125,058,002 elapsed=529.5s

  [12035/13157] intraday_8877.csv.gz  in=377,700,181 out=125,071,973 elapsed=529.5s

  [12036/13157] intraday_8878.csv.gz  in=377,711,501 out=125,082,869 elapsed=529.5s

  [12037/13157] intraday_8879.csv.gz  in=377,722,894 out=125,094,262 elapsed=529.5s

  [12038/13157] intraday_8881.csv.gz  in=377,741,238 out=125,112,606 elapsed=529.5s

  [12039/13157] intraday_8880.csv.gz  in=377,754,812 out=125,126,180 elapsed=529.5s

  [12040/13157] intraday_8882.csv.gz  in=377,767,678 out=125,139,046 elapsed=529.5s

  [12041/13157] intraday_8885.csv.gz  in=377,782,233 out=125,153,601 elapsed=529.6s

  [12042/13157] intraday_8886.csv.gz  in=377,794,770 out=125,166,138 elapsed=529.6s

  [12043/13157] intraday_8884.csv.gz  in=377,807,305 out=125,178,673 elapsed=529.6s

  [12044/13157] intraday_8883.csv.gz  in=377,818,955 out=125,190,323 elapsed=529.6s

  [12045/13157] intraday_8888.csv.gz  in=377,832,583 out=125,203,951 elapsed=529.7s

  [12046/13157] intraday_8887.csv.gz  in=377,847,818 out=125,219,186 elapsed=529.7s

  [12047/13157] intraday_8889.csv.gz  in=377,860,684 out=125,232,052 elapsed=529.7s

  [12048/13157] intraday_8890.csv.gz  in=377,873,320 out=125,244,688 elapsed=529.7s

  [12049/13157] intraday_8893.csv.gz  in=377,886,670 out=125,258,038 elapsed=529.9s

  [12050/13157] intraday_8891.csv.gz  in=377,900,019 out=125,271,387 elapsed=529.9s

  [12051/13157] intraday_8892.csv.gz  in=377,914,424 out=125,285,491 elapsed=529.9s

  [12052/13157] intraday_8894.csv.gz  in=377,928,064 out=125,299,131 elapsed=529.9s

  [12053/13157] intraday_8895.csv.gz  in=377,939,169 out=125,310,236 elapsed=530.1s

  [12054/13157] intraday_8898.csv.gz  in=377,950,591 out=125,321,658 elapsed=530.1s

  [12055/13157] intraday_8897.csv.gz  in=377,963,950 out=125,335,017 elapsed=530.1s

  [12056/13157] intraday_8896.csv.gz  in=377,988,924 out=125,355,900 elapsed=530.1s

  [12057/13157] intraday_8902.csv.gz  in=378,001,163 out=125,368,139 elapsed=530.3s

  [12058/13157] intraday_8899.csv.gz  in=378,015,961 out=125,382,641 elapsed=530.3s

  [12059/13157] intraday_8900.csv.gz  in=378,029,336 out=125,396,016 elapsed=530.3s

  [12060/13157] intraday_8901.csv.gz  in=378,043,275 out=125,409,955 elapsed=530.3s

  [12061/13157] intraday_8905.csv.gz  in=378,055,667 out=125,422,347 elapsed=530.4s

  [12062/13157] intraday_8903.csv.gz  in=378,069,268 out=125,435,948 elapsed=530.4s

  [12063/13157] intraday_8904.csv.gz  in=378,082,499 out=125,449,179 elapsed=530.4s

  [12064/13157] intraday_8906.csv.gz  in=378,097,985 out=125,464,665 elapsed=530.5s

  [12065/13157] intraday_8909.csv.gz  in=378,110,165 out=125,476,845 elapsed=530.5s

  [12066/13157] intraday_8908.csv.gz  in=378,121,944 out=125,488,624 elapsed=530.5s

  [12067/13157] intraday_8910.csv.gz  in=378,136,443 out=125,503,123 elapsed=530.5s

  [12068/13157] intraday_8907.csv.gz  in=378,151,423 out=125,518,103 elapsed=530.5s

  [12069/13157] intraday_8911.csv.gz  in=378,162,774 out=125,529,454 elapsed=530.6s

  [12070/13157] intraday_8913.csv.gz  in=378,179,044 out=125,545,724 elapsed=530.7s

  [12071/13157] intraday_8912.csv.gz  in=378,194,285 out=125,560,965 elapsed=530.7s

  [12072/13157] intraday_8914.csv.gz  in=378,217,044 out=125,583,114 elapsed=530.7s

  [12073/13157] intraday_8918.csv.gz  in=378,230,405 out=125,596,475 elapsed=530.9s

  [12074/13157] intraday_8916.csv.gz  in=378,247,139 out=125,613,209 elapsed=530.9s

  [12075/13157] intraday_8915.csv.gz  in=378,260,690 out=125,626,760 elapsed=530.9s

  [12076/13157] intraday_8917.csv.gz  in=378,272,539 out=125,638,609 elapsed=531.0s

  [12077/13157] intraday_8919.csv.gz  in=378,283,850 out=125,649,920 elapsed=531.1s

  [12078/13157] intraday_8920.csv.gz  in=378,297,163 out=125,663,233 elapsed=531.1s

  [12079/13157] intraday_8921.csv.gz  in=378,308,320 out=125,674,390 elapsed=531.1s

  [12080/13157] intraday_8922.csv.gz  in=378,322,033 out=125,688,103 elapsed=531.1s

  [12081/13157] intraday_8923.csv.gz  in=378,334,459 out=125,700,529 elapsed=531.2s

  [12082/13157] intraday_8924.csv.gz  in=378,350,459 out=125,716,529 elapsed=531.2s

  [12083/13157] intraday_8925.csv.gz  in=378,361,408 out=125,727,478 elapsed=531.2s

  [12084/13157] intraday_8926.csv.gz  in=378,373,954 out=125,740,024 elapsed=531.2s

  [12085/13157] intraday_8927.csv.gz  in=378,384,851 out=125,750,921 elapsed=531.2s

  [12086/13157] intraday_8928.csv.gz  in=378,398,018 out=125,764,088 elapsed=531.2s

  [12087/13157] intraday_8929.csv.gz  in=378,409,992 out=125,776,062 elapsed=531.2s

  [12088/13157] intraday_8930.csv.gz  in=378,424,149 out=125,790,219 elapsed=531.3s

  [12089/13157] intraday_8931.csv.gz  in=378,438,648 out=125,804,718 elapsed=531.3s

  [12090/13157] intraday_8932.csv.gz  in=378,451,992 out=125,818,062 elapsed=531.3s

  [12091/13157] intraday_8934.csv.gz  in=378,464,888 out=125,830,958 elapsed=531.3s

  [12092/13157] intraday_8933.csv.gz  in=378,479,431 out=125,845,501 elapsed=531.3s

  [12093/13157] intraday_8935.csv.gz  in=378,491,264 out=125,857,334 elapsed=531.3s

  [12094/13157] intraday_8936.csv.gz  in=378,504,361 out=125,870,431 elapsed=531.4s

  [12095/13157] intraday_8939.csv.gz  in=378,511,767 out=125,877,837 elapsed=531.4s

  [12096/13157] intraday_8938.csv.gz  in=378,525,517 out=125,891,587 elapsed=531.4s

  [12097/13157] intraday_8937.csv.gz  in=378,536,123 out=125,902,193 elapsed=531.4s

  [12098/13157] intraday_8940.csv.gz  in=378,546,924 out=125,912,721 elapsed=531.4s

  [12099/13157] intraday_8941.csv.gz  in=378,557,495 out=125,923,292 elapsed=531.4s

  [12100/13157] intraday_8943.csv.gz  in=378,559,792 out=125,924,796 elapsed=531.4s

  [12101/13157] intraday_8942.csv.gz  in=378,562,451 out=125,926,447 elapsed=531.4s

  [12102/13157] intraday_8944.csv.gz  in=378,563,324 out=125,927,320 elapsed=531.5s

  [12103/13157] intraday_8946.csv.gz  in=378,563,495 out=125,927,491 elapsed=531.5s

  [12104/13157] intraday_8945.csv.gz  in=378,563,783 out=125,927,571 elapsed=531.5s

  [12105/13157] intraday_8948.csv.gz  in=378,563,860 out=125,927,648 elapsed=531.5s

  [12106/13157] intraday_8950.csv.gz  in=378,564,300 out=125,928,088 elapsed=531.5s

  [12107/13157] intraday_8949.csv.gz  in=378,564,369 out=125,928,157 elapsed=531.5s

  [12108/13157] intraday_8947.csv.gz  in=378,570,880 out=125,933,081 elapsed=531.5s

  [12109/13157] intraday_8954.csv.gz  in=378,570,890 out=125,933,091 elapsed=531.5s

  [12110/13157] intraday_8952.csv.gz  in=378,571,230 out=125,933,431 elapsed=531.6s

  [12111/13157] intraday_8955.csv.gz  in=378,572,074 out=125,933,431 elapsed=531.6s

  [12112/13157] intraday_8953.csv.gz  in=378,572,315 out=125,933,672 elapsed=531.6s

  [12113/13157] intraday_8957.csv.gz  in=378,572,334 out=125,933,691 elapsed=531.6s

  [12114/13157] intraday_8958.csv.gz  in=378,572,372 out=125,933,729 elapsed=531.6s

  [12115/13157] intraday_8956.csv.gz  in=378,572,440 out=125,933,797 elapsed=531.6s

  [12116/13157] intraday_8951.csv.gz  in=378,586,397 out=125,943,396 elapsed=531.6s

  [12117/13157] intraday_8959.csv.gz  in=378,588,422 out=125,945,421 elapsed=531.6s

  [12118/13157] intraday_8961.csv.gz  in=378,588,933 out=125,945,932 elapsed=531.6s

  [12119/13157] intraday_8962.csv.gz  in=378,593,698 out=125,949,237 elapsed=531.6s

  [12120/13157] intraday_8960.csv.gz  in=378,597,228 out=125,951,725 elapsed=531.7s

  [12121/13157] intraday_8963.csv.gz  in=378,597,433 out=125,951,930 elapsed=531.7s

  [12122/13157] intraday_8964.csv.gz  in=378,597,446 out=125,951,943 elapsed=531.7s

  [12123/13157] intraday_8965.csv.gz  in=378,601,208 out=125,954,448 elapsed=531.7s

  [12124/13157] intraday_8966.csv.gz  in=378,601,513 out=125,954,753 elapsed=531.7s

  [12125/13157] intraday_8967.csv.gz  in=378,604,619 out=125,956,894 elapsed=531.7s

  [12126/13157] intraday_8968.csv.gz  in=378,604,882 out=125,957,157 elapsed=531.7s

  [12127/13157] intraday_8969.csv.gz  in=378,604,913 out=125,957,188 elapsed=531.7s

  [12128/13157] intraday_8970.csv.gz  in=378,609,696 out=125,960,813 elapsed=531.7s

  [12129/13157] intraday_8972.csv.gz  in=378,611,594 out=125,962,092 elapsed=531.8s

  [12130/13157] intraday_8973.csv.gz  in=378,626,935 out=125,977,433 elapsed=531.8s

  [12131/13157] intraday_8971.csv.gz  in=378,658,003 out=125,994,872 elapsed=531.8s

  [12132/13157] intraday_8976.csv.gz  in=378,668,685 out=126,005,554 elapsed=531.8s

  [12133/13157] intraday_8975.csv.gz  in=378,682,482 out=126,019,351 elapsed=531.8s

  [12134/13157] intraday_8977.csv.gz  in=378,695,816 out=126,032,685 elapsed=531.8s

  [12135/13157] intraday_8978.csv.gz  in=378,709,978 out=126,046,847 elapsed=531.9s

  [12136/13157] intraday_8974.csv.gz  in=378,721,721 out=126,058,590 elapsed=531.9s

  [12137/13157] intraday_8979.csv.gz  in=378,736,852 out=126,073,721 elapsed=531.9s

  [12138/13157] intraday_8980.csv.gz  in=378,749,378 out=126,086,247 elapsed=532.3s

  [12139/13157] intraday_8981.csv.gz  in=378,762,123 out=126,098,992 elapsed=532.3s

  [12140/13157] intraday_8983.csv.gz  in=378,776,617 out=126,113,486 elapsed=532.3s

  [12141/13157] intraday_8982.csv.gz  in=378,790,449 out=126,127,318 elapsed=532.3s

  [12142/13157] intraday_8984.csv.gz  in=378,803,547 out=126,140,416 elapsed=532.4s

  [12143/13157] intraday_8987.csv.gz  in=378,813,396 out=126,150,265 elapsed=532.5s

  [12144/13157] intraday_8986.csv.gz  in=378,825,390 out=126,162,259 elapsed=532.5s

  [12145/13157] intraday_8985.csv.gz  in=378,841,104 out=126,177,973 elapsed=532.5s

  [12146/13157] intraday_8990.csv.gz  in=378,854,100 out=126,190,969 elapsed=532.6s

  [12147/13157] intraday_8989.csv.gz  in=378,867,387 out=126,204,256 elapsed=532.6s

  [12148/13157] intraday_8988.csv.gz  in=378,879,077 out=126,215,946 elapsed=532.6s

  [12149/13157] intraday_8991.csv.gz  in=378,889,694 out=126,226,563 elapsed=532.6s

  [12150/13157] intraday_8992.csv.gz  in=378,901,384 out=126,238,253 elapsed=532.8s

  [12151/13157] intraday_8994.csv.gz  in=378,914,338 out=126,251,207 elapsed=532.8s

  [12152/13157] intraday_8993.csv.gz  in=378,925,762 out=126,262,631 elapsed=532.9s

  [12153/13157] intraday_8995.csv.gz  in=378,939,566 out=126,276,435 elapsed=532.9s

  [12154/13157] intraday_8996.csv.gz  in=378,952,304 out=126,289,173 elapsed=532.9s

  [12155/13157] intraday_8997.csv.gz  in=378,966,498 out=126,303,367 elapsed=532.9s

  [12156/13157] intraday_8998.csv.gz  in=378,979,467 out=126,316,336 elapsed=533.1s

  [12157/13157] intraday_8999.csv.gz  in=378,991,250 out=126,328,119 elapsed=533.1s

  [12158/13157] intraday_9000.csv.gz  in=379,002,904 out=126,339,773 elapsed=533.1s

  [12159/13157] intraday_9001.csv.gz  in=379,014,781 out=126,351,650 elapsed=533.1s

  [12160/13157] intraday_9002.csv.gz  in=379,027,455 out=126,364,324 elapsed=533.1s

  [12161/13157] intraday_9005.csv.gz  in=379,038,384 out=126,375,253 elapsed=533.3s

  [12162/13157] intraday_9006.csv.gz  in=379,049,928 out=126,386,797 elapsed=533.3s

  [12163/13157] intraday_9003.csv.gz  in=379,066,068 out=126,402,937 elapsed=533.3s

  [12164/13157] intraday_9004.csv.gz  in=379,079,325 out=126,416,194 elapsed=533.3s

  [12165/13157] intraday_9007.csv.gz  in=379,091,801 out=126,428,670 elapsed=533.6s

  [12166/13157] intraday_9009.csv.gz  in=379,103,854 out=126,440,723 elapsed=533.6s

  [12167/13157] intraday_9010.csv.gz  in=379,114,985 out=126,451,854 elapsed=533.6s

  [12168/13157] intraday_9008.csv.gz  in=379,127,428 out=126,464,297 elapsed=533.6s

  [12169/13157] intraday_9011.csv.gz  in=379,138,912 out=126,475,781 elapsed=533.7s

  [12170/13157] intraday_9014.csv.gz  in=379,151,250 out=126,488,119 elapsed=533.7s

  [12171/13157] intraday_9012.csv.gz  in=379,162,106 out=126,498,975 elapsed=533.7s

  [12172/13157] intraday_9013.csv.gz  in=379,174,325 out=126,511,194 elapsed=533.7s

  [12173/13157] intraday_9015.csv.gz  in=379,186,226 out=126,523,095 elapsed=533.7s

  [12174/13157] intraday_9016.csv.gz  in=379,198,973 out=126,535,842 elapsed=533.7s

  [12175/13157] intraday_9017.csv.gz  in=379,213,361 out=126,550,230 elapsed=533.8s

  [12176/13157] intraday_9018.csv.gz  in=379,223,759 out=126,560,628 elapsed=533.8s

  [12177/13157] intraday_9019.csv.gz  in=379,235,833 out=126,572,702 elapsed=533.8s

  [12178/13157] intraday_9020.csv.gz  in=379,248,352 out=126,585,221 elapsed=533.8s

  [12179/13157] intraday_9021.csv.gz  in=379,259,802 out=126,596,671 elapsed=533.8s

  [12180/13157] intraday_9023.csv.gz  in=379,272,918 out=126,609,787 elapsed=533.8s

  [12181/13157] intraday_9024.csv.gz  in=379,282,941 out=126,619,810 elapsed=533.9s

  [12182/13157] intraday_9022.csv.gz  in=379,295,179 out=126,632,048 elapsed=533.9s

  [12183/13157] intraday_9025.csv.gz  in=379,310,664 out=126,647,533 elapsed=533.9s

  [12184/13157] intraday_9029.csv.gz  in=379,322,911 out=126,659,780 elapsed=533.9s

  [12185/13157] intraday_9026.csv.gz  in=379,334,284 out=126,671,153 elapsed=533.9s

  [12186/13157] intraday_9027.csv.gz  in=379,347,113 out=126,683,982 elapsed=533.9s

  [12187/13157] intraday_9028.csv.gz  in=379,361,418 out=126,698,287 elapsed=533.9s

  [12188/13157] intraday_9030.csv.gz  in=379,372,237 out=126,709,106 elapsed=534.1s

  [12189/13157] intraday_9033.csv.gz  in=379,385,312 out=126,722,181 elapsed=534.1s

  [12190/13157] intraday_9031.csv.gz  in=379,395,989 out=126,732,858 elapsed=534.1s

  [12191/13157] intraday_9032.csv.gz  in=379,408,833 out=126,745,702 elapsed=534.1s

  [12192/13157] intraday_9034.csv.gz  in=379,419,964 out=126,756,833 elapsed=534.1s

  [12193/13157] intraday_9035.csv.gz  in=379,432,919 out=126,769,788 elapsed=534.1s

  [12194/13157] intraday_9037.csv.gz  in=379,443,096 out=126,779,965 elapsed=534.1s

  [12195/13157] intraday_9036.csv.gz  in=379,455,903 out=126,792,772 elapsed=534.1s

  [12196/13157] intraday_9038.csv.gz  in=379,469,904 out=126,806,773 elapsed=534.2s

  [12197/13157] intraday_9041.csv.gz  in=379,483,198 out=126,820,067 elapsed=534.2s

  [12198/13157] intraday_9040.csv.gz  in=379,494,896 out=126,831,765 elapsed=534.2s

  [12199/13157] intraday_9039.csv.gz  in=379,509,674 out=126,846,543 elapsed=534.2s

  [12200/13157] intraday_9045.csv.gz  in=379,522,186 out=126,859,055 elapsed=534.3s

  [12201/13157] intraday_9042.csv.gz  in=379,533,746 out=126,870,615 elapsed=534.3s

  [12202/13157] intraday_9043.csv.gz  in=379,543,109 out=126,879,978 elapsed=534.3s

  [12203/13157] intraday_9044.csv.gz  in=379,556,034 out=126,892,903 elapsed=534.3s

  [12204/13157] intraday_9048.csv.gz  in=379,569,118 out=126,905,987 elapsed=534.4s

  [12205/13157] intraday_9047.csv.gz  in=379,581,625 out=126,918,494 elapsed=534.4s

  [12206/13157] intraday_9046.csv.gz  in=379,594,581 out=126,931,450 elapsed=534.4s

  [12207/13157] intraday_9049.csv.gz  in=379,605,884 out=126,942,753 elapsed=534.4s

  [12208/13157] intraday_9051.csv.gz  in=379,618,745 out=126,955,614 elapsed=534.5s

  [12209/13157] intraday_9052.csv.gz  in=379,629,043 out=126,965,912 elapsed=534.5s

  [12210/13157] intraday_9053.csv.gz  in=379,641,172 out=126,978,041 elapsed=534.5s

  [12211/13157] intraday_9050.csv.gz  in=379,653,893 out=126,990,762 elapsed=534.5s

  [12212/13157] intraday_9054.csv.gz  in=379,662,801 out=126,999,670 elapsed=534.5s

  [12213/13157] intraday_9057.csv.gz  in=379,678,924 out=127,015,793 elapsed=534.6s

  [12214/13157] intraday_9056.csv.gz  in=379,691,120 out=127,027,989 elapsed=534.6s

  [12215/13157] intraday_9058.csv.gz  in=379,706,419 out=127,043,288 elapsed=534.6s

  [12216/13157] intraday_9055.csv.gz  in=379,717,983 out=127,054,852 elapsed=534.6s

  [12217/13157] intraday_9059.csv.gz  in=379,729,052 out=127,065,921 elapsed=534.7s

  [12218/13157] intraday_9060.csv.gz  in=379,741,584 out=127,078,453 elapsed=534.7s

  [12219/13157] intraday_9062.csv.gz  in=379,753,639 out=127,090,508 elapsed=534.7s

  [12220/13157] intraday_9061.csv.gz  in=379,767,390 out=127,104,259 elapsed=534.7s

  [12221/13157] intraday_9064.csv.gz  in=379,781,075 out=127,117,944 elapsed=534.7s

  [12222/13157] intraday_9063.csv.gz  in=379,795,526 out=127,132,395 elapsed=534.7s

  [12223/13157] intraday_9065.csv.gz  in=379,807,355 out=127,144,224 elapsed=534.7s

  [12224/13157] intraday_9066.csv.gz  in=379,822,020 out=127,158,889 elapsed=534.8s

  [12225/13157] intraday_9067.csv.gz  in=379,834,997 out=127,171,866 elapsed=534.8s

  [12226/13157] intraday_9070.csv.gz  in=379,846,720 out=127,183,589 elapsed=534.9s

  [12227/13157] intraday_9069.csv.gz  in=379,859,784 out=127,196,653 elapsed=534.9s

  [12228/13157] intraday_9068.csv.gz  in=379,872,594 out=127,209,463 elapsed=534.9s

  [12229/13157] intraday_9071.csv.gz  in=379,884,892 out=127,221,761 elapsed=534.9s

  [12230/13157] intraday_9072.csv.gz  in=379,898,624 out=127,235,493 elapsed=534.9s

  [12231/13157] intraday_9073.csv.gz  in=379,910,210 out=127,247,079 elapsed=534.9s

  [12232/13157] intraday_9074.csv.gz  in=379,921,292 out=127,258,161 elapsed=534.9s

  [12233/13157] intraday_9075.csv.gz  in=379,933,785 out=127,270,654 elapsed=535.0s

  [12234/13157] intraday_9076.csv.gz  in=379,949,412 out=127,286,281 elapsed=535.0s

  [12235/13157] intraday_9078.csv.gz  in=379,961,554 out=127,298,423 elapsed=535.0s

  [12236/13157] intraday_9077.csv.gz  in=379,975,377 out=127,312,246 elapsed=535.0s

  [12237/13157] intraday_9079.csv.gz  in=379,987,676 out=127,324,545 elapsed=535.0s

  [12238/13157] intraday_9081.csv.gz  in=379,999,268 out=127,336,137 elapsed=535.1s

  [12239/13157] intraday_9080.csv.gz  in=380,015,363 out=127,352,232 elapsed=535.1s

  [12240/13157] intraday_9082.csv.gz  in=380,028,508 out=127,365,377 elapsed=535.1s

  [12241/13157] intraday_9084.csv.gz  in=380,041,776 out=127,378,645 elapsed=535.2s

  [12242/13157] intraday_9086.csv.gz  in=380,055,325 out=127,392,194 elapsed=535.2s

  [12243/13157] intraday_9087.csv.gz  in=380,067,151 out=127,404,020 elapsed=535.2s

  [12244/13157] intraday_9083.csv.gz  in=380,081,937 out=127,418,806 elapsed=535.2s

  [12245/13157] intraday_9085.csv.gz  in=380,091,998 out=127,428,867 elapsed=535.2s

  [12246/13157] intraday_9088.csv.gz  in=380,104,412 out=127,441,281 elapsed=535.4s

  [12247/13157] intraday_9089.csv.gz  in=380,122,793 out=127,459,662 elapsed=535.4s

  [12248/13157] intraday_9090.csv.gz  in=380,136,167 out=127,473,036 elapsed=535.4s

  [12249/13157] intraday_9091.csv.gz  in=380,156,681 out=127,493,550 elapsed=535.4s

  [12250/13157] intraday_9095.csv.gz  in=380,169,618 out=127,506,487 elapsed=535.6s

  [12251/13157] intraday_9092.csv.gz  in=380,185,732 out=127,522,601 elapsed=535.6s

  [12252/13157] intraday_9093.csv.gz  in=380,198,765 out=127,535,634 elapsed=535.6s

  [12253/13157] intraday_9094.csv.gz  in=380,211,154 out=127,548,023 elapsed=535.6s

  [12254/13157] intraday_9098.csv.gz  in=380,221,046 out=127,557,915 elapsed=535.8s

  [12255/13157] intraday_9096.csv.gz  in=380,231,578 out=127,568,447 elapsed=535.8s

  [12256/13157] intraday_9097.csv.gz  in=380,245,154 out=127,582,023 elapsed=535.8s

  [12257/13157] intraday_9099.csv.gz  in=380,260,042 out=127,596,911 elapsed=535.8s

  [12258/13157] intraday_9100.csv.gz  in=380,273,096 out=127,609,965 elapsed=535.8s

  [12259/13157] intraday_9101.csv.gz  in=380,288,217 out=127,625,086 elapsed=536.0s

  [12260/13157] intraday_9102.csv.gz  in=380,299,356 out=127,636,225 elapsed=536.1s

  [12261/13157] intraday_9104.csv.gz  in=380,312,077 out=127,648,946 elapsed=536.1s

  [12262/13157] intraday_9103.csv.gz  in=380,324,214 out=127,661,083 elapsed=536.1s

  [12263/13157] intraday_9105.csv.gz  in=380,335,601 out=127,672,470 elapsed=536.2s

  [12264/13157] intraday_9106.csv.gz  in=380,347,921 out=127,684,790 elapsed=536.4s

  [12265/13157] intraday_9107.csv.gz  in=380,362,005 out=127,698,874 elapsed=536.4s

  [12266/13157] intraday_9109.csv.gz  in=380,374,870 out=127,711,739 elapsed=536.5s

  [12267/13157] intraday_9108.csv.gz  in=380,390,497 out=127,727,366 elapsed=536.5s

  [12268/13157] intraday_9110.csv.gz  in=380,404,568 out=127,741,437 elapsed=536.5s

  [12269/13157] intraday_9111.csv.gz  in=380,417,222 out=127,754,091 elapsed=536.5s

  [12270/13157] intraday_9114.csv.gz  in=380,428,159 out=127,765,028 elapsed=536.6s

  [12271/13157] intraday_9115.csv.gz  in=380,439,724 out=127,776,593 elapsed=536.6s

  [12272/13157] intraday_9113.csv.gz  in=380,452,841 out=127,789,710 elapsed=536.6s

  [12273/13157] intraday_9112.csv.gz  in=380,466,581 out=127,803,450 elapsed=536.6s

  [12274/13157] intraday_9116.csv.gz  in=380,473,776 out=127,810,645 elapsed=536.6s

  [12275/13157] intraday_9117.csv.gz  in=380,484,980 out=127,821,849 elapsed=536.6s

  [12276/13157] intraday_9118.csv.gz  in=380,490,752 out=127,827,621 elapsed=536.6s

  [12277/13157] intraday_9119.csv.gz  in=380,516,024 out=127,848,020 elapsed=536.7s

  [12278/13157] intraday_9121.csv.gz  in=380,528,360 out=127,860,356 elapsed=536.7s

  [12279/13157] intraday_9122.csv.gz  in=380,541,626 out=127,873,622 elapsed=536.7s

  [12280/13157] intraday_9120.csv.gz  in=380,557,544 out=127,889,540 elapsed=536.7s

  [12281/13157] intraday_9123.csv.gz  in=380,567,455 out=127,899,451 elapsed=536.8s

  [12282/13157] intraday_9124.csv.gz  in=380,579,965 out=127,911,961 elapsed=536.8s

  [12283/13157] intraday_9126.csv.gz  in=380,595,032 out=127,927,028 elapsed=536.8s

  [12284/13157] intraday_9125.csv.gz  in=380,610,509 out=127,942,505 elapsed=536.8s

  [12285/13157] intraday_9128.csv.gz  in=380,623,103 out=127,955,099 elapsed=536.8s

  [12286/13157] intraday_9127.csv.gz  in=380,635,085 out=127,967,081 elapsed=536.8s

  [12287/13157] intraday_9129.csv.gz  in=380,649,794 out=127,981,790 elapsed=536.8s

  [12288/13157] intraday_9130.csv.gz  in=380,664,748 out=127,996,744 elapsed=536.8s

  [12289/13157] intraday_9132.csv.gz  in=380,678,773 out=128,010,769 elapsed=536.9s

  [12290/13157] intraday_9131.csv.gz  in=380,691,267 out=128,023,263 elapsed=536.9s

  [12291/13157] intraday_9133.csv.gz  in=380,705,665 out=128,037,661 elapsed=536.9s

  [12292/13157] intraday_9134.csv.gz  in=380,714,896 out=128,046,892 elapsed=537.0s

  [12293/13157] intraday_9137.csv.gz  in=380,728,003 out=128,059,999 elapsed=537.0s

  [12294/13157] intraday_9135.csv.gz  in=380,739,858 out=128,071,854 elapsed=537.0s

  [12295/13157] intraday_9138.csv.gz  in=380,751,997 out=128,083,993 elapsed=537.0s

  [12296/13157] intraday_9136.csv.gz  in=380,766,506 out=128,098,502 elapsed=537.0s

  [12297/13157] intraday_9140.csv.gz  in=380,777,894 out=128,109,890 elapsed=537.0s

  [12298/13157] intraday_9141.csv.gz  in=380,791,506 out=128,123,502 elapsed=537.1s

  [12299/13157] intraday_9139.csv.gz  in=380,801,909 out=128,133,905 elapsed=537.1s

  [12300/13157] intraday_9142.csv.gz  in=380,814,568 out=128,146,564 elapsed=537.1s

  [12301/13157] intraday_9143.csv.gz  in=380,828,372 out=128,160,368 elapsed=537.1s

  [12302/13157] intraday_9145.csv.gz  in=380,841,043 out=128,173,039 elapsed=537.2s

  [12303/13157] intraday_9144.csv.gz  in=380,856,701 out=128,188,399 elapsed=537.2s

  [12304/13157] intraday_9147.csv.gz  in=380,868,608 out=128,200,306 elapsed=537.2s

  [12305/13157] intraday_9146.csv.gz  in=380,881,374 out=128,213,072 elapsed=537.2s

  [12306/13157] intraday_9148.csv.gz  in=380,892,453 out=128,224,151 elapsed=537.2s

  [12307/13157] intraday_9149.csv.gz  in=380,905,702 out=128,237,400 elapsed=537.2s

  [12308/13157] intraday_9151.csv.gz  in=380,920,781 out=128,252,479 elapsed=537.2s

  [12309/13157] intraday_9150.csv.gz  in=380,937,369 out=128,269,067 elapsed=537.2s

  [12310/13157] intraday_9152.csv.gz  in=380,947,041 out=128,278,739 elapsed=537.3s

  [12311/13157] intraday_9155.csv.gz  in=380,961,567 out=128,293,265 elapsed=537.3s

  [12312/13157] intraday_9154.csv.gz  in=380,974,136 out=128,305,834 elapsed=537.3s

  [12313/13157] intraday_9153.csv.gz  in=380,986,180 out=128,317,878 elapsed=537.3s

  [12314/13157] intraday_9156.csv.gz  in=380,997,369 out=128,329,067 elapsed=537.3s

  [12315/13157] intraday_9157.csv.gz  in=381,009,448 out=128,341,146 elapsed=537.4s

  [12316/13157] intraday_9159.csv.gz  in=381,020,016 out=128,351,714 elapsed=537.4s

  [12317/13157] intraday_9160.csv.gz  in=381,033,346 out=128,364,666 elapsed=537.4s

  [12318/13157] intraday_9158.csv.gz  in=381,049,897 out=128,379,866 elapsed=537.4s

  [12319/13157] intraday_9161.csv.gz  in=381,063,409 out=128,393,378 elapsed=537.4s

  [12320/13157] intraday_9163.csv.gz  in=381,076,202 out=128,406,171 elapsed=537.5s

  [12321/13157] intraday_9162.csv.gz  in=381,087,736 out=128,417,705 elapsed=537.5s

  [12322/13157] intraday_9165.csv.gz  in=381,100,317 out=128,430,286 elapsed=537.5s

  [12323/13157] intraday_9164.csv.gz  in=381,114,378 out=128,444,347 elapsed=537.5s

  [12324/13157] intraday_9166.csv.gz  in=381,127,116 out=128,457,085 elapsed=537.6s

  [12325/13157] intraday_9167.csv.gz  in=381,138,217 out=128,468,186 elapsed=537.7s

  [12326/13157] intraday_9169.csv.gz  in=381,150,832 out=128,480,270 elapsed=538.0s

  [12327/13157] intraday_9170.csv.gz  in=381,162,778 out=128,492,216 elapsed=538.0s

  [12328/13157] intraday_9168.csv.gz  in=381,175,312 out=128,504,750 elapsed=538.0s

  [12329/13157] intraday_9171.csv.gz  in=381,186,337 out=128,515,775 elapsed=538.0s

  [12330/13157] intraday_9172.csv.gz  in=381,199,386 out=128,528,824 elapsed=538.2s

  [12331/13157] intraday_9173.csv.gz  in=381,214,162 out=128,543,600 elapsed=538.2s

  [12332/13157] intraday_9174.csv.gz  in=381,227,854 out=128,557,292 elapsed=538.2s

  [12333/13157] intraday_9175.csv.gz  in=381,241,073 out=128,570,511 elapsed=538.2s

  [12334/13157] intraday_9176.csv.gz  in=381,253,756 out=128,583,194 elapsed=538.4s

  [12335/13157] intraday_9178.csv.gz  in=381,263,268 out=128,592,706 elapsed=538.4s

  [12336/13157] intraday_9177.csv.gz  in=381,275,131 out=128,604,569 elapsed=538.4s

  [12337/13157] intraday_9179.csv.gz  in=381,288,514 out=128,617,952 elapsed=538.4s

  [12338/13157] intraday_9181.csv.gz  in=381,300,844 out=128,630,144 elapsed=538.4s

  [12339/13157] intraday_9180.csv.gz  in=381,314,547 out=128,643,847 elapsed=538.5s

  [12340/13157] intraday_9182.csv.gz  in=381,328,200 out=128,657,500 elapsed=538.5s

  [12341/13157] intraday_9183.csv.gz  in=381,339,917 out=128,669,217 elapsed=538.5s

  [12342/13157] intraday_9184.csv.gz  in=381,350,328 out=128,679,628 elapsed=538.5s

  [12343/13157] intraday_9187.csv.gz  in=381,362,071 out=128,691,371 elapsed=538.5s

  [12344/13157] intraday_9185.csv.gz  in=381,375,546 out=128,704,846 elapsed=538.5s

  [12345/13157] intraday_9186.csv.gz  in=381,390,484 out=128,719,784 elapsed=538.5s

  [12346/13157] intraday_9190.csv.gz  in=381,401,415 out=128,730,715 elapsed=538.6s

  [12347/13157] intraday_9188.csv.gz  in=381,415,482 out=128,744,782 elapsed=538.6s

  [12348/13157] intraday_9189.csv.gz  in=381,427,765 out=128,757,065 elapsed=538.6s

  [12349/13157] intraday_9191.csv.gz  in=381,439,538 out=128,768,838 elapsed=538.6s

  [12350/13157] intraday_9192.csv.gz  in=381,453,162 out=128,782,462 elapsed=538.6s

  [12351/13157] intraday_9195.csv.gz  in=381,464,914 out=128,794,214 elapsed=538.6s

  [12352/13157] intraday_9193.csv.gz  in=381,476,348 out=128,805,648 elapsed=538.6s

  [12353/13157] intraday_9194.csv.gz  in=381,489,938 out=128,819,238 elapsed=538.6s

  [12354/13157] intraday_9197.csv.gz  in=381,501,207 out=128,830,507 elapsed=538.7s

  [12355/13157] intraday_9196.csv.gz  in=381,513,584 out=128,842,884 elapsed=538.7s

  [12356/13157] intraday_9198.csv.gz  in=381,527,629 out=128,856,929 elapsed=538.7s

  [12357/13157] intraday_9199.csv.gz  in=381,538,625 out=128,867,925 elapsed=538.7s

  [12358/13157] intraday_9200.csv.gz  in=381,550,750 out=128,880,050 elapsed=538.8s

  [12359/13157] intraday_9201.csv.gz  in=381,562,009 out=128,891,309 elapsed=538.8s

  [12360/13157] intraday_9202.csv.gz  in=381,572,949 out=128,902,249 elapsed=538.8s

  [12361/13157] intraday_9203.csv.gz  in=381,584,452 out=128,913,752 elapsed=538.8s

  [12362/13157] intraday_9204.csv.gz  in=381,601,294 out=128,930,594 elapsed=538.8s

  [12363/13157] intraday_9207.csv.gz  in=381,611,923 out=128,941,223 elapsed=538.9s

  [12364/13157] intraday_9205.csv.gz  in=381,628,210 out=128,957,510 elapsed=538.9s

  [12365/13157] intraday_9206.csv.gz  in=381,643,702 out=128,972,251 elapsed=538.9s

  [12366/13157] intraday_9208.csv.gz  in=381,655,558 out=128,984,107 elapsed=539.0s

  [12367/13157] intraday_9209.csv.gz  in=381,670,016 out=128,998,565 elapsed=539.0s

  [12368/13157] intraday_9210.csv.gz  in=381,688,312 out=129,015,448 elapsed=539.0s

  [12369/13157] intraday_9211.csv.gz  in=381,704,248 out=129,031,384 elapsed=539.1s

  [12370/13157] intraday_9212.csv.gz  in=381,716,375 out=129,043,511 elapsed=539.1s

  [12371/13157] intraday_9213.csv.gz  in=381,730,070 out=129,057,206 elapsed=539.1s

  [12372/13157] intraday_9214.csv.gz  in=381,742,366 out=129,069,502 elapsed=539.1s

  [12373/13157] intraday_9215.csv.gz  in=381,757,078 out=129,084,214 elapsed=539.1s

  [12374/13157] intraday_9216.csv.gz  in=381,770,854 out=129,097,990 elapsed=539.2s

  [12375/13157] intraday_9219.csv.gz  in=381,782,422 out=129,109,558 elapsed=539.2s

  [12376/13157] intraday_9218.csv.gz  in=381,795,275 out=129,122,411 elapsed=539.2s

  [12377/13157] intraday_9217.csv.gz  in=381,806,498 out=129,133,634 elapsed=539.2s

  [12378/13157] intraday_9221.csv.gz  in=381,819,275 out=129,146,411 elapsed=539.2s

  [12379/13157] intraday_9222.csv.gz  in=381,830,945 out=129,158,081 elapsed=539.2s

  [12380/13157] intraday_9220.csv.gz  in=381,843,694 out=129,170,830 elapsed=539.3s

  [12381/13157] intraday_9223.csv.gz  in=381,858,650 out=129,185,786 elapsed=539.3s

  [12382/13157] intraday_9226.csv.gz  in=381,871,486 out=129,198,622 elapsed=539.3s

  [12383/13157] intraday_9227.csv.gz  in=381,884,683 out=129,211,819 elapsed=539.4s

  [12384/13157] intraday_9224.csv.gz  in=381,900,410 out=129,227,546 elapsed=539.4s

  [12385/13157] intraday_9225.csv.gz  in=381,913,026 out=129,240,162 elapsed=539.4s

  [12386/13157] intraday_9228.csv.gz  in=381,926,584 out=129,253,720 elapsed=539.4s

  [12387/13157] intraday_9229.csv.gz  in=381,939,674 out=129,266,810 elapsed=539.4s

  [12388/13157] intraday_9231.csv.gz  in=381,954,915 out=129,282,051 elapsed=539.4s

  [12389/13157] intraday_9230.csv.gz  in=381,968,897 out=129,296,033 elapsed=539.4s

  [12390/13157] intraday_9232.csv.gz  in=381,980,693 out=129,307,829 elapsed=539.5s

  [12391/13157] intraday_9233.csv.gz  in=381,991,723 out=129,318,859 elapsed=539.5s

  [12392/13157] intraday_9235.csv.gz  in=382,002,795 out=129,329,931 elapsed=539.5s

  [12393/13157] intraday_9234.csv.gz  in=382,017,480 out=129,344,616 elapsed=539.5s

  [12394/13157] intraday_9236.csv.gz  in=382,033,779 out=129,360,915 elapsed=539.5s

  [12395/13157] intraday_9239.csv.gz  in=382,046,669 out=129,373,805 elapsed=539.6s

  [12396/13157] intraday_9237.csv.gz  in=382,062,019 out=129,389,155 elapsed=539.6s

  [12397/13157] intraday_9240.csv.gz  in=382,079,000 out=129,406,136 elapsed=539.6s

  [12398/13157] intraday_9238.csv.gz  in=382,099,503 out=129,426,639 elapsed=539.6s

  [12399/13157] intraday_9242.csv.gz  in=382,113,777 out=129,440,913 elapsed=539.6s

  [12400/13157] intraday_9241.csv.gz  in=382,130,321 out=129,457,070 elapsed=539.6s

  [12401/13157] intraday_9243.csv.gz  in=382,141,594 out=129,468,343 elapsed=539.7s

  [12402/13157] intraday_9245.csv.gz  in=382,153,646 out=129,480,109 elapsed=539.7s

  [12403/13157] intraday_9244.csv.gz  in=382,166,878 out=129,493,341 elapsed=539.7s

  [12404/13157] intraday_9246.csv.gz  in=382,179,932 out=129,506,395 elapsed=539.7s

  [12405/13157] intraday_9247.csv.gz  in=382,193,950 out=129,520,413 elapsed=539.7s

  [12406/13157] intraday_9249.csv.gz  in=382,205,297 out=129,531,760 elapsed=539.8s

  [12407/13157] intraday_9250.csv.gz  in=382,217,279 out=129,543,742 elapsed=539.8s

  [12408/13157] intraday_9248.csv.gz  in=382,234,126 out=129,560,589 elapsed=539.8s

  [12409/13157] intraday_9251.csv.gz  in=382,245,876 out=129,572,339 elapsed=539.8s

  [12410/13157] intraday_9253.csv.gz  in=382,257,998 out=129,584,461 elapsed=539.9s

  [12411/13157] intraday_9255.csv.gz  in=382,273,198 out=129,599,661 elapsed=539.9s

  [12412/13157] intraday_9252.csv.gz  in=382,285,644 out=129,612,107 elapsed=539.9s

  [12413/13157] intraday_9254.csv.gz  in=382,298,540 out=129,625,003 elapsed=539.9s

  [12414/13157] intraday_9256.csv.gz  in=382,311,974 out=129,638,437 elapsed=540.0s

  [12415/13157] intraday_9258.csv.gz  in=382,325,403 out=129,651,866 elapsed=540.0s

  [12416/13157] intraday_9257.csv.gz  in=382,341,747 out=129,668,210 elapsed=540.0s

  [12417/13157] intraday_9259.csv.gz  in=382,352,698 out=129,679,161 elapsed=540.0s

  [12418/13157] intraday_9263.csv.gz  in=382,360,839 out=129,687,302 elapsed=540.1s

  [12419/13157] intraday_9261.csv.gz  in=382,371,625 out=129,698,088 elapsed=540.1s

  [12420/13157] intraday_9260.csv.gz  in=382,385,808 out=129,712,271 elapsed=540.1s

  [12421/13157] intraday_9262.csv.gz  in=382,399,831 out=129,726,294 elapsed=540.1s

  [12422/13157] intraday_9266.csv.gz  in=382,401,113 out=129,727,576 elapsed=540.2s

  [12423/13157] intraday_9264.csv.gz  in=382,409,526 out=129,735,989 elapsed=540.2s

  [12424/13157] intraday_9265.csv.gz  in=382,422,142 out=129,748,605 elapsed=540.2s

  [12425/13157] intraday_9269.csv.gz  in=382,435,055 out=129,761,518 elapsed=540.3s

  [12426/13157] intraday_9270.csv.gz  in=382,447,660 out=129,774,123 elapsed=540.3s

  [12427/13157] intraday_9268.csv.gz  in=382,463,604 out=129,790,067 elapsed=540.3s

  [12428/13157] intraday_9267.csv.gz  in=382,522,879 out=129,835,714 elapsed=540.3s

  [12429/13157] intraday_9271.csv.gz  in=382,533,564 out=129,846,399 elapsed=540.4s

  [12430/13157] intraday_9272.csv.gz  in=382,546,523 out=129,859,358 elapsed=540.4s

  [12431/13157] intraday_9273.csv.gz  in=382,561,306 out=129,874,141 elapsed=540.4s

  [12432/13157] intraday_9274.csv.gz  in=382,576,048 out=129,888,883 elapsed=540.4s

  [12433/13157] intraday_9277.csv.gz  in=382,590,584 out=129,903,419 elapsed=540.5s

  [12434/13157] intraday_9276.csv.gz  in=382,602,843 out=129,915,678 elapsed=540.5s

  [12435/13157] intraday_9275.csv.gz  in=382,615,898 out=129,928,102 elapsed=540.5s

  [12436/13157] intraday_9278.csv.gz  in=382,630,425 out=129,942,629 elapsed=540.5s

  [12437/13157] intraday_9279.csv.gz  in=382,643,877 out=129,956,081 elapsed=540.5s

  [12438/13157] intraday_9281.csv.gz  in=382,657,926 out=129,970,130 elapsed=540.5s

  [12439/13157] intraday_9280.csv.gz  in=382,671,511 out=129,983,715 elapsed=540.5s

  [12440/13157] intraday_9282.csv.gz  in=382,681,968 out=129,994,172 elapsed=540.6s

  [12441/13157] intraday_9283.csv.gz  in=382,692,506 out=130,004,710 elapsed=540.6s

  [12442/13157] intraday_9285.csv.gz  in=382,705,808 out=130,018,012 elapsed=540.6s

  [12443/13157] intraday_9284.csv.gz  in=382,719,371 out=130,031,575 elapsed=540.6s

  [12444/13157] intraday_9286.csv.gz  in=382,732,253 out=130,044,457 elapsed=540.7s

  [12445/13157] intraday_9289.csv.gz  in=382,745,983 out=130,058,187 elapsed=540.7s

  [12446/13157] intraday_9288.csv.gz  in=382,757,422 out=130,069,626 elapsed=540.7s

  [12447/13157] intraday_9287.csv.gz  in=382,768,712 out=130,080,916 elapsed=540.7s

  [12448/13157] intraday_9291.csv.gz  in=382,782,948 out=130,095,152 elapsed=540.7s

  [12449/13157] intraday_9290.csv.gz  in=382,795,755 out=130,107,959 elapsed=540.7s

  [12450/13157] intraday_9292.csv.gz  in=382,809,726 out=130,121,930 elapsed=540.8s

  [12451/13157] intraday_9293.csv.gz  in=382,822,382 out=130,134,586 elapsed=540.8s

  [12452/13157] intraday_9294.csv.gz  in=382,835,171 out=130,147,375 elapsed=540.8s

  [12453/13157] intraday_9296.csv.gz  in=382,846,534 out=130,158,738 elapsed=540.8s

  [12454/13157] intraday_9295.csv.gz  in=382,858,562 out=130,170,766 elapsed=540.8s

  [12455/13157] intraday_9297.csv.gz  in=382,872,036 out=130,184,240 elapsed=540.8s

  [12456/13157] intraday_9298.csv.gz  in=382,887,548 out=130,199,752 elapsed=540.9s

  [12457/13157] intraday_9299.csv.gz  in=382,901,136 out=130,213,340 elapsed=540.9s

  [12458/13157] intraday_9300.csv.gz  in=382,912,327 out=130,224,531 elapsed=540.9s

  [12459/13157] intraday_9301.csv.gz  in=382,924,568 out=130,236,772 elapsed=540.9s

  [12460/13157] intraday_9302.csv.gz  in=382,937,613 out=130,249,817 elapsed=540.9s

  [12461/13157] intraday_9303.csv.gz  in=382,949,444 out=130,261,648 elapsed=540.9s

  [12462/13157] intraday_9304.csv.gz  in=382,961,484 out=130,273,688 elapsed=540.9s

  [12463/13157] intraday_9305.csv.gz  in=382,973,197 out=130,285,401 elapsed=541.0s

  [12464/13157] intraday_9307.csv.gz  in=382,984,231 out=130,296,435 elapsed=541.0s

  [12465/13157] intraday_9308.csv.gz  in=382,996,336 out=130,308,540 elapsed=541.0s

  [12466/13157] intraday_9306.csv.gz  in=383,008,583 out=130,320,787 elapsed=541.0s

  [12467/13157] intraday_9310.csv.gz  in=383,022,070 out=130,334,274 elapsed=541.0s

  [12468/13157] intraday_9312.csv.gz  in=383,035,740 out=130,347,944 elapsed=541.0s

  [12469/13157] intraday_9309.csv.gz  in=383,048,584 out=130,360,788 elapsed=541.0s

  [12470/13157] intraday_9311.csv.gz  in=383,062,207 out=130,374,411 elapsed=541.0s

  [12471/13157] intraday_9313.csv.gz  in=383,073,452 out=130,385,656 elapsed=541.1s

  [12472/13157] intraday_9314.csv.gz  in=383,085,726 out=130,397,930 elapsed=541.1s

  [12473/13157] intraday_9316.csv.gz  in=383,097,192 out=130,409,396 elapsed=541.2s

  [12474/13157] intraday_9315.csv.gz  in=383,110,514 out=130,422,718 elapsed=541.2s

  [12475/13157] intraday_9317.csv.gz  in=383,123,087 out=130,435,291 elapsed=541.3s

  [12476/13157] intraday_9318.csv.gz  in=383,134,664 out=130,446,868 elapsed=541.3s

  [12477/13157] intraday_9321.csv.gz  in=383,146,217 out=130,458,421 elapsed=541.3s

  [12478/13157] intraday_9320.csv.gz  in=383,163,530 out=130,475,734 elapsed=541.4s

  [12479/13157] intraday_9319.csv.gz  in=383,174,275 out=130,486,479 elapsed=541.4s

  [12480/13157] intraday_9322.csv.gz  in=383,187,198 out=130,499,402 elapsed=541.5s

  [12481/13157] intraday_9324.csv.gz  in=383,200,115 out=130,512,319 elapsed=541.5s

  [12482/13157] intraday_9323.csv.gz  in=383,213,029 out=130,525,233 elapsed=541.5s

  [12483/13157] intraday_9325.csv.gz  in=383,224,528 out=130,536,732 elapsed=541.5s

  [12484/13157] intraday_9326.csv.gz  in=383,235,904 out=130,548,108 elapsed=541.9s

  [12485/13157] intraday_9327.csv.gz  in=383,249,425 out=130,561,629 elapsed=542.0s

  [12486/13157] intraday_9328.csv.gz  in=383,262,488 out=130,574,692 elapsed=542.0s

  [12487/13157] intraday_9329.csv.gz  in=383,274,113 out=130,586,317 elapsed=542.1s

  [12488/13157] intraday_9330.csv.gz  in=383,287,587 out=130,599,791 elapsed=542.1s

  [12489/13157] intraday_9331.csv.gz  in=383,299,818 out=130,612,022 elapsed=542.2s

  [12490/13157] intraday_9333.csv.gz  in=383,314,941 out=130,627,145 elapsed=542.2s

  [12491/13157] intraday_9332.csv.gz  in=383,325,554 out=130,637,758 elapsed=542.2s

  [12492/13157] intraday_9334.csv.gz  in=383,338,548 out=130,650,752 elapsed=542.2s

  [12493/13157] intraday_9335.csv.gz  in=383,352,127 out=130,664,331 elapsed=542.2s

  [12494/13157] intraday_9336.csv.gz  in=383,364,775 out=130,676,979 elapsed=542.3s

  [12495/13157] intraday_9337.csv.gz  in=383,377,038 out=130,689,242 elapsed=542.3s

  [12496/13157] intraday_9338.csv.gz  in=383,387,273 out=130,699,477 elapsed=542.4s

  [12497/13157] intraday_9339.csv.gz  in=383,398,641 out=130,710,845 elapsed=542.4s

  [12498/13157] intraday_9342.csv.gz  in=383,410,762 out=130,722,966 elapsed=542.4s

  [12499/13157] intraday_9341.csv.gz  in=383,424,318 out=130,736,522 elapsed=542.4s

  [12500/13157] intraday_9340.csv.gz  in=383,437,380 out=130,749,584 elapsed=542.4s

  [12501/13157] intraday_9343.csv.gz  in=383,450,158 out=130,762,362 elapsed=542.4s

  [12502/13157] intraday_9344.csv.gz  in=383,461,050 out=130,773,254 elapsed=542.5s

  [12503/13157] intraday_9345.csv.gz  in=383,474,549 out=130,786,753 elapsed=542.5s

  [12504/13157] intraday_9346.csv.gz  in=383,486,654 out=130,798,858 elapsed=542.5s

  [12505/13157] intraday_9347.csv.gz  in=383,497,899 out=130,810,103 elapsed=542.5s

  [12506/13157] intraday_9348.csv.gz  in=383,510,223 out=130,822,427 elapsed=542.5s

  [12507/13157] intraday_9349.csv.gz  in=383,519,456 out=130,831,660 elapsed=542.6s

  [12508/13157] intraday_9351.csv.gz  in=383,532,751 out=130,844,955 elapsed=542.6s

  [12509/13157] intraday_9352.csv.gz  in=383,547,924 out=130,860,128 elapsed=542.6s

  [12510/13157] intraday_9350.csv.gz  in=383,560,552 out=130,872,756 elapsed=542.6s

  [12511/13157] intraday_9356.csv.gz  in=383,575,059 out=130,887,263 elapsed=542.7s

  [12512/13157] intraday_9355.csv.gz  in=383,587,130 out=130,899,334 elapsed=542.7s

  [12513/13157] intraday_9354.csv.gz  in=383,599,866 out=130,912,070 elapsed=542.7s

  [12514/13157] intraday_9353.csv.gz  in=383,614,519 out=130,926,723 elapsed=542.7s

  [12515/13157] intraday_9357.csv.gz  in=383,625,420 out=130,937,624 elapsed=542.7s

  [12516/13157] intraday_9359.csv.gz  in=383,637,767 out=130,949,971 elapsed=542.7s

  [12517/13157] intraday_9358.csv.gz  in=383,654,523 out=130,966,727 elapsed=542.7s

  [12518/13157] intraday_9360.csv.gz  in=383,667,723 out=130,979,927 elapsed=542.8s

  [12519/13157] intraday_9361.csv.gz  in=383,681,394 out=130,993,598 elapsed=542.8s

  [12520/13157] intraday_9362.csv.gz  in=383,694,153 out=131,006,357 elapsed=542.9s

  [12521/13157] intraday_9363.csv.gz  in=383,707,397 out=131,019,601 elapsed=542.9s

  [12522/13157] intraday_9364.csv.gz  in=383,720,169 out=131,032,373 elapsed=542.9s

  [12523/13157] intraday_9365.csv.gz  in=383,732,686 out=131,044,890 elapsed=542.9s

  [12524/13157] intraday_9366.csv.gz  in=383,745,372 out=131,057,576 elapsed=543.4s

  [12525/13157] intraday_9369.csv.gz  in=383,756,407 out=131,068,611 elapsed=543.5s

  [12526/13157] intraday_9367.csv.gz  in=383,768,907 out=131,081,111 elapsed=543.5s

  [12527/13157] intraday_9368.csv.gz  in=383,781,971 out=131,094,175 elapsed=543.5s

  [12528/13157] intraday_9370.csv.gz  in=383,794,465 out=131,106,669 elapsed=543.6s

  [12529/13157] intraday_9372.csv.gz  in=383,807,479 out=131,119,683 elapsed=543.6s

  [12530/13157] intraday_9373.csv.gz  in=383,820,837 out=131,133,041 elapsed=543.6s

  [12531/13157] intraday_9374.csv.gz  in=383,832,910 out=131,145,114 elapsed=543.6s

  [12532/13157] intraday_9371.csv.gz  in=383,849,940 out=131,162,144 elapsed=543.6s

  [12533/13157] intraday_9376.csv.gz  in=383,862,408 out=131,174,612 elapsed=543.7s

  [12534/13157] intraday_9375.csv.gz  in=383,876,921 out=131,189,125 elapsed=543.7s

  [12535/13157] intraday_9377.csv.gz  in=383,889,901 out=131,202,105 elapsed=543.7s

  [12536/13157] intraday_9380.csv.gz  in=383,900,522 out=131,212,726 elapsed=543.7s

  [12537/13157] intraday_9379.csv.gz  in=383,914,054 out=131,226,258 elapsed=543.7s

  [12538/13157] intraday_9378.csv.gz  in=383,928,944 out=131,241,148 elapsed=543.7s

  [12539/13157] intraday_9381.csv.gz  in=383,942,441 out=131,254,645 elapsed=543.8s

  [12540/13157] intraday_9383.csv.gz  in=383,956,160 out=131,268,364 elapsed=543.8s

  [12541/13157] intraday_9382.csv.gz  in=383,968,969 out=131,281,173 elapsed=543.8s

  [12542/13157] intraday_9384.csv.gz  in=383,985,234 out=131,297,438 elapsed=543.8s

  [12543/13157] intraday_9388.csv.gz  in=383,997,374 out=131,309,578 elapsed=543.9s

  [12544/13157] intraday_9385.csv.gz  in=384,012,070 out=131,324,274 elapsed=543.9s

  [12545/13157] intraday_9387.csv.gz  in=384,027,252 out=131,339,456 elapsed=543.9s

  [12546/13157] intraday_9386.csv.gz  in=384,045,300 out=131,357,504 elapsed=543.9s

  [12547/13157] intraday_9392.csv.gz  in=384,058,746 out=131,370,950 elapsed=544.0s

  [12548/13157] intraday_9389.csv.gz  in=384,071,386 out=131,383,590 elapsed=544.0s

  [12549/13157] intraday_9391.csv.gz  in=384,082,399 out=131,394,603 elapsed=544.0s

  [12550/13157] intraday_9390.csv.gz  in=384,094,955 out=131,407,159 elapsed=544.0s

  [12551/13157] intraday_9393.csv.gz  in=384,105,309 out=131,417,513 elapsed=544.0s

  [12552/13157] intraday_9394.csv.gz  in=384,119,918 out=131,432,122 elapsed=544.1s

  [12553/13157] intraday_9397.csv.gz  in=384,131,488 out=131,443,692 elapsed=544.1s

  [12554/13157] intraday_9396.csv.gz  in=384,146,480 out=131,458,684 elapsed=544.1s

  [12555/13157] intraday_9395.csv.gz  in=384,160,078 out=131,472,282 elapsed=544.1s

  [12556/13157] intraday_9398.csv.gz  in=384,170,841 out=131,483,045 elapsed=544.1s

  [12557/13157] intraday_9399.csv.gz  in=384,184,453 out=131,496,657 elapsed=544.2s

  [12558/13157] intraday_9401.csv.gz  in=384,196,819 out=131,509,023 elapsed=544.2s

  [12559/13157] intraday_9400.csv.gz  in=384,208,282 out=131,520,486 elapsed=544.2s

  [12560/13157] intraday_9402.csv.gz  in=384,223,154 out=131,535,358 elapsed=544.2s

  [12561/13157] intraday_9403.csv.gz  in=384,238,102 out=131,550,306 elapsed=544.3s

  [12562/13157] intraday_9404.csv.gz  in=384,251,443 out=131,563,647 elapsed=544.3s

  [12563/13157] intraday_9405.csv.gz  in=384,266,181 out=131,578,385 elapsed=544.3s

  [12564/13157] intraday_9406.csv.gz  in=384,278,783 out=131,590,987 elapsed=544.4s

  [12565/13157] intraday_9408.csv.gz  in=384,291,052 out=131,603,256 elapsed=544.4s

  [12566/13157] intraday_9407.csv.gz  in=384,304,548 out=131,616,752 elapsed=544.5s

  [12567/13157] intraday_9410.csv.gz  in=384,314,281 out=131,626,485 elapsed=544.5s

  [12568/13157] intraday_9409.csv.gz  in=384,327,132 out=131,639,336 elapsed=544.5s

  [12569/13157] intraday_9412.csv.gz  in=384,337,522 out=131,649,726 elapsed=544.5s

  [12570/13157] intraday_9411.csv.gz  in=384,345,755 out=131,657,959 elapsed=544.5s

  [12571/13157] intraday_9413.csv.gz  in=384,350,809 out=131,663,013 elapsed=544.5s

  [12572/13157] intraday_9416.csv.gz  in=384,363,746 out=131,675,950 elapsed=544.5s

  [12573/13157] intraday_9417.csv.gz  in=384,374,494 out=131,686,698 elapsed=544.6s

  [12574/13157] intraday_9415.csv.gz  in=384,390,578 out=131,702,782 elapsed=544.6s

  [12575/13157] intraday_9414.csv.gz  in=384,418,936 out=131,725,932 elapsed=544.6s

  [12576/13157] intraday_9418.csv.gz  in=384,429,708 out=131,736,704 elapsed=544.7s

  [12577/13157] intraday_9419.csv.gz  in=384,441,969 out=131,748,965 elapsed=544.7s

  [12578/13157] intraday_9421.csv.gz  in=384,455,995 out=131,762,991 elapsed=544.7s

  [12579/13157] intraday_9420.csv.gz  in=384,471,477 out=131,778,473 elapsed=544.7s

  [12580/13157] intraday_9422.csv.gz  in=384,483,880 out=131,790,876 elapsed=544.8s

  [12581/13157] intraday_9423.csv.gz  in=384,495,756 out=131,802,752 elapsed=544.8s

  [12582/13157] intraday_9424.csv.gz  in=384,510,383 out=131,817,379 elapsed=544.8s

  [12583/13157] intraday_9425.csv.gz  in=384,525,063 out=131,832,059 elapsed=544.8s

  [12584/13157] intraday_9426.csv.gz  in=384,536,806 out=131,843,802 elapsed=545.0s

  [12585/13157] intraday_9427.csv.gz  in=384,551,240 out=131,858,236 elapsed=545.0s

  [12586/13157] intraday_9429.csv.gz  in=384,562,048 out=131,869,044 elapsed=545.0s

  [12587/13157] intraday_9428.csv.gz  in=384,575,562 out=131,882,558 elapsed=545.0s

  [12588/13157] intraday_9430.csv.gz  in=384,586,871 out=131,893,867 elapsed=545.0s

  [12589/13157] intraday_9432.csv.gz  in=384,599,227 out=131,906,223 elapsed=545.0s

  [12590/13157] intraday_9433.csv.gz  in=384,611,630 out=131,918,626 elapsed=545.1s

  [12591/13157] intraday_9431.csv.gz  in=384,624,836 out=131,931,832 elapsed=545.1s

  [12592/13157] intraday_9435.csv.gz  in=384,636,481 out=131,943,477 elapsed=545.1s

  [12593/13157] intraday_9436.csv.gz  in=384,648,935 out=131,955,931 elapsed=545.1s

  [12594/13157] intraday_9434.csv.gz  in=384,660,283 out=131,967,279 elapsed=545.1s

  [12595/13157] intraday_9437.csv.gz  in=384,673,055 out=131,980,051 elapsed=545.1s

  [12596/13157] intraday_9438.csv.gz  in=384,685,320 out=131,992,316 elapsed=545.2s

  [12597/13157] intraday_9440.csv.gz  in=384,697,588 out=132,004,584 elapsed=545.2s

  [12598/13157] intraday_9441.csv.gz  in=384,709,164 out=132,016,160 elapsed=545.2s

  [12599/13157] intraday_9439.csv.gz  in=384,723,180 out=132,030,176 elapsed=545.2s

  [12600/13157] intraday_9442.csv.gz  in=384,734,815 out=132,041,811 elapsed=545.2s

  [12601/13157] intraday_9443.csv.gz  in=384,746,418 out=132,053,414 elapsed=545.2s

  [12602/13157] intraday_9444.csv.gz  in=384,758,908 out=132,065,904 elapsed=545.3s

  [12603/13157] intraday_9446.csv.gz  in=384,772,128 out=132,079,124 elapsed=545.3s

  [12604/13157] intraday_9445.csv.gz  in=384,787,121 out=132,094,117 elapsed=545.3s

  [12605/13157] intraday_9447.csv.gz  in=384,797,365 out=132,104,361 elapsed=545.3s

  [12606/13157] intraday_9448.csv.gz  in=384,809,188 out=132,116,184 elapsed=545.3s

  [12607/13157] intraday_9449.csv.gz  in=384,821,441 out=132,128,437 elapsed=545.3s

  [12608/13157] intraday_9451.csv.gz  in=384,833,295 out=132,140,291 elapsed=545.4s

  [12609/13157] intraday_9453.csv.gz  in=384,844,457 out=132,151,453 elapsed=545.4s

  [12610/13157] intraday_9452.csv.gz  in=384,856,780 out=132,163,776 elapsed=545.4s

  [12611/13157] intraday_9450.csv.gz  in=384,869,392 out=132,176,388 elapsed=545.4s

  [12612/13157] intraday_9454.csv.gz  in=384,880,002 out=132,186,998 elapsed=545.4s

  [12613/13157] intraday_9455.csv.gz  in=384,891,796 out=132,198,792 elapsed=545.4s

  [12614/13157] intraday_9456.csv.gz  in=384,904,279 out=132,211,275 elapsed=545.4s

  [12615/13157] intraday_9457.csv.gz  in=384,916,593 out=132,223,589 elapsed=545.5s

  [12616/13157] intraday_9459.csv.gz  in=384,930,185 out=132,237,181 elapsed=545.5s

  [12617/13157] intraday_9458.csv.gz  in=384,943,455 out=132,250,451 elapsed=545.5s

  [12618/13157] intraday_9460.csv.gz  in=384,954,964 out=132,261,960 elapsed=545.5s

  [12619/13157] intraday_9464.csv.gz  in=384,965,210 out=132,272,007 elapsed=545.5s

  [12620/13157] intraday_9462.csv.gz  in=384,977,136 out=132,283,933 elapsed=545.6s

  [12621/13157] intraday_9461.csv.gz  in=384,989,523 out=132,296,320 elapsed=545.6s

  [12622/13157] intraday_9463.csv.gz  in=385,003,055 out=132,309,852 elapsed=545.6s

  [12623/13157] intraday_9466.csv.gz  in=385,014,002 out=132,320,799 elapsed=545.6s

  [12624/13157] intraday_9468.csv.gz  in=385,026,363 out=132,333,160 elapsed=545.6s

  [12625/13157] intraday_9465.csv.gz  in=385,038,980 out=132,345,777 elapsed=545.7s

  [12626/13157] intraday_9467.csv.gz  in=385,051,878 out=132,358,675 elapsed=545.7s

  [12627/13157] intraday_9469.csv.gz  in=385,065,123 out=132,371,920 elapsed=545.7s

  [12628/13157] intraday_9470.csv.gz  in=385,079,370 out=132,386,167 elapsed=545.8s

  [12629/13157] intraday_9472.csv.gz  in=385,090,850 out=132,397,647 elapsed=545.8s

  [12630/13157] intraday_9473.csv.gz  in=385,101,099 out=132,407,896 elapsed=545.8s

  [12631/13157] intraday_9471.csv.gz  in=385,112,657 out=132,419,454 elapsed=545.8s

  [12632/13157] intraday_9474.csv.gz  in=385,125,671 out=132,432,468 elapsed=545.8s

  [12633/13157] intraday_9475.csv.gz  in=385,138,046 out=132,444,843 elapsed=545.8s

  [12634/13157] intraday_9477.csv.gz  in=385,151,370 out=132,458,167 elapsed=545.8s

  [12635/13157] intraday_9476.csv.gz  in=385,163,228 out=132,470,025 elapsed=545.8s

  [12636/13157] intraday_9478.csv.gz  in=385,176,251 out=132,483,048 elapsed=545.9s

  [12637/13157] intraday_9479.csv.gz  in=385,186,798 out=132,493,595 elapsed=545.9s

  [12638/13157] intraday_9480.csv.gz  in=385,200,880 out=132,507,677 elapsed=545.9s

  [12639/13157] intraday_9481.csv.gz  in=385,217,063 out=132,523,860 elapsed=545.9s

  [12640/13157] intraday_9484.csv.gz  in=385,228,440 out=132,535,237 elapsed=545.9s

  [12641/13157] intraday_9483.csv.gz  in=385,242,948 out=132,549,745 elapsed=545.9s

  [12642/13157] intraday_9482.csv.gz  in=385,253,447 out=132,560,244 elapsed=545.9s

  [12643/13157] intraday_9486.csv.gz  in=385,265,929 out=132,572,726 elapsed=546.1s

  [12644/13157] intraday_9485.csv.gz  in=385,276,272 out=132,583,069 elapsed=546.1s

  [12645/13157] intraday_9487.csv.gz  in=385,289,339 out=132,596,136 elapsed=546.1s

  [12646/13157] intraday_9488.csv.gz  in=385,302,318 out=132,609,115 elapsed=546.1s

  [12647/13157] intraday_9491.csv.gz  in=385,311,948 out=132,618,745 elapsed=546.2s

  [12648/13157] intraday_9489.csv.gz  in=385,324,511 out=132,631,308 elapsed=546.2s

  [12649/13157] intraday_9490.csv.gz  in=385,337,112 out=132,643,909 elapsed=546.2s

  [12650/13157] intraday_9492.csv.gz  in=385,349,064 out=132,655,861 elapsed=546.2s

  [12651/13157] intraday_9496.csv.gz  in=385,359,963 out=132,666,760 elapsed=546.3s

  [12652/13157] intraday_9494.csv.gz  in=385,371,368 out=132,678,165 elapsed=546.3s

  [12653/13157] intraday_9493.csv.gz  in=385,384,501 out=132,691,298 elapsed=546.3s

  [12654/13157] intraday_9495.csv.gz  in=385,396,220 out=132,703,017 elapsed=546.3s

  [12655/13157] intraday_9497.csv.gz  in=385,407,779 out=132,714,576 elapsed=546.4s

  [12656/13157] intraday_9498.csv.gz  in=385,420,184 out=132,726,981 elapsed=546.4s

  [12657/13157] intraday_9500.csv.gz  in=385,436,125 out=132,742,922 elapsed=546.4s

  [12658/13157] intraday_9499.csv.gz  in=385,451,904 out=132,758,701 elapsed=546.4s

  [12659/13157] intraday_9502.csv.gz  in=385,464,414 out=132,771,211 elapsed=546.5s

  [12660/13157] intraday_9501.csv.gz  in=385,475,589 out=132,782,386 elapsed=546.5s

  [12661/13157] intraday_9504.csv.gz  in=385,488,759 out=132,795,556 elapsed=546.5s

  [12662/13157] intraday_9503.csv.gz  in=385,501,489 out=132,808,286 elapsed=546.5s

  [12663/13157] intraday_9505.csv.gz  in=385,517,107 out=132,823,904 elapsed=546.5s

  [12664/13157] intraday_9507.csv.gz  in=385,529,321 out=132,836,118 elapsed=546.6s

  [12665/13157] intraday_9506.csv.gz  in=385,541,223 out=132,848,020 elapsed=546.6s

  [12666/13157] intraday_9508.csv.gz  in=385,554,975 out=132,861,772 elapsed=546.6s

  [12667/13157] intraday_9509.csv.gz  in=385,568,408 out=132,875,205 elapsed=546.6s

  [12668/13157] intraday_9510.csv.gz  in=385,581,409 out=132,888,206 elapsed=546.6s

  [12669/13157] intraday_9511.csv.gz  in=385,593,974 out=132,900,771 elapsed=546.6s

  [12670/13157] intraday_9512.csv.gz  in=385,606,980 out=132,913,777 elapsed=546.6s

  [12671/13157] intraday_9513.csv.gz  in=385,619,908 out=132,926,705 elapsed=546.6s

  [12672/13157] intraday_9515.csv.gz  in=385,630,492 out=132,937,289 elapsed=546.7s

  [12673/13157] intraday_9517.csv.gz  in=385,644,277 out=132,951,074 elapsed=546.7s

  [12674/13157] intraday_9514.csv.gz  in=385,657,655 out=132,964,452 elapsed=546.7s

  [12675/13157] intraday_9516.csv.gz  in=385,670,148 out=132,976,945 elapsed=546.7s

  [12676/13157] intraday_9518.csv.gz  in=385,684,571 out=132,991,368 elapsed=546.8s

  [12677/13157] intraday_9520.csv.gz  in=385,696,740 out=133,003,537 elapsed=546.8s

  [12678/13157] intraday_9521.csv.gz  in=385,709,756 out=133,016,553 elapsed=546.8s

  [12679/13157] intraday_9519.csv.gz  in=385,723,047 out=133,029,844 elapsed=546.8s

  [12680/13157] intraday_9523.csv.gz  in=385,734,995 out=133,041,792 elapsed=546.8s

  [12681/13157] intraday_9522.csv.gz  in=385,750,239 out=133,057,036 elapsed=546.8s

  [12682/13157] intraday_9525.csv.gz  in=385,765,358 out=133,072,155 elapsed=546.9s

  [12683/13157] intraday_9524.csv.gz  in=385,777,640 out=133,084,437 elapsed=546.9s

  [12684/13157] intraday_9526.csv.gz  in=385,792,636 out=133,099,433 elapsed=546.9s

  [12685/13157] intraday_9527.csv.gz  in=385,801,989 out=133,108,786 elapsed=547.2s

  [12686/13157] intraday_9530.csv.gz  in=385,813,955 out=133,120,752 elapsed=547.3s

  [12687/13157] intraday_9528.csv.gz  in=385,826,877 out=133,133,674 elapsed=547.3s

  [12688/13157] intraday_9529.csv.gz  in=385,840,511 out=133,147,308 elapsed=547.3s

  [12689/13157] intraday_9531.csv.gz  in=385,854,242 out=133,161,039 elapsed=548.1s

  [12690/13157] intraday_9532.csv.gz  in=385,869,719 out=133,176,516 elapsed=548.1s

  [12691/13157] intraday_9533.csv.gz  in=385,887,937 out=133,194,734 elapsed=548.2s

  [12692/13157] intraday_9534.csv.gz  in=385,903,456 out=133,210,253 elapsed=548.2s

  [12693/13157] intraday_9535.csv.gz  in=385,916,890 out=133,223,687 elapsed=548.2s

  [12694/13157] intraday_9536.csv.gz  in=385,928,843 out=133,235,640 elapsed=548.2s

  [12695/13157] intraday_9538.csv.gz  in=385,938,961 out=133,245,758 elapsed=548.3s

  [12696/13157] intraday_9540.csv.gz  in=385,949,714 out=133,256,511 elapsed=548.3s

  [12697/13157] intraday_9537.csv.gz  in=385,962,597 out=133,269,394 elapsed=548.3s

  [12698/13157] intraday_9539.csv.gz  in=385,976,368 out=133,283,165 elapsed=548.3s

  [12699/13157] intraday_9541.csv.gz  in=385,989,633 out=133,296,430 elapsed=548.4s

  [12700/13157] intraday_9542.csv.gz  in=386,002,385 out=133,309,182 elapsed=548.4s

  [12701/13157] intraday_9543.csv.gz  in=386,018,118 out=133,324,915 elapsed=548.4s

  [12702/13157] intraday_9544.csv.gz  in=386,029,152 out=133,335,949 elapsed=548.4s

  [12703/13157] intraday_9546.csv.gz  in=386,040,655 out=133,347,452 elapsed=548.4s

  [12704/13157] intraday_9547.csv.gz  in=386,053,071 out=133,359,868 elapsed=548.4s

  [12705/13157] intraday_9545.csv.gz  in=386,065,298 out=133,372,095 elapsed=548.4s

  [12706/13157] intraday_9548.csv.gz  in=386,076,556 out=133,383,353 elapsed=548.4s

  [12707/13157] intraday_9549.csv.gz  in=386,090,085 out=133,396,882 elapsed=548.5s

  [12708/13157] intraday_9552.csv.gz  in=386,105,025 out=133,411,822 elapsed=548.5s

  [12709/13157] intraday_9550.csv.gz  in=386,120,046 out=133,426,843 elapsed=548.5s

  [12710/13157] intraday_9551.csv.gz  in=386,133,861 out=133,440,658 elapsed=548.5s

  [12711/13157] intraday_9553.csv.gz  in=386,146,768 out=133,453,565 elapsed=548.5s

  [12712/13157] intraday_9554.csv.gz  in=386,158,623 out=133,465,420 elapsed=548.5s

  [12713/13157] intraday_9555.csv.gz  in=386,172,023 out=133,478,820 elapsed=548.6s

  [12714/13157] intraday_9556.csv.gz  in=386,183,854 out=133,490,651 elapsed=548.6s

  [12715/13157] intraday_9557.csv.gz  in=386,197,556 out=133,504,353 elapsed=548.6s

  [12716/13157] intraday_9559.csv.gz  in=386,207,099 out=133,513,896 elapsed=548.6s

  [12717/13157] intraday_9558.csv.gz  in=386,214,482 out=133,521,279 elapsed=548.6s

  [12718/13157] intraday_9560.csv.gz  in=386,225,447 out=133,532,244 elapsed=548.6s

  [12719/13157] intraday_9561.csv.gz  in=386,241,924 out=133,548,628 elapsed=548.6s

  [12720/13157] intraday_9562.csv.gz  in=386,253,990 out=133,560,694 elapsed=548.7s

  [12721/13157] intraday_9563.csv.gz  in=386,266,540 out=133,573,244 elapsed=548.7s

  [12722/13157] intraday_9566.csv.gz  in=386,280,065 out=133,586,769 elapsed=548.7s

  [12723/13157] intraday_9565.csv.gz  in=386,292,641 out=133,599,345 elapsed=548.7s

  [12724/13157] intraday_9564.csv.gz  in=386,302,683 out=133,609,387 elapsed=548.7s

  [12725/13157] intraday_9569.csv.gz  in=386,315,150 out=133,621,854 elapsed=548.8s

  [12726/13157] intraday_9567.csv.gz  in=386,329,882 out=133,636,586 elapsed=548.8s

  [12727/13157] intraday_9570.csv.gz  in=386,344,283 out=133,650,987 elapsed=548.8s

  [12728/13157] intraday_9568.csv.gz  in=386,356,694 out=133,663,366 elapsed=548.8s

  [12729/13157] intraday_9572.csv.gz  in=386,369,836 out=133,676,508 elapsed=548.9s

  [12730/13157] intraday_9573.csv.gz  in=386,383,339 out=133,690,011 elapsed=548.9s

  [12731/13157] intraday_9571.csv.gz  in=386,396,812 out=133,703,484 elapsed=548.9s

  [12732/13157] intraday_9574.csv.gz  in=386,411,320 out=133,717,992 elapsed=548.9s

  [12733/13157] intraday_9578.csv.gz  in=386,424,048 out=133,730,720 elapsed=548.9s

  [12734/13157] intraday_9577.csv.gz  in=386,437,388 out=133,744,060 elapsed=548.9s

  [12735/13157] intraday_9575.csv.gz  in=386,447,913 out=133,754,585 elapsed=548.9s

  [12736/13157] intraday_9576.csv.gz  in=386,459,012 out=133,765,684 elapsed=548.9s

  [12737/13157] intraday_9579.csv.gz  in=386,470,968 out=133,777,640 elapsed=549.0s

  [12738/13157] intraday_9580.csv.gz  in=386,481,811 out=133,788,483 elapsed=549.0s

  [12739/13157] intraday_9582.csv.gz  in=386,496,623 out=133,803,295 elapsed=549.0s

  [12740/13157] intraday_9581.csv.gz  in=386,508,322 out=133,814,994 elapsed=549.0s

  [12741/13157] intraday_9583.csv.gz  in=386,521,598 out=133,828,270 elapsed=549.0s

  [12742/13157] intraday_9584.csv.gz  in=386,533,824 out=133,840,496 elapsed=549.0s

  [12743/13157] intraday_9585.csv.gz  in=386,546,596 out=133,853,268 elapsed=549.1s

  [12744/13157] intraday_9588.csv.gz  in=386,562,801 out=133,869,410 elapsed=549.1s

  [12745/13157] intraday_9586.csv.gz  in=386,574,936 out=133,881,545 elapsed=549.1s

  [12746/13157] intraday_9587.csv.gz  in=386,591,737 out=133,897,200 elapsed=549.1s

  [12747/13157] intraday_9590.csv.gz  in=386,603,668 out=133,909,131 elapsed=549.2s

  [12748/13157] intraday_9589.csv.gz  in=386,616,160 out=133,921,623 elapsed=549.2s

  [12749/13157] intraday_9592.csv.gz  in=386,629,452 out=133,934,915 elapsed=549.2s

  [12750/13157] intraday_9591.csv.gz  in=386,644,845 out=133,950,308 elapsed=549.2s

  [12751/13157] intraday_9596.csv.gz  in=386,656,842 out=133,962,305 elapsed=549.3s

  [12752/13157] intraday_9593.csv.gz  in=386,667,097 out=133,972,560 elapsed=549.3s

  [12753/13157] intraday_9594.csv.gz  in=386,677,463 out=133,982,926 elapsed=549.3s

  [12754/13157] intraday_9595.csv.gz  in=386,691,071 out=133,996,534 elapsed=549.3s

  [12755/13157] intraday_9599.csv.gz  in=386,702,097 out=134,007,560 elapsed=549.4s

  [12756/13157] intraday_9597.csv.gz  in=386,714,170 out=134,019,633 elapsed=549.4s

  [12757/13157] intraday_9598.csv.gz  in=386,730,013 out=134,034,606 elapsed=549.4s

  [12758/13157] intraday_9600.csv.gz  in=386,741,502 out=134,045,665 elapsed=549.5s

  [12759/13157] intraday_9601.csv.gz  in=386,753,067 out=134,057,230 elapsed=549.5s

  [12760/13157] intraday_9602.csv.gz  in=386,766,837 out=134,070,685 elapsed=549.5s

  [12761/13157] intraday_9603.csv.gz  in=386,779,192 out=134,083,040 elapsed=549.5s

  [12762/13157] intraday_9604.csv.gz  in=386,792,381 out=134,096,229 elapsed=549.6s

  [12763/13157] intraday_9606.csv.gz  in=386,808,550 out=134,111,235 elapsed=549.6s

  [12764/13157] intraday_9605.csv.gz  in=386,824,130 out=134,126,424 elapsed=549.6s

  [12765/13157] intraday_9607.csv.gz  in=386,838,715 out=134,140,312 elapsed=549.7s

  [12766/13157] intraday_9608.csv.gz  in=386,850,096 out=134,151,693 elapsed=549.7s

  [12767/13157] intraday_9609.csv.gz  in=386,862,191 out=134,163,788 elapsed=549.7s

  [12768/13157] intraday_9610.csv.gz  in=386,872,172 out=134,173,769 elapsed=549.7s

  [12769/13157] intraday_9611.csv.gz  in=386,884,194 out=134,185,791 elapsed=549.8s

  [12770/13157] intraday_9612.csv.gz  in=386,896,624 out=134,198,221 elapsed=549.8s

  [12771/13157] intraday_9614.csv.gz  in=386,909,811 out=134,211,408 elapsed=549.8s

  [12772/13157] intraday_9613.csv.gz  in=386,921,136 out=134,222,733 elapsed=549.8s

  [12773/13157] intraday_9616.csv.gz  in=386,932,867 out=134,234,464 elapsed=549.8s

  [12774/13157] intraday_9618.csv.gz  in=386,944,469 out=134,246,066 elapsed=549.9s

  [12775/13157] intraday_9615.csv.gz  in=386,956,619 out=134,258,216 elapsed=549.9s

  [12776/13157] intraday_9617.csv.gz  in=386,969,815 out=134,271,412 elapsed=549.9s

  [12777/13157] intraday_9619.csv.gz  in=386,981,038 out=134,282,635 elapsed=549.9s

  [12778/13157] intraday_9620.csv.gz  in=386,994,068 out=134,295,665 elapsed=550.0s

  [12779/13157] intraday_9621.csv.gz  in=387,006,843 out=134,308,440 elapsed=550.0s

  [12780/13157] intraday_9622.csv.gz  in=387,023,946 out=134,324,967 elapsed=550.0s

  [12781/13157] intraday_9623.csv.gz  in=387,036,520 out=134,337,541 elapsed=550.0s

  [12782/13157] intraday_9624.csv.gz  in=387,048,169 out=134,349,190 elapsed=550.0s

  [12783/13157] intraday_9625.csv.gz  in=387,060,430 out=134,361,451 elapsed=550.0s

  [12784/13157] intraday_9626.csv.gz  in=387,072,127 out=134,373,148 elapsed=550.0s

  [12785/13157] intraday_9628.csv.gz  in=387,085,601 out=134,386,622 elapsed=550.1s

  [12786/13157] intraday_9630.csv.gz  in=387,107,539 out=134,405,988 elapsed=550.2s

  [12787/13157] intraday_9627.csv.gz  in=387,122,729 out=134,421,178 elapsed=550.2s

  [12788/13157] intraday_9629.csv.gz  in=387,137,249 out=134,435,698 elapsed=550.2s

  [12789/13157] intraday_9631.csv.gz  in=387,148,357 out=134,446,806 elapsed=550.3s

  [12790/13157] intraday_9634.csv.gz  in=387,160,989 out=134,459,438 elapsed=550.3s

  [12791/13157] intraday_9633.csv.gz  in=387,173,116 out=134,471,565 elapsed=550.3s

  [12792/13157] intraday_9632.csv.gz  in=387,184,107 out=134,482,556 elapsed=550.3s

  [12793/13157] intraday_9636.csv.gz  in=387,196,628 out=134,495,077 elapsed=550.5s

  [12794/13157] intraday_9635.csv.gz  in=387,211,889 out=134,510,052 elapsed=550.5s

  [12795/13157] intraday_9637.csv.gz  in=387,223,216 out=134,521,379 elapsed=550.5s

  [12796/13157] intraday_9638.csv.gz  in=387,234,231 out=134,532,394 elapsed=550.5s

  [12797/13157] intraday_9642.csv.gz  in=387,244,309 out=134,542,472 elapsed=550.6s

  [12798/13157] intraday_9639.csv.gz  in=387,257,208 out=134,555,371 elapsed=550.6s

  [12799/13157] intraday_9641.csv.gz  in=387,269,735 out=134,567,898 elapsed=550.6s

  [12800/13157] intraday_9640.csv.gz  in=387,281,623 out=134,579,786 elapsed=550.6s

  [12801/13157] intraday_9644.csv.gz  in=387,292,897 out=134,591,060 elapsed=550.8s

  [12802/13157] intraday_9645.csv.gz  in=387,310,829 out=134,608,992 elapsed=550.8s

  [12803/13157] intraday_9646.csv.gz  in=387,327,051 out=134,625,214 elapsed=550.8s

  [12804/13157] intraday_9643.csv.gz  in=387,337,620 out=134,635,783 elapsed=550.8s

  [12805/13157] intraday_9648.csv.gz  in=387,348,969 out=134,647,132 elapsed=550.8s

  [12806/13157] intraday_9649.csv.gz  in=387,361,061 out=134,659,224 elapsed=550.9s

  [12807/13157] intraday_9647.csv.gz  in=387,373,246 out=134,671,409 elapsed=550.9s

  [12808/13157] intraday_9651.csv.gz  in=387,385,448 out=134,683,611 elapsed=550.9s

  [12809/13157] intraday_9650.csv.gz  in=387,400,277 out=134,698,440 elapsed=550.9s

  [12810/13157] intraday_9655.csv.gz  in=387,413,504 out=134,711,667 elapsed=551.1s

  [12811/13157] intraday_9654.csv.gz  in=387,426,762 out=134,724,925 elapsed=551.1s

  [12812/13157] intraday_9653.csv.gz  in=387,437,307 out=134,735,470 elapsed=551.1s

  [12813/13157] intraday_9652.csv.gz  in=387,453,179 out=134,751,342 elapsed=551.1s

  [12814/13157] intraday_9657.csv.gz  in=387,466,780 out=134,764,943 elapsed=551.8s

  [12815/13157] intraday_9656.csv.gz  in=387,479,436 out=134,777,599 elapsed=551.8s

  [12816/13157] intraday_9658.csv.gz  in=387,492,029 out=134,790,192 elapsed=551.8s

  [12817/13157] intraday_9659.csv.gz  in=387,505,393 out=134,803,556 elapsed=551.8s

  [12818/13157] intraday_9661.csv.gz  in=387,517,785 out=134,815,948 elapsed=551.8s

  [12819/13157] intraday_9660.csv.gz  in=387,529,681 out=134,827,844 elapsed=551.8s

  [12820/13157] intraday_9662.csv.gz  in=387,542,248 out=134,840,411 elapsed=551.9s

  [12821/13157] intraday_9664.csv.gz  in=387,557,027 out=134,855,190 elapsed=551.9s

  [12822/13157] intraday_9663.csv.gz  in=387,568,840 out=134,867,003 elapsed=551.9s

  [12823/13157] intraday_9665.csv.gz  in=387,583,917 out=134,882,080 elapsed=551.9s

  [12824/13157] intraday_9667.csv.gz  in=387,597,259 out=134,895,300 elapsed=552.0s

  [12825/13157] intraday_9666.csv.gz  in=387,613,033 out=134,911,074 elapsed=552.0s

  [12826/13157] intraday_9668.csv.gz  in=387,625,829 out=134,923,870 elapsed=552.0s

  [12827/13157] intraday_9669.csv.gz  in=387,639,350 out=134,937,391 elapsed=552.0s

  [12828/13157] intraday_9673.csv.gz  in=387,652,699 out=134,950,616 elapsed=552.0s

  [12829/13157] intraday_9670.csv.gz  in=387,663,742 out=134,961,659 elapsed=552.0s

  [12830/13157] intraday_9672.csv.gz  in=387,678,068 out=134,975,985 elapsed=552.0s

  [12831/13157] intraday_9671.csv.gz  in=387,693,370 out=134,991,287 elapsed=552.1s

  [12832/13157] intraday_9674.csv.gz  in=387,704,432 out=135,002,349 elapsed=552.1s

  [12833/13157] intraday_9676.csv.gz  in=387,716,691 out=135,014,608 elapsed=552.1s

  [12834/13157] intraday_9675.csv.gz  in=387,731,604 out=135,029,521 elapsed=552.1s

  [12835/13157] intraday_9677.csv.gz  in=387,745,767 out=135,043,684 elapsed=552.1s

  [12836/13157] intraday_9679.csv.gz  in=387,763,380 out=135,061,297 elapsed=552.2s

  [12837/13157] intraday_9678.csv.gz  in=387,777,742 out=135,075,659 elapsed=552.2s

  [12838/13157] intraday_9680.csv.gz  in=387,790,525 out=135,088,442 elapsed=552.2s

  [12839/13157] intraday_9681.csv.gz  in=387,807,398 out=135,105,315 elapsed=552.2s

  [12840/13157] intraday_9682.csv.gz  in=387,818,874 out=135,116,791 elapsed=552.3s

  [12841/13157] intraday_9684.csv.gz  in=387,830,583 out=135,128,500 elapsed=552.3s

  [12842/13157] intraday_9685.csv.gz  in=387,843,001 out=135,140,918 elapsed=552.3s

  [12843/13157] intraday_9683.csv.gz  in=387,856,294 out=135,154,211 elapsed=552.3s

  [12844/13157] intraday_9686.csv.gz  in=387,867,272 out=135,165,189 elapsed=552.4s

  [12845/13157] intraday_9687.csv.gz  in=387,880,007 out=135,177,924 elapsed=552.4s

  [12846/13157] intraday_9688.csv.gz  in=387,893,554 out=135,191,471 elapsed=552.5s

  [12847/13157] intraday_9689.csv.gz  in=387,909,781 out=135,207,698 elapsed=552.5s

  [12848/13157] intraday_9690.csv.gz  in=387,921,137 out=135,219,054 elapsed=552.6s

  [12849/13157] intraday_9691.csv.gz  in=387,933,440 out=135,231,357 elapsed=552.6s

  [12850/13157] intraday_9693.csv.gz  in=387,946,237 out=135,244,154 elapsed=552.6s

  [12851/13157] intraday_9692.csv.gz  in=387,958,948 out=135,256,710 elapsed=552.6s

  [12852/13157] intraday_9694.csv.gz  in=387,970,140 out=135,267,902 elapsed=552.7s

  [12853/13157] intraday_9695.csv.gz  in=387,982,982 out=135,280,744 elapsed=552.7s

  [12854/13157] intraday_9696.csv.gz  in=387,997,326 out=135,295,088 elapsed=552.7s

  [12855/13157] intraday_9697.csv.gz  in=388,011,289 out=135,309,051 elapsed=552.7s

  [12856/13157] intraday_9699.csv.gz  in=388,024,702 out=135,322,464 elapsed=552.7s

  [12857/13157] intraday_9698.csv.gz  in=388,039,329 out=135,337,091 elapsed=552.8s

  [12858/13157] intraday_9700.csv.gz  in=388,051,580 out=135,349,342 elapsed=552.8s

  [12859/13157] intraday_9701.csv.gz  in=388,065,109 out=135,362,871 elapsed=552.8s

  [12860/13157] intraday_9704.csv.gz  in=388,073,454 out=135,371,216 elapsed=552.8s

  [12861/13157] intraday_9705.csv.gz  in=388,080,942 out=135,378,704 elapsed=552.8s

  [12862/13157] intraday_9703.csv.gz  in=388,094,394 out=135,392,156 elapsed=552.8s

  [12863/13157] intraday_9707.csv.gz  in=388,096,041 out=135,393,803 elapsed=552.8s

  [12864/13157] intraday_9702.csv.gz  in=388,107,985 out=135,405,747 elapsed=552.8s

  [12865/13157] intraday_9706.csv.gz  in=388,120,549 out=135,418,311 elapsed=552.8s

  [12866/13157] intraday_9709.csv.gz  in=388,120,567 out=135,418,329 elapsed=552.9s

  [12867/13157] intraday_9708.csv.gz  in=388,120,588 out=135,418,350 elapsed=552.9s

  [12868/13157] intraday_9710.csv.gz  in=388,120,849 out=135,418,611 elapsed=552.9s

  [12869/13157] intraday_9712.csv.gz  in=388,120,954 out=135,418,716 elapsed=552.9s

  [12870/13157] intraday_9713.csv.gz  in=388,122,452 out=135,419,883 elapsed=552.9s

  [12871/13157] intraday_9711.csv.gz  in=388,126,591 out=135,423,206 elapsed=552.9s

  [12872/13157] intraday_9714.csv.gz  in=388,126,643 out=135,423,258 elapsed=552.9s

  [12873/13157] intraday_9715.csv.gz  in=388,127,081 out=135,423,696 elapsed=552.9s

  [12874/13157] intraday_9716.csv.gz  in=388,127,590 out=135,424,205 elapsed=552.9s

  [12875/13157] intraday_9717.csv.gz  in=388,127,706 out=135,424,321 elapsed=553.0s

  [12876/13157] intraday_9719.csv.gz  in=388,127,805 out=135,424,420 elapsed=553.0s

  [12877/13157] intraday_9718.csv.gz  in=388,129,199 out=135,425,520 elapsed=553.0s

  [12878/13157] intraday_9720.csv.gz  in=388,134,326 out=135,429,853 elapsed=553.0s

  [12879/13157] intraday_9723.csv.gz  in=388,134,339 out=135,429,866 elapsed=553.0s

  [12880/13157] intraday_9722.csv.gz  in=388,134,565 out=135,430,092 elapsed=553.0s

  [12881/13157] intraday_9725.csv.gz  in=388,134,609 out=135,430,136 elapsed=553.0s

  [12882/13157] intraday_9721.csv.gz  in=388,136,591 out=135,432,118 elapsed=553.0s

  [12883/13157] intraday_9726.csv.gz  in=388,138,131 out=135,433,658 elapsed=553.0s

  [12884/13157] intraday_9724.csv.gz  in=388,148,531 out=135,441,230 elapsed=553.0s

  [12885/13157] intraday_9727.csv.gz  in=388,149,735 out=135,442,434 elapsed=553.0s

  [12886/13157] intraday_9728.csv.gz  in=388,150,565 out=135,443,125 elapsed=553.1s

  [12887/13157] intraday_9730.csv.gz  in=388,150,611 out=135,443,171 elapsed=553.1s

  [12888/13157] intraday_9729.csv.gz  in=388,151,907 out=135,444,208 elapsed=553.1s

  [12889/13157] intraday_9731.csv.gz  in=388,152,016 out=135,444,317 elapsed=553.1s

  [12890/13157] intraday_9732.csv.gz  in=388,152,120 out=135,444,421 elapsed=553.1s

  [12891/13157] intraday_9734.csv.gz  in=388,153,328 out=135,445,629 elapsed=553.2s

  [12892/13157] intraday_9735.csv.gz  in=388,154,074 out=135,446,315 elapsed=553.2s

  [12893/13157] intraday_9736.csv.gz  in=388,154,500 out=135,446,741 elapsed=553.2s

  [12894/13157] intraday_9733.csv.gz  in=388,156,890 out=135,449,098 elapsed=553.2s

  [12895/13157] intraday_9738.csv.gz  in=388,156,893 out=135,449,101 elapsed=553.2s

  [12896/13157] intraday_9737.csv.gz  in=388,157,327 out=135,449,535 elapsed=553.2s

  [12897/13157] intraday_9739.csv.gz  in=388,167,779 out=135,458,518 elapsed=553.3s

  [12898/13157] intraday_9743.csv.gz  in=388,177,002 out=135,467,741 elapsed=553.4s

  [12899/13157] intraday_9742.csv.gz  in=388,189,419 out=135,480,158 elapsed=553.4s

  [12900/13157] intraday_9741.csv.gz  in=388,202,193 out=135,492,932 elapsed=553.4s

  [12901/13157] intraday_9740.csv.gz  in=388,217,246 out=135,507,985 elapsed=553.4s

  [12902/13157] intraday_9744.csv.gz  in=388,229,090 out=135,519,829 elapsed=553.6s

  [12903/13157] intraday_9745.csv.gz  in=388,244,646 out=135,535,385 elapsed=553.6s

  [12904/13157] intraday_9747.csv.gz  in=388,255,859 out=135,546,598 elapsed=553.6s

  [12905/13157] intraday_9746.csv.gz  in=388,270,022 out=135,560,761 elapsed=553.6s

  [12906/13157] intraday_9751.csv.gz  in=388,282,470 out=135,573,209 elapsed=553.8s

  [12907/13157] intraday_9748.csv.gz  in=388,294,887 out=135,585,626 elapsed=553.8s

  [12908/13157] intraday_9750.csv.gz  in=388,310,201 out=135,600,940 elapsed=553.8s

  [12909/13157] intraday_9749.csv.gz  in=388,325,239 out=135,615,978 elapsed=553.8s

  [12910/13157] intraday_9754.csv.gz  in=388,334,966 out=135,625,705 elapsed=554.4s

  [12911/13157] intraday_9755.csv.gz  in=388,346,723 out=135,637,462 elapsed=554.4s

  [12912/13157] intraday_9752.csv.gz  in=388,359,865 out=135,650,604 elapsed=554.4s

  [12913/13157] intraday_9753.csv.gz  in=388,375,384 out=135,666,123 elapsed=554.4s

  [12914/13157] intraday_9756.csv.gz  in=388,387,654 out=135,678,393 elapsed=555.1s

  [12915/13157] intraday_9758.csv.gz  in=388,398,914 out=135,689,653 elapsed=555.3s

  [12916/13157] intraday_9759.csv.gz  in=388,409,925 out=135,700,664 elapsed=555.4s

  [12917/13157] intraday_9757.csv.gz  in=388,424,121 out=135,714,860 elapsed=555.4s

  [12918/13157] intraday_9760.csv.gz  in=388,435,995 out=135,726,734 elapsed=555.4s

  [12919/13157] intraday_9761.csv.gz  in=388,450,022 out=135,740,761 elapsed=555.4s

  [12920/13157] intraday_9763.csv.gz  in=388,462,803 out=135,753,542 elapsed=555.4s

  [12921/13157] intraday_9762.csv.gz  in=388,475,146 out=135,765,885 elapsed=555.4s

  [12922/13157] intraday_9764.csv.gz  in=388,488,350 out=135,779,089 elapsed=555.4s

  [12923/13157] intraday_9765.csv.gz  in=388,500,571 out=135,791,310 elapsed=555.4s

  [12924/13157] intraday_9766.csv.gz  in=388,513,048 out=135,803,787 elapsed=555.5s

  [12925/13157] intraday_9767.csv.gz  in=388,524,770 out=135,815,509 elapsed=555.6s

  [12926/13157] intraday_9769.csv.gz  in=388,537,588 out=135,828,327 elapsed=555.6s

  [12927/13157] intraday_9768.csv.gz  in=388,548,605 out=135,839,344 elapsed=555.6s

  [12928/13157] intraday_9770.csv.gz  in=388,562,784 out=135,853,523 elapsed=555.7s

  [12929/13157] intraday_9773.csv.gz  in=388,573,657 out=135,864,396 elapsed=555.8s

  [12930/13157] intraday_9771.csv.gz  in=388,588,365 out=135,879,104 elapsed=555.8s

  [12931/13157] intraday_9772.csv.gz  in=388,599,166 out=135,889,905 elapsed=555.8s

  [12932/13157] intraday_9774.csv.gz  in=388,612,473 out=135,903,212 elapsed=555.8s

  [12933/13157] intraday_9775.csv.gz  in=388,626,046 out=135,916,785 elapsed=555.9s

  [12934/13157] intraday_9776.csv.gz  in=388,636,540 out=135,927,279 elapsed=555.9s

  [12935/13157] intraday_9778.csv.gz  in=388,646,763 out=135,937,502 elapsed=556.0s

  [12936/13157] intraday_9777.csv.gz  in=388,659,289 out=135,950,028 elapsed=556.0s

  [12937/13157] intraday_9780.csv.gz  in=388,670,121 out=135,960,860 elapsed=556.2s

  [12938/13157] intraday_9781.csv.gz  in=388,681,199 out=135,971,938 elapsed=556.3s

  [12939/13157] intraday_9779.csv.gz  in=388,691,518 out=135,982,257 elapsed=556.3s

  [12940/13157] intraday_9782.csv.gz  in=388,704,466 out=135,995,205 elapsed=556.3s

  [12941/13157] intraday_9786.csv.gz  in=388,715,988 out=136,006,727 elapsed=556.4s

  [12942/13157] intraday_9784.csv.gz  in=388,728,819 out=136,019,558 elapsed=556.4s

  [12943/13157] intraday_9783.csv.gz  in=388,741,542 out=136,032,281 elapsed=556.4s

  [12944/13157] intraday_9785.csv.gz  in=388,754,641 out=136,045,380 elapsed=556.4s

  [12945/13157] intraday_9787.csv.gz  in=388,765,906 out=136,056,645 elapsed=556.6s

  [12946/13157] intraday_9788.csv.gz  in=388,778,746 out=136,069,485 elapsed=556.6s

  [12947/13157] intraday_9790.csv.gz  in=388,790,067 out=136,080,806 elapsed=556.6s

  [12948/13157] intraday_9789.csv.gz  in=388,800,757 out=136,091,496 elapsed=556.6s

  [12949/13157] intraday_9791.csv.gz  in=388,812,250 out=136,102,989 elapsed=556.6s

  [12950/13157] intraday_9793.csv.gz  in=388,825,609 out=136,116,348 elapsed=556.7s

  [12951/13157] intraday_9794.csv.gz  in=388,836,215 out=136,126,954 elapsed=556.7s

  [12952/13157] intraday_9795.csv.gz  in=388,849,540 out=136,140,279 elapsed=556.7s

  [12953/13157] intraday_9792.csv.gz  in=388,860,304 out=136,151,043 elapsed=556.7s

  [12954/13157] intraday_9796.csv.gz  in=388,872,623 out=136,163,362 elapsed=556.7s

  [12955/13157] intraday_9797.csv.gz  in=388,885,014 out=136,175,753 elapsed=556.7s

  [12956/13157] intraday_9798.csv.gz  in=388,896,813 out=136,187,552 elapsed=556.7s

  [12957/13157] intraday_9800.csv.gz  in=388,908,487 out=136,199,226 elapsed=556.8s

  [12958/13157] intraday_9799.csv.gz  in=388,920,729 out=136,211,468 elapsed=556.8s

  [12959/13157] intraday_9801.csv.gz  in=388,933,817 out=136,224,556 elapsed=556.8s

  [12960/13157] intraday_9803.csv.gz  in=388,946,486 out=136,237,225 elapsed=556.8s

  [12961/13157] intraday_9802.csv.gz  in=388,957,492 out=136,248,231 elapsed=556.8s

  [12962/13157] intraday_9804.csv.gz  in=388,969,834 out=136,260,573 elapsed=556.9s

  [12963/13157] intraday_9806.csv.gz  in=388,984,926 out=136,275,665 elapsed=556.9s

  [12964/13157] intraday_9805.csv.gz  in=388,996,161 out=136,286,900 elapsed=556.9s

  [12965/13157] intraday_9807.csv.gz  in=389,008,854 out=136,299,593 elapsed=556.9s

  [12966/13157] intraday_9808.csv.gz  in=389,023,606 out=136,314,345 elapsed=557.1s

  [12967/13157] intraday_9811.csv.gz  in=389,034,185 out=136,324,924 elapsed=557.1s

  [12968/13157] intraday_9810.csv.gz  in=389,046,678 out=136,337,417 elapsed=557.1s

  [12969/13157] intraday_9809.csv.gz  in=389,059,028 out=136,349,767 elapsed=557.1s

  [12970/13157] intraday_9812.csv.gz  in=389,071,368 out=136,362,107 elapsed=557.2s

  [12971/13157] intraday_9813.csv.gz  in=389,084,225 out=136,374,964 elapsed=557.2s

  [12972/13157] intraday_9815.csv.gz  in=389,096,405 out=136,387,144 elapsed=557.2s

  [12973/13157] intraday_9814.csv.gz  in=389,110,613 out=136,401,352 elapsed=557.2s

  [12974/13157] intraday_9819.csv.gz  in=389,123,505 out=136,414,244 elapsed=557.3s

  [12975/13157] intraday_9817.csv.gz  in=389,133,627 out=136,424,366 elapsed=557.3s

  [12976/13157] intraday_9818.csv.gz  in=389,147,060 out=136,437,799 elapsed=557.3s

  [12977/13157] intraday_9816.csv.gz  in=389,160,991 out=136,451,730 elapsed=557.3s

  [12978/13157] intraday_9820.csv.gz  in=389,172,291 out=136,463,030 elapsed=557.4s

  [12979/13157] intraday_9822.csv.gz  in=389,182,682 out=136,473,421 elapsed=557.4s

  [12980/13157] intraday_9821.csv.gz  in=389,194,457 out=136,485,196 elapsed=557.4s

  [12981/13157] intraday_9823.csv.gz  in=389,205,849 out=136,496,588 elapsed=557.5s

  [12982/13157] intraday_9824.csv.gz  in=389,217,649 out=136,508,388 elapsed=557.6s

  [12983/13157] intraday_9825.csv.gz  in=389,234,215 out=136,524,954 elapsed=557.6s

  [12984/13157] intraday_9827.csv.gz  in=389,245,398 out=136,536,137 elapsed=557.6s

  [12985/13157] intraday_9826.csv.gz  in=389,261,490 out=136,552,229 elapsed=557.6s

  [12986/13157] intraday_9828.csv.gz  in=389,274,576 out=136,565,315 elapsed=557.9s

  [12987/13157] intraday_9829.csv.gz  in=389,289,208 out=136,579,947 elapsed=557.9s

  [12988/13157] intraday_9831.csv.gz  in=389,303,920 out=136,594,659 elapsed=557.9s

  [12989/13157] intraday_9830.csv.gz  in=389,316,830 out=136,607,569 elapsed=557.9s

  [12990/13157] intraday_9832.csv.gz  in=389,328,425 out=136,619,164 elapsed=558.4s

  [12991/13157] intraday_9835.csv.gz  in=389,341,298 out=136,632,037 elapsed=558.4s

  [12992/13157] intraday_9833.csv.gz  in=389,353,656 out=136,644,395 elapsed=558.4s

  [12993/13157] intraday_9834.csv.gz  in=389,367,283 out=136,658,022 elapsed=558.5s

  [12994/13157] intraday_9837.csv.gz  in=389,380,322 out=136,671,061 elapsed=558.5s

  [12995/13157] intraday_9836.csv.gz  in=389,393,862 out=136,684,601 elapsed=558.5s

  [12996/13157] intraday_9838.csv.gz  in=389,406,207 out=136,696,946 elapsed=558.5s

  [12997/13157] intraday_9839.csv.gz  in=389,418,982 out=136,709,721 elapsed=558.5s

  [12998/13157] intraday_9840.csv.gz  in=389,432,536 out=136,723,275 elapsed=558.6s

  [12999/13157] intraday_9842.csv.gz  in=389,443,739 out=136,734,478 elapsed=558.6s

  [13000/13157] intraday_9843.csv.gz  in=389,457,405 out=136,748,144 elapsed=558.6s

  [13001/13157] intraday_9841.csv.gz  in=389,469,286 out=136,760,025 elapsed=558.6s

  [13002/13157] intraday_9845.csv.gz  in=389,483,220 out=136,773,959 elapsed=558.6s

  [13003/13157] intraday_9847.csv.gz  in=389,496,030 out=136,786,769 elapsed=558.7s

  [13004/13157] intraday_9846.csv.gz  in=389,509,161 out=136,799,900 elapsed=558.7s

  [13005/13157] intraday_9844.csv.gz  in=389,523,898 out=136,814,637 elapsed=558.7s

  [13006/13157] intraday_9848.csv.gz  in=389,540,274 out=136,831,013 elapsed=558.7s

  [13007/13157] intraday_9850.csv.gz  in=389,552,607 out=136,843,346 elapsed=558.7s

  [13008/13157] intraday_9851.csv.gz  in=389,567,178 out=136,857,917 elapsed=558.7s

  [13009/13157] intraday_9849.csv.gz  in=389,578,296 out=136,869,035 elapsed=558.7s

  [13010/13157] intraday_9853.csv.gz  in=389,588,365 out=136,879,104 elapsed=558.8s

  [13011/13157] intraday_9854.csv.gz  in=389,601,841 out=136,892,580 elapsed=558.8s

  [13012/13157] intraday_9855.csv.gz  in=389,614,266 out=136,905,005 elapsed=558.8s

  [13013/13157] intraday_9852.csv.gz  in=389,628,750 out=136,919,489 elapsed=558.8s

  [13014/13157] intraday_9856.csv.gz  in=389,641,705 out=136,932,444 elapsed=559.0s

  [13015/13157] intraday_9858.csv.gz  in=389,657,156 out=136,947,895 elapsed=559.0s

  [13016/13157] intraday_9857.csv.gz  in=389,672,373 out=136,963,112 elapsed=559.0s

  [13017/13157] intraday_9859.csv.gz  in=389,689,659 out=136,980,398 elapsed=559.0s

  [13018/13157] intraday_9860.csv.gz  in=389,705,404 out=136,996,143 elapsed=559.1s

  [13019/13157] intraday_9861.csv.gz  in=389,717,452 out=137,008,191 elapsed=559.1s

  [13020/13157] intraday_9863.csv.gz  in=389,729,980 out=137,020,719 elapsed=559.1s

  [13021/13157] intraday_9864.csv.gz  in=389,740,377 out=137,031,116 elapsed=559.1s

  [13022/13157] intraday_9862.csv.gz  in=389,753,441 out=137,044,180 elapsed=559.1s

  [13023/13157] intraday_9865.csv.gz  in=389,766,834 out=137,057,573 elapsed=559.1s

  [13024/13157] intraday_9866.csv.gz  in=389,777,781 out=137,068,520 elapsed=559.2s

  [13025/13157] intraday_9868.csv.gz  in=389,791,072 out=137,081,811 elapsed=559.2s

  [13026/13157] intraday_9867.csv.gz  in=389,806,079 out=137,096,818 elapsed=559.2s

  [13027/13157] intraday_9869.csv.gz  in=389,821,363 out=137,112,102 elapsed=559.2s

  [13028/13157] intraday_9870.csv.gz  in=389,834,426 out=137,125,165 elapsed=559.2s

  [13029/13157] intraday_9871.csv.gz  in=389,845,446 out=137,136,185 elapsed=559.2s

  [13030/13157] intraday_9872.csv.gz  in=389,857,218 out=137,147,957 elapsed=559.3s

  [13031/13157] intraday_9873.csv.gz  in=389,871,225 out=137,161,964 elapsed=559.3s

  [13032/13157] intraday_9877.csv.gz  in=389,885,166 out=137,175,905 elapsed=559.3s

  [13033/13157] intraday_9876.csv.gz  in=389,899,547 out=137,190,286 elapsed=559.4s

  [13034/13157] intraday_9875.csv.gz  in=389,913,850 out=137,204,589 elapsed=559.4s

  [13035/13157] intraday_9874.csv.gz  in=389,924,356 out=137,215,095 elapsed=559.4s

  [13036/13157] intraday_9880.csv.gz  in=389,936,744 out=137,227,483 elapsed=559.5s

  [13037/13157] intraday_9878.csv.gz  in=389,951,173 out=137,241,912 elapsed=559.5s

  [13038/13157] intraday_9881.csv.gz  in=389,965,338 out=137,256,077 elapsed=559.5s

  [13039/13157] intraday_9879.csv.gz  in=389,977,543 out=137,268,282 elapsed=559.5s

  [13040/13157] intraday_9884.csv.gz  in=389,984,547 out=137,275,286 elapsed=559.6s

  [13041/13157] intraday_9885.csv.gz  in=389,992,921 out=137,283,660 elapsed=559.6s

  [13042/13157] intraday_9882.csv.gz  in=390,003,775 out=137,294,514 elapsed=559.6s

  [13043/13157] intraday_9883.csv.gz  in=390,017,084 out=137,307,823 elapsed=559.6s

  [13044/13157] intraday_9886.csv.gz  in=390,027,670 out=137,318,409 elapsed=559.6s

  [13045/13157] intraday_9887.csv.gz  in=390,042,265 out=137,333,004 elapsed=559.6s

  [13046/13157] intraday_9888.csv.gz  in=390,054,532 out=137,345,271 elapsed=559.6s

  [13047/13157] intraday_9889.csv.gz  in=390,066,154 out=137,356,893 elapsed=559.6s

  [13048/13157] intraday_9890.csv.gz  in=390,076,442 out=137,367,181 elapsed=559.7s

  [13049/13157] intraday_9891.csv.gz  in=390,088,006 out=137,378,745 elapsed=559.7s

  [13050/13157] intraday_9893.csv.gz  in=390,102,483 out=137,393,222 elapsed=559.8s

  [13051/13157] intraday_9894.csv.gz  in=390,113,114 out=137,403,853 elapsed=559.9s

  [13052/13157] intraday_9892.csv.gz  in=390,127,973 out=137,418,712 elapsed=559.9s

  [13053/13157] intraday_9895.csv.gz  in=390,139,853 out=137,430,592 elapsed=559.9s

  [13054/13157] intraday_9898.csv.gz  in=390,151,848 out=137,442,587 elapsed=560.0s

  [13055/13157] intraday_9896.csv.gz  in=390,166,544 out=137,457,283 elapsed=560.1s

  [13056/13157] intraday_9897.csv.gz  in=390,180,397 out=137,471,136 elapsed=560.1s

  [13057/13157] intraday_9899.csv.gz  in=390,194,239 out=137,484,978 elapsed=560.1s

  [13058/13157] intraday_9900.csv.gz  in=390,209,772 out=137,500,229 elapsed=560.1s

  [13059/13157] intraday_9901.csv.gz  in=390,220,326 out=137,510,783 elapsed=560.1s

  [13060/13157] intraday_9902.csv.gz  in=390,233,368 out=137,523,825 elapsed=560.1s

  [13061/13157] intraday_9903.csv.gz  in=390,246,563 out=137,536,619 elapsed=560.2s

  [13062/13157] intraday_9904.csv.gz  in=390,263,111 out=137,553,167 elapsed=560.2s

  [13063/13157] intraday_9906.csv.gz  in=390,273,858 out=137,563,914 elapsed=560.3s

  [13064/13157] intraday_9905.csv.gz  in=390,286,580 out=137,576,636 elapsed=560.3s

  [13065/13157] intraday_9908.csv.gz  in=390,300,284 out=137,590,340 elapsed=560.3s

  [13066/13157] intraday_9907.csv.gz  in=390,315,201 out=137,605,257 elapsed=560.3s

  [13067/13157] intraday_9911.csv.gz  in=390,327,919 out=137,617,975 elapsed=560.3s

  [13068/13157] intraday_9909.csv.gz  in=390,342,354 out=137,632,133 elapsed=560.3s

  [13069/13157] intraday_9912.csv.gz  in=390,354,527 out=137,644,306 elapsed=560.4s

  [13070/13157] intraday_9910.csv.gz  in=390,368,082 out=137,657,774 elapsed=560.4s

  [13071/13157] intraday_9915.csv.gz  in=390,378,187 out=137,667,879 elapsed=560.4s

  [13072/13157] intraday_9913.csv.gz  in=390,389,327 out=137,679,019 elapsed=560.4s

  [13073/13157] intraday_9914.csv.gz  in=390,401,093 out=137,690,785 elapsed=560.4s

  [13074/13157] intraday_9916.csv.gz  in=390,415,841 out=137,705,533 elapsed=560.4s

  [13075/13157] intraday_9918.csv.gz  in=390,428,923 out=137,718,615 elapsed=560.5s

  [13076/13157] intraday_9919.csv.gz  in=390,440,222 out=137,729,914 elapsed=560.5s

  [13077/13157] intraday_9920.csv.gz  in=390,451,344 out=137,741,036 elapsed=560.5s

  [13078/13157] intraday_9917.csv.gz  in=390,467,274 out=137,756,966 elapsed=560.5s

  [13079/13157] intraday_9921.csv.gz  in=390,479,425 out=137,769,117 elapsed=560.5s

  [13080/13157] intraday_9924.csv.gz  in=390,492,110 out=137,781,802 elapsed=560.5s

  [13081/13157] intraday_9923.csv.gz  in=390,503,199 out=137,792,891 elapsed=560.5s

  [13082/13157] intraday_9922.csv.gz  in=390,517,377 out=137,807,069 elapsed=560.6s

  [13083/13157] intraday_9925.csv.gz  in=390,528,339 out=137,818,031 elapsed=560.6s

  [13084/13157] intraday_9927.csv.gz  in=390,539,565 out=137,829,257 elapsed=560.6s

  [13085/13157] intraday_9928.csv.gz  in=390,550,743 out=137,840,435 elapsed=560.6s

  [13086/13157] intraday_9926.csv.gz  in=390,577,318 out=137,866,160 elapsed=560.6s

  [13087/13157] intraday_9929.csv.gz  in=390,590,721 out=137,879,563 elapsed=560.6s

  [13088/13157] intraday_9932.csv.gz  in=390,603,437 out=137,892,279 elapsed=560.7s

  [13089/13157] intraday_9930.csv.gz  in=390,615,034 out=137,903,876 elapsed=560.7s

  [13090/13157] intraday_9931.csv.gz  in=390,628,986 out=137,917,828 elapsed=560.7s

  [13091/13157] intraday_9934.csv.gz  in=390,640,963 out=137,929,805 elapsed=560.7s

  [13092/13157] intraday_9933.csv.gz  in=390,651,696 out=137,940,538 elapsed=560.7s

  [13093/13157] intraday_9936.csv.gz  in=390,662,482 out=137,951,324 elapsed=560.8s

  [13094/13157] intraday_9935.csv.gz  in=390,674,209 out=137,963,051 elapsed=560.8s

  [13095/13157] intraday_9938.csv.gz  in=390,685,179 out=137,974,021 elapsed=560.8s

  [13096/13157] intraday_9937.csv.gz  in=390,696,187 out=137,985,029 elapsed=560.8s

  [13097/13157] intraday_9939.csv.gz  in=390,708,136 out=137,996,978 elapsed=560.9s

  [13098/13157] intraday_9940.csv.gz  in=390,721,723 out=138,010,565 elapsed=560.9s

  [13099/13157] intraday_9941.csv.gz  in=390,733,720 out=138,022,562 elapsed=560.9s

  [13100/13157] intraday_9942.csv.gz  in=390,748,180 out=138,036,668 elapsed=560.9s

  [13101/13157] intraday_9943.csv.gz  in=390,761,657 out=138,050,145 elapsed=561.0s

  [13102/13157] intraday_9945.csv.gz  in=390,772,638 out=138,061,126 elapsed=561.0s

  [13103/13157] intraday_9944.csv.gz  in=390,785,195 out=138,073,683 elapsed=561.0s

  [13104/13157] intraday_9946.csv.gz  in=390,797,071 out=138,085,559 elapsed=561.0s

  [13105/13157] intraday_9947.csv.gz  in=390,809,363 out=138,097,851 elapsed=561.1s

  [13106/13157] intraday_9949.csv.gz  in=390,821,861 out=138,110,349 elapsed=561.1s

  [13107/13157] intraday_9948.csv.gz  in=390,835,924 out=138,124,290 elapsed=561.1s

  [13108/13157] intraday_9950.csv.gz  in=390,847,311 out=138,135,677 elapsed=561.1s

  [13109/13157] intraday_9952.csv.gz  in=390,857,145 out=138,145,511 elapsed=561.2s

  [13110/13157] intraday_9951.csv.gz  in=390,868,804 out=138,157,170 elapsed=561.2s

  [13111/13157] intraday_9954.csv.gz  in=390,881,837 out=138,170,203 elapsed=561.2s

  [13112/13157] intraday_9953.csv.gz  in=390,901,048 out=138,189,259 elapsed=561.2s

  [13113/13157] intraday_9955.csv.gz  in=390,915,921 out=138,204,132 elapsed=561.2s

  [13114/13157] intraday_9958.csv.gz  in=390,925,717 out=138,213,928 elapsed=561.2s

  [13115/13157] intraday_9957.csv.gz  in=390,938,138 out=138,226,349 elapsed=561.3s

  [13116/13157] intraday_9956.csv.gz  in=390,951,555 out=138,239,766 elapsed=561.3s

  [13117/13157] intraday_9959.csv.gz  in=390,964,513 out=138,252,724 elapsed=561.3s

  [13118/13157] intraday_9961.csv.gz  in=390,978,642 out=138,266,853 elapsed=561.4s

  [13119/13157] intraday_9962.csv.gz  in=390,991,040 out=138,279,251 elapsed=561.4s

  [13120/13157] intraday_9960.csv.gz  in=391,003,876 out=138,292,087 elapsed=561.4s

  [13121/13157] intraday_9963.csv.gz  in=391,016,595 out=138,304,806 elapsed=561.4s

  [13122/13157] intraday_9966.csv.gz  in=391,027,643 out=138,315,854 elapsed=561.4s

  [13123/13157] intraday_9964.csv.gz  in=391,038,782 out=138,326,993 elapsed=561.4s

  [13124/13157] intraday_9967.csv.gz  in=391,050,738 out=138,338,949 elapsed=561.4s

  [13125/13157] intraday_9965.csv.gz  in=391,064,388 out=138,352,599 elapsed=561.4s

  [13126/13157] intraday_9969.csv.gz  in=391,073,543 out=138,361,754 elapsed=561.5s

  [13127/13157] intraday_9968.csv.gz  in=391,085,102 out=138,373,313 elapsed=561.6s

  [13128/13157] intraday_9970.csv.gz  in=391,095,655 out=138,383,866 elapsed=561.6s

  [13129/13157] intraday_9971.csv.gz  in=391,122,863 out=138,408,803 elapsed=561.6s

  [13130/13157] intraday_9972.csv.gz  in=391,140,773 out=138,426,713 elapsed=561.6s

  [13131/13157] intraday_9974.csv.gz  in=391,152,691 out=138,438,631 elapsed=561.6s

  [13132/13157] intraday_9973.csv.gz  in=391,167,143 out=138,453,083 elapsed=561.6s

  [13133/13157] intraday_9975.csv.gz  in=391,178,104 out=138,464,044 elapsed=561.6s

  [13134/13157] intraday_9976.csv.gz  in=391,194,330 out=138,480,270 elapsed=561.7s

  [13135/13157] intraday_9979.csv.gz  in=391,205,216 out=138,491,156 elapsed=561.7s

  [13136/13157] intraday_9978.csv.gz  in=391,221,384 out=138,507,324 elapsed=561.7s

  [13137/13157] intraday_9977.csv.gz  in=391,241,583 out=138,525,965 elapsed=561.7s

  [13138/13157] intraday_9980.csv.gz  in=391,253,234 out=138,537,616 elapsed=561.7s

  [13139/13157] intraday_9982.csv.gz  in=391,266,554 out=138,550,936 elapsed=561.8s

  [13140/13157] intraday_9983.csv.gz  in=391,278,961 out=138,563,343 elapsed=561.8s

  [13141/13157] intraday_9981.csv.gz  in=391,292,277 out=138,576,659 elapsed=561.8s

  [13142/13157] intraday_9984.csv.gz  in=391,305,962 out=138,590,344 elapsed=561.8s

  [13143/13157] intraday_9985.csv.gz  in=391,318,324 out=138,602,706 elapsed=561.8s

  [13144/13157] intraday_9986.csv.gz  in=391,329,932 out=138,614,314 elapsed=561.8s

  [13145/13157] intraday_9988.csv.gz  in=391,341,484 out=138,625,866 elapsed=561.9s

  [13146/13157] intraday_9987.csv.gz  in=391,354,673 out=138,639,055 elapsed=561.9s

  [13147/13157] intraday_9989.csv.gz  in=391,365,695 out=138,650,077 elapsed=561.9s

  [13148/13157] intraday_9992.csv.gz  in=391,378,321 out=138,662,703 elapsed=561.9s

  [13149/13157] intraday_9990.csv.gz  in=391,390,698 out=138,675,080 elapsed=561.9s

  [13150/13157] intraday_9993.csv.gz  in=391,405,190 out=138,689,572 elapsed=562.0s

  [13151/13157] intraday_9991.csv.gz  in=391,421,906 out=138,706,288 elapsed=562.0s

  [13152/13157] intraday_9996.csv.gz  in=391,433,572 out=138,717,954 elapsed=562.6s

  [13153/13157] intraday_9994.csv.gz  in=391,444,184 out=138,728,566 elapsed=562.6s

  [13154/13157] intraday_9997.csv.gz  in=391,456,583 out=138,740,965 elapsed=562.6s

  [13155/13157] intraday_9995.csv.gz  in=391,472,468 out=138,756,850 elapsed=562.6s

  [13156/13157] intraday_9998.csv.gz  in=391,485,799 out=138,770,181 elapsed=562.7s

  [13157/13157] intraday_9999.csv.gz  in=391,500,882 out=138,784,988 elapsed=562.7s

✅ DONE  in=391,500,882 → out=138,784,988  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 571.2s

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [20]:
def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,      # лишено для сумісності виклику
    *,
    max_workers: int = 4,
) -> pd.DataFrame:
    """Денні open (перший бар 09:30–09:35) і close (останній бар 15:55–15:59).

    Раніше кожен відібраний рядок проходив через itertuples + оновлення python-словника;
    тепер редукція повністю векторна (sort + drop_duplicates у pyarrow/pandas).
    Клітинка 19 уже рахує це за один прохід — ця функція лишається як самостійний шлях.
    """
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    open_parts, close_parts = [], []
    lock = threading.Lock()

    def _handle(path):
        reader = _open_intraday_csv(path, 64 << 20)
        lo, lc = [], []
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            o_df, c_df = _oc_from_table(pa.Table.from_batches([rb]))
            if len(o_df):
                lo.append(o_df)
            if len(c_df):
                lc.append(c_df)
        with lock:
            open_parts.extend(lo)
            close_parts.extend(lc)

    if max_workers and max_workers > 1:
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            list(ex.map(_handle, files))
    else:
        for p in files:
            _handle(p)

    out = _finalize_oc(open_parts, close_parts)

    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)
    return out

In [21]:
# oc.parquet уже побудовано в клітинці 19 (той самий прохід по файлах).
# Перебудовуємо лише якщо його немає.
_oc_path = str(WORK_DIR / "oc.parquet")
if os.path.exists(_oc_path):
    df_oc = pd.read_parquet(_oc_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(BATCH_DIR), out_path=_oc_path)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [22]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def _prep_oc_prev_close(df_oc: pd.DataFrame) -> pd.DataFrame:
    """['ticker','date','open','prev_close'], date — звичайний рядок 'YYYY-MM-DD'."""
    oc = df_oc[["ticker", "date", "open", "close"]].copy()
    oc["ticker"] = oc["ticker"].astype(str)
    oc["date"] = oc["date"].astype(str).str.slice(0, 10)
    oc = oc.sort_values(["ticker", "date"], kind="stable")
    oc["prev_close"] = oc.groupby("ticker", sort=False)["close"].shift(1)
    return oc[["ticker", "date", "open", "prev_close"]].reset_index(drop=True)


def _date_from_dt(s: pd.Series) -> pd.Series:
    """'YYYY-MM-DD' з 'dt'. Для рядкового dt це зріз (C-рівень), без парсингу дат."""
    if pd.api.types.is_string_dtype(s) or s.dtype == object:
        return s.astype(str).str.slice(0, 10)
    return s.dt.strftime("%Y-%m-%d")


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame,
                                        _oc_prepared: Optional[pd.DataFrame] = None,
                                        sort_out: bool = False) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']

    Прискорення проти попередньої версії:
      - 'dt' лишається рядком: ні pd.to_datetime, ні .dt.date (це були python-об'єкти
        на кожен рядок — найдорожча операція в усьому пайплайні);
      - prev_close рахується ОДИН раз (передається через _oc_prepared), а не на кожен батч;
      - без per-batch sort_values (фінальне сортування робить клітинка 47).
    """
    right = _oc_prepared if _oc_prepared is not None else _prep_oc_prev_close(df_oc)
    out = df_intraday
    out = out[out["dt"].notna()]
    out = out.assign(date=_date_from_dt(out["dt"]))
    out = out.merge(right, on=["ticker", "date"], how="left")
    if sort_out:
        out = out.sort_values(["ticker", "dt"], kind="stable").reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    sort_out: bool = False,
):
    """
    Читає великий Parquet батчами і мерджить денні open/prev_close з oc.parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    df_oc = pd.read_parquet(oc_parquet_path)
    missing = {"ticker", "date", "open", "close"} - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")
    oc_prepared = _prep_oc_prev_close(df_oc)      # рахуємо ОДИН раз, не на кожен батч

    if os.path.exists(out_path):
        os.remove(out_path)
    if not out_path.endswith((".csv", ".gz", ".parquet")):
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0

    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}", flush=True)

    for batch_idx, batch in enumerate(pf.iter_batches(batch_size=batch_rows, columns=cols), 1):
        df_batch = batch.to_pandas()
        df_enriched = enrich_with_day_open_and_prev_close(
            df_batch, None, _oc_prepared=oc_prepared, sort_out=sort_out)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched, preserve_index=False)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            df_enriched.to_csv(
                out_path, index=False, mode="a", header=(total_rows == 0),
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_enriched)
        if batch_idx % log_every_batches == 0:
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s", flush=True)


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [23]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=15.6s

[batch   10] rows=20,000,000  elapsed=30.1s

[batch   15] rows=30,000,000  elapsed=45.1s

[batch   20] rows=40,000,000  elapsed=59.7s

[batch   25] rows=50,000,000  elapsed=73.9s

[batch   30] rows=60,000,000  elapsed=88.1s

[batch   35] rows=70,000,000  elapsed=102.7s

[batch   40] rows=80,000,000  elapsed=117.2s

[batch   45] rows=90,000,000  elapsed=131.7s

[batch   50] rows=100,000,000  elapsed=146.2s

[batch   55] rows=110,000,000  elapsed=160.8s

[batch   60] rows=120,000,000  elapsed=175.3s

[batch   65] rows=130,000,000  elapsed=190.1s

[batch   70] rows=138,784,988  elapsed=202.9s

✅ DONE  rows=138,784,988  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  in 203.2s

Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet

In [24]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    Обчислення в numpy (без проміжних pandas-Series і .replace), без gc на кожен батч.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  "
          f"batch_rows≈{batch_rows:,}  using={value_col}", flush=True)

    for batches, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for c in ("prev_close", value_col):
            if c not in df.columns:
                raise KeyError(f"У вхідному файлі немає колонки '{c}'.")

        num = pd.to_numeric(df[value_col], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        den = pd.to_numeric(df["prev_close"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            pct = np.where(den == 0, np.nan, num / den - 1.0) * 100.0   # 0 → NaN, без ділення на 0
        if round_to is not None:
            pct = np.round(pct, int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s", flush=True)
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [25]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

[batch    5] rows=10,000,000  elapsed=8.6s

[batch   10] rows=20,000,000  elapsed=17.5s

[batch   15] rows=30,000,000  elapsed=26.1s

[batch   20] rows=40,000,000  elapsed=34.7s

[batch   25] rows=50,000,000  elapsed=43.3s

[batch   30] rows=60,000,000  elapsed=51.6s

[batch   35] rows=70,000,000  elapsed=60.2s

[batch   40] rows=80,000,000  elapsed=68.6s

[batch   45] rows=90,000,000  elapsed=77.2s

[batch   50] rows=100,000,000  elapsed=85.6s

[batch   55] rows=110,000,000  elapsed=94.5s

[batch   60] rows=120,000,000  elapsed=103.2s

[batch   65] rows=130,000,000  elapsed=111.7s

[batch   70] rows=138,784,988  elapsed=119.2s

✅ DONE  rows=138,784,988  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  in 119.2s

Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet

In [26]:
import os
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Read ticker->bench mapping from csv/xlsx and return ['ticker','bench'].
    """
    ext = os.path.splitext(mapping_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(mapping_path)
    else:
        try:
            df = pd.read_csv(mapping_path, sep=None, engine="python")
        except Exception:
            df = pd.read_csv(mapping_path)

    cols = {c.lower().strip(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol") or list(df.columns)[0]
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf") or list(df.columns)[1]

    out = df[[tcol, bcol]].rename(columns={tcol: "ticker", bcol: "bench"}).dropna()
    out["ticker"] = out["ticker"].astype(str).str.upper().str.strip()
    out["bench"] = out["bench"].astype(str).str.upper().str.strip()
    out = out[(out["ticker"] != "") & (out["bench"] != "")]
    return out.drop_duplicates(ignore_index=True)


def corr_beta_from_mapping_to_parquet(*args, **kwargs):
    """
    Deprecated API path removed.
    corr/beta is now computed locally in cell 12 and written in cell 13/28.
    """
    raise RuntimeError(
        "corr_beta_from_mapping_to_parquet is deprecated. "
        "Use local calculation in cell 12 and parquet output in cell 13/28."
    )

In [27]:
import os
import pandas as pd

out_path = str(WORK_DIR / "corr_beta_pairs.parquet")

# If parquet already exists from cell 13, keep it.
# Otherwise rebuild it from x_to_best_etf_by_lvl3.csv (no API calls).
if not os.path.exists(out_path):
    src_csv = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv")
    if not os.path.exists(src_csv):
        raise FileNotFoundError(f"Neither {out_path} nor {src_csv} exists")

    d = pd.read_csv(src_csv)
    need = ["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
    miss = [c for c in need if c not in d.columns]
    if miss:
        raise KeyError(f"Missing columns in {src_csv}: {miss}")

    d = d.rename(columns={
        "best_y_ticker": "y_ticker",
        "best_corr": "corr",
        "beta_with_best": "beta",
    })[["x_ticker", "y_ticker", "corr", "beta"]]
    d.to_parquet(out_path, index=False)

print("Result:", out_path)

Result: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [28]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    df = pq.read_table(path).to_pandas()
    inv = {c.strip().lower(): c for c in df.columns}

    has_api = ("x_ticker" in inv) and ("y_ticker" in inv)
    has_direct = ("ticker" in inv) and ("bench" in inv)
    if not (has_api or has_direct):
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={inv["x_ticker"]: "ticker", inv["y_ticker"]: "bench"})
    else:
        df = df.rename(columns={inv["ticker"]: "ticker", inv["bench"]: "bench"})

    for c in ("corr", "beta"):
        if c in inv:
            df = df.rename(columns={inv[c]: c})
        else:
            df[c] = pd.NA

    df = df[["ticker", "bench", "corr", "beta"]].copy()
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"] = df["bench"].astype(str).str.strip().str.upper()
    df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    return (df.sort_values(["ticker", "corr"], ascending=[True, False])
              .drop_duplicates(subset=["ticker"], keep="first")
              .reset_index(drop=True))


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), додає 'bench','corr','beta' по 'ticker'.

    Замість merge на кожен батч (+ strip/upper над мільйонами рядків) нормалізація і
    пошук у мапі йдуть по унікальних тікерах, а результат розгортається за кодами.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    m_bench = dict(zip(mapping["ticker"], mapping["bench"]))
    m_corr = dict(zip(mapping["ticker"], mapping["corr"]))
    m_beta = dict(zip(mapping["ticker"], mapping["beta"]))

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_parquet_path}", flush=True)

    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["bench"] = _map_by_ticker(codes, cats, m_bench, numeric=False)
        df["corr"] = _map_by_ticker(codes, cats, m_corr, numeric=True)
        df["beta"] = _map_by_ticker(codes, cats, m_beta, numeric=True)

        cols = [c for c in df.columns if c not in ("bench", "corr", "beta")]
        if insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]]
        else:
            df = df[cols + ["bench", "corr", "beta"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_parquet_path


# опціональний аліас під старе ім'я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [29]:
out_path = attach_bench_corr_beta_parquet(
    input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    batch_rows=2_000_000,
    round_decimals=4,
    insert_before="pct_vs_prev_close",
    compression="snappy",
)
print("Готово:", out_path)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

[batch    5] rows=10,000,000  elapsed=12.2s

[batch   10] rows=20,000,000  elapsed=24.3s

[batch   15] rows=30,000,000  elapsed=37.9s

[batch   20] rows=40,000,000  elapsed=50.2s

[batch   25] rows=50,000,000  elapsed=63.5s

[batch   30] rows=60,000,000  elapsed=77.0s

[batch   35] rows=70,000,000  elapsed=90.1s

[batch   40] rows=80,000,000  elapsed=103.4s

[batch   45] rows=90,000,000  elapsed=115.5s

[batch   50] rows=100,000,000  elapsed=127.8s

[batch   55] rows=110,000,000  elapsed=139.9s

[batch   60] rows=120,000,000  elapsed=151.8s

[batch   65] rows=130,000,000  elapsed=164.1s

[batch   70] rows=138,784,988  elapsed=174.7s

✅ DONE rows=138,784,988 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet  in 174.7s

Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

In [30]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [31]:
peek_parquet(str(WORK_DIR / "premarket_rows_final.parquet"), n=620)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet
Рядків (meta): 138,784,988
Колонок: 14
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta
NaN у 'bench' (у прев'ю): 0/620
NaN у 'corr' (у прев'ю): 0/620
NaN у 'beta' (у прев'ю): 0/620

Перші рядки:
    ticker                   dt           o           h           l           c         v        date    open  prev_close  Stack% bench    corr    beta
0     SHOP  2026-06-30 00:01:00  114.250000  114.250000  114.250000  114.250000      12.0  2026-06-30  113.00      114.21    0.04   IGV  0.6509  0.5575
1     SHOP  2026-06-30 00:09:00  114.300003  114.330002  114.300003  114.330002      26.0  2026-06-30  113.00      114.21    0.08   IGV  0.6509  0.5575
2     SHOP  2026-06-30 00:26:00  114.449997  114.449997  114.430000  114.430000     200.0  2026-06-30  113.00      114.21    0.21   IGV  0.6509  0.5575
3     SHOP  2026-06-30 00:28:00  114.419998  114.419998  114.410004  114.410004      36.0  2026-06-30  113.00      114.21    0.18   IGV  0.6509  0.5575
4     SHOP  2026-06-30 00:29:00  114.400002  114.400002  114.400002  114.400002     100.0  2026-06-30  113.00      114.21    0.17   IGV  0.6509  0.5575
5     SHOP  2026-06-30 00:30:00  114.360001  114.360001  114.349998  114.349998      37.0  2026-06-30  113.00      114.21    0.13   IGV  0.6509  0.5575
6     SHOP  2026-06-30 00:34:00  114.349998  114.349998  114.349998  114.349998       1.0  2026-06-30  113.00      114.21    0.12   IGV  0.6509  0.5575
7     SHOP  2026-06-30 00:47:00  114.360001  114.360001  114.349998  114.349998     100.0  2026-06-30  113.00      114.21    0.13   IGV  0.6509  0.5575
8     SHOP  2026-06-30 00:57:00  114.370003  114.379997  114.370003  114.379997      40.0  2026-06-30  113.00      114.21    0.14   IGV  0.6509  0.5575
9     SHOP  2026-06-30 01:23:00  114.309998  114.309998  114.309998  114.309998       1.0  2026-06-30  113.00      114.21    0.09   IGV  0.6509  0.5575
10    SHOP  2026-06-30 01:32:00  114.209999  114.209999  114.150002  114.150002      23.0  2026-06-30  113.00      114.21   -0.00   IGV  0.6509  0.5575
11    SHOP  2026-06-30 01:38:00  114.139999  114.139999  114.139999  114.139999       5.0  2026-06-30  113.00      114.21   -0.06   IGV  0.6509  0.5575
12    SHOP  2026-06-30 01:42:00  114.199997  114.209999  114.199997  114.209999      70.0  2026-06-30  113.00      114.21   -0.01   IGV  0.6509  0.5575
13    SHOP  2026-06-30 02:12:00  114.279999  114.290001  114.279999  114.290001      97.0  2026-06-30  113.00      114.21    0.06   IGV  0.6509  0.5575
14    SHOP  2026-06-30 02:24:00  114.300003  114.360001  114.300003  114.360001     111.0  2026-06-30  113.00      114.21    0.08   IGV  0.6509  0.5575
15    SHOP  2026-06-30 02:25:00  114.370003  114.370003  114.370003  114.370003      25.0  2026-06-30  113.00      114.21    0.14   IGV  0.6509  0.5575
16    SHOP  2026-06-30 02:26:00  114.309998  114.309998  114.300003  114.300003     144.0  2026-06-30  113.00      114.21    0.09   IGV  0.6509  0.5575
17    SHOP  2026-06-30 02:33:00  114.290001  114.290001  114.290001  114.290001       7.0  2026-06-30  113.00      114.21    0.07   IGV  0.6509  0.5575
18    SHOP  2026-06-30 02:54:00  114.230003  114.230003  114.230003  114.230003       1.0  2026-06-30  113.00      114.21    0.02   IGV  0.6509  0.5575
19    SHOP  2026-06-30 03:22:00  114.199997  114.199997  114.129997  114.129997      13.0  2026-06-30  113.00      114.21   -0.01   IGV  0.6509  0.5575
20    SHOP  2026-06-30 03:23:00  114.180000  114.239998  114.180000  114.239998     100.0  2026-06-30  113.00      114.21   -0.03   IGV  0.6509  0.5575
21    SHOP  2026-06-30 03:25:00  114.239998  114.239998  114.239998  114.239998      28.0  2026-06-30  113.00      114.21    0.03   IGV  0.6509  0.5575
22    SHOP  2026-06-30 03:36:00  114.190002  114.190002  114.190002  114.190002      33.0  2026-06-30  113.00      114.21   -0.02   IGV  0.6509  0.5575
23    SHOP  2026-06-30 03:40:00  114.209999  114.220001  114.209999  114.220001     156.0  2026-06-30  113.00      114.21   -0.00   IGV  0.6509  0.5575
24    SHOP  2026-06-30 03:45:00  114.120003  114.120003  114.050003  114.050003      36.0  2026-06-30  113.00      114.21   -0.08   IGV  0.6509  0.5575
25    SHOP  2026-06-30 03:47:00  114.180000  114.180000  114.180000  114.180000      21.0  2026-06-30  113.00      114.21   -0.03   IGV  0.6509  0.5575
26    SHOP  2026-06-30 03:48:00  114.190002  114.190002  114.190002  114.190002       4.0  2026-06-30  113.00      114.21   -0.02   IGV  0.6509  0.5575
27    SHOP  2026-06-30 03:49:00  114.190002  114.190002  114.080002  114.080002      56.0  2026-06-30  113.00      114.21   -0.02   IGV  0.6509  0.5575
28    SHOP  2026-06-30 03:50:00  114.180000  114.180000  114.180000  114.180000      44.0  2026-06-30  113.00      114.21   -0.03   IGV  0.6509  0.5575
29    SHOP  2026-06-30 03:51:00  114.120003  114.120003  114.110001  114.110001     200.0  2026-06-30  113.00      114.21   -0.08   IGV  0.6509  0.5575
30    SHOP  2026-06-30 03:53:00  114.129997  114.160004  114.129997  114.150002      33.0  2026-06-30  113.00      114.21   -0.07   IGV  0.6509  0.5575
31    SHOP  2026-06-30 03:54:00  114.150002  114.150002  114.150002  114.150002      13.0  2026-06-30  113.00      114.21   -0.05   IGV  0.6509  0.5575
32    SHOP  2026-06-30 03:57:00  114.230003  114.230003  114.230003  114.230003       1.0  2026-06-30  113.00      114.21    0.02   IGV  0.6509  0.5575
33    SHOP  2026-06-30 03:59:00  114.239998  114.290001  114.239998  114.290001     109.0  2026-06-30  113.00      114.21    0.03   IGV  0.6509  0.5575
34    SHOP  2026-06-30 04:00:00  114.199997  114.422897  114.190002  114.250000    1586.0  2026-06-30  113.00      114.21   -0.01   IGV  0.6509  0.5575
35    SHOP  2026-06-30 04:02:00  114.269997  114.269997  114.269997  114.269997     100.0  2026-06-30  113.00      114.21    0.05   IGV  0.6509  0.5575
36    SHOP  2026-06-30 04:03:00  114.209999  114.209999  114.209999  114.209999     200.0  2026-06-30  113.00      114.21   -0.00   IGV  0.6509  0.5575
37    SHOP  2026-06-30 04:04:00  114.120003  114.120003  114.110001  114.110001     200.0  2026-06-30  113.00      114.21   -0.08   IGV  0.6509  0.5575
38    SHOP  2026-06-30 06:19:00  114.010002  114.010002  114.010002  114.010002     200.0  2026-06-30  113.00      114.21   -0.18   IGV  0.6509  0.5575
39    SHOP  2026-06-30 06:45:00  114.500000  114.500000  114.500000  114.500000     100.0  2026-06-30  113.00      114.21    0.25   IGV  0.6509  0.5575
40    SHOP  2026-06-30 06:57:00  113.559998  113.559998  113.559998  113.559998     210.0  2026-06-30  113.00      114.21   -0.57   IGV  0.6509  0.5575
41    SHOP  2026-06-30 07:05:00  114.150002  114.150002  114.150002  114.150002     100.0  2026-06-30  113.00      114.21   -0.05   IGV  0.6509  0.5575
42    SHOP  2026-06-30 07:06:00  114.150002  114.150002  114.110001  114.110001     290.0  2026-06-30  113.00      114.21   -0.05   IGV  0.6509  0.5575
43    SHOP  2026-06-30 07:16:00  114.038200  114.038200  114.010002  114.010002     600.0  2026-06-30  113.00      114.21   -0.15   IGV  0.6509  0.5575
44    SHOP  2026-06-30 07:25:00  114.010002  114.010002  114.010002  114.010002     200.0  2026-06-30  113.00      114.21   -0.18   IGV  0.6509  0.5575
45    SHOP  2026-06-30 07:34:00  113.989998  113.989998  113.989998  113.989998     200.0  2026-06-30  113.00      114.21   -0.19   IGV  0.6509  0.5575
46    SHOP  2026-06-30 07:35:00  113.900002  113.900002  113.900002  113.900002     100.0  2026-06-30  113.00      114.21   -0.27   IGV  0.6509  0.5575
47    SHOP  2026-06-30 07:39:00  113.889999  113.889999  113.889999  113.889999     250.0  2026-06-30  113.00      114.21   -0.28   IGV  0.6509  0.5575
48    SHOP  2026-06-30 07:40:00  113.242500  113.599998  113.242500  113.599998     400.0  2026-06-30  113.00      114.21   -0.85   IGV  0.6509  0.5575
49    SHOP  2026-06-30 08:01:00  113.800003  113.800003  113.800003  113.800003     500.0  2026-06-30  113.00      114.21   -0.36   IGV  0.6509  0.5575
50    SHOP  2026-06-30 08:08:00  113.550003  113.550003  113.309998  113.550003     825.0  2026-06-30  113.00      114.21   -0.58   IGV  0.6509  0.5575
51    SHOP  2026-06-30 08:22:00  113.309998  113.309998  113.309998  113.309998     372.0  2026-06-30  113.00      114.21   -0.79   IGV  0.6509  0.5575
52    SHOP  2026-06-30 08:26:00  113.388397  113.388397  113.388397  113.388397     100.0  2026-06-30  113.00      114.21   -0.72   IGV  0.6509  0.5575
53    SHOP  2026-06-30 08:27:00  113.300003  113.300003  113.300003  113.300003     500.0  2026-06-30  113.00      114.21   -0.80   IGV  0.6509  0.5575
54    SHOP  2026-06-30 08:33:00  113.652496  113.652496  113.652496  113.652496     670.0  2026-06-30  113.00      114.21   -0.49   IGV  0.6509  0.5575
55    SHOP  2026-06-30 08:48:00  113.099998  113.099998  113.099998  113.099998     770.0  2026-06-30  113.00      114.21   -0.97   IGV  0.6509  0.5575
56    SHOP  2026-06-30 08:51:00  113.070000  113.070000  113.070000  113.070000     100.0  2026-06-30  113.00      114.21   -1.00   IGV  0.6509  0.5575
57    SHOP  2026-06-30 08:54:00  113.083099  113.083099  113.059998  113.059998    1200.0  2026-06-30  113.00      114.21   -0.99   IGV  0.6509  0.5575
58    SHOP  2026-06-30 08:55:00  113.059998  113.059998  113.059998  113.059998     100.0  2026-06-30  113.00      114.21   -1.01   IGV  0.6509  0.5575
59    SHOP  2026-06-30 08:56:00  113.059998  113.199997  112.449997  112.900002    3225.0  2026-06-30  113.00      114.21   -1.01   IGV  0.6509  0.5575
60    SHOP  2026-06-30 08:57:00  113.000000  113.000000  113.000000  113.000000     200.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575
61    SHOP  2026-06-30 08:58:00  113.000000  113.000000  113.000000  113.000000     391.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575
62    SHOP  2026-06-30 09:01:00  113.000000  113.000000  113.000000  113.000000     100.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575
63    SHOP  2026-06-30 09:02:00  113.000000  113.000000  113.000000  113.000000     217.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575
64    SHOP  2026-06-30 09:11:00  113.010002  113.010002  113.010002  113.010002     100.0  2026-06-30  113.00      114.21   -1.05   IGV  0.6509  0.5575
65    SHOP  2026-06-30 09:21:00  113.010002  113.010002  113.000000  113.000000     200.0  2026-06-30  113.00      114.21   -1.05   IGV  0.6509  0.5575
66    SHOP  2026-06-30 09:24:00  113.297997  113.297997  113.297997  113.297997     100.0  2026-06-30  113.00      114.21   -0.80   IGV  0.6509  0.5575
67    SHOP  2026-06-30 09:27:00  113.400002  113.400002  112.879997  112.879997     585.0  2026-06-30  113.00      114.21   -0.71   IGV  0.6509  0.5575
68    SHOP  2026-06-30 09:28:00  112.320000  112.400002  112.139999  112.139999    1121.0  2026-06-30  113.00      114.21   -1.65   IGV  0.6509  0.5575
69    SHOP  2026-06-30 09:29:00  112.150002  112.330002  112.110001  112.110001     304.0  2026-06-30  113.00      114.21   -1.80   IGV  0.6509  0.5575
70    SHOP  2026-06-30 09:30:00  113.000000  114.230003  112.000000  114.144997   82876.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575
71    SHOP  2026-06-30 09:31:00  114.144997  114.360001  113.800003  113.824997   22177.0  2026-06-30  113.00      114.21   -0.06   IGV  0.6509  0.5575
72    SHOP  2026-06-30 09:32:00  113.980003  114.120003  113.129997  113.758598    9412.0  2026-06-30  113.00      114.21   -0.20   IGV  0.6509  0.5575
73    SHOP  2026-06-30 09:33:00  114.239998  114.250000  113.739998  113.800003   10035.0  2026-06-30  113.00      114.21    0.03   IGV  0.6509  0.5575
74    SHOP  2026-06-30 09:34:00  113.919998  114.459999  113.580002  114.370003   12116.0  2026-06-30  113.00      114.21   -0.25   IGV  0.6509  0.5575
75    SHOP  2026-06-30 09:35:00  114.260002  114.559998  114.080002  114.559998    8013.0  2026-06-30  113.00      114.21    0.04   IGV  0.6509  0.5575
76    SHOP  2026-06-30 09:36:00  114.309998  114.599998  114.129997  114.260002   15786.0  2026-06-30  113.00      114.21    0.09   IGV  0.6509  0.5575
77    SHOP  2026-06-30 09:37:00  114.139999  114.180000  113.500000  113.570000   11678.0  2026-06-30  113.00      114.21   -0.06   IGV  0.6509  0.5575
78    SHOP  2026-06-30 09:38:00  113.570000  114.160004  113.459999  114.040001   35488.0  2026-06-30  113.00      114.21   -0.56   IGV  0.6509  0.5575
79    SHOP  2026-06-30 09:39:00  114.000000  114.190002  113.480003  113.480003    7814.0  2026-06-30  113.00      114.21   -0.18   IGV  0.6509  0.5575
80    SHOP  2026-06-30 09:40:00  113.389999  113.610001  113.300003  113.455002    6955.0  2026-06-30  113.00      114.21   -0.72   IGV  0.6509  0.5575
81    SHOP  2026-06-30 09:41:00  113.570000  114.290001  113.570000  114.099998    5815.0  2026-06-30  113.00      114.21   -0.56   IGV  0.6509  0.5575
82    SHOP  2026-06-30 09:42:00  114.000000  114.410004  113.889999  114.410004   11943.0  2026-06-30  113.00      114.21   -0.18   IGV  0.6509  0.5575
83    SHOP  2026-06-30 09:43:00  114.290001  114.449997  114.129997  114.285004    9334.0  2026-06-30  113.00      114.21    0.07   IGV  0.6509  0.5575
84    SHOP  2026-06-30 09:44:00  114.279999  114.279999  113.834999  114.010002   12061.0  2026-06-30  113.00      114.21    0.06   IGV  0.6509  0.5575
85    SHOP  2026-06-30 09:45:00  113.985001  114.300003  113.790001  114.160004   29739.0  2026-06-30  113.00      114.21   -0.20   IGV  0.6509  0.5575
86    SHOP  2026-06-30 09:46:00  114.150002  114.720001  114.019997  114.570000   13156.0  2026-06-30  113.00      114.21   -0.05   IGV  0.6509  0.5575
87    SHOP  2026-06-30 09:47:00  114.570000  114.570000  113.697197  113.697197   13885.0  2026-06-30  113.00      114.21    0.32   IGV  0.6509  0.5575
88    SHOP  2026-06-30 09:48:00  113.750000  114.150002  113.750000  114.099998    3849.0  2026-06-30  113.00      114.21   -0.40   IGV  0.6509  0.5575
89    SHOP  2026-06-30 09:49:00  113.964996  114.750000  113.964996  114.750000   17752.0  2026-06-30  113.00      114.21   -0.21   IGV  0.6509  0.5575
90    SHOP  2026-06-30 09:50:00  114.610001  115.230003  114.610001  115.120003   19234.0  2026-06-30  113.00      114.21    0.35   IGV  0.6509  0.5575
91    SHOP  2026-06-30 09:51:00  115.209999  115.660004  115.209999  115.529999   12292.0  2026-06-30  113.00      114.21    0.88   IGV  0.6509  0.5575
92    SHOP  2026-06-30 09:52:00  115.519997  115.730003  115.234299  115.410004   18801.0  2026-06-30  113.00      114.21    1.15   IGV  0.6509  0.5575
93    SHOP  2026-06-30 09:53:00  115.422501  115.680000  115.417999  115.495003   13048.0  2026-06-30  113.00      114.21    1.06   IGV  0.6509  0.5575
94    SHOP  2026-06-30 09:54:00  115.470001  115.790001  115.300003  115.559998   10308.0  2026-06-30  113.00      114.21    1.10   IGV  0.6509  0.5575
95    SHOP  2026-06-30 09:55:00  115.529999  115.959999  115.529999  115.959999   11921.0  2026-06-30  113.00      114.21    1.16   IGV  0.6509  0.5575
96    SHOP  2026-06-30 09:56:00  115.889999  116.000000  115.410004  115.410004   10045.0  2026-06-30  113.00      114.21    1.47   IGV  0.6509  0.5575
97    SHOP  2026-06-30 09:57:00  115.410004  115.739998  115.330002  115.614998    5010.0  2026-06-30  113.00      114.21    1.05   IGV  0.6509  0.5575
98    SHOP  2026-06-30 09:58:00  115.595001  115.629997  115.160004  115.470001   11902.0  2026-06-30  113.00      114.21    1.21   IGV  0.6509  0.5575
99    SHOP  2026-06-30 09:59:00  115.474998  115.559998  115.320000  115.349998    7430.0  2026-06-30  113.00      114.21    1.11   IGV  0.6509  0.5575
100   SHOP  2026-06-30 10:00:00  115.250000  115.299599  114.769997  114.849998   12014.0  2026-06-30  113.00      114.21    0.91   IGV  0.6509  0.5575
101   SHOP  2026-06-30 10:01:00  114.750000  115.209999  114.639999  115.169998   11181.0  2026-06-30  113.00      114.21    0.47   IGV  0.6509  0.5575
102   SHOP  2026-06-30 10:02:00  115.220001  115.385002  115.129997  115.150002    4351.0  2026-06-30  113.00      114.21    0.88   IGV  0.6509  0.5575
103   SHOP  2026-06-30 10:03:00  115.139999  115.379997  115.120003  115.160004    4517.0  2026-06-30  113.00      114.21    0.81   IGV  0.6509  0.5575
104   SHOP  2026-06-30 10:04:00  115.089996  115.150002  114.955002  115.114998    2623.0  2026-06-30  113.00      114.21    0.77   IGV  0.6509  0.5575
105   SHOP  2026-06-30 10:05:00  115.080002  115.154999  114.950600  115.070099    5666.0  2026-06-30  113.00      114.21    0.76   IGV  0.6509  0.5575
106   SHOP  2026-06-30 10:06:00  115.160004  115.339996  115.139999  115.250000    2294.0  2026-06-30  113.00      114.21    0.83   IGV  0.6509  0.5575
107   SHOP  2026-06-30 10:07:00  115.339996  115.419998  115.129997  115.419998    4497.0  2026-06-30  113.00      114.21    0.99   IGV  0.6509  0.5575
108   SHOP  2026-06-30 10:08:00  115.419998  115.419998  115.000000  115.019997    6186.0  2026-06-30  113.00      114.21    1.06   IGV  0.6509  0.5575
109   SHOP  2026-06-30 10:09:00  115.000000  115.014999  114.720001  114.779999    3861.0  2026-06-30  113.00      114.21    0.69   IGV  0.6509  0.5575
110   SHOP  2026-06-30 10:10:00  114.790001  114.790001  114.489998  114.497101   10898.0  2026-06-30  113.00      114.21    0.51   IGV  0.6509  0.5575
111   SHOP  2026-06-30 10:11:00  114.589996  114.870003  114.589996  114.848000    2597.0  2026-06-30  113.00      114.21    0.33   IGV  0.6509  0.5575
112   SHOP  2026-06-30 10:12:00  114.800003  115.010002  114.800003  114.949997   58063.0  2026-06-30  113.00      114.21    0.52   IGV  0.6509  0.5575
113   SHOP  2026-06-30 10:13:00  115.099998  115.195000  114.919998  114.919998   21694.0  2026-06-30  113.00      114.21    0.78   IGV  0.6509  0.5575
114   SHOP  2026-06-30 10:14:00  115.000000  115.070000  114.849998  114.889999    2000.0  2026-06-30  113.00      114.21    0.69   IGV  0.6509  0.5575
115   SHOP  2026-06-30 10:15:00  114.855003  114.900002  114.750000  114.805000    7107.0  2026-06-30  113.00      114.21    0.56   IGV  0.6509  0.5575
116   SHOP  2026-06-30 10:16:00  114.824997  114.824997  114.720100  114.800003    1320.0  2026-06-30  113.00      114.21    0.54   IGV  0.6509  0.5575
117   SHOP  2026-06-30 10:17:00  114.805000  114.860001  114.459999  114.529999   12027.0  2026-06-30  113.00      114.21    0.52   IGV  0.6509  0.5575
118   SHOP  2026-06-30 10:18:00  114.550003  114.629997  114.400002  114.449997   19105.0  2026-06-30  113.00      114.21    0.30   IGV  0.6509  0.5575
119   SHOP  2026-06-30 10:19:00  114.495003  114.629997  114.410004  114.559998   13509.0  2026-06-30  113.00      114.21    0.25   IGV  0.6509  0.5575
120   SHOP  2026-06-30 10:20:00  114.480003  114.730003  114.410004  114.720001    5746.0  2026-06-30  113.00      114.21    0.24   IGV  0.6509  0.5575
121   SHOP  2026-06-30 10:21:00  114.760002  114.800003  114.669998  114.779999   10087.0  2026-06-30  113.00      114.21    0.48   IGV  0.6509  0.5575
122   SHOP  2026-06-30 10:22:00  114.779999  114.900002  114.720001  114.889999    6603.0  2026-06-30  113.00      114.21    0.50   IGV  0.6509  0.5575
123   SHOP  2026-06-30 10:23:00  114.855003  114.930000  114.720001  114.809998   11871.0  2026-06-30  113.00      114.21    0.56   IGV  0.6509  0.5575
124   SHOP  2026-06-30 10:24:00  114.830002  114.930000  114.779999  114.910004   18749.0  2026-06-30  113.00      114.21    0.54   IGV  0.6509  0.5575
125   SHOP  2026-06-30 10:25:00  114.889999  114.910004  114.779999  114.879997    3809.0  2026-06-30  113.00      114.21    0.60   IGV  0.6509  0.5575
126   SHOP  2026-06-30 10:26:00  114.820000  114.959999  114.699997  114.959999    4679.0  2026-06-30  113.00      114.21    0.53   IGV  0.6509  0.5575
127   SHOP  2026-06-30 10:27:00  114.919998  114.919998  114.839996  114.839996    1500.0  2026-06-30  113.00      114.21    0.62   IGV  0.6509  0.5575

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta
0,SHOP,2026-06-30 00:01:00,114.250000,114.250000,114.250000,114.250000,12.0,2026-06-30,113.00,114.21,0.04,IGV,0.6509,0.5575
1,SHOP,2026-06-30 00:09:00,114.300003,114.330002,114.300003,114.330002,26.0,2026-06-30,113.00,114.21,0.08,IGV,0.6509,0.5575
2,SHOP,2026-06-30 00:26:00,114.449997,114.449997,114.430000,114.430000,200.0,2026-06-30,113.00,114.21,0.21,IGV,0.6509,0.5575
3,SHOP,2026-06-30 00:28:00,114.419998,114.419998,114.410004,114.410004,36.0,2026-06-30,113.00,114.21,0.18,IGV,0.6509,0.5575
4,SHOP,2026-06-30 00:29:00,114.400002,114.400002,114.400002,114.400002,100.0,2026-06-30,113.00,114.21,0.17,IGV,0.6509,0.5575
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,SHV,2026-06-30 07:56:00,110.339996,110.339996,110.339996,110.339996,369.0,2026-06-30,110.34,110.34,-0.00,IWM,-0.0486,-0.0007
616,SHV,2026-06-30 07:57:00,110.340302,110.340302,110.340302,110.340302,150.0,2026-06-30,110.34,110.34,0.00,IWM,-0.0486,-0.0007
617,SHV,2026-06-30 08:01:00,110.339996,110.339996,110.339996,110.339996,300.0,2026-06-30,110.34,110.34,-0.00,IWM,-0.0486,-0.0007
618,SHV,2026-06-30 08:08:00,110.339996,110.339996,110.339996,110.339996,5800.0,2026-06-30,110.34,110.34,-0.00,IWM,-0.0486,-0.0007
619,SHV,2026-06-30 08:17:00,110.340302,110.340302,110.340302,110.340302,100.0,2026-06-30,110.34,110.34,0.00,IWM,-0.0486,-0.0007

In [32]:
# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [33]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=12,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 28 тікерів (пропущено 0 по старому маніфесту) | 2026-05-10 00:00:00 → 2026-08-10 23:59:59 | interval=1 | next batch #0110 | run=946a2075

   workers: tickers=12, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-05-10 → 2026-08-08 (91 днів)

   📈 обробляються дні: 2026-08-09 → 2026-08-10 (2 днів)

   psutil · старт · 🧠 RAM: 1,514.7 MB

[10/28] ✓ FXI: 468 рядків |  35.71% | ETA 00:01

[20/28] ✓ SPY: 1,285 рядків |  71.43% | ETA 00:00

[28/28] ✓ XOP: 507 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 1,567.0 MB

💾 batch 110 → 19,722 рядків (всього 19,722 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\ETF\intraday_0110.csv.gz

   ✅ після flush · 🧠 RAM: 1,563.2 MB

   🔚 фінал · 🧠 RAM: 1,563.2 MB

🏁 Готово. Нових рядків: 19,722 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:01

In [34]:
# Один прохід по ETF-батчах: premarket-рядки + денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc_etf.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    build_oc=True,
    max_workers=4,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  files=110 workers=4

  [1/110] intraday_0004.csv.gz  in=1,760 out=1,760 elapsed=0.0s

  [2/110] intraday_0003.csv.gz  in=10,518 out=10,518 elapsed=0.1s

  [3/110] intraday_0002.csv.gz  in=20,691 out=20,691 elapsed=0.1s

  [4/110] intraday_0005.csv.gz  in=31,264 out=31,264 elapsed=0.1s

  [5/110] intraday_0006.csv.gz  in=41,355 out=41,355 elapsed=0.1s

  [6/110] intraday_0007.csv.gz  in=51,502 out=51,502 elapsed=0.2s

  [7/110] intraday_0008.csv.gz  in=62,186 out=62,186 elapsed=0.2s

  [8/110] intraday_0010.csv.gz  in=63,633 out=63,633 elapsed=0.2s

  [9/110] intraday_0009.csv.gz  in=72,207 out=72,207 elapsed=0.2s

  [10/110] intraday_0011.csv.gz  in=81,941 out=81,941 elapsed=0.2s

  [11/110] intraday_0012.csv.gz  in=91,152 out=91,152 elapsed=0.2s

  [12/110] intraday_0013.csv.gz  in=100,754 out=100,754 elapsed=0.2s

  [13/110] intraday_0016.csv.gz  in=102,125 out=102,125 elapsed=0.3s

  [14/110] intraday_0015.csv.gz  in=110,402 out=110,402 elapsed=0.3s

  [15/110] intraday_0014.csv.gz  in=120,035 out=120,035 elapsed=0.3s

  [16/110] intraday_0017.csv.gz  in=129,351 out=129,351 elapsed=0.3s

  [17/110] intraday_0018.csv.gz  in=138,578 out=138,578 elapsed=0.4s

  [18/110] intraday_0019.csv.gz  in=148,074 out=148,074 elapsed=0.4s

  [19/110] intraday_0021.csv.gz  in=149,677 out=149,677 elapsed=0.4s

  [20/110] intraday_0020.csv.gz  in=157,847 out=157,847 elapsed=0.4s

  [21/110] intraday_0023.csv.gz  in=167,662 out=167,662 elapsed=0.5s

  [22/110] intraday_0022.csv.gz  in=196,862 out=196,862 elapsed=0.5s

  [23/110] intraday_0024.csv.gz  in=218,002 out=218,002 elapsed=0.5s

  [24/110] intraday_0026.csv.gz  in=226,279 out=226,279 elapsed=0.5s

  [25/110] intraday_0027.csv.gz  in=235,077 out=235,077 elapsed=0.7s

  [26/110] intraday_0028.csv.gz  in=244,053 out=244,053 elapsed=0.8s

  [27/110] intraday_0029.csv.gz  in=252,994 out=252,994 elapsed=0.8s

  [28/110] intraday_0030.csv.gz  in=262,243 out=262,243 elapsed=0.9s

  [29/110] intraday_0031.csv.gz  in=271,145 out=271,145 elapsed=0.9s

  [30/110] intraday_0032.csv.gz  in=279,924 out=279,924 elapsed=1.0s

  [31/110] intraday_0033.csv.gz  in=288,701 out=288,701 elapsed=1.0s

  [32/110] intraday_0025.csv.gz  in=393,143 out=393,143 elapsed=1.0s

  [33/110] intraday_0035.csv.gz  in=401,855 out=401,855 elapsed=1.0s

  [34/110] intraday_0034.csv.gz  in=410,508 out=410,508 elapsed=1.0s

  [35/110] intraday_0036.csv.gz  in=419,433 out=419,433 elapsed=1.1s

  [36/110] intraday_0038.csv.gz  in=428,315 out=428,315 elapsed=1.1s

  [37/110] intraday_0037.csv.gz  in=437,237 out=437,237 elapsed=1.1s

  [38/110] intraday_0039.csv.gz  in=445,326 out=445,326 elapsed=1.1s

  [39/110] intraday_0040.csv.gz  in=453,919 out=453,919 elapsed=1.2s

  [40/110] intraday_0041.csv.gz  in=463,227 out=463,227 elapsed=1.2s

  [41/110] intraday_0042.csv.gz  in=471,406 out=471,406 elapsed=1.2s

  [42/110] intraday_0044.csv.gz  in=479,923 out=479,923 elapsed=1.2s

  [43/110] intraday_0045.csv.gz  in=487,104 out=487,104 elapsed=1.2s

  [44/110] intraday_0043.csv.gz  in=495,099 out=495,099 elapsed=1.2s

  [45/110] intraday_0046.csv.gz  in=503,465 out=503,465 elapsed=1.3s

  [46/110] intraday_0047.csv.gz  in=511,813 out=511,813 elapsed=1.3s

  [47/110] intraday_0048.csv.gz  in=520,121 out=520,121 elapsed=1.3s

  [48/110] intraday_0049.csv.gz  in=528,683 out=528,683 elapsed=1.3s

  [49/110] intraday_0050.csv.gz  in=536,960 out=536,960 elapsed=1.5s

  [50/110] intraday_0051.csv.gz  in=545,156 out=545,156 elapsed=1.5s

  [51/110] intraday_0052.csv.gz  in=553,430 out=553,430 elapsed=1.5s

  [52/110] intraday_0001.csv.gz  in=1,140,350 out=1,140,350 elapsed=1.5s

  [53/110] intraday_0054.csv.gz  in=1,148,330 out=1,148,330 elapsed=1.5s

  [54/110] intraday_0053.csv.gz  in=1,156,344 out=1,156,344 elapsed=1.5s

  [55/110] intraday_0057.csv.gz  in=1,165,167 out=1,165,167 elapsed=1.6s

  [56/110] intraday_0056.csv.gz  in=1,173,385 out=1,173,385 elapsed=1.6s

  [57/110] intraday_0058.csv.gz  in=1,181,781 out=1,181,781 elapsed=1.6s

  [58/110] intraday_0059.csv.gz  in=1,189,748 out=1,189,748 elapsed=1.7s

  [59/110] intraday_0061.csv.gz  in=1,197,998 out=1,197,998 elapsed=1.7s

  [60/110] intraday_0060.csv.gz  in=1,206,064 out=1,206,064 elapsed=1.7s

  [61/110] intraday_0063.csv.gz  in=1,214,390 out=1,214,390 elapsed=1.7s

  [62/110] intraday_0062.csv.gz  in=1,222,519 out=1,222,519 elapsed=1.7s

  [63/110] intraday_0064.csv.gz  in=1,230,741 out=1,230,741 elapsed=1.7s

  [64/110] intraday_0065.csv.gz  in=1,239,106 out=1,239,106 elapsed=1.7s

  [65/110] intraday_0066.csv.gz  in=1,246,888 out=1,246,888 elapsed=1.8s

  [66/110] intraday_0055.csv.gz  in=1,360,697 out=1,360,697 elapsed=1.8s

  [67/110] intraday_0067.csv.gz  in=1,368,954 out=1,368,954 elapsed=1.8s

  [68/110] intraday_0068.csv.gz  in=1,377,472 out=1,377,472 elapsed=1.8s

  [69/110] intraday_0070.csv.gz  in=1,395,056 out=1,395,056 elapsed=1.9s

  [70/110] intraday_0071.csv.gz  in=1,412,694 out=1,412,694 elapsed=1.9s

  [71/110] intraday_0072.csv.gz  in=1,430,041 out=1,430,041 elapsed=1.9s

  [72/110] intraday_0073.csv.gz  in=1,447,121 out=1,447,121 elapsed=1.9s

  [73/110] intraday_0074.csv.gz  in=1,464,856 out=1,464,856 elapsed=2.0s

  [74/110] intraday_0075.csv.gz  in=1,482,239 out=1,482,239 elapsed=2.0s

  [75/110] intraday_0077.csv.gz  in=1,484,607 out=1,484,607 elapsed=2.0s

  [76/110] intraday_0076.csv.gz  in=1,501,364 out=1,501,364 elapsed=2.0s

  [77/110] intraday_0078.csv.gz  in=1,518,960 out=1,518,960 elapsed=2.0s

  [78/110] intraday_0079.csv.gz  in=1,535,445 out=1,535,445 elapsed=2.0s

  [79/110] intraday_0080.csv.gz  in=1,552,382 out=1,552,382 elapsed=2.1s

  [80/110] intraday_0082.csv.gz  in=1,569,251 out=1,569,251 elapsed=2.1s

  [81/110] intraday_0081.csv.gz  in=1,586,413 out=1,586,413 elapsed=2.1s

  [82/110] intraday_0083.csv.gz  in=1,604,362 out=1,604,362 elapsed=2.3s

  [83/110] intraday_0085.csv.gz  in=1,621,286 out=1,621,286 elapsed=2.4s

  [84/110] intraday_0084.csv.gz  in=1,638,586 out=1,638,586 elapsed=2.4s

  [85/110] intraday_0087.csv.gz  in=1,655,403 out=1,655,403 elapsed=2.7s

  [86/110] intraday_0086.csv.gz  in=1,672,374 out=1,672,374 elapsed=2.7s

  [87/110] intraday_0088.csv.gz  in=1,690,115 out=1,690,115 elapsed=2.7s

  [88/110] intraday_0090.csv.gz  in=1,706,513 out=1,706,513 elapsed=2.8s

  [89/110] intraday_0091.csv.gz  in=1,723,628 out=1,723,628 elapsed=2.8s

  [90/110] intraday_0093.csv.gz  in=1,723,637 out=1,723,637 elapsed=2.8s

  [91/110] intraday_0092.csv.gz  in=1,739,852 out=1,739,852 elapsed=3.0s

  [92/110] intraday_0094.csv.gz  in=1,758,814 out=1,758,814 elapsed=3.0s

  [93/110] intraday_0095.csv.gz  in=1,775,367 out=1,775,367 elapsed=3.1s

  [94/110] intraday_0096.csv.gz  in=1,793,285 out=1,793,285 elapsed=3.1s

  [95/110] intraday_0097.csv.gz  in=1,809,447 out=1,809,447 elapsed=3.1s

  [96/110] intraday_0099.csv.gz  in=1,811,057 out=1,811,057 elapsed=3.2s

  [97/110] intraday_0098.csv.gz  in=1,826,746 out=1,826,746 elapsed=3.2s

  [98/110] intraday_0089.csv.gz  in=1,954,305 out=1,954,305 elapsed=3.2s

  [99/110] intraday_0100.csv.gz  in=1,970,821 out=1,970,821 elapsed=3.2s

  [100/110] intraday_0101.csv.gz  in=1,987,634 out=1,987,634 elapsed=3.3s

  [101/110] intraday_0103.csv.gz  in=2,006,707 out=2,006,707 elapsed=3.3s

  [102/110] intraday_0105.csv.gz  in=2,025,920 out=2,025,920 elapsed=3.4s

  [103/110] intraday_0106.csv.gz  in=2,045,930 out=2,045,930 elapsed=3.5s

  [104/110] intraday_0102.csv.gz  in=2,278,015 out=2,278,015 elapsed=3.8s

  [105/110] intraday_0107.csv.gz  in=2,297,882 out=2,297,882 elapsed=3.8s

  [106/110] intraday_0069.csv.gz  in=3,043,135 out=3,043,135 elapsed=3.8s

  [107/110] intraday_0110.csv.gz  in=3,062,857 out=3,062,857 elapsed=3.9s

  [108/110] intraday_0108.csv.gz  in=3,081,897 out=3,081,897 elapsed=3.9s

  [109/110] intraday_0109.csv.gz  in=3,099,353 out=3,099,353 elapsed=3.9s

  [110/110] intraday_0104.csv.gz  in=3,685,579 out=3,685,579 elapsed=4.7s

✅ DONE  in=3,685,579 → out=3,685,579  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 4.7s

In [35]:
# oc_etf.parquet уже побудовано в клітинці 34 (той самий прохід по файлах).
_oc_etf_path = str(WORK_DIR / "oc_etf.parquet")
if os.path.exists(_oc_etf_path):
    df_oc = pd.read_parquet(_oc_etf_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(ETF_DIR), out_path=_oc_etf_path)
print(df_oc.head())

  ticker        date   open  close
0   ARKK  2026-05-01  75.85  76.84
1   ARKK  2026-05-04  77.24  78.21
2   ARKK  2026-05-05  78.40  76.62
3   ARKK  2026-05-06  77.33  79.54
4   ARKK  2026-05-07  79.40  78.09

In [36]:
# Ті самі оптимізовані функції, що й у клітинці 22 — тут лише інші дефолти обгортки
# (ETF-файли замість акційних).
def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [37]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=3,685,579  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 5.0s

Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [38]:
# Та сама оптимізована add_pct_vs_prev_close_parquet із клітинки 24 —
# тут лише інші дефолти обгортки (ETF-файли, колонка Bench%).
def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",              # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [39]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=3,685,579  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 3.1s

Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [40]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий по ключах ('bench'↔'ticker', 'dt').

    Прискорення: ETF-мапа читається одним pq.read_table (лише 3 потрібні колонки)
    замість iter_batches + concat + gc; ключ 'dt' лишається рядком —
    лексикографічний порядок 'YYYY-MM-DD HH:MM:SS' збігається з хронологічним,
    тож per-row парсинг дат не потрібен (крім align_to_minute=True).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    t0 = time.time()

    # ---------- 1) Мапа з ETF-файла: (bench, dt) -> Bench% ----------
    etf_names = [f.name for f in pq.ParquetFile(etf_path).schema_arrow]
    cl = {c.lower().strip(): c for c in etf_names}
    for col in ("ticker", "dt"):
        if col not in cl:
            raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")
    val_col = cl.get("bench%") or cl.get("pct_vs_prev_close")
    if val_col is None:
        raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

    etf_map = pq.read_table(etf_path, columns=[cl["ticker"], cl["dt"], val_col]).to_pandas()
    etf_map.columns = ["bench", "dt", "Bench%"]
    etf_map["bench"] = etf_map["bench"].astype(str).str.strip().str.upper()
    etf_map["Bench%"] = pd.to_numeric(etf_map["Bench%"], errors="coerce")
    if round_decimals is not None:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    _dt_is_str = (etf_map["dt"].dtype == object) or pd.api.types.is_string_dtype(etf_map["dt"])
    if align_to_minute or not _dt_is_str:
        etf_map["dt"] = pd.to_datetime(etf_map["dt"], errors="coerce")
        if align_to_minute:
            etf_map["dt"] = etf_map["dt"].dt.floor("T")
    else:
        etf_map["dt"] = etf_map["dt"].astype(str)

    etf_map = (etf_map.dropna(subset=["dt"])
                      .sort_values(["bench", "dt"], kind="stable")
                      .drop_duplicates(subset=["bench", "dt"], keep="last")
                      .reset_index(drop=True))

    # ---------- 2) Потоково проходимо базовий файл ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_path}", flush=True)
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        codes, cats = _ticker_codes(df["bench"])
        df["bench"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)

        _base_dt_is_str = (df["dt"].dtype == object) or pd.api.types.is_string_dtype(df["dt"])
        if align_to_minute or not _base_dt_is_str:
            df["dt"] = pd.to_datetime(df["dt"], errors="coerce")
            if align_to_minute:
                df["dt"] = df["dt"].dt.floor("T")
        else:
            df["dt"] = df["dt"].astype(str)

        merged = df.merge(etf_map, on=["bench", "dt"], how="left")

        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = [c for c in merged.columns if c != "Bench%"]
            pos = cols.index(insert_before)
            merged = merged[cols[:pos] + ["Bench%"] + cols[pos:]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [41]:
merge_bench_pct_from_etf(
    base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    batch_rows=2_000_000,
    align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
    round_decimals=2,
    insert_before=None,          # або, наприклад, "pct_vs_prev_close"
    compression="snappy",
)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet

[batch    5] rows=10,000,000  elapsed=26.7s

[batch   10] rows=20,000,000  elapsed=46.8s

[batch   15] rows=30,000,000  elapsed=66.9s

[batch   20] rows=40,000,000  elapsed=86.7s

[batch   25] rows=50,000,000  elapsed=106.7s

[batch   30] rows=60,000,000  elapsed=126.8s

[batch   35] rows=70,000,000  elapsed=146.7s

[batch   40] rows=80,000,000  elapsed=166.5s

[batch   45] rows=90,000,000  elapsed=187.0s

[batch   50] rows=100,000,000  elapsed=207.9s

[batch   55] rows=110,000,000  elapsed=231.3s

[batch   60] rows=120,000,000  elapsed=255.1s

[batch   65] rows=130,000,000  elapsed=279.5s

[batch   70] rows=138,784,988  elapsed=301.1s

✅ DONE rows=138,784,988 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet  in 301.1s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct.parquet'

In [42]:
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed


def _pick_first_existing(df: pd.DataFrame, candidates):
    cols_l = {c.lower().strip(): c for c in df.columns}
    for c in candidates:
        if c.lower() in cols_l:
            return cols_l[c.lower()]
    return None


def get_reports(ticker, last_n_reports, start_date, end_date):
    try:
        params = {
            "ticker": str(ticker),
            "start_move_date": str(start_date)[:10],
            "end_move_date": str(end_date)[:10],
        }
        reports_df = DatumApi.data_request("/reports", params)
        if reports_df is None or reports_df.empty:
            return pd.DataFrame(columns=["ticker", "report_date"])

        date_col = _pick_first_existing(
            reports_df,
            ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"],
        )
        if date_col is None:
            return pd.DataFrame(columns=["ticker", "report_date"])

        out = reports_df.copy()
        out["report_date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
        out["ticker"] = str(ticker).upper()
        out = out.dropna(subset=["report_date"])
        out = out.sort_values("report_date").tail(int(last_n_reports))
        return out[["ticker", "report_date"]].reset_index(drop=True)
    except Exception as e:
        print(f"Report fetch failed for {ticker}: {e}")
        return pd.DataFrame(columns=["ticker", "report_date"])


def get_reports_for_tickers(tickers_df, start_date, end_date, last_n_reports=20, max_workers=16):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    parts = []

    def fetch(t):
        return get_reports(ticker=t, last_n_reports=last_n_reports, start_date=start_date, end_date=end_date)

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Reports"):
            rep = f.result()
            if rep is not None and not rep.empty:
                parts.append(rep)

    if not parts:
        return pd.DataFrame(columns=["ticker", "report_date"]), {}

    reports = pd.concat(parts, ignore_index=True).drop_duplicates(["ticker", "report_date"])
    report_days_map = reports.groupby("ticker")["report_date"].apply(set).to_dict()
    return reports, report_days_map


def get_gaps_for_tickers_excluding_reports(tickers_df, start_date, end_date, report_days_map, max_workers=16):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()

    def fetch(t):
        params = {
            "ticker": t,
            "start_date": str(start_date)[:10],
            "end_date": str(end_date)[:10],
            "format": "json_records",
        }
        try:
            df_gap = DatumApi.data_request("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                return None

            date_col = _pick_first_existing(df_gap, ["date", "move_date", "dt", "datetime", "day"])
            if date_col is None:
                return None

            out = df_gap.copy()
            out["ticker"] = out["ticker"].astype(str).str.upper() if "ticker" in out.columns else t
            out["date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
            out["gap"] = pd.to_numeric(out.get("gap"), errors="coerce")
            out = out.dropna(subset=["date", "gap"])

            report_days = report_days_map.get(t, set())
            if report_days:
                out = out[~out["date"].isin(report_days)]

            return out if not out.empty else None
        except Exception as e:
            print(f"Gap fetch failed for {t}: {e}")
            return None

    all_results = []
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Gaps (ex-reports)"):
            result = f.result()
            if result is not None:
                all_results.append(result)

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    return pd.DataFrame(columns=["ticker", "date", "gap"])


def add_rolling_sigma_cap(
    df,
    value_col,
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=None,
):
    """Rolling std по попередньому вікну з обрізанням хвостів на квантилі cap_q.

    Раніше це був rolling(...).apply(python_func) — окремий виклик Python на кожне
    вікно кожного тікера. Тепер вікна будуються через sliding_window_view і квантиль/
    clip/std рахуються одразу по всій матриці вікон групи (чисто numpy).
    Результат збігається з попередньою реалізацією до 1e-12.
    """
    if min_periods is None:
        min_periods = window

    out = df.sort_values([group_col, date_col], kind="stable").copy()
    col = f"{value_col}_sigma_{window}d_cap"

    # Рідкісний випадок min_periods != window має іншу семантику (часткові вікна) —
    # там лишаємо стару, повільну, але точну реалізацію.
    if min_periods != window:
        def compute_sigma(s):
            x = s.shift(1)

            def f(arr):
                arr = arr[~np.isnan(arr)]
                if len(arr) < min_periods:
                    return np.nan
                cap = np.quantile(np.abs(arr), cap_q)
                arr_capped = np.clip(arr, -cap, cap)
                return np.std(arr_capped, ddof=1)

            return x.rolling(window, min_periods=min_periods).apply(f, raw=True)

        out[col] = out.groupby(group_col)[value_col].transform(compute_sigma)
        return out

    vals = pd.to_numeric(out[value_col], errors="coerce").to_numpy(dtype="float64")
    codes, _ = pd.factorize(out[group_col], sort=False)
    res = np.full(vals.shape, np.nan)

    order = np.argsort(codes, kind="stable")
    bounds = np.flatnonzero(np.diff(codes[order])) + 1
    for sl in np.split(order, bounds):
        n = sl.size
        if n <= window:
            continue
        x = vals[sl]
        # вікно з ПОПЕРЕДНІХ значень (еквівалент shift(1) у старій версії)
        w = np.lib.stride_tricks.sliding_window_view(x[:-1], window)   # (n-window, window)
        cap = np.quantile(np.abs(w), cap_q, axis=1, keepdims=True)
        res[sl[window:]] = np.clip(w, -cap, cap).std(axis=1, ddof=1)

    out[col] = res
    return out


# 1) Report days in the working window
reports_df, report_days_map = get_reports_for_tickers(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    max_workers=16,
)
print("Report rows:", len(reports_df))

# 2) Gaps without report days
df_gaps_all = get_gaps_for_tickers_excluding_reports(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    report_days_map=report_days_map,
    max_workers=16,
)
print("Rows in gaps (without report days):", len(df_gaps_all))

# 3) Rolling sigma
sigma_daily = add_rolling_sigma_cap(
    df=df_gaps_all,
    value_col="gap",
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=20,
)

sigma_col = "gap_sigma_20d_cap"

std_by_ticker = (
    sigma_daily.dropna(subset=[sigma_col])
    .sort_values(["ticker", "date"])
    .groupby("ticker", as_index=False)
    .tail(1)[["ticker", sigma_col]]
    .rename(columns={sigma_col: "sigma"})
    .reset_index(drop=True)
)

print("Tickers with sigma:", len(std_by_ticker))
std_by_ticker.head()

Reports:   0%|          | 0/7269 [00:00<?, ?it/s]

Reports:   0%|          | 8/7269 [00:00<01:43, 69.86it/s]

Reports:   0%|          | 17/7269 [00:00<02:08, 56.26it/s]

Reports:   0%|          | 32/7269 [00:00<01:22, 87.63it/s]

Reports:   1%|          | 42/7269 [00:00<01:43, 69.57it/s]

Reports:   1%|          | 51/7269 [00:00<01:40, 71.67it/s]

Reports:   1%|          | 59/7269 [00:00<01:41, 71.21it/s]

Reports:   1%|          | 67/7269 [00:00<01:38, 72.95it/s]

Reports:   1%|          | 77/7269 [00:01<01:33, 77.21it/s]

Reports:   1%|          | 85/7269 [00:01<01:38, 72.93it/s]

Reports:   1%|▏         | 98/7269 [00:01<01:34, 76.14it/s]

Reports:   1%|▏         | 106/7269 [00:01<01:41, 70.89it/s]

Reports:   2%|▏         | 115/7269 [00:01<01:37, 73.29it/s]

Reports:   2%|▏         | 123/7269 [00:01<01:35, 74.98it/s]

Reports:   2%|▏         | 133/7269 [00:01<01:35, 74.97it/s]

Reports:   2%|▏         | 141/7269 [00:01<01:37, 73.08it/s]

Reports:   2%|▏         | 152/7269 [00:02<01:34, 75.58it/s]

Reports:   2%|▏         | 165/7269 [00:02<01:29, 79.50it/s]

Reports:   2%|▏         | 175/7269 [00:02<01:31, 77.87it/s]

Reports:   3%|▎         | 187/7269 [00:02<01:23, 84.93it/s]

Reports:   3%|▎         | 197/7269 [00:02<01:21, 87.25it/s]

Reports:   3%|▎         | 206/7269 [00:02<01:22, 86.11it/s]

Reports:   3%|▎         | 215/7269 [00:02<01:20, 87.12it/s]

Reports:   3%|▎         | 224/7269 [00:02<01:27, 80.13it/s]

Reports:   3%|▎         | 236/7269 [00:03<01:24, 83.33it/s]

Reports:   3%|▎         | 245/7269 [00:03<02:01, 57.68it/s]

Reports:   4%|▎         | 256/7269 [00:03<01:44, 67.32it/s]

Reports:   4%|▎         | 264/7269 [00:03<01:47, 65.06it/s]

Reports:   4%|▍         | 275/7269 [00:03<01:34, 74.08it/s]

Reports:   4%|▍         | 284/7269 [00:03<01:48, 64.59it/s]

Reports:   4%|▍         | 293/7269 [00:03<01:43, 67.61it/s]

Reports:   4%|▍         | 303/7269 [00:04<01:39, 70.05it/s]

Reports:   4%|▍         | 311/7269 [00:04<02:00, 57.90it/s]

Reports:   4%|▍         | 326/7269 [00:04<01:39, 70.07it/s]

Reports:   5%|▍         | 335/7269 [00:04<01:35, 72.44it/s]

Reports:   5%|▍         | 343/7269 [00:04<01:34, 73.38it/s]

Reports:   5%|▍         | 354/7269 [00:04<01:25, 80.81it/s]

Reports:   5%|▍         | 363/7269 [00:04<01:30, 76.02it/s]

Reports:   5%|▌         | 374/7269 [00:05<01:26, 79.60it/s]

Reports:   5%|▌         | 383/7269 [00:05<01:26, 79.40it/s]

Reports:   5%|▌         | 393/7269 [00:05<01:31, 74.99it/s]

Reports:   6%|▌         | 406/7269 [00:05<01:17, 88.51it/s]

Reports:   6%|▌         | 416/7269 [00:05<01:30, 75.99it/s]

Reports:   6%|▌         | 425/7269 [00:05<01:26, 79.21it/s]

Reports:   6%|▌         | 434/7269 [00:05<01:26, 78.90it/s]

Reports:   6%|▌         | 444/7269 [00:05<01:20, 84.32it/s]

Reports:   6%|▋         | 456/7269 [00:06<01:12, 93.51it/s]

Reports:   6%|▋         | 466/7269 [00:06<01:18, 87.15it/s]

Reports:   7%|▋         | 477/7269 [00:06<01:16, 89.19it/s]

Reports:   7%|▋         | 487/7269 [00:06<01:16, 88.14it/s]

Reports:   7%|▋         | 498/7269 [00:06<01:14, 90.92it/s]

Reports:   7%|▋         | 508/7269 [00:06<01:13, 92.42it/s]

Reports:   7%|▋         | 518/7269 [00:06<01:21, 83.05it/s]

Reports:   7%|▋         | 527/7269 [00:06<01:19, 84.82it/s]

Reports:   7%|▋         | 536/7269 [00:06<01:21, 82.83it/s]

Reports:   8%|▊         | 547/7269 [00:07<01:14, 89.75it/s]

Reports:   8%|▊         | 557/7269 [00:07<01:18, 85.77it/s]

Reports:   8%|▊         | 566/7269 [00:07<01:21, 81.76it/s]

Reports:   8%|▊         | 576/7269 [00:07<01:20, 83.34it/s]

Reports:   8%|▊         | 590/7269 [00:07<01:22, 80.53it/s]

Reports:   8%|▊         | 606/7269 [00:07<01:17, 85.85it/s]

Reports:   9%|▊         | 620/7269 [00:07<01:10, 94.41it/s]

Reports:   9%|▊         | 630/7269 [00:08<01:17, 85.55it/s]

Reports:   9%|▉         | 640/7269 [00:08<01:17, 85.78it/s]

Reports:   9%|▉         | 649/7269 [00:08<01:19, 83.33it/s]

Reports:   9%|▉         | 659/7269 [00:08<01:17, 85.33it/s]

Reports:   9%|▉         | 672/7269 [00:08<01:09, 95.15it/s]

Reports:   9%|▉         | 682/7269 [00:08<01:14, 88.46it/s]

Reports:  10%|▉         | 692/7269 [00:08<01:17, 84.51it/s]

Reports:  10%|▉         | 701/7269 [00:08<01:18, 84.13it/s]

Reports:  10%|▉         | 710/7269 [00:09<01:23, 78.70it/s]

Reports:  10%|▉         | 723/7269 [00:09<01:17, 84.44it/s]

Reports:  10%|█         | 732/7269 [00:09<01:16, 85.67it/s]

Reports:  10%|█         | 741/7269 [00:09<01:17, 84.46it/s]

Reports:  10%|█         | 756/7269 [00:09<01:16, 84.74it/s]

Reports:  11%|█         | 771/7269 [00:09<01:09, 93.36it/s]

Reports:  11%|█         | 781/7269 [00:09<01:14, 87.25it/s]

Reports:  11%|█         | 790/7269 [00:09<01:22, 78.73it/s]

Reports:  11%|█         | 804/7269 [00:10<01:16, 84.74it/s]

Reports:  11%|█▏        | 820/7269 [00:10<01:13, 87.55it/s]

Reports:  12%|█▏        | 836/7269 [00:10<01:10, 91.35it/s]

Reports:  12%|█▏        | 846/7269 [00:10<01:13, 87.12it/s]

Reports:  12%|█▏        | 857/7269 [00:10<01:10, 91.10it/s]

Reports:  12%|█▏        | 869/7269 [00:10<01:11, 88.93it/s]

Reports:  12%|█▏        | 878/7269 [00:10<01:18, 80.98it/s]

Reports:  12%|█▏        | 892/7269 [00:11<01:13, 86.30it/s]

Reports:  12%|█▏        | 905/7269 [00:11<01:07, 94.22it/s]

Reports:  13%|█▎        | 915/7269 [00:11<01:07, 94.40it/s]

Reports:  13%|█▎        | 925/7269 [00:11<01:14, 84.78it/s]

Reports:  13%|█▎        | 936/7269 [00:11<01:12, 87.56it/s]

Reports:  13%|█▎        | 946/7269 [00:11<01:09, 90.49it/s]

Reports:  13%|█▎        | 956/7269 [00:11<01:09, 90.71it/s]

Reports:  13%|█▎        | 966/7269 [00:11<01:12, 86.79it/s]

Reports:  13%|█▎        | 975/7269 [00:12<01:23, 75.42it/s]

Reports:  14%|█▎        | 990/7269 [00:12<01:10, 89.56it/s]

Reports:  14%|█▍        | 1000/7269 [00:12<01:10, 88.44it/s]

Reports:  14%|█▍        | 1010/7269 [00:12<01:23, 75.07it/s]

Reports:  14%|█▍        | 1023/7269 [00:12<01:16, 81.79it/s]

Reports:  14%|█▍        | 1032/7269 [00:12<01:14, 83.60it/s]

Reports:  14%|█▍        | 1041/7269 [00:12<01:21, 75.99it/s]

Reports:  15%|█▍        | 1055/7269 [00:13<01:15, 82.20it/s]

Reports:  15%|█▍        | 1064/7269 [00:13<01:19, 78.38it/s]

Reports:  15%|█▍        | 1073/7269 [00:13<01:21, 76.28it/s]

Reports:  15%|█▍        | 1081/7269 [00:13<01:22, 75.12it/s]

Reports:  15%|█▌        | 1092/7269 [00:13<01:15, 81.56it/s]

Reports:  15%|█▌        | 1101/7269 [00:13<01:18, 78.19it/s]

Reports:  15%|█▌        | 1112/7269 [00:13<01:16, 80.81it/s]

Reports:  15%|█▌        | 1121/7269 [00:13<01:17, 79.83it/s]

Reports:  16%|█▌        | 1131/7269 [00:14<01:20, 76.57it/s]

Reports:  16%|█▌        | 1143/7269 [00:14<01:14, 81.86it/s]

Reports:  16%|█▌        | 1152/7269 [00:14<01:40, 60.90it/s]

Reports:  16%|█▌        | 1162/7269 [00:14<01:28, 68.90it/s]

Reports:  16%|█▌        | 1170/7269 [00:14<01:31, 66.44it/s]

Reports:  16%|█▌        | 1180/7269 [00:14<01:25, 71.26it/s]

Reports:  16%|█▋        | 1188/7269 [00:14<01:22, 73.30it/s]

Reports:  16%|█▋        | 1199/7269 [00:14<01:22, 73.57it/s]

Reports:  17%|█▋        | 1212/7269 [00:15<01:12, 83.33it/s]

Reports:  17%|█▋        | 1221/7269 [00:15<01:24, 71.94it/s]

Reports:  17%|█▋        | 1231/7269 [00:15<01:18, 76.66it/s]

Reports:  17%|█▋        | 1240/7269 [00:15<01:18, 76.90it/s]

Reports:  17%|█▋        | 1248/7269 [00:15<01:20, 74.50it/s]

Reports:  17%|█▋        | 1260/7269 [00:15<01:12, 83.11it/s]

Reports:  17%|█▋        | 1269/7269 [00:15<01:18, 76.83it/s]

Reports:  18%|█▊        | 1280/7269 [00:16<01:15, 79.47it/s]

Reports:  18%|█▊        | 1289/7269 [00:16<01:32, 64.92it/s]

Reports:  18%|█▊        | 1302/7269 [00:16<01:16, 77.52it/s]

Reports:  18%|█▊        | 1311/7269 [00:16<01:22, 72.28it/s]

Reports:  18%|█▊        | 1319/7269 [00:16<01:20, 73.51it/s]

Reports:  18%|█▊        | 1327/7269 [00:16<01:22, 72.14it/s]

Reports:  18%|█▊        | 1337/7269 [00:16<01:18, 75.97it/s]

Reports:  19%|█▊        | 1345/7269 [00:16<01:17, 75.99it/s]

Reports:  19%|█▊        | 1356/7269 [00:17<01:10, 83.62it/s]

Reports:  19%|█▉        | 1366/7269 [00:17<01:07, 87.00it/s]

Reports:  19%|█▉        | 1375/7269 [00:17<01:09, 84.63it/s]

Reports:  19%|█▉        | 1385/7269 [00:17<01:06, 88.85it/s]

Reports:  19%|█▉        | 1395/7269 [00:17<01:10, 83.74it/s]

Reports:  19%|█▉        | 1405/7269 [00:17<01:07, 87.04it/s]

Reports:  19%|█▉        | 1416/7269 [00:17<01:05, 89.85it/s]

Reports:  20%|█▉        | 1426/7269 [00:17<01:03, 91.53it/s]

Reports:  20%|█▉        | 1436/7269 [00:17<01:07, 86.83it/s]

Reports:  20%|█▉        | 1446/7269 [00:18<01:07, 86.60it/s]

Reports:  20%|██        | 1456/7269 [00:18<01:07, 86.32it/s]

Reports:  20%|██        | 1467/7269 [00:18<01:03, 91.11it/s]

Reports:  20%|██        | 1477/7269 [00:18<01:04, 89.67it/s]

Reports:  20%|██        | 1488/7269 [00:18<01:02, 91.98it/s]

Reports:  21%|██        | 1498/7269 [00:18<01:03, 90.72it/s]

Reports:  21%|██        | 1508/7269 [00:18<01:07, 85.13it/s]

Reports:  21%|██        | 1520/7269 [00:18<01:04, 89.57it/s]

Reports:  21%|██        | 1532/7269 [00:18<00:59, 95.89it/s]

Reports:  21%|██        | 1542/7269 [00:19<01:05, 88.03it/s]

Reports:  21%|██▏       | 1553/7269 [00:19<01:06, 86.42it/s]

Reports:  22%|██▏       | 1566/7269 [00:19<00:58, 96.73it/s]

Reports:  22%|██▏       | 1576/7269 [00:19<01:08, 83.24it/s]

Reports:  22%|██▏       | 1588/7269 [00:19<01:03, 89.68it/s]

Reports:  22%|██▏       | 1599/7269 [00:19<01:02, 90.73it/s]

Reports:  22%|██▏       | 1609/7269 [00:19<01:02, 91.27it/s]

Reports:  22%|██▏       | 1619/7269 [00:19<01:00, 93.46it/s]

Reports:  22%|██▏       | 1629/7269 [00:20<01:04, 86.97it/s]

Reports:  23%|██▎       | 1640/7269 [00:20<01:02, 89.61it/s]

Reports:  23%|██▎       | 1652/7269 [00:20<01:00, 92.69it/s]

Reports:  23%|██▎       | 1662/7269 [00:20<01:04, 87.57it/s]

Reports:  23%|██▎       | 1673/7269 [00:20<01:00, 92.10it/s]

Reports:  23%|██▎       | 1686/7269 [00:20<00:55, 100.52it/s]

Reports:  23%|██▎       | 1697/7269 [00:20<01:00, 92.21it/s]

Reports:  23%|██▎       | 1707/7269 [00:20<01:00, 91.64it/s]

Reports:  24%|██▎       | 1719/7269 [00:21<00:57, 96.30it/s]

Reports:  24%|██▍       | 1729/7269 [00:21<01:01, 90.71it/s]

Reports:  24%|██▍       | 1740/7269 [00:21<01:04, 86.15it/s]

Reports:  24%|██▍       | 1753/7269 [00:21<00:58, 94.05it/s]

Reports:  24%|██▍       | 1763/7269 [00:21<01:01, 89.96it/s]

Reports:  24%|██▍       | 1773/7269 [00:21<01:05, 83.32it/s]

Reports:  25%|██▍       | 1786/7269 [00:21<01:00, 90.34it/s]

Reports:  25%|██▍       | 1796/7269 [00:21<01:01, 88.90it/s]

Reports:  25%|██▍       | 1805/7269 [00:22<01:05, 83.38it/s]

Reports:  25%|██▌       | 1819/7269 [00:22<00:55, 97.61it/s]

Reports:  25%|██▌       | 1830/7269 [00:22<00:59, 92.09it/s]

Reports:  25%|██▌       | 1840/7269 [00:22<01:01, 88.04it/s]

Reports:  25%|██▌       | 1853/7269 [00:22<01:03, 85.89it/s]

Reports:  26%|██▌       | 1863/7269 [00:22<01:02, 86.98it/s]

Reports:  26%|██▌       | 1875/7269 [00:22<00:58, 92.89it/s]

Reports:  26%|██▌       | 1885/7269 [00:22<00:58, 92.23it/s]

Reports:  26%|██▌       | 1895/7269 [00:23<00:58, 91.69it/s]

Reports:  26%|██▌       | 1905/7269 [00:23<00:58, 91.18it/s]

Reports:  26%|██▋       | 1917/7269 [00:23<00:55, 96.07it/s]

Reports:  27%|██▋       | 1927/7269 [00:23<01:01, 86.87it/s]

Reports:  27%|██▋       | 1936/7269 [00:23<01:05, 82.03it/s]

Reports:  27%|██▋       | 1945/7269 [00:23<01:05, 81.76it/s]

Reports:  27%|██▋       | 1955/7269 [00:23<01:05, 80.88it/s]

Reports:  27%|██▋       | 1966/7269 [00:23<01:01, 86.13it/s]

Reports:  27%|██▋       | 1976/7269 [00:23<01:03, 83.79it/s]

Reports:  27%|██▋       | 1985/7269 [00:24<01:08, 76.88it/s]

Reports:  27%|██▋       | 1998/7269 [00:24<01:04, 81.31it/s]

Reports:  28%|██▊       | 2008/7269 [00:24<01:02, 83.54it/s]

Reports:  28%|██▊       | 2017/7269 [00:24<01:15, 69.24it/s]

Reports:  28%|██▊       | 2032/7269 [00:24<01:07, 77.40it/s]

Reports:  28%|██▊       | 2048/7269 [00:24<01:03, 82.19it/s]

Reports:  28%|██▊       | 2063/7269 [00:25<00:55, 94.59it/s]

Reports:  29%|██▊       | 2073/7269 [00:25<00:57, 90.26it/s]

Reports:  29%|██▊       | 2083/7269 [00:25<01:14, 69.67it/s]

Reports:  29%|██▉       | 2094/7269 [00:25<01:08, 76.04it/s]

Reports:  29%|██▉       | 2103/7269 [00:25<01:18, 66.04it/s]

Reports:  29%|██▉       | 2112/7269 [00:25<01:19, 65.26it/s]

Reports:  29%|██▉       | 2120/7269 [00:25<01:22, 62.68it/s]

Reports:  29%|██▉       | 2129/7269 [00:26<01:21, 62.83it/s]

Reports:  29%|██▉       | 2136/7269 [00:26<01:27, 58.72it/s]

Reports:  29%|██▉       | 2144/7269 [00:26<01:22, 61.98it/s]

Reports:  30%|██▉       | 2152/7269 [00:26<01:21, 62.42it/s]

Reports:  30%|██▉       | 2160/7269 [00:26<01:27, 58.42it/s]

Reports:  30%|██▉       | 2166/7269 [00:26<01:38, 51.65it/s]

Reports:  30%|██▉       | 2174/7269 [00:26<01:33, 54.76it/s]

Reports:  30%|██▉       | 2180/7269 [00:27<02:13, 38.09it/s]

Reports:  30%|███       | 2192/7269 [00:27<01:45, 48.01it/s]

Reports:  30%|███       | 2198/7269 [00:27<01:46, 47.76it/s]

Reports:  30%|███       | 2207/7269 [00:27<01:31, 55.20it/s]

Reports:  30%|███       | 2214/7269 [00:27<01:46, 47.26it/s]

Reports:  31%|███       | 2222/7269 [00:27<01:35, 52.81it/s]

Reports:  31%|███       | 2228/7269 [00:28<01:44, 48.03it/s]

Reports:  31%|███       | 2239/7269 [00:28<01:35, 52.93it/s]

Reports:  31%|███       | 2245/7269 [00:28<01:37, 51.39it/s]

Reports:  31%|███       | 2255/7269 [00:28<01:28, 56.77it/s]

Reports:  31%|███       | 2261/7269 [00:28<01:35, 52.44it/s]

Reports:  31%|███       | 2271/7269 [00:28<01:23, 59.59it/s]

Reports:  31%|███▏      | 2278/7269 [00:28<01:31, 54.56it/s]

Reports:  31%|███▏      | 2287/7269 [00:29<01:21, 60.99it/s]

Reports:  32%|███▏      | 2294/7269 [00:29<01:27, 57.18it/s]

Reports:  32%|███▏      | 2301/7269 [00:29<01:30, 54.65it/s]

Reports:  32%|███▏      | 2308/7269 [00:29<01:27, 56.71it/s]

Reports:  32%|███▏      | 2318/7269 [00:29<01:15, 65.48it/s]

Reports:  32%|███▏      | 2329/7269 [00:29<01:08, 71.78it/s]

Reports:  32%|███▏      | 2337/7269 [00:29<01:24, 58.06it/s]

Reports:  32%|███▏      | 2349/7269 [00:30<01:12, 67.68it/s]

Reports:  32%|███▏      | 2357/7269 [00:30<01:11, 68.78it/s]

Reports:  33%|███▎      | 2366/7269 [00:30<01:13, 67.06it/s]

Reports:  33%|███▎      | 2376/7269 [00:30<01:06, 73.07it/s]

Reports:  33%|███▎      | 2386/7269 [00:30<01:07, 72.08it/s]

Reports:  33%|███▎      | 2398/7269 [00:30<00:59, 81.67it/s]

Reports:  33%|███▎      | 2410/7269 [00:30<00:54, 88.92it/s]

Reports:  33%|███▎      | 2420/7269 [00:30<00:58, 82.56it/s]

Reports:  33%|███▎      | 2431/7269 [00:31<00:55, 86.85it/s]

Reports:  34%|███▎      | 2440/7269 [00:31<01:01, 78.95it/s]

Reports:  34%|███▎      | 2450/7269 [00:31<00:57, 83.92it/s]

Reports:  34%|███▍      | 2459/7269 [00:31<01:06, 72.21it/s]

Reports:  34%|███▍      | 2467/7269 [00:31<01:07, 71.13it/s]

Reports:  34%|███▍      | 2476/7269 [00:31<01:06, 72.06it/s]

Reports:  34%|███▍      | 2486/7269 [00:31<01:02, 76.67it/s]

Reports:  34%|███▍      | 2497/7269 [00:31<00:57, 83.26it/s]

Reports:  34%|███▍      | 2506/7269 [00:32<00:57, 82.42it/s]

Reports:  35%|███▍      | 2515/7269 [00:32<00:58, 81.79it/s]

Reports:  35%|███▍      | 2524/7269 [00:32<00:58, 81.61it/s]

Reports:  35%|███▍      | 2533/7269 [00:32<00:58, 81.37it/s]

Reports:  35%|███▍      | 2543/7269 [00:32<00:56, 83.87it/s]

Reports:  35%|███▌      | 2552/7269 [00:32<00:56, 83.16it/s]

Reports:  35%|███▌      | 2561/7269 [00:32<00:59, 79.33it/s]

Reports:  35%|███▌      | 2571/7269 [00:32<01:03, 73.42it/s]

Reports:  36%|███▌      | 2582/7269 [00:33<01:04, 72.33it/s]

Reports:  36%|███▌      | 2598/7269 [00:33<01:02, 74.98it/s]

Reports:  36%|███▌      | 2607/7269 [00:33<01:02, 75.17it/s]

Reports:  36%|███▌      | 2617/7269 [00:33<01:01, 76.17it/s]

Reports:  36%|███▌      | 2630/7269 [00:33<01:05, 70.99it/s]

Reports:  36%|███▋      | 2646/7269 [00:33<00:58, 79.68it/s]

Reports:  37%|███▋      | 2660/7269 [00:33<00:51, 90.33it/s]

Reports:  37%|███▋      | 2670/7269 [00:34<00:58, 79.09it/s]

Reports:  37%|███▋      | 2680/7269 [00:34<00:59, 76.52it/s]

Reports:  37%|███▋      | 2688/7269 [00:34<01:00, 75.45it/s]

Reports:  37%|███▋      | 2697/7269 [00:34<01:01, 74.15it/s]

Reports:  37%|███▋      | 2712/7269 [00:34<00:50, 90.16it/s]

Reports:  37%|███▋      | 2722/7269 [00:34<01:02, 73.09it/s]

Reports:  38%|███▊      | 2733/7269 [00:34<00:56, 80.62it/s]

Reports:  38%|███▊      | 2746/7269 [00:35<00:49, 91.81it/s]

Reports:  38%|███▊      | 2756/7269 [00:35<00:55, 81.85it/s]

Reports:  38%|███▊      | 2765/7269 [00:35<00:56, 80.16it/s]

Reports:  38%|███▊      | 2774/7269 [00:35<00:54, 82.09it/s]

Reports:  38%|███▊      | 2785/7269 [00:35<00:51, 86.80it/s]

Reports:  38%|███▊      | 2797/7269 [00:35<00:50, 89.37it/s]

Reports:  39%|███▊      | 2807/7269 [00:35<00:49, 89.60it/s]

Reports:  39%|███▉      | 2817/7269 [00:35<00:48, 92.06it/s]

Reports:  39%|███▉      | 2827/7269 [00:35<00:52, 84.40it/s]

Reports:  39%|███▉      | 2836/7269 [00:36<00:53, 83.50it/s]

Reports:  39%|███▉      | 2847/7269 [00:36<00:50, 88.05it/s]

Reports:  39%|███▉      | 2856/7269 [00:36<01:10, 62.72it/s]

Reports:  39%|███▉      | 2864/7269 [00:36<01:07, 64.84it/s]

Reports:  40%|███▉      | 2872/7269 [00:36<01:05, 66.77it/s]

Reports:  40%|███▉      | 2883/7269 [00:36<01:00, 72.50it/s]

Reports:  40%|███▉      | 2895/7269 [00:36<00:55, 78.75it/s]

Reports:  40%|███▉      | 2904/7269 [00:37<00:54, 79.70it/s]

Reports:  40%|████      | 2914/7269 [00:37<00:54, 79.59it/s]

Reports:  40%|████      | 2926/7269 [00:37<00:49, 87.32it/s]

Reports:  40%|████      | 2936/7269 [00:37<00:51, 84.64it/s]

Reports:  41%|████      | 2947/7269 [00:37<00:48, 88.65it/s]

Reports:  41%|████      | 2957/7269 [00:37<00:47, 89.87it/s]

Reports:  41%|████      | 2968/7269 [00:37<00:48, 88.25it/s]

Reports:  41%|████      | 2978/7269 [00:37<00:50, 85.31it/s]

Reports:  41%|████      | 2992/7269 [00:38<00:44, 97.04it/s]

Reports:  41%|████▏     | 3002/7269 [00:38<00:46, 91.45it/s]

Reports:  41%|████▏     | 3012/7269 [00:38<00:48, 87.68it/s]

Reports:  42%|████▏     | 3025/7269 [00:38<00:44, 95.88it/s]

Reports:  42%|████▏     | 3035/7269 [00:38<00:48, 86.59it/s]

Reports:  42%|████▏     | 3044/7269 [00:38<00:49, 84.96it/s]

Reports:  42%|████▏     | 3053/7269 [00:38<00:49, 84.76it/s]

Reports:  42%|████▏     | 3064/7269 [00:38<00:47, 87.61it/s]

Reports:  42%|████▏     | 3075/7269 [00:38<00:47, 88.37it/s]

Reports:  42%|████▏     | 3084/7269 [00:39<00:51, 80.80it/s]

Reports:  43%|████▎     | 3096/7269 [00:39<00:47, 87.80it/s]

Reports:  43%|████▎     | 3106/7269 [00:39<00:47, 88.49it/s]

Reports:  43%|████▎     | 3116/7269 [00:39<00:46, 88.83it/s]

Reports:  43%|████▎     | 3127/7269 [00:39<00:46, 88.19it/s]

Reports:  43%|████▎     | 3136/7269 [00:39<00:47, 86.15it/s]

Reports:  43%|████▎     | 3147/7269 [00:39<00:45, 89.79it/s]

Reports:  43%|████▎     | 3157/7269 [00:39<00:47, 86.24it/s]

Reports:  44%|████▎     | 3166/7269 [00:40<00:49, 82.48it/s]

Reports:  44%|████▎     | 3177/7269 [00:40<00:45, 89.74it/s]

Reports:  44%|████▍     | 3187/7269 [00:40<00:47, 85.68it/s]

Reports:  44%|████▍     | 3200/7269 [00:40<00:46, 88.34it/s]

Reports:  44%|████▍     | 3209/7269 [00:40<00:45, 88.48it/s]

Reports:  44%|████▍     | 3219/7269 [00:40<00:46, 87.03it/s]

Reports:  44%|████▍     | 3232/7269 [00:40<00:45, 88.53it/s]

Reports:  45%|████▍     | 3241/7269 [00:40<00:48, 83.10it/s]

Reports:  45%|████▍     | 3251/7269 [00:41<00:47, 85.20it/s]

Reports:  45%|████▍     | 3262/7269 [00:41<00:44, 89.15it/s]

Reports:  45%|████▌     | 3272/7269 [00:41<00:45, 87.83it/s]

Reports:  45%|████▌     | 3284/7269 [00:41<00:42, 94.30it/s]

Reports:  45%|████▌     | 3294/7269 [00:41<00:44, 88.67it/s]

Reports:  45%|████▌     | 3304/7269 [00:41<00:45, 87.87it/s]

Reports:  46%|████▌     | 3318/7269 [00:41<00:40, 97.04it/s]

Reports:  46%|████▌     | 3328/7269 [00:41<00:42, 92.42it/s]

Reports:  46%|████▌     | 3338/7269 [00:41<00:44, 88.19it/s]

Reports:  46%|████▌     | 3351/7269 [00:42<00:41, 95.26it/s]

Reports:  46%|████▌     | 3361/7269 [00:42<00:48, 80.77it/s]

Reports:  46%|████▋     | 3370/7269 [00:42<00:48, 80.87it/s]

Reports:  47%|████▋     | 3384/7269 [00:42<00:41, 93.07it/s]

Reports:  47%|████▋     | 3394/7269 [00:42<00:45, 85.33it/s]

Reports:  47%|████▋     | 3403/7269 [00:42<00:49, 77.81it/s]

Reports:  47%|████▋     | 3417/7269 [00:42<00:45, 84.50it/s]

Reports:  47%|████▋     | 3426/7269 [00:43<00:45, 83.58it/s]

Reports:  47%|████▋     | 3435/7269 [00:43<00:51, 74.18it/s]

Reports:  47%|████▋     | 3449/7269 [00:43<00:50, 76.17it/s]

Reports:  48%|████▊     | 3463/7269 [00:43<00:43, 88.21it/s]

Reports:  48%|████▊     | 3473/7269 [00:43<00:50, 74.87it/s]

Reports:  48%|████▊     | 3484/7269 [00:43<00:48, 77.87it/s]

Reports:  48%|████▊     | 3497/7269 [00:43<00:46, 81.77it/s]

Reports:  48%|████▊     | 3506/7269 [00:44<00:52, 71.50it/s]

Reports:  48%|████▊     | 3516/7269 [00:44<00:49, 75.82it/s]

Reports:  48%|████▊     | 3524/7269 [00:44<00:51, 72.25it/s]

Reports:  49%|████▊     | 3534/7269 [00:44<00:48, 76.91it/s]

Reports:  49%|████▉     | 3544/7269 [00:44<00:46, 80.63it/s]

Reports:  49%|████▉     | 3553/7269 [00:44<00:47, 77.55it/s]

Reports:  49%|████▉     | 3563/7269 [00:44<00:45, 80.80it/s]

Reports:  49%|████▉     | 3572/7269 [00:44<00:49, 74.79it/s]

Reports:  49%|████▉     | 3581/7269 [00:45<00:48, 76.49it/s]

Reports:  49%|████▉     | 3589/7269 [00:45<00:48, 75.19it/s]

Reports:  50%|████▉     | 3599/7269 [00:45<00:46, 79.49it/s]

Reports:  50%|████▉     | 3608/7269 [00:45<00:47, 76.92it/s]

Reports:  50%|████▉     | 3620/7269 [00:45<00:48, 74.90it/s]

Reports:  50%|████▉     | 3628/7269 [00:45<00:49, 74.19it/s]

Reports:  50%|█████     | 3638/7269 [00:45<00:46, 78.67it/s]

Reports:  50%|█████     | 3648/7269 [00:45<00:44, 81.97it/s]

Reports:  50%|█████     | 3657/7269 [00:46<00:45, 78.64it/s]

Reports:  50%|█████     | 3669/7269 [00:46<00:46, 77.70it/s]

Reports:  51%|█████     | 3680/7269 [00:46<00:44, 80.32it/s]

Reports:  51%|█████     | 3692/7269 [00:46<00:43, 81.66it/s]

Reports:  51%|█████     | 3705/7269 [00:46<00:39, 91.11it/s]

Reports:  51%|█████     | 3715/7269 [00:46<00:43, 81.44it/s]

Reports:  51%|█████     | 3724/7269 [00:46<00:48, 73.29it/s]

Reports:  51%|█████▏    | 3735/7269 [00:46<00:44, 79.72it/s]

Reports:  52%|█████▏    | 3744/7269 [00:47<00:50, 69.89it/s]

Reports:  52%|█████▏    | 3756/7269 [00:47<00:44, 79.36it/s]

Reports:  52%|█████▏    | 3765/7269 [00:47<00:43, 79.72it/s]

Reports:  52%|█████▏    | 3776/7269 [00:47<00:44, 78.72it/s]

Reports:  52%|█████▏    | 3785/7269 [00:47<00:43, 79.29it/s]

Reports:  52%|█████▏    | 3794/7269 [00:47<00:43, 79.63it/s]

Reports:  52%|█████▏    | 3808/7269 [00:47<00:40, 85.86it/s]

Reports:  53%|█████▎    | 3817/7269 [00:48<00:43, 78.68it/s]

Reports:  53%|█████▎    | 3828/7269 [00:48<00:42, 81.11it/s]

Reports:  53%|█████▎    | 3837/7269 [00:48<00:43, 78.20it/s]

Reports:  53%|█████▎    | 3845/7269 [00:48<00:48, 71.22it/s]

Reports:  53%|█████▎    | 3855/7269 [00:48<00:48, 70.93it/s]

Reports:  53%|█████▎    | 3863/7269 [00:48<00:49, 68.76it/s]

Reports:  53%|█████▎    | 3877/7269 [00:48<00:43, 78.04it/s]

Reports:  53%|█████▎    | 3887/7269 [00:48<00:43, 78.26it/s]

Reports:  54%|█████▎    | 3895/7269 [00:49<00:45, 73.86it/s]

Reports:  54%|█████▍    | 3909/7269 [00:49<00:39, 84.62it/s]

Reports:  54%|█████▍    | 3919/7269 [00:49<00:40, 82.94it/s]

Reports:  54%|█████▍    | 3929/7269 [00:49<00:40, 81.69it/s]

Reports:  54%|█████▍    | 3941/7269 [00:49<00:37, 88.90it/s]

Reports:  54%|█████▍    | 3950/7269 [00:49<00:38, 86.74it/s]

Reports:  54%|█████▍    | 3960/7269 [00:49<00:37, 87.81it/s]

Reports:  55%|█████▍    | 3969/7269 [00:49<00:38, 85.81it/s]

Reports:  55%|█████▍    | 3978/7269 [00:50<00:40, 80.85it/s]

Reports:  55%|█████▍    | 3992/7269 [00:50<00:36, 90.05it/s]

Reports:  55%|█████▌    | 4001/7269 [00:50<00:41, 78.16it/s]

Reports:  55%|█████▌    | 4012/7269 [00:50<00:40, 80.60it/s]

Reports:  55%|█████▌    | 4026/7269 [00:50<00:34, 92.75it/s]

Reports:  56%|█████▌    | 4036/7269 [00:50<00:42, 76.85it/s]

Reports:  56%|█████▌    | 4045/7269 [00:50<00:45, 70.44it/s]

Reports:  56%|█████▌    | 4053/7269 [00:51<00:47, 68.38it/s]

Reports:  56%|█████▌    | 4064/7269 [00:51<00:43, 73.40it/s]

Reports:  56%|█████▌    | 4078/7269 [00:51<00:39, 80.91it/s]

Reports:  56%|█████▌    | 4087/7269 [00:51<00:44, 70.81it/s]

Reports:  56%|█████▋    | 4098/7269 [00:51<00:42, 74.57it/s]

Reports:  57%|█████▋    | 4113/7269 [00:51<00:37, 83.62it/s]

Reports:  57%|█████▋    | 4122/7269 [00:51<00:37, 83.03it/s]

Reports:  57%|█████▋    | 4132/7269 [00:51<00:38, 81.88it/s]

Reports:  57%|█████▋    | 4146/7269 [00:52<00:35, 87.06it/s]

Reports:  57%|█████▋    | 4157/7269 [00:52<00:34, 90.19it/s]

Reports:  57%|█████▋    | 4167/7269 [00:52<00:35, 86.72it/s]

Reports:  57%|█████▋    | 4178/7269 [00:52<00:34, 90.03it/s]

Reports:  58%|█████▊    | 4188/7269 [00:52<00:34, 90.12it/s]

Reports:  58%|█████▊    | 4198/7269 [00:52<00:35, 86.56it/s]

Reports:  58%|█████▊    | 4212/7269 [00:52<00:32, 94.00it/s]

Reports:  58%|█████▊    | 4222/7269 [00:52<00:32, 92.92it/s]

Reports:  58%|█████▊    | 4232/7269 [00:53<00:35, 85.23it/s]

Reports:  58%|█████▊    | 4246/7269 [00:53<00:33, 89.39it/s]

Reports:  59%|█████▊    | 4260/7269 [00:53<00:30, 99.22it/s]

Reports:  59%|█████▉    | 4271/7269 [00:53<00:31, 95.43it/s]

Reports:  59%|█████▉    | 4281/7269 [00:53<00:33, 90.25it/s]

Reports:  59%|█████▉    | 4294/7269 [00:53<00:30, 97.70it/s]

Reports:  59%|█████▉    | 4304/7269 [00:53<00:33, 88.44it/s]

Reports:  59%|█████▉    | 4315/7269 [00:53<00:32, 91.38it/s]

Reports:  60%|█████▉    | 4326/7269 [00:54<00:31, 93.73it/s]

Reports:  60%|█████▉    | 4336/7269 [00:54<00:32, 89.17it/s]

Reports:  60%|█████▉    | 4346/7269 [00:54<00:32, 89.49it/s]

Reports:  60%|█████▉    | 4356/7269 [00:54<00:36, 80.02it/s]

Reports:  60%|██████    | 4368/7269 [00:54<00:33, 87.64it/s]

Reports:  60%|██████    | 4380/7269 [00:54<00:32, 89.76it/s]

Reports:  60%|██████    | 4390/7269 [00:54<00:38, 75.01it/s]

Reports:  61%|██████    | 4402/7269 [00:55<00:34, 83.28it/s]

Reports:  61%|██████    | 4411/7269 [00:55<00:35, 79.57it/s]

Reports:  61%|██████    | 4420/7269 [00:55<00:35, 79.98it/s]

Reports:  61%|██████    | 4433/7269 [00:55<00:31, 90.19it/s]

Reports:  61%|██████    | 4443/7269 [00:55<00:33, 83.56it/s]

Reports:  61%|██████▏   | 4453/7269 [00:55<00:34, 82.14it/s]

Reports:  61%|██████▏   | 4467/7269 [00:55<00:30, 90.76it/s]

Reports:  62%|██████▏   | 4477/7269 [00:55<00:31, 87.25it/s]

Reports:  62%|██████▏   | 4486/7269 [00:56<00:36, 76.60it/s]

Reports:  62%|██████▏   | 4502/7269 [00:56<00:33, 81.99it/s]

Reports:  62%|██████▏   | 4518/7269 [00:56<00:31, 87.83it/s]

Reports:  62%|██████▏   | 4534/7269 [00:56<00:30, 89.10it/s]

Reports:  62%|██████▏   | 4543/7269 [00:56<00:32, 84.57it/s]

Reports:  63%|██████▎   | 4553/7269 [00:56<00:31, 85.96it/s]

Reports:  63%|██████▎   | 4564/7269 [00:56<00:30, 89.36it/s]

Reports:  63%|██████▎   | 4573/7269 [00:57<00:32, 83.93it/s]

Reports:  63%|██████▎   | 4585/7269 [00:57<00:30, 87.09it/s]

Reports:  63%|██████▎   | 4594/7269 [00:57<00:33, 79.31it/s]

Reports:  63%|██████▎   | 4602/7269 [00:57<00:34, 77.35it/s]

Reports:  63%|██████▎   | 4610/7269 [00:57<00:35, 75.83it/s]

Reports:  64%|██████▎   | 4619/7269 [00:57<00:35, 74.34it/s]

Reports:  64%|██████▎   | 4630/7269 [00:57<00:32, 81.12it/s]

Reports:  64%|██████▍   | 4639/7269 [00:57<00:33, 77.92it/s]

Reports:  64%|██████▍   | 4647/7269 [00:58<00:37, 70.56it/s]

Reports:  64%|██████▍   | 4656/7269 [00:58<00:35, 73.37it/s]

Reports:  64%|██████▍   | 4664/7269 [00:58<00:35, 73.04it/s]

Reports:  64%|██████▍   | 4674/7269 [00:58<00:34, 74.93it/s]

Reports:  64%|██████▍   | 4685/7269 [00:58<00:31, 81.79it/s]

Reports:  65%|██████▍   | 4694/7269 [00:58<00:32, 78.49it/s]

Reports:  65%|██████▍   | 4707/7269 [00:58<00:34, 74.49it/s]

Reports:  65%|██████▍   | 4715/7269 [00:58<00:35, 71.27it/s]

Reports:  65%|██████▍   | 4723/7269 [00:59<00:36, 68.90it/s]

Reports:  65%|██████▌   | 4730/7269 [00:59<00:40, 62.66it/s]

Reports:  65%|██████▌   | 4740/7269 [00:59<00:36, 69.68it/s]

Reports:  65%|██████▌   | 4750/7269 [00:59<00:33, 75.22it/s]

Reports:  65%|██████▌   | 4758/7269 [00:59<00:33, 74.42it/s]

Reports:  66%|██████▌   | 4766/7269 [00:59<00:35, 70.97it/s]

Reports:  66%|██████▌   | 4776/7269 [00:59<00:32, 76.27it/s]

Reports:  66%|██████▌   | 4784/7269 [00:59<00:33, 75.09it/s]

Reports:  66%|██████▌   | 4794/7269 [01:00<00:31, 79.39it/s]

Reports:  66%|██████▌   | 4802/7269 [01:00<00:31, 77.23it/s]

Reports:  66%|██████▌   | 4812/7269 [01:00<00:32, 74.77it/s]

Reports:  66%|██████▋   | 4820/7269 [01:00<00:33, 74.06it/s]

Reports:  66%|██████▋   | 4828/7269 [01:00<00:33, 73.44it/s]

Reports:  67%|██████▋   | 4838/7269 [01:00<00:32, 75.04it/s]

Reports:  67%|██████▋   | 4846/7269 [01:00<00:32, 74.09it/s]

Reports:  67%|██████▋   | 4854/7269 [01:00<00:35, 67.97it/s]

Reports:  67%|██████▋   | 4866/7269 [01:00<00:31, 77.47it/s]

Reports:  67%|██████▋   | 4878/7269 [01:01<00:27, 85.97it/s]

Reports:  67%|██████▋   | 4887/7269 [01:01<00:29, 81.29it/s]

Reports:  67%|██████▋   | 4897/7269 [01:01<00:28, 83.62it/s]

Reports:  68%|██████▊   | 4908/7269 [01:01<00:26, 87.94it/s]

Reports:  68%|██████▊   | 4917/7269 [01:01<00:28, 82.55it/s]

Reports:  68%|██████▊   | 4929/7269 [01:01<00:26, 89.67it/s]

Reports:  68%|██████▊   | 4939/7269 [01:01<00:26, 86.48it/s]

Reports:  68%|██████▊   | 4949/7269 [01:01<00:26, 87.73it/s]

Reports:  68%|██████▊   | 4958/7269 [01:02<00:27, 82.65it/s]

Reports:  68%|██████▊   | 4967/7269 [01:02<00:27, 82.30it/s]

Reports:  68%|██████▊   | 4979/7269 [01:02<00:25, 89.74it/s]

Reports:  69%|██████▊   | 4989/7269 [01:02<00:27, 82.93it/s]

Reports:  69%|██████▉   | 4999/7269 [01:02<00:27, 81.82it/s]

Reports:  69%|██████▉   | 5013/7269 [01:02<00:23, 94.21it/s]

Reports:  69%|██████▉   | 5023/7269 [01:02<00:24, 93.08it/s]

Reports:  69%|██████▉   | 5033/7269 [01:02<00:25, 88.67it/s]

Reports:  69%|██████▉   | 5045/7269 [01:02<00:23, 94.43it/s]

Reports:  70%|██████▉   | 5055/7269 [01:03<00:23, 93.19it/s]

Reports:  70%|██████▉   | 5065/7269 [01:03<00:24, 88.74it/s]

Reports:  70%|██████▉   | 5078/7269 [01:03<00:25, 85.36it/s]

Reports:  70%|███████   | 5090/7269 [01:03<00:24, 88.63it/s]

Reports:  70%|███████   | 5100/7269 [01:03<00:24, 89.22it/s]

Reports:  70%|███████   | 5111/7269 [01:03<00:23, 92.04it/s]

Reports:  70%|███████   | 5121/7269 [01:03<00:23, 91.47it/s]

Reports:  71%|███████   | 5133/7269 [01:03<00:22, 96.28it/s]

Reports:  71%|███████   | 5144/7269 [01:04<00:21, 97.21it/s]

Reports:  71%|███████   | 5154/7269 [01:04<00:24, 87.77it/s]

Reports:  71%|███████   | 5166/7269 [01:04<00:22, 95.05it/s]

Reports:  71%|███████   | 5176/7269 [01:04<00:24, 84.86it/s]

Reports:  71%|███████▏  | 5185/7269 [01:04<00:24, 83.88it/s]

Reports:  72%|███████▏  | 5199/7269 [01:04<00:23, 88.37it/s]

Reports:  72%|███████▏  | 5211/7269 [01:04<00:22, 93.37it/s]

Reports:  72%|███████▏  | 5221/7269 [01:04<00:23, 85.81it/s]

Reports:  72%|███████▏  | 5233/7269 [01:05<00:23, 88.41it/s]

Reports:  72%|███████▏  | 5243/7269 [01:05<00:22, 88.88it/s]

Reports:  72%|███████▏  | 5253/7269 [01:05<00:22, 89.88it/s]

Reports:  72%|███████▏  | 5265/7269 [01:05<00:22, 90.68it/s]

Reports:  73%|███████▎  | 5275/7269 [01:05<00:22, 87.07it/s]

Reports:  73%|███████▎  | 5287/7269 [01:05<00:22, 89.39it/s]

Reports:  73%|███████▎  | 5299/7269 [01:05<00:20, 94.53it/s]

Reports:  73%|███████▎  | 5309/7269 [01:05<00:22, 86.24it/s]

Reports:  73%|███████▎  | 5320/7269 [01:06<00:22, 86.43it/s]

Reports:  73%|███████▎  | 5332/7269 [01:06<00:21, 88.80it/s]

Reports:  73%|███████▎  | 5341/7269 [01:06<00:24, 77.60it/s]

Reports:  74%|███████▎  | 5355/7269 [01:06<00:22, 83.96it/s]

Reports:  74%|███████▍  | 5364/7269 [01:06<00:23, 80.32it/s]

Reports:  74%|███████▍  | 5374/7269 [01:06<00:22, 82.99it/s]

Reports:  74%|███████▍  | 5383/7269 [01:06<00:22, 82.48it/s]

Reports:  74%|███████▍  | 5392/7269 [01:06<00:23, 81.48it/s]

Reports:  74%|███████▍  | 5404/7269 [01:07<00:20, 89.84it/s]

Reports:  74%|███████▍  | 5414/7269 [01:07<00:22, 83.03it/s]

Reports:  75%|███████▍  | 5425/7269 [01:07<00:21, 87.58it/s]

Reports:  75%|███████▍  | 5434/7269 [01:07<00:21, 85.72it/s]

Reports:  75%|███████▍  | 5443/7269 [01:07<00:21, 84.44it/s]

Reports:  75%|███████▌  | 5455/7269 [01:07<00:20, 90.48it/s]

Reports:  75%|███████▌  | 5466/7269 [01:07<00:19, 93.99it/s]

Reports:  75%|███████▌  | 5476/7269 [01:07<00:20, 85.62it/s]

Reports:  76%|███████▌  | 5490/7269 [01:08<00:19, 93.24it/s]

Reports:  76%|███████▌  | 5500/7269 [01:08<00:19, 92.48it/s]

Reports:  76%|███████▌  | 5511/7269 [01:08<00:18, 94.38it/s]

Reports:  76%|███████▌  | 5522/7269 [01:08<00:18, 96.87it/s]

Reports:  76%|███████▌  | 5532/7269 [01:08<00:19, 90.30it/s]

Reports:  76%|███████▌  | 5542/7269 [01:08<00:19, 86.77it/s]

Reports:  76%|███████▋  | 5554/7269 [01:08<00:18, 92.75it/s]

Reports:  77%|███████▋  | 5564/7269 [01:08<00:18, 92.06it/s]

Reports:  77%|███████▋  | 5574/7269 [01:08<00:19, 88.01it/s]

Reports:  77%|███████▋  | 5587/7269 [01:09<00:17, 96.46it/s]

Reports:  77%|███████▋  | 5597/7269 [01:09<00:18, 90.89it/s]

Reports:  77%|███████▋  | 5607/7269 [01:09<00:19, 87.15it/s]

Reports:  77%|███████▋  | 5620/7269 [01:09<00:17, 92.01it/s]

Reports:  77%|███████▋  | 5630/7269 [01:09<00:17, 91.50it/s]

Reports:  78%|███████▊  | 5640/7269 [01:09<00:20, 81.29it/s]

Reports:  78%|███████▊  | 5652/7269 [01:09<00:19, 82.26it/s]

Reports:  78%|███████▊  | 5666/7269 [01:10<00:17, 90.53it/s]

Reports:  78%|███████▊  | 5676/7269 [01:10<00:20, 78.51it/s]

Reports:  78%|███████▊  | 5689/7269 [01:10<00:19, 82.25it/s]

Reports:  78%|███████▊  | 5702/7269 [01:10<00:17, 90.87it/s]

Reports:  79%|███████▊  | 5712/7269 [01:10<00:17, 87.38it/s]

Reports:  79%|███████▊  | 5721/7269 [01:10<00:18, 85.78it/s]

Reports:  79%|███████▉  | 5736/7269 [01:10<00:15, 99.29it/s]

Reports:  79%|███████▉  | 5747/7269 [01:10<00:16, 91.93it/s]

Reports:  79%|███████▉  | 5757/7269 [01:11<00:17, 84.78it/s]

Reports:  79%|███████▉  | 5769/7269 [01:11<00:19, 78.50it/s]

Reports:  80%|███████▉  | 5784/7269 [01:11<00:15, 92.99it/s]

Reports:  80%|███████▉  | 5794/7269 [01:11<00:17, 85.91it/s]

Reports:  80%|███████▉  | 5803/7269 [01:11<00:17, 81.65it/s]

Reports:  80%|████████  | 5816/7269 [01:11<00:17, 84.51it/s]

Reports:  80%|████████  | 5826/7269 [01:11<00:16, 85.91it/s]

Reports:  80%|████████  | 5835/7269 [01:11<00:16, 84.66it/s]

Reports:  80%|████████  | 5844/7269 [01:12<00:18, 77.41it/s]

Reports:  81%|████████  | 5857/7269 [01:12<00:16, 88.01it/s]

Reports:  81%|████████  | 5867/7269 [01:12<00:15, 88.67it/s]

Reports:  81%|████████  | 5877/7269 [01:12<00:16, 82.47it/s]

Reports:  81%|████████  | 5890/7269 [01:12<00:15, 88.58it/s]

Reports:  81%|████████  | 5899/7269 [01:12<00:15, 86.56it/s]

Reports:  81%|████████▏ | 5908/7269 [01:12<00:16, 84.93it/s]

Reports:  81%|████████▏ | 5917/7269 [01:12<00:16, 83.78it/s]

Reports:  82%|████████▏ | 5929/7269 [01:13<00:14, 89.68it/s]

Reports:  82%|████████▏ | 5940/7269 [01:13<00:14, 93.88it/s]

Reports:  82%|████████▏ | 5950/7269 [01:13<00:15, 85.61it/s]

Reports:  82%|████████▏ | 5961/7269 [01:13<00:14, 90.14it/s]

Reports:  82%|████████▏ | 5971/7269 [01:13<00:14, 89.41it/s]

Reports:  82%|████████▏ | 5981/7269 [01:13<00:15, 82.87it/s]

Reports:  82%|████████▏ | 5993/7269 [01:13<00:14, 89.93it/s]

Reports:  83%|████████▎ | 6003/7269 [01:13<00:16, 77.60it/s]

Reports:  83%|████████▎ | 6015/7269 [01:14<00:15, 79.77it/s]

Reports:  83%|████████▎ | 6027/7269 [01:14<00:15, 81.04it/s]

Reports:  83%|████████▎ | 6036/7269 [01:14<00:16, 75.52it/s]

Reports:  83%|████████▎ | 6048/7269 [01:14<00:14, 83.80it/s]

Reports:  83%|████████▎ | 6057/7269 [01:14<00:15, 80.07it/s]

Reports:  83%|████████▎ | 6066/7269 [01:14<00:16, 72.09it/s]

Reports:  84%|████████▎ | 6080/7269 [01:15<00:19, 61.44it/s]

Reports:  84%|████████▍ | 6096/7269 [01:15<00:17, 68.66it/s]

Reports:  84%|████████▍ | 6107/7269 [01:15<00:15, 72.70it/s]

Reports:  84%|████████▍ | 6115/7269 [01:15<00:20, 56.54it/s]

Reports:  84%|████████▍ | 6128/7269 [01:15<00:16, 68.41it/s]

Reports:  84%|████████▍ | 6137/7269 [01:15<00:15, 71.13it/s]

Reports:  85%|████████▍ | 6145/7269 [01:15<00:15, 71.33it/s]

Reports:  85%|████████▍ | 6158/7269 [01:16<00:13, 83.00it/s]

Reports:  85%|████████▍ | 6167/7269 [01:16<00:13, 78.85it/s]

Reports:  85%|████████▍ | 6178/7269 [01:16<00:13, 81.90it/s]

Reports:  85%|████████▌ | 6187/7269 [01:16<00:13, 78.49it/s]

Reports:  85%|████████▌ | 6196/7269 [01:16<00:13, 78.24it/s]

Reports:  85%|████████▌ | 6205/7269 [01:16<00:13, 80.13it/s]

Reports:  85%|████████▌ | 6214/7269 [01:16<00:13, 77.34it/s]

Reports:  86%|████████▌ | 6222/7269 [01:16<00:13, 75.86it/s]

Reports:  86%|████████▌ | 6231/7269 [01:17<00:13, 77.25it/s]

Reports:  86%|████████▌ | 6239/7269 [01:17<00:14, 69.96it/s]

Reports:  86%|████████▌ | 6250/7269 [01:17<00:14, 72.33it/s]

Reports:  86%|████████▌ | 6263/7269 [01:17<00:12, 81.33it/s]

Reports:  86%|████████▋ | 6276/7269 [01:17<00:11, 88.27it/s]

Reports:  86%|████████▋ | 6285/7269 [01:17<00:12, 78.00it/s]

Reports:  87%|████████▋ | 6297/7269 [01:17<00:11, 82.60it/s]

Reports:  87%|████████▋ | 6306/7269 [01:17<00:11, 82.26it/s]

Reports:  87%|████████▋ | 6315/7269 [01:18<00:12, 76.01it/s]

Reports:  87%|████████▋ | 6328/7269 [01:18<00:11, 80.88it/s]

Reports:  87%|████████▋ | 6337/7269 [01:18<00:12, 72.71it/s]

Reports:  87%|████████▋ | 6351/7269 [01:18<00:10, 86.28it/s]

Reports:  88%|████████▊ | 6363/7269 [01:18<00:10, 88.82it/s]

Reports:  88%|████████▊ | 6373/7269 [01:18<00:11, 80.08it/s]

Reports:  88%|████████▊ | 6386/7269 [01:18<00:10, 83.45it/s]

Reports:  88%|████████▊ | 6401/7269 [01:19<00:09, 94.18it/s]

Reports:  88%|████████▊ | 6411/7269 [01:19<00:10, 85.55it/s]

Reports:  88%|████████▊ | 6420/7269 [01:19<00:10, 81.50it/s]

Reports:  89%|████████▊ | 6434/7269 [01:19<00:09, 89.65it/s]

Reports:  89%|████████▊ | 6444/7269 [01:19<00:09, 86.98it/s]

Reports:  89%|████████▉ | 6455/7269 [01:19<00:09, 84.03it/s]

Reports:  89%|████████▉ | 6467/7269 [01:19<00:09, 88.10it/s]

Reports:  89%|████████▉ | 6476/7269 [01:19<00:09, 85.19it/s]

Reports:  89%|████████▉ | 6488/7269 [01:20<00:08, 88.07it/s]

Reports:  89%|████████▉ | 6500/7269 [01:20<00:08, 90.21it/s]

Reports:  90%|████████▉ | 6512/7269 [01:20<00:07, 95.21it/s]

Reports:  90%|████████▉ | 6522/7269 [01:20<00:08, 90.11it/s]

Reports:  90%|████████▉ | 6533/7269 [01:20<00:07, 92.70it/s]

Reports:  90%|█████████ | 6543/7269 [01:20<00:07, 91.91it/s]

Reports:  90%|█████████ | 6553/7269 [01:20<00:07, 91.41it/s]

Reports:  90%|█████████ | 6563/7269 [01:20<00:07, 92.10it/s]

Reports:  90%|█████████ | 6573/7269 [01:21<00:07, 90.43it/s]

Reports:  91%|█████████ | 6585/7269 [01:21<00:07, 96.04it/s]

Reports:  91%|█████████ | 6595/7269 [01:21<00:07, 91.17it/s]

Reports:  91%|█████████ | 6607/7269 [01:21<00:06, 95.50it/s]

Reports:  91%|█████████ | 6619/7269 [01:21<00:06, 99.23it/s]

Reports:  91%|█████████ | 6629/7269 [01:21<00:07, 89.12it/s]

Reports:  91%|█████████▏| 6641/7269 [01:21<00:06, 91.04it/s]

Reports:  92%|█████████▏| 6655/7269 [01:21<00:06, 100.20it/s]

Reports:  92%|█████████▏| 6666/7269 [01:22<00:06, 91.54it/s]

Reports:  92%|█████████▏| 6676/7269 [01:22<00:07, 82.79it/s]

Reports:  92%|█████████▏| 6689/7269 [01:22<00:07, 82.38it/s]

Reports:  92%|█████████▏| 6704/7269 [01:22<00:05, 95.44it/s]

Reports:  92%|█████████▏| 6714/7269 [01:22<00:06, 87.61it/s]

Reports:  93%|█████████▎| 6724/7269 [01:22<00:06, 88.30it/s]

Reports:  93%|█████████▎| 6737/7269 [01:22<00:06, 83.30it/s]

Reports:  93%|█████████▎| 6752/7269 [01:22<00:05, 96.32it/s]

Reports:  93%|█████████▎| 6763/7269 [01:23<00:06, 81.69it/s]

Reports:  93%|█████████▎| 6775/7269 [01:23<00:05, 87.69it/s]

Reports:  93%|█████████▎| 6785/7269 [01:23<00:05, 87.17it/s]

Reports:  93%|█████████▎| 6795/7269 [01:23<00:05, 86.37it/s]

Reports:  94%|█████████▎| 6809/7269 [01:23<00:04, 96.94it/s]

Reports:  94%|█████████▍| 6819/7269 [01:23<00:05, 81.81it/s]

Reports:  94%|█████████▍| 6828/7269 [01:23<00:05, 81.54it/s]

Reports:  94%|█████████▍| 6842/7269 [01:24<00:04, 86.82it/s]

Reports:  94%|█████████▍| 6851/7269 [01:24<00:05, 79.34it/s]

Reports:  94%|█████████▍| 6862/7269 [01:24<00:04, 85.48it/s]

Reports:  95%|█████████▍| 6872/7269 [01:24<00:04, 88.95it/s]

Reports:  95%|█████████▍| 6882/7269 [01:24<00:04, 87.80it/s]

Reports:  95%|█████████▍| 6893/7269 [01:24<00:04, 90.39it/s]

Reports:  95%|█████████▍| 6903/7269 [01:24<00:04, 84.34it/s]

Reports:  95%|█████████▌| 6913/7269 [01:24<00:04, 84.81it/s]

Reports:  95%|█████████▌| 6927/7269 [01:25<00:03, 92.81it/s]

Reports:  95%|█████████▌| 6937/7269 [01:25<00:03, 92.33it/s]

Reports:  96%|█████████▌| 6947/7269 [01:25<00:03, 84.69it/s]

Reports:  96%|█████████▌| 6958/7269 [01:25<00:03, 88.68it/s]

Reports:  96%|█████████▌| 6970/7269 [01:25<00:03, 91.39it/s]

Reports:  96%|█████████▌| 6980/7269 [01:25<00:03, 85.84it/s]

Reports:  96%|█████████▌| 6989/7269 [01:25<00:03, 82.04it/s]

Reports:  96%|█████████▋| 6998/7269 [01:25<00:03, 81.68it/s]

Reports:  96%|█████████▋| 7008/7269 [01:25<00:03, 82.66it/s]

Reports:  97%|█████████▋| 7018/7269 [01:26<00:02, 86.40it/s]

Reports:  97%|█████████▋| 7027/7269 [01:26<00:02, 83.76it/s]

Reports:  97%|█████████▋| 7037/7269 [01:26<00:02, 85.15it/s]

Reports:  97%|█████████▋| 7046/7269 [01:26<00:02, 85.61it/s]

Reports:  97%|█████████▋| 7059/7269 [01:26<00:02, 93.53it/s]

Reports:  97%|█████████▋| 7069/7269 [01:26<00:02, 91.80it/s]

Reports:  97%|█████████▋| 7079/7269 [01:26<00:02, 86.44it/s]

Reports:  98%|█████████▊| 7092/7269 [01:26<00:01, 94.17it/s]

Reports:  98%|█████████▊| 7102/7269 [01:27<00:01, 86.97it/s]

Reports:  98%|█████████▊| 7112/7269 [01:27<00:01, 84.53it/s]

Reports:  98%|█████████▊| 7121/7269 [01:27<00:01, 81.31it/s]

Reports:  98%|█████████▊| 7130/7269 [01:27<00:01, 80.53it/s]

Reports:  98%|█████████▊| 7143/7269 [01:27<00:01, 90.89it/s]

Reports:  98%|█████████▊| 7153/7269 [01:27<00:01, 83.93it/s]

Reports:  99%|█████████▊| 7162/7269 [01:27<00:01, 82.98it/s]

Reports:  99%|█████████▊| 7171/7269 [01:27<00:01, 79.33it/s]

Reports:  99%|█████████▉| 7182/7269 [01:28<00:01, 81.68it/s]

Reports:  99%|█████████▉| 7195/7269 [01:28<00:00, 88.07it/s]

Reports:  99%|█████████▉| 7204/7269 [01:28<00:00, 82.89it/s]

Reports:  99%|█████████▉| 7214/7269 [01:28<00:00, 84.85it/s]

Reports:  99%|█████████▉| 7224/7269 [01:28<00:00, 84.00it/s]

Reports: 100%|█████████▉| 7233/7269 [01:28<00:00, 73.53it/s]

Reports: 100%|█████████▉| 7248/7269 [01:28<00:00, 77.90it/s]

Reports: 100%|█████████▉| 7260/7269 [01:28<00:00, 85.81it/s]

Reports: 100%|██████████| 7269/7269 [01:29<00:00, 78.43it/s]

Reports: 100%|██████████| 7269/7269 [01:29<00:00, 81.57it/s]

Report rows: 4279

Gaps (ex-reports):   0%|          | 0/7269 [00:00<?, ?it/s]

Gaps (ex-reports):   0%|          | 4/7269 [00:00<04:19, 28.01it/s]

Gaps (ex-reports):   0%|          | 17/7269 [00:00<01:37, 74.01it/s]

Gaps (ex-reports):   0%|          | 25/7269 [00:00<01:50, 65.81it/s]

Gaps (ex-reports):   0%|          | 34/7269 [00:00<01:41, 71.27it/s]

Gaps (ex-reports):   1%|          | 42/7269 [00:00<01:37, 73.78it/s]

Gaps (ex-reports):   1%|          | 50/7269 [00:00<01:36, 74.46it/s]

Gaps (ex-reports):   1%|          | 58/7269 [00:00<01:51, 64.73it/s]

Gaps (ex-reports):   1%|          | 68/7269 [00:00<01:40, 71.96it/s]

Gaps (ex-reports):   1%|          | 76/7269 [00:01<02:00, 59.54it/s]

Gaps (ex-reports):   1%|          | 90/7269 [00:01<01:43, 69.08it/s]

Gaps (ex-reports):   1%|▏         | 99/7269 [00:01<01:39, 72.09it/s]

Gaps (ex-reports):   1%|▏         | 108/7269 [00:01<01:39, 71.70it/s]

Gaps (ex-reports):   2%|▏         | 116/7269 [00:01<01:43, 69.02it/s]

Gaps (ex-reports):   2%|▏         | 125/7269 [00:01<01:42, 69.45it/s]

Gaps (ex-reports):   2%|▏         | 138/7269 [00:01<01:26, 82.39it/s]

Gaps (ex-reports):   2%|▏         | 147/7269 [00:02<01:30, 78.91it/s]

Gaps (ex-reports):   2%|▏         | 156/7269 [00:02<01:36, 73.56it/s]

Gaps (ex-reports):   2%|▏         | 165/7269 [00:02<01:41, 70.14it/s]

Gaps (ex-reports):   2%|▏         | 179/7269 [00:02<01:23, 84.71it/s]

Gaps (ex-reports):   3%|▎         | 188/7269 [00:02<01:31, 77.45it/s]

Gaps (ex-reports):   3%|▎         | 197/7269 [00:02<02:00, 58.61it/s]

Gaps (ex-reports):   3%|▎         | 209/7269 [00:02<01:39, 70.82it/s]

Gaps (ex-reports):   3%|▎         | 222/7269 [00:03<01:25, 81.95it/s]

Gaps (ex-reports):   3%|▎         | 232/7269 [00:03<01:29, 78.35it/s]

Gaps (ex-reports):   3%|▎         | 243/7269 [00:03<01:23, 83.65it/s]

Gaps (ex-reports):   3%|▎         | 252/7269 [00:03<01:37, 71.94it/s]

Gaps (ex-reports):   4%|▎         | 263/7269 [00:03<01:27, 80.37it/s]

Gaps (ex-reports):   4%|▍         | 275/7269 [00:03<01:18, 89.59it/s]

Gaps (ex-reports):   4%|▍         | 285/7269 [00:03<01:22, 84.86it/s]

Gaps (ex-reports):   4%|▍         | 295/7269 [00:03<01:25, 81.31it/s]

Gaps (ex-reports):   4%|▍         | 306/7269 [00:04<01:20, 86.08it/s]

Gaps (ex-reports):   4%|▍         | 317/7269 [00:04<01:25, 81.40it/s]

Gaps (ex-reports):   5%|▍         | 329/7269 [00:04<01:19, 87.06it/s]

Gaps (ex-reports):   5%|▍         | 338/7269 [00:04<01:33, 73.93it/s]

Gaps (ex-reports):   5%|▍         | 350/7269 [00:04<01:26, 79.57it/s]

Gaps (ex-reports):   5%|▍         | 359/7269 [00:04<01:32, 74.37it/s]

Gaps (ex-reports):   5%|▌         | 368/7269 [00:04<01:30, 76.02it/s]

Gaps (ex-reports):   5%|▌         | 376/7269 [00:05<01:35, 72.39it/s]

Gaps (ex-reports):   5%|▌         | 385/7269 [00:05<01:39, 69.43it/s]

Gaps (ex-reports):   5%|▌         | 393/7269 [00:05<01:49, 62.96it/s]

Gaps (ex-reports):   6%|▌         | 406/7269 [00:05<01:29, 76.53it/s]

Gaps (ex-reports):   6%|▌         | 415/7269 [00:05<01:38, 69.73it/s]

Gaps (ex-reports):   6%|▌         | 423/7269 [00:05<01:40, 67.87it/s]

Gaps (ex-reports):   6%|▌         | 431/7269 [00:05<01:46, 64.16it/s]

Gaps (ex-reports):   6%|▌         | 439/7269 [00:06<01:58, 57.59it/s]

Gaps (ex-reports):   6%|▌         | 454/7269 [00:06<01:29, 76.30it/s]

Gaps (ex-reports):   6%|▋         | 463/7269 [00:06<01:47, 63.45it/s]

Gaps (ex-reports):   7%|▋         | 474/7269 [00:06<01:44, 65.32it/s]

Gaps (ex-reports):   7%|▋         | 488/7269 [00:06<01:25, 79.29it/s]

Gaps (ex-reports):   7%|▋         | 497/7269 [00:06<01:24, 79.81it/s]

Gaps (ex-reports):   7%|▋         | 506/7269 [00:06<01:31, 74.04it/s]

Gaps (ex-reports):   7%|▋         | 520/7269 [00:07<01:16, 88.25it/s]

Gaps (ex-reports):   7%|▋         | 530/7269 [00:07<01:15, 88.87it/s]

Gaps (ex-reports):   7%|▋         | 540/7269 [00:07<01:21, 82.70it/s]

Gaps (ex-reports):   8%|▊         | 554/7269 [00:07<01:22, 81.86it/s]

Gaps (ex-reports):   8%|▊         | 565/7269 [00:07<01:20, 83.13it/s]

Gaps (ex-reports):   8%|▊         | 577/7269 [00:07<01:15, 89.06it/s]

Gaps (ex-reports):   8%|▊         | 587/7269 [00:07<01:25, 77.74it/s]

Gaps (ex-reports):   8%|▊         | 597/7269 [00:07<01:25, 78.04it/s]

Gaps (ex-reports):   8%|▊         | 606/7269 [00:08<01:24, 78.85it/s]

Gaps (ex-reports):   8%|▊         | 615/7269 [00:08<01:36, 68.85it/s]

Gaps (ex-reports):   9%|▊         | 626/7269 [00:08<01:27, 76.26it/s]

Gaps (ex-reports):   9%|▉         | 638/7269 [00:08<01:16, 86.79it/s]

Gaps (ex-reports):   9%|▉         | 648/7269 [00:08<01:20, 82.36it/s]

Gaps (ex-reports):   9%|▉         | 658/7269 [00:08<01:27, 75.70it/s]

Gaps (ex-reports):   9%|▉         | 667/7269 [00:08<01:25, 77.08it/s]

Gaps (ex-reports):   9%|▉         | 679/7269 [00:08<01:17, 85.41it/s]

Gaps (ex-reports):   9%|▉         | 688/7269 [00:09<01:18, 84.21it/s]

Gaps (ex-reports):  10%|▉         | 697/7269 [00:09<01:18, 83.38it/s]

Gaps (ex-reports):  10%|▉         | 706/7269 [00:09<01:22, 79.44it/s]

Gaps (ex-reports):  10%|▉         | 715/7269 [00:09<01:22, 79.93it/s]

Gaps (ex-reports):  10%|█         | 728/7269 [00:09<01:11, 90.85it/s]

Gaps (ex-reports):  10%|█         | 738/7269 [00:09<01:21, 80.48it/s]

Gaps (ex-reports):  10%|█         | 748/7269 [00:09<01:18, 83.16it/s]

Gaps (ex-reports):  10%|█         | 757/7269 [00:09<01:21, 79.43it/s]

Gaps (ex-reports):  11%|█         | 768/7269 [00:10<01:16, 84.86it/s]

Gaps (ex-reports):  11%|█         | 778/7269 [00:10<01:15, 86.40it/s]

Gaps (ex-reports):  11%|█         | 788/7269 [00:10<01:19, 81.76it/s]

Gaps (ex-reports):  11%|█         | 803/7269 [00:10<01:07, 95.53it/s]

Gaps (ex-reports):  11%|█         | 813/7269 [00:10<01:13, 87.24it/s]

Gaps (ex-reports):  11%|█▏        | 822/7269 [00:10<01:21, 79.05it/s]

Gaps (ex-reports):  11%|█▏        | 831/7269 [00:10<01:20, 79.88it/s]

Gaps (ex-reports):  12%|█▏        | 840/7269 [00:10<01:26, 74.51it/s]

Gaps (ex-reports):  12%|█▏        | 854/7269 [00:11<01:12, 88.35it/s]

Gaps (ex-reports):  12%|█▏        | 864/7269 [00:11<01:14, 85.46it/s]

Gaps (ex-reports):  12%|█▏        | 873/7269 [00:11<01:34, 67.95it/s]

Gaps (ex-reports):  12%|█▏        | 887/7269 [00:11<01:28, 71.91it/s]

Gaps (ex-reports):  12%|█▏        | 903/7269 [00:11<01:16, 83.11it/s]

Gaps (ex-reports):  13%|█▎        | 912/7269 [00:11<01:17, 82.49it/s]

Gaps (ex-reports):  13%|█▎        | 921/7269 [00:12<01:39, 63.67it/s]

Gaps (ex-reports):  13%|█▎        | 935/7269 [00:12<01:21, 77.33it/s]

Gaps (ex-reports):  13%|█▎        | 944/7269 [00:12<01:23, 75.59it/s]

Gaps (ex-reports):  13%|█▎        | 953/7269 [00:12<01:27, 71.86it/s]

Gaps (ex-reports):  13%|█▎        | 961/7269 [00:12<01:49, 57.57it/s]

Gaps (ex-reports):  13%|█▎        | 972/7269 [00:12<01:40, 62.67it/s]

Gaps (ex-reports):  14%|█▎        | 985/7269 [00:12<01:23, 75.02it/s]

Gaps (ex-reports):  14%|█▎        | 994/7269 [00:13<01:27, 71.40it/s]

Gaps (ex-reports):  14%|█▍        | 1003/7269 [00:13<01:25, 73.70it/s]

Gaps (ex-reports):  14%|█▍        | 1011/7269 [00:13<01:28, 70.63it/s]

Gaps (ex-reports):  14%|█▍        | 1019/7269 [00:13<01:31, 68.36it/s]

Gaps (ex-reports):  14%|█▍        | 1030/7269 [00:13<01:30, 68.70it/s]

Gaps (ex-reports):  14%|█▍        | 1042/7269 [00:13<01:22, 75.86it/s]

Gaps (ex-reports):  14%|█▍        | 1050/7269 [00:13<01:35, 65.07it/s]

Gaps (ex-reports):  15%|█▍        | 1061/7269 [00:14<01:24, 73.38it/s]

Gaps (ex-reports):  15%|█▍        | 1069/7269 [00:14<01:49, 56.38it/s]

Gaps (ex-reports):  15%|█▍        | 1082/7269 [00:14<01:39, 62.00it/s]

Gaps (ex-reports):  15%|█▍        | 1089/7269 [00:14<01:42, 60.36it/s]

Gaps (ex-reports):  15%|█▌        | 1100/7269 [00:14<01:28, 69.38it/s]

Gaps (ex-reports):  15%|█▌        | 1108/7269 [00:14<01:28, 70.01it/s]

Gaps (ex-reports):  15%|█▌        | 1117/7269 [00:14<01:24, 72.91it/s]

Gaps (ex-reports):  16%|█▌        | 1127/7269 [00:15<01:22, 74.53it/s]

Gaps (ex-reports):  16%|█▌        | 1136/7269 [00:15<01:23, 73.60it/s]

Gaps (ex-reports):  16%|█▌        | 1150/7269 [00:15<01:15, 81.50it/s]

Gaps (ex-reports):  16%|█▌        | 1160/7269 [00:15<01:12, 83.88it/s]

Gaps (ex-reports):  16%|█▌        | 1169/7269 [00:15<01:27, 69.57it/s]

Gaps (ex-reports):  16%|█▌        | 1180/7269 [00:15<01:19, 76.86it/s]

Gaps (ex-reports):  16%|█▋        | 1189/7269 [00:15<01:21, 75.03it/s]

Gaps (ex-reports):  17%|█▋        | 1200/7269 [00:15<01:14, 81.37it/s]

Gaps (ex-reports):  17%|█▋        | 1209/7269 [00:16<01:32, 65.79it/s]

Gaps (ex-reports):  17%|█▋        | 1219/7269 [00:16<01:24, 71.55it/s]

Gaps (ex-reports):  17%|█▋        | 1227/7269 [00:16<01:30, 66.68it/s]

Gaps (ex-reports):  17%|█▋        | 1239/7269 [00:16<01:20, 74.49it/s]

Gaps (ex-reports):  17%|█▋        | 1249/7269 [00:16<01:19, 75.72it/s]

Gaps (ex-reports):  17%|█▋        | 1257/7269 [00:16<01:23, 71.99it/s]

Gaps (ex-reports):  17%|█▋        | 1268/7269 [00:16<01:21, 73.63it/s]

Gaps (ex-reports):  18%|█▊        | 1279/7269 [00:17<01:20, 74.66it/s]

Gaps (ex-reports):  18%|█▊        | 1288/7269 [00:17<01:21, 73.60it/s]

Gaps (ex-reports):  18%|█▊        | 1299/7269 [00:17<01:14, 80.32it/s]

Gaps (ex-reports):  18%|█▊        | 1308/7269 [00:17<01:16, 77.60it/s]

Gaps (ex-reports):  18%|█▊        | 1318/7269 [00:17<01:16, 78.15it/s]

Gaps (ex-reports):  18%|█▊        | 1328/7269 [00:17<01:13, 81.25it/s]

Gaps (ex-reports):  18%|█▊        | 1337/7269 [00:17<01:16, 77.29it/s]

Gaps (ex-reports):  19%|█▊        | 1346/7269 [00:17<01:18, 75.32it/s]

Gaps (ex-reports):  19%|█▊        | 1356/7269 [00:18<01:14, 79.39it/s]

Gaps (ex-reports):  19%|█▉        | 1365/7269 [00:18<01:13, 79.97it/s]

Gaps (ex-reports):  19%|█▉        | 1375/7269 [00:18<01:14, 79.51it/s]

Gaps (ex-reports):  19%|█▉        | 1383/7269 [00:18<01:19, 74.43it/s]

Gaps (ex-reports):  19%|█▉        | 1393/7269 [00:18<01:17, 75.65it/s]

Gaps (ex-reports):  19%|█▉        | 1402/7269 [00:18<01:16, 77.19it/s]

Gaps (ex-reports):  19%|█▉        | 1411/7269 [00:18<01:14, 78.35it/s]

Gaps (ex-reports):  20%|█▉        | 1424/7269 [00:18<01:13, 79.57it/s]

Gaps (ex-reports):  20%|█▉        | 1432/7269 [00:19<01:26, 67.31it/s]

Gaps (ex-reports):  20%|█▉        | 1446/7269 [00:19<01:13, 79.18it/s]

Gaps (ex-reports):  20%|██        | 1455/7269 [00:19<01:12, 79.68it/s]

Gaps (ex-reports):  20%|██        | 1466/7269 [00:19<01:11, 81.68it/s]

Gaps (ex-reports):  20%|██        | 1478/7269 [00:19<01:12, 79.65it/s]

Gaps (ex-reports):  20%|██        | 1487/7269 [00:19<01:20, 72.18it/s]

Gaps (ex-reports):  21%|██        | 1501/7269 [00:19<01:07, 85.62it/s]

Gaps (ex-reports):  21%|██        | 1510/7269 [00:20<01:15, 75.82it/s]

Gaps (ex-reports):  21%|██        | 1519/7269 [00:20<01:17, 74.47it/s]

Gaps (ex-reports):  21%|██        | 1527/7269 [00:20<01:17, 73.80it/s]

Gaps (ex-reports):  21%|██        | 1538/7269 [00:20<01:13, 77.64it/s]

Gaps (ex-reports):  21%|██▏       | 1548/7269 [00:20<01:10, 81.12it/s]

Gaps (ex-reports):  21%|██▏       | 1557/7269 [00:20<01:16, 75.09it/s]

Gaps (ex-reports):  22%|██▏       | 1570/7269 [00:20<01:08, 83.27it/s]

Gaps (ex-reports):  22%|██▏       | 1579/7269 [00:20<01:19, 71.75it/s]

Gaps (ex-reports):  22%|██▏       | 1594/7269 [00:21<01:09, 81.81it/s]

Gaps (ex-reports):  22%|██▏       | 1606/7269 [00:21<01:04, 88.40it/s]

Gaps (ex-reports):  22%|██▏       | 1616/7269 [00:21<01:15, 74.65it/s]

Gaps (ex-reports):  22%|██▏       | 1627/7269 [00:21<01:09, 80.65it/s]

Gaps (ex-reports):  23%|██▎       | 1636/7269 [00:21<01:12, 77.99it/s]

Gaps (ex-reports):  23%|██▎       | 1647/7269 [00:21<01:09, 80.47it/s]

Gaps (ex-reports):  23%|██▎       | 1658/7269 [00:21<01:05, 85.44it/s]

Gaps (ex-reports):  23%|██▎       | 1667/7269 [00:22<01:09, 80.98it/s]

Gaps (ex-reports):  23%|██▎       | 1680/7269 [00:22<01:03, 87.51it/s]

Gaps (ex-reports):  23%|██▎       | 1689/7269 [00:22<01:07, 82.41it/s]

Gaps (ex-reports):  23%|██▎       | 1698/7269 [00:22<01:10, 78.96it/s]

Gaps (ex-reports):  24%|██▎       | 1709/7269 [00:22<01:08, 81.25it/s]

Gaps (ex-reports):  24%|██▎       | 1718/7269 [00:22<01:10, 78.27it/s]

Gaps (ex-reports):  24%|██▎       | 1726/7269 [00:22<01:12, 76.42it/s]

Gaps (ex-reports):  24%|██▍       | 1737/7269 [00:22<01:06, 82.75it/s]

Gaps (ex-reports):  24%|██▍       | 1746/7269 [00:22<01:07, 82.35it/s]

Gaps (ex-reports):  24%|██▍       | 1756/7269 [00:23<01:05, 84.73it/s]

Gaps (ex-reports):  24%|██▍       | 1765/7269 [00:23<01:05, 83.79it/s]

Gaps (ex-reports):  24%|██▍       | 1774/7269 [00:23<01:08, 79.73it/s]

Gaps (ex-reports):  25%|██▍       | 1783/7269 [00:23<01:08, 80.39it/s]

Gaps (ex-reports):  25%|██▍       | 1792/7269 [00:23<01:10, 77.48it/s]

Gaps (ex-reports):  25%|██▍       | 1800/7269 [00:23<01:32, 59.02it/s]

Gaps (ex-reports):  25%|██▍       | 1814/7269 [00:23<01:12, 75.12it/s]

Gaps (ex-reports):  25%|██▌       | 1825/7269 [00:23<01:07, 81.19it/s]

Gaps (ex-reports):  25%|██▌       | 1834/7269 [00:24<01:09, 78.24it/s]

Gaps (ex-reports):  25%|██▌       | 1843/7269 [00:24<01:16, 70.81it/s]

Gaps (ex-reports):  26%|██▌       | 1857/7269 [00:24<01:05, 82.04it/s]

Gaps (ex-reports):  26%|██▌       | 1866/7269 [00:24<01:10, 76.20it/s]

Gaps (ex-reports):  26%|██▌       | 1874/7269 [00:24<01:19, 67.80it/s]

Gaps (ex-reports):  26%|██▌       | 1890/7269 [00:24<01:10, 75.97it/s]

Gaps (ex-reports):  26%|██▌       | 1900/7269 [00:25<01:10, 76.54it/s]

Gaps (ex-reports):  26%|██▋       | 1909/7269 [00:25<01:16, 70.19it/s]

Gaps (ex-reports):  26%|██▋       | 1923/7269 [00:25<01:03, 83.62it/s]

Gaps (ex-reports):  27%|██▋       | 1932/7269 [00:25<01:11, 74.69it/s]

Gaps (ex-reports):  27%|██▋       | 1942/7269 [00:25<01:07, 78.59it/s]

Gaps (ex-reports):  27%|██▋       | 1951/7269 [00:25<01:12, 73.77it/s]

Gaps (ex-reports):  27%|██▋       | 1962/7269 [00:25<01:08, 77.46it/s]

Gaps (ex-reports):  27%|██▋       | 1975/7269 [00:25<01:04, 81.75it/s]

Gaps (ex-reports):  27%|██▋       | 1984/7269 [00:26<01:11, 73.48it/s]

Gaps (ex-reports):  27%|██▋       | 1996/7269 [00:26<01:06, 79.36it/s]

Gaps (ex-reports):  28%|██▊       | 2005/7269 [00:26<01:05, 79.82it/s]

Gaps (ex-reports):  28%|██▊       | 2014/7269 [00:26<01:08, 77.24it/s]

Gaps (ex-reports):  28%|██▊       | 2025/7269 [00:26<01:05, 80.03it/s]

Gaps (ex-reports):  28%|██▊       | 2034/7269 [00:26<01:15, 69.67it/s]

Gaps (ex-reports):  28%|██▊       | 2047/7269 [00:26<01:04, 81.48it/s]

Gaps (ex-reports):  28%|██▊       | 2056/7269 [00:27<01:13, 70.68it/s]

Gaps (ex-reports):  28%|██▊       | 2065/7269 [00:27<01:16, 68.43it/s]

Gaps (ex-reports):  29%|██▊       | 2073/7269 [00:27<01:17, 66.91it/s]

Gaps (ex-reports):  29%|██▊       | 2081/7269 [00:27<01:16, 68.24it/s]

Gaps (ex-reports):  29%|██▊       | 2088/7269 [00:27<01:23, 62.07it/s]

Gaps (ex-reports):  29%|██▉       | 2100/7269 [00:27<01:17, 66.31it/s]

Gaps (ex-reports):  29%|██▉       | 2110/7269 [00:27<01:11, 72.02it/s]

Gaps (ex-reports):  29%|██▉       | 2118/7269 [00:27<01:14, 69.51it/s]

Gaps (ex-reports):  29%|██▉       | 2126/7269 [00:28<01:13, 70.23it/s]

Gaps (ex-reports):  29%|██▉       | 2135/7269 [00:28<01:10, 73.28it/s]

Gaps (ex-reports):  29%|██▉       | 2143/7269 [00:28<01:21, 62.89it/s]

Gaps (ex-reports):  30%|██▉       | 2154/7269 [00:28<01:10, 72.21it/s]

Gaps (ex-reports):  30%|██▉       | 2167/7269 [00:28<01:00, 84.28it/s]

Gaps (ex-reports):  30%|██▉       | 2176/7269 [00:28<01:08, 74.50it/s]

Gaps (ex-reports):  30%|███       | 2186/7269 [00:28<01:04, 78.68it/s]

Gaps (ex-reports):  30%|███       | 2195/7269 [00:29<01:06, 76.28it/s]

Gaps (ex-reports):  30%|███       | 2204/7269 [00:29<01:05, 77.58it/s]

Gaps (ex-reports):  30%|███       | 2212/7269 [00:29<01:11, 70.37it/s]

Gaps (ex-reports):  31%|███       | 2223/7269 [00:29<01:09, 72.55it/s]

Gaps (ex-reports):  31%|███       | 2231/7269 [00:29<01:09, 72.31it/s]

Gaps (ex-reports):  31%|███       | 2239/7269 [00:29<01:23, 60.37it/s]

Gaps (ex-reports):  31%|███       | 2253/7269 [00:29<01:07, 73.92it/s]

Gaps (ex-reports):  31%|███       | 2261/7269 [00:29<01:13, 68.43it/s]

Gaps (ex-reports):  31%|███       | 2271/7269 [00:30<01:17, 64.62it/s]

Gaps (ex-reports):  31%|███▏      | 2285/7269 [00:30<01:04, 76.74it/s]

Gaps (ex-reports):  32%|███▏      | 2294/7269 [00:30<01:19, 62.21it/s]

Gaps (ex-reports):  32%|███▏      | 2307/7269 [00:30<01:13, 67.97it/s]

Gaps (ex-reports):  32%|███▏      | 2317/7269 [00:30<01:12, 68.48it/s]

Gaps (ex-reports):  32%|███▏      | 2327/7269 [00:30<01:09, 71.15it/s]

Gaps (ex-reports):  32%|███▏      | 2336/7269 [00:31<01:09, 71.13it/s]

Gaps (ex-reports):  32%|███▏      | 2344/7269 [00:31<01:14, 66.55it/s]

Gaps (ex-reports):  32%|███▏      | 2351/7269 [00:31<01:14, 65.67it/s]

Gaps (ex-reports):  32%|███▏      | 2360/7269 [00:31<01:12, 67.31it/s]

Gaps (ex-reports):  33%|███▎      | 2369/7269 [00:31<01:40, 48.64it/s]

Gaps (ex-reports):  33%|███▎      | 2377/7269 [00:31<01:31, 53.53it/s]

Gaps (ex-reports):  33%|███▎      | 2384/7269 [00:31<01:33, 52.25it/s]

Gaps (ex-reports):  33%|███▎      | 2393/7269 [00:32<01:25, 57.11it/s]

Gaps (ex-reports):  33%|███▎      | 2403/7269 [00:32<01:14, 65.13it/s]

Gaps (ex-reports):  33%|███▎      | 2411/7269 [00:32<01:15, 64.39it/s]

Gaps (ex-reports):  33%|███▎      | 2420/7269 [00:32<01:18, 61.81it/s]

Gaps (ex-reports):  33%|███▎      | 2433/7269 [00:32<01:06, 73.13it/s]

Gaps (ex-reports):  34%|███▎      | 2441/7269 [00:32<01:25, 56.22it/s]

Gaps (ex-reports):  34%|███▍      | 2454/7269 [00:33<01:11, 67.48it/s]

Gaps (ex-reports):  34%|███▍      | 2462/7269 [00:33<01:10, 68.50it/s]

Gaps (ex-reports):  34%|███▍      | 2472/7269 [00:33<01:04, 73.86it/s]

Gaps (ex-reports):  34%|███▍      | 2480/7269 [00:33<01:07, 70.71it/s]

Gaps (ex-reports):  34%|███▍      | 2490/7269 [00:33<01:07, 70.30it/s]

Gaps (ex-reports):  34%|███▍      | 2503/7269 [00:33<00:57, 82.38it/s]

Gaps (ex-reports):  35%|███▍      | 2512/7269 [00:33<01:13, 64.65it/s]

Gaps (ex-reports):  35%|███▍      | 2523/7269 [00:33<01:05, 72.68it/s]

Gaps (ex-reports):  35%|███▍      | 2532/7269 [00:34<01:10, 67.47it/s]

Gaps (ex-reports):  35%|███▌      | 2545/7269 [00:34<01:01, 76.81it/s]

Gaps (ex-reports):  35%|███▌      | 2556/7269 [00:34<00:57, 82.38it/s]

Gaps (ex-reports):  35%|███▌      | 2565/7269 [00:34<01:01, 76.13it/s]

Gaps (ex-reports):  35%|███▌      | 2576/7269 [00:34<00:59, 79.09it/s]

Gaps (ex-reports):  36%|███▌      | 2589/7269 [00:34<00:52, 88.97it/s]

Gaps (ex-reports):  36%|███▌      | 2599/7269 [00:34<01:04, 72.52it/s]

Gaps (ex-reports):  36%|███▌      | 2611/7269 [00:35<00:57, 81.17it/s]

Gaps (ex-reports):  36%|███▌      | 2620/7269 [00:35<00:57, 81.12it/s]

Gaps (ex-reports):  36%|███▌      | 2629/7269 [00:35<00:57, 81.10it/s]

Gaps (ex-reports):  36%|███▋      | 2638/7269 [00:35<00:57, 81.11it/s]

Gaps (ex-reports):  36%|███▋      | 2647/7269 [00:35<00:59, 78.00it/s]

Gaps (ex-reports):  37%|███▋      | 2656/7269 [00:35<01:00, 75.92it/s]

Gaps (ex-reports):  37%|███▋      | 2664/7269 [00:35<01:03, 72.00it/s]

Gaps (ex-reports):  37%|███▋      | 2677/7269 [00:35<00:54, 84.44it/s]

Gaps (ex-reports):  37%|███▋      | 2686/7269 [00:35<00:57, 80.18it/s]

Gaps (ex-reports):  37%|███▋      | 2695/7269 [00:36<00:59, 77.30it/s]

Gaps (ex-reports):  37%|███▋      | 2703/7269 [00:36<01:02, 72.94it/s]

Gaps (ex-reports):  37%|███▋      | 2712/7269 [00:36<01:05, 69.64it/s]

Gaps (ex-reports):  37%|███▋      | 2725/7269 [00:36<00:55, 82.35it/s]

Gaps (ex-reports):  38%|███▊      | 2734/7269 [00:36<00:55, 81.96it/s]

Gaps (ex-reports):  38%|███▊      | 2744/7269 [00:36<01:02, 72.58it/s]

Gaps (ex-reports):  38%|███▊      | 2758/7269 [00:36<00:54, 83.21it/s]

Gaps (ex-reports):  38%|███▊      | 2767/7269 [00:37<00:56, 79.72it/s]

Gaps (ex-reports):  38%|███▊      | 2776/7269 [00:37<00:56, 80.17it/s]

Gaps (ex-reports):  38%|███▊      | 2786/7269 [00:37<00:54, 82.93it/s]

Gaps (ex-reports):  38%|███▊      | 2795/7269 [00:37<00:58, 76.19it/s]

Gaps (ex-reports):  39%|███▊      | 2808/7269 [00:37<00:53, 83.91it/s]

Gaps (ex-reports):  39%|███▉      | 2817/7269 [00:37<01:04, 69.54it/s]

Gaps (ex-reports):  39%|███▉      | 2828/7269 [00:37<00:57, 76.85it/s]

Gaps (ex-reports):  39%|███▉      | 2842/7269 [00:38<00:56, 77.99it/s]

Gaps (ex-reports):  39%|███▉      | 2856/7269 [00:38<00:49, 89.63it/s]

Gaps (ex-reports):  39%|███▉      | 2866/7269 [00:38<00:50, 86.50it/s]

Gaps (ex-reports):  40%|███▉      | 2875/7269 [00:38<00:55, 79.09it/s]

Gaps (ex-reports):  40%|███▉      | 2884/7269 [00:38<00:57, 76.85it/s]

Gaps (ex-reports):  40%|███▉      | 2894/7269 [00:38<00:54, 80.37it/s]

Gaps (ex-reports):  40%|███▉      | 2903/7269 [00:38<00:53, 81.78it/s]

Gaps (ex-reports):  40%|████      | 2912/7269 [00:38<00:55, 78.81it/s]

Gaps (ex-reports):  40%|████      | 2923/7269 [00:38<00:51, 84.53it/s]

Gaps (ex-reports):  40%|████      | 2932/7269 [00:39<00:57, 75.63it/s]

Gaps (ex-reports):  40%|████      | 2941/7269 [00:39<00:54, 78.74it/s]

Gaps (ex-reports):  41%|████      | 2950/7269 [00:39<01:07, 63.90it/s]

Gaps (ex-reports):  41%|████      | 2964/7269 [00:39<00:54, 79.29it/s]

Gaps (ex-reports):  41%|████      | 2973/7269 [00:39<00:55, 77.01it/s]

Gaps (ex-reports):  41%|████      | 2982/7269 [00:39<00:56, 75.29it/s]

Gaps (ex-reports):  41%|████      | 2995/7269 [00:39<00:49, 86.61it/s]

Gaps (ex-reports):  41%|████▏     | 3005/7269 [00:40<00:54, 77.99it/s]

Gaps (ex-reports):  41%|████▏     | 3014/7269 [00:40<00:54, 78.70it/s]

Gaps (ex-reports):  42%|████▏     | 3023/7269 [00:40<00:55, 77.04it/s]

Gaps (ex-reports):  42%|████▏     | 3033/7269 [00:40<00:52, 80.43it/s]

Gaps (ex-reports):  42%|████▏     | 3045/7269 [00:40<00:49, 84.84it/s]

Gaps (ex-reports):  42%|████▏     | 3054/7269 [00:40<00:54, 77.74it/s]

Gaps (ex-reports):  42%|████▏     | 3064/7269 [00:40<00:51, 80.97it/s]

Gaps (ex-reports):  42%|████▏     | 3073/7269 [00:40<00:57, 72.39it/s]

Gaps (ex-reports):  42%|████▏     | 3086/7269 [00:41<00:49, 84.08it/s]

Gaps (ex-reports):  43%|████▎     | 3095/7269 [00:41<00:57, 72.20it/s]

Gaps (ex-reports):  43%|████▎     | 3104/7269 [00:41<00:59, 70.11it/s]

Gaps (ex-reports):  43%|████▎     | 3114/7269 [00:41<00:55, 74.78it/s]

Gaps (ex-reports):  43%|████▎     | 3122/7269 [00:41<00:56, 73.98it/s]

Gaps (ex-reports):  43%|████▎     | 3130/7269 [00:41<00:56, 73.43it/s]

Gaps (ex-reports):  43%|████▎     | 3138/7269 [00:41<00:56, 72.99it/s]

Gaps (ex-reports):  43%|████▎     | 3146/7269 [00:41<00:59, 68.72it/s]

Gaps (ex-reports):  43%|████▎     | 3156/7269 [00:42<00:53, 76.41it/s]

Gaps (ex-reports):  44%|████▎     | 3164/7269 [00:42<00:59, 69.15it/s]

Gaps (ex-reports):  44%|████▎     | 3174/7269 [00:42<00:54, 75.28it/s]

Gaps (ex-reports):  44%|████▍     | 3182/7269 [00:42<00:57, 71.53it/s]

Gaps (ex-reports):  44%|████▍     | 3190/7269 [00:42<00:56, 71.74it/s]

Gaps (ex-reports):  44%|████▍     | 3198/7269 [00:42<00:58, 69.11it/s]

Gaps (ex-reports):  44%|████▍     | 3206/7269 [00:42<00:58, 69.93it/s]

Gaps (ex-reports):  44%|████▍     | 3214/7269 [00:42<00:59, 67.84it/s]

Gaps (ex-reports):  44%|████▍     | 3221/7269 [00:43<01:08, 59.27it/s]

Gaps (ex-reports):  44%|████▍     | 3231/7269 [00:43<01:00, 67.19it/s]

Gaps (ex-reports):  45%|████▍     | 3238/7269 [00:43<01:05, 61.55it/s]

Gaps (ex-reports):  45%|████▍     | 3250/7269 [00:43<00:56, 71.17it/s]

Gaps (ex-reports):  45%|████▍     | 3258/7269 [00:43<00:58, 68.78it/s]

Gaps (ex-reports):  45%|████▍     | 3267/7269 [00:43<00:57, 69.33it/s]

Gaps (ex-reports):  45%|████▌     | 3275/7269 [00:43<00:59, 67.51it/s]

Gaps (ex-reports):  45%|████▌     | 3287/7269 [00:43<00:54, 73.25it/s]

Gaps (ex-reports):  45%|████▌     | 3295/7269 [00:44<01:00, 65.55it/s]

Gaps (ex-reports):  45%|████▌     | 3305/7269 [00:44<00:59, 66.92it/s]

Gaps (ex-reports):  46%|████▌     | 3313/7269 [00:44<00:59, 66.39it/s]

Gaps (ex-reports):  46%|████▌     | 3324/7269 [00:44<00:52, 74.92it/s]

Gaps (ex-reports):  46%|████▌     | 3332/7269 [00:44<00:57, 68.84it/s]

Gaps (ex-reports):  46%|████▌     | 3342/7269 [00:44<00:54, 71.77it/s]

Gaps (ex-reports):  46%|████▌     | 3350/7269 [00:44<00:56, 69.29it/s]

Gaps (ex-reports):  46%|████▌     | 3358/7269 [00:45<00:55, 69.99it/s]

Gaps (ex-reports):  46%|████▋     | 3366/7269 [00:45<00:55, 70.58it/s]

Gaps (ex-reports):  46%|████▋     | 3374/7269 [00:45<00:57, 68.19it/s]

Gaps (ex-reports):  47%|████▋     | 3384/7269 [00:45<00:53, 72.53it/s]

Gaps (ex-reports):  47%|████▋     | 3392/7269 [00:45<01:00, 63.69it/s]

Gaps (ex-reports):  47%|████▋     | 3401/7269 [00:45<00:58, 65.70it/s]

Gaps (ex-reports):  47%|████▋     | 3408/7269 [00:45<01:01, 62.61it/s]

Gaps (ex-reports):  47%|████▋     | 3418/7269 [00:45<00:58, 65.50it/s]

Gaps (ex-reports):  47%|████▋     | 3425/7269 [00:46<01:02, 61.96it/s]

Gaps (ex-reports):  47%|████▋     | 3435/7269 [00:46<00:57, 66.75it/s]

Gaps (ex-reports):  47%|████▋     | 3442/7269 [00:46<01:03, 59.88it/s]

Gaps (ex-reports):  48%|████▊     | 3455/7269 [00:46<00:50, 74.80it/s]

Gaps (ex-reports):  48%|████▊     | 3463/7269 [00:46<00:56, 67.75it/s]

Gaps (ex-reports):  48%|████▊     | 3473/7269 [00:46<00:51, 73.64it/s]

Gaps (ex-reports):  48%|████▊     | 3481/7269 [00:46<00:59, 63.27it/s]

Gaps (ex-reports):  48%|████▊     | 3490/7269 [00:47<01:05, 57.40it/s]

Gaps (ex-reports):  48%|████▊     | 3506/7269 [00:47<00:54, 68.50it/s]

Gaps (ex-reports):  48%|████▊     | 3514/7269 [00:47<00:55, 67.11it/s]

Gaps (ex-reports):  48%|████▊     | 3524/7269 [00:47<00:53, 70.22it/s]

Gaps (ex-reports):  49%|████▊     | 3532/7269 [00:47<00:54, 68.23it/s]

Gaps (ex-reports):  49%|████▊     | 3539/7269 [00:47<00:57, 64.38it/s]

Gaps (ex-reports):  49%|████▉     | 3546/7269 [00:47<01:02, 59.59it/s]

Gaps (ex-reports):  49%|████▉     | 3558/7269 [00:48<00:53, 69.58it/s]

Gaps (ex-reports):  49%|████▉     | 3566/7269 [00:48<00:56, 65.33it/s]

Gaps (ex-reports):  49%|████▉     | 3575/7269 [00:48<01:02, 58.70it/s]

Gaps (ex-reports):  49%|████▉     | 3586/7269 [00:48<00:52, 69.92it/s]

Gaps (ex-reports):  49%|████▉     | 3594/7269 [00:48<00:53, 68.78it/s]

Gaps (ex-reports):  50%|████▉     | 3604/7269 [00:48<00:49, 74.36it/s]

Gaps (ex-reports):  50%|████▉     | 3612/7269 [00:48<00:51, 70.95it/s]

Gaps (ex-reports):  50%|████▉     | 3624/7269 [00:48<00:48, 75.30it/s]

Gaps (ex-reports):  50%|█████     | 3636/7269 [00:49<00:44, 81.04it/s]

Gaps (ex-reports):  50%|█████     | 3645/7269 [00:49<00:54, 66.58it/s]

Gaps (ex-reports):  50%|█████     | 3659/7269 [00:49<00:45, 78.72it/s]

Gaps (ex-reports):  50%|█████     | 3668/7269 [00:49<00:44, 80.50it/s]

Gaps (ex-reports):  51%|█████     | 3678/7269 [00:49<00:48, 74.52it/s]

Gaps (ex-reports):  51%|█████     | 3688/7269 [00:49<00:45, 78.91it/s]

Gaps (ex-reports):  51%|█████     | 3697/7269 [00:49<00:44, 79.57it/s]

Gaps (ex-reports):  51%|█████     | 3707/7269 [00:50<00:43, 82.59it/s]

Gaps (ex-reports):  51%|█████     | 3716/7269 [00:50<00:53, 66.10it/s]

Gaps (ex-reports):  51%|█████▏    | 3730/7269 [00:50<00:43, 80.87it/s]

Gaps (ex-reports):  51%|█████▏    | 3739/7269 [00:50<00:46, 75.44it/s]

Gaps (ex-reports):  52%|█████▏    | 3748/7269 [00:50<00:46, 76.20it/s]

Gaps (ex-reports):  52%|█████▏    | 3757/7269 [00:50<00:46, 75.36it/s]

Gaps (ex-reports):  52%|█████▏    | 3765/7269 [00:50<00:47, 74.45it/s]

Gaps (ex-reports):  52%|█████▏    | 3773/7269 [00:50<00:49, 71.09it/s]

Gaps (ex-reports):  52%|█████▏    | 3782/7269 [00:51<00:47, 73.92it/s]

Gaps (ex-reports):  52%|█████▏    | 3792/7269 [00:51<00:44, 78.48it/s]

Gaps (ex-reports):  52%|█████▏    | 3801/7269 [00:51<00:44, 78.12it/s]

Gaps (ex-reports):  52%|█████▏    | 3812/7269 [00:51<00:40, 85.62it/s]

Gaps (ex-reports):  53%|█████▎    | 3821/7269 [00:51<00:46, 74.91it/s]

Gaps (ex-reports):  53%|█████▎    | 3833/7269 [00:51<00:39, 86.12it/s]

Gaps (ex-reports):  53%|█████▎    | 3843/7269 [00:51<00:40, 84.20it/s]

Gaps (ex-reports):  53%|█████▎    | 3852/7269 [00:51<00:40, 84.39it/s]

Gaps (ex-reports):  53%|█████▎    | 3861/7269 [00:52<00:42, 80.15it/s]

Gaps (ex-reports):  53%|█████▎    | 3872/7269 [00:52<00:43, 78.97it/s]

Gaps (ex-reports):  53%|█████▎    | 3885/7269 [00:52<00:39, 86.02it/s]

Gaps (ex-reports):  54%|█████▎    | 3894/7269 [00:52<00:39, 84.63it/s]

Gaps (ex-reports):  54%|█████▎    | 3904/7269 [00:52<00:51, 65.42it/s]

Gaps (ex-reports):  54%|█████▍    | 3920/7269 [00:52<00:45, 73.91it/s]

Gaps (ex-reports):  54%|█████▍    | 3929/7269 [00:52<00:44, 75.75it/s]

Gaps (ex-reports):  54%|█████▍    | 3937/7269 [00:53<00:46, 72.32it/s]

Gaps (ex-reports):  54%|█████▍    | 3945/7269 [00:53<00:47, 69.77it/s]

Gaps (ex-reports):  54%|█████▍    | 3956/7269 [00:53<00:47, 70.24it/s]

Gaps (ex-reports):  55%|█████▍    | 3970/7269 [00:53<00:42, 77.98it/s]

Gaps (ex-reports):  55%|█████▍    | 3978/7269 [00:53<00:47, 69.12it/s]

Gaps (ex-reports):  55%|█████▍    | 3988/7269 [00:53<00:44, 74.24it/s]

Gaps (ex-reports):  55%|█████▌    | 4001/7269 [00:53<00:38, 85.12it/s]

Gaps (ex-reports):  55%|█████▌    | 4010/7269 [00:54<00:47, 68.28it/s]

Gaps (ex-reports):  55%|█████▌    | 4023/7269 [00:54<00:41, 77.38it/s]

Gaps (ex-reports):  55%|█████▌    | 4034/7269 [00:54<00:39, 82.83it/s]

Gaps (ex-reports):  56%|█████▌    | 4043/7269 [00:54<00:40, 79.24it/s]

Gaps (ex-reports):  56%|█████▌    | 4053/7269 [00:54<00:39, 82.22it/s]

Gaps (ex-reports):  56%|█████▌    | 4062/7269 [00:54<00:39, 81.91it/s]

Gaps (ex-reports):  56%|█████▌    | 4072/7269 [00:54<00:38, 84.11it/s]

Gaps (ex-reports):  56%|█████▌    | 4086/7269 [00:54<00:39, 79.75it/s]

Gaps (ex-reports):  56%|█████▋    | 4099/7269 [00:55<00:34, 91.44it/s]

Gaps (ex-reports):  57%|█████▋    | 4109/7269 [00:55<00:36, 85.57it/s]

Gaps (ex-reports):  57%|█████▋    | 4118/7269 [00:55<00:38, 82.64it/s]

Gaps (ex-reports):  57%|█████▋    | 4127/7269 [00:55<00:37, 84.05it/s]

Gaps (ex-reports):  57%|█████▋    | 4136/7269 [00:55<00:39, 80.07it/s]

Gaps (ex-reports):  57%|█████▋    | 4150/7269 [00:55<00:34, 89.42it/s]

Gaps (ex-reports):  57%|█████▋    | 4160/7269 [00:55<00:37, 83.13it/s]

Gaps (ex-reports):  57%|█████▋    | 4169/7269 [00:55<00:37, 82.51it/s]

Gaps (ex-reports):  57%|█████▋    | 4178/7269 [00:56<00:39, 78.98it/s]

Gaps (ex-reports):  58%|█████▊    | 4187/7269 [00:56<00:38, 79.68it/s]

Gaps (ex-reports):  58%|█████▊    | 4199/7269 [00:56<00:36, 84.39it/s]

Gaps (ex-reports):  58%|█████▊    | 4209/7269 [00:56<00:39, 76.90it/s]

Gaps (ex-reports):  58%|█████▊    | 4221/7269 [00:56<00:38, 79.23it/s]

Gaps (ex-reports):  58%|█████▊    | 4234/7269 [00:56<00:36, 82.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4243/7269 [00:56<00:36, 82.43it/s]

Gaps (ex-reports):  59%|█████▊    | 4253/7269 [00:56<00:37, 81.31it/s]

Gaps (ex-reports):  59%|█████▊    | 4262/7269 [00:57<00:36, 81.35it/s]

Gaps (ex-reports):  59%|█████▉    | 4271/7269 [00:57<00:44, 67.68it/s]

Gaps (ex-reports):  59%|█████▉    | 4284/7269 [00:57<00:39, 74.66it/s]

Gaps (ex-reports):  59%|█████▉    | 4292/7269 [00:57<00:44, 66.84it/s]

Gaps (ex-reports):  59%|█████▉    | 4300/7269 [00:57<00:45, 65.84it/s]

Gaps (ex-reports):  59%|█████▉    | 4308/7269 [00:57<00:43, 67.43it/s]

Gaps (ex-reports):  59%|█████▉    | 4317/7269 [00:57<00:40, 72.05it/s]

Gaps (ex-reports):  59%|█████▉    | 4325/7269 [00:58<00:41, 71.02it/s]

Gaps (ex-reports):  60%|█████▉    | 4333/7269 [00:58<00:41, 71.35it/s]

Gaps (ex-reports):  60%|█████▉    | 4341/7269 [00:58<00:44, 66.19it/s]

Gaps (ex-reports):  60%|█████▉    | 4349/7269 [00:58<00:46, 62.89it/s]

Gaps (ex-reports):  60%|█████▉    | 4358/7269 [00:58<00:43, 67.33it/s]

Gaps (ex-reports):  60%|██████    | 4366/7269 [00:58<00:42, 69.07it/s]

Gaps (ex-reports):  60%|██████    | 4374/7269 [00:58<00:46, 62.33it/s]

Gaps (ex-reports):  60%|██████    | 4381/7269 [00:59<01:12, 39.83it/s]

Gaps (ex-reports):  60%|██████    | 4391/7269 [00:59<00:59, 48.28it/s]

Gaps (ex-reports):  61%|██████    | 4398/7269 [00:59<00:55, 51.34it/s]

Gaps (ex-reports):  61%|██████    | 4410/7269 [00:59<00:45, 62.37it/s]

Gaps (ex-reports):  61%|██████    | 4418/7269 [00:59<00:50, 56.88it/s]

Gaps (ex-reports):  61%|██████    | 4428/7269 [00:59<00:44, 64.54it/s]

Gaps (ex-reports):  61%|██████    | 4436/7269 [00:59<00:48, 58.10it/s]

Gaps (ex-reports):  61%|██████    | 4446/7269 [01:00<00:47, 59.63it/s]

Gaps (ex-reports):  61%|██████▏   | 4454/7269 [01:00<00:44, 62.59it/s]

Gaps (ex-reports):  61%|██████▏   | 4463/7269 [01:00<00:43, 64.92it/s]

Gaps (ex-reports):  61%|██████▏   | 4470/7269 [01:00<00:46, 60.15it/s]

Gaps (ex-reports):  62%|██████▏   | 4481/7269 [01:00<00:51, 54.27it/s]

Gaps (ex-reports):  62%|██████▏   | 4497/7269 [01:00<00:38, 71.87it/s]

Gaps (ex-reports):  62%|██████▏   | 4505/7269 [01:00<00:38, 71.95it/s]

Gaps (ex-reports):  62%|██████▏   | 4515/7269 [01:01<00:35, 76.53it/s]

Gaps (ex-reports):  62%|██████▏   | 4524/7269 [01:01<00:48, 56.46it/s]

Gaps (ex-reports):  62%|██████▏   | 4538/7269 [01:01<00:38, 70.03it/s]

Gaps (ex-reports):  63%|██████▎   | 4547/7269 [01:01<00:38, 70.40it/s]

Gaps (ex-reports):  63%|██████▎   | 4558/7269 [01:01<00:35, 77.32it/s]

Gaps (ex-reports):  63%|██████▎   | 4567/7269 [01:01<00:38, 70.44it/s]

Gaps (ex-reports):  63%|██████▎   | 4578/7269 [01:01<00:34, 77.49it/s]

Gaps (ex-reports):  63%|██████▎   | 4588/7269 [01:02<00:33, 80.79it/s]

Gaps (ex-reports):  63%|██████▎   | 4598/7269 [01:02<00:32, 83.40it/s]

Gaps (ex-reports):  63%|██████▎   | 4607/7269 [01:02<00:32, 82.82it/s]

Gaps (ex-reports):  64%|██████▎   | 4616/7269 [01:02<00:33, 78.74it/s]

Gaps (ex-reports):  64%|██████▎   | 4626/7269 [01:02<00:32, 82.30it/s]

Gaps (ex-reports):  64%|██████▍   | 4635/7269 [01:02<00:34, 75.79it/s]

Gaps (ex-reports):  64%|██████▍   | 4643/7269 [01:02<00:36, 71.86it/s]

Gaps (ex-reports):  64%|██████▍   | 4655/7269 [01:02<00:31, 81.82it/s]

Gaps (ex-reports):  64%|██████▍   | 4665/7269 [01:03<00:30, 84.13it/s]

Gaps (ex-reports):  64%|██████▍   | 4675/7269 [01:03<00:30, 85.98it/s]

Gaps (ex-reports):  64%|██████▍   | 4684/7269 [01:03<00:30, 84.58it/s]

Gaps (ex-reports):  65%|██████▍   | 4697/7269 [01:03<00:29, 86.80it/s]

Gaps (ex-reports):  65%|██████▍   | 4706/7269 [01:03<00:32, 78.95it/s]

Gaps (ex-reports):  65%|██████▍   | 4717/7269 [01:03<00:31, 81.32it/s]

Gaps (ex-reports):  65%|██████▌   | 4728/7269 [01:03<00:30, 84.24it/s]

Gaps (ex-reports):  65%|██████▌   | 4737/7269 [01:03<00:30, 82.11it/s]

Gaps (ex-reports):  65%|██████▌   | 4746/7269 [01:04<00:30, 81.87it/s]

Gaps (ex-reports):  65%|██████▌   | 4755/7269 [01:04<00:30, 81.55it/s]

Gaps (ex-reports):  66%|██████▌   | 4764/7269 [01:04<00:38, 65.28it/s]

Gaps (ex-reports):  66%|██████▌   | 4778/7269 [01:04<00:36, 68.32it/s]

Gaps (ex-reports):  66%|██████▌   | 4786/7269 [01:04<00:35, 69.15it/s]

Gaps (ex-reports):  66%|██████▌   | 4794/7269 [01:04<00:36, 67.32it/s]

Gaps (ex-reports):  66%|██████▌   | 4806/7269 [01:04<00:33, 74.26it/s]

Gaps (ex-reports):  66%|██████▌   | 4814/7269 [01:05<00:36, 66.99it/s]

Gaps (ex-reports):  66%|██████▋   | 4824/7269 [01:05<00:32, 74.61it/s]

Gaps (ex-reports):  66%|██████▋   | 4832/7269 [01:05<00:33, 72.08it/s]

Gaps (ex-reports):  67%|██████▋   | 4840/7269 [01:05<00:41, 58.21it/s]

Gaps (ex-reports):  67%|██████▋   | 4853/7269 [01:05<00:33, 72.65it/s]

Gaps (ex-reports):  67%|██████▋   | 4862/7269 [01:05<00:34, 69.75it/s]

Gaps (ex-reports):  67%|██████▋   | 4870/7269 [01:05<00:35, 67.85it/s]

Gaps (ex-reports):  67%|██████▋   | 4882/7269 [01:05<00:31, 75.41it/s]

Gaps (ex-reports):  67%|██████▋   | 4890/7269 [01:06<00:35, 67.05it/s]

Gaps (ex-reports):  67%|██████▋   | 4900/7269 [01:06<00:32, 72.78it/s]

Gaps (ex-reports):  68%|██████▊   | 4912/7269 [01:06<00:28, 82.29it/s]

Gaps (ex-reports):  68%|██████▊   | 4921/7269 [01:06<00:29, 78.88it/s]

Gaps (ex-reports):  68%|██████▊   | 4931/7269 [01:06<00:29, 78.83it/s]

Gaps (ex-reports):  68%|██████▊   | 4941/7269 [01:06<00:32, 70.84it/s]

Gaps (ex-reports):  68%|██████▊   | 4956/7269 [01:06<00:27, 83.96it/s]

Gaps (ex-reports):  68%|██████▊   | 4965/7269 [01:07<00:28, 79.91it/s]

Gaps (ex-reports):  68%|██████▊   | 4974/7269 [01:07<00:32, 69.93it/s]

Gaps (ex-reports):  69%|██████▊   | 4986/7269 [01:07<00:28, 81.01it/s]

Gaps (ex-reports):  69%|██████▊   | 4995/7269 [01:07<00:35, 64.86it/s]

Gaps (ex-reports):  69%|██████▉   | 5005/7269 [01:07<00:32, 70.09it/s]

Gaps (ex-reports):  69%|██████▉   | 5013/7269 [01:07<00:32, 68.83it/s]

Gaps (ex-reports):  69%|██████▉   | 5022/7269 [01:07<00:32, 69.45it/s]

Gaps (ex-reports):  69%|██████▉   | 5030/7269 [01:08<00:33, 67.23it/s]

Gaps (ex-reports):  69%|██████▉   | 5038/7269 [01:08<00:31, 69.84it/s]

Gaps (ex-reports):  69%|██████▉   | 5046/7269 [01:08<00:31, 69.63it/s]

Gaps (ex-reports):  70%|██████▉   | 5057/7269 [01:08<00:28, 77.80it/s]

Gaps (ex-reports):  70%|██████▉   | 5067/7269 [01:08<00:27, 80.76it/s]

Gaps (ex-reports):  70%|██████▉   | 5077/7269 [01:08<00:27, 80.61it/s]

Gaps (ex-reports):  70%|███████   | 5089/7269 [01:08<00:25, 86.87it/s]

Gaps (ex-reports):  70%|███████   | 5098/7269 [01:08<00:28, 77.25it/s]

Gaps (ex-reports):  70%|███████   | 5112/7269 [01:08<00:23, 90.50it/s]

Gaps (ex-reports):  70%|███████   | 5122/7269 [01:09<00:24, 86.87it/s]

Gaps (ex-reports):  71%|███████   | 5131/7269 [01:09<00:25, 85.27it/s]

Gaps (ex-reports):  71%|███████   | 5140/7269 [01:09<00:25, 84.08it/s]

Gaps (ex-reports):  71%|███████   | 5149/7269 [01:09<00:28, 74.10it/s]

Gaps (ex-reports):  71%|███████   | 5160/7269 [01:09<00:26, 80.83it/s]

Gaps (ex-reports):  71%|███████   | 5169/7269 [01:09<00:27, 75.03it/s]

Gaps (ex-reports):  71%|███████   | 5179/7269 [01:09<00:26, 79.06it/s]

Gaps (ex-reports):  71%|███████▏  | 5188/7269 [01:09<00:26, 79.53it/s]

Gaps (ex-reports):  72%|███████▏  | 5198/7269 [01:10<00:24, 83.81it/s]

Gaps (ex-reports):  72%|███████▏  | 5207/7269 [01:10<00:25, 82.08it/s]

Gaps (ex-reports):  72%|███████▏  | 5217/7269 [01:10<00:26, 77.99it/s]

Gaps (ex-reports):  72%|███████▏  | 5225/7269 [01:10<00:26, 76.36it/s]

Gaps (ex-reports):  72%|███████▏  | 5234/7269 [01:10<00:26, 77.25it/s]

Gaps (ex-reports):  72%|███████▏  | 5242/7269 [01:10<00:27, 73.27it/s]

Gaps (ex-reports):  72%|███████▏  | 5251/7269 [01:10<00:27, 72.56it/s]

Gaps (ex-reports):  72%|███████▏  | 5264/7269 [01:10<00:23, 85.27it/s]

Gaps (ex-reports):  73%|███████▎  | 5273/7269 [01:11<00:23, 83.21it/s]

Gaps (ex-reports):  73%|███████▎  | 5282/7269 [01:11<00:23, 83.47it/s]

Gaps (ex-reports):  73%|███████▎  | 5291/7269 [01:11<00:27, 70.67it/s]

Gaps (ex-reports):  73%|███████▎  | 5301/7269 [01:11<00:25, 75.70it/s]

Gaps (ex-reports):  73%|███████▎  | 5309/7269 [01:11<00:29, 66.80it/s]

Gaps (ex-reports):  73%|███████▎  | 5321/7269 [01:11<00:27, 72.05it/s]

Gaps (ex-reports):  73%|███████▎  | 5332/7269 [01:11<00:25, 76.16it/s]

Gaps (ex-reports):  73%|███████▎  | 5340/7269 [01:11<00:25, 75.08it/s]

Gaps (ex-reports):  74%|███████▎  | 5348/7269 [01:12<00:28, 67.31it/s]

Gaps (ex-reports):  74%|███████▎  | 5359/7269 [01:12<00:25, 75.86it/s]

Gaps (ex-reports):  74%|███████▍  | 5368/7269 [01:12<00:24, 77.24it/s]

Gaps (ex-reports):  74%|███████▍  | 5377/7269 [01:12<00:25, 75.31it/s]

Gaps (ex-reports):  74%|███████▍  | 5386/7269 [01:12<00:25, 73.93it/s]

Gaps (ex-reports):  74%|███████▍  | 5396/7269 [01:12<00:24, 77.96it/s]

Gaps (ex-reports):  74%|███████▍  | 5404/7269 [01:12<00:26, 70.99it/s]

Gaps (ex-reports):  74%|███████▍  | 5413/7269 [01:12<00:25, 73.72it/s]

Gaps (ex-reports):  75%|███████▍  | 5422/7269 [01:13<00:24, 75.67it/s]

Gaps (ex-reports):  75%|███████▍  | 5431/7269 [01:13<00:23, 77.27it/s]

Gaps (ex-reports):  75%|███████▍  | 5441/7269 [01:13<00:23, 77.71it/s]

Gaps (ex-reports):  75%|███████▍  | 5449/7269 [01:13<00:23, 76.20it/s]

Gaps (ex-reports):  75%|███████▌  | 5457/7269 [01:13<00:25, 72.13it/s]

Gaps (ex-reports):  75%|███████▌  | 5465/7269 [01:13<00:26, 69.33it/s]

Gaps (ex-reports):  75%|███████▌  | 5474/7269 [01:13<00:27, 64.98it/s]

Gaps (ex-reports):  75%|███████▌  | 5487/7269 [01:13<00:22, 78.84it/s]

Gaps (ex-reports):  76%|███████▌  | 5496/7269 [01:14<00:28, 62.48it/s]

Gaps (ex-reports):  76%|███████▌  | 5505/7269 [01:14<00:29, 60.81it/s]

Gaps (ex-reports):  76%|███████▌  | 5512/7269 [01:14<00:32, 54.06it/s]

Gaps (ex-reports):  76%|███████▌  | 5525/7269 [01:14<00:27, 64.24it/s]

Gaps (ex-reports):  76%|███████▌  | 5532/7269 [01:14<00:27, 63.89it/s]

Gaps (ex-reports):  76%|███████▌  | 5541/7269 [01:14<00:26, 65.79it/s]

Gaps (ex-reports):  76%|███████▋  | 5548/7269 [01:15<00:30, 56.69it/s]

Gaps (ex-reports):  76%|███████▋  | 5560/7269 [01:15<00:24, 69.10it/s]

Gaps (ex-reports):  77%|███████▋  | 5568/7269 [01:15<00:28, 59.05it/s]

Gaps (ex-reports):  77%|███████▋  | 5578/7269 [01:15<00:25, 66.38it/s]

Gaps (ex-reports):  77%|███████▋  | 5586/7269 [01:15<00:28, 59.29it/s]

Gaps (ex-reports):  77%|███████▋  | 5595/7269 [01:15<00:25, 64.54it/s]

Gaps (ex-reports):  77%|███████▋  | 5603/7269 [01:15<00:26, 61.96it/s]

Gaps (ex-reports):  77%|███████▋  | 5614/7269 [01:16<00:24, 68.84it/s]

Gaps (ex-reports):  77%|███████▋  | 5622/7269 [01:16<00:27, 60.17it/s]

Gaps (ex-reports):  78%|███████▊  | 5636/7269 [01:16<00:22, 71.24it/s]

Gaps (ex-reports):  78%|███████▊  | 5644/7269 [01:16<00:26, 60.80it/s]

Gaps (ex-reports):  78%|███████▊  | 5656/7269 [01:16<00:30, 52.59it/s]

Gaps (ex-reports):  78%|███████▊  | 5672/7269 [01:16<00:22, 70.30it/s]

Gaps (ex-reports):  78%|███████▊  | 5681/7269 [01:17<00:23, 66.44it/s]

Gaps (ex-reports):  78%|███████▊  | 5690/7269 [01:17<00:23, 67.41it/s]

Gaps (ex-reports):  78%|███████▊  | 5698/7269 [01:17<00:23, 66.28it/s]

Gaps (ex-reports):  78%|███████▊  | 5706/7269 [01:17<00:23, 67.65it/s]

Gaps (ex-reports):  79%|███████▊  | 5714/7269 [01:17<00:24, 64.04it/s]

Gaps (ex-reports):  79%|███████▊  | 5723/7269 [01:17<00:23, 65.91it/s]

Gaps (ex-reports):  79%|███████▉  | 5730/7269 [01:17<00:24, 62.90it/s]

Gaps (ex-reports):  79%|███████▉  | 5741/7269 [01:17<00:22, 67.34it/s]

Gaps (ex-reports):  79%|███████▉  | 5748/7269 [01:18<00:23, 63.93it/s]

Gaps (ex-reports):  79%|███████▉  | 5758/7269 [01:18<00:21, 70.83it/s]

Gap fetch failed for SLAI: 404 Client Error: Not Found for url: https://api.datum-rd.com/daily/gaps?ticker=SLAI&start_date=2026-05-10&end_date=2026-08-10&format=json_records

Gaps (ex-reports):  79%|███████▉  | 5767/7269 [01:18<00:20, 73.54it/s]

Gaps (ex-reports):  79%|███████▉  | 5775/7269 [01:18<00:20, 73.16it/s]

Gaps (ex-reports):  80%|███████▉  | 5784/7269 [01:18<00:19, 75.37it/s]

Gaps (ex-reports):  80%|███████▉  | 5793/7269 [01:18<00:19, 77.11it/s]

Gaps (ex-reports):  80%|███████▉  | 5805/7269 [01:18<00:16, 86.33it/s]

Gaps (ex-reports):  80%|███████▉  | 5814/7269 [01:18<00:17, 84.71it/s]

Gaps (ex-reports):  80%|████████  | 5824/7269 [01:19<00:17, 82.97it/s]

Gaps (ex-reports):  80%|████████  | 5833/7269 [01:19<00:18, 76.12it/s]

Gaps (ex-reports):  80%|████████  | 5843/7269 [01:19<00:17, 79.96it/s]

Gaps (ex-reports):  81%|████████  | 5852/7269 [01:19<00:19, 74.48it/s]

Gaps (ex-reports):  81%|████████  | 5861/7269 [01:19<00:19, 73.49it/s]

Gaps (ex-reports):  81%|████████  | 5876/7269 [01:19<00:15, 90.40it/s]

Gaps (ex-reports):  81%|████████  | 5886/7269 [01:19<00:15, 86.83it/s]

Gaps (ex-reports):  81%|████████  | 5895/7269 [01:19<00:18, 76.12it/s]

Gaps (ex-reports):  81%|████████  | 5905/7269 [01:20<00:17, 79.68it/s]

Gaps (ex-reports):  81%|████████▏ | 5914/7269 [01:20<00:18, 74.27it/s]

Gaps (ex-reports):  82%|████████▏ | 5927/7269 [01:20<00:15, 85.62it/s]

Gaps (ex-reports):  82%|████████▏ | 5937/7269 [01:20<00:17, 77.84it/s]

Gaps (ex-reports):  82%|████████▏ | 5949/7269 [01:20<00:17, 77.11it/s]

Gaps (ex-reports):  82%|████████▏ | 5964/7269 [01:20<00:14, 91.58it/s]

Gaps (ex-reports):  82%|████████▏ | 5974/7269 [01:20<00:15, 84.79it/s]

Gaps (ex-reports):  82%|████████▏ | 5983/7269 [01:20<00:15, 83.89it/s]

Gaps (ex-reports):  82%|████████▏ | 5992/7269 [01:21<00:15, 81.76it/s]

Gaps (ex-reports):  83%|████████▎ | 6001/7269 [01:21<00:16, 77.67it/s]

Gaps (ex-reports):  83%|████████▎ | 6013/7269 [01:21<00:15, 82.43it/s]

Gaps (ex-reports):  83%|████████▎ | 6022/7269 [01:21<00:16, 76.16it/s]

Gaps (ex-reports):  83%|████████▎ | 6033/7269 [01:21<00:15, 79.42it/s]

Gaps (ex-reports):  83%|████████▎ | 6042/7269 [01:21<00:15, 79.75it/s]

Gaps (ex-reports):  83%|████████▎ | 6051/7269 [01:21<00:16, 73.80it/s]

Gaps (ex-reports):  83%|████████▎ | 6061/7269 [01:22<00:15, 78.37it/s]

Gaps (ex-reports):  84%|████████▎ | 6071/7269 [01:22<00:16, 73.50it/s]

Gaps (ex-reports):  84%|████████▎ | 6084/7269 [01:22<00:14, 84.34it/s]

Gaps (ex-reports):  84%|████████▍ | 6093/7269 [01:22<00:15, 77.49it/s]

Gaps (ex-reports):  84%|████████▍ | 6103/7269 [01:22<00:14, 79.46it/s]

Gaps (ex-reports):  84%|████████▍ | 6113/7269 [01:22<00:14, 80.70it/s]

Gaps (ex-reports):  84%|████████▍ | 6122/7269 [01:22<00:16, 69.72it/s]

Gaps (ex-reports):  84%|████████▍ | 6137/7269 [01:22<00:13, 86.12it/s]

Gaps (ex-reports):  85%|████████▍ | 6147/7269 [01:23<00:14, 75.59it/s]

Gaps (ex-reports):  85%|████████▍ | 6157/7269 [01:23<00:14, 79.12it/s]

Gaps (ex-reports):  85%|████████▍ | 6166/7269 [01:23<00:13, 79.58it/s]

Gaps (ex-reports):  85%|████████▍ | 6175/7269 [01:23<00:14, 76.93it/s]

Gaps (ex-reports):  85%|████████▌ | 6187/7269 [01:23<00:12, 85.44it/s]

Gaps (ex-reports):  85%|████████▌ | 6196/7269 [01:23<00:14, 72.52it/s]

Gaps (ex-reports):  85%|████████▌ | 6207/7269 [01:23<00:14, 75.84it/s]

Gaps (ex-reports):  86%|████████▌ | 6215/7269 [01:24<00:15, 69.83it/s]

Gaps (ex-reports):  86%|████████▌ | 6225/7269 [01:24<00:13, 75.05it/s]

Gaps (ex-reports):  86%|████████▌ | 6233/7269 [01:24<00:14, 70.94it/s]

Gaps (ex-reports):  86%|████████▌ | 6242/7269 [01:24<00:14, 69.04it/s]

Gaps (ex-reports):  86%|████████▌ | 6257/7269 [01:24<00:13, 75.17it/s]

Gaps (ex-reports):  86%|████████▌ | 6265/7269 [01:24<00:13, 73.76it/s]

Gaps (ex-reports):  86%|████████▋ | 6275/7269 [01:24<00:13, 76.14it/s]

Gaps (ex-reports):  87%|████████▋ | 6289/7269 [01:24<00:11, 86.14it/s]

Gaps (ex-reports):  87%|████████▋ | 6298/7269 [01:25<00:12, 78.85it/s]

Gaps (ex-reports):  87%|████████▋ | 6306/7269 [01:25<00:12, 77.15it/s]

Gaps (ex-reports):  87%|████████▋ | 6314/7269 [01:25<00:13, 72.45it/s]

Gaps (ex-reports):  87%|████████▋ | 6324/7269 [01:25<00:12, 77.64it/s]

Gaps (ex-reports):  87%|████████▋ | 6333/7269 [01:25<00:12, 72.84it/s]

Gaps (ex-reports):  87%|████████▋ | 6342/7269 [01:25<00:13, 67.23it/s]

Gaps (ex-reports):  87%|████████▋ | 6357/7269 [01:25<00:10, 84.73it/s]

Gaps (ex-reports):  88%|████████▊ | 6366/7269 [01:26<00:12, 72.71it/s]

Gaps (ex-reports):  88%|████████▊ | 6378/7269 [01:26<00:10, 83.35it/s]

Gaps (ex-reports):  88%|████████▊ | 6387/7269 [01:26<00:11, 75.53it/s]

Gaps (ex-reports):  88%|████████▊ | 6397/7269 [01:26<00:10, 79.38it/s]

Gaps (ex-reports):  88%|████████▊ | 6406/7269 [01:26<00:10, 79.87it/s]

Gaps (ex-reports):  88%|████████▊ | 6415/7269 [01:26<00:11, 77.11it/s]

Gaps (ex-reports):  88%|████████▊ | 6424/7269 [01:26<00:10, 78.33it/s]

Gaps (ex-reports):  89%|████████▊ | 6438/7269 [01:26<00:09, 85.06it/s]

Gaps (ex-reports):  89%|████████▊ | 6447/7269 [01:27<00:11, 72.63it/s]

Gaps (ex-reports):  89%|████████▉ | 6458/7269 [01:27<00:12, 65.28it/s]

Gaps (ex-reports):  89%|████████▉ | 6468/7269 [01:27<00:11, 68.65it/s]

Gaps (ex-reports):  89%|████████▉ | 6476/7269 [01:27<00:15, 51.71it/s]

Gaps (ex-reports):  89%|████████▉ | 6491/7269 [01:27<00:11, 68.76it/s]

Gaps (ex-reports):  89%|████████▉ | 6500/7269 [01:27<00:10, 71.49it/s]

Gaps (ex-reports):  90%|████████▉ | 6509/7269 [01:27<00:10, 73.85it/s]

Gaps (ex-reports):  90%|████████▉ | 6518/7269 [01:28<00:11, 63.92it/s]

Gaps (ex-reports):  90%|████████▉ | 6528/7269 [01:28<00:11, 63.65it/s]

Gaps (ex-reports):  90%|████████▉ | 6535/7269 [01:28<00:11, 63.49it/s]

Gaps (ex-reports):  90%|█████████ | 6544/7269 [01:28<00:11, 65.43it/s]

Gaps (ex-reports):  90%|█████████ | 6551/7269 [01:28<00:11, 62.53it/s]

Gaps (ex-reports):  90%|█████████ | 6561/7269 [01:28<00:10, 66.48it/s]

Gaps (ex-reports):  90%|█████████ | 6568/7269 [01:28<00:10, 66.56it/s]

Gaps (ex-reports):  90%|█████████ | 6578/7269 [01:29<00:09, 73.13it/s]

Gaps (ex-reports):  91%|█████████ | 6586/7269 [01:29<00:10, 64.97it/s]

Gaps (ex-reports):  91%|█████████ | 6595/7269 [01:29<00:11, 56.48it/s]

Gaps (ex-reports):  91%|█████████ | 6610/7269 [01:29<00:09, 68.12it/s]

Gaps (ex-reports):  91%|█████████ | 6618/7269 [01:29<00:10, 64.75it/s]

Gaps (ex-reports):  91%|█████████ | 6627/7269 [01:29<00:09, 68.75it/s]

Gaps (ex-reports):  91%|█████████▏| 6635/7269 [01:30<00:11, 57.12it/s]

Gaps (ex-reports):  91%|█████████▏| 6647/7269 [01:30<00:09, 68.80it/s]

Gaps (ex-reports):  92%|█████████▏| 6655/7269 [01:30<00:10, 61.14it/s]

Gaps (ex-reports):  92%|█████████▏| 6662/7269 [01:30<00:15, 39.91it/s]

Gaps (ex-reports):  92%|█████████▏| 6668/7269 [01:30<00:15, 37.60it/s]

Gaps (ex-reports):  92%|█████████▏| 6680/7269 [01:30<00:11, 49.42it/s]

Gaps (ex-reports):  92%|█████████▏| 6687/7269 [01:31<00:12, 47.96it/s]

Gaps (ex-reports):  92%|█████████▏| 6697/7269 [01:31<00:10, 56.85it/s]

Gaps (ex-reports):  92%|█████████▏| 6704/7269 [01:31<00:10, 51.49it/s]

Gaps (ex-reports):  92%|█████████▏| 6714/7269 [01:31<00:09, 60.32it/s]

Gaps (ex-reports):  92%|█████████▏| 6721/7269 [01:31<00:09, 58.91it/s]

Gaps (ex-reports):  93%|█████████▎| 6732/7269 [01:31<00:07, 68.95it/s]

Gaps (ex-reports):  93%|█████████▎| 6740/7269 [01:31<00:07, 69.72it/s]

Gaps (ex-reports):  93%|█████████▎| 6749/7269 [01:32<00:07, 70.13it/s]

Gaps (ex-reports):  93%|█████████▎| 6759/7269 [01:32<00:06, 75.74it/s]

Gaps (ex-reports):  93%|█████████▎| 6767/7269 [01:32<00:06, 72.43it/s]

Gaps (ex-reports):  93%|█████████▎| 6775/7269 [01:32<00:08, 56.98it/s]

Gaps (ex-reports):  93%|█████████▎| 6784/7269 [01:32<00:07, 60.74it/s]

Gaps (ex-reports):  93%|█████████▎| 6791/7269 [01:32<00:08, 55.93it/s]

Gaps (ex-reports):  94%|█████████▎| 6802/7269 [01:32<00:07, 59.78it/s]

Gaps (ex-reports):  94%|█████████▎| 6809/7269 [01:33<00:07, 60.25it/s]

Gaps (ex-reports):  94%|█████████▍| 6819/7269 [01:33<00:06, 67.92it/s]

Gaps (ex-reports):  94%|█████████▍| 6827/7269 [01:33<00:06, 63.93it/s]

Gaps (ex-reports):  94%|█████████▍| 6837/7269 [01:33<00:06, 71.86it/s]

Gaps (ex-reports):  94%|█████████▍| 6845/7269 [01:33<00:06, 66.47it/s]

Gaps (ex-reports):  94%|█████████▍| 6856/7269 [01:33<00:05, 69.77it/s]

Gaps (ex-reports):  94%|█████████▍| 6865/7269 [01:33<00:05, 73.36it/s]

Gaps (ex-reports):  95%|█████████▍| 6873/7269 [01:33<00:05, 72.47it/s]

Gaps (ex-reports):  95%|█████████▍| 6882/7269 [01:34<00:05, 75.51it/s]

Gaps (ex-reports):  95%|█████████▍| 6892/7269 [01:34<00:04, 81.59it/s]

Gaps (ex-reports):  95%|█████████▍| 6904/7269 [01:34<00:04, 82.66it/s]

Gaps (ex-reports):  95%|█████████▌| 6915/7269 [01:34<00:04, 86.10it/s]

Gaps (ex-reports):  95%|█████████▌| 6924/7269 [01:34<00:04, 81.72it/s]

Gaps (ex-reports):  95%|█████████▌| 6936/7269 [01:34<00:03, 87.98it/s]

Gaps (ex-reports):  96%|█████████▌| 6945/7269 [01:34<00:04, 77.74it/s]

Gaps (ex-reports):  96%|█████████▌| 6954/7269 [01:34<00:04, 70.03it/s]

Gaps (ex-reports):  96%|█████████▌| 6968/7269 [01:35<00:03, 85.45it/s]

Gaps (ex-reports):  96%|█████████▌| 6978/7269 [01:35<00:03, 81.49it/s]

Gaps (ex-reports):  96%|█████████▌| 6987/7269 [01:35<00:03, 77.54it/s]

Gaps (ex-reports):  96%|█████████▌| 6996/7269 [01:35<00:03, 79.62it/s]

Gaps (ex-reports):  96%|█████████▋| 7005/7269 [01:35<00:03, 73.95it/s]

Gaps (ex-reports):  97%|█████████▋| 7017/7269 [01:35<00:02, 85.25it/s]

Gaps (ex-reports):  97%|█████████▋| 7026/7269 [01:35<00:03, 77.23it/s]

Gaps (ex-reports):  97%|█████████▋| 7036/7269 [01:35<00:03, 68.62it/s]

Gaps (ex-reports):  97%|█████████▋| 7052/7269 [01:36<00:02, 74.15it/s]

Gaps (ex-reports):  97%|█████████▋| 7064/7269 [01:36<00:02, 83.38it/s]

Gaps (ex-reports):  97%|█████████▋| 7073/7269 [01:36<00:02, 78.96it/s]

Gaps (ex-reports):  97%|█████████▋| 7084/7269 [01:36<00:02, 82.27it/s]

Gaps (ex-reports):  98%|█████████▊| 7093/7269 [01:36<00:02, 83.37it/s]

Gaps (ex-reports):  98%|█████████▊| 7102/7269 [01:36<00:01, 84.38it/s]

Gaps (ex-reports):  98%|█████████▊| 7112/7269 [01:36<00:01, 87.94it/s]

Gaps (ex-reports):  98%|█████████▊| 7121/7269 [01:36<00:01, 80.16it/s]

Gaps (ex-reports):  98%|█████████▊| 7133/7269 [01:37<00:01, 89.43it/s]

Gaps (ex-reports):  98%|█████████▊| 7143/7269 [01:37<00:01, 81.23it/s]

Gaps (ex-reports):  98%|█████████▊| 7152/7269 [01:37<00:01, 83.03it/s]

Gaps (ex-reports):  99%|█████████▊| 7161/7269 [01:37<00:01, 82.83it/s]

Gaps (ex-reports):  99%|█████████▊| 7170/7269 [01:37<00:01, 79.23it/s]

Gaps (ex-reports):  99%|█████████▉| 7179/7269 [01:37<00:01, 70.86it/s]

Gaps (ex-reports):  99%|█████████▉| 7192/7269 [01:37<00:00, 83.81it/s]

Gaps (ex-reports):  99%|█████████▉| 7201/7269 [01:37<00:00, 84.36it/s]

Gaps (ex-reports):  99%|█████████▉| 7210/7269 [01:38<00:00, 77.50it/s]

Gaps (ex-reports):  99%|█████████▉| 7221/7269 [01:38<00:00, 85.32it/s]

Gaps (ex-reports):  99%|█████████▉| 7230/7269 [01:38<00:00, 80.49it/s]

Gaps (ex-reports): 100%|█████████▉| 7241/7269 [01:38<00:00, 85.70it/s]

Gaps (ex-reports): 100%|█████████▉| 7251/7269 [01:38<00:00, 84.85it/s]

Gaps (ex-reports): 100%|█████████▉| 7260/7269 [01:38<00:00, 70.70it/s]

Gaps (ex-reports): 100%|██████████| 7269/7269 [01:38<00:00, 73.63it/s]

Rows in gaps (without report days): 440917

Tickers with sigma: 7156

  ticker     sigma
0      A  0.826015
1     AA  1.518568
2   AAAU  1.100734
3   AACG  3.108197
4   AADX  1.294539

In [43]:
std_by_ticker

     ticker     sigma
0         A  0.826015
1        AA  1.518568
2      AAAU  1.100734
3      AACG  3.108197
4      AADX  1.294539
...     ...       ...
7151   ZVOL  0.550706
7152   ZVRA  0.718597
7153    ZWS  0.795494
7154   ZYBT  9.080093
7155   ZYME  0.544352

[7156 rows x 2 columns]

In [44]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"] = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet.

    Як і в клітинці 28: нормалізація тікера і пошук у мапі йдуть по унікальних
    значеннях, а не по кожному з мільйонів рядків; per-batch merge не потрібен.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)
    sd = dict(zip(sigma_map["ticker"], sigma_map["sigma"]))

    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}", flush=True)
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["sigma"] = _map_by_ticker(codes, cats, sd, numeric=True)

        cols = [c for c in df.columns if c != "sigma"]
        if insert_before and insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["sigma"] + cols[idx:]]
        else:
            df = df[cols + ["sigma"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [45]:
# std_by_ticker columns: ['ticker', 'sigma']
sigma_out_path = add_sigma_by_ticker_to_parquet(
    base_path=str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    sigma_df=std_by_ticker,
    insert_before=None,
)

# Validation: output parquet must contain sigma matching std_by_ticker
check_df = pd.read_parquet(sigma_out_path, columns=["ticker", "sigma"])
if "sigma" not in check_df.columns:
    raise KeyError("Column 'sigma' is missing in parquet after merge")

file_sigma = (
    check_df.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

exp_sigma = (
    std_by_ticker.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

common = file_sigma.index.intersection(exp_sigma.index)
if len(common) == 0:
    raise ValueError("No common tickers to validate sigma between std_by_ticker and parquet")

diff = (file_sigma.loc[common] - exp_sigma.loc[common]).abs()
max_diff = float(diff.max()) if len(diff) else 0.0
print("sigma_out_path:", sigma_out_path)
print("tickers in std_by_ticker:", len(exp_sigma))
print("tickers checked in parquet:", len(common))
print("max |file_sigma - expected_sigma|:", max_diff)

▶️ START merge sigma → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000  elapsed=16.5s

[batch   10] rows=20,000,000  elapsed=35.9s

[batch   15] rows=30,000,000  elapsed=51.0s

[batch   20] rows=40,000,000  elapsed=66.1s

[batch   25] rows=50,000,000  elapsed=81.2s

[batch   30] rows=60,000,000  elapsed=96.4s

[batch   35] rows=70,000,000  elapsed=111.9s

[batch   40] rows=80,000,000  elapsed=126.9s

[batch   45] rows=90,000,000  elapsed=141.4s

[batch   50] rows=100,000,000  elapsed=156.1s

[batch   55] rows=110,000,000  elapsed=171.0s

[batch   60] rows=120,000,000  elapsed=185.8s

[batch   65] rows=130,000,000  elapsed=200.3s

[batch   70] rows=138,784,988  elapsed=213.9s

✅ DONE rows=138,784,988 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  in 213.9s

sigma_out_path: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
tickers in std_by_ticker: 7156
tickers checked in parquet: 7156
max |file_sigma - expected_sigma|: 4.99992235614144e-07

In [46]:
peek_parquet(str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"), n=21150)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 138,784,988
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma

NaN у 'bench' (у прев'ю): 1205/21150
NaN у 'corr' (у прев'ю): 1205/21150
NaN у 'beta' (у прев'ю): 1205/21150

Перші рядки:

      ticker                   dt           o           h           l           c          v        date    open  prev_close  Stack% bench    corr    beta  Bench%      sigma
0       SHOP  2026-06-30 00:01:00  114.250000  114.250000  114.250000  114.250000       12.0  2026-06-30  113.00      114.21    0.04   IGV  0.6509  0.5575     NaN   1.562547
1       SHOP  2026-06-30 00:09:00  114.300003  114.330002  114.300003  114.330002       26.0  2026-06-30  113.00      114.21    0.08   IGV  0.6509  0.5575     NaN   1.562547
2       SHOP  2026-06-30 00:26:00  114.449997  114.449997  114.430000  114.430000      200.0  2026-06-30  113.00      114.21    0.21   IGV  0.6509  0.5575    0.52   1.562547
3       SHOP  2026-06-30 00:28:00  114.419998  114.419998  114.410004  114.410004       36.0  2026-06-30  113.00      114.21    0.18   IGV  0.6509  0.5575     NaN   1.562547
4       SHOP  2026-06-30 00:29:00  114.400002  114.400002  114.400002  114.400002      100.0  2026-06-30  113.00      114.21    0.17   IGV  0.6509  0.5575     NaN   1.562547
5       SHOP  2026-06-30 00:30:00  114.360001  114.360001  114.349998  114.349998       37.0  2026-06-30  113.00      114.21    0.13   IGV  0.6509  0.5575     NaN   1.562547
6       SHOP  2026-06-30 00:34:00  114.349998  114.349998  114.349998  114.349998        1.0  2026-06-30  113.00      114.21    0.12   IGV  0.6509  0.5575    0.48   1.562547
7       SHOP  2026-06-30 00:47:00  114.360001  114.360001  114.349998  114.349998      100.0  2026-06-30  113.00      114.21    0.13   IGV  0.6509  0.5575     NaN   1.562547
8       SHOP  2026-06-30 00:57:00  114.370003  114.379997  114.370003  114.379997       40.0  2026-06-30  113.00      114.21    0.14   IGV  0.6509  0.5575    0.68   1.562547
9       SHOP  2026-06-30 01:23:00  114.309998  114.309998  114.309998  114.309998        1.0  2026-06-30  113.00      114.21    0.09   IGV  0.6509  0.5575    0.65   1.562547
10      SHOP  2026-06-30 01:32:00  114.209999  114.209999  114.150002  114.150002       23.0  2026-06-30  113.00      114.21   -0.00   IGV  0.6509  0.5575     NaN   1.562547
11      SHOP  2026-06-30 01:38:00  114.139999  114.139999  114.139999  114.139999        5.0  2026-06-30  113.00      114.21   -0.06   IGV  0.6509  0.5575     NaN   1.562547
12      SHOP  2026-06-30 01:42:00  114.199997  114.209999  114.199997  114.209999       70.0  2026-06-30  113.00      114.21   -0.01   IGV  0.6509  0.5575     NaN   1.562547
13      SHOP  2026-06-30 02:12:00  114.279999  114.290001  114.279999  114.290001       97.0  2026-06-30  113.00      114.21    0.06   IGV  0.6509  0.5575    0.60   1.562547
14      SHOP  2026-06-30 02:24:00  114.300003  114.360001  114.300003  114.360001      111.0  2026-06-30  113.00      114.21    0.08   IGV  0.6509  0.5575     NaN   1.562547
15      SHOP  2026-06-30 02:25:00  114.370003  114.370003  114.370003  114.370003       25.0  2026-06-30  113.00      114.21    0.14   IGV  0.6509  0.5575     NaN   1.562547
16      SHOP  2026-06-30 02:26:00  114.309998  114.309998  114.300003  114.300003      144.0  2026-06-30  113.00      114.21    0.09   IGV  0.6509  0.5575     NaN   1.562547
17      SHOP  2026-06-30 02:33:00  114.290001  114.290001  114.290001  114.290001        7.0  2026-06-30  113.00      114.21    0.07   IGV  0.6509  0.5575     NaN   1.562547
18      SHOP  2026-06-30 02:54:00  114.230003  114.230003  114.230003  114.230003        1.0  2026-06-30  113.00      114.21    0.02   IGV  0.6509  0.5575     NaN   1.562547
19      SHOP  2026-06-30 03:22:00  114.199997  114.199997  114.129997  114.129997       13.0  2026-06-30  113.00      114.21   -0.01   IGV  0.6509  0.5575     NaN   1.562547
20      SHOP  2026-06-30 03:23:00  114.180000  114.239998  114.180000  114.239998      100.0  2026-06-30  113.00      114.21   -0.03   IGV  0.6509  0.5575     NaN   1.562547
21      SHOP  2026-06-30 03:25:00  114.239998  114.239998  114.239998  114.239998       28.0  2026-06-30  113.00      114.21    0.03   IGV  0.6509  0.5575    0.48   1.562547
22      SHOP  2026-06-30 03:36:00  114.190002  114.190002  114.190002  114.190002       33.0  2026-06-30  113.00      114.21   -0.02   IGV  0.6509  0.5575     NaN   1.562547
23      SHOP  2026-06-30 03:40:00  114.209999  114.220001  114.209999  114.220001      156.0  2026-06-30  113.00      114.21   -0.00   IGV  0.6509  0.5575    0.48   1.562547
24      SHOP  2026-06-30 03:45:00  114.120003  114.120003  114.050003  114.050003       36.0  2026-06-30  113.00      114.21   -0.08   IGV  0.6509  0.5575     NaN   1.562547
25      SHOP  2026-06-30 03:47:00  114.180000  114.180000  114.180000  114.180000       21.0  2026-06-30  113.00      114.21   -0.03   IGV  0.6509  0.5575     NaN   1.562547
26      SHOP  2026-06-30 03:48:00  114.190002  114.190002  114.190002  114.190002        4.0  2026-06-30  113.00      114.21   -0.02   IGV  0.6509  0.5575    0.42   1.562547
27      SHOP  2026-06-30 03:49:00  114.190002  114.190002  114.080002  114.080002       56.0  2026-06-30  113.00      114.21   -0.02   IGV  0.6509  0.5575    0.42   1.562547
28      SHOP  2026-06-30 03:50:00  114.180000  114.180000  114.180000  114.180000       44.0  2026-06-30  113.00      114.21   -0.03   IGV  0.6509  0.5575     NaN   1.562547
29      SHOP  2026-06-30 03:51:00  114.120003  114.120003  114.110001  114.110001      200.0  2026-06-30  113.00      114.21   -0.08   IGV  0.6509  0.5575     NaN   1.562547
30      SHOP  2026-06-30 03:53:00  114.129997  114.160004  114.129997  114.150002       33.0  2026-06-30  113.00      114.21   -0.07   IGV  0.6509  0.5575    0.41   1.562547
31      SHOP  2026-06-30 03:54:00  114.150002  114.150002  114.150002  114.150002       13.0  2026-06-30  113.00      114.21   -0.05   IGV  0.6509  0.5575    0.41   1.562547
32      SHOP  2026-06-30 03:57:00  114.230003  114.230003  114.230003  114.230003        1.0  2026-06-30  113.00      114.21    0.02   IGV  0.6509  0.5575     NaN   1.562547
33      SHOP  2026-06-30 03:59:00  114.239998  114.290001  114.239998  114.290001      109.0  2026-06-30  113.00      114.21    0.03   IGV  0.6509  0.5575    0.43   1.562547
34      SHOP  2026-06-30 04:00:00  114.199997  114.422897  114.190002  114.250000     1586.0  2026-06-30  113.00      114.21   -0.01   IGV  0.6509  0.5575     NaN   1.562547
35      SHOP  2026-06-30 04:02:00  114.269997  114.269997  114.269997  114.269997      100.0  2026-06-30  113.00      114.21    0.05   IGV  0.6509  0.5575    0.52   1.562547
36      SHOP  2026-06-30 04:03:00  114.209999  114.209999  114.209999  114.209999      200.0  2026-06-30  113.00      114.21   -0.00   IGV  0.6509  0.5575    0.68   1.562547
37      SHOP  2026-06-30 04:04:00  114.120003  114.120003  114.110001  114.110001      200.0  2026-06-30  113.00      114.21   -0.08   IGV  0.6509  0.5575    0.49   1.562547
38      SHOP  2026-06-30 06:19:00  114.010002  114.010002  114.010002  114.010002      200.0  2026-06-30  113.00      114.21   -0.18   IGV  0.6509  0.5575     NaN   1.562547
39      SHOP  2026-06-30 06:45:00  114.500000  114.500000  114.500000  114.500000      100.0  2026-06-30  113.00      114.21    0.25   IGV  0.6509  0.5575     NaN   1.562547
40      SHOP  2026-06-30 06:57:00  113.559998  113.559998  113.559998  113.559998      210.0  2026-06-30  113.00      114.21   -0.57   IGV  0.6509  0.5575     NaN   1.562547
41      SHOP  2026-06-30 07:05:00  114.150002  114.150002  114.150002  114.150002      100.0  2026-06-30  113.00      114.21   -0.05   IGV  0.6509  0.5575     NaN   1.562547
42      SHOP  2026-06-30 07:06:00  114.150002  114.150002  114.110001  114.110001      290.0  2026-06-30  113.00      114.21   -0.05   IGV  0.6509  0.5575    0.26   1.562547
43      SHOP  2026-06-30 07:16:00  114.038200  114.038200  114.010002  114.010002      600.0  2026-06-30  113.00      114.21   -0.15   IGV  0.6509  0.5575    0.11   1.562547
44      SHOP  2026-06-30 07:25:00  114.010002  114.010002  114.010002  114.010002      200.0  2026-06-30  113.00      114.21   -0.18   IGV  0.6509  0.5575     NaN   1.562547
45      SHOP  2026-06-30 07:34:00  113.989998  113.989998  113.989998  113.989998      200.0  2026-06-30  113.00      114.21   -0.19   IGV  0.6509  0.5575     NaN   1.562547
46      SHOP  2026-06-30 07:35:00  113.900002  113.900002  113.900002  113.900002      100.0  2026-06-30  113.00      114.21   -0.27   IGV  0.6509  0.5575    0.08   1.562547
47      SHOP  2026-06-30 07:39:00  113.889999  113.889999  113.889999  113.889999      250.0  2026-06-30  113.00      114.21   -0.28   IGV  0.6509  0.5575     NaN   1.562547
48      SHOP  2026-06-30 07:40:00  113.242500  113.599998  113.242500  113.599998      400.0  2026-06-30  113.00      114.21   -0.85   IGV  0.6509  0.5575     NaN   1.562547
49      SHOP  2026-06-30 08:01:00  113.800003  113.800003  113.800003  113.800003      500.0  2026-06-30  113.00      114.21   -0.36   IGV  0.6509  0.5575   -0.36   1.562547
50      SHOP  2026-06-30 08:08:00  113.550003  113.550003  113.309998  113.550003      825.0  2026-06-30  113.00      114.21   -0.58   IGV  0.6509  0.5575     NaN   1.562547
51      SHOP  2026-06-30 08:22:00  113.309998  113.309998  113.309998  113.309998      372.0  2026-06-30  113.00      114.21   -0.79   IGV  0.6509  0.5575   -0.59   1.562547
52      SHOP  2026-06-30 08:26:00  113.388397  113.388397  113.388397  113.388397      100.0  2026-06-30  113.00      114.21   -0.72   IGV  0.6509  0.5575     NaN   1.562547
53      SHOP  2026-06-30 08:27:00  113.300003  113.300003  113.300003  113.300003      500.0  2026-06-30  113.00      114.21   -0.80   IGV  0.6509  0.5575   -0.66   1.562547
54      SHOP  2026-06-30 08:33:00  113.652496  113.652496  113.652496  113.652496      670.0  2026-06-30  113.00      114.21   -0.49   IGV  0.6509  0.5575     NaN   1.562547
55      SHOP  2026-06-30 08:48:00  113.099998  113.099998  113.099998  113.099998      770.0  2026-06-30  113.00      114.21   -0.97   IGV  0.6509  0.5575   -0.73   1.562547
56      SHOP  2026-06-30 08:51:00  113.070000  113.070000  113.070000  113.070000      100.0  2026-06-30  113.00      114.21   -1.00   IGV  0.6509  0.5575     NaN   1.562547
57      SHOP  2026-06-30 08:54:00  113.083099  113.083099  113.059998  113.059998     1200.0  2026-06-30  113.00      114.21   -0.99   IGV  0.6509  0.5575     NaN   1.562547
58      SHOP  2026-06-30 08:55:00  113.059998  113.059998  113.059998  113.059998      100.0  2026-06-30  113.00      114.21   -1.01   IGV  0.6509  0.5575     NaN   1.562547
59      SHOP  2026-06-30 08:56:00  113.059998  113.199997  112.449997  112.900002     3225.0  2026-06-30  113.00      114.21   -1.01   IGV  0.6509  0.5575     NaN   1.562547
60      SHOP  2026-06-30 08:57:00  113.000000  113.000000  113.000000  113.000000      200.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575     NaN   1.562547
61      SHOP  2026-06-30 08:58:00  113.000000  113.000000  113.000000  113.000000      391.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575     NaN   1.562547
62      SHOP  2026-06-30 09:01:00  113.000000  113.000000  113.000000  113.000000      100.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575     NaN   1.562547
63      SHOP  2026-06-30 09:02:00  113.000000  113.000000  113.000000  113.000000      217.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575   -0.91   1.562547
64      SHOP  2026-06-30 09:11:00  113.010002  113.010002  113.010002  113.010002      100.0  2026-06-30  113.00      114.21   -1.05   IGV  0.6509  0.5575     NaN   1.562547
65      SHOP  2026-06-30 09:21:00  113.010002  113.010002  113.000000  113.000000      200.0  2026-06-30  113.00      114.21   -1.05   IGV  0.6509  0.5575     NaN   1.562547
66      SHOP  2026-06-30 09:24:00  113.297997  113.297997  113.297997  113.297997      100.0  2026-06-30  113.00      114.21   -0.80   IGV  0.6509  0.5575   -0.87   1.562547
67      SHOP  2026-06-30 09:27:00  113.400002  113.400002  112.879997  112.879997      585.0  2026-06-30  113.00      114.21   -0.71   IGV  0.6509  0.5575   -0.99   1.562547
68      SHOP  2026-06-30 09:28:00  112.320000  112.400002  112.139999  112.139999     1121.0  2026-06-30  113.00      114.21   -1.65   IGV  0.6509  0.5575   -1.01   1.562547
69      SHOP  2026-06-30 09:29:00  112.150002  112.330002  112.110001  112.110001      304.0  2026-06-30  113.00      114.21   -1.80   IGV  0.6509  0.5575   -1.11   1.562547
70      SHOP  2026-06-30 09:30:00  113.000000  114.230003  112.000000  114.144997    82876.0  2026-06-30  113.00      114.21   -1.06   IGV  0.6509  0.5575   -0.93   1.562547
71      SHOP  2026-06-30 09:31:00  114.144997  114.360001  113.800003  113.824997    22177.0  2026-06-30  113.00      114.21   -0.06   IGV  0.6509  0.5575   -0.52   1.562547
72      SHOP  2026-06-30 09:32:00  113.980003  114.120003  113.129997  113.758598     9412.0  2026-06-30  113.00      114.21   -0.20   IGV  0.6509  0.5575   -0.38   1.562547
73      SHOP  2026-06-30 09:33:00  114.239998  114.250000  113.739998  113.800003    10035.0  2026-06-30  113.00      114.21    0.03   IGV  0.6509  0.5575   -0.41   1.562547
74      SHOP  2026-06-30 09:34:00  113.919998  114.459999  113.580002  114.370003    12116.0  2026-06-30  113.00      114.21   -0.25   IGV  0.6509  0.5575   -0.24   1.562547
75      SHOP  2026-06-30 09:35:00  114.260002  114.559998  114.080002  114.559998     8013.0  2026-06-30  113.00      114.21    0.04   IGV  0.6509  0.5575   -0.13   1.562547
76      SHOP  2026-06-30 09:36:00  114.309998  114.599998  114.129997  114.260002    15786.0  2026-06-30  113.00      114.21    0.09   IGV  0.6509  0.5575   -0.08   1.562547
77      SHOP  2026-06-30 09:37:00  114.139999  114.180000  113.500000  113.570000    11678.0  2026-06-30  113.00      114.21   -0.06   IGV  0.6509  0.5575   -0.19   1.562547
78      SHOP  2026-06-30 09:38:00  113.570000  114.160004  113.459999  114.040001    35488.0  2026-06-30  113.00      114.21   -0.56   IGV  0.6509  0.5575   -0.46   1.562547
79      SHOP  2026-06-30 09:39:00  114.000000  114.190002  113.480003  113.480003     7814.0  2026-06-30  113.00      114.21   -0.18   IGV  0.6509  0.5575   -0.21   1.562547
80      SHOP  2026-06-30 09:40:00  113.389999  113.610001  113.300003  113.455002     6955.0  2026-06-30  113.00      114.21   -0.72   IGV  0.6509  0.5575   -0.42   1.562547
81      SHOP  2026-06-30 09:41:00  113.570000  114.290001  113.570000  114.099998     5815.0  2026-06-30  113.00      114.21   -0.56   IGV  0.6509  0.5575   -0.33   1.562547
82      SHOP  2026-06-30 09:42:00  114.000000  114.410004  113.889999  114.410004    11943.0  2026-06-30  113.00      114.21   -0.18   IGV  0.6509  0.5575    0.00   1.562547
83      SHOP  2026-06-30 09:43:00  114.290001  114.449997  114.129997  114.285004     9334.0  2026-06-30  113.00      114.21    0.07   IGV  0.6509  0.5575    0.00   1.562547
84      SHOP  2026-06-30 09:44:00  114.279999  114.279999  113.834999  114.010002    12061.0  2026-06-30  113.00      114.21    0.06   IGV  0.6509  0.5575   -0.01   1.562547
85      SHOP  2026-06-30 09:45:00  113.985001  114.300003  113.790001  114.160004    29739.0  2026-06-30  113.00      114.21   -0.20   IGV  0.6509  0.5575   -0.07   1.562547
86      SHOP  2026-06-30 09:46:00  114.150002  114.720001  114.019997  114.570000    13156.0  2026-06-30  113.00      114.21   -0.05   IGV  0.6509  0.5575    0.17   1.562547
87      SHOP  2026-06-30 09:47:00  114.570000  114.570000  113.697197  113.697197    13885.0  2026-06-30  113.00      114.21    0.32   IGV  0.6509  0.5575    0.20   1.562547
88      SHOP  2026-06-30 09:48:00  113.750000  114.150002  113.750000  114.099998     3849.0  2026-06-30  113.00      114.21   -0.40   IGV  0.6509  0.5575   -0.13   1.562547
89      SHOP  2026-06-30 09:49:00  113.964996  114.750000  113.964996  114.750000    17752.0  2026-06-30  113.00      114.21   -0.21   IGV  0.6509  0.5575   -0.16   1.562547
90      SHOP  2026-06-30 09:50:00  114.610001  115.230003  114.610001  115.120003    19234.0  2026-06-30  113.00      114.21    0.35   IGV  0.6509  0.5575    0.00   1.562547
91      SHOP  2026-06-30 09:51:00  115.209999  115.660004  115.209999  115.529999    12292.0  2026-06-30  113.00      114.21    0.88   IGV  0.6509  0.5575    0.12   1.562547
92      SHOP  2026-06-30 09:52:00  115.519997  115.730003  115.234299  115.410004    18801.0  2026-06-30  113.00      114.21    1.15   IGV  0.6509  0.5575    0.34   1.562547
93      SHOP  2026-06-30 09:53:00  115.422501  115.680000  115.417999  115.495003    13048.0  2026-06-30  113.00      114.21    1.06   IGV  0.6509  0.5575    0.47   1.562547
94      SHOP  2026-06-30 09:54:00  115.470001  115.790001  115.300003  115.559998    10308.0  2026-06-30  113.00      114.21    1.10   IGV  0.6509  0.5575    0.44   1.562547
95      SHOP  2026-06-30 09:55:00  115.529999  115.959999  115.529999  115.959999    11921.0  2026-06-30  113.00      114.21    1.16   IGV  0.6509  0.5575    0.27   1.562547
96      SHOP  2026-06-30 09:56:00  115.889999  116.000000  115.410004  115.410004    10045.0  2026-06-30  113.00      114.21    1.47   IGV  0.6509  0.5575    0.50   1.562547
97      SHOP  2026-06-30 09:57:00  115.410004  115.739998  115.330002  115.614998     5010.0  2026-06-30  113.00      114.21    1.05   IGV  0.6509  0.5575    0.39   1.562547
98      SHOP  2026-06-30 09:58:00  115.595001  115.629997  115.160004  115.470001    11902.0  2026-06-30  113.00      114.21    1.21   IGV  0.6509  0.5575    0.45   1.562547
99      SHOP  2026-06-30 09:59:00  115.474998  115.559998  115.320000  115.349998     7430.0  2026-06-30  113.00      114.21    1.11   IGV  0.6509  0.5575    0.43   1.562547
100     SHOP  2026-06-30 10:00:00  115.250000  115.299599  114.769997  114.849998    12014.0  2026-06-30  113.00      114.21    0.91   IGV  0.6509  0.5575    0.34   1.562547
101     SHOP  2026-06-30 10:01:00  114.750000  115.209999  114.639999  115.169998    11181.0  2026-06-30  113.00      114.21    0.47   IGV  0.6509  0.5575    0.16   1.562547
102     SHOP  2026-06-30 10:02:00  115.220001  115.385002  115.129997  115.150002     4351.0  2026-06-30  113.00      114.21    0.88   IGV  0.6509  0.5575    0.34   1.562547
103     SHOP  2026-06-30 10:03:00  115.139999  115.379997  115.120003  115.160004     4517.0  2026-06-30  113.00      114.21    0.81   IGV  0.6509  0.5575    0.51   1.562547
104     SHOP  2026-06-30 10:04:00  115.089996  115.150002  114.955002  115.114998     2623.0  2026-06-30  113.00      114.21    0.77   IGV  0.6509  0.5575    0.43   1.562547
105     SHOP  2026-06-30 10:05:00  115.080002  115.154999  114.950600  115.070099     5666.0  2026-06-30  113.00      114.21    0.76   IGV  0.6509  0.5575    0.42   1.562547
106     SHOP  2026-06-30 10:06:00  115.160004  115.339996  115.139999  115.250000     2294.0  2026-06-30  113.00      114.21    0.83   IGV  0.6509  0.5575    0.34   1.562547
107     SHOP  2026-06-30 10:07:00  115.339996  115.419998  115.129997  115.419998     4497.0  2026-06-30  113.00      114.21    0.99   IGV  0.6509  0.5575    0.34   1.562547
108     SHOP  2026-06-30 10:08:00  115.419998  115.419998  115.000000  115.019997     6186.0  2026-06-30  113.00      114.21    1.06   IGV  0.6509  0.5575    0.43   1.562547
109     SHOP  2026-06-30 10:09:00  115.000000  115.014999  114.720001  114.779999     3861.0  2026-06-30  113.00      114.21    0.69   IGV  0.6509  0.5575    0.30   1.562547
110     SHOP  2026-06-30 10:10:00  114.790001  114.790001  114.489998  114.497101    10898.0  2026-06-30  113.00      114.21    0.51   IGV  0.6509  0.5575    0.22   1.562547
111     SHOP  2026-06-30 10:11:00  114.589996  114.870003  114.589996  114.848000     2597.0  2026-06-30  113.00      114.21    0.33   IGV  0.6509  0.5575    0.19   1.562547
112     SHOP  2026-06-30 10:12:00  114.800003  115.010002  114.800003  114.949997    58063.0  2026-06-30  113.00      114.21    0.52   IGV  0.6509  0.5575    0.37   1.562547

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,SHOP,2026-06-30 00:01:00,114.250000,114.250000,114.250000,114.250000,12.0,2026-06-30,113.00,114.21,0.04,IGV,0.6509,0.5575,NaN,1.562547
1,SHOP,2026-06-30 00:09:00,114.300003,114.330002,114.300003,114.330002,26.0,2026-06-30,113.00,114.21,0.08,IGV,0.6509,0.5575,NaN,1.562547
2,SHOP,2026-06-30 00:26:00,114.449997,114.449997,114.430000,114.430000,200.0,2026-06-30,113.00,114.21,0.21,IGV,0.6509,0.5575,0.52,1.562547
3,SHOP,2026-06-30 00:28:00,114.419998,114.419998,114.410004,114.410004,36.0,2026-06-30,113.00,114.21,0.18,IGV,0.6509,0.5575,NaN,1.562547
4,SHOP,2026-06-30 00:29:00,114.400002,114.400002,114.400002,114.400002,100.0,2026-06-30,113.00,114.21,0.17,IGV,0.6509,0.5575,NaN,1.562547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,SLS,2026-06-30 03:28:00,16.139999,16.139999,16.000000,16.000000,785.0,2026-06-30,15.18,15.46,4.40,XBI,0.4671,0.7024,NaN,1.295190
21146,SLS,2026-06-30 03:29:00,15.930000,15.930000,15.880000,15.890000,381.0,2026-06-30,15.18,15.46,3.04,XBI,0.4671,0.7024,NaN,1.295190
21147,SLS,2026-06-30 03:31:00,15.940000,15.940000,15.880000,15.880000,894.0,2026-06-30,15.18,15.46,3.10,XBI,0.4671,0.7024,-0.04,1.295190
21148,SLS,2026-06-30 03:35:00,16.139999,16.139999,16.139999,16.139999,1.0,2026-06-30,15.18,15.46,4.40,XBI,0.4671,0.7024,NaN,1.295190
21149,SLS,2026-06-30 03:38:00,16.139999,16.139999,16.139999,16.139999,21.0,2026-06-30,15.18,15.46,4.40,XBI,0.4671,0.7024,NaN,1.295190

In [47]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional, List

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
    import pyarrow.compute as pc
except Exception:
    pa = pq = ds = pc = None


def _as_f64(col):
    """ChunkedArray -> float64 без походу в pandas (fallback лише для нечислових типів)."""
    if pa.types.is_floating(col.type) or pa.types.is_integer(col.type):
        return col.cast(pa.float64()) if col.type != pa.float64() else col
    if pa.types.is_decimal(col.type):
        return col.cast(pa.float64())
    return pa.chunked_array([pa.array(
        pd.to_numeric(col.to_pandas(), errors="coerce").to_numpy(dtype="float64"))])


def _round_like_numpy(col, ndigits):
    """np.round над Arrow-колонкою + NaN -> null (як робив pa.Table.from_pandas)."""
    if len(col) == 0:
        return col
    v = col.to_numpy(zero_copy_only=False)   # може бути read-only zero-copy view
    if ndigits is not None:
        v = np.round(v, int(ndigits))
    return pa.array(v, from_pandas=True)


def _add_tp_deviation_devsig(table, *, round_tp_dev=2, round_devsig=6, dt_as_timestamp=False):
    """t_p / deviation / dev_sig як арифметика Arrow над колонками таблиці.

    Раніше кожен батч ходив у pandas і назад (batch.to_pandas() +
    pa.Table.from_pandas()). Для рядкових колонок ticker/dt/date/bench це означало
    матеріалізацію мільйонів python-об'єктів str на кожному батчі й повне
    перезбирання Arrow-масивів — найдорожча частина того циклу. Тут таблиця
    лишається в Arrow від читання до запису.
    """
    names = {n.strip().lower(): n for n in table.column_names}
    stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
    bench_col = names.get("bench%")
    beta_col = names.get("beta")
    sigma_col = names.get("sigma")

    need = {
        "stack%/pct_vs_prev_close": stack_col,
        "bench%": bench_col,
        "beta": beta_col,
        "sigma": sigma_col,
    }
    missing = [k for k, v in need.items() if v is None]
    if missing:
        raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

    drop = [c for c in ("t_p", "deviation", "dev_sig") if c in table.column_names]
    if drop:
        table = table.drop_columns(drop) if hasattr(table, "drop_columns") else table.drop(drop)

    stack = _as_f64(table[stack_col])
    beta = _as_f64(table[beta_col])
    bench = _as_f64(table[bench_col])
    sigma = _as_f64(table[sigma_col])

    tp = pc.multiply(stack, beta)
    dev = pc.subtract(tp, bench)
    denom = pc.if_else(pc.equal(sigma, 0), pa.scalar(None, pa.float64()), sigma)  # sigma 0 -> NaN
    dsg = pc.divide(dev, denom)

    # Округлення саме через np.round, а не pc.round: на значеннях, які вже округлені
    # вище по пайплайну (Stack% до 2 знаків, beta до 4), добуток лягає впритул до
    # межі .005, і pc.round подекуди дає результат на 1 ULP інший за np.round.
    # np.round тут ще й трохи швидший, а pa.array(..., from_pandas=True) відтворює
    # ту саму семантику NaN -> null, що давав старий pa.Table.from_pandas().
    tp = _round_like_numpy(tp, round_tp_dev)
    dev = _round_like_numpy(dev, round_tp_dev)
    dsg = _round_like_numpy(dsg, round_devsig)

    if dt_as_timestamp and "dt" in table.column_names and pa.types.is_string(table["dt"].type):
        i = table.column_names.index("dt")
        table = table.set_column(i, "dt", pc.strptime(table["dt"], format="%Y-%m-%d %H:%M:%S",
                                                      unit="ns", error_is_null=True))

    return (table.append_column("t_p", tp)
                 .append_column("deviation", dev)
                 .append_column("dev_sig", dsg))


def _sort_keys(schema_names):
    keys = [("ticker", "ascending")]
    if "date" in schema_names:
        keys.append(("date", "ascending"))
    if "dt" in schema_names:
        keys.append(("dt", "ascending"))
    return keys


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # batch_rows для потокового режиму / бакетування
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,
    max_rows_in_memory: int = 20_000_000,
    dt_as_timestamp: bool = False,
    row_group_size: int = 2_000_000,
) -> str:
    """
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.

    Якщо sort_final_by_ticker=True, output_path фізично відсортований:
    ticker A→Z, всередині тикера date,dt.

    Що змінилось проти попередньої версії:
      1. Обчислення і сортування — ОДИН прохід. Раніше спершу писався повний
         tmp_unsorted, потім він читався назад і переписувався відсортованим:
         3 читання + 3 записи всього файла. Тепер 1 читання + 1 запис
         (або 2+2, якщо файл не влазить у пам'ять і потрібні бакети).
      2. Уся арифметика в Arrow — без batch.to_pandas()/pa.Table.from_pandas()
         на кожному батчі (це матеріалізувало рядкові колонки як python-об'єкти).
      3. Сортування ПЕРЕД додаванням t_p/deviation/dev_sig — take() переставляє
         на 3 float64-колонки менше.
      4. Бакетування по тикерах — через pc.index_in замість pandas .map по рядках.
      5. row_group_size=2M замість дефолтного 1M: менше row-груп → швидший запис,
         трохи менший файл, і стратегії-споживачі (вони читають
         iter_batches(batch_size=1_000_000)) теж читають його швидше.
    """
    if pq is None or pa is None or ds is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet, pyarrow.dataset).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    total_rows = dataset.count_rows()

    tmp_out = output_path + f".tmp_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    def _finish(rows, mode):
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_out, output_path)
        print(f"✅ DONE ({mode}): {rows:,} rows → {output_path} | "
              f"total_time={time.time()-t0:,.1f}s", flush=True)
        return output_path

    # ---------- 1) без сортування: чистий стрім, один прохід ----------
    if not sort_final_by_ticker:
        print(f"▶ START (stream): {input_path} → {output_path} | "
              f"rows={total_rows:,} batch={chunksize:,}", flush=True)
        writer = None
        written = 0
        try:
            for bi, rb in enumerate(dataset.to_batches(batch_size=chunksize), 1):
                if rb.num_rows == 0:
                    continue
                tbl = _add_tp_deviation_devsig(
                    pa.Table.from_batches([rb]), round_tp_dev=round_tp_dev,
                    round_devsig=round_devsig, dt_as_timestamp=dt_as_timestamp)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl, row_group_size=row_group_size)
                written += tbl.num_rows
                if bi % 5 == 0:
                    print(f"[batch {bi:>4}] rows={written:,}  "
                          f"elapsed={time.time()-t0:,.1f}s", flush=True)
        finally:
            if writer is not None:
                writer.close()
        return _finish(written, "stream")

    keys = _sort_keys(schema_names)
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    # ---------- 2) влазить у пам'ять: читання → сорт → рахунок → запис ----------
    if total_rows <= max_rows_in_memory:
        print(f"▶ START (in-memory sort): {input_path} → {output_path} | "
              f"rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        table = _add_tp_deviation_devsig(
            table, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
            dt_as_timestamp=dt_as_timestamp)
        pq.write_table(table, tmp_out, compression=compression,
                       row_group_size=row_group_size)
        written = table.num_rows
        del table
        gc.collect()
        return _finish(written, "in-memory sort")

    # ---------- 3) не влазить: один прохід у бакети, далі сорт кожного ----------
    n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
    tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
    tickers = sorted(str(t) for t in tickers if t is not None)
    # суміжні діапазони тикерів → порядок бакетів = порядок тикерів
    edges = np.array_split(np.arange(len(tickers)), n_buckets)
    rank_to_bucket = np.zeros(len(tickers), dtype="int32")
    for b, idxs in enumerate(edges):
        rank_to_bucket[idxs] = b
    ticker_set = pa.array(tickers, type=pa.string())
    rank_to_bucket_arr = pa.array(rank_to_bucket)

    print(f"▶ START (bucketed sort): {input_path} → {output_path} | rows={total_rows:,} "
          f"tickers={len(tickers):,} buckets={n_buckets}", flush=True)

    bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
    bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
    try:
        for rb in dataset.to_batches(batch_size=chunksize):
            if rb.num_rows == 0:
                continue
            tbl = pa.Table.from_batches([rb])
            # ранг тикера в відсортованому списку → номер бакета, повністю в Arrow
            ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
            bidx = pc.take(rank_to_bucket_arr, ranks)
            for b in range(n_buckets):
                mask = pc.equal(bidx, b)
                if not pc.any(mask).as_py():
                    continue
                part = tbl.filter(mask)
                if part.num_rows == 0:
                    continue
                if bwriters[b] is None:
                    bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                   compression=compression)
                bwriters[b].write_table(part)
    finally:
        for w in bwriters:
            if w is not None:
                w.close()

    writer = None
    written = 0
    try:
        for b, bp in enumerate(bucket_paths):
            if not os.path.exists(bp):
                continue
            tbl = pq.read_table(bp).sort_by(keys)
            tbl = _add_tp_deviation_devsig(
                tbl, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
                dt_as_timestamp=dt_as_timestamp)
            if writer is None:
                writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
            writer.write_table(tbl, row_group_size=row_group_size)
            written += tbl.num_rows
            del tbl
            gc.collect()
            print(f"  bucket {b+1}/{n_buckets}  written={written:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)
    finally:
        if writer is not None:
            writer.close()
        for bp in bucket_paths:
            if os.path.exists(bp):
                os.remove(bp)

    return _finish(written, "bucketed sort")


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    max_rows_in_memory: int = 20_000_000,
    log_every: int = 200,            # лишено для сумісності виклику
    roundtrip_pandas: bool = True,   # лишено для сумісності виклику
):
    """Лише сортування parquet: ticker A→Z, всередині тикера (date, dt).

    Обчислення t_p/deviation/dev_sig тепер робить сам recompute_tp_deviation_devsig
    у тому ж проході, тож окремо ця функція потрібна лише якщо треба відсортувати
    вже готовий файл.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")
    keys = _sort_keys(schema_names)

    total_rows = dataset.count_rows()
    t0 = time.time()
    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    if total_rows <= max_rows_in_memory:
        print(f"▶ SORT (in-memory): rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        pq.write_table(table, tmp_out, compression=compression)
        written = table.num_rows
        del table
        gc.collect()
    else:
        n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
        tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
        tickers = sorted(str(t) for t in tickers if t is not None)
        rank_to_bucket = np.zeros(len(tickers), dtype="int32")
        for b, idxs in enumerate(np.array_split(np.arange(len(tickers)), n_buckets)):
            rank_to_bucket[idxs] = b
        ticker_set = pa.array(tickers, type=pa.string())
        rank_to_bucket_arr = pa.array(rank_to_bucket)
        print(f"▶ SORT (bucketed): rows={total_rows:,} tickers={len(tickers):,} "
              f"buckets={n_buckets}", flush=True)

        bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
        bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
        try:
            for rb in dataset.to_batches():
                if rb.num_rows == 0:
                    continue
                tbl = pa.Table.from_batches([rb])
                ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
                bidx = pc.take(rank_to_bucket_arr, ranks)
                for b in range(n_buckets):
                    mask = pc.equal(bidx, b)
                    if not pc.any(mask).as_py():
                        continue
                    part = tbl.filter(mask)
                    if part.num_rows == 0:
                        continue
                    if bwriters[b] is None:
                        bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                       compression=compression)
                    bwriters[b].write_table(part)
        finally:
            for w in bwriters:
                if w is not None:
                    w.close()

        writer = None
        written = 0
        try:
            for b, bp in enumerate(bucket_paths):
                if not os.path.exists(bp):
                    continue
                tbl = pq.read_table(bp).sort_by(keys)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl)
                written += tbl.num_rows
                del tbl
                gc.collect()
        finally:
            if writer is not None:
                writer.close()
            for bp in bucket_paths:
                if os.path.exists(bp):
                    os.remove(bp)

    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)
    print(f"✅ SORT DONE: {written:,} rows → {output_path} | time={time.time()-t0:,.1f}s", flush=True)
    return output_path

In [48]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (bucketed sort): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | rows=138,784,988 tickers=7,834 buckets=7

  bucket 1/7  written=19,934,794  elapsed=132.6s

  bucket 2/7  written=39,590,703  elapsed=158.1s

  bucket 3/7  written=58,538,188  elapsed=181.3s

  bucket 4/7  written=77,596,986  elapsed=205.3s

  bucket 5/7  written=98,235,415  elapsed=230.0s

  bucket 6/7  written=119,185,989  elapsed=255.3s

  bucket 7/7  written=138,784,988  elapsed=279.9s

✅ DONE (bucketed sort): 138,784,988 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=281.3s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'