In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2026-06-08 00:00:00
end   = 2026-09-08 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2026-06-08
end_date_str   = 2026-09-08

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

  ticker       value
0      A    53647.16
1     AA  1220442.46
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 13558

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,market_cap',
    'active': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
# market_cap ніде далі не використовується (єдина згадка — у 'fields' вище),
# тому він не має відсіювати тикери: рядок викидаємо лише якщо бракує ticker або lvl3
tickers_df = tickers_df.dropna(subset=["ticker", "lvl3"])

# --- крок 3: додаємо потрібні колонки у df_filtered
TICKERS = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(TICKERS):,} рядків")
TICKERS.head()

Після фільтрації залишилось: 7,223 рядків

  ticker       value                         lvl3  market_cap
0      A    53647.16  Medical Equipment & Devices     41401.0
1     AA  1220442.46              Metals & Mining     13654.0
2   AAAU   373986.86                          NaN         NaN
3   AACG       28.67                     Software        40.0
4   AADX    47768.05          Aerospace & Defense      2135.0

In [7]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [8]:
unique_lvl2 = get_unique_lvl2(TICKERS)
unique_lvl2

🔹 Знайдено 61 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Banks',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Investment Management',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Other Financial Services',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [9]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "IBIT"],
    "Banking": ["XLF", "KRE", "IBIT"],
    "Institutional Financial Svcs": ["XLF", "IBIT"],
    "Insurance": ["XLF"],
    "Specialty Finance": ["XLF", "IBIT"],

    # --- Tech / Internet / Growth ---
    "Software": ["IGV"],
    "IT Services": ["QQQ"],
    "Semiconductors": ["SOXX", "DRAM"],
    "Technology Hardware": ["QQQ", "SOXX"],
    "Internet Media & Services": ["QQQ", "KWEB", "FXI"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "XRT"],
    "Cable & Satellite": ["SPY", "IWM"],
    "Telecommunications": ["QQQ"],
    "Publishing & Broadcasting": ["QQQ"],
    "Entertainment Content": ["QQQ", "ARKK"],
    "Advertising & Marketing": ["QQQ"],

    # --- Industrials ---
    "Aerospace & Defense": ["NASA", "ITA"],
    "Diversified Industrials": ["XLB", "IWM"],
    "Industrial Intermediate Prod": ["XLB", "IWM"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["XLB", "IWM"],
    "Machinery": ["XLB", "IWM"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["XLB", "IWM"],
    "Electrical Equipment": ["QQQ", "XLB"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XOP", "XLE", "UNG"],
    "Oil & Gas Supply Chain": ["XOP", "XLE", "UNG"],
    "Elec & Gas Marketing & Trading": ["XLU", "XLE"],
    "Electric Utilities": ["XLU"],
    "Gas & Water Utilities": ["XLU"],
    "Renewable Energy": ["XLE", "ARKK"],
    "Chemicals": ["XLB", "URA"],
    "Metals & Mining": ["GDX", "FCX", "COPX", "URA", "SLV"],
    "Steel": ["XLB", "GDX"],
    "Construction Materials": ["XLB", "IWM"],
    "Forestry, Paper & Wood Products": ["XLB", "IWM"],

    # --- Health Care ---
    "Biotech & Pharma": ["XBI"],
    "Medical Equipment & Devices": ["XLV"],
    "Health Care Facilities & Svcs": ["XLV", "IWM"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["XLP"],
    "Beverages": ["XLP"],
    "Household Products": ["XLP"],
    "Tobacco & Cannabis": ["XLP"],
    "Retail - Consumer Staples": ["XLP", "XRT"],
    "Wholesale - Consumer Staples": ["XLP"],

    "Retail - Discretionary": ["XRT", "IWM", "SPY"],
    "Wholesale - Discretionary": ["XRT", "IWM"],
    "Consumer Services": ["IWM", "SPY"],
    "Leisure Facilities & Services": ["IWM", "SPY"],
    "Leisure Products": ["XRT", "IWM"],
    "Apparel & Textile Products": ["XRT", "IWM"],
    "Automotive": ["QQQ", "IWM"],
    "Home & Office Products": ["XRT", "IWM"],
    "Home Construction": ["XLB", "IWM"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [10]:
# ------------------------------------------------

In [11]:
import numpy as np
import pandas as pd


def calc_corr_beta_from_joined_gaps(df_pair: pd.DataFrame, x_col: str = "gap_x", y_col: str = "gap_y"):
    """
    Local corr/beta calculation without /calculations/corr_beta API.

    corr = Pearson(x, y)
    beta = cov(x, y) / var(y)
    """
    d = df_pair[[x_col, y_col]].copy()
    d[x_col] = pd.to_numeric(d[x_col], errors="coerce")
    d[y_col] = pd.to_numeric(d[y_col], errors="coerce")
    d = d.dropna()

    n = len(d)
    if n < 2:
        return np.nan, np.nan, n

    var_y = float(d[y_col].var(ddof=1))
    corr = float(d[x_col].corr(d[y_col]))

    if np.isnan(var_y) or var_y == 0:
        return corr, np.nan, n

    cov_xy = float(d[[x_col, y_col]].cov(ddof=1).iloc[0, 1])
    beta = cov_xy / var_y
    return corr, beta, n


def corr_beta_best_match_from_gaps(
    stock_gap_df: pd.DataFrame,
    etf_gap_df: pd.DataFrame,
    x_tickers,
    y_tickers,
    *,
    min_overlap: int = 20,
    output_path: str = None,
):
    """
    Pick best Y per X using local gaps.

    stock_gap_df: ['ticker','date','gap']
    etf_gap_df:   ['ticker','date','gap']
    """
    sx = stock_gap_df.copy()
    sy = etf_gap_df.copy()

    for df in (sx, sy):
        if not {"ticker", "date", "gap"}.issubset(df.columns):
            raise KeyError("Expected columns ['ticker','date','gap'] in gap data")
        df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.strftime("%Y-%m-%d")
        df["gap"] = pd.to_numeric(df["gap"], errors="coerce")

    s_map = {t: g[["date", "gap"]].copy() for t, g in sx.groupby("ticker")}
    e_map = {t: g[["date", "gap"]].copy() for t, g in sy.groupby("ticker")}

    rows_all = []
    rows_best = []

    for x in [str(v).upper() for v in x_tickers]:
        g_x = s_map.get(x)
        if g_x is None or g_x.empty:
            continue

        best = None
        for y in [str(v).upper() for v in y_tickers]:
            g_y = e_map.get(y)
            if g_y is None or g_y.empty:
                continue

            m = g_x.merge(g_y, on="date", how="inner", suffixes=("_x", "_y")).dropna()
            corr, beta, n = calc_corr_beta_from_joined_gaps(m, x_col="gap_x", y_col="gap_y")
            if n < int(min_overlap) or pd.isna(corr):
                continue

            row = {
                "x_ticker": x,
                "y_ticker": y,
                "corr": corr,
                "beta": beta,
                "n_overlap": n,
            }
            rows_all.append(row)
            if best is None or row["corr"] > best["corr"]:
                best = row

        if best is not None:
            rows_best.append({
                "x_ticker": best["x_ticker"],
                "best_y_ticker": best["y_ticker"],
                "best_corr": best["corr"],
                "beta_with_best": best["beta"],
                "n_overlap": best["n_overlap"],
            })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "n_overlap"])

    if output_path:
        df_pairs.to_csv(output_path, index=False)

    return df_all, df_pairs

In [12]:
# Кеш сирого фетчу. /daily/gaps і /reports тягнулись ДВІЧІ за прогін — тут і в
# комірці 42 — тобто ~14 500 зайвих запитів, і саме вони й провокували 429.
# Складаємо результат ДО відкидання викидів: комірка 42 рахує sigma на СИРИХ
# гепах, і підстановка вже обрізаних занизила б її.
CRACEN_FETCH_CACHE = {}


def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
    start_date=None,
    end_date=None,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
    max_workers_net=8,        # 64 потоки без пауз давали суцільні 429
    max_fail_ratio=0.15,      # 4.4% остаточних відмов виміряно як НОРМУ для цього
                              # API навіть з retry; бар упритул до норми валив би
                              # прогін через раз. Ловить справжню відмову, не шум.
):
    import random
    import time
    import numpy as np
    import pandas as pd
    from concurrent.futures import ThreadPoolExecutor

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]
    if start_date is None:
        start_date = globals().get("start_date_str")
    if end_date is None:
        end_date = globals().get("end_date_str")
    if not start_date or not end_date:
        raise ValueError("Provide start_date/end_date or define start_date_str/end_date_str")
    if sector_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{sector_col}' column")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{ticker_col}' column")

    s_date, e_date = str(start_date)[:10], str(end_date)[:10]

    def _pick_col(df, candidates):
        cols_l = {c.lower().strip(): c for c in df.columns}
        return next((cols_l[c.lower()] for c in candidates if c.lower() in cols_l), None)

    _fails = {"gaps": 0, "reports": 0}

    def _request_with_retry(endpoint, params, *, max_retries=6, backoff=0.5):
        """Повторює запит при 429/мережевих збоях з наростаючою паузою.
        Той самий підхід, що в /intraday/v3. Вичерпавши спроби — кидає
        останній виняток, який ловить виклик вище."""
        for attempt in range(max_retries + 1):
            try:
                return DatumApi.data_request(endpoint, params)
            except Exception:
                if attempt == max_retries:
                    raise
                time.sleep(backoff * (2 ** attempt) * (0.9 + 0.2 * random.random()))

    def _fetch_gap(t):
        try:
            dfg = _request_with_retry("/daily/gaps", {
                "ticker": t, "start_date": s_date, "end_date": e_date, "format": "json_records",
            })
            if dfg is None or dfg.empty:
                return None
            dcol = _pick_col(dfg, ["date", "move_date", "dt", "datetime", "day"])
            if dcol is None or "gap" not in dfg.columns:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(dfg[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
                "gap": pd.to_numeric(dfg["gap"], errors="coerce"),
            }).dropna()
            return out if not out.empty else None
        except Exception as ex:
            _fails["gaps"] += 1
            print(f"WARN gaps fail {t}: {ex}")
            return None

    def _fetch_report(t):
        try:
            rep = _request_with_retry("/reports", {
                "ticker": t, "start_move_date": s_date, "end_move_date": e_date,
            })
            if rep is None or rep.empty:
                return None
            dcol = _pick_col(rep, ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"])
            if dcol is None:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(rep[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
            }).dropna().sort_values("date").tail(int(last_n_reports))
            return out if not out.empty else None
        except Exception as ex:
            _fails["reports"] += 1
            print(f"WARN reports fail {t}: {ex}")
            return None

    # ── prepare ──────────────────────────────────────────────────────────────
    df_clean = tickers_df[[ticker_col, sector_col]].drop_duplicates().copy()
    df_clean[ticker_col] = df_clean[ticker_col].astype(str).str.strip().str.upper()
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)

    stocks = sorted(df_clean[ticker_col].dropna().unique())
    etf_candidates = set(fallback_etfs)
    for sec in df_clean[sector_col].unique():
        etf_candidates.update(sector_to_etf.get(sec, fallback_etfs) or fallback_etfs)
    etf_candidates = sorted(str(x).upper() for x in etf_candidates)

    print(f"START gaps: stocks={len(stocks)} etfs={len(etf_candidates)} window={s_date}..{e_date}")

    # ── parallel fetch: all gaps + reports in one pool ────────────────────────
    all_gap_tickers = sorted(set(stocks) | set(etf_candidates))
    with ThreadPoolExecutor(max_workers=min(max_workers_net,
                                            len(all_gap_tickers) + len(stocks))) as ex:
        gap_futs  = {t: ex.submit(_fetch_gap,    t) for t in all_gap_tickers}
        rep_futs  = {t: ex.submit(_fetch_report, t) for t in stocks}

    gap_res = {t: f.result() for t, f in gap_futs.items()}
    rep_res = {t: f.result() for t, f in rep_futs.items()}

    _total = len(gap_futs) + len(rep_futs)
    _failed = _fails["gaps"] + _fails["reports"]
    if _total and _failed / _total > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_failed} з {_total} запитів "
            f"({_failed / _total * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Далі вийшла б порожня або обрізана мапа bench/corr/beta."
        )

    def _concat(parts, cols):
        valid = [p for p in parts if p is not None]
        return pd.concat(valid, ignore_index=True) if valid else pd.DataFrame(columns=cols)

    stock_gaps = _concat([gap_res.get(t) for t in stocks],         ["ticker", "date", "gap"])
    etf_gaps   = _concat([gap_res.get(t) for t in etf_candidates], ["ticker", "date", "gap"])
    reports    = _concat([rep_res.get(t) for t in stocks],          ["ticker", "date"]).drop_duplicates()

    CRACEN_FETCH_CACHE.clear()
    CRACEN_FETCH_CACHE.update({
        "window": (s_date, e_date),
        "last_n_reports": int(last_n_reports),
        "tickers": set(stocks),
        "gaps": stock_gaps.copy(),      # сирі, до drop anomalies нижче
        "reports": reports.copy(),
    })

    # ── exclude report days ──────────────────────────────────────────────────
    if not reports.empty and not stock_gaps.empty:
        m = stock_gaps.merge(reports.assign(_rep=1), on=["ticker", "date"], how="left")
        stock_gaps = m[m["_rep"].isna()][["ticker", "date", "gap"]].copy()

    # ── drop anomalies (vectorised) ──────────────────────────────────────────
    if not stock_gaps.empty:
        stock_gaps["gap"] = pd.to_numeric(stock_gaps["gap"], errors="coerce")
        abs_gap = stock_gaps["gap"].abs()
        cnts = stock_gaps.groupby("ticker")["gap"].transform("count")
        eligible = cnts >= min_hist_for_cap
        if eligible.any():
            caps = (stock_gaps[eligible]
                    .groupby("ticker")["gap"]
                    .agg(lambda x: np.quantile(x.abs(), cap_q)))
            cap_mapped = stock_gaps["ticker"].map(caps)
            stock_gaps = stock_gaps[(~eligible) | (abs_gap <= cap_mapped)].reset_index(drop=True)

    # ── build ETF numpy matrix: rows=dates, cols=etfs ───────────────────────
    if not etf_gaps.empty:
        etf_pivot = etf_gaps.pivot_table(index="date", columns="ticker", values="gap", aggfunc="first")
        date_to_row = {d: i for i, d in enumerate(etf_pivot.index)}
        etf_to_col  = {c: i for i, c in enumerate(etf_pivot.columns)}
        etf_arr     = etf_pivot.to_numpy(dtype=float)
    else:
        date_to_row = {}; etf_to_col = {}; etf_arr = np.empty((0, 0))

    stock_map = (
        {t: g.set_index("date")["gap"] for t, g in stock_gaps.groupby("ticker")}
        if not stock_gaps.empty else {}
    )

    # ── corr/beta loop ───────────────────────────────────────────────────────
    rows_all = []
    rows_best = []
    sectors_with_fallback = []

    for sec in sorted(df_clean[sector_col].unique()):
        etfs_raw = sector_to_etf.get(sec)
        if not etfs_raw:
            etfs_raw = list(fallback_etfs)
            sectors_with_fallback.append(sec)
        etfs = [str(e).upper() for e in etfs_raw]
        etfs_ok  = [e for e in etfs if e in etf_to_col]
        col_idxs = [etf_to_col[e] for e in etfs_ok]
        if not col_idxs:
            continue

        for st in sorted(df_clean.loc[df_clean[sector_col] == sec, ticker_col].unique()):
            sx = stock_map.get(st)
            if sx is None or sx.empty:
                continue

            st_dates = [d for d in sx.index if d in date_to_row]
            if not st_dates:
                continue

            row_idxs = [date_to_row[d] for d in st_dates]
            x_vals   = sx[st_dates].to_numpy(dtype=float)
            y_mat    = etf_arr[np.ix_(row_idxs, col_idxs)]   # (n_dates, n_etfs)
            valid_x  = ~np.isnan(x_vals)

            best_corr = -np.inf
            best_etf  = None
            best_beta = np.nan
            best_n    = 0

            for j, etf in enumerate(etfs_ok):
                mask = valid_x & ~np.isnan(y_mat[:, j])
                n = int(mask.sum())
                if n < min_overlap:
                    continue

                xv = x_vals[mask];  yv = y_mat[mask, j]
                xc = xv - xv.mean(); yc = yv - yv.mean()
                var_y = float((yc * yc).sum() / (n - 1))
                if var_y == 0 or np.isnan(var_y):
                    continue
                cov_xy = float((xc * yc).sum() / (n - 1))
                std_x  = float(np.sqrt((xc * xc).sum() / (n - 1)))
                if std_x == 0:
                    continue
                corr = cov_xy / (std_x * np.sqrt(var_y))
                beta = cov_xy / var_y

                rows_all.append({"x_ticker": st, "y_ticker": etf, "corr": corr, "beta": beta, "lvl3": sec, "n_overlap": n})

                if corr > best_corr:
                    best_corr, best_etf, best_beta, best_n = corr, etf, beta, n

            if best_etf is not None:
                rows_best.append({"x_ticker": st, "best_y_ticker": best_etf, "best_corr": best_corr,
                                  "beta_with_best": best_beta, "lvl3": sec, "n_overlap": best_n})

    # ── output ───────────────────────────────────────────────────────────────
    df_all   = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best) if rows_best else pd.DataFrame(
        columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "lvl3", "n_overlap"])

    df_pairs.to_csv(output_path, index=False)
    df_bench = df_pairs.rename(columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"})[["ticker", "benchmark"]]
    df_bench.to_csv(bench_path, index=False)

    print(f"DONE pairs: {len(df_pairs)} -> {output_path}")
    print(f"DONE bench map: {len(df_bench)} -> {bench_path}")
    if sectors_with_fallback:
        print("Fallback ETF used for sectors:", ", ".join(map(str, sectors_with_fallback[:20])))

    return df_all, df_pairs

In [13]:
# Local corr/beta: stock gaps vs ETF gaps, excluding report days and stock outliers
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=TICKERS,
    sector_to_etf=sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path=str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path=str(WORK_DIR / "ticker_bench_.csv"),
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
)

# Prepare parquet for downstream merge (cell 31)
corr_beta_pairs = df_pairs.rename(columns={
    "best_y_ticker": "y_ticker",
    "best_corr": "corr",
    "beta_with_best": "beta",
})[["x_ticker", "y_ticker", "corr", "beta"]].copy()

corr_beta_pairs.to_parquet(str(WORK_DIR / "corr_beta_pairs.parquet"), index=False)

print(df_all.head())
print("Rows in raw stock-etf pairs:", len(df_all))
print(df_pairs.head())
print("Saved:", str(WORK_DIR / "corr_beta_pairs.parquet"))

START gaps: stocks=7223 etfs=28 window=2026-06-08..2026-09-08

WARN gaps fail IYZ: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/daily/gaps?ticker=IYZ&start_date=2026-06-08&end_date=2026-09-08&format=json_records

WARN gaps fail JAGU: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/daily/gaps?ticker=JAGU&start_date=2026-06-08&end_date=2026-09-08&format=json_records
WARN gaps fail IZEA: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/daily/gaps?ticker=IZEA&start_date=2026-06-08&end_date=2026-09-08&format=json_records

WARN gaps fail JAB: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/daily/gaps?ticker=JAB&start_date=2026-06-08&end_date=2026-09-08&format=json_records
WARN gaps fail J: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/daily/gaps?ticker=J&start_date=2026-06-08&end_date=2026-09-08&format=json_records

WARN gaps fail JAAA: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/daily/gaps?ticker=JAAA&start_date=2026-06-08&end_date=2026-09-08&format=json_records

WARN gaps fail IZM: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/daily/gaps?ticker=IZM&start_date=2026-06-08&end_date=2026-09-08&format=json_records

WARN gaps fail JACK: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/daily/gaps?ticker=JACK&start_date=2026-06-08&end_date=2026-09-08&format=json_records

WARN gaps fail SLAI: 404 Client Error: Not Found for url: https://api.datum-rd.com/daily/gaps?ticker=SLAI&start_date=2026-06-08&end_date=2026-09-08&format=json_records

WARN gaps fail ZYME: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/daily/gaps?ticker=ZYME&start_date=2026-06-08&end_date=2026-09-08&format=json_records

WARN reports fail AALG: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=AALG&start_move_date=2026-06-08&end_move_date=2026-09-08
WARN reports fail AAME: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=AAME&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail AACG: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=AACG&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail AADX: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=AADX&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail AAAU: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=AAAU&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail AA: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=AA&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail AAL: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=AAL&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail FUTU: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=FUTU&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail FULT: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=FULT&start_move_date=2026-06-08&end_move_date=2026-09-08
WARN reports fail FUNC: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=FUNC&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail FUTG: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=FUTG&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail FURY: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=FURY&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail FULC: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=FULC&start_move_date=2026-06-08&end_move_date=2026-09-08
WARN reports fail FUSE: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=FUSE&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail FUN: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=FUN&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail PRTA: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=PRTA&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail PRT: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=PRT&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail PRPL: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=PRPL&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail PRTS: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=PRTS&start_move_date=2026-06-08&end_move_date=2026-09-08

WARN reports fail PRTH: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=PRTH&start_move_date=2026-06-08&end_move_date=2026-09-08
WARN reports fail PRQR: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=PRQR&start_move_date=2026-06-08&end_move_date=2026-09-08
WARN reports fail PRSO: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=PRSO&start_move_date=2026-06-08&end_move_date=2026-09-08
WARN reports fail PRU: 429 Client Error: Too Many Requests for url: https://api.datum-rd.com/reports?ticker=PRU&start_move_date=2026-06-08&end_move_date=2026-09-08

DONE pairs: 7071 -> C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
DONE bench map: 7071 -> C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv
Fallback ETF used for sectors: Diversified Banks, Investment Management, Other Financial Services, UNKNOWN
  x_ticker y_ticker      corr      beta                     lvl3  n_overlap
0      ADV      QQQ  0.252488  0.180959  Advertising & Marketing         51
1     AEHL      QQQ  0.072073  0.193188  Advertising & Marketing         50
2      APP      QQQ  0.036564  0.037576  Advertising & Marketing         50
3     BAOS      QQQ -0.013483 -0.028122  Advertising & Marketing         51
4     CDLX      QQQ  0.270892  0.208207  Advertising & Marketing         50
Rows in raw stock-etf pairs: 15792
  x_ticker best_y_ticker  best_corr  beta_with_best                     lvl3  \
0      ADV           QQQ   0.252488        0.180959  Advertising & Marketing
1     AEHL           QQQ   0.072073        0.193188  Advertising & Marketing
2      APP           QQQ   0.036564        0.037576  Advertising & Marketing
3     BAOS           QQQ  -0.013483       -0.028122  Advertising & Marketing
4     CDLX           QQQ   0.270892        0.208207  Advertising & Marketing

   n_overlap
0         51
1         50
2         50
3         51
4         50
Saved: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [14]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [15]:
TICKERS

     ticker       value                         lvl3  market_cap
0         A    53647.16  Medical Equipment & Devices     41401.0
1        AA  1220442.46              Metals & Mining     13654.0
2      AAAU   373986.86                          NaN         NaN
3      AACG       28.67                     Software        40.0
4      AADX    47768.05          Aerospace & Defense      2135.0
...     ...         ...                          ...         ...
7218   ZVOL     3135.45                          NaN         NaN
7219   ZVRA    13057.78             Biotech & Pharma       752.0
7220    ZWS     2475.13                    Machinery      7850.0
7221   ZYBT     4032.53             Biotech & Pharma        46.0
7222   ZYME    94292.09             Biotech & Pharma      2010.0

[7223 rows x 4 columns]

In [16]:
import pandas as pd

# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]


# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

   ticker
0    ARKK
1    COPX
2    DRAM
3     FCX
4     FXI
5     GDX
6    IBIT
7     IGV
8     ITA
9     IWM
10    KRE
11   KWEB
12   NASA
13    QQQ
14    SLV
15   SOXX
16    SPY
17    UNG
18    URA
19    XBI
20    XLB
21    XLE
22    XLF
23    XLP
24    XLU
25    XLV
26    XOP
27    XRT

In [17]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=TICKERS,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=16,
    parallel_tickers=True,
    max_workers_tickers=16,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 53 тікерів (пропущено 0 по старому маніфесту) | 2026-06-08 00:00:00 → 2026-09-08 23:59:59 | interval=1 | next batch #15692 | run=2982fc2b

   workers: tickers=16, chunks=16 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 7170

   📉 пропущені дні (в межах window): 2026-06-08 → 2026-09-08 (93 днів)

   📈 обробляються дні: –

   psutil · старт · 🧠 RAM: 321.5 MB

[10/53] – EEMV: empty |  18.87% | ETA 00:07

[20/53] – GSST: empty |  37.74% | ETA 00:04

[30/53] – MRNO: empty |  56.60% | ETA 00:03

[40/53] – NCDL: empty |  75.47% | ETA 00:01

[50/53] – VMET: empty |  94.34% | ETA 00:00

   • RAM · 🧠 RAM: 354.7 MB

   ⏳ перед flush · 🧠 RAM: 354.7 MB

💾 batch 15692 → 15,706 рядків (всього 15,706 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_15692.csv.gz

   ✅ після flush · 🧠 RAM: 354.4 MB

[53/53] – XTND: empty | 100.00% | ETA 00:00

   🔚 фінал · 🧠 RAM: 354.1 MB

🏁 Готово. Нових рядків: 15,706 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 00:06

In [18]:
# ================== FAST LOCAL POST-PROCESSING (no API calls) ==================
# Читання батчів робить pyarrow (нативний багатопотоковий CSV-парсер) замість
# pandas.read_csv, а premarket-фільтр і денні open/close рахуються за ОДИН прохід
# по gz-файлах замість двох.
import os, gc, glob, time, threading
from typing import Optional, List, Tuple

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.csv as pacsv
import pyarrow.compute as pc
import pyarrow.dataset as pads
from concurrent.futures import ThreadPoolExecutor

_INTRADAY_COLS = ["ticker", "dt", "o", "h", "l", "c", "v"]

# Парсимо у float64, щоб денні open/close збігалися з попередньою (pandas) реалізацією
# біт у біт; premarket-рядки перед записом кастимо назад у float32 — стара схема на диску.
_INTRADAY_TYPES = {
    "ticker": pa.string(), "dt": pa.string(),
    "o": pa.float64(), "h": pa.float64(), "l": pa.float64(),
    "c": pa.float64(), "v": pa.float64(),
}
_PREMARKET_SCHEMA = pa.schema([
    ("ticker", pa.string()), ("dt", pa.string()),
    ("o", pa.float32()), ("h", pa.float32()), ("l", pa.float32()),
    ("c", pa.float32()), ("v", pa.float32()),
])


# ---------- спільні хелпери для мерджів по тікеру (використовують клітинки 28/40/44) ----------
def _ticker_codes(s: pd.Series):
    """Факторизує колонку тікерів і нормалізує (strip+upper) ЛИШЕ унікальні значення.

    Повертає (codes, categories); codes[i] == -1 означає null. Сенс у тому, щоб
    strip/upper і словниковий пошук виконувались над ~10^3 унікальними тікерами,
    а не над ~10^6 рядками батча.
    """
    cat = s.astype("category")
    cats = pd.Index(cat.cat.categories.astype(str)).str.strip().str.upper()
    return cat.cat.codes.to_numpy(), cats


def _expand(values: np.ndarray, codes: np.ndarray, fill):
    """Розгортає масив «на категорію» назад «на рядок»; де codes == -1 ставить fill."""
    out = np.empty(codes.shape, dtype=values.dtype if values.dtype != object else object)
    valid = codes >= 0
    out[valid] = values[codes[valid]]
    if (~valid).any():
        out[~valid] = fill
    return out


def _map_by_ticker(codes: np.ndarray, cats: pd.Index, mapping: dict, numeric: bool):
    vals = cats.map(mapping)
    if numeric:
        vals = pd.to_numeric(pd.Series(vals), errors="coerce").to_numpy(dtype="float64")
        return _expand(vals, codes, np.nan)
    vals = np.asarray(pd.Series(vals).astype(object).to_numpy(), dtype=object)
    return _expand(vals, codes, None)


# ---------- читання intraday-батчів ----------
def _open_intraday_csv(path: str, block_size: int):
    return pacsv.open_csv(
        path,
        read_options=pacsv.ReadOptions(use_threads=True, block_size=block_size),
        convert_options=pacsv.ConvertOptions(
            include_columns=_INTRADAY_COLS, column_types=_INTRADAY_TYPES
        ),
    )


def _time_date_mask(dt_arr, start_time, end_time, date_min, date_max):
    t = pc.utf8_slice_codeunits(dt_arr, 11, 19)
    mask = pc.and_(pc.greater_equal(t, start_time), pc.less_equal(t, end_time))
    if date_min is not None or date_max is not None:
        d = pc.utf8_slice_codeunits(dt_arr, 0, 10)
        if date_min is not None:
            mask = pc.and_(mask, pc.greater_equal(d, date_min))
        if date_max is not None:
            mask = pc.and_(mask, pc.less_equal(d, date_max))
    return mask


def _oc_from_table(tbl: pa.Table) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Перший open у вікні 09:30–09:35 і останній close у 15:55–15:59 на (ticker, date)."""
    OPEN_FROM, OPEN_TO = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    hhmm = pc.utf8_slice_codeunits(tbl.column("dt"), 11, 16)
    m_o = pc.and_(pc.and_(pc.greater_equal(hhmm, OPEN_FROM), pc.less_equal(hhmm, OPEN_TO)),
                  pc.is_valid(tbl.column("o")))
    m_c = pc.and_(pc.and_(pc.greater_equal(hhmm, CLOSE_FROM), pc.less_equal(hhmm, CLOSE_TO)),
                  pc.is_valid(tbl.column("c")))

    def _reduce(mask, val_col, keep):
        sub = tbl.select(["ticker", "dt", val_col]).filter(mask)
        if sub.num_rows == 0:
            return pd.DataFrame(columns=["ticker", "date", "dt", val_col])
        d = sub.to_pandas()
        d["date"] = d["dt"].str.slice(0, 10)
        d = d.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep=keep)
        return d[["ticker", "date", "dt", val_col]]

    return _reduce(m_o, "o", "first"), _reduce(m_c, "c", "last")


def _finalize_oc(open_parts: List[pd.DataFrame], close_parts: List[pd.DataFrame]) -> pd.DataFrame:
    opens = (pd.concat(open_parts, ignore_index=True) if open_parts
             else pd.DataFrame(columns=["ticker", "date", "dt", "o"]))
    closes = (pd.concat(close_parts, ignore_index=True) if close_parts
              else pd.DataFrame(columns=["ticker", "date", "dt", "c"]))
    if len(opens):
        opens = opens.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="first")
    if len(closes):
        closes = closes.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="last")
    opens = opens[["ticker", "date", "o"]].rename(columns={"o": "open"})
    closes = closes[["ticker", "date", "c"]].rename(columns={"c": "close"})

    out = (opens.merge(closes, on=["ticker", "date"], how="outer")
                .sort_values(["ticker", "date"], kind="stable").reset_index(drop=True))
    out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)
    return out


def collect_premarket_and_oc(
    folder: str,
    out_path: str,
    oc_out_path: Optional[str] = None,
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    build_oc: bool = True,
    max_workers: int = 4,
    block_size: int = 64 << 20,
    compression: str = "snappy",
    sort_chunk: bool = True,
    verbose: bool = True,
):
    """ОДИН прохід по {folder}/{pattern}: пише відфільтровані рядки у out_path і
    (опційно) денні open/close у oc_out_path.

    Замінює пару collect_premarket_by_day_stream + build_oc_from_intraday_folder,
    які раніше читали й розтискали ті самі gz-файли двічі.

    Порядок рядків МІЖ файлами недетермінований (файли читаються паралельно).
    Це безпечно: усі наступні кроки — мерджі по ключах, а фінальний файл
    фізично сортується у клітинці 47. Для точного старого порядку — max_workers=1.
    """
    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    if os.path.exists(out_path):
        os.remove(out_path)

    t0 = time.time()
    lock = threading.Lock()
    state = {"writer": None, "in": 0, "out": 0, "files": 0}
    open_parts: List[pd.DataFrame] = []
    close_parts: List[pd.DataFrame] = []

    def _handle(path: str):
        reader = _open_intraday_csv(path, block_size)
        loc_open, loc_close = [], []
        n_in = n_out = 0
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            tbl = pa.Table.from_batches([rb])
            n_in += tbl.num_rows

            if build_oc:
                o_df, c_df = _oc_from_table(tbl)
                if len(o_df):
                    loc_open.append(o_df)
                if len(c_df):
                    loc_close.append(c_df)

            cut = tbl.filter(_time_date_mask(tbl.column("dt"), start_time, end_time,
                                             date_min, date_max))
            if cut.num_rows:
                cut = cut.cast(_PREMARKET_SCHEMA)
                if sort_chunk:
                    cut = cut.sort_by([("ticker", "ascending"), ("dt", "ascending")])
                n_out += cut.num_rows
                with lock:
                    if state["writer"] is None:
                        state["writer"] = pq.ParquetWriter(out_path, cut.schema,
                                                           compression=compression)
                    state["writer"].write_table(cut)

        with lock:
            state["in"] += n_in
            state["out"] += n_out
            state["files"] += 1
            open_parts.extend(loc_open)
            close_parts.extend(loc_close)
            if verbose:
                print(f"  [{state['files']}/{len(files)}] {os.path.basename(path)}  "
                      f"in={state['in']:,} out={state['out']:,} "
                      f"elapsed={time.time()-t0:,.1f}s", flush=True)

    rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]" if (date_min or date_max) else ""
    if verbose:
        print(f"▶️ START: {folder}/{pattern} → {out_path}  files={len(files)} "
              f"workers={max_workers}{rng_str}", flush=True)
    try:
        if max_workers and max_workers > 1:
            with ThreadPoolExecutor(max_workers=max_workers) as ex:
                list(ex.map(_handle, files))
        else:
            for p in files:
                _handle(p)
    finally:
        if state["writer"] is not None:
            state["writer"].close()

    df_oc = None
    if build_oc:
        df_oc = _finalize_oc(open_parts, close_parts)
        if oc_out_path:
            os.makedirs(os.path.dirname(oc_out_path) or ".", exist_ok=True)
            df_oc.to_parquet(oc_out_path, index=False)

    if verbose:
        print(f"✅ DONE  in={state['in']:,} → out={state['out']:,}  to {out_path}  "
              f"in {time.time()-t0:,.1f}s", flush=True)
    return out_path, df_oc


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,
    date_max: Optional[str] = None,
    aggregate: bool = False,
    chunksize: int = 200_000,          # лишено для сумісності виклику; pyarrow керує блоками сам
    compression: str = "snappy",
    log_every: int = 5,                # лишено для сумісності виклику
    sort_chunk: bool = True,
    max_workers: int = 4,
    verbose: bool = True,
):
    """Тонка обгортка над collect_premarket_and_oc (build_oc=False) — щоб старі
    виклики працювали без змін."""
    if aggregate:
        raise NotImplementedError("aggregate=True у цьому пайплайні не використовується")
    path, _ = collect_premarket_and_oc(
        folder, out_path, oc_out_path=None, pattern=pattern,
        start_time=start_time, end_time=end_time,
        date_min=date_min, date_max=date_max, build_oc=False,
        max_workers=max_workers, compression=compression,
        sort_chunk=sort_chunk, verbose=verbose,
    )
    return path

In [19]:
# Один прохід по gz-батчах: одразу і premarket-рядки, і денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,
    date_max=end_date_str,
    build_oc=True,
    max_workers=4,
)
print(df_oc.head())

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  files=15692 workers=4  date=[2026-06-08..2026-09-08]

  [1/15692] intraday_0003.csv.gz  in=727,885 out=0 elapsed=0.5s

  [2/15692] intraday_0004.csv.gz  in=1,470,913 out=0 elapsed=0.6s

  [3/15692] intraday_0002.csv.gz  in=2,357,625 out=0 elapsed=0.6s

  [4/15692] intraday_0001.csv.gz  in=3,333,452 out=0 elapsed=0.7s

  [5/15692] intraday_0005.csv.gz  in=4,207,443 out=0 elapsed=1.2s

  [6/15692] intraday_0007.csv.gz  in=4,968,024 out=0 elapsed=1.2s

  [7/15692] intraday_0006.csv.gz  in=5,923,107 out=0 elapsed=1.2s

  [8/15692] intraday_0008.csv.gz  in=6,732,671 out=0 elapsed=1.3s

  [9/15692] intraday_0011.csv.gz  in=7,471,310 out=0 elapsed=1.8s

  [10/15692] intraday_0009.csv.gz  in=8,411,136 out=0 elapsed=1.8s

  [11/15692] intraday_0012.csv.gz  in=9,264,822 out=0 elapsed=1.8s

  [12/15692] intraday_0010.csv.gz  in=10,202,410 out=0 elapsed=1.9s

  [13/15692] intraday_0015.csv.gz  in=10,806,484 out=0 elapsed=2.3s

  [14/15692] intraday_0014.csv.gz  in=11,471,803 out=0 elapsed=2.3s

  [15/15692] intraday_0013.csv.gz  in=12,333,647 out=0 elapsed=2.4s

  [16/15692] intraday_0018.csv.gz  in=13,022,745 out=0 elapsed=2.8s

  [17/15692] intraday_0016.csv.gz  in=14,058,532 out=0 elapsed=2.9s

  [18/15692] intraday_0019.csv.gz  in=14,795,001 out=0 elapsed=2.9s

  [19/15692] intraday_0017.csv.gz  in=15,723,943 out=0 elapsed=3.0s

  [20/15692] intraday_0020.csv.gz  in=16,555,781 out=0 elapsed=3.4s

  [21/15692] intraday_0022.csv.gz  in=17,287,747 out=0 elapsed=3.4s

  [22/15692] intraday_0021.csv.gz  in=18,114,555 out=0 elapsed=3.5s

  [23/15692] intraday_0023.csv.gz  in=18,895,557 out=0 elapsed=3.5s

  [24/15692] intraday_0024.csv.gz  in=19,686,597 out=0 elapsed=3.9s

  [25/15692] intraday_0025.csv.gz  in=20,416,242 out=0 elapsed=3.9s

  [26/15692] intraday_0027.csv.gz  in=21,080,210 out=0 elapsed=3.9s

  [27/15692] intraday_0026.csv.gz  in=21,935,669 out=0 elapsed=4.0s

  [28/15692] intraday_0029.csv.gz  in=22,882,186 out=0 elapsed=4.6s

  [29/15692] intraday_0030.csv.gz  in=23,802,016 out=0 elapsed=4.6s

  [30/15692] intraday_0031.csv.gz  in=24,536,026 out=0 elapsed=4.6s

  [31/15692] intraday_0028.csv.gz  in=25,543,444 out=0 elapsed=4.6s

  [32/15692] intraday_0034.csv.gz  in=26,230,726 out=0 elapsed=5.2s

  [33/15692] intraday_0032.csv.gz  in=27,046,628 out=0 elapsed=5.2s

  [34/15692] intraday_0035.csv.gz  in=27,865,784 out=0 elapsed=5.2s

  [35/15692] intraday_0033.csv.gz  in=28,741,745 out=0 elapsed=5.2s

  [36/15692] intraday_0037.csv.gz  in=29,414,856 out=0 elapsed=5.6s

  [37/15692] intraday_0038.csv.gz  in=30,104,913 out=0 elapsed=5.7s

  [38/15692] intraday_0036.csv.gz  in=30,924,778 out=0 elapsed=5.7s

  [39/15692] intraday_0039.csv.gz  in=31,684,289 out=0 elapsed=5.8s

  [40/15692] intraday_0040.csv.gz  in=32,407,718 out=0 elapsed=6.1s

  [41/15692] intraday_0043.csv.gz  in=33,119,568 out=0 elapsed=6.2s

  [42/15692] intraday_0041.csv.gz  in=34,013,644 out=0 elapsed=6.3s

  [43/15692] intraday_0042.csv.gz  in=34,960,739 out=0 elapsed=6.4s

  [44/15692] intraday_0044.csv.gz  in=35,766,274 out=0 elapsed=6.6s

  [45/15692] intraday_0045.csv.gz  in=36,568,713 out=0 elapsed=6.7s

  [46/15692] intraday_0046.csv.gz  in=37,383,804 out=0 elapsed=6.8s

  [47/15692] intraday_0047.csv.gz  in=38,250,311 out=0 elapsed=6.9s

  [48/15692] intraday_0048.csv.gz  in=38,906,436 out=0 elapsed=7.0s

  [49/15692] intraday_0049.csv.gz  in=39,851,960 out=0 elapsed=7.4s

  [50/15692] intraday_0050.csv.gz  in=40,684,592 out=0 elapsed=7.4s

  [51/15692] intraday_0051.csv.gz  in=41,414,383 out=0 elapsed=7.5s

  [52/15692] intraday_0052.csv.gz  in=42,279,351 out=0 elapsed=7.7s

  [53/15692] intraday_0053.csv.gz  in=42,998,896 out=0 elapsed=7.9s

  [54/15692] intraday_0054.csv.gz  in=43,729,514 out=0 elapsed=7.9s

  [55/15692] intraday_0055.csv.gz  in=44,542,383 out=0 elapsed=8.0s

  [56/15692] intraday_0056.csv.gz  in=45,360,329 out=0 elapsed=8.2s

  [57/15692] intraday_0057.csv.gz  in=46,118,655 out=0 elapsed=8.4s

  [58/15692] intraday_0058.csv.gz  in=46,830,377 out=0 elapsed=8.4s

  [59/15692] intraday_0059.csv.gz  in=47,587,522 out=0 elapsed=8.5s

  [60/15692] intraday_0060.csv.gz  in=48,264,439 out=0 elapsed=8.7s

  [61/15692] intraday_0062.csv.gz  in=49,011,023 out=0 elapsed=8.9s

  [62/15692] intraday_0061.csv.gz  in=50,022,323 out=0 elapsed=9.0s

  [63/15692] intraday_0063.csv.gz  in=50,975,856 out=0 elapsed=9.1s

  [64/15692] intraday_0064.csv.gz  in=51,861,073 out=0 elapsed=9.2s

  [65/15692] intraday_0065.csv.gz  in=52,657,022 out=0 elapsed=9.4s

  [66/15692] intraday_0066.csv.gz  in=53,344,110 out=0 elapsed=9.5s

  [67/15692] intraday_0067.csv.gz  in=54,114,222 out=0 elapsed=9.6s

  [68/15692] intraday_0068.csv.gz  in=54,938,820 out=0 elapsed=9.8s

  [69/15692] intraday_0070.csv.gz  in=55,597,571 out=0 elapsed=9.9s

  [70/15692] intraday_0069.csv.gz  in=56,497,048 out=0 elapsed=10.0s

  [71/15692] intraday_0071.csv.gz  in=57,135,058 out=0 elapsed=10.1s

  [72/15692] intraday_0072.csv.gz  in=57,879,667 out=0 elapsed=10.2s

  [73/15692] intraday_0073.csv.gz  in=58,674,810 out=0 elapsed=10.5s

  [74/15692] intraday_0074.csv.gz  in=59,409,405 out=0 elapsed=10.5s

  [75/15692] intraday_0075.csv.gz  in=60,167,330 out=0 elapsed=10.6s

  [76/15692] intraday_0076.csv.gz  in=60,866,670 out=0 elapsed=10.7s

  [77/15692] intraday_0077.csv.gz  in=61,676,095 out=0 elapsed=11.0s

  [78/15692] intraday_0079.csv.gz  in=62,594,700 out=0 elapsed=11.2s

  [79/15692] intraday_0080.csv.gz  in=63,295,220 out=0 elapsed=11.2s

  [80/15692] intraday_0078.csv.gz  in=64,355,814 out=0 elapsed=11.3s

  [81/15692] intraday_0081.csv.gz  in=65,173,353 out=0 elapsed=11.7s

  [82/15692] intraday_0082.csv.gz  in=65,962,271 out=0 elapsed=11.8s

  [83/15692] intraday_0083.csv.gz  in=66,748,390 out=0 elapsed=11.8s

  [84/15692] intraday_0084.csv.gz  in=67,918,886 out=0 elapsed=12.1s

  [85/15692] intraday_0085.csv.gz  in=68,693,048 out=0 elapsed=12.2s

  [86/15692] intraday_0086.csv.gz  in=69,620,846 out=0 elapsed=12.5s

  [87/15692] intraday_0087.csv.gz  in=70,564,187 out=0 elapsed=12.5s

  [88/15692] intraday_0088.csv.gz  in=71,397,243 out=0 elapsed=12.7s

  [89/15692] intraday_0089.csv.gz  in=72,281,904 out=0 elapsed=12.8s

  [90/15692] intraday_0090.csv.gz  in=73,069,473 out=0 elapsed=13.0s

  [91/15692] intraday_0091.csv.gz  in=73,999,201 out=0 elapsed=13.1s

  [92/15692] intraday_0092.csv.gz  in=74,831,839 out=0 elapsed=13.2s

  [93/15692] intraday_0093.csv.gz  in=75,647,498 out=0 elapsed=13.4s

  [94/15692] intraday_0094.csv.gz  in=76,528,738 out=0 elapsed=13.6s

  [95/15692] intraday_0095.csv.gz  in=77,378,774 out=0 elapsed=13.7s

  [96/15692] intraday_0096.csv.gz  in=78,260,543 out=0 elapsed=13.8s

  [97/15692] intraday_0097.csv.gz  in=79,032,923 out=0 elapsed=13.9s

  [98/15692] intraday_0098.csv.gz  in=79,802,827 out=0 elapsed=14.1s

  [99/15692] intraday_0100.csv.gz  in=80,600,542 out=0 elapsed=14.4s

  [100/15692] intraday_0099.csv.gz  in=81,661,660 out=0 elapsed=14.4s

  [101/15692] intraday_0101.csv.gz  in=82,593,388 out=0 elapsed=14.5s

  [102/15692] intraday_0102.csv.gz  in=83,527,121 out=0 elapsed=14.7s

  [103/15692] intraday_0103.csv.gz  in=84,317,945 out=0 elapsed=14.9s

  [104/15692] intraday_0104.csv.gz  in=85,159,844 out=0 elapsed=15.0s

  [105/15692] intraday_0105.csv.gz  in=86,032,104 out=0 elapsed=15.1s

  [106/15692] intraday_0106.csv.gz  in=86,821,848 out=0 elapsed=15.2s

  [107/15692] intraday_0108.csv.gz  in=87,616,449 out=0 elapsed=15.6s

  [108/15692] intraday_0107.csv.gz  in=88,679,847 out=0 elapsed=15.6s

  [109/15692] intraday_0109.csv.gz  in=89,619,231 out=0 elapsed=15.7s

  [110/15692] intraday_0110.csv.gz  in=90,640,909 out=0 elapsed=15.9s

  [111/15692] intraday_0111.csv.gz  in=91,427,941 out=0 elapsed=16.0s

  [112/15692] intraday_0113.csv.gz  in=92,190,652 out=0 elapsed=16.2s

  [113/15692] intraday_0112.csv.gz  in=93,022,660 out=0 elapsed=16.2s

  [114/15692] intraday_0114.csv.gz  in=93,859,984 out=0 elapsed=16.4s

  [115/15692] intraday_0115.csv.gz  in=94,616,153 out=0 elapsed=16.5s

  [116/15692] intraday_0117.csv.gz  in=95,401,469 out=0 elapsed=16.7s

  [117/15692] intraday_0116.csv.gz  in=96,350,237 out=0 elapsed=16.8s

  [118/15692] intraday_0119.csv.gz  in=97,075,034 out=0 elapsed=17.0s

  [119/15692] intraday_0118.csv.gz  in=98,245,742 out=0 elapsed=17.2s

  [120/15692] intraday_0120.csv.gz  in=99,105,343 out=0 elapsed=17.3s

  [121/15692] intraday_0121.csv.gz  in=100,150,376 out=0 elapsed=17.5s

  [122/15692] intraday_0122.csv.gz  in=100,938,876 out=0 elapsed=17.5s

  [123/15692] intraday_0123.csv.gz  in=101,790,604 out=0 elapsed=17.7s

  [124/15692] intraday_0124.csv.gz  in=102,767,055 out=0 elapsed=17.9s

  [125/15692] intraday_0125.csv.gz  in=103,648,833 out=0 elapsed=18.1s

  [126/15692] intraday_0127.csv.gz  in=104,366,101 out=0 elapsed=18.2s

  [127/15692] intraday_0126.csv.gz  in=105,314,012 out=0 elapsed=18.2s

  [128/15692] intraday_0128.csv.gz  in=106,066,285 out=0 elapsed=18.4s

  [129/15692] intraday_0129.csv.gz  in=106,926,182 out=0 elapsed=18.8s

  [130/15692] intraday_0131.csv.gz  in=107,680,974 out=0 elapsed=18.8s

  [131/15692] intraday_0134.csv.gz  in=107,729,125 out=0 elapsed=18.9s

  [132/15692] intraday_0132.csv.gz  in=108,391,401 out=0 elapsed=18.9s

  [133/15692] intraday_0130.csv.gz  in=109,213,684 out=0 elapsed=18.9s

  [134/15692] intraday_0135.csv.gz  in=109,230,042 out=0 elapsed=18.9s

  [135/15692] intraday_0137.csv.gz  in=109,242,093 out=0 elapsed=18.9s

  [136/15692] intraday_0138.csv.gz  in=109,254,623 out=0 elapsed=18.9s

  [137/15692] intraday_0136.csv.gz  in=109,273,313 out=0 elapsed=18.9s

  [138/15692] intraday_0139.csv.gz  in=109,286,997 out=0 elapsed=19.0s

  [139/15692] intraday_0141.csv.gz  in=109,299,583 out=0 elapsed=19.0s

  [140/15692] intraday_0140.csv.gz  in=109,314,490 out=0 elapsed=19.0s

  [141/15692] intraday_0142.csv.gz  in=109,328,468 out=0 elapsed=19.0s

  [142/15692] intraday_0143.csv.gz  in=109,343,799 out=0 elapsed=19.0s

  [143/15692] intraday_0144.csv.gz  in=109,376,519 out=0 elapsed=19.0s

  [144/15692] intraday_0145.csv.gz  in=109,391,725 out=0 elapsed=19.0s

  [145/15692] intraday_0147.csv.gz  in=109,406,698 out=0 elapsed=19.1s

  [146/15692] intraday_0148.csv.gz  in=109,417,998 out=0 elapsed=19.1s

  [147/15692] intraday_0146.csv.gz  in=109,449,779 out=0 elapsed=19.1s

  [148/15692] intraday_0149.csv.gz  in=109,461,076 out=0 elapsed=19.1s

  [149/15692] intraday_0151.csv.gz  in=109,477,069 out=0 elapsed=19.1s

  [150/15692] intraday_0150.csv.gz  in=109,493,543 out=0 elapsed=19.1s

  [151/15692] intraday_0152.csv.gz  in=109,505,698 out=0 elapsed=19.1s

  [152/15692] intraday_0153.csv.gz  in=109,517,425 out=0 elapsed=19.2s

  [153/15692] intraday_0154.csv.gz  in=109,532,249 out=0 elapsed=19.2s

  [154/15692] intraday_0155.csv.gz  in=109,547,829 out=0 elapsed=19.2s

  [155/15692] intraday_0156.csv.gz  in=109,561,190 out=0 elapsed=19.2s

  [156/15692] intraday_0157.csv.gz  in=109,573,389 out=0 elapsed=19.2s

  [157/15692] intraday_0159.csv.gz  in=109,585,001 out=0 elapsed=19.2s

  [158/15692] intraday_0158.csv.gz  in=109,614,934 out=0 elapsed=19.2s

  [159/15692] intraday_0160.csv.gz  in=109,627,373 out=0 elapsed=19.2s

  [160/15692] intraday_0161.csv.gz  in=109,639,687 out=0 elapsed=19.2s

  [161/15692] intraday_0163.csv.gz  in=109,656,893 out=0 elapsed=19.2s

  [162/15692] intraday_0162.csv.gz  in=109,674,179 out=0 elapsed=19.3s

  [163/15692] intraday_0164.csv.gz  in=109,689,370 out=0 elapsed=19.3s

  [164/15692] intraday_0165.csv.gz  in=109,701,993 out=0 elapsed=19.3s

  [165/15692] intraday_0166.csv.gz  in=109,715,603 out=0 elapsed=19.3s

  [166/15692] intraday_0168.csv.gz  in=109,726,460 out=0 elapsed=19.3s

  [167/15692] intraday_0167.csv.gz  in=109,747,301 out=0 elapsed=19.3s

  [168/15692] intraday_0133.csv.gz  in=110,528,202 out=0 elapsed=19.3s

  [169/15692] intraday_0169.csv.gz  in=110,542,533 out=0 elapsed=19.3s

  [170/15692] intraday_0170.csv.gz  in=110,558,073 out=0 elapsed=19.4s

  [171/15692] intraday_0172.csv.gz  in=110,568,807 out=0 elapsed=19.4s

  [172/15692] intraday_0171.csv.gz  in=110,580,228 out=0 elapsed=19.4s

  [173/15692] intraday_0173.csv.gz  in=110,593,066 out=0 elapsed=19.4s

  [174/15692] intraday_0175.csv.gz  in=110,607,440 out=0 elapsed=19.4s

  [175/15692] intraday_0174.csv.gz  in=110,620,244 out=0 elapsed=19.4s

  [176/15692] intraday_0176.csv.gz  in=110,637,126 out=0 elapsed=19.4s

  [177/15692] intraday_0178.csv.gz  in=110,651,069 out=0 elapsed=19.4s

  [178/15692] intraday_0177.csv.gz  in=110,666,020 out=0 elapsed=19.4s

  [179/15692] intraday_0179.csv.gz  in=110,679,724 out=0 elapsed=19.4s

  [180/15692] intraday_0180.csv.gz  in=110,693,457 out=0 elapsed=19.4s

  [181/15692] intraday_0182.csv.gz  in=110,705,949 out=0 elapsed=19.4s

  [182/15692] intraday_0181.csv.gz  in=110,736,763 out=0 elapsed=19.4s

  [183/15692] intraday_0183.csv.gz  in=110,754,307 out=0 elapsed=19.5s

  [184/15692] intraday_0184.csv.gz  in=110,770,536 out=0 elapsed=19.5s

  [185/15692] intraday_0186.csv.gz  in=110,784,994 out=0 elapsed=19.5s

  [186/15692] intraday_0185.csv.gz  in=110,799,047 out=0 elapsed=19.5s

  [187/15692] intraday_0189.csv.gz  in=110,812,192 out=0 elapsed=19.5s

  [188/15692] intraday_0187.csv.gz  in=110,825,918 out=0 elapsed=19.5s

  [189/15692] intraday_0190.csv.gz  in=110,839,626 out=0 elapsed=19.5s

  [190/15692] intraday_0188.csv.gz  in=110,863,095 out=0 elapsed=19.5s

  [191/15692] intraday_0192.csv.gz  in=110,875,148 out=0 elapsed=19.5s

  [192/15692] intraday_0194.csv.gz  in=110,885,283 out=0 elapsed=19.6s

  [193/15692] intraday_0191.csv.gz  in=110,899,748 out=0 elapsed=19.6s

  [194/15692] intraday_0193.csv.gz  in=110,911,659 out=0 elapsed=19.6s

  [195/15692] intraday_0195.csv.gz  in=110,926,310 out=0 elapsed=19.6s

  [196/15692] intraday_0197.csv.gz  in=110,940,802 out=0 elapsed=19.6s

  [197/15692] intraday_0196.csv.gz  in=110,953,423 out=0 elapsed=19.6s

  [198/15692] intraday_0198.csv.gz  in=110,968,845 out=0 elapsed=19.6s

  [199/15692] intraday_0200.csv.gz  in=110,980,268 out=0 elapsed=19.6s

  [200/15692] intraday_0201.csv.gz  in=110,993,924 out=0 elapsed=19.6s

  [201/15692] intraday_0199.csv.gz  in=111,008,704 out=0 elapsed=19.6s

  [202/15692] intraday_0202.csv.gz  in=111,023,231 out=0 elapsed=19.6s

  [203/15692] intraday_0203.csv.gz  in=111,036,171 out=0 elapsed=19.7s

  [204/15692] intraday_0204.csv.gz  in=111,047,240 out=0 elapsed=19.7s

  [205/15692] intraday_0206.csv.gz  in=111,060,480 out=0 elapsed=19.7s

  [206/15692] intraday_0205.csv.gz  in=111,071,031 out=0 elapsed=19.7s

  [207/15692] intraday_0207.csv.gz  in=111,084,627 out=0 elapsed=19.7s

  [208/15692] intraday_0209.csv.gz  in=111,097,063 out=0 elapsed=19.7s

  [209/15692] intraday_0208.csv.gz  in=111,109,213 out=0 elapsed=19.7s

  [210/15692] intraday_0210.csv.gz  in=111,120,563 out=0 elapsed=19.7s

  [211/15692] intraday_0211.csv.gz  in=111,136,024 out=0 elapsed=19.7s

  [212/15692] intraday_0212.csv.gz  in=111,156,081 out=0 elapsed=19.8s

  [213/15692] intraday_0213.csv.gz  in=111,170,551 out=0 elapsed=19.8s

  [214/15692] intraday_0215.csv.gz  in=111,184,467 out=0 elapsed=19.8s

  [215/15692] intraday_0214.csv.gz  in=111,197,300 out=0 elapsed=19.8s

  [216/15692] intraday_0216.csv.gz  in=111,211,568 out=0 elapsed=19.8s

  [217/15692] intraday_0217.csv.gz  in=111,225,093 out=0 elapsed=19.8s

  [218/15692] intraday_0218.csv.gz  in=111,244,102 out=0 elapsed=19.8s

  [219/15692] intraday_0219.csv.gz  in=111,256,130 out=0 elapsed=19.8s

  [220/15692] intraday_0221.csv.gz  in=111,273,224 out=0 elapsed=19.8s

  [221/15692] intraday_0223.csv.gz  in=111,287,928 out=0 elapsed=19.9s

  [222/15692] intraday_0220.csv.gz  in=111,303,131 out=0 elapsed=19.9s

  [223/15692] intraday_0222.csv.gz  in=111,317,643 out=0 elapsed=19.9s

  [224/15692] intraday_0224.csv.gz  in=111,331,291 out=0 elapsed=19.9s

  [225/15692] intraday_0225.csv.gz  in=111,345,732 out=0 elapsed=19.9s

  [226/15692] intraday_0227.csv.gz  in=111,360,249 out=0 elapsed=19.9s

  [227/15692] intraday_0226.csv.gz  in=111,373,404 out=0 elapsed=19.9s

  [228/15692] intraday_0229.csv.gz  in=111,387,264 out=0 elapsed=19.9s

  [229/15692] intraday_0230.csv.gz  in=111,401,830 out=0 elapsed=19.9s

  [230/15692] intraday_0231.csv.gz  in=111,413,791 out=0 elapsed=19.9s

  [231/15692] intraday_0228.csv.gz  in=111,430,225 out=0 elapsed=19.9s

  [232/15692] intraday_0232.csv.gz  in=111,444,220 out=0 elapsed=20.0s

  [233/15692] intraday_0233.csv.gz  in=111,461,382 out=0 elapsed=20.0s

  [234/15692] intraday_0234.csv.gz  in=111,476,182 out=0 elapsed=20.0s

  [235/15692] intraday_0235.csv.gz  in=111,490,802 out=0 elapsed=20.0s

  [236/15692] intraday_0236.csv.gz  in=111,507,721 out=0 elapsed=20.0s

  [237/15692] intraday_0238.csv.gz  in=111,524,622 out=0 elapsed=20.0s

  [238/15692] intraday_0237.csv.gz  in=111,537,182 out=0 elapsed=20.0s

  [239/15692] intraday_0239.csv.gz  in=111,553,893 out=0 elapsed=20.0s

  [240/15692] intraday_0240.csv.gz  in=111,568,283 out=0 elapsed=20.1s

  [241/15692] intraday_0242.csv.gz  in=111,581,855 out=0 elapsed=20.1s

  [242/15692] intraday_0241.csv.gz  in=111,598,399 out=0 elapsed=20.1s

  [243/15692] intraday_0243.csv.gz  in=111,625,135 out=0 elapsed=20.1s

  [244/15692] intraday_0244.csv.gz  in=111,641,791 out=0 elapsed=20.1s

  [245/15692] intraday_0245.csv.gz  in=111,654,087 out=0 elapsed=20.1s

  [246/15692] intraday_0247.csv.gz  in=111,668,111 out=0 elapsed=20.1s

  [247/15692] intraday_0246.csv.gz  in=111,683,569 out=0 elapsed=20.1s

  [248/15692] intraday_0248.csv.gz  in=111,697,128 out=0 elapsed=20.1s

  [249/15692] intraday_0249.csv.gz  in=111,712,496 out=0 elapsed=20.1s

  [250/15692] intraday_0250.csv.gz  in=111,728,198 out=0 elapsed=20.2s

  [251/15692] intraday_0251.csv.gz  in=111,741,334 out=0 elapsed=20.2s

  [252/15692] intraday_0253.csv.gz  in=111,754,681 out=0 elapsed=20.2s

  [253/15692] intraday_0252.csv.gz  in=111,775,789 out=0 elapsed=20.2s

  [254/15692] intraday_0254.csv.gz  in=111,790,210 out=0 elapsed=20.2s

  [255/15692] intraday_0255.csv.gz  in=111,808,314 out=0 elapsed=20.2s

  [256/15692] intraday_0256.csv.gz  in=111,824,019 out=0 elapsed=20.2s

  [257/15692] intraday_0257.csv.gz  in=111,839,272 out=0 elapsed=20.2s

  [258/15692] intraday_0258.csv.gz  in=111,855,418 out=0 elapsed=20.2s

  [259/15692] intraday_0259.csv.gz  in=111,870,028 out=0 elapsed=20.2s

  [260/15692] intraday_0261.csv.gz  in=111,884,122 out=0 elapsed=20.3s

  [261/15692] intraday_0260.csv.gz  in=111,900,357 out=0 elapsed=20.3s

  [262/15692] intraday_0263.csv.gz  in=111,914,867 out=0 elapsed=20.3s

  [263/15692] intraday_0262.csv.gz  in=111,926,807 out=0 elapsed=20.3s

  [264/15692] intraday_0264.csv.gz  in=111,940,725 out=0 elapsed=20.3s

  [265/15692] intraday_0265.csv.gz  in=111,955,763 out=0 elapsed=20.3s

  [266/15692] intraday_0266.csv.gz  in=111,964,686 out=0 elapsed=20.3s

  [267/15692] intraday_0267.csv.gz  in=111,977,949 out=0 elapsed=20.3s

  [268/15692] intraday_0268.csv.gz  in=111,978,303 out=0 elapsed=20.3s

  [269/15692] intraday_0271.csv.gz  in=112,194,521 out=0 elapsed=20.5s

  [270/15692] intraday_0272.csv.gz  in=112,427,225 out=0 elapsed=20.5s

  [271/15692] intraday_0269.csv.gz  in=112,723,596 out=0 elapsed=20.6s

  [272/15692] intraday_0270.csv.gz  in=112,987,663 out=0 elapsed=20.6s

  [273/15692] intraday_0273.csv.gz  in=113,246,304 out=0 elapsed=20.7s

  [274/15692] intraday_0274.csv.gz  in=113,527,425 out=0 elapsed=20.8s

  [275/15692] intraday_0275.csv.gz  in=113,760,473 out=0 elapsed=20.8s

  [276/15692] intraday_0276.csv.gz  in=114,011,989 out=0 elapsed=20.8s

  [277/15692] intraday_0279.csv.gz  in=114,254,598 out=0 elapsed=20.9s

  [278/15692] intraday_0278.csv.gz  in=114,500,722 out=0 elapsed=21.0s

  [279/15692] intraday_0280.csv.gz  in=114,754,915 out=0 elapsed=21.0s

  [280/15692] intraday_0277.csv.gz  in=115,056,079 out=0 elapsed=21.0s

  [281/15692] intraday_0282.csv.gz  in=115,248,860 out=0 elapsed=21.1s

  [282/15692] intraday_0283.csv.gz  in=115,448,136 out=0 elapsed=21.2s

  [283/15692] intraday_0281.csv.gz  in=115,709,313 out=0 elapsed=21.2s

  [284/15692] intraday_0286.csv.gz  in=115,748,047 out=0 elapsed=21.2s

  [285/15692] intraday_0284.csv.gz  in=116,043,246 out=0 elapsed=21.3s

  [286/15692] intraday_0287.csv.gz  in=116,271,090 out=0 elapsed=21.3s

  [287/15692] intraday_0285.csv.gz  in=116,525,928 out=0 elapsed=21.4s

  [288/15692] intraday_0288.csv.gz  in=116,746,745 out=0 elapsed=21.4s

  [289/15692] intraday_0289.csv.gz  in=116,965,439 out=0 elapsed=21.4s

  [290/15692] intraday_0291.csv.gz  in=117,185,469 out=0 elapsed=21.5s

  [291/15692] intraday_0290.csv.gz  in=117,445,345 out=0 elapsed=21.6s

  [292/15692] intraday_0292.csv.gz  in=117,685,256 out=0 elapsed=21.6s

  [293/15692] intraday_0293.csv.gz  in=117,927,992 out=0 elapsed=21.6s

  [294/15692] intraday_0294.csv.gz  in=118,143,729 out=0 elapsed=21.7s

  [295/15692] intraday_0295.csv.gz  in=118,357,943 out=0 elapsed=21.7s

  [296/15692] intraday_0296.csv.gz  in=118,563,185 out=0 elapsed=21.8s

  [297/15692] intraday_0297.csv.gz  in=118,843,298 out=0 elapsed=21.8s

  [298/15692] intraday_0298.csv.gz  in=119,126,473 out=0 elapsed=21.9s

  [299/15692] intraday_0300.csv.gz  in=119,350,117 out=0 elapsed=21.9s

  [300/15692] intraday_0299.csv.gz  in=119,612,107 out=0 elapsed=21.9s

  [301/15692] intraday_0302.csv.gz  in=119,667,069 out=0 elapsed=22.0s

  [302/15692] intraday_0301.csv.gz  in=119,886,957 out=0 elapsed=22.0s

  [303/15692] intraday_0304.csv.gz  in=120,123,356 out=0 elapsed=22.1s

  [304/15692] intraday_0305.csv.gz  in=120,358,027 out=0 elapsed=22.2s

  [305/15692] intraday_0303.csv.gz  in=120,655,391 out=0 elapsed=22.2s

  [306/15692] intraday_0306.csv.gz  in=120,902,289 out=0 elapsed=22.2s

  [307/15692] intraday_0307.csv.gz  in=121,125,738 out=0 elapsed=22.3s

  [308/15692] intraday_0308.csv.gz  in=121,351,202 out=0 elapsed=22.3s

  [309/15692] intraday_0310.csv.gz  in=121,572,408 out=0 elapsed=22.4s

  [310/15692] intraday_0309.csv.gz  in=121,811,036 out=0 elapsed=22.4s

  [311/15692] intraday_0311.csv.gz  in=122,090,746 out=0 elapsed=22.5s

  [312/15692] intraday_0312.csv.gz  in=122,392,310 out=0 elapsed=22.5s

  [313/15692] intraday_0313.csv.gz  in=122,629,607 out=0 elapsed=22.6s

  [314/15692] intraday_0314.csv.gz  in=122,890,640 out=0 elapsed=22.6s

  [315/15692] intraday_0315.csv.gz  in=123,155,037 out=0 elapsed=22.7s

  [316/15692] intraday_0316.csv.gz  in=123,403,821 out=0 elapsed=22.8s

  [317/15692] intraday_0318.csv.gz  in=123,637,922 out=0 elapsed=22.8s

  [318/15692] intraday_0317.csv.gz  in=123,900,660 out=0 elapsed=22.8s

  [319/15692] intraday_0319.csv.gz  in=124,176,134 out=0 elapsed=22.9s

  [320/15692] intraday_0320.csv.gz  in=124,416,353 out=0 elapsed=22.9s

  [321/15692] intraday_0322.csv.gz  in=124,656,782 out=0 elapsed=23.0s

  [322/15692] intraday_0321.csv.gz  in=124,909,648 out=0 elapsed=23.0s

  [323/15692] intraday_0323.csv.gz  in=125,155,264 out=0 elapsed=23.1s

  [324/15692] intraday_0324.csv.gz  in=125,389,255 out=0 elapsed=23.1s

  [325/15692] intraday_0325.csv.gz  in=125,649,135 out=0 elapsed=23.2s

  [326/15692] intraday_0326.csv.gz  in=125,911,356 out=0 elapsed=23.2s

  [327/15692] intraday_0327.csv.gz  in=126,118,825 out=0 elapsed=23.2s

  [328/15692] intraday_0328.csv.gz  in=126,374,250 out=0 elapsed=23.3s

  [329/15692] intraday_0330.csv.gz  in=126,570,754 out=0 elapsed=23.3s

  [330/15692] intraday_0329.csv.gz  in=126,779,582 out=0 elapsed=23.3s

  [331/15692] intraday_0331.csv.gz  in=127,046,519 out=0 elapsed=23.4s

  [332/15692] intraday_0333.csv.gz  in=127,253,545 out=0 elapsed=23.5s

  [333/15692] intraday_0332.csv.gz  in=127,538,683 out=0 elapsed=23.5s

  [334/15692] intraday_0334.csv.gz  in=127,816,232 out=0 elapsed=23.5s

  [335/15692] intraday_0335.csv.gz  in=128,092,776 out=0 elapsed=23.7s

  [336/15692] intraday_0336.csv.gz  in=128,295,496 out=0 elapsed=23.7s

  [337/15692] intraday_0337.csv.gz  in=128,525,452 out=0 elapsed=23.7s

  [338/15692] intraday_0338.csv.gz  in=128,783,286 out=0 elapsed=23.7s

  [339/15692] intraday_0340.csv.gz  in=128,981,471 out=0 elapsed=23.8s

  [340/15692] intraday_0339.csv.gz  in=129,240,852 out=0 elapsed=23.8s

  [341/15692] intraday_0341.csv.gz  in=129,458,823 out=0 elapsed=23.9s

  [342/15692] intraday_0342.csv.gz  in=129,667,620 out=0 elapsed=23.9s

  [343/15692] intraday_0343.csv.gz  in=129,899,349 out=0 elapsed=24.0s

  [344/15692] intraday_0344.csv.gz  in=130,138,366 out=0 elapsed=24.0s

  [345/15692] intraday_0345.csv.gz  in=130,376,937 out=0 elapsed=24.0s

  [346/15692] intraday_0346.csv.gz  in=130,559,285 out=0 elapsed=24.0s

  [347/15692] intraday_0347.csv.gz  in=130,772,959 out=0 elapsed=24.2s

  [348/15692] intraday_0348.csv.gz  in=131,024,833 out=0 elapsed=24.2s

  [349/15692] intraday_0350.csv.gz  in=131,261,296 out=0 elapsed=24.2s

  [350/15692] intraday_0349.csv.gz  in=131,570,921 out=0 elapsed=24.3s

  [351/15692] intraday_0351.csv.gz  in=131,797,285 out=0 elapsed=24.3s

  [352/15692] intraday_0352.csv.gz  in=132,033,883 out=0 elapsed=24.4s

  [353/15692] intraday_0353.csv.gz  in=132,292,867 out=0 elapsed=24.4s

  [354/15692] intraday_0354.csv.gz  in=132,523,180 out=0 elapsed=24.5s

  [355/15692] intraday_0355.csv.gz  in=132,836,273 out=0 elapsed=24.6s

  [356/15692] intraday_0356.csv.gz  in=133,077,260 out=0 elapsed=24.6s

  [357/15692] intraday_0357.csv.gz  in=133,365,265 out=0 elapsed=24.7s

  [358/15692] intraday_0358.csv.gz  in=133,649,154 out=0 elapsed=24.7s

  [359/15692] intraday_0359.csv.gz  in=133,915,035 out=0 elapsed=24.8s

  [360/15692] intraday_0360.csv.gz  in=134,168,226 out=0 elapsed=24.8s

  [361/15692] intraday_0361.csv.gz  in=134,407,423 out=0 elapsed=24.8s

  [362/15692] intraday_0362.csv.gz  in=134,663,024 out=0 elapsed=24.9s

  [363/15692] intraday_0363.csv.gz  in=134,908,995 out=0 elapsed=24.9s

  [364/15692] intraday_0364.csv.gz  in=135,155,263 out=0 elapsed=25.0s

  [365/15692] intraday_0365.csv.gz  in=135,380,830 out=0 elapsed=25.0s

  [366/15692] intraday_0366.csv.gz  in=135,644,767 out=0 elapsed=25.0s

  [367/15692] intraday_0367.csv.gz  in=135,928,713 out=0 elapsed=25.1s

  [368/15692] intraday_0368.csv.gz  in=136,162,187 out=0 elapsed=25.2s

  [369/15692] intraday_0369.csv.gz  in=136,435,160 out=0 elapsed=25.2s

  [370/15692] intraday_0370.csv.gz  in=136,756,824 out=0 elapsed=25.3s

  [371/15692] intraday_0371.csv.gz  in=137,029,476 out=0 elapsed=25.4s

  [372/15692] intraday_0372.csv.gz  in=137,296,332 out=0 elapsed=25.4s

  [373/15692] intraday_0373.csv.gz  in=137,544,174 out=0 elapsed=25.4s

  [374/15692] intraday_0374.csv.gz  in=137,814,211 out=0 elapsed=25.5s

  [375/15692] intraday_0375.csv.gz  in=138,017,550 out=0 elapsed=25.5s

  [376/15692] intraday_0377.csv.gz  in=138,254,790 out=0 elapsed=25.6s

  [377/15692] intraday_0376.csv.gz  in=138,565,665 out=0 elapsed=25.6s

  [378/15692] intraday_0378.csv.gz  in=138,834,795 out=0 elapsed=25.7s

  [379/15692] intraday_0379.csv.gz  in=139,087,787 out=0 elapsed=25.7s

  [380/15692] intraday_0380.csv.gz  in=139,374,542 out=0 elapsed=25.8s

  [381/15692] intraday_0381.csv.gz  in=139,648,162 out=0 elapsed=25.8s

  [382/15692] intraday_0382.csv.gz  in=139,904,999 out=0 elapsed=25.9s

  [383/15692] intraday_0383.csv.gz  in=140,179,278 out=0 elapsed=25.9s

  [384/15692] intraday_0385.csv.gz  in=140,391,955 out=0 elapsed=26.0s

  [385/15692] intraday_0384.csv.gz  in=140,640,779 out=0 elapsed=26.0s

  [386/15692] intraday_0386.csv.gz  in=140,878,294 out=0 elapsed=26.0s

  [387/15692] intraday_0387.csv.gz  in=141,147,253 out=0 elapsed=26.1s

  [388/15692] intraday_0388.csv.gz  in=141,399,520 out=0 elapsed=26.2s

  [389/15692] intraday_0390.csv.gz  in=141,623,618 out=0 elapsed=26.2s

  [390/15692] intraday_0389.csv.gz  in=141,949,153 out=0 elapsed=26.2s

  [391/15692] intraday_0391.csv.gz  in=142,203,569 out=0 elapsed=26.3s

  [392/15692] intraday_0392.csv.gz  in=142,457,409 out=0 elapsed=26.3s

  [393/15692] intraday_0393.csv.gz  in=142,721,977 out=0 elapsed=26.4s

  [394/15692] intraday_0394.csv.gz  in=142,966,664 out=0 elapsed=26.4s

  [395/15692] intraday_0395.csv.gz  in=143,253,685 out=0 elapsed=26.5s

  [396/15692] intraday_0396.csv.gz  in=143,532,614 out=0 elapsed=26.6s

  [397/15692] intraday_0397.csv.gz  in=143,777,948 out=0 elapsed=26.6s

  [398/15692] intraday_0398.csv.gz  in=144,034,957 out=0 elapsed=26.6s

  [399/15692] intraday_0399.csv.gz  in=144,258,829 out=0 elapsed=26.7s

  [400/15692] intraday_0401.csv.gz  in=144,456,402 out=0 elapsed=26.7s

  [401/15692] intraday_0400.csv.gz  in=144,678,165 out=0 elapsed=26.7s

  [402/15692] intraday_0402.csv.gz  in=144,938,220 out=0 elapsed=26.8s

  [403/15692] intraday_0406.csv.gz  in=144,952,932 out=0 elapsed=26.8s

  [404/15692] intraday_0407.csv.gz  in=144,977,359 out=0 elapsed=26.8s

  [405/15692] intraday_0404.csv.gz  in=145,138,657 out=0 elapsed=26.8s

  [406/15692] intraday_0403.csv.gz  in=145,351,978 out=0 elapsed=26.9s

  [407/15692] intraday_0408.csv.gz  in=145,364,245 out=0 elapsed=26.9s

  [408/15692] intraday_0409.csv.gz  in=145,377,611 out=0 elapsed=26.9s

  [409/15692] intraday_0410.csv.gz  in=145,392,730 out=0 elapsed=26.9s

  [410/15692] intraday_0412.csv.gz  in=145,403,794 out=0 elapsed=26.9s

  [411/15692] intraday_0405.csv.gz  in=145,628,198 out=0 elapsed=26.9s

  [412/15692] intraday_0411.csv.gz  in=145,644,055 out=0 elapsed=26.9s

  [413/15692] intraday_0414.csv.gz  in=145,658,626 out=0 elapsed=26.9s

  [414/15692] intraday_0413.csv.gz  in=145,671,610 out=0 elapsed=26.9s

  [415/15692] intraday_0416.csv.gz  in=145,683,008 out=0 elapsed=26.9s

  [416/15692] intraday_0415.csv.gz  in=145,695,807 out=0 elapsed=27.0s

  [417/15692] intraday_0417.csv.gz  in=145,709,282 out=0 elapsed=27.0s

  [418/15692] intraday_0418.csv.gz  in=145,723,588 out=0 elapsed=27.0s

  [419/15692] intraday_0421.csv.gz  in=145,738,891 out=0 elapsed=27.0s

  [420/15692] intraday_0419.csv.gz  in=145,750,168 out=0 elapsed=27.0s

  [421/15692] intraday_0420.csv.gz  in=145,761,843 out=0 elapsed=27.0s

  [422/15692] intraday_0422.csv.gz  in=145,775,162 out=0 elapsed=27.0s

  [423/15692] intraday_0423.csv.gz  in=145,786,663 out=0 elapsed=27.0s

  [424/15692] intraday_0424.csv.gz  in=145,797,862 out=0 elapsed=27.0s

  [425/15692] intraday_0425.csv.gz  in=145,809,626 out=0 elapsed=27.0s

  [426/15692] intraday_0426.csv.gz  in=145,821,626 out=0 elapsed=27.0s

  [427/15692] intraday_0427.csv.gz  in=145,833,678 out=0 elapsed=27.0s

  [428/15692] intraday_0428.csv.gz  in=145,846,867 out=0 elapsed=27.0s

  [429/15692] intraday_0429.csv.gz  in=145,859,925 out=0 elapsed=27.1s

  [430/15692] intraday_0430.csv.gz  in=145,870,744 out=0 elapsed=27.1s

  [431/15692] intraday_0431.csv.gz  in=145,882,155 out=0 elapsed=27.1s

  [432/15692] intraday_0432.csv.gz  in=145,893,068 out=0 elapsed=27.1s

  [433/15692] intraday_0433.csv.gz  in=145,907,644 out=0 elapsed=27.1s

  [434/15692] intraday_0436.csv.gz  in=145,919,951 out=0 elapsed=27.1s

  [435/15692] intraday_0434.csv.gz  in=145,935,727 out=0 elapsed=27.1s

  [436/15692] intraday_0435.csv.gz  in=145,951,958 out=0 elapsed=27.1s

  [437/15692] intraday_0437.csv.gz  in=145,963,948 out=0 elapsed=27.1s

  [438/15692] intraday_0438.csv.gz  in=145,976,928 out=0 elapsed=27.1s

  [439/15692] intraday_0440.csv.gz  in=145,989,184 out=0 elapsed=27.1s

  [440/15692] intraday_0441.csv.gz  in=146,001,106 out=0 elapsed=27.1s

  [441/15692] intraday_0439.csv.gz  in=146,018,926 out=0 elapsed=27.1s

  [442/15692] intraday_0444.csv.gz  in=146,031,268 out=0 elapsed=27.2s

  [443/15692] intraday_0442.csv.gz  in=146,044,881 out=0 elapsed=27.2s

  [444/15692] intraday_0443.csv.gz  in=146,056,615 out=0 elapsed=27.2s

  [445/15692] intraday_0445.csv.gz  in=146,071,013 out=0 elapsed=27.2s

  [446/15692] intraday_0446.csv.gz  in=146,084,577 out=0 elapsed=27.2s

  [447/15692] intraday_0447.csv.gz  in=146,098,749 out=0 elapsed=27.2s

  [448/15692] intraday_0448.csv.gz  in=146,112,265 out=0 elapsed=27.2s

  [449/15692] intraday_0450.csv.gz  in=146,125,627 out=0 elapsed=27.2s

  [450/15692] intraday_0451.csv.gz  in=146,138,212 out=0 elapsed=27.3s

  [451/15692] intraday_0452.csv.gz  in=146,156,689 out=0 elapsed=27.3s

  [452/15692] intraday_0449.csv.gz  in=146,194,390 out=0 elapsed=27.3s

  [453/15692] intraday_0453.csv.gz  in=146,206,987 out=0 elapsed=27.3s

  [454/15692] intraday_0454.csv.gz  in=146,219,751 out=0 elapsed=27.3s

  [455/15692] intraday_0455.csv.gz  in=146,243,311 out=0 elapsed=27.3s

  [456/15692] intraday_0456.csv.gz  in=146,255,603 out=0 elapsed=27.3s

  [457/15692] intraday_0457.csv.gz  in=146,269,716 out=0 elapsed=27.3s

  [458/15692] intraday_0458.csv.gz  in=146,282,797 out=0 elapsed=27.3s

  [459/15692] intraday_0459.csv.gz  in=146,296,147 out=0 elapsed=27.3s

  [460/15692] intraday_0462.csv.gz  in=146,309,731 out=0 elapsed=27.4s

  [461/15692] intraday_0461.csv.gz  in=146,322,047 out=0 elapsed=27.4s

  [462/15692] intraday_0460.csv.gz  in=146,337,792 out=0 elapsed=27.4s

  [463/15692] intraday_0463.csv.gz  in=146,350,280 out=0 elapsed=27.4s

  [464/15692] intraday_0466.csv.gz  in=146,362,900 out=0 elapsed=27.4s

  [465/15692] intraday_0464.csv.gz  in=146,374,668 out=0 elapsed=27.4s

  [466/15692] intraday_0465.csv.gz  in=146,400,574 out=0 elapsed=27.4s

  [467/15692] intraday_0467.csv.gz  in=146,417,843 out=0 elapsed=27.4s

  [468/15692] intraday_0468.csv.gz  in=146,429,806 out=0 elapsed=27.4s

  [469/15692] intraday_0469.csv.gz  in=146,444,443 out=0 elapsed=27.4s

  [470/15692] intraday_0471.csv.gz  in=146,457,069 out=0 elapsed=27.4s

  [471/15692] intraday_0472.csv.gz  in=146,469,015 out=0 elapsed=27.5s

  [472/15692] intraday_0470.csv.gz  in=146,483,702 out=0 elapsed=27.5s

  [473/15692] intraday_0473.csv.gz  in=146,495,640 out=0 elapsed=27.5s

  [474/15692] intraday_0474.csv.gz  in=146,508,636 out=0 elapsed=27.5s

  [475/15692] intraday_0475.csv.gz  in=146,521,728 out=0 elapsed=27.5s

  [476/15692] intraday_0476.csv.gz  in=146,533,238 out=0 elapsed=27.5s

  [477/15692] intraday_0477.csv.gz  in=146,542,494 out=0 elapsed=27.5s

  [478/15692] intraday_0478.csv.gz  in=146,554,934 out=0 elapsed=27.5s

  [479/15692] intraday_0480.csv.gz  in=146,566,656 out=0 elapsed=27.5s

  [480/15692] intraday_0481.csv.gz  in=146,578,909 out=0 elapsed=27.5s

  [481/15692] intraday_0479.csv.gz  in=146,591,926 out=0 elapsed=27.5s

  [482/15692] intraday_0482.csv.gz  in=146,603,171 out=0 elapsed=27.6s

  [483/15692] intraday_0483.csv.gz  in=146,613,850 out=0 elapsed=27.6s

  [484/15692] intraday_0484.csv.gz  in=146,625,831 out=0 elapsed=27.6s

  [485/15692] intraday_0485.csv.gz  in=146,643,216 out=0 elapsed=27.6s

  [486/15692] intraday_0486.csv.gz  in=146,655,077 out=0 elapsed=27.6s

  [487/15692] intraday_0487.csv.gz  in=146,665,512 out=0 elapsed=27.6s

  [488/15692] intraday_0488.csv.gz  in=146,679,315 out=0 elapsed=27.6s

  [489/15692] intraday_0489.csv.gz  in=146,691,816 out=0 elapsed=27.6s

  [490/15692] intraday_0491.csv.gz  in=146,706,683 out=0 elapsed=27.7s

  [491/15692] intraday_0490.csv.gz  in=146,724,538 out=0 elapsed=27.7s

  [492/15692] intraday_0492.csv.gz  in=146,738,727 out=0 elapsed=27.7s

  [493/15692] intraday_0494.csv.gz  in=146,753,507 out=0 elapsed=27.7s

  [494/15692] intraday_0495.csv.gz  in=146,767,084 out=0 elapsed=27.7s

  [495/15692] intraday_0493.csv.gz  in=146,781,319 out=0 elapsed=27.7s

  [496/15692] intraday_0496.csv.gz  in=146,796,225 out=0 elapsed=27.7s

  [497/15692] intraday_0498.csv.gz  in=146,809,413 out=0 elapsed=27.7s

  [498/15692] intraday_0499.csv.gz  in=146,820,728 out=0 elapsed=27.7s

  [499/15692] intraday_0497.csv.gz  in=146,840,301 out=0 elapsed=27.8s

  [500/15692] intraday_0500.csv.gz  in=146,860,626 out=0 elapsed=27.8s

  [501/15692] intraday_0501.csv.gz  in=146,879,764 out=0 elapsed=27.8s

  [502/15692] intraday_0504.csv.gz  in=146,892,430 out=0 elapsed=27.8s

  [503/15692] intraday_0502.csv.gz  in=146,909,552 out=0 elapsed=27.8s

  [504/15692] intraday_0503.csv.gz  in=146,923,190 out=0 elapsed=27.8s

  [505/15692] intraday_0505.csv.gz  in=146,938,528 out=0 elapsed=27.8s

  [506/15692] intraday_0507.csv.gz  in=146,954,063 out=0 elapsed=27.8s

  [507/15692] intraday_0509.csv.gz  in=146,970,123 out=0 elapsed=27.8s

  [508/15692] intraday_0508.csv.gz  in=146,999,268 out=0 elapsed=27.8s

  [509/15692] intraday_0510.csv.gz  in=147,010,635 out=0 elapsed=27.9s

  [510/15692] intraday_0506.csv.gz  in=147,046,916 out=0 elapsed=27.9s

  [511/15692] intraday_0511.csv.gz  in=147,060,675 out=0 elapsed=27.9s

  [512/15692] intraday_0512.csv.gz  in=147,077,697 out=0 elapsed=27.9s

  [513/15692] intraday_0513.csv.gz  in=147,090,371 out=0 elapsed=27.9s

  [514/15692] intraday_0514.csv.gz  in=147,108,078 out=0 elapsed=27.9s

  [515/15692] intraday_0515.csv.gz  in=147,122,880 out=0 elapsed=27.9s

  [516/15692] intraday_0516.csv.gz  in=147,137,901 out=0 elapsed=27.9s

  [517/15692] intraday_0517.csv.gz  in=147,154,561 out=0 elapsed=27.9s

  [518/15692] intraday_0518.csv.gz  in=147,166,721 out=0 elapsed=27.9s

  [519/15692] intraday_0519.csv.gz  in=147,180,329 out=0 elapsed=27.9s

  [520/15692] intraday_0520.csv.gz  in=147,191,638 out=0 elapsed=27.9s

  [521/15692] intraday_0521.csv.gz  in=147,204,598 out=0 elapsed=28.0s

  [522/15692] intraday_0522.csv.gz  in=147,217,859 out=0 elapsed=28.0s

  [523/15692] intraday_0523.csv.gz  in=147,232,671 out=0 elapsed=28.0s

  [524/15692] intraday_0524.csv.gz  in=147,245,780 out=0 elapsed=28.0s

  [525/15692] intraday_0525.csv.gz  in=147,261,573 out=0 elapsed=28.0s

  [526/15692] intraday_0527.csv.gz  in=147,274,550 out=0 elapsed=28.0s

  [527/15692] intraday_0526.csv.gz  in=147,287,469 out=0 elapsed=28.0s

  [528/15692] intraday_0528.csv.gz  in=147,304,425 out=0 elapsed=28.0s

  [529/15692] intraday_0529.csv.gz  in=147,316,770 out=0 elapsed=28.0s

  [530/15692] intraday_0530.csv.gz  in=147,331,059 out=0 elapsed=28.1s

  [531/15692] intraday_0531.csv.gz  in=147,347,109 out=0 elapsed=28.1s

  [532/15692] intraday_0532.csv.gz  in=147,361,302 out=0 elapsed=28.1s

  [533/15692] intraday_0533.csv.gz  in=147,376,091 out=0 elapsed=28.1s

  [534/15692] intraday_0534.csv.gz  in=147,390,514 out=0 elapsed=28.1s

  [535/15692] intraday_0535.csv.gz  in=147,401,061 out=0 elapsed=28.1s

  [536/15692] intraday_0536.csv.gz  in=147,412,623 out=0 elapsed=28.1s

  [537/15692] intraday_0537.csv.gz  in=147,423,684 out=0 elapsed=28.1s

  [538/15692] intraday_0538.csv.gz  in=147,437,484 out=0 elapsed=28.1s

  [539/15692] intraday_0539.csv.gz  in=147,448,480 out=0 elapsed=28.1s

  [540/15692] intraday_0540.csv.gz  in=147,458,505 out=0 elapsed=28.1s

  [541/15692] intraday_0541.csv.gz  in=147,466,999 out=0 elapsed=28.1s

  [542/15692] intraday_0543.csv.gz  in=147,496,589 out=0 elapsed=28.2s

  [543/15692] intraday_0544.csv.gz  in=147,523,470 out=0 elapsed=28.2s

  [544/15692] intraday_0542.csv.gz  in=147,565,316 out=0 elapsed=28.2s

  [545/15692] intraday_0545.csv.gz  in=147,606,543 out=0 elapsed=28.2s

  [546/15692] intraday_0546.csv.gz  in=147,637,961 out=0 elapsed=28.2s

  [547/15692] intraday_0548.csv.gz  in=147,661,901 out=0 elapsed=28.2s

  [548/15692] intraday_0547.csv.gz  in=147,695,604 out=0 elapsed=28.2s

  [549/15692] intraday_0549.csv.gz  in=147,723,194 out=0 elapsed=28.2s

  [550/15692] intraday_0550.csv.gz  in=147,752,711 out=0 elapsed=28.3s

  [551/15692] intraday_0552.csv.gz  in=147,776,750 out=0 elapsed=28.3s

  [552/15692] intraday_0553.csv.gz  in=147,805,298 out=0 elapsed=28.3s

  [553/15692] intraday_0551.csv.gz  in=147,832,832 out=0 elapsed=28.3s

  [554/15692] intraday_0556.csv.gz  in=147,856,606 out=0 elapsed=28.3s

  [555/15692] intraday_0554.csv.gz  in=147,887,611 out=0 elapsed=28.3s

  [556/15692] intraday_0555.csv.gz  in=147,910,090 out=0 elapsed=28.3s

  [557/15692] intraday_0557.csv.gz  in=147,941,618 out=0 elapsed=28.3s

  [558/15692] intraday_0558.csv.gz  in=147,970,209 out=0 elapsed=28.4s

  [559/15692] intraday_0561.csv.gz  in=147,997,282 out=0 elapsed=28.4s

  [560/15692] intraday_0559.csv.gz  in=148,024,155 out=0 elapsed=28.4s

  [561/15692] intraday_0560.csv.gz  in=148,048,023 out=0 elapsed=28.4s

  [562/15692] intraday_0563.csv.gz  in=148,072,792 out=0 elapsed=28.4s

  [563/15692] intraday_0562.csv.gz  in=148,097,855 out=0 elapsed=28.4s

  [564/15692] intraday_0564.csv.gz  in=148,124,975 out=0 elapsed=28.4s

  [565/15692] intraday_0565.csv.gz  in=148,152,228 out=0 elapsed=28.4s

  [566/15692] intraday_0567.csv.gz  in=148,175,399 out=0 elapsed=28.5s

  [567/15692] intraday_0568.csv.gz  in=148,196,408 out=0 elapsed=28.5s

  [568/15692] intraday_0566.csv.gz  in=148,219,961 out=0 elapsed=28.5s

  [569/15692] intraday_0569.csv.gz  in=148,251,292 out=0 elapsed=28.5s

  [570/15692] intraday_0572.csv.gz  in=148,275,606 out=0 elapsed=28.5s

  [571/15692] intraday_0570.csv.gz  in=148,308,858 out=0 elapsed=28.5s

  [572/15692] intraday_0573.csv.gz  in=148,335,163 out=0 elapsed=28.5s

  [573/15692] intraday_0571.csv.gz  in=148,367,608 out=0 elapsed=28.5s

  [574/15692] intraday_0574.csv.gz  in=148,395,071 out=0 elapsed=28.6s

  [575/15692] intraday_0577.csv.gz  in=148,420,604 out=0 elapsed=28.6s

  [576/15692] intraday_0575.csv.gz  in=148,454,444 out=0 elapsed=28.6s

  [577/15692] intraday_0576.csv.gz  in=148,485,209 out=0 elapsed=28.6s

  [578/15692] intraday_0578.csv.gz  in=148,517,233 out=0 elapsed=28.6s

  [579/15692] intraday_0580.csv.gz  in=148,543,926 out=0 elapsed=28.6s

  [580/15692] intraday_0579.csv.gz  in=148,595,905 out=0 elapsed=28.7s

  [581/15692] intraday_0581.csv.gz  in=148,628,651 out=0 elapsed=28.7s

  [582/15692] intraday_0582.csv.gz  in=148,659,685 out=0 elapsed=28.7s

  [583/15692] intraday_0583.csv.gz  in=148,688,678 out=0 elapsed=28.7s

  [584/15692] intraday_0585.csv.gz  in=148,714,730 out=0 elapsed=28.7s

  [585/15692] intraday_0584.csv.gz  in=148,745,268 out=0 elapsed=28.7s

  [586/15692] intraday_0586.csv.gz  in=148,772,890 out=0 elapsed=28.7s

  [587/15692] intraday_0587.csv.gz  in=148,798,828 out=0 elapsed=28.8s

  [588/15692] intraday_0589.csv.gz  in=148,827,976 out=0 elapsed=28.8s

  [589/15692] intraday_0590.csv.gz  in=148,858,914 out=0 elapsed=28.8s

  [590/15692] intraday_0588.csv.gz  in=148,910,881 out=0 elapsed=28.8s

  [591/15692] intraday_0591.csv.gz  in=148,938,696 out=0 elapsed=28.8s

  [592/15692] intraday_0592.csv.gz  in=148,966,176 out=0 elapsed=28.8s

  [593/15692] intraday_0594.csv.gz  in=148,992,313 out=0 elapsed=28.8s

  [594/15692] intraday_0593.csv.gz  in=149,028,521 out=0 elapsed=28.8s

  [595/15692] intraday_0595.csv.gz  in=149,055,519 out=0 elapsed=28.9s

  [596/15692] intraday_0596.csv.gz  in=149,080,692 out=0 elapsed=28.9s

  [597/15692] intraday_0597.csv.gz  in=149,107,419 out=0 elapsed=28.9s

  [598/15692] intraday_0598.csv.gz  in=149,135,059 out=0 elapsed=28.9s

  [599/15692] intraday_0599.csv.gz  in=149,161,545 out=0 elapsed=28.9s

  [600/15692] intraday_0602.csv.gz  in=149,183,985 out=0 elapsed=28.9s

  [601/15692] intraday_0600.csv.gz  in=149,208,272 out=0 elapsed=28.9s

  [602/15692] intraday_0601.csv.gz  in=149,232,632 out=0 elapsed=28.9s

  [603/15692] intraday_0604.csv.gz  in=149,258,376 out=0 elapsed=28.9s

  [604/15692] intraday_0603.csv.gz  in=149,292,076 out=0 elapsed=28.9s

  [605/15692] intraday_0605.csv.gz  in=149,320,593 out=0 elapsed=29.0s

  [606/15692] intraday_0606.csv.gz  in=149,352,504 out=0 elapsed=29.0s

  [607/15692] intraday_0607.csv.gz  in=149,401,073 out=0 elapsed=29.0s

  [608/15692] intraday_0608.csv.gz  in=149,423,867 out=0 elapsed=29.0s

  [609/15692] intraday_0609.csv.gz  in=149,449,906 out=0 elapsed=29.0s

  [610/15692] intraday_0610.csv.gz  in=149,475,762 out=0 elapsed=29.0s

  [611/15692] intraday_0611.csv.gz  in=149,505,510 out=0 elapsed=29.0s

  [612/15692] intraday_0613.csv.gz  in=149,527,026 out=0 elapsed=29.0s

  [613/15692] intraday_0612.csv.gz  in=149,549,726 out=0 elapsed=29.0s

  [614/15692] intraday_0614.csv.gz  in=149,575,053 out=0 elapsed=29.1s

  [615/15692] intraday_0617.csv.gz  in=149,604,418 out=0 elapsed=29.1s

  [616/15692] intraday_0616.csv.gz  in=149,629,082 out=0 elapsed=29.1s

  [617/15692] intraday_0615.csv.gz  in=149,663,849 out=0 elapsed=29.1s

  [618/15692] intraday_0618.csv.gz  in=149,684,038 out=0 elapsed=29.1s

  [619/15692] intraday_0619.csv.gz  in=149,706,447 out=0 elapsed=29.1s

  [620/15692] intraday_0621.csv.gz  in=149,740,849 out=0 elapsed=29.1s

  [621/15692] intraday_0620.csv.gz  in=149,776,338 out=0 elapsed=29.2s

  [622/15692] intraday_0622.csv.gz  in=149,803,181 out=0 elapsed=29.2s

  [623/15692] intraday_0623.csv.gz  in=149,829,559 out=0 elapsed=29.2s

  [624/15692] intraday_0624.csv.gz  in=149,859,203 out=0 elapsed=29.2s

  [625/15692] intraday_0625.csv.gz  in=149,888,290 out=0 elapsed=29.2s

  [626/15692] intraday_0626.csv.gz  in=149,918,669 out=0 elapsed=29.2s

  [627/15692] intraday_0627.csv.gz  in=149,952,541 out=0 elapsed=29.2s

  [628/15692] intraday_0628.csv.gz  in=149,987,266 out=0 elapsed=29.2s

  [629/15692] intraday_0630.csv.gz  in=150,017,883 out=0 elapsed=29.3s

  [630/15692] intraday_0629.csv.gz  in=150,051,815 out=0 elapsed=29.3s

  [631/15692] intraday_0632.csv.gz  in=150,078,805 out=0 elapsed=29.3s

  [632/15692] intraday_0631.csv.gz  in=150,109,334 out=0 elapsed=29.3s

  [633/15692] intraday_0633.csv.gz  in=150,137,613 out=0 elapsed=29.3s

  [634/15692] intraday_0636.csv.gz  in=150,162,253 out=0 elapsed=29.3s

  [635/15692] intraday_0635.csv.gz  in=150,190,543 out=0 elapsed=29.3s

  [636/15692] intraday_0634.csv.gz  in=150,223,517 out=0 elapsed=29.3s

  [637/15692] intraday_0637.csv.gz  in=150,254,101 out=0 elapsed=29.4s

  [638/15692] intraday_0640.csv.gz  in=150,282,412 out=0 elapsed=29.4s

  [639/15692] intraday_0639.csv.gz  in=150,311,322 out=0 elapsed=29.4s

  [640/15692] intraday_0638.csv.gz  in=150,344,888 out=0 elapsed=29.4s

  [641/15692] intraday_0641.csv.gz  in=150,374,658 out=0 elapsed=29.4s

  [642/15692] intraday_0642.csv.gz  in=150,406,279 out=0 elapsed=29.4s

  [643/15692] intraday_0643.csv.gz  in=150,440,063 out=0 elapsed=29.5s

  [644/15692] intraday_0644.csv.gz  in=150,471,135 out=0 elapsed=29.5s

  [645/15692] intraday_0646.csv.gz  in=150,497,193 out=0 elapsed=29.5s

  [646/15692] intraday_0647.csv.gz  in=150,526,308 out=0 elapsed=29.5s

  [647/15692] intraday_0645.csv.gz  in=150,559,265 out=0 elapsed=29.5s

  [648/15692] intraday_0648.csv.gz  in=150,588,431 out=0 elapsed=29.5s

  [649/15692] intraday_0649.csv.gz  in=150,616,816 out=0 elapsed=29.5s

  [650/15692] intraday_0650.csv.gz  in=150,647,955 out=0 elapsed=29.5s

  [651/15692] intraday_0651.csv.gz  in=150,672,868 out=0 elapsed=29.6s

  [652/15692] intraday_0652.csv.gz  in=150,705,622 out=0 elapsed=29.6s

  [653/15692] intraday_0654.csv.gz  in=150,732,794 out=0 elapsed=29.6s

  [654/15692] intraday_0653.csv.gz  in=150,767,795 out=0 elapsed=29.6s

  [655/15692] intraday_0655.csv.gz  in=150,796,374 out=0 elapsed=29.6s

  [656/15692] intraday_0656.csv.gz  in=150,827,694 out=0 elapsed=29.6s

  [657/15692] intraday_0657.csv.gz  in=150,854,681 out=0 elapsed=29.6s

  [658/15692] intraday_0658.csv.gz  in=150,880,261 out=0 elapsed=29.6s

  [659/15692] intraday_0660.csv.gz  in=150,908,292 out=0 elapsed=29.7s

  [660/15692] intraday_0659.csv.gz  in=150,940,951 out=0 elapsed=29.7s

  [661/15692] intraday_0661.csv.gz  in=150,993,194 out=0 elapsed=29.7s

  [662/15692] intraday_0662.csv.gz  in=151,019,866 out=0 elapsed=29.7s

  [663/15692] intraday_0663.csv.gz  in=151,050,073 out=0 elapsed=29.7s

  [664/15692] intraday_0664.csv.gz  in=151,082,311 out=0 elapsed=29.7s

  [665/15692] intraday_0665.csv.gz  in=151,112,109 out=0 elapsed=29.7s

  [666/15692] intraday_0666.csv.gz  in=151,145,019 out=0 elapsed=29.8s

  [667/15692] intraday_0668.csv.gz  in=151,173,904 out=0 elapsed=29.8s

  [668/15692] intraday_0667.csv.gz  in=151,209,545 out=0 elapsed=29.8s

  [669/15692] intraday_0669.csv.gz  in=151,238,489 out=0 elapsed=29.8s

  [670/15692] intraday_0670.csv.gz  in=151,268,576 out=0 elapsed=29.8s

  [671/15692] intraday_0671.csv.gz  in=151,301,299 out=0 elapsed=29.8s

  [672/15692] intraday_0673.csv.gz  in=151,324,654 out=0 elapsed=29.8s

  [673/15692] intraday_0672.csv.gz  in=151,354,334 out=0 elapsed=29.8s

  [674/15692] intraday_0675.csv.gz  in=151,374,813 out=0 elapsed=29.9s

  [675/15692] intraday_0676.csv.gz  in=151,397,390 out=0 elapsed=29.9s

  [676/15692] intraday_0677.csv.gz  in=151,415,623 out=0 elapsed=29.9s

  [677/15692] intraday_0674.csv.gz  in=151,447,334 out=0 elapsed=29.9s

  [678/15692] intraday_0681.csv.gz  in=151,566,858 out=0 elapsed=30.0s

  [679/15692] intraday_0680.csv.gz  in=151,694,372 out=0 elapsed=30.0s

  [680/15692] intraday_0678.csv.gz  in=151,875,757 out=0 elapsed=30.0s

  [681/15692] intraday_0679.csv.gz  in=152,035,572 out=0 elapsed=30.0s

  [682/15692] intraday_0682.csv.gz  in=152,183,889 out=0 elapsed=30.1s

  [683/15692] intraday_0684.csv.gz  in=152,303,931 out=0 elapsed=30.2s

  [684/15692] intraday_0685.csv.gz  in=152,436,248 out=0 elapsed=30.2s

  [685/15692] intraday_0683.csv.gz  in=152,597,012 out=0 elapsed=30.2s

  [686/15692] intraday_0689.csv.gz  in=152,738,953 out=0 elapsed=30.3s

  [687/15692] intraday_0686.csv.gz  in=152,883,719 out=0 elapsed=30.3s

  [688/15692] intraday_0688.csv.gz  in=153,011,591 out=0 elapsed=30.3s

  [689/15692] intraday_0687.csv.gz  in=153,154,517 out=0 elapsed=30.3s

  [690/15692] intraday_0692.csv.gz  in=153,255,887 out=0 elapsed=30.4s

  [691/15692] intraday_0691.csv.gz  in=153,383,278 out=0 elapsed=30.4s

  [692/15692] intraday_0690.csv.gz  in=153,542,476 out=0 elapsed=30.5s

  [693/15692] intraday_0693.csv.gz  in=153,725,767 out=0 elapsed=30.5s

  [694/15692] intraday_0694.csv.gz  in=153,864,268 out=0 elapsed=30.5s

  [695/15692] intraday_0695.csv.gz  in=153,997,703 out=0 elapsed=30.6s

  [696/15692] intraday_0696.csv.gz  in=154,134,404 out=0 elapsed=30.6s

  [697/15692] intraday_0697.csv.gz  in=154,268,443 out=0 elapsed=30.6s

  [698/15692] intraday_0698.csv.gz  in=154,406,877 out=0 elapsed=30.6s

  [699/15692] intraday_0699.csv.gz  in=154,540,161 out=0 elapsed=30.6s

  [700/15692] intraday_0700.csv.gz  in=154,667,673 out=0 elapsed=30.7s

  [701/15692] intraday_0702.csv.gz  in=154,807,028 out=0 elapsed=30.7s

  [702/15692] intraday_0703.csv.gz  in=154,933,198 out=0 elapsed=30.7s

  [703/15692] intraday_0701.csv.gz  in=155,122,287 out=0 elapsed=30.8s

  [704/15692] intraday_0704.csv.gz  in=155,240,129 out=0 elapsed=30.8s

  [705/15692] intraday_0705.csv.gz  in=155,402,243 out=0 elapsed=30.8s

  [706/15692] intraday_0708.csv.gz  in=155,522,748 out=0 elapsed=30.9s

  [707/15692] intraday_0706.csv.gz  in=155,702,641 out=0 elapsed=30.9s

  [708/15692] intraday_0707.csv.gz  in=155,861,235 out=0 elapsed=30.9s

  [709/15692] intraday_0709.csv.gz  in=155,997,571 out=0 elapsed=31.0s

  [710/15692] intraday_0710.csv.gz  in=156,136,449 out=0 elapsed=31.0s

  [711/15692] intraday_0712.csv.gz  in=156,273,222 out=0 elapsed=31.0s

  [712/15692] intraday_0713.csv.gz  in=156,396,389 out=0 elapsed=31.1s

  [713/15692] intraday_0711.csv.gz  in=156,619,873 out=0 elapsed=31.1s

  [714/15692] intraday_0715.csv.gz  in=156,754,514 out=0 elapsed=31.1s

  [715/15692] intraday_0714.csv.gz  in=156,903,093 out=0 elapsed=31.1s

  [716/15692] intraday_0716.csv.gz  in=157,041,253 out=0 elapsed=31.2s

  [717/15692] intraday_0717.csv.gz  in=157,196,573 out=0 elapsed=31.2s

  [718/15692] intraday_0719.csv.gz  in=157,329,992 out=0 elapsed=31.2s

  [719/15692] intraday_0718.csv.gz  in=157,478,345 out=0 elapsed=31.2s

  [720/15692] intraday_0721.csv.gz  in=157,602,475 out=0 elapsed=31.4s

  [721/15692] intraday_0720.csv.gz  in=157,766,245 out=0 elapsed=31.4s

  [722/15692] intraday_0722.csv.gz  in=157,888,287 out=0 elapsed=31.4s

  [723/15692] intraday_0723.csv.gz  in=158,046,991 out=0 elapsed=31.4s

  [724/15692] intraday_0724.csv.gz  in=158,185,787 out=0 elapsed=31.5s

  [725/15692] intraday_0726.csv.gz  in=158,327,091 out=0 elapsed=31.5s

  [726/15692] intraday_0725.csv.gz  in=158,468,376 out=0 elapsed=31.5s

  [727/15692] intraday_0727.csv.gz  in=158,616,553 out=0 elapsed=31.5s

  [728/15692] intraday_0730.csv.gz  in=158,652,357 out=0 elapsed=31.6s

  [729/15692] intraday_0729.csv.gz  in=158,764,658 out=0 elapsed=31.6s

  [730/15692] intraday_0728.csv.gz  in=158,897,969 out=0 elapsed=31.6s

  [731/15692] intraday_0731.csv.gz  in=159,046,471 out=0 elapsed=31.7s

  [732/15692] intraday_0732.csv.gz  in=159,182,736 out=0 elapsed=31.7s

  [733/15692] intraday_0733.csv.gz  in=159,312,419 out=0 elapsed=31.7s

  [734/15692] intraday_0734.csv.gz  in=159,445,206 out=0 elapsed=31.7s

  [735/15692] intraday_0736.csv.gz  in=159,565,824 out=0 elapsed=31.8s

  [736/15692] intraday_0735.csv.gz  in=159,729,226 out=0 elapsed=31.8s

  [737/15692] intraday_0738.csv.gz  in=159,848,715 out=0 elapsed=31.9s

  [738/15692] intraday_0737.csv.gz  in=159,994,738 out=0 elapsed=31.9s

  [739/15692] intraday_0739.csv.gz  in=160,108,715 out=0 elapsed=31.9s

  [740/15692] intraday_0740.csv.gz  in=160,251,867 out=0 elapsed=31.9s

  [741/15692] intraday_0741.csv.gz  in=160,398,732 out=0 elapsed=32.0s

  [742/15692] intraday_0743.csv.gz  in=160,551,885 out=0 elapsed=32.0s

  [743/15692] intraday_0742.csv.gz  in=160,694,567 out=0 elapsed=32.0s

  [744/15692] intraday_0744.csv.gz  in=160,847,878 out=0 elapsed=32.0s

  [745/15692] intraday_0746.csv.gz  in=160,981,611 out=0 elapsed=32.1s

  [746/15692] intraday_0745.csv.gz  in=161,134,735 out=0 elapsed=32.2s

  [747/15692] intraday_0747.csv.gz  in=161,275,438 out=0 elapsed=32.2s

  [748/15692] intraday_0748.csv.gz  in=161,413,941 out=0 elapsed=32.2s

  [749/15692] intraday_0749.csv.gz  in=161,530,783 out=0 elapsed=32.2s

  [750/15692] intraday_0751.csv.gz  in=161,642,263 out=0 elapsed=32.3s

  [751/15692] intraday_0750.csv.gz  in=161,769,784 out=0 elapsed=32.3s

  [752/15692] intraday_0752.csv.gz  in=161,904,477 out=0 elapsed=32.3s

  [753/15692] intraday_0753.csv.gz  in=162,036,013 out=0 elapsed=32.4s

  [754/15692] intraday_0756.csv.gz  in=162,141,237 out=0 elapsed=32.4s

  [755/15692] intraday_0755.csv.gz  in=162,264,935 out=0 elapsed=32.4s

  [756/15692] intraday_0754.csv.gz  in=162,402,013 out=0 elapsed=32.4s

  [757/15692] intraday_0757.csv.gz  in=162,533,048 out=0 elapsed=32.5s

  [758/15692] intraday_0760.csv.gz  in=162,666,525 out=0 elapsed=32.5s

  [759/15692] intraday_0758.csv.gz  in=162,840,643 out=0 elapsed=32.6s

  [760/15692] intraday_0761.csv.gz  in=162,955,568 out=0 elapsed=32.6s

  [761/15692] intraday_0759.csv.gz  in=163,114,446 out=0 elapsed=32.6s

  [762/15692] intraday_0762.csv.gz  in=163,249,987 out=0 elapsed=32.6s

  [763/15692] intraday_0763.csv.gz  in=163,397,708 out=0 elapsed=32.7s

  [764/15692] intraday_0765.csv.gz  in=163,533,935 out=0 elapsed=32.7s

  [765/15692] intraday_0764.csv.gz  in=163,688,782 out=0 elapsed=32.7s

  [766/15692] intraday_0766.csv.gz  in=163,846,217 out=0 elapsed=32.8s

  [767/15692] intraday_0767.csv.gz  in=163,993,651 out=0 elapsed=32.8s

  [768/15692] intraday_0768.csv.gz  in=164,150,804 out=0 elapsed=32.8s

  [769/15692] intraday_0769.csv.gz  in=164,303,234 out=0 elapsed=32.8s

  [770/15692] intraday_0770.csv.gz  in=164,436,536 out=0 elapsed=32.9s

  [771/15692] intraday_0771.csv.gz  in=164,570,092 out=0 elapsed=32.9s

  [772/15692] intraday_0773.csv.gz  in=164,700,589 out=0 elapsed=33.0s

  [773/15692] intraday_0772.csv.gz  in=164,847,419 out=0 elapsed=33.0s

  [774/15692] intraday_0774.csv.gz  in=164,988,419 out=0 elapsed=33.0s

  [775/15692] intraday_0775.csv.gz  in=165,118,612 out=0 elapsed=33.1s

  [776/15692] intraday_0777.csv.gz  in=165,255,747 out=0 elapsed=33.1s

  [777/15692] intraday_0776.csv.gz  in=165,422,237 out=0 elapsed=33.1s

  [778/15692] intraday_0778.csv.gz  in=165,571,124 out=0 elapsed=33.2s

  [779/15692] intraday_0780.csv.gz  in=165,702,180 out=0 elapsed=33.2s

  [780/15692] intraday_0781.csv.gz  in=165,838,888 out=0 elapsed=33.2s

  [781/15692] intraday_0779.csv.gz  in=165,998,218 out=0 elapsed=33.2s

  [782/15692] intraday_0784.csv.gz  in=166,137,295 out=0 elapsed=33.4s

  [783/15692] intraday_0782.csv.gz  in=166,305,106 out=0 elapsed=33.4s

  [784/15692] intraday_0785.csv.gz  in=166,437,985 out=0 elapsed=33.4s

  [785/15692] intraday_0783.csv.gz  in=166,594,735 out=0 elapsed=33.4s

  [786/15692] intraday_0789.csv.gz  in=166,659,088 out=0 elapsed=33.5s

  [787/15692] intraday_0786.csv.gz  in=166,797,967 out=0 elapsed=33.5s

  [788/15692] intraday_0788.csv.gz  in=166,946,735 out=0 elapsed=33.5s

  [789/15692] intraday_0787.csv.gz  in=167,078,657 out=0 elapsed=33.5s

  [790/15692] intraday_0790.csv.gz  in=167,244,773 out=0 elapsed=33.6s

  [791/15692] intraday_0793.csv.gz  in=167,384,105 out=0 elapsed=33.6s

  [792/15692] intraday_0791.csv.gz  in=167,545,130 out=0 elapsed=33.6s

  [793/15692] intraday_0792.csv.gz  in=167,710,769 out=0 elapsed=33.7s

  [794/15692] intraday_0794.csv.gz  in=167,861,533 out=0 elapsed=33.7s

  [795/15692] intraday_0796.csv.gz  in=167,986,152 out=0 elapsed=33.8s

  [796/15692] intraday_0795.csv.gz  in=168,118,552 out=0 elapsed=33.8s

  [797/15692] intraday_0797.csv.gz  in=168,273,090 out=0 elapsed=33.8s

  [798/15692] intraday_0798.csv.gz  in=168,419,998 out=0 elapsed=33.9s

  [799/15692] intraday_0800.csv.gz  in=168,564,380 out=0 elapsed=33.9s

  [800/15692] intraday_0799.csv.gz  in=168,732,695 out=0 elapsed=33.9s

  [801/15692] intraday_0801.csv.gz  in=168,875,476 out=0 elapsed=33.9s

  [802/15692] intraday_0802.csv.gz  in=169,018,762 out=0 elapsed=34.0s

  [803/15692] intraday_0803.csv.gz  in=169,185,875 out=0 elapsed=34.0s

  [804/15692] intraday_0804.csv.gz  in=169,326,594 out=0 elapsed=34.0s

  [805/15692] intraday_0805.csv.gz  in=169,500,098 out=0 elapsed=34.0s

  [806/15692] intraday_0806.csv.gz  in=169,648,754 out=0 elapsed=34.1s

  [807/15692] intraday_0807.csv.gz  in=169,786,706 out=0 elapsed=34.1s

  [808/15692] intraday_0808.csv.gz  in=169,941,973 out=0 elapsed=34.1s

  [809/15692] intraday_0809.csv.gz  in=170,069,026 out=0 elapsed=34.1s

  [810/15692] intraday_0810.csv.gz  in=170,199,485 out=0 elapsed=34.2s

  [811/15692] intraday_0811.csv.gz  in=170,333,352 out=0 elapsed=34.2s

  [812/15692] intraday_0812.csv.gz  in=170,466,177 out=0 elapsed=34.2s

  [813/15692] intraday_0813.csv.gz  in=170,569,218 out=0 elapsed=34.2s

  [814/15692] intraday_0817.csv.gz  in=170,583,417 out=0 elapsed=34.3s

  [815/15692] intraday_0816.csv.gz  in=170,622,032 out=0 elapsed=34.3s

  [816/15692] intraday_0818.csv.gz  in=170,636,027 out=0 elapsed=34.3s

  [817/15692] intraday_0814.csv.gz  in=170,733,336 out=0 elapsed=34.3s

  [818/15692] intraday_0819.csv.gz  in=170,745,538 out=0 elapsed=34.3s

  [819/15692] intraday_0821.csv.gz  in=170,760,462 out=0 elapsed=34.3s

  [820/15692] intraday_0820.csv.gz  in=170,776,861 out=0 elapsed=34.3s

  [821/15692] intraday_0822.csv.gz  in=170,790,908 out=0 elapsed=34.3s

  [822/15692] intraday_0815.csv.gz  in=170,902,088 out=0 elapsed=34.4s

  [823/15692] intraday_0823.csv.gz  in=170,912,904 out=0 elapsed=34.4s

  [824/15692] intraday_0825.csv.gz  in=170,930,229 out=0 elapsed=34.4s

  [825/15692] intraday_0824.csv.gz  in=170,951,617 out=0 elapsed=34.4s

  [826/15692] intraday_0827.csv.gz  in=170,961,238 out=0 elapsed=34.4s

  [827/15692] intraday_0826.csv.gz  in=170,974,625 out=0 elapsed=34.4s

  [828/15692] intraday_0831.csv.gz  in=170,984,148 out=0 elapsed=34.4s

  [829/15692] intraday_0829.csv.gz  in=170,997,504 out=0 elapsed=34.4s

  [830/15692] intraday_0830.csv.gz  in=171,007,658 out=0 elapsed=34.4s

  [831/15692] intraday_0828.csv.gz  in=171,034,647 out=0 elapsed=34.4s

  [832/15692] intraday_0832.csv.gz  in=171,048,427 out=0 elapsed=34.5s

  [833/15692] intraday_0833.csv.gz  in=171,060,905 out=0 elapsed=34.5s

  [834/15692] intraday_0834.csv.gz  in=171,073,732 out=0 elapsed=34.5s

  [835/15692] intraday_0835.csv.gz  in=171,085,053 out=0 elapsed=34.5s

  [836/15692] intraday_0836.csv.gz  in=171,100,482 out=0 elapsed=34.5s

  [837/15692] intraday_0837.csv.gz  in=171,113,243 out=0 elapsed=34.5s

  [838/15692] intraday_0838.csv.gz  in=171,126,352 out=0 elapsed=34.5s

  [839/15692] intraday_0839.csv.gz  in=171,138,213 out=0 elapsed=34.5s

  [840/15692] intraday_0840.csv.gz  in=171,150,913 out=0 elapsed=34.5s

  [841/15692] intraday_0843.csv.gz  in=171,163,181 out=0 elapsed=34.5s

  [842/15692] intraday_0841.csv.gz  in=171,183,510 out=0 elapsed=34.5s

  [843/15692] intraday_0842.csv.gz  in=171,194,078 out=0 elapsed=34.6s

  [844/15692] intraday_0844.csv.gz  in=171,207,678 out=0 elapsed=34.6s

  [845/15692] intraday_0845.csv.gz  in=171,222,799 out=0 elapsed=34.6s

  [846/15692] intraday_0846.csv.gz  in=171,237,060 out=0 elapsed=34.6s

  [847/15692] intraday_0847.csv.gz  in=171,249,394 out=0 elapsed=34.6s

  [848/15692] intraday_0848.csv.gz  in=171,262,538 out=0 elapsed=34.6s

  [849/15692] intraday_0849.csv.gz  in=171,275,034 out=0 elapsed=34.6s

  [850/15692] intraday_0851.csv.gz  in=171,286,602 out=0 elapsed=34.6s

  [851/15692] intraday_0850.csv.gz  in=171,299,233 out=0 elapsed=34.6s

  [852/15692] intraday_0853.csv.gz  in=171,311,047 out=0 elapsed=34.6s

  [853/15692] intraday_0852.csv.gz  in=171,333,791 out=0 elapsed=34.6s

  [854/15692] intraday_0854.csv.gz  in=171,344,863 out=0 elapsed=34.7s

  [855/15692] intraday_0855.csv.gz  in=171,367,005 out=0 elapsed=34.7s

  [856/15692] intraday_0858.csv.gz  in=171,379,485 out=0 elapsed=34.7s

  [857/15692] intraday_0856.csv.gz  in=171,392,152 out=0 elapsed=34.7s

  [858/15692] intraday_0857.csv.gz  in=171,405,058 out=0 elapsed=34.7s

  [859/15692] intraday_0859.csv.gz  in=171,419,692 out=0 elapsed=34.7s

  [860/15692] intraday_0862.csv.gz  in=171,431,758 out=0 elapsed=34.7s

  [861/15692] intraday_0860.csv.gz  in=171,443,869 out=0 elapsed=34.7s

  [862/15692] intraday_0863.csv.gz  in=171,456,272 out=0 elapsed=34.7s

  [863/15692] intraday_0861.csv.gz  in=171,468,222 out=0 elapsed=34.7s

  [864/15692] intraday_0864.csv.gz  in=171,482,017 out=0 elapsed=34.8s

  [865/15692] intraday_0865.csv.gz  in=171,498,820 out=0 elapsed=34.8s

  [866/15692] intraday_0866.csv.gz  in=171,510,495 out=0 elapsed=34.8s

  [867/15692] intraday_0868.csv.gz  in=171,520,177 out=0 elapsed=34.8s

  [868/15692] intraday_0867.csv.gz  in=171,535,560 out=0 elapsed=34.8s

  [869/15692] intraday_0869.csv.gz  in=171,548,360 out=0 elapsed=34.8s

  [870/15692] intraday_0871.csv.gz  in=171,559,111 out=0 elapsed=34.8s

  [871/15692] intraday_0870.csv.gz  in=171,570,872 out=0 elapsed=34.8s

  [872/15692] intraday_0872.csv.gz  in=171,582,750 out=0 elapsed=34.8s

  [873/15692] intraday_0874.csv.gz  in=171,595,613 out=0 elapsed=34.8s

  [874/15692] intraday_0873.csv.gz  in=171,608,084 out=0 elapsed=34.8s

  [875/15692] intraday_0876.csv.gz  in=171,618,708 out=0 elapsed=34.9s

  [876/15692] intraday_0875.csv.gz  in=171,630,652 out=0 elapsed=34.9s

  [877/15692] intraday_0879.csv.gz  in=171,643,691 out=0 elapsed=34.9s

  [878/15692] intraday_0877.csv.gz  in=171,653,906 out=0 elapsed=34.9s

  [879/15692] intraday_0880.csv.gz  in=171,666,555 out=0 elapsed=34.9s

  [880/15692] intraday_0878.csv.gz  in=171,677,195 out=0 elapsed=34.9s

  [881/15692] intraday_0882.csv.gz  in=171,690,621 out=0 elapsed=34.9s

  [882/15692] intraday_0883.csv.gz  in=171,702,137 out=0 elapsed=34.9s

  [883/15692] intraday_0881.csv.gz  in=171,716,945 out=0 elapsed=34.9s

  [884/15692] intraday_0884.csv.gz  in=171,727,599 out=0 elapsed=34.9s

  [885/15692] intraday_0886.csv.gz  in=171,739,331 out=0 elapsed=35.0s

  [886/15692] intraday_0885.csv.gz  in=171,751,580 out=0 elapsed=35.0s

  [887/15692] intraday_0888.csv.gz  in=171,764,334 out=0 elapsed=35.0s

  [888/15692] intraday_0887.csv.gz  in=171,777,220 out=0 elapsed=35.0s

  [889/15692] intraday_0889.csv.gz  in=171,788,961 out=0 elapsed=35.0s

  [890/15692] intraday_0890.csv.gz  in=171,800,237 out=0 elapsed=35.0s

  [891/15692] intraday_0891.csv.gz  in=171,812,341 out=0 elapsed=35.0s

  [892/15692] intraday_0892.csv.gz  in=171,823,805 out=0 elapsed=35.0s

  [893/15692] intraday_0893.csv.gz  in=171,834,942 out=0 elapsed=35.0s

  [894/15692] intraday_0895.csv.gz  in=171,845,734 out=0 elapsed=35.0s

  [895/15692] intraday_0894.csv.gz  in=171,855,495 out=0 elapsed=35.0s

  [896/15692] intraday_0896.csv.gz  in=171,866,627 out=0 elapsed=35.0s

  [897/15692] intraday_0900.csv.gz  in=171,878,330 out=0 elapsed=35.1s

  [898/15692] intraday_0897.csv.gz  in=171,894,386 out=0 elapsed=35.1s

  [899/15692] intraday_0899.csv.gz  in=171,905,564 out=0 elapsed=35.1s

  [900/15692] intraday_0898.csv.gz  in=171,918,523 out=0 elapsed=35.1s

  [901/15692] intraday_0901.csv.gz  in=171,931,030 out=0 elapsed=35.1s

  [902/15692] intraday_0903.csv.gz  in=171,945,624 out=0 elapsed=35.1s

  [903/15692] intraday_0904.csv.gz  in=171,958,065 out=0 elapsed=35.1s

  [904/15692] intraday_0902.csv.gz  in=171,970,669 out=0 elapsed=35.1s

  [905/15692] intraday_0905.csv.gz  in=171,985,253 out=0 elapsed=35.1s

  [906/15692] intraday_0906.csv.gz  in=171,999,586 out=0 elapsed=35.2s

  [907/15692] intraday_0907.csv.gz  in=172,011,979 out=0 elapsed=35.2s

  [908/15692] intraday_0908.csv.gz  in=172,025,210 out=0 elapsed=35.2s

  [909/15692] intraday_0909.csv.gz  in=172,037,663 out=0 elapsed=35.2s

  [910/15692] intraday_0910.csv.gz  in=172,050,205 out=0 elapsed=35.2s

  [911/15692] intraday_0911.csv.gz  in=172,062,369 out=0 elapsed=35.2s

  [912/15692] intraday_0912.csv.gz  in=172,074,088 out=0 elapsed=35.2s

  [913/15692] intraday_0913.csv.gz  in=172,087,236 out=0 elapsed=35.2s

  [914/15692] intraday_0915.csv.gz  in=172,099,411 out=0 elapsed=35.3s

  [915/15692] intraday_0914.csv.gz  in=172,110,713 out=0 elapsed=35.3s

  [916/15692] intraday_0916.csv.gz  in=172,121,855 out=0 elapsed=35.3s

  [917/15692] intraday_0917.csv.gz  in=172,134,361 out=0 elapsed=35.3s

  [918/15692] intraday_0918.csv.gz  in=172,146,865 out=0 elapsed=35.3s

  [919/15692] intraday_0920.csv.gz  in=172,159,869 out=0 elapsed=35.3s

  [920/15692] intraday_0919.csv.gz  in=172,171,440 out=0 elapsed=35.3s

  [921/15692] intraday_0921.csv.gz  in=172,185,852 out=0 elapsed=35.3s

  [922/15692] intraday_0922.csv.gz  in=172,198,803 out=0 elapsed=35.3s

  [923/15692] intraday_0924.csv.gz  in=172,211,447 out=0 elapsed=35.3s

  [924/15692] intraday_0923.csv.gz  in=172,222,572 out=0 elapsed=35.3s

  [925/15692] intraday_0926.csv.gz  in=172,234,891 out=0 elapsed=35.4s

  [926/15692] intraday_0925.csv.gz  in=172,248,876 out=0 elapsed=35.4s

  [927/15692] intraday_0927.csv.gz  in=172,260,868 out=0 elapsed=35.4s

  [928/15692] intraday_0928.csv.gz  in=172,274,527 out=0 elapsed=35.4s

  [929/15692] intraday_0929.csv.gz  in=172,288,263 out=0 elapsed=35.4s

  [930/15692] intraday_0930.csv.gz  in=172,300,820 out=0 elapsed=35.4s

  [931/15692] intraday_0931.csv.gz  in=172,314,019 out=0 elapsed=35.4s

  [932/15692] intraday_0933.csv.gz  in=172,324,770 out=0 elapsed=35.4s

  [933/15692] intraday_0932.csv.gz  in=172,337,937 out=0 elapsed=35.4s

  [934/15692] intraday_0934.csv.gz  in=172,348,617 out=0 elapsed=35.4s

  [935/15692] intraday_0935.csv.gz  in=172,363,031 out=0 elapsed=35.5s

  [936/15692] intraday_0936.csv.gz  in=172,375,984 out=0 elapsed=35.5s

  [937/15692] intraday_0938.csv.gz  in=172,388,037 out=0 elapsed=35.5s

  [938/15692] intraday_0937.csv.gz  in=172,403,487 out=0 elapsed=35.5s

  [939/15692] intraday_0939.csv.gz  in=172,417,191 out=0 elapsed=35.5s

  [940/15692] intraday_0940.csv.gz  in=172,428,760 out=0 elapsed=35.5s

  [941/15692] intraday_0941.csv.gz  in=172,441,679 out=0 elapsed=35.5s

  [942/15692] intraday_0942.csv.gz  in=172,456,071 out=0 elapsed=35.5s

  [943/15692] intraday_0944.csv.gz  in=172,470,100 out=0 elapsed=35.5s

  [944/15692] intraday_0946.csv.gz  in=172,483,951 out=0 elapsed=35.6s

  [945/15692] intraday_0945.csv.gz  in=172,495,948 out=0 elapsed=35.6s

  [946/15692] intraday_0947.csv.gz  in=172,506,415 out=0 elapsed=35.6s

  [947/15692] intraday_0943.csv.gz  in=172,527,681 out=0 elapsed=35.6s

  [948/15692] intraday_0948.csv.gz  in=172,539,630 out=0 elapsed=35.6s

  [949/15692] intraday_0949.csv.gz  in=172,551,621 out=0 elapsed=35.6s

  [950/15692] intraday_0950.csv.gz  in=172,563,487 out=0 elapsed=35.6s

  [951/15692] intraday_0951.csv.gz  in=172,571,876 out=0 elapsed=35.6s

  [952/15692] intraday_0952.csv.gz  in=172,580,367 out=0 elapsed=35.6s

  [953/15692] intraday_0953.csv.gz  in=172,591,936 out=0 elapsed=35.6s

  [954/15692] intraday_0954.csv.gz  in=172,594,176 out=0 elapsed=35.6s

  [955/15692] intraday_0955.csv.gz  in=172,609,257 out=0 elapsed=35.6s

  [956/15692] intraday_0957.csv.gz  in=172,620,944 out=0 elapsed=35.7s

  [957/15692] intraday_0958.csv.gz  in=172,643,379 out=0 elapsed=35.7s

  [958/15692] intraday_0959.csv.gz  in=172,658,110 out=0 elapsed=35.7s

  [959/15692] intraday_0956.csv.gz  in=172,672,377 out=0 elapsed=35.7s

  [960/15692] intraday_0960.csv.gz  in=172,686,888 out=0 elapsed=35.7s

  [961/15692] intraday_0961.csv.gz  in=172,703,954 out=0 elapsed=35.7s

  [962/15692] intraday_0963.csv.gz  in=172,717,339 out=0 elapsed=35.7s

  [963/15692] intraday_0962.csv.gz  in=172,729,667 out=0 elapsed=35.7s

  [964/15692] intraday_0965.csv.gz  in=172,743,455 out=0 elapsed=35.7s

  [965/15692] intraday_0964.csv.gz  in=172,758,327 out=0 elapsed=35.7s

  [966/15692] intraday_0969.csv.gz  in=172,768,470 out=0 elapsed=35.8s

  [967/15692] intraday_0967.csv.gz  in=172,782,448 out=0 elapsed=35.8s

  [968/15692] intraday_0966.csv.gz  in=172,804,558 out=0 elapsed=35.8s

  [969/15692] intraday_0968.csv.gz  in=172,816,729 out=0 elapsed=35.8s

  [970/15692] intraday_0970.csv.gz  in=172,830,592 out=0 elapsed=35.8s

  [971/15692] intraday_0971.csv.gz  in=172,842,612 out=0 elapsed=35.8s

  [972/15692] intraday_0973.csv.gz  in=172,863,132 out=0 elapsed=35.8s

  [973/15692] intraday_0972.csv.gz  in=172,876,609 out=0 elapsed=35.8s

  [974/15692] intraday_0976.csv.gz  in=172,888,906 out=0 elapsed=35.9s

  [975/15692] intraday_0974.csv.gz  in=172,900,541 out=0 elapsed=35.9s

  [976/15692] intraday_0977.csv.gz  in=172,912,465 out=0 elapsed=35.9s

  [977/15692] intraday_0975.csv.gz  in=172,937,964 out=0 elapsed=35.9s

  [978/15692] intraday_0978.csv.gz  in=172,951,142 out=0 elapsed=35.9s

  [979/15692] intraday_0980.csv.gz  in=172,961,989 out=0 elapsed=35.9s

  [980/15692] intraday_0981.csv.gz  in=172,975,120 out=0 elapsed=35.9s

  [981/15692] intraday_0982.csv.gz  in=172,988,287 out=0 elapsed=35.9s

  [982/15692] intraday_0979.csv.gz  in=173,037,190 out=0 elapsed=35.9s

  [983/15692] intraday_0984.csv.gz  in=173,051,841 out=0 elapsed=36.0s

  [984/15692] intraday_0983.csv.gz  in=173,067,616 out=0 elapsed=36.0s

  [985/15692] intraday_0985.csv.gz  in=173,080,108 out=0 elapsed=36.0s

  [986/15692] intraday_0986.csv.gz  in=173,092,348 out=0 elapsed=36.0s

  [987/15692] intraday_0988.csv.gz  in=173,105,709 out=0 elapsed=36.0s

  [988/15692] intraday_0989.csv.gz  in=173,117,385 out=0 elapsed=36.0s

  [989/15692] intraday_0990.csv.gz  in=173,129,002 out=0 elapsed=36.0s

  [990/15692] intraday_0987.csv.gz  in=173,161,035 out=0 elapsed=36.0s

  [991/15692] intraday_0991.csv.gz  in=173,174,144 out=0 elapsed=36.0s

  [992/15692] intraday_0992.csv.gz  in=173,184,929 out=0 elapsed=36.0s

  [993/15692] intraday_0993.csv.gz  in=173,196,319 out=0 elapsed=36.0s

  [994/15692] intraday_0994.csv.gz  in=173,210,070 out=0 elapsed=36.1s

  [995/15692] intraday_0996.csv.gz  in=173,223,798 out=0 elapsed=36.1s

  [996/15692] intraday_0995.csv.gz  in=173,235,726 out=0 elapsed=36.1s

  [997/15692] intraday_0998.csv.gz  in=173,246,623 out=0 elapsed=36.1s

  [998/15692] intraday_0997.csv.gz  in=173,262,519 out=0 elapsed=36.1s

  [999/15692] intraday_0999.csv.gz  in=173,274,768 out=0 elapsed=36.1s

  [1000/15692] intraday_1000.csv.gz  in=173,287,073 out=0 elapsed=36.1s

  [1001/15692] intraday_10003.csv.gz  in=173,299,980 out=12,907 elapsed=36.2s

  [1002/15692] intraday_10000.csv.gz  in=173,311,314 out=23,741 elapsed=36.2s

  [1003/15692] intraday_10001.csv.gz  in=173,325,009 out=37,436 elapsed=36.2s

  [1004/15692] intraday_10002.csv.gz  in=173,337,308 out=49,735 elapsed=36.2s

  [1005/15692] intraday_10005.csv.gz  in=173,351,663 out=64,090 elapsed=36.2s

  [1006/15692] intraday_10004.csv.gz  in=173,368,716 out=81,143 elapsed=36.2s

  [1007/15692] intraday_10006.csv.gz  in=173,387,818 out=100,245 elapsed=36.2s

  [1008/15692] intraday_10007.csv.gz  in=173,403,189 out=115,616 elapsed=36.2s

  [1009/15692] intraday_10008.csv.gz  in=173,416,844 out=129,271 elapsed=36.3s

  [1010/15692] intraday_10010.csv.gz  in=173,429,394 out=141,821 elapsed=36.3s

  [1011/15692] intraday_1001.csv.gz  in=173,444,887 out=141,821 elapsed=36.3s

  [1012/15692] intraday_10009.csv.gz  in=173,457,751 out=154,685 elapsed=36.3s

  [1013/15692] intraday_10011.csv.gz  in=173,468,274 out=165,208 elapsed=36.3s

  [1014/15692] intraday_10012.csv.gz  in=173,481,818 out=178,752 elapsed=36.3s

  [1015/15692] intraday_10014.csv.gz  in=173,496,316 out=193,250 elapsed=36.3s

  [1016/15692] intraday_10013.csv.gz  in=173,506,755 out=203,689 elapsed=36.3s

  [1017/15692] intraday_10015.csv.gz  in=173,520,633 out=217,567 elapsed=36.4s

  [1018/15692] intraday_10016.csv.gz  in=173,536,910 out=233,844 elapsed=36.4s

  [1019/15692] intraday_10018.csv.gz  in=173,547,792 out=244,726 elapsed=36.4s

  [1020/15692] intraday_10017.csv.gz  in=173,559,020 out=255,954 elapsed=36.4s

  [1021/15692] intraday_1002.csv.gz  in=173,571,034 out=255,954 elapsed=36.4s

  [1022/15692] intraday_10019.csv.gz  in=173,584,284 out=269,204 elapsed=36.4s

  [1023/15692] intraday_10020.csv.gz  in=173,596,447 out=281,367 elapsed=36.4s

  [1024/15692] intraday_10021.csv.gz  in=173,606,839 out=291,759 elapsed=36.4s

  [1025/15692] intraday_10022.csv.gz  in=173,622,477 out=307,397 elapsed=36.5s

  [1026/15692] intraday_10024.csv.gz  in=173,635,987 out=320,907 elapsed=36.5s

  [1027/15692] intraday_10023.csv.gz  in=173,650,340 out=335,260 elapsed=36.5s

  [1028/15692] intraday_10025.csv.gz  in=173,666,792 out=351,712 elapsed=36.5s

  [1029/15692] intraday_10026.csv.gz  in=173,678,186 out=363,106 elapsed=36.5s

  [1030/15692] intraday_10028.csv.gz  in=173,691,132 out=376,052 elapsed=36.5s

  [1031/15692] intraday_10027.csv.gz  in=173,702,370 out=387,290 elapsed=36.5s

  [1032/15692] intraday_10029.csv.gz  in=173,713,343 out=398,263 elapsed=36.5s

  [1033/15692] intraday_1003.csv.gz  in=173,724,417 out=398,263 elapsed=36.5s

  [1034/15692] intraday_10031.csv.gz  in=173,732,382 out=406,228 elapsed=36.5s

  [1035/15692] intraday_10030.csv.gz  in=173,745,417 out=419,263 elapsed=36.5s

  [1036/15692] intraday_10032.csv.gz  in=173,756,598 out=430,444 elapsed=36.6s

  [1037/15692] intraday_10033.csv.gz  in=173,765,209 out=439,055 elapsed=36.6s

  [1038/15692] intraday_10036.csv.gz  in=173,776,976 out=450,822 elapsed=36.6s

  [1039/15692] intraday_10034.csv.gz  in=173,791,760 out=465,606 elapsed=36.6s

  [1040/15692] intraday_10035.csv.gz  in=173,803,469 out=477,315 elapsed=36.6s

  [1041/15692] intraday_10037.csv.gz  in=173,813,914 out=487,760 elapsed=36.6s

  [1042/15692] intraday_10038.csv.gz  in=173,825,913 out=499,759 elapsed=36.6s

  [1043/15692] intraday_1004.csv.gz  in=173,840,091 out=499,759 elapsed=36.6s

  [1044/15692] intraday_10039.csv.gz  in=173,855,224 out=514,892 elapsed=36.6s

  [1045/15692] intraday_10041.csv.gz  in=173,866,003 out=525,671 elapsed=36.6s

  [1046/15692] intraday_10040.csv.gz  in=173,880,973 out=540,641 elapsed=36.6s

  [1047/15692] intraday_10042.csv.gz  in=173,895,383 out=554,849 elapsed=36.7s

  [1048/15692] intraday_10043.csv.gz  in=173,909,948 out=569,414 elapsed=36.7s

  [1049/15692] intraday_10044.csv.gz  in=173,922,978 out=582,444 elapsed=36.7s

  [1050/15692] intraday_10045.csv.gz  in=173,934,968 out=594,434 elapsed=36.7s

  [1051/15692] intraday_10046.csv.gz  in=173,948,577 out=608,043 elapsed=36.7s

  [1052/15692] intraday_10048.csv.gz  in=173,959,002 out=618,468 elapsed=36.7s

  [1053/15692] intraday_10047.csv.gz  in=173,972,289 out=631,755 elapsed=36.7s

  [1054/15692] intraday_10049.csv.gz  in=173,983,878 out=643,344 elapsed=36.7s

  [1055/15692] intraday_10050.csv.gz  in=173,994,883 out=654,349 elapsed=36.7s

  [1056/15692] intraday_1005.csv.gz  in=174,007,014 out=654,349 elapsed=36.7s

  [1057/15692] intraday_10051.csv.gz  in=174,022,551 out=669,886 elapsed=36.7s

  [1058/15692] intraday_10053.csv.gz  in=174,033,357 out=680,692 elapsed=36.8s

  [1059/15692] intraday_10052.csv.gz  in=174,044,240 out=691,575 elapsed=36.8s

  [1060/15692] intraday_10054.csv.gz  in=174,056,999 out=704,334 elapsed=36.8s

  [1061/15692] intraday_10055.csv.gz  in=174,070,268 out=717,603 elapsed=36.8s

  [1062/15692] intraday_10056.csv.gz  in=174,084,047 out=731,382 elapsed=36.8s

  [1063/15692] intraday_10057.csv.gz  in=174,096,010 out=743,345 elapsed=36.8s

  [1064/15692] intraday_10058.csv.gz  in=174,110,134 out=757,469 elapsed=36.8s

  [1065/15692] intraday_1006.csv.gz  in=174,121,727 out=757,469 elapsed=36.9s

  [1066/15692] intraday_10059.csv.gz  in=174,135,744 out=770,068 elapsed=36.9s

  [1067/15692] intraday_10061.csv.gz  in=174,146,884 out=781,208 elapsed=36.9s

  [1068/15692] intraday_10062.csv.gz  in=174,157,096 out=791,420 elapsed=36.9s

  [1069/15692] intraday_10060.csv.gz  in=174,169,216 out=803,540 elapsed=36.9s

  [1070/15692] intraday_10063.csv.gz  in=174,182,840 out=817,164 elapsed=36.9s

  [1071/15692] intraday_10064.csv.gz  in=174,196,788 out=831,112 elapsed=36.9s

  [1072/15692] intraday_10067.csv.gz  in=174,207,997 out=842,321 elapsed=37.0s

  [1073/15692] intraday_10065.csv.gz  in=174,222,754 out=857,078 elapsed=37.0s

  [1074/15692] intraday_10066.csv.gz  in=174,240,135 out=870,670 elapsed=37.0s

  [1075/15692] intraday_10069.csv.gz  in=174,254,067 out=884,602 elapsed=37.0s

  [1076/15692] intraday_1007.csv.gz  in=174,265,808 out=884,602 elapsed=37.0s

  [1077/15692] intraday_10068.csv.gz  in=174,277,560 out=896,354 elapsed=37.0s

  [1078/15692] intraday_10070.csv.gz  in=174,288,874 out=907,668 elapsed=37.0s

  [1079/15692] intraday_10072.csv.gz  in=174,299,755 out=918,549 elapsed=37.0s

  [1080/15692] intraday_10071.csv.gz  in=174,313,102 out=931,896 elapsed=37.1s

  [1081/15692] intraday_10074.csv.gz  in=174,324,859 out=943,653 elapsed=37.1s

  [1082/15692] intraday_10075.csv.gz  in=174,336,808 out=955,602 elapsed=37.1s

  [1083/15692] intraday_10073.csv.gz  in=174,349,131 out=967,925 elapsed=37.1s

  [1084/15692] intraday_10076.csv.gz  in=174,361,949 out=980,743 elapsed=37.1s

  [1085/15692] intraday_10077.csv.gz  in=174,374,462 out=993,256 elapsed=37.1s

  [1086/15692] intraday_10078.csv.gz  in=174,386,686 out=1,005,480 elapsed=37.1s

  [1087/15692] intraday_10079.csv.gz  in=174,400,188 out=1,018,982 elapsed=37.2s

  [1088/15692] intraday_1008.csv.gz  in=174,412,772 out=1,018,982 elapsed=37.2s

  [1089/15692] intraday_10081.csv.gz  in=174,424,006 out=1,030,216 elapsed=37.2s

  [1090/15692] intraday_10080.csv.gz  in=174,435,760 out=1,041,970 elapsed=37.2s

  [1091/15692] intraday_10083.csv.gz  in=174,446,972 out=1,053,182 elapsed=37.2s

  [1092/15692] intraday_10082.csv.gz  in=174,459,564 out=1,065,774 elapsed=37.2s

  [1093/15692] intraday_10084.csv.gz  in=174,470,737 out=1,076,947 elapsed=37.2s

  [1094/15692] intraday_10085.csv.gz  in=174,482,074 out=1,088,284 elapsed=37.2s

  [1095/15692] intraday_10086.csv.gz  in=174,495,205 out=1,100,782 elapsed=37.2s

  [1096/15692] intraday_10087.csv.gz  in=174,507,203 out=1,112,549 elapsed=37.3s

  [1097/15692] intraday_10088.csv.gz  in=174,523,964 out=1,128,383 elapsed=37.3s

  [1098/15692] intraday_1009.csv.gz  in=174,536,451 out=1,128,383 elapsed=37.3s

  [1099/15692] intraday_10089.csv.gz  in=174,548,204 out=1,140,136 elapsed=37.3s

  [1100/15692] intraday_10090.csv.gz  in=174,560,505 out=1,152,437 elapsed=37.3s

  [1101/15692] intraday_10092.csv.gz  in=174,572,076 out=1,164,008 elapsed=37.3s

  [1102/15692] intraday_10091.csv.gz  in=174,591,151 out=1,179,538 elapsed=37.4s

  [1103/15692] intraday_10093.csv.gz  in=174,602,807 out=1,191,194 elapsed=37.4s

  [1104/15692] intraday_10094.csv.gz  in=174,615,731 out=1,203,737 elapsed=37.4s

  [1105/15692] intraday_10095.csv.gz  in=174,627,995 out=1,216,001 elapsed=37.4s

  [1106/15692] intraday_10097.csv.gz  in=174,640,798 out=1,228,804 elapsed=37.4s

  [1107/15692] intraday_10098.csv.gz  in=174,652,519 out=1,240,525 elapsed=37.4s

  [1108/15692] intraday_10096.csv.gz  in=174,664,516 out=1,252,522 elapsed=37.4s

  [1109/15692] intraday_10099.csv.gz  in=174,674,900 out=1,262,906 elapsed=37.4s

  [1110/15692] intraday_1010.csv.gz  in=174,686,259 out=1,262,906 elapsed=37.4s

  [1111/15692] intraday_10100.csv.gz  in=174,701,061 out=1,277,708 elapsed=37.5s

  [1112/15692] intraday_10101.csv.gz  in=174,712,971 out=1,289,618 elapsed=37.5s

  [1113/15692] intraday_10102.csv.gz  in=174,727,209 out=1,303,856 elapsed=37.5s

  [1114/15692] intraday_10103.csv.gz  in=174,744,186 out=1,319,141 elapsed=37.5s

  [1115/15692] intraday_10104.csv.gz  in=174,757,104 out=1,332,059 elapsed=37.5s

  [1116/15692] intraday_10105.csv.gz  in=174,766,605 out=1,341,560 elapsed=37.5s

  [1117/15692] intraday_10106.csv.gz  in=174,779,150 out=1,354,105 elapsed=37.5s

  [1118/15692] intraday_10108.csv.gz  in=174,792,887 out=1,367,842 elapsed=37.6s

  [1119/15692] intraday_10109.csv.gz  in=174,806,420 out=1,381,375 elapsed=37.6s

  [1120/15692] intraday_1011.csv.gz  in=174,820,435 out=1,381,375 elapsed=37.6s

  [1121/15692] intraday_10107.csv.gz  in=174,832,910 out=1,393,850 elapsed=37.6s

  [1122/15692] intraday_10111.csv.gz  in=174,843,441 out=1,404,381 elapsed=37.6s

  [1123/15692] intraday_10110.csv.gz  in=174,856,747 out=1,417,687 elapsed=37.6s

  [1124/15692] intraday_10112.csv.gz  in=174,869,634 out=1,430,574 elapsed=37.6s

  [1125/15692] intraday_10113.csv.gz  in=174,880,777 out=1,441,717 elapsed=37.6s

  [1126/15692] intraday_10114.csv.gz  in=174,892,709 out=1,453,649 elapsed=37.6s

  [1127/15692] intraday_10115.csv.gz  in=174,904,120 out=1,465,060 elapsed=37.7s

  [1128/15692] intraday_10116.csv.gz  in=174,913,540 out=1,474,480 elapsed=37.7s

  [1129/15692] intraday_10117.csv.gz  in=174,924,577 out=1,485,517 elapsed=37.7s

  [1130/15692] intraday_10118.csv.gz  in=174,937,686 out=1,498,626 elapsed=37.7s

  [1131/15692] intraday_1012.csv.gz  in=174,950,266 out=1,498,626 elapsed=37.7s

  [1132/15692] intraday_10119.csv.gz  in=174,967,732 out=1,516,092 elapsed=37.7s

  [1133/15692] intraday_10120.csv.gz  in=174,980,833 out=1,529,193 elapsed=37.7s

  [1134/15692] intraday_10122.csv.gz  in=174,995,610 out=1,541,750 elapsed=37.8s

  [1135/15692] intraday_10121.csv.gz  in=175,008,191 out=1,554,331 elapsed=37.8s

  [1136/15692] intraday_10123.csv.gz  in=175,023,118 out=1,569,258 elapsed=37.8s

  [1137/15692] intraday_10124.csv.gz  in=175,035,241 out=1,581,381 elapsed=37.8s

  [1138/15692] intraday_10127.csv.gz  in=175,047,098 out=1,593,238 elapsed=37.8s

  [1139/15692] intraday_10125.csv.gz  in=175,062,703 out=1,608,843 elapsed=37.8s

  [1140/15692] intraday_10126.csv.gz  in=175,073,360 out=1,619,500 elapsed=37.8s

  [1141/15692] intraday_10128.csv.gz  in=175,086,727 out=1,632,867 elapsed=37.9s

  [1142/15692] intraday_10129.csv.gz  in=175,100,187 out=1,646,327 elapsed=37.9s

  [1143/15692] intraday_1013.csv.gz  in=175,111,971 out=1,646,327 elapsed=37.9s

  [1144/15692] intraday_10130.csv.gz  in=175,124,483 out=1,658,839 elapsed=37.9s

  [1145/15692] intraday_10131.csv.gz  in=175,136,810 out=1,671,166 elapsed=37.9s

  [1146/15692] intraday_10132.csv.gz  in=175,149,729 out=1,684,085 elapsed=37.9s

  [1147/15692] intraday_10133.csv.gz  in=175,161,959 out=1,696,315 elapsed=37.9s

  [1148/15692] intraday_10134.csv.gz  in=175,174,754 out=1,709,110 elapsed=37.9s

  [1149/15692] intraday_10135.csv.gz  in=175,187,272 out=1,721,628 elapsed=37.9s

  [1150/15692] intraday_10136.csv.gz  in=175,198,152 out=1,732,508 elapsed=38.0s

  [1151/15692] intraday_10137.csv.gz  in=175,210,624 out=1,744,980 elapsed=38.0s

  [1152/15692] intraday_10138.csv.gz  in=175,224,341 out=1,758,697 elapsed=38.0s

  [1153/15692] intraday_1014.csv.gz  in=175,236,763 out=1,758,697 elapsed=38.0s

  [1154/15692] intraday_10139.csv.gz  in=175,250,734 out=1,772,668 elapsed=38.0s

  [1155/15692] intraday_10140.csv.gz  in=175,263,520 out=1,785,454 elapsed=38.0s

  [1156/15692] intraday_10141.csv.gz  in=175,274,722 out=1,796,656 elapsed=38.0s

  [1157/15692] intraday_10144.csv.gz  in=175,277,323 out=1,799,257 elapsed=38.0s

  [1158/15692] intraday_10142.csv.gz  in=175,292,025 out=1,813,959 elapsed=38.0s

  [1159/15692] intraday_10143.csv.gz  in=175,304,744 out=1,826,678 elapsed=38.0s

  [1160/15692] intraday_10146.csv.gz  in=175,385,002 out=1,906,936 elapsed=38.3s

  [1161/15692] intraday_10145.csv.gz  in=175,488,143 out=2,010,077 elapsed=38.3s

  [1162/15692] intraday_10148.csv.gz  in=175,556,139 out=2,078,073 elapsed=38.3s

  [1163/15692] intraday_10147.csv.gz  in=175,646,836 out=2,168,770 elapsed=38.3s

  [1164/15692] intraday_1015.csv.gz  in=175,658,448 out=2,168,770 elapsed=38.3s

  [1165/15692] intraday_10149.csv.gz  in=175,742,690 out=2,253,012 elapsed=38.5s

  [1166/15692] intraday_10152.csv.gz  in=175,824,633 out=2,334,955 elapsed=38.5s

  [1167/15692] intraday_10151.csv.gz  in=175,929,301 out=2,439,623 elapsed=38.5s

  [1168/15692] intraday_10150.csv.gz  in=176,024,115 out=2,534,437 elapsed=38.5s

  [1169/15692] intraday_10156.csv.gz  in=176,100,901 out=2,611,223 elapsed=38.7s

  [1170/15692] intraday_10153.csv.gz  in=176,183,637 out=2,693,959 elapsed=38.7s

  [1171/15692] intraday_10154.csv.gz  in=176,279,426 out=2,789,748 elapsed=38.7s

  [1172/15692] intraday_10155.csv.gz  in=176,368,566 out=2,878,888 elapsed=38.7s

  [1173/15692] intraday_1016.csv.gz  in=176,378,774 out=2,878,888 elapsed=38.7s

  [1174/15692] intraday_10159.csv.gz  in=176,458,154 out=2,958,252 elapsed=38.8s

  [1175/15692] intraday_10158.csv.gz  in=176,560,618 out=3,056,467 elapsed=38.8s

  [1176/15692] intraday_10160.csv.gz  in=176,638,109 out=3,133,958 elapsed=38.9s

  [1177/15692] intraday_10157.csv.gz  in=176,745,607 out=3,237,344 elapsed=38.9s

  [1178/15692] intraday_10161.csv.gz  in=176,836,371 out=3,325,382 elapsed=38.9s

  [1179/15692] intraday_10162.csv.gz  in=176,935,275 out=3,424,286 elapsed=39.0s

  [1180/15692] intraday_10163.csv.gz  in=177,018,870 out=3,507,881 elapsed=39.1s

  [1181/15692] intraday_10164.csv.gz  in=177,097,805 out=3,586,816 elapsed=39.1s

  [1182/15692] intraday_10165.csv.gz  in=177,173,337 out=3,662,348 elapsed=39.1s

  [1183/15692] intraday_10166.csv.gz  in=177,271,566 out=3,760,577 elapsed=39.1s

  [1184/15692] intraday_1017.csv.gz  in=177,285,786 out=3,760,577 elapsed=39.2s

  [1185/15692] intraday_10168.csv.gz  in=177,375,930 out=3,850,721 elapsed=39.2s

  [1186/15692] intraday_10167.csv.gz  in=177,465,071 out=3,939,738 elapsed=39.3s

  [1187/15692] intraday_10169.csv.gz  in=177,556,583 out=4,031,250 elapsed=39.3s

  [1188/15692] intraday_10170.csv.gz  in=177,640,495 out=4,115,162 elapsed=39.3s

  [1189/15692] intraday_10171.csv.gz  in=177,737,143 out=4,208,314 elapsed=39.4s

  [1190/15692] intraday_10172.csv.gz  in=177,823,374 out=4,294,154 elapsed=39.4s

  [1191/15692] intraday_10173.csv.gz  in=177,892,985 out=4,363,765 elapsed=39.4s

  [1192/15692] intraday_10174.csv.gz  in=177,987,050 out=4,457,830 elapsed=39.4s

  [1193/15692] intraday_10176.csv.gz  in=178,085,007 out=4,555,787 elapsed=39.6s

  [1194/15692] intraday_10175.csv.gz  in=178,200,006 out=4,670,786 elapsed=39.6s

  [1195/15692] intraday_10177.csv.gz  in=178,273,362 out=4,742,610 elapsed=39.6s

  [1196/15692] intraday_10178.csv.gz  in=178,347,875 out=4,817,123 elapsed=39.6s

  [1197/15692] intraday_1018.csv.gz  in=178,359,259 out=4,817,123 elapsed=39.6s

  [1198/15692] intraday_10179.csv.gz  in=178,443,812 out=4,901,676 elapsed=39.8s

  [1199/15692] intraday_10180.csv.gz  in=178,531,134 out=4,988,998 elapsed=39.8s

  [1200/15692] intraday_10181.csv.gz  in=178,609,433 out=5,067,297 elapsed=39.8s

  [1201/15692] intraday_10182.csv.gz  in=178,706,787 out=5,161,963 elapsed=39.8s

  [1202/15692] intraday_10184.csv.gz  in=178,780,958 out=5,236,134 elapsed=40.0s

  [1203/15692] intraday_10183.csv.gz  in=178,856,302 out=5,311,478 elapsed=40.0s

  [1204/15692] intraday_10186.csv.gz  in=178,945,382 out=5,399,725 elapsed=40.0s

  [1205/15692] intraday_10185.csv.gz  in=179,030,280 out=5,481,447 elapsed=40.0s

  [1206/15692] intraday_10187.csv.gz  in=179,118,921 out=5,569,043 elapsed=40.1s

  [1207/15692] intraday_1019.csv.gz  in=179,132,835 out=5,569,043 elapsed=40.1s

  [1208/15692] intraday_10188.csv.gz  in=179,215,109 out=5,651,317 elapsed=40.1s

  [1209/15692] intraday_10191.csv.gz  in=179,288,085 out=5,724,293 elapsed=40.2s

  [1210/15692] intraday_10189.csv.gz  in=179,379,070 out=5,815,278 elapsed=40.2s

  [1211/15692] intraday_10190.csv.gz  in=179,477,175 out=5,913,383 elapsed=40.3s

  [1212/15692] intraday_10192.csv.gz  in=179,558,761 out=5,994,969 elapsed=40.3s

  [1213/15692] intraday_10193.csv.gz  in=179,641,608 out=6,077,816 elapsed=40.3s

  [1214/15692] intraday_10194.csv.gz  in=179,714,178 out=6,150,386 elapsed=40.3s

  [1215/15692] intraday_10196.csv.gz  in=179,790,420 out=6,226,628 elapsed=40.4s

  [1216/15692] intraday_10195.csv.gz  in=179,873,334 out=6,309,542 elapsed=40.4s

  [1217/15692] intraday_10197.csv.gz  in=179,953,755 out=6,387,509 elapsed=40.4s

  [1218/15692] intraday_1020.csv.gz  in=179,967,131 out=6,387,509 elapsed=40.4s

  [1219/15692] intraday_10198.csv.gz  in=180,063,082 out=6,482,422 elapsed=40.5s

  [1220/15692] intraday_10200.csv.gz  in=180,140,224 out=6,559,564 elapsed=40.6s

  [1221/15692] intraday_10199.csv.gz  in=180,219,078 out=6,638,418 elapsed=40.6s

  [1222/15692] intraday_10201.csv.gz  in=180,320,540 out=6,739,880 elapsed=40.6s

  [1223/15692] intraday_10202.csv.gz  in=180,404,680 out=6,824,020 elapsed=40.6s

  [1224/15692] intraday_10203.csv.gz  in=180,483,278 out=6,902,245 elapsed=40.7s

  [1225/15692] intraday_10204.csv.gz  in=180,560,584 out=6,979,551 elapsed=40.7s

  [1226/15692] intraday_10205.csv.gz  in=180,648,610 out=7,067,577 elapsed=40.8s

  [1227/15692] intraday_10206.csv.gz  in=180,725,971 out=7,144,938 elapsed=40.8s

  [1228/15692] intraday_10207.csv.gz  in=180,799,011 out=7,217,978 elapsed=40.8s

  [1229/15692] intraday_1021.csv.gz  in=180,812,113 out=7,217,978 elapsed=40.8s

  [1230/15692] intraday_10208.csv.gz  in=180,899,720 out=7,305,585 elapsed=40.8s

  [1231/15692] intraday_10209.csv.gz  in=180,978,301 out=7,384,166 elapsed=40.9s

  [1232/15692] intraday_10210.csv.gz  in=181,052,594 out=7,458,459 elapsed=40.9s

  [1233/15692] intraday_10212.csv.gz  in=181,146,612 out=7,552,150 elapsed=41.0s

  [1234/15692] intraday_10211.csv.gz  in=181,261,979 out=7,667,517 elapsed=41.0s

  [1235/15692] intraday_10214.csv.gz  in=181,341,598 out=7,747,136 elapsed=41.1s

  [1236/15692] intraday_10213.csv.gz  in=181,443,640 out=7,849,178 elapsed=41.1s

  [1237/15692] intraday_10216.csv.gz  in=181,516,004 out=7,921,421 elapsed=41.1s

  [1238/15692] intraday_10215.csv.gz  in=181,611,320 out=8,015,621 elapsed=41.1s

  [1239/15692] intraday_1022.csv.gz  in=181,622,050 out=8,015,621 elapsed=41.2s

  [1240/15692] intraday_10217.csv.gz  in=181,714,724 out=8,108,295 elapsed=41.3s

  [1241/15692] intraday_10218.csv.gz  in=181,795,908 out=8,189,479 elapsed=41.3s

  [1242/15692] intraday_10219.csv.gz  in=181,886,623 out=8,280,194 elapsed=41.3s

  [1243/15692] intraday_10220.csv.gz  in=181,961,528 out=8,355,099 elapsed=41.3s

  [1244/15692] intraday_10221.csv.gz  in=182,062,513 out=8,456,084 elapsed=41.5s

  [1245/15692] intraday_10224.csv.gz  in=182,140,654 out=8,534,225 elapsed=41.5s

  [1246/15692] intraday_10222.csv.gz  in=182,224,046 out=8,617,617 elapsed=41.5s

  [1247/15692] intraday_10223.csv.gz  in=182,318,621 out=8,712,192 elapsed=41.5s

  [1248/15692] intraday_10227.csv.gz  in=182,380,916 out=8,774,487 elapsed=41.6s

  [1249/15692] intraday_10228.csv.gz  in=182,456,171 out=8,849,364 elapsed=41.6s

  [1250/15692] intraday_10226.csv.gz  in=182,533,091 out=8,926,284 elapsed=41.7s

  [1251/15692] intraday_1023.csv.gz  in=182,546,400 out=8,926,284 elapsed=41.7s

  [1252/15692] intraday_10225.csv.gz  in=182,626,752 out=9,006,636 elapsed=41.7s

  [1253/15692] intraday_10229.csv.gz  in=182,716,973 out=9,096,857 elapsed=41.7s

  [1254/15692] intraday_10230.csv.gz  in=182,830,052 out=9,209,936 elapsed=41.9s

  [1255/15692] intraday_10233.csv.gz  in=182,903,084 out=9,282,901 elapsed=41.9s

  [1256/15692] intraday_10231.csv.gz  in=183,018,391 out=9,398,208 elapsed=41.9s

  [1257/15692] intraday_10232.csv.gz  in=183,109,757 out=9,489,574 elapsed=41.9s

  [1258/15692] intraday_10237.csv.gz  in=183,190,108 out=9,569,925 elapsed=42.1s

  [1259/15692] intraday_10235.csv.gz  in=183,278,563 out=9,658,380 elapsed=42.1s

  [1260/15692] intraday_10234.csv.gz  in=183,376,816 out=9,753,769 elapsed=42.1s

  [1261/15692] intraday_10236.csv.gz  in=183,482,340 out=9,859,293 elapsed=42.1s

  [1262/15692] intraday_1024.csv.gz  in=183,494,276 out=9,859,293 elapsed=42.2s

  [1263/15692] intraday_10238.csv.gz  in=183,575,279 out=9,940,296 elapsed=42.2s

  [1264/15692] intraday_10240.csv.gz  in=183,663,745 out=10,028,762 elapsed=42.3s

  [1265/15692] intraday_10239.csv.gz  in=183,764,000 out=10,129,017 elapsed=42.3s

  [1266/15692] intraday_10241.csv.gz  in=183,855,290 out=10,219,941 elapsed=42.3s

  [1267/15692] intraday_10242.csv.gz  in=183,939,998 out=10,304,649 elapsed=42.4s

  [1268/15692] intraday_10243.csv.gz  in=184,027,574 out=10,390,292 elapsed=42.4s

  [1269/15692] intraday_10244.csv.gz  in=184,116,987 out=10,479,705 elapsed=42.5s

  [1270/15692] intraday_10245.csv.gz  in=184,207,182 out=10,569,318 elapsed=42.5s

  [1271/15692] intraday_10246.csv.gz  in=184,301,232 out=10,661,758 elapsed=42.5s

  [1272/15692] intraday_10247.csv.gz  in=184,375,035 out=10,735,561 elapsed=42.5s

  [1273/15692] intraday_10248.csv.gz  in=184,462,634 out=10,823,160 elapsed=42.6s

  [1274/15692] intraday_1025.csv.gz  in=184,497,338 out=10,823,160 elapsed=42.6s

  [1275/15692] intraday_10249.csv.gz  in=184,588,888 out=10,914,710 elapsed=42.6s

  [1276/15692] intraday_10251.csv.gz  in=184,675,075 out=11,000,897 elapsed=42.7s

  [1277/15692] intraday_10250.csv.gz  in=184,770,845 out=11,096,279 elapsed=42.7s

  [1278/15692] intraday_10252.csv.gz  in=184,853,516 out=11,177,879 elapsed=42.7s

  [1279/15692] intraday_10253.csv.gz  in=184,964,671 out=11,289,034 elapsed=42.7s

  [1280/15692] intraday_10254.csv.gz  in=185,043,773 out=11,368,136 elapsed=42.8s

  [1281/15692] intraday_10255.csv.gz  in=185,128,272 out=11,451,102 elapsed=42.8s

  [1282/15692] intraday_10256.csv.gz  in=185,224,692 out=11,547,522 elapsed=42.9s

  [1283/15692] intraday_10257.csv.gz  in=185,323,770 out=11,646,600 elapsed=42.9s

  [1284/15692] intraday_10258.csv.gz  in=185,412,030 out=11,733,697 elapsed=42.9s

  [1285/15692] intraday_1026.csv.gz  in=185,423,611 out=11,733,697 elapsed=42.9s

  [1286/15692] intraday_10259.csv.gz  in=185,518,466 out=11,828,552 elapsed=43.0s

  [1287/15692] intraday_10260.csv.gz  in=185,601,650 out=11,911,736 elapsed=43.0s

  [1288/15692] intraday_10262.csv.gz  in=185,700,856 out=12,010,942 elapsed=43.1s

  [1289/15692] intraday_10261.csv.gz  in=185,785,713 out=12,095,673 elapsed=43.1s

  [1290/15692] intraday_10263.csv.gz  in=185,902,292 out=12,212,252 elapsed=43.1s

  [1291/15692] intraday_10264.csv.gz  in=186,037,542 out=12,347,502 elapsed=43.2s

  [1292/15692] intraday_10265.csv.gz  in=186,141,184 out=12,451,144 elapsed=43.3s

  [1293/15692] intraday_10267.csv.gz  in=186,217,116 out=12,527,076 elapsed=43.3s

  [1294/15692] intraday_10266.csv.gz  in=186,315,554 out=12,625,514 elapsed=43.3s

  [1295/15692] intraday_1027.csv.gz  in=186,327,889 out=12,625,514 elapsed=43.3s

  [1296/15692] intraday_10268.csv.gz  in=186,419,031 out=12,716,391 elapsed=43.4s

  [1297/15692] intraday_10269.csv.gz  in=186,494,597 out=12,791,957 elapsed=43.4s

  [1298/15692] intraday_10271.csv.gz  in=186,567,903 out=12,865,263 elapsed=43.4s

  [1299/15692] intraday_10270.csv.gz  in=186,670,937 out=12,968,297 elapsed=43.5s

  [1300/15692] intraday_10272.csv.gz  in=186,765,380 out=13,062,740 elapsed=43.5s

  [1301/15692] intraday_10273.csv.gz  in=186,856,537 out=13,153,897 elapsed=43.5s

  [1302/15692] intraday_10275.csv.gz  in=186,930,292 out=13,227,652 elapsed=43.6s

  [1303/15692] intraday_10274.csv.gz  in=187,041,830 out=13,339,190 elapsed=43.6s

  [1304/15692] intraday_10276.csv.gz  in=187,124,059 out=13,421,419 elapsed=43.7s

  [1305/15692] intraday_10277.csv.gz  in=187,202,004 out=13,499,364 elapsed=43.7s

  [1306/15692] intraday_1028.csv.gz  in=187,213,776 out=13,499,364 elapsed=43.7s

  [1307/15692] intraday_10278.csv.gz  in=187,304,715 out=13,590,303 elapsed=43.7s

  [1308/15692] intraday_10279.csv.gz  in=187,386,833 out=13,672,299 elapsed=43.7s

  [1309/15692] intraday_10280.csv.gz  in=187,484,710 out=13,770,176 elapsed=43.8s

  [1310/15692] intraday_10281.csv.gz  in=187,595,459 out=13,878,607 elapsed=43.8s

  [1311/15692] intraday_10283.csv.gz  in=187,703,816 out=13,986,964 elapsed=43.9s

  [1312/15692] intraday_10282.csv.gz  in=187,797,424 out=14,080,572 elapsed=43.9s

  [1313/15692] intraday_10285.csv.gz  in=187,885,609 out=14,168,757 elapsed=43.9s

  [1314/15692] intraday_10284.csv.gz  in=187,959,414 out=14,242,562 elapsed=43.9s

  [1315/15692] intraday_10286.csv.gz  in=188,056,973 out=14,339,734 elapsed=44.0s

  [1316/15692] intraday_10287.csv.gz  in=188,133,461 out=14,416,222 elapsed=44.0s

  [1317/15692] intraday_10289.csv.gz  in=188,195,005 out=14,472,894 elapsed=44.1s

  [1318/15692] intraday_10288.csv.gz  in=188,309,832 out=14,576,044 elapsed=44.1s

  [1319/15692] intraday_1029.csv.gz  in=188,321,560 out=14,576,044 elapsed=44.1s

  [1320/15692] intraday_10293.csv.gz  in=188,333,618 out=14,588,102 elapsed=44.1s

  [1321/15692] intraday_10292.csv.gz  in=188,347,682 out=14,602,166 elapsed=44.1s

  [1322/15692] intraday_10290.csv.gz  in=188,427,852 out=14,682,336 elapsed=44.2s

  [1323/15692] intraday_10291.csv.gz  in=188,496,204 out=14,750,688 elapsed=44.2s

  [1324/15692] intraday_10295.csv.gz  in=188,506,119 out=14,760,603 elapsed=44.2s

  [1325/15692] intraday_10294.csv.gz  in=188,521,614 out=14,776,098 elapsed=44.2s

  [1326/15692] intraday_10298.csv.gz  in=188,534,542 out=14,789,026 elapsed=44.2s

  [1327/15692] intraday_10299.csv.gz  in=188,544,804 out=14,799,288 elapsed=44.2s

  [1328/15692] intraday_1030.csv.gz  in=188,556,844 out=14,799,288 elapsed=44.2s

  [1329/15692] intraday_10297.csv.gz  in=188,570,316 out=14,812,760 elapsed=44.2s

  [1330/15692] intraday_10296.csv.gz  in=188,581,890 out=14,824,334 elapsed=44.2s

  [1331/15692] intraday_10302.csv.gz  in=188,593,559 out=14,836,003 elapsed=44.3s

  [1332/15692] intraday_10301.csv.gz  in=188,607,231 out=14,849,675 elapsed=44.3s

  [1333/15692] intraday_10303.csv.gz  in=188,618,069 out=14,860,513 elapsed=44.3s

  [1334/15692] intraday_10304.csv.gz  in=188,630,492 out=14,872,936 elapsed=44.3s

  [1335/15692] intraday_10305.csv.gz  in=188,643,710 out=14,886,154 elapsed=44.3s

  [1336/15692] intraday_10300.csv.gz  in=188,655,133 out=14,897,577 elapsed=44.3s

  [1337/15692] intraday_10306.csv.gz  in=188,664,538 out=14,906,982 elapsed=44.4s

  [1338/15692] intraday_10307.csv.gz  in=188,675,244 out=14,917,688 elapsed=44.4s

  [1339/15692] intraday_10308.csv.gz  in=188,688,056 out=14,930,500 elapsed=44.4s

  [1340/15692] intraday_10309.csv.gz  in=188,701,110 out=14,943,554 elapsed=44.4s

  [1341/15692] intraday_10310.csv.gz  in=188,712,825 out=14,955,269 elapsed=44.4s

  [1342/15692] intraday_1031.csv.gz  in=188,732,815 out=14,955,269 elapsed=44.4s

  [1343/15692] intraday_10312.csv.gz  in=188,743,776 out=14,966,230 elapsed=44.4s

  [1344/15692] intraday_10314.csv.gz  in=188,756,248 out=14,978,702 elapsed=44.5s

  [1345/15692] intraday_10313.csv.gz  in=188,769,677 out=14,992,131 elapsed=44.5s

  [1346/15692] intraday_10311.csv.gz  in=188,780,661 out=15,003,115 elapsed=44.5s

  [1347/15692] intraday_10315.csv.gz  in=188,792,750 out=15,015,204 elapsed=44.5s

  [1348/15692] intraday_10316.csv.gz  in=188,804,444 out=15,026,898 elapsed=44.5s

  [1349/15692] intraday_10318.csv.gz  in=188,815,691 out=15,038,145 elapsed=44.5s

  [1350/15692] intraday_10317.csv.gz  in=188,826,476 out=15,048,930 elapsed=44.5s

  [1351/15692] intraday_10319.csv.gz  in=188,837,841 out=15,060,295 elapsed=44.5s

  [1352/15692] intraday_1032.csv.gz  in=188,847,949 out=15,060,295 elapsed=44.5s

  [1353/15692] intraday_10320.csv.gz  in=188,858,824 out=15,071,170 elapsed=44.5s

  [1354/15692] intraday_10324.csv.gz  in=188,868,377 out=15,080,723 elapsed=44.6s

  [1355/15692] intraday_10323.csv.gz  in=188,882,822 out=15,094,737 elapsed=44.6s

  [1356/15692] intraday_10322.csv.gz  in=188,897,164 out=15,109,079 elapsed=44.6s

  [1357/15692] intraday_10321.csv.gz  in=188,909,570 out=15,121,485 elapsed=44.6s

  [1358/15692] intraday_10325.csv.gz  in=188,919,534 out=15,131,449 elapsed=44.6s

  [1359/15692] intraday_10328.csv.gz  in=188,930,582 out=15,142,497 elapsed=44.6s

  [1360/15692] intraday_10326.csv.gz  in=188,941,971 out=15,153,886 elapsed=44.7s

  [1361/15692] intraday_1033.csv.gz  in=188,953,516 out=15,153,886 elapsed=44.7s

  [1362/15692] intraday_10327.csv.gz  in=188,965,453 out=15,165,823 elapsed=44.7s

  [1363/15692] intraday_10329.csv.gz  in=188,976,686 out=15,177,056 elapsed=44.7s

  [1364/15692] intraday_10331.csv.gz  in=188,986,530 out=15,186,900 elapsed=44.7s

  [1365/15692] intraday_10330.csv.gz  in=188,996,876 out=15,197,246 elapsed=44.7s

  [1366/15692] intraday_10332.csv.gz  in=189,007,668 out=15,208,038 elapsed=44.7s

  [1367/15692] intraday_10333.csv.gz  in=189,019,146 out=15,219,516 elapsed=44.7s

  [1368/15692] intraday_10334.csv.gz  in=189,032,417 out=15,232,787 elapsed=44.8s

  [1369/15692] intraday_10335.csv.gz  in=189,043,121 out=15,243,491 elapsed=44.8s

  [1370/15692] intraday_10336.csv.gz  in=189,056,271 out=15,256,641 elapsed=44.8s

  [1371/15692] intraday_10337.csv.gz  in=189,069,169 out=15,269,539 elapsed=44.8s

  [1372/15692] intraday_10338.csv.gz  in=189,079,317 out=15,279,687 elapsed=44.8s

  [1373/15692] intraday_1034.csv.gz  in=189,090,714 out=15,279,687 elapsed=44.8s

  [1374/15692] intraday_10339.csv.gz  in=189,104,555 out=15,292,498 elapsed=44.8s

  [1375/15692] intraday_10340.csv.gz  in=189,116,343 out=15,304,286 elapsed=44.8s

  [1376/15692] intraday_10341.csv.gz  in=189,126,157 out=15,314,100 elapsed=44.8s

  [1377/15692] intraday_10342.csv.gz  in=189,137,335 out=15,324,925 elapsed=44.8s

  [1378/15692] intraday_10344.csv.gz  in=189,147,466 out=15,335,056 elapsed=44.9s

  [1379/15692] intraday_10343.csv.gz  in=189,158,176 out=15,345,766 elapsed=44.9s

  [1380/15692] intraday_10345.csv.gz  in=189,170,240 out=15,357,830 elapsed=44.9s

  [1381/15692] intraday_10346.csv.gz  in=189,181,511 out=15,369,101 elapsed=44.9s

  [1382/15692] intraday_10347.csv.gz  in=189,192,631 out=15,380,221 elapsed=44.9s

  [1383/15692] intraday_1035.csv.gz  in=189,207,883 out=15,380,221 elapsed=44.9s

  [1384/15692] intraday_10348.csv.gz  in=189,219,920 out=15,392,258 elapsed=44.9s

  [1385/15692] intraday_10350.csv.gz  in=189,231,225 out=15,403,563 elapsed=44.9s

  [1386/15692] intraday_10349.csv.gz  in=189,242,040 out=15,414,378 elapsed=44.9s

  [1387/15692] intraday_10351.csv.gz  in=189,252,102 out=15,424,440 elapsed=44.9s

  [1388/15692] intraday_10352.csv.gz  in=189,263,616 out=15,435,954 elapsed=45.0s

  [1389/15692] intraday_10353.csv.gz  in=189,273,565 out=15,445,903 elapsed=45.0s

  [1390/15692] intraday_10354.csv.gz  in=189,285,616 out=15,457,954 elapsed=45.0s

  [1391/15692] intraday_10356.csv.gz  in=189,296,147 out=15,468,485 elapsed=45.0s

  [1392/15692] intraday_10355.csv.gz  in=189,308,623 out=15,480,961 elapsed=45.0s

  [1393/15692] intraday_10357.csv.gz  in=189,326,487 out=15,495,561 elapsed=45.0s

  [1394/15692] intraday_10358.csv.gz  in=189,340,638 out=15,509,712 elapsed=45.0s

  [1395/15692] intraday_10359.csv.gz  in=189,353,256 out=15,522,330 elapsed=45.1s

  [1396/15692] intraday_1036.csv.gz  in=189,377,458 out=15,522,330 elapsed=45.1s

  [1397/15692] intraday_10361.csv.gz  in=189,388,983 out=15,533,855 elapsed=45.1s

  [1398/15692] intraday_10360.csv.gz  in=189,402,208 out=15,547,080 elapsed=45.1s

  [1399/15692] intraday_10363.csv.gz  in=189,412,105 out=15,556,977 elapsed=45.1s

  [1400/15692] intraday_10364.csv.gz  in=189,423,082 out=15,567,954 elapsed=45.1s

  [1401/15692] intraday_10362.csv.gz  in=189,434,947 out=15,579,819 elapsed=45.1s

  [1402/15692] intraday_10365.csv.gz  in=189,446,829 out=15,591,701 elapsed=45.1s

  [1403/15692] intraday_10366.csv.gz  in=189,458,931 out=15,603,803 elapsed=45.2s

  [1404/15692] intraday_10367.csv.gz  in=189,471,095 out=15,615,967 elapsed=45.2s

  [1405/15692] intraday_10368.csv.gz  in=189,482,310 out=15,627,182 elapsed=45.2s

  [1406/15692] intraday_10369.csv.gz  in=189,492,194 out=15,637,066 elapsed=45.2s

  [1407/15692] intraday_1037.csv.gz  in=189,504,725 out=15,637,066 elapsed=45.2s

  [1408/15692] intraday_10370.csv.gz  in=189,516,956 out=15,649,297 elapsed=45.2s

  [1409/15692] intraday_10371.csv.gz  in=189,527,614 out=15,659,955 elapsed=45.2s

  [1410/15692] intraday_10373.csv.gz  in=189,538,367 out=15,670,708 elapsed=45.2s

  [1411/15692] intraday_10372.csv.gz  in=189,549,655 out=15,681,996 elapsed=45.3s

  [1412/15692] intraday_10374.csv.gz  in=189,558,451 out=15,690,792 elapsed=45.3s

  [1413/15692] intraday_10375.csv.gz  in=189,568,565 out=15,700,906 elapsed=45.3s

  [1414/15692] intraday_10377.csv.gz  in=189,584,162 out=15,716,503 elapsed=45.3s

  [1415/15692] intraday_10378.csv.gz  in=189,597,764 out=15,730,105 elapsed=45.3s

  [1416/15692] intraday_10376.csv.gz  in=189,609,647 out=15,741,988 elapsed=45.3s

  [1417/15692] intraday_10379.csv.gz  in=189,621,410 out=15,753,751 elapsed=45.3s

  [1418/15692] intraday_1038.csv.gz  in=189,633,115 out=15,753,751 elapsed=45.3s

  [1419/15692] intraday_10380.csv.gz  in=189,642,668 out=15,763,304 elapsed=45.4s

  [1420/15692] intraday_10382.csv.gz  in=189,653,287 out=15,773,923 elapsed=45.4s

  [1421/15692] intraday_10383.csv.gz  in=189,667,071 out=15,787,707 elapsed=45.4s

  [1422/15692] intraday_10381.csv.gz  in=189,680,840 out=15,801,476 elapsed=45.4s

  [1423/15692] intraday_10384.csv.gz  in=189,693,266 out=15,813,902 elapsed=45.4s

  [1424/15692] intraday_10385.csv.gz  in=189,704,206 out=15,824,842 elapsed=45.5s

  [1425/15692] intraday_10387.csv.gz  in=189,717,062 out=15,837,698 elapsed=45.5s

  [1426/15692] intraday_10386.csv.gz  in=189,729,601 out=15,850,237 elapsed=45.5s

  [1427/15692] intraday_10388.csv.gz  in=189,742,115 out=15,862,751 elapsed=45.5s

  [1428/15692] intraday_10389.csv.gz  in=189,753,990 out=15,874,626 elapsed=45.5s

  [1429/15692] intraday_1039.csv.gz  in=189,767,014 out=15,874,626 elapsed=45.5s

  [1430/15692] intraday_10391.csv.gz  in=189,778,092 out=15,885,704 elapsed=45.5s

  [1431/15692] intraday_10390.csv.gz  in=189,790,465 out=15,898,077 elapsed=45.5s

  [1432/15692] intraday_10392.csv.gz  in=189,802,400 out=15,910,012 elapsed=45.6s

  [1433/15692] intraday_10395.csv.gz  in=189,813,850 out=15,921,462 elapsed=45.6s

  [1434/15692] intraday_10393.csv.gz  in=189,826,454 out=15,934,066 elapsed=45.6s

  [1435/15692] intraday_10394.csv.gz  in=189,836,666 out=15,944,278 elapsed=45.6s

  [1436/15692] intraday_10398.csv.gz  in=189,848,428 out=15,956,040 elapsed=45.6s

  [1437/15692] intraday_10396.csv.gz  in=189,861,123 out=15,968,735 elapsed=45.6s

  [1438/15692] intraday_10397.csv.gz  in=189,872,737 out=15,980,349 elapsed=45.6s

  [1439/15692] intraday_10399.csv.gz  in=189,883,013 out=15,990,625 elapsed=45.7s

  [1440/15692] intraday_1040.csv.gz  in=189,895,412 out=15,990,625 elapsed=45.7s

  [1441/15692] intraday_10400.csv.gz  in=189,910,843 out=16,006,056 elapsed=45.7s

  [1442/15692] intraday_10402.csv.gz  in=189,922,519 out=16,017,732 elapsed=45.7s

  [1443/15692] intraday_10401.csv.gz  in=189,931,805 out=16,027,018 elapsed=45.7s

  [1444/15692] intraday_10404.csv.gz  in=189,944,979 out=16,040,192 elapsed=45.7s

  [1445/15692] intraday_10403.csv.gz  in=189,965,299 out=16,059,270 elapsed=45.7s

  [1446/15692] intraday_10405.csv.gz  in=189,975,359 out=16,069,330 elapsed=45.7s

  [1447/15692] intraday_10406.csv.gz  in=189,990,426 out=16,084,397 elapsed=45.7s

  [1448/15692] intraday_10407.csv.gz  in=190,003,378 out=16,097,349 elapsed=45.8s

  [1449/15692] intraday_10408.csv.gz  in=190,014,957 out=16,108,928 elapsed=45.8s

  [1450/15692] intraday_10409.csv.gz  in=190,030,073 out=16,124,044 elapsed=45.8s

  [1451/15692] intraday_1041.csv.gz  in=190,045,358 out=16,124,044 elapsed=45.8s

  [1452/15692] intraday_10410.csv.gz  in=190,060,426 out=16,139,112 elapsed=45.8s

  [1453/15692] intraday_10411.csv.gz  in=190,077,193 out=16,155,879 elapsed=45.8s

  [1454/15692] intraday_10413.csv.gz  in=190,091,156 out=16,169,842 elapsed=45.8s

  [1455/15692] intraday_10412.csv.gz  in=190,105,540 out=16,184,226 elapsed=45.8s

  [1456/15692] intraday_10414.csv.gz  in=190,115,831 out=16,194,517 elapsed=45.8s

  [1457/15692] intraday_10415.csv.gz  in=190,127,352 out=16,206,038 elapsed=45.9s

  [1458/15692] intraday_10418.csv.gz  in=190,138,175 out=16,216,861 elapsed=45.9s

  [1459/15692] intraday_10417.csv.gz  in=190,150,389 out=16,229,075 elapsed=45.9s

  [1460/15692] intraday_10416.csv.gz  in=190,161,069 out=16,239,755 elapsed=45.9s

  [1461/15692] intraday_1042.csv.gz  in=190,173,082 out=16,239,755 elapsed=45.9s

  [1462/15692] intraday_10419.csv.gz  in=190,185,728 out=16,252,401 elapsed=45.9s

  [1463/15692] intraday_10420.csv.gz  in=190,198,732 out=16,265,405 elapsed=45.9s

  [1464/15692] intraday_10421.csv.gz  in=190,212,555 out=16,279,228 elapsed=45.9s

  [1465/15692] intraday_10422.csv.gz  in=190,223,133 out=16,289,806 elapsed=45.9s

  [1466/15692] intraday_10423.csv.gz  in=190,234,082 out=16,300,755 elapsed=46.0s

  [1467/15692] intraday_10426.csv.gz  in=190,244,882 out=16,311,555 elapsed=46.0s

  [1468/15692] intraday_10424.csv.gz  in=190,255,751 out=16,322,424 elapsed=46.0s

  [1469/15692] intraday_10425.csv.gz  in=190,267,065 out=16,333,738 elapsed=46.0s

  [1470/15692] intraday_10427.csv.gz  in=190,281,516 out=16,348,189 elapsed=46.0s

  [1471/15692] intraday_10428.csv.gz  in=190,297,258 out=16,363,931 elapsed=46.0s

  [1472/15692] intraday_1043.csv.gz  in=190,313,311 out=16,363,931 elapsed=46.0s

  [1473/15692] intraday_10429.csv.gz  in=190,326,010 out=16,376,630 elapsed=46.0s

  [1474/15692] intraday_10432.csv.gz  in=190,336,928 out=16,387,548 elapsed=46.1s

  [1475/15692] intraday_10431.csv.gz  in=190,348,032 out=16,398,652 elapsed=46.1s

  [1476/15692] intraday_10433.csv.gz  in=190,360,572 out=16,411,192 elapsed=46.1s

  [1477/15692] intraday_10430.csv.gz  in=190,375,823 out=16,426,443 elapsed=46.1s

  [1478/15692] intraday_10435.csv.gz  in=190,388,411 out=16,439,031 elapsed=46.1s

  [1479/15692] intraday_10434.csv.gz  in=190,398,422 out=16,449,042 elapsed=46.1s

  [1480/15692] intraday_10436.csv.gz  in=190,407,256 out=16,457,876 elapsed=46.1s

  [1481/15692] intraday_10437.csv.gz  in=190,417,986 out=16,468,606 elapsed=46.1s

  [1482/15692] intraday_10438.csv.gz  in=190,426,352 out=16,476,972 elapsed=46.1s

  [1483/15692] intraday_1044.csv.gz  in=190,440,522 out=16,476,972 elapsed=46.2s

  [1484/15692] intraday_10439.csv.gz  in=190,454,999 out=16,491,449 elapsed=46.2s

  [1485/15692] intraday_10440.csv.gz  in=190,467,263 out=16,503,713 elapsed=46.2s

  [1486/15692] intraday_10441.csv.gz  in=190,480,356 out=16,516,806 elapsed=46.2s

  [1487/15692] intraday_10442.csv.gz  in=190,489,830 out=16,526,280 elapsed=46.2s

  [1488/15692] intraday_10443.csv.gz  in=190,501,251 out=16,537,701 elapsed=46.2s

  [1489/15692] intraday_10444.csv.gz  in=190,515,555 out=16,552,005 elapsed=46.2s

  [1490/15692] intraday_10446.csv.gz  in=190,527,314 out=16,563,764 elapsed=46.2s

  [1491/15692] intraday_10447.csv.gz  in=190,538,488 out=16,574,938 elapsed=46.3s

  [1492/15692] intraday_10445.csv.gz  in=190,551,500 out=16,587,950 elapsed=46.3s

  [1493/15692] intraday_10448.csv.gz  in=190,564,926 out=16,601,376 elapsed=46.3s

  [1494/15692] intraday_10449.csv.gz  in=190,579,035 out=16,615,485 elapsed=46.3s

  [1495/15692] intraday_1045.csv.gz  in=190,593,370 out=16,615,485 elapsed=46.3s

  [1496/15692] intraday_10450.csv.gz  in=190,605,078 out=16,627,193 elapsed=46.3s

  [1497/15692] intraday_10451.csv.gz  in=190,617,429 out=16,639,544 elapsed=46.3s

  [1498/15692] intraday_10452.csv.gz  in=190,631,584 out=16,653,699 elapsed=46.4s

  [1499/15692] intraday_10453.csv.gz  in=190,641,555 out=16,663,670 elapsed=46.4s

  [1500/15692] intraday_10454.csv.gz  in=190,651,958 out=16,674,073 elapsed=46.4s

  [1501/15692] intraday_10455.csv.gz  in=190,664,580 out=16,686,695 elapsed=46.4s

  [1502/15692] intraday_10456.csv.gz  in=190,678,423 out=16,700,538 elapsed=46.4s

  [1503/15692] intraday_10457.csv.gz  in=190,690,050 out=16,712,165 elapsed=46.4s

  [1504/15692] intraday_10459.csv.gz  in=190,700,939 out=16,723,054 elapsed=46.4s

  [1505/15692] intraday_10458.csv.gz  in=190,710,999 out=16,733,114 elapsed=46.4s

  [1506/15692] intraday_1046.csv.gz  in=190,723,721 out=16,733,114 elapsed=46.5s

  [1507/15692] intraday_10461.csv.gz  in=190,735,845 out=16,745,238 elapsed=46.5s

  [1508/15692] intraday_10462.csv.gz  in=190,747,976 out=16,757,369 elapsed=46.5s

  [1509/15692] intraday_10460.csv.gz  in=190,761,623 out=16,771,016 elapsed=46.5s

  [1510/15692] intraday_10463.csv.gz  in=190,773,305 out=16,782,698 elapsed=46.5s

  [1511/15692] intraday_10464.csv.gz  in=190,784,570 out=16,793,963 elapsed=46.5s

  [1512/15692] intraday_10465.csv.gz  in=190,795,768 out=16,805,161 elapsed=46.5s

  [1513/15692] intraday_10467.csv.gz  in=190,807,460 out=16,816,853 elapsed=46.5s

  [1514/15692] intraday_10466.csv.gz  in=190,819,138 out=16,828,531 elapsed=46.6s

  [1515/15692] intraday_10468.csv.gz  in=190,831,461 out=16,840,854 elapsed=46.6s

  [1516/15692] intraday_10469.csv.gz  in=190,846,577 out=16,855,970 elapsed=46.6s

  [1517/15692] intraday_1047.csv.gz  in=190,862,993 out=16,855,970 elapsed=46.6s

  [1518/15692] intraday_10471.csv.gz  in=190,872,803 out=16,865,780 elapsed=46.6s

  [1519/15692] intraday_10470.csv.gz  in=190,884,844 out=16,877,821 elapsed=46.6s

  [1520/15692] intraday_10472.csv.gz  in=190,895,719 out=16,888,696 elapsed=46.6s

  [1521/15692] intraday_10473.csv.gz  in=190,908,012 out=16,900,989 elapsed=46.7s

  [1522/15692] intraday_10475.csv.gz  in=190,919,611 out=16,912,588 elapsed=46.7s

  [1523/15692] intraday_10474.csv.gz  in=190,932,834 out=16,925,811 elapsed=46.7s

  [1524/15692] intraday_10477.csv.gz  in=190,942,637 out=16,935,614 elapsed=46.7s

  [1525/15692] intraday_10476.csv.gz  in=190,955,640 out=16,948,473 elapsed=46.7s

  [1526/15692] intraday_10479.csv.gz  in=190,966,421 out=16,959,254 elapsed=46.7s

  [1527/15692] intraday_10478.csv.gz  in=190,975,521 out=16,968,354 elapsed=46.7s

  [1528/15692] intraday_1048.csv.gz  in=190,987,267 out=16,968,354 elapsed=46.7s

  [1529/15692] intraday_10480.csv.gz  in=190,999,633 out=16,980,720 elapsed=46.8s

  [1530/15692] intraday_10482.csv.gz  in=191,011,439 out=16,992,526 elapsed=46.8s

  [1531/15692] intraday_10483.csv.gz  in=191,023,804 out=17,004,891 elapsed=46.8s

  [1532/15692] intraday_10484.csv.gz  in=191,037,037 out=17,018,124 elapsed=46.8s

  [1533/15692] intraday_10481.csv.gz  in=191,051,320 out=17,032,407 elapsed=46.8s

  [1534/15692] intraday_10485.csv.gz  in=191,063,187 out=17,043,666 elapsed=46.9s

  [1535/15692] intraday_10486.csv.gz  in=191,075,177 out=17,055,656 elapsed=46.9s

  [1536/15692] intraday_10487.csv.gz  in=191,086,201 out=17,066,680 elapsed=46.9s

  [1537/15692] intraday_10488.csv.gz  in=191,097,044 out=17,077,523 elapsed=46.9s

  [1538/15692] intraday_10489.csv.gz  in=191,111,790 out=17,090,553 elapsed=46.9s

  [1539/15692] intraday_1049.csv.gz  in=191,124,073 out=17,090,553 elapsed=46.9s

  [1540/15692] intraday_10490.csv.gz  in=191,135,386 out=17,101,866 elapsed=46.9s

  [1541/15692] intraday_10491.csv.gz  in=191,146,905 out=17,113,385 elapsed=46.9s

  [1542/15692] intraday_10492.csv.gz  in=191,158,166 out=17,124,646 elapsed=47.0s

  [1543/15692] intraday_10493.csv.gz  in=191,170,388 out=17,136,868 elapsed=47.0s

  [1544/15692] intraday_10495.csv.gz  in=191,181,712 out=17,148,192 elapsed=47.0s

  [1545/15692] intraday_10494.csv.gz  in=191,195,455 out=17,161,935 elapsed=47.0s

  [1546/15692] intraday_10496.csv.gz  in=191,207,953 out=17,174,433 elapsed=47.0s

  [1547/15692] intraday_10497.csv.gz  in=191,219,335 out=17,185,815 elapsed=47.0s

  [1548/15692] intraday_10498.csv.gz  in=191,230,004 out=17,196,484 elapsed=47.0s

  [1549/15692] intraday_1050.csv.gz  in=191,242,537 out=17,196,484 elapsed=47.0s

  [1550/15692] intraday_10499.csv.gz  in=191,254,843 out=17,208,790 elapsed=47.1s

  [1551/15692] intraday_10501.csv.gz  in=191,268,840 out=17,222,787 elapsed=47.1s

  [1552/15692] intraday_10502.csv.gz  in=191,279,048 out=17,232,995 elapsed=47.1s

  [1553/15692] intraday_10500.csv.gz  in=191,289,829 out=17,243,776 elapsed=47.1s

  [1554/15692] intraday_10503.csv.gz  in=191,300,921 out=17,254,868 elapsed=47.1s

  [1555/15692] intraday_10504.csv.gz  in=191,311,306 out=17,265,253 elapsed=47.2s

  [1556/15692] intraday_10506.csv.gz  in=191,324,632 out=17,278,579 elapsed=47.2s

  [1557/15692] intraday_10505.csv.gz  in=191,339,959 out=17,293,906 elapsed=47.2s

  [1558/15692] intraday_10507.csv.gz  in=191,353,372 out=17,307,319 elapsed=47.2s

  [1559/15692] intraday_10508.csv.gz  in=191,366,201 out=17,320,148 elapsed=47.2s

  [1560/15692] intraday_10509.csv.gz  in=191,378,469 out=17,332,416 elapsed=47.2s

  [1561/15692] intraday_1051.csv.gz  in=191,391,399 out=17,332,416 elapsed=47.2s

  [1562/15692] intraday_10510.csv.gz  in=191,402,922 out=17,343,939 elapsed=47.2s

  [1563/15692] intraday_10511.csv.gz  in=191,414,362 out=17,355,379 elapsed=47.3s

  [1564/15692] intraday_10512.csv.gz  in=191,427,095 out=17,368,112 elapsed=47.3s

  [1565/15692] intraday_10513.csv.gz  in=191,441,197 out=17,382,214 elapsed=47.3s

  [1566/15692] intraday_10514.csv.gz  in=191,453,662 out=17,394,679 elapsed=47.3s

  [1567/15692] intraday_10515.csv.gz  in=191,466,019 out=17,407,036 elapsed=47.3s

  [1568/15692] intraday_10516.csv.gz  in=191,476,461 out=17,417,478 elapsed=47.3s

  [1569/15692] intraday_10518.csv.gz  in=191,487,206 out=17,428,223 elapsed=47.4s

  [1570/15692] intraday_10517.csv.gz  in=191,500,361 out=17,441,378 elapsed=47.4s

  [1571/15692] intraday_1052.csv.gz  in=191,511,701 out=17,441,378 elapsed=47.4s

  [1572/15692] intraday_10519.csv.gz  in=191,528,476 out=17,456,215 elapsed=47.4s

  [1573/15692] intraday_10520.csv.gz  in=191,539,553 out=17,467,292 elapsed=47.4s

  [1574/15692] intraday_10521.csv.gz  in=191,548,793 out=17,476,532 elapsed=47.4s

  [1575/15692] intraday_10523.csv.gz  in=191,562,044 out=17,489,783 elapsed=47.4s

  [1576/15692] intraday_10522.csv.gz  in=191,571,999 out=17,499,738 elapsed=47.4s

  [1577/15692] intraday_10526.csv.gz  in=191,583,042 out=17,510,781 elapsed=47.5s

  [1578/15692] intraday_10525.csv.gz  in=191,596,593 out=17,524,332 elapsed=47.5s

  [1579/15692] intraday_10524.csv.gz  in=191,613,474 out=17,541,213 elapsed=47.5s

  [1580/15692] intraday_10527.csv.gz  in=191,625,063 out=17,552,802 elapsed=47.5s

  [1581/15692] intraday_10528.csv.gz  in=191,637,417 out=17,565,156 elapsed=47.5s

  [1582/15692] intraday_10529.csv.gz  in=191,648,915 out=17,576,654 elapsed=47.5s

  [1583/15692] intraday_10530.csv.gz  in=191,664,255 out=17,591,994 elapsed=47.5s

  [1584/15692] intraday_1053.csv.gz  in=191,689,716 out=17,591,994 elapsed=47.5s

  [1585/15692] intraday_10531.csv.gz  in=191,702,121 out=17,604,399 elapsed=47.6s

  [1586/15692] intraday_10532.csv.gz  in=191,712,691 out=17,614,969 elapsed=47.6s

  [1587/15692] intraday_10533.csv.gz  in=191,724,144 out=17,626,422 elapsed=47.6s

  [1588/15692] intraday_10535.csv.gz  in=191,736,480 out=17,638,758 elapsed=47.6s

  [1589/15692] intraday_10534.csv.gz  in=191,750,756 out=17,653,034 elapsed=47.6s

  [1590/15692] intraday_10536.csv.gz  in=191,762,218 out=17,664,496 elapsed=47.6s

  [1591/15692] intraday_10538.csv.gz  in=191,774,423 out=17,676,701 elapsed=47.6s

  [1592/15692] intraday_10537.csv.gz  in=191,787,103 out=17,689,381 elapsed=47.6s

  [1593/15692] intraday_1054.csv.gz  in=191,798,881 out=17,689,381 elapsed=47.6s

  [1594/15692] intraday_10539.csv.gz  in=191,811,004 out=17,701,504 elapsed=47.7s

  [1595/15692] intraday_10542.csv.gz  in=191,824,699 out=17,715,199 elapsed=47.7s

  [1596/15692] intraday_10540.csv.gz  in=191,837,041 out=17,727,541 elapsed=47.7s

  [1597/15692] intraday_10541.csv.gz  in=191,847,106 out=17,737,606 elapsed=47.7s

  [1598/15692] intraday_10543.csv.gz  in=191,860,497 out=17,750,997 elapsed=47.7s

  [1599/15692] intraday_10544.csv.gz  in=191,873,765 out=17,764,265 elapsed=47.7s

  [1600/15692] intraday_10545.csv.gz  in=191,885,759 out=17,776,259 elapsed=47.7s

  [1601/15692] intraday_10546.csv.gz  in=191,895,529 out=17,786,029 elapsed=47.7s

  [1602/15692] intraday_10547.csv.gz  in=191,911,207 out=17,801,707 elapsed=47.8s

  [1603/15692] intraday_10548.csv.gz  in=191,922,325 out=17,812,825 elapsed=47.8s

  [1604/15692] intraday_10549.csv.gz  in=191,934,020 out=17,824,520 elapsed=47.8s

  [1605/15692] intraday_1055.csv.gz  in=191,945,961 out=17,824,520 elapsed=47.8s

  [1606/15692] intraday_10551.csv.gz  in=191,959,381 out=17,837,940 elapsed=47.8s

  [1607/15692] intraday_10550.csv.gz  in=191,972,675 out=17,851,234 elapsed=47.8s

  [1608/15692] intraday_10553.csv.gz  in=191,986,721 out=17,865,280 elapsed=47.8s

  [1609/15692] intraday_10552.csv.gz  in=191,997,209 out=17,875,768 elapsed=47.8s

  [1610/15692] intraday_10554.csv.gz  in=192,014,320 out=17,892,879 elapsed=47.8s

  [1611/15692] intraday_10555.csv.gz  in=192,026,119 out=17,904,678 elapsed=47.8s

  [1612/15692] intraday_10556.csv.gz  in=192,041,326 out=17,919,885 elapsed=47.9s

  [1613/15692] intraday_10557.csv.gz  in=192,055,721 out=17,934,280 elapsed=47.9s

  [1614/15692] intraday_10558.csv.gz  in=192,073,305 out=17,951,864 elapsed=47.9s

  [1615/15692] intraday_10559.csv.gz  in=192,087,964 out=17,966,523 elapsed=47.9s

  [1616/15692] intraday_1056.csv.gz  in=192,104,345 out=17,966,523 elapsed=47.9s

  [1617/15692] intraday_10561.csv.gz  in=192,115,897 out=17,978,075 elapsed=47.9s

  [1618/15692] intraday_10560.csv.gz  in=192,133,103 out=17,995,281 elapsed=48.0s

  [1619/15692] intraday_10562.csv.gz  in=192,144,919 out=18,007,097 elapsed=48.0s

  [1620/15692] intraday_10564.csv.gz  in=192,158,311 out=18,020,489 elapsed=48.0s

  [1621/15692] intraday_10563.csv.gz  in=192,177,119 out=18,038,671 elapsed=48.0s

  [1622/15692] intraday_10565.csv.gz  in=192,188,190 out=18,049,742 elapsed=48.0s

  [1623/15692] intraday_10566.csv.gz  in=192,200,124 out=18,061,676 elapsed=48.0s

  [1624/15692] intraday_10567.csv.gz  in=192,212,373 out=18,073,925 elapsed=48.1s

  [1625/15692] intraday_10569.csv.gz  in=192,222,452 out=18,084,004 elapsed=48.1s

  [1626/15692] intraday_1057.csv.gz  in=192,232,560 out=18,084,004 elapsed=48.1s

  [1627/15692] intraday_10568.csv.gz  in=192,247,988 out=18,099,432 elapsed=48.1s

  [1628/15692] intraday_10570.csv.gz  in=192,259,039 out=18,110,483 elapsed=48.1s

  [1629/15692] intraday_10571.csv.gz  in=192,271,326 out=18,122,770 elapsed=48.1s

  [1630/15692] intraday_10572.csv.gz  in=192,283,061 out=18,134,505 elapsed=48.1s

  [1631/15692] intraday_10573.csv.gz  in=192,294,038 out=18,145,482 elapsed=48.2s

  [1632/15692] intraday_10574.csv.gz  in=192,309,581 out=18,161,025 elapsed=48.2s

  [1633/15692] intraday_10575.csv.gz  in=192,325,550 out=18,176,994 elapsed=48.2s

  [1634/15692] intraday_10576.csv.gz  in=192,339,120 out=18,190,564 elapsed=48.2s

  [1635/15692] intraday_10579.csv.gz  in=192,350,025 out=18,201,469 elapsed=48.2s

  [1636/15692] intraday_10577.csv.gz  in=192,365,987 out=18,217,431 elapsed=48.2s

  [1637/15692] intraday_10578.csv.gz  in=192,377,295 out=18,228,739 elapsed=48.3s

  [1638/15692] intraday_1058.csv.gz  in=192,390,464 out=18,228,739 elapsed=48.3s

  [1639/15692] intraday_10580.csv.gz  in=192,403,154 out=18,241,429 elapsed=48.3s

  [1640/15692] intraday_10581.csv.gz  in=192,414,731 out=18,253,006 elapsed=48.3s

  [1641/15692] intraday_10582.csv.gz  in=192,424,495 out=18,262,770 elapsed=48.3s

  [1642/15692] intraday_10583.csv.gz  in=192,432,324 out=18,270,599 elapsed=48.3s

  [1643/15692] intraday_10584.csv.gz  in=192,442,942 out=18,281,217 elapsed=48.3s

  [1644/15692] intraday_10585.csv.gz  in=192,449,461 out=18,287,736 elapsed=48.4s

  [1645/15692] intraday_10586.csv.gz  in=192,464,150 out=18,302,425 elapsed=48.4s

  [1646/15692] intraday_10588.csv.gz  in=192,475,631 out=18,313,906 elapsed=48.4s

  [1647/15692] intraday_10589.csv.gz  in=192,485,118 out=18,323,393 elapsed=48.4s

  [1648/15692] intraday_10587.csv.gz  in=192,497,724 out=18,335,999 elapsed=48.4s

  [1649/15692] intraday_10590.csv.gz  in=192,509,343 out=18,347,618 elapsed=48.4s

  [1650/15692] intraday_1059.csv.gz  in=192,532,160 out=18,347,618 elapsed=48.4s

  [1651/15692] intraday_10591.csv.gz  in=192,546,024 out=18,361,482 elapsed=48.4s

  [1652/15692] intraday_10592.csv.gz  in=192,560,255 out=18,375,713 elapsed=48.5s

  [1653/15692] intraday_10593.csv.gz  in=192,571,033 out=18,386,491 elapsed=48.5s

  [1654/15692] intraday_10595.csv.gz  in=192,584,566 out=18,400,024 elapsed=48.5s

  [1655/15692] intraday_10594.csv.gz  in=192,595,813 out=18,411,271 elapsed=48.5s

  [1656/15692] intraday_10596.csv.gz  in=192,609,901 out=18,425,359 elapsed=48.5s

  [1657/15692] intraday_10597.csv.gz  in=192,621,978 out=18,437,436 elapsed=48.5s

  [1658/15692] intraday_10599.csv.gz  in=192,635,021 out=18,450,479 elapsed=48.5s

  [1659/15692] intraday_10598.csv.gz  in=192,649,921 out=18,465,379 elapsed=48.5s

  [1660/15692] intraday_1060.csv.gz  in=192,664,818 out=18,465,379 elapsed=48.5s

  [1661/15692] intraday_10600.csv.gz  in=192,674,486 out=18,475,047 elapsed=48.6s

  [1662/15692] intraday_10601.csv.gz  in=192,684,453 out=18,485,014 elapsed=48.6s

  [1663/15692] intraday_10602.csv.gz  in=192,696,400 out=18,496,961 elapsed=48.6s

  [1664/15692] intraday_10603.csv.gz  in=192,708,930 out=18,509,491 elapsed=48.6s

  [1665/15692] intraday_10604.csv.gz  in=192,720,002 out=18,520,563 elapsed=48.6s

  [1666/15692] intraday_10605.csv.gz  in=192,730,468 out=18,531,029 elapsed=48.6s

  [1667/15692] intraday_10606.csv.gz  in=192,741,091 out=18,541,652 elapsed=48.6s

  [1668/15692] intraday_10607.csv.gz  in=192,755,504 out=18,556,065 elapsed=48.6s

  [1669/15692] intraday_10608.csv.gz  in=192,768,018 out=18,568,579 elapsed=48.7s

  [1670/15692] intraday_10609.csv.gz  in=192,779,613 out=18,580,174 elapsed=48.7s

  [1671/15692] intraday_1061.csv.gz  in=192,791,539 out=18,580,174 elapsed=48.7s

  [1672/15692] intraday_10611.csv.gz  in=192,802,633 out=18,591,268 elapsed=48.7s

  [1673/15692] intraday_10610.csv.gz  in=192,815,899 out=18,604,534 elapsed=48.7s

  [1674/15692] intraday_10612.csv.gz  in=192,828,066 out=18,616,701 elapsed=48.7s

  [1675/15692] intraday_10613.csv.gz  in=192,839,907 out=18,628,542 elapsed=48.7s

  [1676/15692] intraday_10614.csv.gz  in=192,851,671 out=18,640,306 elapsed=48.7s

  [1677/15692] intraday_10615.csv.gz  in=192,863,475 out=18,652,110 elapsed=48.8s

  [1678/15692] intraday_10618.csv.gz  in=192,873,116 out=18,661,751 elapsed=48.8s

  [1679/15692] intraday_10616.csv.gz  in=192,888,392 out=18,677,027 elapsed=48.8s

  [1680/15692] intraday_10617.csv.gz  in=192,900,289 out=18,688,924 elapsed=48.8s

  [1681/15692] intraday_10619.csv.gz  in=192,911,489 out=18,700,124 elapsed=48.8s

  [1682/15692] intraday_1062.csv.gz  in=192,924,982 out=18,700,124 elapsed=48.8s

  [1683/15692] intraday_10620.csv.gz  in=192,936,672 out=18,711,814 elapsed=48.8s

  [1684/15692] intraday_10621.csv.gz  in=192,948,250 out=18,723,392 elapsed=48.8s

  [1685/15692] intraday_10622.csv.gz  in=192,960,101 out=18,735,243 elapsed=48.8s

  [1686/15692] intraday_10623.csv.gz  in=192,971,702 out=18,746,844 elapsed=48.9s

  [1687/15692] intraday_10624.csv.gz  in=192,982,758 out=18,757,900 elapsed=48.9s

  [1688/15692] intraday_10625.csv.gz  in=192,992,755 out=18,767,897 elapsed=48.9s

  [1689/15692] intraday_10626.csv.gz  in=193,003,744 out=18,778,886 elapsed=48.9s

  [1690/15692] intraday_10627.csv.gz  in=193,015,917 out=18,791,059 elapsed=48.9s

  [1691/15692] intraday_10628.csv.gz  in=193,029,468 out=18,804,610 elapsed=48.9s

  [1692/15692] intraday_10629.csv.gz  in=193,040,902 out=18,816,044 elapsed=48.9s

  [1693/15692] intraday_1063.csv.gz  in=193,053,148 out=18,816,044 elapsed=48.9s

  [1694/15692] intraday_10630.csv.gz  in=193,066,757 out=18,829,653 elapsed=48.9s

  [1695/15692] intraday_10631.csv.gz  in=193,078,923 out=18,841,819 elapsed=49.0s

  [1696/15692] intraday_10632.csv.gz  in=193,089,114 out=18,852,010 elapsed=49.0s

  [1697/15692] intraday_10633.csv.gz  in=193,100,961 out=18,863,857 elapsed=49.0s

  [1698/15692] intraday_10635.csv.gz  in=193,111,010 out=18,873,906 elapsed=49.0s

  [1699/15692] intraday_10634.csv.gz  in=193,122,352 out=18,885,248 elapsed=49.0s

  [1700/15692] intraday_10636.csv.gz  in=193,133,380 out=18,896,276 elapsed=49.0s

  [1701/15692] intraday_10637.csv.gz  in=193,144,518 out=18,907,414 elapsed=49.0s

  [1702/15692] intraday_10638.csv.gz  in=193,156,016 out=18,918,912 elapsed=49.0s

  [1703/15692] intraday_10639.csv.gz  in=193,168,091 out=18,930,987 elapsed=49.1s

  [1704/15692] intraday_1064.csv.gz  in=193,180,748 out=18,930,987 elapsed=49.1s

  [1705/15692] intraday_10641.csv.gz  in=193,190,876 out=18,941,115 elapsed=49.1s

  [1706/15692] intraday_10640.csv.gz  in=193,207,136 out=18,956,292 elapsed=49.1s

  [1707/15692] intraday_10642.csv.gz  in=193,220,454 out=18,969,610 elapsed=49.1s

  [1708/15692] intraday_10643.csv.gz  in=193,232,262 out=18,981,418 elapsed=49.1s

  [1709/15692] intraday_10644.csv.gz  in=193,242,564 out=18,991,720 elapsed=49.1s

  [1710/15692] intraday_10645.csv.gz  in=193,254,212 out=19,003,368 elapsed=49.1s

  [1711/15692] intraday_10646.csv.gz  in=193,266,745 out=19,015,901 elapsed=49.2s

  [1712/15692] intraday_10647.csv.gz  in=193,276,590 out=19,025,746 elapsed=49.2s

  [1713/15692] intraday_10649.csv.gz  in=193,287,056 out=19,036,212 elapsed=49.2s

  [1714/15692] intraday_10648.csv.gz  in=193,301,021 out=19,050,177 elapsed=49.2s

  [1715/15692] intraday_10650.csv.gz  in=193,312,298 out=19,061,454 elapsed=49.2s

  [1716/15692] intraday_1065.csv.gz  in=193,324,118 out=19,061,454 elapsed=49.2s

  [1717/15692] intraday_10651.csv.gz  in=193,334,023 out=19,071,359 elapsed=49.2s

  [1718/15692] intraday_10652.csv.gz  in=193,347,785 out=19,085,121 elapsed=49.2s

  [1719/15692] intraday_10654.csv.gz  in=193,361,841 out=19,099,177 elapsed=49.3s

  [1720/15692] intraday_10655.csv.gz  in=193,372,993 out=19,110,329 elapsed=49.3s

  [1721/15692] intraday_10653.csv.gz  in=193,387,402 out=19,124,738 elapsed=49.3s

  [1722/15692] intraday_10656.csv.gz  in=193,400,851 out=19,138,187 elapsed=49.3s

  [1723/15692] intraday_10657.csv.gz  in=193,413,663 out=19,150,999 elapsed=49.3s

  [1724/15692] intraday_10658.csv.gz  in=193,425,700 out=19,163,036 elapsed=49.3s

  [1725/15692] intraday_1066.csv.gz  in=193,440,379 out=19,163,036 elapsed=49.3s

  [1726/15692] intraday_10659.csv.gz  in=193,453,179 out=19,175,836 elapsed=49.3s

  [1727/15692] intraday_10660.csv.gz  in=193,465,948 out=19,188,605 elapsed=49.4s

  [1728/15692] intraday_10662.csv.gz  in=193,477,112 out=19,199,769 elapsed=49.4s

  [1729/15692] intraday_10661.csv.gz  in=193,488,414 out=19,211,071 elapsed=49.4s

  [1730/15692] intraday_10663.csv.gz  in=193,498,772 out=19,221,429 elapsed=49.4s

  [1731/15692] intraday_10664.csv.gz  in=193,512,112 out=19,234,769 elapsed=49.4s

  [1732/15692] intraday_10665.csv.gz  in=193,523,263 out=19,245,920 elapsed=49.4s

  [1733/15692] intraday_10666.csv.gz  in=193,534,241 out=19,256,898 elapsed=49.4s

  [1734/15692] intraday_10667.csv.gz  in=193,544,128 out=19,266,785 elapsed=49.4s

  [1735/15692] intraday_10668.csv.gz  in=193,552,954 out=19,275,611 elapsed=49.4s

  [1736/15692] intraday_10669.csv.gz  in=193,563,317 out=19,285,974 elapsed=49.4s

  [1737/15692] intraday_1067.csv.gz  in=193,575,117 out=19,285,974 elapsed=49.5s

  [1738/15692] intraday_10670.csv.gz  in=193,587,964 out=19,298,821 elapsed=49.5s

  [1739/15692] intraday_10672.csv.gz  in=193,601,055 out=19,311,912 elapsed=49.5s

  [1740/15692] intraday_10673.csv.gz  in=193,612,344 out=19,323,201 elapsed=49.5s

  [1741/15692] intraday_10671.csv.gz  in=193,629,579 out=19,340,436 elapsed=49.5s

  [1742/15692] intraday_10674.csv.gz  in=193,640,769 out=19,351,626 elapsed=49.5s

  [1743/15692] intraday_10675.csv.gz  in=193,653,839 out=19,364,696 elapsed=49.5s

  [1744/15692] intraday_10676.csv.gz  in=193,665,237 out=19,376,094 elapsed=49.5s

  [1745/15692] intraday_10677.csv.gz  in=193,679,459 out=19,390,316 elapsed=49.5s

  [1746/15692] intraday_10679.csv.gz  in=193,691,400 out=19,402,257 elapsed=49.6s

  [1747/15692] intraday_10678.csv.gz  in=193,702,271 out=19,413,128 elapsed=49.6s

  [1748/15692] intraday_1068.csv.gz  in=193,719,334 out=19,413,128 elapsed=49.6s

  [1749/15692] intraday_10680.csv.gz  in=193,730,541 out=19,424,335 elapsed=49.6s

  [1750/15692] intraday_10681.csv.gz  in=193,743,677 out=19,437,471 elapsed=49.6s

  [1751/15692] intraday_10682.csv.gz  in=193,756,656 out=19,450,450 elapsed=49.6s

  [1752/15692] intraday_10683.csv.gz  in=193,768,917 out=19,462,711 elapsed=49.6s

  [1753/15692] intraday_10685.csv.gz  in=193,780,321 out=19,474,115 elapsed=49.6s

  [1754/15692] intraday_10684.csv.gz  in=193,792,695 out=19,486,489 elapsed=49.6s

  [1755/15692] intraday_10686.csv.gz  in=193,804,194 out=19,497,988 elapsed=49.6s

  [1756/15692] intraday_10688.csv.gz  in=193,815,003 out=19,508,797 elapsed=49.6s

  [1757/15692] intraday_10687.csv.gz  in=193,827,508 out=19,521,302 elapsed=49.7s

  [1758/15692] intraday_10689.csv.gz  in=193,838,867 out=19,532,661 elapsed=49.7s

  [1759/15692] intraday_1069.csv.gz  in=193,851,802 out=19,532,661 elapsed=49.7s

  [1760/15692] intraday_10690.csv.gz  in=193,869,957 out=19,548,878 elapsed=49.7s

  [1761/15692] intraday_10691.csv.gz  in=193,882,998 out=19,561,919 elapsed=49.7s

  [1762/15692] intraday_10693.csv.gz  in=193,894,096 out=19,573,017 elapsed=49.7s

  [1763/15692] intraday_10692.csv.gz  in=193,905,003 out=19,583,924 elapsed=49.7s

  [1764/15692] intraday_10694.csv.gz  in=193,919,681 out=19,598,602 elapsed=49.7s

  [1765/15692] intraday_10695.csv.gz  in=193,930,799 out=19,609,720 elapsed=49.7s

  [1766/15692] intraday_10698.csv.gz  in=193,943,845 out=19,622,766 elapsed=49.8s

  [1767/15692] intraday_10697.csv.gz  in=193,955,961 out=19,634,882 elapsed=49.8s

  [1768/15692] intraday_10696.csv.gz  in=193,968,370 out=19,647,291 elapsed=49.8s

  [1769/15692] intraday_10699.csv.gz  in=193,978,838 out=19,657,759 elapsed=49.8s

  [1770/15692] intraday_1070.csv.gz  in=193,994,495 out=19,657,759 elapsed=49.8s

  [1771/15692] intraday_10700.csv.gz  in=194,009,802 out=19,673,066 elapsed=49.8s

  [1772/15692] intraday_10702.csv.gz  in=194,022,333 out=19,685,597 elapsed=49.8s

  [1773/15692] intraday_10703.csv.gz  in=194,035,629 out=19,698,893 elapsed=49.8s

  [1774/15692] intraday_10701.csv.gz  in=194,050,795 out=19,714,059 elapsed=49.8s

  [1775/15692] intraday_10704.csv.gz  in=194,066,351 out=19,729,615 elapsed=49.8s

  [1776/15692] intraday_10706.csv.gz  in=194,080,269 out=19,743,533 elapsed=49.9s

  [1777/15692] intraday_10705.csv.gz  in=194,097,466 out=19,760,730 elapsed=49.9s

  [1778/15692] intraday_10707.csv.gz  in=194,111,230 out=19,774,494 elapsed=49.9s

  [1779/15692] intraday_10708.csv.gz  in=194,123,170 out=19,786,434 elapsed=49.9s

  [1780/15692] intraday_1071.csv.gz  in=194,133,092 out=19,786,434 elapsed=49.9s

  [1781/15692] intraday_10709.csv.gz  in=194,144,395 out=19,797,737 elapsed=49.9s

  [1782/15692] intraday_10710.csv.gz  in=194,154,172 out=19,807,514 elapsed=49.9s

  [1783/15692] intraday_10712.csv.gz  in=194,165,523 out=19,818,865 elapsed=49.9s

  [1784/15692] intraday_10713.csv.gz  in=194,178,144 out=19,831,486 elapsed=49.9s

  [1785/15692] intraday_10711.csv.gz  in=194,190,629 out=19,843,971 elapsed=49.9s

  [1786/15692] intraday_10714.csv.gz  in=194,202,790 out=19,856,132 elapsed=49.9s

  [1787/15692] intraday_10716.csv.gz  in=194,213,367 out=19,866,709 elapsed=50.0s

  [1788/15692] intraday_10715.csv.gz  in=194,228,215 out=19,881,557 elapsed=50.0s

  [1789/15692] intraday_10717.csv.gz  in=194,239,198 out=19,892,540 elapsed=50.0s

  [1790/15692] intraday_10718.csv.gz  in=194,251,767 out=19,905,109 elapsed=50.0s

  [1791/15692] intraday_10719.csv.gz  in=194,263,025 out=19,916,367 elapsed=50.0s

  [1792/15692] intraday_1072.csv.gz  in=194,289,774 out=19,916,367 elapsed=50.0s

  [1793/15692] intraday_10721.csv.gz  in=194,304,656 out=19,931,249 elapsed=50.0s

  [1794/15692] intraday_10720.csv.gz  in=194,316,292 out=19,942,885 elapsed=50.0s

  [1795/15692] intraday_10722.csv.gz  in=194,331,243 out=19,957,836 elapsed=50.1s

  [1796/15692] intraday_10725.csv.gz  in=194,342,569 out=19,969,162 elapsed=50.1s

  [1797/15692] intraday_10723.csv.gz  in=194,356,871 out=19,983,464 elapsed=50.1s

  [1798/15692] intraday_10726.csv.gz  in=194,367,295 out=19,993,888 elapsed=50.1s

  [1799/15692] intraday_10724.csv.gz  in=194,383,023 out=20,009,616 elapsed=50.1s

  [1800/15692] intraday_10727.csv.gz  in=194,396,349 out=20,022,942 elapsed=50.1s

  [1801/15692] intraday_10728.csv.gz  in=194,407,066 out=20,033,659 elapsed=50.1s

  [1802/15692] intraday_10729.csv.gz  in=194,417,115 out=20,043,708 elapsed=50.2s

  [1803/15692] intraday_1073.csv.gz  in=194,428,206 out=20,043,708 elapsed=50.2s

  [1804/15692] intraday_10730.csv.gz  in=194,434,425 out=20,049,927 elapsed=50.2s

  [1805/15692] intraday_10733.csv.gz  in=194,434,431 out=20,049,933 elapsed=50.2s

  [1806/15692] intraday_10731.csv.gz  in=194,444,014 out=20,059,516 elapsed=50.2s

  [1807/15692] intraday_10734.csv.gz  in=194,444,015 out=20,059,517 elapsed=50.2s

  [1808/15692] intraday_10735.csv.gz  in=194,444,018 out=20,059,520 elapsed=50.2s

  [1809/15692] intraday_10732.csv.gz  in=194,452,241 out=20,067,743 elapsed=50.2s

  [1810/15692] intraday_10736.csv.gz  in=194,452,245 out=20,067,747 elapsed=50.2s

  [1811/15692] intraday_10737.csv.gz  in=194,452,252 out=20,067,754 elapsed=50.2s

  [1812/15692] intraday_10738.csv.gz  in=194,452,254 out=20,067,756 elapsed=50.2s

  [1813/15692] intraday_10739.csv.gz  in=194,452,255 out=20,067,757 elapsed=50.2s

  [1814/15692] intraday_10741.csv.gz  in=194,452,258 out=20,067,760 elapsed=50.2s

  [1815/15692] intraday_10740.csv.gz  in=194,452,263 out=20,067,765 elapsed=50.2s

  [1816/15692] intraday_10742.csv.gz  in=194,452,266 out=20,067,768 elapsed=50.2s

  [1817/15692] intraday_10743.csv.gz  in=194,452,269 out=20,067,771 elapsed=50.2s

  [1818/15692] intraday_10744.csv.gz  in=194,452,271 out=20,067,773 elapsed=50.3s

  [1819/15692] intraday_1074.csv.gz  in=194,468,712 out=20,067,773 elapsed=50.3s

  [1820/15692] intraday_10747.csv.gz  in=194,468,714 out=20,067,775 elapsed=50.3s

  [1821/15692] intraday_10746.csv.gz  in=194,468,719 out=20,067,780 elapsed=50.3s

  [1822/15692] intraday_10748.csv.gz  in=194,468,720 out=20,067,781 elapsed=50.3s

  [1823/15692] intraday_10745.csv.gz  in=194,470,976 out=20,069,230 elapsed=50.3s

  [1824/15692] intraday_10749.csv.gz  in=194,470,978 out=20,069,232 elapsed=50.3s

  [1825/15692] intraday_10751.csv.gz  in=194,470,981 out=20,069,235 elapsed=50.3s

  [1826/15692] intraday_10750.csv.gz  in=194,470,983 out=20,069,237 elapsed=50.3s

  [1827/15692] intraday_1075.csv.gz  in=194,484,231 out=20,069,237 elapsed=50.3s

  [1828/15692] intraday_10752.csv.gz  in=194,484,232 out=20,069,238 elapsed=50.3s

  [1829/15692] intraday_10753.csv.gz  in=194,484,400 out=20,069,406 elapsed=50.3s

  [1830/15692] intraday_10754.csv.gz  in=194,484,401 out=20,069,407 elapsed=50.3s

  [1831/15692] intraday_10755.csv.gz  in=194,484,402 out=20,069,408 elapsed=50.3s

  [1832/15692] intraday_10756.csv.gz  in=194,484,404 out=20,069,410 elapsed=50.3s

  [1833/15692] intraday_10757.csv.gz  in=194,484,407 out=20,069,413 elapsed=50.3s

  [1834/15692] intraday_10758.csv.gz  in=194,484,658 out=20,069,664 elapsed=50.3s

  [1835/15692] intraday_10759.csv.gz  in=194,484,659 out=20,069,665 elapsed=50.3s

  [1836/15692] intraday_10761.csv.gz  in=194,484,662 out=20,069,668 elapsed=50.3s

  [1837/15692] intraday_10760.csv.gz  in=194,484,663 out=20,069,669 elapsed=50.4s

  [1838/15692] intraday_1076.csv.gz  in=194,499,957 out=20,069,669 elapsed=50.4s

  [1839/15692] intraday_10763.csv.gz  in=194,499,958 out=20,069,670 elapsed=50.4s

  [1840/15692] intraday_10762.csv.gz  in=194,499,960 out=20,069,672 elapsed=50.4s

  [1841/15692] intraday_10764.csv.gz  in=194,499,961 out=20,069,673 elapsed=50.4s

  [1842/15692] intraday_10765.csv.gz  in=194,499,962 out=20,069,674 elapsed=50.4s

  [1843/15692] intraday_10766.csv.gz  in=194,499,963 out=20,069,675 elapsed=50.4s

  [1844/15692] intraday_10767.csv.gz  in=194,499,965 out=20,069,677 elapsed=50.4s

  [1845/15692] intraday_10768.csv.gz  in=194,499,985 out=20,069,697 elapsed=50.4s

  [1846/15692] intraday_10770.csv.gz  in=194,499,989 out=20,069,701 elapsed=50.4s

  [1847/15692] intraday_10769.csv.gz  in=194,503,042 out=20,071,794 elapsed=50.4s

  [1848/15692] intraday_1077.csv.gz  in=194,516,086 out=20,071,794 elapsed=50.4s

  [1849/15692] intraday_10771.csv.gz  in=194,516,087 out=20,071,795 elapsed=50.4s

  [1850/15692] intraday_10772.csv.gz  in=194,516,088 out=20,071,796 elapsed=50.4s

  [1851/15692] intraday_10773.csv.gz  in=194,516,089 out=20,071,797 elapsed=50.4s

  [1852/15692] intraday_10775.csv.gz  in=194,516,095 out=20,071,803 elapsed=50.4s

  [1853/15692] intraday_10774.csv.gz  in=194,516,096 out=20,071,804 elapsed=50.4s

  [1854/15692] intraday_10776.csv.gz  in=194,516,100 out=20,071,808 elapsed=50.4s

  [1855/15692] intraday_10777.csv.gz  in=194,516,101 out=20,071,809 elapsed=50.4s

  [1856/15692] intraday_10778.csv.gz  in=194,516,105 out=20,071,813 elapsed=50.4s

  [1857/15692] intraday_10779.csv.gz  in=194,516,107 out=20,071,815 elapsed=50.4s

  [1858/15692] intraday_10780.csv.gz  in=194,516,109 out=20,071,817 elapsed=50.4s

  [1859/15692] intraday_10781.csv.gz  in=194,516,110 out=20,071,818 elapsed=50.4s

  [1860/15692] intraday_10782.csv.gz  in=194,516,114 out=20,071,822 elapsed=50.4s

  [1861/15692] intraday_10783.csv.gz  in=194,516,115 out=20,071,823 elapsed=50.4s

  [1862/15692] intraday_10784.csv.gz  in=194,516,119 out=20,071,827 elapsed=50.5s

  [1863/15692] intraday_10785.csv.gz  in=194,516,120 out=20,071,828 elapsed=50.5s

  [1864/15692] intraday_1078.csv.gz  in=194,528,842 out=20,071,828 elapsed=50.5s

  [1865/15692] intraday_10786.csv.gz  in=194,528,843 out=20,071,829 elapsed=50.5s

  [1866/15692] intraday_10788.csv.gz  in=194,528,850 out=20,071,836 elapsed=50.5s

  [1867/15692] intraday_10787.csv.gz  in=194,528,892 out=20,071,878 elapsed=50.5s

  [1868/15692] intraday_10789.csv.gz  in=194,528,896 out=20,071,882 elapsed=50.5s

  [1869/15692] intraday_10790.csv.gz  in=194,528,898 out=20,071,884 elapsed=50.5s

  [1870/15692] intraday_10791.csv.gz  in=194,528,903 out=20,071,889 elapsed=50.5s

  [1871/15692] intraday_10793.csv.gz  in=194,528,904 out=20,071,890 elapsed=50.5s

  [1872/15692] intraday_1079.csv.gz  in=194,544,520 out=20,071,890 elapsed=50.5s

  [1873/15692] intraday_10792.csv.gz  in=194,546,720 out=20,074,090 elapsed=50.5s

  [1874/15692] intraday_10794.csv.gz  in=194,546,723 out=20,074,093 elapsed=50.5s

  [1875/15692] intraday_10796.csv.gz  in=194,546,724 out=20,074,094 elapsed=50.5s

  [1876/15692] intraday_10795.csv.gz  in=194,546,728 out=20,074,098 elapsed=50.6s

  [1877/15692] intraday_10798.csv.gz  in=194,546,730 out=20,074,100 elapsed=50.6s

  [1878/15692] intraday_10799.csv.gz  in=194,546,732 out=20,074,102 elapsed=50.6s

  [1879/15692] intraday_10797.csv.gz  in=194,546,733 out=20,074,103 elapsed=50.6s

  [1880/15692] intraday_10800.csv.gz  in=194,546,735 out=20,074,105 elapsed=50.6s

  [1881/15692] intraday_1080.csv.gz  in=194,559,642 out=20,074,105 elapsed=50.6s

  [1882/15692] intraday_10801.csv.gz  in=194,559,644 out=20,074,107 elapsed=50.6s

  [1883/15692] intraday_10802.csv.gz  in=194,559,645 out=20,074,108 elapsed=50.6s

  [1884/15692] intraday_10803.csv.gz  in=194,559,648 out=20,074,111 elapsed=50.6s

  [1885/15692] intraday_10805.csv.gz  in=194,559,651 out=20,074,114 elapsed=50.6s

  [1886/15692] intraday_10804.csv.gz  in=194,559,752 out=20,074,215 elapsed=50.6s

  [1887/15692] intraday_10806.csv.gz  in=194,559,755 out=20,074,218 elapsed=50.6s

  [1888/15692] intraday_10807.csv.gz  in=194,559,756 out=20,074,219 elapsed=50.6s

  [1889/15692] intraday_10809.csv.gz  in=194,559,757 out=20,074,220 elapsed=50.6s

  [1890/15692] intraday_10808.csv.gz  in=194,559,760 out=20,074,223 elapsed=50.6s

  [1891/15692] intraday_10811.csv.gz  in=194,559,763 out=20,074,226 elapsed=50.6s

  [1892/15692] intraday_10812.csv.gz  in=194,559,765 out=20,074,228 elapsed=50.6s

  [1893/15692] intraday_1081.csv.gz  in=194,572,971 out=20,074,228 elapsed=50.6s

  [1894/15692] intraday_10813.csv.gz  in=194,572,974 out=20,074,231 elapsed=50.6s

  [1895/15692] intraday_10810.csv.gz  in=194,579,661 out=20,078,645 elapsed=50.6s

  [1896/15692] intraday_10815.csv.gz  in=194,579,664 out=20,078,648 elapsed=50.6s

  [1897/15692] intraday_10814.csv.gz  in=194,579,976 out=20,078,960 elapsed=50.7s

  [1898/15692] intraday_10817.csv.gz  in=194,580,024 out=20,079,008 elapsed=50.7s

  [1899/15692] intraday_10818.csv.gz  in=194,580,027 out=20,079,011 elapsed=50.7s

  [1900/15692] intraday_10816.csv.gz  in=194,583,648 out=20,081,711 elapsed=50.7s

  [1901/15692] intraday_10819.csv.gz  in=194,583,656 out=20,081,719 elapsed=50.7s

  [1902/15692] intraday_10820.csv.gz  in=194,583,657 out=20,081,720 elapsed=50.7s

  [1903/15692] intraday_10821.csv.gz  in=194,583,658 out=20,081,721 elapsed=50.7s

  [1904/15692] intraday_10823.csv.gz  in=194,583,661 out=20,081,724 elapsed=50.7s

  [1905/15692] intraday_1082.csv.gz  in=194,604,756 out=20,081,724 elapsed=50.7s

  [1906/15692] intraday_10822.csv.gz  in=194,604,856 out=20,081,824 elapsed=50.7s

  [1907/15692] intraday_10825.csv.gz  in=194,604,863 out=20,081,831 elapsed=50.7s

  [1908/15692] intraday_10824.csv.gz  in=194,604,868 out=20,081,836 elapsed=50.7s

  [1909/15692] intraday_10827.csv.gz  in=194,604,870 out=20,081,838 elapsed=50.7s

  [1910/15692] intraday_10826.csv.gz  in=194,604,883 out=20,081,851 elapsed=50.7s

  [1911/15692] intraday_10829.csv.gz  in=194,604,888 out=20,081,856 elapsed=50.7s

  [1912/15692] intraday_10830.csv.gz  in=194,604,895 out=20,081,863 elapsed=50.8s

  [1913/15692] intraday_10831.csv.gz  in=194,604,901 out=20,081,869 elapsed=50.8s

  [1914/15692] intraday_10828.csv.gz  in=194,604,939 out=20,081,907 elapsed=50.8s

  [1915/15692] intraday_10832.csv.gz  in=194,604,943 out=20,081,911 elapsed=50.8s

  [1916/15692] intraday_1083.csv.gz  in=194,618,839 out=20,081,911 elapsed=50.8s

  [1917/15692] intraday_10836.csv.gz  in=194,618,842 out=20,081,914 elapsed=50.8s

  [1918/15692] intraday_10833.csv.gz  in=194,618,850 out=20,081,922 elapsed=50.8s

  [1919/15692] intraday_10835.csv.gz  in=194,619,111 out=20,082,183 elapsed=50.8s

  [1920/15692] intraday_10834.csv.gz  in=194,621,656 out=20,084,125 elapsed=50.8s

  [1921/15692] intraday_10838.csv.gz  in=194,621,660 out=20,084,129 elapsed=50.8s

  [1922/15692] intraday_10837.csv.gz  in=194,621,662 out=20,084,131 elapsed=50.8s

  [1923/15692] intraday_10839.csv.gz  in=194,621,695 out=20,084,164 elapsed=50.8s

  [1924/15692] intraday_10840.csv.gz  in=194,621,698 out=20,084,167 elapsed=50.8s

  [1925/15692] intraday_10841.csv.gz  in=194,621,699 out=20,084,168 elapsed=50.8s

  [1926/15692] intraday_10843.csv.gz  in=194,621,701 out=20,084,170 elapsed=50.8s

  [1927/15692] intraday_10842.csv.gz  in=194,621,710 out=20,084,179 elapsed=50.8s

  [1928/15692] intraday_1084.csv.gz  in=194,634,903 out=20,084,179 elapsed=50.8s

  [1929/15692] intraday_10846.csv.gz  in=194,634,907 out=20,084,183 elapsed=50.9s

  [1930/15692] intraday_10845.csv.gz  in=194,634,912 out=20,084,188 elapsed=50.9s

  [1931/15692] intraday_10847.csv.gz  in=194,634,916 out=20,084,192 elapsed=50.9s

  [1932/15692] intraday_10844.csv.gz  in=194,635,234 out=20,084,386 elapsed=50.9s

  [1933/15692] intraday_10848.csv.gz  in=194,635,237 out=20,084,389 elapsed=50.9s

  [1934/15692] intraday_10849.csv.gz  in=194,635,240 out=20,084,392 elapsed=50.9s

  [1935/15692] intraday_10850.csv.gz  in=194,635,243 out=20,084,395 elapsed=50.9s

  [1936/15692] intraday_10852.csv.gz  in=194,635,258 out=20,084,410 elapsed=50.9s

  [1937/15692] intraday_10851.csv.gz  in=194,635,261 out=20,084,413 elapsed=50.9s

  [1938/15692] intraday_10854.csv.gz  in=194,635,262 out=20,084,414 elapsed=50.9s

  [1939/15692] intraday_10853.csv.gz  in=194,635,266 out=20,084,418 elapsed=50.9s

  [1940/15692] intraday_1085.csv.gz  in=194,648,439 out=20,084,418 elapsed=50.9s

  [1941/15692] intraday_10855.csv.gz  in=194,648,444 out=20,084,423 elapsed=50.9s

  [1942/15692] intraday_10856.csv.gz  in=194,648,446 out=20,084,425 elapsed=50.9s

  [1943/15692] intraday_10858.csv.gz  in=194,648,447 out=20,084,426 elapsed=50.9s

  [1944/15692] intraday_10857.csv.gz  in=194,649,023 out=20,084,942 elapsed=50.9s

  [1945/15692] intraday_10859.csv.gz  in=194,649,682 out=20,085,377 elapsed=50.9s

  [1946/15692] intraday_10860.csv.gz  in=194,649,775 out=20,085,470 elapsed=50.9s

  [1947/15692] intraday_1086.csv.gz  in=194,660,242 out=20,085,470 elapsed=51.0s

  [1948/15692] intraday_10862.csv.gz  in=194,660,257 out=20,085,485 elapsed=51.0s

  [1949/15692] intraday_10861.csv.gz  in=194,660,557 out=20,085,680 elapsed=51.0s

  [1950/15692] intraday_10863.csv.gz  in=194,660,575 out=20,085,698 elapsed=51.0s

  [1951/15692] intraday_10865.csv.gz  in=194,660,716 out=20,085,839 elapsed=51.0s

  [1952/15692] intraday_10864.csv.gz  in=194,661,491 out=20,086,614 elapsed=51.0s

  [1953/15692] intraday_10866.csv.gz  in=194,662,583 out=20,087,156 elapsed=51.0s

  [1954/15692] intraday_10867.csv.gz  in=194,662,776 out=20,087,349 elapsed=51.0s

  [1955/15692] intraday_10869.csv.gz  in=194,663,190 out=20,087,763 elapsed=51.0s

  [1956/15692] intraday_10868.csv.gz  in=194,665,424 out=20,089,997 elapsed=51.0s

  [1957/15692] intraday_1087.csv.gz  in=194,678,719 out=20,089,997 elapsed=51.0s

  [1958/15692] intraday_10871.csv.gz  in=194,678,961 out=20,090,239 elapsed=51.0s

  [1959/15692] intraday_10872.csv.gz  in=194,679,067 out=20,090,345 elapsed=51.0s

  [1960/15692] intraday_10873.csv.gz  in=194,679,142 out=20,090,420 elapsed=51.1s

  [1961/15692] intraday_10870.csv.gz  in=194,692,039 out=20,098,811 elapsed=51.1s

  [1962/15692] intraday_10875.csv.gz  in=194,692,048 out=20,098,820 elapsed=51.1s

  [1963/15692] intraday_10874.csv.gz  in=194,692,653 out=20,099,425 elapsed=51.1s

  [1964/15692] intraday_10877.csv.gz  in=194,692,774 out=20,099,502 elapsed=51.1s

  [1965/15692] intraday_10878.csv.gz  in=194,693,047 out=20,099,775 elapsed=51.1s

  [1966/15692] intraday_10876.csv.gz  in=194,696,742 out=20,101,698 elapsed=51.1s

  [1967/15692] intraday_10880.csv.gz  in=194,696,786 out=20,101,742 elapsed=51.1s

  [1968/15692] intraday_10879.csv.gz  in=194,696,879 out=20,101,835 elapsed=51.1s

  [1969/15692] intraday_1088.csv.gz  in=194,709,084 out=20,101,835 elapsed=51.1s

  [1970/15692] intraday_10881.csv.gz  in=194,710,361 out=20,103,112 elapsed=51.1s

  [1971/15692] intraday_10883.csv.gz  in=194,710,761 out=20,103,512 elapsed=51.1s

  [1972/15692] intraday_10882.csv.gz  in=194,714,234 out=20,105,750 elapsed=51.2s

  [1973/15692] intraday_10884.csv.gz  in=194,714,253 out=20,105,769 elapsed=51.2s

  [1974/15692] intraday_10885.csv.gz  in=194,714,372 out=20,105,888 elapsed=51.2s

  [1975/15692] intraday_10887.csv.gz  in=194,714,473 out=20,105,989 elapsed=51.2s

  [1976/15692] intraday_10886.csv.gz  in=194,714,486 out=20,106,002 elapsed=51.2s

  [1977/15692] intraday_10888.csv.gz  in=194,715,047 out=20,106,563 elapsed=51.2s

  [1978/15692] intraday_10889.csv.gz  in=194,715,173 out=20,106,689 elapsed=51.2s

  [1979/15692] intraday_10890.csv.gz  in=194,715,315 out=20,106,831 elapsed=51.2s

  [1980/15692] intraday_1089.csv.gz  in=194,726,199 out=20,106,831 elapsed=51.2s

  [1981/15692] intraday_10891.csv.gz  in=194,726,510 out=20,107,142 elapsed=51.2s

  [1982/15692] intraday_10892.csv.gz  in=194,726,655 out=20,107,287 elapsed=51.2s

  [1983/15692] intraday_10893.csv.gz  in=194,726,791 out=20,107,423 elapsed=51.2s

  [1984/15692] intraday_10894.csv.gz  in=194,726,882 out=20,107,514 elapsed=51.2s

  [1985/15692] intraday_10895.csv.gz  in=194,727,146 out=20,107,778 elapsed=51.2s

  [1986/15692] intraday_10896.csv.gz  in=194,727,172 out=20,107,804 elapsed=51.3s

  [1987/15692] intraday_10898.csv.gz  in=194,729,003 out=20,108,921 elapsed=51.3s

  [1988/15692] intraday_10897.csv.gz  in=194,729,147 out=20,109,065 elapsed=51.3s

  [1989/15692] intraday_10900.csv.gz  in=194,729,181 out=20,109,099 elapsed=51.3s

  [1990/15692] intraday_10899.csv.gz  in=194,729,484 out=20,109,402 elapsed=51.3s

  [1991/15692] intraday_1090.csv.gz  in=194,737,289 out=20,109,402 elapsed=51.3s

  [1992/15692] intraday_10902.csv.gz  in=194,737,319 out=20,109,432 elapsed=51.3s

  [1993/15692] intraday_10901.csv.gz  in=194,738,185 out=20,110,298 elapsed=51.3s

  [1994/15692] intraday_10903.csv.gz  in=194,738,197 out=20,110,310 elapsed=51.3s

  [1995/15692] intraday_10905.csv.gz  in=194,738,206 out=20,110,319 elapsed=51.3s

  [1996/15692] intraday_10904.csv.gz  in=194,738,208 out=20,110,321 elapsed=51.3s

  [1997/15692] intraday_10908.csv.gz  in=194,740,389 out=20,111,688 elapsed=51.3s

  [1998/15692] intraday_10906.csv.gz  in=194,740,567 out=20,111,866 elapsed=51.3s

  [1999/15692] intraday_10909.csv.gz  in=194,740,576 out=20,111,875 elapsed=51.3s

  [2000/15692] intraday_10907.csv.gz  in=194,741,278 out=20,112,577 elapsed=51.3s

  [2001/15692] intraday_1091.csv.gz  in=194,753,732 out=20,112,577 elapsed=51.4s

  [2002/15692] intraday_10910.csv.gz  in=194,753,787 out=20,112,632 elapsed=51.4s

  [2003/15692] intraday_10912.csv.gz  in=194,765,449 out=20,124,294 elapsed=51.4s

  [2004/15692] intraday_10913.csv.gz  in=194,779,294 out=20,138,139 elapsed=51.4s

  [2005/15692] intraday_10914.csv.gz  in=194,789,496 out=20,148,341 elapsed=51.4s

  [2006/15692] intraday_10911.csv.gz  in=194,805,461 out=20,164,306 elapsed=51.4s

  [2007/15692] intraday_10915.csv.gz  in=194,817,387 out=20,176,232 elapsed=51.4s

  [2008/15692] intraday_10916.csv.gz  in=194,831,278 out=20,190,123 elapsed=51.4s

  [2009/15692] intraday_10917.csv.gz  in=194,845,796 out=20,204,641 elapsed=51.5s

  [2010/15692] intraday_10919.csv.gz  in=194,856,898 out=20,215,743 elapsed=51.5s

  [2011/15692] intraday_1092.csv.gz  in=194,863,209 out=20,215,743 elapsed=51.5s

  [2012/15692] intraday_10918.csv.gz  in=194,874,308 out=20,226,842 elapsed=51.5s

  [2013/15692] intraday_10920.csv.gz  in=194,887,779 out=20,240,313 elapsed=51.5s

  [2014/15692] intraday_10921.csv.gz  in=194,900,705 out=20,253,239 elapsed=51.5s

  [2015/15692] intraday_10922.csv.gz  in=194,911,528 out=20,264,062 elapsed=51.5s

  [2016/15692] intraday_10923.csv.gz  in=194,924,696 out=20,277,230 elapsed=51.5s

  [2017/15692] intraday_10924.csv.gz  in=194,939,774 out=20,292,308 elapsed=51.5s

  [2018/15692] intraday_10926.csv.gz  in=194,949,924 out=20,302,458 elapsed=51.6s

  [2019/15692] intraday_10925.csv.gz  in=194,959,164 out=20,311,698 elapsed=51.6s

  [2020/15692] intraday_10928.csv.gz  in=194,973,595 out=20,326,129 elapsed=51.6s

  [2021/15692] intraday_10929.csv.gz  in=194,985,910 out=20,338,444 elapsed=51.6s

  [2022/15692] intraday_1093.csv.gz  in=195,000,779 out=20,338,444 elapsed=51.6s

  [2023/15692] intraday_10927.csv.gz  in=195,015,075 out=20,352,740 elapsed=51.6s

  [2024/15692] intraday_10930.csv.gz  in=195,025,419 out=20,363,084 elapsed=51.6s

  [2025/15692] intraday_10931.csv.gz  in=195,036,739 out=20,374,404 elapsed=51.6s

  [2026/15692] intraday_10933.csv.gz  in=195,048,206 out=20,385,871 elapsed=51.7s

  [2027/15692] intraday_10932.csv.gz  in=195,064,852 out=20,401,325 elapsed=51.7s

  [2028/15692] intraday_10934.csv.gz  in=195,077,482 out=20,413,955 elapsed=51.7s

  [2029/15692] intraday_10935.csv.gz  in=195,089,998 out=20,426,471 elapsed=51.7s

  [2030/15692] intraday_10936.csv.gz  in=195,100,659 out=20,437,132 elapsed=51.7s

  [2031/15692] intraday_10938.csv.gz  in=195,111,417 out=20,447,890 elapsed=51.7s

  [2032/15692] intraday_10939.csv.gz  in=195,121,881 out=20,458,354 elapsed=51.7s

  [2033/15692] intraday_10937.csv.gz  in=195,144,607 out=20,478,217 elapsed=51.7s

  [2034/15692] intraday_1094.csv.gz  in=195,159,395 out=20,478,217 elapsed=51.8s

  [2035/15692] intraday_10940.csv.gz  in=195,172,591 out=20,491,413 elapsed=51.8s

  [2036/15692] intraday_10943.csv.gz  in=195,181,777 out=20,500,599 elapsed=51.8s

  [2037/15692] intraday_10942.csv.gz  in=195,195,410 out=20,514,232 elapsed=51.8s

  [2038/15692] intraday_10944.csv.gz  in=195,206,351 out=20,525,173 elapsed=51.8s

  [2039/15692] intraday_10941.csv.gz  in=195,221,468 out=20,540,290 elapsed=51.8s

  [2040/15692] intraday_10945.csv.gz  in=195,235,083 out=20,553,905 elapsed=51.8s

  [2041/15692] intraday_10946.csv.gz  in=195,246,024 out=20,564,846 elapsed=51.8s

  [2042/15692] intraday_10947.csv.gz  in=195,256,968 out=20,575,790 elapsed=51.9s

  [2043/15692] intraday_10949.csv.gz  in=195,267,468 out=20,586,290 elapsed=51.9s

  [2044/15692] intraday_10948.csv.gz  in=195,279,383 out=20,598,205 elapsed=51.9s

  [2045/15692] intraday_1095.csv.gz  in=195,291,322 out=20,598,205 elapsed=51.9s

  [2046/15692] intraday_10951.csv.gz  in=195,301,213 out=20,608,096 elapsed=51.9s

  [2047/15692] intraday_10950.csv.gz  in=195,311,151 out=20,618,034 elapsed=51.9s

  [2048/15692] intraday_10953.csv.gz  in=195,324,412 out=20,631,295 elapsed=51.9s

  [2049/15692] intraday_10952.csv.gz  in=195,335,037 out=20,641,920 elapsed=51.9s

  [2050/15692] intraday_10954.csv.gz  in=195,347,281 out=20,654,164 elapsed=52.0s

  [2051/15692] intraday_10956.csv.gz  in=195,358,587 out=20,665,470 elapsed=52.0s

  [2052/15692] intraday_10957.csv.gz  in=195,368,897 out=20,675,780 elapsed=52.0s

  [2053/15692] intraday_10955.csv.gz  in=195,383,173 out=20,690,056 elapsed=52.0s

  [2054/15692] intraday_10958.csv.gz  in=195,394,892 out=20,701,775 elapsed=52.0s

  [2055/15692] intraday_1096.csv.gz  in=195,406,466 out=20,701,775 elapsed=52.0s

  [2056/15692] intraday_10959.csv.gz  in=195,417,949 out=20,713,258 elapsed=52.0s

  [2057/15692] intraday_10960.csv.gz  in=195,427,571 out=20,722,880 elapsed=52.0s

  [2058/15692] intraday_10961.csv.gz  in=195,438,868 out=20,734,177 elapsed=52.1s

  [2059/15692] intraday_10963.csv.gz  in=195,450,514 out=20,745,823 elapsed=52.1s

  [2060/15692] intraday_10962.csv.gz  in=195,460,919 out=20,756,228 elapsed=52.1s

  [2061/15692] intraday_10964.csv.gz  in=195,472,037 out=20,767,346 elapsed=52.1s

  [2062/15692] intraday_10965.csv.gz  in=195,485,603 out=20,780,912 elapsed=52.1s

  [2063/15692] intraday_10967.csv.gz  in=195,499,018 out=20,794,327 elapsed=52.1s

  [2064/15692] intraday_10966.csv.gz  in=195,512,098 out=20,807,407 elapsed=52.1s

  [2065/15692] intraday_10969.csv.gz  in=195,521,625 out=20,816,934 elapsed=52.2s

  [2066/15692] intraday_10968.csv.gz  in=195,549,112 out=20,839,874 elapsed=52.2s

  [2067/15692] intraday_10970.csv.gz  in=195,561,343 out=20,852,105 elapsed=52.2s

  [2068/15692] intraday_1097.csv.gz  in=195,576,398 out=20,852,105 elapsed=52.2s

  [2069/15692] intraday_10972.csv.gz  in=195,586,498 out=20,862,205 elapsed=52.2s

  [2070/15692] intraday_10971.csv.gz  in=195,599,178 out=20,874,885 elapsed=52.2s

  [2071/15692] intraday_10973.csv.gz  in=195,612,234 out=20,887,941 elapsed=52.2s

  [2072/15692] intraday_10974.csv.gz  in=195,623,176 out=20,898,883 elapsed=52.3s

  [2073/15692] intraday_10975.csv.gz  in=195,633,783 out=20,909,490 elapsed=52.3s

  [2074/15692] intraday_10976.csv.gz  in=195,644,289 out=20,919,996 elapsed=52.3s

  [2075/15692] intraday_10977.csv.gz  in=195,659,010 out=20,934,717 elapsed=52.3s

  [2076/15692] intraday_10978.csv.gz  in=195,675,587 out=20,951,294 elapsed=52.3s

  [2077/15692] intraday_10979.csv.gz  in=195,688,699 out=20,964,406 elapsed=52.3s

  [2078/15692] intraday_1098.csv.gz  in=195,703,243 out=20,964,406 elapsed=52.3s

  [2079/15692] intraday_10980.csv.gz  in=195,715,464 out=20,976,627 elapsed=52.3s

  [2080/15692] intraday_10982.csv.gz  in=195,726,563 out=20,987,726 elapsed=52.4s

  [2081/15692] intraday_10981.csv.gz  in=195,738,435 out=20,999,598 elapsed=52.4s

  [2082/15692] intraday_10983.csv.gz  in=195,750,840 out=21,012,003 elapsed=52.4s

  [2083/15692] intraday_10984.csv.gz  in=195,765,851 out=21,027,014 elapsed=52.4s

  [2084/15692] intraday_10985.csv.gz  in=195,778,235 out=21,039,398 elapsed=52.4s

  [2085/15692] intraday_10986.csv.gz  in=195,788,900 out=21,050,063 elapsed=52.4s

  [2086/15692] intraday_10988.csv.gz  in=195,799,417 out=21,060,580 elapsed=52.4s

  [2087/15692] intraday_10987.csv.gz  in=195,812,223 out=21,073,386 elapsed=52.5s

  [2088/15692] intraday_10989.csv.gz  in=195,825,462 out=21,086,625 elapsed=52.5s

  [2089/15692] intraday_1099.csv.gz  in=195,837,318 out=21,086,625 elapsed=52.5s

  [2090/15692] intraday_10990.csv.gz  in=195,847,436 out=21,096,743 elapsed=52.5s

  [2091/15692] intraday_10991.csv.gz  in=195,859,537 out=21,108,844 elapsed=52.5s

  [2092/15692] intraday_10993.csv.gz  in=195,868,214 out=21,117,521 elapsed=52.5s

  [2093/15692] intraday_10994.csv.gz  in=195,879,820 out=21,129,127 elapsed=52.6s

  [2094/15692] intraday_10992.csv.gz  in=195,896,714 out=21,144,597 elapsed=52.6s

  [2095/15692] intraday_10995.csv.gz  in=195,909,785 out=21,157,668 elapsed=52.6s

  [2096/15692] intraday_10996.csv.gz  in=195,931,899 out=21,179,782 elapsed=52.6s

  [2097/15692] intraday_10997.csv.gz  in=195,943,151 out=21,191,034 elapsed=52.6s

  [2098/15692] intraday_10998.csv.gz  in=195,954,810 out=21,202,693 elapsed=52.6s

  [2099/15692] intraday_1100.csv.gz  in=195,967,490 out=21,202,693 elapsed=52.6s

  [2100/15692] intraday_10999.csv.gz  in=195,983,560 out=21,217,566 elapsed=52.6s

  [2101/15692] intraday_11000.csv.gz  in=195,997,140 out=21,231,146 elapsed=52.7s

  [2102/15692] intraday_11001.csv.gz  in=196,008,015 out=21,242,021 elapsed=52.7s

  [2103/15692] intraday_11003.csv.gz  in=196,019,187 out=21,253,193 elapsed=52.7s

  [2104/15692] intraday_11002.csv.gz  in=196,035,121 out=21,269,127 elapsed=52.7s

  [2105/15692] intraday_11004.csv.gz  in=196,060,939 out=21,290,509 elapsed=52.7s

  [2106/15692] intraday_11006.csv.gz  in=196,074,254 out=21,303,824 elapsed=52.7s

  [2107/15692] intraday_11005.csv.gz  in=196,087,007 out=21,316,577 elapsed=52.7s

  [2108/15692] intraday_11007.csv.gz  in=196,099,930 out=21,329,500 elapsed=52.8s

  [2109/15692] intraday_11008.csv.gz  in=196,111,150 out=21,340,720 elapsed=52.8s

  [2110/15692] intraday_11009.csv.gz  in=196,124,476 out=21,354,046 elapsed=52.8s

  [2111/15692] intraday_11010.csv.gz  in=196,136,146 out=21,365,716 elapsed=52.8s

  [2112/15692] intraday_1101.csv.gz  in=196,150,327 out=21,365,716 elapsed=52.8s

  [2113/15692] intraday_11011.csv.gz  in=196,162,485 out=21,377,874 elapsed=52.8s

  [2114/15692] intraday_11012.csv.gz  in=196,174,603 out=21,389,992 elapsed=52.8s

  [2115/15692] intraday_11013.csv.gz  in=196,185,727 out=21,401,116 elapsed=52.8s

  [2116/15692] intraday_11014.csv.gz  in=196,197,830 out=21,413,219 elapsed=52.8s

  [2117/15692] intraday_11015.csv.gz  in=196,212,256 out=21,427,645 elapsed=52.9s

  [2118/15692] intraday_11016.csv.gz  in=196,224,591 out=21,439,980 elapsed=52.9s

  [2119/15692] intraday_11017.csv.gz  in=196,236,357 out=21,451,746 elapsed=52.9s

  [2120/15692] intraday_11018.csv.gz  in=196,248,776 out=21,464,165 elapsed=52.9s

  [2121/15692] intraday_11020.csv.gz  in=196,260,666 out=21,476,055 elapsed=52.9s

  [2122/15692] intraday_11019.csv.gz  in=196,274,353 out=21,489,742 elapsed=52.9s

  [2123/15692] intraday_1102.csv.gz  in=196,289,202 out=21,489,742 elapsed=52.9s

  [2124/15692] intraday_11021.csv.gz  in=196,302,566 out=21,503,106 elapsed=52.9s

  [2125/15692] intraday_11024.csv.gz  in=196,314,516 out=21,515,056 elapsed=53.0s

  [2126/15692] intraday_11022.csv.gz  in=196,325,163 out=21,525,703 elapsed=53.0s

  [2127/15692] intraday_11023.csv.gz  in=196,338,716 out=21,539,256 elapsed=53.0s

  [2128/15692] intraday_11025.csv.gz  in=196,352,312 out=21,552,852 elapsed=53.0s

  [2129/15692] intraday_11027.csv.gz  in=196,368,081 out=21,568,621 elapsed=53.0s

  [2130/15692] intraday_1103.csv.gz  in=196,378,803 out=21,568,621 elapsed=53.0s

  [2131/15692] intraday_11028.csv.gz  in=196,394,547 out=21,584,365 elapsed=53.0s

  [2132/15692] intraday_11026.csv.gz  in=196,416,115 out=21,604,846 elapsed=53.0s

  [2133/15692] intraday_11029.csv.gz  in=196,431,363 out=21,620,094 elapsed=53.1s

  [2134/15692] intraday_11030.csv.gz  in=196,447,942 out=21,636,673 elapsed=53.1s

  [2135/15692] intraday_11032.csv.gz  in=196,461,341 out=21,650,072 elapsed=53.1s

  [2136/15692] intraday_11031.csv.gz  in=196,478,433 out=21,667,164 elapsed=53.1s

  [2137/15692] intraday_11034.csv.gz  in=196,489,553 out=21,678,284 elapsed=53.1s

  [2138/15692] intraday_11033.csv.gz  in=196,501,582 out=21,690,313 elapsed=53.1s

  [2139/15692] intraday_11035.csv.gz  in=196,511,987 out=21,700,718 elapsed=53.1s

  [2140/15692] intraday_11036.csv.gz  in=196,525,403 out=21,714,134 elapsed=53.2s

  [2141/15692] intraday_11038.csv.gz  in=196,538,393 out=21,727,124 elapsed=53.2s

  [2142/15692] intraday_11037.csv.gz  in=196,549,084 out=21,737,815 elapsed=53.2s

  [2143/15692] intraday_11039.csv.gz  in=196,562,519 out=21,751,250 elapsed=53.2s

  [2144/15692] intraday_11042.csv.gz  in=196,572,754 out=21,761,485 elapsed=53.2s

  [2145/15692] intraday_1104.csv.gz  in=196,585,439 out=21,761,485 elapsed=53.2s

  [2146/15692] intraday_11041.csv.gz  in=196,595,667 out=21,771,713 elapsed=53.3s

  [2147/15692] intraday_11040.csv.gz  in=196,612,316 out=21,788,362 elapsed=53.3s

  [2148/15692] intraday_11044.csv.gz  in=196,623,990 out=21,800,036 elapsed=53.3s

  [2149/15692] intraday_11045.csv.gz  in=196,635,334 out=21,811,380 elapsed=53.3s

  [2150/15692] intraday_11043.csv.gz  in=196,648,038 out=21,824,084 elapsed=53.3s

  [2151/15692] intraday_11046.csv.gz  in=196,663,993 out=21,840,039 elapsed=53.3s

  [2152/15692] intraday_11047.csv.gz  in=196,679,877 out=21,855,923 elapsed=53.3s

  [2153/15692] intraday_1105.csv.gz  in=196,695,194 out=21,855,923 elapsed=53.4s

  [2154/15692] intraday_11048.csv.gz  in=196,708,779 out=21,869,508 elapsed=53.4s

  [2155/15692] intraday_11049.csv.gz  in=196,723,537 out=21,884,266 elapsed=53.4s

  [2156/15692] intraday_11050.csv.gz  in=196,734,744 out=21,895,473 elapsed=53.4s

  [2157/15692] intraday_11051.csv.gz  in=196,746,548 out=21,907,277 elapsed=53.4s

  [2158/15692] intraday_11052.csv.gz  in=196,758,661 out=21,919,390 elapsed=53.4s

  [2159/15692] intraday_11053.csv.gz  in=196,771,048 out=21,931,777 elapsed=53.4s

  [2160/15692] intraday_11054.csv.gz  in=196,780,795 out=21,941,524 elapsed=53.4s

  [2161/15692] intraday_11055.csv.gz  in=196,787,001 out=21,947,730 elapsed=53.4s

  [2162/15692] intraday_11057.csv.gz  in=196,793,217 out=21,953,946 elapsed=53.4s

  [2163/15692] intraday_11058.csv.gz  in=196,807,250 out=21,967,979 elapsed=53.4s

  [2164/15692] intraday_11056.csv.gz  in=196,817,842 out=21,978,571 elapsed=53.4s

  [2165/15692] intraday_11059.csv.gz  in=196,828,864 out=21,989,593 elapsed=53.5s

  [2166/15692] intraday_1106.csv.gz  in=196,840,242 out=21,989,593 elapsed=53.5s

  [2167/15692] intraday_11060.csv.gz  in=196,854,438 out=22,003,789 elapsed=53.5s

  [2168/15692] intraday_11061.csv.gz  in=196,864,775 out=22,014,126 elapsed=53.5s

  [2169/15692] intraday_11062.csv.gz  in=196,876,602 out=22,025,953 elapsed=53.5s

  [2170/15692] intraday_11063.csv.gz  in=196,889,235 out=22,038,586 elapsed=53.5s

  [2171/15692] intraday_11065.csv.gz  in=196,899,648 out=22,048,999 elapsed=53.6s

  [2172/15692] intraday_11064.csv.gz  in=196,913,071 out=22,062,422 elapsed=53.6s

  [2173/15692] intraday_11066.csv.gz  in=196,924,369 out=22,073,720 elapsed=53.6s

  [2174/15692] intraday_11067.csv.gz  in=196,937,330 out=22,086,681 elapsed=53.6s

  [2175/15692] intraday_11068.csv.gz  in=196,949,839 out=22,099,190 elapsed=53.6s

  [2176/15692] intraday_1107.csv.gz  in=196,960,003 out=22,099,190 elapsed=53.6s

  [2177/15692] intraday_11069.csv.gz  in=196,970,341 out=22,109,528 elapsed=53.6s

  [2178/15692] intraday_11070.csv.gz  in=196,982,600 out=22,121,787 elapsed=53.6s

  [2179/15692] intraday_11072.csv.gz  in=196,993,109 out=22,132,296 elapsed=53.7s

  [2180/15692] intraday_11073.csv.gz  in=197,003,540 out=22,142,727 elapsed=53.7s

  [2181/15692] intraday_11071.csv.gz  in=197,016,252 out=22,155,439 elapsed=53.7s

  [2182/15692] intraday_11075.csv.gz  in=197,028,561 out=22,167,748 elapsed=53.7s

  [2183/15692] intraday_11074.csv.gz  in=197,041,762 out=22,180,949 elapsed=53.7s

  [2184/15692] intraday_11076.csv.gz  in=197,053,930 out=22,193,117 elapsed=53.7s

  [2185/15692] intraday_11077.csv.gz  in=197,063,688 out=22,202,875 elapsed=53.7s

  [2186/15692] intraday_11078.csv.gz  in=197,075,025 out=22,214,212 elapsed=53.7s

  [2187/15692] intraday_11079.csv.gz  in=197,086,100 out=22,225,287 elapsed=53.7s

  [2188/15692] intraday_1108.csv.gz  in=197,099,154 out=22,225,287 elapsed=53.7s

  [2189/15692] intraday_11080.csv.gz  in=197,111,362 out=22,237,495 elapsed=53.8s

  [2190/15692] intraday_11081.csv.gz  in=197,123,160 out=22,249,293 elapsed=53.8s

  [2191/15692] intraday_11083.csv.gz  in=197,134,229 out=22,260,362 elapsed=53.8s

  [2192/15692] intraday_11082.csv.gz  in=197,147,180 out=22,273,313 elapsed=53.8s

  [2193/15692] intraday_11085.csv.gz  in=197,157,897 out=22,284,030 elapsed=53.8s

  [2194/15692] intraday_11086.csv.gz  in=197,168,139 out=22,294,272 elapsed=53.8s

  [2195/15692] intraday_11084.csv.gz  in=197,181,362 out=22,307,495 elapsed=53.8s

  [2196/15692] intraday_11087.csv.gz  in=197,194,662 out=22,320,795 elapsed=53.9s

  [2197/15692] intraday_11088.csv.gz  in=197,209,464 out=22,335,597 elapsed=53.9s

  [2198/15692] intraday_11089.csv.gz  in=197,222,850 out=22,348,983 elapsed=53.9s

  [2199/15692] intraday_1109.csv.gz  in=197,235,501 out=22,348,983 elapsed=53.9s

  [2200/15692] intraday_11090.csv.gz  in=197,244,830 out=22,358,312 elapsed=53.9s

  [2201/15692] intraday_11091.csv.gz  in=197,254,308 out=22,367,790 elapsed=53.9s

  [2202/15692] intraday_11092.csv.gz  in=197,266,001 out=22,379,483 elapsed=53.9s

  [2203/15692] intraday_11093.csv.gz  in=197,278,927 out=22,392,409 elapsed=53.9s

  [2204/15692] intraday_11094.csv.gz  in=197,289,094 out=22,402,576 elapsed=54.0s

  [2205/15692] intraday_11096.csv.gz  in=197,300,241 out=22,413,723 elapsed=54.0s

  [2206/15692] intraday_11095.csv.gz  in=197,311,358 out=22,424,840 elapsed=54.0s

  [2207/15692] intraday_11097.csv.gz  in=197,320,203 out=22,433,685 elapsed=54.0s

  [2208/15692] intraday_11098.csv.gz  in=197,330,194 out=22,443,676 elapsed=54.0s

  [2209/15692] intraday_11099.csv.gz  in=197,340,712 out=22,454,194 elapsed=54.0s

  [2210/15692] intraday_1110.csv.gz  in=197,360,522 out=22,454,194 elapsed=54.0s

  [2211/15692] intraday_11100.csv.gz  in=197,373,711 out=22,467,383 elapsed=54.0s

  [2212/15692] intraday_11101.csv.gz  in=197,386,588 out=22,480,151 elapsed=54.1s

  [2213/15692] intraday_11104.csv.gz  in=197,396,650 out=22,490,213 elapsed=54.1s

  [2214/15692] intraday_11102.csv.gz  in=197,409,426 out=22,502,989 elapsed=54.1s

  [2215/15692] intraday_11103.csv.gz  in=197,421,528 out=22,515,091 elapsed=54.1s

  [2216/15692] intraday_11105.csv.gz  in=197,432,861 out=22,526,424 elapsed=54.1s

  [2217/15692] intraday_11106.csv.gz  in=197,445,117 out=22,538,680 elapsed=54.1s

  [2218/15692] intraday_11108.csv.gz  in=197,456,633 out=22,550,196 elapsed=54.1s

  [2219/15692] intraday_11107.csv.gz  in=197,464,838 out=22,558,401 elapsed=54.1s

  [2220/15692] intraday_1111.csv.gz  in=197,476,488 out=22,558,401 elapsed=54.2s

  [2221/15692] intraday_11109.csv.gz  in=197,487,097 out=22,569,010 elapsed=54.2s

  [2222/15692] intraday_11111.csv.gz  in=197,499,290 out=22,581,203 elapsed=54.2s

  [2223/15692] intraday_11110.csv.gz  in=197,509,990 out=22,591,903 elapsed=54.2s

  [2224/15692] intraday_11112.csv.gz  in=197,522,306 out=22,604,219 elapsed=54.2s

  [2225/15692] intraday_11113.csv.gz  in=197,534,155 out=22,616,068 elapsed=54.2s

  [2226/15692] intraday_11114.csv.gz  in=197,546,246 out=22,628,159 elapsed=54.3s

  [2227/15692] intraday_11115.csv.gz  in=197,558,988 out=22,640,901 elapsed=54.3s

  [2228/15692] intraday_11116.csv.gz  in=197,568,137 out=22,650,050 elapsed=54.3s

  [2229/15692] intraday_11117.csv.gz  in=197,581,149 out=22,663,062 elapsed=54.3s

  [2230/15692] intraday_11118.csv.gz  in=197,592,777 out=22,674,690 elapsed=54.3s

  [2231/15692] intraday_11119.csv.gz  in=197,603,258 out=22,685,171 elapsed=54.3s

  [2232/15692] intraday_1112.csv.gz  in=197,614,472 out=22,685,171 elapsed=54.3s

  [2233/15692] intraday_11120.csv.gz  in=197,626,390 out=22,697,089 elapsed=54.3s

  [2234/15692] intraday_11123.csv.gz  in=197,637,283 out=22,707,982 elapsed=54.4s

  [2235/15692] intraday_11121.csv.gz  in=197,647,613 out=22,718,312 elapsed=54.4s

  [2236/15692] intraday_11124.csv.gz  in=197,663,560 out=22,734,259 elapsed=54.4s

  [2237/15692] intraday_11122.csv.gz  in=197,673,111 out=22,743,810 elapsed=54.4s

  [2238/15692] intraday_11125.csv.gz  in=197,685,761 out=22,756,460 elapsed=54.4s

  [2239/15692] intraday_11126.csv.gz  in=197,698,870 out=22,769,569 elapsed=54.4s

  [2240/15692] intraday_11127.csv.gz  in=197,710,324 out=22,781,023 elapsed=54.4s

  [2241/15692] intraday_11128.csv.gz  in=197,721,748 out=22,792,447 elapsed=54.4s

  [2242/15692] intraday_11129.csv.gz  in=197,732,838 out=22,803,537 elapsed=54.4s

  [2243/15692] intraday_1113.csv.gz  in=197,750,415 out=22,803,537 elapsed=54.5s

  [2244/15692] intraday_11131.csv.gz  in=197,763,381 out=22,816,503 elapsed=54.5s

  [2245/15692] intraday_11130.csv.gz  in=197,774,871 out=22,827,993 elapsed=54.5s

  [2246/15692] intraday_11132.csv.gz  in=197,787,665 out=22,840,787 elapsed=54.5s

  [2247/15692] intraday_11133.csv.gz  in=197,798,214 out=22,851,336 elapsed=54.5s

  [2248/15692] intraday_11134.csv.gz  in=197,808,137 out=22,861,259 elapsed=54.5s

  [2249/15692] intraday_11135.csv.gz  in=197,819,243 out=22,872,365 elapsed=54.5s

  [2250/15692] intraday_11136.csv.gz  in=197,832,492 out=22,885,614 elapsed=54.6s

  [2251/15692] intraday_11137.csv.gz  in=197,842,332 out=22,895,454 elapsed=54.6s

  [2252/15692] intraday_11138.csv.gz  in=197,852,516 out=22,905,638 elapsed=54.6s

  [2253/15692] intraday_11139.csv.gz  in=197,860,994 out=22,914,116 elapsed=54.6s

  [2254/15692] intraday_11140.csv.gz  in=197,870,251 out=22,923,373 elapsed=54.6s

  [2255/15692] intraday_1114.csv.gz  in=197,883,166 out=22,923,373 elapsed=54.6s

  [2256/15692] intraday_11141.csv.gz  in=197,895,164 out=22,935,371 elapsed=54.6s

  [2257/15692] intraday_11142.csv.gz  in=197,909,729 out=22,949,936 elapsed=54.6s

  [2258/15692] intraday_11144.csv.gz  in=197,921,886 out=22,962,093 elapsed=54.7s

  [2259/15692] intraday_11143.csv.gz  in=197,938,141 out=22,978,348 elapsed=54.7s

  [2260/15692] intraday_11146.csv.gz  in=197,949,447 out=22,989,654 elapsed=54.7s

  [2261/15692] intraday_11145.csv.gz  in=197,960,120 out=23,000,327 elapsed=54.7s

  [2262/15692] intraday_11147.csv.gz  in=197,972,953 out=23,013,160 elapsed=54.7s

  [2263/15692] intraday_11148.csv.gz  in=197,984,028 out=23,024,235 elapsed=54.7s

  [2264/15692] intraday_1115.csv.gz  in=197,996,982 out=23,024,235 elapsed=54.7s

  [2265/15692] intraday_11149.csv.gz  in=198,010,627 out=23,037,880 elapsed=54.7s

  [2266/15692] intraday_11150.csv.gz  in=198,021,333 out=23,048,586 elapsed=54.7s

  [2267/15692] intraday_11151.csv.gz  in=198,035,033 out=23,062,286 elapsed=54.8s

  [2268/15692] intraday_11153.csv.gz  in=198,047,165 out=23,074,418 elapsed=54.8s

  [2269/15692] intraday_11152.csv.gz  in=198,059,098 out=23,086,351 elapsed=54.8s

  [2270/15692] intraday_11155.csv.gz  in=198,069,839 out=23,097,092 elapsed=54.8s

  [2271/15692] intraday_11154.csv.gz  in=198,082,470 out=23,109,723 elapsed=54.8s

  [2272/15692] intraday_11157.csv.gz  in=198,092,747 out=23,120,000 elapsed=54.8s

  [2273/15692] intraday_11158.csv.gz  in=198,104,297 out=23,131,550 elapsed=54.8s

  [2274/15692] intraday_11156.csv.gz  in=198,117,291 out=23,144,544 elapsed=54.9s

  [2275/15692] intraday_11159.csv.gz  in=198,127,458 out=23,154,711 elapsed=54.9s

  [2276/15692] intraday_1116.csv.gz  in=198,140,433 out=23,154,711 elapsed=54.9s

  [2277/15692] intraday_11160.csv.gz  in=198,152,310 out=23,166,588 elapsed=54.9s

  [2278/15692] intraday_11163.csv.gz  in=198,162,634 out=23,176,912 elapsed=54.9s

  [2279/15692] intraday_11162.csv.gz  in=198,175,026 out=23,189,304 elapsed=54.9s

  [2280/15692] intraday_11161.csv.gz  in=198,187,407 out=23,201,685 elapsed=54.9s

  [2281/15692] intraday_11164.csv.gz  in=198,200,380 out=23,214,658 elapsed=54.9s

  [2282/15692] intraday_11165.csv.gz  in=198,212,260 out=23,226,538 elapsed=54.9s

  [2283/15692] intraday_11167.csv.gz  in=198,223,622 out=23,237,900 elapsed=55.0s

  [2284/15692] intraday_11169.csv.gz  in=198,236,962 out=23,251,240 elapsed=55.0s

  [2285/15692] intraday_11166.csv.gz  in=198,249,898 out=23,264,176 elapsed=55.0s

  [2286/15692] intraday_11168.csv.gz  in=198,262,226 out=23,276,504 elapsed=55.0s

  [2287/15692] intraday_1117.csv.gz  in=198,274,251 out=23,276,504 elapsed=55.0s

  [2288/15692] intraday_11170.csv.gz  in=198,285,828 out=23,288,081 elapsed=55.0s

  [2289/15692] intraday_11171.csv.gz  in=198,295,918 out=23,298,171 elapsed=55.0s

  [2290/15692] intraday_11172.csv.gz  in=198,308,883 out=23,311,136 elapsed=55.1s

  [2291/15692] intraday_11173.csv.gz  in=198,326,343 out=23,328,596 elapsed=55.1s

  [2292/15692] intraday_11174.csv.gz  in=198,340,661 out=23,342,914 elapsed=55.1s

  [2293/15692] intraday_11175.csv.gz  in=198,354,758 out=23,357,011 elapsed=55.1s

  [2294/15692] intraday_11176.csv.gz  in=198,370,655 out=23,372,908 elapsed=55.1s

  [2295/15692] intraday_11177.csv.gz  in=198,383,335 out=23,385,588 elapsed=55.1s

  [2296/15692] intraday_11178.csv.gz  in=198,397,259 out=23,399,512 elapsed=55.1s

  [2297/15692] intraday_11179.csv.gz  in=198,409,613 out=23,411,866 elapsed=55.1s

  [2298/15692] intraday_1118.csv.gz  in=198,420,182 out=23,411,866 elapsed=55.1s

  [2299/15692] intraday_11180.csv.gz  in=198,432,250 out=23,423,934 elapsed=55.2s

  [2300/15692] intraday_11181.csv.gz  in=198,443,040 out=23,434,724 elapsed=55.2s

  [2301/15692] intraday_11183.csv.gz  in=198,453,900 out=23,445,584 elapsed=55.2s

  [2302/15692] intraday_11182.csv.gz  in=198,465,084 out=23,456,768 elapsed=55.2s

  [2303/15692] intraday_11184.csv.gz  in=198,477,240 out=23,468,924 elapsed=55.2s

  [2304/15692] intraday_11186.csv.gz  in=198,491,411 out=23,483,095 elapsed=55.2s

  [2305/15692] intraday_11185.csv.gz  in=198,502,953 out=23,494,637 elapsed=55.2s

  [2306/15692] intraday_11187.csv.gz  in=198,513,328 out=23,505,012 elapsed=55.2s

  [2307/15692] intraday_11188.csv.gz  in=198,523,867 out=23,515,551 elapsed=55.3s

  [2308/15692] intraday_1119.csv.gz  in=198,537,464 out=23,515,551 elapsed=55.3s

  [2309/15692] intraday_11189.csv.gz  in=198,548,301 out=23,526,388 elapsed=55.3s

  [2310/15692] intraday_11190.csv.gz  in=198,560,060 out=23,538,147 elapsed=55.3s

  [2311/15692] intraday_11192.csv.gz  in=198,574,280 out=23,552,367 elapsed=55.3s

  [2312/15692] intraday_11191.csv.gz  in=198,584,442 out=23,562,529 elapsed=55.3s

  [2313/15692] intraday_11193.csv.gz  in=198,599,451 out=23,577,538 elapsed=55.4s

  [2314/15692] intraday_11195.csv.gz  in=198,613,319 out=23,591,406 elapsed=55.4s

  [2315/15692] intraday_11194.csv.gz  in=198,627,191 out=23,605,278 elapsed=55.4s

  [2316/15692] intraday_11197.csv.gz  in=198,638,468 out=23,616,555 elapsed=55.4s

  [2317/15692] intraday_11198.csv.gz  in=198,650,510 out=23,628,597 elapsed=55.4s

  [2318/15692] intraday_11196.csv.gz  in=198,663,583 out=23,641,670 elapsed=55.4s

  [2319/15692] intraday_11199.csv.gz  in=198,673,673 out=23,651,760 elapsed=55.4s

  [2320/15692] intraday_1120.csv.gz  in=198,687,522 out=23,651,760 elapsed=55.4s

  [2321/15692] intraday_11200.csv.gz  in=198,700,043 out=23,664,281 elapsed=55.5s

  [2322/15692] intraday_11202.csv.gz  in=198,706,704 out=23,670,942 elapsed=55.5s

  [2323/15692] intraday_11201.csv.gz  in=198,713,776 out=23,678,014 elapsed=55.5s

  [2324/15692] intraday_11203.csv.gz  in=198,726,203 out=23,690,441 elapsed=55.5s

  [2325/15692] intraday_11204.csv.gz  in=198,727,577 out=23,691,815 elapsed=55.5s

  [2326/15692] intraday_11206.csv.gz  in=198,732,694 out=23,693,140 elapsed=55.5s

  [2327/15692] intraday_11205.csv.gz  in=198,741,356 out=23,700,763 elapsed=55.5s

  [2328/15692] intraday_11207.csv.gz  in=198,750,132 out=23,708,173 elapsed=55.5s

  [2329/15692] intraday_11209.csv.gz  in=198,760,555 out=23,718,596 elapsed=55.5s

  [2330/15692] intraday_1121.csv.gz  in=198,775,763 out=23,718,596 elapsed=55.5s

  [2331/15692] intraday_11208.csv.gz  in=198,789,454 out=23,732,287 elapsed=55.5s

  [2332/15692] intraday_11210.csv.gz  in=198,804,473 out=23,747,306 elapsed=55.6s

  [2333/15692] intraday_11211.csv.gz  in=198,814,040 out=23,756,873 elapsed=55.6s

  [2334/15692] intraday_11212.csv.gz  in=198,824,910 out=23,767,743 elapsed=55.6s

  [2335/15692] intraday_11214.csv.gz  in=198,838,500 out=23,781,333 elapsed=55.6s

  [2336/15692] intraday_11213.csv.gz  in=198,850,845 out=23,793,678 elapsed=55.6s

  [2337/15692] intraday_11215.csv.gz  in=198,859,905 out=23,802,738 elapsed=55.6s

  [2338/15692] intraday_11216.csv.gz  in=198,871,773 out=23,814,606 elapsed=55.6s

  [2339/15692] intraday_11217.csv.gz  in=198,884,449 out=23,827,282 elapsed=55.6s

  [2340/15692] intraday_11218.csv.gz  in=198,896,775 out=23,839,608 elapsed=55.7s

  [2341/15692] intraday_11219.csv.gz  in=198,906,602 out=23,849,435 elapsed=55.7s

  [2342/15692] intraday_1122.csv.gz  in=198,922,545 out=23,849,435 elapsed=55.7s

  [2343/15692] intraday_11220.csv.gz  in=198,938,367 out=23,864,520 elapsed=55.7s

  [2344/15692] intraday_11221.csv.gz  in=198,950,211 out=23,876,364 elapsed=55.7s

  [2345/15692] intraday_11222.csv.gz  in=198,959,784 out=23,885,937 elapsed=55.7s

  [2346/15692] intraday_11223.csv.gz  in=198,970,754 out=23,896,907 elapsed=55.7s

  [2347/15692] intraday_11224.csv.gz  in=198,981,854 out=23,908,007 elapsed=55.8s

  [2348/15692] intraday_11225.csv.gz  in=198,994,572 out=23,920,725 elapsed=55.8s

  [2349/15692] intraday_11226.csv.gz  in=199,006,037 out=23,932,190 elapsed=55.8s

  [2350/15692] intraday_11228.csv.gz  in=199,021,921 out=23,946,744 elapsed=55.8s

  [2351/15692] intraday_1123.csv.gz  in=199,035,209 out=23,946,744 elapsed=55.8s

  [2352/15692] intraday_11229.csv.gz  in=199,047,225 out=23,958,760 elapsed=55.8s

  [2353/15692] intraday_11227.csv.gz  in=199,056,901 out=23,968,436 elapsed=55.8s

  [2354/15692] intraday_11230.csv.gz  in=199,069,443 out=23,980,978 elapsed=55.8s

  [2355/15692] intraday_11231.csv.gz  in=199,081,360 out=23,992,895 elapsed=55.8s

  [2356/15692] intraday_11233.csv.gz  in=199,093,461 out=24,004,996 elapsed=55.9s

  [2357/15692] intraday_11234.csv.gz  in=199,104,217 out=24,015,752 elapsed=55.9s

  [2358/15692] intraday_11232.csv.gz  in=199,116,541 out=24,028,076 elapsed=55.9s

  [2359/15692] intraday_11235.csv.gz  in=199,127,031 out=24,038,566 elapsed=55.9s

  [2360/15692] intraday_11236.csv.gz  in=199,137,036 out=24,048,571 elapsed=55.9s

  [2361/15692] intraday_11237.csv.gz  in=199,149,735 out=24,061,270 elapsed=55.9s

  [2362/15692] intraday_11238.csv.gz  in=199,164,426 out=24,075,961 elapsed=55.9s

  [2363/15692] intraday_1124.csv.gz  in=199,176,764 out=24,075,961 elapsed=55.9s

  [2364/15692] intraday_11240.csv.gz  in=199,186,222 out=24,085,419 elapsed=55.9s

  [2365/15692] intraday_11239.csv.gz  in=199,198,766 out=24,097,963 elapsed=55.9s

  [2366/15692] intraday_11241.csv.gz  in=199,208,900 out=24,108,097 elapsed=56.0s

  [2367/15692] intraday_11242.csv.gz  in=199,220,902 out=24,120,099 elapsed=56.0s

  [2368/15692] intraday_11243.csv.gz  in=199,233,102 out=24,132,299 elapsed=56.0s

  [2369/15692] intraday_11244.csv.gz  in=199,243,201 out=24,142,398 elapsed=56.0s

  [2370/15692] intraday_11245.csv.gz  in=199,254,645 out=24,153,842 elapsed=56.0s

  [2371/15692] intraday_11246.csv.gz  in=199,265,767 out=24,164,964 elapsed=56.0s

  [2372/15692] intraday_11247.csv.gz  in=199,275,662 out=24,174,859 elapsed=56.1s

  [2373/15692] intraday_11248.csv.gz  in=199,284,860 out=24,184,057 elapsed=56.1s

  [2374/15692] intraday_11249.csv.gz  in=199,295,829 out=24,195,026 elapsed=56.1s

  [2375/15692] intraday_1125.csv.gz  in=199,308,498 out=24,195,026 elapsed=56.1s

  [2376/15692] intraday_11250.csv.gz  in=199,320,942 out=24,207,470 elapsed=56.1s

  [2377/15692] intraday_11251.csv.gz  in=199,331,588 out=24,218,116 elapsed=56.1s

  [2378/15692] intraday_11253.csv.gz  in=199,343,377 out=24,229,905 elapsed=56.1s

  [2379/15692] intraday_11252.csv.gz  in=199,356,958 out=24,243,486 elapsed=56.1s

  [2380/15692] intraday_11254.csv.gz  in=199,366,992 out=24,253,520 elapsed=56.1s

  [2381/15692] intraday_11255.csv.gz  in=199,377,720 out=24,264,248 elapsed=56.2s

  [2382/15692] intraday_11256.csv.gz  in=199,389,336 out=24,275,864 elapsed=56.2s

  [2383/15692] intraday_11257.csv.gz  in=199,398,383 out=24,284,911 elapsed=56.2s

  [2384/15692] intraday_11258.csv.gz  in=199,413,721 out=24,299,589 elapsed=56.2s

  [2385/15692] intraday_11259.csv.gz  in=199,424,364 out=24,310,232 elapsed=56.2s

  [2386/15692] intraday_1126.csv.gz  in=199,438,548 out=24,310,232 elapsed=56.2s

  [2387/15692] intraday_11260.csv.gz  in=199,449,933 out=24,321,617 elapsed=56.2s

  [2388/15692] intraday_11261.csv.gz  in=199,461,716 out=24,333,400 elapsed=56.2s

  [2389/15692] intraday_11262.csv.gz  in=199,472,559 out=24,344,243 elapsed=56.3s

  [2390/15692] intraday_11263.csv.gz  in=199,486,351 out=24,358,035 elapsed=56.3s

  [2391/15692] intraday_11264.csv.gz  in=199,499,031 out=24,370,715 elapsed=56.3s

  [2392/15692] intraday_11266.csv.gz  in=199,508,687 out=24,380,371 elapsed=56.3s

  [2393/15692] intraday_11265.csv.gz  in=199,520,596 out=24,392,280 elapsed=56.3s

  [2394/15692] intraday_11267.csv.gz  in=199,532,727 out=24,404,411 elapsed=56.3s

  [2395/15692] intraday_11268.csv.gz  in=199,544,820 out=24,416,504 elapsed=56.3s

  [2396/15692] intraday_1127.csv.gz  in=199,556,760 out=24,416,504 elapsed=56.3s

  [2397/15692] intraday_11269.csv.gz  in=199,566,819 out=24,426,563 elapsed=56.3s

  [2398/15692] intraday_11271.csv.gz  in=199,577,435 out=24,437,179 elapsed=56.4s

  [2399/15692] intraday_11272.csv.gz  in=199,587,050 out=24,446,794 elapsed=56.4s

  [2400/15692] intraday_11270.csv.gz  in=199,604,945 out=24,463,318 elapsed=56.4s

  [2401/15692] intraday_11273.csv.gz  in=199,619,211 out=24,477,584 elapsed=56.4s

  [2402/15692] intraday_11274.csv.gz  in=199,633,151 out=24,491,524 elapsed=56.4s

  [2403/15692] intraday_11275.csv.gz  in=199,643,474 out=24,501,847 elapsed=56.4s

  [2404/15692] intraday_11276.csv.gz  in=199,656,766 out=24,515,139 elapsed=56.5s

  [2405/15692] intraday_11277.csv.gz  in=199,668,218 out=24,526,591 elapsed=56.5s

  [2406/15692] intraday_11278.csv.gz  in=199,679,237 out=24,537,610 elapsed=56.5s

  [2407/15692] intraday_11279.csv.gz  in=199,691,856 out=24,550,229 elapsed=56.5s

  [2408/15692] intraday_11280.csv.gz  in=199,703,662 out=24,562,035 elapsed=56.5s

  [2409/15692] intraday_1128.csv.gz  in=199,722,042 out=24,562,035 elapsed=56.5s

  [2410/15692] intraday_11281.csv.gz  in=199,736,579 out=24,575,842 elapsed=56.5s

  [2411/15692] intraday_11282.csv.gz  in=199,750,169 out=24,589,432 elapsed=56.5s

  [2412/15692] intraday_11284.csv.gz  in=199,760,091 out=24,599,354 elapsed=56.5s

  [2413/15692] intraday_11283.csv.gz  in=199,771,606 out=24,610,869 elapsed=56.5s

  [2414/15692] intraday_11285.csv.gz  in=199,781,377 out=24,620,640 elapsed=56.6s

  [2415/15692] intraday_11286.csv.gz  in=199,794,565 out=24,633,828 elapsed=56.6s

  [2416/15692] intraday_11287.csv.gz  in=199,804,435 out=24,643,698 elapsed=56.6s

  [2417/15692] intraday_11288.csv.gz  in=199,815,214 out=24,654,477 elapsed=56.6s

  [2418/15692] intraday_1129.csv.gz  in=199,828,525 out=24,654,477 elapsed=56.6s

  [2419/15692] intraday_11289.csv.gz  in=199,836,881 out=24,662,833 elapsed=56.6s

  [2420/15692] intraday_11290.csv.gz  in=199,846,110 out=24,672,062 elapsed=56.6s

  [2421/15692] intraday_11291.csv.gz  in=199,856,929 out=24,682,881 elapsed=56.6s

  [2422/15692] intraday_11294.csv.gz  in=199,869,013 out=24,694,965 elapsed=56.6s

  [2423/15692] intraday_11293.csv.gz  in=199,885,827 out=24,711,779 elapsed=56.6s

  [2424/15692] intraday_11292.csv.gz  in=199,899,891 out=24,725,843 elapsed=56.7s

  [2425/15692] intraday_11295.csv.gz  in=199,910,077 out=24,736,029 elapsed=56.7s

  [2426/15692] intraday_11296.csv.gz  in=199,921,257 out=24,747,209 elapsed=56.7s

  [2427/15692] intraday_11298.csv.gz  in=199,932,355 out=24,758,307 elapsed=56.7s

  [2428/15692] intraday_1130.csv.gz  in=199,944,617 out=24,758,307 elapsed=56.7s

  [2429/15692] intraday_11299.csv.gz  in=199,957,747 out=24,771,437 elapsed=56.7s

  [2430/15692] intraday_11297.csv.gz  in=199,970,659 out=24,784,349 elapsed=56.7s

  [2431/15692] intraday_11300.csv.gz  in=199,980,618 out=24,794,308 elapsed=56.7s

  [2432/15692] intraday_11303.csv.gz  in=199,991,727 out=24,805,417 elapsed=56.7s

  [2433/15692] intraday_11301.csv.gz  in=200,007,693 out=24,821,383 elapsed=56.7s

  [2434/15692] intraday_11302.csv.gz  in=200,018,534 out=24,832,224 elapsed=56.8s

  [2435/15692] intraday_11304.csv.gz  in=200,032,318 out=24,846,008 elapsed=56.8s

  [2436/15692] intraday_11305.csv.gz  in=200,043,722 out=24,857,412 elapsed=56.8s

  [2437/15692] intraday_11308.csv.gz  in=200,055,770 out=24,869,460 elapsed=56.8s

  [2438/15692] intraday_11307.csv.gz  in=200,065,880 out=24,879,570 elapsed=56.8s

  [2439/15692] intraday_11309.csv.gz  in=200,075,591 out=24,889,281 elapsed=56.8s

  [2440/15692] intraday_11306.csv.gz  in=200,087,360 out=24,901,050 elapsed=56.8s

  [2441/15692] intraday_1131.csv.gz  in=200,099,058 out=24,901,050 elapsed=56.8s

  [2442/15692] intraday_11310.csv.gz  in=200,111,080 out=24,913,072 elapsed=56.8s

  [2443/15692] intraday_11312.csv.gz  in=200,124,059 out=24,926,051 elapsed=56.9s

  [2444/15692] intraday_11311.csv.gz  in=200,135,374 out=24,937,366 elapsed=56.9s

  [2445/15692] intraday_11313.csv.gz  in=200,146,772 out=24,948,764 elapsed=56.9s

  [2446/15692] intraday_11314.csv.gz  in=200,158,374 out=24,960,366 elapsed=56.9s

  [2447/15692] intraday_11317.csv.gz  in=200,169,522 out=24,971,514 elapsed=56.9s

  [2448/15692] intraday_11316.csv.gz  in=200,181,450 out=24,983,442 elapsed=56.9s

  [2449/15692] intraday_11315.csv.gz  in=200,194,226 out=24,996,218 elapsed=56.9s

  [2450/15692] intraday_11318.csv.gz  in=200,206,663 out=25,008,655 elapsed=56.9s

  [2451/15692] intraday_11320.csv.gz  in=200,217,953 out=25,019,945 elapsed=56.9s

  [2452/15692] intraday_11319.csv.gz  in=200,231,040 out=25,033,032 elapsed=57.0s

  [2453/15692] intraday_1132.csv.gz  in=200,244,757 out=25,033,032 elapsed=57.0s

  [2454/15692] intraday_11321.csv.gz  in=200,255,214 out=25,043,489 elapsed=57.0s

  [2455/15692] intraday_11322.csv.gz  in=200,267,330 out=25,055,605 elapsed=57.0s

  [2456/15692] intraday_11323.csv.gz  in=200,284,260 out=25,072,535 elapsed=57.0s

  [2457/15692] intraday_11324.csv.gz  in=200,299,438 out=25,087,713 elapsed=57.0s

  [2458/15692] intraday_11326.csv.gz  in=200,316,128 out=25,104,403 elapsed=57.0s

  [2459/15692] intraday_11325.csv.gz  in=200,329,736 out=25,118,011 elapsed=57.0s

  [2460/15692] intraday_11327.csv.gz  in=200,341,728 out=25,130,003 elapsed=57.0s

  [2461/15692] intraday_11329.csv.gz  in=200,353,145 out=25,141,420 elapsed=57.1s

  [2462/15692] intraday_1133.csv.gz  in=200,366,749 out=25,141,420 elapsed=57.1s

  [2463/15692] intraday_11328.csv.gz  in=200,382,000 out=25,156,671 elapsed=57.1s

  [2464/15692] intraday_11330.csv.gz  in=200,393,223 out=25,167,894 elapsed=57.1s

  [2465/15692] intraday_11333.csv.gz  in=200,403,880 out=25,178,551 elapsed=57.1s

  [2466/15692] intraday_11331.csv.gz  in=200,415,427 out=25,190,098 elapsed=57.1s

  [2467/15692] intraday_11334.csv.gz  in=200,427,301 out=25,201,972 elapsed=57.1s

  [2468/15692] intraday_11332.csv.gz  in=200,440,055 out=25,214,726 elapsed=57.1s

  [2469/15692] intraday_11335.csv.gz  in=200,451,370 out=25,226,041 elapsed=57.2s

  [2470/15692] intraday_11337.csv.gz  in=200,464,002 out=25,238,673 elapsed=57.2s

  [2471/15692] intraday_11336.csv.gz  in=200,478,450 out=25,253,121 elapsed=57.2s

  [2472/15692] intraday_11338.csv.gz  in=200,489,682 out=25,264,353 elapsed=57.2s

  [2473/15692] intraday_11339.csv.gz  in=200,500,490 out=25,275,161 elapsed=57.2s

  [2474/15692] intraday_11340.csv.gz  in=200,512,357 out=25,287,028 elapsed=57.2s

  [2475/15692] intraday_11341.csv.gz  in=200,524,798 out=25,296,799 elapsed=57.2s

  [2476/15692] intraday_1134.csv.gz  in=200,550,299 out=25,296,799 elapsed=57.3s

  [2477/15692] intraday_11343.csv.gz  in=200,564,807 out=25,311,307 elapsed=57.3s

  [2478/15692] intraday_11342.csv.gz  in=200,577,383 out=25,323,883 elapsed=57.3s

  [2479/15692] intraday_11344.csv.gz  in=200,596,659 out=25,342,194 elapsed=57.3s

  [2480/15692] intraday_11345.csv.gz  in=200,610,516 out=25,356,051 elapsed=57.3s

  [2481/15692] intraday_11346.csv.gz  in=200,625,843 out=25,371,378 elapsed=57.3s

  [2482/15692] intraday_11347.csv.gz  in=200,637,956 out=25,383,491 elapsed=57.4s

  [2483/15692] intraday_11348.csv.gz  in=200,649,124 out=25,394,659 elapsed=57.4s

  [2484/15692] intraday_11349.csv.gz  in=200,662,455 out=25,407,990 elapsed=57.4s

  [2485/15692] intraday_1135.csv.gz  in=200,678,499 out=25,407,990 elapsed=57.4s

  [2486/15692] intraday_11351.csv.gz  in=200,688,345 out=25,417,836 elapsed=57.4s

  [2487/15692] intraday_11352.csv.gz  in=200,695,157 out=25,424,648 elapsed=57.4s

  [2488/15692] intraday_11350.csv.gz  in=200,706,649 out=25,436,140 elapsed=57.4s

  [2489/15692] intraday_11353.csv.gz  in=200,717,771 out=25,447,262 elapsed=57.5s

  [2490/15692] intraday_11354.csv.gz  in=200,724,974 out=25,454,465 elapsed=57.5s

  [2491/15692] intraday_11356.csv.gz  in=200,736,705 out=25,466,196 elapsed=57.5s

  [2492/15692] intraday_11355.csv.gz  in=200,750,437 out=25,479,928 elapsed=57.5s

  [2493/15692] intraday_11357.csv.gz  in=200,764,208 out=25,493,699 elapsed=57.5s

  [2494/15692] intraday_11358.csv.gz  in=200,773,508 out=25,502,999 elapsed=57.5s

  [2495/15692] intraday_1136.csv.gz  in=200,784,961 out=25,502,999 elapsed=57.5s

  [2496/15692] intraday_11359.csv.gz  in=200,795,824 out=25,513,862 elapsed=57.5s

  [2497/15692] intraday_11361.csv.gz  in=200,809,384 out=25,527,422 elapsed=57.6s

  [2498/15692] intraday_11362.csv.gz  in=200,820,105 out=25,538,143 elapsed=57.6s

  [2499/15692] intraday_11360.csv.gz  in=200,833,184 out=25,551,222 elapsed=57.6s

  [2500/15692] intraday_11363.csv.gz  in=200,844,342 out=25,562,380 elapsed=57.6s

  [2501/15692] intraday_11364.csv.gz  in=200,857,222 out=25,575,260 elapsed=57.6s

  [2502/15692] intraday_11365.csv.gz  in=200,869,450 out=25,587,488 elapsed=57.6s

  [2503/15692] intraday_11366.csv.gz  in=200,879,663 out=25,597,701 elapsed=57.6s

  [2504/15692] intraday_11367.csv.gz  in=200,892,374 out=25,610,412 elapsed=57.6s

  [2505/15692] intraday_11368.csv.gz  in=200,905,034 out=25,623,072 elapsed=57.7s

  [2506/15692] intraday_11369.csv.gz  in=200,913,914 out=25,631,952 elapsed=57.7s

  [2507/15692] intraday_1137.csv.gz  in=200,927,677 out=25,631,952 elapsed=57.7s

  [2508/15692] intraday_11370.csv.gz  in=200,937,178 out=25,641,453 elapsed=57.7s

  [2509/15692] intraday_11372.csv.gz  in=200,950,151 out=25,654,426 elapsed=57.7s

  [2510/15692] intraday_11371.csv.gz  in=200,962,489 out=25,666,764 elapsed=57.7s

  [2511/15692] intraday_11373.csv.gz  in=200,973,129 out=25,677,404 elapsed=57.7s

  [2512/15692] intraday_11374.csv.gz  in=200,995,892 out=25,697,908 elapsed=57.7s

  [2513/15692] intraday_11375.csv.gz  in=201,005,948 out=25,707,964 elapsed=57.8s

  [2514/15692] intraday_11376.csv.gz  in=201,018,511 out=25,720,527 elapsed=57.8s

  [2515/15692] intraday_11377.csv.gz  in=201,035,568 out=25,736,658 elapsed=57.8s

  [2516/15692] intraday_11379.csv.gz  in=201,048,674 out=25,749,764 elapsed=57.8s

  [2517/15692] intraday_11378.csv.gz  in=201,059,780 out=25,760,870 elapsed=57.8s

  [2518/15692] intraday_1138.csv.gz  in=201,071,228 out=25,760,870 elapsed=57.8s

  [2519/15692] intraday_11380.csv.gz  in=201,083,055 out=25,772,697 elapsed=57.8s

  [2520/15692] intraday_11381.csv.gz  in=201,095,329 out=25,784,971 elapsed=57.9s

  [2521/15692] intraday_11383.csv.gz  in=201,105,198 out=25,794,840 elapsed=57.9s

  [2522/15692] intraday_11382.csv.gz  in=201,115,871 out=25,805,513 elapsed=57.9s

  [2523/15692] intraday_11384.csv.gz  in=201,128,016 out=25,817,658 elapsed=57.9s

  [2524/15692] intraday_11385.csv.gz  in=201,142,980 out=25,832,622 elapsed=57.9s

  [2525/15692] intraday_11387.csv.gz  in=201,152,673 out=25,842,315 elapsed=57.9s

  [2526/15692] intraday_11388.csv.gz  in=201,162,875 out=25,852,517 elapsed=57.9s

  [2527/15692] intraday_11386.csv.gz  in=201,176,107 out=25,865,749 elapsed=57.9s

  [2528/15692] intraday_11389.csv.gz  in=201,188,750 out=25,878,392 elapsed=58.0s

  [2529/15692] intraday_1139.csv.gz  in=201,200,951 out=25,878,392 elapsed=58.0s

  [2530/15692] intraday_11391.csv.gz  in=201,211,853 out=25,889,294 elapsed=58.1s

  [2531/15692] intraday_11390.csv.gz  in=201,223,291 out=25,900,732 elapsed=58.1s

  [2532/15692] intraday_11392.csv.gz  in=201,234,799 out=25,912,240 elapsed=58.2s

  [2533/15692] intraday_11393.csv.gz  in=201,248,362 out=25,925,803 elapsed=58.2s

  [2534/15692] intraday_11394.csv.gz  in=201,258,164 out=25,935,605 elapsed=58.2s

  [2535/15692] intraday_11395.csv.gz  in=201,269,868 out=25,947,309 elapsed=58.2s

  [2536/15692] intraday_11396.csv.gz  in=201,280,543 out=25,957,984 elapsed=58.2s

  [2537/15692] intraday_11397.csv.gz  in=201,293,275 out=25,970,716 elapsed=58.2s

  [2538/15692] intraday_11398.csv.gz  in=201,303,981 out=25,981,422 elapsed=58.2s

  [2539/15692] intraday_11399.csv.gz  in=201,317,211 out=25,994,652 elapsed=58.2s

  [2540/15692] intraday_1140.csv.gz  in=201,330,368 out=25,994,652 elapsed=58.3s

  [2541/15692] intraday_11402.csv.gz  in=201,341,102 out=26,005,386 elapsed=58.3s

  [2542/15692] intraday_11401.csv.gz  in=201,352,294 out=26,016,578 elapsed=58.3s

  [2543/15692] intraday_11400.csv.gz  in=201,364,612 out=26,028,896 elapsed=58.3s

  [2544/15692] intraday_11403.csv.gz  in=201,376,470 out=26,040,754 elapsed=58.3s

  [2545/15692] intraday_11404.csv.gz  in=201,385,438 out=26,049,722 elapsed=58.3s

  [2546/15692] intraday_11405.csv.gz  in=201,397,905 out=26,062,039 elapsed=58.3s

  [2547/15692] intraday_11406.csv.gz  in=201,408,321 out=26,072,455 elapsed=58.3s

  [2548/15692] intraday_11408.csv.gz  in=201,420,970 out=26,085,104 elapsed=58.4s

  [2549/15692] intraday_11407.csv.gz  in=201,431,341 out=26,095,475 elapsed=58.4s

  [2550/15692] intraday_1141.csv.gz  in=201,442,138 out=26,095,475 elapsed=58.4s

  [2551/15692] intraday_11409.csv.gz  in=201,452,998 out=26,106,335 elapsed=58.4s

  [2552/15692] intraday_11410.csv.gz  in=201,466,771 out=26,120,108 elapsed=58.4s

  [2553/15692] intraday_11412.csv.gz  in=201,479,692 out=26,133,029 elapsed=58.4s

  [2554/15692] intraday_11411.csv.gz  in=201,492,216 out=26,145,553 elapsed=58.5s

  [2555/15692] intraday_11414.csv.gz  in=201,504,356 out=26,157,693 elapsed=58.5s

  [2556/15692] intraday_11413.csv.gz  in=201,514,733 out=26,168,070 elapsed=58.5s

  [2557/15692] intraday_11415.csv.gz  in=201,525,578 out=26,178,915 elapsed=58.5s

  [2558/15692] intraday_11416.csv.gz  in=201,536,559 out=26,189,896 elapsed=58.5s

  [2559/15692] intraday_11418.csv.gz  in=201,547,441 out=26,200,778 elapsed=58.5s

  [2560/15692] intraday_11417.csv.gz  in=201,559,451 out=26,212,788 elapsed=58.5s

  [2561/15692] intraday_1142.csv.gz  in=201,571,116 out=26,212,788 elapsed=58.5s

  [2562/15692] intraday_11419.csv.gz  in=201,580,681 out=26,222,353 elapsed=58.5s

  [2563/15692] intraday_11421.csv.gz  in=201,595,104 out=26,236,776 elapsed=58.6s

  [2564/15692] intraday_11422.csv.gz  in=201,607,344 out=26,249,016 elapsed=58.6s

  [2565/15692] intraday_11423.csv.gz  in=201,620,556 out=26,262,228 elapsed=58.6s

  [2566/15692] intraday_11420.csv.gz  in=201,633,382 out=26,275,054 elapsed=58.6s

  [2567/15692] intraday_11424.csv.gz  in=201,646,136 out=26,287,808 elapsed=58.6s

  [2568/15692] intraday_11425.csv.gz  in=201,659,730 out=26,300,451 elapsed=58.6s

  [2569/15692] intraday_11427.csv.gz  in=201,671,620 out=26,312,341 elapsed=58.6s

  [2570/15692] intraday_11426.csv.gz  in=201,683,362 out=26,324,083 elapsed=58.6s

  [2571/15692] intraday_11429.csv.gz  in=201,696,540 out=26,337,261 elapsed=58.6s

  [2572/15692] intraday_11428.csv.gz  in=201,709,733 out=26,350,454 elapsed=58.6s

  [2573/15692] intraday_1143.csv.gz  in=201,725,093 out=26,350,454 elapsed=58.6s

  [2574/15692] intraday_11430.csv.gz  in=201,737,241 out=26,362,602 elapsed=58.7s

  [2575/15692] intraday_11431.csv.gz  in=201,748,117 out=26,373,478 elapsed=58.7s

  [2576/15692] intraday_11432.csv.gz  in=201,758,790 out=26,384,151 elapsed=58.7s

  [2577/15692] intraday_11433.csv.gz  in=201,772,399 out=26,397,760 elapsed=58.7s

  [2578/15692] intraday_11435.csv.gz  in=201,783,298 out=26,408,659 elapsed=58.7s

  [2579/15692] intraday_11434.csv.gz  in=201,793,928 out=26,419,289 elapsed=58.7s

  [2580/15692] intraday_11436.csv.gz  in=201,802,710 out=26,428,071 elapsed=58.7s

  [2581/15692] intraday_11438.csv.gz  in=201,813,259 out=26,438,620 elapsed=58.7s

  [2582/15692] intraday_11437.csv.gz  in=201,822,597 out=26,447,958 elapsed=58.7s

  [2583/15692] intraday_11439.csv.gz  in=201,835,523 out=26,460,884 elapsed=58.7s

  [2584/15692] intraday_1144.csv.gz  in=201,848,735 out=26,460,884 elapsed=58.8s

  [2585/15692] intraday_11440.csv.gz  in=201,869,665 out=26,481,005 elapsed=58.8s

  [2586/15692] intraday_11441.csv.gz  in=201,881,661 out=26,493,001 elapsed=58.8s

  [2587/15692] intraday_11442.csv.gz  in=201,892,430 out=26,503,770 elapsed=58.8s

  [2588/15692] intraday_11444.csv.gz  in=201,906,133 out=26,517,473 elapsed=58.8s

  [2589/15692] intraday_11445.csv.gz  in=201,916,720 out=26,528,060 elapsed=58.8s

  [2590/15692] intraday_11443.csv.gz  in=201,927,552 out=26,538,892 elapsed=58.8s

  [2591/15692] intraday_11447.csv.gz  in=201,936,917 out=26,548,257 elapsed=58.8s

  [2592/15692] intraday_11446.csv.gz  in=201,951,744 out=26,563,084 elapsed=58.8s

  [2593/15692] intraday_11448.csv.gz  in=201,965,193 out=26,576,533 elapsed=58.8s

  [2594/15692] intraday_11449.csv.gz  in=201,977,310 out=26,588,650 elapsed=58.8s

  [2595/15692] intraday_1145.csv.gz  in=201,988,099 out=26,588,650 elapsed=58.8s

  [2596/15692] intraday_11450.csv.gz  in=202,001,120 out=26,601,671 elapsed=58.9s

  [2597/15692] intraday_11451.csv.gz  in=202,014,733 out=26,615,284 elapsed=58.9s

  [2598/15692] intraday_11452.csv.gz  in=202,025,829 out=26,626,380 elapsed=58.9s

  [2599/15692] intraday_11453.csv.gz  in=202,041,826 out=26,641,987 elapsed=58.9s

  [2600/15692] intraday_11455.csv.gz  in=202,052,665 out=26,652,826 elapsed=58.9s

  [2601/15692] intraday_11454.csv.gz  in=202,063,933 out=26,664,094 elapsed=58.9s

  [2602/15692] intraday_11456.csv.gz  in=202,075,645 out=26,675,806 elapsed=58.9s

  [2603/15692] intraday_11457.csv.gz  in=202,085,999 out=26,686,160 elapsed=58.9s

  [2604/15692] intraday_11458.csv.gz  in=202,097,510 out=26,697,671 elapsed=58.9s

  [2605/15692] intraday_1146.csv.gz  in=202,111,712 out=26,697,671 elapsed=59.0s

  [2606/15692] intraday_11459.csv.gz  in=202,124,813 out=26,710,772 elapsed=59.0s

  [2607/15692] intraday_11460.csv.gz  in=202,136,661 out=26,722,620 elapsed=59.0s

  [2608/15692] intraday_11461.csv.gz  in=202,147,896 out=26,733,855 elapsed=59.0s

  [2609/15692] intraday_11464.csv.gz  in=202,159,714 out=26,745,673 elapsed=59.0s

  [2610/15692] intraday_11462.csv.gz  in=202,172,139 out=26,758,098 elapsed=59.0s

  [2611/15692] intraday_11465.csv.gz  in=202,184,876 out=26,770,835 elapsed=59.0s

  [2612/15692] intraday_11463.csv.gz  in=202,197,551 out=26,783,510 elapsed=59.0s

  [2613/15692] intraday_11467.csv.gz  in=202,210,254 out=26,796,213 elapsed=59.1s

  [2614/15692] intraday_11468.csv.gz  in=202,219,613 out=26,805,572 elapsed=59.1s

  [2615/15692] intraday_1147.csv.gz  in=202,231,324 out=26,805,572 elapsed=59.1s

  [2616/15692] intraday_11466.csv.gz  in=202,243,871 out=26,818,119 elapsed=59.1s

  [2617/15692] intraday_11469.csv.gz  in=202,257,708 out=26,831,956 elapsed=59.1s

  [2618/15692] intraday_11471.csv.gz  in=202,271,328 out=26,845,576 elapsed=59.1s

  [2619/15692] intraday_11470.csv.gz  in=202,288,384 out=26,862,632 elapsed=59.2s

  [2620/15692] intraday_11473.csv.gz  in=202,303,498 out=26,877,746 elapsed=59.2s

  [2621/15692] intraday_11472.csv.gz  in=202,317,686 out=26,891,934 elapsed=59.2s

  [2622/15692] intraday_11474.csv.gz  in=202,331,748 out=26,905,996 elapsed=59.2s

  [2623/15692] intraday_11475.csv.gz  in=202,346,810 out=26,921,058 elapsed=59.2s

  [2624/15692] intraday_11477.csv.gz  in=202,358,394 out=26,932,642 elapsed=59.2s

  [2625/15692] intraday_11478.csv.gz  in=202,371,337 out=26,945,585 elapsed=59.2s

  [2626/15692] intraday_11476.csv.gz  in=202,384,497 out=26,958,745 elapsed=59.2s

  [2627/15692] intraday_11479.csv.gz  in=202,396,068 out=26,970,316 elapsed=59.3s

  [2628/15692] intraday_11481.csv.gz  in=202,408,093 out=26,982,341 elapsed=59.3s

  [2629/15692] intraday_1148.csv.gz  in=202,419,361 out=26,982,341 elapsed=59.3s

  [2630/15692] intraday_11480.csv.gz  in=202,430,518 out=26,993,498 elapsed=59.3s

  [2631/15692] intraday_11482.csv.gz  in=202,443,347 out=27,006,327 elapsed=59.3s

  [2632/15692] intraday_11484.csv.gz  in=202,456,156 out=27,019,136 elapsed=59.3s

  [2633/15692] intraday_11485.csv.gz  in=202,467,412 out=27,030,392 elapsed=59.4s

  [2634/15692] intraday_11486.csv.gz  in=202,477,672 out=27,040,652 elapsed=59.4s

  [2635/15692] intraday_11483.csv.gz  in=202,493,501 out=27,056,481 elapsed=59.4s

  [2636/15692] intraday_11487.csv.gz  in=202,506,357 out=27,069,337 elapsed=59.4s

  [2637/15692] intraday_11488.csv.gz  in=202,517,229 out=27,080,209 elapsed=59.4s

  [2638/15692] intraday_1149.csv.gz  in=202,531,412 out=27,080,209 elapsed=59.4s

  [2639/15692] intraday_11489.csv.gz  in=202,543,232 out=27,092,029 elapsed=59.4s

  [2640/15692] intraday_11490.csv.gz  in=202,558,484 out=27,107,281 elapsed=59.4s

  [2641/15692] intraday_11491.csv.gz  in=202,571,507 out=27,120,304 elapsed=59.5s

  [2642/15692] intraday_11492.csv.gz  in=202,584,939 out=27,133,736 elapsed=59.5s

  [2643/15692] intraday_11493.csv.gz  in=202,599,698 out=27,148,495 elapsed=59.5s

  [2644/15692] intraday_11494.csv.gz  in=202,611,039 out=27,159,836 elapsed=59.5s

  [2645/15692] intraday_11495.csv.gz  in=202,624,106 out=27,172,903 elapsed=59.5s

  [2646/15692] intraday_11496.csv.gz  in=202,634,377 out=27,183,174 elapsed=59.5s

  [2647/15692] intraday_11497.csv.gz  in=202,647,332 out=27,196,129 elapsed=59.5s

  [2648/15692] intraday_11499.csv.gz  in=202,654,441 out=27,203,238 elapsed=59.6s

  [2649/15692] intraday_11498.csv.gz  in=202,661,856 out=27,210,653 elapsed=59.6s

  [2650/15692] intraday_1150.csv.gz  in=202,673,487 out=27,210,653 elapsed=59.6s

  [2651/15692] intraday_11500.csv.gz  in=202,685,541 out=27,222,707 elapsed=59.6s

  [2652/15692] intraday_11501.csv.gz  in=202,688,575 out=27,225,741 elapsed=59.6s

  [2653/15692] intraday_11502.csv.gz  in=202,695,424 out=27,231,202 elapsed=59.6s

  [2654/15692] intraday_11503.csv.gz  in=202,708,396 out=27,244,174 elapsed=59.6s

  [2655/15692] intraday_11504.csv.gz  in=202,720,379 out=27,256,157 elapsed=59.6s

  [2656/15692] intraday_11506.csv.gz  in=202,729,290 out=27,265,068 elapsed=59.6s

  [2657/15692] intraday_11507.csv.gz  in=202,740,333 out=27,276,111 elapsed=59.7s

  [2658/15692] intraday_11505.csv.gz  in=202,752,993 out=27,288,771 elapsed=59.7s

  [2659/15692] intraday_11508.csv.gz  in=202,765,271 out=27,301,049 elapsed=59.7s

  [2660/15692] intraday_11509.csv.gz  in=202,779,245 out=27,315,023 elapsed=59.7s

  [2661/15692] intraday_1151.csv.gz  in=202,792,273 out=27,315,023 elapsed=59.7s

  [2662/15692] intraday_11511.csv.gz  in=202,802,947 out=27,325,697 elapsed=59.7s

  [2663/15692] intraday_11510.csv.gz  in=202,814,077 out=27,336,827 elapsed=59.7s

  [2664/15692] intraday_11512.csv.gz  in=202,826,622 out=27,349,372 elapsed=59.7s

  [2665/15692] intraday_11513.csv.gz  in=202,837,688 out=27,360,438 elapsed=59.7s

  [2666/15692] intraday_11514.csv.gz  in=202,849,136 out=27,371,886 elapsed=59.8s

  [2667/15692] intraday_11515.csv.gz  in=202,860,917 out=27,383,667 elapsed=59.8s

  [2668/15692] intraday_11516.csv.gz  in=202,872,222 out=27,394,972 elapsed=59.8s

  [2669/15692] intraday_11517.csv.gz  in=202,881,177 out=27,403,927 elapsed=59.8s

  [2670/15692] intraday_11519.csv.gz  in=202,893,191 out=27,415,941 elapsed=59.8s

  [2671/15692] intraday_11518.csv.gz  in=202,902,934 out=27,425,684 elapsed=59.8s

  [2672/15692] intraday_1152.csv.gz  in=202,929,621 out=27,425,684 elapsed=59.9s

  [2673/15692] intraday_11522.csv.gz  in=202,939,418 out=27,435,481 elapsed=59.9s

  [2674/15692] intraday_11521.csv.gz  in=202,950,765 out=27,446,828 elapsed=59.9s

  [2675/15692] intraday_11523.csv.gz  in=202,962,077 out=27,458,140 elapsed=59.9s

  [2676/15692] intraday_11520.csv.gz  in=202,973,689 out=27,469,752 elapsed=59.9s

  [2677/15692] intraday_11525.csv.gz  in=202,985,548 out=27,481,611 elapsed=59.9s

  [2678/15692] intraday_11524.csv.gz  in=202,996,104 out=27,492,167 elapsed=59.9s

  [2679/15692] intraday_11526.csv.gz  in=203,006,609 out=27,502,672 elapsed=60.0s

  [2680/15692] intraday_11527.csv.gz  in=203,018,828 out=27,514,891 elapsed=60.0s

  [2681/15692] intraday_11528.csv.gz  in=203,029,584 out=27,525,647 elapsed=60.0s

  [2682/15692] intraday_11529.csv.gz  in=203,041,518 out=27,537,581 elapsed=60.0s

  [2683/15692] intraday_1153.csv.gz  in=203,054,126 out=27,537,581 elapsed=60.0s

  [2684/15692] intraday_11530.csv.gz  in=203,065,316 out=27,548,771 elapsed=60.0s

  [2685/15692] intraday_11531.csv.gz  in=203,074,600 out=27,558,055 elapsed=60.0s

  [2686/15692] intraday_11535.csv.gz  in=203,074,797 out=27,558,252 elapsed=60.1s

  [2687/15692] intraday_11532.csv.gz  in=203,086,798 out=27,570,253 elapsed=60.1s

  [2688/15692] intraday_11533.csv.gz  in=203,100,813 out=27,584,268 elapsed=60.1s

  [2689/15692] intraday_11536.csv.gz  in=203,101,206 out=27,584,661 elapsed=60.1s

  [2690/15692] intraday_11534.csv.gz  in=203,112,739 out=27,596,194 elapsed=60.1s

  [2691/15692] intraday_11537.csv.gz  in=203,112,810 out=27,596,265 elapsed=60.1s

  [2692/15692] intraday_11538.csv.gz  in=203,112,845 out=27,596,300 elapsed=60.1s

  [2693/15692] intraday_11539.csv.gz  in=203,113,119 out=27,596,513 elapsed=60.1s

  [2694/15692] intraday_11540.csv.gz  in=203,113,124 out=27,596,518 elapsed=60.1s

  [2695/15692] intraday_1154.csv.gz  in=203,123,672 out=27,596,518 elapsed=60.1s

  [2696/15692] intraday_11541.csv.gz  in=203,123,700 out=27,596,546 elapsed=60.1s

  [2697/15692] intraday_11542.csv.gz  in=203,123,775 out=27,596,621 elapsed=60.1s

  [2698/15692] intraday_11543.csv.gz  in=203,131,501 out=27,604,347 elapsed=60.1s

  [2699/15692] intraday_11544.csv.gz  in=203,141,993 out=27,614,839 elapsed=60.2s

  [2700/15692] intraday_11545.csv.gz  in=203,153,552 out=27,626,398 elapsed=60.2s

  [2701/15692] intraday_11547.csv.gz  in=203,163,665 out=27,636,511 elapsed=60.2s

  [2702/15692] intraday_11546.csv.gz  in=203,199,235 out=27,667,212 elapsed=60.2s

  [2703/15692] intraday_11549.csv.gz  in=203,208,241 out=27,676,218 elapsed=60.2s

  [2704/15692] intraday_11548.csv.gz  in=203,219,942 out=27,687,919 elapsed=60.2s

  [2705/15692] intraday_1155.csv.gz  in=203,233,284 out=27,687,919 elapsed=60.2s

  [2706/15692] intraday_11550.csv.gz  in=203,243,439 out=27,698,074 elapsed=60.2s

  [2707/15692] intraday_11551.csv.gz  in=203,254,109 out=27,708,744 elapsed=60.3s

  [2708/15692] intraday_11552.csv.gz  in=203,264,721 out=27,719,356 elapsed=60.3s

  [2709/15692] intraday_11553.csv.gz  in=203,277,146 out=27,731,781 elapsed=60.3s

  [2710/15692] intraday_11554.csv.gz  in=203,287,750 out=27,742,385 elapsed=60.3s

  [2711/15692] intraday_11555.csv.gz  in=203,298,843 out=27,753,478 elapsed=60.3s

  [2712/15692] intraday_11556.csv.gz  in=203,312,067 out=27,766,702 elapsed=60.3s

  [2713/15692] intraday_11558.csv.gz  in=203,322,517 out=27,777,152 elapsed=60.3s

  [2714/15692] intraday_11557.csv.gz  in=203,332,069 out=27,786,704 elapsed=60.3s

  [2715/15692] intraday_11559.csv.gz  in=203,343,553 out=27,798,188 elapsed=60.3s

  [2716/15692] intraday_1156.csv.gz  in=203,355,506 out=27,798,188 elapsed=60.4s

  [2717/15692] intraday_11560.csv.gz  in=203,365,654 out=27,808,336 elapsed=60.4s

  [2718/15692] intraday_11562.csv.gz  in=203,376,161 out=27,818,843 elapsed=60.4s

  [2719/15692] intraday_11563.csv.gz  in=203,384,887 out=27,827,569 elapsed=60.4s

  [2720/15692] intraday_11564.csv.gz  in=203,396,437 out=27,839,119 elapsed=60.4s

  [2721/15692] intraday_11561.csv.gz  in=203,419,383 out=27,860,282 elapsed=60.4s

  [2722/15692] intraday_11566.csv.gz  in=203,430,013 out=27,870,912 elapsed=60.5s

  [2723/15692] intraday_11565.csv.gz  in=203,441,222 out=27,882,121 elapsed=60.5s

  [2724/15692] intraday_11567.csv.gz  in=203,452,839 out=27,893,738 elapsed=60.5s

  [2725/15692] intraday_11569.csv.gz  in=203,463,333 out=27,904,232 elapsed=60.5s

  [2726/15692] intraday_11568.csv.gz  in=203,475,074 out=27,915,973 elapsed=60.5s

  [2727/15692] intraday_1157.csv.gz  in=203,487,488 out=27,915,973 elapsed=60.5s

  [2728/15692] intraday_11570.csv.gz  in=203,498,980 out=27,927,465 elapsed=60.5s

  [2729/15692] intraday_11571.csv.gz  in=203,511,019 out=27,939,504 elapsed=60.5s

  [2730/15692] intraday_11572.csv.gz  in=203,521,007 out=27,949,492 elapsed=60.5s

  [2731/15692] intraday_11573.csv.gz  in=203,533,189 out=27,961,674 elapsed=60.6s

  [2732/15692] intraday_11574.csv.gz  in=203,543,189 out=27,971,674 elapsed=60.6s

  [2733/15692] intraday_11575.csv.gz  in=203,556,470 out=27,984,955 elapsed=60.6s

  [2734/15692] intraday_11576.csv.gz  in=203,566,016 out=27,994,501 elapsed=60.6s

  [2735/15692] intraday_11577.csv.gz  in=203,579,564 out=28,008,049 elapsed=60.6s

  [2736/15692] intraday_1158.csv.gz  in=203,596,747 out=28,008,049 elapsed=60.6s

  [2737/15692] intraday_11578.csv.gz  in=203,612,797 out=28,022,902 elapsed=60.6s

  [2738/15692] intraday_11579.csv.gz  in=203,626,417 out=28,036,522 elapsed=60.6s

  [2739/15692] intraday_11582.csv.gz  in=203,636,317 out=28,046,422 elapsed=60.6s

  [2740/15692] intraday_11581.csv.gz  in=203,648,060 out=28,058,165 elapsed=60.6s

  [2741/15692] intraday_11580.csv.gz  in=203,660,737 out=28,070,842 elapsed=60.7s

  [2742/15692] intraday_11584.csv.gz  in=203,672,545 out=28,082,650 elapsed=60.7s

  [2743/15692] intraday_11583.csv.gz  in=203,683,971 out=28,094,076 elapsed=60.7s

  [2744/15692] intraday_11585.csv.gz  in=203,695,347 out=28,105,452 elapsed=60.7s

  [2745/15692] intraday_11587.csv.gz  in=203,706,006 out=28,116,111 elapsed=60.7s

  [2746/15692] intraday_11586.csv.gz  in=203,717,841 out=28,127,946 elapsed=60.7s

  [2747/15692] intraday_11588.csv.gz  in=203,727,518 out=28,137,623 elapsed=60.7s

  [2748/15692] intraday_1159.csv.gz  in=203,743,179 out=28,137,623 elapsed=60.7s

  [2749/15692] intraday_11589.csv.gz  in=203,756,646 out=28,151,090 elapsed=60.7s

  [2750/15692] intraday_11592.csv.gz  in=203,766,324 out=28,160,768 elapsed=60.8s

  [2751/15692] intraday_11590.csv.gz  in=203,775,683 out=28,170,127 elapsed=60.8s

  [2752/15692] intraday_11593.csv.gz  in=203,783,329 out=28,177,773 elapsed=60.8s

  [2753/15692] intraday_11591.csv.gz  in=203,794,340 out=28,188,784 elapsed=60.8s

  [2754/15692] intraday_11594.csv.gz  in=203,805,593 out=28,200,037 elapsed=60.8s

  [2755/15692] intraday_11595.csv.gz  in=203,816,659 out=28,211,103 elapsed=60.8s

  [2756/15692] intraday_11598.csv.gz  in=203,828,864 out=28,223,308 elapsed=60.8s

  [2757/15692] intraday_11596.csv.gz  in=203,844,231 out=28,238,675 elapsed=60.8s

  [2758/15692] intraday_11597.csv.gz  in=203,857,132 out=28,251,576 elapsed=60.8s

  [2759/15692] intraday_1160.csv.gz  in=203,866,668 out=28,251,576 elapsed=60.8s

  [2760/15692] intraday_11599.csv.gz  in=203,875,988 out=28,260,896 elapsed=60.8s

  [2761/15692] intraday_11600.csv.gz  in=203,889,570 out=28,274,478 elapsed=60.9s

  [2762/15692] intraday_11602.csv.gz  in=203,902,420 out=28,287,328 elapsed=60.9s

  [2763/15692] intraday_11601.csv.gz  in=203,912,497 out=28,297,405 elapsed=60.9s

  [2764/15692] intraday_11604.csv.gz  in=203,924,328 out=28,309,236 elapsed=60.9s

  [2765/15692] intraday_11603.csv.gz  in=203,934,798 out=28,319,706 elapsed=60.9s

  [2766/15692] intraday_11605.csv.gz  in=203,945,763 out=28,330,671 elapsed=60.9s

  [2767/15692] intraday_11606.csv.gz  in=203,958,453 out=28,343,361 elapsed=60.9s

  [2768/15692] intraday_11607.csv.gz  in=203,970,387 out=28,355,295 elapsed=61.0s

  [2769/15692] intraday_11608.csv.gz  in=203,982,327 out=28,367,235 elapsed=61.0s

  [2770/15692] intraday_11609.csv.gz  in=203,995,544 out=28,380,452 elapsed=61.0s

  [2771/15692] intraday_1161.csv.gz  in=204,007,668 out=28,380,452 elapsed=61.0s

  [2772/15692] intraday_11612.csv.gz  in=204,018,866 out=28,391,650 elapsed=61.0s

  [2773/15692] intraday_11610.csv.gz  in=204,030,318 out=28,403,102 elapsed=61.0s

  [2774/15692] intraday_11611.csv.gz  in=204,040,014 out=28,412,798 elapsed=61.0s

  [2775/15692] intraday_11614.csv.gz  in=204,051,055 out=28,423,839 elapsed=61.0s

  [2776/15692] intraday_11613.csv.gz  in=204,060,714 out=28,433,498 elapsed=61.0s

  [2777/15692] intraday_11615.csv.gz  in=204,074,412 out=28,447,196 elapsed=61.0s

  [2778/15692] intraday_11616.csv.gz  in=204,086,199 out=28,458,983 elapsed=61.1s

  [2779/15692] intraday_11617.csv.gz  in=204,097,073 out=28,469,857 elapsed=61.1s

  [2780/15692] intraday_11618.csv.gz  in=204,109,538 out=28,482,322 elapsed=61.1s

  [2781/15692] intraday_1162.csv.gz  in=204,122,967 out=28,482,322 elapsed=61.1s

  [2782/15692] intraday_11619.csv.gz  in=204,136,618 out=28,495,973 elapsed=61.1s

  [2783/15692] intraday_11621.csv.gz  in=204,147,665 out=28,507,020 elapsed=61.1s

  [2784/15692] intraday_11622.csv.gz  in=204,160,042 out=28,519,397 elapsed=61.1s

  [2785/15692] intraday_11620.csv.gz  in=204,170,614 out=28,529,969 elapsed=61.1s

  [2786/15692] intraday_11623.csv.gz  in=204,184,387 out=28,543,742 elapsed=61.1s

  [2787/15692] intraday_11624.csv.gz  in=204,193,968 out=28,553,323 elapsed=61.1s

  [2788/15692] intraday_11626.csv.gz  in=204,208,823 out=28,568,178 elapsed=61.2s

  [2789/15692] intraday_11625.csv.gz  in=204,221,751 out=28,581,106 elapsed=61.2s

  [2790/15692] intraday_11627.csv.gz  in=204,234,125 out=28,593,480 elapsed=61.2s

  [2791/15692] intraday_1163.csv.gz  in=204,248,261 out=28,593,480 elapsed=61.2s

  [2792/15692] intraday_11628.csv.gz  in=204,260,896 out=28,606,115 elapsed=61.2s

  [2793/15692] intraday_11629.csv.gz  in=204,274,917 out=28,620,136 elapsed=61.2s

  [2794/15692] intraday_11630.csv.gz  in=204,291,245 out=28,636,464 elapsed=61.2s

  [2795/15692] intraday_11633.csv.gz  in=204,302,043 out=28,647,262 elapsed=61.2s

  [2796/15692] intraday_11632.csv.gz  in=204,314,922 out=28,660,141 elapsed=61.2s

  [2797/15692] intraday_11634.csv.gz  in=204,326,595 out=28,671,814 elapsed=61.3s

  [2798/15692] intraday_11631.csv.gz  in=204,340,943 out=28,686,162 elapsed=61.3s

  [2799/15692] intraday_11635.csv.gz  in=204,352,498 out=28,697,717 elapsed=61.3s

  [2800/15692] intraday_11636.csv.gz  in=204,364,861 out=28,710,080 elapsed=61.3s

  [2801/15692] intraday_11637.csv.gz  in=204,375,226 out=28,720,406 elapsed=61.3s

  [2802/15692] intraday_11638.csv.gz  in=204,387,307 out=28,732,487 elapsed=61.3s

  [2803/15692] intraday_11639.csv.gz  in=204,399,705 out=28,744,885 elapsed=61.3s

  [2804/15692] intraday_1164.csv.gz  in=204,410,313 out=28,744,885 elapsed=61.3s

  [2805/15692] intraday_11640.csv.gz  in=204,425,058 out=28,759,630 elapsed=61.4s

  [2806/15692] intraday_11641.csv.gz  in=204,437,926 out=28,772,389 elapsed=61.4s

  [2807/15692] intraday_11642.csv.gz  in=204,448,281 out=28,782,744 elapsed=61.4s

  [2808/15692] intraday_11643.csv.gz  in=204,459,170 out=28,793,633 elapsed=61.4s

  [2809/15692] intraday_11644.csv.gz  in=204,470,225 out=28,804,688 elapsed=61.4s

  [2810/15692] intraday_11645.csv.gz  in=204,481,199 out=28,815,662 elapsed=61.4s

  [2811/15692] intraday_11647.csv.gz  in=204,495,372 out=28,829,835 elapsed=61.4s

  [2812/15692] intraday_11646.csv.gz  in=204,508,923 out=28,843,386 elapsed=61.4s

  [2813/15692] intraday_11648.csv.gz  in=204,521,157 out=28,855,620 elapsed=61.4s

  [2814/15692] intraday_11649.csv.gz  in=204,536,918 out=28,871,381 elapsed=61.4s

  [2815/15692] intraday_1165.csv.gz  in=204,551,221 out=28,871,381 elapsed=61.4s

  [2816/15692] intraday_11651.csv.gz  in=204,564,163 out=28,884,134 elapsed=61.5s

  [2817/15692] intraday_11650.csv.gz  in=204,575,570 out=28,895,541 elapsed=61.5s

  [2818/15692] intraday_11652.csv.gz  in=204,592,542 out=28,911,578 elapsed=61.5s

  [2819/15692] intraday_11653.csv.gz  in=204,602,620 out=28,921,656 elapsed=61.5s

  [2820/15692] intraday_11655.csv.gz  in=204,611,487 out=28,930,274 elapsed=61.5s

  [2821/15692] intraday_11654.csv.gz  in=204,622,271 out=28,940,933 elapsed=61.5s

  [2822/15692] intraday_11658.csv.gz  in=204,622,400 out=28,941,062 elapsed=61.5s

  [2823/15692] intraday_11656.csv.gz  in=204,630,574 out=28,949,236 elapsed=61.5s

  [2824/15692] intraday_11657.csv.gz  in=204,641,044 out=28,959,706 elapsed=61.6s

  [2825/15692] intraday_1166.csv.gz  in=204,652,093 out=28,959,706 elapsed=61.6s

  [2826/15692] intraday_11659.csv.gz  in=204,665,087 out=28,972,700 elapsed=61.6s

  [2827/15692] intraday_11660.csv.gz  in=204,677,000 out=28,984,613 elapsed=61.6s

  [2828/15692] intraday_11661.csv.gz  in=204,690,382 out=28,997,995 elapsed=61.6s

  [2829/15692] intraday_11662.csv.gz  in=204,700,113 out=29,007,726 elapsed=61.6s

  [2830/15692] intraday_11663.csv.gz  in=204,710,578 out=29,018,191 elapsed=61.6s

  [2831/15692] intraday_11664.csv.gz  in=204,723,544 out=29,031,157 elapsed=61.6s

  [2832/15692] intraday_11666.csv.gz  in=204,734,472 out=29,042,085 elapsed=61.7s

  [2833/15692] intraday_11665.csv.gz  in=204,748,893 out=29,056,506 elapsed=61.7s

  [2834/15692] intraday_11667.csv.gz  in=204,760,234 out=29,067,847 elapsed=61.7s

  [2835/15692] intraday_11669.csv.gz  in=204,772,309 out=29,079,922 elapsed=61.7s

  [2836/15692] intraday_11668.csv.gz  in=204,784,557 out=29,092,170 elapsed=61.7s

  [2837/15692] intraday_1167.csv.gz  in=204,796,897 out=29,092,170 elapsed=61.7s

  [2838/15692] intraday_11671.csv.gz  in=204,809,081 out=29,104,354 elapsed=61.8s

  [2839/15692] intraday_11670.csv.gz  in=204,819,655 out=29,114,928 elapsed=61.8s

  [2840/15692] intraday_11673.csv.gz  in=204,829,604 out=29,124,877 elapsed=61.8s

  [2841/15692] intraday_11674.csv.gz  in=204,838,783 out=29,134,056 elapsed=61.8s

  [2842/15692] intraday_11672.csv.gz  in=204,850,760 out=29,146,033 elapsed=61.8s

  [2843/15692] intraday_11675.csv.gz  in=204,862,625 out=29,157,898 elapsed=61.8s

  [2844/15692] intraday_11678.csv.gz  in=204,872,960 out=29,168,233 elapsed=61.8s

  [2845/15692] intraday_11677.csv.gz  in=204,884,590 out=29,179,863 elapsed=61.8s

  [2846/15692] intraday_11679.csv.gz  in=204,895,284 out=29,190,557 elapsed=61.8s

  [2847/15692] intraday_1168.csv.gz  in=204,907,141 out=29,190,557 elapsed=61.9s

  [2848/15692] intraday_11676.csv.gz  in=204,920,660 out=29,204,076 elapsed=61.9s

  [2849/15692] intraday_11680.csv.gz  in=204,932,563 out=29,215,979 elapsed=61.9s

  [2850/15692] intraday_11681.csv.gz  in=204,945,165 out=29,228,581 elapsed=61.9s

  [2851/15692] intraday_11683.csv.gz  in=204,957,432 out=29,240,848 elapsed=61.9s

  [2852/15692] intraday_11682.csv.gz  in=204,969,048 out=29,252,464 elapsed=61.9s

  [2853/15692] intraday_11684.csv.gz  in=204,979,975 out=29,263,391 elapsed=61.9s

  [2854/15692] intraday_11685.csv.gz  in=204,992,177 out=29,275,593 elapsed=61.9s

  [2855/15692] intraday_11686.csv.gz  in=205,002,566 out=29,285,982 elapsed=62.0s

  [2856/15692] intraday_11687.csv.gz  in=205,012,401 out=29,295,817 elapsed=62.0s

  [2857/15692] intraday_11688.csv.gz  in=205,024,885 out=29,308,301 elapsed=62.0s

  [2858/15692] intraday_11689.csv.gz  in=205,038,345 out=29,321,761 elapsed=62.0s

  [2859/15692] intraday_1169.csv.gz  in=205,052,164 out=29,321,761 elapsed=62.0s

  [2860/15692] intraday_11690.csv.gz  in=205,064,878 out=29,334,475 elapsed=62.0s

  [2861/15692] intraday_11691.csv.gz  in=205,074,611 out=29,344,208 elapsed=62.0s

  [2862/15692] intraday_11692.csv.gz  in=205,084,855 out=29,354,452 elapsed=62.1s

  [2863/15692] intraday_11693.csv.gz  in=205,096,725 out=29,366,322 elapsed=62.1s

  [2864/15692] intraday_11694.csv.gz  in=205,110,338 out=29,379,935 elapsed=62.1s

  [2865/15692] intraday_11695.csv.gz  in=205,120,916 out=29,390,513 elapsed=62.1s

  [2866/15692] intraday_11696.csv.gz  in=205,132,267 out=29,401,864 elapsed=62.1s

  [2867/15692] intraday_11697.csv.gz  in=205,142,059 out=29,411,656 elapsed=62.1s

  [2868/15692] intraday_11698.csv.gz  in=205,152,951 out=29,422,548 elapsed=62.1s

  [2869/15692] intraday_1170.csv.gz  in=205,163,387 out=29,422,548 elapsed=62.1s

  [2870/15692] intraday_11699.csv.gz  in=205,173,622 out=29,432,783 elapsed=62.2s

  [2871/15692] intraday_11700.csv.gz  in=205,184,912 out=29,444,073 elapsed=62.2s

  [2872/15692] intraday_11701.csv.gz  in=205,197,823 out=29,456,984 elapsed=62.2s

  [2873/15692] intraday_11702.csv.gz  in=205,209,146 out=29,468,307 elapsed=62.2s

  [2874/15692] intraday_11703.csv.gz  in=205,220,867 out=29,480,028 elapsed=62.2s

  [2875/15692] intraday_11705.csv.gz  in=205,230,677 out=29,489,838 elapsed=62.2s

  [2876/15692] intraday_11704.csv.gz  in=205,243,408 out=29,502,569 elapsed=62.2s

  [2877/15692] intraday_11706.csv.gz  in=205,255,228 out=29,514,389 elapsed=62.2s

  [2878/15692] intraday_11707.csv.gz  in=205,265,972 out=29,525,133 elapsed=62.2s

  [2879/15692] intraday_11708.csv.gz  in=205,276,530 out=29,535,691 elapsed=62.2s

  [2880/15692] intraday_11709.csv.gz  in=205,287,963 out=29,547,124 elapsed=62.3s

  [2881/15692] intraday_1171.csv.gz  in=205,298,689 out=29,547,124 elapsed=62.3s

  [2882/15692] intraday_11710.csv.gz  in=205,308,631 out=29,557,066 elapsed=62.3s

  [2883/15692] intraday_11711.csv.gz  in=205,318,441 out=29,566,876 elapsed=62.3s

  [2884/15692] intraday_11712.csv.gz  in=205,330,569 out=29,579,004 elapsed=62.3s

  [2885/15692] intraday_11713.csv.gz  in=205,342,699 out=29,591,134 elapsed=62.3s

  [2886/15692] intraday_11717.csv.gz  in=205,353,303 out=29,601,738 elapsed=62.3s

  [2887/15692] intraday_11715.csv.gz  in=205,365,253 out=29,613,688 elapsed=62.3s

  [2888/15692] intraday_11714.csv.gz  in=205,375,766 out=29,624,201 elapsed=62.3s

  [2889/15692] intraday_11716.csv.gz  in=205,387,339 out=29,635,774 elapsed=62.4s

  [2890/15692] intraday_11718.csv.gz  in=205,399,276 out=29,647,711 elapsed=62.4s

  [2891/15692] intraday_1172.csv.gz  in=205,413,538 out=29,647,711 elapsed=62.4s

  [2892/15692] intraday_11719.csv.gz  in=205,425,560 out=29,659,733 elapsed=62.4s

  [2893/15692] intraday_11720.csv.gz  in=205,437,078 out=29,671,251 elapsed=62.4s

  [2894/15692] intraday_11723.csv.gz  in=205,447,821 out=29,681,994 elapsed=62.4s

  [2895/15692] intraday_11722.csv.gz  in=205,458,389 out=29,692,562 elapsed=62.4s

  [2896/15692] intraday_11721.csv.gz  in=205,470,074 out=29,704,247 elapsed=62.4s

  [2897/15692] intraday_11724.csv.gz  in=205,480,382 out=29,714,555 elapsed=62.4s

  [2898/15692] intraday_11725.csv.gz  in=205,494,375 out=29,728,548 elapsed=62.4s

  [2899/15692] intraday_11726.csv.gz  in=205,506,276 out=29,740,449 elapsed=62.5s

  [2900/15692] intraday_11727.csv.gz  in=205,520,303 out=29,754,476 elapsed=62.5s

  [2901/15692] intraday_1173.csv.gz  in=205,535,141 out=29,754,476 elapsed=62.5s

  [2902/15692] intraday_11728.csv.gz  in=205,547,216 out=29,766,551 elapsed=62.5s

  [2903/15692] intraday_11729.csv.gz  in=205,557,891 out=29,777,226 elapsed=62.5s

  [2904/15692] intraday_11730.csv.gz  in=205,568,170 out=29,787,505 elapsed=62.5s

  [2905/15692] intraday_11731.csv.gz  in=205,579,775 out=29,799,110 elapsed=62.5s

  [2906/15692] intraday_11732.csv.gz  in=205,592,919 out=29,812,254 elapsed=62.5s

  [2907/15692] intraday_11733.csv.gz  in=205,605,977 out=29,825,312 elapsed=62.5s

  [2908/15692] intraday_11734.csv.gz  in=205,617,475 out=29,836,810 elapsed=62.5s

  [2909/15692] intraday_11736.csv.gz  in=205,627,450 out=29,846,785 elapsed=62.6s

  [2910/15692] intraday_11737.csv.gz  in=205,641,423 out=29,860,758 elapsed=62.6s

  [2911/15692] intraday_11735.csv.gz  in=205,652,717 out=29,872,052 elapsed=62.6s

  [2912/15692] intraday_11738.csv.gz  in=205,662,980 out=29,882,315 elapsed=62.6s

  [2913/15692] intraday_11739.csv.gz  in=205,673,508 out=29,892,843 elapsed=62.6s

  [2914/15692] intraday_1174.csv.gz  in=205,686,180 out=29,892,843 elapsed=62.6s

  [2915/15692] intraday_11740.csv.gz  in=205,696,158 out=29,902,821 elapsed=62.6s

  [2916/15692] intraday_11741.csv.gz  in=205,704,603 out=29,911,266 elapsed=62.6s

  [2917/15692] intraday_11743.csv.gz  in=205,716,525 out=29,923,188 elapsed=62.6s

  [2918/15692] intraday_11742.csv.gz  in=205,727,626 out=29,934,289 elapsed=62.7s

  [2919/15692] intraday_11744.csv.gz  in=205,744,890 out=29,951,553 elapsed=62.7s

  [2920/15692] intraday_11745.csv.gz  in=205,756,917 out=29,963,580 elapsed=62.7s

  [2921/15692] intraday_11746.csv.gz  in=205,769,035 out=29,975,698 elapsed=62.7s

  [2922/15692] intraday_11747.csv.gz  in=205,779,145 out=29,985,808 elapsed=62.7s

  [2923/15692] intraday_11748.csv.gz  in=205,792,939 out=29,999,602 elapsed=62.7s

  [2924/15692] intraday_1175.csv.gz  in=205,805,028 out=29,999,602 elapsed=62.7s

  [2925/15692] intraday_11750.csv.gz  in=205,817,963 out=30,012,537 elapsed=62.7s

  [2926/15692] intraday_11749.csv.gz  in=205,827,491 out=30,022,065 elapsed=62.7s

  [2927/15692] intraday_11752.csv.gz  in=205,837,980 out=30,032,554 elapsed=62.8s

  [2928/15692] intraday_11751.csv.gz  in=205,849,258 out=30,043,832 elapsed=62.8s

  [2929/15692] intraday_11754.csv.gz  in=205,862,809 out=30,057,383 elapsed=62.8s

  [2930/15692] intraday_11753.csv.gz  in=205,874,601 out=30,069,175 elapsed=62.8s

  [2931/15692] intraday_11755.csv.gz  in=205,887,365 out=30,081,939 elapsed=62.8s

  [2932/15692] intraday_11756.csv.gz  in=205,899,036 out=30,093,610 elapsed=62.8s

  [2933/15692] intraday_11757.csv.gz  in=205,911,122 out=30,105,696 elapsed=62.8s

  [2934/15692] intraday_11759.csv.gz  in=205,921,570 out=30,116,144 elapsed=62.8s

  [2935/15692] intraday_11758.csv.gz  in=205,932,951 out=30,127,525 elapsed=62.8s

  [2936/15692] intraday_1176.csv.gz  in=205,945,989 out=30,127,525 elapsed=62.8s

  [2937/15692] intraday_11760.csv.gz  in=205,957,596 out=30,139,132 elapsed=62.9s

  [2938/15692] intraday_11761.csv.gz  in=205,967,110 out=30,148,646 elapsed=62.9s

  [2939/15692] intraday_11762.csv.gz  in=205,978,895 out=30,160,431 elapsed=62.9s

  [2940/15692] intraday_11763.csv.gz  in=205,991,792 out=30,173,328 elapsed=62.9s

  [2941/15692] intraday_11765.csv.gz  in=206,003,008 out=30,184,544 elapsed=62.9s

  [2942/15692] intraday_11764.csv.gz  in=206,015,270 out=30,196,806 elapsed=62.9s

  [2943/15692] intraday_11766.csv.gz  in=206,025,292 out=30,206,828 elapsed=62.9s

  [2944/15692] intraday_1177.csv.gz  in=206,037,365 out=30,206,828 elapsed=63.0s

  [2945/15692] intraday_11769.csv.gz  in=206,049,231 out=30,218,694 elapsed=63.0s

  [2946/15692] intraday_11768.csv.gz  in=206,059,376 out=30,228,839 elapsed=63.0s

  [2947/15692] intraday_11767.csv.gz  in=206,073,460 out=30,242,923 elapsed=63.0s

  [2948/15692] intraday_11770.csv.gz  in=206,086,209 out=30,255,672 elapsed=63.0s

  [2949/15692] intraday_11772.csv.gz  in=206,096,679 out=30,266,142 elapsed=63.0s

  [2950/15692] intraday_11771.csv.gz  in=206,110,189 out=30,279,652 elapsed=63.0s

  [2951/15692] intraday_11773.csv.gz  in=206,123,426 out=30,292,889 elapsed=63.0s

  [2952/15692] intraday_11776.csv.gz  in=206,137,589 out=30,307,052 elapsed=63.1s

  [2953/15692] intraday_11775.csv.gz  in=206,149,389 out=30,318,852 elapsed=63.1s

  [2954/15692] intraday_11774.csv.gz  in=206,165,003 out=30,334,466 elapsed=63.1s

  [2955/15692] intraday_11777.csv.gz  in=206,178,339 out=30,347,802 elapsed=63.1s

  [2956/15692] intraday_11778.csv.gz  in=206,194,442 out=30,363,905 elapsed=63.1s

  [2957/15692] intraday_11779.csv.gz  in=206,208,112 out=30,377,575 elapsed=63.1s

  [2958/15692] intraday_1178.csv.gz  in=206,221,670 out=30,377,575 elapsed=63.1s

  [2959/15692] intraday_11780.csv.gz  in=206,236,141 out=30,392,046 elapsed=63.2s

  [2960/15692] intraday_11782.csv.gz  in=206,249,190 out=30,405,095 elapsed=63.2s

  [2961/15692] intraday_11781.csv.gz  in=206,259,920 out=30,415,825 elapsed=63.2s

  [2962/15692] intraday_11783.csv.gz  in=206,271,232 out=30,427,137 elapsed=63.2s

  [2963/15692] intraday_11785.csv.gz  in=206,281,956 out=30,437,861 elapsed=63.2s

  [2964/15692] intraday_11784.csv.gz  in=206,293,919 out=30,449,824 elapsed=63.2s

  [2965/15692] intraday_11786.csv.gz  in=206,304,757 out=30,460,662 elapsed=63.2s

  [2966/15692] intraday_11787.csv.gz  in=206,317,895 out=30,473,800 elapsed=63.3s

  [2967/15692] intraday_11788.csv.gz  in=206,331,616 out=30,487,521 elapsed=63.3s

  [2968/15692] intraday_11789.csv.gz  in=206,342,089 out=30,497,994 elapsed=63.3s

  [2969/15692] intraday_1179.csv.gz  in=206,357,908 out=30,497,994 elapsed=63.3s

  [2970/15692] intraday_11791.csv.gz  in=206,369,465 out=30,509,551 elapsed=63.3s

  [2971/15692] intraday_11793.csv.gz  in=206,379,540 out=30,519,626 elapsed=63.3s

  [2972/15692] intraday_11790.csv.gz  in=206,390,324 out=30,530,410 elapsed=63.3s

  [2973/15692] intraday_11792.csv.gz  in=206,402,094 out=30,542,180 elapsed=63.3s

  [2974/15692] intraday_11794.csv.gz  in=206,416,535 out=30,556,621 elapsed=63.3s

  [2975/15692] intraday_11796.csv.gz  in=206,429,004 out=30,569,090 elapsed=63.4s

  [2976/15692] intraday_11798.csv.gz  in=206,440,016 out=30,580,102 elapsed=63.4s

  [2977/15692] intraday_11795.csv.gz  in=206,455,079 out=30,595,165 elapsed=63.4s

  [2978/15692] intraday_11799.csv.gz  in=206,467,035 out=30,607,121 elapsed=63.4s

  [2979/15692] intraday_1180.csv.gz  in=206,486,653 out=30,607,121 elapsed=63.4s

  [2980/15692] intraday_11797.csv.gz  in=206,502,336 out=30,622,804 elapsed=63.4s

  [2981/15692] intraday_11800.csv.gz  in=206,515,151 out=30,635,619 elapsed=63.5s

  [2982/15692] intraday_11801.csv.gz  in=206,524,725 out=30,645,193 elapsed=63.5s

  [2983/15692] intraday_11802.csv.gz  in=206,536,355 out=30,656,823 elapsed=63.5s

  [2984/15692] intraday_11803.csv.gz  in=206,542,426 out=30,662,894 elapsed=63.5s

  [2985/15692] intraday_11804.csv.gz  in=206,552,067 out=30,672,535 elapsed=63.5s

  [2986/15692] intraday_11805.csv.gz  in=206,561,059 out=30,681,527 elapsed=63.5s

  [2987/15692] intraday_11806.csv.gz  in=206,584,200 out=30,701,014 elapsed=63.6s

  [2988/15692] intraday_11808.csv.gz  in=206,597,338 out=30,714,152 elapsed=63.6s

  [2989/15692] intraday_11809.csv.gz  in=206,609,910 out=30,726,724 elapsed=63.6s

  [2990/15692] intraday_11807.csv.gz  in=206,623,904 out=30,740,718 elapsed=63.6s

  [2991/15692] intraday_1181.csv.gz  in=206,638,444 out=30,740,718 elapsed=63.6s

  [2992/15692] intraday_11812.csv.gz  in=206,652,274 out=30,754,548 elapsed=63.6s

  [2993/15692] intraday_11810.csv.gz  in=206,661,713 out=30,763,987 elapsed=63.6s

  [2994/15692] intraday_11811.csv.gz  in=206,673,261 out=30,775,535 elapsed=63.6s

  [2995/15692] intraday_11813.csv.gz  in=206,687,528 out=30,789,802 elapsed=63.7s

  [2996/15692] intraday_11816.csv.gz  in=206,700,433 out=30,802,707 elapsed=63.7s

  [2997/15692] intraday_11814.csv.gz  in=206,712,161 out=30,814,435 elapsed=63.7s

  [2998/15692] intraday_11815.csv.gz  in=206,724,259 out=30,826,533 elapsed=63.7s

  [2999/15692] intraday_11817.csv.gz  in=206,736,833 out=30,839,107 elapsed=63.7s

  [3000/15692] intraday_11818.csv.gz  in=206,747,634 out=30,849,908 elapsed=63.7s

  [3001/15692] intraday_11819.csv.gz  in=206,761,026 out=30,863,300 elapsed=63.7s

  [3002/15692] intraday_1182.csv.gz  in=206,775,682 out=30,863,300 elapsed=63.8s

  [3003/15692] intraday_11820.csv.gz  in=206,788,427 out=30,876,045 elapsed=63.8s

  [3004/15692] intraday_11821.csv.gz  in=206,797,687 out=30,885,305 elapsed=63.8s

  [3005/15692] intraday_11823.csv.gz  in=206,811,379 out=30,898,997 elapsed=63.8s

  [3006/15692] intraday_11824.csv.gz  in=206,826,088 out=30,913,706 elapsed=63.8s

  [3007/15692] intraday_11822.csv.gz  in=206,837,460 out=30,925,078 elapsed=63.8s

  [3008/15692] intraday_11825.csv.gz  in=206,847,754 out=30,935,372 elapsed=63.8s

  [3009/15692] intraday_11826.csv.gz  in=206,858,040 out=30,945,658 elapsed=63.8s

  [3010/15692] intraday_11827.csv.gz  in=206,868,775 out=30,956,393 elapsed=63.9s

  [3011/15692] intraday_11828.csv.gz  in=206,881,265 out=30,968,883 elapsed=63.9s

  [3012/15692] intraday_1183.csv.gz  in=206,896,268 out=30,968,883 elapsed=63.9s

  [3013/15692] intraday_11829.csv.gz  in=206,908,635 out=30,981,250 elapsed=63.9s

  [3014/15692] intraday_11831.csv.gz  in=206,921,917 out=30,994,532 elapsed=63.9s

  [3015/15692] intraday_11830.csv.gz  in=206,933,754 out=31,006,369 elapsed=63.9s

  [3016/15692] intraday_11832.csv.gz  in=206,945,365 out=31,017,980 elapsed=64.0s

  [3017/15692] intraday_11834.csv.gz  in=206,957,312 out=31,029,927 elapsed=64.0s

  [3018/15692] intraday_11833.csv.gz  in=206,969,081 out=31,041,696 elapsed=64.0s

  [3019/15692] intraday_11835.csv.gz  in=206,979,142 out=31,051,757 elapsed=64.0s

  [3020/15692] intraday_11836.csv.gz  in=206,991,893 out=31,064,508 elapsed=64.0s

  [3021/15692] intraday_11837.csv.gz  in=207,005,542 out=31,078,157 elapsed=64.0s

  [3022/15692] intraday_11838.csv.gz  in=207,018,583 out=31,091,198 elapsed=64.1s

  [3023/15692] intraday_1184.csv.gz  in=207,032,329 out=31,091,198 elapsed=64.1s

  [3024/15692] intraday_11839.csv.gz  in=207,042,635 out=31,101,504 elapsed=64.1s

  [3025/15692] intraday_11840.csv.gz  in=207,054,204 out=31,113,073 elapsed=64.1s

  [3026/15692] intraday_11843.csv.gz  in=207,066,068 out=31,124,937 elapsed=64.1s

  [3027/15692] intraday_11842.csv.gz  in=207,079,045 out=31,137,914 elapsed=64.1s

  [3028/15692] intraday_11841.csv.gz  in=207,091,519 out=31,150,388 elapsed=64.1s

  [3029/15692] intraday_11844.csv.gz  in=207,102,301 out=31,161,170 elapsed=64.1s

  [3030/15692] intraday_11845.csv.gz  in=207,113,031 out=31,171,900 elapsed=64.1s

  [3031/15692] intraday_11846.csv.gz  in=207,123,881 out=31,182,750 elapsed=64.1s

  [3032/15692] intraday_11847.csv.gz  in=207,135,460 out=31,194,329 elapsed=64.2s

  [3033/15692] intraday_11849.csv.gz  in=207,146,007 out=31,204,876 elapsed=64.2s

  [3034/15692] intraday_11848.csv.gz  in=207,159,507 out=31,218,376 elapsed=64.2s

  [3035/15692] intraday_1185.csv.gz  in=207,171,770 out=31,218,376 elapsed=64.2s

  [3036/15692] intraday_11850.csv.gz  in=207,184,242 out=31,230,848 elapsed=64.2s

  [3037/15692] intraday_11853.csv.gz  in=207,195,826 out=31,242,432 elapsed=64.2s

  [3038/15692] intraday_11852.csv.gz  in=207,207,689 out=31,254,295 elapsed=64.3s

  [3039/15692] intraday_11851.csv.gz  in=207,221,755 out=31,268,361 elapsed=64.3s

  [3040/15692] intraday_11854.csv.gz  in=207,233,701 out=31,280,307 elapsed=64.3s

  [3041/15692] intraday_11856.csv.gz  in=207,244,034 out=31,290,640 elapsed=64.3s

  [3042/15692] intraday_11855.csv.gz  in=207,256,093 out=31,302,699 elapsed=64.3s

  [3043/15692] intraday_11857.csv.gz  in=207,268,159 out=31,314,765 elapsed=64.3s

  [3044/15692] intraday_11858.csv.gz  in=207,277,351 out=31,323,957 elapsed=64.3s

  [3045/15692] intraday_11859.csv.gz  in=207,288,385 out=31,334,991 elapsed=64.3s

  [3046/15692] intraday_11860.csv.gz  in=207,298,863 out=31,345,469 elapsed=64.3s

  [3047/15692] intraday_11861.csv.gz  in=207,312,361 out=31,358,967 elapsed=64.3s

  [3048/15692] intraday_1186.csv.gz  in=207,333,923 out=31,358,967 elapsed=64.3s

  [3049/15692] intraday_11863.csv.gz  in=207,345,508 out=31,370,552 elapsed=64.4s

  [3050/15692] intraday_11862.csv.gz  in=207,358,559 out=31,383,603 elapsed=64.4s

  [3051/15692] intraday_11864.csv.gz  in=207,370,894 out=31,395,938 elapsed=64.4s

  [3052/15692] intraday_11866.csv.gz  in=207,382,247 out=31,407,250 elapsed=64.4s

  [3053/15692] intraday_11865.csv.gz  in=207,392,820 out=31,417,823 elapsed=64.4s

  [3054/15692] intraday_11867.csv.gz  in=207,405,279 out=31,430,282 elapsed=64.4s

  [3055/15692] intraday_11868.csv.gz  in=207,415,876 out=31,440,879 elapsed=64.4s

  [3056/15692] intraday_11869.csv.gz  in=207,427,144 out=31,452,147 elapsed=64.4s

  [3057/15692] intraday_1187.csv.gz  in=207,441,249 out=31,452,147 elapsed=64.5s

  [3058/15692] intraday_11870.csv.gz  in=207,453,810 out=31,464,708 elapsed=64.5s

  [3059/15692] intraday_11871.csv.gz  in=207,463,234 out=31,474,132 elapsed=64.5s

  [3060/15692] intraday_11872.csv.gz  in=207,477,599 out=31,488,242 elapsed=64.5s

  [3061/15692] intraday_11873.csv.gz  in=207,492,255 out=31,502,898 elapsed=64.5s

  [3062/15692] intraday_11874.csv.gz  in=207,503,684 out=31,514,327 elapsed=64.5s

  [3063/15692] intraday_11876.csv.gz  in=207,514,124 out=31,524,767 elapsed=64.5s

  [3064/15692] intraday_11875.csv.gz  in=207,527,874 out=31,538,517 elapsed=64.5s

  [3065/15692] intraday_11877.csv.gz  in=207,537,462 out=31,548,105 elapsed=64.5s

  [3066/15692] intraday_11878.csv.gz  in=207,551,155 out=31,561,798 elapsed=64.5s

  [3067/15692] intraday_1188.csv.gz  in=207,563,068 out=31,561,798 elapsed=64.6s

  [3068/15692] intraday_11880.csv.gz  in=207,574,681 out=31,573,411 elapsed=64.6s

  [3069/15692] intraday_11879.csv.gz  in=207,587,509 out=31,586,239 elapsed=64.6s

  [3070/15692] intraday_11881.csv.gz  in=207,600,879 out=31,599,609 elapsed=64.6s

  [3071/15692] intraday_11882.csv.gz  in=207,613,854 out=31,612,584 elapsed=64.6s

  [3072/15692] intraday_11884.csv.gz  in=207,625,569 out=31,624,299 elapsed=64.6s

  [3073/15692] intraday_11883.csv.gz  in=207,635,088 out=31,633,818 elapsed=64.6s

  [3074/15692] intraday_11885.csv.gz  in=207,648,513 out=31,647,243 elapsed=64.6s

  [3075/15692] intraday_11887.csv.gz  in=207,658,079 out=31,656,809 elapsed=64.6s

  [3076/15692] intraday_11886.csv.gz  in=207,668,443 out=31,667,173 elapsed=64.7s

  [3077/15692] intraday_11888.csv.gz  in=207,677,133 out=31,675,863 elapsed=64.7s

  [3078/15692] intraday_11889.csv.gz  in=207,688,252 out=31,686,982 elapsed=64.7s

  [3079/15692] intraday_1189.csv.gz  in=207,701,405 out=31,686,982 elapsed=64.7s

  [3080/15692] intraday_11890.csv.gz  in=207,714,156 out=31,699,733 elapsed=64.7s

  [3081/15692] intraday_11893.csv.gz  in=207,726,277 out=31,711,854 elapsed=64.7s

  [3082/15692] intraday_11891.csv.gz  in=207,740,347 out=31,725,924 elapsed=64.8s

  [3083/15692] intraday_11894.csv.gz  in=207,751,704 out=31,737,281 elapsed=64.8s

  [3084/15692] intraday_11892.csv.gz  in=207,768,052 out=31,753,629 elapsed=64.8s

  [3085/15692] intraday_11895.csv.gz  in=207,779,459 out=31,765,036 elapsed=64.8s

  [3086/15692] intraday_11897.csv.gz  in=207,793,462 out=31,779,039 elapsed=64.8s

  [3087/15692] intraday_11898.csv.gz  in=207,804,600 out=31,790,177 elapsed=64.8s

  [3088/15692] intraday_11899.csv.gz  in=207,815,618 out=31,801,195 elapsed=64.8s

  [3089/15692] intraday_11896.csv.gz  in=207,827,878 out=31,813,455 elapsed=64.8s

  [3090/15692] intraday_1190.csv.gz  in=207,840,106 out=31,813,455 elapsed=64.8s

  [3091/15692] intraday_11900.csv.gz  in=207,853,968 out=31,827,317 elapsed=64.9s

  [3092/15692] intraday_11902.csv.gz  in=207,866,486 out=31,839,835 elapsed=64.9s

  [3093/15692] intraday_11901.csv.gz  in=207,879,134 out=31,852,483 elapsed=64.9s

  [3094/15692] intraday_11903.csv.gz  in=207,891,426 out=31,864,775 elapsed=64.9s

  [3095/15692] intraday_11904.csv.gz  in=207,903,186 out=31,876,535 elapsed=64.9s

  [3096/15692] intraday_11905.csv.gz  in=207,915,466 out=31,888,815 elapsed=64.9s

  [3097/15692] intraday_11906.csv.gz  in=207,927,459 out=31,900,808 elapsed=64.9s

  [3098/15692] intraday_11907.csv.gz  in=207,940,044 out=31,913,393 elapsed=64.9s

  [3099/15692] intraday_11908.csv.gz  in=207,951,043 out=31,924,392 elapsed=65.0s

  [3100/15692] intraday_11909.csv.gz  in=207,963,631 out=31,936,980 elapsed=65.0s

  [3101/15692] intraday_1191.csv.gz  in=207,976,089 out=31,936,980 elapsed=65.0s

  [3102/15692] intraday_11910.csv.gz  in=207,989,553 out=31,950,444 elapsed=65.0s

  [3103/15692] intraday_11911.csv.gz  in=208,001,368 out=31,962,259 elapsed=65.0s

  [3104/15692] intraday_11912.csv.gz  in=208,013,051 out=31,973,942 elapsed=65.0s

  [3105/15692] intraday_11913.csv.gz  in=208,024,274 out=31,985,165 elapsed=65.0s

  [3106/15692] intraday_11915.csv.gz  in=208,034,527 out=31,995,418 elapsed=65.1s

  [3107/15692] intraday_11914.csv.gz  in=208,048,985 out=32,009,876 elapsed=65.1s

  [3108/15692] intraday_11917.csv.gz  in=208,062,762 out=32,023,653 elapsed=65.1s

  [3109/15692] intraday_11916.csv.gz  in=208,074,172 out=32,035,063 elapsed=65.1s

  [3110/15692] intraday_11918.csv.gz  in=208,087,800 out=32,048,691 elapsed=65.1s

  [3111/15692] intraday_11919.csv.gz  in=208,097,958 out=32,058,849 elapsed=65.1s

  [3112/15692] intraday_1192.csv.gz  in=208,110,192 out=32,058,849 elapsed=65.1s

  [3113/15692] intraday_11920.csv.gz  in=208,122,993 out=32,071,650 elapsed=65.1s

  [3114/15692] intraday_11922.csv.gz  in=208,137,352 out=32,086,009 elapsed=65.2s

  [3115/15692] intraday_11924.csv.gz  in=208,152,142 out=32,100,799 elapsed=65.2s

  [3116/15692] intraday_11921.csv.gz  in=208,166,689 out=32,115,346 elapsed=65.2s

  [3117/15692] intraday_11923.csv.gz  in=208,179,512 out=32,128,169 elapsed=65.2s

  [3118/15692] intraday_11928.csv.gz  in=208,191,334 out=32,139,991 elapsed=65.2s

  [3119/15692] intraday_11925.csv.gz  in=208,208,524 out=32,157,181 elapsed=65.2s

  [3120/15692] intraday_11926.csv.gz  in=208,222,519 out=32,171,176 elapsed=65.2s

  [3121/15692] intraday_11927.csv.gz  in=208,236,434 out=32,185,091 elapsed=65.3s

  [3122/15692] intraday_1193.csv.gz  in=208,248,417 out=32,185,091 elapsed=65.3s

  [3123/15692] intraday_11929.csv.gz  in=208,261,050 out=32,197,724 elapsed=65.3s

  [3124/15692] intraday_11930.csv.gz  in=208,273,607 out=32,210,281 elapsed=65.3s

  [3125/15692] intraday_11931.csv.gz  in=208,286,106 out=32,222,780 elapsed=65.3s

  [3126/15692] intraday_11933.csv.gz  in=208,298,988 out=32,235,662 elapsed=65.3s

  [3127/15692] intraday_11932.csv.gz  in=208,310,433 out=32,247,107 elapsed=65.3s

  [3128/15692] intraday_11935.csv.gz  in=208,325,565 out=32,262,239 elapsed=65.4s

  [3129/15692] intraday_11934.csv.gz  in=208,337,586 out=32,274,260 elapsed=65.4s

  [3130/15692] intraday_11936.csv.gz  in=208,347,793 out=32,284,467 elapsed=65.4s

  [3131/15692] intraday_11937.csv.gz  in=208,359,064 out=32,295,738 elapsed=65.4s

  [3132/15692] intraday_11938.csv.gz  in=208,370,369 out=32,307,043 elapsed=65.4s

  [3133/15692] intraday_11939.csv.gz  in=208,382,149 out=32,318,823 elapsed=65.4s

  [3134/15692] intraday_1194.csv.gz  in=208,399,840 out=32,318,823 elapsed=65.4s

  [3135/15692] intraday_11940.csv.gz  in=208,410,845 out=32,329,828 elapsed=65.4s

  [3136/15692] intraday_11942.csv.gz  in=208,425,759 out=32,344,742 elapsed=65.5s

  [3137/15692] intraday_11943.csv.gz  in=208,439,373 out=32,358,356 elapsed=65.5s

  [3138/15692] intraday_11941.csv.gz  in=208,452,515 out=32,371,498 elapsed=65.5s

  [3139/15692] intraday_11944.csv.gz  in=208,468,146 out=32,387,129 elapsed=65.5s

  [3140/15692] intraday_11945.csv.gz  in=208,480,499 out=32,399,482 elapsed=65.5s

  [3141/15692] intraday_11946.csv.gz  in=208,492,025 out=32,411,008 elapsed=65.5s

  [3142/15692] intraday_11947.csv.gz  in=208,504,406 out=32,423,389 elapsed=65.5s

  [3143/15692] intraday_11948.csv.gz  in=208,515,163 out=32,434,146 elapsed=65.5s

  [3144/15692] intraday_11949.csv.gz  in=208,527,627 out=32,446,610 elapsed=65.6s

  [3145/15692] intraday_1195.csv.gz  in=208,537,470 out=32,446,610 elapsed=65.6s

  [3146/15692] intraday_11950.csv.gz  in=208,544,007 out=32,453,147 elapsed=65.6s

  [3147/15692] intraday_11952.csv.gz  in=208,555,077 out=32,464,217 elapsed=65.6s

  [3148/15692] intraday_11953.csv.gz  in=208,570,692 out=32,479,832 elapsed=65.6s

  [3149/15692] intraday_11951.csv.gz  in=208,583,248 out=32,491,728 elapsed=65.6s

  [3150/15692] intraday_11954.csv.gz  in=208,596,444 out=32,504,924 elapsed=65.7s

  [3151/15692] intraday_11955.csv.gz  in=208,609,551 out=32,517,901 elapsed=65.7s

  [3152/15692] intraday_11957.csv.gz  in=208,621,512 out=32,529,862 elapsed=65.7s

  [3153/15692] intraday_11956.csv.gz  in=208,632,610 out=32,540,960 elapsed=65.7s

  [3154/15692] intraday_11959.csv.gz  in=208,649,084 out=32,557,434 elapsed=65.7s

  [3155/15692] intraday_11958.csv.gz  in=208,663,748 out=32,572,098 elapsed=65.7s

  [3156/15692] intraday_1196.csv.gz  in=208,683,631 out=32,572,098 elapsed=65.7s

  [3157/15692] intraday_11960.csv.gz  in=208,695,078 out=32,583,545 elapsed=65.8s

  [3158/15692] intraday_11961.csv.gz  in=208,707,088 out=32,595,555 elapsed=65.8s

  [3159/15692] intraday_11962.csv.gz  in=208,720,958 out=32,609,425 elapsed=65.8s

  [3160/15692] intraday_11963.csv.gz  in=208,734,068 out=32,622,535 elapsed=65.8s

  [3161/15692] intraday_11964.csv.gz  in=208,745,424 out=32,633,891 elapsed=65.8s

  [3162/15692] intraday_11965.csv.gz  in=208,758,755 out=32,647,222 elapsed=65.8s

  [3163/15692] intraday_11966.csv.gz  in=208,771,297 out=32,659,764 elapsed=65.9s

  [3164/15692] intraday_11967.csv.gz  in=208,781,178 out=32,669,645 elapsed=65.9s

  [3165/15692] intraday_11968.csv.gz  in=208,792,487 out=32,680,954 elapsed=65.9s

  [3166/15692] intraday_11969.csv.gz  in=208,806,413 out=32,694,880 elapsed=65.9s

  [3167/15692] intraday_1197.csv.gz  in=208,821,601 out=32,694,880 elapsed=65.9s

  [3168/15692] intraday_11970.csv.gz  in=208,834,834 out=32,708,113 elapsed=65.9s

  [3169/15692] intraday_11972.csv.gz  in=208,846,157 out=32,719,436 elapsed=65.9s

  [3170/15692] intraday_11971.csv.gz  in=208,858,586 out=32,731,865 elapsed=65.9s

  [3171/15692] intraday_11974.csv.gz  in=208,870,697 out=32,743,976 elapsed=66.0s

  [3172/15692] intraday_11973.csv.gz  in=208,881,412 out=32,754,691 elapsed=66.0s

  [3173/15692] intraday_11975.csv.gz  in=208,894,418 out=32,767,697 elapsed=66.0s

  [3174/15692] intraday_11976.csv.gz  in=208,907,483 out=32,780,762 elapsed=66.0s

  [3175/15692] intraday_11977.csv.gz  in=208,919,831 out=32,793,110 elapsed=66.0s

  [3176/15692] intraday_11979.csv.gz  in=208,931,626 out=32,804,905 elapsed=66.0s

  [3177/15692] intraday_11978.csv.gz  in=208,943,685 out=32,816,964 elapsed=66.0s

  [3178/15692] intraday_1198.csv.gz  in=208,959,137 out=32,816,964 elapsed=66.0s

  [3179/15692] intraday_11980.csv.gz  in=208,978,174 out=32,834,929 elapsed=66.0s

  [3180/15692] intraday_11982.csv.gz  in=208,991,162 out=32,847,917 elapsed=66.1s

  [3181/15692] intraday_11983.csv.gz  in=209,005,560 out=32,862,315 elapsed=66.1s

  [3182/15692] intraday_11981.csv.gz  in=209,017,017 out=32,873,772 elapsed=66.1s

  [3183/15692] intraday_11985.csv.gz  in=209,027,302 out=32,884,057 elapsed=66.1s

  [3184/15692] intraday_11984.csv.gz  in=209,040,726 out=32,897,481 elapsed=66.1s

  [3185/15692] intraday_11986.csv.gz  in=209,053,209 out=32,909,964 elapsed=66.1s

  [3186/15692] intraday_11987.csv.gz  in=209,066,519 out=32,923,274 elapsed=66.1s

  [3187/15692] intraday_11988.csv.gz  in=209,080,089 out=32,936,844 elapsed=66.1s

  [3188/15692] intraday_1199.csv.gz  in=209,093,801 out=32,936,844 elapsed=66.1s

  [3189/15692] intraday_11989.csv.gz  in=209,106,154 out=32,949,197 elapsed=66.1s

  [3190/15692] intraday_11991.csv.gz  in=209,117,540 out=32,960,583 elapsed=66.1s

  [3191/15692] intraday_11990.csv.gz  in=209,128,652 out=32,971,695 elapsed=66.1s

  [3192/15692] intraday_11992.csv.gz  in=209,140,951 out=32,983,654 elapsed=66.2s

  [3193/15692] intraday_11993.csv.gz  in=209,152,242 out=32,994,945 elapsed=66.2s

  [3194/15692] intraday_11994.csv.gz  in=209,164,519 out=33,007,222 elapsed=66.2s

  [3195/15692] intraday_11996.csv.gz  in=209,176,569 out=33,019,272 elapsed=66.2s

  [3196/15692] intraday_11995.csv.gz  in=209,190,096 out=33,032,799 elapsed=66.2s

  [3197/15692] intraday_11998.csv.gz  in=209,202,359 out=33,045,062 elapsed=66.2s

  [3198/15692] intraday_11997.csv.gz  in=209,218,945 out=33,061,366 elapsed=66.2s

  [3199/15692] intraday_11999.csv.gz  in=209,230,846 out=33,073,267 elapsed=66.2s

  [3200/15692] intraday_12000.csv.gz  in=209,243,333 out=33,085,754 elapsed=66.3s

  [3201/15692] intraday_1200.csv.gz  in=209,266,589 out=33,085,754 elapsed=66.3s

  [3202/15692] intraday_12001.csv.gz  in=209,279,170 out=33,098,335 elapsed=66.3s

  [3203/15692] intraday_12002.csv.gz  in=209,289,343 out=33,108,508 elapsed=66.3s

  [3204/15692] intraday_12003.csv.gz  in=209,301,994 out=33,121,159 elapsed=66.3s

  [3205/15692] intraday_12004.csv.gz  in=209,312,779 out=33,131,944 elapsed=66.3s

  [3206/15692] intraday_12005.csv.gz  in=209,323,494 out=33,142,659 elapsed=66.3s

  [3207/15692] intraday_12006.csv.gz  in=209,336,323 out=33,155,488 elapsed=66.3s

  [3208/15692] intraday_12007.csv.gz  in=209,349,876 out=33,169,041 elapsed=66.3s

  [3209/15692] intraday_12008.csv.gz  in=209,362,220 out=33,181,385 elapsed=66.4s

  [3210/15692] intraday_1201.csv.gz  in=209,375,350 out=33,181,385 elapsed=66.4s

  [3211/15692] intraday_12009.csv.gz  in=209,388,192 out=33,194,227 elapsed=66.4s

  [3212/15692] intraday_12010.csv.gz  in=209,401,071 out=33,207,106 elapsed=66.4s

  [3213/15692] intraday_12012.csv.gz  in=209,413,106 out=33,219,141 elapsed=66.4s

  [3214/15692] intraday_12013.csv.gz  in=209,425,685 out=33,231,720 elapsed=66.4s

  [3215/15692] intraday_12011.csv.gz  in=209,436,059 out=33,242,094 elapsed=66.4s

  [3216/15692] intraday_12014.csv.gz  in=209,447,465 out=33,253,500 elapsed=66.4s

  [3217/15692] intraday_12015.csv.gz  in=209,459,444 out=33,265,479 elapsed=66.5s

  [3218/15692] intraday_12017.csv.gz  in=209,469,283 out=33,275,318 elapsed=66.5s

  [3219/15692] intraday_12016.csv.gz  in=209,481,183 out=33,287,218 elapsed=66.5s

  [3220/15692] intraday_12018.csv.gz  in=209,492,432 out=33,298,467 elapsed=66.5s

  [3221/15692] intraday_1202.csv.gz  in=209,505,942 out=33,298,467 elapsed=66.5s

  [3222/15692] intraday_12019.csv.gz  in=209,528,204 out=33,319,956 elapsed=66.5s

  [3223/15692] intraday_12020.csv.gz  in=209,541,855 out=33,333,607 elapsed=66.6s

  [3224/15692] intraday_12021.csv.gz  in=209,556,052 out=33,347,804 elapsed=66.6s

  [3225/15692] intraday_12022.csv.gz  in=209,568,497 out=33,360,249 elapsed=66.6s

  [3226/15692] intraday_12023.csv.gz  in=209,578,818 out=33,370,570 elapsed=66.6s

  [3227/15692] intraday_12025.csv.gz  in=209,591,676 out=33,383,428 elapsed=66.6s

  [3228/15692] intraday_12024.csv.gz  in=209,603,563 out=33,395,315 elapsed=66.6s

  [3229/15692] intraday_12026.csv.gz  in=209,616,120 out=33,407,872 elapsed=66.6s

  [3230/15692] intraday_12028.csv.gz  in=209,628,438 out=33,420,190 elapsed=66.6s

  [3231/15692] intraday_12027.csv.gz  in=209,642,574 out=33,434,326 elapsed=66.6s

  [3232/15692] intraday_12029.csv.gz  in=209,653,430 out=33,445,182 elapsed=66.6s

  [3233/15692] intraday_1203.csv.gz  in=209,666,902 out=33,445,182 elapsed=66.6s

  [3234/15692] intraday_12030.csv.gz  in=209,677,742 out=33,456,022 elapsed=66.7s

  [3235/15692] intraday_12031.csv.gz  in=209,691,451 out=33,469,731 elapsed=66.7s

  [3236/15692] intraday_12033.csv.gz  in=209,703,268 out=33,481,548 elapsed=66.7s

  [3237/15692] intraday_12034.csv.gz  in=209,713,830 out=33,492,110 elapsed=66.7s

  [3238/15692] intraday_12032.csv.gz  in=209,725,901 out=33,504,181 elapsed=66.7s

  [3239/15692] intraday_12035.csv.gz  in=209,735,497 out=33,513,777 elapsed=66.7s

  [3240/15692] intraday_12036.csv.gz  in=209,747,534 out=33,525,814 elapsed=66.7s

  [3241/15692] intraday_12037.csv.gz  in=209,763,158 out=33,541,438 elapsed=66.7s

  [3242/15692] intraday_12038.csv.gz  in=209,781,813 out=33,560,093 elapsed=66.8s

  [3243/15692] intraday_12039.csv.gz  in=209,794,995 out=33,573,275 elapsed=66.8s

  [3244/15692] intraday_1204.csv.gz  in=209,806,090 out=33,573,275 elapsed=66.8s

  [3245/15692] intraday_12040.csv.gz  in=209,817,883 out=33,585,068 elapsed=66.8s

  [3246/15692] intraday_12041.csv.gz  in=209,828,326 out=33,595,511 elapsed=66.8s

  [3247/15692] intraday_12042.csv.gz  in=209,842,147 out=33,609,332 elapsed=66.8s

  [3248/15692] intraday_12043.csv.gz  in=209,853,187 out=33,620,372 elapsed=66.8s

  [3249/15692] intraday_12045.csv.gz  in=209,863,498 out=33,630,683 elapsed=66.8s

  [3250/15692] intraday_12044.csv.gz  in=209,878,945 out=33,646,130 elapsed=66.9s

  [3251/15692] intraday_12047.csv.gz  in=209,893,243 out=33,660,428 elapsed=66.9s

  [3252/15692] intraday_12046.csv.gz  in=209,905,151 out=33,672,336 elapsed=66.9s

  [3253/15692] intraday_12048.csv.gz  in=209,919,100 out=33,686,285 elapsed=66.9s

  [3254/15692] intraday_12049.csv.gz  in=209,931,736 out=33,698,921 elapsed=66.9s

  [3255/15692] intraday_1205.csv.gz  in=209,945,820 out=33,698,921 elapsed=66.9s

  [3256/15692] intraday_12050.csv.gz  in=209,958,429 out=33,711,530 elapsed=67.0s

  [3257/15692] intraday_12053.csv.gz  in=209,969,422 out=33,722,523 elapsed=67.0s

  [3258/15692] intraday_12051.csv.gz  in=209,982,498 out=33,735,599 elapsed=67.0s

  [3259/15692] intraday_12052.csv.gz  in=209,993,477 out=33,746,578 elapsed=67.0s

  [3260/15692] intraday_12055.csv.gz  in=210,005,494 out=33,758,595 elapsed=67.0s

  [3261/15692] intraday_12054.csv.gz  in=210,018,871 out=33,771,972 elapsed=67.0s

  [3262/15692] intraday_12056.csv.gz  in=210,031,110 out=33,784,211 elapsed=67.0s

  [3263/15692] intraday_12057.csv.gz  in=210,044,646 out=33,797,747 elapsed=67.0s

  [3264/15692] intraday_12058.csv.gz  in=210,057,080 out=33,810,181 elapsed=67.1s

  [3265/15692] intraday_12059.csv.gz  in=210,068,904 out=33,822,005 elapsed=67.1s

  [3266/15692] intraday_1206.csv.gz  in=210,086,572 out=33,822,005 elapsed=67.1s

  [3267/15692] intraday_12060.csv.gz  in=210,099,628 out=33,835,061 elapsed=67.1s

  [3268/15692] intraday_12061.csv.gz  in=210,113,322 out=33,848,755 elapsed=67.1s

  [3269/15692] intraday_12062.csv.gz  in=210,125,549 out=33,860,982 elapsed=67.1s

  [3270/15692] intraday_12064.csv.gz  in=210,138,972 out=33,874,405 elapsed=67.1s

  [3271/15692] intraday_12063.csv.gz  in=210,151,299 out=33,886,732 elapsed=67.1s

  [3272/15692] intraday_12065.csv.gz  in=210,165,103 out=33,900,536 elapsed=67.2s

  [3273/15692] intraday_12066.csv.gz  in=210,175,978 out=33,911,411 elapsed=67.2s

  [3274/15692] intraday_12067.csv.gz  in=210,190,249 out=33,925,682 elapsed=67.2s

  [3275/15692] intraday_12068.csv.gz  in=210,208,436 out=33,943,869 elapsed=67.2s

  [3276/15692] intraday_12069.csv.gz  in=210,221,982 out=33,957,415 elapsed=67.2s

  [3277/15692] intraday_1207.csv.gz  in=210,234,461 out=33,957,415 elapsed=67.2s

  [3278/15692] intraday_12070.csv.gz  in=210,249,563 out=33,972,517 elapsed=67.2s

  [3279/15692] intraday_12071.csv.gz  in=210,266,489 out=33,989,443 elapsed=67.2s

  [3280/15692] intraday_12073.csv.gz  in=210,282,049 out=34,005,003 elapsed=67.3s

  [3281/15692] intraday_12072.csv.gz  in=210,296,936 out=34,019,890 elapsed=67.3s

  [3282/15692] intraday_12074.csv.gz  in=210,312,419 out=34,035,283 elapsed=67.3s

  [3283/15692] intraday_12075.csv.gz  in=210,324,773 out=34,047,637 elapsed=67.3s

  [3284/15692] intraday_12076.csv.gz  in=210,337,851 out=34,060,715 elapsed=67.3s

  [3285/15692] intraday_12078.csv.gz  in=210,349,918 out=34,072,782 elapsed=67.3s

  [3286/15692] intraday_12077.csv.gz  in=210,362,049 out=34,084,913 elapsed=67.3s

  [3287/15692] intraday_12079.csv.gz  in=210,373,950 out=34,096,814 elapsed=67.3s

  [3288/15692] intraday_1208.csv.gz  in=210,398,877 out=34,096,814 elapsed=67.3s

  [3289/15692] intraday_12080.csv.gz  in=210,411,414 out=34,109,351 elapsed=67.4s

  [3290/15692] intraday_12081.csv.gz  in=210,424,427 out=34,122,364 elapsed=67.4s

  [3291/15692] intraday_12082.csv.gz  in=210,439,637 out=34,137,574 elapsed=67.4s

  [3292/15692] intraday_12083.csv.gz  in=210,451,538 out=34,149,475 elapsed=67.4s

  [3293/15692] intraday_12085.csv.gz  in=210,464,609 out=34,162,546 elapsed=67.4s

  [3294/15692] intraday_12084.csv.gz  in=210,475,225 out=34,173,162 elapsed=67.5s

  [3295/15692] intraday_12087.csv.gz  in=210,488,013 out=34,185,950 elapsed=67.5s

  [3296/15692] intraday_12086.csv.gz  in=210,498,683 out=34,196,620 elapsed=67.5s

  [3297/15692] intraday_12088.csv.gz  in=210,512,976 out=34,210,913 elapsed=67.5s

  [3298/15692] intraday_12089.csv.gz  in=210,528,611 out=34,226,548 elapsed=67.5s

  [3299/15692] intraday_1209.csv.gz  in=210,545,934 out=34,226,548 elapsed=67.5s

  [3300/15692] intraday_12090.csv.gz  in=210,560,042 out=34,240,656 elapsed=67.5s

  [3301/15692] intraday_12091.csv.gz  in=210,574,378 out=34,254,992 elapsed=67.5s

  [3302/15692] intraday_12092.csv.gz  in=210,586,463 out=34,267,077 elapsed=67.5s

  [3303/15692] intraday_12093.csv.gz  in=210,599,329 out=34,279,943 elapsed=67.6s

  [3304/15692] intraday_12094.csv.gz  in=210,611,162 out=34,291,776 elapsed=67.6s

  [3305/15692] intraday_12096.csv.gz  in=210,620,115 out=34,300,729 elapsed=67.6s

  [3306/15692] intraday_12095.csv.gz  in=210,635,748 out=34,316,362 elapsed=67.6s

  [3307/15692] intraday_12097.csv.gz  in=210,642,871 out=34,323,485 elapsed=67.6s

  [3308/15692] intraday_12098.csv.gz  in=210,654,864 out=34,335,478 elapsed=67.6s

  [3309/15692] intraday_12099.csv.gz  in=210,660,731 out=34,341,345 elapsed=67.6s

  [3310/15692] intraday_1210.csv.gz  in=210,693,168 out=34,341,345 elapsed=67.7s

  [3311/15692] intraday_12101.csv.gz  in=210,952,363 out=34,363,836 elapsed=67.9s

  [3312/15692] intraday_12103.csv.gz  in=211,192,348 out=34,384,552 elapsed=67.9s

  [3313/15692] intraday_12102.csv.gz  in=211,492,811 out=34,410,893 elapsed=67.9s

  [3314/15692] intraday_12100.csv.gz  in=211,820,512 out=34,444,187 elapsed=67.9s

  [3315/15692] intraday_12104.csv.gz  in=212,141,509 out=34,468,982 elapsed=68.1s

  [3316/15692] intraday_12105.csv.gz  in=212,455,718 out=34,497,428 elapsed=68.1s

  [3317/15692] intraday_12107.csv.gz  in=212,725,299 out=34,521,635 elapsed=68.2s

  [3318/15692] intraday_12106.csv.gz  in=213,052,933 out=34,552,505 elapsed=68.2s

  [3319/15692] intraday_1211.csv.gz  in=213,064,749 out=34,552,505 elapsed=68.2s

  [3320/15692] intraday_12108.csv.gz  in=213,365,675 out=34,577,471 elapsed=68.4s

  [3321/15692] intraday_12109.csv.gz  in=213,663,648 out=34,602,161 elapsed=68.4s

  [3322/15692] intraday_12110.csv.gz  in=213,978,055 out=34,626,649 elapsed=68.5s

  [3323/15692] intraday_12111.csv.gz  in=214,254,888 out=34,650,810 elapsed=68.5s

  [3324/15692] intraday_12114.csv.gz  in=214,469,781 out=34,670,724 elapsed=68.6s

  [3325/15692] intraday_12112.csv.gz  in=214,733,480 out=34,698,274 elapsed=68.7s

  [3326/15692] intraday_12115.csv.gz  in=214,964,170 out=34,721,325 elapsed=68.7s

  [3327/15692] intraday_12113.csv.gz  in=215,251,420 out=34,747,772 elapsed=68.7s

  [3328/15692] intraday_12116.csv.gz  in=215,572,984 out=34,777,066 elapsed=68.9s

  [3329/15692] intraday_12119.csv.gz  in=215,797,920 out=34,797,493 elapsed=68.9s

  [3330/15692] intraday_12118.csv.gz  in=216,050,284 out=34,819,032 elapsed=68.9s

  [3331/15692] intraday_1212.csv.gz  in=216,066,121 out=34,819,032 elapsed=68.9s

  [3332/15692] intraday_12117.csv.gz  in=216,363,515 out=34,844,291 elapsed=69.0s

  [3333/15692] intraday_12122.csv.gz  in=216,614,631 out=34,870,404 elapsed=69.2s

  [3334/15692] intraday_12120.csv.gz  in=216,893,223 out=34,893,234 elapsed=69.2s

  [3335/15692] intraday_12121.csv.gz  in=217,160,061 out=34,917,459 elapsed=69.2s

  [3336/15692] intraday_12123.csv.gz  in=217,441,091 out=34,957,078 elapsed=69.2s

  [3337/15692] intraday_12126.csv.gz  in=217,665,131 out=34,978,753 elapsed=69.4s

  [3338/15692] intraday_12125.csv.gz  in=217,914,967 out=35,001,974 elapsed=69.4s

  [3339/15692] intraday_12124.csv.gz  in=218,194,535 out=35,027,911 elapsed=69.4s

  [3340/15692] intraday_12127.csv.gz  in=218,459,762 out=35,051,869 elapsed=69.4s

  [3341/15692] intraday_1213.csv.gz  in=218,481,451 out=35,051,869 elapsed=69.5s

  [3342/15692] intraday_12128.csv.gz  in=218,733,193 out=35,074,736 elapsed=69.6s

  [3343/15692] intraday_12129.csv.gz  in=219,025,493 out=35,100,730 elapsed=69.7s

  [3344/15692] intraday_12131.csv.gz  in=219,297,836 out=35,125,755 elapsed=69.7s

  [3345/15692] intraday_12132.csv.gz  in=219,530,495 out=35,146,011 elapsed=69.8s

  [3346/15692] intraday_12130.csv.gz  in=219,916,195 out=35,176,258 elapsed=69.8s

  [3347/15692] intraday_12133.csv.gz  in=220,214,766 out=35,203,004 elapsed=69.9s

  [3348/15692] intraday_12134.csv.gz  in=220,507,376 out=35,229,186 elapsed=69.9s

  [3349/15692] intraday_12135.csv.gz  in=220,761,145 out=35,253,860 elapsed=70.0s

  [3350/15692] intraday_12136.csv.gz  in=221,017,636 out=35,278,499 elapsed=70.0s

  [3351/15692] intraday_1214.csv.gz  in=221,033,314 out=35,278,499 elapsed=70.0s

  [3352/15692] intraday_12137.csv.gz  in=221,257,801 out=35,298,427 elapsed=70.1s

  [3353/15692] intraday_12139.csv.gz  in=221,484,570 out=35,326,711 elapsed=70.1s

  [3354/15692] intraday_12138.csv.gz  in=221,775,397 out=35,350,686 elapsed=70.2s

  [3355/15692] intraday_12140.csv.gz  in=222,020,234 out=35,372,138 elapsed=70.2s

  [3356/15692] intraday_12141.csv.gz  in=222,291,389 out=35,396,312 elapsed=70.3s

  [3357/15692] intraday_12142.csv.gz  in=222,558,052 out=35,420,630 elapsed=70.4s

  [3358/15692] intraday_12143.csv.gz  in=222,834,841 out=35,445,692 elapsed=70.4s

  [3359/15692] intraday_12144.csv.gz  in=223,139,207 out=35,473,253 elapsed=70.5s

  [3360/15692] intraday_12145.csv.gz  in=223,382,869 out=35,496,661 elapsed=70.5s

  [3361/15692] intraday_12146.csv.gz  in=223,626,012 out=35,519,467 elapsed=70.6s

  [3362/15692] intraday_1215.csv.gz  in=223,638,830 out=35,519,467 elapsed=70.6s

  [3363/15692] intraday_12148.csv.gz  in=223,856,471 out=35,540,327 elapsed=70.7s

  [3364/15692] intraday_12147.csv.gz  in=224,146,376 out=35,566,423 elapsed=70.7s

  [3365/15692] intraday_12149.csv.gz  in=224,385,444 out=35,589,456 elapsed=70.7s

  [3366/15692] intraday_12150.csv.gz  in=224,629,207 out=35,612,888 elapsed=70.8s

  [3367/15692] intraday_12151.csv.gz  in=224,849,074 out=35,633,171 elapsed=70.8s

  [3368/15692] intraday_12153.csv.gz  in=225,090,563 out=35,654,444 elapsed=70.9s

  [3369/15692] intraday_12152.csv.gz  in=225,427,243 out=35,682,467 elapsed=71.0s

  [3370/15692] intraday_12154.csv.gz  in=225,680,141 out=35,706,373 elapsed=71.0s

  [3371/15692] intraday_12155.csv.gz  in=225,987,689 out=35,734,529 elapsed=71.1s

  [3372/15692] intraday_12156.csv.gz  in=226,270,380 out=35,760,155 elapsed=71.1s

  [3373/15692] intraday_1216.csv.gz  in=226,284,799 out=35,760,155 elapsed=71.1s

  [3374/15692] intraday_12157.csv.gz  in=226,537,923 out=35,784,729 elapsed=71.1s

  [3375/15692] intraday_12158.csv.gz  in=226,807,839 out=35,813,799 elapsed=71.2s

  [3376/15692] intraday_12159.csv.gz  in=227,052,218 out=35,836,598 elapsed=71.3s

  [3377/15692] intraday_12161.csv.gz  in=227,290,102 out=35,859,012 elapsed=71.3s

  [3378/15692] intraday_12160.csv.gz  in=227,595,707 out=35,884,239 elapsed=71.4s

  [3379/15692] intraday_12162.csv.gz  in=227,847,719 out=35,907,254 elapsed=71.4s

  [3380/15692] intraday_12163.csv.gz  in=228,099,372 out=35,930,210 elapsed=71.5s

  [3381/15692] intraday_12164.csv.gz  in=228,320,836 out=35,950,612 elapsed=71.5s

  [3382/15692] intraday_12165.csv.gz  in=228,626,606 out=35,981,374 elapsed=71.6s

  [3383/15692] intraday_12166.csv.gz  in=228,930,578 out=36,009,556 elapsed=71.6s

  [3384/15692] intraday_1217.csv.gz  in=228,945,018 out=36,009,556 elapsed=71.7s

  [3385/15692] intraday_12167.csv.gz  in=229,217,505 out=36,034,742 elapsed=71.7s

  [3386/15692] intraday_12168.csv.gz  in=229,486,216 out=36,060,138 elapsed=71.7s

  [3387/15692] intraday_12169.csv.gz  in=229,750,975 out=36,084,337 elapsed=71.8s

  [3388/15692] intraday_12170.csv.gz  in=229,956,041 out=36,103,725 elapsed=71.8s

  [3389/15692] intraday_12171.csv.gz  in=230,228,579 out=36,129,537 elapsed=71.9s

  [3390/15692] intraday_12172.csv.gz  in=230,486,328 out=36,155,019 elapsed=71.9s

  [3391/15692] intraday_12173.csv.gz  in=230,760,392 out=36,182,251 elapsed=72.1s

  [3392/15692] intraday_12174.csv.gz  in=231,031,301 out=36,209,876 elapsed=72.1s

  [3393/15692] intraday_12175.csv.gz  in=231,276,048 out=36,232,610 elapsed=72.1s

  [3394/15692] intraday_12176.csv.gz  in=231,524,937 out=36,252,870 elapsed=72.1s

  [3395/15692] intraday_1218.csv.gz  in=231,547,219 out=36,252,870 elapsed=72.1s

  [3396/15692] intraday_12177.csv.gz  in=231,811,347 out=36,276,883 elapsed=72.3s

  [3397/15692] intraday_12178.csv.gz  in=232,081,654 out=36,301,636 elapsed=72.3s

  [3398/15692] intraday_12179.csv.gz  in=232,341,082 out=36,325,518 elapsed=72.3s

  [3399/15692] intraday_12180.csv.gz  in=232,613,557 out=36,349,484 elapsed=72.3s

  [3400/15692] intraday_12181.csv.gz  in=232,807,775 out=36,369,220 elapsed=72.5s

  [3401/15692] intraday_12182.csv.gz  in=233,053,758 out=36,390,399 elapsed=72.5s

  [3402/15692] intraday_12183.csv.gz  in=233,325,233 out=36,414,750 elapsed=72.6s

  [3403/15692] intraday_12184.csv.gz  in=233,701,035 out=36,450,099 elapsed=72.7s

  [3404/15692] intraday_12186.csv.gz  in=233,989,563 out=36,478,004 elapsed=72.8s

  [3405/15692] intraday_12185.csv.gz  in=234,317,159 out=36,512,747 elapsed=72.8s

  [3406/15692] intraday_12187.csv.gz  in=234,582,935 out=36,536,539 elapsed=72.8s

  [3407/15692] intraday_1219.csv.gz  in=234,596,994 out=36,536,539 elapsed=72.8s

  [3408/15692] intraday_12188.csv.gz  in=234,867,329 out=36,560,050 elapsed=72.9s

  [3409/15692] intraday_12189.csv.gz  in=235,149,352 out=36,583,936 elapsed=73.0s

  [3410/15692] intraday_12191.csv.gz  in=235,396,811 out=36,606,666 elapsed=73.0s

  [3411/15692] intraday_12190.csv.gz  in=235,746,650 out=36,637,075 elapsed=73.1s

  [3412/15692] intraday_12192.csv.gz  in=236,002,200 out=36,658,077 elapsed=73.1s

  [3413/15692] intraday_12193.csv.gz  in=236,303,666 out=36,685,429 elapsed=73.2s

  [3414/15692] intraday_12194.csv.gz  in=236,603,410 out=36,712,669 elapsed=73.3s

  [3415/15692] intraday_12196.csv.gz  in=236,858,978 out=36,736,422 elapsed=73.3s

  [3416/15692] intraday_12195.csv.gz  in=237,158,842 out=36,762,664 elapsed=73.3s

  [3417/15692] intraday_1220.csv.gz  in=237,179,804 out=36,762,664 elapsed=73.3s

  [3418/15692] intraday_12197.csv.gz  in=237,442,844 out=36,785,521 elapsed=73.4s

  [3419/15692] intraday_12198.csv.gz  in=237,713,074 out=36,810,277 elapsed=73.5s

  [3420/15692] intraday_12199.csv.gz  in=237,955,374 out=36,829,129 elapsed=73.5s

  [3421/15692] intraday_12200.csv.gz  in=238,290,213 out=36,858,073 elapsed=73.6s

  [3422/15692] intraday_12201.csv.gz  in=238,518,712 out=36,877,313 elapsed=73.6s

  [3423/15692] intraday_12202.csv.gz  in=238,805,947 out=36,902,945 elapsed=73.7s

  [3424/15692] intraday_12203.csv.gz  in=239,120,049 out=36,931,251 elapsed=73.7s

  [3425/15692] intraday_12205.csv.gz  in=239,351,960 out=36,957,798 elapsed=73.8s

  [3426/15692] intraday_12204.csv.gz  in=239,646,734 out=36,982,075 elapsed=73.8s

  [3427/15692] intraday_12206.csv.gz  in=239,920,235 out=37,006,714 elapsed=74.0s

  [3428/15692] intraday_1221.csv.gz  in=239,935,724 out=37,006,714 elapsed=74.0s

  [3429/15692] intraday_12208.csv.gz  in=240,202,481 out=37,029,882 elapsed=74.0s

  [3430/15692] intraday_12207.csv.gz  in=240,535,572 out=37,060,239 elapsed=74.0s

  [3431/15692] intraday_12209.csv.gz  in=240,788,048 out=37,082,173 elapsed=74.0s

  [3432/15692] intraday_12212.csv.gz  in=241,054,706 out=37,105,597 elapsed=74.3s

  [3433/15692] intraday_12211.csv.gz  in=241,372,964 out=37,135,266 elapsed=74.3s

  [3434/15692] intraday_12210.csv.gz  in=241,706,007 out=37,164,347 elapsed=74.3s

  [3435/15692] intraday_12213.csv.gz  in=241,982,222 out=37,190,090 elapsed=74.3s

  [3436/15692] intraday_12214.csv.gz  in=242,251,198 out=37,225,446 elapsed=74.5s

  [3437/15692] intraday_12215.csv.gz  in=242,491,876 out=37,249,370 elapsed=74.5s

  [3438/15692] intraday_12216.csv.gz  in=242,821,382 out=37,277,809 elapsed=74.6s

  [3439/15692] intraday_12217.csv.gz  in=243,161,414 out=37,308,957 elapsed=74.6s

  [3440/15692] intraday_1222.csv.gz  in=243,173,542 out=37,308,957 elapsed=74.6s

  [3441/15692] intraday_12219.csv.gz  in=243,471,228 out=37,337,575 elapsed=74.8s

  [3442/15692] intraday_12218.csv.gz  in=243,765,136 out=37,372,646 elapsed=74.8s

  [3443/15692] intraday_12221.csv.gz  in=243,995,494 out=37,397,927 elapsed=74.8s

  [3444/15692] intraday_12220.csv.gz  in=244,335,193 out=37,429,044 elapsed=74.9s

  [3445/15692] intraday_12223.csv.gz  in=244,565,889 out=37,453,031 elapsed=75.0s

  [3446/15692] intraday_12222.csv.gz  in=244,833,073 out=37,477,374 elapsed=75.0s

  [3447/15692] intraday_12224.csv.gz  in=245,139,181 out=37,504,986 elapsed=75.1s

  [3448/15692] intraday_12225.csv.gz  in=245,373,590 out=37,526,137 elapsed=75.1s

  [3449/15692] intraday_12227.csv.gz  in=245,650,958 out=37,552,528 elapsed=75.3s

  [3450/15692] intraday_12226.csv.gz  in=245,960,860 out=37,587,239 elapsed=75.3s

  [3451/15692] intraday_1223.csv.gz  in=245,974,321 out=37,587,239 elapsed=75.3s

  [3452/15692] intraday_12229.csv.gz  in=246,230,009 out=37,609,701 elapsed=75.3s

  [3453/15692] intraday_12228.csv.gz  in=246,568,706 out=37,639,246 elapsed=75.4s

  [3454/15692] intraday_12231.csv.gz  in=246,830,957 out=37,662,108 elapsed=75.5s

  [3455/15692] intraday_12230.csv.gz  in=247,093,409 out=37,683,608 elapsed=75.5s

  [3456/15692] intraday_12232.csv.gz  in=247,412,682 out=37,709,493 elapsed=75.6s

  [3457/15692] intraday_12233.csv.gz  in=247,648,535 out=37,730,780 elapsed=75.6s

  [3458/15692] intraday_12234.csv.gz  in=247,921,041 out=37,757,496 elapsed=75.7s

  [3459/15692] intraday_12235.csv.gz  in=248,242,467 out=37,790,126 elapsed=75.8s

  [3460/15692] intraday_12236.csv.gz  in=248,535,824 out=37,816,356 elapsed=75.8s

  [3461/15692] intraday_1224.csv.gz  in=248,547,752 out=37,816,356 elapsed=75.8s

  [3462/15692] intraday_12237.csv.gz  in=248,870,513 out=37,847,509 elapsed=75.8s

  [3463/15692] intraday_12238.csv.gz  in=249,126,005 out=37,871,599 elapsed=75.9s

  [3464/15692] intraday_12239.csv.gz  in=249,374,765 out=37,895,230 elapsed=75.9s

  [3465/15692] intraday_12241.csv.gz  in=249,625,485 out=37,918,402 elapsed=76.0s

  [3466/15692] intraday_12240.csv.gz  in=249,903,085 out=37,941,791 elapsed=76.0s

  [3467/15692] intraday_12243.csv.gz  in=250,111,178 out=37,956,555 elapsed=76.1s

  [3468/15692] intraday_12242.csv.gz  in=250,406,449 out=37,980,824 elapsed=76.1s

  [3469/15692] intraday_12246.csv.gz  in=250,410,235 out=37,981,128 elapsed=76.1s

  [3470/15692] intraday_12244.csv.gz  in=250,606,302 out=38,000,086 elapsed=76.2s

  [3471/15692] intraday_12247.csv.gz  in=250,608,717 out=38,000,604 elapsed=76.2s

  [3472/15692] intraday_12248.csv.gz  in=250,609,952 out=38,000,746 elapsed=76.2s

  [3473/15692] intraday_12249.csv.gz  in=250,614,661 out=38,002,190 elapsed=76.2s

  [3474/15692] intraday_1225.csv.gz  in=250,627,502 out=38,002,190 elapsed=76.2s

  [3475/15692] intraday_12250.csv.gz  in=250,635,593 out=38,006,776 elapsed=76.2s

  [3476/15692] intraday_12251.csv.gz  in=250,636,112 out=38,006,842 elapsed=76.2s

  [3477/15692] intraday_12252.csv.gz  in=250,637,107 out=38,007,618 elapsed=76.2s

  [3478/15692] intraday_12255.csv.gz  in=250,637,324 out=38,007,649 elapsed=76.3s

  [3479/15692] intraday_12254.csv.gz  in=250,640,384 out=38,008,775 elapsed=76.3s

  [3480/15692] intraday_12253.csv.gz  in=250,653,186 out=38,015,732 elapsed=76.3s

  [3481/15692] intraday_12245.csv.gz  in=250,927,297 out=38,042,711 elapsed=76.3s

  [3482/15692] intraday_12257.csv.gz  in=250,928,187 out=38,042,810 elapsed=76.3s

  [3483/15692] intraday_12256.csv.gz  in=250,929,837 out=38,043,331 elapsed=76.3s

  [3484/15692] intraday_12258.csv.gz  in=250,932,259 out=38,043,559 elapsed=76.3s

  [3485/15692] intraday_12260.csv.gz  in=250,932,524 out=38,043,691 elapsed=76.3s

  [3486/15692] intraday_12259.csv.gz  in=250,932,639 out=38,043,693 elapsed=76.3s

  [3487/15692] intraday_12261.csv.gz  in=250,933,479 out=38,043,772 elapsed=76.3s

  [3488/15692] intraday_12262.csv.gz  in=250,934,697 out=38,044,007 elapsed=76.3s

  [3489/15692] intraday_1226.csv.gz  in=250,945,325 out=38,044,007 elapsed=76.3s

  [3490/15692] intraday_12263.csv.gz  in=250,951,712 out=38,046,844 elapsed=76.4s

  [3491/15692] intraday_12265.csv.gz  in=250,953,560 out=38,048,006 elapsed=76.4s

  [3492/15692] intraday_12264.csv.gz  in=250,953,650 out=38,048,019 elapsed=76.4s

  [3493/15692] intraday_12267.csv.gz  in=250,954,118 out=38,048,019 elapsed=76.4s

  [3494/15692] intraday_12266.csv.gz  in=250,957,297 out=38,048,383 elapsed=76.4s

  [3495/15692] intraday_12268.csv.gz  in=250,960,177 out=38,048,667 elapsed=76.4s

  [3496/15692] intraday_12269.csv.gz  in=250,963,823 out=38,050,038 elapsed=76.4s

  [3497/15692] intraday_12270.csv.gz  in=250,965,549 out=38,050,272 elapsed=76.4s

  [3498/15692] intraday_1227.csv.gz  in=250,979,780 out=38,050,272 elapsed=76.4s

  [3499/15692] intraday_12271.csv.gz  in=250,986,611 out=38,054,780 elapsed=76.4s

  [3500/15692] intraday_12275.csv.gz  in=250,987,098 out=38,054,838 elapsed=76.4s

  [3501/15692] intraday_12274.csv.gz  in=250,987,657 out=38,054,978 elapsed=76.5s

  [3502/15692] intraday_12273.csv.gz  in=250,992,516 out=38,054,978 elapsed=76.5s

  [3503/15692] intraday_12272.csv.gz  in=250,994,745 out=38,056,182 elapsed=76.5s

  [3504/15692] intraday_12277.csv.gz  in=251,007,885 out=38,069,322 elapsed=76.5s

  [3505/15692] intraday_12279.csv.gz  in=251,018,237 out=38,079,674 elapsed=76.5s

  [3506/15692] intraday_12276.csv.gz  in=251,034,671 out=38,096,108 elapsed=76.5s

  [3507/15692] intraday_12278.csv.gz  in=251,047,083 out=38,108,520 elapsed=76.5s

  [3508/15692] intraday_1228.csv.gz  in=251,055,347 out=38,108,520 elapsed=76.5s

  [3509/15692] intraday_12281.csv.gz  in=251,070,538 out=38,123,711 elapsed=76.6s

  [3510/15692] intraday_12280.csv.gz  in=251,082,854 out=38,136,027 elapsed=76.6s

  [3511/15692] intraday_12283.csv.gz  in=251,095,725 out=38,148,898 elapsed=76.6s

  [3512/15692] intraday_12282.csv.gz  in=251,109,950 out=38,163,123 elapsed=76.6s

  [3513/15692] intraday_12284.csv.gz  in=251,122,989 out=38,176,162 elapsed=76.6s

  [3514/15692] intraday_12285.csv.gz  in=251,135,959 out=38,189,132 elapsed=76.6s

  [3515/15692] intraday_12286.csv.gz  in=251,148,219 out=38,201,392 elapsed=76.6s

  [3516/15692] intraday_12287.csv.gz  in=251,160,056 out=38,213,229 elapsed=76.6s

  [3517/15692] intraday_12288.csv.gz  in=251,174,256 out=38,227,429 elapsed=76.6s

  [3518/15692] intraday_12289.csv.gz  in=251,188,333 out=38,241,506 elapsed=76.6s

  [3519/15692] intraday_1229.csv.gz  in=251,199,030 out=38,241,506 elapsed=76.6s

  [3520/15692] intraday_12290.csv.gz  in=251,209,547 out=38,252,023 elapsed=76.7s

  [3521/15692] intraday_12291.csv.gz  in=251,219,712 out=38,262,188 elapsed=76.7s

  [3522/15692] intraday_12293.csv.gz  in=251,232,295 out=38,274,771 elapsed=76.7s

  [3523/15692] intraday_12292.csv.gz  in=251,246,628 out=38,289,104 elapsed=76.7s

  [3524/15692] intraday_12294.csv.gz  in=251,258,187 out=38,300,663 elapsed=76.7s

  [3525/15692] intraday_12295.csv.gz  in=251,269,475 out=38,311,951 elapsed=76.7s

  [3526/15692] intraday_12296.csv.gz  in=251,280,333 out=38,322,809 elapsed=76.7s

  [3527/15692] intraday_12297.csv.gz  in=251,292,955 out=38,335,431 elapsed=76.8s

  [3528/15692] intraday_12298.csv.gz  in=251,306,372 out=38,348,848 elapsed=76.8s

  [3529/15692] intraday_12299.csv.gz  in=251,317,441 out=38,359,917 elapsed=76.8s

  [3530/15692] intraday_1230.csv.gz  in=251,329,037 out=38,359,917 elapsed=76.8s

  [3531/15692] intraday_12300.csv.gz  in=251,341,564 out=38,372,444 elapsed=76.8s

  [3532/15692] intraday_12301.csv.gz  in=251,352,971 out=38,383,851 elapsed=76.8s

  [3533/15692] intraday_12303.csv.gz  in=251,364,600 out=38,395,480 elapsed=76.9s

  [3534/15692] intraday_12302.csv.gz  in=251,377,237 out=38,408,117 elapsed=76.9s

  [3535/15692] intraday_12304.csv.gz  in=251,389,006 out=38,419,886 elapsed=76.9s

  [3536/15692] intraday_12305.csv.gz  in=251,402,168 out=38,433,048 elapsed=76.9s

  [3537/15692] intraday_12307.csv.gz  in=251,415,600 out=38,446,480 elapsed=76.9s

  [3538/15692] intraday_12308.csv.gz  in=251,425,816 out=38,456,696 elapsed=76.9s

  [3539/15692] intraday_12306.csv.gz  in=251,440,822 out=38,471,702 elapsed=76.9s

  [3540/15692] intraday_1231.csv.gz  in=251,456,101 out=38,471,702 elapsed=76.9s

  [3541/15692] intraday_12309.csv.gz  in=251,470,226 out=38,485,827 elapsed=76.9s

  [3542/15692] intraday_12310.csv.gz  in=251,483,522 out=38,499,123 elapsed=76.9s

  [3543/15692] intraday_12311.csv.gz  in=251,497,114 out=38,512,715 elapsed=77.0s

  [3544/15692] intraday_12313.csv.gz  in=251,507,150 out=38,522,751 elapsed=77.0s

  [3545/15692] intraday_12312.csv.gz  in=251,519,558 out=38,535,159 elapsed=77.0s

  [3546/15692] intraday_12316.csv.gz  in=251,530,114 out=38,545,715 elapsed=77.0s

  [3547/15692] intraday_12315.csv.gz  in=251,539,662 out=38,555,263 elapsed=77.0s

  [3548/15692] intraday_12317.csv.gz  in=251,552,993 out=38,568,594 elapsed=77.0s

  [3549/15692] intraday_12314.csv.gz  in=251,565,546 out=38,581,147 elapsed=77.0s

  [3550/15692] intraday_12319.csv.gz  in=251,577,529 out=38,593,130 elapsed=77.1s

  [3551/15692] intraday_1232.csv.gz  in=251,592,042 out=38,593,130 elapsed=77.1s

  [3552/15692] intraday_12318.csv.gz  in=251,604,339 out=38,605,427 elapsed=77.1s

  [3553/15692] intraday_12320.csv.gz  in=251,617,915 out=38,619,003 elapsed=77.1s

  [3554/15692] intraday_12322.csv.gz  in=251,630,228 out=38,631,316 elapsed=77.1s

  [3555/15692] intraday_12321.csv.gz  in=251,643,005 out=38,644,093 elapsed=77.1s

  [3556/15692] intraday_12323.csv.gz  in=251,655,392 out=38,656,480 elapsed=77.1s

  [3557/15692] intraday_12324.csv.gz  in=251,670,015 out=38,671,103 elapsed=77.1s

  [3558/15692] intraday_12325.csv.gz  in=251,680,153 out=38,681,241 elapsed=77.1s

  [3559/15692] intraday_12327.csv.gz  in=251,689,217 out=38,690,305 elapsed=77.1s

  [3560/15692] intraday_12326.csv.gz  in=251,701,098 out=38,702,186 elapsed=77.2s

  [3561/15692] intraday_12329.csv.gz  in=251,711,453 out=38,712,541 elapsed=77.2s

  [3562/15692] intraday_12328.csv.gz  in=251,725,211 out=38,726,299 elapsed=77.2s

  [3563/15692] intraday_1233.csv.gz  in=251,736,412 out=38,726,299 elapsed=77.2s

  [3564/15692] intraday_12331.csv.gz  in=251,750,760 out=38,740,647 elapsed=77.2s

  [3565/15692] intraday_12330.csv.gz  in=251,763,356 out=38,753,243 elapsed=77.2s

  [3566/15692] intraday_12332.csv.gz  in=251,775,622 out=38,765,509 elapsed=77.2s

  [3567/15692] intraday_12333.csv.gz  in=251,786,940 out=38,776,827 elapsed=77.2s

  [3568/15692] intraday_12335.csv.gz  in=251,799,038 out=38,788,925 elapsed=77.3s

  [3569/15692] intraday_12334.csv.gz  in=251,809,789 out=38,799,676 elapsed=77.3s

  [3570/15692] intraday_12336.csv.gz  in=251,821,673 out=38,811,560 elapsed=77.3s

  [3571/15692] intraday_12337.csv.gz  in=251,834,168 out=38,824,055 elapsed=77.3s

  [3572/15692] intraday_1234.csv.gz  in=251,845,466 out=38,824,055 elapsed=77.3s

  [3573/15692] intraday_12339.csv.gz  in=251,857,930 out=38,836,519 elapsed=77.3s

  [3574/15692] intraday_12338.csv.gz  in=251,869,147 out=38,847,736 elapsed=77.3s

  [3575/15692] intraday_12340.csv.gz  in=251,878,482 out=38,857,071 elapsed=77.3s

  [3576/15692] intraday_12342.csv.gz  in=251,893,907 out=38,872,496 elapsed=77.3s

  [3577/15692] intraday_12343.csv.gz  in=251,905,969 out=38,884,558 elapsed=77.4s

  [3578/15692] intraday_12344.csv.gz  in=251,919,782 out=38,898,371 elapsed=77.4s

  [3579/15692] intraday_12341.csv.gz  in=251,934,528 out=38,913,117 elapsed=77.4s

  [3580/15692] intraday_12345.csv.gz  in=251,947,001 out=38,925,590 elapsed=77.4s

  [3581/15692] intraday_12346.csv.gz  in=251,957,117 out=38,935,706 elapsed=77.4s

  [3582/15692] intraday_12347.csv.gz  in=251,970,569 out=38,949,158 elapsed=77.4s

  [3583/15692] intraday_12349.csv.gz  in=251,983,336 out=38,961,925 elapsed=77.4s

  [3584/15692] intraday_12348.csv.gz  in=251,996,245 out=38,974,834 elapsed=77.4s

  [3585/15692] intraday_1235.csv.gz  in=252,010,748 out=38,974,834 elapsed=77.4s

  [3586/15692] intraday_12350.csv.gz  in=252,024,413 out=38,988,499 elapsed=77.5s

  [3587/15692] intraday_12351.csv.gz  in=252,036,277 out=39,000,363 elapsed=77.5s

  [3588/15692] intraday_12352.csv.gz  in=252,047,502 out=39,011,588 elapsed=77.5s

  [3589/15692] intraday_12354.csv.gz  in=252,061,120 out=39,025,206 elapsed=77.5s

  [3590/15692] intraday_12353.csv.gz  in=252,072,432 out=39,036,518 elapsed=77.5s

  [3591/15692] intraday_12355.csv.gz  in=252,084,647 out=39,048,733 elapsed=77.5s

  [3592/15692] intraday_12356.csv.gz  in=252,096,393 out=39,060,479 elapsed=77.5s

  [3593/15692] intraday_12358.csv.gz  in=252,107,660 out=39,071,746 elapsed=77.5s

  [3594/15692] intraday_12357.csv.gz  in=252,119,214 out=39,083,300 elapsed=77.6s

  [3595/15692] intraday_12359.csv.gz  in=252,131,448 out=39,095,534 elapsed=77.6s

  [3596/15692] intraday_1236.csv.gz  in=252,145,501 out=39,095,534 elapsed=77.6s

  [3597/15692] intraday_12360.csv.gz  in=252,161,250 out=39,111,283 elapsed=77.6s

  [3598/15692] intraday_12361.csv.gz  in=252,178,639 out=39,128,672 elapsed=77.6s

  [3599/15692] intraday_12362.csv.gz  in=252,191,950 out=39,141,983 elapsed=77.6s

  [3600/15692] intraday_12364.csv.gz  in=252,203,461 out=39,153,494 elapsed=77.6s

  [3601/15692] intraday_12365.csv.gz  in=252,215,861 out=39,165,894 elapsed=77.7s

  [3602/15692] intraday_12363.csv.gz  in=252,227,796 out=39,177,829 elapsed=77.7s

  [3603/15692] intraday_12367.csv.gz  in=252,238,552 out=39,188,585 elapsed=77.7s

  [3604/15692] intraday_12366.csv.gz  in=252,253,320 out=39,203,353 elapsed=77.7s

  [3605/15692] intraday_12368.csv.gz  in=252,264,312 out=39,214,345 elapsed=77.7s

  [3606/15692] intraday_12369.csv.gz  in=252,279,801 out=39,229,834 elapsed=77.7s

  [3607/15692] intraday_1237.csv.gz  in=252,292,116 out=39,229,834 elapsed=77.7s

  [3608/15692] intraday_12370.csv.gz  in=252,304,549 out=39,242,267 elapsed=77.7s

  [3609/15692] intraday_12371.csv.gz  in=252,317,065 out=39,254,783 elapsed=77.7s

  [3610/15692] intraday_12372.csv.gz  in=252,329,964 out=39,267,682 elapsed=77.8s

  [3611/15692] intraday_12374.csv.gz  in=252,342,853 out=39,280,571 elapsed=77.8s

  [3612/15692] intraday_12373.csv.gz  in=252,353,981 out=39,291,699 elapsed=77.8s

  [3613/15692] intraday_12375.csv.gz  in=252,367,447 out=39,305,165 elapsed=77.8s

  [3614/15692] intraday_12377.csv.gz  in=252,378,357 out=39,316,075 elapsed=77.8s

  [3615/15692] intraday_12376.csv.gz  in=252,390,012 out=39,327,730 elapsed=77.8s

  [3616/15692] intraday_12378.csv.gz  in=252,403,584 out=39,341,302 elapsed=77.9s

  [3617/15692] intraday_1238.csv.gz  in=252,415,684 out=39,341,302 elapsed=77.9s

  [3618/15692] intraday_12379.csv.gz  in=252,429,448 out=39,355,066 elapsed=77.9s

  [3619/15692] intraday_12380.csv.gz  in=252,444,168 out=39,369,042 elapsed=77.9s

  [3620/15692] intraday_12382.csv.gz  in=252,457,186 out=39,382,060 elapsed=77.9s

  [3621/15692] intraday_12383.csv.gz  in=252,472,535 out=39,397,409 elapsed=77.9s

  [3622/15692] intraday_12381.csv.gz  in=252,485,214 out=39,410,088 elapsed=77.9s

  [3623/15692] intraday_12385.csv.gz  in=252,497,664 out=39,422,538 elapsed=77.9s

  [3624/15692] intraday_12384.csv.gz  in=252,508,683 out=39,433,557 elapsed=77.9s

  [3625/15692] intraday_12386.csv.gz  in=252,522,842 out=39,447,716 elapsed=78.0s

  [3626/15692] intraday_12388.csv.gz  in=252,534,627 out=39,459,501 elapsed=78.0s

  [3627/15692] intraday_12387.csv.gz  in=252,549,718 out=39,474,592 elapsed=78.0s

  [3628/15692] intraday_12389.csv.gz  in=252,563,015 out=39,487,889 elapsed=78.0s

  [3629/15692] intraday_1239.csv.gz  in=252,577,723 out=39,487,889 elapsed=78.0s

  [3630/15692] intraday_12390.csv.gz  in=252,593,162 out=39,503,328 elapsed=78.1s

  [3631/15692] intraday_12392.csv.gz  in=252,607,170 out=39,517,336 elapsed=78.1s

  [3632/15692] intraday_12393.csv.gz  in=252,623,500 out=39,533,666 elapsed=78.1s

  [3633/15692] intraday_12391.csv.gz  in=252,636,731 out=39,546,897 elapsed=78.1s

  [3634/15692] intraday_12394.csv.gz  in=252,655,323 out=39,565,489 elapsed=78.1s

  [3635/15692] intraday_12395.csv.gz  in=252,668,907 out=39,579,073 elapsed=78.1s

  [3636/15692] intraday_12396.csv.gz  in=252,685,433 out=39,595,599 elapsed=78.1s

  [3637/15692] intraday_12397.csv.gz  in=252,719,953 out=39,621,690 elapsed=78.1s

  [3638/15692] intraday_12398.csv.gz  in=252,732,273 out=39,634,010 elapsed=78.2s

  [3639/15692] intraday_1240.csv.gz  in=252,746,331 out=39,634,010 elapsed=78.2s

  [3640/15692] intraday_12401.csv.gz  in=252,757,209 out=39,644,888 elapsed=78.2s

  [3641/15692] intraday_12399.csv.gz  in=252,769,801 out=39,657,480 elapsed=78.2s

  [3642/15692] intraday_12400.csv.gz  in=252,782,233 out=39,669,912 elapsed=78.2s

  [3643/15692] intraday_12402.csv.gz  in=252,795,345 out=39,683,024 elapsed=78.2s

  [3644/15692] intraday_12403.csv.gz  in=252,807,016 out=39,694,695 elapsed=78.2s

  [3645/15692] intraday_12405.csv.gz  in=252,817,577 out=39,705,256 elapsed=78.3s

  [3646/15692] intraday_12406.csv.gz  in=252,828,838 out=39,716,517 elapsed=78.3s

  [3647/15692] intraday_12404.csv.gz  in=252,844,692 out=39,732,371 elapsed=78.3s

  [3648/15692] intraday_12407.csv.gz  in=252,856,395 out=39,744,074 elapsed=78.3s

  [3649/15692] intraday_12408.csv.gz  in=252,870,711 out=39,758,390 elapsed=78.3s

  [3650/15692] intraday_1241.csv.gz  in=252,880,482 out=39,758,390 elapsed=78.3s

  [3651/15692] intraday_12409.csv.gz  in=252,891,080 out=39,768,988 elapsed=78.3s

  [3652/15692] intraday_12410.csv.gz  in=252,904,800 out=39,782,708 elapsed=78.3s

  [3653/15692] intraday_12411.csv.gz  in=252,919,435 out=39,797,343 elapsed=78.4s

  [3654/15692] intraday_12413.csv.gz  in=252,933,385 out=39,811,293 elapsed=78.4s

  [3655/15692] intraday_12412.csv.gz  in=252,947,687 out=39,825,595 elapsed=78.4s

  [3656/15692] intraday_12414.csv.gz  in=252,961,932 out=39,839,840 elapsed=78.4s

  [3657/15692] intraday_12415.csv.gz  in=252,973,648 out=39,851,556 elapsed=78.4s

  [3658/15692] intraday_12416.csv.gz  in=252,986,268 out=39,864,176 elapsed=78.4s

  [3659/15692] intraday_12417.csv.gz  in=252,996,602 out=39,874,510 elapsed=78.4s

  [3660/15692] intraday_12418.csv.gz  in=253,009,698 out=39,887,606 elapsed=78.4s

  [3661/15692] intraday_12419.csv.gz  in=253,017,733 out=39,895,641 elapsed=78.5s

  [3662/15692] intraday_12420.csv.gz  in=253,025,345 out=39,903,253 elapsed=78.5s

  [3663/15692] intraday_1242.csv.gz  in=253,040,331 out=39,903,253 elapsed=78.5s

  [3664/15692] intraday_12421.csv.gz  in=253,053,892 out=39,916,814 elapsed=78.5s

  [3665/15692] intraday_12422.csv.gz  in=253,057,505 out=39,920,427 elapsed=78.5s

  [3666/15692] intraday_12423.csv.gz  in=253,075,590 out=39,938,512 elapsed=78.5s

  [3667/15692] intraday_12424.csv.gz  in=253,088,474 out=39,951,396 elapsed=78.5s

  [3668/15692] intraday_12426.csv.gz  in=253,100,716 out=39,962,869 elapsed=78.6s

  [3669/15692] intraday_12425.csv.gz  in=253,115,109 out=39,977,262 elapsed=78.6s

  [3670/15692] intraday_12428.csv.gz  in=253,129,964 out=39,992,117 elapsed=78.6s

  [3671/15692] intraday_12427.csv.gz  in=253,142,244 out=40,004,397 elapsed=78.6s

  [3672/15692] intraday_12429.csv.gz  in=253,161,412 out=40,023,565 elapsed=78.6s

  [3673/15692] intraday_1243.csv.gz  in=253,176,682 out=40,023,565 elapsed=78.6s

  [3674/15692] intraday_12431.csv.gz  in=253,190,623 out=40,037,506 elapsed=78.6s

  [3675/15692] intraday_12430.csv.gz  in=253,202,184 out=40,049,067 elapsed=78.6s

  [3676/15692] intraday_12432.csv.gz  in=253,216,449 out=40,063,332 elapsed=78.6s

  [3677/15692] intraday_12433.csv.gz  in=253,229,838 out=40,076,721 elapsed=78.7s

  [3678/15692] intraday_12434.csv.gz  in=253,242,928 out=40,089,811 elapsed=78.7s

  [3679/15692] intraday_12435.csv.gz  in=253,257,019 out=40,103,902 elapsed=78.7s

  [3680/15692] intraday_12436.csv.gz  in=253,271,194 out=40,118,077 elapsed=78.7s

  [3681/15692] intraday_12437.csv.gz  in=253,293,466 out=40,135,610 elapsed=78.7s

  [3682/15692] intraday_12438.csv.gz  in=253,306,341 out=40,147,515 elapsed=78.7s

  [3683/15692] intraday_12439.csv.gz  in=253,321,097 out=40,162,115 elapsed=78.7s

  [3684/15692] intraday_1244.csv.gz  in=253,332,154 out=40,162,115 elapsed=78.7s

  [3685/15692] intraday_12441.csv.gz  in=253,342,978 out=40,172,939 elapsed=78.8s

  [3686/15692] intraday_12440.csv.gz  in=253,356,574 out=40,186,535 elapsed=78.8s

  [3687/15692] intraday_12442.csv.gz  in=253,367,214 out=40,197,175 elapsed=78.8s

  [3688/15692] intraday_12443.csv.gz  in=253,378,660 out=40,208,621 elapsed=78.8s

  [3689/15692] intraday_12444.csv.gz  in=253,391,464 out=40,221,425 elapsed=78.8s

  [3690/15692] intraday_12445.csv.gz  in=253,404,027 out=40,233,988 elapsed=78.8s

  [3691/15692] intraday_12446.csv.gz  in=253,416,350 out=40,246,311 elapsed=78.8s

  [3692/15692] intraday_12447.csv.gz  in=253,429,188 out=40,259,149 elapsed=78.9s

  [3693/15692] intraday_12448.csv.gz  in=253,441,019 out=40,270,980 elapsed=78.9s

  [3694/15692] intraday_12449.csv.gz  in=253,454,534 out=40,284,495 elapsed=78.9s

  [3695/15692] intraday_1245.csv.gz  in=253,465,215 out=40,284,495 elapsed=78.9s

  [3696/15692] intraday_12450.csv.gz  in=253,477,210 out=40,296,490 elapsed=78.9s

  [3697/15692] intraday_12451.csv.gz  in=253,489,121 out=40,308,401 elapsed=78.9s

  [3698/15692] intraday_12454.csv.gz  in=253,503,267 out=40,322,547 elapsed=79.0s

  [3699/15692] intraday_12453.csv.gz  in=253,519,385 out=40,338,665 elapsed=79.0s

  [3700/15692] intraday_12452.csv.gz  in=253,532,816 out=40,352,096 elapsed=79.0s

  [3701/15692] intraday_12455.csv.gz  in=253,543,320 out=40,362,600 elapsed=79.0s

  [3702/15692] intraday_12458.csv.gz  in=253,557,607 out=40,376,887 elapsed=79.0s

  [3703/15692] intraday_12456.csv.gz  in=253,572,479 out=40,391,759 elapsed=79.0s

  [3704/15692] intraday_12457.csv.gz  in=253,588,525 out=40,407,302 elapsed=79.0s

  [3705/15692] intraday_12459.csv.gz  in=253,600,465 out=40,419,242 elapsed=79.0s

  [3706/15692] intraday_1246.csv.gz  in=253,611,996 out=40,419,242 elapsed=79.1s

  [3707/15692] intraday_12461.csv.gz  in=253,624,406 out=40,431,652 elapsed=79.1s

  [3708/15692] intraday_12460.csv.gz  in=253,635,942 out=40,443,188 elapsed=79.1s

  [3709/15692] intraday_12462.csv.gz  in=253,647,032 out=40,454,278 elapsed=79.1s

  [3710/15692] intraday_12463.csv.gz  in=253,658,414 out=40,465,660 elapsed=79.1s

  [3711/15692] intraday_12464.csv.gz  in=253,673,500 out=40,480,746 elapsed=79.1s

  [3712/15692] intraday_12465.csv.gz  in=253,685,521 out=40,492,767 elapsed=79.1s

  [3713/15692] intraday_12466.csv.gz  in=253,698,613 out=40,505,859 elapsed=79.2s

  [3714/15692] intraday_12467.csv.gz  in=253,714,007 out=40,521,253 elapsed=79.2s

  [3715/15692] intraday_12468.csv.gz  in=253,726,174 out=40,533,420 elapsed=79.2s

  [3716/15692] intraday_1247.csv.gz  in=253,739,158 out=40,533,420 elapsed=79.2s

  [3717/15692] intraday_12469.csv.gz  in=253,751,964 out=40,546,226 elapsed=79.2s

  [3718/15692] intraday_12470.csv.gz  in=253,763,493 out=40,557,755 elapsed=79.2s

  [3719/15692] intraday_12472.csv.gz  in=253,779,075 out=40,569,832 elapsed=79.2s

  [3720/15692] intraday_12471.csv.gz  in=253,792,727 out=40,583,484 elapsed=79.2s

  [3721/15692] intraday_12473.csv.gz  in=253,805,477 out=40,596,234 elapsed=79.2s

  [3722/15692] intraday_12474.csv.gz  in=253,816,043 out=40,606,800 elapsed=79.3s

  [3723/15692] intraday_12476.csv.gz  in=253,828,489 out=40,619,246 elapsed=79.3s

  [3724/15692] intraday_12475.csv.gz  in=253,841,338 out=40,632,095 elapsed=79.3s

  [3725/15692] intraday_12478.csv.gz  in=253,856,099 out=40,646,856 elapsed=79.3s

  [3726/15692] intraday_12477.csv.gz  in=253,868,645 out=40,659,402 elapsed=79.3s

  [3727/15692] intraday_12479.csv.gz  in=253,879,230 out=40,669,987 elapsed=79.3s

  [3728/15692] intraday_1248.csv.gz  in=253,892,285 out=40,669,987 elapsed=79.3s

  [3729/15692] intraday_12481.csv.gz  in=253,903,357 out=40,681,059 elapsed=79.4s

  [3730/15692] intraday_12480.csv.gz  in=253,914,944 out=40,692,646 elapsed=79.4s

  [3731/15692] intraday_12483.csv.gz  in=253,927,159 out=40,704,861 elapsed=79.4s

  [3732/15692] intraday_12482.csv.gz  in=253,940,086 out=40,717,788 elapsed=79.4s

  [3733/15692] intraday_12484.csv.gz  in=253,952,252 out=40,729,954 elapsed=79.4s

  [3734/15692] intraday_12485.csv.gz  in=253,965,378 out=40,743,080 elapsed=79.4s

  [3735/15692] intraday_12487.csv.gz  in=253,975,991 out=40,753,693 elapsed=79.4s

  [3736/15692] intraday_12486.csv.gz  in=253,988,094 out=40,765,796 elapsed=79.4s

  [3737/15692] intraday_12488.csv.gz  in=254,001,546 out=40,779,248 elapsed=79.5s

  [3738/15692] intraday_12489.csv.gz  in=254,017,325 out=40,795,027 elapsed=79.5s

  [3739/15692] intraday_1249.csv.gz  in=254,028,934 out=40,795,027 elapsed=79.5s

  [3740/15692] intraday_12490.csv.gz  in=254,042,792 out=40,808,885 elapsed=79.5s

  [3741/15692] intraday_12491.csv.gz  in=254,057,384 out=40,823,477 elapsed=79.5s

  [3742/15692] intraday_12493.csv.gz  in=254,068,808 out=40,834,901 elapsed=79.5s

  [3743/15692] intraday_12492.csv.gz  in=254,081,653 out=40,847,746 elapsed=79.5s

  [3744/15692] intraday_12494.csv.gz  in=254,093,749 out=40,859,842 elapsed=79.5s

  [3745/15692] intraday_12495.csv.gz  in=254,107,763 out=40,873,856 elapsed=79.5s

  [3746/15692] intraday_12497.csv.gz  in=254,121,727 out=40,887,820 elapsed=79.6s

  [3747/15692] intraday_12496.csv.gz  in=254,134,660 out=40,900,753 elapsed=79.6s

  [3748/15692] intraday_12498.csv.gz  in=254,146,294 out=40,912,387 elapsed=79.6s

  [3749/15692] intraday_12499.csv.gz  in=254,159,308 out=40,925,401 elapsed=79.6s

  [3750/15692] intraday_1250.csv.gz  in=254,170,117 out=40,925,401 elapsed=79.6s

  [3751/15692] intraday_12502.csv.gz  in=254,181,872 out=40,937,156 elapsed=79.7s

  [3752/15692] intraday_12500.csv.gz  in=254,193,391 out=40,948,675 elapsed=79.7s

  [3753/15692] intraday_12501.csv.gz  in=254,208,103 out=40,963,387 elapsed=79.7s

  [3754/15692] intraday_12503.csv.gz  in=254,220,813 out=40,976,097 elapsed=79.7s

  [3755/15692] intraday_12504.csv.gz  in=254,232,313 out=40,987,597 elapsed=79.7s

  [3756/15692] intraday_12506.csv.gz  in=254,245,174 out=41,000,458 elapsed=79.7s

  [3757/15692] intraday_12505.csv.gz  in=254,256,149 out=41,011,433 elapsed=79.7s

  [3758/15692] intraday_12507.csv.gz  in=254,271,220 out=41,026,504 elapsed=79.8s

  [3759/15692] intraday_12508.csv.gz  in=254,289,210 out=41,044,494 elapsed=79.8s

  [3760/15692] intraday_12509.csv.gz  in=254,303,451 out=41,058,735 elapsed=79.8s

  [3761/15692] intraday_1251.csv.gz  in=254,316,285 out=41,058,735 elapsed=79.8s

  [3762/15692] intraday_12510.csv.gz  in=254,327,365 out=41,069,815 elapsed=79.8s

  [3763/15692] intraday_12511.csv.gz  in=254,339,528 out=41,081,978 elapsed=79.8s

  [3764/15692] intraday_12512.csv.gz  in=254,352,826 out=41,095,276 elapsed=79.8s

  [3765/15692] intraday_12513.csv.gz  in=254,364,821 out=41,107,271 elapsed=79.8s

  [3766/15692] intraday_12514.csv.gz  in=254,380,097 out=41,122,547 elapsed=79.8s

  [3767/15692] intraday_12515.csv.gz  in=254,391,670 out=41,134,120 elapsed=79.9s

  [3768/15692] intraday_12516.csv.gz  in=254,407,426 out=41,149,876 elapsed=79.9s

  [3769/15692] intraday_12517.csv.gz  in=254,421,788 out=41,164,238 elapsed=79.9s

  [3770/15692] intraday_12518.csv.gz  in=254,433,102 out=41,175,552 elapsed=79.9s

  [3771/15692] intraday_12519.csv.gz  in=254,446,421 out=41,188,871 elapsed=79.9s

  [3772/15692] intraday_1252.csv.gz  in=254,458,389 out=41,188,871 elapsed=79.9s

  [3773/15692] intraday_12520.csv.gz  in=254,469,947 out=41,200,429 elapsed=79.9s

  [3774/15692] intraday_12522.csv.gz  in=254,481,197 out=41,211,679 elapsed=79.9s

  [3775/15692] intraday_12521.csv.gz  in=254,495,181 out=41,225,663 elapsed=79.9s

  [3776/15692] intraday_12523.csv.gz  in=254,509,973 out=41,240,455 elapsed=80.0s

  [3777/15692] intraday_12524.csv.gz  in=254,522,162 out=41,252,644 elapsed=80.0s

  [3778/15692] intraday_12526.csv.gz  in=254,535,455 out=41,265,937 elapsed=80.0s

  [3779/15692] intraday_12525.csv.gz  in=254,548,212 out=41,278,694 elapsed=80.0s

  [3780/15692] intraday_12527.csv.gz  in=254,563,066 out=41,293,548 elapsed=80.0s

  [3781/15692] intraday_12528.csv.gz  in=254,577,617 out=41,308,099 elapsed=80.0s

  [3782/15692] intraday_1253.csv.gz  in=254,590,398 out=41,308,099 elapsed=80.0s

  [3783/15692] intraday_12529.csv.gz  in=254,602,758 out=41,320,459 elapsed=80.0s

  [3784/15692] intraday_12530.csv.gz  in=254,615,596 out=41,333,297 elapsed=80.1s

  [3785/15692] intraday_12533.csv.gz  in=254,629,912 out=41,347,613 elapsed=80.1s

  [3786/15692] intraday_12532.csv.gz  in=254,641,911 out=41,359,612 elapsed=80.1s

  [3787/15692] intraday_12531.csv.gz  in=254,656,539 out=41,374,240 elapsed=80.1s

  [3788/15692] intraday_12537.csv.gz  in=254,670,587 out=41,388,288 elapsed=80.2s

  [3789/15692] intraday_12535.csv.gz  in=254,683,467 out=41,401,168 elapsed=80.2s

  [3790/15692] intraday_12536.csv.gz  in=254,695,950 out=41,413,651 elapsed=80.2s

  [3791/15692] intraday_12534.csv.gz  in=254,710,772 out=41,428,473 elapsed=80.2s

  [3792/15692] intraday_1254.csv.gz  in=254,723,321 out=41,428,473 elapsed=80.2s

  [3793/15692] intraday_12539.csv.gz  in=254,736,203 out=41,441,355 elapsed=80.2s

  [3794/15692] intraday_12540.csv.gz  in=254,752,212 out=41,457,364 elapsed=80.2s

  [3795/15692] intraday_12538.csv.gz  in=254,769,143 out=41,474,295 elapsed=80.2s

  [3796/15692] intraday_12541.csv.gz  in=254,788,764 out=41,493,916 elapsed=80.2s

  [3797/15692] intraday_12544.csv.gz  in=254,801,796 out=41,506,948 elapsed=80.3s

  [3798/15692] intraday_12542.csv.gz  in=254,816,872 out=41,522,024 elapsed=80.3s

  [3799/15692] intraday_12543.csv.gz  in=254,834,600 out=41,539,752 elapsed=80.3s

  [3800/15692] intraday_12545.csv.gz  in=254,846,858 out=41,552,010 elapsed=80.3s

  [3801/15692] intraday_12546.csv.gz  in=254,859,642 out=41,564,794 elapsed=80.3s

  [3802/15692] intraday_12547.csv.gz  in=254,872,367 out=41,577,519 elapsed=80.3s

  [3803/15692] intraday_12549.csv.gz  in=254,884,211 out=41,589,363 elapsed=80.3s

  [3804/15692] intraday_12548.csv.gz  in=254,896,392 out=41,601,544 elapsed=80.3s

  [3805/15692] intraday_1255.csv.gz  in=254,908,885 out=41,601,544 elapsed=80.3s

  [3806/15692] intraday_12550.csv.gz  in=254,923,075 out=41,615,734 elapsed=80.4s

  [3807/15692] intraday_12553.csv.gz  in=254,934,825 out=41,627,484 elapsed=80.4s

  [3808/15692] intraday_12552.csv.gz  in=254,948,430 out=41,641,089 elapsed=80.4s

  [3809/15692] intraday_12554.csv.gz  in=254,959,718 out=41,652,377 elapsed=80.4s

  [3810/15692] intraday_12551.csv.gz  in=254,974,573 out=41,667,232 elapsed=80.4s

  [3811/15692] intraday_12555.csv.gz  in=254,989,202 out=41,681,861 elapsed=80.4s

  [3812/15692] intraday_12557.csv.gz  in=255,002,184 out=41,694,843 elapsed=80.5s

  [3813/15692] intraday_12558.csv.gz  in=255,017,104 out=41,709,763 elapsed=80.5s

  [3814/15692] intraday_12556.csv.gz  in=255,028,613 out=41,721,272 elapsed=80.5s

  [3815/15692] intraday_1256.csv.gz  in=255,048,177 out=41,721,272 elapsed=80.5s

  [3816/15692] intraday_12559.csv.gz  in=255,063,672 out=41,736,767 elapsed=80.5s

  [3817/15692] intraday_12563.csv.gz  in=255,076,591 out=41,749,686 elapsed=80.6s

  [3818/15692] intraday_12561.csv.gz  in=255,092,682 out=41,765,777 elapsed=80.6s

  [3819/15692] intraday_12562.csv.gz  in=255,104,308 out=41,777,403 elapsed=80.6s

  [3820/15692] intraday_12560.csv.gz  in=255,118,242 out=41,791,337 elapsed=80.6s

  [3821/15692] intraday_12564.csv.gz  in=255,130,226 out=41,803,321 elapsed=80.6s

  [3822/15692] intraday_12565.csv.gz  in=255,142,225 out=41,815,320 elapsed=80.6s

  [3823/15692] intraday_12567.csv.gz  in=255,148,960 out=41,822,055 elapsed=80.6s

  [3824/15692] intraday_12566.csv.gz  in=255,159,094 out=41,832,189 elapsed=80.6s

  [3825/15692] intraday_12568.csv.gz  in=255,173,207 out=41,846,302 elapsed=80.6s

  [3826/15692] intraday_12569.csv.gz  in=255,179,345 out=41,852,440 elapsed=80.7s

  [3827/15692] intraday_1257.csv.gz  in=255,196,915 out=41,852,440 elapsed=80.7s

  [3828/15692] intraday_12570.csv.gz  in=255,214,369 out=41,869,894 elapsed=80.7s

  [3829/15692] intraday_12572.csv.gz  in=255,227,953 out=41,883,478 elapsed=80.7s

  [3830/15692] intraday_12573.csv.gz  in=255,239,089 out=41,894,614 elapsed=80.7s

  [3831/15692] intraday_12571.csv.gz  in=255,251,980 out=41,907,505 elapsed=80.7s

  [3832/15692] intraday_12574.csv.gz  in=255,263,614 out=41,919,139 elapsed=80.7s

  [3833/15692] intraday_12575.csv.gz  in=255,277,869 out=41,933,394 elapsed=80.7s

  [3834/15692] intraday_12577.csv.gz  in=255,290,717 out=41,946,242 elapsed=80.8s

  [3835/15692] intraday_12578.csv.gz  in=255,303,701 out=41,959,226 elapsed=80.8s

  [3836/15692] intraday_12576.csv.gz  in=255,320,746 out=41,976,271 elapsed=80.8s

  [3837/15692] intraday_1258.csv.gz  in=255,333,582 out=41,976,271 elapsed=80.8s

  [3838/15692] intraday_12579.csv.gz  in=255,347,391 out=41,990,080 elapsed=80.8s

  [3839/15692] intraday_12580.csv.gz  in=255,360,628 out=42,003,317 elapsed=80.8s

  [3840/15692] intraday_12583.csv.gz  in=255,374,071 out=42,016,760 elapsed=80.8s

  [3841/15692] intraday_12582.csv.gz  in=255,388,840 out=42,031,529 elapsed=80.9s

  [3842/15692] intraday_12581.csv.gz  in=255,400,506 out=42,043,195 elapsed=80.9s

  [3843/15692] intraday_12584.csv.gz  in=255,410,286 out=42,052,975 elapsed=80.9s

  [3844/15692] intraday_12585.csv.gz  in=255,421,356 out=42,064,045 elapsed=80.9s

  [3845/15692] intraday_12586.csv.gz  in=255,436,400 out=42,079,089 elapsed=80.9s

  [3846/15692] intraday_12588.csv.gz  in=255,446,307 out=42,088,996 elapsed=80.9s

  [3847/15692] intraday_12587.csv.gz  in=255,459,541 out=42,102,230 elapsed=80.9s

  [3848/15692] intraday_12589.csv.gz  in=255,470,106 out=42,112,795 elapsed=80.9s

  [3849/15692] intraday_1259.csv.gz  in=255,483,550 out=42,112,795 elapsed=80.9s

  [3850/15692] intraday_12590.csv.gz  in=255,494,605 out=42,123,850 elapsed=81.0s

  [3851/15692] intraday_12591.csv.gz  in=255,506,950 out=42,136,195 elapsed=81.0s

  [3852/15692] intraday_12593.csv.gz  in=255,518,971 out=42,148,216 elapsed=81.0s

  [3853/15692] intraday_12592.csv.gz  in=255,530,958 out=42,160,203 elapsed=81.0s

  [3854/15692] intraday_12594.csv.gz  in=255,545,023 out=42,174,268 elapsed=81.0s

  [3855/15692] intraday_12595.csv.gz  in=255,556,185 out=42,185,430 elapsed=81.0s

  [3856/15692] intraday_12596.csv.gz  in=255,568,060 out=42,197,305 elapsed=81.0s

  [3857/15692] intraday_12597.csv.gz  in=255,580,813 out=42,210,058 elapsed=81.0s

  [3858/15692] intraday_12599.csv.gz  in=255,594,043 out=42,223,288 elapsed=81.1s

  [3859/15692] intraday_1260.csv.gz  in=255,609,240 out=42,223,288 elapsed=81.1s

  [3860/15692] intraday_12598.csv.gz  in=255,621,072 out=42,235,120 elapsed=81.1s

  [3861/15692] intraday_12600.csv.gz  in=255,637,099 out=42,251,147 elapsed=81.1s

  [3862/15692] intraday_12601.csv.gz  in=255,650,388 out=42,264,436 elapsed=81.1s

  [3863/15692] intraday_12602.csv.gz  in=255,660,431 out=42,274,479 elapsed=81.1s

  [3864/15692] intraday_12603.csv.gz  in=255,673,643 out=42,287,691 elapsed=81.1s

  [3865/15692] intraday_12605.csv.gz  in=255,687,056 out=42,301,104 elapsed=81.1s

  [3866/15692] intraday_12604.csv.gz  in=255,699,993 out=42,314,041 elapsed=81.1s

  [3867/15692] intraday_12607.csv.gz  in=255,710,701 out=42,324,749 elapsed=81.1s

  [3868/15692] intraday_12606.csv.gz  in=255,723,325 out=42,337,373 elapsed=81.1s

  [3869/15692] intraday_1261.csv.gz  in=255,736,635 out=42,337,373 elapsed=81.2s

  [3870/15692] intraday_12608.csv.gz  in=255,753,023 out=42,350,287 elapsed=81.2s

  [3871/15692] intraday_12609.csv.gz  in=255,763,546 out=42,360,486 elapsed=81.2s

  [3872/15692] intraday_12610.csv.gz  in=255,775,487 out=42,372,427 elapsed=81.2s

  [3873/15692] intraday_12611.csv.gz  in=255,789,638 out=42,386,578 elapsed=81.2s

  [3874/15692] intraday_12612.csv.gz  in=255,800,781 out=42,397,721 elapsed=81.2s

  [3875/15692] intraday_12613.csv.gz  in=255,822,549 out=42,416,195 elapsed=81.2s

  [3876/15692] intraday_12615.csv.gz  in=255,835,137 out=42,428,783 elapsed=81.2s

  [3877/15692] intraday_12614.csv.gz  in=255,849,330 out=42,442,976 elapsed=81.3s

  [3878/15692] intraday_12616.csv.gz  in=255,860,488 out=42,454,134 elapsed=81.3s

  [3879/15692] intraday_12617.csv.gz  in=255,872,070 out=42,465,716 elapsed=81.3s

  [3880/15692] intraday_12618.csv.gz  in=255,885,394 out=42,479,040 elapsed=81.3s

  [3881/15692] intraday_12619.csv.gz  in=255,896,000 out=42,489,646 elapsed=81.3s

  [3882/15692] intraday_1262.csv.gz  in=255,908,076 out=42,489,646 elapsed=81.3s

  [3883/15692] intraday_12621.csv.gz  in=255,918,143 out=42,499,713 elapsed=81.3s

  [3884/15692] intraday_12620.csv.gz  in=255,951,025 out=42,524,683 elapsed=81.4s

  [3885/15692] intraday_12624.csv.gz  in=255,963,311 out=42,536,969 elapsed=81.4s

  [3886/15692] intraday_12623.csv.gz  in=255,976,282 out=42,549,940 elapsed=81.4s

  [3887/15692] intraday_12622.csv.gz  in=255,991,024 out=42,564,682 elapsed=81.4s

  [3888/15692] intraday_12625.csv.gz  in=256,004,822 out=42,578,480 elapsed=81.4s

  [3889/15692] intraday_12626.csv.gz  in=256,016,120 out=42,589,778 elapsed=81.4s

  [3890/15692] intraday_12627.csv.gz  in=256,027,793 out=42,601,451 elapsed=81.4s

  [3891/15692] intraday_12628.csv.gz  in=256,038,078 out=42,611,736 elapsed=81.5s

  [3892/15692] intraday_1263.csv.gz  in=256,051,375 out=42,611,736 elapsed=81.5s

  [3893/15692] intraday_12630.csv.gz  in=256,063,024 out=42,623,385 elapsed=81.5s

  [3894/15692] intraday_12629.csv.gz  in=256,077,241 out=42,636,611 elapsed=81.5s

  [3895/15692] intraday_12631.csv.gz  in=256,090,591 out=42,649,626 elapsed=81.5s

  [3896/15692] intraday_12633.csv.gz  in=256,103,233 out=42,662,268 elapsed=81.5s

  [3897/15692] intraday_12632.csv.gz  in=256,125,364 out=42,680,970 elapsed=81.5s

  [3898/15692] intraday_12634.csv.gz  in=256,134,565 out=42,690,171 elapsed=81.5s

  [3899/15692] intraday_12635.csv.gz  in=256,148,863 out=42,704,469 elapsed=81.6s

  [3900/15692] intraday_12637.csv.gz  in=256,162,093 out=42,717,699 elapsed=81.6s

  [3901/15692] intraday_12636.csv.gz  in=256,176,925 out=42,732,531 elapsed=81.6s

  [3902/15692] intraday_12638.csv.gz  in=256,190,474 out=42,746,080 elapsed=81.6s

  [3903/15692] intraday_12639.csv.gz  in=256,204,606 out=42,760,212 elapsed=81.6s

  [3904/15692] intraday_1264.csv.gz  in=256,219,180 out=42,760,212 elapsed=81.6s

  [3905/15692] intraday_12640.csv.gz  in=256,229,495 out=42,770,527 elapsed=81.6s

  [3906/15692] intraday_12641.csv.gz  in=256,241,714 out=42,782,589 elapsed=81.6s

  [3907/15692] intraday_12643.csv.gz  in=256,254,091 out=42,794,966 elapsed=81.6s

  [3908/15692] intraday_12642.csv.gz  in=256,267,739 out=42,808,614 elapsed=81.7s

  [3909/15692] intraday_12644.csv.gz  in=256,281,393 out=42,821,966 elapsed=81.7s

  [3910/15692] intraday_12645.csv.gz  in=256,292,343 out=42,832,916 elapsed=81.7s

  [3911/15692] intraday_12646.csv.gz  in=256,304,644 out=42,845,217 elapsed=81.7s

  [3912/15692] intraday_12647.csv.gz  in=256,315,866 out=42,856,439 elapsed=81.7s

  [3913/15692] intraday_12648.csv.gz  in=256,329,381 out=42,869,954 elapsed=81.7s

  [3914/15692] intraday_1265.csv.gz  in=256,340,977 out=42,869,954 elapsed=81.7s

  [3915/15692] intraday_12649.csv.gz  in=256,351,909 out=42,880,886 elapsed=81.8s

  [3916/15692] intraday_12650.csv.gz  in=256,364,703 out=42,893,680 elapsed=81.8s

  [3917/15692] intraday_12651.csv.gz  in=256,375,588 out=42,904,565 elapsed=81.8s

  [3918/15692] intraday_12652.csv.gz  in=256,385,471 out=42,914,448 elapsed=81.8s

  [3919/15692] intraday_12653.csv.gz  in=256,399,431 out=42,928,408 elapsed=81.8s

  [3920/15692] intraday_12654.csv.gz  in=256,413,134 out=42,942,111 elapsed=81.8s

  [3921/15692] intraday_12655.csv.gz  in=256,428,977 out=42,957,954 elapsed=81.8s

  [3922/15692] intraday_12656.csv.gz  in=256,442,333 out=42,971,310 elapsed=81.9s

  [3923/15692] intraday_12658.csv.gz  in=256,453,432 out=42,982,409 elapsed=81.9s

  [3924/15692] intraday_12657.csv.gz  in=256,471,942 out=42,998,562 elapsed=81.9s

  [3925/15692] intraday_12659.csv.gz  in=256,485,334 out=43,011,954 elapsed=81.9s

  [3926/15692] intraday_12660.csv.gz  in=256,499,741 out=43,026,361 elapsed=81.9s

  [3927/15692] intraday_1266.csv.gz  in=256,514,516 out=43,026,361 elapsed=81.9s

  [3928/15692] intraday_12661.csv.gz  in=256,527,912 out=43,039,757 elapsed=81.9s

  [3929/15692] intraday_12662.csv.gz  in=256,539,149 out=43,050,994 elapsed=81.9s

  [3930/15692] intraday_12663.csv.gz  in=256,554,556 out=43,066,401 elapsed=82.0s

  [3931/15692] intraday_12664.csv.gz  in=256,568,300 out=43,080,145 elapsed=82.0s

  [3932/15692] intraday_12665.csv.gz  in=256,579,228 out=43,091,073 elapsed=82.0s

  [3933/15692] intraday_12667.csv.gz  in=256,590,014 out=43,101,859 elapsed=82.0s

  [3934/15692] intraday_12666.csv.gz  in=256,603,840 out=43,115,685 elapsed=82.0s

  [3935/15692] intraday_12669.csv.gz  in=256,615,294 out=43,127,139 elapsed=82.0s

  [3936/15692] intraday_1267.csv.gz  in=256,627,614 out=43,127,139 elapsed=82.0s

  [3937/15692] intraday_12668.csv.gz  in=256,640,216 out=43,139,741 elapsed=82.0s

  [3938/15692] intraday_12670.csv.gz  in=256,652,522 out=43,152,047 elapsed=82.1s

  [3939/15692] intraday_12672.csv.gz  in=256,664,422 out=43,163,947 elapsed=82.1s

  [3940/15692] intraday_12673.csv.gz  in=256,678,681 out=43,178,206 elapsed=82.1s

  [3941/15692] intraday_12671.csv.gz  in=256,690,876 out=43,190,401 elapsed=82.1s

  [3942/15692] intraday_12674.csv.gz  in=256,703,588 out=43,203,113 elapsed=82.1s

  [3943/15692] intraday_12675.csv.gz  in=256,717,538 out=43,217,063 elapsed=82.2s

  [3944/15692] intraday_12677.csv.gz  in=256,731,856 out=43,231,381 elapsed=82.2s

  [3945/15692] intraday_12676.csv.gz  in=256,744,152 out=43,243,677 elapsed=82.2s

  [3946/15692] intraday_12679.csv.gz  in=256,755,575 out=43,255,100 elapsed=82.2s

  [3947/15692] intraday_12678.csv.gz  in=256,768,460 out=43,267,985 elapsed=82.2s

  [3948/15692] intraday_1268.csv.gz  in=256,779,591 out=43,267,985 elapsed=82.2s

  [3949/15692] intraday_12680.csv.gz  in=256,793,627 out=43,282,021 elapsed=82.2s

  [3950/15692] intraday_12682.csv.gz  in=256,806,492 out=43,294,886 elapsed=82.2s

  [3951/15692] intraday_12681.csv.gz  in=256,821,252 out=43,309,646 elapsed=82.3s

  [3952/15692] intraday_12684.csv.gz  in=256,836,371 out=43,324,765 elapsed=82.3s

  [3953/15692] intraday_12683.csv.gz  in=256,848,725 out=43,337,119 elapsed=82.3s

  [3954/15692] intraday_12685.csv.gz  in=256,863,880 out=43,352,274 elapsed=82.3s

  [3955/15692] intraday_12686.csv.gz  in=256,877,607 out=43,366,001 elapsed=82.3s

  [3956/15692] intraday_12688.csv.gz  in=256,898,736 out=43,387,130 elapsed=82.3s

  [3957/15692] intraday_12689.csv.gz  in=256,911,636 out=43,400,030 elapsed=82.3s

  [3958/15692] intraday_12687.csv.gz  in=256,927,974 out=43,416,368 elapsed=82.3s

  [3959/15692] intraday_1269.csv.gz  in=256,939,211 out=43,416,368 elapsed=82.3s

  [3960/15692] intraday_12690.csv.gz  in=256,955,293 out=43,432,450 elapsed=82.4s

  [3961/15692] intraday_12692.csv.gz  in=256,967,744 out=43,444,901 elapsed=82.4s

  [3962/15692] intraday_12691.csv.gz  in=256,980,985 out=43,458,142 elapsed=82.4s

  [3963/15692] intraday_12693.csv.gz  in=256,998,221 out=43,473,851 elapsed=82.4s

  [3964/15692] intraday_12694.csv.gz  in=257,010,542 out=43,486,172 elapsed=82.4s

  [3965/15692] intraday_12695.csv.gz  in=257,022,489 out=43,498,119 elapsed=82.4s

  [3966/15692] intraday_12696.csv.gz  in=257,034,362 out=43,509,992 elapsed=82.4s

  [3967/15692] intraday_12697.csv.gz  in=257,046,913 out=43,522,543 elapsed=82.5s

  [3968/15692] intraday_12698.csv.gz  in=257,060,900 out=43,536,530 elapsed=82.5s

  [3969/15692] intraday_12699.csv.gz  in=257,074,430 out=43,550,060 elapsed=82.5s

  [3970/15692] intraday_1270.csv.gz  in=257,085,186 out=43,550,060 elapsed=82.5s

  [3971/15692] intraday_12700.csv.gz  in=257,097,410 out=43,562,284 elapsed=82.5s

  [3972/15692] intraday_12701.csv.gz  in=257,108,657 out=43,573,531 elapsed=82.5s

  [3973/15692] intraday_12702.csv.gz  in=257,122,295 out=43,587,169 elapsed=82.5s

  [3974/15692] intraday_12703.csv.gz  in=257,134,426 out=43,599,300 elapsed=82.5s

  [3975/15692] intraday_12704.csv.gz  in=257,146,273 out=43,611,147 elapsed=82.6s

  [3976/15692] intraday_12705.csv.gz  in=257,160,829 out=43,625,703 elapsed=82.6s

  [3977/15692] intraday_12706.csv.gz  in=257,177,201 out=43,642,075 elapsed=82.6s

  [3978/15692] intraday_12707.csv.gz  in=257,190,927 out=43,655,801 elapsed=82.6s

  [3979/15692] intraday_12708.csv.gz  in=257,206,698 out=43,671,572 elapsed=82.6s

  [3980/15692] intraday_1271.csv.gz  in=257,230,249 out=43,671,572 elapsed=82.6s

  [3981/15692] intraday_12709.csv.gz  in=257,241,901 out=43,683,224 elapsed=82.6s

  [3982/15692] intraday_12710.csv.gz  in=257,254,255 out=43,695,578 elapsed=82.6s

  [3983/15692] intraday_12711.csv.gz  in=257,264,947 out=43,706,270 elapsed=82.7s

  [3984/15692] intraday_12712.csv.gz  in=257,277,521 out=43,718,844 elapsed=82.7s

  [3985/15692] intraday_12713.csv.gz  in=257,287,594 out=43,728,917 elapsed=82.7s

  [3986/15692] intraday_12714.csv.gz  in=257,293,707 out=43,735,030 elapsed=82.7s

  [3987/15692] intraday_12715.csv.gz  in=257,308,470 out=43,749,793 elapsed=82.7s

  [3988/15692] intraday_12716.csv.gz  in=257,315,237 out=43,756,560 elapsed=82.7s

  [3989/15692] intraday_12718.csv.gz  in=257,329,147 out=43,770,470 elapsed=82.7s

  [3990/15692] intraday_12719.csv.gz  in=257,341,882 out=43,783,205 elapsed=82.8s

  [3991/15692] intraday_12717.csv.gz  in=257,358,261 out=43,799,584 elapsed=82.8s

  [3992/15692] intraday_1272.csv.gz  in=257,371,457 out=43,799,584 elapsed=82.8s

  [3993/15692] intraday_12720.csv.gz  in=257,381,395 out=43,809,522 elapsed=82.8s

  [3994/15692] intraday_12722.csv.gz  in=257,394,716 out=43,822,843 elapsed=82.8s

  [3995/15692] intraday_12721.csv.gz  in=257,407,190 out=43,835,317 elapsed=82.8s

  [3996/15692] intraday_12723.csv.gz  in=257,422,590 out=43,850,717 elapsed=82.8s

  [3997/15692] intraday_12725.csv.gz  in=257,436,484 out=43,864,611 elapsed=82.8s

  [3998/15692] intraday_12724.csv.gz  in=257,446,939 out=43,875,066 elapsed=82.8s

  [3999/15692] intraday_12726.csv.gz  in=257,459,982 out=43,888,109 elapsed=82.9s

  [4000/15692] intraday_12727.csv.gz  in=257,472,428 out=43,900,555 elapsed=82.9s

  [4001/15692] intraday_12728.csv.gz  in=257,484,066 out=43,912,193 elapsed=82.9s

  [4002/15692] intraday_1273.csv.gz  in=257,502,141 out=43,912,193 elapsed=82.9s

  [4003/15692] intraday_12729.csv.gz  in=257,528,383 out=43,933,951 elapsed=82.9s

  [4004/15692] intraday_12731.csv.gz  in=257,538,378 out=43,943,946 elapsed=82.9s

  [4005/15692] intraday_12732.csv.gz  in=257,547,640 out=43,953,208 elapsed=82.9s

  [4006/15692] intraday_12730.csv.gz  in=257,560,580 out=43,966,148 elapsed=82.9s

  [4007/15692] intraday_12734.csv.gz  in=257,572,815 out=43,978,383 elapsed=83.0s

  [4008/15692] intraday_12733.csv.gz  in=257,587,144 out=43,992,712 elapsed=83.0s

  [4009/15692] intraday_12735.csv.gz  in=257,597,322 out=44,002,890 elapsed=83.0s

  [4010/15692] intraday_12736.csv.gz  in=257,608,403 out=44,013,971 elapsed=83.0s

  [4011/15692] intraday_12738.csv.gz  in=257,620,466 out=44,026,030 elapsed=83.0s

  [4012/15692] intraday_12737.csv.gz  in=257,630,827 out=44,036,391 elapsed=83.0s

  [4013/15692] intraday_1274.csv.gz  in=257,647,047 out=44,036,391 elapsed=83.0s

  [4014/15692] intraday_12739.csv.gz  in=257,659,354 out=44,048,698 elapsed=83.0s

  [4015/15692] intraday_12741.csv.gz  in=257,674,591 out=44,063,935 elapsed=83.0s

  [4016/15692] intraday_12740.csv.gz  in=257,686,021 out=44,075,365 elapsed=83.0s

  [4017/15692] intraday_12742.csv.gz  in=257,697,226 out=44,086,093 elapsed=83.0s

  [4018/15692] intraday_12743.csv.gz  in=257,709,974 out=44,098,841 elapsed=83.1s

  [4019/15692] intraday_12744.csv.gz  in=257,722,772 out=44,111,639 elapsed=83.1s

  [4020/15692] intraday_12745.csv.gz  in=257,734,453 out=44,123,320 elapsed=83.1s

  [4021/15692] intraday_12747.csv.gz  in=257,751,650 out=44,138,872 elapsed=83.1s

  [4022/15692] intraday_12748.csv.gz  in=257,764,973 out=44,152,195 elapsed=83.1s

  [4023/15692] intraday_12749.csv.gz  in=257,775,392 out=44,162,614 elapsed=83.1s

  [4024/15692] intraday_12746.csv.gz  in=257,788,985 out=44,176,207 elapsed=83.1s

  [4025/15692] intraday_1275.csv.gz  in=257,800,535 out=44,176,207 elapsed=83.1s

  [4026/15692] intraday_12750.csv.gz  in=257,813,324 out=44,188,996 elapsed=83.2s

  [4027/15692] intraday_12751.csv.gz  in=257,826,405 out=44,202,077 elapsed=83.2s

  [4028/15692] intraday_12753.csv.gz  in=257,839,106 out=44,214,778 elapsed=83.2s

  [4029/15692] intraday_12752.csv.gz  in=257,852,515 out=44,228,187 elapsed=83.2s

  [4030/15692] intraday_12754.csv.gz  in=257,863,097 out=44,238,769 elapsed=83.2s

  [4031/15692] intraday_12755.csv.gz  in=257,874,439 out=44,250,111 elapsed=83.2s

  [4032/15692] intraday_12756.csv.gz  in=257,884,470 out=44,260,142 elapsed=83.2s

  [4033/15692] intraday_12757.csv.gz  in=257,895,133 out=44,270,805 elapsed=83.2s

  [4034/15692] intraday_12759.csv.gz  in=257,906,324 out=44,281,996 elapsed=83.2s

  [4035/15692] intraday_12758.csv.gz  in=257,919,724 out=44,295,396 elapsed=83.2s

  [4036/15692] intraday_1276.csv.gz  in=257,932,551 out=44,295,396 elapsed=83.2s

  [4037/15692] intraday_12760.csv.gz  in=257,944,926 out=44,307,771 elapsed=83.2s

  [4038/15692] intraday_12763.csv.gz  in=257,956,145 out=44,318,990 elapsed=83.3s

  [4039/15692] intraday_12764.csv.gz  in=257,968,262 out=44,330,078 elapsed=83.3s

  [4040/15692] intraday_12762.csv.gz  in=257,979,749 out=44,341,565 elapsed=83.3s

  [4041/15692] intraday_12761.csv.gz  in=257,993,942 out=44,355,758 elapsed=83.3s

  [4042/15692] intraday_12765.csv.gz  in=258,006,220 out=44,368,036 elapsed=83.3s

  [4043/15692] intraday_12766.csv.gz  in=258,016,683 out=44,378,499 elapsed=83.3s

  [4044/15692] intraday_12767.csv.gz  in=258,028,361 out=44,390,177 elapsed=83.3s

  [4045/15692] intraday_12768.csv.gz  in=258,039,354 out=44,401,170 elapsed=83.3s

  [4046/15692] intraday_12769.csv.gz  in=258,052,608 out=44,414,326 elapsed=83.4s

  [4047/15692] intraday_1277.csv.gz  in=258,064,537 out=44,414,326 elapsed=83.4s

  [4048/15692] intraday_12770.csv.gz  in=258,076,474 out=44,426,263 elapsed=83.4s

  [4049/15692] intraday_12771.csv.gz  in=258,088,231 out=44,438,020 elapsed=83.4s

  [4050/15692] intraday_12772.csv.gz  in=258,101,967 out=44,451,756 elapsed=83.4s

  [4051/15692] intraday_12773.csv.gz  in=258,112,774 out=44,462,563 elapsed=83.4s

  [4052/15692] intraday_12774.csv.gz  in=258,124,864 out=44,474,653 elapsed=83.5s

  [4053/15692] intraday_12775.csv.gz  in=258,134,757 out=44,484,546 elapsed=83.5s

  [4054/15692] intraday_12776.csv.gz  in=258,146,379 out=44,496,168 elapsed=83.5s

  [4055/15692] intraday_12777.csv.gz  in=258,159,841 out=44,509,630 elapsed=83.5s

  [4056/15692] intraday_12778.csv.gz  in=258,170,837 out=44,520,626 elapsed=83.5s

  [4057/15692] intraday_12779.csv.gz  in=258,182,611 out=44,532,400 elapsed=83.5s

  [4058/15692] intraday_1278.csv.gz  in=258,195,271 out=44,532,400 elapsed=83.5s

  [4059/15692] intraday_12781.csv.gz  in=258,204,167 out=44,541,296 elapsed=83.6s

  [4060/15692] intraday_12780.csv.gz  in=258,216,025 out=44,553,154 elapsed=83.6s

  [4061/15692] intraday_12782.csv.gz  in=258,229,491 out=44,566,620 elapsed=83.6s

  [4062/15692] intraday_12783.csv.gz  in=258,243,271 out=44,580,400 elapsed=83.6s

  [4063/15692] intraday_12784.csv.gz  in=258,256,496 out=44,593,625 elapsed=83.6s

  [4064/15692] intraday_12785.csv.gz  in=258,269,933 out=44,607,062 elapsed=83.6s

  [4065/15692] intraday_12786.csv.gz  in=258,285,875 out=44,621,707 elapsed=83.6s

  [4066/15692] intraday_12787.csv.gz  in=258,296,504 out=44,632,336 elapsed=83.6s

  [4067/15692] intraday_12788.csv.gz  in=258,308,339 out=44,644,171 elapsed=83.6s

  [4068/15692] intraday_12789.csv.gz  in=258,320,815 out=44,656,647 elapsed=83.6s

  [4069/15692] intraday_1279.csv.gz  in=258,332,726 out=44,656,647 elapsed=83.7s

  [4070/15692] intraday_12790.csv.gz  in=258,344,329 out=44,668,250 elapsed=83.7s

  [4071/15692] intraday_12792.csv.gz  in=258,356,405 out=44,680,326 elapsed=83.7s

  [4072/15692] intraday_12791.csv.gz  in=258,369,919 out=44,693,840 elapsed=83.7s

  [4073/15692] intraday_12794.csv.gz  in=258,379,863 out=44,703,784 elapsed=83.7s

  [4074/15692] intraday_12793.csv.gz  in=258,396,320 out=44,718,591 elapsed=83.7s

  [4075/15692] intraday_12796.csv.gz  in=258,407,557 out=44,729,828 elapsed=83.8s

  [4076/15692] intraday_12797.csv.gz  in=258,419,188 out=44,741,459 elapsed=83.8s

  [4077/15692] intraday_12799.csv.gz  in=258,429,369 out=44,751,640 elapsed=83.8s

  [4078/15692] intraday_12798.csv.gz  in=258,440,896 out=44,763,167 elapsed=83.8s

  [4079/15692] intraday_12795.csv.gz  in=258,454,320 out=44,776,591 elapsed=83.8s

  [4080/15692] intraday_1280.csv.gz  in=258,465,121 out=44,776,591 elapsed=83.8s

  [4081/15692] intraday_12800.csv.gz  in=258,478,137 out=44,789,607 elapsed=83.8s

  [4082/15692] intraday_12801.csv.gz  in=258,490,818 out=44,802,288 elapsed=83.9s

  [4083/15692] intraday_12802.csv.gz  in=258,507,274 out=44,818,744 elapsed=83.9s

  [4084/15692] intraday_12803.csv.gz  in=258,520,984 out=44,832,454 elapsed=83.9s

  [4085/15692] intraday_12804.csv.gz  in=258,532,974 out=44,844,444 elapsed=83.9s

  [4086/15692] intraday_12805.csv.gz  in=258,543,342 out=44,854,812 elapsed=83.9s

  [4087/15692] intraday_12806.csv.gz  in=258,555,732 out=44,867,202 elapsed=83.9s

  [4088/15692] intraday_12807.csv.gz  in=258,568,323 out=44,879,793 elapsed=83.9s

  [4089/15692] intraday_12808.csv.gz  in=258,582,733 out=44,894,203 elapsed=83.9s

  [4090/15692] intraday_12809.csv.gz  in=258,594,652 out=44,905,269 elapsed=84.0s

  [4091/15692] intraday_1281.csv.gz  in=258,609,273 out=44,905,269 elapsed=84.0s

  [4092/15692] intraday_12810.csv.gz  in=258,623,481 out=44,919,477 elapsed=84.0s

  [4093/15692] intraday_12812.csv.gz  in=258,635,504 out=44,931,472 elapsed=84.0s

  [4094/15692] intraday_12811.csv.gz  in=258,649,450 out=44,945,418 elapsed=84.0s

  [4095/15692] intraday_12814.csv.gz  in=258,661,966 out=44,957,934 elapsed=84.0s

  [4096/15692] intraday_12813.csv.gz  in=258,689,272 out=44,978,222 elapsed=84.0s

  [4097/15692] intraday_12816.csv.gz  in=258,698,548 out=44,987,498 elapsed=84.1s

  [4098/15692] intraday_12815.csv.gz  in=258,711,938 out=45,000,888 elapsed=84.1s

  [4099/15692] intraday_12817.csv.gz  in=258,724,262 out=45,013,212 elapsed=84.1s

  [4100/15692] intraday_12818.csv.gz  in=258,735,292 out=45,024,242 elapsed=84.1s

  [4101/15692] intraday_1282.csv.gz  in=258,746,671 out=45,024,242 elapsed=84.1s

  [4102/15692] intraday_12820.csv.gz  in=258,760,815 out=45,038,386 elapsed=84.1s

  [4103/15692] intraday_12819.csv.gz  in=258,773,222 out=45,050,793 elapsed=84.1s

  [4104/15692] intraday_12822.csv.gz  in=258,787,806 out=45,065,377 elapsed=84.2s

  [4105/15692] intraday_12823.csv.gz  in=258,800,415 out=45,077,986 elapsed=84.2s

  [4106/15692] intraday_12821.csv.gz  in=258,812,249 out=45,089,820 elapsed=84.2s

  [4107/15692] intraday_12824.csv.gz  in=258,828,385 out=45,104,858 elapsed=84.2s

  [4108/15692] intraday_12825.csv.gz  in=258,840,530 out=45,117,003 elapsed=84.2s

  [4109/15692] intraday_12826.csv.gz  in=258,852,525 out=45,128,998 elapsed=84.2s

  [4110/15692] intraday_12827.csv.gz  in=258,865,415 out=45,141,888 elapsed=84.2s

  [4111/15692] intraday_12828.csv.gz  in=258,879,620 out=45,156,093 elapsed=84.2s

  [4112/15692] intraday_12829.csv.gz  in=258,891,741 out=45,168,214 elapsed=84.2s

  [4113/15692] intraday_1283.csv.gz  in=258,903,612 out=45,168,214 elapsed=84.3s

  [4114/15692] intraday_12830.csv.gz  in=258,916,397 out=45,180,999 elapsed=84.3s

  [4115/15692] intraday_12831.csv.gz  in=258,930,479 out=45,195,081 elapsed=84.3s

  [4116/15692] intraday_12832.csv.gz  in=258,944,552 out=45,209,154 elapsed=84.3s

  [4117/15692] intraday_12833.csv.gz  in=258,956,403 out=45,221,005 elapsed=84.3s

  [4118/15692] intraday_12834.csv.gz  in=258,971,670 out=45,236,272 elapsed=84.3s

  [4119/15692] intraday_12835.csv.gz  in=258,991,089 out=45,255,691 elapsed=84.4s

  [4120/15692] intraday_12836.csv.gz  in=259,004,012 out=45,268,614 elapsed=84.4s

  [4121/15692] intraday_12837.csv.gz  in=259,019,133 out=45,283,735 elapsed=84.4s

  [4122/15692] intraday_12838.csv.gz  in=259,031,411 out=45,296,013 elapsed=84.4s

  [4123/15692] intraday_1284.csv.gz  in=259,043,285 out=45,296,013 elapsed=84.4s

  [4124/15692] intraday_12839.csv.gz  in=259,055,675 out=45,308,403 elapsed=84.4s

  [4125/15692] intraday_12841.csv.gz  in=259,068,368 out=45,321,096 elapsed=84.4s

  [4126/15692] intraday_12840.csv.gz  in=259,081,313 out=45,334,041 elapsed=84.4s

  [4127/15692] intraday_12842.csv.gz  in=259,091,821 out=45,344,549 elapsed=84.4s

  [4128/15692] intraday_12843.csv.gz  in=259,104,371 out=45,356,271 elapsed=84.4s

  [4129/15692] intraday_12845.csv.gz  in=259,117,857 out=45,369,757 elapsed=84.5s

  [4130/15692] intraday_12844.csv.gz  in=259,130,058 out=45,381,958 elapsed=84.5s

  [4131/15692] intraday_12846.csv.gz  in=259,143,175 out=45,394,535 elapsed=84.5s

  [4132/15692] intraday_12847.csv.gz  in=259,154,219 out=45,405,579 elapsed=84.5s

  [4133/15692] intraday_12848.csv.gz  in=259,165,084 out=45,416,444 elapsed=84.5s

  [4134/15692] intraday_12849.csv.gz  in=259,177,504 out=45,428,864 elapsed=84.5s

  [4135/15692] intraday_1285.csv.gz  in=259,190,658 out=45,428,864 elapsed=84.5s

  [4136/15692] intraday_12850.csv.gz  in=259,201,123 out=45,439,329 elapsed=84.5s

  [4137/15692] intraday_12851.csv.gz  in=259,214,030 out=45,452,236 elapsed=84.6s

  [4138/15692] intraday_12852.csv.gz  in=259,228,361 out=45,466,567 elapsed=84.6s

  [4139/15692] intraday_12853.csv.gz  in=259,243,583 out=45,481,789 elapsed=84.6s

  [4140/15692] intraday_12854.csv.gz  in=259,256,746 out=45,494,952 elapsed=84.6s

  [4141/15692] intraday_12855.csv.gz  in=259,269,888 out=45,508,094 elapsed=84.6s

  [4142/15692] intraday_12856.csv.gz  in=259,282,057 out=45,520,263 elapsed=84.6s

  [4143/15692] intraday_12857.csv.gz  in=259,296,700 out=45,533,088 elapsed=84.6s

  [4144/15692] intraday_12859.csv.gz  in=259,310,043 out=45,546,431 elapsed=84.6s

  [4145/15692] intraday_12858.csv.gz  in=259,321,768 out=45,558,156 elapsed=84.6s

  [4146/15692] intraday_12860.csv.gz  in=259,331,209 out=45,567,597 elapsed=84.7s

  [4147/15692] intraday_12861.csv.gz  in=259,338,375 out=45,574,763 elapsed=84.7s

  [4148/15692] intraday_12862.csv.gz  in=259,352,201 out=45,588,589 elapsed=84.7s

  [4149/15692] intraday_1286.csv.gz  in=259,385,015 out=45,588,589 elapsed=84.7s

  [4150/15692] intraday_12863.csv.gz  in=259,391,221 out=45,594,795 elapsed=84.7s

  [4151/15692] intraday_12864.csv.gz  in=259,406,739 out=45,610,313 elapsed=84.7s

  [4152/15692] intraday_12866.csv.gz  in=259,418,703 out=45,622,277 elapsed=84.7s

  [4153/15692] intraday_12865.csv.gz  in=259,431,351 out=45,634,925 elapsed=84.7s

  [4154/15692] intraday_12867.csv.gz  in=259,442,388 out=45,645,962 elapsed=84.7s

  [4155/15692] intraday_12868.csv.gz  in=259,453,896 out=45,657,470 elapsed=84.8s

  [4156/15692] intraday_12869.csv.gz  in=259,467,152 out=45,670,726 elapsed=84.8s

  [4157/15692] intraday_1287.csv.gz  in=259,488,026 out=45,670,726 elapsed=84.8s

  [4158/15692] intraday_12870.csv.gz  in=259,500,776 out=45,683,476 elapsed=84.8s

  [4159/15692] intraday_12872.csv.gz  in=259,514,149 out=45,696,849 elapsed=84.8s

  [4160/15692] intraday_12873.csv.gz  in=259,527,928 out=45,710,628 elapsed=84.8s

  [4161/15692] intraday_12871.csv.gz  in=259,538,498 out=45,721,198 elapsed=84.8s

  [4162/15692] intraday_12874.csv.gz  in=259,550,059 out=45,732,759 elapsed=84.8s

  [4163/15692] intraday_12875.csv.gz  in=259,561,968 out=45,744,668 elapsed=84.9s

  [4164/15692] intraday_12877.csv.gz  in=259,575,200 out=45,757,900 elapsed=84.9s

  [4165/15692] intraday_12878.csv.gz  in=259,584,352 out=45,767,052 elapsed=84.9s

  [4166/15692] intraday_12876.csv.gz  in=259,620,048 out=45,795,061 elapsed=84.9s

  [4167/15692] intraday_12879.csv.gz  in=259,630,114 out=45,805,127 elapsed=84.9s

  [4168/15692] intraday_1288.csv.gz  in=259,643,396 out=45,805,127 elapsed=84.9s

  [4169/15692] intraday_12880.csv.gz  in=259,656,616 out=45,818,347 elapsed=84.9s

  [4170/15692] intraday_12882.csv.gz  in=259,666,331 out=45,828,062 elapsed=84.9s

  [4171/15692] intraday_12881.csv.gz  in=259,679,585 out=45,841,316 elapsed=84.9s

  [4172/15692] intraday_12884.csv.gz  in=259,690,622 out=45,852,353 elapsed=85.0s

  [4173/15692] intraday_12883.csv.gz  in=259,701,365 out=45,863,096 elapsed=85.0s

  [4174/15692] intraday_12885.csv.gz  in=259,713,372 out=45,875,103 elapsed=85.0s

  [4175/15692] intraday_12886.csv.gz  in=259,725,200 out=45,886,931 elapsed=85.0s

  [4176/15692] intraday_12887.csv.gz  in=259,736,750 out=45,898,481 elapsed=85.0s

  [4177/15692] intraday_12888.csv.gz  in=259,750,522 out=45,912,253 elapsed=85.0s

  [4178/15692] intraday_1289.csv.gz  in=259,764,839 out=45,912,253 elapsed=85.0s

  [4179/15692] intraday_12890.csv.gz  in=259,777,483 out=45,924,897 elapsed=85.1s

  [4180/15692] intraday_12889.csv.gz  in=259,796,089 out=45,940,953 elapsed=85.1s

  [4181/15692] intraday_12892.csv.gz  in=259,805,548 out=45,950,412 elapsed=85.1s

  [4182/15692] intraday_12891.csv.gz  in=259,818,027 out=45,962,891 elapsed=85.1s

  [4183/15692] intraday_12893.csv.gz  in=259,832,044 out=45,976,908 elapsed=85.1s

  [4184/15692] intraday_12894.csv.gz  in=259,846,077 out=45,990,941 elapsed=85.1s

  [4185/15692] intraday_12896.csv.gz  in=259,855,900 out=46,000,764 elapsed=85.1s

  [4186/15692] intraday_12897.csv.gz  in=259,868,641 out=46,013,505 elapsed=85.1s

  [4187/15692] intraday_12895.csv.gz  in=259,881,636 out=46,026,500 elapsed=85.1s

  [4188/15692] intraday_12898.csv.gz  in=259,893,287 out=46,038,151 elapsed=85.2s

  [4189/15692] intraday_12899.csv.gz  in=259,906,218 out=46,051,082 elapsed=85.2s

  [4190/15692] intraday_1290.csv.gz  in=259,920,160 out=46,051,082 elapsed=85.2s

  [4191/15692] intraday_12900.csv.gz  in=259,932,415 out=46,063,337 elapsed=85.2s

  [4192/15692] intraday_12901.csv.gz  in=259,943,786 out=46,074,708 elapsed=85.2s

  [4193/15692] intraday_12902.csv.gz  in=259,954,516 out=46,085,438 elapsed=85.2s

  [4194/15692] intraday_12903.csv.gz  in=259,964,186 out=46,095,108 elapsed=85.2s

  [4195/15692] intraday_12905.csv.gz  in=259,976,573 out=46,107,495 elapsed=85.2s

  [4196/15692] intraday_12906.csv.gz  in=259,988,285 out=46,119,207 elapsed=85.3s

  [4197/15692] intraday_12904.csv.gz  in=259,998,664 out=46,129,586 elapsed=85.3s

  [4198/15692] intraday_12907.csv.gz  in=260,011,024 out=46,141,946 elapsed=85.3s

  [4199/15692] intraday_12908.csv.gz  in=260,024,600 out=46,155,522 elapsed=85.3s

  [4200/15692] intraday_12909.csv.gz  in=260,035,234 out=46,166,156 elapsed=85.3s

  [4201/15692] intraday_12910.csv.gz  in=260,046,785 out=46,177,707 elapsed=85.3s

  [4202/15692] intraday_1291.csv.gz  in=260,066,281 out=46,177,707 elapsed=85.3s

  [4203/15692] intraday_12911.csv.gz  in=260,077,040 out=46,188,466 elapsed=85.3s

  [4204/15692] intraday_12912.csv.gz  in=260,089,446 out=46,200,872 elapsed=85.3s

  [4205/15692] intraday_12914.csv.gz  in=260,101,168 out=46,212,594 elapsed=85.4s

  [4206/15692] intraday_12913.csv.gz  in=260,111,486 out=46,222,912 elapsed=85.4s

  [4207/15692] intraday_12915.csv.gz  in=260,121,868 out=46,233,294 elapsed=85.4s

  [4208/15692] intraday_12916.csv.gz  in=260,135,294 out=46,246,720 elapsed=85.4s

  [4209/15692] intraday_12917.csv.gz  in=260,146,539 out=46,257,685 elapsed=85.4s

  [4210/15692] intraday_12918.csv.gz  in=260,158,966 out=46,270,112 elapsed=85.4s

  [4211/15692] intraday_12919.csv.gz  in=260,171,695 out=46,282,841 elapsed=85.4s

  [4212/15692] intraday_1292.csv.gz  in=260,181,686 out=46,282,841 elapsed=85.5s

  [4213/15692] intraday_12920.csv.gz  in=260,192,288 out=46,293,443 elapsed=85.5s

  [4214/15692] intraday_12921.csv.gz  in=260,203,011 out=46,304,166 elapsed=85.5s

  [4215/15692] intraday_12923.csv.gz  in=260,214,776 out=46,315,931 elapsed=85.5s

  [4216/15692] intraday_12922.csv.gz  in=260,225,556 out=46,326,711 elapsed=85.5s

  [4217/15692] intraday_12924.csv.gz  in=260,237,122 out=46,338,277 elapsed=85.5s

  [4218/15692] intraday_12925.csv.gz  in=260,248,970 out=46,350,125 elapsed=85.5s

  [4219/15692] intraday_12926.csv.gz  in=260,260,390 out=46,361,545 elapsed=85.5s

  [4220/15692] intraday_12927.csv.gz  in=260,272,294 out=46,373,449 elapsed=85.6s

  [4221/15692] intraday_12928.csv.gz  in=260,281,230 out=46,382,385 elapsed=85.6s

  [4222/15692] intraday_1293.csv.gz  in=260,293,324 out=46,382,385 elapsed=85.6s

  [4223/15692] intraday_12929.csv.gz  in=260,305,936 out=46,394,997 elapsed=85.6s

  [4224/15692] intraday_12930.csv.gz  in=260,319,540 out=46,408,601 elapsed=85.6s

  [4225/15692] intraday_12932.csv.gz  in=260,332,515 out=46,421,576 elapsed=85.6s

  [4226/15692] intraday_12931.csv.gz  in=260,344,310 out=46,433,371 elapsed=85.6s

  [4227/15692] intraday_12933.csv.gz  in=260,355,849 out=46,444,910 elapsed=85.6s

  [4228/15692] intraday_12934.csv.gz  in=260,365,070 out=46,454,131 elapsed=85.6s

  [4229/15692] intraday_12935.csv.gz  in=260,377,042 out=46,466,103 elapsed=85.7s

  [4230/15692] intraday_12936.csv.gz  in=260,389,066 out=46,478,127 elapsed=85.7s

  [4231/15692] intraday_12937.csv.gz  in=260,400,977 out=46,490,038 elapsed=85.7s

  [4232/15692] intraday_12938.csv.gz  in=260,413,306 out=46,502,367 elapsed=85.7s

  [4233/15692] intraday_1294.csv.gz  in=260,425,746 out=46,502,367 elapsed=85.7s

  [4234/15692] intraday_12939.csv.gz  in=260,437,723 out=46,514,344 elapsed=85.7s

  [4235/15692] intraday_12940.csv.gz  in=260,447,053 out=46,523,674 elapsed=85.8s

  [4236/15692] intraday_12941.csv.gz  in=260,458,303 out=46,534,924 elapsed=85.8s

  [4237/15692] intraday_12942.csv.gz  in=260,472,760 out=46,549,381 elapsed=85.8s

  [4238/15692] intraday_12943.csv.gz  in=260,484,666 out=46,561,287 elapsed=85.8s

  [4239/15692] intraday_12944.csv.gz  in=260,495,937 out=46,572,558 elapsed=85.8s

  [4240/15692] intraday_12945.csv.gz  in=260,505,703 out=46,582,324 elapsed=85.8s

  [4241/15692] intraday_12946.csv.gz  in=260,516,376 out=46,592,997 elapsed=85.8s

  [4242/15692] intraday_12947.csv.gz  in=260,528,527 out=46,605,148 elapsed=85.9s

  [4243/15692] intraday_12948.csv.gz  in=260,541,405 out=46,618,026 elapsed=85.9s

  [4244/15692] intraday_12949.csv.gz  in=260,556,023 out=46,632,644 elapsed=85.9s

  [4245/15692] intraday_1295.csv.gz  in=260,568,480 out=46,632,644 elapsed=85.9s

  [4246/15692] intraday_12951.csv.gz  in=260,580,124 out=46,644,288 elapsed=85.9s

  [4247/15692] intraday_12950.csv.gz  in=260,594,657 out=46,658,821 elapsed=85.9s

  [4248/15692] intraday_12952.csv.gz  in=260,606,129 out=46,670,293 elapsed=85.9s

  [4249/15692] intraday_12953.csv.gz  in=260,617,172 out=46,681,336 elapsed=86.0s

  [4250/15692] intraday_12954.csv.gz  in=260,631,088 out=46,695,252 elapsed=86.0s

  [4251/15692] intraday_12956.csv.gz  in=260,641,493 out=46,705,657 elapsed=86.0s

  [4252/15692] intraday_12955.csv.gz  in=260,653,424 out=46,717,588 elapsed=86.0s

  [4253/15692] intraday_12958.csv.gz  in=260,664,487 out=46,728,651 elapsed=86.0s

  [4254/15692] intraday_12957.csv.gz  in=260,680,228 out=46,744,392 elapsed=86.1s

  [4255/15692] intraday_1296.csv.gz  in=260,697,066 out=46,744,392 elapsed=86.1s

  [4256/15692] intraday_12959.csv.gz  in=260,709,228 out=46,756,554 elapsed=86.1s

  [4257/15692] intraday_12960.csv.gz  in=260,721,439 out=46,768,765 elapsed=86.1s

  [4258/15692] intraday_12961.csv.gz  in=260,733,291 out=46,780,617 elapsed=86.1s

  [4259/15692] intraday_12963.csv.gz  in=260,745,103 out=46,792,429 elapsed=86.1s

  [4260/15692] intraday_12962.csv.gz  in=260,756,922 out=46,804,248 elapsed=86.1s

  [4261/15692] intraday_12964.csv.gz  in=260,767,234 out=46,814,560 elapsed=86.1s

  [4262/15692] intraday_12965.csv.gz  in=260,778,194 out=46,825,520 elapsed=86.1s

  [4263/15692] intraday_12966.csv.gz  in=260,790,812 out=46,838,138 elapsed=86.2s

  [4264/15692] intraday_12967.csv.gz  in=260,802,642 out=46,849,968 elapsed=86.2s

  [4265/15692] intraday_12968.csv.gz  in=260,813,730 out=46,861,056 elapsed=86.2s

  [4266/15692] intraday_12969.csv.gz  in=260,827,659 out=46,874,985 elapsed=86.2s

  [4267/15692] intraday_1297.csv.gz  in=260,848,514 out=46,874,985 elapsed=86.2s

  [4268/15692] intraday_12971.csv.gz  in=260,863,791 out=46,890,262 elapsed=86.2s

  [4269/15692] intraday_12970.csv.gz  in=260,875,435 out=46,901,906 elapsed=86.2s

  [4270/15692] intraday_12972.csv.gz  in=260,885,759 out=46,912,230 elapsed=86.2s

  [4271/15692] intraday_12974.csv.gz  in=260,899,861 out=46,926,332 elapsed=86.3s

  [4272/15692] intraday_12975.csv.gz  in=260,914,112 out=46,940,583 elapsed=86.3s

  [4273/15692] intraday_12976.csv.gz  in=260,924,634 out=46,951,105 elapsed=86.3s

  [4274/15692] intraday_12977.csv.gz  in=260,937,307 out=46,963,778 elapsed=86.3s

  [4275/15692] intraday_12973.csv.gz  in=260,954,017 out=46,978,750 elapsed=86.3s

  [4276/15692] intraday_12978.csv.gz  in=260,967,994 out=46,992,727 elapsed=86.3s

  [4277/15692] intraday_12979.csv.gz  in=260,982,068 out=47,006,801 elapsed=86.3s

  [4278/15692] intraday_1298.csv.gz  in=261,000,957 out=47,006,801 elapsed=86.3s

  [4279/15692] intraday_12980.csv.gz  in=261,013,580 out=47,019,424 elapsed=86.4s

  [4280/15692] intraday_12981.csv.gz  in=261,027,760 out=47,033,604 elapsed=86.4s

  [4281/15692] intraday_12983.csv.gz  in=261,039,687 out=47,045,531 elapsed=86.4s

  [4282/15692] intraday_12982.csv.gz  in=261,058,048 out=47,063,892 elapsed=86.4s

  [4283/15692] intraday_12984.csv.gz  in=261,073,462 out=47,079,306 elapsed=86.4s

  [4284/15692] intraday_12985.csv.gz  in=261,083,343 out=47,089,187 elapsed=86.4s

  [4285/15692] intraday_12986.csv.gz  in=261,096,897 out=47,102,741 elapsed=86.4s

  [4286/15692] intraday_12987.csv.gz  in=261,108,927 out=47,114,771 elapsed=86.4s

  [4287/15692] intraday_12989.csv.gz  in=261,119,722 out=47,125,566 elapsed=86.5s

  [4288/15692] intraday_12988.csv.gz  in=261,132,229 out=47,138,073 elapsed=86.5s

  [4289/15692] intraday_1299.csv.gz  in=261,146,837 out=47,138,073 elapsed=86.5s

  [4290/15692] intraday_12990.csv.gz  in=261,158,490 out=47,149,726 elapsed=86.5s

  [4291/15692] intraday_12991.csv.gz  in=261,170,068 out=47,161,304 elapsed=86.5s

  [4292/15692] intraday_12993.csv.gz  in=261,181,753 out=47,172,989 elapsed=86.5s

  [4293/15692] intraday_12992.csv.gz  in=261,194,811 out=47,186,047 elapsed=86.5s

  [4294/15692] intraday_12994.csv.gz  in=261,207,182 out=47,198,418 elapsed=86.5s

  [4295/15692] intraday_12995.csv.gz  in=261,217,194 out=47,208,430 elapsed=86.5s

  [4296/15692] intraday_12996.csv.gz  in=261,230,745 out=47,221,981 elapsed=86.6s

  [4297/15692] intraday_12997.csv.gz  in=261,240,907 out=47,232,143 elapsed=86.6s

  [4298/15692] intraday_12999.csv.gz  in=261,254,746 out=47,245,982 elapsed=86.6s

  [4299/15692] intraday_1300.csv.gz  in=261,267,255 out=47,245,982 elapsed=86.6s

  [4300/15692] intraday_12998.csv.gz  in=261,280,408 out=47,259,135 elapsed=86.6s

  [4301/15692] intraday_13000.csv.gz  in=261,294,911 out=47,273,638 elapsed=86.6s

  [4302/15692] intraday_13001.csv.gz  in=261,308,454 out=47,287,181 elapsed=86.6s

  [4303/15692] intraday_13002.csv.gz  in=261,321,789 out=47,300,516 elapsed=86.6s

  [4304/15692] intraday_13003.csv.gz  in=261,333,142 out=47,311,869 elapsed=86.6s

  [4305/15692] intraday_13004.csv.gz  in=261,345,560 out=47,324,287 elapsed=86.6s

  [4306/15692] intraday_13005.csv.gz  in=261,356,562 out=47,335,289 elapsed=86.6s

  [4307/15692] intraday_13006.csv.gz  in=261,369,897 out=47,348,624 elapsed=86.7s

  [4308/15692] intraday_13007.csv.gz  in=261,378,627 out=47,357,354 elapsed=86.7s

  [4309/15692] intraday_13008.csv.gz  in=261,386,264 out=47,364,991 elapsed=86.7s

  [4310/15692] intraday_1301.csv.gz  in=261,398,764 out=47,364,991 elapsed=86.7s

  [4311/15692] intraday_13009.csv.gz  in=261,412,513 out=47,378,740 elapsed=86.7s

  [4312/15692] intraday_13010.csv.gz  in=261,416,387 out=47,382,614 elapsed=86.7s

  [4313/15692] intraday_13011.csv.gz  in=261,417,107 out=47,383,069 elapsed=86.7s

  [4314/15692] intraday_13012.csv.gz  in=261,434,467 out=47,400,429 elapsed=86.7s

  [4315/15692] intraday_13013.csv.gz  in=261,447,500 out=47,413,462 elapsed=86.8s

  [4316/15692] intraday_13015.csv.gz  in=261,458,017 out=47,423,979 elapsed=86.8s

  [4317/15692] intraday_13014.csv.gz  in=261,470,746 out=47,436,708 elapsed=86.8s

  [4318/15692] intraday_13017.csv.gz  in=261,485,320 out=47,451,282 elapsed=86.8s

  [4319/15692] intraday_13016.csv.gz  in=261,498,074 out=47,464,036 elapsed=86.8s

  [4320/15692] intraday_13019.csv.gz  in=261,510,127 out=47,476,089 elapsed=86.8s

  [4321/15692] intraday_1302.csv.gz  in=261,523,374 out=47,476,089 elapsed=86.8s

  [4322/15692] intraday_13018.csv.gz  in=261,536,197 out=47,488,912 elapsed=86.9s

  [4323/15692] intraday_13020.csv.gz  in=261,550,136 out=47,502,851 elapsed=86.9s

  [4324/15692] intraday_13021.csv.gz  in=261,562,768 out=47,515,483 elapsed=86.9s

  [4325/15692] intraday_13022.csv.gz  in=261,575,903 out=47,528,618 elapsed=86.9s

  [4326/15692] intraday_13023.csv.gz  in=261,588,152 out=47,540,867 elapsed=86.9s

  [4327/15692] intraday_13024.csv.gz  in=261,602,772 out=47,555,487 elapsed=86.9s

  [4328/15692] intraday_13026.csv.gz  in=261,612,558 out=47,565,273 elapsed=87.0s

  [4329/15692] intraday_13025.csv.gz  in=261,625,781 out=47,578,496 elapsed=87.0s

  [4330/15692] intraday_13028.csv.gz  in=261,639,604 out=47,592,319 elapsed=87.0s

  [4331/15692] intraday_13027.csv.gz  in=261,649,646 out=47,602,361 elapsed=87.0s

  [4332/15692] intraday_1303.csv.gz  in=261,662,314 out=47,602,361 elapsed=87.0s

  [4333/15692] intraday_13029.csv.gz  in=261,676,137 out=47,616,184 elapsed=87.0s

  [4334/15692] intraday_13030.csv.gz  in=261,686,113 out=47,626,160 elapsed=87.0s

  [4335/15692] intraday_13031.csv.gz  in=261,696,615 out=47,636,662 elapsed=87.0s

  [4336/15692] intraday_13032.csv.gz  in=261,708,570 out=47,648,617 elapsed=87.1s

  [4337/15692] intraday_13033.csv.gz  in=261,720,496 out=47,660,543 elapsed=87.1s

  [4338/15692] intraday_13034.csv.gz  in=261,733,379 out=47,673,426 elapsed=87.1s

  [4339/15692] intraday_13035.csv.gz  in=261,745,952 out=47,685,999 elapsed=87.1s

  [4340/15692] intraday_13037.csv.gz  in=261,757,448 out=47,697,111 elapsed=87.1s

  [4341/15692] intraday_13036.csv.gz  in=261,772,036 out=47,711,699 elapsed=87.1s

  [4342/15692] intraday_13038.csv.gz  in=261,784,270 out=47,723,933 elapsed=87.1s

  [4343/15692] intraday_13039.csv.gz  in=261,796,921 out=47,736,584 elapsed=87.1s

  [4344/15692] intraday_1304.csv.gz  in=261,808,095 out=47,736,584 elapsed=87.1s

  [4345/15692] intraday_13040.csv.gz  in=261,819,577 out=47,748,066 elapsed=87.2s

  [4346/15692] intraday_13041.csv.gz  in=261,832,243 out=47,760,732 elapsed=87.2s

  [4347/15692] intraday_13043.csv.gz  in=261,845,983 out=47,774,472 elapsed=87.2s

  [4348/15692] intraday_13044.csv.gz  in=261,856,517 out=47,785,006 elapsed=87.2s

  [4349/15692] intraday_13045.csv.gz  in=261,868,229 out=47,796,718 elapsed=87.2s

  [4350/15692] intraday_13042.csv.gz  in=261,885,010 out=47,813,499 elapsed=87.2s

  [4351/15692] intraday_13047.csv.gz  in=261,898,501 out=47,826,990 elapsed=87.3s

  [4352/15692] intraday_13046.csv.gz  in=261,911,013 out=47,839,502 elapsed=87.3s

  [4353/15692] intraday_13048.csv.gz  in=261,923,476 out=47,851,965 elapsed=87.3s

  [4354/15692] intraday_13049.csv.gz  in=261,934,855 out=47,863,344 elapsed=87.3s

  [4355/15692] intraday_1305.csv.gz  in=261,946,629 out=47,863,344 elapsed=87.3s

  [4356/15692] intraday_13050.csv.gz  in=261,958,234 out=47,874,949 elapsed=87.3s

  [4357/15692] intraday_13051.csv.gz  in=261,967,429 out=47,884,144 elapsed=87.3s

  [4358/15692] intraday_13052.csv.gz  in=261,978,392 out=47,895,107 elapsed=87.3s

  [4359/15692] intraday_13053.csv.gz  in=261,991,258 out=47,907,973 elapsed=87.3s

  [4360/15692] intraday_13054.csv.gz  in=262,004,637 out=47,921,352 elapsed=87.4s

  [4361/15692] intraday_13055.csv.gz  in=262,016,856 out=47,933,571 elapsed=87.4s

  [4362/15692] intraday_13057.csv.gz  in=262,027,225 out=47,943,940 elapsed=87.4s

  [4363/15692] intraday_13056.csv.gz  in=262,041,643 out=47,958,358 elapsed=87.4s

  [4364/15692] intraday_13058.csv.gz  in=262,053,723 out=47,970,438 elapsed=87.4s

  [4365/15692] intraday_1306.csv.gz  in=262,065,582 out=47,970,438 elapsed=87.4s

  [4366/15692] intraday_13059.csv.gz  in=262,078,384 out=47,983,240 elapsed=87.4s

  [4367/15692] intraday_13060.csv.gz  in=262,088,724 out=47,993,580 elapsed=87.4s

  [4368/15692] intraday_13061.csv.gz  in=262,100,563 out=48,005,419 elapsed=87.4s

  [4369/15692] intraday_13062.csv.gz  in=262,111,136 out=48,015,992 elapsed=87.5s

  [4370/15692] intraday_13063.csv.gz  in=262,123,383 out=48,028,239 elapsed=87.5s

  [4371/15692] intraday_13064.csv.gz  in=262,137,844 out=48,042,700 elapsed=87.5s

  [4372/15692] intraday_13065.csv.gz  in=262,149,541 out=48,054,397 elapsed=87.5s

  [4373/15692] intraday_13066.csv.gz  in=262,162,828 out=48,067,684 elapsed=87.5s

  [4374/15692] intraday_13067.csv.gz  in=262,174,956 out=48,079,812 elapsed=87.5s

  [4375/15692] intraday_13068.csv.gz  in=262,187,111 out=48,091,967 elapsed=87.5s

  [4376/15692] intraday_13069.csv.gz  in=262,199,258 out=48,104,114 elapsed=87.5s

  [4377/15692] intraday_1307.csv.gz  in=262,211,373 out=48,104,114 elapsed=87.6s

  [4378/15692] intraday_13070.csv.gz  in=262,223,976 out=48,116,717 elapsed=87.6s

  [4379/15692] intraday_13072.csv.gz  in=262,238,717 out=48,131,458 elapsed=87.6s

  [4380/15692] intraday_13071.csv.gz  in=262,250,354 out=48,143,095 elapsed=87.6s

  [4381/15692] intraday_13073.csv.gz  in=262,264,107 out=48,156,848 elapsed=87.6s

  [4382/15692] intraday_13074.csv.gz  in=262,281,465 out=48,172,604 elapsed=87.6s

  [4383/15692] intraday_13076.csv.gz  in=262,293,087 out=48,184,226 elapsed=87.6s

  [4384/15692] intraday_13075.csv.gz  in=262,304,074 out=48,195,213 elapsed=87.7s

  [4385/15692] intraday_13078.csv.gz  in=262,316,109 out=48,207,248 elapsed=87.7s

  [4386/15692] intraday_1308.csv.gz  in=262,327,994 out=48,207,248 elapsed=87.7s

  [4387/15692] intraday_13079.csv.gz  in=262,341,827 out=48,221,081 elapsed=87.7s

  [4388/15692] intraday_13077.csv.gz  in=262,357,994 out=48,237,248 elapsed=87.7s

  [4389/15692] intraday_13080.csv.gz  in=262,370,475 out=48,249,729 elapsed=87.7s

  [4390/15692] intraday_13081.csv.gz  in=262,381,624 out=48,260,878 elapsed=87.7s

  [4391/15692] intraday_13082.csv.gz  in=262,391,038 out=48,270,292 elapsed=87.7s

  [4392/15692] intraday_13083.csv.gz  in=262,404,125 out=48,283,379 elapsed=87.8s

  [4393/15692] intraday_13084.csv.gz  in=262,417,650 out=48,296,904 elapsed=87.8s

  [4394/15692] intraday_13085.csv.gz  in=262,431,047 out=48,310,301 elapsed=87.8s

  [4395/15692] intraday_13086.csv.gz  in=262,441,825 out=48,321,079 elapsed=87.8s

  [4396/15692] intraday_1309.csv.gz  in=262,452,557 out=48,321,079 elapsed=87.8s

  [4397/15692] intraday_13087.csv.gz  in=262,465,539 out=48,334,061 elapsed=87.8s

  [4398/15692] intraday_13088.csv.gz  in=262,475,445 out=48,343,967 elapsed=87.9s

  [4399/15692] intraday_13089.csv.gz  in=262,491,015 out=48,359,537 elapsed=87.9s

  [4400/15692] intraday_13090.csv.gz  in=262,503,733 out=48,372,255 elapsed=87.9s

  [4401/15692] intraday_13091.csv.gz  in=262,514,634 out=48,383,156 elapsed=87.9s

  [4402/15692] intraday_13092.csv.gz  in=262,526,172 out=48,394,694 elapsed=87.9s

  [4403/15692] intraday_13093.csv.gz  in=262,537,161 out=48,405,683 elapsed=87.9s

  [4404/15692] intraday_13095.csv.gz  in=262,549,052 out=48,417,574 elapsed=87.9s

  [4405/15692] intraday_13094.csv.gz  in=262,561,064 out=48,429,586 elapsed=87.9s

  [4406/15692] intraday_13096.csv.gz  in=262,579,590 out=48,448,112 elapsed=88.0s

  [4407/15692] intraday_13097.csv.gz  in=262,595,150 out=48,463,672 elapsed=88.0s

  [4408/15692] intraday_13099.csv.gz  in=262,606,247 out=48,474,769 elapsed=88.0s

  [4409/15692] intraday_13098.csv.gz  in=262,617,714 out=48,486,236 elapsed=88.0s

  [4410/15692] intraday_1310.csv.gz  in=262,629,361 out=48,486,236 elapsed=88.0s

  [4411/15692] intraday_13100.csv.gz  in=262,642,507 out=48,499,382 elapsed=88.0s

  [4412/15692] intraday_13101.csv.gz  in=262,653,898 out=48,510,773 elapsed=88.0s

  [4413/15692] intraday_13102.csv.gz  in=262,669,456 out=48,526,331 elapsed=88.1s

  [4414/15692] intraday_13103.csv.gz  in=262,680,304 out=48,537,179 elapsed=88.1s

  [4415/15692] intraday_13104.csv.gz  in=262,693,759 out=48,550,634 elapsed=88.1s

  [4416/15692] intraday_13105.csv.gz  in=262,707,210 out=48,564,085 elapsed=88.1s

  [4417/15692] intraday_13107.csv.gz  in=262,719,641 out=48,576,516 elapsed=88.1s

  [4418/15692] intraday_13106.csv.gz  in=262,732,869 out=48,589,744 elapsed=88.1s

  [4419/15692] intraday_13108.csv.gz  in=262,745,201 out=48,602,076 elapsed=88.2s

  [4420/15692] intraday_13109.csv.gz  in=262,758,063 out=48,614,938 elapsed=88.2s

  [4421/15692] intraday_1311.csv.gz  in=262,769,513 out=48,614,938 elapsed=88.2s

  [4422/15692] intraday_13110.csv.gz  in=262,781,766 out=48,627,191 elapsed=88.2s

  [4423/15692] intraday_13111.csv.gz  in=262,794,405 out=48,639,830 elapsed=88.2s

  [4424/15692] intraday_13112.csv.gz  in=262,807,328 out=48,652,753 elapsed=88.2s

  [4425/15692] intraday_13113.csv.gz  in=262,818,992 out=48,664,417 elapsed=88.2s

  [4426/15692] intraday_13114.csv.gz  in=262,830,972 out=48,676,397 elapsed=88.2s

  [4427/15692] intraday_13115.csv.gz  in=262,844,712 out=48,690,137 elapsed=88.3s

  [4428/15692] intraday_13116.csv.gz  in=262,857,171 out=48,702,596 elapsed=88.3s

  [4429/15692] intraday_13117.csv.gz  in=262,872,145 out=48,717,570 elapsed=88.3s

  [4430/15692] intraday_13118.csv.gz  in=262,884,677 out=48,730,102 elapsed=88.3s

  [4431/15692] intraday_13119.csv.gz  in=262,899,488 out=48,744,913 elapsed=88.3s

  [4432/15692] intraday_1312.csv.gz  in=262,916,732 out=48,744,913 elapsed=88.3s

  [4433/15692] intraday_13120.csv.gz  in=262,928,367 out=48,756,548 elapsed=88.3s

  [4434/15692] intraday_13121.csv.gz  in=262,941,495 out=48,769,676 elapsed=88.3s

  [4435/15692] intraday_13122.csv.gz  in=262,954,329 out=48,782,510 elapsed=88.4s

  [4436/15692] intraday_13123.csv.gz  in=262,967,992 out=48,796,173 elapsed=88.4s

  [4437/15692] intraday_13124.csv.gz  in=262,978,862 out=48,807,043 elapsed=88.4s

  [4438/15692] intraday_13125.csv.gz  in=262,993,555 out=48,821,736 elapsed=88.4s

  [4439/15692] intraday_13128.csv.gz  in=263,009,461 out=48,837,642 elapsed=88.4s

  [4440/15692] intraday_13129.csv.gz  in=263,027,726 out=48,855,907 elapsed=88.4s

  [4441/15692] intraday_1313.csv.gz  in=263,039,022 out=48,855,907 elapsed=88.4s

  [4442/15692] intraday_13127.csv.gz  in=263,053,599 out=48,870,484 elapsed=88.4s

  [4443/15692] intraday_13126.csv.gz  in=263,069,143 out=48,886,028 elapsed=88.4s

  [4444/15692] intraday_13130.csv.gz  in=263,084,829 out=48,901,714 elapsed=88.5s

  [4445/15692] intraday_13131.csv.gz  in=263,100,743 out=48,917,628 elapsed=88.5s

  [4446/15692] intraday_13132.csv.gz  in=263,115,252 out=48,932,137 elapsed=88.5s

  [4447/15692] intraday_13133.csv.gz  in=263,127,694 out=48,944,579 elapsed=88.5s

  [4448/15692] intraday_13134.csv.gz  in=263,139,276 out=48,956,161 elapsed=88.5s

  [4449/15692] intraday_13136.csv.gz  in=263,152,280 out=48,969,165 elapsed=88.5s

  [4450/15692] intraday_13135.csv.gz  in=263,163,512 out=48,980,397 elapsed=88.5s

  [4451/15692] intraday_13138.csv.gz  in=263,175,908 out=48,992,793 elapsed=88.5s

  [4452/15692] intraday_13137.csv.gz  in=263,186,761 out=49,003,646 elapsed=88.5s

  [4453/15692] intraday_1314.csv.gz  in=263,196,308 out=49,003,646 elapsed=88.6s

  [4454/15692] intraday_13139.csv.gz  in=263,209,179 out=49,016,517 elapsed=88.6s

  [4455/15692] intraday_13141.csv.gz  in=263,219,762 out=49,027,100 elapsed=88.6s

  [4456/15692] intraday_13140.csv.gz  in=263,238,727 out=49,044,890 elapsed=88.6s

  [4457/15692] intraday_13142.csv.gz  in=263,250,351 out=49,056,514 elapsed=88.6s

  [4458/15692] intraday_13144.csv.gz  in=263,261,968 out=49,068,131 elapsed=88.6s

  [4459/15692] intraday_13143.csv.gz  in=263,274,462 out=49,080,625 elapsed=88.6s

  [4460/15692] intraday_13146.csv.gz  in=263,289,142 out=49,095,305 elapsed=88.7s

  [4461/15692] intraday_13145.csv.gz  in=263,302,326 out=49,108,489 elapsed=88.7s

  [4462/15692] intraday_13148.csv.gz  in=263,316,233 out=49,122,396 elapsed=88.7s

  [4463/15692] intraday_13147.csv.gz  in=263,331,805 out=49,137,968 elapsed=88.7s

  [4464/15692] intraday_1315.csv.gz  in=263,343,664 out=49,137,968 elapsed=88.7s

  [4465/15692] intraday_13149.csv.gz  in=263,357,792 out=49,152,096 elapsed=88.7s

  [4466/15692] intraday_13151.csv.gz  in=263,370,582 out=49,164,886 elapsed=88.7s

  [4467/15692] intraday_13150.csv.gz  in=263,383,016 out=49,177,320 elapsed=88.7s

  [4468/15692] intraday_13152.csv.gz  in=263,396,612 out=49,190,916 elapsed=88.7s

  [4469/15692] intraday_13154.csv.gz  in=263,405,909 out=49,200,213 elapsed=88.8s

  [4470/15692] intraday_13155.csv.gz  in=263,413,892 out=49,208,196 elapsed=88.8s

  [4471/15692] intraday_13156.csv.gz  in=263,429,315 out=49,223,619 elapsed=88.8s

  [4472/15692] intraday_13153.csv.gz  in=263,466,369 out=49,252,797 elapsed=88.8s

  [4473/15692] intraday_13157.csv.gz  in=263,471,788 out=49,258,216 elapsed=88.8s

  [4474/15692] intraday_1316.csv.gz  in=263,484,666 out=49,258,216 elapsed=88.8s

  [4475/15692] intraday_13159.csv.gz  in=263,523,611 out=49,297,161 elapsed=88.9s

  [4476/15692] intraday_13161.csv.gz  in=263,534,569 out=49,308,119 elapsed=88.9s

  [4477/15692] intraday_13162.csv.gz  in=263,540,627 out=49,314,177 elapsed=88.9s

  [4478/15692] intraday_13160.csv.gz  in=263,572,988 out=49,346,538 elapsed=89.0s

  [4479/15692] intraday_13158.csv.gz  in=263,621,166 out=49,394,716 elapsed=89.0s

  [4480/15692] intraday_13163.csv.gz  in=263,662,721 out=49,436,131 elapsed=89.0s

  [4481/15692] intraday_13165.csv.gz  in=263,696,432 out=49,469,842 elapsed=89.0s

  [4482/15692] intraday_13166.csv.gz  in=263,730,156 out=49,503,566 elapsed=89.1s

  [4483/15692] intraday_13164.csv.gz  in=263,770,469 out=49,543,879 elapsed=89.1s

  [4484/15692] intraday_13167.csv.gz  in=263,808,723 out=49,582,133 elapsed=89.1s

  [4485/15692] intraday_13168.csv.gz  in=263,850,320 out=49,623,730 elapsed=89.1s

  [4486/15692] intraday_1317.csv.gz  in=263,865,336 out=49,623,730 elapsed=89.1s

  [4487/15692] intraday_13169.csv.gz  in=263,882,815 out=49,641,209 elapsed=89.1s

  [4488/15692] intraday_13170.csv.gz  in=263,901,074 out=49,659,468 elapsed=89.2s

  [4489/15692] intraday_13172.csv.gz  in=263,934,883 out=49,693,277 elapsed=89.2s

  [4490/15692] intraday_13173.csv.gz  in=263,972,335 out=49,730,729 elapsed=89.3s

  [4491/15692] intraday_13171.csv.gz  in=264,016,817 out=49,772,089 elapsed=89.3s

  [4492/15692] intraday_13175.csv.gz  in=264,053,132 out=49,808,404 elapsed=89.3s

  [4493/15692] intraday_13174.csv.gz  in=264,091,109 out=49,846,381 elapsed=89.3s

  [4494/15692] intraday_13177.csv.gz  in=264,122,794 out=49,878,066 elapsed=89.3s

  [4495/15692] intraday_1318.csv.gz  in=264,136,788 out=49,878,066 elapsed=89.3s

  [4496/15692] intraday_13178.csv.gz  in=264,165,424 out=49,906,702 elapsed=89.4s

  [4497/15692] intraday_13176.csv.gz  in=264,213,214 out=49,953,092 elapsed=89.4s

  [4498/15692] intraday_13179.csv.gz  in=264,241,715 out=49,981,593 elapsed=89.4s

  [4499/15692] intraday_13180.csv.gz  in=264,283,791 out=50,023,669 elapsed=89.4s

  [4500/15692] intraday_13181.csv.gz  in=264,315,909 out=50,055,787 elapsed=89.5s

  [4501/15692] intraday_13183.csv.gz  in=264,351,541 out=50,091,419 elapsed=89.5s

  [4502/15692] intraday_13184.csv.gz  in=264,395,391 out=50,132,381 elapsed=89.5s

  [4503/15692] intraday_13186.csv.gz  in=264,397,352 out=50,134,342 elapsed=89.5s

  [4504/15692] intraday_13182.csv.gz  in=264,432,087 out=50,169,077 elapsed=89.5s

  [4505/15692] intraday_13187.csv.gz  in=264,461,542 out=50,198,532 elapsed=89.5s

  [4506/15692] intraday_13185.csv.gz  in=264,492,548 out=50,229,538 elapsed=89.5s

  [4507/15692] intraday_1319.csv.gz  in=264,505,437 out=50,229,538 elapsed=89.6s

  [4508/15692] intraday_13188.csv.gz  in=264,542,427 out=50,266,528 elapsed=89.6s

  [4509/15692] intraday_13189.csv.gz  in=264,577,925 out=50,302,026 elapsed=89.6s

  [4510/15692] intraday_13190.csv.gz  in=264,619,028 out=50,341,514 elapsed=89.7s

  [4511/15692] intraday_13192.csv.gz  in=264,651,702 out=50,374,188 elapsed=89.7s

  [4512/15692] intraday_13191.csv.gz  in=264,692,980 out=50,415,466 elapsed=89.7s

  [4513/15692] intraday_13193.csv.gz  in=264,731,246 out=50,453,732 elapsed=89.7s

  [4514/15692] intraday_13195.csv.gz  in=264,739,768 out=50,462,254 elapsed=89.7s

  [4515/15692] intraday_13197.csv.gz  in=264,774,078 out=50,496,564 elapsed=89.7s

  [4516/15692] intraday_13198.csv.gz  in=264,813,001 out=50,535,487 elapsed=89.8s

  [4517/15692] intraday_13194.csv.gz  in=264,850,517 out=50,573,003 elapsed=89.8s

  [4518/15692] intraday_13196.csv.gz  in=264,891,077 out=50,613,563 elapsed=89.8s

  [4519/15692] intraday_13199.csv.gz  in=264,927,203 out=50,648,451 elapsed=89.8s

  [4520/15692] intraday_1320.csv.gz  in=264,940,398 out=50,648,451 elapsed=89.8s

  [4521/15692] intraday_13203.csv.gz  in=264,950,646 out=50,658,699 elapsed=89.8s

  [4522/15692] intraday_13200.csv.gz  in=264,987,806 out=50,695,859 elapsed=89.9s

  [4523/15692] intraday_13204.csv.gz  in=264,999,384 out=50,707,437 elapsed=89.9s

  [4524/15692] intraday_13201.csv.gz  in=265,032,392 out=50,740,445 elapsed=89.9s

  [4525/15692] intraday_13202.csv.gz  in=265,069,662 out=50,777,715 elapsed=89.9s

  [4526/15692] intraday_13205.csv.gz  in=265,099,956 out=50,807,984 elapsed=90.0s

  [4527/15692] intraday_13206.csv.gz  in=265,128,063 out=50,836,091 elapsed=90.0s

  [4528/15692] intraday_1321.csv.gz  in=265,141,935 out=50,836,091 elapsed=90.1s

  [4529/15692] intraday_13207.csv.gz  in=265,184,265 out=50,878,421 elapsed=90.1s

  [4530/15692] intraday_13209.csv.gz  in=265,222,614 out=50,916,770 elapsed=90.1s

  [4531/15692] intraday_13208.csv.gz  in=265,264,231 out=50,958,286 elapsed=90.1s

  [4532/15692] intraday_13213.csv.gz  in=265,279,103 out=50,973,158 elapsed=90.1s

  [4533/15692] intraday_13212.csv.gz  in=265,288,773 out=50,982,828 elapsed=90.1s

  [4534/15692] intraday_13211.csv.gz  in=265,325,155 out=51,019,210 elapsed=90.1s

  [4535/15692] intraday_13210.csv.gz  in=265,361,900 out=51,055,310 elapsed=90.1s

  [4536/15692] intraday_13214.csv.gz  in=265,398,637 out=51,092,047 elapsed=90.2s

  [4537/15692] intraday_13215.csv.gz  in=265,437,314 out=51,130,724 elapsed=90.2s

  [4538/15692] intraday_13216.csv.gz  in=265,464,037 out=51,157,447 elapsed=90.2s

  [4539/15692] intraday_13217.csv.gz  in=265,504,220 out=51,197,630 elapsed=90.2s

  [4540/15692] intraday_1322.csv.gz  in=265,517,759 out=51,197,630 elapsed=90.2s

  [4541/15692] intraday_13218.csv.gz  in=265,555,718 out=51,235,589 elapsed=90.2s

  [4542/15692] intraday_13219.csv.gz  in=265,588,793 out=51,268,664 elapsed=90.3s

  [4543/15692] intraday_13222.csv.gz  in=265,616,240 out=51,296,111 elapsed=90.3s

  [4544/15692] intraday_13220.csv.gz  in=265,650,401 out=51,330,272 elapsed=90.3s

  [4545/15692] intraday_13221.csv.gz  in=265,675,339 out=51,355,210 elapsed=90.3s

  [4546/15692] intraday_13223.csv.gz  in=265,720,977 out=51,400,848 elapsed=90.3s

  [4547/15692] intraday_13224.csv.gz  in=265,752,100 out=51,431,971 elapsed=90.4s

  [4548/15692] intraday_13225.csv.gz  in=265,792,907 out=51,472,778 elapsed=90.4s

  [4549/15692] intraday_13226.csv.gz  in=265,825,526 out=51,505,397 elapsed=90.4s

  [4550/15692] intraday_13228.csv.gz  in=265,864,268 out=51,542,356 elapsed=90.4s

  [4551/15692] intraday_1323.csv.gz  in=265,877,430 out=51,542,356 elapsed=90.4s

  [4552/15692] intraday_13227.csv.gz  in=265,919,054 out=51,583,980 elapsed=90.4s

  [4553/15692] intraday_13231.csv.gz  in=265,920,544 out=51,585,470 elapsed=90.4s

  [4554/15692] intraday_13229.csv.gz  in=265,954,832 out=51,619,758 elapsed=90.4s

  [4555/15692] intraday_13230.csv.gz  in=265,987,237 out=51,652,163 elapsed=90.5s

  [4556/15692] intraday_13233.csv.gz  in=266,019,817 out=51,684,323 elapsed=90.5s

  [4557/15692] intraday_13234.csv.gz  in=266,060,173 out=51,724,679 elapsed=90.5s

  [4558/15692] intraday_13232.csv.gz  in=266,094,997 out=51,759,503 elapsed=90.5s

  [4559/15692] intraday_13235.csv.gz  in=266,130,174 out=51,794,680 elapsed=90.5s

  [4560/15692] intraday_13236.csv.gz  in=266,159,949 out=51,824,455 elapsed=90.5s

  [4561/15692] intraday_13237.csv.gz  in=266,195,080 out=51,859,586 elapsed=90.6s

  [4562/15692] intraday_13239.csv.gz  in=266,207,461 out=51,871,967 elapsed=90.6s

  [4563/15692] intraday_13238.csv.gz  in=266,243,370 out=51,907,876 elapsed=90.6s

  [4564/15692] intraday_1324.csv.gz  in=266,256,749 out=51,907,876 elapsed=90.6s

  [4565/15692] intraday_13240.csv.gz  in=266,277,332 out=51,928,459 elapsed=90.6s

  [4566/15692] intraday_13241.csv.gz  in=266,311,843 out=51,962,970 elapsed=90.6s

  [4567/15692] intraday_13243.csv.gz  in=266,350,437 out=52,001,564 elapsed=90.7s

  [4568/15692] intraday_13242.csv.gz  in=266,392,063 out=52,041,410 elapsed=90.7s

  [4569/15692] intraday_13244.csv.gz  in=266,439,153 out=52,087,371 elapsed=90.7s

  [4570/15692] intraday_13245.csv.gz  in=266,469,125 out=52,117,343 elapsed=90.7s

  [4571/15692] intraday_13246.csv.gz  in=266,513,712 out=52,161,022 elapsed=90.8s

  [4572/15692] intraday_13249.csv.gz  in=266,514,526 out=52,161,836 elapsed=90.8s

  [4573/15692] intraday_13247.csv.gz  in=266,560,024 out=52,207,334 elapsed=90.8s

  [4574/15692] intraday_13248.csv.gz  in=266,594,261 out=52,241,571 elapsed=90.8s

  [4575/15692] intraday_1325.csv.gz  in=266,605,146 out=52,241,571 elapsed=90.8s

  [4576/15692] intraday_13250.csv.gz  in=266,645,867 out=52,282,292 elapsed=90.8s

  [4577/15692] intraday_13251.csv.gz  in=266,682,908 out=52,319,333 elapsed=90.9s

  [4578/15692] intraday_13253.csv.gz  in=266,718,688 out=52,355,113 elapsed=90.9s

  [4579/15692] intraday_13252.csv.gz  in=266,753,758 out=52,390,183 elapsed=90.9s

  [4580/15692] intraday_13254.csv.gz  in=266,784,158 out=52,420,583 elapsed=90.9s

  [4581/15692] intraday_13255.csv.gz  in=266,826,806 out=52,462,816 elapsed=90.9s

  [4582/15692] intraday_13259.csv.gz  in=266,827,520 out=52,463,530 elapsed=91.0s

  [4583/15692] intraday_1326.csv.gz  in=266,839,756 out=52,463,530 elapsed=91.0s

  [4584/15692] intraday_13258.csv.gz  in=266,870,554 out=52,494,328 elapsed=91.0s

  [4585/15692] intraday_13260.csv.gz  in=266,871,748 out=52,495,522 elapsed=91.0s

  [4586/15692] intraday_13257.csv.gz  in=266,909,871 out=52,533,645 elapsed=91.0s

  [4587/15692] intraday_13256.csv.gz  in=266,939,768 out=52,563,542 elapsed=91.0s

  [4588/15692] intraday_13261.csv.gz  in=266,970,999 out=52,594,773 elapsed=91.1s

  [4589/15692] intraday_13263.csv.gz  in=267,006,349 out=52,630,123 elapsed=91.1s

  [4590/15692] intraday_13262.csv.gz  in=267,042,797 out=52,666,571 elapsed=91.1s

  [4591/15692] intraday_13264.csv.gz  in=267,084,855 out=52,708,629 elapsed=91.2s

  [4592/15692] intraday_13265.csv.gz  in=267,128,419 out=52,752,193 elapsed=91.2s

  [4593/15692] intraday_13266.csv.gz  in=267,167,539 out=52,791,313 elapsed=91.2s

  [4594/15692] intraday_13267.csv.gz  in=267,209,989 out=52,833,763 elapsed=91.2s

  [4595/15692] intraday_13268.csv.gz  in=267,245,554 out=52,869,328 elapsed=91.2s

  [4596/15692] intraday_1327.csv.gz  in=267,258,738 out=52,869,328 elapsed=91.2s

  [4597/15692] intraday_13269.csv.gz  in=267,291,563 out=52,902,153 elapsed=91.3s

  [4598/15692] intraday_13272.csv.gz  in=267,294,337 out=52,904,927 elapsed=91.3s

  [4599/15692] intraday_13270.csv.gz  in=267,329,374 out=52,939,964 elapsed=91.3s

  [4600/15692] intraday_13274.csv.gz  in=267,329,624 out=52,940,214 elapsed=91.3s

  [4601/15692] intraday_13271.csv.gz  in=267,360,045 out=52,970,635 elapsed=91.3s

  [4602/15692] intraday_13275.csv.gz  in=267,360,338 out=52,970,928 elapsed=91.3s

  [4603/15692] intraday_13277.csv.gz  in=267,360,876 out=52,971,466 elapsed=91.3s

  [4604/15692] intraday_13276.csv.gz  in=267,383,300 out=52,987,607 elapsed=91.3s

  [4605/15692] intraday_13273.csv.gz  in=267,415,912 out=53,020,219 elapsed=91.4s

  [4606/15692] intraday_13278.csv.gz  in=267,416,321 out=53,020,628 elapsed=91.4s

  [4607/15692] intraday_13279.csv.gz  in=267,416,645 out=53,020,952 elapsed=91.4s

  [4608/15692] intraday_1328.csv.gz  in=267,430,301 out=53,020,952 elapsed=91.4s

  [4609/15692] intraday_13280.csv.gz  in=267,431,120 out=53,021,771 elapsed=91.4s

  [4610/15692] intraday_13283.csv.gz  in=267,431,522 out=53,022,173 elapsed=91.4s

  [4611/15692] intraday_13282.csv.gz  in=267,431,797 out=53,022,448 elapsed=91.4s

  [4612/15692] intraday_13281.csv.gz  in=267,432,433 out=53,023,084 elapsed=91.4s

  [4613/15692] intraday_13284.csv.gz  in=267,433,025 out=53,023,676 elapsed=91.4s

  [4614/15692] intraday_13286.csv.gz  in=267,445,120 out=53,035,771 elapsed=91.5s

  [4615/15692] intraday_13285.csv.gz  in=267,460,111 out=53,050,687 elapsed=91.5s

  [4616/15692] intraday_13288.csv.gz  in=267,469,564 out=53,060,140 elapsed=91.5s

  [4617/15692] intraday_13287.csv.gz  in=267,481,872 out=53,072,448 elapsed=91.5s

  [4618/15692] intraday_1329.csv.gz  in=267,492,835 out=53,072,448 elapsed=91.5s

  [4619/15692] intraday_13290.csv.gz  in=267,507,085 out=53,086,698 elapsed=91.5s

  [4620/15692] intraday_13291.csv.gz  in=267,521,429 out=53,101,042 elapsed=91.5s

  [4621/15692] intraday_13289.csv.gz  in=267,532,884 out=53,112,497 elapsed=91.5s

  [4622/15692] intraday_13292.csv.gz  in=267,543,821 out=53,123,434 elapsed=91.5s

  [4623/15692] intraday_13293.csv.gz  in=267,555,773 out=53,135,386 elapsed=91.6s

  [4624/15692] intraday_13294.csv.gz  in=267,568,284 out=53,147,897 elapsed=91.6s

  [4625/15692] intraday_13295.csv.gz  in=267,578,720 out=53,158,333 elapsed=91.6s

  [4626/15692] intraday_13296.csv.gz  in=267,590,697 out=53,170,310 elapsed=91.6s

  [4627/15692] intraday_13297.csv.gz  in=267,601,579 out=53,181,192 elapsed=91.6s

  [4628/15692] intraday_13298.csv.gz  in=267,615,734 out=53,195,347 elapsed=91.6s

  [4629/15692] intraday_13299.csv.gz  in=267,618,481 out=53,198,094 elapsed=91.6s

  [4630/15692] intraday_1330.csv.gz  in=267,631,563 out=53,198,094 elapsed=91.7s

  [4631/15692] intraday_13300.csv.gz  in=267,640,810 out=53,207,341 elapsed=91.7s

  [4632/15692] intraday_13301.csv.gz  in=267,651,765 out=53,218,296 elapsed=91.7s

  [4633/15692] intraday_13302.csv.gz  in=267,662,177 out=53,228,708 elapsed=91.7s

  [4634/15692] intraday_13304.csv.gz  in=267,674,815 out=53,241,346 elapsed=91.7s

  [4635/15692] intraday_13303.csv.gz  in=267,686,027 out=53,252,558 elapsed=91.7s

  [4636/15692] intraday_13305.csv.gz  in=267,698,611 out=53,265,142 elapsed=91.7s

  [4637/15692] intraday_13307.csv.gz  in=267,710,820 out=53,277,351 elapsed=91.7s

  [4638/15692] intraday_13306.csv.gz  in=267,723,204 out=53,289,735 elapsed=91.8s

  [4639/15692] intraday_1331.csv.gz  in=267,742,247 out=53,289,735 elapsed=91.8s

  [4640/15692] intraday_13309.csv.gz  in=267,753,226 out=53,300,714 elapsed=91.8s

  [4641/15692] intraday_13308.csv.gz  in=267,763,460 out=53,310,948 elapsed=91.8s

  [4642/15692] intraday_13313.csv.gz  in=267,768,947 out=53,316,435 elapsed=91.8s

  [4643/15692] intraday_13312.csv.gz  in=267,776,731 out=53,324,219 elapsed=91.8s

  [4644/15692] intraday_13310.csv.gz  in=267,788,114 out=53,335,602 elapsed=91.8s

  [4645/15692] intraday_13311.csv.gz  in=267,798,058 out=53,345,546 elapsed=91.8s

  [4646/15692] intraday_13314.csv.gz  in=267,810,288 out=53,357,776 elapsed=91.9s

  [4647/15692] intraday_13315.csv.gz  in=267,821,573 out=53,369,061 elapsed=91.9s

  [4648/15692] intraday_13316.csv.gz  in=267,835,981 out=53,383,469 elapsed=91.9s

  [4649/15692] intraday_13317.csv.gz  in=267,847,915 out=53,395,403 elapsed=91.9s

  [4650/15692] intraday_13318.csv.gz  in=267,858,354 out=53,405,603 elapsed=91.9s

  [4651/15692] intraday_1332.csv.gz  in=267,870,032 out=53,405,603 elapsed=91.9s

  [4652/15692] intraday_13320.csv.gz  in=267,878,813 out=53,414,384 elapsed=92.0s

  [4653/15692] intraday_13321.csv.gz  in=267,888,386 out=53,423,957 elapsed=92.0s

  [4654/15692] intraday_13319.csv.gz  in=267,899,416 out=53,434,987 elapsed=92.0s

  [4655/15692] intraday_13322.csv.gz  in=267,911,022 out=53,446,593 elapsed=92.0s

  [4656/15692] intraday_13325.csv.gz  in=267,916,379 out=53,451,950 elapsed=92.0s

  [4657/15692] intraday_13323.csv.gz  in=267,927,999 out=53,463,570 elapsed=92.0s

  [4658/15692] intraday_13326.csv.gz  in=267,928,000 out=53,463,571 elapsed=92.0s

  [4659/15692] intraday_13324.csv.gz  in=267,943,138 out=53,477,252 elapsed=92.0s

  [4660/15692] intraday_13327.csv.gz  in=267,952,096 out=53,486,210 elapsed=92.0s

  [4661/15692] intraday_1333.csv.gz  in=267,967,273 out=53,486,210 elapsed=92.0s

  [4662/15692] intraday_13329.csv.gz  in=267,978,137 out=53,497,074 elapsed=92.1s

  [4663/15692] intraday_13328.csv.gz  in=267,991,594 out=53,509,586 elapsed=92.1s

  [4664/15692] intraday_13330.csv.gz  in=268,001,959 out=53,519,951 elapsed=92.1s

  [4665/15692] intraday_13331.csv.gz  in=268,011,890 out=53,529,882 elapsed=92.1s

  [4666/15692] intraday_13333.csv.gz  in=268,023,089 out=53,541,081 elapsed=92.1s

  [4667/15692] intraday_13332.csv.gz  in=268,035,605 out=53,553,597 elapsed=92.1s

  [4668/15692] intraday_13334.csv.gz  in=268,046,472 out=53,564,464 elapsed=92.1s

  [4669/15692] intraday_13335.csv.gz  in=268,057,868 out=53,575,860 elapsed=92.1s

  [4670/15692] intraday_13336.csv.gz  in=268,068,543 out=53,586,535 elapsed=92.1s

  [4671/15692] intraday_13337.csv.gz  in=268,080,545 out=53,598,537 elapsed=92.2s

  [4672/15692] intraday_13339.csv.gz  in=268,082,369 out=53,600,361 elapsed=92.2s

  [4673/15692] intraday_13338.csv.gz  in=268,101,232 out=53,617,266 elapsed=92.2s

  [4674/15692] intraday_13340.csv.gz  in=268,104,845 out=53,620,879 elapsed=92.2s

  [4675/15692] intraday_1334.csv.gz  in=268,117,058 out=53,620,879 elapsed=92.2s

  [4676/15692] intraday_13341.csv.gz  in=268,133,932 out=53,635,962 elapsed=92.2s

  [4677/15692] intraday_13343.csv.gz  in=268,142,531 out=53,644,561 elapsed=92.2s

  [4678/15692] intraday_13342.csv.gz  in=268,152,688 out=53,654,718 elapsed=92.2s

  [4679/15692] intraday_13344.csv.gz  in=268,166,595 out=53,668,625 elapsed=92.3s

  [4680/15692] intraday_13345.csv.gz  in=268,179,952 out=53,681,982 elapsed=92.3s

  [4681/15692] intraday_13346.csv.gz  in=268,196,413 out=53,697,764 elapsed=92.3s

  [4682/15692] intraday_13347.csv.gz  in=268,208,351 out=53,709,702 elapsed=92.3s

  [4683/15692] intraday_13349.csv.gz  in=268,216,528 out=53,717,879 elapsed=92.3s

  [4684/15692] intraday_13348.csv.gz  in=268,227,461 out=53,728,812 elapsed=92.3s

  [4685/15692] intraday_1335.csv.gz  in=268,239,487 out=53,728,812 elapsed=92.3s

  [4686/15692] intraday_13350.csv.gz  in=268,251,016 out=53,740,237 elapsed=92.3s

  [4687/15692] intraday_13351.csv.gz  in=268,262,936 out=53,752,157 elapsed=92.4s

  [4688/15692] intraday_13353.csv.gz  in=268,270,354 out=53,759,575 elapsed=92.4s

  [4689/15692] intraday_13352.csv.gz  in=268,283,400 out=53,772,621 elapsed=92.4s

  [4690/15692] intraday_13354.csv.gz  in=268,284,080 out=53,773,301 elapsed=92.4s

  [4691/15692] intraday_13355.csv.gz  in=268,296,368 out=53,785,589 elapsed=92.4s

  [4692/15692] intraday_13356.csv.gz  in=268,307,939 out=53,797,160 elapsed=92.4s

  [4693/15692] intraday_13357.csv.gz  in=268,319,877 out=53,809,098 elapsed=92.4s

  [4694/15692] intraday_13358.csv.gz  in=268,331,321 out=53,820,542 elapsed=92.4s

  [4695/15692] intraday_13359.csv.gz  in=268,340,501 out=53,829,722 elapsed=92.5s

  [4696/15692] intraday_1336.csv.gz  in=268,354,480 out=53,829,722 elapsed=92.5s

  [4697/15692] intraday_13360.csv.gz  in=268,365,945 out=53,841,187 elapsed=92.5s

  [4698/15692] intraday_13361.csv.gz  in=268,377,341 out=53,852,583 elapsed=92.5s

  [4699/15692] intraday_13362.csv.gz  in=268,390,956 out=53,866,198 elapsed=92.5s

  [4700/15692] intraday_13363.csv.gz  in=268,404,622 out=53,879,864 elapsed=92.5s

  [4701/15692] intraday_13364.csv.gz  in=268,417,915 out=53,893,157 elapsed=92.5s

  [4702/15692] intraday_13365.csv.gz  in=268,428,709 out=53,903,951 elapsed=92.5s

  [4703/15692] intraday_13366.csv.gz  in=268,441,239 out=53,916,481 elapsed=92.6s

  [4704/15692] intraday_13367.csv.gz  in=268,452,189 out=53,927,431 elapsed=92.6s

  [4705/15692] intraday_13369.csv.gz  in=268,468,334 out=53,942,588 elapsed=92.6s

  [4706/15692] intraday_13368.csv.gz  in=268,480,214 out=53,954,468 elapsed=92.6s

  [4707/15692] intraday_1337.csv.gz  in=268,495,082 out=53,954,468 elapsed=92.6s

  [4708/15692] intraday_13370.csv.gz  in=268,506,234 out=53,965,620 elapsed=92.6s

  [4709/15692] intraday_13371.csv.gz  in=268,520,029 out=53,979,415 elapsed=92.6s

  [4710/15692] intraday_13372.csv.gz  in=268,532,133 out=53,991,519 elapsed=92.7s

  [4711/15692] intraday_13374.csv.gz  in=268,543,068 out=54,002,454 elapsed=92.7s

  [4712/15692] intraday_13375.csv.gz  in=268,555,456 out=54,014,842 elapsed=92.7s

  [4713/15692] intraday_13376.csv.gz  in=268,566,764 out=54,026,150 elapsed=92.7s

  [4714/15692] intraday_13377.csv.gz  in=268,576,213 out=54,035,567 elapsed=92.7s

  [4715/15692] intraday_13373.csv.gz  in=268,587,787 out=54,047,141 elapsed=92.7s

  [4716/15692] intraday_13379.csv.gz  in=268,598,004 out=54,057,358 elapsed=92.7s

  [4717/15692] intraday_13378.csv.gz  in=268,609,843 out=54,069,197 elapsed=92.7s

  [4718/15692] intraday_1338.csv.gz  in=268,622,463 out=54,069,197 elapsed=92.7s

  [4719/15692] intraday_13380.csv.gz  in=268,634,424 out=54,081,158 elapsed=92.8s

  [4720/15692] intraday_13382.csv.gz  in=268,646,329 out=54,093,063 elapsed=92.8s

  [4721/15692] intraday_13381.csv.gz  in=268,657,396 out=54,104,130 elapsed=92.8s

  [4722/15692] intraday_13383.csv.gz  in=268,670,235 out=54,116,969 elapsed=92.8s

  [4723/15692] intraday_13384.csv.gz  in=268,681,075 out=54,127,809 elapsed=92.8s

  [4724/15692] intraday_13385.csv.gz  in=268,695,324 out=54,142,058 elapsed=92.8s

  [4725/15692] intraday_13386.csv.gz  in=268,706,277 out=54,153,011 elapsed=92.9s

  [4726/15692] intraday_13387.csv.gz  in=268,717,117 out=54,163,851 elapsed=92.9s

  [4727/15692] intraday_13388.csv.gz  in=268,728,984 out=54,175,718 elapsed=92.9s

  [4728/15692] intraday_13389.csv.gz  in=268,742,629 out=54,189,363 elapsed=92.9s

  [4729/15692] intraday_1339.csv.gz  in=268,756,871 out=54,189,363 elapsed=92.9s

  [4730/15692] intraday_13390.csv.gz  in=268,766,855 out=54,199,347 elapsed=92.9s

  [4731/15692] intraday_13391.csv.gz  in=268,779,495 out=54,211,987 elapsed=92.9s

  [4732/15692] intraday_13392.csv.gz  in=268,793,447 out=54,225,939 elapsed=92.9s

  [4733/15692] intraday_13393.csv.gz  in=268,805,741 out=54,238,233 elapsed=92.9s

  [4734/15692] intraday_13394.csv.gz  in=268,819,824 out=54,252,316 elapsed=93.0s

  [4735/15692] intraday_13395.csv.gz  in=268,834,092 out=54,266,584 elapsed=93.0s

  [4736/15692] intraday_13397.csv.gz  in=268,847,479 out=54,279,971 elapsed=93.0s

  [4737/15692] intraday_13396.csv.gz  in=268,864,335 out=54,296,827 elapsed=93.0s

  [4738/15692] intraday_13398.csv.gz  in=268,877,741 out=54,310,233 elapsed=93.0s

  [4739/15692] intraday_13399.csv.gz  in=268,890,303 out=54,322,795 elapsed=93.0s

  [4740/15692] intraday_1340.csv.gz  in=268,902,233 out=54,322,795 elapsed=93.0s

  [4741/15692] intraday_13400.csv.gz  in=268,914,052 out=54,334,614 elapsed=93.0s

  [4742/15692] intraday_13401.csv.gz  in=268,922,946 out=54,343,508 elapsed=93.0s

  [4743/15692] intraday_13403.csv.gz  in=268,932,966 out=54,353,528 elapsed=93.1s

  [4744/15692] intraday_13402.csv.gz  in=268,945,582 out=54,366,144 elapsed=93.1s

  [4745/15692] intraday_13405.csv.gz  in=268,957,820 out=54,378,382 elapsed=93.1s

  [4746/15692] intraday_13406.csv.gz  in=268,971,530 out=54,392,092 elapsed=93.1s

  [4747/15692] intraday_13404.csv.gz  in=268,982,527 out=54,403,089 elapsed=93.1s

  [4748/15692] intraday_13407.csv.gz  in=268,991,380 out=54,411,942 elapsed=93.1s

  [4749/15692] intraday_13408.csv.gz  in=269,001,814 out=54,422,376 elapsed=93.2s

  [4750/15692] intraday_1341.csv.gz  in=269,017,974 out=54,422,376 elapsed=93.2s

  [4751/15692] intraday_13410.csv.gz  in=269,028,260 out=54,432,662 elapsed=93.2s

  [4752/15692] intraday_13409.csv.gz  in=269,040,176 out=54,444,578 elapsed=93.2s

  [4753/15692] intraday_13413.csv.gz  in=269,053,493 out=54,457,895 elapsed=93.2s

  [4754/15692] intraday_13412.csv.gz  in=269,067,157 out=54,471,559 elapsed=93.2s

  [4755/15692] intraday_13414.csv.gz  in=269,078,784 out=54,483,186 elapsed=93.2s

  [4756/15692] intraday_13411.csv.gz  in=269,091,315 out=54,495,717 elapsed=93.2s

  [4757/15692] intraday_13415.csv.gz  in=269,106,060 out=54,510,462 elapsed=93.2s

  [4758/15692] intraday_13416.csv.gz  in=269,116,913 out=54,521,315 elapsed=93.3s

  [4759/15692] intraday_13417.csv.gz  in=269,127,581 out=54,531,983 elapsed=93.3s

  [4760/15692] intraday_13418.csv.gz  in=269,139,552 out=54,543,954 elapsed=93.3s

  [4761/15692] intraday_13419.csv.gz  in=269,151,069 out=54,555,471 elapsed=93.3s

  [4762/15692] intraday_13420.csv.gz  in=269,160,816 out=54,565,218 elapsed=93.3s

  [4763/15692] intraday_1342.csv.gz  in=269,172,314 out=54,565,218 elapsed=93.3s

  [4764/15692] intraday_13421.csv.gz  in=269,177,981 out=54,570,885 elapsed=93.3s

  [4765/15692] intraday_13422.csv.gz  in=269,190,015 out=54,582,919 elapsed=93.3s

  [4766/15692] intraday_13423.csv.gz  in=269,197,605 out=54,590,509 elapsed=93.3s

  [4767/15692] intraday_13424.csv.gz  in=269,197,781 out=54,590,685 elapsed=93.3s

  [4768/15692] intraday_13425.csv.gz  in=269,198,246 out=54,591,150 elapsed=93.3s

  [4769/15692] intraday_13426.csv.gz  in=269,198,989 out=54,591,893 elapsed=93.3s

  [4770/15692] intraday_13427.csv.gz  in=269,199,694 out=54,592,598 elapsed=93.3s

  [4771/15692] intraday_13429.csv.gz  in=269,200,101 out=54,593,005 elapsed=93.3s

  [4772/15692] intraday_13430.csv.gz  in=269,200,494 out=54,593,398 elapsed=93.4s

  [4773/15692] intraday_13428.csv.gz  in=269,200,659 out=54,593,563 elapsed=93.4s

  [4774/15692] intraday_1343.csv.gz  in=269,213,898 out=54,593,563 elapsed=93.4s

  [4775/15692] intraday_13431.csv.gz  in=269,214,193 out=54,593,858 elapsed=93.4s

  [4776/15692] intraday_13432.csv.gz  in=269,214,676 out=54,594,341 elapsed=93.4s

  [4777/15692] intraday_13433.csv.gz  in=269,215,236 out=54,594,901 elapsed=93.4s

  [4778/15692] intraday_13435.csv.gz  in=269,215,464 out=54,595,129 elapsed=93.4s

  [4779/15692] intraday_13434.csv.gz  in=269,216,020 out=54,595,685 elapsed=93.4s

  [4780/15692] intraday_13437.csv.gz  in=269,216,709 out=54,596,374 elapsed=93.4s

  [4781/15692] intraday_13436.csv.gz  in=269,217,375 out=54,597,040 elapsed=93.4s

  [4782/15692] intraday_13438.csv.gz  in=269,217,670 out=54,597,335 elapsed=93.4s

  [4783/15692] intraday_13439.csv.gz  in=269,217,963 out=54,597,628 elapsed=93.4s

  [4784/15692] intraday_13440.csv.gz  in=269,218,235 out=54,597,900 elapsed=93.4s

  [4785/15692] intraday_13441.csv.gz  in=269,218,593 out=54,598,258 elapsed=93.4s

  [4786/15692] intraday_13442.csv.gz  in=269,218,668 out=54,598,333 elapsed=93.4s

  [4787/15692] intraday_13443.csv.gz  in=269,218,841 out=54,598,506 elapsed=93.4s

  [4788/15692] intraday_1344.csv.gz  in=269,234,097 out=54,598,506 elapsed=93.4s

  [4789/15692] intraday_13446.csv.gz  in=269,234,239 out=54,598,648 elapsed=93.5s

  [4790/15692] intraday_13447.csv.gz  in=269,234,808 out=54,599,217 elapsed=93.5s

  [4791/15692] intraday_13445.csv.gz  in=269,235,543 out=54,599,952 elapsed=93.5s

  [4792/15692] intraday_13448.csv.gz  in=269,235,994 out=54,600,403 elapsed=93.5s

  [4793/15692] intraday_13444.csv.gz  in=269,252,364 out=54,614,272 elapsed=93.5s

  [4794/15692] intraday_13449.csv.gz  in=269,253,112 out=54,615,020 elapsed=93.5s

  [4795/15692] intraday_13451.csv.gz  in=269,253,262 out=54,615,170 elapsed=93.5s

  [4796/15692] intraday_13450.csv.gz  in=269,253,942 out=54,615,850 elapsed=93.5s

  [4797/15692] intraday_13452.csv.gz  in=269,254,331 out=54,616,239 elapsed=93.5s

  [4798/15692] intraday_13453.csv.gz  in=269,254,551 out=54,616,459 elapsed=93.5s

  [4799/15692] intraday_1345.csv.gz  in=269,268,895 out=54,616,459 elapsed=93.5s

  [4800/15692] intraday_13455.csv.gz  in=269,269,013 out=54,616,577 elapsed=93.5s

  [4801/15692] intraday_13456.csv.gz  in=269,269,462 out=54,617,026 elapsed=93.5s

  [4802/15692] intraday_13454.csv.gz  in=269,271,722 out=54,619,286 elapsed=93.5s

  [4803/15692] intraday_13457.csv.gz  in=269,271,866 out=54,619,430 elapsed=93.6s

  [4804/15692] intraday_13458.csv.gz  in=269,271,898 out=54,619,462 elapsed=93.6s

  [4805/15692] intraday_13459.csv.gz  in=269,272,050 out=54,619,614 elapsed=93.6s

  [4806/15692] intraday_13460.csv.gz  in=269,272,201 out=54,619,765 elapsed=93.6s

  [4807/15692] intraday_13462.csv.gz  in=269,272,463 out=54,620,027 elapsed=93.6s

  [4808/15692] intraday_13461.csv.gz  in=269,272,832 out=54,620,362 elapsed=93.6s

  [4809/15692] intraday_13463.csv.gz  in=269,272,866 out=54,620,396 elapsed=93.6s

  [4810/15692] intraday_13464.csv.gz  in=269,273,257 out=54,620,787 elapsed=93.6s

  [4811/15692] intraday_13465.csv.gz  in=269,273,410 out=54,620,940 elapsed=93.6s

  [4812/15692] intraday_1346.csv.gz  in=269,285,960 out=54,620,940 elapsed=93.6s

  [4813/15692] intraday_13467.csv.gz  in=269,286,136 out=54,621,116 elapsed=93.6s

  [4814/15692] intraday_13466.csv.gz  in=269,286,673 out=54,621,653 elapsed=93.6s

  [4815/15692] intraday_13469.csv.gz  in=269,287,403 out=54,622,383 elapsed=93.6s

  [4816/15692] intraday_13468.csv.gz  in=269,287,529 out=54,622,509 elapsed=93.6s

  [4817/15692] intraday_13472.csv.gz  in=269,287,709 out=54,622,689 elapsed=93.6s

  [4818/15692] intraday_13470.csv.gz  in=269,288,546 out=54,623,526 elapsed=93.6s

  [4819/15692] intraday_13471.csv.gz  in=269,289,102 out=54,624,082 elapsed=93.6s

  [4820/15692] intraday_1347.csv.gz  in=269,304,470 out=54,624,082 elapsed=93.6s

  [4821/15692] intraday_13473.csv.gz  in=269,304,661 out=54,624,273 elapsed=93.7s

  [4822/15692] intraday_13476.csv.gz  in=269,304,985 out=54,624,597 elapsed=93.7s

  [4823/15692] intraday_13474.csv.gz  in=269,305,126 out=54,624,738 elapsed=93.7s

  [4824/15692] intraday_13478.csv.gz  in=269,305,609 out=54,625,221 elapsed=93.7s

  [4825/15692] intraday_13475.csv.gz  in=269,315,055 out=54,632,786 elapsed=93.7s

  [4826/15692] intraday_13479.csv.gz  in=269,315,209 out=54,632,940 elapsed=93.7s

  [4827/15692] intraday_13477.csv.gz  in=269,315,441 out=54,633,172 elapsed=93.7s

  [4828/15692] intraday_13480.csv.gz  in=269,315,491 out=54,633,222 elapsed=93.7s

  [4829/15692] intraday_13481.csv.gz  in=269,315,650 out=54,633,381 elapsed=93.7s

  [4830/15692] intraday_13482.csv.gz  in=269,316,705 out=54,634,436 elapsed=93.7s

  [4831/15692] intraday_1348.csv.gz  in=269,327,583 out=54,634,436 elapsed=93.7s

  [4832/15692] intraday_13483.csv.gz  in=269,328,340 out=54,635,193 elapsed=93.7s

  [4833/15692] intraday_13484.csv.gz  in=269,328,784 out=54,635,637 elapsed=93.7s

  [4834/15692] intraday_13485.csv.gz  in=269,328,813 out=54,635,666 elapsed=93.7s

  [4835/15692] intraday_13486.csv.gz  in=269,329,499 out=54,636,352 elapsed=93.7s

  [4836/15692] intraday_13489.csv.gz  in=269,329,974 out=54,636,827 elapsed=93.7s

  [4837/15692] intraday_13488.csv.gz  in=269,330,391 out=54,637,244 elapsed=93.8s

  [4838/15692] intraday_13487.csv.gz  in=269,330,997 out=54,637,775 elapsed=93.8s

  [4839/15692] intraday_13490.csv.gz  in=269,331,334 out=54,638,112 elapsed=93.8s

  [4840/15692] intraday_1349.csv.gz  in=269,343,616 out=54,638,112 elapsed=93.8s

  [4841/15692] intraday_13494.csv.gz  in=269,343,836 out=54,638,332 elapsed=93.8s

  [4842/15692] intraday_13492.csv.gz  in=269,344,398 out=54,638,894 elapsed=93.8s

  [4843/15692] intraday_13491.csv.gz  in=269,344,652 out=54,639,148 elapsed=93.8s

  [4844/15692] intraday_13493.csv.gz  in=269,344,917 out=54,639,413 elapsed=93.8s

  [4845/15692] intraday_13498.csv.gz  in=269,344,940 out=54,639,436 elapsed=93.8s

  [4846/15692] intraday_13495.csv.gz  in=269,345,175 out=54,639,671 elapsed=93.8s

  [4847/15692] intraday_13496.csv.gz  in=269,345,714 out=54,640,210 elapsed=93.8s

  [4848/15692] intraday_13497.csv.gz  in=269,346,130 out=54,640,626 elapsed=93.8s

  [4849/15692] intraday_13499.csv.gz  in=269,346,568 out=54,641,064 elapsed=93.8s

  [4850/15692] intraday_13500.csv.gz  in=269,347,150 out=54,641,646 elapsed=93.8s

  [4851/15692] intraday_13501.csv.gz  in=269,348,639 out=54,643,135 elapsed=93.8s

  [4852/15692] intraday_1350.csv.gz  in=269,360,075 out=54,643,135 elapsed=93.8s

  [4853/15692] intraday_13502.csv.gz  in=269,360,802 out=54,643,862 elapsed=93.8s

  [4854/15692] intraday_13504.csv.gz  in=269,361,304 out=54,644,364 elapsed=93.8s

  [4855/15692] intraday_13503.csv.gz  in=269,362,190 out=54,645,250 elapsed=93.9s

  [4856/15692] intraday_13505.csv.gz  in=269,362,533 out=54,645,593 elapsed=93.9s

  [4857/15692] intraday_13506.csv.gz  in=269,362,816 out=54,645,876 elapsed=93.9s

  [4858/15692] intraday_13507.csv.gz  in=269,363,614 out=54,646,674 elapsed=93.9s

  [4859/15692] intraday_13509.csv.gz  in=269,363,889 out=54,646,949 elapsed=93.9s

  [4860/15692] intraday_13510.csv.gz  in=269,364,551 out=54,647,611 elapsed=93.9s

  [4861/15692] intraday_13512.csv.gz  in=269,364,842 out=54,647,902 elapsed=93.9s

  [4862/15692] intraday_13511.csv.gz  in=269,365,251 out=54,648,311 elapsed=93.9s

  [4863/15692] intraday_13513.csv.gz  in=269,365,423 out=54,648,483 elapsed=93.9s

  [4864/15692] intraday_1351.csv.gz  in=269,380,649 out=54,648,483 elapsed=93.9s

  [4865/15692] intraday_13508.csv.gz  in=269,405,487 out=54,667,812 elapsed=93.9s

  [4866/15692] intraday_13515.csv.gz  in=269,405,751 out=54,668,076 elapsed=93.9s

  [4867/15692] intraday_13514.csv.gz  in=269,406,176 out=54,668,501 elapsed=93.9s

  [4868/15692] intraday_13516.csv.gz  in=269,406,792 out=54,669,117 elapsed=93.9s

  [4869/15692] intraday_13517.csv.gz  in=269,406,913 out=54,669,238 elapsed=93.9s

  [4870/15692] intraday_13518.csv.gz  in=269,407,034 out=54,669,359 elapsed=93.9s

  [4871/15692] intraday_13519.csv.gz  in=269,407,413 out=54,669,738 elapsed=93.9s

  [4872/15692] intraday_13521.csv.gz  in=269,408,029 out=54,670,354 elapsed=93.9s

  [4873/15692] intraday_13520.csv.gz  in=269,409,134 out=54,671,459 elapsed=93.9s

  [4874/15692] intraday_13522.csv.gz  in=269,409,788 out=54,672,113 elapsed=94.0s

  [4875/15692] intraday_13523.csv.gz  in=269,410,062 out=54,672,387 elapsed=94.0s

  [4876/15692] intraday_1352.csv.gz  in=269,423,544 out=54,672,387 elapsed=94.0s

  [4877/15692] intraday_13524.csv.gz  in=269,424,045 out=54,672,888 elapsed=94.0s

  [4878/15692] intraday_13525.csv.gz  in=269,424,143 out=54,672,986 elapsed=94.0s

  [4879/15692] intraday_13526.csv.gz  in=269,425,233 out=54,674,076 elapsed=94.0s

  [4880/15692] intraday_13528.csv.gz  in=269,425,597 out=54,674,440 elapsed=94.0s

  [4881/15692] intraday_13529.csv.gz  in=269,425,770 out=54,674,613 elapsed=94.0s

  [4882/15692] intraday_13527.csv.gz  in=269,425,989 out=54,674,832 elapsed=94.0s

  [4883/15692] intraday_13530.csv.gz  in=269,426,423 out=54,675,266 elapsed=94.0s

  [4884/15692] intraday_13531.csv.gz  in=269,427,622 out=54,676,465 elapsed=94.0s

  [4885/15692] intraday_13532.csv.gz  in=269,428,407 out=54,677,250 elapsed=94.0s

  [4886/15692] intraday_13533.csv.gz  in=269,429,693 out=54,678,536 elapsed=94.0s

  [4887/15692] intraday_13534.csv.gz  in=269,430,635 out=54,679,478 elapsed=94.0s

  [4888/15692] intraday_1353.csv.gz  in=269,446,961 out=54,679,478 elapsed=94.0s

  [4889/15692] intraday_13537.csv.gz  in=269,447,383 out=54,679,900 elapsed=94.0s

  [4890/15692] intraday_13536.csv.gz  in=269,448,151 out=54,680,668 elapsed=94.0s

  [4891/15692] intraday_13538.csv.gz  in=269,448,879 out=54,681,396 elapsed=94.0s

  [4892/15692] intraday_13535.csv.gz  in=269,450,177 out=54,682,694 elapsed=94.0s

  [4893/15692] intraday_13539.csv.gz  in=269,450,356 out=54,682,873 elapsed=94.0s

  [4894/15692] intraday_13540.csv.gz  in=269,450,564 out=54,683,081 elapsed=94.0s

  [4895/15692] intraday_13543.csv.gz  in=269,450,734 out=54,683,251 elapsed=94.1s

  [4896/15692] intraday_1354.csv.gz  in=269,464,054 out=54,683,251 elapsed=94.1s

  [4897/15692] intraday_13541.csv.gz  in=269,464,334 out=54,683,531 elapsed=94.1s

  [4898/15692] intraday_13542.csv.gz  in=269,464,515 out=54,683,712 elapsed=94.1s

  [4899/15692] intraday_13544.csv.gz  in=269,465,102 out=54,684,299 elapsed=94.1s

  [4900/15692] intraday_13545.csv.gz  in=269,465,953 out=54,685,150 elapsed=94.1s

  [4901/15692] intraday_13546.csv.gz  in=269,466,135 out=54,685,332 elapsed=94.1s

  [4902/15692] intraday_13547.csv.gz  in=269,466,527 out=54,685,724 elapsed=94.1s

  [4903/15692] intraday_13548.csv.gz  in=269,467,004 out=54,686,201 elapsed=94.1s

  [4904/15692] intraday_13549.csv.gz  in=269,467,377 out=54,686,574 elapsed=94.1s

  [4905/15692] intraday_13550.csv.gz  in=269,467,971 out=54,687,168 elapsed=94.1s

  [4906/15692] intraday_13553.csv.gz  in=269,468,436 out=54,687,633 elapsed=94.1s

  [4907/15692] intraday_13551.csv.gz  in=269,468,617 out=54,687,814 elapsed=94.1s

  [4908/15692] intraday_13552.csv.gz  in=269,468,812 out=54,688,009 elapsed=94.1s

  [4909/15692] intraday_1355.csv.gz  in=269,481,317 out=54,688,009 elapsed=94.1s

  [4910/15692] intraday_13554.csv.gz  in=269,481,556 out=54,688,248 elapsed=94.1s

  [4911/15692] intraday_13555.csv.gz  in=269,482,263 out=54,688,955 elapsed=94.1s

  [4912/15692] intraday_13556.csv.gz  in=269,482,578 out=54,689,270 elapsed=94.1s

  [4913/15692] intraday_13557.csv.gz  in=269,482,997 out=54,689,689 elapsed=94.1s

  [4914/15692] intraday_13558.csv.gz  in=269,483,328 out=54,690,020 elapsed=94.1s

  [4915/15692] intraday_13559.csv.gz  in=269,483,845 out=54,690,537 elapsed=94.2s

  [4916/15692] intraday_13560.csv.gz  in=269,485,416 out=54,691,536 elapsed=94.2s

  [4917/15692] intraday_13561.csv.gz  in=269,486,035 out=54,692,155 elapsed=94.2s

  [4918/15692] intraday_13562.csv.gz  in=269,486,118 out=54,692,238 elapsed=94.2s

  [4919/15692] intraday_1356.csv.gz  in=269,501,306 out=54,692,238 elapsed=94.2s

  [4920/15692] intraday_13566.csv.gz  in=269,524,161 out=54,715,093 elapsed=94.3s

  [4921/15692] intraday_13563.csv.gz  in=269,556,969 out=54,747,901 elapsed=94.3s

  [4922/15692] intraday_13564.csv.gz  in=269,582,203 out=54,773,135 elapsed=94.3s

  [4923/15692] intraday_13565.csv.gz  in=269,606,865 out=54,797,797 elapsed=94.3s

  [4924/15692] intraday_13567.csv.gz  in=269,632,169 out=54,823,101 elapsed=94.3s

  [4925/15692] intraday_1357.csv.gz  in=269,645,549 out=54,823,101 elapsed=94.3s

  [4926/15692] intraday_13568.csv.gz  in=269,676,879 out=54,854,431 elapsed=94.3s

  [4927/15692] intraday_13571.csv.gz  in=269,689,347 out=54,866,899 elapsed=94.3s

  [4928/15692] intraday_13570.csv.gz  in=269,710,989 out=54,888,541 elapsed=94.4s

  [4929/15692] intraday_13569.csv.gz  in=269,739,224 out=54,916,776 elapsed=94.4s

  [4930/15692] intraday_13572.csv.gz  in=269,765,002 out=54,942,554 elapsed=94.4s

  [4931/15692] intraday_13573.csv.gz  in=269,794,324 out=54,971,876 elapsed=94.4s

  [4932/15692] intraday_13574.csv.gz  in=269,811,927 out=54,989,479 elapsed=94.4s

  [4933/15692] intraday_13575.csv.gz  in=269,840,393 out=55,017,933 elapsed=94.4s

  [4934/15692] intraday_13576.csv.gz  in=269,867,585 out=55,045,125 elapsed=94.5s

  [4935/15692] intraday_13578.csv.gz  in=269,889,677 out=55,067,217 elapsed=94.5s

  [4936/15692] intraday_13577.csv.gz  in=269,915,175 out=55,092,715 elapsed=94.5s

  [4937/15692] intraday_13579.csv.gz  in=269,936,559 out=55,114,099 elapsed=94.5s

  [4938/15692] intraday_1358.csv.gz  in=269,949,867 out=55,114,099 elapsed=94.5s

  [4939/15692] intraday_13581.csv.gz  in=269,952,158 out=55,116,390 elapsed=94.5s

  [4940/15692] intraday_13580.csv.gz  in=269,972,066 out=55,136,298 elapsed=94.6s

  [4941/15692] intraday_13584.csv.gz  in=269,994,344 out=55,158,576 elapsed=94.6s

  [4942/15692] intraday_13583.csv.gz  in=270,015,780 out=55,180,012 elapsed=94.6s

  [4943/15692] intraday_13585.csv.gz  in=270,038,145 out=55,202,377 elapsed=94.6s

  [4944/15692] intraday_13582.csv.gz  in=270,062,140 out=55,226,372 elapsed=94.6s

  [4945/15692] intraday_13586.csv.gz  in=270,086,384 out=55,250,616 elapsed=94.7s

  [4946/15692] intraday_13587.csv.gz  in=270,113,246 out=55,277,478 elapsed=94.7s

  [4947/15692] intraday_1359.csv.gz  in=270,128,982 out=55,277,478 elapsed=94.7s

  [4948/15692] intraday_13589.csv.gz  in=270,157,248 out=55,305,744 elapsed=94.7s

  [4949/15692] intraday_13588.csv.gz  in=270,187,049 out=55,335,545 elapsed=94.7s

  [4950/15692] intraday_13590.csv.gz  in=270,208,446 out=55,356,942 elapsed=94.8s

  [4951/15692] intraday_13591.csv.gz  in=270,230,015 out=55,378,511 elapsed=94.8s

  [4952/15692] intraday_13592.csv.gz  in=270,252,367 out=55,400,863 elapsed=94.8s

  [4953/15692] intraday_13593.csv.gz  in=270,275,433 out=55,423,929 elapsed=94.8s

  [4954/15692] intraday_13594.csv.gz  in=270,293,650 out=55,442,146 elapsed=94.8s

  [4955/15692] intraday_13595.csv.gz  in=270,316,332 out=55,464,552 elapsed=94.8s

  [4956/15692] intraday_13596.csv.gz  in=270,342,208 out=55,490,428 elapsed=94.9s

  [4957/15692] intraday_13597.csv.gz  in=270,364,205 out=55,512,425 elapsed=94.9s

  [4958/15692] intraday_13598.csv.gz  in=270,389,022 out=55,537,242 elapsed=94.9s

  [4959/15692] intraday_1360.csv.gz  in=270,403,396 out=55,537,242 elapsed=94.9s

  [4960/15692] intraday_13599.csv.gz  in=270,432,344 out=55,566,190 elapsed=94.9s

  [4961/15692] intraday_13603.csv.gz  in=270,432,346 out=55,566,192 elapsed=94.9s

  [4962/15692] intraday_13600.csv.gz  in=270,457,421 out=55,591,267 elapsed=94.9s

  [4963/15692] intraday_13602.csv.gz  in=270,482,078 out=55,615,924 elapsed=95.0s

  [4964/15692] intraday_13601.csv.gz  in=270,504,240 out=55,638,086 elapsed=95.0s

  [4965/15692] intraday_13604.csv.gz  in=270,522,378 out=55,656,224 elapsed=95.0s

  [4966/15692] intraday_13605.csv.gz  in=270,551,260 out=55,685,106 elapsed=95.0s

  [4967/15692] intraday_13606.csv.gz  in=270,573,004 out=55,706,850 elapsed=95.0s

  [4968/15692] intraday_13608.csv.gz  in=270,598,147 out=55,731,993 elapsed=95.0s

  [4969/15692] intraday_13607.csv.gz  in=270,620,893 out=55,754,739 elapsed=95.0s

  [4970/15692] intraday_1361.csv.gz  in=270,635,338 out=55,754,739 elapsed=95.1s

  [4971/15692] intraday_13609.csv.gz  in=270,658,117 out=55,777,518 elapsed=95.1s

  [4972/15692] intraday_13611.csv.gz  in=270,679,088 out=55,798,489 elapsed=95.1s

  [4973/15692] intraday_13613.csv.gz  in=270,705,015 out=55,824,416 elapsed=95.1s

  [4974/15692] intraday_13612.csv.gz  in=270,726,664 out=55,846,065 elapsed=95.1s

  [4975/15692] intraday_13610.csv.gz  in=270,752,665 out=55,872,066 elapsed=95.1s

  [4976/15692] intraday_13614.csv.gz  in=270,788,755 out=55,904,414 elapsed=95.2s

  [4977/15692] intraday_13616.csv.gz  in=270,789,590 out=55,905,249 elapsed=95.2s

  [4978/15692] intraday_13617.csv.gz  in=270,813,435 out=55,929,094 elapsed=95.2s

  [4979/15692] intraday_13615.csv.gz  in=270,823,037 out=55,938,696 elapsed=95.2s

  [4980/15692] intraday_13619.csv.gz  in=270,851,177 out=55,966,836 elapsed=95.2s

  [4981/15692] intraday_1362.csv.gz  in=270,863,597 out=55,966,836 elapsed=95.2s

  [4982/15692] intraday_13618.csv.gz  in=270,895,668 out=55,998,907 elapsed=95.3s

  [4983/15692] intraday_13620.csv.gz  in=270,922,431 out=56,025,670 elapsed=95.3s

  [4984/15692] intraday_13621.csv.gz  in=270,944,850 out=56,048,089 elapsed=95.3s

  [4985/15692] intraday_13622.csv.gz  in=270,962,541 out=56,065,780 elapsed=95.3s

  [4986/15692] intraday_13623.csv.gz  in=270,989,667 out=56,092,906 elapsed=95.3s

  [4987/15692] intraday_13624.csv.gz  in=271,015,137 out=56,118,376 elapsed=95.3s

  [4988/15692] intraday_13626.csv.gz  in=271,040,232 out=56,143,471 elapsed=95.4s

  [4989/15692] intraday_13625.csv.gz  in=271,065,923 out=56,169,162 elapsed=95.4s

  [4990/15692] intraday_13627.csv.gz  in=271,089,331 out=56,192,570 elapsed=95.4s

  [4991/15692] intraday_13628.csv.gz  in=271,100,487 out=56,203,726 elapsed=95.4s

  [4992/15692] intraday_13629.csv.gz  in=271,100,488 out=56,203,727 elapsed=95.4s

  [4993/15692] intraday_1363.csv.gz  in=271,111,118 out=56,203,727 elapsed=95.4s

  [4994/15692] intraday_13630.csv.gz  in=271,131,129 out=56,223,738 elapsed=95.4s

  [4995/15692] intraday_13632.csv.gz  in=271,149,391 out=56,242,000 elapsed=95.5s

  [4996/15692] intraday_13633.csv.gz  in=271,173,120 out=56,265,729 elapsed=95.5s

  [4997/15692] intraday_13631.csv.gz  in=271,197,120 out=56,289,729 elapsed=95.5s

  [4998/15692] intraday_13634.csv.gz  in=271,223,276 out=56,315,885 elapsed=95.5s

  [4999/15692] intraday_13636.csv.gz  in=271,254,929 out=56,347,203 elapsed=95.5s

  [5000/15692] intraday_13638.csv.gz  in=271,278,361 out=56,370,635 elapsed=95.6s

  [5001/15692] intraday_13635.csv.gz  in=271,306,748 out=56,399,022 elapsed=95.6s

  [5002/15692] intraday_13637.csv.gz  in=271,337,230 out=56,429,504 elapsed=95.6s

  [5003/15692] intraday_1364.csv.gz  in=271,350,345 out=56,429,504 elapsed=95.6s

  [5004/15692] intraday_13639.csv.gz  in=271,377,704 out=56,456,863 elapsed=95.6s

  [5005/15692] intraday_13640.csv.gz  in=271,399,704 out=56,478,863 elapsed=95.6s

  [5006/15692] intraday_13642.csv.gz  in=271,400,862 out=56,480,021 elapsed=95.6s

  [5007/15692] intraday_13641.csv.gz  in=271,401,706 out=56,480,865 elapsed=95.6s

  [5008/15692] intraday_13643.csv.gz  in=271,428,757 out=56,507,916 elapsed=95.7s

  [5009/15692] intraday_13646.csv.gz  in=271,453,035 out=56,532,194 elapsed=95.7s

  [5010/15692] intraday_13647.csv.gz  in=271,476,825 out=56,555,984 elapsed=95.7s

  [5011/15692] intraday_13645.csv.gz  in=271,502,521 out=56,581,680 elapsed=95.7s

  [5012/15692] intraday_13644.csv.gz  in=271,528,131 out=56,607,290 elapsed=95.7s

  [5013/15692] intraday_1365.csv.gz  in=271,539,675 out=56,607,290 elapsed=95.7s

  [5014/15692] intraday_13648.csv.gz  in=271,564,196 out=56,631,811 elapsed=95.8s

  [5015/15692] intraday_13649.csv.gz  in=271,588,842 out=56,656,457 elapsed=95.8s

  [5016/15692] intraday_13650.csv.gz  in=271,613,415 out=56,681,030 elapsed=95.8s

  [5017/15692] intraday_13651.csv.gz  in=271,634,834 out=56,702,449 elapsed=95.8s

  [5018/15692] intraday_13652.csv.gz  in=271,660,214 out=56,727,829 elapsed=95.8s

  [5019/15692] intraday_13655.csv.gz  in=271,686,885 out=56,754,500 elapsed=95.9s

  [5020/15692] intraday_13656.csv.gz  in=271,705,816 out=56,771,758 elapsed=95.9s

  [5021/15692] intraday_13653.csv.gz  in=271,731,156 out=56,797,098 elapsed=95.9s

  [5022/15692] intraday_13654.csv.gz  in=271,757,631 out=56,823,573 elapsed=95.9s

  [5023/15692] intraday_13657.csv.gz  in=271,768,051 out=56,833,993 elapsed=95.9s

  [5024/15692] intraday_1366.csv.gz  in=271,780,309 out=56,833,993 elapsed=95.9s

  [5025/15692] intraday_13658.csv.gz  in=271,805,887 out=56,859,571 elapsed=95.9s

  [5026/15692] intraday_13659.csv.gz  in=271,831,313 out=56,884,997 elapsed=96.0s

  [5027/15692] intraday_13661.csv.gz  in=271,860,359 out=56,914,043 elapsed=96.0s

  [5028/15692] intraday_13660.csv.gz  in=271,883,752 out=56,937,436 elapsed=96.0s

  [5029/15692] intraday_13662.csv.gz  in=271,916,434 out=56,970,118 elapsed=96.0s

  [5030/15692] intraday_13663.csv.gz  in=271,941,225 out=56,994,909 elapsed=96.0s

  [5031/15692] intraday_13664.csv.gz  in=271,971,555 out=57,025,239 elapsed=96.0s

  [5032/15692] intraday_13667.csv.gz  in=271,974,793 out=57,028,477 elapsed=96.0s

  [5033/15692] intraday_13665.csv.gz  in=272,009,939 out=57,063,623 elapsed=96.1s

  [5034/15692] intraday_13668.csv.gz  in=272,021,571 out=57,075,255 elapsed=96.1s

  [5035/15692] intraday_1367.csv.gz  in=272,029,459 out=57,075,255 elapsed=96.1s

  [5036/15692] intraday_13666.csv.gz  in=272,065,262 out=57,111,058 elapsed=96.1s

  [5037/15692] intraday_13670.csv.gz  in=272,082,966 out=57,128,762 elapsed=96.2s

  [5038/15692] intraday_13669.csv.gz  in=272,108,865 out=57,154,661 elapsed=96.2s

  [5039/15692] intraday_13671.csv.gz  in=272,136,916 out=57,182,712 elapsed=96.2s

  [5040/15692] intraday_13672.csv.gz  in=272,159,226 out=57,205,022 elapsed=96.2s

  [5041/15692] intraday_13674.csv.gz  in=272,187,889 out=57,233,685 elapsed=96.2s

  [5042/15692] intraday_13673.csv.gz  in=272,210,568 out=57,256,364 elapsed=96.2s

  [5043/15692] intraday_13676.csv.gz  in=272,229,605 out=57,275,401 elapsed=96.3s

  [5044/15692] intraday_13675.csv.gz  in=272,257,686 out=57,303,482 elapsed=96.3s

  [5045/15692] intraday_13678.csv.gz  in=272,281,639 out=57,327,435 elapsed=96.3s

  [5046/15692] intraday_13677.csv.gz  in=272,306,861 out=57,352,657 elapsed=96.3s

  [5047/15692] intraday_13679.csv.gz  in=272,321,618 out=57,367,414 elapsed=96.3s

  [5048/15692] intraday_1368.csv.gz  in=272,332,677 out=57,367,414 elapsed=96.3s

  [5049/15692] intraday_13680.csv.gz  in=272,333,405 out=57,368,142 elapsed=96.3s

  [5050/15692] intraday_13681.csv.gz  in=272,335,182 out=57,369,919 elapsed=96.3s

  [5051/15692] intraday_13685.csv.gz  in=272,357,120 out=57,391,857 elapsed=96.4s

  [5052/15692] intraday_13683.csv.gz  in=272,381,561 out=57,416,298 elapsed=96.4s

  [5053/15692] intraday_13682.csv.gz  in=272,436,075 out=57,464,875 elapsed=96.4s

  [5054/15692] intraday_13684.csv.gz  in=272,467,762 out=57,496,562 elapsed=96.4s

  [5055/15692] intraday_13686.csv.gz  in=272,496,091 out=57,524,891 elapsed=96.5s

  [5056/15692] intraday_1369.csv.gz  in=272,503,613 out=57,524,891 elapsed=96.5s

  [5057/15692] intraday_13687.csv.gz  in=272,529,698 out=57,550,976 elapsed=96.5s

  [5058/15692] intraday_13689.csv.gz  in=272,553,226 out=57,574,504 elapsed=96.5s

  [5059/15692] intraday_13688.csv.gz  in=272,576,446 out=57,597,724 elapsed=96.5s

  [5060/15692] intraday_13690.csv.gz  in=272,589,373 out=57,610,651 elapsed=96.5s

  [5061/15692] intraday_13692.csv.gz  in=272,602,999 out=57,624,277 elapsed=96.5s

  [5062/15692] intraday_13691.csv.gz  in=272,625,826 out=57,647,104 elapsed=96.6s

  [5063/15692] intraday_13693.csv.gz  in=272,658,751 out=57,680,029 elapsed=96.6s

  [5064/15692] intraday_13694.csv.gz  in=272,690,966 out=57,711,255 elapsed=96.6s

  [5065/15692] intraday_13695.csv.gz  in=272,721,145 out=57,740,538 elapsed=96.6s

  [5066/15692] intraday_13696.csv.gz  in=272,744,618 out=57,764,011 elapsed=96.6s

  [5067/15692] intraday_13697.csv.gz  in=272,767,103 out=57,786,496 elapsed=96.7s

  [5068/15692] intraday_13698.csv.gz  in=272,796,143 out=57,815,536 elapsed=96.7s

  [5069/15692] intraday_1370.csv.gz  in=272,796,195 out=57,815,536 elapsed=96.7s

  [5070/15692] intraday_13699.csv.gz  in=272,826,712 out=57,846,053 elapsed=96.7s

  [5071/15692] intraday_13702.csv.gz  in=272,837,114 out=57,856,243 elapsed=96.7s

  [5072/15692] intraday_13701.csv.gz  in=272,862,191 out=57,881,320 elapsed=96.7s

  [5073/15692] intraday_13703.csv.gz  in=272,879,526 out=57,898,655 elapsed=96.7s

  [5074/15692] intraday_13700.csv.gz  in=272,901,854 out=57,920,983 elapsed=96.7s

  [5075/15692] intraday_13705.csv.gz  in=272,920,453 out=57,939,582 elapsed=96.8s

  [5076/15692] intraday_13704.csv.gz  in=272,949,342 out=57,968,471 elapsed=96.8s

  [5077/15692] intraday_13706.csv.gz  in=272,972,500 out=57,991,629 elapsed=96.8s

  [5078/15692] intraday_13708.csv.gz  in=272,996,899 out=58,016,028 elapsed=96.8s

  [5079/15692] intraday_13707.csv.gz  in=273,030,830 out=58,049,959 elapsed=96.8s

  [5080/15692] intraday_1371.csv.gz  in=273,031,055 out=58,049,959 elapsed=96.8s

  [5081/15692] intraday_13709.csv.gz  in=273,055,941 out=58,074,845 elapsed=96.9s

  [5082/15692] intraday_13710.csv.gz  in=273,080,128 out=58,099,032 elapsed=96.9s

  [5083/15692] intraday_13712.csv.gz  in=273,103,425 out=58,122,329 elapsed=96.9s

  [5084/15692] intraday_13711.csv.gz  in=273,139,525 out=58,157,295 elapsed=96.9s

  [5085/15692] intraday_13714.csv.gz  in=273,165,771 out=58,183,541 elapsed=96.9s

  [5086/15692] intraday_13715.csv.gz  in=273,174,504 out=58,192,274 elapsed=97.0s

  [5087/15692] intraday_13716.csv.gz  in=273,194,712 out=58,212,482 elapsed=97.0s

  [5088/15692] intraday_13713.csv.gz  in=273,223,832 out=58,241,602 elapsed=97.0s

  [5089/15692] intraday_1372.csv.gz  in=273,223,850 out=58,241,602 elapsed=97.0s

  [5090/15692] intraday_13717.csv.gz  in=273,245,485 out=58,263,237 elapsed=97.0s

  [5091/15692] intraday_13718.csv.gz  in=273,276,607 out=58,294,359 elapsed=97.1s

  [5092/15692] intraday_13719.csv.gz  in=273,308,474 out=58,326,226 elapsed=97.1s

  [5093/15692] intraday_13720.csv.gz  in=273,336,627 out=58,354,379 elapsed=97.1s

  [5094/15692] intraday_13721.csv.gz  in=273,357,996 out=58,375,748 elapsed=97.1s

  [5095/15692] intraday_13722.csv.gz  in=273,382,857 out=58,400,609 elapsed=97.1s

  [5096/15692] intraday_13723.csv.gz  in=273,407,426 out=58,425,178 elapsed=97.2s

  [5097/15692] intraday_13725.csv.gz  in=273,431,781 out=58,449,533 elapsed=97.2s

  [5098/15692] intraday_13726.csv.gz  in=273,453,673 out=58,471,425 elapsed=97.2s

  [5099/15692] intraday_13724.csv.gz  in=273,499,511 out=58,513,437 elapsed=97.2s

  [5100/15692] intraday_13728.csv.gz  in=273,508,222 out=58,522,148 elapsed=97.2s

  [5101/15692] intraday_13727.csv.gz  in=273,527,239 out=58,541,165 elapsed=97.2s

  [5102/15692] intraday_1373.csv.gz  in=273,527,285 out=58,541,165 elapsed=97.2s

  [5103/15692] intraday_13729.csv.gz  in=273,550,239 out=58,564,119 elapsed=97.2s

  [5104/15692] intraday_13732.csv.gz  in=273,575,352 out=58,589,232 elapsed=97.3s

  [5105/15692] intraday_13731.csv.gz  in=273,604,791 out=58,618,671 elapsed=97.3s

  [5106/15692] intraday_13733.csv.gz  in=273,635,147 out=58,647,745 elapsed=97.3s

  [5107/15692] intraday_13730.csv.gz  in=273,667,748 out=58,680,056 elapsed=97.3s

  [5108/15692] intraday_13734.csv.gz  in=273,694,869 out=58,707,177 elapsed=97.3s

  [5109/15692] intraday_13735.csv.gz  in=273,715,929 out=58,728,237 elapsed=97.4s

  [5110/15692] intraday_13737.csv.gz  in=273,739,077 out=58,751,385 elapsed=97.4s

  [5111/15692] intraday_13736.csv.gz  in=273,762,757 out=58,775,065 elapsed=97.4s

  [5112/15692] intraday_1374.csv.gz  in=273,762,761 out=58,775,065 elapsed=97.4s

  [5113/15692] intraday_13738.csv.gz  in=273,784,052 out=58,796,356 elapsed=97.4s

  [5114/15692] intraday_13741.csv.gz  in=273,790,796 out=58,803,100 elapsed=97.4s

  [5115/15692] intraday_13740.csv.gz  in=273,806,183 out=58,818,487 elapsed=97.4s

  [5116/15692] intraday_13739.csv.gz  in=273,835,312 out=58,847,616 elapsed=97.4s

  [5117/15692] intraday_13742.csv.gz  in=273,859,205 out=58,871,509 elapsed=97.5s

  [5118/15692] intraday_13743.csv.gz  in=273,894,822 out=58,905,213 elapsed=97.5s

  [5119/15692] intraday_13744.csv.gz  in=273,917,856 out=58,928,247 elapsed=97.5s

  [5120/15692] intraday_13745.csv.gz  in=273,945,450 out=58,955,841 elapsed=97.5s

  [5121/15692] intraday_13746.csv.gz  in=273,980,622 out=58,988,936 elapsed=97.5s

  [5122/15692] intraday_13747.csv.gz  in=274,003,037 out=59,011,351 elapsed=97.5s

  [5123/15692] intraday_1375.csv.gz  in=274,003,099 out=59,011,351 elapsed=97.6s

  [5124/15692] intraday_13749.csv.gz  in=274,030,182 out=59,037,133 elapsed=97.6s

  [5125/15692] intraday_13748.csv.gz  in=274,054,134 out=59,061,085 elapsed=97.6s

  [5126/15692] intraday_13750.csv.gz  in=274,082,045 out=59,088,996 elapsed=97.6s

  [5127/15692] intraday_13751.csv.gz  in=274,112,879 out=59,119,830 elapsed=97.7s

  [5128/15692] intraday_13754.csv.gz  in=274,121,203 out=59,128,154 elapsed=97.7s

  [5129/15692] intraday_13752.csv.gz  in=274,154,814 out=59,159,843 elapsed=97.7s

  [5130/15692] intraday_13753.csv.gz  in=274,179,510 out=59,184,539 elapsed=97.7s

  [5131/15692] intraday_13757.csv.gz  in=274,203,701 out=59,208,730 elapsed=97.7s

  [5132/15692] intraday_13756.csv.gz  in=274,230,039 out=59,235,068 elapsed=97.8s

  [5133/15692] intraday_13755.csv.gz  in=274,255,195 out=59,260,224 elapsed=97.8s

  [5134/15692] intraday_13758.csv.gz  in=274,281,260 out=59,286,289 elapsed=97.8s

  [5135/15692] intraday_1376.csv.gz  in=274,281,346 out=59,286,289 elapsed=97.8s

  [5136/15692] intraday_13759.csv.gz  in=274,300,968 out=59,305,911 elapsed=97.8s

  [5137/15692] intraday_13760.csv.gz  in=274,325,124 out=59,330,067 elapsed=97.8s

  [5138/15692] intraday_13762.csv.gz  in=274,348,692 out=59,353,635 elapsed=97.8s

  [5139/15692] intraday_13761.csv.gz  in=274,376,998 out=59,381,941 elapsed=97.9s

  [5140/15692] intraday_13763.csv.gz  in=274,400,495 out=59,405,438 elapsed=97.9s

  [5141/15692] intraday_13764.csv.gz  in=274,419,065 out=59,424,008 elapsed=97.9s

  [5142/15692] intraday_13765.csv.gz  in=274,442,726 out=59,447,669 elapsed=97.9s

  [5143/15692] intraday_13767.csv.gz  in=274,443,311 out=59,448,254 elapsed=97.9s

  [5144/15692] intraday_13768.csv.gz  in=274,444,002 out=59,448,945 elapsed=97.9s

  [5145/15692] intraday_1377.csv.gz  in=274,444,886 out=59,448,945 elapsed=97.9s

  [5146/15692] intraday_13766.csv.gz  in=274,475,955 out=59,480,014 elapsed=97.9s

  [5147/15692] intraday_13769.csv.gz  in=274,497,328 out=59,501,387 elapsed=97.9s

  [5148/15692] intraday_13771.csv.gz  in=274,519,666 out=59,523,725 elapsed=98.0s

  [5149/15692] intraday_13770.csv.gz  in=274,544,868 out=59,548,927 elapsed=98.0s

  [5150/15692] intraday_13772.csv.gz  in=274,571,289 out=59,575,348 elapsed=98.0s

  [5151/15692] intraday_13774.csv.gz  in=274,595,009 out=59,599,068 elapsed=98.1s

  [5152/15692] intraday_13773.csv.gz  in=274,617,994 out=59,622,053 elapsed=98.1s

  [5153/15692] intraday_13776.csv.gz  in=274,643,238 out=59,647,297 elapsed=98.1s

  [5154/15692] intraday_13775.csv.gz  in=274,670,261 out=59,674,320 elapsed=98.1s

  [5155/15692] intraday_13777.csv.gz  in=274,695,500 out=59,699,559 elapsed=98.2s

  [5156/15692] intraday_13778.csv.gz  in=274,718,150 out=59,722,209 elapsed=98.2s

  [5157/15692] intraday_13779.csv.gz  in=274,743,775 out=59,747,834 elapsed=98.2s

  [5158/15692] intraday_1378.csv.gz  in=274,760,157 out=59,747,834 elapsed=98.2s

  [5159/15692] intraday_13783.csv.gz  in=274,760,164 out=59,747,841 elapsed=98.2s

  [5160/15692] intraday_13781.csv.gz  in=274,785,190 out=59,772,686 elapsed=98.2s

  [5161/15692] intraday_13780.csv.gz  in=274,809,632 out=59,797,128 elapsed=98.2s

  [5162/15692] intraday_13782.csv.gz  in=274,818,579 out=59,806,075 elapsed=98.2s

  [5163/15692] intraday_13785.csv.gz  in=274,843,742 out=59,831,238 elapsed=98.3s

  [5164/15692] intraday_13784.csv.gz  in=274,870,523 out=59,858,019 elapsed=98.3s

  [5165/15692] intraday_13787.csv.gz  in=274,896,127 out=59,883,623 elapsed=98.3s

  [5166/15692] intraday_13786.csv.gz  in=274,923,868 out=59,911,364 elapsed=98.3s

  [5167/15692] intraday_1379.csv.gz  in=274,938,482 out=59,911,364 elapsed=98.4s

  [5168/15692] intraday_13789.csv.gz  in=274,959,668 out=59,932,550 elapsed=98.4s

  [5169/15692] intraday_13790.csv.gz  in=274,985,949 out=59,958,304 elapsed=98.4s

  [5170/15692] intraday_13788.csv.gz  in=275,018,369 out=59,990,724 elapsed=98.4s

  [5171/15692] intraday_13792.csv.gz  in=275,047,874 out=60,020,229 elapsed=98.4s

  [5172/15692] intraday_13794.csv.gz  in=275,051,328 out=60,023,683 elapsed=98.5s

  [5173/15692] intraday_13793.csv.gz  in=275,066,112 out=60,038,467 elapsed=98.5s

  [5174/15692] intraday_13791.csv.gz  in=275,094,454 out=60,066,809 elapsed=98.5s

  [5175/15692] intraday_13795.csv.gz  in=275,122,520 out=60,094,875 elapsed=98.5s

  [5176/15692] intraday_13796.csv.gz  in=275,149,542 out=60,121,897 elapsed=98.5s

  [5177/15692] intraday_13797.csv.gz  in=275,183,870 out=60,156,225 elapsed=98.5s

  [5178/15692] intraday_1380.csv.gz  in=275,196,831 out=60,156,225 elapsed=98.6s

  [5179/15692] intraday_13799.csv.gz  in=275,225,842 out=60,184,854 elapsed=98.6s

  [5180/15692] intraday_13798.csv.gz  in=275,262,286 out=60,221,298 elapsed=98.6s

  [5181/15692] intraday_13800.csv.gz  in=275,291,094 out=60,250,106 elapsed=98.6s

  [5182/15692] intraday_13801.csv.gz  in=275,313,256 out=60,272,268 elapsed=98.6s

  [5183/15692] intraday_13804.csv.gz  in=275,340,318 out=60,299,330 elapsed=98.7s

  [5184/15692] intraday_13803.csv.gz  in=275,360,311 out=60,319,323 elapsed=98.7s

  [5185/15692] intraday_13802.csv.gz  in=275,386,352 out=60,345,364 elapsed=98.7s

  [5186/15692] intraday_13805.csv.gz  in=275,404,016 out=60,363,028 elapsed=98.7s

  [5187/15692] intraday_13806.csv.gz  in=275,405,510 out=60,364,522 elapsed=98.7s

  [5188/15692] intraday_13807.csv.gz  in=275,433,904 out=60,392,916 elapsed=98.7s

  [5189/15692] intraday_13809.csv.gz  in=275,457,650 out=60,416,662 elapsed=98.7s

  [5190/15692] intraday_1381.csv.gz  in=275,472,556 out=60,416,662 elapsed=98.7s

  [5191/15692] intraday_13808.csv.gz  in=275,495,109 out=60,439,215 elapsed=98.7s

  [5192/15692] intraday_13810.csv.gz  in=275,516,690 out=60,460,796 elapsed=98.8s

  [5193/15692] intraday_13812.csv.gz  in=275,540,833 out=60,484,939 elapsed=98.8s

  [5194/15692] intraday_13811.csv.gz  in=275,568,314 out=60,512,304 elapsed=98.8s

  [5195/15692] intraday_13813.csv.gz  in=275,594,376 out=60,538,366 elapsed=98.8s

  [5196/15692] intraday_13814.csv.gz  in=275,624,106 out=60,568,096 elapsed=98.8s

  [5197/15692] intraday_13815.csv.gz  in=275,651,797 out=60,595,787 elapsed=98.9s

  [5198/15692] intraday_13818.csv.gz  in=275,653,602 out=60,597,592 elapsed=98.9s

  [5199/15692] intraday_13817.csv.gz  in=275,677,918 out=60,621,908 elapsed=98.9s

  [5200/15692] intraday_13819.csv.gz  in=275,687,017 out=60,631,007 elapsed=98.9s

  [5201/15692] intraday_1382.csv.gz  in=275,701,567 out=60,631,007 elapsed=98.9s

  [5202/15692] intraday_13816.csv.gz  in=275,728,776 out=60,658,216 elapsed=98.9s

  [5203/15692] intraday_13821.csv.gz  in=275,747,718 out=60,677,158 elapsed=99.0s

  [5204/15692] intraday_13820.csv.gz  in=275,776,152 out=60,705,466 elapsed=99.0s

  [5205/15692] intraday_13822.csv.gz  in=275,796,396 out=60,725,710 elapsed=99.0s

  [5206/15692] intraday_13823.csv.gz  in=275,824,250 out=60,753,564 elapsed=99.0s

  [5207/15692] intraday_13824.csv.gz  in=275,840,189 out=60,769,503 elapsed=99.0s

  [5208/15692] intraday_13825.csv.gz  in=275,851,821 out=60,781,135 elapsed=99.0s

  [5209/15692] intraday_13826.csv.gz  in=275,863,889 out=60,793,203 elapsed=99.1s

  [5210/15692] intraday_13827.csv.gz  in=275,875,245 out=60,804,452 elapsed=99.1s

  [5211/15692] intraday_13828.csv.gz  in=275,886,461 out=60,815,668 elapsed=99.1s

  [5212/15692] intraday_13829.csv.gz  in=275,899,978 out=60,829,185 elapsed=99.1s

  [5213/15692] intraday_1383.csv.gz  in=275,914,898 out=60,829,185 elapsed=99.1s

  [5214/15692] intraday_13830.csv.gz  in=275,927,300 out=60,841,587 elapsed=99.1s

  [5215/15692] intraday_13831.csv.gz  in=275,938,512 out=60,852,799 elapsed=99.1s

  [5216/15692] intraday_13833.csv.gz  in=275,938,834 out=60,853,121 elapsed=99.1s

  [5217/15692] intraday_13834.csv.gz  in=275,939,884 out=60,854,171 elapsed=99.1s

  [5218/15692] intraday_13832.csv.gz  in=275,943,728 out=60,858,015 elapsed=99.2s

  [5219/15692] intraday_13835.csv.gz  in=275,954,516 out=60,868,803 elapsed=99.2s

  [5220/15692] intraday_13837.csv.gz  in=275,963,610 out=60,877,897 elapsed=99.2s

  [5221/15692] intraday_13836.csv.gz  in=275,977,682 out=60,891,969 elapsed=99.2s

  [5222/15692] intraday_13838.csv.gz  in=275,987,764 out=60,902,051 elapsed=99.2s

  [5223/15692] intraday_1384.csv.gz  in=276,001,240 out=60,902,051 elapsed=99.2s

  [5224/15692] intraday_13839.csv.gz  in=276,018,163 out=60,918,974 elapsed=99.2s

  [5225/15692] intraday_13841.csv.gz  in=276,028,306 out=60,929,117 elapsed=99.2s

  [5226/15692] intraday_13840.csv.gz  in=276,042,529 out=60,943,340 elapsed=99.3s

  [5227/15692] intraday_13843.csv.gz  in=276,058,004 out=60,958,815 elapsed=99.3s

  [5228/15692] intraday_13842.csv.gz  in=276,069,912 out=60,970,723 elapsed=99.3s

  [5229/15692] intraday_13844.csv.gz  in=276,081,246 out=60,982,057 elapsed=99.3s

  [5230/15692] intraday_13845.csv.gz  in=276,095,228 out=60,996,039 elapsed=99.3s

  [5231/15692] intraday_13847.csv.gz  in=276,095,401 out=60,996,212 elapsed=99.3s

  [5232/15692] intraday_13846.csv.gz  in=276,101,809 out=61,002,620 elapsed=99.3s

  [5233/15692] intraday_13848.csv.gz  in=276,111,040 out=61,011,851 elapsed=99.3s

  [5234/15692] intraday_13850.csv.gz  in=276,122,909 out=61,023,720 elapsed=99.3s

  [5235/15692] intraday_13849.csv.gz  in=276,134,837 out=61,035,648 elapsed=99.3s

  [5236/15692] intraday_1385.csv.gz  in=276,148,183 out=61,035,648 elapsed=99.3s

  [5237/15692] intraday_13851.csv.gz  in=276,161,608 out=61,049,073 elapsed=99.3s

  [5238/15692] intraday_13854.csv.gz  in=276,171,060 out=61,058,525 elapsed=99.4s

  [5239/15692] intraday_13852.csv.gz  in=276,186,411 out=61,073,876 elapsed=99.4s

  [5240/15692] intraday_13853.csv.gz  in=276,199,273 out=61,086,738 elapsed=99.4s

  [5241/15692] intraday_13855.csv.gz  in=276,212,046 out=61,099,511 elapsed=99.4s

  [5242/15692] intraday_13856.csv.gz  in=276,223,216 out=61,110,681 elapsed=99.4s

  [5243/15692] intraday_13857.csv.gz  in=276,234,953 out=61,122,418 elapsed=99.4s

  [5244/15692] intraday_13858.csv.gz  in=276,246,285 out=61,133,750 elapsed=99.4s

  [5245/15692] intraday_1386.csv.gz  in=276,260,712 out=61,133,750 elapsed=99.4s

  [5246/15692] intraday_13860.csv.gz  in=276,271,806 out=61,144,844 elapsed=99.5s

  [5247/15692] intraday_13859.csv.gz  in=276,282,715 out=61,155,753 elapsed=99.5s

  [5248/15692] intraday_13861.csv.gz  in=276,292,190 out=61,165,228 elapsed=99.5s

  [5249/15692] intraday_13862.csv.gz  in=276,303,042 out=61,176,080 elapsed=99.5s

  [5250/15692] intraday_13863.csv.gz  in=276,314,001 out=61,187,039 elapsed=99.5s

  [5251/15692] intraday_13865.csv.gz  in=276,325,733 out=61,198,771 elapsed=99.5s

  [5252/15692] intraday_13867.csv.gz  in=276,334,875 out=61,207,910 elapsed=99.5s

  [5253/15692] intraday_13864.csv.gz  in=276,350,027 out=61,223,062 elapsed=99.5s

  [5254/15692] intraday_13866.csv.gz  in=276,364,151 out=61,237,186 elapsed=99.5s

  [5255/15692] intraday_13868.csv.gz  in=276,364,483 out=61,237,518 elapsed=99.5s

  [5256/15692] intraday_13869.csv.gz  in=276,373,713 out=61,246,748 elapsed=99.5s

  [5257/15692] intraday_1387.csv.gz  in=276,389,020 out=61,246,748 elapsed=99.6s

  [5258/15692] intraday_13870.csv.gz  in=276,400,072 out=61,257,800 elapsed=99.6s

  [5259/15692] intraday_13871.csv.gz  in=276,411,122 out=61,268,850 elapsed=99.6s

  [5260/15692] intraday_13872.csv.gz  in=276,423,466 out=61,281,194 elapsed=99.6s

  [5261/15692] intraday_13873.csv.gz  in=276,435,947 out=61,293,675 elapsed=99.6s

  [5262/15692] intraday_13876.csv.gz  in=276,446,372 out=61,304,100 elapsed=99.6s

  [5263/15692] intraday_13874.csv.gz  in=276,458,950 out=61,316,678 elapsed=99.6s

  [5264/15692] intraday_13875.csv.gz  in=276,470,526 out=61,328,254 elapsed=99.7s

  [5265/15692] intraday_13877.csv.gz  in=276,482,608 out=61,340,336 elapsed=99.7s

  [5266/15692] intraday_13878.csv.gz  in=276,493,754 out=61,351,378 elapsed=99.7s

  [5267/15692] intraday_13879.csv.gz  in=276,505,344 out=61,362,968 elapsed=99.7s

  [5268/15692] intraday_1388.csv.gz  in=276,515,734 out=61,362,968 elapsed=99.7s

  [5269/15692] intraday_13880.csv.gz  in=276,526,991 out=61,374,225 elapsed=99.7s

  [5270/15692] intraday_13881.csv.gz  in=276,532,568 out=61,379,802 elapsed=99.7s

  [5271/15692] intraday_13882.csv.gz  in=276,542,970 out=61,390,204 elapsed=99.7s

  [5272/15692] intraday_13883.csv.gz  in=276,552,888 out=61,400,122 elapsed=99.8s

  [5273/15692] intraday_13884.csv.gz  in=276,566,280 out=61,413,514 elapsed=99.8s

  [5274/15692] intraday_13885.csv.gz  in=276,579,140 out=61,426,374 elapsed=99.8s

  [5275/15692] intraday_13886.csv.gz  in=276,593,559 out=61,440,793 elapsed=99.8s

  [5276/15692] intraday_13887.csv.gz  in=276,605,045 out=61,452,279 elapsed=99.8s

  [5277/15692] intraday_13889.csv.gz  in=276,614,887 out=61,462,121 elapsed=99.8s

  [5278/15692] intraday_1389.csv.gz  in=276,627,710 out=61,462,121 elapsed=99.8s

  [5279/15692] intraday_13888.csv.gz  in=276,638,848 out=61,473,259 elapsed=99.8s

  [5280/15692] intraday_13892.csv.gz  in=276,639,922 out=61,474,333 elapsed=99.8s

  [5281/15692] intraday_13890.csv.gz  in=276,652,838 out=61,487,249 elapsed=99.9s

  [5282/15692] intraday_13893.csv.gz  in=276,656,955 out=61,491,366 elapsed=99.9s

  [5283/15692] intraday_13891.csv.gz  in=276,668,829 out=61,503,240 elapsed=99.9s

  [5284/15692] intraday_13894.csv.gz  in=276,678,947 out=61,513,358 elapsed=99.9s

  [5285/15692] intraday_13897.csv.gz  in=276,690,083 out=61,524,494 elapsed=99.9s

  [5286/15692] intraday_13896.csv.gz  in=276,700,767 out=61,535,178 elapsed=99.9s

  [5287/15692] intraday_13895.csv.gz  in=276,714,285 out=61,548,696 elapsed=99.9s

  [5288/15692] intraday_13898.csv.gz  in=276,724,762 out=61,559,173 elapsed=99.9s

  [5289/15692] intraday_1390.csv.gz  in=276,740,212 out=61,559,173 elapsed=100.0s

  [5290/15692] intraday_13899.csv.gz  in=276,750,759 out=61,569,720 elapsed=100.0s

  [5291/15692] intraday_13901.csv.gz  in=276,763,259 out=61,582,220 elapsed=100.0s

  [5292/15692] intraday_13900.csv.gz  in=276,775,291 out=61,594,252 elapsed=100.0s

  [5293/15692] intraday_13902.csv.gz  in=276,792,713 out=61,611,674 elapsed=100.0s

  [5294/15692] intraday_13905.csv.gz  in=276,803,510 out=61,622,471 elapsed=100.3s

  [5295/15692] intraday_13903.csv.gz  in=276,816,051 out=61,635,012 elapsed=100.3s

  [5296/15692] intraday_13904.csv.gz  in=276,827,318 out=61,646,279 elapsed=100.3s

  [5297/15692] intraday_13906.csv.gz  in=276,838,474 out=61,657,435 elapsed=100.3s

  [5298/15692] intraday_13907.csv.gz  in=276,850,931 out=61,669,892 elapsed=100.3s

  [5299/15692] intraday_1391.csv.gz  in=276,862,644 out=61,669,892 elapsed=100.3s

  [5300/15692] intraday_13908.csv.gz  in=276,874,366 out=61,681,614 elapsed=100.3s

  [5301/15692] intraday_13909.csv.gz  in=276,883,694 out=61,690,942 elapsed=100.3s

  [5302/15692] intraday_13913.csv.gz  in=276,896,021 out=61,703,269 elapsed=100.4s

  [5303/15692] intraday_13911.csv.gz  in=276,906,877 out=61,714,125 elapsed=100.4s

  [5304/15692] intraday_13912.csv.gz  in=276,917,844 out=61,725,092 elapsed=100.4s

  [5305/15692] intraday_13910.csv.gz  in=276,931,015 out=61,738,263 elapsed=100.4s

  [5306/15692] intraday_13914.csv.gz  in=276,942,792 out=61,750,040 elapsed=100.4s

  [5307/15692] intraday_13917.csv.gz  in=276,943,765 out=61,751,013 elapsed=100.4s

  [5308/15692] intraday_13916.csv.gz  in=276,950,344 out=61,757,592 elapsed=100.5s

  [5309/15692] intraday_13915.csv.gz  in=276,962,247 out=61,769,495 elapsed=100.5s

  [5310/15692] intraday_13918.csv.gz  in=276,975,084 out=61,782,332 elapsed=100.5s

  [5311/15692] intraday_13919.csv.gz  in=276,987,708 out=61,794,956 elapsed=100.5s

  [5312/15692] intraday_13920.csv.gz  in=276,997,732 out=61,804,980 elapsed=100.5s

  [5313/15692] intraday_1392.csv.gz  in=277,008,683 out=61,804,980 elapsed=100.5s

  [5314/15692] intraday_13921.csv.gz  in=277,020,564 out=61,816,861 elapsed=100.5s

  [5315/15692] intraday_13922.csv.gz  in=277,031,671 out=61,827,968 elapsed=100.5s

  [5316/15692] intraday_13924.csv.gz  in=277,042,044 out=61,838,341 elapsed=100.6s

  [5317/15692] intraday_13923.csv.gz  in=277,057,003 out=61,853,300 elapsed=100.6s

  [5318/15692] intraday_13925.csv.gz  in=277,067,802 out=61,864,099 elapsed=100.6s

  [5319/15692] intraday_13927.csv.gz  in=277,082,754 out=61,879,051 elapsed=100.6s

  [5320/15692] intraday_13926.csv.gz  in=277,095,510 out=61,891,807 elapsed=100.6s

  [5321/15692] intraday_13928.csv.gz  in=277,107,552 out=61,903,849 elapsed=100.6s

  [5322/15692] intraday_13929.csv.gz  in=277,120,407 out=61,916,704 elapsed=100.7s

  [5323/15692] intraday_1393.csv.gz  in=277,134,671 out=61,916,704 elapsed=100.7s

  [5324/15692] intraday_13930.csv.gz  in=277,147,607 out=61,929,640 elapsed=100.7s

  [5325/15692] intraday_13931.csv.gz  in=277,160,615 out=61,942,648 elapsed=100.7s

  [5326/15692] intraday_13932.csv.gz  in=277,173,214 out=61,955,247 elapsed=100.7s

  [5327/15692] intraday_13933.csv.gz  in=277,187,053 out=61,969,086 elapsed=100.7s

  [5328/15692] intraday_13934.csv.gz  in=277,204,774 out=61,986,807 elapsed=100.7s

  [5329/15692] intraday_13936.csv.gz  in=277,219,022 out=62,001,055 elapsed=100.8s

  [5330/15692] intraday_13937.csv.gz  in=277,230,987 out=62,013,020 elapsed=100.8s

  [5331/15692] intraday_13935.csv.gz  in=277,242,624 out=62,024,657 elapsed=100.8s

  [5332/15692] intraday_13938.csv.gz  in=277,256,147 out=62,038,180 elapsed=100.8s

  [5333/15692] intraday_1394.csv.gz  in=277,269,346 out=62,038,180 elapsed=100.8s

  [5334/15692] intraday_13939.csv.gz  in=277,279,110 out=62,047,944 elapsed=100.8s

  [5335/15692] intraday_13940.csv.gz  in=277,290,447 out=62,059,281 elapsed=100.8s

  [5336/15692] intraday_13941.csv.gz  in=277,302,695 out=62,071,529 elapsed=100.9s

  [5337/15692] intraday_13942.csv.gz  in=277,314,354 out=62,083,188 elapsed=100.9s

  [5338/15692] intraday_13943.csv.gz  in=277,325,229 out=62,094,063 elapsed=100.9s

  [5339/15692] intraday_13944.csv.gz  in=277,339,940 out=62,108,774 elapsed=100.9s

  [5340/15692] intraday_13947.csv.gz  in=277,350,914 out=62,119,748 elapsed=100.9s

  [5341/15692] intraday_13946.csv.gz  in=277,363,086 out=62,131,920 elapsed=100.9s

  [5342/15692] intraday_13945.csv.gz  in=277,372,968 out=62,141,802 elapsed=100.9s

  [5343/15692] intraday_13949.csv.gz  in=277,385,526 out=62,154,360 elapsed=100.9s

  [5344/15692] intraday_13948.csv.gz  in=277,397,981 out=62,166,815 elapsed=100.9s

  [5345/15692] intraday_1395.csv.gz  in=277,411,612 out=62,166,815 elapsed=100.9s

  [5346/15692] intraday_13950.csv.gz  in=277,424,233 out=62,179,436 elapsed=101.0s

  [5347/15692] intraday_13953.csv.gz  in=277,436,230 out=62,191,433 elapsed=101.0s

  [5348/15692] intraday_13951.csv.gz  in=277,449,736 out=62,204,939 elapsed=101.0s

  [5349/15692] intraday_13952.csv.gz  in=277,462,764 out=62,217,967 elapsed=101.0s

  [5350/15692] intraday_13954.csv.gz  in=277,475,169 out=62,230,372 elapsed=101.0s

  [5351/15692] intraday_13955.csv.gz  in=277,485,974 out=62,241,177 elapsed=101.0s

  [5352/15692] intraday_13956.csv.gz  in=277,499,462 out=62,254,665 elapsed=101.1s

  [5353/15692] intraday_13958.csv.gz  in=277,511,803 out=62,267,006 elapsed=101.1s

  [5354/15692] intraday_13957.csv.gz  in=277,522,488 out=62,277,691 elapsed=101.1s

  [5355/15692] intraday_1396.csv.gz  in=277,535,234 out=62,277,691 elapsed=101.1s

  [5356/15692] intraday_13959.csv.gz  in=277,546,376 out=62,288,833 elapsed=101.1s

  [5357/15692] intraday_13962.csv.gz  in=277,547,937 out=62,290,394 elapsed=101.1s

  [5358/15692] intraday_13960.csv.gz  in=277,556,626 out=62,299,083 elapsed=101.1s

  [5359/15692] intraday_13963.csv.gz  in=277,558,281 out=62,300,018 elapsed=101.1s

  [5360/15692] intraday_13966.csv.gz  in=277,558,283 out=62,300,020 elapsed=101.1s

  [5361/15692] intraday_13964.csv.gz  in=277,559,849 out=62,301,586 elapsed=101.1s

  [5362/15692] intraday_13961.csv.gz  in=277,573,382 out=62,315,119 elapsed=101.1s

  [5363/15692] intraday_13965.csv.gz  in=277,573,542 out=62,315,279 elapsed=101.1s

  [5364/15692] intraday_13968.csv.gz  in=277,573,676 out=62,315,413 elapsed=101.1s

  [5365/15692] intraday_13969.csv.gz  in=277,573,984 out=62,315,721 elapsed=101.2s

  [5366/15692] intraday_13970.csv.gz  in=277,574,100 out=62,315,837 elapsed=101.2s

  [5367/15692] intraday_1397.csv.gz  in=277,585,822 out=62,315,837 elapsed=101.2s

  [5368/15692] intraday_13972.csv.gz  in=277,586,429 out=62,316,444 elapsed=101.2s

  [5369/15692] intraday_13967.csv.gz  in=277,604,375 out=62,331,776 elapsed=101.2s

  [5370/15692] intraday_13971.csv.gz  in=277,605,463 out=62,332,741 elapsed=101.2s

  [5371/15692] intraday_13973.csv.gz  in=277,605,667 out=62,332,945 elapsed=101.2s

  [5372/15692] intraday_13975.csv.gz  in=277,605,698 out=62,332,976 elapsed=101.2s

  [5373/15692] intraday_13976.csv.gz  in=277,608,961 out=62,335,954 elapsed=101.2s

  [5374/15692] intraday_13978.csv.gz  in=277,609,302 out=62,336,241 elapsed=101.2s

  [5375/15692] intraday_13974.csv.gz  in=277,630,273 out=62,355,080 elapsed=101.2s

  [5376/15692] intraday_13977.csv.gz  in=277,634,188 out=62,358,845 elapsed=101.2s

  [5377/15692] intraday_13979.csv.gz  in=277,634,234 out=62,358,891 elapsed=101.3s

  [5378/15692] intraday_13981.csv.gz  in=277,634,282 out=62,358,939 elapsed=101.3s

  [5379/15692] intraday_1398.csv.gz  in=277,648,187 out=62,358,939 elapsed=101.3s

  [5380/15692] intraday_13980.csv.gz  in=277,649,861 out=62,360,613 elapsed=101.3s

  [5381/15692] intraday_13982.csv.gz  in=277,650,745 out=62,361,497 elapsed=101.3s

  [5382/15692] intraday_13983.csv.gz  in=277,650,770 out=62,361,522 elapsed=101.3s

  [5383/15692] intraday_13984.csv.gz  in=277,650,801 out=62,361,553 elapsed=101.3s

  [5384/15692] intraday_13985.csv.gz  in=277,650,965 out=62,361,717 elapsed=101.3s

  [5385/15692] intraday_13986.csv.gz  in=277,653,765 out=62,364,269 elapsed=101.3s

  [5386/15692] intraday_13987.csv.gz  in=277,653,906 out=62,364,410 elapsed=101.3s

  [5387/15692] intraday_13988.csv.gz  in=277,654,033 out=62,364,537 elapsed=101.3s

  [5388/15692] intraday_1399.csv.gz  in=277,666,779 out=62,364,537 elapsed=101.3s

  [5389/15692] intraday_13989.csv.gz  in=277,697,193 out=62,387,051 elapsed=101.4s

  [5390/15692] intraday_13990.csv.gz  in=277,712,515 out=62,402,373 elapsed=101.4s

  [5391/15692] intraday_13992.csv.gz  in=277,724,930 out=62,414,788 elapsed=101.4s

  [5392/15692] intraday_13993.csv.gz  in=277,735,725 out=62,425,583 elapsed=101.4s

  [5393/15692] intraday_13991.csv.gz  in=277,748,274 out=62,438,132 elapsed=101.4s

  [5394/15692] intraday_13994.csv.gz  in=277,759,518 out=62,449,376 elapsed=101.4s

  [5395/15692] intraday_13995.csv.gz  in=277,774,428 out=62,464,286 elapsed=101.5s

  [5396/15692] intraday_13998.csv.gz  in=277,787,646 out=62,477,504 elapsed=101.5s

  [5397/15692] intraday_13997.csv.gz  in=277,799,077 out=62,488,935 elapsed=101.5s

  [5398/15692] intraday_13996.csv.gz  in=277,811,393 out=62,501,251 elapsed=101.5s

  [5399/15692] intraday_13999.csv.gz  in=277,823,570 out=62,513,428 elapsed=101.5s

  [5400/15692] intraday_1400.csv.gz  in=277,842,977 out=62,513,428 elapsed=101.5s

  [5401/15692] intraday_14000.csv.gz  in=277,854,611 out=62,525,062 elapsed=101.6s

  [5402/15692] intraday_14002.csv.gz  in=277,866,042 out=62,536,493 elapsed=101.6s

  [5403/15692] intraday_14003.csv.gz  in=277,880,199 out=62,550,650 elapsed=101.6s

  [5404/15692] intraday_14001.csv.gz  in=277,892,163 out=62,562,614 elapsed=101.6s

  [5405/15692] intraday_14004.csv.gz  in=277,903,231 out=62,573,682 elapsed=101.6s

  [5406/15692] intraday_14005.csv.gz  in=277,911,393 out=62,581,844 elapsed=101.6s

  [5407/15692] intraday_14006.csv.gz  in=277,915,590 out=62,586,041 elapsed=101.6s

  [5408/15692] intraday_14007.csv.gz  in=277,926,794 out=62,597,245 elapsed=101.6s

  [5409/15692] intraday_14009.csv.gz  in=277,938,789 out=62,609,240 elapsed=101.7s

  [5410/15692] intraday_1401.csv.gz  in=277,952,545 out=62,609,240 elapsed=101.7s

  [5411/15692] intraday_14008.csv.gz  in=277,967,860 out=62,624,555 elapsed=101.7s

  [5412/15692] intraday_14010.csv.gz  in=277,981,793 out=62,638,488 elapsed=101.7s

  [5413/15692] intraday_14012.csv.gz  in=277,994,932 out=62,651,627 elapsed=101.7s

  [5414/15692] intraday_14011.csv.gz  in=278,006,433 out=62,663,128 elapsed=101.7s

  [5415/15692] intraday_14013.csv.gz  in=278,016,110 out=62,672,805 elapsed=101.7s

  [5416/15692] intraday_14014.csv.gz  in=278,026,302 out=62,682,997 elapsed=101.7s

  [5417/15692] intraday_14015.csv.gz  in=278,039,190 out=62,695,854 elapsed=101.8s

  [5418/15692] intraday_14017.csv.gz  in=278,052,688 out=62,709,352 elapsed=101.8s

  [5419/15692] intraday_14016.csv.gz  in=278,064,761 out=62,721,425 elapsed=101.8s

  [5420/15692] intraday_14018.csv.gz  in=278,079,972 out=62,736,636 elapsed=101.8s

  [5421/15692] intraday_1402.csv.gz  in=278,092,892 out=62,736,636 elapsed=101.8s

  [5422/15692] intraday_14019.csv.gz  in=278,105,975 out=62,749,719 elapsed=101.8s

  [5423/15692] intraday_14020.csv.gz  in=278,115,375 out=62,759,119 elapsed=101.8s

  [5424/15692] intraday_14022.csv.gz  in=278,118,012 out=62,761,756 elapsed=101.8s

  [5425/15692] intraday_14021.csv.gz  in=278,131,075 out=62,774,819 elapsed=101.8s

  [5426/15692] intraday_14023.csv.gz  in=278,134,200 out=62,777,944 elapsed=101.8s

  [5427/15692] intraday_14024.csv.gz  in=278,145,438 out=62,789,182 elapsed=101.9s

  [5428/15692] intraday_14026.csv.gz  in=278,155,284 out=62,799,028 elapsed=101.9s

  [5429/15692] intraday_14027.csv.gz  in=278,165,998 out=62,809,742 elapsed=101.9s

  [5430/15692] intraday_14025.csv.gz  in=278,178,172 out=62,821,916 elapsed=101.9s

  [5431/15692] intraday_14028.csv.gz  in=278,190,159 out=62,833,903 elapsed=101.9s

  [5432/15692] intraday_1403.csv.gz  in=278,201,244 out=62,833,903 elapsed=101.9s

  [5433/15692] intraday_14029.csv.gz  in=278,215,817 out=62,848,476 elapsed=101.9s

  [5434/15692] intraday_14030.csv.gz  in=278,226,960 out=62,859,619 elapsed=102.0s

  [5435/15692] intraday_14032.csv.gz  in=278,238,847 out=62,871,506 elapsed=102.0s

  [5436/15692] intraday_14031.csv.gz  in=278,253,618 out=62,886,277 elapsed=102.0s

  [5437/15692] intraday_14033.csv.gz  in=278,264,529 out=62,897,188 elapsed=102.0s

  [5438/15692] intraday_14034.csv.gz  in=278,278,080 out=62,910,739 elapsed=102.0s

  [5439/15692] intraday_14036.csv.gz  in=278,288,813 out=62,921,472 elapsed=102.0s

  [5440/15692] intraday_14035.csv.gz  in=278,299,007 out=62,931,666 elapsed=102.0s

  [5441/15692] intraday_14037.csv.gz  in=278,308,444 out=62,941,103 elapsed=102.0s

  [5442/15692] intraday_14038.csv.gz  in=278,316,646 out=62,949,305 elapsed=102.0s

  [5443/15692] intraday_14040.csv.gz  in=278,327,663 out=62,960,322 elapsed=102.1s

  [5444/15692] intraday_1404.csv.gz  in=278,342,935 out=62,960,322 elapsed=102.1s

  [5445/15692] intraday_14039.csv.gz  in=278,355,387 out=62,972,774 elapsed=102.1s

  [5446/15692] intraday_14041.csv.gz  in=278,366,677 out=62,984,064 elapsed=102.1s

  [5447/15692] intraday_14042.csv.gz  in=278,376,691 out=62,994,078 elapsed=102.1s

  [5448/15692] intraday_14044.csv.gz  in=278,389,894 out=63,007,281 elapsed=102.1s

  [5449/15692] intraday_14043.csv.gz  in=278,401,595 out=63,018,982 elapsed=102.1s

  [5450/15692] intraday_14045.csv.gz  in=278,412,687 out=63,030,074 elapsed=102.2s

  [5451/15692] intraday_14046.csv.gz  in=278,425,881 out=63,043,268 elapsed=102.2s

  [5452/15692] intraday_14047.csv.gz  in=278,436,148 out=63,053,535 elapsed=102.2s

  [5453/15692] intraday_14048.csv.gz  in=278,447,149 out=63,064,536 elapsed=102.2s

  [5454/15692] intraday_14049.csv.gz  in=278,457,676 out=63,075,063 elapsed=102.2s

  [5455/15692] intraday_1405.csv.gz  in=278,474,619 out=63,075,063 elapsed=102.2s

  [5456/15692] intraday_14050.csv.gz  in=278,488,950 out=63,089,394 elapsed=102.2s

  [5457/15692] intraday_14051.csv.gz  in=278,493,291 out=63,093,735 elapsed=102.2s

  [5458/15692] intraday_14052.csv.gz  in=278,498,581 out=63,099,025 elapsed=102.2s

  [5459/15692] intraday_14053.csv.gz  in=278,509,433 out=63,109,877 elapsed=102.3s

  [5460/15692] intraday_14054.csv.gz  in=278,520,316 out=63,120,760 elapsed=102.3s

  [5461/15692] intraday_14055.csv.gz  in=278,532,435 out=63,132,879 elapsed=102.3s

  [5462/15692] intraday_14057.csv.gz  in=278,543,883 out=63,144,327 elapsed=102.3s

  [5463/15692] intraday_14056.csv.gz  in=278,557,087 out=63,157,531 elapsed=102.3s

  [5464/15692] intraday_14058.csv.gz  in=278,569,689 out=63,170,133 elapsed=102.3s

  [5465/15692] intraday_14059.csv.gz  in=278,580,254 out=63,180,698 elapsed=102.3s

  [5466/15692] intraday_1406.csv.gz  in=278,596,002 out=63,180,698 elapsed=102.3s

  [5467/15692] intraday_14061.csv.gz  in=278,610,737 out=63,195,433 elapsed=102.4s

  [5468/15692] intraday_14060.csv.gz  in=278,621,265 out=63,205,961 elapsed=102.4s

  [5469/15692] intraday_14062.csv.gz  in=278,632,494 out=63,217,190 elapsed=102.4s

  [5470/15692] intraday_14063.csv.gz  in=278,644,152 out=63,228,848 elapsed=102.4s

  [5471/15692] intraday_14065.csv.gz  in=278,646,016 out=63,230,712 elapsed=102.4s

  [5472/15692] intraday_14064.csv.gz  in=278,653,442 out=63,238,138 elapsed=102.4s

  [5473/15692] intraday_14066.csv.gz  in=278,666,847 out=63,251,543 elapsed=102.4s

  [5474/15692] intraday_14068.csv.gz  in=278,680,121 out=63,264,817 elapsed=102.4s

  [5475/15692] intraday_14067.csv.gz  in=278,695,292 out=63,279,988 elapsed=102.5s

  [5476/15692] intraday_1407.csv.gz  in=278,710,414 out=63,279,988 elapsed=102.5s

  [5477/15692] intraday_14069.csv.gz  in=278,721,634 out=63,291,208 elapsed=102.5s

  [5478/15692] intraday_14070.csv.gz  in=278,732,305 out=63,301,879 elapsed=102.5s

  [5479/15692] intraday_14071.csv.gz  in=278,743,889 out=63,313,463 elapsed=102.5s

  [5480/15692] intraday_14072.csv.gz  in=278,758,092 out=63,327,666 elapsed=102.5s

  [5481/15692] intraday_14074.csv.gz  in=278,767,447 out=63,337,021 elapsed=102.5s

  [5482/15692] intraday_14073.csv.gz  in=278,779,770 out=63,349,344 elapsed=102.5s

  [5483/15692] intraday_14075.csv.gz  in=278,794,538 out=63,364,112 elapsed=102.6s

  [5484/15692] intraday_14076.csv.gz  in=278,805,461 out=63,375,035 elapsed=102.6s

  [5485/15692] intraday_14077.csv.gz  in=278,817,483 out=63,387,057 elapsed=102.6s

  [5486/15692] intraday_1408.csv.gz  in=278,831,075 out=63,387,057 elapsed=102.6s

  [5487/15692] intraday_14078.csv.gz  in=278,842,549 out=63,398,531 elapsed=102.6s

  [5488/15692] intraday_14079.csv.gz  in=278,854,092 out=63,410,074 elapsed=102.6s

  [5489/15692] intraday_14080.csv.gz  in=278,865,865 out=63,421,847 elapsed=102.6s

  [5490/15692] intraday_14083.csv.gz  in=278,876,847 out=63,432,829 elapsed=102.7s

  [5491/15692] intraday_14081.csv.gz  in=278,889,815 out=63,445,797 elapsed=102.7s

  [5492/15692] intraday_14082.csv.gz  in=278,900,676 out=63,456,658 elapsed=102.7s

  [5493/15692] intraday_14084.csv.gz  in=278,914,304 out=63,470,286 elapsed=102.7s

  [5494/15692] intraday_14086.csv.gz  in=278,926,593 out=63,482,575 elapsed=102.7s

  [5495/15692] intraday_14085.csv.gz  in=278,939,200 out=63,495,182 elapsed=102.7s

  [5496/15692] intraday_14087.csv.gz  in=278,950,651 out=63,506,633 elapsed=102.7s

  [5497/15692] intraday_14089.csv.gz  in=278,966,151 out=63,522,133 elapsed=102.7s

  [5498/15692] intraday_1409.csv.gz  in=278,978,811 out=63,522,133 elapsed=102.7s

  [5499/15692] intraday_14090.csv.gz  in=278,989,355 out=63,532,677 elapsed=102.7s

  [5500/15692] intraday_14088.csv.gz  in=279,025,056 out=63,564,876 elapsed=102.8s

  [5501/15692] intraday_14092.csv.gz  in=279,038,347 out=63,578,167 elapsed=102.8s

  [5502/15692] intraday_14091.csv.gz  in=279,049,944 out=63,589,764 elapsed=102.8s

  [5503/15692] intraday_14093.csv.gz  in=279,063,622 out=63,603,442 elapsed=102.8s

  [5504/15692] intraday_14094.csv.gz  in=279,076,295 out=63,616,115 elapsed=102.8s

  [5505/15692] intraday_14097.csv.gz  in=279,088,831 out=63,628,651 elapsed=102.8s

  [5506/15692] intraday_14095.csv.gz  in=279,102,711 out=63,642,531 elapsed=102.8s

  [5507/15692] intraday_14098.csv.gz  in=279,115,769 out=63,655,589 elapsed=102.8s

  [5508/15692] intraday_14096.csv.gz  in=279,129,677 out=63,669,497 elapsed=102.8s

  [5509/15692] intraday_1410.csv.gz  in=279,142,877 out=63,669,497 elapsed=102.9s

  [5510/15692] intraday_14100.csv.gz  in=279,159,103 out=63,685,723 elapsed=102.9s

  [5511/15692] intraday_14101.csv.gz  in=279,172,552 out=63,699,172 elapsed=102.9s

  [5512/15692] intraday_14099.csv.gz  in=279,188,941 out=63,715,561 elapsed=102.9s

  [5513/15692] intraday_14102.csv.gz  in=279,203,752 out=63,730,372 elapsed=102.9s

  [5514/15692] intraday_14103.csv.gz  in=279,214,623 out=63,741,243 elapsed=102.9s

  [5515/15692] intraday_14105.csv.gz  in=279,224,514 out=63,751,134 elapsed=102.9s

  [5516/15692] intraday_14104.csv.gz  in=279,237,552 out=63,764,172 elapsed=102.9s

  [5517/15692] intraday_14107.csv.gz  in=279,248,059 out=63,774,679 elapsed=102.9s

  [5518/15692] intraday_14106.csv.gz  in=279,260,947 out=63,787,567 elapsed=103.0s

  [5519/15692] intraday_14108.csv.gz  in=279,274,118 out=63,800,738 elapsed=103.0s

  [5520/15692] intraday_1411.csv.gz  in=279,287,953 out=63,800,738 elapsed=103.0s

  [5521/15692] intraday_14109.csv.gz  in=279,298,226 out=63,811,011 elapsed=103.0s

  [5522/15692] intraday_14110.csv.gz  in=279,314,510 out=63,827,295 elapsed=103.0s

  [5523/15692] intraday_14112.csv.gz  in=279,326,423 out=63,839,208 elapsed=103.0s

  [5524/15692] intraday_14113.csv.gz  in=279,337,628 out=63,850,413 elapsed=103.0s

  [5525/15692] intraday_14111.csv.gz  in=279,347,555 out=63,860,340 elapsed=103.0s

  [5526/15692] intraday_14114.csv.gz  in=279,361,152 out=63,873,937 elapsed=103.0s

  [5527/15692] intraday_14115.csv.gz  in=279,372,418 out=63,885,203 elapsed=103.0s

  [5528/15692] intraday_14116.csv.gz  in=279,386,197 out=63,898,982 elapsed=103.1s

  [5529/15692] intraday_14119.csv.gz  in=279,399,082 out=63,911,867 elapsed=103.1s

  [5530/15692] intraday_14117.csv.gz  in=279,413,933 out=63,926,718 elapsed=103.1s

  [5531/15692] intraday_14118.csv.gz  in=279,426,671 out=63,939,456 elapsed=103.1s

  [5532/15692] intraday_1412.csv.gz  in=279,438,675 out=63,939,456 elapsed=103.1s

  [5533/15692] intraday_14122.csv.gz  in=279,450,645 out=63,951,426 elapsed=103.1s

  [5534/15692] intraday_14121.csv.gz  in=279,461,501 out=63,962,282 elapsed=103.1s

  [5535/15692] intraday_14123.csv.gz  in=279,471,816 out=63,972,597 elapsed=103.1s

  [5536/15692] intraday_14120.csv.gz  in=279,483,948 out=63,984,729 elapsed=103.1s

  [5537/15692] intraday_14124.csv.gz  in=279,495,956 out=63,996,737 elapsed=103.2s

  [5538/15692] intraday_14125.csv.gz  in=279,507,305 out=64,008,086 elapsed=103.2s

  [5539/15692] intraday_14126.csv.gz  in=279,514,626 out=64,015,407 elapsed=103.2s

  [5540/15692] intraday_14127.csv.gz  in=279,528,195 out=64,028,976 elapsed=103.2s

  [5541/15692] intraday_1413.csv.gz  in=279,541,937 out=64,028,976 elapsed=103.2s

  [5542/15692] intraday_14129.csv.gz  in=279,553,239 out=64,040,278 elapsed=103.2s

  [5543/15692] intraday_14128.csv.gz  in=279,569,384 out=64,056,423 elapsed=103.2s

  [5544/15692] intraday_14130.csv.gz  in=279,582,011 out=64,069,050 elapsed=103.2s

  [5545/15692] intraday_14131.csv.gz  in=279,593,879 out=64,080,918 elapsed=103.3s

  [5546/15692] intraday_14132.csv.gz  in=279,608,355 out=64,094,886 elapsed=103.3s

  [5547/15692] intraday_14134.csv.gz  in=279,621,900 out=64,108,431 elapsed=103.3s

  [5548/15692] intraday_14133.csv.gz  in=279,636,134 out=64,122,665 elapsed=103.3s

  [5549/15692] intraday_14135.csv.gz  in=279,647,034 out=64,133,565 elapsed=103.3s

  [5550/15692] intraday_14136.csv.gz  in=279,659,505 out=64,146,036 elapsed=103.3s

  [5551/15692] intraday_14137.csv.gz  in=279,671,352 out=64,157,883 elapsed=103.3s

  [5552/15692] intraday_14138.csv.gz  in=279,683,035 out=64,169,566 elapsed=103.3s

  [5553/15692] intraday_14139.csv.gz  in=279,694,357 out=64,180,888 elapsed=103.3s

  [5554/15692] intraday_1414.csv.gz  in=279,707,418 out=64,180,888 elapsed=103.3s

  [5555/15692] intraday_14141.csv.gz  in=279,721,697 out=64,195,167 elapsed=103.4s

  [5556/15692] intraday_14140.csv.gz  in=279,736,866 out=64,209,867 elapsed=103.4s

  [5557/15692] intraday_14142.csv.gz  in=279,745,872 out=64,218,873 elapsed=103.4s

  [5558/15692] intraday_14143.csv.gz  in=279,751,954 out=64,224,955 elapsed=103.4s

  [5559/15692] intraday_14145.csv.gz  in=279,762,924 out=64,235,925 elapsed=103.4s

  [5560/15692] intraday_14146.csv.gz  in=279,776,960 out=64,249,961 elapsed=103.4s

  [5561/15692] intraday_14144.csv.gz  in=279,787,930 out=64,260,931 elapsed=103.4s

  [5562/15692] intraday_14147.csv.gz  in=279,799,356 out=64,272,357 elapsed=103.5s

  [5563/15692] intraday_1415.csv.gz  in=279,811,535 out=64,272,357 elapsed=103.5s

  [5564/15692] intraday_14149.csv.gz  in=279,823,886 out=64,284,708 elapsed=103.5s

  [5565/15692] intraday_14148.csv.gz  in=279,836,356 out=64,297,178 elapsed=103.5s

  [5566/15692] intraday_14150.csv.gz  in=279,849,388 out=64,310,210 elapsed=103.5s

  [5567/15692] intraday_14152.csv.gz  in=279,859,510 out=64,320,332 elapsed=103.5s

  [5568/15692] intraday_14151.csv.gz  in=279,869,263 out=64,330,085 elapsed=103.5s

  [5569/15692] intraday_14154.csv.gz  in=279,879,912 out=64,340,734 elapsed=103.6s

  [5570/15692] intraday_14153.csv.gz  in=279,891,120 out=64,351,942 elapsed=103.6s

  [5571/15692] intraday_14155.csv.gz  in=279,905,276 out=64,366,098 elapsed=103.6s

  [5572/15692] intraday_14156.csv.gz  in=279,920,519 out=64,381,341 elapsed=103.6s

  [5573/15692] intraday_14158.csv.gz  in=279,930,239 out=64,391,061 elapsed=103.6s

  [5574/15692] intraday_14157.csv.gz  in=279,943,858 out=64,404,680 elapsed=103.6s

  [5575/15692] intraday_14159.csv.gz  in=279,947,536 out=64,408,358 elapsed=103.6s

  [5576/15692] intraday_1416.csv.gz  in=279,959,356 out=64,408,358 elapsed=103.6s

  [5577/15692] intraday_14160.csv.gz  in=279,961,359 out=64,410,361 elapsed=103.6s

  [5578/15692] intraday_14161.csv.gz  in=279,973,827 out=64,422,829 elapsed=103.6s

  [5579/15692] intraday_14162.csv.gz  in=279,984,003 out=64,432,912 elapsed=103.7s

  [5580/15692] intraday_14164.csv.gz  in=279,993,792 out=64,442,701 elapsed=103.7s

  [5581/15692] intraday_14163.csv.gz  in=280,004,942 out=64,453,851 elapsed=103.7s

  [5582/15692] intraday_14166.csv.gz  in=280,017,345 out=64,466,254 elapsed=103.7s

  [5583/15692] intraday_14165.csv.gz  in=280,027,603 out=64,476,512 elapsed=103.7s

  [5584/15692] intraday_14167.csv.gz  in=280,037,818 out=64,486,727 elapsed=103.7s

  [5585/15692] intraday_14168.csv.gz  in=280,051,848 out=64,500,757 elapsed=103.7s

  [5586/15692] intraday_14169.csv.gz  in=280,065,579 out=64,514,488 elapsed=103.8s

  [5587/15692] intraday_1417.csv.gz  in=280,079,050 out=64,514,488 elapsed=103.8s

  [5588/15692] intraday_14170.csv.gz  in=280,091,453 out=64,526,891 elapsed=103.8s

  [5589/15692] intraday_14173.csv.gz  in=280,094,877 out=64,530,315 elapsed=103.8s

  [5590/15692] intraday_14171.csv.gz  in=280,106,674 out=64,542,112 elapsed=103.8s

  [5591/15692] intraday_14172.csv.gz  in=280,119,217 out=64,554,655 elapsed=103.8s

  [5592/15692] intraday_14174.csv.gz  in=280,122,534 out=64,557,972 elapsed=103.8s

  [5593/15692] intraday_14175.csv.gz  in=280,132,350 out=64,567,788 elapsed=103.9s

  [5594/15692] intraday_14176.csv.gz  in=280,147,931 out=64,583,369 elapsed=103.9s

  [5595/15692] intraday_14178.csv.gz  in=280,158,246 out=64,593,684 elapsed=103.9s

  [5596/15692] intraday_14177.csv.gz  in=280,169,508 out=64,604,946 elapsed=103.9s

  [5597/15692] intraday_14179.csv.gz  in=280,183,859 out=64,619,297 elapsed=103.9s

  [5598/15692] intraday_1418.csv.gz  in=280,198,347 out=64,619,297 elapsed=103.9s

  [5599/15692] intraday_14180.csv.gz  in=280,209,650 out=64,630,600 elapsed=103.9s

  [5600/15692] intraday_14181.csv.gz  in=280,220,955 out=64,641,905 elapsed=103.9s

  [5601/15692] intraday_14182.csv.gz  in=280,231,276 out=64,652,226 elapsed=104.0s

  [5602/15692] intraday_14183.csv.gz  in=280,243,089 out=64,664,039 elapsed=104.0s

  [5603/15692] intraday_14184.csv.gz  in=280,255,082 out=64,676,032 elapsed=104.0s

  [5604/15692] intraday_14185.csv.gz  in=280,267,590 out=64,688,540 elapsed=104.0s

  [5605/15692] intraday_14187.csv.gz  in=280,271,442 out=64,692,392 elapsed=104.0s

  [5606/15692] intraday_14186.csv.gz  in=280,280,753 out=64,701,703 elapsed=104.0s

  [5607/15692] intraday_14188.csv.gz  in=280,286,941 out=64,707,891 elapsed=104.0s

  [5608/15692] intraday_1419.csv.gz  in=280,300,837 out=64,707,891 elapsed=104.0s

  [5609/15692] intraday_14189.csv.gz  in=280,313,922 out=64,720,976 elapsed=104.0s

  [5610/15692] intraday_14190.csv.gz  in=280,326,691 out=64,733,745 elapsed=104.1s

  [5611/15692] intraday_14192.csv.gz  in=280,339,296 out=64,746,350 elapsed=104.1s

  [5612/15692] intraday_14191.csv.gz  in=280,350,375 out=64,757,429 elapsed=104.1s

  [5613/15692] intraday_14194.csv.gz  in=280,362,747 out=64,769,801 elapsed=104.1s

  [5614/15692] intraday_14193.csv.gz  in=280,372,102 out=64,779,156 elapsed=104.1s

  [5615/15692] intraday_14195.csv.gz  in=280,384,582 out=64,791,636 elapsed=104.1s

  [5616/15692] intraday_14196.csv.gz  in=280,397,175 out=64,804,229 elapsed=104.1s

  [5617/15692] intraday_14198.csv.gz  in=280,409,207 out=64,816,261 elapsed=104.1s

  [5618/15692] intraday_14197.csv.gz  in=280,420,886 out=64,827,940 elapsed=104.2s

  [5619/15692] intraday_14199.csv.gz  in=280,430,820 out=64,837,874 elapsed=104.2s

  [5620/15692] intraday_1420.csv.gz  in=280,446,949 out=64,837,874 elapsed=104.2s

  [5621/15692] intraday_14200.csv.gz  in=280,459,893 out=64,850,818 elapsed=104.2s

  [5622/15692] intraday_14201.csv.gz  in=280,472,494 out=64,863,419 elapsed=104.2s

  [5623/15692] intraday_14202.csv.gz  in=280,484,189 out=64,875,114 elapsed=104.2s

  [5624/15692] intraday_14203.csv.gz  in=280,495,049 out=64,885,974 elapsed=104.2s

  [5625/15692] intraday_14205.csv.gz  in=280,505,367 out=64,896,292 elapsed=104.2s

  [5626/15692] intraday_14204.csv.gz  in=280,514,521 out=64,905,446 elapsed=104.2s

  [5627/15692] intraday_14207.csv.gz  in=280,529,812 out=64,920,737 elapsed=104.3s

  [5628/15692] intraday_14209.csv.gz  in=280,544,389 out=64,935,314 elapsed=104.3s

  [5629/15692] intraday_14206.csv.gz  in=280,557,033 out=64,947,958 elapsed=104.3s

  [5630/15692] intraday_14208.csv.gz  in=280,571,616 out=64,962,541 elapsed=104.3s

  [5631/15692] intraday_1421.csv.gz  in=280,583,739 out=64,962,541 elapsed=104.3s

  [5632/15692] intraday_14210.csv.gz  in=280,594,824 out=64,973,626 elapsed=104.3s

  [5633/15692] intraday_14211.csv.gz  in=280,606,999 out=64,985,801 elapsed=104.3s

  [5634/15692] intraday_14213.csv.gz  in=280,622,208 out=65,001,010 elapsed=104.4s

  [5635/15692] intraday_14212.csv.gz  in=280,632,558 out=65,011,360 elapsed=104.4s

  [5636/15692] intraday_14214.csv.gz  in=280,642,402 out=65,021,204 elapsed=104.4s

  [5637/15692] intraday_14215.csv.gz  in=280,654,776 out=65,033,578 elapsed=104.4s

  [5638/15692] intraday_14216.csv.gz  in=280,667,284 out=65,046,086 elapsed=104.4s

  [5639/15692] intraday_14217.csv.gz  in=280,678,797 out=65,057,599 elapsed=104.4s

  [5640/15692] intraday_14218.csv.gz  in=280,691,534 out=65,070,336 elapsed=104.4s

  [5641/15692] intraday_14219.csv.gz  in=280,702,430 out=65,081,232 elapsed=104.4s

  [5642/15692] intraday_1422.csv.gz  in=280,716,219 out=65,081,232 elapsed=104.4s

  [5643/15692] intraday_14220.csv.gz  in=280,728,438 out=65,093,451 elapsed=104.4s

  [5644/15692] intraday_14222.csv.gz  in=280,738,891 out=65,103,904 elapsed=104.5s

  [5645/15692] intraday_14221.csv.gz  in=280,750,409 out=65,115,422 elapsed=104.5s

  [5646/15692] intraday_14224.csv.gz  in=280,762,683 out=65,127,696 elapsed=104.5s

  [5647/15692] intraday_14223.csv.gz  in=280,774,298 out=65,139,311 elapsed=104.5s

  [5648/15692] intraday_14225.csv.gz  in=280,786,672 out=65,151,685 elapsed=104.5s

  [5649/15692] intraday_14227.csv.gz  in=280,800,264 out=65,165,101 elapsed=104.5s

  [5650/15692] intraday_14226.csv.gz  in=280,812,526 out=65,177,363 elapsed=104.5s

  [5651/15692] intraday_14228.csv.gz  in=280,823,837 out=65,188,674 elapsed=104.6s

  [5652/15692] intraday_14229.csv.gz  in=280,835,149 out=65,199,986 elapsed=104.6s

  [5653/15692] intraday_1423.csv.gz  in=280,850,228 out=65,199,986 elapsed=104.6s

  [5654/15692] intraday_14231.csv.gz  in=280,861,784 out=65,211,542 elapsed=104.6s

  [5655/15692] intraday_14232.csv.gz  in=280,873,213 out=65,222,971 elapsed=104.6s

  [5656/15692] intraday_14230.csv.gz  in=280,887,801 out=65,237,559 elapsed=104.6s

  [5657/15692] intraday_14233.csv.gz  in=280,900,483 out=65,250,241 elapsed=104.6s

  [5658/15692] intraday_14234.csv.gz  in=280,914,016 out=65,263,774 elapsed=104.7s

  [5659/15692] intraday_14236.csv.gz  in=280,927,842 out=65,277,600 elapsed=104.7s

  [5660/15692] intraday_14235.csv.gz  in=280,940,110 out=65,289,868 elapsed=104.7s

  [5661/15692] intraday_14237.csv.gz  in=280,953,299 out=65,303,057 elapsed=104.7s

  [5662/15692] intraday_14238.csv.gz  in=280,965,265 out=65,315,023 elapsed=104.7s

  [5663/15692] intraday_14239.csv.gz  in=280,980,834 out=65,330,592 elapsed=104.7s

  [5664/15692] intraday_1424.csv.gz  in=280,994,307 out=65,330,592 elapsed=104.7s

  [5665/15692] intraday_14241.csv.gz  in=281,009,420 out=65,345,705 elapsed=104.8s

  [5666/15692] intraday_14243.csv.gz  in=281,021,513 out=65,357,798 elapsed=104.8s

  [5667/15692] intraday_14240.csv.gz  in=281,038,522 out=65,374,807 elapsed=104.8s

  [5668/15692] intraday_14242.csv.gz  in=281,051,940 out=65,388,225 elapsed=104.8s

  [5669/15692] intraday_14246.csv.gz  in=281,060,821 out=65,397,106 elapsed=104.8s

  [5670/15692] intraday_14244.csv.gz  in=281,073,190 out=65,409,475 elapsed=104.8s

  [5671/15692] intraday_14245.csv.gz  in=281,085,402 out=65,421,687 elapsed=104.8s

  [5672/15692] intraday_14247.csv.gz  in=281,097,856 out=65,434,141 elapsed=104.8s

  [5673/15692] intraday_14248.csv.gz  in=281,108,976 out=65,445,261 elapsed=104.9s

  [5674/15692] intraday_1425.csv.gz  in=281,122,496 out=65,445,261 elapsed=104.9s

  [5675/15692] intraday_14249.csv.gz  in=281,134,529 out=65,457,294 elapsed=104.9s

  [5676/15692] intraday_14250.csv.gz  in=281,147,574 out=65,470,339 elapsed=104.9s

  [5677/15692] intraday_14251.csv.gz  in=281,160,752 out=65,483,517 elapsed=104.9s

  [5678/15692] intraday_14252.csv.gz  in=281,170,682 out=65,493,447 elapsed=104.9s

  [5679/15692] intraday_14253.csv.gz  in=281,182,560 out=65,505,325 elapsed=104.9s

  [5680/15692] intraday_14254.csv.gz  in=281,193,541 out=65,516,306 elapsed=104.9s

  [5681/15692] intraday_14255.csv.gz  in=281,207,931 out=65,530,696 elapsed=105.0s

  [5682/15692] intraday_14257.csv.gz  in=281,221,203 out=65,543,968 elapsed=105.0s

  [5683/15692] intraday_14256.csv.gz  in=281,233,300 out=65,556,065 elapsed=105.0s

  [5684/15692] intraday_14258.csv.gz  in=281,247,374 out=65,570,139 elapsed=105.0s

  [5685/15692] intraday_1426.csv.gz  in=281,259,388 out=65,570,139 elapsed=105.0s

  [5686/15692] intraday_14259.csv.gz  in=281,271,081 out=65,581,832 elapsed=105.0s

  [5687/15692] intraday_14260.csv.gz  in=281,285,268 out=65,596,019 elapsed=105.0s

  [5688/15692] intraday_14261.csv.gz  in=281,295,249 out=65,606,000 elapsed=105.0s

  [5689/15692] intraday_14262.csv.gz  in=281,307,720 out=65,618,471 elapsed=105.1s

  [5690/15692] intraday_14264.csv.gz  in=281,317,708 out=65,628,459 elapsed=105.1s

  [5691/15692] intraday_14263.csv.gz  in=281,329,117 out=65,639,868 elapsed=105.1s

  [5692/15692] intraday_14265.csv.gz  in=281,341,722 out=65,652,473 elapsed=105.1s

  [5693/15692] intraday_14266.csv.gz  in=281,349,446 out=65,660,197 elapsed=105.1s

  [5694/15692] intraday_14268.csv.gz  in=281,359,027 out=65,669,778 elapsed=105.1s

  [5695/15692] intraday_14267.csv.gz  in=281,369,847 out=65,680,598 elapsed=105.1s

  [5696/15692] intraday_1427.csv.gz  in=281,381,062 out=65,680,598 elapsed=105.1s

  [5697/15692] intraday_14269.csv.gz  in=281,396,811 out=65,696,347 elapsed=105.1s

  [5698/15692] intraday_14270.csv.gz  in=281,409,213 out=65,708,749 elapsed=105.2s

  [5699/15692] intraday_14271.csv.gz  in=281,422,242 out=65,721,778 elapsed=105.2s

  [5700/15692] intraday_14272.csv.gz  in=281,431,815 out=65,731,351 elapsed=105.2s

  [5701/15692] intraday_14273.csv.gz  in=281,443,561 out=65,743,097 elapsed=105.2s

  [5702/15692] intraday_14274.csv.gz  in=281,457,274 out=65,756,810 elapsed=105.2s

  [5703/15692] intraday_14276.csv.gz  in=281,466,809 out=65,766,345 elapsed=105.2s

  [5704/15692] intraday_14275.csv.gz  in=281,481,260 out=65,780,796 elapsed=105.2s

  [5705/15692] intraday_14278.csv.gz  in=281,493,505 out=65,793,041 elapsed=105.2s

  [5706/15692] intraday_14279.csv.gz  in=281,504,704 out=65,804,240 elapsed=105.3s

  [5707/15692] intraday_1428.csv.gz  in=281,520,793 out=65,804,240 elapsed=105.3s

  [5708/15692] intraday_14277.csv.gz  in=281,533,735 out=65,817,182 elapsed=105.3s

  [5709/15692] intraday_14281.csv.gz  in=281,545,539 out=65,828,986 elapsed=105.3s

  [5710/15692] intraday_14280.csv.gz  in=281,555,768 out=65,839,215 elapsed=105.3s

  [5711/15692] intraday_14283.csv.gz  in=281,564,292 out=65,847,739 elapsed=105.3s

  [5712/15692] intraday_14282.csv.gz  in=281,578,708 out=65,862,155 elapsed=105.3s

  [5713/15692] intraday_14284.csv.gz  in=281,581,741 out=65,865,188 elapsed=105.3s

  [5714/15692] intraday_14286.csv.gz  in=281,593,024 out=65,876,471 elapsed=105.3s

  [5715/15692] intraday_14285.csv.gz  in=281,603,701 out=65,887,148 elapsed=105.4s

  [5716/15692] intraday_14287.csv.gz  in=281,617,434 out=65,900,881 elapsed=105.4s

  [5717/15692] intraday_14288.csv.gz  in=281,627,818 out=65,911,265 elapsed=105.4s

  [5718/15692] intraday_14289.csv.gz  in=281,640,553 out=65,924,000 elapsed=105.4s

  [5719/15692] intraday_1429.csv.gz  in=281,660,463 out=65,924,000 elapsed=105.4s

  [5720/15692] intraday_14290.csv.gz  in=281,672,619 out=65,936,156 elapsed=105.4s

  [5721/15692] intraday_14291.csv.gz  in=281,685,602 out=65,949,139 elapsed=105.4s

  [5722/15692] intraday_14292.csv.gz  in=281,695,436 out=65,958,973 elapsed=105.5s

  [5723/15692] intraday_14293.csv.gz  in=281,705,465 out=65,969,002 elapsed=105.5s

  [5724/15692] intraday_14294.csv.gz  in=281,717,010 out=65,980,547 elapsed=105.5s

  [5725/15692] intraday_14295.csv.gz  in=281,728,084 out=65,991,621 elapsed=105.5s

  [5726/15692] intraday_14296.csv.gz  in=281,740,704 out=66,004,241 elapsed=105.5s

  [5727/15692] intraday_14299.csv.gz  in=281,744,810 out=66,008,347 elapsed=105.5s

  [5728/15692] intraday_14298.csv.gz  in=281,756,908 out=66,020,445 elapsed=105.5s

  [5729/15692] intraday_14297.csv.gz  in=281,773,922 out=66,037,459 elapsed=105.6s

  [5730/15692] intraday_1430.csv.gz  in=281,786,064 out=66,037,459 elapsed=105.6s

  [5731/15692] intraday_14300.csv.gz  in=281,797,740 out=66,049,135 elapsed=105.6s

  [5732/15692] intraday_14301.csv.gz  in=281,810,542 out=66,061,937 elapsed=105.6s

  [5733/15692] intraday_14302.csv.gz  in=281,819,821 out=66,071,216 elapsed=105.6s

  [5734/15692] intraday_14303.csv.gz  in=281,831,640 out=66,083,035 elapsed=105.6s

  [5735/15692] intraday_14304.csv.gz  in=281,840,530 out=66,091,925 elapsed=105.6s

  [5736/15692] intraday_14305.csv.gz  in=281,851,025 out=66,102,420 elapsed=105.6s

  [5737/15692] intraday_14306.csv.gz  in=281,862,637 out=66,114,032 elapsed=105.6s

  [5738/15692] intraday_14308.csv.gz  in=281,875,193 out=66,126,588 elapsed=105.7s

  [5739/15692] intraday_14307.csv.gz  in=281,886,938 out=66,138,333 elapsed=105.7s

  [5740/15692] intraday_1431.csv.gz  in=281,901,041 out=66,138,333 elapsed=105.7s

  [5741/15692] intraday_14309.csv.gz  in=281,914,922 out=66,152,214 elapsed=105.7s

  [5742/15692] intraday_14310.csv.gz  in=281,926,092 out=66,163,384 elapsed=105.7s

  [5743/15692] intraday_14311.csv.gz  in=281,937,608 out=66,174,900 elapsed=105.7s

  [5744/15692] intraday_14313.csv.gz  in=281,947,821 out=66,185,113 elapsed=105.7s

  [5745/15692] intraday_14312.csv.gz  in=281,959,909 out=66,197,201 elapsed=105.8s

  [5746/15692] intraday_14314.csv.gz  in=281,970,999 out=66,208,291 elapsed=105.8s

  [5747/15692] intraday_14315.csv.gz  in=281,980,610 out=66,217,902 elapsed=105.8s

  [5748/15692] intraday_14316.csv.gz  in=281,989,935 out=66,227,227 elapsed=105.8s

  [5749/15692] intraday_14317.csv.gz  in=281,996,321 out=66,233,613 elapsed=105.8s

  [5750/15692] intraday_14318.csv.gz  in=282,008,336 out=66,245,628 elapsed=105.8s

  [5751/15692] intraday_1432.csv.gz  in=282,021,364 out=66,245,628 elapsed=105.8s

  [5752/15692] intraday_14319.csv.gz  in=282,032,139 out=66,256,403 elapsed=105.8s

  [5753/15692] intraday_14320.csv.gz  in=282,042,290 out=66,266,554 elapsed=105.9s

  [5754/15692] intraday_14322.csv.gz  in=282,055,089 out=66,279,353 elapsed=105.9s

  [5755/15692] intraday_14321.csv.gz  in=282,065,852 out=66,290,116 elapsed=105.9s

  [5756/15692] intraday_14323.csv.gz  in=282,076,973 out=66,301,237 elapsed=105.9s

  [5757/15692] intraday_14324.csv.gz  in=282,088,047 out=66,312,311 elapsed=105.9s

  [5758/15692] intraday_14325.csv.gz  in=282,097,947 out=66,322,211 elapsed=105.9s

  [5759/15692] intraday_14326.csv.gz  in=282,108,810 out=66,333,074 elapsed=105.9s

  [5760/15692] intraday_14327.csv.gz  in=282,117,838 out=66,342,102 elapsed=105.9s

  [5761/15692] intraday_1433.csv.gz  in=282,129,480 out=66,342,102 elapsed=106.0s

  [5762/15692] intraday_14329.csv.gz  in=282,143,373 out=66,355,964 elapsed=106.0s

  [5763/15692] intraday_14330.csv.gz  in=282,156,615 out=66,369,206 elapsed=106.0s

  [5764/15692] intraday_14331.csv.gz  in=282,167,899 out=66,380,490 elapsed=106.0s

  [5765/15692] intraday_14328.csv.gz  in=282,182,782 out=66,395,373 elapsed=106.0s

  [5766/15692] intraday_14333.csv.gz  in=282,184,192 out=66,396,783 elapsed=106.0s

  [5767/15692] intraday_14332.csv.gz  in=282,195,181 out=66,407,772 elapsed=106.0s

  [5768/15692] intraday_14334.csv.gz  in=282,199,097 out=66,411,688 elapsed=106.1s

  [5769/15692] intraday_14335.csv.gz  in=282,210,602 out=66,423,193 elapsed=106.1s

  [5770/15692] intraday_14336.csv.gz  in=282,222,398 out=66,434,989 elapsed=106.1s

  [5771/15692] intraday_14337.csv.gz  in=282,234,000 out=66,446,591 elapsed=106.1s

  [5772/15692] intraday_14338.csv.gz  in=282,243,053 out=66,455,644 elapsed=106.1s

  [5773/15692] intraday_1434.csv.gz  in=282,257,308 out=66,455,644 elapsed=106.1s

  [5774/15692] intraday_14339.csv.gz  in=282,271,906 out=66,470,242 elapsed=106.1s

  [5775/15692] intraday_14342.csv.gz  in=282,282,061 out=66,480,397 elapsed=106.1s

  [5776/15692] intraday_14340.csv.gz  in=282,292,349 out=66,490,685 elapsed=106.2s

  [5777/15692] intraday_14341.csv.gz  in=282,304,760 out=66,503,096 elapsed=106.2s

  [5778/15692] intraday_14343.csv.gz  in=282,314,745 out=66,513,081 elapsed=106.2s

  [5779/15692] intraday_14344.csv.gz  in=282,326,400 out=66,524,736 elapsed=106.2s

  [5780/15692] intraday_14346.csv.gz  in=282,344,377 out=66,542,713 elapsed=106.2s

  [5781/15692] intraday_14348.csv.gz  in=282,357,474 out=66,555,810 elapsed=106.2s

  [5782/15692] intraday_14345.csv.gz  in=282,370,725 out=66,569,061 elapsed=106.2s

  [5783/15692] intraday_14347.csv.gz  in=282,382,461 out=66,580,797 elapsed=106.3s

  [5784/15692] intraday_14349.csv.gz  in=282,393,184 out=66,591,520 elapsed=106.3s

  [5785/15692] intraday_1435.csv.gz  in=282,406,938 out=66,591,520 elapsed=106.3s

  [5786/15692] intraday_14350.csv.gz  in=282,418,779 out=66,603,361 elapsed=106.3s

  [5787/15692] intraday_14352.csv.gz  in=282,433,049 out=66,617,631 elapsed=106.3s

  [5788/15692] intraday_14353.csv.gz  in=282,442,849 out=66,627,431 elapsed=106.3s

  [5789/15692] intraday_14354.csv.gz  in=282,458,005 out=66,642,587 elapsed=106.3s

  [5790/15692] intraday_14351.csv.gz  in=282,471,614 out=66,656,196 elapsed=106.3s

  [5791/15692] intraday_14357.csv.gz  in=282,471,655 out=66,656,237 elapsed=106.3s

  [5792/15692] intraday_14356.csv.gz  in=282,479,778 out=66,664,360 elapsed=106.4s

  [5793/15692] intraday_14355.csv.gz  in=282,490,744 out=66,675,326 elapsed=106.4s

  [5794/15692] intraday_14359.csv.gz  in=282,501,016 out=66,685,598 elapsed=106.4s

  [5795/15692] intraday_14358.csv.gz  in=282,513,602 out=66,698,184 elapsed=106.4s

  [5796/15692] intraday_1436.csv.gz  in=282,525,525 out=66,698,184 elapsed=106.4s

  [5797/15692] intraday_14360.csv.gz  in=282,537,119 out=66,709,778 elapsed=106.4s

  [5798/15692] intraday_14361.csv.gz  in=282,548,052 out=66,720,711 elapsed=106.4s

  [5799/15692] intraday_14363.csv.gz  in=282,561,447 out=66,734,106 elapsed=106.4s

  [5800/15692] intraday_14362.csv.gz  in=282,574,821 out=66,747,480 elapsed=106.5s

  [5801/15692] intraday_14364.csv.gz  in=282,586,288 out=66,758,947 elapsed=106.5s

  [5802/15692] intraday_14366.csv.gz  in=282,596,462 out=66,769,121 elapsed=106.5s

  [5803/15692] intraday_14365.csv.gz  in=282,607,927 out=66,780,586 elapsed=106.5s

  [5804/15692] intraday_14368.csv.gz  in=282,617,897 out=66,790,556 elapsed=106.5s

  [5805/15692] intraday_14367.csv.gz  in=282,632,851 out=66,805,510 elapsed=106.5s

  [5806/15692] intraday_14369.csv.gz  in=282,644,270 out=66,816,929 elapsed=106.5s

  [5807/15692] intraday_1437.csv.gz  in=282,658,980 out=66,816,929 elapsed=106.5s

  [5808/15692] intraday_14370.csv.gz  in=282,671,737 out=66,829,686 elapsed=106.5s

  [5809/15692] intraday_14371.csv.gz  in=282,686,317 out=66,844,266 elapsed=106.6s

  [5810/15692] intraday_14372.csv.gz  in=282,698,189 out=66,856,138 elapsed=106.6s

  [5811/15692] intraday_14373.csv.gz  in=282,709,979 out=66,867,928 elapsed=106.6s

  [5812/15692] intraday_14374.csv.gz  in=282,722,499 out=66,880,448 elapsed=106.6s

  [5813/15692] intraday_14375.csv.gz  in=282,734,804 out=66,892,753 elapsed=106.6s

  [5814/15692] intraday_14376.csv.gz  in=282,749,495 out=66,907,444 elapsed=106.7s

  [5815/15692] intraday_14377.csv.gz  in=282,764,590 out=66,922,539 elapsed=106.7s

  [5816/15692] intraday_14378.csv.gz  in=282,784,298 out=66,942,247 elapsed=106.7s

  [5817/15692] intraday_14379.csv.gz  in=282,794,802 out=66,952,751 elapsed=106.7s

  [5818/15692] intraday_1438.csv.gz  in=282,807,712 out=66,952,751 elapsed=106.7s

  [5819/15692] intraday_14380.csv.gz  in=282,823,133 out=66,968,172 elapsed=106.7s

  [5820/15692] intraday_14381.csv.gz  in=282,833,094 out=66,978,133 elapsed=106.7s

  [5821/15692] intraday_14382.csv.gz  in=282,846,103 out=66,991,142 elapsed=106.7s

  [5822/15692] intraday_14383.csv.gz  in=282,856,502 out=67,001,541 elapsed=106.7s

  [5823/15692] intraday_14385.csv.gz  in=282,866,486 out=67,011,525 elapsed=106.8s

  [5824/15692] intraday_14384.csv.gz  in=282,878,528 out=67,023,567 elapsed=106.8s

  [5825/15692] intraday_14387.csv.gz  in=282,888,623 out=67,033,662 elapsed=106.8s

  [5826/15692] intraday_14386.csv.gz  in=282,901,362 out=67,046,401 elapsed=106.8s

  [5827/15692] intraday_14388.csv.gz  in=282,917,970 out=67,063,009 elapsed=106.8s

  [5828/15692] intraday_1439.csv.gz  in=282,927,977 out=67,063,009 elapsed=106.8s

  [5829/15692] intraday_14389.csv.gz  in=282,936,795 out=67,071,827 elapsed=106.8s

  [5830/15692] intraday_14390.csv.gz  in=282,948,560 out=67,083,592 elapsed=106.8s

  [5831/15692] intraday_14392.csv.gz  in=282,962,069 out=67,097,101 elapsed=106.9s

  [5832/15692] intraday_14393.csv.gz  in=282,972,348 out=67,107,380 elapsed=106.9s

  [5833/15692] intraday_14391.csv.gz  in=282,983,219 out=67,118,251 elapsed=106.9s

  [5834/15692] intraday_14394.csv.gz  in=283,001,253 out=67,136,214 elapsed=106.9s

  [5835/15692] intraday_14395.csv.gz  in=283,015,031 out=67,149,992 elapsed=106.9s

  [5836/15692] intraday_14396.csv.gz  in=283,028,235 out=67,163,196 elapsed=106.9s

  [5837/15692] intraday_14397.csv.gz  in=283,041,941 out=67,176,902 elapsed=106.9s

  [5838/15692] intraday_14398.csv.gz  in=283,053,644 out=67,188,605 elapsed=106.9s

  [5839/15692] intraday_14399.csv.gz  in=283,064,072 out=67,199,033 elapsed=106.9s

  [5840/15692] intraday_1440.csv.gz  in=283,077,986 out=67,199,033 elapsed=106.9s

  [5841/15692] intraday_14400.csv.gz  in=283,090,766 out=67,211,813 elapsed=107.0s

  [5842/15692] intraday_14401.csv.gz  in=283,100,360 out=67,221,407 elapsed=107.0s

  [5843/15692] intraday_14402.csv.gz  in=283,113,089 out=67,234,136 elapsed=107.0s

  [5844/15692] intraday_14403.csv.gz  in=283,123,541 out=67,244,588 elapsed=107.0s

  [5845/15692] intraday_14405.csv.gz  in=283,137,892 out=67,258,939 elapsed=107.0s

  [5846/15692] intraday_14404.csv.gz  in=283,145,234 out=67,266,281 elapsed=107.0s

  [5847/15692] intraday_14406.csv.gz  in=283,145,915 out=67,266,962 elapsed=107.0s

  [5848/15692] intraday_14408.csv.gz  in=283,157,427 out=67,278,474 elapsed=107.1s

  [5849/15692] intraday_1441.csv.gz  in=283,171,965 out=67,278,474 elapsed=107.1s

  [5850/15692] intraday_14407.csv.gz  in=283,187,961 out=67,294,470 elapsed=107.1s

  [5851/15692] intraday_14409.csv.gz  in=283,201,213 out=67,307,722 elapsed=107.1s

  [5852/15692] intraday_14410.csv.gz  in=283,212,335 out=67,318,844 elapsed=107.1s

  [5853/15692] intraday_14411.csv.gz  in=283,223,823 out=67,330,332 elapsed=107.1s

  [5854/15692] intraday_14412.csv.gz  in=283,238,700 out=67,345,209 elapsed=107.1s

  [5855/15692] intraday_14413.csv.gz  in=283,250,747 out=67,357,256 elapsed=107.2s

  [5856/15692] intraday_14414.csv.gz  in=283,261,942 out=67,368,451 elapsed=107.2s

  [5857/15692] intraday_14415.csv.gz  in=283,274,483 out=67,380,992 elapsed=107.2s

  [5858/15692] intraday_14416.csv.gz  in=283,287,386 out=67,393,895 elapsed=107.2s

  [5859/15692] intraday_14417.csv.gz  in=283,298,195 out=67,404,704 elapsed=107.2s

  [5860/15692] intraday_14418.csv.gz  in=283,309,394 out=67,415,903 elapsed=107.2s

  [5861/15692] intraday_14419.csv.gz  in=283,321,313 out=67,427,822 elapsed=107.2s

  [5862/15692] intraday_1442.csv.gz  in=283,332,733 out=67,427,822 elapsed=107.2s

  [5863/15692] intraday_14420.csv.gz  in=283,333,527 out=67,428,616 elapsed=107.2s

  [5864/15692] intraday_14423.csv.gz  in=283,343,398 out=67,438,487 elapsed=107.3s

  [5865/15692] intraday_14421.csv.gz  in=283,356,627 out=67,451,716 elapsed=107.3s

  [5866/15692] intraday_14422.csv.gz  in=283,370,484 out=67,465,573 elapsed=107.3s

  [5867/15692] intraday_14424.csv.gz  in=283,382,057 out=67,477,146 elapsed=107.3s

  [5868/15692] intraday_14425.csv.gz  in=283,396,292 out=67,491,381 elapsed=107.3s

  [5869/15692] intraday_14426.csv.gz  in=283,407,749 out=67,502,838 elapsed=107.3s

  [5870/15692] intraday_14427.csv.gz  in=283,421,796 out=67,516,885 elapsed=107.3s

  [5871/15692] intraday_14428.csv.gz  in=283,433,256 out=67,528,345 elapsed=107.3s

  [5872/15692] intraday_14429.csv.gz  in=283,447,062 out=67,542,151 elapsed=107.4s

  [5873/15692] intraday_1443.csv.gz  in=283,462,021 out=67,542,151 elapsed=107.4s

  [5874/15692] intraday_14431.csv.gz  in=283,472,892 out=67,553,022 elapsed=107.4s

  [5875/15692] intraday_14430.csv.gz  in=283,484,850 out=67,564,980 elapsed=107.4s

  [5876/15692] intraday_14432.csv.gz  in=283,492,837 out=67,572,967 elapsed=107.4s

  [5877/15692] intraday_14433.csv.gz  in=283,497,769 out=67,577,899 elapsed=107.4s

  [5878/15692] intraday_14435.csv.gz  in=283,506,919 out=67,587,049 elapsed=107.5s

  [5879/15692] intraday_14437.csv.gz  in=283,519,352 out=67,599,482 elapsed=107.5s

  [5880/15692] intraday_14434.csv.gz  in=283,532,379 out=67,612,509 elapsed=107.5s

  [5881/15692] intraday_14436.csv.gz  in=283,545,008 out=67,625,138 elapsed=107.5s

  [5882/15692] intraday_14439.csv.gz  in=283,557,495 out=67,637,625 elapsed=107.5s

  [5883/15692] intraday_14438.csv.gz  in=283,570,379 out=67,650,509 elapsed=107.5s

  [5884/15692] intraday_1444.csv.gz  in=283,584,490 out=67,650,509 elapsed=107.5s

  [5885/15692] intraday_14440.csv.gz  in=283,594,323 out=67,660,342 elapsed=107.5s

  [5886/15692] intraday_14441.csv.gz  in=283,605,044 out=67,671,063 elapsed=107.6s

  [5887/15692] intraday_14442.csv.gz  in=283,613,952 out=67,679,971 elapsed=107.6s

  [5888/15692] intraday_14443.csv.gz  in=283,624,182 out=67,690,201 elapsed=107.6s

  [5889/15692] intraday_14444.csv.gz  in=283,636,478 out=67,702,497 elapsed=107.6s

  [5890/15692] intraday_14445.csv.gz  in=283,643,704 out=67,709,723 elapsed=107.6s

  [5891/15692] intraday_14447.csv.gz  in=283,655,754 out=67,721,773 elapsed=107.6s

  [5892/15692] intraday_14446.csv.gz  in=283,662,153 out=67,728,172 elapsed=107.6s

  [5893/15692] intraday_14449.csv.gz  in=283,673,372 out=67,739,391 elapsed=107.7s

  [5894/15692] intraday_14448.csv.gz  in=283,684,903 out=67,750,922 elapsed=107.7s

  [5895/15692] intraday_1445.csv.gz  in=283,695,594 out=67,750,922 elapsed=107.7s

  [5896/15692] intraday_14450.csv.gz  in=283,706,939 out=67,762,267 elapsed=107.7s

  [5897/15692] intraday_14451.csv.gz  in=283,716,926 out=67,772,254 elapsed=107.7s

  [5898/15692] intraday_14452.csv.gz  in=283,729,257 out=67,784,585 elapsed=107.7s

  [5899/15692] intraday_14453.csv.gz  in=283,741,577 out=67,796,905 elapsed=107.7s

  [5900/15692] intraday_14454.csv.gz  in=283,754,032 out=67,809,360 elapsed=107.7s

  [5901/15692] intraday_14456.csv.gz  in=283,765,404 out=67,820,732 elapsed=107.8s

  [5902/15692] intraday_14455.csv.gz  in=283,777,859 out=67,833,187 elapsed=107.8s

  [5903/15692] intraday_14457.csv.gz  in=283,789,491 out=67,844,819 elapsed=107.8s

  [5904/15692] intraday_14459.csv.gz  in=283,801,231 out=67,856,559 elapsed=107.8s

  [5905/15692] intraday_14458.csv.gz  in=283,810,962 out=67,866,290 elapsed=107.8s

  [5906/15692] intraday_1446.csv.gz  in=283,823,582 out=67,866,290 elapsed=107.8s

  [5907/15692] intraday_14460.csv.gz  in=283,829,913 out=67,872,621 elapsed=107.8s

  [5908/15692] intraday_14461.csv.gz  in=283,840,403 out=67,883,111 elapsed=107.9s

  [5909/15692] intraday_14462.csv.gz  in=283,850,729 out=67,893,437 elapsed=107.9s

  [5910/15692] intraday_14463.csv.gz  in=283,860,733 out=67,903,441 elapsed=107.9s

  [5911/15692] intraday_14464.csv.gz  in=283,875,134 out=67,917,842 elapsed=107.9s

  [5912/15692] intraday_14465.csv.gz  in=283,888,803 out=67,931,511 elapsed=107.9s

  [5913/15692] intraday_14466.csv.gz  in=283,901,260 out=67,943,968 elapsed=107.9s

  [5914/15692] intraday_14467.csv.gz  in=283,914,399 out=67,957,107 elapsed=108.0s

  [5915/15692] intraday_14468.csv.gz  in=283,923,718 out=67,966,426 elapsed=108.0s

  [5916/15692] intraday_14469.csv.gz  in=283,934,984 out=67,977,692 elapsed=108.0s

  [5917/15692] intraday_1447.csv.gz  in=283,947,950 out=67,977,692 elapsed=108.0s

  [5918/15692] intraday_14470.csv.gz  in=283,960,495 out=67,990,237 elapsed=108.0s

  [5919/15692] intraday_14471.csv.gz  in=283,971,541 out=68,001,283 elapsed=108.0s

  [5920/15692] intraday_14473.csv.gz  in=283,974,750 out=68,004,492 elapsed=108.0s

  [5921/15692] intraday_14472.csv.gz  in=283,986,817 out=68,016,559 elapsed=108.0s

  [5922/15692] intraday_14474.csv.gz  in=283,990,050 out=68,019,792 elapsed=108.0s

  [5923/15692] intraday_14475.csv.gz  in=284,003,748 out=68,033,490 elapsed=108.1s

  [5924/15692] intraday_14476.csv.gz  in=284,015,770 out=68,045,512 elapsed=108.1s

  [5925/15692] intraday_14477.csv.gz  in=284,028,811 out=68,058,553 elapsed=108.1s

  [5926/15692] intraday_14479.csv.gz  in=284,038,931 out=68,068,673 elapsed=108.1s

  [5927/15692] intraday_14478.csv.gz  in=284,049,203 out=68,078,945 elapsed=108.1s

  [5928/15692] intraday_1448.csv.gz  in=284,063,228 out=68,078,945 elapsed=108.1s

  [5929/15692] intraday_14480.csv.gz  in=284,076,326 out=68,092,043 elapsed=108.1s

  [5930/15692] intraday_14481.csv.gz  in=284,092,126 out=68,107,843 elapsed=108.1s

  [5931/15692] intraday_14483.csv.gz  in=284,106,602 out=68,122,319 elapsed=108.2s

  [5932/15692] intraday_14482.csv.gz  in=284,120,649 out=68,136,366 elapsed=108.2s

  [5933/15692] intraday_14484.csv.gz  in=284,138,098 out=68,153,755 elapsed=108.2s

  [5934/15692] intraday_14485.csv.gz  in=284,149,594 out=68,165,251 elapsed=108.2s

  [5935/15692] intraday_14486.csv.gz  in=284,161,837 out=68,177,458 elapsed=108.2s

  [5936/15692] intraday_14487.csv.gz  in=284,179,037 out=68,194,658 elapsed=108.2s

  [5937/15692] intraday_14489.csv.gz  in=284,189,971 out=68,205,592 elapsed=108.2s

  [5938/15692] intraday_14488.csv.gz  in=284,201,312 out=68,216,933 elapsed=108.3s

  [5939/15692] intraday_1449.csv.gz  in=284,212,910 out=68,216,933 elapsed=108.3s

  [5940/15692] intraday_14491.csv.gz  in=284,219,215 out=68,223,238 elapsed=108.3s

  [5941/15692] intraday_14490.csv.gz  in=284,233,627 out=68,237,650 elapsed=108.3s

  [5942/15692] intraday_14492.csv.gz  in=284,233,786 out=68,237,809 elapsed=108.3s

  [5943/15692] intraday_14493.csv.gz  in=284,244,765 out=68,248,788 elapsed=108.3s

  [5944/15692] intraday_14494.csv.gz  in=284,256,651 out=68,260,674 elapsed=108.3s

  [5945/15692] intraday_14496.csv.gz  in=284,267,073 out=68,271,096 elapsed=108.3s

  [5946/15692] intraday_14495.csv.gz  in=284,279,023 out=68,283,046 elapsed=108.4s

  [5947/15692] intraday_14497.csv.gz  in=284,290,949 out=68,294,972 elapsed=108.4s

  [5948/15692] intraday_14498.csv.gz  in=284,304,532 out=68,308,555 elapsed=108.4s

  [5949/15692] intraday_1450.csv.gz  in=284,323,766 out=68,308,555 elapsed=108.4s

  [5950/15692] intraday_14499.csv.gz  in=284,337,401 out=68,322,190 elapsed=108.4s

  [5951/15692] intraday_14500.csv.gz  in=284,349,247 out=68,334,036 elapsed=108.4s

  [5952/15692] intraday_14504.csv.gz  in=284,358,884 out=68,343,673 elapsed=108.5s

  [5953/15692] intraday_14501.csv.gz  in=284,370,384 out=68,355,173 elapsed=108.5s

  [5954/15692] intraday_14502.csv.gz  in=284,380,889 out=68,365,678 elapsed=108.5s

  [5955/15692] intraday_14503.csv.gz  in=284,396,043 out=68,380,832 elapsed=108.5s

  [5956/15692] intraday_14505.csv.gz  in=284,407,015 out=68,391,804 elapsed=108.5s

  [5957/15692] intraday_14507.csv.gz  in=284,421,855 out=68,406,644 elapsed=108.5s

  [5958/15692] intraday_14506.csv.gz  in=284,435,519 out=68,420,308 elapsed=108.5s

  [5959/15692] intraday_14508.csv.gz  in=284,445,748 out=68,430,537 elapsed=108.6s

  [5960/15692] intraday_14509.csv.gz  in=284,465,438 out=68,450,018 elapsed=108.6s

  [5961/15692] intraday_1451.csv.gz  in=284,477,805 out=68,450,018 elapsed=108.6s

  [5962/15692] intraday_14510.csv.gz  in=284,489,849 out=68,462,062 elapsed=108.6s

  [5963/15692] intraday_14511.csv.gz  in=284,503,460 out=68,475,673 elapsed=108.6s

  [5964/15692] intraday_14512.csv.gz  in=284,517,203 out=68,489,416 elapsed=108.6s

  [5965/15692] intraday_14513.csv.gz  in=284,534,650 out=68,506,863 elapsed=108.6s

  [5966/15692] intraday_14515.csv.gz  in=284,548,080 out=68,520,293 elapsed=108.6s

  [5967/15692] intraday_14516.csv.gz  in=284,561,124 out=68,533,337 elapsed=108.7s

  [5968/15692] intraday_14514.csv.gz  in=284,578,591 out=68,550,804 elapsed=108.7s

  [5969/15692] intraday_14518.csv.gz  in=284,590,971 out=68,563,184 elapsed=108.7s

  [5970/15692] intraday_14519.csv.gz  in=284,600,294 out=68,572,507 elapsed=108.7s

  [5971/15692] intraday_1452.csv.gz  in=284,612,766 out=68,572,507 elapsed=108.7s

  [5972/15692] intraday_14517.csv.gz  in=284,623,688 out=68,583,429 elapsed=108.7s

  [5973/15692] intraday_14520.csv.gz  in=284,636,862 out=68,596,603 elapsed=108.7s

  [5974/15692] intraday_14522.csv.gz  in=284,647,886 out=68,607,621 elapsed=108.7s

  [5975/15692] intraday_14521.csv.gz  in=284,657,997 out=68,617,732 elapsed=108.7s

  [5976/15692] intraday_14523.csv.gz  in=284,670,214 out=68,629,949 elapsed=108.8s

  [5977/15692] intraday_14524.csv.gz  in=284,684,011 out=68,643,746 elapsed=108.8s

  [5978/15692] intraday_14525.csv.gz  in=284,694,898 out=68,654,633 elapsed=108.8s

  [5979/15692] intraday_14526.csv.gz  in=284,705,082 out=68,664,817 elapsed=108.8s

  [5980/15692] intraday_14527.csv.gz  in=284,716,864 out=68,676,599 elapsed=108.8s

  [5981/15692] intraday_14528.csv.gz  in=284,730,048 out=68,689,783 elapsed=108.8s

  [5982/15692] intraday_1453.csv.gz  in=284,742,551 out=68,689,783 elapsed=108.8s

  [5983/15692] intraday_14529.csv.gz  in=284,754,171 out=68,701,403 elapsed=108.8s

  [5984/15692] intraday_14530.csv.gz  in=284,767,835 out=68,715,067 elapsed=108.8s

  [5985/15692] intraday_14531.csv.gz  in=284,781,446 out=68,728,678 elapsed=108.8s

  [5986/15692] intraday_14532.csv.gz  in=284,794,618 out=68,741,850 elapsed=108.8s

  [5987/15692] intraday_14533.csv.gz  in=284,810,045 out=68,757,277 elapsed=108.8s

  [5988/15692] intraday_14534.csv.gz  in=284,820,542 out=68,767,774 elapsed=108.9s

  [5989/15692] intraday_14535.csv.gz  in=284,834,170 out=68,781,402 elapsed=108.9s

  [5990/15692] intraday_14536.csv.gz  in=284,847,625 out=68,794,857 elapsed=108.9s

  [5991/15692] intraday_14537.csv.gz  in=284,858,085 out=68,805,317 elapsed=108.9s

  [5992/15692] intraday_14538.csv.gz  in=284,870,486 out=68,817,718 elapsed=108.9s

  [5993/15692] intraday_14539.csv.gz  in=284,879,362 out=68,826,594 elapsed=108.9s

  [5994/15692] intraday_1454.csv.gz  in=284,892,106 out=68,826,594 elapsed=108.9s

  [5995/15692] intraday_14540.csv.gz  in=284,903,710 out=68,838,198 elapsed=108.9s

  [5996/15692] intraday_14541.csv.gz  in=284,912,437 out=68,846,925 elapsed=109.0s

  [5997/15692] intraday_14542.csv.gz  in=284,926,933 out=68,861,421 elapsed=109.0s

  [5998/15692] intraday_14543.csv.gz  in=284,938,390 out=68,872,878 elapsed=109.0s

  [5999/15692] intraday_14544.csv.gz  in=284,953,003 out=68,887,491 elapsed=109.0s

  [6000/15692] intraday_14546.csv.gz  in=284,964,266 out=68,898,754 elapsed=109.0s

  [6001/15692] intraday_14545.csv.gz  in=284,975,380 out=68,909,868 elapsed=109.0s

  [6002/15692] intraday_14547.csv.gz  in=284,987,842 out=68,922,330 elapsed=109.0s

  [6003/15692] intraday_14548.csv.gz  in=285,000,327 out=68,934,815 elapsed=109.0s

  [6004/15692] intraday_1455.csv.gz  in=285,012,568 out=68,934,815 elapsed=109.0s

  [6005/15692] intraday_14549.csv.gz  in=285,024,169 out=68,946,416 elapsed=109.0s

  [6006/15692] intraday_14550.csv.gz  in=285,037,301 out=68,959,548 elapsed=109.1s

  [6007/15692] intraday_14551.csv.gz  in=285,049,470 out=68,971,717 elapsed=109.1s

  [6008/15692] intraday_14552.csv.gz  in=285,059,640 out=68,981,887 elapsed=109.1s

  [6009/15692] intraday_14553.csv.gz  in=285,069,975 out=68,992,222 elapsed=109.1s

  [6010/15692] intraday_14554.csv.gz  in=285,081,197 out=69,003,444 elapsed=109.1s

  [6011/15692] intraday_14555.csv.gz  in=285,082,363 out=69,004,610 elapsed=109.1s

  [6012/15692] intraday_14556.csv.gz  in=285,090,704 out=69,012,951 elapsed=109.1s

  [6013/15692] intraday_14557.csv.gz  in=285,108,670 out=69,030,754 elapsed=109.1s

  [6014/15692] intraday_14558.csv.gz  in=285,118,644 out=69,040,728 elapsed=109.1s

  [6015/15692] intraday_14559.csv.gz  in=285,128,914 out=69,050,998 elapsed=109.1s

  [6016/15692] intraday_1456.csv.gz  in=285,140,022 out=69,050,998 elapsed=109.1s

  [6017/15692] intraday_14560.csv.gz  in=285,154,573 out=69,065,549 elapsed=109.2s

  [6018/15692] intraday_14561.csv.gz  in=285,166,061 out=69,077,037 elapsed=109.2s

  [6019/15692] intraday_14562.csv.gz  in=285,178,289 out=69,089,265 elapsed=109.2s

  [6020/15692] intraday_14563.csv.gz  in=285,190,206 out=69,101,182 elapsed=109.2s

  [6021/15692] intraday_14564.csv.gz  in=285,203,232 out=69,114,208 elapsed=109.2s

  [6022/15692] intraday_14565.csv.gz  in=285,216,081 out=69,127,057 elapsed=109.2s

  [6023/15692] intraday_14566.csv.gz  in=285,225,882 out=69,136,858 elapsed=109.2s

  [6024/15692] intraday_14567.csv.gz  in=285,237,589 out=69,148,565 elapsed=109.2s

  [6025/15692] intraday_14568.csv.gz  in=285,247,925 out=69,158,901 elapsed=109.3s

  [6026/15692] intraday_14569.csv.gz  in=285,260,621 out=69,171,597 elapsed=109.3s

  [6027/15692] intraday_1457.csv.gz  in=285,273,184 out=69,171,597 elapsed=109.3s

  [6028/15692] intraday_14571.csv.gz  in=285,273,232 out=69,171,645 elapsed=109.3s

  [6029/15692] intraday_14570.csv.gz  in=285,285,100 out=69,183,513 elapsed=109.3s

  [6030/15692] intraday_14573.csv.gz  in=285,297,134 out=69,195,547 elapsed=109.3s

  [6031/15692] intraday_14572.csv.gz  in=285,314,305 out=69,212,107 elapsed=109.3s

  [6032/15692] intraday_14574.csv.gz  in=285,325,900 out=69,223,702 elapsed=109.3s

  [6033/15692] intraday_14575.csv.gz  in=285,335,313 out=69,233,115 elapsed=109.4s

  [6034/15692] intraday_14577.csv.gz  in=285,343,586 out=69,241,323 elapsed=109.4s

  [6035/15692] intraday_14576.csv.gz  in=285,355,692 out=69,253,429 elapsed=109.4s

  [6036/15692] intraday_14578.csv.gz  in=285,365,999 out=69,263,736 elapsed=109.4s

  [6037/15692] intraday_1458.csv.gz  in=285,378,881 out=69,263,736 elapsed=109.4s

  [6038/15692] intraday_14579.csv.gz  in=285,391,308 out=69,276,163 elapsed=109.4s

  [6039/15692] intraday_14580.csv.gz  in=285,403,478 out=69,288,333 elapsed=109.4s

  [6040/15692] intraday_14581.csv.gz  in=285,416,008 out=69,300,863 elapsed=109.4s

  [6041/15692] intraday_14582.csv.gz  in=285,430,631 out=69,315,486 elapsed=109.4s

  [6042/15692] intraday_14585.csv.gz  in=285,432,815 out=69,317,670 elapsed=109.5s

  [6043/15692] intraday_14583.csv.gz  in=285,456,246 out=69,340,055 elapsed=109.5s

  [6044/15692] intraday_14584.csv.gz  in=285,463,181 out=69,346,990 elapsed=109.5s

  [6045/15692] intraday_14586.csv.gz  in=285,473,297 out=69,357,106 elapsed=109.5s

  [6046/15692] intraday_14587.csv.gz  in=285,485,400 out=69,369,209 elapsed=109.5s

  [6047/15692] intraday_14589.csv.gz  in=285,496,854 out=69,380,663 elapsed=109.5s

  [6048/15692] intraday_14588.csv.gz  in=285,511,604 out=69,395,413 elapsed=109.5s

  [6049/15692] intraday_1459.csv.gz  in=285,528,660 out=69,395,413 elapsed=109.5s

  [6050/15692] intraday_14591.csv.gz  in=285,540,681 out=69,407,434 elapsed=109.6s

  [6051/15692] intraday_14590.csv.gz  in=285,551,520 out=69,418,273 elapsed=109.6s

  [6052/15692] intraday_14593.csv.gz  in=285,560,903 out=69,427,656 elapsed=109.6s

  [6053/15692] intraday_14594.csv.gz  in=285,571,917 out=69,438,670 elapsed=109.6s

  [6054/15692] intraday_14592.csv.gz  in=285,583,454 out=69,450,207 elapsed=109.6s

  [6055/15692] intraday_14595.csv.gz  in=285,595,346 out=69,462,099 elapsed=109.6s

  [6056/15692] intraday_14598.csv.gz  in=285,601,894 out=69,468,647 elapsed=109.6s

  [6057/15692] intraday_14596.csv.gz  in=285,612,304 out=69,479,057 elapsed=109.7s

  [6058/15692] intraday_14597.csv.gz  in=285,623,867 out=69,490,620 elapsed=109.7s

  [6059/15692] intraday_1460.csv.gz  in=285,635,744 out=69,490,620 elapsed=109.7s

  [6060/15692] intraday_14599.csv.gz  in=285,644,010 out=69,498,886 elapsed=109.7s

  [6061/15692] intraday_14601.csv.gz  in=285,657,608 out=69,512,484 elapsed=109.7s

  [6062/15692] intraday_14600.csv.gz  in=285,670,835 out=69,525,711 elapsed=109.7s

  [6063/15692] intraday_14602.csv.gz  in=285,682,509 out=69,537,385 elapsed=109.7s

  [6064/15692] intraday_14603.csv.gz  in=285,692,651 out=69,547,527 elapsed=109.7s

  [6065/15692] intraday_14604.csv.gz  in=285,702,836 out=69,557,712 elapsed=109.8s

  [6066/15692] intraday_14607.csv.gz  in=285,714,293 out=69,569,169 elapsed=109.8s

  [6067/15692] intraday_14605.csv.gz  in=285,726,104 out=69,580,980 elapsed=109.8s

  [6068/15692] intraday_14606.csv.gz  in=285,738,298 out=69,592,970 elapsed=109.8s

  [6069/15692] intraday_14608.csv.gz  in=285,750,531 out=69,605,203 elapsed=109.8s

  [6070/15692] intraday_14609.csv.gz  in=285,760,397 out=69,615,069 elapsed=109.8s

  [6071/15692] intraday_1461.csv.gz  in=285,771,947 out=69,615,069 elapsed=109.8s

  [6072/15692] intraday_14610.csv.gz  in=285,780,270 out=69,623,392 elapsed=109.8s

  [6073/15692] intraday_14611.csv.gz  in=285,793,084 out=69,636,206 elapsed=109.9s

  [6074/15692] intraday_14613.csv.gz  in=285,795,766 out=69,638,888 elapsed=109.9s

  [6075/15692] intraday_14612.csv.gz  in=285,797,143 out=69,640,265 elapsed=109.9s

  [6076/15692] intraday_14614.csv.gz  in=285,806,690 out=69,649,812 elapsed=109.9s

  [6077/15692] intraday_14615.csv.gz  in=285,817,800 out=69,660,922 elapsed=109.9s

  [6078/15692] intraday_14616.csv.gz  in=285,831,056 out=69,674,178 elapsed=109.9s

  [6079/15692] intraday_14618.csv.gz  in=285,844,605 out=69,687,727 elapsed=109.9s

  [6080/15692] intraday_14619.csv.gz  in=285,856,318 out=69,699,440 elapsed=109.9s

  [6081/15692] intraday_14617.csv.gz  in=285,872,284 out=69,715,406 elapsed=109.9s

  [6082/15692] intraday_1462.csv.gz  in=285,884,516 out=69,715,406 elapsed=109.9s

  [6083/15692] intraday_14620.csv.gz  in=285,894,974 out=69,725,864 elapsed=110.0s

  [6084/15692] intraday_14621.csv.gz  in=285,906,236 out=69,737,126 elapsed=110.0s

  [6085/15692] intraday_14622.csv.gz  in=285,919,973 out=69,750,863 elapsed=110.0s

  [6086/15692] intraday_14623.csv.gz  in=285,931,883 out=69,762,773 elapsed=110.0s

  [6087/15692] intraday_14624.csv.gz  in=285,941,485 out=69,772,375 elapsed=110.0s

  [6088/15692] intraday_14626.csv.gz  in=285,951,337 out=69,782,227 elapsed=110.1s

  [6089/15692] intraday_14627.csv.gz  in=285,961,916 out=69,792,806 elapsed=110.1s

  [6090/15692] intraday_14628.csv.gz  in=285,974,170 out=69,805,060 elapsed=110.1s

  [6091/15692] intraday_14625.csv.gz  in=285,988,205 out=69,819,095 elapsed=110.1s

  [6092/15692] intraday_14629.csv.gz  in=285,999,450 out=69,830,340 elapsed=110.1s

  [6093/15692] intraday_14630.csv.gz  in=286,011,115 out=69,842,005 elapsed=110.1s

  [6094/15692] intraday_1463.csv.gz  in=286,024,301 out=69,842,005 elapsed=110.2s

  [6095/15692] intraday_14632.csv.gz  in=286,034,801 out=69,852,505 elapsed=110.2s

  [6096/15692] intraday_14631.csv.gz  in=286,044,953 out=69,862,657 elapsed=110.2s

  [6097/15692] intraday_14633.csv.gz  in=286,057,323 out=69,875,027 elapsed=110.2s

  [6098/15692] intraday_14635.csv.gz  in=286,070,101 out=69,887,805 elapsed=110.2s

  [6099/15692] intraday_14634.csv.gz  in=286,085,482 out=69,903,186 elapsed=110.2s

  [6100/15692] intraday_14637.csv.gz  in=286,096,946 out=69,914,650 elapsed=110.2s

  [6101/15692] intraday_14636.csv.gz  in=286,108,672 out=69,926,376 elapsed=110.2s

  [6102/15692] intraday_14638.csv.gz  in=286,118,445 out=69,936,149 elapsed=110.3s

  [6103/15692] intraday_14639.csv.gz  in=286,131,692 out=69,949,396 elapsed=110.3s

  [6104/15692] intraday_14640.csv.gz  in=286,142,737 out=69,960,441 elapsed=110.3s

  [6105/15692] intraday_14641.csv.gz  in=286,153,701 out=69,971,405 elapsed=110.3s

  [6106/15692] intraday_1464.csv.gz  in=286,170,395 out=69,971,405 elapsed=110.3s

  [6107/15692] intraday_14642.csv.gz  in=286,183,978 out=69,984,988 elapsed=110.3s

  [6108/15692] intraday_14643.csv.gz  in=286,197,828 out=69,998,838 elapsed=110.3s

  [6109/15692] intraday_14644.csv.gz  in=286,209,029 out=70,010,039 elapsed=110.3s

  [6110/15692] intraday_14645.csv.gz  in=286,220,389 out=70,021,399 elapsed=110.3s

  [6111/15692] intraday_14646.csv.gz  in=286,232,626 out=70,033,636 elapsed=110.4s

  [6112/15692] intraday_14648.csv.gz  in=286,246,252 out=70,047,262 elapsed=110.4s

  [6113/15692] intraday_14647.csv.gz  in=286,257,568 out=70,058,578 elapsed=110.4s

  [6114/15692] intraday_14649.csv.gz  in=286,271,334 out=70,072,344 elapsed=110.4s

  [6115/15692] intraday_1465.csv.gz  in=286,284,667 out=70,072,344 elapsed=110.4s

  [6116/15692] intraday_14650.csv.gz  in=286,301,990 out=70,089,667 elapsed=110.4s

  [6117/15692] intraday_14651.csv.gz  in=286,313,781 out=70,101,458 elapsed=110.4s

  [6118/15692] intraday_14652.csv.gz  in=286,328,060 out=70,115,737 elapsed=110.4s

  [6119/15692] intraday_14653.csv.gz  in=286,338,258 out=70,125,935 elapsed=110.4s

  [6120/15692] intraday_14656.csv.gz  in=286,350,111 out=70,137,788 elapsed=110.5s

  [6121/15692] intraday_14654.csv.gz  in=286,362,396 out=70,150,073 elapsed=110.5s

  [6122/15692] intraday_14657.csv.gz  in=286,372,661 out=70,160,338 elapsed=110.5s

  [6123/15692] intraday_14655.csv.gz  in=286,383,324 out=70,171,001 elapsed=110.5s

  [6124/15692] intraday_14658.csv.gz  in=286,395,499 out=70,183,176 elapsed=110.5s

  [6125/15692] intraday_14659.csv.gz  in=286,406,319 out=70,193,996 elapsed=110.5s

  [6126/15692] intraday_1466.csv.gz  in=286,420,668 out=70,193,996 elapsed=110.5s

  [6127/15692] intraday_14661.csv.gz  in=286,429,697 out=70,203,025 elapsed=110.5s

  [6128/15692] intraday_14660.csv.gz  in=286,443,777 out=70,217,105 elapsed=110.6s

  [6129/15692] intraday_14662.csv.gz  in=286,454,159 out=70,227,487 elapsed=110.6s

  [6130/15692] intraday_14663.csv.gz  in=286,464,880 out=70,238,208 elapsed=110.6s

  [6131/15692] intraday_14664.csv.gz  in=286,478,052 out=70,251,380 elapsed=110.6s

  [6132/15692] intraday_14665.csv.gz  in=286,490,846 out=70,264,102 elapsed=110.6s

  [6133/15692] intraday_14666.csv.gz  in=286,503,991 out=70,277,247 elapsed=110.6s

  [6134/15692] intraday_14667.csv.gz  in=286,517,087 out=70,290,343 elapsed=110.6s

  [6135/15692] intraday_14668.csv.gz  in=286,530,780 out=70,304,036 elapsed=110.6s

  [6136/15692] intraday_14669.csv.gz  in=286,543,294 out=70,316,550 elapsed=110.6s

  [6137/15692] intraday_1467.csv.gz  in=286,558,612 out=70,316,550 elapsed=110.6s

  [6138/15692] intraday_14670.csv.gz  in=286,570,212 out=70,328,150 elapsed=110.6s

  [6139/15692] intraday_14673.csv.gz  in=286,580,313 out=70,338,251 elapsed=110.7s

  [6140/15692] intraday_14671.csv.gz  in=286,592,467 out=70,350,405 elapsed=110.7s

  [6141/15692] intraday_14672.csv.gz  in=286,604,831 out=70,362,769 elapsed=110.7s

  [6142/15692] intraday_14674.csv.gz  in=286,620,019 out=70,377,957 elapsed=110.7s

  [6143/15692] intraday_14675.csv.gz  in=286,630,706 out=70,388,644 elapsed=110.7s

  [6144/15692] intraday_14676.csv.gz  in=286,639,419 out=70,397,357 elapsed=110.7s

  [6145/15692] intraday_14678.csv.gz  in=286,639,651 out=70,397,589 elapsed=110.7s

  [6146/15692] intraday_14679.csv.gz  in=286,640,552 out=70,398,490 elapsed=110.7s

  [6147/15692] intraday_14680.csv.gz  in=286,640,705 out=70,398,643 elapsed=110.7s

  [6148/15692] intraday_14677.csv.gz  in=286,652,827 out=70,410,765 elapsed=110.7s

  [6149/15692] intraday_14681.csv.gz  in=286,653,345 out=70,411,283 elapsed=110.7s

  [6150/15692] intraday_14682.csv.gz  in=286,653,613 out=70,411,551 elapsed=110.7s

  [6151/15692] intraday_1468.csv.gz  in=286,669,484 out=70,411,551 elapsed=110.7s

  [6152/15692] intraday_14684.csv.gz  in=286,670,040 out=70,412,107 elapsed=110.8s

  [6153/15692] intraday_14685.csv.gz  in=286,670,612 out=70,412,679 elapsed=110.8s

  [6154/15692] intraday_14687.csv.gz  in=286,670,972 out=70,413,039 elapsed=110.8s

  [6155/15692] intraday_14686.csv.gz  in=286,671,195 out=70,413,262 elapsed=110.8s

  [6156/15692] intraday_14683.csv.gz  in=286,671,586 out=70,413,653 elapsed=110.8s

  [6157/15692] intraday_14690.csv.gz  in=286,671,966 out=70,414,033 elapsed=110.8s

  [6158/15692] intraday_14688.csv.gz  in=286,672,190 out=70,414,257 elapsed=110.8s

  [6159/15692] intraday_14689.csv.gz  in=286,673,020 out=70,415,087 elapsed=110.8s

  [6160/15692] intraday_1469.csv.gz  in=286,687,617 out=70,415,087 elapsed=110.8s

  [6161/15692] intraday_14691.csv.gz  in=286,688,045 out=70,415,515 elapsed=110.8s

  [6162/15692] intraday_14693.csv.gz  in=286,688,413 out=70,415,883 elapsed=110.8s

  [6163/15692] intraday_14692.csv.gz  in=286,689,047 out=70,416,517 elapsed=110.8s

  [6164/15692] intraday_14694.csv.gz  in=286,689,185 out=70,416,655 elapsed=110.8s

  [6165/15692] intraday_14695.csv.gz  in=286,689,935 out=70,417,405 elapsed=110.8s

  [6166/15692] intraday_14696.csv.gz  in=286,690,470 out=70,417,940 elapsed=110.8s

  [6167/15692] intraday_14698.csv.gz  in=286,690,798 out=70,418,268 elapsed=110.8s

  [6168/15692] intraday_14697.csv.gz  in=286,691,042 out=70,418,512 elapsed=110.8s

  [6169/15692] intraday_14699.csv.gz  in=286,691,613 out=70,419,083 elapsed=110.8s

  [6170/15692] intraday_14700.csv.gz  in=286,691,745 out=70,419,215 elapsed=110.8s

  [6171/15692] intraday_14702.csv.gz  in=286,692,004 out=70,419,474 elapsed=110.8s

  [6172/15692] intraday_14701.csv.gz  in=286,692,436 out=70,419,906 elapsed=110.8s

  [6173/15692] intraday_14703.csv.gz  in=286,692,793 out=70,420,263 elapsed=110.8s

  [6174/15692] intraday_14704.csv.gz  in=286,693,101 out=70,420,571 elapsed=110.8s

  [6175/15692] intraday_1470.csv.gz  in=286,706,950 out=70,420,571 elapsed=110.9s

  [6176/15692] intraday_14706.csv.gz  in=286,707,005 out=70,420,626 elapsed=110.9s

  [6177/15692] intraday_14705.csv.gz  in=286,707,319 out=70,420,940 elapsed=110.9s

  [6178/15692] intraday_14708.csv.gz  in=286,707,921 out=70,421,542 elapsed=110.9s

  [6179/15692] intraday_14707.csv.gz  in=286,708,577 out=70,422,198 elapsed=110.9s

  [6180/15692] intraday_14709.csv.gz  in=286,709,505 out=70,423,126 elapsed=110.9s

  [6181/15692] intraday_14710.csv.gz  in=286,709,801 out=70,423,422 elapsed=110.9s

  [6182/15692] intraday_14711.csv.gz  in=286,709,994 out=70,423,615 elapsed=110.9s

  [6183/15692] intraday_14713.csv.gz  in=286,710,185 out=70,423,806 elapsed=110.9s

  [6184/15692] intraday_1471.csv.gz  in=286,724,033 out=70,423,806 elapsed=110.9s

  [6185/15692] intraday_14712.csv.gz  in=286,724,380 out=70,424,153 elapsed=110.9s

  [6186/15692] intraday_14714.csv.gz  in=286,724,691 out=70,424,464 elapsed=110.9s

  [6187/15692] intraday_14715.csv.gz  in=286,725,046 out=70,424,819 elapsed=110.9s

  [6188/15692] intraday_14716.csv.gz  in=286,725,402 out=70,425,175 elapsed=110.9s

  [6189/15692] intraday_14717.csv.gz  in=286,725,553 out=70,425,326 elapsed=110.9s

  [6190/15692] intraday_14719.csv.gz  in=286,725,619 out=70,425,392 elapsed=110.9s

  [6191/15692] intraday_14718.csv.gz  in=286,725,683 out=70,425,456 elapsed=110.9s

  [6192/15692] intraday_14722.csv.gz  in=286,725,746 out=70,425,519 elapsed=110.9s

  [6193/15692] intraday_14721.csv.gz  in=286,726,366 out=70,426,139 elapsed=110.9s

  [6194/15692] intraday_14720.csv.gz  in=286,726,684 out=70,426,457 elapsed=110.9s

  [6195/15692] intraday_1472.csv.gz  in=286,739,999 out=70,426,457 elapsed=110.9s

  [6196/15692] intraday_14723.csv.gz  in=286,740,360 out=70,426,818 elapsed=110.9s

  [6197/15692] intraday_14724.csv.gz  in=286,740,524 out=70,426,982 elapsed=110.9s

  [6198/15692] intraday_14728.csv.gz  in=286,740,670 out=70,427,128 elapsed=110.9s

  [6199/15692] intraday_14726.csv.gz  in=286,740,860 out=70,427,318 elapsed=110.9s

  [6200/15692] intraday_14725.csv.gz  in=286,741,183 out=70,427,641 elapsed=110.9s

  [6201/15692] intraday_14727.csv.gz  in=286,741,532 out=70,427,990 elapsed=110.9s

  [6202/15692] intraday_14729.csv.gz  in=286,741,661 out=70,428,119 elapsed=111.0s

  [6203/15692] intraday_14732.csv.gz  in=286,742,045 out=70,428,503 elapsed=111.0s

  [6204/15692] intraday_14730.csv.gz  in=286,742,831 out=70,429,289 elapsed=111.0s

  [6205/15692] intraday_1473.csv.gz  in=286,754,478 out=70,429,289 elapsed=111.0s

  [6206/15692] intraday_14731.csv.gz  in=286,755,168 out=70,429,979 elapsed=111.0s

  [6207/15692] intraday_14733.csv.gz  in=286,755,902 out=70,430,713 elapsed=111.0s

  [6208/15692] intraday_14734.csv.gz  in=286,756,040 out=70,430,851 elapsed=111.0s

  [6209/15692] intraday_14735.csv.gz  in=286,756,161 out=70,430,972 elapsed=111.0s

  [6210/15692] intraday_14736.csv.gz  in=286,756,350 out=70,431,161 elapsed=111.0s

  [6211/15692] intraday_14737.csv.gz  in=286,756,716 out=70,431,527 elapsed=111.0s

  [6212/15692] intraday_14738.csv.gz  in=286,756,908 out=70,431,719 elapsed=111.0s

  [6213/15692] intraday_14739.csv.gz  in=286,757,069 out=70,431,880 elapsed=111.0s

  [6214/15692] intraday_14740.csv.gz  in=286,757,538 out=70,432,349 elapsed=111.0s

  [6215/15692] intraday_14741.csv.gz  in=286,757,641 out=70,432,452 elapsed=111.0s

  [6216/15692] intraday_14743.csv.gz  in=286,758,273 out=70,433,084 elapsed=111.0s

  [6217/15692] intraday_1474.csv.gz  in=286,770,789 out=70,433,084 elapsed=111.0s

  [6218/15692] intraday_14745.csv.gz  in=286,770,871 out=70,433,166 elapsed=111.0s

  [6219/15692] intraday_14742.csv.gz  in=286,770,906 out=70,433,201 elapsed=111.0s

  [6220/15692] intraday_14744.csv.gz  in=286,771,835 out=70,434,130 elapsed=111.0s

  [6221/15692] intraday_14746.csv.gz  in=286,772,036 out=70,434,331 elapsed=111.0s

  [6222/15692] intraday_14748.csv.gz  in=286,772,653 out=70,434,948 elapsed=111.1s

  [6223/15692] intraday_14749.csv.gz  in=286,772,941 out=70,435,236 elapsed=111.1s

  [6224/15692] intraday_14747.csv.gz  in=286,773,449 out=70,435,744 elapsed=111.1s

  [6225/15692] intraday_14750.csv.gz  in=286,773,992 out=70,436,287 elapsed=111.1s

  [6226/15692] intraday_14751.csv.gz  in=286,774,205 out=70,436,500 elapsed=111.1s

  [6227/15692] intraday_1475.csv.gz  in=286,788,379 out=70,436,500 elapsed=111.1s

  [6228/15692] intraday_14752.csv.gz  in=286,788,578 out=70,436,699 elapsed=111.1s

  [6229/15692] intraday_14753.csv.gz  in=286,789,301 out=70,437,422 elapsed=111.1s

  [6230/15692] intraday_14754.csv.gz  in=286,789,494 out=70,437,615 elapsed=111.1s

  [6231/15692] intraday_14756.csv.gz  in=286,789,849 out=70,437,970 elapsed=111.1s

  [6232/15692] intraday_14757.csv.gz  in=286,790,039 out=70,438,160 elapsed=111.1s

  [6233/15692] intraday_14755.csv.gz  in=286,790,331 out=70,438,452 elapsed=111.1s

  [6234/15692] intraday_14759.csv.gz  in=286,790,431 out=70,438,552 elapsed=111.1s

  [6235/15692] intraday_14758.csv.gz  in=286,790,740 out=70,438,861 elapsed=111.1s

  [6236/15692] intraday_14760.csv.gz  in=286,791,126 out=70,439,247 elapsed=111.1s

  [6237/15692] intraday_14761.csv.gz  in=286,791,833 out=70,439,954 elapsed=111.1s

  [6238/15692] intraday_14762.csv.gz  in=286,792,998 out=70,441,119 elapsed=111.1s

  [6239/15692] intraday_14763.csv.gz  in=286,794,009 out=70,442,130 elapsed=111.1s

  [6240/15692] intraday_14764.csv.gz  in=286,794,896 out=70,443,017 elapsed=111.1s

  [6241/15692] intraday_1476.csv.gz  in=286,807,679 out=70,443,017 elapsed=111.1s

  [6242/15692] intraday_14765.csv.gz  in=286,808,163 out=70,443,501 elapsed=111.2s

  [6243/15692] intraday_14767.csv.gz  in=286,808,296 out=70,443,634 elapsed=111.2s

  [6244/15692] intraday_14768.csv.gz  in=286,809,425 out=70,444,763 elapsed=111.2s

  [6245/15692] intraday_14769.csv.gz  in=286,809,596 out=70,444,914 elapsed=111.2s

  [6246/15692] intraday_14766.csv.gz  in=286,810,215 out=70,445,533 elapsed=111.2s

  [6247/15692] intraday_14770.csv.gz  in=286,810,521 out=70,445,839 elapsed=111.2s

  [6248/15692] intraday_1477.csv.gz  in=286,824,536 out=70,445,839 elapsed=111.2s

  [6249/15692] intraday_14772.csv.gz  in=286,824,869 out=70,446,172 elapsed=111.2s

  [6250/15692] intraday_14771.csv.gz  in=286,825,232 out=70,446,535 elapsed=111.2s

  [6251/15692] intraday_14774.csv.gz  in=286,825,441 out=70,446,744 elapsed=111.2s

  [6252/15692] intraday_14775.csv.gz  in=286,825,724 out=70,447,027 elapsed=111.2s

  [6253/15692] intraday_14776.csv.gz  in=286,825,984 out=70,447,287 elapsed=111.2s

  [6254/15692] intraday_14777.csv.gz  in=286,826,535 out=70,447,838 elapsed=111.2s

  [6255/15692] intraday_14773.csv.gz  in=286,832,095 out=70,453,024 elapsed=111.2s

  [6256/15692] intraday_14778.csv.gz  in=286,832,339 out=70,453,268 elapsed=111.2s

  [6257/15692] intraday_14779.csv.gz  in=286,832,856 out=70,453,785 elapsed=111.2s

  [6258/15692] intraday_14780.csv.gz  in=286,833,293 out=70,454,222 elapsed=111.2s

  [6259/15692] intraday_14781.csv.gz  in=286,834,615 out=70,455,544 elapsed=111.2s

  [6260/15692] intraday_14783.csv.gz  in=286,835,065 out=70,455,994 elapsed=111.3s

  [6261/15692] intraday_14782.csv.gz  in=286,836,246 out=70,456,882 elapsed=111.3s

  [6262/15692] intraday_1478.csv.gz  in=286,848,782 out=70,456,882 elapsed=111.3s

  [6263/15692] intraday_14784.csv.gz  in=286,848,999 out=70,457,099 elapsed=111.3s

  [6264/15692] intraday_14786.csv.gz  in=286,849,099 out=70,457,199 elapsed=111.3s

  [6265/15692] intraday_14785.csv.gz  in=286,849,850 out=70,457,950 elapsed=111.3s

  [6266/15692] intraday_14787.csv.gz  in=286,850,245 out=70,458,345 elapsed=111.3s

  [6267/15692] intraday_14788.csv.gz  in=286,850,493 out=70,458,593 elapsed=111.3s

  [6268/15692] intraday_14789.csv.gz  in=286,850,929 out=70,459,029 elapsed=111.3s

  [6269/15692] intraday_14790.csv.gz  in=286,851,270 out=70,459,370 elapsed=111.3s

  [6270/15692] intraday_14791.csv.gz  in=286,851,590 out=70,459,690 elapsed=111.3s

  [6271/15692] intraday_14792.csv.gz  in=286,852,547 out=70,460,647 elapsed=111.3s

  [6272/15692] intraday_14793.csv.gz  in=286,853,252 out=70,461,352 elapsed=111.3s

  [6273/15692] intraday_1479.csv.gz  in=286,866,210 out=70,461,352 elapsed=111.3s

  [6274/15692] intraday_14794.csv.gz  in=286,867,410 out=70,462,552 elapsed=111.3s

  [6275/15692] intraday_14796.csv.gz  in=286,868,163 out=70,463,305 elapsed=111.3s

  [6276/15692] intraday_14795.csv.gz  in=286,869,404 out=70,464,546 elapsed=111.3s

  [6277/15692] intraday_14797.csv.gz  in=286,870,418 out=70,465,560 elapsed=111.3s

  [6278/15692] intraday_14798.csv.gz  in=286,870,633 out=70,465,775 elapsed=111.3s

  [6279/15692] intraday_14799.csv.gz  in=286,871,001 out=70,466,143 elapsed=111.3s

  [6280/15692] intraday_14800.csv.gz  in=286,871,201 out=70,466,343 elapsed=111.4s

  [6281/15692] intraday_14802.csv.gz  in=286,871,686 out=70,466,828 elapsed=111.4s

  [6282/15692] intraday_14801.csv.gz  in=286,871,860 out=70,467,002 elapsed=111.4s

  [6283/15692] intraday_14803.csv.gz  in=286,872,138 out=70,467,280 elapsed=111.4s

  [6284/15692] intraday_1480.csv.gz  in=286,885,541 out=70,467,280 elapsed=111.4s

  [6285/15692] intraday_14804.csv.gz  in=286,885,945 out=70,467,684 elapsed=111.4s

  [6286/15692] intraday_14805.csv.gz  in=286,886,412 out=70,468,151 elapsed=111.4s

  [6287/15692] intraday_14807.csv.gz  in=286,886,708 out=70,468,447 elapsed=111.4s

  [6288/15692] intraday_14806.csv.gz  in=286,887,355 out=70,469,094 elapsed=111.4s

  [6289/15692] intraday_14808.csv.gz  in=286,887,815 out=70,469,554 elapsed=111.4s

  [6290/15692] intraday_14809.csv.gz  in=286,888,188 out=70,469,927 elapsed=111.4s

  [6291/15692] intraday_14810.csv.gz  in=286,888,945 out=70,470,684 elapsed=111.4s

  [6292/15692] intraday_14813.csv.gz  in=286,889,472 out=70,471,211 elapsed=111.4s

  [6293/15692] intraday_1481.csv.gz  in=286,902,470 out=70,471,211 elapsed=111.4s

  [6294/15692] intraday_14812.csv.gz  in=286,902,724 out=70,471,465 elapsed=111.4s

  [6295/15692] intraday_14811.csv.gz  in=286,903,035 out=70,471,776 elapsed=111.4s

  [6296/15692] intraday_14815.csv.gz  in=286,903,260 out=70,472,001 elapsed=111.4s

  [6297/15692] intraday_14814.csv.gz  in=286,903,595 out=70,472,336 elapsed=111.4s

  [6298/15692] intraday_14817.csv.gz  in=286,903,929 out=70,472,670 elapsed=111.4s

  [6299/15692] intraday_14816.csv.gz  in=286,904,759 out=70,473,500 elapsed=111.4s

  [6300/15692] intraday_14818.csv.gz  in=286,904,955 out=70,473,696 elapsed=111.4s

  [6301/15692] intraday_14819.csv.gz  in=286,905,516 out=70,474,257 elapsed=111.4s

  [6302/15692] intraday_14820.csv.gz  in=286,906,094 out=70,474,835 elapsed=111.4s

  [6303/15692] intraday_14821.csv.gz  in=286,906,626 out=70,475,367 elapsed=111.4s

  [6304/15692] intraday_14822.csv.gz  in=286,906,898 out=70,475,639 elapsed=111.4s

  [6305/15692] intraday_14823.csv.gz  in=286,906,952 out=70,475,693 elapsed=111.4s

  [6306/15692] intraday_1482.csv.gz  in=286,921,335 out=70,475,693 elapsed=111.4s

  [6307/15692] intraday_14825.csv.gz  in=286,932,362 out=70,486,720 elapsed=111.5s

  [6308/15692] intraday_14824.csv.gz  in=286,947,323 out=70,501,681 elapsed=111.5s

  [6309/15692] intraday_14826.csv.gz  in=286,961,107 out=70,515,465 elapsed=111.5s

  [6310/15692] intraday_14827.csv.gz  in=286,971,628 out=70,525,986 elapsed=111.5s

  [6311/15692] intraday_14828.csv.gz  in=286,983,703 out=70,538,061 elapsed=111.5s

  [6312/15692] intraday_14829.csv.gz  in=286,996,317 out=70,550,675 elapsed=111.5s

  [6313/15692] intraday_1483.csv.gz  in=287,011,371 out=70,550,675 elapsed=111.5s

  [6314/15692] intraday_14830.csv.gz  in=287,024,456 out=70,563,760 elapsed=111.6s

  [6315/15692] intraday_14831.csv.gz  in=287,035,869 out=70,575,173 elapsed=111.6s

  [6316/15692] intraday_14832.csv.gz  in=287,047,638 out=70,586,942 elapsed=111.6s

  [6317/15692] intraday_14833.csv.gz  in=287,059,833 out=70,599,137 elapsed=111.6s

  [6318/15692] intraday_14834.csv.gz  in=287,070,435 out=70,609,739 elapsed=111.6s

  [6319/15692] intraday_14835.csv.gz  in=287,081,838 out=70,621,142 elapsed=111.6s

  [6320/15692] intraday_14836.csv.gz  in=287,093,146 out=70,632,450 elapsed=111.6s

  [6321/15692] intraday_14837.csv.gz  in=287,106,011 out=70,645,315 elapsed=111.6s

  [6322/15692] intraday_14838.csv.gz  in=287,116,162 out=70,655,466 elapsed=111.7s

  [6323/15692] intraday_1484.csv.gz  in=287,130,747 out=70,655,466 elapsed=111.7s

  [6324/15692] intraday_14839.csv.gz  in=287,139,130 out=70,663,849 elapsed=111.7s

  [6325/15692] intraday_14840.csv.gz  in=287,153,534 out=70,678,253 elapsed=111.7s

  [6326/15692] intraday_14841.csv.gz  in=287,166,153 out=70,690,872 elapsed=111.7s

  [6327/15692] intraday_14843.csv.gz  in=287,176,434 out=70,701,153 elapsed=111.7s

  [6328/15692] intraday_14842.csv.gz  in=287,188,383 out=70,713,102 elapsed=111.7s

  [6329/15692] intraday_14845.csv.gz  in=287,199,767 out=70,724,486 elapsed=111.7s

  [6330/15692] intraday_14844.csv.gz  in=287,213,009 out=70,737,728 elapsed=111.8s

  [6331/15692] intraday_14847.csv.gz  in=287,224,895 out=70,749,614 elapsed=111.8s

  [6332/15692] intraday_14846.csv.gz  in=287,237,530 out=70,762,249 elapsed=111.8s

  [6333/15692] intraday_14848.csv.gz  in=287,250,350 out=70,775,069 elapsed=111.8s

  [6334/15692] intraday_14849.csv.gz  in=287,262,584 out=70,787,303 elapsed=111.8s

  [6335/15692] intraday_1485.csv.gz  in=287,276,322 out=70,787,303 elapsed=111.8s

  [6336/15692] intraday_14850.csv.gz  in=287,286,721 out=70,797,664 elapsed=111.9s

  [6337/15692] intraday_14851.csv.gz  in=287,298,233 out=70,809,176 elapsed=111.9s

  [6338/15692] intraday_14852.csv.gz  in=287,309,081 out=70,820,024 elapsed=111.9s

  [6339/15692] intraday_14854.csv.gz  in=287,324,611 out=70,835,554 elapsed=111.9s

  [6340/15692] intraday_14853.csv.gz  in=287,338,298 out=70,849,241 elapsed=111.9s

  [6341/15692] intraday_14856.csv.gz  in=287,349,281 out=70,860,224 elapsed=111.9s

  [6342/15692] intraday_14855.csv.gz  in=287,361,146 out=70,872,089 elapsed=111.9s

  [6343/15692] intraday_14857.csv.gz  in=287,373,169 out=70,884,112 elapsed=112.0s

  [6344/15692] intraday_14859.csv.gz  in=287,384,775 out=70,895,718 elapsed=112.0s

  [6345/15692] intraday_1486.csv.gz  in=287,399,463 out=70,895,718 elapsed=112.0s

  [6346/15692] intraday_14858.csv.gz  in=287,411,783 out=70,908,038 elapsed=112.0s

  [6347/15692] intraday_14860.csv.gz  in=287,424,394 out=70,920,649 elapsed=112.0s

  [6348/15692] intraday_14861.csv.gz  in=287,434,265 out=70,930,520 elapsed=112.0s

  [6349/15692] intraday_14863.csv.gz  in=287,443,120 out=70,939,375 elapsed=112.0s

  [6350/15692] intraday_14862.csv.gz  in=287,455,003 out=70,951,258 elapsed=112.0s

  [6351/15692] intraday_14864.csv.gz  in=287,466,465 out=70,962,720 elapsed=112.0s

  [6352/15692] intraday_14865.csv.gz  in=287,478,371 out=70,974,626 elapsed=112.1s

  [6353/15692] intraday_14866.csv.gz  in=287,492,063 out=70,988,318 elapsed=112.1s

  [6354/15692] intraday_14867.csv.gz  in=287,503,869 out=71,000,124 elapsed=112.1s

  [6355/15692] intraday_1487.csv.gz  in=287,516,835 out=71,000,124 elapsed=112.2s

  [6356/15692] intraday_14869.csv.gz  in=287,527,129 out=71,010,418 elapsed=112.2s

  [6357/15692] intraday_14870.csv.gz  in=287,538,300 out=71,021,589 elapsed=112.2s

  [6358/15692] intraday_14868.csv.gz  in=287,551,547 out=71,034,836 elapsed=112.2s

  [6359/15692] intraday_14874.csv.gz  in=287,562,861 out=71,046,150 elapsed=112.2s

  [6360/15692] intraday_14872.csv.gz  in=287,581,768 out=71,065,057 elapsed=112.2s

  [6361/15692] intraday_14871.csv.gz  in=287,594,889 out=71,078,178 elapsed=112.3s

  [6362/15692] intraday_14875.csv.gz  in=287,605,016 out=71,088,305 elapsed=112.3s

  [6363/15692] intraday_14873.csv.gz  in=287,615,838 out=71,099,127 elapsed=112.3s

  [6364/15692] intraday_14876.csv.gz  in=287,629,464 out=71,112,753 elapsed=112.3s

  [6365/15692] intraday_14879.csv.gz  in=287,642,057 out=71,125,346 elapsed=112.3s

  [6366/15692] intraday_14877.csv.gz  in=287,654,881 out=71,138,170 elapsed=112.3s

  [6367/15692] intraday_14878.csv.gz  in=287,666,224 out=71,149,513 elapsed=112.3s

  [6368/15692] intraday_1488.csv.gz  in=287,682,382 out=71,149,513 elapsed=112.3s

  [6369/15692] intraday_14880.csv.gz  in=287,692,978 out=71,160,109 elapsed=112.4s

  [6370/15692] intraday_14881.csv.gz  in=287,703,352 out=71,170,483 elapsed=112.4s

  [6371/15692] intraday_14882.csv.gz  in=287,713,773 out=71,180,904 elapsed=112.4s

  [6372/15692] intraday_14883.csv.gz  in=287,726,074 out=71,193,205 elapsed=112.4s

  [6373/15692] intraday_14884.csv.gz  in=287,737,003 out=71,204,134 elapsed=112.4s

  [6374/15692] intraday_14887.csv.gz  in=287,747,801 out=71,214,932 elapsed=112.5s

  [6375/15692] intraday_14885.csv.gz  in=287,759,357 out=71,226,488 elapsed=112.5s

  [6376/15692] intraday_14886.csv.gz  in=287,769,924 out=71,237,055 elapsed=112.5s

  [6377/15692] intraday_14888.csv.gz  in=287,779,786 out=71,246,917 elapsed=112.5s

  [6378/15692] intraday_1489.csv.gz  in=287,792,203 out=71,246,917 elapsed=112.5s

  [6379/15692] intraday_14890.csv.gz  in=287,804,109 out=71,258,823 elapsed=112.5s

  [6380/15692] intraday_14889.csv.gz  in=287,817,783 out=71,272,497 elapsed=112.5s

  [6381/15692] intraday_14891.csv.gz  in=287,830,982 out=71,285,696 elapsed=112.5s

  [6382/15692] intraday_14892.csv.gz  in=287,842,752 out=71,297,466 elapsed=112.5s

  [6383/15692] intraday_14893.csv.gz  in=287,853,851 out=71,308,565 elapsed=112.5s

  [6384/15692] intraday_14895.csv.gz  in=287,865,752 out=71,320,466 elapsed=112.6s

  [6385/15692] intraday_14894.csv.gz  in=287,877,315 out=71,332,029 elapsed=112.6s

  [6386/15692] intraday_14896.csv.gz  in=287,888,802 out=71,343,516 elapsed=112.6s

  [6387/15692] intraday_14897.csv.gz  in=287,900,282 out=71,354,996 elapsed=112.6s

  [6388/15692] intraday_14898.csv.gz  in=287,912,740 out=71,367,454 elapsed=112.6s

  [6389/15692] intraday_14899.csv.gz  in=287,922,493 out=71,377,207 elapsed=112.6s

  [6390/15692] intraday_1490.csv.gz  in=287,936,906 out=71,377,207 elapsed=112.6s

  [6391/15692] intraday_14900.csv.gz  in=287,946,337 out=71,386,638 elapsed=112.6s

  [6392/15692] intraday_14901.csv.gz  in=287,959,102 out=71,399,403 elapsed=112.7s

  [6393/15692] intraday_14902.csv.gz  in=287,969,738 out=71,410,039 elapsed=112.7s

  [6394/15692] intraday_14904.csv.gz  in=287,980,071 out=71,420,350 elapsed=112.7s

  [6395/15692] intraday_14903.csv.gz  in=287,992,152 out=71,432,431 elapsed=112.7s

  [6396/15692] intraday_14905.csv.gz  in=288,001,814 out=71,442,093 elapsed=112.7s

  [6397/15692] intraday_14906.csv.gz  in=288,014,413 out=71,454,692 elapsed=112.7s

  [6398/15692] intraday_14907.csv.gz  in=288,026,560 out=71,466,839 elapsed=112.7s

  [6399/15692] intraday_14909.csv.gz  in=288,039,648 out=71,479,927 elapsed=112.7s

  [6400/15692] intraday_14908.csv.gz  in=288,056,159 out=71,496,438 elapsed=112.7s

  [6401/15692] intraday_1491.csv.gz  in=288,072,631 out=71,496,438 elapsed=112.7s

  [6402/15692] intraday_14910.csv.gz  in=288,085,463 out=71,509,270 elapsed=112.8s

  [6403/15692] intraday_14912.csv.gz  in=288,097,102 out=71,520,909 elapsed=112.8s

  [6404/15692] intraday_14913.csv.gz  in=288,109,272 out=71,533,079 elapsed=112.8s

  [6405/15692] intraday_14911.csv.gz  in=288,119,848 out=71,543,655 elapsed=112.8s

  [6406/15692] intraday_14914.csv.gz  in=288,131,845 out=71,555,652 elapsed=112.8s

  [6407/15692] intraday_14915.csv.gz  in=288,142,446 out=71,566,253 elapsed=112.8s

  [6408/15692] intraday_14916.csv.gz  in=288,156,020 out=71,579,827 elapsed=112.8s

  [6409/15692] intraday_14919.csv.gz  in=288,169,827 out=71,593,634 elapsed=112.9s

  [6410/15692] intraday_14917.csv.gz  in=288,179,998 out=71,603,805 elapsed=112.9s

  [6411/15692] intraday_14918.csv.gz  in=288,190,283 out=71,614,090 elapsed=112.9s

  [6412/15692] intraday_1492.csv.gz  in=288,203,948 out=71,614,090 elapsed=112.9s

  [6413/15692] intraday_14920.csv.gz  in=288,215,953 out=71,626,095 elapsed=112.9s

  [6414/15692] intraday_14921.csv.gz  in=288,228,498 out=71,638,640 elapsed=112.9s

  [6415/15692] intraday_14922.csv.gz  in=288,239,330 out=71,649,472 elapsed=112.9s

  [6416/15692] intraday_14923.csv.gz  in=288,249,892 out=71,660,034 elapsed=112.9s

  [6417/15692] intraday_14924.csv.gz  in=288,261,502 out=71,671,644 elapsed=113.0s

  [6418/15692] intraday_14926.csv.gz  in=288,274,524 out=71,684,666 elapsed=113.0s

  [6419/15692] intraday_14925.csv.gz  in=288,287,206 out=71,697,348 elapsed=113.0s

  [6420/15692] intraday_14927.csv.gz  in=288,298,670 out=71,708,812 elapsed=113.0s

  [6421/15692] intraday_14928.csv.gz  in=288,309,765 out=71,719,907 elapsed=113.0s

  [6422/15692] intraday_1493.csv.gz  in=288,323,799 out=71,719,907 elapsed=113.0s

  [6423/15692] intraday_14929.csv.gz  in=288,335,228 out=71,731,336 elapsed=113.0s

  [6424/15692] intraday_14930.csv.gz  in=288,346,912 out=71,743,020 elapsed=113.0s

  [6425/15692] intraday_14932.csv.gz  in=288,357,378 out=71,753,486 elapsed=113.1s

  [6426/15692] intraday_14931.csv.gz  in=288,370,190 out=71,766,298 elapsed=113.1s

  [6427/15692] intraday_14933.csv.gz  in=288,383,947 out=71,780,055 elapsed=113.1s

  [6428/15692] intraday_14934.csv.gz  in=288,396,908 out=71,793,016 elapsed=113.1s

  [6429/15692] intraday_14935.csv.gz  in=288,408,739 out=71,804,847 elapsed=113.1s

  [6430/15692] intraday_14937.csv.gz  in=288,421,182 out=71,817,290 elapsed=113.1s

  [6431/15692] intraday_14936.csv.gz  in=288,432,651 out=71,828,759 elapsed=113.1s

  [6432/15692] intraday_14938.csv.gz  in=288,445,570 out=71,841,678 elapsed=113.1s

  [6433/15692] intraday_1494.csv.gz  in=288,461,237 out=71,841,678 elapsed=113.2s

  [6434/15692] intraday_14939.csv.gz  in=288,473,628 out=71,854,069 elapsed=113.2s

  [6435/15692] intraday_14940.csv.gz  in=288,487,158 out=71,867,599 elapsed=113.2s

  [6436/15692] intraday_14941.csv.gz  in=288,504,067 out=71,884,508 elapsed=113.2s

  [6437/15692] intraday_14942.csv.gz  in=288,516,721 out=71,897,162 elapsed=113.2s

  [6438/15692] intraday_14943.csv.gz  in=288,532,953 out=71,913,394 elapsed=113.2s

  [6439/15692] intraday_14944.csv.gz  in=288,543,116 out=71,923,557 elapsed=113.2s

  [6440/15692] intraday_14946.csv.gz  in=288,553,915 out=71,934,356 elapsed=113.2s

  [6441/15692] intraday_14945.csv.gz  in=288,566,611 out=71,947,052 elapsed=113.2s

  [6442/15692] intraday_14948.csv.gz  in=288,577,555 out=71,957,996 elapsed=113.3s

  [6443/15692] intraday_14947.csv.gz  in=288,589,667 out=71,970,108 elapsed=113.3s

  [6444/15692] intraday_1495.csv.gz  in=288,600,843 out=71,970,108 elapsed=113.3s

  [6445/15692] intraday_14949.csv.gz  in=288,613,095 out=71,982,360 elapsed=113.3s

  [6446/15692] intraday_14950.csv.gz  in=288,624,309 out=71,993,574 elapsed=113.3s

  [6447/15692] intraday_14953.csv.gz  in=288,634,913 out=72,004,178 elapsed=113.3s

  [6448/15692] intraday_14951.csv.gz  in=288,651,719 out=72,020,984 elapsed=113.3s

  [6449/15692] intraday_14952.csv.gz  in=288,661,213 out=72,030,478 elapsed=113.3s

  [6450/15692] intraday_14955.csv.gz  in=288,672,244 out=72,041,509 elapsed=113.4s

  [6451/15692] intraday_14954.csv.gz  in=288,684,141 out=72,053,406 elapsed=113.4s

  [6452/15692] intraday_14956.csv.gz  in=288,696,369 out=72,065,634 elapsed=113.4s

  [6453/15692] intraday_14957.csv.gz  in=288,709,357 out=72,078,622 elapsed=113.4s

  [6454/15692] intraday_14959.csv.gz  in=288,722,789 out=72,092,054 elapsed=113.4s

  [6455/15692] intraday_1496.csv.gz  in=288,735,178 out=72,092,054 elapsed=113.4s

  [6456/15692] intraday_14958.csv.gz  in=288,753,685 out=72,110,561 elapsed=113.4s

  [6457/15692] intraday_14960.csv.gz  in=288,769,669 out=72,126,409 elapsed=113.4s

  [6458/15692] intraday_14962.csv.gz  in=288,783,377 out=72,140,117 elapsed=113.5s

  [6459/15692] intraday_14961.csv.gz  in=288,796,014 out=72,152,754 elapsed=113.5s

  [6460/15692] intraday_14963.csv.gz  in=288,808,504 out=72,165,244 elapsed=113.5s

  [6461/15692] intraday_14964.csv.gz  in=288,819,021 out=72,175,761 elapsed=113.5s

  [6462/15692] intraday_14965.csv.gz  in=288,830,974 out=72,187,714 elapsed=113.5s

  [6463/15692] intraday_14966.csv.gz  in=288,841,051 out=72,197,791 elapsed=113.5s

  [6464/15692] intraday_14967.csv.gz  in=288,849,474 out=72,206,214 elapsed=113.5s

  [6465/15692] intraday_14968.csv.gz  in=288,862,560 out=72,219,300 elapsed=113.5s

  [6466/15692] intraday_14969.csv.gz  in=288,863,838 out=72,220,578 elapsed=113.5s

  [6467/15692] intraday_1497.csv.gz  in=288,888,432 out=72,220,578 elapsed=113.6s

  [6468/15692] intraday_14970.csv.gz  in=288,903,168 out=72,235,314 elapsed=113.6s

  [6469/15692] intraday_14971.csv.gz  in=288,915,086 out=72,247,232 elapsed=113.6s

  [6470/15692] intraday_14972.csv.gz  in=288,927,580 out=72,259,726 elapsed=113.6s

  [6471/15692] intraday_14973.csv.gz  in=288,939,627 out=72,271,773 elapsed=113.6s

  [6472/15692] intraday_14974.csv.gz  in=288,950,719 out=72,282,865 elapsed=113.6s

  [6473/15692] intraday_14975.csv.gz  in=288,966,076 out=72,298,222 elapsed=113.6s

  [6474/15692] intraday_14976.csv.gz  in=288,978,773 out=72,310,919 elapsed=113.6s

  [6475/15692] intraday_14978.csv.gz  in=288,991,293 out=72,323,439 elapsed=113.7s

  [6476/15692] intraday_14977.csv.gz  in=289,002,676 out=72,334,822 elapsed=113.7s

  [6477/15692] intraday_1498.csv.gz  in=289,017,954 out=72,334,822 elapsed=113.7s

  [6478/15692] intraday_14979.csv.gz  in=289,030,210 out=72,347,078 elapsed=113.7s

  [6479/15692] intraday_14980.csv.gz  in=289,041,204 out=72,358,072 elapsed=113.7s

  [6480/15692] intraday_14981.csv.gz  in=289,053,992 out=72,370,860 elapsed=113.7s

  [6481/15692] intraday_14982.csv.gz  in=289,066,165 out=72,383,033 elapsed=113.7s

  [6482/15692] intraday_14984.csv.gz  in=289,077,298 out=72,394,166 elapsed=113.7s

  [6483/15692] intraday_14983.csv.gz  in=289,090,310 out=72,407,178 elapsed=113.7s

  [6484/15692] intraday_14985.csv.gz  in=289,099,698 out=72,416,566 elapsed=113.8s

  [6485/15692] intraday_14987.csv.gz  in=289,113,141 out=72,430,009 elapsed=113.8s

  [6486/15692] intraday_14988.csv.gz  in=289,124,054 out=72,440,922 elapsed=113.8s

  [6487/15692] intraday_14986.csv.gz  in=289,139,710 out=72,456,578 elapsed=113.8s

  [6488/15692] intraday_14989.csv.gz  in=289,150,740 out=72,467,608 elapsed=113.8s

  [6489/15692] intraday_1499.csv.gz  in=289,166,913 out=72,467,608 elapsed=113.8s

  [6490/15692] intraday_14992.csv.gz  in=289,180,026 out=72,480,721 elapsed=113.8s

  [6491/15692] intraday_14991.csv.gz  in=289,192,037 out=72,492,732 elapsed=113.9s

  [6492/15692] intraday_14993.csv.gz  in=289,204,282 out=72,504,977 elapsed=113.9s

  [6493/15692] intraday_14990.csv.gz  in=289,217,978 out=72,518,673 elapsed=113.9s

  [6494/15692] intraday_14994.csv.gz  in=289,230,612 out=72,531,307 elapsed=113.9s

  [6495/15692] intraday_14995.csv.gz  in=289,241,329 out=72,542,024 elapsed=113.9s

  [6496/15692] intraday_14996.csv.gz  in=289,253,070 out=72,553,765 elapsed=113.9s

  [6497/15692] intraday_14998.csv.gz  in=289,265,411 out=72,566,106 elapsed=113.9s

  [6498/15692] intraday_14997.csv.gz  in=289,276,968 out=72,577,663 elapsed=113.9s

  [6499/15692] intraday_1500.csv.gz  in=289,291,828 out=72,577,663 elapsed=113.9s

  [6500/15692] intraday_14999.csv.gz  in=289,304,598 out=72,590,433 elapsed=113.9s

  [6501/15692] intraday_15002.csv.gz  in=289,315,108 out=72,600,943 elapsed=114.0s

  [6502/15692] intraday_15000.csv.gz  in=289,331,228 out=72,617,063 elapsed=114.0s

  [6503/15692] intraday_15001.csv.gz  in=289,344,404 out=72,630,239 elapsed=114.0s

  [6504/15692] intraday_15003.csv.gz  in=289,357,877 out=72,643,712 elapsed=114.0s

  [6505/15692] intraday_15004.csv.gz  in=289,371,081 out=72,656,916 elapsed=114.0s

  [6506/15692] intraday_15005.csv.gz  in=289,383,442 out=72,669,277 elapsed=114.0s

  [6507/15692] intraday_15006.csv.gz  in=289,396,603 out=72,682,438 elapsed=114.1s

  [6508/15692] intraday_15007.csv.gz  in=289,405,918 out=72,691,753 elapsed=114.1s

  [6509/15692] intraday_15008.csv.gz  in=289,417,980 out=72,703,815 elapsed=114.1s

  [6510/15692] intraday_15009.csv.gz  in=289,427,509 out=72,713,344 elapsed=114.1s

  [6511/15692] intraday_1501.csv.gz  in=289,442,595 out=72,713,344 elapsed=114.1s

  [6512/15692] intraday_15010.csv.gz  in=289,454,481 out=72,725,230 elapsed=114.1s

  [6513/15692] intraday_15011.csv.gz  in=289,466,304 out=72,737,053 elapsed=114.1s

  [6514/15692] intraday_15013.csv.gz  in=289,477,880 out=72,748,629 elapsed=114.2s

  [6515/15692] intraday_15012.csv.gz  in=289,493,038 out=72,763,787 elapsed=114.2s

  [6516/15692] intraday_15015.csv.gz  in=289,503,585 out=72,774,334 elapsed=114.2s

  [6517/15692] intraday_15014.csv.gz  in=289,517,790 out=72,788,539 elapsed=114.2s

  [6518/15692] intraday_15016.csv.gz  in=289,528,841 out=72,799,590 elapsed=114.2s

  [6519/15692] intraday_15017.csv.gz  in=289,541,569 out=72,812,318 elapsed=114.2s

  [6520/15692] intraday_15018.csv.gz  in=289,554,244 out=72,824,993 elapsed=114.2s

  [6521/15692] intraday_15019.csv.gz  in=289,566,159 out=72,836,908 elapsed=114.2s

  [6522/15692] intraday_1502.csv.gz  in=289,581,263 out=72,836,908 elapsed=114.2s

  [6523/15692] intraday_15020.csv.gz  in=289,592,181 out=72,847,826 elapsed=114.3s

  [6524/15692] intraday_15021.csv.gz  in=289,605,357 out=72,861,002 elapsed=114.3s

  [6525/15692] intraday_15022.csv.gz  in=289,617,439 out=72,873,084 elapsed=114.3s

  [6526/15692] intraday_15023.csv.gz  in=289,629,908 out=72,885,553 elapsed=114.3s

  [6527/15692] intraday_15024.csv.gz  in=289,642,575 out=72,898,220 elapsed=114.3s

  [6528/15692] intraday_15027.csv.gz  in=289,651,923 out=72,907,568 elapsed=114.3s

  [6529/15692] intraday_15026.csv.gz  in=289,664,105 out=72,919,750 elapsed=114.3s

  [6530/15692] intraday_15025.csv.gz  in=289,677,040 out=72,932,685 elapsed=114.3s

  [6531/15692] intraday_15028.csv.gz  in=289,690,362 out=72,946,007 elapsed=114.4s

  [6532/15692] intraday_1503.csv.gz  in=289,705,412 out=72,946,007 elapsed=114.4s

  [6533/15692] intraday_15030.csv.gz  in=289,716,354 out=72,956,949 elapsed=114.4s

  [6534/15692] intraday_15029.csv.gz  in=289,750,112 out=72,989,119 elapsed=114.4s

  [6535/15692] intraday_15031.csv.gz  in=289,762,448 out=73,001,455 elapsed=114.4s

  [6536/15692] intraday_15032.csv.gz  in=289,773,620 out=73,012,627 elapsed=114.4s

  [6537/15692] intraday_15033.csv.gz  in=289,783,766 out=73,022,773 elapsed=114.4s

  [6538/15692] intraday_15034.csv.gz  in=289,795,008 out=73,034,015 elapsed=114.4s

  [6539/15692] intraday_15035.csv.gz  in=289,808,418 out=73,047,425 elapsed=114.5s

  [6540/15692] intraday_15037.csv.gz  in=289,821,657 out=73,060,664 elapsed=114.5s

  [6541/15692] intraday_15036.csv.gz  in=289,834,343 out=73,073,350 elapsed=114.5s

  [6542/15692] intraday_15038.csv.gz  in=289,847,190 out=73,086,197 elapsed=114.5s

  [6543/15692] intraday_15039.csv.gz  in=289,857,869 out=73,096,876 elapsed=114.5s

  [6544/15692] intraday_1504.csv.gz  in=289,871,840 out=73,096,876 elapsed=114.5s

  [6545/15692] intraday_15040.csv.gz  in=289,882,441 out=73,107,477 elapsed=114.5s

  [6546/15692] intraday_15041.csv.gz  in=289,896,124 out=73,121,160 elapsed=114.6s

  [6547/15692] intraday_15043.csv.gz  in=289,909,747 out=73,134,783 elapsed=114.6s

  [6548/15692] intraday_15042.csv.gz  in=289,920,474 out=73,145,510 elapsed=114.6s

  [6549/15692] intraday_15044.csv.gz  in=289,931,868 out=73,156,904 elapsed=114.6s

  [6550/15692] intraday_15045.csv.gz  in=289,941,572 out=73,166,608 elapsed=114.6s

  [6551/15692] intraday_15046.csv.gz  in=289,951,728 out=73,176,764 elapsed=114.6s

  [6552/15692] intraday_15047.csv.gz  in=289,965,174 out=73,190,210 elapsed=114.6s

  [6553/15692] intraday_15048.csv.gz  in=289,975,908 out=73,200,944 elapsed=114.6s

  [6554/15692] intraday_1505.csv.gz  in=289,992,423 out=73,200,944 elapsed=114.6s

  [6555/15692] intraday_15049.csv.gz  in=290,005,098 out=73,213,619 elapsed=114.7s

  [6556/15692] intraday_15050.csv.gz  in=290,015,315 out=73,223,836 elapsed=114.7s

  [6557/15692] intraday_15051.csv.gz  in=290,025,601 out=73,234,122 elapsed=114.7s

  [6558/15692] intraday_15053.csv.gz  in=290,038,978 out=73,247,499 elapsed=114.7s

  [6559/15692] intraday_15052.csv.gz  in=290,052,901 out=73,261,422 elapsed=114.7s

  [6560/15692] intraday_15055.csv.gz  in=290,065,681 out=73,274,202 elapsed=114.7s

  [6561/15692] intraday_15054.csv.gz  in=290,080,504 out=73,289,025 elapsed=114.7s

  [6562/15692] intraday_15056.csv.gz  in=290,093,217 out=73,301,738 elapsed=114.8s

  [6563/15692] intraday_15057.csv.gz  in=290,105,451 out=73,313,972 elapsed=114.8s

  [6564/15692] intraday_15058.csv.gz  in=290,116,263 out=73,324,784 elapsed=114.8s

  [6565/15692] intraday_15059.csv.gz  in=290,130,544 out=73,339,065 elapsed=114.8s

  [6566/15692] intraday_15060.csv.gz  in=290,141,898 out=73,350,419 elapsed=114.8s

  [6567/15692] intraday_1506.csv.gz  in=290,158,156 out=73,350,419 elapsed=114.8s

  [6568/15692] intraday_15061.csv.gz  in=290,169,048 out=73,361,311 elapsed=114.8s

  [6569/15692] intraday_15062.csv.gz  in=290,182,508 out=73,374,771 elapsed=114.8s

  [6570/15692] intraday_15064.csv.gz  in=290,194,347 out=73,386,610 elapsed=114.8s

  [6571/15692] intraday_15063.csv.gz  in=290,205,400 out=73,397,663 elapsed=114.9s

  [6572/15692] intraday_15065.csv.gz  in=290,219,584 out=73,411,847 elapsed=114.9s

  [6573/15692] intraday_15066.csv.gz  in=290,232,797 out=73,425,060 elapsed=114.9s

  [6574/15692] intraday_15068.csv.gz  in=290,245,013 out=73,437,276 elapsed=114.9s

  [6575/15692] intraday_15067.csv.gz  in=290,256,867 out=73,449,130 elapsed=114.9s

  [6576/15692] intraday_1507.csv.gz  in=290,270,221 out=73,449,130 elapsed=114.9s

  [6577/15692] intraday_15069.csv.gz  in=290,281,780 out=73,460,689 elapsed=114.9s

  [6578/15692] intraday_15070.csv.gz  in=290,293,718 out=73,472,627 elapsed=114.9s

  [6579/15692] intraday_15071.csv.gz  in=290,307,497 out=73,486,406 elapsed=115.0s

  [6580/15692] intraday_15072.csv.gz  in=290,319,144 out=73,498,053 elapsed=115.0s

  [6581/15692] intraday_15073.csv.gz  in=290,331,745 out=73,510,654 elapsed=115.0s

  [6582/15692] intraday_15074.csv.gz  in=290,345,408 out=73,524,317 elapsed=115.0s

  [6583/15692] intraday_15076.csv.gz  in=290,360,813 out=73,539,722 elapsed=115.0s

  [6584/15692] intraday_15078.csv.gz  in=290,372,510 out=73,551,419 elapsed=115.1s

  [6585/15692] intraday_15077.csv.gz  in=290,383,094 out=73,562,003 elapsed=115.1s

  [6586/15692] intraday_15075.csv.gz  in=290,393,484 out=73,572,393 elapsed=115.1s

  [6587/15692] intraday_15079.csv.gz  in=290,406,744 out=73,585,653 elapsed=115.1s

  [6588/15692] intraday_1508.csv.gz  in=290,422,248 out=73,585,653 elapsed=115.1s

  [6589/15692] intraday_15081.csv.gz  in=290,432,424 out=73,595,829 elapsed=115.1s

  [6590/15692] intraday_15080.csv.gz  in=290,447,428 out=73,610,833 elapsed=115.1s

  [6591/15692] intraday_15082.csv.gz  in=290,462,181 out=73,625,586 elapsed=115.1s

  [6592/15692] intraday_15083.csv.gz  in=290,476,116 out=73,639,521 elapsed=115.1s

  [6593/15692] intraday_15084.csv.gz  in=290,488,262 out=73,651,667 elapsed=115.2s

  [6594/15692] intraday_15085.csv.gz  in=290,500,238 out=73,663,643 elapsed=115.2s

  [6595/15692] intraday_15086.csv.gz  in=290,517,258 out=73,680,663 elapsed=115.2s

  [6596/15692] intraday_15088.csv.gz  in=290,532,670 out=73,696,075 elapsed=115.2s

  [6597/15692] intraday_15087.csv.gz  in=290,549,590 out=73,712,995 elapsed=115.2s

  [6598/15692] intraday_1509.csv.gz  in=290,561,309 out=73,712,995 elapsed=115.2s

  [6599/15692] intraday_15089.csv.gz  in=290,575,953 out=73,727,639 elapsed=115.2s

  [6600/15692] intraday_15090.csv.gz  in=290,587,264 out=73,738,950 elapsed=115.2s

  [6601/15692] intraday_15092.csv.gz  in=290,597,276 out=73,748,962 elapsed=115.3s

  [6602/15692] intraday_15093.csv.gz  in=290,610,539 out=73,762,225 elapsed=115.3s

  [6603/15692] intraday_15094.csv.gz  in=290,621,573 out=73,773,259 elapsed=115.3s

  [6604/15692] intraday_15091.csv.gz  in=290,633,791 out=73,785,477 elapsed=115.3s

  [6605/15692] intraday_15095.csv.gz  in=290,646,220 out=73,797,906 elapsed=115.3s

  [6606/15692] intraday_15098.csv.gz  in=290,657,084 out=73,808,770 elapsed=115.3s

  [6607/15692] intraday_15096.csv.gz  in=290,669,769 out=73,821,455 elapsed=115.3s

  [6608/15692] intraday_15099.csv.gz  in=290,681,416 out=73,833,102 elapsed=115.4s

  [6609/15692] intraday_15097.csv.gz  in=290,695,252 out=73,846,938 elapsed=115.4s

  [6610/15692] intraday_1510.csv.gz  in=290,706,651 out=73,846,938 elapsed=115.4s

  [6611/15692] intraday_15100.csv.gz  in=290,719,304 out=73,859,591 elapsed=115.4s

  [6612/15692] intraday_15101.csv.gz  in=290,732,939 out=73,873,226 elapsed=115.4s

  [6613/15692] intraday_15102.csv.gz  in=290,744,719 out=73,885,006 elapsed=115.4s

  [6614/15692] intraday_15103.csv.gz  in=290,758,363 out=73,898,650 elapsed=115.4s

  [6615/15692] intraday_15105.csv.gz  in=290,770,499 out=73,910,786 elapsed=115.5s

  [6616/15692] intraday_15104.csv.gz  in=290,785,175 out=73,925,462 elapsed=115.5s

  [6617/15692] intraday_15106.csv.gz  in=290,801,026 out=73,941,313 elapsed=115.5s

  [6618/15692] intraday_15107.csv.gz  in=290,812,105 out=73,952,392 elapsed=115.5s

  [6619/15692] intraday_15108.csv.gz  in=290,825,919 out=73,966,206 elapsed=115.5s

  [6620/15692] intraday_1511.csv.gz  in=290,840,552 out=73,966,206 elapsed=115.5s

  [6621/15692] intraday_15110.csv.gz  in=290,850,534 out=73,976,188 elapsed=115.5s

  [6622/15692] intraday_15109.csv.gz  in=290,862,727 out=73,988,381 elapsed=115.5s

  [6623/15692] intraday_15112.csv.gz  in=290,870,158 out=73,995,812 elapsed=115.6s

  [6624/15692] intraday_15111.csv.gz  in=290,882,904 out=74,008,558 elapsed=115.6s

  [6625/15692] intraday_15114.csv.gz  in=290,896,294 out=74,021,534 elapsed=115.6s

  [6626/15692] intraday_15116.csv.gz  in=290,909,150 out=74,034,390 elapsed=115.6s

  [6627/15692] intraday_15115.csv.gz  in=290,923,357 out=74,048,597 elapsed=115.6s

  [6628/15692] intraday_15113.csv.gz  in=290,976,227 out=74,095,660 elapsed=115.7s

  [6629/15692] intraday_15117.csv.gz  in=290,988,188 out=74,107,621 elapsed=115.7s

  [6630/15692] intraday_15118.csv.gz  in=291,000,154 out=74,119,587 elapsed=115.7s

  [6631/15692] intraday_1512.csv.gz  in=291,012,811 out=74,119,587 elapsed=115.7s

  [6632/15692] intraday_15119.csv.gz  in=291,023,998 out=74,130,774 elapsed=115.7s

  [6633/15692] intraday_15120.csv.gz  in=291,038,942 out=74,145,718 elapsed=115.7s

  [6634/15692] intraday_15122.csv.gz  in=291,049,394 out=74,156,170 elapsed=115.7s

  [6635/15692] intraday_15121.csv.gz  in=291,062,749 out=74,169,525 elapsed=115.7s

  [6636/15692] intraday_15123.csv.gz  in=291,074,086 out=74,180,862 elapsed=115.7s

  [6637/15692] intraday_15124.csv.gz  in=291,085,980 out=74,192,756 elapsed=115.8s

  [6638/15692] intraday_15125.csv.gz  in=291,096,717 out=74,203,493 elapsed=115.8s

  [6639/15692] intraday_15127.csv.gz  in=291,109,054 out=74,215,830 elapsed=115.8s

  [6640/15692] intraday_15128.csv.gz  in=291,121,728 out=74,228,504 elapsed=115.8s

  [6641/15692] intraday_15129.csv.gz  in=291,131,675 out=74,238,451 elapsed=115.8s

  [6642/15692] intraday_15126.csv.gz  in=291,145,528 out=74,252,304 elapsed=115.8s

  [6643/15692] intraday_1513.csv.gz  in=291,156,408 out=74,252,304 elapsed=115.8s

  [6644/15692] intraday_15130.csv.gz  in=291,165,425 out=74,261,321 elapsed=115.8s

  [6645/15692] intraday_15132.csv.gz  in=291,177,515 out=74,273,411 elapsed=115.9s

  [6646/15692] intraday_15131.csv.gz  in=291,193,253 out=74,289,149 elapsed=115.9s

  [6647/15692] intraday_15133.csv.gz  in=291,203,224 out=74,299,120 elapsed=115.9s

  [6648/15692] intraday_15135.csv.gz  in=291,215,346 out=74,311,242 elapsed=115.9s

  [6649/15692] intraday_15136.csv.gz  in=291,228,476 out=74,324,372 elapsed=115.9s

  [6650/15692] intraday_15137.csv.gz  in=291,240,594 out=74,336,490 elapsed=115.9s

  [6651/15692] intraday_15138.csv.gz  in=291,253,143 out=74,349,039 elapsed=115.9s

  [6652/15692] intraday_15134.csv.gz  in=291,265,822 out=74,361,718 elapsed=115.9s

  [6653/15692] intraday_1514.csv.gz  in=291,274,669 out=74,361,718 elapsed=115.9s

  [6654/15692] intraday_15139.csv.gz  in=291,290,839 out=74,377,618 elapsed=116.0s

  [6655/15692] intraday_15140.csv.gz  in=291,301,579 out=74,388,358 elapsed=116.0s

  [6656/15692] intraday_15141.csv.gz  in=291,312,872 out=74,399,651 elapsed=116.0s

  [6657/15692] intraday_15142.csv.gz  in=291,323,942 out=74,410,721 elapsed=116.0s

  [6658/15692] intraday_15143.csv.gz  in=291,336,206 out=74,422,985 elapsed=116.0s

  [6659/15692] intraday_15144.csv.gz  in=291,348,658 out=74,435,437 elapsed=116.0s

  [6660/15692] intraday_15146.csv.gz  in=291,360,735 out=74,447,514 elapsed=116.1s

  [6661/15692] intraday_15145.csv.gz  in=291,376,235 out=74,463,014 elapsed=116.1s

  [6662/15692] intraday_15147.csv.gz  in=291,386,687 out=74,473,466 elapsed=116.1s

  [6663/15692] intraday_15148.csv.gz  in=291,399,607 out=74,486,386 elapsed=116.1s

  [6664/15692] intraday_15149.csv.gz  in=291,412,750 out=74,499,529 elapsed=116.1s

  [6665/15692] intraday_1515.csv.gz  in=291,423,609 out=74,499,529 elapsed=116.1s

  [6666/15692] intraday_15150.csv.gz  in=291,435,952 out=74,511,872 elapsed=116.1s

  [6667/15692] intraday_15151.csv.gz  in=291,448,687 out=74,524,607 elapsed=116.1s

  [6668/15692] intraday_15153.csv.gz  in=291,458,094 out=74,534,014 elapsed=116.2s

  [6669/15692] intraday_15152.csv.gz  in=291,469,298 out=74,545,218 elapsed=116.2s

  [6670/15692] intraday_15155.csv.gz  in=291,480,643 out=74,556,563 elapsed=116.2s

  [6671/15692] intraday_15154.csv.gz  in=291,490,813 out=74,566,733 elapsed=116.2s

  [6672/15692] intraday_15156.csv.gz  in=291,503,171 out=74,579,091 elapsed=116.2s

  [6673/15692] intraday_15158.csv.gz  in=291,516,357 out=74,592,277 elapsed=116.2s

  [6674/15692] intraday_15159.csv.gz  in=291,529,237 out=74,605,157 elapsed=116.2s

  [6675/15692] intraday_15157.csv.gz  in=291,542,643 out=74,618,563 elapsed=116.2s

  [6676/15692] intraday_1516.csv.gz  in=291,548,709 out=74,618,563 elapsed=116.2s

  [6677/15692] intraday_15160.csv.gz  in=291,559,834 out=74,629,688 elapsed=116.3s

  [6678/15692] intraday_15161.csv.gz  in=291,571,455 out=74,641,309 elapsed=116.3s

  [6679/15692] intraday_15162.csv.gz  in=291,584,335 out=74,654,189 elapsed=116.3s

  [6680/15692] intraday_15163.csv.gz  in=291,594,994 out=74,664,848 elapsed=116.3s

  [6681/15692] intraday_15164.csv.gz  in=291,607,002 out=74,676,856 elapsed=116.3s

  [6682/15692] intraday_15165.csv.gz  in=291,616,940 out=74,686,794 elapsed=116.3s

  [6683/15692] intraday_15166.csv.gz  in=291,631,914 out=74,701,768 elapsed=116.3s

  [6684/15692] intraday_15169.csv.gz  in=291,646,076 out=74,715,930 elapsed=116.4s

  [6685/15692] intraday_15167.csv.gz  in=291,658,108 out=74,727,962 elapsed=116.4s

  [6686/15692] intraday_15168.csv.gz  in=291,669,244 out=74,739,098 elapsed=116.4s

  [6687/15692] intraday_1517.csv.gz  in=291,684,496 out=74,739,098 elapsed=116.4s

  [6688/15692] intraday_15170.csv.gz  in=291,695,813 out=74,750,415 elapsed=116.4s

  [6689/15692] intraday_15171.csv.gz  in=291,707,760 out=74,762,362 elapsed=116.4s

  [6690/15692] intraday_15172.csv.gz  in=291,719,301 out=74,773,903 elapsed=116.4s

  [6691/15692] intraday_15173.csv.gz  in=291,730,996 out=74,785,598 elapsed=116.4s

  [6692/15692] intraday_15174.csv.gz  in=291,744,347 out=74,798,949 elapsed=116.4s

  [6693/15692] intraday_15175.csv.gz  in=291,755,865 out=74,810,467 elapsed=116.4s

  [6694/15692] intraday_15176.csv.gz  in=291,765,560 out=74,820,162 elapsed=116.4s

  [6695/15692] intraday_15178.csv.gz  in=291,774,613 out=74,829,215 elapsed=116.4s

  [6696/15692] intraday_15177.csv.gz  in=291,786,885 out=74,841,487 elapsed=116.5s

  [6697/15692] intraday_15179.csv.gz  in=291,799,766 out=74,854,368 elapsed=116.5s

  [6698/15692] intraday_1518.csv.gz  in=291,813,880 out=74,854,368 elapsed=116.5s

  [6699/15692] intraday_15180.csv.gz  in=291,827,876 out=74,868,364 elapsed=116.5s

  [6700/15692] intraday_15182.csv.gz  in=291,839,692 out=74,880,180 elapsed=116.5s

  [6701/15692] intraday_15184.csv.gz  in=291,848,197 out=74,888,685 elapsed=116.5s

  [6702/15692] intraday_15181.csv.gz  in=291,860,167 out=74,900,655 elapsed=116.5s

  [6703/15692] intraday_15183.csv.gz  in=291,873,532 out=74,914,020 elapsed=116.5s

  [6704/15692] intraday_15185.csv.gz  in=291,886,664 out=74,927,152 elapsed=116.5s

  [6705/15692] intraday_15187.csv.gz  in=291,898,981 out=74,939,469 elapsed=116.6s

  [6706/15692] intraday_15186.csv.gz  in=291,910,298 out=74,950,786 elapsed=116.6s

  [6707/15692] intraday_15188.csv.gz  in=291,919,938 out=74,960,426 elapsed=116.6s

  [6708/15692] intraday_1519.csv.gz  in=291,931,869 out=74,960,426 elapsed=116.6s

  [6709/15692] intraday_15189.csv.gz  in=291,945,008 out=74,973,565 elapsed=116.6s

  [6710/15692] intraday_15190.csv.gz  in=291,953,943 out=74,982,500 elapsed=116.6s

  [6711/15692] intraday_15191.csv.gz  in=291,965,858 out=74,994,415 elapsed=116.6s

  [6712/15692] intraday_15192.csv.gz  in=291,978,231 out=75,006,788 elapsed=116.6s

  [6713/15692] intraday_15194.csv.gz  in=291,989,564 out=75,018,121 elapsed=116.6s

  [6714/15692] intraday_15193.csv.gz  in=292,000,788 out=75,029,345 elapsed=116.6s

  [6715/15692] intraday_15196.csv.gz  in=292,012,279 out=75,040,836 elapsed=116.6s

  [6716/15692] intraday_15197.csv.gz  in=292,024,279 out=75,052,836 elapsed=116.7s

  [6717/15692] intraday_15195.csv.gz  in=292,034,145 out=75,062,702 elapsed=116.7s

  [6718/15692] intraday_15199.csv.gz  in=292,045,693 out=75,074,250 elapsed=116.7s

  [6719/15692] intraday_15198.csv.gz  in=292,062,342 out=75,090,899 elapsed=116.7s

  [6720/15692] intraday_1520.csv.gz  in=292,074,435 out=75,090,899 elapsed=116.7s

  [6721/15692] intraday_15200.csv.gz  in=292,088,774 out=75,105,238 elapsed=116.7s

  [6722/15692] intraday_15201.csv.gz  in=292,099,542 out=75,116,006 elapsed=116.7s

  [6723/15692] intraday_15203.csv.gz  in=292,109,741 out=75,126,205 elapsed=116.7s

  [6724/15692] intraday_15202.csv.gz  in=292,123,328 out=75,139,792 elapsed=116.7s

  [6725/15692] intraday_15204.csv.gz  in=292,138,184 out=75,154,648 elapsed=116.7s

  [6726/15692] intraday_15206.csv.gz  in=292,150,743 out=75,167,207 elapsed=116.7s

  [6727/15692] intraday_15205.csv.gz  in=292,160,561 out=75,177,025 elapsed=116.8s

  [6728/15692] intraday_15208.csv.gz  in=292,171,184 out=75,187,648 elapsed=116.8s

  [6729/15692] intraday_15207.csv.gz  in=292,183,919 out=75,200,354 elapsed=116.8s

  [6730/15692] intraday_1521.csv.gz  in=292,197,530 out=75,200,354 elapsed=116.8s

  [6731/15692] intraday_15209.csv.gz  in=292,210,724 out=75,213,548 elapsed=116.8s

  [6732/15692] intraday_15210.csv.gz  in=292,223,116 out=75,225,940 elapsed=116.8s

  [6733/15692] intraday_15211.csv.gz  in=292,236,030 out=75,238,854 elapsed=116.8s

  [6734/15692] intraday_15214.csv.gz  in=292,249,193 out=75,252,017 elapsed=116.8s

  [6735/15692] intraday_15213.csv.gz  in=292,260,930 out=75,263,754 elapsed=116.8s

  [6736/15692] intraday_15212.csv.gz  in=292,271,402 out=75,274,226 elapsed=116.8s

  [6737/15692] intraday_15215.csv.gz  in=292,284,126 out=75,286,950 elapsed=116.9s

  [6738/15692] intraday_15216.csv.gz  in=292,296,883 out=75,299,707 elapsed=116.9s

  [6739/15692] intraday_15217.csv.gz  in=292,308,552 out=75,311,376 elapsed=116.9s

  [6740/15692] intraday_15218.csv.gz  in=292,320,643 out=75,323,467 elapsed=116.9s

  [6741/15692] intraday_15219.csv.gz  in=292,332,212 out=75,335,036 elapsed=116.9s

  [6742/15692] intraday_15220.csv.gz  in=292,344,886 out=75,347,710 elapsed=116.9s

  [6743/15692] intraday_1522.csv.gz  in=292,358,465 out=75,347,710 elapsed=116.9s

  [6744/15692] intraday_15222.csv.gz  in=292,369,901 out=75,359,146 elapsed=116.9s

  [6745/15692] intraday_15221.csv.gz  in=292,383,934 out=75,373,179 elapsed=116.9s

  [6746/15692] intraday_15224.csv.gz  in=292,396,364 out=75,385,609 elapsed=117.0s

  [6747/15692] intraday_15223.csv.gz  in=292,409,367 out=75,398,612 elapsed=117.0s

  [6748/15692] intraday_15225.csv.gz  in=292,421,966 out=75,411,211 elapsed=117.0s

  [6749/15692] intraday_15226.csv.gz  in=292,436,900 out=75,426,028 elapsed=117.0s

  [6750/15692] intraday_15227.csv.gz  in=292,449,769 out=75,438,897 elapsed=117.0s

  [6751/15692] intraday_15228.csv.gz  in=292,463,612 out=75,452,740 elapsed=117.0s

  [6752/15692] intraday_15229.csv.gz  in=292,475,370 out=75,464,498 elapsed=117.0s

  [6753/15692] intraday_1523.csv.gz  in=292,487,894 out=75,464,498 elapsed=117.1s

  [6754/15692] intraday_15230.csv.gz  in=292,500,855 out=75,477,459 elapsed=117.1s

  [6755/15692] intraday_15231.csv.gz  in=292,518,104 out=75,494,708 elapsed=117.1s

  [6756/15692] intraday_15232.csv.gz  in=292,530,991 out=75,507,595 elapsed=117.1s

  [6757/15692] intraday_15233.csv.gz  in=292,547,527 out=75,524,131 elapsed=117.1s

  [6758/15692] intraday_15235.csv.gz  in=292,560,262 out=75,536,866 elapsed=117.1s

  [6759/15692] intraday_15236.csv.gz  in=292,570,621 out=75,547,225 elapsed=117.1s

  [6760/15692] intraday_15234.csv.gz  in=292,581,299 out=75,557,903 elapsed=117.1s

  [6761/15692] intraday_15238.csv.gz  in=292,591,742 out=75,568,346 elapsed=117.2s

  [6762/15692] intraday_15237.csv.gz  in=292,603,686 out=75,580,290 elapsed=117.2s

  [6763/15692] intraday_1524.csv.gz  in=292,616,079 out=75,580,290 elapsed=117.2s

  [6764/15692] intraday_15239.csv.gz  in=292,628,730 out=75,592,941 elapsed=117.2s

  [6765/15692] intraday_15240.csv.gz  in=292,640,124 out=75,604,335 elapsed=117.2s

  [6766/15692] intraday_15243.csv.gz  in=292,651,094 out=75,615,305 elapsed=117.2s

  [6767/15692] intraday_15242.csv.gz  in=292,660,809 out=75,625,020 elapsed=117.2s

  [6768/15692] intraday_15244.csv.gz  in=292,672,723 out=75,636,934 elapsed=117.3s

  [6769/15692] intraday_15241.csv.gz  in=292,687,819 out=75,652,030 elapsed=117.3s

  [6770/15692] intraday_15245.csv.gz  in=292,701,410 out=75,665,621 elapsed=117.3s

  [6771/15692] intraday_15246.csv.gz  in=292,711,545 out=75,675,756 elapsed=117.3s

  [6772/15692] intraday_15247.csv.gz  in=292,724,466 out=75,688,677 elapsed=117.3s

  [6773/15692] intraday_15248.csv.gz  in=292,739,880 out=75,704,091 elapsed=117.3s

  [6774/15692] intraday_15249.csv.gz  in=292,753,690 out=75,717,901 elapsed=117.3s

  [6775/15692] intraday_1525.csv.gz  in=292,767,171 out=75,717,901 elapsed=117.3s

  [6776/15692] intraday_15250.csv.gz  in=292,780,536 out=75,731,266 elapsed=117.3s

  [6777/15692] intraday_15251.csv.gz  in=292,793,008 out=75,743,738 elapsed=117.3s

  [6778/15692] intraday_15252.csv.gz  in=292,804,254 out=75,754,984 elapsed=117.4s

  [6779/15692] intraday_15254.csv.gz  in=292,814,454 out=75,765,184 elapsed=117.4s

  [6780/15692] intraday_15253.csv.gz  in=292,826,628 out=75,777,358 elapsed=117.4s

  [6781/15692] intraday_15255.csv.gz  in=292,838,481 out=75,789,211 elapsed=117.4s

  [6782/15692] intraday_15256.csv.gz  in=292,847,950 out=75,798,680 elapsed=117.4s

  [6783/15692] intraday_15257.csv.gz  in=292,856,504 out=75,807,234 elapsed=117.4s

  [6784/15692] intraday_15258.csv.gz  in=292,868,464 out=75,819,194 elapsed=117.4s

  [6785/15692] intraday_15259.csv.gz  in=292,883,292 out=75,834,022 elapsed=117.4s

  [6786/15692] intraday_1526.csv.gz  in=292,897,250 out=75,834,022 elapsed=117.4s

  [6787/15692] intraday_15260.csv.gz  in=292,909,628 out=75,846,400 elapsed=117.5s

  [6788/15692] intraday_15261.csv.gz  in=292,922,534 out=75,859,306 elapsed=117.5s

  [6789/15692] intraday_15264.csv.gz  in=292,937,730 out=75,874,502 elapsed=117.5s

  [6790/15692] intraday_15263.csv.gz  in=292,949,278 out=75,886,050 elapsed=117.5s

  [6791/15692] intraday_15262.csv.gz  in=292,961,825 out=75,898,597 elapsed=117.5s

  [6792/15692] intraday_15265.csv.gz  in=292,974,443 out=75,911,215 elapsed=117.5s

  [6793/15692] intraday_15266.csv.gz  in=292,985,806 out=75,922,578 elapsed=117.5s

  [6794/15692] intraday_15268.csv.gz  in=292,997,900 out=75,934,672 elapsed=117.6s

  [6795/15692] intraday_15267.csv.gz  in=293,010,149 out=75,946,921 elapsed=117.6s

  [6796/15692] intraday_1527.csv.gz  in=293,019,187 out=75,946,921 elapsed=117.6s

  [6797/15692] intraday_15269.csv.gz  in=293,029,941 out=75,957,675 elapsed=117.6s

  [6798/15692] intraday_15270.csv.gz  in=293,043,783 out=75,971,517 elapsed=117.6s

  [6799/15692] intraday_15272.csv.gz  in=293,056,177 out=75,983,911 elapsed=117.6s

  [6800/15692] intraday_15273.csv.gz  in=293,066,198 out=75,993,932 elapsed=117.6s

  [6801/15692] intraday_15271.csv.gz  in=293,080,290 out=76,008,024 elapsed=117.6s

  [6802/15692] intraday_15274.csv.gz  in=293,089,944 out=76,017,678 elapsed=117.6s

  [6803/15692] intraday_15277.csv.gz  in=293,099,725 out=76,027,459 elapsed=117.7s

  [6804/15692] intraday_15275.csv.gz  in=293,114,906 out=76,042,640 elapsed=117.7s

  [6805/15692] intraday_15276.csv.gz  in=293,128,322 out=76,056,056 elapsed=117.7s

  [6806/15692] intraday_15278.csv.gz  in=293,141,144 out=76,068,878 elapsed=117.7s

  [6807/15692] intraday_1528.csv.gz  in=293,152,902 out=76,068,878 elapsed=117.7s

  [6808/15692] intraday_15279.csv.gz  in=293,165,414 out=76,081,390 elapsed=117.7s

  [6809/15692] intraday_15282.csv.gz  in=293,177,433 out=76,093,409 elapsed=117.8s

  [6810/15692] intraday_15280.csv.gz  in=293,190,922 out=76,106,898 elapsed=117.8s

  [6811/15692] intraday_15281.csv.gz  in=293,202,486 out=76,118,462 elapsed=117.8s

  [6812/15692] intraday_15283.csv.gz  in=293,214,020 out=76,129,996 elapsed=117.8s

  [6813/15692] intraday_15284.csv.gz  in=293,226,392 out=76,142,368 elapsed=117.8s

  [6814/15692] intraday_15285.csv.gz  in=293,237,651 out=76,153,627 elapsed=117.8s

  [6815/15692] intraday_15286.csv.gz  in=293,248,211 out=76,164,187 elapsed=117.8s

  [6816/15692] intraday_15287.csv.gz  in=293,259,777 out=76,175,753 elapsed=117.8s

  [6817/15692] intraday_15288.csv.gz  in=293,273,374 out=76,189,350 elapsed=117.9s

  [6818/15692] intraday_15289.csv.gz  in=293,291,039 out=76,206,989 elapsed=117.9s

  [6819/15692] intraday_1529.csv.gz  in=293,305,261 out=76,206,989 elapsed=117.9s

  [6820/15692] intraday_15290.csv.gz  in=293,315,550 out=76,217,278 elapsed=117.9s

  [6821/15692] intraday_15291.csv.gz  in=293,326,773 out=76,228,501 elapsed=117.9s

  [6822/15692] intraday_15292.csv.gz  in=293,339,365 out=76,241,093 elapsed=117.9s

  [6823/15692] intraday_15294.csv.gz  in=293,350,974 out=76,252,702 elapsed=117.9s

  [6824/15692] intraday_15295.csv.gz  in=293,363,984 out=76,265,712 elapsed=118.0s

  [6825/15692] intraday_15293.csv.gz  in=293,395,142 out=76,295,972 elapsed=118.0s

  [6826/15692] intraday_15296.csv.gz  in=293,406,847 out=76,307,677 elapsed=118.0s

  [6827/15692] intraday_15298.csv.gz  in=293,416,253 out=76,317,083 elapsed=118.0s

  [6828/15692] intraday_15297.csv.gz  in=293,426,369 out=76,327,199 elapsed=118.0s

  [6829/15692] intraday_1530.csv.gz  in=293,437,234 out=76,327,199 elapsed=118.0s

  [6830/15692] intraday_15299.csv.gz  in=293,447,874 out=76,337,839 elapsed=118.0s

  [6831/15692] intraday_15300.csv.gz  in=293,459,680 out=76,349,645 elapsed=118.1s

  [6832/15692] intraday_15301.csv.gz  in=293,473,612 out=76,363,577 elapsed=118.1s

  [6833/15692] intraday_15302.csv.gz  in=293,486,434 out=76,376,399 elapsed=118.1s

  [6834/15692] intraday_15303.csv.gz  in=293,499,647 out=76,389,612 elapsed=118.1s

  [6835/15692] intraday_15304.csv.gz  in=293,510,771 out=76,400,736 elapsed=118.1s

  [6836/15692] intraday_15305.csv.gz  in=293,522,168 out=76,412,133 elapsed=118.1s

  [6837/15692] intraday_15306.csv.gz  in=293,535,237 out=76,425,202 elapsed=118.1s

  [6838/15692] intraday_15307.csv.gz  in=293,546,293 out=76,436,258 elapsed=118.1s

  [6839/15692] intraday_15308.csv.gz  in=293,557,641 out=76,447,606 elapsed=118.2s

  [6840/15692] intraday_1531.csv.gz  in=293,567,465 out=76,447,606 elapsed=118.2s

  [6841/15692] intraday_15309.csv.gz  in=293,577,707 out=76,457,848 elapsed=118.2s

  [6842/15692] intraday_15310.csv.gz  in=293,592,745 out=76,472,886 elapsed=118.2s

  [6843/15692] intraday_15311.csv.gz  in=293,604,731 out=76,484,872 elapsed=118.2s

  [6844/15692] intraday_15312.csv.gz  in=293,616,927 out=76,497,068 elapsed=118.2s

  [6845/15692] intraday_15313.csv.gz  in=293,631,754 out=76,511,895 elapsed=118.2s

  [6846/15692] intraday_15315.csv.gz  in=293,642,549 out=76,522,690 elapsed=118.2s

  [6847/15692] intraday_15314.csv.gz  in=293,654,723 out=76,534,864 elapsed=118.2s

  [6848/15692] intraday_15317.csv.gz  in=293,667,979 out=76,548,120 elapsed=118.2s

  [6849/15692] intraday_15318.csv.gz  in=293,680,827 out=76,560,968 elapsed=118.3s

  [6850/15692] intraday_15316.csv.gz  in=293,692,723 out=76,572,864 elapsed=118.3s

  [6851/15692] intraday_15319.csv.gz  in=293,703,752 out=76,583,893 elapsed=118.3s

  [6852/15692] intraday_1532.csv.gz  in=293,717,456 out=76,583,893 elapsed=118.3s

  [6853/15692] intraday_15322.csv.gz  in=293,727,184 out=76,593,621 elapsed=118.3s

  [6854/15692] intraday_15320.csv.gz  in=293,737,456 out=76,603,893 elapsed=118.3s

  [6855/15692] intraday_15323.csv.gz  in=293,751,625 out=76,618,062 elapsed=118.3s

  [6856/15692] intraday_15321.csv.gz  in=293,763,836 out=76,630,273 elapsed=118.3s

  [6857/15692] intraday_15324.csv.gz  in=293,776,744 out=76,643,181 elapsed=118.3s

  [6858/15692] intraday_15325.csv.gz  in=293,789,169 out=76,655,606 elapsed=118.4s

  [6859/15692] intraday_15326.csv.gz  in=293,801,111 out=76,667,548 elapsed=118.4s

  [6860/15692] intraday_15327.csv.gz  in=293,812,783 out=76,679,220 elapsed=118.4s

  [6861/15692] intraday_15328.csv.gz  in=293,821,518 out=76,687,955 elapsed=118.4s

  [6862/15692] intraday_15329.csv.gz  in=293,834,043 out=76,700,480 elapsed=118.4s

  [6863/15692] intraday_1533.csv.gz  in=293,845,496 out=76,700,480 elapsed=118.4s

  [6864/15692] intraday_15330.csv.gz  in=293,856,834 out=76,711,818 elapsed=118.4s

  [6865/15692] intraday_15331.csv.gz  in=293,869,158 out=76,724,142 elapsed=118.4s

  [6866/15692] intraday_15332.csv.gz  in=293,879,347 out=76,734,331 elapsed=118.4s

  [6867/15692] intraday_15333.csv.gz  in=293,891,960 out=76,746,944 elapsed=118.5s

  [6868/15692] intraday_15334.csv.gz  in=293,905,103 out=76,760,087 elapsed=118.5s

  [6869/15692] intraday_15335.csv.gz  in=293,916,846 out=76,771,830 elapsed=118.5s

  [6870/15692] intraday_15336.csv.gz  in=293,929,904 out=76,784,888 elapsed=118.5s

  [6871/15692] intraday_15337.csv.gz  in=293,941,619 out=76,796,603 elapsed=118.5s

  [6872/15692] intraday_15338.csv.gz  in=293,952,969 out=76,807,953 elapsed=118.5s

  [6873/15692] intraday_1534.csv.gz  in=293,965,173 out=76,807,953 elapsed=118.5s

  [6874/15692] intraday_15339.csv.gz  in=293,976,122 out=76,818,902 elapsed=118.5s

  [6875/15692] intraday_15341.csv.gz  in=293,988,250 out=76,831,030 elapsed=118.6s

  [6876/15692] intraday_15340.csv.gz  in=293,999,342 out=76,842,122 elapsed=118.6s

  [6877/15692] intraday_15342.csv.gz  in=294,017,197 out=76,859,977 elapsed=118.6s

  [6878/15692] intraday_15343.csv.gz  in=294,028,638 out=76,871,418 elapsed=118.6s

  [6879/15692] intraday_15345.csv.gz  in=294,039,001 out=76,881,781 elapsed=118.6s

  [6880/15692] intraday_15344.csv.gz  in=294,055,456 out=76,898,236 elapsed=118.6s

  [6881/15692] intraday_15347.csv.gz  in=294,065,516 out=76,908,296 elapsed=118.7s

  [6882/15692] intraday_15346.csv.gz  in=294,078,480 out=76,921,260 elapsed=118.7s

  [6883/15692] intraday_15349.csv.gz  in=294,089,076 out=76,931,856 elapsed=118.7s

  [6884/15692] intraday_15348.csv.gz  in=294,104,710 out=76,947,490 elapsed=118.7s

  [6885/15692] intraday_1535.csv.gz  in=294,116,566 out=76,947,490 elapsed=118.7s

  [6886/15692] intraday_15350.csv.gz  in=294,128,411 out=76,959,335 elapsed=118.7s

  [6887/15692] intraday_15351.csv.gz  in=294,138,874 out=76,969,798 elapsed=118.7s

  [6888/15692] intraday_15352.csv.gz  in=294,150,611 out=76,981,535 elapsed=118.7s

  [6889/15692] intraday_15353.csv.gz  in=294,163,268 out=76,994,192 elapsed=118.8s

  [6890/15692] intraday_15355.csv.gz  in=294,175,340 out=77,006,264 elapsed=118.8s

  [6891/15692] intraday_15354.csv.gz  in=294,191,169 out=77,022,093 elapsed=118.8s

  [6892/15692] intraday_15356.csv.gz  in=294,201,840 out=77,032,764 elapsed=118.8s

  [6893/15692] intraday_15358.csv.gz  in=294,213,936 out=77,044,860 elapsed=118.8s

  [6894/15692] intraday_15357.csv.gz  in=294,225,260 out=77,056,184 elapsed=118.8s

  [6895/15692] intraday_15359.csv.gz  in=294,238,099 out=77,069,023 elapsed=118.8s

  [6896/15692] intraday_1536.csv.gz  in=294,249,524 out=77,069,023 elapsed=118.8s

  [6897/15692] intraday_15360.csv.gz  in=294,262,789 out=77,082,288 elapsed=118.9s

  [6898/15692] intraday_15361.csv.gz  in=294,273,901 out=77,093,400 elapsed=118.9s

  [6899/15692] intraday_15363.csv.gz  in=294,284,078 out=77,103,577 elapsed=118.9s

  [6900/15692] intraday_15362.csv.gz  in=294,296,387 out=77,115,886 elapsed=118.9s

  [6901/15692] intraday_15364.csv.gz  in=294,310,008 out=77,129,507 elapsed=118.9s

  [6902/15692] intraday_15365.csv.gz  in=294,321,556 out=77,141,055 elapsed=118.9s

  [6903/15692] intraday_15367.csv.gz  in=294,334,708 out=77,154,207 elapsed=118.9s

  [6904/15692] intraday_15366.csv.gz  in=294,346,118 out=77,165,617 elapsed=118.9s

  [6905/15692] intraday_15368.csv.gz  in=294,358,936 out=77,178,435 elapsed=118.9s

  [6906/15692] intraday_15369.csv.gz  in=294,371,517 out=77,191,016 elapsed=118.9s

  [6907/15692] intraday_1537.csv.gz  in=294,383,551 out=77,191,016 elapsed=118.9s

  [6908/15692] intraday_15370.csv.gz  in=294,409,272 out=77,216,548 elapsed=119.0s

  [6909/15692] intraday_15372.csv.gz  in=294,422,729 out=77,230,005 elapsed=119.0s

  [6910/15692] intraday_15373.csv.gz  in=294,435,005 out=77,242,281 elapsed=119.0s

  [6911/15692] intraday_15371.csv.gz  in=294,447,637 out=77,254,913 elapsed=119.0s

  [6912/15692] intraday_15376.csv.gz  in=294,459,363 out=77,266,639 elapsed=119.0s

  [6913/15692] intraday_15375.csv.gz  in=294,478,436 out=77,285,712 elapsed=119.0s

  [6914/15692] intraday_15377.csv.gz  in=294,495,054 out=77,302,330 elapsed=119.1s

  [6915/15692] intraday_15374.csv.gz  in=294,508,593 out=77,315,869 elapsed=119.1s

  [6916/15692] intraday_15378.csv.gz  in=294,520,082 out=77,327,358 elapsed=119.1s

  [6917/15692] intraday_1538.csv.gz  in=294,531,952 out=77,327,358 elapsed=119.1s

  [6918/15692] intraday_15379.csv.gz  in=294,544,619 out=77,340,025 elapsed=119.1s

  [6919/15692] intraday_15380.csv.gz  in=294,554,889 out=77,350,295 elapsed=119.1s

  [6920/15692] intraday_15382.csv.gz  in=294,565,439 out=77,360,845 elapsed=119.1s

  [6921/15692] intraday_15381.csv.gz  in=294,577,788 out=77,373,194 elapsed=119.2s

  [6922/15692] intraday_15384.csv.gz  in=294,588,786 out=77,384,192 elapsed=119.2s

  [6923/15692] intraday_15383.csv.gz  in=294,601,900 out=77,397,306 elapsed=119.2s

  [6924/15692] intraday_15385.csv.gz  in=294,618,232 out=77,413,638 elapsed=119.2s

  [6925/15692] intraday_15386.csv.gz  in=294,628,824 out=77,424,230 elapsed=119.2s

  [6926/15692] intraday_15388.csv.gz  in=294,640,173 out=77,435,579 elapsed=119.2s

  [6927/15692] intraday_15387.csv.gz  in=294,651,400 out=77,446,806 elapsed=119.2s

  [6928/15692] intraday_1539.csv.gz  in=294,663,577 out=77,446,806 elapsed=119.2s

  [6929/15692] intraday_15389.csv.gz  in=294,677,034 out=77,460,263 elapsed=119.2s

  [6930/15692] intraday_15390.csv.gz  in=294,687,129 out=77,470,358 elapsed=119.3s

  [6931/15692] intraday_15392.csv.gz  in=294,701,390 out=77,484,619 elapsed=119.3s

  [6932/15692] intraday_15391.csv.gz  in=294,713,652 out=77,496,881 elapsed=119.3s

  [6933/15692] intraday_15393.csv.gz  in=294,726,648 out=77,509,877 elapsed=119.3s

  [6934/15692] intraday_15394.csv.gz  in=294,740,646 out=77,523,875 elapsed=119.3s

  [6935/15692] intraday_15396.csv.gz  in=294,751,759 out=77,534,988 elapsed=119.3s

  [6936/15692] intraday_15395.csv.gz  in=294,763,771 out=77,547,000 elapsed=119.4s

  [6937/15692] intraday_15398.csv.gz  in=294,773,605 out=77,556,834 elapsed=119.4s

  [6938/15692] intraday_15397.csv.gz  in=294,786,086 out=77,569,315 elapsed=119.4s

  [6939/15692] intraday_15399.csv.gz  in=294,798,334 out=77,581,563 elapsed=119.4s

  [6940/15692] intraday_1540.csv.gz  in=294,812,419 out=77,581,563 elapsed=119.4s

  [6941/15692] intraday_15401.csv.gz  in=294,819,702 out=77,588,846 elapsed=119.4s

  [6942/15692] intraday_15400.csv.gz  in=294,829,868 out=77,599,012 elapsed=119.4s

  [6943/15692] intraday_15403.csv.gz  in=294,844,807 out=77,613,951 elapsed=119.5s

  [6944/15692] intraday_15404.csv.gz  in=294,857,207 out=77,626,351 elapsed=119.5s

  [6945/15692] intraday_15402.csv.gz  in=294,868,939 out=77,638,083 elapsed=119.5s

  [6946/15692] intraday_15405.csv.gz  in=294,881,381 out=77,650,525 elapsed=119.5s

  [6947/15692] intraday_15406.csv.gz  in=294,891,890 out=77,661,034 elapsed=119.5s

  [6948/15692] intraday_15407.csv.gz  in=294,905,153 out=77,674,297 elapsed=119.5s

  [6949/15692] intraday_15409.csv.gz  in=294,916,842 out=77,685,986 elapsed=119.5s

  [6950/15692] intraday_1541.csv.gz  in=294,927,668 out=77,685,986 elapsed=119.6s

  [6951/15692] intraday_15408.csv.gz  in=294,942,373 out=77,700,691 elapsed=119.6s

  [6952/15692] intraday_15410.csv.gz  in=294,954,351 out=77,712,669 elapsed=119.6s

  [6953/15692] intraday_15411.csv.gz  in=294,965,779 out=77,724,097 elapsed=119.6s

  [6954/15692] intraday_15412.csv.gz  in=294,977,042 out=77,735,360 elapsed=119.6s

  [6955/15692] intraday_15413.csv.gz  in=294,988,133 out=77,746,451 elapsed=119.6s

  [6956/15692] intraday_15415.csv.gz  in=295,000,809 out=77,759,127 elapsed=119.6s

  [6957/15692] intraday_15414.csv.gz  in=295,013,413 out=77,771,731 elapsed=119.6s

  [6958/15692] intraday_15417.csv.gz  in=295,022,420 out=77,780,738 elapsed=119.7s

  [6959/15692] intraday_15416.csv.gz  in=295,036,432 out=77,794,750 elapsed=119.7s

  [6960/15692] intraday_15418.csv.gz  in=295,046,755 out=77,805,073 elapsed=119.7s

  [6961/15692] intraday_1542.csv.gz  in=295,057,045 out=77,805,073 elapsed=119.7s

  [6962/15692] intraday_15419.csv.gz  in=295,070,980 out=77,819,008 elapsed=119.7s

  [6963/15692] intraday_15420.csv.gz  in=295,083,549 out=77,831,577 elapsed=119.7s

  [6964/15692] intraday_15421.csv.gz  in=295,092,907 out=77,840,935 elapsed=119.7s

  [6965/15692] intraday_15422.csv.gz  in=295,106,069 out=77,854,097 elapsed=119.7s

  [6966/15692] intraday_15423.csv.gz  in=295,117,235 out=77,865,263 elapsed=119.8s

  [6967/15692] intraday_15424.csv.gz  in=295,129,547 out=77,877,575 elapsed=119.8s

  [6968/15692] intraday_15425.csv.gz  in=295,142,083 out=77,890,111 elapsed=119.8s

  [6969/15692] intraday_15427.csv.gz  in=295,154,304 out=77,902,332 elapsed=119.8s

  [6970/15692] intraday_15426.csv.gz  in=295,165,271 out=77,913,299 elapsed=119.8s

  [6971/15692] intraday_15428.csv.gz  in=295,175,868 out=77,923,896 elapsed=119.8s

  [6972/15692] intraday_15429.csv.gz  in=295,186,458 out=77,934,486 elapsed=119.8s

  [6973/15692] intraday_1543.csv.gz  in=295,200,109 out=77,934,486 elapsed=119.9s

  [6974/15692] intraday_15431.csv.gz  in=295,213,173 out=77,947,550 elapsed=119.9s

  [6975/15692] intraday_15430.csv.gz  in=295,223,635 out=77,958,012 elapsed=119.9s

  [6976/15692] intraday_15432.csv.gz  in=295,235,951 out=77,970,328 elapsed=119.9s

  [6977/15692] intraday_15433.csv.gz  in=295,249,753 out=77,984,130 elapsed=119.9s

  [6978/15692] intraday_15434.csv.gz  in=295,259,885 out=77,994,262 elapsed=119.9s

  [6979/15692] intraday_15435.csv.gz  in=295,270,406 out=78,004,783 elapsed=119.9s

  [6980/15692] intraday_15436.csv.gz  in=295,282,349 out=78,016,726 elapsed=119.9s

  [6981/15692] intraday_15437.csv.gz  in=295,302,102 out=78,036,479 elapsed=120.0s

  [6982/15692] intraday_1544.csv.gz  in=295,315,216 out=78,036,479 elapsed=120.0s

  [6983/15692] intraday_15438.csv.gz  in=295,326,260 out=78,047,523 elapsed=120.0s

  [6984/15692] intraday_15439.csv.gz  in=295,338,717 out=78,059,980 elapsed=120.0s

  [6985/15692] intraday_15440.csv.gz  in=295,349,626 out=78,070,889 elapsed=120.0s

  [6986/15692] intraday_15442.csv.gz  in=295,359,448 out=78,080,711 elapsed=120.0s

  [6987/15692] intraday_15443.csv.gz  in=295,370,424 out=78,091,687 elapsed=120.0s

  [6988/15692] intraday_15441.csv.gz  in=295,380,328 out=78,101,591 elapsed=120.0s

  [6989/15692] intraday_15445.csv.gz  in=295,393,454 out=78,114,717 elapsed=120.0s

  [6990/15692] intraday_15444.csv.gz  in=295,405,209 out=78,126,472 elapsed=120.1s

  [6991/15692] intraday_15446.csv.gz  in=295,418,038 out=78,139,301 elapsed=120.1s

  [6992/15692] intraday_15447.csv.gz  in=295,428,854 out=78,150,117 elapsed=120.1s

  [6993/15692] intraday_15448.csv.gz  in=295,440,281 out=78,161,544 elapsed=120.1s

  [6994/15692] intraday_15449.csv.gz  in=295,451,433 out=78,172,696 elapsed=120.1s

  [6995/15692] intraday_1545.csv.gz  in=295,466,259 out=78,172,696 elapsed=120.1s

  [6996/15692] intraday_15450.csv.gz  in=295,478,785 out=78,185,222 elapsed=120.1s

  [6997/15692] intraday_15451.csv.gz  in=295,489,284 out=78,195,721 elapsed=120.1s

  [6998/15692] intraday_15453.csv.gz  in=295,498,786 out=78,205,223 elapsed=120.1s

  [6999/15692] intraday_15452.csv.gz  in=295,509,758 out=78,216,195 elapsed=120.2s

  [7000/15692] intraday_15454.csv.gz  in=295,523,641 out=78,230,078 elapsed=120.2s

  [7001/15692] intraday_15455.csv.gz  in=295,534,826 out=78,241,263 elapsed=120.2s

  [7002/15692] intraday_15456.csv.gz  in=295,545,592 out=78,252,029 elapsed=120.2s

  [7003/15692] intraday_15457.csv.gz  in=295,559,892 out=78,266,329 elapsed=120.2s

  [7004/15692] intraday_15459.csv.gz  in=295,570,699 out=78,277,136 elapsed=120.2s

  [7005/15692] intraday_15458.csv.gz  in=295,581,624 out=78,288,061 elapsed=120.2s

  [7006/15692] intraday_1546.csv.gz  in=295,595,973 out=78,288,061 elapsed=120.2s

  [7007/15692] intraday_15460.csv.gz  in=295,606,913 out=78,299,001 elapsed=120.2s

  [7008/15692] intraday_15461.csv.gz  in=295,617,475 out=78,309,563 elapsed=120.3s

  [7009/15692] intraday_15462.csv.gz  in=295,629,563 out=78,321,651 elapsed=120.3s

  [7010/15692] intraday_15464.csv.gz  in=295,639,848 out=78,331,936 elapsed=120.3s

  [7011/15692] intraday_15463.csv.gz  in=295,670,539 out=78,362,627 elapsed=120.3s

  [7012/15692] intraday_15465.csv.gz  in=295,681,089 out=78,373,177 elapsed=120.3s

  [7013/15692] intraday_15466.csv.gz  in=295,690,661 out=78,382,749 elapsed=120.3s

  [7014/15692] intraday_15467.csv.gz  in=295,704,284 out=78,396,372 elapsed=120.3s

  [7015/15692] intraday_1547.csv.gz  in=295,716,211 out=78,396,372 elapsed=120.4s

  [7016/15692] intraday_15468.csv.gz  in=295,727,020 out=78,407,181 elapsed=120.4s

  [7017/15692] intraday_15471.csv.gz  in=295,738,163 out=78,418,324 elapsed=120.4s

  [7018/15692] intraday_15469.csv.gz  in=295,750,832 out=78,430,993 elapsed=120.4s

  [7019/15692] intraday_15472.csv.gz  in=295,758,977 out=78,439,138 elapsed=120.4s

  [7020/15692] intraday_15470.csv.gz  in=295,770,350 out=78,450,511 elapsed=120.4s

  [7021/15692] intraday_15473.csv.gz  in=295,782,834 out=78,462,995 elapsed=120.4s

  [7022/15692] intraday_15474.csv.gz  in=295,794,151 out=78,474,312 elapsed=120.5s

  [7023/15692] intraday_15475.csv.gz  in=295,805,015 out=78,485,176 elapsed=120.5s

  [7024/15692] intraday_15476.csv.gz  in=295,814,284 out=78,494,445 elapsed=120.5s

  [7025/15692] intraday_15478.csv.gz  in=295,822,811 out=78,502,972 elapsed=120.5s

  [7026/15692] intraday_15477.csv.gz  in=295,832,935 out=78,513,096 elapsed=120.5s

  [7027/15692] intraday_15479.csv.gz  in=295,846,859 out=78,527,020 elapsed=120.5s

  [7028/15692] intraday_1548.csv.gz  in=295,858,895 out=78,527,020 elapsed=120.5s

  [7029/15692] intraday_15480.csv.gz  in=295,870,349 out=78,538,474 elapsed=120.5s

  [7030/15692] intraday_15481.csv.gz  in=295,886,162 out=78,554,287 elapsed=120.6s

  [7031/15692] intraday_15482.csv.gz  in=295,896,575 out=78,564,700 elapsed=120.6s

  [7032/15692] intraday_15484.csv.gz  in=295,907,239 out=78,575,364 elapsed=120.6s

  [7033/15692] intraday_15485.csv.gz  in=295,918,562 out=78,586,687 elapsed=120.6s

  [7034/15692] intraday_15483.csv.gz  in=295,928,961 out=78,597,086 elapsed=120.6s

  [7035/15692] intraday_15486.csv.gz  in=295,944,813 out=78,612,938 elapsed=120.6s

  [7036/15692] intraday_15487.csv.gz  in=295,956,431 out=78,624,556 elapsed=120.6s

  [7037/15692] intraday_15488.csv.gz  in=295,969,775 out=78,637,900 elapsed=120.7s

  [7038/15692] intraday_1549.csv.gz  in=295,981,373 out=78,637,900 elapsed=120.7s

  [7039/15692] intraday_15489.csv.gz  in=295,992,768 out=78,649,295 elapsed=120.7s

  [7040/15692] intraday_15490.csv.gz  in=296,004,762 out=78,661,289 elapsed=120.7s

  [7041/15692] intraday_15491.csv.gz  in=296,016,739 out=78,673,266 elapsed=120.7s

  [7042/15692] intraday_15493.csv.gz  in=296,026,950 out=78,683,477 elapsed=120.7s

  [7043/15692] intraday_15492.csv.gz  in=296,040,128 out=78,696,655 elapsed=120.7s

  [7044/15692] intraday_15494.csv.gz  in=296,052,294 out=78,708,821 elapsed=120.7s

  [7045/15692] intraday_15495.csv.gz  in=296,063,280 out=78,719,807 elapsed=120.7s

  [7046/15692] intraday_15496.csv.gz  in=296,073,691 out=78,730,218 elapsed=120.8s

  [7047/15692] intraday_15498.csv.gz  in=296,084,478 out=78,741,005 elapsed=120.8s

  [7048/15692] intraday_15497.csv.gz  in=296,097,191 out=78,753,718 elapsed=120.8s

  [7049/15692] intraday_15499.csv.gz  in=296,108,617 out=78,765,144 elapsed=120.8s

  [7050/15692] intraday_15500.csv.gz  in=296,119,623 out=78,776,150 elapsed=120.8s

  [7051/15692] intraday_15501.csv.gz  in=296,130,316 out=78,786,843 elapsed=120.8s

  [7052/15692] intraday_15502.csv.gz  in=296,141,355 out=78,797,882 elapsed=120.8s

  [7053/15692] intraday_1550.csv.gz  in=296,175,578 out=78,797,882 elapsed=120.8s

  [7054/15692] intraday_15503.csv.gz  in=296,187,633 out=78,809,937 elapsed=120.8s

  [7055/15692] intraday_15504.csv.gz  in=296,199,465 out=78,821,769 elapsed=120.9s

  [7056/15692] intraday_15505.csv.gz  in=296,210,400 out=78,832,704 elapsed=120.9s

  [7057/15692] intraday_15506.csv.gz  in=296,222,011 out=78,844,315 elapsed=120.9s

  [7058/15692] intraday_15507.csv.gz  in=296,230,980 out=78,853,284 elapsed=120.9s

  [7059/15692] intraday_15508.csv.gz  in=296,245,864 out=78,868,168 elapsed=120.9s

  [7060/15692] intraday_1551.csv.gz  in=296,256,777 out=78,868,168 elapsed=120.9s

  [7061/15692] intraday_15509.csv.gz  in=296,265,973 out=78,877,364 elapsed=120.9s

  [7062/15692] intraday_15510.csv.gz  in=296,280,561 out=78,891,952 elapsed=120.9s

  [7063/15692] intraday_15512.csv.gz  in=296,294,173 out=78,905,564 elapsed=121.0s

  [7064/15692] intraday_15511.csv.gz  in=296,306,560 out=78,917,951 elapsed=121.0s

  [7065/15692] intraday_15513.csv.gz  in=296,316,584 out=78,927,975 elapsed=121.0s

  [7066/15692] intraday_15514.csv.gz  in=296,333,473 out=78,944,864 elapsed=121.0s

  [7067/15692] intraday_15516.csv.gz  in=296,344,546 out=78,955,937 elapsed=121.0s

  [7068/15692] intraday_15515.csv.gz  in=296,357,463 out=78,968,854 elapsed=121.0s

  [7069/15692] intraday_15517.csv.gz  in=296,369,953 out=78,981,344 elapsed=121.0s

  [7070/15692] intraday_15518.csv.gz  in=296,383,733 out=78,995,124 elapsed=121.0s

  [7071/15692] intraday_15519.csv.gz  in=296,400,996 out=79,012,387 elapsed=121.0s

  [7072/15692] intraday_1552.csv.gz  in=296,413,467 out=79,012,387 elapsed=121.0s

  [7073/15692] intraday_15521.csv.gz  in=296,426,901 out=79,025,821 elapsed=121.1s

  [7074/15692] intraday_15522.csv.gz  in=296,437,525 out=79,036,445 elapsed=121.1s

  [7075/15692] intraday_15520.csv.gz  in=296,451,097 out=79,050,017 elapsed=121.1s

  [7076/15692] intraday_15523.csv.gz  in=296,462,871 out=79,061,791 elapsed=121.1s

  [7077/15692] intraday_15525.csv.gz  in=296,475,528 out=79,074,448 elapsed=121.1s

  [7078/15692] intraday_15524.csv.gz  in=296,484,010 out=79,082,930 elapsed=121.1s

  [7079/15692] intraday_15526.csv.gz  in=296,493,893 out=79,092,813 elapsed=121.1s

  [7080/15692] intraday_15529.csv.gz  in=296,508,368 out=79,107,288 elapsed=121.2s

  [7081/15692] intraday_15527.csv.gz  in=296,520,073 out=79,118,993 elapsed=121.2s

  [7082/15692] intraday_15528.csv.gz  in=296,532,142 out=79,131,062 elapsed=121.2s

  [7083/15692] intraday_1553.csv.gz  in=296,543,955 out=79,131,062 elapsed=121.2s

  [7084/15692] intraday_15530.csv.gz  in=296,555,007 out=79,142,114 elapsed=121.2s

  [7085/15692] intraday_15531.csv.gz  in=296,565,497 out=79,152,604 elapsed=121.2s

  [7086/15692] intraday_15533.csv.gz  in=296,577,823 out=79,164,930 elapsed=121.2s

  [7087/15692] intraday_15534.csv.gz  in=296,588,426 out=79,175,533 elapsed=121.2s

  [7088/15692] intraday_15532.csv.gz  in=296,599,144 out=79,186,251 elapsed=121.2s

  [7089/15692] intraday_15535.csv.gz  in=296,611,538 out=79,198,645 elapsed=121.3s

  [7090/15692] intraday_15537.csv.gz  in=296,622,914 out=79,210,021 elapsed=121.3s

  [7091/15692] intraday_15536.csv.gz  in=296,636,450 out=79,223,557 elapsed=121.3s

  [7092/15692] intraday_15539.csv.gz  in=296,645,761 out=79,232,868 elapsed=121.3s

  [7093/15692] intraday_1554.csv.gz  in=296,657,559 out=79,232,868 elapsed=121.3s

  [7094/15692] intraday_15538.csv.gz  in=296,672,499 out=79,247,808 elapsed=121.3s

  [7095/15692] intraday_15540.csv.gz  in=296,683,872 out=79,259,181 elapsed=121.4s

  [7096/15692] intraday_15541.csv.gz  in=296,696,458 out=79,271,767 elapsed=121.4s

  [7097/15692] intraday_15542.csv.gz  in=296,713,780 out=79,289,089 elapsed=121.4s

  [7098/15692] intraday_15543.csv.gz  in=296,724,742 out=79,300,051 elapsed=121.4s

  [7099/15692] intraday_15544.csv.gz  in=296,732,050 out=79,307,359 elapsed=121.4s

  [7100/15692] intraday_15546.csv.gz  in=296,740,083 out=79,315,392 elapsed=121.4s

  [7101/15692] intraday_15547.csv.gz  in=296,756,177 out=79,331,486 elapsed=121.4s

  [7102/15692] intraday_15545.csv.gz  in=296,766,143 out=79,341,452 elapsed=121.4s

  [7103/15692] intraday_15548.csv.gz  in=296,778,406 out=79,353,715 elapsed=121.4s

  [7104/15692] intraday_15549.csv.gz  in=296,791,172 out=79,366,481 elapsed=121.5s

  [7105/15692] intraday_1555.csv.gz  in=296,803,987 out=79,366,481 elapsed=121.5s

  [7106/15692] intraday_15550.csv.gz  in=296,815,073 out=79,377,567 elapsed=121.5s

  [7107/15692] intraday_15551.csv.gz  in=296,827,138 out=79,389,632 elapsed=121.5s

  [7108/15692] intraday_15552.csv.gz  in=296,841,389 out=79,403,883 elapsed=121.5s

  [7109/15692] intraday_15553.csv.gz  in=296,854,867 out=79,417,361 elapsed=121.5s

  [7110/15692] intraday_15554.csv.gz  in=296,865,910 out=79,428,404 elapsed=121.5s

  [7111/15692] intraday_15555.csv.gz  in=296,880,958 out=79,443,452 elapsed=121.5s

  [7112/15692] intraday_15558.csv.gz  in=296,893,623 out=79,456,117 elapsed=121.6s

  [7113/15692] intraday_15556.csv.gz  in=296,906,158 out=79,468,652 elapsed=121.6s

  [7114/15692] intraday_15557.csv.gz  in=296,917,344 out=79,479,838 elapsed=121.6s

  [7115/15692] intraday_1556.csv.gz  in=296,929,355 out=79,479,838 elapsed=121.6s

  [7116/15692] intraday_15559.csv.gz  in=296,945,125 out=79,495,608 elapsed=121.6s

  [7117/15692] intraday_15561.csv.gz  in=296,955,835 out=79,506,318 elapsed=121.6s

  [7118/15692] intraday_15560.csv.gz  in=296,968,825 out=79,519,308 elapsed=121.7s

  [7119/15692] intraday_15562.csv.gz  in=296,979,327 out=79,529,810 elapsed=121.7s

  [7120/15692] intraday_15564.csv.gz  in=296,993,810 out=79,544,293 elapsed=121.7s

  [7121/15692] intraday_15563.csv.gz  in=297,009,051 out=79,559,534 elapsed=121.7s

  [7122/15692] intraday_15565.csv.gz  in=297,020,328 out=79,570,811 elapsed=121.7s

  [7123/15692] intraday_15566.csv.gz  in=297,032,071 out=79,582,554 elapsed=121.7s

  [7124/15692] intraday_15568.csv.gz  in=297,044,366 out=79,594,849 elapsed=121.7s

  [7125/15692] intraday_15569.csv.gz  in=297,057,828 out=79,608,311 elapsed=121.8s

  [7126/15692] intraday_1557.csv.gz  in=297,070,825 out=79,608,311 elapsed=121.8s

  [7127/15692] intraday_15567.csv.gz  in=297,103,849 out=79,641,335 elapsed=121.8s

  [7128/15692] intraday_15570.csv.gz  in=297,115,804 out=79,653,290 elapsed=121.8s

  [7129/15692] intraday_15572.csv.gz  in=297,127,649 out=79,665,135 elapsed=121.8s

  [7130/15692] intraday_15573.csv.gz  in=297,137,768 out=79,675,254 elapsed=121.8s

  [7131/15692] intraday_15571.csv.gz  in=297,150,118 out=79,687,604 elapsed=121.8s

  [7132/15692] intraday_15574.csv.gz  in=297,161,939 out=79,699,425 elapsed=121.8s

  [7133/15692] intraday_15575.csv.gz  in=297,174,351 out=79,711,837 elapsed=121.8s

  [7134/15692] intraday_15576.csv.gz  in=297,188,418 out=79,725,904 elapsed=121.9s

  [7135/15692] intraday_15578.csv.gz  in=297,201,440 out=79,738,926 elapsed=121.9s

  [7136/15692] intraday_15577.csv.gz  in=297,216,771 out=79,754,257 elapsed=121.9s

  [7137/15692] intraday_15579.csv.gz  in=297,227,567 out=79,765,053 elapsed=121.9s

  [7138/15692] intraday_1558.csv.gz  in=297,240,157 out=79,765,053 elapsed=121.9s

  [7139/15692] intraday_15581.csv.gz  in=297,253,371 out=79,778,267 elapsed=121.9s

  [7140/15692] intraday_15580.csv.gz  in=297,265,570 out=79,790,466 elapsed=121.9s

  [7141/15692] intraday_15582.csv.gz  in=297,277,776 out=79,802,672 elapsed=121.9s

  [7142/15692] intraday_15583.csv.gz  in=297,290,650 out=79,815,546 elapsed=121.9s

  [7143/15692] intraday_15584.csv.gz  in=297,299,812 out=79,824,708 elapsed=122.0s

  [7144/15692] intraday_15585.csv.gz  in=297,311,884 out=79,836,780 elapsed=122.0s

  [7145/15692] intraday_15586.csv.gz  in=297,321,045 out=79,845,941 elapsed=122.0s

  [7146/15692] intraday_15587.csv.gz  in=297,332,509 out=79,857,405 elapsed=122.0s

  [7147/15692] intraday_15588.csv.gz  in=297,344,404 out=79,869,300 elapsed=122.0s

  [7148/15692] intraday_1559.csv.gz  in=297,359,507 out=79,869,300 elapsed=122.0s

  [7149/15692] intraday_15589.csv.gz  in=297,373,983 out=79,883,776 elapsed=122.0s

  [7150/15692] intraday_15590.csv.gz  in=297,385,194 out=79,894,987 elapsed=122.0s

  [7151/15692] intraday_15591.csv.gz  in=297,400,630 out=79,910,423 elapsed=122.0s

  [7152/15692] intraday_15592.csv.gz  in=297,412,930 out=79,922,723 elapsed=122.1s

  [7153/15692] intraday_15593.csv.gz  in=297,424,598 out=79,934,391 elapsed=122.1s

  [7154/15692] intraday_15594.csv.gz  in=297,436,543 out=79,946,336 elapsed=122.1s

  [7155/15692] intraday_15595.csv.gz  in=297,448,550 out=79,958,343 elapsed=122.1s

  [7156/15692] intraday_15596.csv.gz  in=297,460,215 out=79,970,008 elapsed=122.1s

  [7157/15692] intraday_15597.csv.gz  in=297,469,976 out=79,979,769 elapsed=122.1s

  [7158/15692] intraday_15599.csv.gz  in=297,483,035 out=79,992,828 elapsed=122.1s

  [7159/15692] intraday_15598.csv.gz  in=297,495,618 out=80,005,411 elapsed=122.1s

  [7160/15692] intraday_1560.csv.gz  in=297,506,766 out=80,005,411 elapsed=122.2s

  [7161/15692] intraday_15600.csv.gz  in=297,520,404 out=80,019,049 elapsed=122.2s

  [7162/15692] intraday_15601.csv.gz  in=297,532,618 out=80,031,263 elapsed=122.2s

  [7163/15692] intraday_15602.csv.gz  in=297,546,059 out=80,044,704 elapsed=122.2s

  [7164/15692] intraday_15603.csv.gz  in=297,557,269 out=80,055,914 elapsed=122.2s

  [7165/15692] intraday_15604.csv.gz  in=297,567,683 out=80,066,328 elapsed=122.2s

  [7166/15692] intraday_15607.csv.gz  in=297,582,522 out=80,081,167 elapsed=122.2s

  [7167/15692] intraday_15606.csv.gz  in=297,596,065 out=80,094,710 elapsed=122.2s

  [7168/15692] intraday_15605.csv.gz  in=297,607,384 out=80,106,029 elapsed=122.2s

  [7169/15692] intraday_15608.csv.gz  in=297,618,981 out=80,117,626 elapsed=122.3s

  [7170/15692] intraday_1561.csv.gz  in=297,632,816 out=80,117,626 elapsed=122.3s

  [7171/15692] intraday_15609.csv.gz  in=297,644,391 out=80,129,201 elapsed=122.3s

  [7172/15692] intraday_15610.csv.gz  in=297,655,541 out=80,140,351 elapsed=122.3s

  [7173/15692] intraday_15614.csv.gz  in=297,667,800 out=80,152,610 elapsed=122.3s

  [7174/15692] intraday_15612.csv.gz  in=297,681,113 out=80,165,923 elapsed=122.4s

  [7175/15692] intraday_15613.csv.gz  in=297,694,861 out=80,179,671 elapsed=122.4s

  [7176/15692] intraday_15611.csv.gz  in=297,708,132 out=80,192,942 elapsed=122.4s

  [7177/15692] intraday_15615.csv.gz  in=297,720,656 out=80,205,466 elapsed=122.4s

  [7178/15692] intraday_15616.csv.gz  in=297,733,228 out=80,218,038 elapsed=122.4s

  [7179/15692] intraday_15617.csv.gz  in=297,744,941 out=80,229,751 elapsed=122.4s

  [7180/15692] intraday_15618.csv.gz  in=297,757,888 out=80,242,698 elapsed=122.4s

  [7181/15692] intraday_1562.csv.gz  in=297,768,524 out=80,242,698 elapsed=122.4s

  [7182/15692] intraday_15619.csv.gz  in=297,780,138 out=80,254,312 elapsed=122.4s

  [7183/15692] intraday_15620.csv.gz  in=297,791,383 out=80,265,557 elapsed=122.5s

  [7184/15692] intraday_15621.csv.gz  in=297,801,997 out=80,276,171 elapsed=122.5s

  [7185/15692] intraday_15622.csv.gz  in=297,812,559 out=80,286,733 elapsed=122.5s

  [7186/15692] intraday_15624.csv.gz  in=297,826,753 out=80,300,927 elapsed=122.5s

  [7187/15692] intraday_15626.csv.gz  in=297,837,800 out=80,311,974 elapsed=122.5s

  [7188/15692] intraday_15625.csv.gz  in=297,849,004 out=80,323,178 elapsed=122.5s

  [7189/15692] intraday_15623.csv.gz  in=297,861,286 out=80,335,460 elapsed=122.5s

  [7190/15692] intraday_15627.csv.gz  in=297,870,724 out=80,344,898 elapsed=122.6s

  [7191/15692] intraday_1563.csv.gz  in=297,882,773 out=80,344,898 elapsed=122.6s

  [7192/15692] intraday_15629.csv.gz  in=297,895,212 out=80,357,337 elapsed=122.6s

  [7193/15692] intraday_15628.csv.gz  in=297,906,799 out=80,368,924 elapsed=122.6s

  [7194/15692] intraday_15631.csv.gz  in=297,920,776 out=80,382,901 elapsed=122.6s

  [7195/15692] intraday_15630.csv.gz  in=297,934,565 out=80,396,690 elapsed=122.6s

  [7196/15692] intraday_15632.csv.gz  in=297,947,813 out=80,409,938 elapsed=122.6s

  [7197/15692] intraday_15633.csv.gz  in=297,959,750 out=80,421,875 elapsed=122.7s

  [7198/15692] intraday_15635.csv.gz  in=297,972,017 out=80,434,142 elapsed=122.7s

  [7199/15692] intraday_15636.csv.gz  in=297,987,360 out=80,449,485 elapsed=122.7s

  [7200/15692] intraday_15634.csv.gz  in=297,999,648 out=80,461,773 elapsed=122.7s

  [7201/15692] intraday_15638.csv.gz  in=298,011,182 out=80,473,307 elapsed=122.7s

  [7202/15692] intraday_15637.csv.gz  in=298,023,905 out=80,486,030 elapsed=122.7s

  [7203/15692] intraday_15639.csv.gz  in=298,036,733 out=80,498,858 elapsed=122.7s

  [7204/15692] intraday_1564.csv.gz  in=298,049,340 out=80,498,858 elapsed=122.8s

  [7205/15692] intraday_15640.csv.gz  in=298,061,326 out=80,510,844 elapsed=122.8s

  [7206/15692] intraday_15641.csv.gz  in=298,073,710 out=80,523,228 elapsed=122.8s

  [7207/15692] intraday_15642.csv.gz  in=298,086,622 out=80,536,140 elapsed=122.8s

  [7208/15692] intraday_15643.csv.gz  in=298,099,389 out=80,548,907 elapsed=122.8s

  [7209/15692] intraday_15644.csv.gz  in=298,110,577 out=80,560,095 elapsed=122.8s

  [7210/15692] intraday_15645.csv.gz  in=298,122,504 out=80,572,022 elapsed=122.8s

  [7211/15692] intraday_15646.csv.gz  in=298,133,962 out=80,583,480 elapsed=122.8s

  [7212/15692] intraday_15648.csv.gz  in=298,149,039 out=80,598,557 elapsed=122.9s

  [7213/15692] intraday_1565.csv.gz  in=298,159,319 out=80,598,557 elapsed=122.9s

  [7214/15692] intraday_15649.csv.gz  in=298,173,319 out=80,612,557 elapsed=122.9s

  [7215/15692] intraday_15647.csv.gz  in=298,184,752 out=80,623,990 elapsed=122.9s

  [7216/15692] intraday_15651.csv.gz  in=298,196,508 out=80,635,746 elapsed=122.9s

  [7217/15692] intraday_15650.csv.gz  in=298,208,388 out=80,647,626 elapsed=122.9s

  [7218/15692] intraday_15652.csv.gz  in=298,218,345 out=80,657,583 elapsed=122.9s

  [7219/15692] intraday_15654.csv.gz  in=298,229,282 out=80,668,520 elapsed=123.0s

  [7220/15692] intraday_15655.csv.gz  in=298,241,862 out=80,681,100 elapsed=123.0s

  [7221/15692] intraday_15653.csv.gz  in=298,257,523 out=80,696,761 elapsed=123.0s

  [7222/15692] intraday_15656.csv.gz  in=298,269,357 out=80,708,595 elapsed=123.0s

  [7223/15692] intraday_15657.csv.gz  in=298,283,328 out=80,722,566 elapsed=123.0s

  [7224/15692] intraday_15658.csv.gz  in=298,295,411 out=80,734,649 elapsed=123.0s

  [7225/15692] intraday_15659.csv.gz  in=298,310,405 out=80,749,643 elapsed=123.0s

  [7226/15692] intraday_1566.csv.gz  in=298,323,754 out=80,749,643 elapsed=123.0s

  [7227/15692] intraday_15661.csv.gz  in=298,333,839 out=80,759,728 elapsed=123.0s

  [7228/15692] intraday_15660.csv.gz  in=298,347,951 out=80,773,840 elapsed=123.1s

  [7229/15692] intraday_15662.csv.gz  in=298,362,117 out=80,788,006 elapsed=123.1s

  [7230/15692] intraday_15663.csv.gz  in=298,378,489 out=80,804,378 elapsed=123.1s

  [7231/15692] intraday_15664.csv.gz  in=298,393,945 out=80,819,834 elapsed=123.1s

  [7232/15692] intraday_15666.csv.gz  in=298,405,836 out=80,831,725 elapsed=123.1s

  [7233/15692] intraday_15667.csv.gz  in=298,418,146 out=80,844,035 elapsed=123.1s

  [7234/15692] intraday_15665.csv.gz  in=298,433,107 out=80,858,996 elapsed=123.1s

  [7235/15692] intraday_15668.csv.gz  in=298,445,145 out=80,871,034 elapsed=123.1s

  [7236/15692] intraday_15669.csv.gz  in=298,455,495 out=80,881,384 elapsed=123.2s

  [7237/15692] intraday_1567.csv.gz  in=298,470,681 out=80,881,384 elapsed=123.2s

  [7238/15692] intraday_15670.csv.gz  in=298,482,595 out=80,893,298 elapsed=123.2s

  [7239/15692] intraday_15671.csv.gz  in=298,493,400 out=80,904,103 elapsed=123.2s

  [7240/15692] intraday_15672.csv.gz  in=298,508,227 out=80,918,930 elapsed=123.2s

  [7241/15692] intraday_15673.csv.gz  in=298,520,562 out=80,931,265 elapsed=123.2s

  [7242/15692] intraday_15674.csv.gz  in=298,534,402 out=80,945,105 elapsed=123.2s

  [7243/15692] intraday_15675.csv.gz  in=298,545,714 out=80,956,417 elapsed=123.3s

  [7244/15692] intraday_15676.csv.gz  in=298,556,789 out=80,967,492 elapsed=123.3s

  [7245/15692] intraday_15677.csv.gz  in=298,570,067 out=80,980,770 elapsed=123.3s

  [7246/15692] intraday_15678.csv.gz  in=298,581,658 out=80,992,361 elapsed=123.3s

  [7247/15692] intraday_15679.csv.gz  in=298,593,932 out=81,004,635 elapsed=123.3s

  [7248/15692] intraday_15680.csv.gz  in=298,607,325 out=81,018,028 elapsed=123.3s

  [7249/15692] intraday_1568.csv.gz  in=298,619,380 out=81,018,028 elapsed=123.3s

  [7250/15692] intraday_15681.csv.gz  in=298,632,828 out=81,031,476 elapsed=123.3s

  [7251/15692] intraday_15682.csv.gz  in=298,645,398 out=81,044,046 elapsed=123.4s

  [7252/15692] intraday_15683.csv.gz  in=298,659,464 out=81,058,112 elapsed=123.4s

  [7253/15692] intraday_15684.csv.gz  in=298,672,467 out=81,071,115 elapsed=123.4s

  [7254/15692] intraday_15685.csv.gz  in=298,684,482 out=81,083,130 elapsed=123.4s

  [7255/15692] intraday_15686.csv.gz  in=298,697,001 out=81,095,649 elapsed=123.4s

  [7256/15692] intraday_15687.csv.gz  in=298,708,557 out=81,107,205 elapsed=123.4s

  [7257/15692] intraday_15688.csv.gz  in=298,718,649 out=81,117,297 elapsed=123.4s

  [7258/15692] intraday_15689.csv.gz  in=298,727,764 out=81,126,412 elapsed=123.4s

  [7259/15692] intraday_1569.csv.gz  in=298,739,453 out=81,126,412 elapsed=123.4s

  [7260/15692] intraday_15690.csv.gz  in=298,749,252 out=81,136,211 elapsed=123.5s

  [7261/15692] intraday_15691.csv.gz  in=298,754,613 out=81,141,572 elapsed=123.5s

  [7262/15692] intraday_1570.csv.gz  in=298,767,320 out=81,141,572 elapsed=123.5s

  [7263/15692] intraday_15692.csv.gz  in=298,783,026 out=81,157,278 elapsed=123.5s

  [7264/15692] intraday_1572.csv.gz  in=298,794,556 out=81,157,278 elapsed=123.5s

  [7265/15692] intraday_1573.csv.gz  in=298,807,398 out=81,157,278 elapsed=123.5s

  [7266/15692] intraday_1571.csv.gz  in=298,819,881 out=81,157,278 elapsed=123.5s

  [7267/15692] intraday_1574.csv.gz  in=298,832,753 out=81,157,278 elapsed=123.5s

  [7268/15692] intraday_1576.csv.gz  in=298,845,419 out=81,157,278 elapsed=123.5s

  [7269/15692] intraday_1577.csv.gz  in=298,857,736 out=81,157,278 elapsed=123.5s

  [7270/15692] intraday_1578.csv.gz  in=298,867,149 out=81,157,278 elapsed=123.6s

  [7271/15692] intraday_1575.csv.gz  in=298,894,084 out=81,157,278 elapsed=123.6s

  [7272/15692] intraday_1579.csv.gz  in=298,906,315 out=81,157,278 elapsed=123.6s

  [7273/15692] intraday_1580.csv.gz  in=298,919,921 out=81,157,278 elapsed=123.6s

  [7274/15692] intraday_1582.csv.gz  in=298,933,915 out=81,157,278 elapsed=123.6s

  [7275/15692] intraday_1584.csv.gz  in=298,947,831 out=81,157,278 elapsed=123.6s

  [7276/15692] intraday_1581.csv.gz  in=298,958,393 out=81,157,278 elapsed=123.6s

  [7277/15692] intraday_1583.csv.gz  in=298,972,055 out=81,157,278 elapsed=123.6s

  [7278/15692] intraday_1585.csv.gz  in=298,983,224 out=81,157,278 elapsed=123.6s

  [7279/15692] intraday_1586.csv.gz  in=298,995,595 out=81,157,278 elapsed=123.6s

  [7280/15692] intraday_1587.csv.gz  in=299,008,201 out=81,157,278 elapsed=123.7s

  [7281/15692] intraday_1588.csv.gz  in=299,019,595 out=81,157,278 elapsed=123.7s

  [7282/15692] intraday_1590.csv.gz  in=299,031,091 out=81,157,278 elapsed=123.7s

  [7283/15692] intraday_1589.csv.gz  in=299,042,613 out=81,157,278 elapsed=123.7s

  [7284/15692] intraday_1591.csv.gz  in=299,054,633 out=81,157,278 elapsed=123.7s

  [7285/15692] intraday_1592.csv.gz  in=299,066,070 out=81,157,278 elapsed=123.7s

  [7286/15692] intraday_1593.csv.gz  in=299,077,989 out=81,157,278 elapsed=123.7s

  [7287/15692] intraday_1594.csv.gz  in=299,089,224 out=81,157,278 elapsed=123.7s

  [7288/15692] intraday_1595.csv.gz  in=299,099,373 out=81,157,278 elapsed=123.7s

  [7289/15692] intraday_1596.csv.gz  in=299,111,122 out=81,157,278 elapsed=123.7s

  [7290/15692] intraday_1597.csv.gz  in=299,123,253 out=81,157,278 elapsed=123.7s

  [7291/15692] intraday_1598.csv.gz  in=299,138,843 out=81,157,278 elapsed=123.7s

  [7292/15692] intraday_1599.csv.gz  in=299,164,625 out=81,157,278 elapsed=123.8s

  [7293/15692] intraday_1600.csv.gz  in=299,174,710 out=81,157,278 elapsed=123.8s

  [7294/15692] intraday_1601.csv.gz  in=299,186,077 out=81,157,278 elapsed=123.8s

  [7295/15692] intraday_1602.csv.gz  in=299,198,362 out=81,157,278 elapsed=123.8s

  [7296/15692] intraday_1603.csv.gz  in=299,213,588 out=81,157,278 elapsed=123.8s

  [7297/15692] intraday_1605.csv.gz  in=299,227,370 out=81,157,278 elapsed=123.8s

  [7298/15692] intraday_1604.csv.gz  in=299,239,772 out=81,157,278 elapsed=123.8s

  [7299/15692] intraday_1606.csv.gz  in=299,252,757 out=81,157,278 elapsed=123.8s

  [7300/15692] intraday_1608.csv.gz  in=299,266,818 out=81,157,278 elapsed=123.8s

  [7301/15692] intraday_1607.csv.gz  in=299,281,031 out=81,157,278 elapsed=123.8s

  [7302/15692] intraday_1609.csv.gz  in=299,294,148 out=81,157,278 elapsed=123.8s

  [7303/15692] intraday_1610.csv.gz  in=299,307,047 out=81,157,278 elapsed=123.8s

  [7304/15692] intraday_1611.csv.gz  in=299,318,711 out=81,157,278 elapsed=123.8s

  [7305/15692] intraday_1612.csv.gz  in=299,329,813 out=81,157,278 elapsed=123.8s

  [7306/15692] intraday_1614.csv.gz  in=299,344,105 out=81,157,278 elapsed=123.9s

  [7307/15692] intraday_1615.csv.gz  in=299,355,482 out=81,157,278 elapsed=123.9s

  [7308/15692] intraday_1613.csv.gz  in=299,370,792 out=81,157,278 elapsed=123.9s

  [7309/15692] intraday_1616.csv.gz  in=299,383,083 out=81,157,278 elapsed=123.9s

  [7310/15692] intraday_1617.csv.gz  in=299,395,329 out=81,157,278 elapsed=123.9s

  [7311/15692] intraday_1618.csv.gz  in=299,407,496 out=81,157,278 elapsed=123.9s

  [7312/15692] intraday_1619.csv.gz  in=299,419,938 out=81,157,278 elapsed=123.9s

  [7313/15692] intraday_1620.csv.gz  in=299,432,184 out=81,157,278 elapsed=123.9s

  [7314/15692] intraday_1621.csv.gz  in=299,445,351 out=81,157,278 elapsed=123.9s

  [7315/15692] intraday_1623.csv.gz  in=299,460,021 out=81,157,278 elapsed=123.9s

  [7316/15692] intraday_1622.csv.gz  in=299,473,015 out=81,157,278 elapsed=123.9s

  [7317/15692] intraday_1624.csv.gz  in=299,484,465 out=81,157,278 elapsed=123.9s

  [7318/15692] intraday_1625.csv.gz  in=299,498,740 out=81,157,278 elapsed=124.0s

  [7319/15692] intraday_1628.csv.gz  in=299,509,968 out=81,157,278 elapsed=124.0s

  [7320/15692] intraday_1627.csv.gz  in=299,527,357 out=81,157,278 elapsed=124.0s

  [7321/15692] intraday_1626.csv.gz  in=299,540,953 out=81,157,278 elapsed=124.0s

  [7322/15692] intraday_1629.csv.gz  in=299,554,360 out=81,157,278 elapsed=124.0s

  [7323/15692] intraday_1631.csv.gz  in=299,567,099 out=81,157,278 elapsed=124.0s

  [7324/15692] intraday_1632.csv.gz  in=299,580,142 out=81,157,278 elapsed=124.0s

  [7325/15692] intraday_1630.csv.gz  in=299,596,131 out=81,157,278 elapsed=124.0s

  [7326/15692] intraday_1633.csv.gz  in=299,611,004 out=81,157,278 elapsed=124.0s

  [7327/15692] intraday_1634.csv.gz  in=299,621,645 out=81,157,278 elapsed=124.0s

  [7328/15692] intraday_1636.csv.gz  in=299,634,191 out=81,157,278 elapsed=124.1s

  [7329/15692] intraday_1635.csv.gz  in=299,646,114 out=81,157,278 elapsed=124.1s

  [7330/15692] intraday_1637.csv.gz  in=299,660,314 out=81,157,278 elapsed=124.1s

  [7331/15692] intraday_1638.csv.gz  in=299,675,895 out=81,157,278 elapsed=124.1s

  [7332/15692] intraday_1639.csv.gz  in=299,689,123 out=81,157,278 elapsed=124.1s

  [7333/15692] intraday_1641.csv.gz  in=299,703,223 out=81,157,278 elapsed=124.1s

  [7334/15692] intraday_1642.csv.gz  in=299,716,397 out=81,157,278 elapsed=124.1s

  [7335/15692] intraday_1640.csv.gz  in=299,730,337 out=81,157,278 elapsed=124.1s

  [7336/15692] intraday_1643.csv.gz  in=299,742,741 out=81,157,278 elapsed=124.1s

  [7337/15692] intraday_1646.csv.gz  in=299,755,048 out=81,157,278 elapsed=124.2s

  [7338/15692] intraday_1645.csv.gz  in=299,770,481 out=81,157,278 elapsed=124.2s

  [7339/15692] intraday_1644.csv.gz  in=299,786,539 out=81,157,278 elapsed=124.2s

  [7340/15692] intraday_1647.csv.gz  in=299,801,479 out=81,157,278 elapsed=124.2s

  [7341/15692] intraday_1648.csv.gz  in=299,812,371 out=81,157,278 elapsed=124.2s

  [7342/15692] intraday_1649.csv.gz  in=299,823,837 out=81,157,278 elapsed=124.2s

  [7343/15692] intraday_1650.csv.gz  in=299,836,034 out=81,157,278 elapsed=124.2s

  [7344/15692] intraday_1651.csv.gz  in=299,847,663 out=81,157,278 elapsed=124.2s

  [7345/15692] intraday_1652.csv.gz  in=299,857,359 out=81,157,278 elapsed=124.2s

  [7346/15692] intraday_1653.csv.gz  in=299,865,673 out=81,157,278 elapsed=124.2s

  [7347/15692] intraday_1655.csv.gz  in=299,869,753 out=81,157,278 elapsed=124.2s

  [7348/15692] intraday_1654.csv.gz  in=299,880,710 out=81,157,278 elapsed=124.3s

  [7349/15692] intraday_1656.csv.gz  in=299,895,162 out=81,157,278 elapsed=124.3s

  [7350/15692] intraday_1657.csv.gz  in=299,909,293 out=81,157,278 elapsed=124.3s

  [7351/15692] intraday_1658.csv.gz  in=299,921,159 out=81,157,278 elapsed=124.3s

  [7352/15692] intraday_1659.csv.gz  in=299,932,450 out=81,157,278 elapsed=124.3s

  [7353/15692] intraday_1662.csv.gz  in=299,944,807 out=81,157,278 elapsed=124.3s

  [7354/15692] intraday_1660.csv.gz  in=299,958,359 out=81,157,278 elapsed=124.3s

  [7355/15692] intraday_1661.csv.gz  in=299,972,070 out=81,157,278 elapsed=124.3s

  [7356/15692] intraday_1663.csv.gz  in=299,984,125 out=81,157,278 elapsed=124.3s

  [7357/15692] intraday_1664.csv.gz  in=299,997,990 out=81,157,278 elapsed=124.3s

  [7358/15692] intraday_1665.csv.gz  in=300,012,202 out=81,157,278 elapsed=124.3s

  [7359/15692] intraday_1666.csv.gz  in=300,021,492 out=81,157,278 elapsed=124.4s

  [7360/15692] intraday_1667.csv.gz  in=300,033,208 out=81,157,278 elapsed=124.4s

  [7361/15692] intraday_1668.csv.gz  in=300,052,263 out=81,157,278 elapsed=124.4s

  [7362/15692] intraday_1669.csv.gz  in=300,063,113 out=81,157,278 elapsed=124.4s

  [7363/15692] intraday_1670.csv.gz  in=300,072,717 out=81,157,278 elapsed=124.4s

  [7364/15692] intraday_1672.csv.gz  in=300,084,097 out=81,157,278 elapsed=124.4s

  [7365/15692] intraday_1673.csv.gz  in=300,096,218 out=81,157,278 elapsed=124.4s

  [7366/15692] intraday_1671.csv.gz  in=300,109,777 out=81,157,278 elapsed=124.4s

  [7367/15692] intraday_1674.csv.gz  in=300,121,423 out=81,157,278 elapsed=124.4s

  [7368/15692] intraday_1675.csv.gz  in=300,133,305 out=81,157,278 elapsed=124.4s

  [7369/15692] intraday_1676.csv.gz  in=300,146,636 out=81,157,278 elapsed=124.4s

  [7370/15692] intraday_1677.csv.gz  in=300,158,387 out=81,157,278 elapsed=124.4s

  [7371/15692] intraday_1678.csv.gz  in=300,171,041 out=81,157,278 elapsed=124.5s

  [7372/15692] intraday_1679.csv.gz  in=300,194,404 out=81,157,278 elapsed=124.5s

  [7373/15692] intraday_1680.csv.gz  in=300,205,534 out=81,157,278 elapsed=124.5s

  [7374/15692] intraday_1681.csv.gz  in=300,215,344 out=81,157,278 elapsed=124.5s

  [7375/15692] intraday_1682.csv.gz  in=300,228,064 out=81,157,278 elapsed=124.5s

  [7376/15692] intraday_1683.csv.gz  in=300,240,607 out=81,157,278 elapsed=124.5s

  [7377/15692] intraday_1686.csv.gz  in=300,252,254 out=81,157,278 elapsed=124.5s

  [7378/15692] intraday_1685.csv.gz  in=300,265,956 out=81,157,278 elapsed=124.5s

  [7379/15692] intraday_1684.csv.gz  in=300,285,955 out=81,157,278 elapsed=124.5s

  [7380/15692] intraday_1687.csv.gz  in=300,306,045 out=81,157,278 elapsed=124.6s

  [7381/15692] intraday_1688.csv.gz  in=300,317,514 out=81,157,278 elapsed=124.6s

  [7382/15692] intraday_1690.csv.gz  in=300,328,064 out=81,157,278 elapsed=124.6s

  [7383/15692] intraday_1689.csv.gz  in=300,340,964 out=81,157,278 elapsed=124.6s

  [7384/15692] intraday_1692.csv.gz  in=300,353,035 out=81,157,278 elapsed=124.6s

  [7385/15692] intraday_1693.csv.gz  in=300,363,866 out=81,157,278 elapsed=124.6s

  [7386/15692] intraday_1691.csv.gz  in=300,376,688 out=81,157,278 elapsed=124.6s

  [7387/15692] intraday_1694.csv.gz  in=300,399,957 out=81,157,278 elapsed=124.6s

  [7388/15692] intraday_1695.csv.gz  in=300,415,057 out=81,157,278 elapsed=124.6s

  [7389/15692] intraday_1696.csv.gz  in=300,427,941 out=81,157,278 elapsed=124.6s

  [7390/15692] intraday_1697.csv.gz  in=300,439,927 out=81,157,278 elapsed=124.6s

  [7391/15692] intraday_1699.csv.gz  in=300,451,936 out=81,157,278 elapsed=124.7s

  [7392/15692] intraday_1698.csv.gz  in=300,467,059 out=81,157,278 elapsed=124.7s

  [7393/15692] intraday_1701.csv.gz  in=300,478,250 out=81,157,278 elapsed=124.7s

  [7394/15692] intraday_1702.csv.gz  in=300,490,415 out=81,157,278 elapsed=124.7s

  [7395/15692] intraday_1700.csv.gz  in=300,517,056 out=81,157,278 elapsed=124.7s

  [7396/15692] intraday_1703.csv.gz  in=300,529,086 out=81,157,278 elapsed=124.7s

  [7397/15692] intraday_1704.csv.gz  in=300,539,523 out=81,157,278 elapsed=124.7s

  [7398/15692] intraday_1705.csv.gz  in=300,549,136 out=81,157,278 elapsed=124.7s

  [7399/15692] intraday_1706.csv.gz  in=300,563,990 out=81,157,278 elapsed=124.8s

  [7400/15692] intraday_1707.csv.gz  in=300,575,148 out=81,157,278 elapsed=124.8s

  [7401/15692] intraday_1708.csv.gz  in=300,586,601 out=81,157,278 elapsed=124.8s

  [7402/15692] intraday_1709.csv.gz  in=300,598,434 out=81,157,278 elapsed=124.8s

  [7403/15692] intraday_1710.csv.gz  in=300,611,119 out=81,157,278 elapsed=124.8s

  [7404/15692] intraday_1711.csv.gz  in=300,630,544 out=81,157,278 elapsed=124.8s

  [7405/15692] intraday_1713.csv.gz  in=300,643,495 out=81,157,278 elapsed=124.8s

  [7406/15692] intraday_1712.csv.gz  in=300,655,407 out=81,157,278 elapsed=124.8s

  [7407/15692] intraday_1714.csv.gz  in=300,666,343 out=81,157,278 elapsed=124.8s

  [7408/15692] intraday_1715.csv.gz  in=300,679,601 out=81,157,278 elapsed=124.8s

  [7409/15692] intraday_1717.csv.gz  in=300,689,979 out=81,157,278 elapsed=124.9s

  [7410/15692] intraday_1716.csv.gz  in=300,701,255 out=81,157,278 elapsed=124.9s

  [7411/15692] intraday_1719.csv.gz  in=300,714,394 out=81,157,278 elapsed=124.9s

  [7412/15692] intraday_1718.csv.gz  in=300,729,894 out=81,157,278 elapsed=124.9s

  [7413/15692] intraday_1720.csv.gz  in=300,742,468 out=81,157,278 elapsed=124.9s

  [7414/15692] intraday_1722.csv.gz  in=300,755,704 out=81,157,278 elapsed=124.9s

  [7415/15692] intraday_1721.csv.gz  in=300,769,919 out=81,157,278 elapsed=124.9s

  [7416/15692] intraday_1724.csv.gz  in=300,782,021 out=81,157,278 elapsed=124.9s

  [7417/15692] intraday_1723.csv.gz  in=300,791,167 out=81,157,278 elapsed=124.9s

  [7418/15692] intraday_1725.csv.gz  in=300,803,153 out=81,157,278 elapsed=124.9s

  [7419/15692] intraday_1727.csv.gz  in=300,815,050 out=81,157,278 elapsed=124.9s

  [7420/15692] intraday_1726.csv.gz  in=300,827,596 out=81,157,278 elapsed=124.9s

  [7421/15692] intraday_1728.csv.gz  in=300,838,292 out=81,157,278 elapsed=125.0s

  [7422/15692] intraday_1729.csv.gz  in=300,850,408 out=81,157,278 elapsed=125.0s

  [7423/15692] intraday_1730.csv.gz  in=300,861,684 out=81,157,278 elapsed=125.0s

  [7424/15692] intraday_1731.csv.gz  in=300,873,088 out=81,157,278 elapsed=125.0s

  [7425/15692] intraday_1732.csv.gz  in=300,885,191 out=81,157,278 elapsed=125.0s

  [7426/15692] intraday_1733.csv.gz  in=300,898,178 out=81,157,278 elapsed=125.0s

  [7427/15692] intraday_1734.csv.gz  in=300,908,268 out=81,157,278 elapsed=125.0s

  [7428/15692] intraday_1735.csv.gz  in=300,919,474 out=81,157,278 elapsed=125.0s

  [7429/15692] intraday_1736.csv.gz  in=300,931,074 out=81,157,278 elapsed=125.1s

  [7430/15692] intraday_1738.csv.gz  in=300,942,126 out=81,157,278 elapsed=125.1s

  [7431/15692] intraday_1737.csv.gz  in=300,957,855 out=81,157,278 elapsed=125.1s

  [7432/15692] intraday_1739.csv.gz  in=300,967,428 out=81,157,278 elapsed=125.1s

  [7433/15692] intraday_1740.csv.gz  in=300,978,245 out=81,157,278 elapsed=125.1s

  [7434/15692] intraday_1741.csv.gz  in=300,990,765 out=81,157,278 elapsed=125.1s

  [7435/15692] intraday_1743.csv.gz  in=301,004,358 out=81,157,278 elapsed=125.1s

  [7436/15692] intraday_1742.csv.gz  in=301,021,038 out=81,157,278 elapsed=125.1s

  [7437/15692] intraday_1744.csv.gz  in=301,033,836 out=81,157,278 elapsed=125.1s

  [7438/15692] intraday_1745.csv.gz  in=301,046,771 out=81,157,278 elapsed=125.1s

  [7439/15692] intraday_1747.csv.gz  in=301,060,407 out=81,157,278 elapsed=125.1s

  [7440/15692] intraday_1746.csv.gz  in=301,074,239 out=81,157,278 elapsed=125.1s

  [7441/15692] intraday_1748.csv.gz  in=301,088,231 out=81,157,278 elapsed=125.2s

  [7442/15692] intraday_1750.csv.gz  in=301,098,754 out=81,157,278 elapsed=125.2s

  [7443/15692] intraday_1749.csv.gz  in=301,118,067 out=81,157,278 elapsed=125.2s

  [7444/15692] intraday_1751.csv.gz  in=301,129,627 out=81,157,278 elapsed=125.2s

  [7445/15692] intraday_1752.csv.gz  in=301,141,060 out=81,157,278 elapsed=125.2s

  [7446/15692] intraday_1753.csv.gz  in=301,154,708 out=81,157,278 elapsed=125.2s

  [7447/15692] intraday_1755.csv.gz  in=301,167,261 out=81,157,278 elapsed=125.2s

  [7448/15692] intraday_1754.csv.gz  in=301,177,859 out=81,157,278 elapsed=125.2s

  [7449/15692] intraday_1756.csv.gz  in=301,189,717 out=81,157,278 elapsed=125.2s

  [7450/15692] intraday_1757.csv.gz  in=301,201,113 out=81,157,278 elapsed=125.2s

  [7451/15692] intraday_1759.csv.gz  in=301,212,337 out=81,157,278 elapsed=125.2s

  [7452/15692] intraday_1758.csv.gz  in=301,227,008 out=81,157,278 elapsed=125.2s

  [7453/15692] intraday_1760.csv.gz  in=301,244,215 out=81,157,278 elapsed=125.2s

  [7454/15692] intraday_1761.csv.gz  in=301,258,218 out=81,157,278 elapsed=125.2s

  [7455/15692] intraday_1762.csv.gz  in=301,271,717 out=81,157,278 elapsed=125.3s

  [7456/15692] intraday_1765.csv.gz  in=301,283,956 out=81,157,278 elapsed=125.3s

  [7457/15692] intraday_1764.csv.gz  in=301,297,809 out=81,157,278 elapsed=125.3s

  [7458/15692] intraday_1766.csv.gz  in=301,310,742 out=81,157,278 elapsed=125.3s

  [7459/15692] intraday_1763.csv.gz  in=301,345,344 out=81,157,278 elapsed=125.3s

  [7460/15692] intraday_1767.csv.gz  in=301,356,132 out=81,157,278 elapsed=125.3s

  [7461/15692] intraday_1768.csv.gz  in=301,369,447 out=81,157,278 elapsed=125.3s

  [7462/15692] intraday_1770.csv.gz  in=301,387,568 out=81,157,278 elapsed=125.3s

  [7463/15692] intraday_1769.csv.gz  in=301,399,897 out=81,157,278 elapsed=125.4s

  [7464/15692] intraday_1772.csv.gz  in=301,412,871 out=81,157,278 elapsed=125.4s

  [7465/15692] intraday_1771.csv.gz  in=301,425,283 out=81,157,278 elapsed=125.4s

  [7466/15692] intraday_1773.csv.gz  in=301,437,432 out=81,157,278 elapsed=125.4s

  [7467/15692] intraday_1774.csv.gz  in=301,450,419 out=81,157,278 elapsed=125.4s

  [7468/15692] intraday_1775.csv.gz  in=301,460,776 out=81,157,278 elapsed=125.4s

  [7469/15692] intraday_1776.csv.gz  in=301,477,589 out=81,157,278 elapsed=125.4s

  [7470/15692] intraday_1777.csv.gz  in=301,491,530 out=81,157,278 elapsed=125.4s

  [7471/15692] intraday_1778.csv.gz  in=301,506,950 out=81,157,278 elapsed=125.4s

  [7472/15692] intraday_1779.csv.gz  in=301,526,830 out=81,157,278 elapsed=125.4s

  [7473/15692] intraday_1781.csv.gz  in=301,540,285 out=81,157,278 elapsed=125.4s

  [7474/15692] intraday_1780.csv.gz  in=301,554,154 out=81,157,278 elapsed=125.4s

  [7475/15692] intraday_1782.csv.gz  in=301,572,665 out=81,157,278 elapsed=125.5s

  [7476/15692] intraday_1783.csv.gz  in=301,585,879 out=81,157,278 elapsed=125.5s

  [7477/15692] intraday_1785.csv.gz  in=301,599,175 out=81,157,278 elapsed=125.5s

  [7478/15692] intraday_1784.csv.gz  in=301,615,514 out=81,157,278 elapsed=125.5s

  [7479/15692] intraday_1786.csv.gz  in=301,627,634 out=81,157,278 elapsed=125.5s

  [7480/15692] intraday_1788.csv.gz  in=301,637,634 out=81,157,278 elapsed=125.5s

  [7481/15692] intraday_1789.csv.gz  in=301,650,628 out=81,157,278 elapsed=125.5s

  [7482/15692] intraday_1787.csv.gz  in=301,663,705 out=81,157,278 elapsed=125.5s

  [7483/15692] intraday_1790.csv.gz  in=301,674,430 out=81,157,278 elapsed=125.5s

  [7484/15692] intraday_1792.csv.gz  in=301,681,983 out=81,157,278 elapsed=125.5s

  [7485/15692] intraday_1791.csv.gz  in=301,693,589 out=81,157,278 elapsed=125.5s

  [7486/15692] intraday_1793.csv.gz  in=301,704,321 out=81,157,278 elapsed=125.5s

  [7487/15692] intraday_1794.csv.gz  in=301,710,705 out=81,157,278 elapsed=125.5s

  [7488/15692] intraday_1795.csv.gz  in=301,725,571 out=81,157,278 elapsed=125.6s

  [7489/15692] intraday_1797.csv.gz  in=301,737,750 out=81,157,278 elapsed=125.6s

  [7490/15692] intraday_1799.csv.gz  in=301,750,612 out=81,157,278 elapsed=125.6s

  [7491/15692] intraday_1796.csv.gz  in=301,763,853 out=81,157,278 elapsed=125.6s

  [7492/15692] intraday_1798.csv.gz  in=301,775,252 out=81,157,278 elapsed=125.6s

  [7493/15692] intraday_1800.csv.gz  in=301,789,865 out=81,157,278 elapsed=125.6s

  [7494/15692] intraday_1801.csv.gz  in=301,802,158 out=81,157,278 elapsed=125.6s

  [7495/15692] intraday_1802.csv.gz  in=301,814,339 out=81,157,278 elapsed=125.6s

  [7496/15692] intraday_1804.csv.gz  in=301,828,688 out=81,157,278 elapsed=125.6s

  [7497/15692] intraday_1803.csv.gz  in=301,842,289 out=81,157,278 elapsed=125.6s

  [7498/15692] intraday_1805.csv.gz  in=301,851,206 out=81,157,278 elapsed=125.6s

  [7499/15692] intraday_1809.csv.gz  in=301,861,421 out=81,157,278 elapsed=125.7s

  [7500/15692] intraday_1806.csv.gz  in=301,873,562 out=81,157,278 elapsed=125.7s

  [7501/15692] intraday_1808.csv.gz  in=301,884,070 out=81,157,278 elapsed=125.7s

  [7502/15692] intraday_1807.csv.gz  in=301,897,284 out=81,157,278 elapsed=125.7s

  [7503/15692] intraday_1810.csv.gz  in=301,909,568 out=81,157,278 elapsed=125.7s

  [7504/15692] intraday_1812.csv.gz  in=301,921,489 out=81,157,278 elapsed=125.7s

  [7505/15692] intraday_1811.csv.gz  in=301,933,993 out=81,157,278 elapsed=125.7s

  [7506/15692] intraday_1813.csv.gz  in=301,945,719 out=81,157,278 elapsed=125.7s

  [7507/15692] intraday_1814.csv.gz  in=301,957,537 out=81,157,278 elapsed=125.7s

  [7508/15692] intraday_1815.csv.gz  in=301,976,665 out=81,157,278 elapsed=125.7s

  [7509/15692] intraday_1817.csv.gz  in=301,990,490 out=81,157,278 elapsed=125.8s

  [7510/15692] intraday_1816.csv.gz  in=302,010,458 out=81,157,278 elapsed=125.8s

  [7511/15692] intraday_1818.csv.gz  in=302,023,123 out=81,157,278 elapsed=125.8s

  [7512/15692] intraday_1819.csv.gz  in=302,035,602 out=81,157,278 elapsed=125.8s

  [7513/15692] intraday_1820.csv.gz  in=302,044,445 out=81,157,278 elapsed=125.8s

  [7514/15692] intraday_1821.csv.gz  in=302,056,732 out=81,157,278 elapsed=125.8s

  [7515/15692] intraday_1822.csv.gz  in=302,068,409 out=81,157,278 elapsed=125.8s

  [7516/15692] intraday_1823.csv.gz  in=302,081,274 out=81,157,278 elapsed=125.8s

  [7517/15692] intraday_1827.csv.gz  in=302,095,757 out=81,157,278 elapsed=125.8s

  [7518/15692] intraday_1826.csv.gz  in=302,106,319 out=81,157,278 elapsed=125.8s

  [7519/15692] intraday_1825.csv.gz  in=302,118,657 out=81,157,278 elapsed=125.8s

  [7520/15692] intraday_1824.csv.gz  in=302,133,815 out=81,157,278 elapsed=125.9s

  [7521/15692] intraday_1829.csv.gz  in=302,144,755 out=81,157,278 elapsed=125.9s

  [7522/15692] intraday_1828.csv.gz  in=302,157,064 out=81,157,278 elapsed=125.9s

  [7523/15692] intraday_1830.csv.gz  in=302,169,301 out=81,157,278 elapsed=125.9s

  [7524/15692] intraday_1831.csv.gz  in=302,180,625 out=81,157,278 elapsed=125.9s

  [7525/15692] intraday_1832.csv.gz  in=302,192,306 out=81,157,278 elapsed=125.9s

  [7526/15692] intraday_1833.csv.gz  in=302,204,504 out=81,157,278 elapsed=125.9s

  [7527/15692] intraday_1835.csv.gz  in=302,218,717 out=81,157,278 elapsed=125.9s

  [7528/15692] intraday_1834.csv.gz  in=302,229,083 out=81,157,278 elapsed=125.9s

  [7529/15692] intraday_1836.csv.gz  in=302,241,384 out=81,157,278 elapsed=125.9s

  [7530/15692] intraday_1838.csv.gz  in=302,253,525 out=81,157,278 elapsed=126.0s

  [7531/15692] intraday_1837.csv.gz  in=302,266,869 out=81,157,278 elapsed=126.0s

  [7532/15692] intraday_1839.csv.gz  in=302,290,885 out=81,157,278 elapsed=126.0s

  [7533/15692] intraday_1840.csv.gz  in=302,303,820 out=81,157,278 elapsed=126.0s

  [7534/15692] intraday_1841.csv.gz  in=302,314,566 out=81,157,278 elapsed=126.0s

  [7535/15692] intraday_1842.csv.gz  in=302,326,969 out=81,157,278 elapsed=126.0s

  [7536/15692] intraday_1843.csv.gz  in=302,338,376 out=81,157,278 elapsed=126.0s

  [7537/15692] intraday_1844.csv.gz  in=302,352,604 out=81,157,278 elapsed=126.0s

  [7538/15692] intraday_1847.csv.gz  in=302,363,010 out=81,157,278 elapsed=126.0s

  [7539/15692] intraday_1845.csv.gz  in=302,378,207 out=81,157,278 elapsed=126.0s

  [7540/15692] intraday_1848.csv.gz  in=302,391,373 out=81,157,278 elapsed=126.0s

  [7541/15692] intraday_1846.csv.gz  in=302,405,956 out=81,157,278 elapsed=126.0s

  [7542/15692] intraday_1850.csv.gz  in=302,417,980 out=81,157,278 elapsed=126.1s

  [7543/15692] intraday_1849.csv.gz  in=302,430,805 out=81,157,278 elapsed=126.1s

  [7544/15692] intraday_1852.csv.gz  in=302,443,368 out=81,157,278 elapsed=126.1s

  [7545/15692] intraday_1851.csv.gz  in=302,453,898 out=81,157,278 elapsed=126.1s

  [7546/15692] intraday_1853.csv.gz  in=302,466,065 out=81,157,278 elapsed=126.1s

  [7547/15692] intraday_1855.csv.gz  in=302,477,677 out=81,157,278 elapsed=126.1s

  [7548/15692] intraday_1856.csv.gz  in=302,497,941 out=81,157,278 elapsed=126.1s

  [7549/15692] intraday_1854.csv.gz  in=302,522,984 out=81,157,278 elapsed=126.1s

  [7550/15692] intraday_1857.csv.gz  in=302,534,452 out=81,157,278 elapsed=126.2s

  [7551/15692] intraday_1860.csv.gz  in=302,548,847 out=81,157,278 elapsed=126.2s

  [7552/15692] intraday_1859.csv.gz  in=302,561,376 out=81,157,278 elapsed=126.2s

  [7553/15692] intraday_1858.csv.gz  in=302,574,185 out=81,157,278 elapsed=126.2s

  [7554/15692] intraday_1864.csv.gz  in=302,586,212 out=81,157,278 elapsed=126.2s

  [7555/15692] intraday_1861.csv.gz  in=302,599,187 out=81,157,278 elapsed=126.2s

  [7556/15692] intraday_1863.csv.gz  in=302,609,567 out=81,157,278 elapsed=126.2s

  [7557/15692] intraday_1862.csv.gz  in=302,621,571 out=81,157,278 elapsed=126.2s

  [7558/15692] intraday_1865.csv.gz  in=302,632,860 out=81,157,278 elapsed=126.2s

  [7559/15692] intraday_1867.csv.gz  in=302,642,708 out=81,157,278 elapsed=126.2s

  [7560/15692] intraday_1866.csv.gz  in=302,666,967 out=81,157,278 elapsed=126.3s

  [7561/15692] intraday_1869.csv.gz  in=302,677,669 out=81,157,278 elapsed=126.3s

  [7562/15692] intraday_1868.csv.gz  in=302,689,148 out=81,157,278 elapsed=126.3s

  [7563/15692] intraday_1870.csv.gz  in=302,702,302 out=81,157,278 elapsed=126.3s

  [7564/15692] intraday_1871.csv.gz  in=302,712,893 out=81,157,278 elapsed=126.3s

  [7565/15692] intraday_1872.csv.gz  in=302,726,079 out=81,157,278 elapsed=126.3s

  [7566/15692] intraday_1873.csv.gz  in=302,736,803 out=81,157,278 elapsed=126.3s

  [7567/15692] intraday_1874.csv.gz  in=302,748,102 out=81,157,278 elapsed=126.3s

  [7568/15692] intraday_1876.csv.gz  in=302,761,266 out=81,157,278 elapsed=126.3s

  [7569/15692] intraday_1877.csv.gz  in=302,773,129 out=81,157,278 elapsed=126.4s

  [7570/15692] intraday_1875.csv.gz  in=302,784,540 out=81,157,278 elapsed=126.4s

  [7571/15692] intraday_1878.csv.gz  in=302,796,196 out=81,157,278 elapsed=126.4s

  [7572/15692] intraday_1879.csv.gz  in=302,805,885 out=81,157,278 elapsed=126.4s

  [7573/15692] intraday_1881.csv.gz  in=302,817,784 out=81,157,278 elapsed=126.4s

  [7574/15692] intraday_1880.csv.gz  in=302,835,623 out=81,157,278 elapsed=126.4s

  [7575/15692] intraday_1883.csv.gz  in=302,847,340 out=81,157,278 elapsed=126.4s

  [7576/15692] intraday_1882.csv.gz  in=302,862,049 out=81,157,278 elapsed=126.4s

  [7577/15692] intraday_1884.csv.gz  in=302,875,924 out=81,157,278 elapsed=126.4s

  [7578/15692] intraday_1885.csv.gz  in=302,889,468 out=81,157,278 elapsed=126.4s

  [7579/15692] intraday_1887.csv.gz  in=302,902,215 out=81,157,278 elapsed=126.4s

  [7580/15692] intraday_1886.csv.gz  in=302,915,229 out=81,157,278 elapsed=126.4s

  [7581/15692] intraday_1889.csv.gz  in=302,926,551 out=81,157,278 elapsed=126.5s

  [7582/15692] intraday_1890.csv.gz  in=302,937,401 out=81,157,278 elapsed=126.5s

  [7583/15692] intraday_1888.csv.gz  in=302,949,645 out=81,157,278 elapsed=126.5s

  [7584/15692] intraday_1891.csv.gz  in=302,961,274 out=81,157,278 elapsed=126.5s

  [7585/15692] intraday_1893.csv.gz  in=302,972,517 out=81,157,278 elapsed=126.5s

  [7586/15692] intraday_1894.csv.gz  in=302,984,318 out=81,157,278 elapsed=126.5s

  [7587/15692] intraday_1892.csv.gz  in=302,996,841 out=81,157,278 elapsed=126.5s

  [7588/15692] intraday_1895.csv.gz  in=303,009,073 out=81,157,278 elapsed=126.5s

  [7589/15692] intraday_1896.csv.gz  in=303,020,942 out=81,157,278 elapsed=126.5s

  [7590/15692] intraday_1898.csv.gz  in=303,033,123 out=81,157,278 elapsed=126.5s

  [7591/15692] intraday_1897.csv.gz  in=303,045,470 out=81,157,278 elapsed=126.5s

  [7592/15692] intraday_1899.csv.gz  in=303,071,194 out=81,157,278 elapsed=126.6s

  [7593/15692] intraday_1900.csv.gz  in=303,084,826 out=81,157,278 elapsed=126.6s

  [7594/15692] intraday_1902.csv.gz  in=303,096,580 out=81,157,278 elapsed=126.6s

  [7595/15692] intraday_1901.csv.gz  in=303,111,410 out=81,157,278 elapsed=126.6s

  [7596/15692] intraday_1904.csv.gz  in=303,124,080 out=81,157,278 elapsed=126.6s

  [7597/15692] intraday_1903.csv.gz  in=303,147,447 out=81,157,278 elapsed=126.6s

  [7598/15692] intraday_1906.csv.gz  in=303,160,415 out=81,157,278 elapsed=126.6s

  [7599/15692] intraday_1905.csv.gz  in=303,180,663 out=81,157,278 elapsed=126.6s

  [7600/15692] intraday_1907.csv.gz  in=303,193,165 out=81,157,278 elapsed=126.6s

  [7601/15692] intraday_1908.csv.gz  in=303,206,485 out=81,157,278 elapsed=126.6s

  [7602/15692] intraday_1910.csv.gz  in=303,218,369 out=81,157,278 elapsed=126.7s

  [7603/15692] intraday_1911.csv.gz  in=303,231,513 out=81,157,278 elapsed=126.7s

  [7604/15692] intraday_1912.csv.gz  in=303,244,627 out=81,157,278 elapsed=126.7s

  [7605/15692] intraday_1909.csv.gz  in=303,261,640 out=81,157,278 elapsed=126.7s

  [7606/15692] intraday_1913.csv.gz  in=303,273,078 out=81,157,278 elapsed=126.7s

  [7607/15692] intraday_1914.csv.gz  in=303,283,604 out=81,157,278 elapsed=126.7s

  [7608/15692] intraday_1916.csv.gz  in=303,296,657 out=81,157,278 elapsed=126.7s

  [7609/15692] intraday_1915.csv.gz  in=303,310,561 out=81,157,278 elapsed=126.7s

  [7610/15692] intraday_1917.csv.gz  in=303,332,584 out=81,157,278 elapsed=126.7s

  [7611/15692] intraday_1918.csv.gz  in=303,345,035 out=81,157,278 elapsed=126.8s

  [7612/15692] intraday_1920.csv.gz  in=303,358,642 out=81,157,278 elapsed=126.8s

  [7613/15692] intraday_1919.csv.gz  in=303,374,222 out=81,157,278 elapsed=126.8s

  [7614/15692] intraday_1921.csv.gz  in=303,387,310 out=81,157,278 elapsed=126.8s

  [7615/15692] intraday_1922.csv.gz  in=303,407,085 out=81,157,278 elapsed=126.8s

  [7616/15692] intraday_1924.csv.gz  in=303,422,119 out=81,157,278 elapsed=126.8s

  [7617/15692] intraday_1923.csv.gz  in=303,437,430 out=81,157,278 elapsed=126.8s

  [7618/15692] intraday_1925.csv.gz  in=303,451,376 out=81,157,278 elapsed=126.8s

  [7619/15692] intraday_1926.csv.gz  in=303,466,243 out=81,157,278 elapsed=126.8s

  [7620/15692] intraday_1927.csv.gz  in=303,477,143 out=81,157,278 elapsed=126.8s

  [7621/15692] intraday_1928.csv.gz  in=303,488,166 out=81,157,278 elapsed=126.8s

  [7622/15692] intraday_1929.csv.gz  in=303,500,925 out=81,157,278 elapsed=126.8s

  [7623/15692] intraday_1931.csv.gz  in=303,510,337 out=81,157,278 elapsed=126.9s

  [7624/15692] intraday_1930.csv.gz  in=303,522,005 out=81,157,278 elapsed=126.9s

  [7625/15692] intraday_1932.csv.gz  in=303,530,982 out=81,157,278 elapsed=126.9s

  [7626/15692] intraday_1933.csv.gz  in=303,540,884 out=81,157,278 elapsed=126.9s

  [7627/15692] intraday_1934.csv.gz  in=303,545,475 out=81,157,278 elapsed=126.9s

  [7628/15692] intraday_1935.csv.gz  in=303,560,351 out=81,157,278 elapsed=126.9s

  [7629/15692] intraday_1937.csv.gz  in=303,572,390 out=81,157,278 elapsed=126.9s

  [7630/15692] intraday_1936.csv.gz  in=303,586,239 out=81,157,278 elapsed=126.9s

  [7631/15692] intraday_1938.csv.gz  in=303,597,825 out=81,157,278 elapsed=126.9s

  [7632/15692] intraday_1939.csv.gz  in=303,611,143 out=81,157,278 elapsed=126.9s

  [7633/15692] intraday_1942.csv.gz  in=303,623,329 out=81,157,278 elapsed=127.0s

  [7634/15692] intraday_1940.csv.gz  in=303,637,857 out=81,157,278 elapsed=127.0s

  [7635/15692] intraday_1941.csv.gz  in=303,650,196 out=81,157,278 elapsed=127.0s

  [7636/15692] intraday_1943.csv.gz  in=303,664,257 out=81,157,278 elapsed=127.0s

  [7637/15692] intraday_1945.csv.gz  in=303,673,202 out=81,157,278 elapsed=127.0s

  [7638/15692] intraday_1944.csv.gz  in=303,688,920 out=81,157,278 elapsed=127.0s

  [7639/15692] intraday_1947.csv.gz  in=303,702,638 out=81,157,278 elapsed=127.0s

  [7640/15692] intraday_1946.csv.gz  in=303,719,943 out=81,157,278 elapsed=127.0s

  [7641/15692] intraday_1948.csv.gz  in=303,735,343 out=81,157,278 elapsed=127.0s

  [7642/15692] intraday_1949.csv.gz  in=303,746,010 out=81,157,278 elapsed=127.0s

  [7643/15692] intraday_1952.csv.gz  in=303,758,504 out=81,157,278 elapsed=127.1s

  [7644/15692] intraday_1950.csv.gz  in=303,771,546 out=81,157,278 elapsed=127.1s

  [7645/15692] intraday_1951.csv.gz  in=303,790,324 out=81,157,278 elapsed=127.1s

  [7646/15692] intraday_1953.csv.gz  in=303,804,246 out=81,157,278 elapsed=127.1s

  [7647/15692] intraday_1954.csv.gz  in=303,816,582 out=81,157,278 elapsed=127.1s

  [7648/15692] intraday_1956.csv.gz  in=303,828,320 out=81,157,278 elapsed=127.1s

  [7649/15692] intraday_1955.csv.gz  in=303,841,691 out=81,157,278 elapsed=127.1s

  [7650/15692] intraday_1957.csv.gz  in=303,856,686 out=81,157,278 elapsed=127.1s

  [7651/15692] intraday_1960.csv.gz  in=303,867,323 out=81,157,278 elapsed=127.1s

  [7652/15692] intraday_1958.csv.gz  in=303,884,987 out=81,157,278 elapsed=127.1s

  [7653/15692] intraday_1959.csv.gz  in=303,897,277 out=81,157,278 elapsed=127.1s

  [7654/15692] intraday_1962.csv.gz  in=303,909,025 out=81,157,278 elapsed=127.2s

  [7655/15692] intraday_1964.csv.gz  in=303,923,706 out=81,157,278 elapsed=127.2s

  [7656/15692] intraday_1961.csv.gz  in=303,935,857 out=81,157,278 elapsed=127.2s

  [7657/15692] intraday_1963.csv.gz  in=303,948,711 out=81,157,278 elapsed=127.2s

  [7658/15692] intraday_1965.csv.gz  in=303,962,466 out=81,157,278 elapsed=127.2s

  [7659/15692] intraday_1966.csv.gz  in=303,973,701 out=81,157,278 elapsed=127.2s

  [7660/15692] intraday_1967.csv.gz  in=303,985,015 out=81,157,278 elapsed=127.2s

  [7661/15692] intraday_1968.csv.gz  in=303,998,437 out=81,157,278 elapsed=127.2s

  [7662/15692] intraday_1969.csv.gz  in=304,009,366 out=81,157,278 elapsed=127.2s

  [7663/15692] intraday_1970.csv.gz  in=304,022,326 out=81,157,278 elapsed=127.3s

  [7664/15692] intraday_1971.csv.gz  in=304,032,766 out=81,157,278 elapsed=127.3s

  [7665/15692] intraday_1973.csv.gz  in=304,046,377 out=81,157,278 elapsed=127.3s

  [7666/15692] intraday_1972.csv.gz  in=304,057,775 out=81,157,278 elapsed=127.3s

  [7667/15692] intraday_1974.csv.gz  in=304,068,653 out=81,157,278 elapsed=127.3s

  [7668/15692] intraday_1977.csv.gz  in=304,080,732 out=81,157,278 elapsed=127.3s

  [7669/15692] intraday_1976.csv.gz  in=304,093,462 out=81,157,278 elapsed=127.3s

  [7670/15692] intraday_1975.csv.gz  in=304,108,543 out=81,157,278 elapsed=127.3s

  [7671/15692] intraday_1978.csv.gz  in=304,121,439 out=81,157,278 elapsed=127.3s

  [7672/15692] intraday_1979.csv.gz  in=304,134,133 out=81,157,278 elapsed=127.3s

  [7673/15692] intraday_1980.csv.gz  in=304,147,097 out=81,157,278 elapsed=127.3s

  [7674/15692] intraday_1981.csv.gz  in=304,158,115 out=81,157,278 elapsed=127.3s

  [7675/15692] intraday_1982.csv.gz  in=304,190,831 out=81,157,278 elapsed=127.4s

  [7676/15692] intraday_1984.csv.gz  in=304,205,482 out=81,157,278 elapsed=127.4s

  [7677/15692] intraday_1983.csv.gz  in=304,217,960 out=81,157,278 elapsed=127.4s

  [7678/15692] intraday_1985.csv.gz  in=304,229,943 out=81,157,278 elapsed=127.4s

  [7679/15692] intraday_1986.csv.gz  in=304,242,487 out=81,157,278 elapsed=127.4s

  [7680/15692] intraday_1987.csv.gz  in=304,254,789 out=81,157,278 elapsed=127.4s

  [7681/15692] intraday_1989.csv.gz  in=304,267,235 out=81,157,278 elapsed=127.4s

  [7682/15692] intraday_1988.csv.gz  in=304,280,528 out=81,157,278 elapsed=127.4s

  [7683/15692] intraday_1991.csv.gz  in=304,291,569 out=81,157,278 elapsed=127.4s

  [7684/15692] intraday_1992.csv.gz  in=304,304,627 out=81,157,278 elapsed=127.4s

  [7685/15692] intraday_1990.csv.gz  in=304,317,080 out=81,157,278 elapsed=127.4s

  [7686/15692] intraday_1994.csv.gz  in=304,329,495 out=81,157,278 elapsed=127.4s

  [7687/15692] intraday_1993.csv.gz  in=304,342,527 out=81,157,278 elapsed=127.5s

  [7688/15692] intraday_1996.csv.gz  in=304,353,254 out=81,157,278 elapsed=127.5s

  [7689/15692] intraday_1997.csv.gz  in=304,363,320 out=81,157,278 elapsed=127.5s

  [7690/15692] intraday_1995.csv.gz  in=304,374,759 out=81,157,278 elapsed=127.5s

  [7691/15692] intraday_1998.csv.gz  in=304,388,473 out=81,157,278 elapsed=127.5s

  [7692/15692] intraday_1999.csv.gz  in=304,400,208 out=81,157,278 elapsed=127.5s

  [7693/15692] intraday_2001.csv.gz  in=304,413,856 out=81,157,278 elapsed=127.5s

  [7694/15692] intraday_2003.csv.gz  in=304,423,754 out=81,157,278 elapsed=127.5s

  [7695/15692] intraday_2000.csv.gz  in=304,437,431 out=81,157,278 elapsed=127.5s

  [7696/15692] intraday_2002.csv.gz  in=304,454,343 out=81,157,278 elapsed=127.6s

  [7697/15692] intraday_2005.csv.gz  in=304,465,832 out=81,157,278 elapsed=127.6s

  [7698/15692] intraday_2006.csv.gz  in=304,478,691 out=81,157,278 elapsed=127.6s

  [7699/15692] intraday_2004.csv.gz  in=304,491,659 out=81,157,278 elapsed=127.6s

  [7700/15692] intraday_2008.csv.gz  in=304,504,001 out=81,157,278 elapsed=127.6s

  [7701/15692] intraday_2009.csv.gz  in=304,514,878 out=81,157,278 elapsed=127.6s

  [7702/15692] intraday_2007.csv.gz  in=304,524,759 out=81,157,278 elapsed=127.6s

  [7703/15692] intraday_2010.csv.gz  in=304,537,018 out=81,157,278 elapsed=127.6s

  [7704/15692] intraday_2011.csv.gz  in=304,547,980 out=81,157,278 elapsed=127.6s

  [7705/15692] intraday_2013.csv.gz  in=304,559,397 out=81,157,278 elapsed=127.6s

  [7706/15692] intraday_2012.csv.gz  in=304,572,937 out=81,157,278 elapsed=127.6s

  [7707/15692] intraday_2014.csv.gz  in=304,583,955 out=81,157,278 elapsed=127.7s

  [7708/15692] intraday_2015.csv.gz  in=304,595,090 out=81,157,278 elapsed=127.7s

  [7709/15692] intraday_2017.csv.gz  in=304,606,480 out=81,157,278 elapsed=127.7s

  [7710/15692] intraday_2019.csv.gz  in=304,617,487 out=81,157,278 elapsed=127.7s

  [7711/15692] intraday_2018.csv.gz  in=304,629,453 out=81,157,278 elapsed=127.7s

  [7712/15692] intraday_2016.csv.gz  in=304,644,460 out=81,157,278 elapsed=127.7s

  [7713/15692] intraday_2020.csv.gz  in=304,656,277 out=81,157,278 elapsed=127.7s

  [7714/15692] intraday_2022.csv.gz  in=304,671,806 out=81,157,278 elapsed=127.7s

  [7715/15692] intraday_2021.csv.gz  in=304,684,113 out=81,157,278 elapsed=127.7s

  [7716/15692] intraday_2023.csv.gz  in=304,695,197 out=81,157,278 elapsed=127.7s

  [7717/15692] intraday_2024.csv.gz  in=304,709,735 out=81,157,278 elapsed=127.7s

  [7718/15692] intraday_2026.csv.gz  in=304,723,883 out=81,157,278 elapsed=127.8s

  [7719/15692] intraday_2028.csv.gz  in=304,737,401 out=81,157,278 elapsed=127.8s

  [7720/15692] intraday_2025.csv.gz  in=304,752,462 out=81,157,278 elapsed=127.8s

  [7721/15692] intraday_2027.csv.gz  in=304,766,687 out=81,157,278 elapsed=127.8s

  [7722/15692] intraday_2031.csv.gz  in=304,777,410 out=81,157,278 elapsed=127.8s

  [7723/15692] intraday_2030.csv.gz  in=304,789,681 out=81,157,278 elapsed=127.8s

  [7724/15692] intraday_2029.csv.gz  in=304,801,726 out=81,157,278 elapsed=127.8s

  [7725/15692] intraday_2032.csv.gz  in=304,813,566 out=81,157,278 elapsed=127.8s

  [7726/15692] intraday_2033.csv.gz  in=304,825,079 out=81,157,278 elapsed=127.8s

  [7727/15692] intraday_2035.csv.gz  in=304,836,015 out=81,157,278 elapsed=127.9s

  [7728/15692] intraday_2034.csv.gz  in=304,850,125 out=81,157,278 elapsed=127.9s

  [7729/15692] intraday_2036.csv.gz  in=304,863,008 out=81,157,278 elapsed=127.9s

  [7730/15692] intraday_2037.csv.gz  in=304,875,398 out=81,157,278 elapsed=127.9s

  [7731/15692] intraday_2038.csv.gz  in=304,888,788 out=81,157,278 elapsed=127.9s

  [7732/15692] intraday_2039.csv.gz  in=304,907,009 out=81,157,278 elapsed=127.9s

  [7733/15692] intraday_2040.csv.gz  in=304,920,976 out=81,157,278 elapsed=127.9s

  [7734/15692] intraday_2042.csv.gz  in=304,934,373 out=81,157,278 elapsed=127.9s

  [7735/15692] intraday_2041.csv.gz  in=304,949,207 out=81,157,278 elapsed=127.9s

  [7736/15692] intraday_2043.csv.gz  in=304,961,631 out=81,157,278 elapsed=127.9s

  [7737/15692] intraday_2045.csv.gz  in=304,973,411 out=81,157,278 elapsed=128.0s

  [7738/15692] intraday_2044.csv.gz  in=304,986,783 out=81,157,278 elapsed=128.0s

  [7739/15692] intraday_2047.csv.gz  in=304,999,335 out=81,157,278 elapsed=128.0s

  [7740/15692] intraday_2046.csv.gz  in=305,012,293 out=81,157,278 elapsed=128.0s

  [7741/15692] intraday_2049.csv.gz  in=305,028,043 out=81,157,278 elapsed=128.0s

  [7742/15692] intraday_2048.csv.gz  in=305,043,119 out=81,157,278 elapsed=128.0s

  [7743/15692] intraday_2050.csv.gz  in=305,055,937 out=81,157,278 elapsed=128.0s

  [7744/15692] intraday_2051.csv.gz  in=305,068,483 out=81,157,278 elapsed=128.0s

  [7745/15692] intraday_2054.csv.gz  in=305,080,478 out=81,157,278 elapsed=128.0s

  [7746/15692] intraday_2052.csv.gz  in=305,101,455 out=81,157,278 elapsed=128.1s

  [7747/15692] intraday_2055.csv.gz  in=305,113,116 out=81,157,278 elapsed=128.1s

  [7748/15692] intraday_2053.csv.gz  in=305,124,147 out=81,157,278 elapsed=128.1s

  [7749/15692] intraday_2056.csv.gz  in=305,139,460 out=81,157,278 elapsed=128.1s

  [7750/15692] intraday_2058.csv.gz  in=305,154,776 out=81,157,278 elapsed=128.1s

  [7751/15692] intraday_2059.csv.gz  in=305,167,173 out=81,157,278 elapsed=128.1s

  [7752/15692] intraday_2057.csv.gz  in=305,180,230 out=81,157,278 elapsed=128.1s

  [7753/15692] intraday_2060.csv.gz  in=305,193,597 out=81,157,278 elapsed=128.1s

  [7754/15692] intraday_2062.csv.gz  in=305,206,108 out=81,157,278 elapsed=128.1s

  [7755/15692] intraday_2061.csv.gz  in=305,220,522 out=81,157,278 elapsed=128.1s

  [7756/15692] intraday_2063.csv.gz  in=305,235,043 out=81,157,278 elapsed=128.1s

  [7757/15692] intraday_2065.csv.gz  in=305,250,230 out=81,157,278 elapsed=128.2s

  [7758/15692] intraday_2064.csv.gz  in=305,265,262 out=81,157,278 elapsed=128.2s

  [7759/15692] intraday_2067.csv.gz  in=305,277,234 out=81,157,278 elapsed=128.2s

  [7760/15692] intraday_2066.csv.gz  in=305,290,703 out=81,157,278 elapsed=128.2s

  [7761/15692] intraday_2068.csv.gz  in=305,306,865 out=81,157,278 elapsed=128.2s

  [7762/15692] intraday_2070.csv.gz  in=305,319,243 out=81,157,278 elapsed=128.2s

  [7763/15692] intraday_2069.csv.gz  in=305,332,381 out=81,157,278 elapsed=128.2s

  [7764/15692] intraday_2071.csv.gz  in=305,347,761 out=81,157,278 elapsed=128.2s

  [7765/15692] intraday_2072.csv.gz  in=305,355,388 out=81,157,278 elapsed=128.2s

  [7766/15692] intraday_2074.csv.gz  in=305,361,505 out=81,157,278 elapsed=128.3s

  [7767/15692] intraday_2073.csv.gz  in=305,372,470 out=81,157,278 elapsed=128.3s

  [7768/15692] intraday_2076.csv.gz  in=305,387,026 out=81,157,278 elapsed=128.3s

  [7769/15692] intraday_2075.csv.gz  in=305,401,818 out=81,157,278 elapsed=128.3s

  [7770/15692] intraday_2077.csv.gz  in=305,413,800 out=81,157,278 elapsed=128.3s

  [7771/15692] intraday_2078.csv.gz  in=305,424,658 out=81,157,278 elapsed=128.3s

  [7772/15692] intraday_2079.csv.gz  in=305,438,735 out=81,157,278 elapsed=128.3s

  [7773/15692] intraday_2081.csv.gz  in=305,450,978 out=81,157,278 elapsed=128.3s

  [7774/15692] intraday_2080.csv.gz  in=305,465,373 out=81,157,278 elapsed=128.3s

  [7775/15692] intraday_2083.csv.gz  in=305,479,793 out=81,157,278 elapsed=128.3s

  [7776/15692] intraday_2082.csv.gz  in=305,492,644 out=81,157,278 elapsed=128.4s

  [7777/15692] intraday_2084.csv.gz  in=305,507,960 out=81,157,278 elapsed=128.4s

  [7778/15692] intraday_2086.csv.gz  in=305,519,751 out=81,157,278 elapsed=128.4s

  [7779/15692] intraday_2087.csv.gz  in=305,533,487 out=81,157,278 elapsed=128.4s

  [7780/15692] intraday_2085.csv.gz  in=305,543,405 out=81,157,278 elapsed=128.4s

  [7781/15692] intraday_2088.csv.gz  in=305,554,674 out=81,157,278 elapsed=128.4s

  [7782/15692] intraday_2091.csv.gz  in=305,567,245 out=81,157,278 elapsed=128.4s

  [7783/15692] intraday_2089.csv.gz  in=305,578,491 out=81,157,278 elapsed=128.4s

  [7784/15692] intraday_2090.csv.gz  in=305,591,097 out=81,157,278 elapsed=128.4s

  [7785/15692] intraday_2092.csv.gz  in=305,603,828 out=81,157,278 elapsed=128.4s

  [7786/15692] intraday_2093.csv.gz  in=305,616,008 out=81,157,278 elapsed=128.5s

  [7787/15692] intraday_2094.csv.gz  in=305,628,233 out=81,157,278 elapsed=128.5s

  [7788/15692] intraday_2095.csv.gz  in=305,641,735 out=81,157,278 elapsed=128.5s

  [7789/15692] intraday_2096.csv.gz  in=305,654,060 out=81,157,278 elapsed=128.5s

  [7790/15692] intraday_2097.csv.gz  in=305,666,446 out=81,157,278 elapsed=128.5s

  [7791/15692] intraday_2098.csv.gz  in=305,678,952 out=81,157,278 elapsed=128.5s

  [7792/15692] intraday_2100.csv.gz  in=305,688,208 out=81,157,278 elapsed=128.5s

  [7793/15692] intraday_2099.csv.gz  in=305,700,699 out=81,157,278 elapsed=128.5s

  [7794/15692] intraday_2101.csv.gz  in=305,712,928 out=81,157,278 elapsed=128.5s

  [7795/15692] intraday_2102.csv.gz  in=305,725,475 out=81,157,278 elapsed=128.5s

  [7796/15692] intraday_2103.csv.gz  in=305,738,996 out=81,157,278 elapsed=128.6s

  [7797/15692] intraday_2105.csv.gz  in=305,751,333 out=81,157,278 elapsed=128.6s

  [7798/15692] intraday_2106.csv.gz  in=305,763,007 out=81,157,278 elapsed=128.6s

  [7799/15692] intraday_2104.csv.gz  in=305,777,979 out=81,157,278 elapsed=128.6s

  [7800/15692] intraday_2107.csv.gz  in=305,790,275 out=81,157,278 elapsed=128.6s

  [7801/15692] intraday_2108.csv.gz  in=305,803,142 out=81,157,278 elapsed=128.6s

  [7802/15692] intraday_2110.csv.gz  in=305,816,160 out=81,157,278 elapsed=128.6s

  [7803/15692] intraday_2109.csv.gz  in=305,827,277 out=81,157,278 elapsed=128.6s

  [7804/15692] intraday_2111.csv.gz  in=305,838,642 out=81,157,278 elapsed=128.6s

  [7805/15692] intraday_2112.csv.gz  in=305,849,829 out=81,157,278 elapsed=128.7s

  [7806/15692] intraday_2113.csv.gz  in=305,862,602 out=81,157,278 elapsed=128.7s

  [7807/15692] intraday_2114.csv.gz  in=305,874,551 out=81,157,278 elapsed=128.7s

  [7808/15692] intraday_2115.csv.gz  in=305,889,292 out=81,157,278 elapsed=128.7s

  [7809/15692] intraday_2118.csv.gz  in=305,902,068 out=81,157,278 elapsed=128.7s

  [7810/15692] intraday_2117.csv.gz  in=305,916,244 out=81,157,278 elapsed=128.7s

  [7811/15692] intraday_2119.csv.gz  in=305,929,017 out=81,157,278 elapsed=128.7s

  [7812/15692] intraday_2116.csv.gz  in=305,941,088 out=81,157,278 elapsed=128.7s

  [7813/15692] intraday_2121.csv.gz  in=305,952,191 out=81,157,278 elapsed=128.7s

  [7814/15692] intraday_2122.csv.gz  in=305,964,591 out=81,157,278 elapsed=128.7s

  [7815/15692] intraday_2120.csv.gz  in=305,977,619 out=81,157,278 elapsed=128.7s

  [7816/15692] intraday_2123.csv.gz  in=305,989,961 out=81,157,278 elapsed=128.8s

  [7817/15692] intraday_2124.csv.gz  in=306,000,520 out=81,157,278 elapsed=128.8s

  [7818/15692] intraday_2127.csv.gz  in=306,011,554 out=81,157,278 elapsed=128.8s

  [7819/15692] intraday_2125.csv.gz  in=306,025,064 out=81,157,278 elapsed=128.8s

  [7820/15692] intraday_2126.csv.gz  in=306,037,167 out=81,157,278 elapsed=128.8s

  [7821/15692] intraday_2129.csv.gz  in=306,051,127 out=81,157,278 elapsed=128.8s

  [7822/15692] intraday_2130.csv.gz  in=306,062,936 out=81,157,278 elapsed=128.8s

  [7823/15692] intraday_2131.csv.gz  in=306,074,618 out=81,157,278 elapsed=128.8s

  [7824/15692] intraday_2128.csv.gz  in=306,087,068 out=81,157,278 elapsed=128.8s

  [7825/15692] intraday_2132.csv.gz  in=306,101,098 out=81,157,278 elapsed=128.8s

  [7826/15692] intraday_2135.csv.gz  in=306,113,649 out=81,157,278 elapsed=128.9s

  [7827/15692] intraday_2134.csv.gz  in=306,126,506 out=81,157,278 elapsed=128.9s

  [7828/15692] intraday_2133.csv.gz  in=306,138,286 out=81,157,278 elapsed=128.9s

  [7829/15692] intraday_2136.csv.gz  in=306,149,149 out=81,157,278 elapsed=128.9s

  [7830/15692] intraday_2139.csv.gz  in=306,162,962 out=81,157,278 elapsed=128.9s

  [7831/15692] intraday_2137.csv.gz  in=306,173,577 out=81,157,278 elapsed=128.9s

  [7832/15692] intraday_2138.csv.gz  in=306,186,942 out=81,157,278 elapsed=128.9s

  [7833/15692] intraday_2141.csv.gz  in=306,201,341 out=81,157,278 elapsed=128.9s

  [7834/15692] intraday_2140.csv.gz  in=306,216,113 out=81,157,278 elapsed=129.0s

  [7835/15692] intraday_2142.csv.gz  in=306,226,721 out=81,157,278 elapsed=129.0s

  [7836/15692] intraday_2144.csv.gz  in=306,238,210 out=81,157,278 elapsed=129.0s

  [7837/15692] intraday_2143.csv.gz  in=306,250,101 out=81,157,278 elapsed=129.0s

  [7838/15692] intraday_2146.csv.gz  in=306,264,094 out=81,157,278 elapsed=129.0s

  [7839/15692] intraday_2145.csv.gz  in=306,276,523 out=81,157,278 elapsed=129.0s

  [7840/15692] intraday_2148.csv.gz  in=306,287,931 out=81,157,278 elapsed=129.0s

  [7841/15692] intraday_2147.csv.gz  in=306,299,355 out=81,157,278 elapsed=129.0s

  [7842/15692] intraday_2149.csv.gz  in=306,311,202 out=81,157,278 elapsed=129.0s

  [7843/15692] intraday_2150.csv.gz  in=306,324,094 out=81,157,278 elapsed=129.0s

  [7844/15692] intraday_2151.csv.gz  in=306,335,487 out=81,157,278 elapsed=129.0s

  [7845/15692] intraday_2152.csv.gz  in=306,348,495 out=81,157,278 elapsed=129.0s

  [7846/15692] intraday_2153.csv.gz  in=306,359,400 out=81,157,278 elapsed=129.1s

  [7847/15692] intraday_2154.csv.gz  in=306,371,102 out=81,157,278 elapsed=129.1s

  [7848/15692] intraday_2155.csv.gz  in=306,383,262 out=81,157,278 elapsed=129.1s

  [7849/15692] intraday_2156.csv.gz  in=306,399,052 out=81,157,278 elapsed=129.1s

  [7850/15692] intraday_2157.csv.gz  in=306,409,659 out=81,157,278 elapsed=129.1s

  [7851/15692] intraday_2159.csv.gz  in=306,419,450 out=81,157,278 elapsed=129.1s

  [7852/15692] intraday_2158.csv.gz  in=306,431,549 out=81,157,278 elapsed=129.1s

  [7853/15692] intraday_2160.csv.gz  in=306,445,935 out=81,157,278 elapsed=129.1s

  [7854/15692] intraday_2164.csv.gz  in=306,460,685 out=81,157,278 elapsed=129.1s

  [7855/15692] intraday_2161.csv.gz  in=306,472,362 out=81,157,278 elapsed=129.1s

  [7856/15692] intraday_2163.csv.gz  in=306,484,656 out=81,157,278 elapsed=129.1s

  [7857/15692] intraday_2162.csv.gz  in=306,500,708 out=81,157,278 elapsed=129.2s

  [7858/15692] intraday_2165.csv.gz  in=306,514,137 out=81,157,278 elapsed=129.2s

  [7859/15692] intraday_2167.csv.gz  in=306,527,776 out=81,157,278 elapsed=129.2s

  [7860/15692] intraday_2166.csv.gz  in=306,542,386 out=81,157,278 elapsed=129.2s

  [7861/15692] intraday_2169.csv.gz  in=306,554,736 out=81,157,278 elapsed=129.2s

  [7862/15692] intraday_2168.csv.gz  in=306,567,167 out=81,157,278 elapsed=129.2s

  [7863/15692] intraday_2171.csv.gz  in=306,580,067 out=81,157,278 elapsed=129.2s

  [7864/15692] intraday_2170.csv.gz  in=306,592,117 out=81,157,278 elapsed=129.2s

  [7865/15692] intraday_2172.csv.gz  in=306,604,741 out=81,157,278 elapsed=129.2s

  [7866/15692] intraday_2173.csv.gz  in=306,616,171 out=81,157,278 elapsed=129.2s

  [7867/15692] intraday_2174.csv.gz  in=306,631,029 out=81,157,278 elapsed=129.2s

  [7868/15692] intraday_2176.csv.gz  in=306,642,617 out=81,157,278 elapsed=129.3s

  [7869/15692] intraday_2177.csv.gz  in=306,658,038 out=81,157,278 elapsed=129.3s

  [7870/15692] intraday_2175.csv.gz  in=306,670,318 out=81,157,278 elapsed=129.3s

  [7871/15692] intraday_2178.csv.gz  in=306,680,643 out=81,157,278 elapsed=129.3s

  [7872/15692] intraday_2179.csv.gz  in=306,693,649 out=81,157,278 elapsed=129.3s

  [7873/15692] intraday_2181.csv.gz  in=306,708,627 out=81,157,278 elapsed=129.3s

  [7874/15692] intraday_2180.csv.gz  in=306,723,023 out=81,157,278 elapsed=129.3s

  [7875/15692] intraday_2182.csv.gz  in=306,735,921 out=81,157,278 elapsed=129.3s

  [7876/15692] intraday_2183.csv.gz  in=306,749,442 out=81,157,278 elapsed=129.3s

  [7877/15692] intraday_2186.csv.gz  in=306,761,587 out=81,157,278 elapsed=129.3s

  [7878/15692] intraday_2184.csv.gz  in=306,773,580 out=81,157,278 elapsed=129.4s

  [7879/15692] intraday_2185.csv.gz  in=306,786,654 out=81,157,278 elapsed=129.4s

  [7880/15692] intraday_2188.csv.gz  in=306,798,488 out=81,157,278 elapsed=129.4s

  [7881/15692] intraday_2187.csv.gz  in=306,812,705 out=81,157,278 elapsed=129.4s

  [7882/15692] intraday_2189.csv.gz  in=306,829,347 out=81,157,278 elapsed=129.4s

  [7883/15692] intraday_2190.csv.gz  in=306,841,769 out=81,157,278 elapsed=129.4s

  [7884/15692] intraday_2191.csv.gz  in=306,856,245 out=81,157,278 elapsed=129.4s

  [7885/15692] intraday_2192.csv.gz  in=306,868,369 out=81,157,278 elapsed=129.4s

  [7886/15692] intraday_2193.csv.gz  in=306,881,047 out=81,157,278 elapsed=129.4s

  [7887/15692] intraday_2194.csv.gz  in=306,891,943 out=81,157,278 elapsed=129.4s

  [7888/15692] intraday_2196.csv.gz  in=306,905,216 out=81,157,278 elapsed=129.4s

  [7889/15692] intraday_2195.csv.gz  in=306,919,905 out=81,157,278 elapsed=129.5s

  [7890/15692] intraday_2197.csv.gz  in=306,935,477 out=81,157,278 elapsed=129.5s

  [7891/15692] intraday_2198.csv.gz  in=306,947,737 out=81,157,278 elapsed=129.5s

  [7892/15692] intraday_2199.csv.gz  in=306,962,573 out=81,157,278 elapsed=129.5s

  [7893/15692] intraday_2201.csv.gz  in=306,975,982 out=81,157,278 elapsed=129.5s

  [7894/15692] intraday_2200.csv.gz  in=306,989,232 out=81,157,278 elapsed=129.5s

  [7895/15692] intraday_2202.csv.gz  in=307,003,598 out=81,157,278 elapsed=129.5s

  [7896/15692] intraday_2203.csv.gz  in=307,019,137 out=81,157,278 elapsed=129.5s

  [7897/15692] intraday_2204.csv.gz  in=307,033,400 out=81,157,278 elapsed=129.5s

  [7898/15692] intraday_2205.csv.gz  in=307,047,539 out=81,157,278 elapsed=129.5s

  [7899/15692] intraday_2206.csv.gz  in=307,061,472 out=81,157,278 elapsed=129.5s

  [7900/15692] intraday_2207.csv.gz  in=307,073,143 out=81,157,278 elapsed=129.6s

  [7901/15692] intraday_2209.csv.gz  in=307,083,730 out=81,157,278 elapsed=129.6s

  [7902/15692] intraday_2210.csv.gz  in=307,098,425 out=81,157,278 elapsed=129.6s

  [7903/15692] intraday_2208.csv.gz  in=307,111,123 out=81,157,278 elapsed=129.6s

  [7904/15692] intraday_2212.csv.gz  in=307,120,708 out=81,157,278 elapsed=129.6s

  [7905/15692] intraday_2211.csv.gz  in=307,128,841 out=81,157,278 elapsed=129.6s

  [7906/15692] intraday_2213.csv.gz  in=307,138,809 out=81,157,278 elapsed=129.6s

  [7907/15692] intraday_2214.csv.gz  in=307,154,086 out=81,157,278 elapsed=129.6s

  [7908/15692] intraday_2215.csv.gz  in=307,167,932 out=81,157,278 elapsed=129.6s

  [7909/15692] intraday_2216.csv.gz  in=307,180,205 out=81,157,278 elapsed=129.6s

  [7910/15692] intraday_2218.csv.gz  in=307,194,011 out=81,157,278 elapsed=129.7s

  [7911/15692] intraday_2217.csv.gz  in=307,205,149 out=81,157,278 elapsed=129.7s

  [7912/15692] intraday_2220.csv.gz  in=307,217,881 out=81,157,278 elapsed=129.7s

  [7913/15692] intraday_2219.csv.gz  in=307,232,192 out=81,157,278 elapsed=129.7s

  [7914/15692] intraday_2221.csv.gz  in=307,244,973 out=81,157,278 elapsed=129.7s

  [7915/15692] intraday_2222.csv.gz  in=307,259,286 out=81,157,278 elapsed=129.7s

  [7916/15692] intraday_2225.csv.gz  in=307,271,040 out=81,157,278 elapsed=129.7s

  [7917/15692] intraday_2223.csv.gz  in=307,286,040 out=81,157,278 elapsed=129.7s

  [7918/15692] intraday_2224.csv.gz  in=307,295,587 out=81,157,278 elapsed=129.7s

  [7919/15692] intraday_2226.csv.gz  in=307,309,838 out=81,157,278 elapsed=129.8s

  [7920/15692] intraday_2227.csv.gz  in=307,327,475 out=81,157,278 elapsed=129.8s

  [7921/15692] intraday_2229.csv.gz  in=307,340,097 out=81,157,278 elapsed=129.8s

  [7922/15692] intraday_2228.csv.gz  in=307,351,972 out=81,157,278 elapsed=129.8s

  [7923/15692] intraday_2230.csv.gz  in=307,365,320 out=81,157,278 elapsed=129.8s

  [7924/15692] intraday_2233.csv.gz  in=307,377,794 out=81,157,278 elapsed=129.8s

  [7925/15692] intraday_2231.csv.gz  in=307,390,378 out=81,157,278 elapsed=129.8s

  [7926/15692] intraday_2232.csv.gz  in=307,410,355 out=81,157,278 elapsed=129.8s

  [7927/15692] intraday_2234.csv.gz  in=307,423,642 out=81,157,278 elapsed=129.8s

  [7928/15692] intraday_2235.csv.gz  in=307,436,239 out=81,157,278 elapsed=129.9s

  [7929/15692] intraday_2236.csv.gz  in=307,448,920 out=81,157,278 elapsed=129.9s

  [7930/15692] intraday_2237.csv.gz  in=307,462,266 out=81,157,278 elapsed=129.9s

  [7931/15692] intraday_2238.csv.gz  in=307,474,925 out=81,157,278 elapsed=129.9s

  [7932/15692] intraday_2239.csv.gz  in=307,484,013 out=81,157,278 elapsed=129.9s

  [7933/15692] intraday_2240.csv.gz  in=307,497,023 out=81,157,278 elapsed=129.9s

  [7934/15692] intraday_2242.csv.gz  in=307,508,988 out=81,157,278 elapsed=129.9s

  [7935/15692] intraday_2241.csv.gz  in=307,526,092 out=81,157,278 elapsed=129.9s

  [7936/15692] intraday_2243.csv.gz  in=307,540,639 out=81,157,278 elapsed=129.9s

  [7937/15692] intraday_2244.csv.gz  in=307,555,224 out=81,157,278 elapsed=129.9s

  [7938/15692] intraday_2245.csv.gz  in=307,567,558 out=81,157,278 elapsed=130.0s

  [7939/15692] intraday_2246.csv.gz  in=307,580,565 out=81,157,278 elapsed=130.0s

  [7940/15692] intraday_2248.csv.gz  in=307,591,736 out=81,157,278 elapsed=130.0s

  [7941/15692] intraday_2247.csv.gz  in=307,604,969 out=81,157,278 elapsed=130.0s

  [7942/15692] intraday_2250.csv.gz  in=307,616,549 out=81,157,278 elapsed=130.0s

  [7943/15692] intraday_2249.csv.gz  in=307,629,709 out=81,157,278 elapsed=130.0s

  [7944/15692] intraday_2251.csv.gz  in=307,640,809 out=81,157,278 elapsed=130.0s

  [7945/15692] intraday_2252.csv.gz  in=307,655,937 out=81,157,278 elapsed=130.0s

  [7946/15692] intraday_2253.csv.gz  in=307,666,609 out=81,157,278 elapsed=130.0s

  [7947/15692] intraday_2254.csv.gz  in=307,681,216 out=81,157,278 elapsed=130.0s

  [7948/15692] intraday_2255.csv.gz  in=307,694,017 out=81,157,278 elapsed=130.0s

  [7949/15692] intraday_2256.csv.gz  in=307,708,062 out=81,157,278 elapsed=130.1s

  [7950/15692] intraday_2257.csv.gz  in=307,720,678 out=81,157,278 elapsed=130.1s

  [7951/15692] intraday_2259.csv.gz  in=307,734,070 out=81,157,278 elapsed=130.1s

  [7952/15692] intraday_2258.csv.gz  in=307,746,527 out=81,157,278 elapsed=130.1s

  [7953/15692] intraday_2260.csv.gz  in=307,757,634 out=81,157,278 elapsed=130.1s

  [7954/15692] intraday_2263.csv.gz  in=307,768,436 out=81,157,278 elapsed=130.1s

  [7955/15692] intraday_2261.csv.gz  in=307,781,101 out=81,157,278 elapsed=130.1s

  [7956/15692] intraday_2262.csv.gz  in=307,797,645 out=81,157,278 elapsed=130.1s

  [7957/15692] intraday_2264.csv.gz  in=307,810,248 out=81,157,278 elapsed=130.1s

  [7958/15692] intraday_2265.csv.gz  in=307,822,126 out=81,157,278 elapsed=130.2s

  [7959/15692] intraday_2266.csv.gz  in=307,833,229 out=81,157,278 elapsed=130.2s

  [7960/15692] intraday_2267.csv.gz  in=307,846,544 out=81,157,278 elapsed=130.2s

  [7961/15692] intraday_2270.csv.gz  in=307,857,744 out=81,157,278 elapsed=130.2s

  [7962/15692] intraday_2269.csv.gz  in=307,869,008 out=81,157,278 elapsed=130.2s

  [7963/15692] intraday_2268.csv.gz  in=307,883,083 out=81,157,278 elapsed=130.2s

  [7964/15692] intraday_2271.csv.gz  in=307,896,264 out=81,157,278 elapsed=130.2s

  [7965/15692] intraday_2275.csv.gz  in=307,908,055 out=81,157,278 elapsed=130.2s

  [7966/15692] intraday_2274.csv.gz  in=307,920,177 out=81,157,278 elapsed=130.2s

  [7967/15692] intraday_2273.csv.gz  in=307,933,300 out=81,157,278 elapsed=130.2s

  [7968/15692] intraday_2272.csv.gz  in=307,946,345 out=81,157,278 elapsed=130.3s

  [7969/15692] intraday_2276.csv.gz  in=307,956,581 out=81,157,278 elapsed=130.3s

  [7970/15692] intraday_2278.csv.gz  in=307,969,184 out=81,157,278 elapsed=130.3s

  [7971/15692] intraday_2279.csv.gz  in=307,985,190 out=81,157,278 elapsed=130.3s

  [7972/15692] intraday_2277.csv.gz  in=307,999,413 out=81,157,278 elapsed=130.3s

  [7973/15692] intraday_2280.csv.gz  in=308,014,260 out=81,157,278 elapsed=130.3s

  [7974/15692] intraday_2281.csv.gz  in=308,025,407 out=81,157,278 elapsed=130.3s

  [7975/15692] intraday_2283.csv.gz  in=308,037,443 out=81,157,278 elapsed=130.3s

  [7976/15692] intraday_2282.csv.gz  in=308,049,377 out=81,157,278 elapsed=130.3s

  [7977/15692] intraday_2285.csv.gz  in=308,064,417 out=81,157,278 elapsed=130.3s

  [7978/15692] intraday_2287.csv.gz  in=308,080,021 out=81,157,278 elapsed=130.4s

  [7979/15692] intraday_2284.csv.gz  in=308,092,770 out=81,157,278 elapsed=130.4s

  [7980/15692] intraday_2286.csv.gz  in=308,103,575 out=81,157,278 elapsed=130.4s

  [7981/15692] intraday_2288.csv.gz  in=308,115,277 out=81,157,278 elapsed=130.4s

  [7982/15692] intraday_2292.csv.gz  in=308,125,690 out=81,157,278 elapsed=130.4s

  [7983/15692] intraday_2290.csv.gz  in=308,137,098 out=81,157,278 elapsed=130.4s

  [7984/15692] intraday_2291.csv.gz  in=308,150,461 out=81,157,278 elapsed=130.4s

  [7985/15692] intraday_2289.csv.gz  in=308,164,673 out=81,157,278 elapsed=130.4s

  [7986/15692] intraday_2293.csv.gz  in=308,176,440 out=81,157,278 elapsed=130.4s

  [7987/15692] intraday_2294.csv.gz  in=308,188,825 out=81,157,278 elapsed=130.5s

  [7988/15692] intraday_2295.csv.gz  in=308,202,467 out=81,157,278 elapsed=130.5s

  [7989/15692] intraday_2296.csv.gz  in=308,215,629 out=81,157,278 elapsed=130.5s

  [7990/15692] intraday_2298.csv.gz  in=308,225,617 out=81,157,278 elapsed=130.5s

  [7991/15692] intraday_2300.csv.gz  in=308,237,502 out=81,157,278 elapsed=130.5s

  [7992/15692] intraday_2297.csv.gz  in=308,250,751 out=81,157,278 elapsed=130.5s

  [7993/15692] intraday_2299.csv.gz  in=308,272,678 out=81,157,278 elapsed=130.5s

  [7994/15692] intraday_2301.csv.gz  in=308,288,556 out=81,157,278 elapsed=130.5s

  [7995/15692] intraday_2303.csv.gz  in=308,304,155 out=81,157,278 elapsed=130.5s

  [7996/15692] intraday_2302.csv.gz  in=308,325,038 out=81,157,278 elapsed=130.5s

  [7997/15692] intraday_2304.csv.gz  in=308,337,517 out=81,157,278 elapsed=130.6s

  [7998/15692] intraday_2305.csv.gz  in=308,351,678 out=81,157,278 elapsed=130.6s

  [7999/15692] intraday_2306.csv.gz  in=308,365,037 out=81,157,278 elapsed=130.6s

  [8000/15692] intraday_2307.csv.gz  in=308,379,827 out=81,157,278 elapsed=130.6s

  [8001/15692] intraday_2309.csv.gz  in=308,392,507 out=81,157,278 elapsed=130.6s

  [8002/15692] intraday_2308.csv.gz  in=308,404,629 out=81,157,278 elapsed=130.6s

  [8003/15692] intraday_2310.csv.gz  in=308,418,061 out=81,157,278 elapsed=130.6s

  [8004/15692] intraday_2311.csv.gz  in=308,431,481 out=81,157,278 elapsed=130.6s

  [8005/15692] intraday_2313.csv.gz  in=308,444,730 out=81,157,278 elapsed=130.6s

  [8006/15692] intraday_2312.csv.gz  in=308,456,485 out=81,157,278 elapsed=130.7s

  [8007/15692] intraday_2314.csv.gz  in=308,471,874 out=81,157,278 elapsed=130.7s

  [8008/15692] intraday_2315.csv.gz  in=308,483,780 out=81,157,278 elapsed=130.7s

  [8009/15692] intraday_2317.csv.gz  in=308,496,242 out=81,157,278 elapsed=130.7s

  [8010/15692] intraday_2318.csv.gz  in=308,508,403 out=81,157,278 elapsed=130.7s

  [8011/15692] intraday_2316.csv.gz  in=308,521,494 out=81,157,278 elapsed=130.7s

  [8012/15692] intraday_2319.csv.gz  in=308,536,122 out=81,157,278 elapsed=130.7s

  [8013/15692] intraday_2320.csv.gz  in=308,551,689 out=81,157,278 elapsed=130.7s

  [8014/15692] intraday_2322.csv.gz  in=308,564,926 out=81,157,278 elapsed=130.7s

  [8015/15692] intraday_2321.csv.gz  in=308,577,951 out=81,157,278 elapsed=130.7s

  [8016/15692] intraday_2323.csv.gz  in=308,591,323 out=81,157,278 elapsed=130.7s

  [8017/15692] intraday_2324.csv.gz  in=308,603,621 out=81,157,278 elapsed=130.8s

  [8018/15692] intraday_2325.csv.gz  in=308,616,143 out=81,157,278 elapsed=130.8s

  [8019/15692] intraday_2326.csv.gz  in=308,629,484 out=81,157,278 elapsed=130.8s

  [8020/15692] intraday_2327.csv.gz  in=308,644,562 out=81,157,278 elapsed=130.8s

  [8021/15692] intraday_2329.csv.gz  in=308,657,248 out=81,157,278 elapsed=130.8s

  [8022/15692] intraday_2330.csv.gz  in=308,671,054 out=81,157,278 elapsed=130.8s

  [8023/15692] intraday_2328.csv.gz  in=308,687,542 out=81,157,278 elapsed=130.8s

  [8024/15692] intraday_2331.csv.gz  in=308,700,531 out=81,157,278 elapsed=130.8s

  [8025/15692] intraday_2333.csv.gz  in=308,712,346 out=81,157,278 elapsed=130.8s

  [8026/15692] intraday_2332.csv.gz  in=308,724,389 out=81,157,278 elapsed=130.8s

  [8027/15692] intraday_2334.csv.gz  in=308,742,404 out=81,157,278 elapsed=130.8s

  [8028/15692] intraday_2335.csv.gz  in=308,755,028 out=81,157,278 elapsed=130.8s

  [8029/15692] intraday_2336.csv.gz  in=308,771,695 out=81,157,278 elapsed=130.9s

  [8030/15692] intraday_2337.csv.gz  in=308,782,802 out=81,157,278 elapsed=130.9s

  [8031/15692] intraday_2339.csv.gz  in=308,795,202 out=81,157,278 elapsed=130.9s

  [8032/15692] intraday_2338.csv.gz  in=308,810,494 out=81,157,278 elapsed=130.9s

  [8033/15692] intraday_2340.csv.gz  in=308,824,877 out=81,157,278 elapsed=130.9s

  [8034/15692] intraday_2341.csv.gz  in=308,838,216 out=81,157,278 elapsed=130.9s

  [8035/15692] intraday_2343.csv.gz  in=308,852,733 out=81,157,278 elapsed=130.9s

  [8036/15692] intraday_2344.csv.gz  in=308,866,696 out=81,157,278 elapsed=130.9s

  [8037/15692] intraday_2342.csv.gz  in=308,887,913 out=81,157,278 elapsed=130.9s

  [8038/15692] intraday_2345.csv.gz  in=308,902,856 out=81,157,278 elapsed=130.9s

  [8039/15692] intraday_2346.csv.gz  in=308,914,454 out=81,157,278 elapsed=130.9s

  [8040/15692] intraday_2347.csv.gz  in=308,926,079 out=81,157,278 elapsed=130.9s

  [8041/15692] intraday_2348.csv.gz  in=308,939,645 out=81,157,278 elapsed=131.0s

  [8042/15692] intraday_2349.csv.gz  in=308,953,491 out=81,157,278 elapsed=131.0s

  [8043/15692] intraday_2351.csv.gz  in=308,962,438 out=81,157,278 elapsed=131.0s

  [8044/15692] intraday_2350.csv.gz  in=308,971,504 out=81,157,278 elapsed=131.0s

  [8045/15692] intraday_2353.csv.gz  in=308,972,913 out=81,157,278 elapsed=131.0s

  [8046/15692] intraday_2352.csv.gz  in=308,984,776 out=81,157,278 elapsed=131.0s

  [8047/15692] intraday_2354.csv.gz  in=309,001,143 out=81,157,278 elapsed=131.0s

  [8048/15692] intraday_2356.csv.gz  in=309,013,705 out=81,157,278 elapsed=131.0s

  [8049/15692] intraday_2355.csv.gz  in=309,027,799 out=81,157,278 elapsed=131.0s

  [8050/15692] intraday_2357.csv.gz  in=309,039,050 out=81,157,278 elapsed=131.0s

  [8051/15692] intraday_2358.csv.gz  in=309,054,099 out=81,157,278 elapsed=131.0s

  [8052/15692] intraday_2360.csv.gz  in=309,067,067 out=81,157,278 elapsed=131.1s

  [8053/15692] intraday_2361.csv.gz  in=309,079,757 out=81,157,278 elapsed=131.1s

  [8054/15692] intraday_2359.csv.gz  in=309,101,560 out=81,157,278 elapsed=131.1s

  [8055/15692] intraday_2362.csv.gz  in=309,119,329 out=81,157,278 elapsed=131.1s

  [8056/15692] intraday_2363.csv.gz  in=309,134,406 out=81,157,278 elapsed=131.1s

  [8057/15692] intraday_2365.csv.gz  in=309,147,053 out=81,157,278 elapsed=131.1s

  [8058/15692] intraday_2364.csv.gz  in=309,156,868 out=81,157,278 elapsed=131.1s

  [8059/15692] intraday_2366.csv.gz  in=309,170,795 out=81,157,278 elapsed=131.1s

  [8060/15692] intraday_2368.csv.gz  in=309,182,258 out=81,157,278 elapsed=131.1s

  [8061/15692] intraday_2367.csv.gz  in=309,192,923 out=81,157,278 elapsed=131.1s

  [8062/15692] intraday_2369.csv.gz  in=309,205,484 out=81,157,278 elapsed=131.1s

  [8063/15692] intraday_2370.csv.gz  in=309,218,542 out=81,157,278 elapsed=131.1s

  [8064/15692] intraday_2374.csv.gz  in=309,232,607 out=81,157,278 elapsed=131.2s

  [8065/15692] intraday_2371.csv.gz  in=309,245,160 out=81,157,278 elapsed=131.2s

  [8066/15692] intraday_2372.csv.gz  in=309,256,075 out=81,157,278 elapsed=131.2s

  [8067/15692] intraday_2373.csv.gz  in=309,268,141 out=81,157,278 elapsed=131.2s

  [8068/15692] intraday_2376.csv.gz  in=309,280,520 out=81,157,278 elapsed=131.2s

  [8069/15692] intraday_2375.csv.gz  in=309,292,552 out=81,157,278 elapsed=131.2s

  [8070/15692] intraday_2378.csv.gz  in=309,305,478 out=81,157,278 elapsed=131.2s

  [8071/15692] intraday_2377.csv.gz  in=309,323,757 out=81,157,278 elapsed=131.2s

  [8072/15692] intraday_2379.csv.gz  in=309,333,242 out=81,157,278 elapsed=131.2s

  [8073/15692] intraday_2382.csv.gz  in=309,346,707 out=81,157,278 elapsed=131.2s

  [8074/15692] intraday_2380.csv.gz  in=309,359,069 out=81,157,278 elapsed=131.2s

  [8075/15692] intraday_2381.csv.gz  in=309,375,202 out=81,157,278 elapsed=131.3s

  [8076/15692] intraday_2383.csv.gz  in=309,390,527 out=81,157,278 elapsed=131.3s

  [8077/15692] intraday_2385.csv.gz  in=309,402,585 out=81,157,278 elapsed=131.3s

  [8078/15692] intraday_2386.csv.gz  in=309,414,887 out=81,157,278 elapsed=131.3s

  [8079/15692] intraday_2384.csv.gz  in=309,429,404 out=81,157,278 elapsed=131.3s

  [8080/15692] intraday_2388.csv.gz  in=309,441,031 out=81,157,278 elapsed=131.3s

  [8081/15692] intraday_2389.csv.gz  in=309,453,328 out=81,157,278 elapsed=131.3s

  [8082/15692] intraday_2390.csv.gz  in=309,465,024 out=81,157,278 elapsed=131.3s

  [8083/15692] intraday_2387.csv.gz  in=309,488,300 out=81,157,278 elapsed=131.3s

  [8084/15692] intraday_2392.csv.gz  in=309,499,979 out=81,157,278 elapsed=131.4s

  [8085/15692] intraday_2391.csv.gz  in=309,511,376 out=81,157,278 elapsed=131.4s

  [8086/15692] intraday_2393.csv.gz  in=309,523,322 out=81,157,278 elapsed=131.4s

  [8087/15692] intraday_2394.csv.gz  in=309,537,704 out=81,157,278 elapsed=131.4s

  [8088/15692] intraday_2396.csv.gz  in=309,549,941 out=81,157,278 elapsed=131.4s

  [8089/15692] intraday_2397.csv.gz  in=309,563,615 out=81,157,278 elapsed=131.4s

  [8090/15692] intraday_2395.csv.gz  in=309,577,615 out=81,157,278 elapsed=131.4s

  [8091/15692] intraday_2398.csv.gz  in=309,592,973 out=81,157,278 elapsed=131.4s

  [8092/15692] intraday_2399.csv.gz  in=309,606,653 out=81,157,278 elapsed=131.4s

  [8093/15692] intraday_2402.csv.gz  in=309,618,753 out=81,157,278 elapsed=131.4s

  [8094/15692] intraday_2400.csv.gz  in=309,636,038 out=81,157,278 elapsed=131.5s

  [8095/15692] intraday_2403.csv.gz  in=309,648,245 out=81,157,278 elapsed=131.5s

  [8096/15692] intraday_2401.csv.gz  in=309,668,789 out=81,157,278 elapsed=131.5s

  [8097/15692] intraday_2405.csv.gz  in=309,680,967 out=81,157,278 elapsed=131.5s

  [8098/15692] intraday_2404.csv.gz  in=309,701,331 out=81,157,278 elapsed=131.5s

  [8099/15692] intraday_2406.csv.gz  in=309,713,122 out=81,157,278 elapsed=131.5s

  [8100/15692] intraday_2407.csv.gz  in=309,726,763 out=81,157,278 elapsed=131.5s

  [8101/15692] intraday_2409.csv.gz  in=309,740,063 out=81,157,278 elapsed=131.5s

  [8102/15692] intraday_2408.csv.gz  in=309,756,233 out=81,157,278 elapsed=131.5s

  [8103/15692] intraday_2411.csv.gz  in=309,769,940 out=81,157,278 elapsed=131.6s

  [8104/15692] intraday_2410.csv.gz  in=309,790,078 out=81,157,278 elapsed=131.6s

  [8105/15692] intraday_2412.csv.gz  in=309,802,711 out=81,157,278 elapsed=131.6s

  [8106/15692] intraday_2413.csv.gz  in=309,816,111 out=81,157,278 elapsed=131.6s

  [8107/15692] intraday_2414.csv.gz  in=309,831,148 out=81,157,278 elapsed=131.6s

  [8108/15692] intraday_2415.csv.gz  in=309,843,685 out=81,157,278 elapsed=131.6s

  [8109/15692] intraday_2416.csv.gz  in=309,863,938 out=81,157,278 elapsed=131.6s

  [8110/15692] intraday_2418.csv.gz  in=309,878,124 out=81,157,278 elapsed=131.6s

  [8111/15692] intraday_2417.csv.gz  in=309,906,643 out=81,157,278 elapsed=131.6s

  [8112/15692] intraday_2419.csv.gz  in=309,921,023 out=81,157,278 elapsed=131.6s

  [8113/15692] intraday_2422.csv.gz  in=309,930,993 out=81,157,278 elapsed=131.7s

  [8114/15692] intraday_2420.csv.gz  in=309,945,448 out=81,157,278 elapsed=131.7s

  [8115/15692] intraday_2423.csv.gz  in=309,957,427 out=81,157,278 elapsed=131.7s

  [8116/15692] intraday_2421.csv.gz  in=309,973,054 out=81,157,278 elapsed=131.7s

  [8117/15692] intraday_2424.csv.gz  in=309,985,665 out=81,157,278 elapsed=131.7s

  [8118/15692] intraday_2425.csv.gz  in=310,000,312 out=81,157,278 elapsed=131.7s

  [8119/15692] intraday_2426.csv.gz  in=310,009,845 out=81,157,278 elapsed=131.7s

  [8120/15692] intraday_2427.csv.gz  in=310,022,310 out=81,157,278 elapsed=131.7s

  [8121/15692] intraday_2428.csv.gz  in=310,033,123 out=81,157,278 elapsed=131.7s

  [8122/15692] intraday_2430.csv.gz  in=310,045,267 out=81,157,278 elapsed=131.7s

  [8123/15692] intraday_2429.csv.gz  in=310,061,853 out=81,157,278 elapsed=131.7s

  [8124/15692] intraday_2432.csv.gz  in=310,073,427 out=81,157,278 elapsed=131.7s

  [8125/15692] intraday_2431.csv.gz  in=310,085,800 out=81,157,278 elapsed=131.7s

  [8126/15692] intraday_2433.csv.gz  in=310,096,536 out=81,157,278 elapsed=131.8s

  [8127/15692] intraday_2434.csv.gz  in=310,107,886 out=81,157,278 elapsed=131.8s

  [8128/15692] intraday_2435.csv.gz  in=310,122,536 out=81,157,278 elapsed=131.8s

  [8129/15692] intraday_2437.csv.gz  in=310,135,189 out=81,157,278 elapsed=131.8s

  [8130/15692] intraday_2438.csv.gz  in=310,147,530 out=81,157,278 elapsed=131.8s

  [8131/15692] intraday_2436.csv.gz  in=310,172,819 out=81,157,278 elapsed=131.8s

  [8132/15692] intraday_2439.csv.gz  in=310,184,172 out=81,157,278 elapsed=131.8s

  [8133/15692] intraday_2440.csv.gz  in=310,196,521 out=81,157,278 elapsed=131.8s

  [8134/15692] intraday_2441.csv.gz  in=310,211,254 out=81,157,278 elapsed=131.8s

  [8135/15692] intraday_2442.csv.gz  in=310,224,008 out=81,157,278 elapsed=131.9s

  [8136/15692] intraday_2443.csv.gz  in=310,237,740 out=81,157,278 elapsed=131.9s

  [8137/15692] intraday_2444.csv.gz  in=310,250,598 out=81,157,278 elapsed=131.9s

  [8138/15692] intraday_2445.csv.gz  in=310,265,031 out=81,157,278 elapsed=131.9s

  [8139/15692] intraday_2446.csv.gz  in=310,279,029 out=81,157,278 elapsed=131.9s

  [8140/15692] intraday_2447.csv.gz  in=310,293,661 out=81,157,278 elapsed=131.9s

  [8141/15692] intraday_2448.csv.gz  in=310,307,566 out=81,157,278 elapsed=131.9s

  [8142/15692] intraday_2449.csv.gz  in=310,318,967 out=81,157,278 elapsed=131.9s

  [8143/15692] intraday_2450.csv.gz  in=310,331,616 out=81,157,278 elapsed=131.9s

  [8144/15692] intraday_2451.csv.gz  in=310,345,532 out=81,157,278 elapsed=131.9s

  [8145/15692] intraday_2453.csv.gz  in=310,356,822 out=81,157,278 elapsed=131.9s

  [8146/15692] intraday_2452.csv.gz  in=310,370,125 out=81,157,278 elapsed=131.9s

  [8147/15692] intraday_2454.csv.gz  in=310,383,963 out=81,157,278 elapsed=131.9s

  [8148/15692] intraday_2456.csv.gz  in=310,398,918 out=81,157,278 elapsed=132.0s

  [8149/15692] intraday_2455.csv.gz  in=310,414,045 out=81,157,278 elapsed=132.0s

  [8150/15692] intraday_2458.csv.gz  in=310,424,279 out=81,157,278 elapsed=132.0s

  [8151/15692] intraday_2457.csv.gz  in=310,440,542 out=81,157,278 elapsed=132.0s

  [8152/15692] intraday_2459.csv.gz  in=310,453,309 out=81,157,278 elapsed=132.0s

  [8153/15692] intraday_2461.csv.gz  in=310,468,245 out=81,157,278 elapsed=132.0s

  [8154/15692] intraday_2460.csv.gz  in=310,482,405 out=81,157,278 elapsed=132.0s

  [8155/15692] intraday_2462.csv.gz  in=310,495,785 out=81,157,278 elapsed=132.0s

  [8156/15692] intraday_2463.csv.gz  in=310,510,218 out=81,157,278 elapsed=132.0s

  [8157/15692] intraday_2464.csv.gz  in=310,522,397 out=81,157,278 elapsed=132.0s

  [8158/15692] intraday_2465.csv.gz  in=310,535,829 out=81,157,278 elapsed=132.0s

  [8159/15692] intraday_2466.csv.gz  in=310,548,878 out=81,157,278 elapsed=132.1s

  [8160/15692] intraday_2468.csv.gz  in=310,560,698 out=81,157,278 elapsed=132.1s

  [8161/15692] intraday_2467.csv.gz  in=310,575,027 out=81,157,278 elapsed=132.1s

  [8162/15692] intraday_2469.csv.gz  in=310,592,255 out=81,157,278 elapsed=132.1s

  [8163/15692] intraday_2470.csv.gz  in=310,604,723 out=81,157,278 elapsed=132.1s

  [8164/15692] intraday_2472.csv.gz  in=310,620,348 out=81,157,278 elapsed=132.1s

  [8165/15692] intraday_2471.csv.gz  in=310,634,561 out=81,157,278 elapsed=132.1s

  [8166/15692] intraday_2473.csv.gz  in=310,647,668 out=81,157,278 elapsed=132.1s

  [8167/15692] intraday_2474.csv.gz  in=310,658,627 out=81,157,278 elapsed=132.1s

  [8168/15692] intraday_2475.csv.gz  in=310,673,125 out=81,157,278 elapsed=132.1s

  [8169/15692] intraday_2477.csv.gz  in=310,689,259 out=81,157,278 elapsed=132.1s

  [8170/15692] intraday_2476.csv.gz  in=310,702,623 out=81,157,278 elapsed=132.1s

  [8171/15692] intraday_2478.csv.gz  in=310,714,569 out=81,157,278 elapsed=132.1s

  [8172/15692] intraday_2480.csv.gz  in=310,728,550 out=81,157,278 elapsed=132.2s

  [8173/15692] intraday_2479.csv.gz  in=310,742,652 out=81,157,278 elapsed=132.2s

  [8174/15692] intraday_2481.csv.gz  in=310,758,186 out=81,157,278 elapsed=132.2s

  [8175/15692] intraday_2482.csv.gz  in=310,772,470 out=81,157,278 elapsed=132.2s

  [8176/15692] intraday_2483.csv.gz  in=310,787,372 out=81,157,278 elapsed=132.2s

  [8177/15692] intraday_2484.csv.gz  in=310,803,184 out=81,157,278 elapsed=132.2s

  [8178/15692] intraday_2487.csv.gz  in=310,814,973 out=81,157,278 elapsed=132.2s

  [8179/15692] intraday_2485.csv.gz  in=310,828,348 out=81,157,278 elapsed=132.2s

  [8180/15692] intraday_2486.csv.gz  in=310,842,705 out=81,157,278 elapsed=132.2s

  [8181/15692] intraday_2488.csv.gz  in=310,854,921 out=81,157,278 elapsed=132.2s

  [8182/15692] intraday_2489.csv.gz  in=310,866,726 out=81,157,278 elapsed=132.3s

  [8183/15692] intraday_2492.csv.gz  in=310,874,788 out=81,157,278 elapsed=132.3s

  [8184/15692] intraday_2490.csv.gz  in=310,889,463 out=81,157,278 elapsed=132.3s

  [8185/15692] intraday_2491.csv.gz  in=310,898,180 out=81,157,278 elapsed=132.3s

  [8186/15692] intraday_2493.csv.gz  in=310,909,669 out=81,157,278 elapsed=132.3s

  [8187/15692] intraday_2496.csv.gz  in=310,921,482 out=81,157,278 elapsed=132.3s

  [8188/15692] intraday_2494.csv.gz  in=310,936,779 out=81,157,278 elapsed=132.3s

  [8189/15692] intraday_2495.csv.gz  in=310,950,694 out=81,157,278 elapsed=132.3s

  [8190/15692] intraday_2497.csv.gz  in=310,961,683 out=81,157,278 elapsed=132.3s

  [8191/15692] intraday_2498.csv.gz  in=310,976,427 out=81,157,278 elapsed=132.3s

  [8192/15692] intraday_2499.csv.gz  in=310,990,330 out=81,157,278 elapsed=132.4s

  [8193/15692] intraday_2500.csv.gz  in=311,002,780 out=81,157,278 elapsed=132.4s

  [8194/15692] intraday_2501.csv.gz  in=311,014,640 out=81,157,278 elapsed=132.4s

  [8195/15692] intraday_2504.csv.gz  in=311,023,729 out=81,157,278 elapsed=132.4s

  [8196/15692] intraday_2503.csv.gz  in=311,038,153 out=81,157,278 elapsed=132.4s

  [8197/15692] intraday_2502.csv.gz  in=311,051,512 out=81,157,278 elapsed=132.4s

  [8198/15692] intraday_2506.csv.gz  in=311,064,446 out=81,157,278 elapsed=132.4s

  [8199/15692] intraday_2505.csv.gz  in=311,075,612 out=81,157,278 elapsed=132.4s

  [8200/15692] intraday_2507.csv.gz  in=311,086,352 out=81,157,278 elapsed=132.4s

  [8201/15692] intraday_2508.csv.gz  in=311,097,688 out=81,157,278 elapsed=132.4s

  [8202/15692] intraday_2509.csv.gz  in=311,109,573 out=81,157,278 elapsed=132.4s

  [8203/15692] intraday_2510.csv.gz  in=311,121,699 out=81,157,278 elapsed=132.4s

  [8204/15692] intraday_2512.csv.gz  in=311,133,455 out=81,157,278 elapsed=132.5s

  [8205/15692] intraday_2513.csv.gz  in=311,144,732 out=81,157,278 elapsed=132.5s

  [8206/15692] intraday_2511.csv.gz  in=311,156,741 out=81,157,278 elapsed=132.5s

  [8207/15692] intraday_2514.csv.gz  in=311,169,787 out=81,157,278 elapsed=132.5s

  [8208/15692] intraday_2516.csv.gz  in=311,181,918 out=81,157,278 elapsed=132.5s

  [8209/15692] intraday_2515.csv.gz  in=311,193,649 out=81,157,278 elapsed=132.5s

  [8210/15692] intraday_2517.csv.gz  in=311,206,235 out=81,157,278 elapsed=132.5s

  [8211/15692] intraday_2518.csv.gz  in=311,218,130 out=81,157,278 elapsed=132.6s

  [8212/15692] intraday_2520.csv.gz  in=311,229,966 out=81,157,278 elapsed=132.6s

  [8213/15692] intraday_2519.csv.gz  in=311,238,783 out=81,157,278 elapsed=132.6s

  [8214/15692] intraday_2521.csv.gz  in=311,252,254 out=81,157,278 elapsed=132.6s

  [8215/15692] intraday_2522.csv.gz  in=311,264,653 out=81,157,278 elapsed=132.6s

  [8216/15692] intraday_2523.csv.gz  in=311,279,128 out=81,157,278 elapsed=132.6s

  [8217/15692] intraday_2524.csv.gz  in=311,292,499 out=81,157,278 elapsed=132.6s

  [8218/15692] intraday_2525.csv.gz  in=311,303,870 out=81,157,278 elapsed=132.6s

  [8219/15692] intraday_2526.csv.gz  in=311,316,535 out=81,157,278 elapsed=132.6s

  [8220/15692] intraday_2527.csv.gz  in=311,329,366 out=81,157,278 elapsed=132.6s

  [8221/15692] intraday_2528.csv.gz  in=311,340,486 out=81,157,278 elapsed=132.6s

  [8222/15692] intraday_2530.csv.gz  in=311,352,038 out=81,157,278 elapsed=132.7s

  [8223/15692] intraday_2529.csv.gz  in=311,365,124 out=81,157,278 elapsed=132.7s

  [8224/15692] intraday_2531.csv.gz  in=311,375,501 out=81,157,278 elapsed=132.7s

  [8225/15692] intraday_2532.csv.gz  in=311,387,774 out=81,157,278 elapsed=132.7s

  [8226/15692] intraday_2533.csv.gz  in=311,397,727 out=81,157,278 elapsed=132.7s

  [8227/15692] intraday_2535.csv.gz  in=311,409,880 out=81,157,278 elapsed=132.7s

  [8228/15692] intraday_2534.csv.gz  in=311,424,942 out=81,157,278 elapsed=132.7s

  [8229/15692] intraday_2537.csv.gz  in=311,436,727 out=81,157,278 elapsed=132.7s

  [8230/15692] intraday_2536.csv.gz  in=311,451,073 out=81,157,278 elapsed=132.7s

  [8231/15692] intraday_2538.csv.gz  in=311,463,358 out=81,157,278 elapsed=132.7s

  [8232/15692] intraday_2540.csv.gz  in=311,473,617 out=81,157,278 elapsed=132.8s

  [8233/15692] intraday_2541.csv.gz  in=311,485,726 out=81,157,278 elapsed=132.8s

  [8234/15692] intraday_2539.csv.gz  in=311,497,779 out=81,157,278 elapsed=132.8s

  [8235/15692] intraday_2542.csv.gz  in=311,509,876 out=81,157,278 elapsed=132.8s

  [8236/15692] intraday_2543.csv.gz  in=311,520,076 out=81,157,278 elapsed=132.8s

  [8237/15692] intraday_2545.csv.gz  in=311,530,986 out=81,157,278 elapsed=132.8s

  [8238/15692] intraday_2544.csv.gz  in=311,544,021 out=81,157,278 elapsed=132.8s

  [8239/15692] intraday_2546.csv.gz  in=311,555,385 out=81,157,278 elapsed=132.8s

  [8240/15692] intraday_2547.csv.gz  in=311,568,996 out=81,157,278 elapsed=132.8s

  [8241/15692] intraday_2549.csv.gz  in=311,579,903 out=81,157,278 elapsed=132.8s

  [8242/15692] intraday_2548.csv.gz  in=311,593,899 out=81,157,278 elapsed=132.8s

  [8243/15692] intraday_2550.csv.gz  in=311,604,902 out=81,157,278 elapsed=132.9s

  [8244/15692] intraday_2552.csv.gz  in=311,618,441 out=81,157,278 elapsed=132.9s

  [8245/15692] intraday_2551.csv.gz  in=311,631,843 out=81,157,278 elapsed=132.9s

  [8246/15692] intraday_2553.csv.gz  in=311,644,287 out=81,157,278 elapsed=132.9s

  [8247/15692] intraday_2554.csv.gz  in=311,655,051 out=81,157,278 elapsed=132.9s

  [8248/15692] intraday_2556.csv.gz  in=311,664,937 out=81,157,278 elapsed=132.9s

  [8249/15692] intraday_2555.csv.gz  in=311,675,872 out=81,157,278 elapsed=132.9s

  [8250/15692] intraday_2557.csv.gz  in=311,690,328 out=81,157,278 elapsed=132.9s

  [8251/15692] intraday_2558.csv.gz  in=311,702,149 out=81,157,278 elapsed=132.9s

  [8252/15692] intraday_2559.csv.gz  in=311,715,228 out=81,157,278 elapsed=133.0s

  [8253/15692] intraday_2561.csv.gz  in=311,726,684 out=81,157,278 elapsed=133.0s

  [8254/15692] intraday_2560.csv.gz  in=311,739,675 out=81,157,278 elapsed=133.0s

  [8255/15692] intraday_2562.csv.gz  in=311,751,296 out=81,157,278 elapsed=133.0s

  [8256/15692] intraday_2564.csv.gz  in=311,761,877 out=81,157,278 elapsed=133.0s

  [8257/15692] intraday_2563.csv.gz  in=311,774,413 out=81,157,278 elapsed=133.0s

  [8258/15692] intraday_2565.csv.gz  in=311,787,062 out=81,157,278 elapsed=133.0s

  [8259/15692] intraday_2566.csv.gz  in=311,796,772 out=81,157,278 elapsed=133.0s

  [8260/15692] intraday_2567.csv.gz  in=311,808,417 out=81,157,278 elapsed=133.0s

  [8261/15692] intraday_2568.csv.gz  in=311,820,715 out=81,157,278 elapsed=133.0s

  [8262/15692] intraday_2570.csv.gz  in=311,832,394 out=81,157,278 elapsed=133.1s

  [8263/15692] intraday_2571.csv.gz  in=311,844,585 out=81,157,278 elapsed=133.1s

  [8264/15692] intraday_2569.csv.gz  in=311,856,271 out=81,157,278 elapsed=133.1s

  [8265/15692] intraday_2572.csv.gz  in=311,866,599 out=81,157,278 elapsed=133.1s

  [8266/15692] intraday_2573.csv.gz  in=311,877,766 out=81,157,278 elapsed=133.1s

  [8267/15692] intraday_2574.csv.gz  in=311,889,552 out=81,157,278 elapsed=133.1s

  [8268/15692] intraday_2575.csv.gz  in=311,904,019 out=81,157,278 elapsed=133.1s

  [8269/15692] intraday_2576.csv.gz  in=311,915,766 out=81,157,278 elapsed=133.1s

  [8270/15692] intraday_2577.csv.gz  in=311,928,153 out=81,157,278 elapsed=133.1s

  [8271/15692] intraday_2579.csv.gz  in=311,939,890 out=81,157,278 elapsed=133.1s

  [8272/15692] intraday_2578.csv.gz  in=311,952,418 out=81,157,278 elapsed=133.2s

  [8273/15692] intraday_2580.csv.gz  in=311,964,835 out=81,157,278 elapsed=133.2s

  [8274/15692] intraday_2581.csv.gz  in=311,980,119 out=81,157,278 elapsed=133.2s

  [8275/15692] intraday_2582.csv.gz  in=311,990,767 out=81,157,278 elapsed=133.2s

  [8276/15692] intraday_2584.csv.gz  in=312,003,416 out=81,157,278 elapsed=133.2s

  [8277/15692] intraday_2585.csv.gz  in=312,016,843 out=81,157,278 elapsed=133.2s

  [8278/15692] intraday_2583.csv.gz  in=312,031,310 out=81,157,278 elapsed=133.2s

  [8279/15692] intraday_2586.csv.gz  in=312,045,030 out=81,157,278 elapsed=133.2s

  [8280/15692] intraday_2587.csv.gz  in=312,057,849 out=81,157,278 elapsed=133.2s

  [8281/15692] intraday_2588.csv.gz  in=312,069,978 out=81,157,278 elapsed=133.3s

  [8282/15692] intraday_2589.csv.gz  in=312,082,427 out=81,157,278 elapsed=133.3s

  [8283/15692] intraday_2590.csv.gz  in=312,092,979 out=81,157,278 elapsed=133.3s

  [8284/15692] intraday_2591.csv.gz  in=312,104,505 out=81,157,278 elapsed=133.3s

  [8285/15692] intraday_2592.csv.gz  in=312,115,575 out=81,157,278 elapsed=133.3s

  [8286/15692] intraday_2593.csv.gz  in=312,128,857 out=81,157,278 elapsed=133.3s

  [8287/15692] intraday_2594.csv.gz  in=312,139,908 out=81,157,278 elapsed=133.3s

  [8288/15692] intraday_2596.csv.gz  in=312,152,107 out=81,157,278 elapsed=133.3s

  [8289/15692] intraday_2595.csv.gz  in=312,165,251 out=81,157,278 elapsed=133.3s

  [8290/15692] intraday_2598.csv.gz  in=312,176,349 out=81,157,278 elapsed=133.3s

  [8291/15692] intraday_2597.csv.gz  in=312,189,861 out=81,157,278 elapsed=133.3s

  [8292/15692] intraday_2599.csv.gz  in=312,202,754 out=81,157,278 elapsed=133.3s

  [8293/15692] intraday_2600.csv.gz  in=312,217,526 out=81,157,278 elapsed=133.4s

  [8294/15692] intraday_2602.csv.gz  in=312,230,799 out=81,157,278 elapsed=133.4s

  [8295/15692] intraday_2601.csv.gz  in=312,244,550 out=81,157,278 elapsed=133.4s

  [8296/15692] intraday_2603.csv.gz  in=312,258,113 out=81,157,278 elapsed=133.4s

  [8297/15692] intraday_2604.csv.gz  in=312,270,030 out=81,157,278 elapsed=133.4s

  [8298/15692] intraday_2605.csv.gz  in=312,282,629 out=81,157,278 elapsed=133.4s

  [8299/15692] intraday_2606.csv.gz  in=312,295,843 out=81,157,278 elapsed=133.4s

  [8300/15692] intraday_2607.csv.gz  in=312,308,415 out=81,157,278 elapsed=133.4s

  [8301/15692] intraday_2608.csv.gz  in=312,324,167 out=81,157,278 elapsed=133.4s

  [8302/15692] intraday_2609.csv.gz  in=312,337,786 out=81,157,278 elapsed=133.4s

  [8303/15692] intraday_2610.csv.gz  in=312,350,511 out=81,157,278 elapsed=133.5s

  [8304/15692] intraday_2612.csv.gz  in=312,360,362 out=81,157,278 elapsed=133.5s

  [8305/15692] intraday_2611.csv.gz  in=312,374,395 out=81,157,278 elapsed=133.5s

  [8306/15692] intraday_2614.csv.gz  in=312,385,203 out=81,157,278 elapsed=133.7s

  [8307/15692] intraday_2613.csv.gz  in=312,397,799 out=81,157,278 elapsed=133.7s

  [8308/15692] intraday_2615.csv.gz  in=312,412,240 out=81,157,278 elapsed=133.7s

  [8309/15692] intraday_2616.csv.gz  in=312,426,026 out=81,157,278 elapsed=133.7s

  [8310/15692] intraday_2617.csv.gz  in=312,442,152 out=81,157,278 elapsed=133.7s

  [8311/15692] intraday_2619.csv.gz  in=312,456,093 out=81,157,278 elapsed=133.8s

  [8312/15692] intraday_2618.csv.gz  in=312,468,034 out=81,157,278 elapsed=133.8s

  [8313/15692] intraday_2620.csv.gz  in=312,481,634 out=81,157,278 elapsed=133.8s

  [8314/15692] intraday_2621.csv.gz  in=312,495,250 out=81,157,278 elapsed=133.8s

  [8315/15692] intraday_2622.csv.gz  in=312,508,344 out=81,157,278 elapsed=133.8s

  [8316/15692] intraday_2623.csv.gz  in=312,523,938 out=81,157,278 elapsed=133.8s

  [8317/15692] intraday_2624.csv.gz  in=312,538,279 out=81,157,278 elapsed=133.8s

  [8318/15692] intraday_2625.csv.gz  in=312,551,872 out=81,157,278 elapsed=133.8s

  [8319/15692] intraday_2627.csv.gz  in=312,561,777 out=81,157,278 elapsed=133.8s

  [8320/15692] intraday_2626.csv.gz  in=312,574,631 out=81,157,278 elapsed=133.8s

  [8321/15692] intraday_2628.csv.gz  in=312,587,448 out=81,157,278 elapsed=133.8s

  [8322/15692] intraday_2629.csv.gz  in=312,599,604 out=81,157,278 elapsed=133.8s

  [8323/15692] intraday_2630.csv.gz  in=312,611,481 out=81,157,278 elapsed=133.9s

  [8324/15692] intraday_2633.csv.gz  in=312,617,504 out=81,157,278 elapsed=133.9s

  [8325/15692] intraday_2631.csv.gz  in=312,624,575 out=81,157,278 elapsed=133.9s

  [8326/15692] intraday_2632.csv.gz  in=312,634,838 out=81,157,278 elapsed=133.9s

  [8327/15692] intraday_2635.csv.gz  in=312,634,963 out=81,157,278 elapsed=133.9s

  [8328/15692] intraday_2636.csv.gz  in=312,647,425 out=81,157,278 elapsed=133.9s

  [8329/15692] intraday_2637.csv.gz  in=312,647,649 out=81,157,278 elapsed=133.9s

  [8330/15692] intraday_2634.csv.gz  in=312,649,850 out=81,157,278 elapsed=133.9s

  [8331/15692] intraday_2638.csv.gz  in=312,649,931 out=81,157,278 elapsed=133.9s

  [8332/15692] intraday_2641.csv.gz  in=312,649,964 out=81,157,278 elapsed=133.9s

  [8333/15692] intraday_2642.csv.gz  in=312,649,975 out=81,157,278 elapsed=133.9s

  [8334/15692] intraday_2643.csv.gz  in=312,649,987 out=81,157,278 elapsed=133.9s

  [8335/15692] intraday_2639.csv.gz  in=312,650,098 out=81,157,278 elapsed=134.0s

  [8336/15692] intraday_2644.csv.gz  in=312,650,140 out=81,157,278 elapsed=134.0s

  [8337/15692] intraday_2640.csv.gz  in=312,656,629 out=81,157,278 elapsed=134.0s

  [8338/15692] intraday_2646.csv.gz  in=312,656,700 out=81,157,278 elapsed=134.0s

  [8339/15692] intraday_2645.csv.gz  in=312,657,476 out=81,157,278 elapsed=134.0s

  [8340/15692] intraday_2648.csv.gz  in=312,657,520 out=81,157,278 elapsed=134.0s

  [8341/15692] intraday_2647.csv.gz  in=312,668,663 out=81,157,278 elapsed=134.0s

  [8342/15692] intraday_2649.csv.gz  in=312,668,692 out=81,157,278 elapsed=134.0s

  [8343/15692] intraday_2650.csv.gz  in=312,683,352 out=81,157,278 elapsed=134.0s

  [8344/15692] intraday_2651.csv.gz  in=312,683,439 out=81,157,278 elapsed=134.0s

  [8345/15692] intraday_2653.csv.gz  in=312,689,293 out=81,157,278 elapsed=134.0s

  [8346/15692] intraday_2652.csv.gz  in=312,689,308 out=81,157,278 elapsed=134.0s

  [8347/15692] intraday_2654.csv.gz  in=312,689,639 out=81,157,278 elapsed=134.0s

  [8348/15692] intraday_2655.csv.gz  in=312,689,805 out=81,157,278 elapsed=134.1s

  [8349/15692] intraday_2656.csv.gz  in=312,691,750 out=81,157,278 elapsed=134.1s

  [8350/15692] intraday_2659.csv.gz  in=312,691,773 out=81,157,278 elapsed=134.1s

  [8351/15692] intraday_2658.csv.gz  in=312,695,933 out=81,157,278 elapsed=134.1s

  [8352/15692] intraday_2657.csv.gz  in=312,699,133 out=81,157,278 elapsed=134.1s

  [8353/15692] intraday_2660.csv.gz  in=312,702,611 out=81,157,278 elapsed=134.1s

  [8354/15692] intraday_2663.csv.gz  in=312,702,771 out=81,157,278 elapsed=134.1s

  [8355/15692] intraday_2662.csv.gz  in=312,702,814 out=81,157,278 elapsed=134.1s

  [8356/15692] intraday_2661.csv.gz  in=312,711,489 out=81,157,278 elapsed=134.1s

  [8357/15692] intraday_2664.csv.gz  in=312,711,577 out=81,157,278 elapsed=134.1s

  [8358/15692] intraday_2665.csv.gz  in=312,726,411 out=81,157,278 elapsed=134.1s

  [8359/15692] intraday_2667.csv.gz  in=312,738,863 out=81,157,278 elapsed=134.1s

  [8360/15692] intraday_2668.csv.gz  in=312,749,164 out=81,157,278 elapsed=134.1s

  [8361/15692] intraday_2666.csv.gz  in=312,762,466 out=81,157,278 elapsed=134.1s

  [8362/15692] intraday_2672.csv.gz  in=312,776,503 out=81,157,278 elapsed=134.2s

  [8363/15692] intraday_2670.csv.gz  in=312,789,732 out=81,157,278 elapsed=134.2s

  [8364/15692] intraday_2669.csv.gz  in=312,803,637 out=81,157,278 elapsed=134.2s

  [8365/15692] intraday_2671.csv.gz  in=312,815,080 out=81,157,278 elapsed=134.2s

  [8366/15692] intraday_2673.csv.gz  in=312,827,846 out=81,157,278 elapsed=134.2s

  [8367/15692] intraday_2675.csv.gz  in=312,836,524 out=81,157,278 elapsed=134.2s

  [8368/15692] intraday_2674.csv.gz  in=312,849,741 out=81,157,278 elapsed=134.2s

  [8369/15692] intraday_2676.csv.gz  in=312,861,203 out=81,157,278 elapsed=134.2s

  [8370/15692] intraday_2677.csv.gz  in=312,872,206 out=81,157,278 elapsed=134.3s

  [8371/15692] intraday_2679.csv.gz  in=312,882,746 out=81,157,278 elapsed=134.3s

  [8372/15692] intraday_2678.csv.gz  in=312,899,608 out=81,157,278 elapsed=134.3s

  [8373/15692] intraday_2680.csv.gz  in=312,909,481 out=81,157,278 elapsed=134.3s

  [8374/15692] intraday_2681.csv.gz  in=312,921,805 out=81,157,278 elapsed=134.3s

  [8375/15692] intraday_2683.csv.gz  in=312,932,063 out=81,157,278 elapsed=134.3s

  [8376/15692] intraday_2682.csv.gz  in=312,943,749 out=81,157,278 elapsed=134.3s

  [8377/15692] intraday_2684.csv.gz  in=312,956,739 out=81,157,278 elapsed=134.3s

  [8378/15692] intraday_2685.csv.gz  in=312,968,662 out=81,157,278 elapsed=134.4s

  [8379/15692] intraday_2687.csv.gz  in=312,979,984 out=81,157,278 elapsed=134.4s

  [8380/15692] intraday_2686.csv.gz  in=312,992,339 out=81,157,278 elapsed=134.4s

  [8381/15692] intraday_2688.csv.gz  in=313,003,306 out=81,157,278 elapsed=134.4s

  [8382/15692] intraday_2689.csv.gz  in=313,014,551 out=81,157,278 elapsed=134.4s

  [8383/15692] intraday_2690.csv.gz  in=313,024,048 out=81,157,278 elapsed=134.4s

  [8384/15692] intraday_2691.csv.gz  in=313,035,838 out=81,157,278 elapsed=134.4s

  [8385/15692] intraday_2692.csv.gz  in=313,047,626 out=81,157,278 elapsed=134.4s

  [8386/15692] intraday_2693.csv.gz  in=313,059,857 out=81,157,278 elapsed=134.4s

  [8387/15692] intraday_2694.csv.gz  in=313,073,508 out=81,157,278 elapsed=134.4s

  [8388/15692] intraday_2695.csv.gz  in=313,086,156 out=81,157,278 elapsed=134.5s

  [8389/15692] intraday_2696.csv.gz  in=313,096,902 out=81,157,278 elapsed=134.5s

  [8390/15692] intraday_2697.csv.gz  in=313,108,729 out=81,157,278 elapsed=134.5s

  [8391/15692] intraday_2698.csv.gz  in=313,121,415 out=81,157,278 elapsed=134.5s

  [8392/15692] intraday_2699.csv.gz  in=313,132,224 out=81,157,278 elapsed=134.5s

  [8393/15692] intraday_2700.csv.gz  in=313,145,630 out=81,157,278 elapsed=134.5s

  [8394/15692] intraday_2701.csv.gz  in=313,154,531 out=81,157,278 elapsed=134.5s

  [8395/15692] intraday_2702.csv.gz  in=313,165,847 out=81,157,278 elapsed=134.5s

  [8396/15692] intraday_2703.csv.gz  in=313,175,485 out=81,157,278 elapsed=134.5s

  [8397/15692] intraday_2705.csv.gz  in=313,187,989 out=81,157,278 elapsed=134.5s

  [8398/15692] intraday_2704.csv.gz  in=313,199,184 out=81,157,278 elapsed=134.5s

  [8399/15692] intraday_2706.csv.gz  in=313,212,498 out=81,157,278 elapsed=134.5s

  [8400/15692] intraday_2708.csv.gz  in=313,225,341 out=81,157,278 elapsed=134.6s

  [8401/15692] intraday_2709.csv.gz  in=313,236,506 out=81,157,278 elapsed=134.6s

  [8402/15692] intraday_2710.csv.gz  in=313,247,346 out=81,157,278 elapsed=134.6s

  [8403/15692] intraday_2707.csv.gz  in=313,263,318 out=81,157,278 elapsed=134.6s

  [8404/15692] intraday_2711.csv.gz  in=313,274,811 out=81,157,278 elapsed=134.6s

  [8405/15692] intraday_2713.csv.gz  in=313,286,143 out=81,157,278 elapsed=134.6s

  [8406/15692] intraday_2714.csv.gz  in=313,295,843 out=81,157,278 elapsed=134.6s

  [8407/15692] intraday_2712.csv.gz  in=313,322,846 out=81,157,278 elapsed=134.7s

  [8408/15692] intraday_2715.csv.gz  in=313,334,025 out=81,157,278 elapsed=134.7s

  [8409/15692] intraday_2717.csv.gz  in=313,348,648 out=81,157,278 elapsed=134.7s

  [8410/15692] intraday_2716.csv.gz  in=313,358,592 out=81,157,278 elapsed=134.7s

  [8411/15692] intraday_2718.csv.gz  in=313,368,983 out=81,157,278 elapsed=134.7s

  [8412/15692] intraday_2719.csv.gz  in=313,381,520 out=81,157,278 elapsed=134.7s

  [8413/15692] intraday_2720.csv.gz  in=313,393,463 out=81,157,278 elapsed=134.7s

  [8414/15692] intraday_2721.csv.gz  in=313,402,379 out=81,157,278 elapsed=134.7s

  [8415/15692] intraday_2722.csv.gz  in=313,414,783 out=81,157,278 elapsed=134.7s

  [8416/15692] intraday_2723.csv.gz  in=313,426,454 out=81,157,278 elapsed=134.8s

  [8417/15692] intraday_2724.csv.gz  in=313,440,784 out=81,157,278 elapsed=134.8s

  [8418/15692] intraday_2725.csv.gz  in=313,451,822 out=81,157,278 elapsed=134.8s

  [8419/15692] intraday_2726.csv.gz  in=313,463,230 out=81,157,278 elapsed=134.8s

  [8420/15692] intraday_2727.csv.gz  in=313,472,642 out=81,157,278 elapsed=134.8s

  [8421/15692] intraday_2730.csv.gz  in=313,482,248 out=81,157,278 elapsed=134.8s

  [8422/15692] intraday_2728.csv.gz  in=313,493,988 out=81,157,278 elapsed=134.8s

  [8423/15692] intraday_2729.csv.gz  in=313,508,195 out=81,157,278 elapsed=134.8s

  [8424/15692] intraday_2731.csv.gz  in=313,521,576 out=81,157,278 elapsed=134.8s

  [8425/15692] intraday_2733.csv.gz  in=313,530,807 out=81,157,278 elapsed=134.8s

  [8426/15692] intraday_2732.csv.gz  in=313,543,416 out=81,157,278 elapsed=134.8s

  [8427/15692] intraday_2734.csv.gz  in=313,566,633 out=81,157,278 elapsed=134.8s

  [8428/15692] intraday_2735.csv.gz  in=313,577,852 out=81,157,278 elapsed=134.9s

  [8429/15692] intraday_2737.csv.gz  in=313,587,560 out=81,157,278 elapsed=134.9s

  [8430/15692] intraday_2736.csv.gz  in=313,599,676 out=81,157,278 elapsed=134.9s

  [8431/15692] intraday_2738.csv.gz  in=313,610,250 out=81,157,278 elapsed=134.9s

  [8432/15692] intraday_2739.csv.gz  in=313,621,327 out=81,157,278 elapsed=134.9s

  [8433/15692] intraday_2740.csv.gz  in=313,632,380 out=81,157,278 elapsed=134.9s

  [8434/15692] intraday_2741.csv.gz  in=313,644,047 out=81,157,278 elapsed=134.9s

  [8435/15692] intraday_2742.csv.gz  in=313,655,481 out=81,157,278 elapsed=134.9s

  [8436/15692] intraday_2744.csv.gz  in=313,665,697 out=81,157,278 elapsed=134.9s

  [8437/15692] intraday_2743.csv.gz  in=313,677,375 out=81,157,278 elapsed=134.9s

  [8438/15692] intraday_2745.csv.gz  in=313,687,743 out=81,157,278 elapsed=134.9s

  [8439/15692] intraday_2746.csv.gz  in=313,700,588 out=81,157,278 elapsed=134.9s

  [8440/15692] intraday_2748.csv.gz  in=313,711,603 out=81,157,278 elapsed=134.9s

  [8441/15692] intraday_2747.csv.gz  in=313,726,285 out=81,157,278 elapsed=135.0s

  [8442/15692] intraday_2750.csv.gz  in=313,736,691 out=81,157,278 elapsed=135.0s

  [8443/15692] intraday_2749.csv.gz  in=313,745,482 out=81,157,278 elapsed=135.0s

  [8444/15692] intraday_2751.csv.gz  in=313,757,277 out=81,157,278 elapsed=135.0s

  [8445/15692] intraday_2753.csv.gz  in=313,770,909 out=81,157,278 elapsed=135.0s

  [8446/15692] intraday_2752.csv.gz  in=313,782,914 out=81,157,278 elapsed=135.0s

  [8447/15692] intraday_2754.csv.gz  in=313,794,382 out=81,157,278 elapsed=135.0s

  [8448/15692] intraday_2755.csv.gz  in=313,806,960 out=81,157,278 elapsed=135.0s

  [8449/15692] intraday_2757.csv.gz  in=313,819,899 out=81,157,278 elapsed=135.0s

  [8450/15692] intraday_2756.csv.gz  in=313,831,949 out=81,157,278 elapsed=135.0s

  [8451/15692] intraday_2758.csv.gz  in=313,843,736 out=81,157,278 elapsed=135.0s

  [8452/15692] intraday_2759.csv.gz  in=313,855,336 out=81,157,278 elapsed=135.0s

  [8453/15692] intraday_2760.csv.gz  in=313,867,501 out=81,157,278 elapsed=135.1s

  [8454/15692] intraday_2761.csv.gz  in=313,878,603 out=81,157,278 elapsed=135.1s

  [8455/15692] intraday_2762.csv.gz  in=313,890,451 out=81,157,278 elapsed=135.1s

  [8456/15692] intraday_2763.csv.gz  in=313,902,142 out=81,157,278 elapsed=135.1s

  [8457/15692] intraday_2764.csv.gz  in=313,912,086 out=81,157,278 elapsed=135.1s

  [8458/15692] intraday_2766.csv.gz  in=313,922,634 out=81,157,278 elapsed=135.1s

  [8459/15692] intraday_2765.csv.gz  in=313,934,692 out=81,157,278 elapsed=135.1s

  [8460/15692] intraday_2767.csv.gz  in=313,946,142 out=81,157,278 elapsed=135.1s

  [8461/15692] intraday_2769.csv.gz  in=313,955,501 out=81,157,278 elapsed=135.1s

  [8462/15692] intraday_2768.csv.gz  in=313,969,050 out=81,157,278 elapsed=135.1s

  [8463/15692] intraday_2770.csv.gz  in=313,984,696 out=81,157,278 elapsed=135.1s

  [8464/15692] intraday_2771.csv.gz  in=313,999,115 out=81,157,278 elapsed=135.1s

  [8465/15692] intraday_2772.csv.gz  in=314,012,929 out=81,157,278 elapsed=135.1s

  [8466/15692] intraday_2773.csv.gz  in=314,025,492 out=81,157,278 elapsed=135.1s

  [8467/15692] intraday_2774.csv.gz  in=314,037,638 out=81,157,278 elapsed=135.2s

  [8468/15692] intraday_2775.csv.gz  in=314,049,421 out=81,157,278 elapsed=135.2s

  [8469/15692] intraday_2776.csv.gz  in=314,062,132 out=81,157,278 elapsed=135.2s

  [8470/15692] intraday_2777.csv.gz  in=314,083,574 out=81,157,278 elapsed=135.2s

  [8471/15692] intraday_2778.csv.gz  in=314,094,519 out=81,157,278 elapsed=135.2s

  [8472/15692] intraday_2779.csv.gz  in=314,107,462 out=81,157,278 elapsed=135.2s

  [8473/15692] intraday_2780.csv.gz  in=314,122,971 out=81,157,278 elapsed=135.2s

  [8474/15692] intraday_2782.csv.gz  in=314,135,879 out=81,157,278 elapsed=135.2s

  [8475/15692] intraday_2781.csv.gz  in=314,147,920 out=81,157,278 elapsed=135.2s

  [8476/15692] intraday_2784.csv.gz  in=314,159,520 out=81,157,278 elapsed=135.2s

  [8477/15692] intraday_2783.csv.gz  in=314,170,862 out=81,157,278 elapsed=135.2s

  [8478/15692] intraday_2786.csv.gz  in=314,184,142 out=81,157,278 elapsed=135.3s

  [8479/15692] intraday_2785.csv.gz  in=314,195,786 out=81,157,278 elapsed=135.3s

  [8480/15692] intraday_2787.csv.gz  in=314,208,019 out=81,157,278 elapsed=135.3s

  [8481/15692] intraday_2788.csv.gz  in=314,223,891 out=81,157,278 elapsed=135.3s

  [8482/15692] intraday_2789.csv.gz  in=314,234,410 out=81,157,278 elapsed=135.3s

  [8483/15692] intraday_2790.csv.gz  in=314,246,847 out=81,157,278 elapsed=135.3s

  [8484/15692] intraday_2793.csv.gz  in=314,258,053 out=81,157,278 elapsed=135.3s

  [8485/15692] intraday_2792.csv.gz  in=314,270,982 out=81,157,278 elapsed=135.3s

  [8486/15692] intraday_2791.csv.gz  in=314,282,976 out=81,157,278 elapsed=135.3s

  [8487/15692] intraday_2794.csv.gz  in=314,298,111 out=81,157,278 elapsed=135.3s

  [8488/15692] intraday_2796.csv.gz  in=314,311,217 out=81,157,278 elapsed=135.3s

  [8489/15692] intraday_2798.csv.gz  in=314,322,184 out=81,157,278 elapsed=135.4s

  [8490/15692] intraday_2797.csv.gz  in=314,335,730 out=81,157,278 elapsed=135.4s

  [8491/15692] intraday_2795.csv.gz  in=314,352,534 out=81,157,278 elapsed=135.4s

  [8492/15692] intraday_2799.csv.gz  in=314,362,613 out=81,157,278 elapsed=135.4s

  [8493/15692] intraday_2800.csv.gz  in=314,374,462 out=81,157,278 elapsed=135.4s

  [8494/15692] intraday_2801.csv.gz  in=314,386,517 out=81,157,278 elapsed=135.4s

  [8495/15692] intraday_2802.csv.gz  in=314,394,458 out=81,157,278 elapsed=135.4s

  [8496/15692] intraday_2803.csv.gz  in=314,402,766 out=81,157,278 elapsed=135.4s

  [8497/15692] intraday_2805.csv.gz  in=314,405,029 out=81,157,278 elapsed=135.4s

  [8498/15692] intraday_2804.csv.gz  in=314,415,972 out=81,157,278 elapsed=135.4s

  [8499/15692] intraday_2806.csv.gz  in=314,431,541 out=81,157,278 elapsed=135.4s

  [8500/15692] intraday_2807.csv.gz  in=314,446,407 out=81,157,278 elapsed=135.4s

  [8501/15692] intraday_2808.csv.gz  in=314,459,541 out=81,157,278 elapsed=135.4s

  [8502/15692] intraday_2809.csv.gz  in=314,470,322 out=81,157,278 elapsed=135.5s

  [8503/15692] intraday_2810.csv.gz  in=314,485,141 out=81,157,278 elapsed=135.5s

  [8504/15692] intraday_2812.csv.gz  in=314,497,725 out=81,157,278 elapsed=135.5s

  [8505/15692] intraday_2811.csv.gz  in=314,511,462 out=81,157,278 elapsed=135.5s

  [8506/15692] intraday_2813.csv.gz  in=314,523,494 out=81,157,278 elapsed=135.5s

  [8507/15692] intraday_2814.csv.gz  in=314,537,515 out=81,157,278 elapsed=135.5s

  [8508/15692] intraday_2816.csv.gz  in=314,546,495 out=81,157,278 elapsed=135.5s

  [8509/15692] intraday_2815.csv.gz  in=314,560,448 out=81,157,278 elapsed=135.5s

  [8510/15692] intraday_2817.csv.gz  in=314,573,586 out=81,157,278 elapsed=135.5s

  [8511/15692] intraday_2818.csv.gz  in=314,585,873 out=81,157,278 elapsed=135.5s

  [8512/15692] intraday_2820.csv.gz  in=314,596,895 out=81,157,278 elapsed=135.5s

  [8513/15692] intraday_2819.csv.gz  in=314,607,937 out=81,157,278 elapsed=135.6s

  [8514/15692] intraday_2821.csv.gz  in=314,619,078 out=81,157,278 elapsed=135.6s

  [8515/15692] intraday_2822.csv.gz  in=314,631,959 out=81,157,278 elapsed=135.6s

  [8516/15692] intraday_2824.csv.gz  in=314,642,716 out=81,157,278 elapsed=135.6s

  [8517/15692] intraday_2823.csv.gz  in=314,655,016 out=81,157,278 elapsed=135.6s

  [8518/15692] intraday_2825.csv.gz  in=314,667,861 out=81,157,278 elapsed=135.6s

  [8519/15692] intraday_2826.csv.gz  in=314,680,714 out=81,157,278 elapsed=135.6s

  [8520/15692] intraday_2827.csv.gz  in=314,692,626 out=81,157,278 elapsed=135.6s

  [8521/15692] intraday_2828.csv.gz  in=314,705,153 out=81,157,278 elapsed=135.6s

  [8522/15692] intraday_2829.csv.gz  in=314,718,055 out=81,157,278 elapsed=135.6s

  [8523/15692] intraday_2831.csv.gz  in=314,727,835 out=81,157,278 elapsed=135.7s

  [8524/15692] intraday_2833.csv.gz  in=314,740,062 out=81,157,278 elapsed=135.7s

  [8525/15692] intraday_2830.csv.gz  in=314,761,234 out=81,157,278 elapsed=135.7s

  [8526/15692] intraday_2832.csv.gz  in=314,773,143 out=81,157,278 elapsed=135.7s

  [8527/15692] intraday_2836.csv.gz  in=314,786,597 out=81,157,278 elapsed=135.7s

  [8528/15692] intraday_2837.csv.gz  in=314,799,924 out=81,157,278 elapsed=135.7s

  [8529/15692] intraday_2834.csv.gz  in=314,818,916 out=81,157,278 elapsed=135.7s

  [8530/15692] intraday_2835.csv.gz  in=314,833,108 out=81,157,278 elapsed=135.7s

  [8531/15692] intraday_2838.csv.gz  in=314,845,953 out=81,157,278 elapsed=135.7s

  [8532/15692] intraday_2839.csv.gz  in=314,858,990 out=81,157,278 elapsed=135.7s

  [8533/15692] intraday_2841.csv.gz  in=314,871,681 out=81,157,278 elapsed=135.8s

  [8534/15692] intraday_2840.csv.gz  in=314,900,861 out=81,157,278 elapsed=135.8s

  [8535/15692] intraday_2842.csv.gz  in=314,911,181 out=81,157,278 elapsed=135.8s

  [8536/15692] intraday_2843.csv.gz  in=314,921,702 out=81,157,278 elapsed=135.8s

  [8537/15692] intraday_2844.csv.gz  in=314,932,670 out=81,157,278 elapsed=135.8s

  [8538/15692] intraday_2845.csv.gz  in=314,943,477 out=81,157,278 elapsed=135.8s

  [8539/15692] intraday_2846.csv.gz  in=314,957,683 out=81,157,278 elapsed=135.8s

  [8540/15692] intraday_2847.csv.gz  in=314,971,180 out=81,157,278 elapsed=135.8s

  [8541/15692] intraday_2848.csv.gz  in=314,983,155 out=81,157,278 elapsed=135.8s

  [8542/15692] intraday_2849.csv.gz  in=314,997,074 out=81,157,278 elapsed=135.8s

  [8543/15692] intraday_2852.csv.gz  in=315,008,137 out=81,157,278 elapsed=135.9s

  [8544/15692] intraday_2851.csv.gz  in=315,024,741 out=81,157,278 elapsed=135.9s

  [8545/15692] intraday_2850.csv.gz  in=315,052,142 out=81,157,278 elapsed=135.9s

  [8546/15692] intraday_2853.csv.gz  in=315,063,525 out=81,157,278 elapsed=135.9s

  [8547/15692] intraday_2856.csv.gz  in=315,075,591 out=81,157,278 elapsed=135.9s

  [8548/15692] intraday_2854.csv.gz  in=315,087,851 out=81,157,278 elapsed=135.9s

  [8549/15692] intraday_2855.csv.gz  in=315,098,473 out=81,157,278 elapsed=135.9s

  [8550/15692] intraday_2857.csv.gz  in=315,109,086 out=81,157,278 elapsed=135.9s

  [8551/15692] intraday_2860.csv.gz  in=315,121,718 out=81,157,278 elapsed=136.0s

  [8552/15692] intraday_2859.csv.gz  in=315,132,902 out=81,157,278 elapsed=136.0s

  [8553/15692] intraday_2861.csv.gz  in=315,144,815 out=81,157,278 elapsed=136.0s

  [8554/15692] intraday_2858.csv.gz  in=315,164,247 out=81,157,278 elapsed=136.0s

  [8555/15692] intraday_2863.csv.gz  in=315,176,951 out=81,157,278 elapsed=136.0s

  [8556/15692] intraday_2862.csv.gz  in=315,186,795 out=81,157,278 elapsed=136.0s

  [8557/15692] intraday_2865.csv.gz  in=315,199,774 out=81,157,278 elapsed=136.0s

  [8558/15692] intraday_2864.csv.gz  in=315,212,397 out=81,157,278 elapsed=136.0s

  [8559/15692] intraday_2869.csv.gz  in=315,224,879 out=81,157,278 elapsed=136.0s

  [8560/15692] intraday_2866.csv.gz  in=315,237,342 out=81,157,278 elapsed=136.0s

  [8561/15692] intraday_2867.csv.gz  in=315,248,735 out=81,157,278 elapsed=136.0s

  [8562/15692] intraday_2868.csv.gz  in=315,258,307 out=81,157,278 elapsed=136.0s

  [8563/15692] intraday_2872.csv.gz  in=315,272,278 out=81,157,278 elapsed=136.1s

  [8564/15692] intraday_2870.csv.gz  in=315,287,547 out=81,157,278 elapsed=136.1s

  [8565/15692] intraday_2871.csv.gz  in=315,297,789 out=81,157,278 elapsed=136.1s

  [8566/15692] intraday_2873.csv.gz  in=315,313,125 out=81,157,278 elapsed=136.1s

  [8567/15692] intraday_2876.csv.gz  in=315,326,307 out=81,157,278 elapsed=136.1s

  [8568/15692] intraday_2875.csv.gz  in=315,338,625 out=81,157,278 elapsed=136.1s

  [8569/15692] intraday_2874.csv.gz  in=315,348,526 out=81,157,278 elapsed=136.1s

  [8570/15692] intraday_2877.csv.gz  in=315,361,133 out=81,157,278 elapsed=136.1s

  [8571/15692] intraday_2878.csv.gz  in=315,371,691 out=81,157,278 elapsed=136.2s

  [8572/15692] intraday_2880.csv.gz  in=315,388,413 out=81,157,278 elapsed=136.2s

  [8573/15692] intraday_2879.csv.gz  in=315,399,643 out=81,157,278 elapsed=136.2s

  [8574/15692] intraday_2881.csv.gz  in=315,411,820 out=81,157,278 elapsed=136.2s

  [8575/15692] intraday_2882.csv.gz  in=315,423,829 out=81,157,278 elapsed=136.2s

  [8576/15692] intraday_2883.csv.gz  in=315,435,847 out=81,157,278 elapsed=136.2s

  [8577/15692] intraday_2885.csv.gz  in=315,446,418 out=81,157,278 elapsed=136.2s

  [8578/15692] intraday_2884.csv.gz  in=315,459,377 out=81,157,278 elapsed=136.2s

  [8579/15692] intraday_2886.csv.gz  in=315,470,051 out=81,157,278 elapsed=136.2s

  [8580/15692] intraday_2887.csv.gz  in=315,482,558 out=81,157,278 elapsed=136.2s

  [8581/15692] intraday_2888.csv.gz  in=315,499,304 out=81,157,278 elapsed=136.2s

  [8582/15692] intraday_2890.csv.gz  in=315,509,941 out=81,157,278 elapsed=136.3s

  [8583/15692] intraday_2889.csv.gz  in=315,520,447 out=81,157,278 elapsed=136.3s

  [8584/15692] intraday_2891.csv.gz  in=315,530,928 out=81,157,278 elapsed=136.3s

  [8585/15692] intraday_2893.csv.gz  in=315,542,263 out=81,157,278 elapsed=136.3s

  [8586/15692] intraday_2894.csv.gz  in=315,557,815 out=81,157,278 elapsed=136.3s

  [8587/15692] intraday_2892.csv.gz  in=315,570,333 out=81,157,278 elapsed=136.3s

  [8588/15692] intraday_2896.csv.gz  in=315,583,543 out=81,157,278 elapsed=136.3s

  [8589/15692] intraday_2895.csv.gz  in=315,594,799 out=81,157,278 elapsed=136.3s

  [8590/15692] intraday_2897.csv.gz  in=315,608,244 out=81,157,278 elapsed=136.3s

  [8591/15692] intraday_2899.csv.gz  in=315,620,346 out=81,157,278 elapsed=136.4s

  [8592/15692] intraday_2898.csv.gz  in=315,647,539 out=81,157,278 elapsed=136.4s

  [8593/15692] intraday_2900.csv.gz  in=315,659,945 out=81,157,278 elapsed=136.4s

  [8594/15692] intraday_2903.csv.gz  in=315,672,651 out=81,157,278 elapsed=136.4s

  [8595/15692] intraday_2901.csv.gz  in=315,696,960 out=81,157,278 elapsed=136.4s

  [8596/15692] intraday_2902.csv.gz  in=315,711,701 out=81,157,278 elapsed=136.4s

  [8597/15692] intraday_2904.csv.gz  in=315,725,714 out=81,157,278 elapsed=136.4s

  [8598/15692] intraday_2905.csv.gz  in=315,736,521 out=81,157,278 elapsed=136.4s

  [8599/15692] intraday_2906.csv.gz  in=315,748,985 out=81,157,278 elapsed=136.4s

  [8600/15692] intraday_2907.csv.gz  in=315,760,867 out=81,157,278 elapsed=136.4s

  [8601/15692] intraday_2908.csv.gz  in=315,785,591 out=81,157,278 elapsed=136.5s

  [8602/15692] intraday_2910.csv.gz  in=315,796,254 out=81,157,278 elapsed=136.5s

  [8603/15692] intraday_2909.csv.gz  in=315,809,512 out=81,157,278 elapsed=136.5s

  [8604/15692] intraday_2912.csv.gz  in=315,823,672 out=81,157,278 elapsed=136.5s

  [8605/15692] intraday_2911.csv.gz  in=315,834,893 out=81,157,278 elapsed=136.5s

  [8606/15692] intraday_2913.csv.gz  in=315,850,053 out=81,157,278 elapsed=136.5s

  [8607/15692] intraday_2914.csv.gz  in=315,862,886 out=81,157,278 elapsed=136.5s

  [8608/15692] intraday_2915.csv.gz  in=315,875,557 out=81,157,278 elapsed=136.5s

  [8609/15692] intraday_2916.csv.gz  in=315,889,545 out=81,157,278 elapsed=136.5s

  [8610/15692] intraday_2917.csv.gz  in=315,902,902 out=81,157,278 elapsed=136.5s

  [8611/15692] intraday_2919.csv.gz  in=315,915,140 out=81,157,278 elapsed=136.6s

  [8612/15692] intraday_2918.csv.gz  in=315,928,448 out=81,157,278 elapsed=136.6s

  [8613/15692] intraday_2920.csv.gz  in=315,942,884 out=81,157,278 elapsed=136.6s

  [8614/15692] intraday_2922.csv.gz  in=315,955,669 out=81,157,278 elapsed=136.6s

  [8615/15692] intraday_2923.csv.gz  in=315,968,797 out=81,157,278 elapsed=136.6s

  [8616/15692] intraday_2921.csv.gz  in=315,990,195 out=81,157,278 elapsed=136.6s

  [8617/15692] intraday_2924.csv.gz  in=316,002,618 out=81,157,278 elapsed=136.6s

  [8618/15692] intraday_2926.csv.gz  in=316,013,954 out=81,157,278 elapsed=136.6s

  [8619/15692] intraday_2927.csv.gz  in=316,027,796 out=81,157,278 elapsed=136.6s

  [8620/15692] intraday_2925.csv.gz  in=316,040,292 out=81,157,278 elapsed=136.6s

  [8621/15692] intraday_2928.csv.gz  in=316,053,301 out=81,157,278 elapsed=136.6s

  [8622/15692] intraday_2931.csv.gz  in=316,067,166 out=81,157,278 elapsed=136.7s

  [8623/15692] intraday_2930.csv.gz  in=316,079,544 out=81,157,278 elapsed=136.7s

  [8624/15692] intraday_2932.csv.gz  in=316,093,230 out=81,157,278 elapsed=136.7s

  [8625/15692] intraday_2929.csv.gz  in=316,109,879 out=81,157,278 elapsed=136.7s

  [8626/15692] intraday_2934.csv.gz  in=316,122,764 out=81,157,278 elapsed=136.7s

  [8627/15692] intraday_2933.csv.gz  in=316,135,209 out=81,157,278 elapsed=136.7s

  [8628/15692] intraday_2935.csv.gz  in=316,157,320 out=81,157,278 elapsed=136.7s

  [8629/15692] intraday_2936.csv.gz  in=316,172,448 out=81,157,278 elapsed=136.7s

  [8630/15692] intraday_2937.csv.gz  in=316,185,868 out=81,157,278 elapsed=136.7s

  [8631/15692] intraday_2938.csv.gz  in=316,200,395 out=81,157,278 elapsed=136.7s

  [8632/15692] intraday_2939.csv.gz  in=316,211,401 out=81,157,278 elapsed=136.8s

  [8633/15692] intraday_2941.csv.gz  in=316,224,343 out=81,157,278 elapsed=136.8s

  [8634/15692] intraday_2940.csv.gz  in=316,235,569 out=81,157,278 elapsed=136.8s

  [8635/15692] intraday_2942.csv.gz  in=316,247,497 out=81,157,278 elapsed=136.8s

  [8636/15692] intraday_2944.csv.gz  in=316,254,956 out=81,157,278 elapsed=136.8s

  [8637/15692] intraday_2943.csv.gz  in=316,265,903 out=81,157,278 elapsed=136.8s

  [8638/15692] intraday_2945.csv.gz  in=316,275,400 out=81,157,278 elapsed=136.8s

  [8639/15692] intraday_2946.csv.gz  in=316,281,551 out=81,157,278 elapsed=136.8s

  [8640/15692] intraday_2947.csv.gz  in=316,298,305 out=81,157,278 elapsed=136.8s

  [8641/15692] intraday_2948.csv.gz  in=316,313,435 out=81,157,278 elapsed=136.8s

  [8642/15692] intraday_2949.csv.gz  in=316,327,374 out=81,157,278 elapsed=136.8s

  [8643/15692] intraday_2951.csv.gz  in=316,342,456 out=81,157,278 elapsed=136.9s

  [8644/15692] intraday_2952.csv.gz  in=316,357,340 out=81,157,278 elapsed=136.9s

  [8645/15692] intraday_2950.csv.gz  in=316,368,381 out=81,157,278 elapsed=136.9s

  [8646/15692] intraday_2953.csv.gz  in=316,381,519 out=81,157,278 elapsed=136.9s

  [8647/15692] intraday_2954.csv.gz  in=316,394,747 out=81,157,278 elapsed=136.9s

  [8648/15692] intraday_2955.csv.gz  in=316,409,617 out=81,157,278 elapsed=136.9s

  [8649/15692] intraday_2956.csv.gz  in=316,424,187 out=81,157,278 elapsed=136.9s

  [8650/15692] intraday_2957.csv.gz  in=316,434,164 out=81,157,278 elapsed=136.9s

  [8651/15692] intraday_2958.csv.gz  in=316,448,139 out=81,157,278 elapsed=136.9s

  [8652/15692] intraday_2959.csv.gz  in=316,461,828 out=81,157,278 elapsed=136.9s

  [8653/15692] intraday_2962.csv.gz  in=316,473,221 out=81,157,278 elapsed=136.9s

  [8654/15692] intraday_2961.csv.gz  in=316,484,664 out=81,157,278 elapsed=136.9s

  [8655/15692] intraday_2960.csv.gz  in=316,497,135 out=81,157,278 elapsed=136.9s

  [8656/15692] intraday_2963.csv.gz  in=316,511,234 out=81,157,278 elapsed=137.0s

  [8657/15692] intraday_2964.csv.gz  in=316,524,192 out=81,157,278 elapsed=137.0s

  [8658/15692] intraday_2965.csv.gz  in=316,535,387 out=81,157,278 elapsed=137.0s

  [8659/15692] intraday_2966.csv.gz  in=316,548,436 out=81,157,278 elapsed=137.0s

  [8660/15692] intraday_2967.csv.gz  in=316,562,478 out=81,157,278 elapsed=137.0s

  [8661/15692] intraday_2968.csv.gz  in=316,574,721 out=81,157,278 elapsed=137.0s

  [8662/15692] intraday_2969.csv.gz  in=316,587,413 out=81,157,278 elapsed=137.0s

  [8663/15692] intraday_2970.csv.gz  in=316,605,650 out=81,157,278 elapsed=137.0s

  [8664/15692] intraday_2972.csv.gz  in=316,616,208 out=81,157,278 elapsed=137.0s

  [8665/15692] intraday_2971.csv.gz  in=316,628,709 out=81,157,278 elapsed=137.0s

  [8666/15692] intraday_2974.csv.gz  in=316,641,430 out=81,157,278 elapsed=137.0s

  [8667/15692] intraday_2973.csv.gz  in=316,654,521 out=81,157,278 elapsed=137.1s

  [8668/15692] intraday_2975.csv.gz  in=316,668,110 out=81,157,278 elapsed=137.1s

  [8669/15692] intraday_2976.csv.gz  in=316,683,986 out=81,157,278 elapsed=137.1s

  [8670/15692] intraday_2977.csv.gz  in=316,698,070 out=81,157,278 elapsed=137.1s

  [8671/15692] intraday_2979.csv.gz  in=316,713,028 out=81,157,278 elapsed=137.1s

  [8672/15692] intraday_2978.csv.gz  in=316,726,690 out=81,157,278 elapsed=137.1s

  [8673/15692] intraday_2981.csv.gz  in=316,742,575 out=81,157,278 elapsed=137.1s

  [8674/15692] intraday_2982.csv.gz  in=316,760,250 out=81,157,278 elapsed=137.1s

  [8675/15692] intraday_2980.csv.gz  in=316,791,208 out=81,157,278 elapsed=137.1s

  [8676/15692] intraday_2983.csv.gz  in=316,801,790 out=81,157,278 elapsed=137.1s

  [8677/15692] intraday_2984.csv.gz  in=316,814,640 out=81,157,278 elapsed=137.1s

  [8678/15692] intraday_2985.csv.gz  in=316,826,939 out=81,157,278 elapsed=137.2s

  [8679/15692] intraday_2987.csv.gz  in=316,841,470 out=81,157,278 elapsed=137.2s

  [8680/15692] intraday_2986.csv.gz  in=316,853,940 out=81,157,278 elapsed=137.2s

  [8681/15692] intraday_2989.csv.gz  in=316,866,113 out=81,157,278 elapsed=137.2s

  [8682/15692] intraday_2991.csv.gz  in=316,877,802 out=81,157,278 elapsed=137.2s

  [8683/15692] intraday_2988.csv.gz  in=316,891,895 out=81,157,278 elapsed=137.2s

  [8684/15692] intraday_2990.csv.gz  in=316,906,438 out=81,157,278 elapsed=137.2s

  [8685/15692] intraday_2992.csv.gz  in=316,919,766 out=81,157,278 elapsed=137.2s

  [8686/15692] intraday_2993.csv.gz  in=316,931,994 out=81,157,278 elapsed=137.2s

  [8687/15692] intraday_2994.csv.gz  in=316,944,118 out=81,157,278 elapsed=137.3s

  [8688/15692] intraday_2995.csv.gz  in=316,956,698 out=81,157,278 elapsed=137.3s

  [8689/15692] intraday_2996.csv.gz  in=316,968,305 out=81,157,278 elapsed=137.3s

  [8690/15692] intraday_2997.csv.gz  in=316,981,311 out=81,157,278 elapsed=137.3s

  [8691/15692] intraday_2998.csv.gz  in=316,993,591 out=81,157,278 elapsed=137.3s

  [8692/15692] intraday_2999.csv.gz  in=317,006,173 out=81,157,278 elapsed=137.3s

  [8693/15692] intraday_3000.csv.gz  in=317,018,244 out=81,157,278 elapsed=137.3s

  [8694/15692] intraday_3002.csv.gz  in=317,030,783 out=81,157,278 elapsed=137.3s

  [8695/15692] intraday_3001.csv.gz  in=317,044,659 out=81,157,278 elapsed=137.4s

  [8696/15692] intraday_3003.csv.gz  in=317,055,638 out=81,157,278 elapsed=137.4s

  [8697/15692] intraday_3004.csv.gz  in=317,069,662 out=81,157,278 elapsed=137.4s

  [8698/15692] intraday_3005.csv.gz  in=317,083,632 out=81,157,278 elapsed=137.4s

  [8699/15692] intraday_3006.csv.gz  in=317,096,405 out=81,157,278 elapsed=137.4s

  [8700/15692] intraday_3007.csv.gz  in=317,109,087 out=81,157,278 elapsed=137.4s

  [8701/15692] intraday_3008.csv.gz  in=317,121,422 out=81,157,278 elapsed=137.4s

  [8702/15692] intraday_3009.csv.gz  in=317,131,550 out=81,157,278 elapsed=137.4s

  [8703/15692] intraday_3010.csv.gz  in=317,144,597 out=81,157,278 elapsed=137.4s

  [8704/15692] intraday_3011.csv.gz  in=317,161,134 out=81,157,278 elapsed=137.4s

  [8705/15692] intraday_3012.csv.gz  in=317,172,131 out=81,157,278 elapsed=137.4s

  [8706/15692] intraday_3013.csv.gz  in=317,185,872 out=81,157,278 elapsed=137.4s

  [8707/15692] intraday_3015.csv.gz  in=317,195,240 out=81,157,278 elapsed=137.5s

  [8708/15692] intraday_3014.csv.gz  in=317,210,054 out=81,157,278 elapsed=137.5s

  [8709/15692] intraday_3016.csv.gz  in=317,223,882 out=81,157,278 elapsed=137.5s

  [8710/15692] intraday_3017.csv.gz  in=317,237,267 out=81,157,278 elapsed=137.5s

  [8711/15692] intraday_3018.csv.gz  in=317,251,466 out=81,157,278 elapsed=137.5s

  [8712/15692] intraday_3019.csv.gz  in=317,262,336 out=81,157,278 elapsed=137.5s

  [8713/15692] intraday_3020.csv.gz  in=317,273,849 out=81,157,278 elapsed=137.5s

  [8714/15692] intraday_3021.csv.gz  in=317,285,934 out=81,157,278 elapsed=137.5s

  [8715/15692] intraday_3022.csv.gz  in=317,298,926 out=81,157,278 elapsed=137.5s

  [8716/15692] intraday_3024.csv.gz  in=317,311,092 out=81,157,278 elapsed=137.5s

  [8717/15692] intraday_3023.csv.gz  in=317,324,577 out=81,157,278 elapsed=137.6s

  [8718/15692] intraday_3025.csv.gz  in=317,338,526 out=81,157,278 elapsed=137.6s

  [8719/15692] intraday_3026.csv.gz  in=317,349,335 out=81,157,278 elapsed=137.6s

  [8720/15692] intraday_3027.csv.gz  in=317,360,303 out=81,157,278 elapsed=137.6s

  [8721/15692] intraday_3029.csv.gz  in=317,377,680 out=81,157,278 elapsed=137.6s

  [8722/15692] intraday_3028.csv.gz  in=317,391,381 out=81,157,278 elapsed=137.6s

  [8723/15692] intraday_3030.csv.gz  in=317,402,499 out=81,157,278 elapsed=137.6s

  [8724/15692] intraday_3031.csv.gz  in=317,414,242 out=81,157,278 elapsed=137.6s

  [8725/15692] intraday_3033.csv.gz  in=317,428,059 out=81,157,278 elapsed=137.6s

  [8726/15692] intraday_3034.csv.gz  in=317,440,369 out=81,157,278 elapsed=137.6s

  [8727/15692] intraday_3032.csv.gz  in=317,450,927 out=81,157,278 elapsed=137.6s

  [8728/15692] intraday_3037.csv.gz  in=317,467,339 out=81,157,278 elapsed=137.7s

  [8729/15692] intraday_3036.csv.gz  in=317,491,000 out=81,157,278 elapsed=137.7s

  [8730/15692] intraday_3035.csv.gz  in=317,521,117 out=81,157,278 elapsed=137.7s

  [8731/15692] intraday_3038.csv.gz  in=317,534,657 out=81,157,278 elapsed=137.7s

  [8732/15692] intraday_3042.csv.gz  in=317,549,470 out=81,157,278 elapsed=137.7s

  [8733/15692] intraday_3040.csv.gz  in=317,562,747 out=81,157,278 elapsed=137.7s

  [8734/15692] intraday_3039.csv.gz  in=317,577,708 out=81,157,278 elapsed=137.7s

  [8735/15692] intraday_3041.csv.gz  in=317,591,035 out=81,157,278 elapsed=137.7s

  [8736/15692] intraday_3043.csv.gz  in=317,603,760 out=81,157,278 elapsed=137.7s

  [8737/15692] intraday_3044.csv.gz  in=317,616,809 out=81,157,278 elapsed=137.7s

  [8738/15692] intraday_3046.csv.gz  in=317,629,624 out=81,157,278 elapsed=137.8s

  [8739/15692] intraday_3045.csv.gz  in=317,642,692 out=81,157,278 elapsed=137.8s

  [8740/15692] intraday_3047.csv.gz  in=317,655,166 out=81,157,278 elapsed=137.8s

  [8741/15692] intraday_3048.csv.gz  in=317,668,216 out=81,157,278 elapsed=137.8s

  [8742/15692] intraday_3050.csv.gz  in=317,681,794 out=81,157,278 elapsed=137.8s

  [8743/15692] intraday_3049.csv.gz  in=317,694,918 out=81,157,278 elapsed=137.8s

  [8744/15692] intraday_3051.csv.gz  in=317,707,385 out=81,157,278 elapsed=137.8s

  [8745/15692] intraday_3052.csv.gz  in=317,719,512 out=81,157,278 elapsed=137.8s

  [8746/15692] intraday_3054.csv.gz  in=317,734,867 out=81,157,278 elapsed=137.8s

  [8747/15692] intraday_3053.csv.gz  in=317,750,092 out=81,157,278 elapsed=137.8s

  [8748/15692] intraday_3056.csv.gz  in=317,763,309 out=81,157,278 elapsed=137.9s

  [8749/15692] intraday_3055.csv.gz  in=317,780,545 out=81,157,278 elapsed=137.9s

  [8750/15692] intraday_3057.csv.gz  in=317,795,014 out=81,157,278 elapsed=137.9s

  [8751/15692] intraday_3058.csv.gz  in=317,809,189 out=81,157,278 elapsed=137.9s

  [8752/15692] intraday_3059.csv.gz  in=317,823,039 out=81,157,278 elapsed=137.9s

  [8753/15692] intraday_3060.csv.gz  in=317,836,584 out=81,157,278 elapsed=137.9s

  [8754/15692] intraday_3062.csv.gz  in=317,853,486 out=81,157,278 elapsed=137.9s

  [8755/15692] intraday_3061.csv.gz  in=317,867,769 out=81,157,278 elapsed=137.9s

  [8756/15692] intraday_3063.csv.gz  in=317,880,639 out=81,157,278 elapsed=137.9s

  [8757/15692] intraday_3064.csv.gz  in=317,895,463 out=81,157,278 elapsed=138.0s

  [8758/15692] intraday_3065.csv.gz  in=317,909,096 out=81,157,278 elapsed=138.0s

  [8759/15692] intraday_3066.csv.gz  in=317,922,697 out=81,157,278 elapsed=138.0s

  [8760/15692] intraday_3067.csv.gz  in=317,934,416 out=81,157,278 elapsed=138.0s

  [8761/15692] intraday_3068.csv.gz  in=317,947,550 out=81,157,278 elapsed=138.0s

  [8762/15692] intraday_3069.csv.gz  in=317,963,980 out=81,157,278 elapsed=138.0s

  [8763/15692] intraday_3071.csv.gz  in=317,978,634 out=81,157,278 elapsed=138.0s

  [8764/15692] intraday_3072.csv.gz  in=317,992,266 out=81,157,278 elapsed=138.0s

  [8765/15692] intraday_3070.csv.gz  in=318,008,160 out=81,157,278 elapsed=138.0s

  [8766/15692] intraday_3073.csv.gz  in=318,023,121 out=81,157,278 elapsed=138.1s

  [8767/15692] intraday_3075.csv.gz  in=318,036,555 out=81,157,278 elapsed=138.1s

  [8768/15692] intraday_3074.csv.gz  in=318,051,119 out=81,157,278 elapsed=138.1s

  [8769/15692] intraday_3076.csv.gz  in=318,065,802 out=81,157,278 elapsed=138.1s

  [8770/15692] intraday_3077.csv.gz  in=318,081,340 out=81,157,278 elapsed=138.1s

  [8771/15692] intraday_3078.csv.gz  in=318,096,428 out=81,157,278 elapsed=138.1s

  [8772/15692] intraday_3079.csv.gz  in=318,113,301 out=81,157,278 elapsed=138.1s

  [8773/15692] intraday_3080.csv.gz  in=318,126,252 out=81,157,278 elapsed=138.1s

  [8774/15692] intraday_3081.csv.gz  in=318,136,980 out=81,157,278 elapsed=138.1s

  [8775/15692] intraday_3083.csv.gz  in=318,149,192 out=81,157,278 elapsed=138.1s

  [8776/15692] intraday_3082.csv.gz  in=318,162,646 out=81,157,278 elapsed=138.1s

  [8777/15692] intraday_3084.csv.gz  in=318,175,138 out=81,157,278 elapsed=138.1s

  [8778/15692] intraday_3085.csv.gz  in=318,183,271 out=81,157,278 elapsed=138.2s

  [8779/15692] intraday_3087.csv.gz  in=318,190,233 out=81,157,278 elapsed=138.2s

  [8780/15692] intraday_3086.csv.gz  in=318,200,908 out=81,157,278 elapsed=138.2s

  [8781/15692] intraday_3088.csv.gz  in=318,215,235 out=81,157,278 elapsed=138.2s

  [8782/15692] intraday_3089.csv.gz  in=318,229,468 out=81,157,278 elapsed=138.2s

  [8783/15692] intraday_3091.csv.gz  in=318,239,715 out=81,157,278 elapsed=138.2s

  [8784/15692] intraday_3090.csv.gz  in=318,252,027 out=81,157,278 elapsed=138.2s

  [8785/15692] intraday_3093.csv.gz  in=318,266,309 out=81,157,278 elapsed=138.2s

  [8786/15692] intraday_3092.csv.gz  in=318,283,006 out=81,157,278 elapsed=138.2s

  [8787/15692] intraday_3095.csv.gz  in=318,295,150 out=81,157,278 elapsed=138.2s

  [8788/15692] intraday_3094.csv.gz  in=318,307,638 out=81,157,278 elapsed=138.3s

  [8789/15692] intraday_3096.csv.gz  in=318,321,020 out=81,157,278 elapsed=138.3s

  [8790/15692] intraday_3097.csv.gz  in=318,334,376 out=81,157,278 elapsed=138.3s

  [8791/15692] intraday_3098.csv.gz  in=318,344,113 out=81,157,278 elapsed=138.3s

  [8792/15692] intraday_3099.csv.gz  in=318,356,136 out=81,157,278 elapsed=138.3s

  [8793/15692] intraday_3100.csv.gz  in=318,368,625 out=81,157,278 elapsed=138.3s

  [8794/15692] intraday_3101.csv.gz  in=318,380,800 out=81,157,278 elapsed=138.3s

  [8795/15692] intraday_3102.csv.gz  in=318,391,901 out=81,157,278 elapsed=138.3s

  [8796/15692] intraday_3103.csv.gz  in=318,401,978 out=81,157,278 elapsed=138.3s

  [8797/15692] intraday_3104.csv.gz  in=318,415,272 out=81,157,278 elapsed=138.3s

  [8798/15692] intraday_3105.csv.gz  in=318,427,166 out=81,157,278 elapsed=138.3s

  [8799/15692] intraday_3107.csv.gz  in=318,438,863 out=81,157,278 elapsed=138.3s

  [8800/15692] intraday_3106.csv.gz  in=318,449,355 out=81,157,278 elapsed=138.3s

  [8801/15692] intraday_3108.csv.gz  in=318,462,503 out=81,157,278 elapsed=138.3s

  [8802/15692] intraday_3109.csv.gz  in=318,473,603 out=81,157,278 elapsed=138.3s

  [8803/15692] intraday_3110.csv.gz  in=318,486,424 out=81,157,278 elapsed=138.4s

  [8804/15692] intraday_3111.csv.gz  in=318,499,448 out=81,157,278 elapsed=138.4s

  [8805/15692] intraday_3113.csv.gz  in=318,509,455 out=81,157,278 elapsed=138.4s

  [8806/15692] intraday_3112.csv.gz  in=318,522,015 out=81,157,278 elapsed=138.4s

  [8807/15692] intraday_3114.csv.gz  in=318,533,937 out=81,157,278 elapsed=138.4s

  [8808/15692] intraday_3116.csv.gz  in=318,545,915 out=81,157,278 elapsed=138.4s

  [8809/15692] intraday_3115.csv.gz  in=318,558,457 out=81,157,278 elapsed=138.4s

  [8810/15692] intraday_3118.csv.gz  in=318,571,792 out=81,157,278 elapsed=138.4s

  [8811/15692] intraday_3117.csv.gz  in=318,586,047 out=81,157,278 elapsed=138.4s

  [8812/15692] intraday_3120.csv.gz  in=318,597,905 out=81,157,278 elapsed=138.5s

  [8813/15692] intraday_3121.csv.gz  in=318,610,883 out=81,157,278 elapsed=138.5s

  [8814/15692] intraday_3119.csv.gz  in=318,623,702 out=81,157,278 elapsed=138.5s

  [8815/15692] intraday_3122.csv.gz  in=318,635,872 out=81,157,278 elapsed=138.5s

  [8816/15692] intraday_3123.csv.gz  in=318,648,778 out=81,157,278 elapsed=138.5s

  [8817/15692] intraday_3125.csv.gz  in=318,659,591 out=81,157,278 elapsed=138.5s

  [8818/15692] intraday_3124.csv.gz  in=318,670,084 out=81,157,278 elapsed=138.5s

  [8819/15692] intraday_3126.csv.gz  in=318,680,538 out=81,157,278 elapsed=138.5s

  [8820/15692] intraday_3127.csv.gz  in=318,697,851 out=81,157,278 elapsed=138.5s

  [8821/15692] intraday_3130.csv.gz  in=318,709,339 out=81,157,278 elapsed=138.6s

  [8822/15692] intraday_3128.csv.gz  in=318,722,720 out=81,157,278 elapsed=138.6s

  [8823/15692] intraday_3129.csv.gz  in=318,736,061 out=81,157,278 elapsed=138.6s

  [8824/15692] intraday_3132.csv.gz  in=318,746,975 out=81,157,278 elapsed=138.6s

  [8825/15692] intraday_3131.csv.gz  in=318,759,881 out=81,157,278 elapsed=138.6s

  [8826/15692] intraday_3133.csv.gz  in=318,772,197 out=81,157,278 elapsed=138.6s

  [8827/15692] intraday_3134.csv.gz  in=318,784,060 out=81,157,278 elapsed=138.6s

  [8828/15692] intraday_3135.csv.gz  in=318,794,869 out=81,157,278 elapsed=138.6s

  [8829/15692] intraday_3137.csv.gz  in=318,805,640 out=81,157,278 elapsed=138.6s

  [8830/15692] intraday_3136.csv.gz  in=318,817,777 out=81,157,278 elapsed=138.6s

  [8831/15692] intraday_3139.csv.gz  in=318,828,318 out=81,157,278 elapsed=138.6s

  [8832/15692] intraday_3138.csv.gz  in=318,840,497 out=81,157,278 elapsed=138.6s

  [8833/15692] intraday_3140.csv.gz  in=318,854,503 out=81,157,278 elapsed=138.6s

  [8834/15692] intraday_3142.csv.gz  in=318,867,547 out=81,157,278 elapsed=138.7s

  [8835/15692] intraday_3141.csv.gz  in=318,877,535 out=81,157,278 elapsed=138.7s

  [8836/15692] intraday_3144.csv.gz  in=318,888,467 out=81,157,278 elapsed=138.7s

  [8837/15692] intraday_3143.csv.gz  in=318,901,272 out=81,157,278 elapsed=138.7s

  [8838/15692] intraday_3146.csv.gz  in=318,913,319 out=81,157,278 elapsed=138.7s

  [8839/15692] intraday_3145.csv.gz  in=318,925,305 out=81,157,278 elapsed=138.7s

  [8840/15692] intraday_3150.csv.gz  in=318,934,913 out=81,157,278 elapsed=138.7s

  [8841/15692] intraday_3149.csv.gz  in=318,947,140 out=81,157,278 elapsed=138.7s

  [8842/15692] intraday_3147.csv.gz  in=318,958,710 out=81,157,278 elapsed=138.7s

  [8843/15692] intraday_3148.csv.gz  in=318,970,300 out=81,157,278 elapsed=138.7s

  [8844/15692] intraday_3151.csv.gz  in=318,982,345 out=81,157,278 elapsed=138.7s

  [8845/15692] intraday_3152.csv.gz  in=318,996,075 out=81,157,278 elapsed=138.7s

  [8846/15692] intraday_3153.csv.gz  in=319,007,166 out=81,157,278 elapsed=138.7s

  [8847/15692] intraday_3154.csv.gz  in=319,020,845 out=81,157,278 elapsed=138.8s

  [8848/15692] intraday_3155.csv.gz  in=319,033,960 out=81,157,278 elapsed=138.8s

  [8849/15692] intraday_3156.csv.gz  in=319,042,396 out=81,157,278 elapsed=138.8s

  [8850/15692] intraday_3158.csv.gz  in=319,054,387 out=81,157,278 elapsed=138.8s

  [8851/15692] intraday_3157.csv.gz  in=319,067,268 out=81,157,278 elapsed=138.8s

  [8852/15692] intraday_3159.csv.gz  in=319,079,142 out=81,157,278 elapsed=138.8s

  [8853/15692] intraday_3160.csv.gz  in=319,090,039 out=81,157,278 elapsed=138.8s

  [8854/15692] intraday_3161.csv.gz  in=319,100,665 out=81,157,278 elapsed=138.8s

  [8855/15692] intraday_3163.csv.gz  in=319,111,241 out=81,157,278 elapsed=138.8s

  [8856/15692] intraday_3162.csv.gz  in=319,121,754 out=81,157,278 elapsed=138.8s

  [8857/15692] intraday_3164.csv.gz  in=319,134,335 out=81,157,278 elapsed=138.8s

  [8858/15692] intraday_3165.csv.gz  in=319,145,799 out=81,157,278 elapsed=138.9s

  [8859/15692] intraday_3168.csv.gz  in=319,156,099 out=81,157,278 elapsed=138.9s

  [8860/15692] intraday_3166.csv.gz  in=319,168,414 out=81,157,278 elapsed=138.9s

  [8861/15692] intraday_3167.csv.gz  in=319,179,368 out=81,157,278 elapsed=138.9s

  [8862/15692] intraday_3169.csv.gz  in=319,192,865 out=81,157,278 elapsed=138.9s

  [8863/15692] intraday_3171.csv.gz  in=319,202,168 out=81,157,278 elapsed=138.9s

  [8864/15692] intraday_3170.csv.gz  in=319,217,796 out=81,157,278 elapsed=138.9s

  [8865/15692] intraday_3172.csv.gz  in=319,230,209 out=81,157,278 elapsed=138.9s

  [8866/15692] intraday_3173.csv.gz  in=319,239,931 out=81,157,278 elapsed=138.9s

  [8867/15692] intraday_3174.csv.gz  in=319,255,628 out=81,157,278 elapsed=138.9s

  [8868/15692] intraday_3175.csv.gz  in=319,266,536 out=81,157,278 elapsed=138.9s

  [8869/15692] intraday_3176.csv.gz  in=319,280,849 out=81,157,278 elapsed=138.9s

  [8870/15692] intraday_3177.csv.gz  in=319,292,201 out=81,157,278 elapsed=138.9s

  [8871/15692] intraday_3179.csv.gz  in=319,304,068 out=81,157,278 elapsed=139.0s

  [8872/15692] intraday_3180.csv.gz  in=319,317,707 out=81,157,278 elapsed=139.0s

  [8873/15692] intraday_3178.csv.gz  in=319,333,032 out=81,157,278 elapsed=139.0s

  [8874/15692] intraday_3181.csv.gz  in=319,345,418 out=81,157,278 elapsed=139.0s

  [8875/15692] intraday_3182.csv.gz  in=319,356,729 out=81,157,278 elapsed=139.0s

  [8876/15692] intraday_3183.csv.gz  in=319,368,877 out=81,157,278 elapsed=139.0s

  [8877/15692] intraday_3184.csv.gz  in=319,382,540 out=81,157,278 elapsed=139.0s

  [8878/15692] intraday_3185.csv.gz  in=319,393,904 out=81,157,278 elapsed=139.0s

  [8879/15692] intraday_3186.csv.gz  in=319,405,734 out=81,157,278 elapsed=139.1s

  [8880/15692] intraday_3187.csv.gz  in=319,417,532 out=81,157,278 elapsed=139.1s

  [8881/15692] intraday_3188.csv.gz  in=319,429,429 out=81,157,278 elapsed=139.1s

  [8882/15692] intraday_3189.csv.gz  in=319,440,367 out=81,157,278 elapsed=139.1s

  [8883/15692] intraday_3190.csv.gz  in=319,453,087 out=81,157,278 elapsed=139.1s

  [8884/15692] intraday_3191.csv.gz  in=319,465,515 out=81,157,278 elapsed=139.1s

  [8885/15692] intraday_3193.csv.gz  in=319,476,912 out=81,157,278 elapsed=139.1s

  [8886/15692] intraday_3192.csv.gz  in=319,497,444 out=81,157,278 elapsed=139.1s

  [8887/15692] intraday_3194.csv.gz  in=319,510,905 out=81,157,278 elapsed=139.1s

  [8888/15692] intraday_3196.csv.gz  in=319,522,586 out=81,157,278 elapsed=139.1s

  [8889/15692] intraday_3197.csv.gz  in=319,535,198 out=81,157,278 elapsed=139.1s

  [8890/15692] intraday_3195.csv.gz  in=319,549,122 out=81,157,278 elapsed=139.1s

  [8891/15692] intraday_3198.csv.gz  in=319,562,090 out=81,157,278 elapsed=139.2s

  [8892/15692] intraday_3199.csv.gz  in=319,573,799 out=81,157,278 elapsed=139.2s

  [8893/15692] intraday_3200.csv.gz  in=319,586,734 out=81,157,278 elapsed=139.2s

  [8894/15692] intraday_3201.csv.gz  in=319,599,425 out=81,157,278 elapsed=139.2s

  [8895/15692] intraday_3202.csv.gz  in=319,612,845 out=81,157,278 elapsed=139.2s

  [8896/15692] intraday_3204.csv.gz  in=319,626,379 out=81,157,278 elapsed=139.2s

  [8897/15692] intraday_3203.csv.gz  in=319,641,248 out=81,157,278 elapsed=139.2s

  [8898/15692] intraday_3205.csv.gz  in=319,652,913 out=81,157,278 elapsed=139.2s

  [8899/15692] intraday_3206.csv.gz  in=319,665,607 out=81,157,278 elapsed=139.3s

  [8900/15692] intraday_3209.csv.gz  in=319,677,284 out=81,157,278 elapsed=139.3s

  [8901/15692] intraday_3208.csv.gz  in=319,688,700 out=81,157,278 elapsed=139.3s

  [8902/15692] intraday_3207.csv.gz  in=319,700,352 out=81,157,278 elapsed=139.3s

  [8903/15692] intraday_3211.csv.gz  in=319,713,693 out=81,157,278 elapsed=139.3s

  [8904/15692] intraday_3212.csv.gz  in=319,728,444 out=81,157,278 elapsed=139.3s

  [8905/15692] intraday_3213.csv.gz  in=319,739,602 out=81,157,278 elapsed=139.3s

  [8906/15692] intraday_3210.csv.gz  in=319,763,596 out=81,157,278 elapsed=139.3s

  [8907/15692] intraday_3214.csv.gz  in=319,776,560 out=81,157,278 elapsed=139.3s

  [8908/15692] intraday_3215.csv.gz  in=319,789,282 out=81,157,278 elapsed=139.3s

  [8909/15692] intraday_3216.csv.gz  in=319,801,697 out=81,157,278 elapsed=139.4s

  [8910/15692] intraday_3217.csv.gz  in=319,814,732 out=81,157,278 elapsed=139.4s

  [8911/15692] intraday_3219.csv.gz  in=319,828,232 out=81,157,278 elapsed=139.4s

  [8912/15692] intraday_3218.csv.gz  in=319,843,559 out=81,157,278 elapsed=139.4s

  [8913/15692] intraday_3221.csv.gz  in=319,856,241 out=81,157,278 elapsed=139.4s

  [8914/15692] intraday_3220.csv.gz  in=319,869,484 out=81,157,278 elapsed=139.4s

  [8915/15692] intraday_3222.csv.gz  in=319,880,750 out=81,157,278 elapsed=139.4s

  [8916/15692] intraday_3223.csv.gz  in=319,893,208 out=81,157,278 elapsed=139.4s

  [8917/15692] intraday_3224.csv.gz  in=319,903,014 out=81,157,278 elapsed=139.4s

  [8918/15692] intraday_3226.csv.gz  in=319,909,605 out=81,157,278 elapsed=139.4s

  [8919/15692] intraday_3225.csv.gz  in=319,923,347 out=81,157,278 elapsed=139.5s

  [8920/15692] intraday_3227.csv.gz  in=319,933,688 out=81,157,278 elapsed=139.5s

  [8921/15692] intraday_3228.csv.gz  in=319,942,107 out=81,157,278 elapsed=139.5s

  [8922/15692] intraday_3229.csv.gz  in=319,956,461 out=81,157,278 elapsed=139.5s

  [8923/15692] intraday_3230.csv.gz  in=319,969,946 out=81,157,278 elapsed=139.5s

  [8924/15692] intraday_3232.csv.gz  in=319,979,843 out=81,157,278 elapsed=139.5s

  [8925/15692] intraday_3233.csv.gz  in=319,993,870 out=81,157,278 elapsed=139.5s

  [8926/15692] intraday_3231.csv.gz  in=320,005,535 out=81,157,278 elapsed=139.5s

  [8927/15692] intraday_3235.csv.gz  in=320,017,966 out=81,157,278 elapsed=139.6s

  [8928/15692] intraday_3237.csv.gz  in=320,030,915 out=81,157,278 elapsed=139.6s

  [8929/15692] intraday_3234.csv.gz  in=320,044,891 out=81,157,278 elapsed=139.6s

  [8930/15692] intraday_3236.csv.gz  in=320,056,684 out=81,157,278 elapsed=139.6s

  [8931/15692] intraday_3239.csv.gz  in=320,066,144 out=81,157,278 elapsed=139.6s

  [8932/15692] intraday_3241.csv.gz  in=320,078,070 out=81,157,278 elapsed=139.6s

  [8933/15692] intraday_3238.csv.gz  in=320,090,711 out=81,157,278 elapsed=139.6s

  [8934/15692] intraday_3240.csv.gz  in=320,102,879 out=81,157,278 elapsed=139.6s

  [8935/15692] intraday_3242.csv.gz  in=320,114,483 out=81,157,278 elapsed=139.6s

  [8936/15692] intraday_3244.csv.gz  in=320,130,506 out=81,157,278 elapsed=139.6s

  [8937/15692] intraday_3243.csv.gz  in=320,141,765 out=81,157,278 elapsed=139.7s

  [8938/15692] intraday_3245.csv.gz  in=320,154,613 out=81,157,278 elapsed=139.7s

  [8939/15692] intraday_3246.csv.gz  in=320,165,853 out=81,157,278 elapsed=139.7s

  [8940/15692] intraday_3248.csv.gz  in=320,177,234 out=81,157,278 elapsed=139.7s

  [8941/15692] intraday_3247.csv.gz  in=320,187,395 out=81,157,278 elapsed=139.7s

  [8942/15692] intraday_3249.csv.gz  in=320,200,244 out=81,157,278 elapsed=139.7s

  [8943/15692] intraday_3251.csv.gz  in=320,211,957 out=81,157,278 elapsed=139.7s

  [8944/15692] intraday_3252.csv.gz  in=320,224,318 out=81,157,278 elapsed=139.7s

  [8945/15692] intraday_3250.csv.gz  in=320,235,501 out=81,157,278 elapsed=139.7s

  [8946/15692] intraday_3253.csv.gz  in=320,247,559 out=81,157,278 elapsed=139.7s

  [8947/15692] intraday_3254.csv.gz  in=320,261,614 out=81,157,278 elapsed=139.7s

  [8948/15692] intraday_3255.csv.gz  in=320,273,584 out=81,157,278 elapsed=139.8s

  [8949/15692] intraday_3257.csv.gz  in=320,284,924 out=81,157,278 elapsed=139.8s

  [8950/15692] intraday_3256.csv.gz  in=320,297,827 out=81,157,278 elapsed=139.8s

  [8951/15692] intraday_3259.csv.gz  in=320,311,580 out=81,157,278 elapsed=139.8s

  [8952/15692] intraday_3258.csv.gz  in=320,326,492 out=81,157,278 elapsed=139.8s

  [8953/15692] intraday_3260.csv.gz  in=320,339,591 out=81,157,278 elapsed=139.8s

  [8954/15692] intraday_3261.csv.gz  in=320,350,249 out=81,157,278 elapsed=139.8s

  [8955/15692] intraday_3262.csv.gz  in=320,362,192 out=81,157,278 elapsed=139.8s

  [8956/15692] intraday_3263.csv.gz  in=320,374,364 out=81,157,278 elapsed=139.8s

  [8957/15692] intraday_3264.csv.gz  in=320,386,913 out=81,157,278 elapsed=139.8s

  [8958/15692] intraday_3266.csv.gz  in=320,397,717 out=81,157,278 elapsed=139.8s

  [8959/15692] intraday_3265.csv.gz  in=320,412,108 out=81,157,278 elapsed=139.9s

  [8960/15692] intraday_3267.csv.gz  in=320,427,707 out=81,157,278 elapsed=139.9s

  [8961/15692] intraday_3268.csv.gz  in=320,438,353 out=81,157,278 elapsed=139.9s

  [8962/15692] intraday_3269.csv.gz  in=320,451,890 out=81,157,278 elapsed=139.9s

  [8963/15692] intraday_3270.csv.gz  in=320,464,352 out=81,157,278 elapsed=139.9s

  [8964/15692] intraday_3271.csv.gz  in=320,474,869 out=81,157,278 elapsed=139.9s

  [8965/15692] intraday_3272.csv.gz  in=320,487,484 out=81,157,278 elapsed=139.9s

  [8966/15692] intraday_3275.csv.gz  in=320,499,265 out=81,157,278 elapsed=139.9s

  [8967/15692] intraday_3273.csv.gz  in=320,509,404 out=81,157,278 elapsed=139.9s

  [8968/15692] intraday_3274.csv.gz  in=320,520,622 out=81,157,278 elapsed=139.9s

  [8969/15692] intraday_3276.csv.gz  in=320,531,097 out=81,157,278 elapsed=140.0s

  [8970/15692] intraday_3280.csv.gz  in=320,541,875 out=81,157,278 elapsed=140.0s

  [8971/15692] intraday_3278.csv.gz  in=320,552,781 out=81,157,278 elapsed=140.0s

  [8972/15692] intraday_3277.csv.gz  in=320,570,185 out=81,157,278 elapsed=140.0s

  [8973/15692] intraday_3279.csv.gz  in=320,581,149 out=81,157,278 elapsed=140.0s

  [8974/15692] intraday_3282.csv.gz  in=320,590,622 out=81,157,278 elapsed=140.0s

  [8975/15692] intraday_3281.csv.gz  in=320,603,288 out=81,157,278 elapsed=140.0s

  [8976/15692] intraday_3284.csv.gz  in=320,613,822 out=81,157,278 elapsed=140.0s

  [8977/15692] intraday_3285.csv.gz  in=320,623,669 out=81,157,278 elapsed=140.0s

  [8978/15692] intraday_3283.csv.gz  in=320,638,144 out=81,157,278 elapsed=140.0s

  [8979/15692] intraday_3286.csv.gz  in=320,649,558 out=81,157,278 elapsed=140.1s

  [8980/15692] intraday_3287.csv.gz  in=320,661,371 out=81,157,278 elapsed=140.1s

  [8981/15692] intraday_3288.csv.gz  in=320,672,157 out=81,157,278 elapsed=140.1s

  [8982/15692] intraday_3289.csv.gz  in=320,695,222 out=81,157,278 elapsed=140.1s

  [8983/15692] intraday_3290.csv.gz  in=320,706,417 out=81,157,278 elapsed=140.1s

  [8984/15692] intraday_3291.csv.gz  in=320,715,976 out=81,157,278 elapsed=140.1s

  [8985/15692] intraday_3292.csv.gz  in=320,728,016 out=81,157,278 elapsed=140.1s

  [8986/15692] intraday_3293.csv.gz  in=320,741,196 out=81,157,278 elapsed=140.1s

  [8987/15692] intraday_3295.csv.gz  in=320,753,905 out=81,157,278 elapsed=140.1s

  [8988/15692] intraday_3296.csv.gz  in=320,766,915 out=81,157,278 elapsed=140.1s

  [8989/15692] intraday_3294.csv.gz  in=320,784,417 out=81,157,278 elapsed=140.1s

  [8990/15692] intraday_3297.csv.gz  in=320,793,858 out=81,157,278 elapsed=140.1s

  [8991/15692] intraday_3300.csv.gz  in=320,805,410 out=81,157,278 elapsed=140.2s

  [8992/15692] intraday_3299.csv.gz  in=320,816,169 out=81,157,278 elapsed=140.2s

  [8993/15692] intraday_3298.csv.gz  in=320,827,685 out=81,157,278 elapsed=140.2s

  [8994/15692] intraday_3301.csv.gz  in=320,839,092 out=81,157,278 elapsed=140.2s

  [8995/15692] intraday_3302.csv.gz  in=320,850,436 out=81,157,278 elapsed=140.2s

  [8996/15692] intraday_3304.csv.gz  in=320,861,541 out=81,157,278 elapsed=140.2s

  [8997/15692] intraday_3303.csv.gz  in=320,871,387 out=81,157,278 elapsed=140.2s

  [8998/15692] intraday_3305.csv.gz  in=320,884,069 out=81,157,278 elapsed=140.2s

  [8999/15692] intraday_3306.csv.gz  in=320,895,167 out=81,157,278 elapsed=140.2s

  [9000/15692] intraday_3307.csv.gz  in=320,907,090 out=81,157,278 elapsed=140.3s

  [9001/15692] intraday_3308.csv.gz  in=320,916,475 out=81,157,278 elapsed=140.3s

  [9002/15692] intraday_3309.csv.gz  in=320,927,054 out=81,157,278 elapsed=140.3s

  [9003/15692] intraday_3310.csv.gz  in=320,939,732 out=81,157,278 elapsed=140.3s

  [9004/15692] intraday_3313.csv.gz  in=320,950,987 out=81,157,278 elapsed=140.3s

  [9005/15692] intraday_3312.csv.gz  in=320,961,116 out=81,157,278 elapsed=140.3s

  [9006/15692] intraday_3311.csv.gz  in=320,975,223 out=81,157,278 elapsed=140.3s

  [9007/15692] intraday_3314.csv.gz  in=320,984,559 out=81,157,278 elapsed=140.3s

  [9008/15692] intraday_3316.csv.gz  in=320,996,030 out=81,157,278 elapsed=140.3s

  [9009/15692] intraday_3317.csv.gz  in=321,010,699 out=81,157,278 elapsed=140.3s

  [9010/15692] intraday_3315.csv.gz  in=321,023,974 out=81,157,278 elapsed=140.3s

  [9011/15692] intraday_3318.csv.gz  in=321,035,032 out=81,157,278 elapsed=140.3s

  [9012/15692] intraday_3319.csv.gz  in=321,049,502 out=81,157,278 elapsed=140.4s

  [9013/15692] intraday_3321.csv.gz  in=321,062,203 out=81,157,278 elapsed=140.4s

  [9014/15692] intraday_3320.csv.gz  in=321,075,169 out=81,157,278 elapsed=140.4s

  [9015/15692] intraday_3324.csv.gz  in=321,086,677 out=81,157,278 elapsed=140.4s

  [9016/15692] intraday_3322.csv.gz  in=321,099,387 out=81,157,278 elapsed=140.4s

  [9017/15692] intraday_3323.csv.gz  in=321,109,714 out=81,157,278 elapsed=140.4s

  [9018/15692] intraday_3325.csv.gz  in=321,124,089 out=81,157,278 elapsed=140.4s

  [9019/15692] intraday_3326.csv.gz  in=321,134,865 out=81,157,278 elapsed=140.4s

  [9020/15692] intraday_3328.csv.gz  in=321,146,444 out=81,157,278 elapsed=140.4s

  [9021/15692] intraday_3329.csv.gz  in=321,158,824 out=81,157,278 elapsed=140.4s

  [9022/15692] intraday_3327.csv.gz  in=321,169,481 out=81,157,278 elapsed=140.4s

  [9023/15692] intraday_3330.csv.gz  in=321,181,293 out=81,157,278 elapsed=140.4s

  [9024/15692] intraday_3331.csv.gz  in=321,193,123 out=81,157,278 elapsed=140.5s

  [9025/15692] intraday_3333.csv.gz  in=321,204,655 out=81,157,278 elapsed=140.5s

  [9026/15692] intraday_3332.csv.gz  in=321,216,300 out=81,157,278 elapsed=140.5s

  [9027/15692] intraday_3334.csv.gz  in=321,226,956 out=81,157,278 elapsed=140.5s

  [9028/15692] intraday_3335.csv.gz  in=321,240,735 out=81,157,278 elapsed=140.5s

  [9029/15692] intraday_3336.csv.gz  in=321,254,152 out=81,157,278 elapsed=140.5s

  [9030/15692] intraday_3337.csv.gz  in=321,265,585 out=81,157,278 elapsed=140.5s

  [9031/15692] intraday_3339.csv.gz  in=321,281,961 out=81,157,278 elapsed=140.5s

  [9032/15692] intraday_3338.csv.gz  in=321,294,026 out=81,157,278 elapsed=140.5s

  [9033/15692] intraday_3341.csv.gz  in=321,306,451 out=81,157,278 elapsed=140.5s

  [9034/15692] intraday_3342.csv.gz  in=321,319,739 out=81,157,278 elapsed=140.6s

  [9035/15692] intraday_3340.csv.gz  in=321,330,987 out=81,157,278 elapsed=140.6s

  [9036/15692] intraday_3343.csv.gz  in=321,343,373 out=81,157,278 elapsed=140.6s

  [9037/15692] intraday_3345.csv.gz  in=321,357,272 out=81,157,278 elapsed=140.6s

  [9038/15692] intraday_3344.csv.gz  in=321,372,137 out=81,157,278 elapsed=140.6s

  [9039/15692] intraday_3346.csv.gz  in=321,384,124 out=81,157,278 elapsed=140.6s

  [9040/15692] intraday_3347.csv.gz  in=321,396,758 out=81,157,278 elapsed=140.6s

  [9041/15692] intraday_3350.csv.gz  in=321,406,772 out=81,157,278 elapsed=140.6s

  [9042/15692] intraday_3348.csv.gz  in=321,419,634 out=81,157,278 elapsed=140.6s

  [9043/15692] intraday_3349.csv.gz  in=321,438,342 out=81,157,278 elapsed=140.6s

  [9044/15692] intraday_3351.csv.gz  in=321,451,689 out=81,157,278 elapsed=140.6s

  [9045/15692] intraday_3352.csv.gz  in=321,464,202 out=81,157,278 elapsed=140.7s

  [9046/15692] intraday_3355.csv.gz  in=321,475,709 out=81,157,278 elapsed=140.7s

  [9047/15692] intraday_3354.csv.gz  in=321,487,163 out=81,157,278 elapsed=140.7s

  [9048/15692] intraday_3353.csv.gz  in=321,503,066 out=81,157,278 elapsed=140.7s

  [9049/15692] intraday_3356.csv.gz  in=321,515,895 out=81,157,278 elapsed=140.7s

  [9050/15692] intraday_3357.csv.gz  in=321,528,432 out=81,157,278 elapsed=140.7s

  [9051/15692] intraday_3358.csv.gz  in=321,540,734 out=81,157,278 elapsed=140.7s

  [9052/15692] intraday_3360.csv.gz  in=321,553,527 out=81,157,278 elapsed=140.7s

  [9053/15692] intraday_3359.csv.gz  in=321,568,291 out=81,157,278 elapsed=140.7s

  [9054/15692] intraday_3361.csv.gz  in=321,580,907 out=81,157,278 elapsed=140.8s

  [9055/15692] intraday_3362.csv.gz  in=321,593,863 out=81,157,278 elapsed=140.8s

  [9056/15692] intraday_3363.csv.gz  in=321,604,665 out=81,157,278 elapsed=140.8s

  [9057/15692] intraday_3365.csv.gz  in=321,614,297 out=81,157,278 elapsed=140.8s

  [9058/15692] intraday_3364.csv.gz  in=321,630,511 out=81,157,278 elapsed=140.8s

  [9059/15692] intraday_3367.csv.gz  in=321,637,188 out=81,157,278 elapsed=140.8s

  [9060/15692] intraday_3366.csv.gz  in=321,650,394 out=81,157,278 elapsed=140.8s

  [9061/15692] intraday_3368.csv.gz  in=321,659,967 out=81,157,278 elapsed=140.8s

  [9062/15692] intraday_3369.csv.gz  in=321,670,335 out=81,157,278 elapsed=140.8s

  [9063/15692] intraday_3370.csv.gz  in=321,685,203 out=81,157,278 elapsed=140.8s

  [9064/15692] intraday_3371.csv.gz  in=321,698,982 out=81,157,278 elapsed=140.8s

  [9065/15692] intraday_3372.csv.gz  in=321,710,549 out=81,157,278 elapsed=140.8s

  [9066/15692] intraday_3373.csv.gz  in=321,720,893 out=81,157,278 elapsed=140.9s

  [9067/15692] intraday_3374.csv.gz  in=321,735,474 out=81,157,278 elapsed=140.9s

  [9068/15692] intraday_3375.csv.gz  in=321,750,060 out=81,157,278 elapsed=140.9s

  [9069/15692] intraday_3376.csv.gz  in=321,762,827 out=81,157,278 elapsed=140.9s

  [9070/15692] intraday_3377.csv.gz  in=321,774,994 out=81,157,278 elapsed=140.9s

  [9071/15692] intraday_3380.csv.gz  in=321,784,581 out=81,157,278 elapsed=140.9s

  [9072/15692] intraday_3378.csv.gz  in=321,798,264 out=81,157,278 elapsed=140.9s

  [9073/15692] intraday_3379.csv.gz  in=321,811,813 out=81,157,278 elapsed=140.9s

  [9074/15692] intraday_3381.csv.gz  in=321,823,673 out=81,157,278 elapsed=140.9s

  [9075/15692] intraday_3382.csv.gz  in=321,836,468 out=81,157,278 elapsed=140.9s

  [9076/15692] intraday_3384.csv.gz  in=321,848,234 out=81,157,278 elapsed=141.0s

  [9077/15692] intraday_3383.csv.gz  in=321,858,418 out=81,157,278 elapsed=141.0s

  [9078/15692] intraday_3385.csv.gz  in=321,869,749 out=81,157,278 elapsed=141.0s

  [9079/15692] intraday_3386.csv.gz  in=321,882,238 out=81,157,278 elapsed=141.0s

  [9080/15692] intraday_3387.csv.gz  in=321,894,393 out=81,157,278 elapsed=141.0s

  [9081/15692] intraday_3388.csv.gz  in=321,905,961 out=81,157,278 elapsed=141.0s

  [9082/15692] intraday_3390.csv.gz  in=321,918,744 out=81,157,278 elapsed=141.0s

  [9083/15692] intraday_3389.csv.gz  in=321,931,140 out=81,157,278 elapsed=141.0s

  [9084/15692] intraday_3391.csv.gz  in=321,942,510 out=81,157,278 elapsed=141.0s

  [9085/15692] intraday_3392.csv.gz  in=321,954,662 out=81,157,278 elapsed=141.0s

  [9086/15692] intraday_3394.csv.gz  in=321,966,573 out=81,157,278 elapsed=141.0s

  [9087/15692] intraday_3393.csv.gz  in=321,979,299 out=81,157,278 elapsed=141.1s

  [9088/15692] intraday_3395.csv.gz  in=321,990,454 out=81,157,278 elapsed=141.1s

  [9089/15692] intraday_3396.csv.gz  in=322,002,132 out=81,157,278 elapsed=141.1s

  [9090/15692] intraday_3398.csv.gz  in=322,016,205 out=81,157,278 elapsed=141.1s

  [9091/15692] intraday_3397.csv.gz  in=322,028,996 out=81,157,278 elapsed=141.1s

  [9092/15692] intraday_3400.csv.gz  in=322,041,360 out=81,157,278 elapsed=141.1s

  [9093/15692] intraday_3401.csv.gz  in=322,053,937 out=81,157,278 elapsed=141.1s

  [9094/15692] intraday_3399.csv.gz  in=322,070,265 out=81,157,278 elapsed=141.1s

  [9095/15692] intraday_3402.csv.gz  in=322,082,132 out=81,157,278 elapsed=141.1s

  [9096/15692] intraday_3403.csv.gz  in=322,095,242 out=81,157,278 elapsed=141.1s

  [9097/15692] intraday_3404.csv.gz  in=322,107,957 out=81,157,278 elapsed=141.2s

  [9098/15692] intraday_3405.csv.gz  in=322,120,185 out=81,157,278 elapsed=141.2s

  [9099/15692] intraday_3406.csv.gz  in=322,131,150 out=81,157,278 elapsed=141.2s

  [9100/15692] intraday_3407.csv.gz  in=322,140,956 out=81,157,278 elapsed=141.2s

  [9101/15692] intraday_3409.csv.gz  in=322,150,531 out=81,157,278 elapsed=141.2s

  [9102/15692] intraday_3408.csv.gz  in=322,162,150 out=81,157,278 elapsed=141.2s

  [9103/15692] intraday_3410.csv.gz  in=322,176,640 out=81,157,278 elapsed=141.2s

  [9104/15692] intraday_3411.csv.gz  in=322,189,234 out=81,157,278 elapsed=141.2s

  [9105/15692] intraday_3413.csv.gz  in=322,200,666 out=81,157,278 elapsed=141.2s

  [9106/15692] intraday_3412.csv.gz  in=322,213,294 out=81,157,278 elapsed=141.2s

  [9107/15692] intraday_3414.csv.gz  in=322,223,941 out=81,157,278 elapsed=141.2s

  [9108/15692] intraday_3416.csv.gz  in=322,234,509 out=81,157,278 elapsed=141.3s

  [9109/15692] intraday_3417.csv.gz  in=322,245,022 out=81,157,278 elapsed=141.3s

  [9110/15692] intraday_3415.csv.gz  in=322,257,973 out=81,157,278 elapsed=141.3s

  [9111/15692] intraday_3418.csv.gz  in=322,269,910 out=81,157,278 elapsed=141.3s

  [9112/15692] intraday_3419.csv.gz  in=322,281,460 out=81,157,278 elapsed=141.3s

  [9113/15692] intraday_3420.csv.gz  in=322,292,798 out=81,157,278 elapsed=141.3s

  [9114/15692] intraday_3421.csv.gz  in=322,304,764 out=81,157,278 elapsed=141.3s

  [9115/15692] intraday_3422.csv.gz  in=322,314,397 out=81,157,278 elapsed=141.3s

  [9116/15692] intraday_3423.csv.gz  in=322,327,859 out=81,157,278 elapsed=141.3s

  [9117/15692] intraday_3424.csv.gz  in=322,339,509 out=81,157,278 elapsed=141.3s

  [9118/15692] intraday_3425.csv.gz  in=322,350,122 out=81,157,278 elapsed=141.4s

  [9119/15692] intraday_3426.csv.gz  in=322,360,014 out=81,157,278 elapsed=141.4s

  [9120/15692] intraday_3427.csv.gz  in=322,372,157 out=81,157,278 elapsed=141.4s

  [9121/15692] intraday_3429.csv.gz  in=322,383,382 out=81,157,278 elapsed=141.4s

  [9122/15692] intraday_3428.csv.gz  in=322,396,395 out=81,157,278 elapsed=141.4s

  [9123/15692] intraday_3430.csv.gz  in=322,407,564 out=81,157,278 elapsed=141.4s

  [9124/15692] intraday_3431.csv.gz  in=322,420,099 out=81,157,278 elapsed=141.4s

  [9125/15692] intraday_3433.csv.gz  in=322,434,049 out=81,157,278 elapsed=141.4s

  [9126/15692] intraday_3432.csv.gz  in=322,443,580 out=81,157,278 elapsed=141.4s

  [9127/15692] intraday_3434.csv.gz  in=322,457,579 out=81,157,278 elapsed=141.4s

  [9128/15692] intraday_3435.csv.gz  in=322,468,022 out=81,157,278 elapsed=141.5s

  [9129/15692] intraday_3436.csv.gz  in=322,481,259 out=81,157,278 elapsed=141.5s

  [9130/15692] intraday_3437.csv.gz  in=322,494,467 out=81,157,278 elapsed=141.5s

  [9131/15692] intraday_3440.csv.gz  in=322,506,018 out=81,157,278 elapsed=141.5s

  [9132/15692] intraday_3438.csv.gz  in=322,515,452 out=81,157,278 elapsed=141.5s

  [9133/15692] intraday_3439.csv.gz  in=322,526,662 out=81,157,278 elapsed=141.5s

  [9134/15692] intraday_3441.csv.gz  in=322,540,102 out=81,157,278 elapsed=141.5s

  [9135/15692] intraday_3442.csv.gz  in=322,549,177 out=81,157,278 elapsed=141.5s

  [9136/15692] intraday_3444.csv.gz  in=322,560,261 out=81,157,278 elapsed=141.5s

  [9137/15692] intraday_3443.csv.gz  in=322,571,617 out=81,157,278 elapsed=141.5s

  [9138/15692] intraday_3445.csv.gz  in=322,583,791 out=81,157,278 elapsed=141.5s

  [9139/15692] intraday_3446.csv.gz  in=322,595,941 out=81,157,278 elapsed=141.6s

  [9140/15692] intraday_3448.csv.gz  in=322,606,455 out=81,157,278 elapsed=141.6s

  [9141/15692] intraday_3447.csv.gz  in=322,619,110 out=81,157,278 elapsed=141.6s

  [9142/15692] intraday_3450.csv.gz  in=322,629,850 out=81,157,278 elapsed=141.6s

  [9143/15692] intraday_3449.csv.gz  in=322,639,335 out=81,157,278 elapsed=141.6s

  [9144/15692] intraday_3451.csv.gz  in=322,655,275 out=81,157,278 elapsed=141.6s

  [9145/15692] intraday_3453.csv.gz  in=322,666,709 out=81,157,278 elapsed=141.6s

  [9146/15692] intraday_3454.csv.gz  in=322,677,265 out=81,157,278 elapsed=141.6s

  [9147/15692] intraday_3452.csv.gz  in=322,690,019 out=81,157,278 elapsed=141.6s

  [9148/15692] intraday_3455.csv.gz  in=322,700,486 out=81,157,278 elapsed=141.7s

  [9149/15692] intraday_3457.csv.gz  in=322,714,259 out=81,157,278 elapsed=141.7s

  [9150/15692] intraday_3458.csv.gz  in=322,726,757 out=81,157,278 elapsed=141.7s

  [9151/15692] intraday_3456.csv.gz  in=322,739,050 out=81,157,278 elapsed=141.7s

  [9152/15692] intraday_3459.csv.gz  in=322,751,802 out=81,157,278 elapsed=141.7s

  [9153/15692] intraday_3460.csv.gz  in=322,765,971 out=81,157,278 elapsed=141.7s

  [9154/15692] intraday_3461.csv.gz  in=322,779,503 out=81,157,278 elapsed=141.7s

  [9155/15692] intraday_3462.csv.gz  in=322,792,845 out=81,157,278 elapsed=141.7s

  [9156/15692] intraday_3463.csv.gz  in=322,804,642 out=81,157,278 elapsed=141.7s

  [9157/15692] intraday_3464.csv.gz  in=322,817,248 out=81,157,278 elapsed=141.7s

  [9158/15692] intraday_3465.csv.gz  in=322,827,800 out=81,157,278 elapsed=141.7s

  [9159/15692] intraday_3466.csv.gz  in=322,841,218 out=81,157,278 elapsed=141.8s

  [9160/15692] intraday_3467.csv.gz  in=322,852,935 out=81,157,278 elapsed=141.8s

  [9161/15692] intraday_3469.csv.gz  in=322,863,146 out=81,157,278 elapsed=141.8s

  [9162/15692] intraday_3468.csv.gz  in=322,875,866 out=81,157,278 elapsed=141.8s

  [9163/15692] intraday_3470.csv.gz  in=322,888,712 out=81,157,278 elapsed=141.8s

  [9164/15692] intraday_3471.csv.gz  in=322,901,064 out=81,157,278 elapsed=141.8s

  [9165/15692] intraday_3472.csv.gz  in=322,913,778 out=81,157,278 elapsed=141.8s

  [9166/15692] intraday_3473.csv.gz  in=322,927,864 out=81,157,278 elapsed=141.8s

  [9167/15692] intraday_3474.csv.gz  in=322,939,218 out=81,157,278 elapsed=141.8s

  [9168/15692] intraday_3475.csv.gz  in=322,951,261 out=81,157,278 elapsed=141.8s

  [9169/15692] intraday_3476.csv.gz  in=322,966,247 out=81,157,278 elapsed=141.8s

  [9170/15692] intraday_3477.csv.gz  in=322,980,189 out=81,157,278 elapsed=141.8s

  [9171/15692] intraday_3478.csv.gz  in=322,992,389 out=81,157,278 elapsed=141.8s

  [9172/15692] intraday_3479.csv.gz  in=323,005,052 out=81,157,278 elapsed=141.9s

  [9173/15692] intraday_3480.csv.gz  in=323,017,450 out=81,157,278 elapsed=141.9s

  [9174/15692] intraday_3481.csv.gz  in=323,029,866 out=81,157,278 elapsed=141.9s

  [9175/15692] intraday_3482.csv.gz  in=323,043,449 out=81,157,278 elapsed=141.9s

  [9176/15692] intraday_3483.csv.gz  in=323,058,304 out=81,157,278 elapsed=141.9s

  [9177/15692] intraday_3484.csv.gz  in=323,070,068 out=81,157,278 elapsed=141.9s

  [9178/15692] intraday_3485.csv.gz  in=323,086,298 out=81,157,278 elapsed=141.9s

  [9179/15692] intraday_3486.csv.gz  in=323,098,308 out=81,157,278 elapsed=141.9s

  [9180/15692] intraday_3487.csv.gz  in=323,110,766 out=81,157,278 elapsed=141.9s

  [9181/15692] intraday_3488.csv.gz  in=323,121,876 out=81,157,278 elapsed=141.9s

  [9182/15692] intraday_3490.csv.gz  in=323,132,074 out=81,157,278 elapsed=141.9s

  [9183/15692] intraday_3489.csv.gz  in=323,145,061 out=81,157,278 elapsed=141.9s

  [9184/15692] intraday_3491.csv.gz  in=323,159,829 out=81,157,278 elapsed=141.9s

  [9185/15692] intraday_3492.csv.gz  in=323,172,378 out=81,157,278 elapsed=142.0s

  [9186/15692] intraday_3494.csv.gz  in=323,184,842 out=81,157,278 elapsed=142.0s

  [9187/15692] intraday_3493.csv.gz  in=323,199,326 out=81,157,278 elapsed=142.0s

  [9188/15692] intraday_3495.csv.gz  in=323,212,325 out=81,157,278 elapsed=142.0s

  [9189/15692] intraday_3496.csv.gz  in=323,224,762 out=81,157,278 elapsed=142.0s

  [9190/15692] intraday_3497.csv.gz  in=323,237,892 out=81,157,278 elapsed=142.0s

  [9191/15692] intraday_3499.csv.gz  in=323,252,473 out=81,157,278 elapsed=142.0s

  [9192/15692] intraday_3498.csv.gz  in=323,265,114 out=81,157,278 elapsed=142.0s

  [9193/15692] intraday_3500.csv.gz  in=323,279,704 out=81,157,278 elapsed=142.0s

  [9194/15692] intraday_3501.csv.gz  in=323,292,850 out=81,157,278 elapsed=142.0s

  [9195/15692] intraday_3504.csv.gz  in=323,303,528 out=81,157,278 elapsed=142.1s

  [9196/15692] intraday_3503.csv.gz  in=323,315,258 out=81,157,278 elapsed=142.1s

  [9197/15692] intraday_3502.csv.gz  in=323,328,625 out=81,157,278 elapsed=142.1s

  [9198/15692] intraday_3505.csv.gz  in=323,340,464 out=81,157,278 elapsed=142.1s

  [9199/15692] intraday_3506.csv.gz  in=323,353,575 out=81,157,278 elapsed=142.1s

  [9200/15692] intraday_3507.csv.gz  in=323,361,961 out=81,157,278 elapsed=142.1s

  [9201/15692] intraday_3508.csv.gz  in=323,370,700 out=81,157,278 elapsed=142.1s

  [9202/15692] intraday_3509.csv.gz  in=323,383,221 out=81,157,278 elapsed=142.1s

  [9203/15692] intraday_3510.csv.gz  in=323,397,428 out=81,157,278 elapsed=142.1s

  [9204/15692] intraday_3511.csv.gz  in=323,410,825 out=81,157,278 elapsed=142.1s

  [9205/15692] intraday_3512.csv.gz  in=323,423,119 out=81,157,278 elapsed=142.1s

  [9206/15692] intraday_3513.csv.gz  in=323,433,107 out=81,157,278 elapsed=142.1s

  [9207/15692] intraday_3514.csv.gz  in=323,446,621 out=81,157,278 elapsed=142.1s

  [9208/15692] intraday_3518.csv.gz  in=323,460,909 out=81,157,278 elapsed=142.2s

  [9209/15692] intraday_3517.csv.gz  in=323,472,938 out=81,157,278 elapsed=142.2s

  [9210/15692] intraday_3516.csv.gz  in=323,485,534 out=81,157,278 elapsed=142.2s

  [9211/15692] intraday_3515.csv.gz  in=323,499,132 out=81,157,278 elapsed=142.2s

  [9212/15692] intraday_3520.csv.gz  in=323,508,376 out=81,157,278 elapsed=142.2s

  [9213/15692] intraday_3521.csv.gz  in=323,520,813 out=81,157,278 elapsed=142.2s

  [9214/15692] intraday_3519.csv.gz  in=323,534,163 out=81,157,278 elapsed=142.2s

  [9215/15692] intraday_3522.csv.gz  in=323,546,338 out=81,157,278 elapsed=142.2s

  [9216/15692] intraday_3525.csv.gz  in=323,557,672 out=81,157,278 elapsed=142.3s

  [9217/15692] intraday_3523.csv.gz  in=323,568,177 out=81,157,278 elapsed=142.3s

  [9218/15692] intraday_3524.csv.gz  in=323,580,082 out=81,157,278 elapsed=142.3s

  [9219/15692] intraday_3526.csv.gz  in=323,592,777 out=81,157,278 elapsed=142.3s

  [9220/15692] intraday_3527.csv.gz  in=323,605,138 out=81,157,278 elapsed=142.3s

  [9221/15692] intraday_3529.csv.gz  in=323,618,252 out=81,157,278 elapsed=142.3s

  [9222/15692] intraday_3528.csv.gz  in=323,629,974 out=81,157,278 elapsed=142.3s

  [9223/15692] intraday_3530.csv.gz  in=323,642,899 out=81,157,278 elapsed=142.3s

  [9224/15692] intraday_3531.csv.gz  in=323,654,279 out=81,157,278 elapsed=142.3s

  [9225/15692] intraday_3532.csv.gz  in=323,665,629 out=81,157,278 elapsed=142.3s

  [9226/15692] intraday_3533.csv.gz  in=323,678,613 out=81,157,278 elapsed=142.3s

  [9227/15692] intraday_3535.csv.gz  in=323,689,218 out=81,157,278 elapsed=142.3s

  [9228/15692] intraday_3534.csv.gz  in=323,701,621 out=81,157,278 elapsed=142.4s

  [9229/15692] intraday_3536.csv.gz  in=323,713,831 out=81,157,278 elapsed=142.4s

  [9230/15692] intraday_3537.csv.gz  in=323,726,163 out=81,157,278 elapsed=142.4s

  [9231/15692] intraday_3538.csv.gz  in=323,740,305 out=81,157,278 elapsed=142.4s

  [9232/15692] intraday_3539.csv.gz  in=323,754,581 out=81,157,278 elapsed=142.4s

  [9233/15692] intraday_3540.csv.gz  in=323,767,652 out=81,157,278 elapsed=142.4s

  [9234/15692] intraday_3542.csv.gz  in=323,779,102 out=81,157,278 elapsed=142.4s

  [9235/15692] intraday_3541.csv.gz  in=323,790,676 out=81,157,278 elapsed=142.4s

  [9236/15692] intraday_3543.csv.gz  in=323,803,265 out=81,157,278 elapsed=142.4s

  [9237/15692] intraday_3544.csv.gz  in=323,814,784 out=81,157,278 elapsed=142.4s

  [9238/15692] intraday_3545.csv.gz  in=323,827,108 out=81,157,278 elapsed=142.4s

  [9239/15692] intraday_3546.csv.gz  in=323,837,977 out=81,157,278 elapsed=142.5s

  [9240/15692] intraday_3548.csv.gz  in=323,848,947 out=81,157,278 elapsed=142.5s

  [9241/15692] intraday_3549.csv.gz  in=323,859,265 out=81,157,278 elapsed=142.5s

  [9242/15692] intraday_3547.csv.gz  in=323,869,952 out=81,157,278 elapsed=142.5s

  [9243/15692] intraday_3550.csv.gz  in=323,883,825 out=81,157,278 elapsed=142.5s

  [9244/15692] intraday_3551.csv.gz  in=323,896,091 out=81,157,278 elapsed=142.5s

  [9245/15692] intraday_3552.csv.gz  in=323,909,661 out=81,157,278 elapsed=142.5s

  [9246/15692] intraday_3553.csv.gz  in=323,920,942 out=81,157,278 elapsed=142.5s

  [9247/15692] intraday_3554.csv.gz  in=323,932,279 out=81,157,278 elapsed=142.5s

  [9248/15692] intraday_3556.csv.gz  in=323,942,471 out=81,157,278 elapsed=142.5s

  [9249/15692] intraday_3555.csv.gz  in=323,955,125 out=81,157,278 elapsed=142.5s

  [9250/15692] intraday_3557.csv.gz  in=323,966,909 out=81,157,278 elapsed=142.5s

  [9251/15692] intraday_3558.csv.gz  in=323,978,755 out=81,157,278 elapsed=142.5s

  [9252/15692] intraday_3559.csv.gz  in=323,989,136 out=81,157,278 elapsed=142.6s

  [9253/15692] intraday_3560.csv.gz  in=324,000,563 out=81,157,278 elapsed=142.6s

  [9254/15692] intraday_3562.csv.gz  in=324,010,976 out=81,157,278 elapsed=142.6s

  [9255/15692] intraday_3561.csv.gz  in=324,021,872 out=81,157,278 elapsed=142.6s

  [9256/15692] intraday_3563.csv.gz  in=324,034,714 out=81,157,278 elapsed=142.6s

  [9257/15692] intraday_3564.csv.gz  in=324,047,038 out=81,157,278 elapsed=142.6s

  [9258/15692] intraday_3566.csv.gz  in=324,056,547 out=81,157,278 elapsed=142.6s

  [9259/15692] intraday_3567.csv.gz  in=324,070,335 out=81,157,278 elapsed=142.6s

  [9260/15692] intraday_3565.csv.gz  in=324,080,771 out=81,157,278 elapsed=142.6s

  [9261/15692] intraday_3569.csv.gz  in=324,091,953 out=81,157,278 elapsed=142.6s

  [9262/15692] intraday_3570.csv.gz  in=324,104,061 out=81,157,278 elapsed=142.6s

  [9263/15692] intraday_3571.csv.gz  in=324,115,473 out=81,157,278 elapsed=142.6s

  [9264/15692] intraday_3568.csv.gz  in=324,128,772 out=81,157,278 elapsed=142.6s

  [9265/15692] intraday_3572.csv.gz  in=324,139,096 out=81,157,278 elapsed=142.7s

  [9266/15692] intraday_3573.csv.gz  in=324,152,458 out=81,157,278 elapsed=142.7s

  [9267/15692] intraday_3576.csv.gz  in=324,165,150 out=81,157,278 elapsed=142.7s

  [9268/15692] intraday_3574.csv.gz  in=324,177,985 out=81,157,278 elapsed=142.7s

  [9269/15692] intraday_3575.csv.gz  in=324,190,517 out=81,157,278 elapsed=142.7s

  [9270/15692] intraday_3577.csv.gz  in=324,201,036 out=81,157,278 elapsed=142.7s

  [9271/15692] intraday_3579.csv.gz  in=324,212,871 out=81,157,278 elapsed=142.7s

  [9272/15692] intraday_3578.csv.gz  in=324,223,162 out=81,157,278 elapsed=142.7s

  [9273/15692] intraday_3581.csv.gz  in=324,236,454 out=81,157,278 elapsed=142.7s

  [9274/15692] intraday_3580.csv.gz  in=324,247,311 out=81,157,278 elapsed=142.7s

  [9275/15692] intraday_3582.csv.gz  in=324,257,567 out=81,157,278 elapsed=142.7s

  [9276/15692] intraday_3583.csv.gz  in=324,267,300 out=81,157,278 elapsed=142.7s

  [9277/15692] intraday_3586.csv.gz  in=324,279,184 out=81,157,278 elapsed=142.8s

  [9278/15692] intraday_3584.csv.gz  in=324,289,874 out=81,157,278 elapsed=142.8s

  [9279/15692] intraday_3585.csv.gz  in=324,302,599 out=81,157,278 elapsed=142.8s

  [9280/15692] intraday_3587.csv.gz  in=324,315,400 out=81,157,278 elapsed=142.8s

  [9281/15692] intraday_3589.csv.gz  in=324,326,908 out=81,157,278 elapsed=142.8s

  [9282/15692] intraday_3588.csv.gz  in=324,338,333 out=81,157,278 elapsed=142.8s

  [9283/15692] intraday_3590.csv.gz  in=324,349,549 out=81,157,278 elapsed=142.8s

  [9284/15692] intraday_3592.csv.gz  in=324,361,948 out=81,157,278 elapsed=142.8s

  [9285/15692] intraday_3591.csv.gz  in=324,375,628 out=81,157,278 elapsed=142.8s

  [9286/15692] intraday_3593.csv.gz  in=324,386,487 out=81,157,278 elapsed=142.8s

  [9287/15692] intraday_3594.csv.gz  in=324,396,822 out=81,157,278 elapsed=142.8s

  [9288/15692] intraday_3595.csv.gz  in=324,408,824 out=81,157,278 elapsed=142.8s

  [9289/15692] intraday_3596.csv.gz  in=324,421,208 out=81,157,278 elapsed=142.8s

  [9290/15692] intraday_3598.csv.gz  in=324,431,937 out=81,157,278 elapsed=142.9s

  [9291/15692] intraday_3597.csv.gz  in=324,447,047 out=81,157,278 elapsed=142.9s

  [9292/15692] intraday_3599.csv.gz  in=324,464,355 out=81,157,278 elapsed=142.9s

  [9293/15692] intraday_3600.csv.gz  in=324,477,515 out=81,157,278 elapsed=142.9s

  [9294/15692] intraday_3601.csv.gz  in=324,491,786 out=81,157,278 elapsed=142.9s

  [9295/15692] intraday_3602.csv.gz  in=324,504,786 out=81,157,278 elapsed=142.9s

  [9296/15692] intraday_3603.csv.gz  in=324,516,168 out=81,157,278 elapsed=142.9s

  [9297/15692] intraday_3604.csv.gz  in=324,527,630 out=81,157,278 elapsed=142.9s

  [9298/15692] intraday_3607.csv.gz  in=324,538,852 out=81,157,278 elapsed=142.9s

  [9299/15692] intraday_3605.csv.gz  in=324,551,099 out=81,157,278 elapsed=142.9s

  [9300/15692] intraday_3606.csv.gz  in=324,569,773 out=81,157,278 elapsed=142.9s

  [9301/15692] intraday_3609.csv.gz  in=324,582,448 out=81,157,278 elapsed=143.0s

  [9302/15692] intraday_3608.csv.gz  in=324,594,524 out=81,157,278 elapsed=143.0s

  [9303/15692] intraday_3610.csv.gz  in=324,605,652 out=81,157,278 elapsed=143.0s

  [9304/15692] intraday_3611.csv.gz  in=324,619,502 out=81,157,278 elapsed=143.0s

  [9305/15692] intraday_3614.csv.gz  in=324,632,162 out=81,157,278 elapsed=143.0s

  [9306/15692] intraday_3612.csv.gz  in=324,644,294 out=81,157,278 elapsed=143.0s

  [9307/15692] intraday_3613.csv.gz  in=324,657,527 out=81,157,278 elapsed=143.0s

  [9308/15692] intraday_3615.csv.gz  in=324,670,128 out=81,157,278 elapsed=143.0s

  [9309/15692] intraday_3617.csv.gz  in=324,683,095 out=81,157,278 elapsed=143.0s

  [9310/15692] intraday_3616.csv.gz  in=324,697,219 out=81,157,278 elapsed=143.0s

  [9311/15692] intraday_3618.csv.gz  in=324,708,589 out=81,157,278 elapsed=143.1s

  [9312/15692] intraday_3619.csv.gz  in=324,722,095 out=81,157,278 elapsed=143.1s

  [9313/15692] intraday_3620.csv.gz  in=324,733,898 out=81,157,278 elapsed=143.1s

  [9314/15692] intraday_3622.csv.gz  in=324,747,997 out=81,157,278 elapsed=143.1s

  [9315/15692] intraday_3621.csv.gz  in=324,760,630 out=81,157,278 elapsed=143.1s

  [9316/15692] intraday_3623.csv.gz  in=324,774,220 out=81,157,278 elapsed=143.1s

  [9317/15692] intraday_3624.csv.gz  in=324,787,746 out=81,157,278 elapsed=143.1s

  [9318/15692] intraday_3625.csv.gz  in=324,801,645 out=81,157,278 elapsed=143.1s

  [9319/15692] intraday_3626.csv.gz  in=324,814,179 out=81,157,278 elapsed=143.1s

  [9320/15692] intraday_3629.csv.gz  in=324,826,859 out=81,157,278 elapsed=143.2s

  [9321/15692] intraday_3630.csv.gz  in=324,836,474 out=81,157,278 elapsed=143.2s

  [9322/15692] intraday_3627.csv.gz  in=324,848,440 out=81,157,278 elapsed=143.2s

  [9323/15692] intraday_3628.csv.gz  in=324,859,287 out=81,157,278 elapsed=143.2s

  [9324/15692] intraday_3631.csv.gz  in=324,872,171 out=81,157,278 elapsed=143.2s

  [9325/15692] intraday_3632.csv.gz  in=324,885,017 out=81,157,278 elapsed=143.2s

  [9326/15692] intraday_3633.csv.gz  in=324,903,527 out=81,157,278 elapsed=143.2s

  [9327/15692] intraday_3634.csv.gz  in=324,914,580 out=81,157,278 elapsed=143.2s

  [9328/15692] intraday_3635.csv.gz  in=324,927,480 out=81,157,278 elapsed=143.2s

  [9329/15692] intraday_3637.csv.gz  in=324,939,248 out=81,157,278 elapsed=143.3s

  [9330/15692] intraday_3638.csv.gz  in=324,952,825 out=81,157,278 elapsed=143.3s

  [9331/15692] intraday_3636.csv.gz  in=324,965,565 out=81,157,278 elapsed=143.3s

  [9332/15692] intraday_3639.csv.gz  in=324,983,435 out=81,157,278 elapsed=143.3s

  [9333/15692] intraday_3640.csv.gz  in=324,997,488 out=81,157,278 elapsed=143.3s

  [9334/15692] intraday_3641.csv.gz  in=325,010,248 out=81,157,278 elapsed=143.3s

  [9335/15692] intraday_3643.csv.gz  in=325,021,464 out=81,157,278 elapsed=143.3s

  [9336/15692] intraday_3642.csv.gz  in=325,034,127 out=81,157,278 elapsed=143.3s

  [9337/15692] intraday_3644.csv.gz  in=325,045,629 out=81,157,278 elapsed=143.3s

  [9338/15692] intraday_3648.csv.gz  in=325,054,094 out=81,157,278 elapsed=143.4s

  [9339/15692] intraday_3646.csv.gz  in=325,067,673 out=81,157,278 elapsed=143.4s

  [9340/15692] intraday_3645.csv.gz  in=325,078,722 out=81,157,278 elapsed=143.4s

  [9341/15692] intraday_3647.csv.gz  in=325,087,589 out=81,157,278 elapsed=143.4s

  [9342/15692] intraday_3649.csv.gz  in=325,097,663 out=81,157,278 elapsed=143.4s

  [9343/15692] intraday_3652.csv.gz  in=325,111,002 out=81,157,278 elapsed=143.4s

  [9344/15692] intraday_3650.csv.gz  in=325,126,200 out=81,157,278 elapsed=143.4s

  [9345/15692] intraday_3651.csv.gz  in=325,140,376 out=81,157,278 elapsed=143.4s

  [9346/15692] intraday_3653.csv.gz  in=325,150,777 out=81,157,278 elapsed=143.4s

  [9347/15692] intraday_3655.csv.gz  in=325,165,206 out=81,157,278 elapsed=143.5s

  [9348/15692] intraday_3654.csv.gz  in=325,179,929 out=81,157,278 elapsed=143.5s

  [9349/15692] intraday_3657.csv.gz  in=325,192,512 out=81,157,278 elapsed=143.5s

  [9350/15692] intraday_3656.csv.gz  in=325,208,574 out=81,157,278 elapsed=143.5s

  [9351/15692] intraday_3658.csv.gz  in=325,222,632 out=81,157,278 elapsed=143.5s

  [9352/15692] intraday_3660.csv.gz  in=325,232,323 out=81,157,278 elapsed=143.5s

  [9353/15692] intraday_3659.csv.gz  in=325,247,431 out=81,157,278 elapsed=143.5s

  [9354/15692] intraday_3661.csv.gz  in=325,260,001 out=81,157,278 elapsed=143.5s

  [9355/15692] intraday_3663.csv.gz  in=325,270,735 out=81,157,278 elapsed=143.5s

  [9356/15692] intraday_3662.csv.gz  in=325,283,689 out=81,157,278 elapsed=143.5s

  [9357/15692] intraday_3664.csv.gz  in=325,295,637 out=81,157,278 elapsed=143.5s

  [9358/15692] intraday_3665.csv.gz  in=325,307,245 out=81,157,278 elapsed=143.5s

  [9359/15692] intraday_3666.csv.gz  in=325,320,125 out=81,157,278 elapsed=143.6s

  [9360/15692] intraday_3667.csv.gz  in=325,333,110 out=81,157,278 elapsed=143.6s

  [9361/15692] intraday_3668.csv.gz  in=325,343,913 out=81,157,278 elapsed=143.6s

  [9362/15692] intraday_3669.csv.gz  in=325,357,174 out=81,157,278 elapsed=143.6s

  [9363/15692] intraday_3670.csv.gz  in=325,371,223 out=81,157,278 elapsed=143.6s

  [9364/15692] intraday_3671.csv.gz  in=325,382,550 out=81,157,278 elapsed=143.6s

  [9365/15692] intraday_3672.csv.gz  in=325,394,854 out=81,157,278 elapsed=143.6s

  [9366/15692] intraday_3674.csv.gz  in=325,407,355 out=81,157,278 elapsed=143.6s

  [9367/15692] intraday_3673.csv.gz  in=325,419,534 out=81,157,278 elapsed=143.6s

  [9368/15692] intraday_3675.csv.gz  in=325,430,515 out=81,157,278 elapsed=143.6s

  [9369/15692] intraday_3676.csv.gz  in=325,443,127 out=81,157,278 elapsed=143.7s

  [9370/15692] intraday_3677.csv.gz  in=325,455,897 out=81,157,278 elapsed=143.7s

  [9371/15692] intraday_3679.csv.gz  in=325,472,380 out=81,157,278 elapsed=143.7s

  [9372/15692] intraday_3678.csv.gz  in=325,486,709 out=81,157,278 elapsed=143.7s

  [9373/15692] intraday_3680.csv.gz  in=325,503,147 out=81,157,278 elapsed=143.7s

  [9374/15692] intraday_3681.csv.gz  in=325,514,120 out=81,157,278 elapsed=143.7s

  [9375/15692] intraday_3683.csv.gz  in=325,526,737 out=81,157,278 elapsed=143.7s

  [9376/15692] intraday_3682.csv.gz  in=325,538,297 out=81,157,278 elapsed=143.7s

  [9377/15692] intraday_3685.csv.gz  in=325,551,353 out=81,157,278 elapsed=143.7s

  [9378/15692] intraday_3684.csv.gz  in=325,563,129 out=81,157,278 elapsed=143.8s

  [9379/15692] intraday_3687.csv.gz  in=325,572,835 out=81,157,278 elapsed=143.8s

  [9380/15692] intraday_3686.csv.gz  in=325,587,473 out=81,157,278 elapsed=143.8s

  [9381/15692] intraday_3689.csv.gz  in=325,597,899 out=81,157,278 elapsed=143.8s

  [9382/15692] intraday_3688.csv.gz  in=325,611,216 out=81,157,278 elapsed=143.8s

  [9383/15692] intraday_3692.csv.gz  in=325,623,228 out=81,157,278 elapsed=143.8s

  [9384/15692] intraday_3691.csv.gz  in=325,635,569 out=81,157,278 elapsed=143.8s

  [9385/15692] intraday_3690.csv.gz  in=325,649,304 out=81,157,278 elapsed=143.8s

  [9386/15692] intraday_3693.csv.gz  in=325,660,982 out=81,157,278 elapsed=143.8s

  [9387/15692] intraday_3694.csv.gz  in=325,672,225 out=81,157,278 elapsed=143.8s

  [9388/15692] intraday_3696.csv.gz  in=325,683,044 out=81,157,278 elapsed=143.9s

  [9389/15692] intraday_3697.csv.gz  in=325,695,204 out=81,157,278 elapsed=143.9s

  [9390/15692] intraday_3695.csv.gz  in=325,708,462 out=81,157,278 elapsed=143.9s

  [9391/15692] intraday_3698.csv.gz  in=325,720,572 out=81,157,278 elapsed=143.9s

  [9392/15692] intraday_3699.csv.gz  in=325,731,836 out=81,157,278 elapsed=143.9s

  [9393/15692] intraday_3701.csv.gz  in=325,746,415 out=81,157,278 elapsed=143.9s

  [9394/15692] intraday_3700.csv.gz  in=325,758,365 out=81,157,278 elapsed=143.9s

  [9395/15692] intraday_3702.csv.gz  in=325,768,274 out=81,157,278 elapsed=143.9s

  [9396/15692] intraday_3703.csv.gz  in=325,781,924 out=81,157,278 elapsed=143.9s

  [9397/15692] intraday_3704.csv.gz  in=325,793,536 out=81,157,278 elapsed=143.9s

  [9398/15692] intraday_3706.csv.gz  in=325,804,414 out=81,157,278 elapsed=143.9s

  [9399/15692] intraday_3705.csv.gz  in=325,815,276 out=81,157,278 elapsed=144.0s

  [9400/15692] intraday_3707.csv.gz  in=325,830,041 out=81,157,278 elapsed=144.0s

  [9401/15692] intraday_3708.csv.gz  in=325,843,341 out=81,157,278 elapsed=144.0s

  [9402/15692] intraday_3709.csv.gz  in=325,855,136 out=81,157,278 elapsed=144.0s

  [9403/15692] intraday_3710.csv.gz  in=325,866,149 out=81,157,278 elapsed=144.0s

  [9404/15692] intraday_3711.csv.gz  in=325,888,644 out=81,157,278 elapsed=144.0s

  [9405/15692] intraday_3712.csv.gz  in=325,898,790 out=81,157,278 elapsed=144.0s

  [9406/15692] intraday_3713.csv.gz  in=325,915,513 out=81,157,278 elapsed=144.0s

  [9407/15692] intraday_3714.csv.gz  in=325,928,851 out=81,157,278 elapsed=144.1s

  [9408/15692] intraday_3715.csv.gz  in=325,941,354 out=81,157,278 elapsed=144.1s

  [9409/15692] intraday_3716.csv.gz  in=325,953,526 out=81,157,278 elapsed=144.1s

  [9410/15692] intraday_3718.csv.gz  in=325,963,422 out=81,157,278 elapsed=144.1s

  [9411/15692] intraday_3717.csv.gz  in=325,979,168 out=81,157,278 elapsed=144.1s

  [9412/15692] intraday_3719.csv.gz  in=325,991,213 out=81,157,278 elapsed=144.1s

  [9413/15692] intraday_3720.csv.gz  in=326,003,013 out=81,157,278 elapsed=144.1s

  [9414/15692] intraday_3722.csv.gz  in=326,013,444 out=81,157,278 elapsed=144.2s

  [9415/15692] intraday_3721.csv.gz  in=326,026,736 out=81,157,278 elapsed=144.2s

  [9416/15692] intraday_3723.csv.gz  in=326,038,888 out=81,157,278 elapsed=144.2s

  [9417/15692] intraday_3724.csv.gz  in=326,050,856 out=81,157,278 elapsed=144.2s

  [9418/15692] intraday_3725.csv.gz  in=326,063,756 out=81,157,278 elapsed=144.2s

  [9419/15692] intraday_3727.csv.gz  in=326,077,379 out=81,157,278 elapsed=144.2s

  [9420/15692] intraday_3726.csv.gz  in=326,089,833 out=81,157,278 elapsed=144.2s

  [9421/15692] intraday_3728.csv.gz  in=326,102,242 out=81,157,278 elapsed=144.2s

  [9422/15692] intraday_3729.csv.gz  in=326,115,733 out=81,157,278 elapsed=144.2s

  [9423/15692] intraday_3730.csv.gz  in=326,126,147 out=81,157,278 elapsed=144.2s

  [9424/15692] intraday_3732.csv.gz  in=326,138,645 out=81,157,278 elapsed=144.2s

  [9425/15692] intraday_3731.csv.gz  in=326,155,150 out=81,157,278 elapsed=144.2s

  [9426/15692] intraday_3733.csv.gz  in=326,167,244 out=81,157,278 elapsed=144.3s

  [9427/15692] intraday_3735.csv.gz  in=326,179,178 out=81,157,278 elapsed=144.3s

  [9428/15692] intraday_3734.csv.gz  in=326,189,978 out=81,157,278 elapsed=144.3s

  [9429/15692] intraday_3736.csv.gz  in=326,203,963 out=81,157,278 elapsed=144.3s

  [9430/15692] intraday_3737.csv.gz  in=326,218,724 out=81,157,278 elapsed=144.3s

  [9431/15692] intraday_3738.csv.gz  in=326,232,785 out=81,157,278 elapsed=144.3s

  [9432/15692] intraday_3739.csv.gz  in=326,243,577 out=81,157,278 elapsed=144.3s

  [9433/15692] intraday_3741.csv.gz  in=326,257,825 out=81,157,278 elapsed=144.3s

  [9434/15692] intraday_3740.csv.gz  in=326,273,633 out=81,157,278 elapsed=144.3s

  [9435/15692] intraday_3742.csv.gz  in=326,287,696 out=81,157,278 elapsed=144.3s

  [9436/15692] intraday_3743.csv.gz  in=326,299,519 out=81,157,278 elapsed=144.3s

  [9437/15692] intraday_3744.csv.gz  in=326,312,270 out=81,157,278 elapsed=144.3s

  [9438/15692] intraday_3747.csv.gz  in=326,324,729 out=81,157,278 elapsed=144.4s

  [9439/15692] intraday_3746.csv.gz  in=326,337,952 out=81,157,278 elapsed=144.4s

  [9440/15692] intraday_3745.csv.gz  in=326,349,740 out=81,157,278 elapsed=144.4s

  [9441/15692] intraday_3748.csv.gz  in=326,361,690 out=81,157,278 elapsed=144.4s

  [9442/15692] intraday_3750.csv.gz  in=326,375,214 out=81,157,278 elapsed=144.4s

  [9443/15692] intraday_3749.csv.gz  in=326,390,480 out=81,157,278 elapsed=144.4s

  [9444/15692] intraday_3751.csv.gz  in=326,404,005 out=81,157,278 elapsed=144.4s

  [9445/15692] intraday_3752.csv.gz  in=326,416,909 out=81,157,278 elapsed=144.4s

  [9446/15692] intraday_3753.csv.gz  in=326,432,709 out=81,157,278 elapsed=144.4s

  [9447/15692] intraday_3754.csv.gz  in=326,444,615 out=81,157,278 elapsed=144.4s

  [9448/15692] intraday_3756.csv.gz  in=326,459,442 out=81,157,278 elapsed=144.4s

  [9449/15692] intraday_3755.csv.gz  in=326,473,495 out=81,157,278 elapsed=144.4s

  [9450/15692] intraday_3757.csv.gz  in=326,487,655 out=81,157,278 elapsed=144.5s

  [9451/15692] intraday_3759.csv.gz  in=326,500,072 out=81,157,278 elapsed=144.5s

  [9452/15692] intraday_3758.csv.gz  in=326,512,604 out=81,157,278 elapsed=144.5s

  [9453/15692] intraday_3761.csv.gz  in=326,525,119 out=81,157,278 elapsed=144.5s

  [9454/15692] intraday_3760.csv.gz  in=326,548,981 out=81,157,278 elapsed=144.5s

  [9455/15692] intraday_3762.csv.gz  in=326,564,509 out=81,157,278 elapsed=144.5s

  [9456/15692] intraday_3764.csv.gz  in=326,578,828 out=81,157,278 elapsed=144.5s

  [9457/15692] intraday_3763.csv.gz  in=326,596,023 out=81,157,278 elapsed=144.5s

  [9458/15692] intraday_3765.csv.gz  in=326,611,421 out=81,157,278 elapsed=144.5s

  [9459/15692] intraday_3766.csv.gz  in=326,630,779 out=81,157,278 elapsed=144.5s

  [9460/15692] intraday_3767.csv.gz  in=326,644,437 out=81,157,278 elapsed=144.5s

  [9461/15692] intraday_3769.csv.gz  in=326,662,086 out=81,157,278 elapsed=144.5s

  [9462/15692] intraday_3768.csv.gz  in=326,674,218 out=81,157,278 elapsed=144.6s

  [9463/15692] intraday_3770.csv.gz  in=326,685,562 out=81,157,278 elapsed=144.6s

  [9464/15692] intraday_3771.csv.gz  in=326,698,111 out=81,157,278 elapsed=144.6s

  [9465/15692] intraday_3772.csv.gz  in=326,711,186 out=81,157,278 elapsed=144.6s

  [9466/15692] intraday_3773.csv.gz  in=326,723,953 out=81,157,278 elapsed=144.6s

  [9467/15692] intraday_3774.csv.gz  in=326,739,374 out=81,157,278 elapsed=144.6s

  [9468/15692] intraday_3775.csv.gz  in=326,751,519 out=81,157,278 elapsed=144.6s

  [9469/15692] intraday_3776.csv.gz  in=326,763,944 out=81,157,278 elapsed=144.6s

  [9470/15692] intraday_3777.csv.gz  in=326,777,682 out=81,157,278 elapsed=144.6s

  [9471/15692] intraday_3778.csv.gz  in=326,789,976 out=81,157,278 elapsed=144.6s

  [9472/15692] intraday_3779.csv.gz  in=326,802,684 out=81,157,278 elapsed=144.6s

  [9473/15692] intraday_3780.csv.gz  in=326,817,360 out=81,157,278 elapsed=144.6s

  [9474/15692] intraday_3781.csv.gz  in=326,831,245 out=81,157,278 elapsed=144.7s

  [9475/15692] intraday_3782.csv.gz  in=326,844,794 out=81,157,278 elapsed=144.7s

  [9476/15692] intraday_3784.csv.gz  in=326,856,314 out=81,157,278 elapsed=144.7s

  [9477/15692] intraday_3783.csv.gz  in=326,868,975 out=81,157,278 elapsed=144.7s

  [9478/15692] intraday_3785.csv.gz  in=326,880,720 out=81,157,278 elapsed=144.7s

  [9479/15692] intraday_3786.csv.gz  in=326,891,946 out=81,157,278 elapsed=144.7s

  [9480/15692] intraday_3788.csv.gz  in=326,899,181 out=81,157,278 elapsed=144.7s

  [9481/15692] intraday_3787.csv.gz  in=326,913,362 out=81,157,278 elapsed=144.7s

  [9482/15692] intraday_3789.csv.gz  in=326,924,934 out=81,157,278 elapsed=144.7s

  [9483/15692] intraday_3790.csv.gz  in=326,933,313 out=81,157,278 elapsed=144.7s

  [9484/15692] intraday_3791.csv.gz  in=326,948,801 out=81,157,278 elapsed=144.8s

  [9485/15692] intraday_3792.csv.gz  in=326,963,994 out=81,157,278 elapsed=144.8s

  [9486/15692] intraday_3793.csv.gz  in=326,976,787 out=81,157,278 elapsed=144.8s

  [9487/15692] intraday_3795.csv.gz  in=326,992,773 out=81,157,278 elapsed=144.8s

  [9488/15692] intraday_3794.csv.gz  in=327,002,936 out=81,157,278 elapsed=144.8s

  [9489/15692] intraday_3796.csv.gz  in=327,017,394 out=81,157,278 elapsed=144.8s

  [9490/15692] intraday_3798.csv.gz  in=327,029,318 out=81,157,278 elapsed=144.8s

  [9491/15692] intraday_3799.csv.gz  in=327,044,108 out=81,157,278 elapsed=144.8s

  [9492/15692] intraday_3797.csv.gz  in=327,056,535 out=81,157,278 elapsed=144.8s

  [9493/15692] intraday_3801.csv.gz  in=327,066,381 out=81,157,278 elapsed=144.8s

  [9494/15692] intraday_3803.csv.gz  in=327,079,542 out=81,157,278 elapsed=144.9s

  [9495/15692] intraday_3802.csv.gz  in=327,091,299 out=81,157,278 elapsed=144.9s

  [9496/15692] intraday_3800.csv.gz  in=327,106,713 out=81,157,278 elapsed=144.9s

  [9497/15692] intraday_3804.csv.gz  in=327,117,120 out=81,157,278 elapsed=144.9s

  [9498/15692] intraday_3805.csv.gz  in=327,128,512 out=81,157,278 elapsed=144.9s

  [9499/15692] intraday_3808.csv.gz  in=327,141,720 out=81,157,278 elapsed=144.9s

  [9500/15692] intraday_3806.csv.gz  in=327,153,281 out=81,157,278 elapsed=144.9s

  [9501/15692] intraday_3807.csv.gz  in=327,166,350 out=81,157,278 elapsed=144.9s

  [9502/15692] intraday_3809.csv.gz  in=327,176,907 out=81,157,278 elapsed=144.9s

  [9503/15692] intraday_3810.csv.gz  in=327,189,873 out=81,157,278 elapsed=144.9s

  [9504/15692] intraday_3811.csv.gz  in=327,204,326 out=81,157,278 elapsed=144.9s

  [9505/15692] intraday_3812.csv.gz  in=327,216,230 out=81,157,278 elapsed=144.9s

  [9506/15692] intraday_3813.csv.gz  in=327,228,369 out=81,157,278 elapsed=145.0s

  [9507/15692] intraday_3815.csv.gz  in=327,240,812 out=81,157,278 elapsed=145.0s

  [9508/15692] intraday_3814.csv.gz  in=327,252,932 out=81,157,278 elapsed=145.0s

  [9509/15692] intraday_3817.csv.gz  in=327,265,922 out=81,157,278 elapsed=145.0s

  [9510/15692] intraday_3816.csv.gz  in=327,275,485 out=81,157,278 elapsed=145.0s

  [9511/15692] intraday_3818.csv.gz  in=327,288,329 out=81,157,278 elapsed=145.0s

  [9512/15692] intraday_3819.csv.gz  in=327,307,973 out=81,157,278 elapsed=145.0s

  [9513/15692] intraday_3821.csv.gz  in=327,323,050 out=81,157,278 elapsed=145.0s

  [9514/15692] intraday_3820.csv.gz  in=327,337,913 out=81,157,278 elapsed=145.0s

  [9515/15692] intraday_3822.csv.gz  in=327,349,822 out=81,157,278 elapsed=145.0s

  [9516/15692] intraday_3823.csv.gz  in=327,362,067 out=81,157,278 elapsed=145.1s

  [9517/15692] intraday_3824.csv.gz  in=327,375,414 out=81,157,278 elapsed=145.1s

  [9518/15692] intraday_3825.csv.gz  in=327,387,035 out=81,157,278 elapsed=145.1s

  [9519/15692] intraday_3827.csv.gz  in=327,397,413 out=81,157,278 elapsed=145.1s

  [9520/15692] intraday_3826.csv.gz  in=327,410,979 out=81,157,278 elapsed=145.1s

  [9521/15692] intraday_3828.csv.gz  in=327,421,577 out=81,157,278 elapsed=145.1s

  [9522/15692] intraday_3830.csv.gz  in=327,431,594 out=81,157,278 elapsed=145.1s

  [9523/15692] intraday_3829.csv.gz  in=327,443,030 out=81,157,278 elapsed=145.1s

  [9524/15692] intraday_3832.csv.gz  in=327,455,199 out=81,157,278 elapsed=145.1s

  [9525/15692] intraday_3831.csv.gz  in=327,469,870 out=81,157,278 elapsed=145.1s

  [9526/15692] intraday_3834.csv.gz  in=327,481,725 out=81,157,278 elapsed=145.2s

  [9527/15692] intraday_3835.csv.gz  in=327,492,882 out=81,157,278 elapsed=145.2s

  [9528/15692] intraday_3836.csv.gz  in=327,506,011 out=81,157,278 elapsed=145.2s

  [9529/15692] intraday_3833.csv.gz  in=327,528,032 out=81,157,278 elapsed=145.2s

  [9530/15692] intraday_3837.csv.gz  in=327,539,228 out=81,157,278 elapsed=145.2s

  [9531/15692] intraday_3838.csv.gz  in=327,551,506 out=81,157,278 elapsed=145.2s

  [9532/15692] intraday_3840.csv.gz  in=327,562,611 out=81,157,278 elapsed=145.2s

  [9533/15692] intraday_3839.csv.gz  in=327,577,961 out=81,157,278 elapsed=145.2s

  [9534/15692] intraday_3841.csv.gz  in=327,589,047 out=81,157,278 elapsed=145.2s

  [9535/15692] intraday_3842.csv.gz  in=327,600,877 out=81,157,278 elapsed=145.2s

  [9536/15692] intraday_3843.csv.gz  in=327,611,692 out=81,157,278 elapsed=145.2s

  [9537/15692] intraday_3844.csv.gz  in=327,623,760 out=81,157,278 elapsed=145.2s

  [9538/15692] intraday_3846.csv.gz  in=327,635,141 out=81,157,278 elapsed=145.3s

  [9539/15692] intraday_3845.csv.gz  in=327,648,093 out=81,157,278 elapsed=145.3s

  [9540/15692] intraday_3847.csv.gz  in=327,658,639 out=81,157,278 elapsed=145.3s

  [9541/15692] intraday_3848.csv.gz  in=327,672,524 out=81,157,278 elapsed=145.3s

  [9542/15692] intraday_3850.csv.gz  in=327,689,990 out=81,157,278 elapsed=145.3s

  [9543/15692] intraday_3849.csv.gz  in=327,703,690 out=81,157,278 elapsed=145.3s

  [9544/15692] intraday_3851.csv.gz  in=327,714,766 out=81,157,278 elapsed=145.3s

  [9545/15692] intraday_3852.csv.gz  in=327,727,535 out=81,157,278 elapsed=145.3s

  [9546/15692] intraday_3853.csv.gz  in=327,739,110 out=81,157,278 elapsed=145.3s

  [9547/15692] intraday_3856.csv.gz  in=327,750,415 out=81,157,278 elapsed=145.4s

  [9548/15692] intraday_3855.csv.gz  in=327,766,080 out=81,157,278 elapsed=145.4s

  [9549/15692] intraday_3854.csv.gz  in=327,780,760 out=81,157,278 elapsed=145.4s

  [9550/15692] intraday_3857.csv.gz  in=327,794,029 out=81,157,278 elapsed=145.4s

  [9551/15692] intraday_3858.csv.gz  in=327,807,137 out=81,157,278 elapsed=145.4s

  [9552/15692] intraday_3859.csv.gz  in=327,817,474 out=81,157,278 elapsed=145.4s

  [9553/15692] intraday_3860.csv.gz  in=327,828,763 out=81,157,278 elapsed=145.4s

  [9554/15692] intraday_3861.csv.gz  in=327,840,261 out=81,157,278 elapsed=145.4s

  [9555/15692] intraday_3862.csv.gz  in=327,853,808 out=81,157,278 elapsed=145.4s

  [9556/15692] intraday_3863.csv.gz  in=327,863,856 out=81,157,278 elapsed=145.4s

  [9557/15692] intraday_3864.csv.gz  in=327,876,317 out=81,157,278 elapsed=145.5s

  [9558/15692] intraday_3865.csv.gz  in=327,887,733 out=81,157,278 elapsed=145.5s

  [9559/15692] intraday_3866.csv.gz  in=327,900,604 out=81,157,278 elapsed=145.5s

  [9560/15692] intraday_3868.csv.gz  in=327,913,729 out=81,157,278 elapsed=145.5s

  [9561/15692] intraday_3867.csv.gz  in=327,926,990 out=81,157,278 elapsed=145.5s

  [9562/15692] intraday_3869.csv.gz  in=327,938,699 out=81,157,278 elapsed=145.5s

  [9563/15692] intraday_3870.csv.gz  in=327,949,772 out=81,157,278 elapsed=145.5s

  [9564/15692] intraday_3872.csv.gz  in=327,967,139 out=81,157,278 elapsed=145.5s

  [9565/15692] intraday_3871.csv.gz  in=327,977,650 out=81,157,278 elapsed=145.5s

  [9566/15692] intraday_3874.csv.gz  in=327,990,089 out=81,157,278 elapsed=145.5s

  [9567/15692] intraday_3873.csv.gz  in=328,009,869 out=81,157,278 elapsed=145.5s

  [9568/15692] intraday_3875.csv.gz  in=328,020,313 out=81,157,278 elapsed=145.5s

  [9569/15692] intraday_3876.csv.gz  in=328,033,145 out=81,157,278 elapsed=145.6s

  [9570/15692] intraday_3877.csv.gz  in=328,046,878 out=81,157,278 elapsed=145.6s

  [9571/15692] intraday_3878.csv.gz  in=328,061,484 out=81,157,278 elapsed=145.6s

  [9572/15692] intraday_3880.csv.gz  in=328,072,500 out=81,157,278 elapsed=145.6s

  [9573/15692] intraday_3879.csv.gz  in=328,086,202 out=81,157,278 elapsed=145.6s

  [9574/15692] intraday_3881.csv.gz  in=328,107,973 out=81,157,278 elapsed=145.6s

  [9575/15692] intraday_3882.csv.gz  in=328,122,828 out=81,157,278 elapsed=145.6s

  [9576/15692] intraday_3883.csv.gz  in=328,139,014 out=81,157,278 elapsed=145.6s

  [9577/15692] intraday_3884.csv.gz  in=328,151,048 out=81,157,278 elapsed=145.6s

  [9578/15692] intraday_3885.csv.gz  in=328,163,201 out=81,157,278 elapsed=145.7s

  [9579/15692] intraday_3886.csv.gz  in=328,174,923 out=81,157,278 elapsed=145.7s

  [9580/15692] intraday_3887.csv.gz  in=328,188,375 out=81,157,278 elapsed=145.7s

  [9581/15692] intraday_3888.csv.gz  in=328,200,554 out=81,157,278 elapsed=145.7s

  [9582/15692] intraday_3889.csv.gz  in=328,213,056 out=81,157,278 elapsed=145.7s

  [9583/15692] intraday_3890.csv.gz  in=328,225,800 out=81,157,278 elapsed=145.7s

  [9584/15692] intraday_3893.csv.gz  in=328,239,319 out=81,157,278 elapsed=145.7s

  [9585/15692] intraday_3891.csv.gz  in=328,253,515 out=81,157,278 elapsed=145.7s

  [9586/15692] intraday_3892.csv.gz  in=328,268,056 out=81,157,278 elapsed=145.7s

  [9587/15692] intraday_3894.csv.gz  in=328,284,674 out=81,157,278 elapsed=145.7s

  [9588/15692] intraday_3896.csv.gz  in=328,296,839 out=81,157,278 elapsed=145.8s

  [9589/15692] intraday_3895.csv.gz  in=328,308,314 out=81,157,278 elapsed=145.8s

  [9590/15692] intraday_3898.csv.gz  in=328,323,014 out=81,157,278 elapsed=145.8s

  [9591/15692] intraday_3897.csv.gz  in=328,338,269 out=81,157,278 elapsed=145.8s

  [9592/15692] intraday_3899.csv.gz  in=328,349,253 out=81,157,278 elapsed=145.8s

  [9593/15692] intraday_3901.csv.gz  in=328,361,791 out=81,157,278 elapsed=145.8s

  [9594/15692] intraday_3900.csv.gz  in=328,376,076 out=81,157,278 elapsed=145.8s

  [9595/15692] intraday_3902.csv.gz  in=328,388,999 out=81,157,278 elapsed=145.8s

  [9596/15692] intraday_3903.csv.gz  in=328,403,960 out=81,157,278 elapsed=145.8s

  [9597/15692] intraday_3907.csv.gz  in=328,415,364 out=81,157,278 elapsed=145.8s

  [9598/15692] intraday_3904.csv.gz  in=328,429,464 out=81,157,278 elapsed=145.9s

  [9599/15692] intraday_3906.csv.gz  in=328,444,919 out=81,157,278 elapsed=145.9s

  [9600/15692] intraday_3905.csv.gz  in=328,461,964 out=81,157,278 elapsed=145.9s

  [9601/15692] intraday_3908.csv.gz  in=328,475,349 out=81,157,278 elapsed=145.9s

  [9602/15692] intraday_3909.csv.gz  in=328,487,861 out=81,157,278 elapsed=145.9s

  [9603/15692] intraday_3910.csv.gz  in=328,499,683 out=81,157,278 elapsed=145.9s

  [9604/15692] intraday_3911.csv.gz  in=328,510,833 out=81,157,278 elapsed=145.9s

  [9605/15692] intraday_3912.csv.gz  in=328,522,648 out=81,157,278 elapsed=145.9s

  [9606/15692] intraday_3913.csv.gz  in=328,536,408 out=81,157,278 elapsed=145.9s

  [9607/15692] intraday_3915.csv.gz  in=328,553,105 out=81,157,278 elapsed=145.9s

  [9608/15692] intraday_3914.csv.gz  in=328,565,770 out=81,157,278 elapsed=145.9s

  [9609/15692] intraday_3917.csv.gz  in=328,578,152 out=81,157,278 elapsed=145.9s

  [9610/15692] intraday_3916.csv.gz  in=328,589,929 out=81,157,278 elapsed=146.0s

  [9611/15692] intraday_3919.csv.gz  in=328,601,787 out=81,157,278 elapsed=146.0s

  [9612/15692] intraday_3921.csv.gz  in=328,616,536 out=81,157,278 elapsed=146.0s

  [9613/15692] intraday_3920.csv.gz  in=328,628,949 out=81,157,278 elapsed=146.0s

  [9614/15692] intraday_3918.csv.gz  in=328,642,243 out=81,157,278 elapsed=146.0s

  [9615/15692] intraday_3922.csv.gz  in=328,655,733 out=81,157,278 elapsed=146.0s

  [9616/15692] intraday_3923.csv.gz  in=328,669,404 out=81,157,278 elapsed=146.0s

  [9617/15692] intraday_3926.csv.gz  in=328,682,688 out=81,157,278 elapsed=146.0s

  [9618/15692] intraday_3924.csv.gz  in=328,695,907 out=81,157,278 elapsed=146.0s

  [9619/15692] intraday_3925.csv.gz  in=328,707,671 out=81,157,278 elapsed=146.0s

  [9620/15692] intraday_3927.csv.gz  in=328,718,249 out=81,157,278 elapsed=146.0s

  [9621/15692] intraday_3928.csv.gz  in=328,732,197 out=81,157,278 elapsed=146.1s

  [9622/15692] intraday_3929.csv.gz  in=328,740,666 out=81,157,278 elapsed=146.1s

  [9623/15692] intraday_3930.csv.gz  in=328,750,146 out=81,157,278 elapsed=146.1s

  [9624/15692] intraday_3931.csv.gz  in=328,761,090 out=81,157,278 elapsed=146.1s

  [9625/15692] intraday_3932.csv.gz  in=328,777,409 out=81,157,278 elapsed=146.1s

  [9626/15692] intraday_3933.csv.gz  in=328,792,068 out=81,157,278 elapsed=146.1s

  [9627/15692] intraday_3935.csv.gz  in=328,802,740 out=81,157,278 elapsed=146.1s

  [9628/15692] intraday_3934.csv.gz  in=328,815,711 out=81,157,278 elapsed=146.1s

  [9629/15692] intraday_3936.csv.gz  in=328,830,901 out=81,157,278 elapsed=146.1s

  [9630/15692] intraday_3937.csv.gz  in=328,845,724 out=81,157,278 elapsed=146.1s

  [9631/15692] intraday_3939.csv.gz  in=328,858,671 out=81,157,278 elapsed=146.2s

  [9632/15692] intraday_3938.csv.gz  in=328,871,476 out=81,157,278 elapsed=146.2s

  [9633/15692] intraday_3940.csv.gz  in=328,886,377 out=81,157,278 elapsed=146.2s

  [9634/15692] intraday_3941.csv.gz  in=328,902,386 out=81,157,278 elapsed=146.2s

  [9635/15692] intraday_3943.csv.gz  in=328,915,993 out=81,157,278 elapsed=146.2s

  [9636/15692] intraday_3942.csv.gz  in=328,925,976 out=81,157,278 elapsed=146.2s

  [9637/15692] intraday_3944.csv.gz  in=328,939,299 out=81,157,278 elapsed=146.2s

  [9638/15692] intraday_3946.csv.gz  in=328,950,446 out=81,157,278 elapsed=146.2s

  [9639/15692] intraday_3948.csv.gz  in=328,962,703 out=81,157,278 elapsed=146.2s

  [9640/15692] intraday_3945.csv.gz  in=328,974,722 out=81,157,278 elapsed=146.2s

  [9641/15692] intraday_3947.csv.gz  in=328,987,931 out=81,157,278 elapsed=146.2s

  [9642/15692] intraday_3949.csv.gz  in=329,001,353 out=81,157,278 elapsed=146.3s

  [9643/15692] intraday_3952.csv.gz  in=329,015,268 out=81,157,278 elapsed=146.3s

  [9644/15692] intraday_3951.csv.gz  in=329,029,604 out=81,157,278 elapsed=146.3s

  [9645/15692] intraday_3950.csv.gz  in=329,041,788 out=81,157,278 elapsed=146.3s

  [9646/15692] intraday_3953.csv.gz  in=329,055,040 out=81,157,278 elapsed=146.3s

  [9647/15692] intraday_3954.csv.gz  in=329,067,632 out=81,157,278 elapsed=146.3s

  [9648/15692] intraday_3955.csv.gz  in=329,080,724 out=81,157,278 elapsed=146.3s

  [9649/15692] intraday_3956.csv.gz  in=329,093,027 out=81,157,278 elapsed=146.3s

  [9650/15692] intraday_3957.csv.gz  in=329,103,644 out=81,157,278 elapsed=146.3s

  [9651/15692] intraday_3958.csv.gz  in=329,116,567 out=81,157,278 elapsed=146.3s

  [9652/15692] intraday_3959.csv.gz  in=329,130,437 out=81,157,278 elapsed=146.4s

  [9653/15692] intraday_3961.csv.gz  in=329,146,152 out=81,157,278 elapsed=146.4s

  [9654/15692] intraday_3960.csv.gz  in=329,160,740 out=81,157,278 elapsed=146.4s

  [9655/15692] intraday_3962.csv.gz  in=329,174,330 out=81,157,278 elapsed=146.4s

  [9656/15692] intraday_3963.csv.gz  in=329,186,456 out=81,157,278 elapsed=146.4s

  [9657/15692] intraday_3964.csv.gz  in=329,199,706 out=81,157,278 elapsed=146.4s

  [9658/15692] intraday_3966.csv.gz  in=329,211,434 out=81,157,278 elapsed=146.4s

  [9659/15692] intraday_3965.csv.gz  in=329,226,135 out=81,157,278 elapsed=146.4s

  [9660/15692] intraday_3967.csv.gz  in=329,239,474 out=81,157,278 elapsed=146.4s

  [9661/15692] intraday_3969.csv.gz  in=329,250,674 out=81,157,278 elapsed=146.5s

  [9662/15692] intraday_3968.csv.gz  in=329,262,369 out=81,157,278 elapsed=146.5s

  [9663/15692] intraday_3971.csv.gz  in=329,275,555 out=81,157,278 elapsed=146.5s

  [9664/15692] intraday_3970.csv.gz  in=329,287,398 out=81,157,278 elapsed=146.5s

  [9665/15692] intraday_3972.csv.gz  in=329,300,370 out=81,157,278 elapsed=146.5s

  [9666/15692] intraday_3973.csv.gz  in=329,313,351 out=81,157,278 elapsed=146.5s

  [9667/15692] intraday_3974.csv.gz  in=329,327,142 out=81,157,278 elapsed=146.5s

  [9668/15692] intraday_3976.csv.gz  in=329,340,220 out=81,157,278 elapsed=146.5s

  [9669/15692] intraday_3975.csv.gz  in=329,352,226 out=81,157,278 elapsed=146.5s

  [9670/15692] intraday_3977.csv.gz  in=329,364,809 out=81,157,278 elapsed=146.5s

  [9671/15692] intraday_3978.csv.gz  in=329,376,486 out=81,157,278 elapsed=146.5s

  [9672/15692] intraday_3981.csv.gz  in=329,387,141 out=81,157,278 elapsed=146.6s

  [9673/15692] intraday_3980.csv.gz  in=329,399,036 out=81,157,278 elapsed=146.6s

  [9674/15692] intraday_3979.csv.gz  in=329,411,857 out=81,157,278 elapsed=146.6s

  [9675/15692] intraday_3982.csv.gz  in=329,425,544 out=81,157,278 elapsed=146.6s

  [9676/15692] intraday_3983.csv.gz  in=329,436,223 out=81,157,278 elapsed=146.6s

  [9677/15692] intraday_3984.csv.gz  in=329,447,262 out=81,157,278 elapsed=146.6s

  [9678/15692] intraday_3985.csv.gz  in=329,461,379 out=81,157,278 elapsed=146.6s

  [9679/15692] intraday_3986.csv.gz  in=329,473,667 out=81,157,278 elapsed=146.6s

  [9680/15692] intraday_3988.csv.gz  in=329,484,680 out=81,157,278 elapsed=146.6s

  [9681/15692] intraday_3989.csv.gz  in=329,499,849 out=81,157,278 elapsed=146.7s

  [9682/15692] intraday_3987.csv.gz  in=329,512,120 out=81,157,278 elapsed=146.7s

  [9683/15692] intraday_3990.csv.gz  in=329,524,646 out=81,157,278 elapsed=146.7s

  [9684/15692] intraday_3991.csv.gz  in=329,537,124 out=81,157,278 elapsed=146.7s

  [9685/15692] intraday_3993.csv.gz  in=329,550,104 out=81,157,278 elapsed=146.7s

  [9686/15692] intraday_3992.csv.gz  in=329,563,070 out=81,157,278 elapsed=146.7s

  [9687/15692] intraday_3995.csv.gz  in=329,578,004 out=81,157,278 elapsed=146.7s

  [9688/15692] intraday_3994.csv.gz  in=329,589,988 out=81,157,278 elapsed=146.7s

  [9689/15692] intraday_3996.csv.gz  in=329,604,284 out=81,157,278 elapsed=146.7s

  [9690/15692] intraday_3997.csv.gz  in=329,617,696 out=81,157,278 elapsed=146.7s

  [9691/15692] intraday_3999.csv.gz  in=329,628,433 out=81,157,278 elapsed=146.7s

  [9692/15692] intraday_3998.csv.gz  in=329,641,905 out=81,157,278 elapsed=146.7s

  [9693/15692] intraday_4001.csv.gz  in=329,653,343 out=81,157,278 elapsed=146.8s

  [9694/15692] intraday_4000.csv.gz  in=329,666,059 out=81,157,278 elapsed=146.8s

  [9695/15692] intraday_4003.csv.gz  in=329,680,299 out=81,157,278 elapsed=146.8s

  [9696/15692] intraday_4002.csv.gz  in=329,693,105 out=81,157,278 elapsed=146.8s

  [9697/15692] intraday_4004.csv.gz  in=329,705,353 out=81,157,278 elapsed=146.8s

  [9698/15692] intraday_4006.csv.gz  in=329,717,760 out=81,157,278 elapsed=146.8s

  [9699/15692] intraday_4005.csv.gz  in=329,727,621 out=81,157,278 elapsed=146.8s

  [9700/15692] intraday_4007.csv.gz  in=329,743,289 out=81,157,278 elapsed=146.8s

  [9701/15692] intraday_4009.csv.gz  in=329,755,739 out=81,157,278 elapsed=146.9s

  [9702/15692] intraday_4010.csv.gz  in=329,767,090 out=81,157,278 elapsed=146.9s

  [9703/15692] intraday_4008.csv.gz  in=329,779,126 out=81,157,278 elapsed=146.9s

  [9704/15692] intraday_4011.csv.gz  in=329,791,121 out=81,157,278 elapsed=146.9s

  [9705/15692] intraday_4012.csv.gz  in=329,805,136 out=81,157,278 elapsed=146.9s

  [9706/15692] intraday_4014.csv.gz  in=329,817,207 out=81,157,278 elapsed=146.9s

  [9707/15692] intraday_4013.csv.gz  in=329,833,200 out=81,157,278 elapsed=146.9s

  [9708/15692] intraday_4015.csv.gz  in=329,845,105 out=81,157,278 elapsed=146.9s

  [9709/15692] intraday_4016.csv.gz  in=329,856,827 out=81,157,278 elapsed=146.9s

  [9710/15692] intraday_4017.csv.gz  in=329,870,924 out=81,157,278 elapsed=146.9s

  [9711/15692] intraday_4018.csv.gz  in=329,885,616 out=81,157,278 elapsed=146.9s

  [9712/15692] intraday_4020.csv.gz  in=329,896,606 out=81,157,278 elapsed=146.9s

  [9713/15692] intraday_4019.csv.gz  in=329,911,492 out=81,157,278 elapsed=147.0s

  [9714/15692] intraday_4021.csv.gz  in=329,926,036 out=81,157,278 elapsed=147.0s

  [9715/15692] intraday_4022.csv.gz  in=329,942,359 out=81,157,278 elapsed=147.0s

  [9716/15692] intraday_4023.csv.gz  in=329,956,185 out=81,157,278 elapsed=147.0s

  [9717/15692] intraday_4024.csv.gz  in=329,971,183 out=81,157,278 elapsed=147.0s

  [9718/15692] intraday_4025.csv.gz  in=329,983,310 out=81,157,278 elapsed=147.0s

  [9719/15692] intraday_4026.csv.gz  in=329,995,647 out=81,157,278 elapsed=147.0s

  [9720/15692] intraday_4028.csv.gz  in=330,007,612 out=81,157,278 elapsed=147.0s

  [9721/15692] intraday_4029.csv.gz  in=330,019,795 out=81,157,278 elapsed=147.0s

  [9722/15692] intraday_4027.csv.gz  in=330,033,046 out=81,157,278 elapsed=147.0s

  [9723/15692] intraday_4030.csv.gz  in=330,044,653 out=81,157,278 elapsed=147.0s

  [9724/15692] intraday_4031.csv.gz  in=330,058,608 out=81,157,278 elapsed=147.0s

  [9725/15692] intraday_4032.csv.gz  in=330,072,583 out=81,157,278 elapsed=147.1s

  [9726/15692] intraday_4034.csv.gz  in=330,085,521 out=81,157,278 elapsed=147.1s

  [9727/15692] intraday_4035.csv.gz  in=330,099,428 out=81,157,278 elapsed=147.1s

  [9728/15692] intraday_4033.csv.gz  in=330,112,774 out=81,157,278 elapsed=147.1s

  [9729/15692] intraday_4036.csv.gz  in=330,126,227 out=81,157,278 elapsed=147.1s

  [9730/15692] intraday_4037.csv.gz  in=330,139,479 out=81,157,278 elapsed=147.1s

  [9731/15692] intraday_4038.csv.gz  in=330,154,086 out=81,157,278 elapsed=147.1s

  [9732/15692] intraday_4040.csv.gz  in=330,166,019 out=81,157,278 elapsed=147.1s

  [9733/15692] intraday_4039.csv.gz  in=330,180,215 out=81,157,278 elapsed=147.1s

  [9734/15692] intraday_4041.csv.gz  in=330,194,560 out=81,157,278 elapsed=147.1s

  [9735/15692] intraday_4042.csv.gz  in=330,206,907 out=81,157,278 elapsed=147.2s

  [9736/15692] intraday_4045.csv.gz  in=330,221,868 out=81,157,278 elapsed=147.2s

  [9737/15692] intraday_4044.csv.gz  in=330,238,074 out=81,157,278 elapsed=147.2s

  [9738/15692] intraday_4043.csv.gz  in=330,252,002 out=81,157,278 elapsed=147.2s

  [9739/15692] intraday_4048.csv.gz  in=330,264,260 out=81,157,278 elapsed=147.2s

  [9740/15692] intraday_4049.csv.gz  in=330,277,230 out=81,157,278 elapsed=147.2s

  [9741/15692] intraday_4046.csv.gz  in=330,290,653 out=81,157,278 elapsed=147.2s

  [9742/15692] intraday_4047.csv.gz  in=330,306,702 out=81,157,278 elapsed=147.2s

  [9743/15692] intraday_4050.csv.gz  in=330,317,789 out=81,157,278 elapsed=147.2s

  [9744/15692] intraday_4053.csv.gz  in=330,331,346 out=81,157,278 elapsed=147.2s

  [9745/15692] intraday_4051.csv.gz  in=330,345,579 out=81,157,278 elapsed=147.3s

  [9746/15692] intraday_4052.csv.gz  in=330,356,106 out=81,157,278 elapsed=147.3s

  [9747/15692] intraday_4054.csv.gz  in=330,369,648 out=81,157,278 elapsed=147.3s

  [9748/15692] intraday_4056.csv.gz  in=330,381,182 out=81,157,278 elapsed=147.3s

  [9749/15692] intraday_4057.csv.gz  in=330,394,617 out=81,157,278 elapsed=147.3s

  [9750/15692] intraday_4055.csv.gz  in=330,411,294 out=81,157,278 elapsed=147.3s

  [9751/15692] intraday_4058.csv.gz  in=330,424,686 out=81,157,278 elapsed=147.3s

  [9752/15692] intraday_4059.csv.gz  in=330,437,151 out=81,157,278 elapsed=147.3s

  [9753/15692] intraday_4060.csv.gz  in=330,451,500 out=81,157,278 elapsed=147.4s

  [9754/15692] intraday_4061.csv.gz  in=330,466,365 out=81,157,278 elapsed=147.4s

  [9755/15692] intraday_4062.csv.gz  in=330,481,187 out=81,157,278 elapsed=147.4s

  [9756/15692] intraday_4063.csv.gz  in=330,494,279 out=81,157,278 elapsed=147.4s

  [9757/15692] intraday_4065.csv.gz  in=330,505,801 out=81,157,278 elapsed=147.4s

  [9758/15692] intraday_4064.csv.gz  in=330,519,416 out=81,157,278 elapsed=147.4s

  [9759/15692] intraday_4066.csv.gz  in=330,531,807 out=81,157,278 elapsed=147.4s

  [9760/15692] intraday_4067.csv.gz  in=330,544,569 out=81,157,278 elapsed=147.4s

  [9761/15692] intraday_4069.csv.gz  in=330,554,241 out=81,157,278 elapsed=147.4s

  [9762/15692] intraday_4068.csv.gz  in=330,568,935 out=81,157,278 elapsed=147.5s

  [9763/15692] intraday_4070.csv.gz  in=330,577,695 out=81,157,278 elapsed=147.5s

  [9764/15692] intraday_4071.csv.gz  in=330,589,564 out=81,157,278 elapsed=147.5s

  [9765/15692] intraday_4072.csv.gz  in=330,589,637 out=81,157,278 elapsed=147.5s

  [9766/15692] intraday_4074.csv.gz  in=330,589,675 out=81,157,278 elapsed=147.5s

  [9767/15692] intraday_4073.csv.gz  in=330,590,720 out=81,157,278 elapsed=147.5s

  [9768/15692] intraday_4075.csv.gz  in=330,590,848 out=81,157,278 elapsed=147.5s

  [9769/15692] intraday_4078.csv.gz  in=330,591,000 out=81,157,278 elapsed=147.5s

  [9770/15692] intraday_4076.csv.gz  in=330,591,031 out=81,157,278 elapsed=147.5s

  [9771/15692] intraday_4079.csv.gz  in=330,591,110 out=81,157,278 elapsed=147.5s

  [9772/15692] intraday_4077.csv.gz  in=330,591,719 out=81,157,278 elapsed=147.5s

  [9773/15692] intraday_4080.csv.gz  in=330,591,748 out=81,157,278 elapsed=147.5s

  [9774/15692] intraday_4082.csv.gz  in=330,591,760 out=81,157,278 elapsed=147.5s

  [9775/15692] intraday_4081.csv.gz  in=330,592,788 out=81,157,278 elapsed=147.5s

  [9776/15692] intraday_4083.csv.gz  in=330,592,796 out=81,157,278 elapsed=147.5s

  [9777/15692] intraday_4085.csv.gz  in=330,592,899 out=81,157,278 elapsed=147.5s

  [9778/15692] intraday_4086.csv.gz  in=330,592,932 out=81,157,278 elapsed=147.6s

  [9779/15692] intraday_4084.csv.gz  in=330,593,657 out=81,157,278 elapsed=147.6s

  [9780/15692] intraday_4087.csv.gz  in=330,594,218 out=81,157,278 elapsed=147.6s

  [9781/15692] intraday_4090.csv.gz  in=330,594,365 out=81,157,278 elapsed=147.6s

  [9782/15692] intraday_4089.csv.gz  in=330,603,245 out=81,157,278 elapsed=147.6s

  [9783/15692] intraday_4088.csv.gz  in=330,607,573 out=81,157,278 elapsed=147.6s

  [9784/15692] intraday_4093.csv.gz  in=330,607,637 out=81,157,278 elapsed=147.6s

  [9785/15692] intraday_4091.csv.gz  in=330,608,166 out=81,157,278 elapsed=147.6s

  [9786/15692] intraday_4094.csv.gz  in=330,609,364 out=81,157,278 elapsed=147.6s

  [9787/15692] intraday_4092.csv.gz  in=330,609,441 out=81,157,278 elapsed=147.6s

  [9788/15692] intraday_4095.csv.gz  in=330,609,554 out=81,157,278 elapsed=147.6s

  [9789/15692] intraday_4096.csv.gz  in=330,609,627 out=81,157,278 elapsed=147.6s

  [9790/15692] intraday_4099.csv.gz  in=330,610,578 out=81,157,278 elapsed=147.6s

  [9791/15692] intraday_4098.csv.gz  in=330,610,597 out=81,157,278 elapsed=147.6s

  [9792/15692] intraday_4100.csv.gz  in=330,617,031 out=81,157,278 elapsed=147.7s

  [9793/15692] intraday_4097.csv.gz  in=330,623,477 out=81,157,278 elapsed=147.7s

  [9794/15692] intraday_4104.csv.gz  in=330,623,509 out=81,157,278 elapsed=147.7s

  [9795/15692] intraday_4102.csv.gz  in=330,624,305 out=81,157,278 elapsed=147.7s

  [9796/15692] intraday_4101.csv.gz  in=330,624,461 out=81,157,278 elapsed=147.7s

  [9797/15692] intraday_4103.csv.gz  in=330,626,946 out=81,157,278 elapsed=147.7s

  [9798/15692] intraday_4105.csv.gz  in=330,627,060 out=81,157,278 elapsed=147.7s

  [9799/15692] intraday_4106.csv.gz  in=330,627,099 out=81,157,278 elapsed=147.7s

  [9800/15692] intraday_4108.csv.gz  in=330,627,512 out=81,157,278 elapsed=147.7s

  [9801/15692] intraday_4107.csv.gz  in=330,635,282 out=81,157,278 elapsed=147.7s

  [9802/15692] intraday_4109.csv.gz  in=330,635,418 out=81,157,278 elapsed=147.7s

  [9803/15692] intraday_4110.csv.gz  in=330,635,554 out=81,157,278 elapsed=147.7s

  [9804/15692] intraday_4112.csv.gz  in=330,635,817 out=81,157,278 elapsed=147.7s

  [9805/15692] intraday_4111.csv.gz  in=330,635,912 out=81,157,278 elapsed=147.7s

  [9806/15692] intraday_4113.csv.gz  in=330,636,051 out=81,157,278 elapsed=147.7s

  [9807/15692] intraday_4114.csv.gz  in=330,636,119 out=81,157,278 elapsed=147.8s

  [9808/15692] intraday_4117.csv.gz  in=330,649,092 out=81,157,278 elapsed=147.8s

  [9809/15692] intraday_4115.csv.gz  in=330,664,662 out=81,157,278 elapsed=147.8s

  [9810/15692] intraday_4116.csv.gz  in=330,679,553 out=81,157,278 elapsed=147.8s

  [9811/15692] intraday_4118.csv.gz  in=330,689,821 out=81,157,278 elapsed=147.8s

  [9812/15692] intraday_4121.csv.gz  in=330,701,994 out=81,157,278 elapsed=147.8s

  [9813/15692] intraday_4120.csv.gz  in=330,716,444 out=81,157,278 elapsed=147.8s

  [9814/15692] intraday_4119.csv.gz  in=330,731,052 out=81,157,278 elapsed=147.8s

  [9815/15692] intraday_4122.csv.gz  in=330,742,940 out=81,157,278 elapsed=147.8s

  [9816/15692] intraday_4123.csv.gz  in=330,757,233 out=81,157,278 elapsed=147.9s

  [9817/15692] intraday_4125.csv.gz  in=330,767,904 out=81,157,278 elapsed=147.9s

  [9818/15692] intraday_4126.csv.gz  in=330,781,921 out=81,157,278 elapsed=147.9s

  [9819/15692] intraday_4124.csv.gz  in=330,797,429 out=81,157,278 elapsed=147.9s

  [9820/15692] intraday_4127.csv.gz  in=330,808,970 out=81,157,278 elapsed=147.9s

  [9821/15692] intraday_4128.csv.gz  in=330,820,512 out=81,157,278 elapsed=147.9s

  [9822/15692] intraday_4129.csv.gz  in=330,831,501 out=81,157,278 elapsed=147.9s

  [9823/15692] intraday_4130.csv.gz  in=330,842,868 out=81,157,278 elapsed=147.9s

  [9824/15692] intraday_4132.csv.gz  in=330,856,836 out=81,157,278 elapsed=147.9s

  [9825/15692] intraday_4131.csv.gz  in=330,870,612 out=81,157,278 elapsed=147.9s

  [9826/15692] intraday_4134.csv.gz  in=330,883,335 out=81,157,278 elapsed=147.9s

  [9827/15692] intraday_4133.csv.gz  in=330,894,042 out=81,157,278 elapsed=147.9s

  [9828/15692] intraday_4135.csv.gz  in=330,908,203 out=81,157,278 elapsed=147.9s

  [9829/15692] intraday_4136.csv.gz  in=330,920,620 out=81,157,278 elapsed=148.0s

  [9830/15692] intraday_4138.csv.gz  in=330,932,963 out=81,157,278 elapsed=148.0s

  [9831/15692] intraday_4137.csv.gz  in=330,944,599 out=81,157,278 elapsed=148.0s

  [9832/15692] intraday_4139.csv.gz  in=330,956,149 out=81,157,278 elapsed=148.0s

  [9833/15692] intraday_4140.csv.gz  in=330,965,953 out=81,157,278 elapsed=148.0s

  [9834/15692] intraday_4141.csv.gz  in=330,979,047 out=81,157,278 elapsed=148.0s

  [9835/15692] intraday_4142.csv.gz  in=330,991,695 out=81,157,278 elapsed=148.0s

  [9836/15692] intraday_4144.csv.gz  in=331,007,185 out=81,157,278 elapsed=148.0s

  [9837/15692] intraday_4143.csv.gz  in=331,019,445 out=81,157,278 elapsed=148.0s

  [9838/15692] intraday_4147.csv.gz  in=331,031,392 out=81,157,278 elapsed=148.0s

  [9839/15692] intraday_4146.csv.gz  in=331,043,479 out=81,157,278 elapsed=148.0s

  [9840/15692] intraday_4145.csv.gz  in=331,058,091 out=81,157,278 elapsed=148.0s

  [9841/15692] intraday_4148.csv.gz  in=331,071,258 out=81,157,278 elapsed=148.0s

  [9842/15692] intraday_4149.csv.gz  in=331,083,216 out=81,157,278 elapsed=148.1s

  [9843/15692] intraday_4151.csv.gz  in=331,093,388 out=81,157,278 elapsed=148.1s

  [9844/15692] intraday_4150.csv.gz  in=331,106,374 out=81,157,278 elapsed=148.1s

  [9845/15692] intraday_4152.csv.gz  in=331,117,438 out=81,157,278 elapsed=148.1s

  [9846/15692] intraday_4153.csv.gz  in=331,129,722 out=81,157,278 elapsed=148.1s

  [9847/15692] intraday_4154.csv.gz  in=331,139,456 out=81,157,278 elapsed=148.1s

  [9848/15692] intraday_4155.csv.gz  in=331,153,953 out=81,157,278 elapsed=148.1s

  [9849/15692] intraday_4156.csv.gz  in=331,166,826 out=81,157,278 elapsed=148.1s

  [9850/15692] intraday_4157.csv.gz  in=331,178,933 out=81,157,278 elapsed=148.1s

  [9851/15692] intraday_4158.csv.gz  in=331,190,168 out=81,157,278 elapsed=148.1s

  [9852/15692] intraday_4159.csv.gz  in=331,201,761 out=81,157,278 elapsed=148.2s

  [9853/15692] intraday_4160.csv.gz  in=331,214,639 out=81,157,278 elapsed=148.2s

  [9854/15692] intraday_4161.csv.gz  in=331,225,484 out=81,157,278 elapsed=148.2s

  [9855/15692] intraday_4162.csv.gz  in=331,237,446 out=81,157,278 elapsed=148.2s

  [9856/15692] intraday_4163.csv.gz  in=331,248,819 out=81,157,278 elapsed=148.2s

  [9857/15692] intraday_4164.csv.gz  in=331,259,545 out=81,157,278 elapsed=148.2s

  [9858/15692] intraday_4165.csv.gz  in=331,270,780 out=81,157,278 elapsed=148.2s

  [9859/15692] intraday_4166.csv.gz  in=331,282,149 out=81,157,278 elapsed=148.2s

  [9860/15692] intraday_4167.csv.gz  in=331,293,420 out=81,157,278 elapsed=148.2s

  [9861/15692] intraday_4168.csv.gz  in=331,306,756 out=81,157,278 elapsed=148.2s

  [9862/15692] intraday_4169.csv.gz  in=331,319,064 out=81,157,278 elapsed=148.2s

  [9863/15692] intraday_4170.csv.gz  in=331,329,636 out=81,157,278 elapsed=148.2s

  [9864/15692] intraday_4171.csv.gz  in=331,340,153 out=81,157,278 elapsed=148.2s

  [9865/15692] intraday_4172.csv.gz  in=331,353,614 out=81,157,278 elapsed=148.2s

  [9866/15692] intraday_4173.csv.gz  in=331,365,822 out=81,157,278 elapsed=148.2s

  [9867/15692] intraday_4174.csv.gz  in=331,377,136 out=81,157,278 elapsed=148.3s

  [9868/15692] intraday_4175.csv.gz  in=331,388,555 out=81,157,278 elapsed=148.3s

  [9869/15692] intraday_4176.csv.gz  in=331,399,969 out=81,157,278 elapsed=148.3s

  [9870/15692] intraday_4177.csv.gz  in=331,411,717 out=81,157,278 elapsed=148.3s

  [9871/15692] intraday_4178.csv.gz  in=331,427,104 out=81,157,278 elapsed=148.3s

  [9872/15692] intraday_4179.csv.gz  in=331,440,164 out=81,157,278 elapsed=148.3s

  [9873/15692] intraday_4180.csv.gz  in=331,452,130 out=81,157,278 elapsed=148.3s

  [9874/15692] intraday_4182.csv.gz  in=331,464,437 out=81,157,278 elapsed=148.3s

  [9875/15692] intraday_4181.csv.gz  in=331,475,943 out=81,157,278 elapsed=148.3s

  [9876/15692] intraday_4183.csv.gz  in=331,485,941 out=81,157,278 elapsed=148.3s

  [9877/15692] intraday_4185.csv.gz  in=331,497,415 out=81,157,278 elapsed=148.4s

  [9878/15692] intraday_4184.csv.gz  in=331,509,505 out=81,157,278 elapsed=148.4s

  [9879/15692] intraday_4186.csv.gz  in=331,523,061 out=81,157,278 elapsed=148.4s

  [9880/15692] intraday_4187.csv.gz  in=331,532,845 out=81,157,278 elapsed=148.4s

  [9881/15692] intraday_4188.csv.gz  in=331,543,678 out=81,157,278 elapsed=148.4s

  [9882/15692] intraday_4190.csv.gz  in=331,557,967 out=81,157,278 elapsed=148.4s

  [9883/15692] intraday_4189.csv.gz  in=331,568,174 out=81,157,278 elapsed=148.4s

  [9884/15692] intraday_4191.csv.gz  in=331,579,980 out=81,157,278 elapsed=148.4s

  [9885/15692] intraday_4192.csv.gz  in=331,593,196 out=81,157,278 elapsed=148.4s

  [9886/15692] intraday_4193.csv.gz  in=331,603,518 out=81,157,278 elapsed=148.5s

  [9887/15692] intraday_4194.csv.gz  in=331,614,280 out=81,157,278 elapsed=148.5s

  [9888/15692] intraday_4195.csv.gz  in=331,626,152 out=81,157,278 elapsed=148.5s

  [9889/15692] intraday_4196.csv.gz  in=331,642,559 out=81,157,278 elapsed=148.5s

  [9890/15692] intraday_4197.csv.gz  in=331,654,080 out=81,157,278 elapsed=148.5s

  [9891/15692] intraday_4198.csv.gz  in=331,665,451 out=81,157,278 elapsed=148.5s

  [9892/15692] intraday_4199.csv.gz  in=331,677,077 out=81,157,278 elapsed=148.5s

  [9893/15692] intraday_4200.csv.gz  in=331,687,756 out=81,157,278 elapsed=148.5s

  [9894/15692] intraday_4201.csv.gz  in=331,701,107 out=81,157,278 elapsed=148.5s

  [9895/15692] intraday_4202.csv.gz  in=331,716,154 out=81,157,278 elapsed=148.5s

  [9896/15692] intraday_4203.csv.gz  in=331,727,994 out=81,157,278 elapsed=148.5s

  [9897/15692] intraday_4204.csv.gz  in=331,741,371 out=81,157,278 elapsed=148.5s

  [9898/15692] intraday_4205.csv.gz  in=331,754,535 out=81,157,278 elapsed=148.5s

  [9899/15692] intraday_4206.csv.gz  in=331,767,954 out=81,157,278 elapsed=148.5s

  [9900/15692] intraday_4207.csv.gz  in=331,790,417 out=81,157,278 elapsed=148.5s

  [9901/15692] intraday_4208.csv.gz  in=331,803,469 out=81,157,278 elapsed=148.5s

  [9902/15692] intraday_4209.csv.gz  in=331,815,302 out=81,157,278 elapsed=148.5s

  [9903/15692] intraday_4210.csv.gz  in=331,826,243 out=81,157,278 elapsed=148.6s

  [9904/15692] intraday_4211.csv.gz  in=331,838,170 out=81,157,278 elapsed=148.6s

  [9905/15692] intraday_4213.csv.gz  in=331,850,124 out=81,157,278 elapsed=148.6s

  [9906/15692] intraday_4212.csv.gz  in=331,861,892 out=81,157,278 elapsed=148.6s

  [9907/15692] intraday_4214.csv.gz  in=331,873,524 out=81,157,278 elapsed=148.6s

  [9908/15692] intraday_4216.csv.gz  in=331,885,505 out=81,157,278 elapsed=148.6s

  [9909/15692] intraday_4215.csv.gz  in=331,898,791 out=81,157,278 elapsed=148.6s

  [9910/15692] intraday_4217.csv.gz  in=331,911,277 out=81,157,278 elapsed=148.6s

  [9911/15692] intraday_4218.csv.gz  in=331,926,679 out=81,157,278 elapsed=148.6s

  [9912/15692] intraday_4219.csv.gz  in=331,937,758 out=81,157,278 elapsed=148.6s

  [9913/15692] intraday_4220.csv.gz  in=331,948,616 out=81,157,278 elapsed=148.7s

  [9914/15692] intraday_4221.csv.gz  in=331,963,091 out=81,157,278 elapsed=148.7s

  [9915/15692] intraday_4222.csv.gz  in=331,977,809 out=81,157,278 elapsed=148.7s

  [9916/15692] intraday_4223.csv.gz  in=331,989,530 out=81,157,278 elapsed=148.7s

  [9917/15692] intraday_4224.csv.gz  in=332,002,514 out=81,157,278 elapsed=148.7s

  [9918/15692] intraday_4225.csv.gz  in=332,015,902 out=81,157,278 elapsed=148.7s

  [9919/15692] intraday_4226.csv.gz  in=332,027,870 out=81,157,278 elapsed=148.7s

  [9920/15692] intraday_4228.csv.gz  in=332,041,261 out=81,157,278 elapsed=148.7s

  [9921/15692] intraday_4229.csv.gz  in=332,054,657 out=81,157,278 elapsed=148.7s

  [9922/15692] intraday_4227.csv.gz  in=332,070,170 out=81,157,278 elapsed=148.7s

  [9923/15692] intraday_4230.csv.gz  in=332,086,553 out=81,157,278 elapsed=148.8s

  [9924/15692] intraday_4231.csv.gz  in=332,099,234 out=81,157,278 elapsed=148.8s

  [9925/15692] intraday_4232.csv.gz  in=332,111,378 out=81,157,278 elapsed=148.8s

  [9926/15692] intraday_4233.csv.gz  in=332,122,369 out=81,157,278 elapsed=148.8s

  [9927/15692] intraday_4234.csv.gz  in=332,133,741 out=81,157,278 elapsed=148.8s

  [9928/15692] intraday_4235.csv.gz  in=332,145,263 out=81,157,278 elapsed=148.8s

  [9929/15692] intraday_4236.csv.gz  in=332,158,279 out=81,157,278 elapsed=148.8s

  [9930/15692] intraday_4237.csv.gz  in=332,170,569 out=81,157,278 elapsed=148.8s

  [9931/15692] intraday_4239.csv.gz  in=332,183,366 out=81,157,278 elapsed=148.8s

  [9932/15692] intraday_4238.csv.gz  in=332,198,915 out=81,157,278 elapsed=148.8s

  [9933/15692] intraday_4240.csv.gz  in=332,212,357 out=81,157,278 elapsed=148.8s

  [9934/15692] intraday_4242.csv.gz  in=332,225,833 out=81,157,278 elapsed=148.9s

  [9935/15692] intraday_4241.csv.gz  in=332,238,323 out=81,157,278 elapsed=148.9s

  [9936/15692] intraday_4243.csv.gz  in=332,250,225 out=81,157,278 elapsed=148.9s

  [9937/15692] intraday_4244.csv.gz  in=332,262,825 out=81,157,278 elapsed=148.9s

  [9938/15692] intraday_4245.csv.gz  in=332,277,199 out=81,157,278 elapsed=148.9s

  [9939/15692] intraday_4247.csv.gz  in=332,290,328 out=81,157,278 elapsed=148.9s

  [9940/15692] intraday_4246.csv.gz  in=332,304,442 out=81,157,278 elapsed=148.9s

  [9941/15692] intraday_4248.csv.gz  in=332,316,343 out=81,157,278 elapsed=148.9s

  [9942/15692] intraday_4249.csv.gz  in=332,326,649 out=81,157,278 elapsed=148.9s

  [9943/15692] intraday_4250.csv.gz  in=332,339,571 out=81,157,278 elapsed=148.9s

  [9944/15692] intraday_4251.csv.gz  in=332,350,978 out=81,157,278 elapsed=148.9s

  [9945/15692] intraday_4252.csv.gz  in=332,363,445 out=81,157,278 elapsed=148.9s

  [9946/15692] intraday_4253.csv.gz  in=332,371,032 out=81,157,278 elapsed=149.0s

  [9947/15692] intraday_4254.csv.gz  in=332,381,337 out=81,157,278 elapsed=149.0s

  [9948/15692] intraday_4255.csv.gz  in=332,388,596 out=81,157,278 elapsed=149.0s

  [9949/15692] intraday_4257.csv.gz  in=332,402,615 out=81,157,278 elapsed=149.0s

  [9950/15692] intraday_4256.csv.gz  in=332,418,398 out=81,157,278 elapsed=149.0s

  [9951/15692] intraday_4259.csv.gz  in=332,428,546 out=81,157,278 elapsed=149.0s

  [9952/15692] intraday_4258.csv.gz  in=332,441,009 out=81,157,278 elapsed=149.0s

  [9953/15692] intraday_4260.csv.gz  in=332,455,935 out=81,157,278 elapsed=149.0s

  [9954/15692] intraday_4261.csv.gz  in=332,470,334 out=81,157,278 elapsed=149.0s

  [9955/15692] intraday_4263.csv.gz  in=332,482,544 out=81,157,278 elapsed=149.0s

  [9956/15692] intraday_4262.csv.gz  in=332,495,064 out=81,157,278 elapsed=149.0s

  [9957/15692] intraday_4264.csv.gz  in=332,509,549 out=81,157,278 elapsed=149.0s

  [9958/15692] intraday_4266.csv.gz  in=332,520,737 out=81,157,278 elapsed=149.1s

  [9959/15692] intraday_4265.csv.gz  in=332,536,427 out=81,157,278 elapsed=149.1s

  [9960/15692] intraday_4267.csv.gz  in=332,549,504 out=81,157,278 elapsed=149.1s

  [9961/15692] intraday_4268.csv.gz  in=332,561,865 out=81,157,278 elapsed=149.1s

  [9962/15692] intraday_4270.csv.gz  in=332,573,127 out=81,157,278 elapsed=149.1s

  [9963/15692] intraday_4269.csv.gz  in=332,585,139 out=81,157,278 elapsed=149.1s

  [9964/15692] intraday_4271.csv.gz  in=332,596,635 out=81,157,278 elapsed=149.1s

  [9965/15692] intraday_4272.csv.gz  in=332,611,024 out=81,157,278 elapsed=149.1s

  [9966/15692] intraday_4273.csv.gz  in=332,624,209 out=81,157,278 elapsed=149.1s

  [9967/15692] intraday_4274.csv.gz  in=332,634,545 out=81,157,278 elapsed=149.1s

  [9968/15692] intraday_4275.csv.gz  in=332,647,298 out=81,157,278 elapsed=149.2s

  [9969/15692] intraday_4277.csv.gz  in=332,660,215 out=81,157,278 elapsed=149.2s

  [9970/15692] intraday_4276.csv.gz  in=332,674,329 out=81,157,278 elapsed=149.2s

  [9971/15692] intraday_4278.csv.gz  in=332,686,488 out=81,157,278 elapsed=149.2s

  [9972/15692] intraday_4279.csv.gz  in=332,699,171 out=81,157,278 elapsed=149.2s

  [9973/15692] intraday_4281.csv.gz  in=332,710,352 out=81,157,278 elapsed=149.2s

  [9974/15692] intraday_4280.csv.gz  in=332,722,728 out=81,157,278 elapsed=149.2s

  [9975/15692] intraday_4282.csv.gz  in=332,736,238 out=81,157,278 elapsed=149.2s

  [9976/15692] intraday_4283.csv.gz  in=332,749,328 out=81,157,278 elapsed=149.2s

  [9977/15692] intraday_4286.csv.gz  in=332,763,212 out=81,157,278 elapsed=149.3s

  [9978/15692] intraday_4285.csv.gz  in=332,777,602 out=81,157,278 elapsed=149.3s

  [9979/15692] intraday_4284.csv.gz  in=332,791,580 out=81,157,278 elapsed=149.3s

  [9980/15692] intraday_4287.csv.gz  in=332,802,667 out=81,157,278 elapsed=149.3s

  [9981/15692] intraday_4288.csv.gz  in=332,814,914 out=81,157,278 elapsed=149.3s

  [9982/15692] intraday_4289.csv.gz  in=332,828,130 out=81,157,278 elapsed=149.3s

  [9983/15692] intraday_4291.csv.gz  in=332,840,256 out=81,157,278 elapsed=149.3s

  [9984/15692] intraday_4290.csv.gz  in=332,852,118 out=81,157,278 elapsed=149.3s

  [9985/15692] intraday_4292.csv.gz  in=332,863,748 out=81,157,278 elapsed=149.3s

  [9986/15692] intraday_4294.csv.gz  in=332,875,359 out=81,157,278 elapsed=149.3s

  [9987/15692] intraday_4295.csv.gz  in=332,886,874 out=81,157,278 elapsed=149.3s

  [9988/15692] intraday_4293.csv.gz  in=332,900,132 out=81,157,278 elapsed=149.4s

  [9989/15692] intraday_4296.csv.gz  in=332,913,729 out=81,157,278 elapsed=149.4s

  [9990/15692] intraday_4299.csv.gz  in=332,925,038 out=81,157,278 elapsed=149.4s

  [9991/15692] intraday_4298.csv.gz  in=332,938,586 out=81,157,278 elapsed=149.4s

  [9992/15692] intraday_4297.csv.gz  in=332,949,754 out=81,157,278 elapsed=149.4s

  [9993/15692] intraday_4300.csv.gz  in=332,962,456 out=81,157,278 elapsed=149.4s

  [9994/15692] intraday_4303.csv.gz  in=332,974,953 out=81,157,278 elapsed=149.4s

  [9995/15692] intraday_4302.csv.gz  in=332,986,155 out=81,157,278 elapsed=149.4s

  [9996/15692] intraday_4301.csv.gz  in=332,998,762 out=81,157,278 elapsed=149.4s

  [9997/15692] intraday_4304.csv.gz  in=333,010,032 out=81,157,278 elapsed=149.4s

  [9998/15692] intraday_4305.csv.gz  in=333,019,560 out=81,157,278 elapsed=149.4s

  [9999/15692] intraday_4306.csv.gz  in=333,033,245 out=81,157,278 elapsed=149.5s

  [10000/15692] intraday_4308.csv.gz  in=333,044,561 out=81,157,278 elapsed=149.5s

  [10001/15692] intraday_4307.csv.gz  in=333,055,805 out=81,157,278 elapsed=149.5s

  [10002/15692] intraday_4309.csv.gz  in=333,068,814 out=81,157,278 elapsed=149.5s

  [10003/15692] intraday_4311.csv.gz  in=333,079,728 out=81,157,278 elapsed=149.5s

  [10004/15692] intraday_4310.csv.gz  in=333,092,166 out=81,157,278 elapsed=149.5s

  [10005/15692] intraday_4312.csv.gz  in=333,102,875 out=81,157,278 elapsed=149.5s

  [10006/15692] intraday_4313.csv.gz  in=333,117,183 out=81,157,278 elapsed=149.5s

  [10007/15692] intraday_4315.csv.gz  in=333,129,449 out=81,157,278 elapsed=149.5s

  [10008/15692] intraday_4314.csv.gz  in=333,141,797 out=81,157,278 elapsed=149.5s

  [10009/15692] intraday_4316.csv.gz  in=333,152,733 out=81,157,278 elapsed=149.6s

  [10010/15692] intraday_4318.csv.gz  in=333,163,931 out=81,157,278 elapsed=149.6s

  [10011/15692] intraday_4317.csv.gz  in=333,175,823 out=81,157,278 elapsed=149.6s

  [10012/15692] intraday_4320.csv.gz  in=333,188,436 out=81,157,278 elapsed=149.6s

  [10013/15692] intraday_4319.csv.gz  in=333,202,936 out=81,157,278 elapsed=149.6s

  [10014/15692] intraday_4321.csv.gz  in=333,216,116 out=81,157,278 elapsed=149.6s

  [10015/15692] intraday_4323.csv.gz  in=333,232,794 out=81,157,278 elapsed=149.6s

  [10016/15692] intraday_4322.csv.gz  in=333,245,214 out=81,157,278 elapsed=149.6s

  [10017/15692] intraday_4324.csv.gz  in=333,256,349 out=81,157,278 elapsed=149.6s

  [10018/15692] intraday_4325.csv.gz  in=333,267,868 out=81,157,278 elapsed=149.6s

  [10019/15692] intraday_4326.csv.gz  in=333,278,702 out=81,157,278 elapsed=149.7s

  [10020/15692] intraday_4327.csv.gz  in=333,292,374 out=81,157,278 elapsed=149.7s

  [10021/15692] intraday_4328.csv.gz  in=333,303,268 out=81,157,278 elapsed=149.7s

  [10022/15692] intraday_4329.csv.gz  in=333,313,758 out=81,157,278 elapsed=149.7s

  [10023/15692] intraday_4330.csv.gz  in=333,326,057 out=81,157,278 elapsed=149.7s

  [10024/15692] intraday_4331.csv.gz  in=333,340,021 out=81,157,278 elapsed=149.7s

  [10025/15692] intraday_4333.csv.gz  in=333,351,934 out=81,157,278 elapsed=149.7s

  [10026/15692] intraday_4332.csv.gz  in=333,362,995 out=81,157,278 elapsed=149.7s

  [10027/15692] intraday_4334.csv.gz  in=333,373,466 out=81,157,278 elapsed=149.7s

  [10028/15692] intraday_4335.csv.gz  in=333,385,604 out=81,157,278 elapsed=149.7s

  [10029/15692] intraday_4336.csv.gz  in=333,398,661 out=81,157,278 elapsed=149.7s

  [10030/15692] intraday_4337.csv.gz  in=333,413,768 out=81,157,278 elapsed=149.7s

  [10031/15692] intraday_4338.csv.gz  in=333,425,076 out=81,157,278 elapsed=149.8s

  [10032/15692] intraday_4339.csv.gz  in=333,435,963 out=81,157,278 elapsed=149.8s

  [10033/15692] intraday_4340.csv.gz  in=333,446,705 out=81,157,278 elapsed=149.8s

  [10034/15692] intraday_4342.csv.gz  in=333,459,745 out=81,157,278 elapsed=149.8s

  [10035/15692] intraday_4341.csv.gz  in=333,472,883 out=81,157,278 elapsed=149.8s

  [10036/15692] intraday_4343.csv.gz  in=333,487,939 out=81,157,278 elapsed=149.8s

  [10037/15692] intraday_4344.csv.gz  in=333,498,908 out=81,157,278 elapsed=149.8s

  [10038/15692] intraday_4345.csv.gz  in=333,513,006 out=81,157,278 elapsed=149.8s

  [10039/15692] intraday_4346.csv.gz  in=333,526,683 out=81,157,278 elapsed=149.8s

  [10040/15692] intraday_4347.csv.gz  in=333,541,264 out=81,157,278 elapsed=149.8s

  [10041/15692] intraday_4348.csv.gz  in=333,556,408 out=81,157,278 elapsed=149.8s

  [10042/15692] intraday_4349.csv.gz  in=333,569,143 out=81,157,278 elapsed=149.8s

  [10043/15692] intraday_4350.csv.gz  in=333,580,665 out=81,157,278 elapsed=149.8s

  [10044/15692] intraday_4351.csv.gz  in=333,593,224 out=81,157,278 elapsed=149.8s

  [10045/15692] intraday_4352.csv.gz  in=333,604,038 out=81,157,278 elapsed=149.9s

  [10046/15692] intraday_4353.csv.gz  in=333,615,079 out=81,157,278 elapsed=149.9s

  [10047/15692] intraday_4354.csv.gz  in=333,626,818 out=81,157,278 elapsed=149.9s

  [10048/15692] intraday_4355.csv.gz  in=333,639,879 out=81,157,278 elapsed=149.9s

  [10049/15692] intraday_4356.csv.gz  in=333,652,670 out=81,157,278 elapsed=149.9s

  [10050/15692] intraday_4357.csv.gz  in=333,664,743 out=81,157,278 elapsed=149.9s

  [10051/15692] intraday_4358.csv.gz  in=333,677,431 out=81,157,278 elapsed=149.9s

  [10052/15692] intraday_4359.csv.gz  in=333,690,775 out=81,157,278 elapsed=149.9s

  [10053/15692] intraday_4360.csv.gz  in=333,703,440 out=81,157,278 elapsed=149.9s

  [10054/15692] intraday_4361.csv.gz  in=333,716,346 out=81,157,278 elapsed=149.9s

  [10055/15692] intraday_4362.csv.gz  in=333,729,219 out=81,157,278 elapsed=149.9s

  [10056/15692] intraday_4363.csv.gz  in=333,743,177 out=81,157,278 elapsed=150.0s

  [10057/15692] intraday_4364.csv.gz  in=333,754,747 out=81,157,278 elapsed=150.0s

  [10058/15692] intraday_4366.csv.gz  in=333,767,183 out=81,157,278 elapsed=150.0s

  [10059/15692] intraday_4367.csv.gz  in=333,780,728 out=81,157,278 elapsed=150.0s

  [10060/15692] intraday_4365.csv.gz  in=333,795,967 out=81,157,278 elapsed=150.0s

  [10061/15692] intraday_4368.csv.gz  in=333,809,594 out=81,157,278 elapsed=150.0s

  [10062/15692] intraday_4369.csv.gz  in=333,823,852 out=81,157,278 elapsed=150.0s

  [10063/15692] intraday_4370.csv.gz  in=333,837,848 out=81,157,278 elapsed=150.0s

  [10064/15692] intraday_4371.csv.gz  in=333,853,347 out=81,157,278 elapsed=150.0s

  [10065/15692] intraday_4372.csv.gz  in=333,873,798 out=81,157,278 elapsed=150.1s

  [10066/15692] intraday_4373.csv.gz  in=333,885,594 out=81,157,278 elapsed=150.1s

  [10067/15692] intraday_4374.csv.gz  in=333,896,144 out=81,157,278 elapsed=150.1s

  [10068/15692] intraday_4375.csv.gz  in=333,910,003 out=81,157,278 elapsed=150.1s

  [10069/15692] intraday_4376.csv.gz  in=333,919,634 out=81,157,278 elapsed=150.1s

  [10070/15692] intraday_4377.csv.gz  in=333,932,975 out=81,157,278 elapsed=150.1s

  [10071/15692] intraday_4380.csv.gz  in=333,945,029 out=81,157,278 elapsed=150.1s

  [10072/15692] intraday_4379.csv.gz  in=333,959,817 out=81,157,278 elapsed=150.1s

  [10073/15692] intraday_4378.csv.gz  in=333,972,719 out=81,157,278 elapsed=150.1s

  [10074/15692] intraday_4381.csv.gz  in=333,985,570 out=81,157,278 elapsed=150.1s

  [10075/15692] intraday_4383.csv.gz  in=333,998,781 out=81,157,278 elapsed=150.2s

  [10076/15692] intraday_4382.csv.gz  in=334,012,093 out=81,157,278 elapsed=150.2s

  [10077/15692] intraday_4384.csv.gz  in=334,023,975 out=81,157,278 elapsed=150.2s

  [10078/15692] intraday_4385.csv.gz  in=334,038,397 out=81,157,278 elapsed=150.2s

  [10079/15692] intraday_4386.csv.gz  in=334,053,379 out=81,157,278 elapsed=150.2s

  [10080/15692] intraday_4388.csv.gz  in=334,067,632 out=81,157,278 elapsed=150.2s

  [10081/15692] intraday_4387.csv.gz  in=334,079,988 out=81,157,278 elapsed=150.2s

  [10082/15692] intraday_4389.csv.gz  in=334,091,030 out=81,157,278 elapsed=150.2s

  [10083/15692] intraday_4391.csv.gz  in=334,103,855 out=81,157,278 elapsed=150.2s

  [10084/15692] intraday_4390.csv.gz  in=334,115,098 out=81,157,278 elapsed=150.3s

  [10085/15692] intraday_4393.csv.gz  in=334,123,976 out=81,157,278 elapsed=150.3s

  [10086/15692] intraday_4392.csv.gz  in=334,137,028 out=81,157,278 elapsed=150.3s

  [10087/15692] intraday_4396.csv.gz  in=334,138,350 out=81,157,278 elapsed=150.3s

  [10088/15692] intraday_4394.csv.gz  in=334,146,651 out=81,157,278 elapsed=150.3s

  [10089/15692] intraday_4395.csv.gz  in=334,158,448 out=81,157,278 elapsed=150.3s

  [10090/15692] intraday_4397.csv.gz  in=334,173,362 out=81,157,278 elapsed=150.3s

  [10091/15692] intraday_4400.csv.gz  in=334,184,053 out=81,157,278 elapsed=150.3s

  [10092/15692] intraday_4398.csv.gz  in=334,198,902 out=81,157,278 elapsed=150.3s

  [10093/15692] intraday_4399.csv.gz  in=334,211,567 out=81,157,278 elapsed=150.3s

  [10094/15692] intraday_4402.csv.gz  in=334,226,276 out=81,157,278 elapsed=150.4s

  [10095/15692] intraday_4401.csv.gz  in=334,241,461 out=81,157,278 elapsed=150.4s

  [10096/15692] intraday_4403.csv.gz  in=334,254,114 out=81,157,278 elapsed=150.4s

  [10097/15692] intraday_4404.csv.gz  in=334,265,368 out=81,157,278 elapsed=150.4s

  [10098/15692] intraday_4405.csv.gz  in=334,279,122 out=81,157,278 elapsed=150.4s

  [10099/15692] intraday_4407.csv.gz  in=334,289,085 out=81,157,278 elapsed=150.4s

  [10100/15692] intraday_4406.csv.gz  in=334,304,768 out=81,157,278 elapsed=150.4s

  [10101/15692] intraday_4410.csv.gz  in=334,317,538 out=81,157,278 elapsed=150.4s

  [10102/15692] intraday_4409.csv.gz  in=334,331,755 out=81,157,278 elapsed=150.4s

  [10103/15692] intraday_4408.csv.gz  in=334,344,455 out=81,157,278 elapsed=150.5s

  [10104/15692] intraday_4411.csv.gz  in=334,355,395 out=81,157,278 elapsed=150.5s

  [10105/15692] intraday_4412.csv.gz  in=334,366,839 out=81,157,278 elapsed=150.5s

  [10106/15692] intraday_4413.csv.gz  in=334,380,092 out=81,157,278 elapsed=150.5s

  [10107/15692] intraday_4414.csv.gz  in=334,393,151 out=81,157,278 elapsed=150.5s

  [10108/15692] intraday_4416.csv.gz  in=334,406,449 out=81,157,278 elapsed=150.5s

  [10109/15692] intraday_4415.csv.gz  in=334,417,625 out=81,157,278 elapsed=150.5s

  [10110/15692] intraday_4417.csv.gz  in=334,431,084 out=81,157,278 elapsed=150.5s

  [10111/15692] intraday_4418.csv.gz  in=334,443,198 out=81,157,278 elapsed=150.5s

  [10112/15692] intraday_4420.csv.gz  in=334,455,898 out=81,157,278 elapsed=150.5s

  [10113/15692] intraday_4419.csv.gz  in=334,467,532 out=81,157,278 elapsed=150.6s

  [10114/15692] intraday_4422.csv.gz  in=334,477,862 out=81,157,278 elapsed=150.6s

  [10115/15692] intraday_4423.csv.gz  in=334,490,777 out=81,157,278 elapsed=150.6s

  [10116/15692] intraday_4421.csv.gz  in=334,502,743 out=81,157,278 elapsed=150.6s

  [10117/15692] intraday_4424.csv.gz  in=334,515,126 out=81,157,278 elapsed=150.6s

  [10118/15692] intraday_4425.csv.gz  in=334,529,375 out=81,157,278 elapsed=150.6s

  [10119/15692] intraday_4427.csv.gz  in=334,543,043 out=81,157,278 elapsed=150.6s

  [10120/15692] intraday_4426.csv.gz  in=334,558,542 out=81,157,278 elapsed=150.6s

  [10121/15692] intraday_4429.csv.gz  in=334,570,707 out=81,157,278 elapsed=150.6s

  [10122/15692] intraday_4428.csv.gz  in=334,582,281 out=81,157,278 elapsed=150.6s

  [10123/15692] intraday_4430.csv.gz  in=334,595,402 out=81,157,278 elapsed=150.6s

  [10124/15692] intraday_4431.csv.gz  in=334,606,847 out=81,157,278 elapsed=150.6s

  [10125/15692] intraday_4433.csv.gz  in=334,617,691 out=81,157,278 elapsed=150.7s

  [10126/15692] intraday_4435.csv.gz  in=334,628,595 out=81,157,278 elapsed=150.7s

  [10127/15692] intraday_4432.csv.gz  in=334,640,648 out=81,157,278 elapsed=150.7s

  [10128/15692] intraday_4434.csv.gz  in=334,651,608 out=81,157,278 elapsed=150.7s

  [10129/15692] intraday_4436.csv.gz  in=334,663,867 out=81,157,278 elapsed=150.7s

  [10130/15692] intraday_4439.csv.gz  in=334,676,955 out=81,157,278 elapsed=150.7s

  [10131/15692] intraday_4437.csv.gz  in=334,695,568 out=81,157,278 elapsed=150.7s

  [10132/15692] intraday_4438.csv.gz  in=334,707,173 out=81,157,278 elapsed=150.7s

  [10133/15692] intraday_4440.csv.gz  in=334,718,146 out=81,157,278 elapsed=150.7s

  [10134/15692] intraday_4441.csv.gz  in=334,730,019 out=81,157,278 elapsed=150.7s

  [10135/15692] intraday_4442.csv.gz  in=334,742,740 out=81,157,278 elapsed=150.8s

  [10136/15692] intraday_4443.csv.gz  in=334,753,742 out=81,157,278 elapsed=150.8s

  [10137/15692] intraday_4444.csv.gz  in=334,766,132 out=81,157,278 elapsed=150.8s

  [10138/15692] intraday_4445.csv.gz  in=334,780,010 out=81,157,278 elapsed=150.8s

  [10139/15692] intraday_4446.csv.gz  in=334,789,947 out=81,157,278 elapsed=150.8s

  [10140/15692] intraday_4449.csv.gz  in=334,801,006 out=81,157,278 elapsed=150.8s

  [10141/15692] intraday_4448.csv.gz  in=334,811,916 out=81,157,278 elapsed=150.8s

  [10142/15692] intraday_4447.csv.gz  in=334,825,118 out=81,157,278 elapsed=150.8s

  [10143/15692] intraday_4450.csv.gz  in=334,838,189 out=81,157,278 elapsed=150.8s

  [10144/15692] intraday_4453.csv.gz  in=334,848,314 out=81,157,278 elapsed=150.8s

  [10145/15692] intraday_4451.csv.gz  in=334,861,179 out=81,157,278 elapsed=150.9s

  [10146/15692] intraday_4452.csv.gz  in=334,872,733 out=81,157,278 elapsed=150.9s

  [10147/15692] intraday_4454.csv.gz  in=334,886,327 out=81,157,278 elapsed=150.9s

  [10148/15692] intraday_4456.csv.gz  in=334,898,408 out=81,157,278 elapsed=150.9s

  [10149/15692] intraday_4457.csv.gz  in=334,909,173 out=81,157,278 elapsed=150.9s

  [10150/15692] intraday_4455.csv.gz  in=334,921,028 out=81,157,278 elapsed=150.9s

  [10151/15692] intraday_4458.csv.gz  in=334,932,832 out=81,157,278 elapsed=150.9s

  [10152/15692] intraday_4460.csv.gz  in=334,946,647 out=81,157,278 elapsed=150.9s

  [10153/15692] intraday_4459.csv.gz  in=334,957,739 out=81,157,278 elapsed=150.9s

  [10154/15692] intraday_4463.csv.gz  in=334,969,967 out=81,157,278 elapsed=150.9s

  [10155/15692] intraday_4462.csv.gz  in=334,983,318 out=81,157,278 elapsed=150.9s

  [10156/15692] intraday_4464.csv.gz  in=334,994,127 out=81,157,278 elapsed=151.0s

  [10157/15692] intraday_4461.csv.gz  in=335,006,983 out=81,157,278 elapsed=151.0s

  [10158/15692] intraday_4466.csv.gz  in=335,018,556 out=81,157,278 elapsed=151.0s

  [10159/15692] intraday_4467.csv.gz  in=335,029,923 out=81,157,278 elapsed=151.0s

  [10160/15692] intraday_4465.csv.gz  in=335,041,382 out=81,157,278 elapsed=151.0s

  [10161/15692] intraday_4468.csv.gz  in=335,054,423 out=81,157,278 elapsed=151.0s

  [10162/15692] intraday_4470.csv.gz  in=335,064,373 out=81,157,278 elapsed=151.0s

  [10163/15692] intraday_4469.csv.gz  in=335,075,308 out=81,157,278 elapsed=151.0s

  [10164/15692] intraday_4471.csv.gz  in=335,087,480 out=81,157,278 elapsed=151.0s

  [10165/15692] intraday_4473.csv.gz  in=335,097,981 out=81,157,278 elapsed=151.0s

  [10166/15692] intraday_4472.csv.gz  in=335,113,068 out=81,157,278 elapsed=151.0s

  [10167/15692] intraday_4474.csv.gz  in=335,125,098 out=81,157,278 elapsed=151.1s

  [10168/15692] intraday_4475.csv.gz  in=335,135,101 out=81,157,278 elapsed=151.1s

  [10169/15692] intraday_4476.csv.gz  in=335,146,458 out=81,157,278 elapsed=151.1s

  [10170/15692] intraday_4477.csv.gz  in=335,159,738 out=81,157,278 elapsed=151.1s

  [10171/15692] intraday_4479.csv.gz  in=335,170,991 out=81,157,278 elapsed=151.1s

  [10172/15692] intraday_4478.csv.gz  in=335,186,259 out=81,157,278 elapsed=151.1s

  [10173/15692] intraday_4480.csv.gz  in=335,197,327 out=81,157,278 elapsed=151.1s

  [10174/15692] intraday_4482.csv.gz  in=335,210,644 out=81,157,278 elapsed=151.1s

  [10175/15692] intraday_4481.csv.gz  in=335,229,281 out=81,157,278 elapsed=151.1s

  [10176/15692] intraday_4484.csv.gz  in=335,244,229 out=81,157,278 elapsed=151.1s

  [10177/15692] intraday_4483.csv.gz  in=335,257,504 out=81,157,278 elapsed=151.1s

  [10178/15692] intraday_4485.csv.gz  in=335,268,049 out=81,157,278 elapsed=151.2s

  [10179/15692] intraday_4487.csv.gz  in=335,281,089 out=81,157,278 elapsed=151.2s

  [10180/15692] intraday_4488.csv.gz  in=335,295,684 out=81,157,278 elapsed=151.2s

  [10181/15692] intraday_4486.csv.gz  in=335,310,302 out=81,157,278 elapsed=151.2s

  [10182/15692] intraday_4490.csv.gz  in=335,322,567 out=81,157,278 elapsed=151.2s

  [10183/15692] intraday_4489.csv.gz  in=335,335,586 out=81,157,278 elapsed=151.2s

  [10184/15692] intraday_4494.csv.gz  in=335,346,581 out=81,157,278 elapsed=151.2s

  [10185/15692] intraday_4491.csv.gz  in=335,358,069 out=81,157,278 elapsed=151.2s

  [10186/15692] intraday_4492.csv.gz  in=335,369,819 out=81,157,278 elapsed=151.2s

  [10187/15692] intraday_4493.csv.gz  in=335,381,094 out=81,157,278 elapsed=151.2s

  [10188/15692] intraday_4498.csv.gz  in=335,393,165 out=81,157,278 elapsed=151.2s

  [10189/15692] intraday_4496.csv.gz  in=335,404,301 out=81,157,278 elapsed=151.3s

  [10190/15692] intraday_4495.csv.gz  in=335,416,304 out=81,157,278 elapsed=151.3s

  [10191/15692] intraday_4497.csv.gz  in=335,429,510 out=81,157,278 elapsed=151.3s

  [10192/15692] intraday_4499.csv.gz  in=335,442,259 out=81,157,278 elapsed=151.3s

  [10193/15692] intraday_4501.csv.gz  in=335,455,346 out=81,157,278 elapsed=151.3s

  [10194/15692] intraday_4500.csv.gz  in=335,468,343 out=81,157,278 elapsed=151.3s

  [10195/15692] intraday_4502.csv.gz  in=335,485,849 out=81,157,278 elapsed=151.3s

  [10196/15692] intraday_4503.csv.gz  in=335,498,942 out=81,157,278 elapsed=151.3s

  [10197/15692] intraday_4504.csv.gz  in=335,513,072 out=81,157,278 elapsed=151.3s

  [10198/15692] intraday_4505.csv.gz  in=335,523,647 out=81,157,278 elapsed=151.3s

  [10199/15692] intraday_4506.csv.gz  in=335,538,457 out=81,157,278 elapsed=151.3s

  [10200/15692] intraday_4507.csv.gz  in=335,550,477 out=81,157,278 elapsed=151.3s

  [10201/15692] intraday_4508.csv.gz  in=335,564,271 out=81,157,278 elapsed=151.3s

  [10202/15692] intraday_4509.csv.gz  in=335,577,923 out=81,157,278 elapsed=151.4s

  [10203/15692] intraday_4510.csv.gz  in=335,592,108 out=81,157,278 elapsed=151.4s

  [10204/15692] intraday_4511.csv.gz  in=335,604,771 out=81,157,278 elapsed=151.4s

  [10205/15692] intraday_4512.csv.gz  in=335,620,610 out=81,157,278 elapsed=151.4s

  [10206/15692] intraday_4513.csv.gz  in=335,633,368 out=81,157,278 elapsed=151.4s

  [10207/15692] intraday_4514.csv.gz  in=335,644,916 out=81,157,278 elapsed=151.4s

  [10208/15692] intraday_4515.csv.gz  in=335,656,180 out=81,157,278 elapsed=151.4s

  [10209/15692] intraday_4516.csv.gz  in=335,670,384 out=81,157,278 elapsed=151.4s

  [10210/15692] intraday_4517.csv.gz  in=335,680,383 out=81,157,278 elapsed=151.4s

  [10211/15692] intraday_4518.csv.gz  in=335,694,487 out=81,157,278 elapsed=151.4s

  [10212/15692] intraday_4519.csv.gz  in=335,708,413 out=81,157,278 elapsed=151.4s

  [10213/15692] intraday_4520.csv.gz  in=335,725,105 out=81,157,278 elapsed=151.4s

  [10214/15692] intraday_4521.csv.gz  in=335,736,112 out=81,157,278 elapsed=151.4s

  [10215/15692] intraday_4522.csv.gz  in=335,748,964 out=81,157,278 elapsed=151.4s

  [10216/15692] intraday_4523.csv.gz  in=335,762,195 out=81,157,278 elapsed=151.4s

  [10217/15692] intraday_4524.csv.gz  in=335,774,179 out=81,157,278 elapsed=151.4s

  [10218/15692] intraday_4525.csv.gz  in=335,785,927 out=81,157,278 elapsed=151.5s

  [10219/15692] intraday_4526.csv.gz  in=335,800,366 out=81,157,278 elapsed=151.5s

  [10220/15692] intraday_4527.csv.gz  in=335,815,537 out=81,157,278 elapsed=151.5s

  [10221/15692] intraday_4529.csv.gz  in=335,829,291 out=81,157,278 elapsed=151.5s

  [10222/15692] intraday_4528.csv.gz  in=335,841,835 out=81,157,278 elapsed=151.5s

  [10223/15692] intraday_4531.csv.gz  in=335,853,040 out=81,157,278 elapsed=151.5s

  [10224/15692] intraday_4530.csv.gz  in=335,864,240 out=81,157,278 elapsed=151.5s

  [10225/15692] intraday_4532.csv.gz  in=335,876,568 out=81,157,278 elapsed=151.5s

  [10226/15692] intraday_4533.csv.gz  in=335,889,318 out=81,157,278 elapsed=151.5s

  [10227/15692] intraday_4534.csv.gz  in=335,898,296 out=81,157,278 elapsed=151.5s

  [10228/15692] intraday_4535.csv.gz  in=335,907,155 out=81,157,278 elapsed=151.6s

  [10229/15692] intraday_4537.csv.gz  in=335,907,464 out=81,157,278 elapsed=151.6s

  [10230/15692] intraday_4536.csv.gz  in=335,919,279 out=81,157,278 elapsed=151.6s

  [10231/15692] intraday_4538.csv.gz  in=335,934,466 out=81,157,278 elapsed=151.6s

  [10232/15692] intraday_4539.csv.gz  in=335,948,355 out=81,157,278 elapsed=151.6s

  [10233/15692] intraday_4540.csv.gz  in=335,960,738 out=81,157,278 elapsed=151.6s

  [10234/15692] intraday_4542.csv.gz  in=335,975,938 out=81,157,278 elapsed=151.6s

  [10235/15692] intraday_4541.csv.gz  in=335,986,484 out=81,157,278 elapsed=151.6s

  [10236/15692] intraday_4543.csv.gz  in=336,008,245 out=81,157,278 elapsed=151.6s

  [10237/15692] intraday_4544.csv.gz  in=336,022,217 out=81,157,278 elapsed=151.6s

  [10238/15692] intraday_4545.csv.gz  in=336,034,951 out=81,157,278 elapsed=151.6s

  [10239/15692] intraday_4546.csv.gz  in=336,048,463 out=81,157,278 elapsed=151.6s

  [10240/15692] intraday_4548.csv.gz  in=336,058,949 out=81,157,278 elapsed=151.6s

  [10241/15692] intraday_4547.csv.gz  in=336,074,083 out=81,157,278 elapsed=151.6s

  [10242/15692] intraday_4549.csv.gz  in=336,086,682 out=81,157,278 elapsed=151.7s

  [10243/15692] intraday_4550.csv.gz  in=336,099,259 out=81,157,278 elapsed=151.7s

  [10244/15692] intraday_4551.csv.gz  in=336,110,444 out=81,157,278 elapsed=151.7s

  [10245/15692] intraday_4552.csv.gz  in=336,121,223 out=81,157,278 elapsed=151.7s

  [10246/15692] intraday_4553.csv.gz  in=336,132,192 out=81,157,278 elapsed=151.7s

  [10247/15692] intraday_4554.csv.gz  in=336,145,323 out=81,157,278 elapsed=151.7s

  [10248/15692] intraday_4555.csv.gz  in=336,158,037 out=81,157,278 elapsed=151.7s

  [10249/15692] intraday_4557.csv.gz  in=336,170,386 out=81,157,278 elapsed=151.7s

  [10250/15692] intraday_4556.csv.gz  in=336,181,094 out=81,157,278 elapsed=151.7s

  [10251/15692] intraday_4558.csv.gz  in=336,194,363 out=81,157,278 elapsed=151.7s

  [10252/15692] intraday_4559.csv.gz  in=336,207,494 out=81,157,278 elapsed=151.7s

  [10253/15692] intraday_4560.csv.gz  in=336,219,775 out=81,157,278 elapsed=151.7s

  [10254/15692] intraday_4561.csv.gz  in=336,234,271 out=81,157,278 elapsed=151.8s

  [10255/15692] intraday_4562.csv.gz  in=336,245,638 out=81,157,278 elapsed=151.8s

  [10256/15692] intraday_4563.csv.gz  in=336,256,404 out=81,157,278 elapsed=151.8s

  [10257/15692] intraday_4564.csv.gz  in=336,268,811 out=81,157,278 elapsed=151.8s

  [10258/15692] intraday_4565.csv.gz  in=336,281,246 out=81,157,278 elapsed=151.8s

  [10259/15692] intraday_4566.csv.gz  in=336,295,590 out=81,157,278 elapsed=151.8s

  [10260/15692] intraday_4567.csv.gz  in=336,310,544 out=81,157,278 elapsed=151.8s

  [10261/15692] intraday_4568.csv.gz  in=336,323,503 out=81,157,278 elapsed=151.8s

  [10262/15692] intraday_4569.csv.gz  in=336,334,966 out=81,157,278 elapsed=151.8s

  [10263/15692] intraday_4570.csv.gz  in=336,346,451 out=81,157,278 elapsed=151.8s

  [10264/15692] intraday_4571.csv.gz  in=336,360,325 out=81,157,278 elapsed=151.8s

  [10265/15692] intraday_4572.csv.gz  in=336,370,908 out=81,157,278 elapsed=151.8s

  [10266/15692] intraday_4573.csv.gz  in=336,383,853 out=81,157,278 elapsed=151.8s

  [10267/15692] intraday_4574.csv.gz  in=336,394,722 out=81,157,278 elapsed=151.8s

  [10268/15692] intraday_4575.csv.gz  in=336,405,295 out=81,157,278 elapsed=151.9s

  [10269/15692] intraday_4576.csv.gz  in=336,417,113 out=81,157,278 elapsed=151.9s

  [10270/15692] intraday_4578.csv.gz  in=336,429,134 out=81,157,278 elapsed=151.9s

  [10271/15692] intraday_4577.csv.gz  in=336,441,192 out=81,157,278 elapsed=151.9s

  [10272/15692] intraday_4579.csv.gz  in=336,454,077 out=81,157,278 elapsed=151.9s

  [10273/15692] intraday_4580.csv.gz  in=336,467,942 out=81,157,278 elapsed=151.9s

  [10274/15692] intraday_4581.csv.gz  in=336,478,825 out=81,157,278 elapsed=151.9s

  [10275/15692] intraday_4582.csv.gz  in=336,492,784 out=81,157,278 elapsed=151.9s

  [10276/15692] intraday_4583.csv.gz  in=336,504,489 out=81,157,278 elapsed=151.9s

  [10277/15692] intraday_4584.csv.gz  in=336,515,641 out=81,157,278 elapsed=151.9s

  [10278/15692] intraday_4585.csv.gz  in=336,527,725 out=81,157,278 elapsed=151.9s

  [10279/15692] intraday_4586.csv.gz  in=336,538,845 out=81,157,278 elapsed=151.9s

  [10280/15692] intraday_4587.csv.gz  in=336,548,453 out=81,157,278 elapsed=151.9s

  [10281/15692] intraday_4589.csv.gz  in=336,558,277 out=81,157,278 elapsed=152.0s

  [10282/15692] intraday_4588.csv.gz  in=336,572,371 out=81,157,278 elapsed=152.0s

  [10283/15692] intraday_4591.csv.gz  in=336,583,878 out=81,157,278 elapsed=152.0s

  [10284/15692] intraday_4590.csv.gz  in=336,595,639 out=81,157,278 elapsed=152.0s

  [10285/15692] intraday_4593.csv.gz  in=336,607,249 out=81,157,278 elapsed=152.0s

  [10286/15692] intraday_4592.csv.gz  in=336,619,183 out=81,157,278 elapsed=152.0s

  [10287/15692] intraday_4594.csv.gz  in=336,629,557 out=81,157,278 elapsed=152.0s

  [10288/15692] intraday_4597.csv.gz  in=336,641,896 out=81,157,278 elapsed=152.0s

  [10289/15692] intraday_4595.csv.gz  in=336,657,834 out=81,157,278 elapsed=152.0s

  [10290/15692] intraday_4596.csv.gz  in=336,668,543 out=81,157,278 elapsed=152.0s

  [10291/15692] intraday_4598.csv.gz  in=336,679,717 out=81,157,278 elapsed=152.0s

  [10292/15692] intraday_4600.csv.gz  in=336,690,911 out=81,157,278 elapsed=152.0s

  [10293/15692] intraday_4602.csv.gz  in=336,704,366 out=81,157,278 elapsed=152.0s

  [10294/15692] intraday_4601.csv.gz  in=336,718,335 out=81,157,278 elapsed=152.1s

  [10295/15692] intraday_4599.csv.gz  in=336,738,990 out=81,157,278 elapsed=152.1s

  [10296/15692] intraday_4603.csv.gz  in=336,752,549 out=81,157,278 elapsed=152.1s

  [10297/15692] intraday_4604.csv.gz  in=336,764,642 out=81,157,278 elapsed=152.1s

  [10298/15692] intraday_4605.csv.gz  in=336,774,394 out=81,157,278 elapsed=152.1s

  [10299/15692] intraday_4606.csv.gz  in=336,798,255 out=81,157,278 elapsed=152.1s

  [10300/15692] intraday_4607.csv.gz  in=336,809,381 out=81,157,278 elapsed=152.1s

  [10301/15692] intraday_4610.csv.gz  in=336,821,078 out=81,157,278 elapsed=152.1s

  [10302/15692] intraday_4609.csv.gz  in=336,833,759 out=81,157,278 elapsed=152.1s

  [10303/15692] intraday_4608.csv.gz  in=336,846,034 out=81,157,278 elapsed=152.1s

  [10304/15692] intraday_4612.csv.gz  in=336,858,064 out=81,157,278 elapsed=152.2s

  [10305/15692] intraday_4611.csv.gz  in=336,868,076 out=81,157,278 elapsed=152.2s

  [10306/15692] intraday_4614.csv.gz  in=336,879,556 out=81,157,278 elapsed=152.2s

  [10307/15692] intraday_4613.csv.gz  in=336,893,959 out=81,157,278 elapsed=152.2s

  [10308/15692] intraday_4615.csv.gz  in=336,906,433 out=81,157,278 elapsed=152.2s

  [10309/15692] intraday_4616.csv.gz  in=336,916,763 out=81,157,278 elapsed=152.2s

  [10310/15692] intraday_4617.csv.gz  in=336,928,210 out=81,157,278 elapsed=152.2s

  [10311/15692] intraday_4618.csv.gz  in=336,940,952 out=81,157,278 elapsed=152.2s

  [10312/15692] intraday_4620.csv.gz  in=336,954,022 out=81,157,278 elapsed=152.2s

  [10313/15692] intraday_4619.csv.gz  in=336,971,053 out=81,157,278 elapsed=152.2s

  [10314/15692] intraday_4621.csv.gz  in=336,982,411 out=81,157,278 elapsed=152.2s

  [10315/15692] intraday_4622.csv.gz  in=336,992,854 out=81,157,278 elapsed=152.3s

  [10316/15692] intraday_4623.csv.gz  in=337,006,887 out=81,157,278 elapsed=152.3s

  [10317/15692] intraday_4624.csv.gz  in=337,021,649 out=81,157,278 elapsed=152.3s

  [10318/15692] intraday_4625.csv.gz  in=337,036,088 out=81,157,278 elapsed=152.3s

  [10319/15692] intraday_4627.csv.gz  in=337,052,745 out=81,157,278 elapsed=152.3s

  [10320/15692] intraday_4626.csv.gz  in=337,063,527 out=81,157,278 elapsed=152.3s

  [10321/15692] intraday_4628.csv.gz  in=337,077,451 out=81,157,278 elapsed=152.3s

  [10322/15692] intraday_4629.csv.gz  in=337,094,927 out=81,157,278 elapsed=152.3s

  [10323/15692] intraday_4633.csv.gz  in=337,107,110 out=81,157,278 elapsed=152.4s

  [10324/15692] intraday_4630.csv.gz  in=337,121,174 out=81,157,278 elapsed=152.4s

  [10325/15692] intraday_4632.csv.gz  in=337,132,729 out=81,157,278 elapsed=152.4s

  [10326/15692] intraday_4631.csv.gz  in=337,144,756 out=81,157,278 elapsed=152.4s

  [10327/15692] intraday_4634.csv.gz  in=337,155,977 out=81,157,278 elapsed=152.4s

  [10328/15692] intraday_4635.csv.gz  in=337,167,366 out=81,157,278 elapsed=152.4s

  [10329/15692] intraday_4636.csv.gz  in=337,178,732 out=81,157,278 elapsed=152.5s

  [10330/15692] intraday_4639.csv.gz  in=337,190,899 out=81,157,278 elapsed=152.5s

  [10331/15692] intraday_4637.csv.gz  in=337,203,211 out=81,157,278 elapsed=152.5s

  [10332/15692] intraday_4638.csv.gz  in=337,219,642 out=81,157,278 elapsed=152.5s

  [10333/15692] intraday_4640.csv.gz  in=337,233,316 out=81,157,278 elapsed=152.5s

  [10334/15692] intraday_4642.csv.gz  in=337,245,864 out=81,157,278 elapsed=152.5s

  [10335/15692] intraday_4641.csv.gz  in=337,258,636 out=81,157,278 elapsed=152.5s

  [10336/15692] intraday_4643.csv.gz  in=337,271,141 out=81,157,278 elapsed=152.5s

  [10337/15692] intraday_4645.csv.gz  in=337,284,196 out=81,157,278 elapsed=152.5s

  [10338/15692] intraday_4644.csv.gz  in=337,298,029 out=81,157,278 elapsed=152.5s

  [10339/15692] intraday_4646.csv.gz  in=337,309,554 out=81,157,278 elapsed=152.6s

  [10340/15692] intraday_4647.csv.gz  in=337,323,726 out=81,157,278 elapsed=152.6s

  [10341/15692] intraday_4648.csv.gz  in=337,336,968 out=81,157,278 elapsed=152.6s

  [10342/15692] intraday_4649.csv.gz  in=337,351,763 out=81,157,278 elapsed=152.6s

  [10343/15692] intraday_4650.csv.gz  in=337,366,147 out=81,157,278 elapsed=152.6s

  [10344/15692] intraday_4652.csv.gz  in=337,380,828 out=81,157,278 elapsed=152.6s

  [10345/15692] intraday_4651.csv.gz  in=337,393,831 out=81,157,278 elapsed=152.6s

  [10346/15692] intraday_4653.csv.gz  in=337,408,199 out=81,157,278 elapsed=152.6s

  [10347/15692] intraday_4654.csv.gz  in=337,421,188 out=81,157,278 elapsed=152.6s

  [10348/15692] intraday_4656.csv.gz  in=337,431,539 out=81,157,278 elapsed=152.6s

  [10349/15692] intraday_4655.csv.gz  in=337,443,146 out=81,157,278 elapsed=152.6s

  [10350/15692] intraday_4657.csv.gz  in=337,456,146 out=81,157,278 elapsed=152.7s

  [10351/15692] intraday_4658.csv.gz  in=337,467,593 out=81,157,278 elapsed=152.7s

  [10352/15692] intraday_4659.csv.gz  in=337,482,093 out=81,157,278 elapsed=152.7s

  [10353/15692] intraday_4660.csv.gz  in=337,495,733 out=81,157,278 elapsed=152.7s

  [10354/15692] intraday_4662.csv.gz  in=337,507,842 out=81,157,278 elapsed=152.7s

  [10355/15692] intraday_4664.csv.gz  in=337,521,284 out=81,157,278 elapsed=152.7s

  [10356/15692] intraday_4661.csv.gz  in=337,538,713 out=81,157,278 elapsed=152.7s

  [10357/15692] intraday_4663.csv.gz  in=337,552,282 out=81,157,278 elapsed=152.7s

  [10358/15692] intraday_4666.csv.gz  in=337,565,087 out=81,157,278 elapsed=152.7s

  [10359/15692] intraday_4665.csv.gz  in=337,576,469 out=81,157,278 elapsed=152.8s

  [10360/15692] intraday_4668.csv.gz  in=337,590,656 out=81,157,278 elapsed=152.8s

  [10361/15692] intraday_4667.csv.gz  in=337,605,705 out=81,157,278 elapsed=152.8s

  [10362/15692] intraday_4671.csv.gz  in=337,616,564 out=81,157,278 elapsed=152.8s

  [10363/15692] intraday_4669.csv.gz  in=337,629,239 out=81,157,278 elapsed=152.8s

  [10364/15692] intraday_4670.csv.gz  in=337,645,806 out=81,157,278 elapsed=152.8s

  [10365/15692] intraday_4672.csv.gz  in=337,657,146 out=81,157,278 elapsed=152.8s

  [10366/15692] intraday_4673.csv.gz  in=337,668,741 out=81,157,278 elapsed=152.8s

  [10367/15692] intraday_4674.csv.gz  in=337,682,149 out=81,157,278 elapsed=152.8s

  [10368/15692] intraday_4675.csv.gz  in=337,691,348 out=81,157,278 elapsed=152.8s

  [10369/15692] intraday_4678.csv.gz  in=337,691,620 out=81,157,278 elapsed=152.8s

  [10370/15692] intraday_4676.csv.gz  in=337,705,905 out=81,157,278 elapsed=152.8s

  [10371/15692] intraday_4677.csv.gz  in=337,717,368 out=81,157,278 elapsed=152.8s

  [10372/15692] intraday_4679.csv.gz  in=337,731,671 out=81,157,278 elapsed=152.9s

  [10373/15692] intraday_4680.csv.gz  in=337,745,438 out=81,157,278 elapsed=152.9s

  [10374/15692] intraday_4682.csv.gz  in=337,755,241 out=81,157,278 elapsed=152.9s

  [10375/15692] intraday_4681.csv.gz  in=337,767,054 out=81,157,278 elapsed=152.9s

  [10376/15692] intraday_4683.csv.gz  in=337,782,009 out=81,157,278 elapsed=152.9s

  [10377/15692] intraday_4684.csv.gz  in=337,798,185 out=81,157,278 elapsed=152.9s

  [10378/15692] intraday_4685.csv.gz  in=337,810,315 out=81,157,278 elapsed=152.9s

  [10379/15692] intraday_4686.csv.gz  in=337,822,629 out=81,157,278 elapsed=152.9s

  [10380/15692] intraday_4687.csv.gz  in=337,836,179 out=81,157,278 elapsed=152.9s

  [10381/15692] intraday_4690.csv.gz  in=337,848,002 out=81,157,278 elapsed=153.0s

  [10382/15692] intraday_4689.csv.gz  in=337,858,650 out=81,157,278 elapsed=153.0s

  [10383/15692] intraday_4688.csv.gz  in=337,872,611 out=81,157,278 elapsed=153.0s

  [10384/15692] intraday_4691.csv.gz  in=337,885,722 out=81,157,278 elapsed=153.0s

  [10385/15692] intraday_4692.csv.gz  in=337,895,849 out=81,157,278 elapsed=153.0s

  [10386/15692] intraday_4693.csv.gz  in=337,906,478 out=81,157,278 elapsed=153.0s

  [10387/15692] intraday_4694.csv.gz  in=337,916,391 out=81,157,278 elapsed=153.0s

  [10388/15692] intraday_4695.csv.gz  in=337,929,448 out=81,157,278 elapsed=153.0s

  [10389/15692] intraday_4696.csv.gz  in=337,941,643 out=81,157,278 elapsed=153.0s

  [10390/15692] intraday_4697.csv.gz  in=337,951,615 out=81,157,278 elapsed=153.0s

  [10391/15692] intraday_4698.csv.gz  in=337,963,565 out=81,157,278 elapsed=153.0s

  [10392/15692] intraday_4699.csv.gz  in=337,976,451 out=81,157,278 elapsed=153.1s

  [10393/15692] intraday_4700.csv.gz  in=337,989,694 out=81,157,278 elapsed=153.1s

  [10394/15692] intraday_4701.csv.gz  in=338,003,652 out=81,157,278 elapsed=153.1s

  [10395/15692] intraday_4702.csv.gz  in=338,015,449 out=81,157,278 elapsed=153.1s

  [10396/15692] intraday_4703.csv.gz  in=338,027,273 out=81,157,278 elapsed=153.1s

  [10397/15692] intraday_4704.csv.gz  in=338,037,282 out=81,157,278 elapsed=153.1s

  [10398/15692] intraday_4705.csv.gz  in=338,049,418 out=81,157,278 elapsed=153.1s

  [10399/15692] intraday_4706.csv.gz  in=338,065,477 out=81,157,278 elapsed=153.1s

  [10400/15692] intraday_4707.csv.gz  in=338,078,051 out=81,157,278 elapsed=153.1s

  [10401/15692] intraday_4708.csv.gz  in=338,091,888 out=81,157,278 elapsed=153.1s

  [10402/15692] intraday_4710.csv.gz  in=338,102,838 out=81,157,278 elapsed=153.1s

  [10403/15692] intraday_4709.csv.gz  in=338,117,628 out=81,157,278 elapsed=153.2s

  [10404/15692] intraday_4711.csv.gz  in=338,128,440 out=81,157,278 elapsed=153.2s

  [10405/15692] intraday_4712.csv.gz  in=338,141,063 out=81,157,278 elapsed=153.2s

  [10406/15692] intraday_4713.csv.gz  in=338,167,122 out=81,157,278 elapsed=153.2s

  [10407/15692] intraday_4715.csv.gz  in=338,177,202 out=81,157,278 elapsed=153.2s

  [10408/15692] intraday_4714.csv.gz  in=338,189,500 out=81,157,278 elapsed=153.2s

  [10409/15692] intraday_4716.csv.gz  in=338,200,216 out=81,157,278 elapsed=153.2s

  [10410/15692] intraday_4718.csv.gz  in=338,211,720 out=81,157,278 elapsed=153.2s

  [10411/15692] intraday_4721.csv.gz  in=338,223,775 out=81,157,278 elapsed=153.3s

  [10412/15692] intraday_4719.csv.gz  in=338,237,307 out=81,157,278 elapsed=153.3s

  [10413/15692] intraday_4717.csv.gz  in=338,267,655 out=81,157,278 elapsed=153.3s

  [10414/15692] intraday_4720.csv.gz  in=338,289,121 out=81,157,278 elapsed=153.3s

  [10415/15692] intraday_4722.csv.gz  in=338,300,140 out=81,157,278 elapsed=153.3s

  [10416/15692] intraday_4723.csv.gz  in=338,311,484 out=81,157,278 elapsed=153.3s

  [10417/15692] intraday_4724.csv.gz  in=338,324,377 out=81,157,278 elapsed=153.3s

  [10418/15692] intraday_4725.csv.gz  in=338,334,432 out=81,157,278 elapsed=153.3s

  [10419/15692] intraday_4726.csv.gz  in=338,345,867 out=81,157,278 elapsed=153.3s

  [10420/15692] intraday_4727.csv.gz  in=338,357,130 out=81,157,278 elapsed=153.3s

  [10421/15692] intraday_4728.csv.gz  in=338,366,662 out=81,157,278 elapsed=153.3s

  [10422/15692] intraday_4729.csv.gz  in=338,377,821 out=81,157,278 elapsed=153.3s

  [10423/15692] intraday_4730.csv.gz  in=338,389,260 out=81,157,278 elapsed=153.4s

  [10424/15692] intraday_4731.csv.gz  in=338,404,975 out=81,157,278 elapsed=153.4s

  [10425/15692] intraday_4732.csv.gz  in=338,417,477 out=81,157,278 elapsed=153.4s

  [10426/15692] intraday_4733.csv.gz  in=338,429,534 out=81,157,278 elapsed=153.4s

  [10427/15692] intraday_4734.csv.gz  in=338,439,215 out=81,157,278 elapsed=153.4s

  [10428/15692] intraday_4735.csv.gz  in=338,450,029 out=81,157,278 elapsed=153.4s

  [10429/15692] intraday_4736.csv.gz  in=338,461,974 out=81,157,278 elapsed=153.4s

  [10430/15692] intraday_4737.csv.gz  in=338,474,446 out=81,157,278 elapsed=153.4s

  [10431/15692] intraday_4738.csv.gz  in=338,486,246 out=81,157,278 elapsed=153.4s

  [10432/15692] intraday_4739.csv.gz  in=338,498,536 out=81,157,278 elapsed=153.4s

  [10433/15692] intraday_4740.csv.gz  in=338,510,572 out=81,157,278 elapsed=153.4s

  [10434/15692] intraday_4741.csv.gz  in=338,520,995 out=81,157,278 elapsed=153.4s

  [10435/15692] intraday_4743.csv.gz  in=338,534,204 out=81,157,278 elapsed=153.5s

  [10436/15692] intraday_4742.csv.gz  in=338,549,768 out=81,157,278 elapsed=153.5s

  [10437/15692] intraday_4744.csv.gz  in=338,563,044 out=81,157,278 elapsed=153.5s

  [10438/15692] intraday_4745.csv.gz  in=338,574,066 out=81,157,278 elapsed=153.5s

  [10439/15692] intraday_4746.csv.gz  in=338,585,552 out=81,157,278 elapsed=153.5s

  [10440/15692] intraday_4747.csv.gz  in=338,595,048 out=81,157,278 elapsed=153.5s

  [10441/15692] intraday_4748.csv.gz  in=338,607,262 out=81,157,278 elapsed=153.5s

  [10442/15692] intraday_4749.csv.gz  in=338,618,573 out=81,157,278 elapsed=153.5s

  [10443/15692] intraday_4750.csv.gz  in=338,631,890 out=81,157,278 elapsed=153.5s

  [10444/15692] intraday_4751.csv.gz  in=338,642,482 out=81,157,278 elapsed=153.5s

  [10445/15692] intraday_4752.csv.gz  in=338,653,542 out=81,157,278 elapsed=153.6s

  [10446/15692] intraday_4754.csv.gz  in=338,667,049 out=81,157,278 elapsed=153.6s

  [10447/15692] intraday_4753.csv.gz  in=338,677,494 out=81,157,278 elapsed=153.6s

  [10448/15692] intraday_4757.csv.gz  in=338,687,722 out=81,157,278 elapsed=153.6s

  [10449/15692] intraday_4755.csv.gz  in=338,699,611 out=81,157,278 elapsed=153.6s

  [10450/15692] intraday_4756.csv.gz  in=338,712,401 out=81,157,278 elapsed=153.6s

  [10451/15692] intraday_4758.csv.gz  in=338,722,276 out=81,157,278 elapsed=153.6s

  [10452/15692] intraday_4759.csv.gz  in=338,733,514 out=81,157,278 elapsed=153.6s

  [10453/15692] intraday_4760.csv.gz  in=338,749,410 out=81,157,278 elapsed=153.6s

  [10454/15692] intraday_4761.csv.gz  in=338,763,697 out=81,157,278 elapsed=153.7s

  [10455/15692] intraday_4762.csv.gz  in=338,775,114 out=81,157,278 elapsed=153.7s

  [10456/15692] intraday_4763.csv.gz  in=338,786,101 out=81,157,278 elapsed=153.7s

  [10457/15692] intraday_4764.csv.gz  in=338,796,189 out=81,157,278 elapsed=153.7s

  [10458/15692] intraday_4765.csv.gz  in=338,809,368 out=81,157,278 elapsed=153.7s

  [10459/15692] intraday_4767.csv.gz  in=338,821,487 out=81,157,278 elapsed=153.7s

  [10460/15692] intraday_4766.csv.gz  in=338,837,108 out=81,157,278 elapsed=153.7s

  [10461/15692] intraday_4768.csv.gz  in=338,850,918 out=81,157,278 elapsed=153.7s

  [10462/15692] intraday_4769.csv.gz  in=338,863,603 out=81,157,278 elapsed=153.7s

  [10463/15692] intraday_4770.csv.gz  in=338,876,705 out=81,157,278 elapsed=153.7s

  [10464/15692] intraday_4772.csv.gz  in=338,888,933 out=81,157,278 elapsed=153.7s

  [10465/15692] intraday_4771.csv.gz  in=338,905,952 out=81,157,278 elapsed=153.7s

  [10466/15692] intraday_4774.csv.gz  in=338,916,628 out=81,157,278 elapsed=153.8s

  [10467/15692] intraday_4773.csv.gz  in=338,936,285 out=81,157,278 elapsed=153.8s

  [10468/15692] intraday_4775.csv.gz  in=338,947,215 out=81,157,278 elapsed=153.8s

  [10469/15692] intraday_4776.csv.gz  in=338,959,444 out=81,157,278 elapsed=153.8s

  [10470/15692] intraday_4778.csv.gz  in=338,971,135 out=81,157,278 elapsed=153.8s

  [10471/15692] intraday_4777.csv.gz  in=338,982,366 out=81,157,278 elapsed=153.8s

  [10472/15692] intraday_4779.csv.gz  in=338,996,424 out=81,157,278 elapsed=153.8s

  [10473/15692] intraday_4780.csv.gz  in=339,018,421 out=81,157,278 elapsed=153.8s

  [10474/15692] intraday_4782.csv.gz  in=339,033,068 out=81,157,278 elapsed=153.8s

  [10475/15692] intraday_4783.csv.gz  in=339,043,501 out=81,157,278 elapsed=153.9s

  [10476/15692] intraday_4781.csv.gz  in=339,072,139 out=81,157,278 elapsed=153.9s

  [10477/15692] intraday_4784.csv.gz  in=339,084,063 out=81,157,278 elapsed=153.9s

  [10478/15692] intraday_4785.csv.gz  in=339,096,932 out=81,157,278 elapsed=153.9s

  [10479/15692] intraday_4786.csv.gz  in=339,111,229 out=81,157,278 elapsed=153.9s

  [10480/15692] intraday_4787.csv.gz  in=339,123,200 out=81,157,278 elapsed=153.9s

  [10481/15692] intraday_4788.csv.gz  in=339,136,082 out=81,157,278 elapsed=153.9s

  [10482/15692] intraday_4789.csv.gz  in=339,149,039 out=81,157,278 elapsed=153.9s

  [10483/15692] intraday_4790.csv.gz  in=339,162,768 out=81,157,278 elapsed=153.9s

  [10484/15692] intraday_4791.csv.gz  in=339,177,704 out=81,157,278 elapsed=153.9s

  [10485/15692] intraday_4792.csv.gz  in=339,191,434 out=81,157,278 elapsed=154.0s

  [10486/15692] intraday_4793.csv.gz  in=339,202,301 out=81,157,278 elapsed=154.0s

  [10487/15692] intraday_4794.csv.gz  in=339,218,105 out=81,157,278 elapsed=154.0s

  [10488/15692] intraday_4796.csv.gz  in=339,229,831 out=81,157,278 elapsed=154.0s

  [10489/15692] intraday_4795.csv.gz  in=339,242,079 out=81,157,278 elapsed=154.0s

  [10490/15692] intraday_4797.csv.gz  in=339,252,611 out=81,157,278 elapsed=154.0s

  [10491/15692] intraday_4798.csv.gz  in=339,264,464 out=81,157,278 elapsed=154.0s

  [10492/15692] intraday_4799.csv.gz  in=339,278,444 out=81,157,278 elapsed=154.0s

  [10493/15692] intraday_4800.csv.gz  in=339,292,033 out=81,157,278 elapsed=154.0s

  [10494/15692] intraday_4802.csv.gz  in=339,309,422 out=81,157,278 elapsed=154.0s

  [10495/15692] intraday_4803.csv.gz  in=339,320,796 out=81,157,278 elapsed=154.0s

  [10496/15692] intraday_4801.csv.gz  in=339,347,756 out=81,157,278 elapsed=154.0s

  [10497/15692] intraday_4804.csv.gz  in=339,360,618 out=81,157,278 elapsed=154.1s

  [10498/15692] intraday_4805.csv.gz  in=339,371,582 out=81,157,278 elapsed=154.1s

  [10499/15692] intraday_4807.csv.gz  in=339,382,020 out=81,157,278 elapsed=154.1s

  [10500/15692] intraday_4806.csv.gz  in=339,394,918 out=81,157,278 elapsed=154.1s

  [10501/15692] intraday_4808.csv.gz  in=339,407,874 out=81,157,278 elapsed=154.1s

  [10502/15692] intraday_4810.csv.gz  in=339,421,030 out=81,157,278 elapsed=154.1s

  [10503/15692] intraday_4809.csv.gz  in=339,435,337 out=81,157,278 elapsed=154.1s

  [10504/15692] intraday_4811.csv.gz  in=339,448,660 out=81,157,278 elapsed=154.1s

  [10505/15692] intraday_4814.csv.gz  in=339,460,827 out=81,157,278 elapsed=154.1s

  [10506/15692] intraday_4812.csv.gz  in=339,471,932 out=81,157,278 elapsed=154.1s

  [10507/15692] intraday_4813.csv.gz  in=339,483,739 out=81,157,278 elapsed=154.1s

  [10508/15692] intraday_4816.csv.gz  in=339,494,860 out=81,157,278 elapsed=154.2s

  [10509/15692] intraday_4818.csv.gz  in=339,504,466 out=81,157,278 elapsed=154.2s

  [10510/15692] intraday_4815.csv.gz  in=339,515,834 out=81,157,278 elapsed=154.2s

  [10511/15692] intraday_4817.csv.gz  in=339,523,696 out=81,157,278 elapsed=154.2s

  [10512/15692] intraday_4819.csv.gz  in=339,537,462 out=81,157,278 elapsed=154.2s

  [10513/15692] intraday_4820.csv.gz  in=339,553,018 out=81,157,278 elapsed=154.2s

  [10514/15692] intraday_4822.csv.gz  in=339,565,493 out=81,157,278 elapsed=154.2s

  [10515/15692] intraday_4823.csv.gz  in=339,574,951 out=81,157,278 elapsed=154.2s

  [10516/15692] intraday_4821.csv.gz  in=339,589,123 out=81,157,278 elapsed=154.2s

  [10517/15692] intraday_4824.csv.gz  in=339,603,956 out=81,157,278 elapsed=154.2s

  [10518/15692] intraday_4825.csv.gz  in=339,620,051 out=81,157,278 elapsed=154.3s

  [10519/15692] intraday_4826.csv.gz  in=339,632,372 out=81,157,278 elapsed=154.3s

  [10520/15692] intraday_4828.csv.gz  in=339,646,692 out=81,157,278 elapsed=154.3s

  [10521/15692] intraday_4827.csv.gz  in=339,658,083 out=81,157,278 elapsed=154.3s

  [10522/15692] intraday_4829.csv.gz  in=339,671,790 out=81,157,278 elapsed=154.3s

  [10523/15692] intraday_4830.csv.gz  in=339,682,315 out=81,157,278 elapsed=154.3s

  [10524/15692] intraday_4831.csv.gz  in=339,694,406 out=81,157,278 elapsed=154.3s

  [10525/15692] intraday_4832.csv.gz  in=339,706,648 out=81,157,278 elapsed=154.3s

  [10526/15692] intraday_4833.csv.gz  in=339,720,424 out=81,157,278 elapsed=154.4s

  [10527/15692] intraday_4834.csv.gz  in=339,731,186 out=81,157,278 elapsed=154.4s

  [10528/15692] intraday_4835.csv.gz  in=339,741,538 out=81,157,278 elapsed=154.4s

  [10529/15692] intraday_4836.csv.gz  in=339,754,618 out=81,157,278 elapsed=154.4s

  [10530/15692] intraday_4837.csv.gz  in=339,766,590 out=81,157,278 elapsed=154.4s

  [10531/15692] intraday_4838.csv.gz  in=339,776,771 out=81,157,278 elapsed=154.4s

  [10532/15692] intraday_4839.csv.gz  in=339,788,389 out=81,157,278 elapsed=154.4s

  [10533/15692] intraday_4840.csv.gz  in=339,801,609 out=81,157,278 elapsed=154.4s

  [10534/15692] intraday_4841.csv.gz  in=339,814,705 out=81,157,278 elapsed=154.4s

  [10535/15692] intraday_4842.csv.gz  in=339,826,069 out=81,157,278 elapsed=154.4s

  [10536/15692] intraday_4843.csv.gz  in=339,838,398 out=81,157,278 elapsed=154.5s

  [10537/15692] intraday_4845.csv.gz  in=339,848,067 out=81,157,278 elapsed=154.5s

  [10538/15692] intraday_4844.csv.gz  in=339,880,322 out=81,157,278 elapsed=154.5s

  [10539/15692] intraday_4847.csv.gz  in=339,891,968 out=81,157,278 elapsed=154.5s

  [10540/15692] intraday_4846.csv.gz  in=339,904,961 out=81,157,278 elapsed=154.5s

  [10541/15692] intraday_4849.csv.gz  in=339,920,042 out=81,157,278 elapsed=154.5s

  [10542/15692] intraday_4848.csv.gz  in=339,932,200 out=81,157,278 elapsed=154.5s

  [10543/15692] intraday_4850.csv.gz  in=339,946,862 out=81,157,278 elapsed=154.5s

  [10544/15692] intraday_4851.csv.gz  in=339,958,008 out=81,157,278 elapsed=154.5s

  [10545/15692] intraday_4854.csv.gz  in=339,970,291 out=81,157,278 elapsed=154.6s

  [10546/15692] intraday_4853.csv.gz  in=339,982,621 out=81,157,278 elapsed=154.6s

  [10547/15692] intraday_4852.csv.gz  in=339,993,718 out=81,157,278 elapsed=154.6s

  [10548/15692] intraday_4855.csv.gz  in=340,018,518 out=81,157,278 elapsed=154.6s

  [10549/15692] intraday_4858.csv.gz  in=340,029,814 out=81,157,278 elapsed=154.6s

  [10550/15692] intraday_4857.csv.gz  in=340,040,962 out=81,157,278 elapsed=154.6s

  [10551/15692] intraday_4856.csv.gz  in=340,050,626 out=81,157,278 elapsed=154.6s

  [10552/15692] intraday_4861.csv.gz  in=340,062,940 out=81,157,278 elapsed=154.6s

  [10553/15692] intraday_4859.csv.gz  in=340,073,943 out=81,157,278 elapsed=154.6s

  [10554/15692] intraday_4862.csv.gz  in=340,085,554 out=81,157,278 elapsed=154.6s

  [10555/15692] intraday_4860.csv.gz  in=340,099,576 out=81,157,278 elapsed=154.6s

  [10556/15692] intraday_4864.csv.gz  in=340,110,918 out=81,157,278 elapsed=154.7s

  [10557/15692] intraday_4863.csv.gz  in=340,121,875 out=81,157,278 elapsed=154.7s

  [10558/15692] intraday_4865.csv.gz  in=340,141,097 out=81,157,278 elapsed=154.7s

  [10559/15692] intraday_4866.csv.gz  in=340,151,043 out=81,157,278 elapsed=154.7s

  [10560/15692] intraday_4868.csv.gz  in=340,163,053 out=81,157,278 elapsed=154.7s

  [10561/15692] intraday_4869.csv.gz  in=340,172,368 out=81,157,278 elapsed=154.7s

  [10562/15692] intraday_4867.csv.gz  in=340,183,098 out=81,157,278 elapsed=154.7s

  [10563/15692] intraday_4870.csv.gz  in=340,194,576 out=81,157,278 elapsed=154.7s

  [10564/15692] intraday_4873.csv.gz  in=340,208,610 out=81,157,278 elapsed=154.8s

  [10565/15692] intraday_4871.csv.gz  in=340,219,370 out=81,157,278 elapsed=154.8s

  [10566/15692] intraday_4872.csv.gz  in=340,234,841 out=81,157,278 elapsed=154.8s

  [10567/15692] intraday_4874.csv.gz  in=340,246,518 out=81,157,278 elapsed=154.8s

  [10568/15692] intraday_4876.csv.gz  in=340,257,229 out=81,157,278 elapsed=154.8s

  [10569/15692] intraday_4875.csv.gz  in=340,267,111 out=81,157,278 elapsed=154.8s

  [10570/15692] intraday_4877.csv.gz  in=340,280,020 out=81,157,278 elapsed=154.8s

  [10571/15692] intraday_4878.csv.gz  in=340,292,826 out=81,157,278 elapsed=154.8s

  [10572/15692] intraday_4879.csv.gz  in=340,304,234 out=81,157,278 elapsed=154.8s

  [10573/15692] intraday_4881.csv.gz  in=340,315,399 out=81,157,278 elapsed=154.8s

  [10574/15692] intraday_4880.csv.gz  in=340,326,233 out=81,157,278 elapsed=154.8s

  [10575/15692] intraday_4885.csv.gz  in=340,338,631 out=81,157,278 elapsed=154.9s

  [10576/15692] intraday_4884.csv.gz  in=340,351,726 out=81,157,278 elapsed=154.9s

  [10577/15692] intraday_4883.csv.gz  in=340,366,524 out=81,157,278 elapsed=154.9s

  [10578/15692] intraday_4882.csv.gz  in=340,381,009 out=81,157,278 elapsed=154.9s

  [10579/15692] intraday_4888.csv.gz  in=340,392,272 out=81,157,278 elapsed=154.9s

  [10580/15692] intraday_4887.csv.gz  in=340,403,451 out=81,157,278 elapsed=154.9s

  [10581/15692] intraday_4886.csv.gz  in=340,414,882 out=81,157,278 elapsed=154.9s

  [10582/15692] intraday_4889.csv.gz  in=340,427,167 out=81,157,278 elapsed=154.9s

  [10583/15692] intraday_4891.csv.gz  in=340,440,521 out=81,157,278 elapsed=155.0s

  [10584/15692] intraday_4890.csv.gz  in=340,452,083 out=81,157,278 elapsed=155.0s

  [10585/15692] intraday_4892.csv.gz  in=340,462,784 out=81,157,278 elapsed=155.0s

  [10586/15692] intraday_4893.csv.gz  in=340,474,294 out=81,157,278 elapsed=155.0s

  [10587/15692] intraday_4894.csv.gz  in=340,484,763 out=81,157,278 elapsed=155.0s

  [10588/15692] intraday_4896.csv.gz  in=340,496,182 out=81,157,278 elapsed=155.0s

  [10589/15692] intraday_4895.csv.gz  in=340,509,670 out=81,157,278 elapsed=155.0s

  [10590/15692] intraday_4897.csv.gz  in=340,521,803 out=81,157,278 elapsed=155.0s

  [10591/15692] intraday_4898.csv.gz  in=340,532,453 out=81,157,278 elapsed=155.0s

  [10592/15692] intraday_4900.csv.gz  in=340,544,022 out=81,157,278 elapsed=155.0s

  [10593/15692] intraday_4899.csv.gz  in=340,554,702 out=81,157,278 elapsed=155.0s

  [10594/15692] intraday_4903.csv.gz  in=340,565,615 out=81,157,278 elapsed=155.1s

  [10595/15692] intraday_4904.csv.gz  in=340,576,892 out=81,157,278 elapsed=155.1s

  [10596/15692] intraday_4902.csv.gz  in=340,589,825 out=81,157,278 elapsed=155.1s

  [10597/15692] intraday_4901.csv.gz  in=340,605,574 out=81,157,278 elapsed=155.1s

  [10598/15692] intraday_4905.csv.gz  in=340,616,916 out=81,157,278 elapsed=155.1s

  [10599/15692] intraday_4906.csv.gz  in=340,631,197 out=81,157,278 elapsed=155.1s

  [10600/15692] intraday_4907.csv.gz  in=340,647,002 out=81,157,278 elapsed=155.1s

  [10601/15692] intraday_4908.csv.gz  in=340,658,294 out=81,157,278 elapsed=155.1s

  [10602/15692] intraday_4909.csv.gz  in=340,672,599 out=81,157,278 elapsed=155.2s

  [10603/15692] intraday_4911.csv.gz  in=340,686,917 out=81,157,278 elapsed=155.2s

  [10604/15692] intraday_4910.csv.gz  in=340,701,155 out=81,157,278 elapsed=155.2s

  [10605/15692] intraday_4912.csv.gz  in=340,713,815 out=81,157,278 elapsed=155.2s

  [10606/15692] intraday_4913.csv.gz  in=340,725,727 out=81,157,278 elapsed=155.2s

  [10607/15692] intraday_4915.csv.gz  in=340,735,581 out=81,157,278 elapsed=155.2s

  [10608/15692] intraday_4914.csv.gz  in=340,747,880 out=81,157,278 elapsed=155.2s

  [10609/15692] intraday_4916.csv.gz  in=340,760,888 out=81,157,278 elapsed=155.2s

  [10610/15692] intraday_4918.csv.gz  in=340,772,661 out=81,157,278 elapsed=155.2s

  [10611/15692] intraday_4917.csv.gz  in=340,783,301 out=81,157,278 elapsed=155.2s

  [10612/15692] intraday_4919.csv.gz  in=340,796,609 out=81,157,278 elapsed=155.2s

  [10613/15692] intraday_4920.csv.gz  in=340,809,337 out=81,157,278 elapsed=155.3s

  [10614/15692] intraday_4922.csv.gz  in=340,820,272 out=81,157,278 elapsed=155.3s

  [10615/15692] intraday_4921.csv.gz  in=340,836,380 out=81,157,278 elapsed=155.3s

  [10616/15692] intraday_4923.csv.gz  in=340,851,856 out=81,157,278 elapsed=155.3s

  [10617/15692] intraday_4924.csv.gz  in=340,862,973 out=81,157,278 elapsed=155.3s

  [10618/15692] intraday_4925.csv.gz  in=340,874,972 out=81,157,278 elapsed=155.3s

  [10619/15692] intraday_4927.csv.gz  in=340,889,055 out=81,157,278 elapsed=155.3s

  [10620/15692] intraday_4928.csv.gz  in=340,900,952 out=81,157,278 elapsed=155.3s

  [10621/15692] intraday_4926.csv.gz  in=340,914,478 out=81,157,278 elapsed=155.3s

  [10622/15692] intraday_4931.csv.gz  in=340,927,762 out=81,157,278 elapsed=155.4s

  [10623/15692] intraday_4930.csv.gz  in=340,941,235 out=81,157,278 elapsed=155.4s

  [10624/15692] intraday_4932.csv.gz  in=340,963,097 out=81,157,278 elapsed=155.4s

  [10625/15692] intraday_4929.csv.gz  in=340,977,021 out=81,157,278 elapsed=155.4s

  [10626/15692] intraday_4933.csv.gz  in=340,991,633 out=81,157,278 elapsed=155.4s

  [10627/15692] intraday_4934.csv.gz  in=341,003,206 out=81,157,278 elapsed=155.4s

  [10628/15692] intraday_4935.csv.gz  in=341,018,776 out=81,157,278 elapsed=155.4s

  [10629/15692] intraday_4936.csv.gz  in=341,030,429 out=81,157,278 elapsed=155.4s

  [10630/15692] intraday_4937.csv.gz  in=341,042,178 out=81,157,278 elapsed=155.4s

  [10631/15692] intraday_4938.csv.gz  in=341,052,643 out=81,157,278 elapsed=155.4s

  [10632/15692] intraday_4940.csv.gz  in=341,063,391 out=81,157,278 elapsed=155.4s

  [10633/15692] intraday_4939.csv.gz  in=341,076,366 out=81,157,278 elapsed=155.5s

  [10634/15692] intraday_4942.csv.gz  in=341,089,073 out=81,157,278 elapsed=155.5s

  [10635/15692] intraday_4941.csv.gz  in=341,102,573 out=81,157,278 elapsed=155.5s

  [10636/15692] intraday_4943.csv.gz  in=341,119,064 out=81,157,278 elapsed=155.5s

  [10637/15692] intraday_4944.csv.gz  in=341,130,395 out=81,157,278 elapsed=155.5s

  [10638/15692] intraday_4945.csv.gz  in=341,142,712 out=81,157,278 elapsed=155.5s

  [10639/15692] intraday_4947.csv.gz  in=341,156,878 out=81,157,278 elapsed=155.5s

  [10640/15692] intraday_4948.csv.gz  in=341,167,771 out=81,157,278 elapsed=155.5s

  [10641/15692] intraday_4946.csv.gz  in=341,192,784 out=81,157,278 elapsed=155.5s

  [10642/15692] intraday_4949.csv.gz  in=341,206,530 out=81,157,278 elapsed=155.6s

  [10643/15692] intraday_4950.csv.gz  in=341,221,622 out=81,157,278 elapsed=155.6s

  [10644/15692] intraday_4951.csv.gz  in=341,234,749 out=81,157,278 elapsed=155.6s

  [10645/15692] intraday_4953.csv.gz  in=341,245,369 out=81,157,278 elapsed=155.6s

  [10646/15692] intraday_4954.csv.gz  in=341,257,091 out=81,157,278 elapsed=155.6s

  [10647/15692] intraday_4952.csv.gz  in=341,271,356 out=81,157,278 elapsed=155.6s

  [10648/15692] intraday_4955.csv.gz  in=341,284,652 out=81,157,278 elapsed=155.6s

  [10649/15692] intraday_4956.csv.gz  in=341,297,887 out=81,157,278 elapsed=155.6s

  [10650/15692] intraday_4957.csv.gz  in=341,307,442 out=81,157,278 elapsed=155.6s

  [10651/15692] intraday_4958.csv.gz  in=341,316,588 out=81,157,278 elapsed=155.6s

  [10652/15692] intraday_4959.csv.gz  in=341,326,987 out=81,157,278 elapsed=155.6s

  [10653/15692] intraday_4960.csv.gz  in=341,333,666 out=81,157,278 elapsed=155.6s

  [10654/15692] intraday_4962.csv.gz  in=341,503,555 out=81,157,278 elapsed=155.8s

  [10655/15692] intraday_4963.csv.gz  in=341,667,115 out=81,157,278 elapsed=155.8s

  [10656/15692] intraday_4964.csv.gz  in=341,839,810 out=81,157,278 elapsed=155.8s

  [10657/15692] intraday_4961.csv.gz  in=342,042,810 out=81,157,278 elapsed=155.9s

  [10658/15692] intraday_4965.csv.gz  in=342,229,689 out=81,157,278 elapsed=156.0s

  [10659/15692] intraday_4968.csv.gz  in=342,384,612 out=81,157,278 elapsed=156.0s

  [10660/15692] intraday_4966.csv.gz  in=342,590,940 out=81,157,278 elapsed=156.0s

  [10661/15692] intraday_4967.csv.gz  in=342,776,746 out=81,157,278 elapsed=156.0s

  [10662/15692] intraday_4969.csv.gz  in=342,956,889 out=81,157,278 elapsed=156.1s

  [10663/15692] intraday_4970.csv.gz  in=343,129,126 out=81,157,278 elapsed=156.1s

  [10664/15692] intraday_4971.csv.gz  in=343,305,735 out=81,157,278 elapsed=156.2s

  [10665/15692] intraday_4972.csv.gz  in=343,463,424 out=81,157,278 elapsed=156.2s

  [10666/15692] intraday_4973.csv.gz  in=343,621,541 out=81,157,278 elapsed=156.2s

  [10667/15692] intraday_4976.csv.gz  in=343,739,797 out=81,157,278 elapsed=156.3s

  [10668/15692] intraday_4974.csv.gz  in=343,887,643 out=81,157,278 elapsed=156.3s

  [10669/15692] intraday_4975.csv.gz  in=344,020,215 out=81,157,278 elapsed=156.3s

  [10670/15692] intraday_4977.csv.gz  in=344,211,006 out=81,157,278 elapsed=156.4s

  [10671/15692] intraday_4979.csv.gz  in=344,342,389 out=81,157,278 elapsed=156.4s

  [10672/15692] intraday_4978.csv.gz  in=344,514,442 out=81,157,278 elapsed=156.4s

  [10673/15692] intraday_4980.csv.gz  in=344,678,326 out=81,157,278 elapsed=156.4s

  [10674/15692] intraday_4981.csv.gz  in=344,825,448 out=81,157,278 elapsed=156.5s

  [10675/15692] intraday_4982.csv.gz  in=345,001,799 out=81,157,278 elapsed=156.5s

  [10676/15692] intraday_4983.csv.gz  in=345,140,911 out=81,157,278 elapsed=156.5s

  [10677/15692] intraday_4984.csv.gz  in=345,292,345 out=81,157,278 elapsed=156.6s

  [10678/15692] intraday_4985.csv.gz  in=345,454,092 out=81,157,278 elapsed=156.6s

  [10679/15692] intraday_4986.csv.gz  in=345,600,868 out=81,157,278 elapsed=156.7s

  [10680/15692] intraday_4987.csv.gz  in=345,761,368 out=81,157,278 elapsed=156.7s

  [10681/15692] intraday_4988.csv.gz  in=345,907,362 out=81,157,278 elapsed=156.7s

  [10682/15692] intraday_4989.csv.gz  in=346,089,834 out=81,157,278 elapsed=156.7s

  [10683/15692] intraday_4990.csv.gz  in=346,281,987 out=81,157,278 elapsed=156.8s

  [10684/15692] intraday_4992.csv.gz  in=346,433,612 out=81,157,278 elapsed=156.8s

  [10685/15692] intraday_4991.csv.gz  in=346,627,860 out=81,157,278 elapsed=156.8s

  [10686/15692] intraday_4993.csv.gz  in=346,779,358 out=81,157,278 elapsed=156.9s

  [10687/15692] intraday_4994.csv.gz  in=346,928,191 out=81,157,278 elapsed=156.9s

  [10688/15692] intraday_4996.csv.gz  in=347,069,077 out=81,157,278 elapsed=157.0s

  [10689/15692] intraday_4997.csv.gz  in=347,227,030 out=81,157,278 elapsed=157.0s

  [10690/15692] intraday_4995.csv.gz  in=347,405,801 out=81,157,278 elapsed=157.0s

  [10691/15692] intraday_4998.csv.gz  in=347,559,945 out=81,157,278 elapsed=157.1s

  [10692/15692] intraday_4999.csv.gz  in=347,687,335 out=81,157,278 elapsed=157.1s

  [10693/15692] intraday_5000.csv.gz  in=347,826,897 out=81,157,278 elapsed=157.1s

  [10694/15692] intraday_5001.csv.gz  in=347,988,078 out=81,157,278 elapsed=157.1s

  [10695/15692] intraday_5002.csv.gz  in=348,140,593 out=81,157,278 elapsed=157.2s

  [10696/15692] intraday_5003.csv.gz  in=348,297,543 out=81,157,278 elapsed=157.2s

  [10697/15692] intraday_5005.csv.gz  in=348,463,476 out=81,157,278 elapsed=157.2s

  [10698/15692] intraday_5004.csv.gz  in=348,636,037 out=81,157,278 elapsed=157.2s

  [10699/15692] intraday_5006.csv.gz  in=348,792,386 out=81,157,278 elapsed=157.3s

  [10700/15692] intraday_5007.csv.gz  in=348,931,965 out=81,157,278 elapsed=157.3s

  [10701/15692] intraday_5008.csv.gz  in=349,076,205 out=81,157,278 elapsed=157.4s

  [10702/15692] intraday_5009.csv.gz  in=349,235,924 out=81,157,278 elapsed=157.4s

  [10703/15692] intraday_5010.csv.gz  in=349,368,923 out=81,157,278 elapsed=157.4s

  [10704/15692] intraday_5011.csv.gz  in=349,509,112 out=81,157,278 elapsed=157.5s

  [10705/15692] intraday_5013.csv.gz  in=349,640,261 out=81,157,278 elapsed=157.5s

  [10706/15692] intraday_5014.csv.gz  in=349,795,955 out=81,157,278 elapsed=157.6s

  [10707/15692] intraday_5012.csv.gz  in=349,998,994 out=81,157,278 elapsed=157.6s

  [10708/15692] intraday_5015.csv.gz  in=350,162,311 out=81,157,278 elapsed=157.6s

  [10709/15692] intraday_5016.csv.gz  in=350,321,696 out=81,157,278 elapsed=157.6s

  [10710/15692] intraday_5017.csv.gz  in=350,464,112 out=81,157,278 elapsed=157.7s

  [10711/15692] intraday_5018.csv.gz  in=350,616,339 out=81,157,278 elapsed=157.7s

  [10712/15692] intraday_5019.csv.gz  in=350,790,070 out=81,157,278 elapsed=157.7s

  [10713/15692] intraday_5020.csv.gz  in=350,936,240 out=81,157,278 elapsed=157.8s

  [10714/15692] intraday_5021.csv.gz  in=351,098,877 out=81,157,278 elapsed=157.8s

  [10715/15692] intraday_5022.csv.gz  in=351,242,755 out=81,157,278 elapsed=157.8s

  [10716/15692] intraday_5023.csv.gz  in=351,380,342 out=81,157,278 elapsed=157.8s

  [10717/15692] intraday_5024.csv.gz  in=351,513,570 out=81,157,278 elapsed=157.9s

  [10718/15692] intraday_5025.csv.gz  in=351,705,238 out=81,157,278 elapsed=157.9s

  [10719/15692] intraday_5026.csv.gz  in=351,874,715 out=81,157,278 elapsed=158.0s

  [10720/15692] intraday_5027.csv.gz  in=352,045,758 out=81,157,278 elapsed=158.0s

  [10721/15692] intraday_5028.csv.gz  in=352,197,628 out=81,157,278 elapsed=158.0s

  [10722/15692] intraday_5029.csv.gz  in=352,347,890 out=81,157,278 elapsed=158.0s

  [10723/15692] intraday_5030.csv.gz  in=352,499,517 out=81,157,278 elapsed=158.1s

  [10724/15692] intraday_5031.csv.gz  in=352,651,850 out=81,157,278 elapsed=158.1s

  [10725/15692] intraday_5032.csv.gz  in=352,790,600 out=81,157,278 elapsed=158.1s

  [10726/15692] intraday_5033.csv.gz  in=352,961,617 out=81,157,278 elapsed=158.2s

  [10727/15692] intraday_5034.csv.gz  in=353,101,924 out=81,157,278 elapsed=158.2s

  [10728/15692] intraday_5036.csv.gz  in=353,245,038 out=81,157,278 elapsed=158.2s

  [10729/15692] intraday_5035.csv.gz  in=353,404,962 out=81,157,278 elapsed=158.2s

  [10730/15692] intraday_5037.csv.gz  in=353,561,565 out=81,157,278 elapsed=158.3s

  [10731/15692] intraday_5038.csv.gz  in=353,711,080 out=81,157,278 elapsed=158.3s

  [10732/15692] intraday_5040.csv.gz  in=353,833,222 out=81,157,278 elapsed=158.4s

  [10733/15692] intraday_5039.csv.gz  in=353,998,769 out=81,157,278 elapsed=158.4s

  [10734/15692] intraday_5041.csv.gz  in=354,145,266 out=81,157,278 elapsed=158.4s

  [10735/15692] intraday_5042.csv.gz  in=354,295,613 out=81,157,278 elapsed=158.5s

  [10736/15692] intraday_5045.csv.gz  in=354,458,779 out=81,157,278 elapsed=158.5s

  [10737/15692] intraday_5044.csv.gz  in=354,638,301 out=81,157,278 elapsed=158.6s

  [10738/15692] intraday_5043.csv.gz  in=354,845,816 out=81,157,278 elapsed=158.6s

  [10739/15692] intraday_5046.csv.gz  in=354,996,254 out=81,157,278 elapsed=158.6s

  [10740/15692] intraday_5047.csv.gz  in=355,141,908 out=81,157,278 elapsed=158.6s

  [10741/15692] intraday_5048.csv.gz  in=355,320,335 out=81,157,278 elapsed=158.7s

  [10742/15692] intraday_5050.csv.gz  in=355,463,121 out=81,157,278 elapsed=158.7s

  [10743/15692] intraday_5049.csv.gz  in=355,673,401 out=81,157,278 elapsed=158.7s

  [10744/15692] intraday_5051.csv.gz  in=355,846,580 out=81,157,278 elapsed=158.8s

  [10745/15692] intraday_5052.csv.gz  in=356,020,749 out=81,157,278 elapsed=158.9s

  [10746/15692] intraday_5054.csv.gz  in=356,192,083 out=81,157,278 elapsed=158.9s

  [10747/15692] intraday_5055.csv.gz  in=356,345,763 out=81,157,278 elapsed=158.9s

  [10748/15692] intraday_5053.csv.gz  in=356,525,718 out=81,157,278 elapsed=158.9s

  [10749/15692] intraday_5057.csv.gz  in=356,664,624 out=81,157,278 elapsed=159.0s

  [10750/15692] intraday_5056.csv.gz  in=356,825,209 out=81,157,278 elapsed=159.0s

  [10751/15692] intraday_5059.csv.gz  in=356,975,824 out=81,157,278 elapsed=159.0s

  [10752/15692] intraday_5058.csv.gz  in=357,166,994 out=81,157,278 elapsed=159.0s

  [10753/15692] intraday_5060.csv.gz  in=357,332,073 out=81,157,278 elapsed=159.1s

  [10754/15692] intraday_5063.csv.gz  in=357,473,404 out=81,157,278 elapsed=159.2s

  [10755/15692] intraday_5061.csv.gz  in=357,644,216 out=81,157,278 elapsed=159.2s

  [10756/15692] intraday_5062.csv.gz  in=357,823,821 out=81,157,278 elapsed=159.2s

  [10757/15692] intraday_5064.csv.gz  in=357,984,276 out=81,157,278 elapsed=159.3s

  [10758/15692] intraday_5066.csv.gz  in=358,126,043 out=81,157,278 elapsed=159.3s

  [10759/15692] intraday_5067.csv.gz  in=358,276,004 out=81,157,278 elapsed=159.3s

  [10760/15692] intraday_5065.csv.gz  in=358,474,439 out=81,157,278 elapsed=159.3s

  [10761/15692] intraday_5070.csv.gz  in=358,620,089 out=81,157,278 elapsed=159.4s

  [10762/15692] intraday_5069.csv.gz  in=358,796,795 out=81,157,278 elapsed=159.4s

  [10763/15692] intraday_5068.csv.gz  in=358,997,478 out=81,157,278 elapsed=159.4s

  [10764/15692] intraday_5071.csv.gz  in=359,164,476 out=81,157,278 elapsed=159.4s

  [10765/15692] intraday_5072.csv.gz  in=359,338,167 out=81,157,278 elapsed=159.5s

  [10766/15692] intraday_5073.csv.gz  in=359,499,791 out=81,157,278 elapsed=159.6s

  [10767/15692] intraday_5075.csv.gz  in=359,670,813 out=81,157,278 elapsed=159.6s

  [10768/15692] intraday_5074.csv.gz  in=359,888,886 out=81,157,278 elapsed=159.6s

  [10769/15692] intraday_5078.csv.gz  in=360,058,303 out=81,157,278 elapsed=159.7s

  [10770/15692] intraday_5076.csv.gz  in=360,248,857 out=81,157,278 elapsed=159.7s

  [10771/15692] intraday_5077.csv.gz  in=360,451,326 out=81,157,278 elapsed=159.7s

  [10772/15692] intraday_5079.csv.gz  in=360,607,627 out=81,157,278 elapsed=159.7s

  [10773/15692] intraday_5080.csv.gz  in=360,751,198 out=81,157,278 elapsed=159.8s

  [10774/15692] intraday_5081.csv.gz  in=360,907,700 out=81,157,278 elapsed=159.9s

  [10775/15692] intraday_5082.csv.gz  in=361,050,200 out=81,157,278 elapsed=159.9s

  [10776/15692] intraday_5083.csv.gz  in=361,209,443 out=81,157,278 elapsed=159.9s

  [10777/15692] intraday_5084.csv.gz  in=361,375,146 out=81,157,278 elapsed=160.0s

  [10778/15692] intraday_5085.csv.gz  in=361,550,041 out=81,157,278 elapsed=160.0s

  [10779/15692] intraday_5087.csv.gz  in=361,707,543 out=81,157,278 elapsed=160.0s

  [10780/15692] intraday_5086.csv.gz  in=361,896,733 out=81,157,278 elapsed=160.0s

  [10781/15692] intraday_5088.csv.gz  in=362,053,893 out=81,157,278 elapsed=160.1s

  [10782/15692] intraday_5089.csv.gz  in=362,224,900 out=81,157,278 elapsed=160.2s

  [10783/15692] intraday_5091.csv.gz  in=362,385,305 out=81,157,278 elapsed=160.2s

  [10784/15692] intraday_5090.csv.gz  in=362,544,770 out=81,157,278 elapsed=160.2s

  [10785/15692] intraday_5092.csv.gz  in=362,730,359 out=81,157,278 elapsed=160.2s

  [10786/15692] intraday_5093.csv.gz  in=362,893,440 out=81,157,278 elapsed=160.3s

  [10787/15692] intraday_5094.csv.gz  in=363,066,027 out=81,157,278 elapsed=160.4s

  [10788/15692] intraday_5096.csv.gz  in=363,200,729 out=81,157,278 elapsed=160.4s

  [10789/15692] intraday_5095.csv.gz  in=363,364,230 out=81,157,278 elapsed=160.4s

  [10790/15692] intraday_5097.csv.gz  in=363,511,745 out=81,157,278 elapsed=160.4s

  [10791/15692] intraday_5100.csv.gz  in=363,620,520 out=81,157,278 elapsed=160.5s

  [10792/15692] intraday_5098.csv.gz  in=363,768,210 out=81,157,278 elapsed=160.5s

  [10793/15692] intraday_5103.csv.gz  in=363,783,588 out=81,157,278 elapsed=160.5s

  [10794/15692] intraday_5099.csv.gz  in=363,963,542 out=81,157,278 elapsed=160.5s

  [10795/15692] intraday_5104.csv.gz  in=363,975,862 out=81,157,278 elapsed=160.5s

  [10796/15692] intraday_5105.csv.gz  in=363,989,727 out=81,157,278 elapsed=160.5s

  [10797/15692] intraday_5107.csv.gz  in=364,003,119 out=81,157,278 elapsed=160.6s

  [10798/15692] intraday_5101.csv.gz  in=364,117,080 out=81,157,278 elapsed=160.6s

  [10799/15692] intraday_5106.csv.gz  in=364,128,253 out=81,157,278 elapsed=160.6s

  [10800/15692] intraday_5102.csv.gz  in=364,241,042 out=81,157,278 elapsed=160.6s

  [10801/15692] intraday_5108.csv.gz  in=364,257,708 out=81,157,278 elapsed=160.6s

  [10802/15692] intraday_5111.csv.gz  in=364,271,606 out=81,157,278 elapsed=160.6s

  [10803/15692] intraday_5110.csv.gz  in=364,283,247 out=81,157,278 elapsed=160.6s

  [10804/15692] intraday_5109.csv.gz  in=364,296,947 out=81,157,278 elapsed=160.7s

  [10805/15692] intraday_5112.csv.gz  in=364,310,289 out=81,157,278 elapsed=160.7s

  [10806/15692] intraday_5113.csv.gz  in=364,324,221 out=81,157,278 elapsed=160.7s

  [10807/15692] intraday_5114.csv.gz  in=364,337,358 out=81,157,278 elapsed=160.7s

  [10808/15692] intraday_5115.csv.gz  in=364,350,341 out=81,157,278 elapsed=160.7s

  [10809/15692] intraday_5116.csv.gz  in=364,361,357 out=81,157,278 elapsed=160.7s

  [10810/15692] intraday_5118.csv.gz  in=364,370,765 out=81,157,278 elapsed=160.7s

  [10811/15692] intraday_5117.csv.gz  in=364,380,864 out=81,157,278 elapsed=160.7s

  [10812/15692] intraday_5119.csv.gz  in=364,401,096 out=81,157,278 elapsed=160.7s

  [10813/15692] intraday_5121.csv.gz  in=364,413,707 out=81,157,278 elapsed=160.7s

  [10814/15692] intraday_5120.csv.gz  in=364,426,988 out=81,157,278 elapsed=160.7s

  [10815/15692] intraday_5122.csv.gz  in=364,438,878 out=81,157,278 elapsed=160.7s

  [10816/15692] intraday_5124.csv.gz  in=364,452,729 out=81,157,278 elapsed=160.8s

  [10817/15692] intraday_5123.csv.gz  in=364,474,152 out=81,157,278 elapsed=160.8s

  [10818/15692] intraday_5126.csv.gz  in=364,486,240 out=81,157,278 elapsed=160.8s

  [10819/15692] intraday_5125.csv.gz  in=364,497,328 out=81,157,278 elapsed=160.8s

  [10820/15692] intraday_5127.csv.gz  in=364,510,447 out=81,157,278 elapsed=160.8s

  [10821/15692] intraday_5130.csv.gz  in=364,522,472 out=81,157,278 elapsed=160.8s

  [10822/15692] intraday_5128.csv.gz  in=364,533,772 out=81,157,278 elapsed=160.8s

  [10823/15692] intraday_5129.csv.gz  in=364,546,095 out=81,157,278 elapsed=160.8s

  [10824/15692] intraday_5134.csv.gz  in=364,557,009 out=81,157,278 elapsed=160.8s

  [10825/15692] intraday_5131.csv.gz  in=364,570,917 out=81,157,278 elapsed=160.9s

  [10826/15692] intraday_5132.csv.gz  in=364,585,925 out=81,157,278 elapsed=160.9s

  [10827/15692] intraday_5133.csv.gz  in=364,601,993 out=81,157,278 elapsed=160.9s

  [10828/15692] intraday_5135.csv.gz  in=364,614,329 out=81,157,278 elapsed=160.9s

  [10829/15692] intraday_5138.csv.gz  in=364,625,220 out=81,157,278 elapsed=160.9s

  [10830/15692] intraday_5136.csv.gz  in=364,637,353 out=81,157,278 elapsed=160.9s

  [10831/15692] intraday_5137.csv.gz  in=364,652,623 out=81,157,278 elapsed=160.9s

  [10832/15692] intraday_5139.csv.gz  in=364,665,357 out=81,157,278 elapsed=160.9s

  [10833/15692] intraday_5140.csv.gz  in=364,678,258 out=81,157,278 elapsed=160.9s

  [10834/15692] intraday_5141.csv.gz  in=364,701,081 out=81,157,278 elapsed=160.9s

  [10835/15692] intraday_5142.csv.gz  in=364,713,724 out=81,157,278 elapsed=160.9s

  [10836/15692] intraday_5143.csv.gz  in=364,726,607 out=81,157,278 elapsed=160.9s

  [10837/15692] intraday_5144.csv.gz  in=364,738,553 out=81,157,278 elapsed=160.9s

  [10838/15692] intraday_5146.csv.gz  in=364,751,364 out=81,157,278 elapsed=161.0s

  [10839/15692] intraday_5145.csv.gz  in=364,764,650 out=81,157,278 elapsed=161.0s

  [10840/15692] intraday_5147.csv.gz  in=364,778,223 out=81,157,278 elapsed=161.0s

  [10841/15692] intraday_5148.csv.gz  in=364,791,268 out=81,157,278 elapsed=161.0s

  [10842/15692] intraday_5150.csv.gz  in=364,803,282 out=81,157,278 elapsed=161.0s

  [10843/15692] intraday_5149.csv.gz  in=364,815,081 out=81,157,278 elapsed=161.0s

  [10844/15692] intraday_5152.csv.gz  in=364,825,983 out=81,157,278 elapsed=161.0s

  [10845/15692] intraday_5151.csv.gz  in=364,839,744 out=81,157,278 elapsed=161.0s

  [10846/15692] intraday_5155.csv.gz  in=364,850,384 out=81,157,278 elapsed=161.0s

  [10847/15692] intraday_5153.csv.gz  in=364,861,802 out=81,157,278 elapsed=161.0s

  [10848/15692] intraday_5154.csv.gz  in=364,875,789 out=81,157,278 elapsed=161.0s

  [10849/15692] intraday_5156.csv.gz  in=364,887,880 out=81,157,278 elapsed=161.0s

  [10850/15692] intraday_5159.csv.gz  in=364,901,285 out=81,157,278 elapsed=161.1s

  [10851/15692] intraday_5157.csv.gz  in=364,914,673 out=81,157,278 elapsed=161.1s

  [10852/15692] intraday_5158.csv.gz  in=364,928,431 out=81,157,278 elapsed=161.1s

  [10853/15692] intraday_5160.csv.gz  in=364,940,578 out=81,157,278 elapsed=161.1s

  [10854/15692] intraday_5161.csv.gz  in=364,954,195 out=81,157,278 elapsed=161.1s

  [10855/15692] intraday_5164.csv.gz  in=364,965,617 out=81,157,278 elapsed=161.1s

  [10856/15692] intraday_5162.csv.gz  in=364,977,548 out=81,157,278 elapsed=161.1s

  [10857/15692] intraday_5163.csv.gz  in=364,990,510 out=81,157,278 elapsed=161.1s

  [10858/15692] intraday_5165.csv.gz  in=365,001,244 out=81,157,278 elapsed=161.1s

  [10859/15692] intraday_5168.csv.gz  in=365,013,858 out=81,157,278 elapsed=161.1s

  [10860/15692] intraday_5169.csv.gz  in=365,027,630 out=81,157,278 elapsed=161.2s

  [10861/15692] intraday_5166.csv.gz  in=365,038,814 out=81,157,278 elapsed=161.2s

  [10862/15692] intraday_5167.csv.gz  in=365,055,273 out=81,157,278 elapsed=161.2s

  [10863/15692] intraday_5170.csv.gz  in=365,067,211 out=81,157,278 elapsed=161.2s

  [10864/15692] intraday_5172.csv.gz  in=365,078,846 out=81,157,278 elapsed=161.2s

  [10865/15692] intraday_5173.csv.gz  in=365,091,033 out=81,157,278 elapsed=161.2s

  [10866/15692] intraday_5171.csv.gz  in=365,100,926 out=81,157,278 elapsed=161.2s

  [10867/15692] intraday_5174.csv.gz  in=365,113,404 out=81,157,278 elapsed=161.2s

  [10868/15692] intraday_5176.csv.gz  in=365,126,210 out=81,157,278 elapsed=161.2s

  [10869/15692] intraday_5175.csv.gz  in=365,139,706 out=81,157,278 elapsed=161.2s

  [10870/15692] intraday_5178.csv.gz  in=365,154,491 out=81,157,278 elapsed=161.2s

  [10871/15692] intraday_5177.csv.gz  in=365,167,586 out=81,157,278 elapsed=161.2s

  [10872/15692] intraday_5179.csv.gz  in=365,180,712 out=81,157,278 elapsed=161.3s

  [10873/15692] intraday_5181.csv.gz  in=365,193,652 out=81,157,278 elapsed=161.3s

  [10874/15692] intraday_5182.csv.gz  in=365,203,809 out=81,157,278 elapsed=161.3s

  [10875/15692] intraday_5180.csv.gz  in=365,215,498 out=81,157,278 elapsed=161.3s

  [10876/15692] intraday_5184.csv.gz  in=365,228,081 out=81,157,278 elapsed=161.3s

  [10877/15692] intraday_5183.csv.gz  in=365,240,174 out=81,157,278 elapsed=161.3s

  [10878/15692] intraday_5186.csv.gz  in=365,253,915 out=81,157,278 elapsed=161.3s

  [10879/15692] intraday_5185.csv.gz  in=365,269,224 out=81,157,278 elapsed=161.3s

  [10880/15692] intraday_5187.csv.gz  in=365,281,661 out=81,157,278 elapsed=161.3s

  [10881/15692] intraday_5188.csv.gz  in=365,293,224 out=81,157,278 elapsed=161.3s

  [10882/15692] intraday_5190.csv.gz  in=365,307,045 out=81,157,278 elapsed=161.4s

  [10883/15692] intraday_5189.csv.gz  in=365,318,199 out=81,157,278 elapsed=161.4s

  [10884/15692] intraday_5192.csv.gz  in=365,329,621 out=81,157,278 elapsed=161.4s

  [10885/15692] intraday_5191.csv.gz  in=365,347,023 out=81,157,278 elapsed=161.4s

  [10886/15692] intraday_5193.csv.gz  in=365,360,778 out=81,157,278 elapsed=161.4s

  [10887/15692] intraday_5194.csv.gz  in=365,374,414 out=81,157,278 elapsed=161.4s

  [10888/15692] intraday_5195.csv.gz  in=365,388,836 out=81,157,278 elapsed=161.4s

  [10889/15692] intraday_5196.csv.gz  in=365,402,227 out=81,157,278 elapsed=161.4s

  [10890/15692] intraday_5197.csv.gz  in=365,418,740 out=81,157,278 elapsed=161.4s

  [10891/15692] intraday_5198.csv.gz  in=365,431,648 out=81,157,278 elapsed=161.4s

  [10892/15692] intraday_5201.csv.gz  in=365,444,644 out=81,157,278 elapsed=161.5s

  [10893/15692] intraday_5199.csv.gz  in=365,454,954 out=81,157,278 elapsed=161.5s

  [10894/15692] intraday_5200.csv.gz  in=365,469,107 out=81,157,278 elapsed=161.5s

  [10895/15692] intraday_5202.csv.gz  in=365,481,912 out=81,157,278 elapsed=161.5s

  [10896/15692] intraday_5203.csv.gz  in=365,495,077 out=81,157,278 elapsed=161.5s

  [10897/15692] intraday_5207.csv.gz  in=365,512,428 out=81,157,278 elapsed=161.5s

  [10898/15692] intraday_5205.csv.gz  in=365,523,175 out=81,157,278 elapsed=161.5s

  [10899/15692] intraday_5206.csv.gz  in=365,536,287 out=81,157,278 elapsed=161.5s

  [10900/15692] intraday_5204.csv.gz  in=365,551,488 out=81,157,278 elapsed=161.5s

  [10901/15692] intraday_5208.csv.gz  in=365,561,576 out=81,157,278 elapsed=161.6s

  [10902/15692] intraday_5209.csv.gz  in=365,573,820 out=81,157,278 elapsed=161.6s

  [10903/15692] intraday_5212.csv.gz  in=365,585,180 out=81,157,278 elapsed=161.6s

  [10904/15692] intraday_5210.csv.gz  in=365,600,486 out=81,157,278 elapsed=161.6s

  [10905/15692] intraday_5211.csv.gz  in=365,614,551 out=81,157,278 elapsed=161.6s

  [10906/15692] intraday_5214.csv.gz  in=365,627,639 out=81,157,278 elapsed=161.6s

  [10907/15692] intraday_5213.csv.gz  in=365,640,326 out=81,157,278 elapsed=161.6s

  [10908/15692] intraday_5216.csv.gz  in=365,657,381 out=81,157,278 elapsed=161.6s

  [10909/15692] intraday_5215.csv.gz  in=365,670,117 out=81,157,278 elapsed=161.6s

  [10910/15692] intraday_5217.csv.gz  in=365,683,040 out=81,157,278 elapsed=161.6s

  [10911/15692] intraday_5220.csv.gz  in=365,697,247 out=81,157,278 elapsed=161.7s

  [10912/15692] intraday_5218.csv.gz  in=365,711,662 out=81,157,278 elapsed=161.7s

  [10913/15692] intraday_5219.csv.gz  in=365,727,256 out=81,157,278 elapsed=161.7s

  [10914/15692] intraday_5221.csv.gz  in=365,739,074 out=81,157,278 elapsed=161.7s

  [10915/15692] intraday_5222.csv.gz  in=365,750,482 out=81,157,278 elapsed=161.7s

  [10916/15692] intraday_5223.csv.gz  in=365,762,689 out=81,157,278 elapsed=161.7s

  [10917/15692] intraday_5225.csv.gz  in=365,775,393 out=81,157,278 elapsed=161.7s

  [10918/15692] intraday_5224.csv.gz  in=365,786,201 out=81,157,278 elapsed=161.7s

  [10919/15692] intraday_5226.csv.gz  in=365,799,044 out=81,157,278 elapsed=161.7s

  [10920/15692] intraday_5227.csv.gz  in=365,818,695 out=81,157,278 elapsed=161.7s

  [10921/15692] intraday_5228.csv.gz  in=365,834,282 out=81,157,278 elapsed=161.8s

  [10922/15692] intraday_5229.csv.gz  in=365,845,934 out=81,157,278 elapsed=161.8s

  [10923/15692] intraday_5230.csv.gz  in=365,857,759 out=81,157,278 elapsed=161.8s

  [10924/15692] intraday_5231.csv.gz  in=365,871,502 out=81,157,278 elapsed=161.8s

  [10925/15692] intraday_5232.csv.gz  in=365,883,534 out=81,157,278 elapsed=161.8s

  [10926/15692] intraday_5233.csv.gz  in=365,895,786 out=81,157,278 elapsed=161.8s

  [10927/15692] intraday_5234.csv.gz  in=365,911,200 out=81,157,278 elapsed=161.8s

  [10928/15692] intraday_5235.csv.gz  in=365,924,459 out=81,157,278 elapsed=161.8s

  [10929/15692] intraday_5237.csv.gz  in=365,936,830 out=81,157,278 elapsed=161.8s

  [10930/15692] intraday_5236.csv.gz  in=365,950,937 out=81,157,278 elapsed=161.8s

  [10931/15692] intraday_5238.csv.gz  in=365,964,260 out=81,157,278 elapsed=161.8s

  [10932/15692] intraday_5239.csv.gz  in=365,977,850 out=81,157,278 elapsed=161.8s

  [10933/15692] intraday_5242.csv.gz  in=365,986,688 out=81,157,278 elapsed=161.9s

  [10934/15692] intraday_5240.csv.gz  in=365,998,611 out=81,157,278 elapsed=161.9s

  [10935/15692] intraday_5241.csv.gz  in=366,013,096 out=81,157,278 elapsed=161.9s

  [10936/15692] intraday_5243.csv.gz  in=366,024,879 out=81,157,278 elapsed=161.9s

  [10937/15692] intraday_5244.csv.gz  in=366,033,882 out=81,157,278 elapsed=161.9s

  [10938/15692] intraday_5245.csv.gz  in=366,050,117 out=81,157,278 elapsed=161.9s

  [10939/15692] intraday_5246.csv.gz  in=366,063,286 out=81,157,278 elapsed=161.9s

  [10940/15692] intraday_5247.csv.gz  in=366,077,944 out=81,157,278 elapsed=161.9s

  [10941/15692] intraday_5248.csv.gz  in=366,089,197 out=81,157,278 elapsed=161.9s

  [10942/15692] intraday_5249.csv.gz  in=366,102,525 out=81,157,278 elapsed=161.9s

  [10943/15692] intraday_5250.csv.gz  in=366,119,560 out=81,157,278 elapsed=161.9s

  [10944/15692] intraday_5251.csv.gz  in=366,133,703 out=81,157,278 elapsed=162.0s

  [10945/15692] intraday_5252.csv.gz  in=366,145,825 out=81,157,278 elapsed=162.0s

  [10946/15692] intraday_5253.csv.gz  in=366,160,162 out=81,157,278 elapsed=162.0s

  [10947/15692] intraday_5254.csv.gz  in=366,173,946 out=81,157,278 elapsed=162.0s

  [10948/15692] intraday_5255.csv.gz  in=366,187,739 out=81,157,278 elapsed=162.0s

  [10949/15692] intraday_5256.csv.gz  in=366,201,538 out=81,157,278 elapsed=162.0s

  [10950/15692] intraday_5257.csv.gz  in=366,214,747 out=81,157,278 elapsed=162.0s

  [10951/15692] intraday_5258.csv.gz  in=366,226,908 out=81,157,278 elapsed=162.0s

  [10952/15692] intraday_5259.csv.gz  in=366,238,216 out=81,157,278 elapsed=162.0s

  [10953/15692] intraday_5260.csv.gz  in=366,248,123 out=81,157,278 elapsed=162.0s

  [10954/15692] intraday_5262.csv.gz  in=366,261,565 out=81,157,278 elapsed=162.0s

  [10955/15692] intraday_5261.csv.gz  in=366,277,050 out=81,157,278 elapsed=162.0s

  [10956/15692] intraday_5263.csv.gz  in=366,288,760 out=81,157,278 elapsed=162.1s

  [10957/15692] intraday_5264.csv.gz  in=366,301,142 out=81,157,278 elapsed=162.1s

  [10958/15692] intraday_5266.csv.gz  in=366,315,172 out=81,157,278 elapsed=162.1s

  [10959/15692] intraday_5265.csv.gz  in=366,327,657 out=81,157,278 elapsed=162.1s

  [10960/15692] intraday_5267.csv.gz  in=366,339,352 out=81,157,278 elapsed=162.1s

  [10961/15692] intraday_5268.csv.gz  in=366,351,955 out=81,157,278 elapsed=162.1s

  [10962/15692] intraday_5270.csv.gz  in=366,363,226 out=81,157,278 elapsed=162.1s

  [10963/15692] intraday_5269.csv.gz  in=366,376,362 out=81,157,278 elapsed=162.1s

  [10964/15692] intraday_5271.csv.gz  in=366,388,532 out=81,157,278 elapsed=162.1s

  [10965/15692] intraday_5272.csv.gz  in=366,399,621 out=81,157,278 elapsed=162.1s

  [10966/15692] intraday_5273.csv.gz  in=366,414,800 out=81,157,278 elapsed=162.1s

  [10967/15692] intraday_5274.csv.gz  in=366,429,617 out=81,157,278 elapsed=162.2s

  [10968/15692] intraday_5276.csv.gz  in=366,440,938 out=81,157,278 elapsed=162.2s

  [10969/15692] intraday_5275.csv.gz  in=366,457,548 out=81,157,278 elapsed=162.2s

  [10970/15692] intraday_5277.csv.gz  in=366,469,765 out=81,157,278 elapsed=162.2s

  [10971/15692] intraday_5280.csv.gz  in=366,480,743 out=81,157,278 elapsed=162.2s

  [10972/15692] intraday_5278.csv.gz  in=366,493,052 out=81,157,278 elapsed=162.2s

  [10973/15692] intraday_5279.csv.gz  in=366,508,082 out=81,157,278 elapsed=162.2s

  [10974/15692] intraday_5281.csv.gz  in=366,520,768 out=81,157,278 elapsed=162.2s

  [10975/15692] intraday_5283.csv.gz  in=366,531,787 out=81,157,278 elapsed=162.2s

  [10976/15692] intraday_5282.csv.gz  in=366,544,986 out=81,157,278 elapsed=162.2s

  [10977/15692] intraday_5285.csv.gz  in=366,558,000 out=81,157,278 elapsed=162.2s

  [10978/15692] intraday_5284.csv.gz  in=366,569,939 out=81,157,278 elapsed=162.3s

  [10979/15692] intraday_5286.csv.gz  in=366,582,486 out=81,157,278 elapsed=162.3s

  [10980/15692] intraday_5289.csv.gz  in=366,595,711 out=81,157,278 elapsed=162.3s

  [10981/15692] intraday_5287.csv.gz  in=366,609,456 out=81,157,278 elapsed=162.3s

  [10982/15692] intraday_5288.csv.gz  in=366,623,042 out=81,157,278 elapsed=162.3s

  [10983/15692] intraday_5291.csv.gz  in=366,635,588 out=81,157,278 elapsed=162.3s

  [10984/15692] intraday_5290.csv.gz  in=366,648,916 out=81,157,278 elapsed=162.3s

  [10985/15692] intraday_5293.csv.gz  in=366,662,443 out=81,157,278 elapsed=162.3s

  [10986/15692] intraday_5292.csv.gz  in=366,674,684 out=81,157,278 elapsed=162.3s

  [10987/15692] intraday_5294.csv.gz  in=366,685,766 out=81,157,278 elapsed=162.4s

  [10988/15692] intraday_5295.csv.gz  in=366,697,855 out=81,157,278 elapsed=162.4s

  [10989/15692] intraday_5296.csv.gz  in=366,714,398 out=81,157,278 elapsed=162.4s

  [10990/15692] intraday_5297.csv.gz  in=366,724,049 out=81,157,278 elapsed=162.4s

  [10991/15692] intraday_5298.csv.gz  in=366,735,664 out=81,157,278 elapsed=162.4s

  [10992/15692] intraday_5299.csv.gz  in=366,749,286 out=81,157,278 elapsed=162.4s

  [10993/15692] intraday_5300.csv.gz  in=366,762,548 out=81,157,278 elapsed=162.4s

  [10994/15692] intraday_5302.csv.gz  in=366,774,417 out=81,157,278 elapsed=162.4s

  [10995/15692] intraday_5301.csv.gz  in=366,788,634 out=81,157,278 elapsed=162.4s

  [10996/15692] intraday_5303.csv.gz  in=366,802,332 out=81,157,278 elapsed=162.4s

  [10997/15692] intraday_5304.csv.gz  in=366,814,282 out=81,157,278 elapsed=162.4s

  [10998/15692] intraday_5306.csv.gz  in=366,826,283 out=81,157,278 elapsed=162.5s

  [10999/15692] intraday_5305.csv.gz  in=366,838,953 out=81,157,278 elapsed=162.5s

  [11000/15692] intraday_5307.csv.gz  in=366,850,252 out=81,157,278 elapsed=162.5s

  [11001/15692] intraday_5308.csv.gz  in=366,860,869 out=81,157,278 elapsed=162.5s

  [11002/15692] intraday_5310.csv.gz  in=366,874,635 out=81,157,278 elapsed=162.5s

  [11003/15692] intraday_5309.csv.gz  in=366,890,687 out=81,157,278 elapsed=162.5s

  [11004/15692] intraday_5312.csv.gz  in=366,902,744 out=81,157,278 elapsed=162.5s

  [11005/15692] intraday_5311.csv.gz  in=366,916,933 out=81,157,278 elapsed=162.5s

  [11006/15692] intraday_5313.csv.gz  in=366,927,542 out=81,157,278 elapsed=162.5s

  [11007/15692] intraday_5314.csv.gz  in=366,939,637 out=81,157,278 elapsed=162.5s

  [11008/15692] intraday_5316.csv.gz  in=366,951,527 out=81,157,278 elapsed=162.6s

  [11009/15692] intraday_5318.csv.gz  in=366,963,882 out=81,157,278 elapsed=162.6s

  [11010/15692] intraday_5315.csv.gz  in=366,976,536 out=81,157,278 elapsed=162.6s

  [11011/15692] intraday_5317.csv.gz  in=366,989,787 out=81,157,278 elapsed=162.6s

  [11012/15692] intraday_5320.csv.gz  in=367,000,934 out=81,157,278 elapsed=162.6s

  [11013/15692] intraday_5319.csv.gz  in=367,013,839 out=81,157,278 elapsed=162.6s

  [11014/15692] intraday_5321.csv.gz  in=367,027,893 out=81,157,278 elapsed=162.6s

  [11015/15692] intraday_5322.csv.gz  in=367,039,493 out=81,157,278 elapsed=162.6s

  [11016/15692] intraday_5323.csv.gz  in=367,052,412 out=81,157,278 elapsed=162.6s

  [11017/15692] intraday_5324.csv.gz  in=367,062,974 out=81,157,278 elapsed=162.6s

  [11018/15692] intraday_5325.csv.gz  in=367,076,036 out=81,157,278 elapsed=162.7s

  [11019/15692] intraday_5329.csv.gz  in=367,089,043 out=81,157,278 elapsed=162.7s

  [11020/15692] intraday_5326.csv.gz  in=367,102,125 out=81,157,278 elapsed=162.7s

  [11021/15692] intraday_5328.csv.gz  in=367,116,428 out=81,157,278 elapsed=162.7s

  [11022/15692] intraday_5327.csv.gz  in=367,132,574 out=81,157,278 elapsed=162.7s

  [11023/15692] intraday_5330.csv.gz  in=367,144,323 out=81,157,278 elapsed=162.7s

  [11024/15692] intraday_5331.csv.gz  in=367,156,022 out=81,157,278 elapsed=162.7s

  [11025/15692] intraday_5332.csv.gz  in=367,170,080 out=81,157,278 elapsed=162.7s

  [11026/15692] intraday_5333.csv.gz  in=367,188,088 out=81,157,278 elapsed=162.7s

  [11027/15692] intraday_5335.csv.gz  in=367,201,867 out=81,157,278 elapsed=162.8s

  [11028/15692] intraday_5334.csv.gz  in=367,213,753 out=81,157,278 elapsed=162.8s

  [11029/15692] intraday_5336.csv.gz  in=367,226,503 out=81,157,278 elapsed=162.8s

  [11030/15692] intraday_5337.csv.gz  in=367,241,135 out=81,157,278 elapsed=162.8s

  [11031/15692] intraday_5339.csv.gz  in=367,253,541 out=81,157,278 elapsed=162.8s

  [11032/15692] intraday_5338.csv.gz  in=367,267,800 out=81,157,278 elapsed=162.8s

  [11033/15692] intraday_5340.csv.gz  in=367,281,367 out=81,157,278 elapsed=162.8s

  [11034/15692] intraday_5342.csv.gz  in=367,295,605 out=81,157,278 elapsed=162.8s

  [11035/15692] intraday_5341.csv.gz  in=367,307,384 out=81,157,278 elapsed=162.8s

  [11036/15692] intraday_5344.csv.gz  in=367,320,374 out=81,157,278 elapsed=162.8s

  [11037/15692] intraday_5343.csv.gz  in=367,333,208 out=81,157,278 elapsed=162.8s

  [11038/15692] intraday_5345.csv.gz  in=367,346,459 out=81,157,278 elapsed=162.8s

  [11039/15692] intraday_5346.csv.gz  in=367,362,240 out=81,157,278 elapsed=162.9s

  [11040/15692] intraday_5348.csv.gz  in=367,375,472 out=81,157,278 elapsed=162.9s

  [11041/15692] intraday_5349.csv.gz  in=367,391,900 out=81,157,278 elapsed=162.9s

  [11042/15692] intraday_5347.csv.gz  in=367,403,210 out=81,157,278 elapsed=162.9s

  [11043/15692] intraday_5350.csv.gz  in=367,414,116 out=81,157,278 elapsed=162.9s

  [11044/15692] intraday_5352.csv.gz  in=367,429,622 out=81,157,278 elapsed=162.9s

  [11045/15692] intraday_5351.csv.gz  in=367,441,788 out=81,157,278 elapsed=162.9s

  [11046/15692] intraday_5353.csv.gz  in=367,456,676 out=81,157,278 elapsed=162.9s

  [11047/15692] intraday_5354.csv.gz  in=367,469,051 out=81,157,278 elapsed=162.9s

  [11048/15692] intraday_5355.csv.gz  in=367,482,628 out=81,157,278 elapsed=162.9s

  [11049/15692] intraday_5356.csv.gz  in=367,496,906 out=81,157,278 elapsed=163.0s

  [11050/15692] intraday_5357.csv.gz  in=367,511,948 out=81,157,278 elapsed=163.0s

  [11051/15692] intraday_5358.csv.gz  in=367,527,852 out=81,157,278 elapsed=163.0s

  [11052/15692] intraday_5359.csv.gz  in=367,542,368 out=81,157,278 elapsed=163.0s

  [11053/15692] intraday_5360.csv.gz  in=367,556,483 out=81,157,278 elapsed=163.0s

  [11054/15692] intraday_5361.csv.gz  in=367,573,441 out=81,157,278 elapsed=163.0s

  [11055/15692] intraday_5362.csv.gz  in=367,587,437 out=81,157,278 elapsed=163.0s

  [11056/15692] intraday_5363.csv.gz  in=367,600,299 out=81,157,278 elapsed=163.0s

  [11057/15692] intraday_5364.csv.gz  in=367,612,265 out=81,157,278 elapsed=163.0s

  [11058/15692] intraday_5366.csv.gz  in=367,623,395 out=81,157,278 elapsed=163.0s

  [11059/15692] intraday_5365.csv.gz  in=367,636,698 out=81,157,278 elapsed=163.0s

  [11060/15692] intraday_5367.csv.gz  in=367,650,462 out=81,157,278 elapsed=163.0s

  [11061/15692] intraday_5368.csv.gz  in=367,664,184 out=81,157,278 elapsed=163.1s

  [11062/15692] intraday_5370.csv.gz  in=367,680,265 out=81,157,278 elapsed=163.1s

  [11063/15692] intraday_5369.csv.gz  in=367,694,609 out=81,157,278 elapsed=163.1s

  [11064/15692] intraday_5371.csv.gz  in=367,707,289 out=81,157,278 elapsed=163.1s

  [11065/15692] intraday_5372.csv.gz  in=367,719,513 out=81,157,278 elapsed=163.1s

  [11066/15692] intraday_5373.csv.gz  in=367,734,120 out=81,157,278 elapsed=163.1s

  [11067/15692] intraday_5375.csv.gz  in=367,746,637 out=81,157,278 elapsed=163.1s

  [11068/15692] intraday_5374.csv.gz  in=367,759,373 out=81,157,278 elapsed=163.1s

  [11069/15692] intraday_5376.csv.gz  in=367,775,219 out=81,157,278 elapsed=163.1s

  [11070/15692] intraday_5377.csv.gz  in=367,789,349 out=81,157,278 elapsed=163.1s

  [11071/15692] intraday_5378.csv.gz  in=367,802,918 out=81,157,278 elapsed=163.1s

  [11072/15692] intraday_5380.csv.gz  in=367,813,868 out=81,157,278 elapsed=163.1s

  [11073/15692] intraday_5382.csv.gz  in=367,825,524 out=81,157,278 elapsed=163.2s

  [11074/15692] intraday_5379.csv.gz  in=367,838,436 out=81,157,278 elapsed=163.2s

  [11075/15692] intraday_5381.csv.gz  in=367,852,137 out=81,157,278 elapsed=163.2s

  [11076/15692] intraday_5383.csv.gz  in=367,866,590 out=81,157,278 elapsed=163.2s

  [11077/15692] intraday_5384.csv.gz  in=367,875,462 out=81,157,278 elapsed=163.2s

  [11078/15692] intraday_5387.csv.gz  in=367,876,017 out=81,157,278 elapsed=163.2s

  [11079/15692] intraday_5388.csv.gz  in=367,876,817 out=81,157,278 elapsed=163.2s

  [11080/15692] intraday_5386.csv.gz  in=367,886,375 out=81,157,278 elapsed=163.2s

  [11081/15692] intraday_5385.csv.gz  in=367,897,895 out=81,157,278 elapsed=163.2s

  [11082/15692] intraday_5389.csv.gz  in=367,899,669 out=81,157,278 elapsed=163.2s

  [11083/15692] intraday_5390.csv.gz  in=367,900,273 out=81,157,278 elapsed=163.2s

  [11084/15692] intraday_5392.csv.gz  in=367,901,031 out=81,157,278 elapsed=163.2s

  [11085/15692] intraday_5391.csv.gz  in=367,901,198 out=81,157,278 elapsed=163.2s

  [11086/15692] intraday_5393.csv.gz  in=367,901,553 out=81,157,278 elapsed=163.3s

  [11087/15692] intraday_5394.csv.gz  in=367,901,946 out=81,157,278 elapsed=163.3s

  [11088/15692] intraday_5395.csv.gz  in=367,901,976 out=81,157,278 elapsed=163.3s

  [11089/15692] intraday_5396.csv.gz  in=367,902,010 out=81,157,278 elapsed=163.3s

  [11090/15692] intraday_5398.csv.gz  in=367,915,189 out=81,157,278 elapsed=163.3s

  [11091/15692] intraday_5399.csv.gz  in=367,928,615 out=81,157,278 elapsed=163.3s

  [11092/15692] intraday_5397.csv.gz  in=367,944,361 out=81,157,278 elapsed=163.3s

  [11093/15692] intraday_5400.csv.gz  in=367,956,629 out=81,157,278 elapsed=163.3s

  [11094/15692] intraday_5401.csv.gz  in=367,969,416 out=81,157,278 elapsed=163.3s

  [11095/15692] intraday_5404.csv.gz  in=367,981,198 out=81,157,278 elapsed=163.3s

  [11096/15692] intraday_5402.csv.gz  in=367,996,466 out=81,157,278 elapsed=163.3s

  [11097/15692] intraday_5405.csv.gz  in=368,010,479 out=81,157,278 elapsed=163.4s

  [11098/15692] intraday_5403.csv.gz  in=368,024,926 out=81,157,278 elapsed=163.4s

  [11099/15692] intraday_5407.csv.gz  in=368,039,182 out=81,157,278 elapsed=163.4s

  [11100/15692] intraday_5408.csv.gz  in=368,052,917 out=81,157,278 elapsed=163.4s

  [11101/15692] intraday_5406.csv.gz  in=368,067,507 out=81,157,278 elapsed=163.4s

  [11102/15692] intraday_5409.csv.gz  in=368,079,585 out=81,157,278 elapsed=163.4s

  [11103/15692] intraday_5410.csv.gz  in=368,091,872 out=81,157,278 elapsed=163.4s

  [11104/15692] intraday_5412.csv.gz  in=368,101,331 out=81,157,278 elapsed=163.4s

  [11105/15692] intraday_5411.csv.gz  in=368,111,945 out=81,157,278 elapsed=163.4s

  [11106/15692] intraday_5413.csv.gz  in=368,127,402 out=81,157,278 elapsed=163.5s

  [11107/15692] intraday_5414.csv.gz  in=368,141,110 out=81,157,278 elapsed=163.5s

  [11108/15692] intraday_5416.csv.gz  in=368,153,215 out=81,157,278 elapsed=163.5s

  [11109/15692] intraday_5415.csv.gz  in=368,164,835 out=81,157,278 elapsed=163.5s

  [11110/15692] intraday_5417.csv.gz  in=368,178,071 out=81,157,278 elapsed=163.5s

  [11111/15692] intraday_5418.csv.gz  in=368,191,695 out=81,157,278 elapsed=163.5s

  [11112/15692] intraday_5419.csv.gz  in=368,204,978 out=81,157,278 elapsed=163.5s

  [11113/15692] intraday_5420.csv.gz  in=368,217,428 out=81,157,278 elapsed=163.5s

  [11114/15692] intraday_5421.csv.gz  in=368,230,924 out=81,157,278 elapsed=163.5s

  [11115/15692] intraday_5422.csv.gz  in=368,242,084 out=81,157,278 elapsed=163.5s

  [11116/15692] intraday_5423.csv.gz  in=368,254,547 out=81,157,278 elapsed=163.6s

  [11117/15692] intraday_5425.csv.gz  in=368,268,955 out=81,157,278 elapsed=163.6s

  [11118/15692] intraday_5426.csv.gz  in=368,284,108 out=81,157,278 elapsed=163.6s

  [11119/15692] intraday_5427.csv.gz  in=368,299,492 out=81,157,278 elapsed=163.6s

  [11120/15692] intraday_5424.csv.gz  in=368,310,932 out=81,157,278 elapsed=163.6s

  [11121/15692] intraday_5429.csv.gz  in=368,322,883 out=81,157,278 elapsed=163.6s

  [11122/15692] intraday_5430.csv.gz  in=368,335,270 out=81,157,278 elapsed=163.6s

  [11123/15692] intraday_5431.csv.gz  in=368,349,762 out=81,157,278 elapsed=163.6s

  [11124/15692] intraday_5428.csv.gz  in=368,361,341 out=81,157,278 elapsed=163.6s

  [11125/15692] intraday_5432.csv.gz  in=368,372,260 out=81,157,278 elapsed=163.6s

  [11126/15692] intraday_5435.csv.gz  in=368,383,157 out=81,157,278 elapsed=163.7s

  [11127/15692] intraday_5433.csv.gz  in=368,395,787 out=81,157,278 elapsed=163.7s

  [11128/15692] intraday_5434.csv.gz  in=368,408,875 out=81,157,278 elapsed=163.7s

  [11129/15692] intraday_5436.csv.gz  in=368,419,943 out=81,157,278 elapsed=163.7s

  [11130/15692] intraday_5438.csv.gz  in=368,433,024 out=81,157,278 elapsed=163.7s

  [11131/15692] intraday_5437.csv.gz  in=368,446,189 out=81,157,278 elapsed=163.7s

  [11132/15692] intraday_5439.csv.gz  in=368,459,942 out=81,157,278 elapsed=163.7s

  [11133/15692] intraday_5440.csv.gz  in=368,473,291 out=81,157,278 elapsed=163.7s

  [11134/15692] intraday_5441.csv.gz  in=368,486,929 out=81,157,278 elapsed=163.7s

  [11135/15692] intraday_5443.csv.gz  in=368,499,162 out=81,157,278 elapsed=163.7s

  [11136/15692] intraday_5442.csv.gz  in=368,511,511 out=81,157,278 elapsed=163.7s

  [11137/15692] intraday_5444.csv.gz  in=368,523,143 out=81,157,278 elapsed=163.8s

  [11138/15692] intraday_5445.csv.gz  in=368,535,746 out=81,157,278 elapsed=163.8s

  [11139/15692] intraday_5447.csv.gz  in=368,547,705 out=81,157,278 elapsed=163.8s

  [11140/15692] intraday_5446.csv.gz  in=368,558,925 out=81,157,278 elapsed=163.8s

  [11141/15692] intraday_5449.csv.gz  in=368,568,647 out=81,157,278 elapsed=163.8s

  [11142/15692] intraday_5451.csv.gz  in=368,582,927 out=81,157,278 elapsed=163.8s

  [11143/15692] intraday_5450.csv.gz  in=368,594,669 out=81,157,278 elapsed=163.8s

  [11144/15692] intraday_5448.csv.gz  in=368,609,844 out=81,157,278 elapsed=163.8s

  [11145/15692] intraday_5453.csv.gz  in=368,624,779 out=81,157,278 elapsed=163.9s

  [11146/15692] intraday_5454.csv.gz  in=368,637,161 out=81,157,278 elapsed=163.9s

  [11147/15692] intraday_5452.csv.gz  in=368,659,058 out=81,157,278 elapsed=163.9s

  [11148/15692] intraday_5455.csv.gz  in=368,672,311 out=81,157,278 elapsed=163.9s

  [11149/15692] intraday_5458.csv.gz  in=368,683,986 out=81,157,278 elapsed=163.9s

  [11150/15692] intraday_5456.csv.gz  in=368,696,971 out=81,157,278 elapsed=163.9s

  [11151/15692] intraday_5457.csv.gz  in=368,710,018 out=81,157,278 elapsed=163.9s

  [11152/15692] intraday_5459.csv.gz  in=368,720,796 out=81,157,278 elapsed=163.9s

  [11153/15692] intraday_5460.csv.gz  in=368,731,203 out=81,157,278 elapsed=163.9s

  [11154/15692] intraday_5464.csv.gz  in=368,743,089 out=81,157,278 elapsed=163.9s

  [11155/15692] intraday_5461.csv.gz  in=368,758,244 out=81,157,278 elapsed=163.9s

  [11156/15692] intraday_5462.csv.gz  in=368,771,688 out=81,157,278 elapsed=163.9s

  [11157/15692] intraday_5463.csv.gz  in=368,786,200 out=81,157,278 elapsed=164.0s

  [11158/15692] intraday_5465.csv.gz  in=368,796,360 out=81,157,278 elapsed=164.0s

  [11159/15692] intraday_5468.csv.gz  in=368,808,279 out=81,157,278 elapsed=164.0s

  [11160/15692] intraday_5466.csv.gz  in=368,820,019 out=81,157,278 elapsed=164.0s

  [11161/15692] intraday_5469.csv.gz  in=368,833,944 out=81,157,278 elapsed=164.0s

  [11162/15692] intraday_5467.csv.gz  in=368,846,394 out=81,157,278 elapsed=164.0s

  [11163/15692] intraday_5470.csv.gz  in=368,858,054 out=81,157,278 elapsed=164.0s

  [11164/15692] intraday_5471.csv.gz  in=368,869,685 out=81,157,278 elapsed=164.0s

  [11165/15692] intraday_5472.csv.gz  in=368,881,444 out=81,157,278 elapsed=164.0s

  [11166/15692] intraday_5473.csv.gz  in=368,895,051 out=81,157,278 elapsed=164.0s

  [11167/15692] intraday_5474.csv.gz  in=368,906,485 out=81,157,278 elapsed=164.1s

  [11168/15692] intraday_5476.csv.gz  in=368,916,536 out=81,157,278 elapsed=164.1s

  [11169/15692] intraday_5475.csv.gz  in=368,929,805 out=81,157,278 elapsed=164.1s

  [11170/15692] intraday_5477.csv.gz  in=368,942,964 out=81,157,278 elapsed=164.1s

  [11171/15692] intraday_5480.csv.gz  in=368,956,588 out=81,157,278 elapsed=164.1s

  [11172/15692] intraday_5478.csv.gz  in=368,968,630 out=81,157,278 elapsed=164.1s

  [11173/15692] intraday_5479.csv.gz  in=368,984,815 out=81,157,278 elapsed=164.1s

  [11174/15692] intraday_5481.csv.gz  in=368,997,169 out=81,157,278 elapsed=164.1s

  [11175/15692] intraday_5482.csv.gz  in=369,008,866 out=81,157,278 elapsed=164.1s

  [11176/15692] intraday_5483.csv.gz  in=369,020,550 out=81,157,278 elapsed=164.1s

  [11177/15692] intraday_5484.csv.gz  in=369,034,708 out=81,157,278 elapsed=164.2s

  [11178/15692] intraday_5486.csv.gz  in=369,046,844 out=81,157,278 elapsed=164.2s

  [11179/15692] intraday_5485.csv.gz  in=369,066,124 out=81,157,278 elapsed=164.2s

  [11180/15692] intraday_5487.csv.gz  in=369,079,683 out=81,157,278 elapsed=164.2s

  [11181/15692] intraday_5489.csv.gz  in=369,093,819 out=81,157,278 elapsed=164.2s

  [11182/15692] intraday_5488.csv.gz  in=369,107,041 out=81,157,278 elapsed=164.2s

  [11183/15692] intraday_5491.csv.gz  in=369,119,380 out=81,157,278 elapsed=164.2s

  [11184/15692] intraday_5490.csv.gz  in=369,133,146 out=81,157,278 elapsed=164.2s

  [11185/15692] intraday_5492.csv.gz  in=369,146,390 out=81,157,278 elapsed=164.2s

  [11186/15692] intraday_5493.csv.gz  in=369,157,792 out=81,157,278 elapsed=164.2s

  [11187/15692] intraday_5495.csv.gz  in=369,170,315 out=81,157,278 elapsed=164.3s

  [11188/15692] intraday_5494.csv.gz  in=369,184,781 out=81,157,278 elapsed=164.3s

  [11189/15692] intraday_5496.csv.gz  in=369,198,129 out=81,157,278 elapsed=164.3s

  [11190/15692] intraday_5500.csv.gz  in=369,211,248 out=81,157,278 elapsed=164.3s

  [11191/15692] intraday_5499.csv.gz  in=369,222,754 out=81,157,278 elapsed=164.3s

  [11192/15692] intraday_5498.csv.gz  in=369,238,018 out=81,157,278 elapsed=164.3s

  [11193/15692] intraday_5497.csv.gz  in=369,268,745 out=81,157,278 elapsed=164.3s

  [11194/15692] intraday_5502.csv.gz  in=369,279,849 out=81,157,278 elapsed=164.3s

  [11195/15692] intraday_5501.csv.gz  in=369,296,377 out=81,157,278 elapsed=164.3s

  [11196/15692] intraday_5503.csv.gz  in=369,308,611 out=81,157,278 elapsed=164.4s

  [11197/15692] intraday_5504.csv.gz  in=369,324,893 out=81,157,278 elapsed=164.4s

  [11198/15692] intraday_5506.csv.gz  in=369,337,238 out=81,157,278 elapsed=164.4s

  [11199/15692] intraday_5507.csv.gz  in=369,350,846 out=81,157,278 elapsed=164.4s

  [11200/15692] intraday_5505.csv.gz  in=369,365,635 out=81,157,278 elapsed=164.4s

  [11201/15692] intraday_5508.csv.gz  in=369,379,276 out=81,157,278 elapsed=164.4s

  [11202/15692] intraday_5509.csv.gz  in=369,392,271 out=81,157,278 elapsed=164.4s

  [11203/15692] intraday_5511.csv.gz  in=369,405,210 out=81,157,278 elapsed=164.4s

  [11204/15692] intraday_5512.csv.gz  in=369,420,139 out=81,157,278 elapsed=164.4s

  [11205/15692] intraday_5510.csv.gz  in=369,436,532 out=81,157,278 elapsed=164.4s

  [11206/15692] intraday_5513.csv.gz  in=369,452,877 out=81,157,278 elapsed=164.5s

  [11207/15692] intraday_5515.csv.gz  in=369,465,034 out=81,157,278 elapsed=164.5s

  [11208/15692] intraday_5516.csv.gz  in=369,476,074 out=81,157,278 elapsed=164.5s

  [11209/15692] intraday_5514.csv.gz  in=369,490,062 out=81,157,278 elapsed=164.5s

  [11210/15692] intraday_5517.csv.gz  in=369,504,614 out=81,157,278 elapsed=164.5s

  [11211/15692] intraday_5520.csv.gz  in=369,517,500 out=81,157,278 elapsed=164.5s

  [11212/15692] intraday_5518.csv.gz  in=369,528,422 out=81,157,278 elapsed=164.5s

  [11213/15692] intraday_5519.csv.gz  in=369,541,864 out=81,157,278 elapsed=164.5s

  [11214/15692] intraday_5521.csv.gz  in=369,558,334 out=81,157,278 elapsed=164.5s

  [11215/15692] intraday_5522.csv.gz  in=369,571,384 out=81,157,278 elapsed=164.6s

  [11216/15692] intraday_5523.csv.gz  in=369,584,135 out=81,157,278 elapsed=164.6s

  [11217/15692] intraday_5525.csv.gz  in=369,597,722 out=81,157,278 elapsed=164.6s

  [11218/15692] intraday_5524.csv.gz  in=369,610,871 out=81,157,278 elapsed=164.6s

  [11219/15692] intraday_5527.csv.gz  in=369,623,952 out=81,157,278 elapsed=164.6s

  [11220/15692] intraday_5528.csv.gz  in=369,638,798 out=81,157,278 elapsed=164.6s

  [11221/15692] intraday_5526.csv.gz  in=369,654,220 out=81,157,278 elapsed=164.6s

  [11222/15692] intraday_5529.csv.gz  in=369,669,075 out=81,157,278 elapsed=164.6s

  [11223/15692] intraday_5530.csv.gz  in=369,684,282 out=81,157,278 elapsed=164.6s

  [11224/15692] intraday_5532.csv.gz  in=369,696,061 out=81,157,278 elapsed=164.6s

  [11225/15692] intraday_5533.csv.gz  in=369,709,829 out=81,157,278 elapsed=164.7s

  [11226/15692] intraday_5531.csv.gz  in=369,721,125 out=81,157,278 elapsed=164.7s

  [11227/15692] intraday_5534.csv.gz  in=369,733,305 out=81,157,278 elapsed=164.7s

  [11228/15692] intraday_5537.csv.gz  in=369,744,926 out=81,157,278 elapsed=164.7s

  [11229/15692] intraday_5536.csv.gz  in=369,752,541 out=81,157,278 elapsed=164.7s

  [11230/15692] intraday_5538.csv.gz  in=369,761,159 out=81,157,278 elapsed=164.7s

  [11231/15692] intraday_5535.csv.gz  in=369,794,841 out=81,157,278 elapsed=164.7s

  [11232/15692] intraday_5539.csv.gz  in=369,809,268 out=81,157,278 elapsed=164.7s

  [11233/15692] intraday_5540.csv.gz  in=369,822,554 out=81,157,278 elapsed=164.7s

  [11234/15692] intraday_5541.csv.gz  in=369,834,949 out=81,157,278 elapsed=164.7s

  [11235/15692] intraday_5542.csv.gz  in=369,846,532 out=81,157,278 elapsed=164.8s

  [11236/15692] intraday_5544.csv.gz  in=369,861,727 out=81,157,278 elapsed=164.8s

  [11237/15692] intraday_5543.csv.gz  in=369,874,043 out=81,157,278 elapsed=164.8s

  [11238/15692] intraday_5546.csv.gz  in=369,885,569 out=81,157,278 elapsed=164.8s

  [11239/15692] intraday_5545.csv.gz  in=369,900,993 out=81,157,278 elapsed=164.8s

  [11240/15692] intraday_5548.csv.gz  in=369,914,564 out=81,157,278 elapsed=164.8s

  [11241/15692] intraday_5547.csv.gz  in=369,927,410 out=81,157,278 elapsed=164.8s

  [11242/15692] intraday_5549.csv.gz  in=369,940,756 out=81,157,278 elapsed=164.8s

  [11243/15692] intraday_5550.csv.gz  in=369,957,703 out=81,157,278 elapsed=164.8s

  [11244/15692] intraday_5551.csv.gz  in=369,969,671 out=81,157,278 elapsed=164.8s

  [11245/15692] intraday_5553.csv.gz  in=369,979,840 out=81,157,278 elapsed=164.8s

  [11246/15692] intraday_5552.csv.gz  in=369,991,359 out=81,157,278 elapsed=164.8s

  [11247/15692] intraday_5554.csv.gz  in=370,000,352 out=81,157,278 elapsed=164.8s

  [11248/15692] intraday_5556.csv.gz  in=370,013,869 out=81,157,278 elapsed=164.9s

  [11249/15692] intraday_5555.csv.gz  in=370,028,173 out=81,157,278 elapsed=164.9s

  [11250/15692] intraday_5557.csv.gz  in=370,038,411 out=81,157,278 elapsed=164.9s

  [11251/15692] intraday_5558.csv.gz  in=370,049,632 out=81,157,278 elapsed=164.9s

  [11252/15692] intraday_5559.csv.gz  in=370,061,660 out=81,157,278 elapsed=164.9s

  [11253/15692] intraday_5560.csv.gz  in=370,075,420 out=81,157,278 elapsed=164.9s

  [11254/15692] intraday_5561.csv.gz  in=370,087,949 out=81,157,278 elapsed=164.9s

  [11255/15692] intraday_5562.csv.gz  in=370,100,279 out=81,157,278 elapsed=164.9s

  [11256/15692] intraday_5564.csv.gz  in=370,111,343 out=81,157,278 elapsed=164.9s

  [11257/15692] intraday_5563.csv.gz  in=370,125,055 out=81,157,278 elapsed=164.9s

  [11258/15692] intraday_5565.csv.gz  in=370,137,449 out=81,157,278 elapsed=164.9s

  [11259/15692] intraday_5566.csv.gz  in=370,148,975 out=81,157,278 elapsed=164.9s

  [11260/15692] intraday_5568.csv.gz  in=370,163,849 out=81,157,278 elapsed=164.9s

  [11261/15692] intraday_5567.csv.gz  in=370,176,875 out=81,157,278 elapsed=165.0s

  [11262/15692] intraday_5569.csv.gz  in=370,191,778 out=81,157,278 elapsed=165.0s

  [11263/15692] intraday_5570.csv.gz  in=370,202,512 out=81,157,278 elapsed=165.0s

  [11264/15692] intraday_5571.csv.gz  in=370,214,162 out=81,157,278 elapsed=165.0s

  [11265/15692] intraday_5573.csv.gz  in=370,228,010 out=81,157,278 elapsed=165.0s

  [11266/15692] intraday_5572.csv.gz  in=370,240,092 out=81,157,278 elapsed=165.0s

  [11267/15692] intraday_5577.csv.gz  in=370,250,758 out=81,157,278 elapsed=165.0s

  [11268/15692] intraday_5574.csv.gz  in=370,272,411 out=81,157,278 elapsed=165.0s

  [11269/15692] intraday_5576.csv.gz  in=370,284,095 out=81,157,278 elapsed=165.0s

  [11270/15692] intraday_5575.csv.gz  in=370,295,874 out=81,157,278 elapsed=165.0s

  [11271/15692] intraday_5578.csv.gz  in=370,306,928 out=81,157,278 elapsed=165.0s

  [11272/15692] intraday_5579.csv.gz  in=370,323,483 out=81,157,278 elapsed=165.1s

  [11273/15692] intraday_5580.csv.gz  in=370,335,846 out=81,157,278 elapsed=165.1s

  [11274/15692] intraday_5582.csv.gz  in=370,349,641 out=81,157,278 elapsed=165.1s

  [11275/15692] intraday_5581.csv.gz  in=370,361,849 out=81,157,278 elapsed=165.1s

  [11276/15692] intraday_5583.csv.gz  in=370,374,508 out=81,157,278 elapsed=165.1s

  [11277/15692] intraday_5584.csv.gz  in=370,386,397 out=81,157,278 elapsed=165.1s

  [11278/15692] intraday_5586.csv.gz  in=370,397,759 out=81,157,278 elapsed=165.1s

  [11279/15692] intraday_5585.csv.gz  in=370,409,584 out=81,157,278 elapsed=165.1s

  [11280/15692] intraday_5587.csv.gz  in=370,421,639 out=81,157,278 elapsed=165.1s

  [11281/15692] intraday_5588.csv.gz  in=370,432,808 out=81,157,278 elapsed=165.1s

  [11282/15692] intraday_5590.csv.gz  in=370,446,729 out=81,157,278 elapsed=165.1s

  [11283/15692] intraday_5589.csv.gz  in=370,458,049 out=81,157,278 elapsed=165.2s

  [11284/15692] intraday_5592.csv.gz  in=370,468,089 out=81,157,278 elapsed=165.2s

  [11285/15692] intraday_5591.csv.gz  in=370,478,275 out=81,157,278 elapsed=165.2s

  [11286/15692] intraday_5595.csv.gz  in=370,492,404 out=81,157,278 elapsed=165.2s

  [11287/15692] intraday_5593.csv.gz  in=370,506,806 out=81,157,278 elapsed=165.2s

  [11288/15692] intraday_5594.csv.gz  in=370,519,036 out=81,157,278 elapsed=165.2s

  [11289/15692] intraday_5596.csv.gz  in=370,530,825 out=81,157,278 elapsed=165.2s

  [11290/15692] intraday_5598.csv.gz  in=370,543,112 out=81,157,278 elapsed=165.2s

  [11291/15692] intraday_5597.csv.gz  in=370,555,863 out=81,157,278 elapsed=165.2s

  [11292/15692] intraday_5599.csv.gz  in=370,568,453 out=81,157,278 elapsed=165.2s

  [11293/15692] intraday_5600.csv.gz  in=370,579,952 out=81,157,278 elapsed=165.2s

  [11294/15692] intraday_5602.csv.gz  in=370,590,674 out=81,157,278 elapsed=165.3s

  [11295/15692] intraday_5601.csv.gz  in=370,601,412 out=81,157,278 elapsed=165.3s

  [11296/15692] intraday_5603.csv.gz  in=370,615,962 out=81,157,278 elapsed=165.3s

  [11297/15692] intraday_5604.csv.gz  in=370,629,005 out=81,157,278 elapsed=165.3s

  [11298/15692] intraday_5607.csv.gz  in=370,638,681 out=81,157,278 elapsed=165.3s

  [11299/15692] intraday_5608.csv.gz  in=370,650,196 out=81,157,278 elapsed=165.3s

  [11300/15692] intraday_5605.csv.gz  in=370,664,240 out=81,157,278 elapsed=165.3s

  [11301/15692] intraday_5606.csv.gz  in=370,676,361 out=81,157,278 elapsed=165.3s

  [11302/15692] intraday_5609.csv.gz  in=370,688,059 out=81,157,278 elapsed=165.3s

  [11303/15692] intraday_5611.csv.gz  in=370,701,491 out=81,157,278 elapsed=165.3s

  [11304/15692] intraday_5610.csv.gz  in=370,713,598 out=81,157,278 elapsed=165.3s

  [11305/15692] intraday_5612.csv.gz  in=370,724,672 out=81,157,278 elapsed=165.3s

  [11306/15692] intraday_5613.csv.gz  in=370,736,269 out=81,157,278 elapsed=165.4s

  [11307/15692] intraday_5615.csv.gz  in=370,749,637 out=81,157,278 elapsed=165.4s

  [11308/15692] intraday_5614.csv.gz  in=370,760,067 out=81,157,278 elapsed=165.4s

  [11309/15692] intraday_5616.csv.gz  in=370,770,975 out=81,157,278 elapsed=165.4s

  [11310/15692] intraday_5617.csv.gz  in=370,783,609 out=81,157,278 elapsed=165.4s

  [11311/15692] intraday_5618.csv.gz  in=370,794,241 out=81,157,278 elapsed=165.4s

  [11312/15692] intraday_5619.csv.gz  in=370,805,882 out=81,157,278 elapsed=165.4s

  [11313/15692] intraday_5620.csv.gz  in=370,817,292 out=81,157,278 elapsed=165.4s

  [11314/15692] intraday_5624.csv.gz  in=370,829,249 out=81,157,278 elapsed=165.4s

  [11315/15692] intraday_5621.csv.gz  in=370,844,257 out=81,157,278 elapsed=165.5s

  [11316/15692] intraday_5623.csv.gz  in=370,856,223 out=81,157,278 elapsed=165.5s

  [11317/15692] intraday_5622.csv.gz  in=370,870,334 out=81,157,278 elapsed=165.5s

  [11318/15692] intraday_5625.csv.gz  in=370,881,448 out=81,157,278 elapsed=165.5s

  [11319/15692] intraday_5627.csv.gz  in=370,897,456 out=81,157,278 elapsed=165.5s

  [11320/15692] intraday_5628.csv.gz  in=370,909,399 out=81,157,278 elapsed=165.5s

  [11321/15692] intraday_5626.csv.gz  in=370,923,026 out=81,157,278 elapsed=165.5s

  [11322/15692] intraday_5629.csv.gz  in=370,936,235 out=81,157,278 elapsed=165.5s

  [11323/15692] intraday_5631.csv.gz  in=370,949,784 out=81,157,278 elapsed=165.5s

  [11324/15692] intraday_5630.csv.gz  in=370,962,799 out=81,157,278 elapsed=165.5s

  [11325/15692] intraday_5632.csv.gz  in=370,977,105 out=81,157,278 elapsed=165.6s

  [11326/15692] intraday_5633.csv.gz  in=370,989,507 out=81,157,278 elapsed=165.6s

  [11327/15692] intraday_5634.csv.gz  in=371,002,487 out=81,157,278 elapsed=165.6s

  [11328/15692] intraday_5635.csv.gz  in=371,014,040 out=81,157,278 elapsed=165.6s

  [11329/15692] intraday_5636.csv.gz  in=371,028,028 out=81,157,278 elapsed=165.6s

  [11330/15692] intraday_5637.csv.gz  in=371,055,738 out=81,157,278 elapsed=165.6s

  [11331/15692] intraday_5638.csv.gz  in=371,068,451 out=81,157,278 elapsed=165.6s

  [11332/15692] intraday_5639.csv.gz  in=371,080,428 out=81,157,278 elapsed=165.6s

  [11333/15692] intraday_5641.csv.gz  in=371,091,374 out=81,157,278 elapsed=165.6s

  [11334/15692] intraday_5640.csv.gz  in=371,105,990 out=81,157,278 elapsed=165.6s

  [11335/15692] intraday_5642.csv.gz  in=371,118,358 out=81,157,278 elapsed=165.6s

  [11336/15692] intraday_5644.csv.gz  in=371,129,055 out=81,157,278 elapsed=165.7s

  [11337/15692] intraday_5643.csv.gz  in=371,145,463 out=81,157,278 elapsed=165.7s

  [11338/15692] intraday_5645.csv.gz  in=371,159,168 out=81,157,278 elapsed=165.7s

  [11339/15692] intraday_5646.csv.gz  in=371,175,101 out=81,157,278 elapsed=165.7s

  [11340/15692] intraday_5647.csv.gz  in=371,190,040 out=81,157,278 elapsed=165.7s

  [11341/15692] intraday_5648.csv.gz  in=371,202,139 out=81,157,278 elapsed=165.7s

  [11342/15692] intraday_5649.csv.gz  in=371,215,285 out=81,157,278 elapsed=165.7s

  [11343/15692] intraday_5651.csv.gz  in=371,228,072 out=81,157,278 elapsed=165.7s

  [11344/15692] intraday_5650.csv.gz  in=371,241,513 out=81,157,278 elapsed=165.7s

  [11345/15692] intraday_5652.csv.gz  in=371,257,262 out=81,157,278 elapsed=165.7s

  [11346/15692] intraday_5653.csv.gz  in=371,270,143 out=81,157,278 elapsed=165.7s

  [11347/15692] intraday_5655.csv.gz  in=371,285,719 out=81,157,278 elapsed=165.8s

  [11348/15692] intraday_5656.csv.gz  in=371,299,065 out=81,157,278 elapsed=165.8s

  [11349/15692] intraday_5657.csv.gz  in=371,311,078 out=81,157,278 elapsed=165.8s

  [11350/15692] intraday_5654.csv.gz  in=371,324,402 out=81,157,278 elapsed=165.8s

  [11351/15692] intraday_5658.csv.gz  in=371,335,521 out=81,157,278 elapsed=165.8s

  [11352/15692] intraday_5660.csv.gz  in=371,346,663 out=81,157,278 elapsed=165.8s

  [11353/15692] intraday_5659.csv.gz  in=371,360,717 out=81,157,278 elapsed=165.8s

  [11354/15692] intraday_5661.csv.gz  in=371,374,037 out=81,157,278 elapsed=165.8s

  [11355/15692] intraday_5664.csv.gz  in=371,386,282 out=81,157,278 elapsed=165.9s

  [11356/15692] intraday_5663.csv.gz  in=371,403,153 out=81,157,278 elapsed=165.9s

  [11357/15692] intraday_5662.csv.gz  in=371,415,321 out=81,157,278 elapsed=165.9s

  [11358/15692] intraday_5665.csv.gz  in=371,427,919 out=81,157,278 elapsed=165.9s

  [11359/15692] intraday_5667.csv.gz  in=371,440,329 out=81,157,278 elapsed=165.9s

  [11360/15692] intraday_5668.csv.gz  in=371,451,918 out=81,157,278 elapsed=165.9s

  [11361/15692] intraday_5669.csv.gz  in=371,465,606 out=81,157,278 elapsed=165.9s

  [11362/15692] intraday_5666.csv.gz  in=371,477,551 out=81,157,278 elapsed=165.9s

  [11363/15692] intraday_5670.csv.gz  in=371,491,556 out=81,157,278 elapsed=165.9s

  [11364/15692] intraday_5672.csv.gz  in=371,505,367 out=81,157,278 elapsed=166.0s

  [11365/15692] intraday_5673.csv.gz  in=371,516,344 out=81,157,278 elapsed=166.0s

  [11366/15692] intraday_5674.csv.gz  in=371,528,137 out=81,157,278 elapsed=166.0s

  [11367/15692] intraday_5671.csv.gz  in=371,543,675 out=81,157,278 elapsed=166.0s

  [11368/15692] intraday_5675.csv.gz  in=371,557,291 out=81,157,278 elapsed=166.0s

  [11369/15692] intraday_5676.csv.gz  in=371,569,501 out=81,157,278 elapsed=166.0s

  [11370/15692] intraday_5679.csv.gz  in=371,580,712 out=81,157,278 elapsed=166.0s

  [11371/15692] intraday_5678.csv.gz  in=371,588,091 out=81,157,278 elapsed=166.0s

  [11372/15692] intraday_5680.csv.gz  in=371,595,796 out=81,157,278 elapsed=166.0s

  [11373/15692] intraday_5677.csv.gz  in=371,621,494 out=81,157,278 elapsed=166.1s

  [11374/15692] intraday_5681.csv.gz  in=371,636,990 out=81,157,278 elapsed=166.1s

  [11375/15692] intraday_5682.csv.gz  in=371,650,121 out=81,157,278 elapsed=166.1s

  [11376/15692] intraday_5684.csv.gz  in=371,660,704 out=81,157,278 elapsed=166.1s

  [11377/15692] intraday_5683.csv.gz  in=371,672,942 out=81,157,278 elapsed=166.1s

  [11378/15692] intraday_5685.csv.gz  in=371,685,327 out=81,157,278 elapsed=166.1s

  [11379/15692] intraday_5686.csv.gz  in=371,700,734 out=81,157,278 elapsed=166.1s

  [11380/15692] intraday_5687.csv.gz  in=371,716,450 out=81,157,278 elapsed=166.1s

  [11381/15692] intraday_5689.csv.gz  in=371,730,085 out=81,157,278 elapsed=166.1s

  [11382/15692] intraday_5688.csv.gz  in=371,741,772 out=81,157,278 elapsed=166.1s

  [11383/15692] intraday_5690.csv.gz  in=371,755,862 out=81,157,278 elapsed=166.1s

  [11384/15692] intraday_5691.csv.gz  in=371,768,540 out=81,157,278 elapsed=166.2s

  [11385/15692] intraday_5692.csv.gz  in=371,781,974 out=81,157,278 elapsed=166.2s

  [11386/15692] intraday_5693.csv.gz  in=371,796,156 out=81,157,278 elapsed=166.2s

  [11387/15692] intraday_5694.csv.gz  in=371,807,837 out=81,157,278 elapsed=166.2s

  [11388/15692] intraday_5696.csv.gz  in=371,817,446 out=81,157,278 elapsed=166.2s

  [11389/15692] intraday_5697.csv.gz  in=371,831,226 out=81,157,278 elapsed=166.2s

  [11390/15692] intraday_5695.csv.gz  in=371,841,886 out=81,157,278 elapsed=166.2s

  [11391/15692] intraday_5698.csv.gz  in=371,854,837 out=81,157,278 elapsed=166.2s

  [11392/15692] intraday_5699.csv.gz  in=371,868,209 out=81,157,278 elapsed=166.2s

  [11393/15692] intraday_5702.csv.gz  in=371,881,167 out=81,157,278 elapsed=166.3s

  [11394/15692] intraday_5701.csv.gz  in=371,893,024 out=81,157,278 elapsed=166.3s

  [11395/15692] intraday_5700.csv.gz  in=371,905,084 out=81,157,278 elapsed=166.3s

  [11396/15692] intraday_5703.csv.gz  in=371,918,212 out=81,157,278 elapsed=166.3s

  [11397/15692] intraday_5704.csv.gz  in=371,931,066 out=81,157,278 elapsed=166.3s

  [11398/15692] intraday_5705.csv.gz  in=371,944,072 out=81,157,278 elapsed=166.3s

  [11399/15692] intraday_5706.csv.gz  in=371,954,935 out=81,157,278 elapsed=166.3s

  [11400/15692] intraday_5707.csv.gz  in=371,966,825 out=81,157,278 elapsed=166.3s

  [11401/15692] intraday_5709.csv.gz  in=371,981,057 out=81,157,278 elapsed=166.3s

  [11402/15692] intraday_5708.csv.gz  in=371,993,092 out=81,157,278 elapsed=166.3s

  [11403/15692] intraday_5710.csv.gz  in=372,008,120 out=81,157,278 elapsed=166.4s

  [11404/15692] intraday_5711.csv.gz  in=372,023,540 out=81,157,278 elapsed=166.4s

  [11405/15692] intraday_5713.csv.gz  in=372,035,564 out=81,157,278 elapsed=166.4s

  [11406/15692] intraday_5712.csv.gz  in=372,051,854 out=81,157,278 elapsed=166.4s

  [11407/15692] intraday_5716.csv.gz  in=372,061,367 out=81,157,278 elapsed=166.4s

  [11408/15692] intraday_5714.csv.gz  in=372,073,389 out=81,157,278 elapsed=166.4s

  [11409/15692] intraday_5717.csv.gz  in=372,087,147 out=81,157,278 elapsed=166.4s

  [11410/15692] intraday_5715.csv.gz  in=372,119,128 out=81,157,278 elapsed=166.4s

  [11411/15692] intraday_5719.csv.gz  in=372,129,434 out=81,157,278 elapsed=166.4s

  [11412/15692] intraday_5718.csv.gz  in=372,140,313 out=81,157,278 elapsed=166.4s

  [11413/15692] intraday_5720.csv.gz  in=372,151,414 out=81,157,278 elapsed=166.4s

  [11414/15692] intraday_5721.csv.gz  in=372,163,952 out=81,157,278 elapsed=166.4s

  [11415/15692] intraday_5723.csv.gz  in=372,175,564 out=81,157,278 elapsed=166.5s

  [11416/15692] intraday_5722.csv.gz  in=372,188,929 out=81,157,278 elapsed=166.5s

  [11417/15692] intraday_5724.csv.gz  in=372,202,406 out=81,157,278 elapsed=166.5s

  [11418/15692] intraday_5725.csv.gz  in=372,214,996 out=81,157,278 elapsed=166.5s

  [11419/15692] intraday_5726.csv.gz  in=372,226,958 out=81,157,278 elapsed=166.5s

  [11420/15692] intraday_5727.csv.gz  in=372,238,365 out=81,157,278 elapsed=166.5s

  [11421/15692] intraday_5728.csv.gz  in=372,250,665 out=81,157,278 elapsed=166.5s

  [11422/15692] intraday_5729.csv.gz  in=372,261,213 out=81,157,278 elapsed=166.5s

  [11423/15692] intraday_5730.csv.gz  in=372,274,897 out=81,157,278 elapsed=166.6s

  [11424/15692] intraday_5731.csv.gz  in=372,285,242 out=81,157,278 elapsed=166.6s

  [11425/15692] intraday_5732.csv.gz  in=372,300,455 out=81,157,278 elapsed=166.6s

  [11426/15692] intraday_5733.csv.gz  in=372,311,555 out=81,157,278 elapsed=166.6s

  [11427/15692] intraday_5734.csv.gz  in=372,322,173 out=81,157,278 elapsed=166.6s

  [11428/15692] intraday_5735.csv.gz  in=372,336,644 out=81,157,278 elapsed=166.6s

  [11429/15692] intraday_5736.csv.gz  in=372,349,654 out=81,157,278 elapsed=166.6s

  [11430/15692] intraday_5738.csv.gz  in=372,360,572 out=81,157,278 elapsed=166.6s

  [11431/15692] intraday_5737.csv.gz  in=372,373,839 out=81,157,278 elapsed=166.6s

  [11432/15692] intraday_5739.csv.gz  in=372,386,968 out=81,157,278 elapsed=166.6s

  [11433/15692] intraday_5740.csv.gz  in=372,399,361 out=81,157,278 elapsed=166.7s

  [11434/15692] intraday_5741.csv.gz  in=372,412,444 out=81,157,278 elapsed=166.7s

  [11435/15692] intraday_5742.csv.gz  in=372,423,617 out=81,157,278 elapsed=166.7s

  [11436/15692] intraday_5746.csv.gz  in=372,436,492 out=81,157,278 elapsed=166.7s

  [11437/15692] intraday_5743.csv.gz  in=372,450,918 out=81,157,278 elapsed=166.7s

  [11438/15692] intraday_5744.csv.gz  in=372,461,549 out=81,157,278 elapsed=166.7s

  [11439/15692] intraday_5745.csv.gz  in=372,477,387 out=81,157,278 elapsed=166.7s

  [11440/15692] intraday_5747.csv.gz  in=372,490,876 out=81,157,278 elapsed=166.7s

  [11441/15692] intraday_5748.csv.gz  in=372,504,287 out=81,157,278 elapsed=166.7s

  [11442/15692] intraday_5749.csv.gz  in=372,515,752 out=81,157,278 elapsed=166.7s

  [11443/15692] intraday_5750.csv.gz  in=372,527,363 out=81,157,278 elapsed=166.7s

  [11444/15692] intraday_5752.csv.gz  in=372,539,907 out=81,157,278 elapsed=166.7s

  [11445/15692] intraday_5751.csv.gz  in=372,551,866 out=81,157,278 elapsed=166.7s

  [11446/15692] intraday_5754.csv.gz  in=372,562,983 out=81,157,278 elapsed=166.8s

  [11447/15692] intraday_5753.csv.gz  in=372,575,950 out=81,157,278 elapsed=166.8s

  [11448/15692] intraday_5756.csv.gz  in=372,588,690 out=81,157,278 elapsed=166.8s

  [11449/15692] intraday_5755.csv.gz  in=372,600,275 out=81,157,278 elapsed=166.8s

  [11450/15692] intraday_5758.csv.gz  in=372,610,943 out=81,157,278 elapsed=166.8s

  [11451/15692] intraday_5757.csv.gz  in=372,624,040 out=81,157,278 elapsed=166.8s

  [11452/15692] intraday_5759.csv.gz  in=372,637,653 out=81,157,278 elapsed=166.8s

  [11453/15692] intraday_5760.csv.gz  in=372,647,692 out=81,157,278 elapsed=166.8s

  [11454/15692] intraday_5761.csv.gz  in=372,659,754 out=81,157,278 elapsed=166.8s

  [11455/15692] intraday_5762.csv.gz  in=372,672,346 out=81,157,278 elapsed=166.8s

  [11456/15692] intraday_5763.csv.gz  in=372,686,434 out=81,157,278 elapsed=166.8s

  [11457/15692] intraday_5764.csv.gz  in=372,702,134 out=81,157,278 elapsed=166.8s

  [11458/15692] intraday_5765.csv.gz  in=372,715,269 out=81,157,278 elapsed=166.8s

  [11459/15692] intraday_5767.csv.gz  in=372,726,751 out=81,157,278 elapsed=166.9s

  [11460/15692] intraday_5766.csv.gz  in=372,738,240 out=81,157,278 elapsed=166.9s

  [11461/15692] intraday_5769.csv.gz  in=372,754,866 out=81,157,278 elapsed=166.9s

  [11462/15692] intraday_5768.csv.gz  in=372,768,604 out=81,157,278 elapsed=166.9s

  [11463/15692] intraday_5770.csv.gz  in=372,781,246 out=81,157,278 elapsed=166.9s

  [11464/15692] intraday_5771.csv.gz  in=372,797,846 out=81,157,278 elapsed=166.9s

  [11465/15692] intraday_5772.csv.gz  in=372,810,631 out=81,157,278 elapsed=166.9s

  [11466/15692] intraday_5773.csv.gz  in=372,824,111 out=81,157,278 elapsed=166.9s

  [11467/15692] intraday_5775.csv.gz  in=372,836,465 out=81,157,278 elapsed=166.9s

  [11468/15692] intraday_5774.csv.gz  in=372,849,969 out=81,157,278 elapsed=166.9s

  [11469/15692] intraday_5776.csv.gz  in=372,862,083 out=81,157,278 elapsed=166.9s

  [11470/15692] intraday_5779.csv.gz  in=372,875,992 out=81,157,278 elapsed=167.0s

  [11471/15692] intraday_5778.csv.gz  in=372,888,172 out=81,157,278 elapsed=167.0s

  [11472/15692] intraday_5777.csv.gz  in=372,901,142 out=81,157,278 elapsed=167.0s

  [11473/15692] intraday_5780.csv.gz  in=372,912,940 out=81,157,278 elapsed=167.0s

  [11474/15692] intraday_5782.csv.gz  in=372,931,831 out=81,157,278 elapsed=167.0s

  [11475/15692] intraday_5781.csv.gz  in=372,944,938 out=81,157,278 elapsed=167.0s

  [11476/15692] intraday_5783.csv.gz  in=372,957,632 out=81,157,278 elapsed=167.0s

  [11477/15692] intraday_5784.csv.gz  in=372,970,458 out=81,157,278 elapsed=167.0s

  [11478/15692] intraday_5788.csv.gz  in=372,984,971 out=81,157,278 elapsed=167.0s

  [11479/15692] intraday_5785.csv.gz  in=373,000,721 out=81,157,278 elapsed=167.0s

  [11480/15692] intraday_5786.csv.gz  in=373,011,925 out=81,157,278 elapsed=167.0s

  [11481/15692] intraday_5787.csv.gz  in=373,025,685 out=81,157,278 elapsed=167.0s

  [11482/15692] intraday_5792.csv.gz  in=373,039,318 out=81,157,278 elapsed=167.1s

  [11483/15692] intraday_5790.csv.gz  in=373,056,978 out=81,157,278 elapsed=167.1s

  [11484/15692] intraday_5789.csv.gz  in=373,072,544 out=81,157,278 elapsed=167.1s

  [11485/15692] intraday_5791.csv.gz  in=373,084,878 out=81,157,278 elapsed=167.1s

  [11486/15692] intraday_5793.csv.gz  in=373,097,609 out=81,157,278 elapsed=167.1s

  [11487/15692] intraday_5796.csv.gz  in=373,111,587 out=81,157,278 elapsed=167.1s

  [11488/15692] intraday_5795.csv.gz  in=373,126,291 out=81,157,278 elapsed=167.1s

  [11489/15692] intraday_5794.csv.gz  in=373,140,072 out=81,157,278 elapsed=167.1s

  [11490/15692] intraday_5798.csv.gz  in=373,153,659 out=81,157,278 elapsed=167.1s

  [11491/15692] intraday_5797.csv.gz  in=373,168,493 out=81,157,278 elapsed=167.2s

  [11492/15692] intraday_5799.csv.gz  in=373,180,741 out=81,157,278 elapsed=167.2s

  [11493/15692] intraday_5800.csv.gz  in=373,192,918 out=81,157,278 elapsed=167.2s

  [11494/15692] intraday_5802.csv.gz  in=373,204,005 out=81,157,278 elapsed=167.2s

  [11495/15692] intraday_5801.csv.gz  in=373,217,043 out=81,157,278 elapsed=167.2s

  [11496/15692] intraday_5803.csv.gz  in=373,229,988 out=81,157,278 elapsed=167.2s

  [11497/15692] intraday_5804.csv.gz  in=373,242,423 out=81,157,278 elapsed=167.2s

  [11498/15692] intraday_5805.csv.gz  in=373,257,000 out=81,157,278 elapsed=167.2s

  [11499/15692] intraday_5806.csv.gz  in=373,270,704 out=81,157,278 elapsed=167.2s

  [11500/15692] intraday_5807.csv.gz  in=373,282,888 out=81,157,278 elapsed=167.3s

  [11501/15692] intraday_5808.csv.gz  in=373,294,402 out=81,157,278 elapsed=167.3s

  [11502/15692] intraday_5809.csv.gz  in=373,308,112 out=81,157,278 elapsed=167.3s

  [11503/15692] intraday_5810.csv.gz  in=373,319,668 out=81,157,278 elapsed=167.3s

  [11504/15692] intraday_5811.csv.gz  in=373,331,900 out=81,157,278 elapsed=167.3s

  [11505/15692] intraday_5813.csv.gz  in=373,346,107 out=81,157,278 elapsed=167.3s

  [11506/15692] intraday_5812.csv.gz  in=373,361,656 out=81,157,278 elapsed=167.3s

  [11507/15692] intraday_5814.csv.gz  in=373,376,395 out=81,157,278 elapsed=167.3s

  [11508/15692] intraday_5817.csv.gz  in=373,390,193 out=81,157,278 elapsed=167.3s

  [11509/15692] intraday_5815.csv.gz  in=373,402,878 out=81,157,278 elapsed=167.3s

  [11510/15692] intraday_5816.csv.gz  in=373,414,296 out=81,157,278 elapsed=167.4s

  [11511/15692] intraday_5818.csv.gz  in=373,425,213 out=81,157,278 elapsed=167.4s

  [11512/15692] intraday_5820.csv.gz  in=373,432,659 out=81,157,278 elapsed=167.4s

  [11513/15692] intraday_5821.csv.gz  in=373,441,792 out=81,157,278 elapsed=167.4s

  [11514/15692] intraday_5822.csv.gz  in=373,452,062 out=81,157,278 elapsed=167.4s

  [11515/15692] intraday_5819.csv.gz  in=373,466,523 out=81,157,278 elapsed=167.4s

  [11516/15692] intraday_5825.csv.gz  in=373,478,184 out=81,157,278 elapsed=167.4s

  [11517/15692] intraday_5823.csv.gz  in=373,494,220 out=81,157,278 elapsed=167.4s

  [11518/15692] intraday_5826.csv.gz  in=373,504,959 out=81,157,278 elapsed=167.4s

  [11519/15692] intraday_5824.csv.gz  in=373,518,367 out=81,157,278 elapsed=167.4s

  [11520/15692] intraday_5827.csv.gz  in=373,531,842 out=81,157,278 elapsed=167.4s

  [11521/15692] intraday_5828.csv.gz  in=373,547,636 out=81,157,278 elapsed=167.5s

  [11522/15692] intraday_5830.csv.gz  in=373,559,228 out=81,157,278 elapsed=167.5s

  [11523/15692] intraday_5831.csv.gz  in=373,572,581 out=81,157,278 elapsed=167.5s

  [11524/15692] intraday_5829.csv.gz  in=373,586,678 out=81,157,278 elapsed=167.5s

  [11525/15692] intraday_5834.csv.gz  in=373,600,361 out=81,157,278 elapsed=167.5s

  [11526/15692] intraday_5832.csv.gz  in=373,613,832 out=81,157,278 elapsed=167.5s

  [11527/15692] intraday_5835.csv.gz  in=373,625,948 out=81,157,278 elapsed=167.5s

  [11528/15692] intraday_5833.csv.gz  in=373,640,424 out=81,157,278 elapsed=167.5s

  [11529/15692] intraday_5836.csv.gz  in=373,652,397 out=81,157,278 elapsed=167.5s

  [11530/15692] intraday_5837.csv.gz  in=373,662,445 out=81,157,278 elapsed=167.6s

  [11531/15692] intraday_5838.csv.gz  in=373,679,000 out=81,157,278 elapsed=167.6s

  [11532/15692] intraday_5839.csv.gz  in=373,692,995 out=81,157,278 elapsed=167.6s

  [11533/15692] intraday_5840.csv.gz  in=373,706,239 out=81,157,278 elapsed=167.6s

  [11534/15692] intraday_5841.csv.gz  in=373,724,172 out=81,157,278 elapsed=167.6s

  [11535/15692] intraday_5843.csv.gz  in=373,736,558 out=81,157,278 elapsed=167.6s

  [11536/15692] intraday_5842.csv.gz  in=373,747,900 out=81,157,278 elapsed=167.6s

  [11537/15692] intraday_5844.csv.gz  in=373,761,167 out=81,157,278 elapsed=167.6s

  [11538/15692] intraday_5846.csv.gz  in=373,773,323 out=81,157,278 elapsed=167.6s

  [11539/15692] intraday_5848.csv.gz  in=373,784,378 out=81,157,278 elapsed=167.7s

  [11540/15692] intraday_5845.csv.gz  in=373,796,889 out=81,157,278 elapsed=167.7s

  [11541/15692] intraday_5847.csv.gz  in=373,809,761 out=81,157,278 elapsed=167.7s

  [11542/15692] intraday_5849.csv.gz  in=373,821,501 out=81,157,278 elapsed=167.7s

  [11543/15692] intraday_5850.csv.gz  in=373,833,413 out=81,157,278 elapsed=167.7s

  [11544/15692] intraday_5851.csv.gz  in=373,846,551 out=81,157,278 elapsed=167.7s

  [11545/15692] intraday_5852.csv.gz  in=373,860,526 out=81,157,278 elapsed=167.7s

  [11546/15692] intraday_5854.csv.gz  in=373,873,106 out=81,157,278 elapsed=167.7s

  [11547/15692] intraday_5853.csv.gz  in=373,888,255 out=81,157,278 elapsed=167.7s

  [11548/15692] intraday_5856.csv.gz  in=373,900,651 out=81,157,278 elapsed=167.7s

  [11549/15692] intraday_5855.csv.gz  in=373,912,771 out=81,157,278 elapsed=167.8s

  [11550/15692] intraday_5857.csv.gz  in=373,926,859 out=81,157,278 elapsed=167.8s

  [11551/15692] intraday_5859.csv.gz  in=373,939,016 out=81,157,278 elapsed=167.8s

  [11552/15692] intraday_5858.csv.gz  in=373,949,541 out=81,157,278 elapsed=167.8s

  [11553/15692] intraday_5860.csv.gz  in=373,961,110 out=81,157,278 elapsed=167.8s

  [11554/15692] intraday_5861.csv.gz  in=373,971,863 out=81,157,278 elapsed=167.8s

  [11555/15692] intraday_5862.csv.gz  in=373,982,911 out=81,157,278 elapsed=167.8s

  [11556/15692] intraday_5865.csv.gz  in=373,995,670 out=81,157,278 elapsed=167.8s

  [11557/15692] intraday_5864.csv.gz  in=374,007,568 out=81,157,278 elapsed=167.8s

  [11558/15692] intraday_5863.csv.gz  in=374,020,315 out=81,157,278 elapsed=167.8s

  [11559/15692] intraday_5866.csv.gz  in=374,033,778 out=81,157,278 elapsed=167.9s

  [11560/15692] intraday_5867.csv.gz  in=374,046,266 out=81,157,278 elapsed=167.9s

  [11561/15692] intraday_5869.csv.gz  in=374,056,962 out=81,157,278 elapsed=167.9s

  [11562/15692] intraday_5868.csv.gz  in=374,069,183 out=81,157,278 elapsed=167.9s

  [11563/15692] intraday_5871.csv.gz  in=374,080,705 out=81,157,278 elapsed=167.9s

  [11564/15692] intraday_5872.csv.gz  in=374,091,726 out=81,157,278 elapsed=167.9s

  [11565/15692] intraday_5870.csv.gz  in=374,103,279 out=81,157,278 elapsed=167.9s

  [11566/15692] intraday_5873.csv.gz  in=374,114,294 out=81,157,278 elapsed=167.9s

  [11567/15692] intraday_5874.csv.gz  in=374,128,783 out=81,157,278 elapsed=167.9s

  [11568/15692] intraday_5875.csv.gz  in=374,139,226 out=81,157,278 elapsed=167.9s

  [11569/15692] intraday_5876.csv.gz  in=374,149,983 out=81,157,278 elapsed=167.9s

  [11570/15692] intraday_5877.csv.gz  in=374,164,435 out=81,157,278 elapsed=168.0s

  [11571/15692] intraday_5878.csv.gz  in=374,177,318 out=81,157,278 elapsed=168.0s

  [11572/15692] intraday_5881.csv.gz  in=374,189,975 out=81,157,278 elapsed=168.0s

  [11573/15692] intraday_5880.csv.gz  in=374,201,736 out=81,157,278 elapsed=168.0s

  [11574/15692] intraday_5879.csv.gz  in=374,214,724 out=81,157,278 elapsed=168.0s

  [11575/15692] intraday_5882.csv.gz  in=374,227,304 out=81,157,278 elapsed=168.0s

  [11576/15692] intraday_5883.csv.gz  in=374,241,067 out=81,157,278 elapsed=168.0s

  [11577/15692] intraday_5884.csv.gz  in=374,252,309 out=81,157,278 elapsed=168.0s

  [11578/15692] intraday_5885.csv.gz  in=374,262,653 out=81,157,278 elapsed=168.0s

  [11579/15692] intraday_5886.csv.gz  in=374,274,010 out=81,157,278 elapsed=168.0s

  [11580/15692] intraday_5888.csv.gz  in=374,287,374 out=81,157,278 elapsed=168.1s

  [11581/15692] intraday_5890.csv.gz  in=374,299,860 out=81,157,278 elapsed=168.1s

  [11582/15692] intraday_5887.csv.gz  in=374,315,428 out=81,157,278 elapsed=168.1s

  [11583/15692] intraday_5889.csv.gz  in=374,328,875 out=81,157,278 elapsed=168.1s

  [11584/15692] intraday_5894.csv.gz  in=374,340,752 out=81,157,278 elapsed=168.1s

  [11585/15692] intraday_5891.csv.gz  in=374,369,267 out=81,157,278 elapsed=168.1s

  [11586/15692] intraday_5892.csv.gz  in=374,388,995 out=81,157,278 elapsed=168.1s

  [11587/15692] intraday_5893.csv.gz  in=374,400,598 out=81,157,278 elapsed=168.1s

  [11588/15692] intraday_5897.csv.gz  in=374,412,300 out=81,157,278 elapsed=168.1s

  [11589/15692] intraday_5896.csv.gz  in=374,425,045 out=81,157,278 elapsed=168.2s

  [11590/15692] intraday_5898.csv.gz  in=374,435,490 out=81,157,278 elapsed=168.2s

  [11591/15692] intraday_5895.csv.gz  in=374,449,065 out=81,157,278 elapsed=168.2s

  [11592/15692] intraday_5900.csv.gz  in=374,460,121 out=81,157,278 elapsed=168.2s

  [11593/15692] intraday_5899.csv.gz  in=374,473,845 out=81,157,278 elapsed=168.2s

  [11594/15692] intraday_5902.csv.gz  in=374,483,188 out=81,157,278 elapsed=168.2s

  [11595/15692] intraday_5901.csv.gz  in=374,505,615 out=81,157,278 elapsed=168.2s

  [11596/15692] intraday_5903.csv.gz  in=374,517,404 out=81,157,278 elapsed=168.2s

  [11597/15692] intraday_5904.csv.gz  in=374,529,922 out=81,157,278 elapsed=168.2s

  [11598/15692] intraday_5905.csv.gz  in=374,544,684 out=81,157,278 elapsed=168.2s

  [11599/15692] intraday_5906.csv.gz  in=374,559,451 out=81,157,278 elapsed=168.2s

  [11600/15692] intraday_5907.csv.gz  in=374,573,477 out=81,157,278 elapsed=168.2s

  [11601/15692] intraday_5909.csv.gz  in=374,585,804 out=81,157,278 elapsed=168.3s

  [11602/15692] intraday_5908.csv.gz  in=374,597,225 out=81,157,278 elapsed=168.3s

  [11603/15692] intraday_5910.csv.gz  in=374,610,764 out=81,157,278 elapsed=168.3s

  [11604/15692] intraday_5911.csv.gz  in=374,627,182 out=81,157,278 elapsed=168.3s

  [11605/15692] intraday_5913.csv.gz  in=374,640,340 out=81,157,278 elapsed=168.3s

  [11606/15692] intraday_5914.csv.gz  in=374,653,529 out=81,157,278 elapsed=168.3s

  [11607/15692] intraday_5912.csv.gz  in=374,666,645 out=81,157,278 elapsed=168.3s

  [11608/15692] intraday_5915.csv.gz  in=374,681,162 out=81,157,278 elapsed=168.3s

  [11609/15692] intraday_5916.csv.gz  in=374,694,663 out=81,157,278 elapsed=168.3s

  [11610/15692] intraday_5917.csv.gz  in=374,709,856 out=81,157,278 elapsed=168.3s

  [11611/15692] intraday_5918.csv.gz  in=374,722,308 out=81,157,278 elapsed=168.3s

  [11612/15692] intraday_5919.csv.gz  in=374,735,252 out=81,157,278 elapsed=168.3s

  [11613/15692] intraday_5920.csv.gz  in=374,747,224 out=81,157,278 elapsed=168.3s

  [11614/15692] intraday_5921.csv.gz  in=374,761,768 out=81,157,278 elapsed=168.4s

  [11615/15692] intraday_5922.csv.gz  in=374,773,947 out=81,157,278 elapsed=168.4s

  [11616/15692] intraday_5924.csv.gz  in=374,787,067 out=81,157,278 elapsed=168.4s

  [11617/15692] intraday_5923.csv.gz  in=374,801,281 out=81,157,278 elapsed=168.4s

  [11618/15692] intraday_5925.csv.gz  in=374,814,789 out=81,157,278 elapsed=168.4s

  [11619/15692] intraday_5926.csv.gz  in=374,831,984 out=81,157,278 elapsed=168.4s

  [11620/15692] intraday_5927.csv.gz  in=374,846,620 out=81,157,278 elapsed=168.4s

  [11621/15692] intraday_5928.csv.gz  in=374,860,254 out=81,157,278 elapsed=168.4s

  [11622/15692] intraday_5929.csv.gz  in=374,872,870 out=81,157,278 elapsed=168.5s

  [11623/15692] intraday_5931.csv.gz  in=374,890,289 out=81,157,278 elapsed=168.5s

  [11624/15692] intraday_5930.csv.gz  in=374,903,893 out=81,157,278 elapsed=168.5s

  [11625/15692] intraday_5933.csv.gz  in=374,916,004 out=81,157,278 elapsed=168.5s

  [11626/15692] intraday_5935.csv.gz  in=374,928,115 out=81,157,278 elapsed=168.5s

  [11627/15692] intraday_5932.csv.gz  in=374,939,892 out=81,157,278 elapsed=168.5s

  [11628/15692] intraday_5934.csv.gz  in=374,953,277 out=81,157,278 elapsed=168.5s

  [11629/15692] intraday_5936.csv.gz  in=374,967,224 out=81,157,278 elapsed=168.8s

  [11630/15692] intraday_5937.csv.gz  in=374,981,670 out=81,157,278 elapsed=168.8s

  [11631/15692] intraday_5939.csv.gz  in=374,996,618 out=81,157,278 elapsed=168.8s

  [11632/15692] intraday_5938.csv.gz  in=375,010,987 out=81,157,278 elapsed=168.8s

  [11633/15692] intraday_5940.csv.gz  in=375,025,354 out=81,157,278 elapsed=168.8s

  [11634/15692] intraday_5941.csv.gz  in=375,037,117 out=81,157,278 elapsed=168.9s

  [11635/15692] intraday_5942.csv.gz  in=375,049,990 out=81,157,278 elapsed=168.9s

  [11636/15692] intraday_5944.csv.gz  in=375,061,911 out=81,157,278 elapsed=168.9s

  [11637/15692] intraday_5943.csv.gz  in=375,073,819 out=81,157,278 elapsed=168.9s

  [11638/15692] intraday_5945.csv.gz  in=375,085,868 out=81,157,278 elapsed=168.9s

  [11639/15692] intraday_5946.csv.gz  in=375,098,381 out=81,157,278 elapsed=168.9s

  [11640/15692] intraday_5947.csv.gz  in=375,111,886 out=81,157,278 elapsed=168.9s

  [11641/15692] intraday_5948.csv.gz  in=375,127,682 out=81,157,278 elapsed=168.9s

  [11642/15692] intraday_5949.csv.gz  in=375,139,063 out=81,157,278 elapsed=168.9s

  [11643/15692] intraday_5950.csv.gz  in=375,150,849 out=81,157,278 elapsed=168.9s

  [11644/15692] intraday_5952.csv.gz  in=375,163,353 out=81,157,278 elapsed=169.0s

  [11645/15692] intraday_5951.csv.gz  in=375,177,254 out=81,157,278 elapsed=169.0s

  [11646/15692] intraday_5953.csv.gz  in=375,189,608 out=81,157,278 elapsed=169.0s

  [11647/15692] intraday_5955.csv.gz  in=375,203,321 out=81,157,278 elapsed=169.0s

  [11648/15692] intraday_5954.csv.gz  in=375,220,356 out=81,157,278 elapsed=169.0s

  [11649/15692] intraday_5956.csv.gz  in=375,234,327 out=81,157,278 elapsed=169.0s

  [11650/15692] intraday_5957.csv.gz  in=375,246,774 out=81,157,278 elapsed=169.0s

  [11651/15692] intraday_5958.csv.gz  in=375,258,786 out=81,157,278 elapsed=169.0s

  [11652/15692] intraday_5960.csv.gz  in=375,269,729 out=81,157,278 elapsed=169.0s

  [11653/15692] intraday_5959.csv.gz  in=375,284,181 out=81,157,278 elapsed=169.0s

  [11654/15692] intraday_5961.csv.gz  in=375,298,192 out=81,157,278 elapsed=169.1s

  [11655/15692] intraday_5962.csv.gz  in=375,307,060 out=81,157,278 elapsed=169.1s

  [11656/15692] intraday_5963.csv.gz  in=375,315,497 out=81,157,278 elapsed=169.1s

  [11657/15692] intraday_5964.csv.gz  in=375,326,311 out=81,157,278 elapsed=169.1s

  [11658/15692] intraday_5967.csv.gz  in=375,339,830 out=81,157,278 elapsed=169.1s

  [11659/15692] intraday_5966.csv.gz  in=375,358,482 out=81,157,278 elapsed=169.1s

  [11660/15692] intraday_5965.csv.gz  in=375,373,819 out=81,157,278 elapsed=169.1s

  [11661/15692] intraday_5968.csv.gz  in=375,383,929 out=81,157,278 elapsed=169.1s

  [11662/15692] intraday_5969.csv.gz  in=375,397,102 out=81,157,278 elapsed=169.1s

  [11663/15692] intraday_5970.csv.gz  in=375,411,314 out=81,157,278 elapsed=169.1s

  [11664/15692] intraday_5972.csv.gz  in=375,421,602 out=81,157,278 elapsed=169.1s

  [11665/15692] intraday_5971.csv.gz  in=375,436,152 out=81,157,278 elapsed=169.1s

  [11666/15692] intraday_5973.csv.gz  in=375,449,092 out=81,157,278 elapsed=169.2s

  [11667/15692] intraday_5974.csv.gz  in=375,463,549 out=81,157,278 elapsed=169.2s

  [11668/15692] intraday_5976.csv.gz  in=375,476,152 out=81,157,278 elapsed=169.2s

  [11669/15692] intraday_5975.csv.gz  in=375,490,228 out=81,157,278 elapsed=169.2s

  [11670/15692] intraday_5978.csv.gz  in=375,502,329 out=81,157,278 elapsed=169.2s

  [11671/15692] intraday_5977.csv.gz  in=375,517,286 out=81,157,278 elapsed=169.2s

  [11672/15692] intraday_5979.csv.gz  in=375,528,181 out=81,157,278 elapsed=169.2s

  [11673/15692] intraday_5981.csv.gz  in=375,542,236 out=81,157,278 elapsed=169.2s

  [11674/15692] intraday_5980.csv.gz  in=375,551,172 out=81,157,278 elapsed=169.2s

  [11675/15692] intraday_5982.csv.gz  in=375,563,953 out=81,157,278 elapsed=169.3s

  [11676/15692] intraday_5985.csv.gz  in=375,576,790 out=81,157,278 elapsed=169.3s

  [11677/15692] intraday_5983.csv.gz  in=375,586,877 out=81,157,278 elapsed=169.3s

  [11678/15692] intraday_5984.csv.gz  in=375,605,557 out=81,157,278 elapsed=169.3s

  [11679/15692] intraday_5987.csv.gz  in=375,621,424 out=81,157,278 elapsed=169.3s

  [11680/15692] intraday_5986.csv.gz  in=375,634,757 out=81,157,278 elapsed=169.3s

  [11681/15692] intraday_5988.csv.gz  in=375,647,685 out=81,157,278 elapsed=169.3s

  [11682/15692] intraday_5989.csv.gz  in=375,659,677 out=81,157,278 elapsed=169.3s

  [11683/15692] intraday_5990.csv.gz  in=375,671,318 out=81,157,278 elapsed=169.3s

  [11684/15692] intraday_5991.csv.gz  in=375,682,189 out=81,157,278 elapsed=169.4s

  [11685/15692] intraday_5992.csv.gz  in=375,694,484 out=81,157,278 elapsed=169.4s

  [11686/15692] intraday_5994.csv.gz  in=375,706,249 out=81,157,278 elapsed=169.4s

  [11687/15692] intraday_5993.csv.gz  in=375,718,270 out=81,157,278 elapsed=169.4s

  [11688/15692] intraday_5997.csv.gz  in=375,729,192 out=81,157,278 elapsed=169.4s

  [11689/15692] intraday_5998.csv.gz  in=375,741,607 out=81,157,278 elapsed=169.4s

  [11690/15692] intraday_5996.csv.gz  in=375,753,549 out=81,157,278 elapsed=169.4s

  [11691/15692] intraday_5995.csv.gz  in=375,769,382 out=81,157,278 elapsed=169.4s

  [11692/15692] intraday_6000.csv.gz  in=375,780,070 out=81,157,278 elapsed=169.4s

  [11693/15692] intraday_6002.csv.gz  in=375,789,161 out=81,157,278 elapsed=169.4s

  [11694/15692] intraday_5999.csv.gz  in=375,801,839 out=81,157,278 elapsed=169.4s

  [11695/15692] intraday_6001.csv.gz  in=375,825,189 out=81,157,278 elapsed=169.4s

  [11696/15692] intraday_6004.csv.gz  in=375,835,043 out=81,157,278 elapsed=169.5s

  [11697/15692] intraday_6005.csv.gz  in=375,846,282 out=81,157,278 elapsed=169.5s

  [11698/15692] intraday_6003.csv.gz  in=375,858,110 out=81,157,278 elapsed=169.5s

  [11699/15692] intraday_6006.csv.gz  in=375,871,143 out=81,157,278 elapsed=169.5s

  [11700/15692] intraday_6007.csv.gz  in=375,882,972 out=81,157,278 elapsed=169.5s

  [11701/15692] intraday_6008.csv.gz  in=375,896,816 out=81,157,278 elapsed=169.5s

  [11702/15692] intraday_6009.csv.gz  in=375,916,054 out=81,157,278 elapsed=169.5s

  [11703/15692] intraday_6010.csv.gz  in=375,926,648 out=81,157,278 elapsed=169.5s

  [11704/15692] intraday_6012.csv.gz  in=375,940,077 out=81,157,278 elapsed=169.5s

  [11705/15692] intraday_6013.csv.gz  in=375,953,279 out=81,157,278 elapsed=169.5s

  [11706/15692] intraday_6011.csv.gz  in=375,965,409 out=81,157,278 elapsed=169.5s

  [11707/15692] intraday_6014.csv.gz  in=375,978,080 out=81,157,278 elapsed=169.6s

  [11708/15692] intraday_6015.csv.gz  in=375,989,666 out=81,157,278 elapsed=169.6s

  [11709/15692] intraday_6016.csv.gz  in=376,002,484 out=81,157,278 elapsed=169.6s

  [11710/15692] intraday_6017.csv.gz  in=376,014,903 out=81,157,278 elapsed=169.6s

  [11711/15692] intraday_6018.csv.gz  in=376,026,467 out=81,157,278 elapsed=169.6s

  [11712/15692] intraday_6019.csv.gz  in=376,039,193 out=81,157,278 elapsed=169.6s

  [11713/15692] intraday_6021.csv.gz  in=376,051,487 out=81,157,278 elapsed=169.6s

  [11714/15692] intraday_6020.csv.gz  in=376,064,084 out=81,157,278 elapsed=169.6s

  [11715/15692] intraday_6022.csv.gz  in=376,077,251 out=81,157,278 elapsed=169.6s

  [11716/15692] intraday_6024.csv.gz  in=376,089,687 out=81,157,278 elapsed=169.7s

  [11717/15692] intraday_6025.csv.gz  in=376,101,447 out=81,157,278 elapsed=169.7s

  [11718/15692] intraday_6026.csv.gz  in=376,114,494 out=81,157,278 elapsed=169.7s

  [11719/15692] intraday_6023.csv.gz  in=376,140,363 out=81,157,278 elapsed=169.7s

  [11720/15692] intraday_6027.csv.gz  in=376,152,931 out=81,157,278 elapsed=169.7s

  [11721/15692] intraday_6028.csv.gz  in=376,162,384 out=81,157,278 elapsed=169.7s

  [11722/15692] intraday_6029.csv.gz  in=376,176,869 out=81,157,278 elapsed=169.7s

  [11723/15692] intraday_6031.csv.gz  in=376,186,744 out=81,157,278 elapsed=169.7s

  [11724/15692] intraday_6030.csv.gz  in=376,202,803 out=81,157,278 elapsed=169.7s

  [11725/15692] intraday_6032.csv.gz  in=376,215,375 out=81,157,278 elapsed=169.7s

  [11726/15692] intraday_6033.csv.gz  in=376,227,772 out=81,157,278 elapsed=169.8s

  [11727/15692] intraday_6034.csv.gz  in=376,238,420 out=81,157,278 elapsed=169.8s

  [11728/15692] intraday_6035.csv.gz  in=376,250,234 out=81,157,278 elapsed=169.8s

  [11729/15692] intraday_6036.csv.gz  in=376,261,321 out=81,157,278 elapsed=169.8s

  [11730/15692] intraday_6037.csv.gz  in=376,274,944 out=81,157,278 elapsed=169.8s

  [11731/15692] intraday_6038.csv.gz  in=376,286,829 out=81,157,278 elapsed=169.8s

  [11732/15692] intraday_6039.csv.gz  in=376,299,907 out=81,157,278 elapsed=169.8s

  [11733/15692] intraday_6040.csv.gz  in=376,309,109 out=81,157,278 elapsed=169.8s

  [11734/15692] intraday_6041.csv.gz  in=376,321,544 out=81,157,278 elapsed=169.8s

  [11735/15692] intraday_6044.csv.gz  in=376,333,366 out=81,157,278 elapsed=169.8s

  [11736/15692] intraday_6045.csv.gz  in=376,342,457 out=81,157,278 elapsed=169.8s

  [11737/15692] intraday_6043.csv.gz  in=376,352,813 out=81,157,278 elapsed=169.9s

  [11738/15692] intraday_6042.csv.gz  in=376,364,746 out=81,157,278 elapsed=169.9s

  [11739/15692] intraday_6047.csv.gz  in=376,378,841 out=81,157,278 elapsed=169.9s

  [11740/15692] intraday_6046.csv.gz  in=376,389,394 out=81,157,278 elapsed=169.9s

  [11741/15692] intraday_6050.csv.gz  in=376,401,512 out=81,157,278 elapsed=169.9s

  [11742/15692] intraday_6048.csv.gz  in=376,419,097 out=81,157,278 elapsed=169.9s

  [11743/15692] intraday_6051.csv.gz  in=376,429,409 out=81,157,278 elapsed=169.9s

  [11744/15692] intraday_6049.csv.gz  in=376,440,915 out=81,157,278 elapsed=169.9s

  [11745/15692] intraday_6052.csv.gz  in=376,456,540 out=81,157,278 elapsed=170.0s

  [11746/15692] intraday_6053.csv.gz  in=376,467,802 out=81,157,278 elapsed=170.0s

  [11747/15692] intraday_6054.csv.gz  in=376,483,583 out=81,157,278 elapsed=170.0s

  [11748/15692] intraday_6055.csv.gz  in=376,495,346 out=81,157,278 elapsed=170.0s

  [11749/15692] intraday_6056.csv.gz  in=376,508,048 out=81,157,278 elapsed=170.0s

  [11750/15692] intraday_6059.csv.gz  in=376,520,100 out=81,157,278 elapsed=170.0s

  [11751/15692] intraday_6057.csv.gz  in=376,533,285 out=81,157,278 elapsed=170.0s

  [11752/15692] intraday_6058.csv.gz  in=376,554,200 out=81,157,278 elapsed=170.0s

  [11753/15692] intraday_6061.csv.gz  in=376,567,361 out=81,157,278 elapsed=170.0s

  [11754/15692] intraday_6060.csv.gz  in=376,580,088 out=81,157,278 elapsed=170.0s

  [11755/15692] intraday_6062.csv.gz  in=376,591,753 out=81,157,278 elapsed=170.1s

  [11756/15692] intraday_6063.csv.gz  in=376,605,151 out=81,157,278 elapsed=170.1s

  [11757/15692] intraday_6064.csv.gz  in=376,617,925 out=81,157,278 elapsed=170.1s

  [11758/15692] intraday_6065.csv.gz  in=376,630,722 out=81,157,278 elapsed=170.1s

  [11759/15692] intraday_6066.csv.gz  in=376,645,773 out=81,157,278 elapsed=170.1s

  [11760/15692] intraday_6067.csv.gz  in=376,661,595 out=81,157,278 elapsed=170.1s

  [11761/15692] intraday_6068.csv.gz  in=376,671,982 out=81,157,278 elapsed=170.1s

  [11762/15692] intraday_6069.csv.gz  in=376,684,042 out=81,157,278 elapsed=170.1s

  [11763/15692] intraday_6070.csv.gz  in=376,702,435 out=81,157,278 elapsed=170.1s

  [11764/15692] intraday_6071.csv.gz  in=376,712,379 out=81,157,278 elapsed=170.1s

  [11765/15692] intraday_6072.csv.gz  in=376,723,512 out=81,157,278 elapsed=170.1s

  [11766/15692] intraday_6074.csv.gz  in=376,736,888 out=81,157,278 elapsed=170.2s

  [11767/15692] intraday_6073.csv.gz  in=376,752,429 out=81,157,278 elapsed=170.2s

  [11768/15692] intraday_6075.csv.gz  in=376,765,761 out=81,157,278 elapsed=170.2s

  [11769/15692] intraday_6076.csv.gz  in=376,778,371 out=81,157,278 elapsed=170.2s

  [11770/15692] intraday_6077.csv.gz  in=376,790,531 out=81,157,278 elapsed=170.2s

  [11771/15692] intraday_6078.csv.gz  in=376,802,795 out=81,157,278 elapsed=170.2s

  [11772/15692] intraday_6080.csv.gz  in=376,814,491 out=81,157,278 elapsed=170.2s

  [11773/15692] intraday_6079.csv.gz  in=376,829,207 out=81,157,278 elapsed=170.2s

  [11774/15692] intraday_6081.csv.gz  in=376,843,234 out=81,157,278 elapsed=170.2s

  [11775/15692] intraday_6084.csv.gz  in=376,854,296 out=81,157,278 elapsed=170.2s

  [11776/15692] intraday_6083.csv.gz  in=376,866,912 out=81,157,278 elapsed=170.3s

  [11777/15692] intraday_6082.csv.gz  in=376,882,835 out=81,157,278 elapsed=170.3s

  [11778/15692] intraday_6085.csv.gz  in=376,894,215 out=81,157,278 elapsed=170.3s

  [11779/15692] intraday_6087.csv.gz  in=376,905,345 out=81,157,278 elapsed=170.3s

  [11780/15692] intraday_6086.csv.gz  in=376,918,804 out=81,157,278 elapsed=170.3s

  [11781/15692] intraday_6089.csv.gz  in=376,936,809 out=81,157,278 elapsed=170.3s

  [11782/15692] intraday_6088.csv.gz  in=376,950,233 out=81,157,278 elapsed=170.3s

  [11783/15692] intraday_6090.csv.gz  in=376,965,975 out=81,157,278 elapsed=170.3s

  [11784/15692] intraday_6091.csv.gz  in=376,978,515 out=81,157,278 elapsed=170.3s

  [11785/15692] intraday_6093.csv.gz  in=376,990,609 out=81,157,278 elapsed=170.3s

  [11786/15692] intraday_6092.csv.gz  in=377,002,143 out=81,157,278 elapsed=170.3s

  [11787/15692] intraday_6094.csv.gz  in=377,013,774 out=81,157,278 elapsed=170.4s

  [11788/15692] intraday_6095.csv.gz  in=377,026,100 out=81,157,278 elapsed=170.4s

  [11789/15692] intraday_6096.csv.gz  in=377,038,250 out=81,157,278 elapsed=170.4s

  [11790/15692] intraday_6097.csv.gz  in=377,057,035 out=81,157,278 elapsed=170.4s

  [11791/15692] intraday_6098.csv.gz  in=377,071,020 out=81,157,278 elapsed=170.4s

  [11792/15692] intraday_6099.csv.gz  in=377,083,980 out=81,157,278 elapsed=170.4s

  [11793/15692] intraday_6100.csv.gz  in=377,096,178 out=81,157,278 elapsed=170.4s

  [11794/15692] intraday_6102.csv.gz  in=377,109,564 out=81,157,278 elapsed=170.4s

  [11795/15692] intraday_6103.csv.gz  in=377,120,601 out=81,157,278 elapsed=170.4s

  [11796/15692] intraday_6101.csv.gz  in=377,132,399 out=81,157,278 elapsed=170.4s

  [11797/15692] intraday_6104.csv.gz  in=377,146,993 out=81,157,278 elapsed=170.4s

  [11798/15692] intraday_6105.csv.gz  in=377,155,326 out=81,157,278 elapsed=170.5s

  [11799/15692] intraday_6106.csv.gz  in=377,164,560 out=81,157,278 elapsed=170.5s

  [11800/15692] intraday_6107.csv.gz  in=377,173,468 out=81,157,278 elapsed=170.5s

  [11801/15692] intraday_6109.csv.gz  in=377,173,488 out=81,157,278 elapsed=170.5s

  [11802/15692] intraday_6108.csv.gz  in=377,173,566 out=81,157,278 elapsed=170.5s

  [11803/15692] intraday_6110.csv.gz  in=377,173,583 out=81,157,278 elapsed=170.5s

  [11804/15692] intraday_6111.csv.gz  in=377,173,598 out=81,157,278 elapsed=170.5s

  [11805/15692] intraday_6113.csv.gz  in=377,177,228 out=81,157,278 elapsed=170.5s

  [11806/15692] intraday_6112.csv.gz  in=377,180,410 out=81,157,278 elapsed=170.5s

  [11807/15692] intraday_6114.csv.gz  in=377,192,749 out=81,157,278 elapsed=170.5s

  [11808/15692] intraday_6115.csv.gz  in=377,198,241 out=81,157,278 elapsed=170.5s

  [11809/15692] intraday_6116.csv.gz  in=377,199,588 out=81,157,278 elapsed=170.6s

  [11810/15692] intraday_6117.csv.gz  in=377,200,527 out=81,157,278 elapsed=170.6s

  [11811/15692] intraday_6118.csv.gz  in=377,201,796 out=81,157,278 elapsed=170.6s

  [11812/15692] intraday_6121.csv.gz  in=377,202,117 out=81,157,278 elapsed=170.6s

  [11813/15692] intraday_6119.csv.gz  in=377,210,209 out=81,157,278 elapsed=170.6s

  [11814/15692] intraday_6120.csv.gz  in=377,211,564 out=81,157,278 elapsed=170.6s

  [11815/15692] intraday_6122.csv.gz  in=377,211,605 out=81,157,278 elapsed=170.6s

  [11816/15692] intraday_6124.csv.gz  in=377,211,626 out=81,157,278 elapsed=170.6s

  [11817/15692] intraday_6125.csv.gz  in=377,212,176 out=81,157,278 elapsed=170.6s

  [11818/15692] intraday_6123.csv.gz  in=377,214,524 out=81,157,278 elapsed=170.6s

  [11819/15692] intraday_6126.csv.gz  in=377,214,638 out=81,157,278 elapsed=170.6s

  [11820/15692] intraday_6127.csv.gz  in=377,223,867 out=81,157,278 elapsed=170.6s

  [11821/15692] intraday_6128.csv.gz  in=377,240,501 out=81,157,278 elapsed=170.7s

  [11822/15692] intraday_6129.csv.gz  in=377,253,318 out=81,157,278 elapsed=170.7s

  [11823/15692] intraday_6131.csv.gz  in=377,264,743 out=81,157,278 elapsed=170.7s

  [11824/15692] intraday_6130.csv.gz  in=377,279,084 out=81,157,278 elapsed=170.7s

  [11825/15692] intraday_6132.csv.gz  in=377,292,114 out=81,157,278 elapsed=170.7s

  [11826/15692] intraday_6135.csv.gz  in=377,303,432 out=81,157,278 elapsed=170.7s

  [11827/15692] intraday_6134.csv.gz  in=377,320,371 out=81,157,278 elapsed=170.7s

  [11828/15692] intraday_6133.csv.gz  in=377,335,556 out=81,157,278 elapsed=170.7s

  [11829/15692] intraday_6136.csv.gz  in=377,349,628 out=81,157,278 elapsed=170.7s

  [11830/15692] intraday_6139.csv.gz  in=377,363,032 out=81,157,278 elapsed=170.7s

  [11831/15692] intraday_6137.csv.gz  in=377,378,973 out=81,157,278 elapsed=170.7s

  [11832/15692] intraday_6138.csv.gz  in=377,393,831 out=81,157,278 elapsed=170.7s

  [11833/15692] intraday_6140.csv.gz  in=377,406,669 out=81,157,278 elapsed=170.7s

  [11834/15692] intraday_6142.csv.gz  in=377,416,753 out=81,157,278 elapsed=170.7s

  [11835/15692] intraday_6141.csv.gz  in=377,429,255 out=81,157,278 elapsed=170.8s

  [11836/15692] intraday_6143.csv.gz  in=377,438,212 out=81,157,278 elapsed=170.8s

  [11837/15692] intraday_6144.csv.gz  in=377,452,656 out=81,157,278 elapsed=170.8s

  [11838/15692] intraday_6145.csv.gz  in=377,466,680 out=81,157,278 elapsed=170.8s

  [11839/15692] intraday_6146.csv.gz  in=377,477,765 out=81,157,278 elapsed=170.8s

  [11840/15692] intraday_6147.csv.gz  in=377,490,087 out=81,157,278 elapsed=170.8s

  [11841/15692] intraday_6149.csv.gz  in=377,503,555 out=81,157,278 elapsed=170.8s

  [11842/15692] intraday_6148.csv.gz  in=377,531,962 out=81,157,278 elapsed=170.8s

  [11843/15692] intraday_6151.csv.gz  in=377,545,289 out=81,157,278 elapsed=170.8s

  [11844/15692] intraday_6150.csv.gz  in=377,558,910 out=81,157,278 elapsed=170.8s

  [11845/15692] intraday_6152.csv.gz  in=377,571,779 out=81,157,278 elapsed=170.8s

  [11846/15692] intraday_6155.csv.gz  in=377,584,142 out=81,157,278 elapsed=170.8s

  [11847/15692] intraday_6153.csv.gz  in=377,595,944 out=81,157,278 elapsed=170.9s

  [11848/15692] intraday_6154.csv.gz  in=377,606,766 out=81,157,278 elapsed=170.9s

  [11849/15692] intraday_6156.csv.gz  in=377,620,958 out=81,157,278 elapsed=170.9s

  [11850/15692] intraday_6157.csv.gz  in=377,636,409 out=81,157,278 elapsed=170.9s

  [11851/15692] intraday_6159.csv.gz  in=377,647,726 out=81,157,278 elapsed=170.9s

  [11852/15692] intraday_6158.csv.gz  in=377,663,055 out=81,157,278 elapsed=170.9s

  [11853/15692] intraday_6161.csv.gz  in=377,675,812 out=81,157,278 elapsed=170.9s

  [11854/15692] intraday_6160.csv.gz  in=377,687,597 out=81,157,278 elapsed=170.9s

  [11855/15692] intraday_6163.csv.gz  in=377,698,970 out=81,157,278 elapsed=170.9s

  [11856/15692] intraday_6162.csv.gz  in=377,713,806 out=81,157,278 elapsed=170.9s

  [11857/15692] intraday_6164.csv.gz  in=377,726,693 out=81,157,278 elapsed=170.9s

  [11858/15692] intraday_6165.csv.gz  in=377,737,558 out=81,157,278 elapsed=170.9s

  [11859/15692] intraday_6166.csv.gz  in=377,749,396 out=81,157,278 elapsed=171.0s

  [11860/15692] intraday_6167.csv.gz  in=377,760,165 out=81,157,278 elapsed=171.0s

  [11861/15692] intraday_6168.csv.gz  in=377,772,438 out=81,157,278 elapsed=171.0s

  [11862/15692] intraday_6169.csv.gz  in=377,785,641 out=81,157,278 elapsed=171.0s

  [11863/15692] intraday_6170.csv.gz  in=377,797,972 out=81,157,278 elapsed=171.0s

  [11864/15692] intraday_6171.csv.gz  in=377,811,483 out=81,157,278 elapsed=171.0s

  [11865/15692] intraday_6172.csv.gz  in=377,824,484 out=81,157,278 elapsed=171.0s

  [11866/15692] intraday_6173.csv.gz  in=377,836,346 out=81,157,278 elapsed=171.0s

  [11867/15692] intraday_6174.csv.gz  in=377,849,088 out=81,157,278 elapsed=171.0s

  [11868/15692] intraday_6175.csv.gz  in=377,861,770 out=81,157,278 elapsed=171.0s

  [11869/15692] intraday_6176.csv.gz  in=377,872,538 out=81,157,278 elapsed=171.0s

  [11870/15692] intraday_6178.csv.gz  in=377,884,452 out=81,157,278 elapsed=171.0s

  [11871/15692] intraday_6177.csv.gz  in=377,896,935 out=81,157,278 elapsed=171.0s

  [11872/15692] intraday_6179.csv.gz  in=377,910,544 out=81,157,278 elapsed=171.0s

  [11873/15692] intraday_6180.csv.gz  in=377,924,001 out=81,157,278 elapsed=171.1s

  [11874/15692] intraday_6181.csv.gz  in=377,935,781 out=81,157,278 elapsed=171.1s

  [11875/15692] intraday_6183.csv.gz  in=377,948,745 out=81,157,278 elapsed=171.1s

  [11876/15692] intraday_6184.csv.gz  in=377,961,509 out=81,157,278 elapsed=171.1s

  [11877/15692] intraday_6182.csv.gz  in=377,975,958 out=81,157,278 elapsed=171.1s

  [11878/15692] intraday_6185.csv.gz  in=377,989,244 out=81,157,278 elapsed=171.1s

  [11879/15692] intraday_6186.csv.gz  in=378,003,513 out=81,157,278 elapsed=171.1s

  [11880/15692] intraday_6187.csv.gz  in=378,017,326 out=81,157,278 elapsed=171.1s

  [11881/15692] intraday_6188.csv.gz  in=378,029,634 out=81,157,278 elapsed=171.1s

  [11882/15692] intraday_6189.csv.gz  in=378,042,212 out=81,157,278 elapsed=171.1s

  [11883/15692] intraday_6190.csv.gz  in=378,054,534 out=81,157,278 elapsed=171.1s

  [11884/15692] intraday_6191.csv.gz  in=378,065,054 out=81,157,278 elapsed=171.1s

  [11885/15692] intraday_6192.csv.gz  in=378,080,300 out=81,157,278 elapsed=171.2s

  [11886/15692] intraday_6193.csv.gz  in=378,095,217 out=81,157,278 elapsed=171.2s

  [11887/15692] intraday_6194.csv.gz  in=378,107,861 out=81,157,278 elapsed=171.2s

  [11888/15692] intraday_6195.csv.gz  in=378,120,448 out=81,157,278 elapsed=171.2s

  [11889/15692] intraday_6196.csv.gz  in=378,133,110 out=81,157,278 elapsed=171.2s

  [11890/15692] intraday_6197.csv.gz  in=378,143,515 out=81,157,278 elapsed=171.2s

  [11891/15692] intraday_6199.csv.gz  in=378,156,407 out=81,157,278 elapsed=171.2s

  [11892/15692] intraday_6198.csv.gz  in=378,168,870 out=81,157,278 elapsed=171.2s

  [11893/15692] intraday_6200.csv.gz  in=378,183,025 out=81,157,278 elapsed=171.2s

  [11894/15692] intraday_6201.csv.gz  in=378,194,148 out=81,157,278 elapsed=171.2s

  [11895/15692] intraday_6203.csv.gz  in=378,204,501 out=81,157,278 elapsed=171.2s

  [11896/15692] intraday_6202.csv.gz  in=378,217,994 out=81,157,278 elapsed=171.2s

  [11897/15692] intraday_6205.csv.gz  in=378,229,293 out=81,157,278 elapsed=171.3s

  [11898/15692] intraday_6204.csv.gz  in=378,243,928 out=81,157,278 elapsed=171.3s

  [11899/15692] intraday_6206.csv.gz  in=378,258,578 out=81,157,278 elapsed=171.3s

  [11900/15692] intraday_6207.csv.gz  in=378,268,449 out=81,157,278 elapsed=171.3s

  [11901/15692] intraday_6208.csv.gz  in=378,279,981 out=81,157,278 elapsed=171.3s

  [11902/15692] intraday_6209.csv.gz  in=378,292,344 out=81,157,278 elapsed=171.3s

  [11903/15692] intraday_6210.csv.gz  in=378,308,520 out=81,157,278 elapsed=171.3s

  [11904/15692] intraday_6211.csv.gz  in=378,325,164 out=81,157,278 elapsed=171.3s

  [11905/15692] intraday_6212.csv.gz  in=378,337,896 out=81,157,278 elapsed=171.3s

  [11906/15692] intraday_6213.csv.gz  in=378,350,263 out=81,157,278 elapsed=171.3s

  [11907/15692] intraday_6214.csv.gz  in=378,362,198 out=81,157,278 elapsed=171.3s

  [11908/15692] intraday_6216.csv.gz  in=378,377,147 out=81,157,278 elapsed=171.4s

  [11909/15692] intraday_6215.csv.gz  in=378,391,356 out=81,157,278 elapsed=171.4s

  [11910/15692] intraday_6217.csv.gz  in=378,405,569 out=81,157,278 elapsed=171.4s

  [11911/15692] intraday_6218.csv.gz  in=378,417,592 out=81,157,278 elapsed=171.4s

  [11912/15692] intraday_6219.csv.gz  in=378,431,900 out=81,157,278 elapsed=171.4s

  [11913/15692] intraday_6220.csv.gz  in=378,445,596 out=81,157,278 elapsed=171.4s

  [11914/15692] intraday_6221.csv.gz  in=378,459,367 out=81,157,278 elapsed=171.4s

  [11915/15692] intraday_6222.csv.gz  in=378,471,900 out=81,157,278 elapsed=171.4s

  [11916/15692] intraday_6223.csv.gz  in=378,485,005 out=81,157,278 elapsed=171.4s

  [11917/15692] intraday_6224.csv.gz  in=378,498,234 out=81,157,278 elapsed=171.4s

  [11918/15692] intraday_6226.csv.gz  in=378,512,297 out=81,157,278 elapsed=171.5s

  [11919/15692] intraday_6227.csv.gz  in=378,523,890 out=81,157,278 elapsed=171.5s

  [11920/15692] intraday_6228.csv.gz  in=378,535,393 out=81,157,278 elapsed=171.5s

  [11921/15692] intraday_6225.csv.gz  in=378,548,821 out=81,157,278 elapsed=171.5s

  [11922/15692] intraday_6231.csv.gz  in=378,561,885 out=81,157,278 elapsed=171.5s

  [11923/15692] intraday_6230.csv.gz  in=378,575,573 out=81,157,278 elapsed=171.5s

  [11924/15692] intraday_6229.csv.gz  in=378,593,087 out=81,157,278 elapsed=171.5s

  [11925/15692] intraday_6232.csv.gz  in=378,607,761 out=81,157,278 elapsed=171.5s

  [11926/15692] intraday_6234.csv.gz  in=378,621,144 out=81,157,278 elapsed=171.5s

  [11927/15692] intraday_6233.csv.gz  in=378,635,965 out=81,157,278 elapsed=171.6s

  [11928/15692] intraday_6235.csv.gz  in=378,649,531 out=81,157,278 elapsed=171.6s

  [11929/15692] intraday_6236.csv.gz  in=378,664,428 out=81,157,278 elapsed=171.6s

  [11930/15692] intraday_6237.csv.gz  in=378,679,089 out=81,157,278 elapsed=171.6s

  [11931/15692] intraday_6239.csv.gz  in=378,694,441 out=81,157,278 elapsed=171.6s

  [11932/15692] intraday_6238.csv.gz  in=378,706,076 out=81,157,278 elapsed=171.6s

  [11933/15692] intraday_6240.csv.gz  in=378,718,912 out=81,157,278 elapsed=171.6s

  [11934/15692] intraday_6241.csv.gz  in=378,733,073 out=81,157,278 elapsed=171.6s

  [11935/15692] intraday_6242.csv.gz  in=378,748,175 out=81,157,278 elapsed=171.7s

  [11936/15692] intraday_6243.csv.gz  in=378,763,481 out=81,157,278 elapsed=171.7s

  [11937/15692] intraday_6244.csv.gz  in=378,777,754 out=81,157,278 elapsed=171.7s

  [11938/15692] intraday_6245.csv.gz  in=378,792,009 out=81,157,278 elapsed=171.7s

  [11939/15692] intraday_6246.csv.gz  in=378,804,567 out=81,157,278 elapsed=171.7s

  [11940/15692] intraday_6248.csv.gz  in=378,815,423 out=81,157,278 elapsed=171.7s

  [11941/15692] intraday_6247.csv.gz  in=378,827,854 out=81,157,278 elapsed=171.7s

  [11942/15692] intraday_6249.csv.gz  in=378,843,347 out=81,157,278 elapsed=171.7s

  [11943/15692] intraday_6250.csv.gz  in=378,854,453 out=81,157,278 elapsed=171.7s

  [11944/15692] intraday_6253.csv.gz  in=378,870,117 out=81,157,278 elapsed=171.7s

  [11945/15692] intraday_6252.csv.gz  in=378,883,605 out=81,157,278 elapsed=171.7s

  [11946/15692] intraday_6251.csv.gz  in=378,897,386 out=81,157,278 elapsed=171.7s

  [11947/15692] intraday_6254.csv.gz  in=378,908,796 out=81,157,278 elapsed=171.8s

  [11948/15692] intraday_6256.csv.gz  in=378,921,810 out=81,157,278 elapsed=171.8s

  [11949/15692] intraday_6255.csv.gz  in=378,935,356 out=81,157,278 elapsed=171.8s

  [11950/15692] intraday_6257.csv.gz  in=378,948,189 out=81,157,278 elapsed=171.8s

  [11951/15692] intraday_6258.csv.gz  in=378,962,466 out=81,157,278 elapsed=171.8s

  [11952/15692] intraday_6261.csv.gz  in=378,976,554 out=81,157,278 elapsed=171.8s

  [11953/15692] intraday_6260.csv.gz  in=378,991,624 out=81,157,278 elapsed=171.8s

  [11954/15692] intraday_6259.csv.gz  in=379,006,627 out=81,157,278 elapsed=171.8s

  [11955/15692] intraday_6262.csv.gz  in=379,020,908 out=81,157,278 elapsed=171.8s

  [11956/15692] intraday_6265.csv.gz  in=379,033,284 out=81,157,278 elapsed=171.8s

  [11957/15692] intraday_6263.csv.gz  in=379,044,613 out=81,157,278 elapsed=171.9s

  [11958/15692] intraday_6264.csv.gz  in=379,058,560 out=81,157,278 elapsed=171.9s

  [11959/15692] intraday_6266.csv.gz  in=379,072,241 out=81,157,278 elapsed=171.9s

  [11960/15692] intraday_6267.csv.gz  in=379,082,996 out=81,157,278 elapsed=171.9s

  [11961/15692] intraday_6268.csv.gz  in=379,092,320 out=81,157,278 elapsed=171.9s

  [11962/15692] intraday_6270.csv.gz  in=379,094,967 out=81,157,278 elapsed=171.9s

  [11963/15692] intraday_6269.csv.gz  in=379,106,842 out=81,157,278 elapsed=171.9s

  [11964/15692] intraday_6271.csv.gz  in=379,122,439 out=81,157,278 elapsed=171.9s

  [11965/15692] intraday_6272.csv.gz  in=379,135,930 out=81,157,278 elapsed=171.9s

  [11966/15692] intraday_6273.csv.gz  in=379,157,717 out=81,157,278 elapsed=171.9s

  [11967/15692] intraday_6274.csv.gz  in=379,185,346 out=81,157,278 elapsed=171.9s

  [11968/15692] intraday_6275.csv.gz  in=379,198,465 out=81,157,278 elapsed=172.0s

  [11969/15692] intraday_6276.csv.gz  in=379,213,064 out=81,157,278 elapsed=172.0s

  [11970/15692] intraday_6277.csv.gz  in=379,230,579 out=81,157,278 elapsed=172.0s

  [11971/15692] intraday_6278.csv.gz  in=379,241,394 out=81,157,278 elapsed=172.0s

  [11972/15692] intraday_6279.csv.gz  in=379,256,322 out=81,157,278 elapsed=172.0s

  [11973/15692] intraday_6282.csv.gz  in=379,269,558 out=81,157,278 elapsed=172.0s

  [11974/15692] intraday_6281.csv.gz  in=379,286,133 out=81,157,278 elapsed=172.0s

  [11975/15692] intraday_6284.csv.gz  in=379,299,536 out=81,157,278 elapsed=172.0s

  [11976/15692] intraday_6283.csv.gz  in=379,312,063 out=81,157,278 elapsed=172.0s

  [11977/15692] intraday_6280.csv.gz  in=379,327,011 out=81,157,278 elapsed=172.1s

  [11978/15692] intraday_6287.csv.gz  in=379,340,927 out=81,157,278 elapsed=172.1s

  [11979/15692] intraday_6285.csv.gz  in=379,350,353 out=81,157,278 elapsed=172.1s

  [11980/15692] intraday_6286.csv.gz  in=379,359,831 out=81,157,278 elapsed=172.1s

  [11981/15692] intraday_6288.csv.gz  in=379,372,831 out=81,157,278 elapsed=172.1s

  [11982/15692] intraday_6289.csv.gz  in=379,383,899 out=81,157,278 elapsed=172.1s

  [11983/15692] intraday_6291.csv.gz  in=379,396,547 out=81,157,278 elapsed=172.1s

  [11984/15692] intraday_6292.csv.gz  in=379,408,626 out=81,157,278 elapsed=172.1s

  [11985/15692] intraday_6290.csv.gz  in=379,422,317 out=81,157,278 elapsed=172.1s

  [11986/15692] intraday_6293.csv.gz  in=379,436,249 out=81,157,278 elapsed=172.1s

  [11987/15692] intraday_6294.csv.gz  in=379,450,565 out=81,157,278 elapsed=172.2s

  [11988/15692] intraday_6296.csv.gz  in=379,462,529 out=81,157,278 elapsed=172.2s

  [11989/15692] intraday_6297.csv.gz  in=379,474,135 out=81,157,278 elapsed=172.2s

  [11990/15692] intraday_6295.csv.gz  in=379,487,213 out=81,157,278 elapsed=172.2s

  [11991/15692] intraday_6298.csv.gz  in=379,501,285 out=81,157,278 elapsed=172.2s

  [11992/15692] intraday_6300.csv.gz  in=379,525,267 out=81,157,278 elapsed=172.2s

  [11993/15692] intraday_6299.csv.gz  in=379,538,165 out=81,157,278 elapsed=172.2s

  [11994/15692] intraday_6301.csv.gz  in=379,555,126 out=81,157,278 elapsed=172.2s

  [11995/15692] intraday_6302.csv.gz  in=379,567,984 out=81,157,278 elapsed=172.2s

  [11996/15692] intraday_6303.csv.gz  in=379,578,330 out=81,157,278 elapsed=172.3s

  [11997/15692] intraday_6304.csv.gz  in=379,591,160 out=81,157,278 elapsed=172.3s

  [11998/15692] intraday_6305.csv.gz  in=379,614,460 out=81,157,278 elapsed=172.3s

  [11999/15692] intraday_6306.csv.gz  in=379,626,340 out=81,157,278 elapsed=172.3s

  [12000/15692] intraday_6307.csv.gz  in=379,638,216 out=81,157,278 elapsed=172.3s

  [12001/15692] intraday_6309.csv.gz  in=379,650,876 out=81,157,278 elapsed=172.3s

  [12002/15692] intraday_6308.csv.gz  in=379,661,374 out=81,157,278 elapsed=172.3s

  [12003/15692] intraday_6310.csv.gz  in=379,683,270 out=81,157,278 elapsed=172.3s

  [12004/15692] intraday_6311.csv.gz  in=379,693,950 out=81,157,278 elapsed=172.3s

  [12005/15692] intraday_6312.csv.gz  in=379,711,016 out=81,157,278 elapsed=172.3s

  [12006/15692] intraday_6313.csv.gz  in=379,725,224 out=81,157,278 elapsed=172.3s

  [12007/15692] intraday_6314.csv.gz  in=379,735,934 out=81,157,278 elapsed=172.4s

  [12008/15692] intraday_6315.csv.gz  in=379,749,590 out=81,157,278 elapsed=172.4s

  [12009/15692] intraday_6316.csv.gz  in=379,760,048 out=81,157,278 elapsed=172.4s

  [12010/15692] intraday_6317.csv.gz  in=379,774,809 out=81,157,278 elapsed=172.4s

  [12011/15692] intraday_6318.csv.gz  in=379,788,279 out=81,157,278 elapsed=172.4s

  [12012/15692] intraday_6320.csv.gz  in=379,809,355 out=81,157,278 elapsed=172.4s

  [12013/15692] intraday_6319.csv.gz  in=379,823,771 out=81,157,278 elapsed=172.4s

  [12014/15692] intraday_6322.csv.gz  in=379,834,151 out=81,157,278 elapsed=172.4s

  [12015/15692] intraday_6321.csv.gz  in=379,845,911 out=81,157,278 elapsed=172.4s

  [12016/15692] intraday_6323.csv.gz  in=379,860,202 out=81,157,278 elapsed=172.4s

  [12017/15692] intraday_6324.csv.gz  in=379,870,677 out=81,157,278 elapsed=172.5s

  [12018/15692] intraday_6325.csv.gz  in=379,885,132 out=81,157,278 elapsed=172.5s

  [12019/15692] intraday_6326.csv.gz  in=379,898,445 out=81,157,278 elapsed=172.5s

  [12020/15692] intraday_6327.csv.gz  in=379,911,081 out=81,157,278 elapsed=172.5s

  [12021/15692] intraday_6328.csv.gz  in=379,926,652 out=81,157,278 elapsed=172.5s

  [12022/15692] intraday_6329.csv.gz  in=379,939,534 out=81,157,278 elapsed=172.5s

  [12023/15692] intraday_6330.csv.gz  in=379,953,914 out=81,157,278 elapsed=172.5s

  [12024/15692] intraday_6332.csv.gz  in=379,968,140 out=81,157,278 elapsed=172.5s

  [12025/15692] intraday_6331.csv.gz  in=379,979,840 out=81,157,278 elapsed=172.6s

  [12026/15692] intraday_6333.csv.gz  in=379,991,476 out=81,157,278 elapsed=172.6s

  [12027/15692] intraday_6334.csv.gz  in=380,001,301 out=81,157,278 elapsed=172.6s

  [12028/15692] intraday_6336.csv.gz  in=380,015,609 out=81,157,278 elapsed=172.6s

  [12029/15692] intraday_6335.csv.gz  in=380,027,383 out=81,157,278 elapsed=172.6s

  [12030/15692] intraday_6338.csv.gz  in=380,041,238 out=81,157,278 elapsed=172.6s

  [12031/15692] intraday_6337.csv.gz  in=380,056,194 out=81,157,278 elapsed=172.6s

  [12032/15692] intraday_6341.csv.gz  in=380,067,907 out=81,157,278 elapsed=172.6s

  [12033/15692] intraday_6339.csv.gz  in=380,080,599 out=81,157,278 elapsed=172.6s

  [12034/15692] intraday_6340.csv.gz  in=380,091,972 out=81,157,278 elapsed=172.6s

  [12035/15692] intraday_6342.csv.gz  in=380,103,781 out=81,157,278 elapsed=172.6s

  [12036/15692] intraday_6343.csv.gz  in=380,116,039 out=81,157,278 elapsed=172.7s

  [12037/15692] intraday_6345.csv.gz  in=380,128,833 out=81,157,278 elapsed=172.7s

  [12038/15692] intraday_6344.csv.gz  in=380,142,071 out=81,157,278 elapsed=172.7s

  [12039/15692] intraday_6346.csv.gz  in=380,153,760 out=81,157,278 elapsed=172.7s

  [12040/15692] intraday_6347.csv.gz  in=380,164,283 out=81,157,278 elapsed=172.7s

  [12041/15692] intraday_6348.csv.gz  in=380,178,328 out=81,157,278 elapsed=172.7s

  [12042/15692] intraday_6351.csv.gz  in=380,188,002 out=81,157,278 elapsed=172.7s

  [12043/15692] intraday_6349.csv.gz  in=380,199,503 out=81,157,278 elapsed=172.7s

  [12044/15692] intraday_6350.csv.gz  in=380,212,902 out=81,157,278 elapsed=172.7s

  [12045/15692] intraday_6352.csv.gz  in=380,225,306 out=81,157,278 elapsed=172.7s

  [12046/15692] intraday_6353.csv.gz  in=380,238,569 out=81,157,278 elapsed=172.7s

  [12047/15692] intraday_6355.csv.gz  in=380,254,166 out=81,157,278 elapsed=172.8s

  [12048/15692] intraday_6356.csv.gz  in=380,269,829 out=81,157,278 elapsed=172.8s

  [12049/15692] intraday_6354.csv.gz  in=380,284,909 out=81,157,278 elapsed=172.8s

  [12050/15692] intraday_6357.csv.gz  in=380,296,371 out=81,157,278 elapsed=172.8s

  [12051/15692] intraday_6358.csv.gz  in=380,309,345 out=81,157,278 elapsed=172.8s

  [12052/15692] intraday_6360.csv.gz  in=380,325,722 out=81,157,278 elapsed=172.8s

  [12053/15692] intraday_6359.csv.gz  in=380,339,249 out=81,157,278 elapsed=172.8s

  [12054/15692] intraday_6361.csv.gz  in=380,360,609 out=81,157,278 elapsed=172.8s

  [12055/15692] intraday_6362.csv.gz  in=380,373,704 out=81,157,278 elapsed=172.8s

  [12056/15692] intraday_6363.csv.gz  in=380,386,996 out=81,157,278 elapsed=172.8s

  [12057/15692] intraday_6364.csv.gz  in=380,400,865 out=81,157,278 elapsed=172.8s

  [12058/15692] intraday_6365.csv.gz  in=380,415,475 out=81,157,278 elapsed=172.8s

  [12059/15692] intraday_6366.csv.gz  in=380,427,880 out=81,157,278 elapsed=172.8s

  [12060/15692] intraday_6367.csv.gz  in=380,440,824 out=81,157,278 elapsed=172.9s

  [12061/15692] intraday_6368.csv.gz  in=380,454,051 out=81,157,278 elapsed=172.9s

  [12062/15692] intraday_6369.csv.gz  in=380,466,443 out=81,157,278 elapsed=172.9s

  [12063/15692] intraday_6370.csv.gz  in=380,480,562 out=81,157,278 elapsed=172.9s

  [12064/15692] intraday_6371.csv.gz  in=380,492,448 out=81,157,278 elapsed=172.9s

  [12065/15692] intraday_6373.csv.gz  in=380,507,103 out=81,157,278 elapsed=172.9s

  [12066/15692] intraday_6372.csv.gz  in=380,525,558 out=81,157,278 elapsed=172.9s

  [12067/15692] intraday_6374.csv.gz  in=380,539,146 out=81,157,278 elapsed=172.9s

  [12068/15692] intraday_6375.csv.gz  in=380,552,258 out=81,157,278 elapsed=172.9s

  [12069/15692] intraday_6376.csv.gz  in=380,566,629 out=81,157,278 elapsed=172.9s

  [12070/15692] intraday_6377.csv.gz  in=380,581,128 out=81,157,278 elapsed=172.9s

  [12071/15692] intraday_6378.csv.gz  in=380,593,761 out=81,157,278 elapsed=173.0s

  [12072/15692] intraday_6379.csv.gz  in=380,607,262 out=81,157,278 elapsed=173.0s

  [12073/15692] intraday_6380.csv.gz  in=380,622,772 out=81,157,278 elapsed=173.0s

  [12074/15692] intraday_6381.csv.gz  in=380,636,102 out=81,157,278 elapsed=173.0s

  [12075/15692] intraday_6382.csv.gz  in=380,647,870 out=81,157,278 elapsed=173.0s

  [12076/15692] intraday_6384.csv.gz  in=380,659,704 out=81,157,278 elapsed=173.0s

  [12077/15692] intraday_6383.csv.gz  in=380,674,037 out=81,157,278 elapsed=173.0s

  [12078/15692] intraday_6386.csv.gz  in=380,689,964 out=81,157,278 elapsed=173.0s

  [12079/15692] intraday_6385.csv.gz  in=380,704,307 out=81,157,278 elapsed=173.0s

  [12080/15692] intraday_6388.csv.gz  in=380,719,000 out=81,157,278 elapsed=173.0s

  [12081/15692] intraday_6387.csv.gz  in=380,733,755 out=81,157,278 elapsed=173.0s

  [12082/15692] intraday_6389.csv.gz  in=380,746,711 out=81,157,278 elapsed=173.1s

  [12083/15692] intraday_6391.csv.gz  in=380,759,500 out=81,157,278 elapsed=173.1s

  [12084/15692] intraday_6392.csv.gz  in=380,770,514 out=81,157,278 elapsed=173.1s

  [12085/15692] intraday_6390.csv.gz  in=380,787,740 out=81,157,278 elapsed=173.1s

  [12086/15692] intraday_6396.csv.gz  in=380,801,701 out=81,157,278 elapsed=173.1s

  [12087/15692] intraday_6393.csv.gz  in=380,815,503 out=81,157,278 elapsed=173.1s

  [12088/15692] intraday_6394.csv.gz  in=380,827,242 out=81,157,278 elapsed=173.1s

  [12089/15692] intraday_6395.csv.gz  in=380,839,667 out=81,157,278 elapsed=173.1s

  [12090/15692] intraday_6398.csv.gz  in=380,851,319 out=81,157,278 elapsed=173.1s

  [12091/15692] intraday_6400.csv.gz  in=380,864,620 out=81,157,278 elapsed=173.1s

  [12092/15692] intraday_6397.csv.gz  in=380,891,130 out=81,157,278 elapsed=173.2s

  [12093/15692] intraday_6399.csv.gz  in=380,903,201 out=81,157,278 elapsed=173.2s

  [12094/15692] intraday_6402.csv.gz  in=380,918,916 out=81,157,278 elapsed=173.2s

  [12095/15692] intraday_6401.csv.gz  in=380,930,642 out=81,157,278 elapsed=173.2s

  [12096/15692] intraday_6404.csv.gz  in=380,945,381 out=81,157,278 elapsed=173.2s

  [12097/15692] intraday_6403.csv.gz  in=380,959,555 out=81,157,278 elapsed=173.2s

  [12098/15692] intraday_6405.csv.gz  in=380,974,202 out=81,157,278 elapsed=173.2s

  [12099/15692] intraday_6408.csv.gz  in=380,987,006 out=81,157,278 elapsed=173.2s

  [12100/15692] intraday_6406.csv.gz  in=381,001,001 out=81,157,278 elapsed=173.2s

  [12101/15692] intraday_6407.csv.gz  in=381,012,473 out=81,157,278 elapsed=173.2s

  [12102/15692] intraday_6409.csv.gz  in=381,024,915 out=81,157,278 elapsed=173.3s

  [12103/15692] intraday_6410.csv.gz  in=381,037,899 out=81,157,278 elapsed=173.3s

  [12104/15692] intraday_6412.csv.gz  in=381,046,807 out=81,157,278 elapsed=173.3s

  [12105/15692] intraday_6411.csv.gz  in=381,057,047 out=81,157,278 elapsed=173.3s

  [12106/15692] intraday_6413.csv.gz  in=381,069,618 out=81,157,278 elapsed=173.3s

  [12107/15692] intraday_6414.csv.gz  in=381,072,301 out=81,157,278 elapsed=173.3s

  [12108/15692] intraday_6416.csv.gz  in=381,085,202 out=81,157,278 elapsed=173.3s

  [12109/15692] intraday_6415.csv.gz  in=381,101,531 out=81,157,278 elapsed=173.3s

  [12110/15692] intraday_6417.csv.gz  in=381,115,518 out=81,157,278 elapsed=173.3s

  [12111/15692] intraday_6418.csv.gz  in=381,126,761 out=81,157,278 elapsed=173.3s

  [12112/15692] intraday_6419.csv.gz  in=381,139,632 out=81,157,278 elapsed=173.4s

  [12113/15692] intraday_6422.csv.gz  in=381,152,341 out=81,157,278 elapsed=173.4s

  [12114/15692] intraday_6421.csv.gz  in=381,167,375 out=81,157,278 elapsed=173.4s

  [12115/15692] intraday_6420.csv.gz  in=381,181,653 out=81,157,278 elapsed=173.4s

  [12116/15692] intraday_6424.csv.gz  in=381,196,150 out=81,157,278 elapsed=173.4s

  [12117/15692] intraday_6423.csv.gz  in=381,210,103 out=81,157,278 elapsed=173.4s

  [12118/15692] intraday_6426.csv.gz  in=381,223,953 out=81,157,278 elapsed=173.4s

  [12119/15692] intraday_6425.csv.gz  in=381,239,943 out=81,157,278 elapsed=173.4s

  [12120/15692] intraday_6427.csv.gz  in=381,253,661 out=81,157,278 elapsed=173.4s

  [12121/15692] intraday_6429.csv.gz  in=381,264,553 out=81,157,278 elapsed=173.4s

  [12122/15692] intraday_6428.csv.gz  in=381,277,038 out=81,157,278 elapsed=173.4s

  [12123/15692] intraday_6430.csv.gz  in=381,286,673 out=81,157,278 elapsed=173.4s

  [12124/15692] intraday_6431.csv.gz  in=381,300,456 out=81,157,278 elapsed=173.5s

  [12125/15692] intraday_6432.csv.gz  in=381,314,397 out=81,157,278 elapsed=173.5s

  [12126/15692] intraday_6434.csv.gz  in=381,327,758 out=81,157,278 elapsed=173.5s

  [12127/15692] intraday_6433.csv.gz  in=381,338,176 out=81,157,278 elapsed=173.5s

  [12128/15692] intraday_6437.csv.gz  in=381,350,418 out=81,157,278 elapsed=173.5s

  [12129/15692] intraday_6436.csv.gz  in=381,363,329 out=81,157,278 elapsed=173.5s

  [12130/15692] intraday_6435.csv.gz  in=381,375,714 out=81,157,278 elapsed=173.5s

  [12131/15692] intraday_6438.csv.gz  in=381,389,137 out=81,157,278 elapsed=173.5s

  [12132/15692] intraday_6439.csv.gz  in=381,401,470 out=81,157,278 elapsed=173.5s

  [12133/15692] intraday_6440.csv.gz  in=381,412,854 out=81,157,278 elapsed=173.6s

  [12134/15692] intraday_6442.csv.gz  in=381,424,688 out=81,157,278 elapsed=173.6s

  [12135/15692] intraday_6441.csv.gz  in=381,436,140 out=81,157,278 elapsed=173.6s

  [12136/15692] intraday_6443.csv.gz  in=381,448,941 out=81,157,278 elapsed=173.6s

  [12137/15692] intraday_6444.csv.gz  in=381,463,422 out=81,157,278 elapsed=173.6s

  [12138/15692] intraday_6446.csv.gz  in=381,474,272 out=81,157,278 elapsed=173.6s

  [12139/15692] intraday_6447.csv.gz  in=381,484,997 out=81,157,278 elapsed=173.6s

  [12140/15692] intraday_6445.csv.gz  in=381,502,301 out=81,157,278 elapsed=173.6s

  [12141/15692] intraday_6448.csv.gz  in=381,515,406 out=81,157,278 elapsed=173.7s

  [12142/15692] intraday_6449.csv.gz  in=381,530,329 out=81,157,278 elapsed=173.7s

  [12143/15692] intraday_6450.csv.gz  in=381,542,272 out=81,157,278 elapsed=173.7s

  [12144/15692] intraday_6451.csv.gz  in=381,555,955 out=81,157,278 elapsed=173.7s

  [12145/15692] intraday_6452.csv.gz  in=381,566,442 out=81,157,278 elapsed=173.7s

  [12146/15692] intraday_6454.csv.gz  in=381,577,578 out=81,157,278 elapsed=173.7s

  [12147/15692] intraday_6455.csv.gz  in=381,589,538 out=81,157,278 elapsed=173.7s

  [12148/15692] intraday_6453.csv.gz  in=381,601,941 out=81,157,278 elapsed=173.7s

  [12149/15692] intraday_6457.csv.gz  in=381,615,198 out=81,157,278 elapsed=173.7s

  [12150/15692] intraday_6456.csv.gz  in=381,628,409 out=81,157,278 elapsed=173.7s

  [12151/15692] intraday_6458.csv.gz  in=381,641,940 out=81,157,278 elapsed=173.7s

  [12152/15692] intraday_6459.csv.gz  in=381,654,961 out=81,157,278 elapsed=173.8s

  [12153/15692] intraday_6460.csv.gz  in=381,665,988 out=81,157,278 elapsed=173.8s

  [12154/15692] intraday_6462.csv.gz  in=381,677,594 out=81,157,278 elapsed=173.8s

  [12155/15692] intraday_6461.csv.gz  in=381,690,670 out=81,157,278 elapsed=173.8s

  [12156/15692] intraday_6463.csv.gz  in=381,701,682 out=81,157,278 elapsed=173.8s

  [12157/15692] intraday_6466.csv.gz  in=381,714,637 out=81,157,278 elapsed=173.8s

  [12158/15692] intraday_6464.csv.gz  in=381,726,357 out=81,157,278 elapsed=173.8s

  [12159/15692] intraday_6465.csv.gz  in=381,738,297 out=81,157,278 elapsed=173.8s

  [12160/15692] intraday_6467.csv.gz  in=381,750,979 out=81,157,278 elapsed=173.8s

  [12161/15692] intraday_6471.csv.gz  in=381,762,903 out=81,157,278 elapsed=173.9s

  [12162/15692] intraday_6468.csv.gz  in=381,774,646 out=81,157,278 elapsed=173.9s

  [12163/15692] intraday_6470.csv.gz  in=381,787,687 out=81,157,278 elapsed=173.9s

  [12164/15692] intraday_6469.csv.gz  in=381,802,683 out=81,157,278 elapsed=173.9s

  [12165/15692] intraday_6474.csv.gz  in=381,817,221 out=81,157,278 elapsed=173.9s

  [12166/15692] intraday_6475.csv.gz  in=381,829,464 out=81,157,278 elapsed=173.9s

  [12167/15692] intraday_6472.csv.gz  in=381,840,453 out=81,157,278 elapsed=173.9s

  [12168/15692] intraday_6473.csv.gz  in=381,854,541 out=81,157,278 elapsed=173.9s

  [12169/15692] intraday_6476.csv.gz  in=381,866,547 out=81,157,278 elapsed=173.9s

  [12170/15692] intraday_6477.csv.gz  in=381,878,825 out=81,157,278 elapsed=173.9s

  [12171/15692] intraday_6478.csv.gz  in=381,889,822 out=81,157,278 elapsed=174.0s

  [12172/15692] intraday_6479.csv.gz  in=381,903,895 out=81,157,278 elapsed=174.0s

  [12173/15692] intraday_6480.csv.gz  in=381,920,237 out=81,157,278 elapsed=174.0s

  [12174/15692] intraday_6482.csv.gz  in=381,932,746 out=81,157,278 elapsed=174.0s

  [12175/15692] intraday_6481.csv.gz  in=381,944,280 out=81,157,278 elapsed=174.0s

  [12176/15692] intraday_6483.csv.gz  in=381,957,466 out=81,157,278 elapsed=174.0s

  [12177/15692] intraday_6485.csv.gz  in=381,968,792 out=81,157,278 elapsed=174.0s

  [12178/15692] intraday_6486.csv.gz  in=381,980,673 out=81,157,278 elapsed=174.0s

  [12179/15692] intraday_6484.csv.gz  in=381,991,251 out=81,157,278 elapsed=174.0s

  [12180/15692] intraday_6487.csv.gz  in=382,006,075 out=81,157,278 elapsed=174.0s

  [12181/15692] intraday_6490.csv.gz  in=382,016,471 out=81,157,278 elapsed=174.1s

  [12182/15692] intraday_6489.csv.gz  in=382,029,465 out=81,157,278 elapsed=174.1s

  [12183/15692] intraday_6491.csv.gz  in=382,043,596 out=81,157,278 elapsed=174.1s

  [12184/15692] intraday_6488.csv.gz  in=382,054,719 out=81,157,278 elapsed=174.1s

  [12185/15692] intraday_6494.csv.gz  in=382,065,486 out=81,157,278 elapsed=174.1s

  [12186/15692] intraday_6495.csv.gz  in=382,076,128 out=81,157,278 elapsed=174.1s

  [12187/15692] intraday_6493.csv.gz  in=382,090,015 out=81,157,278 elapsed=174.1s

  [12188/15692] intraday_6492.csv.gz  in=382,102,423 out=81,157,278 elapsed=174.1s

  [12189/15692] intraday_6496.csv.gz  in=382,114,775 out=81,157,278 elapsed=174.1s

  [12190/15692] intraday_6497.csv.gz  in=382,130,970 out=81,157,278 elapsed=174.1s

  [12191/15692] intraday_6499.csv.gz  in=382,144,961 out=81,157,278 elapsed=174.1s

  [12192/15692] intraday_6498.csv.gz  in=382,161,443 out=81,157,278 elapsed=174.1s

  [12193/15692] intraday_6501.csv.gz  in=382,172,911 out=81,157,278 elapsed=174.2s

  [12194/15692] intraday_6500.csv.gz  in=382,186,227 out=81,157,278 elapsed=174.2s

  [12195/15692] intraday_6502.csv.gz  in=382,200,739 out=81,157,278 elapsed=174.2s

  [12196/15692] intraday_6503.csv.gz  in=382,214,994 out=81,157,278 elapsed=174.2s

  [12197/15692] intraday_6504.csv.gz  in=382,229,522 out=81,157,278 elapsed=174.2s

  [12198/15692] intraday_6507.csv.gz  in=382,243,665 out=81,157,278 elapsed=174.2s

  [12199/15692] intraday_6505.csv.gz  in=382,255,737 out=81,157,278 elapsed=174.2s

  [12200/15692] intraday_6506.csv.gz  in=382,272,370 out=81,157,278 elapsed=174.2s

  [12201/15692] intraday_6508.csv.gz  in=382,286,071 out=81,157,278 elapsed=174.2s

  [12202/15692] intraday_6509.csv.gz  in=382,298,641 out=81,157,278 elapsed=174.2s

  [12203/15692] intraday_6510.csv.gz  in=382,312,029 out=81,157,278 elapsed=174.2s

  [12204/15692] intraday_6511.csv.gz  in=382,324,338 out=81,157,278 elapsed=174.2s

  [12205/15692] intraday_6512.csv.gz  in=382,338,903 out=81,157,278 elapsed=174.2s

  [12206/15692] intraday_6513.csv.gz  in=382,351,456 out=81,157,278 elapsed=174.3s

  [12207/15692] intraday_6514.csv.gz  in=382,364,370 out=81,157,278 elapsed=174.3s

  [12208/15692] intraday_6515.csv.gz  in=382,376,465 out=81,157,278 elapsed=174.3s

  [12209/15692] intraday_6516.csv.gz  in=382,391,521 out=81,157,278 elapsed=174.3s

  [12210/15692] intraday_6517.csv.gz  in=382,406,771 out=81,157,278 elapsed=174.3s

  [12211/15692] intraday_6519.csv.gz  in=382,417,601 out=81,157,278 elapsed=174.3s

  [12212/15692] intraday_6518.csv.gz  in=382,431,541 out=81,157,278 elapsed=174.3s

  [12213/15692] intraday_6522.csv.gz  in=382,443,128 out=81,157,278 elapsed=174.3s

  [12214/15692] intraday_6523.csv.gz  in=382,458,095 out=81,157,278 elapsed=174.3s

  [12215/15692] intraday_6521.csv.gz  in=382,470,823 out=81,157,278 elapsed=174.3s

  [12216/15692] intraday_6520.csv.gz  in=382,503,899 out=81,157,278 elapsed=174.3s

  [12217/15692] intraday_6524.csv.gz  in=382,517,217 out=81,157,278 elapsed=174.4s

  [12218/15692] intraday_6525.csv.gz  in=382,529,189 out=81,157,278 elapsed=174.4s

  [12219/15692] intraday_6527.csv.gz  in=382,551,573 out=81,157,278 elapsed=174.4s

  [12220/15692] intraday_6526.csv.gz  in=382,566,422 out=81,157,278 elapsed=174.4s

  [12221/15692] intraday_6528.csv.gz  in=382,579,967 out=81,157,278 elapsed=174.4s

  [12222/15692] intraday_6529.csv.gz  in=382,595,937 out=81,157,278 elapsed=174.4s

  [12223/15692] intraday_6531.csv.gz  in=382,608,436 out=81,157,278 elapsed=174.4s

  [12224/15692] intraday_6530.csv.gz  in=382,625,170 out=81,157,278 elapsed=174.4s

  [12225/15692] intraday_6532.csv.gz  in=382,641,073 out=81,157,278 elapsed=174.4s

  [12226/15692] intraday_6533.csv.gz  in=382,652,729 out=81,157,278 elapsed=174.4s

  [12227/15692] intraday_6535.csv.gz  in=382,664,014 out=81,157,278 elapsed=174.5s

  [12228/15692] intraday_6534.csv.gz  in=382,677,130 out=81,157,278 elapsed=174.5s

  [12229/15692] intraday_6537.csv.gz  in=382,688,381 out=81,157,278 elapsed=174.5s

  [12230/15692] intraday_6536.csv.gz  in=382,702,891 out=81,157,278 elapsed=174.5s

  [12231/15692] intraday_6538.csv.gz  in=382,717,001 out=81,157,278 elapsed=174.5s

  [12232/15692] intraday_6539.csv.gz  in=382,729,318 out=81,157,278 elapsed=174.5s

  [12233/15692] intraday_6541.csv.gz  in=382,742,528 out=81,157,278 elapsed=174.5s

  [12234/15692] intraday_6542.csv.gz  in=382,755,268 out=81,157,278 elapsed=174.5s

  [12235/15692] intraday_6540.csv.gz  in=382,770,607 out=81,157,278 elapsed=174.5s

  [12236/15692] intraday_6543.csv.gz  in=382,783,678 out=81,157,278 elapsed=174.5s

  [12237/15692] intraday_6544.csv.gz  in=382,796,089 out=81,157,278 elapsed=174.5s

  [12238/15692] intraday_6545.csv.gz  in=382,809,281 out=81,157,278 elapsed=174.5s

  [12239/15692] intraday_6546.csv.gz  in=382,823,831 out=81,157,278 elapsed=174.5s

  [12240/15692] intraday_6548.csv.gz  in=382,838,824 out=81,157,278 elapsed=174.6s

  [12241/15692] intraday_6547.csv.gz  in=382,852,345 out=81,157,278 elapsed=174.6s

  [12242/15692] intraday_6550.csv.gz  in=382,863,131 out=81,157,278 elapsed=174.6s

  [12243/15692] intraday_6549.csv.gz  in=382,876,976 out=81,157,278 elapsed=174.6s

  [12244/15692] intraday_6551.csv.gz  in=382,890,629 out=81,157,278 elapsed=174.6s

  [12245/15692] intraday_6552.csv.gz  in=382,903,399 out=81,157,278 elapsed=174.6s

  [12246/15692] intraday_6553.csv.gz  in=382,915,167 out=81,157,278 elapsed=174.6s

  [12247/15692] intraday_6554.csv.gz  in=382,926,958 out=81,157,278 elapsed=174.6s

  [12248/15692] intraday_6555.csv.gz  in=382,935,498 out=81,157,278 elapsed=174.6s

  [12249/15692] intraday_6557.csv.gz  in=382,940,748 out=81,157,278 elapsed=174.6s

  [12250/15692] intraday_6556.csv.gz  in=382,953,334 out=81,157,278 elapsed=174.6s

  [12251/15692] intraday_6558.csv.gz  in=382,972,610 out=81,157,278 elapsed=174.6s

  [12252/15692] intraday_6559.csv.gz  in=382,985,985 out=81,157,278 elapsed=174.7s

  [12253/15692] intraday_6560.csv.gz  in=382,998,951 out=81,157,278 elapsed=174.7s

  [12254/15692] intraday_6562.csv.gz  in=383,011,735 out=81,157,278 elapsed=174.7s

  [12255/15692] intraday_6561.csv.gz  in=383,023,223 out=81,157,278 elapsed=174.7s

  [12256/15692] intraday_6563.csv.gz  in=383,038,604 out=81,157,278 elapsed=174.7s

  [12257/15692] intraday_6564.csv.gz  in=383,052,943 out=81,157,278 elapsed=174.7s

  [12258/15692] intraday_6565.csv.gz  in=383,064,995 out=81,157,278 elapsed=174.7s

  [12259/15692] intraday_6566.csv.gz  in=383,082,439 out=81,157,278 elapsed=174.7s

  [12260/15692] intraday_6567.csv.gz  in=383,096,272 out=81,157,278 elapsed=174.7s

  [12261/15692] intraday_6569.csv.gz  in=383,110,000 out=81,157,278 elapsed=174.7s

  [12262/15692] intraday_6568.csv.gz  in=383,126,433 out=81,157,278 elapsed=174.7s

  [12263/15692] intraday_6570.csv.gz  in=383,140,609 out=81,157,278 elapsed=174.7s

  [12264/15692] intraday_6571.csv.gz  in=383,152,938 out=81,157,278 elapsed=174.7s

  [12265/15692] intraday_6572.csv.gz  in=383,163,365 out=81,157,278 elapsed=174.7s

  [12266/15692] intraday_6575.csv.gz  in=383,176,568 out=81,157,278 elapsed=174.7s

  [12267/15692] intraday_6573.csv.gz  in=383,185,784 out=81,157,278 elapsed=174.7s

  [12268/15692] intraday_6574.csv.gz  in=383,200,038 out=81,157,278 elapsed=174.7s

  [12269/15692] intraday_6576.csv.gz  in=383,212,130 out=81,157,278 elapsed=174.7s

  [12270/15692] intraday_6580.csv.gz  in=383,224,152 out=81,157,278 elapsed=174.8s

  [12271/15692] intraday_6578.csv.gz  in=383,236,507 out=81,157,278 elapsed=174.8s

  [12272/15692] intraday_6579.csv.gz  in=383,248,967 out=81,157,278 elapsed=174.8s

  [12273/15692] intraday_6577.csv.gz  in=383,261,705 out=81,157,278 elapsed=174.8s

  [12274/15692] intraday_6582.csv.gz  in=383,275,569 out=81,157,278 elapsed=174.8s

  [12275/15692] intraday_6581.csv.gz  in=383,289,143 out=81,157,278 elapsed=174.8s

  [12276/15692] intraday_6583.csv.gz  in=383,310,149 out=81,157,278 elapsed=174.8s

  [12277/15692] intraday_6584.csv.gz  in=383,321,709 out=81,157,278 elapsed=174.8s

  [12278/15692] intraday_6585.csv.gz  in=383,333,910 out=81,157,278 elapsed=174.8s

  [12279/15692] intraday_6587.csv.gz  in=383,346,495 out=81,157,278 elapsed=174.8s

  [12280/15692] intraday_6586.csv.gz  in=383,358,916 out=81,157,278 elapsed=174.8s

  [12281/15692] intraday_6588.csv.gz  in=383,376,566 out=81,157,278 elapsed=174.9s

  [12282/15692] intraday_6589.csv.gz  in=383,389,328 out=81,157,278 elapsed=174.9s

  [12283/15692] intraday_6590.csv.gz  in=383,401,004 out=81,157,278 elapsed=174.9s

  [12284/15692] intraday_6591.csv.gz  in=383,413,908 out=81,157,278 elapsed=174.9s

  [12285/15692] intraday_6592.csv.gz  in=383,427,716 out=81,157,278 elapsed=174.9s

  [12286/15692] intraday_6594.csv.gz  in=383,442,513 out=81,157,278 elapsed=174.9s

  [12287/15692] intraday_6593.csv.gz  in=383,454,123 out=81,157,278 elapsed=174.9s

  [12288/15692] intraday_6595.csv.gz  in=383,465,338 out=81,157,278 elapsed=174.9s

  [12289/15692] intraday_6596.csv.gz  in=383,479,431 out=81,157,278 elapsed=174.9s

  [12290/15692] intraday_6597.csv.gz  in=383,491,644 out=81,157,278 elapsed=174.9s

  [12291/15692] intraday_6598.csv.gz  in=383,504,137 out=81,157,278 elapsed=175.0s

  [12292/15692] intraday_6599.csv.gz  in=383,520,726 out=81,157,278 elapsed=175.0s

  [12293/15692] intraday_6600.csv.gz  in=383,534,065 out=81,157,278 elapsed=175.0s

  [12294/15692] intraday_6601.csv.gz  in=383,545,334 out=81,157,278 elapsed=175.0s

  [12295/15692] intraday_6602.csv.gz  in=383,559,170 out=81,157,278 elapsed=175.0s

  [12296/15692] intraday_6604.csv.gz  in=383,571,545 out=81,157,278 elapsed=175.0s

  [12297/15692] intraday_6603.csv.gz  in=383,582,671 out=81,157,278 elapsed=175.0s

  [12298/15692] intraday_6605.csv.gz  in=383,596,068 out=81,157,278 elapsed=175.0s

  [12299/15692] intraday_6606.csv.gz  in=383,606,778 out=81,157,278 elapsed=175.0s

  [12300/15692] intraday_6608.csv.gz  in=383,618,566 out=81,157,278 elapsed=175.0s

  [12301/15692] intraday_6607.csv.gz  in=383,630,115 out=81,157,278 elapsed=175.0s

  [12302/15692] intraday_6609.csv.gz  in=383,642,509 out=81,157,278 elapsed=175.1s

  [12303/15692] intraday_6610.csv.gz  in=383,655,197 out=81,157,278 elapsed=175.1s

  [12304/15692] intraday_6611.csv.gz  in=383,667,552 out=81,157,278 elapsed=175.1s

  [12305/15692] intraday_6612.csv.gz  in=383,682,420 out=81,157,278 elapsed=175.1s

  [12306/15692] intraday_6613.csv.gz  in=383,696,359 out=81,157,278 elapsed=175.1s

  [12307/15692] intraday_6615.csv.gz  in=383,707,744 out=81,157,278 elapsed=175.1s

  [12308/15692] intraday_6614.csv.gz  in=383,720,632 out=81,157,278 elapsed=175.1s

  [12309/15692] intraday_6617.csv.gz  in=383,735,421 out=81,157,278 elapsed=175.1s

  [12310/15692] intraday_6616.csv.gz  in=383,749,451 out=81,157,278 elapsed=175.1s

  [12311/15692] intraday_6619.csv.gz  in=383,763,133 out=81,157,278 elapsed=175.1s

  [12312/15692] intraday_6618.csv.gz  in=383,776,297 out=81,157,278 elapsed=175.2s

  [12313/15692] intraday_6620.csv.gz  in=383,787,980 out=81,157,278 elapsed=175.2s

  [12314/15692] intraday_6621.csv.gz  in=383,799,664 out=81,157,278 elapsed=175.2s

  [12315/15692] intraday_6623.csv.gz  in=383,815,413 out=81,157,278 elapsed=175.2s

  [12316/15692] intraday_6624.csv.gz  in=383,828,560 out=81,157,278 elapsed=175.2s

  [12317/15692] intraday_6622.csv.gz  in=383,845,231 out=81,157,278 elapsed=175.2s

  [12318/15692] intraday_6625.csv.gz  in=383,858,469 out=81,157,278 elapsed=175.2s

  [12319/15692] intraday_6627.csv.gz  in=383,869,912 out=81,157,278 elapsed=175.2s

  [12320/15692] intraday_6628.csv.gz  in=383,882,176 out=81,157,278 elapsed=175.2s

  [12321/15692] intraday_6626.csv.gz  in=383,894,889 out=81,157,278 elapsed=175.2s

  [12322/15692] intraday_6629.csv.gz  in=383,905,874 out=81,157,278 elapsed=175.3s

  [12323/15692] intraday_6630.csv.gz  in=383,920,375 out=81,157,278 elapsed=175.3s

  [12324/15692] intraday_6631.csv.gz  in=383,933,388 out=81,157,278 elapsed=175.3s

  [12325/15692] intraday_6632.csv.gz  in=383,945,440 out=81,157,278 elapsed=175.3s

  [12326/15692] intraday_6634.csv.gz  in=383,958,726 out=81,157,278 elapsed=175.3s

  [12327/15692] intraday_6635.csv.gz  in=383,970,598 out=81,157,278 elapsed=175.3s

  [12328/15692] intraday_6633.csv.gz  in=383,980,930 out=81,157,278 elapsed=175.3s

  [12329/15692] intraday_6636.csv.gz  in=383,993,092 out=81,157,278 elapsed=175.3s

  [12330/15692] intraday_6638.csv.gz  in=384,002,823 out=81,157,278 elapsed=175.3s

  [12331/15692] intraday_6639.csv.gz  in=384,015,026 out=81,157,278 elapsed=175.4s

  [12332/15692] intraday_6637.csv.gz  in=384,031,750 out=81,157,278 elapsed=175.4s

  [12333/15692] intraday_6640.csv.gz  in=384,044,401 out=81,157,278 elapsed=175.4s

  [12334/15692] intraday_6641.csv.gz  in=384,060,145 out=81,157,278 elapsed=175.4s

  [12335/15692] intraday_6643.csv.gz  in=384,073,566 out=81,157,278 elapsed=175.4s

  [12336/15692] intraday_6644.csv.gz  in=384,085,974 out=81,157,278 elapsed=175.4s

  [12337/15692] intraday_6642.csv.gz  in=384,100,701 out=81,157,278 elapsed=175.4s

  [12338/15692] intraday_6645.csv.gz  in=384,114,832 out=81,157,278 elapsed=175.4s

  [12339/15692] intraday_6647.csv.gz  in=384,131,089 out=81,157,278 elapsed=175.4s

  [12340/15692] intraday_6646.csv.gz  in=384,144,408 out=81,157,278 elapsed=175.4s

  [12341/15692] intraday_6650.csv.gz  in=384,158,643 out=81,157,278 elapsed=175.5s

  [12342/15692] intraday_6651.csv.gz  in=384,173,005 out=81,157,278 elapsed=175.5s

  [12343/15692] intraday_6648.csv.gz  in=384,187,956 out=81,157,278 elapsed=175.5s

  [12344/15692] intraday_6649.csv.gz  in=384,205,324 out=81,157,278 elapsed=175.5s

  [12345/15692] intraday_6652.csv.gz  in=384,219,081 out=81,157,278 elapsed=175.5s

  [12346/15692] intraday_6653.csv.gz  in=384,232,139 out=81,157,278 elapsed=175.5s

  [12347/15692] intraday_6655.csv.gz  in=384,245,291 out=81,157,278 elapsed=175.5s

  [12348/15692] intraday_6654.csv.gz  in=384,257,837 out=81,157,278 elapsed=175.5s

  [12349/15692] intraday_6656.csv.gz  in=384,272,011 out=81,157,278 elapsed=175.5s

  [12350/15692] intraday_6657.csv.gz  in=384,286,253 out=81,157,278 elapsed=175.6s

  [12351/15692] intraday_6659.csv.gz  in=384,299,937 out=81,157,278 elapsed=175.6s

  [12352/15692] intraday_6658.csv.gz  in=384,312,346 out=81,157,278 elapsed=175.6s

  [12353/15692] intraday_6660.csv.gz  in=384,327,048 out=81,157,278 elapsed=175.6s

  [12354/15692] intraday_6661.csv.gz  in=384,341,140 out=81,157,278 elapsed=175.6s

  [12355/15692] intraday_6662.csv.gz  in=384,354,071 out=81,157,278 elapsed=175.6s

  [12356/15692] intraday_6664.csv.gz  in=384,369,654 out=81,157,278 elapsed=175.6s

  [12357/15692] intraday_6663.csv.gz  in=384,384,396 out=81,157,278 elapsed=175.6s

  [12358/15692] intraday_6665.csv.gz  in=384,396,618 out=81,157,278 elapsed=175.6s

  [12359/15692] intraday_6666.csv.gz  in=384,410,345 out=81,157,278 elapsed=175.6s

  [12360/15692] intraday_6668.csv.gz  in=384,423,400 out=81,157,278 elapsed=175.7s

  [12361/15692] intraday_6669.csv.gz  in=384,434,379 out=81,157,278 elapsed=175.7s

  [12362/15692] intraday_6667.csv.gz  in=384,449,761 out=81,157,278 elapsed=175.7s

  [12363/15692] intraday_6670.csv.gz  in=384,464,491 out=81,157,278 elapsed=175.7s

  [12364/15692] intraday_6671.csv.gz  in=384,476,207 out=81,157,278 elapsed=175.7s

  [12365/15692] intraday_6672.csv.gz  in=384,491,317 out=81,157,278 elapsed=175.7s

  [12366/15692] intraday_6673.csv.gz  in=384,506,909 out=81,157,278 elapsed=175.7s

  [12367/15692] intraday_6674.csv.gz  in=384,523,465 out=81,157,278 elapsed=175.7s

  [12368/15692] intraday_6675.csv.gz  in=384,538,573 out=81,157,278 elapsed=175.7s

  [12369/15692] intraday_6677.csv.gz  in=384,550,842 out=81,157,278 elapsed=175.8s

  [12370/15692] intraday_6676.csv.gz  in=384,563,271 out=81,157,278 elapsed=175.8s

  [12371/15692] intraday_6679.csv.gz  in=384,574,428 out=81,157,278 elapsed=175.8s

  [12372/15692] intraday_6678.csv.gz  in=384,586,436 out=81,157,278 elapsed=175.8s

  [12373/15692] intraday_6681.csv.gz  in=384,597,265 out=81,157,278 elapsed=175.8s

  [12374/15692] intraday_6680.csv.gz  in=384,612,186 out=81,157,278 elapsed=175.8s

  [12375/15692] intraday_6682.csv.gz  in=384,625,309 out=81,157,278 elapsed=175.8s

  [12376/15692] intraday_6683.csv.gz  in=384,638,184 out=81,157,278 elapsed=175.8s

  [12377/15692] intraday_6685.csv.gz  in=384,654,721 out=81,157,278 elapsed=175.8s

  [12378/15692] intraday_6686.csv.gz  in=384,667,458 out=81,157,278 elapsed=175.8s

  [12379/15692] intraday_6684.csv.gz  in=384,683,249 out=81,157,278 elapsed=175.8s

  [12380/15692] intraday_6687.csv.gz  in=384,696,879 out=81,157,278 elapsed=175.8s

  [12381/15692] intraday_6689.csv.gz  in=384,709,690 out=81,157,278 elapsed=175.9s

  [12382/15692] intraday_6688.csv.gz  in=384,723,638 out=81,157,278 elapsed=175.9s

  [12383/15692] intraday_6690.csv.gz  in=384,737,915 out=81,157,278 elapsed=175.9s

  [12384/15692] intraday_6691.csv.gz  in=384,752,319 out=81,157,278 elapsed=175.9s

  [12385/15692] intraday_6692.csv.gz  in=384,765,985 out=81,157,278 elapsed=175.9s

  [12386/15692] intraday_6693.csv.gz  in=384,779,512 out=81,157,278 elapsed=175.9s

  [12387/15692] intraday_6694.csv.gz  in=384,791,018 out=81,157,278 elapsed=175.9s

  [12388/15692] intraday_6695.csv.gz  in=384,804,770 out=81,157,278 elapsed=175.9s

  [12389/15692] intraday_6697.csv.gz  in=384,816,927 out=81,157,278 elapsed=176.0s

  [12390/15692] intraday_6696.csv.gz  in=384,828,840 out=81,157,278 elapsed=176.0s

  [12391/15692] intraday_6698.csv.gz  in=384,840,183 out=81,157,278 elapsed=176.0s

  [12392/15692] intraday_6701.csv.gz  in=384,843,955 out=81,157,278 elapsed=176.0s

  [12393/15692] intraday_6699.csv.gz  in=384,852,153 out=81,157,278 elapsed=176.0s

  [12394/15692] intraday_6703.csv.gz  in=384,852,362 out=81,157,278 elapsed=176.0s

  [12395/15692] intraday_6702.csv.gz  in=384,852,398 out=81,157,278 elapsed=176.0s

  [12396/15692] intraday_6700.csv.gz  in=384,865,444 out=81,157,278 elapsed=176.0s

  [12397/15692] intraday_6704.csv.gz  in=384,866,139 out=81,157,278 elapsed=176.0s

  [12398/15692] intraday_6706.csv.gz  in=384,866,149 out=81,157,278 elapsed=176.0s

  [12399/15692] intraday_6705.csv.gz  in=384,866,173 out=81,157,278 elapsed=176.0s

  [12400/15692] intraday_6707.csv.gz  in=384,866,194 out=81,157,278 elapsed=176.0s

  [12401/15692] intraday_6709.csv.gz  in=384,866,197 out=81,157,278 elapsed=176.0s

  [12402/15692] intraday_6708.csv.gz  in=384,866,525 out=81,157,278 elapsed=176.0s

  [12403/15692] intraday_6710.csv.gz  in=384,866,550 out=81,157,278 elapsed=176.0s

  [12404/15692] intraday_6711.csv.gz  in=384,884,258 out=81,157,278 elapsed=176.1s

  [12405/15692] intraday_6714.csv.gz  in=384,897,003 out=81,157,278 elapsed=176.1s

  [12406/15692] intraday_6712.csv.gz  in=384,910,840 out=81,157,278 elapsed=176.1s

  [12407/15692] intraday_6713.csv.gz  in=384,924,735 out=81,157,278 elapsed=176.1s

  [12408/15692] intraday_6715.csv.gz  in=384,936,860 out=81,157,278 elapsed=176.1s

  [12409/15692] intraday_6717.csv.gz  in=384,953,227 out=81,157,278 elapsed=176.1s

  [12410/15692] intraday_6716.csv.gz  in=384,968,809 out=81,157,278 elapsed=176.2s

  [12411/15692] intraday_6719.csv.gz  in=384,983,091 out=81,157,278 elapsed=176.2s

  [12412/15692] intraday_6718.csv.gz  in=384,995,880 out=81,157,278 elapsed=176.2s

  [12413/15692] intraday_6720.csv.gz  in=385,010,698 out=81,157,278 elapsed=176.2s

  [12414/15692] intraday_6723.csv.gz  in=385,024,333 out=81,157,278 elapsed=176.2s

  [12415/15692] intraday_6721.csv.gz  in=385,040,288 out=81,157,278 elapsed=176.2s

  [12416/15692] intraday_6722.csv.gz  in=385,055,287 out=81,157,278 elapsed=176.2s

  [12417/15692] intraday_6725.csv.gz  in=385,066,479 out=81,157,278 elapsed=176.2s

  [12418/15692] intraday_6726.csv.gz  in=385,079,398 out=81,157,278 elapsed=176.2s

  [12419/15692] intraday_6724.csv.gz  in=385,093,143 out=81,157,278 elapsed=176.2s

  [12420/15692] intraday_6727.csv.gz  in=385,107,978 out=81,157,278 elapsed=176.3s

  [12421/15692] intraday_6728.csv.gz  in=385,122,460 out=81,157,278 elapsed=176.3s

  [12422/15692] intraday_6731.csv.gz  in=385,134,723 out=81,157,278 elapsed=176.3s

  [12423/15692] intraday_6729.csv.gz  in=385,146,376 out=81,157,278 elapsed=176.3s

  [12424/15692] intraday_6730.csv.gz  in=385,159,580 out=81,157,278 elapsed=176.3s

  [12425/15692] intraday_6733.csv.gz  in=385,172,082 out=81,157,278 elapsed=176.3s

  [12426/15692] intraday_6732.csv.gz  in=385,185,372 out=81,157,278 elapsed=176.3s

  [12427/15692] intraday_6734.csv.gz  in=385,199,502 out=81,157,278 elapsed=176.3s

  [12428/15692] intraday_6735.csv.gz  in=385,213,652 out=81,157,278 elapsed=176.3s

  [12429/15692] intraday_6736.csv.gz  in=385,227,322 out=81,157,278 elapsed=176.3s

  [12430/15692] intraday_6739.csv.gz  in=385,240,111 out=81,157,278 elapsed=176.3s

  [12431/15692] intraday_6738.csv.gz  in=385,253,691 out=81,157,278 elapsed=176.3s

  [12432/15692] intraday_6737.csv.gz  in=385,264,977 out=81,157,278 elapsed=176.3s

  [12433/15692] intraday_6740.csv.gz  in=385,278,877 out=81,157,278 elapsed=176.4s

  [12434/15692] intraday_6742.csv.gz  in=385,293,907 out=81,157,278 elapsed=176.4s

  [12435/15692] intraday_6743.csv.gz  in=385,304,454 out=81,157,278 elapsed=176.4s

  [12436/15692] intraday_6741.csv.gz  in=385,323,493 out=81,157,278 elapsed=176.4s

  [12437/15692] intraday_6744.csv.gz  in=385,337,137 out=81,157,278 elapsed=176.4s

  [12438/15692] intraday_6745.csv.gz  in=385,352,735 out=81,157,278 elapsed=176.4s

  [12439/15692] intraday_6747.csv.gz  in=385,366,734 out=81,157,278 elapsed=176.4s

  [12440/15692] intraday_6746.csv.gz  in=385,387,271 out=81,157,278 elapsed=176.4s

  [12441/15692] intraday_6748.csv.gz  in=385,399,567 out=81,157,278 elapsed=176.4s

  [12442/15692] intraday_6749.csv.gz  in=385,412,902 out=81,157,278 elapsed=176.4s

  [12443/15692] intraday_6750.csv.gz  in=385,424,306 out=81,157,278 elapsed=176.4s

  [12444/15692] intraday_6751.csv.gz  in=385,436,250 out=81,157,278 elapsed=176.4s

  [12445/15692] intraday_6752.csv.gz  in=385,449,141 out=81,157,278 elapsed=176.4s

  [12446/15692] intraday_6753.csv.gz  in=385,462,961 out=81,157,278 elapsed=176.4s

  [12447/15692] intraday_6754.csv.gz  in=385,486,775 out=81,157,278 elapsed=176.5s

  [12448/15692] intraday_6755.csv.gz  in=385,500,375 out=81,157,278 elapsed=176.5s

  [12449/15692] intraday_6757.csv.gz  in=385,513,296 out=81,157,278 elapsed=176.5s

  [12450/15692] intraday_6756.csv.gz  in=385,526,189 out=81,157,278 elapsed=176.5s

  [12451/15692] intraday_6761.csv.gz  in=385,537,859 out=81,157,278 elapsed=176.5s

  [12452/15692] intraday_6758.csv.gz  in=385,552,713 out=81,157,278 elapsed=176.5s

  [12453/15692] intraday_6760.csv.gz  in=385,566,242 out=81,157,278 elapsed=176.5s

  [12454/15692] intraday_6759.csv.gz  in=385,578,508 out=81,157,278 elapsed=176.5s

  [12455/15692] intraday_6762.csv.gz  in=385,590,200 out=81,157,278 elapsed=176.5s

  [12456/15692] intraday_6764.csv.gz  in=385,600,334 out=81,157,278 elapsed=176.5s

  [12457/15692] intraday_6763.csv.gz  in=385,615,656 out=81,157,278 elapsed=176.5s

  [12458/15692] intraday_6765.csv.gz  in=385,632,381 out=81,157,278 elapsed=176.5s

  [12459/15692] intraday_6766.csv.gz  in=385,646,460 out=81,157,278 elapsed=176.6s

  [12460/15692] intraday_6767.csv.gz  in=385,660,074 out=81,157,278 elapsed=176.6s

  [12461/15692] intraday_6768.csv.gz  in=385,673,950 out=81,157,278 elapsed=176.6s

  [12462/15692] intraday_6769.csv.gz  in=385,687,687 out=81,157,278 elapsed=176.6s

  [12463/15692] intraday_6771.csv.gz  in=385,701,105 out=81,157,278 elapsed=176.6s

  [12464/15692] intraday_6773.csv.gz  in=385,712,788 out=81,157,278 elapsed=176.6s

  [12465/15692] intraday_6770.csv.gz  in=385,746,238 out=81,157,278 elapsed=176.6s

  [12466/15692] intraday_6774.csv.gz  in=385,757,995 out=81,157,278 elapsed=176.6s

  [12467/15692] intraday_6772.csv.gz  in=385,792,895 out=81,157,278 elapsed=176.6s

  [12468/15692] intraday_6775.csv.gz  in=385,804,864 out=81,157,278 elapsed=176.6s

  [12469/15692] intraday_6776.csv.gz  in=385,821,346 out=81,157,278 elapsed=176.7s

  [12470/15692] intraday_6777.csv.gz  in=385,834,461 out=81,157,278 elapsed=176.7s

  [12471/15692] intraday_6778.csv.gz  in=385,849,103 out=81,157,278 elapsed=176.7s

  [12472/15692] intraday_6780.csv.gz  in=385,860,956 out=81,157,278 elapsed=176.7s

  [12473/15692] intraday_6779.csv.gz  in=385,873,997 out=81,157,278 elapsed=176.7s

  [12474/15692] intraday_6781.csv.gz  in=385,885,708 out=81,157,278 elapsed=176.7s

  [12475/15692] intraday_6784.csv.gz  in=385,899,066 out=81,157,278 elapsed=176.7s

  [12476/15692] intraday_6783.csv.gz  in=385,911,924 out=81,157,278 elapsed=176.7s

  [12477/15692] intraday_6785.csv.gz  in=385,923,769 out=81,157,278 elapsed=176.7s

  [12478/15692] intraday_6782.csv.gz  in=385,936,914 out=81,157,278 elapsed=176.7s

  [12479/15692] intraday_6787.csv.gz  in=385,947,719 out=81,157,278 elapsed=176.8s

  [12480/15692] intraday_6786.csv.gz  in=385,961,023 out=81,157,278 elapsed=176.8s

  [12481/15692] intraday_6788.csv.gz  in=385,974,867 out=81,157,278 elapsed=176.8s

  [12482/15692] intraday_6789.csv.gz  in=385,987,011 out=81,157,278 elapsed=176.8s

  [12483/15692] intraday_6791.csv.gz  in=385,997,236 out=81,157,278 elapsed=176.8s

  [12484/15692] intraday_6792.csv.gz  in=386,008,866 out=81,157,278 elapsed=176.8s

  [12485/15692] intraday_6793.csv.gz  in=386,021,086 out=81,157,278 elapsed=176.8s

  [12486/15692] intraday_6790.csv.gz  in=386,036,200 out=81,157,278 elapsed=176.8s

  [12487/15692] intraday_6795.csv.gz  in=386,052,243 out=81,157,278 elapsed=176.8s

  [12488/15692] intraday_6796.csv.gz  in=386,067,421 out=81,157,278 elapsed=176.8s

  [12489/15692] intraday_6794.csv.gz  in=386,087,264 out=81,157,278 elapsed=176.8s

  [12490/15692] intraday_6797.csv.gz  in=386,100,482 out=81,157,278 elapsed=176.9s

  [12491/15692] intraday_6798.csv.gz  in=386,114,307 out=81,157,278 elapsed=176.9s

  [12492/15692] intraday_6799.csv.gz  in=386,128,893 out=81,157,278 elapsed=176.9s

  [12493/15692] intraday_6801.csv.gz  in=386,142,796 out=81,157,278 elapsed=176.9s

  [12494/15692] intraday_6800.csv.gz  in=386,159,183 out=81,157,278 elapsed=176.9s

  [12495/15692] intraday_6802.csv.gz  in=386,171,652 out=81,157,278 elapsed=176.9s

  [12496/15692] intraday_6803.csv.gz  in=386,188,164 out=81,157,278 elapsed=176.9s

  [12497/15692] intraday_6804.csv.gz  in=386,203,660 out=81,157,278 elapsed=176.9s

  [12498/15692] intraday_6805.csv.gz  in=386,217,300 out=81,157,278 elapsed=176.9s

  [12499/15692] intraday_6806.csv.gz  in=386,231,549 out=81,157,278 elapsed=176.9s

  [12500/15692] intraday_6808.csv.gz  in=386,244,539 out=81,157,278 elapsed=177.0s

  [12501/15692] intraday_6807.csv.gz  in=386,257,459 out=81,157,278 elapsed=177.0s

  [12502/15692] intraday_6809.csv.gz  in=386,272,577 out=81,157,278 elapsed=177.0s

  [12503/15692] intraday_6811.csv.gz  in=386,286,025 out=81,157,278 elapsed=177.0s

  [12504/15692] intraday_6810.csv.gz  in=386,300,096 out=81,157,278 elapsed=177.0s

  [12505/15692] intraday_6812.csv.gz  in=386,313,631 out=81,157,278 elapsed=177.0s

  [12506/15692] intraday_6814.csv.gz  in=386,327,670 out=81,157,278 elapsed=177.0s

  [12507/15692] intraday_6813.csv.gz  in=386,344,346 out=81,157,278 elapsed=177.0s

  [12508/15692] intraday_6816.csv.gz  in=386,356,091 out=81,157,278 elapsed=177.0s

  [12509/15692] intraday_6815.csv.gz  in=386,370,467 out=81,157,278 elapsed=177.0s

  [12510/15692] intraday_6817.csv.gz  in=386,389,182 out=81,157,278 elapsed=177.0s

  [12511/15692] intraday_6820.csv.gz  in=386,405,201 out=81,157,278 elapsed=177.1s

  [12512/15692] intraday_6819.csv.gz  in=386,418,180 out=81,157,278 elapsed=177.1s

  [12513/15692] intraday_6818.csv.gz  in=386,431,060 out=81,157,278 elapsed=177.1s

  [12514/15692] intraday_6821.csv.gz  in=386,444,523 out=81,157,278 elapsed=177.1s

  [12515/15692] intraday_6822.csv.gz  in=386,457,266 out=81,157,278 elapsed=177.1s

  [12516/15692] intraday_6824.csv.gz  in=386,470,393 out=81,157,278 elapsed=177.1s

  [12517/15692] intraday_6825.csv.gz  in=386,484,798 out=81,157,278 elapsed=177.1s

  [12518/15692] intraday_6823.csv.gz  in=386,499,228 out=81,157,278 elapsed=177.1s

  [12519/15692] intraday_6826.csv.gz  in=386,516,563 out=81,157,278 elapsed=177.1s

  [12520/15692] intraday_6828.csv.gz  in=386,530,169 out=81,157,278 elapsed=177.1s

  [12521/15692] intraday_6829.csv.gz  in=386,547,065 out=81,157,278 elapsed=177.1s

  [12522/15692] intraday_6827.csv.gz  in=386,563,279 out=81,157,278 elapsed=177.2s

  [12523/15692] intraday_6830.csv.gz  in=386,578,643 out=81,157,278 elapsed=177.2s

  [12524/15692] intraday_6831.csv.gz  in=386,591,517 out=81,157,278 elapsed=177.2s

  [12525/15692] intraday_6832.csv.gz  in=386,603,228 out=81,157,278 elapsed=177.2s

  [12526/15692] intraday_6833.csv.gz  in=386,618,011 out=81,157,278 elapsed=177.2s

  [12527/15692] intraday_6834.csv.gz  in=386,629,485 out=81,157,278 elapsed=177.2s

  [12528/15692] intraday_6835.csv.gz  in=386,646,767 out=81,157,278 elapsed=177.2s

  [12529/15692] intraday_6836.csv.gz  in=386,658,905 out=81,157,278 elapsed=177.2s

  [12530/15692] intraday_6837.csv.gz  in=386,675,896 out=81,157,278 elapsed=177.2s

  [12531/15692] intraday_6838.csv.gz  in=386,689,400 out=81,157,278 elapsed=177.2s

  [12532/15692] intraday_6840.csv.gz  in=386,702,553 out=81,157,278 elapsed=177.3s

  [12533/15692] intraday_6839.csv.gz  in=386,715,559 out=81,157,278 elapsed=177.3s

  [12534/15692] intraday_6841.csv.gz  in=386,728,097 out=81,157,278 elapsed=177.3s

  [12535/15692] intraday_6842.csv.gz  in=386,740,713 out=81,157,278 elapsed=177.3s

  [12536/15692] intraday_6844.csv.gz  in=386,756,190 out=81,157,278 elapsed=177.3s

  [12537/15692] intraday_6843.csv.gz  in=386,773,098 out=81,157,278 elapsed=177.3s

  [12538/15692] intraday_6845.csv.gz  in=386,788,128 out=81,157,278 elapsed=177.3s

  [12539/15692] intraday_6847.csv.gz  in=386,802,481 out=81,157,278 elapsed=177.3s

  [12540/15692] intraday_6848.csv.gz  in=386,813,641 out=81,157,278 elapsed=177.3s

  [12541/15692] intraday_6846.csv.gz  in=386,835,326 out=81,157,278 elapsed=177.3s

  [12542/15692] intraday_6849.csv.gz  in=386,849,750 out=81,157,278 elapsed=177.3s

  [12543/15692] intraday_6850.csv.gz  in=386,861,122 out=81,157,278 elapsed=177.4s

  [12544/15692] intraday_6852.csv.gz  in=386,870,649 out=81,157,278 elapsed=177.4s

  [12545/15692] intraday_6851.csv.gz  in=386,885,747 out=81,157,278 elapsed=177.4s

  [12546/15692] intraday_6853.csv.gz  in=386,895,969 out=81,157,278 elapsed=177.4s

  [12547/15692] intraday_6854.csv.gz  in=386,908,372 out=81,157,278 elapsed=177.4s

  [12548/15692] intraday_6858.csv.gz  in=386,919,074 out=81,157,278 elapsed=177.4s

  [12549/15692] intraday_6857.csv.gz  in=386,932,315 out=81,157,278 elapsed=177.4s

  [12550/15692] intraday_6856.csv.gz  in=386,945,326 out=81,157,278 elapsed=177.4s

  [12551/15692] intraday_6855.csv.gz  in=386,992,725 out=81,157,278 elapsed=177.5s

  [12552/15692] intraday_6859.csv.gz  in=387,006,634 out=81,157,278 elapsed=177.5s

  [12553/15692] intraday_6860.csv.gz  in=387,020,936 out=81,157,278 elapsed=177.5s

  [12554/15692] intraday_6861.csv.gz  in=387,037,352 out=81,157,278 elapsed=177.5s

  [12555/15692] intraday_6862.csv.gz  in=387,049,972 out=81,157,278 elapsed=177.5s

  [12556/15692] intraday_6863.csv.gz  in=387,062,723 out=81,157,278 elapsed=177.5s

  [12557/15692] intraday_6864.csv.gz  in=387,077,661 out=81,157,278 elapsed=177.5s

  [12558/15692] intraday_6865.csv.gz  in=387,093,152 out=81,157,278 elapsed=177.5s

  [12559/15692] intraday_6867.csv.gz  in=387,106,953 out=81,157,278 elapsed=177.5s

  [12560/15692] intraday_6866.csv.gz  in=387,121,867 out=81,157,278 elapsed=177.5s

  [12561/15692] intraday_6869.csv.gz  in=387,132,229 out=81,157,278 elapsed=177.5s

  [12562/15692] intraday_6868.csv.gz  in=387,145,689 out=81,157,278 elapsed=177.5s

  [12563/15692] intraday_6870.csv.gz  in=387,155,288 out=81,157,278 elapsed=177.6s

  [12564/15692] intraday_6873.csv.gz  in=387,165,997 out=81,157,278 elapsed=177.6s

  [12565/15692] intraday_6871.csv.gz  in=387,181,617 out=81,157,278 elapsed=177.6s

  [12566/15692] intraday_6872.csv.gz  in=387,195,804 out=81,157,278 elapsed=177.6s

  [12567/15692] intraday_6874.csv.gz  in=387,207,586 out=81,157,278 elapsed=177.6s

  [12568/15692] intraday_6875.csv.gz  in=387,220,834 out=81,157,278 elapsed=177.6s

  [12569/15692] intraday_6876.csv.gz  in=387,233,311 out=81,157,278 elapsed=177.6s

  [12570/15692] intraday_6877.csv.gz  in=387,244,356 out=81,157,278 elapsed=177.6s

  [12571/15692] intraday_6878.csv.gz  in=387,257,830 out=81,157,278 elapsed=177.6s

  [12572/15692] intraday_6879.csv.gz  in=387,271,430 out=81,157,278 elapsed=177.6s

  [12573/15692] intraday_6880.csv.gz  in=387,283,992 out=81,157,278 elapsed=177.6s

  [12574/15692] intraday_6881.csv.gz  in=387,295,978 out=81,157,278 elapsed=177.6s

  [12575/15692] intraday_6882.csv.gz  in=387,308,118 out=81,157,278 elapsed=177.6s

  [12576/15692] intraday_6883.csv.gz  in=387,320,996 out=81,157,278 elapsed=177.7s

  [12577/15692] intraday_6884.csv.gz  in=387,335,046 out=81,157,278 elapsed=177.7s

  [12578/15692] intraday_6886.csv.gz  in=387,350,355 out=81,157,278 elapsed=177.7s

  [12579/15692] intraday_6885.csv.gz  in=387,368,120 out=81,157,278 elapsed=177.7s

  [12580/15692] intraday_6887.csv.gz  in=387,378,538 out=81,157,278 elapsed=177.7s

  [12581/15692] intraday_6888.csv.gz  in=387,393,051 out=81,157,278 elapsed=177.7s

  [12582/15692] intraday_6889.csv.gz  in=387,407,936 out=81,157,278 elapsed=177.7s

  [12583/15692] intraday_6890.csv.gz  in=387,420,201 out=81,157,278 elapsed=177.7s

  [12584/15692] intraday_6891.csv.gz  in=387,433,398 out=81,157,278 elapsed=177.7s

  [12585/15692] intraday_6892.csv.gz  in=387,444,254 out=81,157,278 elapsed=177.7s

  [12586/15692] intraday_6893.csv.gz  in=387,457,778 out=81,157,278 elapsed=177.7s

  [12587/15692] intraday_6894.csv.gz  in=387,468,683 out=81,157,278 elapsed=177.8s

  [12588/15692] intraday_6895.csv.gz  in=387,479,781 out=81,157,278 elapsed=177.8s

  [12589/15692] intraday_6897.csv.gz  in=387,493,882 out=81,157,278 elapsed=177.8s

  [12590/15692] intraday_6896.csv.gz  in=387,506,191 out=81,157,278 elapsed=177.8s

  [12591/15692] intraday_6898.csv.gz  in=387,519,281 out=81,157,278 elapsed=177.8s

  [12592/15692] intraday_6899.csv.gz  in=387,532,623 out=81,157,278 elapsed=177.8s

  [12593/15692] intraday_6901.csv.gz  in=387,544,306 out=81,157,278 elapsed=177.8s

  [12594/15692] intraday_6902.csv.gz  in=387,558,450 out=81,157,278 elapsed=177.8s

  [12595/15692] intraday_6900.csv.gz  in=387,570,624 out=81,157,278 elapsed=177.8s

  [12596/15692] intraday_6903.csv.gz  in=387,582,456 out=81,157,278 elapsed=177.8s

  [12597/15692] intraday_6905.csv.gz  in=387,593,782 out=81,157,278 elapsed=177.9s

  [12598/15692] intraday_6904.csv.gz  in=387,606,664 out=81,157,278 elapsed=177.9s

  [12599/15692] intraday_6906.csv.gz  in=387,616,983 out=81,157,278 elapsed=177.9s

  [12600/15692] intraday_6907.csv.gz  in=387,633,627 out=81,157,278 elapsed=177.9s

  [12601/15692] intraday_6908.csv.gz  in=387,643,163 out=81,157,278 elapsed=177.9s

  [12602/15692] intraday_6909.csv.gz  in=387,659,959 out=81,157,278 elapsed=177.9s

  [12603/15692] intraday_6910.csv.gz  in=387,673,600 out=81,157,278 elapsed=177.9s

  [12604/15692] intraday_6911.csv.gz  in=387,687,534 out=81,157,278 elapsed=177.9s

  [12605/15692] intraday_6912.csv.gz  in=387,699,660 out=81,157,278 elapsed=177.9s

  [12606/15692] intraday_6913.csv.gz  in=387,713,404 out=81,157,278 elapsed=177.9s

  [12607/15692] intraday_6914.csv.gz  in=387,727,324 out=81,157,278 elapsed=177.9s

  [12608/15692] intraday_6917.csv.gz  in=387,738,775 out=81,157,278 elapsed=178.0s

  [12609/15692] intraday_6915.csv.gz  in=387,752,213 out=81,157,278 elapsed=178.0s

  [12610/15692] intraday_6916.csv.gz  in=387,767,161 out=81,157,278 elapsed=178.0s

  [12611/15692] intraday_6918.csv.gz  in=387,778,285 out=81,157,278 elapsed=178.0s

  [12612/15692] intraday_6919.csv.gz  in=387,789,521 out=81,157,278 elapsed=178.0s

  [12613/15692] intraday_6922.csv.gz  in=387,803,811 out=81,157,278 elapsed=178.0s

  [12614/15692] intraday_6920.csv.gz  in=387,818,895 out=81,157,278 elapsed=178.0s

  [12615/15692] intraday_6921.csv.gz  in=387,831,956 out=81,157,278 elapsed=178.0s

  [12616/15692] intraday_6923.csv.gz  in=387,844,230 out=81,157,278 elapsed=178.0s

  [12617/15692] intraday_6924.csv.gz  in=387,855,719 out=81,157,278 elapsed=178.1s

  [12618/15692] intraday_6925.csv.gz  in=387,868,684 out=81,157,278 elapsed=178.1s

  [12619/15692] intraday_6927.csv.gz  in=387,881,180 out=81,157,278 elapsed=178.1s

  [12620/15692] intraday_6926.csv.gz  in=387,893,653 out=81,157,278 elapsed=178.1s

  [12621/15692] intraday_6928.csv.gz  in=387,908,100 out=81,157,278 elapsed=178.1s

  [12622/15692] intraday_6930.csv.gz  in=387,921,065 out=81,157,278 elapsed=178.1s

  [12623/15692] intraday_6929.csv.gz  in=387,932,994 out=81,157,278 elapsed=178.1s

  [12624/15692] intraday_6931.csv.gz  in=387,944,007 out=81,157,278 elapsed=178.1s

  [12625/15692] intraday_6932.csv.gz  in=387,957,977 out=81,157,278 elapsed=178.1s

  [12626/15692] intraday_6933.csv.gz  in=387,969,999 out=81,157,278 elapsed=178.1s

  [12627/15692] intraday_6936.csv.gz  in=387,981,699 out=81,157,278 elapsed=178.1s

  [12628/15692] intraday_6935.csv.gz  in=387,991,398 out=81,157,278 elapsed=178.1s

  [12629/15692] intraday_6934.csv.gz  in=388,005,279 out=81,157,278 elapsed=178.2s

  [12630/15692] intraday_6938.csv.gz  in=388,022,002 out=81,157,278 elapsed=178.2s

  [12631/15692] intraday_6937.csv.gz  in=388,035,344 out=81,157,278 elapsed=178.2s

  [12632/15692] intraday_6939.csv.gz  in=388,050,963 out=81,157,278 elapsed=178.2s

  [12633/15692] intraday_6940.csv.gz  in=388,064,720 out=81,157,278 elapsed=178.2s

  [12634/15692] intraday_6941.csv.gz  in=388,077,737 out=81,157,278 elapsed=178.2s

  [12635/15692] intraday_6942.csv.gz  in=388,089,541 out=81,157,278 elapsed=178.2s

  [12636/15692] intraday_6943.csv.gz  in=388,103,881 out=81,157,278 elapsed=178.2s

  [12637/15692] intraday_6944.csv.gz  in=388,121,443 out=81,157,278 elapsed=178.2s

  [12638/15692] intraday_6947.csv.gz  in=388,136,899 out=81,157,278 elapsed=178.2s

  [12639/15692] intraday_6946.csv.gz  in=388,148,570 out=81,157,278 elapsed=178.3s

  [12640/15692] intraday_6945.csv.gz  in=388,180,082 out=81,157,278 elapsed=178.3s

  [12641/15692] intraday_6948.csv.gz  in=388,195,303 out=81,157,278 elapsed=178.3s

  [12642/15692] intraday_6949.csv.gz  in=388,209,782 out=81,157,278 elapsed=178.3s

  [12643/15692] intraday_6951.csv.gz  in=388,222,867 out=81,157,278 elapsed=178.3s

  [12644/15692] intraday_6950.csv.gz  in=388,236,437 out=81,157,278 elapsed=178.3s

  [12645/15692] intraday_6952.csv.gz  in=388,248,754 out=81,157,278 elapsed=178.3s

  [12646/15692] intraday_6953.csv.gz  in=388,263,024 out=81,157,278 elapsed=178.3s

  [12647/15692] intraday_6954.csv.gz  in=388,277,298 out=81,157,278 elapsed=178.3s

  [12648/15692] intraday_6955.csv.gz  in=388,288,534 out=81,157,278 elapsed=178.3s

  [12649/15692] intraday_6957.csv.gz  in=388,304,267 out=81,157,278 elapsed=178.3s

  [12650/15692] intraday_6956.csv.gz  in=388,317,387 out=81,157,278 elapsed=178.4s

  [12651/15692] intraday_6958.csv.gz  in=388,331,306 out=81,157,278 elapsed=178.4s

  [12652/15692] intraday_6959.csv.gz  in=388,345,205 out=81,157,278 elapsed=178.4s

  [12653/15692] intraday_6960.csv.gz  in=388,358,988 out=81,157,278 elapsed=178.4s

  [12654/15692] intraday_6962.csv.gz  in=388,371,621 out=81,157,278 elapsed=178.4s

  [12655/15692] intraday_6961.csv.gz  in=388,387,734 out=81,157,278 elapsed=178.4s

  [12656/15692] intraday_6964.csv.gz  in=388,403,145 out=81,157,278 elapsed=178.4s

  [12657/15692] intraday_6963.csv.gz  in=388,416,166 out=81,157,278 elapsed=178.4s

  [12658/15692] intraday_6966.csv.gz  in=388,427,133 out=81,157,278 elapsed=178.4s

  [12659/15692] intraday_6967.csv.gz  in=388,442,330 out=81,157,278 elapsed=178.4s

  [12660/15692] intraday_6965.csv.gz  in=388,456,379 out=81,157,278 elapsed=178.4s

  [12661/15692] intraday_6968.csv.gz  in=388,468,760 out=81,157,278 elapsed=178.4s

  [12662/15692] intraday_6969.csv.gz  in=388,482,743 out=81,157,278 elapsed=178.5s

  [12663/15692] intraday_6970.csv.gz  in=388,498,461 out=81,157,278 elapsed=178.5s

  [12664/15692] intraday_6971.csv.gz  in=388,514,933 out=81,157,278 elapsed=178.5s

  [12665/15692] intraday_6973.csv.gz  in=388,529,037 out=81,157,278 elapsed=178.5s

  [12666/15692] intraday_6972.csv.gz  in=388,544,248 out=81,157,278 elapsed=178.5s

  [12667/15692] intraday_6974.csv.gz  in=388,556,926 out=81,157,278 elapsed=178.5s

  [12668/15692] intraday_6976.csv.gz  in=388,567,678 out=81,157,278 elapsed=178.5s

  [12669/15692] intraday_6975.csv.gz  in=388,580,562 out=81,157,278 elapsed=178.5s

  [12670/15692] intraday_6977.csv.gz  in=388,595,598 out=81,157,278 elapsed=178.6s

  [12671/15692] intraday_6978.csv.gz  in=388,607,200 out=81,157,278 elapsed=178.6s

  [12672/15692] intraday_6979.csv.gz  in=388,620,992 out=81,157,278 elapsed=178.6s

  [12673/15692] intraday_6980.csv.gz  in=388,633,582 out=81,157,278 elapsed=178.6s

  [12674/15692] intraday_6982.csv.gz  in=388,645,858 out=81,157,278 elapsed=178.6s

  [12675/15692] intraday_6984.csv.gz  in=388,658,156 out=81,157,278 elapsed=178.6s

  [12676/15692] intraday_6981.csv.gz  in=388,673,645 out=81,157,278 elapsed=178.6s

  [12677/15692] intraday_6983.csv.gz  in=388,685,594 out=81,157,278 elapsed=178.6s

  [12678/15692] intraday_6985.csv.gz  in=388,698,968 out=81,157,278 elapsed=178.6s

  [12679/15692] intraday_6988.csv.gz  in=388,713,398 out=81,157,278 elapsed=178.6s

  [12680/15692] intraday_6986.csv.gz  in=388,724,591 out=81,157,278 elapsed=178.6s

  [12681/15692] intraday_6987.csv.gz  in=388,740,147 out=81,157,278 elapsed=178.6s

  [12682/15692] intraday_6989.csv.gz  in=388,755,068 out=81,157,278 elapsed=178.7s

  [12683/15692] intraday_6992.csv.gz  in=388,766,978 out=81,157,278 elapsed=178.7s

  [12684/15692] intraday_6991.csv.gz  in=388,778,280 out=81,157,278 elapsed=178.7s

  [12685/15692] intraday_6993.csv.gz  in=388,791,895 out=81,157,278 elapsed=178.7s

  [12686/15692] intraday_6994.csv.gz  in=388,804,278 out=81,157,278 elapsed=178.7s

  [12687/15692] intraday_6995.csv.gz  in=388,816,445 out=81,157,278 elapsed=178.7s

  [12688/15692] intraday_6996.csv.gz  in=388,826,111 out=81,157,278 elapsed=178.7s

  [12689/15692] intraday_6990.csv.gz  in=388,865,682 out=81,157,278 elapsed=178.7s

  [12690/15692] intraday_6997.csv.gz  in=388,879,038 out=81,157,278 elapsed=178.7s

  [12691/15692] intraday_6998.csv.gz  in=388,886,331 out=81,157,278 elapsed=178.7s

  [12692/15692] intraday_7000.csv.gz  in=388,898,660 out=81,157,278 elapsed=178.8s

  [12693/15692] intraday_6999.csv.gz  in=388,915,199 out=81,157,278 elapsed=178.8s

  [12694/15692] intraday_7001.csv.gz  in=388,928,776 out=81,157,278 elapsed=178.8s

  [12695/15692] intraday_7002.csv.gz  in=388,939,208 out=81,157,278 elapsed=178.8s

  [12696/15692] intraday_7003.csv.gz  in=388,952,868 out=81,157,278 elapsed=178.8s

  [12697/15692] intraday_7004.csv.gz  in=388,968,020 out=81,157,278 elapsed=178.8s

  [12698/15692] intraday_7005.csv.gz  in=388,984,876 out=81,157,278 elapsed=178.8s

  [12699/15692] intraday_7007.csv.gz  in=388,998,376 out=81,157,278 elapsed=178.8s

  [12700/15692] intraday_7006.csv.gz  in=389,010,244 out=81,157,278 elapsed=178.8s

  [12701/15692] intraday_7008.csv.gz  in=389,024,457 out=81,157,278 elapsed=178.8s

  [12702/15692] intraday_7010.csv.gz  in=389,039,692 out=81,157,278 elapsed=178.9s

  [12703/15692] intraday_7009.csv.gz  in=389,056,020 out=81,157,278 elapsed=178.9s

  [12704/15692] intraday_7012.csv.gz  in=389,069,927 out=81,157,278 elapsed=178.9s

  [12705/15692] intraday_7011.csv.gz  in=389,082,558 out=81,157,278 elapsed=178.9s

  [12706/15692] intraday_7013.csv.gz  in=389,092,044 out=81,157,278 elapsed=178.9s

  [12707/15692] intraday_7014.csv.gz  in=389,102,158 out=81,157,278 elapsed=178.9s

  [12708/15692] intraday_7015.csv.gz  in=389,117,386 out=81,157,278 elapsed=178.9s

  [12709/15692] intraday_7016.csv.gz  in=389,131,436 out=81,157,278 elapsed=178.9s

  [12710/15692] intraday_7017.csv.gz  in=389,143,541 out=81,157,278 elapsed=178.9s

  [12711/15692] intraday_7018.csv.gz  in=389,154,850 out=81,157,278 elapsed=178.9s

  [12712/15692] intraday_7019.csv.gz  in=389,167,016 out=81,157,278 elapsed=178.9s

  [12713/15692] intraday_7021.csv.gz  in=389,178,956 out=81,157,278 elapsed=179.0s

  [12714/15692] intraday_7020.csv.gz  in=389,191,615 out=81,157,278 elapsed=179.0s

  [12715/15692] intraday_7022.csv.gz  in=389,204,811 out=81,157,278 elapsed=179.0s

  [12716/15692] intraday_7023.csv.gz  in=389,218,147 out=81,157,278 elapsed=179.0s

  [12717/15692] intraday_7024.csv.gz  in=389,232,258 out=81,157,278 elapsed=179.0s

  [12718/15692] intraday_7025.csv.gz  in=389,243,804 out=81,157,278 elapsed=179.0s

  [12719/15692] intraday_7027.csv.gz  in=389,255,089 out=81,157,278 elapsed=179.0s

  [12720/15692] intraday_7026.csv.gz  in=389,268,066 out=81,157,278 elapsed=179.0s

  [12721/15692] intraday_7031.csv.gz  in=389,279,057 out=81,157,278 elapsed=179.1s

  [12722/15692] intraday_7028.csv.gz  in=389,293,610 out=81,157,278 elapsed=179.1s

  [12723/15692] intraday_7030.csv.gz  in=389,308,375 out=81,157,278 elapsed=179.1s

  [12724/15692] intraday_7029.csv.gz  in=389,326,578 out=81,157,278 elapsed=179.1s

  [12725/15692] intraday_7034.csv.gz  in=389,339,015 out=81,157,278 elapsed=179.1s

  [12726/15692] intraday_7032.csv.gz  in=389,354,703 out=81,157,278 elapsed=179.1s

  [12727/15692] intraday_7035.csv.gz  in=389,367,177 out=81,157,278 elapsed=179.1s

  [12728/15692] intraday_7033.csv.gz  in=389,382,307 out=81,157,278 elapsed=179.1s

  [12729/15692] intraday_7037.csv.gz  in=389,395,145 out=81,157,278 elapsed=179.1s

  [12730/15692] intraday_7036.csv.gz  in=389,406,729 out=81,157,278 elapsed=179.1s

  [12731/15692] intraday_7038.csv.gz  in=389,417,149 out=81,157,278 elapsed=179.1s

  [12732/15692] intraday_7039.csv.gz  in=389,428,610 out=81,157,278 elapsed=179.1s

  [12733/15692] intraday_7040.csv.gz  in=389,440,917 out=81,157,278 elapsed=179.2s

  [12734/15692] intraday_7041.csv.gz  in=389,453,672 out=81,157,278 elapsed=179.2s

  [12735/15692] intraday_7042.csv.gz  in=389,467,351 out=81,157,278 elapsed=179.2s

  [12736/15692] intraday_7043.csv.gz  in=389,480,696 out=81,157,278 elapsed=179.2s

  [12737/15692] intraday_7044.csv.gz  in=389,493,421 out=81,157,278 elapsed=179.2s

  [12738/15692] intraday_7045.csv.gz  in=389,505,676 out=81,157,278 elapsed=179.2s

  [12739/15692] intraday_7046.csv.gz  in=389,517,993 out=81,157,278 elapsed=179.2s

  [12740/15692] intraday_7047.csv.gz  in=389,531,953 out=81,157,278 elapsed=179.2s

  [12741/15692] intraday_7048.csv.gz  in=389,544,449 out=81,157,278 elapsed=179.2s

  [12742/15692] intraday_7049.csv.gz  in=389,556,018 out=81,157,278 elapsed=179.2s

  [12743/15692] intraday_7050.csv.gz  in=389,566,153 out=81,157,278 elapsed=179.2s

  [12744/15692] intraday_7051.csv.gz  in=389,581,523 out=81,157,278 elapsed=179.3s

  [12745/15692] intraday_7053.csv.gz  in=389,596,261 out=81,157,278 elapsed=179.3s

  [12746/15692] intraday_7052.csv.gz  in=389,606,168 out=81,157,278 elapsed=179.3s

  [12747/15692] intraday_7054.csv.gz  in=389,621,323 out=81,157,278 elapsed=179.3s

  [12748/15692] intraday_7055.csv.gz  in=389,634,530 out=81,157,278 elapsed=179.3s

  [12749/15692] intraday_7057.csv.gz  in=389,647,539 out=81,157,278 elapsed=179.3s

  [12750/15692] intraday_7056.csv.gz  in=389,660,435 out=81,157,278 elapsed=179.3s

  [12751/15692] intraday_7058.csv.gz  in=389,674,274 out=81,157,278 elapsed=179.3s

  [12752/15692] intraday_7059.csv.gz  in=389,688,216 out=81,157,278 elapsed=179.3s

  [12753/15692] intraday_7060.csv.gz  in=389,701,732 out=81,157,278 elapsed=179.3s

  [12754/15692] intraday_7061.csv.gz  in=389,713,834 out=81,157,278 elapsed=179.3s

  [12755/15692] intraday_7063.csv.gz  in=389,725,153 out=81,157,278 elapsed=179.4s

  [12756/15692] intraday_7062.csv.gz  in=389,736,831 out=81,157,278 elapsed=179.4s

  [12757/15692] intraday_7064.csv.gz  in=389,751,926 out=81,157,278 elapsed=179.4s

  [12758/15692] intraday_7065.csv.gz  in=389,764,864 out=81,157,278 elapsed=179.4s

  [12759/15692] intraday_7067.csv.gz  in=389,778,494 out=81,157,278 elapsed=179.4s

  [12760/15692] intraday_7066.csv.gz  in=389,792,596 out=81,157,278 elapsed=179.4s

  [12761/15692] intraday_7069.csv.gz  in=389,804,066 out=81,157,278 elapsed=179.4s

  [12762/15692] intraday_7070.csv.gz  in=389,816,938 out=81,157,278 elapsed=179.4s

  [12763/15692] intraday_7071.csv.gz  in=389,829,844 out=81,157,278 elapsed=179.4s

  [12764/15692] intraday_7068.csv.gz  in=389,850,956 out=81,157,278 elapsed=179.4s

  [12765/15692] intraday_7073.csv.gz  in=389,862,345 out=81,157,278 elapsed=179.5s

  [12766/15692] intraday_7072.csv.gz  in=389,876,872 out=81,157,278 elapsed=179.5s

  [12767/15692] intraday_7074.csv.gz  in=389,889,996 out=81,157,278 elapsed=179.5s

  [12768/15692] intraday_7075.csv.gz  in=389,900,749 out=81,157,278 elapsed=179.5s

  [12769/15692] intraday_7076.csv.gz  in=389,914,638 out=81,157,278 elapsed=179.5s

  [12770/15692] intraday_7077.csv.gz  in=389,937,299 out=81,157,278 elapsed=179.5s

  [12771/15692] intraday_7078.csv.gz  in=389,949,910 out=81,157,278 elapsed=179.5s

  [12772/15692] intraday_7079.csv.gz  in=389,965,544 out=81,157,278 elapsed=179.5s

  [12773/15692] intraday_7081.csv.gz  in=389,976,985 out=81,157,278 elapsed=179.5s

  [12774/15692] intraday_7080.csv.gz  in=389,998,881 out=81,157,278 elapsed=179.5s

  [12775/15692] intraday_7082.csv.gz  in=390,016,460 out=81,157,278 elapsed=179.6s

  [12776/15692] intraday_7085.csv.gz  in=390,028,470 out=81,157,278 elapsed=179.6s

  [12777/15692] intraday_7083.csv.gz  in=390,045,377 out=81,157,278 elapsed=179.6s

  [12778/15692] intraday_7084.csv.gz  in=390,059,782 out=81,157,278 elapsed=179.6s

  [12779/15692] intraday_7086.csv.gz  in=390,071,261 out=81,157,278 elapsed=179.6s

  [12780/15692] intraday_7087.csv.gz  in=390,086,782 out=81,157,278 elapsed=179.6s

  [12781/15692] intraday_7088.csv.gz  in=390,099,760 out=81,157,278 elapsed=179.6s

  [12782/15692] intraday_7090.csv.gz  in=390,112,644 out=81,157,278 elapsed=179.6s

  [12783/15692] intraday_7089.csv.gz  in=390,128,665 out=81,157,278 elapsed=179.6s

  [12784/15692] intraday_7093.csv.gz  in=390,141,722 out=81,157,278 elapsed=179.7s

  [12785/15692] intraday_7092.csv.gz  in=390,156,868 out=81,157,278 elapsed=179.7s

  [12786/15692] intraday_7091.csv.gz  in=390,171,476 out=81,157,278 elapsed=179.7s

  [12787/15692] intraday_7094.csv.gz  in=390,187,059 out=81,157,278 elapsed=179.7s

  [12788/15692] intraday_7096.csv.gz  in=390,200,871 out=81,157,278 elapsed=179.7s

  [12789/15692] intraday_7097.csv.gz  in=390,214,776 out=81,157,278 elapsed=179.7s

  [12790/15692] intraday_7095.csv.gz  in=390,241,018 out=81,157,278 elapsed=179.7s

  [12791/15692] intraday_7098.csv.gz  in=390,254,510 out=81,157,278 elapsed=179.7s

  [12792/15692] intraday_7099.csv.gz  in=390,266,703 out=81,157,278 elapsed=179.7s

  [12793/15692] intraday_7100.csv.gz  in=390,280,537 out=81,157,278 elapsed=179.8s

  [12794/15692] intraday_7101.csv.gz  in=390,297,476 out=81,157,278 elapsed=179.8s

  [12795/15692] intraday_7103.csv.gz  in=390,309,064 out=81,157,278 elapsed=179.8s

  [12796/15692] intraday_7102.csv.gz  in=390,324,790 out=81,157,278 elapsed=179.8s

  [12797/15692] intraday_7104.csv.gz  in=390,337,715 out=81,157,278 elapsed=179.8s

  [12798/15692] intraday_7106.csv.gz  in=390,349,547 out=81,157,278 elapsed=179.8s

  [12799/15692] intraday_7107.csv.gz  in=390,361,789 out=81,157,278 elapsed=179.8s

  [12800/15692] intraday_7105.csv.gz  in=390,379,934 out=81,157,278 elapsed=179.8s

  [12801/15692] intraday_7108.csv.gz  in=390,395,851 out=81,157,278 elapsed=179.9s

  [12802/15692] intraday_7109.csv.gz  in=390,410,908 out=81,157,278 elapsed=179.9s

  [12803/15692] intraday_7110.csv.gz  in=390,423,652 out=81,157,278 elapsed=179.9s

  [12804/15692] intraday_7111.csv.gz  in=390,436,740 out=81,157,278 elapsed=179.9s

  [12805/15692] intraday_7112.csv.gz  in=390,449,371 out=81,157,278 elapsed=179.9s

  [12806/15692] intraday_7113.csv.gz  in=390,461,323 out=81,157,278 elapsed=179.9s

  [12807/15692] intraday_7114.csv.gz  in=390,479,113 out=81,157,278 elapsed=179.9s

  [12808/15692] intraday_7115.csv.gz  in=390,493,397 out=81,157,278 elapsed=179.9s

  [12809/15692] intraday_7116.csv.gz  in=390,508,612 out=81,157,278 elapsed=179.9s

  [12810/15692] intraday_7117.csv.gz  in=390,524,768 out=81,157,278 elapsed=179.9s

  [12811/15692] intraday_7119.csv.gz  in=390,536,774 out=81,157,278 elapsed=180.0s

  [12812/15692] intraday_7118.csv.gz  in=390,550,568 out=81,157,278 elapsed=180.0s

  [12813/15692] intraday_7120.csv.gz  in=390,563,008 out=81,157,278 elapsed=180.0s

  [12814/15692] intraday_7121.csv.gz  in=390,576,269 out=81,157,278 elapsed=180.0s

  [12815/15692] intraday_7122.csv.gz  in=390,588,128 out=81,157,278 elapsed=180.0s

  [12816/15692] intraday_7125.csv.gz  in=390,602,158 out=81,157,278 elapsed=180.0s

  [12817/15692] intraday_7124.csv.gz  in=390,615,590 out=81,157,278 elapsed=180.0s

  [12818/15692] intraday_7123.csv.gz  in=390,651,062 out=81,157,278 elapsed=180.0s

  [12819/15692] intraday_7126.csv.gz  in=390,666,016 out=81,157,278 elapsed=180.0s

  [12820/15692] intraday_7127.csv.gz  in=390,678,750 out=81,157,278 elapsed=180.0s

  [12821/15692] intraday_7128.csv.gz  in=390,690,683 out=81,157,278 elapsed=180.0s

  [12822/15692] intraday_7131.csv.gz  in=390,702,989 out=81,157,278 elapsed=180.1s

  [12823/15692] intraday_7129.csv.gz  in=390,716,952 out=81,157,278 elapsed=180.1s

  [12824/15692] intraday_7130.csv.gz  in=390,729,371 out=81,157,278 elapsed=180.1s

  [12825/15692] intraday_7132.csv.gz  in=390,744,144 out=81,157,278 elapsed=180.1s

  [12826/15692] intraday_7135.csv.gz  in=390,757,940 out=81,157,278 elapsed=180.1s

  [12827/15692] intraday_7133.csv.gz  in=390,773,238 out=81,157,278 elapsed=180.1s

  [12828/15692] intraday_7134.csv.gz  in=390,787,890 out=81,157,278 elapsed=180.1s

  [12829/15692] intraday_7136.csv.gz  in=390,798,926 out=81,157,278 elapsed=180.1s

  [12830/15692] intraday_7139.csv.gz  in=390,813,936 out=81,157,278 elapsed=180.1s

  [12831/15692] intraday_7137.csv.gz  in=390,827,531 out=81,157,278 elapsed=180.1s

  [12832/15692] intraday_7138.csv.gz  in=390,839,546 out=81,157,278 elapsed=180.1s

  [12833/15692] intraday_7140.csv.gz  in=390,849,228 out=81,157,278 elapsed=180.1s

  [12834/15692] intraday_7143.csv.gz  in=390,849,869 out=81,157,278 elapsed=180.1s

  [12835/15692] intraday_7141.csv.gz  in=390,859,579 out=81,157,278 elapsed=180.2s

  [12836/15692] intraday_7142.csv.gz  in=390,873,335 out=81,157,278 elapsed=180.2s

  [12837/15692] intraday_7144.csv.gz  in=390,890,212 out=81,157,278 elapsed=180.2s

  [12838/15692] intraday_7145.csv.gz  in=390,904,703 out=81,157,278 elapsed=180.2s

  [12839/15692] intraday_7146.csv.gz  in=390,917,797 out=81,157,278 elapsed=180.2s

  [12840/15692] intraday_7147.csv.gz  in=390,929,091 out=81,157,278 elapsed=180.2s

  [12841/15692] intraday_7148.csv.gz  in=390,940,713 out=81,157,278 elapsed=180.2s

  [12842/15692] intraday_7149.csv.gz  in=390,955,279 out=81,157,278 elapsed=180.2s

  [12843/15692] intraday_7151.csv.gz  in=390,967,272 out=81,157,278 elapsed=180.2s

  [12844/15692] intraday_7150.csv.gz  in=390,982,571 out=81,157,278 elapsed=180.2s

  [12845/15692] intraday_7153.csv.gz  in=390,996,045 out=81,157,278 elapsed=180.2s

  [12846/15692] intraday_7152.csv.gz  in=391,009,268 out=81,157,278 elapsed=180.2s

  [12847/15692] intraday_7155.csv.gz  in=391,025,257 out=81,157,278 elapsed=180.3s

  [12848/15692] intraday_7154.csv.gz  in=391,045,069 out=81,157,278 elapsed=180.3s

  [12849/15692] intraday_7157.csv.gz  in=391,058,025 out=81,157,278 elapsed=180.3s

  [12850/15692] intraday_7156.csv.gz  in=391,071,002 out=81,157,278 elapsed=180.3s

  [12851/15692] intraday_7158.csv.gz  in=391,080,705 out=81,157,278 elapsed=180.3s

  [12852/15692] intraday_7159.csv.gz  in=391,089,598 out=81,157,278 elapsed=180.3s

  [12853/15692] intraday_7161.csv.gz  in=391,102,935 out=81,157,278 elapsed=180.3s

  [12854/15692] intraday_7160.csv.gz  in=391,117,864 out=81,157,278 elapsed=180.3s

  [12855/15692] intraday_7162.csv.gz  in=391,130,319 out=81,157,278 elapsed=180.3s

  [12856/15692] intraday_7163.csv.gz  in=391,140,857 out=81,157,278 elapsed=180.3s

  [12857/15692] intraday_7165.csv.gz  in=391,154,515 out=81,157,278 elapsed=180.4s

  [12858/15692] intraday_7164.csv.gz  in=391,167,422 out=81,157,278 elapsed=180.4s

  [12859/15692] intraday_7166.csv.gz  in=391,178,094 out=81,157,278 elapsed=180.4s

  [12860/15692] intraday_7167.csv.gz  in=391,190,635 out=81,157,278 elapsed=180.4s

  [12861/15692] intraday_7168.csv.gz  in=391,203,688 out=81,157,278 elapsed=180.4s

  [12862/15692] intraday_7169.csv.gz  in=391,217,085 out=81,157,278 elapsed=180.4s

  [12863/15692] intraday_7170.csv.gz  in=391,227,667 out=81,157,278 elapsed=180.4s

  [12864/15692] intraday_7171.csv.gz  in=391,242,650 out=81,157,278 elapsed=180.4s

  [12865/15692] intraday_7173.csv.gz  in=391,255,978 out=81,157,278 elapsed=180.4s

  [12866/15692] intraday_7172.csv.gz  in=391,267,275 out=81,157,278 elapsed=180.5s

  [12867/15692] intraday_7175.csv.gz  in=391,280,843 out=81,157,278 elapsed=180.5s

  [12868/15692] intraday_7174.csv.gz  in=391,297,147 out=81,157,278 elapsed=180.5s

  [12869/15692] intraday_7176.csv.gz  in=391,308,790 out=81,157,278 elapsed=180.5s

  [12870/15692] intraday_7179.csv.gz  in=391,319,858 out=81,157,278 elapsed=180.5s

  [12871/15692] intraday_7177.csv.gz  in=391,331,515 out=81,157,278 elapsed=180.5s

  [12872/15692] intraday_7178.csv.gz  in=391,345,488 out=81,157,278 elapsed=180.5s

  [12873/15692] intraday_7181.csv.gz  in=391,355,247 out=81,157,278 elapsed=180.5s

  [12874/15692] intraday_7180.csv.gz  in=391,369,526 out=81,157,278 elapsed=180.5s

  [12875/15692] intraday_7183.csv.gz  in=391,380,550 out=81,157,278 elapsed=180.5s

  [12876/15692] intraday_7185.csv.gz  in=391,392,937 out=81,157,278 elapsed=180.6s

  [12877/15692] intraday_7182.csv.gz  in=391,404,759 out=81,157,278 elapsed=180.6s

  [12878/15692] intraday_7184.csv.gz  in=391,416,081 out=81,157,278 elapsed=180.6s

  [12879/15692] intraday_7186.csv.gz  in=391,431,098 out=81,157,278 elapsed=180.6s

  [12880/15692] intraday_7187.csv.gz  in=391,442,501 out=81,157,278 elapsed=180.6s

  [12881/15692] intraday_7190.csv.gz  in=391,453,304 out=81,157,278 elapsed=180.6s

  [12882/15692] intraday_7189.csv.gz  in=391,465,956 out=81,157,278 elapsed=180.6s

  [12883/15692] intraday_7188.csv.gz  in=391,480,197 out=81,157,278 elapsed=180.6s

  [12884/15692] intraday_7191.csv.gz  in=391,493,737 out=81,157,278 elapsed=180.6s

  [12885/15692] intraday_7194.csv.gz  in=391,504,093 out=81,157,278 elapsed=180.6s

  [12886/15692] intraday_7192.csv.gz  in=391,516,265 out=81,157,278 elapsed=180.6s

  [12887/15692] intraday_7193.csv.gz  in=391,527,987 out=81,157,278 elapsed=180.7s

  [12888/15692] intraday_7195.csv.gz  in=391,539,026 out=81,157,278 elapsed=180.7s

  [12889/15692] intraday_7198.csv.gz  in=391,553,397 out=81,157,278 elapsed=180.7s

  [12890/15692] intraday_7197.csv.gz  in=391,564,719 out=81,157,278 elapsed=180.7s

  [12891/15692] intraday_7196.csv.gz  in=391,578,344 out=81,157,278 elapsed=180.7s

  [12892/15692] intraday_7200.csv.gz  in=391,591,540 out=81,157,278 elapsed=180.7s

  [12893/15692] intraday_7201.csv.gz  in=391,602,217 out=81,157,278 elapsed=180.7s

  [12894/15692] intraday_7199.csv.gz  in=391,615,965 out=81,157,278 elapsed=180.7s

  [12895/15692] intraday_7202.csv.gz  in=391,628,110 out=81,157,278 elapsed=180.7s

  [12896/15692] intraday_7204.csv.gz  in=391,641,199 out=81,157,278 elapsed=180.8s

  [12897/15692] intraday_7206.csv.gz  in=391,652,611 out=81,157,278 elapsed=180.8s

  [12898/15692] intraday_7205.csv.gz  in=391,665,390 out=81,157,278 elapsed=180.8s

  [12899/15692] intraday_7203.csv.gz  in=391,679,870 out=81,157,278 elapsed=180.8s

  [12900/15692] intraday_7207.csv.gz  in=391,689,656 out=81,157,278 elapsed=180.8s

  [12901/15692] intraday_7210.csv.gz  in=391,702,802 out=81,157,278 elapsed=180.8s

  [12902/15692] intraday_7208.csv.gz  in=391,713,575 out=81,157,278 elapsed=180.8s

  [12903/15692] intraday_7209.csv.gz  in=391,729,451 out=81,157,278 elapsed=180.8s

  [12904/15692] intraday_7211.csv.gz  in=391,742,805 out=81,157,278 elapsed=180.8s

  [12905/15692] intraday_7212.csv.gz  in=391,755,064 out=81,157,278 elapsed=180.8s

  [12906/15692] intraday_7215.csv.gz  in=391,766,780 out=81,157,278 elapsed=180.9s

  [12907/15692] intraday_7213.csv.gz  in=391,784,116 out=81,157,278 elapsed=180.9s

  [12908/15692] intraday_7214.csv.gz  in=391,796,827 out=81,157,278 elapsed=180.9s

  [12909/15692] intraday_7216.csv.gz  in=391,808,293 out=81,157,278 elapsed=180.9s

  [12910/15692] intraday_7219.csv.gz  in=391,821,872 out=81,157,278 elapsed=180.9s

  [12911/15692] intraday_7217.csv.gz  in=391,835,165 out=81,157,278 elapsed=180.9s

  [12912/15692] intraday_7218.csv.gz  in=391,846,872 out=81,157,278 elapsed=180.9s

  [12913/15692] intraday_7221.csv.gz  in=391,859,130 out=81,157,278 elapsed=180.9s

  [12914/15692] intraday_7222.csv.gz  in=391,869,759 out=81,157,278 elapsed=180.9s

  [12915/15692] intraday_7220.csv.gz  in=391,882,935 out=81,157,278 elapsed=180.9s

  [12916/15692] intraday_7223.csv.gz  in=391,896,048 out=81,157,278 elapsed=180.9s

  [12917/15692] intraday_7224.csv.gz  in=391,906,774 out=81,157,278 elapsed=181.0s

  [12918/15692] intraday_7226.csv.gz  in=391,919,682 out=81,157,278 elapsed=181.0s

  [12919/15692] intraday_7227.csv.gz  in=391,935,922 out=81,157,278 elapsed=181.0s

  [12920/15692] intraday_7225.csv.gz  in=391,947,872 out=81,157,278 elapsed=181.0s

  [12921/15692] intraday_7228.csv.gz  in=391,962,312 out=81,157,278 elapsed=181.0s

  [12922/15692] intraday_7231.csv.gz  in=391,973,793 out=81,157,278 elapsed=181.0s

  [12923/15692] intraday_7230.csv.gz  in=391,986,304 out=81,157,278 elapsed=181.0s

  [12924/15692] intraday_7229.csv.gz  in=391,999,845 out=81,157,278 elapsed=181.0s

  [12925/15692] intraday_7232.csv.gz  in=392,012,498 out=81,157,278 elapsed=181.0s

  [12926/15692] intraday_7234.csv.gz  in=392,024,266 out=81,157,278 elapsed=181.0s

  [12927/15692] intraday_7235.csv.gz  in=392,035,794 out=81,157,278 elapsed=181.1s

  [12928/15692] intraday_7233.csv.gz  in=392,052,707 out=81,157,278 elapsed=181.1s

  [12929/15692] intraday_7236.csv.gz  in=392,066,399 out=81,157,278 elapsed=181.1s

  [12930/15692] intraday_7239.csv.gz  in=392,078,789 out=81,157,278 elapsed=181.1s

  [12931/15692] intraday_7237.csv.gz  in=392,092,156 out=81,157,278 elapsed=181.1s

  [12932/15692] intraday_7238.csv.gz  in=392,105,546 out=81,157,278 elapsed=181.1s

  [12933/15692] intraday_7240.csv.gz  in=392,118,107 out=81,157,278 elapsed=181.1s

  [12934/15692] intraday_7242.csv.gz  in=392,132,505 out=81,157,278 elapsed=181.1s

  [12935/15692] intraday_7241.csv.gz  in=392,143,865 out=81,157,278 elapsed=181.1s

  [12936/15692] intraday_7244.csv.gz  in=392,154,063 out=81,157,278 elapsed=181.1s

  [12937/15692] intraday_7243.csv.gz  in=392,189,964 out=81,157,278 elapsed=181.1s

  [12938/15692] intraday_7246.csv.gz  in=392,204,399 out=81,157,278 elapsed=181.2s

  [12939/15692] intraday_7245.csv.gz  in=392,216,978 out=81,157,278 elapsed=181.2s

  [12940/15692] intraday_7247.csv.gz  in=392,229,850 out=81,157,278 elapsed=181.2s

  [12941/15692] intraday_7248.csv.gz  in=392,245,021 out=81,157,278 elapsed=181.2s

  [12942/15692] intraday_7249.csv.gz  in=392,257,497 out=81,157,278 elapsed=181.2s

  [12943/15692] intraday_7250.csv.gz  in=392,273,488 out=81,157,278 elapsed=181.2s

  [12944/15692] intraday_7251.csv.gz  in=392,286,612 out=81,157,278 elapsed=181.2s

  [12945/15692] intraday_7253.csv.gz  in=392,302,186 out=81,157,278 elapsed=181.2s

  [12946/15692] intraday_7252.csv.gz  in=392,315,214 out=81,157,278 elapsed=181.2s

  [12947/15692] intraday_7255.csv.gz  in=392,325,540 out=81,157,278 elapsed=181.2s

  [12948/15692] intraday_7254.csv.gz  in=392,340,049 out=81,157,278 elapsed=181.3s

  [12949/15692] intraday_7257.csv.gz  in=392,350,465 out=81,157,278 elapsed=181.3s

  [12950/15692] intraday_7256.csv.gz  in=392,365,552 out=81,157,278 elapsed=181.3s

  [12951/15692] intraday_7258.csv.gz  in=392,380,216 out=81,157,278 elapsed=181.3s

  [12952/15692] intraday_7259.csv.gz  in=392,396,325 out=81,157,278 elapsed=181.3s

  [12953/15692] intraday_7260.csv.gz  in=392,412,760 out=81,157,278 elapsed=181.3s

  [12954/15692] intraday_7261.csv.gz  in=392,427,299 out=81,157,278 elapsed=181.3s

  [12955/15692] intraday_7262.csv.gz  in=392,442,342 out=81,157,278 elapsed=181.3s

  [12956/15692] intraday_7264.csv.gz  in=392,453,492 out=81,157,278 elapsed=181.3s

  [12957/15692] intraday_7265.csv.gz  in=392,464,129 out=81,157,278 elapsed=181.3s

  [12958/15692] intraday_7263.csv.gz  in=392,477,671 out=81,157,278 elapsed=181.3s

  [12959/15692] intraday_7266.csv.gz  in=392,491,958 out=81,157,278 elapsed=181.4s

  [12960/15692] intraday_7268.csv.gz  in=392,505,182 out=81,157,278 elapsed=181.4s

  [12961/15692] intraday_7267.csv.gz  in=392,516,281 out=81,157,278 elapsed=181.4s

  [12962/15692] intraday_7269.csv.gz  in=392,528,753 out=81,157,278 elapsed=181.4s

  [12963/15692] intraday_7270.csv.gz  in=392,544,007 out=81,157,278 elapsed=181.4s

  [12964/15692] intraday_7271.csv.gz  in=392,556,813 out=81,157,278 elapsed=181.4s

  [12965/15692] intraday_7273.csv.gz  in=392,568,620 out=81,157,278 elapsed=181.4s

  [12966/15692] intraday_7272.csv.gz  in=392,581,118 out=81,157,278 elapsed=181.4s

  [12967/15692] intraday_7274.csv.gz  in=392,593,680 out=81,157,278 elapsed=181.4s

  [12968/15692] intraday_7275.csv.gz  in=392,605,537 out=81,157,278 elapsed=181.4s

  [12969/15692] intraday_7276.csv.gz  in=392,622,043 out=81,157,278 elapsed=181.4s

  [12970/15692] intraday_7277.csv.gz  in=392,636,105 out=81,157,278 elapsed=181.5s

  [12971/15692] intraday_7278.csv.gz  in=392,649,935 out=81,157,278 elapsed=181.5s

  [12972/15692] intraday_7279.csv.gz  in=392,664,508 out=81,157,278 elapsed=181.5s

  [12973/15692] intraday_7280.csv.gz  in=392,676,177 out=81,157,278 elapsed=181.5s

  [12974/15692] intraday_7284.csv.gz  in=392,688,837 out=81,157,278 elapsed=181.5s

  [12975/15692] intraday_7282.csv.gz  in=392,702,503 out=81,157,278 elapsed=181.5s

  [12976/15692] intraday_7283.csv.gz  in=392,714,416 out=81,157,278 elapsed=181.5s

  [12977/15692] intraday_7281.csv.gz  in=392,725,781 out=81,157,278 elapsed=181.5s

  [12978/15692] intraday_7285.csv.gz  in=392,733,677 out=81,157,278 elapsed=181.5s

  [12979/15692] intraday_7287.csv.gz  in=392,740,428 out=81,157,278 elapsed=181.5s

  [12980/15692] intraday_7288.csv.gz  in=392,756,824 out=81,157,278 elapsed=181.5s

  [12981/15692] intraday_7286.csv.gz  in=392,769,382 out=81,157,278 elapsed=181.6s

  [12982/15692] intraday_7289.csv.gz  in=392,784,724 out=81,157,278 elapsed=181.6s

  [12983/15692] intraday_7290.csv.gz  in=392,797,594 out=81,157,278 elapsed=181.6s

  [12984/15692] intraday_7292.csv.gz  in=392,809,918 out=81,157,278 elapsed=181.6s

  [12985/15692] intraday_7291.csv.gz  in=392,821,641 out=81,157,278 elapsed=181.6s

  [12986/15692] intraday_7293.csv.gz  in=392,835,835 out=81,157,278 elapsed=181.6s

  [12987/15692] intraday_7294.csv.gz  in=392,852,230 out=81,157,278 elapsed=181.6s

  [12988/15692] intraday_7295.csv.gz  in=392,863,761 out=81,157,278 elapsed=181.6s

  [12989/15692] intraday_7296.csv.gz  in=392,877,749 out=81,157,278 elapsed=181.6s

  [12990/15692] intraday_7297.csv.gz  in=392,892,352 out=81,157,278 elapsed=181.6s

  [12991/15692] intraday_7300.csv.gz  in=392,905,208 out=81,157,278 elapsed=181.7s

  [12992/15692] intraday_7298.csv.gz  in=392,921,755 out=81,157,278 elapsed=181.7s

  [12993/15692] intraday_7299.csv.gz  in=392,936,857 out=81,157,278 elapsed=181.7s

  [12994/15692] intraday_7301.csv.gz  in=392,953,830 out=81,157,278 elapsed=181.7s

  [12995/15692] intraday_7302.csv.gz  in=392,964,321 out=81,157,278 elapsed=181.7s

  [12996/15692] intraday_7305.csv.gz  in=392,977,549 out=81,157,278 elapsed=181.7s

  [12997/15692] intraday_7303.csv.gz  in=392,989,193 out=81,157,278 elapsed=181.7s

  [12998/15692] intraday_7304.csv.gz  in=393,004,296 out=81,157,278 elapsed=181.7s

  [12999/15692] intraday_7306.csv.gz  in=393,016,954 out=81,157,278 elapsed=181.7s

  [13000/15692] intraday_7308.csv.gz  in=393,029,911 out=81,157,278 elapsed=181.8s

  [13001/15692] intraday_7307.csv.gz  in=393,042,451 out=81,157,278 elapsed=181.8s

  [13002/15692] intraday_7309.csv.gz  in=393,055,462 out=81,157,278 elapsed=181.8s

  [13003/15692] intraday_7310.csv.gz  in=393,068,191 out=81,157,278 elapsed=181.8s

  [13004/15692] intraday_7311.csv.gz  in=393,080,786 out=81,157,278 elapsed=181.8s

  [13005/15692] intraday_7313.csv.gz  in=393,094,313 out=81,157,278 elapsed=181.8s

  [13006/15692] intraday_7312.csv.gz  in=393,108,017 out=81,157,278 elapsed=181.8s

  [13007/15692] intraday_7314.csv.gz  in=393,118,855 out=81,157,278 elapsed=181.8s

  [13008/15692] intraday_7315.csv.gz  in=393,131,379 out=81,157,278 elapsed=181.8s

  [13009/15692] intraday_7316.csv.gz  in=393,143,390 out=81,157,278 elapsed=181.8s

  [13010/15692] intraday_7317.csv.gz  in=393,157,585 out=81,157,278 elapsed=181.8s

  [13011/15692] intraday_7318.csv.gz  in=393,173,949 out=81,157,278 elapsed=181.8s

  [13012/15692] intraday_7320.csv.gz  in=393,183,942 out=81,157,278 elapsed=181.8s

  [13013/15692] intraday_7319.csv.gz  in=393,197,983 out=81,157,278 elapsed=181.9s

  [13014/15692] intraday_7322.csv.gz  in=393,211,980 out=81,157,278 elapsed=181.9s

  [13015/15692] intraday_7321.csv.gz  in=393,226,534 out=81,157,278 elapsed=181.9s

  [13016/15692] intraday_7323.csv.gz  in=393,239,373 out=81,157,278 elapsed=181.9s

  [13017/15692] intraday_7324.csv.gz  in=393,251,901 out=81,157,278 elapsed=181.9s

  [13018/15692] intraday_7325.csv.gz  in=393,263,510 out=81,157,278 elapsed=181.9s

  [13019/15692] intraday_7326.csv.gz  in=393,277,158 out=81,157,278 elapsed=181.9s

  [13020/15692] intraday_7328.csv.gz  in=393,288,729 out=81,157,278 elapsed=181.9s

  [13021/15692] intraday_7327.csv.gz  in=393,301,210 out=81,157,278 elapsed=181.9s

  [13022/15692] intraday_7329.csv.gz  in=393,313,789 out=81,157,278 elapsed=181.9s

  [13023/15692] intraday_7330.csv.gz  in=393,326,738 out=81,157,278 elapsed=181.9s

  [13024/15692] intraday_7331.csv.gz  in=393,341,198 out=81,157,278 elapsed=181.9s

  [13025/15692] intraday_7332.csv.gz  in=393,356,153 out=81,157,278 elapsed=181.9s

  [13026/15692] intraday_7333.csv.gz  in=393,368,272 out=81,157,278 elapsed=182.0s

  [13027/15692] intraday_7334.csv.gz  in=393,380,543 out=81,157,278 elapsed=182.0s

  [13028/15692] intraday_7335.csv.gz  in=393,394,146 out=81,157,278 elapsed=182.0s

  [13029/15692] intraday_7336.csv.gz  in=393,406,573 out=81,157,278 elapsed=182.0s

  [13030/15692] intraday_7337.csv.gz  in=393,419,302 out=81,157,278 elapsed=182.0s

  [13031/15692] intraday_7338.csv.gz  in=393,430,245 out=81,157,278 elapsed=182.0s

  [13032/15692] intraday_7339.csv.gz  in=393,442,049 out=81,157,278 elapsed=182.0s

  [13033/15692] intraday_7340.csv.gz  in=393,456,890 out=81,157,278 elapsed=182.0s

  [13034/15692] intraday_7341.csv.gz  in=393,467,100 out=81,157,278 elapsed=182.0s

  [13035/15692] intraday_7342.csv.gz  in=393,482,675 out=81,157,278 elapsed=182.0s

  [13036/15692] intraday_7343.csv.gz  in=393,495,738 out=81,157,278 elapsed=182.0s

  [13037/15692] intraday_7344.csv.gz  in=393,511,086 out=81,157,278 elapsed=182.0s

  [13038/15692] intraday_7345.csv.gz  in=393,523,136 out=81,157,278 elapsed=182.1s

  [13039/15692] intraday_7346.csv.gz  in=393,536,140 out=81,157,278 elapsed=182.1s

  [13040/15692] intraday_7347.csv.gz  in=393,549,431 out=81,157,278 elapsed=182.1s

  [13041/15692] intraday_7348.csv.gz  in=393,562,443 out=81,157,278 elapsed=182.1s

  [13042/15692] intraday_7349.csv.gz  in=393,576,425 out=81,157,278 elapsed=182.1s

  [13043/15692] intraday_7350.csv.gz  in=393,588,308 out=81,157,278 elapsed=182.1s

  [13044/15692] intraday_7351.csv.gz  in=393,599,475 out=81,157,278 elapsed=182.1s

  [13045/15692] intraday_7352.csv.gz  in=393,610,892 out=81,157,278 elapsed=182.1s

  [13046/15692] intraday_7353.csv.gz  in=393,626,112 out=81,157,278 elapsed=182.1s

  [13047/15692] intraday_7355.csv.gz  in=393,641,079 out=81,157,278 elapsed=182.1s

  [13048/15692] intraday_7354.csv.gz  in=393,654,483 out=81,157,278 elapsed=182.1s

  [13049/15692] intraday_7356.csv.gz  in=393,666,959 out=81,157,278 elapsed=182.1s

  [13050/15692] intraday_7359.csv.gz  in=393,678,982 out=81,157,278 elapsed=182.2s

  [13051/15692] intraday_7357.csv.gz  in=393,691,652 out=81,157,278 elapsed=182.2s

  [13052/15692] intraday_7358.csv.gz  in=393,702,847 out=81,157,278 elapsed=182.2s

  [13053/15692] intraday_7360.csv.gz  in=393,715,585 out=81,157,278 elapsed=182.2s

  [13054/15692] intraday_7361.csv.gz  in=393,729,532 out=81,157,278 elapsed=182.2s

  [13055/15692] intraday_7362.csv.gz  in=393,741,472 out=81,157,278 elapsed=182.2s

  [13056/15692] intraday_7363.csv.gz  in=393,753,407 out=81,157,278 elapsed=182.2s

  [13057/15692] intraday_7364.csv.gz  in=393,763,402 out=81,157,278 elapsed=182.2s

  [13058/15692] intraday_7366.csv.gz  in=393,775,171 out=81,157,278 elapsed=182.2s

  [13059/15692] intraday_7365.csv.gz  in=393,790,135 out=81,157,278 elapsed=182.2s

  [13060/15692] intraday_7367.csv.gz  in=393,802,213 out=81,157,278 elapsed=182.2s

  [13061/15692] intraday_7368.csv.gz  in=393,813,112 out=81,157,278 elapsed=182.2s

  [13062/15692] intraday_7369.csv.gz  in=393,822,680 out=81,157,278 elapsed=182.2s

  [13063/15692] intraday_7370.csv.gz  in=393,834,813 out=81,157,278 elapsed=182.2s

  [13064/15692] intraday_7371.csv.gz  in=393,852,749 out=81,157,278 elapsed=182.3s

  [13065/15692] intraday_7373.csv.gz  in=393,866,562 out=81,157,278 elapsed=182.3s

  [13066/15692] intraday_7372.csv.gz  in=393,884,341 out=81,157,278 elapsed=182.3s

  [13067/15692] intraday_7374.csv.gz  in=393,894,888 out=81,157,278 elapsed=182.3s

  [13068/15692] intraday_7375.csv.gz  in=393,907,705 out=81,157,278 elapsed=182.3s

  [13069/15692] intraday_7376.csv.gz  in=393,923,011 out=81,157,278 elapsed=182.3s

  [13070/15692] intraday_7377.csv.gz  in=393,937,097 out=81,157,278 elapsed=182.3s

  [13071/15692] intraday_7378.csv.gz  in=393,952,036 out=81,157,278 elapsed=182.3s

  [13072/15692] intraday_7379.csv.gz  in=393,966,678 out=81,157,278 elapsed=182.3s

  [13073/15692] intraday_7380.csv.gz  in=393,980,179 out=81,157,278 elapsed=182.3s

  [13074/15692] intraday_7381.csv.gz  in=393,993,907 out=81,157,278 elapsed=182.3s

  [13075/15692] intraday_7382.csv.gz  in=394,007,538 out=81,157,278 elapsed=182.3s

  [13076/15692] intraday_7384.csv.gz  in=394,018,845 out=81,157,278 elapsed=182.4s

  [13077/15692] intraday_7383.csv.gz  in=394,032,587 out=81,157,278 elapsed=182.4s

  [13078/15692] intraday_7385.csv.gz  in=394,046,350 out=81,157,278 elapsed=182.4s

  [13079/15692] intraday_7386.csv.gz  in=394,059,911 out=81,157,278 elapsed=182.4s

  [13080/15692] intraday_7387.csv.gz  in=394,073,377 out=81,157,278 elapsed=182.4s

  [13081/15692] intraday_7389.csv.gz  in=394,087,797 out=81,157,278 elapsed=182.4s

  [13082/15692] intraday_7390.csv.gz  in=394,100,537 out=81,157,278 elapsed=182.4s

  [13083/15692] intraday_7388.csv.gz  in=394,112,448 out=81,157,278 elapsed=182.4s

  [13084/15692] intraday_7391.csv.gz  in=394,128,804 out=81,157,278 elapsed=182.4s

  [13085/15692] intraday_7392.csv.gz  in=394,140,870 out=81,157,278 elapsed=182.4s

  [13086/15692] intraday_7393.csv.gz  in=394,153,515 out=81,157,278 elapsed=182.4s

  [13087/15692] intraday_7395.csv.gz  in=394,166,655 out=81,157,278 elapsed=182.4s

  [13088/15692] intraday_7394.csv.gz  in=394,183,909 out=81,157,278 elapsed=182.4s

  [13089/15692] intraday_7396.csv.gz  in=394,195,881 out=81,157,278 elapsed=182.4s

  [13090/15692] intraday_7397.csv.gz  in=394,211,930 out=81,157,278 elapsed=182.5s

  [13091/15692] intraday_7399.csv.gz  in=394,224,497 out=81,157,278 elapsed=182.5s

  [13092/15692] intraday_7398.csv.gz  in=394,240,405 out=81,157,278 elapsed=182.5s

  [13093/15692] intraday_7400.csv.gz  in=394,253,748 out=81,157,278 elapsed=182.5s

  [13094/15692] intraday_7401.csv.gz  in=394,267,433 out=81,157,278 elapsed=182.5s

  [13095/15692] intraday_7402.csv.gz  in=394,279,968 out=81,157,278 elapsed=182.5s

  [13096/15692] intraday_7404.csv.gz  in=394,294,542 out=81,157,278 elapsed=182.5s

  [13097/15692] intraday_7403.csv.gz  in=394,313,580 out=81,157,278 elapsed=182.5s

  [13098/15692] intraday_7405.csv.gz  in=394,328,816 out=81,157,278 elapsed=182.5s

  [13099/15692] intraday_7406.csv.gz  in=394,346,226 out=81,157,278 elapsed=182.5s

  [13100/15692] intraday_7408.csv.gz  in=394,359,234 out=81,157,278 elapsed=182.5s

  [13101/15692] intraday_7407.csv.gz  in=394,374,173 out=81,157,278 elapsed=182.5s

  [13102/15692] intraday_7409.csv.gz  in=394,386,321 out=81,157,278 elapsed=182.6s

  [13103/15692] intraday_7410.csv.gz  in=394,399,643 out=81,157,278 elapsed=182.6s

  [13104/15692] intraday_7411.csv.gz  in=394,411,137 out=81,157,278 elapsed=182.6s

  [13105/15692] intraday_7412.csv.gz  in=394,425,248 out=81,157,278 elapsed=182.6s

  [13106/15692] intraday_7413.csv.gz  in=394,437,939 out=81,157,278 elapsed=182.6s

  [13107/15692] intraday_7414.csv.gz  in=394,453,935 out=81,157,278 elapsed=182.6s

  [13108/15692] intraday_7415.csv.gz  in=394,468,104 out=81,157,278 elapsed=182.6s

  [13109/15692] intraday_7416.csv.gz  in=394,481,693 out=81,157,278 elapsed=182.6s

  [13110/15692] intraday_7417.csv.gz  in=394,493,499 out=81,157,278 elapsed=182.6s

  [13111/15692] intraday_7418.csv.gz  in=394,507,972 out=81,157,278 elapsed=182.7s

  [13112/15692] intraday_7419.csv.gz  in=394,520,070 out=81,157,278 elapsed=182.7s

  [13113/15692] intraday_7420.csv.gz  in=394,532,935 out=81,157,278 elapsed=182.7s

  [13114/15692] intraday_7421.csv.gz  in=394,548,746 out=81,157,278 elapsed=182.7s

  [13115/15692] intraday_7422.csv.gz  in=394,563,727 out=81,157,278 elapsed=182.7s

  [13116/15692] intraday_7424.csv.gz  in=394,578,346 out=81,157,278 elapsed=182.7s

  [13117/15692] intraday_7423.csv.gz  in=394,598,457 out=81,157,278 elapsed=182.7s

  [13118/15692] intraday_7425.csv.gz  in=394,611,438 out=81,157,278 elapsed=182.7s

  [13119/15692] intraday_7427.csv.gz  in=394,622,139 out=81,157,278 elapsed=182.7s

  [13120/15692] intraday_7426.csv.gz  in=394,635,747 out=81,157,278 elapsed=182.8s

  [13121/15692] intraday_7428.csv.gz  in=394,650,359 out=81,157,278 elapsed=182.8s

  [13122/15692] intraday_7430.csv.gz  in=394,659,621 out=81,157,278 elapsed=182.8s

  [13123/15692] intraday_7429.csv.gz  in=394,670,533 out=81,157,278 elapsed=182.8s

  [13124/15692] intraday_7432.csv.gz  in=394,672,626 out=81,157,278 elapsed=182.8s

  [13125/15692] intraday_7434.csv.gz  in=394,672,661 out=81,157,278 elapsed=182.8s

  [13126/15692] intraday_7431.csv.gz  in=394,686,180 out=81,157,278 elapsed=182.8s

  [13127/15692] intraday_7435.csv.gz  in=394,686,202 out=81,157,278 elapsed=182.8s

  [13128/15692] intraday_7433.csv.gz  in=394,686,310 out=81,157,278 elapsed=182.8s

  [13129/15692] intraday_7436.csv.gz  in=394,694,193 out=81,157,278 elapsed=182.8s

  [13130/15692] intraday_7437.csv.gz  in=394,696,705 out=81,157,278 elapsed=182.8s

  [13131/15692] intraday_7438.csv.gz  in=394,696,748 out=81,157,278 elapsed=182.8s

  [13132/15692] intraday_7439.csv.gz  in=394,698,567 out=81,157,278 elapsed=182.8s

  [13133/15692] intraday_7440.csv.gz  in=394,698,743 out=81,157,278 elapsed=182.8s

  [13134/15692] intraday_7442.csv.gz  in=394,698,877 out=81,157,278 elapsed=182.8s

  [13135/15692] intraday_7441.csv.gz  in=394,703,734 out=81,157,278 elapsed=182.8s

  [13136/15692] intraday_7443.csv.gz  in=394,704,890 out=81,157,278 elapsed=182.9s

  [13137/15692] intraday_7444.csv.gz  in=394,704,903 out=81,157,278 elapsed=182.9s

  [13138/15692] intraday_7446.csv.gz  in=394,705,005 out=81,157,278 elapsed=182.9s

  [13139/15692] intraday_7445.csv.gz  in=394,705,028 out=81,157,278 elapsed=182.9s

  [13140/15692] intraday_7447.csv.gz  in=394,705,946 out=81,157,278 elapsed=182.9s

  [13141/15692] intraday_7448.csv.gz  in=394,706,845 out=81,157,278 elapsed=182.9s

  [13142/15692] intraday_7451.csv.gz  in=394,706,890 out=81,157,278 elapsed=182.9s

  [13143/15692] intraday_7450.csv.gz  in=394,706,898 out=81,157,278 elapsed=182.9s

  [13144/15692] intraday_7449.csv.gz  in=394,707,061 out=81,157,278 elapsed=182.9s

  [13145/15692] intraday_7452.csv.gz  in=394,708,397 out=81,157,278 elapsed=182.9s

  [13146/15692] intraday_7454.csv.gz  in=394,712,682 out=81,157,278 elapsed=182.9s

  [13147/15692] intraday_7453.csv.gz  in=394,717,138 out=81,157,278 elapsed=182.9s

  [13148/15692] intraday_7455.csv.gz  in=394,717,858 out=81,157,278 elapsed=182.9s

  [13149/15692] intraday_7458.csv.gz  in=394,717,881 out=81,157,278 elapsed=182.9s

  [13150/15692] intraday_7456.csv.gz  in=394,718,198 out=81,157,278 elapsed=183.0s

  [13151/15692] intraday_7459.csv.gz  in=394,718,329 out=81,157,278 elapsed=183.0s

  [13152/15692] intraday_7457.csv.gz  in=394,722,552 out=81,157,278 elapsed=183.0s

  [13153/15692] intraday_7460.csv.gz  in=394,722,763 out=81,157,278 elapsed=183.0s

  [13154/15692] intraday_7463.csv.gz  in=394,726,245 out=81,160,760 elapsed=183.0s

  [13155/15692] intraday_7461.csv.gz  in=394,726,551 out=81,160,760 elapsed=183.0s

  [13156/15692] intraday_7466.csv.gz  in=394,729,044 out=81,163,253 elapsed=183.0s

  [13157/15692] intraday_7465.csv.gz  in=394,731,457 out=81,165,666 elapsed=183.0s

  [13158/15692] intraday_7462.csv.gz  in=394,763,200 out=81,165,666 elapsed=183.0s

  [13159/15692] intraday_7464.csv.gz  in=394,766,021 out=81,168,482 elapsed=183.0s

  [13160/15692] intraday_7469.csv.gz  in=394,770,051 out=81,172,512 elapsed=183.0s

  [13161/15692] intraday_7467.csv.gz  in=394,772,492 out=81,174,953 elapsed=183.1s

  [13162/15692] intraday_7470.csv.gz  in=394,774,731 out=81,177,192 elapsed=183.1s

  [13163/15692] intraday_7468.csv.gz  in=394,777,770 out=81,180,231 elapsed=183.1s

  [13164/15692] intraday_7471.csv.gz  in=394,780,464 out=81,182,925 elapsed=183.1s

  [13165/15692] intraday_7472.csv.gz  in=394,783,497 out=81,185,958 elapsed=183.1s

  [13166/15692] intraday_7473.csv.gz  in=394,787,765 out=81,189,923 elapsed=183.1s

  [13167/15692] intraday_7475.csv.gz  in=394,790,776 out=81,192,934 elapsed=183.1s

  [13168/15692] intraday_7476.csv.gz  in=394,793,815 out=81,195,973 elapsed=183.1s

  [13169/15692] intraday_7474.csv.gz  in=394,797,510 out=81,199,668 elapsed=183.1s

  [13170/15692] intraday_7478.csv.gz  in=394,799,598 out=81,201,756 elapsed=183.1s

  [13171/15692] intraday_7477.csv.gz  in=394,802,051 out=81,204,209 elapsed=183.1s

  [13172/15692] intraday_7479.csv.gz  in=394,805,327 out=81,207,485 elapsed=183.1s

  [13173/15692] intraday_7482.csv.gz  in=394,807,442 out=81,209,600 elapsed=183.1s

  [13174/15692] intraday_7480.csv.gz  in=394,810,118 out=81,212,276 elapsed=183.1s

  [13175/15692] intraday_7481.csv.gz  in=394,812,169 out=81,214,327 elapsed=183.2s

  [13176/15692] intraday_7483.csv.gz  in=394,814,942 out=81,217,100 elapsed=183.2s

  [13177/15692] intraday_7484.csv.gz  in=394,818,168 out=81,219,645 elapsed=183.2s

  [13178/15692] intraday_7485.csv.gz  in=394,819,860 out=81,221,337 elapsed=183.2s

  [13179/15692] intraday_7486.csv.gz  in=394,822,511 out=81,223,988 elapsed=183.2s

  [13180/15692] intraday_7487.csv.gz  in=394,824,804 out=81,226,281 elapsed=183.2s

  [13181/15692] intraday_7489.csv.gz  in=394,827,239 out=81,228,716 elapsed=183.2s

  [13182/15692] intraday_7490.csv.gz  in=394,829,821 out=81,231,298 elapsed=183.2s

  [13183/15692] intraday_7491.csv.gz  in=394,832,392 out=81,233,869 elapsed=183.2s

  [13184/15692] intraday_7488.csv.gz  in=394,835,601 out=81,236,227 elapsed=183.2s

  [13185/15692] intraday_7493.csv.gz  in=394,839,559 out=81,240,185 elapsed=183.2s

  [13186/15692] intraday_7492.csv.gz  in=394,842,799 out=81,243,425 elapsed=183.2s

  [13187/15692] intraday_7494.csv.gz  in=394,845,250 out=81,245,876 elapsed=183.3s

  [13188/15692] intraday_7495.csv.gz  in=394,846,673 out=81,247,299 elapsed=183.3s

  [13189/15692] intraday_7496.csv.gz  in=394,849,719 out=81,250,345 elapsed=183.3s

  [13190/15692] intraday_7497.csv.gz  in=394,852,180 out=81,252,806 elapsed=183.3s

  [13191/15692] intraday_7498.csv.gz  in=394,854,389 out=81,255,015 elapsed=183.3s

  [13192/15692] intraday_7499.csv.gz  in=394,856,679 out=81,257,305 elapsed=183.3s

  [13193/15692] intraday_7502.csv.gz  in=394,858,664 out=81,259,290 elapsed=183.3s

  [13194/15692] intraday_7500.csv.gz  in=394,860,850 out=81,261,476 elapsed=183.3s

  [13195/15692] intraday_7501.csv.gz  in=394,863,286 out=81,263,912 elapsed=183.3s

  [13196/15692] intraday_7503.csv.gz  in=394,865,936 out=81,266,562 elapsed=183.3s

  [13197/15692] intraday_7505.csv.gz  in=394,868,816 out=81,269,442 elapsed=183.3s

  [13198/15692] intraday_7504.csv.gz  in=394,871,190 out=81,271,816 elapsed=183.4s

  [13199/15692] intraday_7506.csv.gz  in=394,873,885 out=81,274,464 elapsed=183.4s

  [13200/15692] intraday_7508.csv.gz  in=394,876,031 out=81,276,610 elapsed=183.4s

  [13201/15692] intraday_7507.csv.gz  in=394,878,282 out=81,278,861 elapsed=183.4s

  [13202/15692] intraday_7510.csv.gz  in=394,880,479 out=81,281,058 elapsed=183.4s

  [13203/15692] intraday_7509.csv.gz  in=394,881,880 out=81,282,459 elapsed=183.4s

  [13204/15692] intraday_7511.csv.gz  in=394,883,901 out=81,284,480 elapsed=183.4s

  [13205/15692] intraday_7512.csv.gz  in=394,887,437 out=81,286,407 elapsed=183.4s

  [13206/15692] intraday_7513.csv.gz  in=394,889,436 out=81,288,188 elapsed=183.4s

  [13207/15692] intraday_7515.csv.gz  in=394,893,656 out=81,292,408 elapsed=183.4s

  [13208/15692] intraday_7516.csv.gz  in=394,896,030 out=81,294,782 elapsed=183.4s

  [13209/15692] intraday_7514.csv.gz  in=394,897,938 out=81,296,690 elapsed=183.4s

  [13210/15692] intraday_7518.csv.gz  in=394,901,823 out=81,300,575 elapsed=183.5s

  [13211/15692] intraday_7519.csv.gz  in=394,904,264 out=81,303,016 elapsed=183.5s

  [13212/15692] intraday_7517.csv.gz  in=394,911,165 out=81,308,040 elapsed=183.5s

  [13213/15692] intraday_7521.csv.gz  in=394,913,754 out=81,310,629 elapsed=183.5s

  [13214/15692] intraday_7520.csv.gz  in=394,915,398 out=81,312,273 elapsed=183.5s

  [13215/15692] intraday_7522.csv.gz  in=394,918,052 out=81,314,927 elapsed=183.5s

  [13216/15692] intraday_7523.csv.gz  in=394,919,753 out=81,316,628 elapsed=183.5s

  [13217/15692] intraday_7525.csv.gz  in=394,921,539 out=81,318,414 elapsed=183.5s

  [13218/15692] intraday_7526.csv.gz  in=394,923,196 out=81,320,071 elapsed=183.5s

  [13219/15692] intraday_7524.csv.gz  in=394,926,322 out=81,322,803 elapsed=183.5s

  [13220/15692] intraday_7527.csv.gz  in=394,928,565 out=81,324,971 elapsed=183.5s

  [13221/15692] intraday_7528.csv.gz  in=394,932,326 out=81,328,732 elapsed=183.5s

  [13222/15692] intraday_7529.csv.gz  in=394,935,939 out=81,332,345 elapsed=183.5s

  [13223/15692] intraday_7530.csv.gz  in=394,938,424 out=81,334,828 elapsed=183.6s

  [13224/15692] intraday_7531.csv.gz  in=394,941,062 out=81,337,466 elapsed=183.6s

  [13225/15692] intraday_7532.csv.gz  in=394,943,527 out=81,339,931 elapsed=183.6s

  [13226/15692] intraday_7533.csv.gz  in=394,945,961 out=81,342,365 elapsed=183.6s

  [13227/15692] intraday_7535.csv.gz  in=394,948,415 out=81,344,819 elapsed=183.6s

  [13228/15692] intraday_7536.csv.gz  in=394,951,576 out=81,347,580 elapsed=183.6s

  [13229/15692] intraday_7534.csv.gz  in=394,954,039 out=81,349,374 elapsed=183.6s

  [13230/15692] intraday_7537.csv.gz  in=394,955,988 out=81,351,323 elapsed=183.6s

  [13231/15692] intraday_7538.csv.gz  in=394,959,088 out=81,354,423 elapsed=183.6s

  [13232/15692] intraday_7539.csv.gz  in=394,961,004 out=81,356,339 elapsed=183.6s

  [13233/15692] intraday_7540.csv.gz  in=394,963,758 out=81,359,093 elapsed=183.6s

  [13234/15692] intraday_7541.csv.gz  in=394,965,862 out=81,361,195 elapsed=183.6s

  [13235/15692] intraday_7543.csv.gz  in=394,968,017 out=81,363,350 elapsed=183.7s

  [13236/15692] intraday_7542.csv.gz  in=394,970,184 out=81,365,517 elapsed=183.7s

  [13237/15692] intraday_7544.csv.gz  in=394,971,555 out=81,366,888 elapsed=183.7s

  [13238/15692] intraday_7545.csv.gz  in=394,974,330 out=81,369,663 elapsed=183.7s

  [13239/15692] intraday_7546.csv.gz  in=394,979,584 out=81,374,917 elapsed=183.7s

  [13240/15692] intraday_7547.csv.gz  in=394,985,217 out=81,380,550 elapsed=183.7s

  [13241/15692] intraday_7548.csv.gz  in=394,988,737 out=81,384,070 elapsed=183.7s

  [13242/15692] intraday_7549.csv.gz  in=394,991,345 out=81,386,678 elapsed=183.7s

  [13243/15692] intraday_7550.csv.gz  in=394,994,012 out=81,389,345 elapsed=183.7s

  [13244/15692] intraday_7551.csv.gz  in=394,998,143 out=81,393,476 elapsed=183.7s

  [13245/15692] intraday_7552.csv.gz  in=395,001,184 out=81,396,517 elapsed=183.7s

  [13246/15692] intraday_7553.csv.gz  in=395,006,002 out=81,401,335 elapsed=183.7s

  [13247/15692] intraday_7554.csv.gz  in=395,008,210 out=81,403,543 elapsed=183.7s

  [13248/15692] intraday_7555.csv.gz  in=395,010,705 out=81,406,002 elapsed=183.7s

  [13249/15692] intraday_7557.csv.gz  in=395,013,701 out=81,408,998 elapsed=183.8s

  [13250/15692] intraday_7556.csv.gz  in=395,016,815 out=81,412,112 elapsed=183.8s

  [13251/15692] intraday_7558.csv.gz  in=395,019,251 out=81,414,548 elapsed=183.8s

  [13252/15692] intraday_7560.csv.gz  in=395,021,782 out=81,417,079 elapsed=183.8s

  [13253/15692] intraday_7559.csv.gz  in=395,023,975 out=81,419,267 elapsed=183.8s

  [13254/15692] intraday_7562.csv.gz  in=395,028,204 out=81,423,496 elapsed=183.8s

  [13255/15692] intraday_7561.csv.gz  in=395,031,092 out=81,426,287 elapsed=183.8s

  [13256/15692] intraday_7563.csv.gz  in=395,032,478 out=81,427,673 elapsed=183.8s

  [13257/15692] intraday_7565.csv.gz  in=395,036,256 out=81,431,451 elapsed=183.8s

  [13258/15692] intraday_7564.csv.gz  in=395,038,440 out=81,433,635 elapsed=183.8s

  [13259/15692] intraday_7567.csv.gz  in=395,040,556 out=81,435,751 elapsed=183.8s

  [13260/15692] intraday_7566.csv.gz  in=395,045,269 out=81,440,462 elapsed=183.8s

  [13261/15692] intraday_7568.csv.gz  in=395,048,041 out=81,443,234 elapsed=183.8s

  [13262/15692] intraday_7569.csv.gz  in=395,052,532 out=81,447,725 elapsed=183.8s

  [13263/15692] intraday_7570.csv.gz  in=395,058,560 out=81,450,969 elapsed=183.8s

  [13264/15692] intraday_7571.csv.gz  in=395,060,698 out=81,453,107 elapsed=183.9s

  [13265/15692] intraday_7574.csv.gz  in=395,063,129 out=81,455,538 elapsed=183.9s

  [13266/15692] intraday_7572.csv.gz  in=395,066,650 out=81,458,447 elapsed=183.9s

  [13267/15692] intraday_7575.csv.gz  in=395,069,145 out=81,460,942 elapsed=183.9s

  [13268/15692] intraday_7573.csv.gz  in=395,073,506 out=81,465,303 elapsed=183.9s

  [13269/15692] intraday_7577.csv.gz  in=395,076,166 out=81,467,963 elapsed=183.9s

  [13270/15692] intraday_7576.csv.gz  in=395,083,684 out=81,471,054 elapsed=183.9s

  [13271/15692] intraday_7579.csv.gz  in=395,086,930 out=81,474,300 elapsed=183.9s

  [13272/15692] intraday_7578.csv.gz  in=395,093,428 out=81,480,798 elapsed=183.9s

  [13273/15692] intraday_7580.csv.gz  in=395,097,861 out=81,485,231 elapsed=183.9s

  [13274/15692] intraday_7581.csv.gz  in=395,102,225 out=81,489,595 elapsed=183.9s

  [13275/15692] intraday_7582.csv.gz  in=395,105,075 out=81,492,445 elapsed=183.9s

  [13276/15692] intraday_7584.csv.gz  in=395,107,197 out=81,494,567 elapsed=183.9s

  [13277/15692] intraday_7583.csv.gz  in=395,110,368 out=81,497,738 elapsed=183.9s

  [13278/15692] intraday_7585.csv.gz  in=395,112,763 out=81,500,133 elapsed=183.9s

  [13279/15692] intraday_7586.csv.gz  in=395,115,366 out=81,502,736 elapsed=184.0s

  [13280/15692] intraday_7587.csv.gz  in=395,117,456 out=81,504,826 elapsed=184.0s

  [13281/15692] intraday_7589.csv.gz  in=395,121,411 out=81,508,781 elapsed=184.0s

  [13282/15692] intraday_7590.csv.gz  in=395,125,757 out=81,513,127 elapsed=184.0s

  [13283/15692] intraday_7591.csv.gz  in=395,131,032 out=81,516,099 elapsed=184.0s

  [13284/15692] intraday_7592.csv.gz  in=395,132,974 out=81,518,041 elapsed=184.0s

  [13285/15692] intraday_7588.csv.gz  in=395,138,509 out=81,521,076 elapsed=184.0s

  [13286/15692] intraday_7593.csv.gz  in=395,141,648 out=81,524,214 elapsed=184.0s

  [13287/15692] intraday_7594.csv.gz  in=395,144,415 out=81,526,981 elapsed=184.0s

  [13288/15692] intraday_7596.csv.gz  in=395,147,334 out=81,529,890 elapsed=184.0s

  [13289/15692] intraday_7595.csv.gz  in=395,149,858 out=81,532,414 elapsed=184.0s

  [13290/15692] intraday_7597.csv.gz  in=395,152,660 out=81,535,216 elapsed=184.0s

  [13291/15692] intraday_7598.csv.gz  in=395,155,289 out=81,537,845 elapsed=184.0s

  [13292/15692] intraday_7599.csv.gz  in=395,157,695 out=81,540,251 elapsed=184.0s

  [13293/15692] intraday_7600.csv.gz  in=395,159,546 out=81,542,102 elapsed=184.1s

  [13294/15692] intraday_7601.csv.gz  in=395,162,694 out=81,545,250 elapsed=184.1s

  [13295/15692] intraday_7602.csv.gz  in=395,164,745 out=81,547,301 elapsed=184.1s

  [13296/15692] intraday_7603.csv.gz  in=395,167,361 out=81,549,869 elapsed=184.1s

  [13297/15692] intraday_7604.csv.gz  in=395,170,298 out=81,552,806 elapsed=184.1s

  [13298/15692] intraday_7605.csv.gz  in=395,172,291 out=81,554,799 elapsed=184.1s

  [13299/15692] intraday_7606.csv.gz  in=395,175,164 out=81,557,672 elapsed=184.1s

  [13300/15692] intraday_7608.csv.gz  in=395,175,169 out=81,557,677 elapsed=184.1s

  [13301/15692] intraday_7607.csv.gz  in=395,176,301 out=81,558,809 elapsed=184.1s

  [13302/15692] intraday_7610.csv.gz  in=395,188,979 out=81,571,487 elapsed=184.1s

  [13303/15692] intraday_7609.csv.gz  in=395,206,847 out=81,589,355 elapsed=184.2s

  [13304/15692] intraday_7611.csv.gz  in=395,220,224 out=81,602,732 elapsed=184.2s

  [13305/15692] intraday_7612.csv.gz  in=395,231,948 out=81,614,456 elapsed=184.2s

  [13306/15692] intraday_7613.csv.gz  in=395,246,783 out=81,627,792 elapsed=184.2s

  [13307/15692] intraday_7614.csv.gz  in=395,262,567 out=81,643,576 elapsed=184.2s

  [13308/15692] intraday_7615.csv.gz  in=395,276,224 out=81,657,233 elapsed=184.2s

  [13309/15692] intraday_7617.csv.gz  in=395,289,483 out=81,670,492 elapsed=184.2s

  [13310/15692] intraday_7616.csv.gz  in=395,303,163 out=81,684,172 elapsed=184.2s

  [13311/15692] intraday_7618.csv.gz  in=395,317,292 out=81,698,301 elapsed=184.3s

  [13312/15692] intraday_7619.csv.gz  in=395,331,510 out=81,712,519 elapsed=184.3s

  [13313/15692] intraday_7620.csv.gz  in=395,346,843 out=81,727,852 elapsed=184.3s

  [13314/15692] intraday_7621.csv.gz  in=395,360,124 out=81,741,133 elapsed=184.3s

  [13315/15692] intraday_7622.csv.gz  in=395,373,547 out=81,754,556 elapsed=184.3s

  [13316/15692] intraday_7623.csv.gz  in=395,384,700 out=81,765,709 elapsed=184.3s

  [13317/15692] intraday_7624.csv.gz  in=395,395,460 out=81,776,469 elapsed=184.3s

  [13318/15692] intraday_7625.csv.gz  in=395,409,781 out=81,790,790 elapsed=184.4s

  [13319/15692] intraday_7626.csv.gz  in=395,423,366 out=81,804,375 elapsed=184.4s

  [13320/15692] intraday_7627.csv.gz  in=395,435,960 out=81,816,969 elapsed=184.4s

  [13321/15692] intraday_7628.csv.gz  in=395,446,498 out=81,827,507 elapsed=184.4s

  [13322/15692] intraday_7629.csv.gz  in=395,459,831 out=81,840,840 elapsed=184.4s

  [13323/15692] intraday_7630.csv.gz  in=395,473,933 out=81,854,942 elapsed=184.4s

  [13324/15692] intraday_7631.csv.gz  in=395,485,380 out=81,866,389 elapsed=184.4s

  [13325/15692] intraday_7632.csv.gz  in=395,500,280 out=81,881,289 elapsed=184.4s

  [13326/15692] intraday_7633.csv.gz  in=395,513,959 out=81,894,968 elapsed=184.4s

  [13327/15692] intraday_7634.csv.gz  in=395,527,483 out=81,908,492 elapsed=184.5s

  [13328/15692] intraday_7635.csv.gz  in=395,541,021 out=81,922,030 elapsed=184.5s

  [13329/15692] intraday_7636.csv.gz  in=395,553,875 out=81,934,884 elapsed=184.5s

  [13330/15692] intraday_7637.csv.gz  in=395,566,387 out=81,947,396 elapsed=184.5s

  [13331/15692] intraday_7638.csv.gz  in=395,579,356 out=81,960,365 elapsed=184.5s

  [13332/15692] intraday_7639.csv.gz  in=395,594,555 out=81,975,564 elapsed=184.5s

  [13333/15692] intraday_7640.csv.gz  in=395,607,609 out=81,988,618 elapsed=184.5s

  [13334/15692] intraday_7641.csv.gz  in=395,618,763 out=81,999,772 elapsed=184.5s

  [13335/15692] intraday_7642.csv.gz  in=395,633,396 out=82,014,405 elapsed=184.6s

  [13336/15692] intraday_7643.csv.gz  in=395,647,784 out=82,028,793 elapsed=184.6s

  [13337/15692] intraday_7645.csv.gz  in=395,661,946 out=82,042,955 elapsed=184.6s

  [13338/15692] intraday_7644.csv.gz  in=395,674,388 out=82,055,397 elapsed=184.6s

  [13339/15692] intraday_7646.csv.gz  in=395,686,113 out=82,067,122 elapsed=184.6s

  [13340/15692] intraday_7647.csv.gz  in=395,698,464 out=82,079,473 elapsed=184.6s

  [13341/15692] intraday_7649.csv.gz  in=395,711,502 out=82,092,511 elapsed=184.6s

  [13342/15692] intraday_7648.csv.gz  in=395,722,066 out=82,103,075 elapsed=184.6s

  [13343/15692] intraday_7650.csv.gz  in=395,737,093 out=82,118,102 elapsed=184.6s

  [13344/15692] intraday_7652.csv.gz  in=395,749,394 out=82,130,403 elapsed=184.6s

  [13345/15692] intraday_7651.csv.gz  in=395,762,327 out=82,143,336 elapsed=184.7s

  [13346/15692] intraday_7654.csv.gz  in=395,774,997 out=82,156,006 elapsed=184.7s

  [13347/15692] intraday_7653.csv.gz  in=395,791,270 out=82,171,134 elapsed=184.7s

  [13348/15692] intraday_7655.csv.gz  in=395,804,007 out=82,183,871 elapsed=184.7s

  [13349/15692] intraday_7656.csv.gz  in=395,816,454 out=82,196,318 elapsed=184.7s

  [13350/15692] intraday_7657.csv.gz  in=395,828,825 out=82,208,689 elapsed=184.7s

  [13351/15692] intraday_7658.csv.gz  in=395,840,863 out=82,220,727 elapsed=184.7s

  [13352/15692] intraday_7660.csv.gz  in=395,854,100 out=82,233,964 elapsed=184.7s

  [13353/15692] intraday_7659.csv.gz  in=395,865,824 out=82,245,688 elapsed=184.8s

  [13354/15692] intraday_7661.csv.gz  in=395,878,507 out=82,258,371 elapsed=184.8s

  [13355/15692] intraday_7662.csv.gz  in=395,893,619 out=82,273,483 elapsed=184.8s

  [13356/15692] intraday_7664.csv.gz  in=395,906,260 out=82,286,124 elapsed=184.8s

  [13357/15692] intraday_7665.csv.gz  in=395,919,929 out=82,299,793 elapsed=184.8s

  [13358/15692] intraday_7663.csv.gz  in=395,935,070 out=82,314,934 elapsed=184.8s

  [13359/15692] intraday_7666.csv.gz  in=395,945,573 out=82,325,437 elapsed=184.8s

  [13360/15692] intraday_7667.csv.gz  in=395,959,719 out=82,339,583 elapsed=184.8s

  [13361/15692] intraday_7668.csv.gz  in=395,973,731 out=82,353,595 elapsed=184.9s

  [13362/15692] intraday_7669.csv.gz  in=395,985,656 out=82,365,520 elapsed=184.9s

  [13363/15692] intraday_7670.csv.gz  in=395,999,349 out=82,379,213 elapsed=184.9s

  [13364/15692] intraday_7671.csv.gz  in=396,011,975 out=82,391,839 elapsed=184.9s

  [13365/15692] intraday_7672.csv.gz  in=396,023,200 out=82,403,064 elapsed=184.9s

  [13366/15692] intraday_7673.csv.gz  in=396,036,305 out=82,416,169 elapsed=184.9s

  [13367/15692] intraday_7674.csv.gz  in=396,050,141 out=82,430,005 elapsed=184.9s

  [13368/15692] intraday_7675.csv.gz  in=396,065,850 out=82,445,714 elapsed=185.0s

  [13369/15692] intraday_7677.csv.gz  in=396,079,613 out=82,459,477 elapsed=185.0s

  [13370/15692] intraday_7676.csv.gz  in=396,094,916 out=82,474,780 elapsed=185.0s

  [13371/15692] intraday_7678.csv.gz  in=396,106,915 out=82,486,779 elapsed=185.0s

  [13372/15692] intraday_7679.csv.gz  in=396,118,886 out=82,498,750 elapsed=185.0s

  [13373/15692] intraday_7680.csv.gz  in=396,131,071 out=82,510,935 elapsed=185.0s

  [13374/15692] intraday_7682.csv.gz  in=396,145,124 out=82,524,988 elapsed=185.0s

  [13375/15692] intraday_7683.csv.gz  in=396,157,997 out=82,537,861 elapsed=185.1s

  [13376/15692] intraday_7684.csv.gz  in=396,168,412 out=82,548,276 elapsed=185.1s

  [13377/15692] intraday_7681.csv.gz  in=396,181,085 out=82,560,949 elapsed=185.1s

  [13378/15692] intraday_7685.csv.gz  in=396,192,832 out=82,572,696 elapsed=185.1s

  [13379/15692] intraday_7686.csv.gz  in=396,206,794 out=82,586,658 elapsed=185.1s

  [13380/15692] intraday_7687.csv.gz  in=396,217,826 out=82,597,690 elapsed=185.1s

  [13381/15692] intraday_7688.csv.gz  in=396,230,241 out=82,610,105 elapsed=185.1s

  [13382/15692] intraday_7689.csv.gz  in=396,241,145 out=82,621,009 elapsed=185.1s

  [13383/15692] intraday_7690.csv.gz  in=396,253,620 out=82,633,484 elapsed=185.1s

  [13384/15692] intraday_7692.csv.gz  in=396,271,406 out=82,651,270 elapsed=185.2s

  [13385/15692] intraday_7691.csv.gz  in=396,284,584 out=82,664,448 elapsed=185.2s

  [13386/15692] intraday_7694.csv.gz  in=396,298,264 out=82,678,128 elapsed=185.2s

  [13387/15692] intraday_7693.csv.gz  in=396,313,860 out=82,693,724 elapsed=185.2s

  [13388/15692] intraday_7695.csv.gz  in=396,325,577 out=82,705,441 elapsed=185.2s

  [13389/15692] intraday_7696.csv.gz  in=396,339,294 out=82,719,158 elapsed=185.2s

  [13390/15692] intraday_7697.csv.gz  in=396,355,806 out=82,735,670 elapsed=185.2s

  [13391/15692] intraday_7699.csv.gz  in=396,369,500 out=82,748,078 elapsed=185.3s

  [13392/15692] intraday_7698.csv.gz  in=396,386,078 out=82,764,656 elapsed=185.3s

  [13393/15692] intraday_7700.csv.gz  in=396,399,824 out=82,778,402 elapsed=185.3s

  [13394/15692] intraday_7701.csv.gz  in=396,413,713 out=82,792,245 elapsed=185.3s

  [13395/15692] intraday_7703.csv.gz  in=396,427,706 out=82,806,238 elapsed=185.3s

  [13396/15692] intraday_7702.csv.gz  in=396,441,021 out=82,819,553 elapsed=185.3s

  [13397/15692] intraday_7705.csv.gz  in=396,453,840 out=82,832,227 elapsed=185.3s

  [13398/15692] intraday_7704.csv.gz  in=396,467,402 out=82,845,789 elapsed=185.3s

  [13399/15692] intraday_7706.csv.gz  in=396,480,106 out=82,858,493 elapsed=185.4s

  [13400/15692] intraday_7708.csv.gz  in=396,493,884 out=82,872,271 elapsed=185.4s

  [13401/15692] intraday_7707.csv.gz  in=396,507,660 out=82,886,047 elapsed=185.4s

  [13402/15692] intraday_7710.csv.gz  in=396,520,523 out=82,898,910 elapsed=185.4s

  [13403/15692] intraday_7709.csv.gz  in=396,530,946 out=82,909,333 elapsed=185.4s

  [13404/15692] intraday_7711.csv.gz  in=396,546,739 out=82,925,126 elapsed=185.4s

  [13405/15692] intraday_7714.csv.gz  in=396,558,912 out=82,937,299 elapsed=185.4s

  [13406/15692] intraday_7712.csv.gz  in=396,572,743 out=82,951,130 elapsed=185.4s

  [13407/15692] intraday_7713.csv.gz  in=396,586,955 out=82,965,342 elapsed=185.5s

  [13408/15692] intraday_7716.csv.gz  in=396,601,190 out=82,979,577 elapsed=185.5s

  [13409/15692] intraday_7717.csv.gz  in=396,615,644 out=82,994,031 elapsed=185.5s

  [13410/15692] intraday_7718.csv.gz  in=396,630,721 out=83,009,108 elapsed=185.5s

  [13411/15692] intraday_7715.csv.gz  in=396,647,214 out=83,025,601 elapsed=185.5s

  [13412/15692] intraday_7719.csv.gz  in=396,661,545 out=83,039,932 elapsed=185.5s

  [13413/15692] intraday_7720.csv.gz  in=396,672,817 out=83,051,204 elapsed=185.5s

  [13414/15692] intraday_7722.csv.gz  in=396,685,995 out=83,064,382 elapsed=185.6s

  [13415/15692] intraday_7721.csv.gz  in=396,700,908 out=83,079,295 elapsed=185.6s

  [13416/15692] intraday_7723.csv.gz  in=396,714,522 out=83,092,909 elapsed=185.6s

  [13417/15692] intraday_7724.csv.gz  in=396,731,651 out=83,110,038 elapsed=185.6s

  [13418/15692] intraday_7725.csv.gz  in=396,747,375 out=83,125,762 elapsed=185.6s

  [13419/15692] intraday_7726.csv.gz  in=396,762,960 out=83,141,347 elapsed=185.6s

  [13420/15692] intraday_7728.csv.gz  in=396,774,991 out=83,153,257 elapsed=185.7s

  [13421/15692] intraday_7729.csv.gz  in=396,789,326 out=83,167,592 elapsed=185.7s

  [13422/15692] intraday_7727.csv.gz  in=396,804,488 out=83,182,754 elapsed=185.7s

  [13423/15692] intraday_7731.csv.gz  in=396,819,931 out=83,198,197 elapsed=185.7s

  [13424/15692] intraday_7730.csv.gz  in=396,831,447 out=83,209,713 elapsed=185.7s

  [13425/15692] intraday_7732.csv.gz  in=396,842,331 out=83,220,597 elapsed=185.7s

  [13426/15692] intraday_7734.csv.gz  in=396,855,296 out=83,233,562 elapsed=185.7s

  [13427/15692] intraday_7735.csv.gz  in=396,870,906 out=83,249,172 elapsed=185.8s

  [13428/15692] intraday_7733.csv.gz  in=396,886,083 out=83,264,349 elapsed=185.8s

  [13429/15692] intraday_7736.csv.gz  in=396,897,902 out=83,276,168 elapsed=185.8s

  [13430/15692] intraday_7737.csv.gz  in=396,911,572 out=83,289,838 elapsed=185.8s

  [13431/15692] intraday_7738.csv.gz  in=396,924,922 out=83,303,188 elapsed=185.8s

  [13432/15692] intraday_7739.csv.gz  in=396,936,909 out=83,315,175 elapsed=185.8s

  [13433/15692] intraday_7740.csv.gz  in=396,949,978 out=83,328,244 elapsed=185.8s

  [13434/15692] intraday_7741.csv.gz  in=396,964,830 out=83,343,096 elapsed=185.8s

  [13435/15692] intraday_7742.csv.gz  in=396,979,571 out=83,357,837 elapsed=185.9s

  [13436/15692] intraday_7743.csv.gz  in=396,994,334 out=83,372,600 elapsed=185.9s

  [13437/15692] intraday_7744.csv.gz  in=397,008,759 out=83,387,025 elapsed=185.9s

  [13438/15692] intraday_7745.csv.gz  in=397,020,470 out=83,398,736 elapsed=185.9s

  [13439/15692] intraday_7746.csv.gz  in=397,032,712 out=83,410,978 elapsed=185.9s

  [13440/15692] intraday_7747.csv.gz  in=397,047,085 out=83,425,351 elapsed=185.9s

  [13441/15692] intraday_7749.csv.gz  in=397,059,611 out=83,437,877 elapsed=185.9s

  [13442/15692] intraday_7748.csv.gz  in=397,072,412 out=83,450,678 elapsed=185.9s

  [13443/15692] intraday_7750.csv.gz  in=397,081,654 out=83,459,920 elapsed=186.0s

  [13444/15692] intraday_7751.csv.gz  in=397,094,146 out=83,472,412 elapsed=186.0s

  [13445/15692] intraday_7752.csv.gz  in=397,102,614 out=83,480,880 elapsed=186.0s

  [13446/15692] intraday_7754.csv.gz  in=397,116,156 out=83,494,422 elapsed=186.0s

  [13447/15692] intraday_7753.csv.gz  in=397,131,899 out=83,510,165 elapsed=186.0s

  [13448/15692] intraday_7756.csv.gz  in=397,145,039 out=83,523,305 elapsed=186.0s

  [13449/15692] intraday_7755.csv.gz  in=397,157,194 out=83,535,460 elapsed=186.0s

  [13450/15692] intraday_7757.csv.gz  in=397,168,420 out=83,546,686 elapsed=186.0s

  [13451/15692] intraday_7758.csv.gz  in=397,182,411 out=83,560,677 elapsed=186.0s

  [13452/15692] intraday_7760.csv.gz  in=397,193,198 out=83,571,464 elapsed=186.1s

  [13453/15692] intraday_7761.csv.gz  in=397,206,504 out=83,584,770 elapsed=186.1s

  [13454/15692] intraday_7759.csv.gz  in=397,223,870 out=83,602,136 elapsed=186.1s

  [13455/15692] intraday_7763.csv.gz  in=397,238,820 out=83,617,086 elapsed=186.1s

  [13456/15692] intraday_7762.csv.gz  in=397,252,566 out=83,630,806 elapsed=186.1s

  [13457/15692] intraday_7764.csv.gz  in=397,264,437 out=83,642,677 elapsed=186.1s

  [13458/15692] intraday_7767.csv.gz  in=397,274,561 out=83,652,801 elapsed=186.1s

  [13459/15692] intraday_7765.csv.gz  in=397,288,565 out=83,666,805 elapsed=186.2s

  [13460/15692] intraday_7766.csv.gz  in=397,301,527 out=83,679,767 elapsed=186.2s

  [13461/15692] intraday_7768.csv.gz  in=397,313,923 out=83,692,163 elapsed=186.2s

  [13462/15692] intraday_7769.csv.gz  in=397,328,304 out=83,706,544 elapsed=186.2s

  [13463/15692] intraday_7770.csv.gz  in=397,342,554 out=83,720,794 elapsed=186.2s

  [13464/15692] intraday_7771.csv.gz  in=397,353,367 out=83,731,607 elapsed=186.2s

  [13465/15692] intraday_7772.csv.gz  in=397,365,542 out=83,743,782 elapsed=186.2s

  [13466/15692] intraday_7773.csv.gz  in=397,377,464 out=83,755,704 elapsed=186.2s

  [13467/15692] intraday_7774.csv.gz  in=397,390,737 out=83,768,977 elapsed=186.3s

  [13468/15692] intraday_7775.csv.gz  in=397,401,945 out=83,780,185 elapsed=186.3s

  [13469/15692] intraday_7776.csv.gz  in=397,417,186 out=83,795,426 elapsed=186.3s

  [13470/15692] intraday_7777.csv.gz  in=397,430,168 out=83,808,408 elapsed=186.3s

  [13471/15692] intraday_7778.csv.gz  in=397,446,419 out=83,824,659 elapsed=186.3s

  [13472/15692] intraday_7779.csv.gz  in=397,458,007 out=83,836,247 elapsed=186.3s

  [13473/15692] intraday_7780.csv.gz  in=397,470,966 out=83,849,206 elapsed=186.3s

  [13474/15692] intraday_7781.csv.gz  in=397,484,211 out=83,861,934 elapsed=186.3s

  [13475/15692] intraday_7782.csv.gz  in=397,496,586 out=83,874,309 elapsed=186.4s

  [13476/15692] intraday_7783.csv.gz  in=397,512,520 out=83,890,243 elapsed=186.4s

  [13477/15692] intraday_7785.csv.gz  in=397,523,014 out=83,900,737 elapsed=186.4s

  [13478/15692] intraday_7784.csv.gz  in=397,536,464 out=83,914,187 elapsed=186.4s

  [13479/15692] intraday_7786.csv.gz  in=397,549,477 out=83,927,200 elapsed=186.4s

  [13480/15692] intraday_7787.csv.gz  in=397,563,325 out=83,941,048 elapsed=186.4s

  [13481/15692] intraday_7788.csv.gz  in=397,575,875 out=83,953,598 elapsed=186.4s

  [13482/15692] intraday_7789.csv.gz  in=397,589,795 out=83,967,518 elapsed=186.4s

  [13483/15692] intraday_7791.csv.gz  in=397,602,472 out=83,980,195 elapsed=186.5s

  [13484/15692] intraday_7790.csv.gz  in=397,614,608 out=83,992,331 elapsed=186.5s

  [13485/15692] intraday_7793.csv.gz  in=397,626,769 out=84,004,492 elapsed=186.5s

  [13486/15692] intraday_7792.csv.gz  in=397,637,866 out=84,015,589 elapsed=186.5s

  [13487/15692] intraday_7794.csv.gz  in=397,651,757 out=84,027,919 elapsed=186.5s

  [13488/15692] intraday_7796.csv.gz  in=397,662,578 out=84,038,740 elapsed=186.5s

  [13489/15692] intraday_7795.csv.gz  in=397,676,741 out=84,052,903 elapsed=186.5s

  [13490/15692] intraday_7797.csv.gz  in=397,692,452 out=84,068,614 elapsed=186.6s

  [13491/15692] intraday_7798.csv.gz  in=397,704,314 out=84,080,476 elapsed=186.6s

  [13492/15692] intraday_7799.csv.gz  in=397,716,434 out=84,092,596 elapsed=186.6s

  [13493/15692] intraday_7800.csv.gz  in=397,730,162 out=84,106,324 elapsed=186.6s

  [13494/15692] intraday_7801.csv.gz  in=397,741,365 out=84,117,527 elapsed=186.6s

  [13495/15692] intraday_7802.csv.gz  in=397,753,397 out=84,129,559 elapsed=186.6s

  [13496/15692] intraday_7803.csv.gz  in=397,765,269 out=84,141,431 elapsed=186.7s

  [13497/15692] intraday_7804.csv.gz  in=397,776,714 out=84,152,876 elapsed=186.7s

  [13498/15692] intraday_7806.csv.gz  in=397,790,191 out=84,166,353 elapsed=186.7s

  [13499/15692] intraday_7807.csv.gz  in=397,804,023 out=84,180,185 elapsed=186.7s

  [13500/15692] intraday_7808.csv.gz  in=397,817,949 out=84,194,111 elapsed=186.7s

  [13501/15692] intraday_7805.csv.gz  in=397,832,836 out=84,208,998 elapsed=186.7s

  [13502/15692] intraday_7809.csv.gz  in=397,846,124 out=84,221,512 elapsed=186.8s

  [13503/15692] intraday_7810.csv.gz  in=397,858,237 out=84,233,625 elapsed=186.8s

  [13504/15692] intraday_7811.csv.gz  in=397,873,221 out=84,248,609 elapsed=186.8s

  [13505/15692] intraday_7812.csv.gz  in=397,884,992 out=84,260,380 elapsed=186.8s

  [13506/15692] intraday_7813.csv.gz  in=397,900,429 out=84,275,695 elapsed=186.8s

  [13507/15692] intraday_7814.csv.gz  in=397,913,491 out=84,288,757 elapsed=186.8s

  [13508/15692] intraday_7815.csv.gz  in=397,924,777 out=84,300,043 elapsed=186.8s

  [13509/15692] intraday_7816.csv.gz  in=397,936,969 out=84,312,235 elapsed=186.8s

  [13510/15692] intraday_7817.csv.gz  in=397,947,828 out=84,323,094 elapsed=186.8s

  [13511/15692] intraday_7818.csv.gz  in=397,961,596 out=84,336,862 elapsed=186.9s

  [13512/15692] intraday_7819.csv.gz  in=397,976,294 out=84,351,560 elapsed=186.9s

  [13513/15692] intraday_7820.csv.gz  in=397,991,556 out=84,366,822 elapsed=186.9s

  [13514/15692] intraday_7821.csv.gz  in=398,004,306 out=84,379,572 elapsed=186.9s

  [13515/15692] intraday_7822.csv.gz  in=398,015,881 out=84,391,147 elapsed=186.9s

  [13516/15692] intraday_7823.csv.gz  in=398,028,402 out=84,403,668 elapsed=186.9s

  [13517/15692] intraday_7824.csv.gz  in=398,040,004 out=84,415,270 elapsed=186.9s

  [13518/15692] intraday_7825.csv.gz  in=398,053,371 out=84,428,637 elapsed=186.9s

  [13519/15692] intraday_7826.csv.gz  in=398,067,210 out=84,442,476 elapsed=187.0s

  [13520/15692] intraday_7827.csv.gz  in=398,078,816 out=84,454,082 elapsed=187.0s

  [13521/15692] intraday_7828.csv.gz  in=398,090,581 out=84,465,847 elapsed=187.0s

  [13522/15692] intraday_7829.csv.gz  in=398,101,683 out=84,476,949 elapsed=187.0s

  [13523/15692] intraday_7830.csv.gz  in=398,114,874 out=84,490,140 elapsed=187.0s

  [13524/15692] intraday_7831.csv.gz  in=398,125,510 out=84,500,776 elapsed=187.0s

  [13525/15692] intraday_7832.csv.gz  in=398,137,259 out=84,512,525 elapsed=187.0s

  [13526/15692] intraday_7833.csv.gz  in=398,148,028 out=84,523,294 elapsed=187.0s

  [13527/15692] intraday_7834.csv.gz  in=398,161,275 out=84,533,615 elapsed=187.1s

  [13528/15692] intraday_7835.csv.gz  in=398,173,416 out=84,545,756 elapsed=187.1s

  [13529/15692] intraday_7837.csv.gz  in=398,189,768 out=84,562,108 elapsed=187.1s

  [13530/15692] intraday_7836.csv.gz  in=398,208,539 out=84,580,879 elapsed=187.1s

  [13531/15692] intraday_7838.csv.gz  in=398,221,475 out=84,593,815 elapsed=187.1s

  [13532/15692] intraday_7839.csv.gz  in=398,233,311 out=84,605,651 elapsed=187.1s

  [13533/15692] intraday_7840.csv.gz  in=398,244,772 out=84,617,112 elapsed=187.1s

  [13534/15692] intraday_7843.csv.gz  in=398,260,060 out=84,632,400 elapsed=187.1s

  [13535/15692] intraday_7842.csv.gz  in=398,274,423 out=84,646,763 elapsed=187.1s

  [13536/15692] intraday_7841.csv.gz  in=398,290,415 out=84,661,968 elapsed=187.1s

  [13537/15692] intraday_7844.csv.gz  in=398,302,136 out=84,673,689 elapsed=187.2s

  [13538/15692] intraday_7845.csv.gz  in=398,317,072 out=84,688,625 elapsed=187.2s

  [13539/15692] intraday_7846.csv.gz  in=398,331,888 out=84,703,441 elapsed=187.2s

  [13540/15692] intraday_7847.csv.gz  in=398,343,932 out=84,715,485 elapsed=187.2s

  [13541/15692] intraday_7848.csv.gz  in=398,358,743 out=84,730,296 elapsed=187.2s

  [13542/15692] intraday_7849.csv.gz  in=398,370,446 out=84,741,999 elapsed=187.2s

  [13543/15692] intraday_7851.csv.gz  in=398,383,670 out=84,755,223 elapsed=187.2s

  [13544/15692] intraday_7850.csv.gz  in=398,396,373 out=84,767,926 elapsed=187.3s

  [13545/15692] intraday_7852.csv.gz  in=398,408,913 out=84,780,466 elapsed=187.3s

  [13546/15692] intraday_7853.csv.gz  in=398,420,706 out=84,792,259 elapsed=187.3s

  [13547/15692] intraday_7854.csv.gz  in=398,435,501 out=84,807,054 elapsed=187.3s

  [13548/15692] intraday_7857.csv.gz  in=398,447,082 out=84,818,635 elapsed=187.3s

  [13549/15692] intraday_7856.csv.gz  in=398,463,513 out=84,835,066 elapsed=187.3s

  [13550/15692] intraday_7858.csv.gz  in=398,475,895 out=84,847,448 elapsed=187.3s

  [13551/15692] intraday_7855.csv.gz  in=398,487,862 out=84,859,415 elapsed=187.3s

  [13552/15692] intraday_7859.csv.gz  in=398,504,621 out=84,876,174 elapsed=187.4s

  [13553/15692] intraday_7860.csv.gz  in=398,519,804 out=84,888,835 elapsed=187.4s

  [13554/15692] intraday_7862.csv.gz  in=398,535,552 out=84,904,583 elapsed=187.4s

  [13555/15692] intraday_7861.csv.gz  in=398,547,803 out=84,916,834 elapsed=187.4s

  [13556/15692] intraday_7864.csv.gz  in=398,558,005 out=84,927,036 elapsed=187.4s

  [13557/15692] intraday_7863.csv.gz  in=398,572,636 out=84,941,667 elapsed=187.4s

  [13558/15692] intraday_7866.csv.gz  in=398,585,959 out=84,954,990 elapsed=187.4s

  [13559/15692] intraday_7865.csv.gz  in=398,599,370 out=84,968,401 elapsed=187.4s

  [13560/15692] intraday_7867.csv.gz  in=398,614,041 out=84,983,072 elapsed=187.4s

  [13561/15692] intraday_7868.csv.gz  in=398,633,649 out=85,002,680 elapsed=187.5s

  [13562/15692] intraday_7869.csv.gz  in=398,649,376 out=85,018,407 elapsed=187.5s

  [13563/15692] intraday_7871.csv.gz  in=398,666,232 out=85,035,263 elapsed=187.5s

  [13564/15692] intraday_7870.csv.gz  in=398,679,290 out=85,048,321 elapsed=187.5s

  [13565/15692] intraday_7872.csv.gz  in=398,692,681 out=85,061,712 elapsed=187.5s

  [13566/15692] intraday_7873.csv.gz  in=398,704,524 out=85,073,555 elapsed=187.5s

  [13567/15692] intraday_7874.csv.gz  in=398,716,898 out=85,085,929 elapsed=187.5s

  [13568/15692] intraday_7875.csv.gz  in=398,730,912 out=85,099,943 elapsed=187.5s

  [13569/15692] intraday_7876.csv.gz  in=398,742,296 out=85,111,327 elapsed=187.6s

  [13570/15692] intraday_7877.csv.gz  in=398,756,353 out=85,125,384 elapsed=187.6s

  [13571/15692] intraday_7879.csv.gz  in=398,770,077 out=85,139,108 elapsed=187.6s

  [13572/15692] intraday_7878.csv.gz  in=398,782,514 out=85,151,545 elapsed=187.6s

  [13573/15692] intraday_7880.csv.gz  in=398,797,429 out=85,166,460 elapsed=187.6s

  [13574/15692] intraday_7881.csv.gz  in=398,809,013 out=85,178,044 elapsed=187.6s

  [13575/15692] intraday_7883.csv.gz  in=398,821,742 out=85,190,773 elapsed=187.6s

  [13576/15692] intraday_7882.csv.gz  in=398,835,645 out=85,204,676 elapsed=187.7s

  [13577/15692] intraday_7885.csv.gz  in=398,848,094 out=85,217,125 elapsed=187.7s

  [13578/15692] intraday_7884.csv.gz  in=398,860,539 out=85,229,570 elapsed=187.7s

  [13579/15692] intraday_7886.csv.gz  in=398,875,705 out=85,244,736 elapsed=187.7s

  [13580/15692] intraday_7887.csv.gz  in=398,889,357 out=85,258,388 elapsed=187.7s

  [13581/15692] intraday_7888.csv.gz  in=398,901,571 out=85,270,602 elapsed=187.7s

  [13582/15692] intraday_7892.csv.gz  in=398,912,923 out=85,281,954 elapsed=187.8s

  [13583/15692] intraday_7890.csv.gz  in=398,924,249 out=85,293,280 elapsed=187.8s

  [13584/15692] intraday_7891.csv.gz  in=398,937,406 out=85,306,437 elapsed=187.8s

  [13585/15692] intraday_7889.csv.gz  in=398,952,353 out=85,321,384 elapsed=187.8s

  [13586/15692] intraday_7894.csv.gz  in=398,962,597 out=85,331,628 elapsed=187.8s

  [13587/15692] intraday_7893.csv.gz  in=398,976,992 out=85,346,023 elapsed=187.8s

  [13588/15692] intraday_7897.csv.gz  in=398,978,653 out=85,347,684 elapsed=187.8s

  [13589/15692] intraday_7895.csv.gz  in=398,989,298 out=85,358,329 elapsed=187.8s

  [13590/15692] intraday_7896.csv.gz  in=399,003,035 out=85,372,066 elapsed=187.8s

  [13591/15692] intraday_7898.csv.gz  in=399,019,968 out=85,378,006 elapsed=187.9s

  [13592/15692] intraday_7899.csv.gz  in=399,036,128 out=85,394,166 elapsed=187.9s

  [13593/15692] intraday_7901.csv.gz  in=399,049,384 out=85,407,422 elapsed=187.9s

  [13594/15692] intraday_7903.csv.gz  in=399,059,973 out=85,418,011 elapsed=187.9s

  [13595/15692] intraday_7902.csv.gz  in=399,071,404 out=85,429,442 elapsed=187.9s

  [13596/15692] intraday_7900.csv.gz  in=399,086,783 out=85,443,231 elapsed=187.9s

  [13597/15692] intraday_7906.csv.gz  in=399,098,415 out=85,454,863 elapsed=188.0s

  [13598/15692] intraday_7904.csv.gz  in=399,112,668 out=85,469,116 elapsed=188.0s

  [13599/15692] intraday_7907.csv.gz  in=399,126,445 out=85,482,893 elapsed=188.0s

  [13600/15692] intraday_7905.csv.gz  in=399,142,069 out=85,498,517 elapsed=188.0s

  [13601/15692] intraday_7908.csv.gz  in=399,156,073 out=85,512,521 elapsed=188.0s

  [13602/15692] intraday_7909.csv.gz  in=399,171,478 out=85,527,926 elapsed=188.0s

  [13603/15692] intraday_7911.csv.gz  in=399,184,995 out=85,541,443 elapsed=188.0s

  [13604/15692] intraday_7910.csv.gz  in=399,197,891 out=85,554,339 elapsed=188.0s

  [13605/15692] intraday_7912.csv.gz  in=399,213,217 out=85,569,665 elapsed=188.0s

  [13606/15692] intraday_7914.csv.gz  in=399,223,154 out=85,579,602 elapsed=188.1s

  [13607/15692] intraday_7913.csv.gz  in=399,234,266 out=85,590,714 elapsed=188.1s

  [13608/15692] intraday_7916.csv.gz  in=399,247,437 out=85,603,885 elapsed=188.1s

  [13609/15692] intraday_7917.csv.gz  in=399,258,243 out=85,614,691 elapsed=188.1s

  [13610/15692] intraday_7915.csv.gz  in=399,272,505 out=85,628,953 elapsed=188.1s

  [13611/15692] intraday_7918.csv.gz  in=399,283,937 out=85,640,385 elapsed=188.1s

  [13612/15692] intraday_7919.csv.gz  in=399,295,050 out=85,651,498 elapsed=188.1s

  [13613/15692] intraday_7921.csv.gz  in=399,307,160 out=85,663,608 elapsed=188.1s

  [13614/15692] intraday_7920.csv.gz  in=399,320,970 out=85,677,418 elapsed=188.2s

  [13615/15692] intraday_7922.csv.gz  in=399,335,687 out=85,692,135 elapsed=188.2s

  [13616/15692] intraday_7923.csv.gz  in=399,349,978 out=85,706,426 elapsed=188.2s

  [13617/15692] intraday_7925.csv.gz  in=399,363,292 out=85,719,740 elapsed=188.2s

  [13618/15692] intraday_7924.csv.gz  in=399,377,053 out=85,733,501 elapsed=188.2s

  [13619/15692] intraday_7926.csv.gz  in=399,388,503 out=85,744,951 elapsed=188.2s

  [13620/15692] intraday_7927.csv.gz  in=399,400,633 out=85,757,081 elapsed=188.2s

  [13621/15692] intraday_7928.csv.gz  in=399,414,884 out=85,771,332 elapsed=188.3s

  [13622/15692] intraday_7930.csv.gz  in=399,427,927 out=85,784,375 elapsed=188.3s

  [13623/15692] intraday_7929.csv.gz  in=399,443,852 out=85,800,300 elapsed=188.3s

  [13624/15692] intraday_7931.csv.gz  in=399,453,664 out=85,810,112 elapsed=188.3s

  [13625/15692] intraday_7932.csv.gz  in=399,468,153 out=85,824,601 elapsed=188.3s

  [13626/15692] intraday_7933.csv.gz  in=399,482,087 out=85,838,535 elapsed=188.3s

  [13627/15692] intraday_7934.csv.gz  in=399,493,816 out=85,850,264 elapsed=188.3s

  [13628/15692] intraday_7935.csv.gz  in=399,506,959 out=85,863,407 elapsed=188.3s

  [13629/15692] intraday_7936.csv.gz  in=399,520,306 out=85,876,754 elapsed=188.4s

  [13630/15692] intraday_7937.csv.gz  in=399,533,439 out=85,889,887 elapsed=188.4s

  [13631/15692] intraday_7938.csv.gz  in=399,544,139 out=85,900,587 elapsed=188.4s

  [13632/15692] intraday_7940.csv.gz  in=399,556,337 out=85,912,785 elapsed=188.4s

  [13633/15692] intraday_7939.csv.gz  in=399,568,618 out=85,925,066 elapsed=188.4s

  [13634/15692] intraday_7941.csv.gz  in=399,583,192 out=85,939,640 elapsed=188.4s

  [13635/15692] intraday_7942.csv.gz  in=399,595,230 out=85,951,678 elapsed=188.4s

  [13636/15692] intraday_7943.csv.gz  in=399,609,935 out=85,966,383 elapsed=188.5s

  [13637/15692] intraday_7944.csv.gz  in=399,621,879 out=85,978,327 elapsed=188.5s

  [13638/15692] intraday_7945.csv.gz  in=399,633,137 out=85,989,585 elapsed=188.5s

  [13639/15692] intraday_7947.csv.gz  in=399,645,601 out=86,002,049 elapsed=188.5s

  [13640/15692] intraday_7948.csv.gz  in=399,657,452 out=86,013,900 elapsed=188.5s

  [13641/15692] intraday_7946.csv.gz  in=399,672,085 out=86,028,533 elapsed=188.5s

  [13642/15692] intraday_7950.csv.gz  in=399,684,753 out=86,041,201 elapsed=188.6s

  [13643/15692] intraday_7949.csv.gz  in=399,697,777 out=86,054,225 elapsed=188.6s

  [13644/15692] intraday_7952.csv.gz  in=399,711,553 out=86,068,001 elapsed=188.6s

  [13645/15692] intraday_7951.csv.gz  in=399,725,301 out=86,081,749 elapsed=188.6s

  [13646/15692] intraday_7953.csv.gz  in=399,740,107 out=86,096,555 elapsed=188.6s

  [13647/15692] intraday_7954.csv.gz  in=399,752,909 out=86,109,357 elapsed=188.6s

  [13648/15692] intraday_7955.csv.gz  in=399,765,057 out=86,121,505 elapsed=188.6s

  [13649/15692] intraday_7956.csv.gz  in=399,775,983 out=86,132,431 elapsed=188.7s

  [13650/15692] intraday_7957.csv.gz  in=399,790,290 out=86,146,738 elapsed=188.7s

  [13651/15692] intraday_7959.csv.gz  in=399,803,177 out=86,159,625 elapsed=188.7s

  [13652/15692] intraday_7958.csv.gz  in=399,816,935 out=86,173,383 elapsed=188.7s

  [13653/15692] intraday_7961.csv.gz  in=399,828,939 out=86,185,387 elapsed=188.7s

  [13654/15692] intraday_7962.csv.gz  in=399,840,381 out=86,196,552 elapsed=188.7s

  [13655/15692] intraday_7960.csv.gz  in=399,853,583 out=86,209,754 elapsed=188.7s

  [13656/15692] intraday_7963.csv.gz  in=399,865,104 out=86,221,275 elapsed=188.8s

  [13657/15692] intraday_7964.csv.gz  in=399,879,392 out=86,235,563 elapsed=188.8s

  [13658/15692] intraday_7966.csv.gz  in=399,893,090 out=86,249,261 elapsed=188.8s

  [13659/15692] intraday_7965.csv.gz  in=399,906,745 out=86,262,916 elapsed=188.8s

  [13660/15692] intraday_7967.csv.gz  in=399,922,010 out=86,276,347 elapsed=188.8s

  [13661/15692] intraday_7968.csv.gz  in=399,933,212 out=86,287,549 elapsed=188.8s

  [13662/15692] intraday_7969.csv.gz  in=399,945,874 out=86,300,211 elapsed=188.8s

  [13663/15692] intraday_7970.csv.gz  in=399,958,387 out=86,312,724 elapsed=188.9s

  [13664/15692] intraday_7971.csv.gz  in=399,970,651 out=86,324,988 elapsed=188.9s

  [13665/15692] intraday_7973.csv.gz  in=399,982,805 out=86,337,142 elapsed=188.9s

  [13666/15692] intraday_7972.csv.gz  in=399,996,808 out=86,351,145 elapsed=188.9s

  [13667/15692] intraday_7974.csv.gz  in=400,006,990 out=86,361,327 elapsed=188.9s

  [13668/15692] intraday_7975.csv.gz  in=400,020,896 out=86,375,233 elapsed=188.9s

  [13669/15692] intraday_7977.csv.gz  in=400,032,098 out=86,386,435 elapsed=188.9s

  [13670/15692] intraday_7976.csv.gz  in=400,043,997 out=86,398,334 elapsed=188.9s

  [13671/15692] intraday_7978.csv.gz  in=400,059,861 out=86,411,039 elapsed=188.9s

  [13672/15692] intraday_7979.csv.gz  in=400,070,727 out=86,420,379 elapsed=189.0s

  [13673/15692] intraday_7980.csv.gz  in=400,082,584 out=86,432,236 elapsed=189.0s

  [13674/15692] intraday_7981.csv.gz  in=400,095,730 out=86,445,382 elapsed=189.0s

  [13675/15692] intraday_7982.csv.gz  in=400,112,158 out=86,461,810 elapsed=189.0s

  [13676/15692] intraday_7983.csv.gz  in=400,128,327 out=86,477,979 elapsed=189.0s

  [13677/15692] intraday_7985.csv.gz  in=400,141,285 out=86,490,937 elapsed=189.0s

  [13678/15692] intraday_7984.csv.gz  in=400,154,267 out=86,503,919 elapsed=189.0s

  [13679/15692] intraday_7986.csv.gz  in=400,166,566 out=86,516,218 elapsed=189.0s

  [13680/15692] intraday_7987.csv.gz  in=400,179,404 out=86,529,056 elapsed=189.1s

  [13681/15692] intraday_7988.csv.gz  in=400,195,554 out=86,545,206 elapsed=189.1s

  [13682/15692] intraday_7989.csv.gz  in=400,207,829 out=86,557,481 elapsed=189.1s

  [13683/15692] intraday_7990.csv.gz  in=400,220,330 out=86,569,982 elapsed=189.1s

  [13684/15692] intraday_7991.csv.gz  in=400,234,184 out=86,583,836 elapsed=189.1s

  [13685/15692] intraday_7992.csv.gz  in=400,248,943 out=86,598,595 elapsed=189.1s

  [13686/15692] intraday_7994.csv.gz  in=400,263,204 out=86,612,076 elapsed=189.1s

  [13687/15692] intraday_7993.csv.gz  in=400,278,477 out=86,627,349 elapsed=189.1s

  [13688/15692] intraday_7997.csv.gz  in=400,291,685 out=86,640,557 elapsed=189.2s

  [13689/15692] intraday_7995.csv.gz  in=400,303,481 out=86,652,353 elapsed=189.2s

  [13690/15692] intraday_7996.csv.gz  in=400,316,313 out=86,665,185 elapsed=189.2s

  [13691/15692] intraday_7998.csv.gz  in=400,331,126 out=86,679,998 elapsed=189.2s

  [13692/15692] intraday_7999.csv.gz  in=400,343,455 out=86,692,327 elapsed=189.2s

  [13693/15692] intraday_8002.csv.gz  in=400,356,678 out=86,705,550 elapsed=189.2s

  [13694/15692] intraday_8000.csv.gz  in=400,366,978 out=86,715,850 elapsed=189.2s

  [13695/15692] intraday_8001.csv.gz  in=400,383,032 out=86,731,904 elapsed=189.2s

  [13696/15692] intraday_8004.csv.gz  in=400,395,248 out=86,744,120 elapsed=189.2s

  [13697/15692] intraday_8003.csv.gz  in=400,410,219 out=86,758,752 elapsed=189.2s

  [13698/15692] intraday_8006.csv.gz  in=400,423,341 out=86,771,874 elapsed=189.3s

  [13699/15692] intraday_8007.csv.gz  in=400,436,451 out=86,784,984 elapsed=189.3s

  [13700/15692] intraday_8005.csv.gz  in=400,455,270 out=86,803,803 elapsed=189.3s

  [13701/15692] intraday_8008.csv.gz  in=400,470,001 out=86,818,534 elapsed=189.3s

  [13702/15692] intraday_8009.csv.gz  in=400,484,409 out=86,832,942 elapsed=189.3s

  [13703/15692] intraday_8010.csv.gz  in=400,495,977 out=86,844,510 elapsed=189.3s

  [13704/15692] intraday_8012.csv.gz  in=400,510,404 out=86,858,937 elapsed=189.3s

  [13705/15692] intraday_8011.csv.gz  in=400,525,891 out=86,874,424 elapsed=189.3s

  [13706/15692] intraday_8014.csv.gz  in=400,541,734 out=86,890,267 elapsed=189.3s

  [13707/15692] intraday_8013.csv.gz  in=400,556,682 out=86,905,215 elapsed=189.3s

  [13708/15692] intraday_8015.csv.gz  in=400,571,896 out=86,920,429 elapsed=189.4s

  [13709/15692] intraday_8016.csv.gz  in=400,584,866 out=86,933,399 elapsed=189.4s

  [13710/15692] intraday_8017.csv.gz  in=400,603,523 out=86,949,535 elapsed=189.4s

  [13711/15692] intraday_8019.csv.gz  in=400,617,138 out=86,962,123 elapsed=189.4s

  [13712/15692] intraday_8018.csv.gz  in=400,629,048 out=86,974,033 elapsed=189.4s

  [13713/15692] intraday_8021.csv.gz  in=400,642,706 out=86,987,691 elapsed=189.4s

  [13714/15692] intraday_8020.csv.gz  in=400,655,660 out=87,000,645 elapsed=189.4s

  [13715/15692] intraday_8022.csv.gz  in=400,666,873 out=87,011,858 elapsed=189.4s

  [13716/15692] intraday_8023.csv.gz  in=400,681,938 out=87,026,923 elapsed=189.4s

  [13717/15692] intraday_8025.csv.gz  in=400,698,327 out=87,043,312 elapsed=189.5s

  [13718/15692] intraday_8024.csv.gz  in=400,718,319 out=87,059,139 elapsed=189.5s

  [13719/15692] intraday_8026.csv.gz  in=400,730,123 out=87,070,943 elapsed=189.5s

  [13720/15692] intraday_8027.csv.gz  in=400,743,893 out=87,084,713 elapsed=189.5s

  [13721/15692] intraday_8028.csv.gz  in=400,756,255 out=87,097,075 elapsed=189.5s

  [13722/15692] intraday_8029.csv.gz  in=400,769,745 out=87,110,565 elapsed=189.5s

  [13723/15692] intraday_8030.csv.gz  in=400,781,552 out=87,122,372 elapsed=189.6s

  [13724/15692] intraday_8031.csv.gz  in=400,795,797 out=87,136,617 elapsed=189.6s

  [13725/15692] intraday_8032.csv.gz  in=400,810,528 out=87,151,348 elapsed=189.6s

  [13726/15692] intraday_8033.csv.gz  in=400,824,602 out=87,165,422 elapsed=189.6s

  [13727/15692] intraday_8034.csv.gz  in=400,840,141 out=87,180,768 elapsed=189.6s

  [13728/15692] intraday_8035.csv.gz  in=400,854,923 out=87,195,123 elapsed=189.6s

  [13729/15692] intraday_8037.csv.gz  in=400,868,611 out=87,208,811 elapsed=189.6s

  [13730/15692] intraday_8036.csv.gz  in=400,878,896 out=87,219,096 elapsed=189.6s

  [13731/15692] intraday_8038.csv.gz  in=400,890,646 out=87,230,846 elapsed=189.7s

  [13732/15692] intraday_8039.csv.gz  in=400,906,055 out=87,246,255 elapsed=189.7s

  [13733/15692] intraday_8040.csv.gz  in=400,914,399 out=87,254,599 elapsed=189.7s

  [13734/15692] intraday_8042.csv.gz  in=400,925,737 out=87,265,937 elapsed=189.7s

  [13735/15692] intraday_8041.csv.gz  in=400,937,986 out=87,278,186 elapsed=189.7s

  [13736/15692] intraday_8043.csv.gz  in=400,947,983 out=87,279,296 elapsed=189.7s

  [13737/15692] intraday_8045.csv.gz  in=400,962,285 out=87,293,598 elapsed=189.7s

  [13738/15692] intraday_8044.csv.gz  in=400,977,385 out=87,308,698 elapsed=189.8s

  [13739/15692] intraday_8047.csv.gz  in=400,988,642 out=87,319,955 elapsed=189.8s

  [13740/15692] intraday_8046.csv.gz  in=401,001,550 out=87,332,863 elapsed=189.8s

  [13741/15692] intraday_8048.csv.gz  in=401,012,745 out=87,344,058 elapsed=189.8s

  [13742/15692] intraday_8049.csv.gz  in=401,027,489 out=87,358,802 elapsed=189.8s

  [13743/15692] intraday_8051.csv.gz  in=401,039,965 out=87,371,278 elapsed=189.8s

  [13744/15692] intraday_8052.csv.gz  in=401,053,394 out=87,384,707 elapsed=189.8s

  [13745/15692] intraday_8050.csv.gz  in=401,067,462 out=87,398,775 elapsed=189.8s

  [13746/15692] intraday_8053.csv.gz  in=401,082,975 out=87,414,288 elapsed=189.9s

  [13747/15692] intraday_8056.csv.gz  in=401,096,207 out=87,427,520 elapsed=189.9s

  [13748/15692] intraday_8055.csv.gz  in=401,109,394 out=87,440,707 elapsed=189.9s

  [13749/15692] intraday_8054.csv.gz  in=401,123,712 out=87,455,025 elapsed=189.9s

  [13750/15692] intraday_8057.csv.gz  in=401,136,990 out=87,468,303 elapsed=189.9s

  [13751/15692] intraday_8059.csv.gz  in=401,147,026 out=87,478,339 elapsed=189.9s

  [13752/15692] intraday_8058.csv.gz  in=401,156,482 out=87,487,795 elapsed=189.9s

  [13753/15692] intraday_8060.csv.gz  in=401,169,832 out=87,501,145 elapsed=189.9s

  [13754/15692] intraday_8061.csv.gz  in=401,182,227 out=87,513,540 elapsed=190.0s

  [13755/15692] intraday_8063.csv.gz  in=401,194,387 out=87,524,906 elapsed=190.0s

  [13756/15692] intraday_8062.csv.gz  in=401,205,115 out=87,535,634 elapsed=190.0s

  [13757/15692] intraday_8064.csv.gz  in=401,217,138 out=87,547,657 elapsed=190.0s

  [13758/15692] intraday_8065.csv.gz  in=401,229,691 out=87,560,210 elapsed=190.0s

  [13759/15692] intraday_8066.csv.gz  in=401,242,278 out=87,572,797 elapsed=190.0s

  [13760/15692] intraday_8067.csv.gz  in=401,255,505 out=87,586,024 elapsed=190.1s

  [13761/15692] intraday_8068.csv.gz  in=401,268,690 out=87,599,209 elapsed=190.1s

  [13762/15692] intraday_8069.csv.gz  in=401,282,291 out=87,612,810 elapsed=190.1s

  [13763/15692] intraday_8070.csv.gz  in=401,303,831 out=87,625,738 elapsed=190.1s

  [13764/15692] intraday_8072.csv.gz  in=401,314,343 out=87,636,250 elapsed=190.1s

  [13765/15692] intraday_8071.csv.gz  in=401,325,913 out=87,647,820 elapsed=190.1s

  [13766/15692] intraday_8073.csv.gz  in=401,340,243 out=87,662,150 elapsed=190.1s

  [13767/15692] intraday_8075.csv.gz  in=401,352,956 out=87,674,863 elapsed=190.1s

  [13768/15692] intraday_8074.csv.gz  in=401,369,146 out=87,691,053 elapsed=190.1s

  [13769/15692] intraday_8076.csv.gz  in=401,379,732 out=87,701,639 elapsed=190.2s

  [13770/15692] intraday_8079.csv.gz  in=401,392,214 out=87,713,799 elapsed=190.2s

  [13771/15692] intraday_8077.csv.gz  in=401,405,225 out=87,726,810 elapsed=190.2s

  [13772/15692] intraday_8078.csv.gz  in=401,424,853 out=87,740,869 elapsed=190.2s

  [13773/15692] intraday_8080.csv.gz  in=401,437,485 out=87,753,501 elapsed=190.2s

  [13774/15692] intraday_8081.csv.gz  in=401,449,848 out=87,765,864 elapsed=190.2s

  [13775/15692] intraday_8082.csv.gz  in=401,462,626 out=87,778,161 elapsed=190.3s

  [13776/15692] intraday_8083.csv.gz  in=401,473,899 out=87,789,434 elapsed=190.3s

  [13777/15692] intraday_8084.csv.gz  in=401,485,132 out=87,800,667 elapsed=190.3s

  [13778/15692] intraday_8085.csv.gz  in=401,497,203 out=87,812,738 elapsed=190.3s

  [13779/15692] intraday_8086.csv.gz  in=401,509,821 out=87,825,356 elapsed=190.3s

  [13780/15692] intraday_8087.csv.gz  in=401,521,229 out=87,836,764 elapsed=190.3s

  [13781/15692] intraday_8088.csv.gz  in=401,534,873 out=87,850,408 elapsed=190.3s

  [13782/15692] intraday_8089.csv.gz  in=401,546,119 out=87,861,654 elapsed=190.3s

  [13783/15692] intraday_8090.csv.gz  in=401,557,820 out=87,873,355 elapsed=190.4s

  [13784/15692] intraday_8091.csv.gz  in=401,571,192 out=87,886,727 elapsed=190.4s

  [13785/15692] intraday_8092.csv.gz  in=401,583,564 out=87,899,099 elapsed=190.4s

  [13786/15692] intraday_8093.csv.gz  in=401,595,801 out=87,911,336 elapsed=190.4s

  [13787/15692] intraday_8094.csv.gz  in=401,607,610 out=87,923,145 elapsed=190.4s

  [13788/15692] intraday_8095.csv.gz  in=401,618,380 out=87,933,915 elapsed=190.4s

  [13789/15692] intraday_8096.csv.gz  in=401,634,117 out=87,949,652 elapsed=190.4s

  [13790/15692] intraday_8097.csv.gz  in=401,645,590 out=87,961,125 elapsed=190.4s

  [13791/15692] intraday_8098.csv.gz  in=401,660,531 out=87,976,066 elapsed=190.5s

  [13792/15692] intraday_8099.csv.gz  in=401,672,681 out=87,988,216 elapsed=190.5s

  [13793/15692] intraday_8100.csv.gz  in=401,687,202 out=88,001,663 elapsed=190.5s

  [13794/15692] intraday_8101.csv.gz  in=401,697,766 out=88,012,227 elapsed=190.5s

  [13795/15692] intraday_8102.csv.gz  in=401,710,252 out=88,024,713 elapsed=190.5s

  [13796/15692] intraday_8103.csv.gz  in=401,722,523 out=88,036,984 elapsed=190.5s

  [13797/15692] intraday_8104.csv.gz  in=401,734,313 out=88,048,774 elapsed=190.5s

  [13798/15692] intraday_8105.csv.gz  in=401,746,420 out=88,060,881 elapsed=190.5s

  [13799/15692] intraday_8106.csv.gz  in=401,758,250 out=88,072,328 elapsed=190.5s

  [13800/15692] intraday_8107.csv.gz  in=401,774,703 out=88,083,972 elapsed=190.6s

  [13801/15692] intraday_8108.csv.gz  in=401,785,524 out=88,094,793 elapsed=190.6s

  [13802/15692] intraday_8109.csv.gz  in=401,798,950 out=88,108,219 elapsed=190.6s

  [13803/15692] intraday_8112.csv.gz  in=401,811,648 out=88,120,917 elapsed=190.6s

  [13804/15692] intraday_8111.csv.gz  in=401,825,121 out=88,134,390 elapsed=190.6s

  [13805/15692] intraday_8113.csv.gz  in=401,836,977 out=88,145,274 elapsed=190.6s

  [13806/15692] intraday_8110.csv.gz  in=401,850,633 out=88,158,930 elapsed=190.6s

  [13807/15692] intraday_8114.csv.gz  in=401,863,636 out=88,169,640 elapsed=190.7s

  [13808/15692] intraday_8115.csv.gz  in=401,876,611 out=88,182,615 elapsed=190.7s

  [13809/15692] intraday_8116.csv.gz  in=401,888,953 out=88,194,957 elapsed=190.7s

  [13810/15692] intraday_8118.csv.gz  in=401,900,347 out=88,206,351 elapsed=190.7s

  [13811/15692] intraday_8117.csv.gz  in=401,913,493 out=88,219,497 elapsed=190.7s

  [13812/15692] intraday_8119.csv.gz  in=401,927,641 out=88,231,500 elapsed=190.7s

  [13813/15692] intraday_8120.csv.gz  in=401,937,956 out=88,241,815 elapsed=190.7s

  [13814/15692] intraday_8122.csv.gz  in=401,949,302 out=88,253,161 elapsed=190.8s

  [13815/15692] intraday_8121.csv.gz  in=401,962,233 out=88,266,092 elapsed=190.8s

  [13816/15692] intraday_8123.csv.gz  in=401,973,899 out=88,277,758 elapsed=190.8s

  [13817/15692] intraday_8124.csv.gz  in=401,984,199 out=88,288,058 elapsed=190.8s

  [13818/15692] intraday_8125.csv.gz  in=401,994,796 out=88,297,997 elapsed=190.8s

  [13819/15692] intraday_8126.csv.gz  in=402,006,699 out=88,309,900 elapsed=190.8s

  [13820/15692] intraday_8127.csv.gz  in=402,020,927 out=88,324,128 elapsed=190.8s

  [13821/15692] intraday_8128.csv.gz  in=402,038,719 out=88,341,920 elapsed=190.8s

  [13822/15692] intraday_8129.csv.gz  in=402,052,296 out=88,355,497 elapsed=190.9s

  [13823/15692] intraday_8130.csv.gz  in=402,064,158 out=88,366,104 elapsed=190.9s

  [13824/15692] intraday_8131.csv.gz  in=402,075,529 out=88,377,475 elapsed=190.9s

  [13825/15692] intraday_8132.csv.gz  in=402,088,795 out=88,390,741 elapsed=190.9s

  [13826/15692] intraday_8133.csv.gz  in=402,102,330 out=88,404,276 elapsed=190.9s

  [13827/15692] intraday_8134.csv.gz  in=402,118,852 out=88,417,837 elapsed=190.9s

  [13828/15692] intraday_8135.csv.gz  in=402,131,320 out=88,430,305 elapsed=190.9s

  [13829/15692] intraday_8136.csv.gz  in=402,143,760 out=88,442,745 elapsed=190.9s

  [13830/15692] intraday_8137.csv.gz  in=402,156,043 out=88,455,028 elapsed=191.0s

  [13831/15692] intraday_8138.csv.gz  in=402,170,174 out=88,469,159 elapsed=191.0s

  [13832/15692] intraday_8139.csv.gz  in=402,185,119 out=88,484,104 elapsed=191.0s

  [13833/15692] intraday_8140.csv.gz  in=402,196,208 out=88,495,193 elapsed=191.0s

  [13834/15692] intraday_8141.csv.gz  in=402,212,101 out=88,508,683 elapsed=191.0s

  [13835/15692] intraday_8143.csv.gz  in=402,226,379 out=88,522,961 elapsed=191.0s

  [13836/15692] intraday_8142.csv.gz  in=402,238,059 out=88,534,641 elapsed=191.0s

  [13837/15692] intraday_8144.csv.gz  in=402,250,607 out=88,547,189 elapsed=191.0s

  [13838/15692] intraday_8145.csv.gz  in=402,262,470 out=88,559,052 elapsed=191.0s

  [13839/15692] intraday_8146.csv.gz  in=402,275,498 out=88,572,080 elapsed=191.1s

  [13840/15692] intraday_8147.csv.gz  in=402,289,501 out=88,586,083 elapsed=191.1s

  [13841/15692] intraday_8149.csv.gz  in=402,302,069 out=88,598,651 elapsed=191.1s

  [13842/15692] intraday_8148.csv.gz  in=402,314,142 out=88,610,724 elapsed=191.1s

  [13843/15692] intraday_8150.csv.gz  in=402,328,465 out=88,625,047 elapsed=191.1s

  [13844/15692] intraday_8152.csv.gz  in=402,342,349 out=88,638,931 elapsed=191.1s

  [13845/15692] intraday_8151.csv.gz  in=402,356,981 out=88,653,563 elapsed=191.1s

  [13846/15692] intraday_8153.csv.gz  in=402,370,813 out=88,667,210 elapsed=191.2s

  [13847/15692] intraday_8154.csv.gz  in=402,387,165 out=88,683,017 elapsed=191.2s

  [13848/15692] intraday_8155.csv.gz  in=402,398,801 out=88,694,653 elapsed=191.2s

  [13849/15692] intraday_8157.csv.gz  in=402,412,854 out=88,708,706 elapsed=191.2s

  [13850/15692] intraday_8156.csv.gz  in=402,426,231 out=88,722,083 elapsed=191.2s

  [13851/15692] intraday_8159.csv.gz  in=402,439,909 out=88,735,761 elapsed=191.2s

  [13852/15692] intraday_8160.csv.gz  in=402,455,444 out=88,751,296 elapsed=191.2s

  [13853/15692] intraday_8161.csv.gz  in=402,472,100 out=88,767,952 elapsed=191.2s

  [13854/15692] intraday_8162.csv.gz  in=402,487,237 out=88,783,089 elapsed=191.3s

  [13855/15692] intraday_8158.csv.gz  in=402,499,248 out=88,795,100 elapsed=191.3s

  [13856/15692] intraday_8163.csv.gz  in=402,512,174 out=88,808,026 elapsed=191.3s

  [13857/15692] intraday_8164.csv.gz  in=402,525,026 out=88,820,878 elapsed=191.3s

  [13858/15692] intraday_8166.csv.gz  in=402,536,190 out=88,832,042 elapsed=191.3s

  [13859/15692] intraday_8165.csv.gz  in=402,551,663 out=88,843,864 elapsed=191.3s

  [13860/15692] intraday_8168.csv.gz  in=402,562,474 out=88,854,675 elapsed=191.3s

  [13861/15692] intraday_8167.csv.gz  in=402,577,037 out=88,869,238 elapsed=191.4s

  [13862/15692] intraday_8169.csv.gz  in=402,591,314 out=88,883,515 elapsed=191.4s

  [13863/15692] intraday_8170.csv.gz  in=402,605,083 out=88,897,284 elapsed=191.4s

  [13864/15692] intraday_8173.csv.gz  in=402,617,404 out=88,909,605 elapsed=191.4s

  [13865/15692] intraday_8171.csv.gz  in=402,632,722 out=88,924,923 elapsed=191.4s

  [13866/15692] intraday_8172.csv.gz  in=402,648,884 out=88,936,439 elapsed=191.4s

  [13867/15692] intraday_8175.csv.gz  in=402,660,528 out=88,948,083 elapsed=191.4s

  [13868/15692] intraday_8174.csv.gz  in=402,674,470 out=88,962,025 elapsed=191.4s

  [13869/15692] intraday_8176.csv.gz  in=402,687,499 out=88,975,054 elapsed=191.5s

  [13870/15692] intraday_8179.csv.gz  in=402,701,210 out=88,988,765 elapsed=191.5s

  [13871/15692] intraday_8178.csv.gz  in=402,716,080 out=89,003,635 elapsed=191.5s

  [13872/15692] intraday_8177.csv.gz  in=402,729,989 out=89,017,544 elapsed=191.5s

  [13873/15692] intraday_8180.csv.gz  in=402,743,512 out=89,031,067 elapsed=191.5s

  [13874/15692] intraday_8181.csv.gz  in=402,756,101 out=89,043,656 elapsed=191.5s

  [13875/15692] intraday_8183.csv.gz  in=402,769,194 out=89,056,749 elapsed=191.5s

  [13876/15692] intraday_8182.csv.gz  in=402,781,418 out=89,068,973 elapsed=191.6s

  [13877/15692] intraday_8184.csv.gz  in=402,792,921 out=89,080,476 elapsed=191.6s

  [13878/15692] intraday_8185.csv.gz  in=402,804,290 out=89,091,845 elapsed=191.6s

  [13879/15692] intraday_8186.csv.gz  in=402,811,734 out=89,099,289 elapsed=191.6s

  [13880/15692] intraday_8187.csv.gz  in=402,824,017 out=89,111,572 elapsed=191.6s

  [13881/15692] intraday_8188.csv.gz  in=402,830,697 out=89,118,252 elapsed=191.6s

  [13882/15692] intraday_8189.csv.gz  in=402,830,736 out=89,118,270 elapsed=191.6s

  [13883/15692] intraday_8190.csv.gz  in=402,834,833 out=89,118,876 elapsed=191.6s

  [13884/15692] intraday_8191.csv.gz  in=402,837,321 out=89,119,271 elapsed=191.6s

  [13885/15692] intraday_8192.csv.gz  in=402,838,336 out=89,120,124 elapsed=191.6s

  [13886/15692] intraday_8193.csv.gz  in=402,839,273 out=89,120,213 elapsed=191.6s

  [13887/15692] intraday_8195.csv.gz  in=402,839,358 out=89,120,298 elapsed=191.6s

  [13888/15692] intraday_8194.csv.gz  in=402,839,988 out=89,120,928 elapsed=191.7s

  [13889/15692] intraday_8196.csv.gz  in=402,840,054 out=89,120,994 elapsed=191.7s

  [13890/15692] intraday_8198.csv.gz  in=402,840,408 out=89,121,348 elapsed=191.7s

  [13891/15692] intraday_8197.csv.gz  in=402,843,216 out=89,121,825 elapsed=191.7s

  [13892/15692] intraday_8200.csv.gz  in=402,843,376 out=89,121,985 elapsed=191.7s

  [13893/15692] intraday_8199.csv.gz  in=402,847,988 out=89,123,785 elapsed=191.7s

  [13894/15692] intraday_8202.csv.gz  in=402,849,311 out=89,123,887 elapsed=191.7s

  [13895/15692] intraday_8201.csv.gz  in=402,854,079 out=89,124,495 elapsed=191.7s

  [13896/15692] intraday_8204.csv.gz  in=402,854,119 out=89,124,535 elapsed=191.7s

  [13897/15692] intraday_8206.csv.gz  in=402,854,120 out=89,124,536 elapsed=191.7s

  [13898/15692] intraday_8203.csv.gz  in=402,854,370 out=89,124,786 elapsed=191.7s

  [13899/15692] intraday_8205.csv.gz  in=402,865,093 out=89,126,444 elapsed=191.8s

  [13900/15692] intraday_8207.csv.gz  in=402,869,876 out=89,130,123 elapsed=191.8s

  [13901/15692] intraday_8208.csv.gz  in=402,878,328 out=89,131,189 elapsed=191.8s

  [13902/15692] intraday_8209.csv.gz  in=402,878,911 out=89,131,440 elapsed=191.8s

  [13903/15692] intraday_8210.csv.gz  in=402,879,029 out=89,131,454 elapsed=191.8s

  [13904/15692] intraday_8211.csv.gz  in=402,880,007 out=89,131,580 elapsed=191.8s

  [13905/15692] intraday_8213.csv.gz  in=402,880,230 out=89,131,803 elapsed=191.8s

  [13906/15692] intraday_8215.csv.gz  in=402,880,796 out=89,132,369 elapsed=191.8s

  [13907/15692] intraday_8214.csv.gz  in=402,882,411 out=89,133,984 elapsed=191.8s

  [13908/15692] intraday_8216.csv.gz  in=402,883,231 out=89,134,804 elapsed=191.8s

  [13909/15692] intraday_8217.csv.gz  in=402,883,800 out=89,135,373 elapsed=191.8s

  [13910/15692] intraday_8212.csv.gz  in=402,897,696 out=89,137,221 elapsed=191.8s

  [13911/15692] intraday_8218.csv.gz  in=402,898,781 out=89,138,306 elapsed=191.8s

  [13912/15692] intraday_8219.csv.gz  in=402,899,559 out=89,139,084 elapsed=191.8s

  [13913/15692] intraday_8221.csv.gz  in=402,900,237 out=89,139,762 elapsed=191.9s

  [13914/15692] intraday_8220.csv.gz  in=402,901,495 out=89,141,020 elapsed=191.9s

  [13915/15692] intraday_8222.csv.gz  in=402,902,176 out=89,141,701 elapsed=191.9s

  [13916/15692] intraday_8223.csv.gz  in=402,903,165 out=89,142,690 elapsed=191.9s

  [13917/15692] intraday_8224.csv.gz  in=402,904,526 out=89,144,051 elapsed=191.9s

  [13918/15692] intraday_8227.csv.gz  in=402,905,590 out=89,145,115 elapsed=191.9s

  [13919/15692] intraday_8226.csv.gz  in=402,906,428 out=89,145,953 elapsed=191.9s

  [13920/15692] intraday_8228.csv.gz  in=402,906,689 out=89,146,214 elapsed=191.9s

  [13921/15692] intraday_8225.csv.gz  in=402,907,529 out=89,147,054 elapsed=191.9s

  [13922/15692] intraday_8229.csv.gz  in=402,907,869 out=89,147,394 elapsed=191.9s

  [13923/15692] intraday_8230.csv.gz  in=402,908,671 out=89,148,196 elapsed=191.9s

  [13924/15692] intraday_8231.csv.gz  in=402,909,484 out=89,149,009 elapsed=191.9s

  [13925/15692] intraday_8232.csv.gz  in=402,910,046 out=89,149,571 elapsed=191.9s

  [13926/15692] intraday_8233.csv.gz  in=402,910,431 out=89,149,956 elapsed=191.9s

  [13927/15692] intraday_8234.csv.gz  in=402,911,103 out=89,150,628 elapsed=191.9s

  [13928/15692] intraday_8235.csv.gz  in=402,911,746 out=89,151,271 elapsed=191.9s

  [13929/15692] intraday_8236.csv.gz  in=402,912,135 out=89,151,660 elapsed=191.9s

  [13930/15692] intraday_8238.csv.gz  in=402,912,576 out=89,152,101 elapsed=191.9s

  [13931/15692] intraday_8240.csv.gz  in=402,913,151 out=89,152,676 elapsed=191.9s

  [13932/15692] intraday_8239.csv.gz  in=402,914,119 out=89,153,644 elapsed=191.9s

  [13933/15692] intraday_8237.csv.gz  in=402,915,017 out=89,154,542 elapsed=191.9s

  [13934/15692] intraday_8241.csv.gz  in=402,915,212 out=89,154,737 elapsed=192.0s

  [13935/15692] intraday_8242.csv.gz  in=402,916,195 out=89,155,720 elapsed=192.0s

  [13936/15692] intraday_8243.csv.gz  in=402,917,285 out=89,156,810 elapsed=192.0s

  [13937/15692] intraday_8244.csv.gz  in=402,918,751 out=89,158,276 elapsed=192.0s

  [13938/15692] intraday_8245.csv.gz  in=402,919,714 out=89,159,239 elapsed=192.0s

  [13939/15692] intraday_8246.csv.gz  in=402,920,264 out=89,159,789 elapsed=192.0s

  [13940/15692] intraday_8248.csv.gz  in=402,920,708 out=89,160,233 elapsed=192.0s

  [13941/15692] intraday_8249.csv.gz  in=402,921,441 out=89,160,966 elapsed=192.0s

  [13942/15692] intraday_8250.csv.gz  in=402,921,845 out=89,161,370 elapsed=192.0s

  [13943/15692] intraday_8247.csv.gz  in=402,922,422 out=89,161,947 elapsed=192.0s

  [13944/15692] intraday_8251.csv.gz  in=402,923,083 out=89,162,608 elapsed=192.0s

  [13945/15692] intraday_8252.csv.gz  in=402,923,634 out=89,163,159 elapsed=192.0s

  [13946/15692] intraday_8254.csv.gz  in=402,923,971 out=89,163,496 elapsed=192.0s

  [13947/15692] intraday_8253.csv.gz  in=402,924,302 out=89,163,827 elapsed=192.0s

  [13948/15692] intraday_8256.csv.gz  in=402,924,680 out=89,164,205 elapsed=192.0s

  [13949/15692] intraday_8255.csv.gz  in=402,925,170 out=89,164,695 elapsed=192.0s

  [13950/15692] intraday_8257.csv.gz  in=402,925,666 out=89,165,191 elapsed=192.0s

  [13951/15692] intraday_8258.csv.gz  in=402,926,231 out=89,165,756 elapsed=192.0s

  [13952/15692] intraday_8259.csv.gz  in=402,926,841 out=89,166,366 elapsed=192.0s

  [13953/15692] intraday_8260.csv.gz  in=402,927,059 out=89,166,584 elapsed=192.0s

  [13954/15692] intraday_8262.csv.gz  in=402,927,688 out=89,167,213 elapsed=192.0s

  [13955/15692] intraday_8263.csv.gz  in=402,927,969 out=89,167,494 elapsed=192.1s

  [13956/15692] intraday_8261.csv.gz  in=402,928,488 out=89,168,013 elapsed=192.1s

  [13957/15692] intraday_8264.csv.gz  in=402,928,815 out=89,168,340 elapsed=192.1s

  [13958/15692] intraday_8265.csv.gz  in=402,929,338 out=89,168,863 elapsed=192.1s

  [13959/15692] intraday_8266.csv.gz  in=402,930,460 out=89,169,985 elapsed=192.1s

  [13960/15692] intraday_8267.csv.gz  in=402,931,626 out=89,171,151 elapsed=192.1s

  [13961/15692] intraday_8268.csv.gz  in=402,932,538 out=89,172,063 elapsed=192.1s

  [13962/15692] intraday_8270.csv.gz  in=402,932,753 out=89,172,278 elapsed=192.1s

  [13963/15692] intraday_8269.csv.gz  in=402,933,326 out=89,172,851 elapsed=192.1s

  [13964/15692] intraday_8272.csv.gz  in=402,934,297 out=89,173,822 elapsed=192.1s

  [13965/15692] intraday_8271.csv.gz  in=402,934,502 out=89,174,027 elapsed=192.1s

  [13966/15692] intraday_8274.csv.gz  in=402,934,769 out=89,174,294 elapsed=192.1s

  [13967/15692] intraday_8273.csv.gz  in=402,935,624 out=89,175,149 elapsed=192.1s

  [13968/15692] intraday_8275.csv.gz  in=402,936,591 out=89,176,116 elapsed=192.1s

  [13969/15692] intraday_8276.csv.gz  in=402,936,719 out=89,176,244 elapsed=192.1s

  [13970/15692] intraday_8278.csv.gz  in=402,937,223 out=89,176,748 elapsed=192.1s

  [13971/15692] intraday_8277.csv.gz  in=402,937,420 out=89,176,945 elapsed=192.1s

  [13972/15692] intraday_8281.csv.gz  in=402,937,767 out=89,177,292 elapsed=192.1s

  [13973/15692] intraday_8279.csv.gz  in=402,939,243 out=89,178,768 elapsed=192.1s

  [13974/15692] intraday_8282.csv.gz  in=402,939,898 out=89,179,423 elapsed=192.1s

  [13975/15692] intraday_8280.csv.gz  in=402,941,025 out=89,180,550 elapsed=192.1s

  [13976/15692] intraday_8283.csv.gz  in=402,941,551 out=89,181,076 elapsed=192.2s

  [13977/15692] intraday_8284.csv.gz  in=402,941,995 out=89,181,520 elapsed=192.2s

  [13978/15692] intraday_8285.csv.gz  in=402,943,046 out=89,182,571 elapsed=192.2s

  [13979/15692] intraday_8286.csv.gz  in=402,943,419 out=89,182,944 elapsed=192.2s

  [13980/15692] intraday_8287.csv.gz  in=402,944,028 out=89,183,553 elapsed=192.2s

  [13981/15692] intraday_8288.csv.gz  in=402,944,417 out=89,183,942 elapsed=192.2s

  [13982/15692] intraday_8289.csv.gz  in=402,945,452 out=89,184,977 elapsed=192.2s

  [13983/15692] intraday_8291.csv.gz  in=402,946,205 out=89,185,730 elapsed=192.2s

  [13984/15692] intraday_8290.csv.gz  in=402,946,720 out=89,186,245 elapsed=192.2s

  [13985/15692] intraday_8292.csv.gz  in=402,947,375 out=89,186,900 elapsed=192.2s

  [13986/15692] intraday_8293.csv.gz  in=402,948,076 out=89,187,601 elapsed=192.2s

  [13987/15692] intraday_8295.csv.gz  in=402,948,439 out=89,187,964 elapsed=192.2s

  [13988/15692] intraday_8294.csv.gz  in=402,948,537 out=89,188,062 elapsed=192.2s

  [13989/15692] intraday_8296.csv.gz  in=402,949,182 out=89,188,707 elapsed=192.2s

  [13990/15692] intraday_8299.csv.gz  in=402,950,322 out=89,189,847 elapsed=192.2s

  [13991/15692] intraday_8297.csv.gz  in=402,952,652 out=89,192,177 elapsed=192.2s

  [13992/15692] intraday_8300.csv.gz  in=402,953,618 out=89,193,143 elapsed=192.2s

  [13993/15692] intraday_8298.csv.gz  in=402,955,084 out=89,194,609 elapsed=192.2s

  [13994/15692] intraday_8301.csv.gz  in=402,955,559 out=89,195,084 elapsed=192.2s

  [13995/15692] intraday_8303.csv.gz  in=402,956,669 out=89,196,194 elapsed=192.2s

  [13996/15692] intraday_8302.csv.gz  in=402,957,585 out=89,197,110 elapsed=192.3s

  [13997/15692] intraday_8304.csv.gz  in=402,958,917 out=89,198,442 elapsed=192.3s

  [13998/15692] intraday_8305.csv.gz  in=402,959,190 out=89,198,715 elapsed=192.3s

  [13999/15692] intraday_8306.csv.gz  in=402,960,014 out=89,199,539 elapsed=192.3s

  [14000/15692] intraday_8307.csv.gz  in=402,961,225 out=89,200,750 elapsed=192.3s

  [14001/15692] intraday_8308.csv.gz  in=402,961,806 out=89,201,331 elapsed=192.3s

  [14002/15692] intraday_8310.csv.gz  in=402,962,292 out=89,201,817 elapsed=192.3s

  [14003/15692] intraday_8309.csv.gz  in=402,963,055 out=89,202,580 elapsed=192.3s

  [14004/15692] intraday_8311.csv.gz  in=402,963,393 out=89,202,918 elapsed=192.3s

  [14005/15692] intraday_8313.csv.gz  in=402,964,375 out=89,203,900 elapsed=192.3s

  [14006/15692] intraday_8314.csv.gz  in=402,964,560 out=89,204,085 elapsed=192.3s

  [14007/15692] intraday_8315.csv.gz  in=402,965,291 out=89,204,816 elapsed=192.3s

  [14008/15692] intraday_8312.csv.gz  in=402,969,556 out=89,206,144 elapsed=192.3s

  [14009/15692] intraday_8317.csv.gz  in=402,971,287 out=89,207,875 elapsed=192.3s

  [14010/15692] intraday_8318.csv.gz  in=402,972,133 out=89,208,721 elapsed=192.3s

  [14011/15692] intraday_8316.csv.gz  in=402,973,699 out=89,210,287 elapsed=192.3s

  [14012/15692] intraday_8319.csv.gz  in=402,974,039 out=89,210,627 elapsed=192.3s

  [14013/15692] intraday_8320.csv.gz  in=402,975,877 out=89,212,465 elapsed=192.3s

  [14014/15692] intraday_8321.csv.gz  in=402,976,374 out=89,212,962 elapsed=192.3s

  [14015/15692] intraday_8322.csv.gz  in=402,976,889 out=89,213,477 elapsed=192.4s

  [14016/15692] intraday_8323.csv.gz  in=402,977,885 out=89,214,473 elapsed=192.4s

  [14017/15692] intraday_8324.csv.gz  in=402,978,489 out=89,215,077 elapsed=192.4s

  [14018/15692] intraday_8325.csv.gz  in=402,979,275 out=89,215,863 elapsed=192.4s

  [14019/15692] intraday_8326.csv.gz  in=402,980,072 out=89,216,660 elapsed=192.4s

  [14020/15692] intraday_8327.csv.gz  in=402,980,821 out=89,217,409 elapsed=192.4s

  [14021/15692] intraday_8328.csv.gz  in=402,981,923 out=89,218,511 elapsed=192.4s

  [14022/15692] intraday_8329.csv.gz  in=402,984,108 out=89,220,696 elapsed=192.4s

  [14023/15692] intraday_8331.csv.gz  in=402,984,811 out=89,221,399 elapsed=192.4s

  [14024/15692] intraday_8333.csv.gz  in=402,985,683 out=89,222,271 elapsed=192.4s

  [14025/15692] intraday_8332.csv.gz  in=402,987,065 out=89,223,653 elapsed=192.4s

  [14026/15692] intraday_8335.csv.gz  in=402,987,292 out=89,223,880 elapsed=192.4s

  [14027/15692] intraday_8334.csv.gz  in=402,987,744 out=89,224,332 elapsed=192.4s

  [14028/15692] intraday_8330.csv.gz  in=402,989,204 out=89,225,792 elapsed=192.4s

  [14029/15692] intraday_8336.csv.gz  in=402,989,727 out=89,226,315 elapsed=192.4s

  [14030/15692] intraday_8337.csv.gz  in=402,990,167 out=89,226,755 elapsed=192.4s

  [14031/15692] intraday_8338.csv.gz  in=402,990,786 out=89,227,374 elapsed=192.4s

  [14032/15692] intraday_8340.csv.gz  in=402,991,767 out=89,228,355 elapsed=192.4s

  [14033/15692] intraday_8339.csv.gz  in=402,992,527 out=89,229,115 elapsed=192.4s

  [14034/15692] intraday_8341.csv.gz  in=402,993,638 out=89,230,226 elapsed=192.5s

  [14035/15692] intraday_8342.csv.gz  in=402,994,278 out=89,230,866 elapsed=192.5s

  [14036/15692] intraday_8343.csv.gz  in=402,995,280 out=89,231,868 elapsed=192.5s

  [14037/15692] intraday_8345.csv.gz  in=402,996,145 out=89,232,733 elapsed=192.5s

  [14038/15692] intraday_8346.csv.gz  in=402,996,605 out=89,233,193 elapsed=192.5s

  [14039/15692] intraday_8344.csv.gz  in=402,997,524 out=89,234,112 elapsed=192.5s

  [14040/15692] intraday_8347.csv.gz  in=402,998,024 out=89,234,612 elapsed=192.5s

  [14041/15692] intraday_8348.csv.gz  in=402,998,442 out=89,235,030 elapsed=192.5s

  [14042/15692] intraday_8351.csv.gz  in=402,998,806 out=89,235,394 elapsed=192.5s

  [14043/15692] intraday_8350.csv.gz  in=402,999,440 out=89,236,028 elapsed=192.5s

  [14044/15692] intraday_8349.csv.gz  in=403,000,684 out=89,237,272 elapsed=192.5s

  [14045/15692] intraday_8352.csv.gz  in=403,001,485 out=89,238,073 elapsed=192.5s

  [14046/15692] intraday_8353.csv.gz  in=403,001,838 out=89,238,426 elapsed=192.5s

  [14047/15692] intraday_8354.csv.gz  in=403,003,083 out=89,239,671 elapsed=192.5s

  [14048/15692] intraday_8355.csv.gz  in=403,003,481 out=89,240,069 elapsed=192.5s

  [14049/15692] intraday_8357.csv.gz  in=403,004,483 out=89,241,071 elapsed=192.5s

  [14050/15692] intraday_8356.csv.gz  in=403,004,865 out=89,241,453 elapsed=192.5s

  [14051/15692] intraday_8358.csv.gz  in=403,004,874 out=89,241,462 elapsed=192.5s

  [14052/15692] intraday_8362.csv.gz  in=403,017,337 out=89,253,925 elapsed=192.6s

  [14053/15692] intraday_8359.csv.gz  in=403,032,836 out=89,269,424 elapsed=192.6s

  [14054/15692] intraday_8360.csv.gz  in=403,045,324 out=89,281,912 elapsed=192.6s

  [14055/15692] intraday_8363.csv.gz  in=403,058,451 out=89,295,039 elapsed=192.6s

  [14056/15692] intraday_8361.csv.gz  in=403,072,341 out=89,308,929 elapsed=192.6s

  [14057/15692] intraday_8364.csv.gz  in=403,086,896 out=89,323,484 elapsed=192.6s

  [14058/15692] intraday_8365.csv.gz  in=403,102,290 out=89,338,878 elapsed=192.7s

  [14059/15692] intraday_8366.csv.gz  in=403,114,719 out=89,351,307 elapsed=192.7s

  [14060/15692] intraday_8367.csv.gz  in=403,127,940 out=89,364,528 elapsed=192.7s

  [14061/15692] intraday_8368.csv.gz  in=403,143,532 out=89,380,120 elapsed=192.7s

  [14062/15692] intraday_8369.csv.gz  in=403,158,517 out=89,395,105 elapsed=192.7s

  [14063/15692] intraday_8370.csv.gz  in=403,172,147 out=89,408,735 elapsed=192.7s

  [14064/15692] intraday_8373.csv.gz  in=403,181,855 out=89,418,443 elapsed=192.7s

  [14065/15692] intraday_8372.csv.gz  in=403,195,001 out=89,431,589 elapsed=192.8s

  [14066/15692] intraday_8371.csv.gz  in=403,209,574 out=89,446,162 elapsed=192.8s

  [14067/15692] intraday_8374.csv.gz  in=403,220,259 out=89,456,847 elapsed=192.8s

  [14068/15692] intraday_8375.csv.gz  in=403,234,058 out=89,470,646 elapsed=192.8s

  [14069/15692] intraday_8377.csv.gz  in=403,245,512 out=89,482,100 elapsed=192.8s

  [14070/15692] intraday_8376.csv.gz  in=403,259,132 out=89,495,720 elapsed=192.8s

  [14071/15692] intraday_8378.csv.gz  in=403,271,174 out=89,507,762 elapsed=192.8s

  [14072/15692] intraday_8379.csv.gz  in=403,283,754 out=89,520,342 elapsed=192.8s

  [14073/15692] intraday_8380.csv.gz  in=403,296,898 out=89,533,486 elapsed=192.8s

  [14074/15692] intraday_8381.csv.gz  in=403,309,652 out=89,546,240 elapsed=192.8s

  [14075/15692] intraday_8382.csv.gz  in=403,324,103 out=89,560,691 elapsed=192.9s

  [14076/15692] intraday_8383.csv.gz  in=403,337,961 out=89,574,549 elapsed=192.9s

  [14077/15692] intraday_8384.csv.gz  in=403,351,146 out=89,587,734 elapsed=192.9s

  [14078/15692] intraday_8386.csv.gz  in=403,364,074 out=89,600,662 elapsed=192.9s

  [14079/15692] intraday_8385.csv.gz  in=403,376,240 out=89,612,828 elapsed=192.9s

  [14080/15692] intraday_8387.csv.gz  in=403,388,236 out=89,624,824 elapsed=192.9s

  [14081/15692] intraday_8388.csv.gz  in=403,403,252 out=89,639,840 elapsed=192.9s

  [14082/15692] intraday_8389.csv.gz  in=403,420,109 out=89,656,697 elapsed=192.9s

  [14083/15692] intraday_8391.csv.gz  in=403,431,913 out=89,668,501 elapsed=192.9s

  [14084/15692] intraday_8392.csv.gz  in=403,444,435 out=89,681,023 elapsed=192.9s

  [14085/15692] intraday_8390.csv.gz  in=403,457,734 out=89,694,322 elapsed=193.0s

  [14086/15692] intraday_8394.csv.gz  in=403,470,103 out=89,706,691 elapsed=193.0s

  [14087/15692] intraday_8393.csv.gz  in=403,484,493 out=89,721,081 elapsed=193.0s

  [14088/15692] intraday_8395.csv.gz  in=403,496,940 out=89,733,528 elapsed=193.0s

  [14089/15692] intraday_8396.csv.gz  in=403,508,545 out=89,745,133 elapsed=193.0s

  [14090/15692] intraday_8397.csv.gz  in=403,522,003 out=89,758,591 elapsed=193.0s

  [14091/15692] intraday_8398.csv.gz  in=403,532,446 out=89,769,034 elapsed=193.0s

  [14092/15692] intraday_8399.csv.gz  in=403,544,768 out=89,781,356 elapsed=193.0s

  [14093/15692] intraday_8400.csv.gz  in=403,557,351 out=89,793,939 elapsed=193.1s

  [14094/15692] intraday_8402.csv.gz  in=403,569,977 out=89,806,565 elapsed=193.1s

  [14095/15692] intraday_8401.csv.gz  in=403,583,890 out=89,820,478 elapsed=193.1s

  [14096/15692] intraday_8403.csv.gz  in=403,597,935 out=89,834,523 elapsed=193.1s

  [14097/15692] intraday_8404.csv.gz  in=403,609,249 out=89,845,837 elapsed=193.1s

  [14098/15692] intraday_8406.csv.gz  in=403,623,063 out=89,859,651 elapsed=193.1s

  [14099/15692] intraday_8407.csv.gz  in=403,634,705 out=89,871,293 elapsed=193.1s

  [14100/15692] intraday_8405.csv.gz  in=403,646,541 out=89,883,129 elapsed=193.1s

  [14101/15692] intraday_8408.csv.gz  in=403,659,507 out=89,896,095 elapsed=193.2s

  [14102/15692] intraday_8409.csv.gz  in=403,671,380 out=89,907,968 elapsed=193.2s

  [14103/15692] intraday_8410.csv.gz  in=403,683,602 out=89,920,190 elapsed=193.2s

  [14104/15692] intraday_8411.csv.gz  in=403,698,567 out=89,935,155 elapsed=193.2s

  [14105/15692] intraday_8413.csv.gz  in=403,713,200 out=89,949,788 elapsed=193.2s

  [14106/15692] intraday_8412.csv.gz  in=403,725,919 out=89,962,507 elapsed=193.2s

  [14107/15692] intraday_8414.csv.gz  in=403,739,617 out=89,976,205 elapsed=193.2s

  [14108/15692] intraday_8416.csv.gz  in=403,750,280 out=89,986,868 elapsed=193.3s

  [14109/15692] intraday_8415.csv.gz  in=403,762,052 out=89,998,640 elapsed=193.3s

  [14110/15692] intraday_8417.csv.gz  in=403,777,168 out=90,013,756 elapsed=193.3s

  [14111/15692] intraday_8418.csv.gz  in=403,790,900 out=90,027,488 elapsed=193.3s

  [14112/15692] intraday_8419.csv.gz  in=403,802,724 out=90,039,312 elapsed=193.3s

  [14113/15692] intraday_8420.csv.gz  in=403,816,955 out=90,053,543 elapsed=193.3s

  [14114/15692] intraday_8421.csv.gz  in=403,828,368 out=90,064,956 elapsed=193.3s

  [14115/15692] intraday_8423.csv.gz  in=403,839,511 out=90,076,099 elapsed=193.3s

  [14116/15692] intraday_8424.csv.gz  in=403,853,930 out=90,090,518 elapsed=193.4s

  [14117/15692] intraday_8422.csv.gz  in=403,864,974 out=90,101,562 elapsed=193.4s

  [14118/15692] intraday_8425.csv.gz  in=403,877,724 out=90,114,312 elapsed=193.4s

  [14119/15692] intraday_8428.csv.gz  in=403,889,176 out=90,125,764 elapsed=193.4s

  [14120/15692] intraday_8426.csv.gz  in=403,904,264 out=90,140,852 elapsed=193.4s

  [14121/15692] intraday_8427.csv.gz  in=403,917,022 out=90,153,610 elapsed=193.4s

  [14122/15692] intraday_8429.csv.gz  in=403,928,495 out=90,165,083 elapsed=193.4s

  [14123/15692] intraday_8431.csv.gz  in=403,941,219 out=90,177,807 elapsed=193.4s

  [14124/15692] intraday_8432.csv.gz  in=403,955,556 out=90,192,144 elapsed=193.5s

  [14125/15692] intraday_8433.csv.gz  in=403,967,332 out=90,203,920 elapsed=193.5s

  [14126/15692] intraday_8430.csv.gz  in=403,980,429 out=90,217,017 elapsed=193.5s

  [14127/15692] intraday_8434.csv.gz  in=403,990,793 out=90,227,381 elapsed=193.5s

  [14128/15692] intraday_8435.csv.gz  in=404,001,859 out=90,238,447 elapsed=193.5s

  [14129/15692] intraday_8436.csv.gz  in=404,015,747 out=90,252,335 elapsed=193.5s

  [14130/15692] intraday_8437.csv.gz  in=404,026,610 out=90,263,198 elapsed=193.5s

  [14131/15692] intraday_8438.csv.gz  in=404,039,286 out=90,275,874 elapsed=193.5s

  [14132/15692] intraday_8439.csv.gz  in=404,049,490 out=90,286,078 elapsed=193.6s

  [14133/15692] intraday_8440.csv.gz  in=404,060,849 out=90,297,437 elapsed=193.6s

  [14134/15692] intraday_8441.csv.gz  in=404,073,325 out=90,309,913 elapsed=193.6s

  [14135/15692] intraday_8442.csv.gz  in=404,089,140 out=90,325,728 elapsed=193.6s

  [14136/15692] intraday_8444.csv.gz  in=404,102,732 out=90,339,320 elapsed=193.6s

  [14137/15692] intraday_8443.csv.gz  in=404,119,759 out=90,356,347 elapsed=193.6s

  [14138/15692] intraday_8446.csv.gz  in=404,131,574 out=90,368,162 elapsed=193.6s

  [14139/15692] intraday_8445.csv.gz  in=404,143,373 out=90,379,961 elapsed=193.6s

  [14140/15692] intraday_8447.csv.gz  in=404,157,928 out=90,394,516 elapsed=193.7s

  [14141/15692] intraday_8448.csv.gz  in=404,171,942 out=90,408,530 elapsed=193.7s

  [14142/15692] intraday_8449.csv.gz  in=404,186,724 out=90,423,312 elapsed=193.7s

  [14143/15692] intraday_8451.csv.gz  in=404,201,099 out=90,437,687 elapsed=193.7s

  [14144/15692] intraday_8450.csv.gz  in=404,212,795 out=90,449,383 elapsed=193.7s

  [14145/15692] intraday_8452.csv.gz  in=404,227,071 out=90,463,659 elapsed=193.7s

  [14146/15692] intraday_8453.csv.gz  in=404,240,542 out=90,477,130 elapsed=193.8s

  [14147/15692] intraday_8454.csv.gz  in=404,254,795 out=90,491,383 elapsed=193.8s

  [14148/15692] intraday_8455.csv.gz  in=404,267,141 out=90,503,729 elapsed=193.8s

  [14149/15692] intraday_8456.csv.gz  in=404,279,111 out=90,515,699 elapsed=193.8s

  [14150/15692] intraday_8457.csv.gz  in=404,291,963 out=90,528,551 elapsed=193.8s

  [14151/15692] intraday_8458.csv.gz  in=404,306,222 out=90,542,810 elapsed=193.8s

  [14152/15692] intraday_8459.csv.gz  in=404,319,166 out=90,555,754 elapsed=193.8s

  [14153/15692] intraday_8460.csv.gz  in=404,332,587 out=90,569,175 elapsed=193.8s

  [14154/15692] intraday_8461.csv.gz  in=404,347,743 out=90,584,331 elapsed=193.8s

  [14155/15692] intraday_8463.csv.gz  in=404,360,420 out=90,597,008 elapsed=193.9s

  [14156/15692] intraday_8462.csv.gz  in=404,374,240 out=90,610,828 elapsed=193.9s

  [14157/15692] intraday_8464.csv.gz  in=404,386,512 out=90,623,100 elapsed=193.9s

  [14158/15692] intraday_8465.csv.gz  in=404,405,556 out=90,642,144 elapsed=193.9s

  [14159/15692] intraday_8466.csv.gz  in=404,418,386 out=90,654,974 elapsed=193.9s

  [14160/15692] intraday_8467.csv.gz  in=404,431,903 out=90,668,491 elapsed=193.9s

  [14161/15692] intraday_8468.csv.gz  in=404,448,641 out=90,685,229 elapsed=193.9s

  [14162/15692] intraday_8469.csv.gz  in=404,462,455 out=90,699,043 elapsed=193.9s

  [14163/15692] intraday_8471.csv.gz  in=404,476,771 out=90,713,359 elapsed=194.0s

  [14164/15692] intraday_8472.csv.gz  in=404,489,751 out=90,726,339 elapsed=194.0s

  [14165/15692] intraday_8470.csv.gz  in=404,501,752 out=90,738,340 elapsed=194.0s

  [14166/15692] intraday_8473.csv.gz  in=404,515,185 out=90,751,773 elapsed=194.0s

  [14167/15692] intraday_8475.csv.gz  in=404,529,099 out=90,765,687 elapsed=194.0s

  [14168/15692] intraday_8476.csv.gz  in=404,542,873 out=90,779,461 elapsed=194.0s

  [14169/15692] intraday_8474.csv.gz  in=404,562,265 out=90,798,853 elapsed=194.0s

  [14170/15692] intraday_8477.csv.gz  in=404,578,692 out=90,815,280 elapsed=194.0s

  [14171/15692] intraday_8478.csv.gz  in=404,592,003 out=90,828,591 elapsed=194.0s

  [14172/15692] intraday_8480.csv.gz  in=404,604,116 out=90,840,704 elapsed=194.0s

  [14173/15692] intraday_8479.csv.gz  in=404,615,959 out=90,852,547 elapsed=194.1s

  [14174/15692] intraday_8481.csv.gz  in=404,629,143 out=90,865,731 elapsed=194.1s

  [14175/15692] intraday_8483.csv.gz  in=404,641,723 out=90,878,311 elapsed=194.1s

  [14176/15692] intraday_8482.csv.gz  in=404,653,064 out=90,889,652 elapsed=194.1s

  [14177/15692] intraday_8484.csv.gz  in=404,667,053 out=90,903,641 elapsed=194.1s

  [14178/15692] intraday_8485.csv.gz  in=404,683,180 out=90,919,768 elapsed=194.1s

  [14179/15692] intraday_8487.csv.gz  in=404,696,790 out=90,933,378 elapsed=194.2s

  [14180/15692] intraday_8486.csv.gz  in=404,708,441 out=90,945,029 elapsed=194.2s

  [14181/15692] intraday_8488.csv.gz  in=404,719,603 out=90,956,191 elapsed=194.2s

  [14182/15692] intraday_8490.csv.gz  in=404,730,937 out=90,967,525 elapsed=194.2s

  [14183/15692] intraday_8491.csv.gz  in=404,744,512 out=90,981,100 elapsed=194.2s

  [14184/15692] intraday_8489.csv.gz  in=404,759,778 out=90,996,366 elapsed=194.2s

  [14185/15692] intraday_8492.csv.gz  in=404,774,432 out=91,011,020 elapsed=194.2s

  [14186/15692] intraday_8494.csv.gz  in=404,788,809 out=91,025,397 elapsed=194.2s

  [14187/15692] intraday_8493.csv.gz  in=404,803,355 out=91,039,943 elapsed=194.3s

  [14188/15692] intraday_8495.csv.gz  in=404,817,490 out=91,054,078 elapsed=194.3s

  [14189/15692] intraday_8496.csv.gz  in=404,829,486 out=91,066,074 elapsed=194.3s

  [14190/15692] intraday_8497.csv.gz  in=404,843,733 out=91,080,321 elapsed=194.3s

  [14191/15692] intraday_8498.csv.gz  in=404,855,293 out=91,091,881 elapsed=194.3s

  [14192/15692] intraday_8500.csv.gz  in=404,865,713 out=91,102,301 elapsed=194.3s

  [14193/15692] intraday_8499.csv.gz  in=404,880,403 out=91,116,991 elapsed=194.3s

  [14194/15692] intraday_8503.csv.gz  in=404,881,594 out=91,118,182 elapsed=194.3s

  [14195/15692] intraday_8502.csv.gz  in=404,895,475 out=91,132,063 elapsed=194.4s

  [14196/15692] intraday_8501.csv.gz  in=404,904,153 out=91,140,741 elapsed=194.4s

  [14197/15692] intraday_8504.csv.gz  in=404,950,874 out=91,153,695 elapsed=194.4s

  [14198/15692] intraday_8505.csv.gz  in=404,965,037 out=91,159,830 elapsed=194.4s

  [14199/15692] intraday_8506.csv.gz  in=404,979,908 out=91,174,701 elapsed=194.4s

  [14200/15692] intraday_8507.csv.gz  in=404,991,884 out=91,186,677 elapsed=194.4s

  [14201/15692] intraday_8508.csv.gz  in=405,004,813 out=91,199,606 elapsed=194.5s

  [14202/15692] intraday_8509.csv.gz  in=405,015,782 out=91,210,575 elapsed=194.5s

  [14203/15692] intraday_8511.csv.gz  in=405,030,545 out=91,225,338 elapsed=194.5s

  [14204/15692] intraday_8512.csv.gz  in=405,043,986 out=91,238,779 elapsed=194.5s

  [14205/15692] intraday_8510.csv.gz  in=405,056,990 out=91,251,783 elapsed=194.5s

  [14206/15692] intraday_8513.csv.gz  in=405,069,719 out=91,264,512 elapsed=194.5s

  [14207/15692] intraday_8514.csv.gz  in=405,081,397 out=91,276,190 elapsed=194.5s

  [14208/15692] intraday_8515.csv.gz  in=405,095,865 out=91,290,658 elapsed=194.5s

  [14209/15692] intraday_8517.csv.gz  in=405,109,076 out=91,303,869 elapsed=194.6s

  [14210/15692] intraday_8516.csv.gz  in=405,121,992 out=91,316,785 elapsed=194.6s

  [14211/15692] intraday_8519.csv.gz  in=405,134,736 out=91,329,529 elapsed=194.6s

  [14212/15692] intraday_8518.csv.gz  in=405,147,646 out=91,342,439 elapsed=194.6s

  [14213/15692] intraday_8521.csv.gz  in=405,157,945 out=91,352,738 elapsed=194.6s

  [14214/15692] intraday_8520.csv.gz  in=405,167,434 out=91,362,227 elapsed=194.6s

  [14215/15692] intraday_8522.csv.gz  in=405,181,358 out=91,376,151 elapsed=194.6s

  [14216/15692] intraday_8523.csv.gz  in=405,193,627 out=91,388,420 elapsed=194.7s

  [14217/15692] intraday_8524.csv.gz  in=405,204,130 out=91,398,923 elapsed=194.7s

  [14218/15692] intraday_8525.csv.gz  in=405,214,797 out=91,409,590 elapsed=194.7s

  [14219/15692] intraday_8526.csv.gz  in=405,226,969 out=91,421,762 elapsed=194.7s

  [14220/15692] intraday_8528.csv.gz  in=405,238,796 out=91,433,589 elapsed=194.7s

  [14221/15692] intraday_8527.csv.gz  in=405,251,450 out=91,446,243 elapsed=194.7s

  [14222/15692] intraday_8529.csv.gz  in=405,264,881 out=91,459,674 elapsed=194.7s

  [14223/15692] intraday_8530.csv.gz  in=405,277,893 out=91,472,686 elapsed=194.8s

  [14224/15692] intraday_8531.csv.gz  in=405,291,334 out=91,485,925 elapsed=194.8s

  [14225/15692] intraday_8532.csv.gz  in=405,302,653 out=91,497,244 elapsed=194.8s

  [14226/15692] intraday_8534.csv.gz  in=405,314,619 out=91,509,210 elapsed=194.8s

  [14227/15692] intraday_8533.csv.gz  in=405,326,301 out=91,520,892 elapsed=194.8s

  [14228/15692] intraday_8535.csv.gz  in=405,339,712 out=91,534,303 elapsed=194.8s

  [14229/15692] intraday_8536.csv.gz  in=405,355,263 out=91,549,854 elapsed=194.8s

  [14230/15692] intraday_8537.csv.gz  in=405,369,335 out=91,563,926 elapsed=194.8s

  [14231/15692] intraday_8538.csv.gz  in=405,379,963 out=91,574,554 elapsed=194.8s

  [14232/15692] intraday_8539.csv.gz  in=405,392,184 out=91,586,775 elapsed=194.9s

  [14233/15692] intraday_8540.csv.gz  in=405,404,817 out=91,599,408 elapsed=194.9s

  [14234/15692] intraday_8541.csv.gz  in=405,416,332 out=91,610,923 elapsed=194.9s

  [14235/15692] intraday_8542.csv.gz  in=405,427,755 out=91,622,346 elapsed=194.9s

  [14236/15692] intraday_8544.csv.gz  in=405,440,241 out=91,634,832 elapsed=194.9s

  [14237/15692] intraday_8543.csv.gz  in=405,450,491 out=91,645,082 elapsed=194.9s

  [14238/15692] intraday_8545.csv.gz  in=405,460,419 out=91,655,010 elapsed=194.9s

  [14239/15692] intraday_8546.csv.gz  in=405,471,707 out=91,666,298 elapsed=194.9s

  [14240/15692] intraday_8547.csv.gz  in=405,483,590 out=91,678,181 elapsed=194.9s

  [14241/15692] intraday_8549.csv.gz  in=405,495,183 out=91,689,774 elapsed=195.0s

  [14242/15692] intraday_8548.csv.gz  in=405,508,125 out=91,702,716 elapsed=195.0s

  [14243/15692] intraday_8550.csv.gz  in=405,521,309 out=91,715,900 elapsed=195.0s

  [14244/15692] intraday_8551.csv.gz  in=405,531,720 out=91,726,311 elapsed=195.0s

  [14245/15692] intraday_8552.csv.gz  in=405,542,910 out=91,737,501 elapsed=195.0s

  [14246/15692] intraday_8554.csv.gz  in=405,554,640 out=91,749,231 elapsed=195.0s

  [14247/15692] intraday_8556.csv.gz  in=405,566,441 out=91,761,032 elapsed=195.0s

  [14248/15692] intraday_8553.csv.gz  in=405,579,131 out=91,773,722 elapsed=195.0s

  [14249/15692] intraday_8555.csv.gz  in=405,590,446 out=91,785,037 elapsed=195.0s

  [14250/15692] intraday_8557.csv.gz  in=405,601,522 out=91,796,113 elapsed=195.0s

  [14251/15692] intraday_8558.csv.gz  in=405,615,269 out=91,809,860 elapsed=195.0s

  [14252/15692] intraday_8559.csv.gz  in=405,625,216 out=91,819,807 elapsed=195.1s

  [14253/15692] intraday_8560.csv.gz  in=405,638,277 out=91,832,868 elapsed=195.1s

  [14254/15692] intraday_8561.csv.gz  in=405,651,499 out=91,846,090 elapsed=195.1s

  [14255/15692] intraday_8562.csv.gz  in=405,663,245 out=91,857,836 elapsed=195.1s

  [14256/15692] intraday_8563.csv.gz  in=405,673,902 out=91,868,493 elapsed=195.1s

  [14257/15692] intraday_8564.csv.gz  in=405,687,337 out=91,881,928 elapsed=195.1s

  [14258/15692] intraday_8566.csv.gz  in=405,699,968 out=91,894,559 elapsed=195.1s

  [14259/15692] intraday_8565.csv.gz  in=405,711,836 out=91,906,427 elapsed=195.1s

  [14260/15692] intraday_8567.csv.gz  in=405,723,235 out=91,917,826 elapsed=195.1s

  [14261/15692] intraday_8568.csv.gz  in=405,734,623 out=91,929,214 elapsed=195.1s

  [14262/15692] intraday_8569.csv.gz  in=405,745,595 out=91,940,186 elapsed=195.2s

  [14263/15692] intraday_8570.csv.gz  in=405,756,912 out=91,951,503 elapsed=195.2s

  [14264/15692] intraday_8572.csv.gz  in=405,769,451 out=91,964,042 elapsed=195.2s

  [14265/15692] intraday_8573.csv.gz  in=405,784,496 out=91,979,087 elapsed=195.2s

  [14266/15692] intraday_8571.csv.gz  in=405,797,234 out=91,991,825 elapsed=195.2s

  [14267/15692] intraday_8575.csv.gz  in=405,808,806 out=92,003,397 elapsed=195.2s

  [14268/15692] intraday_8574.csv.gz  in=405,820,362 out=92,014,953 elapsed=195.2s

  [14269/15692] intraday_8576.csv.gz  in=405,830,141 out=92,024,732 elapsed=195.2s

  [14270/15692] intraday_8578.csv.gz  in=405,841,839 out=92,036,430 elapsed=195.2s

  [14271/15692] intraday_8577.csv.gz  in=405,854,477 out=92,049,068 elapsed=195.2s

  [14272/15692] intraday_8580.csv.gz  in=405,864,898 out=92,059,489 elapsed=195.3s

  [14273/15692] intraday_8579.csv.gz  in=405,878,482 out=92,073,073 elapsed=195.3s

  [14274/15692] intraday_8581.csv.gz  in=405,889,865 out=92,084,456 elapsed=195.3s

  [14275/15692] intraday_8582.csv.gz  in=405,901,281 out=92,095,872 elapsed=195.3s

  [14276/15692] intraday_8583.csv.gz  in=405,914,187 out=92,108,778 elapsed=195.3s

  [14277/15692] intraday_8584.csv.gz  in=405,925,539 out=92,120,130 elapsed=195.3s

  [14278/15692] intraday_8585.csv.gz  in=405,936,024 out=92,130,615 elapsed=195.3s

  [14279/15692] intraday_8586.csv.gz  in=405,946,481 out=92,141,072 elapsed=195.3s

  [14280/15692] intraday_8587.csv.gz  in=405,956,980 out=92,151,571 elapsed=195.3s

  [14281/15692] intraday_8588.csv.gz  in=405,966,821 out=92,161,412 elapsed=195.3s

  [14282/15692] intraday_8589.csv.gz  in=405,981,329 out=92,175,920 elapsed=195.4s

  [14283/15692] intraday_8591.csv.gz  in=405,995,067 out=92,189,658 elapsed=195.4s

  [14284/15692] intraday_8590.csv.gz  in=406,012,841 out=92,207,432 elapsed=195.4s

  [14285/15692] intraday_8592.csv.gz  in=406,023,211 out=92,217,802 elapsed=195.4s

  [14286/15692] intraday_8594.csv.gz  in=406,037,535 out=92,232,126 elapsed=195.4s

  [14287/15692] intraday_8593.csv.gz  in=406,049,168 out=92,243,759 elapsed=195.4s

  [14288/15692] intraday_8595.csv.gz  in=406,060,753 out=92,255,344 elapsed=195.4s

  [14289/15692] intraday_8596.csv.gz  in=406,075,873 out=92,270,464 elapsed=195.4s

  [14290/15692] intraday_8597.csv.gz  in=406,087,529 out=92,282,120 elapsed=195.5s

  [14291/15692] intraday_8598.csv.gz  in=406,100,326 out=92,294,917 elapsed=195.5s

  [14292/15692] intraday_8600.csv.gz  in=406,114,611 out=92,309,202 elapsed=195.5s

  [14293/15692] intraday_8599.csv.gz  in=406,126,456 out=92,321,047 elapsed=195.5s

  [14294/15692] intraday_8601.csv.gz  in=406,140,034 out=92,334,625 elapsed=195.5s

  [14295/15692] intraday_8603.csv.gz  in=406,152,412 out=92,347,003 elapsed=195.5s

  [14296/15692] intraday_8602.csv.gz  in=406,165,199 out=92,359,790 elapsed=195.5s

  [14297/15692] intraday_8604.csv.gz  in=406,175,910 out=92,370,501 elapsed=195.5s

  [14298/15692] intraday_8605.csv.gz  in=406,189,198 out=92,383,789 elapsed=195.6s

  [14299/15692] intraday_8607.csv.gz  in=406,201,324 out=92,395,915 elapsed=195.6s

  [14300/15692] intraday_8608.csv.gz  in=406,213,750 out=92,408,341 elapsed=195.6s

  [14301/15692] intraday_8606.csv.gz  in=406,226,088 out=92,420,679 elapsed=195.6s

  [14302/15692] intraday_8609.csv.gz  in=406,240,446 out=92,435,037 elapsed=195.6s

  [14303/15692] intraday_8610.csv.gz  in=406,251,862 out=92,446,453 elapsed=195.6s

  [14304/15692] intraday_8611.csv.gz  in=406,264,077 out=92,458,668 elapsed=195.7s

  [14305/15692] intraday_8612.csv.gz  in=406,280,051 out=92,474,642 elapsed=195.7s

  [14306/15692] intraday_8613.csv.gz  in=406,292,036 out=92,486,627 elapsed=195.7s

  [14307/15692] intraday_8615.csv.gz  in=406,305,971 out=92,500,562 elapsed=195.7s

  [14308/15692] intraday_8614.csv.gz  in=406,319,402 out=92,513,993 elapsed=195.7s

  [14309/15692] intraday_8617.csv.gz  in=406,329,698 out=92,524,289 elapsed=195.7s

  [14310/15692] intraday_8616.csv.gz  in=406,345,340 out=92,539,931 elapsed=195.7s

  [14311/15692] intraday_8618.csv.gz  in=406,357,843 out=92,552,434 elapsed=195.7s

  [14312/15692] intraday_8619.csv.gz  in=406,370,646 out=92,565,237 elapsed=195.8s

  [14313/15692] intraday_8620.csv.gz  in=406,383,703 out=92,578,294 elapsed=195.8s

  [14314/15692] intraday_8621.csv.gz  in=406,398,141 out=92,592,732 elapsed=195.8s

  [14315/15692] intraday_8622.csv.gz  in=406,414,583 out=92,609,174 elapsed=195.8s

  [14316/15692] intraday_8624.csv.gz  in=406,428,407 out=92,622,998 elapsed=195.8s

  [14317/15692] intraday_8623.csv.gz  in=406,457,391 out=92,651,982 elapsed=195.8s

  [14318/15692] intraday_8625.csv.gz  in=406,472,981 out=92,667,572 elapsed=195.8s

  [14319/15692] intraday_8626.csv.gz  in=406,485,440 out=92,679,759 elapsed=195.8s

  [14320/15692] intraday_8628.csv.gz  in=406,495,246 out=92,689,565 elapsed=195.9s

  [14321/15692] intraday_8627.csv.gz  in=406,508,659 out=92,702,978 elapsed=195.9s

  [14322/15692] intraday_8630.csv.gz  in=406,518,417 out=92,712,736 elapsed=195.9s

  [14323/15692] intraday_8631.csv.gz  in=406,531,290 out=92,725,609 elapsed=195.9s

  [14324/15692] intraday_8629.csv.gz  in=406,545,881 out=92,740,200 elapsed=195.9s

  [14325/15692] intraday_8632.csv.gz  in=406,559,005 out=92,753,324 elapsed=195.9s

  [14326/15692] intraday_8633.csv.gz  in=406,573,804 out=92,768,123 elapsed=195.9s

  [14327/15692] intraday_8634.csv.gz  in=406,584,977 out=92,779,296 elapsed=195.9s

  [14328/15692] intraday_8635.csv.gz  in=406,597,073 out=92,791,392 elapsed=195.9s

  [14329/15692] intraday_8636.csv.gz  in=406,608,683 out=92,803,002 elapsed=196.0s

  [14330/15692] intraday_8637.csv.gz  in=406,620,856 out=92,815,175 elapsed=196.0s

  [14331/15692] intraday_8638.csv.gz  in=406,631,849 out=92,826,168 elapsed=196.0s

  [14332/15692] intraday_8640.csv.gz  in=406,646,490 out=92,840,809 elapsed=196.0s

  [14333/15692] intraday_8639.csv.gz  in=406,660,881 out=92,855,200 elapsed=196.0s

  [14334/15692] intraday_8641.csv.gz  in=406,673,522 out=92,867,841 elapsed=196.0s

  [14335/15692] intraday_8642.csv.gz  in=406,688,551 out=92,882,870 elapsed=196.0s

  [14336/15692] intraday_8644.csv.gz  in=406,700,681 out=92,895,000 elapsed=196.1s

  [14337/15692] intraday_8643.csv.gz  in=406,713,370 out=92,907,689 elapsed=196.1s

  [14338/15692] intraday_8645.csv.gz  in=406,727,119 out=92,921,438 elapsed=196.1s

  [14339/15692] intraday_8646.csv.gz  in=406,738,105 out=92,932,424 elapsed=196.1s

  [14340/15692] intraday_8647.csv.gz  in=406,749,411 out=92,943,730 elapsed=196.1s

  [14341/15692] intraday_8648.csv.gz  in=406,756,400 out=92,950,719 elapsed=196.1s

  [14342/15692] intraday_8649.csv.gz  in=406,767,651 out=92,961,970 elapsed=196.1s

  [14343/15692] intraday_8650.csv.gz  in=406,775,437 out=92,969,756 elapsed=196.1s

  [14344/15692] intraday_8651.csv.gz  in=406,790,717 out=92,970,515 elapsed=196.1s

  [14345/15692] intraday_8653.csv.gz  in=406,803,119 out=92,982,917 elapsed=196.2s

  [14346/15692] intraday_8652.csv.gz  in=406,818,590 out=92,998,388 elapsed=196.2s

  [14347/15692] intraday_8654.csv.gz  in=406,831,519 out=93,011,317 elapsed=196.2s

  [14348/15692] intraday_8655.csv.gz  in=406,843,886 out=93,023,684 elapsed=196.2s

  [14349/15692] intraday_8656.csv.gz  in=406,855,577 out=93,035,375 elapsed=196.2s

  [14350/15692] intraday_8657.csv.gz  in=406,870,661 out=93,050,459 elapsed=196.2s

  [14351/15692] intraday_8658.csv.gz  in=406,885,482 out=93,065,280 elapsed=196.2s

  [14352/15692] intraday_8661.csv.gz  in=406,899,675 out=93,079,473 elapsed=196.3s

  [14353/15692] intraday_8659.csv.gz  in=406,911,553 out=93,091,351 elapsed=196.3s

  [14354/15692] intraday_8660.csv.gz  in=406,924,491 out=93,104,289 elapsed=196.3s

  [14355/15692] intraday_8662.csv.gz  in=406,938,583 out=93,118,381 elapsed=196.3s

  [14356/15692] intraday_8663.csv.gz  in=406,951,701 out=93,131,499 elapsed=196.3s

  [14357/15692] intraday_8664.csv.gz  in=406,965,882 out=93,145,680 elapsed=196.3s

  [14358/15692] intraday_8666.csv.gz  in=406,975,443 out=93,155,241 elapsed=196.3s

  [14359/15692] intraday_8665.csv.gz  in=406,989,473 out=93,169,271 elapsed=196.3s

  [14360/15692] intraday_8667.csv.gz  in=407,001,361 out=93,181,159 elapsed=196.4s

  [14361/15692] intraday_8668.csv.gz  in=407,014,984 out=93,194,782 elapsed=196.4s

  [14362/15692] intraday_8669.csv.gz  in=407,028,673 out=93,208,471 elapsed=196.4s

  [14363/15692] intraday_8670.csv.gz  in=407,040,355 out=93,220,153 elapsed=196.4s

  [14364/15692] intraday_8672.csv.gz  in=407,051,244 out=93,231,042 elapsed=196.4s

  [14365/15692] intraday_8671.csv.gz  in=407,062,886 out=93,242,684 elapsed=196.4s

  [14366/15692] intraday_8673.csv.gz  in=407,077,578 out=93,257,376 elapsed=196.4s

  [14367/15692] intraday_8674.csv.gz  in=407,089,869 out=93,269,667 elapsed=196.5s

  [14368/15692] intraday_8675.csv.gz  in=407,103,006 out=93,282,804 elapsed=196.5s

  [14369/15692] intraday_8676.csv.gz  in=407,116,642 out=93,296,440 elapsed=196.5s

  [14370/15692] intraday_8677.csv.gz  in=407,129,188 out=93,308,986 elapsed=196.5s

  [14371/15692] intraday_8678.csv.gz  in=407,142,122 out=93,321,920 elapsed=196.5s

  [14372/15692] intraday_8679.csv.gz  in=407,153,569 out=93,333,367 elapsed=196.5s

  [14373/15692] intraday_8681.csv.gz  in=407,166,874 out=93,346,672 elapsed=196.5s

  [14374/15692] intraday_8680.csv.gz  in=407,178,948 out=93,358,746 elapsed=196.5s

  [14375/15692] intraday_8682.csv.gz  in=407,196,068 out=93,375,866 elapsed=196.6s

  [14376/15692] intraday_8683.csv.gz  in=407,210,595 out=93,390,393 elapsed=196.6s

  [14377/15692] intraday_8684.csv.gz  in=407,220,968 out=93,400,766 elapsed=196.6s

  [14378/15692] intraday_8685.csv.gz  in=407,233,156 out=93,412,954 elapsed=196.6s

  [14379/15692] intraday_8687.csv.gz  in=407,244,327 out=93,424,125 elapsed=196.6s

  [14380/15692] intraday_8686.csv.gz  in=407,257,822 out=93,437,620 elapsed=196.6s

  [14381/15692] intraday_8688.csv.gz  in=407,270,122 out=93,449,920 elapsed=196.6s

  [14382/15692] intraday_8689.csv.gz  in=407,280,861 out=93,460,659 elapsed=196.6s

  [14383/15692] intraday_8691.csv.gz  in=407,291,502 out=93,471,300 elapsed=196.6s

  [14384/15692] intraday_8690.csv.gz  in=407,304,239 out=93,484,037 elapsed=196.6s

  [14385/15692] intraday_8692.csv.gz  in=407,316,191 out=93,495,989 elapsed=196.7s

  [14386/15692] intraday_8693.csv.gz  in=407,328,118 out=93,507,916 elapsed=196.7s

  [14387/15692] intraday_8694.csv.gz  in=407,341,732 out=93,521,530 elapsed=196.7s

  [14388/15692] intraday_8695.csv.gz  in=407,353,765 out=93,533,563 elapsed=196.7s

  [14389/15692] intraday_8697.csv.gz  in=407,364,633 out=93,544,431 elapsed=196.7s

  [14390/15692] intraday_8696.csv.gz  in=407,379,189 out=93,558,987 elapsed=196.7s

  [14391/15692] intraday_8698.csv.gz  in=407,391,216 out=93,571,014 elapsed=196.7s

  [14392/15692] intraday_8700.csv.gz  in=407,402,582 out=93,582,380 elapsed=196.7s

  [14393/15692] intraday_8699.csv.gz  in=407,415,933 out=93,595,731 elapsed=196.7s

  [14394/15692] intraday_8702.csv.gz  in=407,428,132 out=93,607,930 elapsed=196.8s

  [14395/15692] intraday_8701.csv.gz  in=407,439,573 out=93,619,371 elapsed=196.8s

  [14396/15692] intraday_8703.csv.gz  in=407,450,411 out=93,630,209 elapsed=196.8s

  [14397/15692] intraday_8704.csv.gz  in=407,465,872 out=93,645,670 elapsed=196.8s

  [14398/15692] intraday_8707.csv.gz  in=407,479,072 out=93,658,870 elapsed=196.8s

  [14399/15692] intraday_8705.csv.gz  in=407,490,576 out=93,670,374 elapsed=196.8s

  [14400/15692] intraday_8706.csv.gz  in=407,503,488 out=93,683,286 elapsed=196.8s

  [14401/15692] intraday_8708.csv.gz  in=407,515,301 out=93,695,099 elapsed=196.8s

  [14402/15692] intraday_8709.csv.gz  in=407,526,004 out=93,705,802 elapsed=196.8s

  [14403/15692] intraday_8710.csv.gz  in=407,539,777 out=93,719,575 elapsed=196.8s

  [14404/15692] intraday_8711.csv.gz  in=407,553,086 out=93,732,884 elapsed=196.9s

  [14405/15692] intraday_8712.csv.gz  in=407,564,573 out=93,744,371 elapsed=196.9s

  [14406/15692] intraday_8713.csv.gz  in=407,577,889 out=93,757,687 elapsed=196.9s

  [14407/15692] intraday_8714.csv.gz  in=407,589,267 out=93,769,065 elapsed=196.9s

  [14408/15692] intraday_8715.csv.gz  in=407,601,930 out=93,781,728 elapsed=196.9s

  [14409/15692] intraday_8716.csv.gz  in=407,612,590 out=93,792,388 elapsed=196.9s

  [14410/15692] intraday_8717.csv.gz  in=407,627,700 out=93,807,480 elapsed=196.9s

  [14411/15692] intraday_8720.csv.gz  in=407,639,511 out=93,819,291 elapsed=197.0s

  [14412/15692] intraday_8718.csv.gz  in=407,652,482 out=93,832,262 elapsed=197.0s

  [14413/15692] intraday_8721.csv.gz  in=407,663,907 out=93,843,687 elapsed=197.0s

  [14414/15692] intraday_8719.csv.gz  in=407,681,662 out=93,861,442 elapsed=197.0s

  [14415/15692] intraday_8722.csv.gz  in=407,692,242 out=93,872,022 elapsed=197.0s

  [14416/15692] intraday_8724.csv.gz  in=407,704,644 out=93,884,424 elapsed=197.0s

  [14417/15692] intraday_8723.csv.gz  in=407,717,710 out=93,897,490 elapsed=197.0s

  [14418/15692] intraday_8726.csv.gz  in=407,728,530 out=93,908,310 elapsed=197.0s

  [14419/15692] intraday_8725.csv.gz  in=407,742,634 out=93,922,414 elapsed=197.1s

  [14420/15692] intraday_8727.csv.gz  in=407,755,248 out=93,935,028 elapsed=197.1s

  [14421/15692] intraday_8728.csv.gz  in=407,766,411 out=93,946,191 elapsed=197.1s

  [14422/15692] intraday_8729.csv.gz  in=407,780,437 out=93,960,217 elapsed=197.1s

  [14423/15692] intraday_8730.csv.gz  in=407,790,790 out=93,970,570 elapsed=197.1s

  [14424/15692] intraday_8732.csv.gz  in=407,801,992 out=93,981,772 elapsed=197.1s

  [14425/15692] intraday_8731.csv.gz  in=407,813,662 out=93,993,442 elapsed=197.1s

  [14426/15692] intraday_8733.csv.gz  in=407,824,064 out=94,003,844 elapsed=197.1s

  [14427/15692] intraday_8734.csv.gz  in=407,835,162 out=94,014,942 elapsed=197.2s

  [14428/15692] intraday_8735.csv.gz  in=407,851,263 out=94,031,043 elapsed=197.2s

  [14429/15692] intraday_8737.csv.gz  in=407,864,505 out=94,044,285 elapsed=197.2s

  [14430/15692] intraday_8736.csv.gz  in=407,880,592 out=94,060,372 elapsed=197.2s

  [14431/15692] intraday_8738.csv.gz  in=407,891,929 out=94,071,709 elapsed=197.2s

  [14432/15692] intraday_8739.csv.gz  in=407,904,565 out=94,084,345 elapsed=197.2s

  [14433/15692] intraday_8740.csv.gz  in=407,918,331 out=94,098,111 elapsed=197.2s

  [14434/15692] intraday_8741.csv.gz  in=407,930,405 out=94,110,185 elapsed=197.2s

  [14435/15692] intraday_8742.csv.gz  in=407,945,388 out=94,125,168 elapsed=197.3s

  [14436/15692] intraday_8743.csv.gz  in=407,957,572 out=94,137,352 elapsed=197.3s

  [14437/15692] intraday_8744.csv.gz  in=407,972,184 out=94,151,964 elapsed=197.3s

  [14438/15692] intraday_8745.csv.gz  in=407,985,345 out=94,165,125 elapsed=197.3s

  [14439/15692] intraday_8746.csv.gz  in=407,998,367 out=94,178,147 elapsed=197.3s

  [14440/15692] intraday_8747.csv.gz  in=408,011,990 out=94,191,770 elapsed=197.3s

  [14441/15692] intraday_8748.csv.gz  in=408,024,092 out=94,203,872 elapsed=197.3s

  [14442/15692] intraday_8749.csv.gz  in=408,042,369 out=94,217,732 elapsed=197.4s

  [14443/15692] intraday_8751.csv.gz  in=408,055,267 out=94,229,747 elapsed=197.4s

  [14444/15692] intraday_8752.csv.gz  in=408,066,709 out=94,241,189 elapsed=197.4s

  [14445/15692] intraday_8750.csv.gz  in=408,078,732 out=94,253,212 elapsed=197.4s

  [14446/15692] intraday_8753.csv.gz  in=408,092,440 out=94,266,920 elapsed=197.4s

  [14447/15692] intraday_8756.csv.gz  in=408,104,030 out=94,278,510 elapsed=197.4s

  [14448/15692] intraday_8755.csv.gz  in=408,121,333 out=94,293,175 elapsed=197.5s

  [14449/15692] intraday_8754.csv.gz  in=408,133,641 out=94,305,483 elapsed=197.5s

  [14450/15692] intraday_8757.csv.gz  in=408,146,234 out=94,318,076 elapsed=197.5s

  [14451/15692] intraday_8758.csv.gz  in=408,162,042 out=94,333,884 elapsed=197.5s

  [14452/15692] intraday_8759.csv.gz  in=408,174,621 out=94,346,463 elapsed=197.5s

  [14453/15692] intraday_8760.csv.gz  in=408,187,173 out=94,359,015 elapsed=197.5s

  [14454/15692] intraday_8761.csv.gz  in=408,202,303 out=94,374,145 elapsed=197.5s

  [14455/15692] intraday_8762.csv.gz  in=408,217,529 out=94,389,371 elapsed=197.5s

  [14456/15692] intraday_8764.csv.gz  in=408,230,648 out=94,402,490 elapsed=197.6s

  [14457/15692] intraday_8765.csv.gz  in=408,243,560 out=94,415,402 elapsed=197.6s

  [14458/15692] intraday_8766.csv.gz  in=408,256,023 out=94,427,865 elapsed=197.6s

  [14459/15692] intraday_8763.csv.gz  in=408,266,942 out=94,438,784 elapsed=197.6s

  [14460/15692] intraday_8767.csv.gz  in=408,282,257 out=94,454,099 elapsed=197.6s

  [14461/15692] intraday_8768.csv.gz  in=408,297,865 out=94,469,707 elapsed=197.6s

  [14462/15692] intraday_8770.csv.gz  in=408,313,222 out=94,485,064 elapsed=197.6s

  [14463/15692] intraday_8771.csv.gz  in=408,327,592 out=94,499,434 elapsed=197.7s

  [14464/15692] intraday_8772.csv.gz  in=408,340,195 out=94,512,037 elapsed=197.7s

  [14465/15692] intraday_8769.csv.gz  in=408,361,787 out=94,533,629 elapsed=197.7s

  [14466/15692] intraday_8774.csv.gz  in=408,372,420 out=94,544,262 elapsed=197.7s

  [14467/15692] intraday_8773.csv.gz  in=408,384,872 out=94,556,714 elapsed=197.7s

  [14468/15692] intraday_8775.csv.gz  in=408,399,496 out=94,571,338 elapsed=197.7s

  [14469/15692] intraday_8776.csv.gz  in=408,410,543 out=94,582,385 elapsed=197.7s

  [14470/15692] intraday_8777.csv.gz  in=408,423,341 out=94,595,183 elapsed=197.7s

  [14471/15692] intraday_8778.csv.gz  in=408,437,204 out=94,609,046 elapsed=197.8s

  [14472/15692] intraday_8779.csv.gz  in=408,451,738 out=94,623,580 elapsed=197.8s

  [14473/15692] intraday_8780.csv.gz  in=408,462,901 out=94,634,743 elapsed=197.8s

  [14474/15692] intraday_8781.csv.gz  in=408,474,747 out=94,646,589 elapsed=197.8s

  [14475/15692] intraday_8782.csv.gz  in=408,486,721 out=94,658,563 elapsed=197.8s

  [14476/15692] intraday_8783.csv.gz  in=408,498,976 out=94,670,818 elapsed=197.8s

  [14477/15692] intraday_8785.csv.gz  in=408,513,061 out=94,684,903 elapsed=197.8s

  [14478/15692] intraday_8784.csv.gz  in=408,524,649 out=94,696,491 elapsed=197.9s

  [14479/15692] intraday_8786.csv.gz  in=408,539,529 out=94,711,371 elapsed=197.9s

  [14480/15692] intraday_8787.csv.gz  in=408,553,227 out=94,725,069 elapsed=197.9s

  [14481/15692] intraday_8789.csv.gz  in=408,565,499 out=94,737,341 elapsed=197.9s

  [14482/15692] intraday_8790.csv.gz  in=408,577,368 out=94,749,210 elapsed=197.9s

  [14483/15692] intraday_8791.csv.gz  in=408,591,597 out=94,763,439 elapsed=197.9s

  [14484/15692] intraday_8788.csv.gz  in=408,606,348 out=94,778,190 elapsed=197.9s

  [14485/15692] intraday_8792.csv.gz  in=408,617,591 out=94,789,390 elapsed=197.9s

  [14486/15692] intraday_8793.csv.gz  in=408,629,224 out=94,801,023 elapsed=197.9s

  [14487/15692] intraday_8794.csv.gz  in=408,635,829 out=94,807,628 elapsed=198.0s

  [14488/15692] intraday_8795.csv.gz  in=408,648,764 out=94,820,563 elapsed=198.0s

  [14489/15692] intraday_8796.csv.gz  in=408,655,422 out=94,827,221 elapsed=198.0s

  [14490/15692] intraday_8797.csv.gz  in=408,670,814 out=94,842,613 elapsed=198.0s

  [14491/15692] intraday_8798.csv.gz  in=408,682,680 out=94,854,479 elapsed=198.0s

  [14492/15692] intraday_8800.csv.gz  in=408,693,078 out=94,864,877 elapsed=198.0s

  [14493/15692] intraday_8801.csv.gz  in=408,705,313 out=94,877,112 elapsed=198.0s

  [14494/15692] intraday_8799.csv.gz  in=408,719,651 out=94,891,450 elapsed=198.0s

  [14495/15692] intraday_8802.csv.gz  in=408,735,210 out=94,907,009 elapsed=198.1s

  [14496/15692] intraday_8803.csv.gz  in=408,749,393 out=94,921,192 elapsed=198.1s

  [14497/15692] intraday_8805.csv.gz  in=408,761,875 out=94,933,674 elapsed=198.1s

  [14498/15692] intraday_8804.csv.gz  in=408,773,474 out=94,945,273 elapsed=198.1s

  [14499/15692] intraday_8806.csv.gz  in=408,788,206 out=94,960,005 elapsed=198.1s

  [14500/15692] intraday_8807.csv.gz  in=408,802,471 out=94,973,336 elapsed=198.1s

  [14501/15692] intraday_8809.csv.gz  in=408,815,945 out=94,986,810 elapsed=198.1s

  [14502/15692] intraday_8810.csv.gz  in=408,830,260 out=95,001,125 elapsed=198.2s

  [14503/15692] intraday_8808.csv.gz  in=408,844,186 out=95,015,051 elapsed=198.2s

  [14504/15692] intraday_8811.csv.gz  in=408,854,080 out=95,024,945 elapsed=198.2s

  [14505/15692] intraday_8812.csv.gz  in=408,865,918 out=95,036,783 elapsed=198.2s

  [14506/15692] intraday_8813.csv.gz  in=408,879,832 out=95,050,697 elapsed=198.2s

  [14507/15692] intraday_8815.csv.gz  in=408,892,093 out=95,062,958 elapsed=198.2s

  [14508/15692] intraday_8816.csv.gz  in=408,903,289 out=95,074,154 elapsed=198.2s

  [14509/15692] intraday_8814.csv.gz  in=408,915,534 out=95,086,399 elapsed=198.2s

  [14510/15692] intraday_8817.csv.gz  in=408,927,667 out=95,098,532 elapsed=198.2s

  [14511/15692] intraday_8818.csv.gz  in=408,941,804 out=95,112,669 elapsed=198.3s

  [14512/15692] intraday_8821.csv.gz  in=408,955,227 out=95,126,092 elapsed=198.3s

  [14513/15692] intraday_8820.csv.gz  in=408,968,863 out=95,139,728 elapsed=198.3s

  [14514/15692] intraday_8819.csv.gz  in=408,981,637 out=95,152,502 elapsed=198.3s

  [14515/15692] intraday_8822.csv.gz  in=408,994,941 out=95,165,752 elapsed=198.3s

  [14516/15692] intraday_8823.csv.gz  in=409,007,335 out=95,178,146 elapsed=198.3s

  [14517/15692] intraday_8824.csv.gz  in=409,019,325 out=95,190,136 elapsed=198.3s

  [14518/15692] intraday_8826.csv.gz  in=409,033,377 out=95,204,188 elapsed=198.3s

  [14519/15692] intraday_8825.csv.gz  in=409,050,349 out=95,216,746 elapsed=198.3s

  [14520/15692] intraday_8827.csv.gz  in=409,066,159 out=95,232,556 elapsed=198.4s

  [14521/15692] intraday_8828.csv.gz  in=409,079,701 out=95,246,098 elapsed=198.4s

  [14522/15692] intraday_8830.csv.gz  in=409,092,136 out=95,258,533 elapsed=198.4s

  [14523/15692] intraday_8829.csv.gz  in=409,103,576 out=95,269,973 elapsed=198.4s

  [14524/15692] intraday_8831.csv.gz  in=409,116,495 out=95,282,892 elapsed=198.4s

  [14525/15692] intraday_8832.csv.gz  in=409,127,456 out=95,293,853 elapsed=198.4s

  [14526/15692] intraday_8833.csv.gz  in=409,140,323 out=95,306,720 elapsed=198.4s

  [14527/15692] intraday_8834.csv.gz  in=409,151,001 out=95,317,398 elapsed=198.4s

  [14528/15692] intraday_8835.csv.gz  in=409,163,267 out=95,329,664 elapsed=198.4s

  [14529/15692] intraday_8836.csv.gz  in=409,174,320 out=95,340,717 elapsed=198.4s

  [14530/15692] intraday_8837.csv.gz  in=409,186,147 out=95,352,544 elapsed=198.5s

  [14531/15692] intraday_8839.csv.gz  in=409,199,890 out=95,366,287 elapsed=198.5s

  [14532/15692] intraday_8838.csv.gz  in=409,212,240 out=95,378,637 elapsed=198.5s

  [14533/15692] intraday_8840.csv.gz  in=409,224,337 out=95,390,734 elapsed=198.5s

  [14534/15692] intraday_8841.csv.gz  in=409,238,115 out=95,404,512 elapsed=198.5s

  [14535/15692] intraday_8842.csv.gz  in=409,249,270 out=95,415,667 elapsed=198.5s

  [14536/15692] intraday_8843.csv.gz  in=409,260,383 out=95,426,780 elapsed=198.5s

  [14537/15692] intraday_8845.csv.gz  in=409,270,894 out=95,437,291 elapsed=198.5s

  [14538/15692] intraday_8844.csv.gz  in=409,284,528 out=95,450,925 elapsed=198.5s

  [14539/15692] intraday_8846.csv.gz  in=409,296,282 out=95,462,679 elapsed=198.5s

  [14540/15692] intraday_8847.csv.gz  in=409,308,319 out=95,474,716 elapsed=198.5s

  [14541/15692] intraday_8848.csv.gz  in=409,319,736 out=95,486,133 elapsed=198.6s

  [14542/15692] intraday_8849.csv.gz  in=409,335,618 out=95,502,015 elapsed=198.6s

  [14543/15692] intraday_8850.csv.gz  in=409,349,042 out=95,512,989 elapsed=198.6s

  [14544/15692] intraday_8851.csv.gz  in=409,362,429 out=95,526,376 elapsed=198.6s

  [14545/15692] intraday_8853.csv.gz  in=409,376,507 out=95,538,827 elapsed=198.6s

  [14546/15692] intraday_8854.csv.gz  in=409,387,639 out=95,549,959 elapsed=198.6s

  [14547/15692] intraday_8852.csv.gz  in=409,407,174 out=95,564,758 elapsed=198.6s

  [14548/15692] intraday_8855.csv.gz  in=409,419,382 out=95,576,966 elapsed=198.6s

  [14549/15692] intraday_8859.csv.gz  in=409,430,442 out=95,588,026 elapsed=198.7s

  [14550/15692] intraday_8858.csv.gz  in=409,447,403 out=95,603,764 elapsed=198.7s

  [14551/15692] intraday_8857.csv.gz  in=409,459,837 out=95,616,198 elapsed=198.7s

  [14552/15692] intraday_8856.csv.gz  in=409,472,535 out=95,628,896 elapsed=198.7s

  [14553/15692] intraday_8860.csv.gz  in=409,485,297 out=95,641,658 elapsed=198.8s

  [14554/15692] intraday_8863.csv.gz  in=409,497,356 out=95,653,717 elapsed=198.8s

  [14555/15692] intraday_8862.csv.gz  in=409,512,733 out=95,669,094 elapsed=198.8s

  [14556/15692] intraday_8861.csv.gz  in=409,523,604 out=95,679,965 elapsed=198.8s

  [14557/15692] intraday_8866.csv.gz  in=409,534,751 out=95,691,112 elapsed=198.8s

  [14558/15692] intraday_8867.csv.gz  in=409,544,028 out=95,700,389 elapsed=198.8s

  [14559/15692] intraday_8864.csv.gz  in=409,558,011 out=95,714,372 elapsed=198.8s

  [14560/15692] intraday_8865.csv.gz  in=409,571,641 out=95,728,002 elapsed=198.8s

  [14561/15692] intraday_8868.csv.gz  in=409,583,637 out=95,739,998 elapsed=198.8s

  [14562/15692] intraday_8869.csv.gz  in=409,596,727 out=95,753,088 elapsed=198.9s

  [14563/15692] intraday_8870.csv.gz  in=409,610,534 out=95,766,895 elapsed=198.9s

  [14564/15692] intraday_8871.csv.gz  in=409,625,067 out=95,779,597 elapsed=198.9s

  [14565/15692] intraday_8872.csv.gz  in=409,637,805 out=95,792,335 elapsed=198.9s

  [14566/15692] intraday_8873.csv.gz  in=409,651,016 out=95,805,546 elapsed=198.9s

  [14567/15692] intraday_8874.csv.gz  in=409,664,673 out=95,819,203 elapsed=198.9s

  [14568/15692] intraday_8875.csv.gz  in=409,675,383 out=95,829,913 elapsed=198.9s

  [14569/15692] intraday_8876.csv.gz  in=409,687,098 out=95,841,628 elapsed=199.0s

  [14570/15692] intraday_8877.csv.gz  in=409,703,138 out=95,853,221 elapsed=199.0s

  [14571/15692] intraday_8878.csv.gz  in=409,714,458 out=95,863,431 elapsed=199.0s

  [14572/15692] intraday_8880.csv.gz  in=409,728,032 out=95,877,005 elapsed=199.0s

  [14573/15692] intraday_8879.csv.gz  in=409,739,425 out=95,888,398 elapsed=199.0s

  [14574/15692] intraday_8882.csv.gz  in=409,752,291 out=95,901,264 elapsed=199.0s

  [14575/15692] intraday_8883.csv.gz  in=409,763,941 out=95,912,914 elapsed=199.0s

  [14576/15692] intraday_8881.csv.gz  in=409,782,285 out=95,931,258 elapsed=199.1s

  [14577/15692] intraday_8884.csv.gz  in=409,794,820 out=95,943,793 elapsed=199.1s

  [14578/15692] intraday_8885.csv.gz  in=409,809,375 out=95,958,348 elapsed=199.1s

  [14579/15692] intraday_8886.csv.gz  in=409,821,912 out=95,970,885 elapsed=199.1s

  [14580/15692] intraday_8887.csv.gz  in=409,837,147 out=95,986,120 elapsed=199.1s

  [14581/15692] intraday_8888.csv.gz  in=409,850,775 out=95,999,748 elapsed=199.1s

  [14582/15692] intraday_8889.csv.gz  in=409,863,641 out=96,012,614 elapsed=199.2s

  [14583/15692] intraday_8891.csv.gz  in=409,876,990 out=96,025,963 elapsed=199.2s

  [14584/15692] intraday_8890.csv.gz  in=409,889,626 out=96,038,599 elapsed=199.2s

  [14585/15692] intraday_8892.csv.gz  in=409,904,031 out=96,051,769 elapsed=199.2s

  [14586/15692] intraday_8894.csv.gz  in=409,917,671 out=96,065,409 elapsed=199.2s

  [14587/15692] intraday_8895.csv.gz  in=409,928,776 out=96,076,514 elapsed=199.2s

  [14588/15692] intraday_8893.csv.gz  in=409,942,126 out=96,089,864 elapsed=199.2s

  [14589/15692] intraday_8896.csv.gz  in=409,967,100 out=96,103,773 elapsed=199.3s

  [14590/15692] intraday_8898.csv.gz  in=409,978,522 out=96,115,195 elapsed=199.3s

  [14591/15692] intraday_8897.csv.gz  in=409,991,881 out=96,128,554 elapsed=199.3s

  [14592/15692] intraday_8899.csv.gz  in=410,006,679 out=96,142,682 elapsed=199.3s

  [14593/15692] intraday_8900.csv.gz  in=410,020,054 out=96,156,057 elapsed=199.3s

  [14594/15692] intraday_8901.csv.gz  in=410,033,993 out=96,169,996 elapsed=199.3s

  [14595/15692] intraday_8902.csv.gz  in=410,046,232 out=96,182,235 elapsed=199.3s

  [14596/15692] intraday_8903.csv.gz  in=410,059,833 out=96,195,836 elapsed=199.3s

  [14597/15692] intraday_8904.csv.gz  in=410,073,064 out=96,209,067 elapsed=199.3s

  [14598/15692] intraday_8905.csv.gz  in=410,085,456 out=96,221,459 elapsed=199.4s

  [14599/15692] intraday_8907.csv.gz  in=410,100,436 out=96,236,439 elapsed=199.4s

  [14600/15692] intraday_8908.csv.gz  in=410,112,215 out=96,248,218 elapsed=199.4s

  [14601/15692] intraday_8909.csv.gz  in=410,124,395 out=96,260,398 elapsed=199.4s

  [14602/15692] intraday_8906.csv.gz  in=410,139,881 out=96,275,884 elapsed=199.4s

  [14603/15692] intraday_8910.csv.gz  in=410,154,380 out=96,290,383 elapsed=199.4s

  [14604/15692] intraday_8911.csv.gz  in=410,165,731 out=96,301,734 elapsed=199.4s

  [14605/15692] intraday_8912.csv.gz  in=410,180,972 out=96,316,975 elapsed=199.5s

  [14606/15692] intraday_8913.csv.gz  in=410,197,242 out=96,333,245 elapsed=199.5s

  [14607/15692] intraday_8915.csv.gz  in=410,210,793 out=96,346,796 elapsed=199.5s

  [14608/15692] intraday_8914.csv.gz  in=410,233,552 out=96,368,143 elapsed=199.5s

  [14609/15692] intraday_8916.csv.gz  in=410,250,286 out=96,384,877 elapsed=199.5s

  [14610/15692] intraday_8917.csv.gz  in=410,262,135 out=96,396,726 elapsed=199.5s

  [14611/15692] intraday_8918.csv.gz  in=410,275,496 out=96,410,087 elapsed=199.5s

  [14612/15692] intraday_8919.csv.gz  in=410,286,807 out=96,421,398 elapsed=199.5s

  [14613/15692] intraday_8920.csv.gz  in=410,300,120 out=96,434,711 elapsed=199.6s

  [14614/15692] intraday_8922.csv.gz  in=410,313,833 out=96,448,424 elapsed=199.6s

  [14615/15692] intraday_8923.csv.gz  in=410,326,259 out=96,460,850 elapsed=199.6s

  [14616/15692] intraday_8921.csv.gz  in=410,337,416 out=96,472,007 elapsed=199.6s

  [14617/15692] intraday_8924.csv.gz  in=410,353,416 out=96,488,007 elapsed=199.6s

  [14618/15692] intraday_8926.csv.gz  in=410,365,962 out=96,500,553 elapsed=199.6s

  [14619/15692] intraday_8925.csv.gz  in=410,376,911 out=96,511,502 elapsed=199.6s

  [14620/15692] intraday_8928.csv.gz  in=410,390,078 out=96,524,669 elapsed=199.6s

  [14621/15692] intraday_8927.csv.gz  in=410,400,975 out=96,535,566 elapsed=199.7s

  [14622/15692] intraday_8929.csv.gz  in=410,412,949 out=96,547,540 elapsed=199.7s

  [14623/15692] intraday_8930.csv.gz  in=410,427,106 out=96,561,697 elapsed=199.7s

  [14624/15692] intraday_8932.csv.gz  in=410,440,450 out=96,575,041 elapsed=199.7s

  [14625/15692] intraday_8931.csv.gz  in=410,454,949 out=96,589,540 elapsed=199.7s

  [14626/15692] intraday_8934.csv.gz  in=410,467,845 out=96,602,436 elapsed=199.8s

  [14627/15692] intraday_8933.csv.gz  in=410,482,388 out=96,616,979 elapsed=199.8s

  [14628/15692] intraday_8936.csv.gz  in=410,495,485 out=96,630,076 elapsed=199.8s

  [14629/15692] intraday_8935.csv.gz  in=410,507,318 out=96,641,909 elapsed=199.8s

  [14630/15692] intraday_8937.csv.gz  in=410,517,924 out=96,652,515 elapsed=199.8s

  [14631/15692] intraday_8938.csv.gz  in=410,531,674 out=96,666,265 elapsed=199.8s

  [14632/15692] intraday_8939.csv.gz  in=410,539,080 out=96,673,671 elapsed=199.8s

  [14633/15692] intraday_8940.csv.gz  in=410,549,881 out=96,684,038 elapsed=199.8s

  [14634/15692] intraday_8942.csv.gz  in=410,552,540 out=96,684,472 elapsed=199.8s

  [14635/15692] intraday_8941.csv.gz  in=410,563,111 out=96,695,043 elapsed=199.9s

  [14636/15692] intraday_8943.csv.gz  in=410,565,408 out=96,695,429 elapsed=199.9s

  [14637/15692] intraday_8944.csv.gz  in=410,566,281 out=96,696,302 elapsed=199.9s

  [14638/15692] intraday_8945.csv.gz  in=410,566,569 out=96,696,302 elapsed=199.9s

  [14639/15692] intraday_8946.csv.gz  in=410,566,740 out=96,696,473 elapsed=199.9s

  [14640/15692] intraday_8948.csv.gz  in=410,566,817 out=96,696,550 elapsed=199.9s

  [14641/15692] intraday_8950.csv.gz  in=410,567,257 out=96,696,990 elapsed=199.9s

  [14642/15692] intraday_8947.csv.gz  in=410,573,768 out=96,698,699 elapsed=199.9s

  [14643/15692] intraday_8949.csv.gz  in=410,573,837 out=96,698,768 elapsed=199.9s

  [14644/15692] intraday_8951.csv.gz  in=410,587,794 out=96,701,906 elapsed=199.9s

  [14645/15692] intraday_8952.csv.gz  in=410,588,134 out=96,702,246 elapsed=199.9s

  [14646/15692] intraday_8953.csv.gz  in=410,588,375 out=96,702,487 elapsed=199.9s

  [14647/15692] intraday_8954.csv.gz  in=410,588,385 out=96,702,497 elapsed=199.9s

  [14648/15692] intraday_8957.csv.gz  in=410,588,404 out=96,702,516 elapsed=200.0s

  [14649/15692] intraday_8955.csv.gz  in=410,589,248 out=96,702,516 elapsed=200.0s

  [14650/15692] intraday_8956.csv.gz  in=410,589,316 out=96,702,584 elapsed=200.0s

  [14651/15692] intraday_8958.csv.gz  in=410,589,354 out=96,702,622 elapsed=200.0s

  [14652/15692] intraday_8960.csv.gz  in=410,592,884 out=96,703,403 elapsed=200.0s

  [14653/15692] intraday_8961.csv.gz  in=410,593,395 out=96,703,914 elapsed=200.0s

  [14654/15692] intraday_8959.csv.gz  in=410,595,420 out=96,705,939 elapsed=200.0s

  [14655/15692] intraday_8964.csv.gz  in=410,595,433 out=96,705,952 elapsed=200.0s

  [14656/15692] intraday_8963.csv.gz  in=410,595,638 out=96,706,157 elapsed=200.0s

  [14657/15692] intraday_8962.csv.gz  in=410,600,403 out=96,707,374 elapsed=200.0s

  [14658/15692] intraday_8965.csv.gz  in=410,604,165 out=96,708,282 elapsed=200.0s

  [14659/15692] intraday_8967.csv.gz  in=410,607,271 out=96,709,004 elapsed=200.0s

  [14660/15692] intraday_8966.csv.gz  in=410,607,576 out=96,709,309 elapsed=200.0s

  [14661/15692] intraday_8968.csv.gz  in=410,607,839 out=96,709,572 elapsed=200.0s

  [14662/15692] intraday_8969.csv.gz  in=410,607,870 out=96,709,603 elapsed=200.0s

  [14663/15692] intraday_8970.csv.gz  in=410,612,653 out=96,710,679 elapsed=200.1s

  [14664/15692] intraday_8972.csv.gz  in=410,614,551 out=96,711,182 elapsed=200.1s

  [14665/15692] intraday_8973.csv.gz  in=410,629,892 out=96,726,523 elapsed=200.1s

  [14666/15692] intraday_8971.csv.gz  in=410,660,960 out=96,731,441 elapsed=200.1s

  [14667/15692] intraday_8974.csv.gz  in=410,672,703 out=96,743,184 elapsed=200.1s

  [14668/15692] intraday_8975.csv.gz  in=410,686,500 out=96,756,981 elapsed=200.1s

  [14669/15692] intraday_8976.csv.gz  in=410,697,182 out=96,767,663 elapsed=200.1s

  [14670/15692] intraday_8977.csv.gz  in=410,710,516 out=96,780,997 elapsed=200.1s

  [14671/15692] intraday_8978.csv.gz  in=410,724,678 out=96,795,159 elapsed=200.2s

  [14672/15692] intraday_8979.csv.gz  in=410,739,809 out=96,810,290 elapsed=200.2s

  [14673/15692] intraday_8980.csv.gz  in=410,752,335 out=96,822,816 elapsed=200.2s

  [14674/15692] intraday_8981.csv.gz  in=410,765,080 out=96,835,561 elapsed=200.2s

  [14675/15692] intraday_8982.csv.gz  in=410,778,912 out=96,849,393 elapsed=200.2s

  [14676/15692] intraday_8983.csv.gz  in=410,793,406 out=96,863,887 elapsed=200.2s

  [14677/15692] intraday_8984.csv.gz  in=410,806,504 out=96,876,985 elapsed=200.2s

  [14678/15692] intraday_8985.csv.gz  in=410,822,218 out=96,892,699 elapsed=200.2s

  [14679/15692] intraday_8987.csv.gz  in=410,832,067 out=96,902,548 elapsed=200.2s

  [14680/15692] intraday_8986.csv.gz  in=410,844,061 out=96,914,542 elapsed=200.2s

  [14681/15692] intraday_8988.csv.gz  in=410,855,751 out=96,926,232 elapsed=200.2s

  [14682/15692] intraday_8989.csv.gz  in=410,869,038 out=96,939,519 elapsed=200.2s

  [14683/15692] intraday_8990.csv.gz  in=410,882,034 out=96,952,515 elapsed=200.3s

  [14684/15692] intraday_8991.csv.gz  in=410,892,651 out=96,963,132 elapsed=200.3s

  [14685/15692] intraday_8992.csv.gz  in=410,904,341 out=96,974,822 elapsed=200.3s

  [14686/15692] intraday_8993.csv.gz  in=410,915,765 out=96,986,246 elapsed=200.3s

  [14687/15692] intraday_8994.csv.gz  in=410,928,719 out=96,999,200 elapsed=200.3s

  [14688/15692] intraday_8995.csv.gz  in=410,942,523 out=97,013,004 elapsed=200.3s

  [14689/15692] intraday_8996.csv.gz  in=410,955,261 out=97,025,742 elapsed=200.3s

  [14690/15692] intraday_8997.csv.gz  in=410,969,455 out=97,039,936 elapsed=200.3s

  [14691/15692] intraday_8999.csv.gz  in=410,981,238 out=97,051,719 elapsed=200.3s

  [14692/15692] intraday_8998.csv.gz  in=410,994,207 out=97,064,688 elapsed=200.3s

  [14693/15692] intraday_9000.csv.gz  in=411,005,861 out=97,076,342 elapsed=200.4s

  [14694/15692] intraday_9002.csv.gz  in=411,018,535 out=97,089,016 elapsed=200.4s

  [14695/15692] intraday_9001.csv.gz  in=411,030,412 out=97,100,893 elapsed=200.4s

  [14696/15692] intraday_9005.csv.gz  in=411,041,341 out=97,111,822 elapsed=200.4s

  [14697/15692] intraday_9004.csv.gz  in=411,054,598 out=97,125,079 elapsed=200.4s

  [14698/15692] intraday_9003.csv.gz  in=411,070,738 out=97,141,219 elapsed=200.4s

  [14699/15692] intraday_9006.csv.gz  in=411,082,282 out=97,152,763 elapsed=200.4s

  [14700/15692] intraday_9007.csv.gz  in=411,094,758 out=97,165,239 elapsed=200.4s

  [14701/15692] intraday_9008.csv.gz  in=411,107,201 out=97,177,682 elapsed=200.4s

  [14702/15692] intraday_9010.csv.gz  in=411,118,332 out=97,188,813 elapsed=200.5s

  [14703/15692] intraday_9009.csv.gz  in=411,130,385 out=97,200,866 elapsed=200.5s

  [14704/15692] intraday_9011.csv.gz  in=411,141,869 out=97,212,350 elapsed=200.5s

  [14705/15692] intraday_9012.csv.gz  in=411,152,725 out=97,223,206 elapsed=200.5s

  [14706/15692] intraday_9015.csv.gz  in=411,164,626 out=97,235,107 elapsed=200.5s

  [14707/15692] intraday_9013.csv.gz  in=411,176,845 out=97,247,326 elapsed=200.5s

  [14708/15692] intraday_9016.csv.gz  in=411,189,592 out=97,260,073 elapsed=200.5s

  [14709/15692] intraday_9017.csv.gz  in=411,203,980 out=97,274,461 elapsed=200.5s

  [14710/15692] intraday_9014.csv.gz  in=411,216,318 out=97,286,799 elapsed=200.5s

  [14711/15692] intraday_9018.csv.gz  in=411,226,716 out=97,297,197 elapsed=200.5s

  [14712/15692] intraday_9019.csv.gz  in=411,238,790 out=97,309,271 elapsed=200.6s

  [14713/15692] intraday_9021.csv.gz  in=411,250,240 out=97,320,721 elapsed=200.6s

  [14714/15692] intraday_9020.csv.gz  in=411,262,759 out=97,333,240 elapsed=200.6s

  [14715/15692] intraday_9022.csv.gz  in=411,274,997 out=97,345,478 elapsed=200.6s

  [14716/15692] intraday_9023.csv.gz  in=411,288,113 out=97,358,594 elapsed=200.6s

  [14717/15692] intraday_9024.csv.gz  in=411,298,136 out=97,368,617 elapsed=200.6s

  [14718/15692] intraday_9026.csv.gz  in=411,309,509 out=97,379,990 elapsed=200.6s

  [14719/15692] intraday_9025.csv.gz  in=411,324,994 out=97,395,475 elapsed=200.6s

  [14720/15692] intraday_9028.csv.gz  in=411,339,299 out=97,409,780 elapsed=200.7s

  [14721/15692] intraday_9027.csv.gz  in=411,352,128 out=97,422,609 elapsed=200.7s

  [14722/15692] intraday_9029.csv.gz  in=411,364,375 out=97,434,856 elapsed=200.7s

  [14723/15692] intraday_9030.csv.gz  in=411,375,194 out=97,445,675 elapsed=200.7s

  [14724/15692] intraday_9031.csv.gz  in=411,385,871 out=97,456,352 elapsed=200.7s

  [14725/15692] intraday_9032.csv.gz  in=411,398,715 out=97,469,196 elapsed=200.7s

  [14726/15692] intraday_9033.csv.gz  in=411,411,790 out=97,482,271 elapsed=200.7s

  [14727/15692] intraday_9034.csv.gz  in=411,422,921 out=97,493,402 elapsed=200.7s

  [14728/15692] intraday_9035.csv.gz  in=411,435,876 out=97,506,357 elapsed=200.7s

  [14729/15692] intraday_9036.csv.gz  in=411,448,683 out=97,519,164 elapsed=200.7s

  [14730/15692] intraday_9037.csv.gz  in=411,458,860 out=97,529,341 elapsed=200.7s

  [14731/15692] intraday_9038.csv.gz  in=411,472,861 out=97,543,342 elapsed=200.7s

  [14732/15692] intraday_9040.csv.gz  in=411,484,559 out=97,555,040 elapsed=200.8s

  [14733/15692] intraday_9041.csv.gz  in=411,497,853 out=97,568,334 elapsed=200.8s

  [14734/15692] intraday_9039.csv.gz  in=411,512,631 out=97,583,112 elapsed=200.8s

  [14735/15692] intraday_9042.csv.gz  in=411,524,191 out=97,594,672 elapsed=200.8s

  [14736/15692] intraday_9043.csv.gz  in=411,533,554 out=97,604,035 elapsed=200.8s

  [14737/15692] intraday_9044.csv.gz  in=411,546,479 out=97,616,960 elapsed=200.8s

  [14738/15692] intraday_9045.csv.gz  in=411,558,991 out=97,629,472 elapsed=200.8s

  [14739/15692] intraday_9046.csv.gz  in=411,571,947 out=97,642,428 elapsed=200.9s

  [14740/15692] intraday_9047.csv.gz  in=411,584,454 out=97,654,935 elapsed=200.9s

  [14741/15692] intraday_9048.csv.gz  in=411,597,538 out=97,668,019 elapsed=200.9s

  [14742/15692] intraday_9049.csv.gz  in=411,608,841 out=97,679,322 elapsed=200.9s

  [14743/15692] intraday_9050.csv.gz  in=411,621,562 out=97,692,043 elapsed=200.9s

  [14744/15692] intraday_9051.csv.gz  in=411,634,423 out=97,704,904 elapsed=200.9s

  [14745/15692] intraday_9052.csv.gz  in=411,644,721 out=97,715,202 elapsed=200.9s

  [14746/15692] intraday_9054.csv.gz  in=411,653,629 out=97,724,110 elapsed=201.0s

  [14747/15692] intraday_9055.csv.gz  in=411,665,193 out=97,735,674 elapsed=201.0s

  [14748/15692] intraday_9053.csv.gz  in=411,677,322 out=97,747,803 elapsed=201.0s

  [14749/15692] intraday_9056.csv.gz  in=411,689,518 out=97,759,999 elapsed=201.0s

  [14750/15692] intraday_9057.csv.gz  in=411,705,641 out=97,776,122 elapsed=201.0s

  [14751/15692] intraday_9058.csv.gz  in=411,720,940 out=97,791,421 elapsed=201.0s

  [14752/15692] intraday_9059.csv.gz  in=411,732,009 out=97,802,490 elapsed=201.0s

  [14753/15692] intraday_9060.csv.gz  in=411,744,541 out=97,815,022 elapsed=201.0s

  [14754/15692] intraday_9061.csv.gz  in=411,758,292 out=97,828,773 elapsed=201.1s

  [14755/15692] intraday_9062.csv.gz  in=411,770,347 out=97,840,828 elapsed=201.1s

  [14756/15692] intraday_9063.csv.gz  in=411,784,798 out=97,855,279 elapsed=201.1s

  [14757/15692] intraday_9065.csv.gz  in=411,796,627 out=97,867,108 elapsed=201.1s

  [14758/15692] intraday_9064.csv.gz  in=411,810,312 out=97,880,793 elapsed=201.1s

  [14759/15692] intraday_9066.csv.gz  in=411,824,977 out=97,895,458 elapsed=201.1s

  [14760/15692] intraday_9068.csv.gz  in=411,837,787 out=97,908,268 elapsed=201.1s

  [14761/15692] intraday_9067.csv.gz  in=411,850,764 out=97,921,245 elapsed=201.1s

  [14762/15692] intraday_9069.csv.gz  in=411,863,828 out=97,934,309 elapsed=201.1s

  [14763/15692] intraday_9070.csv.gz  in=411,875,551 out=97,946,032 elapsed=201.2s

  [14764/15692] intraday_9071.csv.gz  in=411,887,849 out=97,958,330 elapsed=201.2s

  [14765/15692] intraday_9072.csv.gz  in=411,901,581 out=97,972,062 elapsed=201.2s

  [14766/15692] intraday_9073.csv.gz  in=411,913,167 out=97,983,648 elapsed=201.2s

  [14767/15692] intraday_9074.csv.gz  in=411,924,249 out=97,994,730 elapsed=201.2s

  [14768/15692] intraday_9075.csv.gz  in=411,936,742 out=98,007,223 elapsed=201.2s

  [14769/15692] intraday_9078.csv.gz  in=411,948,884 out=98,019,365 elapsed=201.2s

  [14770/15692] intraday_9076.csv.gz  in=411,964,511 out=98,034,992 elapsed=201.2s

  [14771/15692] intraday_9077.csv.gz  in=411,978,334 out=98,048,815 elapsed=201.2s

  [14772/15692] intraday_9079.csv.gz  in=411,990,633 out=98,061,114 elapsed=201.3s

  [14773/15692] intraday_9081.csv.gz  in=412,002,225 out=98,072,706 elapsed=201.3s

  [14774/15692] intraday_9080.csv.gz  in=412,018,320 out=98,088,801 elapsed=201.3s

  [14775/15692] intraday_9082.csv.gz  in=412,031,465 out=98,101,946 elapsed=201.3s

  [14776/15692] intraday_9083.csv.gz  in=412,046,251 out=98,116,732 elapsed=201.3s

  [14777/15692] intraday_9084.csv.gz  in=412,059,519 out=98,130,000 elapsed=201.3s

  [14778/15692] intraday_9085.csv.gz  in=412,069,580 out=98,140,061 elapsed=201.3s

  [14779/15692] intraday_9086.csv.gz  in=412,083,129 out=98,153,610 elapsed=201.3s

  [14780/15692] intraday_9087.csv.gz  in=412,094,955 out=98,165,436 elapsed=201.4s

  [14781/15692] intraday_9089.csv.gz  in=412,113,336 out=98,183,817 elapsed=201.4s

  [14782/15692] intraday_9090.csv.gz  in=412,126,710 out=98,197,191 elapsed=201.4s

  [14783/15692] intraday_9088.csv.gz  in=412,139,124 out=98,209,605 elapsed=201.4s

  [14784/15692] intraday_9091.csv.gz  in=412,159,638 out=98,230,119 elapsed=201.4s

  [14785/15692] intraday_9093.csv.gz  in=412,172,671 out=98,243,152 elapsed=201.5s

  [14786/15692] intraday_9094.csv.gz  in=412,185,060 out=98,255,541 elapsed=201.5s

  [14787/15692] intraday_9092.csv.gz  in=412,201,174 out=98,271,655 elapsed=201.5s

  [14788/15692] intraday_9095.csv.gz  in=412,214,111 out=98,284,592 elapsed=201.5s

  [14789/15692] intraday_9096.csv.gz  in=412,224,643 out=98,295,124 elapsed=201.5s

  [14790/15692] intraday_9097.csv.gz  in=412,238,219 out=98,308,700 elapsed=201.5s

  [14791/15692] intraday_9099.csv.gz  in=412,253,107 out=98,323,588 elapsed=201.5s

  [14792/15692] intraday_9100.csv.gz  in=412,266,161 out=98,336,642 elapsed=201.6s

  [14793/15692] intraday_9098.csv.gz  in=412,276,053 out=98,346,534 elapsed=201.6s

  [14794/15692] intraday_9101.csv.gz  in=412,291,174 out=98,361,655 elapsed=201.6s

  [14795/15692] intraday_9102.csv.gz  in=412,302,313 out=98,372,794 elapsed=201.6s

  [14796/15692] intraday_9103.csv.gz  in=412,314,450 out=98,384,931 elapsed=201.6s

  [14797/15692] intraday_9104.csv.gz  in=412,327,171 out=98,397,652 elapsed=201.6s

  [14798/15692] intraday_9106.csv.gz  in=412,339,491 out=98,409,972 elapsed=201.6s

  [14799/15692] intraday_9107.csv.gz  in=412,353,575 out=98,424,056 elapsed=201.7s

  [14800/15692] intraday_9108.csv.gz  in=412,369,202 out=98,439,683 elapsed=201.7s

  [14801/15692] intraday_9109.csv.gz  in=412,382,067 out=98,452,548 elapsed=201.7s

  [14802/15692] intraday_9105.csv.gz  in=412,393,454 out=98,463,935 elapsed=201.7s

  [14803/15692] intraday_9110.csv.gz  in=412,407,525 out=98,478,006 elapsed=201.7s

  [14804/15692] intraday_9111.csv.gz  in=412,420,179 out=98,490,660 elapsed=201.7s

  [14805/15692] intraday_9112.csv.gz  in=412,433,919 out=98,504,400 elapsed=201.7s

  [14806/15692] intraday_9113.csv.gz  in=412,447,036 out=98,517,517 elapsed=201.7s

  [14807/15692] intraday_9115.csv.gz  in=412,458,601 out=98,529,082 elapsed=201.8s

  [14808/15692] intraday_9114.csv.gz  in=412,469,538 out=98,540,019 elapsed=201.8s

  [14809/15692] intraday_9116.csv.gz  in=412,476,733 out=98,547,214 elapsed=201.8s

  [14810/15692] intraday_9117.csv.gz  in=412,487,937 out=98,558,418 elapsed=201.8s

  [14811/15692] intraday_9118.csv.gz  in=412,493,709 out=98,564,190 elapsed=201.8s

  [14812/15692] intraday_9119.csv.gz  in=412,518,981 out=98,576,243 elapsed=201.8s

  [14813/15692] intraday_9120.csv.gz  in=412,534,899 out=98,592,161 elapsed=201.8s

  [14814/15692] intraday_9121.csv.gz  in=412,547,235 out=98,604,497 elapsed=201.8s

  [14815/15692] intraday_9122.csv.gz  in=412,560,501 out=98,617,763 elapsed=201.9s

  [14816/15692] intraday_9123.csv.gz  in=412,570,412 out=98,627,674 elapsed=201.9s

  [14817/15692] intraday_9124.csv.gz  in=412,582,922 out=98,640,184 elapsed=201.9s

  [14818/15692] intraday_9126.csv.gz  in=412,597,989 out=98,655,251 elapsed=201.9s

  [14819/15692] intraday_9127.csv.gz  in=412,609,971 out=98,667,233 elapsed=201.9s

  [14820/15692] intraday_9125.csv.gz  in=412,625,448 out=98,682,710 elapsed=201.9s

  [14821/15692] intraday_9128.csv.gz  in=412,638,042 out=98,695,304 elapsed=201.9s

  [14822/15692] intraday_9129.csv.gz  in=412,652,751 out=98,710,013 elapsed=202.0s

  [14823/15692] intraday_9131.csv.gz  in=412,665,245 out=98,722,507 elapsed=202.0s

  [14824/15692] intraday_9132.csv.gz  in=412,679,270 out=98,736,532 elapsed=202.0s

  [14825/15692] intraday_9130.csv.gz  in=412,694,224 out=98,751,486 elapsed=202.0s

  [14826/15692] intraday_9134.csv.gz  in=412,703,455 out=98,760,717 elapsed=202.0s

  [14827/15692] intraday_9133.csv.gz  in=412,717,853 out=98,775,115 elapsed=202.0s

  [14828/15692] intraday_9135.csv.gz  in=412,729,708 out=98,786,970 elapsed=202.0s

  [14829/15692] intraday_9136.csv.gz  in=412,744,217 out=98,801,479 elapsed=202.0s

  [14830/15692] intraday_9137.csv.gz  in=412,757,324 out=98,814,586 elapsed=202.0s

  [14831/15692] intraday_9138.csv.gz  in=412,769,463 out=98,826,725 elapsed=202.1s

  [14832/15692] intraday_9139.csv.gz  in=412,779,866 out=98,837,128 elapsed=202.1s

  [14833/15692] intraday_9140.csv.gz  in=412,791,254 out=98,848,516 elapsed=202.1s

  [14834/15692] intraday_9142.csv.gz  in=412,803,913 out=98,861,175 elapsed=202.1s

  [14835/15692] intraday_9141.csv.gz  in=412,817,525 out=98,874,787 elapsed=202.1s

  [14836/15692] intraday_9143.csv.gz  in=412,831,329 out=98,888,591 elapsed=202.1s

  [14837/15692] intraday_9144.csv.gz  in=412,846,987 out=98,903,359 elapsed=202.1s

  [14838/15692] intraday_9145.csv.gz  in=412,859,658 out=98,916,030 elapsed=202.1s

  [14839/15692] intraday_9147.csv.gz  in=412,871,565 out=98,927,937 elapsed=202.1s

  [14840/15692] intraday_9148.csv.gz  in=412,882,644 out=98,939,016 elapsed=202.2s

  [14841/15692] intraday_9149.csv.gz  in=412,895,893 out=98,952,265 elapsed=202.2s

  [14842/15692] intraday_9146.csv.gz  in=412,908,659 out=98,965,031 elapsed=202.2s

  [14843/15692] intraday_9150.csv.gz  in=412,925,247 out=98,981,619 elapsed=202.2s

  [14844/15692] intraday_9151.csv.gz  in=412,940,326 out=98,996,698 elapsed=202.2s

  [14845/15692] intraday_9153.csv.gz  in=412,952,370 out=99,008,742 elapsed=202.2s

  [14846/15692] intraday_9154.csv.gz  in=412,964,939 out=99,021,311 elapsed=202.2s

  [14847/15692] intraday_9155.csv.gz  in=412,979,465 out=99,035,837 elapsed=202.2s

  [14848/15692] intraday_9152.csv.gz  in=412,989,137 out=99,045,509 elapsed=202.2s

  [14849/15692] intraday_9156.csv.gz  in=413,000,326 out=99,056,698 elapsed=202.2s

  [14850/15692] intraday_9157.csv.gz  in=413,012,405 out=99,068,777 elapsed=202.3s

  [14851/15692] intraday_9159.csv.gz  in=413,022,973 out=99,079,345 elapsed=202.3s

  [14852/15692] intraday_9158.csv.gz  in=413,039,524 out=99,092,075 elapsed=202.3s

  [14853/15692] intraday_9160.csv.gz  in=413,052,854 out=99,103,976 elapsed=202.3s

  [14854/15692] intraday_9161.csv.gz  in=413,066,366 out=99,117,488 elapsed=202.3s

  [14855/15692] intraday_9162.csv.gz  in=413,077,900 out=99,129,022 elapsed=202.3s

  [14856/15692] intraday_9163.csv.gz  in=413,090,693 out=99,141,815 elapsed=202.3s

  [14857/15692] intraday_9165.csv.gz  in=413,103,274 out=99,154,396 elapsed=202.3s

  [14858/15692] intraday_9164.csv.gz  in=413,117,335 out=99,168,359 elapsed=202.3s

  [14859/15692] intraday_9166.csv.gz  in=413,130,073 out=99,181,097 elapsed=202.4s

  [14860/15692] intraday_9168.csv.gz  in=413,142,607 out=99,193,631 elapsed=202.4s

  [14861/15692] intraday_9167.csv.gz  in=413,153,708 out=99,204,732 elapsed=202.4s

  [14862/15692] intraday_9169.csv.gz  in=413,166,323 out=99,215,880 elapsed=202.4s

  [14863/15692] intraday_9171.csv.gz  in=413,177,348 out=99,226,905 elapsed=202.4s

  [14864/15692] intraday_9170.csv.gz  in=413,189,294 out=99,238,851 elapsed=202.4s

  [14865/15692] intraday_9173.csv.gz  in=413,204,070 out=99,253,627 elapsed=202.4s

  [14866/15692] intraday_9172.csv.gz  in=413,217,119 out=99,266,676 elapsed=202.4s

  [14867/15692] intraday_9174.csv.gz  in=413,230,811 out=99,280,368 elapsed=202.4s

  [14868/15692] intraday_9175.csv.gz  in=413,244,030 out=99,293,587 elapsed=202.5s

  [14869/15692] intraday_9178.csv.gz  in=413,253,542 out=99,303,099 elapsed=202.5s

  [14870/15692] intraday_9176.csv.gz  in=413,266,225 out=99,315,782 elapsed=202.5s

  [14871/15692] intraday_9177.csv.gz  in=413,278,088 out=99,327,645 elapsed=202.5s

  [14872/15692] intraday_9179.csv.gz  in=413,291,471 out=99,341,028 elapsed=202.5s

  [14873/15692] intraday_9180.csv.gz  in=413,305,174 out=99,354,731 elapsed=202.5s

  [14874/15692] intraday_9181.csv.gz  in=413,317,504 out=99,366,420 elapsed=202.5s

  [14875/15692] intraday_9182.csv.gz  in=413,331,157 out=99,380,073 elapsed=202.5s

  [14876/15692] intraday_9183.csv.gz  in=413,342,874 out=99,391,790 elapsed=202.6s

  [14877/15692] intraday_9184.csv.gz  in=413,353,285 out=99,402,201 elapsed=202.6s

  [14878/15692] intraday_9185.csv.gz  in=413,366,760 out=99,415,676 elapsed=202.6s

  [14879/15692] intraday_9186.csv.gz  in=413,381,698 out=99,430,614 elapsed=202.6s

  [14880/15692] intraday_9188.csv.gz  in=413,395,765 out=99,444,681 elapsed=202.6s

  [14881/15692] intraday_9187.csv.gz  in=413,407,508 out=99,456,424 elapsed=202.6s

  [14882/15692] intraday_9190.csv.gz  in=413,418,439 out=99,467,355 elapsed=202.6s

  [14883/15692] intraday_9189.csv.gz  in=413,430,722 out=99,479,638 elapsed=202.6s

  [14884/15692] intraday_9192.csv.gz  in=413,444,346 out=99,493,262 elapsed=202.7s

  [14885/15692] intraday_9191.csv.gz  in=413,456,119 out=99,505,035 elapsed=202.7s

  [14886/15692] intraday_9193.csv.gz  in=413,467,553 out=99,516,469 elapsed=202.7s

  [14887/15692] intraday_9194.csv.gz  in=413,481,143 out=99,530,059 elapsed=202.7s

  [14888/15692] intraday_9196.csv.gz  in=413,493,520 out=99,542,436 elapsed=202.7s

  [14889/15692] intraday_9195.csv.gz  in=413,505,272 out=99,554,188 elapsed=202.7s

  [14890/15692] intraday_9197.csv.gz  in=413,516,541 out=99,565,457 elapsed=202.8s

  [14891/15692] intraday_9200.csv.gz  in=413,528,666 out=99,577,582 elapsed=202.8s

  [14892/15692] intraday_9199.csv.gz  in=413,539,662 out=99,588,578 elapsed=202.8s

  [14893/15692] intraday_9198.csv.gz  in=413,553,707 out=99,602,623 elapsed=202.8s

  [14894/15692] intraday_9201.csv.gz  in=413,564,966 out=99,613,882 elapsed=202.8s

  [14895/15692] intraday_9203.csv.gz  in=413,576,469 out=99,625,385 elapsed=202.8s

  [14896/15692] intraday_9202.csv.gz  in=413,587,409 out=99,636,325 elapsed=202.8s

  [14897/15692] intraday_9205.csv.gz  in=413,603,696 out=99,652,612 elapsed=202.9s

  [14898/15692] intraday_9207.csv.gz  in=413,614,325 out=99,663,241 elapsed=202.9s

  [14899/15692] intraday_9206.csv.gz  in=413,629,817 out=99,676,968 elapsed=202.9s

  [14900/15692] intraday_9204.csv.gz  in=413,646,659 out=99,693,810 elapsed=202.9s

  [14901/15692] intraday_9208.csv.gz  in=413,658,515 out=99,705,666 elapsed=202.9s

  [14902/15692] intraday_9209.csv.gz  in=413,672,973 out=99,720,124 elapsed=202.9s

  [14903/15692] intraday_9210.csv.gz  in=413,691,269 out=99,733,895 elapsed=202.9s

  [14904/15692] intraday_9212.csv.gz  in=413,703,396 out=99,746,022 elapsed=202.9s

  [14905/15692] intraday_9211.csv.gz  in=413,719,332 out=99,761,958 elapsed=202.9s

  [14906/15692] intraday_9213.csv.gz  in=413,733,027 out=99,775,653 elapsed=203.0s

  [14907/15692] intraday_9214.csv.gz  in=413,745,323 out=99,787,949 elapsed=203.0s

  [14908/15692] intraday_9215.csv.gz  in=413,760,035 out=99,802,661 elapsed=203.0s

  [14909/15692] intraday_9217.csv.gz  in=413,771,258 out=99,813,884 elapsed=203.0s

  [14910/15692] intraday_9216.csv.gz  in=413,785,034 out=99,827,660 elapsed=203.0s

  [14911/15692] intraday_9219.csv.gz  in=413,796,602 out=99,839,228 elapsed=203.0s

  [14912/15692] intraday_9218.csv.gz  in=413,809,455 out=99,852,081 elapsed=203.1s

  [14913/15692] intraday_9221.csv.gz  in=413,822,232 out=99,864,858 elapsed=203.1s

  [14914/15692] intraday_9220.csv.gz  in=413,834,981 out=99,877,607 elapsed=203.1s

  [14915/15692] intraday_9223.csv.gz  in=413,849,937 out=99,892,563 elapsed=203.2s

  [14916/15692] intraday_9225.csv.gz  in=413,862,553 out=99,905,179 elapsed=203.2s

  [14917/15692] intraday_9224.csv.gz  in=413,878,280 out=99,920,906 elapsed=203.2s

  [14918/15692] intraday_9222.csv.gz  in=413,889,950 out=99,932,576 elapsed=203.2s

  [14919/15692] intraday_9226.csv.gz  in=413,902,786 out=99,945,412 elapsed=203.2s

  [14920/15692] intraday_9227.csv.gz  in=413,915,983 out=99,958,609 elapsed=203.2s

  [14921/15692] intraday_9229.csv.gz  in=413,929,073 out=99,971,699 elapsed=203.2s

  [14922/15692] intraday_9230.csv.gz  in=413,943,055 out=99,985,681 elapsed=203.2s

  [14923/15692] intraday_9228.csv.gz  in=413,956,613 out=99,999,239 elapsed=203.2s

  [14924/15692] intraday_9231.csv.gz  in=413,971,854 out=100,014,480 elapsed=203.3s

  [14925/15692] intraday_9232.csv.gz  in=413,983,650 out=100,026,276 elapsed=203.3s

  [14926/15692] intraday_9234.csv.gz  in=413,998,335 out=100,040,961 elapsed=203.3s

  [14927/15692] intraday_9233.csv.gz  in=414,009,365 out=100,051,991 elapsed=203.3s

  [14928/15692] intraday_9235.csv.gz  in=414,020,437 out=100,063,063 elapsed=203.3s

  [14929/15692] intraday_9236.csv.gz  in=414,036,736 out=100,079,362 elapsed=203.3s

  [14930/15692] intraday_9237.csv.gz  in=414,052,086 out=100,094,712 elapsed=203.3s

  [14931/15692] intraday_9239.csv.gz  in=414,064,976 out=100,107,602 elapsed=203.4s

  [14932/15692] intraday_9240.csv.gz  in=414,081,957 out=100,124,583 elapsed=203.4s

  [14933/15692] intraday_9238.csv.gz  in=414,102,460 out=100,145,086 elapsed=203.4s

  [14934/15692] intraday_9241.csv.gz  in=414,119,004 out=100,157,883 elapsed=203.4s

  [14935/15692] intraday_9242.csv.gz  in=414,133,278 out=100,172,157 elapsed=203.4s

  [14936/15692] intraday_9243.csv.gz  in=414,144,551 out=100,183,430 elapsed=203.4s

  [14937/15692] intraday_9244.csv.gz  in=414,157,783 out=100,196,662 elapsed=203.4s

  [14938/15692] intraday_9245.csv.gz  in=414,169,835 out=100,207,908 elapsed=203.4s

  [14939/15692] intraday_9246.csv.gz  in=414,182,889 out=100,220,834 elapsed=203.5s

  [14940/15692] intraday_9247.csv.gz  in=414,196,907 out=100,234,852 elapsed=203.5s

  [14941/15692] intraday_9248.csv.gz  in=414,213,754 out=100,251,699 elapsed=203.5s

  [14942/15692] intraday_9249.csv.gz  in=414,225,101 out=100,263,046 elapsed=203.5s

  [14943/15692] intraday_9250.csv.gz  in=414,237,083 out=100,275,028 elapsed=203.5s

  [14944/15692] intraday_9252.csv.gz  in=414,249,529 out=100,287,474 elapsed=203.6s

  [14945/15692] intraday_9253.csv.gz  in=414,261,651 out=100,299,596 elapsed=203.6s

  [14946/15692] intraday_9254.csv.gz  in=414,274,547 out=100,312,492 elapsed=203.6s

  [14947/15692] intraday_9251.csv.gz  in=414,286,297 out=100,324,242 elapsed=203.6s

  [14948/15692] intraday_9255.csv.gz  in=414,301,497 out=100,339,442 elapsed=203.6s

  [14949/15692] intraday_9256.csv.gz  in=414,314,931 out=100,352,876 elapsed=203.6s

  [14950/15692] intraday_9257.csv.gz  in=414,331,275 out=100,369,220 elapsed=203.6s

  [14951/15692] intraday_9258.csv.gz  in=414,344,704 out=100,382,649 elapsed=203.6s

  [14952/15692] intraday_9259.csv.gz  in=414,355,655 out=100,393,600 elapsed=203.6s

  [14953/15692] intraday_9261.csv.gz  in=414,366,441 out=100,404,386 elapsed=203.7s

  [14954/15692] intraday_9262.csv.gz  in=414,380,464 out=100,418,409 elapsed=203.7s

  [14955/15692] intraday_9260.csv.gz  in=414,394,647 out=100,432,592 elapsed=203.7s

  [14956/15692] intraday_9264.csv.gz  in=414,403,060 out=100,441,005 elapsed=203.7s

  [14957/15692] intraday_9263.csv.gz  in=414,411,201 out=100,449,146 elapsed=203.7s

  [14958/15692] intraday_9266.csv.gz  in=414,412,483 out=100,450,428 elapsed=203.7s

  [14959/15692] intraday_9265.csv.gz  in=414,425,099 out=100,463,044 elapsed=203.7s

  [14960/15692] intraday_9269.csv.gz  in=414,438,012 out=100,475,957 elapsed=203.8s

  [14961/15692] intraday_9268.csv.gz  in=414,453,956 out=100,491,901 elapsed=203.8s

  [14962/15692] intraday_9270.csv.gz  in=414,466,561 out=100,504,506 elapsed=203.8s

  [14963/15692] intraday_9271.csv.gz  in=414,477,246 out=100,515,191 elapsed=203.8s

  [14964/15692] intraday_9273.csv.gz  in=414,492,029 out=100,529,974 elapsed=203.8s

  [14965/15692] intraday_9272.csv.gz  in=414,504,988 out=100,542,933 elapsed=203.8s

  [14966/15692] intraday_9267.csv.gz  in=414,564,263 out=100,559,621 elapsed=203.8s

  [14967/15692] intraday_9274.csv.gz  in=414,579,005 out=100,574,363 elapsed=203.8s

  [14968/15692] intraday_9275.csv.gz  in=414,592,060 out=100,586,787 elapsed=203.9s

  [14969/15692] intraday_9276.csv.gz  in=414,604,319 out=100,599,046 elapsed=203.9s

  [14970/15692] intraday_9277.csv.gz  in=414,618,855 out=100,613,582 elapsed=203.9s

  [14971/15692] intraday_9278.csv.gz  in=414,633,382 out=100,628,109 elapsed=203.9s

  [14972/15692] intraday_9279.csv.gz  in=414,646,834 out=100,641,561 elapsed=203.9s

  [14973/15692] intraday_9280.csv.gz  in=414,660,419 out=100,655,146 elapsed=203.9s

  [14974/15692] intraday_9282.csv.gz  in=414,670,876 out=100,665,603 elapsed=203.9s

  [14975/15692] intraday_9281.csv.gz  in=414,684,925 out=100,679,652 elapsed=203.9s

  [14976/15692] intraday_9283.csv.gz  in=414,695,463 out=100,690,190 elapsed=204.0s

  [14977/15692] intraday_9284.csv.gz  in=414,709,026 out=100,703,753 elapsed=204.0s

  [14978/15692] intraday_9285.csv.gz  in=414,722,328 out=100,717,055 elapsed=204.0s

  [14979/15692] intraday_9286.csv.gz  in=414,735,210 out=100,729,937 elapsed=204.0s

  [14980/15692] intraday_9287.csv.gz  in=414,746,500 out=100,741,227 elapsed=204.0s

  [14981/15692] intraday_9288.csv.gz  in=414,757,939 out=100,752,666 elapsed=204.0s

  [14982/15692] intraday_9289.csv.gz  in=414,771,669 out=100,766,396 elapsed=204.0s

  [14983/15692] intraday_9290.csv.gz  in=414,784,476 out=100,779,203 elapsed=204.0s

  [14984/15692] intraday_9292.csv.gz  in=414,798,447 out=100,793,174 elapsed=204.0s

  [14985/15692] intraday_9291.csv.gz  in=414,812,683 out=100,807,410 elapsed=204.0s

  [14986/15692] intraday_9293.csv.gz  in=414,825,339 out=100,820,066 elapsed=204.1s

  [14987/15692] intraday_9294.csv.gz  in=414,838,128 out=100,832,855 elapsed=204.1s

  [14988/15692] intraday_9296.csv.gz  in=414,849,491 out=100,844,218 elapsed=204.1s

  [14989/15692] intraday_9295.csv.gz  in=414,861,519 out=100,856,246 elapsed=204.1s

  [14990/15692] intraday_9297.csv.gz  in=414,874,993 out=100,869,720 elapsed=204.1s

  [14991/15692] intraday_9298.csv.gz  in=414,890,505 out=100,885,232 elapsed=204.1s

  [14992/15692] intraday_9299.csv.gz  in=414,904,093 out=100,898,820 elapsed=204.1s

  [14993/15692] intraday_9300.csv.gz  in=414,915,284 out=100,910,011 elapsed=204.1s

  [14994/15692] intraday_9302.csv.gz  in=414,928,329 out=100,923,056 elapsed=204.2s

  [14995/15692] intraday_9301.csv.gz  in=414,940,570 out=100,935,297 elapsed=204.2s

  [14996/15692] intraday_9303.csv.gz  in=414,952,401 out=100,947,128 elapsed=204.2s

  [14997/15692] intraday_9304.csv.gz  in=414,964,441 out=100,959,168 elapsed=204.2s

  [14998/15692] intraday_9305.csv.gz  in=414,976,154 out=100,970,881 elapsed=204.2s

  [14999/15692] intraday_9306.csv.gz  in=414,988,401 out=100,983,128 elapsed=204.2s

  [15000/15692] intraday_9307.csv.gz  in=414,999,435 out=100,994,162 elapsed=204.2s

  [15001/15692] intraday_9308.csv.gz  in=415,011,540 out=101,006,267 elapsed=204.2s

  [15002/15692] intraday_9309.csv.gz  in=415,024,384 out=101,019,111 elapsed=204.2s

  [15003/15692] intraday_9311.csv.gz  in=415,038,007 out=101,032,734 elapsed=204.3s

  [15004/15692] intraday_9310.csv.gz  in=415,051,494 out=101,046,221 elapsed=204.3s

  [15005/15692] intraday_9313.csv.gz  in=415,062,739 out=101,057,466 elapsed=204.3s

  [15006/15692] intraday_9312.csv.gz  in=415,076,409 out=101,071,136 elapsed=204.3s

  [15007/15692] intraday_9314.csv.gz  in=415,088,683 out=101,083,410 elapsed=204.3s

  [15008/15692] intraday_9315.csv.gz  in=415,102,005 out=101,096,732 elapsed=204.3s

  [15009/15692] intraday_9317.csv.gz  in=415,114,578 out=101,109,305 elapsed=204.3s

  [15010/15692] intraday_9316.csv.gz  in=415,126,044 out=101,120,771 elapsed=204.4s

  [15011/15692] intraday_9319.csv.gz  in=415,136,789 out=101,131,516 elapsed=204.4s

  [15012/15692] intraday_9318.csv.gz  in=415,148,366 out=101,143,093 elapsed=204.4s

  [15013/15692] intraday_9321.csv.gz  in=415,159,919 out=101,154,646 elapsed=204.4s

  [15014/15692] intraday_9320.csv.gz  in=415,177,232 out=101,171,959 elapsed=204.4s

  [15015/15692] intraday_9322.csv.gz  in=415,190,155 out=101,184,882 elapsed=204.4s

  [15016/15692] intraday_9323.csv.gz  in=415,203,069 out=101,197,796 elapsed=204.4s

  [15017/15692] intraday_9324.csv.gz  in=415,215,986 out=101,210,713 elapsed=204.4s

  [15018/15692] intraday_9325.csv.gz  in=415,227,485 out=101,222,212 elapsed=204.4s

  [15019/15692] intraday_9326.csv.gz  in=415,238,861 out=101,233,588 elapsed=204.5s

  [15020/15692] intraday_9327.csv.gz  in=415,252,382 out=101,247,109 elapsed=204.5s

  [15021/15692] intraday_9328.csv.gz  in=415,265,445 out=101,260,172 elapsed=204.5s

  [15022/15692] intraday_9329.csv.gz  in=415,277,070 out=101,271,797 elapsed=204.5s

  [15023/15692] intraday_9330.csv.gz  in=415,290,544 out=101,285,271 elapsed=204.5s

  [15024/15692] intraday_9331.csv.gz  in=415,302,775 out=101,297,502 elapsed=204.5s

  [15025/15692] intraday_9332.csv.gz  in=415,313,388 out=101,308,115 elapsed=204.5s

  [15026/15692] intraday_9333.csv.gz  in=415,328,511 out=101,323,238 elapsed=204.5s

  [15027/15692] intraday_9334.csv.gz  in=415,341,505 out=101,336,232 elapsed=204.6s

  [15028/15692] intraday_9335.csv.gz  in=415,355,084 out=101,349,811 elapsed=204.6s

  [15029/15692] intraday_9336.csv.gz  in=415,367,732 out=101,362,459 elapsed=204.6s

  [15030/15692] intraday_9337.csv.gz  in=415,379,995 out=101,374,722 elapsed=204.6s

  [15031/15692] intraday_9338.csv.gz  in=415,390,230 out=101,384,957 elapsed=204.6s

  [15032/15692] intraday_9339.csv.gz  in=415,401,598 out=101,396,325 elapsed=204.6s

  [15033/15692] intraday_9340.csv.gz  in=415,414,660 out=101,409,387 elapsed=204.6s

  [15034/15692] intraday_9342.csv.gz  in=415,426,781 out=101,421,508 elapsed=204.6s

  [15035/15692] intraday_9341.csv.gz  in=415,440,337 out=101,435,064 elapsed=204.7s

  [15036/15692] intraday_9343.csv.gz  in=415,453,115 out=101,447,842 elapsed=204.7s

  [15037/15692] intraday_9344.csv.gz  in=415,464,007 out=101,458,734 elapsed=204.7s

  [15038/15692] intraday_9346.csv.gz  in=415,476,112 out=101,470,839 elapsed=204.7s

  [15039/15692] intraday_9345.csv.gz  in=415,489,611 out=101,484,338 elapsed=204.7s

  [15040/15692] intraday_9348.csv.gz  in=415,501,935 out=101,496,662 elapsed=204.7s

  [15041/15692] intraday_9347.csv.gz  in=415,513,180 out=101,507,907 elapsed=204.7s

  [15042/15692] intraday_9350.csv.gz  in=415,525,808 out=101,520,535 elapsed=204.7s

  [15043/15692] intraday_9349.csv.gz  in=415,535,041 out=101,529,768 elapsed=204.7s

  [15044/15692] intraday_9351.csv.gz  in=415,548,336 out=101,543,063 elapsed=204.8s

  [15045/15692] intraday_9352.csv.gz  in=415,563,509 out=101,558,236 elapsed=204.8s

  [15046/15692] intraday_9353.csv.gz  in=415,578,162 out=101,572,889 elapsed=204.8s

  [15047/15692] intraday_9355.csv.gz  in=415,590,233 out=101,584,960 elapsed=204.8s

  [15048/15692] intraday_9356.csv.gz  in=415,604,740 out=101,599,467 elapsed=204.8s

  [15049/15692] intraday_9357.csv.gz  in=415,615,641 out=101,610,368 elapsed=204.8s

  [15050/15692] intraday_9354.csv.gz  in=415,628,377 out=101,623,104 elapsed=204.9s

  [15051/15692] intraday_9358.csv.gz  in=415,645,133 out=101,639,860 elapsed=204.9s

  [15052/15692] intraday_9359.csv.gz  in=415,657,480 out=101,652,207 elapsed=204.9s

  [15053/15692] intraday_9360.csv.gz  in=415,670,680 out=101,665,407 elapsed=204.9s

  [15054/15692] intraday_9362.csv.gz  in=415,683,439 out=101,678,166 elapsed=204.9s

  [15055/15692] intraday_9361.csv.gz  in=415,697,110 out=101,691,837 elapsed=204.9s

  [15056/15692] intraday_9363.csv.gz  in=415,710,354 out=101,705,081 elapsed=205.0s

  [15057/15692] intraday_9365.csv.gz  in=415,722,871 out=101,717,598 elapsed=205.0s

  [15058/15692] intraday_9364.csv.gz  in=415,735,643 out=101,730,370 elapsed=205.0s

  [15059/15692] intraday_9366.csv.gz  in=415,748,329 out=101,743,056 elapsed=205.0s

  [15060/15692] intraday_9367.csv.gz  in=415,760,829 out=101,755,556 elapsed=205.0s

  [15061/15692] intraday_9368.csv.gz  in=415,773,893 out=101,768,620 elapsed=205.0s

  [15062/15692] intraday_9370.csv.gz  in=415,786,387 out=101,781,114 elapsed=205.0s

  [15063/15692] intraday_9369.csv.gz  in=415,797,422 out=101,792,149 elapsed=205.0s

  [15064/15692] intraday_9371.csv.gz  in=415,814,452 out=101,809,179 elapsed=205.0s

  [15065/15692] intraday_9374.csv.gz  in=415,826,525 out=101,821,252 elapsed=205.1s

  [15066/15692] intraday_9372.csv.gz  in=415,839,539 out=101,834,266 elapsed=205.1s

  [15067/15692] intraday_9373.csv.gz  in=415,852,897 out=101,847,624 elapsed=205.1s

  [15068/15692] intraday_9375.csv.gz  in=415,867,410 out=101,862,137 elapsed=205.1s

  [15069/15692] intraday_9376.csv.gz  in=415,879,878 out=101,874,605 elapsed=205.1s

  [15070/15692] intraday_9377.csv.gz  in=415,892,858 out=101,887,585 elapsed=205.1s

  [15071/15692] intraday_9379.csv.gz  in=415,906,390 out=101,901,117 elapsed=205.2s

  [15072/15692] intraday_9378.csv.gz  in=415,921,280 out=101,916,007 elapsed=205.2s

  [15073/15692] intraday_9380.csv.gz  in=415,931,901 out=101,926,628 elapsed=205.2s

  [15074/15692] intraday_9382.csv.gz  in=415,944,710 out=101,939,437 elapsed=205.2s

  [15075/15692] intraday_9381.csv.gz  in=415,958,207 out=101,952,934 elapsed=205.2s

  [15076/15692] intraday_9383.csv.gz  in=415,971,926 out=101,966,653 elapsed=205.2s

  [15077/15692] intraday_9384.csv.gz  in=415,988,191 out=101,982,918 elapsed=205.2s

  [15078/15692] intraday_9385.csv.gz  in=416,002,887 out=101,997,614 elapsed=205.3s

  [15079/15692] intraday_9386.csv.gz  in=416,020,935 out=102,015,662 elapsed=205.3s

  [15080/15692] intraday_9387.csv.gz  in=416,036,117 out=102,030,844 elapsed=205.3s

  [15081/15692] intraday_9388.csv.gz  in=416,048,257 out=102,042,984 elapsed=205.3s

  [15082/15692] intraday_9389.csv.gz  in=416,060,897 out=102,055,624 elapsed=205.3s

  [15083/15692] intraday_9390.csv.gz  in=416,073,453 out=102,068,180 elapsed=205.3s

  [15084/15692] intraday_9392.csv.gz  in=416,086,899 out=102,081,626 elapsed=205.3s

  [15085/15692] intraday_9391.csv.gz  in=416,097,912 out=102,092,639 elapsed=205.3s

  [15086/15692] intraday_9393.csv.gz  in=416,108,266 out=102,102,993 elapsed=205.3s

  [15087/15692] intraday_9394.csv.gz  in=416,122,875 out=102,117,602 elapsed=205.4s

  [15088/15692] intraday_9395.csv.gz  in=416,136,473 out=102,131,200 elapsed=205.4s

  [15089/15692] intraday_9396.csv.gz  in=416,151,465 out=102,146,192 elapsed=205.4s

  [15090/15692] intraday_9397.csv.gz  in=416,163,035 out=102,157,762 elapsed=205.4s

  [15091/15692] intraday_9398.csv.gz  in=416,173,798 out=102,168,525 elapsed=205.4s

  [15092/15692] intraday_9399.csv.gz  in=416,187,410 out=102,182,137 elapsed=205.4s

  [15093/15692] intraday_9400.csv.gz  in=416,198,873 out=102,193,600 elapsed=205.4s

  [15094/15692] intraday_9401.csv.gz  in=416,211,239 out=102,205,966 elapsed=205.4s

  [15095/15692] intraday_9402.csv.gz  in=416,226,111 out=102,220,838 elapsed=205.4s

  [15096/15692] intraday_9406.csv.gz  in=416,238,713 out=102,233,440 elapsed=205.5s

  [15097/15692] intraday_9404.csv.gz  in=416,252,054 out=102,246,781 elapsed=205.5s

  [15098/15692] intraday_9405.csv.gz  in=416,266,792 out=102,261,519 elapsed=205.5s

  [15099/15692] intraday_9403.csv.gz  in=416,281,740 out=102,276,467 elapsed=205.5s

  [15100/15692] intraday_9408.csv.gz  in=416,294,009 out=102,288,736 elapsed=205.5s

  [15101/15692] intraday_9407.csv.gz  in=416,307,505 out=102,302,232 elapsed=205.6s

  [15102/15692] intraday_9410.csv.gz  in=416,317,238 out=102,311,965 elapsed=205.6s

  [15103/15692] intraday_9409.csv.gz  in=416,330,089 out=102,324,816 elapsed=205.6s

  [15104/15692] intraday_9411.csv.gz  in=416,338,322 out=102,333,049 elapsed=205.6s

  [15105/15692] intraday_9413.csv.gz  in=416,343,376 out=102,338,103 elapsed=205.6s

  [15106/15692] intraday_9412.csv.gz  in=416,353,766 out=102,348,493 elapsed=205.6s

  [15107/15692] intraday_9414.csv.gz  in=416,382,124 out=102,361,854 elapsed=205.7s

  [15108/15692] intraday_9417.csv.gz  in=416,392,872 out=102,372,602 elapsed=205.7s

  [15109/15692] intraday_9416.csv.gz  in=416,405,809 out=102,385,539 elapsed=205.7s

  [15110/15692] intraday_9415.csv.gz  in=416,421,893 out=102,401,623 elapsed=205.7s

  [15111/15692] intraday_9418.csv.gz  in=416,432,665 out=102,412,395 elapsed=205.7s

  [15112/15692] intraday_9419.csv.gz  in=416,444,926 out=102,424,656 elapsed=205.7s

  [15113/15692] intraday_9420.csv.gz  in=416,460,408 out=102,440,138 elapsed=205.7s

  [15114/15692] intraday_9421.csv.gz  in=416,474,434 out=102,454,164 elapsed=205.7s

  [15115/15692] intraday_9422.csv.gz  in=416,486,837 out=102,466,567 elapsed=205.7s

  [15116/15692] intraday_9423.csv.gz  in=416,498,713 out=102,478,443 elapsed=205.7s

  [15117/15692] intraday_9424.csv.gz  in=416,513,340 out=102,493,070 elapsed=205.7s

  [15118/15692] intraday_9426.csv.gz  in=416,525,083 out=102,504,813 elapsed=205.8s

  [15119/15692] intraday_9425.csv.gz  in=416,539,763 out=102,519,493 elapsed=205.8s

  [15120/15692] intraday_9427.csv.gz  in=416,554,197 out=102,533,927 elapsed=205.8s

  [15121/15692] intraday_9429.csv.gz  in=416,565,005 out=102,544,735 elapsed=205.8s

  [15122/15692] intraday_9430.csv.gz  in=416,576,314 out=102,556,044 elapsed=205.8s

  [15123/15692] intraday_9431.csv.gz  in=416,589,520 out=102,569,250 elapsed=205.9s

  [15124/15692] intraday_9428.csv.gz  in=416,603,034 out=102,582,764 elapsed=205.9s

  [15125/15692] intraday_9432.csv.gz  in=416,615,390 out=102,595,120 elapsed=205.9s

  [15126/15692] intraday_9433.csv.gz  in=416,627,793 out=102,607,523 elapsed=205.9s

  [15127/15692] intraday_9434.csv.gz  in=416,639,141 out=102,618,871 elapsed=205.9s

  [15128/15692] intraday_9436.csv.gz  in=416,651,595 out=102,631,325 elapsed=205.9s

  [15129/15692] intraday_9435.csv.gz  in=416,663,240 out=102,642,970 elapsed=205.9s

  [15130/15692] intraday_9438.csv.gz  in=416,675,505 out=102,655,235 elapsed=206.0s

  [15131/15692] intraday_9439.csv.gz  in=416,689,521 out=102,669,251 elapsed=206.0s

  [15132/15692] intraday_9437.csv.gz  in=416,702,293 out=102,682,023 elapsed=206.0s

  [15133/15692] intraday_9440.csv.gz  in=416,714,561 out=102,694,291 elapsed=206.0s

  [15134/15692] intraday_9441.csv.gz  in=416,726,137 out=102,705,867 elapsed=206.0s

  [15135/15692] intraday_9442.csv.gz  in=416,737,772 out=102,717,502 elapsed=206.0s

  [15136/15692] intraday_9443.csv.gz  in=416,749,375 out=102,729,105 elapsed=206.0s

  [15137/15692] intraday_9444.csv.gz  in=416,761,865 out=102,741,595 elapsed=206.0s

  [15138/15692] intraday_9445.csv.gz  in=416,776,858 out=102,756,588 elapsed=206.0s

  [15139/15692] intraday_9447.csv.gz  in=416,787,102 out=102,766,832 elapsed=206.0s

  [15140/15692] intraday_9446.csv.gz  in=416,800,322 out=102,780,052 elapsed=206.1s

  [15141/15692] intraday_9448.csv.gz  in=416,812,145 out=102,791,875 elapsed=206.1s

  [15142/15692] intraday_9449.csv.gz  in=416,824,398 out=102,804,128 elapsed=206.1s

  [15143/15692] intraday_9450.csv.gz  in=416,837,010 out=102,816,740 elapsed=206.1s

  [15144/15692] intraday_9451.csv.gz  in=416,848,864 out=102,828,594 elapsed=206.1s

  [15145/15692] intraday_9452.csv.gz  in=416,861,187 out=102,840,917 elapsed=206.1s

  [15146/15692] intraday_9453.csv.gz  in=416,872,349 out=102,852,079 elapsed=206.1s

  [15147/15692] intraday_9454.csv.gz  in=416,882,959 out=102,862,689 elapsed=206.1s

  [15148/15692] intraday_9455.csv.gz  in=416,894,753 out=102,874,483 elapsed=206.2s

  [15149/15692] intraday_9456.csv.gz  in=416,907,236 out=102,886,966 elapsed=206.2s

  [15150/15692] intraday_9457.csv.gz  in=416,919,550 out=102,899,280 elapsed=206.2s

  [15151/15692] intraday_9458.csv.gz  in=416,932,820 out=102,912,550 elapsed=206.2s

  [15152/15692] intraday_9459.csv.gz  in=416,946,412 out=102,926,142 elapsed=206.2s

  [15153/15692] intraday_9460.csv.gz  in=416,957,921 out=102,937,651 elapsed=206.2s

  [15154/15692] intraday_9461.csv.gz  in=416,970,308 out=102,950,038 elapsed=206.2s

  [15155/15692] intraday_9462.csv.gz  in=416,982,234 out=102,961,964 elapsed=206.2s

  [15156/15692] intraday_9463.csv.gz  in=416,995,766 out=102,975,496 elapsed=206.3s

  [15157/15692] intraday_9465.csv.gz  in=417,008,383 out=102,988,113 elapsed=206.3s

  [15158/15692] intraday_9464.csv.gz  in=417,018,629 out=102,998,102 elapsed=206.3s

  [15159/15692] intraday_9466.csv.gz  in=417,029,576 out=103,009,049 elapsed=206.3s

  [15160/15692] intraday_9467.csv.gz  in=417,042,474 out=103,021,947 elapsed=206.3s

  [15161/15692] intraday_9468.csv.gz  in=417,054,835 out=103,034,308 elapsed=206.3s

  [15162/15692] intraday_9469.csv.gz  in=417,068,080 out=103,047,553 elapsed=206.3s

  [15163/15692] intraday_9471.csv.gz  in=417,079,638 out=103,059,111 elapsed=206.3s

  [15164/15692] intraday_9470.csv.gz  in=417,093,885 out=103,073,358 elapsed=206.4s

  [15165/15692] intraday_9472.csv.gz  in=417,105,365 out=103,084,838 elapsed=206.4s

  [15166/15692] intraday_9473.csv.gz  in=417,115,614 out=103,095,087 elapsed=206.4s

  [15167/15692] intraday_9474.csv.gz  in=417,128,628 out=103,108,101 elapsed=206.4s

  [15168/15692] intraday_9475.csv.gz  in=417,141,003 out=103,120,476 elapsed=206.4s

  [15169/15692] intraday_9477.csv.gz  in=417,154,327 out=103,133,800 elapsed=206.4s

  [15170/15692] intraday_9476.csv.gz  in=417,166,185 out=103,145,658 elapsed=206.4s

  [15171/15692] intraday_9478.csv.gz  in=417,179,208 out=103,158,681 elapsed=206.4s

  [15172/15692] intraday_9479.csv.gz  in=417,189,755 out=103,169,228 elapsed=206.4s

  [15173/15692] intraday_9480.csv.gz  in=417,203,837 out=103,183,310 elapsed=206.5s

  [15174/15692] intraday_9482.csv.gz  in=417,214,336 out=103,193,809 elapsed=206.5s

  [15175/15692] intraday_9481.csv.gz  in=417,230,519 out=103,209,992 elapsed=206.5s

  [15176/15692] intraday_9483.csv.gz  in=417,245,027 out=103,224,500 elapsed=206.5s

  [15177/15692] intraday_9484.csv.gz  in=417,256,404 out=103,235,877 elapsed=206.5s

  [15178/15692] intraday_9485.csv.gz  in=417,266,747 out=103,246,220 elapsed=206.5s

  [15179/15692] intraday_9486.csv.gz  in=417,279,229 out=103,258,702 elapsed=206.5s

  [15180/15692] intraday_9488.csv.gz  in=417,292,208 out=103,271,681 elapsed=206.5s

  [15181/15692] intraday_9489.csv.gz  in=417,304,771 out=103,284,244 elapsed=206.6s

  [15182/15692] intraday_9491.csv.gz  in=417,314,401 out=103,293,874 elapsed=206.6s

  [15183/15692] intraday_9487.csv.gz  in=417,327,468 out=103,306,941 elapsed=206.6s

  [15184/15692] intraday_9490.csv.gz  in=417,340,069 out=103,319,542 elapsed=206.6s

  [15185/15692] intraday_9492.csv.gz  in=417,352,021 out=103,331,494 elapsed=206.6s

  [15186/15692] intraday_9493.csv.gz  in=417,365,154 out=103,344,627 elapsed=206.6s

  [15187/15692] intraday_9494.csv.gz  in=417,376,559 out=103,356,032 elapsed=206.7s

  [15188/15692] intraday_9496.csv.gz  in=417,387,458 out=103,366,931 elapsed=206.7s

  [15189/15692] intraday_9495.csv.gz  in=417,399,177 out=103,378,650 elapsed=206.7s

  [15190/15692] intraday_9497.csv.gz  in=417,410,736 out=103,390,209 elapsed=206.7s

  [15191/15692] intraday_9498.csv.gz  in=417,423,141 out=103,402,614 elapsed=206.7s

  [15192/15692] intraday_9499.csv.gz  in=417,438,920 out=103,418,393 elapsed=206.7s

  [15193/15692] intraday_9500.csv.gz  in=417,454,861 out=103,434,334 elapsed=206.7s

  [15194/15692] intraday_9502.csv.gz  in=417,467,371 out=103,446,844 elapsed=206.8s

  [15195/15692] intraday_9501.csv.gz  in=417,478,546 out=103,458,019 elapsed=206.8s

  [15196/15692] intraday_9503.csv.gz  in=417,491,276 out=103,470,749 elapsed=206.8s

  [15197/15692] intraday_9504.csv.gz  in=417,504,446 out=103,483,919 elapsed=206.8s

  [15198/15692] intraday_9506.csv.gz  in=417,516,348 out=103,495,821 elapsed=206.8s

  [15199/15692] intraday_9507.csv.gz  in=417,528,562 out=103,508,035 elapsed=206.8s

  [15200/15692] intraday_9505.csv.gz  in=417,544,180 out=103,523,653 elapsed=206.8s

  [15201/15692] intraday_9508.csv.gz  in=417,557,932 out=103,537,405 elapsed=206.9s

  [15202/15692] intraday_9509.csv.gz  in=417,571,365 out=103,550,838 elapsed=206.9s

  [15203/15692] intraday_9510.csv.gz  in=417,584,366 out=103,563,839 elapsed=206.9s

  [15204/15692] intraday_9511.csv.gz  in=417,596,931 out=103,576,404 elapsed=206.9s

  [15205/15692] intraday_9512.csv.gz  in=417,609,937 out=103,589,410 elapsed=206.9s

  [15206/15692] intraday_9513.csv.gz  in=417,622,865 out=103,602,338 elapsed=206.9s

  [15207/15692] intraday_9515.csv.gz  in=417,633,449 out=103,612,922 elapsed=206.9s

  [15208/15692] intraday_9514.csv.gz  in=417,646,827 out=103,626,300 elapsed=206.9s

  [15209/15692] intraday_9516.csv.gz  in=417,659,320 out=103,638,793 elapsed=206.9s

  [15210/15692] intraday_9517.csv.gz  in=417,673,105 out=103,652,578 elapsed=206.9s

  [15211/15692] intraday_9519.csv.gz  in=417,686,396 out=103,665,869 elapsed=207.0s

  [15212/15692] intraday_9520.csv.gz  in=417,698,565 out=103,678,038 elapsed=207.0s

  [15213/15692] intraday_9518.csv.gz  in=417,712,988 out=103,692,461 elapsed=207.0s

  [15214/15692] intraday_9521.csv.gz  in=417,726,004 out=103,705,477 elapsed=207.0s

  [15215/15692] intraday_9522.csv.gz  in=417,741,248 out=103,720,721 elapsed=207.0s

  [15216/15692] intraday_9523.csv.gz  in=417,753,196 out=103,732,669 elapsed=207.0s

  [15217/15692] intraday_9524.csv.gz  in=417,765,478 out=103,744,951 elapsed=207.0s

  [15218/15692] intraday_9525.csv.gz  in=417,780,597 out=103,760,070 elapsed=207.1s

  [15219/15692] intraday_9527.csv.gz  in=417,789,950 out=103,769,423 elapsed=207.1s

  [15220/15692] intraday_9528.csv.gz  in=417,802,872 out=103,782,345 elapsed=207.1s

  [15221/15692] intraday_9526.csv.gz  in=417,817,868 out=103,797,341 elapsed=207.1s

  [15222/15692] intraday_9529.csv.gz  in=417,831,502 out=103,810,975 elapsed=207.1s

  [15223/15692] intraday_9530.csv.gz  in=417,843,468 out=103,822,941 elapsed=207.1s

  [15224/15692] intraday_9531.csv.gz  in=417,857,199 out=103,836,672 elapsed=207.1s

  [15225/15692] intraday_9532.csv.gz  in=417,872,676 out=103,852,149 elapsed=207.1s

  [15226/15692] intraday_9533.csv.gz  in=417,890,894 out=103,870,367 elapsed=207.2s

  [15227/15692] intraday_9534.csv.gz  in=417,906,413 out=103,885,886 elapsed=207.2s

  [15228/15692] intraday_9536.csv.gz  in=417,918,366 out=103,897,839 elapsed=207.2s

  [15229/15692] intraday_9535.csv.gz  in=417,931,800 out=103,911,273 elapsed=207.2s

  [15230/15692] intraday_9537.csv.gz  in=417,944,683 out=103,924,156 elapsed=207.2s

  [15231/15692] intraday_9538.csv.gz  in=417,954,801 out=103,934,274 elapsed=207.2s

  [15232/15692] intraday_9540.csv.gz  in=417,965,554 out=103,945,027 elapsed=207.2s

  [15233/15692] intraday_9541.csv.gz  in=417,978,819 out=103,958,292 elapsed=207.2s

  [15234/15692] intraday_9539.csv.gz  in=417,992,590 out=103,972,063 elapsed=207.3s

  [15235/15692] intraday_9542.csv.gz  in=418,005,342 out=103,984,815 elapsed=207.3s

  [15236/15692] intraday_9545.csv.gz  in=418,017,569 out=103,997,042 elapsed=207.3s

  [15237/15692] intraday_9543.csv.gz  in=418,033,302 out=104,012,775 elapsed=207.3s

  [15238/15692] intraday_9544.csv.gz  in=418,044,336 out=104,023,809 elapsed=207.3s

  [15239/15692] intraday_9547.csv.gz  in=418,056,752 out=104,036,225 elapsed=207.3s

  [15240/15692] intraday_9546.csv.gz  in=418,068,255 out=104,047,728 elapsed=207.3s

  [15241/15692] intraday_9549.csv.gz  in=418,081,784 out=104,061,257 elapsed=207.4s

  [15242/15692] intraday_9548.csv.gz  in=418,093,042 out=104,072,515 elapsed=207.4s

  [15243/15692] intraday_9550.csv.gz  in=418,108,063 out=104,087,536 elapsed=207.4s

  [15244/15692] intraday_9551.csv.gz  in=418,121,878 out=104,101,351 elapsed=207.4s

  [15245/15692] intraday_9552.csv.gz  in=418,136,818 out=104,116,291 elapsed=207.4s

  [15246/15692] intraday_9554.csv.gz  in=418,148,673 out=104,128,146 elapsed=207.4s

  [15247/15692] intraday_9553.csv.gz  in=418,161,580 out=104,141,053 elapsed=207.5s

  [15248/15692] intraday_9556.csv.gz  in=418,173,411 out=104,152,884 elapsed=207.5s

  [15249/15692] intraday_9555.csv.gz  in=418,186,811 out=104,166,284 elapsed=207.5s

  [15250/15692] intraday_9557.csv.gz  in=418,200,513 out=104,179,986 elapsed=207.5s

  [15251/15692] intraday_9558.csv.gz  in=418,207,896 out=104,187,369 elapsed=207.5s

  [15252/15692] intraday_9560.csv.gz  in=418,218,861 out=104,198,334 elapsed=207.5s

  [15253/15692] intraday_9559.csv.gz  in=418,228,404 out=104,207,877 elapsed=207.5s

  [15254/15692] intraday_9561.csv.gz  in=418,244,881 out=104,224,054 elapsed=207.5s

  [15255/15692] intraday_9562.csv.gz  in=418,256,947 out=104,236,120 elapsed=207.5s

  [15256/15692] intraday_9563.csv.gz  in=418,269,497 out=104,248,670 elapsed=207.5s

  [15257/15692] intraday_9565.csv.gz  in=418,282,073 out=104,261,246 elapsed=207.5s

  [15258/15692] intraday_9564.csv.gz  in=418,292,115 out=104,271,288 elapsed=207.5s

  [15259/15692] intraday_9566.csv.gz  in=418,305,640 out=104,284,813 elapsed=207.6s

  [15260/15692] intraday_9567.csv.gz  in=418,320,372 out=104,299,545 elapsed=207.6s

  [15261/15692] intraday_9569.csv.gz  in=418,332,839 out=104,312,012 elapsed=207.6s

  [15262/15692] intraday_9571.csv.gz  in=418,346,312 out=104,325,485 elapsed=207.6s

  [15263/15692] intraday_9568.csv.gz  in=418,358,723 out=104,337,420 elapsed=207.6s

  [15264/15692] intraday_9570.csv.gz  in=418,373,124 out=104,351,821 elapsed=207.6s

  [15265/15692] intraday_9572.csv.gz  in=418,386,266 out=104,364,963 elapsed=207.6s

  [15266/15692] intraday_9573.csv.gz  in=418,399,769 out=104,378,466 elapsed=207.6s

  [15267/15692] intraday_9576.csv.gz  in=418,410,868 out=104,389,565 elapsed=207.7s

  [15268/15692] intraday_9574.csv.gz  in=418,425,376 out=104,404,073 elapsed=207.7s

  [15269/15692] intraday_9577.csv.gz  in=418,438,716 out=104,417,413 elapsed=207.7s

  [15270/15692] intraday_9575.csv.gz  in=418,449,241 out=104,427,938 elapsed=207.7s

  [15271/15692] intraday_9578.csv.gz  in=418,461,969 out=104,440,666 elapsed=207.7s

  [15272/15692] intraday_9579.csv.gz  in=418,473,925 out=104,452,622 elapsed=207.7s

  [15273/15692] intraday_9580.csv.gz  in=418,484,768 out=104,463,465 elapsed=207.7s

  [15274/15692] intraday_9581.csv.gz  in=418,496,467 out=104,475,164 elapsed=207.7s

  [15275/15692] intraday_9582.csv.gz  in=418,511,279 out=104,489,976 elapsed=207.7s

  [15276/15692] intraday_9583.csv.gz  in=418,524,555 out=104,503,252 elapsed=207.8s

  [15277/15692] intraday_9584.csv.gz  in=418,536,781 out=104,515,478 elapsed=207.8s

  [15278/15692] intraday_9586.csv.gz  in=418,548,916 out=104,527,613 elapsed=207.8s

  [15279/15692] intraday_9585.csv.gz  in=418,561,688 out=104,540,385 elapsed=207.8s

  [15280/15692] intraday_9587.csv.gz  in=418,578,489 out=104,553,760 elapsed=207.8s

  [15281/15692] intraday_9588.csv.gz  in=418,594,694 out=104,569,791 elapsed=207.8s

  [15282/15692] intraday_9590.csv.gz  in=418,606,625 out=104,581,722 elapsed=207.8s

  [15283/15692] intraday_9589.csv.gz  in=418,619,117 out=104,594,214 elapsed=207.8s

  [15284/15692] intraday_9591.csv.gz  in=418,634,510 out=104,609,607 elapsed=207.8s

  [15285/15692] intraday_9592.csv.gz  in=418,647,802 out=104,622,899 elapsed=207.8s

  [15286/15692] intraday_9594.csv.gz  in=418,658,168 out=104,633,265 elapsed=207.9s

  [15287/15692] intraday_9593.csv.gz  in=418,668,423 out=104,643,520 elapsed=207.9s

  [15288/15692] intraday_9595.csv.gz  in=418,682,031 out=104,657,128 elapsed=207.9s

  [15289/15692] intraday_9596.csv.gz  in=418,694,028 out=104,669,125 elapsed=207.9s

  [15290/15692] intraday_9597.csv.gz  in=418,706,101 out=104,681,198 elapsed=207.9s

  [15291/15692] intraday_9598.csv.gz  in=418,721,944 out=104,694,521 elapsed=207.9s

  [15292/15692] intraday_9599.csv.gz  in=418,732,970 out=104,705,547 elapsed=207.9s

  [15293/15692] intraday_9600.csv.gz  in=418,744,459 out=104,715,617 elapsed=207.9s

  [15294/15692] intraday_9601.csv.gz  in=418,756,024 out=104,727,182 elapsed=207.9s

  [15295/15692] intraday_9602.csv.gz  in=418,769,794 out=104,739,980 elapsed=207.9s

  [15296/15692] intraday_9603.csv.gz  in=418,782,149 out=104,752,335 elapsed=208.0s

  [15297/15692] intraday_9604.csv.gz  in=418,795,338 out=104,765,524 elapsed=208.0s

  [15298/15692] intraday_9605.csv.gz  in=418,810,918 out=104,779,909 elapsed=208.0s

  [15299/15692] intraday_9607.csv.gz  in=418,825,503 out=104,792,386 elapsed=208.0s

  [15300/15692] intraday_9609.csv.gz  in=418,837,598 out=104,804,481 elapsed=208.0s

  [15301/15692] intraday_9606.csv.gz  in=418,853,767 out=104,817,212 elapsed=208.0s

  [15302/15692] intraday_9608.csv.gz  in=418,865,148 out=104,828,593 elapsed=208.0s

  [15303/15692] intraday_9610.csv.gz  in=418,875,129 out=104,838,574 elapsed=208.0s

  [15304/15692] intraday_9611.csv.gz  in=418,887,151 out=104,850,596 elapsed=208.1s

  [15305/15692] intraday_9612.csv.gz  in=418,899,581 out=104,863,026 elapsed=208.1s

  [15306/15692] intraday_9614.csv.gz  in=418,912,768 out=104,876,213 elapsed=208.1s

  [15307/15692] intraday_9613.csv.gz  in=418,924,093 out=104,887,538 elapsed=208.1s

  [15308/15692] intraday_9615.csv.gz  in=418,936,243 out=104,899,688 elapsed=208.1s

  [15309/15692] intraday_9616.csv.gz  in=418,947,974 out=104,911,419 elapsed=208.1s

  [15310/15692] intraday_9617.csv.gz  in=418,961,170 out=104,924,615 elapsed=208.1s

  [15311/15692] intraday_9619.csv.gz  in=418,972,393 out=104,935,838 elapsed=208.2s

  [15312/15692] intraday_9618.csv.gz  in=418,983,995 out=104,947,440 elapsed=208.2s

  [15313/15692] intraday_9620.csv.gz  in=418,997,025 out=104,960,470 elapsed=208.2s

  [15314/15692] intraday_9621.csv.gz  in=419,009,800 out=104,973,245 elapsed=208.2s

  [15315/15692] intraday_9624.csv.gz  in=419,021,449 out=104,984,894 elapsed=208.2s

  [15316/15692] intraday_9622.csv.gz  in=419,038,552 out=104,998,446 elapsed=208.2s

  [15317/15692] intraday_9623.csv.gz  in=419,051,126 out=105,011,020 elapsed=208.2s

  [15318/15692] intraday_9626.csv.gz  in=419,062,823 out=105,022,717 elapsed=208.3s

  [15319/15692] intraday_9625.csv.gz  in=419,075,084 out=105,034,978 elapsed=208.3s

  [15320/15692] intraday_9628.csv.gz  in=419,088,558 out=105,048,218 elapsed=208.3s

  [15321/15692] intraday_9627.csv.gz  in=419,103,748 out=105,063,408 elapsed=208.3s

  [15322/15692] intraday_9630.csv.gz  in=419,125,686 out=105,078,553 elapsed=208.3s

  [15323/15692] intraday_9629.csv.gz  in=419,140,206 out=105,093,073 elapsed=208.3s

  [15324/15692] intraday_9631.csv.gz  in=419,151,314 out=105,104,181 elapsed=208.3s

  [15325/15692] intraday_9632.csv.gz  in=419,162,305 out=105,115,172 elapsed=208.3s

  [15326/15692] intraday_9634.csv.gz  in=419,174,937 out=105,127,804 elapsed=208.4s

  [15327/15692] intraday_9633.csv.gz  in=419,187,064 out=105,139,931 elapsed=208.4s

  [15328/15692] intraday_9635.csv.gz  in=419,202,325 out=105,153,591 elapsed=208.4s

  [15329/15692] intraday_9636.csv.gz  in=419,214,846 out=105,166,112 elapsed=208.4s

  [15330/15692] intraday_9637.csv.gz  in=419,226,173 out=105,177,439 elapsed=208.4s

  [15331/15692] intraday_9638.csv.gz  in=419,237,188 out=105,188,454 elapsed=208.4s

  [15332/15692] intraday_9639.csv.gz  in=419,250,087 out=105,201,353 elapsed=208.4s

  [15333/15692] intraday_9641.csv.gz  in=419,262,614 out=105,213,880 elapsed=208.5s

  [15334/15692] intraday_9642.csv.gz  in=419,272,692 out=105,223,958 elapsed=208.5s

  [15335/15692] intraday_9640.csv.gz  in=419,284,580 out=105,235,846 elapsed=208.5s

  [15336/15692] intraday_9643.csv.gz  in=419,295,149 out=105,246,415 elapsed=208.5s

  [15337/15692] intraday_9644.csv.gz  in=419,306,423 out=105,257,689 elapsed=208.5s

  [15338/15692] intraday_9646.csv.gz  in=419,322,645 out=105,273,911 elapsed=208.5s

  [15339/15692] intraday_9645.csv.gz  in=419,340,577 out=105,291,843 elapsed=208.5s

  [15340/15692] intraday_9647.csv.gz  in=419,352,762 out=105,304,028 elapsed=208.5s

  [15341/15692] intraday_9648.csv.gz  in=419,364,111 out=105,315,377 elapsed=208.6s

  [15342/15692] intraday_9649.csv.gz  in=419,376,203 out=105,327,469 elapsed=208.6s

  [15343/15692] intraday_9650.csv.gz  in=419,391,032 out=105,342,298 elapsed=208.6s

  [15344/15692] intraday_9651.csv.gz  in=419,403,234 out=105,354,500 elapsed=208.6s

  [15345/15692] intraday_9652.csv.gz  in=419,419,106 out=105,370,372 elapsed=208.6s

  [15346/15692] intraday_9654.csv.gz  in=419,432,364 out=105,383,630 elapsed=208.6s

  [15347/15692] intraday_9653.csv.gz  in=419,442,909 out=105,394,175 elapsed=208.6s

  [15348/15692] intraday_9655.csv.gz  in=419,456,136 out=105,407,402 elapsed=208.6s

  [15349/15692] intraday_9656.csv.gz  in=419,468,792 out=105,420,058 elapsed=208.7s

  [15350/15692] intraday_9658.csv.gz  in=419,481,385 out=105,432,651 elapsed=208.7s

  [15351/15692] intraday_9657.csv.gz  in=419,494,986 out=105,446,252 elapsed=208.7s

  [15352/15692] intraday_9659.csv.gz  in=419,508,350 out=105,459,616 elapsed=208.7s

  [15353/15692] intraday_9660.csv.gz  in=419,520,246 out=105,471,512 elapsed=208.7s

  [15354/15692] intraday_9661.csv.gz  in=419,532,638 out=105,483,904 elapsed=208.7s

  [15355/15692] intraday_9662.csv.gz  in=419,545,205 out=105,496,471 elapsed=208.8s

  [15356/15692] intraday_9663.csv.gz  in=419,557,018 out=105,508,284 elapsed=208.8s

  [15357/15692] intraday_9666.csv.gz  in=419,572,792 out=105,524,058 elapsed=208.8s

  [15358/15692] intraday_9667.csv.gz  in=419,586,134 out=105,536,970 elapsed=208.8s

  [15359/15692] intraday_9664.csv.gz  in=419,600,913 out=105,551,749 elapsed=208.8s

  [15360/15692] intraday_9665.csv.gz  in=419,615,990 out=105,566,826 elapsed=208.8s

  [15361/15692] intraday_9668.csv.gz  in=419,628,786 out=105,579,622 elapsed=208.8s

  [15362/15692] intraday_9669.csv.gz  in=419,642,307 out=105,593,143 elapsed=208.9s

  [15363/15692] intraday_9670.csv.gz  in=419,653,350 out=105,604,186 elapsed=208.9s

  [15364/15692] intraday_9671.csv.gz  in=419,668,652 out=105,619,488 elapsed=208.9s

  [15365/15692] intraday_9672.csv.gz  in=419,682,978 out=105,633,814 elapsed=208.9s

  [15366/15692] intraday_9674.csv.gz  in=419,694,040 out=105,644,876 elapsed=208.9s

  [15367/15692] intraday_9673.csv.gz  in=419,707,389 out=105,657,580 elapsed=208.9s

  [15368/15692] intraday_9675.csv.gz  in=419,722,302 out=105,672,493 elapsed=208.9s

  [15369/15692] intraday_9676.csv.gz  in=419,734,561 out=105,684,752 elapsed=209.0s

  [15370/15692] intraday_9677.csv.gz  in=419,748,724 out=105,698,915 elapsed=209.0s

  [15371/15692] intraday_9678.csv.gz  in=419,763,086 out=105,713,277 elapsed=209.0s

  [15372/15692] intraday_9680.csv.gz  in=419,775,869 out=105,726,060 elapsed=209.0s

  [15373/15692] intraday_9679.csv.gz  in=419,793,482 out=105,743,673 elapsed=209.0s

  [15374/15692] intraday_9681.csv.gz  in=419,810,355 out=105,760,546 elapsed=209.0s

  [15375/15692] intraday_9683.csv.gz  in=419,823,648 out=105,773,839 elapsed=209.0s

  [15376/15692] intraday_9684.csv.gz  in=419,835,357 out=105,785,548 elapsed=209.1s

  [15377/15692] intraday_9682.csv.gz  in=419,846,833 out=105,797,024 elapsed=209.1s

  [15378/15692] intraday_9685.csv.gz  in=419,859,251 out=105,809,442 elapsed=209.1s

  [15379/15692] intraday_9686.csv.gz  in=419,870,229 out=105,820,420 elapsed=209.1s

  [15380/15692] intraday_9687.csv.gz  in=419,882,964 out=105,833,155 elapsed=209.1s

  [15381/15692] intraday_9688.csv.gz  in=419,896,511 out=105,846,470 elapsed=209.1s

  [15382/15692] intraday_9689.csv.gz  in=419,912,738 out=105,862,697 elapsed=209.1s

  [15383/15692] intraday_9690.csv.gz  in=419,924,094 out=105,874,053 elapsed=209.1s

  [15384/15692] intraday_9691.csv.gz  in=419,936,397 out=105,886,356 elapsed=209.2s

  [15385/15692] intraday_9692.csv.gz  in=419,949,108 out=105,898,559 elapsed=209.2s

  [15386/15692] intraday_9693.csv.gz  in=419,961,905 out=105,911,356 elapsed=209.2s

  [15387/15692] intraday_9694.csv.gz  in=419,973,097 out=105,922,537 elapsed=209.2s

  [15388/15692] intraday_9695.csv.gz  in=419,985,939 out=105,935,379 elapsed=209.2s

  [15389/15692] intraday_9696.csv.gz  in=420,000,283 out=105,949,723 elapsed=209.2s

  [15390/15692] intraday_9697.csv.gz  in=420,014,246 out=105,963,686 elapsed=209.2s

  [15391/15692] intraday_9698.csv.gz  in=420,028,873 out=105,978,313 elapsed=209.2s

  [15392/15692] intraday_9699.csv.gz  in=420,042,286 out=105,991,726 elapsed=209.2s

  [15393/15692] intraday_9700.csv.gz  in=420,054,537 out=106,003,977 elapsed=209.3s

  [15394/15692] intraday_9701.csv.gz  in=420,068,066 out=106,017,506 elapsed=209.3s

  [15395/15692] intraday_9702.csv.gz  in=420,080,010 out=106,029,450 elapsed=209.3s

  [15396/15692] intraday_9703.csv.gz  in=420,093,462 out=106,042,902 elapsed=209.3s

  [15397/15692] intraday_9704.csv.gz  in=420,101,807 out=106,051,247 elapsed=209.3s

  [15398/15692] intraday_9705.csv.gz  in=420,109,295 out=106,058,735 elapsed=209.3s

  [15399/15692] intraday_9706.csv.gz  in=420,121,859 out=106,071,299 elapsed=209.3s

  [15400/15692] intraday_9708.csv.gz  in=420,121,880 out=106,071,320 elapsed=209.3s

  [15401/15692] intraday_9709.csv.gz  in=420,121,898 out=106,071,338 elapsed=209.3s

  [15402/15692] intraday_9707.csv.gz  in=420,123,545 out=106,072,985 elapsed=209.3s

  [15403/15692] intraday_9710.csv.gz  in=420,123,806 out=106,073,246 elapsed=209.3s

  [15404/15692] intraday_9712.csv.gz  in=420,123,911 out=106,073,351 elapsed=209.3s

  [15405/15692] intraday_9711.csv.gz  in=420,128,050 out=106,074,844 elapsed=209.4s

  [15406/15692] intraday_9714.csv.gz  in=420,128,102 out=106,074,896 elapsed=209.4s

  [15407/15692] intraday_9715.csv.gz  in=420,128,540 out=106,075,120 elapsed=209.4s

  [15408/15692] intraday_9713.csv.gz  in=420,130,038 out=106,075,729 elapsed=209.4s

  [15409/15692] intraday_9716.csv.gz  in=420,130,547 out=106,076,238 elapsed=209.4s

  [15410/15692] intraday_9717.csv.gz  in=420,130,663 out=106,076,354 elapsed=209.4s

  [15411/15692] intraday_9718.csv.gz  in=420,132,057 out=106,076,837 elapsed=209.4s

  [15412/15692] intraday_9719.csv.gz  in=420,132,156 out=106,076,936 elapsed=209.4s

  [15413/15692] intraday_9720.csv.gz  in=420,137,283 out=106,079,275 elapsed=209.4s

  [15414/15692] intraday_9721.csv.gz  in=420,139,265 out=106,081,257 elapsed=209.4s

  [15415/15692] intraday_9723.csv.gz  in=420,139,278 out=106,081,270 elapsed=209.4s

  [15416/15692] intraday_9722.csv.gz  in=420,139,504 out=106,081,496 elapsed=209.4s

  [15417/15692] intraday_9725.csv.gz  in=420,139,548 out=106,081,540 elapsed=209.4s

  [15418/15692] intraday_9726.csv.gz  in=420,141,088 out=106,083,080 elapsed=209.4s

  [15419/15692] intraday_9724.csv.gz  in=420,151,488 out=106,084,984 elapsed=209.5s

  [15420/15692] intraday_9727.csv.gz  in=420,152,692 out=106,085,739 elapsed=209.5s

  [15421/15692] intraday_9728.csv.gz  in=420,153,522 out=106,086,067 elapsed=209.5s

  [15422/15692] intraday_9730.csv.gz  in=420,153,568 out=106,086,113 elapsed=209.5s

  [15423/15692] intraday_9732.csv.gz  in=420,153,672 out=106,086,217 elapsed=209.5s

  [15424/15692] intraday_9731.csv.gz  in=420,153,781 out=106,086,326 elapsed=209.5s

  [15425/15692] intraday_9729.csv.gz  in=420,155,077 out=106,086,780 elapsed=209.5s

  [15426/15692] intraday_9733.csv.gz  in=420,157,467 out=106,088,061 elapsed=209.5s

  [15427/15692] intraday_9734.csv.gz  in=420,158,675 out=106,089,269 elapsed=209.5s

  [15428/15692] intraday_9735.csv.gz  in=420,159,421 out=106,089,555 elapsed=209.5s

  [15429/15692] intraday_9736.csv.gz  in=420,159,847 out=106,089,981 elapsed=209.5s

  [15430/15692] intraday_9738.csv.gz  in=420,159,850 out=106,089,984 elapsed=209.5s

  [15431/15692] intraday_9737.csv.gz  in=420,160,284 out=106,090,418 elapsed=209.5s

  [15432/15692] intraday_9739.csv.gz  in=420,170,736 out=106,094,968 elapsed=209.6s

  [15433/15692] intraday_9740.csv.gz  in=420,185,789 out=106,110,021 elapsed=209.6s

  [15434/15692] intraday_9742.csv.gz  in=420,198,206 out=106,122,438 elapsed=209.6s

  [15435/15692] intraday_9741.csv.gz  in=420,210,980 out=106,135,212 elapsed=209.6s

  [15436/15692] intraday_9743.csv.gz  in=420,220,203 out=106,144,435 elapsed=209.6s

  [15437/15692] intraday_9744.csv.gz  in=420,232,047 out=106,156,279 elapsed=209.6s

  [15438/15692] intraday_9745.csv.gz  in=420,247,603 out=106,171,835 elapsed=209.7s

  [15439/15692] intraday_9748.csv.gz  in=420,260,020 out=106,184,252 elapsed=209.7s

  [15440/15692] intraday_9747.csv.gz  in=420,271,233 out=106,195,465 elapsed=209.7s

  [15441/15692] intraday_9746.csv.gz  in=420,285,396 out=106,209,628 elapsed=209.7s

  [15442/15692] intraday_9749.csv.gz  in=420,300,434 out=106,224,666 elapsed=209.7s

  [15443/15692] intraday_9751.csv.gz  in=420,312,882 out=106,237,114 elapsed=209.7s

  [15444/15692] intraday_9752.csv.gz  in=420,326,024 out=106,250,256 elapsed=209.7s

  [15445/15692] intraday_9750.csv.gz  in=420,341,338 out=106,265,570 elapsed=209.7s

  [15446/15692] intraday_9753.csv.gz  in=420,356,857 out=106,281,089 elapsed=209.7s

  [15447/15692] intraday_9754.csv.gz  in=420,366,584 out=106,290,816 elapsed=209.8s

  [15448/15692] intraday_9755.csv.gz  in=420,378,341 out=106,302,573 elapsed=209.8s

  [15449/15692] intraday_9756.csv.gz  in=420,390,611 out=106,314,843 elapsed=209.8s

  [15450/15692] intraday_9757.csv.gz  in=420,404,807 out=106,329,039 elapsed=209.8s

  [15451/15692] intraday_9758.csv.gz  in=420,416,067 out=106,340,299 elapsed=209.8s

  [15452/15692] intraday_9760.csv.gz  in=420,427,941 out=106,352,173 elapsed=209.8s

  [15453/15692] intraday_9761.csv.gz  in=420,441,968 out=106,366,200 elapsed=209.8s

  [15454/15692] intraday_9759.csv.gz  in=420,452,979 out=106,377,211 elapsed=209.8s

  [15455/15692] intraday_9762.csv.gz  in=420,465,322 out=106,389,554 elapsed=209.9s

  [15456/15692] intraday_9763.csv.gz  in=420,478,103 out=106,402,335 elapsed=209.9s

  [15457/15692] intraday_9765.csv.gz  in=420,490,324 out=106,414,556 elapsed=209.9s

  [15458/15692] intraday_9764.csv.gz  in=420,503,528 out=106,427,760 elapsed=209.9s

  [15459/15692] intraday_9766.csv.gz  in=420,516,005 out=106,440,237 elapsed=209.9s

  [15460/15692] intraday_9767.csv.gz  in=420,527,727 out=106,451,959 elapsed=209.9s

  [15461/15692] intraday_9768.csv.gz  in=420,538,744 out=106,462,976 elapsed=209.9s

  [15462/15692] intraday_9770.csv.gz  in=420,552,923 out=106,477,155 elapsed=210.0s

  [15463/15692] intraday_9769.csv.gz  in=420,565,741 out=106,489,973 elapsed=210.0s

  [15464/15692] intraday_9772.csv.gz  in=420,576,542 out=106,500,774 elapsed=210.0s

  [15465/15692] intraday_9771.csv.gz  in=420,591,250 out=106,515,482 elapsed=210.0s

  [15466/15692] intraday_9773.csv.gz  in=420,602,123 out=106,526,355 elapsed=210.0s

  [15467/15692] intraday_9774.csv.gz  in=420,615,430 out=106,539,662 elapsed=210.0s

  [15468/15692] intraday_9776.csv.gz  in=420,625,924 out=106,550,156 elapsed=210.0s

  [15469/15692] intraday_9778.csv.gz  in=420,636,147 out=106,560,379 elapsed=210.1s

  [15470/15692] intraday_9775.csv.gz  in=420,649,720 out=106,573,952 elapsed=210.1s

  [15471/15692] intraday_9777.csv.gz  in=420,662,246 out=106,586,478 elapsed=210.1s

  [15472/15692] intraday_9779.csv.gz  in=420,672,565 out=106,596,797 elapsed=210.1s

  [15473/15692] intraday_9780.csv.gz  in=420,683,397 out=106,607,629 elapsed=210.1s

  [15474/15692] intraday_9781.csv.gz  in=420,694,475 out=106,618,707 elapsed=210.1s

  [15475/15692] intraday_9782.csv.gz  in=420,707,423 out=106,631,655 elapsed=210.1s

  [15476/15692] intraday_9783.csv.gz  in=420,720,146 out=106,644,378 elapsed=210.1s

  [15477/15692] intraday_9785.csv.gz  in=420,733,245 out=106,657,477 elapsed=210.1s

  [15478/15692] intraday_9784.csv.gz  in=420,746,076 out=106,670,308 elapsed=210.1s

  [15479/15692] intraday_9786.csv.gz  in=420,757,598 out=106,681,830 elapsed=210.2s

  [15480/15692] intraday_9787.csv.gz  in=420,768,863 out=106,693,095 elapsed=210.2s

  [15481/15692] intraday_9788.csv.gz  in=420,781,703 out=106,705,935 elapsed=210.2s

  [15482/15692] intraday_9789.csv.gz  in=420,792,393 out=106,716,625 elapsed=210.2s

  [15483/15692] intraday_9790.csv.gz  in=420,803,714 out=106,727,946 elapsed=210.2s

  [15484/15692] intraday_9791.csv.gz  in=420,815,207 out=106,739,439 elapsed=210.2s

  [15485/15692] intraday_9793.csv.gz  in=420,828,566 out=106,752,798 elapsed=210.2s

  [15486/15692] intraday_9792.csv.gz  in=420,839,330 out=106,763,562 elapsed=210.2s

  [15487/15692] intraday_9794.csv.gz  in=420,849,936 out=106,774,168 elapsed=210.3s

  [15488/15692] intraday_9795.csv.gz  in=420,863,261 out=106,787,493 elapsed=210.3s

  [15489/15692] intraday_9796.csv.gz  in=420,875,580 out=106,799,812 elapsed=210.3s

  [15490/15692] intraday_9798.csv.gz  in=420,887,379 out=106,811,611 elapsed=210.3s

  [15491/15692] intraday_9797.csv.gz  in=420,899,770 out=106,824,002 elapsed=210.3s

  [15492/15692] intraday_9800.csv.gz  in=420,911,444 out=106,835,676 elapsed=210.3s

  [15493/15692] intraday_9799.csv.gz  in=420,923,686 out=106,847,918 elapsed=210.3s

  [15494/15692] intraday_9802.csv.gz  in=420,934,692 out=106,858,924 elapsed=210.3s

  [15495/15692] intraday_9801.csv.gz  in=420,947,780 out=106,872,012 elapsed=210.3s

  [15496/15692] intraday_9803.csv.gz  in=420,960,449 out=106,884,681 elapsed=210.4s

  [15497/15692] intraday_9805.csv.gz  in=420,971,684 out=106,895,916 elapsed=210.4s

  [15498/15692] intraday_9804.csv.gz  in=420,984,026 out=106,908,258 elapsed=210.4s

  [15499/15692] intraday_9806.csv.gz  in=420,999,118 out=106,923,350 elapsed=210.4s

  [15500/15692] intraday_9807.csv.gz  in=421,011,811 out=106,936,043 elapsed=210.4s

  [15501/15692] intraday_9809.csv.gz  in=421,024,161 out=106,948,393 elapsed=210.4s

  [15502/15692] intraday_9811.csv.gz  in=421,034,740 out=106,958,972 elapsed=210.5s

  [15503/15692] intraday_9808.csv.gz  in=421,049,492 out=106,973,724 elapsed=210.5s

  [15504/15692] intraday_9810.csv.gz  in=421,061,985 out=106,986,217 elapsed=210.5s

  [15505/15692] intraday_9812.csv.gz  in=421,074,325 out=106,998,557 elapsed=210.5s

  [15506/15692] intraday_9813.csv.gz  in=421,087,182 out=107,011,414 elapsed=210.5s

  [15507/15692] intraday_9815.csv.gz  in=421,099,362 out=107,023,594 elapsed=210.5s

  [15508/15692] intraday_9814.csv.gz  in=421,113,570 out=107,037,802 elapsed=210.5s

  [15509/15692] intraday_9816.csv.gz  in=421,127,501 out=107,051,733 elapsed=210.5s

  [15510/15692] intraday_9817.csv.gz  in=421,137,623 out=107,061,855 elapsed=210.5s

  [15511/15692] intraday_9819.csv.gz  in=421,150,515 out=107,074,747 elapsed=210.6s

  [15512/15692] intraday_9818.csv.gz  in=421,163,948 out=107,088,180 elapsed=210.6s

  [15513/15692] intraday_9820.csv.gz  in=421,175,248 out=107,099,480 elapsed=210.6s

  [15514/15692] intraday_9821.csv.gz  in=421,187,023 out=107,111,255 elapsed=210.6s

  [15515/15692] intraday_9822.csv.gz  in=421,197,414 out=107,121,646 elapsed=210.6s

  [15516/15692] intraday_9823.csv.gz  in=421,208,806 out=107,133,038 elapsed=210.6s

  [15517/15692] intraday_9824.csv.gz  in=421,220,606 out=107,144,838 elapsed=210.6s

  [15518/15692] intraday_9825.csv.gz  in=421,237,172 out=107,161,404 elapsed=210.6s

  [15519/15692] intraday_9827.csv.gz  in=421,248,355 out=107,172,587 elapsed=210.7s

  [15520/15692] intraday_9826.csv.gz  in=421,264,447 out=107,188,679 elapsed=210.7s

  [15521/15692] intraday_9828.csv.gz  in=421,277,533 out=107,201,765 elapsed=210.7s

  [15522/15692] intraday_9829.csv.gz  in=421,292,165 out=107,216,397 elapsed=210.7s

  [15523/15692] intraday_9830.csv.gz  in=421,305,075 out=107,229,307 elapsed=210.7s

  [15524/15692] intraday_9831.csv.gz  in=421,319,787 out=107,244,019 elapsed=210.7s

  [15525/15692] intraday_9832.csv.gz  in=421,331,382 out=107,255,614 elapsed=210.7s

  [15526/15692] intraday_9834.csv.gz  in=421,345,009 out=107,269,241 elapsed=210.8s

  [15527/15692] intraday_9833.csv.gz  in=421,357,367 out=107,281,599 elapsed=210.8s

  [15528/15692] intraday_9835.csv.gz  in=421,370,240 out=107,294,472 elapsed=210.8s

  [15529/15692] intraday_9836.csv.gz  in=421,383,780 out=107,308,012 elapsed=210.8s

  [15530/15692] intraday_9837.csv.gz  in=421,396,819 out=107,321,051 elapsed=210.8s

  [15531/15692] intraday_9838.csv.gz  in=421,409,164 out=107,333,396 elapsed=210.8s

  [15532/15692] intraday_9839.csv.gz  in=421,421,939 out=107,346,171 elapsed=210.8s

  [15533/15692] intraday_9840.csv.gz  in=421,435,493 out=107,359,725 elapsed=210.9s

  [15534/15692] intraday_9842.csv.gz  in=421,446,696 out=107,370,928 elapsed=210.9s

  [15535/15692] intraday_9843.csv.gz  in=421,460,362 out=107,384,594 elapsed=210.9s

  [15536/15692] intraday_9841.csv.gz  in=421,472,243 out=107,396,475 elapsed=210.9s

  [15537/15692] intraday_9844.csv.gz  in=421,486,980 out=107,411,212 elapsed=210.9s

  [15538/15692] intraday_9845.csv.gz  in=421,500,914 out=107,425,146 elapsed=210.9s

  [15539/15692] intraday_9847.csv.gz  in=421,513,724 out=107,437,956 elapsed=210.9s

  [15540/15692] intraday_9846.csv.gz  in=421,526,855 out=107,451,087 elapsed=211.0s

  [15541/15692] intraday_9848.csv.gz  in=421,543,231 out=107,467,463 elapsed=211.0s

  [15542/15692] intraday_9849.csv.gz  in=421,554,349 out=107,478,581 elapsed=211.0s

  [15543/15692] intraday_9850.csv.gz  in=421,566,682 out=107,490,914 elapsed=211.0s

  [15544/15692] intraday_9851.csv.gz  in=421,581,253 out=107,505,485 elapsed=211.0s

  [15545/15692] intraday_9853.csv.gz  in=421,591,322 out=107,515,554 elapsed=211.0s

  [15546/15692] intraday_9852.csv.gz  in=421,605,806 out=107,530,038 elapsed=211.0s

  [15547/15692] intraday_9854.csv.gz  in=421,619,282 out=107,543,514 elapsed=211.0s

  [15548/15692] intraday_9855.csv.gz  in=421,631,707 out=107,555,939 elapsed=211.0s

  [15549/15692] intraday_9856.csv.gz  in=421,644,662 out=107,568,894 elapsed=211.1s

  [15550/15692] intraday_9857.csv.gz  in=421,659,879 out=107,584,111 elapsed=211.1s

  [15551/15692] intraday_9858.csv.gz  in=421,675,330 out=107,599,562 elapsed=211.1s

  [15552/15692] intraday_9859.csv.gz  in=421,692,616 out=107,616,848 elapsed=211.1s

  [15553/15692] intraday_9860.csv.gz  in=421,708,361 out=107,632,593 elapsed=211.1s

  [15554/15692] intraday_9861.csv.gz  in=421,720,409 out=107,644,641 elapsed=211.1s

  [15555/15692] intraday_9863.csv.gz  in=421,732,937 out=107,657,169 elapsed=211.1s

  [15556/15692] intraday_9862.csv.gz  in=421,746,001 out=107,670,233 elapsed=211.1s

  [15557/15692] intraday_9865.csv.gz  in=421,759,394 out=107,683,626 elapsed=211.2s

  [15558/15692] intraday_9864.csv.gz  in=421,769,791 out=107,694,023 elapsed=211.2s

  [15559/15692] intraday_9866.csv.gz  in=421,780,738 out=107,704,970 elapsed=211.2s

  [15560/15692] intraday_9868.csv.gz  in=421,794,029 out=107,718,261 elapsed=211.2s

  [15561/15692] intraday_9867.csv.gz  in=421,809,036 out=107,733,268 elapsed=211.2s

  [15562/15692] intraday_9869.csv.gz  in=421,824,320 out=107,748,552 elapsed=211.2s

  [15563/15692] intraday_9870.csv.gz  in=421,837,383 out=107,761,615 elapsed=211.5s

  [15564/15692] intraday_9871.csv.gz  in=421,848,403 out=107,772,635 elapsed=211.6s

  [15565/15692] intraday_9872.csv.gz  in=421,860,175 out=107,784,407 elapsed=211.6s

  [15566/15692] intraday_9874.csv.gz  in=421,870,681 out=107,794,913 elapsed=211.6s

  [15567/15692] intraday_9873.csv.gz  in=421,884,688 out=107,808,920 elapsed=211.6s

  [15568/15692] intraday_9875.csv.gz  in=421,898,991 out=107,823,223 elapsed=211.6s

  [15569/15692] intraday_9876.csv.gz  in=421,913,372 out=107,837,604 elapsed=211.6s

  [15570/15692] intraday_9879.csv.gz  in=421,925,577 out=107,849,809 elapsed=211.7s

  [15571/15692] intraday_9880.csv.gz  in=421,937,965 out=107,862,197 elapsed=211.7s

  [15572/15692] intraday_9878.csv.gz  in=421,952,394 out=107,876,626 elapsed=211.7s

  [15573/15692] intraday_9877.csv.gz  in=421,966,335 out=107,890,567 elapsed=211.7s

  [15574/15692] intraday_9882.csv.gz  in=421,977,189 out=107,901,421 elapsed=211.7s

  [15575/15692] intraday_9883.csv.gz  in=421,990,498 out=107,914,730 elapsed=211.7s

  [15576/15692] intraday_9881.csv.gz  in=422,004,663 out=107,928,895 elapsed=211.7s

  [15577/15692] intraday_9884.csv.gz  in=422,011,667 out=107,935,899 elapsed=211.7s

  [15578/15692] intraday_9885.csv.gz  in=422,020,041 out=107,944,273 elapsed=211.8s

  [15579/15692] intraday_9886.csv.gz  in=422,030,627 out=107,954,859 elapsed=211.8s

  [15580/15692] intraday_9887.csv.gz  in=422,045,222 out=107,969,454 elapsed=211.8s

  [15581/15692] intraday_9888.csv.gz  in=422,057,489 out=107,981,721 elapsed=211.8s

  [15582/15692] intraday_9890.csv.gz  in=422,067,777 out=107,992,009 elapsed=211.8s

  [15583/15692] intraday_9889.csv.gz  in=422,079,399 out=108,003,631 elapsed=211.8s

  [15584/15692] intraday_9891.csv.gz  in=422,090,963 out=108,015,195 elapsed=211.9s

  [15585/15692] intraday_9892.csv.gz  in=422,105,822 out=108,030,054 elapsed=211.9s

  [15586/15692] intraday_9893.csv.gz  in=422,120,299 out=108,044,531 elapsed=211.9s

  [15587/15692] intraday_9894.csv.gz  in=422,130,930 out=108,055,162 elapsed=211.9s

  [15588/15692] intraday_9895.csv.gz  in=422,142,810 out=108,067,042 elapsed=211.9s

  [15589/15692] intraday_9897.csv.gz  in=422,156,663 out=108,080,895 elapsed=211.9s

  [15590/15692] intraday_9896.csv.gz  in=422,171,359 out=108,095,591 elapsed=211.9s

  [15591/15692] intraday_9899.csv.gz  in=422,185,201 out=108,109,433 elapsed=212.0s

  [15592/15692] intraday_9898.csv.gz  in=422,197,196 out=108,121,428 elapsed=212.0s

  [15593/15692] intraday_9901.csv.gz  in=422,207,750 out=108,131,982 elapsed=212.0s

  [15594/15692] intraday_9900.csv.gz  in=422,223,283 out=108,146,130 elapsed=212.0s

  [15595/15692] intraday_9902.csv.gz  in=422,236,325 out=108,159,172 elapsed=212.0s

  [15596/15692] intraday_9904.csv.gz  in=422,252,873 out=108,175,720 elapsed=212.0s

  [15597/15692] intraday_9903.csv.gz  in=422,266,068 out=108,187,609 elapsed=212.0s

  [15598/15692] intraday_9905.csv.gz  in=422,278,790 out=108,200,331 elapsed=212.0s

  [15599/15692] intraday_9906.csv.gz  in=422,289,537 out=108,211,078 elapsed=212.1s

  [15600/15692] intraday_9907.csv.gz  in=422,304,454 out=108,225,995 elapsed=212.1s

  [15601/15692] intraday_9909.csv.gz  in=422,318,889 out=108,239,448 elapsed=212.1s

  [15602/15692] intraday_9910.csv.gz  in=422,332,444 out=108,252,688 elapsed=212.1s

  [15603/15692] intraday_9908.csv.gz  in=422,346,148 out=108,266,392 elapsed=212.1s

  [15604/15692] intraday_9911.csv.gz  in=422,358,866 out=108,279,110 elapsed=212.1s

  [15605/15692] intraday_9912.csv.gz  in=422,371,039 out=108,291,283 elapsed=212.1s

  [15606/15692] intraday_9913.csv.gz  in=422,382,179 out=108,302,423 elapsed=212.1s

  [15607/15692] intraday_9915.csv.gz  in=422,392,284 out=108,312,528 elapsed=212.1s

  [15608/15692] intraday_9914.csv.gz  in=422,404,050 out=108,324,294 elapsed=212.2s

  [15609/15692] intraday_9917.csv.gz  in=422,419,980 out=108,340,224 elapsed=212.2s

  [15610/15692] intraday_9916.csv.gz  in=422,434,728 out=108,354,972 elapsed=212.2s

  [15611/15692] intraday_9918.csv.gz  in=422,447,810 out=108,368,054 elapsed=212.2s

  [15612/15692] intraday_9919.csv.gz  in=422,459,109 out=108,379,353 elapsed=212.2s

  [15613/15692] intraday_9921.csv.gz  in=422,471,260 out=108,391,504 elapsed=212.2s

  [15614/15692] intraday_9920.csv.gz  in=422,482,382 out=108,402,626 elapsed=212.2s

  [15615/15692] intraday_9922.csv.gz  in=422,496,560 out=108,416,804 elapsed=212.3s

  [15616/15692] intraday_9923.csv.gz  in=422,507,649 out=108,427,893 elapsed=212.3s

  [15617/15692] intraday_9925.csv.gz  in=422,518,611 out=108,438,855 elapsed=212.3s

  [15618/15692] intraday_9924.csv.gz  in=422,531,296 out=108,451,540 elapsed=212.3s

  [15619/15692] intraday_9927.csv.gz  in=422,542,522 out=108,462,766 elapsed=212.3s

  [15620/15692] intraday_9926.csv.gz  in=422,569,097 out=108,479,620 elapsed=212.3s

  [15621/15692] intraday_9928.csv.gz  in=422,580,275 out=108,490,798 elapsed=212.3s

  [15622/15692] intraday_9929.csv.gz  in=422,593,678 out=108,504,201 elapsed=212.4s

  [15623/15692] intraday_9930.csv.gz  in=422,605,275 out=108,515,798 elapsed=212.4s

  [15624/15692] intraday_9931.csv.gz  in=422,619,227 out=108,529,750 elapsed=212.4s

  [15625/15692] intraday_9932.csv.gz  in=422,631,943 out=108,542,466 elapsed=212.4s

  [15626/15692] intraday_9933.csv.gz  in=422,642,676 out=108,553,199 elapsed=212.4s

  [15627/15692] intraday_9934.csv.gz  in=422,654,653 out=108,565,176 elapsed=212.4s

  [15628/15692] intraday_9935.csv.gz  in=422,666,380 out=108,576,903 elapsed=212.4s

  [15629/15692] intraday_9936.csv.gz  in=422,677,166 out=108,587,689 elapsed=212.5s

  [15630/15692] intraday_9937.csv.gz  in=422,688,174 out=108,598,697 elapsed=212.5s

  [15631/15692] intraday_9939.csv.gz  in=422,700,123 out=108,610,646 elapsed=212.5s

  [15632/15692] intraday_9938.csv.gz  in=422,711,093 out=108,621,616 elapsed=212.5s

  [15633/15692] intraday_9941.csv.gz  in=422,723,090 out=108,633,613 elapsed=212.5s

  [15634/15692] intraday_9942.csv.gz  in=422,737,550 out=108,646,789 elapsed=212.5s

  [15635/15692] intraday_9940.csv.gz  in=422,751,137 out=108,660,376 elapsed=212.5s

  [15636/15692] intraday_9943.csv.gz  in=422,764,614 out=108,673,853 elapsed=212.6s

  [15637/15692] intraday_9944.csv.gz  in=422,777,171 out=108,686,410 elapsed=212.6s

  [15638/15692] intraday_9946.csv.gz  in=422,789,047 out=108,698,286 elapsed=212.6s

  [15639/15692] intraday_9945.csv.gz  in=422,800,028 out=108,709,267 elapsed=212.6s

  [15640/15692] intraday_9948.csv.gz  in=422,814,091 out=108,722,537 elapsed=212.6s

  [15641/15692] intraday_9947.csv.gz  in=422,826,383 out=108,734,829 elapsed=212.6s

  [15642/15692] intraday_9950.csv.gz  in=422,837,770 out=108,746,216 elapsed=212.6s

  [15643/15692] intraday_9949.csv.gz  in=422,850,268 out=108,758,714 elapsed=212.6s

  [15644/15692] intraday_9952.csv.gz  in=422,860,102 out=108,768,548 elapsed=212.7s

  [15645/15692] intraday_9951.csv.gz  in=422,871,761 out=108,780,207 elapsed=212.7s

  [15646/15692] intraday_9954.csv.gz  in=422,884,794 out=108,793,240 elapsed=212.7s

  [15647/15692] intraday_9953.csv.gz  in=422,904,005 out=108,811,301 elapsed=212.7s

  [15648/15692] intraday_9955.csv.gz  in=422,918,878 out=108,826,174 elapsed=212.7s

  [15649/15692] intraday_9956.csv.gz  in=422,932,295 out=108,839,591 elapsed=212.7s

  [15650/15692] intraday_9958.csv.gz  in=422,942,091 out=108,849,387 elapsed=212.7s

  [15651/15692] intraday_9957.csv.gz  in=422,954,512 out=108,861,808 elapsed=212.8s

  [15652/15692] intraday_9959.csv.gz  in=422,967,470 out=108,874,766 elapsed=212.8s

  [15653/15692] intraday_9960.csv.gz  in=422,980,306 out=108,887,602 elapsed=212.8s

  [15654/15692] intraday_9961.csv.gz  in=422,994,435 out=108,901,731 elapsed=212.8s

  [15655/15692] intraday_9962.csv.gz  in=423,006,833 out=108,914,129 elapsed=212.8s

  [15656/15692] intraday_9964.csv.gz  in=423,017,972 out=108,925,268 elapsed=212.8s

  [15657/15692] intraday_9963.csv.gz  in=423,030,691 out=108,937,987 elapsed=212.8s

  [15658/15692] intraday_9965.csv.gz  in=423,044,341 out=108,951,637 elapsed=212.8s

  [15659/15692] intraday_9966.csv.gz  in=423,055,389 out=108,962,685 elapsed=212.8s

  [15660/15692] intraday_9967.csv.gz  in=423,067,345 out=108,974,641 elapsed=212.8s

  [15661/15692] intraday_9968.csv.gz  in=423,078,904 out=108,986,200 elapsed=212.9s

  [15662/15692] intraday_9970.csv.gz  in=423,089,457 out=108,996,753 elapsed=212.9s

  [15663/15692] intraday_9971.csv.gz  in=423,116,665 out=109,016,234 elapsed=212.9s

  [15664/15692] intraday_9969.csv.gz  in=423,125,820 out=109,025,389 elapsed=212.9s

  [15665/15692] intraday_9972.csv.gz  in=423,143,730 out=109,043,299 elapsed=212.9s

  [15666/15692] intraday_9973.csv.gz  in=423,158,182 out=109,057,751 elapsed=212.9s

  [15667/15692] intraday_9974.csv.gz  in=423,170,100 out=109,069,669 elapsed=212.9s

  [15668/15692] intraday_9975.csv.gz  in=423,181,061 out=109,080,630 elapsed=212.9s

  [15669/15692] intraday_9976.csv.gz  in=423,197,287 out=109,096,856 elapsed=213.0s

  [15670/15692] intraday_9977.csv.gz  in=423,217,486 out=109,111,787 elapsed=213.0s

  [15671/15692] intraday_9979.csv.gz  in=423,228,372 out=109,122,673 elapsed=213.0s

  [15672/15692] intraday_9978.csv.gz  in=423,244,540 out=109,138,841 elapsed=213.0s

  [15673/15692] intraday_9980.csv.gz  in=423,256,191 out=109,150,492 elapsed=213.0s

  [15674/15692] intraday_9981.csv.gz  in=423,269,507 out=109,163,808 elapsed=213.0s

  [15675/15692] intraday_9983.csv.gz  in=423,281,914 out=109,176,215 elapsed=213.0s

  [15676/15692] intraday_9982.csv.gz  in=423,295,234 out=109,189,535 elapsed=213.0s

  [15677/15692] intraday_9984.csv.gz  in=423,308,919 out=109,203,220 elapsed=213.0s

  [15678/15692] intraday_9985.csv.gz  in=423,321,281 out=109,215,582 elapsed=213.0s

  [15679/15692] intraday_9986.csv.gz  in=423,332,889 out=109,227,190 elapsed=213.1s

  [15680/15692] intraday_9987.csv.gz  in=423,346,078 out=109,240,379 elapsed=213.1s

  [15681/15692] intraday_9988.csv.gz  in=423,357,630 out=109,251,931 elapsed=213.1s

  [15682/15692] intraday_9989.csv.gz  in=423,368,652 out=109,262,953 elapsed=213.1s

  [15683/15692] intraday_9990.csv.gz  in=423,381,029 out=109,275,330 elapsed=213.1s

  [15684/15692] intraday_9992.csv.gz  in=423,393,655 out=109,287,956 elapsed=213.1s

  [15685/15692] intraday_9991.csv.gz  in=423,410,371 out=109,304,672 elapsed=213.1s

  [15686/15692] intraday_9994.csv.gz  in=423,420,983 out=109,315,284 elapsed=213.1s

  [15687/15692] intraday_9993.csv.gz  in=423,435,475 out=109,329,776 elapsed=213.1s

  [15688/15692] intraday_9996.csv.gz  in=423,447,141 out=109,341,442 elapsed=213.1s

  [15689/15692] intraday_9998.csv.gz  in=423,460,472 out=109,354,773 elapsed=213.2s

  [15690/15692] intraday_9997.csv.gz  in=423,472,871 out=109,367,172 elapsed=213.2s

  [15691/15692] intraday_9995.csv.gz  in=423,488,756 out=109,383,057 elapsed=213.2s

  [15692/15692] intraday_9999.csv.gz  in=423,503,839 out=109,397,168 elapsed=213.2s

✅ DONE  in=423,503,839 → out=109,397,168  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 222.5s

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [20]:
def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,      # лишено для сумісності виклику
    *,
    max_workers: int = 4,
) -> pd.DataFrame:
    """Денні open (перший бар 09:30–09:35) і close (останній бар 15:55–15:59).

    Раніше кожен відібраний рядок проходив через itertuples + оновлення python-словника;
    тепер редукція повністю векторна (sort + drop_duplicates у pyarrow/pandas).
    Клітинка 19 уже рахує це за один прохід — ця функція лишається як самостійний шлях.
    """
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    open_parts, close_parts = [], []
    lock = threading.Lock()

    def _handle(path):
        reader = _open_intraday_csv(path, 64 << 20)
        lo, lc = [], []
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            o_df, c_df = _oc_from_table(pa.Table.from_batches([rb]))
            if len(o_df):
                lo.append(o_df)
            if len(c_df):
                lc.append(c_df)
        with lock:
            open_parts.extend(lo)
            close_parts.extend(lc)

    if max_workers and max_workers > 1:
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            list(ex.map(_handle, files))
    else:
        for p in files:
            _handle(p)

    out = _finalize_oc(open_parts, close_parts)

    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)
    return out

In [21]:
# oc.parquet уже побудовано в клітинці 19 (той самий прохід по файлах).
# Перебудовуємо лише якщо його немає.
_oc_path = str(WORK_DIR / "oc.parquet")
if os.path.exists(_oc_path):
    df_oc = pd.read_parquet(_oc_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(BATCH_DIR), out_path=_oc_path)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [22]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def _prep_oc_prev_close(df_oc: pd.DataFrame) -> pd.DataFrame:
    """['ticker','date','open','prev_close'], date — звичайний рядок 'YYYY-MM-DD'."""
    oc = df_oc[["ticker", "date", "open", "close"]].copy()
    oc["ticker"] = oc["ticker"].astype(str)
    oc["date"] = oc["date"].astype(str).str.slice(0, 10)
    oc = oc.sort_values(["ticker", "date"], kind="stable")
    oc["prev_close"] = oc.groupby("ticker", sort=False)["close"].shift(1)
    return oc[["ticker", "date", "open", "prev_close"]].reset_index(drop=True)


def _date_from_dt(s: pd.Series) -> pd.Series:
    """'YYYY-MM-DD' з 'dt'. Для рядкового dt це зріз (C-рівень), без парсингу дат."""
    if pd.api.types.is_string_dtype(s) or s.dtype == object:
        return s.astype(str).str.slice(0, 10)
    return s.dt.strftime("%Y-%m-%d")


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame,
                                        _oc_prepared: Optional[pd.DataFrame] = None,
                                        sort_out: bool = False) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']

    Прискорення проти попередньої версії:
      - 'dt' лишається рядком: ні pd.to_datetime, ні .dt.date (це були python-об'єкти
        на кожен рядок — найдорожча операція в усьому пайплайні);
      - prev_close рахується ОДИН раз (передається через _oc_prepared), а не на кожен батч;
      - без per-batch sort_values (фінальне сортування робить клітинка 47).
    """
    right = _oc_prepared if _oc_prepared is not None else _prep_oc_prev_close(df_oc)
    out = df_intraday
    out = out[out["dt"].notna()]
    out = out.assign(date=_date_from_dt(out["dt"]))
    out = out.merge(right, on=["ticker", "date"], how="left")
    if sort_out:
        out = out.sort_values(["ticker", "dt"], kind="stable").reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    sort_out: bool = False,
):
    """
    Читає великий Parquet батчами і мерджить денні open/prev_close з oc.parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    df_oc = pd.read_parquet(oc_parquet_path)
    missing = {"ticker", "date", "open", "close"} - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")
    oc_prepared = _prep_oc_prev_close(df_oc)      # рахуємо ОДИН раз, не на кожен батч

    if os.path.exists(out_path):
        os.remove(out_path)
    if not out_path.endswith((".csv", ".gz", ".parquet")):
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0

    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}", flush=True)

    for batch_idx, batch in enumerate(pf.iter_batches(batch_size=batch_rows, columns=cols), 1):
        df_batch = batch.to_pandas()
        df_enriched = enrich_with_day_open_and_prev_close(
            df_batch, None, _oc_prepared=oc_prepared, sort_out=sort_out)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched, preserve_index=False)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            df_enriched.to_csv(
                out_path, index=False, mode="a", header=(total_rows == 0),
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_enriched)
        if batch_idx % log_every_batches == 0:
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s", flush=True)


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [23]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
# print("Результат у файлі:", out_path)

In [24]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    Обчислення в numpy (без проміжних pandas-Series і .replace), без gc на кожен батч.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  "
          f"batch_rows≈{batch_rows:,}  using={value_col}", flush=True)

    for batches, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for c in ("prev_close", value_col):
            if c not in df.columns:
                raise KeyError(f"У вхідному файлі немає колонки '{c}'.")

        num = pd.to_numeric(df[value_col], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        den = pd.to_numeric(df["prev_close"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            pct = np.where(den == 0, np.nan, num / den - 1.0) * 100.0   # 0 → NaN, без ділення на 0
        if round_to is not None:
            pct = np.round(pct, int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s", flush=True)
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [25]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
# print("Готово:", out_path)

In [26]:
import os
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Read ticker->bench mapping from csv/xlsx and return ['ticker','bench'].
    """
    ext = os.path.splitext(mapping_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(mapping_path)
    else:
        try:
            df = pd.read_csv(mapping_path, sep=None, engine="python")
        except Exception:
            df = pd.read_csv(mapping_path)

    cols = {c.lower().strip(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol") or list(df.columns)[0]
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf") or list(df.columns)[1]

    out = df[[tcol, bcol]].rename(columns={tcol: "ticker", bcol: "bench"}).dropna()
    out["ticker"] = out["ticker"].astype(str).str.upper().str.strip()
    out["bench"] = out["bench"].astype(str).str.upper().str.strip()
    out = out[(out["ticker"] != "") & (out["bench"] != "")]
    return out.drop_duplicates(ignore_index=True)


def corr_beta_from_mapping_to_parquet(*args, **kwargs):
    """
    Deprecated API path removed.
    corr/beta is now computed locally in cell 12 and written in cell 13/28.
    """
    raise RuntimeError(
        "corr_beta_from_mapping_to_parquet is deprecated. "
        "Use local calculation in cell 12 and parquet output in cell 13/28."
    )

In [27]:
import os
import pandas as pd

out_path = str(WORK_DIR / "corr_beta_pairs.parquet")

# If parquet already exists from cell 13, keep it.
# Otherwise rebuild it from x_to_best_etf_by_lvl3.csv (no API calls).
if not os.path.exists(out_path):
    src_csv = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv")
    if not os.path.exists(src_csv):
        raise FileNotFoundError(f"Neither {out_path} nor {src_csv} exists")

    d = pd.read_csv(src_csv)
    need = ["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
    miss = [c for c in need if c not in d.columns]
    if miss:
        raise KeyError(f"Missing columns in {src_csv}: {miss}")

    d = d.rename(columns={
        "best_y_ticker": "y_ticker",
        "best_corr": "corr",
        "beta_with_best": "beta",
    })[["x_ticker", "y_ticker", "corr", "beta"]]
    d.to_parquet(out_path, index=False)

print("Result:", out_path)

Result: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [28]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    df = pq.read_table(path).to_pandas()
    inv = {c.strip().lower(): c for c in df.columns}

    has_api = ("x_ticker" in inv) and ("y_ticker" in inv)
    has_direct = ("ticker" in inv) and ("bench" in inv)
    if not (has_api or has_direct):
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={inv["x_ticker"]: "ticker", inv["y_ticker"]: "bench"})
    else:
        df = df.rename(columns={inv["ticker"]: "ticker", inv["bench"]: "bench"})

    for c in ("corr", "beta"):
        if c in inv:
            df = df.rename(columns={inv[c]: c})
        else:
            df[c] = pd.NA

    df = df[["ticker", "bench", "corr", "beta"]].copy()
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"] = df["bench"].astype(str).str.strip().str.upper()
    df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    return (df.sort_values(["ticker", "corr"], ascending=[True, False])
              .drop_duplicates(subset=["ticker"], keep="first")
              .reset_index(drop=True))


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), додає 'bench','corr','beta' по 'ticker'.

    Замість merge на кожен батч (+ strip/upper над мільйонами рядків) нормалізація і
    пошук у мапі йдуть по унікальних тікерах, а результат розгортається за кодами.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if mapping.empty:
        raise ValueError(
            f"Мапа bench/corr/beta порожня: {corrbeta_parquet_path}. "
            "Крок побудови x_to_best_etf_by_lvl3 не дав жодного рядка — "
            "інакше bench/corr/beta були б null у всіх рядках."
        )

    m_bench = dict(zip(mapping["ticker"], mapping["bench"]))
    m_corr = dict(zip(mapping["ticker"], mapping["corr"]))
    m_beta = dict(zip(mapping["ticker"], mapping["beta"]))

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_parquet_path}", flush=True)

    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        # dtype="string" тримає bench рядковим і в батчі без жодного збігу: інакше
        # суцільний None дає pyarrow-тип null і схема розійдеться з першим батчем
        df["bench"] = pd.array(_map_by_ticker(codes, cats, m_bench, numeric=False), dtype="string")
        df["corr"] = _map_by_ticker(codes, cats, m_corr, numeric=True)
        df["beta"] = _map_by_ticker(codes, cats, m_beta, numeric=True)

        cols = [c for c in df.columns if c not in ("bench", "corr", "beta")]
        if insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]]
        else:
            df = df[cols + ["bench", "corr", "beta"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        elif not table.schema.equals(writer.schema, check_metadata=False):
            table = table.cast(writer.schema)
        writer.write_table(table)

        total_rows += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_parquet_path


# опціональний аліас під старе ім'я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [29]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = attach_bench_corr_beta_parquet(
#     input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
#     corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
#     out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
#     batch_rows=2_000_000,
#     round_decimals=4,
#     insert_before="pct_vs_prev_close",
#     compression="snappy",
# )
# print("Готово:", out_path)

In [30]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [31]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Проміжного premarket_rows_final.parquet більше не існує: bench/corr/beta
# додаються за той самий прохід, що й решта. Готовий файл — у комірці 47.

In [32]:
# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [33]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=12,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 0 тікерів (пропущено 0 по старому маніфесту) | 2026-06-08 00:00:00 → 2026-09-08 23:59:59 | interval=1 | next batch #0119 | run=61ff5ce3

   workers: tickers=12, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 28

   📉 пропущені дні (в межах window): 2026-06-08 → 2026-09-08 (93 днів)

   📈 обробляються дні: –

   psutil · старт · 🧠 RAM: 684.6 MB

   🔚 фінал · 🧠 RAM: 684.6 MB

🏁 Готово. Нових рядків: 0 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:00

In [34]:
# Один прохід по ETF-батчах: premarket-рядки + денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc_etf.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    build_oc=True,
    max_workers=4,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  files=118 workers=4

  [1/118] intraday_0004.csv.gz  in=1,760 out=1,760 elapsed=0.0s

  [2/118] intraday_0003.csv.gz  in=10,518 out=10,518 elapsed=0.1s

  [3/118] intraday_0002.csv.gz  in=20,691 out=20,691 elapsed=0.1s

  [4/118] intraday_0005.csv.gz  in=31,264 out=31,264 elapsed=0.1s

  [5/118] intraday_0006.csv.gz  in=41,355 out=41,355 elapsed=0.2s

  [6/118] intraday_0008.csv.gz  in=52,039 out=52,039 elapsed=0.2s

  [7/118] intraday_0007.csv.gz  in=62,186 out=62,186 elapsed=0.2s

  [8/118] intraday_0009.csv.gz  in=70,760 out=70,760 elapsed=0.2s

  [9/118] intraday_0011.csv.gz  in=80,494 out=80,494 elapsed=0.2s

  [10/118] intraday_0010.csv.gz  in=81,941 out=81,941 elapsed=0.2s

  [11/118] intraday_0012.csv.gz  in=91,152 out=91,152 elapsed=0.2s

  [12/118] intraday_0014.csv.gz  in=100,785 out=100,785 elapsed=0.2s

  [13/118] intraday_0013.csv.gz  in=110,387 out=110,387 elapsed=0.2s

  [14/118] intraday_0016.csv.gz  in=111,758 out=111,758 elapsed=0.3s

  [15/118] intraday_0015.csv.gz  in=120,035 out=120,035 elapsed=0.3s

  [16/118] intraday_0017.csv.gz  in=129,351 out=129,351 elapsed=0.3s

  [17/118] intraday_0018.csv.gz  in=138,578 out=138,578 elapsed=0.3s

  [18/118] intraday_0021.csv.gz  in=140,181 out=140,181 elapsed=0.3s

  [19/118] intraday_0019.csv.gz  in=149,677 out=149,677 elapsed=0.3s

  [20/118] intraday_0020.csv.gz  in=157,847 out=157,847 elapsed=0.3s

  [21/118] intraday_0022.csv.gz  in=187,047 out=187,047 elapsed=0.3s

  [22/118] intraday_0024.csv.gz  in=208,187 out=208,187 elapsed=0.3s

  [23/118] intraday_0023.csv.gz  in=218,002 out=218,002 elapsed=0.3s

  [24/118] intraday_0026.csv.gz  in=226,279 out=226,279 elapsed=0.4s

  [25/118] intraday_0027.csv.gz  in=235,077 out=235,077 elapsed=0.4s

  [26/118] intraday_0028.csv.gz  in=244,053 out=244,053 elapsed=0.4s

  [27/118] intraday_0029.csv.gz  in=252,994 out=252,994 elapsed=0.4s

  [28/118] intraday_0030.csv.gz  in=262,243 out=262,243 elapsed=0.4s

  [29/118] intraday_0031.csv.gz  in=271,145 out=271,145 elapsed=0.4s

  [30/118] intraday_0032.csv.gz  in=279,924 out=279,924 elapsed=0.4s

  [31/118] intraday_0025.csv.gz  in=384,366 out=384,366 elapsed=0.5s

  [32/118] intraday_0033.csv.gz  in=393,143 out=393,143 elapsed=0.5s

  [33/118] intraday_0034.csv.gz  in=401,796 out=401,796 elapsed=0.5s

  [34/118] intraday_0036.csv.gz  in=410,721 out=410,721 elapsed=0.5s

  [35/118] intraday_0035.csv.gz  in=419,433 out=419,433 elapsed=0.5s

  [36/118] intraday_0037.csv.gz  in=428,355 out=428,355 elapsed=0.5s

  [37/118] intraday_0038.csv.gz  in=437,237 out=437,237 elapsed=0.7s

  [38/118] intraday_0039.csv.gz  in=445,326 out=445,326 elapsed=0.7s

  [39/118] intraday_0040.csv.gz  in=453,919 out=453,919 elapsed=0.7s

  [40/118] intraday_0001.csv.gz  in=1,040,839 out=1,040,839 elapsed=0.7s

  [41/118] intraday_0041.csv.gz  in=1,050,147 out=1,050,147 elapsed=0.7s

  [42/118] intraday_0042.csv.gz  in=1,058,326 out=1,058,326 elapsed=0.8s

  [43/118] intraday_0044.csv.gz  in=1,066,843 out=1,066,843 elapsed=0.8s

  [44/118] intraday_0043.csv.gz  in=1,074,838 out=1,074,838 elapsed=0.8s

  [45/118] intraday_0046.csv.gz  in=1,083,204 out=1,083,204 elapsed=0.8s

  [46/118] intraday_0045.csv.gz  in=1,090,385 out=1,090,385 elapsed=0.8s

  [47/118] intraday_0048.csv.gz  in=1,098,693 out=1,098,693 elapsed=0.8s

  [48/118] intraday_0047.csv.gz  in=1,107,041 out=1,107,041 elapsed=0.8s

  [49/118] intraday_0049.csv.gz  in=1,115,603 out=1,115,603 elapsed=0.8s

  [50/118] intraday_0050.csv.gz  in=1,123,880 out=1,123,880 elapsed=0.8s

  [51/118] intraday_0051.csv.gz  in=1,132,076 out=1,132,076 elapsed=0.8s

  [52/118] intraday_0052.csv.gz  in=1,140,350 out=1,140,350 elapsed=0.9s

  [53/118] intraday_0054.csv.gz  in=1,148,330 out=1,148,330 elapsed=0.9s

  [54/118] intraday_0053.csv.gz  in=1,156,344 out=1,156,344 elapsed=0.9s

  [55/118] intraday_0057.csv.gz  in=1,165,167 out=1,165,167 elapsed=0.9s

  [56/118] intraday_0056.csv.gz  in=1,173,385 out=1,173,385 elapsed=0.9s

  [57/118] intraday_0058.csv.gz  in=1,181,781 out=1,181,781 elapsed=0.9s

  [58/118] intraday_0059.csv.gz  in=1,189,748 out=1,189,748 elapsed=0.9s

  [59/118] intraday_0060.csv.gz  in=1,197,814 out=1,197,814 elapsed=0.9s

  [60/118] intraday_0061.csv.gz  in=1,206,064 out=1,206,064 elapsed=1.0s

  [61/118] intraday_0062.csv.gz  in=1,214,193 out=1,214,193 elapsed=1.0s

  [62/118] intraday_0063.csv.gz  in=1,222,519 out=1,222,519 elapsed=1.0s

  [63/118] intraday_0064.csv.gz  in=1,230,741 out=1,230,741 elapsed=1.0s

  [64/118] intraday_0065.csv.gz  in=1,239,106 out=1,239,106 elapsed=1.0s

  [65/118] intraday_0066.csv.gz  in=1,246,888 out=1,246,888 elapsed=1.1s

  [66/118] intraday_0068.csv.gz  in=1,255,406 out=1,255,406 elapsed=1.1s

  [67/118] intraday_0067.csv.gz  in=1,263,663 out=1,263,663 elapsed=1.1s

  [68/118] intraday_0055.csv.gz  in=1,377,472 out=1,377,472 elapsed=1.1s

  [69/118] intraday_0072.csv.gz  in=1,394,819 out=1,394,819 elapsed=1.1s

  [70/118] intraday_0070.csv.gz  in=1,412,403 out=1,412,403 elapsed=1.1s

  [71/118] intraday_0071.csv.gz  in=1,430,041 out=1,430,041 elapsed=1.1s

  [72/118] intraday_0073.csv.gz  in=1,447,121 out=1,447,121 elapsed=1.2s

  [73/118] intraday_0074.csv.gz  in=1,464,856 out=1,464,856 elapsed=1.3s

  [74/118] intraday_0075.csv.gz  in=1,482,239 out=1,482,239 elapsed=1.3s

  [75/118] intraday_0076.csv.gz  in=1,498,996 out=1,498,996 elapsed=1.3s

  [76/118] intraday_0077.csv.gz  in=1,501,364 out=1,501,364 elapsed=1.3s

  [77/118] intraday_0079.csv.gz  in=1,517,849 out=1,517,849 elapsed=1.3s

  [78/118] intraday_0080.csv.gz  in=1,534,786 out=1,534,786 elapsed=1.3s

  [79/118] intraday_0078.csv.gz  in=1,552,382 out=1,552,382 elapsed=1.3s

  [80/118] intraday_0081.csv.gz  in=1,569,544 out=1,569,544 elapsed=1.3s

  [81/118] intraday_0082.csv.gz  in=1,586,413 out=1,586,413 elapsed=1.4s

  [82/118] intraday_0084.csv.gz  in=1,603,713 out=1,603,713 elapsed=1.4s

  [83/118] intraday_0083.csv.gz  in=1,621,662 out=1,621,662 elapsed=1.4s

  [84/118] intraday_0085.csv.gz  in=1,638,586 out=1,638,586 elapsed=1.4s

  [85/118] intraday_0086.csv.gz  in=1,655,557 out=1,655,557 elapsed=1.4s

  [86/118] intraday_0087.csv.gz  in=1,672,374 out=1,672,374 elapsed=1.4s

  [87/118] intraday_0088.csv.gz  in=1,690,115 out=1,690,115 elapsed=1.4s

  [88/118] intraday_0091.csv.gz  in=1,707,230 out=1,707,230 elapsed=1.5s

  [89/118] intraday_0090.csv.gz  in=1,723,628 out=1,723,628 elapsed=1.5s

  [90/118] intraday_0092.csv.gz  in=1,739,843 out=1,739,843 elapsed=1.5s

  [91/118] intraday_0093.csv.gz  in=1,739,852 out=1,739,852 elapsed=1.5s

  [92/118] intraday_0089.csv.gz  in=1,867,411 out=1,867,411 elapsed=1.6s

  [93/118] intraday_0095.csv.gz  in=1,883,964 out=1,883,964 elapsed=1.6s

  [94/118] intraday_0094.csv.gz  in=1,902,926 out=1,902,926 elapsed=1.6s

  [95/118] intraday_0096.csv.gz  in=1,920,844 out=1,920,844 elapsed=1.6s

  [96/118] intraday_0097.csv.gz  in=1,937,006 out=1,937,006 elapsed=1.6s

  [97/118] intraday_0098.csv.gz  in=1,952,695 out=1,952,695 elapsed=1.6s

  [98/118] intraday_0099.csv.gz  in=1,954,305 out=1,954,305 elapsed=1.7s

  [99/118] intraday_0101.csv.gz  in=1,971,118 out=1,971,118 elapsed=1.7s

  [100/118] intraday_0100.csv.gz  in=1,987,634 out=1,987,634 elapsed=1.7s

  [101/118] intraday_0103.csv.gz  in=2,006,707 out=2,006,707 elapsed=1.7s

  [102/118] intraday_0105.csv.gz  in=2,025,920 out=2,025,920 elapsed=1.8s

  [103/118] intraday_0106.csv.gz  in=2,045,930 out=2,045,930 elapsed=2.0s

  [104/118] intraday_0069.csv.gz  in=2,791,183 out=2,791,183 elapsed=2.0s

  [105/118] intraday_0102.csv.gz  in=3,023,268 out=3,023,268 elapsed=2.1s

  [106/118] intraday_0108.csv.gz  in=3,042,308 out=3,042,308 elapsed=2.1s

  [107/118] intraday_0107.csv.gz  in=3,062,175 out=3,062,175 elapsed=2.1s

  [108/118] intraday_0109.csv.gz  in=3,079,631 out=3,079,631 elapsed=2.2s

  [109/118] intraday_0110.csv.gz  in=3,099,353 out=3,099,353 elapsed=2.2s

  [110/118] intraday_0112.csv.gz  in=3,101,522 out=3,101,522 elapsed=2.2s

  [111/118] intraday_0113.csv.gz  in=3,120,377 out=3,120,377 elapsed=2.3s

  [112/118] intraday_0114.csv.gz  in=3,140,120 out=3,140,120 elapsed=2.3s

  [113/118] intraday_0104.csv.gz  in=3,726,346 out=3,726,346 elapsed=2.5s

  [114/118] intraday_0115.csv.gz  in=3,745,321 out=3,745,321 elapsed=2.5s

  [115/118] intraday_0116.csv.gz  in=3,764,168 out=3,764,168 elapsed=2.5s

  [116/118] intraday_0111.csv.gz  in=4,032,352 out=4,032,352 elapsed=2.5s

  [117/118] intraday_0117.csv.gz  in=4,049,528 out=4,049,528 elapsed=2.5s

  [118/118] intraday_0118.csv.gz  in=4,067,862 out=4,067,862 elapsed=2.5s

✅ DONE  in=4,067,862 → out=4,067,862  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 2.6s

In [35]:
# oc_etf.parquet уже побудовано в клітинці 34 (той самий прохід по файлах).
_oc_etf_path = str(WORK_DIR / "oc_etf.parquet")
if os.path.exists(_oc_etf_path):
    df_oc = pd.read_parquet(_oc_etf_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(ETF_DIR), out_path=_oc_etf_path)
print(df_oc.head())

  ticker        date   open  close
0   ARKK  2026-05-01  75.85  76.84
1   ARKK  2026-05-04  77.24  78.21
2   ARKK  2026-05-05  78.40  76.62
3   ARKK  2026-05-06  77.33  79.54
4   ARKK  2026-05-07  79.40  78.09

In [36]:
# Ті самі оптимізовані функції, що й у клітинці 22 — тут лише інші дефолти обгортки
# (ETF-файли замість акційних).
def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [37]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=4,067,862  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 5.4s

Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [38]:
# Та сама оптимізована add_pct_vs_prev_close_parquet із клітинки 24 —
# тут лише інші дефолти обгортки (ETF-файли, колонка Bench%).
def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",              # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [39]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=4,067,862  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 3.3s

Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [40]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий по ключах ('bench'↔'ticker', 'dt').

    Прискорення: ETF-мапа читається одним pq.read_table (лише 3 потрібні колонки)
    замість iter_batches + concat + gc; ключ 'dt' лишається рядком —
    лексикографічний порядок 'YYYY-MM-DD HH:MM:SS' збігається з хронологічним,
    тож per-row парсинг дат не потрібен (крім align_to_minute=True).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    t0 = time.time()

    # ---------- 1) Мапа з ETF-файла: (bench, dt) -> Bench% ----------
    etf_names = [f.name for f in pq.ParquetFile(etf_path).schema_arrow]
    cl = {c.lower().strip(): c for c in etf_names}
    for col in ("ticker", "dt"):
        if col not in cl:
            raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")
    val_col = cl.get("bench%") or cl.get("pct_vs_prev_close")
    if val_col is None:
        raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

    etf_map = pq.read_table(etf_path, columns=[cl["ticker"], cl["dt"], val_col]).to_pandas()
    etf_map.columns = ["bench", "dt", "Bench%"]
    etf_map["bench"] = etf_map["bench"].astype(str).str.strip().str.upper()
    etf_map["Bench%"] = pd.to_numeric(etf_map["Bench%"], errors="coerce")
    if round_decimals is not None:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    _dt_is_str = (etf_map["dt"].dtype == object) or pd.api.types.is_string_dtype(etf_map["dt"])
    if align_to_minute or not _dt_is_str:
        etf_map["dt"] = pd.to_datetime(etf_map["dt"], errors="coerce")
        if align_to_minute:
            etf_map["dt"] = etf_map["dt"].dt.floor("T")
    else:
        etf_map["dt"] = etf_map["dt"].astype(str)

    etf_map = (etf_map.dropna(subset=["dt"])
                      .sort_values(["bench", "dt"], kind="stable")
                      .drop_duplicates(subset=["bench", "dt"], keep="last")
                      .reset_index(drop=True))

    # ---------- 2) Потоково проходимо базовий файл ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_path}", flush=True)
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        codes, cats = _ticker_codes(df["bench"])
        df["bench"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)

        _base_dt_is_str = (df["dt"].dtype == object) or pd.api.types.is_string_dtype(df["dt"])
        if align_to_minute or not _base_dt_is_str:
            df["dt"] = pd.to_datetime(df["dt"], errors="coerce")
            if align_to_minute:
                df["dt"] = df["dt"].dt.floor("T")
        else:
            df["dt"] = df["dt"].astype(str)

        merged = df.merge(etf_map, on=["bench", "dt"], how="left")

        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = [c for c in merged.columns if c != "Bench%"]
            pos = cols.index(insert_before)
            merged = merged[cols[:pos] + ["Bench%"] + cols[pos:]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [41]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# merge_bench_pct_from_etf(
#     base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
#     etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
#     out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
#     batch_rows=2_000_000,
#     align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
#     round_decimals=2,
#     insert_before=None,          # або, наприклад, "pct_vs_prev_close"
#     compression="snappy",
# )

In [42]:
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed


def _pick_first_existing(df: pd.DataFrame, candidates):
    cols_l = {c.lower().strip(): c for c in df.columns}
    for c in candidates:
        if c.lower() in cols_l:
            return cols_l[c.lower()]
    return None


_REPORT_FAILS = {"n": 0}
_GAP_FAILS = {"n": 0}


def _datum_request_retry(endpoint, params, *, max_retries=6, backoff=0.5):
    """Повторює запит при 429/мережевих збоях з наростаючою паузою.
    Вичерпавши спроби — кидає останній виняток."""
    import random, time
    for attempt in range(max_retries + 1):
        try:
            return DatumApi.data_request(endpoint, params)
        except Exception:
            if attempt == max_retries:
                raise
            time.sleep(backoff * (2 ** attempt) * (0.9 + 0.2 * random.random()))


def get_reports(ticker, last_n_reports, start_date, end_date):
    try:
        params = {
            "ticker": str(ticker),
            "start_move_date": str(start_date)[:10],
            "end_move_date": str(end_date)[:10],
        }
        reports_df = _datum_request_retry("/reports", params)
        if reports_df is None or reports_df.empty:
            return pd.DataFrame(columns=["ticker", "report_date"])

        date_col = _pick_first_existing(
            reports_df,
            ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"],
        )
        if date_col is None:
            return pd.DataFrame(columns=["ticker", "report_date"])

        out = reports_df.copy()
        out["report_date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
        out["ticker"] = str(ticker).upper()
        out = out.dropna(subset=["report_date"])
        out = out.sort_values("report_date").tail(int(last_n_reports))
        return out[["ticker", "report_date"]].reset_index(drop=True)
    except Exception as e:
        _REPORT_FAILS["n"] += 1
        print(f"Report fetch failed for {ticker}: {e}")
        return pd.DataFrame(columns=["ticker", "report_date"])


def get_reports_for_tickers(tickers_df, start_date, end_date, last_n_reports=20,
                            max_workers=8, max_fail_ratio=0.15):
    # 16 потоків без пауз давали суцільні 429; з retry вистачає меншого числа
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    parts = []
    _REPORT_FAILS["n"] = 0

    # Ті самі репорти вже завантажила комірка 11. Беремо їх лише коли вікно,
    # last_n_reports і набір тикерів збігаються; інакше — звичайний фетч.
    _c = globals().get("CRACEN_FETCH_CACHE") or {}
    if (_c.get("window") == (str(start_date)[:10], str(end_date)[:10])
            and _c.get("last_n_reports") == int(last_n_reports)
            and set(tickers) <= _c.get("tickers", set())):
        _r = _c["reports"].rename(columns={"date": "report_date"})
        _r = (_r[_r["ticker"].isin(tickers)]
                .drop_duplicates(["ticker", "report_date"]).reset_index(drop=True))
        print(f"Reports: узято з кешу комірки 11 ({len(_r)} рядків), фетч пропущено")
        return _r, _r.groupby("ticker")["report_date"].apply(set).to_dict()

    def fetch(t):
        return get_reports(ticker=t, last_n_reports=last_n_reports, start_date=start_date, end_date=end_date)

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Reports"):
            rep = f.result()
            if rep is not None and not rep.empty:
                parts.append(rep)

    if tickers and _REPORT_FAILS["n"] / len(tickers) > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_REPORT_FAILS['n']} з {len(tickers)} тикерів "
            f"({_REPORT_FAILS['n'] / len(tickers) * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Репорти вийшли б неповними."
        )

    if not parts:
        return pd.DataFrame(columns=["ticker", "report_date"]), {}

    reports = pd.concat(parts, ignore_index=True).drop_duplicates(["ticker", "report_date"])
    report_days_map = reports.groupby("ticker")["report_date"].apply(set).to_dict()
    return reports, report_days_map


def get_gaps_for_tickers_excluding_reports(tickers_df, start_date, end_date, report_days_map,
                                           max_workers=8, max_fail_ratio=0.15):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    _GAP_FAILS["n"] = 0

    _c = globals().get("CRACEN_FETCH_CACHE") or {}
    if (_c.get("window") == (str(start_date)[:10], str(end_date)[:10])
            and set(tickers) <= _c.get("tickers", set())):
        _g = _c["gaps"]
        _g = _g[_g["ticker"].isin(tickers)].copy()
        _rep = pd.DataFrame([(t, d) for t, ds in (report_days_map or {}).items() for d in ds],
                            columns=["ticker", "date"])
        if len(_rep):
            _g = _g.merge(_rep.assign(_r=1), on=["ticker", "date"], how="left")
            _g = _g[_g["_r"].isna()].drop(columns="_r")
        print(f"Gaps: узято з кешу комірки 11 ({len(_g)} рядків), фетч пропущено")
        return _g.reset_index(drop=True)

    def fetch(t):
        params = {
            "ticker": t,
            "start_date": str(start_date)[:10],
            "end_date": str(end_date)[:10],
            "format": "json_records",
        }
        try:
            df_gap = _datum_request_retry("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                return None

            date_col = _pick_first_existing(df_gap, ["date", "move_date", "dt", "datetime", "day"])
            if date_col is None:
                return None

            out = df_gap.copy()
            out["ticker"] = out["ticker"].astype(str).str.upper() if "ticker" in out.columns else t
            out["date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
            out["gap"] = pd.to_numeric(out.get("gap"), errors="coerce")
            out = out.dropna(subset=["date", "gap"])

            report_days = report_days_map.get(t, set())
            if report_days:
                out = out[~out["date"].isin(report_days)]

            return out if not out.empty else None
        except Exception as e:
            _GAP_FAILS["n"] += 1
            print(f"Gap fetch failed for {t}: {e}")
            return None

    all_results = []
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Gaps (ex-reports)"):
            result = f.result()
            if result is not None:
                all_results.append(result)

    if tickers and _GAP_FAILS["n"] / len(tickers) > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_GAP_FAILS['n']} з {len(tickers)} тикерів "
            f"({_GAP_FAILS['n'] / len(tickers) * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Гепи вийшли б неповними."
        )

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    return pd.DataFrame(columns=["ticker", "date", "gap"])


def add_rolling_sigma_cap(
    df,
    value_col,
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=None,
):
    """Rolling std по попередньому вікну з обрізанням хвостів на квантилі cap_q.

    Раніше це був rolling(...).apply(python_func) — окремий виклик Python на кожне
    вікно кожного тікера. Тепер вікна будуються через sliding_window_view і квантиль/
    clip/std рахуються одразу по всій матриці вікон групи (чисто numpy).
    Результат збігається з попередньою реалізацією до 1e-12.
    """
    if min_periods is None:
        min_periods = window

    out = df.sort_values([group_col, date_col], kind="stable").copy()
    col = f"{value_col}_sigma_{window}d_cap"

    # Рідкісний випадок min_periods != window має іншу семантику (часткові вікна) —
    # там лишаємо стару, повільну, але точну реалізацію.
    if min_periods != window:
        def compute_sigma(s):
            x = s.shift(1)

            def f(arr):
                arr = arr[~np.isnan(arr)]
                if len(arr) < min_periods:
                    return np.nan
                cap = np.quantile(np.abs(arr), cap_q)
                arr_capped = np.clip(arr, -cap, cap)
                return np.std(arr_capped, ddof=1)

            return x.rolling(window, min_periods=min_periods).apply(f, raw=True)

        out[col] = out.groupby(group_col)[value_col].transform(compute_sigma)
        return out

    vals = pd.to_numeric(out[value_col], errors="coerce").to_numpy(dtype="float64")
    codes, _ = pd.factorize(out[group_col], sort=False)
    res = np.full(vals.shape, np.nan)

    order = np.argsort(codes, kind="stable")
    bounds = np.flatnonzero(np.diff(codes[order])) + 1
    for sl in np.split(order, bounds):
        n = sl.size
        if n <= window:
            continue
        x = vals[sl]
        # вікно з ПОПЕРЕДНІХ значень (еквівалент shift(1) у старій версії)
        w = np.lib.stride_tricks.sliding_window_view(x[:-1], window)   # (n-window, window)
        cap = np.quantile(np.abs(w), cap_q, axis=1, keepdims=True)
        res[sl[window:]] = np.clip(w, -cap, cap).std(axis=1, ddof=1)

    out[col] = res
    return out


# 1) Report days in the working window
reports_df, report_days_map = get_reports_for_tickers(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
)
print("Report rows:", len(reports_df))

# 2) Gaps without report days
df_gaps_all = get_gaps_for_tickers_excluding_reports(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    report_days_map=report_days_map,
)
print("Rows in gaps (without report days):", len(df_gaps_all))

# 3) Rolling sigma
sigma_daily = add_rolling_sigma_cap(
    df=df_gaps_all,
    value_col="gap",
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=20,
)

sigma_col = "gap_sigma_20d_cap"

std_by_ticker = (
    sigma_daily.dropna(subset=[sigma_col])
    .sort_values(["ticker", "date"])
    .groupby("ticker", as_index=False)
    .tail(1)[["ticker", sigma_col]]
    .rename(columns={sigma_col: "sigma"})
    .reset_index(drop=True)
)

print("Tickers with sigma:", len(std_by_ticker))
std_by_ticker.head()

Reports: узято з кешу комірки 11 (4182 рядків), фетч пропущено
Report rows: 4182

Gaps: узято з кешу комірки 11 (444918 рядків), фетч пропущено
Rows in gaps (without report days): 444918

Tickers with sigma: 7095

  ticker     sigma
0      A  0.664418
1     AA  1.537772
2   AAAU  0.894833
3   AACG  2.557269
4   AADX  1.136964

In [43]:
std_by_ticker

     ticker     sigma
0         A  0.664418
1        AA  1.537772
2      AAAU  0.894833
3      AACG  2.557269
4      AADX  1.136964
...     ...       ...
7090   ZVIA  1.421882
7091   ZVOL  0.411389
7092   ZVRA  0.768461
7093    ZWS  0.753721
7094   ZYBT  1.835335

[7095 rows x 2 columns]

In [44]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"] = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet.

    Як і в клітинці 28: нормалізація тікера і пошук у мапі йдуть по унікальних
    значеннях, а не по кожному з мільйонів рядків; per-batch merge не потрібен.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)
    sd = dict(zip(sigma_map["ticker"], sigma_map["sigma"]))

    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}", flush=True)
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["sigma"] = _map_by_ticker(codes, cats, sd, numeric=True)

        cols = [c for c in df.columns if c != "sigma"]
        if insert_before and insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["sigma"] + cols[idx:]]
        else:
            df = df[cols + ["sigma"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [45]:
def build_final_in_one_pass(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    corrbeta_parquet_path: str,
    etf_parquet_path: str,
    out_parquet_path: str,
    *,
    sigma_df=None,
    sigma_path=None,
    batch_rows: int = 2_000_000,
    round_decimals=4,
    stack_round_to=None,
    bench_round_decimals=2,
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """Один потоковий прохід замість п'яти: oc-мердж → Stack% → bench/corr/beta
    → Bench% → sigma. Замінює merge_intraday_and_oc_to_file +
    add_pct_vs_prev_close_parquet + attach_bench_corr_beta_parquet +
    merge_bench_pct_from_etf + add_sigma_by_ticker_to_parquet.

    Результат побайтово збігається з ланцюжком; економія — у тому, що ~3 ГБ
    читаються й пишуться один раз, а не шість.
    """
    t0 = time.time()

    # ---------- side-входи: готуються ОДИН раз ----------
    oc_prepared = _prep_oc_prev_close(pq.read_table(oc_parquet_path).to_pandas())

    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if mapping.empty:
        raise ValueError(
            f"Мапа bench/corr/beta порожня: {corrbeta_parquet_path}. "
            "Крок побудови x_to_best_etf_by_lvl3 не дав жодного рядка."
        )
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)
    m_bench = dict(zip(mapping["ticker"], mapping["bench"]))
    m_corr = dict(zip(mapping["ticker"], mapping["corr"]))
    m_beta = dict(zip(mapping["ticker"], mapping["beta"]))

    etf_names = [f.name for f in pq.ParquetFile(etf_parquet_path).schema_arrow]
    cl = {c.lower().strip(): c for c in etf_names}
    val_col = cl.get("bench%") or cl.get("pct_vs_prev_close")
    etf_map = pq.read_table(etf_parquet_path,
                            columns=[cl["ticker"], cl["dt"], val_col]).to_pandas()
    etf_map.columns = ["bench", "dt", "Bench%"]
    etf_map["bench"] = etf_map["bench"].astype(str).str.strip().str.upper()
    etf_map["Bench%"] = pd.to_numeric(etf_map["Bench%"], errors="coerce")
    if bench_round_decimals is not None:
        etf_map["Bench%"] = etf_map["Bench%"].round(bench_round_decimals)
    etf_map["dt"] = etf_map["dt"].astype(str)
    etf_map = (etf_map.dropna(subset=["dt"])
                      .sort_values(["bench", "dt"], kind="stable")
                      .drop_duplicates(subset=["bench", "dt"], keep="last")
                      .reset_index(drop=True))

    sig = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    m_sigma = dict(zip(sig["ticker"], sig["sigma"]))

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    ORDER = ["ticker", "dt", "o", "h", "l", "c", "v", "date", "open", "prev_close",
             "Stack%", "bench", "corr", "beta", "Bench%", "sigma"]

    pf = pq.ParquetFile(intraday_parquet_path)
    writer = None
    total_rows = 0
    print(f"▶️ START one-pass → {out_parquet_path}", flush=True)

    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # 1) день + open/prev_close (ключ — сирий ticker, як у ланцюжку)
        df = df[df["dt"].notna()]
        df = df.assign(date=_date_from_dt(df["dt"]))
        df = df.merge(oc_prepared, on=["ticker", "date"], how="left")

        # 2) Stack%
        num = pd.to_numeric(df["o"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        den = pd.to_numeric(df["prev_close"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            pct = np.where(den == 0, np.nan, num / den - 1.0) * 100.0
        if stack_round_to is not None:
            pct = np.round(pct, int(stack_round_to))
        df["Stack%"] = pct

        # 3) bench/corr/beta (тут ticker нормалізується — як у ланцюжку)
        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["bench"] = _map_by_ticker(codes, cats, m_bench, numeric=False)
        df["corr"] = _map_by_ticker(codes, cats, m_corr, numeric=True)
        df["beta"] = _map_by_ticker(codes, cats, m_beta, numeric=True)

        # 4) sigma — теж по codes/cats, тому рахуємо ДО мерджа
        df["sigma"] = _map_by_ticker(codes, cats, m_sigma, numeric=True)

        # 5) Bench% по (bench, dt); bench лишається object для мерджа
        df["dt"] = df["dt"].astype(str)
        df = df.merge(etf_map, on=["bench", "dt"], how="left")

        # string-dtype один раз наприкінці: тримає тип bench стабільним між батчами
        df["bench"] = pd.array(df["bench"], dtype="string")

        df = df[[c for c in ORDER if c in df.columns]]
        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        elif not table.schema.equals(writer.schema, check_metadata=False):
            table = table.cast(writer.schema)
        writer.write_table(table)

        total_rows += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,} elapsed={time.time()-t0:,.1f}s", flush=True)
        del df, table, batch
        gc.collect()

    if writer is not None:
        writer.close()
    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path} in {time.time()-t0:,.1f}s", flush=True)
    return out_parquet_path

In [46]:
# std_by_ticker columns: ['ticker', 'sigma']
# Один прохід замість п'яти: oc-мердж → Stack% → bench/corr/beta → Bench% → sigma.
# Замінює комірки 23, 25, 29, 41 і колишній add_sigma_by_ticker_to_parquet.
sigma_out_path = build_final_in_one_pass(
    intraday_parquet_path=str(WORK_DIR / "premarket_rows.parquet"),
    oc_parquet_path=str(WORK_DIR / "oc.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    etf_parquet_path=str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    sigma_df=std_by_ticker,
    batch_rows=2_000_000,
    round_decimals=4,
    bench_round_decimals=2,
    compression="snappy",
)

# Validation: output parquet must contain sigma matching std_by_ticker
check_df = pd.read_parquet(sigma_out_path, columns=["ticker", "sigma"])
if "sigma" not in check_df.columns:
    raise KeyError("Column 'sigma' is missing in parquet after merge")

file_sigma = (
    check_df.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

exp_sigma = (
    std_by_ticker.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

common = file_sigma.index.intersection(exp_sigma.index)
if len(common) == 0:
    raise ValueError("No common tickers to validate sigma between std_by_ticker and parquet")

diff = (file_sigma.loc[common] - exp_sigma.loc[common]).abs()
max_diff = float(diff.max()) if len(diff) else 0.0
print("sigma_out_path:", sigma_out_path)
print("tickers in std_by_ticker:", len(exp_sigma))
print("tickers checked in parquet:", len(common))
print("max |file_sigma - expected_sigma|:", max_diff)

▶️ START one-pass → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000 elapsed=36.6s

[batch   10] rows=20,000,000 elapsed=65.8s

[batch   15] rows=30,000,000 elapsed=95.7s

[batch   20] rows=40,000,000 elapsed=125.1s

[batch   25] rows=50,000,000 elapsed=154.0s

[batch   30] rows=60,000,000 elapsed=183.4s

[batch   35] rows=70,000,000 elapsed=212.9s

[batch   40] rows=80,000,000 elapsed=242.7s

[batch   45] rows=90,000,000 elapsed=271.1s

[batch   50] rows=100,000,000 elapsed=299.6s

[batch   55] rows=109,397,168 elapsed=326.4s

✅ DONE rows=109,397,168 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet in 326.4s

sigma_out_path: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
tickers in std_by_ticker: 7095
tickers checked in parquet: 7093
max |file_sigma - expected_sigma|: 0.0

In [47]:
peek_parquet(str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"), n=21150)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 109,397,168
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 299/21150
NaN у 'corr' (у прев'ю): 299/21150
NaN у 'beta' (у прев'ю): 299/21150

Перші рядки:

      ticker                   dt           o           h           l           c          v        date    open  prev_close        Stack% bench    corr    beta  Bench%     sigma
0        SCO  2026-06-30 00:23:00   34.900002   34.900002   34.900002   34.900002        8.0  2026-06-30   34.13       34.82  2.297574e-01   IWM  0.3962  1.3229     NaN  2.017616
1        SCO  2026-06-30 00:26:00   34.939999   34.939999   34.939999   34.939999        1.0  2026-06-30   34.13       34.82  3.446256e-01   IWM  0.3962  1.3229     NaN  2.017616
2        SCO  2026-06-30 00:28:00   35.000000   35.009998   35.000000   35.009998      205.0  2026-06-30   34.13       34.82  5.169443e-01   IWM  0.3962  1.3229     NaN  2.017616
3        SCO  2026-06-30 00:31:00   35.009998   35.009998   35.009998   35.009998       12.0  2026-06-30   34.13       34.82  5.456586e-01   IWM  0.3962  1.3229     NaN  2.017616
4        SCO  2026-06-30 00:34:00   34.990002   34.990002   34.990002   34.990002       11.0  2026-06-30   34.13       34.82  4.882300e-01   IWM  0.3962  1.3229     NaN  2.017616
5        SCO  2026-06-30 00:35:00   35.020000   35.020000   35.020000   35.020000        1.0  2026-06-30   34.13       34.82  5.743839e-01   IWM  0.3962  1.3229    0.15  2.017616
6        SCO  2026-06-30 00:40:00   35.020000   35.020000   35.020000   35.020000        1.0  2026-06-30   34.13       34.82  5.743839e-01   IWM  0.3962  1.3229     NaN  2.017616
7        SCO  2026-06-30 00:43:00   35.049999   35.049999   35.049999   35.049999      100.0  2026-06-30   34.13       34.82  6.605377e-01   IWM  0.3962  1.3229     NaN  2.017616
8        SCO  2026-06-30 00:45:00   35.029999   35.029999   35.029999   35.029999       21.0  2026-06-30   34.13       34.82  6.030982e-01   IWM  0.3962  1.3229     NaN  2.017616
9        SCO  2026-06-30 00:47:00   35.029999   35.029999   35.029999   35.029999      100.0  2026-06-30   34.13       34.82  6.030982e-01   IWM  0.3962  1.3229    0.12  2.017616
10       SCO  2026-06-30 01:00:00   35.060001   35.099998   35.060001   35.099998      519.0  2026-06-30   34.13       34.82  6.892630e-01   IWM  0.3962  1.3229    0.12  2.017616
11       SCO  2026-06-30 01:01:00   35.150002   35.200001   35.150002   35.200001      832.0  2026-06-30   34.13       34.82  9.477356e-01   IWM  0.3962  1.3229     NaN  2.017616
12       SCO  2026-06-30 01:02:00   35.200001   35.200001   35.200001   35.200001      100.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.3962  1.3229     NaN  2.017616
13       SCO  2026-06-30 01:04:00   35.200001   35.200001   35.200001   35.200001        5.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.3962  1.3229    0.17  2.017616
14       SCO  2026-06-30 01:08:00   35.200001   35.200001   35.189999   35.189999      230.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.3962  1.3229    0.17  2.017616
15       SCO  2026-06-30 01:11:00   35.150002   35.150002   35.150002   35.150002        5.0  2026-06-30   34.13       34.82  9.477356e-01   IWM  0.3962  1.3229     NaN  2.017616
16       SCO  2026-06-30 01:12:00   35.130001   35.130001   35.130001   35.130001        1.0  2026-06-30   34.13       34.82  8.902960e-01   IWM  0.3962  1.3229     NaN  2.017616
17       SCO  2026-06-30 01:16:00   35.119999   35.130001   35.119999   35.130001       13.0  2026-06-30   34.13       34.82  8.615707e-01   IWM  0.3962  1.3229    0.15  2.017616
18       SCO  2026-06-30 01:18:00   35.139999   35.139999   35.139999   35.139999       10.0  2026-06-30   34.13       34.82  9.190103e-01   IWM  0.3962  1.3229    0.12  2.017616
19       SCO  2026-06-30 01:19:00   35.130001   35.130001   35.110001   35.110001       37.0  2026-06-30   34.13       34.82  8.902960e-01   IWM  0.3962  1.3229     NaN  2.017616
20       SCO  2026-06-30 01:20:00   35.099998   35.099998   35.099998   35.099998       60.0  2026-06-30   34.13       34.82  8.041312e-01   IWM  0.3962  1.3229     NaN  2.017616
21       SCO  2026-06-30 01:21:00   35.119999   35.119999   35.119999   35.119999       20.0  2026-06-30   34.13       34.82  8.615707e-01   IWM  0.3962  1.3229     NaN  2.017616
22       SCO  2026-06-30 01:26:00   35.090000   35.090000   35.090000   35.090000      150.0  2026-06-30   34.13       34.82  7.754169e-01   IWM  0.3962  1.3229    0.11  2.017616
23       SCO  2026-06-30 01:30:00   35.080002   35.180000   35.070000   35.180000      172.0  2026-06-30   34.13       34.82  7.467026e-01   IWM  0.3962  1.3229    0.09  2.017616
24       SCO  2026-06-30 01:31:00   35.160000   35.160000   35.160000   35.160000        2.0  2026-06-30   34.13       34.82  9.764499e-01   IWM  0.3962  1.3229     NaN  2.017616
25       SCO  2026-06-30 01:38:00   35.060001   35.060001   35.020000   35.020000       27.0  2026-06-30   34.13       34.82  6.892630e-01   IWM  0.3962  1.3229     NaN  2.017616
26       SCO  2026-06-30 01:40:00   35.040001   35.040001   35.029999   35.029999       20.0  2026-06-30   34.13       34.82  6.318234e-01   IWM  0.3962  1.3229     NaN  2.017616
27       SCO  2026-06-30 01:41:00   35.020000   35.020000   35.020000   35.020000        2.0  2026-06-30   34.13       34.82  5.743839e-01   IWM  0.3962  1.3229     NaN  2.017616
28       SCO  2026-06-30 01:42:00   35.040001   35.040001   35.020000   35.020000       35.0  2026-06-30   34.13       34.82  6.318234e-01   IWM  0.3962  1.3229     NaN  2.017616
29       SCO  2026-06-30 01:44:00   35.020000   35.020000   35.020000   35.020000        4.0  2026-06-30   34.13       34.82  5.743839e-01   IWM  0.3962  1.3229     NaN  2.017616
30       SCO  2026-06-30 01:45:00   35.009998   35.009998   35.000000   35.009998       25.0  2026-06-30   34.13       34.82  5.456586e-01   IWM  0.3962  1.3229     NaN  2.017616
31       SCO  2026-06-30 01:50:00   35.119999   35.119999   35.119999   35.119999       60.0  2026-06-30   34.13       34.82  8.615707e-01   IWM  0.3962  1.3229     NaN  2.017616
32       SCO  2026-06-30 01:53:00   35.119999   35.130001   35.119999   35.130001       17.0  2026-06-30   34.13       34.82  8.615707e-01   IWM  0.3962  1.3229     NaN  2.017616
33       SCO  2026-06-30 01:59:00   35.160000   35.160000   35.160000   35.160000       10.0  2026-06-30   34.13       34.82  9.764499e-01   IWM  0.3962  1.3229    0.11  2.017616
34       SCO  2026-06-30 02:01:00   35.220001   35.230000   35.220001   35.230000        6.0  2026-06-30   34.13       34.82  1.148769e+00   IWM  0.3962  1.3229     NaN  2.017616
35       SCO  2026-06-30 02:04:00   35.230000   35.259998   35.230000   35.250000      201.0  2026-06-30   34.13       34.82  1.177483e+00   IWM  0.3962  1.3229     NaN  2.017616
36       SCO  2026-06-30 02:05:00   35.240002   35.240002   35.240002   35.240002        1.0  2026-06-30   34.13       34.82  1.206208e+00   IWM  0.3962  1.3229     NaN  2.017616
37       SCO  2026-06-30 02:07:00   35.209999   35.209999   35.209999   35.209999       10.0  2026-06-30   34.13       34.82  1.120043e+00   IWM  0.3962  1.3229    0.11  2.017616
38       SCO  2026-06-30 02:08:00   35.200001   35.200001   35.200001   35.200001       10.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.3962  1.3229     NaN  2.017616
39       SCO  2026-06-30 02:12:00   35.200001   35.200001   35.200001   35.200001       40.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.3962  1.3229     NaN  2.017616
40       SCO  2026-06-30 02:13:00   35.240002   35.240002   35.240002   35.240002      102.0  2026-06-30   34.13       34.82  1.206208e+00   IWM  0.3962  1.3229     NaN  2.017616
41       SCO  2026-06-30 02:17:00   35.250000   35.259998   35.250000   35.259998      118.0  2026-06-30   34.13       34.82  1.234922e+00   IWM  0.3962  1.3229     NaN  2.017616
42       SCO  2026-06-30 02:19:00   35.270000   35.270000   35.270000   35.270000        1.0  2026-06-30   34.13       34.82  1.292362e+00   IWM  0.3962  1.3229     NaN  2.017616
43       SCO  2026-06-30 02:20:00   35.279999   35.279999   35.279999   35.279999        1.0  2026-06-30   34.13       34.82  1.321076e+00   IWM  0.3962  1.3229    0.06  2.017616
44       SCO  2026-06-30 02:21:00   35.299999   35.299999   35.299999   35.299999      155.0  2026-06-30   34.13       34.82  1.378516e+00   IWM  0.3962  1.3229     NaN  2.017616
45       SCO  2026-06-30 02:23:00   35.320000   35.360001   35.320000   35.360001     1061.0  2026-06-30   34.13       34.82  1.435955e+00   IWM  0.3962  1.3229    0.05  2.017616
46       SCO  2026-06-30 02:24:00   35.330002   35.330002   35.330002   35.330002     2903.0  2026-06-30   34.13       34.82  1.464681e+00   IWM  0.3962  1.3229     NaN  2.017616
47       SCO  2026-06-30 02:25:00   35.330002   35.330002   35.330002   35.330002       97.0  2026-06-30   34.13       34.82  1.464681e+00   IWM  0.3962  1.3229    0.03  2.017616
48       SCO  2026-06-30 02:28:00   35.299999   35.299999   35.299999   35.299999       10.0  2026-06-30   34.13       34.82  1.378516e+00   IWM  0.3962  1.3229     NaN  2.017616
49       SCO  2026-06-30 02:30:00   35.360001   35.360001   35.360001   35.360001        5.0  2026-06-30   34.13       34.82  1.550835e+00   IWM  0.3962  1.3229     NaN  2.017616
50       SCO  2026-06-30 02:33:00   35.259998   35.259998   35.240002   35.240002        5.0  2026-06-30   34.13       34.82  1.263637e+00   IWM  0.3962  1.3229     NaN  2.017616
51       SCO  2026-06-30 02:34:00   35.240002   35.240002   35.240002   35.240002      244.0  2026-06-30   34.13       34.82  1.206208e+00   IWM  0.3962  1.3229    0.02  2.017616
52       SCO  2026-06-30 02:38:00   35.320000   35.320000   35.320000   35.320000        3.0  2026-06-30   34.13       34.82  1.435955e+00   IWM  0.3962  1.3229    0.05  2.017616
53       SCO  2026-06-30 02:40:00   35.310001   35.310001   35.310001   35.310001      193.0  2026-06-30   34.13       34.82  1.407241e+00   IWM  0.3962  1.3229     NaN  2.017616
54       SCO  2026-06-30 02:42:00   35.299999   35.299999   35.299999   35.299999      235.0  2026-06-30   34.13       34.82  1.378516e+00   IWM  0.3962  1.3229     NaN  2.017616
55       SCO  2026-06-30 02:45:00   35.209999   35.209999   35.209999   35.209999      200.0  2026-06-30   34.13       34.82  1.120043e+00   IWM  0.3962  1.3229    0.02  2.017616
56       SCO  2026-06-30 02:48:00   35.200001   35.200001   35.189999   35.189999     1601.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.3962  1.3229     NaN  2.017616
57       SCO  2026-06-30 02:51:00   35.110001   35.110001   35.110001   35.110001       10.0  2026-06-30   34.13       34.82  8.328564e-01   IWM  0.3962  1.3229     NaN  2.017616
58       SCO  2026-06-30 02:52:00   35.110001   35.110001   35.110001   35.110001        1.0  2026-06-30   34.13       34.82  8.328564e-01   IWM  0.3962  1.3229    0.07  2.017616
59       SCO  2026-06-30 02:54:00   35.110001   35.110001   35.110001   35.110001      175.0  2026-06-30   34.13       34.82  8.328564e-01   IWM  0.3962  1.3229     NaN  2.017616
60       SCO  2026-06-30 03:00:00   35.049999   35.049999   35.040001   35.040001       69.0  2026-06-30   34.13       34.82  6.605377e-01   IWM  0.3962  1.3229     NaN  2.017616
61       SCO  2026-06-30 03:06:00   35.040001   35.040001   35.040001   35.040001        8.0  2026-06-30   34.13       34.82  6.318234e-01   IWM  0.3962  1.3229    0.17  2.017616
62       SCO  2026-06-30 03:12:00   35.040001   35.040001   35.040001   35.040001       70.0  2026-06-30   34.13       34.82  6.318234e-01   IWM  0.3962  1.3229     NaN  2.017616
63       SCO  2026-06-30 03:13:00   35.000000   35.000000   34.980000   34.980000       20.0  2026-06-30   34.13       34.82  5.169443e-01   IWM  0.3962  1.3229     NaN  2.017616
64       SCO  2026-06-30 03:15:00   34.980000   34.980000   34.980000   34.980000      160.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.3962  1.3229     NaN  2.017616
65       SCO  2026-06-30 03:16:00   34.980000   34.980000   34.980000   34.980000        2.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.3962  1.3229     NaN  2.017616
66       SCO  2026-06-30 03:22:00   34.980000   34.980000   34.950001   34.950001      215.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.3962  1.3229     NaN  2.017616
67       SCO  2026-06-30 03:26:00   34.980000   34.980000   34.980000   34.980000      200.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.3962  1.3229     NaN  2.017616
68       SCO  2026-06-30 03:31:00   34.939999   34.939999   34.900002   34.900002       27.0  2026-06-30   34.13       34.82  3.446256e-01   IWM  0.3962  1.3229     NaN  2.017616
69       SCO  2026-06-30 03:40:00   34.980000   34.980000   34.980000   34.980000        1.0  2026-06-30   34.13       34.82  4.595047e-01   IWM  0.3962  1.3229     NaN  2.017616
70       SCO  2026-06-30 03:45:00   34.959999   34.970001   34.959999   34.970001     1234.0  2026-06-30   34.13       34.82  4.020651e-01   IWM  0.3962  1.3229     NaN  2.017616
71       SCO  2026-06-30 03:56:00   35.009998   35.060001   35.009998   35.060001     4327.0  2026-06-30   34.13       34.82  5.456586e-01   IWM  0.3962  1.3229    0.02  2.017616
72       SCO  2026-06-30 04:00:00   35.060001   35.189999   35.009998   35.009998     2013.0  2026-06-30   34.13       34.82  6.892630e-01   IWM  0.3962  1.3229    0.04  2.017616
73       SCO  2026-06-30 04:02:00   35.009998   35.200001   35.009998   35.189999     1586.0  2026-06-30   34.13       34.82  5.456586e-01   IWM  0.3962  1.3229    0.00  2.017616
74       SCO  2026-06-30 04:03:00   35.200001   35.360001   34.959999   34.980000     8144.0  2026-06-30   34.13       34.82  1.091329e+00   IWM  0.3962  1.3229    0.15  2.017616
75       SCO  2026-06-30 04:04:00   35.060001   35.060001   34.970001   35.009998     4659.0  2026-06-30   34.13       34.82  6.892630e-01   IWM  0.3962  1.3229    0.02  2.017616
76       SCO  2026-06-30 04:12:00   34.880001   34.880001   34.880001   34.880001      200.0  2026-06-30   34.13       34.82  1.723178e-01   IWM  0.3962  1.3229    0.03  2.017616
77       SCO  2026-06-30 04:14:00   34.730000   34.740002   34.700001   34.700001     1020.0  2026-06-30   34.13       34.82 -2.584735e-01   IWM  0.3962  1.3229    0.02  2.017616
78       SCO  2026-06-30 04:19:00   34.732601   34.732601   34.732601   34.732601      471.0  2026-06-30   34.13       34.82 -2.510018e-01   IWM  0.3962  1.3229   -0.00  2.017616
79       SCO  2026-06-30 04:20:00   34.770000   34.770000   34.770000   34.770000      160.0  2026-06-30   34.13       34.82 -1.435943e-01   IWM  0.3962  1.3229    0.01  2.017616
80       SCO  2026-06-30 04:21:00   34.820000   34.820000   34.820000   34.820000      364.0  2026-06-30   34.13       34.82 -8.764382e-07   IWM  0.3962  1.3229    0.02  2.017616
81       SCO  2026-06-30 04:28:00   34.770000   34.799999   34.770000   34.799999      260.0  2026-06-30   34.13       34.82 -1.435943e-01   IWM  0.3962  1.3229    0.05  2.017616
82       SCO  2026-06-30 04:29:00   34.779999   34.779999   34.770000   34.770000      260.0  2026-06-30   34.13       34.82 -1.148800e-01   IWM  0.3962  1.3229    0.05  2.017616
83       SCO  2026-06-30 04:32:00   34.700001   34.700001   34.700001   34.700001      100.0  2026-06-30   34.13       34.82 -3.446273e-01   IWM  0.3962  1.3229     NaN  2.017616
84       SCO  2026-06-30 04:34:00   34.599998   34.639999   34.599998   34.639999      252.0  2026-06-30   34.13       34.82 -6.318252e-01   IWM  0.3962  1.3229     NaN  2.017616
85       SCO  2026-06-30 04:39:00   34.630001   34.630001   34.630001   34.630001      160.0  2026-06-30   34.13       34.82 -5.456603e-01   IWM  0.3962  1.3229   -0.11  2.017616
86       SCO  2026-06-30 04:40:00   34.660000   34.669998   34.660000   34.669998      640.0  2026-06-30   34.13       34.82 -4.595065e-01   IWM  0.3962  1.3229   -0.13  2.017616
87       SCO  2026-06-30 04:42:00   34.599998   34.599998   34.599998   34.599998      200.0  2026-06-30   34.13       34.82 -6.318252e-01   IWM  0.3962  1.3229   -0.13  2.017616
88       SCO  2026-06-30 04:46:00   34.593899   34.593899   34.593899   34.593899      150.0  2026-06-30   34.13       34.82 -6.493430e-01   IWM  0.3962  1.3229   -0.10  2.017616
89       SCO  2026-06-30 04:47:00   34.680000   34.680000   34.669998   34.669998      530.0  2026-06-30   34.13       34.82 -4.020669e-01   IWM  0.3962  1.3229   -0.10  2.017616
90       SCO  2026-06-30 04:51:00   34.639999   34.639999   34.639999   34.639999      200.0  2026-06-30   34.13       34.82 -5.169460e-01   IWM  0.3962  1.3229     NaN  2.017616
91       SCO  2026-06-30 04:56:00   34.830002   34.939999   34.830002   34.939999      300.0  2026-06-30   34.13       34.82  2.872439e-02   IWM  0.3962  1.3229   -0.03  2.017616
92       SCO  2026-06-30 04:57:00   34.869999   34.869999   34.869999   34.869999      250.0  2026-06-30   34.13       34.82  1.435926e-01   IWM  0.3962  1.3229     NaN  2.017616
93       SCO  2026-06-30 04:59:00   34.869999   34.869999   34.869999   34.869999      100.0  2026-06-30   34.13       34.82  1.435926e-01   IWM  0.3962  1.3229   -0.02  2.017616
94       SCO  2026-06-30 05:06:00   34.860001   34.860001   34.840000   34.840000      500.0  2026-06-30   34.13       34.82  1.148783e-01   IWM  0.3962  1.3229    0.01  2.017616
95       SCO  2026-06-30 05:24:00   34.660000   34.660000   34.660000   34.660000     6000.0  2026-06-30   34.13       34.82 -4.595065e-01   IWM  0.3962  1.3229     NaN  2.017616
96       SCO  2026-06-30 05:25:00   34.759998   34.759998   34.759998   34.759998      320.0  2026-06-30   34.13       34.82 -1.723196e-01   IWM  0.3962  1.3229    0.05  2.017616
97       SCO  2026-06-30 05:27:00   34.830002   34.830002   34.830002   34.830002      808.0  2026-06-30   34.13       34.82  2.872439e-02   IWM  0.3962  1.3229    0.04  2.017616
98       SCO  2026-06-30 05:30:00   34.680000   34.680000   34.590000   34.619999     1000.0  2026-06-30   34.13       34.82 -4.020669e-01   IWM  0.3962  1.3229     NaN  2.017616
99       SCO  2026-06-30 05:31:00   34.599998   34.599998   34.549999   34.549999     1298.0  2026-06-30   34.13       34.82 -6.318252e-01   IWM  0.3962  1.3229   -0.02  2.017616
100      SCO  2026-06-30 05:34:00   34.609402   34.609402   34.560001   34.560001     1513.0  2026-06-30   34.13       34.82 -6.048199e-01   IWM  0.3962  1.3229     NaN  2.017616
101      SCO  2026-06-30 05:36:00   34.529999   34.529999   34.529999   34.529999      160.0  2026-06-30   34.13       34.82 -8.328582e-01   IWM  0.3962  1.3229   -0.02  2.017616
102      SCO  2026-06-30 05:44:00   34.560001   34.560001   34.540001   34.540001      260.0  2026-06-30   34.13       34.82 -7.466934e-01   IWM  0.3962  1.3229    0.07  2.017616
103      SCO  2026-06-30 05:50:00   34.549999   34.549999   34.549999   34.549999      160.0  2026-06-30   34.13       34.82 -7.754186e-01   IWM  0.3962  1.3229     NaN  2.017616
104      SCO  2026-06-30 05:54:00   34.560001   34.560001   34.560001   34.560001      100.0  2026-06-30   34.13       34.82 -7.466934e-01   IWM  0.3962  1.3229    0.13  2.017616
105      SCO  2026-06-30 05:57:00   34.500000   34.500000   34.490002   34.490002     1508.0  2026-06-30   34.13       34.82 -9.190121e-01   IWM  0.3962  1.3229    0.13  2.017616
106      SCO  2026-06-30 05:58:00   34.459999   34.459999   34.459999   34.459999      500.0  2026-06-30   34.13       34.82 -1.033891e+00   IWM  0.3962  1.3229     NaN  2.017616
107      SCO  2026-06-30 06:01:00   34.389999   34.389999   34.389999   34.389999      100.0  2026-06-30   34.13       34.82 -1.234924e+00   IWM  0.3962  1.3229    0.12  2.017616
108      SCO  2026-06-30 06:02:00   34.380001   34.384701   34.380001   34.384701      530.0  2026-06-30   34.13       34.82 -1.263639e+00   IWM  0.3962  1.3229    0.11  2.017616
109      SCO  2026-06-30 06:03:00   34.419998   34.419998   34.419998   34.419998      160.0  2026-06-30   34.13       34.82 -1.148770e+00   IWM  0.3962  1.3229    0.11  2.017616

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,SCO,2026-06-30 00:23:00,34.900002,34.900002,34.900002,34.900002,8.0,2026-06-30,34.13,34.82,0.229757,IWM,0.3962,1.3229,NaN,2.017616
1,SCO,2026-06-30 00:26:00,34.939999,34.939999,34.939999,34.939999,1.0,2026-06-30,34.13,34.82,0.344626,IWM,0.3962,1.3229,NaN,2.017616
2,SCO,2026-06-30 00:28:00,35.000000,35.009998,35.000000,35.009998,205.0,2026-06-30,34.13,34.82,0.516944,IWM,0.3962,1.3229,NaN,2.017616
3,SCO,2026-06-30 00:31:00,35.009998,35.009998,35.009998,35.009998,12.0,2026-06-30,34.13,34.82,0.545659,IWM,0.3962,1.3229,NaN,2.017616
4,SCO,2026-06-30 00:34:00,34.990002,34.990002,34.990002,34.990002,11.0,2026-06-30,34.13,34.82,0.488230,IWM,0.3962,1.3229,NaN,2.017616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,SHIM,2026-06-30 15:33:00,4.615000,4.630000,4.600000,4.630000,1049.0,2026-06-30,4.31,4.29,7.575752,IWM,0.5777,0.7918,0.64,1.025722
21146,SHIM,2026-06-30 15:35:00,4.600000,4.600000,4.600000,4.600000,400.0,2026-06-30,4.31,4.29,7.226105,IWM,0.5777,0.7918,0.62,1.025722
21147,SHIM,2026-06-30 15:37:00,4.615000,4.615000,4.615000,4.615000,100.0,2026-06-30,4.31,4.29,7.575752,IWM,0.5777,0.7918,0.58,1.025722
21148,SHIM,2026-06-30 15:39:00,4.615000,4.615000,4.600000,4.600000,300.0,2026-06-30,4.31,4.29,7.575752,IWM,0.5777,0.7918,0.55,1.025722
21149,SHIM,2026-06-30 15:40:00,4.600000,4.610000,4.600000,4.610000,1100.0,2026-06-30,4.31,4.29,7.226105,IWM,0.5777,0.7918,0.55,1.025722

In [48]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional, List

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
    import pyarrow.compute as pc
except Exception:
    pa = pq = ds = pc = None


def _as_f64(col):
    """ChunkedArray -> float64 без походу в pandas (fallback лише для нечислових типів)."""
    if pa.types.is_floating(col.type) or pa.types.is_integer(col.type):
        return col.cast(pa.float64()) if col.type != pa.float64() else col
    if pa.types.is_decimal(col.type):
        return col.cast(pa.float64())
    return pa.chunked_array([pa.array(
        pd.to_numeric(col.to_pandas(), errors="coerce").to_numpy(dtype="float64"))])


def _round_like_numpy(col, ndigits):
    """np.round над Arrow-колонкою + NaN -> null (як робив pa.Table.from_pandas)."""
    if len(col) == 0:
        return col
    v = col.to_numpy(zero_copy_only=False)   # може бути read-only zero-copy view
    if ndigits is not None:
        v = np.round(v, int(ndigits))
    return pa.array(v, from_pandas=True)


def _add_tp_deviation_devsig(table, *, round_tp_dev=2, round_devsig=6, dt_as_timestamp=False):
    """t_p / deviation / dev_sig як арифметика Arrow над колонками таблиці.

    Раніше кожен батч ходив у pandas і назад (batch.to_pandas() +
    pa.Table.from_pandas()). Для рядкових колонок ticker/dt/date/bench це означало
    матеріалізацію мільйонів python-об'єктів str на кожному батчі й повне
    перезбирання Arrow-масивів — найдорожча частина того циклу. Тут таблиця
    лишається в Arrow від читання до запису.
    """
    names = {n.strip().lower(): n for n in table.column_names}
    stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
    bench_col = names.get("bench%")
    beta_col = names.get("beta")
    sigma_col = names.get("sigma")

    need = {
        "stack%/pct_vs_prev_close": stack_col,
        "bench%": bench_col,
        "beta": beta_col,
        "sigma": sigma_col,
    }
    missing = [k for k, v in need.items() if v is None]
    if missing:
        raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

    drop = [c for c in ("t_p", "deviation", "dev_sig") if c in table.column_names]
    if drop:
        table = table.drop_columns(drop) if hasattr(table, "drop_columns") else table.drop(drop)

    stack = _as_f64(table[stack_col])
    beta = _as_f64(table[beta_col])
    bench = _as_f64(table[bench_col])
    sigma = _as_f64(table[sigma_col])

    tp = pc.multiply(stack, beta)
    dev = pc.subtract(tp, bench)
    denom = pc.if_else(pc.equal(sigma, 0), pa.scalar(None, pa.float64()), sigma)  # sigma 0 -> NaN
    dsg = pc.divide(dev, denom)

    # Округлення саме через np.round, а не pc.round: на значеннях, які вже округлені
    # вище по пайплайну (Stack% до 2 знаків, beta до 4), добуток лягає впритул до
    # межі .005, і pc.round подекуди дає результат на 1 ULP інший за np.round.
    # np.round тут ще й трохи швидший, а pa.array(..., from_pandas=True) відтворює
    # ту саму семантику NaN -> null, що давав старий pa.Table.from_pandas().
    tp = _round_like_numpy(tp, round_tp_dev)
    dev = _round_like_numpy(dev, round_tp_dev)
    dsg = _round_like_numpy(dsg, round_devsig)

    if dt_as_timestamp and "dt" in table.column_names and pa.types.is_string(table["dt"].type):
        i = table.column_names.index("dt")
        table = table.set_column(i, "dt", pc.strptime(table["dt"], format="%Y-%m-%d %H:%M:%S",
                                                      unit="ns", error_is_null=True))

    return (table.append_column("t_p", tp)
                 .append_column("deviation", dev)
                 .append_column("dev_sig", dsg))


def _sort_keys(schema_names):
    keys = [("ticker", "ascending")]
    if "date" in schema_names:
        keys.append(("date", "ascending"))
    if "dt" in schema_names:
        keys.append(("dt", "ascending"))
    return keys


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # batch_rows для потокового режиму / бакетування
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,
    max_rows_in_memory: int = 20_000_000,
    dt_as_timestamp: bool = False,
    row_group_size: int = 2_000_000,
) -> str:
    """
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.

    Якщо sort_final_by_ticker=True, output_path фізично відсортований:
    ticker A→Z, всередині тикера date,dt.

    Що змінилось проти попередньої версії:
      1. Обчислення і сортування — ОДИН прохід. Раніше спершу писався повний
         tmp_unsorted, потім він читався назад і переписувався відсортованим:
         3 читання + 3 записи всього файла. Тепер 1 читання + 1 запис
         (або 2+2, якщо файл не влазить у пам'ять і потрібні бакети).
      2. Уся арифметика в Arrow — без batch.to_pandas()/pa.Table.from_pandas()
         на кожному батчі (це матеріалізувало рядкові колонки як python-об'єкти).
      3. Сортування ПЕРЕД додаванням t_p/deviation/dev_sig — take() переставляє
         на 3 float64-колонки менше.
      4. Бакетування по тикерах — через pc.index_in замість pandas .map по рядках.
      5. row_group_size=2M замість дефолтного 1M: менше row-груп → швидший запис,
         трохи менший файл, і стратегії-споживачі (вони читають
         iter_batches(batch_size=1_000_000)) теж читають його швидше.
    """
    if pq is None or pa is None or ds is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet, pyarrow.dataset).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    total_rows = dataset.count_rows()

    tmp_out = output_path + f".tmp_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    def _finish(rows, mode):
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_out, output_path)
        print(f"✅ DONE ({mode}): {rows:,} rows → {output_path} | "
              f"total_time={time.time()-t0:,.1f}s", flush=True)
        return output_path

    # ---------- 1) без сортування: чистий стрім, один прохід ----------
    if not sort_final_by_ticker:
        print(f"▶ START (stream): {input_path} → {output_path} | "
              f"rows={total_rows:,} batch={chunksize:,}", flush=True)
        writer = None
        written = 0
        try:
            for bi, rb in enumerate(dataset.to_batches(batch_size=chunksize), 1):
                if rb.num_rows == 0:
                    continue
                tbl = _add_tp_deviation_devsig(
                    pa.Table.from_batches([rb]), round_tp_dev=round_tp_dev,
                    round_devsig=round_devsig, dt_as_timestamp=dt_as_timestamp)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl, row_group_size=row_group_size)
                written += tbl.num_rows
                if bi % 5 == 0:
                    print(f"[batch {bi:>4}] rows={written:,}  "
                          f"elapsed={time.time()-t0:,.1f}s", flush=True)
        finally:
            if writer is not None:
                writer.close()
        return _finish(written, "stream")

    keys = _sort_keys(schema_names)
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    # ---------- 2) влазить у пам'ять: читання → сорт → рахунок → запис ----------
    if total_rows <= max_rows_in_memory:
        print(f"▶ START (in-memory sort): {input_path} → {output_path} | "
              f"rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        table = _add_tp_deviation_devsig(
            table, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
            dt_as_timestamp=dt_as_timestamp)
        pq.write_table(table, tmp_out, compression=compression,
                       row_group_size=row_group_size)
        written = table.num_rows
        del table
        gc.collect()
        return _finish(written, "in-memory sort")

    # ---------- 3) не влазить: один прохід у бакети, далі сорт кожного ----------
    n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
    tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
    tickers = sorted(str(t) for t in tickers if t is not None)
    # суміжні діапазони тикерів → порядок бакетів = порядок тикерів
    edges = np.array_split(np.arange(len(tickers)), n_buckets)
    rank_to_bucket = np.zeros(len(tickers), dtype="int32")
    for b, idxs in enumerate(edges):
        rank_to_bucket[idxs] = b
    ticker_set = pa.array(tickers, type=pa.string())
    rank_to_bucket_arr = pa.array(rank_to_bucket)

    print(f"▶ START (bucketed sort): {input_path} → {output_path} | rows={total_rows:,} "
          f"tickers={len(tickers):,} buckets={n_buckets}", flush=True)

    bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
    bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
    try:
        for rb in dataset.to_batches(batch_size=chunksize):
            if rb.num_rows == 0:
                continue
            tbl = pa.Table.from_batches([rb])
            # ранг тикера в відсортованому списку → номер бакета, повністю в Arrow
            ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
            bidx = pc.take(rank_to_bucket_arr, ranks)
            for b in range(n_buckets):
                mask = pc.equal(bidx, b)
                if not pc.any(mask).as_py():
                    continue
                part = tbl.filter(mask)
                if part.num_rows == 0:
                    continue
                if bwriters[b] is None:
                    bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                   compression=compression)
                bwriters[b].write_table(part)
    finally:
        for w in bwriters:
            if w is not None:
                w.close()

    writer = None
    written = 0
    try:
        for b, bp in enumerate(bucket_paths):
            if not os.path.exists(bp):
                continue
            tbl = pq.read_table(bp).sort_by(keys)
            tbl = _add_tp_deviation_devsig(
                tbl, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
                dt_as_timestamp=dt_as_timestamp)
            if writer is None:
                writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
            writer.write_table(tbl, row_group_size=row_group_size)
            written += tbl.num_rows
            del tbl
            gc.collect()
            print(f"  bucket {b+1}/{n_buckets}  written={written:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)
    finally:
        if writer is not None:
            writer.close()
        for bp in bucket_paths:
            if os.path.exists(bp):
                os.remove(bp)

    return _finish(written, "bucketed sort")


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    max_rows_in_memory: int = 20_000_000,
    log_every: int = 200,            # лишено для сумісності виклику
    roundtrip_pandas: bool = True,   # лишено для сумісності виклику
):
    """Лише сортування parquet: ticker A→Z, всередині тикера (date, dt).

    Обчислення t_p/deviation/dev_sig тепер робить сам recompute_tp_deviation_devsig
    у тому ж проході, тож окремо ця функція потрібна лише якщо треба відсортувати
    вже готовий файл.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")
    keys = _sort_keys(schema_names)

    total_rows = dataset.count_rows()
    t0 = time.time()
    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    if total_rows <= max_rows_in_memory:
        print(f"▶ SORT (in-memory): rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        pq.write_table(table, tmp_out, compression=compression)
        written = table.num_rows
        del table
        gc.collect()
    else:
        n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
        tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
        tickers = sorted(str(t) for t in tickers if t is not None)
        rank_to_bucket = np.zeros(len(tickers), dtype="int32")
        for b, idxs in enumerate(np.array_split(np.arange(len(tickers)), n_buckets)):
            rank_to_bucket[idxs] = b
        ticker_set = pa.array(tickers, type=pa.string())
        rank_to_bucket_arr = pa.array(rank_to_bucket)
        print(f"▶ SORT (bucketed): rows={total_rows:,} tickers={len(tickers):,} "
              f"buckets={n_buckets}", flush=True)

        bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
        bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
        try:
            for rb in dataset.to_batches():
                if rb.num_rows == 0:
                    continue
                tbl = pa.Table.from_batches([rb])
                ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
                bidx = pc.take(rank_to_bucket_arr, ranks)
                for b in range(n_buckets):
                    mask = pc.equal(bidx, b)
                    if not pc.any(mask).as_py():
                        continue
                    part = tbl.filter(mask)
                    if part.num_rows == 0:
                        continue
                    if bwriters[b] is None:
                        bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                       compression=compression)
                    bwriters[b].write_table(part)
        finally:
            for w in bwriters:
                if w is not None:
                    w.close()

        writer = None
        written = 0
        try:
            for b, bp in enumerate(bucket_paths):
                if not os.path.exists(bp):
                    continue
                tbl = pq.read_table(bp).sort_by(keys)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl)
                written += tbl.num_rows
                del tbl
                gc.collect()
        finally:
            if writer is not None:
                writer.close()
            for bp in bucket_paths:
                if os.path.exists(bp):
                    os.remove(bp)

    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)
    print(f"✅ SORT DONE: {written:,} rows → {output_path} | time={time.time()-t0:,.1f}s", flush=True)
    return output_path

In [49]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (bucketed sort): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | rows=109,397,168 tickers=7,878 buckets=6

  bucket 1/6  written=18,391,215  elapsed=89.3s

  bucket 2/6  written=36,224,625  elapsed=108.1s

  bucket 3/6  written=53,433,051  elapsed=126.5s

  bucket 4/6  written=71,903,054  elapsed=146.6s

  bucket 5/6  written=91,249,224  elapsed=167.8s

  bucket 6/6  written=109,397,168  elapsed=187.0s

✅ DONE (bucketed sort): 109,397,168 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=187.1s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'