In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2026-07-24 00:00:00
end   = 2026-10-24 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2026-07-24
end_date_str   = 2026-10-24

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker      value
0      A   69713.24
1     AA  977030.32
2    AAA       0.00
3   AAAA       0.00
4   AAAB       0.00
Рядків: 13636

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,market_cap',
    'active': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
# market_cap ніде далі не використовується (єдина згадка — у 'fields' вище),
# тому він не має відсіювати тикери: рядок викидаємо лише якщо бракує ticker або lvl3
tickers_df = tickers_df.dropna(subset=["ticker", "lvl3"])

# --- крок 3: додаємо потрібні колонки у df_filtered
TICKERS = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(TICKERS):,} рядків")
TICKERS.head()

Після фільтрації залишилось: 7,050 рядків

  ticker      value                         lvl3  market_cap
0      A   69713.24  Medical Equipment & Devices     48793.0
1     AA  977030.32              Metals & Mining     10004.0
2   AAAU  325294.03                          NaN         NaN
3   AACG      17.22                     Software        31.0
4   AADX   57701.33          Aerospace & Defense      1723.0

In [7]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [8]:
unique_lvl2 = get_unique_lvl2(TICKERS)
unique_lvl2

🔹 Знайдено 60 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Investment Management',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Other Financial Services',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [9]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "IBIT"],
    "Banking": ["XLF", "KRE", "IBIT"],
    "Institutional Financial Svcs": ["XLF", "IBIT"],
    "Insurance": ["XLF"],
    "Specialty Finance": ["XLF", "IBIT"],

    # --- Tech / Internet / Growth ---
    "Software": ["IGV"],
    "IT Services": ["QQQ"],
    "Semiconductors": ["SOXX", "DRAM"],
    "Technology Hardware": ["QQQ", "SOXX"],
    "Internet Media & Services": ["QQQ", "KWEB", "FXI"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "XRT"],
    "Cable & Satellite": ["SPY", "IWM"],
    "Telecommunications": ["QQQ"],
    "Publishing & Broadcasting": ["QQQ"],
    "Entertainment Content": ["QQQ", "ARKK"],
    "Advertising & Marketing": ["QQQ"],

    # --- Industrials ---
    "Aerospace & Defense": ["NASA", "ITA"],
    "Diversified Industrials": ["XLB", "IWM"],
    "Industrial Intermediate Prod": ["XLB", "IWM"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["XLB", "IWM"],
    "Machinery": ["XLB", "IWM"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["XLB", "IWM"],
    "Electrical Equipment": ["QQQ", "XLB"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XOP", "XLE", "UNG"],
    "Oil & Gas Supply Chain": ["XOP", "XLE", "UNG"],
    "Elec & Gas Marketing & Trading": ["XLU", "XLE"],
    "Electric Utilities": ["XLU"],
    "Gas & Water Utilities": ["XLU"],
    "Renewable Energy": ["XLE", "ARKK"],
    "Chemicals": ["XLB", "URA"],
    "Metals & Mining": ["GDX", "FCX", "COPX", "URA", "SLV"],
    "Steel": ["XLB", "GDX"],
    "Construction Materials": ["XLB", "IWM"],
    "Forestry, Paper & Wood Products": ["XLB", "IWM"],

    # --- Health Care ---
    "Biotech & Pharma": ["XBI"],
    "Medical Equipment & Devices": ["XLV"],
    "Health Care Facilities & Svcs": ["XLV", "IWM"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["XLP"],
    "Beverages": ["XLP"],
    "Household Products": ["XLP"],
    "Tobacco & Cannabis": ["XLP"],
    "Retail - Consumer Staples": ["XLP", "XRT"],
    "Wholesale - Consumer Staples": ["XLP"],

    "Retail - Discretionary": ["XRT", "IWM", "SPY"],
    "Wholesale - Discretionary": ["XRT", "IWM"],
    "Consumer Services": ["IWM", "SPY"],
    "Leisure Facilities & Services": ["IWM", "SPY"],
    "Leisure Products": ["XRT", "IWM"],
    "Apparel & Textile Products": ["XRT", "IWM"],
    "Automotive": ["QQQ", "IWM"],
    "Home & Office Products": ["XRT", "IWM"],
    "Home Construction": ["XLB", "IWM"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [10]:
# ------------------------------------------------

In [11]:
import numpy as np
import pandas as pd


def calc_corr_beta_from_joined_gaps(df_pair: pd.DataFrame, x_col: str = "gap_x", y_col: str = "gap_y"):
    """
    Local corr/beta calculation without /calculations/corr_beta API.

    corr = Pearson(x, y)
    beta = cov(x, y) / var(y)
    """
    d = df_pair[[x_col, y_col]].copy()
    d[x_col] = pd.to_numeric(d[x_col], errors="coerce")
    d[y_col] = pd.to_numeric(d[y_col], errors="coerce")
    d = d.dropna()

    n = len(d)
    if n < 2:
        return np.nan, np.nan, n

    var_y = float(d[y_col].var(ddof=1))
    corr = float(d[x_col].corr(d[y_col]))

    if np.isnan(var_y) or var_y == 0:
        return corr, np.nan, n

    cov_xy = float(d[[x_col, y_col]].cov(ddof=1).iloc[0, 1])
    beta = cov_xy / var_y
    return corr, beta, n


def corr_beta_best_match_from_gaps(
    stock_gap_df: pd.DataFrame,
    etf_gap_df: pd.DataFrame,
    x_tickers,
    y_tickers,
    *,
    min_overlap: int = 20,
    output_path: str = None,
):
    """
    Pick best Y per X using local gaps.

    stock_gap_df: ['ticker','date','gap']
    etf_gap_df:   ['ticker','date','gap']
    """
    sx = stock_gap_df.copy()
    sy = etf_gap_df.copy()

    for df in (sx, sy):
        if not {"ticker", "date", "gap"}.issubset(df.columns):
            raise KeyError("Expected columns ['ticker','date','gap'] in gap data")
        df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.strftime("%Y-%m-%d")
        df["gap"] = pd.to_numeric(df["gap"], errors="coerce")

    s_map = {t: g[["date", "gap"]].copy() for t, g in sx.groupby("ticker")}
    e_map = {t: g[["date", "gap"]].copy() for t, g in sy.groupby("ticker")}

    rows_all = []
    rows_best = []

    for x in [str(v).upper() for v in x_tickers]:
        g_x = s_map.get(x)
        if g_x is None or g_x.empty:
            continue

        best = None
        for y in [str(v).upper() for v in y_tickers]:
            g_y = e_map.get(y)
            if g_y is None or g_y.empty:
                continue

            m = g_x.merge(g_y, on="date", how="inner", suffixes=("_x", "_y")).dropna()
            corr, beta, n = calc_corr_beta_from_joined_gaps(m, x_col="gap_x", y_col="gap_y")
            if n < int(min_overlap) or pd.isna(corr):
                continue

            row = {
                "x_ticker": x,
                "y_ticker": y,
                "corr": corr,
                "beta": beta,
                "n_overlap": n,
            }
            rows_all.append(row)
            if best is None or row["corr"] > best["corr"]:
                best = row

        if best is not None:
            rows_best.append({
                "x_ticker": best["x_ticker"],
                "best_y_ticker": best["y_ticker"],
                "best_corr": best["corr"],
                "beta_with_best": best["beta"],
                "n_overlap": best["n_overlap"],
            })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "n_overlap"])

    if output_path:
        df_pairs.to_csv(output_path, index=False)

    return df_all, df_pairs

In [12]:
# Кеш сирого фетчу. /daily/gaps і /reports тягнулись ДВІЧІ за прогін — тут і в
# комірці 42 — тобто ~14 500 зайвих запитів, і саме вони й провокували 429.
# Складаємо результат ДО відкидання викидів: комірка 42 рахує sigma на СИРИХ
# гепах, і підстановка вже обрізаних занизила б її.
CRACEN_FETCH_CACHE = {}


def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
    start_date=None,
    end_date=None,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
    max_workers_net=8,        # 64 потоки без пауз давали суцільні 429
    max_fail_ratio=0.15,      # 4.4% остаточних відмов виміряно як НОРМУ для цього
                              # API навіть з retry; бар упритул до норми валив би
                              # прогін через раз. Ловить справжню відмову, не шум.
):
    import random
    import time
    import numpy as np
    import pandas as pd
    from concurrent.futures import ThreadPoolExecutor

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]
    if start_date is None:
        start_date = globals().get("start_date_str")
    if end_date is None:
        end_date = globals().get("end_date_str")
    if not start_date or not end_date:
        raise ValueError("Provide start_date/end_date or define start_date_str/end_date_str")
    if sector_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{sector_col}' column")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{ticker_col}' column")

    s_date, e_date = str(start_date)[:10], str(end_date)[:10]

    def _pick_col(df, candidates):
        cols_l = {c.lower().strip(): c for c in df.columns}
        return next((cols_l[c.lower()] for c in candidates if c.lower() in cols_l), None)

    _fails = {"gaps": 0, "reports": 0}

    def _request_with_retry(endpoint, params, *, max_retries=6, backoff=0.5):
        """Повторює запит при 429/мережевих збоях з наростаючою паузою.
        Той самий підхід, що в /intraday/v3. Вичерпавши спроби — кидає
        останній виняток, який ловить виклик вище."""
        for attempt in range(max_retries + 1):
            try:
                return DatumApi.data_request(endpoint, params)
            except Exception:
                if attempt == max_retries:
                    raise
                time.sleep(backoff * (2 ** attempt) * (0.9 + 0.2 * random.random()))

    def _fetch_gap(t):
        try:
            dfg = _request_with_retry("/daily/gaps", {
                "ticker": t, "start_date": s_date, "end_date": e_date, "format": "json_records",
            })
            if dfg is None or dfg.empty:
                return None
            dcol = _pick_col(dfg, ["date", "move_date", "dt", "datetime", "day"])
            if dcol is None or "gap" not in dfg.columns:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(dfg[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
                "gap": pd.to_numeric(dfg["gap"], errors="coerce"),
            }).dropna()
            return out if not out.empty else None
        except Exception as ex:
            _fails["gaps"] += 1
            print(f"WARN gaps fail {t}: {ex}")
            return None

    def _fetch_report(t):
        try:
            rep = _request_with_retry("/reports", {
                "ticker": t, "start_move_date": s_date, "end_move_date": e_date,
            })
            if rep is None or rep.empty:
                return None
            dcol = _pick_col(rep, ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"])
            if dcol is None:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(rep[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
            }).dropna().sort_values("date").tail(int(last_n_reports))
            return out if not out.empty else None
        except Exception as ex:
            _fails["reports"] += 1
            print(f"WARN reports fail {t}: {ex}")
            return None

    # ── prepare ──────────────────────────────────────────────────────────────
    df_clean = tickers_df[[ticker_col, sector_col]].drop_duplicates().copy()
    df_clean[ticker_col] = df_clean[ticker_col].astype(str).str.strip().str.upper()
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)

    stocks = sorted(df_clean[ticker_col].dropna().unique())
    etf_candidates = set(fallback_etfs)
    for sec in df_clean[sector_col].unique():
        etf_candidates.update(sector_to_etf.get(sec, fallback_etfs) or fallback_etfs)
    etf_candidates = sorted(str(x).upper() for x in etf_candidates)

    print(f"START gaps: stocks={len(stocks)} etfs={len(etf_candidates)} window={s_date}..{e_date}")

    # ── parallel fetch: all gaps + reports in one pool ────────────────────────
    all_gap_tickers = sorted(set(stocks) | set(etf_candidates))
    with ThreadPoolExecutor(max_workers=min(max_workers_net,
                                            len(all_gap_tickers) + len(stocks))) as ex:
        gap_futs  = {t: ex.submit(_fetch_gap,    t) for t in all_gap_tickers}
        rep_futs  = {t: ex.submit(_fetch_report, t) for t in stocks}

    gap_res = {t: f.result() for t, f in gap_futs.items()}
    rep_res = {t: f.result() for t, f in rep_futs.items()}

    _total = len(gap_futs) + len(rep_futs)
    _failed = _fails["gaps"] + _fails["reports"]
    if _total and _failed / _total > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_failed} з {_total} запитів "
            f"({_failed / _total * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Далі вийшла б порожня або обрізана мапа bench/corr/beta."
        )

    def _concat(parts, cols):
        valid = [p for p in parts if p is not None]
        return pd.concat(valid, ignore_index=True) if valid else pd.DataFrame(columns=cols)

    stock_gaps = _concat([gap_res.get(t) for t in stocks],         ["ticker", "date", "gap"])
    etf_gaps   = _concat([gap_res.get(t) for t in etf_candidates], ["ticker", "date", "gap"])
    reports    = _concat([rep_res.get(t) for t in stocks],          ["ticker", "date"]).drop_duplicates()

    CRACEN_FETCH_CACHE.clear()
    CRACEN_FETCH_CACHE.update({
        "window": (s_date, e_date),
        "last_n_reports": int(last_n_reports),
        "tickers": set(stocks),
        "gaps": stock_gaps.copy(),      # сирі, до drop anomalies нижче
        "reports": reports.copy(),
    })

    # ── exclude report days ──────────────────────────────────────────────────
    if not reports.empty and not stock_gaps.empty:
        m = stock_gaps.merge(reports.assign(_rep=1), on=["ticker", "date"], how="left")
        stock_gaps = m[m["_rep"].isna()][["ticker", "date", "gap"]].copy()

    # ── drop anomalies (vectorised) ──────────────────────────────────────────
    if not stock_gaps.empty:
        stock_gaps["gap"] = pd.to_numeric(stock_gaps["gap"], errors="coerce")
        abs_gap = stock_gaps["gap"].abs()
        cnts = stock_gaps.groupby("ticker")["gap"].transform("count")
        eligible = cnts >= min_hist_for_cap
        if eligible.any():
            caps = (stock_gaps[eligible]
                    .groupby("ticker")["gap"]
                    .agg(lambda x: np.quantile(x.abs(), cap_q)))
            cap_mapped = stock_gaps["ticker"].map(caps)
            stock_gaps = stock_gaps[(~eligible) | (abs_gap <= cap_mapped)].reset_index(drop=True)

    # ── build ETF numpy matrix: rows=dates, cols=etfs ───────────────────────
    if not etf_gaps.empty:
        etf_pivot = etf_gaps.pivot_table(index="date", columns="ticker", values="gap", aggfunc="first")
        date_to_row = {d: i for i, d in enumerate(etf_pivot.index)}
        etf_to_col  = {c: i for i, c in enumerate(etf_pivot.columns)}
        etf_arr     = etf_pivot.to_numpy(dtype=float)
    else:
        date_to_row = {}; etf_to_col = {}; etf_arr = np.empty((0, 0))

    stock_map = (
        {t: g.set_index("date")["gap"] for t, g in stock_gaps.groupby("ticker")}
        if not stock_gaps.empty else {}
    )

    # ── corr/beta loop ───────────────────────────────────────────────────────
    rows_all = []
    rows_best = []
    sectors_with_fallback = []

    for sec in sorted(df_clean[sector_col].unique()):
        etfs_raw = sector_to_etf.get(sec)
        if not etfs_raw:
            etfs_raw = list(fallback_etfs)
            sectors_with_fallback.append(sec)
        etfs = [str(e).upper() for e in etfs_raw]
        etfs_ok  = [e for e in etfs if e in etf_to_col]
        col_idxs = [etf_to_col[e] for e in etfs_ok]
        if not col_idxs:
            continue

        for st in sorted(df_clean.loc[df_clean[sector_col] == sec, ticker_col].unique()):
            sx = stock_map.get(st)
            if sx is None or sx.empty:
                continue

            st_dates = [d for d in sx.index if d in date_to_row]
            if not st_dates:
                continue

            row_idxs = [date_to_row[d] for d in st_dates]
            x_vals   = sx[st_dates].to_numpy(dtype=float)
            y_mat    = etf_arr[np.ix_(row_idxs, col_idxs)]   # (n_dates, n_etfs)
            valid_x  = ~np.isnan(x_vals)

            best_corr = -np.inf
            best_etf  = None
            best_beta = np.nan
            best_n    = 0

            for j, etf in enumerate(etfs_ok):
                mask = valid_x & ~np.isnan(y_mat[:, j])
                n = int(mask.sum())
                if n < min_overlap:
                    continue

                xv = x_vals[mask];  yv = y_mat[mask, j]
                xc = xv - xv.mean(); yc = yv - yv.mean()
                var_y = float((yc * yc).sum() / (n - 1))
                if var_y == 0 or np.isnan(var_y):
                    continue
                cov_xy = float((xc * yc).sum() / (n - 1))
                std_x  = float(np.sqrt((xc * xc).sum() / (n - 1)))
                if std_x == 0:
                    continue
                corr = cov_xy / (std_x * np.sqrt(var_y))
                beta = cov_xy / var_y

                rows_all.append({"x_ticker": st, "y_ticker": etf, "corr": corr, "beta": beta, "lvl3": sec, "n_overlap": n})

                if corr > best_corr:
                    best_corr, best_etf, best_beta, best_n = corr, etf, beta, n

            if best_etf is not None:
                rows_best.append({"x_ticker": st, "best_y_ticker": best_etf, "best_corr": best_corr,
                                  "beta_with_best": best_beta, "lvl3": sec, "n_overlap": best_n})

    # ── output ───────────────────────────────────────────────────────────────
    df_all   = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best) if rows_best else pd.DataFrame(
        columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "lvl3", "n_overlap"])

    df_pairs.to_csv(output_path, index=False)
    df_bench = df_pairs.rename(columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"})[["ticker", "benchmark"]]
    df_bench.to_csv(bench_path, index=False)

    print(f"DONE pairs: {len(df_pairs)} -> {output_path}")
    print(f"DONE bench map: {len(df_bench)} -> {bench_path}")
    if sectors_with_fallback:
        print("Fallback ETF used for sectors:", ", ".join(map(str, sectors_with_fallback[:20])))

    return df_all, df_pairs

In [13]:
# Local corr/beta: stock gaps vs ETF gaps, excluding report days and stock outliers
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=TICKERS,
    sector_to_etf=sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path=str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path=str(WORK_DIR / "ticker_bench_.csv"),
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    cap_q=0.8,
    min_hist_for_cap=20,
    min_overlap=20,
)

# Prepare parquet for downstream merge (cell 31)
corr_beta_pairs = df_pairs.rename(columns={
    "best_y_ticker": "y_ticker",
    "best_corr": "corr",
    "beta_with_best": "beta",
})[["x_ticker", "y_ticker", "corr", "beta"]].copy()

corr_beta_pairs.to_parquet(str(WORK_DIR / "corr_beta_pairs.parquet"), index=False)

print(df_all.head())
print("Rows in raw stock-etf pairs:", len(df_all))
print(df_pairs.head())
print("Saved:", str(WORK_DIR / "corr_beta_pairs.parquet"))

START gaps: stocks=7050 etfs=28 window=2026-07-24..2026-10-24

DONE pairs: 6964 -> C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
DONE bench map: 6964 -> C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv
Fallback ETF used for sectors: Investment Management, Other Financial Services, UNKNOWN

  x_ticker y_ticker      corr      beta                     lvl3  n_overlap
0      ADV      QQQ -0.070962 -0.058142  Advertising & Marketing         51
1     AEHL      QQQ  0.125007  0.613564  Advertising & Marketing         52
2      APP      QQQ  0.219996  0.223348  Advertising & Marketing         51
3     BAOS      QQQ  0.186206  0.500952  Advertising & Marketing         52
4     CDLX      QQQ  0.262349  0.319999  Advertising & Marketing         51
Rows in raw stock-etf pairs: 15633
  x_ticker best_y_ticker  best_corr  beta_with_best                     lvl3  \
0      ADV           QQQ  -0.070962       -0.058142  Advertising & Marketing
1     AEHL           QQQ   0.125007        0.613564  Advertising & Marketing
2      APP           QQQ   0.219996        0.223348  Advertising & Marketing
3     BAOS           QQQ   0.186206        0.500952  Advertising & Marketing
4     CDLX           QQQ   0.262349        0.319999  Advertising & Marketing

   n_overlap
0         51
1         52
2         51
3         52
4         51
Saved: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [14]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random, threading
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- збої API != порожні дані ----------
# Раніше будь-який збій (429/5xx/мережа; DatumApi.data_request повертає None після
# вичерпання ретраїв) тихо перетворювався на порожній DataFrame, а порожній результат
# позначав ВСІ дні діапазону «готовими» у done_days.csv → ці дні більше ніколи не
# докачувались (NVDA/AAPL/INTC… без 10–28 серпня при «готових» днях у маніфесті).
# Тепер збій піднімає FetchFailed, і такі дні НЕ потрапляють у маніфест.
class FetchFailed(Exception):
    pass

_MANIFEST_LOCK = threading.Lock()   # done_days.csv пишуть і воркери, і _flush → без lock рядки рвались

def _data_request_checked(endpoint: str, params: dict, max_retries: int, retry_backoff: float) -> pd.DataFrame:
    """DataFrame (можливо порожній = API відповів 200 і барів справді нема) або FetchFailed."""
    attempts = max(0, int(max_retries)) + 1
    last = None
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request(endpoint, params)
            if isinstance(df, pd.DataFrame):
                return df
            last = "None (DatumApi вичерпав ретраї)"
        except Exception as e:
            code = getattr(getattr(e, "response", None), "status_code", None)
            if code in (400, 404, 422):      # запит/тікер не обслуговується — не тимчасовий збій
                return pd.DataFrame()
            last = f"{type(e).__name__}: {e}"
        if attempt < attempts - 1:
            time.sleep(retry_backoff * (2 ** attempt) * (0.9 + 0.2 * random.random()))
    raise FetchFailed(f"{endpoint} {params.get('ticker')} {params.get('start_datetime')}..{params.get('end_datetime')}: {last}")

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    with _MANIFEST_LOCK:
        need_header = not os.path.exists(path)
        with open(path, "a", encoding="utf-8", newline="") as f:
            wr = csv.writer(f)
            if need_header:
                wr.writerow(["ticker","date"])
            for tk, dd in zip(tmp["ticker"], tmp["date"]):
                wr.writerow([str(tk).strip(), str(dd).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 4,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3. Збій → FetchFailed (не порожній DF)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    df = _data_request_checked("/intraday/v3", params, max_retries, retry_backoff)
    if df.empty:
        return pd.DataFrame()
    if "ticker" not in df.columns:
        df.insert(0, "ticker", ticker.upper())
    if normalize_ohlcv:
        for col in ("o","h","l","c","v"):
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="ignore")
    return df

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 4,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00). Збій → FetchFailed."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    df = _data_request_checked("/intraday/v3/blue_ocean", params, max_retries, retry_backoff)
    if df.empty:
        return pd.DataFrame()
    if "ticker" not in df.columns:
        df.insert(0, "ticker", ticker.upper())
    if normalize_ohlcv:
        for col in ("o","h","l","c","v"):
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="ignore")
    return df

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- один діапазон: основний ендпоінт (+ Blue Ocean) ---
    def _fetch_range(tk: str, a: str, b: str):
        """ok=False, якщо будь-який виклик ВПАВ (429/5xx/мережа). Порожня відповідь 200 — не збій."""
        parts: List[pd.DataFrame] = []
        ok, why = True, None
        calls = [lambda: _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv",
                                              include_boats=False, normalize_ohlcv=False)]
        if include_blue_ocean:
            calls.append(lambda: _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv",
                                                                 normalize_ohlcv=False))
        for call in calls:
            try:
                df = call()
            except FetchFailed as e:
                ok, why = False, str(e)
                continue
            if df is not None and not df.empty:
                parts.append(df)
        return a, b, parts, ok, why

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    results = list(ex.map(lambda r: _fetch_range(tk, r[0], r[1]), todo_ranges))
            else:
                results = [_fetch_range(tk, a, b) for (a, b) in todo_ranges]

            parts: List[pd.DataFrame] = []
            ok_days, bad_days, failed = set(), set(), []
            for a, b, p, ok, why in results:
                days = {d.strftime("%Y-%m-%d") for d in _dates_between(a, b)}
                if ok:
                    parts.extend(p)
                    ok_days |= days
                else:
                    # діапазон впав: його дні НЕ можна вважати готовими, а частково прийшлі
                    # рядки цих днів відкидаємо — інакше _flush позначить день «готовим»
                    # і докачки (напр. Blue Ocean частини) вже ніколи не буде
                    parts.extend(p)
                    bad_days |= days
                    failed.append(f"{a[:10]}..{b[:10]}: {why}")
            err = ("; ".join(failed))[:600] if failed else None

            dfo = pd.DataFrame()
            if parts:
                dfo = pd.concat(parts, ignore_index=True)
                if "dt" in dfo.columns:
                    dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                    dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

                # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
                if keep_columns:
                    base = ["ticker", "dt"]
                    cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                    cols = [c for c in cols if c in dfo.columns]
                    dfo = dfo[cols]

            present = set()
            if len(dfo) and "dt" in dfo.columns:
                day_s = dfo["dt"].astype(str).str.slice(0, 10)
                present = set(day_s)
                if bad_days:
                    dfo = dfo[~day_s.isin(bad_days)]

            # успішний діапазон без жодного бара за день = справді порожній день → готовий
            # (дні з барами позначить _flush після запису на диск)
            _mark_days_done(tk, [pd.Timestamp(d) for d in sorted(ok_days - present)])
            return tk, dfo, err
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err and df is not None and not df.empty:
                    # частковий збій: що прийшло — зберігаємо, збійні діапазони докачаються наступним запуском
                    errors.append({"ticker": tk_, "error": "PARTIAL: " + err})
                    if verbose:
                        _p(f"[{processed}/{total}] ⚠ {tk_}: частковий збій (буде докачано) | {err[:160]}")
                if err and (df is None or df.empty):
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err and df is not None and not df.empty:
                errors.append({"ticker": tk_, "error": "PARTIAL: " + err})
                if verbose:
                    _p(f"[{i}/{total}] ⚠ {tk_}: частковий збій (буде докачано) | {err[:160]}")
            if err and (df is None or df.empty):
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
        if errors:
            _p(f"⚠️ Тікерів зі збоями API: {len(errors)}. Їхні дні НЕ позначені готовими — "
               f"перезапусти цю ж клітинку, вона докачає саме їх.")
    return pd.DataFrame(errors)


def rebuild_done_days_from_batches(out_dir: str, start_date_str: str, end_date_str: str,
                                   pattern: str = "intraday_*.csv.gz") -> dict:
    """Перебудовує done_days.csv ЛИШЕ з того, що реально лежить у батчах.

    Старий маніфест містив «готові» дні без жодного бара (збій API → порожньо → «готово»)
    і побиті рядки. Після перебудови день вважається готовим, лише якщо в батчах є бар
    цього (ticker, date). Решту fetch_intraday_v3_for_all_tickers докачає і сам позначить
    справді порожні дні (вихідні/свята) — але тільки після УСПІШНОЇ відповіді API.
    """
    import pyarrow.csv as pacsv
    import pyarrow.compute as pc
    import pyarrow as pa
    files = sorted(glob.glob(os.path.join(out_dir, pattern)))
    if not files:
        raise FileNotFoundError(f"Немає {pattern} у {out_dir}")
    d0, d1 = str(start_date_str)[:10], str(end_date_str)[:10]
    pairs = set()
    for k, fp in enumerate(files, 1):
        rdr = pacsv.open_csv(fp, convert_options=pacsv.ConvertOptions(
            include_columns=["ticker", "dt"],
            column_types={"ticker": pa.string(), "dt": pa.string()}))
        for rb in rdr:
            t = pa.Table.from_batches([rb])
            g = pa.table({"ticker": pc.utf8_upper(pc.utf8_trim_whitespace(t["ticker"])),
                          "date": pc.utf8_slice_codeunits(t["dt"], 0, 10)}) \
                  .group_by(["ticker", "date"]).aggregate([])
            pairs.update(zip(g["ticker"].to_pylist(), g["date"].to_pylist()))
        if k % 100 == 0:
            print(f"  [{k}/{len(files)}] пар (ticker,date): {len(pairs):,}", flush=True)
    pairs = {(tk, dd) for tk, dd in pairs
             if tk and dd and re.fullmatch(r"\d{4}-\d\d-\d\d", dd) and d0 <= dd <= d1}
    path = _manifest_days_path(out_dir)
    old_n = 0
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            old_n = max(0, sum(1 for _ in f) - 1)
        os.replace(path, path + ".bak")
    with _MANIFEST_LOCK, open(path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker", "date"])
        for tk, dd in sorted(pairs):
            wr.writerow([tk, dd])
    print(f"✅ done_days.csv: було {old_n:,} → стало {len(pairs):,} (старий збережено як .bak)")
    done = {}
    for tk, dd in pairs:
        done.setdefault(tk, set()).add(dd)
    return done

In [15]:
TICKERS

     ticker      value                         lvl3  market_cap
0         A   69713.24  Medical Equipment & Devices     48793.0
1        AA  977030.32              Metals & Mining     10004.0
2      AAAU  325294.03                          NaN         NaN
3      AACG      17.22                     Software        31.0
4      AADX   57701.33          Aerospace & Defense      1723.0
...     ...        ...                          ...         ...
7045   ZVOL    5241.00                          NaN         NaN
7046   ZVRA    5103.69             Biotech & Pharma       582.0
7047    ZWS    1274.25                    Machinery      8052.0
7048   ZYBT    4589.24             Biotech & Pharma        44.0
7049   ZYME   38053.24             Biotech & Pharma      2017.0

[7050 rows x 4 columns]

In [16]:
import pandas as pd

# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]


# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

   ticker
0    ARKK
1    COPX
2    DRAM
3     FCX
4     FXI
5     GDX
6    IBIT
7     IGV
8     ITA
9     IWM
10    KRE
11   KWEB
12   NASA
13    QQQ
14    SLV
15   SOXX
16    SPY
17    UNG
18    URA
19    XBI
20    XLB
21    XLE
22    XLF
23    XLP
24    XLU
25    XLV
26    XOP
27    XRT

In [17]:
# Одноразово ПЕРЕД докачкою (клітинки з fetch_intraday_v3_for_all_tickers): перебудувати
# done_days.csv з реальних батчів. Старі маніфести містили «готові» дні без жодного бара
# (збій API трактувався як «порожньо»), через що ці дні не докачувались ніколи.
# Постав True, запусти, і знову постав False.
REBUILD_DONE_DAYS = False
if REBUILD_DONE_DAYS:
    rebuild_done_days_from_batches(str(BATCH_DIR), start_date_str, end_date_str)
    rebuild_done_days_from_batches(str(ETF_DIR), start_date_str, end_date_str)

In [18]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=TICKERS,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=16,
    parallel_tickers=True,
    max_workers_tickers=16,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

# Збої API більше не маскуються під «порожні дні»: усе, що тут перелічено, НЕ позначено
# готовим. Запускай клітинку повторно, доки errs не стане порожнім.
if errs is not None and len(errs):
    print(f"⚠️ {len(errs)} тікерів зі збоями — перезапусти клітинку:")
    print(errs.head(20).to_string())

▶ Починаємо: 7050 тікерів (пропущено 0 по старому маніфесту) | 2026-07-24 00:00:00 → 2026-10-24 23:59:59 | interval=1 | next batch #20947 | run=16c2d4a6

   workers: tickers=16, chunks=16 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-07-24 → 2026-10-22 (91 днів)

   📈 обробляються дні: 2026-10-23 → 2026-10-24 (2 днів)

   psutil · старт · 🧠 RAM: 319.1 MB

[10/7050] ✓ AA: 442 рядків |   0.14% | ETA 22:27

[20/7050] ✓ AAPU: 317 рядків |   0.28% | ETA 19:15

[30/7050] ✓ ABCL: 485 рядків |   0.43% | ETA 17:56

[40/7050] ✓ ABSI: 405 рядків |   0.57% | ETA 17:13

[50/7050] ✓ ACB: 208 рядків |   0.71% | ETA 16:55

   • RAM · 🧠 RAM: 343.3 MB

   ⏳ перед flush · 🧠 RAM: 343.5 MB

💾 batch 20947 → 15,452 рядків (всього 15,452 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20947.csv.gz

   ✅ після flush · 🧠 RAM: 350.8 MB

[60/7050] ✓ ACHC: 344 рядків |   0.85% | ETA 17:13

[70/7050] ✓ ACNB: 47 рядків |   0.99% | ETA 16:58

[80/7050] ✓ ACT: 247 рядків |   1.13% | ETA 16:47

[90/7050] ✓ ADBE: 558 рядків |   1.28% | ETA 16:40

[100/7050] ✓ ADM: 397 рядків |   1.42% | ETA 16:33

   • RAM · 🧠 RAM: 351.8 MB

   ⏳ перед flush · 🧠 RAM: 351.8 MB

💾 batch 20948 → 12,913 рядків (всього 28,365 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20948.csv.gz

   ✅ після flush · 🧠 RAM: 355.4 MB

[110/7050] ✓ ADUR: 148 рядків |   1.56% | ETA 16:58

[120/7050] ✓ AEG: 374 рядків |   1.70% | ETA 16:46

[130/7050] ✓ AEO: 400 рядків |   1.84% | ETA 16:36

[140/7050] ✓ AFJK: 2 рядків |   1.99% | ETA 16:33

[150/7050] ✓ AGIQ: 13 рядків |   2.13% | ETA 16:30

   • RAM · 🧠 RAM: 356.1 MB

   ⏳ перед flush · 🧠 RAM: 356.1 MB

💾 batch 20949 → 11,940 рядків (всього 40,305 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20949.csv.gz

   ✅ після flush · 🧠 RAM: 358.5 MB

[160/7050] ✓ AGO: 207 рядків |   2.27% | ETA 16:40

[170/7050] ✓ AGX: 327 рядків |   2.41% | ETA 16:34

[180/7050] ✓ AADX: 364 рядків |   2.55% | ETA 16:29

[190/7050] ✓ AIFF: 125 рядків |   2.70% | ETA 16:22

[200/7050] ✓ AIR: 276 рядків |   2.84% | ETA 16:20

   • RAM · 🧠 RAM: 351.4 MB

   ⏳ перед flush · 🧠 RAM: 351.5 MB

💾 batch 20950 → 9,309 рядків (всього 49,614 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20950.csv.gz

   ✅ після flush · 🧠 RAM: 356.6 MB

[210/7050] ✓ AIRR: 359 рядків |   2.98% | ETA 16:27

[220/7050] ✓ AKR: 286 рядків |   3.12% | ETA 16:25

[230/7050] – ALBG: empty |   3.26% | ETA 16:22

[240/7050] ✓ ALGT: 190 рядків |   3.40% | ETA 16:22

[250/7050] ✓ ALLO: 389 рядків |   3.55% | ETA 16:19

   • RAM · 🧠 RAM: 357.8 MB

   ⏳ перед flush · 🧠 RAM: 357.8 MB

💾 batch 20951 → 13,285 рядків (всього 62,899 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20951.csv.gz

   ✅ після flush · 🧠 RAM: 360.4 MB

[260/7050] ✓ ALOY: 356 рядків |   3.69% | ETA 16:28

[270/7050] ✓ ALTO: 308 рядків |   3.83% | ETA 16:24

[280/7050] ✓ AMBO: 2 рядків |   3.97% | ETA 16:21

[290/7050] ✓ AMDG: 67 рядків |   4.11% | ETA 16:19

[300/7050] ✓ AMIX: 65 рядків |   4.26% | ETA 16:16

   • RAM · 🧠 RAM: 361.5 MB

   ⏳ перед flush · 🧠 RAM: 361.5 MB

💾 batch 20952 → 13,270 рядків (всього 76,169 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20952.csv.gz

   ✅ після flush · 🧠 RAM: 362.5 MB

[310/7050] ✓ AMPU: 90 рядків |   4.40% | ETA 16:24

[320/7050] ✓ AMST: 14 рядків |   4.54% | ETA 16:19

[330/7050] ✓ AMWL: 122 рядків |   4.68% | ETA 16:15

[340/7050] ✓ AMZZ: 59 рядків |   4.82% | ETA 16:12

[350/7050] ✓ ANGH: 4 рядків |   4.96% | ETA 16:11

   • RAM · 🧠 RAM: 363.3 MB

   ⏳ перед flush · 🧠 RAM: 363.3 MB

💾 batch 20953 → 11,820 рядків (всього 87,989 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20953.csv.gz

   ✅ після flush · 🧠 RAM: 365.6 MB

[360/7050] ✓ ANGX: 369 рядків |   5.11% | ETA 16:15

[370/7050] ✓ AOD: 137 рядків |   5.25% | ETA 16:11

[380/7050] ✓ APAM: 305 рядків |   5.39% | ETA 16:09

[390/7050] ✓ APLZ: 90 рядків |   5.53% | ETA 16:07

[400/7050] ✓ APPS: 383 рядків |   5.67% | ETA 16:06

   • RAM · 🧠 RAM: 363.9 MB

   ⏳ перед flush · 🧠 RAM: 363.9 MB

💾 batch 20954 → 11,898 рядків (всього 99,887 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20954.csv.gz

   ✅ після flush · 🧠 RAM: 365.7 MB

[410/7050] ✓ AQMS: 27 рядків |   5.82% | ETA 16:09

[420/7050] ✓ ARBK: 5 рядків |   5.96% | ETA 16:06

[430/7050] ✓ AREC: 373 рядків |   6.10% | ETA 16:05

[440/7050] ✓ ARKK: 415 рядків |   6.24% | ETA 16:03

[450/7050] ✓ ARMK: 385 рядків |   6.38% | ETA 16:00

   • RAM · 🧠 RAM: 366.8 MB

   ⏳ перед flush · 🧠 RAM: 366.8 MB

💾 batch 20955 → 11,248 рядків (всього 111,135 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20955.csv.gz

   ✅ після flush · 🧠 RAM: 368.1 MB

[460/7050] ✓ ARR: 422 рядків |   6.52% | ETA 16:04

[470/7050] ✓ ARTY: 233 рядків |   6.67% | ETA 16:00

[480/7050] ✓ ASH: 197 рядків |   6.81% | ETA 15:58

[490/7050] ✓ ASND: 260 рядків |   6.95% | ETA 15:56

[500/7050] ✓ ASTI: 221 рядків |   7.09% | ETA 15:55

   • RAM · 🧠 RAM: 368.7 MB

   ⏳ перед flush · 🧠 RAM: 368.8 MB

💾 batch 20956 → 10,883 рядків (всього 122,018 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20956.csv.gz

   ✅ після flush · 🧠 RAM: 369.4 MB

[510/7050] ✓ ASYS: 195 рядків |   7.23% | ETA 15:58

[520/7050] ✓ ATGL: 98 рядків |   7.38% | ETA 15:54

[530/7050] ✓ ATOS: 91 рядків |   7.52% | ETA 15:52

[540/7050] ✓ ATXG: 5 рядків |   7.66% | ETA 15:51

[550/7050] ✓ AURE: 93 рядків |   7.80% | ETA 15:49

   • RAM · 🧠 RAM: 370.3 MB

   ⏳ перед flush · 🧠 RAM: 370.3 MB

💾 batch 20957 → 10,016 рядків (всього 132,034 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20957.csv.gz

   ✅ після flush · 🧠 RAM: 371.9 MB

[560/7050] ✓ AVAL: 144 рядків |   7.94% | ETA 15:52

[570/7050] ✓ AVDS: 36 рядків |   8.09% | ETA 15:49

[580/7050] ✓ AVIV: 97 рядків |   8.23% | ETA 15:47

[590/7050] ✓ AVR: 285 рядків |   8.37% | ETA 15:45

[600/7050] ✓ AVX: 196 рядків |   8.51% | ETA 15:44

   • RAM · 🧠 RAM: 373.0 MB

   ⏳ перед flush · 🧠 RAM: 373.0 MB

💾 batch 20958 → 11,696 рядків (всього 143,730 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20958.csv.gz

   ✅ після flush · 🧠 RAM: 373.7 MB

[610/7050] ✓ AX: 134 рядків |   8.65% | ETA 15:45

[620/7050] ✓ AXS: 345 рядків |   8.79% | ETA 15:43

[630/7050] ✓ AYA: 353 рядків |   8.94% | ETA 15:41

[640/7050] ✓ BAB: 123 рядків |   9.08% | ETA 15:39

[650/7050] ✓ BAER: 101 рядків |   9.22% | ETA 15:38

   • RAM · 🧠 RAM: 374.9 MB

   ⏳ перед flush · 🧠 RAM: 374.9 MB

💾 batch 20959 → 13,243 рядків (всього 156,973 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20959.csv.gz

   ✅ після flush · 🧠 RAM: 376.2 MB

[660/7050] ✓ BANC: 384 рядків |   9.36% | ETA 15:41

[670/7050] ✓ BATRA: 46 рядків |   9.50% | ETA 15:37

[680/7050] ✓ BBCP: 112 рядків |   9.65% | ETA 15:35

[690/7050] ✓ BBT: 346 рядків |   9.79% | ETA 15:34

[700/7050] – BCARU: empty |   9.93% | ETA 15:32

   • RAM · 🧠 RAM: 376.5 MB

   ⏳ перед flush · 🧠 RAM: 376.5 MB

💾 batch 20960 → 11,073 рядків (всього 168,046 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20960.csv.gz

   ✅ після flush · 🧠 RAM: 376.9 MB

[710/7050] ✓ BCD: 55 рядків |  10.07% | ETA 15:33

[720/7050] ✓ BCRX: 375 рядків |  10.21% | ETA 15:31

[730/7050] ✓ BDMD: 43 рядків |  10.35% | ETA 15:30

[740/7050] ✓ BEC: 122 рядків |  10.50% | ETA 15:29

[750/7050] ✓ BESS: 26 рядків |  10.64% | ETA 15:27

   • RAM · 🧠 RAM: 378.1 MB

   ⏳ перед flush · 🧠 RAM: 378.1 MB

💾 batch 20961 → 9,941 рядків (всього 177,987 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20961.csv.gz

   ✅ після flush · 🧠 RAM: 379.8 MB

[760/7050] ✓ BEX: 978 рядків |  10.78% | ETA 15:29

[770/7050] ✓ BGC: 378 рядків |  10.92% | ETA 15:27

[780/7050] ✓ BGMS: 18 рядків |  11.06% | ETA 15:25

[790/7050] ✓ BHRB: 103 рядків |  11.21% | ETA 15:23

[800/7050] ✓ BIDU: 498 рядків |  11.35% | ETA 15:22

   • RAM · 🧠 RAM: 380.6 MB

   ⏳ перед flush · 🧠 RAM: 380.6 MB

💾 batch 20962 → 10,039 рядків (всього 188,026 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20962.csv.gz

   ✅ після flush · 🧠 RAM: 381.2 MB

[810/7050] ✓ BIPC: 338 рядків |  11.49% | ETA 15:23

[820/7050] ✓ BIV: 385 рядків |  11.63% | ETA 15:21

[830/7050] ✓ BJRI: 249 рядків |  11.77% | ETA 15:20

[840/7050] ✓ BKU: 263 рядків |  11.91% | ETA 15:19

[850/7050] ✓ BLDP: 358 рядків |  12.06% | ETA 15:17

   • RAM · 🧠 RAM: 382.2 MB

   ⏳ перед flush · 🧠 RAM: 382.3 MB

💾 batch 20963 → 14,792 рядків (всього 202,818 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20963.csv.gz

   ✅ після flush · 🧠 RAM: 384.8 MB

[860/7050] ✓ BLOK: 199 рядків |  12.20% | ETA 15:19

[870/7050] ✓ BMEA: 354 рядків |  12.34% | ETA 15:17

[880/7050] ✓ BMR: 32 рядків |  12.48% | ETA 15:16

[890/7050] ✓ BMY: 406 рядків |  12.62% | ETA 15:15

[900/7050] ✓ BNR: 104 рядків |  12.77% | ETA 15:13

   • RAM · 🧠 RAM: 385.5 MB

   ⏳ перед flush · 🧠 RAM: 385.5 MB

💾 batch 20964 → 11,362 рядків (всього 214,180 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20964.csv.gz

   ✅ після flush · 🧠 RAM: 385.7 MB

[910/7050] ✓ BOEG: 51 рядків |  12.91% | ETA 15:14

[920/7050] ✓ BOXL: 9 рядків |  13.05% | ETA 15:12

[930/7050] ✓ BRAI: 70 рядків |  13.19% | ETA 15:11

[940/7050] ✓ BRKU: 102 рядків |  13.33% | ETA 15:09

[950/7050] – BRR: empty |  13.48% | ETA 15:08

   • RAM · 🧠 RAM: 389.2 MB

   ⏳ перед flush · 🧠 RAM: 389.2 MB

💾 batch 20965 → 19,934 рядків (всього 234,114 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20965.csv.gz

   ✅ після flush · 🧠 RAM: 390.8 MB

[960/7050] ✓ BRZU: 134 рядків |  13.62% | ETA 15:10

[970/7050] ✓ BSM: 235 рядків |  13.76% | ETA 15:08

[980/7050] ✓ BSV: 382 рядків |  13.90% | ETA 15:06

[990/7050] ✓ BTCL: 41 рядків |  14.04% | ETA 15:04

[1000/7050] ✓ BTGD: 24 рядків |  14.18% | ETA 15:03

   • RAM · 🧠 RAM: 390.8 MB

   ⏳ перед flush · 🧠 RAM: 390.8 MB

💾 batch 20966 → 10,128 рядків (всього 244,242 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20966.csv.gz

   ✅ після flush · 🧠 RAM: 390.8 MB

[1010/7050] ✓ BTU: 369 рядків |  14.33% | ETA 15:04

[1020/7050] ✓ BULL: 586 рядків |  14.47% | ETA 15:02

[1030/7050] ✓ BVS: 256 рядків |  14.61% | ETA 15:01

[1040/7050] ✓ BXBL: 55 рядків |  14.75% | ETA 14:59

[1050/7050] ✓ BY: 179 рядків |  14.89% | ETA 14:58

   • RAM · 🧠 RAM: 390.9 MB

   ⏳ перед flush · 🧠 RAM: 390.9 MB

💾 batch 20967 → 12,303 рядків (всього 256,545 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20967.csv.gz

   ✅ після flush · 🧠 RAM: 392.2 MB

[1060/7050] ✓ C: 422 рядків |  15.04% | ETA 14:58

[1070/7050] ✓ CAE: 286 рядків |  15.18% | ETA 14:57

[1080/7050] ✓ CALM: 333 рядків |  15.32% | ETA 14:55

[1090/7050] ✓ CAPA: 3 рядків |  15.46% | ETA 14:54

[1100/7050] ✓ CARS: 216 рядків |  15.60% | ETA 14:53

   • RAM · 🧠 RAM: 392.7 MB

   ⏳ перед flush · 🧠 RAM: 392.7 MB

💾 batch 20968 → 11,157 рядків (всього 267,702 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20968.csv.gz

   ✅ після flush · 🧠 RAM: 392.9 MB

[1110/7050] ✓ CATX: 335 рядків |  15.74% | ETA 14:53

[1120/7050] ✓ CBNK: 135 рядків |  15.89% | ETA 14:52

[1130/7050] ✓ CBU: 115 рядків |  16.03% | ETA 14:51

[1140/7050] ✓ CCCC: 361 рядків |  16.17% | ETA 14:49

[1150/7050] ✓ CCK: 292 рядків |  16.31% | ETA 14:47

   • RAM · 🧠 RAM: 393.3 MB

   ⏳ перед flush · 🧠 RAM: 393.4 MB

💾 batch 20969 → 11,628 рядків (всього 279,330 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20969.csv.gz

   ✅ після flush · 🧠 RAM: 394.3 MB

[1160/7050] ✓ CCXI: 383 рядків |  16.45% | ETA 14:47

[1170/7050] ✓ CDNS: 424 рядків |  16.60% | ETA 14:46

[1180/7050] ✓ CEGX: 81 рядків |  16.74% | ETA 14:45

[1190/7050] ✓ CEPL: 258 рядків |  16.88% | ETA 14:43

[1200/7050] ✓ CF: 379 рядків |  17.02% | ETA 14:43

   • RAM · 🧠 RAM: 395.4 MB

   ⏳ перед flush · 🧠 RAM: 395.4 MB

💾 batch 20970 → 11,239 рядків (всього 290,569 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20970.csv.gz

   ✅ після flush · 🧠 RAM: 396.6 MB

[1210/7050] ✓ CGBL: 361 рядків |  17.16% | ETA 14:43

[1220/7050] ✓ CGMU: 358 рядків |  17.30% | ETA 14:42

[1230/7050] ✓ CGUI: 82 рядків |  17.45% | ETA 14:41

[1240/7050] ✓ CHAT: 252 рядків |  17.59% | ETA 14:39

[1250/7050] ✓ CHMG: 76 рядків |  17.73% | ETA 14:37

   • RAM · 🧠 RAM: 396.8 MB

   ⏳ перед flush · 🧠 RAM: 396.8 MB

💾 batch 20971 → 11,955 рядків (всього 302,524 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20971.csv.gz

   ✅ після flush · 🧠 RAM: 398.6 MB

[1260/7050] ✓ CHR: 16 рядків |  17.87% | ETA 14:37

[1270/7050] ✓ CIBR: 428 рядків |  18.01% | ETA 14:36

[1280/7050] ✓ CIFU: 391 рядків |  18.16% | ETA 14:34

[1290/7050] ✓ CIRC: 289 рядків |  18.30% | ETA 14:33

[1300/7050] ✓ CJMB: 1,118 рядків |  18.44% | ETA 14:32

   • RAM · 🧠 RAM: 398.8 MB

   ⏳ перед flush · 🧠 RAM: 398.8 MB

💾 batch 20972 → 12,410 рядків (всього 314,934 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20972.csv.gz

   ✅ після flush · 🧠 RAM: 399.7 MB

[1310/7050] ✓ CLIP: 157 рядків |  18.58% | ETA 14:32

[1320/7050] ✓ CLPS: 27 рядків |  18.72% | ETA 14:31

[1330/7050] ✓ CLYM: 291 рядків |  18.87% | ETA 14:29

[1340/7050] ✓ CMF: 309 рядків |  19.01% | ETA 14:28

[1350/7050] ✓ CMRC: 217 рядків |  19.15% | ETA 14:27

   • RAM · 🧠 RAM: 400.0 MB

   ⏳ перед flush · 🧠 RAM: 400.2 MB

💾 batch 20973 → 12,775 рядків (всього 327,709 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20973.csv.gz

   ✅ після flush · 🧠 RAM: 400.5 MB

[1360/7050] ✓ CNET: 21 рядків |  19.29% | ETA 14:27

[1370/7050] ✓ CNQQ: 45 рядків |  19.43% | ETA 14:26

[1380/7050] ✓ CNX: 360 рядків |  19.57% | ETA 14:24

[1390/7050] ✓ COCO: 383 рядків |  19.72% | ETA 14:23

[1400/7050] ✓ COIA: 16 рядків |  19.86% | ETA 14:22

   • RAM · 🧠 RAM: 401.3 MB

   ⏳ перед flush · 🧠 RAM: 401.3 MB

💾 batch 20974 → 9,969 рядків (всього 337,678 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20974.csv.gz

   ✅ після flush · 🧠 RAM: 401.6 MB

[1410/7050] ✓ COLL: 224 рядків |  20.00% | ETA 14:22

[1420/7050] ✓ COOT: 33 рядків |  20.14% | ETA 14:21

[1430/7050] ✓ COPY: 89 рядків |  20.28% | ETA 14:19

[1440/7050] ✓ COSO: 91 рядків |  20.43% | ETA 14:18

[1450/7050] ✓ CPA: 160 рядків |  20.57% | ETA 14:17

   • RAM · 🧠 RAM: 401.5 MB

   ⏳ перед flush · 🧠 RAM: 401.5 MB

💾 batch 20975 → 13,487 рядків (всього 351,165 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20975.csv.gz

   ✅ після flush · 🧠 RAM: 402.4 MB

[1460/7050] ✓ CPRI: 392 рядків |  20.71% | ETA 14:17

[1470/7050] ✓ CQQQ: 371 рядків |  20.85% | ETA 14:16

[1480/7050] ✓ CRCG: 475 рядків |  20.99% | ETA 14:14

[1490/7050] ✓ CRGO: 24 рядків |  21.13% | ETA 14:13

[1500/7050] – CRMU: empty |  21.28% | ETA 14:12

   • RAM · 🧠 RAM: 402.3 MB

   ⏳ перед flush · 🧠 RAM: 402.3 MB

💾 batch 20976 → 13,114 рядків (всього 364,279 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20976.csv.gz

   ✅ після flush · 🧠 RAM: 404.1 MB

[1510/7050] – CROB: empty |  21.42% | ETA 14:13

[1520/7050] ✓ CRVS: 350 рядків |  21.56% | ETA 14:12

[1530/7050] ✓ CRWX: 109 рядків |  21.70% | ETA 14:10

[1540/7050] ✓ CSHR: 195 рядків |  21.84% | ETA 14:09

[1550/7050] ✓ CSTE: 34 рядків |  21.99% | ETA 14:08

   • RAM · 🧠 RAM: 405.1 MB

   ⏳ перед flush · 🧠 RAM: 405.2 MB

💾 batch 20977 → 12,285 рядків (всього 376,564 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20977.csv.gz

   ✅ після flush · 🧠 RAM: 406.7 MB

[1560/7050] ✓ CTM: 159 рядків |  22.13% | ETA 14:09

[1570/7050] ✓ CTRI: 366 рядків |  22.27% | ETA 14:07

[1580/7050] ✓ CUBE: 373 рядків |  22.41% | ETA 14:06

[1590/7050] ✓ CV: 126 рядків |  22.55% | ETA 14:05

[1600/7050] ✓ CVNY: 26 рядків |  22.70% | ETA 14:04

   • RAM · 🧠 RAM: 407.7 MB

   ⏳ перед flush · 🧠 RAM: 407.7 MB

💾 batch 20978 → 10,765 рядків (всього 387,329 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20978.csv.gz

   ✅ після flush · 🧠 RAM: 408.8 MB

[1610/7050] ✓ CWD: 40 рядків |  22.84% | ETA 14:04

[1620/7050] ✓ CXSE: 22 рядків |  22.98% | ETA 14:02

[1630/7050] ✓ CYD: 137 рядків |  23.12% | ETA 14:01

[1640/7050] ✓ DAC: 111 рядків |  23.26% | ETA 14:00

[1650/7050] ✓ DAVA: 119 рядків |  23.40% | ETA 13:59

   • RAM · 🧠 RAM: 410.0 MB

   ⏳ перед flush · 🧠 RAM: 409.9 MB

💾 batch 20979 → 11,305 рядків (всього 398,634 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20979.csv.gz

   ✅ після flush · 🧠 RAM: 410.8 MB

[1660/7050] ✓ DBC: 309 рядків |  23.55% | ETA 13:59

[1670/7050] ✓ DBX: 393 рядків |  23.69% | ETA 13:58

[1680/7050] ✓ DCOY: 47 рядків |  23.83% | ETA 13:57

[1690/7050] ✓ DDM: 184 рядків |  23.97% | ETA 13:56

[1700/7050] ✓ DEO: 429 рядків |  24.11% | ETA 13:54

   • RAM · 🧠 RAM: 411.3 MB

   ⏳ перед flush · 🧠 RAM: 411.3 MB

💾 batch 20980 → 11,577 рядків (всього 410,211 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20980.csv.gz

   ✅ після flush · 🧠 RAM: 412.4 MB

[1710/7050] ✓ DFAR: 336 рядків |  24.26% | ETA 13:54

[1720/7050] ✓ DFEV: 215 рядків |  24.40% | ETA 13:53

[1730/7050] ✓ DG: 396 рядків |  24.54% | ETA 13:52

[1740/7050] ✓ DGS: 62 рядків |  24.68% | ETA 13:50

[1750/7050] ✓ DIG: 94 рядків |  24.82% | ETA 13:49

   • RAM · 🧠 RAM: 412.6 MB

   ⏳ перед flush · 🧠 RAM: 412.6 MB

💾 batch 20981 → 11,617 рядків (всього 421,828 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20981.csv.gz

   ✅ після flush · 🧠 RAM: 412.7 MB

[1760/7050] ✓ DIVB: 296 рядків |  24.96% | ETA 13:49

[1770/7050] ✓ DLX: 185 рядків |  25.11% | ETA 13:47

[1780/7050] ✓ DLLL: 418 рядків |  25.25% | ETA 13:46

[1790/7050] ✓ DNN: 422 рядків |  25.39% | ETA 13:45

[1800/7050] ✓ DOLE: 283 рядків |  25.53% | ETA 13:43

   • RAM · 🧠 RAM: 411.1 MB

   ⏳ перед flush · 🧠 RAM: 411.1 MB

💾 batch 20982 → 13,244 рядків (всього 435,072 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20982.csv.gz

   ✅ після flush · 🧠 RAM: 411.4 MB

[1810/7050] ✓ DOX: 331 рядків |  25.67% | ETA 13:43

[1820/7050] ✓ DRAM: 1,056 рядків |  25.82% | ETA 13:42

[1830/7050] – DRNL: empty |  25.96% | ETA 13:41

[1840/7050] ✓ DRVN: 383 рядків |  26.10% | ETA 13:39

[1850/7050] ✓ DSY: 7 рядків |  26.24% | ETA 13:38

   • RAM · 🧠 RAM: 411.9 MB

   ⏳ перед flush · 🧠 RAM: 411.9 MB

💾 batch 20983 → 9,834 рядків (всього 444,906 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20983.csv.gz

   ✅ після flush · 🧠 RAM: 411.9 MB

[1860/7050] ✓ DUKR: 8 рядків |  26.38% | ETA 13:38

[1870/7050] ✓ DUOT: 260 рядків |  26.52% | ETA 13:37

[1880/7050] ✓ DX: 415 рядків |  26.67% | ETA 13:35

[1890/7050] ✓ DYAI: 33 рядків |  26.81% | ETA 13:34

[1900/7050] ✓ EBC: 387 рядків |  26.95% | ETA 13:33

   • RAM · 🧠 RAM: 412.9 MB

   ⏳ перед flush · 🧠 RAM: 413.0 MB

💾 batch 20984 → 10,990 рядків (всього 455,896 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20984.csv.gz

   ✅ після flush · 🧠 RAM: 415.2 MB

[1910/7050] ✓ ECC: 303 рядків |  27.09% | ETA 13:33

[1920/7050] ✓ EDGQ: 19 рядків |  27.23% | ETA 13:31

[1930/7050] ✓ EDVA: 213 рядків |  27.38% | ETA 13:30

[1940/7050] ✓ EEMV: 201 рядків |  27.52% | ETA 13:29

[1950/7050] ✓ EFX: 381 рядків |  27.66% | ETA 13:28

   • RAM · 🧠 RAM: 410.4 MB

   ⏳ перед flush · 🧠 RAM: 410.4 MB

💾 batch 20985 → 10,815 рядків (всього 466,711 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20985.csv.gz

   ✅ після flush · 🧠 RAM: 410.9 MB

[1960/7050] ✓ EGBN: 323 рядків |  27.80% | ETA 13:28

[1970/7050] ✓ EH: 300 рядків |  27.94% | ETA 13:26

[1980/7050] ✓ ELBM: 215 рядків |  28.09% | ETA 13:25

[1990/7050] ✓ ELOX: 31 рядків |  28.23% | ETA 13:24

[2000/7050] ✓ EMAT: 188 рядків |  28.37% | ETA 13:23

   • RAM · 🧠 RAM: 407.2 MB

   ⏳ перед flush · 🧠 RAM: 407.2 MB

💾 batch 20986 → 10,228 рядків (всього 476,939 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20986.csv.gz

   ✅ після flush · 🧠 RAM: 407.9 MB

[2010/7050] ✓ EMQQ: 25 рядків |  28.51% | ETA 13:22

[2020/7050] ✓ ENHA: 207 рядків |  28.65% | ETA 13:21

[2030/7050] ✓ ENSC: 74 рядків |  28.79% | ETA 13:20

[2040/7050] ✓ EPAM: 341 рядків |  28.94% | ETA 13:19

[2050/7050] ✓ EPR: 281 рядків |  29.08% | ETA 13:18

   • RAM · 🧠 RAM: 409.0 MB

   ⏳ перед flush · 🧠 RAM: 409.0 MB

💾 batch 20987 → 12,286 рядків (всього 489,225 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20987.csv.gz

   ✅ після flush · 🧠 RAM: 410.4 MB

[2060/7050] ✓ EQRR: 6 рядків |  29.22% | ETA 13:18

[2070/7050] ✓ ERIE: 113 рядків |  29.36% | ETA 13:16

[2080/7050] ✓ ESGD: 190 рядків |  29.50% | ETA 13:15

[2090/7050] ✓ ESP: 33 рядків |  29.65% | ETA 13:14

[2100/7050] ✓ ETHA: 631 рядків |  29.79% | ETA 13:13

   • RAM · 🧠 RAM: 411.5 MB

   ⏳ перед flush · 🧠 RAM: 411.5 MB

💾 batch 20988 → 11,860 рядків (всього 501,085 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20988.csv.gz

   ✅ після flush · 🧠 RAM: 412.7 MB

[2110/7050] ✓ ETOR: 269 рядків |  29.93% | ETA 13:13

[2120/7050] ✓ EUAD: 217 рядків |  30.07% | ETA 13:11

[2130/7050] ✓ EVEX: 272 рядків |  30.21% | ETA 13:10

[2140/7050] ✓ EW: 385 рядків |  30.35% | ETA 13:09

[2150/7050] ✓ EWH: 308 рядків |  30.50% | ETA 13:08

   • RAM · 🧠 RAM: 413.6 MB

   ⏳ перед flush · 🧠 RAM: 413.6 MB

💾 batch 20989 → 12,539 рядків (всього 513,624 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20989.csv.gz

   ✅ після flush · 🧠 RAM: 413.9 MB

[2160/7050] ✓ EWS: 307 рядків |  30.64% | ETA 13:08

[2170/7050] ✓ EXOD: 34 рядків |  30.78% | ETA 13:07

[2180/7050] ✓ EXPE: 355 рядків |  30.92% | ETA 13:05

[2190/7050] ✓ EYE: 312 рядків |  31.06% | ETA 13:04

[2200/7050] ✓ FALN: 310 рядків |  31.21% | ETA 13:03

   • RAM · 🧠 RAM: 414.9 MB

   ⏳ перед flush · 🧠 RAM: 414.9 MB

💾 batch 20990 → 13,495 рядків (всього 527,119 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20990.csv.gz

   ✅ після flush · 🧠 RAM: 416.0 MB

[2210/7050] ✓ FBDT: 104 рядків |  31.35% | ETA 13:02

[2220/7050] ✓ FBT: 110 рядків |  31.49% | ETA 13:01

[2230/7050] ✓ FCEL: 497 рядків |  31.63% | ETA 13:00

[2240/7050] ✓ FCUV: 23 рядків |  31.77% | ETA 12:59

[2250/7050] ✓ FDUS: 174 рядків |  31.91% | ETA 12:57

   • RAM · 🧠 RAM: 415.3 MB

   ⏳ перед flush · 🧠 RAM: 415.3 MB

💾 batch 20991 → 10,381 рядків (всього 537,500 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20991.csv.gz

   ✅ після flush · 🧠 RAM: 419.1 MB

[2260/7050] ✓ FEGE: 276 рядків |  32.06% | ETA 12:57

[2270/7050] ✓ FERG: 319 рядків |  32.20% | ETA 12:55

[2280/7050] ✓ FFLX: 55 рядків |  32.34% | ETA 12:54

[2290/7050] ✓ FHB: 393 рядків |  32.48% | ETA 12:53

[2300/7050] ✓ FIDU: 163 рядків |  32.62% | ETA 12:52

   • RAM · 🧠 RAM: 422.3 MB

   ⏳ перед flush · 🧠 RAM: 422.3 MB

💾 batch 20992 → 23,444 рядків (всього 560,944 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20992.csv.gz

   ✅ після flush · 🧠 RAM: 425.1 MB

[2310/7050] ✓ FIGS: 392 рядків |  32.77% | ETA 12:52

[2320/7050] ✓ FLBR: 193 рядків |  32.91% | ETA 12:50

[2330/7050] ✓ FLGV: 123 рядків |  33.05% | ETA 12:49

[2340/7050] ✓ FLOT: 373 рядків |  33.19% | ETA 12:48

[2350/7050] ✓ FLUX: 59 рядків |  33.33% | ETA 12:46

   • RAM · 🧠 RAM: 425.1 MB

   ⏳ перед flush · 🧠 RAM: 425.1 MB

💾 batch 20993 → 12,636 рядків (всього 573,580 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20993.csv.gz

   ✅ після flush · 🧠 RAM: 425.1 MB

[2360/7050] ✓ FMBH: 103 рядків |  33.48% | ETA 12:46

[2370/7050] ✓ FNCL: 127 рядків |  33.62% | ETA 12:45

[2380/7050] ✓ FNDX: 382 рядків |  33.76% | ETA 12:44

[2390/7050] ✓ FNV: 337 рядків |  33.90% | ETA 12:42

[2400/7050] ✓ FOXX: 13 рядків |  34.04% | ETA 12:41

   • RAM · 🧠 RAM: 425.0 MB

   ⏳ перед flush · 🧠 RAM: 425.0 MB

💾 batch 20994 → 11,855 рядків (всього 585,435 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20994.csv.gz

   ✅ після flush · 🧠 RAM: 425.0 MB

[2410/7050] ✓ FRD: 46 рядків |  34.18% | ETA 12:41

[2420/7050] ✓ FRPT: 284 рядків |  34.33% | ETA 12:39

[2430/7050] ✓ FSLR: 417 рядків |  34.47% | ETA 12:38

[2440/7050] ✓ FTCI: 101 рядків |  34.61% | ETA 12:37

[2450/7050] ✓ FTHI: 256 рядків |  34.75% | ETA 12:35

   • RAM · 🧠 RAM: 422.9 MB

   ⏳ перед flush · 🧠 RAM: 422.9 MB

💾 batch 20995 → 12,287 рядків (всього 597,722 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20995.csv.gz

   ✅ після flush · 🧠 RAM: 422.9 MB

[2460/7050] ✓ FUBO: 367 рядків |  34.89% | ETA 12:35

[2470/7050] ✓ FUNC: 36 рядків |  35.04% | ETA 12:34

[2480/7050] ✓ FWONA: 108 рядків |  35.18% | ETA 12:32

[2490/7050] ✓ FXU: 237 рядків |  35.32% | ETA 12:31

[2500/7050] ✓ GAME: 69 рядків |  35.46% | ETA 12:30

   • RAM · 🧠 RAM: 416.8 MB

   ⏳ перед flush · 🧠 RAM: 416.8 MB

💾 batch 20996 → 10,980 рядків (всього 608,702 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20996.csv.gz

   ✅ після flush · 🧠 RAM: 416.9 MB

[2510/7050] ✓ GBDC: 343 рядків |  35.60% | ETA 12:29

[2520/7050] ✓ GCT: 246 рядків |  35.74% | ETA 12:28

[2530/7050] ✓ GDLC: 50 рядків |  35.89% | ETA 12:26

[2540/7050] ✓ GE: 515 рядків |  36.03% | ETA 12:25

[2550/7050] ✓ GENB: 227 рядків |  36.17% | ETA 12:23

   • RAM · 🧠 RAM: 417.6 MB

   ⏳ перед flush · 🧠 RAM: 417.6 MB

💾 batch 20997 → 11,210 рядків (всього 619,912 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20997.csv.gz

   ✅ після flush · 🧠 RAM: 417.7 MB

[2560/7050] ✓ GEV: 594 рядків |  36.31% | ETA 12:23

[2570/7050] ✓ GGAL: 315 рядків |  36.45% | ETA 12:21

[2580/7050] ✓ GGN: 265 рядків |  36.60% | ETA 12:20

[2590/7050] ✓ GILT: 295 рядків |  36.74% | ETA 12:19

[2600/7050] ✓ GLBE: 367 рядків |  36.88% | ETA 12:17

   • RAM · 🧠 RAM: 418.6 MB

   ⏳ перед flush · 🧠 RAM: 418.6 MB

💾 batch 20998 → 12,481 рядків (всього 632,393 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20998.csv.gz

   ✅ після flush · 🧠 RAM: 419.8 MB

[2610/7050] ✓ GLIBK: 191 рядків |  37.02% | ETA 12:17

[2620/7050] ✓ GLUE: 303 рядків |  37.16% | ETA 12:15

[2630/7050] ✓ GMAB: 417 рядків |  37.30% | ETA 12:14

[2640/7050] ✓ GMUB: 113 рядків |  37.45% | ETA 12:13

[2650/7050] ✓ GNS: 371 рядків |  37.59% | ETA 12:11

   • RAM · 🧠 RAM: 420.4 MB

   ⏳ перед flush · 🧠 RAM: 420.4 MB

💾 batch 20999 → 11,797 рядків (всього 644,190 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_20999.csv.gz

   ✅ після flush · 🧠 RAM: 421.6 MB

[2660/7050] ✓ GOGL: 10 рядків |  37.73% | ETA 12:10

[2670/7050] ✓ GOOL: 72 рядків |  37.87% | ETA 12:09

[2680/7050] ✓ GOTU: 226 рядків |  38.01% | ETA 12:08

[2690/7050] ✓ GPCR: 311 рядків |  38.16% | ETA 12:06

[2700/7050] ✓ GPRO: 435 рядків |  38.30% | ETA 12:05

   • RAM · 🧠 RAM: 421.5 MB

   ⏳ перед flush · 🧠 RAM: 421.5 MB

💾 batch 21000 → 12,259 рядків (всього 656,449 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21000.csv.gz

   ✅ після flush · 🧠 RAM: 423.2 MB

[2710/7050] ✓ GRCE: 35 рядків |  38.44% | ETA 12:05

[2720/7050] ✓ GRID: 390 рядків |  38.58% | ETA 12:03

[2730/7050] ✓ GS: 450 рядків |  38.72% | ETA 12:02

[2740/7050] ✓ GSM: 298 рядків |  38.87% | ETA 12:00

[2750/7050] ✓ GTM: 390 рядків |  39.01% | ETA 11:59

   • RAM · 🧠 RAM: 423.5 MB

   ⏳ перед flush · 🧠 RAM: 423.5 MB

💾 batch 21001 → 12,114 рядків (всього 668,563 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21001.csv.gz

   ✅ після flush · 🧠 RAM: 423.7 MB

[2760/7050] – GV: empty |  39.15% | ETA 11:58

[2770/7050] ✓ GWRS: 44 рядків |  39.29% | ETA 11:57

[2780/7050] ✓ HAKY: 32 рядків |  39.43% | ETA 11:55

[2790/7050] ✓ HASI: 288 рядків |  39.57% | ETA 11:54

[2800/7050] ✓ HCAT: 129 рядків |  39.72% | ETA 11:52

   • RAM · 🧠 RAM: 424.5 MB

   ⏳ перед flush · 🧠 RAM: 424.5 MB

💾 batch 21002 → 10,383 рядків (всього 678,946 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21002.csv.gz

   ✅ після flush · 🧠 RAM: 425.0 MB

[2810/7050] ✓ HDSN: 227 рядків |  39.86% | ETA 11:51

[2820/7050] ✓ HELO: 209 рядків |  40.00% | ETA 11:50

[2830/7050] ✓ HG: 190 рядків |  40.14% | ETA 11:49

[2840/7050] ✓ HII: 366 рядків |  40.28% | ETA 11:47

[2850/7050] ✓ HIVE: 468 рядків |  40.43% | ETA 11:46

   • RAM · 🧠 RAM: 418.3 MB

   ⏳ перед flush · 🧠 RAM: 418.3 MB

💾 batch 21003 → 10,484 рядків (всього 689,430 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21003.csv.gz

   ✅ після flush · 🧠 RAM: 418.6 MB

[2860/7050] ✓ HLIT: 327 рядків |  40.57% | ETA 11:45

[2870/7050] ✓ HMR: 61 рядків |  40.71% | ETA 11:44

[2880/7050] ✓ HNST: 393 рядків |  40.85% | ETA 11:42

[2890/7050] ✓ HOOD: 846 рядків |  40.99% | ETA 11:41

[2900/7050] ✓ HOYY: 29 рядків |  41.13% | ETA 11:39

   • RAM · 🧠 RAM: 416.1 MB

   ⏳ перед flush · 🧠 RAM: 416.1 MB

💾 batch 21004 → 11,840 рядків (всього 701,270 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21004.csv.gz

   ✅ після flush · 🧠 RAM: 417.1 MB

[2910/7050] ✓ HQ: 90 рядків |  41.28% | ETA 11:39

[2920/7050] ✓ HSAI: 481 рядків |  41.42% | ETA 11:37

[2930/7050] ✓ HSY: 386 рядків |  41.56% | ETA 11:36

[2940/7050] ✓ HTOO: 9 рядків |  41.70% | ETA 11:34

[2950/7050] ✓ HUDI: 160 рядків |  41.84% | ETA 11:33

   • RAM · 🧠 RAM: 417.6 MB

   ⏳ перед flush · 🧠 RAM: 417.6 MB

💾 batch 21005 → 13,749 рядків (всього 715,019 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21005.csv.gz

   ✅ після flush · 🧠 RAM: 418.8 MB

[2960/7050] ✓ HVAC: 15 рядків |  41.99% | ETA 11:32

[2970/7050] ✓ HYFT: 115 рядків |  42.13% | ETA 11:31

[2980/7050] ✓ HYPD: 105 рядків |  42.27% | ETA 11:29

[2990/7050] ✓ IAM: 334 рядків |  42.41% | ETA 11:28

[3000/7050] ✓ IBCP: 138 рядків |  42.55% | ETA 11:26

   • RAM · 🧠 RAM: 419.8 MB

   ⏳ перед flush · 🧠 RAM: 419.8 MB

💾 batch 21006 → 11,982 рядків (всього 727,001 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21006.csv.gz

   ✅ після flush · 🧠 RAM: 420.9 MB

[3010/7050] ✓ IBLC: 11 рядків |  42.70% | ETA 11:26

[3020/7050] ✓ IBTK: 138 рядків |  42.84% | ETA 11:24

[3030/7050] ✓ ICG: 62 рядків |  42.98% | ETA 11:23

[3040/7050] ✓ ICUI: 162 рядків |  43.12% | ETA 11:21

[3050/7050] ✓ IDNA: 119 рядків |  43.26% | ETA 11:20

   • RAM · 🧠 RAM: 421.4 MB

   ⏳ перед flush · 🧠 RAM: 421.7 MB

💾 batch 21007 → 10,728 рядків (всього 737,729 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21007.csv.gz

   ✅ після flush · 🧠 RAM: 421.9 MB

[3060/7050] ✓ IDXX: 313 рядків |  43.40% | ETA 11:19

[3070/7050] ✓ IEZ: 365 рядків |  43.55% | ETA 11:17

[3080/7050] ✓ IFS: 75 рядків |  43.69% | ETA 11:16

[3090/7050] ✓ IGSB: 373 рядків |  43.83% | ETA 11:15

[3100/7050] ✓ IJH: 399 рядків |  43.97% | ETA 11:13

   • RAM · 🧠 RAM: 421.6 MB

   ⏳ перед flush · 🧠 RAM: 421.6 MB

💾 batch 21008 → 12,507 рядків (всього 750,236 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21008.csv.gz

   ✅ після flush · 🧠 RAM: 422.7 MB

[3110/7050] – ILLR: empty |  44.11% | ETA 11:12

[3120/7050] ✓ IMCC: 95 рядків |  44.26% | ETA 11:11

[3130/7050] ✓ IMRX: 278 рядків |  44.40% | ETA 11:09

[3140/7050] ✓ INBS: 33 рядків |  44.54% | ETA 11:08

[3150/7050] ✓ INDY: 79 рядків |  44.68% | ETA 11:06

   • RAM · 🧠 RAM: 422.7 MB

   ⏳ перед flush · 🧠 RAM: 422.7 MB

💾 batch 21009 → 9,300 рядків (всього 759,536 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21009.csv.gz

   ✅ після flush · 🧠 RAM: 424.0 MB

[3160/7050] ✓ INGN: 176 рядків |  44.82% | ETA 11:05

[3170/7050] ✓ INMU: 194 рядків |  44.96% | ETA 11:04

[3180/7050] ✓ INT: 63 рядків |  45.11% | ETA 11:03

[3190/7050] ✓ INVA: 307 рядків |  45.25% | ETA 11:01

[3200/7050] ✓ IONL: 304 рядків |  45.39% | ETA 11:00

   • RAM · 🧠 RAM: 425.1 MB

   ⏳ перед flush · 🧠 RAM: 425.1 MB

💾 batch 21010 → 13,891 рядків (всього 773,427 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21010.csv.gz

   ✅ після flush · 🧠 RAM: 426.5 MB

[3210/7050] ✓ IOYY: 13 рядків |  45.53% | ETA 10:59

[3220/7050] ✓ IPSC: 260 рядків |  45.67% | ETA 10:57

[3230/7050] ✓ IQMM: 22 рядків |  45.82% | ETA 10:56

[3240/7050] ✓ INDL: 38 рядків |  45.96% | ETA 10:55

[3250/7050] ✓ IRTC: 248 рядків |  46.10% | ETA 10:53

   • RAM · 🧠 RAM: 425.4 MB

   ⏳ перед flush · 🧠 RAM: 425.5 MB

💾 batch 21011 → 12,720 рядків (всього 786,147 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21011.csv.gz

   ✅ після flush · 🧠 RAM: 426.5 MB

[3260/7050] ✓ ISRG: 461 рядків |  46.24% | ETA 10:52

[3270/7050] ✓ ITGR: 244 рядків |  46.38% | ETA 10:51

[3280/7050] ✓ IVA: 371 рядків |  46.52% | ETA 10:49

[3290/7050] ✓ IVF: 72 рядків |  46.67% | ETA 10:48

[3300/7050] ✓ IWD: 370 рядків |  46.81% | ETA 10:47

   • RAM · 🧠 RAM: 426.9 MB

   ⏳ перед flush · 🧠 RAM: 426.9 MB

💾 batch 21012 → 11,485 рядків (всього 797,632 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21012.csv.gz

   ✅ після flush · 🧠 RAM: 428.8 MB

[3310/7050] ✓ IWV: 243 рядків |  46.95% | ETA 10:46

[3320/7050] ✓ IYE: 417 рядків |  47.09% | ETA 10:44

[3330/7050] ✓ IYZ: 349 рядків |  47.23% | ETA 10:43

[3340/7050] ✓ JAN: 373 рядків |  47.38% | ETA 10:41

[3350/7050] ✓ JBHT: 337 рядків |  47.52% | ETA 10:40

   • RAM · 🧠 RAM: 429.2 MB

   ⏳ перед flush · 🧠 RAM: 429.2 MB

💾 batch 21013 → 12,762 рядків (всього 810,394 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21013.csv.gz

   ✅ після flush · 🧠 RAM: 430.1 MB

[3360/7050] ✓ JDVI: 55 рядків |  47.66% | ETA 10:39

[3370/7050] ✓ JEPI: 490 рядків |  47.80% | ETA 10:37

[3380/7050] ✓ JHMD: 75 рядків |  47.94% | ETA 10:36

[3390/7050] ✓ JKS: 298 рядків |  48.09% | ETA 10:34

[3400/7050] ✓ JNJ: 441 рядків |  48.23% | ETA 10:33

   • RAM · 🧠 RAM: 428.5 MB

   ⏳ перед flush · 🧠 RAM: 428.5 MB

💾 batch 21014 → 12,467 рядків (всього 822,861 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21014.csv.gz

   ✅ після flush · 🧠 RAM: 428.7 MB

[3410/7050] ✓ JPRF: 93 рядків |  48.37% | ETA 10:32

[3420/7050] ✓ JQC: 182 рядків |  48.51% | ETA 10:30

[3430/7050] ✓ JXG: 84 рядків |  48.65% | ETA 10:29

[3440/7050] ✓ KALU: 265 рядків |  48.79% | ETA 10:28

[3450/7050] ✓ KBH: 367 рядків |  48.94% | ETA 10:26

   • RAM · 🧠 RAM: 429.4 MB

   ⏳ перед flush · 🧠 RAM: 429.4 MB

💾 batch 21015 → 7,952 рядків (всього 830,813 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21015.csv.gz

   ✅ після flush · 🧠 RAM: 430.2 MB

[3460/7050] ✓ KE: 96 рядків |  49.08% | ETA 10:25

[3470/7050] ✓ KEY: 393 рядків |  49.22% | ETA 10:24

[3480/7050] ✓ KHC: 448 рядків |  49.36% | ETA 10:22

[3490/7050] ✓ KLIC: 292 рядків |  49.50% | ETA 10:21

[3500/7050] ✓ KMLI: 17 рядків |  49.65% | ETA 10:19

   • RAM · 🧠 RAM: 431.1 MB

   ⏳ перед flush · 🧠 RAM: 431.1 MB

💾 batch 21016 → 11,758 рядків (всього 842,571 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21016.csv.gz

   ✅ після flush · 🧠 RAM: 433.6 MB

[3510/7050] ✓ KNDI: 38 рядків |  49.79% | ETA 10:18

[3520/7050] ✓ KOID: 138 рядків |  49.93% | ETA 10:17

[3530/7050] ✓ KOS: 416 рядків |  50.07% | ETA 10:15

[3540/7050] ✓ KR: 406 рядків |  50.21% | ETA 10:14

[3550/7050] ✓ KRSA: 143 рядків |  50.35% | ETA 10:12

   • RAM · 🧠 RAM: 433.1 MB

   ⏳ перед flush · 🧠 RAM: 433.1 MB

💾 batch 21017 → 13,130 рядків (всього 855,701 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21017.csv.gz

   ✅ після flush · 🧠 RAM: 434.6 MB

[3560/7050] ✓ KSS: 415 рядків |  50.50% | ETA 10:12

[3570/7050] ✓ KULR: 325 рядків |  50.64% | ETA 10:10

[3580/7050] ✓ KYLD: 72 рядків |  50.78% | ETA 10:09

[3590/7050] ✓ LABU: 241 рядків |  50.92% | ETA 10:07

[3600/7050] ✓ LANV: 9 рядків |  51.06% | ETA 10:06

   • RAM · 🧠 RAM: 432.5 MB

   ⏳ перед flush · 🧠 RAM: 432.5 MB

💾 batch 21018 → 11,527 рядків (всього 867,228 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21018.csv.gz

   ✅ після flush · 🧠 RAM: 432.7 MB

[3610/7050] ✓ LB: 128 рядків |  51.21% | ETA 10:05

[3620/7050] ✓ LCU: 9 рядків |  51.35% | ETA 10:03

[3630/7050] ✓ LEDS: 8 рядків |  51.49% | ETA 10:02

[3640/7050] ✓ LEU: 408 рядків |  51.63% | ETA 10:00

[3650/7050] ✓ LFUS: 291 рядків |  51.77% | ETA 09:59

   • RAM · 🧠 RAM: 433.2 MB

   ⏳ перед flush · 🧠 RAM: 433.2 MB

💾 batch 21019 → 9,736 рядків (всього 876,964 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21019.csv.gz

   ✅ після flush · 🧠 RAM: 433.4 MB

[3660/7050] ✓ LHSW: 330 рядків |  51.91% | ETA 09:58

[3670/7050] ✓ LHX: 403 рядків |  52.06% | ETA 09:56

[3680/7050] ✓ LINT: 68 рядків |  52.20% | ETA 09:55

[3690/7050] ✓ LITX: 817 рядків |  52.34% | ETA 09:53

[3700/7050] ✓ LLYX: 174 рядків |  52.48% | ETA 09:52

   • RAM · 🧠 RAM: 434.4 MB

   ⏳ перед flush · 🧠 RAM: 434.4 MB

💾 batch 21020 → 11,925 рядків (всього 888,889 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21020.csv.gz

   ✅ після flush · 🧠 RAM: 436.0 MB

[3710/7050] ✓ LNAI: 535 рядків |  52.62% | ETA 09:51

[3720/7050] ✓ LOAN: 23 рядків |  52.77% | ETA 09:49

[3730/7050] ✓ LONA: 35 рядків |  52.91% | ETA 09:48

[3740/7050] ✓ LPA: 9 рядків |  53.05% | ETA 09:46

[3750/7050] – LRHC: empty |  53.19% | ETA 09:45

   • RAM · 🧠 RAM: 436.8 MB

   ⏳ перед flush · 🧠 RAM: 436.8 MB

💾 batch 21021 → 9,469 рядків (всього 898,358 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21021.csv.gz

   ✅ після flush · 🧠 RAM: 436.9 MB

[3760/7050] ✓ LSCC: 410 рядків |  53.33% | ETA 09:43

[3770/7050] ✓ LTRN: 86 рядків |  53.48% | ETA 09:42

[3780/7050] ✓ LUMA: 16 рядків |  53.62% | ETA 09:40

[3790/7050] ✓ LVS: 416 рядків |  53.76% | ETA 09:39

[3800/7050] ✓ LXP: 306 рядків |  53.90% | ETA 09:37

   • RAM · 🧠 RAM: 438.2 MB

   ⏳ перед flush · 🧠 RAM: 438.2 MB

💾 batch 21022 → 12,360 рядків (всього 910,718 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21022.csv.gz

   ✅ після flush · 🧠 RAM: 440.7 MB

[3810/7050] ✓ LZ: 387 рядків |  54.04% | ETA 09:36

[3820/7050] ✓ MAIN: 256 рядків |  54.18% | ETA 09:35

[3830/7050] ✓ MANE: 246 рядків |  54.33% | ETA 09:33

[3840/7050] ✓ MAT: 394 рядків |  54.47% | ETA 09:32

[3850/7050] ✓ MBC: 359 рядків |  54.61% | ETA 09:30

   • RAM · 🧠 RAM: 441.5 MB

   ⏳ перед flush · 🧠 RAM: 441.5 MB

💾 batch 21023 → 12,638 рядків (всього 923,356 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21023.csv.gz

   ✅ після flush · 🧠 RAM: 442.0 MB

[3860/7050] ✓ MBWM: 92 рядків |  54.75% | ETA 09:29

[3870/7050] ✓ MCY: 98 рядків |  54.89% | ETA 09:28

[3880/7050] ✓ MDGL: 255 рядків |  55.04% | ETA 09:26

[3890/7050] ✓ MDYV: 95 рядків |  55.18% | ETA 09:25

[3900/7050] ✓ MEI: 245 рядків |  55.32% | ETA 09:23

   • RAM · 🧠 RAM: 442.4 MB

   ⏳ перед flush · 🧠 RAM: 442.5 MB

💾 batch 21024 → 11,148 рядків (всього 934,504 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21024.csv.gz

   ✅ після flush · 🧠 RAM: 443.8 MB

[3910/7050] ✓ METQ: 200 рядків |  55.46% | ETA 09:22

[3920/7050] ✓ MFC: 387 рядків |  55.60% | ETA 09:21

[3930/7050] ✓ MGNR: 104 рядків |  55.74% | ETA 09:19

[3940/7050] ✓ MGY: 388 рядків |  55.89% | ETA 09:18

[3950/7050] ✓ MICC: 292 рядків |  56.03% | ETA 09:16

   • RAM · 🧠 RAM: 443.0 MB

   ⏳ перед flush · 🧠 RAM: 443.0 MB

💾 batch 21025 → 13,457 рядків (всього 947,961 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21025.csv.gz

   ✅ після flush · 🧠 RAM: 444.0 MB

[3960/7050] ✓ MITQ: 19 рядків |  56.17% | ETA 09:15

[3970/7050] ✓ MLAB: 60 рядків |  56.31% | ETA 09:13

[3980/7050] ✓ MLI: 390 рядків |  56.45% | ETA 09:12

[3990/7050] ✓ MMS: 219 рядків |  56.60% | ETA 09:10

[4000/7050] ✓ MNKD: 382 рядків |  56.74% | ETA 09:09

   • RAM · 🧠 RAM: 443.4 MB

   ⏳ перед flush · 🧠 RAM: 443.4 MB

💾 batch 21026 → 9,742 рядків (всього 957,703 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21026.csv.gz

   ✅ після flush · 🧠 RAM: 444.4 MB

[4010/7050] ✓ MNTS: 221 рядків |  56.88% | ETA 09:08

[4020/7050] ✓ MOG.A: 329 рядків |  57.02% | ETA 09:06

[4030/7050] – MPL: empty |  57.16% | ETA 09:04

[4040/7050] ✓ MPWR: 466 рядків |  57.30% | ETA 09:03

[4050/7050] ✓ MRLN: 343 рядків |  57.45% | ETA 09:01

   • RAM · 🧠 RAM: 445.5 MB

   ⏳ перед flush · 🧠 RAM: 445.5 MB

💾 batch 21027 → 10,155 рядків (всього 967,858 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21027.csv.gz

   ✅ після flush · 🧠 RAM: 446.8 MB

[4060/7050] ✓ MRVX: 6 рядків |  57.59% | ETA 09:00

[4070/7050] ✓ MSBI: 164 рядків |  57.73% | ETA 08:58

[4080/7050] ✓ MSFU: 409 рядків |  57.87% | ETA 08:57

[4090/7050] ✓ MSOS: 384 рядків |  58.01% | ETA 08:55

[4100/7050] ✓ MSTR: 967 рядків |  58.16% | ETA 08:54

   • RAM · 🧠 RAM: 447.9 MB

   ⏳ перед flush · 🧠 RAM: 447.9 MB

💾 batch 21028 → 14,844 рядків (всього 982,702 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21028.csv.gz

   ✅ після flush · 🧠 RAM: 449.5 MB

[4110/7050] ✓ MTEK: 153 рядків |  58.30% | ETA 08:53

[4120/7050] ✓ MTVA: 50 рядків |  58.44% | ETA 08:51

[4130/7050] ✓ MUD: 653 рядків |  58.58% | ETA 08:50

[4140/7050] – MVO: empty |  58.72% | ETA 08:48

[4150/7050] ✓ MWH: 373 рядків |  58.87% | ETA 08:46

   • RAM · 🧠 RAM: 450.7 MB

   ⏳ перед flush · 🧠 RAM: 450.7 MB

💾 batch 21029 → 14,572 рядків (всього 997,274 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21029.csv.gz

   ✅ після flush · 🧠 RAM: 452.0 MB

[4160/7050] ✓ MYGN: 366 рядків |  59.01% | ETA 08:45

[4170/7050] ✓ NAD: 342 рядків |  59.15% | ETA 08:44

[4180/7050] ✓ NASA: 464 рядків |  59.29% | ETA 08:42

[4190/7050] ✓ NBIC: 13 рядків |  59.43% | ETA 08:40

[4200/7050] ✓ NBR: 195 рядків |  59.57% | ETA 08:39

   • RAM · 🧠 RAM: 445.1 MB

   ⏳ перед flush · 🧠 RAM: 445.1 MB

💾 batch 21030 → 13,626 рядків (всього 1,010,900 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21030.csv.gz

   ✅ після flush · 🧠 RAM: 445.1 MB

[4210/7050] ✓ NCMI: 235 рядків |  59.72% | ETA 08:38

[4220/7050] ✓ NDAQ: 420 рядків |  59.86% | ETA 08:36

[4230/7050] ✓ NEM: 577 рядків |  60.00% | ETA 08:34

[4240/7050] ✓ NEXA: 282 рядків |  60.14% | ETA 08:33

[4250/7050] ✓ NFTY: 8 рядків |  60.28% | ETA 08:31

   • RAM · 🧠 RAM: 437.2 MB

   ⏳ перед flush · 🧠 RAM: 437.2 MB

💾 batch 21031 → 11,084 рядків (всього 1,021,984 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21031.csv.gz

   ✅ після flush · 🧠 RAM: 439.6 MB

[4260/7050] ✓ NGVC: 80 рядків |  60.43% | ETA 08:30

[4270/7050] ✓ NIOG: 20 рядків |  60.57% | ETA 08:28

[4280/7050] ✓ NIXX: 156 рядків |  60.71% | ETA 08:27

[4290/7050] – NMCO/R: empty |  60.85% | ETA 08:25

[4300/7050] ✓ NN: 390 рядків |  60.99% | ETA 08:24

   • RAM · 🧠 RAM: 431.9 MB

   ⏳ перед flush · 🧠 RAM: 432.2 MB

💾 batch 21032 → 11,790 рядків (всього 1,033,774 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21032.csv.gz

   ✅ після flush · 🧠 RAM: 433.3 MB

[4310/7050] ✓ NOC: 400 рядків |  61.13% | ETA 08:22

[4320/7050] ✓ NOWL: 477 рядків |  61.28% | ETA 08:21

[4330/7050] ✓ NRGV: 395 рядків |  61.42% | ETA 08:19

[4340/7050] ✓ NSAI: 1 рядків |  61.56% | ETA 08:17

[4350/7050] ✓ NTAP: 373 рядків |  61.70% | ETA 08:16

   • RAM · 🧠 RAM: 429.2 MB

   ⏳ перед flush · 🧠 RAM: 429.2 MB

💾 batch 21033 → 12,108 рядків (всього 1,045,882 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21033.csv.gz

   ✅ після flush · 🧠 RAM: 430.5 MB

[4360/7050] ✓ NTRA: 366 рядків |  61.84% | ETA 08:14

[4370/7050] ✓ NUAI: 524 рядків |  61.99% | ETA 08:13

[4380/7050] ✓ NVAX: 445 рядків |  62.13% | ETA 08:11

[4390/7050] ✓ NVDW: 64 рядків |  62.27% | ETA 08:10

[4400/7050] – NVTC: empty |  62.41% | ETA 08:08

   • RAM · 🧠 RAM: 426.1 MB

   ⏳ перед flush · 🧠 RAM: 426.1 MB

💾 batch 21034 → 13,149 рядків (всього 1,059,031 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21034.csv.gz

   ✅ після flush · 🧠 RAM: 426.6 MB

[4410/7050] ✓ NVX: 24 рядків |  62.55% | ETA 08:07

[4420/7050] ✓ NWS: 388 рядків |  62.70% | ETA 08:05

[4430/7050] ✓ NXH: 588 рядків |  62.84% | ETA 08:03

[4440/7050] ✓ NYAX: 35 рядків |  62.98% | ETA 08:02

[4450/7050] ✓ O: 536 рядків |  63.12% | ETA 08:00

   • RAM · 🧠 RAM: 425.6 MB

   ⏳ перед flush · 🧠 RAM: 425.6 MB

💾 batch 21035 → 11,830 рядків (всього 1,070,861 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21035.csv.gz

   ✅ після flush · 🧠 RAM: 426.8 MB

[4460/7050] ✓ OCFC: 322 рядків |  63.26% | ETA 07:59

[4470/7050] ✓ OCUL: 379 рядків |  63.40% | ETA 07:57

[4480/7050] ✓ OGE: 387 рядків |  63.55% | ETA 07:55

[4490/7050] ✓ OII: 394 рядків |  63.69% | ETA 07:54

[4500/7050] ✓ OKTA: 452 рядків |  63.83% | ETA 07:52

   • RAM · 🧠 RAM: 427.7 MB

   ⏳ перед flush · 🧠 RAM: 427.7 MB

💾 batch 21036 → 11,316 рядків (всього 1,082,177 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21036.csv.gz

   ✅ після flush · 🧠 RAM: 427.9 MB

[4510/7050] ✓ OMAB: 91 рядків |  63.97% | ETA 07:51

[4520/7050] ✓ ONB: 391 рядків |  64.11% | ETA 07:49

[4530/7050] ✓ ONEG: 91 рядків |  64.26% | ETA 07:47

[4540/7050] ✓ ONTO: 359 рядків |  64.40% | ETA 07:46

[4550/7050] ✓ OPEN: 596 рядків |  64.54% | ETA 07:44

   • RAM · 🧠 RAM: 428.6 MB

   ⏳ перед flush · 🧠 RAM: 428.6 MB

💾 batch 21037 → 11,235 рядків (всього 1,093,412 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21037.csv.gz

   ✅ після flush · 🧠 RAM: 429.8 MB

[4560/7050] ✓ OPTH: 24 рядків |  64.68% | ETA 07:43

[4570/7050] ✓ OPTU: 397 рядків |  64.82% | ETA 07:41

[4580/7050] ✓ ORCX: 423 рядків |  64.96% | ETA 07:39

[4590/7050] ✓ ORN: 245 рядків |  65.11% | ETA 07:38

[4600/7050] ✓ OSW: 213 рядків |  65.25% | ETA 07:36

   • RAM · 🧠 RAM: 430.6 MB

   ⏳ перед flush · 🧠 RAM: 430.6 MB

💾 batch 21038 → 10,571 рядків (всього 1,103,983 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21038.csv.gz

   ✅ після flush · 🧠 RAM: 430.9 MB

[4610/7050] ✓ OTLY: 35 рядків |  65.39% | ETA 07:35

[4620/7050] ✓ OVV: 392 рядків |  65.53% | ETA 07:33

[4630/7050] ✓ OZK: 383 рядків |  65.67% | ETA 07:31

[4640/7050] ✓ PALD: 98 рядків |  65.82% | ETA 07:30

[4650/7050] ✓ PAPL: 42 рядків |  65.96% | ETA 07:28

   • RAM · 🧠 RAM: 432.1 MB

   ⏳ перед flush · 🧠 RAM: 432.1 MB

💾 batch 21039 → 12,451 рядків (всього 1,116,434 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21039.csv.gz

   ✅ після flush · 🧠 RAM: 433.0 MB

[4660/7050] ✓ PAVM: 44 рядків |  66.10% | ETA 07:27

[4670/7050] ✓ PAYS: 295 рядків |  66.24% | ETA 07:25

[4680/7050] ✓ PBM: 22 рядків |  66.38% | ETA 07:23

[4690/7050] ✓ PCLA: 20 рядків |  66.52% | ETA 07:21

[4700/7050] ✓ PD: 361 рядків |  66.67% | ETA 07:20

   • RAM · 🧠 RAM: 433.8 MB

   ⏳ перед flush · 🧠 RAM: 433.8 MB

💾 batch 21040 → 12,048 рядків (всього 1,128,482 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21040.csv.gz

   ✅ після flush · 🧠 RAM: 435.9 MB

[4710/7050] ✓ PDS: 129 рядків |  66.81% | ETA 07:18

[4720/7050] ✓ PEB: 386 рядків |  66.95% | ETA 07:17

[4730/7050] ✓ PERI: 197 рядків |  67.09% | ETA 07:15

[4740/7050] ✓ PFGC: 378 рядків |  67.23% | ETA 07:13

[4750/7050] ✓ PFSI: 249 рядків |  67.38% | ETA 07:12

   • RAM · 🧠 RAM: 436.7 MB

   ⏳ перед flush · 🧠 RAM: 436.7 MB

💾 batch 21041 → 12,096 рядків (всього 1,140,578 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21041.csv.gz

   ✅ після flush · 🧠 RAM: 438.3 MB

[4760/7050] ✓ PHAR: 24 рядків |  67.52% | ETA 07:10

[4770/7050] ✓ PHR: 263 рядків |  67.66% | ETA 07:08

[4780/7050] ✓ PIIIW: 2 рядків |  67.80% | ETA 07:07

[4790/7050] ✓ PKE: 161 рядків |  67.94% | ETA 07:05

[4800/7050] ✓ PLCE: 118 рядків |  68.09% | ETA 07:03

   • RAM · 🧠 RAM: 438.2 MB

   ⏳ перед flush · 🧠 RAM: 438.2 MB

💾 batch 21042 → 11,747 рядків (всього 1,152,325 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21042.csv.gz

   ✅ після flush · 🧠 RAM: 439.2 MB

[4810/7050] ✓ PLRZ: 29 рядків |  68.23% | ETA 07:02

[4820/7050] ✓ PLTZ: 491 рядків |  68.37% | ETA 07:00

[4830/7050] ✓ PLYY: 6 рядків |  68.51% | ETA 06:58

[4840/7050] ✓ PNBK: 57 рядків |  68.65% | ETA 06:57

[4850/7050] ✓ PNTG: 103 рядків |  68.79% | ETA 06:55

   • RAM · 🧠 RAM: 440.1 MB

   ⏳ перед flush · 🧠 RAM: 440.1 MB

💾 batch 21043 → 8,976 рядків (всього 1,161,301 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21043.csv.gz

   ✅ після flush · 🧠 RAM: 440.2 MB

[4860/7050] ✓ POMG: 180 рядків |  68.94% | ETA 06:53

[4870/7050] ✓ PPC: 331 рядків |  69.08% | ETA 06:52

[4880/7050] ✓ PPTA: 369 рядків |  69.22% | ETA 06:50

[4890/7050] ✓ PRFX: 41 рядків |  69.36% | ETA 06:48

[4900/7050] ✓ PRMB: 391 рядків |  69.50% | ETA 06:47

   • RAM · 🧠 RAM: 439.6 MB

   ⏳ перед flush · 🧠 RAM: 439.6 MB

💾 batch 21044 → 12,401 рядків (всього 1,173,702 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21044.csv.gz

   ✅ після flush · 🧠 RAM: 440.8 MB

[4910/7050] ✓ PRSO: 364 рядків |  69.65% | ETA 06:45

[4920/7050] ✓ PSFE: 193 рядків |  69.79% | ETA 06:43

[4930/7050] ✓ PSLV: 572 рядків |  69.93% | ETA 06:42

[4940/7050] ✓ PSUS: 125 рядків |  70.07% | ETA 06:40

[4950/7050] ✓ PTN: 84 рядків |  70.21% | ETA 06:38

   • RAM · 🧠 RAM: 441.7 MB

   ⏳ перед flush · 🧠 RAM: 441.7 MB

💾 batch 21045 → 10,665 рядків (всього 1,184,367 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21045.csv.gz

   ✅ після flush · 🧠 RAM: 442.9 MB

[4960/7050] ✓ PULM: 17 рядків |  70.35% | ETA 06:37

[4970/7050] ✓ PWB: 132 рядків |  70.50% | ETA 06:35

[4980/7050] ✓ PXF: 108 рядків |  70.64% | ETA 06:33

[4990/7050] ✓ PZZA: 371 рядків |  70.78% | ETA 06:31

[5000/7050] ✓ QCMD: 11 рядків |  70.92% | ETA 06:30

   • RAM · 🧠 RAM: 442.5 MB

   ⏳ перед flush · 🧠 RAM: 442.5 MB

💾 batch 21046 → 10,877 рядків (всього 1,195,244 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21046.csv.gz

   ✅ після flush · 🧠 RAM: 443.0 MB

[5010/7050] ✓ QDTE: 310 рядків |  71.06% | ETA 06:28

[5020/7050] ✓ QLD: 907 рядків |  71.21% | ETA 06:26

[5030/7050] ✓ QQA: 159 рядків |  71.35% | ETA 06:25

[5040/7050] ✓ QQQ: 1,161 рядків |  71.49% | ETA 06:23

[5050/7050] ✓ QSU: 67 рядків |  71.63% | ETA 06:21

   • RAM · 🧠 RAM: 443.9 MB

   ⏳ перед flush · 🧠 RAM: 443.9 MB

💾 batch 21047 → 11,736 рядків (всього 1,206,980 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21047.csv.gz

   ✅ після flush · 🧠 RAM: 444.9 MB

[5060/7050] ✓ QTUM: 231 рядків |  71.77% | ETA 06:19

[5070/7050] ✓ QXL: 35 рядків |  71.91% | ETA 06:18

[5080/7050] ✓ RAIN: 73 рядків |  72.06% | ETA 06:16

[5090/7050] ✓ RAPP: 383 рядків |  72.20% | ETA 06:14

[5100/7050] ✓ RC: 313 рядків |  72.34% | ETA 06:12

   • RAM · 🧠 RAM: 445.8 MB

   ⏳ перед flush · 🧠 RAM: 445.8 MB

💾 batch 21048 → 12,452 рядків (всього 1,219,432 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21048.csv.gz

   ✅ після flush · 🧠 RAM: 446.4 MB

[5110/7050] ✓ RCL: 424 рядків |  72.48% | ETA 06:11

[5120/7050] ✓ RDCM: 38 рядків |  72.62% | ETA 06:09

[5130/7050] ✓ RDYY: 23 рядків |  72.77% | ETA 06:07

[5140/7050] ✓ REBN: 32 рядків |  72.91% | ETA 06:06

[5150/7050] ✓ REK: 25 рядків |  73.05% | ETA 06:04

   • RAM · 🧠 RAM: 444.7 MB

   ⏳ перед flush · 🧠 RAM: 444.9 MB

💾 batch 21049 → 10,798 рядків (всього 1,230,230 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21049.csv.gz

   ✅ після flush · 🧠 RAM: 446.6 MB

[5160/7050] ✓ REPL: 390 рядків |  73.19% | ETA 06:02

[5170/7050] ✓ REZI: 310 рядків |  73.33% | ETA 06:00

[5180/7050] ✓ RGA: 248 рядків |  73.48% | ETA 05:59

[5190/7050] ✓ RGTI: 726 рядків |  73.62% | ETA 05:57

[5200/7050] ✓ RING: 195 рядків |  73.76% | ETA 05:55

   • RAM · 🧠 RAM: 447.2 MB

   ⏳ перед flush · 🧠 RAM: 447.4 MB

💾 batch 21050 → 12,105 рядків (всього 1,242,335 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21050.csv.gz

   ✅ після flush · 🧠 RAM: 448.5 MB

[5210/7050] ✓ RJF: 326 рядків |  73.90% | ETA 05:54

[5220/7050] ✓ RKTO: 109 рядків |  74.04% | ETA 05:52

[5230/7050] ✓ RMBX: 8 рядків |  74.18% | ETA 05:50

[5240/7050] ✓ RNA: 168 рядків |  74.33% | ETA 05:48

[5250/7050] ✓ ROBN: 312 рядків |  74.47% | ETA 05:47

   • RAM · 🧠 RAM: 449.3 MB

   ⏳ перед flush · 🧠 RAM: 449.3 MB

💾 batch 21051 → 12,016 рядків (всього 1,254,351 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21051.csv.gz

   ✅ після flush · 🧠 RAM: 449.5 MB

[5260/7050] ✓ ROIV: 402 рядків |  74.61% | ETA 05:45

[5270/7050] ✓ ROOT: 123 рядків |  74.75% | ETA 05:43

[5280/7050] ✓ RQI: 273 рядків |  74.89% | ETA 05:41

[5290/7050] ✓ RSPH: 166 рядків |  75.04% | ETA 05:40

[5300/7050] ✓ RTX: 422 рядків |  75.18% | ETA 05:38

   • RAM · 🧠 RAM: 450.3 MB

   ⏳ перед flush · 🧠 RAM: 450.3 MB

💾 batch 21052 → 11,558 рядків (всього 1,265,909 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21052.csv.gz

   ✅ після flush · 🧠 RAM: 451.6 MB

[5310/7050] ✓ RVII: 131 рядків |  75.32% | ETA 05:36

[5320/7050] ✓ RWR: 313 рядків |  75.46% | ETA 05:34

[5330/7050] ✓ RYAM: 297 рядків |  75.60% | ETA 05:33

[5340/7050] ✓ S: 457 рядків |  75.74% | ETA 05:31

[5350/7050] ✓ SAIA: 312 рядків |  75.89% | ETA 05:29

   • RAM · 🧠 RAM: 453.0 MB

   ⏳ перед flush · 🧠 RAM: 453.0 MB

💾 batch 21053 → 12,575 рядків (всього 1,278,484 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21053.csv.gz

   ✅ після flush · 🧠 RAM: 453.5 MB

[5360/7050] ✓ SAIQ: 1,106 рядків |  76.03% | ETA 05:27

[5370/7050] ✓ SBAC: 404 рядків |  76.17% | ETA 05:26

[5380/7050] ✓ SBR: 21 рядків |  76.31% | ETA 05:24

[5390/7050] ✓ SCHA: 381 рядків |  76.45% | ETA 05:22

[5400/7050] ✓ SCHK: 304 рядків |  76.60% | ETA 05:20

   • RAM · 🧠 RAM: 454.8 MB

   ⏳ перед flush · 🧠 RAM: 454.8 MB

💾 batch 21054 → 14,588 рядків (всього 1,293,072 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21054.csv.gz

   ✅ після flush · 🧠 RAM: 456.4 MB

[5410/7050] ✓ SCHR: 343 рядків |  76.74% | ETA 05:19

[5420/7050] ✓ SCNI: 68 рядків |  76.88% | ETA 05:17

[5430/7050] ✓ SDOT: 76 рядків |  77.02% | ETA 05:15

[5440/7050] ✓ SDEV: 1,062 рядків |  77.16% | ETA 05:13

[5450/7050] ✓ SEER: 134 рядків |  77.30% | ETA 05:11

   • RAM · 🧠 RAM: 450.8 MB

   ⏳ перед flush · 🧠 RAM: 450.8 MB

💾 batch 21055 → 13,073 рядків (всього 1,306,145 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21055.csv.gz

   ✅ після flush · 🧠 RAM: 450.9 MB

[5460/7050] ✓ SENS: 216 рядків |  77.45% | ETA 05:10

[5470/7050] ✓ SEZL: 362 рядків |  77.59% | ETA 05:08

[5480/7050] ✓ SFST: 51 рядків |  77.73% | ETA 05:06

[5490/7050] ✓ SGRX: 208 рядків |  77.87% | ETA 05:04

[5500/7050] ✓ SHC: 388 рядків |  78.01% | ETA 05:02

   • RAM · 🧠 RAM: 446.2 MB

   ⏳ перед flush · 🧠 RAM: 446.2 MB

💾 batch 21056 → 12,300 рядків (всього 1,318,445 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21056.csv.gz

   ✅ після flush · 🧠 RAM: 448.3 MB

[5510/7050] ✓ SHMD: 278 рядків |  78.16% | ETA 05:01

[5520/7050] ✓ SHV: 438 рядків |  78.30% | ETA 04:59

[5530/7050] ✓ SIGA: 204 рядків |  78.44% | ETA 04:57

[5540/7050] ✓ SINT: 12 рядків |  78.58% | ETA 04:55

[5550/7050] ✓ SIVR: 456 рядків |  78.72% | ETA 04:53

   • RAM · 🧠 RAM: 449.5 MB

   ⏳ перед flush · 🧠 RAM: 449.5 MB

💾 batch 21057 → 14,312 рядків (всього 1,332,757 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21057.csv.gz

   ✅ після flush · 🧠 RAM: 449.6 MB

[5560/7050] ✓ SKHZ: 323 рядків |  78.87% | ETA 04:52

[5570/7050] ✓ SKHY: 1,098 рядків |  79.01% | ETA 04:50

[5580/7050] ✓ SLAB: 157 рядків |  79.15% | ETA 04:48

[5590/7050] ✓ SLDP: 489 рядків |  79.29% | ETA 04:46

[5600/7050] – SLP: empty |  79.43% | ETA 04:44

   • RAM · 🧠 RAM: 449.8 MB

   ⏳ перед flush · 🧠 RAM: 449.8 MB

💾 batch 21058 → 13,236 рядків (всього 1,345,993 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21058.csv.gz

   ✅ після flush · 🧠 RAM: 450.7 MB

[5610/7050] ✓ SLVO: 141 рядків |  79.57% | ETA 04:43

[5620/7050] ✓ SMBS: 189 рядків |  79.72% | ETA 04:41

[5630/7050] ✓ SMHU: 22 рядків |  79.86% | ETA 04:39

[5640/7050] ✓ SMPL: 370 рядків |  80.00% | ETA 04:37

[5650/7050] ✓ SMU: 228 рядків |  80.14% | ETA 04:35

   • RAM · 🧠 RAM: 452.1 MB

   ⏳ перед flush · 🧠 RAM: 452.1 MB

💾 batch 21059 → 13,346 рядків (всього 1,359,339 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21059.csv.gz

   ✅ після flush · 🧠 RAM: 453.4 MB

[5660/7050] ✓ SNDA: 201 рядків |  80.28% | ETA 04:34

[5670/7050] ✓ SNDX: 369 рядків |  80.43% | ETA 04:32

[5680/7050] ✓ SNSC: 18 рядків |  80.57% | ETA 04:30

[5690/7050] ✓ SOEZ: 3 рядків |  80.71% | ETA 04:28

[5700/7050] ✓ SOFI: 826 рядків |  80.85% | ETA 04:26

   • RAM · 🧠 RAM: 450.3 MB

   ⏳ перед flush · 🧠 RAM: 450.3 MB

💾 batch 21060 → 14,564 рядків (всього 1,373,903 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21060.csv.gz

   ✅ після flush · 🧠 RAM: 451.6 MB

[5710/7050] ✓ SONY: 438 рядків |  80.99% | ETA 04:25

[5720/7050] ✓ SPAI: 115 рядків |  81.13% | ETA 04:23

[5730/7050] ✓ SPCF: 457 рядків |  81.28% | ETA 04:21

[5740/7050] ✓ SPGM: 90 рядків |  81.42% | ETA 04:19

[5750/7050] ✓ SPHD: 349 рядків |  81.56% | ETA 04:17

   • RAM · 🧠 RAM: 447.5 MB

   ⏳ перед flush · 🧠 RAM: 447.5 MB

💾 batch 21061 → 16,236 рядків (всього 1,390,139 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21061.csv.gz

   ✅ після flush · 🧠 RAM: 448.4 MB

[5760/7050] ✓ SPMD: 386 рядків |  81.70% | ETA 04:15

[5770/7050] ✓ SPRO: 152 рядків |  81.84% | ETA 04:13

[5780/7050] ✓ SPTB: 39 рядків |  81.99% | ETA 04:12

[5790/7050] ✓ SPUS: 312 рядків |  82.13% | ETA 04:10

[5800/7050] ✓ SPYD: 348 рядків |  82.27% | ETA 04:08

   • RAM · 🧠 RAM: 440.0 MB

   ⏳ перед flush · 🧠 RAM: 440.0 MB

💾 batch 21062 → 13,709 рядків (всього 1,403,848 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21062.csv.gz

   ✅ після flush · 🧠 RAM: 440.1 MB

[5810/7050] ✓ SRAD: 274 рядків |  82.41% | ETA 04:06

[5820/7050] ✓ SRTM: 80 рядків |  82.55% | ETA 04:04

[5830/7050] ✓ SSM: 76 рядків |  82.70% | ETA 04:02

[5840/7050] ✓ SSTK: 262 рядків |  82.84% | ETA 04:00

[5850/7050] ✓ STAK: 941 рядків |  82.98% | ETA 03:59

   • RAM · 🧠 RAM: 434.4 MB

   ⏳ перед flush · 🧠 RAM: 434.4 MB

💾 batch 21063 → 14,903 рядків (всього 1,418,751 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21063.csv.gz

   ✅ після flush · 🧠 RAM: 435.0 MB

[5860/7050] ✓ STK: 59 рядків |  83.12% | ETA 03:57

[5870/7050] ✓ STLN: 345 рядків |  83.26% | ETA 03:55

[5880/7050] ✓ STRK: 80 рядків |  83.40% | ETA 03:53

[5890/7050] ✓ STX: 681 рядків |  83.55% | ETA 03:51

[5900/7050] ✓ SUIG: 164 рядків |  83.69% | ETA 03:49

   • RAM · 🧠 RAM: 431.0 MB

   ⏳ перед flush · 🧠 RAM: 431.1 MB

💾 batch 21064 → 11,274 рядків (всього 1,430,025 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21064.csv.gz

   ✅ після flush · 🧠 RAM: 431.5 MB

[5910/7050] ✓ SUPV: 234 рядків |  83.83% | ETA 03:47

[5920/7050] ✓ SVRN: 72 рядків |  83.97% | ETA 03:45

[5930/7050] ✓ SWVLW: 4 рядків |  84.11% | ETA 03:43

[5940/7050] ✓ SYK: 396 рядків |  84.26% | ETA 03:42

[5950/7050] ✓ TAK: 361 рядків |  84.40% | ETA 03:40

   • RAM · 🧠 RAM: 432.5 MB

   ⏳ перед flush · 🧠 RAM: 432.5 MB

💾 batch 21065 → 13,223 рядків (всього 1,443,248 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21065.csv.gz

   ✅ після flush · 🧠 RAM: 434.4 MB

[5960/7050] ✓ TARS: 251 рядків |  84.54% | ETA 03:38

[5970/7050] ✓ TBLL: 106 рядків |  84.68% | ETA 03:36

[5980/7050] ✓ TCBK: 225 рядків |  84.82% | ETA 03:34

[5990/7050] ✓ TCRX: 217 рядків |  84.96% | ETA 03:32

[6000/7050] ✓ TDIV: 164 рядків |  85.11% | ETA 03:30

   • RAM · 🧠 RAM: 435.2 MB

   ⏳ перед flush · 🧠 RAM: 435.2 MB

💾 batch 21066 → 10,015 рядків (всього 1,453,263 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21066.csv.gz

   ✅ після flush · 🧠 RAM: 436.1 MB

[6010/7050] ✓ TEAM: 418 рядків |  85.25% | ETA 03:28

[6020/7050] ✓ TECX: 107 рядків |  85.39% | ETA 03:26

[6030/7050] ✓ TEUP: 18 рядків |  85.53% | ETA 03:25

[6040/7050] ✓ TFX: 228 рядків |  85.67% | ETA 03:23

[6050/7050] ✓ TGS: 166 рядків |  85.82% | ETA 03:21

   • RAM · 🧠 RAM: 437.1 MB

   ⏳ перед flush · 🧠 RAM: 437.1 MB

💾 batch 21067 → 12,023 рядків (всього 1,465,286 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21067.csv.gz

   ✅ після flush · 🧠 RAM: 437.4 MB

[6060/7050] ✓ THM: 256 рядків |  85.96% | ETA 03:19

[6070/7050] ✓ THW: 76 рядків |  86.10% | ETA 03:17

[6080/7050] ✓ TKNO: 302 рядків |  86.24% | ETA 03:15

[6090/7050] ✓ TLH: 413 рядків |  86.38% | ETA 03:13

[6100/7050] ✓ TLT: 814 рядків |  86.52% | ETA 03:11

   • RAM · 🧠 RAM: 438.5 MB

   ⏳ перед flush · 🧠 RAM: 438.5 MB

💾 batch 21068 → 10,684 рядків (всього 1,475,970 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21068.csv.gz

   ✅ після flush · 🧠 RAM: 440.0 MB

[6110/7050] ✓ TMGN: 118 рядків |  86.67% | ETA 03:09

[6120/7050] ✓ TMQ: 328 рядків |  86.81% | ETA 03:07

[6130/7050] ✓ TOON: 83 рядків |  86.95% | ETA 03:05

[6140/7050] ✓ TOST: 408 рядків |  87.09% | ETA 03:03

[6150/7050] ✓ TPL: 274 рядків |  87.23% | ETA 03:01

   • RAM · 🧠 RAM: 440.5 MB

   ⏳ перед flush · 🧠 RAM: 440.5 MB

💾 batch 21069 → 11,999 рядків (всього 1,487,969 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21069.csv.gz

   ✅ після flush · 🧠 RAM: 441.1 MB

[6160/7050] ✓ TRDA: 171 рядків |  87.38% | ETA 03:00

[6170/7050] ✓ TRN: 290 рядків |  87.52% | ETA 02:58

[6180/7050] ✓ TRON: 342 рядків |  87.66% | ETA 02:56

[6190/7050] ✓ TRVI: 281 рядків |  87.80% | ETA 02:54

[6200/7050] ✓ TSCO: 415 рядків |  87.94% | ETA 02:52

   • RAM · 🧠 RAM: 442.3 MB

   ⏳ перед flush · 🧠 RAM: 442.3 MB

💾 batch 21070 → 12,475 рядків (всього 1,500,444 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21070.csv.gz

   ✅ після flush · 🧠 RAM: 443.1 MB

[6210/7050] ✓ TSLG: 471 рядків |  88.09% | ETA 02:50

[6220/7050] ✓ TSLZ: 448 рядків |  88.23% | ETA 02:48

[6230/7050] ✓ TSN: 380 рядків |  88.37% | ETA 02:46

[6240/7050] ✓ TSYY: 26 рядків |  88.51% | ETA 02:44

[6250/7050] ✓ TTEC: 179 рядків |  88.65% | ETA 02:42

   • RAM · 🧠 RAM: 443.4 MB

   ⏳ перед flush · 🧠 RAM: 443.4 MB

💾 batch 21071 → 12,622 рядків (всього 1,513,066 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21071.csv.gz

   ✅ після flush · 🧠 RAM: 444.0 MB

[6260/7050] ✓ TUR: 169 рядків |  88.79% | ETA 02:40

[6270/7050] ✓ TWAV: 20 рядків |  88.94% | ETA 02:38

[6280/7050] ✓ TXG: 409 рядків |  89.08% | ETA 02:36

[6290/7050] ✓ TYGO: 294 рядків |  89.22% | ETA 02:34

[6300/7050] ✓ UAMY: 479 рядків |  89.36% | ETA 02:32

   • RAM · 🧠 RAM: 445.0 MB

   ⏳ перед flush · 🧠 RAM: 445.0 MB

💾 batch 21072 → 11,268 рядків (всього 1,524,334 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21072.csv.gz

   ✅ після flush · 🧠 RAM: 446.8 MB

[6310/7050] – UCYB: empty |  89.50% | ETA 02:30

[6320/7050] – UECG: empty |  89.65% | ETA 02:28

[6330/7050] ✓ UGA: 32 рядків |  89.79% | ETA 02:26

[6340/7050] ✓ UK: 6 рядків |  89.93% | ETA 02:24

[6350/7050] ✓ ULTY: 280 рядків |  90.07% | ETA 02:22

   • RAM · 🧠 RAM: 446.3 MB

   ⏳ перед flush · 🧠 RAM: 446.3 MB

💾 batch 21073 → 11,210 рядків (всього 1,535,544 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21073.csv.gz

   ✅ після flush · 🧠 RAM: 446.5 MB

[6360/7050] ✓ UNG: 726 рядків |  90.21% | ETA 02:20

[6370/7050] ✓ UONEK: 50 рядків |  90.35% | ETA 02:18

[6380/7050] ✓ UPRO: 633 рядків |  90.50% | ETA 02:16

[6390/7050] ✓ URTY: 209 рядків |  90.64% | ETA 02:14

[6400/7050] ✓ USB: 397 рядків |  90.78% | ETA 02:12

   • RAM · 🧠 RAM: 447.2 MB

   ⏳ перед flush · 🧠 RAM: 447.2 MB

💾 batch 21074 → 13,061 рядків (всього 1,548,605 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21074.csv.gz

   ✅ після flush · 🧠 RAM: 448.0 MB

[6410/7050] ✓ USHY: 385 рядків |  90.92% | ETA 02:11

[6420/7050] ✓ USNA: 156 рядків |  91.06% | ETA 02:09

[6430/7050] ✓ UTHR: 329 рядків |  91.21% | ETA 02:07

[6440/7050] ✓ UVE: 165 рядків |  91.35% | ETA 02:05

[6450/7050] ✓ UWM: 229 рядків |  91.49% | ETA 02:03

   • RAM · 🧠 RAM: 447.1 MB

   ⏳ перед flush · 🧠 RAM: 447.1 MB

💾 batch 21075 → 11,476 рядків (всього 1,560,081 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21075.csv.gz

   ✅ після flush · 🧠 RAM: 448.3 MB

[6460/7050] ✓ VAVX: 12 рядків |  91.63% | ETA 02:01

[6470/7050] ✓ VCR: 179 рядків |  91.77% | ETA 01:59

[6480/7050] ✓ VCSH: 388 рядків |  91.91% | ETA 01:57

[6490/7050] ✓ VEEV: 383 рядків |  92.06% | ETA 01:55

[6500/7050] ✓ VEU: 393 рядків |  92.20% | ETA 01:53

   • RAM · 🧠 RAM: 449.2 MB

   ⏳ перед flush · 🧠 RAM: 449.2 MB

💾 batch 21076 → 11,975 рядків (всього 1,572,056 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21076.csv.gz

   ✅ після flush · 🧠 RAM: 450.3 MB

[6510/7050] ✓ VGHY: 55 рядків |  92.34% | ETA 01:51

[6520/7050] ✓ VGZ: 364 рядків |  92.48% | ETA 01:49

[6530/7050] ✓ VIK: 395 рядків |  92.62% | ETA 01:47

[6540/7050] ✓ VIRT: 333 рядків |  92.77% | ETA 01:45

[6550/7050] ✓ VLGEA: 38 рядків |  92.91% | ETA 01:43

   • RAM · 🧠 RAM: 450.2 MB

   ⏳ перед flush · 🧠 RAM: 450.2 MB

💾 batch 21077 → 13,000 рядків (всього 1,585,056 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21077.csv.gz

   ✅ після flush · 🧠 RAM: 451.1 MB

[6560/7050] ✓ VMD: 123 рядків |  93.05% | ETA 01:41

[6570/7050] ✓ VNET: 398 рядків |  93.19% | ETA 01:39

[6580/7050] ✓ VNTG: 65 рядків |  93.33% | ETA 01:37

[6590/7050] ✓ VOT: 307 рядків |  93.48% | ETA 01:34

[6600/7050] ✓ VRAX: 32 рядків |  93.62% | ETA 01:32

   • RAM · 🧠 RAM: 451.7 MB

   ⏳ перед flush · 🧠 RAM: 451.7 MB

💾 batch 21078 → 13,498 рядків (всього 1,598,554 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21078.csv.gz

   ✅ після flush · 🧠 RAM: 453.3 MB

[6610/7050] ✓ VRT: 734 рядків |  93.76% | ETA 01:30

[6620/7050] – VSEE: empty |  93.90% | ETA 01:28

[6630/7050] ✓ VST: 612 рядків |  94.04% | ETA 01:26

[6640/7050] ✓ VTEB: 399 рядків |  94.18% | ETA 01:24

[6650/7050] ✓ VTIX: 129 рядків |  94.33% | ETA 01:22

   • RAM · 🧠 RAM: 454.4 MB

   ⏳ перед flush · 🧠 RAM: 454.4 MB

💾 batch 21079 → 12,339 рядків (всього 1,610,893 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21079.csv.gz

   ✅ після flush · 🧠 RAM: 456.4 MB

[6660/7050] ✓ VVX: 126 рядків |  94.47% | ETA 01:20

[6670/7050] ✓ VYMI: 365 рядків |  94.61% | ETA 01:18

[6680/7050] ✓ WAGN: 72 рядків |  94.75% | ETA 01:16

[6690/7050] ✓ WAT: 383 рядків |  94.89% | ETA 01:14

[6700/7050] ✓ WCBR: 215 рядків |  95.04% | ETA 01:12

   • RAM · 🧠 RAM: 457.0 MB

   ⏳ перед flush · 🧠 RAM: 457.0 MB

💾 batch 21080 → 12,137 рядків (всього 1,623,030 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21080.csv.gz

   ✅ після flush · 🧠 RAM: 457.7 MB

[6710/7050] ✓ WDH: 48 рядків |  95.18% | ETA 01:10

[6720/7050] ✓ WEC: 390 рядків |  95.32% | ETA 01:08

[6730/7050] ✓ WEYS: 16 рядків |  95.46% | ETA 01:06

[6740/7050] ✓ WHF: 52 рядків |  95.60% | ETA 01:04

[6750/7050] ✓ WKHS: 50 рядків |  95.74% | ETA 01:02

   • RAM · 🧠 RAM: 458.7 MB

   ⏳ перед flush · 🧠 RAM: 458.7 MB

💾 batch 21081 → 13,338 рядків (всього 1,636,368 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21081.csv.gz

   ✅ після flush · 🧠 RAM: 460.0 MB

[6760/7050] ✓ WLK: 352 рядків |  95.89% | ETA 01:00

[6770/7050] ✓ WNC: 277 рядків |  96.03% | ETA 00:58

[6780/7050] ✓ WRBY: 361 рядків |  96.17% | ETA 00:56

[6790/7050] ✓ WSC: 385 рядків |  96.31% | ETA 00:54

[6800/7050] ✓ WTAI: 134 рядків |  96.45% | ETA 00:52

   • RAM · 🧠 RAM: 459.4 MB

   ⏳ перед flush · 🧠 RAM: 459.4 MB

💾 batch 21082 → 12,759 рядків (всього 1,649,127 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21082.csv.gz

   ✅ після flush · 🧠 RAM: 460.3 MB

[6810/7050] ✓ WTW: 356 рядків |  96.60% | ETA 00:50

[6820/7050] ✓ WYFI: 429 рядків |  96.74% | ETA 00:48

[6830/7050] ✓ WYNN: 417 рядків |  96.88% | ETA 00:45

[6840/7050] ✓ XBTY: 15 рядків |  97.02% | ETA 00:43

[6850/7050] ✓ XELB: 29 рядків |  97.16% | ETA 00:41

   • RAM · 🧠 RAM: 458.2 MB

   ⏳ перед flush · 🧠 RAM: 458.2 MB

💾 batch 21083 → 9,230 рядків (всього 1,658,357 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21083.csv.gz

   ✅ після flush · 🧠 RAM: 459.2 MB

[6860/7050] ✓ XHB: 391 рядків |  97.30% | ETA 00:39

[6870/7050] ✓ XLP: 482 рядків |  97.45% | ETA 00:37

[6880/7050] ✓ XLVI: 62 рядків |  97.59% | ETA 00:35

[6890/7050] ✓ XNTK: 160 рядків |  97.73% | ETA 00:33

[6900/7050] ✓ XPAY: 63 рядків |  97.87% | ETA 00:31

   • RAM · 🧠 RAM: 459.7 MB

   ⏳ перед flush · 🧠 RAM: 459.7 MB

💾 batch 21084 → 14,819 рядків (всього 1,673,176 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21084.csv.gz

   ✅ після flush · 🧠 RAM: 460.4 MB

[6910/7050] ✓ XQQI: 203 рядків |  98.01% | ETA 00:29

[6920/7050] ✓ XRPN: 232 рядків |  98.16% | ETA 00:27

[6930/7050] ✓ XSOE: 70 рядків |  98.30% | ETA 00:25

[6940/7050] ✓ XTND: 338 рядків |  98.44% | ETA 00:23

[6950/7050] ✓ XYLG: 19 рядків |  98.58% | ETA 00:21

   • RAM · 🧠 RAM: 457.8 MB

   ⏳ перед flush · 🧠 RAM: 457.8 MB

💾 batch 21085 → 7,891 рядків (всього 1,681,067 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21085.csv.gz

   ✅ після flush · 🧠 RAM: 457.8 MB

[6960/7050] ✓ YCS: 7 рядків |  98.72% | ETA 00:18

[6970/7050] ✓ YJ: 80 рядків |  98.87% | ETA 00:16

[6980/7050] ✓ YOLO: 20 рядків |  99.01% | ETA 00:14

[6990/7050] ✓ YSPY: 3 рядків |  99.15% | ETA 00:12

[7000/7050] ✓ ZAP: 165 рядків |  99.29% | ETA 00:10

   • RAM · 🧠 RAM: 457.0 MB

   ⏳ перед flush · 🧠 RAM: 457.0 MB

💾 batch 21086 → 10,350 рядків (всього 1,691,417 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21086.csv.gz

   ✅ після flush · 🧠 RAM: 458.7 MB

[7010/7050] ✓ ZD: 211 рядків |  99.43% | ETA 00:08

[7020/7050] ✓ ZG: 335 рядків |  99.57% | ETA 00:06

[7030/7050] ✓ ZNTL: 289 рядків |  99.72% | ETA 00:04

[7040/7050] ✓ ZTG: 281 рядків |  99.86% | ETA 00:02

[7050/7050] ✓ ZYME: 325 рядків | 100.00% | ETA 00:00

   • RAM · 🧠 RAM: 458.2 MB

   ⏳ перед flush · 🧠 RAM: 458.2 MB

💾 batch 21087 → 11,160 рядків (всього 1,702,577 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_21087.csv.gz

   ✅ після flush · 🧠 RAM: 459.5 MB

   🔚 фінал · 🧠 RAM: 459.2 MB

🏁 Готово. Нових рядків: 1,702,577 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 24:49

In [19]:
# ================== FAST LOCAL POST-PROCESSING (no API calls) ==================
# Читання батчів робить pyarrow (нативний багатопотоковий CSV-парсер) замість
# pandas.read_csv, а premarket-фільтр і денні open/close рахуються за ОДИН прохід
# по gz-файлах замість двох.
import os, gc, glob, time, threading
from typing import Optional, List, Tuple

import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.csv as pacsv
import pyarrow.compute as pc
import pyarrow.dataset as pads
from concurrent.futures import ThreadPoolExecutor

_INTRADAY_COLS = ["ticker", "dt", "o", "h", "l", "c", "v"]

# Парсимо у float64, щоб денні open/close збігалися з попередньою (pandas) реалізацією
# біт у біт; premarket-рядки перед записом кастимо назад у float32 — стара схема на диску.
_INTRADAY_TYPES = {
    "ticker": pa.string(), "dt": pa.string(),
    "o": pa.float64(), "h": pa.float64(), "l": pa.float64(),
    "c": pa.float64(), "v": pa.float64(),
}
_PREMARKET_SCHEMA = pa.schema([
    ("ticker", pa.string()), ("dt", pa.string()),
    ("o", pa.float32()), ("h", pa.float32()), ("l", pa.float32()),
    ("c", pa.float32()), ("v", pa.float32()),
])


# ---------- спільні хелпери для мерджів по тікеру (використовують клітинки 28/40/44) ----------
def _ticker_codes(s: pd.Series):
    """Факторизує колонку тікерів і нормалізує (strip+upper) ЛИШЕ унікальні значення.

    Повертає (codes, categories); codes[i] == -1 означає null. Сенс у тому, щоб
    strip/upper і словниковий пошук виконувались над ~10^3 унікальними тікерами,
    а не над ~10^6 рядками батча.
    """
    cat = s.astype("category")
    cats = pd.Index(cat.cat.categories.astype(str)).str.strip().str.upper()
    return cat.cat.codes.to_numpy(), cats


def _expand(values: np.ndarray, codes: np.ndarray, fill):
    """Розгортає масив «на категорію» назад «на рядок»; де codes == -1 ставить fill."""
    out = np.empty(codes.shape, dtype=values.dtype if values.dtype != object else object)
    valid = codes >= 0
    out[valid] = values[codes[valid]]
    if (~valid).any():
        out[~valid] = fill
    return out


def _map_by_ticker(codes: np.ndarray, cats: pd.Index, mapping: dict, numeric: bool):
    vals = cats.map(mapping)
    if numeric:
        vals = pd.to_numeric(pd.Series(vals), errors="coerce").to_numpy(dtype="float64")
        return _expand(vals, codes, np.nan)
    vals = np.asarray(pd.Series(vals).astype(object).to_numpy(), dtype=object)
    return _expand(vals, codes, None)


# ---------- читання intraday-батчів ----------
def _open_intraday_csv(path: str, block_size: int):
    return pacsv.open_csv(
        path,
        read_options=pacsv.ReadOptions(use_threads=True, block_size=block_size),
        convert_options=pacsv.ConvertOptions(
            include_columns=_INTRADAY_COLS, column_types=_INTRADAY_TYPES
        ),
    )


def _time_date_mask(dt_arr, start_time, end_time, date_min, date_max):
    t = pc.utf8_slice_codeunits(dt_arr, 11, 19)
    mask = pc.and_(pc.greater_equal(t, start_time), pc.less_equal(t, end_time))
    if date_min is not None or date_max is not None:
        d = pc.utf8_slice_codeunits(dt_arr, 0, 10)
        if date_min is not None:
            mask = pc.and_(mask, pc.greater_equal(d, date_min))
        if date_max is not None:
            mask = pc.and_(mask, pc.less_equal(d, date_max))
    return mask


def _oc_from_table(tbl: pa.Table) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Перший open у вікні 09:30–09:35 і останній close у 15:55–15:59 на (ticker, date)."""
    OPEN_FROM, OPEN_TO = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    hhmm = pc.utf8_slice_codeunits(tbl.column("dt"), 11, 16)
    m_o = pc.and_(pc.and_(pc.greater_equal(hhmm, OPEN_FROM), pc.less_equal(hhmm, OPEN_TO)),
                  pc.is_valid(tbl.column("o")))
    m_c = pc.and_(pc.and_(pc.greater_equal(hhmm, CLOSE_FROM), pc.less_equal(hhmm, CLOSE_TO)),
                  pc.is_valid(tbl.column("c")))

    def _reduce(mask, val_col, keep):
        sub = tbl.select(["ticker", "dt", val_col]).filter(mask)
        if sub.num_rows == 0:
            return pd.DataFrame(columns=["ticker", "date", "dt", val_col])
        d = sub.to_pandas()
        d["date"] = d["dt"].str.slice(0, 10)
        d = d.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep=keep)
        return d[["ticker", "date", "dt", val_col]]

    return _reduce(m_o, "o", "first"), _reduce(m_c, "c", "last")


def _finalize_oc(open_parts: List[pd.DataFrame], close_parts: List[pd.DataFrame]) -> pd.DataFrame:
    opens = (pd.concat(open_parts, ignore_index=True) if open_parts
             else pd.DataFrame(columns=["ticker", "date", "dt", "o"]))
    closes = (pd.concat(close_parts, ignore_index=True) if close_parts
              else pd.DataFrame(columns=["ticker", "date", "dt", "c"]))
    if len(opens):
        opens = opens.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="first")
    if len(closes):
        closes = closes.sort_values("dt", kind="stable").drop_duplicates(["ticker", "date"], keep="last")
    opens = opens[["ticker", "date", "o"]].rename(columns={"o": "open"})
    closes = closes[["ticker", "date", "c"]].rename(columns={"c": "close"})

    out = (opens.merge(closes, on=["ticker", "date"], how="outer")
                .sort_values(["ticker", "date"], kind="stable").reset_index(drop=True))
    out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)
    return out


def collect_premarket_and_oc(
    folder: str,
    out_path: str,
    oc_out_path: Optional[str] = None,
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    build_oc: bool = True,
    max_workers: int = 4,
    block_size: int = 64 << 20,
    compression: str = "snappy",
    sort_chunk: bool = True,
    verbose: bool = True,
):
    """ОДИН прохід по {folder}/{pattern}: пише відфільтровані рядки у out_path і
    (опційно) денні open/close у oc_out_path.

    Замінює пару collect_premarket_by_day_stream + build_oc_from_intraday_folder,
    які раніше читали й розтискали ті самі gz-файли двічі.

    Порядок рядків МІЖ файлами недетермінований (файли читаються паралельно).
    Це безпечно: усі наступні кроки — мерджі по ключах, а фінальний файл
    фізично сортується у клітинці 47. Для точного старого порядку — max_workers=1.
    """
    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    if os.path.exists(out_path):
        os.remove(out_path)

    t0 = time.time()
    lock = threading.Lock()
    state = {"writer": None, "in": 0, "out": 0, "files": 0}
    open_parts: List[pd.DataFrame] = []
    close_parts: List[pd.DataFrame] = []

    def _handle(path: str):
        reader = _open_intraday_csv(path, block_size)
        loc_open, loc_close = [], []
        n_in = n_out = 0
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            tbl = pa.Table.from_batches([rb])
            n_in += tbl.num_rows

            if build_oc:
                o_df, c_df = _oc_from_table(tbl)
                if len(o_df):
                    loc_open.append(o_df)
                if len(c_df):
                    loc_close.append(c_df)

            cut = tbl.filter(_time_date_mask(tbl.column("dt"), start_time, end_time,
                                             date_min, date_max))
            if cut.num_rows:
                cut = cut.cast(_PREMARKET_SCHEMA)
                if sort_chunk:
                    cut = cut.sort_by([("ticker", "ascending"), ("dt", "ascending")])
                n_out += cut.num_rows
                with lock:
                    if state["writer"] is None:
                        state["writer"] = pq.ParquetWriter(out_path, cut.schema,
                                                           compression=compression)
                    state["writer"].write_table(cut)

        with lock:
            state["in"] += n_in
            state["out"] += n_out
            state["files"] += 1
            open_parts.extend(loc_open)
            close_parts.extend(loc_close)
            if verbose:
                print(f"  [{state['files']}/{len(files)}] {os.path.basename(path)}  "
                      f"in={state['in']:,} out={state['out']:,} "
                      f"elapsed={time.time()-t0:,.1f}s", flush=True)

    rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]" if (date_min or date_max) else ""
    if verbose:
        print(f"▶️ START: {folder}/{pattern} → {out_path}  files={len(files)} "
              f"workers={max_workers}{rng_str}", flush=True)
    try:
        if max_workers and max_workers > 1:
            with ThreadPoolExecutor(max_workers=max_workers) as ex:
                list(ex.map(_handle, files))
        else:
            for p in files:
                _handle(p)
    finally:
        if state["writer"] is not None:
            state["writer"].close()

    df_oc = None
    if build_oc:
        df_oc = _finalize_oc(open_parts, close_parts)
        if oc_out_path:
            os.makedirs(os.path.dirname(oc_out_path) or ".", exist_ok=True)
            df_oc.to_parquet(oc_out_path, index=False)

    if verbose:
        print(f"✅ DONE  in={state['in']:,} → out={state['out']:,}  to {out_path}  "
              f"in {time.time()-t0:,.1f}s", flush=True)
    return out_path, df_oc


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str = "23:59:00",
    *,
    date_min: Optional[str] = None,
    date_max: Optional[str] = None,
    aggregate: bool = False,
    chunksize: int = 200_000,          # лишено для сумісності виклику; pyarrow керує блоками сам
    compression: str = "snappy",
    log_every: int = 5,                # лишено для сумісності виклику
    sort_chunk: bool = True,
    max_workers: int = 4,
    verbose: bool = True,
):
    """Тонка обгортка над collect_premarket_and_oc (build_oc=False) — щоб старі
    виклики працювали без змін."""
    if aggregate:
        raise NotImplementedError("aggregate=True у цьому пайплайні не використовується")
    path, _ = collect_premarket_and_oc(
        folder, out_path, oc_out_path=None, pattern=pattern,
        start_time=start_time, end_time=end_time,
        date_min=date_min, date_max=date_max, build_oc=False,
        max_workers=max_workers, compression=compression,
        sort_chunk=sort_chunk, verbose=verbose,
    )
    return path

In [20]:
# Один прохід по gz-батчах: одразу і premarket-рядки, і денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,
    date_max=end_date_str,
    build_oc=True,
    max_workers=4,
)
print(df_oc.head())

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  files=21087 workers=4  date=[2026-07-24..2026-10-24]

  [1/21087] intraday_0004.csv.gz  in=743,028 out=0 elapsed=0.7s

  [2/21087] intraday_0003.csv.gz  in=1,470,913 out=0 elapsed=0.7s

  [3/21087] intraday_0002.csv.gz  in=2,357,625 out=0 elapsed=0.8s

  [4/21087] intraday_0001.csv.gz  in=3,333,452 out=0 elapsed=0.8s

  [5/21087] intraday_0005.csv.gz  in=4,207,443 out=0 elapsed=1.3s

  [6/21087] intraday_0007.csv.gz  in=4,968,024 out=0 elapsed=1.3s

  [7/21087] intraday_0008.csv.gz  in=5,777,588 out=0 elapsed=1.3s

  [8/21087] intraday_0006.csv.gz  in=6,732,671 out=0 elapsed=1.4s

  [9/21087] intraday_0011.csv.gz  in=7,471,310 out=0 elapsed=1.8s

  [10/21087] intraday_0010.csv.gz  in=8,408,898 out=0 elapsed=1.9s

  [11/21087] intraday_0009.csv.gz  in=9,348,724 out=0 elapsed=2.0s

  [12/21087] intraday_0012.csv.gz  in=10,202,410 out=0 elapsed=2.0s

  [13/21087] intraday_0015.csv.gz  in=10,806,484 out=0 elapsed=2.4s

  [14/21087] intraday_0014.csv.gz  in=11,471,803 out=0 elapsed=2.4s

  [15/21087] intraday_0013.csv.gz  in=12,333,647 out=0 elapsed=2.4s

  [16/21087] intraday_0016.csv.gz  in=13,369,434 out=0 elapsed=2.6s

  [17/21087] intraday_0018.csv.gz  in=14,058,532 out=0 elapsed=2.8s

  [18/21087] intraday_0019.csv.gz  in=14,795,001 out=0 elapsed=2.9s

  [19/21087] intraday_0017.csv.gz  in=15,723,943 out=0 elapsed=3.0s

  [20/21087] intraday_0020.csv.gz  in=16,555,781 out=0 elapsed=3.1s

  [21/21087] intraday_0022.csv.gz  in=17,287,747 out=0 elapsed=3.4s

  [22/21087] intraday_0021.csv.gz  in=18,114,555 out=0 elapsed=3.4s

  [23/21087] intraday_0023.csv.gz  in=18,895,557 out=0 elapsed=3.5s

  [24/21087] intraday_0024.csv.gz  in=19,686,597 out=0 elapsed=3.6s

  [25/21087] intraday_0025.csv.gz  in=20,416,242 out=0 elapsed=3.8s

  [26/21087] intraday_0027.csv.gz  in=21,080,210 out=0 elapsed=3.9s

  [27/21087] intraday_0026.csv.gz  in=21,935,669 out=0 elapsed=3.9s

  [28/21087] intraday_0028.csv.gz  in=22,943,087 out=0 elapsed=4.2s

  [29/21087] intraday_0031.csv.gz  in=23,677,097 out=0 elapsed=4.4s

  [30/21087] intraday_0029.csv.gz  in=24,623,614 out=0 elapsed=4.4s

  [31/21087] intraday_0030.csv.gz  in=25,543,444 out=0 elapsed=4.5s

  [32/21087] intraday_0032.csv.gz  in=26,359,346 out=0 elapsed=4.7s

  [33/21087] intraday_0034.csv.gz  in=27,046,628 out=0 elapsed=4.9s

  [34/21087] intraday_0033.csv.gz  in=27,922,589 out=0 elapsed=5.0s

  [35/21087] intraday_0035.csv.gz  in=28,741,745 out=0 elapsed=5.0s

  [36/21087] intraday_0037.csv.gz  in=29,414,856 out=0 elapsed=7.0s

  [37/21087] intraday_0038.csv.gz  in=30,104,913 out=0 elapsed=7.0s

  [38/21087] intraday_0039.csv.gz  in=30,864,424 out=0 elapsed=7.1s

  [39/21087] intraday_0036.csv.gz  in=31,684,289 out=0 elapsed=7.1s

  [40/21087] intraday_0040.csv.gz  in=32,407,718 out=0 elapsed=7.5s

  [41/21087] intraday_0043.csv.gz  in=33,119,568 out=0 elapsed=7.6s

  [42/21087] intraday_0041.csv.gz  in=34,013,644 out=0 elapsed=7.6s

  [43/21087] intraday_0042.csv.gz  in=34,960,739 out=0 elapsed=7.7s

  [44/21087] intraday_0044.csv.gz  in=35,766,274 out=0 elapsed=8.0s

  [45/21087] intraday_0045.csv.gz  in=36,568,713 out=0 elapsed=8.1s

  [46/21087] intraday_0046.csv.gz  in=37,383,804 out=0 elapsed=8.2s

  [47/21087] intraday_0047.csv.gz  in=38,250,311 out=0 elapsed=8.3s

  [48/21087] intraday_0048.csv.gz  in=38,906,436 out=0 elapsed=8.4s

  [49/21087] intraday_0049.csv.gz  in=39,851,960 out=0 elapsed=8.7s

  [50/21087] intraday_0050.csv.gz  in=40,684,592 out=0 elapsed=8.7s

  [51/21087] intraday_0051.csv.gz  in=41,414,383 out=0 elapsed=8.8s

  [52/21087] intraday_0052.csv.gz  in=42,279,351 out=0 elapsed=9.0s

  [53/21087] intraday_0053.csv.gz  in=42,998,896 out=0 elapsed=9.2s

  [54/21087] intraday_0054.csv.gz  in=43,729,514 out=0 elapsed=9.2s

  [55/21087] intraday_0055.csv.gz  in=44,542,383 out=0 elapsed=9.3s

  [56/21087] intraday_0056.csv.gz  in=45,360,329 out=0 elapsed=9.5s

  [57/21087] intraday_0057.csv.gz  in=46,118,655 out=0 elapsed=9.7s

  [58/21087] intraday_0058.csv.gz  in=46,830,377 out=0 elapsed=9.7s

  [59/21087] intraday_0059.csv.gz  in=47,587,522 out=0 elapsed=9.7s

  [60/21087] intraday_0060.csv.gz  in=48,264,439 out=0 elapsed=9.9s

  [61/21087] intraday_0062.csv.gz  in=49,011,023 out=0 elapsed=10.2s

  [62/21087] intraday_0061.csv.gz  in=50,022,323 out=0 elapsed=10.3s

  [63/21087] intraday_0063.csv.gz  in=50,975,856 out=0 elapsed=10.4s

  [64/21087] intraday_0064.csv.gz  in=51,861,073 out=0 elapsed=10.5s

  [65/21087] intraday_0065.csv.gz  in=52,657,022 out=0 elapsed=10.7s

  [66/21087] intraday_0066.csv.gz  in=53,344,110 out=0 elapsed=10.8s

  [67/21087] intraday_0067.csv.gz  in=54,114,222 out=0 elapsed=10.9s

  [68/21087] intraday_0068.csv.gz  in=54,938,820 out=0 elapsed=11.0s

  [69/21087] intraday_0070.csv.gz  in=55,597,571 out=0 elapsed=11.2s

  [70/21087] intraday_0069.csv.gz  in=56,497,048 out=0 elapsed=11.3s

  [71/21087] intraday_0071.csv.gz  in=57,135,058 out=0 elapsed=11.3s

  [72/21087] intraday_0072.csv.gz  in=57,879,667 out=0 elapsed=11.5s

  [73/21087] intraday_0073.csv.gz  in=58,674,810 out=0 elapsed=11.7s

  [74/21087] intraday_0074.csv.gz  in=59,409,405 out=0 elapsed=11.7s

  [75/21087] intraday_0075.csv.gz  in=60,167,330 out=0 elapsed=11.8s

  [76/21087] intraday_0076.csv.gz  in=60,866,670 out=0 elapsed=11.9s

  [77/21087] intraday_0077.csv.gz  in=61,676,095 out=0 elapsed=12.2s

  [78/21087] intraday_0080.csv.gz  in=62,376,615 out=0 elapsed=12.4s

  [79/21087] intraday_0079.csv.gz  in=63,295,220 out=0 elapsed=12.4s

  [80/21087] intraday_0078.csv.gz  in=64,355,814 out=0 elapsed=12.4s

  [81/21087] intraday_0081.csv.gz  in=65,173,353 out=0 elapsed=12.7s

  [82/21087] intraday_0082.csv.gz  in=65,962,271 out=0 elapsed=12.9s

  [83/21087] intraday_0083.csv.gz  in=66,748,390 out=0 elapsed=12.9s

  [84/21087] intraday_0084.csv.gz  in=67,918,886 out=0 elapsed=13.2s

  [85/21087] intraday_0085.csv.gz  in=68,693,048 out=0 elapsed=13.2s

  [86/21087] intraday_0086.csv.gz  in=69,620,846 out=0 elapsed=13.4s

  [87/21087] intraday_0087.csv.gz  in=70,564,187 out=0 elapsed=13.5s

  [88/21087] intraday_0088.csv.gz  in=71,397,243 out=0 elapsed=13.7s

  [89/21087] intraday_0089.csv.gz  in=72,281,904 out=0 elapsed=13.8s

  [90/21087] intraday_0090.csv.gz  in=73,069,473 out=0 elapsed=13.9s

  [91/21087] intraday_0091.csv.gz  in=73,999,201 out=0 elapsed=14.1s

  [92/21087] intraday_0092.csv.gz  in=74,831,839 out=0 elapsed=14.2s

  [93/21087] intraday_0093.csv.gz  in=75,647,498 out=0 elapsed=14.3s

  [94/21087] intraday_0094.csv.gz  in=76,528,738 out=0 elapsed=14.5s

  [95/21087] intraday_0095.csv.gz  in=77,378,774 out=0 elapsed=14.6s

  [96/21087] intraday_0096.csv.gz  in=78,260,543 out=0 elapsed=14.7s

  [97/21087] intraday_0097.csv.gz  in=79,032,923 out=0 elapsed=14.8s

  [98/21087] intraday_0098.csv.gz  in=79,802,827 out=0 elapsed=15.0s

  [99/21087] intraday_0099.csv.gz  in=80,863,945 out=0 elapsed=15.2s

  [100/21087] intraday_0100.csv.gz  in=81,661,660 out=0 elapsed=15.2s

  [101/21087] intraday_0101.csv.gz  in=82,593,388 out=0 elapsed=15.3s

  [102/21087] intraday_0102.csv.gz  in=83,527,121 out=0 elapsed=15.5s

  [103/21087] intraday_0103.csv.gz  in=84,317,945 out=0 elapsed=15.8s

  [104/21087] intraday_0104.csv.gz  in=85,159,844 out=0 elapsed=15.8s

  [105/21087] intraday_0105.csv.gz  in=86,032,104 out=0 elapsed=15.9s

  [106/21087] intraday_0106.csv.gz  in=86,821,848 out=0 elapsed=16.0s

  [107/21087] intraday_0108.csv.gz  in=87,616,449 out=0 elapsed=16.3s

  [108/21087] intraday_0107.csv.gz  in=88,679,847 out=0 elapsed=16.4s

  [109/21087] intraday_0109.csv.gz  in=89,619,231 out=0 elapsed=16.5s

  [110/21087] intraday_0110.csv.gz  in=90,640,909 out=0 elapsed=16.6s

  [111/21087] intraday_0111.csv.gz  in=91,427,941 out=0 elapsed=16.8s

  [112/21087] intraday_0112.csv.gz  in=92,259,949 out=0 elapsed=16.9s

  [113/21087] intraday_0113.csv.gz  in=93,022,660 out=0 elapsed=17.0s

  [114/21087] intraday_0114.csv.gz  in=93,859,984 out=0 elapsed=17.2s

  [115/21087] intraday_0115.csv.gz  in=94,616,153 out=0 elapsed=17.3s

  [116/21087] intraday_0117.csv.gz  in=95,401,469 out=0 elapsed=17.5s

  [117/21087] intraday_0116.csv.gz  in=96,350,237 out=0 elapsed=17.5s

  [118/21087] intraday_0119.csv.gz  in=97,075,034 out=0 elapsed=17.7s

  [119/21087] intraday_0118.csv.gz  in=98,245,742 out=0 elapsed=17.9s

  [120/21087] intraday_0120.csv.gz  in=99,105,343 out=0 elapsed=18.0s

  [121/21087] intraday_0121.csv.gz  in=100,150,376 out=0 elapsed=18.2s

  [122/21087] intraday_0122.csv.gz  in=100,938,876 out=0 elapsed=18.2s

  [123/21087] intraday_0123.csv.gz  in=101,790,604 out=0 elapsed=18.5s

  [124/21087] intraday_0124.csv.gz  in=102,767,055 out=0 elapsed=18.6s

  [125/21087] intraday_0125.csv.gz  in=103,648,833 out=0 elapsed=18.8s

  [126/21087] intraday_0126.csv.gz  in=104,596,744 out=0 elapsed=18.8s

  [127/21087] intraday_0127.csv.gz  in=105,314,012 out=0 elapsed=18.9s

  [128/21087] intraday_0128.csv.gz  in=106,066,285 out=0 elapsed=19.1s

  [129/21087] intraday_0129.csv.gz  in=106,926,182 out=0 elapsed=19.3s

  [130/21087] intraday_0130.csv.gz  in=107,748,465 out=0 elapsed=19.4s

  [131/21087] intraday_0131.csv.gz  in=108,503,257 out=0 elapsed=19.4s

  [132/21087] intraday_0135.csv.gz  in=108,519,615 out=0 elapsed=19.5s

  [133/21087] intraday_0134.csv.gz  in=108,567,766 out=0 elapsed=19.5s

  [134/21087] intraday_0136.csv.gz  in=108,586,456 out=0 elapsed=19.5s

  [135/21087] intraday_0137.csv.gz  in=108,598,507 out=0 elapsed=19.5s

  [136/21087] intraday_0138.csv.gz  in=108,611,037 out=0 elapsed=19.5s

  [137/21087] intraday_0139.csv.gz  in=108,624,721 out=0 elapsed=19.5s

  [138/21087] intraday_0132.csv.gz  in=109,286,997 out=0 elapsed=19.5s

  [139/21087] intraday_0140.csv.gz  in=109,301,904 out=0 elapsed=19.5s

  [140/21087] intraday_0141.csv.gz  in=109,314,490 out=0 elapsed=19.5s

  [141/21087] intraday_0142.csv.gz  in=109,328,468 out=0 elapsed=19.5s

  [142/21087] intraday_0143.csv.gz  in=109,343,799 out=0 elapsed=19.6s

  [143/21087] intraday_0145.csv.gz  in=109,359,005 out=0 elapsed=19.6s

  [144/21087] intraday_0144.csv.gz  in=109,391,725 out=0 elapsed=19.6s

  [145/21087] intraday_0147.csv.gz  in=109,406,698 out=0 elapsed=19.6s

  [146/21087] intraday_0148.csv.gz  in=109,417,998 out=0 elapsed=19.6s

  [147/21087] intraday_0146.csv.gz  in=109,449,779 out=0 elapsed=19.6s

  [148/21087] intraday_0149.csv.gz  in=109,461,076 out=0 elapsed=19.6s

  [149/21087] intraday_0150.csv.gz  in=109,477,550 out=0 elapsed=19.6s

  [150/21087] intraday_0151.csv.gz  in=109,493,543 out=0 elapsed=19.6s

  [151/21087] intraday_0152.csv.gz  in=109,505,698 out=0 elapsed=19.6s

  [152/21087] intraday_0153.csv.gz  in=109,517,425 out=0 elapsed=19.7s

  [153/21087] intraday_0154.csv.gz  in=109,532,249 out=0 elapsed=19.7s

  [154/21087] intraday_0155.csv.gz  in=109,547,829 out=0 elapsed=19.7s

  [155/21087] intraday_0157.csv.gz  in=109,560,028 out=0 elapsed=19.7s

  [156/21087] intraday_0156.csv.gz  in=109,573,389 out=0 elapsed=19.7s

  [157/21087] intraday_0159.csv.gz  in=109,585,001 out=0 elapsed=19.7s

  [158/21087] intraday_0160.csv.gz  in=109,597,440 out=0 elapsed=19.7s

  [159/21087] intraday_0158.csv.gz  in=109,627,373 out=0 elapsed=19.7s

  [160/21087] intraday_0161.csv.gz  in=109,639,687 out=0 elapsed=19.8s

  [161/21087] intraday_0162.csv.gz  in=109,656,973 out=0 elapsed=19.8s

  [162/21087] intraday_0163.csv.gz  in=109,674,179 out=0 elapsed=19.8s

  [163/21087] intraday_0164.csv.gz  in=109,689,370 out=0 elapsed=19.8s

  [164/21087] intraday_0165.csv.gz  in=109,701,993 out=0 elapsed=19.8s

  [165/21087] intraday_0166.csv.gz  in=109,715,603 out=0 elapsed=19.8s

  [166/21087] intraday_0168.csv.gz  in=109,726,460 out=0 elapsed=19.8s

  [167/21087] intraday_0169.csv.gz  in=109,740,791 out=0 elapsed=19.8s

  [168/21087] intraday_0167.csv.gz  in=109,761,632 out=0 elapsed=19.8s

  [169/21087] intraday_0133.csv.gz  in=110,542,533 out=0 elapsed=19.9s

  [170/21087] intraday_0170.csv.gz  in=110,558,073 out=0 elapsed=19.9s

  [171/21087] intraday_0172.csv.gz  in=110,568,807 out=0 elapsed=19.9s

  [172/21087] intraday_0171.csv.gz  in=110,580,228 out=0 elapsed=19.9s

  [173/21087] intraday_0173.csv.gz  in=110,593,066 out=0 elapsed=19.9s

  [174/21087] intraday_0174.csv.gz  in=110,605,870 out=0 elapsed=19.9s

  [175/21087] intraday_0175.csv.gz  in=110,620,244 out=0 elapsed=19.9s

  [176/21087] intraday_0176.csv.gz  in=110,637,126 out=0 elapsed=19.9s

  [177/21087] intraday_0177.csv.gz  in=110,652,077 out=0 elapsed=19.9s

  [178/21087] intraday_0178.csv.gz  in=110,666,020 out=0 elapsed=19.9s

  [179/21087] intraday_0179.csv.gz  in=110,679,724 out=0 elapsed=19.9s

  [180/21087] intraday_0180.csv.gz  in=110,693,457 out=0 elapsed=19.9s

  [181/21087] intraday_0181.csv.gz  in=110,724,271 out=0 elapsed=20.0s

  [182/21087] intraday_0182.csv.gz  in=110,736,763 out=0 elapsed=20.0s

  [183/21087] intraday_0183.csv.gz  in=110,754,307 out=0 elapsed=20.0s

  [184/21087] intraday_0184.csv.gz  in=110,770,536 out=0 elapsed=20.0s

  [185/21087] intraday_0185.csv.gz  in=110,784,589 out=0 elapsed=20.0s

  [186/21087] intraday_0186.csv.gz  in=110,799,047 out=0 elapsed=20.0s

  [187/21087] intraday_0187.csv.gz  in=110,812,773 out=0 elapsed=20.0s

  [188/21087] intraday_0189.csv.gz  in=110,825,918 out=0 elapsed=20.0s

  [189/21087] intraday_0188.csv.gz  in=110,849,387 out=0 elapsed=20.0s

  [190/21087] intraday_0190.csv.gz  in=110,863,095 out=0 elapsed=20.0s

  [191/21087] intraday_0191.csv.gz  in=110,877,560 out=0 elapsed=20.0s

  [192/21087] intraday_0192.csv.gz  in=110,889,613 out=0 elapsed=20.0s

  [193/21087] intraday_0193.csv.gz  in=110,901,524 out=0 elapsed=20.0s

  [194/21087] intraday_0194.csv.gz  in=110,911,659 out=0 elapsed=20.0s

  [195/21087] intraday_0195.csv.gz  in=110,926,310 out=0 elapsed=20.1s

  [196/21087] intraday_0196.csv.gz  in=110,938,931 out=0 elapsed=20.1s

  [197/21087] intraday_0197.csv.gz  in=110,953,423 out=0 elapsed=20.1s

  [198/21087] intraday_0198.csv.gz  in=110,968,845 out=0 elapsed=20.1s

  [199/21087] intraday_0200.csv.gz  in=110,980,268 out=0 elapsed=20.1s

  [200/21087] intraday_0199.csv.gz  in=110,995,048 out=0 elapsed=20.1s

  [201/21087] intraday_0201.csv.gz  in=111,008,704 out=0 elapsed=20.1s

  [202/21087] intraday_0202.csv.gz  in=111,023,231 out=0 elapsed=20.1s

  [203/21087] intraday_0204.csv.gz  in=111,034,300 out=0 elapsed=20.1s

  [204/21087] intraday_0203.csv.gz  in=111,047,240 out=0 elapsed=20.1s

  [205/21087] intraday_0205.csv.gz  in=111,057,791 out=0 elapsed=20.1s

  [206/21087] intraday_0206.csv.gz  in=111,071,031 out=0 elapsed=20.1s

  [207/21087] intraday_0207.csv.gz  in=111,084,627 out=0 elapsed=20.2s

  [208/21087] intraday_0208.csv.gz  in=111,096,777 out=0 elapsed=20.2s

  [209/21087] intraday_0209.csv.gz  in=111,109,213 out=0 elapsed=20.2s

  [210/21087] intraday_0210.csv.gz  in=111,120,563 out=0 elapsed=20.2s

  [211/21087] intraday_0211.csv.gz  in=111,136,024 out=0 elapsed=20.2s

  [212/21087] intraday_0213.csv.gz  in=111,150,494 out=0 elapsed=20.2s

  [213/21087] intraday_0212.csv.gz  in=111,170,551 out=0 elapsed=20.2s

  [214/21087] intraday_0214.csv.gz  in=111,183,384 out=0 elapsed=20.2s

  [215/21087] intraday_0215.csv.gz  in=111,197,300 out=0 elapsed=20.2s

  [216/21087] intraday_0216.csv.gz  in=111,211,568 out=0 elapsed=20.2s

  [217/21087] intraday_0217.csv.gz  in=111,225,093 out=0 elapsed=20.2s

  [218/21087] intraday_0218.csv.gz  in=111,244,102 out=0 elapsed=20.2s

  [219/21087] intraday_0219.csv.gz  in=111,256,130 out=0 elapsed=20.3s

  [220/21087] intraday_0220.csv.gz  in=111,271,333 out=0 elapsed=20.3s

  [221/21087] intraday_0221.csv.gz  in=111,288,427 out=0 elapsed=20.3s

  [222/21087] intraday_0222.csv.gz  in=111,302,939 out=0 elapsed=20.3s

  [223/21087] intraday_0224.csv.gz  in=111,316,587 out=0 elapsed=20.3s

  [224/21087] intraday_0223.csv.gz  in=111,331,291 out=0 elapsed=20.3s

  [225/21087] intraday_0225.csv.gz  in=111,345,732 out=0 elapsed=20.3s

  [226/21087] intraday_0226.csv.gz  in=111,358,887 out=0 elapsed=20.3s

  [227/21087] intraday_0227.csv.gz  in=111,373,404 out=0 elapsed=20.3s

  [228/21087] intraday_0228.csv.gz  in=111,389,838 out=0 elapsed=20.3s

  [229/21087] intraday_0229.csv.gz  in=111,403,698 out=0 elapsed=20.3s

  [230/21087] intraday_0230.csv.gz  in=111,418,264 out=0 elapsed=20.3s

  [231/21087] intraday_0231.csv.gz  in=111,430,225 out=0 elapsed=20.3s

  [232/21087] intraday_0232.csv.gz  in=111,444,220 out=0 elapsed=20.4s

  [233/21087] intraday_0233.csv.gz  in=111,461,382 out=0 elapsed=20.4s

  [234/21087] intraday_0234.csv.gz  in=111,476,182 out=0 elapsed=20.4s

  [235/21087] intraday_0235.csv.gz  in=111,490,802 out=0 elapsed=20.4s

  [236/21087] intraday_0236.csv.gz  in=111,507,721 out=0 elapsed=20.4s

  [237/21087] intraday_0237.csv.gz  in=111,520,281 out=0 elapsed=20.4s

  [238/21087] intraday_0238.csv.gz  in=111,537,182 out=0 elapsed=20.4s

  [239/21087] intraday_0239.csv.gz  in=111,553,893 out=0 elapsed=20.4s

  [240/21087] intraday_0240.csv.gz  in=111,568,283 out=0 elapsed=20.4s

  [241/21087] intraday_0241.csv.gz  in=111,584,827 out=0 elapsed=20.4s

  [242/21087] intraday_0242.csv.gz  in=111,598,399 out=0 elapsed=20.4s

  [243/21087] intraday_0244.csv.gz  in=111,615,055 out=0 elapsed=20.4s

  [244/21087] intraday_0243.csv.gz  in=111,641,791 out=0 elapsed=20.5s

  [245/21087] intraday_0245.csv.gz  in=111,654,087 out=0 elapsed=20.5s

  [246/21087] intraday_0246.csv.gz  in=111,669,545 out=0 elapsed=20.5s

  [247/21087] intraday_0247.csv.gz  in=111,683,569 out=0 elapsed=20.5s

  [248/21087] intraday_0248.csv.gz  in=111,697,128 out=0 elapsed=20.5s

  [249/21087] intraday_0249.csv.gz  in=111,712,496 out=0 elapsed=20.5s

  [250/21087] intraday_0250.csv.gz  in=111,728,198 out=0 elapsed=20.5s

  [251/21087] intraday_0251.csv.gz  in=111,741,334 out=0 elapsed=20.5s

  [252/21087] intraday_0252.csv.gz  in=111,762,442 out=0 elapsed=20.5s

  [253/21087] intraday_0253.csv.gz  in=111,775,789 out=0 elapsed=20.5s

  [254/21087] intraday_0254.csv.gz  in=111,790,210 out=0 elapsed=20.5s

  [255/21087] intraday_0255.csv.gz  in=111,808,314 out=0 elapsed=20.5s

  [256/21087] intraday_0256.csv.gz  in=111,824,019 out=0 elapsed=20.6s

  [257/21087] intraday_0257.csv.gz  in=111,839,272 out=0 elapsed=20.6s

  [258/21087] intraday_0258.csv.gz  in=111,855,418 out=0 elapsed=20.6s

  [259/21087] intraday_0259.csv.gz  in=111,870,028 out=0 elapsed=20.6s

  [260/21087] intraday_0260.csv.gz  in=111,886,263 out=0 elapsed=20.6s

  [261/21087] intraday_0261.csv.gz  in=111,900,357 out=0 elapsed=20.6s

  [262/21087] intraday_0262.csv.gz  in=111,912,297 out=0 elapsed=20.6s

  [263/21087] intraday_0263.csv.gz  in=111,926,807 out=0 elapsed=20.6s

  [264/21087] intraday_0264.csv.gz  in=111,940,725 out=0 elapsed=20.6s

  [265/21087] intraday_0265.csv.gz  in=111,955,763 out=0 elapsed=20.6s

  [266/21087] intraday_0266.csv.gz  in=111,964,686 out=0 elapsed=20.6s

  [267/21087] intraday_0268.csv.gz  in=111,965,040 out=0 elapsed=20.6s

  [268/21087] intraday_0267.csv.gz  in=111,978,303 out=0 elapsed=20.6s

  [269/21087] intraday_0271.csv.gz  in=112,194,521 out=0 elapsed=20.8s

  [270/21087] intraday_0269.csv.gz  in=112,490,892 out=0 elapsed=20.8s

  [271/21087] intraday_0272.csv.gz  in=112,723,596 out=0 elapsed=20.8s

  [272/21087] intraday_0270.csv.gz  in=112,987,663 out=0 elapsed=20.9s

  [273/21087] intraday_0273.csv.gz  in=113,246,304 out=0 elapsed=21.0s

  [274/21087] intraday_0275.csv.gz  in=113,479,352 out=0 elapsed=21.0s

  [275/21087] intraday_0276.csv.gz  in=113,730,868 out=0 elapsed=21.0s

  [276/21087] intraday_0274.csv.gz  in=114,011,989 out=0 elapsed=21.0s

  [277/21087] intraday_0278.csv.gz  in=114,258,113 out=0 elapsed=21.2s

  [278/21087] intraday_0279.csv.gz  in=114,500,722 out=0 elapsed=21.2s

  [279/21087] intraday_0280.csv.gz  in=114,754,915 out=0 elapsed=21.3s

  [280/21087] intraday_0277.csv.gz  in=115,056,079 out=0 elapsed=21.3s

  [281/21087] intraday_0282.csv.gz  in=115,248,860 out=0 elapsed=21.4s

  [282/21087] intraday_0283.csv.gz  in=115,448,136 out=0 elapsed=21.4s

  [283/21087] intraday_0281.csv.gz  in=115,709,313 out=0 elapsed=21.4s

  [284/21087] intraday_0286.csv.gz  in=115,748,047 out=0 elapsed=21.4s

  [285/21087] intraday_0284.csv.gz  in=116,043,246 out=0 elapsed=21.5s

  [286/21087] intraday_0285.csv.gz  in=116,298,084 out=0 elapsed=21.6s

  [287/21087] intraday_0287.csv.gz  in=116,525,928 out=0 elapsed=21.6s

  [288/21087] intraday_0288.csv.gz  in=116,746,745 out=0 elapsed=21.6s

  [289/21087] intraday_0289.csv.gz  in=116,965,439 out=0 elapsed=21.6s

  [290/21087] intraday_0291.csv.gz  in=117,185,469 out=0 elapsed=21.7s

  [291/21087] intraday_0290.csv.gz  in=117,445,345 out=0 elapsed=21.7s

  [292/21087] intraday_0292.csv.gz  in=117,685,256 out=0 elapsed=21.8s

  [293/21087] intraday_0293.csv.gz  in=117,927,992 out=0 elapsed=21.8s

  [294/21087] intraday_0295.csv.gz  in=118,142,206 out=0 elapsed=21.9s

  [295/21087] intraday_0294.csv.gz  in=118,357,943 out=0 elapsed=21.9s

  [296/21087] intraday_0296.csv.gz  in=118,563,185 out=0 elapsed=21.9s

  [297/21087] intraday_0297.csv.gz  in=118,843,298 out=0 elapsed=22.0s

  [298/21087] intraday_0300.csv.gz  in=119,066,942 out=0 elapsed=22.1s

  [299/21087] intraday_0299.csv.gz  in=119,328,932 out=0 elapsed=22.1s

  [300/21087] intraday_0298.csv.gz  in=119,612,107 out=0 elapsed=22.1s

  [301/21087] intraday_0301.csv.gz  in=119,831,995 out=0 elapsed=22.1s

  [302/21087] intraday_0302.csv.gz  in=119,886,957 out=0 elapsed=22.1s

  [303/21087] intraday_0304.csv.gz  in=120,123,356 out=0 elapsed=22.3s

  [304/21087] intraday_0305.csv.gz  in=120,358,027 out=0 elapsed=22.3s

  [305/21087] intraday_0303.csv.gz  in=120,655,391 out=0 elapsed=22.3s

  [306/21087] intraday_0306.csv.gz  in=120,902,289 out=0 elapsed=22.3s

  [307/21087] intraday_0307.csv.gz  in=121,125,738 out=0 elapsed=22.4s

  [308/21087] intraday_0308.csv.gz  in=121,351,202 out=0 elapsed=22.4s

  [309/21087] intraday_0310.csv.gz  in=121,572,408 out=0 elapsed=22.5s

  [310/21087] intraday_0309.csv.gz  in=121,811,036 out=0 elapsed=22.5s

  [311/21087] intraday_0311.csv.gz  in=122,090,746 out=0 elapsed=22.6s

  [312/21087] intraday_0313.csv.gz  in=122,328,043 out=0 elapsed=22.6s

  [313/21087] intraday_0314.csv.gz  in=122,589,076 out=0 elapsed=22.6s

  [314/21087] intraday_0312.csv.gz  in=122,890,640 out=0 elapsed=22.7s

  [315/21087] intraday_0315.csv.gz  in=123,155,037 out=0 elapsed=22.8s

  [316/21087] intraday_0316.csv.gz  in=123,403,821 out=0 elapsed=22.8s

  [317/21087] intraday_0318.csv.gz  in=123,637,922 out=0 elapsed=22.8s

  [318/21087] intraday_0317.csv.gz  in=123,900,660 out=0 elapsed=22.8s

  [319/21087] intraday_0319.csv.gz  in=124,176,134 out=0 elapsed=23.0s

  [320/21087] intraday_0320.csv.gz  in=124,416,353 out=0 elapsed=23.0s

  [321/21087] intraday_0322.csv.gz  in=124,656,782 out=0 elapsed=23.0s

  [322/21087] intraday_0321.csv.gz  in=124,909,648 out=0 elapsed=23.0s

  [323/21087] intraday_0323.csv.gz  in=125,155,264 out=0 elapsed=23.1s

  [324/21087] intraday_0324.csv.gz  in=125,389,255 out=0 elapsed=23.2s

  [325/21087] intraday_0325.csv.gz  in=125,649,135 out=0 elapsed=23.2s

  [326/21087] intraday_0326.csv.gz  in=125,911,356 out=0 elapsed=23.2s

  [327/21087] intraday_0327.csv.gz  in=126,118,825 out=0 elapsed=23.3s

  [328/21087] intraday_0328.csv.gz  in=126,374,250 out=0 elapsed=23.3s

  [329/21087] intraday_0330.csv.gz  in=126,570,754 out=0 elapsed=23.3s

  [330/21087] intraday_0329.csv.gz  in=126,779,582 out=0 elapsed=23.3s

  [331/21087] intraday_0331.csv.gz  in=127,046,519 out=0 elapsed=23.4s

  [332/21087] intraday_0333.csv.gz  in=127,253,545 out=0 elapsed=23.5s

  [333/21087] intraday_0332.csv.gz  in=127,538,683 out=0 elapsed=23.5s

  [334/21087] intraday_0334.csv.gz  in=127,816,232 out=0 elapsed=23.5s

  [335/21087] intraday_0335.csv.gz  in=128,092,776 out=0 elapsed=23.6s

  [336/21087] intraday_0336.csv.gz  in=128,295,496 out=0 elapsed=23.7s

  [337/21087] intraday_0337.csv.gz  in=128,525,452 out=0 elapsed=23.7s

  [338/21087] intraday_0338.csv.gz  in=128,783,286 out=0 elapsed=23.7s

  [339/21087] intraday_0340.csv.gz  in=128,981,471 out=0 elapsed=23.8s

  [340/21087] intraday_0339.csv.gz  in=129,240,852 out=0 elapsed=23.8s

  [341/21087] intraday_0341.csv.gz  in=129,458,823 out=0 elapsed=23.8s

  [342/21087] intraday_0342.csv.gz  in=129,667,620 out=0 elapsed=23.9s

  [343/21087] intraday_0343.csv.gz  in=129,899,349 out=0 elapsed=24.0s

  [344/21087] intraday_0344.csv.gz  in=130,138,366 out=0 elapsed=24.0s

  [345/21087] intraday_0346.csv.gz  in=130,320,714 out=0 elapsed=24.0s

  [346/21087] intraday_0345.csv.gz  in=130,559,285 out=0 elapsed=24.0s

  [347/21087] intraday_0347.csv.gz  in=130,772,959 out=0 elapsed=24.1s

  [348/21087] intraday_0348.csv.gz  in=131,024,833 out=0 elapsed=24.2s

  [349/21087] intraday_0350.csv.gz  in=131,261,296 out=0 elapsed=24.2s

  [350/21087] intraday_0349.csv.gz  in=131,570,921 out=0 elapsed=24.2s

  [351/21087] intraday_0351.csv.gz  in=131,797,285 out=0 elapsed=24.2s

  [352/21087] intraday_0352.csv.gz  in=132,033,883 out=0 elapsed=24.3s

  [353/21087] intraday_0353.csv.gz  in=132,292,867 out=0 elapsed=24.4s

  [354/21087] intraday_0354.csv.gz  in=132,523,180 out=0 elapsed=24.4s

  [355/21087] intraday_0355.csv.gz  in=132,836,273 out=0 elapsed=24.5s

  [356/21087] intraday_0356.csv.gz  in=133,077,260 out=0 elapsed=24.5s

  [357/21087] intraday_0357.csv.gz  in=133,365,265 out=0 elapsed=24.5s

  [358/21087] intraday_0358.csv.gz  in=133,649,154 out=0 elapsed=24.6s

  [359/21087] intraday_0359.csv.gz  in=133,915,035 out=0 elapsed=24.6s

  [360/21087] intraday_0360.csv.gz  in=134,168,226 out=0 elapsed=24.6s

  [361/21087] intraday_0361.csv.gz  in=134,407,423 out=0 elapsed=24.7s

  [362/21087] intraday_0362.csv.gz  in=134,663,024 out=0 elapsed=24.7s

  [363/21087] intraday_0363.csv.gz  in=134,908,995 out=0 elapsed=24.8s

  [364/21087] intraday_0364.csv.gz  in=135,155,263 out=0 elapsed=24.8s

  [365/21087] intraday_0365.csv.gz  in=135,380,830 out=0 elapsed=24.9s

  [366/21087] intraday_0366.csv.gz  in=135,644,767 out=0 elapsed=24.9s

  [367/21087] intraday_0368.csv.gz  in=135,878,241 out=0 elapsed=25.0s

  [368/21087] intraday_0367.csv.gz  in=136,162,187 out=0 elapsed=25.0s

  [369/21087] intraday_0369.csv.gz  in=136,435,160 out=0 elapsed=25.1s

  [370/21087] intraday_0370.csv.gz  in=136,756,824 out=0 elapsed=25.1s

  [371/21087] intraday_0371.csv.gz  in=137,029,476 out=0 elapsed=25.2s

  [372/21087] intraday_0372.csv.gz  in=137,296,332 out=0 elapsed=25.2s

  [373/21087] intraday_0373.csv.gz  in=137,544,174 out=0 elapsed=25.2s

  [374/21087] intraday_0375.csv.gz  in=137,747,513 out=0 elapsed=25.3s

  [375/21087] intraday_0374.csv.gz  in=138,017,550 out=0 elapsed=25.3s

  [376/21087] intraday_0377.csv.gz  in=138,254,790 out=0 elapsed=25.4s

  [377/21087] intraday_0376.csv.gz  in=138,565,665 out=0 elapsed=25.4s

  [378/21087] intraday_0379.csv.gz  in=138,818,657 out=0 elapsed=25.5s

  [379/21087] intraday_0378.csv.gz  in=139,087,787 out=0 elapsed=25.5s

  [380/21087] intraday_0380.csv.gz  in=139,374,542 out=0 elapsed=25.6s

  [381/21087] intraday_0381.csv.gz  in=139,648,162 out=0 elapsed=25.6s

  [382/21087] intraday_0382.csv.gz  in=139,904,999 out=0 elapsed=25.7s

  [383/21087] intraday_0383.csv.gz  in=140,179,278 out=0 elapsed=25.7s

  [384/21087] intraday_0385.csv.gz  in=140,391,955 out=0 elapsed=25.7s

  [385/21087] intraday_0384.csv.gz  in=140,640,779 out=0 elapsed=25.7s

  [386/21087] intraday_0386.csv.gz  in=140,878,294 out=0 elapsed=25.8s

  [387/21087] intraday_0387.csv.gz  in=141,147,253 out=0 elapsed=25.9s

  [388/21087] intraday_0388.csv.gz  in=141,399,520 out=0 elapsed=25.9s

  [389/21087] intraday_0389.csv.gz  in=141,725,055 out=0 elapsed=26.0s

  [390/21087] intraday_0390.csv.gz  in=141,949,153 out=0 elapsed=26.0s

  [391/21087] intraday_0391.csv.gz  in=142,203,569 out=0 elapsed=26.0s

  [392/21087] intraday_0392.csv.gz  in=142,457,409 out=0 elapsed=26.1s

  [393/21087] intraday_0393.csv.gz  in=142,721,977 out=0 elapsed=26.1s

  [394/21087] intraday_0394.csv.gz  in=142,966,664 out=0 elapsed=26.1s

  [395/21087] intraday_0395.csv.gz  in=143,253,685 out=0 elapsed=26.2s

  [396/21087] intraday_0396.csv.gz  in=143,532,614 out=0 elapsed=26.3s

  [397/21087] intraday_0397.csv.gz  in=143,777,948 out=0 elapsed=26.3s

  [398/21087] intraday_0398.csv.gz  in=144,034,957 out=0 elapsed=26.3s

  [399/21087] intraday_0399.csv.gz  in=144,258,829 out=0 elapsed=26.4s

  [400/21087] intraday_0400.csv.gz  in=144,480,592 out=0 elapsed=26.4s

  [401/21087] intraday_0401.csv.gz  in=144,678,165 out=0 elapsed=26.4s

  [402/21087] intraday_0402.csv.gz  in=144,938,220 out=0 elapsed=26.5s

  [403/21087] intraday_0404.csv.gz  in=145,099,518 out=0 elapsed=26.5s

  [404/21087] intraday_0406.csv.gz  in=145,114,230 out=0 elapsed=26.5s

  [405/21087] intraday_0403.csv.gz  in=145,327,551 out=0 elapsed=26.5s

  [406/21087] intraday_0408.csv.gz  in=145,339,818 out=0 elapsed=26.6s

  [407/21087] intraday_0409.csv.gz  in=145,353,184 out=0 elapsed=26.6s

  [408/21087] intraday_0407.csv.gz  in=145,377,611 out=0 elapsed=26.6s

  [409/21087] intraday_0410.csv.gz  in=145,392,730 out=0 elapsed=26.6s

  [410/21087] intraday_0411.csv.gz  in=145,408,587 out=0 elapsed=26.6s

  [411/21087] intraday_0412.csv.gz  in=145,419,651 out=0 elapsed=26.6s

  [412/21087] intraday_0413.csv.gz  in=145,432,635 out=0 elapsed=26.6s

  [413/21087] intraday_0405.csv.gz  in=145,657,039 out=0 elapsed=26.6s

  [414/21087] intraday_0415.csv.gz  in=145,669,838 out=0 elapsed=26.6s

  [415/21087] intraday_0414.csv.gz  in=145,684,409 out=0 elapsed=26.6s

  [416/21087] intraday_0416.csv.gz  in=145,695,807 out=0 elapsed=26.7s

  [417/21087] intraday_0417.csv.gz  in=145,709,282 out=0 elapsed=26.7s

  [418/21087] intraday_0418.csv.gz  in=145,723,588 out=0 elapsed=26.7s

  [419/21087] intraday_0419.csv.gz  in=145,734,865 out=0 elapsed=26.7s

  [420/21087] intraday_0420.csv.gz  in=145,746,540 out=0 elapsed=26.7s

  [421/21087] intraday_0421.csv.gz  in=145,761,843 out=0 elapsed=26.7s

  [422/21087] intraday_0422.csv.gz  in=145,775,162 out=0 elapsed=26.7s

  [423/21087] intraday_0423.csv.gz  in=145,786,663 out=0 elapsed=26.7s

  [424/21087] intraday_0424.csv.gz  in=145,797,862 out=0 elapsed=26.7s

  [425/21087] intraday_0425.csv.gz  in=145,809,626 out=0 elapsed=26.7s

  [426/21087] intraday_0426.csv.gz  in=145,821,626 out=0 elapsed=26.7s

  [427/21087] intraday_0427.csv.gz  in=145,833,678 out=0 elapsed=26.7s

  [428/21087] intraday_0428.csv.gz  in=145,846,867 out=0 elapsed=26.7s

  [429/21087] intraday_0429.csv.gz  in=145,859,925 out=0 elapsed=26.8s

  [430/21087] intraday_0430.csv.gz  in=145,870,744 out=0 elapsed=26.8s

  [431/21087] intraday_0431.csv.gz  in=145,882,155 out=0 elapsed=26.8s

  [432/21087] intraday_0432.csv.gz  in=145,893,068 out=0 elapsed=26.8s

  [433/21087] intraday_0433.csv.gz  in=145,907,644 out=0 elapsed=26.8s

  [434/21087] intraday_0435.csv.gz  in=145,923,875 out=0 elapsed=26.8s

  [435/21087] intraday_0434.csv.gz  in=145,939,651 out=0 elapsed=26.8s

  [436/21087] intraday_0436.csv.gz  in=145,951,958 out=0 elapsed=26.8s

  [437/21087] intraday_0437.csv.gz  in=145,963,948 out=0 elapsed=26.8s

  [438/21087] intraday_0438.csv.gz  in=145,976,928 out=0 elapsed=26.8s

  [439/21087] intraday_0439.csv.gz  in=145,994,748 out=0 elapsed=26.8s

  [440/21087] intraday_0440.csv.gz  in=146,007,004 out=0 elapsed=26.8s

  [441/21087] intraday_0441.csv.gz  in=146,018,926 out=0 elapsed=26.9s

  [442/21087] intraday_0442.csv.gz  in=146,032,539 out=0 elapsed=26.9s

  [443/21087] intraday_0443.csv.gz  in=146,044,273 out=0 elapsed=26.9s

  [444/21087] intraday_0444.csv.gz  in=146,056,615 out=0 elapsed=26.9s

  [445/21087] intraday_0445.csv.gz  in=146,071,013 out=0 elapsed=26.9s

  [446/21087] intraday_0446.csv.gz  in=146,084,577 out=0 elapsed=26.9s

  [447/21087] intraday_0447.csv.gz  in=146,098,749 out=0 elapsed=26.9s

  [448/21087] intraday_0448.csv.gz  in=146,112,265 out=0 elapsed=26.9s

  [449/21087] intraday_0450.csv.gz  in=146,125,627 out=0 elapsed=26.9s

  [450/21087] intraday_0449.csv.gz  in=146,163,328 out=0 elapsed=26.9s

  [451/21087] intraday_0451.csv.gz  in=146,175,913 out=0 elapsed=26.9s

  [452/21087] intraday_0452.csv.gz  in=146,194,390 out=0 elapsed=26.9s

  [453/21087] intraday_0453.csv.gz  in=146,206,987 out=0 elapsed=26.9s

  [454/21087] intraday_0454.csv.gz  in=146,219,751 out=0 elapsed=27.0s

  [455/21087] intraday_0456.csv.gz  in=146,232,043 out=0 elapsed=27.0s

  [456/21087] intraday_0455.csv.gz  in=146,255,603 out=0 elapsed=27.0s

  [457/21087] intraday_0457.csv.gz  in=146,269,716 out=0 elapsed=27.0s

  [458/21087] intraday_0458.csv.gz  in=146,282,797 out=0 elapsed=27.0s

  [459/21087] intraday_0459.csv.gz  in=146,296,147 out=0 elapsed=27.0s

  [460/21087] intraday_0460.csv.gz  in=146,311,892 out=0 elapsed=27.0s

  [461/21087] intraday_0461.csv.gz  in=146,324,208 out=0 elapsed=27.0s

  [462/21087] intraday_0462.csv.gz  in=146,337,792 out=0 elapsed=27.0s

  [463/21087] intraday_0463.csv.gz  in=146,350,280 out=0 elapsed=27.0s

  [464/21087] intraday_0464.csv.gz  in=146,362,048 out=0 elapsed=27.0s

  [465/21087] intraday_0465.csv.gz  in=146,387,954 out=0 elapsed=27.0s

  [466/21087] intraday_0466.csv.gz  in=146,400,574 out=0 elapsed=27.0s

  [467/21087] intraday_0468.csv.gz  in=146,412,537 out=0 elapsed=27.1s

  [468/21087] intraday_0467.csv.gz  in=146,429,806 out=0 elapsed=27.1s

  [469/21087] intraday_0469.csv.gz  in=146,444,443 out=0 elapsed=27.1s

  [470/21087] intraday_0470.csv.gz  in=146,459,130 out=0 elapsed=27.1s

  [471/21087] intraday_0471.csv.gz  in=146,471,756 out=0 elapsed=27.1s

  [472/21087] intraday_0472.csv.gz  in=146,483,702 out=0 elapsed=27.1s

  [473/21087] intraday_0473.csv.gz  in=146,495,640 out=0 elapsed=27.1s

  [474/21087] intraday_0474.csv.gz  in=146,508,636 out=0 elapsed=27.1s

  [475/21087] intraday_0476.csv.gz  in=146,520,146 out=0 elapsed=27.1s

  [476/21087] intraday_0475.csv.gz  in=146,533,238 out=0 elapsed=27.1s

  [477/21087] intraday_0477.csv.gz  in=146,542,494 out=0 elapsed=27.1s

  [478/21087] intraday_0478.csv.gz  in=146,554,934 out=0 elapsed=27.2s

  [479/21087] intraday_0479.csv.gz  in=146,567,951 out=0 elapsed=27.2s

  [480/21087] intraday_0480.csv.gz  in=146,579,673 out=0 elapsed=27.2s

  [481/21087] intraday_0481.csv.gz  in=146,591,926 out=0 elapsed=27.2s

  [482/21087] intraday_0482.csv.gz  in=146,603,171 out=0 elapsed=27.2s

  [483/21087] intraday_0483.csv.gz  in=146,613,850 out=0 elapsed=27.2s

  [484/21087] intraday_0484.csv.gz  in=146,625,831 out=0 elapsed=27.2s

  [485/21087] intraday_0485.csv.gz  in=146,643,216 out=0 elapsed=27.2s

  [486/21087] intraday_0486.csv.gz  in=146,655,077 out=0 elapsed=27.2s

  [487/21087] intraday_0487.csv.gz  in=146,665,512 out=0 elapsed=27.2s

  [488/21087] intraday_0488.csv.gz  in=146,679,315 out=0 elapsed=27.2s

  [489/21087] intraday_0489.csv.gz  in=146,691,816 out=0 elapsed=27.2s

  [490/21087] intraday_0490.csv.gz  in=146,709,671 out=0 elapsed=27.3s

  [491/21087] intraday_0491.csv.gz  in=146,724,538 out=0 elapsed=27.3s

  [492/21087] intraday_0492.csv.gz  in=146,738,727 out=0 elapsed=27.3s

  [493/21087] intraday_0493.csv.gz  in=146,752,962 out=0 elapsed=27.3s

  [494/21087] intraday_0494.csv.gz  in=146,767,742 out=0 elapsed=27.3s

  [495/21087] intraday_0495.csv.gz  in=146,781,319 out=0 elapsed=27.3s

  [496/21087] intraday_0496.csv.gz  in=146,796,225 out=0 elapsed=27.3s

  [497/21087] intraday_0497.csv.gz  in=146,815,798 out=0 elapsed=27.3s

  [498/21087] intraday_0498.csv.gz  in=146,828,986 out=0 elapsed=27.3s

  [499/21087] intraday_0499.csv.gz  in=146,840,301 out=0 elapsed=27.3s

  [500/21087] intraday_0500.csv.gz  in=146,860,626 out=0 elapsed=27.3s

  [501/21087] intraday_0501.csv.gz  in=146,879,764 out=0 elapsed=27.4s

  [502/21087] intraday_0503.csv.gz  in=146,893,402 out=0 elapsed=27.4s

  [503/21087] intraday_0502.csv.gz  in=146,910,524 out=0 elapsed=27.4s

  [504/21087] intraday_0504.csv.gz  in=146,923,190 out=0 elapsed=27.4s

  [505/21087] intraday_0505.csv.gz  in=146,938,528 out=0 elapsed=27.4s

  [506/21087] intraday_0507.csv.gz  in=146,954,063 out=0 elapsed=27.4s

  [507/21087] intraday_0506.csv.gz  in=146,990,344 out=0 elapsed=27.4s

  [508/21087] intraday_0509.csv.gz  in=147,006,404 out=0 elapsed=27.4s

  [509/21087] intraday_0508.csv.gz  in=147,035,549 out=0 elapsed=27.4s

  [510/21087] intraday_0510.csv.gz  in=147,046,916 out=0 elapsed=27.4s

  [511/21087] intraday_0511.csv.gz  in=147,060,675 out=0 elapsed=27.4s

  [512/21087] intraday_0512.csv.gz  in=147,077,697 out=0 elapsed=27.5s

  [513/21087] intraday_0513.csv.gz  in=147,090,371 out=0 elapsed=27.5s

  [514/21087] intraday_0514.csv.gz  in=147,108,078 out=0 elapsed=27.5s

  [515/21087] intraday_0515.csv.gz  in=147,122,880 out=0 elapsed=27.5s

  [516/21087] intraday_0516.csv.gz  in=147,137,901 out=0 elapsed=27.5s

  [517/21087] intraday_0517.csv.gz  in=147,154,561 out=0 elapsed=27.5s

  [518/21087] intraday_0518.csv.gz  in=147,166,721 out=0 elapsed=27.5s

  [519/21087] intraday_0519.csv.gz  in=147,180,329 out=0 elapsed=27.5s

  [520/21087] intraday_0520.csv.gz  in=147,191,638 out=0 elapsed=27.5s

  [521/21087] intraday_0521.csv.gz  in=147,204,598 out=0 elapsed=27.5s

  [522/21087] intraday_0523.csv.gz  in=147,219,410 out=0 elapsed=27.5s

  [523/21087] intraday_0522.csv.gz  in=147,232,671 out=0 elapsed=27.5s

  [524/21087] intraday_0524.csv.gz  in=147,245,780 out=0 elapsed=27.5s

  [525/21087] intraday_0525.csv.gz  in=147,261,573 out=0 elapsed=27.5s

  [526/21087] intraday_0526.csv.gz  in=147,274,492 out=0 elapsed=27.6s

  [527/21087] intraday_0527.csv.gz  in=147,287,469 out=0 elapsed=27.6s

  [528/21087] intraday_0528.csv.gz  in=147,304,425 out=0 elapsed=27.6s

  [529/21087] intraday_0529.csv.gz  in=147,316,770 out=0 elapsed=27.6s

  [530/21087] intraday_0530.csv.gz  in=147,331,059 out=0 elapsed=27.6s

  [531/21087] intraday_0531.csv.gz  in=147,347,109 out=0 elapsed=27.6s

  [532/21087] intraday_0532.csv.gz  in=147,361,302 out=0 elapsed=27.6s

  [533/21087] intraday_0533.csv.gz  in=147,376,091 out=0 elapsed=27.6s

  [534/21087] intraday_0534.csv.gz  in=147,390,514 out=0 elapsed=27.6s

  [535/21087] intraday_0537.csv.gz  in=147,401,575 out=0 elapsed=27.6s

  [536/21087] intraday_0536.csv.gz  in=147,413,137 out=0 elapsed=27.6s

  [537/21087] intraday_0535.csv.gz  in=147,423,684 out=0 elapsed=27.6s

  [538/21087] intraday_0538.csv.gz  in=147,437,484 out=0 elapsed=27.7s

  [539/21087] intraday_0541.csv.gz  in=147,445,978 out=0 elapsed=27.7s

  [540/21087] intraday_0539.csv.gz  in=147,456,974 out=0 elapsed=27.7s

  [541/21087] intraday_0540.csv.gz  in=147,466,999 out=0 elapsed=27.7s

  [542/21087] intraday_0544.csv.gz  in=147,493,880 out=0 elapsed=27.7s

  [543/21087] intraday_0543.csv.gz  in=147,523,470 out=0 elapsed=27.7s

  [544/21087] intraday_0542.csv.gz  in=147,565,316 out=0 elapsed=27.7s

  [545/21087] intraday_0545.csv.gz  in=147,606,543 out=0 elapsed=27.7s

  [546/21087] intraday_0548.csv.gz  in=147,630,483 out=0 elapsed=27.8s

  [547/21087] intraday_0546.csv.gz  in=147,661,901 out=0 elapsed=27.8s

  [548/21087] intraday_0547.csv.gz  in=147,695,604 out=0 elapsed=27.8s

  [549/21087] intraday_0549.csv.gz  in=147,723,194 out=0 elapsed=27.8s

  [550/21087] intraday_0550.csv.gz  in=147,752,711 out=0 elapsed=27.8s

  [551/21087] intraday_0551.csv.gz  in=147,780,245 out=0 elapsed=27.8s

  [552/21087] intraday_0552.csv.gz  in=147,804,284 out=0 elapsed=27.8s

  [553/21087] intraday_0553.csv.gz  in=147,832,832 out=0 elapsed=27.8s

  [554/21087] intraday_0555.csv.gz  in=147,855,311 out=0 elapsed=27.8s

  [555/21087] intraday_0556.csv.gz  in=147,879,085 out=0 elapsed=27.9s

  [556/21087] intraday_0554.csv.gz  in=147,910,090 out=0 elapsed=27.9s

  [557/21087] intraday_0557.csv.gz  in=147,941,618 out=0 elapsed=27.9s

  [558/21087] intraday_0558.csv.gz  in=147,970,209 out=0 elapsed=27.9s

  [559/21087] intraday_0560.csv.gz  in=147,994,077 out=0 elapsed=27.9s

  [560/21087] intraday_0561.csv.gz  in=148,021,150 out=0 elapsed=27.9s

  [561/21087] intraday_0559.csv.gz  in=148,048,023 out=0 elapsed=27.9s

  [562/21087] intraday_0562.csv.gz  in=148,073,086 out=0 elapsed=27.9s

  [563/21087] intraday_0563.csv.gz  in=148,097,855 out=0 elapsed=27.9s

  [564/21087] intraday_0564.csv.gz  in=148,124,975 out=0 elapsed=27.9s

  [565/21087] intraday_0565.csv.gz  in=148,152,228 out=0 elapsed=27.9s

  [566/21087] intraday_0566.csv.gz  in=148,175,781 out=0 elapsed=28.0s

  [567/21087] intraday_0568.csv.gz  in=148,196,790 out=0 elapsed=28.0s

  [568/21087] intraday_0567.csv.gz  in=148,219,961 out=0 elapsed=28.0s

  [569/21087] intraday_0569.csv.gz  in=148,251,292 out=0 elapsed=28.0s

  [570/21087] intraday_0570.csv.gz  in=148,284,544 out=0 elapsed=28.0s

  [571/21087] intraday_0572.csv.gz  in=148,308,858 out=0 elapsed=28.0s

  [572/21087] intraday_0573.csv.gz  in=148,335,163 out=0 elapsed=28.0s

  [573/21087] intraday_0571.csv.gz  in=148,367,608 out=0 elapsed=28.0s

  [574/21087] intraday_0574.csv.gz  in=148,395,071 out=0 elapsed=28.0s

  [575/21087] intraday_0575.csv.gz  in=148,428,911 out=0 elapsed=28.1s

  [576/21087] intraday_0576.csv.gz  in=148,459,676 out=0 elapsed=28.1s

  [577/21087] intraday_0577.csv.gz  in=148,485,209 out=0 elapsed=28.1s

  [578/21087] intraday_0578.csv.gz  in=148,517,233 out=0 elapsed=28.1s

  [579/21087] intraday_0580.csv.gz  in=148,543,926 out=0 elapsed=28.1s

  [580/21087] intraday_0581.csv.gz  in=148,576,672 out=0 elapsed=28.1s

  [581/21087] intraday_0582.csv.gz  in=148,607,706 out=0 elapsed=28.1s

  [582/21087] intraday_0579.csv.gz  in=148,659,685 out=0 elapsed=28.1s

  [583/21087] intraday_0583.csv.gz  in=148,688,678 out=0 elapsed=28.2s

  [584/21087] intraday_0585.csv.gz  in=148,714,730 out=0 elapsed=28.2s

  [585/21087] intraday_0584.csv.gz  in=148,745,268 out=0 elapsed=28.2s

  [586/21087] intraday_0586.csv.gz  in=148,772,890 out=0 elapsed=28.2s

  [587/21087] intraday_0587.csv.gz  in=148,798,828 out=0 elapsed=28.2s

  [588/21087] intraday_0591.csv.gz  in=148,826,643 out=0 elapsed=28.2s

  [589/21087] intraday_0590.csv.gz  in=148,857,581 out=0 elapsed=28.2s

  [590/21087] intraday_0589.csv.gz  in=148,886,729 out=0 elapsed=28.2s

  [591/21087] intraday_0588.csv.gz  in=148,938,696 out=0 elapsed=28.2s

  [592/21087] intraday_0592.csv.gz  in=148,966,176 out=0 elapsed=28.3s

  [593/21087] intraday_0594.csv.gz  in=148,992,313 out=0 elapsed=28.3s

  [594/21087] intraday_0595.csv.gz  in=149,019,311 out=0 elapsed=28.3s

  [595/21087] intraday_0593.csv.gz  in=149,055,519 out=0 elapsed=28.3s

  [596/21087] intraday_0596.csv.gz  in=149,080,692 out=0 elapsed=28.3s

  [597/21087] intraday_0597.csv.gz  in=149,107,419 out=0 elapsed=28.3s

  [598/21087] intraday_0599.csv.gz  in=149,133,905 out=0 elapsed=28.3s

  [599/21087] intraday_0598.csv.gz  in=149,161,545 out=0 elapsed=28.3s

  [600/21087] intraday_0601.csv.gz  in=149,185,905 out=0 elapsed=28.3s

  [601/21087] intraday_0600.csv.gz  in=149,210,192 out=0 elapsed=28.3s

  [602/21087] intraday_0602.csv.gz  in=149,232,632 out=0 elapsed=28.4s

  [603/21087] intraday_0603.csv.gz  in=149,266,332 out=0 elapsed=28.4s

  [604/21087] intraday_0604.csv.gz  in=149,292,076 out=0 elapsed=28.4s

  [605/21087] intraday_0605.csv.gz  in=149,320,593 out=0 elapsed=28.4s

  [606/21087] intraday_0606.csv.gz  in=149,352,504 out=0 elapsed=28.4s

  [607/21087] intraday_0608.csv.gz  in=149,375,298 out=0 elapsed=28.4s

  [608/21087] intraday_0607.csv.gz  in=149,423,867 out=0 elapsed=28.4s

  [609/21087] intraday_0609.csv.gz  in=149,449,906 out=0 elapsed=28.4s

  [610/21087] intraday_0610.csv.gz  in=149,475,762 out=0 elapsed=28.4s

  [611/21087] intraday_0612.csv.gz  in=149,498,462 out=0 elapsed=28.4s

  [612/21087] intraday_0611.csv.gz  in=149,528,210 out=0 elapsed=28.4s

  [613/21087] intraday_0613.csv.gz  in=149,549,726 out=0 elapsed=28.5s

  [614/21087] intraday_0614.csv.gz  in=149,575,053 out=0 elapsed=28.5s

  [615/21087] intraday_0615.csv.gz  in=149,609,820 out=0 elapsed=28.5s

  [616/21087] intraday_0616.csv.gz  in=149,634,484 out=0 elapsed=28.5s

  [617/21087] intraday_0618.csv.gz  in=149,654,673 out=0 elapsed=28.5s

  [618/21087] intraday_0617.csv.gz  in=149,684,038 out=0 elapsed=28.5s

  [619/21087] intraday_0619.csv.gz  in=149,706,447 out=0 elapsed=28.5s

  [620/21087] intraday_0622.csv.gz  in=149,733,290 out=0 elapsed=28.5s

  [621/21087] intraday_0620.csv.gz  in=149,768,779 out=0 elapsed=28.5s

  [622/21087] intraday_0621.csv.gz  in=149,803,181 out=0 elapsed=28.5s

  [623/21087] intraday_0623.csv.gz  in=149,829,559 out=0 elapsed=28.6s

  [624/21087] intraday_0624.csv.gz  in=149,859,203 out=0 elapsed=28.6s

  [625/21087] intraday_0626.csv.gz  in=149,889,582 out=0 elapsed=28.6s

  [626/21087] intraday_0625.csv.gz  in=149,918,669 out=0 elapsed=28.6s

  [627/21087] intraday_0627.csv.gz  in=149,952,541 out=0 elapsed=28.6s

  [628/21087] intraday_0628.csv.gz  in=149,987,266 out=0 elapsed=28.6s

  [629/21087] intraday_0629.csv.gz  in=150,021,198 out=0 elapsed=28.6s

  [630/21087] intraday_0630.csv.gz  in=150,051,815 out=0 elapsed=28.6s

  [631/21087] intraday_0631.csv.gz  in=150,082,344 out=0 elapsed=28.6s

  [632/21087] intraday_0632.csv.gz  in=150,109,334 out=0 elapsed=28.6s

  [633/21087] intraday_0633.csv.gz  in=150,137,613 out=0 elapsed=28.7s

  [634/21087] intraday_0634.csv.gz  in=150,170,587 out=0 elapsed=28.7s

  [635/21087] intraday_0635.csv.gz  in=150,198,877 out=0 elapsed=28.7s

  [636/21087] intraday_0636.csv.gz  in=150,223,517 out=0 elapsed=28.7s

  [637/21087] intraday_0637.csv.gz  in=150,254,101 out=0 elapsed=28.7s

  [638/21087] intraday_0638.csv.gz  in=150,287,667 out=0 elapsed=28.7s

  [639/21087] intraday_0639.csv.gz  in=150,316,577 out=0 elapsed=28.7s

  [640/21087] intraday_0640.csv.gz  in=150,344,888 out=0 elapsed=28.7s

  [641/21087] intraday_0641.csv.gz  in=150,374,658 out=0 elapsed=28.7s

  [642/21087] intraday_0642.csv.gz  in=150,406,279 out=0 elapsed=28.7s

  [643/21087] intraday_0643.csv.gz  in=150,440,063 out=0 elapsed=28.8s

  [644/21087] intraday_0644.csv.gz  in=150,471,135 out=0 elapsed=28.8s

  [645/21087] intraday_0645.csv.gz  in=150,504,092 out=0 elapsed=28.8s

  [646/21087] intraday_0646.csv.gz  in=150,530,150 out=0 elapsed=28.8s

  [647/21087] intraday_0647.csv.gz  in=150,559,265 out=0 elapsed=28.8s

  [648/21087] intraday_0648.csv.gz  in=150,588,431 out=0 elapsed=28.8s

  [649/21087] intraday_0649.csv.gz  in=150,616,816 out=0 elapsed=28.8s

  [650/21087] intraday_0650.csv.gz  in=150,647,955 out=0 elapsed=28.8s

  [651/21087] intraday_0651.csv.gz  in=150,672,868 out=0 elapsed=28.8s

  [652/21087] intraday_0652.csv.gz  in=150,705,622 out=0 elapsed=28.8s

  [653/21087] intraday_0654.csv.gz  in=150,732,794 out=0 elapsed=28.8s

  [654/21087] intraday_0653.csv.gz  in=150,767,795 out=0 elapsed=28.8s

  [655/21087] intraday_0655.csv.gz  in=150,796,374 out=0 elapsed=28.9s

  [656/21087] intraday_0656.csv.gz  in=150,827,694 out=0 elapsed=28.9s

  [657/21087] intraday_0657.csv.gz  in=150,854,681 out=0 elapsed=28.9s

  [658/21087] intraday_0658.csv.gz  in=150,880,261 out=0 elapsed=28.9s

  [659/21087] intraday_0659.csv.gz  in=150,912,920 out=0 elapsed=28.9s

  [660/21087] intraday_0660.csv.gz  in=150,940,951 out=0 elapsed=29.0s

  [661/21087] intraday_0662.csv.gz  in=150,967,623 out=0 elapsed=29.0s

  [662/21087] intraday_0663.csv.gz  in=150,997,830 out=0 elapsed=29.0s

  [663/21087] intraday_0661.csv.gz  in=151,050,073 out=0 elapsed=29.0s

  [664/21087] intraday_0664.csv.gz  in=151,082,311 out=0 elapsed=29.0s

  [665/21087] intraday_0666.csv.gz  in=151,115,221 out=0 elapsed=29.0s

  [666/21087] intraday_0665.csv.gz  in=151,145,019 out=0 elapsed=29.0s

  [667/21087] intraday_0667.csv.gz  in=151,180,660 out=0 elapsed=29.0s

  [668/21087] intraday_0668.csv.gz  in=151,209,545 out=0 elapsed=29.1s

  [669/21087] intraday_0669.csv.gz  in=151,238,489 out=0 elapsed=29.1s

  [670/21087] intraday_0670.csv.gz  in=151,268,576 out=0 elapsed=29.1s

  [671/21087] intraday_0671.csv.gz  in=151,301,299 out=0 elapsed=29.1s

  [672/21087] intraday_0672.csv.gz  in=151,330,979 out=0 elapsed=29.1s

  [673/21087] intraday_0673.csv.gz  in=151,354,334 out=0 elapsed=29.1s

  [674/21087] intraday_0675.csv.gz  in=151,374,813 out=0 elapsed=29.1s

  [675/21087] intraday_0674.csv.gz  in=151,406,524 out=0 elapsed=29.1s

  [676/21087] intraday_0676.csv.gz  in=151,429,101 out=0 elapsed=29.1s

  [677/21087] intraday_0677.csv.gz  in=151,447,334 out=0 elapsed=29.1s

  [678/21087] intraday_0681.csv.gz  in=151,566,858 out=0 elapsed=29.2s

  [679/21087] intraday_0680.csv.gz  in=151,694,372 out=0 elapsed=29.2s

  [680/21087] intraday_0679.csv.gz  in=151,854,187 out=0 elapsed=29.2s

  [681/21087] intraday_0678.csv.gz  in=152,035,572 out=0 elapsed=29.2s

  [682/21087] intraday_0682.csv.gz  in=152,183,889 out=0 elapsed=29.3s

  [683/21087] intraday_0684.csv.gz  in=152,303,931 out=0 elapsed=29.3s

  [684/21087] intraday_0685.csv.gz  in=152,436,248 out=0 elapsed=29.4s

  [685/21087] intraday_0683.csv.gz  in=152,597,012 out=0 elapsed=29.4s

  [686/21087] intraday_0686.csv.gz  in=152,741,778 out=0 elapsed=29.4s

  [687/21087] intraday_0687.csv.gz  in=152,884,704 out=0 elapsed=29.4s

  [688/21087] intraday_0688.csv.gz  in=153,012,576 out=0 elapsed=29.5s

  [689/21087] intraday_0689.csv.gz  in=153,154,517 out=0 elapsed=29.5s

  [690/21087] intraday_0692.csv.gz  in=153,255,887 out=0 elapsed=29.5s

  [691/21087] intraday_0691.csv.gz  in=153,383,278 out=0 elapsed=29.5s

  [692/21087] intraday_0690.csv.gz  in=153,542,476 out=0 elapsed=29.6s

  [693/21087] intraday_0693.csv.gz  in=153,725,767 out=0 elapsed=29.6s

  [694/21087] intraday_0694.csv.gz  in=153,864,268 out=0 elapsed=29.6s

  [695/21087] intraday_0695.csv.gz  in=153,997,703 out=0 elapsed=29.6s

  [696/21087] intraday_0696.csv.gz  in=154,134,404 out=0 elapsed=29.7s

  [697/21087] intraday_0697.csv.gz  in=154,268,443 out=0 elapsed=29.7s

  [698/21087] intraday_0699.csv.gz  in=154,401,727 out=0 elapsed=29.7s

  [699/21087] intraday_0698.csv.gz  in=154,540,161 out=0 elapsed=29.8s

  [700/21087] intraday_0700.csv.gz  in=154,667,673 out=0 elapsed=29.8s

  [701/21087] intraday_0701.csv.gz  in=154,856,762 out=0 elapsed=29.8s

  [702/21087] intraday_0703.csv.gz  in=154,982,932 out=0 elapsed=29.9s

  [703/21087] intraday_0704.csv.gz  in=155,100,774 out=0 elapsed=29.9s

  [704/21087] intraday_0702.csv.gz  in=155,240,129 out=0 elapsed=29.9s

  [705/21087] intraday_0705.csv.gz  in=155,402,243 out=0 elapsed=29.9s

  [706/21087] intraday_0708.csv.gz  in=155,522,748 out=0 elapsed=30.0s

  [707/21087] intraday_0707.csv.gz  in=155,681,342 out=0 elapsed=30.0s

  [708/21087] intraday_0706.csv.gz  in=155,861,235 out=0 elapsed=30.0s

  [709/21087] intraday_0709.csv.gz  in=155,997,571 out=0 elapsed=30.0s

  [710/21087] intraday_0710.csv.gz  in=156,136,449 out=0 elapsed=30.1s

  [711/21087] intraday_0712.csv.gz  in=156,273,222 out=0 elapsed=30.1s

  [712/21087] intraday_0711.csv.gz  in=156,496,706 out=0 elapsed=30.1s

  [713/21087] intraday_0713.csv.gz  in=156,619,873 out=0 elapsed=30.1s

  [714/21087] intraday_0714.csv.gz  in=156,768,452 out=0 elapsed=30.2s

  [715/21087] intraday_0715.csv.gz  in=156,903,093 out=0 elapsed=30.2s

  [716/21087] intraday_0716.csv.gz  in=157,041,253 out=0 elapsed=30.2s

  [717/21087] intraday_0717.csv.gz  in=157,196,573 out=0 elapsed=30.3s

  [718/21087] intraday_0719.csv.gz  in=157,329,992 out=0 elapsed=30.3s

  [719/21087] intraday_0718.csv.gz  in=157,478,345 out=0 elapsed=30.3s

  [720/21087] intraday_0721.csv.gz  in=157,602,475 out=0 elapsed=30.4s

  [721/21087] intraday_0720.csv.gz  in=157,766,245 out=0 elapsed=30.4s

  [722/21087] intraday_0722.csv.gz  in=157,888,287 out=0 elapsed=30.4s

  [723/21087] intraday_0723.csv.gz  in=158,046,991 out=0 elapsed=30.4s

  [724/21087] intraday_0724.csv.gz  in=158,185,787 out=0 elapsed=30.5s

  [725/21087] intraday_0725.csv.gz  in=158,327,072 out=0 elapsed=30.5s

  [726/21087] intraday_0726.csv.gz  in=158,468,376 out=0 elapsed=30.5s

  [727/21087] intraday_0727.csv.gz  in=158,616,553 out=0 elapsed=30.5s

  [728/21087] intraday_0730.csv.gz  in=158,652,357 out=0 elapsed=30.5s

  [729/21087] intraday_0729.csv.gz  in=158,764,658 out=0 elapsed=30.6s

  [730/21087] intraday_0728.csv.gz  in=158,897,969 out=0 elapsed=30.6s

  [731/21087] intraday_0731.csv.gz  in=159,046,471 out=0 elapsed=30.6s

  [732/21087] intraday_0732.csv.gz  in=159,182,736 out=0 elapsed=30.6s

  [733/21087] intraday_0733.csv.gz  in=159,312,419 out=0 elapsed=30.6s

  [734/21087] intraday_0734.csv.gz  in=159,445,206 out=0 elapsed=30.7s

  [735/21087] intraday_0736.csv.gz  in=159,565,824 out=0 elapsed=30.7s

  [736/21087] intraday_0735.csv.gz  in=159,729,226 out=0 elapsed=30.7s

  [737/21087] intraday_0737.csv.gz  in=159,875,249 out=0 elapsed=30.7s

  [738/21087] intraday_0738.csv.gz  in=159,994,738 out=0 elapsed=30.8s

  [739/21087] intraday_0739.csv.gz  in=160,108,715 out=0 elapsed=30.9s

  [740/21087] intraday_0740.csv.gz  in=160,251,867 out=0 elapsed=30.9s

  [741/21087] intraday_0741.csv.gz  in=160,398,732 out=0 elapsed=30.9s

  [742/21087] intraday_0742.csv.gz  in=160,541,414 out=0 elapsed=30.9s

  [743/21087] intraday_0743.csv.gz  in=160,694,567 out=0 elapsed=31.0s

  [744/21087] intraday_0744.csv.gz  in=160,847,878 out=0 elapsed=31.0s

  [745/21087] intraday_0746.csv.gz  in=160,981,611 out=0 elapsed=31.0s

  [746/21087] intraday_0745.csv.gz  in=161,134,735 out=0 elapsed=31.0s

  [747/21087] intraday_0747.csv.gz  in=161,275,438 out=0 elapsed=31.1s

  [748/21087] intraday_0749.csv.gz  in=161,392,280 out=0 elapsed=31.1s

  [749/21087] intraday_0748.csv.gz  in=161,530,783 out=0 elapsed=31.1s

  [750/21087] intraday_0750.csv.gz  in=161,658,304 out=0 elapsed=31.1s

  [751/21087] intraday_0751.csv.gz  in=161,769,784 out=0 elapsed=31.2s

  [752/21087] intraday_0752.csv.gz  in=161,904,477 out=0 elapsed=31.2s

  [753/21087] intraday_0753.csv.gz  in=162,036,013 out=0 elapsed=31.2s

  [754/21087] intraday_0754.csv.gz  in=162,173,091 out=0 elapsed=31.2s

  [755/21087] intraday_0755.csv.gz  in=162,296,789 out=0 elapsed=31.2s

  [756/21087] intraday_0756.csv.gz  in=162,402,013 out=0 elapsed=31.3s

  [757/21087] intraday_0757.csv.gz  in=162,533,048 out=0 elapsed=31.3s

  [758/21087] intraday_0758.csv.gz  in=162,707,166 out=0 elapsed=31.4s

  [759/21087] intraday_0759.csv.gz  in=162,866,044 out=0 elapsed=31.4s

  [760/21087] intraday_0760.csv.gz  in=162,999,521 out=0 elapsed=31.4s

  [761/21087] intraday_0761.csv.gz  in=163,114,446 out=0 elapsed=31.4s

  [762/21087] intraday_0762.csv.gz  in=163,249,987 out=0 elapsed=31.5s

  [763/21087] intraday_0763.csv.gz  in=163,397,708 out=0 elapsed=31.5s

  [764/21087] intraday_0764.csv.gz  in=163,552,555 out=0 elapsed=31.5s

  [765/21087] intraday_0765.csv.gz  in=163,688,782 out=0 elapsed=31.5s

  [766/21087] intraday_0766.csv.gz  in=163,846,217 out=0 elapsed=31.6s

  [767/21087] intraday_0767.csv.gz  in=163,993,651 out=0 elapsed=31.6s

  [768/21087] intraday_0768.csv.gz  in=164,150,804 out=0 elapsed=31.6s

  [769/21087] intraday_0769.csv.gz  in=164,303,234 out=0 elapsed=31.6s

  [770/21087] intraday_0770.csv.gz  in=164,436,536 out=0 elapsed=31.7s

  [771/21087] intraday_0771.csv.gz  in=164,570,092 out=0 elapsed=31.7s

  [772/21087] intraday_0773.csv.gz  in=164,700,589 out=0 elapsed=31.7s

  [773/21087] intraday_0772.csv.gz  in=164,847,419 out=0 elapsed=31.7s

  [774/21087] intraday_0774.csv.gz  in=164,988,419 out=0 elapsed=31.8s

  [775/21087] intraday_0775.csv.gz  in=165,118,612 out=0 elapsed=31.8s

  [776/21087] intraday_0777.csv.gz  in=165,255,747 out=0 elapsed=31.8s

  [777/21087] intraday_0776.csv.gz  in=165,422,237 out=0 elapsed=31.9s

  [778/21087] intraday_0778.csv.gz  in=165,571,124 out=0 elapsed=31.9s

  [779/21087] intraday_0779.csv.gz  in=165,730,454 out=0 elapsed=31.9s

  [780/21087] intraday_0780.csv.gz  in=165,861,510 out=0 elapsed=32.0s

  [781/21087] intraday_0781.csv.gz  in=165,998,218 out=0 elapsed=32.0s

  [782/21087] intraday_0782.csv.gz  in=166,166,029 out=0 elapsed=32.0s

  [783/21087] intraday_0783.csv.gz  in=166,322,779 out=0 elapsed=32.0s

  [784/21087] intraday_0784.csv.gz  in=166,461,856 out=0 elapsed=32.1s

  [785/21087] intraday_0785.csv.gz  in=166,594,735 out=0 elapsed=32.1s

  [786/21087] intraday_0787.csv.gz  in=166,726,657 out=0 elapsed=32.1s

  [787/21087] intraday_0786.csv.gz  in=166,865,536 out=0 elapsed=32.1s

  [788/21087] intraday_0789.csv.gz  in=166,929,889 out=0 elapsed=32.1s

  [789/21087] intraday_0788.csv.gz  in=167,078,657 out=0 elapsed=32.2s

  [790/21087] intraday_0791.csv.gz  in=167,239,682 out=0 elapsed=32.2s

  [791/21087] intraday_0790.csv.gz  in=167,405,798 out=0 elapsed=32.2s

  [792/21087] intraday_0792.csv.gz  in=167,571,437 out=0 elapsed=32.2s

  [793/21087] intraday_0793.csv.gz  in=167,710,769 out=0 elapsed=32.3s

  [794/21087] intraday_0795.csv.gz  in=167,843,169 out=0 elapsed=32.3s

  [795/21087] intraday_0796.csv.gz  in=167,967,788 out=0 elapsed=32.3s

  [796/21087] intraday_0794.csv.gz  in=168,118,552 out=0 elapsed=32.3s

  [797/21087] intraday_0797.csv.gz  in=168,273,090 out=0 elapsed=32.4s

  [798/21087] intraday_0798.csv.gz  in=168,419,998 out=0 elapsed=32.5s

  [799/21087] intraday_0800.csv.gz  in=168,564,380 out=0 elapsed=32.5s

  [800/21087] intraday_0801.csv.gz  in=168,707,161 out=0 elapsed=32.5s

  [801/21087] intraday_0799.csv.gz  in=168,875,476 out=0 elapsed=32.5s

  [802/21087] intraday_0802.csv.gz  in=169,018,762 out=0 elapsed=32.6s

  [803/21087] intraday_0804.csv.gz  in=169,159,481 out=0 elapsed=32.6s

  [804/21087] intraday_0803.csv.gz  in=169,326,594 out=0 elapsed=32.6s

  [805/21087] intraday_0805.csv.gz  in=169,500,098 out=0 elapsed=32.6s

  [806/21087] intraday_0806.csv.gz  in=169,648,754 out=0 elapsed=32.7s

  [807/21087] intraday_0807.csv.gz  in=169,786,706 out=0 elapsed=32.7s

  [808/21087] intraday_0808.csv.gz  in=169,941,973 out=0 elapsed=32.7s

  [809/21087] intraday_0809.csv.gz  in=170,069,026 out=0 elapsed=32.7s

  [810/21087] intraday_0810.csv.gz  in=170,199,485 out=0 elapsed=32.8s

  [811/21087] intraday_0813.csv.gz  in=170,302,526 out=0 elapsed=32.8s

  [812/21087] intraday_0811.csv.gz  in=170,436,393 out=0 elapsed=32.8s

  [813/21087] intraday_0812.csv.gz  in=170,569,218 out=0 elapsed=32.8s

  [814/21087] intraday_0817.csv.gz  in=170,583,417 out=0 elapsed=32.8s

  [815/21087] intraday_0816.csv.gz  in=170,622,032 out=0 elapsed=32.9s

  [816/21087] intraday_0818.csv.gz  in=170,636,027 out=0 elapsed=32.9s

  [817/21087] intraday_0814.csv.gz  in=170,733,336 out=0 elapsed=32.9s

  [818/21087] intraday_0819.csv.gz  in=170,745,538 out=0 elapsed=32.9s

  [819/21087] intraday_0815.csv.gz  in=170,856,718 out=0 elapsed=32.9s

  [820/21087] intraday_0820.csv.gz  in=170,873,117 out=0 elapsed=32.9s

  [821/21087] intraday_0821.csv.gz  in=170,888,041 out=0 elapsed=32.9s

  [822/21087] intraday_0822.csv.gz  in=170,902,088 out=0 elapsed=32.9s

  [823/21087] intraday_0823.csv.gz  in=170,912,904 out=0 elapsed=32.9s

  [824/21087] intraday_0825.csv.gz  in=170,930,229 out=0 elapsed=32.9s

  [825/21087] intraday_0824.csv.gz  in=170,951,617 out=0 elapsed=32.9s

  [826/21087] intraday_0826.csv.gz  in=170,965,004 out=0 elapsed=33.0s

  [827/21087] intraday_0827.csv.gz  in=170,974,625 out=0 elapsed=33.0s

  [828/21087] intraday_0829.csv.gz  in=170,987,981 out=0 elapsed=33.0s

  [829/21087] intraday_0830.csv.gz  in=170,998,135 out=0 elapsed=33.0s

  [830/21087] intraday_0831.csv.gz  in=171,007,658 out=0 elapsed=33.0s

  [831/21087] intraday_0828.csv.gz  in=171,034,647 out=0 elapsed=33.0s

  [832/21087] intraday_0832.csv.gz  in=171,048,427 out=0 elapsed=33.0s

  [833/21087] intraday_0834.csv.gz  in=171,061,254 out=0 elapsed=33.0s

  [834/21087] intraday_0833.csv.gz  in=171,073,732 out=0 elapsed=33.0s

  [835/21087] intraday_0835.csv.gz  in=171,085,053 out=0 elapsed=33.0s

  [836/21087] intraday_0836.csv.gz  in=171,100,482 out=0 elapsed=33.0s

  [837/21087] intraday_0837.csv.gz  in=171,113,243 out=0 elapsed=33.0s

  [838/21087] intraday_0838.csv.gz  in=171,126,352 out=0 elapsed=33.0s

  [839/21087] intraday_0839.csv.gz  in=171,138,213 out=0 elapsed=33.0s

  [840/21087] intraday_0840.csv.gz  in=171,150,913 out=0 elapsed=33.1s

  [841/21087] intraday_0842.csv.gz  in=171,161,481 out=0 elapsed=33.1s

  [842/21087] intraday_0841.csv.gz  in=171,181,810 out=0 elapsed=33.1s

  [843/21087] intraday_0843.csv.gz  in=171,194,078 out=0 elapsed=33.1s

  [844/21087] intraday_0844.csv.gz  in=171,207,678 out=0 elapsed=33.1s

  [845/21087] intraday_0845.csv.gz  in=171,222,799 out=0 elapsed=33.1s

  [846/21087] intraday_0846.csv.gz  in=171,237,060 out=0 elapsed=33.1s

  [847/21087] intraday_0847.csv.gz  in=171,249,394 out=0 elapsed=33.1s

  [848/21087] intraday_0848.csv.gz  in=171,262,538 out=0 elapsed=33.1s

  [849/21087] intraday_0849.csv.gz  in=171,275,034 out=0 elapsed=33.1s

  [850/21087] intraday_0850.csv.gz  in=171,287,665 out=0 elapsed=33.1s

  [851/21087] intraday_0851.csv.gz  in=171,299,233 out=0 elapsed=33.1s

  [852/21087] intraday_0853.csv.gz  in=171,311,047 out=0 elapsed=33.2s

  [853/21087] intraday_0852.csv.gz  in=171,333,791 out=0 elapsed=33.2s

  [854/21087] intraday_0854.csv.gz  in=171,344,863 out=0 elapsed=33.2s

  [855/21087] intraday_0855.csv.gz  in=171,367,005 out=0 elapsed=33.2s

  [856/21087] intraday_0856.csv.gz  in=171,379,672 out=0 elapsed=33.2s

  [857/21087] intraday_0857.csv.gz  in=171,392,578 out=0 elapsed=33.2s

  [858/21087] intraday_0858.csv.gz  in=171,405,058 out=0 elapsed=33.2s

  [859/21087] intraday_0859.csv.gz  in=171,419,692 out=0 elapsed=33.2s

  [860/21087] intraday_0860.csv.gz  in=171,431,803 out=0 elapsed=33.2s

  [861/21087] intraday_0861.csv.gz  in=171,443,753 out=0 elapsed=33.2s

  [862/21087] intraday_0862.csv.gz  in=171,455,819 out=0 elapsed=33.2s

  [863/21087] intraday_0863.csv.gz  in=171,468,222 out=0 elapsed=33.2s

  [864/21087] intraday_0864.csv.gz  in=171,482,017 out=0 elapsed=33.2s

  [865/21087] intraday_0865.csv.gz  in=171,498,820 out=0 elapsed=33.3s

  [866/21087] intraday_0866.csv.gz  in=171,510,495 out=0 elapsed=33.3s

  [867/21087] intraday_0867.csv.gz  in=171,525,878 out=0 elapsed=33.3s

  [868/21087] intraday_0868.csv.gz  in=171,535,560 out=0 elapsed=33.3s

  [869/21087] intraday_0869.csv.gz  in=171,548,360 out=0 elapsed=33.3s

  [870/21087] intraday_0870.csv.gz  in=171,560,121 out=0 elapsed=33.3s

  [871/21087] intraday_0871.csv.gz  in=171,570,872 out=0 elapsed=33.3s

  [872/21087] intraday_0872.csv.gz  in=171,582,750 out=0 elapsed=33.3s

  [873/21087] intraday_0873.csv.gz  in=171,595,221 out=0 elapsed=33.3s

  [874/21087] intraday_0874.csv.gz  in=171,608,084 out=0 elapsed=33.3s

  [875/21087] intraday_0875.csv.gz  in=171,620,028 out=0 elapsed=33.3s

  [876/21087] intraday_0876.csv.gz  in=171,630,652 out=0 elapsed=33.3s

  [877/21087] intraday_0877.csv.gz  in=171,640,867 out=0 elapsed=33.4s

  [878/21087] intraday_0878.csv.gz  in=171,651,507 out=0 elapsed=33.4s

  [879/21087] intraday_0879.csv.gz  in=171,664,546 out=0 elapsed=33.4s

  [880/21087] intraday_0880.csv.gz  in=171,677,195 out=0 elapsed=33.4s

  [881/21087] intraday_0881.csv.gz  in=171,692,003 out=0 elapsed=33.4s

  [882/21087] intraday_0882.csv.gz  in=171,705,429 out=0 elapsed=33.4s

  [883/21087] intraday_0883.csv.gz  in=171,716,945 out=0 elapsed=33.4s

  [884/21087] intraday_0884.csv.gz  in=171,727,599 out=0 elapsed=33.4s

  [885/21087] intraday_0885.csv.gz  in=171,739,848 out=0 elapsed=33.4s

  [886/21087] intraday_0886.csv.gz  in=171,751,580 out=0 elapsed=33.4s

  [887/21087] intraday_0887.csv.gz  in=171,764,466 out=0 elapsed=33.4s

  [888/21087] intraday_0888.csv.gz  in=171,777,220 out=0 elapsed=33.4s

  [889/21087] intraday_0889.csv.gz  in=171,788,961 out=0 elapsed=33.4s

  [890/21087] intraday_0891.csv.gz  in=171,801,065 out=0 elapsed=33.5s

  [891/21087] intraday_0890.csv.gz  in=171,812,341 out=0 elapsed=33.5s

  [892/21087] intraday_0892.csv.gz  in=171,823,805 out=0 elapsed=33.5s

  [893/21087] intraday_0893.csv.gz  in=171,834,942 out=0 elapsed=33.5s

  [894/21087] intraday_0894.csv.gz  in=171,844,703 out=0 elapsed=33.5s

  [895/21087] intraday_0895.csv.gz  in=171,855,495 out=0 elapsed=33.5s

  [896/21087] intraday_0896.csv.gz  in=171,866,627 out=0 elapsed=33.5s

  [897/21087] intraday_0897.csv.gz  in=171,882,683 out=0 elapsed=33.5s

  [898/21087] intraday_0898.csv.gz  in=171,895,642 out=0 elapsed=33.5s

  [899/21087] intraday_0899.csv.gz  in=171,906,820 out=0 elapsed=33.5s

  [900/21087] intraday_0900.csv.gz  in=171,918,523 out=0 elapsed=33.5s

  [901/21087] intraday_0901.csv.gz  in=171,931,030 out=0 elapsed=33.5s

  [902/21087] intraday_0903.csv.gz  in=171,945,624 out=0 elapsed=33.6s

  [903/21087] intraday_0902.csv.gz  in=171,958,228 out=0 elapsed=33.6s

  [904/21087] intraday_0904.csv.gz  in=171,970,669 out=0 elapsed=33.6s

  [905/21087] intraday_0905.csv.gz  in=171,985,253 out=0 elapsed=33.6s

  [906/21087] intraday_0906.csv.gz  in=171,999,586 out=0 elapsed=33.6s

  [907/21087] intraday_0907.csv.gz  in=172,011,979 out=0 elapsed=33.6s

  [908/21087] intraday_0908.csv.gz  in=172,025,210 out=0 elapsed=33.6s

  [909/21087] intraday_0909.csv.gz  in=172,037,663 out=0 elapsed=33.6s

  [910/21087] intraday_0910.csv.gz  in=172,050,205 out=0 elapsed=33.6s

  [911/21087] intraday_0911.csv.gz  in=172,062,369 out=0 elapsed=33.6s

  [912/21087] intraday_0912.csv.gz  in=172,074,088 out=0 elapsed=33.6s

  [913/21087] intraday_0913.csv.gz  in=172,087,236 out=0 elapsed=33.6s

  [914/21087] intraday_0914.csv.gz  in=172,098,538 out=0 elapsed=33.7s

  [915/21087] intraday_0916.csv.gz  in=172,109,680 out=0 elapsed=33.7s

  [916/21087] intraday_0915.csv.gz  in=172,121,855 out=0 elapsed=33.7s

  [917/21087] intraday_0917.csv.gz  in=172,134,361 out=0 elapsed=33.7s

  [918/21087] intraday_0918.csv.gz  in=172,146,865 out=0 elapsed=33.7s

  [919/21087] intraday_0919.csv.gz  in=172,158,436 out=0 elapsed=33.7s

  [920/21087] intraday_0920.csv.gz  in=172,171,440 out=0 elapsed=33.7s

  [921/21087] intraday_0921.csv.gz  in=172,185,852 out=0 elapsed=33.7s

  [922/21087] intraday_0922.csv.gz  in=172,198,803 out=0 elapsed=33.7s

  [923/21087] intraday_0923.csv.gz  in=172,209,928 out=0 elapsed=33.7s

  [924/21087] intraday_0924.csv.gz  in=172,222,572 out=0 elapsed=33.7s

  [925/21087] intraday_0925.csv.gz  in=172,236,557 out=0 elapsed=33.7s

  [926/21087] intraday_0926.csv.gz  in=172,248,876 out=0 elapsed=33.7s

  [927/21087] intraday_0927.csv.gz  in=172,260,868 out=0 elapsed=33.7s

  [928/21087] intraday_0928.csv.gz  in=172,274,527 out=0 elapsed=33.8s

  [929/21087] intraday_0929.csv.gz  in=172,288,263 out=0 elapsed=33.8s

  [930/21087] intraday_0930.csv.gz  in=172,300,820 out=0 elapsed=33.8s

  [931/21087] intraday_0931.csv.gz  in=172,314,019 out=0 elapsed=33.8s

  [932/21087] intraday_0932.csv.gz  in=172,327,186 out=0 elapsed=33.8s

  [933/21087] intraday_0933.csv.gz  in=172,337,937 out=0 elapsed=33.8s

  [934/21087] intraday_0934.csv.gz  in=172,348,617 out=0 elapsed=33.8s

  [935/21087] intraday_0936.csv.gz  in=172,361,570 out=0 elapsed=33.8s

  [936/21087] intraday_0935.csv.gz  in=172,375,984 out=0 elapsed=33.8s

  [937/21087] intraday_0937.csv.gz  in=172,391,434 out=0 elapsed=33.8s

  [938/21087] intraday_0938.csv.gz  in=172,403,487 out=0 elapsed=33.9s

  [939/21087] intraday_0940.csv.gz  in=172,415,056 out=0 elapsed=33.9s

  [940/21087] intraday_0939.csv.gz  in=172,428,760 out=0 elapsed=33.9s

  [941/21087] intraday_0941.csv.gz  in=172,441,679 out=0 elapsed=33.9s

  [942/21087] intraday_0942.csv.gz  in=172,456,071 out=0 elapsed=33.9s

  [943/21087] intraday_0944.csv.gz  in=172,470,100 out=0 elapsed=33.9s

  [944/21087] intraday_0945.csv.gz  in=172,482,097 out=0 elapsed=33.9s

  [945/21087] intraday_0943.csv.gz  in=172,503,363 out=0 elapsed=33.9s

  [946/21087] intraday_0946.csv.gz  in=172,517,214 out=0 elapsed=33.9s

  [947/21087] intraday_0947.csv.gz  in=172,527,681 out=0 elapsed=33.9s

  [948/21087] intraday_0949.csv.gz  in=172,539,672 out=0 elapsed=33.9s

  [949/21087] intraday_0948.csv.gz  in=172,551,621 out=0 elapsed=33.9s

  [950/21087] intraday_0950.csv.gz  in=172,563,487 out=0 elapsed=34.0s

  [951/21087] intraday_0951.csv.gz  in=172,571,876 out=0 elapsed=34.0s

  [952/21087] intraday_0954.csv.gz  in=172,574,116 out=0 elapsed=34.0s

  [953/21087] intraday_0952.csv.gz  in=172,582,607 out=0 elapsed=34.0s

  [954/21087] intraday_0953.csv.gz  in=172,594,176 out=0 elapsed=34.0s

  [955/21087] intraday_0956.csv.gz  in=172,608,443 out=0 elapsed=34.0s

  [956/21087] intraday_0955.csv.gz  in=172,623,524 out=0 elapsed=34.0s

  [957/21087] intraday_0957.csv.gz  in=172,635,211 out=0 elapsed=34.0s

  [958/21087] intraday_0958.csv.gz  in=172,657,646 out=0 elapsed=34.0s

  [959/21087] intraday_0959.csv.gz  in=172,672,377 out=0 elapsed=34.0s

  [960/21087] intraday_0960.csv.gz  in=172,686,888 out=0 elapsed=34.0s

  [961/21087] intraday_0961.csv.gz  in=172,703,954 out=0 elapsed=34.0s

  [962/21087] intraday_0962.csv.gz  in=172,716,282 out=0 elapsed=34.1s

  [963/21087] intraday_0963.csv.gz  in=172,729,667 out=0 elapsed=34.1s

  [964/21087] intraday_0964.csv.gz  in=172,744,539 out=0 elapsed=34.1s

  [965/21087] intraday_0965.csv.gz  in=172,758,327 out=0 elapsed=34.1s

  [966/21087] intraday_0966.csv.gz  in=172,780,437 out=0 elapsed=34.1s

  [967/21087] intraday_0967.csv.gz  in=172,794,415 out=0 elapsed=34.1s

  [968/21087] intraday_0968.csv.gz  in=172,806,586 out=0 elapsed=34.1s

  [969/21087] intraday_0969.csv.gz  in=172,816,729 out=0 elapsed=34.1s

  [970/21087] intraday_0970.csv.gz  in=172,830,592 out=0 elapsed=34.1s

  [971/21087] intraday_0971.csv.gz  in=172,842,612 out=0 elapsed=34.2s

  [972/21087] intraday_0972.csv.gz  in=172,856,089 out=0 elapsed=34.2s

  [973/21087] intraday_0973.csv.gz  in=172,876,609 out=0 elapsed=34.2s

  [974/21087] intraday_0974.csv.gz  in=172,888,244 out=0 elapsed=34.2s

  [975/21087] intraday_0975.csv.gz  in=172,913,743 out=0 elapsed=34.2s

  [976/21087] intraday_0977.csv.gz  in=172,925,667 out=0 elapsed=34.2s

  [977/21087] intraday_0976.csv.gz  in=172,937,964 out=0 elapsed=34.2s

  [978/21087] intraday_0978.csv.gz  in=172,951,142 out=0 elapsed=34.2s

  [979/21087] intraday_0980.csv.gz  in=172,961,989 out=0 elapsed=34.2s

  [980/21087] intraday_0981.csv.gz  in=172,975,120 out=0 elapsed=34.2s

  [981/21087] intraday_0982.csv.gz  in=172,988,287 out=0 elapsed=34.2s

  [982/21087] intraday_0979.csv.gz  in=173,037,190 out=0 elapsed=34.3s

  [983/21087] intraday_0983.csv.gz  in=173,052,965 out=0 elapsed=34.3s

  [984/21087] intraday_0985.csv.gz  in=173,065,457 out=0 elapsed=34.3s

  [985/21087] intraday_0984.csv.gz  in=173,080,108 out=0 elapsed=34.3s

  [986/21087] intraday_0986.csv.gz  in=173,092,348 out=0 elapsed=34.3s

  [987/21087] intraday_0988.csv.gz  in=173,105,709 out=0 elapsed=34.3s

  [988/21087] intraday_0989.csv.gz  in=173,117,385 out=0 elapsed=34.3s

  [989/21087] intraday_0987.csv.gz  in=173,149,418 out=0 elapsed=34.3s

  [990/21087] intraday_0990.csv.gz  in=173,161,035 out=0 elapsed=34.3s

  [991/21087] intraday_0991.csv.gz  in=173,174,144 out=0 elapsed=34.3s

  [992/21087] intraday_0992.csv.gz  in=173,184,929 out=0 elapsed=34.3s

  [993/21087] intraday_0993.csv.gz  in=173,196,319 out=0 elapsed=34.3s

  [994/21087] intraday_0994.csv.gz  in=173,210,070 out=0 elapsed=34.4s

  [995/21087] intraday_0995.csv.gz  in=173,221,998 out=0 elapsed=34.4s

  [996/21087] intraday_0996.csv.gz  in=173,235,726 out=0 elapsed=34.4s

  [997/21087] intraday_0998.csv.gz  in=173,246,623 out=0 elapsed=34.4s

  [998/21087] intraday_0997.csv.gz  in=173,262,519 out=0 elapsed=34.4s

  [999/21087] intraday_0999.csv.gz  in=173,274,768 out=0 elapsed=34.4s

  [1000/21087] intraday_1000.csv.gz  in=173,287,073 out=0 elapsed=34.4s

  [1001/21087] intraday_10000.csv.gz  in=173,298,407 out=0 elapsed=34.4s

  [1002/21087] intraday_10001.csv.gz  in=173,312,102 out=0 elapsed=34.4s

  [1003/21087] intraday_10002.csv.gz  in=173,324,401 out=0 elapsed=34.4s

  [1004/21087] intraday_10003.csv.gz  in=173,337,308 out=0 elapsed=34.4s

  [1005/21087] intraday_10004.csv.gz  in=173,354,361 out=0 elapsed=34.5s

  [1006/21087] intraday_10005.csv.gz  in=173,368,716 out=0 elapsed=34.5s

  [1007/21087] intraday_10006.csv.gz  in=173,387,818 out=0 elapsed=34.5s

  [1008/21087] intraday_10007.csv.gz  in=173,403,189 out=0 elapsed=34.5s

  [1009/21087] intraday_10009.csv.gz  in=173,416,053 out=0 elapsed=34.5s

  [1010/21087] intraday_10008.csv.gz  in=173,429,708 out=0 elapsed=34.5s

  [1011/21087] intraday_1001.csv.gz  in=173,445,201 out=0 elapsed=34.5s

  [1012/21087] intraday_10010.csv.gz  in=173,457,751 out=0 elapsed=34.5s

  [1013/21087] intraday_10011.csv.gz  in=173,468,274 out=0 elapsed=34.5s

  [1014/21087] intraday_10012.csv.gz  in=173,481,818 out=0 elapsed=34.5s

  [1015/21087] intraday_10013.csv.gz  in=173,492,257 out=0 elapsed=34.5s

  [1016/21087] intraday_10014.csv.gz  in=173,506,755 out=0 elapsed=34.5s

  [1017/21087] intraday_10015.csv.gz  in=173,520,633 out=0 elapsed=34.5s

  [1018/21087] intraday_10017.csv.gz  in=173,531,861 out=0 elapsed=34.6s

  [1019/21087] intraday_10016.csv.gz  in=173,548,138 out=0 elapsed=34.6s

  [1020/21087] intraday_10019.csv.gz  in=173,561,388 out=0 elapsed=34.6s

  [1021/21087] intraday_10018.csv.gz  in=173,572,270 out=0 elapsed=34.6s

  [1022/21087] intraday_1002.csv.gz  in=173,584,284 out=0 elapsed=34.6s

  [1023/21087] intraday_10020.csv.gz  in=173,596,447 out=0 elapsed=34.6s

  [1024/21087] intraday_10021.csv.gz  in=173,606,839 out=0 elapsed=34.6s

  [1025/21087] intraday_10022.csv.gz  in=173,622,477 out=0 elapsed=34.6s

  [1026/21087] intraday_10023.csv.gz  in=173,636,830 out=0 elapsed=34.6s

  [1027/21087] intraday_10024.csv.gz  in=173,650,340 out=0 elapsed=34.6s

  [1028/21087] intraday_10025.csv.gz  in=173,666,792 out=0 elapsed=34.7s

  [1029/21087] intraday_10026.csv.gz  in=173,678,186 out=0 elapsed=34.7s

  [1030/21087] intraday_10027.csv.gz  in=173,689,424 out=0 elapsed=34.7s

  [1031/21087] intraday_10028.csv.gz  in=173,702,370 out=0 elapsed=34.7s

  [1032/21087] intraday_10029.csv.gz  in=173,713,343 out=0 elapsed=34.7s

  [1033/21087] intraday_1003.csv.gz  in=173,724,417 out=0 elapsed=34.7s

  [1034/21087] intraday_10030.csv.gz  in=173,737,452 out=0 elapsed=34.7s

  [1035/21087] intraday_10031.csv.gz  in=173,745,417 out=0 elapsed=34.7s

  [1036/21087] intraday_10032.csv.gz  in=173,756,598 out=0 elapsed=34.7s

  [1037/21087] intraday_10033.csv.gz  in=173,765,209 out=0 elapsed=34.7s

  [1038/21087] intraday_10035.csv.gz  in=173,776,918 out=0 elapsed=34.7s

  [1039/21087] intraday_10034.csv.gz  in=173,791,702 out=0 elapsed=34.7s

  [1040/21087] intraday_10036.csv.gz  in=173,803,469 out=0 elapsed=34.7s

  [1041/21087] intraday_10037.csv.gz  in=173,813,914 out=0 elapsed=34.8s

  [1042/21087] intraday_10038.csv.gz  in=173,825,913 out=0 elapsed=34.8s

  [1043/21087] intraday_1004.csv.gz  in=173,840,091 out=0 elapsed=34.8s

  [1044/21087] intraday_10039.csv.gz  in=173,855,224 out=0 elapsed=34.8s

  [1045/21087] intraday_10040.csv.gz  in=173,870,194 out=0 elapsed=34.8s

  [1046/21087] intraday_10041.csv.gz  in=173,880,973 out=0 elapsed=34.8s

  [1047/21087] intraday_10042.csv.gz  in=173,895,383 out=0 elapsed=34.8s

  [1048/21087] intraday_10043.csv.gz  in=173,909,948 out=0 elapsed=34.8s

  [1049/21087] intraday_10044.csv.gz  in=173,922,978 out=0 elapsed=34.8s

  [1050/21087] intraday_10045.csv.gz  in=173,934,968 out=0 elapsed=34.8s

  [1051/21087] intraday_10046.csv.gz  in=173,948,577 out=0 elapsed=34.8s

  [1052/21087] intraday_10047.csv.gz  in=173,961,864 out=0 elapsed=34.8s

  [1053/21087] intraday_10048.csv.gz  in=173,972,289 out=0 elapsed=34.8s

  [1054/21087] intraday_10049.csv.gz  in=173,983,878 out=0 elapsed=34.8s

  [1055/21087] intraday_1005.csv.gz  in=173,996,009 out=0 elapsed=34.9s

  [1056/21087] intraday_10050.csv.gz  in=174,007,014 out=0 elapsed=34.9s

  [1057/21087] intraday_10051.csv.gz  in=174,022,551 out=0 elapsed=34.9s

  [1058/21087] intraday_10052.csv.gz  in=174,033,434 out=0 elapsed=34.9s

  [1059/21087] intraday_10054.csv.gz  in=174,046,193 out=0 elapsed=34.9s

  [1060/21087] intraday_10053.csv.gz  in=174,056,999 out=0 elapsed=34.9s

  [1061/21087] intraday_10055.csv.gz  in=174,070,268 out=0 elapsed=34.9s

  [1062/21087] intraday_10056.csv.gz  in=174,084,047 out=0 elapsed=34.9s

  [1063/21087] intraday_10057.csv.gz  in=174,096,010 out=0 elapsed=34.9s

  [1064/21087] intraday_10058.csv.gz  in=174,110,134 out=0 elapsed=34.9s

  [1065/21087] intraday_10059.csv.gz  in=174,124,151 out=0 elapsed=35.0s

  [1066/21087] intraday_1006.csv.gz  in=174,135,744 out=0 elapsed=35.0s

  [1067/21087] intraday_10060.csv.gz  in=174,147,864 out=0 elapsed=35.0s

  [1068/21087] intraday_10061.csv.gz  in=174,159,004 out=0 elapsed=35.0s

  [1069/21087] intraday_10062.csv.gz  in=174,169,216 out=0 elapsed=35.0s

  [1070/21087] intraday_10063.csv.gz  in=174,182,840 out=0 elapsed=35.0s

  [1071/21087] intraday_10064.csv.gz  in=174,196,788 out=0 elapsed=35.0s

  [1072/21087] intraday_10065.csv.gz  in=174,211,545 out=0 elapsed=35.0s

  [1073/21087] intraday_10067.csv.gz  in=174,222,754 out=0 elapsed=35.0s

  [1074/21087] intraday_10068.csv.gz  in=174,234,506 out=0 elapsed=35.0s

  [1075/21087] intraday_10066.csv.gz  in=174,251,887 out=0 elapsed=35.0s

  [1076/21087] intraday_10069.csv.gz  in=174,265,819 out=0 elapsed=35.1s

  [1077/21087] intraday_10070.csv.gz  in=174,277,133 out=0 elapsed=35.1s

  [1078/21087] intraday_1007.csv.gz  in=174,288,874 out=0 elapsed=35.1s

  [1079/21087] intraday_10071.csv.gz  in=174,302,221 out=0 elapsed=35.1s

  [1080/21087] intraday_10072.csv.gz  in=174,313,102 out=0 elapsed=35.1s

  [1081/21087] intraday_10073.csv.gz  in=174,325,425 out=0 elapsed=35.1s

  [1082/21087] intraday_10074.csv.gz  in=174,337,182 out=0 elapsed=35.1s

  [1083/21087] intraday_10075.csv.gz  in=174,349,131 out=0 elapsed=35.1s

  [1084/21087] intraday_10076.csv.gz  in=174,361,949 out=0 elapsed=35.1s

  [1085/21087] intraday_10077.csv.gz  in=174,374,462 out=0 elapsed=35.1s

  [1086/21087] intraday_10078.csv.gz  in=174,386,686 out=0 elapsed=35.1s

  [1087/21087] intraday_10079.csv.gz  in=174,400,188 out=0 elapsed=35.1s

  [1088/21087] intraday_10080.csv.gz  in=174,411,942 out=0 elapsed=35.2s

  [1089/21087] intraday_1008.csv.gz  in=174,424,526 out=0 elapsed=35.2s

  [1090/21087] intraday_10081.csv.gz  in=174,435,760 out=0 elapsed=35.2s

  [1091/21087] intraday_10082.csv.gz  in=174,448,352 out=0 elapsed=35.2s

  [1092/21087] intraday_10083.csv.gz  in=174,459,564 out=0 elapsed=35.2s

  [1093/21087] intraday_10084.csv.gz  in=174,470,737 out=0 elapsed=35.2s

  [1094/21087] intraday_10085.csv.gz  in=174,482,074 out=0 elapsed=35.2s

  [1095/21087] intraday_10086.csv.gz  in=174,495,205 out=0 elapsed=35.2s

  [1096/21087] intraday_10087.csv.gz  in=174,507,203 out=0 elapsed=35.2s

  [1097/21087] intraday_10088.csv.gz  in=174,523,964 out=0 elapsed=35.2s

  [1098/21087] intraday_10089.csv.gz  in=174,535,717 out=0 elapsed=35.2s

  [1099/21087] intraday_1009.csv.gz  in=174,548,204 out=0 elapsed=35.2s

  [1100/21087] intraday_10090.csv.gz  in=174,560,505 out=0 elapsed=35.2s

  [1101/21087] intraday_10091.csv.gz  in=174,579,580 out=0 elapsed=35.3s

  [1102/21087] intraday_10092.csv.gz  in=174,591,151 out=0 elapsed=35.3s

  [1103/21087] intraday_10093.csv.gz  in=174,602,807 out=0 elapsed=35.3s

  [1104/21087] intraday_10094.csv.gz  in=174,615,731 out=0 elapsed=35.3s

  [1105/21087] intraday_10095.csv.gz  in=174,627,995 out=0 elapsed=35.3s

  [1106/21087] intraday_10096.csv.gz  in=174,639,992 out=0 elapsed=35.3s

  [1107/21087] intraday_10097.csv.gz  in=174,652,795 out=0 elapsed=35.3s

  [1108/21087] intraday_10098.csv.gz  in=174,664,516 out=0 elapsed=35.3s

  [1109/21087] intraday_10099.csv.gz  in=174,674,900 out=0 elapsed=35.3s

  [1110/21087] intraday_1010.csv.gz  in=174,686,259 out=0 elapsed=35.3s

  [1111/21087] intraday_10100.csv.gz  in=174,701,061 out=0 elapsed=35.3s

  [1112/21087] intraday_10101.csv.gz  in=174,712,971 out=0 elapsed=35.4s

  [1113/21087] intraday_10102.csv.gz  in=174,727,209 out=0 elapsed=35.4s

  [1114/21087] intraday_10104.csv.gz  in=174,740,127 out=0 elapsed=35.4s

  [1115/21087] intraday_10103.csv.gz  in=174,757,104 out=0 elapsed=35.4s

  [1116/21087] intraday_10105.csv.gz  in=174,766,605 out=0 elapsed=35.4s

  [1117/21087] intraday_10106.csv.gz  in=174,779,150 out=0 elapsed=35.4s

  [1118/21087] intraday_10107.csv.gz  in=174,791,625 out=0 elapsed=35.4s

  [1119/21087] intraday_10108.csv.gz  in=174,805,362 out=0 elapsed=35.4s

  [1120/21087] intraday_10109.csv.gz  in=174,818,895 out=0 elapsed=35.4s

  [1121/21087] intraday_1011.csv.gz  in=174,832,910 out=0 elapsed=35.4s

  [1122/21087] intraday_10111.csv.gz  in=174,843,441 out=0 elapsed=35.4s

  [1123/21087] intraday_10110.csv.gz  in=174,856,747 out=0 elapsed=35.4s

  [1124/21087] intraday_10112.csv.gz  in=174,869,634 out=0 elapsed=35.4s

  [1125/21087] intraday_10113.csv.gz  in=174,880,777 out=0 elapsed=35.4s

  [1126/21087] intraday_10114.csv.gz  in=174,892,709 out=0 elapsed=35.5s

  [1127/21087] intraday_10115.csv.gz  in=174,904,120 out=0 elapsed=35.5s

  [1128/21087] intraday_10116.csv.gz  in=174,913,540 out=0 elapsed=35.5s

  [1129/21087] intraday_10117.csv.gz  in=174,924,577 out=0 elapsed=35.5s

  [1130/21087] intraday_10118.csv.gz  in=174,937,686 out=0 elapsed=35.5s

  [1131/21087] intraday_1012.csv.gz  in=174,950,266 out=0 elapsed=35.5s

  [1132/21087] intraday_10119.csv.gz  in=174,967,732 out=0 elapsed=35.5s

  [1133/21087] intraday_10120.csv.gz  in=174,980,833 out=0 elapsed=35.5s

  [1134/21087] intraday_10121.csv.gz  in=174,993,414 out=0 elapsed=35.5s

  [1135/21087] intraday_10122.csv.gz  in=175,008,191 out=0 elapsed=35.5s

  [1136/21087] intraday_10123.csv.gz  in=175,023,118 out=0 elapsed=35.5s

  [1137/21087] intraday_10124.csv.gz  in=175,035,241 out=0 elapsed=35.5s

  [1138/21087] intraday_10125.csv.gz  in=175,050,846 out=0 elapsed=35.5s

  [1139/21087] intraday_10126.csv.gz  in=175,061,503 out=0 elapsed=35.5s

  [1140/21087] intraday_10128.csv.gz  in=175,074,870 out=0 elapsed=35.6s

  [1141/21087] intraday_10127.csv.gz  in=175,086,727 out=0 elapsed=35.6s

  [1142/21087] intraday_10129.csv.gz  in=175,100,187 out=0 elapsed=35.6s

  [1143/21087] intraday_1013.csv.gz  in=175,111,971 out=0 elapsed=35.6s

  [1144/21087] intraday_10130.csv.gz  in=175,124,483 out=0 elapsed=35.6s

  [1145/21087] intraday_10131.csv.gz  in=175,136,810 out=0 elapsed=35.6s

  [1146/21087] intraday_10132.csv.gz  in=175,149,729 out=0 elapsed=35.6s

  [1147/21087] intraday_10133.csv.gz  in=175,161,959 out=0 elapsed=35.6s

  [1148/21087] intraday_10135.csv.gz  in=175,174,477 out=0 elapsed=35.6s

  [1149/21087] intraday_10134.csv.gz  in=175,187,272 out=0 elapsed=35.6s

  [1150/21087] intraday_10136.csv.gz  in=175,198,152 out=0 elapsed=35.6s

  [1151/21087] intraday_10137.csv.gz  in=175,210,624 out=0 elapsed=35.6s

  [1152/21087] intraday_10138.csv.gz  in=175,224,341 out=0 elapsed=35.6s

  [1153/21087] intraday_10139.csv.gz  in=175,238,312 out=0 elapsed=35.7s

  [1154/21087] intraday_1014.csv.gz  in=175,250,734 out=0 elapsed=35.7s

  [1155/21087] intraday_10140.csv.gz  in=175,263,520 out=0 elapsed=35.7s

  [1156/21087] intraday_10141.csv.gz  in=175,274,722 out=0 elapsed=35.7s

  [1157/21087] intraday_10144.csv.gz  in=175,277,323 out=0 elapsed=35.7s

  [1158/21087] intraday_10143.csv.gz  in=175,290,042 out=0 elapsed=35.7s

  [1159/21087] intraday_10142.csv.gz  in=175,304,744 out=0 elapsed=35.7s

  [1160/21087] intraday_10146.csv.gz  in=175,385,002 out=0 elapsed=35.7s

  [1161/21087] intraday_10148.csv.gz  in=175,452,998 out=0 elapsed=35.8s

  [1162/21087] intraday_10145.csv.gz  in=175,556,139 out=0 elapsed=35.8s

  [1163/21087] intraday_10147.csv.gz  in=175,646,836 out=0 elapsed=35.8s

  [1164/21087] intraday_1015.csv.gz  in=175,658,448 out=0 elapsed=35.8s

  [1165/21087] intraday_10149.csv.gz  in=175,742,690 out=0 elapsed=35.8s

  [1166/21087] intraday_10150.csv.gz  in=175,837,504 out=0 elapsed=35.8s

  [1167/21087] intraday_10152.csv.gz  in=175,919,447 out=0 elapsed=35.9s

  [1168/21087] intraday_10151.csv.gz  in=176,024,115 out=0 elapsed=35.9s

  [1169/21087] intraday_10153.csv.gz  in=176,106,851 out=0 elapsed=35.9s

  [1170/21087] intraday_10154.csv.gz  in=176,202,640 out=0 elapsed=35.9s

  [1171/21087] intraday_10155.csv.gz  in=176,291,780 out=0 elapsed=35.9s

  [1172/21087] intraday_10156.csv.gz  in=176,368,566 out=0 elapsed=35.9s

  [1173/21087] intraday_1016.csv.gz  in=176,378,774 out=0 elapsed=35.9s

  [1174/21087] intraday_10157.csv.gz  in=176,486,272 out=0 elapsed=35.9s

  [1175/21087] intraday_10158.csv.gz  in=176,588,736 out=0 elapsed=36.0s

  [1176/21087] intraday_10159.csv.gz  in=176,668,116 out=0 elapsed=36.0s

  [1177/21087] intraday_10160.csv.gz  in=176,745,607 out=0 elapsed=36.0s

  [1178/21087] intraday_10161.csv.gz  in=176,836,371 out=0 elapsed=36.0s

  [1179/21087] intraday_10162.csv.gz  in=176,935,275 out=0 elapsed=36.0s

  [1180/21087] intraday_10163.csv.gz  in=177,018,870 out=0 elapsed=36.0s

  [1181/21087] intraday_10164.csv.gz  in=177,097,805 out=0 elapsed=36.1s

  [1182/21087] intraday_10165.csv.gz  in=177,173,337 out=0 elapsed=36.1s

  [1183/21087] intraday_10167.csv.gz  in=177,262,478 out=0 elapsed=36.1s

  [1184/21087] intraday_10166.csv.gz  in=177,360,707 out=0 elapsed=36.1s

  [1185/21087] intraday_10168.csv.gz  in=177,450,851 out=0 elapsed=36.1s

  [1186/21087] intraday_1017.csv.gz  in=177,465,071 out=0 elapsed=36.1s

  [1187/21087] intraday_10169.csv.gz  in=177,556,583 out=0 elapsed=36.2s

  [1188/21087] intraday_10170.csv.gz  in=177,640,495 out=0 elapsed=36.2s

  [1189/21087] intraday_10173.csv.gz  in=177,710,106 out=0 elapsed=36.2s

  [1190/21087] intraday_10172.csv.gz  in=177,796,337 out=0 elapsed=36.2s

  [1191/21087] intraday_10171.csv.gz  in=177,892,985 out=0 elapsed=36.2s

  [1192/21087] intraday_10174.csv.gz  in=177,987,050 out=0 elapsed=36.3s

  [1193/21087] intraday_10177.csv.gz  in=178,060,406 out=0 elapsed=36.3s

  [1194/21087] intraday_10176.csv.gz  in=178,158,363 out=0 elapsed=36.3s

  [1195/21087] intraday_10175.csv.gz  in=178,273,362 out=0 elapsed=36.3s

  [1196/21087] intraday_10178.csv.gz  in=178,347,875 out=0 elapsed=36.3s

  [1197/21087] intraday_1018.csv.gz  in=178,359,259 out=0 elapsed=36.3s

  [1198/21087] intraday_10179.csv.gz  in=178,443,812 out=0 elapsed=36.4s

  [1199/21087] intraday_10180.csv.gz  in=178,531,134 out=0 elapsed=36.4s

  [1200/21087] intraday_10181.csv.gz  in=178,609,433 out=0 elapsed=36.4s

  [1201/21087] intraday_10182.csv.gz  in=178,706,787 out=0 elapsed=36.4s

  [1202/21087] intraday_10183.csv.gz  in=178,782,131 out=0 elapsed=36.4s

  [1203/21087] intraday_10184.csv.gz  in=178,856,302 out=0 elapsed=36.4s

  [1204/21087] intraday_10185.csv.gz  in=178,941,200 out=0 elapsed=36.5s

  [1205/21087] intraday_10186.csv.gz  in=179,030,280 out=0 elapsed=36.5s

  [1206/21087] intraday_10187.csv.gz  in=179,118,921 out=0 elapsed=36.5s

  [1207/21087] intraday_1019.csv.gz  in=179,132,835 out=0 elapsed=36.5s

  [1208/21087] intraday_10188.csv.gz  in=179,215,109 out=0 elapsed=36.5s

  [1209/21087] intraday_10189.csv.gz  in=179,306,094 out=0 elapsed=36.5s

  [1210/21087] intraday_10191.csv.gz  in=179,379,070 out=0 elapsed=36.6s

  [1211/21087] intraday_10190.csv.gz  in=179,477,175 out=0 elapsed=36.6s

  [1212/21087] intraday_10192.csv.gz  in=179,558,761 out=0 elapsed=36.6s

  [1213/21087] intraday_10193.csv.gz  in=179,641,608 out=0 elapsed=36.6s

  [1214/21087] intraday_10194.csv.gz  in=179,714,178 out=0 elapsed=36.6s

  [1215/21087] intraday_10195.csv.gz  in=179,797,092 out=0 elapsed=36.6s

  [1216/21087] intraday_10196.csv.gz  in=179,873,334 out=0 elapsed=36.6s

  [1217/21087] intraday_10197.csv.gz  in=179,953,755 out=0 elapsed=36.6s

  [1218/21087] intraday_1020.csv.gz  in=179,967,131 out=0 elapsed=36.7s

  [1219/21087] intraday_10198.csv.gz  in=180,063,082 out=0 elapsed=36.7s

  [1220/21087] intraday_10199.csv.gz  in=180,141,936 out=0 elapsed=36.7s

  [1221/21087] intraday_10200.csv.gz  in=180,219,078 out=0 elapsed=36.7s

  [1222/21087] intraday_10201.csv.gz  in=180,320,540 out=0 elapsed=36.7s

  [1223/21087] intraday_10202.csv.gz  in=180,404,680 out=0 elapsed=36.7s

  [1224/21087] intraday_10203.csv.gz  in=180,483,278 out=0 elapsed=36.8s

  [1225/21087] intraday_10204.csv.gz  in=180,560,584 out=0 elapsed=36.8s

  [1226/21087] intraday_10205.csv.gz  in=180,648,610 out=0 elapsed=36.8s

  [1227/21087] intraday_10206.csv.gz  in=180,725,971 out=0 elapsed=36.8s

  [1228/21087] intraday_10207.csv.gz  in=180,799,011 out=0 elapsed=36.8s

  [1229/21087] intraday_1021.csv.gz  in=180,812,113 out=0 elapsed=36.8s

  [1230/21087] intraday_10208.csv.gz  in=180,899,720 out=0 elapsed=36.9s

  [1231/21087] intraday_10209.csv.gz  in=180,978,301 out=0 elapsed=36.9s

  [1232/21087] intraday_10210.csv.gz  in=181,052,594 out=0 elapsed=36.9s

  [1233/21087] intraday_10212.csv.gz  in=181,146,612 out=0 elapsed=36.9s

  [1234/21087] intraday_10211.csv.gz  in=181,261,979 out=0 elapsed=36.9s

  [1235/21087] intraday_10213.csv.gz  in=181,364,021 out=0 elapsed=36.9s

  [1236/21087] intraday_10214.csv.gz  in=181,443,640 out=0 elapsed=37.0s

  [1237/21087] intraday_10216.csv.gz  in=181,516,004 out=0 elapsed=37.0s

  [1238/21087] intraday_10215.csv.gz  in=181,611,320 out=0 elapsed=37.0s

  [1239/21087] intraday_10218.csv.gz  in=181,692,504 out=0 elapsed=37.0s

  [1240/21087] intraday_1022.csv.gz  in=181,703,234 out=0 elapsed=37.0s

  [1241/21087] intraday_10217.csv.gz  in=181,795,908 out=0 elapsed=37.0s

  [1242/21087] intraday_10219.csv.gz  in=181,886,623 out=0 elapsed=37.1s

  [1243/21087] intraday_10220.csv.gz  in=181,961,528 out=0 elapsed=37.1s

  [1244/21087] intraday_10222.csv.gz  in=182,044,920 out=0 elapsed=37.1s

  [1245/21087] intraday_10221.csv.gz  in=182,145,905 out=0 elapsed=37.1s

  [1246/21087] intraday_10223.csv.gz  in=182,240,480 out=0 elapsed=37.1s

  [1247/21087] intraday_10224.csv.gz  in=182,318,621 out=0 elapsed=37.1s

  [1248/21087] intraday_10225.csv.gz  in=182,398,973 out=0 elapsed=37.2s

  [1249/21087] intraday_10226.csv.gz  in=182,475,893 out=0 elapsed=37.2s

  [1250/21087] intraday_10227.csv.gz  in=182,538,188 out=0 elapsed=37.2s

  [1251/21087] intraday_1023.csv.gz  in=182,551,497 out=0 elapsed=37.2s

  [1252/21087] intraday_10228.csv.gz  in=182,626,752 out=0 elapsed=37.2s

  [1253/21087] intraday_10229.csv.gz  in=182,716,973 out=0 elapsed=37.2s

  [1254/21087] intraday_10230.csv.gz  in=182,830,052 out=0 elapsed=37.3s

  [1255/21087] intraday_10231.csv.gz  in=182,945,359 out=0 elapsed=37.3s

  [1256/21087] intraday_10232.csv.gz  in=183,036,725 out=0 elapsed=37.3s

  [1257/21087] intraday_10233.csv.gz  in=183,109,757 out=0 elapsed=37.3s

  [1258/21087] intraday_10235.csv.gz  in=183,198,212 out=0 elapsed=37.4s

  [1259/21087] intraday_10237.csv.gz  in=183,278,563 out=0 elapsed=37.4s

  [1260/21087] intraday_10234.csv.gz  in=183,376,816 out=0 elapsed=37.4s

  [1261/21087] intraday_10236.csv.gz  in=183,482,340 out=0 elapsed=37.4s

  [1262/21087] intraday_1024.csv.gz  in=183,494,276 out=0 elapsed=37.4s

  [1263/21087] intraday_10238.csv.gz  in=183,575,279 out=0 elapsed=37.4s

  [1264/21087] intraday_10239.csv.gz  in=183,675,534 out=0 elapsed=37.4s

  [1265/21087] intraday_10240.csv.gz  in=183,764,000 out=0 elapsed=37.4s

  [1266/21087] intraday_10241.csv.gz  in=183,855,290 out=0 elapsed=37.5s

  [1267/21087] intraday_10242.csv.gz  in=183,939,998 out=0 elapsed=37.5s

  [1268/21087] intraday_10243.csv.gz  in=184,027,574 out=0 elapsed=37.5s

  [1269/21087] intraday_10244.csv.gz  in=184,116,987 out=0 elapsed=37.5s

  [1270/21087] intraday_10245.csv.gz  in=184,207,182 out=0 elapsed=37.5s

  [1271/21087] intraday_10246.csv.gz  in=184,301,232 out=0 elapsed=37.6s

  [1272/21087] intraday_10247.csv.gz  in=184,375,035 out=0 elapsed=37.6s

  [1273/21087] intraday_10248.csv.gz  in=184,462,634 out=0 elapsed=37.6s

  [1274/21087] intraday_1025.csv.gz  in=184,497,338 out=0 elapsed=37.6s

  [1275/21087] intraday_10249.csv.gz  in=184,588,888 out=0 elapsed=37.6s

  [1276/21087] intraday_10250.csv.gz  in=184,684,658 out=0 elapsed=37.7s

  [1277/21087] intraday_10252.csv.gz  in=184,767,329 out=0 elapsed=37.7s

  [1278/21087] intraday_10251.csv.gz  in=184,853,516 out=0 elapsed=37.7s

  [1279/21087] intraday_10253.csv.gz  in=184,964,671 out=0 elapsed=37.7s

  [1280/21087] intraday_10254.csv.gz  in=185,043,773 out=0 elapsed=37.7s

  [1281/21087] intraday_10255.csv.gz  in=185,128,272 out=0 elapsed=37.7s

  [1282/21087] intraday_10256.csv.gz  in=185,224,692 out=0 elapsed=37.7s

  [1283/21087] intraday_10257.csv.gz  in=185,323,770 out=0 elapsed=37.8s

  [1284/21087] intraday_1026.csv.gz  in=185,335,351 out=0 elapsed=37.8s

  [1285/21087] intraday_10258.csv.gz  in=185,423,611 out=0 elapsed=37.8s

  [1286/21087] intraday_10259.csv.gz  in=185,518,466 out=0 elapsed=37.8s

  [1287/21087] intraday_10260.csv.gz  in=185,601,650 out=0 elapsed=37.8s

  [1288/21087] intraday_10261.csv.gz  in=185,686,507 out=0 elapsed=37.8s

  [1289/21087] intraday_10262.csv.gz  in=185,785,713 out=0 elapsed=37.9s

  [1290/21087] intraday_10263.csv.gz  in=185,902,292 out=0 elapsed=37.9s

  [1291/21087] intraday_10265.csv.gz  in=186,005,934 out=0 elapsed=37.9s

  [1292/21087] intraday_10264.csv.gz  in=186,141,184 out=0 elapsed=37.9s

  [1293/21087] intraday_10266.csv.gz  in=186,239,622 out=0 elapsed=37.9s

  [1294/21087] intraday_1027.csv.gz  in=186,251,957 out=0 elapsed=38.0s

  [1295/21087] intraday_10267.csv.gz  in=186,327,889 out=0 elapsed=38.0s

  [1296/21087] intraday_10268.csv.gz  in=186,419,031 out=0 elapsed=38.0s

  [1297/21087] intraday_10269.csv.gz  in=186,494,597 out=0 elapsed=38.0s

  [1298/21087] intraday_10271.csv.gz  in=186,567,903 out=0 elapsed=38.0s

  [1299/21087] intraday_10270.csv.gz  in=186,670,937 out=0 elapsed=38.0s

  [1300/21087] intraday_10272.csv.gz  in=186,765,380 out=0 elapsed=38.1s

  [1301/21087] intraday_10273.csv.gz  in=186,856,537 out=0 elapsed=38.1s

  [1302/21087] intraday_10274.csv.gz  in=186,968,075 out=0 elapsed=38.1s

  [1303/21087] intraday_10275.csv.gz  in=187,041,830 out=0 elapsed=38.1s

  [1304/21087] intraday_10277.csv.gz  in=187,119,775 out=0 elapsed=38.1s

  [1305/21087] intraday_10276.csv.gz  in=187,202,004 out=0 elapsed=38.1s

  [1306/21087] intraday_1028.csv.gz  in=187,213,776 out=0 elapsed=38.1s

  [1307/21087] intraday_10279.csv.gz  in=187,295,894 out=0 elapsed=38.2s

  [1308/21087] intraday_10278.csv.gz  in=187,386,833 out=0 elapsed=38.2s

  [1309/21087] intraday_10280.csv.gz  in=187,484,710 out=0 elapsed=38.2s

  [1310/21087] intraday_10281.csv.gz  in=187,595,459 out=0 elapsed=38.2s

  [1311/21087] intraday_10282.csv.gz  in=187,689,067 out=0 elapsed=38.2s

  [1312/21087] intraday_10283.csv.gz  in=187,797,424 out=0 elapsed=38.2s

  [1313/21087] intraday_10284.csv.gz  in=187,871,229 out=0 elapsed=38.3s

  [1314/21087] intraday_10285.csv.gz  in=187,959,414 out=0 elapsed=38.3s

  [1315/21087] intraday_10286.csv.gz  in=188,056,973 out=0 elapsed=38.3s

  [1316/21087] intraday_10287.csv.gz  in=188,133,461 out=0 elapsed=38.3s

  [1317/21087] intraday_1029.csv.gz  in=188,145,189 out=0 elapsed=38.3s

  [1318/21087] intraday_10288.csv.gz  in=188,260,016 out=0 elapsed=38.3s

  [1319/21087] intraday_10289.csv.gz  in=188,321,560 out=0 elapsed=38.3s

  [1320/21087] intraday_10292.csv.gz  in=188,335,624 out=0 elapsed=38.4s

  [1321/21087] intraday_10293.csv.gz  in=188,347,682 out=0 elapsed=38.4s

  [1322/21087] intraday_10290.csv.gz  in=188,427,852 out=0 elapsed=38.4s

  [1323/21087] intraday_10294.csv.gz  in=188,443,347 out=0 elapsed=38.4s

  [1324/21087] intraday_10295.csv.gz  in=188,453,262 out=0 elapsed=38.4s

  [1325/21087] intraday_10296.csv.gz  in=188,464,836 out=0 elapsed=38.4s

  [1326/21087] intraday_10291.csv.gz  in=188,533,188 out=0 elapsed=38.4s

  [1327/21087] intraday_10297.csv.gz  in=188,546,660 out=0 elapsed=38.4s

  [1328/21087] intraday_10298.csv.gz  in=188,559,588 out=0 elapsed=38.4s

  [1329/21087] intraday_10299.csv.gz  in=188,569,850 out=0 elapsed=38.4s

  [1330/21087] intraday_1030.csv.gz  in=188,581,890 out=0 elapsed=38.5s

  [1331/21087] intraday_10300.csv.gz  in=188,593,313 out=0 elapsed=38.5s

  [1332/21087] intraday_10301.csv.gz  in=188,606,985 out=0 elapsed=38.5s

  [1333/21087] intraday_10302.csv.gz  in=188,618,654 out=0 elapsed=38.5s

  [1334/21087] intraday_10303.csv.gz  in=188,629,492 out=0 elapsed=38.5s

  [1335/21087] intraday_10304.csv.gz  in=188,641,915 out=0 elapsed=38.5s

  [1336/21087] intraday_10305.csv.gz  in=188,655,133 out=0 elapsed=38.5s

  [1337/21087] intraday_10306.csv.gz  in=188,664,538 out=0 elapsed=38.5s

  [1338/21087] intraday_10307.csv.gz  in=188,675,244 out=0 elapsed=38.5s

  [1339/21087] intraday_10308.csv.gz  in=188,688,056 out=0 elapsed=38.5s

  [1340/21087] intraday_10309.csv.gz  in=188,701,110 out=0 elapsed=38.5s

  [1341/21087] intraday_1031.csv.gz  in=188,721,100 out=0 elapsed=38.5s

  [1342/21087] intraday_10310.csv.gz  in=188,732,815 out=0 elapsed=38.5s

  [1343/21087] intraday_10311.csv.gz  in=188,743,799 out=0 elapsed=38.5s

  [1344/21087] intraday_10312.csv.gz  in=188,754,760 out=0 elapsed=38.6s

  [1345/21087] intraday_10313.csv.gz  in=188,768,189 out=0 elapsed=38.6s

  [1346/21087] intraday_10314.csv.gz  in=188,780,661 out=0 elapsed=38.6s

  [1347/21087] intraday_10315.csv.gz  in=188,792,750 out=0 elapsed=38.6s

  [1348/21087] intraday_10316.csv.gz  in=188,804,444 out=0 elapsed=38.6s

  [1349/21087] intraday_10317.csv.gz  in=188,815,229 out=0 elapsed=38.6s

  [1350/21087] intraday_10319.csv.gz  in=188,826,594 out=0 elapsed=38.6s

  [1351/21087] intraday_10318.csv.gz  in=188,837,841 out=0 elapsed=38.6s

  [1352/21087] intraday_1032.csv.gz  in=188,847,949 out=0 elapsed=38.6s

  [1353/21087] intraday_10320.csv.gz  in=188,858,824 out=0 elapsed=38.6s

  [1354/21087] intraday_10321.csv.gz  in=188,871,230 out=0 elapsed=38.6s

  [1355/21087] intraday_10322.csv.gz  in=188,885,572 out=0 elapsed=38.6s

  [1356/21087] intraday_10324.csv.gz  in=188,895,125 out=0 elapsed=38.6s

  [1357/21087] intraday_10323.csv.gz  in=188,909,570 out=0 elapsed=38.6s

  [1358/21087] intraday_10325.csv.gz  in=188,919,534 out=0 elapsed=38.7s

  [1359/21087] intraday_10326.csv.gz  in=188,930,923 out=0 elapsed=38.7s

  [1360/21087] intraday_10328.csv.gz  in=188,941,971 out=0 elapsed=38.7s

  [1361/21087] intraday_10327.csv.gz  in=188,953,908 out=0 elapsed=38.7s

  [1362/21087] intraday_10329.csv.gz  in=188,965,141 out=0 elapsed=38.7s

  [1363/21087] intraday_1033.csv.gz  in=188,976,686 out=0 elapsed=38.7s

  [1364/21087] intraday_10330.csv.gz  in=188,987,032 out=0 elapsed=38.7s

  [1365/21087] intraday_10331.csv.gz  in=188,996,876 out=0 elapsed=38.7s

  [1366/21087] intraday_10332.csv.gz  in=189,007,668 out=0 elapsed=38.7s

  [1367/21087] intraday_10333.csv.gz  in=189,019,146 out=0 elapsed=38.7s

  [1368/21087] intraday_10334.csv.gz  in=189,032,417 out=0 elapsed=38.7s

  [1369/21087] intraday_10335.csv.gz  in=189,043,121 out=0 elapsed=38.7s

  [1370/21087] intraday_10336.csv.gz  in=189,056,271 out=0 elapsed=38.8s

  [1371/21087] intraday_10337.csv.gz  in=189,069,169 out=0 elapsed=38.8s

  [1372/21087] intraday_10338.csv.gz  in=189,079,317 out=0 elapsed=38.8s

  [1373/21087] intraday_10339.csv.gz  in=189,093,158 out=0 elapsed=38.8s

  [1374/21087] intraday_1034.csv.gz  in=189,104,555 out=0 elapsed=38.8s

  [1375/21087] intraday_10340.csv.gz  in=189,116,343 out=0 elapsed=38.8s

  [1376/21087] intraday_10341.csv.gz  in=189,126,157 out=0 elapsed=38.8s

  [1377/21087] intraday_10343.csv.gz  in=189,136,867 out=0 elapsed=38.8s

  [1378/21087] intraday_10342.csv.gz  in=189,148,045 out=0 elapsed=38.8s

  [1379/21087] intraday_10344.csv.gz  in=189,158,176 out=0 elapsed=38.8s

  [1380/21087] intraday_10345.csv.gz  in=189,170,240 out=0 elapsed=38.8s

  [1381/21087] intraday_10346.csv.gz  in=189,181,511 out=0 elapsed=38.9s

  [1382/21087] intraday_10347.csv.gz  in=189,192,631 out=0 elapsed=38.9s

  [1383/21087] intraday_10348.csv.gz  in=189,204,668 out=0 elapsed=38.9s

  [1384/21087] intraday_10349.csv.gz  in=189,215,483 out=0 elapsed=38.9s

  [1385/21087] intraday_1035.csv.gz  in=189,230,735 out=0 elapsed=38.9s

  [1386/21087] intraday_10350.csv.gz  in=189,242,040 out=0 elapsed=38.9s

  [1387/21087] intraday_10351.csv.gz  in=189,252,102 out=0 elapsed=38.9s

  [1388/21087] intraday_10353.csv.gz  in=189,262,051 out=0 elapsed=38.9s

  [1389/21087] intraday_10352.csv.gz  in=189,273,565 out=0 elapsed=38.9s

  [1390/21087] intraday_10354.csv.gz  in=189,285,616 out=0 elapsed=38.9s

  [1391/21087] intraday_10355.csv.gz  in=189,298,092 out=0 elapsed=38.9s

  [1392/21087] intraday_10356.csv.gz  in=189,308,623 out=0 elapsed=38.9s

  [1393/21087] intraday_10357.csv.gz  in=189,326,487 out=0 elapsed=39.0s

  [1394/21087] intraday_10358.csv.gz  in=189,340,638 out=0 elapsed=39.0s

  [1395/21087] intraday_10359.csv.gz  in=189,353,256 out=0 elapsed=39.0s

  [1396/21087] intraday_1036.csv.gz  in=189,377,458 out=0 elapsed=39.0s

  [1397/21087] intraday_10360.csv.gz  in=189,390,683 out=0 elapsed=39.0s

  [1398/21087] intraday_10362.csv.gz  in=189,402,548 out=0 elapsed=39.0s

  [1399/21087] intraday_10361.csv.gz  in=189,414,073 out=0 elapsed=39.0s

  [1400/21087] intraday_10363.csv.gz  in=189,423,970 out=0 elapsed=39.0s

  [1401/21087] intraday_10364.csv.gz  in=189,434,947 out=0 elapsed=39.0s

  [1402/21087] intraday_10365.csv.gz  in=189,446,829 out=0 elapsed=39.0s

  [1403/21087] intraday_10366.csv.gz  in=189,458,931 out=0 elapsed=39.0s

  [1404/21087] intraday_10367.csv.gz  in=189,471,095 out=0 elapsed=39.0s

  [1405/21087] intraday_10368.csv.gz  in=189,482,310 out=0 elapsed=39.0s

  [1406/21087] intraday_10369.csv.gz  in=189,492,194 out=0 elapsed=39.1s

  [1407/21087] intraday_1037.csv.gz  in=189,504,725 out=0 elapsed=39.1s

  [1408/21087] intraday_10370.csv.gz  in=189,516,956 out=0 elapsed=39.1s

  [1409/21087] intraday_10371.csv.gz  in=189,527,614 out=0 elapsed=39.1s

  [1410/21087] intraday_10372.csv.gz  in=189,538,902 out=0 elapsed=39.1s

  [1411/21087] intraday_10374.csv.gz  in=189,547,698 out=0 elapsed=39.1s

  [1412/21087] intraday_10373.csv.gz  in=189,558,451 out=0 elapsed=39.1s

  [1413/21087] intraday_10375.csv.gz  in=189,568,565 out=0 elapsed=39.1s

  [1414/21087] intraday_10376.csv.gz  in=189,580,448 out=0 elapsed=39.1s

  [1415/21087] intraday_10377.csv.gz  in=189,596,045 out=0 elapsed=39.1s

  [1416/21087] intraday_10378.csv.gz  in=189,609,647 out=0 elapsed=39.2s

  [1417/21087] intraday_10379.csv.gz  in=189,621,410 out=0 elapsed=39.2s

  [1418/21087] intraday_1038.csv.gz  in=189,633,115 out=0 elapsed=39.2s

  [1419/21087] intraday_10380.csv.gz  in=189,642,668 out=0 elapsed=39.2s

  [1420/21087] intraday_10381.csv.gz  in=189,656,437 out=0 elapsed=39.2s

  [1421/21087] intraday_10382.csv.gz  in=189,667,056 out=0 elapsed=39.2s

  [1422/21087] intraday_10383.csv.gz  in=189,680,840 out=0 elapsed=39.2s

  [1423/21087] intraday_10384.csv.gz  in=189,693,266 out=0 elapsed=39.2s

  [1424/21087] intraday_10385.csv.gz  in=189,704,206 out=0 elapsed=39.2s

  [1425/21087] intraday_10386.csv.gz  in=189,716,745 out=0 elapsed=39.2s

  [1426/21087] intraday_10387.csv.gz  in=189,729,601 out=0 elapsed=39.2s

  [1427/21087] intraday_10388.csv.gz  in=189,742,115 out=0 elapsed=39.2s

  [1428/21087] intraday_10389.csv.gz  in=189,753,990 out=0 elapsed=39.2s

  [1429/21087] intraday_1039.csv.gz  in=189,767,014 out=0 elapsed=39.3s

  [1430/21087] intraday_10390.csv.gz  in=189,779,387 out=0 elapsed=39.3s

  [1431/21087] intraday_10392.csv.gz  in=189,791,322 out=0 elapsed=39.3s

  [1432/21087] intraday_10391.csv.gz  in=189,802,400 out=0 elapsed=39.3s

  [1433/21087] intraday_10393.csv.gz  in=189,815,004 out=0 elapsed=39.3s

  [1434/21087] intraday_10394.csv.gz  in=189,825,216 out=0 elapsed=39.3s

  [1435/21087] intraday_10395.csv.gz  in=189,836,666 out=0 elapsed=39.3s

  [1436/21087] intraday_10396.csv.gz  in=189,849,361 out=0 elapsed=39.3s

  [1437/21087] intraday_10397.csv.gz  in=189,860,975 out=0 elapsed=39.3s

  [1438/21087] intraday_10398.csv.gz  in=189,872,737 out=0 elapsed=39.3s

  [1439/21087] intraday_10399.csv.gz  in=189,883,013 out=0 elapsed=39.3s

  [1440/21087] intraday_1040.csv.gz  in=189,895,412 out=0 elapsed=39.4s

  [1441/21087] intraday_10400.csv.gz  in=189,910,843 out=0 elapsed=39.4s

  [1442/21087] intraday_10401.csv.gz  in=189,920,129 out=0 elapsed=39.4s

  [1443/21087] intraday_10402.csv.gz  in=189,931,805 out=0 elapsed=39.4s

  [1444/21087] intraday_10403.csv.gz  in=189,952,125 out=0 elapsed=39.4s

  [1445/21087] intraday_10404.csv.gz  in=189,965,299 out=0 elapsed=39.4s

  [1446/21087] intraday_10405.csv.gz  in=189,975,359 out=0 elapsed=39.4s

  [1447/21087] intraday_10406.csv.gz  in=189,990,426 out=0 elapsed=39.4s

  [1448/21087] intraday_10407.csv.gz  in=190,003,378 out=0 elapsed=39.4s

  [1449/21087] intraday_10408.csv.gz  in=190,014,957 out=0 elapsed=39.4s

  [1450/21087] intraday_10409.csv.gz  in=190,030,073 out=0 elapsed=39.4s

  [1451/21087] intraday_1041.csv.gz  in=190,045,358 out=0 elapsed=39.4s

  [1452/21087] intraday_10410.csv.gz  in=190,060,426 out=0 elapsed=39.5s

  [1453/21087] intraday_10411.csv.gz  in=190,077,193 out=0 elapsed=39.5s

  [1454/21087] intraday_10412.csv.gz  in=190,091,577 out=0 elapsed=39.5s

  [1455/21087] intraday_10413.csv.gz  in=190,105,540 out=0 elapsed=39.5s

  [1456/21087] intraday_10414.csv.gz  in=190,115,831 out=0 elapsed=39.5s

  [1457/21087] intraday_10415.csv.gz  in=190,127,352 out=0 elapsed=39.5s

  [1458/21087] intraday_10416.csv.gz  in=190,138,032 out=0 elapsed=39.5s

  [1459/21087] intraday_10418.csv.gz  in=190,148,855 out=0 elapsed=39.5s

  [1460/21087] intraday_10417.csv.gz  in=190,161,069 out=0 elapsed=39.5s

  [1461/21087] intraday_10419.csv.gz  in=190,173,715 out=0 elapsed=39.5s

  [1462/21087] intraday_1042.csv.gz  in=190,185,728 out=0 elapsed=39.5s

  [1463/21087] intraday_10420.csv.gz  in=190,198,732 out=0 elapsed=39.5s

  [1464/21087] intraday_10421.csv.gz  in=190,212,555 out=0 elapsed=39.5s

  [1465/21087] intraday_10422.csv.gz  in=190,223,133 out=0 elapsed=39.6s

  [1466/21087] intraday_10423.csv.gz  in=190,234,082 out=0 elapsed=39.6s

  [1467/21087] intraday_10424.csv.gz  in=190,244,951 out=0 elapsed=39.6s

  [1468/21087] intraday_10425.csv.gz  in=190,256,265 out=0 elapsed=39.6s

  [1469/21087] intraday_10426.csv.gz  in=190,267,065 out=0 elapsed=39.6s

  [1470/21087] intraday_10427.csv.gz  in=190,281,516 out=0 elapsed=39.6s

  [1471/21087] intraday_10428.csv.gz  in=190,297,258 out=0 elapsed=39.6s

  [1472/21087] intraday_10429.csv.gz  in=190,309,957 out=0 elapsed=39.6s

  [1473/21087] intraday_1043.csv.gz  in=190,326,010 out=0 elapsed=39.6s

  [1474/21087] intraday_10430.csv.gz  in=190,341,261 out=0 elapsed=39.6s

  [1475/21087] intraday_10431.csv.gz  in=190,352,365 out=0 elapsed=39.6s

  [1476/21087] intraday_10432.csv.gz  in=190,363,283 out=0 elapsed=39.6s

  [1477/21087] intraday_10433.csv.gz  in=190,375,823 out=0 elapsed=39.6s

  [1478/21087] intraday_10434.csv.gz  in=190,385,834 out=0 elapsed=39.7s

  [1479/21087] intraday_10435.csv.gz  in=190,398,422 out=0 elapsed=39.7s

  [1480/21087] intraday_10436.csv.gz  in=190,407,256 out=0 elapsed=39.7s

  [1481/21087] intraday_10437.csv.gz  in=190,417,986 out=0 elapsed=39.7s

  [1482/21087] intraday_10438.csv.gz  in=190,426,352 out=0 elapsed=39.7s

  [1483/21087] intraday_10439.csv.gz  in=190,440,829 out=0 elapsed=39.7s

  [1484/21087] intraday_10441.csv.gz  in=190,453,922 out=0 elapsed=39.7s

  [1485/21087] intraday_10440.csv.gz  in=190,466,186 out=0 elapsed=39.7s

  [1486/21087] intraday_1044.csv.gz  in=190,480,356 out=0 elapsed=39.7s

  [1487/21087] intraday_10442.csv.gz  in=190,489,830 out=0 elapsed=39.7s

  [1488/21087] intraday_10443.csv.gz  in=190,501,251 out=0 elapsed=39.7s

  [1489/21087] intraday_10444.csv.gz  in=190,515,555 out=0 elapsed=39.8s

  [1490/21087] intraday_10445.csv.gz  in=190,528,567 out=0 elapsed=39.8s

  [1491/21087] intraday_10446.csv.gz  in=190,540,326 out=0 elapsed=39.8s

  [1492/21087] intraday_10447.csv.gz  in=190,551,500 out=0 elapsed=39.8s

  [1493/21087] intraday_10448.csv.gz  in=190,564,926 out=0 elapsed=39.8s

  [1494/21087] intraday_10449.csv.gz  in=190,579,035 out=0 elapsed=39.8s

  [1495/21087] intraday_1045.csv.gz  in=190,593,370 out=0 elapsed=39.8s

  [1496/21087] intraday_10450.csv.gz  in=190,605,078 out=0 elapsed=39.8s

  [1497/21087] intraday_10451.csv.gz  in=190,617,429 out=0 elapsed=39.8s

  [1498/21087] intraday_10453.csv.gz  in=190,627,400 out=0 elapsed=39.8s

  [1499/21087] intraday_10452.csv.gz  in=190,641,555 out=0 elapsed=39.8s

  [1500/21087] intraday_10454.csv.gz  in=190,651,958 out=0 elapsed=39.8s

  [1501/21087] intraday_10455.csv.gz  in=190,664,580 out=0 elapsed=39.8s

  [1502/21087] intraday_10456.csv.gz  in=190,678,423 out=0 elapsed=39.9s

  [1503/21087] intraday_10457.csv.gz  in=190,690,050 out=0 elapsed=39.9s

  [1504/21087] intraday_10458.csv.gz  in=190,700,110 out=0 elapsed=39.9s

  [1505/21087] intraday_10459.csv.gz  in=190,710,999 out=0 elapsed=39.9s

  [1506/21087] intraday_1046.csv.gz  in=190,723,721 out=0 elapsed=39.9s

  [1507/21087] intraday_10460.csv.gz  in=190,737,368 out=0 elapsed=39.9s

  [1508/21087] intraday_10461.csv.gz  in=190,749,492 out=0 elapsed=39.9s

  [1509/21087] intraday_10462.csv.gz  in=190,761,623 out=0 elapsed=39.9s

  [1510/21087] intraday_10463.csv.gz  in=190,773,305 out=0 elapsed=39.9s

  [1511/21087] intraday_10464.csv.gz  in=190,784,570 out=0 elapsed=39.9s

  [1512/21087] intraday_10465.csv.gz  in=190,795,768 out=0 elapsed=39.9s

  [1513/21087] intraday_10467.csv.gz  in=190,807,460 out=0 elapsed=39.9s

  [1514/21087] intraday_10466.csv.gz  in=190,819,138 out=0 elapsed=39.9s

  [1515/21087] intraday_10468.csv.gz  in=190,831,461 out=0 elapsed=40.0s

  [1516/21087] intraday_10469.csv.gz  in=190,846,577 out=0 elapsed=40.0s

  [1517/21087] intraday_1047.csv.gz  in=190,862,993 out=0 elapsed=40.0s

  [1518/21087] intraday_10470.csv.gz  in=190,875,034 out=0 elapsed=40.0s

  [1519/21087] intraday_10471.csv.gz  in=190,884,844 out=0 elapsed=40.0s

  [1520/21087] intraday_10472.csv.gz  in=190,895,719 out=0 elapsed=40.0s

  [1521/21087] intraday_10473.csv.gz  in=190,908,012 out=0 elapsed=40.0s

  [1522/21087] intraday_10474.csv.gz  in=190,921,235 out=0 elapsed=40.0s

  [1523/21087] intraday_10475.csv.gz  in=190,932,834 out=0 elapsed=40.0s

  [1524/21087] intraday_10476.csv.gz  in=190,945,837 out=0 elapsed=40.0s

  [1525/21087] intraday_10477.csv.gz  in=190,955,640 out=0 elapsed=40.0s

  [1526/21087] intraday_10478.csv.gz  in=190,964,740 out=0 elapsed=40.0s

  [1527/21087] intraday_10479.csv.gz  in=190,975,521 out=0 elapsed=40.1s

  [1528/21087] intraday_1048.csv.gz  in=190,987,267 out=0 elapsed=40.1s

  [1529/21087] intraday_10480.csv.gz  in=190,999,633 out=0 elapsed=40.1s

  [1530/21087] intraday_10481.csv.gz  in=191,013,916 out=0 elapsed=40.1s

  [1531/21087] intraday_10482.csv.gz  in=191,025,722 out=0 elapsed=40.1s

  [1532/21087] intraday_10483.csv.gz  in=191,038,087 out=0 elapsed=40.1s

  [1533/21087] intraday_10484.csv.gz  in=191,051,320 out=0 elapsed=40.1s

  [1534/21087] intraday_10485.csv.gz  in=191,063,187 out=0 elapsed=40.1s

  [1535/21087] intraday_10486.csv.gz  in=191,075,177 out=0 elapsed=40.1s

  [1536/21087] intraday_10487.csv.gz  in=191,086,201 out=0 elapsed=40.1s

  [1537/21087] intraday_10488.csv.gz  in=191,097,044 out=0 elapsed=40.1s

  [1538/21087] intraday_10489.csv.gz  in=191,111,790 out=0 elapsed=40.2s

  [1539/21087] intraday_1049.csv.gz  in=191,124,073 out=0 elapsed=40.2s

  [1540/21087] intraday_10490.csv.gz  in=191,135,386 out=0 elapsed=40.2s

  [1541/21087] intraday_10491.csv.gz  in=191,146,905 out=0 elapsed=40.2s

  [1542/21087] intraday_10492.csv.gz  in=191,158,166 out=0 elapsed=40.2s

  [1543/21087] intraday_10493.csv.gz  in=191,170,388 out=0 elapsed=40.2s

  [1544/21087] intraday_10494.csv.gz  in=191,184,131 out=0 elapsed=40.2s

  [1545/21087] intraday_10496.csv.gz  in=191,196,629 out=0 elapsed=40.2s

  [1546/21087] intraday_10495.csv.gz  in=191,207,953 out=0 elapsed=40.2s

  [1547/21087] intraday_10497.csv.gz  in=191,219,335 out=0 elapsed=40.2s

  [1548/21087] intraday_10499.csv.gz  in=191,231,641 out=0 elapsed=40.2s

  [1549/21087] intraday_10498.csv.gz  in=191,242,310 out=0 elapsed=40.2s

  [1550/21087] intraday_1050.csv.gz  in=191,254,843 out=0 elapsed=40.3s

  [1551/21087] intraday_10500.csv.gz  in=191,265,624 out=0 elapsed=40.3s

  [1552/21087] intraday_10501.csv.gz  in=191,279,621 out=0 elapsed=40.3s

  [1553/21087] intraday_10502.csv.gz  in=191,289,829 out=0 elapsed=40.3s

  [1554/21087] intraday_10503.csv.gz  in=191,300,921 out=0 elapsed=40.3s

  [1555/21087] intraday_10504.csv.gz  in=191,311,306 out=0 elapsed=40.3s

  [1556/21087] intraday_10505.csv.gz  in=191,326,633 out=0 elapsed=40.3s

  [1557/21087] intraday_10506.csv.gz  in=191,339,959 out=0 elapsed=40.3s

  [1558/21087] intraday_10507.csv.gz  in=191,353,372 out=0 elapsed=40.3s

  [1559/21087] intraday_10508.csv.gz  in=191,366,201 out=0 elapsed=40.3s

  [1560/21087] intraday_10509.csv.gz  in=191,378,469 out=0 elapsed=40.3s

  [1561/21087] intraday_10510.csv.gz  in=191,389,992 out=0 elapsed=40.4s

  [1562/21087] intraday_1051.csv.gz  in=191,402,922 out=0 elapsed=40.4s

  [1563/21087] intraday_10511.csv.gz  in=191,414,362 out=0 elapsed=40.4s

  [1564/21087] intraday_10512.csv.gz  in=191,427,095 out=0 elapsed=40.4s

  [1565/21087] intraday_10514.csv.gz  in=191,439,560 out=0 elapsed=40.4s

  [1566/21087] intraday_10513.csv.gz  in=191,453,662 out=0 elapsed=40.4s

  [1567/21087] intraday_10515.csv.gz  in=191,466,019 out=0 elapsed=40.4s

  [1568/21087] intraday_10516.csv.gz  in=191,476,461 out=0 elapsed=40.4s

  [1569/21087] intraday_10517.csv.gz  in=191,489,616 out=0 elapsed=40.4s

  [1570/21087] intraday_10518.csv.gz  in=191,500,361 out=0 elapsed=40.4s

  [1571/21087] intraday_1052.csv.gz  in=191,511,701 out=0 elapsed=40.4s

  [1572/21087] intraday_10519.csv.gz  in=191,528,476 out=0 elapsed=40.4s

  [1573/21087] intraday_10520.csv.gz  in=191,539,553 out=0 elapsed=40.5s

  [1574/21087] intraday_10521.csv.gz  in=191,548,793 out=0 elapsed=40.5s

  [1575/21087] intraday_10523.csv.gz  in=191,562,044 out=0 elapsed=40.5s

  [1576/21087] intraday_10522.csv.gz  in=191,571,999 out=0 elapsed=40.5s

  [1577/21087] intraday_10524.csv.gz  in=191,588,880 out=0 elapsed=40.5s

  [1578/21087] intraday_10525.csv.gz  in=191,602,431 out=0 elapsed=40.5s

  [1579/21087] intraday_10526.csv.gz  in=191,613,474 out=0 elapsed=40.5s

  [1580/21087] intraday_10527.csv.gz  in=191,625,063 out=0 elapsed=40.5s

  [1581/21087] intraday_10529.csv.gz  in=191,636,561 out=0 elapsed=40.5s

  [1582/21087] intraday_10528.csv.gz  in=191,648,915 out=0 elapsed=40.5s

  [1583/21087] intraday_10530.csv.gz  in=191,664,255 out=0 elapsed=40.5s

  [1584/21087] intraday_1053.csv.gz  in=191,689,716 out=0 elapsed=40.5s

  [1585/21087] intraday_10531.csv.gz  in=191,702,121 out=0 elapsed=40.5s

  [1586/21087] intraday_10532.csv.gz  in=191,712,691 out=0 elapsed=40.6s

  [1587/21087] intraday_10533.csv.gz  in=191,724,144 out=0 elapsed=40.6s

  [1588/21087] intraday_10534.csv.gz  in=191,738,420 out=0 elapsed=40.6s

  [1589/21087] intraday_10535.csv.gz  in=191,750,756 out=0 elapsed=40.6s

  [1590/21087] intraday_10536.csv.gz  in=191,762,218 out=0 elapsed=40.6s

  [1591/21087] intraday_10537.csv.gz  in=191,774,898 out=0 elapsed=40.6s

  [1592/21087] intraday_10539.csv.gz  in=191,787,021 out=0 elapsed=40.6s

  [1593/21087] intraday_10538.csv.gz  in=191,799,226 out=0 elapsed=40.6s

  [1594/21087] intraday_1054.csv.gz  in=191,811,004 out=0 elapsed=40.6s

  [1595/21087] intraday_10540.csv.gz  in=191,823,346 out=0 elapsed=40.6s

  [1596/21087] intraday_10541.csv.gz  in=191,833,411 out=0 elapsed=40.6s

  [1597/21087] intraday_10542.csv.gz  in=191,847,106 out=0 elapsed=40.6s

  [1598/21087] intraday_10543.csv.gz  in=191,860,497 out=0 elapsed=40.7s

  [1599/21087] intraday_10544.csv.gz  in=191,873,765 out=0 elapsed=40.7s

  [1600/21087] intraday_10545.csv.gz  in=191,885,759 out=0 elapsed=40.7s

  [1601/21087] intraday_10546.csv.gz  in=191,895,529 out=0 elapsed=40.7s

  [1602/21087] intraday_10547.csv.gz  in=191,911,207 out=0 elapsed=40.7s

  [1603/21087] intraday_10549.csv.gz  in=191,922,902 out=0 elapsed=40.7s

  [1604/21087] intraday_10548.csv.gz  in=191,934,020 out=0 elapsed=40.7s

  [1605/21087] intraday_1055.csv.gz  in=191,945,961 out=0 elapsed=40.7s

  [1606/21087] intraday_10550.csv.gz  in=191,959,255 out=0 elapsed=40.7s

  [1607/21087] intraday_10552.csv.gz  in=191,969,743 out=0 elapsed=40.7s

  [1608/21087] intraday_10553.csv.gz  in=191,983,789 out=0 elapsed=40.7s

  [1609/21087] intraday_10551.csv.gz  in=191,997,209 out=0 elapsed=40.7s

  [1610/21087] intraday_10554.csv.gz  in=192,014,320 out=0 elapsed=40.8s

  [1611/21087] intraday_10555.csv.gz  in=192,026,119 out=0 elapsed=40.8s

  [1612/21087] intraday_10556.csv.gz  in=192,041,326 out=0 elapsed=40.8s

  [1613/21087] intraday_10557.csv.gz  in=192,055,721 out=0 elapsed=40.8s

  [1614/21087] intraday_10558.csv.gz  in=192,073,305 out=0 elapsed=40.8s

  [1615/21087] intraday_10559.csv.gz  in=192,087,964 out=0 elapsed=40.8s

  [1616/21087] intraday_1056.csv.gz  in=192,104,345 out=0 elapsed=40.8s

  [1617/21087] intraday_10560.csv.gz  in=192,121,551 out=0 elapsed=40.8s

  [1618/21087] intraday_10561.csv.gz  in=192,133,103 out=0 elapsed=40.8s

  [1619/21087] intraday_10562.csv.gz  in=192,144,919 out=0 elapsed=40.8s

  [1620/21087] intraday_10563.csv.gz  in=192,163,727 out=0 elapsed=40.8s

  [1621/21087] intraday_10565.csv.gz  in=192,174,798 out=0 elapsed=40.8s

  [1622/21087] intraday_10564.csv.gz  in=192,188,190 out=0 elapsed=40.8s

  [1623/21087] intraday_10566.csv.gz  in=192,200,124 out=0 elapsed=40.8s

  [1624/21087] intraday_10567.csv.gz  in=192,212,373 out=0 elapsed=40.9s

  [1625/21087] intraday_10569.csv.gz  in=192,222,452 out=0 elapsed=40.9s

  [1626/21087] intraday_10568.csv.gz  in=192,237,880 out=0 elapsed=40.9s

  [1627/21087] intraday_1057.csv.gz  in=192,247,988 out=0 elapsed=40.9s

  [1628/21087] intraday_10570.csv.gz  in=192,259,039 out=0 elapsed=40.9s

  [1629/21087] intraday_10571.csv.gz  in=192,271,326 out=0 elapsed=40.9s

  [1630/21087] intraday_10573.csv.gz  in=192,282,303 out=0 elapsed=40.9s

  [1631/21087] intraday_10572.csv.gz  in=192,294,038 out=0 elapsed=40.9s

  [1632/21087] intraday_10574.csv.gz  in=192,309,581 out=0 elapsed=40.9s

  [1633/21087] intraday_10575.csv.gz  in=192,325,550 out=0 elapsed=40.9s

  [1634/21087] intraday_10576.csv.gz  in=192,339,120 out=0 elapsed=40.9s

  [1635/21087] intraday_10577.csv.gz  in=192,355,082 out=0 elapsed=40.9s

  [1636/21087] intraday_10578.csv.gz  in=192,366,390 out=0 elapsed=40.9s

  [1637/21087] intraday_10579.csv.gz  in=192,377,295 out=0 elapsed=40.9s

  [1638/21087] intraday_1058.csv.gz  in=192,390,464 out=0 elapsed=41.0s

  [1639/21087] intraday_10580.csv.gz  in=192,403,154 out=0 elapsed=41.0s

  [1640/21087] intraday_10582.csv.gz  in=192,412,918 out=0 elapsed=41.0s

  [1641/21087] intraday_10581.csv.gz  in=192,424,495 out=0 elapsed=41.0s

  [1642/21087] intraday_10583.csv.gz  in=192,432,324 out=0 elapsed=41.0s

  [1643/21087] intraday_10584.csv.gz  in=192,442,942 out=0 elapsed=41.0s

  [1644/21087] intraday_10585.csv.gz  in=192,449,461 out=0 elapsed=41.0s

  [1645/21087] intraday_10586.csv.gz  in=192,464,150 out=0 elapsed=41.0s

  [1646/21087] intraday_10587.csv.gz  in=192,476,756 out=0 elapsed=41.0s

  [1647/21087] intraday_10589.csv.gz  in=192,486,243 out=0 elapsed=41.0s

  [1648/21087] intraday_10588.csv.gz  in=192,497,724 out=0 elapsed=41.0s

  [1649/21087] intraday_1059.csv.gz  in=192,520,541 out=0 elapsed=41.1s

  [1650/21087] intraday_10590.csv.gz  in=192,532,160 out=0 elapsed=41.1s

  [1651/21087] intraday_10591.csv.gz  in=192,546,024 out=0 elapsed=41.1s

  [1652/21087] intraday_10592.csv.gz  in=192,560,255 out=0 elapsed=41.1s

  [1653/21087] intraday_10593.csv.gz  in=192,571,033 out=0 elapsed=41.1s

  [1654/21087] intraday_10594.csv.gz  in=192,582,280 out=0 elapsed=41.1s

  [1655/21087] intraday_10595.csv.gz  in=192,595,813 out=0 elapsed=41.1s

  [1656/21087] intraday_10596.csv.gz  in=192,609,901 out=0 elapsed=41.1s

  [1657/21087] intraday_10597.csv.gz  in=192,621,978 out=0 elapsed=41.1s

  [1658/21087] intraday_10598.csv.gz  in=192,636,878 out=0 elapsed=41.1s

  [1659/21087] intraday_10599.csv.gz  in=192,649,921 out=0 elapsed=41.1s

  [1660/21087] intraday_1060.csv.gz  in=192,664,818 out=0 elapsed=41.1s

  [1661/21087] intraday_10600.csv.gz  in=192,674,486 out=0 elapsed=41.2s

  [1662/21087] intraday_10601.csv.gz  in=192,684,453 out=0 elapsed=41.2s

  [1663/21087] intraday_10602.csv.gz  in=192,696,400 out=0 elapsed=41.2s

  [1664/21087] intraday_10603.csv.gz  in=192,708,930 out=0 elapsed=41.2s

  [1665/21087] intraday_10604.csv.gz  in=192,720,002 out=0 elapsed=41.2s

  [1666/21087] intraday_10606.csv.gz  in=192,730,625 out=0 elapsed=41.2s

  [1667/21087] intraday_10605.csv.gz  in=192,741,091 out=0 elapsed=41.2s

  [1668/21087] intraday_10607.csv.gz  in=192,755,504 out=0 elapsed=41.2s

  [1669/21087] intraday_10608.csv.gz  in=192,768,018 out=0 elapsed=41.2s

  [1670/21087] intraday_10609.csv.gz  in=192,779,613 out=0 elapsed=41.2s

  [1671/21087] intraday_1061.csv.gz  in=192,791,539 out=0 elapsed=41.2s

  [1672/21087] intraday_10610.csv.gz  in=192,804,805 out=0 elapsed=41.2s

  [1673/21087] intraday_10611.csv.gz  in=192,815,899 out=0 elapsed=41.2s

  [1674/21087] intraday_10612.csv.gz  in=192,828,066 out=0 elapsed=41.2s

  [1675/21087] intraday_10613.csv.gz  in=192,839,907 out=0 elapsed=41.3s

  [1676/21087] intraday_10614.csv.gz  in=192,851,671 out=0 elapsed=41.3s

  [1677/21087] intraday_10615.csv.gz  in=192,863,475 out=0 elapsed=41.3s

  [1678/21087] intraday_10618.csv.gz  in=192,873,116 out=0 elapsed=41.3s

  [1679/21087] intraday_10616.csv.gz  in=192,888,392 out=0 elapsed=41.3s

  [1680/21087] intraday_10617.csv.gz  in=192,900,289 out=0 elapsed=41.3s

  [1681/21087] intraday_10619.csv.gz  in=192,911,489 out=0 elapsed=41.3s

  [1682/21087] intraday_1062.csv.gz  in=192,924,982 out=0 elapsed=41.3s

  [1683/21087] intraday_10620.csv.gz  in=192,936,672 out=0 elapsed=41.3s

  [1684/21087] intraday_10622.csv.gz  in=192,948,523 out=0 elapsed=41.3s

  [1685/21087] intraday_10621.csv.gz  in=192,960,101 out=0 elapsed=41.3s

  [1686/21087] intraday_10625.csv.gz  in=192,970,098 out=0 elapsed=41.4s

  [1687/21087] intraday_10624.csv.gz  in=192,981,154 out=0 elapsed=41.4s

  [1688/21087] intraday_10623.csv.gz  in=192,992,755 out=0 elapsed=41.4s

  [1689/21087] intraday_10626.csv.gz  in=193,003,744 out=0 elapsed=41.4s

  [1690/21087] intraday_10627.csv.gz  in=193,015,917 out=0 elapsed=41.4s

  [1691/21087] intraday_1063.csv.gz  in=193,028,163 out=0 elapsed=41.4s

  [1692/21087] intraday_10629.csv.gz  in=193,039,597 out=0 elapsed=41.4s

  [1693/21087] intraday_10628.csv.gz  in=193,053,148 out=0 elapsed=41.4s

  [1694/21087] intraday_10631.csv.gz  in=193,065,314 out=0 elapsed=41.4s

  [1695/21087] intraday_10630.csv.gz  in=193,078,923 out=0 elapsed=41.4s

  [1696/21087] intraday_10632.csv.gz  in=193,089,114 out=0 elapsed=41.4s

  [1697/21087] intraday_10633.csv.gz  in=193,100,961 out=0 elapsed=41.5s

  [1698/21087] intraday_10634.csv.gz  in=193,112,303 out=0 elapsed=41.5s

  [1699/21087] intraday_10636.csv.gz  in=193,123,331 out=0 elapsed=41.5s

  [1700/21087] intraday_10637.csv.gz  in=193,134,469 out=0 elapsed=41.5s

  [1701/21087] intraday_10635.csv.gz  in=193,144,518 out=0 elapsed=41.5s

  [1702/21087] intraday_10638.csv.gz  in=193,156,016 out=0 elapsed=41.5s

  [1703/21087] intraday_10639.csv.gz  in=193,168,091 out=0 elapsed=41.5s

  [1704/21087] intraday_10640.csv.gz  in=193,184,351 out=0 elapsed=41.5s

  [1705/21087] intraday_1064.csv.gz  in=193,197,008 out=0 elapsed=41.5s

  [1706/21087] intraday_10641.csv.gz  in=193,207,136 out=0 elapsed=41.5s

  [1707/21087] intraday_10642.csv.gz  in=193,220,454 out=0 elapsed=41.5s

  [1708/21087] intraday_10643.csv.gz  in=193,232,262 out=0 elapsed=41.6s

  [1709/21087] intraday_10644.csv.gz  in=193,242,564 out=0 elapsed=41.6s

  [1710/21087] intraday_10645.csv.gz  in=193,254,212 out=0 elapsed=41.6s

  [1711/21087] intraday_10646.csv.gz  in=193,266,745 out=0 elapsed=41.6s

  [1712/21087] intraday_10647.csv.gz  in=193,276,590 out=0 elapsed=41.6s

  [1713/21087] intraday_10648.csv.gz  in=193,290,555 out=0 elapsed=41.6s

  [1714/21087] intraday_10649.csv.gz  in=193,301,021 out=0 elapsed=41.6s

  [1715/21087] intraday_1065.csv.gz  in=193,312,841 out=0 elapsed=41.6s

  [1716/21087] intraday_10650.csv.gz  in=193,324,118 out=0 elapsed=41.6s

  [1717/21087] intraday_10651.csv.gz  in=193,334,023 out=0 elapsed=41.6s

  [1718/21087] intraday_10652.csv.gz  in=193,347,785 out=0 elapsed=41.6s

  [1719/21087] intraday_10653.csv.gz  in=193,362,194 out=0 elapsed=41.6s

  [1720/21087] intraday_10654.csv.gz  in=193,376,250 out=0 elapsed=41.7s

  [1721/21087] intraday_10655.csv.gz  in=193,387,402 out=0 elapsed=41.7s

  [1722/21087] intraday_10656.csv.gz  in=193,400,851 out=0 elapsed=41.7s

  [1723/21087] intraday_10657.csv.gz  in=193,413,663 out=0 elapsed=41.7s

  [1724/21087] intraday_10658.csv.gz  in=193,425,700 out=0 elapsed=41.7s

  [1725/21087] intraday_10659.csv.gz  in=193,438,500 out=0 elapsed=41.7s

  [1726/21087] intraday_1066.csv.gz  in=193,453,179 out=0 elapsed=41.7s

  [1727/21087] intraday_10660.csv.gz  in=193,465,948 out=0 elapsed=41.7s

  [1728/21087] intraday_10661.csv.gz  in=193,477,250 out=0 elapsed=41.7s

  [1729/21087] intraday_10662.csv.gz  in=193,488,414 out=0 elapsed=41.7s

  [1730/21087] intraday_10663.csv.gz  in=193,498,772 out=0 elapsed=41.7s

  [1731/21087] intraday_10664.csv.gz  in=193,512,112 out=0 elapsed=41.7s

  [1732/21087] intraday_10666.csv.gz  in=193,523,090 out=0 elapsed=41.8s

  [1733/21087] intraday_10665.csv.gz  in=193,534,241 out=0 elapsed=41.8s

  [1734/21087] intraday_10667.csv.gz  in=193,544,128 out=0 elapsed=41.8s

  [1735/21087] intraday_10668.csv.gz  in=193,552,954 out=0 elapsed=41.8s

  [1736/21087] intraday_10669.csv.gz  in=193,563,317 out=0 elapsed=41.8s

  [1737/21087] intraday_1067.csv.gz  in=193,575,117 out=0 elapsed=41.8s

  [1738/21087] intraday_10670.csv.gz  in=193,587,964 out=0 elapsed=41.8s

  [1739/21087] intraday_10671.csv.gz  in=193,605,199 out=0 elapsed=41.8s

  [1740/21087] intraday_10672.csv.gz  in=193,618,290 out=0 elapsed=41.8s

  [1741/21087] intraday_10673.csv.gz  in=193,629,579 out=0 elapsed=41.8s

  [1742/21087] intraday_10674.csv.gz  in=193,640,769 out=0 elapsed=41.8s

  [1743/21087] intraday_10676.csv.gz  in=193,652,167 out=0 elapsed=41.8s

  [1744/21087] intraday_10675.csv.gz  in=193,665,237 out=0 elapsed=41.9s

  [1745/21087] intraday_10677.csv.gz  in=193,679,459 out=0 elapsed=41.9s

  [1746/21087] intraday_10678.csv.gz  in=193,690,330 out=0 elapsed=41.9s

  [1747/21087] intraday_10679.csv.gz  in=193,702,271 out=0 elapsed=41.9s

  [1748/21087] intraday_1068.csv.gz  in=193,719,334 out=0 elapsed=41.9s

  [1749/21087] intraday_10680.csv.gz  in=193,730,541 out=0 elapsed=41.9s

  [1750/21087] intraday_10681.csv.gz  in=193,743,677 out=0 elapsed=41.9s

  [1751/21087] intraday_10682.csv.gz  in=193,756,656 out=0 elapsed=41.9s

  [1752/21087] intraday_10683.csv.gz  in=193,768,917 out=0 elapsed=41.9s

  [1753/21087] intraday_10684.csv.gz  in=193,781,291 out=0 elapsed=41.9s

  [1754/21087] intraday_10685.csv.gz  in=193,792,695 out=0 elapsed=41.9s

  [1755/21087] intraday_10686.csv.gz  in=193,804,194 out=0 elapsed=41.9s

  [1756/21087] intraday_10687.csv.gz  in=193,816,699 out=0 elapsed=42.0s

  [1757/21087] intraday_10688.csv.gz  in=193,827,508 out=0 elapsed=42.0s

  [1758/21087] intraday_10689.csv.gz  in=193,838,867 out=0 elapsed=42.0s

  [1759/21087] intraday_1069.csv.gz  in=193,851,802 out=0 elapsed=42.0s

  [1760/21087] intraday_10691.csv.gz  in=193,864,843 out=0 elapsed=42.0s

  [1761/21087] intraday_10693.csv.gz  in=193,875,941 out=0 elapsed=42.0s

  [1762/21087] intraday_10692.csv.gz  in=193,886,848 out=0 elapsed=42.0s

  [1763/21087] intraday_10690.csv.gz  in=193,905,003 out=0 elapsed=42.0s

  [1764/21087] intraday_10694.csv.gz  in=193,919,681 out=0 elapsed=42.0s

  [1765/21087] intraday_10695.csv.gz  in=193,930,799 out=0 elapsed=42.0s

  [1766/21087] intraday_10697.csv.gz  in=193,942,915 out=0 elapsed=42.0s

  [1767/21087] intraday_10696.csv.gz  in=193,955,324 out=0 elapsed=42.0s

  [1768/21087] intraday_10698.csv.gz  in=193,968,370 out=0 elapsed=42.0s

  [1769/21087] intraday_10699.csv.gz  in=193,978,838 out=0 elapsed=42.1s

  [1770/21087] intraday_10700.csv.gz  in=193,994,145 out=0 elapsed=42.1s

  [1771/21087] intraday_1070.csv.gz  in=194,009,802 out=0 elapsed=42.1s

  [1772/21087] intraday_10701.csv.gz  in=194,024,968 out=0 elapsed=42.1s

  [1773/21087] intraday_10702.csv.gz  in=194,037,499 out=0 elapsed=42.1s

  [1774/21087] intraday_10703.csv.gz  in=194,050,795 out=0 elapsed=42.1s

  [1775/21087] intraday_10704.csv.gz  in=194,066,351 out=0 elapsed=42.1s

  [1776/21087] intraday_10705.csv.gz  in=194,083,548 out=0 elapsed=42.1s

  [1777/21087] intraday_10706.csv.gz  in=194,097,466 out=0 elapsed=42.1s

  [1778/21087] intraday_10707.csv.gz  in=194,111,230 out=0 elapsed=42.1s

  [1779/21087] intraday_10708.csv.gz  in=194,123,170 out=0 elapsed=42.1s

  [1780/21087] intraday_1071.csv.gz  in=194,133,092 out=0 elapsed=42.1s

  [1781/21087] intraday_10709.csv.gz  in=194,144,395 out=0 elapsed=42.1s

  [1782/21087] intraday_10710.csv.gz  in=194,154,172 out=0 elapsed=42.2s

  [1783/21087] intraday_10712.csv.gz  in=194,165,523 out=0 elapsed=42.2s

  [1784/21087] intraday_10711.csv.gz  in=194,178,008 out=0 elapsed=42.2s

  [1785/21087] intraday_10713.csv.gz  in=194,190,629 out=0 elapsed=42.2s

  [1786/21087] intraday_10714.csv.gz  in=194,202,790 out=0 elapsed=42.2s

  [1787/21087] intraday_10716.csv.gz  in=194,213,367 out=0 elapsed=42.2s

  [1788/21087] intraday_10715.csv.gz  in=194,228,215 out=0 elapsed=42.2s

  [1789/21087] intraday_10717.csv.gz  in=194,239,198 out=0 elapsed=42.2s

  [1790/21087] intraday_10718.csv.gz  in=194,251,767 out=0 elapsed=42.2s

  [1791/21087] intraday_10719.csv.gz  in=194,263,025 out=0 elapsed=42.2s

  [1792/21087] intraday_10721.csv.gz  in=194,277,907 out=0 elapsed=42.3s

  [1793/21087] intraday_10720.csv.gz  in=194,289,543 out=0 elapsed=42.3s

  [1794/21087] intraday_1072.csv.gz  in=194,316,292 out=0 elapsed=42.3s

  [1795/21087] intraday_10723.csv.gz  in=194,330,594 out=0 elapsed=42.3s

  [1796/21087] intraday_10725.csv.gz  in=194,341,920 out=0 elapsed=42.3s

  [1797/21087] intraday_10722.csv.gz  in=194,356,871 out=0 elapsed=42.3s

  [1798/21087] intraday_10724.csv.gz  in=194,372,599 out=0 elapsed=42.3s

  [1799/21087] intraday_10726.csv.gz  in=194,383,023 out=0 elapsed=42.3s

  [1800/21087] intraday_10729.csv.gz  in=194,393,072 out=0 elapsed=42.3s

  [1801/21087] intraday_10728.csv.gz  in=194,403,789 out=0 elapsed=42.3s

  [1802/21087] intraday_10727.csv.gz  in=194,417,115 out=0 elapsed=42.3s

  [1803/21087] intraday_1073.csv.gz  in=194,428,206 out=0 elapsed=42.3s

  [1804/21087] intraday_10730.csv.gz  in=194,434,425 out=0 elapsed=42.3s

  [1805/21087] intraday_10733.csv.gz  in=194,434,431 out=0 elapsed=42.5s

  [1806/21087] intraday_10732.csv.gz  in=194,442,654 out=0 elapsed=42.5s

  [1807/21087] intraday_10731.csv.gz  in=194,452,237 out=0 elapsed=42.5s

  [1808/21087] intraday_10734.csv.gz  in=194,452,238 out=0 elapsed=42.5s

  [1809/21087] intraday_10735.csv.gz  in=194,452,241 out=0 elapsed=42.5s

  [1810/21087] intraday_10736.csv.gz  in=194,452,245 out=0 elapsed=42.6s

  [1811/21087] intraday_10738.csv.gz  in=194,452,247 out=0 elapsed=42.6s

  [1812/21087] intraday_10737.csv.gz  in=194,452,254 out=0 elapsed=42.6s

  [1813/21087] intraday_10739.csv.gz  in=194,452,255 out=0 elapsed=42.6s

  [1814/21087] intraday_10742.csv.gz  in=194,452,258 out=0 elapsed=42.6s

  [1815/21087] intraday_10741.csv.gz  in=194,452,261 out=0 elapsed=42.6s

  [1816/21087] intraday_10740.csv.gz  in=194,452,266 out=0 elapsed=42.6s

  [1817/21087] intraday_10743.csv.gz  in=194,452,269 out=0 elapsed=42.6s

  [1818/21087] intraday_10744.csv.gz  in=194,452,271 out=0 elapsed=42.6s

  [1819/21087] intraday_10746.csv.gz  in=194,452,276 out=0 elapsed=42.6s

  [1820/21087] intraday_1074.csv.gz  in=194,468,717 out=0 elapsed=42.6s

  [1821/21087] intraday_10747.csv.gz  in=194,468,719 out=0 elapsed=42.6s

  [1822/21087] intraday_10745.csv.gz  in=194,470,975 out=0 elapsed=42.6s

  [1823/21087] intraday_10749.csv.gz  in=194,470,977 out=0 elapsed=42.6s

  [1824/21087] intraday_10748.csv.gz  in=194,470,978 out=0 elapsed=42.6s

  [1825/21087] intraday_10750.csv.gz  in=194,470,980 out=0 elapsed=42.6s

  [1826/21087] intraday_10751.csv.gz  in=194,470,983 out=0 elapsed=42.6s

  [1827/21087] intraday_10752.csv.gz  in=194,470,984 out=0 elapsed=42.6s

  [1828/21087] intraday_10755.csv.gz  in=194,470,985 out=0 elapsed=42.6s

  [1829/21087] intraday_10754.csv.gz  in=194,470,986 out=0 elapsed=42.6s

  [1830/21087] intraday_1075.csv.gz  in=194,484,234 out=0 elapsed=42.7s

  [1831/21087] intraday_10753.csv.gz  in=194,484,402 out=0 elapsed=42.7s

  [1832/21087] intraday_10756.csv.gz  in=194,484,404 out=0 elapsed=42.7s

  [1833/21087] intraday_10757.csv.gz  in=194,484,407 out=0 elapsed=42.7s

  [1834/21087] intraday_10759.csv.gz  in=194,484,408 out=0 elapsed=42.7s

  [1835/21087] intraday_10758.csv.gz  in=194,484,659 out=0 elapsed=42.7s

  [1836/21087] intraday_10760.csv.gz  in=194,484,660 out=0 elapsed=42.7s

  [1837/21087] intraday_10761.csv.gz  in=194,484,663 out=0 elapsed=42.7s

  [1838/21087] intraday_10762.csv.gz  in=194,484,665 out=0 elapsed=42.7s

  [1839/21087] intraday_1076.csv.gz  in=194,499,959 out=0 elapsed=42.7s

  [1840/21087] intraday_10763.csv.gz  in=194,499,960 out=0 elapsed=42.7s

  [1841/21087] intraday_10764.csv.gz  in=194,499,961 out=0 elapsed=42.7s

  [1842/21087] intraday_10766.csv.gz  in=194,499,962 out=0 elapsed=42.7s

  [1843/21087] intraday_10765.csv.gz  in=194,499,963 out=0 elapsed=42.7s

  [1844/21087] intraday_10767.csv.gz  in=194,499,965 out=0 elapsed=42.7s

  [1845/21087] intraday_10768.csv.gz  in=194,499,985 out=0 elapsed=42.7s

  [1846/21087] intraday_10769.csv.gz  in=194,503,038 out=0 elapsed=42.7s

  [1847/21087] intraday_10770.csv.gz  in=194,503,042 out=0 elapsed=42.7s

  [1848/21087] intraday_10771.csv.gz  in=194,503,043 out=0 elapsed=42.7s

  [1849/21087] intraday_10772.csv.gz  in=194,503,044 out=0 elapsed=42.7s

  [1850/21087] intraday_1077.csv.gz  in=194,516,088 out=0 elapsed=42.7s

  [1851/21087] intraday_10773.csv.gz  in=194,516,089 out=0 elapsed=42.8s

  [1852/21087] intraday_10774.csv.gz  in=194,516,090 out=0 elapsed=42.8s

  [1853/21087] intraday_10775.csv.gz  in=194,516,096 out=0 elapsed=42.8s

  [1854/21087] intraday_10776.csv.gz  in=194,516,100 out=0 elapsed=42.8s

  [1855/21087] intraday_10777.csv.gz  in=194,516,101 out=0 elapsed=42.8s

  [1856/21087] intraday_10778.csv.gz  in=194,516,105 out=0 elapsed=42.8s

  [1857/21087] intraday_10780.csv.gz  in=194,516,107 out=0 elapsed=42.8s

  [1858/21087] intraday_10779.csv.gz  in=194,516,109 out=0 elapsed=42.8s

  [1859/21087] intraday_10781.csv.gz  in=194,516,110 out=0 elapsed=42.8s

  [1860/21087] intraday_10782.csv.gz  in=194,516,114 out=0 elapsed=42.8s

  [1861/21087] intraday_10783.csv.gz  in=194,516,115 out=0 elapsed=42.8s

  [1862/21087] intraday_10784.csv.gz  in=194,516,119 out=0 elapsed=42.8s

  [1863/21087] intraday_1078.csv.gz  in=194,528,841 out=0 elapsed=42.8s

  [1864/21087] intraday_10785.csv.gz  in=194,528,842 out=0 elapsed=42.8s

  [1865/21087] intraday_10786.csv.gz  in=194,528,843 out=0 elapsed=42.8s

  [1866/21087] intraday_10787.csv.gz  in=194,528,885 out=0 elapsed=42.8s

  [1867/21087] intraday_10788.csv.gz  in=194,528,892 out=0 elapsed=42.8s

  [1868/21087] intraday_10789.csv.gz  in=194,528,896 out=0 elapsed=42.8s

  [1869/21087] intraday_10790.csv.gz  in=194,528,898 out=0 elapsed=42.8s

  [1870/21087] intraday_10791.csv.gz  in=194,528,903 out=0 elapsed=42.8s

  [1871/21087] intraday_10792.csv.gz  in=194,531,103 out=0 elapsed=42.8s

  [1872/21087] intraday_10794.csv.gz  in=194,531,106 out=0 elapsed=42.8s

  [1873/21087] intraday_10793.csv.gz  in=194,531,107 out=0 elapsed=42.8s

  [1874/21087] intraday_10795.csv.gz  in=194,531,111 out=0 elapsed=42.8s

  [1875/21087] intraday_1079.csv.gz  in=194,546,727 out=0 elapsed=42.8s

  [1876/21087] intraday_10796.csv.gz  in=194,546,728 out=0 elapsed=42.8s

  [1877/21087] intraday_10797.csv.gz  in=194,546,729 out=0 elapsed=42.8s

  [1878/21087] intraday_10798.csv.gz  in=194,546,731 out=0 elapsed=42.8s

  [1879/21087] intraday_10799.csv.gz  in=194,546,733 out=0 elapsed=42.8s

  [1880/21087] intraday_10800.csv.gz  in=194,546,735 out=0 elapsed=42.9s

  [1881/21087] intraday_10801.csv.gz  in=194,546,737 out=0 elapsed=42.9s

  [1882/21087] intraday_10802.csv.gz  in=194,546,738 out=0 elapsed=42.9s

  [1883/21087] intraday_10803.csv.gz  in=194,546,741 out=0 elapsed=42.9s

  [1884/21087] intraday_10805.csv.gz  in=194,546,744 out=0 elapsed=42.9s

  [1885/21087] intraday_10806.csv.gz  in=194,546,747 out=0 elapsed=42.9s

  [1886/21087] intraday_10807.csv.gz  in=194,546,748 out=0 elapsed=42.9s

  [1887/21087] intraday_1080.csv.gz  in=194,559,655 out=0 elapsed=42.9s

  [1888/21087] intraday_10804.csv.gz  in=194,559,756 out=0 elapsed=42.9s

  [1889/21087] intraday_10808.csv.gz  in=194,559,759 out=0 elapsed=42.9s

  [1890/21087] intraday_10809.csv.gz  in=194,559,760 out=0 elapsed=42.9s

  [1891/21087] intraday_10812.csv.gz  in=194,559,762 out=0 elapsed=42.9s

  [1892/21087] intraday_10811.csv.gz  in=194,559,765 out=0 elapsed=42.9s

  [1893/21087] intraday_10810.csv.gz  in=194,566,452 out=0 elapsed=42.9s

  [1894/21087] intraday_1081.csv.gz  in=194,579,658 out=0 elapsed=42.9s

  [1895/21087] intraday_10813.csv.gz  in=194,579,661 out=0 elapsed=42.9s

  [1896/21087] intraday_10814.csv.gz  in=194,579,973 out=0 elapsed=42.9s

  [1897/21087] intraday_10815.csv.gz  in=194,579,976 out=0 elapsed=42.9s

  [1898/21087] intraday_10818.csv.gz  in=194,579,979 out=0 elapsed=43.0s

  [1899/21087] intraday_10819.csv.gz  in=194,579,987 out=0 elapsed=43.0s

  [1900/21087] intraday_10817.csv.gz  in=194,580,035 out=0 elapsed=43.0s

  [1901/21087] intraday_10820.csv.gz  in=194,580,036 out=0 elapsed=43.0s

  [1902/21087] intraday_10816.csv.gz  in=194,583,657 out=0 elapsed=43.0s

  [1903/21087] intraday_10821.csv.gz  in=194,583,658 out=0 elapsed=43.0s

  [1904/21087] intraday_10823.csv.gz  in=194,583,661 out=0 elapsed=43.0s

  [1905/21087] intraday_1082.csv.gz  in=194,604,756 out=0 elapsed=43.0s

  [1906/21087] intraday_10822.csv.gz  in=194,604,856 out=0 elapsed=43.0s

  [1907/21087] intraday_10825.csv.gz  in=194,604,863 out=0 elapsed=43.0s

  [1908/21087] intraday_10824.csv.gz  in=194,604,868 out=0 elapsed=43.0s

  [1909/21087] intraday_10826.csv.gz  in=194,604,881 out=0 elapsed=43.0s

  [1910/21087] intraday_10829.csv.gz  in=194,604,886 out=0 elapsed=43.0s

  [1911/21087] intraday_10828.csv.gz  in=194,604,924 out=0 elapsed=43.0s

  [1912/21087] intraday_10827.csv.gz  in=194,604,926 out=0 elapsed=43.0s

  [1913/21087] intraday_10830.csv.gz  in=194,604,933 out=0 elapsed=43.0s

  [1914/21087] intraday_10831.csv.gz  in=194,604,939 out=0 elapsed=43.0s

  [1915/21087] intraday_10832.csv.gz  in=194,604,943 out=0 elapsed=43.0s

  [1916/21087] intraday_10833.csv.gz  in=194,604,951 out=0 elapsed=43.0s

  [1917/21087] intraday_10835.csv.gz  in=194,605,212 out=0 elapsed=43.0s

  [1918/21087] intraday_1083.csv.gz  in=194,619,108 out=0 elapsed=43.0s

  [1919/21087] intraday_10834.csv.gz  in=194,621,653 out=0 elapsed=43.0s

  [1920/21087] intraday_10836.csv.gz  in=194,621,656 out=0 elapsed=43.1s

  [1921/21087] intraday_10837.csv.gz  in=194,621,658 out=0 elapsed=43.1s

  [1922/21087] intraday_10838.csv.gz  in=194,621,662 out=0 elapsed=43.1s

  [1923/21087] intraday_10839.csv.gz  in=194,621,695 out=0 elapsed=43.1s

  [1924/21087] intraday_10840.csv.gz  in=194,621,698 out=0 elapsed=43.1s

  [1925/21087] intraday_10841.csv.gz  in=194,621,699 out=0 elapsed=43.1s

  [1926/21087] intraday_10842.csv.gz  in=194,621,708 out=0 elapsed=43.1s

  [1927/21087] intraday_10843.csv.gz  in=194,621,710 out=0 elapsed=43.1s

  [1928/21087] intraday_1084.csv.gz  in=194,634,903 out=0 elapsed=43.1s

  [1929/21087] intraday_10845.csv.gz  in=194,634,908 out=0 elapsed=43.1s

  [1930/21087] intraday_10844.csv.gz  in=194,635,226 out=0 elapsed=43.1s

  [1931/21087] intraday_10846.csv.gz  in=194,635,230 out=0 elapsed=43.1s

  [1932/21087] intraday_10848.csv.gz  in=194,635,233 out=0 elapsed=43.1s

  [1933/21087] intraday_10849.csv.gz  in=194,635,236 out=0 elapsed=43.1s

  [1934/21087] intraday_10847.csv.gz  in=194,635,240 out=0 elapsed=43.1s

  [1935/21087] intraday_10850.csv.gz  in=194,635,243 out=0 elapsed=43.1s

  [1936/21087] intraday_10851.csv.gz  in=194,635,246 out=0 elapsed=43.1s

  [1937/21087] intraday_10852.csv.gz  in=194,635,261 out=0 elapsed=43.1s

  [1938/21087] intraday_1085.csv.gz  in=194,648,434 out=0 elapsed=43.1s

  [1939/21087] intraday_10854.csv.gz  in=194,648,435 out=0 elapsed=43.1s

  [1940/21087] intraday_10853.csv.gz  in=194,648,439 out=0 elapsed=43.1s

  [1941/21087] intraday_10855.csv.gz  in=194,648,444 out=0 elapsed=43.1s

  [1942/21087] intraday_10856.csv.gz  in=194,648,446 out=0 elapsed=43.1s

  [1943/21087] intraday_10858.csv.gz  in=194,648,447 out=0 elapsed=43.1s

  [1944/21087] intraday_10857.csv.gz  in=194,649,023 out=0 elapsed=43.2s

  [1945/21087] intraday_10859.csv.gz  in=194,649,682 out=0 elapsed=43.2s

  [1946/21087] intraday_10860.csv.gz  in=194,649,775 out=0 elapsed=43.2s

  [1947/21087] intraday_10862.csv.gz  in=194,649,790 out=0 elapsed=43.2s

  [1948/21087] intraday_10861.csv.gz  in=194,650,090 out=0 elapsed=43.2s

  [1949/21087] intraday_1086.csv.gz  in=194,660,557 out=0 elapsed=43.2s

  [1950/21087] intraday_10863.csv.gz  in=194,660,575 out=0 elapsed=43.2s

  [1951/21087] intraday_10864.csv.gz  in=194,661,350 out=0 elapsed=43.2s

  [1952/21087] intraday_10865.csv.gz  in=194,661,491 out=0 elapsed=43.2s

  [1953/21087] intraday_10866.csv.gz  in=194,662,583 out=0 elapsed=43.2s

  [1954/21087] intraday_10867.csv.gz  in=194,662,776 out=0 elapsed=43.2s

  [1955/21087] intraday_10869.csv.gz  in=194,663,190 out=0 elapsed=43.2s

  [1956/21087] intraday_10868.csv.gz  in=194,665,424 out=0 elapsed=43.2s

  [1957/21087] intraday_10872.csv.gz  in=194,665,530 out=0 elapsed=43.3s

  [1958/21087] intraday_1087.csv.gz  in=194,678,825 out=0 elapsed=43.3s

  [1959/21087] intraday_10871.csv.gz  in=194,679,067 out=0 elapsed=43.3s

  [1960/21087] intraday_10870.csv.gz  in=194,691,964 out=0 elapsed=43.3s

  [1961/21087] intraday_10875.csv.gz  in=194,691,973 out=0 elapsed=43.3s

  [1962/21087] intraday_10874.csv.gz  in=194,692,578 out=0 elapsed=43.3s

  [1963/21087] intraday_10873.csv.gz  in=194,692,653 out=0 elapsed=43.3s

  [1964/21087] intraday_10876.csv.gz  in=194,696,348 out=0 elapsed=43.3s

  [1965/21087] intraday_10877.csv.gz  in=194,696,469 out=0 elapsed=43.3s

  [1966/21087] intraday_10879.csv.gz  in=194,696,562 out=0 elapsed=43.3s

  [1967/21087] intraday_10878.csv.gz  in=194,696,835 out=0 elapsed=43.3s

  [1968/21087] intraday_1088.csv.gz  in=194,709,040 out=0 elapsed=43.3s

  [1969/21087] intraday_10880.csv.gz  in=194,709,084 out=0 elapsed=43.3s

  [1970/21087] intraday_10881.csv.gz  in=194,710,361 out=0 elapsed=43.3s

  [1971/21087] intraday_10882.csv.gz  in=194,713,834 out=0 elapsed=43.3s

  [1972/21087] intraday_10883.csv.gz  in=194,714,234 out=0 elapsed=43.4s

  [1973/21087] intraday_10885.csv.gz  in=194,714,353 out=0 elapsed=43.4s

  [1974/21087] intraday_10884.csv.gz  in=194,714,372 out=0 elapsed=43.4s

  [1975/21087] intraday_10886.csv.gz  in=194,714,385 out=0 elapsed=43.4s

  [1976/21087] intraday_10887.csv.gz  in=194,714,486 out=0 elapsed=43.4s

  [1977/21087] intraday_10888.csv.gz  in=194,715,047 out=0 elapsed=43.4s

  [1978/21087] intraday_10889.csv.gz  in=194,715,173 out=0 elapsed=43.4s

  [1979/21087] intraday_10890.csv.gz  in=194,715,315 out=0 elapsed=43.4s

  [1980/21087] intraday_1089.csv.gz  in=194,726,199 out=0 elapsed=43.4s

  [1981/21087] intraday_10891.csv.gz  in=194,726,510 out=0 elapsed=43.4s

  [1982/21087] intraday_10892.csv.gz  in=194,726,655 out=0 elapsed=43.4s

  [1983/21087] intraday_10893.csv.gz  in=194,726,791 out=0 elapsed=43.4s

  [1984/21087] intraday_10894.csv.gz  in=194,726,882 out=0 elapsed=43.4s

  [1985/21087] intraday_10896.csv.gz  in=194,726,908 out=0 elapsed=43.5s

  [1986/21087] intraday_10897.csv.gz  in=194,727,052 out=0 elapsed=43.5s

  [1987/21087] intraday_10895.csv.gz  in=194,727,316 out=0 elapsed=43.5s

  [1988/21087] intraday_10898.csv.gz  in=194,729,147 out=0 elapsed=43.5s

  [1989/21087] intraday_10899.csv.gz  in=194,729,450 out=0 elapsed=43.5s

  [1990/21087] intraday_10900.csv.gz  in=194,729,484 out=0 elapsed=43.5s

  [1991/21087] intraday_10901.csv.gz  in=194,730,350 out=0 elapsed=43.5s

  [1992/21087] intraday_1090.csv.gz  in=194,738,155 out=0 elapsed=43.5s

  [1993/21087] intraday_10902.csv.gz  in=194,738,185 out=0 elapsed=43.5s

  [1994/21087] intraday_10903.csv.gz  in=194,738,197 out=0 elapsed=43.5s

  [1995/21087] intraday_10904.csv.gz  in=194,738,199 out=0 elapsed=43.5s

  [1996/21087] intraday_10905.csv.gz  in=194,738,208 out=0 elapsed=43.5s

  [1997/21087] intraday_10907.csv.gz  in=194,738,910 out=0 elapsed=43.5s

  [1998/21087] intraday_10909.csv.gz  in=194,738,919 out=0 elapsed=43.5s

  [1999/21087] intraday_10906.csv.gz  in=194,739,097 out=0 elapsed=43.5s

  [2000/21087] intraday_10908.csv.gz  in=194,741,278 out=0 elapsed=43.5s

  [2001/21087] intraday_10910.csv.gz  in=194,741,333 out=0 elapsed=43.6s

  [2002/21087] intraday_1091.csv.gz  in=194,753,787 out=0 elapsed=43.6s

  [2003/21087] intraday_10912.csv.gz  in=194,765,449 out=0 elapsed=43.6s

  [2004/21087] intraday_10911.csv.gz  in=194,781,414 out=0 elapsed=43.6s

  [2005/21087] intraday_10914.csv.gz  in=194,791,616 out=0 elapsed=43.6s

  [2006/21087] intraday_10913.csv.gz  in=194,805,461 out=0 elapsed=43.6s

  [2007/21087] intraday_10916.csv.gz  in=194,819,352 out=0 elapsed=43.6s

  [2008/21087] intraday_10915.csv.gz  in=194,831,278 out=0 elapsed=43.6s

  [2009/21087] intraday_10917.csv.gz  in=194,845,796 out=0 elapsed=43.6s

  [2010/21087] intraday_10918.csv.gz  in=194,856,895 out=0 elapsed=43.6s

  [2011/21087] intraday_10919.csv.gz  in=194,867,997 out=0 elapsed=43.7s

  [2012/21087] intraday_1092.csv.gz  in=194,874,308 out=0 elapsed=43.7s

  [2013/21087] intraday_10920.csv.gz  in=194,887,779 out=0 elapsed=43.7s

  [2014/21087] intraday_10922.csv.gz  in=194,898,602 out=0 elapsed=43.7s

  [2015/21087] intraday_10921.csv.gz  in=194,911,528 out=0 elapsed=43.7s

  [2016/21087] intraday_10923.csv.gz  in=194,924,696 out=0 elapsed=43.7s

  [2017/21087] intraday_10924.csv.gz  in=194,939,774 out=0 elapsed=43.7s

  [2018/21087] intraday_10925.csv.gz  in=194,949,014 out=0 elapsed=43.7s

  [2019/21087] intraday_10927.csv.gz  in=194,963,310 out=0 elapsed=43.7s

  [2020/21087] intraday_10926.csv.gz  in=194,973,460 out=0 elapsed=43.7s

  [2021/21087] intraday_10928.csv.gz  in=194,987,891 out=0 elapsed=43.7s

  [2022/21087] intraday_10929.csv.gz  in=195,000,206 out=0 elapsed=43.7s

  [2023/21087] intraday_10930.csv.gz  in=195,010,550 out=0 elapsed=43.8s

  [2024/21087] intraday_1093.csv.gz  in=195,025,419 out=0 elapsed=43.8s

  [2025/21087] intraday_10931.csv.gz  in=195,036,739 out=0 elapsed=43.8s

  [2026/21087] intraday_10932.csv.gz  in=195,053,385 out=0 elapsed=43.8s

  [2027/21087] intraday_10933.csv.gz  in=195,064,852 out=0 elapsed=43.8s

  [2028/21087] intraday_10934.csv.gz  in=195,077,482 out=0 elapsed=43.8s

  [2029/21087] intraday_10935.csv.gz  in=195,089,998 out=0 elapsed=43.8s

  [2030/21087] intraday_10936.csv.gz  in=195,100,659 out=0 elapsed=43.8s

  [2031/21087] intraday_10938.csv.gz  in=195,111,417 out=0 elapsed=43.8s

  [2032/21087] intraday_10937.csv.gz  in=195,134,143 out=0 elapsed=43.8s

  [2033/21087] intraday_10939.csv.gz  in=195,144,607 out=0 elapsed=43.8s

  [2034/21087] intraday_1094.csv.gz  in=195,159,395 out=0 elapsed=43.8s

  [2035/21087] intraday_10940.csv.gz  in=195,172,591 out=0 elapsed=43.9s

  [2036/21087] intraday_10941.csv.gz  in=195,187,708 out=0 elapsed=43.9s

  [2037/21087] intraday_10942.csv.gz  in=195,201,341 out=0 elapsed=43.9s

  [2038/21087] intraday_10943.csv.gz  in=195,210,527 out=0 elapsed=43.9s

  [2039/21087] intraday_10944.csv.gz  in=195,221,468 out=0 elapsed=43.9s

  [2040/21087] intraday_10945.csv.gz  in=195,235,083 out=0 elapsed=43.9s

  [2041/21087] intraday_10947.csv.gz  in=195,246,027 out=0 elapsed=43.9s

  [2042/21087] intraday_10946.csv.gz  in=195,256,968 out=0 elapsed=43.9s

  [2043/21087] intraday_10948.csv.gz  in=195,268,883 out=0 elapsed=43.9s

  [2044/21087] intraday_10949.csv.gz  in=195,279,383 out=0 elapsed=43.9s

  [2045/21087] intraday_1095.csv.gz  in=195,291,322 out=0 elapsed=43.9s

  [2046/21087] intraday_10950.csv.gz  in=195,301,260 out=0 elapsed=43.9s

  [2047/21087] intraday_10951.csv.gz  in=195,311,151 out=0 elapsed=43.9s

  [2048/21087] intraday_10952.csv.gz  in=195,321,776 out=0 elapsed=43.9s

  [2049/21087] intraday_10954.csv.gz  in=195,334,020 out=0 elapsed=44.0s

  [2050/21087] intraday_10953.csv.gz  in=195,347,281 out=0 elapsed=44.0s

  [2051/21087] intraday_10956.csv.gz  in=195,358,587 out=0 elapsed=44.0s

  [2052/21087] intraday_10955.csv.gz  in=195,372,863 out=0 elapsed=44.0s

  [2053/21087] intraday_10957.csv.gz  in=195,383,173 out=0 elapsed=44.0s

  [2054/21087] intraday_10958.csv.gz  in=195,394,892 out=0 elapsed=44.0s

  [2055/21087] intraday_10959.csv.gz  in=195,406,375 out=0 elapsed=44.0s

  [2056/21087] intraday_1096.csv.gz  in=195,417,949 out=0 elapsed=44.0s

  [2057/21087] intraday_10960.csv.gz  in=195,427,571 out=0 elapsed=44.0s

  [2058/21087] intraday_10962.csv.gz  in=195,437,976 out=0 elapsed=44.0s

  [2059/21087] intraday_10961.csv.gz  in=195,449,273 out=0 elapsed=44.0s

  [2060/21087] intraday_10963.csv.gz  in=195,460,919 out=0 elapsed=44.0s

  [2061/21087] intraday_10964.csv.gz  in=195,472,037 out=0 elapsed=44.1s

  [2062/21087] intraday_10965.csv.gz  in=195,485,603 out=0 elapsed=44.1s

  [2063/21087] intraday_10966.csv.gz  in=195,498,683 out=0 elapsed=44.1s

  [2064/21087] intraday_10967.csv.gz  in=195,512,098 out=0 elapsed=44.1s

  [2065/21087] intraday_10969.csv.gz  in=195,521,625 out=0 elapsed=44.1s

  [2066/21087] intraday_10968.csv.gz  in=195,549,112 out=0 elapsed=44.1s

  [2067/21087] intraday_1097.csv.gz  in=195,564,167 out=0 elapsed=44.1s

  [2068/21087] intraday_10970.csv.gz  in=195,576,398 out=0 elapsed=44.1s

  [2069/21087] intraday_10971.csv.gz  in=195,589,078 out=0 elapsed=44.1s

  [2070/21087] intraday_10972.csv.gz  in=195,599,178 out=0 elapsed=44.1s

  [2071/21087] intraday_10974.csv.gz  in=195,610,120 out=0 elapsed=44.1s

  [2072/21087] intraday_10973.csv.gz  in=195,623,176 out=0 elapsed=44.1s

  [2073/21087] intraday_10975.csv.gz  in=195,633,783 out=0 elapsed=44.1s

  [2074/21087] intraday_10976.csv.gz  in=195,644,289 out=0 elapsed=44.2s

  [2075/21087] intraday_10977.csv.gz  in=195,659,010 out=0 elapsed=44.2s

  [2076/21087] intraday_10978.csv.gz  in=195,675,587 out=0 elapsed=44.2s

  [2077/21087] intraday_10979.csv.gz  in=195,688,699 out=0 elapsed=44.2s

  [2078/21087] intraday_10980.csv.gz  in=195,700,920 out=0 elapsed=44.2s

  [2079/21087] intraday_1098.csv.gz  in=195,715,464 out=0 elapsed=44.2s

  [2080/21087] intraday_10981.csv.gz  in=195,727,336 out=0 elapsed=44.2s

  [2081/21087] intraday_10982.csv.gz  in=195,738,435 out=0 elapsed=44.2s

  [2082/21087] intraday_10983.csv.gz  in=195,750,840 out=0 elapsed=44.2s

  [2083/21087] intraday_10984.csv.gz  in=195,765,851 out=0 elapsed=44.2s

  [2084/21087] intraday_10985.csv.gz  in=195,778,235 out=0 elapsed=44.2s

  [2085/21087] intraday_10986.csv.gz  in=195,788,900 out=0 elapsed=44.2s

  [2086/21087] intraday_10987.csv.gz  in=195,801,706 out=0 elapsed=44.2s

  [2087/21087] intraday_10988.csv.gz  in=195,812,223 out=0 elapsed=44.3s

  [2088/21087] intraday_10989.csv.gz  in=195,825,462 out=0 elapsed=44.3s

  [2089/21087] intraday_1099.csv.gz  in=195,837,318 out=0 elapsed=44.3s

  [2090/21087] intraday_10990.csv.gz  in=195,847,436 out=0 elapsed=44.3s

  [2091/21087] intraday_10991.csv.gz  in=195,859,537 out=0 elapsed=44.3s

  [2092/21087] intraday_10993.csv.gz  in=195,868,214 out=0 elapsed=44.3s

  [2093/21087] intraday_10992.csv.gz  in=195,885,108 out=0 elapsed=44.3s

  [2094/21087] intraday_10994.csv.gz  in=195,896,714 out=0 elapsed=44.3s

  [2095/21087] intraday_10995.csv.gz  in=195,909,785 out=0 elapsed=44.3s

  [2096/21087] intraday_10996.csv.gz  in=195,931,899 out=0 elapsed=44.3s

  [2097/21087] intraday_10997.csv.gz  in=195,943,151 out=0 elapsed=44.3s

  [2098/21087] intraday_10998.csv.gz  in=195,954,810 out=0 elapsed=44.3s

  [2099/21087] intraday_10999.csv.gz  in=195,970,880 out=0 elapsed=44.4s

  [2100/21087] intraday_1100.csv.gz  in=195,983,560 out=0 elapsed=44.4s

  [2101/21087] intraday_11000.csv.gz  in=195,997,140 out=0 elapsed=44.4s

  [2102/21087] intraday_11001.csv.gz  in=196,008,015 out=0 elapsed=44.4s

  [2103/21087] intraday_11002.csv.gz  in=196,023,949 out=0 elapsed=44.4s

  [2104/21087] intraday_11003.csv.gz  in=196,035,121 out=0 elapsed=44.4s

  [2105/21087] intraday_11005.csv.gz  in=196,047,874 out=0 elapsed=44.4s

  [2106/21087] intraday_11004.csv.gz  in=196,073,692 out=0 elapsed=44.4s

  [2107/21087] intraday_11007.csv.gz  in=196,086,615 out=0 elapsed=44.4s

  [2108/21087] intraday_11006.csv.gz  in=196,099,930 out=0 elapsed=44.4s

  [2109/21087] intraday_11008.csv.gz  in=196,111,150 out=0 elapsed=44.4s

  [2110/21087] intraday_1101.csv.gz  in=196,125,331 out=0 elapsed=44.4s

  [2111/21087] intraday_11009.csv.gz  in=196,138,657 out=0 elapsed=44.4s

  [2112/21087] intraday_11010.csv.gz  in=196,150,327 out=0 elapsed=44.5s

  [2113/21087] intraday_11011.csv.gz  in=196,162,485 out=0 elapsed=44.5s

  [2114/21087] intraday_11012.csv.gz  in=196,174,603 out=0 elapsed=44.5s

  [2115/21087] intraday_11014.csv.gz  in=196,186,706 out=0 elapsed=44.5s

  [2116/21087] intraday_11013.csv.gz  in=196,197,830 out=0 elapsed=44.5s

  [2117/21087] intraday_11015.csv.gz  in=196,212,256 out=0 elapsed=44.5s

  [2118/21087] intraday_11016.csv.gz  in=196,224,591 out=0 elapsed=44.5s

  [2119/21087] intraday_11017.csv.gz  in=196,236,357 out=0 elapsed=44.5s

  [2120/21087] intraday_11018.csv.gz  in=196,248,776 out=0 elapsed=44.5s

  [2121/21087] intraday_11019.csv.gz  in=196,262,463 out=0 elapsed=44.5s

  [2122/21087] intraday_11020.csv.gz  in=196,274,353 out=0 elapsed=44.6s

  [2123/21087] intraday_1102.csv.gz  in=196,289,202 out=0 elapsed=44.6s

  [2124/21087] intraday_11021.csv.gz  in=196,302,566 out=0 elapsed=44.6s

  [2125/21087] intraday_11022.csv.gz  in=196,313,213 out=0 elapsed=44.6s

  [2126/21087] intraday_11024.csv.gz  in=196,325,163 out=0 elapsed=44.6s

  [2127/21087] intraday_11023.csv.gz  in=196,338,716 out=0 elapsed=44.6s

  [2128/21087] intraday_11025.csv.gz  in=196,352,312 out=0 elapsed=44.6s

  [2129/21087] intraday_11026.csv.gz  in=196,373,880 out=0 elapsed=44.6s

  [2130/21087] intraday_11027.csv.gz  in=196,389,649 out=0 elapsed=44.6s

  [2131/21087] intraday_11028.csv.gz  in=196,405,393 out=0 elapsed=44.6s

  [2132/21087] intraday_11029.csv.gz  in=196,420,641 out=0 elapsed=44.6s

  [2133/21087] intraday_1103.csv.gz  in=196,431,363 out=0 elapsed=44.6s

  [2134/21087] intraday_11030.csv.gz  in=196,447,942 out=0 elapsed=44.7s

  [2135/21087] intraday_11032.csv.gz  in=196,461,341 out=0 elapsed=44.7s

  [2136/21087] intraday_11031.csv.gz  in=196,478,433 out=0 elapsed=44.7s

  [2137/21087] intraday_11033.csv.gz  in=196,490,462 out=0 elapsed=44.7s

  [2138/21087] intraday_11034.csv.gz  in=196,501,582 out=0 elapsed=44.7s

  [2139/21087] intraday_11035.csv.gz  in=196,511,987 out=0 elapsed=44.7s

  [2140/21087] intraday_11037.csv.gz  in=196,522,678 out=0 elapsed=44.7s

  [2141/21087] intraday_11036.csv.gz  in=196,536,094 out=0 elapsed=44.7s

  [2142/21087] intraday_11038.csv.gz  in=196,549,084 out=0 elapsed=44.7s

  [2143/21087] intraday_11039.csv.gz  in=196,562,519 out=0 elapsed=44.7s

  [2144/21087] intraday_1104.csv.gz  in=196,575,204 out=0 elapsed=44.7s

  [2145/21087] intraday_11041.csv.gz  in=196,585,432 out=0 elapsed=44.7s

  [2146/21087] intraday_11040.csv.gz  in=196,602,081 out=0 elapsed=44.8s

  [2147/21087] intraday_11042.csv.gz  in=196,612,316 out=0 elapsed=44.8s

  [2148/21087] intraday_11043.csv.gz  in=196,625,020 out=0 elapsed=44.8s

  [2149/21087] intraday_11044.csv.gz  in=196,636,694 out=0 elapsed=44.8s

  [2150/21087] intraday_11045.csv.gz  in=196,648,038 out=0 elapsed=44.8s

  [2151/21087] intraday_11046.csv.gz  in=196,663,993 out=0 elapsed=44.8s

  [2152/21087] intraday_11047.csv.gz  in=196,679,877 out=0 elapsed=44.8s

  [2153/21087] intraday_11048.csv.gz  in=196,693,462 out=0 elapsed=44.8s

  [2154/21087] intraday_11049.csv.gz  in=196,708,220 out=0 elapsed=44.8s

  [2155/21087] intraday_1105.csv.gz  in=196,723,537 out=0 elapsed=44.8s

  [2156/21087] intraday_11050.csv.gz  in=196,734,744 out=0 elapsed=44.8s

  [2157/21087] intraday_11051.csv.gz  in=196,746,548 out=0 elapsed=44.9s

  [2158/21087] intraday_11052.csv.gz  in=196,758,661 out=0 elapsed=44.9s

  [2159/21087] intraday_11053.csv.gz  in=196,771,048 out=0 elapsed=44.9s

  [2160/21087] intraday_11054.csv.gz  in=196,780,795 out=0 elapsed=44.9s

  [2161/21087] intraday_11055.csv.gz  in=196,787,001 out=0 elapsed=44.9s

  [2162/21087] intraday_11056.csv.gz  in=196,797,593 out=0 elapsed=44.9s

  [2163/21087] intraday_11057.csv.gz  in=196,803,809 out=0 elapsed=44.9s

  [2164/21087] intraday_11058.csv.gz  in=196,817,842 out=0 elapsed=44.9s

  [2165/21087] intraday_11059.csv.gz  in=196,828,864 out=0 elapsed=44.9s

  [2166/21087] intraday_1106.csv.gz  in=196,840,242 out=0 elapsed=44.9s

  [2167/21087] intraday_11060.csv.gz  in=196,854,438 out=0 elapsed=44.9s

  [2168/21087] intraday_11061.csv.gz  in=196,864,775 out=0 elapsed=44.9s

  [2169/21087] intraday_11062.csv.gz  in=196,876,602 out=0 elapsed=44.9s

  [2170/21087] intraday_11063.csv.gz  in=196,889,235 out=0 elapsed=45.0s

  [2171/21087] intraday_11065.csv.gz  in=196,899,648 out=0 elapsed=45.0s

  [2172/21087] intraday_11064.csv.gz  in=196,913,071 out=0 elapsed=45.0s

  [2173/21087] intraday_11066.csv.gz  in=196,924,369 out=0 elapsed=45.0s

  [2174/21087] intraday_11068.csv.gz  in=196,936,878 out=0 elapsed=45.0s

  [2175/21087] intraday_11067.csv.gz  in=196,949,839 out=0 elapsed=45.0s

  [2176/21087] intraday_11069.csv.gz  in=196,960,177 out=0 elapsed=45.0s

  [2177/21087] intraday_1107.csv.gz  in=196,970,341 out=0 elapsed=45.0s

  [2178/21087] intraday_11070.csv.gz  in=196,982,600 out=0 elapsed=45.0s

  [2179/21087] intraday_11071.csv.gz  in=196,995,312 out=0 elapsed=45.0s

  [2180/21087] intraday_11072.csv.gz  in=197,005,821 out=0 elapsed=45.0s

  [2181/21087] intraday_11073.csv.gz  in=197,016,252 out=0 elapsed=45.0s

  [2182/21087] intraday_11075.csv.gz  in=197,028,561 out=0 elapsed=45.1s

  [2183/21087] intraday_11074.csv.gz  in=197,041,762 out=0 elapsed=45.1s

  [2184/21087] intraday_11077.csv.gz  in=197,051,520 out=0 elapsed=45.1s

  [2185/21087] intraday_11076.csv.gz  in=197,063,688 out=0 elapsed=45.1s

  [2186/21087] intraday_11078.csv.gz  in=197,075,025 out=0 elapsed=45.1s

  [2187/21087] intraday_11079.csv.gz  in=197,086,100 out=0 elapsed=45.1s

  [2188/21087] intraday_1108.csv.gz  in=197,099,154 out=0 elapsed=45.1s

  [2189/21087] intraday_11080.csv.gz  in=197,111,362 out=0 elapsed=45.1s

  [2190/21087] intraday_11081.csv.gz  in=197,123,160 out=0 elapsed=45.1s

  [2191/21087] intraday_11082.csv.gz  in=197,136,111 out=0 elapsed=45.1s

  [2192/21087] intraday_11083.csv.gz  in=197,147,180 out=0 elapsed=45.1s

  [2193/21087] intraday_11084.csv.gz  in=197,160,403 out=0 elapsed=45.1s

  [2194/21087] intraday_11085.csv.gz  in=197,171,120 out=0 elapsed=45.2s

  [2195/21087] intraday_11086.csv.gz  in=197,181,362 out=0 elapsed=45.2s

  [2196/21087] intraday_11087.csv.gz  in=197,194,662 out=0 elapsed=45.2s

  [2197/21087] intraday_11088.csv.gz  in=197,209,464 out=0 elapsed=45.2s

  [2198/21087] intraday_11089.csv.gz  in=197,222,850 out=0 elapsed=45.2s

  [2199/21087] intraday_1109.csv.gz  in=197,235,501 out=0 elapsed=45.2s

  [2200/21087] intraday_11090.csv.gz  in=197,244,830 out=0 elapsed=45.2s

  [2201/21087] intraday_11091.csv.gz  in=197,254,308 out=0 elapsed=45.2s

  [2202/21087] intraday_11092.csv.gz  in=197,266,001 out=0 elapsed=45.2s

  [2203/21087] intraday_11093.csv.gz  in=197,278,927 out=0 elapsed=45.2s

  [2204/21087] intraday_11094.csv.gz  in=197,289,094 out=0 elapsed=45.2s

  [2205/21087] intraday_11095.csv.gz  in=197,300,211 out=0 elapsed=45.2s

  [2206/21087] intraday_11096.csv.gz  in=197,311,358 out=0 elapsed=45.2s

  [2207/21087] intraday_11097.csv.gz  in=197,320,203 out=0 elapsed=45.3s

  [2208/21087] intraday_11098.csv.gz  in=197,330,194 out=0 elapsed=45.3s

  [2209/21087] intraday_11099.csv.gz  in=197,340,712 out=0 elapsed=45.3s

  [2210/21087] intraday_1110.csv.gz  in=197,360,522 out=0 elapsed=45.3s

  [2211/21087] intraday_11100.csv.gz  in=197,373,711 out=0 elapsed=45.3s

  [2212/21087] intraday_11102.csv.gz  in=197,386,487 out=0 elapsed=45.3s

  [2213/21087] intraday_11101.csv.gz  in=197,399,364 out=0 elapsed=45.3s

  [2214/21087] intraday_11103.csv.gz  in=197,411,466 out=0 elapsed=45.3s

  [2215/21087] intraday_11104.csv.gz  in=197,421,528 out=0 elapsed=45.3s

  [2216/21087] intraday_11105.csv.gz  in=197,432,861 out=0 elapsed=45.3s

  [2217/21087] intraday_11106.csv.gz  in=197,445,117 out=0 elapsed=45.3s

  [2218/21087] intraday_11107.csv.gz  in=197,453,322 out=0 elapsed=45.4s

  [2219/21087] intraday_11108.csv.gz  in=197,464,838 out=0 elapsed=45.4s

  [2220/21087] intraday_11109.csv.gz  in=197,475,447 out=0 elapsed=45.4s

  [2221/21087] intraday_11110.csv.gz  in=197,486,147 out=0 elapsed=45.4s

  [2222/21087] intraday_1111.csv.gz  in=197,497,797 out=0 elapsed=45.4s

  [2223/21087] intraday_11111.csv.gz  in=197,509,990 out=0 elapsed=45.4s

  [2224/21087] intraday_11112.csv.gz  in=197,522,306 out=0 elapsed=45.4s

  [2225/21087] intraday_11115.csv.gz  in=197,535,048 out=0 elapsed=45.4s

  [2226/21087] intraday_11113.csv.gz  in=197,546,897 out=0 elapsed=45.4s

  [2227/21087] intraday_11114.csv.gz  in=197,558,988 out=0 elapsed=45.4s

  [2228/21087] intraday_11116.csv.gz  in=197,568,137 out=0 elapsed=45.4s

  [2229/21087] intraday_11118.csv.gz  in=197,579,765 out=0 elapsed=45.5s

  [2230/21087] intraday_11117.csv.gz  in=197,592,777 out=0 elapsed=45.5s

  [2231/21087] intraday_11119.csv.gz  in=197,603,258 out=0 elapsed=45.5s

  [2232/21087] intraday_1112.csv.gz  in=197,614,472 out=0 elapsed=45.5s

  [2233/21087] intraday_11120.csv.gz  in=197,626,390 out=0 elapsed=45.5s

  [2234/21087] intraday_11121.csv.gz  in=197,636,720 out=0 elapsed=45.5s

  [2235/21087] intraday_11122.csv.gz  in=197,646,271 out=0 elapsed=45.5s

  [2236/21087] intraday_11123.csv.gz  in=197,657,164 out=0 elapsed=45.5s

  [2237/21087] intraday_11124.csv.gz  in=197,673,111 out=0 elapsed=45.5s

  [2238/21087] intraday_11125.csv.gz  in=197,685,761 out=0 elapsed=45.5s

  [2239/21087] intraday_11126.csv.gz  in=197,698,870 out=0 elapsed=45.5s

  [2240/21087] intraday_11127.csv.gz  in=197,710,324 out=0 elapsed=45.5s

  [2241/21087] intraday_11128.csv.gz  in=197,721,748 out=0 elapsed=45.5s

  [2242/21087] intraday_11129.csv.gz  in=197,732,838 out=0 elapsed=45.5s

  [2243/21087] intraday_1113.csv.gz  in=197,750,415 out=0 elapsed=45.6s

  [2244/21087] intraday_11130.csv.gz  in=197,761,905 out=0 elapsed=45.6s

  [2245/21087] intraday_11131.csv.gz  in=197,774,871 out=0 elapsed=45.6s

  [2246/21087] intraday_11132.csv.gz  in=197,787,665 out=0 elapsed=45.6s

  [2247/21087] intraday_11133.csv.gz  in=197,798,214 out=0 elapsed=45.6s

  [2248/21087] intraday_11134.csv.gz  in=197,808,137 out=0 elapsed=45.6s

  [2249/21087] intraday_11135.csv.gz  in=197,819,243 out=0 elapsed=45.6s

  [2250/21087] intraday_11136.csv.gz  in=197,832,492 out=0 elapsed=45.6s

  [2251/21087] intraday_11137.csv.gz  in=197,842,332 out=0 elapsed=45.6s

  [2252/21087] intraday_11139.csv.gz  in=197,850,810 out=0 elapsed=45.6s

  [2253/21087] intraday_11138.csv.gz  in=197,860,994 out=0 elapsed=45.6s

  [2254/21087] intraday_1114.csv.gz  in=197,873,909 out=0 elapsed=45.6s

  [2255/21087] intraday_11140.csv.gz  in=197,883,166 out=0 elapsed=45.6s

  [2256/21087] intraday_11141.csv.gz  in=197,895,164 out=0 elapsed=45.7s

  [2257/21087] intraday_11142.csv.gz  in=197,909,729 out=0 elapsed=45.7s

  [2258/21087] intraday_11144.csv.gz  in=197,921,886 out=0 elapsed=45.7s

  [2259/21087] intraday_11143.csv.gz  in=197,938,141 out=0 elapsed=45.7s

  [2260/21087] intraday_11145.csv.gz  in=197,948,814 out=0 elapsed=45.7s

  [2261/21087] intraday_11146.csv.gz  in=197,960,120 out=0 elapsed=45.7s

  [2262/21087] intraday_11147.csv.gz  in=197,972,953 out=0 elapsed=45.7s

  [2263/21087] intraday_11148.csv.gz  in=197,984,028 out=0 elapsed=45.7s

  [2264/21087] intraday_11149.csv.gz  in=197,997,673 out=0 elapsed=45.7s

  [2265/21087] intraday_1115.csv.gz  in=198,010,627 out=0 elapsed=45.7s

  [2266/21087] intraday_11150.csv.gz  in=198,021,333 out=0 elapsed=45.7s

  [2267/21087] intraday_11151.csv.gz  in=198,035,033 out=0 elapsed=45.7s

  [2268/21087] intraday_11152.csv.gz  in=198,046,966 out=0 elapsed=45.7s

  [2269/21087] intraday_11153.csv.gz  in=198,059,098 out=0 elapsed=45.7s

  [2270/21087] intraday_11154.csv.gz  in=198,071,729 out=0 elapsed=45.8s

  [2271/21087] intraday_11155.csv.gz  in=198,082,470 out=0 elapsed=45.8s

  [2272/21087] intraday_11156.csv.gz  in=198,095,464 out=0 elapsed=45.8s

  [2273/21087] intraday_11157.csv.gz  in=198,105,741 out=0 elapsed=45.8s

  [2274/21087] intraday_11158.csv.gz  in=198,117,291 out=0 elapsed=45.8s

  [2275/21087] intraday_11159.csv.gz  in=198,127,458 out=0 elapsed=45.8s

  [2276/21087] intraday_1116.csv.gz  in=198,140,433 out=0 elapsed=45.8s

  [2277/21087] intraday_11160.csv.gz  in=198,152,310 out=0 elapsed=45.8s

  [2278/21087] intraday_11161.csv.gz  in=198,164,691 out=0 elapsed=45.8s

  [2279/21087] intraday_11162.csv.gz  in=198,177,083 out=0 elapsed=45.8s

  [2280/21087] intraday_11163.csv.gz  in=198,187,407 out=0 elapsed=45.8s

  [2281/21087] intraday_11164.csv.gz  in=198,200,380 out=0 elapsed=45.9s

  [2282/21087] intraday_11166.csv.gz  in=198,213,316 out=0 elapsed=45.9s

  [2283/21087] intraday_11165.csv.gz  in=198,225,196 out=0 elapsed=45.9s

  [2284/21087] intraday_11167.csv.gz  in=198,236,558 out=0 elapsed=45.9s

  [2285/21087] intraday_11169.csv.gz  in=198,249,898 out=0 elapsed=45.9s

  [2286/21087] intraday_11168.csv.gz  in=198,262,226 out=0 elapsed=45.9s

  [2287/21087] intraday_1117.csv.gz  in=198,274,251 out=0 elapsed=45.9s

  [2288/21087] intraday_11170.csv.gz  in=198,285,828 out=0 elapsed=45.9s

  [2289/21087] intraday_11171.csv.gz  in=198,295,918 out=0 elapsed=45.9s

  [2290/21087] intraday_11172.csv.gz  in=198,308,883 out=0 elapsed=45.9s

  [2291/21087] intraday_11174.csv.gz  in=198,323,201 out=0 elapsed=45.9s

  [2292/21087] intraday_11173.csv.gz  in=198,340,661 out=0 elapsed=45.9s

  [2293/21087] intraday_11175.csv.gz  in=198,354,758 out=0 elapsed=45.9s

  [2294/21087] intraday_11176.csv.gz  in=198,370,655 out=0 elapsed=46.0s

  [2295/21087] intraday_11179.csv.gz  in=198,383,009 out=0 elapsed=46.0s

  [2296/21087] intraday_11177.csv.gz  in=198,395,689 out=0 elapsed=46.0s

  [2297/21087] intraday_11178.csv.gz  in=198,409,613 out=0 elapsed=46.0s

  [2298/21087] intraday_1118.csv.gz  in=198,420,182 out=0 elapsed=46.0s

  [2299/21087] intraday_11181.csv.gz  in=198,430,972 out=0 elapsed=46.0s

  [2300/21087] intraday_11180.csv.gz  in=198,443,040 out=0 elapsed=46.0s

  [2301/21087] intraday_11182.csv.gz  in=198,454,224 out=0 elapsed=46.0s

  [2302/21087] intraday_11183.csv.gz  in=198,465,084 out=0 elapsed=46.0s

  [2303/21087] intraday_11184.csv.gz  in=198,477,240 out=0 elapsed=46.0s

  [2304/21087] intraday_11185.csv.gz  in=198,488,782 out=0 elapsed=46.0s

  [2305/21087] intraday_11186.csv.gz  in=198,502,953 out=0 elapsed=46.0s

  [2306/21087] intraday_11187.csv.gz  in=198,513,328 out=0 elapsed=46.0s

  [2307/21087] intraday_11188.csv.gz  in=198,523,867 out=0 elapsed=46.1s

  [2308/21087] intraday_11189.csv.gz  in=198,534,704 out=0 elapsed=46.1s

  [2309/21087] intraday_1119.csv.gz  in=198,548,301 out=0 elapsed=46.1s

  [2310/21087] intraday_11190.csv.gz  in=198,560,060 out=0 elapsed=46.1s

  [2311/21087] intraday_11191.csv.gz  in=198,570,222 out=0 elapsed=46.1s

  [2312/21087] intraday_11192.csv.gz  in=198,584,442 out=0 elapsed=46.1s

  [2313/21087] intraday_11193.csv.gz  in=198,599,451 out=0 elapsed=46.1s

  [2314/21087] intraday_11194.csv.gz  in=198,613,323 out=0 elapsed=46.1s

  [2315/21087] intraday_11195.csv.gz  in=198,627,191 out=0 elapsed=46.1s

  [2316/21087] intraday_11196.csv.gz  in=198,640,264 out=0 elapsed=46.1s

  [2317/21087] intraday_11197.csv.gz  in=198,651,541 out=0 elapsed=46.2s

  [2318/21087] intraday_11198.csv.gz  in=198,663,583 out=0 elapsed=46.2s

  [2319/21087] intraday_11199.csv.gz  in=198,673,673 out=0 elapsed=46.2s

  [2320/21087] intraday_1120.csv.gz  in=198,687,522 out=0 elapsed=46.2s

  [2321/21087] intraday_11201.csv.gz  in=198,694,594 out=0 elapsed=46.2s

  [2322/21087] intraday_11200.csv.gz  in=198,707,115 out=0 elapsed=46.2s

  [2323/21087] intraday_11202.csv.gz  in=198,713,776 out=0 elapsed=46.2s

  [2324/21087] intraday_11203.csv.gz  in=198,726,203 out=0 elapsed=46.2s

  [2325/21087] intraday_11204.csv.gz  in=198,727,577 out=0 elapsed=46.2s

  [2326/21087] intraday_11205.csv.gz  in=198,736,239 out=0 elapsed=46.2s

  [2327/21087] intraday_11206.csv.gz  in=198,741,356 out=0 elapsed=46.2s

  [2328/21087] intraday_11207.csv.gz  in=198,750,132 out=0 elapsed=46.2s

  [2329/21087] intraday_11209.csv.gz  in=198,760,555 out=0 elapsed=46.2s

  [2330/21087] intraday_11208.csv.gz  in=198,774,246 out=0 elapsed=46.3s

  [2331/21087] intraday_1121.csv.gz  in=198,789,454 out=0 elapsed=46.3s

  [2332/21087] intraday_11210.csv.gz  in=198,804,473 out=0 elapsed=46.3s

  [2333/21087] intraday_11211.csv.gz  in=198,814,040 out=0 elapsed=46.3s

  [2334/21087] intraday_11213.csv.gz  in=198,826,385 out=0 elapsed=46.3s

  [2335/21087] intraday_11212.csv.gz  in=198,837,255 out=0 elapsed=46.3s

  [2336/21087] intraday_11214.csv.gz  in=198,850,845 out=0 elapsed=46.3s

  [2337/21087] intraday_11215.csv.gz  in=198,859,905 out=0 elapsed=46.3s

  [2338/21087] intraday_11216.csv.gz  in=198,871,773 out=0 elapsed=46.3s

  [2339/21087] intraday_11218.csv.gz  in=198,884,099 out=0 elapsed=46.3s

  [2340/21087] intraday_11217.csv.gz  in=198,896,775 out=0 elapsed=46.3s

  [2341/21087] intraday_11219.csv.gz  in=198,906,602 out=0 elapsed=46.3s

  [2342/21087] intraday_1122.csv.gz  in=198,922,545 out=0 elapsed=46.4s

  [2343/21087] intraday_11221.csv.gz  in=198,934,389 out=0 elapsed=46.4s

  [2344/21087] intraday_11220.csv.gz  in=198,950,211 out=0 elapsed=46.4s

  [2345/21087] intraday_11223.csv.gz  in=198,961,181 out=0 elapsed=46.4s

  [2346/21087] intraday_11222.csv.gz  in=198,970,754 out=0 elapsed=46.4s

  [2347/21087] intraday_11224.csv.gz  in=198,981,854 out=0 elapsed=46.4s

  [2348/21087] intraday_11225.csv.gz  in=198,994,572 out=0 elapsed=46.4s

  [2349/21087] intraday_11226.csv.gz  in=199,006,037 out=0 elapsed=46.4s

  [2350/21087] intraday_11227.csv.gz  in=199,015,713 out=0 elapsed=46.4s

  [2351/21087] intraday_11228.csv.gz  in=199,031,597 out=0 elapsed=46.4s

  [2352/21087] intraday_11229.csv.gz  in=199,043,613 out=0 elapsed=46.4s

  [2353/21087] intraday_1123.csv.gz  in=199,056,901 out=0 elapsed=46.5s

  [2354/21087] intraday_11230.csv.gz  in=199,069,443 out=0 elapsed=46.5s

  [2355/21087] intraday_11231.csv.gz  in=199,081,360 out=0 elapsed=46.5s

  [2356/21087] intraday_11232.csv.gz  in=199,093,684 out=0 elapsed=46.5s

  [2357/21087] intraday_11233.csv.gz  in=199,105,785 out=0 elapsed=46.5s

  [2358/21087] intraday_11234.csv.gz  in=199,116,541 out=0 elapsed=46.5s

  [2359/21087] intraday_11235.csv.gz  in=199,127,031 out=0 elapsed=46.5s

  [2360/21087] intraday_11236.csv.gz  in=199,137,036 out=0 elapsed=46.5s

  [2361/21087] intraday_11237.csv.gz  in=199,149,735 out=0 elapsed=46.5s

  [2362/21087] intraday_11239.csv.gz  in=199,162,279 out=0 elapsed=46.5s

  [2363/21087] intraday_11238.csv.gz  in=199,176,970 out=0 elapsed=46.5s

  [2364/21087] intraday_1124.csv.gz  in=199,189,308 out=0 elapsed=46.6s

  [2365/21087] intraday_11241.csv.gz  in=199,199,442 out=0 elapsed=46.6s

  [2366/21087] intraday_11240.csv.gz  in=199,208,900 out=0 elapsed=46.6s

  [2367/21087] intraday_11242.csv.gz  in=199,220,902 out=0 elapsed=46.6s

  [2368/21087] intraday_11243.csv.gz  in=199,233,102 out=0 elapsed=46.6s

  [2369/21087] intraday_11244.csv.gz  in=199,243,201 out=0 elapsed=46.6s

  [2370/21087] intraday_11245.csv.gz  in=199,254,645 out=0 elapsed=46.6s

  [2371/21087] intraday_11247.csv.gz  in=199,264,540 out=0 elapsed=46.6s

  [2372/21087] intraday_11246.csv.gz  in=199,275,662 out=0 elapsed=46.6s

  [2373/21087] intraday_11248.csv.gz  in=199,284,860 out=0 elapsed=46.6s

  [2374/21087] intraday_11249.csv.gz  in=199,295,829 out=0 elapsed=46.6s

  [2375/21087] intraday_1125.csv.gz  in=199,308,498 out=0 elapsed=46.7s

  [2376/21087] intraday_11251.csv.gz  in=199,319,144 out=0 elapsed=46.7s

  [2377/21087] intraday_11250.csv.gz  in=199,331,588 out=0 elapsed=46.7s

  [2378/21087] intraday_11252.csv.gz  in=199,345,169 out=0 elapsed=46.7s

  [2379/21087] intraday_11253.csv.gz  in=199,356,958 out=0 elapsed=46.7s

  [2380/21087] intraday_11254.csv.gz  in=199,366,992 out=0 elapsed=46.7s

  [2381/21087] intraday_11255.csv.gz  in=199,377,720 out=0 elapsed=46.7s

  [2382/21087] intraday_11256.csv.gz  in=199,389,336 out=0 elapsed=46.7s

  [2383/21087] intraday_11257.csv.gz  in=199,398,383 out=0 elapsed=46.7s

  [2384/21087] intraday_11258.csv.gz  in=199,413,721 out=0 elapsed=46.7s

  [2385/21087] intraday_11259.csv.gz  in=199,424,364 out=0 elapsed=46.7s

  [2386/21087] intraday_1126.csv.gz  in=199,438,548 out=0 elapsed=46.7s

  [2387/21087] intraday_11260.csv.gz  in=199,449,933 out=0 elapsed=46.7s

  [2388/21087] intraday_11261.csv.gz  in=199,461,716 out=0 elapsed=46.8s

  [2389/21087] intraday_11262.csv.gz  in=199,472,559 out=0 elapsed=46.8s

  [2390/21087] intraday_11263.csv.gz  in=199,486,351 out=0 elapsed=46.8s

  [2391/21087] intraday_11264.csv.gz  in=199,499,031 out=0 elapsed=46.8s

  [2392/21087] intraday_11265.csv.gz  in=199,510,940 out=0 elapsed=46.8s

  [2393/21087] intraday_11266.csv.gz  in=199,520,596 out=0 elapsed=46.8s

  [2394/21087] intraday_11267.csv.gz  in=199,532,727 out=0 elapsed=46.8s

  [2395/21087] intraday_11268.csv.gz  in=199,544,820 out=0 elapsed=46.8s

  [2396/21087] intraday_11269.csv.gz  in=199,554,879 out=0 elapsed=46.8s

  [2397/21087] intraday_1127.csv.gz  in=199,566,819 out=0 elapsed=46.8s

  [2398/21087] intraday_11270.csv.gz  in=199,584,714 out=0 elapsed=46.8s

  [2399/21087] intraday_11271.csv.gz  in=199,595,330 out=0 elapsed=46.9s

  [2400/21087] intraday_11272.csv.gz  in=199,604,945 out=0 elapsed=46.9s

  [2401/21087] intraday_11273.csv.gz  in=199,619,211 out=0 elapsed=46.9s

  [2402/21087] intraday_11275.csv.gz  in=199,629,534 out=0 elapsed=46.9s

  [2403/21087] intraday_11274.csv.gz  in=199,643,474 out=0 elapsed=46.9s

  [2404/21087] intraday_11277.csv.gz  in=199,654,926 out=0 elapsed=46.9s

  [2405/21087] intraday_11276.csv.gz  in=199,668,218 out=0 elapsed=46.9s

  [2406/21087] intraday_11278.csv.gz  in=199,679,237 out=0 elapsed=46.9s

  [2407/21087] intraday_11279.csv.gz  in=199,691,856 out=0 elapsed=46.9s

  [2408/21087] intraday_11280.csv.gz  in=199,703,662 out=0 elapsed=46.9s

  [2409/21087] intraday_1128.csv.gz  in=199,722,042 out=0 elapsed=46.9s

  [2410/21087] intraday_11281.csv.gz  in=199,736,579 out=0 elapsed=46.9s

  [2411/21087] intraday_11282.csv.gz  in=199,750,169 out=0 elapsed=47.0s

  [2412/21087] intraday_11283.csv.gz  in=199,761,684 out=0 elapsed=47.0s

  [2413/21087] intraday_11284.csv.gz  in=199,771,606 out=0 elapsed=47.0s

  [2414/21087] intraday_11285.csv.gz  in=199,781,377 out=0 elapsed=47.0s

  [2415/21087] intraday_11287.csv.gz  in=199,791,247 out=0 elapsed=47.0s

  [2416/21087] intraday_11286.csv.gz  in=199,804,435 out=0 elapsed=47.0s

  [2417/21087] intraday_11288.csv.gz  in=199,815,214 out=0 elapsed=47.0s

  [2418/21087] intraday_11289.csv.gz  in=199,823,570 out=0 elapsed=47.0s

  [2419/21087] intraday_11290.csv.gz  in=199,832,799 out=0 elapsed=47.0s

  [2420/21087] intraday_1129.csv.gz  in=199,846,110 out=0 elapsed=47.0s

  [2421/21087] intraday_11291.csv.gz  in=199,856,929 out=0 elapsed=47.0s

  [2422/21087] intraday_11292.csv.gz  in=199,870,993 out=0 elapsed=47.0s

  [2423/21087] intraday_11294.csv.gz  in=199,883,077 out=0 elapsed=47.1s

  [2424/21087] intraday_11293.csv.gz  in=199,899,891 out=0 elapsed=47.1s

  [2425/21087] intraday_11295.csv.gz  in=199,910,077 out=0 elapsed=47.1s

  [2426/21087] intraday_11296.csv.gz  in=199,921,257 out=0 elapsed=47.1s

  [2427/21087] intraday_11297.csv.gz  in=199,934,169 out=0 elapsed=47.1s

  [2428/21087] intraday_11298.csv.gz  in=199,945,267 out=0 elapsed=47.1s

  [2429/21087] intraday_11299.csv.gz  in=199,958,397 out=0 elapsed=47.1s

  [2430/21087] intraday_1130.csv.gz  in=199,970,659 out=0 elapsed=47.1s

  [2431/21087] intraday_11300.csv.gz  in=199,980,618 out=0 elapsed=47.1s

  [2432/21087] intraday_11301.csv.gz  in=199,996,584 out=0 elapsed=47.1s

  [2433/21087] intraday_11302.csv.gz  in=200,007,425 out=0 elapsed=47.1s

  [2434/21087] intraday_11303.csv.gz  in=200,018,534 out=0 elapsed=47.1s

  [2435/21087] intraday_11304.csv.gz  in=200,032,318 out=0 elapsed=47.1s

  [2436/21087] intraday_11305.csv.gz  in=200,043,722 out=0 elapsed=47.2s

  [2437/21087] intraday_11306.csv.gz  in=200,055,491 out=0 elapsed=47.2s

  [2438/21087] intraday_11307.csv.gz  in=200,065,601 out=0 elapsed=47.2s

  [2439/21087] intraday_11308.csv.gz  in=200,077,649 out=0 elapsed=47.2s

  [2440/21087] intraday_11309.csv.gz  in=200,087,360 out=0 elapsed=47.2s

  [2441/21087] intraday_1131.csv.gz  in=200,099,058 out=0 elapsed=47.2s

  [2442/21087] intraday_11310.csv.gz  in=200,111,080 out=0 elapsed=47.2s

  [2443/21087] intraday_11311.csv.gz  in=200,122,395 out=0 elapsed=47.2s

  [2444/21087] intraday_11312.csv.gz  in=200,135,374 out=0 elapsed=47.2s

  [2445/21087] intraday_11313.csv.gz  in=200,146,772 out=0 elapsed=47.2s

  [2446/21087] intraday_11314.csv.gz  in=200,158,374 out=0 elapsed=47.2s

  [2447/21087] intraday_11315.csv.gz  in=200,171,150 out=0 elapsed=47.2s

  [2448/21087] intraday_11316.csv.gz  in=200,183,078 out=0 elapsed=47.3s

  [2449/21087] intraday_11317.csv.gz  in=200,194,226 out=0 elapsed=47.3s

  [2450/21087] intraday_11318.csv.gz  in=200,206,663 out=0 elapsed=47.3s

  [2451/21087] intraday_11319.csv.gz  in=200,219,750 out=0 elapsed=47.3s

  [2452/21087] intraday_11320.csv.gz  in=200,231,040 out=0 elapsed=47.3s

  [2453/21087] intraday_1132.csv.gz  in=200,244,757 out=0 elapsed=47.3s

  [2454/21087] intraday_11321.csv.gz  in=200,255,214 out=0 elapsed=47.3s

  [2455/21087] intraday_11322.csv.gz  in=200,267,330 out=0 elapsed=47.3s

  [2456/21087] intraday_11323.csv.gz  in=200,284,260 out=0 elapsed=47.3s

  [2457/21087] intraday_11324.csv.gz  in=200,299,438 out=0 elapsed=47.3s

  [2458/21087] intraday_11325.csv.gz  in=200,313,046 out=0 elapsed=47.3s

  [2459/21087] intraday_11326.csv.gz  in=200,329,736 out=0 elapsed=47.3s

  [2460/21087] intraday_11327.csv.gz  in=200,341,728 out=0 elapsed=47.3s

  [2461/21087] intraday_11329.csv.gz  in=200,353,145 out=0 elapsed=47.4s

  [2462/21087] intraday_11328.csv.gz  in=200,368,396 out=0 elapsed=47.4s

  [2463/21087] intraday_1133.csv.gz  in=200,382,000 out=0 elapsed=47.4s

  [2464/21087] intraday_11330.csv.gz  in=200,393,223 out=0 elapsed=47.4s

  [2465/21087] intraday_11332.csv.gz  in=200,405,977 out=0 elapsed=47.4s

  [2466/21087] intraday_11331.csv.gz  in=200,417,524 out=0 elapsed=47.4s

  [2467/21087] intraday_11333.csv.gz  in=200,428,181 out=0 elapsed=47.4s

  [2468/21087] intraday_11334.csv.gz  in=200,440,055 out=0 elapsed=47.4s

  [2469/21087] intraday_11335.csv.gz  in=200,451,370 out=0 elapsed=47.4s

  [2470/21087] intraday_11336.csv.gz  in=200,465,818 out=0 elapsed=47.4s

  [2471/21087] intraday_11337.csv.gz  in=200,478,450 out=0 elapsed=47.4s

  [2472/21087] intraday_11338.csv.gz  in=200,489,682 out=0 elapsed=47.4s

  [2473/21087] intraday_11339.csv.gz  in=200,500,490 out=0 elapsed=47.4s

  [2474/21087] intraday_11340.csv.gz  in=200,512,357 out=0 elapsed=47.5s

  [2475/21087] intraday_11341.csv.gz  in=200,524,798 out=0 elapsed=47.5s

  [2476/21087] intraday_11342.csv.gz  in=200,537,374 out=0 elapsed=47.5s

  [2477/21087] intraday_1134.csv.gz  in=200,562,875 out=0 elapsed=47.5s

  [2478/21087] intraday_11343.csv.gz  in=200,577,383 out=0 elapsed=47.5s

  [2479/21087] intraday_11344.csv.gz  in=200,596,659 out=0 elapsed=47.5s

  [2480/21087] intraday_11345.csv.gz  in=200,610,516 out=0 elapsed=47.5s

  [2481/21087] intraday_11346.csv.gz  in=200,625,843 out=0 elapsed=47.5s

  [2482/21087] intraday_11347.csv.gz  in=200,637,956 out=0 elapsed=47.5s

  [2483/21087] intraday_11348.csv.gz  in=200,649,124 out=0 elapsed=47.5s

  [2484/21087] intraday_11349.csv.gz  in=200,662,455 out=0 elapsed=47.5s

  [2485/21087] intraday_11350.csv.gz  in=200,673,947 out=0 elapsed=47.5s

  [2486/21087] intraday_1135.csv.gz  in=200,689,991 out=0 elapsed=47.5s

  [2487/21087] intraday_11351.csv.gz  in=200,699,837 out=0 elapsed=47.6s

  [2488/21087] intraday_11352.csv.gz  in=200,706,649 out=0 elapsed=47.6s

  [2489/21087] intraday_11354.csv.gz  in=200,713,852 out=0 elapsed=47.6s

  [2490/21087] intraday_11353.csv.gz  in=200,724,974 out=0 elapsed=47.6s

  [2491/21087] intraday_11355.csv.gz  in=200,738,706 out=0 elapsed=47.6s

  [2492/21087] intraday_11356.csv.gz  in=200,750,437 out=0 elapsed=47.6s

  [2493/21087] intraday_11357.csv.gz  in=200,764,208 out=0 elapsed=47.6s

  [2494/21087] intraday_11358.csv.gz  in=200,773,508 out=0 elapsed=47.6s

  [2495/21087] intraday_11359.csv.gz  in=200,784,371 out=0 elapsed=47.6s

  [2496/21087] intraday_1136.csv.gz  in=200,795,824 out=0 elapsed=47.6s

  [2497/21087] intraday_11360.csv.gz  in=200,808,903 out=0 elapsed=47.6s

  [2498/21087] intraday_11361.csv.gz  in=200,822,463 out=0 elapsed=47.6s

  [2499/21087] intraday_11363.csv.gz  in=200,833,621 out=0 elapsed=47.6s

  [2500/21087] intraday_11362.csv.gz  in=200,844,342 out=0 elapsed=47.7s

  [2501/21087] intraday_11364.csv.gz  in=200,857,222 out=0 elapsed=47.7s

  [2502/21087] intraday_11365.csv.gz  in=200,869,450 out=0 elapsed=47.7s

  [2503/21087] intraday_11366.csv.gz  in=200,879,663 out=0 elapsed=47.7s

  [2504/21087] intraday_11367.csv.gz  in=200,892,374 out=0 elapsed=47.7s

  [2505/21087] intraday_11368.csv.gz  in=200,905,034 out=0 elapsed=47.7s

  [2506/21087] intraday_11369.csv.gz  in=200,913,914 out=0 elapsed=47.7s

  [2507/21087] intraday_1137.csv.gz  in=200,927,677 out=0 elapsed=47.7s

  [2508/21087] intraday_11370.csv.gz  in=200,937,178 out=0 elapsed=47.7s

  [2509/21087] intraday_11371.csv.gz  in=200,949,516 out=0 elapsed=47.7s

  [2510/21087] intraday_11372.csv.gz  in=200,962,489 out=0 elapsed=47.7s

  [2511/21087] intraday_11373.csv.gz  in=200,973,129 out=0 elapsed=47.7s

  [2512/21087] intraday_11375.csv.gz  in=200,983,185 out=0 elapsed=47.8s

  [2513/21087] intraday_11376.csv.gz  in=200,995,748 out=0 elapsed=47.8s

  [2514/21087] intraday_11377.csv.gz  in=201,012,805 out=0 elapsed=47.8s

  [2515/21087] intraday_11374.csv.gz  in=201,035,568 out=0 elapsed=47.8s

  [2516/21087] intraday_11378.csv.gz  in=201,046,674 out=0 elapsed=47.8s

  [2517/21087] intraday_11379.csv.gz  in=201,059,780 out=0 elapsed=47.8s

  [2518/21087] intraday_1138.csv.gz  in=201,071,228 out=0 elapsed=47.8s

  [2519/21087] intraday_11380.csv.gz  in=201,083,055 out=0 elapsed=47.8s

  [2520/21087] intraday_11381.csv.gz  in=201,095,329 out=0 elapsed=47.8s

  [2521/21087] intraday_11382.csv.gz  in=201,106,002 out=0 elapsed=47.8s

  [2522/21087] intraday_11383.csv.gz  in=201,115,871 out=0 elapsed=47.8s

  [2523/21087] intraday_11385.csv.gz  in=201,130,835 out=0 elapsed=47.8s

  [2524/21087] intraday_11384.csv.gz  in=201,142,980 out=0 elapsed=47.9s

  [2525/21087] intraday_11386.csv.gz  in=201,156,212 out=0 elapsed=47.9s

  [2526/21087] intraday_11388.csv.gz  in=201,166,414 out=0 elapsed=47.9s

  [2527/21087] intraday_11387.csv.gz  in=201,176,107 out=0 elapsed=47.9s

  [2528/21087] intraday_11389.csv.gz  in=201,188,750 out=0 elapsed=47.9s

  [2529/21087] intraday_1139.csv.gz  in=201,200,951 out=0 elapsed=47.9s

  [2530/21087] intraday_11390.csv.gz  in=201,212,389 out=0 elapsed=47.9s

  [2531/21087] intraday_11391.csv.gz  in=201,223,291 out=0 elapsed=47.9s

  [2532/21087] intraday_11392.csv.gz  in=201,234,799 out=0 elapsed=47.9s

  [2533/21087] intraday_11393.csv.gz  in=201,248,362 out=0 elapsed=47.9s

  [2534/21087] intraday_11394.csv.gz  in=201,258,164 out=0 elapsed=47.9s

  [2535/21087] intraday_11396.csv.gz  in=201,268,839 out=0 elapsed=47.9s

  [2536/21087] intraday_11395.csv.gz  in=201,280,543 out=0 elapsed=47.9s

  [2537/21087] intraday_11397.csv.gz  in=201,293,275 out=0 elapsed=48.0s

  [2538/21087] intraday_11398.csv.gz  in=201,303,981 out=0 elapsed=48.0s

  [2539/21087] intraday_1140.csv.gz  in=201,317,138 out=0 elapsed=48.0s

  [2540/21087] intraday_11399.csv.gz  in=201,330,368 out=0 elapsed=48.0s

  [2541/21087] intraday_11400.csv.gz  in=201,342,686 out=0 elapsed=48.0s

  [2542/21087] intraday_11401.csv.gz  in=201,353,878 out=0 elapsed=48.0s

  [2543/21087] intraday_11402.csv.gz  in=201,364,612 out=0 elapsed=48.0s

  [2544/21087] intraday_11404.csv.gz  in=201,373,580 out=0 elapsed=48.0s

  [2545/21087] intraday_11403.csv.gz  in=201,385,438 out=0 elapsed=48.0s

  [2546/21087] intraday_11405.csv.gz  in=201,397,905 out=0 elapsed=48.0s

  [2547/21087] intraday_11406.csv.gz  in=201,408,321 out=0 elapsed=48.0s

  [2548/21087] intraday_11407.csv.gz  in=201,418,692 out=0 elapsed=48.0s

  [2549/21087] intraday_11409.csv.gz  in=201,429,552 out=0 elapsed=48.1s

  [2550/21087] intraday_1141.csv.gz  in=201,440,349 out=0 elapsed=48.1s

  [2551/21087] intraday_11408.csv.gz  in=201,452,998 out=0 elapsed=48.1s

  [2552/21087] intraday_11410.csv.gz  in=201,466,771 out=0 elapsed=48.1s

  [2553/21087] intraday_11411.csv.gz  in=201,479,295 out=0 elapsed=48.1s

  [2554/21087] intraday_11413.csv.gz  in=201,489,672 out=0 elapsed=48.1s

  [2555/21087] intraday_11412.csv.gz  in=201,502,593 out=0 elapsed=48.1s

  [2556/21087] intraday_11414.csv.gz  in=201,514,733 out=0 elapsed=48.1s

  [2557/21087] intraday_11415.csv.gz  in=201,525,578 out=0 elapsed=48.1s

  [2558/21087] intraday_11416.csv.gz  in=201,536,559 out=0 elapsed=48.1s

  [2559/21087] intraday_11417.csv.gz  in=201,548,569 out=0 elapsed=48.1s

  [2560/21087] intraday_11418.csv.gz  in=201,559,451 out=0 elapsed=48.1s

  [2561/21087] intraday_11419.csv.gz  in=201,569,016 out=0 elapsed=48.1s

  [2562/21087] intraday_1142.csv.gz  in=201,580,681 out=0 elapsed=48.2s

  [2563/21087] intraday_11420.csv.gz  in=201,593,507 out=0 elapsed=48.2s

  [2564/21087] intraday_11421.csv.gz  in=201,607,930 out=0 elapsed=48.2s

  [2565/21087] intraday_11422.csv.gz  in=201,620,170 out=0 elapsed=48.2s

  [2566/21087] intraday_11423.csv.gz  in=201,633,382 out=0 elapsed=48.2s

  [2567/21087] intraday_11424.csv.gz  in=201,646,136 out=0 elapsed=48.2s

  [2568/21087] intraday_11425.csv.gz  in=201,659,730 out=0 elapsed=48.2s

  [2569/21087] intraday_11426.csv.gz  in=201,671,472 out=0 elapsed=48.2s

  [2570/21087] intraday_11427.csv.gz  in=201,683,362 out=0 elapsed=48.2s

  [2571/21087] intraday_11428.csv.gz  in=201,696,555 out=0 elapsed=48.2s

  [2572/21087] intraday_11429.csv.gz  in=201,709,733 out=0 elapsed=48.2s

  [2573/21087] intraday_1143.csv.gz  in=201,725,093 out=0 elapsed=48.3s

  [2574/21087] intraday_11430.csv.gz  in=201,737,241 out=0 elapsed=48.3s

  [2575/21087] intraday_11431.csv.gz  in=201,748,117 out=0 elapsed=48.3s

  [2576/21087] intraday_11432.csv.gz  in=201,758,790 out=0 elapsed=48.3s

  [2577/21087] intraday_11433.csv.gz  in=201,772,399 out=0 elapsed=48.3s

  [2578/21087] intraday_11434.csv.gz  in=201,783,029 out=0 elapsed=48.3s

  [2579/21087] intraday_11435.csv.gz  in=201,793,928 out=0 elapsed=48.3s

  [2580/21087] intraday_11436.csv.gz  in=201,802,710 out=0 elapsed=48.3s

  [2581/21087] intraday_11437.csv.gz  in=201,812,048 out=0 elapsed=48.3s

  [2582/21087] intraday_11438.csv.gz  in=201,822,597 out=0 elapsed=48.3s

  [2583/21087] intraday_11439.csv.gz  in=201,835,523 out=0 elapsed=48.3s

  [2584/21087] intraday_1144.csv.gz  in=201,848,735 out=0 elapsed=48.3s

  [2585/21087] intraday_11440.csv.gz  in=201,869,665 out=0 elapsed=48.3s

  [2586/21087] intraday_11441.csv.gz  in=201,881,661 out=0 elapsed=48.3s

  [2587/21087] intraday_11442.csv.gz  in=201,892,430 out=0 elapsed=48.4s

  [2588/21087] intraday_11443.csv.gz  in=201,903,262 out=0 elapsed=48.4s

  [2589/21087] intraday_11444.csv.gz  in=201,916,965 out=0 elapsed=48.4s

  [2590/21087] intraday_11445.csv.gz  in=201,927,552 out=0 elapsed=48.4s

  [2591/21087] intraday_11447.csv.gz  in=201,936,917 out=0 elapsed=48.4s

  [2592/21087] intraday_11446.csv.gz  in=201,951,744 out=0 elapsed=48.4s

  [2593/21087] intraday_11448.csv.gz  in=201,965,193 out=0 elapsed=48.4s

  [2594/21087] intraday_1145.csv.gz  in=201,975,982 out=0 elapsed=48.4s

  [2595/21087] intraday_11449.csv.gz  in=201,988,099 out=0 elapsed=48.4s

  [2596/21087] intraday_11450.csv.gz  in=202,001,120 out=0 elapsed=48.4s

  [2597/21087] intraday_11451.csv.gz  in=202,014,733 out=0 elapsed=48.4s

  [2598/21087] intraday_11452.csv.gz  in=202,025,829 out=0 elapsed=48.4s

  [2599/21087] intraday_11453.csv.gz  in=202,041,826 out=0 elapsed=48.5s

  [2600/21087] intraday_11454.csv.gz  in=202,053,094 out=0 elapsed=48.5s

  [2601/21087] intraday_11455.csv.gz  in=202,063,933 out=0 elapsed=48.5s

  [2602/21087] intraday_11456.csv.gz  in=202,075,645 out=0 elapsed=48.5s

  [2603/21087] intraday_11457.csv.gz  in=202,085,999 out=0 elapsed=48.5s

  [2604/21087] intraday_11458.csv.gz  in=202,097,510 out=0 elapsed=48.5s

  [2605/21087] intraday_11459.csv.gz  in=202,110,611 out=0 elapsed=48.5s

  [2606/21087] intraday_1146.csv.gz  in=202,124,813 out=0 elapsed=48.5s

  [2607/21087] intraday_11461.csv.gz  in=202,136,048 out=0 elapsed=48.5s

  [2608/21087] intraday_11460.csv.gz  in=202,147,896 out=0 elapsed=48.5s

  [2609/21087] intraday_11462.csv.gz  in=202,160,321 out=0 elapsed=48.5s

  [2610/21087] intraday_11463.csv.gz  in=202,172,996 out=0 elapsed=48.5s

  [2611/21087] intraday_11464.csv.gz  in=202,184,814 out=0 elapsed=48.5s

  [2612/21087] intraday_11465.csv.gz  in=202,197,551 out=0 elapsed=48.6s

  [2613/21087] intraday_11467.csv.gz  in=202,210,254 out=0 elapsed=48.6s

  [2614/21087] intraday_11466.csv.gz  in=202,222,801 out=0 elapsed=48.6s

  [2615/21087] intraday_11468.csv.gz  in=202,232,160 out=0 elapsed=48.6s

  [2616/21087] intraday_11469.csv.gz  in=202,245,997 out=0 elapsed=48.6s

  [2617/21087] intraday_1147.csv.gz  in=202,257,708 out=0 elapsed=48.6s

  [2618/21087] intraday_11470.csv.gz  in=202,274,764 out=0 elapsed=48.6s

  [2619/21087] intraday_11471.csv.gz  in=202,288,384 out=0 elapsed=48.6s

  [2620/21087] intraday_11472.csv.gz  in=202,302,572 out=0 elapsed=48.6s

  [2621/21087] intraday_11473.csv.gz  in=202,317,686 out=0 elapsed=48.6s

  [2622/21087] intraday_11474.csv.gz  in=202,331,748 out=0 elapsed=48.6s

  [2623/21087] intraday_11475.csv.gz  in=202,346,810 out=0 elapsed=48.6s

  [2624/21087] intraday_11476.csv.gz  in=202,359,970 out=0 elapsed=48.7s

  [2625/21087] intraday_11477.csv.gz  in=202,371,554 out=0 elapsed=48.7s

  [2626/21087] intraday_11478.csv.gz  in=202,384,497 out=0 elapsed=48.7s

  [2627/21087] intraday_11479.csv.gz  in=202,396,068 out=0 elapsed=48.7s

  [2628/21087] intraday_1148.csv.gz  in=202,407,336 out=0 elapsed=48.7s

  [2629/21087] intraday_11480.csv.gz  in=202,418,493 out=0 elapsed=48.7s

  [2630/21087] intraday_11481.csv.gz  in=202,430,518 out=0 elapsed=48.7s

  [2631/21087] intraday_11482.csv.gz  in=202,443,347 out=0 elapsed=48.7s

  [2632/21087] intraday_11483.csv.gz  in=202,459,176 out=0 elapsed=48.7s

  [2633/21087] intraday_11484.csv.gz  in=202,471,985 out=0 elapsed=48.7s

  [2634/21087] intraday_11485.csv.gz  in=202,483,241 out=0 elapsed=48.7s

  [2635/21087] intraday_11486.csv.gz  in=202,493,501 out=0 elapsed=48.7s

  [2636/21087] intraday_11487.csv.gz  in=202,506,357 out=0 elapsed=48.7s

  [2637/21087] intraday_11488.csv.gz  in=202,517,229 out=0 elapsed=48.7s

  [2638/21087] intraday_11489.csv.gz  in=202,529,049 out=0 elapsed=48.8s

  [2639/21087] intraday_1149.csv.gz  in=202,543,232 out=0 elapsed=48.8s

  [2640/21087] intraday_11490.csv.gz  in=202,558,484 out=0 elapsed=48.8s

  [2641/21087] intraday_11491.csv.gz  in=202,571,507 out=0 elapsed=48.8s

  [2642/21087] intraday_11493.csv.gz  in=202,586,266 out=0 elapsed=48.8s

  [2643/21087] intraday_11492.csv.gz  in=202,599,698 out=0 elapsed=48.8s

  [2644/21087] intraday_11494.csv.gz  in=202,611,039 out=0 elapsed=48.8s

  [2645/21087] intraday_11495.csv.gz  in=202,624,106 out=0 elapsed=48.8s

  [2646/21087] intraday_11496.csv.gz  in=202,634,377 out=0 elapsed=48.8s

  [2647/21087] intraday_11497.csv.gz  in=202,647,332 out=0 elapsed=48.8s

  [2648/21087] intraday_11498.csv.gz  in=202,654,747 out=0 elapsed=48.8s

  [2649/21087] intraday_11499.csv.gz  in=202,661,856 out=0 elapsed=48.8s

  [2650/21087] intraday_11501.csv.gz  in=202,664,890 out=0 elapsed=48.8s

  [2651/21087] intraday_1150.csv.gz  in=202,676,521 out=0 elapsed=48.8s

  [2652/21087] intraday_11500.csv.gz  in=202,688,575 out=0 elapsed=48.9s

  [2653/21087] intraday_11502.csv.gz  in=202,695,424 out=0 elapsed=48.9s

  [2654/21087] intraday_11503.csv.gz  in=202,708,396 out=12,972 elapsed=48.9s

  [2655/21087] intraday_11504.csv.gz  in=202,720,379 out=24,954 elapsed=48.9s

  [2656/21087] intraday_11505.csv.gz  in=202,733,039 out=37,614 elapsed=48.9s

  [2657/21087] intraday_11506.csv.gz  in=202,741,950 out=46,525 elapsed=48.9s

  [2658/21087] intraday_11507.csv.gz  in=202,752,993 out=57,568 elapsed=48.9s

  [2659/21087] intraday_1151.csv.gz  in=202,766,021 out=57,568 elapsed=48.9s

  [2660/21087] intraday_11508.csv.gz  in=202,778,299 out=69,846 elapsed=48.9s

  [2661/21087] intraday_11509.csv.gz  in=202,792,273 out=83,820 elapsed=49.0s

  [2662/21087] intraday_11511.csv.gz  in=202,802,947 out=94,494 elapsed=49.0s

  [2663/21087] intraday_11510.csv.gz  in=202,814,077 out=105,624 elapsed=49.0s

  [2664/21087] intraday_11512.csv.gz  in=202,826,622 out=118,073 elapsed=49.0s

  [2665/21087] intraday_11513.csv.gz  in=202,837,688 out=129,139 elapsed=49.0s

  [2666/21087] intraday_11514.csv.gz  in=202,849,136 out=140,587 elapsed=49.0s

  [2667/21087] intraday_11515.csv.gz  in=202,860,917 out=152,368 elapsed=49.0s

  [2668/21087] intraday_11516.csv.gz  in=202,872,222 out=163,673 elapsed=49.0s

  [2669/21087] intraday_11517.csv.gz  in=202,881,177 out=172,628 elapsed=49.0s

  [2670/21087] intraday_11518.csv.gz  in=202,890,920 out=182,371 elapsed=49.0s

  [2671/21087] intraday_11519.csv.gz  in=202,902,934 out=194,369 elapsed=49.1s

  [2672/21087] intraday_1152.csv.gz  in=202,929,621 out=194,369 elapsed=49.1s

  [2673/21087] intraday_11520.csv.gz  in=202,941,233 out=205,981 elapsed=49.1s

  [2674/21087] intraday_11521.csv.gz  in=202,952,580 out=217,328 elapsed=49.1s

  [2675/21087] intraday_11522.csv.gz  in=202,962,377 out=227,075 elapsed=49.1s

  [2676/21087] intraday_11524.csv.gz  in=202,972,933 out=237,631 elapsed=49.1s

  [2677/21087] intraday_11525.csv.gz  in=202,984,792 out=249,490 elapsed=49.1s

  [2678/21087] intraday_11523.csv.gz  in=202,996,104 out=260,802 elapsed=49.1s

  [2679/21087] intraday_11526.csv.gz  in=203,006,609 out=271,307 elapsed=49.2s

  [2680/21087] intraday_11527.csv.gz  in=203,018,828 out=283,526 elapsed=49.2s

  [2681/21087] intraday_11528.csv.gz  in=203,029,584 out=294,282 elapsed=49.2s

  [2682/21087] intraday_11529.csv.gz  in=203,041,518 out=306,216 elapsed=49.2s

  [2683/21087] intraday_1153.csv.gz  in=203,054,126 out=306,216 elapsed=49.2s

  [2684/21087] intraday_11530.csv.gz  in=203,065,316 out=317,406 elapsed=49.2s

  [2685/21087] intraday_11531.csv.gz  in=203,074,600 out=326,690 elapsed=49.2s

  [2686/21087] intraday_11532.csv.gz  in=203,086,601 out=338,691 elapsed=49.2s

  [2687/21087] intraday_11533.csv.gz  in=203,100,616 out=352,706 elapsed=49.2s

  [2688/21087] intraday_11535.csv.gz  in=203,100,813 out=352,782 elapsed=49.2s

  [2689/21087] intraday_11534.csv.gz  in=203,112,346 out=364,315 elapsed=49.2s

  [2690/21087] intraday_11536.csv.gz  in=203,112,739 out=364,387 elapsed=49.2s

  [2691/21087] intraday_11537.csv.gz  in=203,112,810 out=364,458 elapsed=49.3s

  [2692/21087] intraday_11538.csv.gz  in=203,112,845 out=364,479 elapsed=49.3s

  [2693/21087] intraday_11539.csv.gz  in=203,113,119 out=364,492 elapsed=49.3s

  [2694/21087] intraday_1154.csv.gz  in=203,123,667 out=364,492 elapsed=49.3s

  [2695/21087] intraday_11540.csv.gz  in=203,123,672 out=364,495 elapsed=49.3s

  [2696/21087] intraday_11542.csv.gz  in=203,123,747 out=364,570 elapsed=49.3s

  [2697/21087] intraday_11541.csv.gz  in=203,123,775 out=364,580 elapsed=49.3s

  [2698/21087] intraday_11543.csv.gz  in=203,131,501 out=372,306 elapsed=49.3s

  [2699/21087] intraday_11544.csv.gz  in=203,141,993 out=382,798 elapsed=49.3s

  [2700/21087] intraday_11545.csv.gz  in=203,153,552 out=394,357 elapsed=49.3s

  [2701/21087] intraday_11547.csv.gz  in=203,163,665 out=404,470 elapsed=49.3s

  [2702/21087] intraday_11546.csv.gz  in=203,199,235 out=416,286 elapsed=49.3s

  [2703/21087] intraday_11548.csv.gz  in=203,210,936 out=427,987 elapsed=49.4s

  [2704/21087] intraday_11549.csv.gz  in=203,219,942 out=436,993 elapsed=49.4s

  [2705/21087] intraday_1155.csv.gz  in=203,233,284 out=436,993 elapsed=49.4s

  [2706/21087] intraday_11551.csv.gz  in=203,243,954 out=447,663 elapsed=49.4s

  [2707/21087] intraday_11550.csv.gz  in=203,254,109 out=457,772 elapsed=49.4s

  [2708/21087] intraday_11553.csv.gz  in=203,266,534 out=470,197 elapsed=49.4s

  [2709/21087] intraday_11552.csv.gz  in=203,277,146 out=480,809 elapsed=49.4s

  [2710/21087] intraday_11554.csv.gz  in=203,287,750 out=491,328 elapsed=49.4s

  [2711/21087] intraday_11557.csv.gz  in=203,297,302 out=500,880 elapsed=49.5s

  [2712/21087] intraday_11556.csv.gz  in=203,310,526 out=514,104 elapsed=49.5s

  [2713/21087] intraday_11558.csv.gz  in=203,320,976 out=524,554 elapsed=49.5s

  [2714/21087] intraday_11555.csv.gz  in=203,332,069 out=535,287 elapsed=49.5s

  [2715/21087] intraday_11559.csv.gz  in=203,343,553 out=546,771 elapsed=49.5s

  [2716/21087] intraday_1156.csv.gz  in=203,355,506 out=546,771 elapsed=49.5s

  [2717/21087] intraday_11560.csv.gz  in=203,365,654 out=556,919 elapsed=49.5s

  [2718/21087] intraday_11562.csv.gz  in=203,376,161 out=567,426 elapsed=49.6s

  [2719/21087] intraday_11561.csv.gz  in=203,399,107 out=578,040 elapsed=49.6s

  [2720/21087] intraday_11563.csv.gz  in=203,407,833 out=586,766 elapsed=49.6s

  [2721/21087] intraday_11564.csv.gz  in=203,419,383 out=598,299 elapsed=49.6s

  [2722/21087] intraday_11565.csv.gz  in=203,430,592 out=609,132 elapsed=49.6s

  [2723/21087] intraday_11566.csv.gz  in=203,441,222 out=619,762 elapsed=49.6s

  [2724/21087] intraday_11568.csv.gz  in=203,452,963 out=631,459 elapsed=49.6s

  [2725/21087] intraday_11567.csv.gz  in=203,464,580 out=643,076 elapsed=49.6s

  [2726/21087] intraday_1157.csv.gz  in=203,476,994 out=643,076 elapsed=49.6s

  [2727/21087] intraday_11569.csv.gz  in=203,487,488 out=653,570 elapsed=49.6s

  [2728/21087] intraday_11570.csv.gz  in=203,498,980 out=665,062 elapsed=49.6s

  [2729/21087] intraday_11571.csv.gz  in=203,511,019 out=677,101 elapsed=49.7s

  [2730/21087] intraday_11572.csv.gz  in=203,521,007 out=687,089 elapsed=49.7s

  [2731/21087] intraday_11573.csv.gz  in=203,533,189 out=699,165 elapsed=49.7s

  [2732/21087] intraday_11574.csv.gz  in=203,543,189 out=709,165 elapsed=49.7s

  [2733/21087] intraday_11576.csv.gz  in=203,552,735 out=718,711 elapsed=49.7s

  [2734/21087] intraday_11575.csv.gz  in=203,566,016 out=729,794 elapsed=49.7s

  [2735/21087] intraday_11577.csv.gz  in=203,579,564 out=743,342 elapsed=49.7s

  [2736/21087] intraday_11578.csv.gz  in=203,595,614 out=754,646 elapsed=49.7s

  [2737/21087] intraday_1158.csv.gz  in=203,612,797 out=754,646 elapsed=49.7s

  [2738/21087] intraday_11579.csv.gz  in=203,626,417 out=768,266 elapsed=49.7s

  [2739/21087] intraday_11580.csv.gz  in=203,639,094 out=780,943 elapsed=49.8s

  [2740/21087] intraday_11582.csv.gz  in=203,648,994 out=790,843 elapsed=49.8s

  [2741/21087] intraday_11581.csv.gz  in=203,660,737 out=802,580 elapsed=49.8s

  [2742/21087] intraday_11583.csv.gz  in=203,672,163 out=814,006 elapsed=49.8s

  [2743/21087] intraday_11584.csv.gz  in=203,683,971 out=825,814 elapsed=49.8s

  [2744/21087] intraday_11585.csv.gz  in=203,695,347 out=837,190 elapsed=49.8s

  [2745/21087] intraday_11586.csv.gz  in=203,707,182 out=849,025 elapsed=49.8s

  [2746/21087] intraday_11587.csv.gz  in=203,717,841 out=859,684 elapsed=49.8s

  [2747/21087] intraday_11588.csv.gz  in=203,727,518 out=869,361 elapsed=49.8s

  [2748/21087] intraday_1159.csv.gz  in=203,743,179 out=869,361 elapsed=49.9s

  [2749/21087] intraday_11589.csv.gz  in=203,756,646 out=882,757 elapsed=49.9s

  [2750/21087] intraday_11590.csv.gz  in=203,766,005 out=892,116 elapsed=49.9s

  [2751/21087] intraday_11591.csv.gz  in=203,777,016 out=903,127 elapsed=49.9s

  [2752/21087] intraday_11592.csv.gz  in=203,786,694 out=912,805 elapsed=49.9s

  [2753/21087] intraday_11593.csv.gz  in=203,794,340 out=920,451 elapsed=49.9s

  [2754/21087] intraday_11594.csv.gz  in=203,805,593 out=931,704 elapsed=49.9s

  [2755/21087] intraday_11595.csv.gz  in=203,816,659 out=942,770 elapsed=49.9s

  [2756/21087] intraday_11597.csv.gz  in=203,829,560 out=955,671 elapsed=49.9s

  [2757/21087] intraday_11596.csv.gz  in=203,844,927 out=971,038 elapsed=49.9s

  [2758/21087] intraday_11598.csv.gz  in=203,857,132 out=983,144 elapsed=49.9s

  [2759/21087] intraday_11599.csv.gz  in=203,866,452 out=992,464 elapsed=49.9s

  [2760/21087] intraday_1160.csv.gz  in=203,875,988 out=992,464 elapsed=49.9s

  [2761/21087] intraday_11601.csv.gz  in=203,886,065 out=1,002,541 elapsed=50.0s

  [2762/21087] intraday_11603.csv.gz  in=203,896,535 out=1,013,011 elapsed=50.0s

  [2763/21087] intraday_11602.csv.gz  in=203,909,385 out=1,025,861 elapsed=50.0s

  [2764/21087] intraday_11600.csv.gz  in=203,922,967 out=1,039,443 elapsed=50.0s

  [2765/21087] intraday_11605.csv.gz  in=203,933,932 out=1,050,408 elapsed=50.0s

  [2766/21087] intraday_11606.csv.gz  in=203,946,622 out=1,063,098 elapsed=50.1s

  [2767/21087] intraday_11604.csv.gz  in=203,958,453 out=1,074,929 elapsed=50.1s

  [2768/21087] intraday_11607.csv.gz  in=203,970,387 out=1,086,314 elapsed=50.1s

  [2769/21087] intraday_11608.csv.gz  in=203,982,327 out=1,098,254 elapsed=50.1s

  [2770/21087] intraday_11609.csv.gz  in=203,995,544 out=1,110,705 elapsed=50.1s

  [2771/21087] intraday_1161.csv.gz  in=204,007,668 out=1,110,705 elapsed=50.1s

  [2772/21087] intraday_11610.csv.gz  in=204,019,120 out=1,122,157 elapsed=50.1s

  [2773/21087] intraday_11611.csv.gz  in=204,028,816 out=1,131,853 elapsed=50.1s

  [2774/21087] intraday_11612.csv.gz  in=204,040,014 out=1,143,051 elapsed=50.1s

  [2775/21087] intraday_11613.csv.gz  in=204,049,673 out=1,152,710 elapsed=50.1s

  [2776/21087] intraday_11614.csv.gz  in=204,060,714 out=1,163,751 elapsed=50.1s

  [2777/21087] intraday_11616.csv.gz  in=204,072,501 out=1,175,534 elapsed=50.2s

  [2778/21087] intraday_11615.csv.gz  in=204,086,199 out=1,188,049 elapsed=50.2s

  [2779/21087] intraday_11617.csv.gz  in=204,097,073 out=1,198,923 elapsed=50.2s

  [2780/21087] intraday_11618.csv.gz  in=204,109,538 out=1,209,318 elapsed=50.2s

  [2781/21087] intraday_1162.csv.gz  in=204,122,967 out=1,209,318 elapsed=50.2s

  [2782/21087] intraday_11620.csv.gz  in=204,133,539 out=1,219,890 elapsed=50.2s

  [2783/21087] intraday_11619.csv.gz  in=204,147,190 out=1,233,541 elapsed=50.2s

  [2784/21087] intraday_11621.csv.gz  in=204,158,237 out=1,244,588 elapsed=50.2s

  [2785/21087] intraday_11622.csv.gz  in=204,170,614 out=1,256,965 elapsed=50.2s

  [2786/21087] intraday_11624.csv.gz  in=204,180,195 out=1,266,546 elapsed=50.3s

  [2787/21087] intraday_11623.csv.gz  in=204,193,968 out=1,279,895 elapsed=50.3s

  [2788/21087] intraday_11625.csv.gz  in=204,206,896 out=1,292,823 elapsed=50.3s

  [2789/21087] intraday_11626.csv.gz  in=204,221,751 out=1,307,678 elapsed=50.3s

  [2790/21087] intraday_11627.csv.gz  in=204,234,125 out=1,320,052 elapsed=50.3s

  [2791/21087] intraday_1163.csv.gz  in=204,248,261 out=1,320,052 elapsed=50.3s

  [2792/21087] intraday_11629.csv.gz  in=204,262,282 out=1,334,052 elapsed=50.3s

  [2793/21087] intraday_11630.csv.gz  in=204,278,610 out=1,350,380 elapsed=50.3s

  [2794/21087] intraday_11628.csv.gz  in=204,291,245 out=1,363,015 elapsed=50.3s

  [2795/21087] intraday_11631.csv.gz  in=204,305,593 out=1,377,363 elapsed=50.3s

  [2796/21087] intraday_11632.csv.gz  in=204,318,472 out=1,388,967 elapsed=50.4s

  [2797/21087] intraday_11633.csv.gz  in=204,329,270 out=1,399,765 elapsed=50.4s

  [2798/21087] intraday_11634.csv.gz  in=204,340,943 out=1,411,438 elapsed=50.4s

  [2799/21087] intraday_11635.csv.gz  in=204,352,498 out=1,422,993 elapsed=50.4s

  [2800/21087] intraday_11636.csv.gz  in=204,364,861 out=1,435,356 elapsed=50.4s

  [2801/21087] intraday_1164.csv.gz  in=204,375,469 out=1,435,356 elapsed=50.4s

  [2802/21087] intraday_11637.csv.gz  in=204,385,834 out=1,444,506 elapsed=50.4s

  [2803/21087] intraday_11638.csv.gz  in=204,397,915 out=1,456,587 elapsed=50.4s

  [2804/21087] intraday_11639.csv.gz  in=204,410,313 out=1,468,985 elapsed=50.4s

  [2805/21087] intraday_11642.csv.gz  in=204,420,668 out=1,479,325 elapsed=50.5s

  [2806/21087] intraday_11643.csv.gz  in=204,431,557 out=1,490,214 elapsed=50.5s

  [2807/21087] intraday_11641.csv.gz  in=204,444,425 out=1,500,558 elapsed=50.5s

  [2808/21087] intraday_11640.csv.gz  in=204,459,170 out=1,515,141 elapsed=50.5s

  [2809/21087] intraday_11644.csv.gz  in=204,470,225 out=1,526,196 elapsed=50.5s

  [2810/21087] intraday_11645.csv.gz  in=204,481,199 out=1,537,170 elapsed=50.5s

  [2811/21087] intraday_11646.csv.gz  in=204,494,750 out=1,550,568 elapsed=50.5s

  [2812/21087] intraday_11647.csv.gz  in=204,508,923 out=1,564,741 elapsed=50.5s

  [2813/21087] intraday_11648.csv.gz  in=204,521,157 out=1,576,975 elapsed=50.5s

  [2814/21087] intraday_1165.csv.gz  in=204,535,460 out=1,576,975 elapsed=50.6s

  [2815/21087] intraday_11649.csv.gz  in=204,551,221 out=1,592,736 elapsed=50.6s

  [2816/21087] intraday_11650.csv.gz  in=204,562,628 out=1,604,143 elapsed=50.6s

  [2817/21087] intraday_11651.csv.gz  in=204,575,570 out=1,616,535 elapsed=50.6s

  [2818/21087] intraday_11652.csv.gz  in=204,592,542 out=1,628,827 elapsed=50.6s

  [2819/21087] intraday_11655.csv.gz  in=204,601,409 out=1,635,049 elapsed=50.6s

  [2820/21087] intraday_11654.csv.gz  in=204,612,193 out=1,645,127 elapsed=50.6s

  [2821/21087] intraday_11653.csv.gz  in=204,622,271 out=1,655,205 elapsed=50.6s

  [2822/21087] intraday_11656.csv.gz  in=204,630,445 out=1,663,379 elapsed=50.6s

  [2823/21087] intraday_11658.csv.gz  in=204,630,574 out=1,663,508 elapsed=50.6s

  [2824/21087] intraday_1166.csv.gz  in=204,641,623 out=1,663,508 elapsed=50.7s

  [2825/21087] intraday_11657.csv.gz  in=204,652,093 out=1,673,978 elapsed=50.7s

  [2826/21087] intraday_11659.csv.gz  in=204,665,087 out=1,686,972 elapsed=50.7s

  [2827/21087] intraday_11660.csv.gz  in=204,677,000 out=1,698,885 elapsed=50.7s

  [2828/21087] intraday_11662.csv.gz  in=204,686,731 out=1,708,616 elapsed=50.7s

  [2829/21087] intraday_11661.csv.gz  in=204,700,113 out=1,721,998 elapsed=50.7s

  [2830/21087] intraday_11664.csv.gz  in=204,713,079 out=1,734,964 elapsed=50.7s

  [2831/21087] intraday_11663.csv.gz  in=204,723,544 out=1,745,429 elapsed=50.7s

  [2832/21087] intraday_11665.csv.gz  in=204,737,965 out=1,759,850 elapsed=50.7s

  [2833/21087] intraday_11666.csv.gz  in=204,748,893 out=1,770,778 elapsed=50.7s

  [2834/21087] intraday_11667.csv.gz  in=204,760,234 out=1,782,119 elapsed=50.7s

  [2835/21087] intraday_11668.csv.gz  in=204,772,482 out=1,794,367 elapsed=50.8s

  [2836/21087] intraday_1167.csv.gz  in=204,784,822 out=1,794,367 elapsed=50.8s

  [2837/21087] intraday_11669.csv.gz  in=204,796,897 out=1,806,442 elapsed=50.8s

  [2838/21087] intraday_11670.csv.gz  in=204,807,471 out=1,817,016 elapsed=50.8s

  [2839/21087] intraday_11671.csv.gz  in=204,819,655 out=1,829,200 elapsed=50.8s

  [2840/21087] intraday_11673.csv.gz  in=204,829,604 out=1,839,149 elapsed=50.8s

  [2841/21087] intraday_11672.csv.gz  in=204,841,581 out=1,851,126 elapsed=50.8s

  [2842/21087] intraday_11674.csv.gz  in=204,850,760 out=1,860,305 elapsed=50.8s

  [2843/21087] intraday_11675.csv.gz  in=204,862,625 out=1,872,170 elapsed=50.8s

  [2844/21087] intraday_11676.csv.gz  in=204,876,144 out=1,885,689 elapsed=50.8s

  [2845/21087] intraday_11677.csv.gz  in=204,887,774 out=1,897,319 elapsed=50.9s

  [2846/21087] intraday_11678.csv.gz  in=204,898,109 out=1,907,654 elapsed=50.9s

  [2847/21087] intraday_1168.csv.gz  in=204,909,966 out=1,907,654 elapsed=50.9s

  [2848/21087] intraday_11679.csv.gz  in=204,920,660 out=1,918,348 elapsed=50.9s

  [2849/21087] intraday_11680.csv.gz  in=204,932,563 out=1,930,251 elapsed=50.9s

  [2850/21087] intraday_11681.csv.gz  in=204,945,165 out=1,942,853 elapsed=50.9s

  [2851/21087] intraday_11682.csv.gz  in=204,956,781 out=1,954,469 elapsed=50.9s

  [2852/21087] intraday_11683.csv.gz  in=204,969,048 out=1,966,736 elapsed=50.9s

  [2853/21087] intraday_11684.csv.gz  in=204,979,975 out=1,977,663 elapsed=50.9s

  [2854/21087] intraday_11687.csv.gz  in=204,989,810 out=1,987,498 elapsed=51.0s

  [2855/21087] intraday_11686.csv.gz  in=205,000,199 out=1,997,887 elapsed=51.0s

  [2856/21087] intraday_11688.csv.gz  in=205,012,683 out=2,010,371 elapsed=51.0s

  [2857/21087] intraday_11685.csv.gz  in=205,024,885 out=2,022,573 elapsed=51.0s

  [2858/21087] intraday_1169.csv.gz  in=205,038,704 out=2,022,573 elapsed=51.0s

  [2859/21087] intraday_11689.csv.gz  in=205,052,164 out=2,036,033 elapsed=51.0s

  [2860/21087] intraday_11691.csv.gz  in=205,061,897 out=2,045,766 elapsed=51.0s

  [2861/21087] intraday_11690.csv.gz  in=205,074,611 out=2,058,480 elapsed=51.0s

  [2862/21087] intraday_11692.csv.gz  in=205,084,855 out=2,068,724 elapsed=51.0s

  [2863/21087] intraday_11693.csv.gz  in=205,096,725 out=2,080,594 elapsed=51.1s

  [2864/21087] intraday_11694.csv.gz  in=205,110,338 out=2,094,207 elapsed=51.1s

  [2865/21087] intraday_11695.csv.gz  in=205,120,916 out=2,104,785 elapsed=51.1s

  [2866/21087] intraday_11696.csv.gz  in=205,132,267 out=2,116,136 elapsed=51.1s

  [2867/21087] intraday_11697.csv.gz  in=205,142,059 out=2,125,928 elapsed=51.1s

  [2868/21087] intraday_11698.csv.gz  in=205,152,951 out=2,136,820 elapsed=51.1s

  [2869/21087] intraday_11699.csv.gz  in=205,163,186 out=2,147,055 elapsed=51.1s

  [2870/21087] intraday_1170.csv.gz  in=205,173,622 out=2,147,055 elapsed=51.1s

  [2871/21087] intraday_11700.csv.gz  in=205,184,912 out=2,158,345 elapsed=51.1s

  [2872/21087] intraday_11701.csv.gz  in=205,197,823 out=2,171,256 elapsed=51.1s

  [2873/21087] intraday_11702.csv.gz  in=205,209,146 out=2,182,579 elapsed=51.2s

  [2874/21087] intraday_11703.csv.gz  in=205,220,867 out=2,194,300 elapsed=51.2s

  [2875/21087] intraday_11704.csv.gz  in=205,233,598 out=2,207,031 elapsed=51.2s

  [2876/21087] intraday_11705.csv.gz  in=205,243,408 out=2,216,841 elapsed=51.2s

  [2877/21087] intraday_11707.csv.gz  in=205,254,152 out=2,227,585 elapsed=51.2s

  [2878/21087] intraday_11706.csv.gz  in=205,265,972 out=2,239,405 elapsed=51.2s

  [2879/21087] intraday_11708.csv.gz  in=205,276,530 out=2,249,963 elapsed=51.2s

  [2880/21087] intraday_11709.csv.gz  in=205,287,963 out=2,261,396 elapsed=51.2s

  [2881/21087] intraday_1171.csv.gz  in=205,298,689 out=2,261,396 elapsed=51.2s

  [2882/21087] intraday_11710.csv.gz  in=205,308,631 out=2,271,338 elapsed=51.3s

  [2883/21087] intraday_11711.csv.gz  in=205,318,441 out=2,281,148 elapsed=51.3s

  [2884/21087] intraday_11712.csv.gz  in=205,330,569 out=2,293,276 elapsed=51.3s

  [2885/21087] intraday_11713.csv.gz  in=205,342,699 out=2,305,406 elapsed=51.3s

  [2886/21087] intraday_11714.csv.gz  in=205,353,212 out=2,315,919 elapsed=51.3s

  [2887/21087] intraday_11715.csv.gz  in=205,365,162 out=2,327,869 elapsed=51.3s

  [2888/21087] intraday_11716.csv.gz  in=205,376,735 out=2,339,442 elapsed=51.3s

  [2889/21087] intraday_11717.csv.gz  in=205,387,339 out=2,350,046 elapsed=51.3s

  [2890/21087] intraday_11718.csv.gz  in=205,399,276 out=2,361,983 elapsed=51.3s

  [2891/21087] intraday_1172.csv.gz  in=205,413,538 out=2,361,983 elapsed=51.4s

  [2892/21087] intraday_11719.csv.gz  in=205,425,560 out=2,374,005 elapsed=51.4s

  [2893/21087] intraday_11720.csv.gz  in=205,437,078 out=2,385,523 elapsed=51.4s

  [2894/21087] intraday_11721.csv.gz  in=205,448,763 out=2,397,208 elapsed=51.4s

  [2895/21087] intraday_11722.csv.gz  in=205,459,331 out=2,407,776 elapsed=51.4s

  [2896/21087] intraday_11723.csv.gz  in=205,470,074 out=2,418,519 elapsed=51.4s

  [2897/21087] intraday_11724.csv.gz  in=205,480,382 out=2,428,827 elapsed=51.4s

  [2898/21087] intraday_11725.csv.gz  in=205,494,375 out=2,442,820 elapsed=51.4s

  [2899/21087] intraday_11726.csv.gz  in=205,506,276 out=2,454,721 elapsed=51.4s

  [2900/21087] intraday_11727.csv.gz  in=205,520,303 out=2,468,748 elapsed=51.4s

  [2901/21087] intraday_11729.csv.gz  in=205,530,978 out=2,479,423 elapsed=51.5s

  [2902/21087] intraday_1173.csv.gz  in=205,545,816 out=2,479,423 elapsed=51.5s

  [2903/21087] intraday_11728.csv.gz  in=205,557,891 out=2,491,498 elapsed=51.5s

  [2904/21087] intraday_11730.csv.gz  in=205,568,170 out=2,501,777 elapsed=51.5s

  [2905/21087] intraday_11731.csv.gz  in=205,579,775 out=2,513,382 elapsed=51.5s

  [2906/21087] intraday_11732.csv.gz  in=205,592,919 out=2,526,526 elapsed=51.5s

  [2907/21087] intraday_11734.csv.gz  in=205,604,417 out=2,538,024 elapsed=51.5s

  [2908/21087] intraday_11733.csv.gz  in=205,617,475 out=2,551,082 elapsed=51.5s

  [2909/21087] intraday_11735.csv.gz  in=205,628,769 out=2,562,376 elapsed=51.5s

  [2910/21087] intraday_11736.csv.gz  in=205,638,744 out=2,572,351 elapsed=51.5s

  [2911/21087] intraday_11738.csv.gz  in=205,649,007 out=2,582,614 elapsed=51.6s

  [2912/21087] intraday_11739.csv.gz  in=205,659,535 out=2,593,142 elapsed=51.6s

  [2913/21087] intraday_11737.csv.gz  in=205,673,508 out=2,607,115 elapsed=51.6s

  [2914/21087] intraday_1174.csv.gz  in=205,686,180 out=2,607,115 elapsed=51.6s

  [2915/21087] intraday_11741.csv.gz  in=205,694,625 out=2,615,560 elapsed=51.6s

  [2916/21087] intraday_11740.csv.gz  in=205,704,603 out=2,625,538 elapsed=51.6s

  [2917/21087] intraday_11742.csv.gz  in=205,715,704 out=2,636,639 elapsed=51.6s

  [2918/21087] intraday_11743.csv.gz  in=205,727,626 out=2,648,561 elapsed=51.6s

  [2919/21087] intraday_11747.csv.gz  in=205,737,736 out=2,658,671 elapsed=51.7s

  [2920/21087] intraday_11746.csv.gz  in=205,749,854 out=2,670,789 elapsed=51.7s

  [2921/21087] intraday_11745.csv.gz  in=205,761,881 out=2,682,816 elapsed=51.7s

  [2922/21087] intraday_11744.csv.gz  in=205,779,145 out=2,700,080 elapsed=51.7s

  [2923/21087] intraday_1175.csv.gz  in=205,791,234 out=2,700,080 elapsed=51.7s

  [2924/21087] intraday_11749.csv.gz  in=205,800,762 out=2,709,608 elapsed=51.7s

  [2925/21087] intraday_11748.csv.gz  in=205,814,556 out=2,723,402 elapsed=51.7s

  [2926/21087] intraday_11750.csv.gz  in=205,827,491 out=2,736,337 elapsed=51.7s

  [2927/21087] intraday_11751.csv.gz  in=205,838,769 out=2,747,615 elapsed=51.7s

  [2928/21087] intraday_11752.csv.gz  in=205,849,258 out=2,758,104 elapsed=51.8s

  [2929/21087] intraday_11754.csv.gz  in=205,862,809 out=2,771,655 elapsed=51.8s

  [2930/21087] intraday_11753.csv.gz  in=205,874,601 out=2,783,447 elapsed=51.8s

  [2931/21087] intraday_11755.csv.gz  in=205,887,365 out=2,796,211 elapsed=51.8s

  [2932/21087] intraday_11756.csv.gz  in=205,899,036 out=2,807,882 elapsed=51.8s

  [2933/21087] intraday_11759.csv.gz  in=205,909,484 out=2,818,330 elapsed=51.8s

  [2934/21087] intraday_1176.csv.gz  in=205,922,522 out=2,818,330 elapsed=51.8s

  [2935/21087] intraday_11757.csv.gz  in=205,934,608 out=2,830,416 elapsed=51.8s

  [2936/21087] intraday_11758.csv.gz  in=205,945,989 out=2,841,797 elapsed=51.8s

  [2937/21087] intraday_11760.csv.gz  in=205,957,596 out=2,853,404 elapsed=51.9s

  [2938/21087] intraday_11761.csv.gz  in=205,967,110 out=2,862,918 elapsed=51.9s

  [2939/21087] intraday_11762.csv.gz  in=205,978,895 out=2,874,703 elapsed=51.9s

  [2940/21087] intraday_11763.csv.gz  in=205,991,792 out=2,887,600 elapsed=51.9s

  [2941/21087] intraday_11765.csv.gz  in=206,003,008 out=2,898,816 elapsed=51.9s

  [2942/21087] intraday_11766.csv.gz  in=206,013,030 out=2,908,838 elapsed=51.9s

  [2943/21087] intraday_11764.csv.gz  in=206,025,292 out=2,921,100 elapsed=51.9s

  [2944/21087] intraday_11767.csv.gz  in=206,039,376 out=2,935,184 elapsed=51.9s

  [2945/21087] intraday_11768.csv.gz  in=206,049,521 out=2,945,329 elapsed=51.9s

  [2946/21087] intraday_11769.csv.gz  in=206,061,387 out=2,957,195 elapsed=51.9s

  [2947/21087] intraday_1177.csv.gz  in=206,073,460 out=2,957,195 elapsed=52.0s

  [2948/21087] intraday_11770.csv.gz  in=206,086,209 out=2,969,944 elapsed=52.0s

  [2949/21087] intraday_11771.csv.gz  in=206,099,719 out=2,983,454 elapsed=52.0s

  [2950/21087] intraday_11772.csv.gz  in=206,110,189 out=2,993,924 elapsed=52.0s

  [2951/21087] intraday_11773.csv.gz  in=206,123,426 out=3,007,161 elapsed=52.0s

  [2952/21087] intraday_11774.csv.gz  in=206,139,040 out=3,022,775 elapsed=52.0s

  [2953/21087] intraday_11775.csv.gz  in=206,150,840 out=3,034,575 elapsed=52.0s

  [2954/21087] intraday_11776.csv.gz  in=206,165,003 out=3,048,738 elapsed=52.0s

  [2955/21087] intraday_11777.csv.gz  in=206,178,339 out=3,062,074 elapsed=52.0s

  [2956/21087] intraday_11778.csv.gz  in=206,194,442 out=3,078,177 elapsed=52.1s

  [2957/21087] intraday_11779.csv.gz  in=206,208,112 out=3,091,847 elapsed=52.1s

  [2958/21087] intraday_1178.csv.gz  in=206,221,670 out=3,091,847 elapsed=52.1s

  [2959/21087] intraday_11780.csv.gz  in=206,236,141 out=3,106,318 elapsed=52.1s

  [2960/21087] intraday_11781.csv.gz  in=206,246,871 out=3,117,048 elapsed=52.1s

  [2961/21087] intraday_11782.csv.gz  in=206,259,920 out=3,130,097 elapsed=52.1s

  [2962/21087] intraday_11783.csv.gz  in=206,271,232 out=3,141,409 elapsed=52.1s

  [2963/21087] intraday_11784.csv.gz  in=206,283,195 out=3,153,372 elapsed=52.1s

  [2964/21087] intraday_11785.csv.gz  in=206,293,919 out=3,164,096 elapsed=52.1s

  [2965/21087] intraday_11786.csv.gz  in=206,304,757 out=3,174,934 elapsed=52.2s

  [2966/21087] intraday_11788.csv.gz  in=206,318,478 out=3,188,655 elapsed=52.2s

  [2967/21087] intraday_11787.csv.gz  in=206,331,616 out=3,201,793 elapsed=52.2s

  [2968/21087] intraday_11789.csv.gz  in=206,342,089 out=3,212,266 elapsed=52.2s

  [2969/21087] intraday_1179.csv.gz  in=206,357,908 out=3,212,266 elapsed=52.2s

  [2970/21087] intraday_11790.csv.gz  in=206,368,692 out=3,223,050 elapsed=52.2s

  [2971/21087] intraday_11791.csv.gz  in=206,380,249 out=3,234,607 elapsed=52.2s

  [2972/21087] intraday_11792.csv.gz  in=206,392,019 out=3,246,377 elapsed=52.2s

  [2973/21087] intraday_11793.csv.gz  in=206,402,094 out=3,256,452 elapsed=52.2s

  [2974/21087] intraday_11794.csv.gz  in=206,416,535 out=3,270,893 elapsed=52.2s

  [2975/21087] intraday_11795.csv.gz  in=206,431,598 out=3,285,956 elapsed=52.3s

  [2976/21087] intraday_11796.csv.gz  in=206,444,067 out=3,298,425 elapsed=52.3s

  [2977/21087] intraday_11797.csv.gz  in=206,459,750 out=3,314,108 elapsed=52.3s

  [2978/21087] intraday_11798.csv.gz  in=206,470,762 out=3,325,120 elapsed=52.3s

  [2979/21087] intraday_11799.csv.gz  in=206,482,718 out=3,337,076 elapsed=52.3s

  [2980/21087] intraday_1180.csv.gz  in=206,502,336 out=3,337,076 elapsed=52.3s

  [2981/21087] intraday_11800.csv.gz  in=206,515,151 out=3,349,891 elapsed=52.3s

  [2982/21087] intraday_11801.csv.gz  in=206,524,725 out=3,359,465 elapsed=52.3s

  [2983/21087] intraday_11802.csv.gz  in=206,536,355 out=3,371,095 elapsed=52.3s

  [2984/21087] intraday_11803.csv.gz  in=206,542,426 out=3,377,166 elapsed=52.3s

  [2985/21087] intraday_11804.csv.gz  in=206,552,067 out=3,386,807 elapsed=52.3s

  [2986/21087] intraday_11805.csv.gz  in=206,561,059 out=3,395,799 elapsed=52.3s

  [2987/21087] intraday_11806.csv.gz  in=206,584,200 out=3,398,224 elapsed=52.4s

  [2988/21087] intraday_11808.csv.gz  in=206,597,338 out=3,411,362 elapsed=52.4s

  [2989/21087] intraday_11807.csv.gz  in=206,611,332 out=3,425,356 elapsed=52.4s

  [2990/21087] intraday_1181.csv.gz  in=206,625,872 out=3,425,356 elapsed=52.4s

  [2991/21087] intraday_11809.csv.gz  in=206,638,444 out=3,437,928 elapsed=52.4s

  [2992/21087] intraday_11810.csv.gz  in=206,647,883 out=3,447,367 elapsed=52.4s

  [2993/21087] intraday_11813.csv.gz  in=206,662,150 out=3,461,634 elapsed=52.4s

  [2994/21087] intraday_11811.csv.gz  in=206,673,698 out=3,473,182 elapsed=52.4s

  [2995/21087] intraday_11812.csv.gz  in=206,687,528 out=3,487,012 elapsed=52.4s

  [2996/21087] intraday_11814.csv.gz  in=206,699,256 out=3,498,740 elapsed=52.5s

  [2997/21087] intraday_11815.csv.gz  in=206,711,354 out=3,510,838 elapsed=52.5s

  [2998/21087] intraday_11816.csv.gz  in=206,724,259 out=3,523,743 elapsed=52.5s

  [2999/21087] intraday_11817.csv.gz  in=206,736,833 out=3,536,317 elapsed=52.5s

  [3000/21087] intraday_11818.csv.gz  in=206,747,634 out=3,547,118 elapsed=52.5s

  [3001/21087] intraday_11819.csv.gz  in=206,761,026 out=3,560,510 elapsed=52.5s

  [3002/21087] intraday_1182.csv.gz  in=206,775,682 out=3,560,510 elapsed=52.5s

  [3003/21087] intraday_11821.csv.gz  in=206,784,942 out=3,569,770 elapsed=52.5s

  [3004/21087] intraday_11820.csv.gz  in=206,797,687 out=3,582,515 elapsed=52.5s

  [3005/21087] intraday_11822.csv.gz  in=206,809,059 out=3,593,887 elapsed=52.5s

  [3006/21087] intraday_11823.csv.gz  in=206,822,751 out=3,607,579 elapsed=52.6s

  [3007/21087] intraday_11824.csv.gz  in=206,837,460 out=3,622,288 elapsed=52.6s

  [3008/21087] intraday_11826.csv.gz  in=206,847,746 out=3,632,574 elapsed=52.6s

  [3009/21087] intraday_11825.csv.gz  in=206,858,040 out=3,642,868 elapsed=52.6s

  [3010/21087] intraday_11827.csv.gz  in=206,868,775 out=3,653,603 elapsed=52.6s

  [3011/21087] intraday_11828.csv.gz  in=206,881,265 out=3,666,093 elapsed=52.6s

  [3012/21087] intraday_1183.csv.gz  in=206,896,268 out=3,666,093 elapsed=52.6s

  [3013/21087] intraday_11829.csv.gz  in=206,908,635 out=3,678,460 elapsed=52.6s

  [3014/21087] intraday_11830.csv.gz  in=206,920,472 out=3,690,297 elapsed=52.6s

  [3015/21087] intraday_11831.csv.gz  in=206,933,754 out=3,703,311 elapsed=52.6s

  [3016/21087] intraday_11832.csv.gz  in=206,945,365 out=3,714,922 elapsed=52.7s

  [3017/21087] intraday_11833.csv.gz  in=206,957,134 out=3,726,691 elapsed=52.7s

  [3018/21087] intraday_11834.csv.gz  in=206,969,081 out=3,738,638 elapsed=52.7s

  [3019/21087] intraday_11835.csv.gz  in=206,979,142 out=3,748,699 elapsed=52.7s

  [3020/21087] intraday_11836.csv.gz  in=206,991,893 out=3,761,450 elapsed=52.7s

  [3021/21087] intraday_11837.csv.gz  in=207,005,542 out=3,775,099 elapsed=52.7s

  [3022/21087] intraday_11839.csv.gz  in=207,015,848 out=3,785,405 elapsed=52.7s

  [3023/21087] intraday_11838.csv.gz  in=207,028,889 out=3,798,446 elapsed=52.7s

  [3024/21087] intraday_1184.csv.gz  in=207,042,635 out=3,798,446 elapsed=52.7s

  [3025/21087] intraday_11840.csv.gz  in=207,054,204 out=3,810,015 elapsed=52.7s

  [3026/21087] intraday_11841.csv.gz  in=207,066,678 out=3,822,489 elapsed=52.8s

  [3027/21087] intraday_11842.csv.gz  in=207,079,655 out=3,835,466 elapsed=52.8s

  [3028/21087] intraday_11843.csv.gz  in=207,091,519 out=3,847,330 elapsed=52.8s

  [3029/21087] intraday_11844.csv.gz  in=207,102,301 out=3,858,112 elapsed=52.8s

  [3030/21087] intraday_11845.csv.gz  in=207,113,031 out=3,868,842 elapsed=52.8s

  [3031/21087] intraday_11846.csv.gz  in=207,123,881 out=3,879,692 elapsed=52.8s

  [3032/21087] intraday_11847.csv.gz  in=207,135,460 out=3,891,271 elapsed=52.8s

  [3033/21087] intraday_11848.csv.gz  in=207,148,960 out=3,904,771 elapsed=52.8s

  [3034/21087] intraday_11849.csv.gz  in=207,159,507 out=3,915,310 elapsed=52.8s

  [3035/21087] intraday_1185.csv.gz  in=207,171,770 out=3,915,310 elapsed=52.8s

  [3036/21087] intraday_11850.csv.gz  in=207,184,242 out=3,927,782 elapsed=52.9s

  [3037/21087] intraday_11852.csv.gz  in=207,196,105 out=3,939,645 elapsed=52.9s

  [3038/21087] intraday_11851.csv.gz  in=207,210,171 out=3,953,711 elapsed=52.9s

  [3039/21087] intraday_11853.csv.gz  in=207,221,755 out=3,965,295 elapsed=52.9s

  [3040/21087] intraday_11854.csv.gz  in=207,233,701 out=3,977,241 elapsed=52.9s

  [3041/21087] intraday_11855.csv.gz  in=207,245,760 out=3,989,300 elapsed=52.9s

  [3042/21087] intraday_11856.csv.gz  in=207,256,093 out=3,999,633 elapsed=52.9s

  [3043/21087] intraday_11857.csv.gz  in=207,268,159 out=4,011,662 elapsed=52.9s

  [3044/21087] intraday_11858.csv.gz  in=207,277,351 out=4,020,854 elapsed=52.9s

  [3045/21087] intraday_1186.csv.gz  in=207,298,913 out=4,020,854 elapsed=53.0s

  [3046/21087] intraday_11859.csv.gz  in=207,309,947 out=4,031,888 elapsed=53.0s

  [3047/21087] intraday_11860.csv.gz  in=207,320,425 out=4,042,366 elapsed=53.0s

  [3048/21087] intraday_11861.csv.gz  in=207,333,923 out=4,055,864 elapsed=53.0s

  [3049/21087] intraday_11862.csv.gz  in=207,346,974 out=4,068,915 elapsed=53.0s

  [3050/21087] intraday_11864.csv.gz  in=207,359,309 out=4,081,250 elapsed=53.0s

  [3051/21087] intraday_11863.csv.gz  in=207,370,894 out=4,092,764 elapsed=53.0s

  [3052/21087] intraday_11865.csv.gz  in=207,381,467 out=4,103,337 elapsed=53.0s

  [3053/21087] intraday_11866.csv.gz  in=207,392,820 out=4,114,631 elapsed=53.1s

  [3054/21087] intraday_11867.csv.gz  in=207,405,279 out=4,127,090 elapsed=53.1s

  [3055/21087] intraday_11868.csv.gz  in=207,415,876 out=4,137,687 elapsed=53.1s

  [3056/21087] intraday_11869.csv.gz  in=207,427,144 out=4,148,955 elapsed=53.1s

  [3057/21087] intraday_1187.csv.gz  in=207,441,249 out=4,148,955 elapsed=53.1s

  [3058/21087] intraday_11871.csv.gz  in=207,450,673 out=4,158,379 elapsed=53.1s

  [3059/21087] intraday_11870.csv.gz  in=207,463,234 out=4,170,940 elapsed=53.1s

  [3060/21087] intraday_11872.csv.gz  in=207,477,599 out=4,183,982 elapsed=53.1s

  [3061/21087] intraday_11873.csv.gz  in=207,492,255 out=4,198,638 elapsed=53.1s

  [3062/21087] intraday_11874.csv.gz  in=207,503,684 out=4,210,067 elapsed=53.1s

  [3063/21087] intraday_11875.csv.gz  in=207,517,434 out=4,223,817 elapsed=53.1s

  [3064/21087] intraday_11876.csv.gz  in=207,527,874 out=4,234,257 elapsed=53.1s

  [3065/21087] intraday_11877.csv.gz  in=207,537,462 out=4,243,845 elapsed=53.2s

  [3066/21087] intraday_1188.csv.gz  in=207,549,375 out=4,243,845 elapsed=53.2s

  [3067/21087] intraday_11879.csv.gz  in=207,562,203 out=4,256,673 elapsed=53.2s

  [3068/21087] intraday_11878.csv.gz  in=207,575,896 out=4,270,366 elapsed=53.2s

  [3069/21087] intraday_11880.csv.gz  in=207,587,509 out=4,281,979 elapsed=53.2s

  [3070/21087] intraday_11881.csv.gz  in=207,600,879 out=4,295,349 elapsed=53.2s

  [3071/21087] intraday_11884.csv.gz  in=207,612,594 out=4,307,064 elapsed=53.3s

  [3072/21087] intraday_11882.csv.gz  in=207,625,569 out=4,320,039 elapsed=53.3s

  [3073/21087] intraday_11885.csv.gz  in=207,638,994 out=4,333,464 elapsed=53.3s

  [3074/21087] intraday_11883.csv.gz  in=207,648,513 out=4,342,983 elapsed=53.3s

  [3075/21087] intraday_11886.csv.gz  in=207,658,877 out=4,353,347 elapsed=53.3s

  [3076/21087] intraday_11887.csv.gz  in=207,668,443 out=4,362,913 elapsed=53.3s

  [3077/21087] intraday_11888.csv.gz  in=207,677,133 out=4,371,603 elapsed=53.3s

  [3078/21087] intraday_1189.csv.gz  in=207,690,286 out=4,371,603 elapsed=53.3s

  [3079/21087] intraday_11889.csv.gz  in=207,701,405 out=4,382,722 elapsed=53.3s

  [3080/21087] intraday_11890.csv.gz  in=207,714,156 out=4,395,473 elapsed=53.4s

  [3081/21087] intraday_11893.csv.gz  in=207,726,277 out=4,407,594 elapsed=53.4s

  [3082/21087] intraday_11891.csv.gz  in=207,740,347 out=4,421,664 elapsed=53.4s

  [3083/21087] intraday_11892.csv.gz  in=207,756,695 out=4,438,012 elapsed=53.4s

  [3084/21087] intraday_11897.csv.gz  in=207,770,698 out=4,452,015 elapsed=53.4s

  [3085/21087] intraday_11895.csv.gz  in=207,782,105 out=4,463,422 elapsed=53.4s

  [3086/21087] intraday_11896.csv.gz  in=207,794,365 out=4,475,682 elapsed=53.4s

  [3087/21087] intraday_11894.csv.gz  in=207,805,722 out=4,487,039 elapsed=53.4s

  [3088/21087] intraday_1190.csv.gz  in=207,817,950 out=4,487,039 elapsed=53.4s

  [3089/21087] intraday_11898.csv.gz  in=207,829,088 out=4,498,177 elapsed=53.5s

  [3090/21087] intraday_11899.csv.gz  in=207,840,106 out=4,509,195 elapsed=53.5s

  [3091/21087] intraday_11900.csv.gz  in=207,853,968 out=4,523,057 elapsed=53.5s

  [3092/21087] intraday_11901.csv.gz  in=207,866,616 out=4,535,705 elapsed=53.5s

  [3093/21087] intraday_11902.csv.gz  in=207,879,134 out=4,548,223 elapsed=53.5s

  [3094/21087] intraday_11903.csv.gz  in=207,891,426 out=4,560,515 elapsed=53.5s

  [3095/21087] intraday_11904.csv.gz  in=207,903,186 out=4,572,275 elapsed=53.5s

  [3096/21087] intraday_11905.csv.gz  in=207,915,466 out=4,584,555 elapsed=53.5s

  [3097/21087] intraday_11906.csv.gz  in=207,927,459 out=4,596,548 elapsed=53.5s

  [3098/21087] intraday_11908.csv.gz  in=207,938,458 out=4,607,547 elapsed=53.6s

  [3099/21087] intraday_11907.csv.gz  in=207,951,043 out=4,620,132 elapsed=53.6s

  [3100/21087] intraday_11909.csv.gz  in=207,963,631 out=4,632,720 elapsed=53.6s

  [3101/21087] intraday_1191.csv.gz  in=207,976,089 out=4,632,720 elapsed=53.6s

  [3102/21087] intraday_11913.csv.gz  in=207,987,312 out=4,643,777 elapsed=53.6s

  [3103/21087] intraday_11911.csv.gz  in=207,999,127 out=4,655,592 elapsed=53.6s

  [3104/21087] intraday_11910.csv.gz  in=208,012,591 out=4,669,056 elapsed=53.6s

  [3105/21087] intraday_11912.csv.gz  in=208,024,274 out=4,680,739 elapsed=53.6s

  [3106/21087] intraday_11915.csv.gz  in=208,034,527 out=4,690,992 elapsed=53.7s

  [3107/21087] intraday_11916.csv.gz  in=208,045,937 out=4,702,402 elapsed=53.7s

  [3108/21087] intraday_11914.csv.gz  in=208,060,395 out=4,716,860 elapsed=53.7s

  [3109/21087] intraday_11917.csv.gz  in=208,074,172 out=4,730,637 elapsed=53.7s

  [3110/21087] intraday_1192.csv.gz  in=208,086,406 out=4,730,637 elapsed=53.7s

  [3111/21087] intraday_11919.csv.gz  in=208,096,564 out=4,740,795 elapsed=53.7s

  [3112/21087] intraday_11920.csv.gz  in=208,109,365 out=4,753,596 elapsed=53.7s

  [3113/21087] intraday_11918.csv.gz  in=208,122,993 out=4,767,224 elapsed=53.7s

  [3114/21087] intraday_11922.csv.gz  in=208,137,352 out=4,781,583 elapsed=53.8s

  [3115/21087] intraday_11921.csv.gz  in=208,151,899 out=4,796,130 elapsed=53.8s

  [3116/21087] intraday_11923.csv.gz  in=208,164,722 out=4,808,953 elapsed=53.8s

  [3117/21087] intraday_11924.csv.gz  in=208,179,512 out=4,823,743 elapsed=53.8s

  [3118/21087] intraday_11926.csv.gz  in=208,193,507 out=4,837,738 elapsed=53.8s

  [3119/21087] intraday_11925.csv.gz  in=208,210,697 out=4,854,928 elapsed=53.8s

  [3120/21087] intraday_11928.csv.gz  in=208,222,519 out=4,866,750 elapsed=53.8s

  [3121/21087] intraday_11927.csv.gz  in=208,236,434 out=4,880,665 elapsed=53.8s

  [3122/21087] intraday_1193.csv.gz  in=208,248,417 out=4,880,665 elapsed=53.8s

  [3123/21087] intraday_11929.csv.gz  in=208,261,050 out=4,893,298 elapsed=53.8s

  [3124/21087] intraday_11930.csv.gz  in=208,273,607 out=4,905,855 elapsed=53.9s

  [3125/21087] intraday_11932.csv.gz  in=208,285,052 out=4,917,127 elapsed=53.9s

  [3126/21087] intraday_11931.csv.gz  in=208,297,551 out=4,929,626 elapsed=53.9s

  [3127/21087] intraday_11933.csv.gz  in=208,310,433 out=4,942,508 elapsed=53.9s

  [3128/21087] intraday_11934.csv.gz  in=208,322,454 out=4,954,529 elapsed=53.9s

  [3129/21087] intraday_11935.csv.gz  in=208,337,586 out=4,969,661 elapsed=53.9s

  [3130/21087] intraday_11936.csv.gz  in=208,347,793 out=4,979,868 elapsed=53.9s

  [3131/21087] intraday_11937.csv.gz  in=208,359,064 out=4,991,139 elapsed=53.9s

  [3132/21087] intraday_11938.csv.gz  in=208,370,369 out=5,002,444 elapsed=53.9s

  [3133/21087] intraday_11939.csv.gz  in=208,382,149 out=5,014,224 elapsed=53.9s

  [3134/21087] intraday_1194.csv.gz  in=208,399,840 out=5,014,224 elapsed=54.0s

  [3135/21087] intraday_11940.csv.gz  in=208,410,845 out=5,025,229 elapsed=54.0s

  [3136/21087] intraday_11941.csv.gz  in=208,423,987 out=5,038,371 elapsed=54.0s

  [3137/21087] intraday_11942.csv.gz  in=208,438,901 out=5,053,285 elapsed=54.0s

  [3138/21087] intraday_11943.csv.gz  in=208,452,515 out=5,066,899 elapsed=54.0s

  [3139/21087] intraday_11945.csv.gz  in=208,464,868 out=5,079,252 elapsed=54.0s

  [3140/21087] intraday_11944.csv.gz  in=208,480,499 out=5,094,883 elapsed=54.0s

  [3141/21087] intraday_11946.csv.gz  in=208,492,025 out=5,106,409 elapsed=54.0s

  [3142/21087] intraday_11947.csv.gz  in=208,504,406 out=5,118,790 elapsed=54.0s

  [3143/21087] intraday_11948.csv.gz  in=208,515,163 out=5,129,547 elapsed=54.0s

  [3144/21087] intraday_11949.csv.gz  in=208,527,627 out=5,142,011 elapsed=54.1s

  [3145/21087] intraday_1195.csv.gz  in=208,537,470 out=5,142,011 elapsed=54.1s

  [3146/21087] intraday_11950.csv.gz  in=208,544,007 out=5,148,548 elapsed=54.1s

  [3147/21087] intraday_11952.csv.gz  in=208,555,077 out=5,159,618 elapsed=54.1s

  [3148/21087] intraday_11953.csv.gz  in=208,570,692 out=5,175,233 elapsed=54.1s

  [3149/21087] intraday_11954.csv.gz  in=208,583,888 out=5,188,429 elapsed=54.1s

  [3150/21087] intraday_11951.csv.gz  in=208,596,444 out=5,197,086 elapsed=54.1s

  [3151/21087] intraday_11955.csv.gz  in=208,609,551 out=5,209,377 elapsed=54.1s

  [3152/21087] intraday_11956.csv.gz  in=208,620,649 out=5,220,475 elapsed=54.2s

  [3153/21087] intraday_11958.csv.gz  in=208,635,313 out=5,235,139 elapsed=54.2s

  [3154/21087] intraday_11957.csv.gz  in=208,647,274 out=5,247,100 elapsed=54.2s

  [3155/21087] intraday_11959.csv.gz  in=208,663,748 out=5,263,574 elapsed=54.2s

  [3156/21087] intraday_1196.csv.gz  in=208,683,631 out=5,263,574 elapsed=54.2s

  [3157/21087] intraday_11960.csv.gz  in=208,695,078 out=5,275,021 elapsed=54.2s

  [3158/21087] intraday_11963.csv.gz  in=208,708,188 out=5,288,131 elapsed=54.2s

  [3159/21087] intraday_11961.csv.gz  in=208,720,198 out=5,300,141 elapsed=54.2s

  [3160/21087] intraday_11962.csv.gz  in=208,734,068 out=5,314,011 elapsed=54.2s

  [3161/21087] intraday_11964.csv.gz  in=208,745,424 out=5,325,367 elapsed=54.2s

  [3162/21087] intraday_11965.csv.gz  in=208,758,755 out=5,338,698 elapsed=54.3s

  [3163/21087] intraday_11966.csv.gz  in=208,771,297 out=5,351,240 elapsed=54.3s

  [3164/21087] intraday_11967.csv.gz  in=208,781,178 out=5,361,121 elapsed=54.3s

  [3165/21087] intraday_11968.csv.gz  in=208,792,487 out=5,372,430 elapsed=54.3s

  [3166/21087] intraday_11969.csv.gz  in=208,806,413 out=5,386,356 elapsed=54.3s

  [3167/21087] intraday_1197.csv.gz  in=208,821,601 out=5,386,356 elapsed=54.3s

  [3168/21087] intraday_11970.csv.gz  in=208,834,834 out=5,399,589 elapsed=54.3s

  [3169/21087] intraday_11971.csv.gz  in=208,847,263 out=5,411,713 elapsed=54.3s

  [3170/21087] intraday_11972.csv.gz  in=208,858,586 out=5,423,036 elapsed=54.3s

  [3171/21087] intraday_11973.csv.gz  in=208,869,301 out=5,433,751 elapsed=54.3s

  [3172/21087] intraday_11974.csv.gz  in=208,881,412 out=5,445,862 elapsed=54.4s

  [3173/21087] intraday_11975.csv.gz  in=208,894,418 out=5,458,868 elapsed=54.4s

  [3174/21087] intraday_11976.csv.gz  in=208,907,483 out=5,471,933 elapsed=54.4s

  [3175/21087] intraday_11977.csv.gz  in=208,919,831 out=5,484,281 elapsed=54.4s

  [3176/21087] intraday_11978.csv.gz  in=208,931,890 out=5,496,340 elapsed=54.4s

  [3177/21087] intraday_11979.csv.gz  in=208,943,685 out=5,508,135 elapsed=54.4s

  [3178/21087] intraday_1198.csv.gz  in=208,959,137 out=5,508,135 elapsed=54.4s

  [3179/21087] intraday_11980.csv.gz  in=208,978,174 out=5,520,378 elapsed=54.4s

  [3180/21087] intraday_11981.csv.gz  in=208,989,631 out=5,531,835 elapsed=54.4s

  [3181/21087] intraday_11982.csv.gz  in=209,002,619 out=5,544,823 elapsed=54.4s

  [3182/21087] intraday_11983.csv.gz  in=209,017,017 out=5,559,221 elapsed=54.5s

  [3183/21087] intraday_11984.csv.gz  in=209,030,441 out=5,572,645 elapsed=54.5s

  [3184/21087] intraday_11986.csv.gz  in=209,042,924 out=5,585,128 elapsed=54.5s

  [3185/21087] intraday_11987.csv.gz  in=209,056,234 out=5,598,438 elapsed=54.5s

  [3186/21087] intraday_11985.csv.gz  in=209,066,519 out=5,608,723 elapsed=54.5s

  [3187/21087] intraday_11988.csv.gz  in=209,080,089 out=5,622,293 elapsed=54.5s

  [3188/21087] intraday_1199.csv.gz  in=209,093,801 out=5,622,293 elapsed=54.6s

  [3189/21087] intraday_11990.csv.gz  in=209,104,913 out=5,633,405 elapsed=54.6s

  [3190/21087] intraday_11989.csv.gz  in=209,117,266 out=5,645,758 elapsed=54.6s

  [3191/21087] intraday_11991.csv.gz  in=209,128,652 out=5,657,144 elapsed=54.6s

  [3192/21087] intraday_11992.csv.gz  in=209,140,951 out=5,667,024 elapsed=54.6s

  [3193/21087] intraday_11993.csv.gz  in=209,152,242 out=5,678,315 elapsed=54.6s

  [3194/21087] intraday_11994.csv.gz  in=209,164,519 out=5,690,592 elapsed=54.6s

  [3195/21087] intraday_11995.csv.gz  in=209,178,046 out=5,704,119 elapsed=54.6s

  [3196/21087] intraday_11996.csv.gz  in=209,190,096 out=5,716,169 elapsed=54.6s

  [3197/21087] intraday_11997.csv.gz  in=209,206,682 out=5,729,885 elapsed=54.6s

  [3198/21087] intraday_11998.csv.gz  in=209,218,945 out=5,742,148 elapsed=54.6s

  [3199/21087] intraday_1200.csv.gz  in=209,242,201 out=5,742,148 elapsed=54.6s

  [3200/21087] intraday_11999.csv.gz  in=209,254,102 out=5,754,049 elapsed=54.6s

  [3201/21087] intraday_12001.csv.gz  in=209,266,683 out=5,766,630 elapsed=54.7s

  [3202/21087] intraday_12000.csv.gz  in=209,279,170 out=5,779,117 elapsed=54.7s

  [3203/21087] intraday_12003.csv.gz  in=209,291,821 out=5,791,768 elapsed=54.7s

  [3204/21087] intraday_12002.csv.gz  in=209,301,994 out=5,801,941 elapsed=54.7s

  [3205/21087] intraday_12004.csv.gz  in=209,312,779 out=5,812,726 elapsed=54.7s

  [3206/21087] intraday_12006.csv.gz  in=209,325,608 out=5,825,555 elapsed=54.7s

  [3207/21087] intraday_12005.csv.gz  in=209,336,323 out=5,836,270 elapsed=54.7s

  [3208/21087] intraday_12007.csv.gz  in=209,349,876 out=5,849,823 elapsed=54.8s

  [3209/21087] intraday_12008.csv.gz  in=209,362,220 out=5,862,167 elapsed=54.8s

  [3210/21087] intraday_12009.csv.gz  in=209,375,062 out=5,875,009 elapsed=54.8s

  [3211/21087] intraday_1201.csv.gz  in=209,388,192 out=5,875,009 elapsed=54.8s

  [3212/21087] intraday_12011.csv.gz  in=209,398,566 out=5,885,383 elapsed=54.8s

  [3213/21087] intraday_12010.csv.gz  in=209,411,445 out=5,898,262 elapsed=54.8s

  [3214/21087] intraday_12012.csv.gz  in=209,423,480 out=5,910,297 elapsed=54.8s

  [3215/21087] intraday_12013.csv.gz  in=209,436,059 out=5,922,876 elapsed=54.8s

  [3216/21087] intraday_12015.csv.gz  in=209,448,038 out=5,934,855 elapsed=54.8s

  [3217/21087] intraday_12017.csv.gz  in=209,457,877 out=5,944,694 elapsed=54.9s

  [3218/21087] intraday_12016.csv.gz  in=209,469,777 out=5,956,594 elapsed=54.9s

  [3219/21087] intraday_12014.csv.gz  in=209,481,183 out=5,968,000 elapsed=54.9s

  [3220/21087] intraday_12018.csv.gz  in=209,492,432 out=5,979,249 elapsed=54.9s

  [3221/21087] intraday_1202.csv.gz  in=209,505,942 out=5,979,249 elapsed=54.9s

  [3222/21087] intraday_12020.csv.gz  in=209,519,593 out=5,992,900 elapsed=54.9s

  [3223/21087] intraday_12022.csv.gz  in=209,532,038 out=6,005,345 elapsed=54.9s

  [3224/21087] intraday_12019.csv.gz  in=209,554,300 out=6,020,868 elapsed=54.9s

  [3225/21087] intraday_12021.csv.gz  in=209,568,497 out=6,034,975 elapsed=54.9s

  [3226/21087] intraday_12023.csv.gz  in=209,578,818 out=6,045,296 elapsed=55.0s

  [3227/21087] intraday_12024.csv.gz  in=209,590,705 out=6,057,183 elapsed=55.0s

  [3228/21087] intraday_12026.csv.gz  in=209,603,262 out=6,069,740 elapsed=55.0s

  [3229/21087] intraday_12025.csv.gz  in=209,616,120 out=6,082,598 elapsed=55.0s

  [3230/21087] intraday_12027.csv.gz  in=209,630,256 out=6,096,734 elapsed=55.0s

  [3231/21087] intraday_12029.csv.gz  in=209,641,112 out=6,107,590 elapsed=55.0s

  [3232/21087] intraday_1203.csv.gz  in=209,654,584 out=6,107,590 elapsed=55.0s

  [3233/21087] intraday_12028.csv.gz  in=209,666,902 out=6,119,908 elapsed=55.0s

  [3234/21087] intraday_12030.csv.gz  in=209,677,742 out=6,130,748 elapsed=55.0s

  [3235/21087] intraday_12032.csv.gz  in=209,689,813 out=6,142,819 elapsed=55.1s

  [3236/21087] intraday_12031.csv.gz  in=209,703,522 out=6,156,528 elapsed=55.1s

  [3237/21087] intraday_12033.csv.gz  in=209,715,339 out=6,168,345 elapsed=55.1s

  [3238/21087] intraday_12034.csv.gz  in=209,725,901 out=6,178,907 elapsed=55.1s

  [3239/21087] intraday_12035.csv.gz  in=209,735,497 out=6,188,503 elapsed=55.1s

  [3240/21087] intraday_12036.csv.gz  in=209,747,534 out=6,200,540 elapsed=55.1s

  [3241/21087] intraday_12037.csv.gz  in=209,763,158 out=6,216,164 elapsed=55.1s

  [3242/21087] intraday_1204.csv.gz  in=209,774,253 out=6,216,164 elapsed=55.1s

  [3243/21087] intraday_12038.csv.gz  in=209,792,908 out=6,234,819 elapsed=55.1s

  [3244/21087] intraday_12039.csv.gz  in=209,806,090 out=6,248,001 elapsed=55.1s

  [3245/21087] intraday_12041.csv.gz  in=209,816,533 out=6,258,444 elapsed=55.1s

  [3246/21087] intraday_12043.csv.gz  in=209,827,573 out=6,269,484 elapsed=55.2s

  [3247/21087] intraday_12040.csv.gz  in=209,839,366 out=6,281,277 elapsed=55.2s

  [3248/21087] intraday_12042.csv.gz  in=209,853,187 out=6,295,098 elapsed=55.2s

  [3249/21087] intraday_12044.csv.gz  in=209,868,634 out=6,310,545 elapsed=55.2s

  [3250/21087] intraday_12045.csv.gz  in=209,878,945 out=6,320,856 elapsed=55.2s

  [3251/21087] intraday_12046.csv.gz  in=209,890,853 out=6,332,764 elapsed=55.2s

  [3252/21087] intraday_12047.csv.gz  in=209,905,151 out=6,347,062 elapsed=55.2s

  [3253/21087] intraday_1205.csv.gz  in=209,919,235 out=6,347,062 elapsed=55.3s

  [3254/21087] intraday_12048.csv.gz  in=209,933,184 out=6,361,011 elapsed=55.3s

  [3255/21087] intraday_12049.csv.gz  in=209,945,820 out=6,373,647 elapsed=55.3s

  [3256/21087] intraday_12050.csv.gz  in=209,958,429 out=6,386,113 elapsed=55.3s

  [3257/21087] intraday_12051.csv.gz  in=209,971,505 out=6,399,189 elapsed=55.3s

  [3258/21087] intraday_12052.csv.gz  in=209,982,484 out=6,410,168 elapsed=55.3s

  [3259/21087] intraday_12053.csv.gz  in=209,993,477 out=6,421,161 elapsed=55.3s

  [3260/21087] intraday_12054.csv.gz  in=210,006,854 out=6,434,538 elapsed=55.3s

  [3261/21087] intraday_12055.csv.gz  in=210,018,871 out=6,446,555 elapsed=55.3s

  [3262/21087] intraday_12056.csv.gz  in=210,031,110 out=6,458,794 elapsed=55.3s

  [3263/21087] intraday_12057.csv.gz  in=210,044,646 out=6,472,330 elapsed=55.4s

  [3264/21087] intraday_12059.csv.gz  in=210,056,470 out=6,484,154 elapsed=55.4s

  [3265/21087] intraday_1206.csv.gz  in=210,074,138 out=6,484,154 elapsed=55.4s

  [3266/21087] intraday_12058.csv.gz  in=210,086,572 out=6,496,588 elapsed=55.4s

  [3267/21087] intraday_12062.csv.gz  in=210,098,799 out=6,508,815 elapsed=55.4s

  [3268/21087] intraday_12060.csv.gz  in=210,111,855 out=6,521,871 elapsed=55.4s

  [3269/21087] intraday_12061.csv.gz  in=210,125,549 out=6,535,565 elapsed=55.4s

  [3270/21087] intraday_12063.csv.gz  in=210,137,876 out=6,547,892 elapsed=55.4s

  [3271/21087] intraday_12064.csv.gz  in=210,151,299 out=6,561,315 elapsed=55.5s

  [3272/21087] intraday_12065.csv.gz  in=210,165,103 out=6,575,119 elapsed=55.5s

  [3273/21087] intraday_12067.csv.gz  in=210,179,374 out=6,589,390 elapsed=55.5s

  [3274/21087] intraday_12066.csv.gz  in=210,190,249 out=6,600,265 elapsed=55.5s

  [3275/21087] intraday_12068.csv.gz  in=210,208,436 out=6,618,452 elapsed=55.5s

  [3276/21087] intraday_1207.csv.gz  in=210,220,915 out=6,618,452 elapsed=55.5s

  [3277/21087] intraday_12069.csv.gz  in=210,234,461 out=6,631,998 elapsed=55.5s

  [3278/21087] intraday_12070.csv.gz  in=210,249,563 out=6,647,100 elapsed=55.5s

  [3279/21087] intraday_12072.csv.gz  in=210,264,450 out=6,661,987 elapsed=55.6s

  [3280/21087] intraday_12074.csv.gz  in=210,279,933 out=6,676,857 elapsed=55.6s

  [3281/21087] intraday_12073.csv.gz  in=210,295,493 out=6,692,417 elapsed=55.6s

  [3282/21087] intraday_12075.csv.gz  in=210,307,847 out=6,704,771 elapsed=55.6s

  [3283/21087] intraday_12071.csv.gz  in=210,324,773 out=6,721,697 elapsed=55.6s

  [3284/21087] intraday_12076.csv.gz  in=210,337,851 out=6,734,775 elapsed=55.6s

  [3285/21087] intraday_12077.csv.gz  in=210,349,982 out=6,746,906 elapsed=55.6s

  [3286/21087] intraday_12078.csv.gz  in=210,362,049 out=6,758,973 elapsed=55.6s

  [3287/21087] intraday_12079.csv.gz  in=210,373,950 out=6,770,874 elapsed=55.6s

  [3288/21087] intraday_1208.csv.gz  in=210,398,877 out=6,770,874 elapsed=55.7s

  [3289/21087] intraday_12081.csv.gz  in=210,411,890 out=6,783,887 elapsed=55.7s

  [3290/21087] intraday_12082.csv.gz  in=210,427,100 out=6,799,097 elapsed=55.7s

  [3291/21087] intraday_12080.csv.gz  in=210,439,637 out=6,811,634 elapsed=55.7s

  [3292/21087] intraday_12083.csv.gz  in=210,451,538 out=6,823,535 elapsed=55.7s

  [3293/21087] intraday_12084.csv.gz  in=210,462,154 out=6,834,151 elapsed=55.7s

  [3294/21087] intraday_12085.csv.gz  in=210,475,225 out=6,847,222 elapsed=55.7s

  [3295/21087] intraday_12086.csv.gz  in=210,485,895 out=6,857,892 elapsed=55.7s

  [3296/21087] intraday_12087.csv.gz  in=210,498,683 out=6,870,680 elapsed=55.7s

  [3297/21087] intraday_12088.csv.gz  in=210,512,976 out=6,884,973 elapsed=55.7s

  [3298/21087] intraday_12089.csv.gz  in=210,528,611 out=6,900,608 elapsed=55.7s

  [3299/21087] intraday_1209.csv.gz  in=210,545,934 out=6,900,608 elapsed=55.8s

  [3300/21087] intraday_12090.csv.gz  in=210,560,042 out=6,914,716 elapsed=55.8s

  [3301/21087] intraday_12091.csv.gz  in=210,574,378 out=6,929,052 elapsed=55.8s

  [3302/21087] intraday_12092.csv.gz  in=210,586,463 out=6,941,137 elapsed=55.8s

  [3303/21087] intraday_12093.csv.gz  in=210,599,329 out=6,954,003 elapsed=55.8s

  [3304/21087] intraday_12094.csv.gz  in=210,611,162 out=6,965,836 elapsed=55.8s

  [3305/21087] intraday_12097.csv.gz  in=210,618,285 out=6,972,896 elapsed=55.8s

  [3306/21087] intraday_12095.csv.gz  in=210,633,918 out=6,986,169 elapsed=55.8s

  [3307/21087] intraday_12096.csv.gz  in=210,642,871 out=6,995,122 elapsed=55.8s

  [3308/21087] intraday_12099.csv.gz  in=210,648,738 out=7,000,989 elapsed=55.9s

  [3309/21087] intraday_12098.csv.gz  in=210,660,731 out=7,012,982 elapsed=55.9s

  [3310/21087] intraday_1210.csv.gz  in=210,693,168 out=7,012,982 elapsed=55.9s

  [3311/21087] intraday_12103.csv.gz  in=210,933,153 out=7,033,698 elapsed=56.1s

  [3312/21087] intraday_12101.csv.gz  in=211,192,348 out=7,056,189 elapsed=56.1s

  [3313/21087] intraday_12100.csv.gz  in=211,520,049 out=7,089,483 elapsed=56.1s

  [3314/21087] intraday_12102.csv.gz  in=211,820,512 out=7,115,824 elapsed=56.1s

  [3315/21087] intraday_12105.csv.gz  in=212,134,721 out=7,144,270 elapsed=56.3s

  [3316/21087] intraday_12104.csv.gz  in=212,455,718 out=7,169,065 elapsed=56.3s

  [3317/21087] intraday_12107.csv.gz  in=212,725,299 out=7,193,272 elapsed=56.4s

  [3318/21087] intraday_12106.csv.gz  in=213,052,933 out=7,224,142 elapsed=56.4s

  [3319/21087] intraday_1211.csv.gz  in=213,064,749 out=7,224,142 elapsed=56.4s

  [3320/21087] intraday_12108.csv.gz  in=213,365,675 out=7,249,108 elapsed=56.6s

  [3321/21087] intraday_12111.csv.gz  in=213,642,508 out=7,272,711 elapsed=56.6s

  [3322/21087] intraday_12109.csv.gz  in=213,940,481 out=7,297,401 elapsed=56.6s

  [3323/21087] intraday_12110.csv.gz  in=214,254,888 out=7,321,889 elapsed=56.6s

  [3324/21087] intraday_12114.csv.gz  in=214,469,781 out=7,341,803 elapsed=56.8s

  [3325/21087] intraday_12112.csv.gz  in=214,733,480 out=7,369,353 elapsed=56.8s

  [3326/21087] intraday_12115.csv.gz  in=214,964,170 out=7,392,404 elapsed=56.8s

  [3327/21087] intraday_12113.csv.gz  in=215,251,420 out=7,418,851 elapsed=56.8s

  [3328/21087] intraday_12119.csv.gz  in=215,476,356 out=7,439,278 elapsed=57.0s

  [3329/21087] intraday_12116.csv.gz  in=215,797,920 out=7,468,572 elapsed=57.0s

  [3330/21087] intraday_12118.csv.gz  in=216,050,284 out=7,490,111 elapsed=57.0s

  [3331/21087] intraday_12117.csv.gz  in=216,347,678 out=7,515,370 elapsed=57.0s

  [3332/21087] intraday_1212.csv.gz  in=216,363,515 out=7,515,370 elapsed=57.0s

  [3333/21087] intraday_12122.csv.gz  in=216,614,631 out=7,541,483 elapsed=57.2s

  [3334/21087] intraday_12121.csv.gz  in=216,881,469 out=7,565,708 elapsed=57.2s

  [3335/21087] intraday_12123.csv.gz  in=217,162,499 out=7,591,280 elapsed=57.3s

  [3336/21087] intraday_12120.csv.gz  in=217,441,091 out=7,614,110 elapsed=57.3s

  [3337/21087] intraday_12124.csv.gz  in=217,720,659 out=7,640,047 elapsed=57.4s

  [3338/21087] intraday_12125.csv.gz  in=217,970,495 out=7,663,268 elapsed=57.4s

  [3339/21087] intraday_12126.csv.gz  in=218,194,535 out=7,684,943 elapsed=57.4s

  [3340/21087] intraday_12127.csv.gz  in=218,459,762 out=7,708,901 elapsed=57.5s

  [3341/21087] intraday_1213.csv.gz  in=218,481,451 out=7,708,901 elapsed=57.5s

  [3342/21087] intraday_12128.csv.gz  in=218,733,193 out=7,731,768 elapsed=57.6s

  [3343/21087] intraday_12131.csv.gz  in=219,005,536 out=7,756,793 elapsed=57.7s

  [3344/21087] intraday_12129.csv.gz  in=219,297,836 out=7,782,787 elapsed=57.7s

  [3345/21087] intraday_12130.csv.gz  in=219,683,536 out=7,813,034 elapsed=57.8s

  [3346/21087] intraday_12132.csv.gz  in=219,916,195 out=7,833,290 elapsed=57.8s

  [3347/21087] intraday_12133.csv.gz  in=220,214,766 out=7,860,036 elapsed=57.9s

  [3348/21087] intraday_12134.csv.gz  in=220,507,376 out=7,886,218 elapsed=57.9s

  [3349/21087] intraday_12135.csv.gz  in=220,761,145 out=7,910,892 elapsed=57.9s

  [3350/21087] intraday_12136.csv.gz  in=221,017,636 out=7,935,400 elapsed=58.0s

  [3351/21087] intraday_1214.csv.gz  in=221,033,314 out=7,935,400 elapsed=58.0s

  [3352/21087] intraday_12137.csv.gz  in=221,257,801 out=7,955,328 elapsed=58.1s

  [3353/21087] intraday_12139.csv.gz  in=221,484,570 out=7,976,492 elapsed=58.1s

  [3354/21087] intraday_12138.csv.gz  in=221,775,397 out=8,000,467 elapsed=58.1s

  [3355/21087] intraday_12140.csv.gz  in=222,020,234 out=8,021,919 elapsed=58.2s

  [3356/21087] intraday_12141.csv.gz  in=222,291,389 out=8,046,093 elapsed=58.3s

  [3357/21087] intraday_12142.csv.gz  in=222,558,052 out=8,070,411 elapsed=58.3s

  [3358/21087] intraday_12143.csv.gz  in=222,834,841 out=8,095,473 elapsed=58.3s

  [3359/21087] intraday_12144.csv.gz  in=223,139,207 out=8,123,034 elapsed=58.4s

  [3360/21087] intraday_12145.csv.gz  in=223,382,869 out=8,146,442 elapsed=58.4s

  [3361/21087] intraday_12146.csv.gz  in=223,626,012 out=8,168,464 elapsed=58.5s

  [3362/21087] intraday_1215.csv.gz  in=223,638,830 out=8,168,464 elapsed=58.5s

  [3363/21087] intraday_12147.csv.gz  in=223,928,735 out=8,194,560 elapsed=58.5s

  [3364/21087] intraday_12148.csv.gz  in=224,146,376 out=8,215,420 elapsed=58.6s

  [3365/21087] intraday_12149.csv.gz  in=224,385,444 out=8,238,453 elapsed=58.6s

  [3366/21087] intraday_12150.csv.gz  in=224,629,207 out=8,260,999 elapsed=58.7s

  [3367/21087] intraday_12151.csv.gz  in=224,849,074 out=8,281,282 elapsed=58.7s

  [3368/21087] intraday_12153.csv.gz  in=225,090,563 out=8,302,555 elapsed=58.8s

  [3369/21087] intraday_12152.csv.gz  in=225,427,243 out=8,330,578 elapsed=58.8s

  [3370/21087] intraday_12154.csv.gz  in=225,680,141 out=8,354,267 elapsed=58.9s

  [3371/21087] intraday_12155.csv.gz  in=225,987,689 out=8,382,423 elapsed=58.9s

  [3372/21087] intraday_12157.csv.gz  in=226,240,813 out=8,404,928 elapsed=59.0s

  [3373/21087] intraday_12156.csv.gz  in=226,523,504 out=8,430,554 elapsed=59.0s

  [3374/21087] intraday_1216.csv.gz  in=226,537,923 out=8,430,554 elapsed=59.0s

  [3375/21087] intraday_12158.csv.gz  in=226,807,839 out=8,453,342 elapsed=59.0s

  [3376/21087] intraday_12159.csv.gz  in=227,052,218 out=8,476,141 elapsed=59.1s

  [3377/21087] intraday_12161.csv.gz  in=227,290,102 out=8,498,555 elapsed=59.2s

  [3378/21087] intraday_12160.csv.gz  in=227,595,707 out=8,523,782 elapsed=59.2s

  [3379/21087] intraday_12162.csv.gz  in=227,847,719 out=8,546,797 elapsed=59.2s

  [3380/21087] intraday_12163.csv.gz  in=228,099,372 out=8,569,753 elapsed=59.3s

  [3381/21087] intraday_12164.csv.gz  in=228,320,836 out=8,589,245 elapsed=59.4s

  [3382/21087] intraday_12165.csv.gz  in=228,626,606 out=8,620,007 elapsed=59.4s

  [3383/21087] intraday_12166.csv.gz  in=228,930,578 out=8,648,189 elapsed=59.5s

  [3384/21087] intraday_12167.csv.gz  in=229,203,065 out=8,673,375 elapsed=59.5s

  [3385/21087] intraday_1217.csv.gz  in=229,217,505 out=8,673,375 elapsed=59.5s

  [3386/21087] intraday_12168.csv.gz  in=229,486,216 out=8,698,771 elapsed=59.6s

  [3387/21087] intraday_12169.csv.gz  in=229,750,975 out=8,722,970 elapsed=59.6s

  [3388/21087] intraday_12170.csv.gz  in=229,956,041 out=8,742,358 elapsed=59.6s

  [3389/21087] intraday_12171.csv.gz  in=230,228,579 out=8,768,170 elapsed=59.7s

  [3390/21087] intraday_12172.csv.gz  in=230,486,328 out=8,793,652 elapsed=59.7s

  [3391/21087] intraday_12173.csv.gz  in=230,760,392 out=8,820,884 elapsed=59.9s

  [3392/21087] intraday_12174.csv.gz  in=231,031,301 out=8,848,509 elapsed=59.9s

  [3393/21087] intraday_12175.csv.gz  in=231,276,048 out=8,871,243 elapsed=59.9s

  [3394/21087] intraday_12176.csv.gz  in=231,524,937 out=8,891,503 elapsed=59.9s

  [3395/21087] intraday_1218.csv.gz  in=231,547,219 out=8,891,503 elapsed=59.9s

  [3396/21087] intraday_12179.csv.gz  in=231,806,647 out=8,915,385 elapsed=60.1s

  [3397/21087] intraday_12177.csv.gz  in=232,070,775 out=8,939,398 elapsed=60.1s

  [3398/21087] intraday_12178.csv.gz  in=232,341,082 out=8,964,151 elapsed=60.1s

  [3399/21087] intraday_12180.csv.gz  in=232,613,557 out=8,988,117 elapsed=60.1s

  [3400/21087] intraday_12181.csv.gz  in=232,807,775 out=9,007,853 elapsed=60.3s

  [3401/21087] intraday_12182.csv.gz  in=233,053,758 out=9,029,032 elapsed=60.3s

  [3402/21087] intraday_12183.csv.gz  in=233,325,233 out=9,053,383 elapsed=60.3s

  [3403/21087] intraday_12184.csv.gz  in=233,701,035 out=9,088,732 elapsed=60.4s

  [3404/21087] intraday_12185.csv.gz  in=234,028,631 out=9,123,475 elapsed=60.6s

  [3405/21087] intraday_12187.csv.gz  in=234,294,407 out=9,147,267 elapsed=60.6s

  [3406/21087] intraday_12186.csv.gz  in=234,582,935 out=9,175,172 elapsed=60.6s

  [3407/21087] intraday_12188.csv.gz  in=234,853,270 out=9,198,683 elapsed=60.6s

  [3408/21087] intraday_1219.csv.gz  in=234,867,329 out=9,198,683 elapsed=60.6s

  [3409/21087] intraday_12189.csv.gz  in=235,149,352 out=9,222,569 elapsed=60.8s

  [3410/21087] intraday_12191.csv.gz  in=235,396,811 out=9,245,299 elapsed=60.8s

  [3411/21087] intraday_12192.csv.gz  in=235,652,361 out=9,266,301 elapsed=60.8s

  [3412/21087] intraday_12190.csv.gz  in=236,002,200 out=9,296,710 elapsed=60.8s

  [3413/21087] intraday_12193.csv.gz  in=236,303,666 out=9,324,062 elapsed=61.0s

  [3414/21087] intraday_12194.csv.gz  in=236,603,410 out=9,350,988 elapsed=61.0s

  [3415/21087] intraday_12195.csv.gz  in=236,903,274 out=9,377,230 elapsed=61.0s

  [3416/21087] intraday_12196.csv.gz  in=237,158,842 out=9,400,983 elapsed=61.0s

  [3417/21087] intraday_1220.csv.gz  in=237,179,804 out=9,400,983 elapsed=61.1s

  [3418/21087] intraday_12197.csv.gz  in=237,442,844 out=9,423,840 elapsed=61.2s

  [3419/21087] intraday_12199.csv.gz  in=237,685,144 out=9,442,692 elapsed=61.2s

  [3420/21087] intraday_12198.csv.gz  in=237,955,374 out=9,467,448 elapsed=61.2s

  [3421/21087] intraday_12200.csv.gz  in=238,290,213 out=9,494,778 elapsed=61.3s

  [3422/21087] intraday_12201.csv.gz  in=238,518,712 out=9,514,018 elapsed=61.3s

  [3423/21087] intraday_12202.csv.gz  in=238,805,947 out=9,539,650 elapsed=61.4s

  [3424/21087] intraday_12203.csv.gz  in=239,120,049 out=9,567,956 elapsed=61.4s

  [3425/21087] intraday_12204.csv.gz  in=239,414,823 out=9,592,233 elapsed=61.5s

  [3426/21087] intraday_12205.csv.gz  in=239,646,734 out=9,618,780 elapsed=61.5s

  [3427/21087] intraday_12206.csv.gz  in=239,920,235 out=9,643,419 elapsed=61.6s

  [3428/21087] intraday_1221.csv.gz  in=239,935,724 out=9,643,419 elapsed=61.6s

  [3429/21087] intraday_12207.csv.gz  in=240,268,815 out=9,673,776 elapsed=61.7s

  [3430/21087] intraday_12209.csv.gz  in=240,521,291 out=9,695,710 elapsed=61.7s

  [3431/21087] intraday_12208.csv.gz  in=240,788,048 out=9,718,878 elapsed=61.7s

  [3432/21087] intraday_12210.csv.gz  in=241,121,091 out=9,747,943 elapsed=61.9s

  [3433/21087] intraday_12213.csv.gz  in=241,397,306 out=9,773,686 elapsed=61.9s

  [3434/21087] intraday_12212.csv.gz  in=241,663,964 out=9,796,233 elapsed=61.9s

  [3435/21087] intraday_12211.csv.gz  in=241,982,222 out=9,825,902 elapsed=61.9s

  [3436/21087] intraday_12214.csv.gz  in=242,251,198 out=9,861,258 elapsed=62.1s

  [3437/21087] intraday_12215.csv.gz  in=242,491,876 out=9,884,359 elapsed=62.1s

  [3438/21087] intraday_12216.csv.gz  in=242,821,382 out=9,912,798 elapsed=62.2s

  [3439/21087] intraday_12217.csv.gz  in=243,161,414 out=9,943,946 elapsed=62.2s

  [3440/21087] intraday_1222.csv.gz  in=243,173,542 out=9,943,946 elapsed=62.2s

  [3441/21087] intraday_12218.csv.gz  in=243,467,450 out=9,979,017 elapsed=62.3s

  [3442/21087] intraday_12219.csv.gz  in=243,765,136 out=10,007,635 elapsed=62.3s

  [3443/21087] intraday_12221.csv.gz  in=243,995,494 out=10,032,916 elapsed=62.4s

  [3444/21087] intraday_12220.csv.gz  in=244,335,193 out=10,064,033 elapsed=62.4s

  [3445/21087] intraday_12223.csv.gz  in=244,565,889 out=10,085,678 elapsed=62.5s

  [3446/21087] intraday_12222.csv.gz  in=244,833,073 out=10,110,021 elapsed=62.5s

  [3447/21087] intraday_12224.csv.gz  in=245,139,181 out=10,137,633 elapsed=62.6s

  [3448/21087] intraday_12225.csv.gz  in=245,373,590 out=10,158,784 elapsed=62.6s

  [3449/21087] intraday_12227.csv.gz  in=245,650,958 out=10,185,175 elapsed=62.7s

  [3450/21087] intraday_12226.csv.gz  in=245,960,860 out=10,212,081 elapsed=62.7s

  [3451/21087] intraday_1223.csv.gz  in=245,974,321 out=10,212,081 elapsed=62.7s

  [3452/21087] intraday_12229.csv.gz  in=246,230,009 out=10,234,543 elapsed=62.8s

  [3453/21087] intraday_12228.csv.gz  in=246,568,706 out=10,264,088 elapsed=62.8s

  [3454/21087] intraday_12230.csv.gz  in=246,831,158 out=10,285,588 elapsed=62.9s

  [3455/21087] intraday_12231.csv.gz  in=247,093,409 out=10,308,450 elapsed=62.9s

  [3456/21087] intraday_12233.csv.gz  in=247,329,262 out=10,329,737 elapsed=63.0s

  [3457/21087] intraday_12232.csv.gz  in=247,648,535 out=10,355,622 elapsed=63.0s

  [3458/21087] intraday_12234.csv.gz  in=247,921,041 out=10,381,157 elapsed=63.1s

  [3459/21087] intraday_12235.csv.gz  in=248,242,467 out=10,412,990 elapsed=63.2s

  [3460/21087] intraday_12236.csv.gz  in=248,535,824 out=10,439,220 elapsed=63.2s

  [3461/21087] intraday_1224.csv.gz  in=248,547,752 out=10,439,220 elapsed=63.2s

  [3462/21087] intraday_12237.csv.gz  in=248,870,513 out=10,470,373 elapsed=63.3s

  [3463/21087] intraday_12238.csv.gz  in=249,126,005 out=10,494,463 elapsed=63.3s

  [3464/21087] intraday_12239.csv.gz  in=249,374,765 out=10,518,094 elapsed=63.3s

  [3465/21087] intraday_12240.csv.gz  in=249,652,365 out=10,541,483 elapsed=63.4s

  [3466/21087] intraday_12241.csv.gz  in=249,903,085 out=10,564,421 elapsed=63.5s

  [3467/21087] intraday_12243.csv.gz  in=250,111,178 out=10,579,185 elapsed=63.5s

  [3468/21087] intraday_12246.csv.gz  in=250,114,964 out=10,579,489 elapsed=63.5s

  [3469/21087] intraday_12242.csv.gz  in=250,410,235 out=10,603,758 elapsed=63.5s

  [3470/21087] intraday_12247.csv.gz  in=250,412,650 out=10,604,276 elapsed=63.5s

  [3471/21087] intraday_12249.csv.gz  in=250,417,359 out=10,605,327 elapsed=63.6s

  [3472/21087] intraday_12248.csv.gz  in=250,418,594 out=10,605,469 elapsed=63.6s

  [3473/21087] intraday_12250.csv.gz  in=250,426,685 out=10,605,961 elapsed=63.6s

  [3474/21087] intraday_1225.csv.gz  in=250,439,526 out=10,605,961 elapsed=63.6s

  [3475/21087] intraday_12251.csv.gz  in=250,440,045 out=10,606,027 elapsed=63.6s

  [3476/21087] intraday_12252.csv.gz  in=250,441,040 out=10,606,166 elapsed=63.6s

  [3477/21087] intraday_12244.csv.gz  in=250,637,107 out=10,625,124 elapsed=63.6s

  [3478/21087] intraday_12255.csv.gz  in=250,637,324 out=10,625,155 elapsed=63.6s

  [3479/21087] intraday_12254.csv.gz  in=250,640,384 out=10,625,350 elapsed=63.6s

  [3480/21087] intraday_12253.csv.gz  in=250,653,186 out=10,627,398 elapsed=63.6s

  [3481/21087] intraday_12256.csv.gz  in=250,654,836 out=10,627,764 elapsed=63.7s

  [3482/21087] intraday_12257.csv.gz  in=250,655,726 out=10,627,863 elapsed=63.7s

  [3483/21087] intraday_12258.csv.gz  in=250,658,148 out=10,628,091 elapsed=63.7s

  [3484/21087] intraday_12245.csv.gz  in=250,932,259 out=10,655,070 elapsed=63.7s

  [3485/21087] intraday_12259.csv.gz  in=250,932,374 out=10,655,072 elapsed=63.7s

  [3486/21087] intraday_12260.csv.gz  in=250,932,639 out=10,655,168 elapsed=63.7s

  [3487/21087] intraday_1226.csv.gz  in=250,943,267 out=10,655,168 elapsed=63.7s

  [3488/21087] intraday_12261.csv.gz  in=250,944,107 out=10,655,247 elapsed=63.7s

  [3489/21087] intraday_12262.csv.gz  in=250,945,325 out=10,655,482 elapsed=63.7s

  [3490/21087] intraday_12264.csv.gz  in=250,945,415 out=10,655,495 elapsed=63.7s

  [3491/21087] intraday_12263.csv.gz  in=250,951,802 out=10,656,773 elapsed=63.7s

  [3492/21087] intraday_12265.csv.gz  in=250,953,650 out=10,657,108 elapsed=63.7s

  [3493/21087] intraday_12267.csv.gz  in=250,954,118 out=10,657,108 elapsed=63.7s

  [3494/21087] intraday_12266.csv.gz  in=250,957,297 out=10,657,472 elapsed=63.7s

  [3495/21087] intraday_12268.csv.gz  in=250,960,177 out=10,657,756 elapsed=63.7s

  [3496/21087] intraday_12269.csv.gz  in=250,963,823 out=10,658,267 elapsed=63.8s

  [3497/21087] intraday_12270.csv.gz  in=250,965,549 out=10,658,501 elapsed=63.8s

  [3498/21087] intraday_1227.csv.gz  in=250,979,780 out=10,658,501 elapsed=63.8s

  [3499/21087] intraday_12271.csv.gz  in=250,986,611 out=10,659,203 elapsed=63.8s

  [3500/21087] intraday_12273.csv.gz  in=250,991,470 out=10,659,203 elapsed=63.8s

  [3501/21087] intraday_12272.csv.gz  in=250,993,699 out=10,659,510 elapsed=63.8s

  [3502/21087] intraday_12274.csv.gz  in=250,994,258 out=10,659,650 elapsed=63.8s

  [3503/21087] intraday_12275.csv.gz  in=250,994,745 out=10,659,708 elapsed=63.8s

  [3504/21087] intraday_12277.csv.gz  in=251,007,885 out=10,672,848 elapsed=63.9s

  [3505/21087] intraday_12279.csv.gz  in=251,018,237 out=10,683,200 elapsed=63.9s

  [3506/21087] intraday_12276.csv.gz  in=251,034,671 out=10,699,634 elapsed=63.9s

  [3507/21087] intraday_1228.csv.gz  in=251,042,935 out=10,699,634 elapsed=63.9s

  [3508/21087] intraday_12278.csv.gz  in=251,055,347 out=10,712,046 elapsed=63.9s

  [3509/21087] intraday_12280.csv.gz  in=251,067,663 out=10,724,362 elapsed=63.9s

  [3510/21087] intraday_12283.csv.gz  in=251,080,534 out=10,737,233 elapsed=63.9s

  [3511/21087] intraday_12282.csv.gz  in=251,094,759 out=10,751,458 elapsed=63.9s

  [3512/21087] intraday_12281.csv.gz  in=251,109,950 out=10,766,649 elapsed=63.9s

  [3513/21087] intraday_12284.csv.gz  in=251,122,989 out=10,779,688 elapsed=64.0s

  [3514/21087] intraday_12285.csv.gz  in=251,135,959 out=10,792,658 elapsed=64.0s

  [3515/21087] intraday_12286.csv.gz  in=251,148,219 out=10,804,918 elapsed=64.0s

  [3516/21087] intraday_12287.csv.gz  in=251,160,056 out=10,816,755 elapsed=64.0s

  [3517/21087] intraday_12288.csv.gz  in=251,174,256 out=10,830,955 elapsed=64.0s

  [3518/21087] intraday_12289.csv.gz  in=251,188,333 out=10,845,032 elapsed=64.0s

  [3519/21087] intraday_1229.csv.gz  in=251,199,030 out=10,845,032 elapsed=64.0s

  [3520/21087] intraday_12290.csv.gz  in=251,209,547 out=10,855,549 elapsed=64.0s

  [3521/21087] intraday_12291.csv.gz  in=251,219,712 out=10,865,714 elapsed=64.0s

  [3522/21087] intraday_12292.csv.gz  in=251,234,045 out=10,880,047 elapsed=64.1s

  [3523/21087] intraday_12293.csv.gz  in=251,246,628 out=10,892,630 elapsed=64.1s

  [3524/21087] intraday_12294.csv.gz  in=251,258,187 out=10,904,189 elapsed=64.1s

  [3525/21087] intraday_12295.csv.gz  in=251,269,475 out=10,915,477 elapsed=64.1s

  [3526/21087] intraday_12296.csv.gz  in=251,280,333 out=10,926,335 elapsed=64.1s

  [3527/21087] intraday_12297.csv.gz  in=251,292,955 out=10,938,957 elapsed=64.1s

  [3528/21087] intraday_1230.csv.gz  in=251,304,551 out=10,938,957 elapsed=64.1s

  [3529/21087] intraday_12299.csv.gz  in=251,315,620 out=10,950,026 elapsed=64.1s

  [3530/21087] intraday_12298.csv.gz  in=251,329,037 out=10,963,443 elapsed=64.1s

  [3531/21087] intraday_12300.csv.gz  in=251,341,564 out=10,975,970 elapsed=64.1s

  [3532/21087] intraday_12301.csv.gz  in=251,352,971 out=10,987,377 elapsed=64.2s

  [3533/21087] intraday_12303.csv.gz  in=251,364,600 out=10,999,006 elapsed=64.2s

  [3534/21087] intraday_12302.csv.gz  in=251,377,237 out=11,011,643 elapsed=64.2s

  [3535/21087] intraday_12304.csv.gz  in=251,389,006 out=11,023,412 elapsed=64.2s

  [3536/21087] intraday_12305.csv.gz  in=251,402,168 out=11,036,574 elapsed=64.2s

  [3537/21087] intraday_12307.csv.gz  in=251,415,600 out=11,050,006 elapsed=64.2s

  [3538/21087] intraday_12306.csv.gz  in=251,430,606 out=11,065,012 elapsed=64.2s

  [3539/21087] intraday_12308.csv.gz  in=251,440,822 out=11,075,228 elapsed=64.2s

  [3540/21087] intraday_12309.csv.gz  in=251,454,947 out=11,089,353 elapsed=64.2s

  [3541/21087] intraday_1231.csv.gz  in=251,470,226 out=11,089,353 elapsed=64.3s

  [3542/21087] intraday_12310.csv.gz  in=251,483,522 out=11,102,649 elapsed=64.3s

  [3543/21087] intraday_12311.csv.gz  in=251,497,114 out=11,116,241 elapsed=64.3s

  [3544/21087] intraday_12312.csv.gz  in=251,509,522 out=11,128,649 elapsed=64.3s

  [3545/21087] intraday_12313.csv.gz  in=251,519,558 out=11,138,685 elapsed=64.3s

  [3546/21087] intraday_12314.csv.gz  in=251,532,111 out=11,151,238 elapsed=64.3s

  [3547/21087] intraday_12316.csv.gz  in=251,542,667 out=11,161,794 elapsed=64.3s

  [3548/21087] intraday_12315.csv.gz  in=251,552,215 out=11,171,342 elapsed=64.3s

  [3549/21087] intraday_12317.csv.gz  in=251,565,546 out=11,184,673 elapsed=64.3s

  [3550/21087] intraday_12318.csv.gz  in=251,577,843 out=11,196,970 elapsed=64.3s

  [3551/21087] intraday_1232.csv.gz  in=251,592,356 out=11,196,970 elapsed=64.4s

  [3552/21087] intraday_12319.csv.gz  in=251,604,339 out=11,208,953 elapsed=64.4s

  [3553/21087] intraday_12320.csv.gz  in=251,617,915 out=11,222,529 elapsed=64.4s

  [3554/21087] intraday_12321.csv.gz  in=251,630,692 out=11,235,306 elapsed=64.4s

  [3555/21087] intraday_12322.csv.gz  in=251,643,005 out=11,247,619 elapsed=64.4s

  [3556/21087] intraday_12323.csv.gz  in=251,655,392 out=11,260,006 elapsed=64.4s

  [3557/21087] intraday_12324.csv.gz  in=251,670,015 out=11,274,629 elapsed=64.4s

  [3558/21087] intraday_12325.csv.gz  in=251,680,153 out=11,284,767 elapsed=64.4s

  [3559/21087] intraday_12326.csv.gz  in=251,692,034 out=11,296,648 elapsed=64.4s

  [3560/21087] intraday_12327.csv.gz  in=251,701,098 out=11,305,712 elapsed=64.4s

  [3561/21087] intraday_12328.csv.gz  in=251,714,856 out=11,319,470 elapsed=64.5s

  [3562/21087] intraday_1233.csv.gz  in=251,726,057 out=11,319,470 elapsed=64.5s

  [3563/21087] intraday_12329.csv.gz  in=251,736,412 out=11,329,825 elapsed=64.5s

  [3564/21087] intraday_12330.csv.gz  in=251,749,008 out=11,342,421 elapsed=64.5s

  [3565/21087] intraday_12332.csv.gz  in=251,761,274 out=11,354,687 elapsed=64.5s

  [3566/21087] intraday_12334.csv.gz  in=251,772,025 out=11,365,438 elapsed=64.5s

  [3567/21087] intraday_12333.csv.gz  in=251,783,343 out=11,376,756 elapsed=64.5s

  [3568/21087] intraday_12331.csv.gz  in=251,797,691 out=11,391,104 elapsed=64.5s

  [3569/21087] intraday_12335.csv.gz  in=251,809,789 out=11,403,202 elapsed=64.5s

  [3570/21087] intraday_12337.csv.gz  in=251,822,284 out=11,415,697 elapsed=64.6s

  [3571/21087] intraday_12336.csv.gz  in=251,834,168 out=11,427,581 elapsed=64.6s

  [3572/21087] intraday_12339.csv.gz  in=251,846,632 out=11,440,045 elapsed=64.6s

  [3573/21087] intraday_12338.csv.gz  in=251,857,849 out=11,451,262 elapsed=64.6s

  [3574/21087] intraday_1234.csv.gz  in=251,869,147 out=11,451,262 elapsed=64.6s

  [3575/21087] intraday_12340.csv.gz  in=251,878,482 out=11,460,597 elapsed=64.6s

  [3576/21087] intraday_12341.csv.gz  in=251,893,228 out=11,475,343 elapsed=64.6s

  [3577/21087] intraday_12342.csv.gz  in=251,908,653 out=11,490,768 elapsed=64.6s

  [3578/21087] intraday_12343.csv.gz  in=251,920,715 out=11,502,830 elapsed=64.6s

  [3579/21087] intraday_12344.csv.gz  in=251,934,528 out=11,516,643 elapsed=64.6s

  [3580/21087] intraday_12345.csv.gz  in=251,947,001 out=11,529,116 elapsed=64.7s

  [3581/21087] intraday_12347.csv.gz  in=251,960,453 out=11,542,568 elapsed=64.7s

  [3582/21087] intraday_12346.csv.gz  in=251,970,569 out=11,552,684 elapsed=64.7s

  [3583/21087] intraday_12348.csv.gz  in=251,983,478 out=11,565,593 elapsed=64.7s

  [3584/21087] intraday_12349.csv.gz  in=251,996,245 out=11,578,360 elapsed=64.7s

  [3585/21087] intraday_1235.csv.gz  in=252,010,748 out=11,578,360 elapsed=64.7s

  [3586/21087] intraday_12350.csv.gz  in=252,024,413 out=11,592,025 elapsed=64.7s

  [3587/21087] intraday_12351.csv.gz  in=252,036,277 out=11,603,889 elapsed=64.7s

  [3588/21087] intraday_12352.csv.gz  in=252,047,502 out=11,615,114 elapsed=64.7s

  [3589/21087] intraday_12353.csv.gz  in=252,058,814 out=11,626,426 elapsed=64.7s

  [3590/21087] intraday_12354.csv.gz  in=252,072,432 out=11,640,044 elapsed=64.8s

  [3591/21087] intraday_12355.csv.gz  in=252,084,647 out=11,652,259 elapsed=64.8s

  [3592/21087] intraday_12356.csv.gz  in=252,096,393 out=11,664,005 elapsed=64.8s

  [3593/21087] intraday_12357.csv.gz  in=252,107,947 out=11,675,559 elapsed=64.8s

  [3594/21087] intraday_12358.csv.gz  in=252,119,214 out=11,686,826 elapsed=64.8s

  [3595/21087] intraday_12359.csv.gz  in=252,131,448 out=11,699,060 elapsed=64.8s

  [3596/21087] intraday_1236.csv.gz  in=252,145,501 out=11,699,060 elapsed=64.8s

  [3597/21087] intraday_12360.csv.gz  in=252,161,250 out=11,714,809 elapsed=64.8s

  [3598/21087] intraday_12362.csv.gz  in=252,174,561 out=11,728,120 elapsed=64.8s

  [3599/21087] intraday_12361.csv.gz  in=252,191,950 out=11,745,509 elapsed=64.9s

  [3600/21087] intraday_12363.csv.gz  in=252,203,885 out=11,757,444 elapsed=64.9s

  [3601/21087] intraday_12364.csv.gz  in=252,215,396 out=11,768,955 elapsed=64.9s

  [3602/21087] intraday_12365.csv.gz  in=252,227,796 out=11,781,355 elapsed=64.9s

  [3603/21087] intraday_12367.csv.gz  in=252,238,552 out=11,792,111 elapsed=64.9s

  [3604/21087] intraday_12368.csv.gz  in=252,249,544 out=11,803,103 elapsed=64.9s

  [3605/21087] intraday_12366.csv.gz  in=252,264,312 out=11,817,871 elapsed=64.9s

  [3606/21087] intraday_1237.csv.gz  in=252,276,627 out=11,817,871 elapsed=64.9s

  [3607/21087] intraday_12369.csv.gz  in=252,292,116 out=11,833,360 elapsed=64.9s

  [3608/21087] intraday_12370.csv.gz  in=252,304,549 out=11,845,793 elapsed=65.0s

  [3609/21087] intraday_12373.csv.gz  in=252,315,677 out=11,856,921 elapsed=65.0s

  [3610/21087] intraday_12372.csv.gz  in=252,328,576 out=11,869,820 elapsed=65.0s

  [3611/21087] intraday_12371.csv.gz  in=252,341,092 out=11,882,336 elapsed=65.0s

  [3612/21087] intraday_12374.csv.gz  in=252,353,981 out=11,895,225 elapsed=65.0s

  [3613/21087] intraday_12377.csv.gz  in=252,364,891 out=11,906,135 elapsed=65.0s

  [3614/21087] intraday_12375.csv.gz  in=252,378,357 out=11,919,601 elapsed=65.0s

  [3615/21087] intraday_12376.csv.gz  in=252,390,012 out=11,931,256 elapsed=65.0s

  [3616/21087] intraday_12378.csv.gz  in=252,403,584 out=11,944,828 elapsed=65.0s

  [3617/21087] intraday_1238.csv.gz  in=252,415,684 out=11,944,828 elapsed=65.1s

  [3618/21087] intraday_12379.csv.gz  in=252,429,448 out=11,958,592 elapsed=65.1s

  [3619/21087] intraday_12381.csv.gz  in=252,442,127 out=11,971,271 elapsed=65.1s

  [3620/21087] intraday_12382.csv.gz  in=252,455,145 out=11,984,289 elapsed=65.1s

  [3621/21087] intraday_12380.csv.gz  in=252,469,865 out=11,997,375 elapsed=65.1s

  [3622/21087] intraday_12383.csv.gz  in=252,485,214 out=12,012,724 elapsed=65.1s

  [3623/21087] intraday_12384.csv.gz  in=252,496,233 out=12,023,743 elapsed=65.1s

  [3624/21087] intraday_12385.csv.gz  in=252,508,683 out=12,036,193 elapsed=65.1s

  [3625/21087] intraday_12386.csv.gz  in=252,522,842 out=12,050,352 elapsed=65.1s

  [3626/21087] intraday_12387.csv.gz  in=252,537,933 out=12,065,443 elapsed=65.1s

  [3627/21087] intraday_12388.csv.gz  in=252,549,718 out=12,077,228 elapsed=65.2s

  [3628/21087] intraday_12389.csv.gz  in=252,563,015 out=12,090,525 elapsed=65.2s

  [3629/21087] intraday_1239.csv.gz  in=252,577,723 out=12,090,525 elapsed=65.2s

  [3630/21087] intraday_12390.csv.gz  in=252,593,162 out=12,105,964 elapsed=65.2s

  [3631/21087] intraday_12392.csv.gz  in=252,607,170 out=12,119,972 elapsed=65.2s

  [3632/21087] intraday_12391.csv.gz  in=252,620,401 out=12,133,203 elapsed=65.2s

  [3633/21087] intraday_12393.csv.gz  in=252,636,731 out=12,149,533 elapsed=65.2s

  [3634/21087] intraday_12394.csv.gz  in=252,655,323 out=12,168,125 elapsed=65.2s

  [3635/21087] intraday_12395.csv.gz  in=252,668,907 out=12,181,709 elapsed=65.2s

  [3636/21087] intraday_12396.csv.gz  in=252,685,433 out=12,198,235 elapsed=65.3s

  [3637/21087] intraday_12398.csv.gz  in=252,697,753 out=12,210,555 elapsed=65.3s

  [3638/21087] intraday_12399.csv.gz  in=252,710,345 out=12,223,147 elapsed=65.3s

  [3639/21087] intraday_12397.csv.gz  in=252,744,865 out=12,237,443 elapsed=65.3s

  [3640/21087] intraday_1240.csv.gz  in=252,758,923 out=12,237,443 elapsed=65.3s

  [3641/21087] intraday_12400.csv.gz  in=252,771,355 out=12,249,875 elapsed=65.3s

  [3642/21087] intraday_12401.csv.gz  in=252,782,233 out=12,260,753 elapsed=65.3s

  [3643/21087] intraday_12402.csv.gz  in=252,795,345 out=12,273,865 elapsed=65.3s

  [3644/21087] intraday_12403.csv.gz  in=252,807,016 out=12,285,536 elapsed=65.3s

  [3645/21087] intraday_12404.csv.gz  in=252,822,870 out=12,301,390 elapsed=65.3s

  [3646/21087] intraday_12405.csv.gz  in=252,833,431 out=12,311,951 elapsed=65.4s

  [3647/21087] intraday_12406.csv.gz  in=252,844,692 out=12,323,212 elapsed=65.4s

  [3648/21087] intraday_12407.csv.gz  in=252,856,395 out=12,334,915 elapsed=65.4s

  [3649/21087] intraday_12408.csv.gz  in=252,870,711 out=12,349,231 elapsed=65.4s

  [3650/21087] intraday_1241.csv.gz  in=252,880,482 out=12,349,231 elapsed=65.4s

  [3651/21087] intraday_12409.csv.gz  in=252,891,080 out=12,359,829 elapsed=65.4s

  [3652/21087] intraday_12410.csv.gz  in=252,904,800 out=12,373,549 elapsed=65.4s

  [3653/21087] intraday_12411.csv.gz  in=252,919,435 out=12,388,184 elapsed=65.4s

  [3654/21087] intraday_12412.csv.gz  in=252,933,737 out=12,402,486 elapsed=65.4s

  [3655/21087] intraday_12413.csv.gz  in=252,947,687 out=12,416,436 elapsed=65.4s

  [3656/21087] intraday_12415.csv.gz  in=252,959,403 out=12,428,152 elapsed=65.5s

  [3657/21087] intraday_12414.csv.gz  in=252,973,648 out=12,442,397 elapsed=65.5s

  [3658/21087] intraday_12417.csv.gz  in=252,983,982 out=12,452,731 elapsed=65.5s

  [3659/21087] intraday_12416.csv.gz  in=252,996,602 out=12,465,351 elapsed=65.5s

  [3660/21087] intraday_12419.csv.gz  in=253,004,637 out=12,473,386 elapsed=65.5s

  [3661/21087] intraday_1242.csv.gz  in=253,019,623 out=12,473,386 elapsed=65.5s

  [3662/21087] intraday_12418.csv.gz  in=253,032,719 out=12,486,482 elapsed=65.5s

  [3663/21087] intraday_12420.csv.gz  in=253,040,331 out=12,494,094 elapsed=65.5s

  [3664/21087] intraday_12422.csv.gz  in=253,043,944 out=12,497,707 elapsed=65.6s

  [3665/21087] intraday_12424.csv.gz  in=253,056,828 out=12,510,591 elapsed=65.6s

  [3666/21087] intraday_12421.csv.gz  in=253,070,389 out=12,524,152 elapsed=65.6s

  [3667/21087] intraday_12423.csv.gz  in=253,088,474 out=12,542,237 elapsed=65.6s

  [3668/21087] intraday_12425.csv.gz  in=253,102,867 out=12,556,630 elapsed=65.6s

  [3669/21087] intraday_12427.csv.gz  in=253,115,147 out=12,568,910 elapsed=65.6s

  [3670/21087] intraday_12426.csv.gz  in=253,127,389 out=12,580,383 elapsed=65.6s

  [3671/21087] intraday_12428.csv.gz  in=253,142,244 out=12,595,238 elapsed=65.7s

  [3672/21087] intraday_12429.csv.gz  in=253,161,412 out=12,614,406 elapsed=65.7s

  [3673/21087] intraday_1243.csv.gz  in=253,176,682 out=12,614,406 elapsed=65.7s

  [3674/21087] intraday_12430.csv.gz  in=253,188,243 out=12,625,967 elapsed=65.7s

  [3675/21087] intraday_12431.csv.gz  in=253,202,184 out=12,639,908 elapsed=65.7s

  [3676/21087] intraday_12432.csv.gz  in=253,216,449 out=12,654,173 elapsed=65.7s

  [3677/21087] intraday_12433.csv.gz  in=253,229,838 out=12,667,562 elapsed=65.7s

  [3678/21087] intraday_12434.csv.gz  in=253,242,928 out=12,680,652 elapsed=65.7s

  [3679/21087] intraday_12435.csv.gz  in=253,257,019 out=12,694,743 elapsed=65.7s

  [3680/21087] intraday_12436.csv.gz  in=253,271,194 out=12,708,918 elapsed=65.7s

  [3681/21087] intraday_12437.csv.gz  in=253,293,466 out=12,720,545 elapsed=65.8s

  [3682/21087] intraday_1244.csv.gz  in=253,304,523 out=12,720,545 elapsed=65.8s

  [3683/21087] intraday_12439.csv.gz  in=253,319,279 out=12,735,145 elapsed=65.8s

  [3684/21087] intraday_12438.csv.gz  in=253,332,154 out=12,747,050 elapsed=65.8s

  [3685/21087] intraday_12440.csv.gz  in=253,345,750 out=12,760,646 elapsed=65.8s

  [3686/21087] intraday_12441.csv.gz  in=253,356,574 out=12,771,470 elapsed=65.8s

  [3687/21087] intraday_12443.csv.gz  in=253,368,020 out=12,782,916 elapsed=65.8s

  [3688/21087] intraday_12442.csv.gz  in=253,378,660 out=12,793,556 elapsed=65.8s

  [3689/21087] intraday_12444.csv.gz  in=253,391,464 out=12,806,360 elapsed=65.8s

  [3690/21087] intraday_12445.csv.gz  in=253,404,027 out=12,818,923 elapsed=65.8s

  [3691/21087] intraday_12446.csv.gz  in=253,416,350 out=12,831,246 elapsed=65.9s

  [3692/21087] intraday_12447.csv.gz  in=253,429,188 out=12,844,084 elapsed=65.9s

  [3693/21087] intraday_1245.csv.gz  in=253,439,869 out=12,844,084 elapsed=65.9s

  [3694/21087] intraday_12449.csv.gz  in=253,453,384 out=12,857,599 elapsed=65.9s

  [3695/21087] intraday_12448.csv.gz  in=253,465,215 out=12,869,430 elapsed=65.9s

  [3696/21087] intraday_12450.csv.gz  in=253,477,210 out=12,881,425 elapsed=65.9s

  [3697/21087] intraday_12452.csv.gz  in=253,490,641 out=12,894,856 elapsed=65.9s

  [3698/21087] intraday_12451.csv.gz  in=253,502,552 out=12,906,767 elapsed=65.9s

  [3699/21087] intraday_12453.csv.gz  in=253,518,670 out=12,922,885 elapsed=65.9s

  [3700/21087] intraday_12454.csv.gz  in=253,532,816 out=12,937,031 elapsed=65.9s

  [3701/21087] intraday_12455.csv.gz  in=253,543,320 out=12,947,535 elapsed=66.0s

  [3702/21087] intraday_12456.csv.gz  in=253,558,192 out=12,962,407 elapsed=66.0s

  [3703/21087] intraday_12457.csv.gz  in=253,574,238 out=12,975,959 elapsed=66.0s

  [3704/21087] intraday_12458.csv.gz  in=253,588,525 out=12,990,246 elapsed=66.0s

  [3705/21087] intraday_12459.csv.gz  in=253,600,465 out=13,002,186 elapsed=66.0s

  [3706/21087] intraday_1246.csv.gz  in=253,611,996 out=13,002,186 elapsed=66.0s

  [3707/21087] intraday_12460.csv.gz  in=253,623,532 out=13,013,722 elapsed=66.0s

  [3708/21087] intraday_12461.csv.gz  in=253,635,942 out=13,026,132 elapsed=66.0s

  [3709/21087] intraday_12462.csv.gz  in=253,647,032 out=13,037,222 elapsed=66.1s

  [3710/21087] intraday_12463.csv.gz  in=253,658,414 out=13,048,604 elapsed=66.1s

  [3711/21087] intraday_12464.csv.gz  in=253,673,500 out=13,063,690 elapsed=66.1s

  [3712/21087] intraday_12465.csv.gz  in=253,685,521 out=13,075,711 elapsed=66.1s

  [3713/21087] intraday_12466.csv.gz  in=253,698,613 out=13,088,803 elapsed=66.1s

  [3714/21087] intraday_12467.csv.gz  in=253,714,007 out=13,104,197 elapsed=66.1s

  [3715/21087] intraday_12468.csv.gz  in=253,726,174 out=13,116,364 elapsed=66.1s

  [3716/21087] intraday_12469.csv.gz  in=253,738,980 out=13,129,170 elapsed=66.1s

  [3717/21087] intraday_1247.csv.gz  in=253,751,964 out=13,129,170 elapsed=66.1s

  [3718/21087] intraday_12470.csv.gz  in=253,763,493 out=13,140,699 elapsed=66.1s

  [3719/21087] intraday_12471.csv.gz  in=253,777,145 out=13,154,351 elapsed=66.1s

  [3720/21087] intraday_12472.csv.gz  in=253,792,727 out=13,166,428 elapsed=66.2s

  [3721/21087] intraday_12473.csv.gz  in=253,805,477 out=13,179,178 elapsed=66.2s

  [3722/21087] intraday_12474.csv.gz  in=253,816,043 out=13,189,744 elapsed=66.2s

  [3723/21087] intraday_12475.csv.gz  in=253,828,892 out=13,202,593 elapsed=66.2s

  [3724/21087] intraday_12476.csv.gz  in=253,841,338 out=13,215,039 elapsed=66.2s

  [3725/21087] intraday_12477.csv.gz  in=253,853,884 out=13,227,585 elapsed=66.2s

  [3726/21087] intraday_12478.csv.gz  in=253,868,645 out=13,242,346 elapsed=66.2s

  [3727/21087] intraday_12479.csv.gz  in=253,879,230 out=13,252,931 elapsed=66.2s

  [3728/21087] intraday_1248.csv.gz  in=253,892,285 out=13,252,931 elapsed=66.2s

  [3729/21087] intraday_12480.csv.gz  in=253,903,872 out=13,264,518 elapsed=66.2s

  [3730/21087] intraday_12481.csv.gz  in=253,914,944 out=13,275,590 elapsed=66.3s

  [3731/21087] intraday_12482.csv.gz  in=253,927,871 out=13,288,517 elapsed=66.3s

  [3732/21087] intraday_12483.csv.gz  in=253,940,086 out=13,300,732 elapsed=66.3s

  [3733/21087] intraday_12484.csv.gz  in=253,952,252 out=13,312,898 elapsed=66.3s

  [3734/21087] intraday_12485.csv.gz  in=253,965,378 out=13,326,024 elapsed=66.3s

  [3735/21087] intraday_12486.csv.gz  in=253,977,481 out=13,338,127 elapsed=66.3s

  [3736/21087] intraday_12487.csv.gz  in=253,988,094 out=13,348,740 elapsed=66.3s

  [3737/21087] intraday_12488.csv.gz  in=254,001,546 out=13,362,192 elapsed=66.3s

  [3738/21087] intraday_12489.csv.gz  in=254,017,325 out=13,377,971 elapsed=66.3s

  [3739/21087] intraday_1249.csv.gz  in=254,028,934 out=13,377,971 elapsed=66.3s

  [3740/21087] intraday_12490.csv.gz  in=254,042,792 out=13,391,829 elapsed=66.3s

  [3741/21087] intraday_12492.csv.gz  in=254,055,637 out=13,404,674 elapsed=66.4s

  [3742/21087] intraday_12493.csv.gz  in=254,067,061 out=13,416,098 elapsed=66.4s

  [3743/21087] intraday_12491.csv.gz  in=254,081,653 out=13,430,690 elapsed=66.4s

  [3744/21087] intraday_12494.csv.gz  in=254,093,749 out=13,442,786 elapsed=66.4s

  [3745/21087] intraday_12495.csv.gz  in=254,107,763 out=13,456,800 elapsed=66.4s

  [3746/21087] intraday_12497.csv.gz  in=254,121,727 out=13,470,764 elapsed=66.4s

  [3747/21087] intraday_12498.csv.gz  in=254,133,361 out=13,482,398 elapsed=66.4s

  [3748/21087] intraday_12496.csv.gz  in=254,146,294 out=13,495,331 elapsed=66.4s

  [3749/21087] intraday_12499.csv.gz  in=254,159,308 out=13,508,345 elapsed=66.4s

  [3750/21087] intraday_1250.csv.gz  in=254,170,117 out=13,508,345 elapsed=66.4s

  [3751/21087] intraday_12500.csv.gz  in=254,181,636 out=13,519,864 elapsed=66.5s

  [3752/21087] intraday_12502.csv.gz  in=254,193,391 out=13,531,619 elapsed=66.5s

  [3753/21087] intraday_12501.csv.gz  in=254,208,103 out=13,546,331 elapsed=66.5s

  [3754/21087] intraday_12503.csv.gz  in=254,220,813 out=13,559,041 elapsed=66.5s

  [3755/21087] intraday_12504.csv.gz  in=254,232,313 out=13,570,541 elapsed=66.5s

  [3756/21087] intraday_12505.csv.gz  in=254,243,288 out=13,581,516 elapsed=66.5s

  [3757/21087] intraday_12506.csv.gz  in=254,256,149 out=13,594,377 elapsed=66.5s

  [3758/21087] intraday_12507.csv.gz  in=254,271,220 out=13,609,448 elapsed=66.5s

  [3759/21087] intraday_1251.csv.gz  in=254,284,054 out=13,609,448 elapsed=66.5s

  [3760/21087] intraday_12509.csv.gz  in=254,298,295 out=13,623,689 elapsed=66.6s

  [3761/21087] intraday_12508.csv.gz  in=254,316,285 out=13,641,679 elapsed=66.6s

  [3762/21087] intraday_12510.csv.gz  in=254,327,365 out=13,652,759 elapsed=66.6s

  [3763/21087] intraday_12511.csv.gz  in=254,339,528 out=13,664,922 elapsed=66.6s

  [3764/21087] intraday_12512.csv.gz  in=254,352,826 out=13,678,220 elapsed=66.6s

  [3765/21087] intraday_12513.csv.gz  in=254,364,821 out=13,690,215 elapsed=66.6s

  [3766/21087] intraday_12514.csv.gz  in=254,380,097 out=13,705,491 elapsed=66.6s

  [3767/21087] intraday_12515.csv.gz  in=254,391,670 out=13,717,064 elapsed=66.6s

  [3768/21087] intraday_12517.csv.gz  in=254,406,032 out=13,731,426 elapsed=66.6s

  [3769/21087] intraday_12516.csv.gz  in=254,421,788 out=13,747,182 elapsed=66.6s

  [3770/21087] intraday_12518.csv.gz  in=254,433,102 out=13,758,496 elapsed=66.7s

  [3771/21087] intraday_12519.csv.gz  in=254,446,421 out=13,771,815 elapsed=66.7s

  [3772/21087] intraday_1252.csv.gz  in=254,458,389 out=13,771,815 elapsed=66.7s

  [3773/21087] intraday_12520.csv.gz  in=254,469,947 out=13,783,373 elapsed=66.7s

  [3774/21087] intraday_12521.csv.gz  in=254,483,931 out=13,797,357 elapsed=66.7s

  [3775/21087] intraday_12522.csv.gz  in=254,495,181 out=13,808,607 elapsed=66.7s

  [3776/21087] intraday_12523.csv.gz  in=254,509,973 out=13,823,399 elapsed=66.7s

  [3777/21087] intraday_12524.csv.gz  in=254,522,162 out=13,835,588 elapsed=66.7s

  [3778/21087] intraday_12525.csv.gz  in=254,534,919 out=13,848,345 elapsed=66.7s

  [3779/21087] intraday_12526.csv.gz  in=254,548,212 out=13,861,638 elapsed=66.7s

  [3780/21087] intraday_12527.csv.gz  in=254,563,066 out=13,876,492 elapsed=66.8s

  [3781/21087] intraday_1253.csv.gz  in=254,575,847 out=13,876,492 elapsed=66.8s

  [3782/21087] intraday_12528.csv.gz  in=254,590,398 out=13,891,043 elapsed=66.8s

  [3783/21087] intraday_12529.csv.gz  in=254,602,758 out=13,903,403 elapsed=66.8s

  [3784/21087] intraday_12531.csv.gz  in=254,617,386 out=13,918,031 elapsed=66.8s

  [3785/21087] intraday_12530.csv.gz  in=254,630,224 out=13,930,869 elapsed=66.8s

  [3786/21087] intraday_12532.csv.gz  in=254,642,223 out=13,942,868 elapsed=66.8s

  [3787/21087] intraday_12533.csv.gz  in=254,656,539 out=13,957,184 elapsed=66.8s

  [3788/21087] intraday_12536.csv.gz  in=254,669,022 out=13,969,667 elapsed=66.9s

  [3789/21087] intraday_12535.csv.gz  in=254,681,902 out=13,982,547 elapsed=66.9s

  [3790/21087] intraday_12537.csv.gz  in=254,695,950 out=13,996,595 elapsed=66.9s

  [3791/21087] intraday_12534.csv.gz  in=254,710,772 out=14,011,417 elapsed=66.9s

  [3792/21087] intraday_1254.csv.gz  in=254,723,321 out=14,011,417 elapsed=66.9s

  [3793/21087] intraday_12538.csv.gz  in=254,740,252 out=14,028,348 elapsed=66.9s

  [3794/21087] intraday_12539.csv.gz  in=254,753,134 out=14,041,230 elapsed=66.9s

  [3795/21087] intraday_12540.csv.gz  in=254,769,143 out=14,057,239 elapsed=66.9s

  [3796/21087] intraday_12542.csv.gz  in=254,784,219 out=14,072,315 elapsed=66.9s

  [3797/21087] intraday_12543.csv.gz  in=254,801,947 out=14,090,043 elapsed=67.0s

  [3798/21087] intraday_12544.csv.gz  in=254,814,979 out=14,103,075 elapsed=67.0s

  [3799/21087] intraday_12545.csv.gz  in=254,827,237 out=14,115,333 elapsed=67.0s

  [3800/21087] intraday_12541.csv.gz  in=254,846,858 out=14,134,954 elapsed=67.0s

  [3801/21087] intraday_12546.csv.gz  in=254,859,642 out=14,147,738 elapsed=67.0s

  [3802/21087] intraday_12547.csv.gz  in=254,872,367 out=14,160,463 elapsed=67.0s

  [3803/21087] intraday_12548.csv.gz  in=254,884,548 out=14,172,644 elapsed=67.0s

  [3804/21087] intraday_1255.csv.gz  in=254,897,041 out=14,172,644 elapsed=67.0s

  [3805/21087] intraday_12549.csv.gz  in=254,908,885 out=14,184,488 elapsed=67.0s

  [3806/21087] intraday_12553.csv.gz  in=254,920,635 out=14,196,238 elapsed=67.1s

  [3807/21087] intraday_12551.csv.gz  in=254,935,490 out=14,211,093 elapsed=67.1s

  [3808/21087] intraday_12552.csv.gz  in=254,949,095 out=14,224,698 elapsed=67.1s

  [3809/21087] intraday_12550.csv.gz  in=254,963,285 out=14,238,888 elapsed=67.1s

  [3810/21087] intraday_12554.csv.gz  in=254,974,573 out=14,250,176 elapsed=67.1s

  [3811/21087] intraday_12556.csv.gz  in=254,986,082 out=14,261,685 elapsed=67.1s

  [3812/21087] intraday_12555.csv.gz  in=255,000,711 out=14,276,314 elapsed=67.1s

  [3813/21087] intraday_12557.csv.gz  in=255,013,693 out=14,289,296 elapsed=67.1s

  [3814/21087] intraday_12558.csv.gz  in=255,028,613 out=14,304,216 elapsed=67.1s

  [3815/21087] intraday_1256.csv.gz  in=255,048,177 out=14,304,216 elapsed=67.2s

  [3816/21087] intraday_12559.csv.gz  in=255,063,672 out=14,319,711 elapsed=67.2s

  [3817/21087] intraday_12560.csv.gz  in=255,077,606 out=14,333,645 elapsed=67.2s

  [3818/21087] intraday_12561.csv.gz  in=255,093,697 out=14,349,736 elapsed=67.2s

  [3819/21087] intraday_12562.csv.gz  in=255,105,323 out=14,361,362 elapsed=67.2s

  [3820/21087] intraday_12563.csv.gz  in=255,118,242 out=14,374,281 elapsed=67.2s

  [3821/21087] intraday_12564.csv.gz  in=255,130,226 out=14,386,265 elapsed=67.2s

  [3822/21087] intraday_12565.csv.gz  in=255,142,225 out=14,398,264 elapsed=67.2s

  [3823/21087] intraday_12567.csv.gz  in=255,148,960 out=14,404,999 elapsed=67.2s

  [3824/21087] intraday_12566.csv.gz  in=255,159,094 out=14,415,133 elapsed=67.3s

  [3825/21087] intraday_12569.csv.gz  in=255,165,232 out=14,421,271 elapsed=67.3s

  [3826/21087] intraday_12568.csv.gz  in=255,179,345 out=14,435,384 elapsed=67.3s

  [3827/21087] intraday_1257.csv.gz  in=255,196,915 out=14,435,384 elapsed=67.3s

  [3828/21087] intraday_12571.csv.gz  in=255,209,806 out=14,448,275 elapsed=67.3s

  [3829/21087] intraday_12570.csv.gz  in=255,227,260 out=14,465,729 elapsed=67.3s

  [3830/21087] intraday_12572.csv.gz  in=255,240,844 out=14,479,313 elapsed=67.3s

  [3831/21087] intraday_12573.csv.gz  in=255,251,980 out=14,490,449 elapsed=67.3s

  [3832/21087] intraday_12574.csv.gz  in=255,263,614 out=14,502,083 elapsed=67.3s

  [3833/21087] intraday_12575.csv.gz  in=255,277,869 out=14,516,338 elapsed=67.3s

  [3834/21087] intraday_12577.csv.gz  in=255,290,717 out=14,529,186 elapsed=67.4s

  [3835/21087] intraday_12576.csv.gz  in=255,307,762 out=14,546,223 elapsed=67.4s

  [3836/21087] intraday_12578.csv.gz  in=255,320,746 out=14,559,207 elapsed=67.4s

  [3837/21087] intraday_12579.csv.gz  in=255,334,555 out=14,573,016 elapsed=67.4s

  [3838/21087] intraday_1258.csv.gz  in=255,347,391 out=14,573,016 elapsed=67.4s

  [3839/21087] intraday_12580.csv.gz  in=255,360,628 out=14,586,253 elapsed=67.4s

  [3840/21087] intraday_12581.csv.gz  in=255,372,294 out=14,597,919 elapsed=67.4s

  [3841/21087] intraday_12582.csv.gz  in=255,387,063 out=14,612,688 elapsed=67.4s

  [3842/21087] intraday_12583.csv.gz  in=255,400,506 out=14,626,131 elapsed=67.4s

  [3843/21087] intraday_12584.csv.gz  in=255,410,286 out=14,635,911 elapsed=67.4s

  [3844/21087] intraday_12586.csv.gz  in=255,425,330 out=14,650,955 elapsed=67.5s

  [3845/21087] intraday_12587.csv.gz  in=255,438,564 out=14,664,189 elapsed=67.5s

  [3846/21087] intraday_12585.csv.gz  in=255,449,634 out=14,675,259 elapsed=67.5s

  [3847/21087] intraday_12588.csv.gz  in=255,459,541 out=14,685,166 elapsed=67.5s

  [3848/21087] intraday_1259.csv.gz  in=255,472,985 out=14,685,166 elapsed=67.5s

  [3849/21087] intraday_12589.csv.gz  in=255,483,550 out=14,695,731 elapsed=67.5s

  [3850/21087] intraday_12590.csv.gz  in=255,494,605 out=14,706,786 elapsed=67.5s

  [3851/21087] intraday_12591.csv.gz  in=255,506,950 out=14,719,131 elapsed=67.5s

  [3852/21087] intraday_12592.csv.gz  in=255,518,937 out=14,731,118 elapsed=67.5s

  [3853/21087] intraday_12593.csv.gz  in=255,530,958 out=14,743,139 elapsed=67.5s

  [3854/21087] intraday_12595.csv.gz  in=255,542,120 out=14,754,301 elapsed=67.6s

  [3855/21087] intraday_12594.csv.gz  in=255,556,185 out=14,768,366 elapsed=67.6s

  [3856/21087] intraday_12596.csv.gz  in=255,568,060 out=14,780,241 elapsed=67.6s

  [3857/21087] intraday_12597.csv.gz  in=255,580,813 out=14,792,994 elapsed=67.6s

  [3858/21087] intraday_12598.csv.gz  in=255,592,645 out=14,804,826 elapsed=67.6s

  [3859/21087] intraday_1260.csv.gz  in=255,607,842 out=14,804,826 elapsed=67.6s

  [3860/21087] intraday_12599.csv.gz  in=255,621,072 out=14,818,056 elapsed=67.6s

  [3861/21087] intraday_12600.csv.gz  in=255,637,099 out=14,834,083 elapsed=67.6s

  [3862/21087] intraday_12601.csv.gz  in=255,650,388 out=14,847,372 elapsed=67.6s

  [3863/21087] intraday_12602.csv.gz  in=255,660,431 out=14,857,415 elapsed=67.6s

  [3864/21087] intraday_12603.csv.gz  in=255,673,643 out=14,870,627 elapsed=67.6s

  [3865/21087] intraday_12604.csv.gz  in=255,686,580 out=14,883,564 elapsed=67.7s

  [3866/21087] intraday_12605.csv.gz  in=255,699,993 out=14,896,977 elapsed=67.7s

  [3867/21087] intraday_12607.csv.gz  in=255,710,701 out=14,907,685 elapsed=67.7s

  [3868/21087] intraday_12606.csv.gz  in=255,723,325 out=14,920,309 elapsed=67.7s

  [3869/21087] intraday_12608.csv.gz  in=255,739,713 out=14,933,223 elapsed=67.7s

  [3870/21087] intraday_1261.csv.gz  in=255,753,023 out=14,933,223 elapsed=67.7s

  [3871/21087] intraday_12609.csv.gz  in=255,763,546 out=14,943,033 elapsed=67.7s

  [3872/21087] intraday_12610.csv.gz  in=255,775,487 out=14,954,974 elapsed=67.7s

  [3873/21087] intraday_12612.csv.gz  in=255,786,630 out=14,966,117 elapsed=67.7s

  [3874/21087] intraday_12611.csv.gz  in=255,800,781 out=14,980,268 elapsed=67.8s

  [3875/21087] intraday_12613.csv.gz  in=255,822,549 out=14,994,475 elapsed=67.8s

  [3876/21087] intraday_12614.csv.gz  in=255,836,742 out=15,008,668 elapsed=67.8s

  [3877/21087] intraday_12615.csv.gz  in=255,849,330 out=15,021,256 elapsed=67.8s

  [3878/21087] intraday_12616.csv.gz  in=255,860,488 out=15,032,414 elapsed=67.8s

  [3879/21087] intraday_12618.csv.gz  in=255,873,812 out=15,045,738 elapsed=67.8s

  [3880/21087] intraday_12617.csv.gz  in=255,885,394 out=15,057,320 elapsed=67.8s

  [3881/21087] intraday_12619.csv.gz  in=255,896,000 out=15,067,926 elapsed=67.8s

  [3882/21087] intraday_1262.csv.gz  in=255,908,076 out=15,067,926 elapsed=67.8s

  [3883/21087] intraday_12621.csv.gz  in=255,918,143 out=15,077,993 elapsed=67.9s

  [3884/21087] intraday_12622.csv.gz  in=255,932,885 out=15,092,735 elapsed=67.9s

  [3885/21087] intraday_12620.csv.gz  in=255,965,767 out=15,107,277 elapsed=67.9s

  [3886/21087] intraday_12623.csv.gz  in=255,978,738 out=15,120,248 elapsed=67.9s

  [3887/21087] intraday_12624.csv.gz  in=255,991,024 out=15,132,534 elapsed=67.9s

  [3888/21087] intraday_12625.csv.gz  in=256,004,822 out=15,146,332 elapsed=67.9s

  [3889/21087] intraday_12626.csv.gz  in=256,016,120 out=15,157,630 elapsed=67.9s

  [3890/21087] intraday_12627.csv.gz  in=256,027,793 out=15,169,303 elapsed=67.9s

  [3891/21087] intraday_12628.csv.gz  in=256,038,078 out=15,179,588 elapsed=67.9s

  [3892/21087] intraday_12629.csv.gz  in=256,052,295 out=15,192,677 elapsed=67.9s

  [3893/21087] intraday_1263.csv.gz  in=256,065,592 out=15,192,677 elapsed=67.9s

  [3894/21087] intraday_12630.csv.gz  in=256,077,241 out=15,204,326 elapsed=68.0s

  [3895/21087] intraday_12631.csv.gz  in=256,090,591 out=15,216,408 elapsed=68.0s

  [3896/21087] intraday_12633.csv.gz  in=256,103,233 out=15,229,050 elapsed=68.0s

  [3897/21087] intraday_12632.csv.gz  in=256,125,364 out=15,242,876 elapsed=68.0s

  [3898/21087] intraday_12634.csv.gz  in=256,134,565 out=15,252,077 elapsed=68.0s

  [3899/21087] intraday_12635.csv.gz  in=256,148,863 out=15,266,375 elapsed=68.0s

  [3900/21087] intraday_12636.csv.gz  in=256,163,695 out=15,281,207 elapsed=68.0s

  [3901/21087] intraday_12637.csv.gz  in=256,176,925 out=15,294,437 elapsed=68.0s

  [3902/21087] intraday_12638.csv.gz  in=256,190,474 out=15,307,986 elapsed=68.0s

  [3903/21087] intraday_12639.csv.gz  in=256,204,606 out=15,322,118 elapsed=68.1s

  [3904/21087] intraday_1264.csv.gz  in=256,219,180 out=15,322,118 elapsed=68.1s

  [3905/21087] intraday_12640.csv.gz  in=256,229,495 out=15,332,433 elapsed=68.1s

  [3906/21087] intraday_12641.csv.gz  in=256,241,714 out=15,344,401 elapsed=68.1s

  [3907/21087] intraday_12642.csv.gz  in=256,255,362 out=15,358,049 elapsed=68.1s

  [3908/21087] intraday_12643.csv.gz  in=256,267,739 out=15,370,426 elapsed=68.1s

  [3909/21087] intraday_12644.csv.gz  in=256,281,393 out=15,383,778 elapsed=68.1s

  [3910/21087] intraday_12645.csv.gz  in=256,292,343 out=15,394,728 elapsed=68.1s

  [3911/21087] intraday_12646.csv.gz  in=256,304,644 out=15,407,029 elapsed=68.1s

  [3912/21087] intraday_12647.csv.gz  in=256,315,866 out=15,418,251 elapsed=68.2s

  [3913/21087] intraday_1265.csv.gz  in=256,327,462 out=15,418,251 elapsed=68.2s

  [3914/21087] intraday_12649.csv.gz  in=256,338,394 out=15,429,183 elapsed=68.2s

  [3915/21087] intraday_12648.csv.gz  in=256,351,909 out=15,442,698 elapsed=68.2s

  [3916/21087] intraday_12650.csv.gz  in=256,364,703 out=15,455,492 elapsed=68.2s

  [3917/21087] intraday_12651.csv.gz  in=256,375,588 out=15,466,377 elapsed=68.2s

  [3918/21087] intraday_12652.csv.gz  in=256,385,471 out=15,476,260 elapsed=68.2s

  [3919/21087] intraday_12653.csv.gz  in=256,399,431 out=15,490,220 elapsed=68.2s

  [3920/21087] intraday_12654.csv.gz  in=256,413,134 out=15,503,923 elapsed=68.2s

  [3921/21087] intraday_12656.csv.gz  in=256,426,490 out=15,517,279 elapsed=68.3s

  [3922/21087] intraday_12655.csv.gz  in=256,442,333 out=15,533,122 elapsed=68.3s

  [3923/21087] intraday_12658.csv.gz  in=256,453,432 out=15,544,221 elapsed=68.3s

  [3924/21087] intraday_12657.csv.gz  in=256,471,942 out=15,557,313 elapsed=68.3s

  [3925/21087] intraday_1266.csv.gz  in=256,486,717 out=15,557,313 elapsed=68.3s

  [3926/21087] intraday_12659.csv.gz  in=256,500,109 out=15,570,705 elapsed=68.3s

  [3927/21087] intraday_12660.csv.gz  in=256,514,516 out=15,585,112 elapsed=68.3s

  [3928/21087] intraday_12661.csv.gz  in=256,527,912 out=15,598,508 elapsed=68.3s

  [3929/21087] intraday_12662.csv.gz  in=256,539,149 out=15,609,745 elapsed=68.3s

  [3930/21087] intraday_12663.csv.gz  in=256,554,556 out=15,625,152 elapsed=68.3s

  [3931/21087] intraday_12664.csv.gz  in=256,568,300 out=15,638,896 elapsed=68.4s

  [3932/21087] intraday_12665.csv.gz  in=256,579,228 out=15,649,824 elapsed=68.4s

  [3933/21087] intraday_12666.csv.gz  in=256,593,054 out=15,663,650 elapsed=68.4s

  [3934/21087] intraday_12667.csv.gz  in=256,603,840 out=15,674,436 elapsed=68.4s

  [3935/21087] intraday_12668.csv.gz  in=256,616,442 out=15,687,038 elapsed=68.4s

  [3936/21087] intraday_1267.csv.gz  in=256,628,762 out=15,687,038 elapsed=68.4s

  [3937/21087] intraday_12669.csv.gz  in=256,640,216 out=15,698,492 elapsed=68.4s

  [3938/21087] intraday_12670.csv.gz  in=256,652,522 out=15,710,798 elapsed=68.4s

  [3939/21087] intraday_12671.csv.gz  in=256,664,717 out=15,722,993 elapsed=68.4s

  [3940/21087] intraday_12672.csv.gz  in=256,676,617 out=15,734,893 elapsed=68.4s

  [3941/21087] intraday_12674.csv.gz  in=256,689,329 out=15,747,605 elapsed=68.4s

  [3942/21087] intraday_12673.csv.gz  in=256,703,588 out=15,761,864 elapsed=68.5s

  [3943/21087] intraday_12675.csv.gz  in=256,717,538 out=15,775,814 elapsed=68.5s

  [3944/21087] intraday_12676.csv.gz  in=256,729,834 out=15,788,110 elapsed=68.5s

  [3945/21087] intraday_12677.csv.gz  in=256,744,152 out=15,802,428 elapsed=68.5s

  [3946/21087] intraday_1268.csv.gz  in=256,755,283 out=15,802,428 elapsed=68.5s

  [3947/21087] intraday_12678.csv.gz  in=256,768,168 out=15,815,313 elapsed=68.5s

  [3948/21087] intraday_12679.csv.gz  in=256,779,591 out=15,826,736 elapsed=68.5s

  [3949/21087] intraday_12681.csv.gz  in=256,794,351 out=15,841,496 elapsed=68.6s

  [3950/21087] intraday_12680.csv.gz  in=256,808,387 out=15,855,532 elapsed=68.6s

  [3951/21087] intraday_12683.csv.gz  in=256,820,741 out=15,867,886 elapsed=68.6s

  [3952/21087] intraday_12682.csv.gz  in=256,833,606 out=15,880,751 elapsed=68.6s

  [3953/21087] intraday_12684.csv.gz  in=256,848,725 out=15,895,870 elapsed=68.6s

  [3954/21087] intraday_12685.csv.gz  in=256,863,880 out=15,911,025 elapsed=68.6s

  [3955/21087] intraday_12686.csv.gz  in=256,877,607 out=15,924,752 elapsed=68.6s

  [3956/21087] intraday_12687.csv.gz  in=256,893,945 out=15,941,090 elapsed=68.6s

  [3957/21087] intraday_12689.csv.gz  in=256,906,845 out=15,953,990 elapsed=68.6s

  [3958/21087] intraday_1269.csv.gz  in=256,918,082 out=15,953,990 elapsed=68.6s

  [3959/21087] intraday_12688.csv.gz  in=256,939,211 out=15,975,119 elapsed=68.7s

  [3960/21087] intraday_12690.csv.gz  in=256,955,293 out=15,991,201 elapsed=68.7s

  [3961/21087] intraday_12691.csv.gz  in=256,968,534 out=16,004,442 elapsed=68.7s

  [3962/21087] intraday_12692.csv.gz  in=256,980,985 out=16,016,893 elapsed=68.7s

  [3963/21087] intraday_12693.csv.gz  in=256,998,221 out=16,030,876 elapsed=68.7s

  [3964/21087] intraday_12694.csv.gz  in=257,010,542 out=16,043,197 elapsed=68.7s

  [3965/21087] intraday_12695.csv.gz  in=257,022,489 out=16,055,144 elapsed=68.7s

  [3966/21087] intraday_12696.csv.gz  in=257,034,362 out=16,067,017 elapsed=68.7s

  [3967/21087] intraday_12697.csv.gz  in=257,046,913 out=16,079,568 elapsed=68.7s

  [3968/21087] intraday_1270.csv.gz  in=257,057,669 out=16,079,568 elapsed=68.7s

  [3969/21087] intraday_12698.csv.gz  in=257,071,656 out=16,093,555 elapsed=68.7s

  [3970/21087] intraday_12699.csv.gz  in=257,085,186 out=16,107,085 elapsed=68.8s

  [3971/21087] intraday_12700.csv.gz  in=257,097,410 out=16,119,309 elapsed=68.8s

  [3972/21087] intraday_12701.csv.gz  in=257,108,657 out=16,130,556 elapsed=68.8s

  [3973/21087] intraday_12702.csv.gz  in=257,122,295 out=16,144,194 elapsed=68.8s

  [3974/21087] intraday_12703.csv.gz  in=257,134,426 out=16,156,325 elapsed=68.8s

  [3975/21087] intraday_12704.csv.gz  in=257,146,273 out=16,168,172 elapsed=68.8s

  [3976/21087] intraday_12705.csv.gz  in=257,160,829 out=16,182,728 elapsed=68.8s

  [3977/21087] intraday_12707.csv.gz  in=257,174,555 out=16,196,454 elapsed=68.8s

  [3978/21087] intraday_12708.csv.gz  in=257,190,326 out=16,212,225 elapsed=68.9s

  [3979/21087] intraday_12706.csv.gz  in=257,206,698 out=16,228,597 elapsed=68.9s

  [3980/21087] intraday_12709.csv.gz  in=257,218,350 out=16,240,249 elapsed=68.9s

  [3981/21087] intraday_1271.csv.gz  in=257,241,901 out=16,240,249 elapsed=68.9s

  [3982/21087] intraday_12710.csv.gz  in=257,254,255 out=16,252,603 elapsed=68.9s

  [3983/21087] intraday_12711.csv.gz  in=257,264,947 out=16,263,295 elapsed=68.9s

  [3984/21087] intraday_12712.csv.gz  in=257,277,521 out=16,275,869 elapsed=68.9s

  [3985/21087] intraday_12713.csv.gz  in=257,287,594 out=16,285,942 elapsed=68.9s

  [3986/21087] intraday_12714.csv.gz  in=257,293,707 out=16,292,055 elapsed=68.9s

  [3987/21087] intraday_12716.csv.gz  in=257,300,474 out=16,298,822 elapsed=68.9s

  [3988/21087] intraday_12717.csv.gz  in=257,316,853 out=16,315,201 elapsed=69.0s

  [3989/21087] intraday_12718.csv.gz  in=257,330,763 out=16,329,111 elapsed=69.0s

  [3990/21087] intraday_12719.csv.gz  in=257,343,498 out=16,341,846 elapsed=69.0s

  [3991/21087] intraday_12715.csv.gz  in=257,358,261 out=16,356,609 elapsed=69.0s

  [3992/21087] intraday_1272.csv.gz  in=257,371,457 out=16,356,609 elapsed=69.0s

  [3993/21087] intraday_12720.csv.gz  in=257,381,395 out=16,366,547 elapsed=69.0s

  [3994/21087] intraday_12721.csv.gz  in=257,393,869 out=16,379,021 elapsed=69.0s

  [3995/21087] intraday_12722.csv.gz  in=257,407,190 out=16,392,342 elapsed=69.0s

  [3996/21087] intraday_12723.csv.gz  in=257,422,590 out=16,407,742 elapsed=69.0s

  [3997/21087] intraday_12724.csv.gz  in=257,433,045 out=16,418,197 elapsed=69.0s

  [3998/21087] intraday_12725.csv.gz  in=257,446,939 out=16,432,091 elapsed=69.0s

  [3999/21087] intraday_12728.csv.gz  in=257,458,577 out=16,443,729 elapsed=69.1s

  [4000/21087] intraday_12726.csv.gz  in=257,471,620 out=16,456,772 elapsed=69.1s

  [4001/21087] intraday_12727.csv.gz  in=257,484,066 out=16,469,218 elapsed=69.1s

  [4002/21087] intraday_12729.csv.gz  in=257,510,308 out=16,485,414 elapsed=69.1s

  [4003/21087] intraday_1273.csv.gz  in=257,528,383 out=16,485,414 elapsed=69.1s

  [4004/21087] intraday_12731.csv.gz  in=257,538,378 out=16,495,409 elapsed=69.1s

  [4005/21087] intraday_12732.csv.gz  in=257,547,640 out=16,504,671 elapsed=69.1s

  [4006/21087] intraday_12730.csv.gz  in=257,560,580 out=16,517,611 elapsed=69.2s

  [4007/21087] intraday_12733.csv.gz  in=257,574,909 out=16,531,940 elapsed=69.2s

  [4008/21087] intraday_12735.csv.gz  in=257,585,087 out=16,542,118 elapsed=69.2s

  [4009/21087] intraday_12734.csv.gz  in=257,597,322 out=16,554,353 elapsed=69.2s

  [4010/21087] intraday_12736.csv.gz  in=257,608,403 out=16,565,434 elapsed=69.2s

  [4011/21087] intraday_12737.csv.gz  in=257,618,764 out=16,575,751 elapsed=69.2s

  [4012/21087] intraday_12738.csv.gz  in=257,630,827 out=16,587,810 elapsed=69.2s

  [4013/21087] intraday_12740.csv.gz  in=257,642,257 out=16,599,240 elapsed=69.2s

  [4014/21087] intraday_12739.csv.gz  in=257,654,564 out=16,611,547 elapsed=69.2s

  [4015/21087] intraday_1274.csv.gz  in=257,670,784 out=16,611,547 elapsed=69.2s

  [4016/21087] intraday_12741.csv.gz  in=257,686,021 out=16,626,784 elapsed=69.3s

  [4017/21087] intraday_12742.csv.gz  in=257,697,226 out=16,637,512 elapsed=69.3s

  [4018/21087] intraday_12744.csv.gz  in=257,710,024 out=16,650,310 elapsed=69.3s

  [4019/21087] intraday_12743.csv.gz  in=257,722,772 out=16,663,058 elapsed=69.3s

  [4020/21087] intraday_12745.csv.gz  in=257,734,453 out=16,674,739 elapsed=69.3s

  [4021/21087] intraday_12746.csv.gz  in=257,748,046 out=16,688,332 elapsed=69.3s

  [4022/21087] intraday_12748.csv.gz  in=257,761,369 out=16,701,655 elapsed=69.3s

  [4023/21087] intraday_1275.csv.gz  in=257,772,919 out=16,701,655 elapsed=69.3s

  [4024/21087] intraday_12747.csv.gz  in=257,790,116 out=16,717,089 elapsed=69.3s

  [4025/21087] intraday_12749.csv.gz  in=257,800,535 out=16,727,508 elapsed=69.3s

  [4026/21087] intraday_12750.csv.gz  in=257,813,324 out=16,740,297 elapsed=69.4s

  [4027/21087] intraday_12751.csv.gz  in=257,826,405 out=16,753,378 elapsed=69.4s

  [4028/21087] intraday_12753.csv.gz  in=257,839,106 out=16,766,079 elapsed=69.4s

  [4029/21087] intraday_12752.csv.gz  in=257,852,515 out=16,779,488 elapsed=69.4s

  [4030/21087] intraday_12754.csv.gz  in=257,863,097 out=16,790,070 elapsed=69.4s

  [4031/21087] intraday_12755.csv.gz  in=257,874,439 out=16,801,412 elapsed=69.4s

  [4032/21087] intraday_12757.csv.gz  in=257,885,102 out=16,812,075 elapsed=69.4s

  [4033/21087] intraday_12756.csv.gz  in=257,895,133 out=16,822,106 elapsed=69.4s

  [4034/21087] intraday_12758.csv.gz  in=257,908,533 out=16,835,506 elapsed=69.4s

  [4035/21087] intraday_12759.csv.gz  in=257,919,724 out=16,846,697 elapsed=69.5s

  [4036/21087] intraday_1276.csv.gz  in=257,932,551 out=16,846,697 elapsed=69.5s

  [4037/21087] intraday_12760.csv.gz  in=257,944,926 out=16,859,072 elapsed=69.5s

  [4038/21087] intraday_12761.csv.gz  in=257,959,119 out=16,873,265 elapsed=69.5s

  [4039/21087] intraday_12762.csv.gz  in=257,970,606 out=16,884,752 elapsed=69.5s

  [4040/21087] intraday_12763.csv.gz  in=257,981,825 out=16,895,971 elapsed=69.5s

  [4041/21087] intraday_12764.csv.gz  in=257,993,942 out=16,907,059 elapsed=69.5s

  [4042/21087] intraday_12765.csv.gz  in=258,006,220 out=16,919,337 elapsed=69.5s

  [4043/21087] intraday_12766.csv.gz  in=258,016,683 out=16,929,800 elapsed=69.5s

  [4044/21087] intraday_12767.csv.gz  in=258,028,361 out=16,941,478 elapsed=69.6s

  [4045/21087] intraday_12768.csv.gz  in=258,039,354 out=16,952,471 elapsed=69.6s

  [4046/21087] intraday_1277.csv.gz  in=258,051,283 out=16,952,471 elapsed=69.6s

  [4047/21087] intraday_12769.csv.gz  in=258,064,537 out=16,965,627 elapsed=69.6s

  [4048/21087] intraday_12770.csv.gz  in=258,076,474 out=16,977,564 elapsed=69.6s

  [4049/21087] intraday_12771.csv.gz  in=258,088,231 out=16,989,321 elapsed=69.6s

  [4050/21087] intraday_12773.csv.gz  in=258,099,038 out=17,000,128 elapsed=69.6s

  [4051/21087] intraday_12772.csv.gz  in=258,112,774 out=17,013,864 elapsed=69.6s

  [4052/21087] intraday_12774.csv.gz  in=258,124,864 out=17,025,954 elapsed=69.6s

  [4053/21087] intraday_12775.csv.gz  in=258,134,757 out=17,035,847 elapsed=69.6s

  [4054/21087] intraday_12776.csv.gz  in=258,146,379 out=17,047,469 elapsed=69.7s

  [4055/21087] intraday_12777.csv.gz  in=258,159,841 out=17,060,931 elapsed=69.7s

  [4056/21087] intraday_12778.csv.gz  in=258,170,837 out=17,071,927 elapsed=69.7s

  [4057/21087] intraday_12779.csv.gz  in=258,182,611 out=17,083,701 elapsed=69.7s

  [4058/21087] intraday_1278.csv.gz  in=258,195,271 out=17,083,701 elapsed=69.7s

  [4059/21087] intraday_12781.csv.gz  in=258,204,167 out=17,092,597 elapsed=69.7s

  [4060/21087] intraday_12780.csv.gz  in=258,216,025 out=17,104,455 elapsed=69.7s

  [4061/21087] intraday_12782.csv.gz  in=258,229,491 out=17,117,921 elapsed=69.7s

  [4062/21087] intraday_12783.csv.gz  in=258,243,271 out=17,131,701 elapsed=69.7s

  [4063/21087] intraday_12784.csv.gz  in=258,256,496 out=17,144,926 elapsed=69.7s

  [4064/21087] intraday_12785.csv.gz  in=258,269,933 out=17,158,363 elapsed=69.7s

  [4065/21087] intraday_12786.csv.gz  in=258,285,875 out=17,171,053 elapsed=69.7s

  [4066/21087] intraday_12787.csv.gz  in=258,296,504 out=17,181,682 elapsed=69.8s

  [4067/21087] intraday_12788.csv.gz  in=258,308,339 out=17,193,517 elapsed=69.8s

  [4068/21087] intraday_1279.csv.gz  in=258,320,250 out=17,193,517 elapsed=69.8s

  [4069/21087] intraday_12789.csv.gz  in=258,332,726 out=17,205,993 elapsed=69.8s

  [4070/21087] intraday_12790.csv.gz  in=258,344,329 out=17,217,596 elapsed=69.8s

  [4071/21087] intraday_12791.csv.gz  in=258,357,843 out=17,231,110 elapsed=69.8s

  [4072/21087] intraday_12792.csv.gz  in=258,369,919 out=17,243,186 elapsed=69.8s

  [4073/21087] intraday_12793.csv.gz  in=258,386,376 out=17,255,407 elapsed=69.8s

  [4074/21087] intraday_12794.csv.gz  in=258,396,320 out=17,265,351 elapsed=69.8s

  [4075/21087] intraday_12795.csv.gz  in=258,409,744 out=17,278,775 elapsed=69.9s

  [4076/21087] intraday_12796.csv.gz  in=258,420,981 out=17,290,012 elapsed=69.9s

  [4077/21087] intraday_12797.csv.gz  in=258,432,612 out=17,301,643 elapsed=69.9s

  [4078/21087] intraday_12798.csv.gz  in=258,444,139 out=17,313,170 elapsed=69.9s

  [4079/21087] intraday_1280.csv.gz  in=258,454,940 out=17,313,170 elapsed=69.9s

  [4080/21087] intraday_12799.csv.gz  in=258,465,121 out=17,323,351 elapsed=69.9s

  [4081/21087] intraday_12800.csv.gz  in=258,478,137 out=17,336,367 elapsed=69.9s

  [4082/21087] intraday_12801.csv.gz  in=258,490,818 out=17,349,048 elapsed=69.9s

  [4083/21087] intraday_12802.csv.gz  in=258,507,274 out=17,365,504 elapsed=69.9s

  [4084/21087] intraday_12804.csv.gz  in=258,519,264 out=17,377,494 elapsed=70.0s

  [4085/21087] intraday_12806.csv.gz  in=258,531,654 out=17,389,884 elapsed=70.0s

  [4086/21087] intraday_12803.csv.gz  in=258,545,364 out=17,403,594 elapsed=70.0s

  [4087/21087] intraday_12805.csv.gz  in=258,555,732 out=17,413,962 elapsed=70.0s

  [4088/21087] intraday_12807.csv.gz  in=258,568,323 out=17,426,553 elapsed=70.0s

  [4089/21087] intraday_1281.csv.gz  in=258,582,944 out=17,426,553 elapsed=70.0s

  [4090/21087] intraday_12809.csv.gz  in=258,594,863 out=17,436,538 elapsed=70.0s

  [4091/21087] intraday_12808.csv.gz  in=258,609,273 out=17,450,948 elapsed=70.0s

  [4092/21087] intraday_12810.csv.gz  in=258,623,481 out=17,465,156 elapsed=70.1s

  [4093/21087] intraday_12812.csv.gz  in=258,635,504 out=17,477,149 elapsed=70.1s

  [4094/21087] intraday_12811.csv.gz  in=258,649,450 out=17,491,095 elapsed=70.1s

  [4095/21087] intraday_12813.csv.gz  in=258,676,756 out=17,505,682 elapsed=70.1s

  [4096/21087] intraday_12816.csv.gz  in=258,686,032 out=17,514,958 elapsed=70.1s

  [4097/21087] intraday_12814.csv.gz  in=258,698,548 out=17,527,474 elapsed=70.1s

  [4098/21087] intraday_12815.csv.gz  in=258,711,938 out=17,540,864 elapsed=70.1s

  [4099/21087] intraday_12817.csv.gz  in=258,724,262 out=17,553,188 elapsed=70.1s

  [4100/21087] intraday_12818.csv.gz  in=258,735,292 out=17,564,218 elapsed=70.1s

  [4101/21087] intraday_1282.csv.gz  in=258,746,671 out=17,564,218 elapsed=70.2s

  [4102/21087] intraday_12819.csv.gz  in=258,759,078 out=17,576,625 elapsed=70.2s

  [4103/21087] intraday_12820.csv.gz  in=258,773,222 out=17,590,769 elapsed=70.2s

  [4104/21087] intraday_12821.csv.gz  in=258,785,056 out=17,602,603 elapsed=70.2s

  [4105/21087] intraday_12823.csv.gz  in=258,797,665 out=17,615,212 elapsed=70.2s

  [4106/21087] intraday_12822.csv.gz  in=258,812,249 out=17,629,796 elapsed=70.2s

  [4107/21087] intraday_12825.csv.gz  in=258,824,394 out=17,641,941 elapsed=70.2s

  [4108/21087] intraday_12824.csv.gz  in=258,840,530 out=17,656,639 elapsed=70.2s

  [4109/21087] intraday_12826.csv.gz  in=258,852,525 out=17,668,634 elapsed=70.2s

  [4110/21087] intraday_12827.csv.gz  in=258,865,415 out=17,681,524 elapsed=70.2s

  [4111/21087] intraday_12829.csv.gz  in=258,877,536 out=17,693,645 elapsed=70.3s

  [4112/21087] intraday_12828.csv.gz  in=258,891,741 out=17,707,850 elapsed=70.3s

  [4113/21087] intraday_1283.csv.gz  in=258,903,612 out=17,707,850 elapsed=70.3s

  [4114/21087] intraday_12830.csv.gz  in=258,916,397 out=17,720,635 elapsed=70.3s

  [4115/21087] intraday_12831.csv.gz  in=258,930,479 out=17,734,717 elapsed=70.3s

  [4116/21087] intraday_12833.csv.gz  in=258,942,330 out=17,746,568 elapsed=70.3s

  [4117/21087] intraday_12832.csv.gz  in=258,956,403 out=17,760,641 elapsed=70.3s

  [4118/21087] intraday_12834.csv.gz  in=258,971,670 out=17,775,908 elapsed=70.3s

  [4119/21087] intraday_12836.csv.gz  in=258,984,593 out=17,788,831 elapsed=70.4s

  [4120/21087] intraday_12837.csv.gz  in=258,999,714 out=17,803,952 elapsed=70.4s

  [4121/21087] intraday_12838.csv.gz  in=259,011,992 out=17,816,230 elapsed=70.4s

  [4122/21087] intraday_12835.csv.gz  in=259,031,411 out=17,835,649 elapsed=70.4s

  [4123/21087] intraday_1284.csv.gz  in=259,043,285 out=17,835,649 elapsed=70.4s

  [4124/21087] intraday_12839.csv.gz  in=259,055,675 out=17,848,039 elapsed=70.4s

  [4125/21087] intraday_12840.csv.gz  in=259,068,620 out=17,860,984 elapsed=70.4s

  [4126/21087] intraday_12841.csv.gz  in=259,081,313 out=17,873,677 elapsed=70.4s

  [4127/21087] intraday_12842.csv.gz  in=259,091,821 out=17,884,185 elapsed=70.4s

  [4128/21087] intraday_12843.csv.gz  in=259,104,371 out=17,895,513 elapsed=70.4s

  [4129/21087] intraday_12844.csv.gz  in=259,116,572 out=17,907,714 elapsed=70.4s

  [4130/21087] intraday_12845.csv.gz  in=259,130,058 out=17,921,200 elapsed=70.5s

  [4131/21087] intraday_12846.csv.gz  in=259,143,175 out=17,933,333 elapsed=70.5s

  [4132/21087] intraday_12847.csv.gz  in=259,154,219 out=17,944,377 elapsed=70.5s

  [4133/21087] intraday_12848.csv.gz  in=259,165,084 out=17,955,242 elapsed=70.5s

  [4134/21087] intraday_12849.csv.gz  in=259,177,504 out=17,967,662 elapsed=70.5s

  [4135/21087] intraday_1285.csv.gz  in=259,190,658 out=17,967,662 elapsed=70.5s

  [4136/21087] intraday_12850.csv.gz  in=259,201,123 out=17,978,127 elapsed=70.5s

  [4137/21087] intraday_12851.csv.gz  in=259,214,030 out=17,991,034 elapsed=70.5s

  [4138/21087] intraday_12852.csv.gz  in=259,228,361 out=18,005,365 elapsed=70.5s

  [4139/21087] intraday_12853.csv.gz  in=259,243,583 out=18,020,587 elapsed=70.6s

  [4140/21087] intraday_12854.csv.gz  in=259,256,746 out=18,033,750 elapsed=70.6s

  [4141/21087] intraday_12855.csv.gz  in=259,269,888 out=18,046,892 elapsed=70.6s

  [4142/21087] intraday_12856.csv.gz  in=259,282,057 out=18,059,061 elapsed=70.6s

  [4143/21087] intraday_12857.csv.gz  in=259,296,700 out=18,071,886 elapsed=70.6s

  [4144/21087] intraday_12858.csv.gz  in=259,308,425 out=18,083,611 elapsed=70.6s

  [4145/21087] intraday_12859.csv.gz  in=259,321,768 out=18,096,954 elapsed=70.6s

  [4146/21087] intraday_1286.csv.gz  in=259,354,582 out=18,096,954 elapsed=70.6s

  [4147/21087] intraday_12860.csv.gz  in=259,364,023 out=18,106,395 elapsed=70.6s

  [4148/21087] intraday_12861.csv.gz  in=259,371,189 out=18,113,561 elapsed=70.7s

  [4149/21087] intraday_12862.csv.gz  in=259,385,015 out=18,127,387 elapsed=70.7s

  [4150/21087] intraday_12863.csv.gz  in=259,391,221 out=18,133,593 elapsed=70.7s

  [4151/21087] intraday_12864.csv.gz  in=259,406,739 out=18,149,111 elapsed=70.7s

  [4152/21087] intraday_12865.csv.gz  in=259,419,387 out=18,161,759 elapsed=70.7s

  [4153/21087] intraday_12868.csv.gz  in=259,430,895 out=18,173,267 elapsed=70.7s

  [4154/21087] intraday_12866.csv.gz  in=259,442,859 out=18,185,231 elapsed=70.7s

  [4155/21087] intraday_12867.csv.gz  in=259,453,896 out=18,196,268 elapsed=70.7s

  [4156/21087] intraday_12869.csv.gz  in=259,467,152 out=18,209,524 elapsed=70.7s

  [4157/21087] intraday_1287.csv.gz  in=259,488,026 out=18,209,524 elapsed=70.8s

  [4158/21087] intraday_12870.csv.gz  in=259,500,776 out=18,222,274 elapsed=70.8s

  [4159/21087] intraday_12871.csv.gz  in=259,511,346 out=18,232,844 elapsed=70.8s

  [4160/21087] intraday_12872.csv.gz  in=259,524,719 out=18,246,217 elapsed=70.8s

  [4161/21087] intraday_12874.csv.gz  in=259,536,280 out=18,257,778 elapsed=70.8s

  [4162/21087] intraday_12873.csv.gz  in=259,550,059 out=18,271,557 elapsed=70.8s

  [4163/21087] intraday_12875.csv.gz  in=259,561,968 out=18,283,466 elapsed=70.8s

  [4164/21087] intraday_12876.csv.gz  in=259,597,664 out=18,299,727 elapsed=70.8s

  [4165/21087] intraday_12877.csv.gz  in=259,610,896 out=18,312,959 elapsed=70.8s

  [4166/21087] intraday_12878.csv.gz  in=259,620,048 out=18,322,111 elapsed=70.8s

  [4167/21087] intraday_1288.csv.gz  in=259,633,330 out=18,322,111 elapsed=70.8s

  [4168/21087] intraday_12879.csv.gz  in=259,643,396 out=18,332,177 elapsed=70.8s

  [4169/21087] intraday_12880.csv.gz  in=259,656,616 out=18,345,397 elapsed=70.8s

  [4170/21087] intraday_12881.csv.gz  in=259,669,870 out=18,358,651 elapsed=70.9s

  [4171/21087] intraday_12882.csv.gz  in=259,679,585 out=18,368,366 elapsed=70.9s

  [4172/21087] intraday_12883.csv.gz  in=259,690,328 out=18,379,109 elapsed=70.9s

  [4173/21087] intraday_12884.csv.gz  in=259,701,365 out=18,390,146 elapsed=70.9s

  [4174/21087] intraday_12885.csv.gz  in=259,713,372 out=18,402,153 elapsed=70.9s

  [4175/21087] intraday_12886.csv.gz  in=259,725,200 out=18,413,981 elapsed=70.9s

  [4176/21087] intraday_12887.csv.gz  in=259,736,750 out=18,425,531 elapsed=70.9s

  [4177/21087] intraday_12888.csv.gz  in=259,750,522 out=18,439,303 elapsed=70.9s

  [4178/21087] intraday_12889.csv.gz  in=259,769,128 out=18,450,819 elapsed=70.9s

  [4179/21087] intraday_1289.csv.gz  in=259,783,445 out=18,450,819 elapsed=70.9s

  [4180/21087] intraday_12890.csv.gz  in=259,796,089 out=18,463,463 elapsed=71.0s

  [4181/21087] intraday_12892.csv.gz  in=259,805,548 out=18,472,922 elapsed=71.0s

  [4182/21087] intraday_12891.csv.gz  in=259,818,027 out=18,485,401 elapsed=71.0s

  [4183/21087] intraday_12893.csv.gz  in=259,832,044 out=18,499,418 elapsed=71.0s

  [4184/21087] intraday_12894.csv.gz  in=259,846,077 out=18,513,451 elapsed=71.0s

  [4185/21087] intraday_12895.csv.gz  in=259,859,072 out=18,526,446 elapsed=71.0s

  [4186/21087] intraday_12896.csv.gz  in=259,868,895 out=18,536,269 elapsed=71.0s

  [4187/21087] intraday_12897.csv.gz  in=259,881,636 out=18,549,010 elapsed=71.0s

  [4188/21087] intraday_12898.csv.gz  in=259,893,287 out=18,560,661 elapsed=71.0s

  [4189/21087] intraday_12899.csv.gz  in=259,906,218 out=18,573,592 elapsed=71.0s

  [4190/21087] intraday_1290.csv.gz  in=259,920,160 out=18,573,592 elapsed=71.0s

  [4191/21087] intraday_12900.csv.gz  in=259,932,415 out=18,585,847 elapsed=71.1s

  [4192/21087] intraday_12901.csv.gz  in=259,943,786 out=18,597,218 elapsed=71.1s

  [4193/21087] intraday_12904.csv.gz  in=259,954,165 out=18,607,597 elapsed=71.1s

  [4194/21087] intraday_12903.csv.gz  in=259,963,835 out=18,617,267 elapsed=71.1s

  [4195/21087] intraday_12902.csv.gz  in=259,974,565 out=18,627,997 elapsed=71.1s

  [4196/21087] intraday_12905.csv.gz  in=259,986,952 out=18,640,384 elapsed=71.1s

  [4197/21087] intraday_12906.csv.gz  in=259,998,664 out=18,652,096 elapsed=71.1s

  [4198/21087] intraday_12907.csv.gz  in=260,011,024 out=18,664,456 elapsed=71.1s

  [4199/21087] intraday_12908.csv.gz  in=260,024,600 out=18,678,032 elapsed=71.1s

  [4200/21087] intraday_12909.csv.gz  in=260,035,234 out=18,688,666 elapsed=71.1s

  [4201/21087] intraday_1291.csv.gz  in=260,054,730 out=18,688,666 elapsed=71.2s

  [4202/21087] intraday_12910.csv.gz  in=260,066,281 out=18,700,217 elapsed=71.2s

  [4203/21087] intraday_12911.csv.gz  in=260,077,040 out=18,710,976 elapsed=71.2s

  [4204/21087] intraday_12912.csv.gz  in=260,089,446 out=18,723,382 elapsed=71.2s

  [4205/21087] intraday_12913.csv.gz  in=260,099,764 out=18,733,700 elapsed=71.2s

  [4206/21087] intraday_12914.csv.gz  in=260,111,486 out=18,745,422 elapsed=71.2s

  [4207/21087] intraday_12915.csv.gz  in=260,121,868 out=18,755,804 elapsed=71.2s

  [4208/21087] intraday_12916.csv.gz  in=260,135,294 out=18,769,230 elapsed=71.2s

  [4209/21087] intraday_12917.csv.gz  in=260,146,539 out=18,780,195 elapsed=71.2s

  [4210/21087] intraday_12918.csv.gz  in=260,158,966 out=18,792,622 elapsed=71.2s

  [4211/21087] intraday_12919.csv.gz  in=260,171,695 out=18,805,351 elapsed=71.2s

  [4212/21087] intraday_1292.csv.gz  in=260,181,686 out=18,805,351 elapsed=71.3s

  [4213/21087] intraday_12921.csv.gz  in=260,192,409 out=18,816,074 elapsed=71.3s

  [4214/21087] intraday_12920.csv.gz  in=260,203,011 out=18,826,676 elapsed=71.3s

  [4215/21087] intraday_12922.csv.gz  in=260,213,791 out=18,837,456 elapsed=71.3s

  [4216/21087] intraday_12923.csv.gz  in=260,225,556 out=18,849,221 elapsed=71.3s

  [4217/21087] intraday_12924.csv.gz  in=260,237,122 out=18,860,787 elapsed=71.3s

  [4218/21087] intraday_12925.csv.gz  in=260,248,970 out=18,872,635 elapsed=71.4s

  [4219/21087] intraday_12926.csv.gz  in=260,260,390 out=18,884,055 elapsed=71.4s

  [4220/21087] intraday_12927.csv.gz  in=260,272,294 out=18,895,959 elapsed=71.4s

  [4221/21087] intraday_12928.csv.gz  in=260,281,230 out=18,904,895 elapsed=71.4s

  [4222/21087] intraday_1293.csv.gz  in=260,293,324 out=18,904,895 elapsed=71.4s

  [4223/21087] intraday_12929.csv.gz  in=260,305,936 out=18,917,507 elapsed=71.4s

  [4224/21087] intraday_12931.csv.gz  in=260,317,731 out=18,929,302 elapsed=71.4s

  [4225/21087] intraday_12930.csv.gz  in=260,331,335 out=18,942,906 elapsed=71.4s

  [4226/21087] intraday_12932.csv.gz  in=260,344,310 out=18,955,881 elapsed=71.4s

  [4227/21087] intraday_12933.csv.gz  in=260,355,849 out=18,967,420 elapsed=71.4s

  [4228/21087] intraday_12934.csv.gz  in=260,365,070 out=18,976,641 elapsed=71.4s

  [4229/21087] intraday_12935.csv.gz  in=260,377,042 out=18,988,613 elapsed=71.5s

  [4230/21087] intraday_12936.csv.gz  in=260,389,066 out=19,000,637 elapsed=71.5s

  [4231/21087] intraday_12937.csv.gz  in=260,400,977 out=19,012,548 elapsed=71.5s

  [4232/21087] intraday_12938.csv.gz  in=260,413,306 out=19,024,877 elapsed=71.5s

  [4233/21087] intraday_12939.csv.gz  in=260,425,283 out=19,036,854 elapsed=71.5s

  [4234/21087] intraday_1294.csv.gz  in=260,437,723 out=19,036,854 elapsed=71.5s

  [4235/21087] intraday_12940.csv.gz  in=260,447,053 out=19,046,184 elapsed=71.5s

  [4236/21087] intraday_12941.csv.gz  in=260,458,303 out=19,057,434 elapsed=71.5s

  [4237/21087] intraday_12942.csv.gz  in=260,472,760 out=19,071,891 elapsed=71.5s

  [4238/21087] intraday_12943.csv.gz  in=260,484,666 out=19,083,797 elapsed=71.5s

  [4239/21087] intraday_12945.csv.gz  in=260,494,432 out=19,093,563 elapsed=71.6s

  [4240/21087] intraday_12944.csv.gz  in=260,505,703 out=19,104,834 elapsed=71.6s

  [4241/21087] intraday_12946.csv.gz  in=260,516,376 out=19,115,507 elapsed=71.6s

  [4242/21087] intraday_12947.csv.gz  in=260,528,527 out=19,127,658 elapsed=71.6s

  [4243/21087] intraday_12949.csv.gz  in=260,543,145 out=19,142,276 elapsed=71.6s

  [4244/21087] intraday_1295.csv.gz  in=260,555,602 out=19,142,276 elapsed=71.6s

  [4245/21087] intraday_12948.csv.gz  in=260,568,480 out=19,155,154 elapsed=71.6s

  [4246/21087] intraday_12950.csv.gz  in=260,583,013 out=19,169,687 elapsed=71.6s

  [4247/21087] intraday_12952.csv.gz  in=260,594,485 out=19,181,159 elapsed=71.7s

  [4248/21087] intraday_12953.csv.gz  in=260,605,528 out=19,192,202 elapsed=71.7s

  [4249/21087] intraday_12951.csv.gz  in=260,617,172 out=19,203,846 elapsed=71.7s

  [4250/21087] intraday_12954.csv.gz  in=260,631,088 out=19,217,762 elapsed=71.7s

  [4251/21087] intraday_12956.csv.gz  in=260,641,493 out=19,228,167 elapsed=71.7s

  [4252/21087] intraday_12955.csv.gz  in=260,653,424 out=19,240,098 elapsed=71.7s

  [4253/21087] intraday_12958.csv.gz  in=260,664,487 out=19,251,161 elapsed=71.7s

  [4254/21087] intraday_12957.csv.gz  in=260,680,228 out=19,266,902 elapsed=71.7s

  [4255/21087] intraday_12959.csv.gz  in=260,692,390 out=19,279,064 elapsed=71.7s

  [4256/21087] intraday_1296.csv.gz  in=260,709,228 out=19,279,064 elapsed=71.8s

  [4257/21087] intraday_12961.csv.gz  in=260,721,080 out=19,290,916 elapsed=71.8s

  [4258/21087] intraday_12960.csv.gz  in=260,733,291 out=19,303,127 elapsed=71.8s

  [4259/21087] intraday_12962.csv.gz  in=260,745,110 out=19,314,946 elapsed=71.8s

  [4260/21087] intraday_12963.csv.gz  in=260,756,922 out=19,326,758 elapsed=71.8s

  [4261/21087] intraday_12966.csv.gz  in=260,769,540 out=19,339,376 elapsed=71.8s

  [4262/21087] intraday_12965.csv.gz  in=260,780,500 out=19,350,336 elapsed=71.8s

  [4263/21087] intraday_12964.csv.gz  in=260,790,812 out=19,360,648 elapsed=71.8s

  [4264/21087] intraday_12967.csv.gz  in=260,802,642 out=19,372,478 elapsed=71.8s

  [4265/21087] intraday_12968.csv.gz  in=260,813,730 out=19,383,566 elapsed=71.8s

  [4266/21087] intraday_1297.csv.gz  in=260,834,585 out=19,383,566 elapsed=71.8s

  [4267/21087] intraday_12969.csv.gz  in=260,848,514 out=19,397,495 elapsed=71.8s

  [4268/21087] intraday_12970.csv.gz  in=260,860,158 out=19,409,139 elapsed=71.9s

  [4269/21087] intraday_12971.csv.gz  in=260,875,435 out=19,424,416 elapsed=71.9s

  [4270/21087] intraday_12972.csv.gz  in=260,885,759 out=19,434,722 elapsed=71.9s

  [4271/21087] intraday_12973.csv.gz  in=260,902,469 out=19,446,958 elapsed=71.9s

  [4272/21087] intraday_12974.csv.gz  in=260,916,571 out=19,461,060 elapsed=71.9s

  [4273/21087] intraday_12975.csv.gz  in=260,930,822 out=19,475,311 elapsed=71.9s

  [4274/21087] intraday_12976.csv.gz  in=260,941,344 out=19,485,833 elapsed=71.9s

  [4275/21087] intraday_12978.csv.gz  in=260,955,321 out=19,499,810 elapsed=71.9s

  [4276/21087] intraday_12977.csv.gz  in=260,967,994 out=19,512,483 elapsed=72.0s

  [4277/21087] intraday_12979.csv.gz  in=260,982,068 out=19,526,557 elapsed=72.0s

  [4278/21087] intraday_1298.csv.gz  in=261,000,957 out=19,526,557 elapsed=72.0s

  [4279/21087] intraday_12980.csv.gz  in=261,013,580 out=19,539,180 elapsed=72.0s

  [4280/21087] intraday_12983.csv.gz  in=261,025,507 out=19,551,107 elapsed=72.0s

  [4281/21087] intraday_12981.csv.gz  in=261,039,687 out=19,565,287 elapsed=72.0s

  [4282/21087] intraday_12982.csv.gz  in=261,058,048 out=19,583,648 elapsed=72.0s

  [4283/21087] intraday_12984.csv.gz  in=261,073,462 out=19,599,062 elapsed=72.0s

  [4284/21087] intraday_12985.csv.gz  in=261,083,343 out=19,608,943 elapsed=72.0s

  [4285/21087] intraday_12987.csv.gz  in=261,095,373 out=19,620,973 elapsed=72.1s

  [4286/21087] intraday_12986.csv.gz  in=261,108,927 out=19,634,527 elapsed=72.1s

  [4287/21087] intraday_12988.csv.gz  in=261,121,434 out=19,647,034 elapsed=72.1s

  [4288/21087] intraday_12989.csv.gz  in=261,132,229 out=19,657,829 elapsed=72.1s

  [4289/21087] intraday_1299.csv.gz  in=261,146,837 out=19,657,829 elapsed=72.1s

  [4290/21087] intraday_12990.csv.gz  in=261,158,490 out=19,669,482 elapsed=72.1s

  [4291/21087] intraday_12991.csv.gz  in=261,170,068 out=19,681,060 elapsed=72.1s

  [4292/21087] intraday_12992.csv.gz  in=261,183,126 out=19,694,118 elapsed=72.1s

  [4293/21087] intraday_12993.csv.gz  in=261,194,811 out=19,705,803 elapsed=72.1s

  [4294/21087] intraday_12996.csv.gz  in=261,208,362 out=19,719,354 elapsed=72.2s

  [4295/21087] intraday_12997.csv.gz  in=261,218,524 out=19,729,516 elapsed=72.2s

  [4296/21087] intraday_12994.csv.gz  in=261,230,895 out=19,741,887 elapsed=72.2s

  [4297/21087] intraday_12995.csv.gz  in=261,240,907 out=19,751,899 elapsed=72.2s

  [4298/21087] intraday_1300.csv.gz  in=261,253,416 out=19,751,899 elapsed=72.2s

  [4299/21087] intraday_12998.csv.gz  in=261,266,569 out=19,765,052 elapsed=72.2s

  [4300/21087] intraday_12999.csv.gz  in=261,280,408 out=19,778,891 elapsed=72.2s

  [4301/21087] intraday_13000.csv.gz  in=261,294,911 out=19,793,394 elapsed=72.2s

  [4302/21087] intraday_13001.csv.gz  in=261,308,454 out=19,806,937 elapsed=72.2s

  [4303/21087] intraday_13002.csv.gz  in=261,321,789 out=19,820,272 elapsed=72.3s

  [4304/21087] intraday_13004.csv.gz  in=261,334,207 out=19,832,690 elapsed=72.3s

  [4305/21087] intraday_13003.csv.gz  in=261,345,560 out=19,844,043 elapsed=72.3s

  [4306/21087] intraday_13005.csv.gz  in=261,356,562 out=19,855,045 elapsed=72.3s

  [4307/21087] intraday_13009.csv.gz  in=261,370,311 out=19,868,794 elapsed=72.3s

  [4308/21087] intraday_13007.csv.gz  in=261,379,041 out=19,877,524 elapsed=72.3s

  [4309/21087] intraday_13006.csv.gz  in=261,392,376 out=19,890,859 elapsed=72.3s

  [4310/21087] intraday_13008.csv.gz  in=261,400,013 out=19,898,496 elapsed=72.3s

  [4311/21087] intraday_13011.csv.gz  in=261,400,733 out=19,898,496 elapsed=72.4s

  [4312/21087] intraday_1301.csv.gz  in=261,413,233 out=19,898,496 elapsed=72.4s

  [4313/21087] intraday_13010.csv.gz  in=261,417,107 out=19,902,370 elapsed=72.4s

  [4314/21087] intraday_13012.csv.gz  in=261,434,467 out=19,919,730 elapsed=72.4s

  [4315/21087] intraday_13013.csv.gz  in=261,447,500 out=19,932,763 elapsed=72.4s

  [4316/21087] intraday_13015.csv.gz  in=261,458,017 out=19,943,280 elapsed=72.4s

  [4317/21087] intraday_13014.csv.gz  in=261,470,746 out=19,956,009 elapsed=72.4s

  [4318/21087] intraday_13016.csv.gz  in=261,483,500 out=19,968,763 elapsed=72.4s

  [4319/21087] intraday_13017.csv.gz  in=261,498,074 out=19,983,337 elapsed=72.4s

  [4320/21087] intraday_13018.csv.gz  in=261,510,897 out=19,996,160 elapsed=72.4s

  [4321/21087] intraday_1302.csv.gz  in=261,524,144 out=19,996,160 elapsed=72.4s

  [4322/21087] intraday_13019.csv.gz  in=261,536,197 out=20,008,213 elapsed=72.4s

  [4323/21087] intraday_13020.csv.gz  in=261,550,136 out=20,022,152 elapsed=72.5s

  [4324/21087] intraday_13021.csv.gz  in=261,562,768 out=20,034,784 elapsed=72.5s

  [4325/21087] intraday_13022.csv.gz  in=261,575,903 out=20,047,919 elapsed=72.5s

  [4326/21087] intraday_13023.csv.gz  in=261,588,152 out=20,060,168 elapsed=72.5s

  [4327/21087] intraday_13025.csv.gz  in=261,601,375 out=20,073,391 elapsed=72.5s

  [4328/21087] intraday_13024.csv.gz  in=261,615,995 out=20,088,011 elapsed=72.5s

  [4329/21087] intraday_13026.csv.gz  in=261,625,781 out=20,097,797 elapsed=72.5s

  [4330/21087] intraday_13027.csv.gz  in=261,635,823 out=20,107,839 elapsed=72.5s

  [4331/21087] intraday_13028.csv.gz  in=261,649,646 out=20,121,662 elapsed=72.6s

  [4332/21087] intraday_1303.csv.gz  in=261,662,314 out=20,121,662 elapsed=72.6s

  [4333/21087] intraday_13029.csv.gz  in=261,676,137 out=20,135,485 elapsed=72.6s

  [4334/21087] intraday_13030.csv.gz  in=261,686,113 out=20,145,461 elapsed=72.6s

  [4335/21087] intraday_13031.csv.gz  in=261,696,615 out=20,155,963 elapsed=72.6s

  [4336/21087] intraday_13033.csv.gz  in=261,708,541 out=20,167,889 elapsed=72.6s

  [4337/21087] intraday_13032.csv.gz  in=261,720,496 out=20,179,844 elapsed=72.6s

  [4338/21087] intraday_13034.csv.gz  in=261,733,379 out=20,192,727 elapsed=72.6s

  [4339/21087] intraday_13037.csv.gz  in=261,744,875 out=20,203,839 elapsed=72.7s

  [4340/21087] intraday_13035.csv.gz  in=261,757,448 out=20,216,412 elapsed=72.7s

  [4341/21087] intraday_13036.csv.gz  in=261,772,036 out=20,231,000 elapsed=72.7s

  [4342/21087] intraday_13038.csv.gz  in=261,784,270 out=20,243,234 elapsed=72.7s

  [4343/21087] intraday_13039.csv.gz  in=261,796,921 out=20,255,885 elapsed=72.7s

  [4344/21087] intraday_1304.csv.gz  in=261,808,095 out=20,255,885 elapsed=72.7s

  [4345/21087] intraday_13040.csv.gz  in=261,819,577 out=20,267,367 elapsed=72.7s

  [4346/21087] intraday_13041.csv.gz  in=261,832,243 out=20,280,033 elapsed=72.7s

  [4347/21087] intraday_13042.csv.gz  in=261,849,024 out=20,296,814 elapsed=72.7s

  [4348/21087] intraday_13043.csv.gz  in=261,862,764 out=20,310,554 elapsed=72.7s

  [4349/21087] intraday_13044.csv.gz  in=261,873,298 out=20,321,088 elapsed=72.7s

  [4350/21087] intraday_13045.csv.gz  in=261,885,010 out=20,332,800 elapsed=72.8s

  [4351/21087] intraday_13046.csv.gz  in=261,897,522 out=20,345,312 elapsed=72.8s

  [4352/21087] intraday_13047.csv.gz  in=261,911,013 out=20,358,803 elapsed=72.8s

  [4353/21087] intraday_13048.csv.gz  in=261,923,476 out=20,371,266 elapsed=72.8s

  [4354/21087] intraday_13049.csv.gz  in=261,934,855 out=20,382,645 elapsed=72.8s

  [4355/21087] intraday_1305.csv.gz  in=261,946,629 out=20,382,645 elapsed=72.8s

  [4356/21087] intraday_13050.csv.gz  in=261,958,234 out=20,394,250 elapsed=72.8s

  [4357/21087] intraday_13051.csv.gz  in=261,967,429 out=20,403,445 elapsed=72.8s

  [4358/21087] intraday_13052.csv.gz  in=261,978,392 out=20,414,408 elapsed=72.8s

  [4359/21087] intraday_13053.csv.gz  in=261,991,258 out=20,427,274 elapsed=72.8s

  [4360/21087] intraday_13054.csv.gz  in=262,004,637 out=20,440,653 elapsed=72.8s

  [4361/21087] intraday_13055.csv.gz  in=262,016,856 out=20,452,872 elapsed=72.9s

  [4362/21087] intraday_13056.csv.gz  in=262,031,274 out=20,467,290 elapsed=72.9s

  [4363/21087] intraday_13057.csv.gz  in=262,041,643 out=20,477,659 elapsed=72.9s

  [4364/21087] intraday_13058.csv.gz  in=262,053,723 out=20,489,739 elapsed=72.9s

  [4365/21087] intraday_13059.csv.gz  in=262,066,525 out=20,502,541 elapsed=72.9s

  [4366/21087] intraday_1306.csv.gz  in=262,078,384 out=20,502,541 elapsed=72.9s

  [4367/21087] intraday_13060.csv.gz  in=262,088,724 out=20,512,881 elapsed=72.9s

  [4368/21087] intraday_13061.csv.gz  in=262,100,563 out=20,524,720 elapsed=72.9s

  [4369/21087] intraday_13062.csv.gz  in=262,111,136 out=20,535,293 elapsed=72.9s

  [4370/21087] intraday_13063.csv.gz  in=262,123,383 out=20,547,540 elapsed=72.9s

  [4371/21087] intraday_13064.csv.gz  in=262,137,844 out=20,562,001 elapsed=73.0s

  [4372/21087] intraday_13065.csv.gz  in=262,149,541 out=20,573,698 elapsed=73.0s

  [4373/21087] intraday_13066.csv.gz  in=262,162,828 out=20,586,985 elapsed=73.0s

  [4374/21087] intraday_13067.csv.gz  in=262,174,956 out=20,599,113 elapsed=73.0s

  [4375/21087] intraday_13068.csv.gz  in=262,187,111 out=20,611,268 elapsed=73.0s

  [4376/21087] intraday_13069.csv.gz  in=262,199,258 out=20,623,415 elapsed=73.0s

  [4377/21087] intraday_1307.csv.gz  in=262,211,373 out=20,623,415 elapsed=73.0s

  [4378/21087] intraday_13070.csv.gz  in=262,223,976 out=20,636,018 elapsed=73.0s

  [4379/21087] intraday_13071.csv.gz  in=262,235,613 out=20,647,655 elapsed=73.0s

  [4380/21087] intraday_13072.csv.gz  in=262,250,354 out=20,662,396 elapsed=73.0s

  [4381/21087] intraday_13073.csv.gz  in=262,264,107 out=20,676,149 elapsed=73.0s

  [4382/21087] intraday_13074.csv.gz  in=262,281,465 out=20,687,994 elapsed=73.1s

  [4383/21087] intraday_13075.csv.gz  in=262,292,452 out=20,698,981 elapsed=73.1s

  [4384/21087] intraday_13076.csv.gz  in=262,304,074 out=20,710,603 elapsed=73.1s

  [4385/21087] intraday_13077.csv.gz  in=262,320,241 out=20,726,770 elapsed=73.1s

  [4386/21087] intraday_13078.csv.gz  in=262,332,276 out=20,738,805 elapsed=73.1s

  [4387/21087] intraday_13079.csv.gz  in=262,346,109 out=20,752,638 elapsed=73.1s

  [4388/21087] intraday_1308.csv.gz  in=262,357,994 out=20,752,638 elapsed=73.1s

  [4389/21087] intraday_13080.csv.gz  in=262,370,475 out=20,765,119 elapsed=73.1s

  [4390/21087] intraday_13082.csv.gz  in=262,379,889 out=20,774,533 elapsed=73.1s

  [4391/21087] intraday_13081.csv.gz  in=262,391,038 out=20,785,682 elapsed=73.1s

  [4392/21087] intraday_13083.csv.gz  in=262,404,125 out=20,798,769 elapsed=73.2s

  [4393/21087] intraday_13086.csv.gz  in=262,414,903 out=20,809,547 elapsed=73.2s

  [4394/21087] intraday_13085.csv.gz  in=262,428,300 out=20,822,944 elapsed=73.2s

  [4395/21087] intraday_13084.csv.gz  in=262,441,825 out=20,836,469 elapsed=73.2s

  [4396/21087] intraday_13087.csv.gz  in=262,454,807 out=20,849,451 elapsed=73.2s

  [4397/21087] intraday_1309.csv.gz  in=262,465,539 out=20,849,451 elapsed=73.2s

  [4398/21087] intraday_13088.csv.gz  in=262,475,445 out=20,859,357 elapsed=73.2s

  [4399/21087] intraday_13089.csv.gz  in=262,491,015 out=20,874,927 elapsed=73.2s

  [4400/21087] intraday_13091.csv.gz  in=262,501,916 out=20,885,828 elapsed=73.3s

  [4401/21087] intraday_13090.csv.gz  in=262,514,634 out=20,898,546 elapsed=73.3s

  [4402/21087] intraday_13092.csv.gz  in=262,526,172 out=20,910,084 elapsed=73.3s

  [4403/21087] intraday_13093.csv.gz  in=262,537,161 out=20,921,073 elapsed=73.3s

  [4404/21087] intraday_13094.csv.gz  in=262,549,173 out=20,933,085 elapsed=73.3s

  [4405/21087] intraday_13095.csv.gz  in=262,561,064 out=20,944,976 elapsed=73.3s

  [4406/21087] intraday_13097.csv.gz  in=262,576,624 out=20,960,536 elapsed=73.3s

  [4407/21087] intraday_13098.csv.gz  in=262,588,091 out=20,972,003 elapsed=73.3s

  [4408/21087] intraday_13096.csv.gz  in=262,606,617 out=20,990,529 elapsed=73.3s

  [4409/21087] intraday_13099.csv.gz  in=262,617,714 out=21,001,626 elapsed=73.3s

  [4410/21087] intraday_1310.csv.gz  in=262,629,361 out=21,001,626 elapsed=73.4s

  [4411/21087] intraday_13100.csv.gz  in=262,642,507 out=21,014,772 elapsed=73.4s

  [4412/21087] intraday_13101.csv.gz  in=262,653,898 out=21,026,163 elapsed=73.4s

  [4413/21087] intraday_13102.csv.gz  in=262,669,456 out=21,041,721 elapsed=73.4s

  [4414/21087] intraday_13103.csv.gz  in=262,680,304 out=21,052,569 elapsed=73.4s

  [4415/21087] intraday_13104.csv.gz  in=262,693,759 out=21,066,024 elapsed=73.4s

  [4416/21087] intraday_13105.csv.gz  in=262,707,210 out=21,079,475 elapsed=73.4s

  [4417/21087] intraday_13106.csv.gz  in=262,720,438 out=21,092,703 elapsed=73.5s

  [4418/21087] intraday_13107.csv.gz  in=262,732,869 out=21,105,134 elapsed=73.5s

  [4419/21087] intraday_13108.csv.gz  in=262,745,201 out=21,117,466 elapsed=73.5s

  [4420/21087] intraday_13109.csv.gz  in=262,758,063 out=21,130,328 elapsed=73.5s

  [4421/21087] intraday_1311.csv.gz  in=262,769,513 out=21,130,328 elapsed=73.5s

  [4422/21087] intraday_13110.csv.gz  in=262,781,766 out=21,142,526 elapsed=73.5s

  [4423/21087] intraday_13111.csv.gz  in=262,794,405 out=21,155,165 elapsed=73.5s

  [4424/21087] intraday_13112.csv.gz  in=262,807,328 out=21,168,088 elapsed=73.5s

  [4425/21087] intraday_13113.csv.gz  in=262,818,992 out=21,179,752 elapsed=73.5s

  [4426/21087] intraday_13114.csv.gz  in=262,830,972 out=21,191,732 elapsed=73.5s

  [4427/21087] intraday_13115.csv.gz  in=262,844,712 out=21,205,472 elapsed=73.6s

  [4428/21087] intraday_13116.csv.gz  in=262,857,171 out=21,217,931 elapsed=73.6s

  [4429/21087] intraday_13118.csv.gz  in=262,869,703 out=21,230,463 elapsed=73.6s

  [4430/21087] intraday_13117.csv.gz  in=262,884,677 out=21,245,437 elapsed=73.6s

  [4431/21087] intraday_1312.csv.gz  in=262,901,921 out=21,245,437 elapsed=73.6s

  [4432/21087] intraday_13120.csv.gz  in=262,913,556 out=21,257,072 elapsed=73.6s

  [4433/21087] intraday_13119.csv.gz  in=262,928,367 out=21,271,883 elapsed=73.6s

  [4434/21087] intraday_13121.csv.gz  in=262,941,495 out=21,285,011 elapsed=73.6s

  [4435/21087] intraday_13122.csv.gz  in=262,954,329 out=21,297,845 elapsed=73.7s

  [4436/21087] intraday_13123.csv.gz  in=262,967,992 out=21,311,508 elapsed=73.7s

  [4437/21087] intraday_13124.csv.gz  in=262,978,862 out=21,322,378 elapsed=73.7s

  [4438/21087] intraday_13125.csv.gz  in=262,993,555 out=21,337,071 elapsed=73.7s

  [4439/21087] intraday_13126.csv.gz  in=263,009,099 out=21,352,615 elapsed=73.7s

  [4440/21087] intraday_1313.csv.gz  in=263,020,395 out=21,352,615 elapsed=73.7s

  [4441/21087] intraday_13127.csv.gz  in=263,034,972 out=21,367,192 elapsed=73.7s

  [4442/21087] intraday_13128.csv.gz  in=263,050,878 out=21,383,098 elapsed=73.7s

  [4443/21087] intraday_13129.csv.gz  in=263,069,143 out=21,401,363 elapsed=73.7s

  [4444/21087] intraday_13130.csv.gz  in=263,084,829 out=21,417,049 elapsed=73.8s

  [4445/21087] intraday_13131.csv.gz  in=263,100,743 out=21,432,963 elapsed=73.8s

  [4446/21087] intraday_13132.csv.gz  in=263,115,252 out=21,447,472 elapsed=73.8s

  [4447/21087] intraday_13133.csv.gz  in=263,127,694 out=21,459,914 elapsed=73.8s

  [4448/21087] intraday_13134.csv.gz  in=263,139,276 out=21,471,496 elapsed=73.8s

  [4449/21087] intraday_13136.csv.gz  in=263,152,280 out=21,484,500 elapsed=73.8s

  [4450/21087] intraday_13135.csv.gz  in=263,163,512 out=21,495,732 elapsed=73.8s

  [4451/21087] intraday_13137.csv.gz  in=263,174,365 out=21,506,585 elapsed=73.8s

  [4452/21087] intraday_13138.csv.gz  in=263,186,761 out=21,518,981 elapsed=73.8s

  [4453/21087] intraday_1314.csv.gz  in=263,196,308 out=21,518,981 elapsed=73.8s

  [4454/21087] intraday_13139.csv.gz  in=263,209,179 out=21,531,852 elapsed=73.9s

  [4455/21087] intraday_13141.csv.gz  in=263,219,762 out=21,542,435 elapsed=73.9s

  [4456/21087] intraday_13140.csv.gz  in=263,238,727 out=21,557,436 elapsed=73.9s

  [4457/21087] intraday_13142.csv.gz  in=263,250,351 out=21,569,060 elapsed=73.9s

  [4458/21087] intraday_13144.csv.gz  in=263,261,968 out=21,580,677 elapsed=73.9s

  [4459/21087] intraday_13143.csv.gz  in=263,274,462 out=21,593,171 elapsed=73.9s

  [4460/21087] intraday_13145.csv.gz  in=263,287,646 out=21,606,355 elapsed=73.9s

  [4461/21087] intraday_13146.csv.gz  in=263,302,326 out=21,621,035 elapsed=73.9s

  [4462/21087] intraday_13148.csv.gz  in=263,316,233 out=21,634,942 elapsed=73.9s

  [4463/21087] intraday_13147.csv.gz  in=263,331,805 out=21,650,514 elapsed=74.0s

  [4464/21087] intraday_1315.csv.gz  in=263,343,664 out=21,650,514 elapsed=74.0s

  [4465/21087] intraday_13149.csv.gz  in=263,357,792 out=21,664,642 elapsed=74.0s

  [4466/21087] intraday_13151.csv.gz  in=263,370,582 out=21,677,432 elapsed=74.0s

  [4467/21087] intraday_13152.csv.gz  in=263,384,178 out=21,691,028 elapsed=74.0s

  [4468/21087] intraday_13150.csv.gz  in=263,396,612 out=21,703,462 elapsed=74.0s

  [4469/21087] intraday_13153.csv.gz  in=263,433,666 out=21,720,209 elapsed=74.0s

  [4470/21087] intraday_13155.csv.gz  in=263,441,649 out=21,728,192 elapsed=74.0s

  [4471/21087] intraday_13154.csv.gz  in=263,450,946 out=21,737,489 elapsed=74.0s

  [4472/21087] intraday_13157.csv.gz  in=263,456,365 out=21,742,908 elapsed=74.0s

  [4473/21087] intraday_13156.csv.gz  in=263,471,788 out=21,758,331 elapsed=74.0s

  [4474/21087] intraday_1316.csv.gz  in=263,484,666 out=21,758,331 elapsed=74.1s

  [4475/21087] intraday_13160.csv.gz  in=263,517,027 out=21,790,692 elapsed=74.1s

  [4476/21087] intraday_13161.csv.gz  in=263,527,985 out=21,801,650 elapsed=74.1s

  [4477/21087] intraday_13159.csv.gz  in=263,566,930 out=21,840,595 elapsed=74.1s

  [4478/21087] intraday_13158.csv.gz  in=263,615,108 out=21,888,773 elapsed=74.1s

  [4479/21087] intraday_13162.csv.gz  in=263,621,166 out=21,894,831 elapsed=74.1s

  [4480/21087] intraday_13163.csv.gz  in=263,662,721 out=21,935,539 elapsed=74.2s

  [4481/21087] intraday_13166.csv.gz  in=263,696,445 out=21,969,263 elapsed=74.2s

  [4482/21087] intraday_13165.csv.gz  in=263,730,156 out=22,002,974 elapsed=74.2s

  [4483/21087] intraday_13164.csv.gz  in=263,770,469 out=22,043,287 elapsed=74.2s

  [4484/21087] intraday_13167.csv.gz  in=263,808,723 out=22,081,493 elapsed=74.2s

  [4485/21087] intraday_1317.csv.gz  in=263,823,739 out=22,081,493 elapsed=74.3s

  [4486/21087] intraday_13169.csv.gz  in=263,841,218 out=22,098,972 elapsed=74.3s

  [4487/21087] intraday_13170.csv.gz  in=263,859,477 out=22,117,231 elapsed=74.3s

  [4488/21087] intraday_13168.csv.gz  in=263,901,074 out=22,158,828 elapsed=74.3s

  [4489/21087] intraday_13171.csv.gz  in=263,945,556 out=22,194,306 elapsed=74.3s

  [4490/21087] intraday_13172.csv.gz  in=263,979,365 out=22,228,115 elapsed=74.4s

  [4491/21087] intraday_13173.csv.gz  in=264,016,817 out=22,265,567 elapsed=74.4s

  [4492/21087] intraday_13174.csv.gz  in=264,054,794 out=22,303,544 elapsed=74.4s

  [4493/21087] intraday_13175.csv.gz  in=264,091,109 out=22,339,859 elapsed=74.4s

  [4494/21087] intraday_13176.csv.gz  in=264,138,899 out=22,383,300 elapsed=74.5s

  [4495/21087] intraday_13177.csv.gz  in=264,170,584 out=22,414,985 elapsed=74.5s

  [4496/21087] intraday_13178.csv.gz  in=264,199,220 out=22,443,621 elapsed=74.5s

  [4497/21087] intraday_13179.csv.gz  in=264,227,721 out=22,472,122 elapsed=74.5s

  [4498/21087] intraday_1318.csv.gz  in=264,241,715 out=22,472,122 elapsed=74.5s

  [4499/21087] intraday_13181.csv.gz  in=264,273,833 out=22,504,240 elapsed=74.6s

  [4500/21087] intraday_13182.csv.gz  in=264,308,568 out=22,538,975 elapsed=74.6s

  [4501/21087] intraday_13180.csv.gz  in=264,350,644 out=22,580,912 elapsed=74.6s

  [4502/21087] intraday_13183.csv.gz  in=264,386,276 out=22,616,544 elapsed=74.6s

  [4503/21087] intraday_13186.csv.gz  in=264,388,237 out=22,618,505 elapsed=74.6s

  [4504/21087] intraday_13184.csv.gz  in=264,432,087 out=22,658,439 elapsed=74.7s

  [4505/21087] intraday_13187.csv.gz  in=264,461,542 out=22,687,894 elapsed=74.7s

  [4506/21087] intraday_13185.csv.gz  in=264,492,548 out=22,718,900 elapsed=74.7s

  [4507/21087] intraday_13188.csv.gz  in=264,529,538 out=22,755,890 elapsed=74.7s

  [4508/21087] intraday_1319.csv.gz  in=264,542,427 out=22,755,890 elapsed=74.7s

  [4509/21087] intraday_13190.csv.gz  in=264,583,530 out=22,794,584 elapsed=74.7s

  [4510/21087] intraday_13191.csv.gz  in=264,624,808 out=22,835,862 elapsed=74.8s

  [4511/21087] intraday_13189.csv.gz  in=264,660,306 out=22,871,360 elapsed=74.8s

  [4512/21087] intraday_13192.csv.gz  in=264,692,980 out=22,904,034 elapsed=74.8s

  [4513/21087] intraday_13195.csv.gz  in=264,701,502 out=22,912,556 elapsed=74.8s

  [4514/21087] intraday_13196.csv.gz  in=264,742,062 out=22,953,116 elapsed=74.8s

  [4515/21087] intraday_13194.csv.gz  in=264,779,578 out=22,990,632 elapsed=74.8s

  [4516/21087] intraday_13193.csv.gz  in=264,817,844 out=23,028,898 elapsed=74.8s

  [4517/21087] intraday_13197.csv.gz  in=264,852,154 out=23,063,208 elapsed=74.8s

  [4518/21087] intraday_1320.csv.gz  in=264,865,349 out=23,063,208 elapsed=74.9s

  [4519/21087] intraday_13198.csv.gz  in=264,904,272 out=23,102,131 elapsed=74.9s

  [4520/21087] intraday_13199.csv.gz  in=264,940,398 out=23,136,757 elapsed=74.9s

  [4521/21087] intraday_13200.csv.gz  in=264,977,558 out=23,173,917 elapsed=74.9s

  [4522/21087] intraday_13201.csv.gz  in=265,010,566 out=23,206,925 elapsed=74.9s

  [4523/21087] intraday_13204.csv.gz  in=265,022,144 out=23,218,503 elapsed=75.0s

  [4524/21087] intraday_13203.csv.gz  in=265,032,392 out=23,228,751 elapsed=75.0s

  [4525/21087] intraday_13202.csv.gz  in=265,069,662 out=23,266,021 elapsed=75.0s

  [4526/21087] intraday_13205.csv.gz  in=265,099,956 out=23,296,290 elapsed=75.0s

  [4527/21087] intraday_13206.csv.gz  in=265,128,063 out=23,324,397 elapsed=75.0s

  [4528/21087] intraday_1321.csv.gz  in=265,141,935 out=23,324,397 elapsed=75.1s

  [4529/21087] intraday_13207.csv.gz  in=265,184,265 out=23,366,727 elapsed=75.1s

  [4530/21087] intraday_13209.csv.gz  in=265,222,614 out=23,405,076 elapsed=75.1s

  [4531/21087] intraday_13208.csv.gz  in=265,264,231 out=23,446,458 elapsed=75.1s

  [4532/21087] intraday_13210.csv.gz  in=265,300,976 out=23,481,289 elapsed=75.1s

  [4533/21087] intraday_13213.csv.gz  in=265,315,848 out=23,496,161 elapsed=75.1s

  [4534/21087] intraday_13212.csv.gz  in=265,325,518 out=23,504,981 elapsed=75.1s

  [4535/21087] intraday_13211.csv.gz  in=265,361,900 out=23,541,363 elapsed=75.2s

  [4536/21087] intraday_13214.csv.gz  in=265,398,637 out=23,578,100 elapsed=75.2s

  [4537/21087] intraday_13215.csv.gz  in=265,437,314 out=23,616,777 elapsed=75.2s

  [4538/21087] intraday_13216.csv.gz  in=265,464,037 out=23,643,500 elapsed=75.2s

  [4539/21087] intraday_13217.csv.gz  in=265,504,220 out=23,683,683 elapsed=75.2s

  [4540/21087] intraday_1322.csv.gz  in=265,517,759 out=23,683,683 elapsed=75.2s

  [4541/21087] intraday_13218.csv.gz  in=265,555,718 out=23,721,642 elapsed=75.3s

  [4542/21087] intraday_13219.csv.gz  in=265,588,793 out=23,754,717 elapsed=75.3s

  [4543/21087] intraday_13221.csv.gz  in=265,613,731 out=23,779,655 elapsed=75.3s

  [4544/21087] intraday_13220.csv.gz  in=265,647,892 out=23,813,816 elapsed=75.3s

  [4545/21087] intraday_13222.csv.gz  in=265,675,339 out=23,841,263 elapsed=75.3s

  [4546/21087] intraday_13223.csv.gz  in=265,720,977 out=23,886,901 elapsed=75.3s

  [4547/21087] intraday_13224.csv.gz  in=265,752,100 out=23,918,024 elapsed=75.4s

  [4548/21087] intraday_13225.csv.gz  in=265,792,907 out=23,958,831 elapsed=75.4s

  [4549/21087] intraday_13226.csv.gz  in=265,825,526 out=23,991,450 elapsed=75.4s

  [4550/21087] intraday_13227.csv.gz  in=265,867,150 out=24,033,074 elapsed=75.4s

  [4551/21087] intraday_13228.csv.gz  in=265,905,892 out=24,066,940 elapsed=75.4s

  [4552/21087] intraday_1323.csv.gz  in=265,919,054 out=24,066,940 elapsed=75.4s

  [4553/21087] intraday_13229.csv.gz  in=265,953,342 out=24,101,228 elapsed=75.4s

  [4554/21087] intraday_13231.csv.gz  in=265,954,832 out=24,102,718 elapsed=75.5s

  [4555/21087] intraday_13230.csv.gz  in=265,987,237 out=24,135,123 elapsed=75.5s

  [4556/21087] intraday_13233.csv.gz  in=266,019,817 out=24,166,860 elapsed=75.5s

  [4557/21087] intraday_13234.csv.gz  in=266,060,173 out=24,207,216 elapsed=75.5s

  [4558/21087] intraday_13232.csv.gz  in=266,094,997 out=24,242,040 elapsed=75.5s

  [4559/21087] intraday_13235.csv.gz  in=266,130,174 out=24,277,217 elapsed=75.6s

  [4560/21087] intraday_13236.csv.gz  in=266,159,949 out=24,306,992 elapsed=75.6s

  [4561/21087] intraday_13237.csv.gz  in=266,195,080 out=24,342,123 elapsed=75.6s

  [4562/21087] intraday_13239.csv.gz  in=266,207,461 out=24,354,504 elapsed=75.6s

  [4563/21087] intraday_1324.csv.gz  in=266,220,840 out=24,354,504 elapsed=75.6s

  [4564/21087] intraday_13238.csv.gz  in=266,256,749 out=24,390,413 elapsed=75.6s

  [4565/21087] intraday_13240.csv.gz  in=266,277,332 out=24,410,996 elapsed=75.7s

  [4566/21087] intraday_13243.csv.gz  in=266,315,926 out=24,449,590 elapsed=75.7s

  [4567/21087] intraday_13242.csv.gz  in=266,357,552 out=24,485,578 elapsed=75.7s

  [4568/21087] intraday_13244.csv.gz  in=266,404,642 out=24,531,539 elapsed=75.7s

  [4569/21087] intraday_13241.csv.gz  in=266,439,153 out=24,566,050 elapsed=75.7s

  [4570/21087] intraday_13245.csv.gz  in=266,469,125 out=24,596,022 elapsed=75.8s

  [4571/21087] intraday_13248.csv.gz  in=266,503,362 out=24,630,259 elapsed=75.8s

  [4572/21087] intraday_13246.csv.gz  in=266,547,949 out=24,671,870 elapsed=75.8s

  [4573/21087] intraday_13249.csv.gz  in=266,548,763 out=24,672,684 elapsed=75.8s

  [4574/21087] intraday_1325.csv.gz  in=266,559,648 out=24,672,684 elapsed=75.8s

  [4575/21087] intraday_13247.csv.gz  in=266,605,146 out=24,718,182 elapsed=75.8s

  [4576/21087] intraday_13251.csv.gz  in=266,642,187 out=24,755,223 elapsed=75.9s

  [4577/21087] intraday_13250.csv.gz  in=266,682,908 out=24,795,944 elapsed=75.9s

  [4578/21087] intraday_13253.csv.gz  in=266,718,688 out=24,831,724 elapsed=75.9s

  [4579/21087] intraday_13252.csv.gz  in=266,753,758 out=24,866,794 elapsed=75.9s

  [4580/21087] intraday_13256.csv.gz  in=266,783,655 out=24,896,691 elapsed=76.0s

  [4581/21087] intraday_13254.csv.gz  in=266,814,055 out=24,927,091 elapsed=76.0s

  [4582/21087] intraday_13255.csv.gz  in=266,856,703 out=24,968,674 elapsed=76.0s

  [4583/21087] intraday_13257.csv.gz  in=266,894,826 out=25,006,797 elapsed=76.0s

  [4584/21087] intraday_13259.csv.gz  in=266,895,540 out=25,007,511 elapsed=76.0s

  [4585/21087] intraday_13260.csv.gz  in=266,896,734 out=25,008,705 elapsed=76.0s

  [4586/21087] intraday_1326.csv.gz  in=266,908,970 out=25,008,705 elapsed=76.0s

  [4587/21087] intraday_13258.csv.gz  in=266,939,768 out=25,039,503 elapsed=76.0s

  [4588/21087] intraday_13261.csv.gz  in=266,970,999 out=25,070,734 elapsed=76.0s

  [4589/21087] intraday_13262.csv.gz  in=267,007,447 out=25,107,182 elapsed=76.0s

  [4590/21087] intraday_13263.csv.gz  in=267,042,797 out=25,142,532 elapsed=76.1s

  [4591/21087] intraday_13264.csv.gz  in=267,084,855 out=25,184,590 elapsed=76.1s

  [4592/21087] intraday_13265.csv.gz  in=267,128,419 out=25,228,154 elapsed=76.1s

  [4593/21087] intraday_13266.csv.gz  in=267,167,539 out=25,267,274 elapsed=76.1s

  [4594/21087] intraday_1327.csv.gz  in=267,180,723 out=25,267,274 elapsed=76.1s

  [4595/21087] intraday_13267.csv.gz  in=267,223,173 out=25,309,724 elapsed=76.1s

  [4596/21087] intraday_13268.csv.gz  in=267,258,738 out=25,345,289 elapsed=76.2s

  [4597/21087] intraday_13269.csv.gz  in=267,291,563 out=25,378,114 elapsed=76.2s

  [4598/21087] intraday_13272.csv.gz  in=267,294,337 out=25,380,888 elapsed=76.2s

  [4599/21087] intraday_13270.csv.gz  in=267,329,374 out=25,415,925 elapsed=76.2s

  [4600/21087] intraday_13271.csv.gz  in=267,359,795 out=25,446,346 elapsed=76.2s

  [4601/21087] intraday_13273.csv.gz  in=267,392,407 out=25,478,958 elapsed=76.2s

  [4602/21087] intraday_13275.csv.gz  in=267,392,700 out=25,479,251 elapsed=76.2s

  [4603/21087] intraday_13274.csv.gz  in=267,392,950 out=25,479,501 elapsed=76.2s

  [4604/21087] intraday_13276.csv.gz  in=267,415,374 out=25,485,209 elapsed=76.2s

  [4605/21087] intraday_13277.csv.gz  in=267,415,912 out=25,485,747 elapsed=76.3s

  [4606/21087] intraday_13279.csv.gz  in=267,416,236 out=25,486,071 elapsed=76.3s

  [4607/21087] intraday_13278.csv.gz  in=267,416,645 out=25,486,480 elapsed=76.3s

  [4608/21087] intraday_1328.csv.gz  in=267,430,301 out=25,486,480 elapsed=76.3s

  [4609/21087] intraday_13280.csv.gz  in=267,431,120 out=25,487,299 elapsed=76.3s

  [4610/21087] intraday_13281.csv.gz  in=267,431,756 out=25,487,935 elapsed=76.3s

  [4611/21087] intraday_13282.csv.gz  in=267,432,031 out=25,488,210 elapsed=76.3s

  [4612/21087] intraday_13283.csv.gz  in=267,432,433 out=25,488,612 elapsed=76.3s

  [4613/21087] intraday_13284.csv.gz  in=267,433,025 out=25,489,204 elapsed=76.3s

  [4614/21087] intraday_13286.csv.gz  in=267,445,120 out=25,501,299 elapsed=76.3s

  [4615/21087] intraday_13285.csv.gz  in=267,460,111 out=25,516,215 elapsed=76.3s

  [4616/21087] intraday_13288.csv.gz  in=267,469,564 out=25,525,668 elapsed=76.3s

  [4617/21087] intraday_13287.csv.gz  in=267,481,872 out=25,537,976 elapsed=76.3s

  [4618/21087] intraday_1329.csv.gz  in=267,492,835 out=25,537,976 elapsed=76.3s

  [4619/21087] intraday_13289.csv.gz  in=267,504,290 out=25,549,431 elapsed=76.4s

  [4620/21087] intraday_13290.csv.gz  in=267,518,540 out=25,563,681 elapsed=76.4s

  [4621/21087] intraday_13291.csv.gz  in=267,532,884 out=25,578,025 elapsed=76.4s

  [4622/21087] intraday_13292.csv.gz  in=267,543,821 out=25,588,962 elapsed=76.4s

  [4623/21087] intraday_13293.csv.gz  in=267,555,773 out=25,600,914 elapsed=76.4s

  [4624/21087] intraday_13294.csv.gz  in=267,568,284 out=25,613,425 elapsed=76.4s

  [4625/21087] intraday_13295.csv.gz  in=267,578,720 out=25,623,861 elapsed=76.4s

  [4626/21087] intraday_13296.csv.gz  in=267,590,697 out=25,635,838 elapsed=76.4s

  [4627/21087] intraday_13297.csv.gz  in=267,601,579 out=25,646,720 elapsed=76.5s

  [4628/21087] intraday_13298.csv.gz  in=267,615,734 out=25,660,875 elapsed=76.5s

  [4629/21087] intraday_13299.csv.gz  in=267,618,481 out=25,663,622 elapsed=76.5s

  [4630/21087] intraday_1330.csv.gz  in=267,631,563 out=25,663,622 elapsed=76.5s

  [4631/21087] intraday_13300.csv.gz  in=267,640,810 out=25,672,869 elapsed=76.5s

  [4632/21087] intraday_13301.csv.gz  in=267,651,765 out=25,683,824 elapsed=76.5s

  [4633/21087] intraday_13303.csv.gz  in=267,662,977 out=25,695,036 elapsed=76.5s

  [4634/21087] intraday_13302.csv.gz  in=267,673,389 out=25,705,448 elapsed=76.5s

  [4635/21087] intraday_13304.csv.gz  in=267,686,027 out=25,718,086 elapsed=76.5s

  [4636/21087] intraday_13305.csv.gz  in=267,698,611 out=25,730,670 elapsed=76.5s

  [4637/21087] intraday_13308.csv.gz  in=267,708,845 out=25,740,904 elapsed=76.6s

  [4638/21087] intraday_13306.csv.gz  in=267,721,229 out=25,753,288 elapsed=76.6s

  [4639/21087] intraday_13307.csv.gz  in=267,733,438 out=25,765,497 elapsed=76.6s

  [4640/21087] intraday_13309.csv.gz  in=267,744,417 out=25,776,476 elapsed=76.6s

  [4641/21087] intraday_1331.csv.gz  in=267,763,460 out=25,776,476 elapsed=76.6s

  [4642/21087] intraday_13311.csv.gz  in=267,773,404 out=25,786,420 elapsed=76.6s

  [4643/21087] intraday_13312.csv.gz  in=267,781,188 out=25,794,204 elapsed=76.6s

  [4644/21087] intraday_13310.csv.gz  in=267,792,571 out=25,805,587 elapsed=76.6s

  [4645/21087] intraday_13313.csv.gz  in=267,798,058 out=25,811,074 elapsed=76.6s

  [4646/21087] intraday_13315.csv.gz  in=267,809,343 out=25,822,359 elapsed=76.7s

  [4647/21087] intraday_13314.csv.gz  in=267,821,573 out=25,834,589 elapsed=76.7s

  [4648/21087] intraday_13316.csv.gz  in=267,835,981 out=25,848,997 elapsed=76.7s

  [4649/21087] intraday_13317.csv.gz  in=267,847,915 out=25,860,931 elapsed=76.7s

  [4650/21087] intraday_1332.csv.gz  in=267,859,593 out=25,860,931 elapsed=76.7s

  [4651/21087] intraday_13320.csv.gz  in=267,868,374 out=25,869,712 elapsed=76.7s

  [4652/21087] intraday_13318.csv.gz  in=267,878,813 out=25,879,206 elapsed=76.7s

  [4653/21087] intraday_13319.csv.gz  in=267,889,843 out=25,890,236 elapsed=76.7s

  [4654/21087] intraday_13321.csv.gz  in=267,899,416 out=25,899,809 elapsed=76.7s

  [4655/21087] intraday_13325.csv.gz  in=267,904,773 out=25,905,166 elapsed=76.8s

  [4656/21087] intraday_13322.csv.gz  in=267,916,379 out=25,916,772 elapsed=76.8s

  [4657/21087] intraday_13323.csv.gz  in=267,927,999 out=25,928,392 elapsed=76.8s

  [4658/21087] intraday_13324.csv.gz  in=267,943,137 out=25,942,073 elapsed=76.8s

  [4659/21087] intraday_13326.csv.gz  in=267,943,138 out=25,942,074 elapsed=76.8s

  [4660/21087] intraday_13327.csv.gz  in=267,952,096 out=25,951,032 elapsed=76.8s

  [4661/21087] intraday_1333.csv.gz  in=267,967,273 out=25,951,032 elapsed=76.8s

  [4662/21087] intraday_13329.csv.gz  in=267,978,137 out=25,961,896 elapsed=76.8s

  [4663/21087] intraday_13330.csv.gz  in=267,988,502 out=25,972,261 elapsed=76.8s

  [4664/21087] intraday_13328.csv.gz  in=268,001,959 out=25,982,647 elapsed=76.8s

  [4665/21087] intraday_13331.csv.gz  in=268,011,890 out=25,992,578 elapsed=76.9s

  [4666/21087] intraday_13332.csv.gz  in=268,024,406 out=26,005,094 elapsed=76.9s

  [4667/21087] intraday_13334.csv.gz  in=268,035,273 out=26,015,961 elapsed=76.9s

  [4668/21087] intraday_13335.csv.gz  in=268,046,669 out=26,027,357 elapsed=76.9s

  [4669/21087] intraday_13333.csv.gz  in=268,057,868 out=26,038,556 elapsed=76.9s

  [4670/21087] intraday_13336.csv.gz  in=268,068,543 out=26,049,231 elapsed=76.9s

  [4671/21087] intraday_13337.csv.gz  in=268,080,545 out=26,061,233 elapsed=76.9s

  [4672/21087] intraday_13339.csv.gz  in=268,082,369 out=26,063,057 elapsed=76.9s

  [4673/21087] intraday_1334.csv.gz  in=268,094,582 out=26,063,057 elapsed=76.9s

  [4674/21087] intraday_13338.csv.gz  in=268,113,445 out=26,076,256 elapsed=76.9s

  [4675/21087] intraday_13340.csv.gz  in=268,117,058 out=26,079,869 elapsed=76.9s

  [4676/21087] intraday_13342.csv.gz  in=268,127,215 out=26,090,026 elapsed=77.0s

  [4677/21087] intraday_13341.csv.gz  in=268,144,089 out=26,101,408 elapsed=77.0s

  [4678/21087] intraday_13343.csv.gz  in=268,152,688 out=26,110,007 elapsed=77.0s

  [4679/21087] intraday_13344.csv.gz  in=268,166,595 out=26,123,914 elapsed=77.0s

  [4680/21087] intraday_13345.csv.gz  in=268,179,952 out=26,137,271 elapsed=77.0s

  [4681/21087] intraday_13346.csv.gz  in=268,196,413 out=26,151,270 elapsed=77.0s

  [4682/21087] intraday_13347.csv.gz  in=268,208,351 out=26,163,208 elapsed=77.0s

  [4683/21087] intraday_13348.csv.gz  in=268,219,284 out=26,174,141 elapsed=77.0s

  [4684/21087] intraday_13349.csv.gz  in=268,227,461 out=26,182,318 elapsed=77.0s

  [4685/21087] intraday_1335.csv.gz  in=268,239,487 out=26,182,318 elapsed=77.0s

  [4686/21087] intraday_13350.csv.gz  in=268,251,016 out=26,193,743 elapsed=77.1s

  [4687/21087] intraday_13351.csv.gz  in=268,262,936 out=26,205,663 elapsed=77.1s

  [4688/21087] intraday_13352.csv.gz  in=268,275,982 out=26,218,709 elapsed=77.1s

  [4689/21087] intraday_13354.csv.gz  in=268,276,662 out=26,219,389 elapsed=77.1s

  [4690/21087] intraday_13353.csv.gz  in=268,284,080 out=26,226,807 elapsed=77.1s

  [4691/21087] intraday_13355.csv.gz  in=268,296,368 out=26,239,095 elapsed=77.1s

  [4692/21087] intraday_13357.csv.gz  in=268,308,306 out=26,251,033 elapsed=77.1s

  [4693/21087] intraday_13356.csv.gz  in=268,319,877 out=26,262,604 elapsed=77.1s

  [4694/21087] intraday_13359.csv.gz  in=268,329,057 out=26,271,784 elapsed=77.1s

  [4695/21087] intraday_13358.csv.gz  in=268,340,501 out=26,283,228 elapsed=77.2s

  [4696/21087] intraday_1336.csv.gz  in=268,354,480 out=26,283,228 elapsed=77.2s

  [4697/21087] intraday_13360.csv.gz  in=268,365,945 out=26,294,693 elapsed=77.2s

  [4698/21087] intraday_13361.csv.gz  in=268,377,341 out=26,306,089 elapsed=77.2s

  [4699/21087] intraday_13362.csv.gz  in=268,390,956 out=26,319,704 elapsed=77.2s

  [4700/21087] intraday_13363.csv.gz  in=268,404,622 out=26,333,370 elapsed=77.2s

  [4701/21087] intraday_13364.csv.gz  in=268,417,915 out=26,346,663 elapsed=77.2s

  [4702/21087] intraday_13365.csv.gz  in=268,428,709 out=26,357,457 elapsed=77.2s

  [4703/21087] intraday_13366.csv.gz  in=268,441,239 out=26,369,987 elapsed=77.2s

  [4704/21087] intraday_13367.csv.gz  in=268,452,189 out=26,380,937 elapsed=77.3s

  [4705/21087] intraday_1337.csv.gz  in=268,467,057 out=26,380,937 elapsed=77.3s

  [4706/21087] intraday_13369.csv.gz  in=268,483,202 out=26,394,264 elapsed=77.3s

  [4707/21087] intraday_13368.csv.gz  in=268,495,082 out=26,406,144 elapsed=77.3s

  [4708/21087] intraday_13370.csv.gz  in=268,506,234 out=26,417,296 elapsed=77.3s

  [4709/21087] intraday_13371.csv.gz  in=268,520,029 out=26,431,091 elapsed=77.3s

  [4710/21087] intraday_13373.csv.gz  in=268,531,603 out=26,442,665 elapsed=77.3s

  [4711/21087] intraday_13372.csv.gz  in=268,543,707 out=26,454,769 elapsed=77.3s

  [4712/21087] intraday_13374.csv.gz  in=268,554,642 out=26,465,704 elapsed=77.4s

  [4713/21087] intraday_13375.csv.gz  in=268,567,030 out=26,478,092 elapsed=77.4s

  [4714/21087] intraday_13377.csv.gz  in=268,576,479 out=26,487,503 elapsed=77.4s

  [4715/21087] intraday_13376.csv.gz  in=268,587,787 out=26,498,811 elapsed=77.4s

  [4716/21087] intraday_13378.csv.gz  in=268,599,626 out=26,510,650 elapsed=77.4s

  [4717/21087] intraday_13379.csv.gz  in=268,609,843 out=26,520,867 elapsed=77.4s

  [4718/21087] intraday_1338.csv.gz  in=268,622,463 out=26,520,867 elapsed=77.4s

  [4719/21087] intraday_13380.csv.gz  in=268,634,424 out=26,532,828 elapsed=77.4s

  [4720/21087] intraday_13381.csv.gz  in=268,645,491 out=26,543,895 elapsed=77.4s

  [4721/21087] intraday_13382.csv.gz  in=268,657,396 out=26,555,800 elapsed=77.4s

  [4722/21087] intraday_13383.csv.gz  in=268,670,235 out=26,568,639 elapsed=77.5s

  [4723/21087] intraday_13384.csv.gz  in=268,681,075 out=26,579,479 elapsed=77.5s

  [4724/21087] intraday_13385.csv.gz  in=268,695,324 out=26,593,728 elapsed=77.5s

  [4725/21087] intraday_13386.csv.gz  in=268,706,277 out=26,604,681 elapsed=77.5s

  [4726/21087] intraday_13388.csv.gz  in=268,718,144 out=26,616,548 elapsed=77.5s

  [4727/21087] intraday_13387.csv.gz  in=268,728,984 out=26,627,388 elapsed=77.5s

  [4728/21087] intraday_1339.csv.gz  in=268,743,226 out=26,627,388 elapsed=77.5s

  [4729/21087] intraday_13389.csv.gz  in=268,756,871 out=26,641,033 elapsed=77.5s

  [4730/21087] intraday_13391.csv.gz  in=268,769,511 out=26,653,673 elapsed=77.5s

  [4731/21087] intraday_13390.csv.gz  in=268,779,495 out=26,663,657 elapsed=77.5s

  [4732/21087] intraday_13393.csv.gz  in=268,791,789 out=26,675,951 elapsed=77.6s

  [4733/21087] intraday_13392.csv.gz  in=268,805,741 out=26,689,903 elapsed=77.6s

  [4734/21087] intraday_13394.csv.gz  in=268,819,824 out=26,703,986 elapsed=77.6s

  [4735/21087] intraday_13395.csv.gz  in=268,834,092 out=26,718,254 elapsed=77.6s

  [4736/21087] intraday_13397.csv.gz  in=268,847,479 out=26,731,641 elapsed=77.6s

  [4737/21087] intraday_13396.csv.gz  in=268,864,335 out=26,748,497 elapsed=77.6s

  [4738/21087] intraday_13398.csv.gz  in=268,877,741 out=26,761,903 elapsed=77.6s

  [4739/21087] intraday_13399.csv.gz  in=268,890,303 out=26,774,465 elapsed=77.6s

  [4740/21087] intraday_1340.csv.gz  in=268,902,233 out=26,774,465 elapsed=77.6s

  [4741/21087] intraday_13400.csv.gz  in=268,914,052 out=26,786,284 elapsed=77.6s

  [4742/21087] intraday_13402.csv.gz  in=268,926,668 out=26,798,900 elapsed=77.7s

  [4743/21087] intraday_13403.csv.gz  in=268,936,688 out=26,808,920 elapsed=77.7s

  [4744/21087] intraday_13401.csv.gz  in=268,945,582 out=26,817,814 elapsed=77.7s

  [4745/21087] intraday_13404.csv.gz  in=268,956,579 out=26,828,811 elapsed=77.7s

  [4746/21087] intraday_13405.csv.gz  in=268,968,817 out=26,841,049 elapsed=77.7s

  [4747/21087] intraday_13406.csv.gz  in=268,982,527 out=26,854,759 elapsed=77.7s

  [4748/21087] intraday_13407.csv.gz  in=268,991,380 out=26,863,612 elapsed=77.7s

  [4749/21087] intraday_13408.csv.gz  in=269,001,814 out=26,874,046 elapsed=77.7s

  [4750/21087] intraday_1341.csv.gz  in=269,017,974 out=26,874,046 elapsed=77.7s

  [4751/21087] intraday_13409.csv.gz  in=269,029,890 out=26,885,962 elapsed=77.7s

  [4752/21087] intraday_13412.csv.gz  in=269,043,554 out=26,899,626 elapsed=77.8s

  [4753/21087] intraday_13410.csv.gz  in=269,053,840 out=26,909,912 elapsed=77.8s

  [4754/21087] intraday_13411.csv.gz  in=269,066,371 out=26,922,443 elapsed=77.8s

  [4755/21087] intraday_13413.csv.gz  in=269,079,688 out=26,935,760 elapsed=77.8s

  [4756/21087] intraday_13416.csv.gz  in=269,090,541 out=26,946,613 elapsed=77.8s

  [4757/21087] intraday_13414.csv.gz  in=269,102,168 out=26,958,240 elapsed=77.8s

  [4758/21087] intraday_13417.csv.gz  in=269,112,836 out=26,968,908 elapsed=77.8s

  [4759/21087] intraday_13415.csv.gz  in=269,127,581 out=26,983,653 elapsed=77.9s

  [4760/21087] intraday_13418.csv.gz  in=269,139,552 out=26,995,624 elapsed=77.9s

  [4761/21087] intraday_1342.csv.gz  in=269,151,050 out=26,995,624 elapsed=77.9s

  [4762/21087] intraday_13419.csv.gz  in=269,162,567 out=27,007,141 elapsed=77.9s

  [4763/21087] intraday_13420.csv.gz  in=269,172,314 out=27,016,888 elapsed=77.9s

  [4764/21087] intraday_13421.csv.gz  in=269,177,981 out=27,022,555 elapsed=77.9s

  [4765/21087] intraday_13424.csv.gz  in=269,178,157 out=27,022,731 elapsed=77.9s

  [4766/21087] intraday_13422.csv.gz  in=269,190,191 out=27,034,765 elapsed=77.9s

  [4767/21087] intraday_13425.csv.gz  in=269,190,656 out=27,035,230 elapsed=77.9s

  [4768/21087] intraday_13426.csv.gz  in=269,191,399 out=27,035,973 elapsed=77.9s

  [4769/21087] intraday_13423.csv.gz  in=269,198,989 out=27,043,563 elapsed=77.9s

  [4770/21087] intraday_13427.csv.gz  in=269,199,694 out=27,044,268 elapsed=77.9s

  [4771/21087] intraday_13429.csv.gz  in=269,200,101 out=27,044,675 elapsed=77.9s

  [4772/21087] intraday_13428.csv.gz  in=269,200,266 out=27,044,840 elapsed=78.0s

  [4773/21087] intraday_1343.csv.gz  in=269,213,505 out=27,044,840 elapsed=78.0s

  [4774/21087] intraday_13430.csv.gz  in=269,213,898 out=27,045,233 elapsed=78.0s

  [4775/21087] intraday_13432.csv.gz  in=269,214,381 out=27,045,716 elapsed=78.0s

  [4776/21087] intraday_13431.csv.gz  in=269,214,676 out=27,046,011 elapsed=78.0s

  [4777/21087] intraday_13433.csv.gz  in=269,215,236 out=27,046,571 elapsed=78.0s

  [4778/21087] intraday_13434.csv.gz  in=269,215,792 out=27,047,127 elapsed=78.0s

  [4779/21087] intraday_13435.csv.gz  in=269,216,020 out=27,047,355 elapsed=78.0s

  [4780/21087] intraday_13436.csv.gz  in=269,216,686 out=27,048,021 elapsed=78.0s

  [4781/21087] intraday_13438.csv.gz  in=269,216,981 out=27,048,316 elapsed=78.0s

  [4782/21087] intraday_13437.csv.gz  in=269,217,670 out=27,049,005 elapsed=78.0s

  [4783/21087] intraday_13439.csv.gz  in=269,217,963 out=27,049,298 elapsed=78.0s

  [4784/21087] intraday_13441.csv.gz  in=269,218,321 out=27,049,656 elapsed=78.0s

  [4785/21087] intraday_13440.csv.gz  in=269,218,593 out=27,049,928 elapsed=78.0s

  [4786/21087] intraday_13442.csv.gz  in=269,218,668 out=27,050,003 elapsed=78.0s

  [4787/21087] intraday_1344.csv.gz  in=269,233,924 out=27,050,003 elapsed=78.0s

  [4788/21087] intraday_13443.csv.gz  in=269,234,097 out=27,050,176 elapsed=78.0s

  [4789/21087] intraday_13446.csv.gz  in=269,234,239 out=27,050,318 elapsed=78.0s

  [4790/21087] intraday_13445.csv.gz  in=269,234,974 out=27,050,926 elapsed=78.0s

  [4791/21087] intraday_13447.csv.gz  in=269,235,543 out=27,051,495 elapsed=78.0s

  [4792/21087] intraday_13448.csv.gz  in=269,235,994 out=27,051,946 elapsed=78.0s

  [4793/21087] intraday_13444.csv.gz  in=269,252,364 out=27,057,412 elapsed=78.1s

  [4794/21087] intraday_13451.csv.gz  in=269,252,514 out=27,057,562 elapsed=78.1s

  [4795/21087] intraday_13450.csv.gz  in=269,253,194 out=27,058,242 elapsed=78.1s

  [4796/21087] intraday_13449.csv.gz  in=269,253,942 out=27,058,990 elapsed=78.1s

  [4797/21087] intraday_1345.csv.gz  in=269,268,286 out=27,058,990 elapsed=78.1s

  [4798/21087] intraday_13452.csv.gz  in=269,268,675 out=27,059,379 elapsed=78.1s

  [4799/21087] intraday_13453.csv.gz  in=269,268,895 out=27,059,599 elapsed=78.1s

  [4800/21087] intraday_13455.csv.gz  in=269,269,013 out=27,059,717 elapsed=78.1s

  [4801/21087] intraday_13454.csv.gz  in=269,271,273 out=27,061,977 elapsed=78.1s

  [4802/21087] intraday_13456.csv.gz  in=269,271,722 out=27,062,426 elapsed=78.1s

  [4803/21087] intraday_13457.csv.gz  in=269,271,866 out=27,062,570 elapsed=78.1s

  [4804/21087] intraday_13458.csv.gz  in=269,271,898 out=27,062,602 elapsed=78.1s

  [4805/21087] intraday_13459.csv.gz  in=269,272,050 out=27,062,754 elapsed=78.1s

  [4806/21087] intraday_13460.csv.gz  in=269,272,201 out=27,062,905 elapsed=78.2s

  [4807/21087] intraday_1346.csv.gz  in=269,284,751 out=27,062,905 elapsed=78.2s

  [4808/21087] intraday_13462.csv.gz  in=269,285,013 out=27,063,167 elapsed=78.2s

  [4809/21087] intraday_13463.csv.gz  in=269,285,047 out=27,063,201 elapsed=78.2s

  [4810/21087] intraday_13461.csv.gz  in=269,285,416 out=27,063,531 elapsed=78.2s

  [4811/21087] intraday_13465.csv.gz  in=269,285,569 out=27,063,684 elapsed=78.2s

  [4812/21087] intraday_13464.csv.gz  in=269,285,960 out=27,064,075 elapsed=78.2s

  [4813/21087] intraday_13467.csv.gz  in=269,286,136 out=27,064,251 elapsed=78.2s

  [4814/21087] intraday_13466.csv.gz  in=269,286,673 out=27,064,788 elapsed=78.2s

  [4815/21087] intraday_13468.csv.gz  in=269,286,799 out=27,064,914 elapsed=78.2s

  [4816/21087] intraday_13469.csv.gz  in=269,287,529 out=27,065,644 elapsed=78.2s

  [4817/21087] intraday_13470.csv.gz  in=269,288,366 out=27,066,481 elapsed=78.2s

  [4818/21087] intraday_13471.csv.gz  in=269,288,922 out=27,067,037 elapsed=78.2s

  [4819/21087] intraday_13473.csv.gz  in=269,289,113 out=27,067,228 elapsed=78.2s

  [4820/21087] intraday_1347.csv.gz  in=269,304,481 out=27,067,228 elapsed=78.2s

  [4821/21087] intraday_13474.csv.gz  in=269,304,622 out=27,067,369 elapsed=78.2s

  [4822/21087] intraday_13472.csv.gz  in=269,304,802 out=27,067,549 elapsed=78.2s

  [4823/21087] intraday_13476.csv.gz  in=269,305,126 out=27,067,873 elapsed=78.2s

  [4824/21087] intraday_13478.csv.gz  in=269,305,609 out=27,068,356 elapsed=78.2s

  [4825/21087] intraday_13477.csv.gz  in=269,305,841 out=27,068,588 elapsed=78.2s

  [4826/21087] intraday_13475.csv.gz  in=269,315,287 out=27,071,278 elapsed=78.2s

  [4827/21087] intraday_1348.csv.gz  in=269,326,165 out=27,071,278 elapsed=78.3s

  [4828/21087] intraday_13479.csv.gz  in=269,326,319 out=27,071,432 elapsed=78.3s

  [4829/21087] intraday_13481.csv.gz  in=269,326,478 out=27,071,591 elapsed=78.3s

  [4830/21087] intraday_13480.csv.gz  in=269,326,528 out=27,071,641 elapsed=78.3s

  [4831/21087] intraday_13482.csv.gz  in=269,327,583 out=27,072,696 elapsed=78.3s

  [4832/21087] intraday_13483.csv.gz  in=269,328,340 out=27,073,453 elapsed=78.3s

  [4833/21087] intraday_13484.csv.gz  in=269,328,784 out=27,073,897 elapsed=78.3s

  [4834/21087] intraday_13485.csv.gz  in=269,328,813 out=27,073,926 elapsed=78.3s

  [4835/21087] intraday_13486.csv.gz  in=269,329,499 out=27,074,612 elapsed=78.3s

  [4836/21087] intraday_13487.csv.gz  in=269,330,105 out=27,074,850 elapsed=78.3s

  [4837/21087] intraday_13489.csv.gz  in=269,330,580 out=27,075,325 elapsed=78.3s

  [4838/21087] intraday_13488.csv.gz  in=269,330,997 out=27,075,742 elapsed=78.3s

  [4839/21087] intraday_13490.csv.gz  in=269,331,334 out=27,076,079 elapsed=78.3s

  [4840/21087] intraday_13491.csv.gz  in=269,331,588 out=27,076,333 elapsed=78.3s

  [4841/21087] intraday_13492.csv.gz  in=269,332,150 out=27,076,895 elapsed=78.3s

  [4842/21087] intraday_1349.csv.gz  in=269,344,432 out=27,076,895 elapsed=78.3s

  [4843/21087] intraday_13494.csv.gz  in=269,344,652 out=27,077,115 elapsed=78.3s

  [4844/21087] intraday_13493.csv.gz  in=269,344,917 out=27,077,380 elapsed=78.3s

  [4845/21087] intraday_13495.csv.gz  in=269,345,152 out=27,077,615 elapsed=78.3s

  [4846/21087] intraday_13496.csv.gz  in=269,345,691 out=27,078,154 elapsed=78.3s

  [4847/21087] intraday_13498.csv.gz  in=269,345,714 out=27,078,177 elapsed=78.3s

  [4848/21087] intraday_13497.csv.gz  in=269,346,130 out=27,078,593 elapsed=78.4s

  [4849/21087] intraday_13499.csv.gz  in=269,346,568 out=27,079,031 elapsed=78.4s

  [4850/21087] intraday_13500.csv.gz  in=269,347,150 out=27,079,613 elapsed=78.4s

  [4851/21087] intraday_13501.csv.gz  in=269,348,639 out=27,080,905 elapsed=78.4s

  [4852/21087] intraday_13502.csv.gz  in=269,349,366 out=27,081,632 elapsed=78.4s

  [4853/21087] intraday_1350.csv.gz  in=269,360,802 out=27,081,632 elapsed=78.4s

  [4854/21087] intraday_13503.csv.gz  in=269,361,688 out=27,082,518 elapsed=78.4s

  [4855/21087] intraday_13506.csv.gz  in=269,361,971 out=27,082,801 elapsed=78.4s

  [4856/21087] intraday_13505.csv.gz  in=269,362,314 out=27,083,144 elapsed=78.4s

  [4857/21087] intraday_13504.csv.gz  in=269,362,816 out=27,083,646 elapsed=78.4s

  [4858/21087] intraday_13507.csv.gz  in=269,363,614 out=27,084,444 elapsed=78.4s

  [4859/21087] intraday_13509.csv.gz  in=269,363,889 out=27,084,719 elapsed=78.4s

  [4860/21087] intraday_1351.csv.gz  in=269,379,115 out=27,084,719 elapsed=78.4s

  [4861/21087] intraday_13510.csv.gz  in=269,379,777 out=27,085,381 elapsed=78.4s

  [4862/21087] intraday_13511.csv.gz  in=269,380,186 out=27,085,790 elapsed=78.4s

  [4863/21087] intraday_13508.csv.gz  in=269,405,024 out=27,092,620 elapsed=78.5s

  [4864/21087] intraday_13513.csv.gz  in=269,405,196 out=27,092,792 elapsed=78.5s

  [4865/21087] intraday_13512.csv.gz  in=269,405,487 out=27,093,083 elapsed=78.5s

  [4866/21087] intraday_13514.csv.gz  in=269,405,912 out=27,093,508 elapsed=78.5s

  [4867/21087] intraday_13515.csv.gz  in=269,406,176 out=27,093,772 elapsed=78.5s

  [4868/21087] intraday_13517.csv.gz  in=269,406,297 out=27,093,893 elapsed=78.5s

  [4869/21087] intraday_13516.csv.gz  in=269,406,913 out=27,094,509 elapsed=78.5s

  [4870/21087] intraday_13518.csv.gz  in=269,407,034 out=27,094,630 elapsed=78.5s

  [4871/21087] intraday_13519.csv.gz  in=269,407,413 out=27,095,009 elapsed=78.5s

  [4872/21087] intraday_13521.csv.gz  in=269,408,029 out=27,095,625 elapsed=78.5s

  [4873/21087] intraday_13520.csv.gz  in=269,409,134 out=27,096,730 elapsed=78.5s

  [4874/21087] intraday_13522.csv.gz  in=269,409,788 out=27,097,384 elapsed=78.5s

  [4875/21087] intraday_1352.csv.gz  in=269,423,270 out=27,097,384 elapsed=78.5s

  [4876/21087] intraday_13523.csv.gz  in=269,423,544 out=27,097,658 elapsed=78.5s

  [4877/21087] intraday_13524.csv.gz  in=269,424,045 out=27,098,159 elapsed=78.5s

  [4878/21087] intraday_13525.csv.gz  in=269,424,143 out=27,098,257 elapsed=78.5s

  [4879/21087] intraday_13527.csv.gz  in=269,424,362 out=27,098,476 elapsed=78.5s

  [4880/21087] intraday_13526.csv.gz  in=269,425,452 out=27,099,566 elapsed=78.5s

  [4881/21087] intraday_13529.csv.gz  in=269,425,625 out=27,099,739 elapsed=78.5s

  [4882/21087] intraday_13528.csv.gz  in=269,425,989 out=27,100,103 elapsed=78.5s

  [4883/21087] intraday_13530.csv.gz  in=269,426,423 out=27,100,537 elapsed=78.5s

  [4884/21087] intraday_13531.csv.gz  in=269,427,622 out=27,101,736 elapsed=78.5s

  [4885/21087] intraday_13532.csv.gz  in=269,428,407 out=27,102,521 elapsed=78.5s

  [4886/21087] intraday_1353.csv.gz  in=269,444,733 out=27,102,521 elapsed=78.6s

  [4887/21087] intraday_13533.csv.gz  in=269,446,019 out=27,103,807 elapsed=78.6s

  [4888/21087] intraday_13534.csv.gz  in=269,446,961 out=27,104,749 elapsed=78.6s

  [4889/21087] intraday_13535.csv.gz  in=269,448,259 out=27,106,047 elapsed=78.6s

  [4890/21087] intraday_13536.csv.gz  in=269,449,027 out=27,106,815 elapsed=78.6s

  [4891/21087] intraday_13537.csv.gz  in=269,449,449 out=27,107,237 elapsed=78.6s

  [4892/21087] intraday_13539.csv.gz  in=269,449,628 out=27,107,416 elapsed=78.6s

  [4893/21087] intraday_13538.csv.gz  in=269,450,356 out=27,108,144 elapsed=78.6s

  [4894/21087] intraday_13540.csv.gz  in=269,450,564 out=27,108,352 elapsed=78.6s

  [4895/21087] intraday_13541.csv.gz  in=269,450,844 out=27,108,632 elapsed=78.6s

  [4896/21087] intraday_13542.csv.gz  in=269,451,025 out=27,108,813 elapsed=78.6s

  [4897/21087] intraday_13543.csv.gz  in=269,451,195 out=27,108,983 elapsed=78.6s

  [4898/21087] intraday_1354.csv.gz  in=269,464,515 out=27,108,983 elapsed=78.6s

  [4899/21087] intraday_13544.csv.gz  in=269,465,102 out=27,109,570 elapsed=78.6s

  [4900/21087] intraday_13546.csv.gz  in=269,465,284 out=27,109,752 elapsed=78.6s

  [4901/21087] intraday_13545.csv.gz  in=269,466,135 out=27,110,603 elapsed=78.6s

  [4902/21087] intraday_13547.csv.gz  in=269,466,527 out=27,110,995 elapsed=78.6s

  [4903/21087] intraday_13548.csv.gz  in=269,467,004 out=27,111,472 elapsed=78.6s

  [4904/21087] intraday_13549.csv.gz  in=269,467,377 out=27,111,845 elapsed=78.6s

  [4905/21087] intraday_1355.csv.gz  in=269,479,882 out=27,111,845 elapsed=78.7s

  [4906/21087] intraday_13550.csv.gz  in=269,480,476 out=27,112,439 elapsed=78.7s

  [4907/21087] intraday_13551.csv.gz  in=269,480,657 out=27,112,620 elapsed=78.7s

  [4908/21087] intraday_13552.csv.gz  in=269,480,852 out=27,112,815 elapsed=78.7s

  [4909/21087] intraday_13553.csv.gz  in=269,481,317 out=27,113,280 elapsed=78.7s

  [4910/21087] intraday_13555.csv.gz  in=269,482,024 out=27,113,987 elapsed=78.7s

  [4911/21087] intraday_13554.csv.gz  in=269,482,263 out=27,114,226 elapsed=78.7s

  [4912/21087] intraday_13556.csv.gz  in=269,482,578 out=27,114,541 elapsed=78.7s

  [4913/21087] intraday_13557.csv.gz  in=269,482,997 out=27,114,960 elapsed=78.7s

  [4914/21087] intraday_13558.csv.gz  in=269,483,328 out=27,115,291 elapsed=78.7s

  [4915/21087] intraday_13559.csv.gz  in=269,483,845 out=27,115,808 elapsed=78.7s

  [4916/21087] intraday_13561.csv.gz  in=269,484,464 out=27,116,427 elapsed=78.7s

  [4917/21087] intraday_13560.csv.gz  in=269,486,035 out=27,117,320 elapsed=78.7s

  [4918/21087] intraday_13562.csv.gz  in=269,486,118 out=27,117,403 elapsed=78.7s

  [4919/21087] intraday_1356.csv.gz  in=269,501,306 out=27,117,403 elapsed=78.7s

  [4920/21087] intraday_13564.csv.gz  in=269,526,540 out=27,142,637 elapsed=78.8s

  [4921/21087] intraday_13566.csv.gz  in=269,549,395 out=27,165,492 elapsed=78.8s

  [4922/21087] intraday_13563.csv.gz  in=269,582,203 out=27,198,300 elapsed=78.8s

  [4923/21087] intraday_13565.csv.gz  in=269,606,865 out=27,222,962 elapsed=78.8s

  [4924/21087] intraday_1357.csv.gz  in=269,620,245 out=27,222,962 elapsed=78.8s

  [4925/21087] intraday_13567.csv.gz  in=269,645,549 out=27,248,266 elapsed=78.8s

  [4926/21087] intraday_13568.csv.gz  in=269,676,879 out=27,279,596 elapsed=78.9s

  [4927/21087] intraday_13569.csv.gz  in=269,705,114 out=27,307,831 elapsed=78.9s

  [4928/21087] intraday_13570.csv.gz  in=269,726,756 out=27,329,473 elapsed=78.9s

  [4929/21087] intraday_13571.csv.gz  in=269,739,224 out=27,341,941 elapsed=78.9s

  [4930/21087] intraday_13572.csv.gz  in=269,765,002 out=27,367,719 elapsed=78.9s

  [4931/21087] intraday_13574.csv.gz  in=269,782,605 out=27,385,322 elapsed=78.9s

  [4932/21087] intraday_13573.csv.gz  in=269,811,927 out=27,414,508 elapsed=78.9s

  [4933/21087] intraday_13575.csv.gz  in=269,840,393 out=27,439,956 elapsed=79.0s

  [4934/21087] intraday_13576.csv.gz  in=269,867,585 out=27,467,148 elapsed=79.0s

  [4935/21087] intraday_13577.csv.gz  in=269,893,083 out=27,492,646 elapsed=79.0s

  [4936/21087] intraday_13578.csv.gz  in=269,915,175 out=27,514,738 elapsed=79.0s

  [4937/21087] intraday_1358.csv.gz  in=269,928,483 out=27,514,738 elapsed=79.0s

  [4938/21087] intraday_13579.csv.gz  in=269,949,867 out=27,536,122 elapsed=79.0s

  [4939/21087] intraday_13581.csv.gz  in=269,952,158 out=27,538,413 elapsed=79.0s

  [4940/21087] intraday_13580.csv.gz  in=269,972,066 out=27,558,321 elapsed=79.0s

  [4941/21087] intraday_13582.csv.gz  in=269,996,061 out=27,582,316 elapsed=79.0s

  [4942/21087] intraday_13583.csv.gz  in=270,017,497 out=27,603,752 elapsed=79.1s

  [4943/21087] intraday_13584.csv.gz  in=270,039,775 out=27,626,030 elapsed=79.1s

  [4944/21087] intraday_13585.csv.gz  in=270,062,140 out=27,648,395 elapsed=79.1s

  [4945/21087] intraday_13587.csv.gz  in=270,089,002 out=27,675,257 elapsed=79.1s

  [4946/21087] intraday_13586.csv.gz  in=270,113,246 out=27,699,501 elapsed=79.1s

  [4947/21087] intraday_13588.csv.gz  in=270,143,047 out=27,729,302 elapsed=79.1s

  [4948/21087] intraday_13589.csv.gz  in=270,171,313 out=27,757,568 elapsed=79.1s

  [4949/21087] intraday_1359.csv.gz  in=270,187,049 out=27,757,568 elapsed=79.1s

  [4950/21087] intraday_13590.csv.gz  in=270,208,446 out=27,778,965 elapsed=79.2s

  [4951/21087] intraday_13591.csv.gz  in=270,230,015 out=27,800,534 elapsed=79.2s

  [4952/21087] intraday_13592.csv.gz  in=270,252,367 out=27,822,886 elapsed=79.2s

  [4953/21087] intraday_13593.csv.gz  in=270,275,433 out=27,845,952 elapsed=79.2s

  [4954/21087] intraday_13594.csv.gz  in=270,293,650 out=27,864,169 elapsed=79.2s

  [4955/21087] intraday_13595.csv.gz  in=270,316,332 out=27,885,805 elapsed=79.2s

  [4956/21087] intraday_13597.csv.gz  in=270,338,329 out=27,907,802 elapsed=79.3s

  [4957/21087] intraday_13599.csv.gz  in=270,367,277 out=27,936,750 elapsed=79.3s

  [4958/21087] intraday_13598.csv.gz  in=270,392,094 out=27,961,567 elapsed=79.3s

  [4959/21087] intraday_1360.csv.gz  in=270,406,468 out=27,961,567 elapsed=79.3s

  [4960/21087] intraday_13596.csv.gz  in=270,432,344 out=27,987,443 elapsed=79.3s

  [4961/21087] intraday_13603.csv.gz  in=270,432,346 out=27,987,445 elapsed=79.3s

  [4962/21087] intraday_13602.csv.gz  in=270,457,003 out=28,012,102 elapsed=79.3s

  [4963/21087] intraday_13601.csv.gz  in=270,479,165 out=28,034,264 elapsed=79.3s

  [4964/21087] intraday_13600.csv.gz  in=270,504,240 out=28,059,339 elapsed=79.3s

  [4965/21087] intraday_13604.csv.gz  in=270,522,378 out=28,077,477 elapsed=79.4s

  [4966/21087] intraday_13606.csv.gz  in=270,544,122 out=28,099,221 elapsed=79.4s

  [4967/21087] intraday_13605.csv.gz  in=270,573,004 out=28,128,103 elapsed=79.4s

  [4968/21087] intraday_13608.csv.gz  in=270,598,147 out=28,153,246 elapsed=79.4s

  [4969/21087] intraday_13607.csv.gz  in=270,620,893 out=28,175,992 elapsed=79.4s

  [4970/21087] intraday_1361.csv.gz  in=270,635,338 out=28,175,992 elapsed=79.5s

  [4971/21087] intraday_13609.csv.gz  in=270,658,117 out=28,198,771 elapsed=79.5s

  [4972/21087] intraday_13611.csv.gz  in=270,679,088 out=28,219,742 elapsed=79.5s

  [4973/21087] intraday_13610.csv.gz  in=270,705,089 out=28,245,743 elapsed=79.5s

  [4974/21087] intraday_13612.csv.gz  in=270,726,738 out=28,267,392 elapsed=79.5s

  [4975/21087] intraday_13616.csv.gz  in=270,727,573 out=28,268,227 elapsed=79.5s

  [4976/21087] intraday_13615.csv.gz  in=270,737,175 out=28,277,829 elapsed=79.5s

  [4977/21087] intraday_13613.csv.gz  in=270,763,102 out=28,303,756 elapsed=79.5s

  [4978/21087] intraday_13614.csv.gz  in=270,799,192 out=28,328,959 elapsed=79.6s

  [4979/21087] intraday_13617.csv.gz  in=270,823,037 out=28,352,804 elapsed=79.6s

  [4980/21087] intraday_1362.csv.gz  in=270,835,457 out=28,352,804 elapsed=79.6s

  [4981/21087] intraday_13618.csv.gz  in=270,867,528 out=28,384,875 elapsed=79.6s

  [4982/21087] intraday_13619.csv.gz  in=270,895,668 out=28,413,015 elapsed=79.6s

  [4983/21087] intraday_13620.csv.gz  in=270,922,431 out=28,439,778 elapsed=79.6s

  [4984/21087] intraday_13621.csv.gz  in=270,944,850 out=28,462,197 elapsed=79.6s

  [4985/21087] intraday_13622.csv.gz  in=270,962,541 out=28,479,888 elapsed=79.6s

  [4986/21087] intraday_13623.csv.gz  in=270,989,667 out=28,507,014 elapsed=79.6s

  [4987/21087] intraday_13624.csv.gz  in=271,015,137 out=28,532,484 elapsed=79.7s

  [4988/21087] intraday_13625.csv.gz  in=271,040,828 out=28,558,175 elapsed=79.7s

  [4989/21087] intraday_13626.csv.gz  in=271,065,923 out=28,583,270 elapsed=79.7s

  [4990/21087] intraday_13627.csv.gz  in=271,089,331 out=28,606,678 elapsed=79.7s

  [4991/21087] intraday_13628.csv.gz  in=271,100,487 out=28,617,834 elapsed=79.7s

  [4992/21087] intraday_13629.csv.gz  in=271,100,488 out=28,617,835 elapsed=79.7s

  [4993/21087] intraday_1363.csv.gz  in=271,111,118 out=28,617,835 elapsed=79.7s

  [4994/21087] intraday_13630.csv.gz  in=271,131,129 out=28,637,846 elapsed=79.8s

  [4995/21087] intraday_13633.csv.gz  in=271,154,858 out=28,661,575 elapsed=79.8s

  [4996/21087] intraday_13631.csv.gz  in=271,178,858 out=28,685,575 elapsed=79.8s

  [4997/21087] intraday_13632.csv.gz  in=271,197,120 out=28,703,837 elapsed=79.8s

  [4998/21087] intraday_13634.csv.gz  in=271,223,276 out=28,729,993 elapsed=79.8s

  [4999/21087] intraday_13635.csv.gz  in=271,251,663 out=28,758,380 elapsed=79.9s

  [5000/21087] intraday_13636.csv.gz  in=271,283,316 out=28,789,698 elapsed=79.9s

  [5001/21087] intraday_13637.csv.gz  in=271,313,798 out=28,820,180 elapsed=79.9s

  [5002/21087] intraday_13638.csv.gz  in=271,337,230 out=28,843,612 elapsed=79.9s

  [5003/21087] intraday_13641.csv.gz  in=271,338,074 out=28,844,456 elapsed=79.9s

  [5004/21087] intraday_1364.csv.gz  in=271,351,189 out=28,844,456 elapsed=79.9s

  [5005/21087] intraday_13642.csv.gz  in=271,352,347 out=28,845,614 elapsed=79.9s

  [5006/21087] intraday_13640.csv.gz  in=271,374,347 out=28,867,614 elapsed=79.9s

  [5007/21087] intraday_13639.csv.gz  in=271,401,706 out=28,894,973 elapsed=79.9s

  [5008/21087] intraday_13643.csv.gz  in=271,428,757 out=28,922,024 elapsed=80.0s

  [5009/21087] intraday_13644.csv.gz  in=271,454,367 out=28,947,544 elapsed=80.0s

  [5010/21087] intraday_13645.csv.gz  in=271,480,063 out=28,973,240 elapsed=80.0s

  [5011/21087] intraday_13646.csv.gz  in=271,504,341 out=28,997,518 elapsed=80.0s

  [5012/21087] intraday_13647.csv.gz  in=271,528,131 out=29,021,308 elapsed=80.0s

  [5013/21087] intraday_1365.csv.gz  in=271,539,675 out=29,021,308 elapsed=80.0s

  [5014/21087] intraday_13648.csv.gz  in=271,564,196 out=29,045,829 elapsed=80.0s

  [5015/21087] intraday_13649.csv.gz  in=271,588,842 out=29,070,475 elapsed=80.0s

  [5016/21087] intraday_13650.csv.gz  in=271,613,415 out=29,095,048 elapsed=80.1s

  [5017/21087] intraday_13652.csv.gz  in=271,638,795 out=29,120,428 elapsed=80.1s

  [5018/21087] intraday_13651.csv.gz  in=271,660,214 out=29,141,847 elapsed=80.1s

  [5019/21087] intraday_13654.csv.gz  in=271,686,689 out=29,168,322 elapsed=80.1s

  [5020/21087] intraday_13653.csv.gz  in=271,712,029 out=29,193,662 elapsed=80.1s

  [5021/21087] intraday_13655.csv.gz  in=271,738,700 out=29,220,333 elapsed=80.1s

  [5022/21087] intraday_13656.csv.gz  in=271,757,631 out=29,237,591 elapsed=80.1s

  [5023/21087] intraday_13657.csv.gz  in=271,768,051 out=29,248,011 elapsed=80.2s

  [5024/21087] intraday_13658.csv.gz  in=271,793,629 out=29,273,589 elapsed=80.2s

  [5025/21087] intraday_1366.csv.gz  in=271,805,887 out=29,273,589 elapsed=80.2s

  [5026/21087] intraday_13659.csv.gz  in=271,831,313 out=29,299,015 elapsed=80.2s

  [5027/21087] intraday_13660.csv.gz  in=271,854,706 out=29,322,408 elapsed=80.2s

  [5028/21087] intraday_13661.csv.gz  in=271,883,752 out=29,351,454 elapsed=80.2s

  [5029/21087] intraday_13662.csv.gz  in=271,916,434 out=29,384,136 elapsed=80.2s

  [5030/21087] intraday_13664.csv.gz  in=271,946,764 out=29,414,466 elapsed=80.3s

  [5031/21087] intraday_13663.csv.gz  in=271,971,555 out=29,439,257 elapsed=80.3s

  [5032/21087] intraday_13665.csv.gz  in=272,006,701 out=29,474,403 elapsed=80.3s

  [5033/21087] intraday_13667.csv.gz  in=272,009,939 out=29,477,641 elapsed=80.3s

  [5034/21087] intraday_1367.csv.gz  in=272,017,827 out=29,477,641 elapsed=80.3s

  [5035/21087] intraday_13668.csv.gz  in=272,029,459 out=29,489,273 elapsed=80.3s

  [5036/21087] intraday_13666.csv.gz  in=272,065,262 out=29,525,076 elapsed=80.3s

  [5037/21087] intraday_13669.csv.gz  in=272,091,161 out=29,550,975 elapsed=80.3s

  [5038/21087] intraday_13670.csv.gz  in=272,108,865 out=29,568,679 elapsed=80.3s

  [5039/21087] intraday_13671.csv.gz  in=272,136,916 out=29,596,730 elapsed=80.3s

  [5040/21087] intraday_13672.csv.gz  in=272,159,226 out=29,619,040 elapsed=80.4s

  [5041/21087] intraday_13673.csv.gz  in=272,181,905 out=29,641,719 elapsed=80.4s

  [5042/21087] intraday_13674.csv.gz  in=272,210,568 out=29,670,382 elapsed=80.4s

  [5043/21087] intraday_13676.csv.gz  in=272,229,605 out=29,689,419 elapsed=80.6s

  [5044/21087] intraday_13678.csv.gz  in=272,253,558 out=29,713,372 elapsed=80.6s

  [5045/21087] intraday_13677.csv.gz  in=272,278,780 out=29,738,594 elapsed=80.6s

  [5046/21087] intraday_13675.csv.gz  in=272,306,861 out=29,766,675 elapsed=80.6s

  [5047/21087] intraday_13679.csv.gz  in=272,321,618 out=29,781,432 elapsed=80.6s

  [5048/21087] intraday_13680.csv.gz  in=272,322,346 out=29,782,160 elapsed=80.6s

  [5049/21087] intraday_1368.csv.gz  in=272,333,405 out=29,782,160 elapsed=80.7s

  [5050/21087] intraday_13681.csv.gz  in=272,335,182 out=29,783,937 elapsed=80.7s

  [5051/21087] intraday_13683.csv.gz  in=272,359,623 out=29,808,378 elapsed=80.7s

  [5052/21087] intraday_13684.csv.gz  in=272,391,310 out=29,840,065 elapsed=80.7s

  [5053/21087] intraday_13685.csv.gz  in=272,413,248 out=29,861,972 elapsed=80.7s

  [5054/21087] intraday_13682.csv.gz  in=272,467,762 out=29,896,549 elapsed=80.7s

  [5055/21087] intraday_13686.csv.gz  in=272,496,091 out=29,924,878 elapsed=80.7s

  [5056/21087] intraday_13687.csv.gz  in=272,522,176 out=29,950,963 elapsed=80.8s

  [5057/21087] intraday_13688.csv.gz  in=272,545,396 out=29,974,183 elapsed=80.8s

  [5058/21087] intraday_1369.csv.gz  in=272,552,918 out=29,974,183 elapsed=80.8s

  [5059/21087] intraday_13689.csv.gz  in=272,576,446 out=29,997,711 elapsed=80.8s

  [5060/21087] intraday_13690.csv.gz  in=272,589,373 out=30,010,638 elapsed=80.8s

  [5061/21087] intraday_13691.csv.gz  in=272,612,200 out=30,033,465 elapsed=80.8s

  [5062/21087] intraday_13692.csv.gz  in=272,625,826 out=30,047,091 elapsed=80.8s

  [5063/21087] intraday_13693.csv.gz  in=272,658,751 out=30,080,016 elapsed=80.9s

  [5064/21087] intraday_13695.csv.gz  in=272,688,930 out=30,109,299 elapsed=80.9s

  [5065/21087] intraday_13696.csv.gz  in=272,712,403 out=30,132,772 elapsed=80.9s

  [5066/21087] intraday_13694.csv.gz  in=272,744,618 out=30,160,526 elapsed=80.9s

  [5067/21087] intraday_13697.csv.gz  in=272,767,103 out=30,183,011 elapsed=80.9s

  [5068/21087] intraday_1370.csv.gz  in=272,767,155 out=30,183,011 elapsed=80.9s

  [5069/21087] intraday_13698.csv.gz  in=272,796,195 out=30,212,051 elapsed=81.0s

  [5070/21087] intraday_13699.csv.gz  in=272,826,712 out=30,242,568 elapsed=81.0s

  [5071/21087] intraday_13701.csv.gz  in=272,851,789 out=30,267,645 elapsed=81.0s

  [5072/21087] intraday_13700.csv.gz  in=272,874,117 out=30,289,973 elapsed=81.0s

  [5073/21087] intraday_13702.csv.gz  in=272,884,519 out=30,299,514 elapsed=81.0s

  [5074/21087] intraday_13703.csv.gz  in=272,901,854 out=30,316,849 elapsed=81.0s

  [5075/21087] intraday_13704.csv.gz  in=272,930,743 out=30,345,738 elapsed=81.0s

  [5076/21087] intraday_13705.csv.gz  in=272,949,342 out=30,364,337 elapsed=81.0s

  [5077/21087] intraday_13706.csv.gz  in=272,972,500 out=30,387,495 elapsed=81.1s

  [5078/21087] intraday_13707.csv.gz  in=273,006,431 out=30,421,426 elapsed=81.1s

  [5079/21087] intraday_1371.csv.gz  in=273,006,656 out=30,421,426 elapsed=81.1s

  [5080/21087] intraday_13708.csv.gz  in=273,031,055 out=30,445,825 elapsed=81.1s

  [5081/21087] intraday_13709.csv.gz  in=273,055,941 out=30,470,711 elapsed=81.1s

  [5082/21087] intraday_13710.csv.gz  in=273,080,128 out=30,494,898 elapsed=81.1s

  [5083/21087] intraday_13711.csv.gz  in=273,116,228 out=30,527,876 elapsed=81.1s

  [5084/21087] intraday_13712.csv.gz  in=273,139,525 out=30,551,173 elapsed=81.1s

  [5085/21087] intraday_13713.csv.gz  in=273,168,645 out=30,580,293 elapsed=81.2s

  [5086/21087] intraday_13715.csv.gz  in=273,177,378 out=30,589,026 elapsed=81.2s

  [5087/21087] intraday_13714.csv.gz  in=273,203,624 out=30,615,272 elapsed=81.2s

  [5088/21087] intraday_13717.csv.gz  in=273,225,259 out=30,636,907 elapsed=81.2s

  [5089/21087] intraday_13716.csv.gz  in=273,245,467 out=30,657,115 elapsed=81.2s

  [5090/21087] intraday_13719.csv.gz  in=273,277,334 out=30,688,982 elapsed=81.2s

  [5091/21087] intraday_13718.csv.gz  in=273,308,456 out=30,720,104 elapsed=81.2s

  [5092/21087] intraday_1372.csv.gz  in=273,308,474 out=30,720,104 elapsed=81.2s

  [5093/21087] intraday_13720.csv.gz  in=273,336,627 out=30,748,257 elapsed=81.3s

  [5094/21087] intraday_13721.csv.gz  in=273,357,996 out=30,769,626 elapsed=81.3s

  [5095/21087] intraday_13723.csv.gz  in=273,382,565 out=30,794,195 elapsed=81.3s

  [5096/21087] intraday_13722.csv.gz  in=273,407,426 out=30,819,056 elapsed=81.3s

  [5097/21087] intraday_13724.csv.gz  in=273,453,264 out=30,850,913 elapsed=81.3s

  [5098/21087] intraday_13727.csv.gz  in=273,472,281 out=30,869,930 elapsed=81.3s

  [5099/21087] intraday_13726.csv.gz  in=273,494,173 out=30,891,822 elapsed=81.3s

  [5100/21087] intraday_13725.csv.gz  in=273,518,528 out=30,916,177 elapsed=81.3s

  [5101/21087] intraday_13728.csv.gz  in=273,527,239 out=30,924,888 elapsed=81.4s

  [5102/21087] intraday_1373.csv.gz  in=273,527,285 out=30,924,888 elapsed=81.4s

  [5103/21087] intraday_13729.csv.gz  in=273,550,239 out=30,947,842 elapsed=81.4s

  [5104/21087] intraday_13730.csv.gz  in=273,582,840 out=30,977,877 elapsed=81.4s

  [5105/21087] intraday_13732.csv.gz  in=273,607,953 out=31,002,990 elapsed=81.4s

  [5106/21087] intraday_13733.csv.gz  in=273,638,309 out=31,028,141 elapsed=81.4s

  [5107/21087] intraday_13734.csv.gz  in=273,665,430 out=31,055,262 elapsed=81.5s

  [5108/21087] intraday_13731.csv.gz  in=273,694,869 out=31,084,701 elapsed=81.5s

  [5109/21087] intraday_13735.csv.gz  in=273,715,929 out=31,105,761 elapsed=81.5s

  [5110/21087] intraday_13736.csv.gz  in=273,739,609 out=31,129,441 elapsed=81.5s

  [5111/21087] intraday_1374.csv.gz  in=273,739,613 out=31,129,441 elapsed=81.5s

  [5112/21087] intraday_13738.csv.gz  in=273,760,904 out=31,150,732 elapsed=81.5s

  [5113/21087] intraday_13737.csv.gz  in=273,784,052 out=31,173,880 elapsed=81.5s

  [5114/21087] intraday_13739.csv.gz  in=273,813,181 out=31,203,009 elapsed=81.5s

  [5115/21087] intraday_13741.csv.gz  in=273,819,925 out=31,209,753 elapsed=81.5s

  [5116/21087] intraday_13740.csv.gz  in=273,835,312 out=31,225,140 elapsed=81.5s

  [5117/21087] intraday_13742.csv.gz  in=273,859,205 out=31,249,033 elapsed=81.6s

  [5118/21087] intraday_13743.csv.gz  in=273,894,822 out=31,277,006 elapsed=81.6s

  [5119/21087] intraday_13744.csv.gz  in=273,917,856 out=31,300,040 elapsed=81.6s

  [5120/21087] intraday_13745.csv.gz  in=273,945,450 out=31,327,634 elapsed=81.6s

  [5121/21087] intraday_13746.csv.gz  in=273,980,622 out=31,356,155 elapsed=81.6s

  [5122/21087] intraday_1375.csv.gz  in=273,980,684 out=31,356,155 elapsed=81.6s

  [5123/21087] intraday_13747.csv.gz  in=274,003,099 out=31,378,570 elapsed=81.7s

  [5124/21087] intraday_13748.csv.gz  in=274,027,051 out=31,402,522 elapsed=81.7s

  [5125/21087] intraday_13749.csv.gz  in=274,054,134 out=31,425,047 elapsed=81.7s

  [5126/21087] intraday_13750.csv.gz  in=274,082,045 out=31,452,958 elapsed=81.7s

  [5127/21087] intraday_13753.csv.gz  in=274,106,741 out=31,477,654 elapsed=81.7s

  [5128/21087] intraday_13754.csv.gz  in=274,115,065 out=31,485,978 elapsed=81.8s

  [5129/21087] intraday_13752.csv.gz  in=274,148,676 out=31,516,693 elapsed=81.8s

  [5130/21087] intraday_13751.csv.gz  in=274,179,510 out=31,547,527 elapsed=81.8s

  [5131/21087] intraday_13755.csv.gz  in=274,204,666 out=31,572,683 elapsed=81.8s

  [5132/21087] intraday_13757.csv.gz  in=274,228,857 out=31,596,874 elapsed=81.8s

  [5133/21087] intraday_13758.csv.gz  in=274,254,922 out=31,622,939 elapsed=81.8s

  [5134/21087] intraday_13759.csv.gz  in=274,274,544 out=31,642,561 elapsed=81.8s

  [5135/21087] intraday_1376.csv.gz  in=274,274,630 out=31,642,561 elapsed=81.8s

  [5136/21087] intraday_13756.csv.gz  in=274,300,968 out=31,668,899 elapsed=81.8s

  [5137/21087] intraday_13760.csv.gz  in=274,325,124 out=31,693,055 elapsed=81.9s

  [5138/21087] intraday_13762.csv.gz  in=274,348,692 out=31,716,623 elapsed=81.9s

  [5139/21087] intraday_13764.csv.gz  in=274,367,262 out=31,735,193 elapsed=81.9s

  [5140/21087] intraday_13761.csv.gz  in=274,395,568 out=31,763,499 elapsed=81.9s

  [5141/21087] intraday_13763.csv.gz  in=274,419,065 out=31,786,996 elapsed=81.9s

  [5142/21087] intraday_13767.csv.gz  in=274,419,650 out=31,787,581 elapsed=81.9s

  [5143/21087] intraday_13768.csv.gz  in=274,420,341 out=31,788,272 elapsed=81.9s

  [5144/21087] intraday_1377.csv.gz  in=274,421,225 out=31,788,272 elapsed=82.0s

  [5145/21087] intraday_13765.csv.gz  in=274,444,886 out=31,811,933 elapsed=82.0s

  [5146/21087] intraday_13766.csv.gz  in=274,475,955 out=31,843,002 elapsed=82.0s

  [5147/21087] intraday_13769.csv.gz  in=274,497,328 out=31,864,375 elapsed=82.0s

  [5148/21087] intraday_13771.csv.gz  in=274,519,666 out=31,886,713 elapsed=82.0s

  [5149/21087] intraday_13770.csv.gz  in=274,544,868 out=31,911,915 elapsed=82.0s

  [5150/21087] intraday_13772.csv.gz  in=274,571,289 out=31,938,336 elapsed=82.0s

  [5151/21087] intraday_13773.csv.gz  in=274,594,274 out=31,961,321 elapsed=82.1s

  [5152/21087] intraday_13774.csv.gz  in=274,617,994 out=31,985,041 elapsed=82.1s

  [5153/21087] intraday_13775.csv.gz  in=274,645,017 out=32,012,064 elapsed=82.1s

  [5154/21087] intraday_13776.csv.gz  in=274,670,261 out=32,037,308 elapsed=82.1s

  [5155/21087] intraday_13777.csv.gz  in=274,695,500 out=32,062,547 elapsed=82.1s

  [5156/21087] intraday_13778.csv.gz  in=274,718,150 out=32,085,197 elapsed=82.1s

  [5157/21087] intraday_13779.csv.gz  in=274,743,775 out=32,110,822 elapsed=82.1s

  [5158/21087] intraday_1378.csv.gz  in=274,760,157 out=32,110,822 elapsed=82.1s

  [5159/21087] intraday_13783.csv.gz  in=274,760,164 out=32,110,829 elapsed=82.1s

  [5160/21087] intraday_13782.csv.gz  in=274,769,111 out=32,119,776 elapsed=82.2s

  [5161/21087] intraday_13780.csv.gz  in=274,793,553 out=32,144,218 elapsed=82.2s

  [5162/21087] intraday_13785.csv.gz  in=274,818,716 out=32,169,381 elapsed=82.2s

  [5163/21087] intraday_13784.csv.gz  in=274,845,497 out=32,196,162 elapsed=82.2s

  [5164/21087] intraday_13781.csv.gz  in=274,870,523 out=32,219,978 elapsed=82.2s

  [5165/21087] intraday_13786.csv.gz  in=274,898,264 out=32,247,719 elapsed=82.3s

  [5166/21087] intraday_13788.csv.gz  in=274,930,684 out=32,280,139 elapsed=82.3s

  [5167/21087] intraday_1379.csv.gz  in=274,945,298 out=32,280,139 elapsed=82.3s

  [5168/21087] intraday_13789.csv.gz  in=274,966,484 out=32,301,325 elapsed=82.3s

  [5169/21087] intraday_13787.csv.gz  in=274,992,088 out=32,325,354 elapsed=82.3s

  [5170/21087] intraday_13793.csv.gz  in=275,006,872 out=32,340,138 elapsed=82.3s

  [5171/21087] intraday_13792.csv.gz  in=275,036,377 out=32,369,643 elapsed=82.4s

  [5172/21087] intraday_13790.csv.gz  in=275,062,658 out=32,393,486 elapsed=82.4s

  [5173/21087] intraday_13791.csv.gz  in=275,091,000 out=32,421,828 elapsed=82.4s

  [5174/21087] intraday_13794.csv.gz  in=275,094,454 out=32,425,282 elapsed=82.4s

  [5175/21087] intraday_13795.csv.gz  in=275,122,520 out=32,453,348 elapsed=82.4s

  [5176/21087] intraday_13796.csv.gz  in=275,149,542 out=32,480,370 elapsed=82.4s

  [5177/21087] intraday_13797.csv.gz  in=275,183,870 out=32,514,698 elapsed=82.5s

  [5178/21087] intraday_13798.csv.gz  in=275,220,314 out=32,551,142 elapsed=82.5s

  [5179/21087] intraday_1380.csv.gz  in=275,233,275 out=32,551,142 elapsed=82.5s

  [5180/21087] intraday_13799.csv.gz  in=275,262,286 out=32,578,924 elapsed=82.5s

  [5181/21087] intraday_13801.csv.gz  in=275,284,448 out=32,601,086 elapsed=82.5s

  [5182/21087] intraday_13800.csv.gz  in=275,313,256 out=32,629,894 elapsed=82.5s

  [5183/21087] intraday_13802.csv.gz  in=275,339,297 out=32,655,935 elapsed=82.5s

  [5184/21087] intraday_13803.csv.gz  in=275,359,290 out=32,675,928 elapsed=82.5s

  [5185/21087] intraday_13806.csv.gz  in=275,360,784 out=32,677,422 elapsed=82.6s

  [5186/21087] intraday_13804.csv.gz  in=275,387,846 out=32,704,484 elapsed=82.6s

  [5187/21087] intraday_13805.csv.gz  in=275,405,510 out=32,722,148 elapsed=82.6s

  [5188/21087] intraday_13807.csv.gz  in=275,433,904 out=32,750,542 elapsed=82.6s

  [5189/21087] intraday_1381.csv.gz  in=275,448,810 out=32,750,542 elapsed=82.6s

  [5190/21087] intraday_13808.csv.gz  in=275,471,363 out=32,773,095 elapsed=82.6s

  [5191/21087] intraday_13809.csv.gz  in=275,495,109 out=32,796,841 elapsed=82.6s

  [5192/21087] intraday_13810.csv.gz  in=275,516,690 out=32,818,422 elapsed=82.6s

  [5193/21087] intraday_13812.csv.gz  in=275,540,833 out=32,842,565 elapsed=82.7s

  [5194/21087] intraday_13811.csv.gz  in=275,568,314 out=32,868,865 elapsed=82.7s

  [5195/21087] intraday_13813.csv.gz  in=275,594,376 out=32,894,927 elapsed=82.7s

  [5196/21087] intraday_13814.csv.gz  in=275,624,106 out=32,924,635 elapsed=82.7s

  [5197/21087] intraday_13815.csv.gz  in=275,651,797 out=32,952,326 elapsed=82.7s

  [5198/21087] intraday_13818.csv.gz  in=275,653,602 out=32,954,131 elapsed=82.7s

  [5199/21087] intraday_13816.csv.gz  in=275,680,811 out=32,981,340 elapsed=82.7s

  [5200/21087] intraday_13817.csv.gz  in=275,705,127 out=33,005,656 elapsed=82.7s

  [5201/21087] intraday_1382.csv.gz  in=275,719,677 out=33,005,656 elapsed=82.8s

  [5202/21087] intraday_13819.csv.gz  in=275,728,776 out=33,014,755 elapsed=82.8s

  [5203/21087] intraday_13821.csv.gz  in=275,747,718 out=33,033,697 elapsed=82.8s

  [5204/21087] intraday_13820.csv.gz  in=275,776,152 out=33,060,176 elapsed=82.8s

  [5205/21087] intraday_13822.csv.gz  in=275,796,396 out=33,080,420 elapsed=82.8s

  [5206/21087] intraday_13823.csv.gz  in=275,824,250 out=33,108,274 elapsed=82.8s

  [5207/21087] intraday_13824.csv.gz  in=275,840,189 out=33,124,213 elapsed=82.8s

  [5208/21087] intraday_13827.csv.gz  in=275,851,545 out=33,135,191 elapsed=82.9s

  [5209/21087] intraday_13826.csv.gz  in=275,863,613 out=33,147,259 elapsed=82.9s

  [5210/21087] intraday_13825.csv.gz  in=275,875,245 out=33,158,891 elapsed=82.9s

  [5211/21087] intraday_13828.csv.gz  in=275,886,461 out=33,170,107 elapsed=82.9s

  [5212/21087] intraday_13829.csv.gz  in=275,899,978 out=33,183,624 elapsed=82.9s

  [5213/21087] intraday_13830.csv.gz  in=275,912,380 out=33,196,026 elapsed=82.9s

  [5214/21087] intraday_1383.csv.gz  in=275,927,300 out=33,196,026 elapsed=82.9s

  [5215/21087] intraday_13831.csv.gz  in=275,938,512 out=33,207,238 elapsed=82.9s

  [5216/21087] intraday_13832.csv.gz  in=275,942,356 out=33,211,082 elapsed=82.9s

  [5217/21087] intraday_13833.csv.gz  in=275,942,678 out=33,211,404 elapsed=82.9s

  [5218/21087] intraday_13834.csv.gz  in=275,943,728 out=33,212,454 elapsed=82.9s

  [5219/21087] intraday_13835.csv.gz  in=275,954,516 out=33,223,242 elapsed=83.0s

  [5220/21087] intraday_13837.csv.gz  in=275,963,610 out=33,232,336 elapsed=83.0s

  [5221/21087] intraday_13836.csv.gz  in=275,977,682 out=33,246,408 elapsed=83.0s

  [5222/21087] intraday_13838.csv.gz  in=275,987,764 out=33,256,490 elapsed=83.0s

  [5223/21087] intraday_13839.csv.gz  in=276,004,687 out=33,273,413 elapsed=83.0s

  [5224/21087] intraday_1384.csv.gz  in=276,018,163 out=33,273,413 elapsed=83.0s

  [5225/21087] intraday_13840.csv.gz  in=276,032,386 out=33,287,636 elapsed=83.0s

  [5226/21087] intraday_13841.csv.gz  in=276,042,529 out=33,297,779 elapsed=83.0s

  [5227/21087] intraday_13842.csv.gz  in=276,054,437 out=33,309,687 elapsed=83.1s

  [5228/21087] intraday_13843.csv.gz  in=276,069,912 out=33,325,162 elapsed=83.1s

  [5229/21087] intraday_13844.csv.gz  in=276,081,246 out=33,336,496 elapsed=83.1s

  [5230/21087] intraday_13845.csv.gz  in=276,095,228 out=33,350,478 elapsed=83.1s

  [5231/21087] intraday_13847.csv.gz  in=276,095,401 out=33,350,651 elapsed=83.1s

  [5232/21087] intraday_13846.csv.gz  in=276,101,809 out=33,357,059 elapsed=83.1s

  [5233/21087] intraday_13848.csv.gz  in=276,111,040 out=33,366,290 elapsed=83.1s

  [5234/21087] intraday_1385.csv.gz  in=276,124,386 out=33,366,290 elapsed=83.1s

  [5235/21087] intraday_13850.csv.gz  in=276,136,255 out=33,378,159 elapsed=83.1s

  [5236/21087] intraday_13849.csv.gz  in=276,148,183 out=33,390,087 elapsed=83.1s

  [5237/21087] intraday_13851.csv.gz  in=276,161,608 out=33,403,512 elapsed=83.2s

  [5238/21087] intraday_13852.csv.gz  in=276,176,959 out=33,418,863 elapsed=83.2s

  [5239/21087] intraday_13853.csv.gz  in=276,189,821 out=33,431,725 elapsed=83.2s

  [5240/21087] intraday_13854.csv.gz  in=276,199,273 out=33,441,177 elapsed=83.2s

  [5241/21087] intraday_13855.csv.gz  in=276,212,046 out=33,453,950 elapsed=83.2s

  [5242/21087] intraday_13856.csv.gz  in=276,223,216 out=33,465,120 elapsed=83.2s

  [5243/21087] intraday_13857.csv.gz  in=276,234,953 out=33,476,857 elapsed=83.2s

  [5244/21087] intraday_13858.csv.gz  in=276,246,285 out=33,488,189 elapsed=83.2s

  [5245/21087] intraday_13859.csv.gz  in=276,257,194 out=33,499,098 elapsed=83.2s

  [5246/21087] intraday_13860.csv.gz  in=276,268,288 out=33,510,192 elapsed=83.3s

  [5247/21087] intraday_1386.csv.gz  in=276,282,715 out=33,510,192 elapsed=83.3s

  [5248/21087] intraday_13861.csv.gz  in=276,292,190 out=33,519,667 elapsed=83.3s

  [5249/21087] intraday_13862.csv.gz  in=276,303,042 out=33,530,519 elapsed=83.3s

  [5250/21087] intraday_13863.csv.gz  in=276,314,001 out=33,541,478 elapsed=83.3s

  [5251/21087] intraday_13865.csv.gz  in=276,325,733 out=33,553,210 elapsed=83.3s

  [5252/21087] intraday_13864.csv.gz  in=276,340,885 out=33,568,362 elapsed=83.3s

  [5253/21087] intraday_13866.csv.gz  in=276,355,009 out=33,582,486 elapsed=83.3s

  [5254/21087] intraday_13868.csv.gz  in=276,355,341 out=33,582,818 elapsed=83.4s

  [5255/21087] intraday_1387.csv.gz  in=276,370,648 out=33,582,818 elapsed=83.4s

  [5256/21087] intraday_13867.csv.gz  in=276,379,790 out=33,591,957 elapsed=83.4s

  [5257/21087] intraday_13869.csv.gz  in=276,389,020 out=33,601,187 elapsed=83.4s

  [5258/21087] intraday_13870.csv.gz  in=276,400,072 out=33,612,239 elapsed=83.4s

  [5259/21087] intraday_13871.csv.gz  in=276,411,122 out=33,623,289 elapsed=83.4s

  [5260/21087] intraday_13872.csv.gz  in=276,423,466 out=33,635,633 elapsed=83.4s

  [5261/21087] intraday_13873.csv.gz  in=276,435,947 out=33,648,114 elapsed=83.4s

  [5262/21087] intraday_13874.csv.gz  in=276,448,525 out=33,660,692 elapsed=83.4s

  [5263/21087] intraday_13875.csv.gz  in=276,460,101 out=33,672,268 elapsed=83.4s

  [5264/21087] intraday_13877.csv.gz  in=276,472,183 out=33,684,350 elapsed=83.4s

  [5265/21087] intraday_13876.csv.gz  in=276,482,608 out=33,694,775 elapsed=83.5s

  [5266/21087] intraday_13878.csv.gz  in=276,493,754 out=33,705,565 elapsed=83.5s

  [5267/21087] intraday_13879.csv.gz  in=276,505,344 out=33,717,155 elapsed=83.5s

  [5268/21087] intraday_1388.csv.gz  in=276,515,734 out=33,717,155 elapsed=83.5s

  [5269/21087] intraday_13880.csv.gz  in=276,526,991 out=33,728,412 elapsed=83.5s

  [5270/21087] intraday_13881.csv.gz  in=276,532,568 out=33,733,989 elapsed=83.5s

  [5271/21087] intraday_13882.csv.gz  in=276,542,970 out=33,744,391 elapsed=83.5s

  [5272/21087] intraday_13883.csv.gz  in=276,552,888 out=33,754,309 elapsed=83.5s

  [5273/21087] intraday_13884.csv.gz  in=276,566,280 out=33,767,701 elapsed=83.5s

  [5274/21087] intraday_13885.csv.gz  in=276,579,140 out=33,780,561 elapsed=83.5s

  [5275/21087] intraday_13886.csv.gz  in=276,593,559 out=33,794,980 elapsed=83.6s

  [5276/21087] intraday_13887.csv.gz  in=276,605,045 out=33,806,437 elapsed=83.6s

  [5277/21087] intraday_1389.csv.gz  in=276,617,868 out=33,806,437 elapsed=83.6s

  [5278/21087] intraday_13888.csv.gz  in=276,629,006 out=33,817,575 elapsed=83.6s

  [5279/21087] intraday_13889.csv.gz  in=276,638,848 out=33,827,417 elapsed=83.6s

  [5280/21087] intraday_13890.csv.gz  in=276,651,764 out=33,840,333 elapsed=83.6s

  [5281/21087] intraday_13892.csv.gz  in=276,652,838 out=33,841,407 elapsed=83.6s

  [5282/21087] intraday_13893.csv.gz  in=276,656,955 out=33,845,524 elapsed=83.6s

  [5283/21087] intraday_13894.csv.gz  in=276,667,073 out=33,855,642 elapsed=83.6s

  [5284/21087] intraday_13891.csv.gz  in=276,678,947 out=33,867,516 elapsed=83.6s

  [5285/21087] intraday_13895.csv.gz  in=276,692,465 out=33,881,034 elapsed=83.6s

  [5286/21087] intraday_13896.csv.gz  in=276,703,149 out=33,891,718 elapsed=83.7s

  [5287/21087] intraday_13897.csv.gz  in=276,714,285 out=33,902,854 elapsed=83.7s

  [5288/21087] intraday_13898.csv.gz  in=276,724,762 out=33,913,331 elapsed=83.7s

  [5289/21087] intraday_13899.csv.gz  in=276,735,309 out=33,923,878 elapsed=83.7s

  [5290/21087] intraday_1390.csv.gz  in=276,750,759 out=33,923,878 elapsed=83.7s

  [5291/21087] intraday_13900.csv.gz  in=276,762,791 out=33,935,910 elapsed=83.7s

  [5292/21087] intraday_13902.csv.gz  in=276,780,213 out=33,953,332 elapsed=83.7s

  [5293/21087] intraday_13901.csv.gz  in=276,792,713 out=33,965,832 elapsed=83.7s

  [5294/21087] intraday_13903.csv.gz  in=276,805,254 out=33,978,373 elapsed=83.7s

  [5295/21087] intraday_13904.csv.gz  in=276,816,521 out=33,989,640 elapsed=83.8s

  [5296/21087] intraday_13906.csv.gz  in=276,827,677 out=34,000,796 elapsed=83.8s

  [5297/21087] intraday_13905.csv.gz  in=276,838,474 out=34,011,593 elapsed=83.8s

  [5298/21087] intraday_13907.csv.gz  in=276,850,931 out=34,024,050 elapsed=83.8s

  [5299/21087] intraday_13908.csv.gz  in=276,862,653 out=34,035,772 elapsed=83.8s

  [5300/21087] intraday_13909.csv.gz  in=276,871,981 out=34,045,100 elapsed=83.8s

  [5301/21087] intraday_1391.csv.gz  in=276,883,694 out=34,045,100 elapsed=83.8s

  [5302/21087] intraday_13910.csv.gz  in=276,896,865 out=34,058,271 elapsed=83.8s

  [5303/21087] intraday_13911.csv.gz  in=276,907,721 out=34,069,127 elapsed=83.8s

  [5304/21087] intraday_13913.csv.gz  in=276,920,048 out=34,081,454 elapsed=83.8s

  [5305/21087] intraday_13912.csv.gz  in=276,931,015 out=34,092,421 elapsed=83.8s

  [5306/21087] intraday_13914.csv.gz  in=276,942,792 out=34,104,198 elapsed=83.9s

  [5307/21087] intraday_13917.csv.gz  in=276,943,765 out=34,105,171 elapsed=83.9s

  [5308/21087] intraday_13916.csv.gz  in=276,950,344 out=34,111,750 elapsed=83.9s

  [5309/21087] intraday_13915.csv.gz  in=276,962,247 out=34,123,653 elapsed=83.9s

  [5310/21087] intraday_13918.csv.gz  in=276,975,084 out=34,136,490 elapsed=83.9s

  [5311/21087] intraday_1392.csv.gz  in=276,986,035 out=34,136,490 elapsed=83.9s

  [5312/21087] intraday_13919.csv.gz  in=276,998,659 out=34,149,114 elapsed=83.9s

  [5313/21087] intraday_13920.csv.gz  in=277,008,683 out=34,159,138 elapsed=83.9s

  [5314/21087] intraday_13921.csv.gz  in=277,020,564 out=34,171,019 elapsed=83.9s

  [5315/21087] intraday_13922.csv.gz  in=277,031,671 out=34,182,126 elapsed=83.9s

  [5316/21087] intraday_13924.csv.gz  in=277,042,044 out=34,192,499 elapsed=83.9s

  [5317/21087] intraday_13923.csv.gz  in=277,057,003 out=34,207,458 elapsed=84.0s

  [5318/21087] intraday_13925.csv.gz  in=277,067,802 out=34,218,257 elapsed=84.0s

  [5319/21087] intraday_13926.csv.gz  in=277,080,558 out=34,231,013 elapsed=84.0s

  [5320/21087] intraday_13927.csv.gz  in=277,095,510 out=34,245,965 elapsed=84.0s

  [5321/21087] intraday_13928.csv.gz  in=277,107,552 out=34,258,007 elapsed=84.0s

  [5322/21087] intraday_13929.csv.gz  in=277,120,407 out=34,270,862 elapsed=84.0s

  [5323/21087] intraday_13930.csv.gz  in=277,133,343 out=34,283,798 elapsed=84.0s

  [5324/21087] intraday_1393.csv.gz  in=277,147,607 out=34,283,798 elapsed=84.0s

  [5325/21087] intraday_13931.csv.gz  in=277,160,615 out=34,296,806 elapsed=84.1s

  [5326/21087] intraday_13932.csv.gz  in=277,173,214 out=34,309,405 elapsed=84.1s

  [5327/21087] intraday_13934.csv.gz  in=277,190,935 out=34,327,126 elapsed=84.1s

  [5328/21087] intraday_13933.csv.gz  in=277,204,774 out=34,340,965 elapsed=84.1s

  [5329/21087] intraday_13935.csv.gz  in=277,216,411 out=34,352,602 elapsed=84.1s

  [5330/21087] intraday_13936.csv.gz  in=277,230,659 out=34,366,850 elapsed=84.1s

  [5331/21087] intraday_13937.csv.gz  in=277,242,624 out=34,378,815 elapsed=84.1s

  [5332/21087] intraday_13939.csv.gz  in=277,252,388 out=34,388,579 elapsed=84.1s

  [5333/21087] intraday_13938.csv.gz  in=277,265,911 out=34,402,102 elapsed=84.1s

  [5334/21087] intraday_1394.csv.gz  in=277,279,110 out=34,402,102 elapsed=84.1s

  [5335/21087] intraday_13940.csv.gz  in=277,290,447 out=34,413,439 elapsed=84.2s

  [5336/21087] intraday_13942.csv.gz  in=277,302,106 out=34,425,098 elapsed=84.2s

  [5337/21087] intraday_13941.csv.gz  in=277,314,354 out=34,437,346 elapsed=84.2s

  [5338/21087] intraday_13943.csv.gz  in=277,325,229 out=34,448,221 elapsed=84.2s

  [5339/21087] intraday_13944.csv.gz  in=277,339,940 out=34,462,932 elapsed=84.2s

  [5340/21087] intraday_13945.csv.gz  in=277,349,822 out=34,472,814 elapsed=84.2s

  [5341/21087] intraday_13946.csv.gz  in=277,361,994 out=34,484,986 elapsed=84.2s

  [5342/21087] intraday_13947.csv.gz  in=277,372,968 out=34,495,960 elapsed=84.2s

  [5343/21087] intraday_13948.csv.gz  in=277,385,423 out=34,508,415 elapsed=84.2s

  [5344/21087] intraday_13949.csv.gz  in=277,397,981 out=34,520,973 elapsed=84.2s

  [5345/21087] intraday_1395.csv.gz  in=277,411,612 out=34,520,973 elapsed=84.3s

  [5346/21087] intraday_13950.csv.gz  in=277,424,233 out=34,533,594 elapsed=84.3s

  [5347/21087] intraday_13951.csv.gz  in=277,437,739 out=34,547,100 elapsed=84.3s

  [5348/21087] intraday_13953.csv.gz  in=277,449,736 out=34,559,097 elapsed=84.3s

  [5349/21087] intraday_13952.csv.gz  in=277,462,764 out=34,572,125 elapsed=84.3s

  [5350/21087] intraday_13955.csv.gz  in=277,473,569 out=34,582,930 elapsed=84.3s

  [5351/21087] intraday_13954.csv.gz  in=277,485,974 out=34,595,335 elapsed=84.3s

  [5352/21087] intraday_13956.csv.gz  in=277,499,462 out=34,608,823 elapsed=84.3s

  [5353/21087] intraday_13957.csv.gz  in=277,510,147 out=34,619,508 elapsed=84.3s

  [5354/21087] intraday_13959.csv.gz  in=277,521,289 out=34,630,650 elapsed=84.3s

  [5355/21087] intraday_13958.csv.gz  in=277,533,630 out=34,642,991 elapsed=84.4s

  [5356/21087] intraday_1396.csv.gz  in=277,546,376 out=34,642,991 elapsed=84.4s

  [5357/21087] intraday_13960.csv.gz  in=277,555,065 out=34,651,680 elapsed=84.4s

  [5358/21087] intraday_13962.csv.gz  in=277,556,626 out=34,653,241 elapsed=84.4s

  [5359/21087] intraday_13961.csv.gz  in=277,570,159 out=34,666,774 elapsed=84.4s

  [5360/21087] intraday_13963.csv.gz  in=277,571,814 out=34,667,043 elapsed=84.4s

  [5361/21087] intraday_13964.csv.gz  in=277,573,380 out=34,668,609 elapsed=84.4s

  [5362/21087] intraday_13965.csv.gz  in=277,573,540 out=34,668,769 elapsed=84.4s

  [5363/21087] intraday_13966.csv.gz  in=277,573,542 out=34,668,771 elapsed=84.4s

  [5364/21087] intraday_13968.csv.gz  in=277,573,676 out=34,668,905 elapsed=84.4s

  [5365/21087] intraday_13969.csv.gz  in=277,573,984 out=34,669,213 elapsed=84.4s

  [5366/21087] intraday_1397.csv.gz  in=277,585,706 out=34,669,213 elapsed=84.4s

  [5367/21087] intraday_13967.csv.gz  in=277,603,652 out=34,674,763 elapsed=84.4s

  [5368/21087] intraday_13970.csv.gz  in=277,603,768 out=34,674,879 elapsed=84.4s

  [5369/21087] intraday_13971.csv.gz  in=277,604,856 out=34,675,364 elapsed=84.5s

  [5370/21087] intraday_13972.csv.gz  in=277,605,463 out=34,675,971 elapsed=84.5s

  [5371/21087] intraday_13973.csv.gz  in=277,605,667 out=34,676,175 elapsed=84.5s

  [5372/21087] intraday_13975.csv.gz  in=277,605,698 out=34,676,206 elapsed=84.5s

  [5373/21087] intraday_13976.csv.gz  in=277,608,961 out=34,677,692 elapsed=84.5s

  [5374/21087] intraday_13974.csv.gz  in=277,629,932 out=34,685,934 elapsed=84.5s

  [5375/21087] intraday_13977.csv.gz  in=277,633,847 out=34,688,654 elapsed=84.5s

  [5376/21087] intraday_13979.csv.gz  in=277,633,893 out=34,688,700 elapsed=84.5s

  [5377/21087] intraday_13978.csv.gz  in=277,634,234 out=34,688,987 elapsed=84.5s

  [5378/21087] intraday_1398.csv.gz  in=277,648,139 out=34,688,987 elapsed=84.5s

  [5379/21087] intraday_13981.csv.gz  in=277,648,187 out=34,689,035 elapsed=84.5s

  [5380/21087] intraday_13980.csv.gz  in=277,649,861 out=34,690,709 elapsed=84.5s

  [5381/21087] intraday_13982.csv.gz  in=277,650,745 out=34,691,593 elapsed=84.5s

  [5382/21087] intraday_13983.csv.gz  in=277,650,770 out=34,691,618 elapsed=84.6s

  [5383/21087] intraday_13984.csv.gz  in=277,650,801 out=34,691,649 elapsed=84.6s

  [5384/21087] intraday_13985.csv.gz  in=277,650,965 out=34,691,813 elapsed=84.6s

  [5385/21087] intraday_13988.csv.gz  in=277,651,092 out=34,691,940 elapsed=84.6s

  [5386/21087] intraday_13987.csv.gz  in=277,651,233 out=34,692,081 elapsed=84.6s

  [5387/21087] intraday_13986.csv.gz  in=277,654,033 out=34,693,577 elapsed=84.6s

  [5388/21087] intraday_13989.csv.gz  in=277,684,447 out=34,701,885 elapsed=84.6s

  [5389/21087] intraday_1399.csv.gz  in=277,697,193 out=34,701,885 elapsed=84.6s

  [5390/21087] intraday_13991.csv.gz  in=277,709,742 out=34,714,434 elapsed=84.6s

  [5391/21087] intraday_13990.csv.gz  in=277,725,064 out=34,729,756 elapsed=84.6s

  [5392/21087] intraday_13992.csv.gz  in=277,737,479 out=34,742,171 elapsed=84.7s

  [5393/21087] intraday_13993.csv.gz  in=277,748,274 out=34,752,966 elapsed=84.7s

  [5394/21087] intraday_13994.csv.gz  in=277,759,518 out=34,764,210 elapsed=84.7s

  [5395/21087] intraday_13995.csv.gz  in=277,774,428 out=34,779,120 elapsed=84.7s

  [5396/21087] intraday_13996.csv.gz  in=277,786,744 out=34,791,436 elapsed=84.7s

  [5397/21087] intraday_13999.csv.gz  in=277,798,921 out=34,803,613 elapsed=84.7s

  [5398/21087] intraday_13997.csv.gz  in=277,810,352 out=34,815,044 elapsed=84.7s

  [5399/21087] intraday_13998.csv.gz  in=277,823,570 out=34,828,262 elapsed=84.7s

  [5400/21087] intraday_1400.csv.gz  in=277,842,977 out=34,828,262 elapsed=84.7s

  [5401/21087] intraday_14000.csv.gz  in=277,854,611 out=34,839,896 elapsed=84.8s

  [5402/21087] intraday_14002.csv.gz  in=277,866,042 out=34,851,327 elapsed=84.8s

  [5403/21087] intraday_14001.csv.gz  in=277,878,006 out=34,863,291 elapsed=84.8s

  [5404/21087] intraday_14003.csv.gz  in=277,892,163 out=34,877,448 elapsed=84.8s

  [5405/21087] intraday_14004.csv.gz  in=277,903,231 out=34,888,516 elapsed=84.8s

  [5406/21087] intraday_14006.csv.gz  in=277,907,428 out=34,892,713 elapsed=84.8s

  [5407/21087] intraday_14005.csv.gz  in=277,915,590 out=34,900,875 elapsed=84.8s

  [5408/21087] intraday_14007.csv.gz  in=277,926,794 out=34,912,079 elapsed=84.8s

  [5409/21087] intraday_14008.csv.gz  in=277,942,109 out=34,927,394 elapsed=84.9s

  [5410/21087] intraday_1401.csv.gz  in=277,955,865 out=34,927,394 elapsed=84.9s

  [5411/21087] intraday_14009.csv.gz  in=277,967,860 out=34,939,389 elapsed=84.9s

  [5412/21087] intraday_14010.csv.gz  in=277,981,793 out=34,953,322 elapsed=84.9s

  [5413/21087] intraday_14011.csv.gz  in=277,993,294 out=34,964,823 elapsed=84.9s

  [5414/21087] intraday_14013.csv.gz  in=278,002,971 out=34,974,500 elapsed=84.9s

  [5415/21087] intraday_14014.csv.gz  in=278,013,163 out=34,984,692 elapsed=84.9s

  [5416/21087] intraday_14012.csv.gz  in=278,026,302 out=34,997,831 elapsed=84.9s

  [5417/21087] intraday_14018.csv.gz  in=278,041,513 out=35,013,042 elapsed=85.0s

  [5418/21087] intraday_14016.csv.gz  in=278,053,586 out=35,025,115 elapsed=85.0s

  [5419/21087] intraday_14015.csv.gz  in=278,066,474 out=35,037,067 elapsed=85.0s

  [5420/21087] intraday_14017.csv.gz  in=278,079,972 out=35,050,565 elapsed=85.0s

  [5421/21087] intraday_1402.csv.gz  in=278,092,892 out=35,050,565 elapsed=85.0s

  [5422/21087] intraday_14020.csv.gz  in=278,102,292 out=35,059,965 elapsed=85.0s

  [5423/21087] intraday_14019.csv.gz  in=278,115,375 out=35,073,048 elapsed=85.0s

  [5424/21087] intraday_14022.csv.gz  in=278,118,012 out=35,075,685 elapsed=85.1s

  [5425/21087] intraday_14021.csv.gz  in=278,131,075 out=35,088,748 elapsed=85.1s

  [5426/21087] intraday_14023.csv.gz  in=278,134,200 out=35,091,873 elapsed=85.1s

  [5427/21087] intraday_14024.csv.gz  in=278,145,438 out=35,103,111 elapsed=85.1s

  [5428/21087] intraday_14025.csv.gz  in=278,157,612 out=35,115,285 elapsed=85.1s

  [5429/21087] intraday_14026.csv.gz  in=278,167,458 out=35,125,131 elapsed=85.1s

  [5430/21087] intraday_14027.csv.gz  in=278,178,172 out=35,135,845 elapsed=85.1s

  [5431/21087] intraday_14028.csv.gz  in=278,190,159 out=35,147,832 elapsed=85.1s

  [5432/21087] intraday_1403.csv.gz  in=278,201,244 out=35,147,832 elapsed=85.1s

  [5433/21087] intraday_14029.csv.gz  in=278,215,817 out=35,162,405 elapsed=85.1s

  [5434/21087] intraday_14030.csv.gz  in=278,226,960 out=35,173,548 elapsed=85.2s

  [5435/21087] intraday_14031.csv.gz  in=278,241,731 out=35,188,319 elapsed=85.2s

  [5436/21087] intraday_14032.csv.gz  in=278,253,618 out=35,200,206 elapsed=85.2s

  [5437/21087] intraday_14033.csv.gz  in=278,264,529 out=35,211,117 elapsed=85.2s

  [5438/21087] intraday_14034.csv.gz  in=278,278,080 out=35,224,668 elapsed=85.2s

  [5439/21087] intraday_14035.csv.gz  in=278,288,274 out=35,234,862 elapsed=85.2s

  [5440/21087] intraday_14036.csv.gz  in=278,299,007 out=35,245,595 elapsed=85.2s

  [5441/21087] intraday_14037.csv.gz  in=278,308,444 out=35,255,032 elapsed=85.2s

  [5442/21087] intraday_14038.csv.gz  in=278,316,646 out=35,263,234 elapsed=85.2s

  [5443/21087] intraday_14039.csv.gz  in=278,329,098 out=35,275,686 elapsed=85.2s

  [5444/21087] intraday_1404.csv.gz  in=278,344,370 out=35,275,686 elapsed=85.3s

  [5445/21087] intraday_14040.csv.gz  in=278,355,387 out=35,286,703 elapsed=85.3s

  [5446/21087] intraday_14041.csv.gz  in=278,366,677 out=35,297,993 elapsed=85.3s

  [5447/21087] intraday_14042.csv.gz  in=278,376,691 out=35,308,007 elapsed=85.3s

  [5448/21087] intraday_14043.csv.gz  in=278,388,392 out=35,319,708 elapsed=85.3s

  [5449/21087] intraday_14045.csv.gz  in=278,399,484 out=35,330,800 elapsed=85.3s

  [5450/21087] intraday_14044.csv.gz  in=278,412,687 out=35,344,003 elapsed=85.3s

  [5451/21087] intraday_14046.csv.gz  in=278,425,881 out=35,357,197 elapsed=85.3s

  [5452/21087] intraday_14047.csv.gz  in=278,436,148 out=35,367,464 elapsed=85.3s

  [5453/21087] intraday_14048.csv.gz  in=278,447,149 out=35,378,465 elapsed=85.3s

  [5454/21087] intraday_14049.csv.gz  in=278,457,676 out=35,388,992 elapsed=85.4s

  [5455/21087] intraday_1405.csv.gz  in=278,474,619 out=35,388,992 elapsed=85.4s

  [5456/21087] intraday_14051.csv.gz  in=278,478,960 out=35,393,333 elapsed=85.4s

  [5457/21087] intraday_14050.csv.gz  in=278,493,291 out=35,407,664 elapsed=85.4s

  [5458/21087] intraday_14052.csv.gz  in=278,498,581 out=35,412,954 elapsed=85.4s

  [5459/21087] intraday_14053.csv.gz  in=278,509,433 out=35,423,806 elapsed=85.4s

  [5460/21087] intraday_14054.csv.gz  in=278,520,316 out=35,434,689 elapsed=85.4s

  [5461/21087] intraday_14055.csv.gz  in=278,532,435 out=35,446,808 elapsed=85.4s

  [5462/21087] intraday_14056.csv.gz  in=278,545,639 out=35,460,012 elapsed=85.4s

  [5463/21087] intraday_14057.csv.gz  in=278,557,087 out=35,471,460 elapsed=85.5s

  [5464/21087] intraday_14058.csv.gz  in=278,569,689 out=35,484,062 elapsed=85.5s

  [5465/21087] intraday_1406.csv.gz  in=278,585,437 out=35,484,062 elapsed=85.5s

  [5466/21087] intraday_14059.csv.gz  in=278,596,002 out=35,494,627 elapsed=85.5s

  [5467/21087] intraday_14060.csv.gz  in=278,606,530 out=35,505,155 elapsed=85.5s

  [5468/21087] intraday_14061.csv.gz  in=278,621,265 out=35,519,890 elapsed=85.5s

  [5469/21087] intraday_14062.csv.gz  in=278,632,494 out=35,531,119 elapsed=85.5s

  [5470/21087] intraday_14063.csv.gz  in=278,644,152 out=35,542,777 elapsed=85.5s

  [5471/21087] intraday_14064.csv.gz  in=278,651,578 out=35,550,203 elapsed=85.5s

  [5472/21087] intraday_14065.csv.gz  in=278,653,442 out=35,552,067 elapsed=85.5s

  [5473/21087] intraday_14066.csv.gz  in=278,666,847 out=35,565,472 elapsed=85.5s

  [5474/21087] intraday_14068.csv.gz  in=278,680,121 out=35,578,746 elapsed=85.6s

  [5475/21087] intraday_14067.csv.gz  in=278,695,292 out=35,593,917 elapsed=85.6s

  [5476/21087] intraday_14069.csv.gz  in=278,706,512 out=35,605,137 elapsed=85.6s

  [5477/21087] intraday_1407.csv.gz  in=278,721,634 out=35,605,137 elapsed=85.6s

  [5478/21087] intraday_14070.csv.gz  in=278,732,305 out=35,615,808 elapsed=85.6s

  [5479/21087] intraday_14071.csv.gz  in=278,743,889 out=35,627,392 elapsed=85.6s

  [5480/21087] intraday_14072.csv.gz  in=278,758,092 out=35,641,595 elapsed=85.6s

  [5481/21087] intraday_14073.csv.gz  in=278,770,415 out=35,653,918 elapsed=85.6s

  [5482/21087] intraday_14074.csv.gz  in=278,779,770 out=35,663,273 elapsed=85.6s

  [5483/21087] intraday_14076.csv.gz  in=278,790,693 out=35,674,196 elapsed=85.7s

  [5484/21087] intraday_14075.csv.gz  in=278,805,461 out=35,688,964 elapsed=85.7s

  [5485/21087] intraday_14077.csv.gz  in=278,817,483 out=35,700,986 elapsed=85.7s

  [5486/21087] intraday_14078.csv.gz  in=278,828,957 out=35,712,460 elapsed=85.7s

  [5487/21087] intraday_14079.csv.gz  in=278,840,500 out=35,724,003 elapsed=85.7s

  [5488/21087] intraday_1408.csv.gz  in=278,854,092 out=35,724,003 elapsed=85.7s

  [5489/21087] intraday_14080.csv.gz  in=278,865,865 out=35,735,776 elapsed=85.7s

  [5490/21087] intraday_14081.csv.gz  in=278,878,833 out=35,748,744 elapsed=85.7s

  [5491/21087] intraday_14082.csv.gz  in=278,889,694 out=35,759,605 elapsed=85.7s

  [5492/21087] intraday_14083.csv.gz  in=278,900,676 out=35,770,587 elapsed=85.7s

  [5493/21087] intraday_14084.csv.gz  in=278,914,304 out=35,784,215 elapsed=85.8s

  [5494/21087] intraday_14086.csv.gz  in=278,926,593 out=35,796,504 elapsed=85.8s

  [5495/21087] intraday_14085.csv.gz  in=278,939,200 out=35,809,111 elapsed=85.8s

  [5496/21087] intraday_14087.csv.gz  in=278,950,651 out=35,820,562 elapsed=85.8s

  [5497/21087] intraday_14088.csv.gz  in=278,986,352 out=35,840,202 elapsed=85.8s

  [5498/21087] intraday_14090.csv.gz  in=278,996,896 out=35,850,746 elapsed=85.8s

  [5499/21087] intraday_1409.csv.gz  in=279,009,556 out=35,850,746 elapsed=85.8s

  [5500/21087] intraday_14089.csv.gz  in=279,025,056 out=35,866,246 elapsed=85.8s

  [5501/21087] intraday_14091.csv.gz  in=279,036,653 out=35,877,843 elapsed=85.8s

  [5502/21087] intraday_14093.csv.gz  in=279,050,331 out=35,891,521 elapsed=85.9s

  [5503/21087] intraday_14092.csv.gz  in=279,063,622 out=35,904,812 elapsed=85.9s

  [5504/21087] intraday_14094.csv.gz  in=279,076,295 out=35,917,485 elapsed=85.9s

  [5505/21087] intraday_14095.csv.gz  in=279,090,175 out=35,931,365 elapsed=85.9s

  [5506/21087] intraday_14096.csv.gz  in=279,104,083 out=35,945,273 elapsed=85.9s

  [5507/21087] intraday_14097.csv.gz  in=279,116,619 out=35,957,809 elapsed=85.9s

  [5508/21087] intraday_14098.csv.gz  in=279,129,677 out=35,970,867 elapsed=85.9s

  [5509/21087] intraday_1410.csv.gz  in=279,142,877 out=35,970,867 elapsed=85.9s

  [5510/21087] intraday_14099.csv.gz  in=279,159,266 out=35,987,256 elapsed=85.9s

  [5511/21087] intraday_14100.csv.gz  in=279,175,492 out=36,003,482 elapsed=85.9s

  [5512/21087] intraday_14101.csv.gz  in=279,188,941 out=36,016,931 elapsed=86.0s

  [5513/21087] intraday_14102.csv.gz  in=279,203,752 out=36,031,742 elapsed=86.0s

  [5514/21087] intraday_14103.csv.gz  in=279,214,623 out=36,042,613 elapsed=86.0s

  [5515/21087] intraday_14104.csv.gz  in=279,227,661 out=36,055,651 elapsed=86.0s

  [5516/21087] intraday_14105.csv.gz  in=279,237,552 out=36,065,542 elapsed=86.0s

  [5517/21087] intraday_14106.csv.gz  in=279,250,440 out=36,078,430 elapsed=86.0s

  [5518/21087] intraday_14108.csv.gz  in=279,263,611 out=36,091,601 elapsed=86.0s

  [5519/21087] intraday_14107.csv.gz  in=279,274,118 out=36,102,108 elapsed=86.0s

  [5520/21087] intraday_1411.csv.gz  in=279,287,953 out=36,102,108 elapsed=86.0s

  [5521/21087] intraday_14109.csv.gz  in=279,298,226 out=36,112,381 elapsed=86.0s

  [5522/21087] intraday_14110.csv.gz  in=279,314,510 out=36,128,665 elapsed=86.1s

  [5523/21087] intraday_14111.csv.gz  in=279,324,437 out=36,138,592 elapsed=86.1s

  [5524/21087] intraday_14113.csv.gz  in=279,335,642 out=36,149,797 elapsed=86.1s

  [5525/21087] intraday_14112.csv.gz  in=279,347,555 out=36,161,710 elapsed=86.1s

  [5526/21087] intraday_14114.csv.gz  in=279,361,152 out=36,175,307 elapsed=86.1s

  [5527/21087] intraday_14115.csv.gz  in=279,372,418 out=36,186,573 elapsed=86.1s

  [5528/21087] intraday_14116.csv.gz  in=279,386,197 out=36,200,352 elapsed=86.1s

  [5529/21087] intraday_14117.csv.gz  in=279,401,048 out=36,215,203 elapsed=86.1s

  [5530/21087] intraday_14118.csv.gz  in=279,413,786 out=36,227,941 elapsed=86.1s

  [5531/21087] intraday_14119.csv.gz  in=279,426,671 out=36,240,826 elapsed=86.1s

  [5532/21087] intraday_1412.csv.gz  in=279,438,675 out=36,240,826 elapsed=86.1s

  [5533/21087] intraday_14120.csv.gz  in=279,450,807 out=36,252,958 elapsed=86.2s

  [5534/21087] intraday_14121.csv.gz  in=279,461,663 out=36,263,814 elapsed=86.2s

  [5535/21087] intraday_14123.csv.gz  in=279,471,978 out=36,274,129 elapsed=86.2s

  [5536/21087] intraday_14122.csv.gz  in=279,483,948 out=36,286,099 elapsed=86.2s

  [5537/21087] intraday_14124.csv.gz  in=279,495,956 out=36,298,107 elapsed=86.2s

  [5538/21087] intraday_14125.csv.gz  in=279,507,305 out=36,309,456 elapsed=86.2s

  [5539/21087] intraday_14126.csv.gz  in=279,514,626 out=36,316,777 elapsed=86.2s

  [5540/21087] intraday_14127.csv.gz  in=279,528,195 out=36,330,346 elapsed=86.2s

  [5541/21087] intraday_14128.csv.gz  in=279,544,340 out=36,346,491 elapsed=86.2s

  [5542/21087] intraday_14129.csv.gz  in=279,555,642 out=36,357,793 elapsed=86.2s

  [5543/21087] intraday_1413.csv.gz  in=279,569,384 out=36,357,793 elapsed=86.3s

  [5544/21087] intraday_14131.csv.gz  in=279,581,252 out=36,369,661 elapsed=86.3s

  [5545/21087] intraday_14130.csv.gz  in=279,593,879 out=36,382,288 elapsed=86.3s

  [5546/21087] intraday_14132.csv.gz  in=279,608,355 out=36,394,817 elapsed=86.3s

  [5547/21087] intraday_14133.csv.gz  in=279,622,589 out=36,409,051 elapsed=86.3s

  [5548/21087] intraday_14135.csv.gz  in=279,633,489 out=36,419,951 elapsed=86.3s

  [5549/21087] intraday_14137.csv.gz  in=279,645,336 out=36,431,798 elapsed=86.4s

  [5550/21087] intraday_14136.csv.gz  in=279,657,807 out=36,444,269 elapsed=86.4s

  [5551/21087] intraday_14134.csv.gz  in=279,671,352 out=36,457,814 elapsed=86.4s

  [5552/21087] intraday_14138.csv.gz  in=279,683,035 out=36,469,497 elapsed=86.4s

  [5553/21087] intraday_1414.csv.gz  in=279,696,096 out=36,469,497 elapsed=86.4s

  [5554/21087] intraday_14139.csv.gz  in=279,707,418 out=36,480,819 elapsed=86.4s

  [5555/21087] intraday_14140.csv.gz  in=279,722,587 out=36,493,444 elapsed=86.4s

  [5556/21087] intraday_14141.csv.gz  in=279,736,866 out=36,507,723 elapsed=86.4s

  [5557/21087] intraday_14144.csv.gz  in=279,747,836 out=36,518,693 elapsed=86.4s

  [5558/21087] intraday_14142.csv.gz  in=279,756,842 out=36,527,699 elapsed=86.4s

  [5559/21087] intraday_14143.csv.gz  in=279,762,924 out=36,533,781 elapsed=86.4s

  [5560/21087] intraday_14145.csv.gz  in=279,773,894 out=36,544,751 elapsed=86.5s

  [5561/21087] intraday_14146.csv.gz  in=279,787,930 out=36,558,787 elapsed=86.5s

  [5562/21087] intraday_14148.csv.gz  in=279,800,400 out=36,571,257 elapsed=86.5s

  [5563/21087] intraday_14147.csv.gz  in=279,811,826 out=36,582,683 elapsed=86.5s

  [5564/21087] intraday_14149.csv.gz  in=279,824,177 out=36,595,034 elapsed=86.5s

  [5565/21087] intraday_1415.csv.gz  in=279,836,356 out=36,595,034 elapsed=86.5s

  [5566/21087] intraday_14151.csv.gz  in=279,846,109 out=36,604,787 elapsed=86.5s

  [5567/21087] intraday_14152.csv.gz  in=279,856,231 out=36,614,909 elapsed=86.5s

  [5568/21087] intraday_14150.csv.gz  in=279,869,263 out=36,627,941 elapsed=86.5s

  [5569/21087] intraday_14153.csv.gz  in=279,880,471 out=36,639,149 elapsed=86.5s

  [5570/21087] intraday_14154.csv.gz  in=279,891,120 out=36,649,798 elapsed=86.6s

  [5571/21087] intraday_14155.csv.gz  in=279,905,276 out=36,663,954 elapsed=86.6s

  [5572/21087] intraday_14156.csv.gz  in=279,920,519 out=36,679,197 elapsed=86.6s

  [5573/21087] intraday_14157.csv.gz  in=279,934,138 out=36,692,816 elapsed=86.6s

  [5574/21087] intraday_14159.csv.gz  in=279,937,816 out=36,696,494 elapsed=86.6s

  [5575/21087] intraday_14158.csv.gz  in=279,947,536 out=36,706,214 elapsed=86.6s

  [5576/21087] intraday_1416.csv.gz  in=279,959,356 out=36,706,214 elapsed=86.6s

  [5577/21087] intraday_14160.csv.gz  in=279,961,359 out=36,708,217 elapsed=86.6s

  [5578/21087] intraday_14161.csv.gz  in=279,973,827 out=36,720,685 elapsed=86.7s

  [5579/21087] intraday_14162.csv.gz  in=279,984,003 out=36,730,768 elapsed=86.7s

  [5580/21087] intraday_14163.csv.gz  in=279,995,153 out=36,741,918 elapsed=86.7s

  [5581/21087] intraday_14164.csv.gz  in=280,004,942 out=36,751,707 elapsed=86.7s

  [5582/21087] intraday_14165.csv.gz  in=280,015,200 out=36,761,965 elapsed=86.7s

  [5583/21087] intraday_14166.csv.gz  in=280,027,603 out=36,774,368 elapsed=86.7s

  [5584/21087] intraday_14168.csv.gz  in=280,041,633 out=36,788,398 elapsed=86.7s

  [5585/21087] intraday_14167.csv.gz  in=280,051,848 out=36,798,613 elapsed=86.7s

  [5586/21087] intraday_1417.csv.gz  in=280,065,319 out=36,798,613 elapsed=86.7s

  [5587/21087] intraday_14169.csv.gz  in=280,079,050 out=36,812,344 elapsed=86.7s

  [5588/21087] intraday_14171.csv.gz  in=280,090,847 out=36,824,141 elapsed=86.7s

  [5589/21087] intraday_14170.csv.gz  in=280,103,250 out=36,836,544 elapsed=86.8s

  [5590/21087] intraday_14173.csv.gz  in=280,106,674 out=36,839,968 elapsed=86.8s

  [5591/21087] intraday_14172.csv.gz  in=280,119,217 out=36,852,511 elapsed=86.8s

  [5592/21087] intraday_14174.csv.gz  in=280,122,534 out=36,855,828 elapsed=86.8s

  [5593/21087] intraday_14175.csv.gz  in=280,132,350 out=36,865,644 elapsed=86.8s

  [5594/21087] intraday_14177.csv.gz  in=280,143,612 out=36,876,906 elapsed=86.8s

  [5595/21087] intraday_14178.csv.gz  in=280,153,927 out=36,887,221 elapsed=86.8s

  [5596/21087] intraday_14176.csv.gz  in=280,169,508 out=36,902,802 elapsed=86.8s

  [5597/21087] intraday_14179.csv.gz  in=280,183,859 out=36,917,153 elapsed=86.9s

  [5598/21087] intraday_1418.csv.gz  in=280,198,347 out=36,917,153 elapsed=86.9s

  [5599/21087] intraday_14180.csv.gz  in=280,209,650 out=36,928,456 elapsed=86.9s

  [5600/21087] intraday_14181.csv.gz  in=280,220,955 out=36,939,761 elapsed=86.9s

  [5601/21087] intraday_14182.csv.gz  in=280,231,276 out=36,950,082 elapsed=86.9s

  [5602/21087] intraday_14183.csv.gz  in=280,243,089 out=36,961,895 elapsed=86.9s

  [5603/21087] intraday_14184.csv.gz  in=280,255,082 out=36,973,888 elapsed=86.9s

  [5604/21087] intraday_14185.csv.gz  in=280,267,590 out=36,986,396 elapsed=86.9s

  [5605/21087] intraday_14186.csv.gz  in=280,276,901 out=36,995,707 elapsed=86.9s

  [5606/21087] intraday_14187.csv.gz  in=280,280,753 out=36,999,559 elapsed=86.9s

  [5607/21087] intraday_14188.csv.gz  in=280,286,941 out=37,005,747 elapsed=86.9s

  [5608/21087] intraday_1419.csv.gz  in=280,300,837 out=37,005,747 elapsed=87.0s

  [5609/21087] intraday_14189.csv.gz  in=280,313,922 out=37,018,832 elapsed=87.0s

  [5610/21087] intraday_14191.csv.gz  in=280,325,001 out=37,029,911 elapsed=87.0s

  [5611/21087] intraday_14190.csv.gz  in=280,337,770 out=37,042,680 elapsed=87.0s

  [5612/21087] intraday_14192.csv.gz  in=280,350,375 out=37,055,285 elapsed=87.0s

  [5613/21087] intraday_14193.csv.gz  in=280,359,730 out=37,064,640 elapsed=87.0s

  [5614/21087] intraday_14194.csv.gz  in=280,372,102 out=37,077,012 elapsed=87.0s

  [5615/21087] intraday_14195.csv.gz  in=280,384,582 out=37,089,492 elapsed=87.0s

  [5616/21087] intraday_14196.csv.gz  in=280,397,175 out=37,102,085 elapsed=87.0s

  [5617/21087] intraday_14197.csv.gz  in=280,408,854 out=37,113,764 elapsed=87.1s

  [5618/21087] intraday_14199.csv.gz  in=280,418,788 out=37,123,698 elapsed=87.1s

  [5619/21087] intraday_14198.csv.gz  in=280,430,820 out=37,135,730 elapsed=87.1s

  [5620/21087] intraday_1420.csv.gz  in=280,446,949 out=37,135,730 elapsed=87.1s

  [5621/21087] intraday_14200.csv.gz  in=280,459,893 out=37,148,674 elapsed=87.1s

  [5622/21087] intraday_14201.csv.gz  in=280,472,494 out=37,161,275 elapsed=87.1s

  [5623/21087] intraday_14202.csv.gz  in=280,484,189 out=37,172,970 elapsed=87.1s

  [5624/21087] intraday_14203.csv.gz  in=280,495,049 out=37,183,830 elapsed=87.1s

  [5625/21087] intraday_14204.csv.gz  in=280,504,203 out=37,192,984 elapsed=87.1s

  [5626/21087] intraday_14205.csv.gz  in=280,514,521 out=37,203,302 elapsed=87.1s

  [5627/21087] intraday_14206.csv.gz  in=280,527,165 out=37,215,946 elapsed=87.1s

  [5628/21087] intraday_14207.csv.gz  in=280,542,456 out=37,231,237 elapsed=87.1s

  [5629/21087] intraday_14208.csv.gz  in=280,557,039 out=37,245,820 elapsed=87.2s

  [5630/21087] intraday_1421.csv.gz  in=280,569,162 out=37,245,820 elapsed=87.2s

  [5631/21087] intraday_14209.csv.gz  in=280,583,739 out=37,260,397 elapsed=87.2s

  [5632/21087] intraday_14211.csv.gz  in=280,595,914 out=37,272,572 elapsed=87.2s

  [5633/21087] intraday_14210.csv.gz  in=280,606,999 out=37,283,657 elapsed=87.2s

  [5634/21087] intraday_14212.csv.gz  in=280,617,349 out=37,294,007 elapsed=87.2s

  [5635/21087] intraday_14213.csv.gz  in=280,632,558 out=37,309,175 elapsed=87.2s

  [5636/21087] intraday_14214.csv.gz  in=280,642,402 out=37,319,019 elapsed=87.2s

  [5637/21087] intraday_14215.csv.gz  in=280,654,776 out=37,331,393 elapsed=87.2s

  [5638/21087] intraday_14217.csv.gz  in=280,666,289 out=37,342,906 elapsed=87.3s

  [5639/21087] intraday_14216.csv.gz  in=280,678,797 out=37,355,414 elapsed=87.3s

  [5640/21087] intraday_14219.csv.gz  in=280,689,693 out=37,366,310 elapsed=87.3s

  [5641/21087] intraday_14218.csv.gz  in=280,702,430 out=37,379,047 elapsed=87.3s

  [5642/21087] intraday_1422.csv.gz  in=280,716,219 out=37,379,047 elapsed=87.3s

  [5643/21087] intraday_14220.csv.gz  in=280,728,438 out=37,391,266 elapsed=87.3s

  [5644/21087] intraday_14222.csv.gz  in=280,738,891 out=37,401,719 elapsed=87.3s

  [5645/21087] intraday_14221.csv.gz  in=280,750,409 out=37,413,237 elapsed=87.3s

  [5646/21087] intraday_14223.csv.gz  in=280,762,024 out=37,424,852 elapsed=87.3s

  [5647/21087] intraday_14224.csv.gz  in=280,774,298 out=37,437,126 elapsed=87.3s

  [5648/21087] intraday_14225.csv.gz  in=280,786,672 out=37,449,500 elapsed=87.4s

  [5649/21087] intraday_14226.csv.gz  in=280,798,934 out=37,461,762 elapsed=87.4s

  [5650/21087] intraday_14227.csv.gz  in=280,812,526 out=37,474,549 elapsed=87.4s

  [5651/21087] intraday_14228.csv.gz  in=280,823,837 out=37,485,860 elapsed=87.4s

  [5652/21087] intraday_1423.csv.gz  in=280,838,916 out=37,485,860 elapsed=87.4s

  [5653/21087] intraday_14229.csv.gz  in=280,850,228 out=37,497,172 elapsed=87.4s

  [5654/21087] intraday_14230.csv.gz  in=280,864,816 out=37,511,760 elapsed=87.4s

  [5655/21087] intraday_14232.csv.gz  in=280,876,245 out=37,523,189 elapsed=87.4s

  [5656/21087] intraday_14231.csv.gz  in=280,887,801 out=37,534,745 elapsed=87.4s

  [5657/21087] intraday_14233.csv.gz  in=280,900,483 out=37,547,427 elapsed=87.4s

  [5658/21087] intraday_14234.csv.gz  in=280,914,016 out=37,560,960 elapsed=87.5s

  [5659/21087] intraday_14235.csv.gz  in=280,926,284 out=37,573,228 elapsed=87.5s

  [5660/21087] intraday_14236.csv.gz  in=280,940,110 out=37,587,054 elapsed=87.5s

  [5661/21087] intraday_14237.csv.gz  in=280,953,299 out=37,600,243 elapsed=87.5s

  [5662/21087] intraday_14238.csv.gz  in=280,965,265 out=37,612,209 elapsed=87.5s

  [5663/21087] intraday_1424.csv.gz  in=280,978,738 out=37,612,209 elapsed=87.5s

  [5664/21087] intraday_14239.csv.gz  in=280,994,307 out=37,627,778 elapsed=87.5s

  [5665/21087] intraday_14240.csv.gz  in=281,011,316 out=37,644,787 elapsed=87.5s

  [5666/21087] intraday_14242.csv.gz  in=281,024,734 out=37,658,205 elapsed=87.5s

  [5667/21087] intraday_14243.csv.gz  in=281,036,827 out=37,670,298 elapsed=87.6s

  [5668/21087] intraday_14241.csv.gz  in=281,051,940 out=37,685,411 elapsed=87.6s

  [5669/21087] intraday_14244.csv.gz  in=281,064,309 out=37,697,780 elapsed=87.6s

  [5670/21087] intraday_14245.csv.gz  in=281,076,521 out=37,709,992 elapsed=87.6s

  [5671/21087] intraday_14246.csv.gz  in=281,085,402 out=37,718,873 elapsed=87.6s

  [5672/21087] intraday_14248.csv.gz  in=281,096,522 out=37,729,993 elapsed=87.6s

  [5673/21087] intraday_14247.csv.gz  in=281,108,976 out=37,742,447 elapsed=87.6s

  [5674/21087] intraday_1425.csv.gz  in=281,122,496 out=37,742,447 elapsed=87.6s

  [5675/21087] intraday_14249.csv.gz  in=281,134,529 out=37,754,480 elapsed=87.6s

  [5676/21087] intraday_14250.csv.gz  in=281,147,574 out=37,767,525 elapsed=87.7s

  [5677/21087] intraday_14251.csv.gz  in=281,160,752 out=37,780,703 elapsed=87.7s

  [5678/21087] intraday_14253.csv.gz  in=281,172,630 out=37,792,581 elapsed=87.7s

  [5679/21087] intraday_14252.csv.gz  in=281,182,560 out=37,802,511 elapsed=87.7s

  [5680/21087] intraday_14254.csv.gz  in=281,193,541 out=37,813,492 elapsed=87.7s

  [5681/21087] intraday_14255.csv.gz  in=281,207,931 out=37,827,882 elapsed=87.7s

  [5682/21087] intraday_14256.csv.gz  in=281,220,028 out=37,839,979 elapsed=87.7s

  [5683/21087] intraday_14257.csv.gz  in=281,233,300 out=37,853,251 elapsed=87.7s

  [5684/21087] intraday_1426.csv.gz  in=281,245,314 out=37,853,251 elapsed=87.7s

  [5685/21087] intraday_14259.csv.gz  in=281,257,007 out=37,864,944 elapsed=87.7s

  [5686/21087] intraday_14258.csv.gz  in=281,271,081 out=37,879,018 elapsed=87.8s

  [5687/21087] intraday_14260.csv.gz  in=281,285,268 out=37,893,205 elapsed=87.8s

  [5688/21087] intraday_14261.csv.gz  in=281,295,249 out=37,903,186 elapsed=87.8s

  [5689/21087] intraday_14262.csv.gz  in=281,307,720 out=37,915,657 elapsed=87.8s

  [5690/21087] intraday_14263.csv.gz  in=281,319,129 out=37,927,066 elapsed=87.8s

  [5691/21087] intraday_14264.csv.gz  in=281,329,117 out=37,937,054 elapsed=87.8s

  [5692/21087] intraday_14265.csv.gz  in=281,341,722 out=37,949,659 elapsed=87.8s

  [5693/21087] intraday_14266.csv.gz  in=281,349,446 out=37,957,383 elapsed=87.8s

  [5694/21087] intraday_14267.csv.gz  in=281,360,266 out=37,968,203 elapsed=87.8s

  [5695/21087] intraday_14268.csv.gz  in=281,369,847 out=37,977,784 elapsed=87.8s

  [5696/21087] intraday_1427.csv.gz  in=281,381,062 out=37,977,784 elapsed=87.8s

  [5697/21087] intraday_14269.csv.gz  in=281,396,811 out=37,993,533 elapsed=87.8s

  [5698/21087] intraday_14270.csv.gz  in=281,409,213 out=38,005,935 elapsed=87.9s

  [5699/21087] intraday_14271.csv.gz  in=281,422,242 out=38,018,964 elapsed=87.9s

  [5700/21087] intraday_14272.csv.gz  in=281,431,815 out=38,028,537 elapsed=87.9s

  [5701/21087] intraday_14273.csv.gz  in=281,443,561 out=38,040,283 elapsed=87.9s

  [5702/21087] intraday_14274.csv.gz  in=281,457,274 out=38,053,996 elapsed=87.9s

  [5703/21087] intraday_14276.csv.gz  in=281,466,809 out=38,063,531 elapsed=87.9s

  [5704/21087] intraday_14275.csv.gz  in=281,481,260 out=38,077,982 elapsed=87.9s

  [5705/21087] intraday_14277.csv.gz  in=281,494,202 out=38,090,924 elapsed=87.9s

  [5706/21087] intraday_14279.csv.gz  in=281,505,401 out=38,102,123 elapsed=87.9s

  [5707/21087] intraday_14278.csv.gz  in=281,517,646 out=38,114,368 elapsed=87.9s

  [5708/21087] intraday_1428.csv.gz  in=281,533,735 out=38,114,368 elapsed=87.9s

  [5709/21087] intraday_14280.csv.gz  in=281,543,964 out=38,124,597 elapsed=88.0s

  [5710/21087] intraday_14283.csv.gz  in=281,552,488 out=38,133,121 elapsed=88.0s

  [5711/21087] intraday_14284.csv.gz  in=281,555,521 out=38,136,154 elapsed=88.0s

  [5712/21087] intraday_14282.csv.gz  in=281,569,937 out=38,150,570 elapsed=88.0s

  [5713/21087] intraday_14281.csv.gz  in=281,581,741 out=38,162,374 elapsed=88.0s

  [5714/21087] intraday_14285.csv.gz  in=281,592,418 out=38,173,051 elapsed=88.0s

  [5715/21087] intraday_14286.csv.gz  in=281,603,701 out=38,184,334 elapsed=88.0s

  [5716/21087] intraday_14287.csv.gz  in=281,617,434 out=38,198,067 elapsed=88.0s

  [5717/21087] intraday_14288.csv.gz  in=281,627,818 out=38,208,451 elapsed=88.0s

  [5718/21087] intraday_14289.csv.gz  in=281,640,553 out=38,221,186 elapsed=88.0s

  [5719/21087] intraday_1429.csv.gz  in=281,660,463 out=38,221,186 elapsed=88.1s

  [5720/21087] intraday_14290.csv.gz  in=281,672,619 out=38,233,342 elapsed=88.1s

  [5721/21087] intraday_14292.csv.gz  in=281,682,453 out=38,243,176 elapsed=88.1s

  [5722/21087] intraday_14291.csv.gz  in=281,695,436 out=38,256,159 elapsed=88.1s

  [5723/21087] intraday_14293.csv.gz  in=281,705,465 out=38,266,188 elapsed=88.1s

  [5724/21087] intraday_14294.csv.gz  in=281,717,010 out=38,277,733 elapsed=88.1s

  [5725/21087] intraday_14297.csv.gz  in=281,734,024 out=38,294,747 elapsed=88.1s

  [5726/21087] intraday_14296.csv.gz  in=281,746,644 out=38,307,367 elapsed=88.1s

  [5727/21087] intraday_14295.csv.gz  in=281,757,718 out=38,318,441 elapsed=88.1s

  [5728/21087] intraday_14299.csv.gz  in=281,761,824 out=38,322,547 elapsed=88.2s

  [5729/21087] intraday_1430.csv.gz  in=281,773,966 out=38,322,547 elapsed=88.2s

  [5730/21087] intraday_14300.csv.gz  in=281,785,642 out=38,334,223 elapsed=88.2s

  [5731/21087] intraday_14298.csv.gz  in=281,797,740 out=38,346,321 elapsed=88.2s

  [5732/21087] intraday_14301.csv.gz  in=281,810,542 out=38,359,123 elapsed=88.2s

  [5733/21087] intraday_14302.csv.gz  in=281,819,821 out=38,368,402 elapsed=88.2s

  [5734/21087] intraday_14303.csv.gz  in=281,831,640 out=38,380,221 elapsed=88.2s

  [5735/21087] intraday_14304.csv.gz  in=281,840,530 out=38,389,111 elapsed=88.2s

  [5736/21087] intraday_14305.csv.gz  in=281,851,025 out=38,399,606 elapsed=88.3s

  [5737/21087] intraday_14306.csv.gz  in=281,862,637 out=38,411,218 elapsed=88.3s

  [5738/21087] intraday_14307.csv.gz  in=281,874,382 out=38,422,963 elapsed=88.3s

  [5739/21087] intraday_14308.csv.gz  in=281,886,938 out=38,435,519 elapsed=88.3s

  [5740/21087] intraday_1431.csv.gz  in=281,901,041 out=38,435,519 elapsed=88.3s

  [5741/21087] intraday_14309.csv.gz  in=281,914,922 out=38,449,400 elapsed=88.3s

  [5742/21087] intraday_14310.csv.gz  in=281,926,092 out=38,460,570 elapsed=88.3s

  [5743/21087] intraday_14311.csv.gz  in=281,937,608 out=38,472,086 elapsed=88.3s

  [5744/21087] intraday_14313.csv.gz  in=281,947,821 out=38,482,299 elapsed=88.3s

  [5745/21087] intraday_14312.csv.gz  in=281,959,909 out=38,494,387 elapsed=88.3s

  [5746/21087] intraday_14317.csv.gz  in=281,966,295 out=38,500,773 elapsed=88.4s

  [5747/21087] intraday_14315.csv.gz  in=281,975,906 out=38,510,384 elapsed=88.4s

  [5748/21087] intraday_14316.csv.gz  in=281,985,231 out=38,519,709 elapsed=88.4s

  [5749/21087] intraday_14314.csv.gz  in=281,996,321 out=38,530,799 elapsed=88.4s

  [5750/21087] intraday_14318.csv.gz  in=282,008,336 out=38,542,814 elapsed=88.4s

  [5751/21087] intraday_14319.csv.gz  in=282,019,111 out=38,553,589 elapsed=88.4s

  [5752/21087] intraday_1432.csv.gz  in=282,032,139 out=38,553,589 elapsed=88.4s

  [5753/21087] intraday_14320.csv.gz  in=282,042,290 out=38,563,740 elapsed=88.4s

  [5754/21087] intraday_14321.csv.gz  in=282,053,053 out=38,574,503 elapsed=88.5s

  [5755/21087] intraday_14324.csv.gz  in=282,064,127 out=38,585,577 elapsed=88.5s

  [5756/21087] intraday_14322.csv.gz  in=282,076,926 out=38,598,376 elapsed=88.5s

  [5757/21087] intraday_14323.csv.gz  in=282,088,047 out=38,609,497 elapsed=88.5s

  [5758/21087] intraday_14325.csv.gz  in=282,097,947 out=38,619,397 elapsed=88.5s

  [5759/21087] intraday_14326.csv.gz  in=282,108,810 out=38,630,260 elapsed=88.5s

  [5760/21087] intraday_14327.csv.gz  in=282,117,838 out=38,639,288 elapsed=88.5s

  [5761/21087] intraday_14328.csv.gz  in=282,132,721 out=38,654,171 elapsed=88.5s

  [5762/21087] intraday_14329.csv.gz  in=282,146,614 out=38,667,128 elapsed=88.5s

  [5763/21087] intraday_1433.csv.gz  in=282,158,256 out=38,667,128 elapsed=88.5s

  [5764/21087] intraday_14333.csv.gz  in=282,159,666 out=38,668,538 elapsed=88.6s

  [5765/21087] intraday_14331.csv.gz  in=282,170,950 out=38,679,822 elapsed=88.6s

  [5766/21087] intraday_14334.csv.gz  in=282,174,866 out=38,683,738 elapsed=88.6s

  [5767/21087] intraday_14332.csv.gz  in=282,185,855 out=38,694,727 elapsed=88.6s

  [5768/21087] intraday_14330.csv.gz  in=282,199,097 out=38,707,969 elapsed=88.6s

  [5769/21087] intraday_14335.csv.gz  in=282,210,602 out=38,719,474 elapsed=88.6s

  [5770/21087] intraday_14338.csv.gz  in=282,219,655 out=38,728,527 elapsed=88.6s

  [5771/21087] intraday_14336.csv.gz  in=282,231,451 out=38,740,323 elapsed=88.6s

  [5772/21087] intraday_14337.csv.gz  in=282,243,053 out=38,751,925 elapsed=88.6s

  [5773/21087] intraday_14339.csv.gz  in=282,257,651 out=38,766,523 elapsed=88.6s

  [5774/21087] intraday_1434.csv.gz  in=282,271,906 out=38,766,523 elapsed=88.7s

  [5775/21087] intraday_14340.csv.gz  in=282,282,194 out=38,776,811 elapsed=88.7s

  [5776/21087] intraday_14341.csv.gz  in=282,294,605 out=38,789,222 elapsed=88.7s

  [5777/21087] intraday_14342.csv.gz  in=282,304,760 out=38,799,377 elapsed=88.7s

  [5778/21087] intraday_14343.csv.gz  in=282,314,745 out=38,809,362 elapsed=88.7s

  [5779/21087] intraday_14344.csv.gz  in=282,326,400 out=38,821,017 elapsed=88.7s

  [5780/21087] intraday_14345.csv.gz  in=282,339,651 out=38,834,268 elapsed=88.7s

  [5781/21087] intraday_14346.csv.gz  in=282,357,628 out=38,852,245 elapsed=88.7s

  [5782/21087] intraday_14347.csv.gz  in=282,369,364 out=38,863,981 elapsed=88.7s

  [5783/21087] intraday_14349.csv.gz  in=282,380,087 out=38,874,704 elapsed=88.8s

  [5784/21087] intraday_1435.csv.gz  in=282,393,841 out=38,874,704 elapsed=88.8s

  [5785/21087] intraday_14348.csv.gz  in=282,406,938 out=38,887,801 elapsed=88.8s

  [5786/21087] intraday_14350.csv.gz  in=282,418,779 out=38,899,642 elapsed=88.8s

  [5787/21087] intraday_14351.csv.gz  in=282,432,388 out=38,913,251 elapsed=88.8s

  [5788/21087] intraday_14354.csv.gz  in=282,447,544 out=38,928,407 elapsed=88.8s

  [5789/21087] intraday_14353.csv.gz  in=282,457,344 out=38,938,207 elapsed=88.8s

  [5790/21087] intraday_14352.csv.gz  in=282,471,614 out=38,952,477 elapsed=88.8s

  [5791/21087] intraday_14357.csv.gz  in=282,471,655 out=38,952,518 elapsed=88.8s

  [5792/21087] intraday_14355.csv.gz  in=282,482,621 out=38,963,484 elapsed=88.9s

  [5793/21087] intraday_14356.csv.gz  in=282,490,744 out=38,971,607 elapsed=88.9s

  [5794/21087] intraday_14358.csv.gz  in=282,503,330 out=38,984,193 elapsed=88.9s

  [5795/21087] intraday_14359.csv.gz  in=282,513,602 out=38,994,465 elapsed=88.9s

  [5796/21087] intraday_1436.csv.gz  in=282,525,525 out=38,994,465 elapsed=88.9s

  [5797/21087] intraday_14360.csv.gz  in=282,537,119 out=39,006,059 elapsed=88.9s

  [5798/21087] intraday_14361.csv.gz  in=282,548,052 out=39,016,992 elapsed=88.9s

  [5799/21087] intraday_14362.csv.gz  in=282,561,426 out=39,030,366 elapsed=88.9s

  [5800/21087] intraday_14363.csv.gz  in=282,574,821 out=39,043,761 elapsed=88.9s

  [5801/21087] intraday_14365.csv.gz  in=282,586,286 out=39,055,226 elapsed=88.9s

  [5802/21087] intraday_14364.csv.gz  in=282,597,753 out=39,066,693 elapsed=88.9s

  [5803/21087] intraday_14367.csv.gz  in=282,612,707 out=39,081,647 elapsed=89.0s

  [5804/21087] intraday_14366.csv.gz  in=282,622,881 out=39,091,821 elapsed=89.0s

  [5805/21087] intraday_14369.csv.gz  in=282,634,300 out=39,103,240 elapsed=89.0s

  [5806/21087] intraday_14368.csv.gz  in=282,644,270 out=39,113,210 elapsed=89.0s

  [5807/21087] intraday_1437.csv.gz  in=282,658,980 out=39,113,210 elapsed=89.0s

  [5808/21087] intraday_14370.csv.gz  in=282,671,737 out=39,125,967 elapsed=89.0s

  [5809/21087] intraday_14372.csv.gz  in=282,683,609 out=39,137,839 elapsed=89.1s

  [5810/21087] intraday_14371.csv.gz  in=282,698,189 out=39,152,419 elapsed=89.1s

  [5811/21087] intraday_14373.csv.gz  in=282,709,979 out=39,164,209 elapsed=89.1s

  [5812/21087] intraday_14374.csv.gz  in=282,722,499 out=39,176,729 elapsed=89.1s

  [5813/21087] intraday_14375.csv.gz  in=282,734,804 out=39,189,034 elapsed=89.1s

  [5814/21087] intraday_14376.csv.gz  in=282,749,495 out=39,203,725 elapsed=89.1s

  [5815/21087] intraday_14377.csv.gz  in=282,764,590 out=39,218,820 elapsed=89.1s

  [5816/21087] intraday_1438.csv.gz  in=282,777,500 out=39,218,820 elapsed=89.1s

  [5817/21087] intraday_14378.csv.gz  in=282,797,208 out=39,238,528 elapsed=89.1s

  [5818/21087] intraday_14379.csv.gz  in=282,807,712 out=39,249,032 elapsed=89.1s

  [5819/21087] intraday_14380.csv.gz  in=282,823,133 out=39,264,453 elapsed=89.2s

  [5820/21087] intraday_14381.csv.gz  in=282,833,094 out=39,274,414 elapsed=89.2s

  [5821/21087] intraday_14383.csv.gz  in=282,843,493 out=39,284,813 elapsed=89.2s

  [5822/21087] intraday_14385.csv.gz  in=282,853,477 out=39,294,797 elapsed=89.2s

  [5823/21087] intraday_14384.csv.gz  in=282,865,519 out=39,306,839 elapsed=89.2s

  [5824/21087] intraday_14382.csv.gz  in=282,878,528 out=39,319,848 elapsed=89.2s

  [5825/21087] intraday_14386.csv.gz  in=282,891,267 out=39,332,587 elapsed=89.2s

  [5826/21087] intraday_14387.csv.gz  in=282,901,362 out=39,342,682 elapsed=89.2s

  [5827/21087] intraday_1439.csv.gz  in=282,911,369 out=39,342,682 elapsed=89.2s

  [5828/21087] intraday_14388.csv.gz  in=282,927,977 out=39,359,290 elapsed=89.2s

  [5829/21087] intraday_14389.csv.gz  in=282,936,795 out=39,368,108 elapsed=89.3s

  [5830/21087] intraday_14391.csv.gz  in=282,947,666 out=39,378,979 elapsed=89.3s

  [5831/21087] intraday_14393.csv.gz  in=282,957,945 out=39,389,258 elapsed=89.3s

  [5832/21087] intraday_14390.csv.gz  in=282,969,710 out=39,401,023 elapsed=89.3s

  [5833/21087] intraday_14392.csv.gz  in=282,983,219 out=39,414,532 elapsed=89.3s

  [5834/21087] intraday_14395.csv.gz  in=282,996,997 out=39,428,310 elapsed=89.3s

  [5835/21087] intraday_14394.csv.gz  in=283,015,031 out=39,444,552 elapsed=89.3s

  [5836/21087] intraday_14396.csv.gz  in=283,028,235 out=39,457,756 elapsed=89.3s

  [5837/21087] intraday_14397.csv.gz  in=283,041,941 out=39,471,462 elapsed=89.3s

  [5838/21087] intraday_14398.csv.gz  in=283,053,644 out=39,483,165 elapsed=89.4s

  [5839/21087] intraday_1440.csv.gz  in=283,067,558 out=39,483,165 elapsed=89.4s

  [5840/21087] intraday_14400.csv.gz  in=283,080,338 out=39,495,945 elapsed=89.4s

  [5841/21087] intraday_14399.csv.gz  in=283,090,766 out=39,506,373 elapsed=89.4s

  [5842/21087] intraday_14401.csv.gz  in=283,100,360 out=39,515,967 elapsed=89.4s

  [5843/21087] intraday_14402.csv.gz  in=283,113,089 out=39,528,696 elapsed=89.4s

  [5844/21087] intraday_14403.csv.gz  in=283,123,541 out=39,539,148 elapsed=89.4s

  [5845/21087] intraday_14406.csv.gz  in=283,124,222 out=39,539,829 elapsed=89.4s

  [5846/21087] intraday_14404.csv.gz  in=283,131,564 out=39,547,171 elapsed=89.4s

  [5847/21087] intraday_14405.csv.gz  in=283,145,915 out=39,561,522 elapsed=89.5s

  [5848/21087] intraday_14408.csv.gz  in=283,157,427 out=39,573,034 elapsed=89.5s

  [5849/21087] intraday_14407.csv.gz  in=283,173,423 out=39,589,030 elapsed=89.5s

  [5850/21087] intraday_1441.csv.gz  in=283,187,961 out=39,589,030 elapsed=89.5s

  [5851/21087] intraday_14409.csv.gz  in=283,201,213 out=39,602,282 elapsed=89.5s

  [5852/21087] intraday_14413.csv.gz  in=283,213,260 out=39,614,329 elapsed=89.5s

  [5853/21087] intraday_14411.csv.gz  in=283,224,748 out=39,625,817 elapsed=89.5s

  [5854/21087] intraday_14410.csv.gz  in=283,235,870 out=39,636,939 elapsed=89.5s

  [5855/21087] intraday_14412.csv.gz  in=283,250,747 out=39,651,816 elapsed=89.5s

  [5856/21087] intraday_14414.csv.gz  in=283,261,942 out=39,663,011 elapsed=89.6s

  [5857/21087] intraday_14415.csv.gz  in=283,274,483 out=39,675,552 elapsed=89.6s

  [5858/21087] intraday_14416.csv.gz  in=283,287,386 out=39,688,455 elapsed=89.6s

  [5859/21087] intraday_14418.csv.gz  in=283,298,585 out=39,699,654 elapsed=89.6s

  [5860/21087] intraday_14417.csv.gz  in=283,309,394 out=39,710,463 elapsed=89.6s

  [5861/21087] intraday_1442.csv.gz  in=283,320,814 out=39,710,463 elapsed=89.6s

  [5862/21087] intraday_14420.csv.gz  in=283,321,608 out=39,711,257 elapsed=89.6s

  [5863/21087] intraday_14419.csv.gz  in=283,333,527 out=39,723,176 elapsed=89.6s

  [5864/21087] intraday_14421.csv.gz  in=283,346,756 out=39,736,405 elapsed=89.7s

  [5865/21087] intraday_14422.csv.gz  in=283,360,613 out=39,750,262 elapsed=89.7s

  [5866/21087] intraday_14423.csv.gz  in=283,370,484 out=39,760,133 elapsed=89.7s

  [5867/21087] intraday_14424.csv.gz  in=283,382,057 out=39,771,706 elapsed=89.7s

  [5868/21087] intraday_14425.csv.gz  in=283,396,292 out=39,785,941 elapsed=89.7s

  [5869/21087] intraday_14426.csv.gz  in=283,407,749 out=39,797,398 elapsed=89.7s

  [5870/21087] intraday_14427.csv.gz  in=283,421,796 out=39,811,445 elapsed=89.7s

  [5871/21087] intraday_14428.csv.gz  in=283,433,256 out=39,822,905 elapsed=89.7s

  [5872/21087] intraday_14429.csv.gz  in=283,447,062 out=39,836,711 elapsed=89.7s

  [5873/21087] intraday_1443.csv.gz  in=283,462,021 out=39,836,711 elapsed=89.7s

  [5874/21087] intraday_14431.csv.gz  in=283,472,892 out=39,847,582 elapsed=89.8s

  [5875/21087] intraday_14430.csv.gz  in=283,484,850 out=39,859,540 elapsed=89.8s

  [5876/21087] intraday_14433.csv.gz  in=283,489,782 out=39,864,472 elapsed=89.8s

  [5877/21087] intraday_14432.csv.gz  in=283,497,769 out=39,872,459 elapsed=89.8s

  [5878/21087] intraday_14435.csv.gz  in=283,506,919 out=39,881,609 elapsed=89.8s

  [5879/21087] intraday_14434.csv.gz  in=283,519,946 out=39,894,636 elapsed=89.8s

  [5880/21087] intraday_14436.csv.gz  in=283,532,575 out=39,907,265 elapsed=89.8s

  [5881/21087] intraday_14437.csv.gz  in=283,545,008 out=39,919,698 elapsed=89.8s

  [5882/21087] intraday_14438.csv.gz  in=283,557,892 out=39,932,582 elapsed=89.8s

  [5883/21087] intraday_1444.csv.gz  in=283,572,003 out=39,932,582 elapsed=89.8s

  [5884/21087] intraday_14439.csv.gz  in=283,584,490 out=39,945,069 elapsed=89.8s

  [5885/21087] intraday_14440.csv.gz  in=283,594,323 out=39,954,902 elapsed=89.9s

  [5886/21087] intraday_14442.csv.gz  in=283,603,231 out=39,963,810 elapsed=89.9s

  [5887/21087] intraday_14441.csv.gz  in=283,613,952 out=39,974,531 elapsed=89.9s

  [5888/21087] intraday_14443.csv.gz  in=283,624,182 out=39,984,761 elapsed=89.9s

  [5889/21087] intraday_14444.csv.gz  in=283,636,478 out=39,997,057 elapsed=89.9s

  [5890/21087] intraday_14445.csv.gz  in=283,643,704 out=40,004,283 elapsed=89.9s

  [5891/21087] intraday_14448.csv.gz  in=283,655,235 out=40,015,814 elapsed=89.9s

  [5892/21087] intraday_14447.csv.gz  in=283,667,285 out=40,027,864 elapsed=89.9s

  [5893/21087] intraday_14446.csv.gz  in=283,673,684 out=40,034,263 elapsed=89.9s

  [5894/21087] intraday_14449.csv.gz  in=283,684,903 out=40,045,482 elapsed=89.9s

  [5895/21087] intraday_1445.csv.gz  in=283,695,594 out=40,045,482 elapsed=89.9s

  [5896/21087] intraday_14451.csv.gz  in=283,705,581 out=40,055,469 elapsed=90.0s

  [5897/21087] intraday_14452.csv.gz  in=283,717,912 out=40,067,800 elapsed=90.0s

  [5898/21087] intraday_14450.csv.gz  in=283,729,257 out=40,079,145 elapsed=90.0s

  [5899/21087] intraday_14453.csv.gz  in=283,741,577 out=40,091,465 elapsed=90.0s

  [5900/21087] intraday_14454.csv.gz  in=283,754,032 out=40,103,920 elapsed=90.0s

  [5901/21087] intraday_14456.csv.gz  in=283,765,404 out=40,115,292 elapsed=90.0s

  [5902/21087] intraday_14455.csv.gz  in=283,777,859 out=40,127,747 elapsed=90.0s

  [5903/21087] intraday_14458.csv.gz  in=283,787,590 out=40,137,478 elapsed=90.1s

  [5904/21087] intraday_14457.csv.gz  in=283,799,222 out=40,149,110 elapsed=90.1s

  [5905/21087] intraday_1446.csv.gz  in=283,811,842 out=40,149,110 elapsed=90.1s

  [5906/21087] intraday_14459.csv.gz  in=283,823,582 out=40,160,850 elapsed=90.1s

  [5907/21087] intraday_14460.csv.gz  in=283,829,913 out=40,167,181 elapsed=90.1s

  [5908/21087] intraday_14461.csv.gz  in=283,840,403 out=40,177,671 elapsed=90.1s

  [5909/21087] intraday_14462.csv.gz  in=283,850,729 out=40,187,997 elapsed=90.1s

  [5910/21087] intraday_14463.csv.gz  in=283,860,733 out=40,198,001 elapsed=90.1s

  [5911/21087] intraday_14464.csv.gz  in=283,875,134 out=40,212,402 elapsed=90.1s

  [5912/21087] intraday_14466.csv.gz  in=283,887,591 out=40,224,859 elapsed=90.1s

  [5913/21087] intraday_14465.csv.gz  in=283,901,260 out=40,238,528 elapsed=90.1s

  [5914/21087] intraday_14467.csv.gz  in=283,914,399 out=40,251,667 elapsed=90.2s

  [5915/21087] intraday_14468.csv.gz  in=283,923,718 out=40,260,986 elapsed=90.2s

  [5916/21087] intraday_1447.csv.gz  in=283,936,684 out=40,260,986 elapsed=90.2s

  [5917/21087] intraday_14469.csv.gz  in=283,947,950 out=40,272,252 elapsed=90.2s

  [5918/21087] intraday_14471.csv.gz  in=283,958,996 out=40,283,298 elapsed=90.2s

  [5919/21087] intraday_14473.csv.gz  in=283,962,205 out=40,286,507 elapsed=90.2s

  [5920/21087] intraday_14470.csv.gz  in=283,974,750 out=40,299,052 elapsed=90.2s

  [5921/21087] intraday_14472.csv.gz  in=283,986,817 out=40,311,119 elapsed=90.2s

  [5922/21087] intraday_14474.csv.gz  in=283,990,050 out=40,314,352 elapsed=90.2s

  [5923/21087] intraday_14475.csv.gz  in=284,003,748 out=40,328,050 elapsed=90.2s

  [5924/21087] intraday_14476.csv.gz  in=284,015,770 out=40,340,072 elapsed=90.2s

  [5925/21087] intraday_14478.csv.gz  in=284,026,042 out=40,350,344 elapsed=90.3s

  [5926/21087] intraday_14477.csv.gz  in=284,039,083 out=40,363,385 elapsed=90.3s

  [5927/21087] intraday_1448.csv.gz  in=284,053,108 out=40,363,385 elapsed=90.3s

  [5928/21087] intraday_14479.csv.gz  in=284,063,228 out=40,373,505 elapsed=90.3s

  [5929/21087] intraday_14480.csv.gz  in=284,076,326 out=40,386,603 elapsed=90.3s

  [5930/21087] intraday_14481.csv.gz  in=284,092,126 out=40,402,403 elapsed=90.3s

  [5931/21087] intraday_14482.csv.gz  in=284,106,173 out=40,416,450 elapsed=90.3s

  [5932/21087] intraday_14483.csv.gz  in=284,120,649 out=40,430,926 elapsed=90.3s

  [5933/21087] intraday_14485.csv.gz  in=284,132,145 out=40,442,422 elapsed=90.3s

  [5934/21087] intraday_14484.csv.gz  in=284,149,594 out=40,458,841 elapsed=90.3s

  [5935/21087] intraday_14487.csv.gz  in=284,166,794 out=40,476,041 elapsed=90.4s

  [5936/21087] intraday_14489.csv.gz  in=284,177,728 out=40,486,975 elapsed=90.4s

  [5937/21087] intraday_14488.csv.gz  in=284,189,069 out=40,498,316 elapsed=90.4s

  [5938/21087] intraday_14486.csv.gz  in=284,201,312 out=40,510,294 elapsed=90.4s

  [5939/21087] intraday_14492.csv.gz  in=284,201,471 out=40,510,453 elapsed=90.4s

  [5940/21087] intraday_14491.csv.gz  in=284,207,776 out=40,516,758 elapsed=90.4s

  [5941/21087] intraday_1449.csv.gz  in=284,219,374 out=40,516,758 elapsed=90.4s

  [5942/21087] intraday_14490.csv.gz  in=284,233,786 out=40,531,170 elapsed=90.5s

  [5943/21087] intraday_14493.csv.gz  in=284,244,765 out=40,542,149 elapsed=90.5s

  [5944/21087] intraday_14494.csv.gz  in=284,256,651 out=40,554,035 elapsed=90.5s

  [5945/21087] intraday_14495.csv.gz  in=284,268,601 out=40,565,985 elapsed=90.5s

  [5946/21087] intraday_14496.csv.gz  in=284,279,023 out=40,576,407 elapsed=90.5s

  [5947/21087] intraday_14497.csv.gz  in=284,290,949 out=40,588,333 elapsed=90.5s

  [5948/21087] intraday_14498.csv.gz  in=284,304,532 out=40,601,916 elapsed=90.5s

  [5949/21087] intraday_14499.csv.gz  in=284,318,167 out=40,615,551 elapsed=90.5s

  [5950/21087] intraday_1450.csv.gz  in=284,337,401 out=40,615,551 elapsed=90.5s

  [5951/21087] intraday_14500.csv.gz  in=284,349,247 out=40,627,397 elapsed=90.5s

  [5952/21087] intraday_14502.csv.gz  in=284,359,752 out=40,637,902 elapsed=90.6s

  [5953/21087] intraday_14503.csv.gz  in=284,374,906 out=40,653,056 elapsed=90.6s

  [5954/21087] intraday_14504.csv.gz  in=284,384,543 out=40,662,693 elapsed=90.6s

  [5955/21087] intraday_14501.csv.gz  in=284,396,043 out=40,674,193 elapsed=90.6s

  [5956/21087] intraday_14505.csv.gz  in=284,407,015 out=40,685,165 elapsed=90.6s

  [5957/21087] intraday_14506.csv.gz  in=284,420,679 out=40,698,829 elapsed=90.6s

  [5958/21087] intraday_14508.csv.gz  in=284,430,908 out=40,709,058 elapsed=90.6s

  [5959/21087] intraday_14507.csv.gz  in=284,445,748 out=40,723,898 elapsed=90.6s

  [5960/21087] intraday_14509.csv.gz  in=284,465,438 out=40,741,373 elapsed=90.6s

  [5961/21087] intraday_1451.csv.gz  in=284,477,805 out=40,741,373 elapsed=90.6s

  [5962/21087] intraday_14510.csv.gz  in=284,489,849 out=40,753,417 elapsed=90.7s

  [5963/21087] intraday_14511.csv.gz  in=284,503,460 out=40,767,028 elapsed=90.7s

  [5964/21087] intraday_14512.csv.gz  in=284,517,203 out=40,780,771 elapsed=90.7s

  [5965/21087] intraday_14513.csv.gz  in=284,534,650 out=40,798,218 elapsed=90.7s

  [5966/21087] intraday_14514.csv.gz  in=284,552,117 out=40,815,685 elapsed=90.7s

  [5967/21087] intraday_14515.csv.gz  in=284,565,547 out=40,829,115 elapsed=90.7s

  [5968/21087] intraday_14517.csv.gz  in=284,576,469 out=40,840,037 elapsed=90.7s

  [5969/21087] intraday_14516.csv.gz  in=284,589,513 out=40,853,081 elapsed=90.7s

  [5970/21087] intraday_14518.csv.gz  in=284,601,893 out=40,865,461 elapsed=90.7s

  [5971/21087] intraday_14519.csv.gz  in=284,611,216 out=40,874,784 elapsed=90.7s

  [5972/21087] intraday_1452.csv.gz  in=284,623,688 out=40,874,784 elapsed=90.7s

  [5973/21087] intraday_14521.csv.gz  in=284,633,799 out=40,884,895 elapsed=90.8s

  [5974/21087] intraday_14522.csv.gz  in=284,644,823 out=40,895,913 elapsed=90.8s

  [5975/21087] intraday_14520.csv.gz  in=284,657,997 out=40,909,087 elapsed=90.8s

  [5976/21087] intraday_14523.csv.gz  in=284,670,214 out=40,921,304 elapsed=90.8s

  [5977/21087] intraday_14526.csv.gz  in=284,680,398 out=40,931,488 elapsed=90.8s

  [5978/21087] intraday_14524.csv.gz  in=284,694,195 out=40,945,285 elapsed=90.8s

  [5979/21087] intraday_14525.csv.gz  in=284,705,082 out=40,956,172 elapsed=90.8s

  [5980/21087] intraday_14527.csv.gz  in=284,716,864 out=40,967,954 elapsed=90.8s

  [5981/21087] intraday_1453.csv.gz  in=284,729,367 out=40,967,954 elapsed=90.9s

  [5982/21087] intraday_14530.csv.gz  in=284,743,031 out=40,981,618 elapsed=90.9s

  [5983/21087] intraday_14529.csv.gz  in=284,754,651 out=40,993,238 elapsed=90.9s

  [5984/21087] intraday_14528.csv.gz  in=284,767,835 out=41,006,422 elapsed=90.9s

  [5985/21087] intraday_14531.csv.gz  in=284,781,446 out=41,020,033 elapsed=90.9s

  [5986/21087] intraday_14532.csv.gz  in=284,794,618 out=41,033,205 elapsed=90.9s

  [5987/21087] intraday_14533.csv.gz  in=284,810,045 out=41,048,632 elapsed=90.9s

  [5988/21087] intraday_14534.csv.gz  in=284,820,542 out=41,059,129 elapsed=90.9s

  [5989/21087] intraday_14535.csv.gz  in=284,834,170 out=41,072,757 elapsed=90.9s

  [5990/21087] intraday_14536.csv.gz  in=284,847,625 out=41,086,212 elapsed=90.9s

  [5991/21087] intraday_14539.csv.gz  in=284,856,501 out=41,095,088 elapsed=91.0s

  [5992/21087] intraday_1454.csv.gz  in=284,869,245 out=41,095,088 elapsed=91.0s

  [5993/21087] intraday_14537.csv.gz  in=284,879,705 out=41,105,548 elapsed=91.0s

  [5994/21087] intraday_14538.csv.gz  in=284,892,106 out=41,117,949 elapsed=91.0s

  [5995/21087] intraday_14541.csv.gz  in=284,900,833 out=41,126,676 elapsed=91.0s

  [5996/21087] intraday_14540.csv.gz  in=284,912,437 out=41,138,280 elapsed=91.0s

  [5997/21087] intraday_14543.csv.gz  in=284,923,894 out=41,149,737 elapsed=91.0s

  [5998/21087] intraday_14542.csv.gz  in=284,938,390 out=41,164,233 elapsed=91.0s

  [5999/21087] intraday_14544.csv.gz  in=284,953,003 out=41,178,836 elapsed=91.0s

  [6000/21087] intraday_14545.csv.gz  in=284,964,117 out=41,189,950 elapsed=91.1s

  [6001/21087] intraday_14546.csv.gz  in=284,975,380 out=41,201,213 elapsed=91.1s

  [6002/21087] intraday_14547.csv.gz  in=284,987,842 out=41,213,675 elapsed=91.1s

  [6003/21087] intraday_14548.csv.gz  in=285,000,327 out=41,226,160 elapsed=91.1s

  [6004/21087] intraday_1455.csv.gz  in=285,012,568 out=41,226,160 elapsed=91.1s

  [6005/21087] intraday_14549.csv.gz  in=285,024,169 out=41,237,761 elapsed=91.1s

  [6006/21087] intraday_14551.csv.gz  in=285,036,338 out=41,249,930 elapsed=91.1s

  [6007/21087] intraday_14550.csv.gz  in=285,049,470 out=41,263,062 elapsed=91.1s

  [6008/21087] intraday_14552.csv.gz  in=285,059,640 out=41,273,232 elapsed=91.1s

  [6009/21087] intraday_14553.csv.gz  in=285,069,975 out=41,283,567 elapsed=91.1s

  [6010/21087] intraday_14554.csv.gz  in=285,081,197 out=41,294,789 elapsed=91.2s

  [6011/21087] intraday_14555.csv.gz  in=285,082,363 out=41,295,955 elapsed=91.2s

  [6012/21087] intraday_14556.csv.gz  in=285,090,704 out=41,304,296 elapsed=91.2s

  [6013/21087] intraday_14557.csv.gz  in=285,108,670 out=41,319,404 elapsed=91.2s

  [6014/21087] intraday_14558.csv.gz  in=285,118,644 out=41,329,378 elapsed=91.2s

  [6015/21087] intraday_1456.csv.gz  in=285,129,752 out=41,329,378 elapsed=91.2s

  [6016/21087] intraday_14559.csv.gz  in=285,140,022 out=41,339,648 elapsed=91.2s

  [6017/21087] intraday_14560.csv.gz  in=285,154,573 out=41,354,199 elapsed=91.2s

  [6018/21087] intraday_14563.csv.gz  in=285,166,490 out=41,366,116 elapsed=91.2s

  [6019/21087] intraday_14562.csv.gz  in=285,178,718 out=41,378,344 elapsed=91.2s

  [6020/21087] intraday_14561.csv.gz  in=285,190,206 out=41,389,832 elapsed=91.2s

  [6021/21087] intraday_14564.csv.gz  in=285,203,232 out=41,402,858 elapsed=91.3s

  [6022/21087] intraday_14566.csv.gz  in=285,213,033 out=41,412,659 elapsed=91.3s

  [6023/21087] intraday_14567.csv.gz  in=285,224,740 out=41,424,366 elapsed=91.3s

  [6024/21087] intraday_14565.csv.gz  in=285,237,589 out=41,437,215 elapsed=91.3s

  [6025/21087] intraday_14568.csv.gz  in=285,247,925 out=41,447,551 elapsed=91.3s

  [6026/21087] intraday_14569.csv.gz  in=285,260,621 out=41,460,247 elapsed=91.3s

  [6027/21087] intraday_14571.csv.gz  in=285,260,669 out=41,460,295 elapsed=91.3s

  [6028/21087] intraday_1457.csv.gz  in=285,273,232 out=41,460,295 elapsed=91.3s

  [6029/21087] intraday_14570.csv.gz  in=285,285,100 out=41,472,163 elapsed=91.3s

  [6030/21087] intraday_14573.csv.gz  in=285,297,134 out=41,484,197 elapsed=91.4s

  [6031/21087] intraday_14572.csv.gz  in=285,314,305 out=41,497,621 elapsed=91.4s

  [6032/21087] intraday_14574.csv.gz  in=285,325,900 out=41,509,216 elapsed=91.4s

  [6033/21087] intraday_14575.csv.gz  in=285,335,313 out=41,518,629 elapsed=91.4s

  [6034/21087] intraday_14576.csv.gz  in=285,347,419 out=41,530,735 elapsed=91.4s

  [6035/21087] intraday_14577.csv.gz  in=285,355,692 out=41,538,943 elapsed=91.4s

  [6036/21087] intraday_14578.csv.gz  in=285,365,999 out=41,549,250 elapsed=91.4s

  [6037/21087] intraday_14579.csv.gz  in=285,378,426 out=41,561,677 elapsed=91.4s

  [6038/21087] intraday_1458.csv.gz  in=285,391,308 out=41,561,677 elapsed=91.4s

  [6039/21087] intraday_14580.csv.gz  in=285,403,478 out=41,573,847 elapsed=91.4s

  [6040/21087] intraday_14581.csv.gz  in=285,416,008 out=41,586,377 elapsed=91.4s

  [6041/21087] intraday_14582.csv.gz  in=285,430,631 out=41,601,000 elapsed=91.5s

  [6042/21087] intraday_14583.csv.gz  in=285,454,062 out=41,616,377 elapsed=91.5s

  [6043/21087] intraday_14584.csv.gz  in=285,460,997 out=41,623,312 elapsed=91.5s

  [6044/21087] intraday_14585.csv.gz  in=285,463,181 out=41,625,496 elapsed=91.5s

  [6045/21087] intraday_14586.csv.gz  in=285,473,297 out=41,635,612 elapsed=91.5s

  [6046/21087] intraday_14587.csv.gz  in=285,485,400 out=41,647,715 elapsed=91.5s

  [6047/21087] intraday_1459.csv.gz  in=285,502,456 out=41,647,715 elapsed=91.5s

  [6048/21087] intraday_14588.csv.gz  in=285,517,206 out=41,662,234 elapsed=91.5s

  [6049/21087] intraday_14589.csv.gz  in=285,528,660 out=41,673,688 elapsed=91.5s

  [6050/21087] intraday_14590.csv.gz  in=285,539,499 out=41,684,527 elapsed=91.5s

  [6051/21087] intraday_14591.csv.gz  in=285,551,520 out=41,696,548 elapsed=91.6s

  [6052/21087] intraday_14592.csv.gz  in=285,563,057 out=41,708,085 elapsed=91.6s

  [6053/21087] intraday_14593.csv.gz  in=285,572,440 out=41,717,468 elapsed=91.6s

  [6054/21087] intraday_14594.csv.gz  in=285,583,454 out=41,728,482 elapsed=91.6s

  [6055/21087] intraday_14596.csv.gz  in=285,593,864 out=41,738,892 elapsed=91.6s

  [6056/21087] intraday_14597.csv.gz  in=285,605,427 out=41,750,455 elapsed=91.6s

  [6057/21087] intraday_14598.csv.gz  in=285,611,975 out=41,757,003 elapsed=91.6s

  [6058/21087] intraday_14595.csv.gz  in=285,623,867 out=41,768,895 elapsed=91.6s

  [6059/21087] intraday_1460.csv.gz  in=285,635,744 out=41,768,895 elapsed=91.6s

  [6060/21087] intraday_14599.csv.gz  in=285,644,010 out=41,777,161 elapsed=91.7s

  [6061/21087] intraday_14600.csv.gz  in=285,657,237 out=41,790,388 elapsed=91.7s

  [6062/21087] intraday_14601.csv.gz  in=285,670,835 out=41,803,986 elapsed=91.7s

  [6063/21087] intraday_14602.csv.gz  in=285,682,509 out=41,815,660 elapsed=91.7s

  [6064/21087] intraday_14603.csv.gz  in=285,692,651 out=41,825,802 elapsed=91.7s

  [6065/21087] intraday_14604.csv.gz  in=285,702,836 out=41,835,987 elapsed=91.7s

  [6066/21087] intraday_14605.csv.gz  in=285,714,647 out=41,847,798 elapsed=91.7s

  [6067/21087] intraday_14608.csv.gz  in=285,726,880 out=41,860,031 elapsed=91.7s

  [6068/21087] intraday_14606.csv.gz  in=285,739,074 out=41,871,419 elapsed=91.7s

  [6069/21087] intraday_14607.csv.gz  in=285,750,531 out=41,882,876 elapsed=91.7s

  [6070/21087] intraday_14609.csv.gz  in=285,760,397 out=41,892,742 elapsed=91.7s

  [6071/21087] intraday_1461.csv.gz  in=285,771,947 out=41,892,742 elapsed=91.8s

  [6072/21087] intraday_14610.csv.gz  in=285,780,270 out=41,901,065 elapsed=91.8s

  [6073/21087] intraday_14611.csv.gz  in=285,793,084 out=41,913,879 elapsed=91.8s

  [6074/21087] intraday_14612.csv.gz  in=285,794,461 out=41,915,256 elapsed=91.8s

  [6075/21087] intraday_14613.csv.gz  in=285,797,143 out=41,917,938 elapsed=91.8s

  [6076/21087] intraday_14614.csv.gz  in=285,806,690 out=41,927,485 elapsed=91.8s

  [6077/21087] intraday_14615.csv.gz  in=285,817,800 out=41,938,595 elapsed=91.8s

  [6078/21087] intraday_14616.csv.gz  in=285,831,056 out=41,951,851 elapsed=91.8s

  [6079/21087] intraday_14617.csv.gz  in=285,847,022 out=41,967,817 elapsed=91.8s

  [6080/21087] intraday_14618.csv.gz  in=285,860,571 out=41,981,366 elapsed=91.8s

  [6081/21087] intraday_14619.csv.gz  in=285,872,284 out=41,993,079 elapsed=91.9s

  [6082/21087] intraday_1462.csv.gz  in=285,884,516 out=41,993,079 elapsed=91.9s

  [6083/21087] intraday_14620.csv.gz  in=285,894,974 out=42,003,537 elapsed=91.9s

  [6084/21087] intraday_14621.csv.gz  in=285,906,236 out=42,014,799 elapsed=91.9s

  [6085/21087] intraday_14622.csv.gz  in=285,919,973 out=42,028,536 elapsed=91.9s

  [6086/21087] intraday_14623.csv.gz  in=285,931,883 out=42,040,446 elapsed=91.9s

  [6087/21087] intraday_14625.csv.gz  in=285,945,918 out=42,054,481 elapsed=91.9s

  [6088/21087] intraday_14624.csv.gz  in=285,955,520 out=42,064,083 elapsed=91.9s

  [6089/21087] intraday_14626.csv.gz  in=285,965,372 out=42,073,935 elapsed=91.9s

  [6090/21087] intraday_14627.csv.gz  in=285,975,951 out=42,084,514 elapsed=91.9s

  [6091/21087] intraday_14628.csv.gz  in=285,988,205 out=42,096,768 elapsed=92.0s

  [6092/21087] intraday_14629.csv.gz  in=285,999,450 out=42,108,013 elapsed=92.0s

  [6093/21087] intraday_1463.csv.gz  in=286,012,636 out=42,108,013 elapsed=92.0s

  [6094/21087] intraday_14630.csv.gz  in=286,024,301 out=42,119,678 elapsed=92.0s

  [6095/21087] intraday_14632.csv.gz  in=286,034,801 out=42,130,178 elapsed=92.0s

  [6096/21087] intraday_14631.csv.gz  in=286,044,953 out=42,140,330 elapsed=92.0s

  [6097/21087] intraday_14633.csv.gz  in=286,057,323 out=42,152,700 elapsed=92.0s

  [6098/21087] intraday_14634.csv.gz  in=286,072,704 out=42,168,081 elapsed=92.0s

  [6099/21087] intraday_14635.csv.gz  in=286,085,482 out=42,180,859 elapsed=92.0s

  [6100/21087] intraday_14637.csv.gz  in=286,096,946 out=42,192,323 elapsed=92.1s

  [6101/21087] intraday_14636.csv.gz  in=286,108,672 out=42,204,049 elapsed=92.1s

  [6102/21087] intraday_14638.csv.gz  in=286,118,445 out=42,213,822 elapsed=92.1s

  [6103/21087] intraday_14639.csv.gz  in=286,131,692 out=42,227,069 elapsed=92.1s

  [6104/21087] intraday_1464.csv.gz  in=286,148,386 out=42,227,069 elapsed=92.1s

  [6105/21087] intraday_14640.csv.gz  in=286,159,431 out=42,238,114 elapsed=92.1s

  [6106/21087] intraday_14641.csv.gz  in=286,170,395 out=42,249,078 elapsed=92.1s

  [6107/21087] intraday_14642.csv.gz  in=286,183,978 out=42,262,661 elapsed=92.1s

  [6108/21087] intraday_14643.csv.gz  in=286,197,828 out=42,276,511 elapsed=92.1s

  [6109/21087] intraday_14644.csv.gz  in=286,209,029 out=42,287,712 elapsed=92.1s

  [6110/21087] intraday_14645.csv.gz  in=286,220,389 out=42,299,072 elapsed=92.1s

  [6111/21087] intraday_14646.csv.gz  in=286,232,626 out=42,311,309 elapsed=92.1s

  [6112/21087] intraday_14647.csv.gz  in=286,243,942 out=42,322,625 elapsed=92.1s

  [6113/21087] intraday_1465.csv.gz  in=286,257,275 out=42,322,625 elapsed=92.2s

  [6114/21087] intraday_14648.csv.gz  in=286,270,901 out=42,336,251 elapsed=92.2s

  [6115/21087] intraday_14649.csv.gz  in=286,284,667 out=42,350,017 elapsed=92.2s

  [6116/21087] intraday_14650.csv.gz  in=286,301,990 out=42,367,340 elapsed=92.2s

  [6117/21087] intraday_14654.csv.gz  in=286,314,275 out=42,379,625 elapsed=92.2s

  [6118/21087] intraday_14651.csv.gz  in=286,326,066 out=42,391,416 elapsed=92.2s

  [6119/21087] intraday_14652.csv.gz  in=286,340,345 out=42,405,695 elapsed=92.2s

  [6120/21087] intraday_14653.csv.gz  in=286,350,543 out=42,415,893 elapsed=92.2s

  [6121/21087] intraday_14655.csv.gz  in=286,361,206 out=42,426,556 elapsed=92.3s

  [6122/21087] intraday_14657.csv.gz  in=286,371,471 out=42,436,821 elapsed=92.3s

  [6123/21087] intraday_14656.csv.gz  in=286,383,324 out=42,448,561 elapsed=92.3s

  [6124/21087] intraday_14658.csv.gz  in=286,395,499 out=42,460,736 elapsed=92.3s

  [6125/21087] intraday_1466.csv.gz  in=286,409,848 out=42,460,736 elapsed=92.3s

  [6126/21087] intraday_14659.csv.gz  in=286,420,668 out=42,471,556 elapsed=92.3s

  [6127/21087] intraday_14661.csv.gz  in=286,429,697 out=42,480,585 elapsed=92.3s

  [6128/21087] intraday_14660.csv.gz  in=286,443,777 out=42,494,665 elapsed=92.3s

  [6129/21087] intraday_14663.csv.gz  in=286,454,498 out=42,505,386 elapsed=92.3s

  [6130/21087] intraday_14662.csv.gz  in=286,464,880 out=42,515,768 elapsed=92.3s

  [6131/21087] intraday_14664.csv.gz  in=286,478,052 out=42,528,940 elapsed=92.4s

  [6132/21087] intraday_14665.csv.gz  in=286,490,846 out=42,540,983 elapsed=92.4s

  [6133/21087] intraday_14666.csv.gz  in=286,503,991 out=42,554,128 elapsed=92.4s

  [6134/21087] intraday_14667.csv.gz  in=286,517,087 out=42,567,224 elapsed=92.4s

  [6135/21087] intraday_14668.csv.gz  in=286,530,780 out=42,580,917 elapsed=92.4s

  [6136/21087] intraday_14669.csv.gz  in=286,543,294 out=42,593,431 elapsed=92.4s

  [6137/21087] intraday_14670.csv.gz  in=286,554,894 out=42,605,031 elapsed=92.4s

  [6138/21087] intraday_1467.csv.gz  in=286,570,212 out=42,605,031 elapsed=92.4s

  [6139/21087] intraday_14672.csv.gz  in=286,582,576 out=42,617,395 elapsed=92.5s

  [6140/21087] intraday_14673.csv.gz  in=286,592,677 out=42,627,496 elapsed=92.5s

  [6141/21087] intraday_14671.csv.gz  in=286,604,831 out=42,639,650 elapsed=92.5s

  [6142/21087] intraday_14674.csv.gz  in=286,620,019 out=42,654,838 elapsed=92.5s

  [6143/21087] intraday_14675.csv.gz  in=286,630,706 out=42,665,525 elapsed=92.5s

  [6144/21087] intraday_14678.csv.gz  in=286,630,938 out=42,665,757 elapsed=92.5s

  [6145/21087] intraday_14676.csv.gz  in=286,639,651 out=42,674,470 elapsed=92.5s

  [6146/21087] intraday_14677.csv.gz  in=286,651,773 out=42,686,592 elapsed=92.5s

  [6147/21087] intraday_14679.csv.gz  in=286,652,674 out=42,687,493 elapsed=92.5s

  [6148/21087] intraday_14680.csv.gz  in=286,652,827 out=42,687,646 elapsed=92.5s

  [6149/21087] intraday_14681.csv.gz  in=286,653,345 out=42,688,164 elapsed=92.5s

  [6150/21087] intraday_14682.csv.gz  in=286,653,613 out=42,688,432 elapsed=92.5s

  [6151/21087] intraday_14683.csv.gz  in=286,654,004 out=42,688,823 elapsed=92.5s

  [6152/21087] intraday_1468.csv.gz  in=286,669,875 out=42,688,823 elapsed=92.5s

  [6153/21087] intraday_14684.csv.gz  in=286,670,431 out=42,689,379 elapsed=92.5s

  [6154/21087] intraday_14685.csv.gz  in=286,671,003 out=42,689,951 elapsed=92.5s

  [6155/21087] intraday_14686.csv.gz  in=286,671,226 out=42,690,174 elapsed=92.5s

  [6156/21087] intraday_14688.csv.gz  in=286,671,450 out=42,690,398 elapsed=92.5s

  [6157/21087] intraday_14687.csv.gz  in=286,671,810 out=42,690,758 elapsed=92.5s

  [6158/21087] intraday_14689.csv.gz  in=286,672,640 out=42,691,588 elapsed=92.6s

  [6159/21087] intraday_14691.csv.gz  in=286,673,068 out=42,692,016 elapsed=92.6s

  [6160/21087] intraday_14690.csv.gz  in=286,673,448 out=42,692,396 elapsed=92.6s

  [6161/21087] intraday_1469.csv.gz  in=286,688,045 out=42,692,396 elapsed=92.6s

  [6162/21087] intraday_14694.csv.gz  in=286,688,183 out=42,692,534 elapsed=92.6s

  [6163/21087] intraday_14693.csv.gz  in=286,688,551 out=42,692,902 elapsed=92.6s

  [6164/21087] intraday_14692.csv.gz  in=286,689,185 out=42,693,536 elapsed=92.6s

  [6165/21087] intraday_14695.csv.gz  in=286,689,935 out=42,694,286 elapsed=92.6s

  [6166/21087] intraday_14696.csv.gz  in=286,690,470 out=42,694,821 elapsed=92.6s

  [6167/21087] intraday_14697.csv.gz  in=286,690,714 out=42,695,065 elapsed=92.6s

  [6168/21087] intraday_14698.csv.gz  in=286,691,042 out=42,695,393 elapsed=92.6s

  [6169/21087] intraday_14699.csv.gz  in=286,691,613 out=42,695,964 elapsed=92.6s

  [6170/21087] intraday_14700.csv.gz  in=286,691,745 out=42,696,096 elapsed=92.6s

  [6171/21087] intraday_14701.csv.gz  in=286,692,177 out=42,696,528 elapsed=92.6s

  [6172/21087] intraday_1470.csv.gz  in=286,706,026 out=42,696,528 elapsed=92.6s

  [6173/21087] intraday_14704.csv.gz  in=286,706,334 out=42,696,836 elapsed=92.6s

  [6174/21087] intraday_14702.csv.gz  in=286,706,593 out=42,697,095 elapsed=92.6s

  [6175/21087] intraday_14703.csv.gz  in=286,706,950 out=42,697,452 elapsed=92.6s

  [6176/21087] intraday_14705.csv.gz  in=286,707,264 out=42,697,766 elapsed=92.6s

  [6177/21087] intraday_14706.csv.gz  in=286,707,319 out=42,697,821 elapsed=92.6s

  [6178/21087] intraday_14707.csv.gz  in=286,707,975 out=42,698,477 elapsed=92.6s

  [6179/21087] intraday_14708.csv.gz  in=286,708,577 out=42,699,079 elapsed=92.6s

  [6180/21087] intraday_14709.csv.gz  in=286,709,505 out=42,700,007 elapsed=92.6s

  [6181/21087] intraday_14710.csv.gz  in=286,709,801 out=42,700,303 elapsed=92.7s

  [6182/21087] intraday_14711.csv.gz  in=286,709,994 out=42,700,496 elapsed=92.7s

  [6183/21087] intraday_14712.csv.gz  in=286,710,341 out=42,700,843 elapsed=92.7s

  [6184/21087] intraday_14713.csv.gz  in=286,710,532 out=42,701,034 elapsed=92.7s

  [6185/21087] intraday_1471.csv.gz  in=286,724,380 out=42,701,034 elapsed=92.7s

  [6186/21087] intraday_14714.csv.gz  in=286,724,691 out=42,701,345 elapsed=92.7s

  [6187/21087] intraday_14715.csv.gz  in=286,725,046 out=42,701,700 elapsed=92.7s

  [6188/21087] intraday_14716.csv.gz  in=286,725,402 out=42,702,056 elapsed=92.7s

  [6189/21087] intraday_14717.csv.gz  in=286,725,553 out=42,702,207 elapsed=92.7s

  [6190/21087] intraday_14718.csv.gz  in=286,725,617 out=42,702,271 elapsed=92.7s

  [6191/21087] intraday_14719.csv.gz  in=286,725,683 out=42,702,337 elapsed=92.7s

  [6192/21087] intraday_14720.csv.gz  in=286,726,001 out=42,702,655 elapsed=92.7s

  [6193/21087] intraday_14721.csv.gz  in=286,726,621 out=42,703,275 elapsed=92.7s

  [6194/21087] intraday_14722.csv.gz  in=286,726,684 out=42,703,338 elapsed=92.7s

  [6195/21087] intraday_1472.csv.gz  in=286,739,999 out=42,703,338 elapsed=92.7s

  [6196/21087] intraday_14723.csv.gz  in=286,740,360 out=42,703,699 elapsed=92.7s

  [6197/21087] intraday_14724.csv.gz  in=286,740,524 out=42,703,863 elapsed=92.7s

  [6198/21087] intraday_14725.csv.gz  in=286,740,847 out=42,704,186 elapsed=92.7s

  [6199/21087] intraday_14726.csv.gz  in=286,741,037 out=42,704,376 elapsed=92.7s

  [6200/21087] intraday_14727.csv.gz  in=286,741,386 out=42,704,725 elapsed=92.7s

  [6201/21087] intraday_14728.csv.gz  in=286,741,532 out=42,704,871 elapsed=92.7s

  [6202/21087] intraday_14729.csv.gz  in=286,741,661 out=42,705,000 elapsed=92.7s

  [6203/21087] intraday_14731.csv.gz  in=286,742,351 out=42,705,690 elapsed=92.8s

  [6204/21087] intraday_14730.csv.gz  in=286,743,137 out=42,706,476 elapsed=92.8s

  [6205/21087] intraday_14732.csv.gz  in=286,743,521 out=42,706,860 elapsed=92.8s

  [6206/21087] intraday_1473.csv.gz  in=286,755,168 out=42,706,860 elapsed=92.8s

  [6207/21087] intraday_14733.csv.gz  in=286,755,902 out=42,707,594 elapsed=92.8s

  [6208/21087] intraday_14734.csv.gz  in=286,756,040 out=42,707,732 elapsed=92.8s

  [6209/21087] intraday_14735.csv.gz  in=286,756,161 out=42,707,853 elapsed=92.8s

  [6210/21087] intraday_14736.csv.gz  in=286,756,350 out=42,708,042 elapsed=92.8s

  [6211/21087] intraday_14738.csv.gz  in=286,756,542 out=42,708,234 elapsed=92.8s

  [6212/21087] intraday_14737.csv.gz  in=286,756,908 out=42,708,600 elapsed=92.8s

  [6213/21087] intraday_14739.csv.gz  in=286,757,069 out=42,708,761 elapsed=92.8s

  [6214/21087] intraday_14740.csv.gz  in=286,757,538 out=42,709,230 elapsed=92.8s

  [6215/21087] intraday_14741.csv.gz  in=286,757,641 out=42,709,333 elapsed=92.8s

  [6216/21087] intraday_14742.csv.gz  in=286,757,676 out=42,709,368 elapsed=92.8s

  [6217/21087] intraday_1474.csv.gz  in=286,770,192 out=42,709,368 elapsed=92.8s

  [6218/21087] intraday_14743.csv.gz  in=286,770,824 out=42,710,000 elapsed=92.8s

  [6219/21087] intraday_14744.csv.gz  in=286,771,753 out=42,710,929 elapsed=92.8s

  [6220/21087] intraday_14745.csv.gz  in=286,771,835 out=42,711,011 elapsed=92.8s

  [6221/21087] intraday_14746.csv.gz  in=286,772,036 out=42,711,212 elapsed=92.8s

  [6222/21087] intraday_14747.csv.gz  in=286,772,544 out=42,711,720 elapsed=92.8s

  [6223/21087] intraday_14749.csv.gz  in=286,772,832 out=42,712,008 elapsed=92.8s

  [6224/21087] intraday_14748.csv.gz  in=286,773,449 out=42,712,625 elapsed=92.8s

  [6225/21087] intraday_14750.csv.gz  in=286,773,992 out=42,713,168 elapsed=92.8s

  [6226/21087] intraday_14751.csv.gz  in=286,774,205 out=42,713,381 elapsed=92.9s

  [6227/21087] intraday_14752.csv.gz  in=286,774,404 out=42,713,580 elapsed=92.9s

  [6228/21087] intraday_1475.csv.gz  in=286,788,578 out=42,713,580 elapsed=92.9s

  [6229/21087] intraday_14754.csv.gz  in=286,788,771 out=42,713,773 elapsed=92.9s

  [6230/21087] intraday_14755.csv.gz  in=286,789,063 out=42,714,065 elapsed=92.9s

  [6231/21087] intraday_14753.csv.gz  in=286,789,786 out=42,714,788 elapsed=92.9s

  [6232/21087] intraday_14756.csv.gz  in=286,790,141 out=42,715,143 elapsed=92.9s

  [6233/21087] intraday_14757.csv.gz  in=286,790,331 out=42,715,333 elapsed=92.9s

  [6234/21087] intraday_14759.csv.gz  in=286,790,431 out=42,715,433 elapsed=92.9s

  [6235/21087] intraday_14758.csv.gz  in=286,790,740 out=42,715,742 elapsed=92.9s

  [6236/21087] intraday_14760.csv.gz  in=286,791,126 out=42,716,128 elapsed=92.9s

  [6237/21087] intraday_14761.csv.gz  in=286,791,833 out=42,716,835 elapsed=92.9s

  [6238/21087] intraday_14762.csv.gz  in=286,792,998 out=42,718,000 elapsed=92.9s

  [6239/21087] intraday_1476.csv.gz  in=286,805,781 out=42,718,000 elapsed=92.9s

  [6240/21087] intraday_14763.csv.gz  in=286,806,792 out=42,719,011 elapsed=92.9s

  [6241/21087] intraday_14764.csv.gz  in=286,807,679 out=42,719,898 elapsed=92.9s

  [6242/21087] intraday_14766.csv.gz  in=286,808,298 out=42,720,517 elapsed=92.9s

  [6243/21087] intraday_14765.csv.gz  in=286,808,782 out=42,721,001 elapsed=92.9s

  [6244/21087] intraday_14767.csv.gz  in=286,808,915 out=42,721,134 elapsed=92.9s

  [6245/21087] intraday_14768.csv.gz  in=286,810,044 out=42,722,263 elapsed=92.9s

  [6246/21087] intraday_14769.csv.gz  in=286,810,215 out=42,722,414 elapsed=92.9s

  [6247/21087] intraday_14770.csv.gz  in=286,810,521 out=42,722,720 elapsed=92.9s

  [6248/21087] intraday_14771.csv.gz  in=286,810,884 out=42,723,083 elapsed=93.0s

  [6249/21087] intraday_1477.csv.gz  in=286,824,899 out=42,723,083 elapsed=93.0s

  [6250/21087] intraday_14772.csv.gz  in=286,825,232 out=42,723,416 elapsed=93.0s

  [6251/21087] intraday_14774.csv.gz  in=286,825,441 out=42,723,625 elapsed=93.0s

  [6252/21087] intraday_14775.csv.gz  in=286,825,724 out=42,723,908 elapsed=93.0s

  [6253/21087] intraday_14776.csv.gz  in=286,825,984 out=42,724,168 elapsed=93.0s

  [6254/21087] intraday_14773.csv.gz  in=286,831,544 out=42,726,636 elapsed=93.0s

  [6255/21087] intraday_14777.csv.gz  in=286,832,095 out=42,727,187 elapsed=93.0s

  [6256/21087] intraday_14778.csv.gz  in=286,832,339 out=42,727,431 elapsed=93.0s

  [6257/21087] intraday_14779.csv.gz  in=286,832,856 out=42,727,948 elapsed=93.0s

  [6258/21087] intraday_14780.csv.gz  in=286,833,293 out=42,728,385 elapsed=93.0s

  [6259/21087] intraday_14781.csv.gz  in=286,834,615 out=42,729,707 elapsed=93.0s

  [6260/21087] intraday_1478.csv.gz  in=286,847,151 out=42,729,707 elapsed=93.0s

  [6261/21087] intraday_14782.csv.gz  in=286,848,332 out=42,730,367 elapsed=93.0s

  [6262/21087] intraday_14783.csv.gz  in=286,848,782 out=42,730,817 elapsed=93.0s

  [6263/21087] intraday_14784.csv.gz  in=286,848,999 out=42,731,034 elapsed=93.0s

  [6264/21087] intraday_14785.csv.gz  in=286,849,750 out=42,731,785 elapsed=93.0s

  [6265/21087] intraday_14786.csv.gz  in=286,849,850 out=42,731,885 elapsed=93.0s

  [6266/21087] intraday_14787.csv.gz  in=286,850,245 out=42,732,280 elapsed=93.0s

  [6267/21087] intraday_14788.csv.gz  in=286,850,493 out=42,732,528 elapsed=93.0s

  [6268/21087] intraday_14789.csv.gz  in=286,850,929 out=42,732,964 elapsed=93.0s

  [6269/21087] intraday_14790.csv.gz  in=286,851,270 out=42,733,305 elapsed=93.1s

  [6270/21087] intraday_14791.csv.gz  in=286,851,590 out=42,733,625 elapsed=93.1s

  [6271/21087] intraday_14792.csv.gz  in=286,852,547 out=42,734,582 elapsed=93.1s

  [6272/21087] intraday_1479.csv.gz  in=286,865,505 out=42,734,582 elapsed=93.1s

  [6273/21087] intraday_14793.csv.gz  in=286,866,210 out=42,735,287 elapsed=93.1s

  [6274/21087] intraday_14794.csv.gz  in=286,867,410 out=42,736,487 elapsed=93.1s

  [6275/21087] intraday_14795.csv.gz  in=286,868,651 out=42,737,728 elapsed=93.1s

  [6276/21087] intraday_14796.csv.gz  in=286,869,404 out=42,738,481 elapsed=93.1s

  [6277/21087] intraday_14797.csv.gz  in=286,870,418 out=42,739,495 elapsed=93.1s

  [6278/21087] intraday_14798.csv.gz  in=286,870,633 out=42,739,710 elapsed=93.1s

  [6279/21087] intraday_14799.csv.gz  in=286,871,001 out=42,740,078 elapsed=93.1s

  [6280/21087] intraday_14800.csv.gz  in=286,871,201 out=42,740,278 elapsed=93.1s

  [6281/21087] intraday_14801.csv.gz  in=286,871,375 out=42,740,452 elapsed=93.1s

  [6282/21087] intraday_14802.csv.gz  in=286,871,860 out=42,740,937 elapsed=93.1s

  [6283/21087] intraday_1480.csv.gz  in=286,885,263 out=42,740,937 elapsed=93.1s

  [6284/21087] intraday_14803.csv.gz  in=286,885,541 out=42,741,215 elapsed=93.1s

  [6285/21087] intraday_14804.csv.gz  in=286,885,945 out=42,741,619 elapsed=93.2s

  [6286/21087] intraday_14805.csv.gz  in=286,886,412 out=42,742,086 elapsed=93.2s

  [6287/21087] intraday_14806.csv.gz  in=286,887,059 out=42,742,733 elapsed=93.2s

  [6288/21087] intraday_14807.csv.gz  in=286,887,355 out=42,743,029 elapsed=93.2s

  [6289/21087] intraday_14808.csv.gz  in=286,887,815 out=42,743,489 elapsed=93.2s

  [6290/21087] intraday_14809.csv.gz  in=286,888,188 out=42,743,862 elapsed=93.2s

  [6291/21087] intraday_14810.csv.gz  in=286,888,945 out=42,744,619 elapsed=93.2s

  [6292/21087] intraday_14811.csv.gz  in=286,889,256 out=42,744,930 elapsed=93.2s

  [6293/21087] intraday_14812.csv.gz  in=286,889,510 out=42,745,184 elapsed=93.2s

  [6294/21087] intraday_1481.csv.gz  in=286,902,508 out=42,745,184 elapsed=93.2s

  [6295/21087] intraday_14814.csv.gz  in=286,902,843 out=42,745,519 elapsed=93.2s

  [6296/21087] intraday_14815.csv.gz  in=286,903,068 out=42,745,744 elapsed=93.2s

  [6297/21087] intraday_14813.csv.gz  in=286,903,595 out=42,746,271 elapsed=93.2s

  [6298/21087] intraday_14816.csv.gz  in=286,904,425 out=42,747,101 elapsed=93.2s

  [6299/21087] intraday_14817.csv.gz  in=286,904,759 out=42,747,435 elapsed=93.2s

  [6300/21087] intraday_14818.csv.gz  in=286,904,955 out=42,747,631 elapsed=93.2s

  [6301/21087] intraday_14819.csv.gz  in=286,905,516 out=42,748,192 elapsed=93.2s

  [6302/21087] intraday_14820.csv.gz  in=286,906,094 out=42,748,770 elapsed=93.2s

  [6303/21087] intraday_1482.csv.gz  in=286,920,477 out=42,748,770 elapsed=93.2s

  [6304/21087] intraday_14821.csv.gz  in=286,921,009 out=42,749,302 elapsed=93.2s

  [6305/21087] intraday_14822.csv.gz  in=286,921,281 out=42,749,574 elapsed=93.2s

  [6306/21087] intraday_14823.csv.gz  in=286,921,335 out=42,749,628 elapsed=93.2s

  [6307/21087] intraday_14825.csv.gz  in=286,932,362 out=42,760,655 elapsed=93.3s

  [6308/21087] intraday_14827.csv.gz  in=286,942,883 out=42,771,176 elapsed=93.3s

  [6309/21087] intraday_14826.csv.gz  in=286,956,667 out=42,784,960 elapsed=93.3s

  [6310/21087] intraday_14824.csv.gz  in=286,971,628 out=42,799,921 elapsed=93.3s

  [6311/21087] intraday_14828.csv.gz  in=286,983,703 out=42,811,996 elapsed=93.3s

  [6312/21087] intraday_1483.csv.gz  in=286,998,757 out=42,811,996 elapsed=93.3s

  [6313/21087] intraday_14829.csv.gz  in=287,011,371 out=42,824,610 elapsed=93.3s

  [6314/21087] intraday_14830.csv.gz  in=287,024,456 out=42,837,695 elapsed=93.3s

  [6315/21087] intraday_14831.csv.gz  in=287,035,869 out=42,849,108 elapsed=93.3s

  [6316/21087] intraday_14832.csv.gz  in=287,047,638 out=42,860,877 elapsed=93.3s

  [6317/21087] intraday_14833.csv.gz  in=287,059,833 out=42,873,072 elapsed=93.4s

  [6318/21087] intraday_14834.csv.gz  in=287,070,435 out=42,883,674 elapsed=93.4s

  [6319/21087] intraday_14835.csv.gz  in=287,081,838 out=42,895,077 elapsed=93.4s

  [6320/21087] intraday_14836.csv.gz  in=287,093,146 out=42,906,385 elapsed=93.4s

  [6321/21087] intraday_14837.csv.gz  in=287,106,011 out=42,919,250 elapsed=93.4s

  [6322/21087] intraday_14839.csv.gz  in=287,114,394 out=42,927,633 elapsed=93.4s

  [6323/21087] intraday_1484.csv.gz  in=287,128,979 out=42,927,633 elapsed=93.4s

  [6324/21087] intraday_14838.csv.gz  in=287,139,130 out=42,937,784 elapsed=93.4s

  [6325/21087] intraday_14840.csv.gz  in=287,153,534 out=42,952,188 elapsed=93.4s

  [6326/21087] intraday_14841.csv.gz  in=287,166,153 out=42,964,807 elapsed=93.5s

  [6327/21087] intraday_14842.csv.gz  in=287,178,102 out=42,976,756 elapsed=93.5s

  [6328/21087] intraday_14843.csv.gz  in=287,188,383 out=42,987,037 elapsed=93.5s

  [6329/21087] intraday_14844.csv.gz  in=287,201,625 out=43,000,279 elapsed=93.5s

  [6330/21087] intraday_14845.csv.gz  in=287,213,009 out=43,011,663 elapsed=93.5s

  [6331/21087] intraday_14846.csv.gz  in=287,225,644 out=43,024,298 elapsed=93.5s

  [6332/21087] intraday_14848.csv.gz  in=287,238,464 out=43,037,118 elapsed=93.5s

  [6333/21087] intraday_14847.csv.gz  in=287,250,350 out=43,049,004 elapsed=93.5s

  [6334/21087] intraday_14849.csv.gz  in=287,262,584 out=43,061,238 elapsed=93.5s

  [6335/21087] intraday_1485.csv.gz  in=287,276,322 out=43,061,238 elapsed=93.5s

  [6336/21087] intraday_14850.csv.gz  in=287,286,721 out=43,071,347 elapsed=93.5s

  [6337/21087] intraday_14851.csv.gz  in=287,298,233 out=43,082,859 elapsed=93.6s

  [6338/21087] intraday_14852.csv.gz  in=287,309,081 out=43,093,707 elapsed=93.6s

  [6339/21087] intraday_14853.csv.gz  in=287,322,768 out=43,107,394 elapsed=93.6s

  [6340/21087] intraday_14855.csv.gz  in=287,334,633 out=43,119,259 elapsed=93.6s

  [6341/21087] intraday_14854.csv.gz  in=287,350,163 out=43,134,789 elapsed=93.6s

  [6342/21087] intraday_14856.csv.gz  in=287,361,146 out=43,145,772 elapsed=93.6s

  [6343/21087] intraday_14857.csv.gz  in=287,373,169 out=43,157,795 elapsed=93.6s

  [6344/21087] intraday_14859.csv.gz  in=287,384,775 out=43,169,401 elapsed=93.6s

  [6345/21087] intraday_14858.csv.gz  in=287,397,095 out=43,181,721 elapsed=93.6s

  [6346/21087] intraday_1486.csv.gz  in=287,411,783 out=43,181,721 elapsed=93.6s

  [6347/21087] intraday_14860.csv.gz  in=287,424,394 out=43,194,332 elapsed=93.6s

  [6348/21087] intraday_14861.csv.gz  in=287,434,265 out=43,204,203 elapsed=93.7s

  [6349/21087] intraday_14862.csv.gz  in=287,446,148 out=43,216,086 elapsed=93.7s

  [6350/21087] intraday_14863.csv.gz  in=287,455,003 out=43,224,941 elapsed=93.7s

  [6351/21087] intraday_14864.csv.gz  in=287,466,465 out=43,236,403 elapsed=93.7s

  [6352/21087] intraday_14865.csv.gz  in=287,478,371 out=43,248,309 elapsed=93.7s

  [6353/21087] intraday_14866.csv.gz  in=287,492,063 out=43,262,001 elapsed=93.7s

  [6354/21087] intraday_14867.csv.gz  in=287,503,869 out=43,273,807 elapsed=93.7s

  [6355/21087] intraday_14868.csv.gz  in=287,517,116 out=43,287,054 elapsed=93.7s

  [6356/21087] intraday_14869.csv.gz  in=287,527,410 out=43,297,348 elapsed=93.7s

  [6357/21087] intraday_1487.csv.gz  in=287,540,376 out=43,297,348 elapsed=93.7s

  [6358/21087] intraday_14870.csv.gz  in=287,551,547 out=43,308,519 elapsed=93.7s

  [6359/21087] intraday_14871.csv.gz  in=287,564,668 out=43,321,640 elapsed=93.8s

  [6360/21087] intraday_14872.csv.gz  in=287,583,575 out=43,336,856 elapsed=93.8s

  [6361/21087] intraday_14873.csv.gz  in=287,594,397 out=43,347,678 elapsed=93.8s

  [6362/21087] intraday_14874.csv.gz  in=287,605,711 out=43,358,992 elapsed=93.8s

  [6363/21087] intraday_14875.csv.gz  in=287,615,838 out=43,369,119 elapsed=93.8s

  [6364/21087] intraday_14876.csv.gz  in=287,629,464 out=43,382,745 elapsed=93.8s

  [6365/21087] intraday_14877.csv.gz  in=287,642,288 out=43,395,569 elapsed=93.8s

  [6366/21087] intraday_1488.csv.gz  in=287,658,446 out=43,395,569 elapsed=93.8s

  [6367/21087] intraday_14878.csv.gz  in=287,669,789 out=43,406,912 elapsed=93.8s

  [6368/21087] intraday_14879.csv.gz  in=287,682,382 out=43,419,505 elapsed=93.8s

  [6369/21087] intraday_14880.csv.gz  in=287,692,978 out=43,430,101 elapsed=93.8s

  [6370/21087] intraday_14881.csv.gz  in=287,703,352 out=43,440,475 elapsed=93.9s

  [6371/21087] intraday_14882.csv.gz  in=287,713,773 out=43,450,896 elapsed=93.9s

  [6372/21087] intraday_14883.csv.gz  in=287,726,074 out=43,463,197 elapsed=93.9s

  [6373/21087] intraday_14884.csv.gz  in=287,737,003 out=43,474,126 elapsed=93.9s

  [6374/21087] intraday_14885.csv.gz  in=287,748,559 out=43,485,682 elapsed=93.9s

  [6375/21087] intraday_14887.csv.gz  in=287,759,357 out=43,496,480 elapsed=93.9s

  [6376/21087] intraday_14886.csv.gz  in=287,769,924 out=43,507,047 elapsed=93.9s

  [6377/21087] intraday_14888.csv.gz  in=287,779,786 out=43,516,909 elapsed=93.9s

  [6378/21087] intraday_14889.csv.gz  in=287,793,460 out=43,530,583 elapsed=93.9s

  [6379/21087] intraday_1489.csv.gz  in=287,805,877 out=43,530,583 elapsed=93.9s

  [6380/21087] intraday_14891.csv.gz  in=287,819,076 out=43,543,782 elapsed=94.0s

  [6381/21087] intraday_14890.csv.gz  in=287,830,982 out=43,555,688 elapsed=94.0s

  [6382/21087] intraday_14892.csv.gz  in=287,842,752 out=43,567,458 elapsed=94.0s

  [6383/21087] intraday_14893.csv.gz  in=287,853,851 out=43,578,557 elapsed=94.0s

  [6384/21087] intraday_14894.csv.gz  in=287,865,414 out=43,590,120 elapsed=94.0s

  [6385/21087] intraday_14896.csv.gz  in=287,876,901 out=43,601,607 elapsed=94.0s

  [6386/21087] intraday_14895.csv.gz  in=287,888,802 out=43,613,508 elapsed=94.0s

  [6387/21087] intraday_14897.csv.gz  in=287,900,282 out=43,624,988 elapsed=94.0s

  [6388/21087] intraday_14898.csv.gz  in=287,912,740 out=43,637,446 elapsed=94.0s

  [6389/21087] intraday_14899.csv.gz  in=287,922,493 out=43,647,199 elapsed=94.0s

  [6390/21087] intraday_14900.csv.gz  in=287,931,924 out=43,656,630 elapsed=94.1s

  [6391/21087] intraday_1490.csv.gz  in=287,946,337 out=43,656,630 elapsed=94.1s

  [6392/21087] intraday_14901.csv.gz  in=287,959,102 out=43,669,395 elapsed=94.1s

  [6393/21087] intraday_14902.csv.gz  in=287,969,738 out=43,680,031 elapsed=94.1s

  [6394/21087] intraday_14904.csv.gz  in=287,980,071 out=43,690,174 elapsed=94.1s

  [6395/21087] intraday_14903.csv.gz  in=287,992,152 out=43,702,255 elapsed=94.1s

  [6396/21087] intraday_14905.csv.gz  in=288,001,814 out=43,711,917 elapsed=94.1s

  [6397/21087] intraday_14906.csv.gz  in=288,014,413 out=43,724,516 elapsed=94.1s

  [6398/21087] intraday_14907.csv.gz  in=288,026,560 out=43,736,663 elapsed=94.2s

  [6399/21087] intraday_1491.csv.gz  in=288,043,032 out=43,736,663 elapsed=94.2s

  [6400/21087] intraday_14909.csv.gz  in=288,056,120 out=43,749,751 elapsed=94.2s

  [6401/21087] intraday_14908.csv.gz  in=288,072,631 out=43,766,262 elapsed=94.2s

  [6402/21087] intraday_14910.csv.gz  in=288,085,463 out=43,779,094 elapsed=94.2s

  [6403/21087] intraday_14911.csv.gz  in=288,096,039 out=43,789,670 elapsed=94.2s

  [6404/21087] intraday_14912.csv.gz  in=288,107,678 out=43,801,309 elapsed=94.2s

  [6405/21087] intraday_14913.csv.gz  in=288,119,848 out=43,813,479 elapsed=94.2s

  [6406/21087] intraday_14914.csv.gz  in=288,131,845 out=43,825,476 elapsed=94.2s

  [6407/21087] intraday_14915.csv.gz  in=288,142,446 out=43,836,077 elapsed=94.2s

  [6408/21087] intraday_14917.csv.gz  in=288,152,617 out=43,846,248 elapsed=94.3s

  [6409/21087] intraday_14916.csv.gz  in=288,166,191 out=43,859,822 elapsed=94.3s

  [6410/21087] intraday_14918.csv.gz  in=288,176,476 out=43,870,107 elapsed=94.3s

  [6411/21087] intraday_14919.csv.gz  in=288,190,283 out=43,883,914 elapsed=94.3s

  [6412/21087] intraday_1492.csv.gz  in=288,203,948 out=43,883,914 elapsed=94.3s

  [6413/21087] intraday_14920.csv.gz  in=288,215,953 out=43,895,919 elapsed=94.3s

  [6414/21087] intraday_14921.csv.gz  in=288,228,498 out=43,908,464 elapsed=94.3s

  [6415/21087] intraday_14922.csv.gz  in=288,239,330 out=43,919,296 elapsed=94.3s

  [6416/21087] intraday_14923.csv.gz  in=288,249,892 out=43,929,858 elapsed=94.3s

  [6417/21087] intraday_14924.csv.gz  in=288,261,502 out=43,941,468 elapsed=94.3s

  [6418/21087] intraday_14925.csv.gz  in=288,274,184 out=43,954,150 elapsed=94.3s

  [6419/21087] intraday_14926.csv.gz  in=288,287,206 out=43,967,172 elapsed=94.4s

  [6420/21087] intraday_14927.csv.gz  in=288,298,670 out=43,978,636 elapsed=94.4s

  [6421/21087] intraday_14928.csv.gz  in=288,309,765 out=43,989,731 elapsed=94.4s

  [6422/21087] intraday_14929.csv.gz  in=288,321,194 out=44,001,160 elapsed=94.4s

  [6423/21087] intraday_1493.csv.gz  in=288,335,228 out=44,001,160 elapsed=94.4s

  [6424/21087] intraday_14930.csv.gz  in=288,346,912 out=44,012,844 elapsed=94.4s

  [6425/21087] intraday_14932.csv.gz  in=288,357,378 out=44,023,310 elapsed=94.4s

  [6426/21087] intraday_14931.csv.gz  in=288,370,190 out=44,036,122 elapsed=94.4s

  [6427/21087] intraday_14933.csv.gz  in=288,383,947 out=44,049,879 elapsed=94.4s

  [6428/21087] intraday_14934.csv.gz  in=288,396,908 out=44,062,840 elapsed=94.4s

  [6429/21087] intraday_14935.csv.gz  in=288,408,739 out=44,074,671 elapsed=94.5s

  [6430/21087] intraday_14936.csv.gz  in=288,420,208 out=44,086,140 elapsed=94.5s

  [6431/21087] intraday_14937.csv.gz  in=288,432,651 out=44,098,583 elapsed=94.5s

  [6432/21087] intraday_14938.csv.gz  in=288,445,570 out=44,111,502 elapsed=94.5s

  [6433/21087] intraday_1494.csv.gz  in=288,461,237 out=44,111,502 elapsed=94.5s

  [6434/21087] intraday_14939.csv.gz  in=288,473,628 out=44,123,893 elapsed=94.5s

  [6435/21087] intraday_14940.csv.gz  in=288,487,158 out=44,137,423 elapsed=94.5s

  [6436/21087] intraday_14941.csv.gz  in=288,504,067 out=44,154,332 elapsed=94.5s

  [6437/21087] intraday_14942.csv.gz  in=288,516,721 out=44,166,986 elapsed=94.6s

  [6438/21087] intraday_14943.csv.gz  in=288,532,953 out=44,183,218 elapsed=94.6s

  [6439/21087] intraday_14944.csv.gz  in=288,543,116 out=44,193,381 elapsed=94.6s

  [6440/21087] intraday_14945.csv.gz  in=288,555,812 out=44,206,077 elapsed=94.6s

  [6441/21087] intraday_14946.csv.gz  in=288,566,611 out=44,216,876 elapsed=94.6s

  [6442/21087] intraday_14947.csv.gz  in=288,578,723 out=44,228,988 elapsed=94.6s

  [6443/21087] intraday_1495.csv.gz  in=288,589,899 out=44,228,988 elapsed=94.6s

  [6444/21087] intraday_14948.csv.gz  in=288,600,843 out=44,239,932 elapsed=94.6s

  [6445/21087] intraday_14949.csv.gz  in=288,613,095 out=44,252,184 elapsed=94.6s

  [6446/21087] intraday_14952.csv.gz  in=288,622,589 out=44,261,678 elapsed=94.6s

  [6447/21087] intraday_14950.csv.gz  in=288,633,803 out=44,272,892 elapsed=94.7s

  [6448/21087] intraday_14951.csv.gz  in=288,650,609 out=44,289,698 elapsed=94.7s

  [6449/21087] intraday_14953.csv.gz  in=288,661,213 out=44,300,302 elapsed=94.7s

  [6450/21087] intraday_14955.csv.gz  in=288,672,244 out=44,311,333 elapsed=94.7s

  [6451/21087] intraday_14957.csv.gz  in=288,685,232 out=44,324,321 elapsed=94.7s

  [6452/21087] intraday_14956.csv.gz  in=288,697,460 out=44,336,549 elapsed=94.7s

  [6453/21087] intraday_14954.csv.gz  in=288,709,357 out=44,348,446 elapsed=94.7s

  [6454/21087] intraday_14959.csv.gz  in=288,722,789 out=44,361,878 elapsed=94.7s

  [6455/21087] intraday_1496.csv.gz  in=288,735,178 out=44,361,878 elapsed=94.7s

  [6456/21087] intraday_14958.csv.gz  in=288,753,685 out=44,377,577 elapsed=94.8s

  [6457/21087] intraday_14960.csv.gz  in=288,769,669 out=44,392,113 elapsed=94.8s

  [6458/21087] intraday_14961.csv.gz  in=288,782,306 out=44,404,750 elapsed=94.8s

  [6459/21087] intraday_14962.csv.gz  in=288,796,014 out=44,418,458 elapsed=94.8s

  [6460/21087] intraday_14963.csv.gz  in=288,808,504 out=44,430,948 elapsed=94.8s

  [6461/21087] intraday_14964.csv.gz  in=288,819,021 out=44,441,465 elapsed=94.8s

  [6462/21087] intraday_14965.csv.gz  in=288,830,974 out=44,453,418 elapsed=94.8s

  [6463/21087] intraday_14966.csv.gz  in=288,841,051 out=44,463,495 elapsed=94.8s

  [6464/21087] intraday_14967.csv.gz  in=288,849,474 out=44,471,918 elapsed=94.8s

  [6465/21087] intraday_14969.csv.gz  in=288,850,752 out=44,473,196 elapsed=94.8s

  [6466/21087] intraday_14968.csv.gz  in=288,863,838 out=44,486,282 elapsed=94.8s

  [6467/21087] intraday_14970.csv.gz  in=288,878,574 out=44,501,018 elapsed=94.9s

  [6468/21087] intraday_14971.csv.gz  in=288,890,492 out=44,512,936 elapsed=94.9s

  [6469/21087] intraday_1497.csv.gz  in=288,915,086 out=44,512,936 elapsed=94.9s

  [6470/21087] intraday_14972.csv.gz  in=288,927,580 out=44,525,430 elapsed=94.9s

  [6471/21087] intraday_14974.csv.gz  in=288,938,672 out=44,536,522 elapsed=94.9s

  [6472/21087] intraday_14975.csv.gz  in=288,954,029 out=44,551,879 elapsed=94.9s

  [6473/21087] intraday_14973.csv.gz  in=288,966,076 out=44,563,926 elapsed=94.9s

  [6474/21087] intraday_14976.csv.gz  in=288,978,773 out=44,576,623 elapsed=94.9s

  [6475/21087] intraday_14977.csv.gz  in=288,990,156 out=44,588,006 elapsed=94.9s

  [6476/21087] intraday_1498.csv.gz  in=289,005,434 out=44,588,006 elapsed=95.0s

  [6477/21087] intraday_14978.csv.gz  in=289,017,954 out=44,600,526 elapsed=95.0s

  [6478/21087] intraday_14979.csv.gz  in=289,030,210 out=44,612,782 elapsed=95.0s

  [6479/21087] intraday_14980.csv.gz  in=289,041,204 out=44,623,776 elapsed=95.0s

  [6480/21087] intraday_14981.csv.gz  in=289,053,992 out=44,636,564 elapsed=95.0s

  [6481/21087] intraday_14982.csv.gz  in=289,066,165 out=44,648,737 elapsed=95.0s

  [6482/21087] intraday_14984.csv.gz  in=289,077,298 out=44,659,870 elapsed=95.0s

  [6483/21087] intraday_14985.csv.gz  in=289,086,686 out=44,669,258 elapsed=95.0s

  [6484/21087] intraday_14983.csv.gz  in=289,099,698 out=44,682,270 elapsed=95.0s

  [6485/21087] intraday_14986.csv.gz  in=289,115,354 out=44,697,926 elapsed=95.0s

  [6486/21087] intraday_14987.csv.gz  in=289,128,797 out=44,711,369 elapsed=95.1s

  [6487/21087] intraday_14988.csv.gz  in=289,139,710 out=44,722,282 elapsed=95.1s

  [6488/21087] intraday_1499.csv.gz  in=289,155,883 out=44,722,282 elapsed=95.1s

  [6489/21087] intraday_14989.csv.gz  in=289,166,913 out=44,733,312 elapsed=95.1s

  [6490/21087] intraday_14990.csv.gz  in=289,180,609 out=44,747,008 elapsed=95.1s

  [6491/21087] intraday_14993.csv.gz  in=289,192,854 out=44,759,253 elapsed=95.1s

  [6492/21087] intraday_14991.csv.gz  in=289,204,865 out=44,771,264 elapsed=95.1s

  [6493/21087] intraday_14992.csv.gz  in=289,217,978 out=44,784,377 elapsed=95.1s

  [6494/21087] intraday_14994.csv.gz  in=289,230,612 out=44,797,011 elapsed=95.1s

  [6495/21087] intraday_14995.csv.gz  in=289,241,329 out=44,807,728 elapsed=95.1s

  [6496/21087] intraday_14996.csv.gz  in=289,253,070 out=44,819,469 elapsed=95.2s

  [6497/21087] intraday_14998.csv.gz  in=289,265,411 out=44,831,810 elapsed=95.2s

  [6498/21087] intraday_14997.csv.gz  in=289,276,968 out=44,843,367 elapsed=95.2s

  [6499/21087] intraday_1500.csv.gz  in=289,291,828 out=44,843,367 elapsed=95.2s

  [6500/21087] intraday_14999.csv.gz  in=289,304,598 out=44,856,137 elapsed=95.2s

  [6501/21087] intraday_15002.csv.gz  in=289,315,108 out=44,866,647 elapsed=95.2s

  [6502/21087] intraday_15001.csv.gz  in=289,328,284 out=44,879,823 elapsed=95.2s

  [6503/21087] intraday_15000.csv.gz  in=289,344,404 out=44,895,943 elapsed=95.2s

  [6504/21087] intraday_15003.csv.gz  in=289,357,877 out=44,909,416 elapsed=95.3s

  [6505/21087] intraday_15004.csv.gz  in=289,371,081 out=44,922,620 elapsed=95.3s

  [6506/21087] intraday_15005.csv.gz  in=289,383,442 out=44,934,981 elapsed=95.3s

  [6507/21087] intraday_15006.csv.gz  in=289,396,603 out=44,948,142 elapsed=95.3s

  [6508/21087] intraday_15007.csv.gz  in=289,405,918 out=44,957,457 elapsed=95.3s

  [6509/21087] intraday_15008.csv.gz  in=289,417,980 out=44,969,519 elapsed=95.3s

  [6510/21087] intraday_1501.csv.gz  in=289,433,066 out=44,969,519 elapsed=95.3s

  [6511/21087] intraday_15009.csv.gz  in=289,442,595 out=44,979,048 elapsed=95.3s

  [6512/21087] intraday_15010.csv.gz  in=289,454,481 out=44,990,934 elapsed=95.3s

  [6513/21087] intraday_15011.csv.gz  in=289,466,304 out=45,002,757 elapsed=95.3s

  [6514/21087] intraday_15012.csv.gz  in=289,481,462 out=45,017,915 elapsed=95.4s

  [6515/21087] intraday_15013.csv.gz  in=289,493,038 out=45,029,491 elapsed=95.4s

  [6516/21087] intraday_15015.csv.gz  in=289,503,585 out=45,040,038 elapsed=95.4s

  [6517/21087] intraday_15014.csv.gz  in=289,517,790 out=45,054,243 elapsed=95.4s

  [6518/21087] intraday_15016.csv.gz  in=289,528,841 out=45,065,294 elapsed=95.4s

  [6519/21087] intraday_15019.csv.gz  in=289,540,756 out=45,077,209 elapsed=95.4s

  [6520/21087] intraday_15017.csv.gz  in=289,553,484 out=45,089,937 elapsed=95.4s

  [6521/21087] intraday_1502.csv.gz  in=289,568,588 out=45,089,937 elapsed=95.4s

  [6522/21087] intraday_15018.csv.gz  in=289,581,263 out=45,102,612 elapsed=95.4s

  [6523/21087] intraday_15020.csv.gz  in=289,592,181 out=45,113,530 elapsed=95.5s

  [6524/21087] intraday_15022.csv.gz  in=289,604,263 out=45,125,612 elapsed=95.5s

  [6525/21087] intraday_15021.csv.gz  in=289,617,439 out=45,138,788 elapsed=95.5s

  [6526/21087] intraday_15023.csv.gz  in=289,629,908 out=45,151,257 elapsed=95.5s

  [6527/21087] intraday_15024.csv.gz  in=289,642,575 out=45,163,924 elapsed=95.5s

  [6528/21087] intraday_15025.csv.gz  in=289,655,510 out=45,176,859 elapsed=95.5s

  [6529/21087] intraday_15027.csv.gz  in=289,664,858 out=45,186,207 elapsed=95.5s

  [6530/21087] intraday_15026.csv.gz  in=289,677,040 out=45,198,389 elapsed=95.5s

  [6531/21087] intraday_15028.csv.gz  in=289,690,362 out=45,211,711 elapsed=95.5s

  [6532/21087] intraday_1503.csv.gz  in=289,705,412 out=45,211,711 elapsed=95.5s

  [6533/21087] intraday_15029.csv.gz  in=289,739,170 out=45,233,672 elapsed=95.6s

  [6534/21087] intraday_15030.csv.gz  in=289,750,112 out=45,244,614 elapsed=95.6s

  [6535/21087] intraday_15031.csv.gz  in=289,762,448 out=45,256,950 elapsed=95.6s

  [6536/21087] intraday_15032.csv.gz  in=289,773,620 out=45,268,122 elapsed=95.6s

  [6537/21087] intraday_15033.csv.gz  in=289,783,766 out=45,278,268 elapsed=95.6s

  [6538/21087] intraday_15034.csv.gz  in=289,795,008 out=45,289,510 elapsed=95.6s

  [6539/21087] intraday_15035.csv.gz  in=289,808,418 out=45,302,920 elapsed=95.6s

  [6540/21087] intraday_15036.csv.gz  in=289,821,104 out=45,315,606 elapsed=95.6s

  [6541/21087] intraday_15037.csv.gz  in=289,834,343 out=45,328,845 elapsed=95.6s

  [6542/21087] intraday_15038.csv.gz  in=289,847,190 out=45,341,692 elapsed=95.6s

  [6543/21087] intraday_15039.csv.gz  in=289,857,869 out=45,352,371 elapsed=95.6s

  [6544/21087] intraday_1504.csv.gz  in=289,871,840 out=45,352,371 elapsed=95.7s

  [6545/21087] intraday_15041.csv.gz  in=289,885,523 out=45,366,054 elapsed=95.7s

  [6546/21087] intraday_15040.csv.gz  in=289,896,124 out=45,376,655 elapsed=95.7s

  [6547/21087] intraday_15042.csv.gz  in=289,906,851 out=45,387,382 elapsed=95.7s

  [6548/21087] intraday_15043.csv.gz  in=289,920,474 out=45,401,005 elapsed=95.7s

  [6549/21087] intraday_15045.csv.gz  in=289,930,178 out=45,410,709 elapsed=95.7s

  [6550/21087] intraday_15044.csv.gz  in=289,941,572 out=45,422,103 elapsed=95.7s

  [6551/21087] intraday_15046.csv.gz  in=289,951,728 out=45,432,259 elapsed=95.7s

  [6552/21087] intraday_15047.csv.gz  in=289,965,174 out=45,445,705 elapsed=95.7s

  [6553/21087] intraday_15048.csv.gz  in=289,975,908 out=45,456,439 elapsed=95.7s

  [6554/21087] intraday_15049.csv.gz  in=289,988,583 out=45,469,114 elapsed=95.8s

  [6555/21087] intraday_1505.csv.gz  in=290,005,098 out=45,469,114 elapsed=95.8s

  [6556/21087] intraday_15050.csv.gz  in=290,015,315 out=45,479,331 elapsed=95.8s

  [6557/21087] intraday_15051.csv.gz  in=290,025,601 out=45,489,617 elapsed=95.8s

  [6558/21087] intraday_15055.csv.gz  in=290,038,381 out=45,502,397 elapsed=95.8s

  [6559/21087] intraday_15053.csv.gz  in=290,051,758 out=45,515,774 elapsed=95.8s

  [6560/21087] intraday_15052.csv.gz  in=290,065,681 out=45,529,697 elapsed=95.8s

  [6561/21087] intraday_15054.csv.gz  in=290,080,504 out=45,544,520 elapsed=95.8s

  [6562/21087] intraday_15056.csv.gz  in=290,093,217 out=45,557,233 elapsed=95.9s

  [6563/21087] intraday_15059.csv.gz  in=290,107,498 out=45,571,514 elapsed=95.9s

  [6564/21087] intraday_15057.csv.gz  in=290,119,732 out=45,583,748 elapsed=95.9s

  [6565/21087] intraday_15058.csv.gz  in=290,130,544 out=45,594,560 elapsed=95.9s

  [6566/21087] intraday_1506.csv.gz  in=290,146,802 out=45,594,560 elapsed=95.9s

  [6567/21087] intraday_15061.csv.gz  in=290,157,694 out=45,605,452 elapsed=95.9s

  [6568/21087] intraday_15060.csv.gz  in=290,169,048 out=45,616,806 elapsed=96.0s

  [6569/21087] intraday_15063.csv.gz  in=290,180,101 out=45,627,859 elapsed=96.0s

  [6570/21087] intraday_15062.csv.gz  in=290,193,561 out=45,641,319 elapsed=96.0s

  [6571/21087] intraday_15066.csv.gz  in=290,206,774 out=45,654,532 elapsed=96.0s

  [6572/21087] intraday_15067.csv.gz  in=290,218,628 out=45,666,386 elapsed=96.0s

  [6573/21087] intraday_15065.csv.gz  in=290,232,812 out=45,680,570 elapsed=96.0s

  [6574/21087] intraday_15064.csv.gz  in=290,244,651 out=45,692,409 elapsed=96.0s

  [6575/21087] intraday_1507.csv.gz  in=290,258,005 out=45,692,409 elapsed=96.0s

  [6576/21087] intraday_15068.csv.gz  in=290,270,221 out=45,704,625 elapsed=96.1s

  [6577/21087] intraday_15069.csv.gz  in=290,281,780 out=45,716,184 elapsed=96.1s

  [6578/21087] intraday_15070.csv.gz  in=290,293,718 out=45,728,122 elapsed=96.1s

  [6579/21087] intraday_15071.csv.gz  in=290,307,497 out=45,741,901 elapsed=96.1s

  [6580/21087] intraday_15073.csv.gz  in=290,320,098 out=45,754,502 elapsed=96.1s

  [6581/21087] intraday_15072.csv.gz  in=290,331,745 out=45,766,149 elapsed=96.1s

  [6582/21087] intraday_15074.csv.gz  in=290,345,408 out=45,779,812 elapsed=96.1s

  [6583/21087] intraday_15075.csv.gz  in=290,355,798 out=45,790,202 elapsed=96.1s

  [6584/21087] intraday_15078.csv.gz  in=290,367,495 out=45,801,899 elapsed=96.2s

  [6585/21087] intraday_15077.csv.gz  in=290,378,079 out=45,812,483 elapsed=96.2s

  [6586/21087] intraday_15076.csv.gz  in=290,393,484 out=45,827,888 elapsed=96.2s

  [6587/21087] intraday_15079.csv.gz  in=290,406,744 out=45,841,148 elapsed=96.2s

  [6588/21087] intraday_1508.csv.gz  in=290,422,248 out=45,841,148 elapsed=96.2s

  [6589/21087] intraday_15081.csv.gz  in=290,432,424 out=45,851,324 elapsed=96.2s

  [6590/21087] intraday_15080.csv.gz  in=290,447,428 out=45,866,328 elapsed=96.2s

  [6591/21087] intraday_15082.csv.gz  in=290,462,181 out=45,881,081 elapsed=96.2s

  [6592/21087] intraday_15083.csv.gz  in=290,476,116 out=45,895,016 elapsed=96.2s

  [6593/21087] intraday_15084.csv.gz  in=290,488,262 out=45,907,162 elapsed=96.3s

  [6594/21087] intraday_15085.csv.gz  in=290,500,238 out=45,919,138 elapsed=96.3s

  [6595/21087] intraday_15087.csv.gz  in=290,517,158 out=45,936,058 elapsed=96.3s

  [6596/21087] intraday_15086.csv.gz  in=290,534,178 out=45,953,078 elapsed=96.3s

  [6597/21087] intraday_15088.csv.gz  in=290,549,590 out=45,968,490 elapsed=96.3s

  [6598/21087] intraday_15089.csv.gz  in=290,564,234 out=45,983,134 elapsed=96.3s

  [6599/21087] intraday_1509.csv.gz  in=290,575,953 out=45,983,134 elapsed=96.3s

  [6600/21087] intraday_15090.csv.gz  in=290,587,264 out=45,994,445 elapsed=96.3s

  [6601/21087] intraday_15091.csv.gz  in=290,599,482 out=46,006,663 elapsed=96.4s

  [6602/21087] intraday_15092.csv.gz  in=290,609,494 out=46,016,675 elapsed=96.4s

  [6603/21087] intraday_15093.csv.gz  in=290,622,757 out=46,029,938 elapsed=96.4s

  [6604/21087] intraday_15095.csv.gz  in=290,635,186 out=46,042,367 elapsed=96.4s

  [6605/21087] intraday_15096.csv.gz  in=290,647,871 out=46,055,052 elapsed=96.4s

  [6606/21087] intraday_15094.csv.gz  in=290,658,905 out=46,066,086 elapsed=96.4s

  [6607/21087] intraday_15097.csv.gz  in=290,672,741 out=46,079,922 elapsed=96.4s

  [6608/21087] intraday_15098.csv.gz  in=290,683,605 out=46,090,786 elapsed=96.5s

  [6609/21087] intraday_15099.csv.gz  in=290,695,252 out=46,102,433 elapsed=96.5s

  [6610/21087] intraday_1510.csv.gz  in=290,706,651 out=46,102,433 elapsed=96.5s

  [6611/21087] intraday_15100.csv.gz  in=290,719,304 out=46,115,086 elapsed=96.5s

  [6612/21087] intraday_15103.csv.gz  in=290,732,948 out=46,128,730 elapsed=96.5s

  [6613/21087] intraday_15102.csv.gz  in=290,744,728 out=46,140,510 elapsed=96.5s

  [6614/21087] intraday_15101.csv.gz  in=290,758,363 out=46,154,145 elapsed=96.5s

  [6615/21087] intraday_15104.csv.gz  in=290,773,039 out=46,168,821 elapsed=96.5s

  [6616/21087] intraday_15105.csv.gz  in=290,785,175 out=46,180,957 elapsed=96.5s

  [6617/21087] intraday_15106.csv.gz  in=290,801,026 out=46,196,808 elapsed=96.6s

  [6618/21087] intraday_15108.csv.gz  in=290,814,840 out=46,210,622 elapsed=96.6s

  [6619/21087] intraday_15107.csv.gz  in=290,825,919 out=46,221,701 elapsed=96.6s

  [6620/21087] intraday_15109.csv.gz  in=290,838,112 out=46,233,894 elapsed=96.6s

  [6621/21087] intraday_1511.csv.gz  in=290,852,745 out=46,233,894 elapsed=96.6s

  [6622/21087] intraday_15112.csv.gz  in=290,860,176 out=46,241,325 elapsed=96.6s

  [6623/21087] intraday_15110.csv.gz  in=290,870,158 out=46,251,307 elapsed=96.6s

  [6624/21087] intraday_15111.csv.gz  in=290,882,904 out=46,264,053 elapsed=96.6s

  [6625/21087] intraday_15114.csv.gz  in=290,896,294 out=46,274,379 elapsed=96.7s

  [6626/21087] intraday_15116.csv.gz  in=290,909,150 out=46,287,235 elapsed=96.7s

  [6627/21087] intraday_15115.csv.gz  in=290,923,357 out=46,301,442 elapsed=96.7s

  [6628/21087] intraday_15117.csv.gz  in=290,935,318 out=46,313,403 elapsed=96.7s

  [6629/21087] intraday_15118.csv.gz  in=290,947,284 out=46,325,369 elapsed=96.7s

  [6630/21087] intraday_15113.csv.gz  in=291,000,154 out=46,348,703 elapsed=96.7s

  [6631/21087] intraday_15119.csv.gz  in=291,011,341 out=46,359,890 elapsed=96.7s

  [6632/21087] intraday_1512.csv.gz  in=291,023,998 out=46,359,890 elapsed=96.7s

  [6633/21087] intraday_15120.csv.gz  in=291,038,942 out=46,374,834 elapsed=96.8s

  [6634/21087] intraday_15122.csv.gz  in=291,049,394 out=46,385,286 elapsed=96.8s

  [6635/21087] intraday_15121.csv.gz  in=291,062,749 out=46,398,641 elapsed=96.8s

  [6636/21087] intraday_15123.csv.gz  in=291,074,086 out=46,409,978 elapsed=96.8s

  [6637/21087] intraday_15124.csv.gz  in=291,085,980 out=46,421,872 elapsed=96.8s

  [6638/21087] intraday_15125.csv.gz  in=291,096,717 out=46,432,609 elapsed=96.8s

  [6639/21087] intraday_15127.csv.gz  in=291,109,054 out=46,444,946 elapsed=96.8s

  [6640/21087] intraday_15126.csv.gz  in=291,122,907 out=46,458,799 elapsed=96.8s

  [6641/21087] intraday_15128.csv.gz  in=291,135,581 out=46,471,473 elapsed=96.8s

  [6642/21087] intraday_1513.csv.gz  in=291,146,461 out=46,471,473 elapsed=96.8s

  [6643/21087] intraday_15130.csv.gz  in=291,155,478 out=46,480,490 elapsed=96.8s

  [6644/21087] intraday_15129.csv.gz  in=291,165,425 out=46,490,437 elapsed=96.9s

  [6645/21087] intraday_15131.csv.gz  in=291,181,163 out=46,506,175 elapsed=96.9s

  [6646/21087] intraday_15132.csv.gz  in=291,193,253 out=46,518,265 elapsed=96.9s

  [6647/21087] intraday_15133.csv.gz  in=291,203,224 out=46,528,236 elapsed=96.9s

  [6648/21087] intraday_15134.csv.gz  in=291,215,903 out=46,540,915 elapsed=96.9s

  [6649/21087] intraday_15135.csv.gz  in=291,228,025 out=46,553,037 elapsed=96.9s

  [6650/21087] intraday_15137.csv.gz  in=291,240,143 out=46,565,155 elapsed=96.9s

  [6651/21087] intraday_15136.csv.gz  in=291,253,273 out=46,578,285 elapsed=96.9s

  [6652/21087] intraday_15138.csv.gz  in=291,265,822 out=46,590,834 elapsed=96.9s

  [6653/21087] intraday_15139.csv.gz  in=291,281,992 out=46,604,603 elapsed=96.9s

  [6654/21087] intraday_1514.csv.gz  in=291,290,839 out=46,604,603 elapsed=96.9s

  [6655/21087] intraday_15140.csv.gz  in=291,301,579 out=46,615,343 elapsed=97.0s

  [6656/21087] intraday_15141.csv.gz  in=291,312,872 out=46,626,636 elapsed=97.0s

  [6657/21087] intraday_15142.csv.gz  in=291,323,942 out=46,637,706 elapsed=97.0s

  [6658/21087] intraday_15143.csv.gz  in=291,336,206 out=46,649,970 elapsed=97.0s

  [6659/21087] intraday_15144.csv.gz  in=291,348,658 out=46,662,422 elapsed=97.0s

  [6660/21087] intraday_15145.csv.gz  in=291,364,158 out=46,677,922 elapsed=97.0s

  [6661/21087] intraday_15147.csv.gz  in=291,374,610 out=46,688,374 elapsed=97.0s

  [6662/21087] intraday_15146.csv.gz  in=291,386,687 out=46,700,451 elapsed=97.0s

  [6663/21087] intraday_15148.csv.gz  in=291,399,607 out=46,713,371 elapsed=97.0s

  [6664/21087] intraday_1515.csv.gz  in=291,410,466 out=46,713,371 elapsed=97.0s

  [6665/21087] intraday_15149.csv.gz  in=291,423,609 out=46,726,514 elapsed=97.0s

  [6666/21087] intraday_15150.csv.gz  in=291,435,952 out=46,738,857 elapsed=97.0s

  [6667/21087] intraday_15151.csv.gz  in=291,448,687 out=46,751,592 elapsed=97.1s

  [6668/21087] intraday_15153.csv.gz  in=291,458,094 out=46,760,999 elapsed=97.1s

  [6669/21087] intraday_15154.csv.gz  in=291,468,264 out=46,771,169 elapsed=97.1s

  [6670/21087] intraday_15152.csv.gz  in=291,479,468 out=46,782,373 elapsed=97.1s

  [6671/21087] intraday_15155.csv.gz  in=291,490,813 out=46,793,718 elapsed=97.1s

  [6672/21087] intraday_15156.csv.gz  in=291,503,171 out=46,806,076 elapsed=97.1s

  [6673/21087] intraday_15157.csv.gz  in=291,516,577 out=46,819,482 elapsed=97.1s

  [6674/21087] intraday_15158.csv.gz  in=291,529,763 out=46,832,668 elapsed=97.1s

  [6675/21087] intraday_1516.csv.gz  in=291,535,829 out=46,832,668 elapsed=97.1s

  [6676/21087] intraday_15159.csv.gz  in=291,548,709 out=46,845,548 elapsed=97.1s

  [6677/21087] intraday_15160.csv.gz  in=291,559,834 out=46,856,673 elapsed=97.2s

  [6678/21087] intraday_15161.csv.gz  in=291,571,455 out=46,868,294 elapsed=97.2s

  [6679/21087] intraday_15162.csv.gz  in=291,584,335 out=46,881,174 elapsed=97.2s

  [6680/21087] intraday_15164.csv.gz  in=291,596,343 out=46,893,182 elapsed=97.2s

  [6681/21087] intraday_15166.csv.gz  in=291,611,317 out=46,908,156 elapsed=97.2s

  [6682/21087] intraday_15165.csv.gz  in=291,621,255 out=46,918,094 elapsed=97.2s

  [6683/21087] intraday_15163.csv.gz  in=291,631,914 out=46,928,753 elapsed=97.2s

  [6684/21087] intraday_15167.csv.gz  in=291,643,946 out=46,940,785 elapsed=97.3s

  [6685/21087] intraday_1517.csv.gz  in=291,659,198 out=46,940,785 elapsed=97.3s

  [6686/21087] intraday_15168.csv.gz  in=291,670,334 out=46,951,921 elapsed=97.3s

  [6687/21087] intraday_15169.csv.gz  in=291,684,496 out=46,966,083 elapsed=97.3s

  [6688/21087] intraday_15170.csv.gz  in=291,695,813 out=46,977,400 elapsed=97.3s

  [6689/21087] intraday_15172.csv.gz  in=291,707,354 out=46,988,941 elapsed=97.3s

  [6690/21087] intraday_15171.csv.gz  in=291,719,301 out=47,000,888 elapsed=97.3s

  [6691/21087] intraday_15173.csv.gz  in=291,730,996 out=47,012,583 elapsed=97.3s

  [6692/21087] intraday_15174.csv.gz  in=291,744,347 out=47,025,934 elapsed=97.3s

  [6693/21087] intraday_15176.csv.gz  in=291,754,042 out=47,035,629 elapsed=97.3s

  [6694/21087] intraday_15175.csv.gz  in=291,765,560 out=47,047,147 elapsed=97.3s

  [6695/21087] intraday_15178.csv.gz  in=291,774,613 out=47,056,200 elapsed=97.4s

  [6696/21087] intraday_15177.csv.gz  in=291,786,885 out=47,068,472 elapsed=97.4s

  [6697/21087] intraday_1518.csv.gz  in=291,800,999 out=47,068,472 elapsed=97.4s

  [6698/21087] intraday_15179.csv.gz  in=291,813,880 out=47,081,353 elapsed=97.4s

  [6699/21087] intraday_15180.csv.gz  in=291,827,876 out=47,095,349 elapsed=97.4s

  [6700/21087] intraday_15181.csv.gz  in=291,839,846 out=47,107,319 elapsed=97.4s

  [6701/21087] intraday_15182.csv.gz  in=291,851,662 out=47,119,135 elapsed=97.4s

  [6702/21087] intraday_15183.csv.gz  in=291,865,027 out=47,132,500 elapsed=97.4s

  [6703/21087] intraday_15184.csv.gz  in=291,873,532 out=47,141,005 elapsed=97.4s

  [6704/21087] intraday_15185.csv.gz  in=291,886,664 out=47,154,137 elapsed=97.4s

  [6705/21087] intraday_15186.csv.gz  in=291,897,981 out=47,165,454 elapsed=97.5s

  [6706/21087] intraday_15187.csv.gz  in=291,910,298 out=47,177,771 elapsed=97.5s

  [6707/21087] intraday_15188.csv.gz  in=291,919,938 out=47,187,411 elapsed=97.5s

  [6708/21087] intraday_1519.csv.gz  in=291,931,869 out=47,187,411 elapsed=97.5s

  [6709/21087] intraday_15189.csv.gz  in=291,945,008 out=47,200,550 elapsed=97.5s

  [6710/21087] intraday_15190.csv.gz  in=291,953,943 out=47,209,485 elapsed=97.5s

  [6711/21087] intraday_15191.csv.gz  in=291,965,858 out=47,221,400 elapsed=97.5s

  [6712/21087] intraday_15192.csv.gz  in=291,978,231 out=47,233,773 elapsed=97.5s

  [6713/21087] intraday_15193.csv.gz  in=291,989,455 out=47,244,997 elapsed=97.5s

  [6714/21087] intraday_15194.csv.gz  in=292,000,788 out=47,256,330 elapsed=97.5s

  [6715/21087] intraday_15195.csv.gz  in=292,010,654 out=47,266,196 elapsed=97.6s

  [6716/21087] intraday_15197.csv.gz  in=292,022,654 out=47,278,196 elapsed=97.6s

  [6717/21087] intraday_15196.csv.gz  in=292,034,145 out=47,289,687 elapsed=97.6s

  [6718/21087] intraday_15199.csv.gz  in=292,045,693 out=47,301,235 elapsed=97.6s

  [6719/21087] intraday_15198.csv.gz  in=292,062,342 out=47,317,884 elapsed=97.6s

  [6720/21087] intraday_1520.csv.gz  in=292,074,435 out=47,317,884 elapsed=97.6s

  [6721/21087] intraday_15201.csv.gz  in=292,085,203 out=47,328,652 elapsed=97.6s

  [6722/21087] intraday_15200.csv.gz  in=292,099,542 out=47,342,991 elapsed=97.6s

  [6723/21087] intraday_15202.csv.gz  in=292,113,129 out=47,356,578 elapsed=97.6s

  [6724/21087] intraday_15203.csv.gz  in=292,123,328 out=47,366,777 elapsed=97.6s

  [6725/21087] intraday_15204.csv.gz  in=292,138,184 out=47,381,633 elapsed=97.7s

  [6726/21087] intraday_15205.csv.gz  in=292,148,002 out=47,391,451 elapsed=97.7s

  [6727/21087] intraday_15206.csv.gz  in=292,160,561 out=47,404,010 elapsed=97.7s

  [6728/21087] intraday_15207.csv.gz  in=292,173,296 out=47,416,136 elapsed=97.7s

  [6729/21087] intraday_15208.csv.gz  in=292,183,919 out=47,426,759 elapsed=97.7s

  [6730/21087] intraday_1521.csv.gz  in=292,197,530 out=47,426,759 elapsed=97.7s

  [6731/21087] intraday_15209.csv.gz  in=292,210,724 out=47,439,953 elapsed=97.7s

  [6732/21087] intraday_15210.csv.gz  in=292,223,116 out=47,452,345 elapsed=97.7s

  [6733/21087] intraday_15212.csv.gz  in=292,233,588 out=47,462,817 elapsed=97.8s

  [6734/21087] intraday_15211.csv.gz  in=292,246,502 out=47,475,731 elapsed=97.8s

  [6735/21087] intraday_15214.csv.gz  in=292,259,665 out=47,488,894 elapsed=97.8s

  [6736/21087] intraday_15213.csv.gz  in=292,271,402 out=47,500,631 elapsed=97.8s

  [6737/21087] intraday_15215.csv.gz  in=292,284,126 out=47,513,355 elapsed=97.8s

  [6738/21087] intraday_15216.csv.gz  in=292,296,883 out=47,526,112 elapsed=97.8s

  [6739/21087] intraday_15217.csv.gz  in=292,308,552 out=47,537,781 elapsed=97.8s

  [6740/21087] intraday_15218.csv.gz  in=292,320,643 out=47,549,872 elapsed=97.8s

  [6741/21087] intraday_1522.csv.gz  in=292,334,222 out=47,549,872 elapsed=97.8s

  [6742/21087] intraday_15219.csv.gz  in=292,345,791 out=47,561,441 elapsed=97.8s

  [6743/21087] intraday_15220.csv.gz  in=292,358,465 out=47,574,115 elapsed=97.8s

  [6744/21087] intraday_15223.csv.gz  in=292,371,468 out=47,587,118 elapsed=97.9s

  [6745/21087] intraday_15221.csv.gz  in=292,385,501 out=47,601,151 elapsed=97.9s

  [6746/21087] intraday_15222.csv.gz  in=292,396,937 out=47,612,587 elapsed=97.9s

  [6747/21087] intraday_15224.csv.gz  in=292,409,367 out=47,625,017 elapsed=97.9s

  [6748/21087] intraday_15225.csv.gz  in=292,421,966 out=47,637,616 elapsed=97.9s

  [6749/21087] intraday_15227.csv.gz  in=292,434,835 out=47,650,485 elapsed=97.9s

  [6750/21087] intraday_15226.csv.gz  in=292,449,769 out=47,664,796 elapsed=97.9s

  [6751/21087] intraday_15229.csv.gz  in=292,461,527 out=47,676,554 elapsed=98.0s

  [6752/21087] intraday_15228.csv.gz  in=292,475,370 out=47,690,397 elapsed=98.0s

  [6753/21087] intraday_1523.csv.gz  in=292,487,894 out=47,690,397 elapsed=98.0s

  [6754/21087] intraday_15230.csv.gz  in=292,500,855 out=47,703,358 elapsed=98.0s

  [6755/21087] intraday_15231.csv.gz  in=292,518,104 out=47,720,607 elapsed=98.0s

  [6756/21087] intraday_15232.csv.gz  in=292,530,991 out=47,733,494 elapsed=98.0s

  [6757/21087] intraday_15233.csv.gz  in=292,547,527 out=47,750,030 elapsed=98.0s

  [6758/21087] intraday_15234.csv.gz  in=292,558,205 out=47,760,708 elapsed=98.0s

  [6759/21087] intraday_15236.csv.gz  in=292,568,564 out=47,771,067 elapsed=98.0s

  [6760/21087] intraday_15235.csv.gz  in=292,581,299 out=47,783,802 elapsed=98.1s

  [6761/21087] intraday_15238.csv.gz  in=292,591,742 out=47,794,245 elapsed=98.1s

  [6762/21087] intraday_15237.csv.gz  in=292,603,686 out=47,806,189 elapsed=98.1s

  [6763/21087] intraday_15239.csv.gz  in=292,616,337 out=47,818,840 elapsed=98.1s

  [6764/21087] intraday_1524.csv.gz  in=292,628,730 out=47,818,840 elapsed=98.1s

  [6765/21087] intraday_15240.csv.gz  in=292,640,124 out=47,830,234 elapsed=98.1s

  [6766/21087] intraday_15241.csv.gz  in=292,655,220 out=47,845,330 elapsed=98.1s

  [6767/21087] intraday_15243.csv.gz  in=292,666,190 out=47,856,300 elapsed=98.1s

  [6768/21087] intraday_15242.csv.gz  in=292,675,905 out=47,866,015 elapsed=98.1s

  [6769/21087] intraday_15244.csv.gz  in=292,687,819 out=47,877,929 elapsed=98.1s

  [6770/21087] intraday_15245.csv.gz  in=292,701,410 out=47,891,520 elapsed=98.2s

  [6771/21087] intraday_15246.csv.gz  in=292,711,545 out=47,901,655 elapsed=98.2s

  [6772/21087] intraday_15247.csv.gz  in=292,724,466 out=47,914,576 elapsed=98.2s

  [6773/21087] intraday_15248.csv.gz  in=292,739,880 out=47,929,990 elapsed=98.2s

  [6774/21087] intraday_1525.csv.gz  in=292,753,361 out=47,929,990 elapsed=98.2s

  [6775/21087] intraday_15249.csv.gz  in=292,767,171 out=47,943,800 elapsed=98.2s

  [6776/21087] intraday_15250.csv.gz  in=292,780,536 out=47,957,165 elapsed=98.2s

  [6777/21087] intraday_15251.csv.gz  in=292,793,008 out=47,969,637 elapsed=98.2s

  [6778/21087] intraday_15252.csv.gz  in=292,804,254 out=47,980,883 elapsed=98.2s

  [6779/21087] intraday_15253.csv.gz  in=292,816,428 out=47,993,057 elapsed=98.2s

  [6780/21087] intraday_15255.csv.gz  in=292,828,281 out=48,004,910 elapsed=98.3s

  [6781/21087] intraday_15256.csv.gz  in=292,837,750 out=48,014,379 elapsed=98.3s

  [6782/21087] intraday_15254.csv.gz  in=292,847,950 out=48,024,579 elapsed=98.3s

  [6783/21087] intraday_15257.csv.gz  in=292,856,504 out=48,033,133 elapsed=98.3s

  [6784/21087] intraday_15258.csv.gz  in=292,868,464 out=48,045,093 elapsed=98.3s

  [6785/21087] intraday_1526.csv.gz  in=292,882,422 out=48,045,093 elapsed=98.3s

  [6786/21087] intraday_15259.csv.gz  in=292,897,250 out=48,059,921 elapsed=98.3s

  [6787/21087] intraday_15260.csv.gz  in=292,909,628 out=48,072,299 elapsed=98.3s

  [6788/21087] intraday_15261.csv.gz  in=292,922,534 out=48,085,205 elapsed=98.3s

  [6789/21087] intraday_15262.csv.gz  in=292,935,081 out=48,097,752 elapsed=98.4s

  [6790/21087] intraday_15263.csv.gz  in=292,946,629 out=48,109,300 elapsed=98.4s

  [6791/21087] intraday_15264.csv.gz  in=292,961,825 out=48,124,496 elapsed=98.4s

  [6792/21087] intraday_15265.csv.gz  in=292,974,443 out=48,137,114 elapsed=98.4s

  [6793/21087] intraday_15266.csv.gz  in=292,985,806 out=48,148,477 elapsed=98.4s

  [6794/21087] intraday_15267.csv.gz  in=292,998,055 out=48,160,726 elapsed=98.4s

  [6795/21087] intraday_15268.csv.gz  in=293,010,149 out=48,172,820 elapsed=98.4s

  [6796/21087] intraday_15269.csv.gz  in=293,020,903 out=48,183,574 elapsed=98.4s

  [6797/21087] intraday_1527.csv.gz  in=293,029,941 out=48,183,574 elapsed=98.4s

  [6798/21087] intraday_15270.csv.gz  in=293,043,783 out=48,197,416 elapsed=98.5s

  [6799/21087] intraday_15272.csv.gz  in=293,056,177 out=48,209,810 elapsed=98.5s

  [6800/21087] intraday_15271.csv.gz  in=293,070,269 out=48,223,902 elapsed=98.5s

  [6801/21087] intraday_15273.csv.gz  in=293,080,290 out=48,233,923 elapsed=98.5s

  [6802/21087] intraday_15274.csv.gz  in=293,089,944 out=48,243,577 elapsed=98.5s

  [6803/21087] intraday_15275.csv.gz  in=293,105,125 out=48,258,758 elapsed=98.5s

  [6804/21087] intraday_15276.csv.gz  in=293,118,541 out=48,272,174 elapsed=98.5s

  [6805/21087] intraday_15277.csv.gz  in=293,128,322 out=48,281,955 elapsed=98.5s

  [6806/21087] intraday_1528.csv.gz  in=293,140,080 out=48,281,955 elapsed=98.5s

  [6807/21087] intraday_15278.csv.gz  in=293,152,902 out=48,294,777 elapsed=98.5s

  [6808/21087] intraday_15279.csv.gz  in=293,165,414 out=48,307,289 elapsed=98.5s

  [6809/21087] intraday_15280.csv.gz  in=293,178,903 out=48,320,778 elapsed=98.6s

  [6810/21087] intraday_15281.csv.gz  in=293,190,467 out=48,332,342 elapsed=98.6s

  [6811/21087] intraday_15282.csv.gz  in=293,202,486 out=48,344,361 elapsed=98.6s

  [6812/21087] intraday_15283.csv.gz  in=293,214,020 out=48,355,895 elapsed=98.6s

  [6813/21087] intraday_15285.csv.gz  in=293,225,279 out=48,367,154 elapsed=98.6s

  [6814/21087] intraday_15286.csv.gz  in=293,235,839 out=48,377,714 elapsed=98.6s

  [6815/21087] intraday_15284.csv.gz  in=293,248,211 out=48,390,086 elapsed=98.6s

  [6816/21087] intraday_15287.csv.gz  in=293,259,777 out=48,401,652 elapsed=98.6s

  [6817/21087] intraday_15288.csv.gz  in=293,273,374 out=48,415,249 elapsed=98.7s

  [6818/21087] intraday_1529.csv.gz  in=293,287,596 out=48,415,249 elapsed=98.7s

  [6819/21087] intraday_15290.csv.gz  in=293,297,885 out=48,425,538 elapsed=98.7s

  [6820/21087] intraday_15289.csv.gz  in=293,315,550 out=48,442,904 elapsed=98.7s

  [6821/21087] intraday_15291.csv.gz  in=293,326,773 out=48,454,127 elapsed=98.7s

  [6822/21087] intraday_15292.csv.gz  in=293,339,365 out=48,466,719 elapsed=98.7s

  [6823/21087] intraday_15294.csv.gz  in=293,350,974 out=48,478,328 elapsed=98.7s

  [6824/21087] intraday_15293.csv.gz  in=293,382,132 out=48,499,371 elapsed=98.7s

  [6825/21087] intraday_15295.csv.gz  in=293,395,142 out=48,512,381 elapsed=98.7s

  [6826/21087] intraday_15296.csv.gz  in=293,406,847 out=48,524,086 elapsed=98.7s

  [6827/21087] intraday_15297.csv.gz  in=293,416,963 out=48,534,202 elapsed=98.7s

  [6828/21087] intraday_15298.csv.gz  in=293,426,369 out=48,543,608 elapsed=98.7s

  [6829/21087] intraday_1530.csv.gz  in=293,437,234 out=48,543,608 elapsed=98.8s

  [6830/21087] intraday_15299.csv.gz  in=293,447,874 out=48,554,248 elapsed=98.8s

  [6831/21087] intraday_15300.csv.gz  in=293,459,680 out=48,566,054 elapsed=98.8s

  [6832/21087] intraday_15301.csv.gz  in=293,473,612 out=48,579,986 elapsed=98.8s

  [6833/21087] intraday_15302.csv.gz  in=293,486,434 out=48,592,808 elapsed=98.8s

  [6834/21087] intraday_15303.csv.gz  in=293,499,647 out=48,606,021 elapsed=98.8s

  [6835/21087] intraday_15305.csv.gz  in=293,511,044 out=48,617,418 elapsed=98.8s

  [6836/21087] intraday_15304.csv.gz  in=293,522,168 out=48,628,542 elapsed=98.8s

  [6837/21087] intraday_15306.csv.gz  in=293,535,237 out=48,641,611 elapsed=98.9s

  [6838/21087] intraday_15307.csv.gz  in=293,546,293 out=48,652,667 elapsed=98.9s

  [6839/21087] intraday_15309.csv.gz  in=293,556,535 out=48,662,909 elapsed=98.9s

  [6840/21087] intraday_1531.csv.gz  in=293,566,359 out=48,662,909 elapsed=98.9s

  [6841/21087] intraday_15308.csv.gz  in=293,577,707 out=48,674,257 elapsed=98.9s

  [6842/21087] intraday_15310.csv.gz  in=293,592,745 out=48,689,295 elapsed=98.9s

  [6843/21087] intraday_15311.csv.gz  in=293,604,731 out=48,701,281 elapsed=98.9s

  [6844/21087] intraday_15312.csv.gz  in=293,616,927 out=48,713,477 elapsed=98.9s

  [6845/21087] intraday_15313.csv.gz  in=293,631,754 out=48,728,304 elapsed=98.9s

  [6846/21087] intraday_15314.csv.gz  in=293,643,928 out=48,740,478 elapsed=98.9s

  [6847/21087] intraday_15315.csv.gz  in=293,654,723 out=48,751,273 elapsed=98.9s

  [6848/21087] intraday_15316.csv.gz  in=293,666,619 out=48,763,169 elapsed=98.9s

  [6849/21087] intraday_15317.csv.gz  in=293,679,875 out=48,776,425 elapsed=99.0s

  [6850/21087] intraday_1532.csv.gz  in=293,693,579 out=48,776,425 elapsed=99.0s

  [6851/21087] intraday_15318.csv.gz  in=293,706,427 out=48,789,273 elapsed=99.0s

  [6852/21087] intraday_15319.csv.gz  in=293,717,456 out=48,800,302 elapsed=99.0s

  [6853/21087] intraday_15320.csv.gz  in=293,727,728 out=48,810,574 elapsed=99.0s

  [6854/21087] intraday_15321.csv.gz  in=293,739,939 out=48,822,785 elapsed=99.0s

  [6855/21087] intraday_15323.csv.gz  in=293,754,108 out=48,836,954 elapsed=99.0s

  [6856/21087] intraday_15322.csv.gz  in=293,763,836 out=48,846,682 elapsed=99.0s

  [6857/21087] intraday_15325.csv.gz  in=293,776,261 out=48,859,107 elapsed=99.1s

  [6858/21087] intraday_15324.csv.gz  in=293,789,169 out=48,872,015 elapsed=99.1s

  [6859/21087] intraday_15327.csv.gz  in=293,800,841 out=48,883,687 elapsed=99.1s

  [6860/21087] intraday_15326.csv.gz  in=293,812,783 out=48,895,629 elapsed=99.1s

  [6861/21087] intraday_15328.csv.gz  in=293,821,518 out=48,904,364 elapsed=99.1s

  [6862/21087] intraday_1533.csv.gz  in=293,832,971 out=48,904,364 elapsed=99.1s

  [6863/21087] intraday_15329.csv.gz  in=293,845,496 out=48,916,889 elapsed=99.1s

  [6864/21087] intraday_15330.csv.gz  in=293,856,834 out=48,928,227 elapsed=99.1s

  [6865/21087] intraday_15331.csv.gz  in=293,869,158 out=48,940,551 elapsed=99.1s

  [6866/21087] intraday_15332.csv.gz  in=293,879,347 out=48,950,740 elapsed=99.1s

  [6867/21087] intraday_15333.csv.gz  in=293,891,960 out=48,963,353 elapsed=99.1s

  [6868/21087] intraday_15335.csv.gz  in=293,903,703 out=48,975,096 elapsed=99.2s

  [6869/21087] intraday_15334.csv.gz  in=293,916,846 out=48,987,748 elapsed=99.2s

  [6870/21087] intraday_15336.csv.gz  in=293,929,904 out=49,000,806 elapsed=99.2s

  [6871/21087] intraday_15337.csv.gz  in=293,941,619 out=49,012,521 elapsed=99.2s

  [6872/21087] intraday_15338.csv.gz  in=293,952,969 out=49,023,871 elapsed=99.2s

  [6873/21087] intraday_15339.csv.gz  in=293,963,918 out=49,034,820 elapsed=99.2s

  [6874/21087] intraday_1534.csv.gz  in=293,976,122 out=49,034,820 elapsed=99.2s

  [6875/21087] intraday_15340.csv.gz  in=293,987,214 out=49,045,912 elapsed=99.2s

  [6876/21087] intraday_15341.csv.gz  in=293,999,342 out=49,058,040 elapsed=99.2s

  [6877/21087] intraday_15344.csv.gz  in=294,015,797 out=49,074,495 elapsed=99.3s

  [6878/21087] intraday_15343.csv.gz  in=294,027,238 out=49,085,936 elapsed=99.3s

  [6879/21087] intraday_15342.csv.gz  in=294,045,093 out=49,103,791 elapsed=99.3s

  [6880/21087] intraday_15345.csv.gz  in=294,055,456 out=49,114,154 elapsed=99.3s

  [6881/21087] intraday_15347.csv.gz  in=294,065,516 out=49,124,214 elapsed=99.3s

  [6882/21087] intraday_15349.csv.gz  in=294,076,112 out=49,134,810 elapsed=99.3s

  [6883/21087] intraday_15346.csv.gz  in=294,089,076 out=49,147,774 elapsed=99.3s

  [6884/21087] intraday_15348.csv.gz  in=294,104,710 out=49,163,408 elapsed=99.3s

  [6885/21087] intraday_1535.csv.gz  in=294,116,566 out=49,163,408 elapsed=99.3s

  [6886/21087] intraday_15350.csv.gz  in=294,128,411 out=49,175,253 elapsed=99.4s

  [6887/21087] intraday_15351.csv.gz  in=294,138,874 out=49,185,716 elapsed=99.4s

  [6888/21087] intraday_15352.csv.gz  in=294,150,611 out=49,197,453 elapsed=99.4s

  [6889/21087] intraday_15353.csv.gz  in=294,163,268 out=49,210,110 elapsed=99.4s

  [6890/21087] intraday_15357.csv.gz  in=294,174,592 out=49,221,434 elapsed=99.4s

  [6891/21087] intraday_15354.csv.gz  in=294,190,421 out=49,236,053 elapsed=99.4s

  [6892/21087] intraday_15355.csv.gz  in=294,202,493 out=49,248,125 elapsed=99.4s

  [6893/21087] intraday_15356.csv.gz  in=294,213,164 out=49,258,796 elapsed=99.4s

  [6894/21087] intraday_1536.csv.gz  in=294,224,589 out=49,258,796 elapsed=99.4s

  [6895/21087] intraday_15358.csv.gz  in=294,236,685 out=49,270,892 elapsed=99.5s

  [6896/21087] intraday_15359.csv.gz  in=294,249,524 out=49,283,731 elapsed=99.5s

  [6897/21087] intraday_15360.csv.gz  in=294,262,789 out=49,296,996 elapsed=99.5s

  [6898/21087] intraday_15361.csv.gz  in=294,273,901 out=49,308,108 elapsed=99.5s

  [6899/21087] intraday_15363.csv.gz  in=294,284,078 out=49,318,285 elapsed=99.5s

  [6900/21087] intraday_15362.csv.gz  in=294,296,387 out=49,330,594 elapsed=99.5s

  [6901/21087] intraday_15364.csv.gz  in=294,310,008 out=49,344,215 elapsed=99.5s

  [6902/21087] intraday_15365.csv.gz  in=294,321,556 out=49,355,763 elapsed=99.5s

  [6903/21087] intraday_15366.csv.gz  in=294,332,966 out=49,367,173 elapsed=99.5s

  [6904/21087] intraday_1537.csv.gz  in=294,345,000 out=49,367,173 elapsed=99.6s

  [6905/21087] intraday_15367.csv.gz  in=294,358,152 out=49,380,325 elapsed=99.6s

  [6906/21087] intraday_15368.csv.gz  in=294,370,970 out=49,393,143 elapsed=99.6s

  [6907/21087] intraday_15369.csv.gz  in=294,383,551 out=49,405,724 elapsed=99.6s

  [6908/21087] intraday_15373.csv.gz  in=294,395,827 out=49,418,000 elapsed=99.6s

  [6909/21087] intraday_15371.csv.gz  in=294,408,459 out=49,430,632 elapsed=99.6s

  [6910/21087] intraday_15372.csv.gz  in=294,421,916 out=49,444,089 elapsed=99.6s

  [6911/21087] intraday_15370.csv.gz  in=294,447,637 out=49,461,848 elapsed=99.6s

  [6912/21087] intraday_15375.csv.gz  in=294,466,710 out=49,480,921 elapsed=99.7s

  [6913/21087] intraday_15374.csv.gz  in=294,480,249 out=49,494,460 elapsed=99.7s

  [6914/21087] intraday_15376.csv.gz  in=294,491,975 out=49,506,186 elapsed=99.7s

  [6915/21087] intraday_15377.csv.gz  in=294,508,593 out=49,522,804 elapsed=99.7s

  [6916/21087] intraday_1538.csv.gz  in=294,520,463 out=49,522,804 elapsed=99.7s

  [6917/21087] intraday_15378.csv.gz  in=294,531,952 out=49,534,293 elapsed=99.7s

  [6918/21087] intraday_15379.csv.gz  in=294,544,619 out=49,546,960 elapsed=99.7s

  [6919/21087] intraday_15380.csv.gz  in=294,554,889 out=49,557,230 elapsed=99.7s

  [6920/21087] intraday_15381.csv.gz  in=294,567,238 out=49,569,579 elapsed=99.7s

  [6921/21087] intraday_15382.csv.gz  in=294,577,788 out=49,580,129 elapsed=99.8s

  [6922/21087] intraday_15384.csv.gz  in=294,588,786 out=49,591,127 elapsed=99.8s

  [6923/21087] intraday_15383.csv.gz  in=294,601,900 out=49,604,241 elapsed=99.8s

  [6924/21087] intraday_15385.csv.gz  in=294,618,232 out=49,620,573 elapsed=99.8s

  [6925/21087] intraday_15386.csv.gz  in=294,628,824 out=49,631,165 elapsed=99.8s

  [6926/21087] intraday_15387.csv.gz  in=294,640,051 out=49,642,392 elapsed=99.8s

  [6927/21087] intraday_15388.csv.gz  in=294,651,400 out=49,653,741 elapsed=99.8s

  [6928/21087] intraday_1539.csv.gz  in=294,663,577 out=49,653,741 elapsed=99.8s

  [6929/21087] intraday_15389.csv.gz  in=294,677,034 out=49,667,198 elapsed=99.8s

  [6930/21087] intraday_15390.csv.gz  in=294,687,129 out=49,677,293 elapsed=99.9s

  [6931/21087] intraday_15391.csv.gz  in=294,699,391 out=49,689,555 elapsed=99.9s

  [6932/21087] intraday_15392.csv.gz  in=294,713,652 out=49,703,816 elapsed=99.9s

  [6933/21087] intraday_15393.csv.gz  in=294,726,648 out=49,716,812 elapsed=99.9s

  [6934/21087] intraday_15394.csv.gz  in=294,740,646 out=49,730,810 elapsed=99.9s

  [6935/21087] intraday_15396.csv.gz  in=294,751,759 out=49,741,923 elapsed=99.9s

  [6936/21087] intraday_15395.csv.gz  in=294,763,771 out=49,753,935 elapsed=99.9s

  [6937/21087] intraday_15397.csv.gz  in=294,776,252 out=49,766,416 elapsed=99.9s

  [6938/21087] intraday_15398.csv.gz  in=294,786,086 out=49,776,250 elapsed=99.9s

  [6939/21087] intraday_1540.csv.gz  in=294,800,171 out=49,776,250 elapsed=100.0s

  [6940/21087] intraday_15399.csv.gz  in=294,812,419 out=49,788,498 elapsed=100.0s

  [6941/21087] intraday_15400.csv.gz  in=294,822,585 out=49,798,664 elapsed=100.0s

  [6942/21087] intraday_15401.csv.gz  in=294,829,868 out=49,805,947 elapsed=100.0s

  [6943/21087] intraday_15402.csv.gz  in=294,841,600 out=49,817,679 elapsed=100.0s

  [6944/21087] intraday_15403.csv.gz  in=294,856,539 out=49,832,618 elapsed=100.0s

  [6945/21087] intraday_15406.csv.gz  in=294,867,048 out=49,843,001 elapsed=100.0s

  [6946/21087] intraday_15405.csv.gz  in=294,879,490 out=49,855,443 elapsed=100.0s

  [6947/21087] intraday_15404.csv.gz  in=294,891,890 out=49,867,843 elapsed=100.0s

  [6948/21087] intraday_1541.csv.gz  in=294,902,716 out=49,867,843 elapsed=100.1s

  [6949/21087] intraday_15409.csv.gz  in=294,914,405 out=49,879,532 elapsed=100.1s

  [6950/21087] intraday_15407.csv.gz  in=294,927,668 out=49,892,795 elapsed=100.1s

  [6951/21087] intraday_15408.csv.gz  in=294,942,373 out=49,907,500 elapsed=100.1s

  [6952/21087] intraday_15410.csv.gz  in=294,954,351 out=49,919,478 elapsed=100.1s

  [6953/21087] intraday_15411.csv.gz  in=294,965,779 out=49,930,906 elapsed=100.1s

  [6954/21087] intraday_15412.csv.gz  in=294,977,042 out=49,942,169 elapsed=100.1s

  [6955/21087] intraday_15413.csv.gz  in=294,988,133 out=49,953,260 elapsed=100.1s

  [6956/21087] intraday_15414.csv.gz  in=295,000,737 out=49,965,864 elapsed=100.1s

  [6957/21087] intraday_15417.csv.gz  in=295,009,744 out=49,974,871 elapsed=100.2s

  [6958/21087] intraday_15415.csv.gz  in=295,022,420 out=49,987,547 elapsed=100.2s

  [6959/21087] intraday_15416.csv.gz  in=295,036,432 out=50,001,244 elapsed=100.2s

  [6960/21087] intraday_15418.csv.gz  in=295,046,755 out=50,011,567 elapsed=100.2s

  [6961/21087] intraday_15419.csv.gz  in=295,060,690 out=50,025,502 elapsed=100.2s

  [6962/21087] intraday_1542.csv.gz  in=295,070,980 out=50,025,502 elapsed=100.2s

  [6963/21087] intraday_15421.csv.gz  in=295,080,338 out=50,034,860 elapsed=100.2s

  [6964/21087] intraday_15422.csv.gz  in=295,093,500 out=50,048,022 elapsed=100.2s

  [6965/21087] intraday_15420.csv.gz  in=295,106,069 out=50,060,591 elapsed=100.2s

  [6966/21087] intraday_15423.csv.gz  in=295,117,235 out=50,071,757 elapsed=100.2s

  [6967/21087] intraday_15424.csv.gz  in=295,129,547 out=50,084,069 elapsed=100.2s

  [6968/21087] intraday_15425.csv.gz  in=295,142,083 out=50,096,605 elapsed=100.3s

  [6969/21087] intraday_15426.csv.gz  in=295,153,050 out=50,107,572 elapsed=100.3s

  [6970/21087] intraday_15427.csv.gz  in=295,165,271 out=50,119,793 elapsed=100.3s

  [6971/21087] intraday_15428.csv.gz  in=295,175,868 out=50,130,390 elapsed=100.3s

  [6972/21087] intraday_15429.csv.gz  in=295,186,458 out=50,140,980 elapsed=100.3s

  [6973/21087] intraday_1543.csv.gz  in=295,200,109 out=50,140,980 elapsed=100.3s

  [6974/21087] intraday_15430.csv.gz  in=295,210,571 out=50,151,442 elapsed=100.3s

  [6975/21087] intraday_15431.csv.gz  in=295,223,635 out=50,164,506 elapsed=100.3s

  [6976/21087] intraday_15432.csv.gz  in=295,235,951 out=50,176,822 elapsed=100.3s

  [6977/21087] intraday_15433.csv.gz  in=295,249,753 out=50,190,624 elapsed=100.4s

  [6978/21087] intraday_15434.csv.gz  in=295,259,885 out=50,200,756 elapsed=100.4s

  [6979/21087] intraday_15435.csv.gz  in=295,270,406 out=50,211,277 elapsed=100.4s

  [6980/21087] intraday_15436.csv.gz  in=295,282,349 out=50,223,220 elapsed=100.4s

  [6981/21087] intraday_15438.csv.gz  in=295,293,393 out=50,234,264 elapsed=100.4s

  [6982/21087] intraday_15437.csv.gz  in=295,313,146 out=50,250,494 elapsed=100.4s

  [6983/21087] intraday_1544.csv.gz  in=295,326,260 out=50,250,494 elapsed=100.4s

  [6984/21087] intraday_15439.csv.gz  in=295,338,717 out=50,262,951 elapsed=100.4s

  [6985/21087] intraday_15440.csv.gz  in=295,349,626 out=50,273,860 elapsed=100.4s

  [6986/21087] intraday_15441.csv.gz  in=295,359,530 out=50,283,764 elapsed=100.4s

  [6987/21087] intraday_15442.csv.gz  in=295,369,352 out=50,293,586 elapsed=100.5s

  [6988/21087] intraday_15443.csv.gz  in=295,380,328 out=50,304,562 elapsed=100.5s

  [6989/21087] intraday_15444.csv.gz  in=295,392,083 out=50,316,317 elapsed=100.5s

  [6990/21087] intraday_15445.csv.gz  in=295,405,209 out=50,329,443 elapsed=100.5s

  [6991/21087] intraday_15446.csv.gz  in=295,418,038 out=50,342,272 elapsed=100.5s

  [6992/21087] intraday_15448.csv.gz  in=295,429,465 out=50,353,699 elapsed=100.5s

  [6993/21087] intraday_15447.csv.gz  in=295,440,281 out=50,364,515 elapsed=100.5s

  [6994/21087] intraday_15449.csv.gz  in=295,451,433 out=50,375,667 elapsed=100.5s

  [6995/21087] intraday_1545.csv.gz  in=295,466,259 out=50,375,667 elapsed=100.5s

  [6996/21087] intraday_15451.csv.gz  in=295,476,758 out=50,386,166 elapsed=100.6s

  [6997/21087] intraday_15453.csv.gz  in=295,486,260 out=50,395,668 elapsed=100.6s

  [6998/21087] intraday_15450.csv.gz  in=295,498,786 out=50,408,194 elapsed=100.6s

  [6999/21087] intraday_15452.csv.gz  in=295,509,758 out=50,419,166 elapsed=100.6s

  [7000/21087] intraday_15454.csv.gz  in=295,523,641 out=50,433,049 elapsed=100.6s

  [7001/21087] intraday_15455.csv.gz  in=295,534,826 out=50,444,234 elapsed=100.6s

  [7002/21087] intraday_15458.csv.gz  in=295,545,751 out=50,455,159 elapsed=100.6s

  [7003/21087] intraday_15456.csv.gz  in=295,556,517 out=50,465,925 elapsed=100.6s

  [7004/21087] intraday_15457.csv.gz  in=295,570,817 out=50,480,225 elapsed=100.6s

  [7005/21087] intraday_1546.csv.gz  in=295,585,166 out=50,480,225 elapsed=100.7s

  [7006/21087] intraday_15459.csv.gz  in=295,595,973 out=50,491,032 elapsed=100.7s

  [7007/21087] intraday_15460.csv.gz  in=295,606,913 out=50,501,972 elapsed=100.7s

  [7008/21087] intraday_15461.csv.gz  in=295,617,475 out=50,512,534 elapsed=100.7s

  [7009/21087] intraday_15462.csv.gz  in=295,629,563 out=50,524,622 elapsed=100.7s

  [7010/21087] intraday_15463.csv.gz  in=295,660,254 out=50,546,175 elapsed=100.7s

  [7011/21087] intraday_15464.csv.gz  in=295,670,539 out=50,556,460 elapsed=100.7s

  [7012/21087] intraday_15465.csv.gz  in=295,681,089 out=50,567,010 elapsed=100.7s

  [7013/21087] intraday_15466.csv.gz  in=295,690,661 out=50,576,582 elapsed=100.7s

  [7014/21087] intraday_1547.csv.gz  in=295,702,588 out=50,576,582 elapsed=100.8s

  [7015/21087] intraday_15468.csv.gz  in=295,713,397 out=50,587,391 elapsed=100.8s

  [7016/21087] intraday_15467.csv.gz  in=295,727,020 out=50,601,014 elapsed=100.8s

  [7017/21087] intraday_15469.csv.gz  in=295,739,689 out=50,613,683 elapsed=100.8s

  [7018/21087] intraday_15470.csv.gz  in=295,751,062 out=50,625,056 elapsed=100.8s

  [7019/21087] intraday_15472.csv.gz  in=295,759,207 out=50,633,201 elapsed=100.8s

  [7020/21087] intraday_15471.csv.gz  in=295,770,350 out=50,644,344 elapsed=100.8s

  [7021/21087] intraday_15473.csv.gz  in=295,782,834 out=50,656,828 elapsed=100.8s

  [7022/21087] intraday_15474.csv.gz  in=295,794,151 out=50,668,145 elapsed=100.8s

  [7023/21087] intraday_15475.csv.gz  in=295,805,015 out=50,679,009 elapsed=100.9s

  [7024/21087] intraday_15477.csv.gz  in=295,815,139 out=50,689,133 elapsed=100.9s

  [7025/21087] intraday_15476.csv.gz  in=295,824,408 out=50,698,394 elapsed=100.9s

  [7026/21087] intraday_15478.csv.gz  in=295,832,935 out=50,706,921 elapsed=100.9s

  [7027/21087] intraday_1548.csv.gz  in=295,844,971 out=50,706,921 elapsed=100.9s

  [7028/21087] intraday_15479.csv.gz  in=295,858,895 out=50,720,845 elapsed=100.9s

  [7029/21087] intraday_15480.csv.gz  in=295,870,349 out=50,732,299 elapsed=100.9s

  [7030/21087] intraday_15482.csv.gz  in=295,880,762 out=50,742,712 elapsed=100.9s

  [7031/21087] intraday_15481.csv.gz  in=295,896,575 out=50,755,835 elapsed=100.9s

  [7032/21087] intraday_15483.csv.gz  in=295,906,974 out=50,766,234 elapsed=101.0s

  [7033/21087] intraday_15484.csv.gz  in=295,917,638 out=50,776,898 elapsed=101.0s

  [7034/21087] intraday_15485.csv.gz  in=295,928,961 out=50,788,221 elapsed=101.0s

  [7035/21087] intraday_15486.csv.gz  in=295,944,813 out=50,804,073 elapsed=101.0s

  [7036/21087] intraday_1549.csv.gz  in=295,956,411 out=50,804,073 elapsed=101.0s

  [7037/21087] intraday_15488.csv.gz  in=295,969,755 out=50,817,417 elapsed=101.0s

  [7038/21087] intraday_15489.csv.gz  in=295,981,150 out=50,828,812 elapsed=101.0s

  [7039/21087] intraday_15487.csv.gz  in=295,992,768 out=50,840,430 elapsed=101.0s

  [7040/21087] intraday_15490.csv.gz  in=296,004,762 out=50,852,424 elapsed=101.0s

  [7041/21087] intraday_15492.csv.gz  in=296,017,940 out=50,865,602 elapsed=101.1s

  [7042/21087] intraday_15491.csv.gz  in=296,029,917 out=50,877,579 elapsed=101.1s

  [7043/21087] intraday_15493.csv.gz  in=296,040,128 out=50,887,790 elapsed=101.1s

  [7044/21087] intraday_15494.csv.gz  in=296,052,294 out=50,899,956 elapsed=101.1s

  [7045/21087] intraday_15495.csv.gz  in=296,063,280 out=50,910,942 elapsed=101.1s

  [7046/21087] intraday_15498.csv.gz  in=296,074,067 out=50,921,729 elapsed=101.1s

  [7047/21087] intraday_15497.csv.gz  in=296,086,780 out=50,934,442 elapsed=101.1s

  [7048/21087] intraday_15499.csv.gz  in=296,098,206 out=50,945,868 elapsed=101.1s

  [7049/21087] intraday_15496.csv.gz  in=296,108,617 out=50,956,279 elapsed=101.1s

  [7050/21087] intraday_15500.csv.gz  in=296,119,623 out=50,967,285 elapsed=101.2s

  [7051/21087] intraday_1550.csv.gz  in=296,153,846 out=50,967,285 elapsed=101.2s

  [7052/21087] intraday_15502.csv.gz  in=296,164,885 out=50,978,319 elapsed=101.2s

  [7053/21087] intraday_15501.csv.gz  in=296,175,578 out=50,989,012 elapsed=101.2s

  [7054/21087] intraday_15503.csv.gz  in=296,187,633 out=51,001,067 elapsed=101.2s

  [7055/21087] intraday_15505.csv.gz  in=296,198,568 out=51,012,002 elapsed=101.2s

  [7056/21087] intraday_15506.csv.gz  in=296,210,179 out=51,023,613 elapsed=101.2s

  [7057/21087] intraday_15507.csv.gz  in=296,219,148 out=51,032,582 elapsed=101.2s

  [7058/21087] intraday_15504.csv.gz  in=296,230,980 out=51,044,414 elapsed=101.2s

  [7059/21087] intraday_1551.csv.gz  in=296,241,893 out=51,044,414 elapsed=101.3s

  [7060/21087] intraday_15509.csv.gz  in=296,251,089 out=51,053,610 elapsed=101.3s

  [7061/21087] intraday_15510.csv.gz  in=296,265,677 out=51,066,163 elapsed=101.3s

  [7062/21087] intraday_15508.csv.gz  in=296,280,561 out=51,081,047 elapsed=101.3s

  [7063/21087] intraday_15511.csv.gz  in=296,292,948 out=51,093,434 elapsed=101.3s

  [7064/21087] intraday_15513.csv.gz  in=296,302,972 out=51,103,458 elapsed=101.4s

  [7065/21087] intraday_15512.csv.gz  in=296,316,584 out=51,117,070 elapsed=101.4s

  [7066/21087] intraday_15514.csv.gz  in=296,333,473 out=51,130,273 elapsed=101.4s

  [7067/21087] intraday_15515.csv.gz  in=296,346,390 out=51,143,190 elapsed=101.4s

  [7068/21087] intraday_15516.csv.gz  in=296,357,463 out=51,154,263 elapsed=101.4s

  [7069/21087] intraday_15517.csv.gz  in=296,369,953 out=51,166,753 elapsed=101.4s

  [7070/21087] intraday_1552.csv.gz  in=296,382,424 out=51,166,753 elapsed=101.4s

  [7071/21087] intraday_15518.csv.gz  in=296,396,204 out=51,180,533 elapsed=101.4s

  [7072/21087] intraday_15519.csv.gz  in=296,413,467 out=51,197,796 elapsed=101.4s

  [7073/21087] intraday_15523.csv.gz  in=296,425,241 out=51,209,570 elapsed=101.5s

  [7074/21087] intraday_15521.csv.gz  in=296,438,675 out=51,223,004 elapsed=101.5s

  [7075/21087] intraday_15520.csv.gz  in=296,452,247 out=51,236,576 elapsed=101.5s

  [7076/21087] intraday_15522.csv.gz  in=296,462,871 out=51,247,200 elapsed=101.5s

  [7077/21087] intraday_15524.csv.gz  in=296,471,353 out=51,255,682 elapsed=101.5s

  [7078/21087] intraday_15526.csv.gz  in=296,481,236 out=51,265,565 elapsed=101.5s

  [7079/21087] intraday_15525.csv.gz  in=296,493,893 out=51,278,222 elapsed=101.5s

  [7080/21087] intraday_15527.csv.gz  in=296,505,598 out=51,289,927 elapsed=101.5s

  [7081/21087] intraday_1553.csv.gz  in=296,517,411 out=51,289,927 elapsed=101.6s

  [7082/21087] intraday_15528.csv.gz  in=296,529,480 out=51,301,996 elapsed=101.6s

  [7083/21087] intraday_15530.csv.gz  in=296,540,532 out=51,313,048 elapsed=101.6s

  [7084/21087] intraday_15529.csv.gz  in=296,555,007 out=51,327,523 elapsed=101.6s

  [7085/21087] intraday_15531.csv.gz  in=296,565,497 out=51,338,013 elapsed=101.6s

  [7086/21087] intraday_15532.csv.gz  in=296,576,215 out=51,348,731 elapsed=101.6s

  [7087/21087] intraday_15533.csv.gz  in=296,588,541 out=51,361,057 elapsed=101.6s

  [7088/21087] intraday_15534.csv.gz  in=296,599,144 out=51,371,660 elapsed=101.6s

  [7089/21087] intraday_15535.csv.gz  in=296,611,538 out=51,384,054 elapsed=101.6s

  [7090/21087] intraday_15536.csv.gz  in=296,625,074 out=51,397,590 elapsed=101.6s

  [7091/21087] intraday_15537.csv.gz  in=296,636,450 out=51,408,966 elapsed=101.6s

  [7092/21087] intraday_1554.csv.gz  in=296,648,248 out=51,408,966 elapsed=101.7s

  [7093/21087] intraday_15538.csv.gz  in=296,663,188 out=51,423,906 elapsed=101.7s

  [7094/21087] intraday_15539.csv.gz  in=296,672,499 out=51,433,217 elapsed=101.7s

  [7095/21087] intraday_15540.csv.gz  in=296,683,872 out=51,444,590 elapsed=101.7s

  [7096/21087] intraday_15541.csv.gz  in=296,696,458 out=51,457,176 elapsed=101.7s

  [7097/21087] intraday_15543.csv.gz  in=296,707,420 out=51,468,138 elapsed=101.7s

  [7098/21087] intraday_15544.csv.gz  in=296,714,728 out=51,475,446 elapsed=101.7s

  [7099/21087] intraday_15542.csv.gz  in=296,732,050 out=51,488,065 elapsed=101.7s

  [7100/21087] intraday_15545.csv.gz  in=296,742,016 out=51,498,031 elapsed=101.7s

  [7101/21087] intraday_15546.csv.gz  in=296,750,049 out=51,506,064 elapsed=101.8s

  [7102/21087] intraday_15548.csv.gz  in=296,762,312 out=51,518,327 elapsed=101.8s

  [7103/21087] intraday_15547.csv.gz  in=296,778,406 out=51,534,421 elapsed=101.8s

  [7104/21087] intraday_1555.csv.gz  in=296,791,221 out=51,534,421 elapsed=101.8s

  [7105/21087] intraday_15549.csv.gz  in=296,803,987 out=51,547,187 elapsed=101.8s

  [7106/21087] intraday_15552.csv.gz  in=296,818,238 out=51,561,438 elapsed=101.8s

  [7107/21087] intraday_15550.csv.gz  in=296,829,324 out=51,572,524 elapsed=101.8s

  [7108/21087] intraday_15551.csv.gz  in=296,841,389 out=51,584,589 elapsed=101.8s

  [7109/21087] intraday_15553.csv.gz  in=296,854,867 out=51,598,067 elapsed=101.8s

  [7110/21087] intraday_15554.csv.gz  in=296,865,910 out=51,609,110 elapsed=101.9s

  [7111/21087] intraday_15556.csv.gz  in=296,878,445 out=51,621,645 elapsed=101.9s

  [7112/21087] intraday_15557.csv.gz  in=296,889,631 out=51,632,831 elapsed=101.9s

  [7113/21087] intraday_15555.csv.gz  in=296,904,679 out=51,647,879 elapsed=101.9s

  [7114/21087] intraday_1556.csv.gz  in=296,916,690 out=51,647,879 elapsed=101.9s

  [7115/21087] intraday_15560.csv.gz  in=296,929,680 out=51,660,869 elapsed=101.9s

  [7116/21087] intraday_15559.csv.gz  in=296,945,450 out=51,675,350 elapsed=101.9s

  [7117/21087] intraday_15558.csv.gz  in=296,958,115 out=51,688,015 elapsed=101.9s

  [7118/21087] intraday_15561.csv.gz  in=296,968,825 out=51,698,725 elapsed=101.9s

  [7119/21087] intraday_15562.csv.gz  in=296,979,327 out=51,709,227 elapsed=102.0s

  [7120/21087] intraday_15563.csv.gz  in=296,994,568 out=51,724,468 elapsed=102.0s

  [7121/21087] intraday_15564.csv.gz  in=297,009,051 out=51,738,951 elapsed=102.0s

  [7122/21087] intraday_15566.csv.gz  in=297,020,794 out=51,750,694 elapsed=102.0s

  [7123/21087] intraday_15565.csv.gz  in=297,032,071 out=51,761,971 elapsed=102.0s

  [7124/21087] intraday_1557.csv.gz  in=297,045,068 out=51,761,971 elapsed=102.0s

  [7125/21087] intraday_15568.csv.gz  in=297,057,363 out=51,774,266 elapsed=102.0s

  [7126/21087] intraday_15569.csv.gz  in=297,070,825 out=51,787,728 elapsed=102.0s

  [7127/21087] intraday_15567.csv.gz  in=297,103,849 out=51,812,348 elapsed=102.1s

  [7128/21087] intraday_15570.csv.gz  in=297,115,804 out=51,824,303 elapsed=102.1s

  [7129/21087] intraday_15571.csv.gz  in=297,128,154 out=51,836,653 elapsed=102.1s

  [7130/21087] intraday_15572.csv.gz  in=297,139,999 out=51,848,498 elapsed=102.1s

  [7131/21087] intraday_15573.csv.gz  in=297,150,118 out=51,858,617 elapsed=102.1s

  [7132/21087] intraday_15574.csv.gz  in=297,161,939 out=51,870,438 elapsed=102.1s

  [7133/21087] intraday_15575.csv.gz  in=297,174,351 out=51,882,850 elapsed=102.1s

  [7134/21087] intraday_15576.csv.gz  in=297,188,418 out=51,896,334 elapsed=102.1s

  [7135/21087] intraday_15577.csv.gz  in=297,203,749 out=51,911,630 elapsed=102.1s

  [7136/21087] intraday_15578.csv.gz  in=297,216,771 out=51,924,652 elapsed=102.1s

  [7137/21087] intraday_15579.csv.gz  in=297,227,567 out=51,935,448 elapsed=102.1s

  [7138/21087] intraday_1558.csv.gz  in=297,240,157 out=51,935,448 elapsed=102.2s

  [7139/21087] intraday_15580.csv.gz  in=297,252,356 out=51,947,647 elapsed=102.2s

  [7140/21087] intraday_15582.csv.gz  in=297,264,562 out=51,959,853 elapsed=102.2s

  [7141/21087] intraday_15581.csv.gz  in=297,277,776 out=51,973,067 elapsed=102.2s

  [7142/21087] intraday_15583.csv.gz  in=297,290,650 out=51,985,941 elapsed=102.2s

  [7143/21087] intraday_15584.csv.gz  in=297,299,812 out=51,995,103 elapsed=102.2s

  [7144/21087] intraday_15585.csv.gz  in=297,311,884 out=52,007,175 elapsed=102.2s

  [7145/21087] intraday_15586.csv.gz  in=297,321,045 out=52,016,336 elapsed=102.2s

  [7146/21087] intraday_15587.csv.gz  in=297,332,509 out=52,027,800 elapsed=102.2s

  [7147/21087] intraday_15588.csv.gz  in=297,344,404 out=52,039,695 elapsed=102.2s

  [7148/21087] intraday_1559.csv.gz  in=297,359,507 out=52,039,695 elapsed=102.3s

  [7149/21087] intraday_15589.csv.gz  in=297,373,983 out=52,054,171 elapsed=102.3s

  [7150/21087] intraday_15590.csv.gz  in=297,385,194 out=52,065,382 elapsed=102.3s

  [7151/21087] intraday_15592.csv.gz  in=297,397,494 out=52,077,682 elapsed=102.3s

  [7152/21087] intraday_15591.csv.gz  in=297,412,930 out=52,092,586 elapsed=102.3s

  [7153/21087] intraday_15593.csv.gz  in=297,424,598 out=52,104,254 elapsed=102.3s

  [7154/21087] intraday_15594.csv.gz  in=297,436,543 out=52,116,199 elapsed=102.3s

  [7155/21087] intraday_15595.csv.gz  in=297,448,550 out=52,128,206 elapsed=102.3s

  [7156/21087] intraday_15596.csv.gz  in=297,460,215 out=52,139,871 elapsed=102.3s

  [7157/21087] intraday_15597.csv.gz  in=297,469,976 out=52,149,632 elapsed=102.3s

  [7158/21087] intraday_15598.csv.gz  in=297,482,559 out=52,162,215 elapsed=102.3s

  [7159/21087] intraday_15599.csv.gz  in=297,495,618 out=52,175,274 elapsed=102.4s

  [7160/21087] intraday_1560.csv.gz  in=297,506,766 out=52,175,274 elapsed=102.4s

  [7161/21087] intraday_15601.csv.gz  in=297,518,980 out=52,187,488 elapsed=102.4s

  [7162/21087] intraday_15603.csv.gz  in=297,530,190 out=52,198,698 elapsed=102.4s

  [7163/21087] intraday_15602.csv.gz  in=297,543,631 out=52,212,139 elapsed=102.4s

  [7164/21087] intraday_15600.csv.gz  in=297,557,269 out=52,225,777 elapsed=102.4s

  [7165/21087] intraday_15604.csv.gz  in=297,567,683 out=52,236,191 elapsed=102.4s

  [7166/21087] intraday_15605.csv.gz  in=297,579,002 out=52,247,510 elapsed=102.4s

  [7167/21087] intraday_15606.csv.gz  in=297,592,545 out=52,261,053 elapsed=102.4s

  [7168/21087] intraday_15607.csv.gz  in=297,607,384 out=52,275,892 elapsed=102.5s

  [7169/21087] intraday_15608.csv.gz  in=297,618,981 out=52,287,489 elapsed=102.5s

  [7170/21087] intraday_15609.csv.gz  in=297,630,556 out=52,299,064 elapsed=102.5s

  [7171/21087] intraday_1561.csv.gz  in=297,644,391 out=52,299,064 elapsed=102.5s

  [7172/21087] intraday_15610.csv.gz  in=297,655,541 out=52,310,214 elapsed=102.5s

  [7173/21087] intraday_15611.csv.gz  in=297,668,812 out=52,323,485 elapsed=102.5s

  [7174/21087] intraday_15612.csv.gz  in=297,682,125 out=52,336,798 elapsed=102.5s

  [7175/21087] intraday_15613.csv.gz  in=297,695,873 out=52,350,546 elapsed=102.5s

  [7176/21087] intraday_15614.csv.gz  in=297,708,132 out=52,362,805 elapsed=102.5s

  [7177/21087] intraday_15615.csv.gz  in=297,720,656 out=52,375,329 elapsed=102.6s

  [7178/21087] intraday_15616.csv.gz  in=297,733,228 out=52,387,769 elapsed=102.6s

  [7179/21087] intraday_15618.csv.gz  in=297,746,175 out=52,400,716 elapsed=102.6s

  [7180/21087] intraday_15617.csv.gz  in=297,757,888 out=52,412,429 elapsed=102.6s

  [7181/21087] intraday_1562.csv.gz  in=297,768,524 out=52,412,429 elapsed=102.6s

  [7182/21087] intraday_15619.csv.gz  in=297,780,138 out=52,424,043 elapsed=102.7s

  [7183/21087] intraday_15620.csv.gz  in=297,791,383 out=52,435,288 elapsed=102.7s

  [7184/21087] intraday_15621.csv.gz  in=297,801,997 out=52,445,902 elapsed=102.7s

  [7185/21087] intraday_15622.csv.gz  in=297,812,559 out=52,456,464 elapsed=102.7s

  [7186/21087] intraday_15623.csv.gz  in=297,824,841 out=52,468,746 elapsed=102.7s

  [7187/21087] intraday_15624.csv.gz  in=297,839,035 out=52,482,940 elapsed=102.7s

  [7188/21087] intraday_15626.csv.gz  in=297,850,082 out=52,493,987 elapsed=102.7s

  [7189/21087] intraday_15625.csv.gz  in=297,861,286 out=52,505,191 elapsed=102.7s

  [7190/21087] intraday_15627.csv.gz  in=297,870,724 out=52,514,629 elapsed=102.8s

  [7191/21087] intraday_15629.csv.gz  in=297,883,163 out=52,527,068 elapsed=102.8s

  [7192/21087] intraday_15628.csv.gz  in=297,894,750 out=52,538,655 elapsed=102.8s

  [7193/21087] intraday_1563.csv.gz  in=297,906,799 out=52,538,655 elapsed=102.8s

  [7194/21087] intraday_15630.csv.gz  in=297,920,588 out=52,552,444 elapsed=102.8s

  [7195/21087] intraday_15632.csv.gz  in=297,933,836 out=52,565,692 elapsed=102.8s

  [7196/21087] intraday_15631.csv.gz  in=297,947,813 out=52,579,669 elapsed=102.8s

  [7197/21087] intraday_15633.csv.gz  in=297,959,750 out=52,591,606 elapsed=102.8s

  [7198/21087] intraday_15634.csv.gz  in=297,972,038 out=52,603,894 elapsed=102.8s

  [7199/21087] intraday_15635.csv.gz  in=297,984,305 out=52,616,161 elapsed=102.9s

  [7200/21087] intraday_15638.csv.gz  in=297,995,839 out=52,627,695 elapsed=102.9s

  [7201/21087] intraday_15636.csv.gz  in=298,011,182 out=52,643,038 elapsed=102.9s

  [7202/21087] intraday_15637.csv.gz  in=298,023,905 out=52,655,761 elapsed=102.9s

  [7203/21087] intraday_15639.csv.gz  in=298,036,733 out=52,668,589 elapsed=102.9s

  [7204/21087] intraday_1564.csv.gz  in=298,049,340 out=52,668,589 elapsed=102.9s

  [7205/21087] intraday_15640.csv.gz  in=298,061,326 out=52,680,575 elapsed=102.9s

  [7206/21087] intraday_15642.csv.gz  in=298,074,238 out=52,693,487 elapsed=102.9s

  [7207/21087] intraday_15641.csv.gz  in=298,086,622 out=52,705,871 elapsed=102.9s

  [7208/21087] intraday_15643.csv.gz  in=298,099,389 out=52,718,638 elapsed=103.0s

  [7209/21087] intraday_15644.csv.gz  in=298,110,577 out=52,729,826 elapsed=103.0s

  [7210/21087] intraday_15645.csv.gz  in=298,122,504 out=52,741,753 elapsed=103.0s

  [7211/21087] intraday_15646.csv.gz  in=298,133,962 out=52,753,211 elapsed=103.0s

  [7212/21087] intraday_15647.csv.gz  in=298,145,395 out=52,764,644 elapsed=103.0s

  [7213/21087] intraday_15648.csv.gz  in=298,160,472 out=52,778,954 elapsed=103.0s

  [7214/21087] intraday_1565.csv.gz  in=298,170,752 out=52,778,954 elapsed=103.0s

  [7215/21087] intraday_15649.csv.gz  in=298,184,752 out=52,792,954 elapsed=103.0s

  [7216/21087] intraday_15650.csv.gz  in=298,196,632 out=52,804,834 elapsed=103.0s

  [7217/21087] intraday_15652.csv.gz  in=298,206,589 out=52,814,791 elapsed=103.1s

  [7218/21087] intraday_15654.csv.gz  in=298,217,526 out=52,825,728 elapsed=103.1s

  [7219/21087] intraday_15651.csv.gz  in=298,229,282 out=52,837,484 elapsed=103.1s

  [7220/21087] intraday_15653.csv.gz  in=298,244,943 out=52,853,145 elapsed=103.1s

  [7221/21087] intraday_15655.csv.gz  in=298,257,523 out=52,865,725 elapsed=103.1s

  [7222/21087] intraday_15656.csv.gz  in=298,269,357 out=52,877,559 elapsed=103.1s

  [7223/21087] intraday_15659.csv.gz  in=298,284,351 out=52,892,553 elapsed=103.1s

  [7224/21087] intraday_15657.csv.gz  in=298,298,322 out=52,906,524 elapsed=103.1s

  [7225/21087] intraday_1566.csv.gz  in=298,311,671 out=52,906,524 elapsed=103.1s

  [7226/21087] intraday_15658.csv.gz  in=298,323,754 out=52,918,607 elapsed=103.1s

  [7227/21087] intraday_15661.csv.gz  in=298,333,839 out=52,928,692 elapsed=103.2s

  [7228/21087] intraday_15660.csv.gz  in=298,347,951 out=52,942,804 elapsed=103.2s

  [7229/21087] intraday_15662.csv.gz  in=298,362,117 out=52,956,970 elapsed=103.2s

  [7230/21087] intraday_15663.csv.gz  in=298,378,489 out=52,973,342 elapsed=103.2s

  [7231/21087] intraday_15664.csv.gz  in=298,393,945 out=52,988,798 elapsed=103.2s

  [7232/21087] intraday_15666.csv.gz  in=298,405,836 out=53,000,689 elapsed=103.2s

  [7233/21087] intraday_15667.csv.gz  in=298,418,146 out=53,012,999 elapsed=103.3s

  [7234/21087] intraday_15665.csv.gz  in=298,433,107 out=53,027,960 elapsed=103.3s

  [7235/21087] intraday_15668.csv.gz  in=298,445,145 out=53,039,998 elapsed=103.3s

  [7236/21087] intraday_15669.csv.gz  in=298,455,495 out=53,050,348 elapsed=103.3s

  [7237/21087] intraday_1567.csv.gz  in=298,470,681 out=53,050,348 elapsed=103.3s

  [7238/21087] intraday_15671.csv.gz  in=298,481,486 out=53,061,153 elapsed=103.3s

  [7239/21087] intraday_15670.csv.gz  in=298,493,400 out=53,073,067 elapsed=103.3s

  [7240/21087] intraday_15672.csv.gz  in=298,508,227 out=53,087,148 elapsed=103.3s

  [7241/21087] intraday_15673.csv.gz  in=298,520,562 out=53,099,483 elapsed=103.3s

  [7242/21087] intraday_15674.csv.gz  in=298,534,402 out=53,113,323 elapsed=103.3s

  [7243/21087] intraday_15676.csv.gz  in=298,545,477 out=53,124,398 elapsed=103.4s

  [7244/21087] intraday_15675.csv.gz  in=298,556,789 out=53,135,710 elapsed=103.4s

  [7245/21087] intraday_15677.csv.gz  in=298,570,067 out=53,148,988 elapsed=103.4s

  [7246/21087] intraday_15678.csv.gz  in=298,581,658 out=53,160,579 elapsed=103.4s

  [7247/21087] intraday_1568.csv.gz  in=298,593,713 out=53,160,579 elapsed=103.4s

  [7248/21087] intraday_15679.csv.gz  in=298,605,987 out=53,172,853 elapsed=103.4s

  [7249/21087] intraday_15680.csv.gz  in=298,619,380 out=53,186,246 elapsed=103.4s

  [7250/21087] intraday_15681.csv.gz  in=298,632,828 out=53,199,694 elapsed=103.4s

  [7251/21087] intraday_15682.csv.gz  in=298,645,398 out=53,212,264 elapsed=103.4s

  [7252/21087] intraday_15683.csv.gz  in=298,659,464 out=53,226,330 elapsed=103.4s

  [7253/21087] intraday_15685.csv.gz  in=298,671,479 out=53,238,345 elapsed=103.4s

  [7254/21087] intraday_15684.csv.gz  in=298,684,482 out=53,251,348 elapsed=103.4s

  [7255/21087] intraday_15686.csv.gz  in=298,697,001 out=53,263,867 elapsed=103.5s

  [7256/21087] intraday_15687.csv.gz  in=298,708,557 out=53,275,423 elapsed=103.5s

  [7257/21087] intraday_15688.csv.gz  in=298,718,649 out=53,285,515 elapsed=103.5s

  [7258/21087] intraday_15689.csv.gz  in=298,727,764 out=53,294,630 elapsed=103.5s

  [7259/21087] intraday_1569.csv.gz  in=298,739,453 out=53,294,630 elapsed=103.5s

  [7260/21087] intraday_15690.csv.gz  in=298,749,252 out=53,304,429 elapsed=103.5s

  [7261/21087] intraday_15691.csv.gz  in=298,754,613 out=53,309,790 elapsed=103.5s

  [7262/21087] intraday_15692.csv.gz  in=298,770,319 out=53,317,740 elapsed=103.5s

  [7263/21087] intraday_15693.csv.gz  in=298,786,712 out=53,334,133 elapsed=103.6s

  [7264/21087] intraday_15695.csv.gz  in=298,798,839 out=53,346,260 elapsed=103.6s

  [7265/21087] intraday_15694.csv.gz  in=298,813,227 out=53,360,648 elapsed=103.6s

  [7266/21087] intraday_15696.csv.gz  in=298,824,905 out=53,372,326 elapsed=103.6s

  [7267/21087] intraday_15697.csv.gz  in=298,836,557 out=53,383,978 elapsed=103.6s

  [7268/21087] intraday_1570.csv.gz  in=298,849,264 out=53,383,978 elapsed=103.6s

  [7269/21087] intraday_15698.csv.gz  in=298,863,703 out=53,398,417 elapsed=103.6s

  [7270/21087] intraday_15699.csv.gz  in=298,876,349 out=53,411,063 elapsed=103.6s

  [7271/21087] intraday_15700.csv.gz  in=298,887,229 out=53,421,943 elapsed=103.6s

  [7272/21087] intraday_15701.csv.gz  in=298,899,242 out=53,433,956 elapsed=103.6s

  [7273/21087] intraday_15703.csv.gz  in=298,910,457 out=53,445,171 elapsed=103.6s

  [7274/21087] intraday_15702.csv.gz  in=298,923,042 out=53,457,756 elapsed=103.6s

  [7275/21087] intraday_15704.csv.gz  in=298,938,602 out=53,471,636 elapsed=103.7s

  [7276/21087] intraday_15705.csv.gz  in=298,951,874 out=53,484,908 elapsed=103.7s

  [7277/21087] intraday_15707.csv.gz  in=298,961,808 out=53,494,842 elapsed=103.7s

  [7278/21087] intraday_15706.csv.gz  in=298,974,015 out=53,507,049 elapsed=103.7s

  [7279/21087] intraday_15708.csv.gz  in=298,983,562 out=53,516,596 elapsed=103.7s

  [7280/21087] intraday_1571.csv.gz  in=298,996,045 out=53,516,596 elapsed=103.7s

  [7281/21087] intraday_15709.csv.gz  in=299,011,772 out=53,532,323 elapsed=103.7s

  [7282/21087] intraday_15710.csv.gz  in=299,025,104 out=53,545,655 elapsed=103.7s

  [7283/21087] intraday_15711.csv.gz  in=299,036,006 out=53,556,557 elapsed=103.7s

  [7284/21087] intraday_15712.csv.gz  in=299,048,379 out=53,568,677 elapsed=103.7s

  [7285/21087] intraday_15713.csv.gz  in=299,059,452 out=53,579,750 elapsed=103.7s

  [7286/21087] intraday_15714.csv.gz  in=299,071,664 out=53,591,962 elapsed=103.8s

  [7287/21087] intraday_15715.csv.gz  in=299,086,788 out=53,605,887 elapsed=103.8s

  [7288/21087] intraday_15716.csv.gz  in=299,098,770 out=53,617,869 elapsed=103.8s

  [7289/21087] intraday_15717.csv.gz  in=299,111,310 out=53,630,409 elapsed=103.8s

  [7290/21087] intraday_15718.csv.gz  in=299,122,564 out=53,641,663 elapsed=103.8s

  [7291/21087] intraday_15719.csv.gz  in=299,132,328 out=53,651,427 elapsed=103.8s

  [7292/21087] intraday_1572.csv.gz  in=299,143,858 out=53,651,427 elapsed=103.8s

  [7293/21087] intraday_15720.csv.gz  in=299,155,074 out=53,662,643 elapsed=103.8s

  [7294/21087] intraday_15722.csv.gz  in=299,166,681 out=53,674,250 elapsed=103.8s

  [7295/21087] intraday_15721.csv.gz  in=299,179,483 out=53,687,052 elapsed=103.9s

  [7296/21087] intraday_15723.csv.gz  in=299,195,575 out=53,703,144 elapsed=103.9s

  [7297/21087] intraday_15724.csv.gz  in=299,208,277 out=53,715,846 elapsed=103.9s

  [7298/21087] intraday_15725.csv.gz  in=299,218,345 out=53,725,914 elapsed=103.9s

  [7299/21087] intraday_15726.csv.gz  in=299,230,252 out=53,737,821 elapsed=103.9s

  [7300/21087] intraday_15728.csv.gz  in=299,242,207 out=53,749,776 elapsed=103.9s

  [7301/21087] intraday_15727.csv.gz  in=299,254,548 out=53,762,117 elapsed=103.9s

  [7302/21087] intraday_1573.csv.gz  in=299,267,390 out=53,762,117 elapsed=103.9s

  [7303/21087] intraday_15729.csv.gz  in=299,281,089 out=53,775,816 elapsed=103.9s

  [7304/21087] intraday_15730.csv.gz  in=299,290,131 out=53,784,858 elapsed=103.9s

  [7305/21087] intraday_15731.csv.gz  in=299,301,711 out=53,796,438 elapsed=103.9s

  [7306/21087] intraday_15732.csv.gz  in=299,310,610 out=53,805,337 elapsed=104.0s

  [7307/21087] intraday_15733.csv.gz  in=299,321,552 out=53,816,279 elapsed=104.0s

  [7308/21087] intraday_15735.csv.gz  in=299,335,197 out=53,829,924 elapsed=104.0s

  [7309/21087] intraday_15736.csv.gz  in=299,347,442 out=53,842,169 elapsed=104.0s

  [7310/21087] intraday_15734.csv.gz  in=299,364,904 out=53,856,492 elapsed=104.0s

  [7311/21087] intraday_15737.csv.gz  in=299,378,408 out=53,869,996 elapsed=104.0s

  [7312/21087] intraday_15739.csv.gz  in=299,389,935 out=53,881,523 elapsed=104.1s

  [7313/21087] intraday_15738.csv.gz  in=299,401,110 out=53,892,698 elapsed=104.1s

  [7314/21087] intraday_15740.csv.gz  in=299,412,058 out=53,903,646 elapsed=104.1s

  [7315/21087] intraday_1574.csv.gz  in=299,424,930 out=53,903,646 elapsed=104.1s

  [7316/21087] intraday_15742.csv.gz  in=299,436,295 out=53,915,011 elapsed=104.1s

  [7317/21087] intraday_15741.csv.gz  in=299,447,438 out=53,926,154 elapsed=104.1s

  [7318/21087] intraday_15743.csv.gz  in=299,458,802 out=53,937,518 elapsed=104.1s

  [7319/21087] intraday_15744.csv.gz  in=299,471,934 out=53,950,650 elapsed=104.1s

  [7320/21087] intraday_15745.csv.gz  in=299,484,408 out=53,963,124 elapsed=104.2s

  [7321/21087] intraday_15746.csv.gz  in=299,497,726 out=53,976,442 elapsed=104.2s

  [7322/21087] intraday_15747.csv.gz  in=299,511,126 out=53,989,842 elapsed=104.2s

  [7323/21087] intraday_15748.csv.gz  in=299,523,593 out=54,002,309 elapsed=104.2s

  [7324/21087] intraday_15749.csv.gz  in=299,534,657 out=54,013,373 elapsed=104.2s

  [7325/21087] intraday_1575.csv.gz  in=299,561,592 out=54,013,373 elapsed=104.2s

  [7326/21087] intraday_15751.csv.gz  in=299,573,831 out=54,025,612 elapsed=104.2s

  [7327/21087] intraday_15752.csv.gz  in=299,587,079 out=54,038,860 elapsed=104.3s

  [7328/21087] intraday_15750.csv.gz  in=299,616,168 out=54,058,601 elapsed=104.3s

  [7329/21087] intraday_15753.csv.gz  in=299,627,094 out=54,069,527 elapsed=104.3s

  [7330/21087] intraday_15754.csv.gz  in=299,638,980 out=54,081,413 elapsed=104.3s

  [7331/21087] intraday_15755.csv.gz  in=299,650,102 out=54,092,535 elapsed=104.3s

  [7332/21087] intraday_15757.csv.gz  in=299,662,944 out=54,105,377 elapsed=104.3s

  [7333/21087] intraday_15756.csv.gz  in=299,673,569 out=54,116,002 elapsed=104.3s

  [7334/21087] intraday_15758.csv.gz  in=299,689,025 out=54,131,458 elapsed=104.3s

  [7335/21087] intraday_1576.csv.gz  in=299,701,691 out=54,131,458 elapsed=104.3s

  [7336/21087] intraday_15759.csv.gz  in=299,714,271 out=54,144,038 elapsed=104.3s

  [7337/21087] intraday_15760.csv.gz  in=299,726,462 out=54,156,229 elapsed=104.3s

  [7338/21087] intraday_15762.csv.gz  in=299,734,986 out=54,164,753 elapsed=104.3s

  [7339/21087] intraday_15761.csv.gz  in=299,751,731 out=54,179,834 elapsed=104.4s

  [7340/21087] intraday_15764.csv.gz  in=299,764,613 out=54,192,716 elapsed=104.4s

  [7341/21087] intraday_15763.csv.gz  in=299,775,950 out=54,204,053 elapsed=104.4s

  [7342/21087] intraday_15765.csv.gz  in=299,786,536 out=54,214,639 elapsed=104.4s

  [7343/21087] intraday_15766.csv.gz  in=299,798,159 out=54,226,262 elapsed=104.4s

  [7344/21087] intraday_15767.csv.gz  in=299,810,198 out=54,238,301 elapsed=104.4s

  [7345/21087] intraday_15768.csv.gz  in=299,820,541 out=54,248,644 elapsed=104.4s

  [7346/21087] intraday_15769.csv.gz  in=299,831,604 out=54,259,707 elapsed=104.4s

  [7347/21087] intraday_1577.csv.gz  in=299,843,921 out=54,259,707 elapsed=104.4s

  [7348/21087] intraday_15770.csv.gz  in=299,857,592 out=54,273,378 elapsed=104.4s

  [7349/21087] intraday_15773.csv.gz  in=299,867,757 out=54,283,543 elapsed=104.5s

  [7350/21087] intraday_15771.csv.gz  in=299,878,496 out=54,294,282 elapsed=104.5s

  [7351/21087] intraday_15772.csv.gz  in=299,891,019 out=54,306,805 elapsed=104.5s

  [7352/21087] intraday_15774.csv.gz  in=299,902,622 out=54,318,408 elapsed=104.5s

  [7353/21087] intraday_15775.csv.gz  in=299,915,044 out=54,330,830 elapsed=104.5s

  [7354/21087] intraday_15777.csv.gz  in=299,929,484 out=54,345,270 elapsed=104.5s

  [7355/21087] intraday_15776.csv.gz  in=299,943,381 out=54,359,167 elapsed=104.5s

  [7356/21087] intraday_15778.csv.gz  in=299,956,661 out=54,372,447 elapsed=104.5s

  [7357/21087] intraday_15779.csv.gz  in=299,968,997 out=54,384,783 elapsed=104.5s

  [7358/21087] intraday_1578.csv.gz  in=299,978,410 out=54,384,783 elapsed=104.5s

  [7359/21087] intraday_15780.csv.gz  in=299,990,646 out=54,397,019 elapsed=104.6s

  [7360/21087] intraday_15782.csv.gz  in=300,005,033 out=54,411,381 elapsed=104.6s

  [7361/21087] intraday_15781.csv.gz  in=300,016,545 out=54,422,887 elapsed=104.6s

  [7362/21087] intraday_15783.csv.gz  in=300,027,272 out=54,433,614 elapsed=104.6s

  [7363/21087] intraday_15784.csv.gz  in=300,039,287 out=54,445,629 elapsed=104.6s

  [7364/21087] intraday_15786.csv.gz  in=300,051,170 out=54,457,512 elapsed=104.6s

  [7365/21087] intraday_15785.csv.gz  in=300,065,025 out=54,471,367 elapsed=104.6s

  [7366/21087] intraday_15787.csv.gz  in=300,076,970 out=54,483,312 elapsed=104.6s

  [7367/21087] intraday_15788.csv.gz  in=300,088,654 out=54,494,996 elapsed=104.6s

  [7368/21087] intraday_1579.csv.gz  in=300,100,885 out=54,494,996 elapsed=104.6s

  [7369/21087] intraday_15789.csv.gz  in=300,114,268 out=54,508,379 elapsed=104.7s

  [7370/21087] intraday_15790.csv.gz  in=300,125,592 out=54,519,703 elapsed=104.7s

  [7371/21087] intraday_15791.csv.gz  in=300,137,049 out=54,531,160 elapsed=104.7s

  [7372/21087] intraday_15792.csv.gz  in=300,148,122 out=54,542,233 elapsed=104.7s

  [7373/21087] intraday_15793.csv.gz  in=300,159,957 out=54,554,068 elapsed=104.7s

  [7374/21087] intraday_15794.csv.gz  in=300,174,171 out=54,567,381 elapsed=104.7s

  [7375/21087] intraday_15795.csv.gz  in=300,187,010 out=54,580,220 elapsed=104.7s

  [7376/21087] intraday_15796.csv.gz  in=300,199,265 out=54,592,475 elapsed=104.7s

  [7377/21087] intraday_15797.csv.gz  in=300,211,504 out=54,604,714 elapsed=104.7s

  [7378/21087] intraday_15798.csv.gz  in=300,221,173 out=54,614,383 elapsed=104.7s

  [7379/21087] intraday_1580.csv.gz  in=300,234,779 out=54,614,383 elapsed=104.8s

  [7380/21087] intraday_15799.csv.gz  in=300,250,520 out=54,630,124 elapsed=104.8s

  [7381/21087] intraday_15800.csv.gz  in=300,261,451 out=54,641,055 elapsed=104.8s

  [7382/21087] intraday_15801.csv.gz  in=300,273,200 out=54,652,804 elapsed=104.8s

  [7383/21087] intraday_15802.csv.gz  in=300,285,951 out=54,665,555 elapsed=104.8s

  [7384/21087] intraday_15803.csv.gz  in=300,300,214 out=54,679,818 elapsed=104.8s

  [7385/21087] intraday_15804.csv.gz  in=300,311,235 out=54,690,839 elapsed=104.8s

  [7386/21087] intraday_15806.csv.gz  in=300,324,464 out=54,704,068 elapsed=104.8s

  [7387/21087] intraday_15805.csv.gz  in=300,339,440 out=54,719,044 elapsed=104.8s

  [7388/21087] intraday_15807.csv.gz  in=300,352,400 out=54,732,004 elapsed=104.8s

  [7389/21087] intraday_15808.csv.gz  in=300,364,770 out=54,744,374 elapsed=104.9s

  [7390/21087] intraday_1581.csv.gz  in=300,375,332 out=54,744,374 elapsed=104.9s

  [7391/21087] intraday_15809.csv.gz  in=300,391,515 out=54,760,557 elapsed=104.9s

  [7392/21087] intraday_15810.csv.gz  in=300,408,568 out=54,777,610 elapsed=104.9s

  [7393/21087] intraday_15811.csv.gz  in=300,422,809 out=54,791,851 elapsed=104.9s

  [7394/21087] intraday_15812.csv.gz  in=300,435,710 out=54,804,752 elapsed=104.9s

  [7395/21087] intraday_15813.csv.gz  in=300,448,750 out=54,817,792 elapsed=104.9s

  [7396/21087] intraday_15814.csv.gz  in=300,461,993 out=54,831,035 elapsed=104.9s

  [7397/21087] intraday_15815.csv.gz  in=300,471,193 out=54,840,235 elapsed=104.9s

  [7398/21087] intraday_15816.csv.gz  in=300,483,556 out=54,852,598 elapsed=104.9s

  [7399/21087] intraday_15817.csv.gz  in=300,494,225 out=54,863,267 elapsed=105.0s

  [7400/21087] intraday_15818.csv.gz  in=300,506,600 out=54,875,642 elapsed=105.0s

  [7401/21087] intraday_15819.csv.gz  in=300,519,724 out=54,888,766 elapsed=105.0s

  [7402/21087] intraday_1582.csv.gz  in=300,533,718 out=54,888,766 elapsed=105.0s

  [7403/21087] intraday_15820.csv.gz  in=300,547,598 out=54,902,646 elapsed=105.0s

  [7404/21087] intraday_15822.csv.gz  in=300,560,723 out=54,915,771 elapsed=105.0s

  [7405/21087] intraday_15821.csv.gz  in=300,570,898 out=54,925,946 elapsed=105.0s

  [7406/21087] intraday_15823.csv.gz  in=300,583,157 out=54,938,205 elapsed=105.0s

  [7407/21087] intraday_15824.csv.gz  in=300,595,713 out=54,950,761 elapsed=105.0s

  [7408/21087] intraday_15825.csv.gz  in=300,607,227 out=54,962,275 elapsed=105.0s

  [7409/21087] intraday_15826.csv.gz  in=300,619,829 out=54,974,877 elapsed=105.1s

  [7410/21087] intraday_15827.csv.gz  in=300,632,872 out=54,987,920 elapsed=105.1s

  [7411/21087] intraday_15828.csv.gz  in=300,646,012 out=55,001,060 elapsed=105.1s

  [7412/21087] intraday_1583.csv.gz  in=300,659,674 out=55,001,060 elapsed=105.1s

  [7413/21087] intraday_15829.csv.gz  in=300,674,340 out=55,015,726 elapsed=105.1s

  [7414/21087] intraday_15830.csv.gz  in=300,685,574 out=55,026,960 elapsed=105.1s

  [7415/21087] intraday_15831.csv.gz  in=300,697,609 out=55,038,995 elapsed=105.1s

  [7416/21087] intraday_15833.csv.gz  in=300,708,847 out=55,050,233 elapsed=105.1s

  [7417/21087] intraday_15832.csv.gz  in=300,720,534 out=55,061,920 elapsed=105.1s

  [7418/21087] intraday_15834.csv.gz  in=300,731,380 out=55,072,766 elapsed=105.1s

  [7419/21087] intraday_15835.csv.gz  in=300,739,495 out=55,080,881 elapsed=105.2s

  [7420/21087] intraday_15837.csv.gz  in=300,745,847 out=55,087,233 elapsed=105.2s

  [7421/21087] intraday_15836.csv.gz  in=300,757,464 out=55,098,850 elapsed=105.2s

  [7422/21087] intraday_15838.csv.gz  in=300,773,934 out=55,115,320 elapsed=105.2s

  [7423/21087] intraday_15839.csv.gz  in=300,788,002 out=55,129,388 elapsed=105.2s

  [7424/21087] intraday_1584.csv.gz  in=300,801,918 out=55,129,388 elapsed=105.2s

  [7425/21087] intraday_15840.csv.gz  in=300,814,706 out=55,142,176 elapsed=105.2s

  [7426/21087] intraday_15841.csv.gz  in=300,827,726 out=55,155,196 elapsed=105.2s

  [7427/21087] intraday_15843.csv.gz  in=300,840,925 out=55,168,395 elapsed=105.2s

  [7428/21087] intraday_15842.csv.gz  in=300,852,331 out=55,179,801 elapsed=105.2s

  [7429/21087] intraday_15844.csv.gz  in=300,864,315 out=55,191,785 elapsed=105.2s

  [7430/21087] intraday_15845.csv.gz  in=300,876,091 out=55,203,561 elapsed=105.3s

  [7431/21087] intraday_15846.csv.gz  in=300,888,939 out=55,216,409 elapsed=105.3s

  [7432/21087] intraday_15847.csv.gz  in=300,901,047 out=55,228,517 elapsed=105.3s

  [7433/21087] intraday_15848.csv.gz  in=300,911,752 out=55,239,222 elapsed=105.3s

  [7434/21087] intraday_15849.csv.gz  in=300,925,088 out=55,252,558 elapsed=105.3s

  [7435/21087] intraday_1585.csv.gz  in=300,936,257 out=55,252,558 elapsed=105.3s

  [7436/21087] intraday_15850.csv.gz  in=300,949,090 out=55,265,391 elapsed=105.3s

  [7437/21087] intraday_15851.csv.gz  in=300,963,121 out=55,278,777 elapsed=105.3s

  [7438/21087] intraday_15852.csv.gz  in=300,972,633 out=55,288,289 elapsed=105.3s

  [7439/21087] intraday_15853.csv.gz  in=300,981,684 out=55,297,340 elapsed=105.4s

  [7440/21087] intraday_15856.csv.gz  in=300,992,528 out=55,308,184 elapsed=105.4s

  [7441/21087] intraday_15855.csv.gz  in=301,004,925 out=55,320,581 elapsed=105.4s

  [7442/21087] intraday_15857.csv.gz  in=301,016,530 out=55,332,186 elapsed=105.4s

  [7443/21087] intraday_15854.csv.gz  in=301,032,395 out=55,348,051 elapsed=105.4s

  [7444/21087] intraday_15858.csv.gz  in=301,043,986 out=55,359,642 elapsed=105.4s

  [7445/21087] intraday_1586.csv.gz  in=301,056,357 out=55,359,642 elapsed=105.4s

  [7446/21087] intraday_15859.csv.gz  in=301,069,312 out=55,372,597 elapsed=105.4s

  [7447/21087] intraday_15860.csv.gz  in=301,081,355 out=55,384,640 elapsed=105.4s

  [7448/21087] intraday_15861.csv.gz  in=301,093,514 out=55,396,799 elapsed=105.5s

  [7449/21087] intraday_15863.csv.gz  in=301,104,577 out=55,407,862 elapsed=105.5s

  [7450/21087] intraday_15864.csv.gz  in=301,115,062 out=55,418,347 elapsed=105.5s

  [7451/21087] intraday_15862.csv.gz  in=301,127,544 out=55,430,829 elapsed=105.5s

  [7452/21087] intraday_15865.csv.gz  in=301,139,733 out=55,443,018 elapsed=105.5s

  [7453/21087] intraday_15867.csv.gz  in=301,151,893 out=55,455,178 elapsed=105.6s

  [7454/21087] intraday_15866.csv.gz  in=301,164,842 out=55,468,127 elapsed=105.6s

  [7455/21087] intraday_15868.csv.gz  in=301,180,633 out=55,483,918 elapsed=105.6s

  [7456/21087] intraday_15869.csv.gz  in=301,191,590 out=55,494,875 elapsed=105.6s

  [7457/21087] intraday_1587.csv.gz  in=301,204,196 out=55,494,875 elapsed=105.6s

  [7458/21087] intraday_15870.csv.gz  in=301,214,422 out=55,505,101 elapsed=105.6s

  [7459/21087] intraday_15871.csv.gz  in=301,227,055 out=55,517,734 elapsed=105.6s

  [7460/21087] intraday_15873.csv.gz  in=301,238,570 out=55,529,249 elapsed=105.6s

  [7461/21087] intraday_15872.csv.gz  in=301,262,657 out=55,553,336 elapsed=105.6s

  [7462/21087] intraday_15874.csv.gz  in=301,276,131 out=55,566,810 elapsed=105.6s

  [7463/21087] intraday_15875.csv.gz  in=301,286,130 out=55,576,809 elapsed=105.7s

  [7464/21087] intraday_15876.csv.gz  in=301,296,725 out=55,587,404 elapsed=105.7s

  [7465/21087] intraday_15877.csv.gz  in=301,306,281 out=55,596,960 elapsed=105.7s

  [7466/21087] intraday_15878.csv.gz  in=301,318,871 out=55,609,550 elapsed=105.7s

  [7467/21087] intraday_1588.csv.gz  in=301,330,265 out=55,609,550 elapsed=105.7s

  [7468/21087] intraday_15879.csv.gz  in=301,342,230 out=55,621,515 elapsed=105.7s

  [7469/21087] intraday_15880.csv.gz  in=301,356,133 out=55,635,418 elapsed=105.7s

  [7470/21087] intraday_15881.csv.gz  in=301,366,768 out=55,646,053 elapsed=105.7s

  [7471/21087] intraday_15882.csv.gz  in=301,380,445 out=55,659,730 elapsed=105.7s

  [7472/21087] intraday_15883.csv.gz  in=301,395,953 out=55,672,983 elapsed=105.7s

  [7473/21087] intraday_15885.csv.gz  in=301,407,542 out=55,684,572 elapsed=105.7s

  [7474/21087] intraday_15884.csv.gz  in=301,419,279 out=55,696,309 elapsed=105.7s

  [7475/21087] intraday_15886.csv.gz  in=301,430,014 out=55,707,044 elapsed=105.8s

  [7476/21087] intraday_15887.csv.gz  in=301,442,429 out=55,719,459 elapsed=105.8s

  [7477/21087] intraday_15888.csv.gz  in=301,454,938 out=55,730,839 elapsed=105.8s

  [7478/21087] intraday_15889.csv.gz  in=301,469,595 out=55,745,496 elapsed=105.8s

  [7479/21087] intraday_1589.csv.gz  in=301,481,117 out=55,745,496 elapsed=105.8s

  [7480/21087] intraday_15890.csv.gz  in=301,500,528 out=55,761,453 elapsed=105.8s

  [7481/21087] intraday_15891.csv.gz  in=301,513,249 out=55,774,174 elapsed=105.8s

  [7482/21087] intraday_15892.csv.gz  in=301,526,170 out=55,787,095 elapsed=105.8s

  [7483/21087] intraday_15893.csv.gz  in=301,539,248 out=55,800,173 elapsed=105.9s

  [7484/21087] intraday_15894.csv.gz  in=301,549,747 out=55,810,672 elapsed=105.9s

  [7485/21087] intraday_15895.csv.gz  in=301,560,911 out=55,821,836 elapsed=105.9s

  [7486/21087] intraday_15896.csv.gz  in=301,594,583 out=55,844,264 elapsed=105.9s

  [7487/21087] intraday_15897.csv.gz  in=301,606,462 out=55,856,143 elapsed=105.9s

  [7488/21087] intraday_15898.csv.gz  in=301,618,384 out=55,868,065 elapsed=105.9s

  [7489/21087] intraday_15899.csv.gz  in=301,635,413 out=55,882,756 elapsed=105.9s

  [7490/21087] intraday_1590.csv.gz  in=301,646,909 out=55,882,756 elapsed=105.9s

  [7491/21087] intraday_15900.csv.gz  in=301,659,531 out=55,895,378 elapsed=106.0s

  [7492/21087] intraday_15901.csv.gz  in=301,670,613 out=55,906,460 elapsed=106.0s

  [7493/21087] intraday_15902.csv.gz  in=301,681,880 out=55,917,727 elapsed=106.0s

  [7494/21087] intraday_15903.csv.gz  in=301,695,766 out=55,931,613 elapsed=106.0s

  [7495/21087] intraday_15904.csv.gz  in=301,709,363 out=55,945,210 elapsed=106.0s

  [7496/21087] intraday_15905.csv.gz  in=301,722,119 out=55,957,966 elapsed=106.0s

  [7497/21087] intraday_15906.csv.gz  in=301,743,809 out=55,975,407 elapsed=106.0s

  [7498/21087] intraday_15907.csv.gz  in=301,754,319 out=55,985,917 elapsed=106.0s

  [7499/21087] intraday_15908.csv.gz  in=301,764,774 out=55,996,372 elapsed=106.0s

  [7500/21087] intraday_1591.csv.gz  in=301,776,794 out=55,996,372 elapsed=106.0s

  [7501/21087] intraday_15909.csv.gz  in=301,789,822 out=56,009,400 elapsed=106.0s

  [7502/21087] intraday_15910.csv.gz  in=301,799,723 out=56,019,301 elapsed=106.1s

  [7503/21087] intraday_15911.csv.gz  in=301,812,212 out=56,031,790 elapsed=106.1s

  [7504/21087] intraday_15913.csv.gz  in=301,822,116 out=56,041,694 elapsed=106.1s

  [7505/21087] intraday_15912.csv.gz  in=301,832,929 out=56,052,507 elapsed=106.1s

  [7506/21087] intraday_15914.csv.gz  in=301,843,661 out=56,063,239 elapsed=106.1s

  [7507/21087] intraday_15915.csv.gz  in=301,857,458 out=56,077,036 elapsed=106.1s

  [7508/21087] intraday_15916.csv.gz  in=301,868,974 out=56,088,552 elapsed=106.1s

  [7509/21087] intraday_15917.csv.gz  in=301,881,359 out=56,100,937 elapsed=106.2s

  [7510/21087] intraday_15918.csv.gz  in=301,892,188 out=56,111,766 elapsed=106.2s

  [7511/21087] intraday_15919.csv.gz  in=301,902,630 out=56,122,208 elapsed=106.2s

  [7512/21087] intraday_1592.csv.gz  in=301,914,067 out=56,122,208 elapsed=106.2s

  [7513/21087] intraday_15920.csv.gz  in=301,926,619 out=56,134,760 elapsed=106.2s

  [7514/21087] intraday_15921.csv.gz  in=301,940,634 out=56,148,775 elapsed=106.2s

  [7515/21087] intraday_15923.csv.gz  in=301,953,068 out=56,161,209 elapsed=106.2s

  [7516/21087] intraday_15922.csv.gz  in=301,967,185 out=56,175,326 elapsed=106.2s

  [7517/21087] intraday_15924.csv.gz  in=301,978,964 out=56,187,105 elapsed=106.2s

  [7518/21087] intraday_15926.csv.gz  in=301,989,607 out=56,197,748 elapsed=106.3s

  [7519/21087] intraday_15927.csv.gz  in=302,003,424 out=56,211,565 elapsed=106.3s

  [7520/21087] intraday_15928.csv.gz  in=302,015,248 out=56,223,389 elapsed=106.3s

  [7521/21087] intraday_15925.csv.gz  in=302,027,027 out=56,235,168 elapsed=106.3s

  [7522/21087] intraday_15929.csv.gz  in=302,038,806 out=56,246,947 elapsed=106.3s

  [7523/21087] intraday_1593.csv.gz  in=302,050,725 out=56,246,947 elapsed=106.3s

  [7524/21087] intraday_15931.csv.gz  in=302,063,458 out=56,259,680 elapsed=106.3s

  [7525/21087] intraday_15932.csv.gz  in=302,075,382 out=56,271,604 elapsed=106.3s

  [7526/21087] intraday_15930.csv.gz  in=302,113,950 out=56,298,087 elapsed=106.4s

  [7527/21087] intraday_15933.csv.gz  in=302,126,352 out=56,310,489 elapsed=106.4s

  [7528/21087] intraday_15934.csv.gz  in=302,139,755 out=56,323,892 elapsed=106.4s

  [7529/21087] intraday_15935.csv.gz  in=302,152,320 out=56,336,457 elapsed=106.4s

  [7530/21087] intraday_15936.csv.gz  in=302,163,629 out=56,347,766 elapsed=106.4s

  [7531/21087] intraday_15937.csv.gz  in=302,174,227 out=56,358,364 elapsed=106.4s

  [7532/21087] intraday_15938.csv.gz  in=302,185,335 out=56,369,472 elapsed=106.4s

  [7533/21087] intraday_1594.csv.gz  in=302,196,570 out=56,369,472 elapsed=106.4s

  [7534/21087] intraday_15939.csv.gz  in=302,208,956 out=56,381,858 elapsed=106.4s

  [7535/21087] intraday_15940.csv.gz  in=302,228,038 out=56,398,443 elapsed=106.4s

  [7536/21087] intraday_15941.csv.gz  in=302,240,218 out=56,410,623 elapsed=106.4s

  [7537/21087] intraday_15942.csv.gz  in=302,251,852 out=56,422,257 elapsed=106.5s

  [7538/21087] intraday_15943.csv.gz  in=302,262,966 out=56,433,371 elapsed=106.5s

  [7539/21087] intraday_15944.csv.gz  in=302,277,682 out=56,448,087 elapsed=106.5s

  [7540/21087] intraday_15945.csv.gz  in=302,288,069 out=56,458,474 elapsed=106.5s

  [7541/21087] intraday_15946.csv.gz  in=302,299,359 out=56,469,764 elapsed=106.5s

  [7542/21087] intraday_15947.csv.gz  in=302,312,407 out=56,482,812 elapsed=106.5s

  [7543/21087] intraday_1595.csv.gz  in=302,322,556 out=56,482,812 elapsed=106.5s

  [7544/21087] intraday_15948.csv.gz  in=302,335,937 out=56,496,193 elapsed=106.5s

  [7545/21087] intraday_15949.csv.gz  in=302,347,093 out=56,507,349 elapsed=106.5s

  [7546/21087] intraday_15950.csv.gz  in=302,361,038 out=56,521,294 elapsed=106.5s

  [7547/21087] intraday_15951.csv.gz  in=302,375,134 out=56,535,390 elapsed=106.5s

  [7548/21087] intraday_15952.csv.gz  in=302,389,291 out=56,549,547 elapsed=106.6s

  [7549/21087] intraday_15953.csv.gz  in=302,401,839 out=56,562,095 elapsed=106.6s

  [7550/21087] intraday_15954.csv.gz  in=302,418,724 out=56,578,980 elapsed=106.6s

  [7551/21087] intraday_15955.csv.gz  in=302,436,283 out=56,596,539 elapsed=106.6s

  [7552/21087] intraday_15956.csv.gz  in=302,450,096 out=56,610,352 elapsed=106.6s

  [7553/21087] intraday_15958.csv.gz  in=302,461,075 out=56,621,331 elapsed=106.6s

  [7554/21087] intraday_15957.csv.gz  in=302,474,617 out=56,634,873 elapsed=106.6s

  [7555/21087] intraday_1596.csv.gz  in=302,486,366 out=56,634,873 elapsed=106.6s

  [7556/21087] intraday_15959.csv.gz  in=302,501,331 out=56,649,838 elapsed=106.6s

  [7557/21087] intraday_15960.csv.gz  in=302,512,160 out=56,660,667 elapsed=106.7s

  [7558/21087] intraday_15961.csv.gz  in=302,528,191 out=56,675,026 elapsed=106.7s

  [7559/21087] intraday_15962.csv.gz  in=302,538,023 out=56,684,858 elapsed=106.7s

  [7560/21087] intraday_15963.csv.gz  in=302,551,898 out=56,698,733 elapsed=106.7s

  [7561/21087] intraday_15964.csv.gz  in=302,564,279 out=56,711,114 elapsed=106.7s

  [7562/21087] intraday_15966.csv.gz  in=302,575,227 out=56,722,062 elapsed=106.7s

  [7563/21087] intraday_15965.csv.gz  in=302,588,438 out=56,735,273 elapsed=106.7s

  [7564/21087] intraday_15967.csv.gz  in=302,601,003 out=56,747,838 elapsed=106.7s

  [7565/21087] intraday_15968.csv.gz  in=302,613,216 out=56,760,051 elapsed=106.7s

  [7566/21087] intraday_1597.csv.gz  in=302,625,347 out=56,760,051 elapsed=106.8s

  [7567/21087] intraday_15969.csv.gz  in=302,638,087 out=56,772,791 elapsed=106.8s

  [7568/21087] intraday_15970.csv.gz  in=302,653,401 out=56,786,722 elapsed=106.8s

  [7569/21087] intraday_15971.csv.gz  in=302,667,028 out=56,800,349 elapsed=106.8s

  [7570/21087] intraday_15972.csv.gz  in=302,681,342 out=56,814,663 elapsed=106.8s

  [7571/21087] intraday_15973.csv.gz  in=302,693,127 out=56,826,448 elapsed=106.8s

  [7572/21087] intraday_15975.csv.gz  in=302,703,157 out=56,836,478 elapsed=106.8s

  [7573/21087] intraday_15977.csv.gz  in=302,715,453 out=56,848,774 elapsed=106.9s

  [7574/21087] intraday_15974.csv.gz  in=302,731,397 out=56,864,718 elapsed=106.9s

  [7575/21087] intraday_15976.csv.gz  in=302,743,047 out=56,876,368 elapsed=106.9s

  [7576/21087] intraday_15978.csv.gz  in=302,753,146 out=56,886,467 elapsed=106.9s

  [7577/21087] intraday_1598.csv.gz  in=302,768,736 out=56,886,467 elapsed=106.9s

  [7578/21087] intraday_15981.csv.gz  in=302,778,787 out=56,896,518 elapsed=106.9s

  [7579/21087] intraday_15980.csv.gz  in=302,787,757 out=56,905,488 elapsed=106.9s

  [7580/21087] intraday_15979.csv.gz  in=302,799,756 out=56,917,487 elapsed=106.9s

  [7581/21087] intraday_15982.csv.gz  in=302,808,437 out=56,926,168 elapsed=106.9s

  [7582/21087] intraday_15985.csv.gz  in=302,823,066 out=56,940,797 elapsed=106.9s

  [7583/21087] intraday_15983.csv.gz  in=302,838,641 out=56,956,372 elapsed=107.0s

  [7584/21087] intraday_15984.csv.gz  in=302,851,628 out=56,969,359 elapsed=107.0s

  [7585/21087] intraday_15986.csv.gz  in=302,863,497 out=56,981,228 elapsed=107.0s

  [7586/21087] intraday_15987.csv.gz  in=302,878,036 out=56,995,767 elapsed=107.0s

  [7587/21087] intraday_15988.csv.gz  in=302,892,788 out=57,010,519 elapsed=107.0s

  [7588/21087] intraday_1599.csv.gz  in=302,918,570 out=57,010,519 elapsed=107.0s

  [7589/21087] intraday_15989.csv.gz  in=302,930,932 out=57,022,881 elapsed=107.0s

  [7590/21087] intraday_15990.csv.gz  in=302,942,588 out=57,034,537 elapsed=107.0s

  [7591/21087] intraday_15993.csv.gz  in=302,952,385 out=57,044,334 elapsed=107.0s

  [7592/21087] intraday_15991.csv.gz  in=302,963,514 out=57,055,463 elapsed=107.1s

  [7593/21087] intraday_15994.csv.gz  in=302,976,069 out=57,068,018 elapsed=107.1s

  [7594/21087] intraday_15992.csv.gz  in=302,991,541 out=57,083,082 elapsed=107.1s

  [7595/21087] intraday_15995.csv.gz  in=303,004,769 out=57,096,310 elapsed=107.1s

  [7596/21087] intraday_15996.csv.gz  in=303,017,027 out=57,108,568 elapsed=107.1s

  [7597/21087] intraday_15997.csv.gz  in=303,027,159 out=57,118,700 elapsed=107.1s

  [7598/21087] intraday_15998.csv.gz  in=303,038,099 out=57,129,640 elapsed=107.1s

  [7599/21087] intraday_1600.csv.gz  in=303,048,184 out=57,129,640 elapsed=107.1s

  [7600/21087] intraday_15999.csv.gz  in=303,062,288 out=57,143,744 elapsed=107.2s

  [7601/21087] intraday_16000.csv.gz  in=303,074,895 out=57,156,351 elapsed=107.2s

  [7602/21087] intraday_16001.csv.gz  in=303,085,816 out=57,167,272 elapsed=107.2s

  [7603/21087] intraday_16002.csv.gz  in=303,096,028 out=57,177,484 elapsed=107.2s

  [7604/21087] intraday_16003.csv.gz  in=303,107,856 out=57,189,312 elapsed=107.2s

  [7605/21087] intraday_16004.csv.gz  in=303,120,045 out=57,201,501 elapsed=107.2s

  [7606/21087] intraday_16005.csv.gz  in=303,131,784 out=57,213,240 elapsed=107.2s

  [7607/21087] intraday_16006.csv.gz  in=303,144,372 out=57,225,828 elapsed=107.2s

  [7608/21087] intraday_16007.csv.gz  in=303,156,656 out=57,238,112 elapsed=107.2s

  [7609/21087] intraday_16009.csv.gz  in=303,166,413 out=57,247,869 elapsed=107.2s

  [7610/21087] intraday_1601.csv.gz  in=303,177,780 out=57,247,869 elapsed=107.2s

  [7611/21087] intraday_16008.csv.gz  in=303,211,195 out=57,271,439 elapsed=107.3s

  [7612/21087] intraday_16010.csv.gz  in=303,222,990 out=57,283,234 elapsed=107.3s

  [7613/21087] intraday_16011.csv.gz  in=303,235,808 out=57,296,052 elapsed=107.3s

  [7614/21087] intraday_16012.csv.gz  in=303,248,050 out=57,308,294 elapsed=107.3s

  [7615/21087] intraday_16014.csv.gz  in=303,260,654 out=57,320,898 elapsed=107.3s

  [7616/21087] intraday_16015.csv.gz  in=303,271,075 out=57,331,319 elapsed=107.3s

  [7617/21087] intraday_16016.csv.gz  in=303,283,942 out=57,344,186 elapsed=107.4s

  [7618/21087] intraday_16013.csv.gz  in=303,299,776 out=57,359,632 elapsed=107.4s

  [7619/21087] intraday_16018.csv.gz  in=303,312,045 out=57,371,901 elapsed=107.4s

  [7620/21087] intraday_16017.csv.gz  in=303,335,787 out=57,395,643 elapsed=107.4s

  [7621/21087] intraday_1602.csv.gz  in=303,348,072 out=57,395,643 elapsed=107.4s

  [7622/21087] intraday_16019.csv.gz  in=303,360,316 out=57,407,887 elapsed=107.4s

  [7623/21087] intraday_16021.csv.gz  in=303,370,345 out=57,417,916 elapsed=107.4s

  [7624/21087] intraday_16022.csv.gz  in=303,379,900 out=57,427,471 elapsed=107.4s

  [7625/21087] intraday_16020.csv.gz  in=303,390,903 out=57,438,474 elapsed=107.4s

  [7626/21087] intraday_16023.csv.gz  in=303,401,445 out=57,449,016 elapsed=107.4s

  [7627/21087] intraday_16027.csv.gz  in=303,414,398 out=57,461,969 elapsed=107.5s

  [7628/21087] intraday_16026.csv.gz  in=303,429,613 out=57,477,184 elapsed=107.5s

  [7629/21087] intraday_16025.csv.gz  in=303,444,305 out=57,491,876 elapsed=107.5s

  [7630/21087] intraday_16024.csv.gz  in=303,455,887 out=57,503,458 elapsed=107.5s

  [7631/21087] intraday_16028.csv.gz  in=303,465,558 out=57,513,129 elapsed=107.5s

  [7632/21087] intraday_1603.csv.gz  in=303,480,784 out=57,513,129 elapsed=107.5s

  [7633/21087] intraday_16030.csv.gz  in=303,493,933 out=57,525,542 elapsed=107.5s

  [7634/21087] intraday_16029.csv.gz  in=303,506,762 out=57,538,371 elapsed=107.5s

  [7635/21087] intraday_16031.csv.gz  in=303,525,267 out=57,553,094 elapsed=107.5s

  [7636/21087] intraday_16032.csv.gz  in=303,537,779 out=57,565,606 elapsed=107.6s

  [7637/21087] intraday_16033.csv.gz  in=303,548,236 out=57,576,063 elapsed=107.6s

  [7638/21087] intraday_16034.csv.gz  in=303,561,956 out=57,589,783 elapsed=107.6s

  [7639/21087] intraday_16035.csv.gz  in=303,573,716 out=57,601,543 elapsed=107.6s

  [7640/21087] intraday_16036.csv.gz  in=303,586,063 out=57,613,890 elapsed=107.6s

  [7641/21087] intraday_16037.csv.gz  in=303,598,209 out=57,626,036 elapsed=107.6s

  [7642/21087] intraday_1604.csv.gz  in=303,610,611 out=57,626,036 elapsed=107.6s

  [7643/21087] intraday_16038.csv.gz  in=303,623,766 out=57,639,191 elapsed=107.6s

  [7644/21087] intraday_16039.csv.gz  in=303,634,100 out=57,649,525 elapsed=107.6s

  [7645/21087] intraday_16040.csv.gz  in=303,647,205 out=57,661,613 elapsed=107.6s

  [7646/21087] intraday_16043.csv.gz  in=303,657,807 out=57,672,215 elapsed=107.7s

  [7647/21087] intraday_16041.csv.gz  in=303,672,939 out=57,687,347 elapsed=107.7s

  [7648/21087] intraday_16042.csv.gz  in=303,685,865 out=57,700,273 elapsed=107.7s

  [7649/21087] intraday_16044.csv.gz  in=303,697,565 out=57,711,973 elapsed=107.7s

  [7650/21087] intraday_16045.csv.gz  in=303,708,506 out=57,722,914 elapsed=107.7s

  [7651/21087] intraday_16046.csv.gz  in=303,719,265 out=57,733,673 elapsed=107.7s

  [7652/21087] intraday_16047.csv.gz  in=303,731,836 out=57,746,244 elapsed=107.7s

  [7653/21087] intraday_16048.csv.gz  in=303,747,015 out=57,761,423 elapsed=107.7s

  [7654/21087] intraday_16049.csv.gz  in=303,757,533 out=57,771,941 elapsed=107.7s

  [7655/21087] intraday_1605.csv.gz  in=303,771,315 out=57,771,941 elapsed=107.7s

  [7656/21087] intraday_16050.csv.gz  in=303,783,666 out=57,784,292 elapsed=107.8s

  [7657/21087] intraday_16053.csv.gz  in=303,795,535 out=57,796,161 elapsed=107.8s

  [7658/21087] intraday_16052.csv.gz  in=303,810,540 out=57,808,440 elapsed=107.8s

  [7659/21087] intraday_16054.csv.gz  in=303,823,569 out=57,821,469 elapsed=107.8s

  [7660/21087] intraday_16051.csv.gz  in=303,864,857 out=57,849,545 elapsed=107.8s

  [7661/21087] intraday_16055.csv.gz  in=303,875,986 out=57,860,674 elapsed=107.8s

  [7662/21087] intraday_16057.csv.gz  in=303,887,354 out=57,871,326 elapsed=107.8s

  [7663/21087] intraday_16056.csv.gz  in=303,901,792 out=57,885,764 elapsed=107.8s

  [7664/21087] intraday_16058.csv.gz  in=303,911,517 out=57,895,489 elapsed=107.8s

  [7665/21087] intraday_16059.csv.gz  in=303,922,910 out=57,906,882 elapsed=107.8s

  [7666/21087] intraday_1606.csv.gz  in=303,935,895 out=57,906,882 elapsed=107.9s

  [7667/21087] intraday_16060.csv.gz  in=303,949,655 out=57,920,642 elapsed=107.9s

  [7668/21087] intraday_16061.csv.gz  in=303,960,736 out=57,931,723 elapsed=107.9s

  [7669/21087] intraday_16062.csv.gz  in=303,971,987 out=57,942,974 elapsed=107.9s

  [7670/21087] intraday_16063.csv.gz  in=303,981,970 out=57,952,957 elapsed=107.9s

  [7671/21087] intraday_16064.csv.gz  in=303,992,743 out=57,963,730 elapsed=107.9s

  [7672/21087] intraday_16065.csv.gz  in=304,004,523 out=57,975,510 elapsed=107.9s

  [7673/21087] intraday_16067.csv.gz  in=304,018,919 out=57,989,906 elapsed=107.9s

  [7674/21087] intraday_16066.csv.gz  in=304,033,693 out=58,004,680 elapsed=108.0s

  [7675/21087] intraday_16068.csv.gz  in=304,047,757 out=58,018,744 elapsed=108.0s

  [7676/21087] intraday_16069.csv.gz  in=304,058,446 out=58,029,433 elapsed=108.0s

  [7677/21087] intraday_1607.csv.gz  in=304,072,659 out=58,029,433 elapsed=108.0s

  [7678/21087] intraday_16070.csv.gz  in=304,089,070 out=58,045,582 elapsed=108.0s

  [7679/21087] intraday_16071.csv.gz  in=304,099,116 out=58,055,628 elapsed=108.0s

  [7680/21087] intraday_16073.csv.gz  in=304,108,946 out=58,065,458 elapsed=108.0s

  [7681/21087] intraday_16072.csv.gz  in=304,123,697 out=58,080,209 elapsed=108.0s

  [7682/21087] intraday_16074.csv.gz  in=304,135,995 out=58,092,507 elapsed=108.0s

  [7683/21087] intraday_16075.csv.gz  in=304,147,274 out=58,103,786 elapsed=108.1s

  [7684/21087] intraday_16077.csv.gz  in=304,159,640 out=58,116,152 elapsed=108.1s

  [7685/21087] intraday_16076.csv.gz  in=304,172,675 out=58,129,187 elapsed=108.1s

  [7686/21087] intraday_1608.csv.gz  in=304,186,736 out=58,129,187 elapsed=108.1s

  [7687/21087] intraday_16078.csv.gz  in=304,199,440 out=58,141,891 elapsed=108.1s

  [7688/21087] intraday_16080.csv.gz  in=304,210,119 out=58,152,570 elapsed=108.1s

  [7689/21087] intraday_16079.csv.gz  in=304,222,135 out=58,164,586 elapsed=108.1s

  [7690/21087] intraday_16081.csv.gz  in=304,233,845 out=58,176,296 elapsed=108.1s

  [7691/21087] intraday_16082.csv.gz  in=304,245,569 out=58,188,020 elapsed=108.1s

  [7692/21087] intraday_16084.csv.gz  in=304,256,953 out=58,199,404 elapsed=108.2s

  [7693/21087] intraday_16083.csv.gz  in=304,268,090 out=58,210,541 elapsed=108.2s

  [7694/21087] intraday_16085.csv.gz  in=304,281,123 out=58,223,574 elapsed=108.2s

  [7695/21087] intraday_16086.csv.gz  in=304,293,203 out=58,235,654 elapsed=108.2s

  [7696/21087] intraday_16088.csv.gz  in=304,304,172 out=58,246,623 elapsed=108.2s

  [7697/21087] intraday_1609.csv.gz  in=304,317,289 out=58,246,623 elapsed=108.2s

  [7698/21087] intraday_16087.csv.gz  in=304,328,755 out=58,258,089 elapsed=108.2s

  [7699/21087] intraday_16089.csv.gz  in=304,341,894 out=58,271,228 elapsed=108.2s

  [7700/21087] intraday_16091.csv.gz  in=304,353,584 out=58,282,918 elapsed=108.2s

  [7701/21087] intraday_16090.csv.gz  in=304,365,156 out=58,294,490 elapsed=108.2s

  [7702/21087] intraday_16092.csv.gz  in=304,377,277 out=58,306,611 elapsed=108.2s

  [7703/21087] intraday_16093.csv.gz  in=304,390,886 out=58,320,220 elapsed=108.3s

  [7704/21087] intraday_16094.csv.gz  in=304,402,375 out=58,331,709 elapsed=108.3s

  [7705/21087] intraday_16095.csv.gz  in=304,417,089 out=58,346,423 elapsed=108.3s

  [7706/21087] intraday_16096.csv.gz  in=304,429,785 out=58,359,119 elapsed=108.3s

  [7707/21087] intraday_16097.csv.gz  in=304,443,989 out=58,373,323 elapsed=108.3s

  [7708/21087] intraday_16098.csv.gz  in=304,456,555 out=58,385,889 elapsed=108.3s

  [7709/21087] intraday_1610.csv.gz  in=304,469,454 out=58,385,889 elapsed=108.3s

  [7710/21087] intraday_16099.csv.gz  in=304,488,755 out=58,405,190 elapsed=108.3s

  [7711/21087] intraday_16102.csv.gz  in=304,500,047 out=58,416,482 elapsed=108.3s

  [7712/21087] intraday_16100.csv.gz  in=304,514,582 out=58,431,017 elapsed=108.3s

  [7713/21087] intraday_16101.csv.gz  in=304,530,516 out=58,446,951 elapsed=108.4s

  [7714/21087] intraday_16103.csv.gz  in=304,545,308 out=58,461,743 elapsed=108.4s

  [7715/21087] intraday_16105.csv.gz  in=304,555,165 out=58,471,600 elapsed=108.4s

  [7716/21087] intraday_16104.csv.gz  in=304,567,574 out=58,484,009 elapsed=108.4s

  [7717/21087] intraday_16106.csv.gz  in=304,579,633 out=58,496,068 elapsed=108.4s

  [7718/21087] intraday_16107.csv.gz  in=304,591,927 out=58,508,362 elapsed=108.4s

  [7719/21087] intraday_16108.csv.gz  in=304,603,735 out=58,520,170 elapsed=108.4s

  [7720/21087] intraday_16109.csv.gz  in=304,617,249 out=58,533,684 elapsed=108.4s

  [7721/21087] intraday_1611.csv.gz  in=304,628,913 out=58,533,684 elapsed=108.4s

  [7722/21087] intraday_16110.csv.gz  in=304,642,114 out=58,546,881 elapsed=108.4s

  [7723/21087] intraday_16111.csv.gz  in=304,653,381 out=58,558,148 elapsed=108.4s

  [7724/21087] intraday_16112.csv.gz  in=304,664,579 out=58,569,346 elapsed=108.5s

  [7725/21087] intraday_16114.csv.gz  in=304,677,489 out=58,582,256 elapsed=108.5s

  [7726/21087] intraday_16113.csv.gz  in=304,690,972 out=58,595,739 elapsed=108.5s

  [7727/21087] intraday_16115.csv.gz  in=304,702,470 out=58,607,237 elapsed=108.5s

  [7728/21087] intraday_16116.csv.gz  in=304,716,858 out=58,621,625 elapsed=108.5s

  [7729/21087] intraday_16118.csv.gz  in=304,729,114 out=58,633,881 elapsed=108.5s

  [7730/21087] intraday_1612.csv.gz  in=304,740,216 out=58,633,881 elapsed=108.5s

  [7731/21087] intraday_16117.csv.gz  in=304,767,257 out=58,655,520 elapsed=108.5s

  [7732/21087] intraday_16119.csv.gz  in=304,780,340 out=58,668,603 elapsed=108.5s

  [7733/21087] intraday_16120.csv.gz  in=304,792,004 out=58,680,267 elapsed=108.5s

  [7734/21087] intraday_16121.csv.gz  in=304,805,360 out=58,693,623 elapsed=108.6s

  [7735/21087] intraday_16122.csv.gz  in=304,815,799 out=58,704,062 elapsed=108.6s

  [7736/21087] intraday_16123.csv.gz  in=304,827,653 out=58,715,916 elapsed=108.6s

  [7737/21087] intraday_16124.csv.gz  in=304,838,372 out=58,726,635 elapsed=108.6s

  [7738/21087] intraday_16125.csv.gz  in=304,848,071 out=58,735,648 elapsed=108.6s

  [7739/21087] intraday_16127.csv.gz  in=304,851,779 out=58,739,356 elapsed=108.6s

  [7740/21087] intraday_16126.csv.gz  in=304,862,533 out=58,750,110 elapsed=108.6s

  [7741/21087] intraday_1613.csv.gz  in=304,877,843 out=58,750,110 elapsed=108.6s

  [7742/21087] intraday_16128.csv.gz  in=304,893,901 out=58,766,168 elapsed=108.6s

  [7743/21087] intraday_16129.csv.gz  in=304,908,363 out=58,780,630 elapsed=108.6s

  [7744/21087] intraday_16130.csv.gz  in=304,922,407 out=58,794,674 elapsed=108.6s

  [7745/21087] intraday_16131.csv.gz  in=304,934,182 out=58,806,449 elapsed=108.7s

  [7746/21087] intraday_16132.csv.gz  in=304,947,274 out=58,819,541 elapsed=108.7s

  [7747/21087] intraday_16134.csv.gz  in=304,960,220 out=58,832,487 elapsed=108.7s

  [7748/21087] intraday_16133.csv.gz  in=304,974,615 out=58,846,882 elapsed=108.7s

  [7749/21087] intraday_16135.csv.gz  in=304,986,777 out=58,859,044 elapsed=108.7s

  [7750/21087] intraday_16137.csv.gz  in=305,000,308 out=58,872,575 elapsed=108.7s

  [7751/21087] intraday_16136.csv.gz  in=305,012,898 out=58,885,165 elapsed=108.7s

  [7752/21087] intraday_16138.csv.gz  in=305,022,957 out=58,895,224 elapsed=108.7s

  [7753/21087] intraday_16139.csv.gz  in=305,036,558 out=58,908,825 elapsed=108.7s

  [7754/21087] intraday_1614.csv.gz  in=305,050,850 out=58,908,825 elapsed=108.8s

  [7755/21087] intraday_16141.csv.gz  in=305,062,653 out=58,920,628 elapsed=108.8s

  [7756/21087] intraday_16142.csv.gz  in=305,073,841 out=58,931,816 elapsed=108.8s

  [7757/21087] intraday_16140.csv.gz  in=305,088,369 out=58,946,344 elapsed=108.8s

  [7758/21087] intraday_16143.csv.gz  in=305,099,607 out=58,957,582 elapsed=108.8s

  [7759/21087] intraday_16144.csv.gz  in=305,114,382 out=58,972,357 elapsed=108.9s

  [7760/21087] intraday_16146.csv.gz  in=305,125,418 out=58,983,393 elapsed=108.9s

  [7761/21087] intraday_16147.csv.gz  in=305,136,325 out=58,994,300 elapsed=108.9s

  [7762/21087] intraday_16145.csv.gz  in=305,151,142 out=59,009,117 elapsed=108.9s

  [7763/21087] intraday_1615.csv.gz  in=305,162,519 out=59,009,117 elapsed=108.9s

  [7764/21087] intraday_16148.csv.gz  in=305,175,057 out=59,021,655 elapsed=108.9s

  [7765/21087] intraday_16149.csv.gz  in=305,187,270 out=59,033,868 elapsed=108.9s

  [7766/21087] intraday_16150.csv.gz  in=305,200,217 out=59,046,815 elapsed=108.9s

  [7767/21087] intraday_16151.csv.gz  in=305,212,954 out=59,059,552 elapsed=108.9s

  [7768/21087] intraday_16152.csv.gz  in=305,224,869 out=59,071,467 elapsed=109.0s

  [7769/21087] intraday_16153.csv.gz  in=305,236,058 out=59,082,656 elapsed=109.0s

  [7770/21087] intraday_16155.csv.gz  in=305,247,052 out=59,093,650 elapsed=109.0s

  [7771/21087] intraday_16154.csv.gz  in=305,258,925 out=59,105,523 elapsed=109.0s

  [7772/21087] intraday_16156.csv.gz  in=305,274,060 out=59,120,658 elapsed=109.0s

  [7773/21087] intraday_16157.csv.gz  in=305,288,420 out=59,135,018 elapsed=109.0s

  [7774/21087] intraday_16159.csv.gz  in=305,300,237 out=59,146,835 elapsed=109.0s

  [7775/21087] intraday_1616.csv.gz  in=305,312,528 out=59,146,835 elapsed=109.0s

  [7776/21087] intraday_16158.csv.gz  in=305,328,884 out=59,163,191 elapsed=109.0s

  [7777/21087] intraday_16160.csv.gz  in=305,339,788 out=59,174,095 elapsed=109.1s

  [7778/21087] intraday_16161.csv.gz  in=305,352,928 out=59,187,235 elapsed=109.1s

  [7779/21087] intraday_16162.csv.gz  in=305,366,006 out=59,200,313 elapsed=109.1s

  [7780/21087] intraday_16163.csv.gz  in=305,378,428 out=59,212,735 elapsed=109.1s

  [7781/21087] intraday_16164.csv.gz  in=305,391,637 out=59,225,944 elapsed=109.1s

  [7782/21087] intraday_16167.csv.gz  in=305,402,290 out=59,236,597 elapsed=109.1s

  [7783/21087] intraday_16166.csv.gz  in=305,412,752 out=59,247,059 elapsed=109.1s

  [7784/21087] intraday_16165.csv.gz  in=305,424,065 out=59,258,372 elapsed=109.1s

  [7785/21087] intraday_16168.csv.gz  in=305,436,001 out=59,270,308 elapsed=109.1s

  [7786/21087] intraday_1617.csv.gz  in=305,448,247 out=59,270,308 elapsed=109.2s

  [7787/21087] intraday_16171.csv.gz  in=305,461,685 out=59,283,746 elapsed=109.2s

  [7788/21087] intraday_16169.csv.gz  in=305,473,826 out=59,295,887 elapsed=109.2s

  [7789/21087] intraday_16170.csv.gz  in=305,488,671 out=59,310,732 elapsed=109.2s

  [7790/21087] intraday_16172.csv.gz  in=305,501,101 out=59,323,162 elapsed=109.2s

  [7791/21087] intraday_16175.csv.gz  in=305,513,041 out=59,335,102 elapsed=109.2s

  [7792/21087] intraday_16174.csv.gz  in=305,525,257 out=59,347,318 elapsed=109.2s

  [7793/21087] intraday_16173.csv.gz  in=305,536,566 out=59,358,627 elapsed=109.2s

  [7794/21087] intraday_16176.csv.gz  in=305,548,078 out=59,370,139 elapsed=109.2s

  [7795/21087] intraday_16178.csv.gz  in=305,558,126 out=59,380,187 elapsed=109.3s

  [7796/21087] intraday_1618.csv.gz  in=305,570,293 out=59,380,187 elapsed=109.3s

  [7797/21087] intraday_16179.csv.gz  in=305,584,657 out=59,394,551 elapsed=109.3s

  [7798/21087] intraday_16177.csv.gz  in=305,597,632 out=59,407,526 elapsed=109.3s

  [7799/21087] intraday_16180.csv.gz  in=305,608,961 out=59,418,855 elapsed=109.3s

  [7800/21087] intraday_16181.csv.gz  in=305,621,352 out=59,431,246 elapsed=109.3s

  [7801/21087] intraday_16182.csv.gz  in=305,635,753 out=59,445,647 elapsed=109.3s

  [7802/21087] intraday_16183.csv.gz  in=305,648,148 out=59,458,042 elapsed=109.3s

  [7803/21087] intraday_16184.csv.gz  in=305,659,865 out=59,469,759 elapsed=109.3s

  [7804/21087] intraday_16185.csv.gz  in=305,671,494 out=59,481,388 elapsed=109.3s

  [7805/21087] intraday_16187.csv.gz  in=305,683,610 out=59,493,504 elapsed=109.3s

  [7806/21087] intraday_16186.csv.gz  in=305,697,695 out=59,507,589 elapsed=109.4s

  [7807/21087] intraday_16189.csv.gz  in=305,707,341 out=59,517,235 elapsed=109.4s

  [7808/21087] intraday_16188.csv.gz  in=305,720,878 out=59,530,772 elapsed=109.4s

  [7809/21087] intraday_1619.csv.gz  in=305,733,320 out=59,530,772 elapsed=109.4s

  [7810/21087] intraday_16191.csv.gz  in=305,744,058 out=59,541,510 elapsed=109.4s

  [7811/21087] intraday_16190.csv.gz  in=305,756,296 out=59,553,748 elapsed=109.4s

  [7812/21087] intraday_16192.csv.gz  in=305,769,823 out=59,567,275 elapsed=109.4s

  [7813/21087] intraday_16193.csv.gz  in=305,782,773 out=59,580,225 elapsed=109.4s

  [7814/21087] intraday_16194.csv.gz  in=305,796,583 out=59,594,035 elapsed=109.4s

  [7815/21087] intraday_16197.csv.gz  in=305,804,604 out=59,602,056 elapsed=109.5s

  [7816/21087] intraday_16196.csv.gz  in=305,816,796 out=59,614,248 elapsed=109.5s

  [7817/21087] intraday_16195.csv.gz  in=305,828,935 out=59,626,387 elapsed=109.5s

  [7818/21087] intraday_16198.csv.gz  in=305,841,587 out=59,639,039 elapsed=109.5s

  [7819/21087] intraday_16199.csv.gz  in=305,854,849 out=59,652,301 elapsed=109.5s

  [7820/21087] intraday_1620.csv.gz  in=305,867,095 out=59,652,301 elapsed=109.5s

  [7821/21087] intraday_16201.csv.gz  in=305,876,939 out=59,662,145 elapsed=109.5s

  [7822/21087] intraday_16200.csv.gz  in=305,889,034 out=59,674,240 elapsed=109.5s

  [7823/21087] intraday_16202.csv.gz  in=305,901,667 out=59,686,873 elapsed=109.5s

  [7824/21087] intraday_16203.csv.gz  in=305,910,590 out=59,695,796 elapsed=109.5s

  [7825/21087] intraday_16205.csv.gz  in=305,924,103 out=59,709,309 elapsed=109.6s

  [7826/21087] intraday_16204.csv.gz  in=305,936,516 out=59,721,722 elapsed=109.6s

  [7827/21087] intraday_16206.csv.gz  in=305,948,427 out=59,733,633 elapsed=109.6s

  [7828/21087] intraday_16207.csv.gz  in=305,960,086 out=59,745,292 elapsed=109.6s

  [7829/21087] intraday_16208.csv.gz  in=305,969,938 out=59,755,144 elapsed=109.6s

  [7830/21087] intraday_1621.csv.gz  in=305,983,105 out=59,755,144 elapsed=109.6s

  [7831/21087] intraday_16209.csv.gz  in=305,994,135 out=59,766,174 elapsed=109.6s

  [7832/21087] intraday_16210.csv.gz  in=306,007,165 out=59,779,204 elapsed=109.6s

  [7833/21087] intraday_16211.csv.gz  in=306,024,548 out=59,796,587 elapsed=109.6s

  [7834/21087] intraday_16212.csv.gz  in=306,038,880 out=59,810,919 elapsed=109.6s

  [7835/21087] intraday_16213.csv.gz  in=306,052,864 out=59,824,903 elapsed=109.6s

  [7836/21087] intraday_16214.csv.gz  in=306,064,537 out=59,836,576 elapsed=109.7s

  [7837/21087] intraday_16215.csv.gz  in=306,078,723 out=59,850,762 elapsed=109.7s

  [7838/21087] intraday_16216.csv.gz  in=306,089,607 out=59,861,646 elapsed=109.7s

  [7839/21087] intraday_16217.csv.gz  in=306,104,963 out=59,877,002 elapsed=109.7s

  [7840/21087] intraday_16218.csv.gz  in=306,115,183 out=59,887,222 elapsed=109.7s

  [7841/21087] intraday_16219.csv.gz  in=306,128,252 out=59,900,291 elapsed=109.7s

  [7842/21087] intraday_1622.csv.gz  in=306,141,246 out=59,900,291 elapsed=109.7s

  [7843/21087] intraday_16221.csv.gz  in=306,154,645 out=59,913,690 elapsed=109.7s

  [7844/21087] intraday_16220.csv.gz  in=306,166,269 out=59,925,314 elapsed=109.7s

  [7845/21087] intraday_16222.csv.gz  in=306,178,954 out=59,937,999 elapsed=109.8s

  [7846/21087] intraday_16223.csv.gz  in=306,191,699 out=59,950,744 elapsed=109.8s

  [7847/21087] intraday_16225.csv.gz  in=306,201,986 out=59,961,031 elapsed=109.8s

  [7848/21087] intraday_16226.csv.gz  in=306,213,682 out=59,972,727 elapsed=109.8s

  [7849/21087] intraday_16224.csv.gz  in=306,228,025 out=59,987,070 elapsed=109.8s

  [7850/21087] intraday_16227.csv.gz  in=306,240,696 out=59,999,741 elapsed=109.8s

  [7851/21087] intraday_16228.csv.gz  in=306,252,964 out=60,012,009 elapsed=109.8s

  [7852/21087] intraday_1623.csv.gz  in=306,267,634 out=60,012,009 elapsed=109.8s

  [7853/21087] intraday_16229.csv.gz  in=306,280,598 out=60,024,973 elapsed=109.8s

  [7854/21087] intraday_16230.csv.gz  in=306,294,335 out=60,038,710 elapsed=109.8s

  [7855/21087] intraday_16231.csv.gz  in=306,308,026 out=60,052,401 elapsed=109.8s

  [7856/21087] intraday_16232.csv.gz  in=306,318,765 out=60,063,140 elapsed=109.9s

  [7857/21087] intraday_16233.csv.gz  in=306,332,027 out=60,076,402 elapsed=109.9s

  [7858/21087] intraday_16234.csv.gz  in=306,343,656 out=60,088,031 elapsed=109.9s

  [7859/21087] intraday_16235.csv.gz  in=306,356,251 out=60,100,626 elapsed=109.9s

  [7860/21087] intraday_16236.csv.gz  in=306,370,161 out=60,114,536 elapsed=109.9s

  [7861/21087] intraday_16239.csv.gz  in=306,382,000 out=60,126,375 elapsed=109.9s

  [7862/21087] intraday_1624.csv.gz  in=306,393,450 out=60,126,375 elapsed=109.9s

  [7863/21087] intraday_16238.csv.gz  in=306,406,886 out=60,139,811 elapsed=109.9s

  [7864/21087] intraday_16237.csv.gz  in=306,420,044 out=60,152,969 elapsed=109.9s

  [7865/21087] intraday_16241.csv.gz  in=306,434,784 out=60,167,709 elapsed=110.0s

  [7866/21087] intraday_16240.csv.gz  in=306,449,034 out=60,181,959 elapsed=110.0s

  [7867/21087] intraday_16243.csv.gz  in=306,463,837 out=60,196,762 elapsed=110.0s

  [7868/21087] intraday_16242.csv.gz  in=306,478,471 out=60,211,396 elapsed=110.0s

  [7869/21087] intraday_16244.csv.gz  in=306,498,249 out=60,231,174 elapsed=110.0s

  [7870/21087] intraday_16245.csv.gz  in=306,510,245 out=60,243,170 elapsed=110.0s

  [7871/21087] intraday_16247.csv.gz  in=306,522,100 out=60,255,025 elapsed=110.0s

  [7872/21087] intraday_16246.csv.gz  in=306,538,835 out=60,271,760 elapsed=110.0s

  [7873/21087] intraday_1625.csv.gz  in=306,553,110 out=60,271,760 elapsed=110.1s

  [7874/21087] intraday_16249.csv.gz  in=306,563,977 out=60,282,627 elapsed=110.1s

  [7875/21087] intraday_16250.csv.gz  in=306,576,481 out=60,295,131 elapsed=110.1s

  [7876/21087] intraday_16248.csv.gz  in=306,591,228 out=60,309,878 elapsed=110.1s

  [7877/21087] intraday_16251.csv.gz  in=306,602,042 out=60,320,692 elapsed=110.1s

  [7878/21087] intraday_16252.csv.gz  in=306,616,963 out=60,335,613 elapsed=110.1s

  [7879/21087] intraday_16253.csv.gz  in=306,628,306 out=60,346,956 elapsed=110.1s

  [7880/21087] intraday_16254.csv.gz  in=306,643,919 out=60,362,569 elapsed=110.1s

  [7881/21087] intraday_16255.csv.gz  in=306,654,662 out=60,373,312 elapsed=110.1s

  [7882/21087] intraday_16257.csv.gz  in=306,665,285 out=60,383,935 elapsed=110.2s

  [7883/21087] intraday_16256.csv.gz  in=306,677,684 out=60,396,334 elapsed=110.2s

  [7884/21087] intraday_16258.csv.gz  in=306,691,297 out=60,409,947 elapsed=110.2s

  [7885/21087] intraday_1626.csv.gz  in=306,704,893 out=60,409,947 elapsed=110.2s

  [7886/21087] intraday_16259.csv.gz  in=306,717,996 out=60,423,050 elapsed=110.2s

  [7887/21087] intraday_16260.csv.gz  in=306,732,960 out=60,438,014 elapsed=110.2s

  [7888/21087] intraday_16262.csv.gz  in=306,747,151 out=60,452,205 elapsed=110.2s

  [7889/21087] intraday_16261.csv.gz  in=306,761,033 out=60,466,087 elapsed=110.2s

  [7890/21087] intraday_16264.csv.gz  in=306,773,035 out=60,478,089 elapsed=110.2s

  [7891/21087] intraday_16263.csv.gz  in=306,788,295 out=60,493,349 elapsed=110.2s

  [7892/21087] intraday_16266.csv.gz  in=306,801,242 out=60,506,296 elapsed=110.3s

  [7893/21087] intraday_16267.csv.gz  in=306,810,890 out=60,515,944 elapsed=110.3s

  [7894/21087] intraday_16268.csv.gz  in=306,824,247 out=60,529,301 elapsed=110.3s

  [7895/21087] intraday_16265.csv.gz  in=306,836,270 out=60,541,324 elapsed=110.3s

  [7896/21087] intraday_16269.csv.gz  in=306,845,814 out=60,550,868 elapsed=110.3s

  [7897/21087] intraday_1627.csv.gz  in=306,863,203 out=60,550,868 elapsed=110.3s

  [7898/21087] intraday_16271.csv.gz  in=306,874,027 out=60,561,692 elapsed=110.3s

  [7899/21087] intraday_16270.csv.gz  in=306,882,502 out=60,570,167 elapsed=110.3s

  [7900/21087] intraday_16272.csv.gz  in=306,897,747 out=60,585,412 elapsed=110.4s

  [7901/21087] intraday_16273.csv.gz  in=306,911,741 out=60,599,406 elapsed=110.4s

  [7902/21087] intraday_16274.csv.gz  in=306,924,861 out=60,612,526 elapsed=110.4s

  [7903/21087] intraday_16275.csv.gz  in=306,935,594 out=60,623,259 elapsed=110.4s

  [7904/21087] intraday_16276.csv.gz  in=306,947,791 out=60,635,456 elapsed=110.4s

  [7905/21087] intraday_16277.csv.gz  in=306,961,007 out=60,648,672 elapsed=110.4s

  [7906/21087] intraday_1628.csv.gz  in=306,972,235 out=60,648,672 elapsed=110.4s

  [7907/21087] intraday_16278.csv.gz  in=306,984,609 out=60,661,046 elapsed=110.4s

  [7908/21087] intraday_16279.csv.gz  in=306,996,105 out=60,672,542 elapsed=110.4s

  [7909/21087] intraday_16280.csv.gz  in=307,007,957 out=60,684,394 elapsed=110.5s

  [7910/21087] intraday_16281.csv.gz  in=307,021,256 out=60,697,693 elapsed=110.5s

  [7911/21087] intraday_16282.csv.gz  in=307,030,673 out=60,707,110 elapsed=110.5s

  [7912/21087] intraday_16283.csv.gz  in=307,034,028 out=60,710,465 elapsed=110.5s

  [7913/21087] intraday_16284.csv.gz  in=307,041,673 out=60,718,110 elapsed=110.5s

  [7914/21087] intraday_16285.csv.gz  in=307,056,556 out=60,732,993 elapsed=110.5s

  [7915/21087] intraday_16287.csv.gz  in=307,069,330 out=60,745,767 elapsed=110.5s

  [7916/21087] intraday_16286.csv.gz  in=307,083,004 out=60,759,441 elapsed=110.5s

  [7917/21087] intraday_16288.csv.gz  in=307,093,365 out=60,769,802 elapsed=110.5s

  [7918/21087] intraday_16289.csv.gz  in=307,106,349 out=60,782,786 elapsed=110.5s

  [7919/21087] intraday_1629.csv.gz  in=307,119,756 out=60,782,786 elapsed=110.6s

  [7920/21087] intraday_16290.csv.gz  in=307,132,388 out=60,795,418 elapsed=110.6s

  [7921/21087] intraday_16291.csv.gz  in=307,146,882 out=60,808,634 elapsed=110.6s

  [7922/21087] intraday_16292.csv.gz  in=307,159,559 out=60,821,311 elapsed=110.6s

  [7923/21087] intraday_16293.csv.gz  in=307,172,747 out=60,834,338 elapsed=110.6s

  [7924/21087] intraday_16294.csv.gz  in=307,184,675 out=60,846,266 elapsed=110.6s

  [7925/21087] intraday_16295.csv.gz  in=307,194,879 out=60,856,470 elapsed=110.6s

  [7926/21087] intraday_16296.csv.gz  in=307,206,837 out=60,868,428 elapsed=110.6s

  [7927/21087] intraday_16298.csv.gz  in=307,218,991 out=60,880,582 elapsed=110.7s

  [7928/21087] intraday_16297.csv.gz  in=307,231,744 out=60,893,335 elapsed=110.7s

  [7929/21087] intraday_1630.csv.gz  in=307,247,733 out=60,893,335 elapsed=110.7s

  [7930/21087] intraday_16299.csv.gz  in=307,263,200 out=60,908,802 elapsed=110.7s

  [7931/21087] intraday_16301.csv.gz  in=307,274,104 out=60,919,706 elapsed=110.7s

  [7932/21087] intraday_16300.csv.gz  in=307,288,588 out=60,934,190 elapsed=110.7s

  [7933/21087] intraday_16303.csv.gz  in=307,289,058 out=60,934,660 elapsed=110.7s

  [7934/21087] intraday_16302.csv.gz  in=307,290,668 out=60,936,270 elapsed=110.7s

  [7935/21087] intraday_16304.csv.gz  in=307,300,360 out=60,945,962 elapsed=110.7s

  [7936/21087] intraday_16305.csv.gz  in=307,311,450 out=60,957,052 elapsed=110.7s

  [7937/21087] intraday_16306.csv.gz  in=307,321,348 out=60,966,950 elapsed=110.7s

  [7938/21087] intraday_16307.csv.gz  in=307,333,379 out=60,978,981 elapsed=110.7s

  [7939/21087] intraday_16308.csv.gz  in=307,345,606 out=60,991,208 elapsed=110.8s

  [7940/21087] intraday_1631.csv.gz  in=307,358,345 out=60,991,208 elapsed=110.8s

  [7941/21087] intraday_16309.csv.gz  in=307,373,327 out=61,006,190 elapsed=110.8s

  [7942/21087] intraday_16310.csv.gz  in=307,384,414 out=61,017,277 elapsed=110.8s

  [7943/21087] intraday_16312.csv.gz  in=307,394,826 out=61,027,689 elapsed=110.8s

  [7944/21087] intraday_16311.csv.gz  in=307,409,220 out=61,042,083 elapsed=110.8s

  [7945/21087] intraday_16314.csv.gz  in=307,420,468 out=61,053,331 elapsed=110.9s

  [7946/21087] intraday_16313.csv.gz  in=307,432,559 out=61,065,422 elapsed=110.9s

  [7947/21087] intraday_16315.csv.gz  in=307,444,272 out=61,077,135 elapsed=110.9s

  [7948/21087] intraday_16316.csv.gz  in=307,456,958 out=61,089,821 elapsed=110.9s

  [7949/21087] intraday_16317.csv.gz  in=307,467,498 out=61,100,361 elapsed=110.9s

  [7950/21087] intraday_16319.csv.gz  in=307,473,260 out=61,106,123 elapsed=110.9s

  [7951/21087] intraday_1632.csv.gz  in=307,486,303 out=61,106,123 elapsed=110.9s

  [7952/21087] intraday_16318.csv.gz  in=307,496,220 out=61,116,040 elapsed=110.9s

  [7953/21087] intraday_16320.csv.gz  in=307,508,506 out=61,128,326 elapsed=110.9s

  [7954/21087] intraday_16321.csv.gz  in=307,520,363 out=61,140,183 elapsed=111.0s

  [7955/21087] intraday_16322.csv.gz  in=307,531,028 out=61,150,848 elapsed=111.0s

  [7956/21087] intraday_16323.csv.gz  in=307,544,304 out=61,164,124 elapsed=111.0s

  [7957/21087] intraday_16324.csv.gz  in=307,557,349 out=61,177,169 elapsed=111.0s

  [7958/21087] intraday_16325.csv.gz  in=307,569,445 out=61,189,265 elapsed=111.0s

  [7959/21087] intraday_16326.csv.gz  in=307,579,930 out=61,199,750 elapsed=111.0s

  [7960/21087] intraday_16327.csv.gz  in=307,592,108 out=61,211,928 elapsed=111.0s

  [7961/21087] intraday_16328.csv.gz  in=307,607,108 out=61,224,610 elapsed=111.0s

  [7962/21087] intraday_1633.csv.gz  in=307,621,981 out=61,224,610 elapsed=111.0s

  [7963/21087] intraday_16331.csv.gz  in=307,633,208 out=61,235,837 elapsed=111.1s

  [7964/21087] intraday_16329.csv.gz  in=307,646,330 out=61,248,959 elapsed=111.1s

  [7965/21087] intraday_16330.csv.gz  in=307,660,060 out=61,262,689 elapsed=111.1s

  [7966/21087] intraday_16332.csv.gz  in=307,673,495 out=61,276,124 elapsed=111.1s

  [7967/21087] intraday_16334.csv.gz  in=307,674,811 out=61,277,440 elapsed=111.1s

  [7968/21087] intraday_16333.csv.gz  in=307,688,623 out=61,291,252 elapsed=111.1s

  [7969/21087] intraday_16335.csv.gz  in=307,700,282 out=61,302,911 elapsed=111.1s

  [7970/21087] intraday_16336.csv.gz  in=307,712,387 out=61,315,016 elapsed=111.1s

  [7971/21087] intraday_16337.csv.gz  in=307,722,983 out=61,325,612 elapsed=111.1s

  [7972/21087] intraday_16338.csv.gz  in=307,732,539 out=61,335,168 elapsed=111.1s

  [7973/21087] intraday_16339.csv.gz  in=307,743,778 out=61,346,407 elapsed=111.1s

  [7974/21087] intraday_1634.csv.gz  in=307,754,419 out=61,346,407 elapsed=111.1s

  [7975/21087] intraday_16340.csv.gz  in=307,767,974 out=61,359,962 elapsed=111.2s

  [7976/21087] intraday_16341.csv.gz  in=307,779,294 out=61,371,282 elapsed=111.2s

  [7977/21087] intraday_16342.csv.gz  in=307,792,223 out=61,384,211 elapsed=111.2s

  [7978/21087] intraday_16343.csv.gz  in=307,801,738 out=61,393,726 elapsed=111.2s

  [7979/21087] intraday_16344.csv.gz  in=307,813,308 out=61,405,296 elapsed=111.2s

  [7980/21087] intraday_16345.csv.gz  in=307,824,885 out=61,416,873 elapsed=111.2s

  [7981/21087] intraday_16347.csv.gz  in=307,839,078 out=61,431,066 elapsed=111.2s

  [7982/21087] intraday_16346.csv.gz  in=307,854,713 out=61,446,701 elapsed=111.2s

  [7983/21087] intraday_16348.csv.gz  in=307,869,543 out=61,461,531 elapsed=111.2s

  [7984/21087] intraday_1635.csv.gz  in=307,881,466 out=61,461,531 elapsed=111.2s

  [7985/21087] intraday_16349.csv.gz  in=307,894,116 out=61,474,181 elapsed=111.2s

  [7986/21087] intraday_16350.csv.gz  in=307,908,402 out=61,488,467 elapsed=111.3s

  [7987/21087] intraday_16353.csv.gz  in=307,918,592 out=61,498,657 elapsed=111.3s

  [7988/21087] intraday_16351.csv.gz  in=307,929,315 out=61,509,380 elapsed=111.3s

  [7989/21087] intraday_16352.csv.gz  in=307,943,170 out=61,523,235 elapsed=111.3s

  [7990/21087] intraday_16354.csv.gz  in=307,954,536 out=61,534,601 elapsed=111.3s

  [7991/21087] intraday_16356.csv.gz  in=307,959,305 out=61,539,370 elapsed=111.3s

  [7992/21087] intraday_16357.csv.gz  in=307,966,356 out=61,546,421 elapsed=111.3s

  [7993/21087] intraday_16355.csv.gz  in=307,978,228 out=61,558,293 elapsed=111.3s

  [7994/21087] intraday_16358.csv.gz  in=307,988,959 out=61,569,024 elapsed=111.4s

  [7995/21087] intraday_1636.csv.gz  in=308,001,505 out=61,569,024 elapsed=111.4s

  [7996/21087] intraday_16359.csv.gz  in=308,013,549 out=61,581,068 elapsed=111.4s

  [7997/21087] intraday_16360.csv.gz  in=308,024,829 out=61,592,348 elapsed=111.4s

  [7998/21087] intraday_16361.csv.gz  in=308,044,785 out=61,608,066 elapsed=111.4s

  [7999/21087] intraday_16362.csv.gz  in=308,057,212 out=61,620,493 elapsed=111.4s

  [8000/21087] intraday_16363.csv.gz  in=308,069,467 out=61,632,748 elapsed=111.4s

  [8001/21087] intraday_16364.csv.gz  in=308,082,086 out=61,645,367 elapsed=111.4s

  [8002/21087] intraday_16365.csv.gz  in=308,094,229 out=61,657,510 elapsed=111.4s

  [8003/21087] intraday_16366.csv.gz  in=308,106,235 out=61,669,516 elapsed=111.5s

  [8004/21087] intraday_16367.csv.gz  in=308,122,467 out=61,685,748 elapsed=111.5s

  [8005/21087] intraday_16368.csv.gz  in=308,133,338 out=61,696,619 elapsed=111.5s

  [8006/21087] intraday_1637.csv.gz  in=308,147,538 out=61,696,619 elapsed=111.5s

  [8007/21087] intraday_16369.csv.gz  in=308,159,104 out=61,708,185 elapsed=111.5s

  [8008/21087] intraday_16370.csv.gz  in=308,171,777 out=61,720,858 elapsed=111.5s

  [8009/21087] intraday_16371.csv.gz  in=308,186,914 out=61,735,995 elapsed=111.5s

  [8010/21087] intraday_16373.csv.gz  in=308,200,142 out=61,749,223 elapsed=111.5s

  [8011/21087] intraday_16372.csv.gz  in=308,211,519 out=61,760,600 elapsed=111.5s

  [8012/21087] intraday_16374.csv.gz  in=308,224,587 out=61,773,668 elapsed=111.5s

  [8013/21087] intraday_16376.csv.gz  in=308,237,350 out=61,786,431 elapsed=111.6s

  [8014/21087] intraday_16375.csv.gz  in=308,250,030 out=61,799,111 elapsed=111.6s

  [8015/21087] intraday_16377.csv.gz  in=308,268,010 out=61,817,091 elapsed=111.6s

  [8016/21087] intraday_16378.csv.gz  in=308,286,065 out=61,833,980 elapsed=111.6s

  [8017/21087] intraday_16379.csv.gz  in=308,301,435 out=61,849,350 elapsed=111.6s

  [8018/21087] intraday_1638.csv.gz  in=308,317,016 out=61,849,350 elapsed=111.6s

  [8019/21087] intraday_16380.csv.gz  in=308,333,166 out=61,865,500 elapsed=111.6s

  [8020/21087] intraday_16381.csv.gz  in=308,345,870 out=61,878,204 elapsed=111.6s

  [8021/21087] intraday_16382.csv.gz  in=308,359,359 out=61,891,693 elapsed=111.6s

  [8022/21087] intraday_16383.csv.gz  in=308,369,235 out=61,901,569 elapsed=111.6s

  [8023/21087] intraday_16384.csv.gz  in=308,381,832 out=61,914,166 elapsed=111.7s

  [8024/21087] intraday_16385.csv.gz  in=308,393,137 out=61,925,471 elapsed=111.7s

  [8025/21087] intraday_16386.csv.gz  in=308,405,817 out=61,938,151 elapsed=111.7s

  [8026/21087] intraday_16387.csv.gz  in=308,419,794 out=61,952,128 elapsed=111.7s

  [8027/21087] intraday_16388.csv.gz  in=308,433,087 out=61,965,421 elapsed=111.7s

  [8028/21087] intraday_16389.csv.gz  in=308,443,088 out=61,975,422 elapsed=111.7s

  [8029/21087] intraday_1639.csv.gz  in=308,456,316 out=61,975,422 elapsed=111.7s

  [8030/21087] intraday_16390.csv.gz  in=308,467,966 out=61,987,072 elapsed=111.8s

  [8031/21087] intraday_16391.csv.gz  in=308,480,533 out=61,999,639 elapsed=111.8s

  [8032/21087] intraday_16392.csv.gz  in=308,492,903 out=62,012,009 elapsed=111.8s

  [8033/21087] intraday_16393.csv.gz  in=308,504,570 out=62,023,676 elapsed=111.8s

  [8034/21087] intraday_16394.csv.gz  in=308,505,850 out=62,024,956 elapsed=111.8s

  [8035/21087] intraday_16395.csv.gz  in=308,520,157 out=62,039,263 elapsed=111.8s

  [8036/21087] intraday_16396.csv.gz  in=308,531,657 out=62,050,763 elapsed=111.8s

  [8037/21087] intraday_16397.csv.gz  in=308,543,901 out=62,063,007 elapsed=111.8s

  [8038/21087] intraday_16398.csv.gz  in=308,555,955 out=62,075,061 elapsed=111.8s

  [8039/21087] intraday_16399.csv.gz  in=308,566,684 out=62,085,790 elapsed=111.8s

  [8040/21087] intraday_16401.csv.gz  in=308,574,444 out=62,093,550 elapsed=111.8s

  [8041/21087] intraday_1640.csv.gz  in=308,588,384 out=62,093,550 elapsed=111.8s

  [8042/21087] intraday_16400.csv.gz  in=308,600,380 out=62,105,546 elapsed=111.9s

  [8043/21087] intraday_16402.csv.gz  in=308,610,259 out=62,115,425 elapsed=111.9s

  [8044/21087] intraday_16403.csv.gz  in=308,616,244 out=62,121,410 elapsed=111.9s

  [8045/21087] intraday_16404.csv.gz  in=308,631,973 out=62,137,139 elapsed=111.9s

  [8046/21087] intraday_16405.csv.gz  in=308,646,202 out=62,151,368 elapsed=111.9s

  [8047/21087] intraday_16407.csv.gz  in=308,656,612 out=62,161,778 elapsed=111.9s

  [8048/21087] intraday_16406.csv.gz  in=308,672,650 out=62,177,816 elapsed=111.9s

  [8049/21087] intraday_16408.csv.gz  in=308,684,839 out=62,190,005 elapsed=111.9s

  [8050/21087] intraday_1641.csv.gz  in=308,698,939 out=62,190,005 elapsed=111.9s

  [8051/21087] intraday_16409.csv.gz  in=308,713,953 out=62,205,019 elapsed=111.9s

  [8052/21087] intraday_16411.csv.gz  in=308,713,991 out=62,205,057 elapsed=111.9s

  [8053/21087] intraday_16410.csv.gz  in=308,724,625 out=62,215,691 elapsed=111.9s

  [8054/21087] intraday_16412.csv.gz  in=308,728,634 out=62,219,700 elapsed=112.0s

  [8055/21087] intraday_16413.csv.gz  in=308,741,017 out=62,232,083 elapsed=112.0s

  [8056/21087] intraday_16415.csv.gz  in=308,753,244 out=62,244,310 elapsed=112.0s

  [8057/21087] intraday_16414.csv.gz  in=308,767,422 out=62,258,488 elapsed=112.0s

  [8058/21087] intraday_16416.csv.gz  in=308,777,662 out=62,268,728 elapsed=112.0s

  [8059/21087] intraday_16417.csv.gz  in=308,790,298 out=62,281,364 elapsed=112.0s

  [8060/21087] intraday_16419.csv.gz  in=308,803,896 out=62,294,962 elapsed=112.0s

  [8061/21087] intraday_16418.csv.gz  in=308,818,580 out=62,309,646 elapsed=112.0s

  [8062/21087] intraday_1642.csv.gz  in=308,831,754 out=62,309,646 elapsed=112.0s

  [8063/21087] intraday_16420.csv.gz  in=308,842,666 out=62,320,558 elapsed=112.0s

  [8064/21087] intraday_16421.csv.gz  in=308,853,260 out=62,331,152 elapsed=112.1s

  [8065/21087] intraday_16423.csv.gz  in=308,866,224 out=62,344,116 elapsed=112.1s

  [8066/21087] intraday_16422.csv.gz  in=308,878,680 out=62,356,572 elapsed=112.1s

  [8067/21087] intraday_16424.csv.gz  in=308,891,365 out=62,369,257 elapsed=112.1s

  [8068/21087] intraday_16425.csv.gz  in=308,903,961 out=62,381,853 elapsed=112.1s

  [8069/21087] intraday_16426.csv.gz  in=308,915,572 out=62,393,464 elapsed=112.1s

  [8070/21087] intraday_16427.csv.gz  in=308,927,018 out=62,404,910 elapsed=112.1s

  [8071/21087] intraday_16428.csv.gz  in=308,938,011 out=62,415,903 elapsed=112.1s

  [8072/21087] intraday_16429.csv.gz  in=308,949,571 out=62,427,463 elapsed=112.1s

  [8073/21087] intraday_16430.csv.gz  in=308,950,810 out=62,428,702 elapsed=112.2s

  [8074/21087] intraday_1643.csv.gz  in=308,963,214 out=62,428,702 elapsed=112.2s

  [8075/21087] intraday_16431.csv.gz  in=308,972,386 out=62,437,874 elapsed=112.2s

  [8076/21087] intraday_16432.csv.gz  in=308,984,960 out=62,450,448 elapsed=112.2s

  [8077/21087] intraday_16433.csv.gz  in=308,998,443 out=62,463,931 elapsed=112.2s

  [8078/21087] intraday_16434.csv.gz  in=309,011,683 out=62,477,171 elapsed=112.2s

  [8079/21087] intraday_16435.csv.gz  in=309,024,239 out=62,489,727 elapsed=112.2s

  [8080/21087] intraday_16437.csv.gz  in=309,035,072 out=62,500,560 elapsed=112.2s

  [8081/21087] intraday_16438.csv.gz  in=309,045,070 out=62,510,558 elapsed=112.2s

  [8082/21087] intraday_16436.csv.gz  in=309,070,141 out=62,530,910 elapsed=112.3s

  [8083/21087] intraday_1644.csv.gz  in=309,086,199 out=62,530,910 elapsed=112.3s

  [8084/21087] intraday_16439.csv.gz  in=309,098,526 out=62,543,237 elapsed=112.3s

  [8085/21087] intraday_16440.csv.gz  in=309,110,850 out=62,555,561 elapsed=112.3s

  [8086/21087] intraday_16443.csv.gz  in=309,123,590 out=62,568,301 elapsed=112.3s

  [8087/21087] intraday_16442.csv.gz  in=309,136,900 out=62,581,611 elapsed=112.3s

  [8088/21087] intraday_16441.csv.gz  in=309,150,540 out=62,595,251 elapsed=112.3s

  [8089/21087] intraday_16444.csv.gz  in=309,161,612 out=62,606,323 elapsed=112.3s

  [8090/21087] intraday_16447.csv.gz  in=309,173,869 out=62,618,580 elapsed=112.4s

  [8091/21087] intraday_16445.csv.gz  in=309,185,578 out=62,630,289 elapsed=112.4s

  [8092/21087] intraday_16446.csv.gz  in=309,198,607 out=62,643,318 elapsed=112.4s

  [8093/21087] intraday_16448.csv.gz  in=309,211,242 out=62,655,953 elapsed=112.4s

  [8094/21087] intraday_1645.csv.gz  in=309,226,675 out=62,655,953 elapsed=112.4s

  [8095/21087] intraday_16449.csv.gz  in=309,237,738 out=62,667,016 elapsed=112.4s

  [8096/21087] intraday_16451.csv.gz  in=309,249,420 out=62,678,698 elapsed=112.4s

  [8097/21087] intraday_16450.csv.gz  in=309,263,574 out=62,692,852 elapsed=112.4s

  [8098/21087] intraday_16452.csv.gz  in=309,278,157 out=62,707,435 elapsed=112.4s

  [8099/21087] intraday_16453.csv.gz  in=309,290,972 out=62,720,250 elapsed=112.4s

  [8100/21087] intraday_16454.csv.gz  in=309,303,080 out=62,732,358 elapsed=112.5s

  [8101/21087] intraday_16455.csv.gz  in=309,314,675 out=62,743,953 elapsed=112.5s

  [8102/21087] intraday_16456.csv.gz  in=309,327,030 out=62,756,308 elapsed=112.5s

  [8103/21087] intraday_16457.csv.gz  in=309,340,169 out=62,769,447 elapsed=112.5s

  [8104/21087] intraday_16458.csv.gz  in=309,352,078 out=62,781,356 elapsed=112.5s

  [8105/21087] intraday_1646.csv.gz  in=309,364,385 out=62,781,356 elapsed=112.5s

  [8106/21087] intraday_16459.csv.gz  in=309,377,216 out=62,794,187 elapsed=112.5s

  [8107/21087] intraday_16460.csv.gz  in=309,384,564 out=62,801,535 elapsed=112.5s

  [8108/21087] intraday_16461.csv.gz  in=309,397,323 out=62,814,294 elapsed=112.5s

  [8109/21087] intraday_16462.csv.gz  in=309,411,038 out=62,828,009 elapsed=112.5s

  [8110/21087] intraday_16463.csv.gz  in=309,423,638 out=62,840,609 elapsed=112.6s

  [8111/21087] intraday_16464.csv.gz  in=309,435,232 out=62,852,203 elapsed=112.6s

  [8112/21087] intraday_16465.csv.gz  in=309,444,858 out=62,861,829 elapsed=112.6s

  [8113/21087] intraday_16466.csv.gz  in=309,456,328 out=62,873,299 elapsed=112.6s

  [8114/21087] intraday_16467.csv.gz  in=309,469,666 out=62,886,637 elapsed=112.6s

  [8115/21087] intraday_16469.csv.gz  in=309,480,837 out=62,897,808 elapsed=112.6s

  [8116/21087] intraday_16468.csv.gz  in=309,493,312 out=62,910,283 elapsed=112.6s

  [8117/21087] intraday_1647.csv.gz  in=309,508,252 out=62,910,283 elapsed=112.6s

  [8118/21087] intraday_16471.csv.gz  in=309,517,174 out=62,919,205 elapsed=112.6s

  [8119/21087] intraday_16470.csv.gz  in=309,530,081 out=62,932,112 elapsed=112.6s

  [8120/21087] intraday_16473.csv.gz  in=309,542,958 out=62,944,989 elapsed=112.6s

  [8121/21087] intraday_16472.csv.gz  in=309,556,798 out=62,958,829 elapsed=112.6s

  [8122/21087] intraday_16474.csv.gz  in=309,569,015 out=62,971,046 elapsed=112.7s

  [8123/21087] intraday_16476.csv.gz  in=309,579,605 out=62,981,636 elapsed=112.7s

  [8124/21087] intraday_16477.csv.gz  in=309,590,278 out=62,992,309 elapsed=112.7s

  [8125/21087] intraday_16475.csv.gz  in=309,601,842 out=63,003,873 elapsed=112.7s

  [8126/21087] intraday_16478.csv.gz  in=309,613,922 out=63,015,953 elapsed=112.7s

  [8127/21087] intraday_1648.csv.gz  in=309,624,814 out=63,015,953 elapsed=112.7s

  [8128/21087] intraday_16480.csv.gz  in=309,633,667 out=63,024,806 elapsed=112.8s

  [8129/21087] intraday_16481.csv.gz  in=309,643,097 out=63,034,236 elapsed=112.8s

  [8130/21087] intraday_16479.csv.gz  in=309,661,916 out=63,053,055 elapsed=112.8s

  [8131/21087] intraday_16483.csv.gz  in=309,672,268 out=63,063,407 elapsed=112.8s

  [8132/21087] intraday_16482.csv.gz  in=309,690,082 out=63,081,221 elapsed=112.8s

  [8133/21087] intraday_16485.csv.gz  in=309,701,470 out=63,092,609 elapsed=112.8s

  [8134/21087] intraday_16484.csv.gz  in=309,714,126 out=63,105,265 elapsed=112.8s

  [8135/21087] intraday_16486.csv.gz  in=309,726,280 out=63,117,419 elapsed=112.8s

  [8136/21087] intraday_16487.csv.gz  in=309,739,261 out=63,130,400 elapsed=112.8s

  [8137/21087] intraday_1649.csv.gz  in=309,750,727 out=63,130,400 elapsed=112.8s

  [8138/21087] intraday_16490.csv.gz  in=309,761,363 out=63,141,036 elapsed=112.9s

  [8139/21087] intraday_16489.csv.gz  in=309,775,990 out=63,155,663 elapsed=112.9s

  [8140/21087] intraday_16488.csv.gz  in=309,790,185 out=63,168,243 elapsed=112.9s

  [8141/21087] intraday_16491.csv.gz  in=309,800,756 out=63,178,814 elapsed=112.9s

  [8142/21087] intraday_16493.csv.gz  in=309,813,416 out=63,191,474 elapsed=112.9s

  [8143/21087] intraday_16492.csv.gz  in=309,826,458 out=63,204,516 elapsed=112.9s

  [8144/21087] intraday_16495.csv.gz  in=309,839,999 out=63,218,057 elapsed=112.9s

  [8145/21087] intraday_16494.csv.gz  in=309,852,516 out=63,230,574 elapsed=112.9s

  [8146/21087] intraday_16496.csv.gz  in=309,865,511 out=63,243,569 elapsed=112.9s

  [8147/21087] intraday_16497.csv.gz  in=309,876,415 out=63,254,473 elapsed=113.0s

  [8148/21087] intraday_1650.csv.gz  in=309,888,612 out=63,254,473 elapsed=113.0s

  [8149/21087] intraday_16498.csv.gz  in=309,903,194 out=63,269,055 elapsed=113.0s

  [8150/21087] intraday_16500.csv.gz  in=309,914,896 out=63,280,757 elapsed=113.0s

  [8151/21087] intraday_16499.csv.gz  in=309,968,253 out=63,329,054 elapsed=113.0s

  [8152/21087] intraday_16501.csv.gz  in=309,981,005 out=63,341,806 elapsed=113.0s

  [8153/21087] intraday_16502.csv.gz  in=309,995,009 out=63,355,810 elapsed=113.0s

  [8154/21087] intraday_16503.csv.gz  in=310,007,903 out=63,368,704 elapsed=113.0s

  [8155/21087] intraday_16504.csv.gz  in=310,019,934 out=63,380,735 elapsed=113.1s

  [8156/21087] intraday_16505.csv.gz  in=310,033,411 out=63,394,212 elapsed=113.1s

  [8157/21087] intraday_16506.csv.gz  in=310,047,580 out=63,408,381 elapsed=113.1s

  [8158/21087] intraday_16507.csv.gz  in=310,062,300 out=63,423,101 elapsed=113.1s

  [8159/21087] intraday_16508.csv.gz  in=310,077,263 out=63,438,064 elapsed=113.1s

  [8160/21087] intraday_1651.csv.gz  in=310,088,892 out=63,438,064 elapsed=113.1s

  [8161/21087] intraday_16510.csv.gz  in=310,102,635 out=63,451,807 elapsed=113.1s

  [8162/21087] intraday_16509.csv.gz  in=310,120,670 out=63,469,842 elapsed=113.1s

  [8163/21087] intraday_16511.csv.gz  in=310,136,323 out=63,485,495 elapsed=113.1s

  [8164/21087] intraday_16512.csv.gz  in=310,148,217 out=63,497,389 elapsed=113.1s

  [8165/21087] intraday_16513.csv.gz  in=310,150,000 out=63,499,172 elapsed=113.1s

  [8166/21087] intraday_16514.csv.gz  in=310,157,058 out=63,506,230 elapsed=113.2s

  [8167/21087] intraday_16516.csv.gz  in=310,170,268 out=63,519,440 elapsed=113.2s

  [8168/21087] intraday_16515.csv.gz  in=310,183,778 out=63,532,950 elapsed=113.2s

  [8169/21087] intraday_16517.csv.gz  in=310,199,871 out=63,549,043 elapsed=113.2s

  [8170/21087] intraday_16518.csv.gz  in=310,210,816 out=63,559,988 elapsed=113.2s

  [8171/21087] intraday_1652.csv.gz  in=310,220,512 out=63,559,988 elapsed=113.2s

  [8172/21087] intraday_16521.csv.gz  in=310,233,698 out=63,573,174 elapsed=113.2s

  [8173/21087] intraday_16520.csv.gz  in=310,245,009 out=63,584,485 elapsed=113.2s

  [8174/21087] intraday_16519.csv.gz  in=310,257,599 out=63,597,075 elapsed=113.3s

  [8175/21087] intraday_16522.csv.gz  in=310,269,859 out=63,609,335 elapsed=113.3s

  [8176/21087] intraday_16523.csv.gz  in=310,283,899 out=63,623,375 elapsed=113.3s

  [8177/21087] intraday_16524.csv.gz  in=310,298,209 out=63,637,685 elapsed=113.3s

  [8178/21087] intraday_16525.csv.gz  in=310,312,703 out=63,652,179 elapsed=113.3s

  [8179/21087] intraday_16526.csv.gz  in=310,327,303 out=63,666,779 elapsed=113.3s

  [8180/21087] intraday_16527.csv.gz  in=310,340,160 out=63,679,636 elapsed=113.3s

  [8181/21087] intraday_1653.csv.gz  in=310,348,474 out=63,679,636 elapsed=113.3s

  [8182/21087] intraday_16528.csv.gz  in=310,360,922 out=63,692,084 elapsed=113.4s

  [8183/21087] intraday_16530.csv.gz  in=310,371,512 out=63,702,674 elapsed=113.4s

  [8184/21087] intraday_16529.csv.gz  in=310,384,269 out=63,715,431 elapsed=113.4s

  [8185/21087] intraday_16531.csv.gz  in=310,396,946 out=63,728,108 elapsed=113.4s

  [8186/21087] intraday_16532.csv.gz  in=310,405,711 out=63,736,873 elapsed=113.4s

  [8187/21087] intraday_16533.csv.gz  in=310,416,256 out=63,747,418 elapsed=113.4s

  [8188/21087] intraday_16534.csv.gz  in=310,426,624 out=63,757,786 elapsed=113.4s

  [8189/21087] intraday_16535.csv.gz  in=310,442,474 out=63,773,636 elapsed=113.4s

  [8190/21087] intraday_16536.csv.gz  in=310,456,343 out=63,787,505 elapsed=113.4s

  [8191/21087] intraday_16537.csv.gz  in=310,470,245 out=63,801,407 elapsed=113.4s

  [8192/21087] intraday_1654.csv.gz  in=310,481,202 out=63,801,407 elapsed=113.4s

  [8193/21087] intraday_16538.csv.gz  in=310,492,876 out=63,813,081 elapsed=113.5s

  [8194/21087] intraday_16539.csv.gz  in=310,504,182 out=63,824,387 elapsed=113.5s

  [8195/21087] intraday_16541.csv.gz  in=310,512,171 out=63,832,376 elapsed=113.5s

  [8196/21087] intraday_16540.csv.gz  in=310,526,626 out=63,846,831 elapsed=113.5s

  [8197/21087] intraday_16542.csv.gz  in=310,536,312 out=63,856,517 elapsed=113.5s

  [8198/21087] intraday_16543.csv.gz  in=310,548,541 out=63,868,746 elapsed=113.5s

  [8199/21087] intraday_16544.csv.gz  in=310,562,006 out=63,882,211 elapsed=113.5s

  [8200/21087] intraday_16545.csv.gz  in=310,574,791 out=63,894,996 elapsed=113.6s

  [8201/21087] intraday_16547.csv.gz  in=310,585,853 out=63,906,058 elapsed=113.6s

  [8202/21087] intraday_16546.csv.gz  in=310,596,432 out=63,916,637 elapsed=113.6s

  [8203/21087] intraday_16548.csv.gz  in=310,610,840 out=63,931,045 elapsed=113.6s

  [8204/21087] intraday_1655.csv.gz  in=310,614,920 out=63,931,045 elapsed=113.6s

  [8205/21087] intraday_16549.csv.gz  in=310,628,260 out=63,944,385 elapsed=113.6s

  [8206/21087] intraday_16551.csv.gz  in=310,638,627 out=63,954,752 elapsed=113.6s

  [8207/21087] intraday_16550.csv.gz  in=310,649,946 out=63,966,071 elapsed=113.6s

  [8208/21087] intraday_16552.csv.gz  in=310,663,126 out=63,979,251 elapsed=113.7s

  [8209/21087] intraday_16553.csv.gz  in=310,674,995 out=63,991,120 elapsed=113.7s

  [8210/21087] intraday_16554.csv.gz  in=310,687,192 out=64,003,317 elapsed=113.7s

  [8211/21087] intraday_16555.csv.gz  in=310,699,152 out=64,015,277 elapsed=113.7s

  [8212/21087] intraday_16556.csv.gz  in=310,711,176 out=64,027,301 elapsed=113.7s

  [8213/21087] intraday_16557.csv.gz  in=310,722,112 out=64,038,237 elapsed=113.7s

  [8214/21087] intraday_16559.csv.gz  in=310,725,118 out=64,041,243 elapsed=113.7s

  [8215/21087] intraday_16558.csv.gz  in=310,736,177 out=64,052,302 elapsed=113.7s

  [8216/21087] intraday_1656.csv.gz  in=310,750,629 out=64,052,302 elapsed=113.7s

  [8217/21087] intraday_16560.csv.gz  in=310,760,243 out=64,061,916 elapsed=113.7s

  [8218/21087] intraday_16562.csv.gz  in=310,770,583 out=64,072,256 elapsed=113.8s

  [8219/21087] intraday_16563.csv.gz  in=310,784,682 out=64,086,355 elapsed=113.8s

  [8220/21087] intraday_16561.csv.gz  in=310,806,481 out=64,105,687 elapsed=113.8s

  [8221/21087] intraday_16564.csv.gz  in=310,829,076 out=64,124,878 elapsed=113.8s

  [8222/21087] intraday_16565.csv.gz  in=310,842,050 out=64,137,852 elapsed=113.8s

  [8223/21087] intraday_16566.csv.gz  in=310,855,909 out=64,151,711 elapsed=113.8s

  [8224/21087] intraday_16567.csv.gz  in=310,868,052 out=64,163,854 elapsed=113.8s

  [8225/21087] intraday_16568.csv.gz  in=310,878,472 out=64,174,274 elapsed=113.8s

  [8226/21087] intraday_1657.csv.gz  in=310,892,603 out=64,174,274 elapsed=113.8s

  [8227/21087] intraday_16569.csv.gz  in=310,901,805 out=64,183,476 elapsed=113.8s

  [8228/21087] intraday_16570.csv.gz  in=310,913,798 out=64,195,469 elapsed=113.8s

  [8229/21087] intraday_16571.csv.gz  in=310,925,823 out=64,207,494 elapsed=113.8s

  [8230/21087] intraday_16572.csv.gz  in=310,939,515 out=64,221,186 elapsed=113.9s

  [8231/21087] intraday_16574.csv.gz  in=310,952,400 out=64,234,071 elapsed=113.9s

  [8232/21087] intraday_16573.csv.gz  in=310,965,196 out=64,246,867 elapsed=113.9s

  [8233/21087] intraday_16575.csv.gz  in=310,975,292 out=64,256,963 elapsed=113.9s

  [8234/21087] intraday_16576.csv.gz  in=310,987,060 out=64,268,731 elapsed=113.9s

  [8235/21087] intraday_1658.csv.gz  in=310,998,926 out=64,268,731 elapsed=113.9s

  [8236/21087] intraday_16578.csv.gz  in=311,009,820 out=64,279,625 elapsed=113.9s

  [8237/21087] intraday_16577.csv.gz  in=311,022,401 out=64,292,206 elapsed=113.9s

  [8238/21087] intraday_16579.csv.gz  in=311,035,757 out=64,305,562 elapsed=113.9s

  [8239/21087] intraday_16580.csv.gz  in=311,045,518 out=64,315,323 elapsed=114.0s

  [8240/21087] intraday_16581.csv.gz  in=311,058,936 out=64,328,741 elapsed=114.0s

  [8241/21087] intraday_16582.csv.gz  in=311,071,703 out=64,341,508 elapsed=114.0s

  [8242/21087] intraday_16583.csv.gz  in=311,085,688 out=64,355,493 elapsed=114.0s

  [8243/21087] intraday_16584.csv.gz  in=311,100,030 out=64,369,835 elapsed=114.0s

  [8244/21087] intraday_16588.csv.gz  in=311,102,385 out=64,372,190 elapsed=114.0s

  [8245/21087] intraday_16585.csv.gz  in=311,114,012 out=64,383,817 elapsed=114.0s

  [8246/21087] intraday_16587.csv.gz  in=311,125,823 out=64,395,628 elapsed=114.0s

  [8247/21087] intraday_16586.csv.gz  in=311,136,373 out=64,406,178 elapsed=114.0s

  [8248/21087] intraday_16589.csv.gz  in=311,139,908 out=64,409,713 elapsed=114.1s

  [8249/21087] intraday_1659.csv.gz  in=311,151,199 out=64,409,713 elapsed=114.1s

  [8250/21087] intraday_16591.csv.gz  in=311,160,897 out=64,419,411 elapsed=114.1s

  [8251/21087] intraday_16590.csv.gz  in=311,172,597 out=64,431,111 elapsed=114.1s

  [8252/21087] intraday_16592.csv.gz  in=311,188,078 out=64,446,592 elapsed=114.1s

  [8253/21087] intraday_16593.csv.gz  in=311,201,003 out=64,459,517 elapsed=114.1s

  [8254/21087] intraday_16594.csv.gz  in=311,214,029 out=64,472,543 elapsed=114.1s

  [8255/21087] intraday_16595.csv.gz  in=311,226,869 out=64,485,383 elapsed=114.1s

  [8256/21087] intraday_16596.csv.gz  in=311,238,119 out=64,496,633 elapsed=114.1s

  [8257/21087] intraday_16597.csv.gz  in=311,247,570 out=64,506,084 elapsed=114.1s

  [8258/21087] intraday_16598.csv.gz  in=311,259,262 out=64,517,776 elapsed=114.2s

  [8259/21087] intraday_16599.csv.gz  in=311,272,533 out=64,531,047 elapsed=114.2s

  [8260/21087] intraday_1660.csv.gz  in=311,286,085 out=64,531,047 elapsed=114.2s

  [8261/21087] intraday_16600.csv.gz  in=311,299,358 out=64,544,320 elapsed=114.2s

  [8262/21087] intraday_16603.csv.gz  in=311,309,029 out=64,553,991 elapsed=114.2s

  [8263/21087] intraday_16601.csv.gz  in=311,319,213 out=64,564,175 elapsed=114.2s

  [8264/21087] intraday_16602.csv.gz  in=311,331,794 out=64,576,756 elapsed=114.2s

  [8265/21087] intraday_16604.csv.gz  in=311,345,648 out=64,590,610 elapsed=114.2s

  [8266/21087] intraday_16606.csv.gz  in=311,357,111 out=64,602,073 elapsed=114.2s

  [8267/21087] intraday_16605.csv.gz  in=311,370,111 out=64,615,073 elapsed=114.3s

  [8268/21087] intraday_16607.csv.gz  in=311,382,251 out=64,627,213 elapsed=114.3s

  [8269/21087] intraday_16608.csv.gz  in=311,392,197 out=64,637,159 elapsed=114.3s

  [8270/21087] intraday_16609.csv.gz  in=311,404,180 out=64,649,142 elapsed=114.3s

  [8271/21087] intraday_16610.csv.gz  in=311,409,369 out=64,654,331 elapsed=114.3s

  [8272/21087] intraday_1661.csv.gz  in=311,423,080 out=64,654,331 elapsed=114.3s

  [8273/21087] intraday_16611.csv.gz  in=311,428,886 out=64,660,137 elapsed=114.3s

  [8274/21087] intraday_16612.csv.gz  in=311,441,206 out=64,672,457 elapsed=114.3s

  [8275/21087] intraday_16613.csv.gz  in=311,453,852 out=64,685,103 elapsed=114.3s

  [8276/21087] intraday_16614.csv.gz  in=311,467,177 out=64,698,428 elapsed=114.3s

  [8277/21087] intraday_16615.csv.gz  in=311,480,558 out=64,711,809 elapsed=114.3s

  [8278/21087] intraday_16616.csv.gz  in=311,490,643 out=64,721,894 elapsed=114.4s

  [8279/21087] intraday_16617.csv.gz  in=311,502,730 out=64,733,981 elapsed=114.4s

  [8280/21087] intraday_16618.csv.gz  in=311,513,035 out=64,744,286 elapsed=114.4s

  [8281/21087] intraday_16619.csv.gz  in=311,525,866 out=64,757,117 elapsed=114.4s

  [8282/21087] intraday_1662.csv.gz  in=311,538,223 out=64,757,117 elapsed=114.4s

  [8283/21087] intraday_16620.csv.gz  in=311,549,955 out=64,768,849 elapsed=114.4s

  [8284/21087] intraday_16621.csv.gz  in=311,561,660 out=64,780,554 elapsed=114.4s

  [8285/21087] intraday_16622.csv.gz  in=311,575,244 out=64,794,138 elapsed=114.4s

  [8286/21087] intraday_16623.csv.gz  in=311,586,323 out=64,805,217 elapsed=114.4s

  [8287/21087] intraday_16624.csv.gz  in=311,596,262 out=64,815,156 elapsed=114.4s

  [8288/21087] intraday_16625.csv.gz  in=311,609,658 out=64,828,552 elapsed=114.4s

  [8289/21087] intraday_16626.csv.gz  in=311,621,716 out=64,840,610 elapsed=114.5s

  [8290/21087] intraday_16628.csv.gz  in=311,634,909 out=64,853,803 elapsed=114.5s

  [8291/21087] intraday_16629.csv.gz  in=311,648,056 out=64,866,950 elapsed=114.5s

  [8292/21087] intraday_16627.csv.gz  in=311,687,317 out=64,896,588 elapsed=114.5s

  [8293/21087] intraday_1663.csv.gz  in=311,699,372 out=64,896,588 elapsed=114.5s

  [8294/21087] intraday_16630.csv.gz  in=311,710,842 out=64,908,058 elapsed=114.5s

  [8295/21087] intraday_16631.csv.gz  in=311,724,268 out=64,921,484 elapsed=114.5s

  [8296/21087] intraday_16632.csv.gz  in=311,736,982 out=64,934,198 elapsed=114.5s

  [8297/21087] intraday_16633.csv.gz  in=311,748,069 out=64,945,285 elapsed=114.5s

  [8298/21087] intraday_16634.csv.gz  in=311,761,753 out=64,958,969 elapsed=114.6s

  [8299/21087] intraday_16635.csv.gz  in=311,775,175 out=64,972,391 elapsed=114.6s

  [8300/21087] intraday_16637.csv.gz  in=311,782,186 out=64,979,402 elapsed=114.6s

  [8301/21087] intraday_16636.csv.gz  in=311,795,505 out=64,992,721 elapsed=114.6s

  [8302/21087] intraday_16638.csv.gz  in=311,807,427 out=65,004,643 elapsed=114.6s

  [8303/21087] intraday_1664.csv.gz  in=311,821,292 out=65,004,643 elapsed=114.6s

  [8304/21087] intraday_16640.csv.gz  in=311,833,961 out=65,017,312 elapsed=114.6s

  [8305/21087] intraday_16641.csv.gz  in=311,850,478 out=65,033,829 elapsed=114.6s

  [8306/21087] intraday_16642.csv.gz  in=311,862,931 out=65,046,282 elapsed=114.6s

  [8307/21087] intraday_16643.csv.gz  in=311,876,364 out=65,059,715 elapsed=114.7s

  [8308/21087] intraday_16639.csv.gz  in=311,915,031 out=65,095,417 elapsed=114.7s

  [8309/21087] intraday_16644.csv.gz  in=311,925,540 out=65,105,926 elapsed=114.7s

  [8310/21087] intraday_16646.csv.gz  in=311,936,657 out=65,117,043 elapsed=114.7s

  [8311/21087] intraday_16645.csv.gz  in=311,949,189 out=65,129,575 elapsed=114.7s

  [8312/21087] intraday_16647.csv.gz  in=311,961,771 out=65,142,157 elapsed=114.7s

  [8313/21087] intraday_16648.csv.gz  in=311,974,529 out=65,154,915 elapsed=114.7s

  [8314/21087] intraday_1665.csv.gz  in=311,988,741 out=65,154,915 elapsed=114.7s

  [8315/21087] intraday_16649.csv.gz  in=312,005,175 out=65,171,349 elapsed=114.7s

  [8316/21087] intraday_16650.csv.gz  in=312,014,951 out=65,181,125 elapsed=114.7s

  [8317/21087] intraday_16651.csv.gz  in=312,027,720 out=65,193,894 elapsed=114.8s

  [8318/21087] intraday_16652.csv.gz  in=312,040,086 out=65,206,260 elapsed=114.8s

  [8319/21087] intraday_16653.csv.gz  in=312,053,794 out=65,219,968 elapsed=114.8s

  [8320/21087] intraday_16654.csv.gz  in=312,065,248 out=65,231,422 elapsed=114.8s

  [8321/21087] intraday_16655.csv.gz  in=312,078,704 out=65,244,878 elapsed=114.8s

  [8322/21087] intraday_16656.csv.gz  in=312,092,496 out=65,258,670 elapsed=114.8s

  [8323/21087] intraday_16657.csv.gz  in=312,106,558 out=65,272,732 elapsed=114.8s

  [8324/21087] intraday_16658.csv.gz  in=312,120,951 out=65,287,125 elapsed=114.8s

  [8325/21087] intraday_1666.csv.gz  in=312,130,241 out=65,287,125 elapsed=114.8s

  [8326/21087] intraday_16659.csv.gz  in=312,141,605 out=65,298,489 elapsed=114.8s

  [8327/21087] intraday_16660.csv.gz  in=312,154,638 out=65,311,522 elapsed=114.9s

  [8328/21087] intraday_16661.csv.gz  in=312,166,749 out=65,323,633 elapsed=114.9s

  [8329/21087] intraday_16662.csv.gz  in=312,177,118 out=65,334,002 elapsed=114.9s

  [8330/21087] intraday_16663.csv.gz  in=312,189,940 out=65,346,824 elapsed=114.9s

  [8331/21087] intraday_16664.csv.gz  in=312,199,081 out=65,355,965 elapsed=114.9s

  [8332/21087] intraday_16665.csv.gz  in=312,207,545 out=65,364,429 elapsed=114.9s

  [8333/21087] intraday_16666.csv.gz  in=312,219,826 out=65,376,710 elapsed=114.9s

  [8334/21087] intraday_16667.csv.gz  in=312,235,563 out=65,392,447 elapsed=114.9s

  [8335/21087] intraday_16668.csv.gz  in=312,248,600 out=65,405,484 elapsed=114.9s

  [8336/21087] intraday_16669.csv.gz  in=312,261,592 out=65,418,476 elapsed=115.0s

  [8337/21087] intraday_1667.csv.gz  in=312,273,308 out=65,418,476 elapsed=115.0s

  [8338/21087] intraday_16670.csv.gz  in=312,284,171 out=65,429,339 elapsed=115.0s

  [8339/21087] intraday_16671.csv.gz  in=312,296,511 out=65,441,679 elapsed=115.0s

  [8340/21087] intraday_16674.csv.gz  in=312,307,556 out=65,452,724 elapsed=115.0s

  [8341/21087] intraday_16673.csv.gz  in=312,320,209 out=65,465,377 elapsed=115.0s

  [8342/21087] intraday_16672.csv.gz  in=312,334,827 out=65,479,995 elapsed=115.0s

  [8343/21087] intraday_16675.csv.gz  in=312,346,615 out=65,491,783 elapsed=115.0s

  [8344/21087] intraday_16676.csv.gz  in=312,359,078 out=65,504,246 elapsed=115.0s

  [8345/21087] intraday_16677.csv.gz  in=312,368,969 out=65,514,137 elapsed=115.0s

  [8346/21087] intraday_16679.csv.gz  in=312,381,793 out=65,526,961 elapsed=115.1s

  [8347/21087] intraday_1668.csv.gz  in=312,400,848 out=65,526,961 elapsed=115.1s

  [8348/21087] intraday_16678.csv.gz  in=312,412,483 out=65,538,596 elapsed=115.1s

  [8349/21087] intraday_16680.csv.gz  in=312,424,053 out=65,550,166 elapsed=115.1s

  [8350/21087] intraday_16682.csv.gz  in=312,434,575 out=65,560,688 elapsed=115.1s

  [8351/21087] intraday_16681.csv.gz  in=312,445,012 out=65,571,125 elapsed=115.1s

  [8352/21087] intraday_16683.csv.gz  in=312,460,696 out=65,586,809 elapsed=115.1s

  [8353/21087] intraday_16684.csv.gz  in=312,473,592 out=65,599,705 elapsed=115.1s

  [8354/21087] intraday_16685.csv.gz  in=312,484,566 out=65,610,679 elapsed=115.1s

  [8355/21087] intraday_16686.csv.gz  in=312,495,025 out=65,621,138 elapsed=115.2s

  [8356/21087] intraday_16688.csv.gz  in=312,507,402 out=65,633,515 elapsed=115.2s

  [8357/21087] intraday_16687.csv.gz  in=312,521,319 out=65,647,432 elapsed=115.2s

  [8358/21087] intraday_16689.csv.gz  in=312,529,612 out=65,655,725 elapsed=115.2s

  [8359/21087] intraday_1669.csv.gz  in=312,540,462 out=65,655,725 elapsed=115.2s

  [8360/21087] intraday_16690.csv.gz  in=312,542,658 out=65,657,921 elapsed=115.2s

  [8361/21087] intraday_16691.csv.gz  in=312,553,709 out=65,668,972 elapsed=115.2s

  [8362/21087] intraday_16694.csv.gz  in=312,569,219 out=65,684,482 elapsed=115.2s

  [8363/21087] intraday_16692.csv.gz  in=312,583,155 out=65,698,418 elapsed=115.2s

  [8364/21087] intraday_16693.csv.gz  in=312,595,703 out=65,710,966 elapsed=115.2s

  [8365/21087] intraday_16695.csv.gz  in=312,608,436 out=65,723,699 elapsed=115.3s

  [8366/21087] intraday_16696.csv.gz  in=312,618,488 out=65,733,751 elapsed=115.3s

  [8367/21087] intraday_16698.csv.gz  in=312,631,768 out=65,747,031 elapsed=115.3s

  [8368/21087] intraday_16697.csv.gz  in=312,662,559 out=65,770,892 elapsed=115.3s

  [8369/21087] intraday_1670.csv.gz  in=312,672,163 out=65,770,892 elapsed=115.3s

  [8370/21087] intraday_16699.csv.gz  in=312,684,472 out=65,783,201 elapsed=115.3s

  [8371/21087] intraday_16703.csv.gz  in=312,694,731 out=65,793,460 elapsed=115.3s

  [8372/21087] intraday_16701.csv.gz  in=312,706,331 out=65,805,060 elapsed=115.3s

  [8373/21087] intraday_16700.csv.gz  in=312,719,474 out=65,818,203 elapsed=115.3s

  [8374/21087] intraday_16702.csv.gz  in=312,728,958 out=65,827,687 elapsed=115.3s

  [8375/21087] intraday_16704.csv.gz  in=312,739,971 out=65,838,700 elapsed=115.4s

  [8376/21087] intraday_16705.csv.gz  in=312,751,485 out=65,850,214 elapsed=115.4s

  [8377/21087] intraday_16707.csv.gz  in=312,764,107 out=65,862,836 elapsed=115.4s

  [8378/21087] intraday_16706.csv.gz  in=312,777,756 out=65,876,485 elapsed=115.4s

  [8379/21087] intraday_1671.csv.gz  in=312,791,315 out=65,876,485 elapsed=115.4s

  [8380/21087] intraday_16708.csv.gz  in=312,803,196 out=65,888,366 elapsed=115.4s

  [8381/21087] intraday_16709.csv.gz  in=312,814,273 out=65,899,443 elapsed=115.4s

  [8382/21087] intraday_16710.csv.gz  in=312,825,769 out=65,910,939 elapsed=115.4s

  [8383/21087] intraday_16712.csv.gz  in=312,837,819 out=65,922,989 elapsed=115.5s

  [8384/21087] intraday_16713.csv.gz  in=312,850,056 out=65,935,226 elapsed=115.5s

  [8385/21087] intraday_16711.csv.gz  in=312,862,217 out=65,947,387 elapsed=115.5s

  [8386/21087] intraday_16714.csv.gz  in=312,872,394 out=65,957,564 elapsed=115.5s

  [8387/21087] intraday_16715.csv.gz  in=312,886,921 out=65,972,091 elapsed=115.5s

  [8388/21087] intraday_16717.csv.gz  in=312,900,563 out=65,985,733 elapsed=115.5s

  [8389/21087] intraday_16716.csv.gz  in=312,913,000 out=65,998,170 elapsed=115.5s

  [8390/21087] intraday_16718.csv.gz  in=312,925,612 out=66,010,782 elapsed=115.5s

  [8391/21087] intraday_16719.csv.gz  in=312,937,096 out=66,022,266 elapsed=115.5s

  [8392/21087] intraday_1672.csv.gz  in=312,948,476 out=66,022,266 elapsed=115.5s

  [8393/21087] intraday_16721.csv.gz  in=312,960,017 out=66,033,807 elapsed=115.6s

  [8394/21087] intraday_16720.csv.gz  in=312,970,699 out=66,044,489 elapsed=115.6s

  [8395/21087] intraday_16722.csv.gz  in=312,983,148 out=66,056,938 elapsed=115.6s

  [8396/21087] intraday_16723.csv.gz  in=312,995,437 out=66,069,227 elapsed=115.6s

  [8397/21087] intraday_16724.csv.gz  in=313,010,001 out=66,083,727 elapsed=115.6s

  [8398/21087] intraday_16725.csv.gz  in=313,018,728 out=66,092,454 elapsed=115.7s

  [8399/21087] intraday_16726.csv.gz  in=313,030,263 out=66,103,989 elapsed=115.7s

  [8400/21087] intraday_16727.csv.gz  in=313,040,514 out=66,114,240 elapsed=115.7s

  [8401/21087] intraday_16728.csv.gz  in=313,054,979 out=66,128,705 elapsed=115.7s

  [8402/21087] intraday_1673.csv.gz  in=313,067,100 out=66,128,705 elapsed=115.7s

  [8403/21087] intraday_16729.csv.gz  in=313,079,092 out=66,140,697 elapsed=115.7s

  [8404/21087] intraday_16730.csv.gz  in=313,092,321 out=66,153,926 elapsed=115.7s

  [8405/21087] intraday_16731.csv.gz  in=313,104,221 out=66,165,826 elapsed=115.7s

  [8406/21087] intraday_16732.csv.gz  in=313,116,546 out=66,178,151 elapsed=115.7s

  [8407/21087] intraday_16733.csv.gz  in=313,124,711 out=66,186,316 elapsed=115.7s

  [8408/21087] intraday_16734.csv.gz  in=313,136,664 out=66,198,269 elapsed=115.7s

  [8409/21087] intraday_16735.csv.gz  in=313,149,282 out=66,210,887 elapsed=115.8s

  [8410/21087] intraday_16736.csv.gz  in=313,161,819 out=66,223,424 elapsed=115.8s

  [8411/21087] intraday_16737.csv.gz  in=313,171,519 out=66,233,124 elapsed=115.8s

  [8412/21087] intraday_16739.csv.gz  in=313,180,997 out=66,242,602 elapsed=115.8s

  [8413/21087] intraday_1674.csv.gz  in=313,192,643 out=66,242,602 elapsed=115.8s

  [8414/21087] intraday_16738.csv.gz  in=313,203,932 out=66,253,891 elapsed=115.8s

  [8415/21087] intraday_16740.csv.gz  in=313,216,664 out=66,266,623 elapsed=115.8s

  [8416/21087] intraday_16742.csv.gz  in=313,228,421 out=66,278,380 elapsed=115.8s

  [8417/21087] intraday_16741.csv.gz  in=313,241,424 out=66,291,383 elapsed=115.8s

  [8418/21087] intraday_16744.csv.gz  in=313,251,555 out=66,301,514 elapsed=115.8s

  [8419/21087] intraday_16743.csv.gz  in=313,263,534 out=66,313,493 elapsed=115.8s

  [8420/21087] intraday_16745.csv.gz  in=313,274,397 out=66,324,356 elapsed=115.8s

  [8421/21087] intraday_16747.csv.gz  in=313,292,095 out=66,342,054 elapsed=115.9s

  [8422/21087] intraday_16748.csv.gz  in=313,303,365 out=66,353,324 elapsed=115.9s

  [8423/21087] intraday_16749.csv.gz  in=313,315,339 out=66,365,298 elapsed=115.9s

  [8424/21087] intraday_16746.csv.gz  in=313,327,936 out=66,377,895 elapsed=115.9s

  [8425/21087] intraday_1675.csv.gz  in=313,339,818 out=66,377,895 elapsed=115.9s

  [8426/21087] intraday_16751.csv.gz  in=313,352,594 out=66,390,052 elapsed=115.9s

  [8427/21087] intraday_16750.csv.gz  in=313,364,874 out=66,402,332 elapsed=115.9s

  [8428/21087] intraday_16753.csv.gz  in=313,378,025 out=66,415,483 elapsed=116.0s

  [8429/21087] intraday_16752.csv.gz  in=313,389,393 out=66,426,851 elapsed=116.0s

  [8430/21087] intraday_16754.csv.gz  in=313,399,332 out=66,436,790 elapsed=116.0s

  [8431/21087] intraday_16755.csv.gz  in=313,411,464 out=66,448,922 elapsed=116.0s

  [8432/21087] intraday_16756.csv.gz  in=313,421,773 out=66,459,231 elapsed=116.0s

  [8433/21087] intraday_16757.csv.gz  in=313,433,167 out=66,470,625 elapsed=116.0s

  [8434/21087] intraday_16758.csv.gz  in=313,445,305 out=66,482,763 elapsed=116.0s

  [8435/21087] intraday_1676.csv.gz  in=313,458,636 out=66,482,763 elapsed=116.0s

  [8436/21087] intraday_16759.csv.gz  in=313,470,567 out=66,494,694 elapsed=116.0s

  [8437/21087] intraday_16760.csv.gz  in=313,482,841 out=66,506,968 elapsed=116.0s

  [8438/21087] intraday_16761.csv.gz  in=313,492,516 out=66,516,643 elapsed=116.0s

  [8439/21087] intraday_16762.csv.gz  in=313,502,532 out=66,526,659 elapsed=116.1s

  [8440/21087] intraday_16763.csv.gz  in=313,514,327 out=66,538,454 elapsed=116.1s

  [8441/21087] intraday_16765.csv.gz  in=313,526,508 out=66,550,635 elapsed=116.1s

  [8442/21087] intraday_16764.csv.gz  in=313,539,253 out=66,563,380 elapsed=116.1s

  [8443/21087] intraday_16766.csv.gz  in=313,550,789 out=66,574,916 elapsed=116.1s

  [8444/21087] intraday_16767.csv.gz  in=313,563,221 out=66,587,348 elapsed=116.1s

  [8445/21087] intraday_16768.csv.gz  in=313,574,499 out=66,598,626 elapsed=116.1s

  [8446/21087] intraday_1677.csv.gz  in=313,586,250 out=66,598,626 elapsed=116.1s

  [8447/21087] intraday_16769.csv.gz  in=313,598,354 out=66,610,730 elapsed=116.1s

  [8448/21087] intraday_16770.csv.gz  in=313,610,510 out=66,622,886 elapsed=116.1s

  [8449/21087] intraday_16771.csv.gz  in=313,621,939 out=66,634,315 elapsed=116.2s

  [8450/21087] intraday_16772.csv.gz  in=313,636,311 out=66,648,687 elapsed=116.2s

  [8451/21087] intraday_16774.csv.gz  in=313,647,843 out=66,660,219 elapsed=116.2s

  [8452/21087] intraday_16773.csv.gz  in=313,661,579 out=66,673,955 elapsed=116.2s

  [8453/21087] intraday_16775.csv.gz  in=313,673,928 out=66,686,304 elapsed=116.2s

  [8454/21087] intraday_16778.csv.gz  in=313,687,919 out=66,700,295 elapsed=116.2s

  [8455/21087] intraday_16777.csv.gz  in=313,699,781 out=66,712,157 elapsed=116.2s

  [8456/21087] intraday_16776.csv.gz  in=313,713,288 out=66,725,664 elapsed=116.2s

  [8457/21087] intraday_16779.csv.gz  in=313,728,308 out=66,740,684 elapsed=116.2s

  [8458/21087] intraday_1678.csv.gz  in=313,740,962 out=66,740,684 elapsed=116.3s

  [8459/21087] intraday_16781.csv.gz  in=313,753,116 out=66,752,838 elapsed=116.3s

  [8460/21087] intraday_16780.csv.gz  in=313,770,070 out=66,769,792 elapsed=116.3s

  [8461/21087] intraday_16782.csv.gz  in=313,785,841 out=66,785,563 elapsed=116.3s

  [8462/21087] intraday_16783.csv.gz  in=313,798,019 out=66,797,741 elapsed=116.3s

  [8463/21087] intraday_16785.csv.gz  in=313,808,522 out=66,808,244 elapsed=116.3s

  [8464/21087] intraday_16784.csv.gz  in=313,821,221 out=66,820,943 elapsed=116.3s

  [8465/21087] intraday_16787.csv.gz  in=313,831,023 out=66,830,745 elapsed=116.3s

  [8466/21087] intraday_16786.csv.gz  in=313,843,392 out=66,843,114 elapsed=116.3s

  [8467/21087] intraday_16788.csv.gz  in=313,856,018 out=66,855,740 elapsed=116.4s

  [8468/21087] intraday_16789.csv.gz  in=313,867,953 out=66,867,675 elapsed=116.4s

  [8469/21087] intraday_1679.csv.gz  in=313,891,316 out=66,867,675 elapsed=116.4s

  [8470/21087] intraday_16790.csv.gz  in=313,905,183 out=66,881,542 elapsed=116.4s

  [8471/21087] intraday_16791.csv.gz  in=313,916,683 out=66,893,042 elapsed=116.4s

  [8472/21087] intraday_16792.csv.gz  in=313,927,322 out=66,903,681 elapsed=116.4s

  [8473/21087] intraday_16793.csv.gz  in=313,939,340 out=66,915,699 elapsed=116.4s

  [8474/21087] intraday_16795.csv.gz  in=313,950,165 out=66,926,524 elapsed=116.4s

  [8475/21087] intraday_16794.csv.gz  in=313,964,623 out=66,940,982 elapsed=116.4s

  [8476/21087] intraday_16796.csv.gz  in=313,983,288 out=66,957,949 elapsed=116.5s

  [8477/21087] intraday_16797.csv.gz  in=313,996,005 out=66,970,666 elapsed=116.5s

  [8478/21087] intraday_16798.csv.gz  in=314,009,437 out=66,984,098 elapsed=116.5s

  [8479/21087] intraday_16799.csv.gz  in=314,024,526 out=66,999,187 elapsed=116.5s

  [8480/21087] intraday_1680.csv.gz  in=314,035,656 out=66,999,187 elapsed=116.5s

  [8481/21087] intraday_16800.csv.gz  in=314,046,326 out=67,009,857 elapsed=116.5s

  [8482/21087] intraday_16802.csv.gz  in=314,057,920 out=67,021,451 elapsed=116.5s

  [8483/21087] intraday_16801.csv.gz  in=314,070,387 out=67,033,918 elapsed=116.5s

  [8484/21087] intraday_16803.csv.gz  in=314,081,582 out=67,045,113 elapsed=116.5s

  [8485/21087] intraday_16804.csv.gz  in=314,092,252 out=67,055,783 elapsed=116.5s

  [8486/21087] intraday_16808.csv.gz  in=314,092,728 out=67,055,783 elapsed=116.6s

  [8487/21087] intraday_16807.csv.gz  in=314,101,023 out=67,064,078 elapsed=116.6s

  [8488/21087] intraday_16809.csv.gz  in=314,101,079 out=67,064,078 elapsed=116.6s

  [8489/21087] intraday_16806.csv.gz  in=314,110,504 out=67,073,503 elapsed=116.6s

  [8490/21087] intraday_16805.csv.gz  in=314,119,741 out=67,082,740 elapsed=116.6s

  [8491/21087] intraday_16810.csv.gz  in=314,120,672 out=67,083,671 elapsed=116.6s

  [8492/21087] intraday_16811.csv.gz  in=314,121,149 out=67,084,148 elapsed=116.6s

  [8493/21087] intraday_16812.csv.gz  in=314,121,650 out=67,084,649 elapsed=116.6s

  [8494/21087] intraday_1681.csv.gz  in=314,131,460 out=67,084,649 elapsed=116.6s

  [8495/21087] intraday_16813.csv.gz  in=314,131,814 out=67,085,003 elapsed=116.6s

  [8496/21087] intraday_16815.csv.gz  in=314,132,810 out=67,085,999 elapsed=116.6s

  [8497/21087] intraday_16814.csv.gz  in=314,133,185 out=67,086,374 elapsed=116.6s

  [8498/21087] intraday_16816.csv.gz  in=314,133,747 out=67,086,936 elapsed=116.6s

  [8499/21087] intraday_16817.csv.gz  in=314,134,046 out=67,087,235 elapsed=116.6s

  [8500/21087] intraday_16818.csv.gz  in=314,134,491 out=67,087,680 elapsed=116.6s

  [8501/21087] intraday_16819.csv.gz  in=314,135,225 out=67,088,414 elapsed=116.6s

  [8502/21087] intraday_16820.csv.gz  in=314,135,700 out=67,088,889 elapsed=116.6s

  [8503/21087] intraday_16821.csv.gz  in=314,136,227 out=67,089,416 elapsed=116.6s

  [8504/21087] intraday_16822.csv.gz  in=314,137,003 out=67,090,192 elapsed=116.6s

  [8505/21087] intraday_1682.csv.gz  in=314,149,723 out=67,090,192 elapsed=116.6s

  [8506/21087] intraday_16823.csv.gz  in=314,150,026 out=67,090,495 elapsed=116.6s

  [8507/21087] intraday_16824.csv.gz  in=314,150,516 out=67,090,985 elapsed=116.6s

  [8508/21087] intraday_16825.csv.gz  in=314,150,860 out=67,091,329 elapsed=116.7s

  [8509/21087] intraday_16826.csv.gz  in=314,151,634 out=67,092,103 elapsed=116.7s

  [8510/21087] intraday_16828.csv.gz  in=314,151,979 out=67,092,448 elapsed=116.7s

  [8511/21087] intraday_16827.csv.gz  in=314,152,807 out=67,093,276 elapsed=116.7s

  [8512/21087] intraday_16829.csv.gz  in=314,153,216 out=67,093,685 elapsed=116.7s

  [8513/21087] intraday_16830.csv.gz  in=314,153,969 out=67,094,438 elapsed=116.7s

  [8514/21087] intraday_16831.csv.gz  in=314,154,179 out=67,094,648 elapsed=116.7s

  [8515/21087] intraday_1683.csv.gz  in=314,166,722 out=67,094,648 elapsed=116.7s

  [8516/21087] intraday_16832.csv.gz  in=314,167,011 out=67,094,937 elapsed=116.7s

  [8517/21087] intraday_16833.csv.gz  in=314,167,483 out=67,095,409 elapsed=116.7s

  [8518/21087] intraday_16834.csv.gz  in=314,167,564 out=67,095,490 elapsed=116.7s

  [8519/21087] intraday_16836.csv.gz  in=314,167,835 out=67,095,761 elapsed=116.7s

  [8520/21087] intraday_16835.csv.gz  in=314,168,246 out=67,096,172 elapsed=116.7s

  [8521/21087] intraday_16837.csv.gz  in=314,168,306 out=67,096,232 elapsed=116.7s

  [8522/21087] intraday_16838.csv.gz  in=314,169,418 out=67,097,344 elapsed=116.7s

  [8523/21087] intraday_16839.csv.gz  in=314,170,526 out=67,098,452 elapsed=116.7s

  [8524/21087] intraday_16840.csv.gz  in=314,171,552 out=67,099,478 elapsed=116.7s

  [8525/21087] intraday_16842.csv.gz  in=314,171,996 out=67,099,922 elapsed=116.7s

  [8526/21087] intraday_1684.csv.gz  in=314,191,995 out=67,099,922 elapsed=116.7s

  [8527/21087] intraday_16843.csv.gz  in=314,192,639 out=67,100,566 elapsed=116.7s

  [8528/21087] intraday_16844.csv.gz  in=314,192,978 out=67,100,905 elapsed=116.7s

  [8529/21087] intraday_16845.csv.gz  in=314,193,452 out=67,101,379 elapsed=116.7s

  [8530/21087] intraday_16846.csv.gz  in=314,193,739 out=67,101,666 elapsed=116.8s

  [8531/21087] intraday_16841.csv.gz  in=314,212,389 out=67,114,501 elapsed=116.8s

  [8532/21087] intraday_16848.csv.gz  in=314,212,534 out=67,114,646 elapsed=116.8s

  [8533/21087] intraday_16847.csv.gz  in=314,212,804 out=67,114,916 elapsed=116.8s

  [8534/21087] intraday_16849.csv.gz  in=314,213,027 out=67,115,139 elapsed=116.8s

  [8535/21087] intraday_16851.csv.gz  in=314,213,108 out=67,115,220 elapsed=116.8s

  [8536/21087] intraday_16850.csv.gz  in=314,213,323 out=67,115,435 elapsed=116.8s

  [8537/21087] intraday_16852.csv.gz  in=314,214,208 out=67,116,320 elapsed=116.8s

  [8538/21087] intraday_1685.csv.gz  in=314,227,910 out=67,116,320 elapsed=116.8s

  [8539/21087] intraday_16854.csv.gz  in=314,228,148 out=67,116,558 elapsed=116.8s

  [8540/21087] intraday_16853.csv.gz  in=314,228,396 out=67,116,806 elapsed=116.8s

  [8541/21087] intraday_16855.csv.gz  in=314,228,512 out=67,116,922 elapsed=116.8s

  [8542/21087] intraday_16856.csv.gz  in=314,228,745 out=67,117,155 elapsed=116.8s

  [8543/21087] intraday_16857.csv.gz  in=314,228,933 out=67,117,343 elapsed=116.8s

  [8544/21087] intraday_16858.csv.gz  in=314,229,191 out=67,117,601 elapsed=116.8s

  [8545/21087] intraday_16859.csv.gz  in=314,229,364 out=67,117,774 elapsed=116.8s

  [8546/21087] intraday_16860.csv.gz  in=314,229,558 out=67,117,968 elapsed=116.8s

  [8547/21087] intraday_16861.csv.gz  in=314,230,345 out=67,118,755 elapsed=116.8s

  [8548/21087] intraday_16862.csv.gz  in=314,231,478 out=67,119,888 elapsed=116.8s

  [8549/21087] intraday_1686.csv.gz  in=314,243,125 out=67,119,888 elapsed=116.8s

  [8550/21087] intraday_16863.csv.gz  in=314,243,995 out=67,120,758 elapsed=116.8s

  [8551/21087] intraday_16864.csv.gz  in=314,244,571 out=67,121,334 elapsed=116.8s

  [8552/21087] intraday_16865.csv.gz  in=314,244,698 out=67,121,461 elapsed=116.8s

  [8553/21087] intraday_16866.csv.gz  in=314,244,809 out=67,121,572 elapsed=116.8s

  [8554/21087] intraday_16867.csv.gz  in=314,245,037 out=67,121,800 elapsed=116.8s

  [8555/21087] intraday_16868.csv.gz  in=314,245,540 out=67,122,303 elapsed=116.9s

  [8556/21087] intraday_16869.csv.gz  in=314,245,852 out=67,122,615 elapsed=116.9s

  [8557/21087] intraday_16870.csv.gz  in=314,246,381 out=67,123,144 elapsed=116.9s

  [8558/21087] intraday_16871.csv.gz  in=314,246,479 out=67,123,242 elapsed=116.9s

  [8559/21087] intraday_16872.csv.gz  in=314,246,777 out=67,123,540 elapsed=116.9s

  [8560/21087] intraday_16873.csv.gz  in=314,247,007 out=67,123,770 elapsed=116.9s

  [8561/21087] intraday_1687.csv.gz  in=314,267,097 out=67,123,770 elapsed=116.9s

  [8562/21087] intraday_16874.csv.gz  in=314,268,017 out=67,124,690 elapsed=116.9s

  [8563/21087] intraday_16875.csv.gz  in=314,268,647 out=67,125,320 elapsed=116.9s

  [8564/21087] intraday_16876.csv.gz  in=314,268,886 out=67,125,559 elapsed=116.9s

  [8565/21087] intraday_16877.csv.gz  in=314,269,396 out=67,126,069 elapsed=116.9s

  [8566/21087] intraday_16879.csv.gz  in=314,269,583 out=67,126,256 elapsed=116.9s

  [8567/21087] intraday_16878.csv.gz  in=314,269,860 out=67,126,533 elapsed=116.9s

  [8568/21087] intraday_16880.csv.gz  in=314,270,665 out=67,127,338 elapsed=116.9s

  [8569/21087] intraday_16882.csv.gz  in=314,270,917 out=67,127,590 elapsed=116.9s

  [8570/21087] intraday_16881.csv.gz  in=314,271,105 out=67,127,778 elapsed=116.9s

  [8571/21087] intraday_1688.csv.gz  in=314,282,574 out=67,127,778 elapsed=116.9s

  [8572/21087] intraday_16883.csv.gz  in=314,282,892 out=67,128,096 elapsed=116.9s

  [8573/21087] intraday_16884.csv.gz  in=314,283,687 out=67,128,891 elapsed=116.9s

  [8574/21087] intraday_16885.csv.gz  in=314,283,991 out=67,129,195 elapsed=116.9s

  [8575/21087] intraday_16886.csv.gz  in=314,284,350 out=67,129,554 elapsed=116.9s

  [8576/21087] intraday_16887.csv.gz  in=314,284,842 out=67,130,046 elapsed=116.9s

  [8577/21087] intraday_16888.csv.gz  in=314,285,445 out=67,130,649 elapsed=116.9s

  [8578/21087] intraday_16889.csv.gz  in=314,285,500 out=67,130,704 elapsed=117.0s

  [8579/21087] intraday_1689.csv.gz  in=314,298,400 out=67,130,704 elapsed=117.0s

  [8580/21087] intraday_16890.csv.gz  in=314,298,668 out=67,130,972 elapsed=117.0s

  [8581/21087] intraday_16892.csv.gz  in=314,299,854 out=67,132,158 elapsed=117.0s

  [8582/21087] intraday_16891.csv.gz  in=314,300,977 out=67,133,281 elapsed=117.0s

  [8583/21087] intraday_16893.csv.gz  in=314,302,121 out=67,134,425 elapsed=117.0s

  [8584/21087] intraday_16894.csv.gz  in=314,302,919 out=67,135,223 elapsed=117.0s

  [8585/21087] intraday_16895.csv.gz  in=314,303,494 out=67,135,798 elapsed=117.0s

  [8586/21087] intraday_16896.csv.gz  in=314,304,101 out=67,136,405 elapsed=117.0s

  [8587/21087] intraday_16897.csv.gz  in=314,304,259 out=67,136,563 elapsed=117.0s

  [8588/21087] intraday_16898.csv.gz  in=314,305,276 out=67,137,580 elapsed=117.0s

  [8589/21087] intraday_16899.csv.gz  in=314,305,581 out=67,137,885 elapsed=117.0s

  [8590/21087] intraday_16900.csv.gz  in=314,305,850 out=67,138,154 elapsed=117.0s

  [8591/21087] intraday_16901.csv.gz  in=314,306,481 out=67,138,785 elapsed=117.0s

  [8592/21087] intraday_1690.csv.gz  in=314,317,031 out=67,138,785 elapsed=117.0s

  [8593/21087] intraday_16902.csv.gz  in=314,317,452 out=67,139,206 elapsed=117.0s

  [8594/21087] intraday_16903.csv.gz  in=314,317,864 out=67,139,618 elapsed=117.0s

  [8595/21087] intraday_16904.csv.gz  in=314,318,168 out=67,139,922 elapsed=117.0s

  [8596/21087] intraday_16905.csv.gz  in=314,318,593 out=67,140,347 elapsed=117.0s

  [8597/21087] intraday_16906.csv.gz  in=314,318,681 out=67,140,435 elapsed=117.0s

  [8598/21087] intraday_16908.csv.gz  in=314,318,872 out=67,140,626 elapsed=117.0s

  [8599/21087] intraday_16907.csv.gz  in=314,319,420 out=67,141,174 elapsed=117.0s

  [8600/21087] intraday_16909.csv.gz  in=314,319,613 out=67,141,367 elapsed=117.0s

  [8601/21087] intraday_16910.csv.gz  in=314,320,219 out=67,141,973 elapsed=117.0s

  [8602/21087] intraday_16911.csv.gz  in=314,321,671 out=67,143,425 elapsed=117.0s

  [8603/21087] intraday_16912.csv.gz  in=314,322,312 out=67,144,066 elapsed=117.0s

  [8604/21087] intraday_1691.csv.gz  in=314,335,134 out=67,144,066 elapsed=117.1s

  [8605/21087] intraday_16913.csv.gz  in=314,335,760 out=67,144,692 elapsed=117.1s

  [8606/21087] intraday_16914.csv.gz  in=314,336,239 out=67,145,171 elapsed=117.1s

  [8607/21087] intraday_16915.csv.gz  in=314,336,812 out=67,145,744 elapsed=117.1s

  [8608/21087] intraday_16916.csv.gz  in=314,336,937 out=67,145,869 elapsed=117.1s

  [8609/21087] intraday_16919.csv.gz  in=314,337,666 out=67,146,598 elapsed=117.1s

  [8610/21087] intraday_16918.csv.gz  in=314,338,021 out=67,146,953 elapsed=117.1s

  [8611/21087] intraday_16917.csv.gz  in=314,338,378 out=67,147,310 elapsed=117.1s

  [8612/21087] intraday_16920.csv.gz  in=314,338,869 out=67,147,801 elapsed=117.1s

  [8613/21087] intraday_16921.csv.gz  in=314,339,097 out=67,148,029 elapsed=117.1s

  [8614/21087] intraday_16922.csv.gz  in=314,340,061 out=67,148,993 elapsed=117.1s

  [8615/21087] intraday_1692.csv.gz  in=314,352,132 out=67,148,993 elapsed=117.1s

  [8616/21087] intraday_16923.csv.gz  in=314,353,065 out=67,149,926 elapsed=117.1s

  [8617/21087] intraday_16925.csv.gz  in=314,354,831 out=67,151,692 elapsed=117.1s

  [8618/21087] intraday_16924.csv.gz  in=314,356,196 out=67,153,057 elapsed=117.1s

  [8619/21087] intraday_16926.csv.gz  in=314,356,459 out=67,153,320 elapsed=117.1s

  [8620/21087] intraday_16927.csv.gz  in=314,357,522 out=67,154,383 elapsed=117.1s

  [8621/21087] intraday_16928.csv.gz  in=314,357,811 out=67,154,672 elapsed=117.1s

  [8622/21087] intraday_16929.csv.gz  in=314,358,219 out=67,155,080 elapsed=117.1s

  [8623/21087] intraday_16930.csv.gz  in=314,358,307 out=67,155,168 elapsed=117.1s

  [8624/21087] intraday_1693.csv.gz  in=314,369,138 out=67,155,168 elapsed=117.1s

  [8625/21087] intraday_16932.csv.gz  in=314,369,217 out=67,155,247 elapsed=117.1s

  [8626/21087] intraday_16931.csv.gz  in=314,369,784 out=67,155,814 elapsed=117.1s

  [8627/21087] intraday_16933.csv.gz  in=314,370,280 out=67,156,310 elapsed=117.2s

  [8628/21087] intraday_16934.csv.gz  in=314,370,763 out=67,156,793 elapsed=117.2s

  [8629/21087] intraday_16937.csv.gz  in=314,371,245 out=67,157,275 elapsed=117.2s

  [8630/21087] intraday_16936.csv.gz  in=314,371,508 out=67,157,538 elapsed=117.2s

  [8631/21087] intraday_16935.csv.gz  in=314,372,611 out=67,158,641 elapsed=117.2s

  [8632/21087] intraday_16938.csv.gz  in=314,373,148 out=67,159,178 elapsed=117.2s

  [8633/21087] intraday_16940.csv.gz  in=314,373,402 out=67,159,432 elapsed=117.2s

  [8634/21087] intraday_16939.csv.gz  in=314,374,277 out=67,160,307 elapsed=117.2s

  [8635/21087] intraday_16941.csv.gz  in=314,374,755 out=67,160,785 elapsed=117.2s

  [8636/21087] intraday_16942.csv.gz  in=314,374,978 out=67,161,008 elapsed=117.2s

  [8637/21087] intraday_16944.csv.gz  in=314,375,344 out=67,161,374 elapsed=117.2s

  [8638/21087] intraday_16943.csv.gz  in=314,375,930 out=67,161,960 elapsed=117.2s

  [8639/21087] intraday_1694.csv.gz  in=314,399,199 out=67,161,960 elapsed=117.2s

  [8640/21087] intraday_16945.csv.gz  in=314,399,647 out=67,162,408 elapsed=117.2s

  [8641/21087] intraday_16947.csv.gz  in=314,399,866 out=67,162,627 elapsed=117.2s

  [8642/21087] intraday_16946.csv.gz  in=314,400,303 out=67,163,064 elapsed=117.2s

  [8643/21087] intraday_16948.csv.gz  in=314,400,548 out=67,163,309 elapsed=117.2s

  [8644/21087] intraday_16949.csv.gz  in=314,401,003 out=67,163,764 elapsed=117.2s

  [8645/21087] intraday_16951.csv.gz  in=314,401,344 out=67,164,105 elapsed=117.2s

  [8646/21087] intraday_16950.csv.gz  in=314,401,766 out=67,164,527 elapsed=117.2s

  [8647/21087] intraday_16952.csv.gz  in=314,402,111 out=67,164,872 elapsed=117.2s

  [8648/21087] intraday_1695.csv.gz  in=314,417,211 out=67,164,872 elapsed=117.2s

  [8649/21087] intraday_16954.csv.gz  in=314,430,887 out=67,178,548 elapsed=117.3s

  [8650/21087] intraday_16953.csv.gz  in=314,447,828 out=67,195,489 elapsed=117.3s

  [8651/21087] intraday_16955.csv.gz  in=314,460,518 out=67,208,179 elapsed=117.3s

  [8652/21087] intraday_16956.csv.gz  in=314,471,545 out=67,219,206 elapsed=117.3s

  [8653/21087] intraday_16957.csv.gz  in=314,484,437 out=67,232,098 elapsed=117.3s

  [8654/21087] intraday_1696.csv.gz  in=314,497,321 out=67,232,098 elapsed=117.3s

  [8655/21087] intraday_16958.csv.gz  in=314,513,903 out=67,248,680 elapsed=117.3s

  [8656/21087] intraday_16960.csv.gz  in=314,525,728 out=67,260,505 elapsed=117.3s

  [8657/21087] intraday_16959.csv.gz  in=314,538,823 out=67,273,600 elapsed=117.3s

  [8658/21087] intraday_16961.csv.gz  in=314,551,869 out=67,286,646 elapsed=117.3s

  [8659/21087] intraday_16963.csv.gz  in=314,562,488 out=67,297,265 elapsed=117.4s

  [8660/21087] intraday_16962.csv.gz  in=314,576,368 out=67,311,145 elapsed=117.4s

  [8661/21087] intraday_16964.csv.gz  in=314,590,309 out=67,325,086 elapsed=117.4s

  [8662/21087] intraday_16965.csv.gz  in=314,604,306 out=67,339,083 elapsed=117.4s

  [8663/21087] intraday_16966.csv.gz  in=314,616,474 out=67,351,251 elapsed=117.4s

  [8664/21087] intraday_1697.csv.gz  in=314,628,460 out=67,351,251 elapsed=117.4s

  [8665/21087] intraday_16968.csv.gz  in=314,639,048 out=67,361,839 elapsed=117.4s

  [8666/21087] intraday_16967.csv.gz  in=314,649,799 out=67,372,590 elapsed=117.4s

  [8667/21087] intraday_16969.csv.gz  in=314,666,048 out=67,388,839 elapsed=117.4s

  [8668/21087] intraday_16970.csv.gz  in=314,680,535 out=67,403,326 elapsed=117.5s

  [8669/21087] intraday_16971.csv.gz  in=314,692,304 out=67,415,095 elapsed=117.5s

  [8670/21087] intraday_16973.csv.gz  in=314,707,820 out=67,430,611 elapsed=117.5s

  [8671/21087] intraday_16972.csv.gz  in=314,719,149 out=67,441,940 elapsed=117.5s

  [8672/21087] intraday_16974.csv.gz  in=314,731,784 out=67,454,575 elapsed=117.5s

  [8673/21087] intraday_16975.csv.gz  in=314,743,899 out=67,466,690 elapsed=117.5s

  [8674/21087] intraday_16976.csv.gz  in=314,756,580 out=67,479,371 elapsed=117.5s

  [8675/21087] intraday_16977.csv.gz  in=314,768,782 out=67,491,573 elapsed=117.6s

  [8676/21087] intraday_16978.csv.gz  in=314,780,368 out=67,503,159 elapsed=117.6s

  [8677/21087] intraday_1698.csv.gz  in=314,795,491 out=67,503,159 elapsed=117.6s

  [8678/21087] intraday_16979.csv.gz  in=314,807,588 out=67,515,256 elapsed=117.6s

  [8679/21087] intraday_16980.csv.gz  in=314,818,979 out=67,526,647 elapsed=117.6s

  [8680/21087] intraday_16981.csv.gz  in=314,833,321 out=67,540,989 elapsed=117.6s

  [8681/21087] intraday_16982.csv.gz  in=314,846,224 out=67,553,892 elapsed=117.6s

  [8682/21087] intraday_16985.csv.gz  in=314,858,458 out=67,566,126 elapsed=117.6s

  [8683/21087] intraday_16984.csv.gz  in=314,871,645 out=67,579,313 elapsed=117.6s

  [8684/21087] intraday_16983.csv.gz  in=314,889,874 out=67,597,542 elapsed=117.6s

  [8685/21087] intraday_16986.csv.gz  in=314,903,053 out=67,610,721 elapsed=117.7s

  [8686/21087] intraday_16988.csv.gz  in=314,916,735 out=67,624,403 elapsed=117.7s

  [8687/21087] intraday_16987.csv.gz  in=314,931,464 out=67,639,132 elapsed=117.7s

  [8688/21087] intraday_1699.csv.gz  in=314,943,473 out=67,639,132 elapsed=117.7s

  [8689/21087] intraday_16989.csv.gz  in=314,957,360 out=67,653,019 elapsed=117.7s

  [8690/21087] intraday_16991.csv.gz  in=314,968,028 out=67,663,687 elapsed=117.7s

  [8691/21087] intraday_16990.csv.gz  in=314,979,449 out=67,675,108 elapsed=117.7s

  [8692/21087] intraday_16993.csv.gz  in=314,992,153 out=67,687,812 elapsed=117.7s

  [8693/21087] intraday_16992.csv.gz  in=315,006,571 out=67,702,230 elapsed=117.7s

  [8694/21087] intraday_16994.csv.gz  in=315,018,274 out=67,713,933 elapsed=117.8s

  [8695/21087] intraday_16995.csv.gz  in=315,037,906 out=67,732,881 elapsed=117.8s

  [8696/21087] intraday_16996.csv.gz  in=315,050,497 out=67,745,472 elapsed=117.8s

  [8697/21087] intraday_16997.csv.gz  in=315,063,842 out=67,758,817 elapsed=117.8s

  [8698/21087] intraday_16998.csv.gz  in=315,074,911 out=67,769,886 elapsed=117.8s

  [8699/21087] intraday_16999.csv.gz  in=315,086,981 out=67,781,956 elapsed=117.8s

  [8700/21087] intraday_17000.csv.gz  in=315,099,747 out=67,794,722 elapsed=117.8s

  [8701/21087] intraday_1700.csv.gz  in=315,126,388 out=67,794,722 elapsed=117.9s

  [8702/21087] intraday_17001.csv.gz  in=315,138,092 out=67,806,426 elapsed=117.9s

  [8703/21087] intraday_17002.csv.gz  in=315,151,105 out=67,819,439 elapsed=117.9s

  [8704/21087] intraday_17003.csv.gz  in=315,166,206 out=67,832,944 elapsed=117.9s

  [8705/21087] intraday_17004.csv.gz  in=315,182,419 out=67,848,240 elapsed=117.9s

  [8706/21087] intraday_17005.csv.gz  in=315,195,946 out=67,861,767 elapsed=117.9s

  [8707/21087] intraday_17006.csv.gz  in=315,209,694 out=67,875,515 elapsed=117.9s

  [8708/21087] intraday_17007.csv.gz  in=315,225,131 out=67,890,952 elapsed=117.9s

  [8709/21087] intraday_1701.csv.gz  in=315,236,322 out=67,890,952 elapsed=117.9s

  [8710/21087] intraday_17009.csv.gz  in=315,246,179 out=67,900,809 elapsed=117.9s

  [8711/21087] intraday_17008.csv.gz  in=315,259,395 out=67,914,025 elapsed=118.0s

  [8712/21087] intraday_17010.csv.gz  in=315,271,321 out=67,925,951 elapsed=118.0s

  [8713/21087] intraday_17011.csv.gz  in=315,284,212 out=67,938,842 elapsed=118.0s

  [8714/21087] intraday_17012.csv.gz  in=315,298,192 out=67,952,822 elapsed=118.0s

  [8715/21087] intraday_17013.csv.gz  in=315,310,429 out=67,965,059 elapsed=118.0s

  [8716/21087] intraday_17014.csv.gz  in=315,321,143 out=67,975,773 elapsed=118.0s

  [8717/21087] intraday_17015.csv.gz  in=315,333,440 out=67,988,070 elapsed=118.0s

  [8718/21087] intraday_17016.csv.gz  in=315,343,880 out=67,998,510 elapsed=118.0s

  [8719/21087] intraday_1702.csv.gz  in=315,356,045 out=67,998,510 elapsed=118.0s

  [8720/21087] intraday_17017.csv.gz  in=315,373,801 out=68,016,266 elapsed=118.1s

  [8721/21087] intraday_17018.csv.gz  in=315,388,095 out=68,030,560 elapsed=118.1s

  [8722/21087] intraday_17019.csv.gz  in=315,400,213 out=68,042,678 elapsed=118.1s

  [8723/21087] intraday_17020.csv.gz  in=315,413,401 out=68,055,866 elapsed=118.1s

  [8724/21087] intraday_17022.csv.gz  in=315,421,655 out=68,064,120 elapsed=118.1s

  [8725/21087] intraday_17021.csv.gz  in=315,433,549 out=68,076,014 elapsed=118.1s

  [8726/21087] intraday_17023.csv.gz  in=315,446,526 out=68,088,991 elapsed=118.1s

  [8727/21087] intraday_17024.csv.gz  in=315,460,020 out=68,102,485 elapsed=118.1s

  [8728/21087] intraday_17025.csv.gz  in=315,472,848 out=68,115,313 elapsed=118.1s

  [8729/21087] intraday_17026.csv.gz  in=315,483,587 out=68,126,052 elapsed=118.1s

  [8730/21087] intraday_17027.csv.gz  in=315,496,301 out=68,138,766 elapsed=118.2s

  [8731/21087] intraday_1703.csv.gz  in=315,508,331 out=68,138,766 elapsed=118.2s

  [8732/21087] intraday_17028.csv.gz  in=315,518,586 out=68,149,021 elapsed=118.2s

  [8733/21087] intraday_17029.csv.gz  in=315,530,255 out=68,160,690 elapsed=118.2s

  [8734/21087] intraday_17030.csv.gz  in=315,544,293 out=68,174,728 elapsed=118.2s

  [8735/21087] intraday_17033.csv.gz  in=315,554,110 out=68,184,545 elapsed=118.2s

  [8736/21087] intraday_17031.csv.gz  in=315,567,211 out=68,197,646 elapsed=118.2s

  [8737/21087] intraday_17032.csv.gz  in=315,581,182 out=68,211,617 elapsed=118.2s

  [8738/21087] intraday_17034.csv.gz  in=315,592,588 out=68,223,023 elapsed=118.2s

  [8739/21087] intraday_17035.csv.gz  in=315,607,058 out=68,237,493 elapsed=118.3s

  [8740/21087] intraday_17037.csv.gz  in=315,619,534 out=68,249,969 elapsed=118.3s

  [8741/21087] intraday_17036.csv.gz  in=315,638,425 out=68,268,860 elapsed=118.3s

  [8742/21087] intraday_17038.csv.gz  in=315,653,368 out=68,283,803 elapsed=118.3s

  [8743/21087] intraday_17039.csv.gz  in=315,665,957 out=68,296,392 elapsed=118.3s

  [8744/21087] intraday_1704.csv.gz  in=315,676,394 out=68,296,392 elapsed=118.3s

  [8745/21087] intraday_17041.csv.gz  in=315,687,221 out=68,307,219 elapsed=118.3s

  [8746/21087] intraday_17040.csv.gz  in=315,700,906 out=68,320,904 elapsed=118.3s

  [8747/21087] intraday_17042.csv.gz  in=315,716,476 out=68,336,474 elapsed=118.3s

  [8748/21087] intraday_17043.csv.gz  in=315,727,054 out=68,347,052 elapsed=118.3s

  [8749/21087] intraday_17044.csv.gz  in=315,740,241 out=68,360,239 elapsed=118.3s

  [8750/21087] intraday_17045.csv.gz  in=315,751,818 out=68,371,816 elapsed=118.4s

  [8751/21087] intraday_17046.csv.gz  in=315,763,788 out=68,383,786 elapsed=118.4s

  [8752/21087] intraday_17047.csv.gz  in=315,778,128 out=68,397,727 elapsed=118.4s

  [8753/21087] intraday_17048.csv.gz  in=315,789,540 out=68,409,139 elapsed=118.4s

  [8754/21087] intraday_17049.csv.gz  in=315,803,294 out=68,422,893 elapsed=118.4s

  [8755/21087] intraday_1705.csv.gz  in=315,812,907 out=68,422,893 elapsed=118.4s

  [8756/21087] intraday_17051.csv.gz  in=315,822,820 out=68,432,806 elapsed=118.4s

  [8757/21087] intraday_17050.csv.gz  in=315,836,499 out=68,446,485 elapsed=118.4s

  [8758/21087] intraday_17052.csv.gz  in=315,848,721 out=68,458,707 elapsed=118.5s

  [8759/21087] intraday_17053.csv.gz  in=315,860,789 out=68,470,775 elapsed=118.5s

  [8760/21087] intraday_17054.csv.gz  in=315,873,791 out=68,483,777 elapsed=118.5s

  [8761/21087] intraday_17056.csv.gz  in=315,887,473 out=68,497,459 elapsed=118.5s

  [8762/21087] intraday_17057.csv.gz  in=315,899,032 out=68,509,018 elapsed=118.5s

  [8763/21087] intraday_17055.csv.gz  in=315,915,240 out=68,525,226 elapsed=118.5s

  [8764/21087] intraday_17058.csv.gz  in=315,929,940 out=68,539,926 elapsed=118.5s

  [8765/21087] intraday_17059.csv.gz  in=315,942,387 out=68,552,373 elapsed=118.5s

  [8766/21087] intraday_1706.csv.gz  in=315,957,241 out=68,552,373 elapsed=118.5s

  [8767/21087] intraday_17060.csv.gz  in=315,968,993 out=68,564,125 elapsed=118.6s

  [8768/21087] intraday_17061.csv.gz  in=315,982,713 out=68,577,845 elapsed=118.6s

  [8769/21087] intraday_17062.csv.gz  in=315,997,153 out=68,592,285 elapsed=118.6s

  [8770/21087] intraday_17063.csv.gz  in=316,011,802 out=68,606,934 elapsed=118.6s

  [8771/21087] intraday_17064.csv.gz  in=316,022,928 out=68,618,060 elapsed=118.6s

  [8772/21087] intraday_17065.csv.gz  in=316,036,842 out=68,631,974 elapsed=118.6s

  [8773/21087] intraday_17066.csv.gz  in=316,050,603 out=68,645,735 elapsed=118.6s

  [8774/21087] intraday_1707.csv.gz  in=316,061,761 out=68,645,735 elapsed=118.9s

  [8775/21087] intraday_17067.csv.gz  in=316,076,975 out=68,660,949 elapsed=118.9s

  [8776/21087] intraday_17068.csv.gz  in=316,092,883 out=68,676,857 elapsed=118.9s

  [8777/21087] intraday_17069.csv.gz  in=316,117,937 out=68,701,911 elapsed=118.9s

  [8778/21087] intraday_17070.csv.gz  in=316,130,367 out=68,714,341 elapsed=119.0s

  [8779/21087] intraday_17071.csv.gz  in=316,148,134 out=68,732,108 elapsed=119.0s

  [8780/21087] intraday_17074.csv.gz  in=316,158,452 out=68,742,426 elapsed=119.0s

  [8781/21087] intraday_17072.csv.gz  in=316,170,816 out=68,754,790 elapsed=119.0s

  [8782/21087] intraday_17075.csv.gz  in=316,184,030 out=68,768,004 elapsed=119.0s

  [8783/21087] intraday_17073.csv.gz  in=316,213,982 out=68,791,703 elapsed=119.0s

  [8784/21087] intraday_17076.csv.gz  in=316,225,021 out=68,802,742 elapsed=119.0s

  [8785/21087] intraday_17077.csv.gz  in=316,237,939 out=68,815,660 elapsed=119.0s

  [8786/21087] intraday_17078.csv.gz  in=316,250,525 out=68,828,246 elapsed=119.0s

  [8787/21087] intraday_1708.csv.gz  in=316,261,978 out=68,828,246 elapsed=119.0s

  [8788/21087] intraday_17079.csv.gz  in=316,277,653 out=68,843,921 elapsed=119.0s

  [8789/21087] intraday_17080.csv.gz  in=316,288,866 out=68,855,134 elapsed=119.1s

  [8790/21087] intraday_17081.csv.gz  in=316,300,832 out=68,867,100 elapsed=119.1s

  [8791/21087] intraday_17082.csv.gz  in=316,312,140 out=68,878,408 elapsed=119.1s

  [8792/21087] intraday_17083.csv.gz  in=316,326,827 out=68,893,095 elapsed=119.1s

  [8793/21087] intraday_17085.csv.gz  in=316,342,711 out=68,908,979 elapsed=119.1s

  [8794/21087] intraday_17084.csv.gz  in=316,354,713 out=68,920,981 elapsed=119.1s

  [8795/21087] intraday_17088.csv.gz  in=316,369,577 out=68,935,845 elapsed=119.1s

  [8796/21087] intraday_17087.csv.gz  in=316,384,791 out=68,951,059 elapsed=119.1s

  [8797/21087] intraday_17089.csv.gz  in=316,396,508 out=68,962,776 elapsed=119.1s

  [8798/21087] intraday_17086.csv.gz  in=316,410,288 out=68,976,556 elapsed=119.1s

  [8799/21087] intraday_1709.csv.gz  in=316,422,121 out=68,976,556 elapsed=119.2s

  [8800/21087] intraday_17092.csv.gz  in=316,432,113 out=68,986,548 elapsed=119.2s

  [8801/21087] intraday_17090.csv.gz  in=316,445,057 out=68,999,492 elapsed=119.2s

  [8802/21087] intraday_17091.csv.gz  in=316,457,560 out=69,011,995 elapsed=119.2s

  [8803/21087] intraday_17093.csv.gz  in=316,470,490 out=69,024,925 elapsed=119.2s

  [8804/21087] intraday_17094.csv.gz  in=316,480,781 out=69,035,216 elapsed=119.2s

  [8805/21087] intraday_17095.csv.gz  in=316,490,271 out=69,044,706 elapsed=119.2s

  [8806/21087] intraday_17096.csv.gz  in=316,501,184 out=69,055,619 elapsed=119.2s

  [8807/21087] intraday_17097.csv.gz  in=316,517,280 out=69,071,715 elapsed=119.2s

  [8808/21087] intraday_17098.csv.gz  in=316,530,376 out=69,084,811 elapsed=119.3s

  [8809/21087] intraday_1710.csv.gz  in=316,543,061 out=69,084,811 elapsed=119.3s

  [8810/21087] intraday_17099.csv.gz  in=316,556,889 out=69,098,639 elapsed=119.3s

  [8811/21087] intraday_17100.csv.gz  in=316,567,183 out=69,108,933 elapsed=119.3s

  [8812/21087] intraday_17101.csv.gz  in=316,580,467 out=69,122,217 elapsed=119.3s

  [8813/21087] intraday_17102.csv.gz  in=316,596,216 out=69,137,966 elapsed=119.3s

  [8814/21087] intraday_17104.csv.gz  in=316,607,982 out=69,149,732 elapsed=119.3s

  [8815/21087] intraday_17103.csv.gz  in=316,621,128 out=69,162,878 elapsed=119.3s

  [8816/21087] intraday_17105.csv.gz  in=316,633,356 out=69,175,106 elapsed=119.3s

  [8817/21087] intraday_17106.csv.gz  in=316,647,113 out=69,188,863 elapsed=119.4s

  [8818/21087] intraday_17107.csv.gz  in=316,657,682 out=69,199,432 elapsed=119.4s

  [8819/21087] intraday_17108.csv.gz  in=316,670,789 out=69,212,539 elapsed=119.4s

  [8820/21087] intraday_1711.csv.gz  in=316,690,214 out=69,212,539 elapsed=119.4s

  [8821/21087] intraday_17109.csv.gz  in=316,704,239 out=69,226,564 elapsed=119.4s

  [8822/21087] intraday_17111.csv.gz  in=316,714,952 out=69,237,277 elapsed=119.4s

  [8823/21087] intraday_17110.csv.gz  in=316,727,692 out=69,250,017 elapsed=119.4s

  [8824/21087] intraday_17112.csv.gz  in=316,739,771 out=69,262,096 elapsed=119.4s

  [8825/21087] intraday_17113.csv.gz  in=316,755,073 out=69,277,398 elapsed=119.4s

  [8826/21087] intraday_17115.csv.gz  in=316,766,371 out=69,288,696 elapsed=119.5s

  [8827/21087] intraday_17116.csv.gz  in=316,776,994 out=69,299,319 elapsed=119.5s

  [8828/21087] intraday_17114.csv.gz  in=316,791,377 out=69,313,702 elapsed=119.5s

  [8829/21087] intraday_17117.csv.gz  in=316,805,446 out=69,327,771 elapsed=119.5s

  [8830/21087] intraday_17118.csv.gz  in=316,818,197 out=69,340,522 elapsed=119.5s

  [8831/21087] intraday_1712.csv.gz  in=316,830,109 out=69,340,522 elapsed=119.5s

  [8832/21087] intraday_17119.csv.gz  in=316,842,569 out=69,352,982 elapsed=119.5s

  [8833/21087] intraday_17120.csv.gz  in=316,855,292 out=69,365,705 elapsed=119.5s

  [8834/21087] intraday_17121.csv.gz  in=316,867,387 out=69,377,800 elapsed=119.6s

  [8835/21087] intraday_17122.csv.gz  in=316,879,037 out=69,389,450 elapsed=119.6s

  [8836/21087] intraday_17123.csv.gz  in=316,891,303 out=69,401,716 elapsed=119.6s

  [8837/21087] intraday_17124.csv.gz  in=316,902,471 out=69,412,884 elapsed=119.6s

  [8838/21087] intraday_17125.csv.gz  in=316,917,247 out=69,427,660 elapsed=119.6s

  [8839/21087] intraday_17126.csv.gz  in=316,932,390 out=69,442,803 elapsed=119.6s

  [8840/21087] intraday_17127.csv.gz  in=316,946,764 out=69,457,177 elapsed=119.6s

  [8841/21087] intraday_1713.csv.gz  in=316,959,715 out=69,457,177 elapsed=119.6s

  [8842/21087] intraday_17128.csv.gz  in=316,972,593 out=69,470,055 elapsed=119.7s

  [8843/21087] intraday_17129.csv.gz  in=316,984,613 out=69,482,075 elapsed=119.7s

  [8844/21087] intraday_17130.csv.gz  in=316,999,622 out=69,497,084 elapsed=119.7s

  [8845/21087] intraday_17131.csv.gz  in=317,013,275 out=69,510,737 elapsed=119.7s

  [8846/21087] intraday_17134.csv.gz  in=317,024,246 out=69,521,708 elapsed=119.7s

  [8847/21087] intraday_17133.csv.gz  in=317,036,892 out=69,534,354 elapsed=119.7s

  [8848/21087] intraday_17132.csv.gz  in=317,050,786 out=69,548,248 elapsed=119.7s

  [8849/21087] intraday_17135.csv.gz  in=317,061,575 out=69,559,037 elapsed=119.7s

  [8850/21087] intraday_17139.csv.gz  in=317,075,955 out=69,573,417 elapsed=119.8s

  [8851/21087] intraday_17137.csv.gz  in=317,087,838 out=69,585,300 elapsed=119.8s

  [8852/21087] intraday_17138.csv.gz  in=317,100,935 out=69,598,397 elapsed=119.8s

  [8853/21087] intraday_17136.csv.gz  in=317,112,011 out=69,609,473 elapsed=119.8s

  [8854/21087] intraday_1714.csv.gz  in=317,122,947 out=69,609,473 elapsed=119.8s

  [8855/21087] intraday_17140.csv.gz  in=317,136,553 out=69,623,079 elapsed=119.8s

  [8856/21087] intraday_17143.csv.gz  in=317,148,600 out=69,635,126 elapsed=119.8s

  [8857/21087] intraday_17141.csv.gz  in=317,162,942 out=69,649,468 elapsed=119.8s

  [8858/21087] intraday_17142.csv.gz  in=317,174,161 out=69,660,687 elapsed=119.8s

  [8859/21087] intraday_17144.csv.gz  in=317,187,456 out=69,673,982 elapsed=119.9s

  [8860/21087] intraday_17147.csv.gz  in=317,199,061 out=69,685,587 elapsed=119.9s

  [8861/21087] intraday_17146.csv.gz  in=317,211,233 out=69,697,759 elapsed=119.9s

  [8862/21087] intraday_17145.csv.gz  in=317,222,898 out=69,709,424 elapsed=119.9s

  [8863/21087] intraday_17148.csv.gz  in=317,237,622 out=69,724,148 elapsed=119.9s

  [8864/21087] intraday_1715.csv.gz  in=317,250,880 out=69,724,148 elapsed=119.9s

  [8865/21087] intraday_17149.csv.gz  in=317,263,920 out=69,737,188 elapsed=119.9s

  [8866/21087] intraday_17150.csv.gz  in=317,277,519 out=69,750,787 elapsed=119.9s

  [8867/21087] intraday_17151.csv.gz  in=317,292,735 out=69,766,003 elapsed=119.9s

  [8868/21087] intraday_17152.csv.gz  in=317,305,135 out=69,778,403 elapsed=119.9s

  [8869/21087] intraday_17153.csv.gz  in=317,317,348 out=69,790,616 elapsed=120.0s

  [8870/21087] intraday_17155.csv.gz  in=317,330,053 out=69,803,321 elapsed=120.0s

  [8871/21087] intraday_17154.csv.gz  in=317,341,875 out=69,815,143 elapsed=120.0s

  [8872/21087] intraday_17156.csv.gz  in=317,353,792 out=69,827,060 elapsed=120.0s

  [8873/21087] intraday_17157.csv.gz  in=317,367,183 out=69,840,451 elapsed=120.0s

  [8874/21087] intraday_1716.csv.gz  in=317,378,459 out=69,840,451 elapsed=120.0s

  [8875/21087] intraday_17158.csv.gz  in=317,389,251 out=69,851,243 elapsed=120.0s

  [8876/21087] intraday_17159.csv.gz  in=317,401,618 out=69,863,610 elapsed=120.0s

  [8877/21087] intraday_17160.csv.gz  in=317,412,332 out=69,874,324 elapsed=120.0s

  [8878/21087] intraday_17162.csv.gz  in=317,424,784 out=69,886,776 elapsed=120.0s

  [8879/21087] intraday_17163.csv.gz  in=317,438,736 out=69,900,728 elapsed=120.1s

  [8880/21087] intraday_17164.csv.gz  in=317,451,888 out=69,913,880 elapsed=120.1s

  [8881/21087] intraday_17161.csv.gz  in=317,467,686 out=69,929,678 elapsed=120.1s

  [8882/21087] intraday_17165.csv.gz  in=317,478,877 out=69,940,869 elapsed=120.1s

  [8883/21087] intraday_17166.csv.gz  in=317,488,664 out=69,950,656 elapsed=120.1s

  [8884/21087] intraday_17167.csv.gz  in=317,500,716 out=69,962,708 elapsed=120.1s

  [8885/21087] intraday_17168.csv.gz  in=317,514,596 out=69,976,588 elapsed=120.1s

  [8886/21087] intraday_1717.csv.gz  in=317,524,974 out=69,976,588 elapsed=120.1s

  [8887/21087] intraday_17169.csv.gz  in=317,537,307 out=69,988,921 elapsed=120.1s

  [8888/21087] intraday_17170.csv.gz  in=317,548,954 out=70,000,568 elapsed=120.2s

  [8889/21087] intraday_17172.csv.gz  in=317,559,095 out=70,010,709 elapsed=120.2s

  [8890/21087] intraday_17171.csv.gz  in=317,571,085 out=70,022,699 elapsed=120.2s

  [8891/21087] intraday_17173.csv.gz  in=317,585,580 out=70,037,194 elapsed=120.2s

  [8892/21087] intraday_17176.csv.gz  in=317,595,905 out=70,047,519 elapsed=120.2s

  [8893/21087] intraday_17177.csv.gz  in=317,607,018 out=70,058,632 elapsed=120.2s

  [8894/21087] intraday_17174.csv.gz  in=317,621,177 out=70,072,791 elapsed=120.2s

  [8895/21087] intraday_17175.csv.gz  in=317,634,855 out=70,086,469 elapsed=120.2s

  [8896/21087] intraday_17178.csv.gz  in=317,649,089 out=70,100,703 elapsed=120.2s

  [8897/21087] intraday_1718.csv.gz  in=317,664,589 out=70,100,703 elapsed=120.3s

  [8898/21087] intraday_17179.csv.gz  in=317,679,569 out=70,115,683 elapsed=120.3s

  [8899/21087] intraday_17180.csv.gz  in=317,695,120 out=70,131,234 elapsed=120.3s

  [8900/21087] intraday_17181.csv.gz  in=317,708,439 out=70,144,553 elapsed=120.3s

  [8901/21087] intraday_17182.csv.gz  in=317,721,640 out=70,157,754 elapsed=120.3s

  [8902/21087] intraday_17183.csv.gz  in=317,734,308 out=70,170,422 elapsed=120.3s

  [8903/21087] intraday_17184.csv.gz  in=317,746,072 out=70,182,186 elapsed=120.3s

  [8904/21087] intraday_17186.csv.gz  in=317,758,010 out=70,194,124 elapsed=120.3s

  [8905/21087] intraday_17185.csv.gz  in=317,773,942 out=70,210,056 elapsed=120.3s

  [8906/21087] intraday_17187.csv.gz  in=317,785,583 out=70,221,697 elapsed=120.3s

  [8907/21087] intraday_17189.csv.gz  in=317,797,191 out=70,233,305 elapsed=120.4s

  [8908/21087] intraday_1719.csv.gz  in=317,810,330 out=70,233,305 elapsed=120.4s

  [8909/21087] intraday_17188.csv.gz  in=317,824,437 out=70,247,412 elapsed=120.4s

  [8910/21087] intraday_17190.csv.gz  in=317,837,802 out=70,260,777 elapsed=120.4s

  [8911/21087] intraday_17191.csv.gz  in=317,850,540 out=70,273,515 elapsed=120.4s

  [8912/21087] intraday_17192.csv.gz  in=317,863,517 out=70,286,492 elapsed=120.4s

  [8913/21087] intraday_17193.csv.gz  in=317,875,864 out=70,298,839 elapsed=120.4s

  [8914/21087] intraday_17194.csv.gz  in=317,886,845 out=70,309,820 elapsed=120.4s

  [8915/21087] intraday_17195.csv.gz  in=317,898,108 out=70,321,083 elapsed=120.5s

  [8916/21087] intraday_17196.csv.gz  in=317,909,814 out=70,332,789 elapsed=120.5s

  [8917/21087] intraday_17197.csv.gz  in=317,922,822 out=70,345,797 elapsed=120.5s

  [8918/21087] intraday_1720.csv.gz  in=317,935,396 out=70,345,797 elapsed=120.5s

  [8919/21087] intraday_17198.csv.gz  in=317,949,659 out=70,360,060 elapsed=120.5s

  [8920/21087] intraday_17199.csv.gz  in=317,964,967 out=70,375,368 elapsed=120.5s

  [8921/21087] intraday_17200.csv.gz  in=317,977,315 out=70,387,716 elapsed=120.5s

  [8922/21087] intraday_17201.csv.gz  in=317,990,702 out=70,401,103 elapsed=120.5s

  [8923/21087] intraday_17203.csv.gz  in=318,001,970 out=70,412,371 elapsed=120.5s

  [8924/21087] intraday_17202.csv.gz  in=318,015,552 out=70,425,953 elapsed=120.5s

  [8925/21087] intraday_17204.csv.gz  in=318,028,843 out=70,439,244 elapsed=120.6s

  [8926/21087] intraday_17205.csv.gz  in=318,042,004 out=70,452,405 elapsed=120.6s

  [8927/21087] intraday_17207.csv.gz  in=318,054,062 out=70,464,463 elapsed=120.6s

  [8928/21087] intraday_17206.csv.gz  in=318,069,507 out=70,479,908 elapsed=120.6s

  [8929/21087] intraday_17208.csv.gz  in=318,083,831 out=70,494,232 elapsed=120.6s

  [8930/21087] intraday_17209.csv.gz  in=318,098,106 out=70,508,507 elapsed=120.6s

  [8931/21087] intraday_1721.csv.gz  in=318,112,321 out=70,508,507 elapsed=120.6s

  [8932/21087] intraday_17210.csv.gz  in=318,125,678 out=70,521,864 elapsed=120.6s

  [8933/21087] intraday_17211.csv.gz  in=318,140,808 out=70,536,994 elapsed=120.7s

  [8934/21087] intraday_17213.csv.gz  in=318,154,819 out=70,551,005 elapsed=120.7s

  [8935/21087] intraday_17212.csv.gz  in=318,172,458 out=70,568,644 elapsed=120.7s

  [8936/21087] intraday_17214.csv.gz  in=318,188,995 out=70,585,181 elapsed=120.7s

  [8937/21087] intraday_17216.csv.gz  in=318,201,525 out=70,597,711 elapsed=120.7s

  [8938/21087] intraday_17217.csv.gz  in=318,213,730 out=70,609,916 elapsed=120.7s

  [8939/21087] intraday_17215.csv.gz  in=318,227,850 out=70,624,036 elapsed=120.7s

  [8940/21087] intraday_17218.csv.gz  in=318,239,015 out=70,635,201 elapsed=120.7s

  [8941/21087] intraday_1722.csv.gz  in=318,252,251 out=70,635,201 elapsed=120.7s

  [8942/21087] intraday_17219.csv.gz  in=318,264,232 out=70,647,182 elapsed=120.8s

  [8943/21087] intraday_17220.csv.gz  in=318,276,355 out=70,659,305 elapsed=120.8s

  [8944/21087] intraday_17221.csv.gz  in=318,290,113 out=70,673,063 elapsed=120.8s

  [8945/21087] intraday_17222.csv.gz  in=318,304,545 out=70,687,495 elapsed=120.8s

  [8946/21087] intraday_17226.csv.gz  in=318,316,917 out=70,699,867 elapsed=120.8s

  [8947/21087] intraday_17223.csv.gz  in=318,329,921 out=70,712,871 elapsed=120.8s

  [8948/21087] intraday_17224.csv.gz  in=318,342,160 out=70,725,110 elapsed=120.8s

  [8949/21087] intraday_17225.csv.gz  in=318,354,484 out=70,737,434 elapsed=120.8s

  [8950/21087] intraday_1723.csv.gz  in=318,363,630 out=70,737,434 elapsed=120.8s

  [8951/21087] intraday_17227.csv.gz  in=318,375,941 out=70,749,745 elapsed=120.9s

  [8952/21087] intraday_17228.csv.gz  in=318,390,109 out=70,763,913 elapsed=120.9s

  [8953/21087] intraday_17229.csv.gz  in=318,404,945 out=70,778,749 elapsed=120.9s

  [8954/21087] intraday_17230.csv.gz  in=318,419,676 out=70,793,480 elapsed=120.9s

  [8955/21087] intraday_17232.csv.gz  in=318,431,429 out=70,805,233 elapsed=120.9s

  [8956/21087] intraday_17231.csv.gz  in=318,445,565 out=70,819,369 elapsed=120.9s

  [8957/21087] intraday_17233.csv.gz  in=318,458,882 out=70,832,686 elapsed=120.9s

  [8958/21087] intraday_17234.csv.gz  in=318,471,393 out=70,845,197 elapsed=120.9s

  [8959/21087] intraday_17235.csv.gz  in=318,481,841 out=70,855,645 elapsed=120.9s

  [8960/21087] intraday_17238.csv.gz  in=318,490,837 out=70,864,641 elapsed=121.0s

  [8961/21087] intraday_17237.csv.gz  in=318,501,285 out=70,875,089 elapsed=121.0s

  [8962/21087] intraday_17236.csv.gz  in=318,514,788 out=70,888,592 elapsed=121.0s

  [8963/21087] intraday_1724.csv.gz  in=318,526,890 out=70,888,592 elapsed=121.0s

  [8964/21087] intraday_17239.csv.gz  in=318,540,677 out=70,902,379 elapsed=121.0s

  [8965/21087] intraday_17243.csv.gz  in=318,551,031 out=70,912,733 elapsed=121.0s

  [8966/21087] intraday_17242.csv.gz  in=318,562,514 out=70,924,216 elapsed=121.0s

  [8967/21087] intraday_17240.csv.gz  in=318,578,213 out=70,939,915 elapsed=121.0s

  [8968/21087] intraday_17241.csv.gz  in=318,592,948 out=70,954,650 elapsed=121.0s

  [8969/21087] intraday_17244.csv.gz  in=318,606,594 out=70,968,296 elapsed=121.0s

  [8970/21087] intraday_17248.csv.gz  in=318,618,676 out=70,980,378 elapsed=121.1s

  [8971/21087] intraday_17246.csv.gz  in=318,631,151 out=70,992,853 elapsed=121.1s

  [8972/21087] intraday_17247.csv.gz  in=318,643,672 out=71,005,374 elapsed=121.1s

  [8973/21087] intraday_17245.csv.gz  in=318,658,260 out=71,019,962 elapsed=121.1s

  [8974/21087] intraday_1725.csv.gz  in=318,670,246 out=71,019,962 elapsed=121.1s

  [8975/21087] intraday_17250.csv.gz  in=318,679,716 out=71,029,432 elapsed=121.1s

  [8976/21087] intraday_17251.csv.gz  in=318,693,572 out=71,043,288 elapsed=121.1s

  [8977/21087] intraday_17249.csv.gz  in=318,707,827 out=71,057,543 elapsed=121.1s

  [8978/21087] intraday_17252.csv.gz  in=318,722,776 out=71,072,492 elapsed=121.2s

  [8979/21087] intraday_17253.csv.gz  in=318,734,052 out=71,083,768 elapsed=121.2s

  [8980/21087] intraday_17254.csv.gz  in=318,744,595 out=71,094,311 elapsed=121.2s

  [8981/21087] intraday_17255.csv.gz  in=318,756,116 out=71,105,832 elapsed=121.2s

  [8982/21087] intraday_17256.csv.gz  in=318,772,071 out=71,121,787 elapsed=121.2s

  [8983/21087] intraday_17258.csv.gz  in=318,782,690 out=71,132,406 elapsed=121.2s

  [8984/21087] intraday_1726.csv.gz  in=318,795,236 out=71,132,406 elapsed=121.2s

  [8985/21087] intraday_17259.csv.gz  in=318,805,348 out=71,142,518 elapsed=121.2s

  [8986/21087] intraday_17257.csv.gz  in=318,819,009 out=71,156,179 elapsed=121.2s

  [8987/21087] intraday_17263.csv.gz  in=318,832,554 out=71,168,465 elapsed=121.3s

  [8988/21087] intraday_17261.csv.gz  in=318,845,176 out=71,181,087 elapsed=121.3s

  [8989/21087] intraday_17262.csv.gz  in=318,858,499 out=71,194,410 elapsed=121.3s

  [8990/21087] intraday_17260.csv.gz  in=318,871,667 out=71,207,578 elapsed=121.3s

  [8991/21087] intraday_17267.csv.gz  in=318,881,971 out=71,217,882 elapsed=121.3s

  [8992/21087] intraday_17265.csv.gz  in=318,892,996 out=71,228,907 elapsed=121.3s

  [8993/21087] intraday_17266.csv.gz  in=318,905,692 out=71,241,603 elapsed=121.3s

  [8994/21087] intraday_17264.csv.gz  in=318,917,546 out=71,253,457 elapsed=121.3s

  [8995/21087] intraday_1727.csv.gz  in=318,929,443 out=71,253,457 elapsed=121.4s

  [8996/21087] intraday_17268.csv.gz  in=318,944,164 out=71,268,178 elapsed=121.4s

  [8997/21087] intraday_17269.csv.gz  in=318,957,486 out=71,281,500 elapsed=121.4s

  [8998/21087] intraday_17270.csv.gz  in=318,971,947 out=71,295,961 elapsed=121.4s

  [8999/21087] intraday_17271.csv.gz  in=318,984,619 out=71,308,633 elapsed=121.4s

  [9000/21087] intraday_17272.csv.gz  in=319,007,073 out=71,327,748 elapsed=121.4s

  [9001/21087] intraday_17274.csv.gz  in=319,021,022 out=71,341,697 elapsed=121.4s

  [9002/21087] intraday_17273.csv.gz  in=319,035,769 out=71,356,444 elapsed=121.4s

  [9003/21087] intraday_17275.csv.gz  in=319,048,621 out=71,369,296 elapsed=121.4s

  [9004/21087] intraday_17276.csv.gz  in=319,060,693 out=71,381,368 elapsed=121.4s

  [9005/21087] intraday_17278.csv.gz  in=319,070,831 out=71,391,506 elapsed=121.5s

  [9006/21087] intraday_1728.csv.gz  in=319,081,527 out=71,391,506 elapsed=121.5s

  [9007/21087] intraday_17277.csv.gz  in=319,092,814 out=71,402,793 elapsed=121.5s

  [9008/21087] intraday_17279.csv.gz  in=319,104,456 out=71,414,435 elapsed=121.5s

  [9009/21087] intraday_17280.csv.gz  in=319,115,916 out=71,425,895 elapsed=121.5s

  [9010/21087] intraday_17281.csv.gz  in=319,128,553 out=71,438,532 elapsed=121.5s

  [9011/21087] intraday_17284.csv.gz  in=319,141,604 out=71,451,583 elapsed=121.5s

  [9012/21087] intraday_17283.csv.gz  in=319,156,124 out=71,466,103 elapsed=121.5s

  [9013/21087] intraday_17282.csv.gz  in=319,170,078 out=71,480,057 elapsed=121.5s

  [9014/21087] intraday_17285.csv.gz  in=319,181,225 out=71,491,204 elapsed=121.5s

  [9015/21087] intraday_17287.csv.gz  in=319,194,405 out=71,504,384 elapsed=121.6s

  [9016/21087] intraday_17286.csv.gz  in=319,205,602 out=71,515,581 elapsed=121.6s

  [9017/21087] intraday_17288.csv.gz  in=319,217,117 out=71,527,096 elapsed=121.6s

  [9018/21087] intraday_17289.csv.gz  in=319,229,622 out=71,539,601 elapsed=121.6s

  [9019/21087] intraday_1729.csv.gz  in=319,241,738 out=71,539,601 elapsed=121.6s

  [9020/21087] intraday_17290.csv.gz  in=319,253,382 out=71,551,245 elapsed=121.6s

  [9021/21087] intraday_17291.csv.gz  in=319,268,778 out=71,566,641 elapsed=121.6s

  [9022/21087] intraday_17292.csv.gz  in=319,281,368 out=71,579,231 elapsed=121.6s

  [9023/21087] intraday_17293.csv.gz  in=319,294,725 out=71,592,588 elapsed=121.6s

  [9024/21087] intraday_17295.csv.gz  in=319,306,906 out=71,604,769 elapsed=121.7s

  [9025/21087] intraday_17294.csv.gz  in=319,322,118 out=71,619,981 elapsed=121.7s

  [9026/21087] intraday_17297.csv.gz  in=319,333,523 out=71,631,386 elapsed=121.7s

  [9027/21087] intraday_17296.csv.gz  in=319,346,230 out=71,644,093 elapsed=121.7s

  [9028/21087] intraday_1730.csv.gz  in=319,357,506 out=71,644,093 elapsed=121.7s

  [9029/21087] intraday_17298.csv.gz  in=319,370,526 out=71,657,113 elapsed=121.7s

  [9030/21087] intraday_17300.csv.gz  in=319,384,466 out=71,671,053 elapsed=121.7s

  [9031/21087] intraday_17299.csv.gz  in=319,417,836 out=71,695,538 elapsed=121.7s

  [9032/21087] intraday_17301.csv.gz  in=319,428,580 out=71,706,282 elapsed=121.7s

  [9033/21087] intraday_17302.csv.gz  in=319,441,234 out=71,718,936 elapsed=121.8s

  [9034/21087] intraday_17303.csv.gz  in=319,452,026 out=71,729,728 elapsed=121.8s

  [9035/21087] intraday_17304.csv.gz  in=319,468,414 out=71,746,116 elapsed=121.8s

  [9036/21087] intraday_17305.csv.gz  in=319,480,571 out=71,758,273 elapsed=121.8s

  [9037/21087] intraday_17306.csv.gz  in=319,494,753 out=71,772,455 elapsed=121.8s

  [9038/21087] intraday_17307.csv.gz  in=319,509,531 out=71,787,233 elapsed=121.8s

  [9039/21087] intraday_17309.csv.gz  in=319,519,408 out=71,797,110 elapsed=121.8s

  [9040/21087] intraday_17308.csv.gz  in=319,533,316 out=71,809,806 elapsed=121.8s

  [9041/21087] intraday_1731.csv.gz  in=319,544,720 out=71,809,806 elapsed=121.8s

  [9042/21087] intraday_17310.csv.gz  in=319,558,325 out=71,823,411 elapsed=121.8s

  [9043/21087] intraday_17311.csv.gz  in=319,571,574 out=71,836,660 elapsed=121.9s

  [9044/21087] intraday_17313.csv.gz  in=319,582,738 out=71,847,824 elapsed=121.9s

  [9045/21087] intraday_17312.csv.gz  in=319,594,538 out=71,859,624 elapsed=121.9s

  [9046/21087] intraday_17314.csv.gz  in=319,605,226 out=71,870,312 elapsed=121.9s

  [9047/21087] intraday_17315.csv.gz  in=319,615,285 out=71,880,371 elapsed=121.9s

  [9048/21087] intraday_17316.csv.gz  in=319,630,118 out=71,895,204 elapsed=121.9s

  [9049/21087] intraday_17318.csv.gz  in=319,643,652 out=71,908,738 elapsed=121.9s

  [9050/21087] intraday_17317.csv.gz  in=319,655,941 out=71,921,027 elapsed=121.9s

  [9051/21087] intraday_17319.csv.gz  in=319,666,486 out=71,931,572 elapsed=121.9s

  [9052/21087] intraday_1732.csv.gz  in=319,678,589 out=71,931,572 elapsed=121.9s

  [9053/21087] intraday_17320.csv.gz  in=319,689,734 out=71,942,717 elapsed=121.9s

  [9054/21087] intraday_17321.csv.gz  in=319,702,815 out=71,955,798 elapsed=122.0s

  [9055/21087] intraday_17323.csv.gz  in=319,717,628 out=71,970,611 elapsed=122.0s

  [9056/21087] intraday_17322.csv.gz  in=319,733,648 out=71,986,631 elapsed=122.0s

  [9057/21087] intraday_17324.csv.gz  in=319,746,649 out=71,999,632 elapsed=122.0s

  [9058/21087] intraday_17325.csv.gz  in=319,759,290 out=72,012,273 elapsed=122.0s

  [9059/21087] intraday_17328.csv.gz  in=319,774,023 out=72,027,006 elapsed=122.0s

  [9060/21087] intraday_17326.csv.gz  in=319,789,287 out=72,042,270 elapsed=122.0s

  [9061/21087] intraday_17327.csv.gz  in=319,798,617 out=72,051,600 elapsed=122.0s

  [9062/21087] intraday_17329.csv.gz  in=319,808,872 out=72,061,855 elapsed=122.0s

  [9063/21087] intraday_1733.csv.gz  in=319,821,859 out=72,061,855 elapsed=122.1s

  [9064/21087] intraday_17330.csv.gz  in=319,834,203 out=72,074,199 elapsed=122.1s

  [9065/21087] intraday_17331.csv.gz  in=319,848,686 out=72,088,625 elapsed=122.1s

  [9066/21087] intraday_17332.csv.gz  in=319,859,609 out=72,099,548 elapsed=122.1s

  [9067/21087] intraday_17333.csv.gz  in=319,873,074 out=72,113,013 elapsed=122.1s

  [9068/21087] intraday_17334.csv.gz  in=319,885,635 out=72,125,574 elapsed=122.1s

  [9069/21087] intraday_17335.csv.gz  in=319,898,347 out=72,138,286 elapsed=122.1s

  [9070/21087] intraday_17337.csv.gz  in=319,909,168 out=72,149,107 elapsed=122.1s

  [9071/21087] intraday_17336.csv.gz  in=319,921,697 out=72,161,636 elapsed=122.1s

  [9072/21087] intraday_17338.csv.gz  in=319,934,272 out=72,174,211 elapsed=122.1s

  [9073/21087] intraday_17339.csv.gz  in=319,945,547 out=72,185,486 elapsed=122.2s

  [9074/21087] intraday_1734.csv.gz  in=319,955,637 out=72,185,486 elapsed=122.2s

  [9075/21087] intraday_17340.csv.gz  in=319,969,063 out=72,198,912 elapsed=122.2s

  [9076/21087] intraday_17341.csv.gz  in=319,983,306 out=72,213,155 elapsed=122.2s

  [9077/21087] intraday_17343.csv.gz  in=319,994,791 out=72,224,640 elapsed=122.2s

  [9078/21087] intraday_17342.csv.gz  in=320,008,994 out=72,238,843 elapsed=122.2s

  [9079/21087] intraday_17344.csv.gz  in=320,022,940 out=72,252,789 elapsed=122.2s

  [9080/21087] intraday_17345.csv.gz  in=320,037,084 out=72,266,933 elapsed=122.2s

  [9081/21087] intraday_17346.csv.gz  in=320,049,115 out=72,278,964 elapsed=122.2s

  [9082/21087] intraday_17347.csv.gz  in=320,062,498 out=72,292,347 elapsed=122.2s

  [9083/21087] intraday_17348.csv.gz  in=320,076,363 out=72,306,212 elapsed=122.3s

  [9084/21087] intraday_1735.csv.gz  in=320,087,569 out=72,306,212 elapsed=122.3s

  [9085/21087] intraday_17349.csv.gz  in=320,101,967 out=72,320,610 elapsed=122.3s

  [9086/21087] intraday_17350.csv.gz  in=320,113,299 out=72,331,942 elapsed=122.3s

  [9087/21087] intraday_17351.csv.gz  in=320,127,283 out=72,345,926 elapsed=122.3s

  [9088/21087] intraday_17352.csv.gz  in=320,140,356 out=72,358,999 elapsed=122.3s

  [9089/21087] intraday_17353.csv.gz  in=320,154,443 out=72,373,086 elapsed=122.3s

  [9090/21087] intraday_17354.csv.gz  in=320,170,766 out=72,389,409 elapsed=122.3s

  [9091/21087] intraday_17357.csv.gz  in=320,188,066 out=72,406,709 elapsed=122.4s

  [9092/21087] intraday_17356.csv.gz  in=320,201,103 out=72,419,746 elapsed=122.4s

  [9093/21087] intraday_17358.csv.gz  in=320,213,114 out=72,431,757 elapsed=122.4s

  [9094/21087] intraday_17355.csv.gz  in=320,232,020 out=72,450,663 elapsed=122.4s

  [9095/21087] intraday_1736.csv.gz  in=320,243,620 out=72,450,663 elapsed=122.4s

  [9096/21087] intraday_17360.csv.gz  in=320,254,414 out=72,461,457 elapsed=122.4s

  [9097/21087] intraday_17359.csv.gz  in=320,267,435 out=72,474,478 elapsed=122.4s

  [9098/21087] intraday_17361.csv.gz  in=320,280,397 out=72,487,440 elapsed=122.4s

  [9099/21087] intraday_17362.csv.gz  in=320,290,588 out=72,497,631 elapsed=122.4s

  [9100/21087] intraday_17363.csv.gz  in=320,305,055 out=72,512,098 elapsed=122.5s

  [9101/21087] intraday_17364.csv.gz  in=320,318,375 out=72,525,418 elapsed=122.5s

  [9102/21087] intraday_17365.csv.gz  in=320,332,597 out=72,539,640 elapsed=122.5s

  [9103/21087] intraday_17366.csv.gz  in=320,344,533 out=72,551,576 elapsed=122.5s

  [9104/21087] intraday_17367.csv.gz  in=320,356,239 out=72,563,282 elapsed=122.5s

  [9105/21087] intraday_1737.csv.gz  in=320,371,968 out=72,563,282 elapsed=122.5s

  [9106/21087] intraday_17368.csv.gz  in=320,384,990 out=72,576,304 elapsed=122.5s

  [9107/21087] intraday_17369.csv.gz  in=320,398,570 out=72,589,884 elapsed=122.5s

  [9108/21087] intraday_17370.csv.gz  in=320,409,851 out=72,601,165 elapsed=122.5s

  [9109/21087] intraday_17371.csv.gz  in=320,423,874 out=72,615,188 elapsed=122.5s

  [9110/21087] intraday_17372.csv.gz  in=320,438,526 out=72,629,840 elapsed=122.6s

  [9111/21087] intraday_17373.csv.gz  in=320,452,783 out=72,644,097 elapsed=122.6s

  [9112/21087] intraday_17374.csv.gz  in=320,469,166 out=72,660,480 elapsed=122.6s

  [9113/21087] intraday_17375.csv.gz  in=320,479,748 out=72,671,062 elapsed=122.6s

  [9114/21087] intraday_17376.csv.gz  in=320,494,250 out=72,685,564 elapsed=122.6s

  [9115/21087] intraday_17377.csv.gz  in=320,506,201 out=72,697,515 elapsed=122.6s

  [9116/21087] intraday_17378.csv.gz  in=320,516,915 out=72,708,229 elapsed=122.6s

  [9117/21087] intraday_1738.csv.gz  in=320,527,967 out=72,708,229 elapsed=122.6s

  [9118/21087] intraday_17379.csv.gz  in=320,541,375 out=72,721,637 elapsed=122.6s

  [9119/21087] intraday_17380.csv.gz  in=320,549,877 out=72,730,139 elapsed=122.6s

  [9120/21087] intraday_17382.csv.gz  in=320,556,940 out=72,737,202 elapsed=122.6s

  [9121/21087] intraday_17381.csv.gz  in=320,568,999 out=72,749,261 elapsed=122.6s

  [9122/21087] intraday_17383.csv.gz  in=320,584,768 out=72,765,030 elapsed=122.7s

  [9123/21087] intraday_17384.csv.gz  in=320,599,054 out=72,779,316 elapsed=122.7s

  [9124/21087] intraday_17385.csv.gz  in=320,610,989 out=72,791,251 elapsed=122.7s

  [9125/21087] intraday_17386.csv.gz  in=320,621,848 out=72,802,110 elapsed=122.7s

  [9126/21087] intraday_17387.csv.gz  in=320,635,176 out=72,815,438 elapsed=122.7s

  [9127/21087] intraday_17388.csv.gz  in=320,650,657 out=72,830,919 elapsed=122.7s

  [9128/21087] intraday_1739.csv.gz  in=320,660,230 out=72,830,919 elapsed=122.7s

  [9129/21087] intraday_17390.csv.gz  in=320,671,614 out=72,842,303 elapsed=122.7s

  [9130/21087] intraday_17389.csv.gz  in=320,684,652 out=72,855,341 elapsed=122.7s

  [9131/21087] intraday_17391.csv.gz  in=320,697,712 out=72,868,401 elapsed=122.8s

  [9132/21087] intraday_17392.csv.gz  in=320,712,122 out=72,882,811 elapsed=122.8s

  [9133/21087] intraday_17393.csv.gz  in=320,723,027 out=72,893,716 elapsed=122.8s

  [9134/21087] intraday_17394.csv.gz  in=320,740,608 out=72,910,071 elapsed=122.8s

  [9135/21087] intraday_17396.csv.gz  in=320,752,708 out=72,922,171 elapsed=122.8s

  [9136/21087] intraday_17395.csv.gz  in=320,766,143 out=72,935,606 elapsed=122.8s

  [9137/21087] intraday_17397.csv.gz  in=320,777,523 out=72,946,986 elapsed=122.8s

  [9138/21087] intraday_17398.csv.gz  in=320,789,313 out=72,958,776 elapsed=122.8s

  [9139/21087] intraday_1740.csv.gz  in=320,800,130 out=72,958,776 elapsed=122.8s

  [9140/21087] intraday_17400.csv.gz  in=320,813,761 out=72,972,407 elapsed=122.8s

  [9141/21087] intraday_17399.csv.gz  in=320,829,149 out=72,987,795 elapsed=122.9s

  [9142/21087] intraday_17402.csv.gz  in=320,840,064 out=72,998,710 elapsed=122.9s

  [9143/21087] intraday_17401.csv.gz  in=320,850,562 out=73,009,208 elapsed=122.9s

  [9144/21087] intraday_17403.csv.gz  in=320,863,573 out=73,022,219 elapsed=122.9s

  [9145/21087] intraday_17406.csv.gz  in=320,876,037 out=73,034,683 elapsed=122.9s

  [9146/21087] intraday_17404.csv.gz  in=320,888,632 out=73,047,278 elapsed=122.9s

  [9147/21087] intraday_17405.csv.gz  in=320,900,283 out=73,058,929 elapsed=122.9s

  [9148/21087] intraday_17407.csv.gz  in=320,920,957 out=73,079,603 elapsed=122.9s

  [9149/21087] intraday_17408.csv.gz  in=320,932,214 out=73,090,860 elapsed=122.9s

  [9150/21087] intraday_17409.csv.gz  in=320,944,119 out=73,102,765 elapsed=122.9s

  [9151/21087] intraday_1741.csv.gz  in=320,956,639 out=73,102,765 elapsed=122.9s

  [9152/21087] intraday_17410.csv.gz  in=320,966,851 out=73,112,977 elapsed=123.0s

  [9153/21087] intraday_17412.csv.gz  in=320,980,570 out=73,126,696 elapsed=123.0s

  [9154/21087] intraday_17411.csv.gz  in=320,995,660 out=73,141,786 elapsed=123.0s

  [9155/21087] intraday_17413.csv.gz  in=321,008,761 out=73,154,887 elapsed=123.0s

  [9156/21087] intraday_17414.csv.gz  in=321,021,154 out=73,167,280 elapsed=123.0s

  [9157/21087] intraday_17415.csv.gz  in=321,032,456 out=73,178,582 elapsed=123.0s

  [9158/21087] intraday_17416.csv.gz  in=321,047,608 out=73,193,734 elapsed=123.1s

  [9159/21087] intraday_17417.csv.gz  in=321,061,776 out=73,207,902 elapsed=123.1s

  [9160/21087] intraday_17418.csv.gz  in=321,075,523 out=73,221,649 elapsed=123.1s

  [9161/21087] intraday_17419.csv.gz  in=321,086,766 out=73,232,892 elapsed=123.1s

  [9162/21087] intraday_1742.csv.gz  in=321,103,446 out=73,232,892 elapsed=123.1s

  [9163/21087] intraday_17421.csv.gz  in=321,113,486 out=73,242,932 elapsed=123.1s

  [9164/21087] intraday_17420.csv.gz  in=321,124,338 out=73,253,784 elapsed=123.1s

  [9165/21087] intraday_17422.csv.gz  in=321,135,488 out=73,264,934 elapsed=123.1s

  [9166/21087] intraday_17423.csv.gz  in=321,147,964 out=73,277,410 elapsed=123.1s

  [9167/21087] intraday_17424.csv.gz  in=321,159,760 out=73,289,206 elapsed=123.1s

  [9168/21087] intraday_17425.csv.gz  in=321,173,350 out=73,302,796 elapsed=123.1s

  [9169/21087] intraday_17426.csv.gz  in=321,187,172 out=73,316,618 elapsed=123.1s

  [9170/21087] intraday_17427.csv.gz  in=321,200,496 out=73,329,942 elapsed=123.2s

  [9171/21087] intraday_1743.csv.gz  in=321,214,089 out=73,329,942 elapsed=123.2s

  [9172/21087] intraday_17429.csv.gz  in=321,225,599 out=73,341,452 elapsed=123.2s

  [9173/21087] intraday_17428.csv.gz  in=321,236,728 out=73,352,581 elapsed=123.2s

  [9174/21087] intraday_17430.csv.gz  in=321,249,809 out=73,365,662 elapsed=123.2s

  [9175/21087] intraday_17431.csv.gz  in=321,262,571 out=73,378,424 elapsed=123.2s

  [9176/21087] intraday_17432.csv.gz  in=321,275,653 out=73,391,506 elapsed=123.2s

  [9177/21087] intraday_17433.csv.gz  in=321,288,082 out=73,403,935 elapsed=123.2s

  [9178/21087] intraday_17434.csv.gz  in=321,302,777 out=73,418,630 elapsed=123.3s

  [9179/21087] intraday_17437.csv.gz  in=321,317,155 out=73,433,008 elapsed=123.3s

  [9180/21087] intraday_17436.csv.gz  in=321,329,674 out=73,445,527 elapsed=123.3s

  [9181/21087] intraday_17438.csv.gz  in=321,341,704 out=73,457,557 elapsed=123.3s

  [9182/21087] intraday_17435.csv.gz  in=321,355,162 out=73,471,015 elapsed=123.3s

  [9183/21087] intraday_1744.csv.gz  in=321,367,960 out=73,471,015 elapsed=123.3s

  [9184/21087] intraday_17439.csv.gz  in=321,380,547 out=73,483,602 elapsed=123.3s

  [9185/21087] intraday_17440.csv.gz  in=321,393,075 out=73,496,130 elapsed=123.3s

  [9186/21087] intraday_17441.csv.gz  in=321,405,878 out=73,508,933 elapsed=123.4s

  [9187/21087] intraday_17442.csv.gz  in=321,416,996 out=73,520,051 elapsed=123.4s

  [9188/21087] intraday_17443.csv.gz  in=321,429,597 out=73,532,652 elapsed=123.4s

  [9189/21087] intraday_17444.csv.gz  in=321,441,621 out=73,544,676 elapsed=123.4s

  [9190/21087] intraday_17445.csv.gz  in=321,452,897 out=73,555,952 elapsed=123.4s

  [9191/21087] intraday_17447.csv.gz  in=321,467,675 out=73,570,730 elapsed=123.4s

  [9192/21087] intraday_17446.csv.gz  in=321,479,472 out=73,582,527 elapsed=123.4s

  [9193/21087] intraday_17448.csv.gz  in=321,492,475 out=73,595,530 elapsed=123.4s

  [9194/21087] intraday_17449.csv.gz  in=321,506,129 out=73,609,184 elapsed=123.4s

  [9195/21087] intraday_1745.csv.gz  in=321,519,064 out=73,609,184 elapsed=123.5s

  [9196/21087] intraday_17451.csv.gz  in=321,529,791 out=73,619,911 elapsed=123.5s

  [9197/21087] intraday_17452.csv.gz  in=321,540,393 out=73,630,513 elapsed=123.5s

  [9198/21087] intraday_17450.csv.gz  in=321,556,408 out=73,645,701 elapsed=123.5s

  [9199/21087] intraday_17453.csv.gz  in=321,569,782 out=73,659,075 elapsed=123.5s

  [9200/21087] intraday_17455.csv.gz  in=321,581,877 out=73,671,170 elapsed=123.5s

  [9201/21087] intraday_17456.csv.gz  in=321,592,255 out=73,681,548 elapsed=123.5s

  [9202/21087] intraday_17457.csv.gz  in=321,603,005 out=73,692,298 elapsed=123.5s

  [9203/21087] intraday_17454.csv.gz  in=321,616,099 out=73,705,392 elapsed=123.5s

  [9204/21087] intraday_17458.csv.gz  in=321,626,741 out=73,716,034 elapsed=123.5s

  [9205/21087] intraday_17459.csv.gz  in=321,641,374 out=73,730,667 elapsed=123.6s

  [9206/21087] intraday_1746.csv.gz  in=321,655,206 out=73,730,667 elapsed=123.6s

  [9207/21087] intraday_17460.csv.gz  in=321,667,894 out=73,743,355 elapsed=123.6s

  [9208/21087] intraday_17461.csv.gz  in=321,682,765 out=73,758,226 elapsed=123.6s

  [9209/21087] intraday_17462.csv.gz  in=321,692,704 out=73,768,165 elapsed=123.6s

  [9210/21087] intraday_17463.csv.gz  in=321,704,387 out=73,779,848 elapsed=123.6s

  [9211/21087] intraday_17464.csv.gz  in=321,717,875 out=73,793,336 elapsed=123.6s

  [9212/21087] intraday_17465.csv.gz  in=321,732,344 out=73,807,805 elapsed=123.6s

  [9213/21087] intraday_17466.csv.gz  in=321,747,442 out=73,822,903 elapsed=123.7s

  [9214/21087] intraday_17467.csv.gz  in=321,762,073 out=73,837,534 elapsed=123.7s

  [9215/21087] intraday_17468.csv.gz  in=321,772,309 out=73,847,770 elapsed=123.7s

  [9216/21087] intraday_17469.csv.gz  in=321,787,472 out=73,862,933 elapsed=123.7s

  [9217/21087] intraday_1747.csv.gz  in=321,801,108 out=73,862,933 elapsed=123.7s

  [9218/21087] intraday_17470.csv.gz  in=321,812,386 out=73,874,211 elapsed=123.7s

  [9219/21087] intraday_17472.csv.gz  in=321,822,886 out=73,884,711 elapsed=123.7s

  [9220/21087] intraday_17471.csv.gz  in=321,836,256 out=73,898,081 elapsed=123.7s

  [9221/21087] intraday_17473.csv.gz  in=321,848,722 out=73,910,547 elapsed=123.7s

  [9222/21087] intraday_17474.csv.gz  in=321,861,151 out=73,922,976 elapsed=123.7s

  [9223/21087] intraday_17475.csv.gz  in=321,873,765 out=73,935,590 elapsed=123.7s

  [9224/21087] intraday_17476.csv.gz  in=321,887,022 out=73,948,847 elapsed=123.7s

  [9225/21087] intraday_17477.csv.gz  in=321,899,402 out=73,961,227 elapsed=123.8s

  [9226/21087] intraday_17478.csv.gz  in=321,913,773 out=73,975,598 elapsed=123.8s

  [9227/21087] intraday_1748.csv.gz  in=321,927,765 out=73,975,598 elapsed=123.8s

  [9228/21087] intraday_17479.csv.gz  in=321,939,129 out=73,986,962 elapsed=123.8s

  [9229/21087] intraday_17480.csv.gz  in=321,950,817 out=73,998,650 elapsed=123.8s

  [9230/21087] intraday_17481.csv.gz  in=321,963,560 out=74,011,393 elapsed=123.8s

  [9231/21087] intraday_17482.csv.gz  in=321,975,930 out=74,023,763 elapsed=123.8s

  [9232/21087] intraday_17483.csv.gz  in=321,989,625 out=74,037,458 elapsed=123.8s

  [9233/21087] intraday_17484.csv.gz  in=322,003,150 out=74,050,983 elapsed=123.8s

  [9234/21087] intraday_17485.csv.gz  in=322,016,352 out=74,063,685 elapsed=123.9s

  [9235/21087] intraday_17486.csv.gz  in=322,027,619 out=74,074,952 elapsed=123.9s

  [9236/21087] intraday_17488.csv.gz  in=322,041,067 out=74,088,400 elapsed=123.9s

  [9237/21087] intraday_17487.csv.gz  in=322,054,640 out=74,101,973 elapsed=123.9s

  [9238/21087] intraday_17489.csv.gz  in=322,067,556 out=74,114,889 elapsed=123.9s

  [9239/21087] intraday_17490.csv.gz  in=322,080,581 out=74,127,914 elapsed=123.9s

  [9240/21087] intraday_1749.csv.gz  in=322,099,894 out=74,127,914 elapsed=123.9s

  [9241/21087] intraday_17491.csv.gz  in=322,113,592 out=74,141,612 elapsed=123.9s

  [9242/21087] intraday_17492.csv.gz  in=322,128,942 out=74,156,962 elapsed=123.9s

  [9243/21087] intraday_17493.csv.gz  in=322,140,998 out=74,169,018 elapsed=124.0s

  [9244/21087] intraday_17494.csv.gz  in=322,154,135 out=74,182,155 elapsed=124.0s

  [9245/21087] intraday_17495.csv.gz  in=322,167,975 out=74,195,995 elapsed=124.0s

  [9246/21087] intraday_17496.csv.gz  in=322,189,392 out=74,215,104 elapsed=124.0s

  [9247/21087] intraday_17497.csv.gz  in=322,205,924 out=74,231,636 elapsed=124.0s

  [9248/21087] intraday_1750.csv.gz  in=322,216,447 out=74,231,636 elapsed=124.0s

  [9249/21087] intraday_17498.csv.gz  in=322,235,832 out=74,251,021 elapsed=124.0s

  [9250/21087] intraday_17499.csv.gz  in=322,250,825 out=74,266,014 elapsed=124.0s

  [9251/21087] intraday_17500.csv.gz  in=322,266,575 out=74,281,764 elapsed=124.0s

  [9252/21087] intraday_17501.csv.gz  in=322,279,716 out=74,294,905 elapsed=124.1s

  [9253/21087] intraday_17502.csv.gz  in=322,292,582 out=74,307,771 elapsed=124.1s

  [9254/21087] intraday_17503.csv.gz  in=322,303,175 out=74,318,364 elapsed=124.1s

  [9255/21087] intraday_17504.csv.gz  in=322,316,068 out=74,331,257 elapsed=124.1s

  [9256/21087] intraday_17505.csv.gz  in=322,327,100 out=74,342,289 elapsed=124.1s

  [9257/21087] intraday_17506.csv.gz  in=322,340,653 out=74,355,842 elapsed=124.1s

  [9258/21087] intraday_17507.csv.gz  in=322,355,257 out=74,370,446 elapsed=124.1s

  [9259/21087] intraday_17508.csv.gz  in=322,369,167 out=74,384,356 elapsed=124.1s

  [9260/21087] intraday_17509.csv.gz  in=322,381,561 out=74,396,750 elapsed=124.1s

  [9261/21087] intraday_1751.csv.gz  in=322,393,121 out=74,396,750 elapsed=124.1s

  [9262/21087] intraday_17510.csv.gz  in=322,405,921 out=74,409,550 elapsed=124.2s

  [9263/21087] intraday_17511.csv.gz  in=322,418,564 out=74,422,193 elapsed=124.2s

  [9264/21087] intraday_17512.csv.gz  in=322,431,797 out=74,435,426 elapsed=124.2s

  [9265/21087] intraday_17513.csv.gz  in=322,445,150 out=74,448,779 elapsed=124.2s

  [9266/21087] intraday_17514.csv.gz  in=322,458,882 out=74,462,511 elapsed=124.2s

  [9267/21087] intraday_17515.csv.gz  in=322,473,664 out=74,477,293 elapsed=124.2s

  [9268/21087] intraday_17516.csv.gz  in=322,488,261 out=74,491,890 elapsed=124.2s

  [9269/21087] intraday_17517.csv.gz  in=322,502,686 out=74,506,315 elapsed=124.2s

  [9270/21087] intraday_17518.csv.gz  in=322,514,398 out=74,518,027 elapsed=124.2s

  [9271/21087] intraday_1752.csv.gz  in=322,525,831 out=74,518,027 elapsed=124.2s

  [9272/21087] intraday_17519.csv.gz  in=322,539,772 out=74,531,968 elapsed=124.2s

  [9273/21087] intraday_17520.csv.gz  in=322,551,371 out=74,543,567 elapsed=124.3s

  [9274/21087] intraday_17521.csv.gz  in=322,563,694 out=74,555,890 elapsed=124.3s

  [9275/21087] intraday_17523.csv.gz  in=322,572,746 out=74,564,942 elapsed=124.3s

  [9276/21087] intraday_17522.csv.gz  in=322,583,519 out=74,575,715 elapsed=124.3s

  [9277/21087] intraday_17525.csv.gz  in=322,587,764 out=74,579,960 elapsed=124.3s

  [9278/21087] intraday_17526.csv.gz  in=322,602,579 out=74,594,775 elapsed=124.3s

  [9279/21087] intraday_17524.csv.gz  in=322,615,024 out=74,607,220 elapsed=124.3s

  [9280/21087] intraday_17527.csv.gz  in=322,628,338 out=74,620,534 elapsed=124.3s

  [9281/21087] intraday_17528.csv.gz  in=322,640,104 out=74,632,300 elapsed=124.4s

  [9282/21087] intraday_1753.csv.gz  in=322,653,752 out=74,632,300 elapsed=124.4s

  [9283/21087] intraday_17529.csv.gz  in=322,664,998 out=74,643,546 elapsed=124.4s

  [9284/21087] intraday_17530.csv.gz  in=322,678,107 out=74,656,655 elapsed=124.4s

  [9285/21087] intraday_17531.csv.gz  in=322,691,811 out=74,670,359 elapsed=124.4s

  [9286/21087] intraday_17533.csv.gz  in=322,701,792 out=74,680,340 elapsed=124.4s

  [9287/21087] intraday_17532.csv.gz  in=322,714,083 out=74,692,631 elapsed=124.4s

  [9288/21087] intraday_17534.csv.gz  in=322,728,314 out=74,706,862 elapsed=124.5s

  [9289/21087] intraday_17535.csv.gz  in=322,739,988 out=74,718,536 elapsed=124.5s

  [9290/21087] intraday_17537.csv.gz  in=322,751,785 out=74,730,333 elapsed=124.5s

  [9291/21087] intraday_17536.csv.gz  in=322,762,076 out=74,740,624 elapsed=124.5s

  [9292/21087] intraday_17538.csv.gz  in=322,774,570 out=74,753,118 elapsed=124.5s

  [9293/21087] intraday_17539.csv.gz  in=322,786,136 out=74,764,684 elapsed=124.5s

  [9294/21087] intraday_1754.csv.gz  in=322,796,734 out=74,764,684 elapsed=124.5s

  [9295/21087] intraday_17540.csv.gz  in=322,807,692 out=74,775,642 elapsed=124.5s

  [9296/21087] intraday_17541.csv.gz  in=322,818,096 out=74,786,046 elapsed=124.5s

  [9297/21087] intraday_17542.csv.gz  in=322,832,459 out=74,800,409 elapsed=124.6s

  [9298/21087] intraday_17543.csv.gz  in=322,844,997 out=74,812,947 elapsed=124.6s

  [9299/21087] intraday_17544.csv.gz  in=322,854,948 out=74,822,898 elapsed=124.6s

  [9300/21087] intraday_17545.csv.gz  in=322,865,785 out=74,833,735 elapsed=124.6s

  [9301/21087] intraday_17546.csv.gz  in=322,877,342 out=74,845,292 elapsed=124.6s

  [9302/21087] intraday_17547.csv.gz  in=322,890,384 out=74,858,334 elapsed=124.6s

  [9303/21087] intraday_17548.csv.gz  in=322,901,853 out=74,869,803 elapsed=124.6s

  [9304/21087] intraday_1755.csv.gz  in=322,914,406 out=74,869,803 elapsed=124.6s

  [9305/21087] intraday_17549.csv.gz  in=322,926,023 out=74,881,420 elapsed=124.6s

  [9306/21087] intraday_17550.csv.gz  in=322,938,712 out=74,894,109 elapsed=124.6s

  [9307/21087] intraday_17551.csv.gz  in=322,949,538 out=74,904,935 elapsed=124.6s

  [9308/21087] intraday_17552.csv.gz  in=322,961,679 out=74,917,076 elapsed=124.7s

  [9309/21087] intraday_17553.csv.gz  in=322,972,722 out=74,928,119 elapsed=124.7s

  [9310/21087] intraday_17555.csv.gz  in=322,986,158 out=74,941,555 elapsed=124.7s

  [9311/21087] intraday_17554.csv.gz  in=322,999,785 out=74,955,182 elapsed=124.7s

  [9312/21087] intraday_17556.csv.gz  in=323,011,420 out=74,966,817 elapsed=124.7s

  [9313/21087] intraday_17557.csv.gz  in=323,023,534 out=74,978,931 elapsed=124.7s

  [9314/21087] intraday_17558.csv.gz  in=323,034,820 out=74,990,217 elapsed=124.7s

  [9315/21087] intraday_17559.csv.gz  in=323,047,559 out=75,002,956 elapsed=124.7s

  [9316/21087] intraday_1756.csv.gz  in=323,059,417 out=75,002,956 elapsed=124.7s

  [9317/21087] intraday_17560.csv.gz  in=323,073,117 out=75,016,656 elapsed=124.7s

  [9318/21087] intraday_17562.csv.gz  in=323,084,134 out=75,027,673 elapsed=124.8s

  [9319/21087] intraday_17563.csv.gz  in=323,094,217 out=75,037,756 elapsed=124.8s

  [9320/21087] intraday_17564.csv.gz  in=323,105,023 out=75,048,562 elapsed=124.8s

  [9321/21087] intraday_17561.csv.gz  in=323,127,640 out=75,069,067 elapsed=124.8s

  [9322/21087] intraday_17565.csv.gz  in=323,137,866 out=75,079,293 elapsed=124.8s

  [9323/21087] intraday_17566.csv.gz  in=323,150,106 out=75,091,533 elapsed=124.8s

  [9324/21087] intraday_17567.csv.gz  in=323,161,668 out=75,103,095 elapsed=124.8s

  [9325/21087] intraday_17568.csv.gz  in=323,173,867 out=75,115,294 elapsed=124.8s

  [9326/21087] intraday_1757.csv.gz  in=323,185,263 out=75,115,294 elapsed=124.8s

  [9327/21087] intraday_17569.csv.gz  in=323,198,891 out=75,128,922 elapsed=124.8s

  [9328/21087] intraday_17570.csv.gz  in=323,211,127 out=75,141,158 elapsed=124.8s

  [9329/21087] intraday_17572.csv.gz  in=323,222,147 out=75,152,178 elapsed=124.9s

  [9330/21087] intraday_17573.csv.gz  in=323,234,075 out=75,164,106 elapsed=124.9s

  [9331/21087] intraday_17571.csv.gz  in=323,245,137 out=75,175,168 elapsed=124.9s

  [9332/21087] intraday_17574.csv.gz  in=323,257,391 out=75,187,422 elapsed=124.9s

  [9333/21087] intraday_17575.csv.gz  in=323,270,563 out=75,200,594 elapsed=124.9s

  [9334/21087] intraday_17576.csv.gz  in=323,286,474 out=75,214,892 elapsed=124.9s

  [9335/21087] intraday_17578.csv.gz  in=323,299,925 out=75,228,343 elapsed=124.9s

  [9336/21087] intraday_17577.csv.gz  in=323,313,975 out=75,242,393 elapsed=124.9s

  [9337/21087] intraday_1758.csv.gz  in=323,328,646 out=75,242,393 elapsed=124.9s

  [9338/21087] intraday_17579.csv.gz  in=323,339,557 out=75,253,304 elapsed=125.0s

  [9339/21087] intraday_17580.csv.gz  in=323,352,913 out=75,266,660 elapsed=125.0s

  [9340/21087] intraday_17582.csv.gz  in=323,364,512 out=75,278,259 elapsed=125.0s

  [9341/21087] intraday_17583.csv.gz  in=323,375,133 out=75,288,880 elapsed=125.0s

  [9342/21087] intraday_17581.csv.gz  in=323,386,540 out=75,300,287 elapsed=125.0s

  [9343/21087] intraday_17584.csv.gz  in=323,399,490 out=75,313,237 elapsed=125.0s

  [9344/21087] intraday_17585.csv.gz  in=323,410,203 out=75,323,950 elapsed=125.0s

  [9345/21087] intraday_17587.csv.gz  in=323,421,716 out=75,335,463 elapsed=125.1s

  [9346/21087] intraday_17586.csv.gz  in=323,433,421 out=75,347,168 elapsed=125.1s

  [9347/21087] intraday_17589.csv.gz  in=323,445,680 out=75,359,427 elapsed=125.1s

  [9348/21087] intraday_1759.csv.gz  in=323,456,904 out=75,359,427 elapsed=125.1s

  [9349/21087] intraday_17588.csv.gz  in=323,477,778 out=75,377,029 elapsed=125.1s

  [9350/21087] intraday_17590.csv.gz  in=323,495,211 out=75,393,090 elapsed=125.1s

  [9351/21087] intraday_17591.csv.gz  in=323,508,002 out=75,405,881 elapsed=125.1s

  [9352/21087] intraday_17593.csv.gz  in=323,520,686 out=75,418,565 elapsed=125.1s

  [9353/21087] intraday_17592.csv.gz  in=323,533,597 out=75,431,476 elapsed=125.1s

  [9354/21087] intraday_17595.csv.gz  in=323,543,114 out=75,440,993 elapsed=125.1s

  [9355/21087] intraday_17594.csv.gz  in=323,554,346 out=75,452,032 elapsed=125.1s

  [9356/21087] intraday_17596.csv.gz  in=323,566,865 out=75,464,551 elapsed=125.2s

  [9357/21087] intraday_17597.csv.gz  in=323,583,582 out=75,481,268 elapsed=125.2s

  [9358/21087] intraday_17598.csv.gz  in=323,595,357 out=75,493,043 elapsed=125.2s

  [9359/21087] intraday_1760.csv.gz  in=323,612,564 out=75,493,043 elapsed=125.2s

  [9360/21087] intraday_17599.csv.gz  in=323,622,741 out=75,503,220 elapsed=125.2s

  [9361/21087] intraday_17600.csv.gz  in=323,633,737 out=75,514,216 elapsed=125.2s

  [9362/21087] intraday_17601.csv.gz  in=323,643,748 out=75,524,227 elapsed=125.2s

  [9363/21087] intraday_17602.csv.gz  in=323,656,991 out=75,537,470 elapsed=125.2s

  [9364/21087] intraday_17603.csv.gz  in=323,669,639 out=75,550,118 elapsed=125.2s

  [9365/21087] intraday_17605.csv.gz  in=323,679,466 out=75,559,945 elapsed=125.2s

  [9366/21087] intraday_17604.csv.gz  in=323,692,073 out=75,572,552 elapsed=125.2s

  [9367/21087] intraday_17606.csv.gz  in=323,703,077 out=75,583,556 elapsed=125.3s

  [9368/21087] intraday_17607.csv.gz  in=323,715,931 out=75,596,410 elapsed=125.3s

  [9369/21087] intraday_17609.csv.gz  in=323,729,318 out=75,609,797 elapsed=125.3s

  [9370/21087] intraday_17608.csv.gz  in=323,743,534 out=75,624,013 elapsed=125.3s

  [9371/21087] intraday_1761.csv.gz  in=323,757,537 out=75,624,013 elapsed=125.3s

  [9372/21087] intraday_17610.csv.gz  in=323,770,844 out=75,637,320 elapsed=125.3s

  [9373/21087] intraday_17611.csv.gz  in=323,781,520 out=75,647,996 elapsed=125.3s

  [9374/21087] intraday_17612.csv.gz  in=323,796,146 out=75,662,622 elapsed=125.3s

  [9375/21087] intraday_17613.csv.gz  in=323,806,134 out=75,672,610 elapsed=125.3s

  [9376/21087] intraday_17615.csv.gz  in=323,816,314 out=75,682,790 elapsed=125.3s

  [9377/21087] intraday_17614.csv.gz  in=323,828,708 out=75,695,184 elapsed=125.3s

  [9378/21087] intraday_17617.csv.gz  in=323,840,907 out=75,707,383 elapsed=125.4s

  [9379/21087] intraday_17616.csv.gz  in=323,852,563 out=75,719,039 elapsed=125.4s

  [9380/21087] intraday_17619.csv.gz  in=323,865,621 out=75,732,097 elapsed=125.4s

  [9381/21087] intraday_17618.csv.gz  in=323,883,938 out=75,747,337 elapsed=125.4s

  [9382/21087] intraday_1762.csv.gz  in=323,897,437 out=75,747,337 elapsed=125.4s

  [9383/21087] intraday_17620.csv.gz  in=323,909,257 out=75,759,157 elapsed=125.4s

  [9384/21087] intraday_17621.csv.gz  in=323,922,772 out=75,772,672 elapsed=125.4s

  [9385/21087] intraday_17623.csv.gz  in=323,933,116 out=75,783,016 elapsed=125.4s

  [9386/21087] intraday_17622.csv.gz  in=323,944,990 out=75,794,890 elapsed=125.4s

  [9387/21087] intraday_17624.csv.gz  in=323,956,932 out=75,806,832 elapsed=125.5s

  [9388/21087] intraday_17625.csv.gz  in=323,968,670 out=75,818,570 elapsed=125.5s

  [9389/21087] intraday_17628.csv.gz  in=323,980,136 out=75,830,036 elapsed=125.5s

  [9390/21087] intraday_17627.csv.gz  in=323,993,198 out=75,843,098 elapsed=125.5s

  [9391/21087] intraday_17626.csv.gz  in=324,008,105 out=75,856,585 elapsed=125.5s

  [9392/21087] intraday_17629.csv.gz  in=324,019,096 out=75,867,576 elapsed=125.5s

  [9393/21087] intraday_17630.csv.gz  in=324,032,236 out=75,880,716 elapsed=125.6s

  [9394/21087] intraday_1763.csv.gz  in=324,066,838 out=75,880,716 elapsed=125.6s

  [9395/21087] intraday_17631.csv.gz  in=324,078,705 out=75,892,583 elapsed=125.6s

  [9396/21087] intraday_17632.csv.gz  in=324,090,344 out=75,904,222 elapsed=125.6s

  [9397/21087] intraday_17633.csv.gz  in=324,102,398 out=75,916,276 elapsed=125.6s

  [9398/21087] intraday_17634.csv.gz  in=324,115,719 out=75,929,597 elapsed=125.6s

  [9399/21087] intraday_17635.csv.gz  in=324,130,194 out=75,944,072 elapsed=125.6s

  [9400/21087] intraday_17636.csv.gz  in=324,142,233 out=75,956,111 elapsed=125.6s

  [9401/21087] intraday_17637.csv.gz  in=324,154,490 out=75,968,368 elapsed=125.6s

  [9402/21087] intraday_17638.csv.gz  in=324,166,378 out=75,980,256 elapsed=125.6s

  [9403/21087] intraday_1764.csv.gz  in=324,180,231 out=75,980,256 elapsed=125.6s

  [9404/21087] intraday_17639.csv.gz  in=324,193,547 out=75,993,572 elapsed=125.6s

  [9405/21087] intraday_17640.csv.gz  in=324,207,136 out=76,007,161 elapsed=125.7s

  [9406/21087] intraday_17641.csv.gz  in=324,224,126 out=76,024,151 elapsed=125.7s

  [9407/21087] intraday_17642.csv.gz  in=324,238,302 out=76,038,327 elapsed=125.7s

  [9408/21087] intraday_17643.csv.gz  in=324,253,157 out=76,053,182 elapsed=125.7s

  [9409/21087] intraday_17644.csv.gz  in=324,265,014 out=76,065,039 elapsed=125.7s

  [9410/21087] intraday_17646.csv.gz  in=324,275,577 out=76,075,602 elapsed=125.7s

  [9411/21087] intraday_17647.csv.gz  in=324,289,060 out=76,089,085 elapsed=125.7s

  [9412/21087] intraday_17645.csv.gz  in=324,303,848 out=76,103,634 elapsed=125.7s

  [9413/21087] intraday_17648.csv.gz  in=324,316,128 out=76,115,914 elapsed=125.8s

  [9414/21087] intraday_17649.csv.gz  in=324,328,882 out=76,128,668 elapsed=125.8s

  [9415/21087] intraday_1765.csv.gz  in=324,341,121 out=76,128,668 elapsed=125.8s

  [9416/21087] intraday_17652.csv.gz  in=324,352,903 out=76,140,450 elapsed=125.8s

  [9417/21087] intraday_17650.csv.gz  in=324,364,924 out=76,152,471 elapsed=125.8s

  [9418/21087] intraday_17651.csv.gz  in=324,379,125 out=76,166,672 elapsed=125.8s

  [9419/21087] intraday_17653.csv.gz  in=324,389,784 out=76,177,331 elapsed=125.8s

  [9420/21087] intraday_17654.csv.gz  in=324,401,673 out=76,189,220 elapsed=125.9s

  [9421/21087] intraday_17655.csv.gz  in=324,414,244 out=76,201,791 elapsed=125.9s

  [9422/21087] intraday_17656.csv.gz  in=324,426,515 out=76,213,850 elapsed=125.9s

  [9423/21087] intraday_17657.csv.gz  in=324,440,259 out=76,227,594 elapsed=125.9s

  [9424/21087] intraday_17658.csv.gz  in=324,453,547 out=76,240,882 elapsed=125.9s

  [9425/21087] intraday_1766.csv.gz  in=324,466,480 out=76,240,882 elapsed=125.9s

  [9426/21087] intraday_17659.csv.gz  in=324,478,987 out=76,253,389 elapsed=125.9s

  [9427/21087] intraday_17661.csv.gz  in=324,488,800 out=76,263,202 elapsed=125.9s

  [9428/21087] intraday_17660.csv.gz  in=324,504,210 out=76,278,612 elapsed=125.9s

  [9429/21087] intraday_17662.csv.gz  in=324,516,384 out=76,290,786 elapsed=125.9s

  [9430/21087] intraday_17663.csv.gz  in=324,530,047 out=76,304,449 elapsed=125.9s

  [9431/21087] intraday_17665.csv.gz  in=324,541,235 out=76,315,637 elapsed=126.0s

  [9432/21087] intraday_17666.csv.gz  in=324,549,432 out=76,323,834 elapsed=126.0s

  [9433/21087] intraday_17664.csv.gz  in=324,559,670 out=76,334,072 elapsed=126.0s

  [9434/21087] intraday_17669.csv.gz  in=324,560,588 out=76,334,990 elapsed=126.0s

  [9435/21087] intraday_17667.csv.gz  in=324,570,811 out=76,345,213 elapsed=126.0s

  [9436/21087] intraday_17668.csv.gz  in=324,578,913 out=76,353,315 elapsed=126.0s

  [9437/21087] intraday_17670.csv.gz  in=324,579,248 out=76,353,650 elapsed=126.0s

  [9438/21087] intraday_17671.csv.gz  in=324,579,615 out=76,354,017 elapsed=126.0s

  [9439/21087] intraday_1767.csv.gz  in=324,590,403 out=76,354,017 elapsed=126.0s

  [9440/21087] intraday_17672.csv.gz  in=324,590,999 out=76,354,613 elapsed=126.0s

  [9441/21087] intraday_17673.csv.gz  in=324,591,508 out=76,355,122 elapsed=126.0s

  [9442/21087] intraday_17674.csv.gz  in=324,592,293 out=76,355,907 elapsed=126.0s

  [9443/21087] intraday_17675.csv.gz  in=324,592,822 out=76,356,436 elapsed=126.0s

  [9444/21087] intraday_17677.csv.gz  in=324,593,437 out=76,357,051 elapsed=126.0s

  [9445/21087] intraday_17678.csv.gz  in=324,593,795 out=76,357,409 elapsed=126.0s

  [9446/21087] intraday_17676.csv.gz  in=324,594,173 out=76,357,787 elapsed=126.0s

  [9447/21087] intraday_17679.csv.gz  in=324,594,544 out=76,358,158 elapsed=126.0s

  [9448/21087] intraday_17680.csv.gz  in=324,595,143 out=76,358,757 elapsed=126.0s

  [9449/21087] intraday_17682.csv.gz  in=324,595,511 out=76,359,125 elapsed=126.1s

  [9450/21087] intraday_17681.csv.gz  in=324,596,547 out=76,360,161 elapsed=126.1s

  [9451/21087] intraday_17683.csv.gz  in=324,596,994 out=76,360,608 elapsed=126.1s

  [9452/21087] intraday_17684.csv.gz  in=324,597,380 out=76,360,994 elapsed=126.1s

  [9453/21087] intraday_1768.csv.gz  in=324,610,695 out=76,360,994 elapsed=126.1s

  [9454/21087] intraday_17685.csv.gz  in=324,611,390 out=76,361,689 elapsed=126.1s

  [9455/21087] intraday_17686.csv.gz  in=324,611,997 out=76,362,296 elapsed=126.1s

  [9456/21087] intraday_17688.csv.gz  in=324,612,214 out=76,362,513 elapsed=126.1s

  [9457/21087] intraday_17687.csv.gz  in=324,612,596 out=76,362,895 elapsed=126.1s

  [9458/21087] intraday_17689.csv.gz  in=324,613,035 out=76,363,334 elapsed=126.1s

  [9459/21087] intraday_17690.csv.gz  in=324,613,225 out=76,363,524 elapsed=126.1s

  [9460/21087] intraday_17692.csv.gz  in=324,613,682 out=76,363,981 elapsed=126.1s

  [9461/21087] intraday_17691.csv.gz  in=324,613,987 out=76,364,286 elapsed=126.1s

  [9462/21087] intraday_1769.csv.gz  in=324,626,316 out=76,364,286 elapsed=126.1s

  [9463/21087] intraday_17693.csv.gz  in=324,626,409 out=76,364,379 elapsed=126.1s

  [9464/21087] intraday_17694.csv.gz  in=324,626,762 out=76,364,732 elapsed=126.1s

  [9465/21087] intraday_17695.csv.gz  in=324,627,212 out=76,365,182 elapsed=126.1s

  [9466/21087] intraday_17696.csv.gz  in=324,627,639 out=76,365,609 elapsed=126.1s

  [9467/21087] intraday_17697.csv.gz  in=324,628,549 out=76,366,519 elapsed=126.1s

  [9468/21087] intraday_17698.csv.gz  in=324,629,503 out=76,367,473 elapsed=126.2s

  [9469/21087] intraday_17699.csv.gz  in=324,630,216 out=76,368,186 elapsed=126.2s

  [9470/21087] intraday_17700.csv.gz  in=324,630,275 out=76,368,245 elapsed=126.2s

  [9471/21087] intraday_17701.csv.gz  in=324,630,686 out=76,368,656 elapsed=126.2s

  [9472/21087] intraday_17702.csv.gz  in=324,631,008 out=76,368,978 elapsed=126.2s

  [9473/21087] intraday_17703.csv.gz  in=324,631,202 out=76,369,172 elapsed=126.2s

  [9474/21087] intraday_17705.csv.gz  in=324,631,509 out=76,369,479 elapsed=126.2s

  [9475/21087] intraday_17704.csv.gz  in=324,631,735 out=76,369,705 elapsed=126.2s

  [9476/21087] intraday_1770.csv.gz  in=324,649,856 out=76,369,705 elapsed=126.2s

  [9477/21087] intraday_17706.csv.gz  in=324,650,049 out=76,369,898 elapsed=126.2s

  [9478/21087] intraday_17707.csv.gz  in=324,650,151 out=76,370,000 elapsed=126.2s

  [9479/21087] intraday_17709.csv.gz  in=324,650,346 out=76,370,195 elapsed=126.2s

  [9480/21087] intraday_17708.csv.gz  in=324,650,513 out=76,370,362 elapsed=126.2s

  [9481/21087] intraday_17710.csv.gz  in=324,650,681 out=76,370,530 elapsed=126.2s

  [9482/21087] intraday_17711.csv.gz  in=324,651,201 out=76,371,050 elapsed=126.2s

  [9483/21087] intraday_1771.csv.gz  in=324,663,613 out=76,371,050 elapsed=126.2s

  [9484/21087] intraday_17712.csv.gz  in=324,663,880 out=76,371,317 elapsed=126.2s

  [9485/21087] intraday_17713.csv.gz  in=324,664,183 out=76,371,620 elapsed=126.2s

  [9486/21087] intraday_17714.csv.gz  in=324,664,289 out=76,371,726 elapsed=126.2s

  [9487/21087] intraday_17716.csv.gz  in=324,664,447 out=76,371,884 elapsed=126.2s

  [9488/21087] intraday_17717.csv.gz  in=324,664,781 out=76,372,218 elapsed=126.2s

  [9489/21087] intraday_17718.csv.gz  in=324,665,149 out=76,372,586 elapsed=126.3s

  [9490/21087] intraday_17715.csv.gz  in=324,669,957 out=76,376,065 elapsed=126.3s

  [9491/21087] intraday_17720.csv.gz  in=324,670,421 out=76,376,529 elapsed=126.3s

  [9492/21087] intraday_17719.csv.gz  in=324,671,304 out=76,377,412 elapsed=126.3s

  [9493/21087] intraday_17721.csv.gz  in=324,672,385 out=76,378,493 elapsed=126.3s

  [9494/21087] intraday_1772.csv.gz  in=324,685,359 out=76,378,493 elapsed=126.3s

  [9495/21087] intraday_17722.csv.gz  in=324,686,173 out=76,379,307 elapsed=126.3s

  [9496/21087] intraday_17723.csv.gz  in=324,686,749 out=76,379,883 elapsed=126.3s

  [9497/21087] intraday_17724.csv.gz  in=324,687,177 out=76,380,247 elapsed=126.3s

  [9498/21087] intraday_17725.csv.gz  in=324,687,363 out=76,380,433 elapsed=126.3s

  [9499/21087] intraday_17726.csv.gz  in=324,687,774 out=76,380,844 elapsed=126.3s

  [9500/21087] intraday_17727.csv.gz  in=324,688,021 out=76,381,091 elapsed=126.3s

  [9501/21087] intraday_17729.csv.gz  in=324,688,190 out=76,381,260 elapsed=126.3s

  [9502/21087] intraday_17728.csv.gz  in=324,688,727 out=76,381,797 elapsed=126.3s

  [9503/21087] intraday_17730.csv.gz  in=324,688,884 out=76,381,954 elapsed=126.3s

  [9504/21087] intraday_17732.csv.gz  in=324,689,737 out=76,382,807 elapsed=126.3s

  [9505/21087] intraday_1773.csv.gz  in=324,701,886 out=76,382,807 elapsed=126.3s

  [9506/21087] intraday_17731.csv.gz  in=324,701,986 out=76,382,907 elapsed=126.3s

  [9507/21087] intraday_17733.csv.gz  in=324,702,996 out=76,383,917 elapsed=126.3s

  [9508/21087] intraday_17734.csv.gz  in=324,703,293 out=76,384,214 elapsed=126.4s

  [9509/21087] intraday_17735.csv.gz  in=324,703,513 out=76,384,434 elapsed=126.4s

  [9510/21087] intraday_17736.csv.gz  in=324,704,017 out=76,384,938 elapsed=126.4s

  [9511/21087] intraday_17737.csv.gz  in=324,704,279 out=76,385,200 elapsed=126.4s

  [9512/21087] intraday_17738.csv.gz  in=324,704,677 out=76,385,598 elapsed=126.4s

  [9513/21087] intraday_17739.csv.gz  in=324,705,267 out=76,386,188 elapsed=126.4s

  [9514/21087] intraday_17740.csv.gz  in=324,705,514 out=76,386,435 elapsed=126.4s

  [9515/21087] intraday_17741.csv.gz  in=324,705,802 out=76,386,723 elapsed=126.4s

  [9516/21087] intraday_17742.csv.gz  in=324,706,364 out=76,387,285 elapsed=126.4s

  [9517/21087] intraday_17743.csv.gz  in=324,706,476 out=76,387,397 elapsed=126.4s

  [9518/21087] intraday_1774.csv.gz  in=324,719,463 out=76,387,397 elapsed=126.4s

  [9519/21087] intraday_17744.csv.gz  in=324,719,809 out=76,387,743 elapsed=126.4s

  [9520/21087] intraday_17745.csv.gz  in=324,720,085 out=76,388,019 elapsed=126.4s

  [9521/21087] intraday_17746.csv.gz  in=324,720,455 out=76,388,389 elapsed=126.4s

  [9522/21087] intraday_17747.csv.gz  in=324,721,232 out=76,389,166 elapsed=126.4s

  [9523/21087] intraday_17748.csv.gz  in=324,721,288 out=76,389,222 elapsed=126.4s

  [9524/21087] intraday_17749.csv.gz  in=324,721,632 out=76,389,566 elapsed=126.4s

  [9525/21087] intraday_17751.csv.gz  in=324,722,875 out=76,390,809 elapsed=126.4s

  [9526/21087] intraday_17750.csv.gz  in=324,724,842 out=76,392,776 elapsed=126.4s

  [9527/21087] intraday_1775.csv.gz  in=324,735,199 out=76,392,776 elapsed=126.4s

  [9528/21087] intraday_17752.csv.gz  in=324,735,897 out=76,393,474 elapsed=126.4s

  [9529/21087] intraday_17753.csv.gz  in=324,736,493 out=76,394,070 elapsed=126.5s

  [9530/21087] intraday_17754.csv.gz  in=324,736,914 out=76,394,491 elapsed=126.5s

  [9531/21087] intraday_17755.csv.gz  in=324,737,266 out=76,394,843 elapsed=126.5s

  [9532/21087] intraday_17756.csv.gz  in=324,738,205 out=76,395,782 elapsed=126.5s

  [9533/21087] intraday_17757.csv.gz  in=324,738,388 out=76,395,965 elapsed=126.5s

  [9534/21087] intraday_17758.csv.gz  in=324,738,598 out=76,396,175 elapsed=126.5s

  [9535/21087] intraday_17759.csv.gz  in=324,739,185 out=76,396,762 elapsed=126.5s

  [9536/21087] intraday_17760.csv.gz  in=324,739,753 out=76,397,330 elapsed=126.5s

  [9537/21087] intraday_17761.csv.gz  in=324,739,955 out=76,397,532 elapsed=126.5s

  [9538/21087] intraday_17762.csv.gz  in=324,740,228 out=76,397,805 elapsed=126.5s

  [9539/21087] intraday_17763.csv.gz  in=324,740,487 out=76,398,064 elapsed=126.5s

  [9540/21087] intraday_17764.csv.gz  in=324,740,702 out=76,398,279 elapsed=126.5s

  [9541/21087] intraday_1776.csv.gz  in=324,757,515 out=76,398,279 elapsed=126.5s

  [9542/21087] intraday_17765.csv.gz  in=324,758,111 out=76,398,875 elapsed=126.5s

  [9543/21087] intraday_17766.csv.gz  in=324,758,394 out=76,399,158 elapsed=126.5s

  [9544/21087] intraday_17767.csv.gz  in=324,758,536 out=76,399,300 elapsed=126.5s

  [9545/21087] intraday_17768.csv.gz  in=324,758,763 out=76,399,527 elapsed=126.5s

  [9546/21087] intraday_17769.csv.gz  in=324,759,994 out=76,400,758 elapsed=126.5s

  [9547/21087] intraday_17770.csv.gz  in=324,760,987 out=76,401,751 elapsed=126.5s

  [9548/21087] intraday_17771.csv.gz  in=324,761,467 out=76,402,231 elapsed=126.5s

  [9549/21087] intraday_1777.csv.gz  in=324,775,408 out=76,402,231 elapsed=126.5s

  [9550/21087] intraday_17774.csv.gz  in=324,775,512 out=76,402,335 elapsed=126.5s

  [9551/21087] intraday_17772.csv.gz  in=324,775,827 out=76,402,650 elapsed=126.5s

  [9552/21087] intraday_17775.csv.gz  in=324,775,973 out=76,402,796 elapsed=126.5s

  [9553/21087] intraday_17773.csv.gz  in=324,776,697 out=76,403,520 elapsed=126.6s

  [9554/21087] intraday_17777.csv.gz  in=324,777,174 out=76,403,997 elapsed=126.6s

  [9555/21087] intraday_17776.csv.gz  in=324,777,549 out=76,404,372 elapsed=126.6s

  [9556/21087] intraday_17778.csv.gz  in=324,778,124 out=76,404,947 elapsed=126.6s

  [9557/21087] intraday_17779.csv.gz  in=324,778,765 out=76,405,588 elapsed=126.6s

  [9558/21087] intraday_17780.csv.gz  in=324,779,831 out=76,406,654 elapsed=126.6s

  [9559/21087] intraday_17781.csv.gz  in=324,780,776 out=76,407,599 elapsed=126.6s

  [9560/21087] intraday_17782.csv.gz  in=324,781,959 out=76,408,782 elapsed=126.6s

  [9561/21087] intraday_17784.csv.gz  in=324,782,458 out=76,409,281 elapsed=126.6s

  [9562/21087] intraday_17783.csv.gz  in=324,783,889 out=76,410,712 elapsed=126.6s

  [9563/21087] intraday_1778.csv.gz  in=324,799,309 out=76,410,712 elapsed=126.6s

  [9564/21087] intraday_17786.csv.gz  in=324,799,798 out=76,411,201 elapsed=126.6s

  [9565/21087] intraday_17785.csv.gz  in=324,801,005 out=76,412,408 elapsed=126.6s

  [9566/21087] intraday_17787.csv.gz  in=324,801,458 out=76,412,861 elapsed=126.6s

  [9567/21087] intraday_17788.csv.gz  in=324,801,577 out=76,412,980 elapsed=126.6s

  [9568/21087] intraday_17789.csv.gz  in=324,802,300 out=76,413,703 elapsed=126.6s

  [9569/21087] intraday_17790.csv.gz  in=324,802,360 out=76,413,763 elapsed=126.6s

  [9570/21087] intraday_17791.csv.gz  in=324,802,957 out=76,414,360 elapsed=126.6s

  [9571/21087] intraday_17792.csv.gz  in=324,803,278 out=76,414,681 elapsed=126.6s

  [9572/21087] intraday_17793.csv.gz  in=324,804,262 out=76,415,665 elapsed=126.6s

  [9573/21087] intraday_1779.csv.gz  in=324,824,142 out=76,415,665 elapsed=126.7s

  [9574/21087] intraday_17794.csv.gz  in=324,824,502 out=76,416,025 elapsed=126.7s

  [9575/21087] intraday_17795.csv.gz  in=324,824,951 out=76,416,474 elapsed=126.7s

  [9576/21087] intraday_17796.csv.gz  in=324,825,435 out=76,416,958 elapsed=126.7s

  [9577/21087] intraday_17797.csv.gz  in=324,826,390 out=76,417,913 elapsed=126.7s

  [9578/21087] intraday_17799.csv.gz  in=324,826,598 out=76,418,121 elapsed=126.7s

  [9579/21087] intraday_17798.csv.gz  in=324,826,922 out=76,418,445 elapsed=126.7s

  [9580/21087] intraday_17801.csv.gz  in=324,827,424 out=76,418,947 elapsed=126.7s

  [9581/21087] intraday_17800.csv.gz  in=324,827,618 out=76,419,124 elapsed=126.7s

  [9582/21087] intraday_17802.csv.gz  in=324,828,128 out=76,419,634 elapsed=126.7s

  [9583/21087] intraday_1780.csv.gz  in=324,841,997 out=76,419,634 elapsed=126.7s

  [9584/21087] intraday_17803.csv.gz  in=324,842,303 out=76,419,940 elapsed=126.7s

  [9585/21087] intraday_17804.csv.gz  in=324,842,657 out=76,420,294 elapsed=126.7s

  [9586/21087] intraday_17805.csv.gz  in=324,843,000 out=76,420,637 elapsed=126.7s

  [9587/21087] intraday_17806.csv.gz  in=324,843,265 out=76,420,902 elapsed=126.7s

  [9588/21087] intraday_17807.csv.gz  in=324,843,670 out=76,421,307 elapsed=126.7s

  [9589/21087] intraday_17808.csv.gz  in=324,844,207 out=76,421,844 elapsed=126.7s

  [9590/21087] intraday_17809.csv.gz  in=324,844,528 out=76,422,165 elapsed=126.7s

  [9591/21087] intraday_17810.csv.gz  in=324,844,773 out=76,422,410 elapsed=126.7s

  [9592/21087] intraday_1781.csv.gz  in=324,858,228 out=76,422,410 elapsed=126.7s

  [9593/21087] intraday_17811.csv.gz  in=324,873,849 out=76,438,031 elapsed=126.8s

  [9594/21087] intraday_17812.csv.gz  in=324,887,730 out=76,451,912 elapsed=126.8s

  [9595/21087] intraday_17814.csv.gz  in=324,899,059 out=76,463,241 elapsed=126.8s

  [9596/21087] intraday_17813.csv.gz  in=324,912,473 out=76,476,655 elapsed=126.8s

  [9597/21087] intraday_17815.csv.gz  in=324,925,290 out=76,489,472 elapsed=126.8s

  [9598/21087] intraday_17816.csv.gz  in=324,939,751 out=76,503,933 elapsed=126.8s

  [9599/21087] intraday_17818.csv.gz  in=324,950,634 out=76,514,816 elapsed=126.8s

  [9600/21087] intraday_17817.csv.gz  in=324,963,889 out=76,528,071 elapsed=126.8s

  [9601/21087] intraday_17819.csv.gz  in=324,977,950 out=76,542,132 elapsed=126.8s

  [9602/21087] intraday_1782.csv.gz  in=324,996,461 out=76,542,132 elapsed=126.9s

  [9603/21087] intraday_17820.csv.gz  in=325,010,671 out=76,556,342 elapsed=126.9s

  [9604/21087] intraday_17821.csv.gz  in=325,020,217 out=76,565,888 elapsed=126.9s

  [9605/21087] intraday_17822.csv.gz  in=325,032,311 out=76,577,982 elapsed=126.9s

  [9606/21087] intraday_17823.csv.gz  in=325,046,672 out=76,592,343 elapsed=126.9s

  [9607/21087] intraday_17824.csv.gz  in=325,058,717 out=76,604,388 elapsed=126.9s

  [9608/21087] intraday_17825.csv.gz  in=325,069,618 out=76,615,289 elapsed=126.9s

  [9609/21087] intraday_17827.csv.gz  in=325,084,007 out=76,629,678 elapsed=126.9s

  [9610/21087] intraday_17826.csv.gz  in=325,095,485 out=76,641,156 elapsed=127.0s

  [9611/21087] intraday_17828.csv.gz  in=325,109,050 out=76,654,721 elapsed=127.0s

  [9612/21087] intraday_17829.csv.gz  in=325,120,309 out=76,665,980 elapsed=127.0s

  [9613/21087] intraday_1783.csv.gz  in=325,133,523 out=76,665,980 elapsed=127.0s

  [9614/21087] intraday_17830.csv.gz  in=325,144,424 out=76,676,881 elapsed=127.0s

  [9615/21087] intraday_17831.csv.gz  in=325,156,829 out=76,689,286 elapsed=127.0s

  [9616/21087] intraday_17832.csv.gz  in=325,169,863 out=76,702,320 elapsed=127.0s

  [9617/21087] intraday_17833.csv.gz  in=325,182,409 out=76,714,866 elapsed=127.0s

  [9618/21087] intraday_17834.csv.gz  in=325,193,553 out=76,726,010 elapsed=127.0s

  [9619/21087] intraday_17835.csv.gz  in=325,206,133 out=76,738,590 elapsed=127.0s

  [9620/21087] intraday_17836.csv.gz  in=325,217,137 out=76,749,594 elapsed=127.1s

  [9621/21087] intraday_17838.csv.gz  in=325,228,230 out=76,760,687 elapsed=127.1s

  [9622/21087] intraday_17839.csv.gz  in=325,242,053 out=76,774,510 elapsed=127.1s

  [9623/21087] intraday_1784.csv.gz  in=325,258,392 out=76,774,510 elapsed=127.1s

  [9624/21087] intraday_17837.csv.gz  in=325,271,480 out=76,787,598 elapsed=127.1s

  [9625/21087] intraday_17840.csv.gz  in=325,285,828 out=76,801,946 elapsed=127.1s

  [9626/21087] intraday_17841.csv.gz  in=325,298,579 out=76,814,697 elapsed=127.1s

  [9627/21087] intraday_17842.csv.gz  in=325,310,302 out=76,826,420 elapsed=127.1s

  [9628/21087] intraday_17843.csv.gz  in=325,321,547 out=76,837,665 elapsed=127.1s

  [9629/21087] intraday_17844.csv.gz  in=325,334,449 out=76,850,567 elapsed=127.2s

  [9630/21087] intraday_17847.csv.gz  in=325,348,675 out=76,864,161 elapsed=127.2s

  [9631/21087] intraday_17846.csv.gz  in=325,361,206 out=76,876,692 elapsed=127.2s

  [9632/21087] intraday_17845.csv.gz  in=325,396,082 out=76,905,883 elapsed=127.2s

  [9633/21087] intraday_17848.csv.gz  in=325,407,093 out=76,916,894 elapsed=127.2s

  [9634/21087] intraday_17849.csv.gz  in=325,417,803 out=76,927,604 elapsed=127.2s

  [9635/21087] intraday_1785.csv.gz  in=325,431,099 out=76,927,604 elapsed=127.2s

  [9636/21087] intraday_17850.csv.gz  in=325,441,867 out=76,938,372 elapsed=127.2s

  [9637/21087] intraday_17851.csv.gz  in=325,454,466 out=76,950,971 elapsed=127.3s

  [9638/21087] intraday_17852.csv.gz  in=325,465,770 out=76,962,275 elapsed=127.3s

  [9639/21087] intraday_17853.csv.gz  in=325,478,886 out=76,975,391 elapsed=127.3s

  [9640/21087] intraday_17854.csv.gz  in=325,493,953 out=76,990,458 elapsed=127.3s

  [9641/21087] intraday_17855.csv.gz  in=325,506,138 out=77,002,643 elapsed=127.3s

  [9642/21087] intraday_17857.csv.gz  in=325,518,066 out=77,014,571 elapsed=127.3s

  [9643/21087] intraday_17856.csv.gz  in=325,530,272 out=77,026,777 elapsed=127.3s

  [9644/21087] intraday_17858.csv.gz  in=325,542,516 out=77,039,021 elapsed=127.3s

  [9645/21087] intraday_1786.csv.gz  in=325,554,636 out=77,039,021 elapsed=127.3s

  [9646/21087] intraday_17859.csv.gz  in=325,566,915 out=77,051,300 elapsed=127.3s

  [9647/21087] intraday_17860.csv.gz  in=325,580,202 out=77,064,587 elapsed=127.3s

  [9648/21087] intraday_17861.csv.gz  in=325,590,966 out=77,075,351 elapsed=127.4s

  [9649/21087] intraday_17862.csv.gz  in=325,605,661 out=77,090,046 elapsed=127.4s

  [9650/21087] intraday_17863.csv.gz  in=325,620,087 out=77,104,472 elapsed=127.4s

  [9651/21087] intraday_17864.csv.gz  in=325,631,922 out=77,116,307 elapsed=127.4s

  [9652/21087] intraday_17865.csv.gz  in=325,647,756 out=77,132,141 elapsed=127.4s

  [9653/21087] intraday_17868.csv.gz  in=325,659,805 out=77,144,190 elapsed=127.4s

  [9654/21087] intraday_17866.csv.gz  in=325,672,100 out=77,156,485 elapsed=127.4s

  [9655/21087] intraday_17867.csv.gz  in=325,682,760 out=77,167,145 elapsed=127.4s

  [9656/21087] intraday_17869.csv.gz  in=325,695,439 out=77,179,824 elapsed=127.4s

  [9657/21087] intraday_17870.csv.gz  in=325,706,275 out=77,190,660 elapsed=127.5s

  [9658/21087] intraday_1787.csv.gz  in=325,719,352 out=77,190,660 elapsed=127.5s

  [9659/21087] intraday_17871.csv.gz  in=325,732,652 out=77,203,960 elapsed=127.5s

  [9660/21087] intraday_17872.csv.gz  in=325,743,506 out=77,214,814 elapsed=127.5s

  [9661/21087] intraday_17873.csv.gz  in=325,754,723 out=77,226,031 elapsed=127.5s

  [9662/21087] intraday_17874.csv.gz  in=325,766,108 out=77,237,416 elapsed=127.5s

  [9663/21087] intraday_17875.csv.gz  in=325,780,273 out=77,251,581 elapsed=127.5s

  [9664/21087] intraday_17877.csv.gz  in=325,794,819 out=77,266,127 elapsed=127.5s

  [9665/21087] intraday_17876.csv.gz  in=325,807,537 out=77,278,845 elapsed=127.6s

  [9666/21087] intraday_17878.csv.gz  in=325,821,015 out=77,292,323 elapsed=127.6s

  [9667/21087] intraday_1788.csv.gz  in=325,831,015 out=77,292,323 elapsed=127.6s

  [9668/21087] intraday_17879.csv.gz  in=325,841,557 out=77,302,865 elapsed=127.6s

  [9669/21087] intraday_17880.csv.gz  in=325,850,744 out=77,312,052 elapsed=127.6s

  [9670/21087] intraday_17881.csv.gz  in=325,865,957 out=77,327,265 elapsed=127.6s

  [9671/21087] intraday_17883.csv.gz  in=325,879,095 out=77,340,403 elapsed=127.6s

  [9672/21087] intraday_17882.csv.gz  in=325,891,288 out=77,352,596 elapsed=127.6s

  [9673/21087] intraday_17884.csv.gz  in=325,901,604 out=77,362,912 elapsed=127.6s

  [9674/21087] intraday_17886.csv.gz  in=325,911,693 out=77,373,001 elapsed=127.6s

  [9675/21087] intraday_17885.csv.gz  in=325,923,101 out=77,384,409 elapsed=127.7s

  [9676/21087] intraday_17887.csv.gz  in=325,936,929 out=77,398,237 elapsed=127.7s

  [9677/21087] intraday_17888.csv.gz  in=325,949,402 out=77,410,710 elapsed=127.7s

  [9678/21087] intraday_17889.csv.gz  in=325,963,901 out=77,425,209 elapsed=127.7s

  [9679/21087] intraday_1789.csv.gz  in=325,976,895 out=77,425,209 elapsed=127.7s

  [9680/21087] intraday_17890.csv.gz  in=325,988,112 out=77,436,426 elapsed=127.7s

  [9681/21087] intraday_17891.csv.gz  in=325,999,436 out=77,447,750 elapsed=127.7s

  [9682/21087] intraday_17892.csv.gz  in=326,012,329 out=77,460,643 elapsed=127.7s

  [9683/21087] intraday_17893.csv.gz  in=326,029,485 out=77,477,799 elapsed=127.7s

  [9684/21087] intraday_17894.csv.gz  in=326,044,161 out=77,492,475 elapsed=127.7s

  [9685/21087] intraday_17895.csv.gz  in=326,058,861 out=77,507,175 elapsed=127.8s

  [9686/21087] intraday_17897.csv.gz  in=326,073,672 out=77,521,986 elapsed=127.8s

  [9687/21087] intraday_17896.csv.gz  in=326,085,749 out=77,534,063 elapsed=127.8s

  [9688/21087] intraday_17898.csv.gz  in=326,096,799 out=77,545,113 elapsed=127.8s

  [9689/21087] intraday_17899.csv.gz  in=326,111,409 out=77,559,723 elapsed=127.8s

  [9690/21087] intraday_1790.csv.gz  in=326,122,134 out=77,559,723 elapsed=127.8s

  [9691/21087] intraday_17900.csv.gz  in=326,132,722 out=77,570,311 elapsed=127.8s

  [9692/21087] intraday_17902.csv.gz  in=326,145,896 out=77,583,485 elapsed=127.8s

  [9693/21087] intraday_17901.csv.gz  in=326,157,466 out=77,595,055 elapsed=127.8s

  [9694/21087] intraday_17904.csv.gz  in=326,171,264 out=77,608,853 elapsed=127.9s

  [9695/21087] intraday_17903.csv.gz  in=326,183,171 out=77,620,760 elapsed=127.9s

  [9696/21087] intraday_17905.csv.gz  in=326,194,160 out=77,631,749 elapsed=127.9s

  [9697/21087] intraday_17906.csv.gz  in=326,207,309 out=77,644,898 elapsed=127.9s

  [9698/21087] intraday_17907.csv.gz  in=326,218,497 out=77,656,086 elapsed=127.9s

  [9699/21087] intraday_17908.csv.gz  in=326,230,774 out=77,668,363 elapsed=127.9s

  [9700/21087] intraday_1791.csv.gz  in=326,242,380 out=77,668,363 elapsed=127.9s

  [9701/21087] intraday_17909.csv.gz  in=326,254,226 out=77,680,209 elapsed=127.9s

  [9702/21087] intraday_17910.csv.gz  in=326,265,653 out=77,691,636 elapsed=127.9s

  [9703/21087] intraday_17911.csv.gz  in=326,278,320 out=77,704,303 elapsed=128.0s

  [9704/21087] intraday_17912.csv.gz  in=326,295,334 out=77,719,951 elapsed=128.0s

  [9705/21087] intraday_17913.csv.gz  in=326,308,279 out=77,732,896 elapsed=128.0s

  [9706/21087] intraday_17914.csv.gz  in=326,320,170 out=77,744,787 elapsed=128.0s

  [9707/21087] intraday_17915.csv.gz  in=326,332,354 out=77,756,971 elapsed=128.0s

  [9708/21087] intraday_17916.csv.gz  in=326,345,103 out=77,769,720 elapsed=128.0s

  [9709/21087] intraday_17917.csv.gz  in=326,362,253 out=77,785,234 elapsed=128.0s

  [9710/21087] intraday_17918.csv.gz  in=326,375,856 out=77,798,837 elapsed=128.0s

  [9711/21087] intraday_1792.csv.gz  in=326,383,409 out=77,798,837 elapsed=128.0s

  [9712/21087] intraday_17919.csv.gz  in=326,396,953 out=77,812,381 elapsed=128.0s

  [9713/21087] intraday_17921.csv.gz  in=326,408,227 out=77,823,655 elapsed=128.1s

  [9714/21087] intraday_17922.csv.gz  in=326,422,963 out=77,838,391 elapsed=128.1s

  [9715/21087] intraday_17920.csv.gz  in=326,439,556 out=77,854,984 elapsed=128.1s

  [9716/21087] intraday_17923.csv.gz  in=326,452,897 out=77,868,325 elapsed=128.1s

  [9717/21087] intraday_17924.csv.gz  in=326,468,768 out=77,884,196 elapsed=128.1s

  [9718/21087] intraday_17925.csv.gz  in=326,483,972 out=77,899,400 elapsed=128.1s

  [9719/21087] intraday_17926.csv.gz  in=326,502,681 out=77,918,109 elapsed=128.1s

  [9720/21087] intraday_17927.csv.gz  in=326,515,568 out=77,930,996 elapsed=128.1s

  [9721/21087] intraday_17928.csv.gz  in=326,531,849 out=77,947,277 elapsed=128.1s

  [9722/21087] intraday_17929.csv.gz  in=326,543,748 out=77,959,176 elapsed=128.2s

  [9723/21087] intraday_1793.csv.gz  in=326,554,480 out=77,959,176 elapsed=128.2s

  [9724/21087] intraday_17931.csv.gz  in=326,564,444 out=77,969,140 elapsed=128.2s

  [9725/21087] intraday_17930.csv.gz  in=326,577,170 out=77,981,866 elapsed=128.2s

  [9726/21087] intraday_17933.csv.gz  in=326,587,791 out=77,992,487 elapsed=128.2s

  [9727/21087] intraday_17932.csv.gz  in=326,601,211 out=78,005,907 elapsed=128.2s

  [9728/21087] intraday_17934.csv.gz  in=326,614,459 out=78,019,155 elapsed=128.2s

  [9729/21087] intraday_17935.csv.gz  in=326,626,443 out=78,031,139 elapsed=128.2s

  [9730/21087] intraday_17937.csv.gz  in=326,637,932 out=78,042,628 elapsed=128.3s

  [9731/21087] intraday_17938.csv.gz  in=326,649,666 out=78,054,362 elapsed=128.3s

  [9732/21087] intraday_17936.csv.gz  in=326,665,230 out=78,069,926 elapsed=128.3s

  [9733/21087] intraday_17939.csv.gz  in=326,677,329 out=78,082,025 elapsed=128.3s

  [9734/21087] intraday_1794.csv.gz  in=326,683,713 out=78,082,025 elapsed=128.3s

  [9735/21087] intraday_17940.csv.gz  in=326,697,686 out=78,095,998 elapsed=128.3s

  [9736/21087] intraday_17941.csv.gz  in=326,708,885 out=78,107,197 elapsed=128.3s

  [9737/21087] intraday_17942.csv.gz  in=326,722,725 out=78,121,037 elapsed=128.3s

  [9738/21087] intraday_17943.csv.gz  in=326,736,153 out=78,134,465 elapsed=128.3s

  [9739/21087] intraday_17944.csv.gz  in=326,749,122 out=78,147,434 elapsed=128.4s

  [9740/21087] intraday_17945.csv.gz  in=326,765,095 out=78,163,407 elapsed=128.4s

  [9741/21087] intraday_17946.csv.gz  in=326,776,522 out=78,174,834 elapsed=128.4s

  [9742/21087] intraday_17947.csv.gz  in=326,788,600 out=78,186,912 elapsed=128.4s

  [9743/21087] intraday_17948.csv.gz  in=326,801,044 out=78,199,356 elapsed=128.4s

  [9744/21087] intraday_17949.csv.gz  in=326,811,453 out=78,209,765 elapsed=128.4s

  [9745/21087] intraday_1795.csv.gz  in=326,826,319 out=78,209,765 elapsed=128.4s

  [9746/21087] intraday_17950.csv.gz  in=326,838,937 out=78,222,383 elapsed=128.4s

  [9747/21087] intraday_17951.csv.gz  in=326,847,474 out=78,230,920 elapsed=128.4s

  [9748/21087] intraday_17953.csv.gz  in=326,855,558 out=78,239,004 elapsed=128.4s

  [9749/21087] intraday_17952.csv.gz  in=326,866,610 out=78,250,056 elapsed=128.4s

  [9750/21087] intraday_17954.csv.gz  in=326,882,680 out=78,266,126 elapsed=128.4s

  [9751/21087] intraday_17955.csv.gz  in=326,896,108 out=78,279,554 elapsed=128.5s

  [9752/21087] intraday_17956.csv.gz  in=326,908,879 out=78,292,325 elapsed=128.5s

  [9753/21087] intraday_17957.csv.gz  in=326,919,017 out=78,302,463 elapsed=128.5s

  [9754/21087] intraday_17958.csv.gz  in=326,932,387 out=78,315,833 elapsed=128.5s

  [9755/21087] intraday_1796.csv.gz  in=326,945,628 out=78,315,833 elapsed=128.5s

  [9756/21087] intraday_17959.csv.gz  in=326,959,560 out=78,329,765 elapsed=128.5s

  [9757/21087] intraday_17961.csv.gz  in=326,970,731 out=78,340,936 elapsed=128.5s

  [9758/21087] intraday_17963.csv.gz  in=326,983,818 out=78,354,023 elapsed=128.6s

  [9759/21087] intraday_17960.csv.gz  in=326,997,290 out=78,367,495 elapsed=128.6s

  [9760/21087] intraday_17962.csv.gz  in=327,011,315 out=78,381,520 elapsed=128.6s

  [9761/21087] intraday_17964.csv.gz  in=327,021,697 out=78,391,902 elapsed=128.6s

  [9762/21087] intraday_17967.csv.gz  in=327,032,757 out=78,402,962 elapsed=128.6s

  [9763/21087] intraday_17965.csv.gz  in=327,044,754 out=78,414,959 elapsed=128.6s

  [9764/21087] intraday_17968.csv.gz  in=327,055,896 out=78,426,101 elapsed=128.6s

  [9765/21087] intraday_17966.csv.gz  in=327,071,077 out=78,441,282 elapsed=128.6s

  [9766/21087] intraday_1797.csv.gz  in=327,083,256 out=78,441,282 elapsed=128.7s

  [9767/21087] intraday_17971.csv.gz  in=327,096,258 out=78,454,284 elapsed=128.7s

  [9768/21087] intraday_17969.csv.gz  in=327,107,170 out=78,465,196 elapsed=128.7s

  [9769/21087] intraday_17970.csv.gz  in=327,122,672 out=78,480,698 elapsed=128.7s

  [9770/21087] intraday_17972.csv.gz  in=327,133,741 out=78,491,767 elapsed=128.7s

  [9771/21087] intraday_17973.csv.gz  in=327,144,315 out=78,502,341 elapsed=128.7s

  [9772/21087] intraday_17974.csv.gz  in=327,157,011 out=78,515,037 elapsed=128.7s

  [9773/21087] intraday_17975.csv.gz  in=327,170,286 out=78,528,312 elapsed=128.7s

  [9774/21087] intraday_17976.csv.gz  in=327,183,625 out=78,541,651 elapsed=128.7s

  [9775/21087] intraday_17977.csv.gz  in=327,195,129 out=78,553,155 elapsed=128.7s

  [9776/21087] intraday_1798.csv.gz  in=327,206,528 out=78,553,155 elapsed=128.8s

  [9777/21087] intraday_17979.csv.gz  in=327,217,696 out=78,564,323 elapsed=128.8s

  [9778/21087] intraday_17978.csv.gz  in=327,229,405 out=78,576,032 elapsed=128.8s

  [9779/21087] intraday_17980.csv.gz  in=327,241,526 out=78,588,153 elapsed=128.8s

  [9780/21087] intraday_17981.csv.gz  in=327,252,510 out=78,599,137 elapsed=128.8s

  [9781/21087] intraday_17982.csv.gz  in=327,266,668 out=78,613,295 elapsed=128.8s

  [9782/21087] intraday_17983.csv.gz  in=327,280,324 out=78,626,951 elapsed=128.8s

  [9783/21087] intraday_17984.csv.gz  in=327,292,119 out=78,638,746 elapsed=128.8s

  [9784/21087] intraday_17985.csv.gz  in=327,304,126 out=78,650,753 elapsed=128.8s

  [9785/21087] intraday_17986.csv.gz  in=327,315,920 out=78,662,547 elapsed=128.8s

  [9786/21087] intraday_17987.csv.gz  in=327,329,094 out=78,675,721 elapsed=128.8s

  [9787/21087] intraday_17988.csv.gz  in=327,342,760 out=78,689,387 elapsed=128.9s

  [9788/21087] intraday_17989.csv.gz  in=327,356,014 out=78,702,641 elapsed=128.9s

  [9789/21087] intraday_1799.csv.gz  in=327,368,876 out=78,702,641 elapsed=128.9s

  [9790/21087] intraday_17990.csv.gz  in=327,379,810 out=78,713,575 elapsed=128.9s

  [9791/21087] intraday_17991.csv.gz  in=327,391,426 out=78,725,191 elapsed=128.9s

  [9792/21087] intraday_17992.csv.gz  in=327,401,680 out=78,735,445 elapsed=128.9s

  [9793/21087] intraday_17993.csv.gz  in=327,412,838 out=78,746,603 elapsed=128.9s

  [9794/21087] intraday_17994.csv.gz  in=327,425,642 out=78,759,407 elapsed=128.9s

  [9795/21087] intraday_17995.csv.gz  in=327,437,506 out=78,771,271 elapsed=128.9s

  [9796/21087] intraday_17996.csv.gz  in=327,451,852 out=78,785,617 elapsed=129.0s

  [9797/21087] intraday_17997.csv.gz  in=327,465,690 out=78,799,455 elapsed=129.0s

  [9798/21087] intraday_17999.csv.gz  in=327,477,267 out=78,811,032 elapsed=129.0s

  [9799/21087] intraday_17998.csv.gz  in=327,489,387 out=78,823,152 elapsed=129.0s

  [9800/21087] intraday_1800.csv.gz  in=327,504,000 out=78,823,152 elapsed=129.0s

  [9801/21087] intraday_18000.csv.gz  in=327,516,565 out=78,835,717 elapsed=129.0s

  [9802/21087] intraday_18001.csv.gz  in=327,527,680 out=78,846,832 elapsed=129.0s

  [9803/21087] intraday_18002.csv.gz  in=327,540,441 out=78,859,593 elapsed=129.0s

  [9804/21087] intraday_18003.csv.gz  in=327,552,074 out=78,871,226 elapsed=129.0s

  [9805/21087] intraday_18004.csv.gz  in=327,562,943 out=78,882,095 elapsed=129.0s

  [9806/21087] intraday_18005.csv.gz  in=327,575,304 out=78,894,456 elapsed=129.1s

  [9807/21087] intraday_18006.csv.gz  in=327,589,488 out=78,908,640 elapsed=129.1s

  [9808/21087] intraday_18007.csv.gz  in=327,602,549 out=78,921,701 elapsed=129.1s

  [9809/21087] intraday_18008.csv.gz  in=327,615,705 out=78,934,857 elapsed=129.1s

  [9810/21087] intraday_1801.csv.gz  in=327,627,998 out=78,934,857 elapsed=129.1s

  [9811/21087] intraday_18009.csv.gz  in=327,639,234 out=78,946,093 elapsed=129.1s

  [9812/21087] intraday_18010.csv.gz  in=327,650,797 out=78,957,656 elapsed=129.1s

  [9813/21087] intraday_18011.csv.gz  in=327,663,584 out=78,970,443 elapsed=129.1s

  [9814/21087] intraday_18012.csv.gz  in=327,675,869 out=78,982,728 elapsed=129.1s

  [9815/21087] intraday_18013.csv.gz  in=327,687,141 out=78,994,000 elapsed=129.1s

  [9816/21087] intraday_18014.csv.gz  in=327,698,361 out=79,005,220 elapsed=129.1s

  [9817/21087] intraday_18016.csv.gz  in=327,708,800 out=79,015,659 elapsed=129.2s

  [9818/21087] intraday_18015.csv.gz  in=327,721,201 out=79,028,060 elapsed=129.2s

  [9819/21087] intraday_18017.csv.gz  in=327,733,996 out=79,040,855 elapsed=129.2s

  [9820/21087] intraday_18018.csv.gz  in=327,747,780 out=79,054,639 elapsed=129.2s

  [9821/21087] intraday_18019.csv.gz  in=327,760,459 out=79,067,318 elapsed=129.2s

  [9822/21087] intraday_1802.csv.gz  in=327,772,640 out=79,067,318 elapsed=129.2s

  [9823/21087] intraday_18021.csv.gz  in=327,785,751 out=79,080,429 elapsed=129.2s

  [9824/21087] intraday_18020.csv.gz  in=327,799,877 out=79,094,555 elapsed=129.2s

  [9825/21087] intraday_18022.csv.gz  in=327,809,604 out=79,104,282 elapsed=129.2s

  [9826/21087] intraday_18023.csv.gz  in=327,821,749 out=79,116,427 elapsed=129.2s

  [9827/21087] intraday_18025.csv.gz  in=327,833,459 out=79,128,137 elapsed=129.3s

  [9828/21087] intraday_18027.csv.gz  in=327,844,707 out=79,139,385 elapsed=129.3s

  [9829/21087] intraday_18026.csv.gz  in=327,856,100 out=79,150,778 elapsed=129.3s

  [9830/21087] intraday_18024.csv.gz  in=327,872,839 out=79,167,517 elapsed=129.3s

  [9831/21087] intraday_18028.csv.gz  in=327,881,920 out=79,176,598 elapsed=129.3s

  [9832/21087] intraday_1803.csv.gz  in=327,895,521 out=79,176,598 elapsed=129.3s

  [9833/21087] intraday_18029.csv.gz  in=327,907,769 out=79,188,846 elapsed=129.3s

  [9834/21087] intraday_18030.csv.gz  in=327,922,236 out=79,203,313 elapsed=129.3s

  [9835/21087] intraday_18031.csv.gz  in=327,934,393 out=79,215,470 elapsed=129.4s

  [9836/21087] intraday_18032.csv.gz  in=327,947,950 out=79,229,027 elapsed=129.4s

  [9837/21087] intraday_18033.csv.gz  in=327,958,366 out=79,239,443 elapsed=129.4s

  [9838/21087] intraday_18034.csv.gz  in=327,969,681 out=79,250,758 elapsed=129.4s

  [9839/21087] intraday_18035.csv.gz  in=327,984,390 out=79,265,467 elapsed=129.4s

  [9840/21087] intraday_18036.csv.gz  in=328,002,342 out=79,283,419 elapsed=129.4s

  [9841/21087] intraday_18037.csv.gz  in=328,016,298 out=79,297,375 elapsed=129.4s

  [9842/21087] intraday_18038.csv.gz  in=328,029,769 out=79,310,846 elapsed=129.4s

  [9843/21087] intraday_1804.csv.gz  in=328,044,118 out=79,310,846 elapsed=129.4s

  [9844/21087] intraday_18039.csv.gz  in=328,057,464 out=79,324,192 elapsed=129.4s

  [9845/21087] intraday_18040.csv.gz  in=328,069,710 out=79,336,438 elapsed=129.5s

  [9846/21087] intraday_18041.csv.gz  in=328,083,407 out=79,350,135 elapsed=129.5s

  [9847/21087] intraday_18042.csv.gz  in=328,096,301 out=79,363,029 elapsed=129.5s

  [9848/21087] intraday_18043.csv.gz  in=328,106,723 out=79,373,451 elapsed=129.5s

  [9849/21087] intraday_18044.csv.gz  in=328,119,865 out=79,386,593 elapsed=129.5s

  [9850/21087] intraday_18045.csv.gz  in=328,133,140 out=79,399,868 elapsed=129.5s

  [9851/21087] intraday_18046.csv.gz  in=328,143,905 out=79,410,633 elapsed=129.5s

  [9852/21087] intraday_18047.csv.gz  in=328,156,525 out=79,423,253 elapsed=129.5s

  [9853/21087] intraday_18049.csv.gz  in=328,169,482 out=79,436,210 elapsed=129.5s

  [9854/21087] intraday_1805.csv.gz  in=328,178,399 out=79,436,210 elapsed=129.5s

  [9855/21087] intraday_18048.csv.gz  in=328,190,658 out=79,448,469 elapsed=129.5s

  [9856/21087] intraday_18050.csv.gz  in=328,201,722 out=79,459,533 elapsed=129.5s

  [9857/21087] intraday_18052.csv.gz  in=328,213,623 out=79,471,434 elapsed=129.6s

  [9858/21087] intraday_18051.csv.gz  in=328,224,616 out=79,482,427 elapsed=129.6s

  [9859/21087] intraday_18053.csv.gz  in=328,236,641 out=79,494,452 elapsed=129.6s

  [9860/21087] intraday_18054.csv.gz  in=328,248,304 out=79,506,115 elapsed=129.6s

  [9861/21087] intraday_18056.csv.gz  in=328,259,995 out=79,517,806 elapsed=129.7s

  [9862/21087] intraday_18057.csv.gz  in=328,272,228 out=79,530,039 elapsed=129.7s

  [9863/21087] intraday_18055.csv.gz  in=328,285,979 out=79,543,790 elapsed=129.7s

  [9864/21087] intraday_18058.csv.gz  in=328,299,401 out=79,557,212 elapsed=129.7s

  [9865/21087] intraday_1806.csv.gz  in=328,311,542 out=79,557,212 elapsed=129.7s

  [9866/21087] intraday_18061.csv.gz  in=328,324,757 out=79,570,427 elapsed=129.7s

  [9867/21087] intraday_18060.csv.gz  in=328,336,712 out=79,582,382 elapsed=129.7s

  [9868/21087] intraday_18059.csv.gz  in=328,346,636 out=79,592,306 elapsed=129.7s

  [9869/21087] intraday_18062.csv.gz  in=328,361,616 out=79,607,286 elapsed=129.7s

  [9870/21087] intraday_18063.csv.gz  in=328,374,884 out=79,620,554 elapsed=129.8s

  [9871/21087] intraday_18064.csv.gz  in=328,388,975 out=79,634,645 elapsed=129.8s

  [9872/21087] intraday_18065.csv.gz  in=328,401,716 out=79,647,386 elapsed=129.8s

  [9873/21087] intraday_18066.csv.gz  in=328,416,476 out=79,662,146 elapsed=129.8s

  [9874/21087] intraday_18067.csv.gz  in=328,430,381 out=79,676,051 elapsed=129.8s

  [9875/21087] intraday_1807.csv.gz  in=328,443,595 out=79,676,051 elapsed=129.8s

  [9876/21087] intraday_18069.csv.gz  in=328,457,594 out=79,690,050 elapsed=129.8s

  [9877/21087] intraday_18068.csv.gz  in=328,474,947 out=79,707,403 elapsed=129.8s

  [9878/21087] intraday_18070.csv.gz  in=328,491,564 out=79,724,020 elapsed=129.8s

  [9879/21087] intraday_18071.csv.gz  in=328,503,940 out=79,736,396 elapsed=129.8s

  [9880/21087] intraday_18072.csv.gz  in=328,517,243 out=79,749,699 elapsed=129.8s

  [9881/21087] intraday_18073.csv.gz  in=328,529,265 out=79,761,721 elapsed=129.9s

  [9882/21087] intraday_18074.csv.gz  in=328,541,709 out=79,774,165 elapsed=129.9s

  [9883/21087] intraday_18075.csv.gz  in=328,552,545 out=79,785,001 elapsed=129.9s

  [9884/21087] intraday_18077.csv.gz  in=328,564,226 out=79,796,682 elapsed=129.9s

  [9885/21087] intraday_18076.csv.gz  in=328,576,954 out=79,809,410 elapsed=129.9s

  [9886/21087] intraday_18078.csv.gz  in=328,592,201 out=79,824,657 elapsed=129.9s

  [9887/21087] intraday_18079.csv.gz  in=328,602,937 out=79,835,393 elapsed=129.9s

  [9888/21087] intraday_1808.csv.gz  in=328,613,445 out=79,835,393 elapsed=129.9s

  [9889/21087] intraday_18080.csv.gz  in=328,626,646 out=79,848,594 elapsed=130.0s

  [9890/21087] intraday_18082.csv.gz  in=328,639,708 out=79,861,656 elapsed=130.0s

  [9891/21087] intraday_18081.csv.gz  in=328,651,694 out=79,873,642 elapsed=130.0s

  [9892/21087] intraday_18083.csv.gz  in=328,663,689 out=79,885,637 elapsed=130.0s

  [9893/21087] intraday_18084.csv.gz  in=328,676,495 out=79,898,443 elapsed=130.0s

  [9894/21087] intraday_18085.csv.gz  in=328,689,499 out=79,911,447 elapsed=130.0s

  [9895/21087] intraday_18086.csv.gz  in=328,703,578 out=79,925,526 elapsed=130.0s

  [9896/21087] intraday_18087.csv.gz  in=328,718,355 out=79,940,303 elapsed=130.0s

  [9897/21087] intraday_18088.csv.gz  in=328,730,671 out=79,952,619 elapsed=130.0s

  [9898/21087] intraday_1809.csv.gz  in=328,740,886 out=79,952,619 elapsed=130.1s

  [9899/21087] intraday_18089.csv.gz  in=328,752,322 out=79,964,055 elapsed=130.1s

  [9900/21087] intraday_18091.csv.gz  in=328,762,475 out=79,974,208 elapsed=130.1s

  [9901/21087] intraday_18090.csv.gz  in=328,775,208 out=79,986,941 elapsed=130.1s

  [9902/21087] intraday_18093.csv.gz  in=328,785,650 out=79,997,383 elapsed=130.1s

  [9903/21087] intraday_18092.csv.gz  in=328,799,393 out=80,011,126 elapsed=130.1s

  [9904/21087] intraday_18094.csv.gz  in=328,808,749 out=80,020,482 elapsed=130.1s

  [9905/21087] intraday_18095.csv.gz  in=328,819,674 out=80,031,407 elapsed=130.1s

  [9906/21087] intraday_18096.csv.gz  in=328,835,012 out=80,046,745 elapsed=130.1s

  [9907/21087] intraday_18097.csv.gz  in=328,849,198 out=80,060,931 elapsed=130.2s

  [9908/21087] intraday_1810.csv.gz  in=328,861,482 out=80,060,931 elapsed=130.2s

  [9909/21087] intraday_18099.csv.gz  in=328,871,923 out=80,071,372 elapsed=130.2s

  [9910/21087] intraday_18098.csv.gz  in=328,884,690 out=80,084,139 elapsed=130.2s

  [9911/21087] intraday_18100.csv.gz  in=328,897,053 out=80,096,502 elapsed=130.2s

  [9912/21087] intraday_18103.csv.gz  in=328,908,149 out=80,107,598 elapsed=130.2s

  [9913/21087] intraday_18101.csv.gz  in=328,922,789 out=80,122,238 elapsed=130.2s

  [9914/21087] intraday_18104.csv.gz  in=328,936,845 out=80,136,294 elapsed=130.2s

  [9915/21087] intraday_18102.csv.gz  in=328,949,646 out=80,149,095 elapsed=130.2s

  [9916/21087] intraday_18106.csv.gz  in=328,959,548 out=80,158,997 elapsed=130.3s

  [9917/21087] intraday_18105.csv.gz  in=328,972,062 out=80,171,511 elapsed=130.3s

  [9918/21087] intraday_18107.csv.gz  in=328,984,215 out=80,183,664 elapsed=130.3s

  [9919/21087] intraday_18108.csv.gz  in=328,998,544 out=80,197,993 elapsed=130.3s

  [9920/21087] intraday_1811.csv.gz  in=329,011,048 out=80,197,993 elapsed=130.3s

  [9921/21087] intraday_18109.csv.gz  in=329,023,452 out=80,210,397 elapsed=130.3s

  [9922/21087] intraday_18110.csv.gz  in=329,033,205 out=80,220,150 elapsed=130.3s

  [9923/21087] intraday_18111.csv.gz  in=329,045,109 out=80,232,054 elapsed=130.3s

  [9924/21087] intraday_18112.csv.gz  in=329,061,237 out=80,248,182 elapsed=130.3s

  [9925/21087] intraday_18113.csv.gz  in=329,073,586 out=80,260,531 elapsed=130.4s

  [9926/21087] intraday_18114.csv.gz  in=329,084,571 out=80,271,516 elapsed=130.4s

  [9927/21087] intraday_18115.csv.gz  in=329,095,450 out=80,282,395 elapsed=130.4s

  [9928/21087] intraday_18116.csv.gz  in=329,108,415 out=80,295,360 elapsed=130.4s

  [9929/21087] intraday_1812.csv.gz  in=329,120,336 out=80,295,360 elapsed=130.4s

  [9930/21087] intraday_18119.csv.gz  in=329,131,978 out=80,307,002 elapsed=130.4s

  [9931/21087] intraday_18118.csv.gz  in=329,145,362 out=80,320,386 elapsed=130.4s

  [9932/21087] intraday_18117.csv.gz  in=329,159,616 out=80,334,640 elapsed=130.4s

  [9933/21087] intraday_18120.csv.gz  in=329,172,044 out=80,347,068 elapsed=130.4s

  [9934/21087] intraday_18121.csv.gz  in=329,183,422 out=80,358,446 elapsed=130.4s

  [9935/21087] intraday_18123.csv.gz  in=329,194,684 out=80,369,708 elapsed=130.5s

  [9936/21087] intraday_18122.csv.gz  in=329,207,773 out=80,382,797 elapsed=130.5s

  [9937/21087] intraday_18124.csv.gz  in=329,221,744 out=80,396,768 elapsed=130.5s

  [9938/21087] intraday_18125.csv.gz  in=329,235,938 out=80,410,919 elapsed=130.5s

  [9939/21087] intraday_18126.csv.gz  in=329,248,164 out=80,423,145 elapsed=130.5s

  [9940/21087] intraday_18127.csv.gz  in=329,259,403 out=80,434,384 elapsed=130.5s

  [9941/21087] intraday_18128.csv.gz  in=329,271,036 out=80,446,017 elapsed=130.5s

  [9942/21087] intraday_1813.csv.gz  in=329,282,762 out=80,446,017 elapsed=130.5s

  [9943/21087] intraday_18129.csv.gz  in=329,295,001 out=80,458,256 elapsed=130.5s

  [9944/21087] intraday_18130.csv.gz  in=329,308,242 out=80,471,497 elapsed=130.5s

  [9945/21087] intraday_18132.csv.gz  in=329,319,442 out=80,482,697 elapsed=130.6s

  [9946/21087] intraday_18133.csv.gz  in=329,331,279 out=80,494,534 elapsed=130.6s

  [9947/21087] intraday_18131.csv.gz  in=329,344,867 out=80,508,122 elapsed=130.6s

  [9948/21087] intraday_18134.csv.gz  in=329,362,312 out=80,523,638 elapsed=130.6s

  [9949/21087] intraday_18135.csv.gz  in=329,373,027 out=80,534,353 elapsed=130.6s

  [9950/21087] intraday_18137.csv.gz  in=329,384,782 out=80,546,108 elapsed=130.6s

  [9951/21087] intraday_18136.csv.gz  in=329,406,122 out=80,564,761 elapsed=130.6s

  [9952/21087] intraday_18138.csv.gz  in=329,420,986 out=80,579,341 elapsed=130.6s

  [9953/21087] intraday_18139.csv.gz  in=329,434,321 out=80,592,676 elapsed=130.6s

  [9954/21087] intraday_1814.csv.gz  in=329,446,139 out=80,592,676 elapsed=130.6s

  [9955/21087] intraday_18140.csv.gz  in=329,458,671 out=80,605,208 elapsed=130.7s

  [9956/21087] intraday_18142.csv.gz  in=329,471,950 out=80,618,487 elapsed=130.7s

  [9957/21087] intraday_18143.csv.gz  in=329,484,494 out=80,631,031 elapsed=130.7s

  [9958/21087] intraday_18145.csv.gz  in=329,495,276 out=80,641,813 elapsed=130.7s

  [9959/21087] intraday_18144.csv.gz  in=329,508,405 out=80,654,942 elapsed=130.7s

  [9960/21087] intraday_18141.csv.gz  in=329,540,876 out=80,683,257 elapsed=130.7s

  [9961/21087] intraday_18146.csv.gz  in=329,552,322 out=80,694,703 elapsed=130.7s

  [9962/21087] intraday_18147.csv.gz  in=329,564,911 out=80,707,292 elapsed=130.7s

  [9963/21087] intraday_1815.csv.gz  in=329,584,039 out=80,707,292 elapsed=130.8s

  [9964/21087] intraday_18149.csv.gz  in=329,598,272 out=80,721,525 elapsed=130.8s

  [9965/21087] intraday_18148.csv.gz  in=329,613,051 out=80,736,304 elapsed=130.8s

  [9966/21087] intraday_18152.csv.gz  in=329,624,267 out=80,747,520 elapsed=130.8s

  [9967/21087] intraday_18153.csv.gz  in=329,636,761 out=80,760,014 elapsed=130.8s

  [9968/21087] intraday_18151.csv.gz  in=329,648,446 out=80,771,699 elapsed=130.8s

  [9969/21087] intraday_18150.csv.gz  in=329,661,379 out=80,784,632 elapsed=130.8s

  [9970/21087] intraday_18154.csv.gz  in=329,674,780 out=80,798,033 elapsed=130.9s

  [9971/21087] intraday_18156.csv.gz  in=329,687,063 out=80,810,316 elapsed=130.9s

  [9972/21087] intraday_18155.csv.gz  in=329,697,888 out=80,821,141 elapsed=130.9s

  [9973/21087] intraday_18157.csv.gz  in=329,710,073 out=80,833,326 elapsed=130.9s

  [9974/21087] intraday_18158.csv.gz  in=329,720,488 out=80,843,741 elapsed=130.9s

  [9975/21087] intraday_18159.csv.gz  in=329,733,953 out=80,857,206 elapsed=130.9s

  [9976/21087] intraday_1816.csv.gz  in=329,753,921 out=80,857,206 elapsed=130.9s

  [9977/21087] intraday_18160.csv.gz  in=329,768,269 out=80,871,554 elapsed=130.9s

  [9978/21087] intraday_18161.csv.gz  in=329,780,107 out=80,883,392 elapsed=130.9s

  [9979/21087] intraday_18162.csv.gz  in=329,793,828 out=80,897,113 elapsed=130.9s

  [9980/21087] intraday_18163.csv.gz  in=329,824,798 out=80,923,864 elapsed=131.0s

  [9981/21087] intraday_18164.csv.gz  in=329,834,524 out=80,933,590 elapsed=131.0s

  [9982/21087] intraday_18165.csv.gz  in=329,846,759 out=80,945,825 elapsed=131.0s

  [9983/21087] intraday_18166.csv.gz  in=329,861,928 out=80,960,994 elapsed=131.0s

  [9984/21087] intraday_18168.csv.gz  in=329,873,483 out=80,972,549 elapsed=131.0s

  [9985/21087] intraday_18167.csv.gz  in=329,886,030 out=80,985,096 elapsed=131.0s

  [9986/21087] intraday_1817.csv.gz  in=329,899,855 out=80,985,096 elapsed=131.0s

  [9987/21087] intraday_18169.csv.gz  in=329,912,054 out=80,997,295 elapsed=131.0s

  [9988/21087] intraday_18170.csv.gz  in=329,922,118 out=81,007,359 elapsed=131.0s

  [9989/21087] intraday_18171.csv.gz  in=329,933,892 out=81,019,133 elapsed=131.0s

  [9990/21087] intraday_18172.csv.gz  in=329,947,114 out=81,032,331 elapsed=131.1s

  [9991/21087] intraday_18173.csv.gz  in=329,958,801 out=81,044,018 elapsed=131.1s

  [9992/21087] intraday_18174.csv.gz  in=329,971,728 out=81,056,843 elapsed=131.1s

  [9993/21087] intraday_18175.csv.gz  in=329,981,693 out=81,066,808 elapsed=131.1s

  [9994/21087] intraday_18176.csv.gz  in=329,993,277 out=81,078,392 elapsed=131.1s

  [9995/21087] intraday_18177.csv.gz  in=330,008,503 out=81,093,618 elapsed=131.1s

  [9996/21087] intraday_18178.csv.gz  in=330,027,467 out=81,112,582 elapsed=131.1s

  [9997/21087] intraday_1818.csv.gz  in=330,040,132 out=81,112,582 elapsed=131.1s

  [9998/21087] intraday_18179.csv.gz  in=330,053,402 out=81,125,852 elapsed=131.1s

  [9999/21087] intraday_18180.csv.gz  in=330,067,219 out=81,139,669 elapsed=131.2s

  [10000/21087] intraday_18181.csv.gz  in=330,080,750 out=81,153,200 elapsed=131.2s

  [10001/21087] intraday_18182.csv.gz  in=330,093,165 out=81,165,615 elapsed=131.2s

  [10002/21087] intraday_18183.csv.gz  in=330,107,526 out=81,179,976 elapsed=131.2s

  [10003/21087] intraday_18185.csv.gz  in=330,117,812 out=81,190,262 elapsed=131.2s

  [10004/21087] intraday_18184.csv.gz  in=330,129,214 out=81,201,664 elapsed=131.2s

  [10005/21087] intraday_18186.csv.gz  in=330,142,488 out=81,214,938 elapsed=131.2s

  [10006/21087] intraday_18187.csv.gz  in=330,162,480 out=81,234,480 elapsed=131.2s

  [10007/21087] intraday_1819.csv.gz  in=330,174,959 out=81,234,480 elapsed=131.3s

  [10008/21087] intraday_18188.csv.gz  in=330,187,084 out=81,246,605 elapsed=131.3s

  [10009/21087] intraday_18189.csv.gz  in=330,200,395 out=81,259,916 elapsed=131.3s

  [10010/21087] intraday_18190.csv.gz  in=330,212,711 out=81,272,232 elapsed=131.3s

  [10011/21087] intraday_18191.csv.gz  in=330,224,724 out=81,284,245 elapsed=131.3s

  [10012/21087] intraday_18192.csv.gz  in=330,235,767 out=81,295,288 elapsed=131.3s

  [10013/21087] intraday_18193.csv.gz  in=330,246,132 out=81,305,653 elapsed=131.3s

  [10014/21087] intraday_18194.csv.gz  in=330,257,586 out=81,317,107 elapsed=131.3s

  [10015/21087] intraday_18195.csv.gz  in=330,270,420 out=81,329,941 elapsed=131.3s

  [10016/21087] intraday_18196.csv.gz  in=330,285,025 out=81,344,136 elapsed=131.3s

  [10017/21087] intraday_1820.csv.gz  in=330,293,868 out=81,344,136 elapsed=131.4s

  [10018/21087] intraday_18197.csv.gz  in=330,307,464 out=81,357,732 elapsed=131.4s

  [10019/21087] intraday_18199.csv.gz  in=330,320,187 out=81,370,455 elapsed=131.4s

  [10020/21087] intraday_18198.csv.gz  in=330,332,711 out=81,382,979 elapsed=131.4s

  [10021/21087] intraday_18201.csv.gz  in=330,343,458 out=81,393,726 elapsed=131.4s

  [10022/21087] intraday_18200.csv.gz  in=330,356,968 out=81,407,236 elapsed=131.4s

  [10023/21087] intraday_18203.csv.gz  in=330,370,015 out=81,420,283 elapsed=131.4s

  [10024/21087] intraday_18202.csv.gz  in=330,381,822 out=81,432,090 elapsed=131.4s

  [10025/21087] intraday_18204.csv.gz  in=330,396,150 out=81,446,418 elapsed=131.4s

  [10026/21087] intraday_18206.csv.gz  in=330,410,899 out=81,461,167 elapsed=131.5s

  [10027/21087] intraday_18205.csv.gz  in=330,424,895 out=81,475,163 elapsed=131.5s

  [10028/21087] intraday_18207.csv.gz  in=330,439,196 out=81,489,011 elapsed=131.5s

  [10029/21087] intraday_18208.csv.gz  in=330,454,395 out=81,504,210 elapsed=131.5s

  [10030/21087] intraday_1821.csv.gz  in=330,466,682 out=81,504,210 elapsed=131.5s

  [10031/21087] intraday_18209.csv.gz  in=330,480,224 out=81,517,752 elapsed=131.5s

  [10032/21087] intraday_18210.csv.gz  in=330,498,457 out=81,535,985 elapsed=131.5s

  [10033/21087] intraday_18211.csv.gz  in=330,517,985 out=81,553,534 elapsed=131.5s

  [10034/21087] intraday_18213.csv.gz  in=330,528,942 out=81,564,491 elapsed=131.6s

  [10035/21087] intraday_18212.csv.gz  in=330,547,286 out=81,582,835 elapsed=131.6s

  [10036/21087] intraday_18215.csv.gz  in=330,558,473 out=81,594,022 elapsed=131.6s

  [10037/21087] intraday_18214.csv.gz  in=330,571,926 out=81,607,156 elapsed=131.6s

  [10038/21087] intraday_18216.csv.gz  in=330,584,037 out=81,619,267 elapsed=131.6s

  [10039/21087] intraday_18217.csv.gz  in=330,595,996 out=81,631,226 elapsed=131.6s

  [10040/21087] intraday_18218.csv.gz  in=330,609,610 out=81,644,840 elapsed=131.6s

  [10041/21087] intraday_18219.csv.gz  in=330,628,625 out=81,661,891 elapsed=131.6s

  [10042/21087] intraday_1822.csv.gz  in=330,640,302 out=81,661,891 elapsed=131.6s

  [10043/21087] intraday_18220.csv.gz  in=330,655,707 out=81,677,296 elapsed=131.6s

  [10044/21087] intraday_18221.csv.gz  in=330,666,400 out=81,687,989 elapsed=131.7s

  [10045/21087] intraday_18222.csv.gz  in=330,678,799 out=81,700,388 elapsed=131.7s

  [10046/21087] intraday_18223.csv.gz  in=330,690,009 out=81,711,598 elapsed=131.7s

  [10047/21087] intraday_18224.csv.gz  in=330,703,598 out=81,725,187 elapsed=131.7s

  [10048/21087] intraday_18225.csv.gz  in=330,716,220 out=81,737,809 elapsed=131.7s

  [10049/21087] intraday_18226.csv.gz  in=330,729,908 out=81,751,497 elapsed=131.7s

  [10050/21087] intraday_18227.csv.gz  in=330,744,941 out=81,766,530 elapsed=131.7s

  [10051/21087] intraday_18228.csv.gz  in=330,757,268 out=81,778,857 elapsed=131.7s

  [10052/21087] intraday_1823.csv.gz  in=330,770,133 out=81,778,857 elapsed=131.7s

  [10053/21087] intraday_18229.csv.gz  in=330,786,591 out=81,795,315 elapsed=131.7s

  [10054/21087] intraday_18230.csv.gz  in=330,796,760 out=81,805,484 elapsed=131.8s

  [10055/21087] intraday_18231.csv.gz  in=330,809,459 out=81,818,183 elapsed=131.8s

  [10056/21087] intraday_18233.csv.gz  in=330,819,053 out=81,827,777 elapsed=131.8s

  [10057/21087] intraday_18232.csv.gz  in=330,831,936 out=81,840,660 elapsed=131.8s

  [10058/21087] intraday_18235.csv.gz  in=330,840,604 out=81,849,328 elapsed=131.8s

  [10059/21087] intraday_18237.csv.gz  in=330,848,658 out=81,857,382 elapsed=131.8s

  [10060/21087] intraday_18234.csv.gz  in=330,861,077 out=81,869,801 elapsed=131.8s

  [10061/21087] intraday_18236.csv.gz  in=330,871,541 out=81,880,265 elapsed=131.8s

  [10062/21087] intraday_18238.csv.gz  in=330,888,215 out=81,896,939 elapsed=131.8s

  [10063/21087] intraday_1824.csv.gz  in=330,903,373 out=81,896,939 elapsed=131.9s

  [10064/21087] intraday_18240.csv.gz  in=330,916,948 out=81,910,514 elapsed=131.9s

  [10065/21087] intraday_18239.csv.gz  in=330,931,780 out=81,925,346 elapsed=131.9s

  [10066/21087] intraday_18241.csv.gz  in=330,943,416 out=81,936,982 elapsed=131.9s

  [10067/21087] intraday_18242.csv.gz  in=330,957,496 out=81,951,062 elapsed=131.9s

  [10068/21087] intraday_18243.csv.gz  in=330,972,702 out=81,966,268 elapsed=132.0s

  [10069/21087] intraday_18244.csv.gz  in=330,986,011 out=81,979,577 elapsed=132.0s

  [10070/21087] intraday_18245.csv.gz  in=330,998,769 out=81,992,335 elapsed=132.0s

  [10071/21087] intraday_18246.csv.gz  in=331,011,672 out=82,005,238 elapsed=132.0s

  [10072/21087] intraday_18248.csv.gz  in=331,022,930 out=82,016,496 elapsed=132.0s

  [10073/21087] intraday_1825.csv.gz  in=331,035,268 out=82,016,496 elapsed=132.0s

  [10074/21087] intraday_18247.csv.gz  in=331,049,023 out=82,030,251 elapsed=132.0s

  [10075/21087] intraday_18249.csv.gz  in=331,061,855 out=82,043,083 elapsed=132.0s

  [10076/21087] intraday_18250.csv.gz  in=331,075,851 out=82,057,079 elapsed=132.0s

  [10077/21087] intraday_18252.csv.gz  in=331,086,859 out=82,068,087 elapsed=132.0s

  [10078/21087] intraday_18251.csv.gz  in=331,100,246 out=82,081,474 elapsed=132.0s

  [10079/21087] intraday_18253.csv.gz  in=331,111,405 out=82,092,633 elapsed=132.1s

  [10080/21087] intraday_18254.csv.gz  in=331,127,520 out=82,108,748 elapsed=132.1s

  [10081/21087] intraday_18256.csv.gz  in=331,138,161 out=82,119,389 elapsed=132.1s

  [10082/21087] intraday_18255.csv.gz  in=331,154,025 out=82,134,758 elapsed=132.1s

  [10083/21087] intraday_18257.csv.gz  in=331,165,331 out=82,146,064 elapsed=132.1s

  [10084/21087] intraday_18258.csv.gz  in=331,179,405 out=82,160,138 elapsed=132.1s

  [10085/21087] intraday_1826.csv.gz  in=331,189,967 out=82,160,138 elapsed=132.1s

  [10086/21087] intraday_18259.csv.gz  in=331,204,461 out=82,174,632 elapsed=132.1s

  [10087/21087] intraday_18261.csv.gz  in=331,216,499 out=82,186,670 elapsed=132.1s

  [10088/21087] intraday_18260.csv.gz  in=331,229,534 out=82,199,705 elapsed=132.1s

  [10089/21087] intraday_18262.csv.gz  in=331,242,337 out=82,212,508 elapsed=132.2s

  [10090/21087] intraday_18263.csv.gz  in=331,254,569 out=82,224,740 elapsed=132.2s

  [10091/21087] intraday_18264.csv.gz  in=331,267,700 out=82,237,871 elapsed=132.2s

  [10092/21087] intraday_18265.csv.gz  in=331,278,985 out=82,249,156 elapsed=132.2s

  [10093/21087] intraday_18266.csv.gz  in=331,294,372 out=82,264,543 elapsed=132.2s

  [10094/21087] intraday_18267.csv.gz  in=331,308,305 out=82,278,476 elapsed=132.2s

  [10095/21087] intraday_18268.csv.gz  in=331,320,954 out=82,291,125 elapsed=132.2s

  [10096/21087] intraday_1827.csv.gz  in=331,335,437 out=82,291,125 elapsed=132.2s

  [10097/21087] intraday_18269.csv.gz  in=331,348,541 out=82,304,229 elapsed=132.2s

  [10098/21087] intraday_18270.csv.gz  in=331,361,192 out=82,316,880 elapsed=132.2s

  [10099/21087] intraday_18274.csv.gz  in=331,371,777 out=82,327,465 elapsed=132.3s

  [10100/21087] intraday_18271.csv.gz  in=331,384,224 out=82,339,912 elapsed=132.3s

  [10101/21087] intraday_18272.csv.gz  in=331,398,571 out=82,354,259 elapsed=132.3s

  [10102/21087] intraday_18273.csv.gz  in=331,412,116 out=82,367,804 elapsed=132.3s

  [10103/21087] intraday_18275.csv.gz  in=331,424,049 out=82,379,737 elapsed=132.3s

  [10104/21087] intraday_18278.csv.gz  in=331,439,600 out=82,394,665 elapsed=132.3s

  [10105/21087] intraday_18277.csv.gz  in=331,451,511 out=82,406,576 elapsed=132.3s

  [10106/21087] intraday_18276.csv.gz  in=331,482,501 out=82,432,485 elapsed=132.3s

  [10107/21087] intraday_1828.csv.gz  in=331,494,810 out=82,432,485 elapsed=132.3s

  [10108/21087] intraday_18279.csv.gz  in=331,508,565 out=82,446,240 elapsed=132.3s

  [10109/21087] intraday_18281.csv.gz  in=331,522,640 out=82,460,315 elapsed=132.4s

  [10110/21087] intraday_18280.csv.gz  in=331,535,772 out=82,473,447 elapsed=132.4s

  [10111/21087] intraday_18283.csv.gz  in=331,547,142 out=82,484,817 elapsed=132.4s

  [10112/21087] intraday_18282.csv.gz  in=331,559,546 out=82,497,221 elapsed=132.4s

  [10113/21087] intraday_18284.csv.gz  in=331,574,477 out=82,512,152 elapsed=132.4s

  [10114/21087] intraday_18287.csv.gz  in=331,586,329 out=82,524,004 elapsed=132.4s

  [10115/21087] intraday_18285.csv.gz  in=331,599,110 out=82,536,785 elapsed=132.4s

  [10116/21087] intraday_18286.csv.gz  in=331,612,911 out=82,550,586 elapsed=132.4s

  [10117/21087] intraday_1829.csv.gz  in=331,623,851 out=82,550,586 elapsed=132.5s

  [10118/21087] intraday_18288.csv.gz  in=331,636,920 out=82,563,655 elapsed=132.5s

  [10119/21087] intraday_18290.csv.gz  in=331,653,460 out=82,580,195 elapsed=132.5s

  [10120/21087] intraday_18289.csv.gz  in=331,667,158 out=82,593,893 elapsed=132.5s

  [10121/21087] intraday_18291.csv.gz  in=331,682,982 out=82,609,717 elapsed=132.5s

  [10122/21087] intraday_18292.csv.gz  in=331,695,079 out=82,621,814 elapsed=132.5s

  [10123/21087] intraday_18294.csv.gz  in=331,706,414 out=82,633,149 elapsed=132.5s

  [10124/21087] intraday_18293.csv.gz  in=331,718,569 out=82,645,304 elapsed=132.5s

  [10125/21087] intraday_18295.csv.gz  in=331,731,733 out=82,658,468 elapsed=132.6s

  [10126/21087] intraday_18296.csv.gz  in=331,745,390 out=82,672,125 elapsed=132.6s

  [10127/21087] intraday_18297.csv.gz  in=331,758,238 out=82,684,973 elapsed=132.6s

  [10128/21087] intraday_1830.csv.gz  in=331,770,475 out=82,684,973 elapsed=132.6s

  [10129/21087] intraday_18298.csv.gz  in=331,793,223 out=82,705,115 elapsed=132.6s

  [10130/21087] intraday_18299.csv.gz  in=331,806,626 out=82,718,518 elapsed=132.6s

  [10131/21087] intraday_18302.csv.gz  in=331,821,057 out=82,732,949 elapsed=132.7s

  [10132/21087] intraday_18303.csv.gz  in=331,833,674 out=82,745,566 elapsed=132.7s

  [10133/21087] intraday_18301.csv.gz  in=331,848,441 out=82,760,333 elapsed=132.7s

  [10134/21087] intraday_18300.csv.gz  in=331,862,343 out=82,773,239 elapsed=132.7s

  [10135/21087] intraday_18304.csv.gz  in=331,877,518 out=82,788,414 elapsed=132.7s

  [10136/21087] intraday_18305.csv.gz  in=331,890,753 out=82,801,649 elapsed=132.7s

  [10137/21087] intraday_18306.csv.gz  in=331,899,959 out=82,810,855 elapsed=132.7s

  [10138/21087] intraday_18307.csv.gz  in=331,912,959 out=82,823,855 elapsed=132.7s

  [10139/21087] intraday_1831.csv.gz  in=331,924,283 out=82,823,855 elapsed=132.7s

  [10140/21087] intraday_18309.csv.gz  in=331,937,395 out=82,836,967 elapsed=132.8s

  [10141/21087] intraday_18310.csv.gz  in=331,949,248 out=82,848,820 elapsed=132.8s

  [10142/21087] intraday_18308.csv.gz  in=331,963,759 out=82,863,331 elapsed=132.8s

  [10143/21087] intraday_18311.csv.gz  in=331,977,172 out=82,876,744 elapsed=132.8s

  [10144/21087] intraday_18312.csv.gz  in=331,988,893 out=82,888,465 elapsed=132.8s

  [10145/21087] intraday_18313.csv.gz  in=332,003,148 out=82,902,720 elapsed=132.8s

  [10146/21087] intraday_18314.csv.gz  in=332,016,434 out=82,916,006 elapsed=132.8s

  [10147/21087] intraday_18315.csv.gz  in=332,029,343 out=82,928,915 elapsed=132.8s

  [10148/21087] intraday_18316.csv.gz  in=332,041,762 out=82,941,334 elapsed=132.8s

  [10149/21087] intraday_18317.csv.gz  in=332,053,123 out=82,952,695 elapsed=132.9s

  [10150/21087] intraday_18318.csv.gz  in=332,065,293 out=82,964,865 elapsed=132.9s

  [10151/21087] intraday_18319.csv.gz  in=332,081,945 out=82,981,517 elapsed=132.9s

  [10152/21087] intraday_1832.csv.gz  in=332,093,626 out=82,981,517 elapsed=132.9s

  [10153/21087] intraday_18320.csv.gz  in=332,109,759 out=82,997,650 elapsed=132.9s

  [10154/21087] intraday_18321.csv.gz  in=332,128,290 out=83,015,357 elapsed=132.9s

  [10155/21087] intraday_18322.csv.gz  in=332,142,411 out=83,029,478 elapsed=132.9s

  [10156/21087] intraday_18323.csv.gz  in=332,160,571 out=83,047,638 elapsed=132.9s

  [10157/21087] intraday_18324.csv.gz  in=332,174,045 out=83,060,454 elapsed=132.9s

  [10158/21087] intraday_18326.csv.gz  in=332,185,924 out=83,072,333 elapsed=133.0s

  [10159/21087] intraday_18325.csv.gz  in=332,201,211 out=83,087,620 elapsed=133.0s

  [10160/21087] intraday_18327.csv.gz  in=332,212,432 out=83,098,841 elapsed=133.0s

  [10161/21087] intraday_18328.csv.gz  in=332,226,397 out=83,112,806 elapsed=133.0s

  [10162/21087] intraday_18329.csv.gz  in=332,238,854 out=83,125,263 elapsed=133.0s

  [10163/21087] intraday_1833.csv.gz  in=332,251,052 out=83,125,263 elapsed=133.0s

  [10164/21087] intraday_18330.csv.gz  in=332,263,796 out=83,138,007 elapsed=133.0s

  [10165/21087] intraday_18331.csv.gz  in=332,277,485 out=83,151,696 elapsed=133.0s

  [10166/21087] intraday_18333.csv.gz  in=332,290,263 out=83,164,474 elapsed=133.0s

  [10167/21087] intraday_18332.csv.gz  in=332,302,719 out=83,176,930 elapsed=133.0s

  [10168/21087] intraday_18334.csv.gz  in=332,314,180 out=83,188,391 elapsed=133.0s

  [10169/21087] intraday_18335.csv.gz  in=332,326,313 out=83,200,524 elapsed=133.1s

  [10170/21087] intraday_18338.csv.gz  in=332,339,637 out=83,213,848 elapsed=133.1s

  [10171/21087] intraday_18336.csv.gz  in=332,351,753 out=83,225,964 elapsed=133.1s

  [10172/21087] intraday_18337.csv.gz  in=332,364,013 out=83,238,224 elapsed=133.1s

  [10173/21087] intraday_18339.csv.gz  in=332,378,971 out=83,253,182 elapsed=133.1s

  [10174/21087] intraday_1834.csv.gz  in=332,389,337 out=83,253,182 elapsed=133.1s

  [10175/21087] intraday_18340.csv.gz  in=332,400,861 out=83,264,706 elapsed=133.1s

  [10176/21087] intraday_18342.csv.gz  in=332,414,315 out=83,278,160 elapsed=133.1s

  [10177/21087] intraday_18341.csv.gz  in=332,427,900 out=83,291,745 elapsed=133.2s

  [10178/21087] intraday_18343.csv.gz  in=332,439,768 out=83,303,613 elapsed=133.2s

  [10179/21087] intraday_18344.csv.gz  in=332,453,279 out=83,317,124 elapsed=133.2s

  [10180/21087] intraday_18345.csv.gz  in=332,467,116 out=83,330,961 elapsed=133.2s

  [10181/21087] intraday_18348.csv.gz  in=332,483,456 out=83,347,301 elapsed=133.2s

  [10182/21087] intraday_18346.csv.gz  in=332,499,222 out=83,363,067 elapsed=133.2s

  [10183/21087] intraday_18347.csv.gz  in=332,513,919 out=83,377,764 elapsed=133.2s

  [10184/21087] intraday_18349.csv.gz  in=332,527,767 out=83,391,612 elapsed=133.2s

  [10185/21087] intraday_1835.csv.gz  in=332,541,980 out=83,391,612 elapsed=133.2s

  [10186/21087] intraday_18350.csv.gz  in=332,557,660 out=83,407,292 elapsed=133.3s

  [10187/21087] intraday_18352.csv.gz  in=332,576,582 out=83,426,214 elapsed=133.3s

  [10188/21087] intraday_18351.csv.gz  in=332,592,622 out=83,442,254 elapsed=133.3s

  [10189/21087] intraday_18353.csv.gz  in=332,606,276 out=83,455,908 elapsed=133.3s

  [10190/21087] intraday_18354.csv.gz  in=332,623,782 out=83,473,414 elapsed=133.3s

  [10191/21087] intraday_18357.csv.gz  in=332,633,767 out=83,483,399 elapsed=133.3s

  [10192/21087] intraday_18356.csv.gz  in=332,646,712 out=83,496,344 elapsed=133.3s

  [10193/21087] intraday_18355.csv.gz  in=332,659,774 out=83,509,406 elapsed=133.3s

  [10194/21087] intraday_18358.csv.gz  in=332,674,299 out=83,523,931 elapsed=133.3s

  [10195/21087] intraday_18359.csv.gz  in=332,686,449 out=83,536,081 elapsed=133.4s

  [10196/21087] intraday_1836.csv.gz  in=332,698,750 out=83,536,081 elapsed=133.4s

  [10197/21087] intraday_18361.csv.gz  in=332,711,554 out=83,548,885 elapsed=133.4s

  [10198/21087] intraday_18360.csv.gz  in=332,725,295 out=83,562,626 elapsed=133.4s

  [10199/21087] intraday_18362.csv.gz  in=332,739,123 out=83,576,454 elapsed=133.4s

  [10200/21087] intraday_18363.csv.gz  in=332,750,997 out=83,588,328 elapsed=133.4s

  [10201/21087] intraday_18364.csv.gz  in=332,763,942 out=83,601,273 elapsed=133.4s

  [10202/21087] intraday_18365.csv.gz  in=332,777,689 out=83,615,020 elapsed=133.5s

  [10203/21087] intraday_18367.csv.gz  in=332,789,765 out=83,627,096 elapsed=133.5s

  [10204/21087] intraday_18366.csv.gz  in=332,804,262 out=83,641,593 elapsed=133.5s

  [10205/21087] intraday_18368.csv.gz  in=332,820,063 out=83,657,394 elapsed=133.5s

  [10206/21087] intraday_1837.csv.gz  in=332,833,407 out=83,657,394 elapsed=133.5s

  [10207/21087] intraday_18369.csv.gz  in=332,849,541 out=83,673,528 elapsed=133.5s

  [10208/21087] intraday_18370.csv.gz  in=332,862,670 out=83,686,461 elapsed=133.5s

  [10209/21087] intraday_18371.csv.gz  in=332,877,174 out=83,700,965 elapsed=133.5s

  [10210/21087] intraday_18372.csv.gz  in=332,889,604 out=83,713,395 elapsed=133.5s

  [10211/21087] intraday_18374.csv.gz  in=332,901,535 out=83,725,326 elapsed=133.5s

  [10212/21087] intraday_18373.csv.gz  in=332,913,813 out=83,737,604 elapsed=133.5s

  [10213/21087] intraday_18375.csv.gz  in=332,933,219 out=83,756,954 elapsed=133.6s

  [10214/21087] intraday_18376.csv.gz  in=332,944,827 out=83,768,562 elapsed=133.6s

  [10215/21087] intraday_18377.csv.gz  in=332,953,097 out=83,776,832 elapsed=133.6s

  [10216/21087] intraday_18379.csv.gz  in=332,959,087 out=83,782,822 elapsed=133.6s

  [10217/21087] intraday_18378.csv.gz  in=332,969,198 out=83,792,933 elapsed=133.6s

  [10218/21087] intraday_1838.csv.gz  in=332,981,339 out=83,792,933 elapsed=133.6s

  [10219/21087] intraday_18380.csv.gz  in=332,997,363 out=83,808,957 elapsed=133.6s

  [10220/21087] intraday_18381.csv.gz  in=333,012,029 out=83,823,623 elapsed=133.6s

  [10221/21087] intraday_18382.csv.gz  in=333,024,247 out=83,835,841 elapsed=133.6s

  [10222/21087] intraday_18383.csv.gz  in=333,034,731 out=83,846,325 elapsed=133.6s

  [10223/21087] intraday_18384.csv.gz  in=333,049,063 out=83,860,657 elapsed=133.7s

  [10224/21087] intraday_18387.csv.gz  in=333,060,885 out=83,872,479 elapsed=133.7s

  [10225/21087] intraday_18386.csv.gz  in=333,073,898 out=83,885,492 elapsed=133.7s

  [10226/21087] intraday_18385.csv.gz  in=333,089,304 out=83,900,898 elapsed=133.7s

  [10227/21087] intraday_1839.csv.gz  in=333,113,320 out=83,900,898 elapsed=133.7s

  [10228/21087] intraday_18389.csv.gz  in=333,125,663 out=83,913,241 elapsed=133.7s

  [10229/21087] intraday_18390.csv.gz  in=333,136,829 out=83,924,407 elapsed=133.7s

  [10230/21087] intraday_18388.csv.gz  in=333,150,922 out=83,938,500 elapsed=133.7s

  [10231/21087] intraday_18391.csv.gz  in=333,163,297 out=83,950,875 elapsed=133.8s

  [10232/21087] intraday_18394.csv.gz  in=333,174,185 out=83,961,763 elapsed=133.8s

  [10233/21087] intraday_18393.csv.gz  in=333,185,956 out=83,973,534 elapsed=133.8s

  [10234/21087] intraday_18392.csv.gz  in=333,199,688 out=83,987,266 elapsed=133.8s

  [10235/21087] intraday_18395.csv.gz  in=333,209,687 out=83,997,265 elapsed=133.8s

  [10236/21087] intraday_18397.csv.gz  in=333,222,320 out=84,009,898 elapsed=133.8s

  [10237/21087] intraday_18398.csv.gz  in=333,233,622 out=84,021,200 elapsed=133.9s

  [10238/21087] intraday_18396.csv.gz  in=333,249,733 out=84,037,311 elapsed=133.9s

  [10239/21087] intraday_1840.csv.gz  in=333,262,668 out=84,037,311 elapsed=133.9s

  [10240/21087] intraday_18399.csv.gz  in=333,273,692 out=84,048,335 elapsed=133.9s

  [10241/21087] intraday_18400.csv.gz  in=333,287,036 out=84,061,679 elapsed=133.9s

  [10242/21087] intraday_18401.csv.gz  in=333,299,838 out=84,074,481 elapsed=133.9s

  [10243/21087] intraday_18402.csv.gz  in=333,312,477 out=84,087,120 elapsed=133.9s

  [10244/21087] intraday_18403.csv.gz  in=333,324,218 out=84,098,861 elapsed=133.9s

  [10245/21087] intraday_18406.csv.gz  in=333,336,571 out=84,111,214 elapsed=134.0s

  [10246/21087] intraday_18407.csv.gz  in=333,346,962 out=84,121,605 elapsed=134.0s

  [10247/21087] intraday_18405.csv.gz  in=333,359,286 out=84,133,929 elapsed=134.0s

  [10248/21087] intraday_18404.csv.gz  in=333,371,608 out=84,146,251 elapsed=134.0s

  [10249/21087] intraday_1841.csv.gz  in=333,382,354 out=84,146,251 elapsed=134.0s

  [10250/21087] intraday_18408.csv.gz  in=333,396,231 out=84,160,128 elapsed=134.0s

  [10251/21087] intraday_18410.csv.gz  in=333,407,492 out=84,171,389 elapsed=134.0s

  [10252/21087] intraday_18409.csv.gz  in=333,421,495 out=84,185,392 elapsed=134.0s

  [10253/21087] intraday_18411.csv.gz  in=333,433,697 out=84,197,594 elapsed=134.0s

  [10254/21087] intraday_18413.csv.gz  in=333,446,048 out=84,209,945 elapsed=134.1s

  [10255/21087] intraday_18412.csv.gz  in=333,458,716 out=84,222,613 elapsed=134.1s

  [10256/21087] intraday_18415.csv.gz  in=333,471,601 out=84,235,498 elapsed=134.1s

  [10257/21087] intraday_18414.csv.gz  in=333,485,559 out=84,249,456 elapsed=134.1s

  [10258/21087] intraday_18416.csv.gz  in=333,496,108 out=84,260,005 elapsed=134.1s

  [10259/21087] intraday_18417.csv.gz  in=333,507,594 out=84,271,491 elapsed=134.1s

  [10260/21087] intraday_1842.csv.gz  in=333,519,997 out=84,271,491 elapsed=134.1s

  [10261/21087] intraday_18419.csv.gz  in=333,531,277 out=84,282,771 elapsed=134.1s

  [10262/21087] intraday_18418.csv.gz  in=333,542,965 out=84,294,388 elapsed=134.1s

  [10263/21087] intraday_18420.csv.gz  in=333,554,972 out=84,306,395 elapsed=134.2s

  [10264/21087] intraday_18421.csv.gz  in=333,568,106 out=84,319,529 elapsed=134.2s

  [10265/21087] intraday_18422.csv.gz  in=333,581,290 out=84,332,713 elapsed=134.2s

  [10266/21087] intraday_18423.csv.gz  in=333,594,898 out=84,346,321 elapsed=134.2s

  [10267/21087] intraday_18424.csv.gz  in=333,607,137 out=84,358,560 elapsed=134.2s

  [10268/21087] intraday_18427.csv.gz  in=333,621,519 out=84,372,942 elapsed=134.2s

  [10269/21087] intraday_18428.csv.gz  in=333,634,608 out=84,386,031 elapsed=134.2s

  [10270/21087] intraday_18425.csv.gz  in=333,645,928 out=84,397,351 elapsed=134.2s

  [10271/21087] intraday_18426.csv.gz  in=333,663,251 out=84,414,014 elapsed=134.2s

  [10272/21087] intraday_18429.csv.gz  in=333,675,051 out=84,425,814 elapsed=134.3s

  [10273/21087] intraday_1843.csv.gz  in=333,686,458 out=84,425,814 elapsed=134.3s

  [10274/21087] intraday_18430.csv.gz  in=333,697,822 out=84,437,178 elapsed=134.3s

  [10275/21087] intraday_18431.csv.gz  in=333,710,122 out=84,449,478 elapsed=134.3s

  [10276/21087] intraday_18432.csv.gz  in=333,724,096 out=84,463,452 elapsed=134.3s

  [10277/21087] intraday_18433.csv.gz  in=333,741,080 out=84,479,929 elapsed=134.3s

  [10278/21087] intraday_18435.csv.gz  in=333,752,120 out=84,490,969 elapsed=134.3s

  [10279/21087] intraday_18434.csv.gz  in=333,766,533 out=84,505,382 elapsed=134.3s

  [10280/21087] intraday_18436.csv.gz  in=333,777,727 out=84,516,576 elapsed=134.3s

  [10281/21087] intraday_18437.csv.gz  in=333,799,615 out=84,536,558 elapsed=134.3s

  [10282/21087] intraday_1844.csv.gz  in=333,813,843 out=84,536,558 elapsed=134.4s

  [10283/21087] intraday_18439.csv.gz  in=333,825,896 out=84,548,611 elapsed=134.4s

  [10284/21087] intraday_18438.csv.gz  in=333,839,880 out=84,562,595 elapsed=134.4s

  [10285/21087] intraday_18440.csv.gz  in=333,852,172 out=84,574,887 elapsed=134.4s

  [10286/21087] intraday_18441.csv.gz  in=333,864,342 out=84,587,057 elapsed=134.4s

  [10287/21087] intraday_18442.csv.gz  in=333,875,175 out=84,597,890 elapsed=134.4s

  [10288/21087] intraday_18443.csv.gz  in=333,888,354 out=84,611,069 elapsed=134.4s

  [10289/21087] intraday_18444.csv.gz  in=333,901,355 out=84,624,070 elapsed=134.4s

  [10290/21087] intraday_18445.csv.gz  in=333,912,857 out=84,635,572 elapsed=134.4s

  [10291/21087] intraday_18446.csv.gz  in=333,927,507 out=84,650,222 elapsed=134.4s

  [10292/21087] intraday_18448.csv.gz  in=333,937,159 out=84,659,874 elapsed=134.5s

  [10293/21087] intraday_18447.csv.gz  in=333,951,035 out=84,673,691 elapsed=134.5s

  [10294/21087] intraday_1845.csv.gz  in=333,966,232 out=84,673,691 elapsed=134.5s

  [10295/21087] intraday_18449.csv.gz  in=333,979,045 out=84,686,504 elapsed=134.5s

  [10296/21087] intraday_18450.csv.gz  in=333,992,763 out=84,700,222 elapsed=134.5s

  [10297/21087] intraday_18451.csv.gz  in=334,004,403 out=84,711,862 elapsed=134.5s

  [10298/21087] intraday_18453.csv.gz  in=334,016,325 out=84,723,784 elapsed=134.5s

  [10299/21087] intraday_18454.csv.gz  in=334,025,778 out=84,733,237 elapsed=134.5s

  [10300/21087] intraday_18452.csv.gz  in=334,037,509 out=84,744,968 elapsed=134.5s

  [10301/21087] intraday_18455.csv.gz  in=334,050,850 out=84,758,309 elapsed=134.5s

  [10302/21087] intraday_18456.csv.gz  in=334,064,269 out=84,771,728 elapsed=134.6s

  [10303/21087] intraday_18457.csv.gz  in=334,076,023 out=84,783,482 elapsed=134.6s

  [10304/21087] intraday_18459.csv.gz  in=334,086,595 out=84,794,054 elapsed=134.6s

  [10305/21087] intraday_1846.csv.gz  in=334,101,178 out=84,794,054 elapsed=134.6s

  [10306/21087] intraday_18458.csv.gz  in=334,119,118 out=84,811,000 elapsed=134.6s

  [10307/21087] intraday_18461.csv.gz  in=334,130,974 out=84,822,856 elapsed=134.6s

  [10308/21087] intraday_18460.csv.gz  in=334,142,292 out=84,834,174 elapsed=134.6s

  [10309/21087] intraday_18463.csv.gz  in=334,155,232 out=84,847,114 elapsed=134.6s

  [10310/21087] intraday_18462.csv.gz  in=334,174,081 out=84,865,963 elapsed=134.6s

  [10311/21087] intraday_18464.csv.gz  in=334,186,746 out=84,878,628 elapsed=134.7s

  [10312/21087] intraday_18465.csv.gz  in=334,199,733 out=84,891,615 elapsed=134.7s

  [10313/21087] intraday_18466.csv.gz  in=334,212,478 out=84,904,360 elapsed=134.7s

  [10314/21087] intraday_18467.csv.gz  in=334,225,478 out=84,917,360 elapsed=134.7s

  [10315/21087] intraday_1847.csv.gz  in=334,235,884 out=84,917,360 elapsed=134.7s

  [10316/21087] intraday_18468.csv.gz  in=334,248,988 out=84,930,464 elapsed=134.7s

  [10317/21087] intraday_18470.csv.gz  in=334,262,192 out=84,943,668 elapsed=134.7s

  [10318/21087] intraday_18469.csv.gz  in=334,272,724 out=84,954,200 elapsed=134.7s

  [10319/21087] intraday_18471.csv.gz  in=334,283,134 out=84,964,610 elapsed=134.7s

  [10320/21087] intraday_18472.csv.gz  in=334,296,250 out=84,977,726 elapsed=134.7s

  [10321/21087] intraday_18473.csv.gz  in=334,308,226 out=84,989,702 elapsed=134.8s

  [10322/21087] intraday_18474.csv.gz  in=334,321,184 out=85,002,660 elapsed=134.8s

  [10323/21087] intraday_18475.csv.gz  in=334,333,498 out=85,014,974 elapsed=134.8s

  [10324/21087] intraday_18476.csv.gz  in=334,344,295 out=85,025,771 elapsed=134.8s

  [10325/21087] intraday_18477.csv.gz  in=334,355,138 out=85,036,614 elapsed=134.8s

  [10326/21087] intraday_1848.csv.gz  in=334,368,304 out=85,036,614 elapsed=134.8s

  [10327/21087] intraday_18478.csv.gz  in=334,380,861 out=85,049,171 elapsed=134.8s

  [10328/21087] intraday_18479.csv.gz  in=334,393,482 out=85,061,792 elapsed=134.8s

  [10329/21087] intraday_18480.csv.gz  in=334,405,625 out=85,073,935 elapsed=134.8s

  [10330/21087] intraday_18481.csv.gz  in=334,418,769 out=85,087,027 elapsed=134.9s

  [10331/21087] intraday_18482.csv.gz  in=334,430,027 out=85,098,285 elapsed=134.9s

  [10332/21087] intraday_18483.csv.gz  in=334,444,754 out=85,112,992 elapsed=134.9s

  [10333/21087] intraday_18484.csv.gz  in=334,458,712 out=85,126,950 elapsed=134.9s

  [10334/21087] intraday_18485.csv.gz  in=334,469,622 out=85,137,860 elapsed=134.9s

  [10335/21087] intraday_18486.csv.gz  in=334,481,246 out=85,149,484 elapsed=134.9s

  [10336/21087] intraday_18487.csv.gz  in=334,496,895 out=85,165,133 elapsed=134.9s

  [10337/21087] intraday_18488.csv.gz  in=334,511,330 out=85,179,568 elapsed=134.9s

  [10338/21087] intraday_18489.csv.gz  in=334,527,718 out=85,195,956 elapsed=134.9s

  [10339/21087] intraday_1849.csv.gz  in=334,540,543 out=85,195,956 elapsed=134.9s

  [10340/21087] intraday_18490.csv.gz  in=334,555,850 out=85,211,263 elapsed=135.0s

  [10341/21087] intraday_18492.csv.gz  in=334,568,320 out=85,223,733 elapsed=135.0s

  [10342/21087] intraday_18493.csv.gz  in=334,584,526 out=85,239,939 elapsed=135.0s

  [10343/21087] intraday_18491.csv.gz  in=334,598,317 out=85,253,730 elapsed=135.0s

  [10344/21087] intraday_18495.csv.gz  in=334,611,790 out=85,267,203 elapsed=135.0s

  [10345/21087] intraday_18494.csv.gz  in=334,628,333 out=85,283,746 elapsed=135.0s

  [10346/21087] intraday_18496.csv.gz  in=334,646,303 out=85,301,636 elapsed=135.0s

  [10347/21087] intraday_18497.csv.gz  in=334,660,669 out=85,316,002 elapsed=135.0s

  [10348/21087] intraday_18498.csv.gz  in=334,674,759 out=85,330,092 elapsed=135.0s

  [10349/21087] intraday_1850.csv.gz  in=334,686,783 out=85,330,092 elapsed=135.1s

  [10350/21087] intraday_18500.csv.gz  in=334,697,408 out=85,340,717 elapsed=135.1s

  [10351/21087] intraday_18499.csv.gz  in=334,709,747 out=85,353,056 elapsed=135.1s

  [10352/21087] intraday_18501.csv.gz  in=334,722,008 out=85,365,317 elapsed=135.1s

  [10353/21087] intraday_18502.csv.gz  in=334,734,323 out=85,377,632 elapsed=135.1s

  [10354/21087] intraday_18505.csv.gz  in=334,745,822 out=85,389,131 elapsed=135.1s

  [10355/21087] intraday_18503.csv.gz  in=334,759,636 out=85,402,826 elapsed=135.1s

  [10356/21087] intraday_18504.csv.gz  in=334,773,534 out=85,416,724 elapsed=135.1s

  [10357/21087] intraday_18506.csv.gz  in=334,785,241 out=85,428,431 elapsed=135.1s

  [10358/21087] intraday_18507.csv.gz  in=334,797,736 out=85,440,926 elapsed=135.2s

  [10359/21087] intraday_1851.csv.gz  in=334,808,266 out=85,440,926 elapsed=135.2s

  [10360/21087] intraday_18508.csv.gz  in=334,820,178 out=85,452,838 elapsed=135.2s

  [10361/21087] intraday_18509.csv.gz  in=334,832,778 out=85,465,438 elapsed=135.2s

  [10362/21087] intraday_18510.csv.gz  in=334,846,694 out=85,479,354 elapsed=135.2s

  [10363/21087] intraday_18511.csv.gz  in=334,861,354 out=85,494,014 elapsed=135.2s

  [10364/21087] intraday_18512.csv.gz  in=334,874,610 out=85,507,270 elapsed=135.2s

  [10365/21087] intraday_18514.csv.gz  in=334,888,478 out=85,521,138 elapsed=135.2s

  [10366/21087] intraday_18513.csv.gz  in=334,901,996 out=85,534,656 elapsed=135.2s

  [10367/21087] intraday_18515.csv.gz  in=334,913,259 out=85,545,919 elapsed=135.3s

  [10368/21087] intraday_18516.csv.gz  in=334,925,778 out=85,558,438 elapsed=135.3s

  [10369/21087] intraday_18517.csv.gz  in=334,936,050 out=85,568,710 elapsed=135.3s

  [10370/21087] intraday_18518.csv.gz  in=334,949,641 out=85,582,301 elapsed=135.3s

  [10371/21087] intraday_1852.csv.gz  in=334,962,204 out=85,582,301 elapsed=135.3s

  [10372/21087] intraday_18519.csv.gz  in=334,978,485 out=85,597,050 elapsed=135.3s

  [10373/21087] intraday_18520.csv.gz  in=334,986,573 out=85,605,138 elapsed=135.3s

  [10374/21087] intraday_18524.csv.gz  in=334,986,873 out=85,605,438 elapsed=135.3s

  [10375/21087] intraday_18522.csv.gz  in=334,987,758 out=85,606,323 elapsed=135.3s

  [10376/21087] intraday_18523.csv.gz  in=334,988,053 out=85,606,618 elapsed=135.3s

  [10377/21087] intraday_18521.csv.gz  in=334,999,895 out=85,618,460 elapsed=135.3s

  [10378/21087] intraday_18526.csv.gz  in=335,000,372 out=85,618,937 elapsed=135.3s

  [10379/21087] intraday_18525.csv.gz  in=335,000,936 out=85,619,501 elapsed=135.4s

  [10380/21087] intraday_18527.csv.gz  in=335,001,735 out=85,620,300 elapsed=135.4s

  [10381/21087] intraday_18528.csv.gz  in=335,002,422 out=85,620,987 elapsed=135.4s

  [10382/21087] intraday_18529.csv.gz  in=335,002,774 out=85,621,339 elapsed=135.4s

  [10383/21087] intraday_18530.csv.gz  in=335,003,372 out=85,621,937 elapsed=135.4s

  [10384/21087] intraday_18531.csv.gz  in=335,003,812 out=85,622,377 elapsed=135.4s

  [10385/21087] intraday_1853.csv.gz  in=335,015,979 out=85,622,377 elapsed=135.4s

  [10386/21087] intraday_18532.csv.gz  in=335,016,407 out=85,622,805 elapsed=135.4s

  [10387/21087] intraday_18533.csv.gz  in=335,017,047 out=85,623,445 elapsed=135.4s

  [10388/21087] intraday_18534.csv.gz  in=335,017,933 out=85,624,331 elapsed=135.4s

  [10389/21087] intraday_18535.csv.gz  in=335,018,228 out=85,624,626 elapsed=135.4s

  [10390/21087] intraday_18536.csv.gz  in=335,018,490 out=85,624,888 elapsed=135.4s

  [10391/21087] intraday_18537.csv.gz  in=335,018,817 out=85,625,215 elapsed=135.4s

  [10392/21087] intraday_18538.csv.gz  in=335,019,508 out=85,625,906 elapsed=135.4s

  [10393/21087] intraday_18539.csv.gz  in=335,020,110 out=85,626,508 elapsed=135.4s

  [10394/21087] intraday_18540.csv.gz  in=335,020,357 out=85,626,755 elapsed=135.4s

  [10395/21087] intraday_18541.csv.gz  in=335,020,729 out=85,627,127 elapsed=135.4s

  [10396/21087] intraday_18543.csv.gz  in=335,020,886 out=85,627,284 elapsed=135.4s

  [10397/21087] intraday_18542.csv.gz  in=335,021,572 out=85,627,970 elapsed=135.4s

  [10398/21087] intraday_18544.csv.gz  in=335,022,122 out=85,628,520 elapsed=135.4s

  [10399/21087] intraday_1854.csv.gz  in=335,047,165 out=85,628,520 elapsed=135.4s

  [10400/21087] intraday_18545.csv.gz  in=335,047,494 out=85,628,849 elapsed=135.4s

  [10401/21087] intraday_18546.csv.gz  in=335,047,536 out=85,628,891 elapsed=135.4s

  [10402/21087] intraday_18547.csv.gz  in=335,047,924 out=85,629,279 elapsed=135.4s

  [10403/21087] intraday_18548.csv.gz  in=335,048,227 out=85,629,582 elapsed=135.5s

  [10404/21087] intraday_18549.csv.gz  in=335,048,338 out=85,629,693 elapsed=135.5s

  [10405/21087] intraday_18550.csv.gz  in=335,049,318 out=85,630,673 elapsed=135.5s

  [10406/21087] intraday_1855.csv.gz  in=335,060,930 out=85,630,673 elapsed=135.5s

  [10407/21087] intraday_18553.csv.gz  in=335,061,315 out=85,631,058 elapsed=135.5s

  [10408/21087] intraday_18554.csv.gz  in=335,061,873 out=85,631,616 elapsed=135.5s

  [10409/21087] intraday_18551.csv.gz  in=335,062,655 out=85,632,398 elapsed=135.5s

  [10410/21087] intraday_18552.csv.gz  in=335,063,153 out=85,632,896 elapsed=135.5s

  [10411/21087] intraday_18555.csv.gz  in=335,063,720 out=85,633,463 elapsed=135.5s

  [10412/21087] intraday_18556.csv.gz  in=335,063,885 out=85,633,628 elapsed=135.5s

  [10413/21087] intraday_18557.csv.gz  in=335,064,068 out=85,633,811 elapsed=135.6s

  [10414/21087] intraday_18558.csv.gz  in=335,064,347 out=85,634,090 elapsed=135.6s

  [10415/21087] intraday_18559.csv.gz  in=335,064,527 out=85,634,270 elapsed=135.6s

  [10416/21087] intraday_18560.csv.gz  in=335,064,637 out=85,634,380 elapsed=135.6s

  [10417/21087] intraday_18561.csv.gz  in=335,064,741 out=85,634,484 elapsed=135.6s

  [10418/21087] intraday_18562.csv.gz  in=335,064,890 out=85,634,633 elapsed=135.6s

  [10419/21087] intraday_1856.csv.gz  in=335,085,154 out=85,634,633 elapsed=135.6s

  [10420/21087] intraday_18563.csv.gz  in=335,085,299 out=85,634,778 elapsed=135.6s

  [10421/21087] intraday_18564.csv.gz  in=335,085,841 out=85,635,320 elapsed=135.6s

  [10422/21087] intraday_18565.csv.gz  in=335,086,314 out=85,635,793 elapsed=135.6s

  [10423/21087] intraday_18566.csv.gz  in=335,086,512 out=85,635,991 elapsed=135.6s

  [10424/21087] intraday_18567.csv.gz  in=335,086,637 out=85,636,116 elapsed=135.6s

  [10425/21087] intraday_18568.csv.gz  in=335,086,903 out=85,636,382 elapsed=135.6s

  [10426/21087] intraday_18569.csv.gz  in=335,087,519 out=85,636,998 elapsed=135.6s

  [10427/21087] intraday_18570.csv.gz  in=335,087,762 out=85,637,241 elapsed=135.6s

  [10428/21087] intraday_18571.csv.gz  in=335,087,910 out=85,637,389 elapsed=135.6s

  [10429/21087] intraday_18572.csv.gz  in=335,088,343 out=85,637,822 elapsed=135.6s

  [10430/21087] intraday_1857.csv.gz  in=335,099,811 out=85,637,822 elapsed=135.6s

  [10431/21087] intraday_18573.csv.gz  in=335,100,222 out=85,638,233 elapsed=135.6s

  [10432/21087] intraday_18574.csv.gz  in=335,101,423 out=85,639,434 elapsed=135.6s

  [10433/21087] intraday_18575.csv.gz  in=335,102,455 out=85,640,466 elapsed=135.6s

  [10434/21087] intraday_18576.csv.gz  in=335,102,939 out=85,640,950 elapsed=135.6s

  [10435/21087] intraday_18578.csv.gz  in=335,103,173 out=85,641,184 elapsed=135.7s

  [10436/21087] intraday_18579.csv.gz  in=335,103,653 out=85,641,664 elapsed=135.7s

  [10437/21087] intraday_1858.csv.gz  in=335,116,462 out=85,641,664 elapsed=135.7s

  [10438/21087] intraday_18581.csv.gz  in=335,116,705 out=85,641,907 elapsed=135.7s

  [10439/21087] intraday_18580.csv.gz  in=335,116,969 out=85,642,171 elapsed=135.7s

  [10440/21087] intraday_18577.csv.gz  in=335,133,977 out=85,655,838 elapsed=135.7s

  [10441/21087] intraday_18583.csv.gz  in=335,134,043 out=85,655,904 elapsed=135.7s

  [10442/21087] intraday_18582.csv.gz  in=335,134,401 out=85,656,262 elapsed=135.7s

  [10443/21087] intraday_18584.csv.gz  in=335,134,484 out=85,656,345 elapsed=135.7s

  [10444/21087] intraday_18585.csv.gz  in=335,135,155 out=85,657,016 elapsed=135.7s

  [10445/21087] intraday_18587.csv.gz  in=335,135,453 out=85,657,314 elapsed=135.7s

  [10446/21087] intraday_18586.csv.gz  in=335,136,129 out=85,657,990 elapsed=135.7s

  [10447/21087] intraday_18588.csv.gz  in=335,136,470 out=85,658,331 elapsed=135.7s

  [10448/21087] intraday_18589.csv.gz  in=335,136,839 out=85,658,700 elapsed=135.7s

  [10449/21087] intraday_18590.csv.gz  in=335,137,168 out=85,659,029 elapsed=135.7s

  [10450/21087] intraday_18591.csv.gz  in=335,137,492 out=85,659,353 elapsed=135.7s

  [10451/21087] intraday_1859.csv.gz  in=335,150,021 out=85,659,353 elapsed=135.7s

  [10452/21087] intraday_18592.csv.gz  in=335,150,585 out=85,659,917 elapsed=135.7s

  [10453/21087] intraday_18593.csv.gz  in=335,150,871 out=85,660,203 elapsed=135.7s

  [10454/21087] intraday_18594.csv.gz  in=335,151,272 out=85,660,604 elapsed=135.7s

  [10455/21087] intraday_18595.csv.gz  in=335,151,953 out=85,661,285 elapsed=135.7s

  [10456/21087] intraday_18596.csv.gz  in=335,152,131 out=85,661,463 elapsed=135.8s

  [10457/21087] intraday_18598.csv.gz  in=335,152,477 out=85,661,809 elapsed=135.8s

  [10458/21087] intraday_18597.csv.gz  in=335,152,868 out=85,662,200 elapsed=135.8s

  [10459/21087] intraday_18599.csv.gz  in=335,153,161 out=85,662,493 elapsed=135.8s

  [10460/21087] intraday_18601.csv.gz  in=335,153,225 out=85,662,557 elapsed=135.8s

  [10461/21087] intraday_18600.csv.gz  in=335,153,655 out=85,662,987 elapsed=135.8s

  [10462/21087] intraday_1860.csv.gz  in=335,168,050 out=85,662,987 elapsed=135.8s

  [10463/21087] intraday_18602.csv.gz  in=335,168,430 out=85,663,367 elapsed=135.8s

  [10464/21087] intraday_18604.csv.gz  in=335,170,171 out=85,665,108 elapsed=135.8s

  [10465/21087] intraday_18603.csv.gz  in=335,171,062 out=85,665,999 elapsed=135.8s

  [10466/21087] intraday_18605.csv.gz  in=335,171,670 out=85,666,607 elapsed=135.8s

  [10467/21087] intraday_18606.csv.gz  in=335,172,338 out=85,667,275 elapsed=135.8s

  [10468/21087] intraday_18607.csv.gz  in=335,173,139 out=85,668,076 elapsed=135.8s

  [10469/21087] intraday_18608.csv.gz  in=335,173,476 out=85,668,413 elapsed=135.8s

  [10470/21087] intraday_18609.csv.gz  in=335,174,231 out=85,669,168 elapsed=135.8s

  [10471/21087] intraday_18610.csv.gz  in=335,174,793 out=85,669,730 elapsed=135.8s

  [10472/21087] intraday_18611.csv.gz  in=335,175,026 out=85,669,963 elapsed=135.8s

  [10473/21087] intraday_18612.csv.gz  in=335,175,476 out=85,670,413 elapsed=135.8s

  [10474/21087] intraday_1861.csv.gz  in=335,188,451 out=85,670,413 elapsed=135.8s

  [10475/21087] intraday_18613.csv.gz  in=335,188,877 out=85,670,839 elapsed=135.8s

  [10476/21087] intraday_18614.csv.gz  in=335,189,078 out=85,671,040 elapsed=135.8s

  [10477/21087] intraday_18615.csv.gz  in=335,189,401 out=85,671,363 elapsed=135.8s

  [10478/21087] intraday_18616.csv.gz  in=335,189,779 out=85,671,741 elapsed=135.8s

  [10479/21087] intraday_18618.csv.gz  in=335,190,079 out=85,672,041 elapsed=135.8s

  [10480/21087] intraday_18617.csv.gz  in=335,190,310 out=85,672,272 elapsed=135.8s

  [10481/21087] intraday_18619.csv.gz  in=335,190,782 out=85,672,744 elapsed=135.9s

  [10482/21087] intraday_18620.csv.gz  in=335,190,871 out=85,672,833 elapsed=135.9s

  [10483/21087] intraday_18621.csv.gz  in=335,191,186 out=85,673,148 elapsed=135.9s

  [10484/21087] intraday_1862.csv.gz  in=335,203,190 out=85,673,148 elapsed=135.9s

  [10485/21087] intraday_18622.csv.gz  in=335,204,017 out=85,673,975 elapsed=135.9s

  [10486/21087] intraday_18624.csv.gz  in=335,204,407 out=85,674,365 elapsed=135.9s

  [10487/21087] intraday_18623.csv.gz  in=335,205,534 out=85,675,492 elapsed=135.9s

  [10488/21087] intraday_18625.csv.gz  in=335,205,734 out=85,675,692 elapsed=135.9s

  [10489/21087] intraday_18627.csv.gz  in=335,205,858 out=85,675,816 elapsed=135.9s

  [10490/21087] intraday_18628.csv.gz  in=335,205,979 out=85,675,937 elapsed=135.9s

  [10491/21087] intraday_18626.csv.gz  in=335,206,919 out=85,676,877 elapsed=135.9s

  [10492/21087] intraday_18629.csv.gz  in=335,207,432 out=85,677,390 elapsed=135.9s

  [10493/21087] intraday_18630.csv.gz  in=335,208,025 out=85,677,983 elapsed=135.9s

  [10494/21087] intraday_18632.csv.gz  in=335,208,508 out=85,678,466 elapsed=135.9s

  [10495/21087] intraday_18631.csv.gz  in=335,209,309 out=85,679,267 elapsed=135.9s

  [10496/21087] intraday_1863.csv.gz  in=335,219,689 out=85,679,267 elapsed=135.9s

  [10497/21087] intraday_18634.csv.gz  in=335,220,305 out=85,679,883 elapsed=135.9s

  [10498/21087] intraday_18633.csv.gz  in=335,220,989 out=85,680,567 elapsed=135.9s

  [10499/21087] intraday_18635.csv.gz  in=335,222,280 out=85,681,858 elapsed=135.9s

  [10500/21087] intraday_18636.csv.gz  in=335,223,878 out=85,683,456 elapsed=135.9s

  [10501/21087] intraday_18637.csv.gz  in=335,224,474 out=85,684,052 elapsed=135.9s

  [10502/21087] intraday_18638.csv.gz  in=335,225,407 out=85,684,985 elapsed=135.9s

  [10503/21087] intraday_18640.csv.gz  in=335,226,067 out=85,685,645 elapsed=135.9s

  [10504/21087] intraday_18639.csv.gz  in=335,226,777 out=85,686,355 elapsed=136.0s

  [10505/21087] intraday_18641.csv.gz  in=335,226,923 out=85,686,501 elapsed=136.0s

  [10506/21087] intraday_1864.csv.gz  in=335,238,950 out=85,686,501 elapsed=136.0s

  [10507/21087] intraday_18643.csv.gz  in=335,239,084 out=85,686,635 elapsed=136.0s

  [10508/21087] intraday_18642.csv.gz  in=335,239,449 out=85,687,000 elapsed=136.0s

  [10509/21087] intraday_18647.csv.gz  in=335,239,988 out=85,687,539 elapsed=136.0s

  [10510/21087] intraday_18646.csv.gz  in=335,240,624 out=85,688,175 elapsed=136.0s

  [10511/21087] intraday_18644.csv.gz  in=335,241,101 out=85,688,652 elapsed=136.0s

  [10512/21087] intraday_18645.csv.gz  in=335,241,694 out=85,689,245 elapsed=136.0s

  [10513/21087] intraday_18648.csv.gz  in=335,242,127 out=85,689,678 elapsed=136.0s

  [10514/21087] intraday_18649.csv.gz  in=335,242,737 out=85,690,288 elapsed=136.0s

  [10515/21087] intraday_18650.csv.gz  in=335,243,482 out=85,691,033 elapsed=136.0s

  [10516/21087] intraday_1865.csv.gz  in=335,254,771 out=85,691,033 elapsed=136.0s

  [10517/21087] intraday_18651.csv.gz  in=335,255,170 out=85,691,432 elapsed=136.0s

  [10518/21087] intraday_18652.csv.gz  in=335,255,626 out=85,691,888 elapsed=136.0s

  [10519/21087] intraday_18653.csv.gz  in=335,255,928 out=85,692,190 elapsed=136.0s

  [10520/21087] intraday_18655.csv.gz  in=335,256,557 out=85,692,819 elapsed=136.0s

  [10521/21087] intraday_18657.csv.gz  in=335,256,940 out=85,693,202 elapsed=136.0s

  [10522/21087] intraday_18658.csv.gz  in=335,257,276 out=85,693,538 elapsed=136.0s

  [10523/21087] intraday_18656.csv.gz  in=335,267,823 out=85,701,690 elapsed=136.1s

  [10524/21087] intraday_18659.csv.gz  in=335,268,120 out=85,701,987 elapsed=136.1s

  [10525/21087] intraday_18654.csv.gz  in=335,297,397 out=85,719,446 elapsed=136.1s

  [10526/21087] intraday_18660.csv.gz  in=335,297,806 out=85,719,855 elapsed=136.1s

  [10527/21087] intraday_18661.csv.gz  in=335,298,341 out=85,720,390 elapsed=136.1s

  [10528/21087] intraday_1866.csv.gz  in=335,322,600 out=85,720,390 elapsed=136.1s

  [10529/21087] intraday_18662.csv.gz  in=335,322,914 out=85,720,704 elapsed=136.1s

  [10530/21087] intraday_18663.csv.gz  in=335,323,332 out=85,721,122 elapsed=136.1s

  [10531/21087] intraday_18664.csv.gz  in=335,339,368 out=85,737,158 elapsed=136.1s

  [10532/21087] intraday_18666.csv.gz  in=335,352,111 out=85,749,901 elapsed=136.1s

  [10533/21087] intraday_18667.csv.gz  in=335,364,179 out=85,761,969 elapsed=136.1s

  [10534/21087] intraday_18665.csv.gz  in=335,378,331 out=85,776,121 elapsed=136.1s

  [10535/21087] intraday_18668.csv.gz  in=335,391,701 out=85,789,491 elapsed=136.1s

  [10536/21087] intraday_1867.csv.gz  in=335,401,549 out=85,789,491 elapsed=136.2s

  [10537/21087] intraday_18669.csv.gz  in=335,415,240 out=85,803,182 elapsed=136.2s

  [10538/21087] intraday_18670.csv.gz  in=335,428,319 out=85,816,261 elapsed=136.2s

  [10539/21087] intraday_18671.csv.gz  in=335,440,800 out=85,828,742 elapsed=136.2s

  [10540/21087] intraday_18674.csv.gz  in=335,451,120 out=85,839,062 elapsed=136.2s

  [10541/21087] intraday_18673.csv.gz  in=335,465,666 out=85,853,608 elapsed=136.2s

  [10542/21087] intraday_18672.csv.gz  in=335,479,865 out=85,867,807 elapsed=136.2s

  [10543/21087] intraday_18675.csv.gz  in=335,492,603 out=85,880,545 elapsed=136.2s

  [10544/21087] intraday_18676.csv.gz  in=335,506,820 out=85,894,762 elapsed=136.3s

  [10545/21087] intraday_18678.csv.gz  in=335,518,079 out=85,906,021 elapsed=136.3s

  [10546/21087] intraday_18679.csv.gz  in=335,528,823 out=85,916,765 elapsed=136.3s

  [10547/21087] intraday_18677.csv.gz  in=335,540,305 out=85,928,247 elapsed=136.3s

  [10548/21087] intraday_1868.csv.gz  in=335,551,784 out=85,928,247 elapsed=136.3s

  [10549/21087] intraday_18681.csv.gz  in=335,564,124 out=85,940,587 elapsed=136.3s

  [10550/21087] intraday_18683.csv.gz  in=335,575,824 out=85,952,287 elapsed=136.3s

  [10551/21087] intraday_18680.csv.gz  in=335,590,800 out=85,967,263 elapsed=136.3s

  [10552/21087] intraday_18682.csv.gz  in=335,601,787 out=85,978,250 elapsed=136.3s

  [10553/21087] intraday_18684.csv.gz  in=335,615,272 out=85,991,735 elapsed=136.3s

  [10554/21087] intraday_18685.csv.gz  in=335,627,932 out=86,004,395 elapsed=136.4s

  [10555/21087] intraday_18687.csv.gz  in=335,638,085 out=86,014,548 elapsed=136.4s

  [10556/21087] intraday_18686.csv.gz  in=335,651,124 out=86,027,587 elapsed=136.4s

  [10557/21087] intraday_18688.csv.gz  in=335,663,680 out=86,040,143 elapsed=136.4s

  [10558/21087] intraday_1869.csv.gz  in=335,674,382 out=86,040,143 elapsed=136.4s

  [10559/21087] intraday_18689.csv.gz  in=335,686,271 out=86,052,032 elapsed=136.4s

  [10560/21087] intraday_18690.csv.gz  in=335,698,491 out=86,064,252 elapsed=136.4s

  [10561/21087] intraday_18691.csv.gz  in=335,710,766 out=86,076,527 elapsed=136.4s

  [10562/21087] intraday_18693.csv.gz  in=335,724,529 out=86,090,290 elapsed=136.4s

  [10563/21087] intraday_18692.csv.gz  in=335,736,699 out=86,102,460 elapsed=136.5s

  [10564/21087] intraday_18694.csv.gz  in=335,749,337 out=86,115,098 elapsed=136.5s

  [10565/21087] intraday_18695.csv.gz  in=335,761,194 out=86,126,955 elapsed=136.5s

  [10566/21087] intraday_18696.csv.gz  in=335,773,865 out=86,139,626 elapsed=136.5s

  [10567/21087] intraday_18697.csv.gz  in=335,785,709 out=86,151,470 elapsed=136.5s

  [10568/21087] intraday_18699.csv.gz  in=335,798,298 out=86,164,059 elapsed=136.5s

  [10569/21087] intraday_18698.csv.gz  in=335,810,821 out=86,176,582 elapsed=136.5s

  [10570/21087] intraday_1870.csv.gz  in=335,823,975 out=86,176,582 elapsed=136.5s

  [10571/21087] intraday_18700.csv.gz  in=335,834,287 out=86,186,894 elapsed=136.5s

  [10572/21087] intraday_18701.csv.gz  in=335,845,619 out=86,198,226 elapsed=136.5s

  [10573/21087] intraday_18702.csv.gz  in=335,856,394 out=86,209,001 elapsed=136.6s

  [10574/21087] intraday_18703.csv.gz  in=335,867,295 out=86,219,902 elapsed=136.6s

  [10575/21087] intraday_18704.csv.gz  in=335,879,511 out=86,232,118 elapsed=136.6s

  [10576/21087] intraday_18705.csv.gz  in=335,891,161 out=86,243,768 elapsed=136.6s

  [10577/21087] intraday_18706.csv.gz  in=335,904,828 out=86,257,435 elapsed=136.6s

  [10578/21087] intraday_18708.csv.gz  in=335,915,961 out=86,268,568 elapsed=136.6s

  [10579/21087] intraday_1871.csv.gz  in=335,926,552 out=86,268,568 elapsed=136.6s

  [10580/21087] intraday_18707.csv.gz  in=335,941,158 out=86,283,174 elapsed=136.6s

  [10581/21087] intraday_18709.csv.gz  in=335,952,420 out=86,294,436 elapsed=136.6s

  [10582/21087] intraday_18710.csv.gz  in=335,965,593 out=86,307,609 elapsed=136.7s

  [10583/21087] intraday_18711.csv.gz  in=335,978,092 out=86,320,108 elapsed=136.7s

  [10584/21087] intraday_18713.csv.gz  in=335,988,803 out=86,330,819 elapsed=136.7s

  [10585/21087] intraday_18712.csv.gz  in=336,002,295 out=86,344,311 elapsed=136.7s

  [10586/21087] intraday_18717.csv.gz  in=336,017,176 out=86,359,192 elapsed=136.7s

  [10587/21087] intraday_18715.csv.gz  in=336,029,961 out=86,371,977 elapsed=136.7s

  [10588/21087] intraday_18714.csv.gz  in=336,042,198 out=86,384,214 elapsed=136.7s

  [10589/21087] intraday_18716.csv.gz  in=336,055,932 out=86,397,948 elapsed=136.7s

  [10590/21087] intraday_1872.csv.gz  in=336,069,118 out=86,397,948 elapsed=136.8s

  [10591/21087] intraday_18719.csv.gz  in=336,079,106 out=86,407,936 elapsed=136.8s

  [10592/21087] intraday_18718.csv.gz  in=336,091,615 out=86,420,445 elapsed=136.8s

  [10593/21087] intraday_18720.csv.gz  in=336,103,381 out=86,432,211 elapsed=136.8s

  [10594/21087] intraday_18721.csv.gz  in=336,116,074 out=86,444,904 elapsed=136.8s

  [10595/21087] intraday_18724.csv.gz  in=336,126,300 out=86,455,130 elapsed=136.8s

  [10596/21087] intraday_18722.csv.gz  in=336,139,489 out=86,468,319 elapsed=136.8s

  [10597/21087] intraday_18723.csv.gz  in=336,152,928 out=86,481,758 elapsed=136.8s

  [10598/21087] intraday_18725.csv.gz  in=336,165,515 out=86,494,345 elapsed=136.8s

  [10599/21087] intraday_18726.csv.gz  in=336,176,293 out=86,505,123 elapsed=136.9s

  [10600/21087] intraday_18727.csv.gz  in=336,191,267 out=86,520,097 elapsed=136.9s

  [10601/21087] intraday_18729.csv.gz  in=336,205,054 out=86,533,884 elapsed=136.9s

  [10602/21087] intraday_18728.csv.gz  in=336,217,073 out=86,545,903 elapsed=136.9s

  [10603/21087] intraday_1873.csv.gz  in=336,227,797 out=86,545,903 elapsed=136.9s

  [10604/21087] intraday_18730.csv.gz  in=336,241,202 out=86,559,308 elapsed=136.9s

  [10605/21087] intraday_18732.csv.gz  in=336,250,378 out=86,568,484 elapsed=136.9s

  [10606/21087] intraday_18731.csv.gz  in=336,263,000 out=86,581,106 elapsed=136.9s

  [10607/21087] intraday_18733.csv.gz  in=336,275,914 out=86,594,020 elapsed=136.9s

  [10608/21087] intraday_18734.csv.gz  in=336,289,735 out=86,607,841 elapsed=137.0s

  [10609/21087] intraday_18735.csv.gz  in=336,301,715 out=86,619,821 elapsed=137.0s

  [10610/21087] intraday_18737.csv.gz  in=336,313,206 out=86,631,312 elapsed=137.0s

  [10611/21087] intraday_18736.csv.gz  in=336,346,718 out=86,660,640 elapsed=137.0s

  [10612/21087] intraday_1874.csv.gz  in=336,358,017 out=86,660,640 elapsed=137.0s

  [10613/21087] intraday_18739.csv.gz  in=336,371,668 out=86,674,291 elapsed=137.0s

  [10614/21087] intraday_18738.csv.gz  in=336,382,243 out=86,684,866 elapsed=137.0s

  [10615/21087] intraday_18740.csv.gz  in=336,394,558 out=86,697,181 elapsed=137.0s

  [10616/21087] intraday_18742.csv.gz  in=336,405,352 out=86,707,975 elapsed=137.0s

  [10617/21087] intraday_18741.csv.gz  in=336,418,123 out=86,720,746 elapsed=137.1s

  [10618/21087] intraday_18743.csv.gz  in=336,428,595 out=86,731,218 elapsed=137.1s

  [10619/21087] intraday_18744.csv.gz  in=336,442,786 out=86,745,409 elapsed=137.1s

  [10620/21087] intraday_18745.csv.gz  in=336,457,783 out=86,760,406 elapsed=137.1s

  [10621/21087] intraday_18746.csv.gz  in=336,471,006 out=86,773,629 elapsed=137.1s

  [10622/21087] intraday_18748.csv.gz  in=336,483,182 out=86,785,805 elapsed=137.1s

  [10623/21087] intraday_18749.csv.gz  in=336,498,474 out=86,801,097 elapsed=137.1s

  [10624/21087] intraday_18747.csv.gz  in=336,513,255 out=86,815,878 elapsed=137.1s

  [10625/21087] intraday_1875.csv.gz  in=336,524,666 out=86,815,878 elapsed=137.1s

  [10626/21087] intraday_18750.csv.gz  in=336,535,206 out=86,826,418 elapsed=137.1s

  [10627/21087] intraday_18752.csv.gz  in=336,545,516 out=86,836,728 elapsed=137.1s

  [10628/21087] intraday_18751.csv.gz  in=336,560,877 out=86,852,089 elapsed=137.2s

  [10629/21087] intraday_18753.csv.gz  in=336,572,906 out=86,864,118 elapsed=137.2s

  [10630/21087] intraday_18754.csv.gz  in=336,585,639 out=86,876,851 elapsed=137.2s

  [10631/21087] intraday_18755.csv.gz  in=336,597,405 out=86,888,617 elapsed=137.2s

  [10632/21087] intraday_18756.csv.gz  in=336,610,520 out=86,901,732 elapsed=137.2s

  [10633/21087] intraday_18757.csv.gz  in=336,623,658 out=86,914,870 elapsed=137.2s

  [10634/21087] intraday_18759.csv.gz  in=336,635,067 out=86,926,279 elapsed=137.2s

  [10635/21087] intraday_18758.csv.gz  in=336,648,681 out=86,939,893 elapsed=137.2s

  [10636/21087] intraday_1876.csv.gz  in=336,661,845 out=86,939,893 elapsed=137.2s

  [10637/21087] intraday_18760.csv.gz  in=336,672,147 out=86,950,195 elapsed=137.2s

  [10638/21087] intraday_18761.csv.gz  in=336,684,478 out=86,962,526 elapsed=137.3s

  [10639/21087] intraday_18762.csv.gz  in=336,696,730 out=86,974,778 elapsed=137.3s

  [10640/21087] intraday_18763.csv.gz  in=336,710,027 out=86,988,075 elapsed=137.3s

  [10641/21087] intraday_18764.csv.gz  in=336,723,983 out=87,002,031 elapsed=137.3s

  [10642/21087] intraday_18765.csv.gz  in=336,736,855 out=87,014,903 elapsed=137.3s

  [10643/21087] intraday_18766.csv.gz  in=336,747,827 out=87,025,875 elapsed=137.3s

  [10644/21087] intraday_18768.csv.gz  in=336,760,158 out=87,038,206 elapsed=137.3s

  [10645/21087] intraday_18767.csv.gz  in=336,773,140 out=87,051,188 elapsed=137.3s

  [10646/21087] intraday_1877.csv.gz  in=336,785,003 out=87,051,188 elapsed=137.3s

  [10647/21087] intraday_18769.csv.gz  in=336,796,306 out=87,062,491 elapsed=137.3s

  [10648/21087] intraday_18770.csv.gz  in=336,809,928 out=87,076,113 elapsed=137.4s

  [10649/21087] intraday_18771.csv.gz  in=336,826,383 out=87,092,568 elapsed=137.4s

  [10650/21087] intraday_18773.csv.gz  in=336,840,409 out=87,106,594 elapsed=137.4s

  [10651/21087] intraday_18772.csv.gz  in=336,856,854 out=87,123,039 elapsed=137.4s

  [10652/21087] intraday_18774.csv.gz  in=336,869,981 out=87,136,166 elapsed=137.4s

  [10653/21087] intraday_18776.csv.gz  in=336,883,975 out=87,150,160 elapsed=137.4s

  [10654/21087] intraday_18778.csv.gz  in=336,902,025 out=87,168,210 elapsed=137.4s

  [10655/21087] intraday_18777.csv.gz  in=336,918,048 out=87,184,233 elapsed=137.5s

  [10656/21087] intraday_18775.csv.gz  in=336,959,877 out=87,219,835 elapsed=137.5s

  [10657/21087] intraday_1878.csv.gz  in=336,971,533 out=87,219,835 elapsed=137.5s

  [10658/21087] intraday_18779.csv.gz  in=336,986,189 out=87,234,491 elapsed=137.5s

  [10659/21087] intraday_18780.csv.gz  in=337,001,362 out=87,249,664 elapsed=137.5s

  [10660/21087] intraday_18781.csv.gz  in=337,015,293 out=87,263,595 elapsed=137.5s

  [10661/21087] intraday_18783.csv.gz  in=337,025,021 out=87,273,323 elapsed=137.5s

  [10662/21087] intraday_18782.csv.gz  in=337,038,006 out=87,286,308 elapsed=137.5s

  [10663/21087] intraday_18785.csv.gz  in=337,049,157 out=87,297,459 elapsed=137.6s

  [10664/21087] intraday_18786.csv.gz  in=337,061,962 out=87,310,264 elapsed=137.6s

  [10665/21087] intraday_18784.csv.gz  in=337,075,002 out=87,323,304 elapsed=137.6s

  [10666/21087] intraday_18787.csv.gz  in=337,088,210 out=87,336,512 elapsed=137.6s

  [10667/21087] intraday_1879.csv.gz  in=337,097,899 out=87,336,512 elapsed=137.6s

  [10668/21087] intraday_18789.csv.gz  in=337,109,921 out=87,348,534 elapsed=137.6s

  [10669/21087] intraday_18788.csv.gz  in=337,124,488 out=87,363,101 elapsed=137.6s

  [10670/21087] intraday_18790.csv.gz  in=337,136,216 out=87,374,829 elapsed=137.6s

  [10671/21087] intraday_18791.csv.gz  in=337,150,230 out=87,388,843 elapsed=137.6s

  [10672/21087] intraday_18792.csv.gz  in=337,162,222 out=87,400,835 elapsed=137.7s

  [10673/21087] intraday_18794.csv.gz  in=337,176,208 out=87,414,821 elapsed=137.7s

  [10674/21087] intraday_18793.csv.gz  in=337,190,508 out=87,429,121 elapsed=137.7s

  [10675/21087] intraday_18795.csv.gz  in=337,204,757 out=87,443,370 elapsed=137.7s

  [10676/21087] intraday_18796.csv.gz  in=337,218,328 out=87,456,941 elapsed=137.7s

  [10677/21087] intraday_18797.csv.gz  in=337,230,943 out=87,469,556 elapsed=137.7s

  [10678/21087] intraday_18798.csv.gz  in=337,243,649 out=87,482,262 elapsed=137.7s

  [10679/21087] intraday_1880.csv.gz  in=337,261,488 out=87,482,262 elapsed=137.7s

  [10680/21087] intraday_18799.csv.gz  in=337,275,709 out=87,496,483 elapsed=137.7s

  [10681/21087] intraday_18800.csv.gz  in=337,286,519 out=87,507,293 elapsed=137.8s

  [10682/21087] intraday_18803.csv.gz  in=337,294,082 out=87,514,856 elapsed=137.8s

  [10683/21087] intraday_18801.csv.gz  in=337,306,914 out=87,527,688 elapsed=137.8s

  [10684/21087] intraday_18802.csv.gz  in=337,318,579 out=87,539,353 elapsed=137.8s

  [10685/21087] intraday_18804.csv.gz  in=337,330,680 out=87,551,454 elapsed=137.8s

  [10686/21087] intraday_18805.csv.gz  in=337,333,117 out=87,553,891 elapsed=137.8s

  [10687/21087] intraday_18807.csv.gz  in=337,346,288 out=87,567,062 elapsed=137.8s

  [10688/21087] intraday_18806.csv.gz  in=337,363,122 out=87,583,896 elapsed=137.8s

  [10689/21087] intraday_18808.csv.gz  in=337,376,186 out=87,596,960 elapsed=137.8s

  [10690/21087] intraday_18809.csv.gz  in=337,388,680 out=87,609,454 elapsed=137.8s

  [10691/21087] intraday_1881.csv.gz  in=337,400,579 out=87,609,454 elapsed=137.9s

  [10692/21087] intraday_18810.csv.gz  in=337,414,848 out=87,623,723 elapsed=137.9s

  [10693/21087] intraday_18811.csv.gz  in=337,429,471 out=87,638,346 elapsed=137.9s

  [10694/21087] intraday_18812.csv.gz  in=337,442,360 out=87,651,235 elapsed=137.9s

  [10695/21087] intraday_18813.csv.gz  in=337,454,540 out=87,663,415 elapsed=137.9s

  [10696/21087] intraday_18814.csv.gz  in=337,469,773 out=87,678,648 elapsed=137.9s

  [10697/21087] intraday_18816.csv.gz  in=337,479,448 out=87,688,323 elapsed=137.9s

  [10698/21087] intraday_18815.csv.gz  in=337,492,042 out=87,700,917 elapsed=137.9s

  [10699/21087] intraday_18817.csv.gz  in=337,510,898 out=87,718,611 elapsed=138.0s

  [10700/21087] intraday_18818.csv.gz  in=337,537,442 out=87,743,309 elapsed=138.0s

  [10701/21087] intraday_18819.csv.gz  in=337,549,852 out=87,755,719 elapsed=138.0s

  [10702/21087] intraday_1882.csv.gz  in=337,564,561 out=87,755,719 elapsed=138.0s

  [10703/21087] intraday_18820.csv.gz  in=337,575,663 out=87,766,821 elapsed=138.0s

  [10704/21087] intraday_18822.csv.gz  in=337,591,556 out=87,782,714 elapsed=138.0s

  [10705/21087] intraday_18821.csv.gz  in=337,602,068 out=87,793,226 elapsed=138.0s

  [10706/21087] intraday_18823.csv.gz  in=337,615,201 out=87,806,359 elapsed=138.0s

  [10707/21087] intraday_18824.csv.gz  in=337,626,076 out=87,817,234 elapsed=138.0s

  [10708/21087] intraday_18825.csv.gz  in=337,636,831 out=87,827,989 elapsed=138.0s

  [10709/21087] intraday_18826.csv.gz  in=337,649,836 out=87,840,994 elapsed=138.0s

  [10710/21087] intraday_18827.csv.gz  in=337,662,540 out=87,853,698 elapsed=138.0s

  [10711/21087] intraday_1883.csv.gz  in=337,674,257 out=87,853,698 elapsed=138.1s

  [10712/21087] intraday_18829.csv.gz  in=337,685,990 out=87,865,431 elapsed=138.1s

  [10713/21087] intraday_18830.csv.gz  in=337,697,978 out=87,877,419 elapsed=138.1s

  [10714/21087] intraday_18828.csv.gz  in=337,711,223 out=87,890,664 elapsed=138.1s

  [10715/21087] intraday_18831.csv.gz  in=337,724,106 out=87,903,547 elapsed=138.1s

  [10716/21087] intraday_18833.csv.gz  in=337,734,391 out=87,913,832 elapsed=138.1s

  [10717/21087] intraday_18832.csv.gz  in=337,745,426 out=87,924,867 elapsed=138.1s

  [10718/21087] intraday_18834.csv.gz  in=337,759,514 out=87,938,955 elapsed=138.2s

  [10719/21087] intraday_18835.csv.gz  in=337,772,082 out=87,951,523 elapsed=138.2s

  [10720/21087] intraday_18836.csv.gz  in=337,785,010 out=87,964,451 elapsed=138.2s

  [10721/21087] intraday_18838.csv.gz  in=337,796,985 out=87,976,426 elapsed=138.2s

  [10722/21087] intraday_18837.csv.gz  in=337,808,625 out=87,988,066 elapsed=138.2s

  [10723/21087] intraday_1884.csv.gz  in=337,822,500 out=87,988,066 elapsed=138.2s

  [10724/21087] intraday_18839.csv.gz  in=337,835,232 out=88,000,798 elapsed=138.2s

  [10725/21087] intraday_18841.csv.gz  in=337,848,902 out=88,014,468 elapsed=138.3s

  [10726/21087] intraday_18840.csv.gz  in=337,868,161 out=88,033,727 elapsed=138.3s

  [10727/21087] intraday_18842.csv.gz  in=337,878,273 out=88,043,839 elapsed=138.3s

  [10728/21087] intraday_18843.csv.gz  in=337,889,406 out=88,054,972 elapsed=138.3s

  [10729/21087] intraday_18845.csv.gz  in=337,899,687 out=88,065,253 elapsed=138.3s

  [10730/21087] intraday_18847.csv.gz  in=337,920,213 out=88,084,257 elapsed=138.3s

  [10731/21087] intraday_18844.csv.gz  in=337,932,177 out=88,096,221 elapsed=138.3s

  [10732/21087] intraday_18846.csv.gz  in=337,944,903 out=88,108,947 elapsed=138.3s

  [10733/21087] intraday_18848.csv.gz  in=337,957,274 out=88,121,318 elapsed=138.3s

  [10734/21087] intraday_1885.csv.gz  in=337,970,818 out=88,121,318 elapsed=138.3s

  [10735/21087] intraday_18849.csv.gz  in=337,984,761 out=88,135,261 elapsed=138.3s

  [10736/21087] intraday_18850.csv.gz  in=337,995,824 out=88,146,324 elapsed=138.4s

  [10737/21087] intraday_18851.csv.gz  in=338,007,555 out=88,158,055 elapsed=138.4s

  [10738/21087] intraday_18852.csv.gz  in=338,019,852 out=88,170,352 elapsed=138.4s

  [10739/21087] intraday_18854.csv.gz  in=338,033,215 out=88,183,715 elapsed=138.4s

  [10740/21087] intraday_18853.csv.gz  in=338,046,167 out=88,196,667 elapsed=138.4s

  [10741/21087] intraday_18855.csv.gz  in=338,058,139 out=88,208,639 elapsed=138.4s

  [10742/21087] intraday_18856.csv.gz  in=338,068,686 out=88,219,186 elapsed=138.4s

  [10743/21087] intraday_18857.csv.gz  in=338,082,271 out=88,232,771 elapsed=138.4s

  [10744/21087] intraday_1886.csv.gz  in=338,095,285 out=88,232,771 elapsed=138.4s

  [10745/21087] intraday_18858.csv.gz  in=338,110,345 out=88,247,831 elapsed=138.4s

  [10746/21087] intraday_18859.csv.gz  in=338,123,628 out=88,261,114 elapsed=138.5s

  [10747/21087] intraday_18860.csv.gz  in=338,137,151 out=88,274,637 elapsed=138.5s

  [10748/21087] intraday_18861.csv.gz  in=338,147,524 out=88,285,010 elapsed=138.5s

  [10749/21087] intraday_18862.csv.gz  in=338,157,917 out=88,295,403 elapsed=138.5s

  [10750/21087] intraday_18863.csv.gz  in=338,170,757 out=88,308,243 elapsed=138.5s

  [10751/21087] intraday_18864.csv.gz  in=338,184,405 out=88,321,891 elapsed=138.5s

  [10752/21087] intraday_18865.csv.gz  in=338,196,446 out=88,333,932 elapsed=138.5s

  [10753/21087] intraday_18867.csv.gz  in=338,208,503 out=88,345,989 elapsed=138.5s

  [10754/21087] intraday_18866.csv.gz  in=338,220,582 out=88,358,068 elapsed=138.5s

  [10755/21087] intraday_18868.csv.gz  in=338,234,832 out=88,371,557 elapsed=138.5s

  [10756/21087] intraday_18869.csv.gz  in=338,245,936 out=88,382,661 elapsed=138.5s

  [10757/21087] intraday_1887.csv.gz  in=338,258,683 out=88,382,661 elapsed=138.6s

  [10758/21087] intraday_18870.csv.gz  in=338,273,123 out=88,397,101 elapsed=138.6s

  [10759/21087] intraday_18871.csv.gz  in=338,286,067 out=88,410,045 elapsed=138.6s

  [10760/21087] intraday_18872.csv.gz  in=338,299,945 out=88,423,923 elapsed=138.6s

  [10761/21087] intraday_18873.csv.gz  in=338,313,448 out=88,437,426 elapsed=138.6s

  [10762/21087] intraday_18874.csv.gz  in=338,323,728 out=88,447,706 elapsed=138.6s

  [10763/21087] intraday_18875.csv.gz  in=338,336,209 out=88,460,102 elapsed=138.6s

  [10764/21087] intraday_18877.csv.gz  in=338,347,230 out=88,471,123 elapsed=138.6s

  [10765/21087] intraday_18876.csv.gz  in=338,360,115 out=88,484,008 elapsed=138.6s

  [10766/21087] intraday_18878.csv.gz  in=338,373,022 out=88,496,915 elapsed=138.7s

  [10767/21087] intraday_18879.csv.gz  in=338,384,358 out=88,508,251 elapsed=138.7s

  [10768/21087] intraday_1888.csv.gz  in=338,396,602 out=88,508,251 elapsed=138.7s

  [10769/21087] intraday_18880.csv.gz  in=338,406,765 out=88,518,414 elapsed=138.7s

  [10770/21087] intraday_18881.csv.gz  in=338,419,071 out=88,530,720 elapsed=138.7s

  [10771/21087] intraday_18882.csv.gz  in=338,432,528 out=88,544,177 elapsed=138.7s

  [10772/21087] intraday_18883.csv.gz  in=338,443,508 out=88,555,157 elapsed=138.7s

  [10773/21087] intraday_18884.csv.gz  in=338,455,723 out=88,567,372 elapsed=138.7s

  [10774/21087] intraday_18885.csv.gz  in=338,466,392 out=88,578,041 elapsed=138.7s

  [10775/21087] intraday_18886.csv.gz  in=338,478,869 out=88,590,518 elapsed=138.8s

  [10776/21087] intraday_18887.csv.gz  in=338,492,030 out=88,603,679 elapsed=138.8s

  [10777/21087] intraday_18889.csv.gz  in=338,504,242 out=88,615,891 elapsed=138.8s

  [10778/21087] intraday_1889.csv.gz  in=338,515,564 out=88,615,891 elapsed=138.8s

  [10779/21087] intraday_18888.csv.gz  in=338,533,574 out=88,633,901 elapsed=138.8s

  [10780/21087] intraday_18890.csv.gz  in=338,547,025 out=88,647,352 elapsed=138.8s

  [10781/21087] intraday_18891.csv.gz  in=338,557,095 out=88,657,422 elapsed=138.8s

  [10782/21087] intraday_18893.csv.gz  in=338,568,088 out=88,668,415 elapsed=138.8s

  [10783/21087] intraday_18892.csv.gz  in=338,583,828 out=88,684,155 elapsed=138.8s

  [10784/21087] intraday_18894.csv.gz  in=338,599,276 out=88,699,603 elapsed=138.8s

  [10785/21087] intraday_18895.csv.gz  in=338,609,176 out=88,709,503 elapsed=138.8s

  [10786/21087] intraday_18896.csv.gz  in=338,623,697 out=88,724,024 elapsed=138.9s

  [10787/21087] intraday_18897.csv.gz  in=338,635,424 out=88,735,751 elapsed=138.9s

  [10788/21087] intraday_18898.csv.gz  in=338,647,214 out=88,747,541 elapsed=138.9s

  [10789/21087] intraday_18899.csv.gz  in=338,660,153 out=88,760,480 elapsed=138.9s

  [10790/21087] intraday_1890.csv.gz  in=338,671,003 out=88,760,480 elapsed=138.9s

  [10791/21087] intraday_18900.csv.gz  in=338,684,647 out=88,774,124 elapsed=138.9s

  [10792/21087] intraday_18901.csv.gz  in=338,697,937 out=88,787,414 elapsed=138.9s

  [10793/21087] intraday_18902.csv.gz  in=338,707,753 out=88,797,230 elapsed=138.9s

  [10794/21087] intraday_18903.csv.gz  in=338,719,635 out=88,809,112 elapsed=138.9s

  [10795/21087] intraday_18904.csv.gz  in=338,731,406 out=88,820,883 elapsed=138.9s

  [10796/21087] intraday_18905.csv.gz  in=338,743,017 out=88,832,494 elapsed=138.9s

  [10797/21087] intraday_18906.csv.gz  in=338,759,478 out=88,848,955 elapsed=139.0s

  [10798/21087] intraday_18907.csv.gz  in=338,774,425 out=88,863,902 elapsed=139.0s

  [10799/21087] intraday_18908.csv.gz  in=338,785,880 out=88,875,357 elapsed=139.0s

  [10800/21087] intraday_18909.csv.gz  in=338,797,040 out=88,886,517 elapsed=139.0s

  [10801/21087] intraday_1891.csv.gz  in=338,808,669 out=88,886,517 elapsed=139.0s

  [10802/21087] intraday_18910.csv.gz  in=338,822,944 out=88,900,792 elapsed=139.0s

  [10803/21087] intraday_18911.csv.gz  in=338,834,667 out=88,912,515 elapsed=139.0s

  [10804/21087] intraday_18912.csv.gz  in=338,847,293 out=88,925,141 elapsed=139.0s

  [10805/21087] intraday_18913.csv.gz  in=338,863,076 out=88,940,924 elapsed=139.0s

  [10806/21087] intraday_18915.csv.gz  in=338,877,356 out=88,955,204 elapsed=139.1s

  [10807/21087] intraday_18916.csv.gz  in=338,891,090 out=88,968,938 elapsed=139.1s

  [10808/21087] intraday_18917.csv.gz  in=338,915,785 out=88,992,248 elapsed=139.1s

  [10809/21087] intraday_18914.csv.gz  in=338,930,935 out=89,007,398 elapsed=139.1s

  [10810/21087] intraday_18918.csv.gz  in=338,942,807 out=89,019,270 elapsed=139.1s

  [10811/21087] intraday_1892.csv.gz  in=338,955,330 out=89,019,270 elapsed=139.1s

  [10812/21087] intraday_18919.csv.gz  in=338,982,581 out=89,044,342 elapsed=139.1s

  [10813/21087] intraday_18920.csv.gz  in=338,996,564 out=89,058,325 elapsed=139.1s

  [10814/21087] intraday_18921.csv.gz  in=339,014,679 out=89,076,440 elapsed=139.1s

  [10815/21087] intraday_18923.csv.gz  in=339,028,116 out=89,089,877 elapsed=139.1s

  [10816/21087] intraday_18922.csv.gz  in=339,043,721 out=89,105,482 elapsed=139.1s

  [10817/21087] intraday_18925.csv.gz  in=339,056,785 out=89,118,546 elapsed=139.2s

  [10818/21087] intraday_18924.csv.gz  in=339,070,972 out=89,132,733 elapsed=139.2s

  [10819/21087] intraday_18926.csv.gz  in=339,080,905 out=89,142,666 elapsed=139.2s

  [10820/21087] intraday_18927.csv.gz  in=339,093,603 out=89,155,364 elapsed=139.2s

  [10821/21087] intraday_18928.csv.gz  in=339,106,348 out=89,168,109 elapsed=139.2s

  [10822/21087] intraday_18929.csv.gz  in=339,117,096 out=89,178,857 elapsed=139.2s

  [10823/21087] intraday_1893.csv.gz  in=339,128,339 out=89,178,857 elapsed=139.2s

  [10824/21087] intraday_18930.csv.gz  in=339,141,489 out=89,192,007 elapsed=139.2s

  [10825/21087] intraday_18933.csv.gz  in=339,152,497 out=89,203,015 elapsed=139.3s

  [10826/21087] intraday_18932.csv.gz  in=339,165,190 out=89,215,708 elapsed=139.3s

  [10827/21087] intraday_18931.csv.gz  in=339,179,333 out=89,229,851 elapsed=139.3s

  [10828/21087] intraday_18934.csv.gz  in=339,192,919 out=89,243,437 elapsed=139.3s

  [10829/21087] intraday_18935.csv.gz  in=339,205,169 out=89,255,687 elapsed=139.3s

  [10830/21087] intraday_18938.csv.gz  in=339,219,898 out=89,270,416 elapsed=139.3s

  [10831/21087] intraday_18937.csv.gz  in=339,233,823 out=89,284,341 elapsed=139.3s

  [10832/21087] intraday_18936.csv.gz  in=339,259,194 out=89,307,890 elapsed=139.3s

  [10833/21087] intraday_18939.csv.gz  in=339,272,454 out=89,321,150 elapsed=139.3s

  [10834/21087] intraday_1894.csv.gz  in=339,284,255 out=89,321,150 elapsed=139.3s

  [10835/21087] intraday_18940.csv.gz  in=339,296,252 out=89,333,147 elapsed=139.4s

  [10836/21087] intraday_18941.csv.gz  in=339,308,846 out=89,345,741 elapsed=139.4s

  [10837/21087] intraday_18942.csv.gz  in=339,322,219 out=89,359,114 elapsed=139.4s

  [10838/21087] intraday_18943.csv.gz  in=339,332,412 out=89,369,307 elapsed=139.4s

  [10839/21087] intraday_18944.csv.gz  in=339,348,423 out=89,385,318 elapsed=139.4s

  [10840/21087] intraday_18948.csv.gz  in=339,349,505 out=89,386,400 elapsed=139.4s

  [10841/21087] intraday_18946.csv.gz  in=339,356,593 out=89,393,488 elapsed=139.4s

  [10842/21087] intraday_18945.csv.gz  in=339,367,442 out=89,404,337 elapsed=139.5s

  [10843/21087] intraday_18947.csv.gz  in=339,379,336 out=89,416,231 elapsed=139.5s

  [10844/21087] intraday_1895.csv.gz  in=339,391,568 out=89,416,231 elapsed=139.5s

  [10845/21087] intraday_18949.csv.gz  in=339,408,008 out=89,432,671 elapsed=139.5s

  [10846/21087] intraday_18950.csv.gz  in=339,421,986 out=89,446,649 elapsed=139.5s

  [10847/21087] intraday_18952.csv.gz  in=339,432,554 out=89,457,217 elapsed=139.5s

  [10848/21087] intraday_18953.csv.gz  in=339,446,179 out=89,470,842 elapsed=139.5s

  [10849/21087] intraday_18951.csv.gz  in=339,460,627 out=89,485,290 elapsed=139.5s

  [10850/21087] intraday_18955.csv.gz  in=339,473,338 out=89,497,708 elapsed=139.5s

  [10851/21087] intraday_18954.csv.gz  in=339,488,481 out=89,512,851 elapsed=139.5s

  [10852/21087] intraday_18956.csv.gz  in=339,501,086 out=89,525,456 elapsed=139.6s

  [10853/21087] intraday_18957.csv.gz  in=339,516,035 out=89,540,405 elapsed=139.6s

  [10854/21087] intraday_18959.csv.gz  in=339,525,803 out=89,550,173 elapsed=139.6s

  [10855/21087] intraday_18958.csv.gz  in=339,538,684 out=89,563,054 elapsed=139.6s

  [10856/21087] intraday_1896.csv.gz  in=339,550,553 out=89,563,054 elapsed=139.6s

  [10857/21087] intraday_18960.csv.gz  in=339,563,469 out=89,575,970 elapsed=139.6s

  [10858/21087] intraday_18962.csv.gz  in=339,574,639 out=89,587,140 elapsed=139.6s

  [10859/21087] intraday_18963.csv.gz  in=339,585,588 out=89,598,089 elapsed=139.6s

  [10860/21087] intraday_18964.csv.gz  in=339,595,463 out=89,607,964 elapsed=139.7s

  [10861/21087] intraday_18961.csv.gz  in=339,610,303 out=89,622,804 elapsed=139.7s

  [10862/21087] intraday_18966.csv.gz  in=339,623,686 out=89,636,187 elapsed=139.7s

  [10863/21087] intraday_18965.csv.gz  in=339,641,053 out=89,653,554 elapsed=139.7s

  [10864/21087] intraday_18967.csv.gz  in=339,651,066 out=89,663,567 elapsed=139.7s

  [10865/21087] intraday_18968.csv.gz  in=339,662,021 out=89,674,522 elapsed=139.7s

  [10866/21087] intraday_18969.csv.gz  in=339,675,790 out=89,688,291 elapsed=139.7s

  [10867/21087] intraday_1897.csv.gz  in=339,688,137 out=89,688,291 elapsed=139.7s

  [10868/21087] intraday_18970.csv.gz  in=339,701,316 out=89,701,470 elapsed=139.7s

  [10869/21087] intraday_18971.csv.gz  in=339,713,984 out=89,714,138 elapsed=139.7s

  [10870/21087] intraday_18972.csv.gz  in=339,725,418 out=89,725,572 elapsed=139.8s

  [10871/21087] intraday_18973.csv.gz  in=339,738,079 out=89,738,233 elapsed=139.8s

  [10872/21087] intraday_18974.csv.gz  in=339,749,980 out=89,750,134 elapsed=139.8s

  [10873/21087] intraday_18975.csv.gz  in=339,761,382 out=89,761,536 elapsed=139.8s

  [10874/21087] intraday_18976.csv.gz  in=339,771,930 out=89,772,084 elapsed=139.8s

  [10875/21087] intraday_18977.csv.gz  in=339,785,775 out=89,785,929 elapsed=139.8s

  [10876/21087] intraday_18978.csv.gz  in=339,800,170 out=89,800,324 elapsed=139.8s

  [10877/21087] intraday_1898.csv.gz  in=339,812,351 out=89,800,324 elapsed=139.8s

  [10878/21087] intraday_18979.csv.gz  in=339,825,242 out=89,813,215 elapsed=139.8s

  [10879/21087] intraday_18980.csv.gz  in=339,836,469 out=89,824,442 elapsed=139.8s

  [10880/21087] intraday_18981.csv.gz  in=339,848,492 out=89,836,465 elapsed=139.9s

  [10881/21087] intraday_18982.csv.gz  in=339,860,417 out=89,848,390 elapsed=139.9s

  [10882/21087] intraday_18983.csv.gz  in=339,874,444 out=89,862,417 elapsed=139.9s

  [10883/21087] intraday_18984.csv.gz  in=339,888,861 out=89,876,834 elapsed=139.9s

  [10884/21087] intraday_18985.csv.gz  in=339,900,016 out=89,887,989 elapsed=139.9s

  [10885/21087] intraday_18986.csv.gz  in=339,910,829 out=89,898,802 elapsed=139.9s

  [10886/21087] intraday_18987.csv.gz  in=339,920,735 out=89,908,708 elapsed=139.9s

  [10887/21087] intraday_18988.csv.gz  in=339,931,228 out=89,919,201 elapsed=139.9s

  [10888/21087] intraday_18989.csv.gz  in=339,943,826 out=89,931,799 elapsed=139.9s

  [10889/21087] intraday_18990.csv.gz  in=339,956,032 out=89,944,005 elapsed=140.0s

  [10890/21087] intraday_1899.csv.gz  in=339,981,756 out=89,944,005 elapsed=140.0s

  [10891/21087] intraday_18991.csv.gz  in=339,995,243 out=89,957,492 elapsed=140.0s

  [10892/21087] intraday_18993.csv.gz  in=340,007,175 out=89,969,424 elapsed=140.0s

  [10893/21087] intraday_18992.csv.gz  in=340,027,597 out=89,989,846 elapsed=140.0s

  [10894/21087] intraday_18994.csv.gz  in=340,039,253 out=90,001,502 elapsed=140.0s

  [10895/21087] intraday_18995.csv.gz  in=340,050,583 out=90,012,832 elapsed=140.0s

  [10896/21087] intraday_18996.csv.gz  in=340,062,548 out=90,024,797 elapsed=140.0s

  [10897/21087] intraday_18998.csv.gz  in=340,073,872 out=90,036,121 elapsed=140.0s

  [10898/21087] intraday_18997.csv.gz  in=340,088,354 out=90,050,603 elapsed=140.0s

  [10899/21087] intraday_1900.csv.gz  in=340,101,986 out=90,050,603 elapsed=140.1s

  [10900/21087] intraday_18999.csv.gz  in=340,112,586 out=90,061,203 elapsed=140.1s

  [10901/21087] intraday_19000.csv.gz  in=340,126,294 out=90,074,911 elapsed=140.1s

  [10902/21087] intraday_19001.csv.gz  in=340,141,757 out=90,090,374 elapsed=140.1s

  [10903/21087] intraday_19002.csv.gz  in=340,154,217 out=90,102,834 elapsed=140.1s

  [10904/21087] intraday_19003.csv.gz  in=340,168,361 out=90,116,978 elapsed=140.1s

  [10905/21087] intraday_19004.csv.gz  in=340,178,230 out=90,126,847 elapsed=140.1s

  [10906/21087] intraday_19005.csv.gz  in=340,188,534 out=90,137,151 elapsed=140.1s

  [10907/21087] intraday_19006.csv.gz  in=340,200,805 out=90,149,422 elapsed=140.1s

  [10908/21087] intraday_19008.csv.gz  in=340,212,532 out=90,161,149 elapsed=140.1s

  [10909/21087] intraday_19009.csv.gz  in=340,224,610 out=90,173,227 elapsed=140.2s

  [10910/21087] intraday_19007.csv.gz  in=340,238,374 out=90,186,991 elapsed=140.2s

  [10911/21087] intraday_1901.csv.gz  in=340,253,204 out=90,186,991 elapsed=140.2s

  [10912/21087] intraday_19010.csv.gz  in=340,264,892 out=90,198,679 elapsed=140.2s

  [10913/21087] intraday_19012.csv.gz  in=340,275,550 out=90,209,337 elapsed=140.2s

  [10914/21087] intraday_19013.csv.gz  in=340,291,257 out=90,225,044 elapsed=140.2s

  [10915/21087] intraday_19011.csv.gz  in=340,304,982 out=90,238,146 elapsed=140.2s

  [10916/21087] intraday_19014.csv.gz  in=340,318,590 out=90,251,754 elapsed=140.2s

  [10917/21087] intraday_19018.csv.gz  in=340,330,444 out=90,263,608 elapsed=140.3s

  [10918/21087] intraday_19015.csv.gz  in=340,344,170 out=90,277,334 elapsed=140.3s

  [10919/21087] intraday_19016.csv.gz  in=340,357,139 out=90,290,303 elapsed=140.3s

  [10920/21087] intraday_19017.csv.gz  in=340,371,421 out=90,304,063 elapsed=140.3s

  [10921/21087] intraday_1902.csv.gz  in=340,383,175 out=90,304,063 elapsed=140.3s

  [10922/21087] intraday_19019.csv.gz  in=340,397,191 out=90,318,079 elapsed=140.3s

  [10923/21087] intraday_19020.csv.gz  in=340,408,086 out=90,328,974 elapsed=140.3s

  [10924/21087] intraday_19021.csv.gz  in=340,420,409 out=90,341,297 elapsed=140.3s

  [10925/21087] intraday_19022.csv.gz  in=340,432,310 out=90,353,198 elapsed=140.3s

  [10926/21087] intraday_19023.csv.gz  in=340,443,271 out=90,364,159 elapsed=140.4s

  [10927/21087] intraday_19025.csv.gz  in=340,456,185 out=90,377,073 elapsed=140.4s

  [10928/21087] intraday_19024.csv.gz  in=340,469,012 out=90,389,900 elapsed=140.4s

  [10929/21087] intraday_19026.csv.gz  in=340,480,889 out=90,401,777 elapsed=140.4s

  [10930/21087] intraday_19028.csv.gz  in=340,491,988 out=90,412,876 elapsed=140.4s

  [10931/21087] intraday_1903.csv.gz  in=340,515,355 out=90,412,876 elapsed=140.4s

  [10932/21087] intraday_19027.csv.gz  in=340,527,796 out=90,425,317 elapsed=140.4s

  [10933/21087] intraday_19029.csv.gz  in=340,540,536 out=90,438,057 elapsed=140.4s

  [10934/21087] intraday_19030.csv.gz  in=340,554,242 out=90,451,763 elapsed=140.5s

  [10935/21087] intraday_19032.csv.gz  in=340,568,287 out=90,465,808 elapsed=140.5s

  [10936/21087] intraday_19033.csv.gz  in=340,586,055 out=90,483,576 elapsed=140.5s

  [10937/21087] intraday_19031.csv.gz  in=340,604,124 out=90,501,645 elapsed=140.5s

  [10938/21087] intraday_19036.csv.gz  in=340,614,237 out=90,511,758 elapsed=140.5s

  [10939/21087] intraday_19034.csv.gz  in=340,626,083 out=90,523,604 elapsed=140.5s

  [10940/21087] intraday_19035.csv.gz  in=340,639,274 out=90,536,795 elapsed=140.6s

  [10941/21087] intraday_19037.csv.gz  in=340,655,066 out=90,552,587 elapsed=140.6s

  [10942/21087] intraday_19038.csv.gz  in=340,666,800 out=90,564,321 elapsed=140.6s

  [10943/21087] intraday_1904.csv.gz  in=340,679,470 out=90,564,321 elapsed=140.6s

  [10944/21087] intraday_19039.csv.gz  in=340,693,126 out=90,577,977 elapsed=140.6s

  [10945/21087] intraday_19040.csv.gz  in=340,704,557 out=90,589,408 elapsed=140.6s

  [10946/21087] intraday_19041.csv.gz  in=340,716,500 out=90,601,351 elapsed=140.6s

  [10947/21087] intraday_19042.csv.gz  in=340,729,201 out=90,614,052 elapsed=140.6s

  [10948/21087] intraday_19043.csv.gz  in=340,741,399 out=90,626,250 elapsed=140.6s

  [10949/21087] intraday_19044.csv.gz  in=340,755,397 out=90,640,248 elapsed=140.6s

  [10950/21087] intraday_19045.csv.gz  in=340,766,011 out=90,650,862 elapsed=140.7s

  [10951/21087] intraday_19046.csv.gz  in=340,777,718 out=90,662,569 elapsed=140.7s

  [10952/21087] intraday_19047.csv.gz  in=340,789,479 out=90,674,330 elapsed=140.7s

  [10953/21087] intraday_19048.csv.gz  in=340,801,864 out=90,686,715 elapsed=140.7s

  [10954/21087] intraday_19049.csv.gz  in=340,813,374 out=90,698,225 elapsed=140.7s

  [10955/21087] intraday_1905.csv.gz  in=340,833,622 out=90,698,225 elapsed=140.7s

  [10956/21087] intraday_19051.csv.gz  in=340,845,412 out=90,710,015 elapsed=140.7s

  [10957/21087] intraday_19050.csv.gz  in=340,859,936 out=90,724,539 elapsed=140.7s

  [10958/21087] intraday_19053.csv.gz  in=340,874,168 out=90,738,771 elapsed=140.7s

  [10959/21087] intraday_19052.csv.gz  in=340,885,545 out=90,750,148 elapsed=140.7s

  [10960/21087] intraday_19054.csv.gz  in=340,895,953 out=90,760,555 elapsed=140.8s

  [10961/21087] intraday_19055.csv.gz  in=340,908,227 out=90,772,829 elapsed=140.8s

  [10962/21087] intraday_19056.csv.gz  in=340,923,391 out=90,787,993 elapsed=140.8s

  [10963/21087] intraday_19058.csv.gz  in=340,937,051 out=90,801,653 elapsed=140.8s

  [10964/21087] intraday_19059.csv.gz  in=340,950,792 out=90,815,394 elapsed=140.8s

  [10965/21087] intraday_19057.csv.gz  in=340,966,595 out=90,831,197 elapsed=140.8s

  [10966/21087] intraday_1906.csv.gz  in=340,979,563 out=90,831,197 elapsed=140.9s

  [10967/21087] intraday_19060.csv.gz  in=340,993,485 out=90,845,119 elapsed=140.9s

  [10968/21087] intraday_19061.csv.gz  in=341,006,940 out=90,858,574 elapsed=140.9s

  [10969/21087] intraday_19062.csv.gz  in=341,023,778 out=90,875,412 elapsed=140.9s

  [10970/21087] intraday_19063.csv.gz  in=341,037,515 out=90,889,149 elapsed=140.9s

  [10971/21087] intraday_19064.csv.gz  in=341,055,694 out=90,907,328 elapsed=140.9s

  [10972/21087] intraday_19065.csv.gz  in=341,070,027 out=90,921,661 elapsed=140.9s

  [10973/21087] intraday_19066.csv.gz  in=341,084,682 out=90,936,316 elapsed=140.9s

  [10974/21087] intraday_19067.csv.gz  in=341,098,097 out=90,949,731 elapsed=141.0s

  [10975/21087] intraday_19068.csv.gz  in=341,111,333 out=90,962,967 elapsed=141.0s

  [10976/21087] intraday_19069.csv.gz  in=341,121,241 out=90,972,875 elapsed=141.0s

  [10977/21087] intraday_1907.csv.gz  in=341,133,743 out=90,972,875 elapsed=141.0s

  [10978/21087] intraday_19070.csv.gz  in=341,146,231 out=90,985,227 elapsed=141.0s

  [10979/21087] intraday_19071.csv.gz  in=341,157,733 out=90,996,729 elapsed=141.0s

  [10980/21087] intraday_19073.csv.gz  in=341,170,668 out=91,009,664 elapsed=141.0s

  [10981/21087] intraday_19072.csv.gz  in=341,184,050 out=91,023,046 elapsed=141.0s

  [10982/21087] intraday_19074.csv.gz  in=341,197,570 out=91,036,566 elapsed=141.0s

  [10983/21087] intraday_19075.csv.gz  in=341,209,587 out=91,048,583 elapsed=141.0s

  [10984/21087] intraday_19076.csv.gz  in=341,221,301 out=91,060,297 elapsed=141.1s

  [10985/21087] intraday_19077.csv.gz  in=341,235,720 out=91,074,716 elapsed=141.1s

  [10986/21087] intraday_19078.csv.gz  in=341,247,663 out=91,086,659 elapsed=141.1s

  [10987/21087] intraday_19079.csv.gz  in=341,260,712 out=91,099,708 elapsed=141.1s

  [10988/21087] intraday_1908.csv.gz  in=341,274,032 out=91,099,708 elapsed=141.1s

  [10989/21087] intraday_19080.csv.gz  in=341,287,722 out=91,113,398 elapsed=141.1s

  [10990/21087] intraday_19081.csv.gz  in=341,301,409 out=91,127,085 elapsed=141.1s

  [10991/21087] intraday_19082.csv.gz  in=341,315,122 out=91,140,798 elapsed=141.1s

  [10992/21087] intraday_19083.csv.gz  in=341,327,320 out=91,152,996 elapsed=141.1s

  [10993/21087] intraday_19084.csv.gz  in=341,341,049 out=91,166,725 elapsed=141.1s

  [10994/21087] intraday_19085.csv.gz  in=341,353,679 out=91,179,355 elapsed=141.2s

  [10995/21087] intraday_19088.csv.gz  in=341,365,105 out=91,190,781 elapsed=141.2s

  [10996/21087] intraday_19086.csv.gz  in=341,374,763 out=91,200,439 elapsed=141.2s

  [10997/21087] intraday_19087.csv.gz  in=341,389,923 out=91,215,599 elapsed=141.2s

  [10998/21087] intraday_19089.csv.gz  in=341,396,893 out=91,222,569 elapsed=141.2s

  [10999/21087] intraday_1909.csv.gz  in=341,413,906 out=91,222,569 elapsed=141.2s

  [11000/21087] intraday_19091.csv.gz  in=341,415,729 out=91,224,392 elapsed=141.2s

  [11001/21087] intraday_19090.csv.gz  in=341,427,181 out=91,235,844 elapsed=141.2s

  [11002/21087] intraday_19092.csv.gz  in=341,444,888 out=91,253,551 elapsed=141.2s

  [11003/21087] intraday_19093.csv.gz  in=341,458,437 out=91,267,100 elapsed=141.2s

  [11004/21087] intraday_19094.csv.gz  in=341,471,022 out=91,279,685 elapsed=141.3s

  [11005/21087] intraday_19095.csv.gz  in=341,481,939 out=91,290,602 elapsed=141.3s

  [11006/21087] intraday_19096.csv.gz  in=341,496,182 out=91,304,845 elapsed=141.3s

  [11007/21087] intraday_19098.csv.gz  in=341,509,787 out=91,318,450 elapsed=141.3s

  [11008/21087] intraday_19099.csv.gz  in=341,522,225 out=91,330,888 elapsed=141.3s

  [11009/21087] intraday_19097.csv.gz  in=341,537,230 out=91,345,893 elapsed=141.3s

  [11010/21087] intraday_1910.csv.gz  in=341,549,114 out=91,345,893 elapsed=141.3s

  [11011/21087] intraday_19101.csv.gz  in=341,562,623 out=91,359,402 elapsed=141.4s

  [11012/21087] intraday_19102.csv.gz  in=341,573,035 out=91,369,814 elapsed=141.4s

  [11013/21087] intraday_19103.csv.gz  in=341,585,853 out=91,382,632 elapsed=141.4s

  [11014/21087] intraday_19100.csv.gz  in=341,599,794 out=91,396,573 elapsed=141.4s

  [11015/21087] intraday_19105.csv.gz  in=341,611,654 out=91,408,433 elapsed=141.4s

  [11016/21087] intraday_19107.csv.gz  in=341,622,586 out=91,419,365 elapsed=141.4s

  [11017/21087] intraday_19104.csv.gz  in=341,637,857 out=91,434,636 elapsed=141.4s

  [11018/21087] intraday_19106.csv.gz  in=341,654,565 out=91,449,518 elapsed=141.4s

  [11019/21087] intraday_19108.csv.gz  in=341,670,941 out=91,465,894 elapsed=141.5s

  [11020/21087] intraday_19109.csv.gz  in=341,684,232 out=91,479,185 elapsed=141.5s

  [11021/21087] intraday_1911.csv.gz  in=341,697,376 out=91,479,185 elapsed=141.5s

  [11022/21087] intraday_19110.csv.gz  in=341,707,796 out=91,489,605 elapsed=141.5s

  [11023/21087] intraday_19111.csv.gz  in=341,719,196 out=91,501,005 elapsed=141.5s

  [11024/21087] intraday_19115.csv.gz  in=341,730,716 out=91,512,525 elapsed=141.5s

  [11025/21087] intraday_19114.csv.gz  in=341,743,837 out=91,525,646 elapsed=141.5s

  [11026/21087] intraday_19113.csv.gz  in=341,756,975 out=91,538,784 elapsed=141.5s

  [11027/21087] intraday_19112.csv.gz  in=341,770,480 out=91,552,289 elapsed=141.5s

  [11028/21087] intraday_19117.csv.gz  in=341,782,981 out=91,564,790 elapsed=141.6s

  [11029/21087] intraday_19116.csv.gz  in=341,802,959 out=91,584,768 elapsed=141.6s

  [11030/21087] intraday_19118.csv.gz  in=341,815,043 out=91,596,852 elapsed=141.6s

  [11031/21087] intraday_19119.csv.gz  in=341,825,774 out=91,607,583 elapsed=141.6s

  [11032/21087] intraday_1912.csv.gz  in=341,838,888 out=91,607,583 elapsed=141.6s

  [11033/21087] intraday_19122.csv.gz  in=341,852,181 out=91,620,876 elapsed=141.6s

  [11034/21087] intraday_19121.csv.gz  in=341,867,300 out=91,635,995 elapsed=141.7s

  [11035/21087] intraday_19120.csv.gz  in=341,882,108 out=91,650,803 elapsed=141.7s

  [11036/21087] intraday_19123.csv.gz  in=341,892,515 out=91,661,210 elapsed=141.7s

  [11037/21087] intraday_19124.csv.gz  in=341,905,336 out=91,674,031 elapsed=141.7s

  [11038/21087] intraday_19125.csv.gz  in=341,917,975 out=91,686,670 elapsed=141.7s

  [11039/21087] intraday_19126.csv.gz  in=341,932,409 out=91,701,104 elapsed=141.7s

  [11040/21087] intraday_19127.csv.gz  in=341,946,022 out=91,714,717 elapsed=141.7s

  [11041/21087] intraday_19128.csv.gz  in=341,956,665 out=91,725,360 elapsed=141.7s

  [11042/21087] intraday_1913.csv.gz  in=341,968,103 out=91,725,360 elapsed=141.8s

  [11043/21087] intraday_19130.csv.gz  in=341,978,706 out=91,735,963 elapsed=141.8s

  [11044/21087] intraday_19131.csv.gz  in=341,988,678 out=91,745,935 elapsed=141.8s

  [11045/21087] intraday_19129.csv.gz  in=342,001,335 out=91,758,592 elapsed=141.8s

  [11046/21087] intraday_19132.csv.gz  in=342,015,130 out=91,772,387 elapsed=141.8s

  [11047/21087] intraday_19133.csv.gz  in=342,026,918 out=91,784,175 elapsed=141.8s

  [11048/21087] intraday_19134.csv.gz  in=342,041,114 out=91,798,371 elapsed=141.8s

  [11049/21087] intraday_19135.csv.gz  in=342,055,703 out=91,812,960 elapsed=141.8s

  [11050/21087] intraday_19137.csv.gz  in=342,066,846 out=91,824,103 elapsed=141.9s

  [11051/21087] intraday_19136.csv.gz  in=342,078,425 out=91,835,682 elapsed=141.9s

  [11052/21087] intraday_19138.csv.gz  in=342,091,105 out=91,848,362 elapsed=141.9s

  [11053/21087] intraday_1914.csv.gz  in=342,101,631 out=91,848,362 elapsed=141.9s

  [11054/21087] intraday_19139.csv.gz  in=342,115,821 out=91,862,552 elapsed=141.9s

  [11055/21087] intraday_19140.csv.gz  in=342,130,083 out=91,876,814 elapsed=141.9s

  [11056/21087] intraday_19142.csv.gz  in=342,141,953 out=91,888,684 elapsed=141.9s

  [11057/21087] intraday_19141.csv.gz  in=342,153,112 out=91,899,843 elapsed=141.9s

  [11058/21087] intraday_19143.csv.gz  in=342,166,138 out=91,912,869 elapsed=141.9s

  [11059/21087] intraday_19144.csv.gz  in=342,181,200 out=91,927,931 elapsed=141.9s

  [11060/21087] intraday_19147.csv.gz  in=342,191,871 out=91,938,602 elapsed=142.0s

  [11061/21087] intraday_19146.csv.gz  in=342,205,910 out=91,952,641 elapsed=142.0s

  [11062/21087] intraday_19145.csv.gz  in=342,225,176 out=91,971,907 elapsed=142.0s

  [11063/21087] intraday_19148.csv.gz  in=342,236,706 out=91,983,437 elapsed=142.0s

  [11064/21087] intraday_1915.csv.gz  in=342,250,610 out=91,983,437 elapsed=142.0s

  [11065/21087] intraday_19149.csv.gz  in=342,263,456 out=91,996,283 elapsed=142.0s

  [11066/21087] intraday_19150.csv.gz  in=342,276,881 out=92,009,708 elapsed=142.0s

  [11067/21087] intraday_19151.csv.gz  in=342,289,901 out=92,022,728 elapsed=142.0s

  [11068/21087] intraday_19152.csv.gz  in=342,302,631 out=92,035,458 elapsed=142.0s

  [11069/21087] intraday_19154.csv.gz  in=342,312,979 out=92,045,806 elapsed=142.0s

  [11070/21087] intraday_19153.csv.gz  in=342,324,784 out=92,057,611 elapsed=142.0s

  [11071/21087] intraday_19155.csv.gz  in=342,338,167 out=92,070,994 elapsed=142.0s

  [11072/21087] intraday_19156.csv.gz  in=342,352,652 out=92,085,479 elapsed=142.1s

  [11073/21087] intraday_19159.csv.gz  in=342,364,851 out=92,097,678 elapsed=142.1s

  [11074/21087] intraday_19158.csv.gz  in=342,379,535 out=92,112,362 elapsed=142.1s

  [11075/21087] intraday_1916.csv.gz  in=342,392,588 out=92,112,362 elapsed=142.1s

  [11076/21087] intraday_19157.csv.gz  in=342,407,068 out=92,126,842 elapsed=142.1s

  [11077/21087] intraday_19161.csv.gz  in=342,419,024 out=92,138,798 elapsed=142.1s

  [11078/21087] intraday_19163.csv.gz  in=342,431,691 out=92,151,465 elapsed=142.1s

  [11079/21087] intraday_19162.csv.gz  in=342,445,591 out=92,165,365 elapsed=142.1s

  [11080/21087] intraday_19160.csv.gz  in=342,461,276 out=92,181,050 elapsed=142.1s

  [11081/21087] intraday_19164.csv.gz  in=342,473,899 out=92,193,673 elapsed=142.2s

  [11082/21087] intraday_19166.csv.gz  in=342,483,868 out=92,203,642 elapsed=142.2s

  [11083/21087] intraday_19165.csv.gz  in=342,495,614 out=92,215,388 elapsed=142.2s

  [11084/21087] intraday_19167.csv.gz  in=342,509,424 out=92,229,198 elapsed=142.2s

  [11085/21087] intraday_19168.csv.gz  in=342,523,656 out=92,243,430 elapsed=142.2s

  [11086/21087] intraday_1917.csv.gz  in=342,545,679 out=92,243,430 elapsed=142.2s

  [11087/21087] intraday_19169.csv.gz  in=342,556,582 out=92,254,333 elapsed=142.2s

  [11088/21087] intraday_19170.csv.gz  in=342,569,997 out=92,267,748 elapsed=142.2s

  [11089/21087] intraday_19171.csv.gz  in=342,581,488 out=92,279,239 elapsed=142.3s

  [11090/21087] intraday_19172.csv.gz  in=342,593,757 out=92,291,508 elapsed=142.3s

  [11091/21087] intraday_19173.csv.gz  in=342,608,094 out=92,305,845 elapsed=142.3s

  [11092/21087] intraday_19175.csv.gz  in=342,621,026 out=92,318,777 elapsed=142.3s

  [11093/21087] intraday_19174.csv.gz  in=342,638,768 out=92,336,519 elapsed=142.3s

  [11094/21087] intraday_19177.csv.gz  in=342,650,992 out=92,348,743 elapsed=142.3s

  [11095/21087] intraday_19176.csv.gz  in=342,666,160 out=92,363,911 elapsed=142.3s

  [11096/21087] intraday_19178.csv.gz  in=342,679,469 out=92,377,220 elapsed=142.3s

  [11097/21087] intraday_19179.csv.gz  in=342,690,903 out=92,388,654 elapsed=142.3s

  [11098/21087] intraday_1918.csv.gz  in=342,703,354 out=92,388,654 elapsed=142.3s

  [11099/21087] intraday_19180.csv.gz  in=342,720,869 out=92,404,956 elapsed=142.4s

  [11100/21087] intraday_19182.csv.gz  in=342,735,271 out=92,419,358 elapsed=142.4s

  [11101/21087] intraday_19181.csv.gz  in=342,746,255 out=92,430,342 elapsed=142.4s

  [11102/21087] intraday_19183.csv.gz  in=342,757,790 out=92,441,877 elapsed=142.4s

  [11103/21087] intraday_19184.csv.gz  in=342,770,886 out=92,454,973 elapsed=142.4s

  [11104/21087] intraday_19185.csv.gz  in=342,783,194 out=92,467,281 elapsed=142.4s

  [11105/21087] intraday_19186.csv.gz  in=342,795,554 out=92,479,641 elapsed=142.4s

  [11106/21087] intraday_19188.csv.gz  in=342,806,064 out=92,490,151 elapsed=142.4s

  [11107/21087] intraday_19187.csv.gz  in=342,820,173 out=92,504,260 elapsed=142.4s

  [11108/21087] intraday_19189.csv.gz  in=342,832,512 out=92,516,599 elapsed=142.4s

  [11109/21087] intraday_1919.csv.gz  in=342,848,092 out=92,516,599 elapsed=142.4s

  [11110/21087] intraday_19190.csv.gz  in=342,860,095 out=92,528,602 elapsed=142.5s

  [11111/21087] intraday_19191.csv.gz  in=342,873,300 out=92,541,807 elapsed=142.5s

  [11112/21087] intraday_19192.csv.gz  in=342,885,639 out=92,554,146 elapsed=142.5s

  [11113/21087] intraday_19193.csv.gz  in=342,900,705 out=92,569,212 elapsed=142.5s

  [11114/21087] intraday_19194.csv.gz  in=342,912,637 out=92,581,144 elapsed=142.5s

  [11115/21087] intraday_19195.csv.gz  in=342,924,853 out=92,593,360 elapsed=142.5s

  [11116/21087] intraday_19197.csv.gz  in=342,936,635 out=92,605,142 elapsed=142.5s

  [11117/21087] intraday_19196.csv.gz  in=342,952,830 out=92,621,337 elapsed=142.5s

  [11118/21087] intraday_19198.csv.gz  in=342,964,970 out=92,633,477 elapsed=142.5s

  [11119/21087] intraday_1920.csv.gz  in=342,978,577 out=92,633,477 elapsed=142.6s

  [11120/21087] intraday_19199.csv.gz  in=343,000,489 out=92,654,233 elapsed=142.6s

  [11121/21087] intraday_19200.csv.gz  in=343,017,309 out=92,671,053 elapsed=142.6s

  [11122/21087] intraday_19201.csv.gz  in=343,031,466 out=92,685,210 elapsed=142.6s

  [11123/21087] intraday_19203.csv.gz  in=343,046,238 out=92,699,982 elapsed=142.6s

  [11124/21087] intraday_19202.csv.gz  in=343,060,428 out=92,714,172 elapsed=142.6s

  [11125/21087] intraday_19204.csv.gz  in=343,073,329 out=92,727,073 elapsed=142.6s

  [11126/21087] intraday_19205.csv.gz  in=343,089,597 out=92,743,341 elapsed=142.6s

  [11127/21087] intraday_19206.csv.gz  in=343,104,848 out=92,758,592 elapsed=142.6s

  [11128/21087] intraday_19207.csv.gz  in=343,123,466 out=92,777,210 elapsed=142.6s

  [11129/21087] intraday_19208.csv.gz  in=343,139,265 out=92,793,009 elapsed=142.7s

  [11130/21087] intraday_19209.csv.gz  in=343,152,865 out=92,806,609 elapsed=142.7s

  [11131/21087] intraday_1921.csv.gz  in=343,165,953 out=92,806,609 elapsed=142.7s

  [11132/21087] intraday_19210.csv.gz  in=343,178,710 out=92,819,366 elapsed=142.7s

  [11133/21087] intraday_19211.csv.gz  in=343,192,927 out=92,833,583 elapsed=142.7s

  [11134/21087] intraday_19212.csv.gz  in=343,206,093 out=92,846,409 elapsed=142.7s

  [11135/21087] intraday_19213.csv.gz  in=343,218,166 out=92,858,482 elapsed=142.7s

  [11136/21087] intraday_19214.csv.gz  in=343,229,439 out=92,869,755 elapsed=142.7s

  [11137/21087] intraday_19215.csv.gz  in=343,243,105 out=92,883,421 elapsed=142.8s

  [11138/21087] intraday_19217.csv.gz  in=343,257,935 out=92,898,251 elapsed=142.8s

  [11139/21087] intraday_19218.csv.gz  in=343,270,051 out=92,910,367 elapsed=142.8s

  [11140/21087] intraday_19216.csv.gz  in=343,283,077 out=92,923,393 elapsed=142.8s

  [11141/21087] intraday_19219.csv.gz  in=343,294,803 out=92,935,119 elapsed=142.8s

  [11142/21087] intraday_1922.csv.gz  in=343,314,578 out=92,935,119 elapsed=142.8s

  [11143/21087] intraday_19220.csv.gz  in=343,328,879 out=92,949,420 elapsed=142.8s

  [11144/21087] intraday_19221.csv.gz  in=343,341,833 out=92,962,374 elapsed=142.8s

  [11145/21087] intraday_19222.csv.gz  in=343,355,710 out=92,976,251 elapsed=142.8s

  [11146/21087] intraday_19223.csv.gz  in=343,369,572 out=92,990,113 elapsed=142.9s

  [11147/21087] intraday_19224.csv.gz  in=343,383,318 out=93,003,859 elapsed=142.9s

  [11148/21087] intraday_19225.csv.gz  in=343,397,352 out=93,017,893 elapsed=142.9s

  [11149/21087] intraday_19226.csv.gz  in=343,409,559 out=93,030,100 elapsed=142.9s

  [11150/21087] intraday_19229.csv.gz  in=343,419,211 out=93,039,752 elapsed=142.9s

  [11151/21087] intraday_19227.csv.gz  in=343,432,347 out=93,052,888 elapsed=142.9s

  [11152/21087] intraday_1923.csv.gz  in=343,447,658 out=93,052,888 elapsed=142.9s

  [11153/21087] intraday_19228.csv.gz  in=343,461,104 out=93,066,334 elapsed=142.9s

  [11154/21087] intraday_19230.csv.gz  in=343,476,546 out=93,081,776 elapsed=142.9s

  [11155/21087] intraday_19232.csv.gz  in=343,484,302 out=93,089,532 elapsed=143.0s

  [11156/21087] intraday_19233.csv.gz  in=343,496,231 out=93,101,461 elapsed=143.0s

  [11157/21087] intraday_19231.csv.gz  in=343,507,326 out=93,112,556 elapsed=143.0s

  [11158/21087] intraday_19234.csv.gz  in=343,508,693 out=93,113,923 elapsed=143.0s

  [11159/21087] intraday_19235.csv.gz  in=343,524,261 out=93,129,491 elapsed=143.0s

  [11160/21087] intraday_19236.csv.gz  in=343,537,204 out=93,142,434 elapsed=143.0s

  [11161/21087] intraday_19238.csv.gz  in=343,546,004 out=93,151,234 elapsed=143.0s

  [11162/21087] intraday_19237.csv.gz  in=343,558,388 out=93,163,618 elapsed=143.0s

  [11163/21087] intraday_19239.csv.gz  in=343,571,829 out=93,177,059 elapsed=143.0s

  [11164/21087] intraday_1924.csv.gz  in=343,586,863 out=93,177,059 elapsed=143.1s

  [11165/21087] intraday_19240.csv.gz  in=343,599,516 out=93,189,712 elapsed=143.1s

  [11166/21087] intraday_19241.csv.gz  in=343,611,330 out=93,201,526 elapsed=143.1s

  [11167/21087] intraday_19242.csv.gz  in=343,623,119 out=93,213,315 elapsed=143.1s

  [11168/21087] intraday_19244.csv.gz  in=343,635,479 out=93,225,675 elapsed=143.1s

  [11169/21087] intraday_19243.csv.gz  in=343,650,287 out=93,240,483 elapsed=143.1s

  [11170/21087] intraday_19245.csv.gz  in=343,660,138 out=93,250,334 elapsed=143.1s

  [11171/21087] intraday_19246.csv.gz  in=343,672,072 out=93,262,268 elapsed=143.1s

  [11172/21087] intraday_19248.csv.gz  in=343,683,727 out=93,273,923 elapsed=143.1s

  [11173/21087] intraday_1925.csv.gz  in=343,697,673 out=93,273,923 elapsed=143.1s

  [11174/21087] intraday_19247.csv.gz  in=343,710,047 out=93,286,297 elapsed=143.1s

  [11175/21087] intraday_19249.csv.gz  in=343,720,352 out=93,296,602 elapsed=143.1s

  [11176/21087] intraday_19250.csv.gz  in=343,730,354 out=93,306,604 elapsed=143.2s

  [11177/21087] intraday_19253.csv.gz  in=343,740,102 out=93,316,352 elapsed=143.2s

  [11178/21087] intraday_19252.csv.gz  in=343,751,834 out=93,328,084 elapsed=143.2s

  [11179/21087] intraday_19251.csv.gz  in=343,764,946 out=93,341,196 elapsed=143.2s

  [11180/21087] intraday_19254.csv.gz  in=343,774,786 out=93,351,036 elapsed=143.2s

  [11181/21087] intraday_19256.csv.gz  in=343,787,197 out=93,363,447 elapsed=143.2s

  [11182/21087] intraday_19257.csv.gz  in=343,798,628 out=93,374,878 elapsed=143.2s

  [11183/21087] intraday_19258.csv.gz  in=343,809,872 out=93,386,122 elapsed=143.2s

  [11184/21087] intraday_19255.csv.gz  in=343,829,970 out=93,404,955 elapsed=143.2s

  [11185/21087] intraday_1926.csv.gz  in=343,844,837 out=93,404,955 elapsed=143.3s

  [11186/21087] intraday_19259.csv.gz  in=343,855,935 out=93,416,053 elapsed=143.3s

  [11187/21087] intraday_19260.csv.gz  in=343,867,300 out=93,427,418 elapsed=143.3s

  [11188/21087] intraday_19261.csv.gz  in=343,878,826 out=93,438,944 elapsed=143.3s

  [11189/21087] intraday_19262.csv.gz  in=343,888,486 out=93,448,604 elapsed=143.3s

  [11190/21087] intraday_19263.csv.gz  in=343,902,642 out=93,462,760 elapsed=143.3s

  [11191/21087] intraday_19264.csv.gz  in=343,915,059 out=93,475,177 elapsed=143.3s

  [11192/21087] intraday_19265.csv.gz  in=343,926,906 out=93,487,024 elapsed=143.3s

  [11193/21087] intraday_19267.csv.gz  in=343,938,023 out=93,498,141 elapsed=143.4s

  [11194/21087] intraday_19266.csv.gz  in=343,948,069 out=93,508,187 elapsed=143.4s

  [11195/21087] intraday_19268.csv.gz  in=343,959,702 out=93,519,820 elapsed=143.4s

  [11196/21087] intraday_19269.csv.gz  in=343,971,301 out=93,531,419 elapsed=143.4s

  [11197/21087] intraday_1927.csv.gz  in=343,982,201 out=93,531,419 elapsed=143.4s

  [11198/21087] intraday_19271.csv.gz  in=343,991,914 out=93,541,132 elapsed=143.4s

  [11199/21087] intraday_19270.csv.gz  in=344,005,534 out=93,554,752 elapsed=143.4s

  [11200/21087] intraday_19272.csv.gz  in=344,015,584 out=93,564,802 elapsed=143.4s

  [11201/21087] intraday_19273.csv.gz  in=344,025,246 out=93,574,464 elapsed=143.4s

  [11202/21087] intraday_19274.csv.gz  in=344,035,186 out=93,584,404 elapsed=143.4s

  [11203/21087] intraday_19275.csv.gz  in=344,047,203 out=93,596,421 elapsed=143.5s

  [11204/21087] intraday_19277.csv.gz  in=344,060,300 out=93,609,518 elapsed=143.5s

  [11205/21087] intraday_19276.csv.gz  in=344,070,789 out=93,620,007 elapsed=143.5s

  [11206/21087] intraday_19278.csv.gz  in=344,082,919 out=93,632,137 elapsed=143.5s

  [11207/21087] intraday_1928.csv.gz  in=344,093,942 out=93,632,137 elapsed=143.5s

  [11208/21087] intraday_19279.csv.gz  in=344,104,803 out=93,642,998 elapsed=143.5s

  [11209/21087] intraday_19280.csv.gz  in=344,114,795 out=93,652,990 elapsed=143.5s

  [11210/21087] intraday_19281.csv.gz  in=344,127,362 out=93,665,557 elapsed=143.6s

  [11211/21087] intraday_19284.csv.gz  in=344,137,898 out=93,676,093 elapsed=143.6s

  [11212/21087] intraday_19283.csv.gz  in=344,150,569 out=93,688,764 elapsed=143.6s

  [11213/21087] intraday_19282.csv.gz  in=344,162,228 out=93,700,423 elapsed=143.6s

  [11214/21087] intraday_19285.csv.gz  in=344,173,087 out=93,711,282 elapsed=143.6s

  [11215/21087] intraday_19286.csv.gz  in=344,185,678 out=93,723,873 elapsed=143.6s

  [11216/21087] intraday_19287.csv.gz  in=344,197,441 out=93,735,636 elapsed=143.6s

  [11217/21087] intraday_19288.csv.gz  in=344,209,750 out=93,747,945 elapsed=143.6s

  [11218/21087] intraday_19289.csv.gz  in=344,221,923 out=93,760,118 elapsed=143.6s

  [11219/21087] intraday_1929.csv.gz  in=344,234,682 out=93,760,118 elapsed=143.6s

  [11220/21087] intraday_19290.csv.gz  in=344,244,291 out=93,769,727 elapsed=143.6s

  [11221/21087] intraday_19291.csv.gz  in=344,254,720 out=93,780,156 elapsed=143.7s

  [11222/21087] intraday_19292.csv.gz  in=344,266,280 out=93,791,716 elapsed=143.7s

  [11223/21087] intraday_19293.csv.gz  in=344,278,845 out=93,804,281 elapsed=143.7s

  [11224/21087] intraday_19294.csv.gz  in=344,290,769 out=93,816,205 elapsed=143.7s

  [11225/21087] intraday_19295.csv.gz  in=344,300,952 out=93,826,388 elapsed=143.7s

  [11226/21087] intraday_19296.csv.gz  in=344,312,869 out=93,838,305 elapsed=143.7s

  [11227/21087] intraday_19297.csv.gz  in=344,321,312 out=93,846,748 elapsed=143.7s

  [11228/21087] intraday_1930.csv.gz  in=344,332,980 out=93,846,748 elapsed=143.7s

  [11229/21087] intraday_19298.csv.gz  in=344,346,183 out=93,859,951 elapsed=143.7s

  [11230/21087] intraday_19299.csv.gz  in=344,359,971 out=93,873,739 elapsed=143.7s

  [11231/21087] intraday_19300.csv.gz  in=344,371,356 out=93,885,124 elapsed=143.7s

  [11232/21087] intraday_19303.csv.gz  in=344,381,148 out=93,894,916 elapsed=143.8s

  [11233/21087] intraday_19304.csv.gz  in=344,392,828 out=93,906,596 elapsed=143.8s

  [11234/21087] intraday_19301.csv.gz  in=344,405,834 out=93,919,602 elapsed=143.8s

  [11235/21087] intraday_19302.csv.gz  in=344,417,061 out=93,930,829 elapsed=143.8s

  [11236/21087] intraday_19306.csv.gz  in=344,428,500 out=93,942,238 elapsed=143.8s

  [11237/21087] intraday_19307.csv.gz  in=344,438,404 out=93,952,142 elapsed=143.8s

  [11238/21087] intraday_19308.csv.gz  in=344,449,851 out=93,963,589 elapsed=143.8s

  [11239/21087] intraday_19305.csv.gz  in=344,462,272 out=93,976,010 elapsed=143.9s

  [11240/21087] intraday_1931.csv.gz  in=344,471,684 out=93,976,010 elapsed=143.9s

  [11241/21087] intraday_19309.csv.gz  in=344,481,619 out=93,985,945 elapsed=143.9s

  [11242/21087] intraday_19310.csv.gz  in=344,493,429 out=93,997,755 elapsed=143.9s

  [11243/21087] intraday_19311.csv.gz  in=344,504,953 out=94,009,279 elapsed=143.9s

  [11244/21087] intraday_19312.csv.gz  in=344,516,169 out=94,020,495 elapsed=143.9s

  [11245/21087] intraday_19315.csv.gz  in=344,527,643 out=94,031,969 elapsed=144.0s

  [11246/21087] intraday_19313.csv.gz  in=344,539,765 out=94,044,091 elapsed=144.0s

  [11247/21087] intraday_19314.csv.gz  in=344,553,635 out=94,057,961 elapsed=144.0s

  [11248/21087] intraday_19316.csv.gz  in=344,568,567 out=94,072,893 elapsed=144.0s

  [11249/21087] intraday_1932.csv.gz  in=344,577,544 out=94,072,893 elapsed=144.0s

  [11250/21087] intraday_19317.csv.gz  in=344,592,034 out=94,087,383 elapsed=144.0s

  [11251/21087] intraday_19318.csv.gz  in=344,604,090 out=94,099,439 elapsed=144.0s

  [11252/21087] intraday_19319.csv.gz  in=344,616,100 out=94,111,449 elapsed=144.0s

  [11253/21087] intraday_19320.csv.gz  in=344,627,000 out=94,122,349 elapsed=144.0s

  [11254/21087] intraday_19321.csv.gz  in=344,637,809 out=94,133,158 elapsed=144.0s

  [11255/21087] intraday_19322.csv.gz  in=344,650,992 out=94,146,341 elapsed=144.0s

  [11256/21087] intraday_19323.csv.gz  in=344,662,218 out=94,157,567 elapsed=144.1s

  [11257/21087] intraday_19324.csv.gz  in=344,672,770 out=94,168,119 elapsed=144.1s

  [11258/21087] intraday_19325.csv.gz  in=344,686,241 out=94,181,590 elapsed=144.1s

  [11259/21087] intraday_19326.csv.gz  in=344,696,880 out=94,192,229 elapsed=144.1s

  [11260/21087] intraday_19327.csv.gz  in=344,708,631 out=94,203,980 elapsed=144.1s

  [11261/21087] intraday_19328.csv.gz  in=344,720,107 out=94,215,456 elapsed=144.1s

  [11262/21087] intraday_19329.csv.gz  in=344,732,897 out=94,228,246 elapsed=144.1s

  [11263/21087] intraday_1933.csv.gz  in=344,742,799 out=94,228,246 elapsed=144.1s

  [11264/21087] intraday_19331.csv.gz  in=344,753,898 out=94,239,345 elapsed=144.1s

  [11265/21087] intraday_19332.csv.gz  in=344,764,894 out=94,250,341 elapsed=144.1s

  [11266/21087] intraday_19330.csv.gz  in=344,775,639 out=94,261,086 elapsed=144.1s

  [11267/21087] intraday_19333.csv.gz  in=344,785,747 out=94,271,194 elapsed=144.1s

  [11268/21087] intraday_19334.csv.gz  in=344,797,165 out=94,282,612 elapsed=144.2s

  [11269/21087] intraday_19335.csv.gz  in=344,808,596 out=94,294,043 elapsed=144.2s

  [11270/21087] intraday_19336.csv.gz  in=344,820,446 out=94,305,893 elapsed=144.2s

  [11271/21087] intraday_19337.csv.gz  in=344,832,264 out=94,317,711 elapsed=144.2s

  [11272/21087] intraday_19338.csv.gz  in=344,846,501 out=94,331,948 elapsed=144.2s

  [11273/21087] intraday_1934.csv.gz  in=344,851,092 out=94,331,948 elapsed=144.2s

  [11274/21087] intraday_19339.csv.gz  in=344,871,230 out=94,350,940 elapsed=144.2s

  [11275/21087] intraday_19340.csv.gz  in=344,882,766 out=94,362,476 elapsed=144.2s

  [11276/21087] intraday_19341.csv.gz  in=344,894,773 out=94,374,483 elapsed=144.2s

  [11277/21087] intraday_19342.csv.gz  in=344,909,201 out=94,388,911 elapsed=144.2s

  [11278/21087] intraday_19343.csv.gz  in=344,923,012 out=94,402,722 elapsed=144.3s

  [11279/21087] intraday_19344.csv.gz  in=344,935,449 out=94,415,159 elapsed=144.3s

  [11280/21087] intraday_19346.csv.gz  in=344,947,123 out=94,426,833 elapsed=144.3s

  [11281/21087] intraday_19345.csv.gz  in=344,960,419 out=94,440,129 elapsed=144.3s

  [11282/21087] intraday_19347.csv.gz  in=344,972,799 out=94,452,509 elapsed=144.3s

  [11283/21087] intraday_19348.csv.gz  in=344,986,971 out=94,466,681 elapsed=144.3s

  [11284/21087] intraday_1935.csv.gz  in=345,001,847 out=94,466,681 elapsed=144.3s

  [11285/21087] intraday_19349.csv.gz  in=345,019,283 out=94,484,117 elapsed=144.3s

  [11286/21087] intraday_19350.csv.gz  in=345,030,336 out=94,495,170 elapsed=144.3s

  [11287/21087] intraday_19351.csv.gz  in=345,046,219 out=94,511,053 elapsed=144.4s

  [11288/21087] intraday_19353.csv.gz  in=345,058,692 out=94,523,526 elapsed=144.4s

  [11289/21087] intraday_19352.csv.gz  in=345,069,221 out=94,534,055 elapsed=144.4s

  [11290/21087] intraday_19354.csv.gz  in=345,078,708 out=94,543,542 elapsed=144.4s

  [11291/21087] intraday_19355.csv.gz  in=345,091,473 out=94,556,307 elapsed=144.4s

  [11292/21087] intraday_19356.csv.gz  in=345,101,970 out=94,566,804 elapsed=144.4s

  [11293/21087] intraday_19358.csv.gz  in=345,113,356 out=94,578,190 elapsed=144.4s

  [11294/21087] intraday_19357.csv.gz  in=345,126,218 out=94,591,052 elapsed=144.4s

  [11295/21087] intraday_1936.csv.gz  in=345,140,067 out=94,591,052 elapsed=144.4s

  [11296/21087] intraday_19359.csv.gz  in=345,151,847 out=94,602,832 elapsed=144.4s

  [11297/21087] intraday_19360.csv.gz  in=345,162,831 out=94,613,816 elapsed=144.5s

  [11298/21087] intraday_19361.csv.gz  in=345,173,733 out=94,624,718 elapsed=144.5s

  [11299/21087] intraday_19363.csv.gz  in=345,184,886 out=94,635,871 elapsed=144.5s

  [11300/21087] intraday_19362.csv.gz  in=345,197,211 out=94,648,196 elapsed=144.5s

  [11301/21087] intraday_19364.csv.gz  in=345,209,620 out=94,660,590 elapsed=144.5s

  [11302/21087] intraday_19367.csv.gz  in=345,221,637 out=94,672,607 elapsed=144.5s

  [11303/21087] intraday_19365.csv.gz  in=345,235,231 out=94,686,201 elapsed=144.5s

  [11304/21087] intraday_19366.csv.gz  in=345,249,003 out=94,699,973 elapsed=144.5s

  [11305/21087] intraday_19368.csv.gz  in=345,262,621 out=94,713,591 elapsed=144.5s

  [11306/21087] intraday_1937.csv.gz  in=345,274,660 out=94,713,591 elapsed=144.6s

  [11307/21087] intraday_19369.csv.gz  in=345,285,055 out=94,723,986 elapsed=144.6s

  [11308/21087] intraday_19371.csv.gz  in=345,296,145 out=94,735,076 elapsed=144.6s

  [11309/21087] intraday_19370.csv.gz  in=345,308,757 out=94,747,688 elapsed=144.6s

  [11310/21087] intraday_19372.csv.gz  in=345,320,975 out=94,759,906 elapsed=144.6s

  [11311/21087] intraday_19373.csv.gz  in=345,332,910 out=94,771,833 elapsed=144.6s

  [11312/21087] intraday_19374.csv.gz  in=345,339,686 out=94,778,609 elapsed=144.6s

  [11313/21087] intraday_19375.csv.gz  in=345,349,005 out=94,787,928 elapsed=144.6s

  [11314/21087] intraday_19377.csv.gz  in=345,349,806 out=94,788,729 elapsed=144.6s

  [11315/21087] intraday_19376.csv.gz  in=345,355,148 out=94,794,071 elapsed=144.6s

  [11316/21087] intraday_19380.csv.gz  in=345,355,485 out=94,794,408 elapsed=144.7s

  [11317/21087] intraday_19379.csv.gz  in=345,359,515 out=94,798,322 elapsed=144.7s

  [11318/21087] intraday_19378.csv.gz  in=345,365,388 out=94,803,382 elapsed=144.7s

  [11319/21087] intraday_1938.csv.gz  in=345,376,974 out=94,803,382 elapsed=144.7s

  [11320/21087] intraday_19381.csv.gz  in=345,377,356 out=94,803,764 elapsed=144.7s

  [11321/21087] intraday_19382.csv.gz  in=345,377,965 out=94,804,373 elapsed=144.7s

  [11322/21087] intraday_19384.csv.gz  in=345,378,306 out=94,804,714 elapsed=144.7s

  [11323/21087] intraday_19383.csv.gz  in=345,378,765 out=94,805,173 elapsed=144.7s

  [11324/21087] intraday_19385.csv.gz  in=345,379,536 out=94,805,944 elapsed=144.7s

  [11325/21087] intraday_19386.csv.gz  in=345,379,872 out=94,806,280 elapsed=144.7s

  [11326/21087] intraday_19387.csv.gz  in=345,380,362 out=94,806,770 elapsed=144.7s

  [11327/21087] intraday_19388.csv.gz  in=345,380,745 out=94,807,153 elapsed=144.7s

  [11328/21087] intraday_19389.csv.gz  in=345,382,595 out=94,808,734 elapsed=144.7s

  [11329/21087] intraday_19390.csv.gz  in=345,382,859 out=94,808,998 elapsed=144.7s

  [11330/21087] intraday_1939.csv.gz  in=345,396,177 out=94,808,998 elapsed=144.7s

  [11331/21087] intraday_19391.csv.gz  in=345,396,603 out=94,809,424 elapsed=144.7s

  [11332/21087] intraday_19392.csv.gz  in=345,396,806 out=94,809,627 elapsed=144.7s

  [11333/21087] intraday_19393.csv.gz  in=345,397,330 out=94,810,151 elapsed=144.7s

  [11334/21087] intraday_19394.csv.gz  in=345,397,763 out=94,810,584 elapsed=144.7s

  [11335/21087] intraday_19395.csv.gz  in=345,398,065 out=94,810,886 elapsed=144.7s

  [11336/21087] intraday_19397.csv.gz  in=345,398,460 out=94,811,281 elapsed=144.8s

  [11337/21087] intraday_19396.csv.gz  in=345,398,759 out=94,811,580 elapsed=144.8s

  [11338/21087] intraday_19399.csv.gz  in=345,399,061 out=94,811,882 elapsed=144.8s

  [11339/21087] intraday_19398.csv.gz  in=345,399,861 out=94,812,627 elapsed=144.8s

  [11340/21087] intraday_19400.csv.gz  in=345,400,094 out=94,812,860 elapsed=144.8s

  [11341/21087] intraday_19402.csv.gz  in=345,400,479 out=94,813,245 elapsed=144.8s

  [11342/21087] intraday_1940.csv.gz  in=345,415,007 out=94,813,245 elapsed=144.8s

  [11343/21087] intraday_19403.csv.gz  in=345,415,169 out=94,813,407 elapsed=144.8s

  [11344/21087] intraday_19404.csv.gz  in=345,415,208 out=94,813,446 elapsed=144.8s

  [11345/21087] intraday_19401.csv.gz  in=345,430,365 out=94,826,538 elapsed=144.8s

  [11346/21087] intraday_19405.csv.gz  in=345,430,999 out=94,827,172 elapsed=144.8s

  [11347/21087] intraday_19406.csv.gz  in=345,431,771 out=94,827,944 elapsed=144.8s

  [11348/21087] intraday_19407.csv.gz  in=345,432,094 out=94,828,267 elapsed=144.8s

  [11349/21087] intraday_19409.csv.gz  in=345,432,235 out=94,828,408 elapsed=144.8s

  [11350/21087] intraday_19408.csv.gz  in=345,432,519 out=94,828,692 elapsed=144.8s

  [11351/21087] intraday_19410.csv.gz  in=345,432,775 out=94,828,948 elapsed=144.8s

  [11352/21087] intraday_1941.csv.gz  in=345,445,114 out=94,828,948 elapsed=144.8s

  [11353/21087] intraday_19412.csv.gz  in=345,446,076 out=94,829,910 elapsed=144.8s

  [11354/21087] intraday_19413.csv.gz  in=345,446,352 out=94,830,186 elapsed=144.9s

  [11355/21087] intraday_19411.csv.gz  in=345,453,223 out=94,836,123 elapsed=144.9s

  [11356/21087] intraday_19416.csv.gz  in=345,453,270 out=94,836,170 elapsed=144.9s

  [11357/21087] intraday_19417.csv.gz  in=345,453,479 out=94,836,379 elapsed=144.9s

  [11358/21087] intraday_19414.csv.gz  in=345,453,602 out=94,836,502 elapsed=144.9s

  [11359/21087] intraday_19415.csv.gz  in=345,453,903 out=94,836,803 elapsed=144.9s

  [11360/21087] intraday_19418.csv.gz  in=345,454,018 out=94,836,918 elapsed=144.9s

  [11361/21087] intraday_19419.csv.gz  in=345,454,596 out=94,837,496 elapsed=144.9s

  [11362/21087] intraday_19420.csv.gz  in=345,455,014 out=94,837,914 elapsed=144.9s

  [11363/21087] intraday_19421.csv.gz  in=345,455,167 out=94,838,067 elapsed=144.9s

  [11364/21087] intraday_1942.csv.gz  in=345,467,353 out=94,838,067 elapsed=144.9s

  [11365/21087] intraday_19422.csv.gz  in=345,467,428 out=94,838,142 elapsed=144.9s

  [11366/21087] intraday_19423.csv.gz  in=345,467,525 out=94,838,239 elapsed=144.9s

  [11367/21087] intraday_19424.csv.gz  in=345,468,262 out=94,838,976 elapsed=144.9s

  [11368/21087] intraday_19426.csv.gz  in=345,468,352 out=94,839,066 elapsed=144.9s

  [11369/21087] intraday_19425.csv.gz  in=345,469,628 out=94,840,342 elapsed=144.9s

  [11370/21087] intraday_19427.csv.gz  in=345,473,926 out=94,844,443 elapsed=144.9s

  [11371/21087] intraday_19429.csv.gz  in=345,474,545 out=94,845,062 elapsed=145.0s

  [11372/21087] intraday_19430.csv.gz  in=345,476,630 out=94,846,944 elapsed=145.0s

  [11373/21087] intraday_1943.csv.gz  in=345,490,691 out=94,846,944 elapsed=145.0s

  [11374/21087] intraday_19431.csv.gz  in=345,491,304 out=94,847,557 elapsed=145.0s

  [11375/21087] intraday_19428.csv.gz  in=345,507,460 out=94,862,747 elapsed=145.0s

  [11376/21087] intraday_19432.csv.gz  in=345,507,585 out=94,862,872 elapsed=145.0s

  [11377/21087] intraday_19433.csv.gz  in=345,507,719 out=94,863,006 elapsed=145.0s

  [11378/21087] intraday_19434.csv.gz  in=345,507,910 out=94,863,197 elapsed=145.0s

  [11379/21087] intraday_19436.csv.gz  in=345,508,027 out=94,863,314 elapsed=145.0s

  [11380/21087] intraday_19435.csv.gz  in=345,508,420 out=94,863,707 elapsed=145.0s

  [11381/21087] intraday_19437.csv.gz  in=345,508,822 out=94,864,109 elapsed=145.0s

  [11382/21087] intraday_19439.csv.gz  in=345,508,903 out=94,864,190 elapsed=145.0s

  [11383/21087] intraday_19438.csv.gz  in=345,512,578 out=94,867,579 elapsed=145.0s

  [11384/21087] intraday_1944.csv.gz  in=345,528,296 out=94,867,579 elapsed=145.0s

  [11385/21087] intraday_19441.csv.gz  in=345,529,067 out=94,868,350 elapsed=145.0s

  [11386/21087] intraday_19440.csv.gz  in=345,532,417 out=94,871,700 elapsed=145.0s

  [11387/21087] intraday_19442.csv.gz  in=345,536,275 out=94,874,901 elapsed=145.1s

  [11388/21087] intraday_19443.csv.gz  in=345,536,417 out=94,875,043 elapsed=145.1s

  [11389/21087] intraday_19444.csv.gz  in=345,536,599 out=94,875,225 elapsed=145.1s

  [11390/21087] intraday_19445.csv.gz  in=345,537,069 out=94,875,695 elapsed=145.1s

  [11391/21087] intraday_19446.csv.gz  in=345,537,418 out=94,876,044 elapsed=145.1s

  [11392/21087] intraday_19447.csv.gz  in=345,537,691 out=94,876,317 elapsed=145.1s

  [11393/21087] intraday_19449.csv.gz  in=345,537,864 out=94,876,490 elapsed=145.1s

  [11394/21087] intraday_19450.csv.gz  in=345,538,115 out=94,876,741 elapsed=145.1s

  [11395/21087] intraday_19448.csv.gz  in=345,540,187 out=94,878,813 elapsed=145.1s

  [11396/21087] intraday_1945.csv.gz  in=345,549,132 out=94,878,813 elapsed=145.1s

  [11397/21087] intraday_19451.csv.gz  in=345,549,809 out=94,879,490 elapsed=145.1s

  [11398/21087] intraday_19452.csv.gz  in=345,549,993 out=94,879,674 elapsed=145.1s

  [11399/21087] intraday_19453.csv.gz  in=345,550,277 out=94,879,958 elapsed=145.1s

  [11400/21087] intraday_19454.csv.gz  in=345,550,470 out=94,880,151 elapsed=145.1s

  [11401/21087] intraday_19455.csv.gz  in=345,550,884 out=94,880,565 elapsed=145.1s

  [11402/21087] intraday_19456.csv.gz  in=345,551,145 out=94,880,826 elapsed=145.1s

  [11403/21087] intraday_19457.csv.gz  in=345,551,314 out=94,880,995 elapsed=145.1s

  [11404/21087] intraday_19458.csv.gz  in=345,552,189 out=94,881,870 elapsed=145.1s

  [11405/21087] intraday_19459.csv.gz  in=345,553,340 out=94,883,021 elapsed=145.1s

  [11406/21087] intraday_19460.csv.gz  in=345,554,108 out=94,883,789 elapsed=145.1s

  [11407/21087] intraday_19461.csv.gz  in=345,555,003 out=94,884,684 elapsed=145.2s

  [11408/21087] intraday_1946.csv.gz  in=345,572,308 out=94,884,684 elapsed=145.2s

  [11409/21087] intraday_19462.csv.gz  in=345,572,631 out=94,885,007 elapsed=145.2s

  [11410/21087] intraday_19463.csv.gz  in=345,573,102 out=94,885,478 elapsed=145.2s

  [11411/21087] intraday_19464.csv.gz  in=345,573,337 out=94,885,713 elapsed=145.2s

  [11412/21087] intraday_19465.csv.gz  in=345,574,178 out=94,886,554 elapsed=145.2s

  [11413/21087] intraday_19466.csv.gz  in=345,574,373 out=94,886,749 elapsed=145.2s

  [11414/21087] intraday_19467.csv.gz  in=345,575,436 out=94,887,812 elapsed=145.2s

  [11415/21087] intraday_19468.csv.gz  in=345,575,698 out=94,888,074 elapsed=145.2s

  [11416/21087] intraday_19469.csv.gz  in=345,576,559 out=94,888,935 elapsed=145.2s

  [11417/21087] intraday_1947.csv.gz  in=345,590,277 out=94,888,935 elapsed=145.2s

  [11418/21087] intraday_19470.csv.gz  in=345,590,489 out=94,889,147 elapsed=145.2s

  [11419/21087] intraday_19471.csv.gz  in=345,590,579 out=94,889,237 elapsed=145.2s

  [11420/21087] intraday_19473.csv.gz  in=345,590,743 out=94,889,401 elapsed=145.2s

  [11421/21087] intraday_19474.csv.gz  in=345,591,375 out=94,890,033 elapsed=145.2s

  [11422/21087] intraday_19475.csv.gz  in=345,591,491 out=94,890,149 elapsed=145.2s

  [11423/21087] intraday_19472.csv.gz  in=345,596,875 out=94,895,500 elapsed=145.2s

  [11424/21087] intraday_19476.csv.gz  in=345,597,021 out=94,895,646 elapsed=145.2s

  [11425/21087] intraday_19478.csv.gz  in=345,598,061 out=94,896,686 elapsed=145.2s

  [11426/21087] intraday_19479.csv.gz  in=345,598,843 out=94,897,468 elapsed=145.2s

  [11427/21087] intraday_19480.csv.gz  in=345,599,230 out=94,897,855 elapsed=145.3s

  [11428/21087] intraday_1948.csv.gz  in=345,614,630 out=94,897,855 elapsed=145.3s

  [11429/21087] intraday_19477.csv.gz  in=345,629,174 out=94,911,103 elapsed=145.3s

  [11430/21087] intraday_19481.csv.gz  in=345,629,514 out=94,911,443 elapsed=145.3s

  [11431/21087] intraday_19482.csv.gz  in=345,629,953 out=94,911,882 elapsed=145.3s

  [11432/21087] intraday_19483.csv.gz  in=345,630,027 out=94,911,956 elapsed=145.3s

  [11433/21087] intraday_19484.csv.gz  in=345,630,614 out=94,912,543 elapsed=145.3s

  [11434/21087] intraday_19486.csv.gz  in=345,631,898 out=94,913,827 elapsed=145.3s

  [11435/21087] intraday_19485.csv.gz  in=345,633,954 out=94,915,883 elapsed=145.3s

  [11436/21087] intraday_19487.csv.gz  in=345,634,867 out=94,916,796 elapsed=145.3s

  [11437/21087] intraday_19488.csv.gz  in=345,635,929 out=94,916,983 elapsed=145.3s

  [11438/21087] intraday_19489.csv.gz  in=345,636,756 out=94,917,810 elapsed=145.3s

  [11439/21087] intraday_19490.csv.gz  in=345,637,506 out=94,918,560 elapsed=145.3s

  [11440/21087] intraday_1949.csv.gz  in=345,648,173 out=94,918,560 elapsed=145.3s

  [11441/21087] intraday_19492.csv.gz  in=345,649,704 out=94,920,091 elapsed=145.3s

  [11442/21087] intraday_19491.csv.gz  in=345,651,203 out=94,921,590 elapsed=145.3s

  [11443/21087] intraday_19493.csv.gz  in=345,651,354 out=94,921,741 elapsed=145.4s

  [11444/21087] intraday_19494.csv.gz  in=345,652,408 out=94,922,795 elapsed=145.4s

  [11445/21087] intraday_19496.csv.gz  in=345,652,832 out=94,923,219 elapsed=145.4s

  [11446/21087] intraday_19495.csv.gz  in=345,653,148 out=94,923,535 elapsed=145.4s

  [11447/21087] intraday_19497.csv.gz  in=345,653,215 out=94,923,602 elapsed=145.4s

  [11448/21087] intraday_19498.csv.gz  in=345,653,546 out=94,923,933 elapsed=145.4s

  [11449/21087] intraday_19499.csv.gz  in=345,653,729 out=94,924,116 elapsed=145.4s

  [11450/21087] intraday_19500.csv.gz  in=345,654,178 out=94,924,565 elapsed=145.4s

  [11451/21087] intraday_19501.csv.gz  in=345,654,651 out=94,925,038 elapsed=145.4s

  [11452/21087] intraday_1950.csv.gz  in=345,667,693 out=94,925,038 elapsed=145.4s

  [11453/21087] intraday_19502.csv.gz  in=345,668,539 out=94,925,884 elapsed=145.4s

  [11454/21087] intraday_19504.csv.gz  in=345,668,891 out=94,926,236 elapsed=145.4s

  [11455/21087] intraday_19503.csv.gz  in=345,670,572 out=94,927,917 elapsed=145.4s

  [11456/21087] intraday_19505.csv.gz  in=345,671,014 out=94,928,359 elapsed=145.4s

  [11457/21087] intraday_19506.csv.gz  in=345,671,572 out=94,928,917 elapsed=145.4s

  [11458/21087] intraday_19507.csv.gz  in=345,671,970 out=94,929,315 elapsed=145.4s

  [11459/21087] intraday_19509.csv.gz  in=345,672,267 out=94,929,612 elapsed=145.4s

  [11460/21087] intraday_19508.csv.gz  in=345,672,645 out=94,929,990 elapsed=145.4s

  [11461/21087] intraday_19510.csv.gz  in=345,673,182 out=94,930,527 elapsed=145.4s

  [11462/21087] intraday_19511.csv.gz  in=345,673,406 out=94,930,751 elapsed=145.4s

  [11463/21087] intraday_19512.csv.gz  in=345,674,174 out=94,931,519 elapsed=145.5s

  [11464/21087] intraday_1951.csv.gz  in=345,692,952 out=94,931,519 elapsed=145.5s

  [11465/21087] intraday_19514.csv.gz  in=345,693,136 out=94,931,703 elapsed=145.5s

  [11466/21087] intraday_19513.csv.gz  in=345,693,433 out=94,932,000 elapsed=145.5s

  [11467/21087] intraday_19515.csv.gz  in=345,693,689 out=94,932,256 elapsed=145.5s

  [11468/21087] intraday_19517.csv.gz  in=345,693,984 out=94,932,551 elapsed=145.5s

  [11469/21087] intraday_19518.csv.gz  in=345,694,355 out=94,932,922 elapsed=145.5s

  [11470/21087] intraday_19519.csv.gz  in=345,694,726 out=94,933,293 elapsed=145.5s

  [11471/21087] intraday_1952.csv.gz  in=345,707,220 out=94,933,293 elapsed=145.5s

  [11472/21087] intraday_19516.csv.gz  in=345,719,401 out=94,945,241 elapsed=145.5s

  [11473/21087] intraday_19521.csv.gz  in=345,731,767 out=94,957,607 elapsed=145.5s

  [11474/21087] intraday_19520.csv.gz  in=345,747,834 out=94,973,674 elapsed=145.5s

  [11475/21087] intraday_19523.csv.gz  in=345,757,049 out=94,982,889 elapsed=145.5s

  [11476/21087] intraday_19522.csv.gz  in=345,770,082 out=94,995,922 elapsed=145.5s

  [11477/21087] intraday_19524.csv.gz  in=345,783,218 out=95,009,058 elapsed=145.6s

  [11478/21087] intraday_19525.csv.gz  in=345,797,414 out=95,023,254 elapsed=145.6s

  [11479/21087] intraday_19526.csv.gz  in=345,809,158 out=95,034,998 elapsed=145.6s

  [11480/21087] intraday_19527.csv.gz  in=345,821,203 out=95,047,043 elapsed=145.6s

  [11481/21087] intraday_19528.csv.gz  in=345,833,958 out=95,059,798 elapsed=145.6s

  [11482/21087] intraday_19529.csv.gz  in=345,845,969 out=95,071,809 elapsed=145.6s

  [11483/21087] intraday_19530.csv.gz  in=345,855,749 out=95,081,589 elapsed=145.6s

  [11484/21087] intraday_1953.csv.gz  in=345,869,671 out=95,081,589 elapsed=145.6s

  [11485/21087] intraday_19531.csv.gz  in=345,881,117 out=95,093,035 elapsed=145.6s

  [11486/21087] intraday_19534.csv.gz  in=345,891,696 out=95,103,614 elapsed=145.7s

  [11487/21087] intraday_19532.csv.gz  in=345,927,157 out=95,135,594 elapsed=145.7s

  [11488/21087] intraday_19533.csv.gz  in=345,936,916 out=95,145,353 elapsed=145.7s

  [11489/21087] intraday_19535.csv.gz  in=345,946,173 out=95,154,610 elapsed=145.7s

  [11490/21087] intraday_19536.csv.gz  in=345,960,550 out=95,168,987 elapsed=145.7s

  [11491/21087] intraday_19539.csv.gz  in=345,970,408 out=95,178,845 elapsed=145.7s

  [11492/21087] intraday_19537.csv.gz  in=345,983,126 out=95,191,563 elapsed=145.7s

  [11493/21087] intraday_19538.csv.gz  in=345,992,831 out=95,201,268 elapsed=145.7s

  [11494/21087] intraday_1954.csv.gz  in=346,005,167 out=95,201,268 elapsed=145.8s

  [11495/21087] intraday_19541.csv.gz  in=346,017,404 out=95,213,505 elapsed=145.8s

  [11496/21087] intraday_19540.csv.gz  in=346,029,239 out=95,225,340 elapsed=145.8s

  [11497/21087] intraday_19542.csv.gz  in=346,041,822 out=95,237,923 elapsed=145.8s

  [11498/21087] intraday_19543.csv.gz  in=346,052,295 out=95,248,396 elapsed=145.8s

  [11499/21087] intraday_19544.csv.gz  in=346,063,762 out=95,259,863 elapsed=145.8s

  [11500/21087] intraday_19545.csv.gz  in=346,074,933 out=95,271,034 elapsed=145.8s

  [11501/21087] intraday_19546.csv.gz  in=346,087,276 out=95,283,377 elapsed=145.8s

  [11502/21087] intraday_19547.csv.gz  in=346,097,541 out=95,293,642 elapsed=145.8s

  [11503/21087] intraday_19549.csv.gz  in=346,110,119 out=95,306,220 elapsed=145.8s

  [11504/21087] intraday_19548.csv.gz  in=346,123,992 out=95,320,093 elapsed=145.9s

  [11505/21087] intraday_1955.csv.gz  in=346,137,363 out=95,320,093 elapsed=145.9s

  [11506/21087] intraday_19550.csv.gz  in=346,150,250 out=95,332,980 elapsed=145.9s

  [11507/21087] intraday_19551.csv.gz  in=346,161,150 out=95,343,880 elapsed=145.9s

  [11508/21087] intraday_19552.csv.gz  in=346,172,982 out=95,355,712 elapsed=145.9s

  [11509/21087] intraday_19553.csv.gz  in=346,184,657 out=95,367,387 elapsed=145.9s

  [11510/21087] intraday_19554.csv.gz  in=346,197,215 out=95,379,945 elapsed=145.9s

  [11511/21087] intraday_19555.csv.gz  in=346,210,402 out=95,393,132 elapsed=145.9s

  [11512/21087] intraday_19556.csv.gz  in=346,220,656 out=95,403,386 elapsed=145.9s

  [11513/21087] intraday_19557.csv.gz  in=346,231,341 out=95,414,071 elapsed=145.9s

  [11514/21087] intraday_19558.csv.gz  in=346,241,538 out=95,424,268 elapsed=145.9s

  [11515/21087] intraday_19559.csv.gz  in=346,251,551 out=95,434,281 elapsed=146.0s

  [11516/21087] intraday_1956.csv.gz  in=346,263,289 out=95,434,281 elapsed=146.0s

  [11517/21087] intraday_19561.csv.gz  in=346,273,670 out=95,444,662 elapsed=146.0s

  [11518/21087] intraday_19560.csv.gz  in=346,286,444 out=95,457,436 elapsed=146.0s

  [11519/21087] intraday_19563.csv.gz  in=346,298,642 out=95,469,634 elapsed=146.0s

  [11520/21087] intraday_19562.csv.gz  in=346,312,772 out=95,483,764 elapsed=146.0s

  [11521/21087] intraday_19565.csv.gz  in=346,322,664 out=95,493,656 elapsed=146.0s

  [11522/21087] intraday_19564.csv.gz  in=346,334,239 out=95,505,231 elapsed=146.0s

  [11523/21087] intraday_19566.csv.gz  in=346,346,828 out=95,517,820 elapsed=146.0s

  [11524/21087] intraday_19567.csv.gz  in=346,357,516 out=95,528,508 elapsed=146.1s

  [11525/21087] intraday_1957.csv.gz  in=346,372,511 out=95,528,508 elapsed=146.1s

  [11526/21087] intraday_19569.csv.gz  in=346,382,690 out=95,538,687 elapsed=146.1s

  [11527/21087] intraday_19568.csv.gz  in=346,396,384 out=95,552,381 elapsed=146.1s

  [11528/21087] intraday_19571.csv.gz  in=346,408,262 out=95,564,259 elapsed=146.1s

  [11529/21087] intraday_19573.csv.gz  in=346,419,161 out=95,575,158 elapsed=146.1s

  [11530/21087] intraday_19570.csv.gz  in=346,429,798 out=95,585,795 elapsed=146.1s

  [11531/21087] intraday_19572.csv.gz  in=346,443,883 out=95,599,880 elapsed=146.2s

  [11532/21087] intraday_19574.csv.gz  in=346,457,047 out=95,613,044 elapsed=146.2s

  [11533/21087] intraday_19576.csv.gz  in=346,466,788 out=95,622,785 elapsed=146.2s

  [11534/21087] intraday_19575.csv.gz  in=346,476,628 out=95,632,625 elapsed=146.2s

  [11535/21087] intraday_19577.csv.gz  in=346,488,194 out=95,644,191 elapsed=146.2s

  [11536/21087] intraday_1958.csv.gz  in=346,505,858 out=95,644,191 elapsed=146.2s

  [11537/21087] intraday_19578.csv.gz  in=346,518,889 out=95,657,222 elapsed=146.2s

  [11538/21087] intraday_19579.csv.gz  in=346,530,458 out=95,668,791 elapsed=146.2s

  [11539/21087] intraday_19581.csv.gz  in=346,541,068 out=95,679,401 elapsed=146.3s

  [11540/21087] intraday_19582.csv.gz  in=346,551,049 out=95,689,382 elapsed=146.3s

  [11541/21087] intraday_19580.csv.gz  in=346,562,374 out=95,700,707 elapsed=146.3s

  [11542/21087] intraday_19583.csv.gz  in=346,572,925 out=95,711,258 elapsed=146.3s

  [11543/21087] intraday_19585.csv.gz  in=346,586,397 out=95,724,730 elapsed=146.3s

  [11544/21087] intraday_19586.csv.gz  in=346,598,795 out=95,737,128 elapsed=146.3s

  [11545/21087] intraday_19584.csv.gz  in=346,613,406 out=95,751,739 elapsed=146.3s

  [11546/21087] intraday_19587.csv.gz  in=346,625,843 out=95,764,176 elapsed=146.3s

  [11547/21087] intraday_1959.csv.gz  in=346,638,133 out=95,764,176 elapsed=146.4s

  [11548/21087] intraday_19588.csv.gz  in=346,648,376 out=95,774,419 elapsed=146.4s

  [11549/21087] intraday_19590.csv.gz  in=346,661,159 out=95,787,202 elapsed=146.4s

  [11550/21087] intraday_19589.csv.gz  in=346,672,786 out=95,798,829 elapsed=146.4s

  [11551/21087] intraday_19591.csv.gz  in=346,682,592 out=95,808,635 elapsed=146.4s

  [11552/21087] intraday_19593.csv.gz  in=346,692,808 out=95,818,851 elapsed=146.4s

  [11553/21087] intraday_19592.csv.gz  in=346,704,720 out=95,830,763 elapsed=146.4s

  [11554/21087] intraday_19594.csv.gz  in=346,715,834 out=95,841,877 elapsed=146.4s

  [11555/21087] intraday_19595.csv.gz  in=346,727,399 out=95,853,442 elapsed=146.4s

  [11556/21087] intraday_19596.csv.gz  in=346,740,856 out=95,866,899 elapsed=146.5s

  [11557/21087] intraday_19597.csv.gz  in=346,752,510 out=95,878,553 elapsed=146.5s

  [11558/21087] intraday_19598.csv.gz  in=346,764,909 out=95,890,952 elapsed=146.5s

  [11559/21087] intraday_19599.csv.gz  in=346,775,591 out=95,901,634 elapsed=146.5s

  [11560/21087] intraday_1960.csv.gz  in=346,786,228 out=95,901,634 elapsed=146.5s

  [11561/21087] intraday_19600.csv.gz  in=346,798,254 out=95,913,660 elapsed=146.5s

  [11562/21087] intraday_19603.csv.gz  in=346,809,723 out=95,925,129 elapsed=146.5s

  [11563/21087] intraday_19601.csv.gz  in=346,823,750 out=95,939,156 elapsed=146.5s

  [11564/21087] intraday_19602.csv.gz  in=346,841,426 out=95,956,832 elapsed=146.5s

  [11565/21087] intraday_19604.csv.gz  in=346,855,425 out=95,970,831 elapsed=146.6s

  [11566/21087] intraday_19605.csv.gz  in=346,865,522 out=95,980,928 elapsed=146.6s

  [11567/21087] intraday_19606.csv.gz  in=346,878,814 out=95,994,220 elapsed=146.6s

  [11568/21087] intraday_19607.csv.gz  in=346,890,804 out=96,006,210 elapsed=146.6s

  [11569/21087] intraday_19608.csv.gz  in=346,902,369 out=96,017,775 elapsed=146.6s

  [11570/21087] intraday_1961.csv.gz  in=346,914,520 out=96,017,775 elapsed=146.6s

  [11571/21087] intraday_19609.csv.gz  in=346,924,711 out=96,027,966 elapsed=146.6s

  [11572/21087] intraday_19610.csv.gz  in=346,939,734 out=96,042,989 elapsed=146.6s

  [11573/21087] intraday_19611.csv.gz  in=346,949,905 out=96,053,160 elapsed=146.6s

  [11574/21087] intraday_19612.csv.gz  in=346,961,110 out=96,064,365 elapsed=146.7s

  [11575/21087] intraday_19613.csv.gz  in=346,973,214 out=96,076,469 elapsed=146.7s

  [11576/21087] intraday_19614.csv.gz  in=346,986,143 out=96,089,398 elapsed=146.7s

  [11577/21087] intraday_19615.csv.gz  in=346,998,111 out=96,101,366 elapsed=146.7s

  [11578/21087] intraday_19616.csv.gz  in=347,008,116 out=96,111,371 elapsed=146.7s

  [11579/21087] intraday_19617.csv.gz  in=347,020,111 out=96,123,366 elapsed=146.7s

  [11580/21087] intraday_19618.csv.gz  in=347,030,521 out=96,133,776 elapsed=146.7s

  [11581/21087] intraday_19619.csv.gz  in=347,042,132 out=96,145,387 elapsed=146.7s

  [11582/21087] intraday_1962.csv.gz  in=347,053,880 out=96,145,387 elapsed=146.7s

  [11583/21087] intraday_19620.csv.gz  in=347,066,287 out=96,157,794 elapsed=146.7s

  [11584/21087] intraday_19621.csv.gz  in=347,079,740 out=96,171,247 elapsed=146.7s

  [11585/21087] intraday_19622.csv.gz  in=347,091,544 out=96,183,051 elapsed=146.8s

  [11586/21087] intraday_19623.csv.gz  in=347,103,259 out=96,194,766 elapsed=146.8s

  [11587/21087] intraday_19624.csv.gz  in=347,117,323 out=96,208,830 elapsed=146.8s

  [11588/21087] intraday_19625.csv.gz  in=347,129,064 out=96,220,379 elapsed=146.8s

  [11589/21087] intraday_19626.csv.gz  in=347,140,336 out=96,231,651 elapsed=146.8s

  [11590/21087] intraday_19627.csv.gz  in=347,154,549 out=96,245,864 elapsed=146.8s

  [11591/21087] intraday_19628.csv.gz  in=347,169,225 out=96,260,540 elapsed=146.8s

  [11592/21087] intraday_1963.csv.gz  in=347,182,079 out=96,260,540 elapsed=146.8s

  [11593/21087] intraday_19629.csv.gz  in=347,195,256 out=96,273,717 elapsed=146.8s

  [11594/21087] intraday_19630.csv.gz  in=347,208,406 out=96,286,867 elapsed=146.8s

  [11595/21087] intraday_19632.csv.gz  in=347,219,204 out=96,297,665 elapsed=146.9s

  [11596/21087] intraday_19631.csv.gz  in=347,235,133 out=96,313,594 elapsed=146.9s

  [11597/21087] intraday_19633.csv.gz  in=347,252,416 out=96,330,877 elapsed=146.9s

  [11598/21087] intraday_19634.csv.gz  in=347,269,129 out=96,347,590 elapsed=146.9s

  [11599/21087] intraday_19635.csv.gz  in=347,283,207 out=96,361,668 elapsed=146.9s

  [11600/21087] intraday_19637.csv.gz  in=347,294,500 out=96,372,961 elapsed=146.9s

  [11601/21087] intraday_19636.csv.gz  in=347,310,020 out=96,388,481 elapsed=146.9s

  [11602/21087] intraday_19638.csv.gz  in=347,322,592 out=96,401,053 elapsed=146.9s

  [11603/21087] intraday_19639.csv.gz  in=347,334,902 out=96,413,363 elapsed=146.9s

  [11604/21087] intraday_1964.csv.gz  in=347,349,583 out=96,413,363 elapsed=146.9s

  [11605/21087] intraday_19640.csv.gz  in=347,360,834 out=96,424,614 elapsed=147.0s

  [11606/21087] intraday_19641.csv.gz  in=347,370,987 out=96,434,767 elapsed=147.0s

  [11607/21087] intraday_19642.csv.gz  in=347,383,834 out=96,447,614 elapsed=147.0s

  [11608/21087] intraday_19643.csv.gz  in=347,394,539 out=96,458,319 elapsed=147.0s

  [11609/21087] intraday_19644.csv.gz  in=347,409,953 out=96,473,733 elapsed=147.0s

  [11610/21087] intraday_19645.csv.gz  in=347,419,055 out=96,482,835 elapsed=147.0s

  [11611/21087] intraday_19647.csv.gz  in=347,429,904 out=96,493,684 elapsed=147.0s

  [11612/21087] intraday_19646.csv.gz  in=347,442,119 out=96,505,899 elapsed=147.0s

  [11613/21087] intraday_19648.csv.gz  in=347,455,329 out=96,519,109 elapsed=147.0s

  [11614/21087] intraday_19649.csv.gz  in=347,465,831 out=96,529,611 elapsed=147.0s

  [11615/21087] intraday_1965.csv.gz  in=347,479,586 out=96,529,611 elapsed=147.1s

  [11616/21087] intraday_19651.csv.gz  in=347,492,915 out=96,542,940 elapsed=147.1s

  [11617/21087] intraday_19650.csv.gz  in=347,508,227 out=96,558,252 elapsed=147.1s

  [11618/21087] intraday_19652.csv.gz  in=347,520,197 out=96,570,222 elapsed=147.1s

  [11619/21087] intraday_19653.csv.gz  in=347,533,775 out=96,583,800 elapsed=147.1s

  [11620/21087] intraday_19654.csv.gz  in=347,546,249 out=96,596,274 elapsed=147.1s

  [11621/21087] intraday_19655.csv.gz  in=347,558,353 out=96,608,378 elapsed=147.1s

  [11622/21087] intraday_19657.csv.gz  in=347,567,687 out=96,617,712 elapsed=147.1s

  [11623/21087] intraday_19656.csv.gz  in=347,579,824 out=96,629,849 elapsed=147.1s

  [11624/21087] intraday_19658.csv.gz  in=347,593,078 out=96,643,103 elapsed=147.1s

  [11625/21087] intraday_19659.csv.gz  in=347,601,909 out=96,651,934 elapsed=147.2s

  [11626/21087] intraday_1966.csv.gz  in=347,613,144 out=96,651,934 elapsed=147.2s

  [11627/21087] intraday_19660.csv.gz  in=347,622,581 out=96,661,371 elapsed=147.2s

  [11628/21087] intraday_19661.csv.gz  in=347,632,704 out=96,671,494 elapsed=147.2s

  [11629/21087] intraday_19663.csv.gz  in=347,645,933 out=96,684,723 elapsed=147.2s

  [11630/21087] intraday_19662.csv.gz  in=347,662,674 out=96,701,464 elapsed=147.2s

  [11631/21087] intraday_19665.csv.gz  in=347,673,751 out=96,712,541 elapsed=147.2s

  [11632/21087] intraday_19664.csv.gz  in=347,686,654 out=96,725,444 elapsed=147.2s

  [11633/21087] intraday_19666.csv.gz  in=347,700,409 out=96,739,199 elapsed=147.2s

  [11634/21087] intraday_19667.csv.gz  in=347,715,536 out=96,754,326 elapsed=147.3s

  [11635/21087] intraday_1967.csv.gz  in=347,726,850 out=96,754,326 elapsed=147.3s

  [11636/21087] intraday_19669.csv.gz  in=347,738,612 out=96,766,088 elapsed=147.3s

  [11637/21087] intraday_19668.csv.gz  in=347,750,013 out=96,777,489 elapsed=147.3s

  [11638/21087] intraday_19670.csv.gz  in=347,762,405 out=96,789,881 elapsed=147.3s

  [11639/21087] intraday_19671.csv.gz  in=347,775,228 out=96,802,704 elapsed=147.3s

  [11640/21087] intraday_19672.csv.gz  in=347,785,871 out=96,813,347 elapsed=147.3s

  [11641/21087] intraday_19673.csv.gz  in=347,798,338 out=96,825,814 elapsed=147.3s

  [11642/21087] intraday_19674.csv.gz  in=347,812,593 out=96,840,069 elapsed=147.3s

  [11643/21087] intraday_19676.csv.gz  in=347,825,033 out=96,852,509 elapsed=147.4s

  [11644/21087] intraday_19675.csv.gz  in=347,837,524 out=96,865,000 elapsed=147.4s

  [11645/21087] intraday_19677.csv.gz  in=347,846,711 out=96,874,187 elapsed=147.4s

  [11646/21087] intraday_19678.csv.gz  in=347,862,916 out=96,890,392 elapsed=147.4s

  [11647/21087] intraday_1968.csv.gz  in=347,876,338 out=96,890,392 elapsed=147.4s

  [11648/21087] intraday_19680.csv.gz  in=347,886,747 out=96,900,801 elapsed=147.4s

  [11649/21087] intraday_19679.csv.gz  in=347,901,161 out=96,915,215 elapsed=147.4s

  [11650/21087] intraday_19681.csv.gz  in=347,911,951 out=96,926,005 elapsed=147.4s

  [11651/21087] intraday_19682.csv.gz  in=347,922,801 out=96,936,855 elapsed=147.4s

  [11652/21087] intraday_19683.csv.gz  in=347,934,907 out=96,948,961 elapsed=147.4s

  [11653/21087] intraday_19685.csv.gz  in=347,946,053 out=96,960,107 elapsed=147.4s

  [11654/21087] intraday_19684.csv.gz  in=347,960,744 out=96,974,798 elapsed=147.5s

  [11655/21087] intraday_19687.csv.gz  in=347,972,449 out=96,986,503 elapsed=147.5s

  [11656/21087] intraday_19686.csv.gz  in=347,985,287 out=96,999,341 elapsed=147.5s

  [11657/21087] intraday_19688.csv.gz  in=347,997,026 out=97,011,080 elapsed=147.5s

  [11658/21087] intraday_1969.csv.gz  in=348,007,955 out=97,011,080 elapsed=147.5s

  [11659/21087] intraday_19689.csv.gz  in=348,020,482 out=97,023,607 elapsed=147.5s

  [11660/21087] intraday_19690.csv.gz  in=348,032,582 out=97,035,707 elapsed=147.5s

  [11661/21087] intraday_19691.csv.gz  in=348,044,503 out=97,047,628 elapsed=147.5s

  [11662/21087] intraday_19692.csv.gz  in=348,058,096 out=97,061,221 elapsed=147.5s

  [11663/21087] intraday_19694.csv.gz  in=348,068,427 out=97,071,552 elapsed=147.6s

  [11664/21087] intraday_19693.csv.gz  in=348,079,518 out=97,082,643 elapsed=147.6s

  [11665/21087] intraday_19695.csv.gz  in=348,092,730 out=97,095,855 elapsed=147.6s

  [11666/21087] intraday_19696.csv.gz  in=348,105,885 out=97,109,010 elapsed=147.6s

  [11667/21087] intraday_1970.csv.gz  in=348,118,845 out=97,109,010 elapsed=147.6s

  [11668/21087] intraday_19699.csv.gz  in=348,129,609 out=97,119,774 elapsed=147.6s

  [11669/21087] intraday_19698.csv.gz  in=348,141,552 out=97,131,717 elapsed=147.6s

  [11670/21087] intraday_19697.csv.gz  in=348,155,398 out=97,145,563 elapsed=147.6s

  [11671/21087] intraday_19700.csv.gz  in=348,165,963 out=97,156,128 elapsed=147.6s

  [11672/21087] intraday_19701.csv.gz  in=348,176,779 out=97,166,944 elapsed=147.7s

  [11673/21087] intraday_19702.csv.gz  in=348,189,388 out=97,179,553 elapsed=147.7s

  [11674/21087] intraday_19703.csv.gz  in=348,201,823 out=97,191,988 elapsed=147.7s

  [11675/21087] intraday_19704.csv.gz  in=348,214,090 out=97,204,255 elapsed=147.7s

  [11676/21087] intraday_19705.csv.gz  in=348,229,118 out=97,219,283 elapsed=147.7s

  [11677/21087] intraday_19707.csv.gz  in=348,240,261 out=97,230,426 elapsed=147.7s

  [11678/21087] intraday_19708.csv.gz  in=348,251,246 out=97,241,411 elapsed=147.7s

  [11679/21087] intraday_19706.csv.gz  in=348,264,409 out=97,254,574 elapsed=147.7s

  [11680/21087] intraday_19709.csv.gz  in=348,277,701 out=97,267,866 elapsed=147.7s

  [11681/21087] intraday_1971.csv.gz  in=348,288,141 out=97,267,866 elapsed=147.7s

  [11682/21087] intraday_19712.csv.gz  in=348,296,796 out=97,276,521 elapsed=147.8s

  [11683/21087] intraday_19710.csv.gz  in=348,309,828 out=97,289,553 elapsed=147.8s

  [11684/21087] intraday_19713.csv.gz  in=348,323,210 out=97,302,935 elapsed=147.8s

  [11685/21087] intraday_19711.csv.gz  in=348,335,999 out=97,315,724 elapsed=147.8s

  [11686/21087] intraday_19714.csv.gz  in=348,348,635 out=97,328,360 elapsed=147.8s

  [11687/21087] intraday_19715.csv.gz  in=348,361,865 out=97,341,590 elapsed=147.9s

  [11688/21087] intraday_19717.csv.gz  in=348,372,766 out=97,352,491 elapsed=147.9s

  [11689/21087] intraday_19716.csv.gz  in=348,384,931 out=97,364,656 elapsed=147.9s

  [11690/21087] intraday_19718.csv.gz  in=348,396,261 out=97,375,986 elapsed=147.9s

  [11691/21087] intraday_19719.csv.gz  in=348,407,101 out=97,386,826 elapsed=147.9s

  [11692/21087] intraday_1972.csv.gz  in=348,418,499 out=97,386,826 elapsed=147.9s

  [11693/21087] intraday_19721.csv.gz  in=348,430,467 out=97,398,794 elapsed=147.9s

  [11694/21087] intraday_19720.csv.gz  in=348,443,173 out=97,411,500 elapsed=147.9s

  [11695/21087] intraday_19723.csv.gz  in=348,453,823 out=97,422,150 elapsed=147.9s

  [11696/21087] intraday_19722.csv.gz  in=348,467,297 out=97,435,624 elapsed=147.9s

  [11697/21087] intraday_19724.csv.gz  in=348,478,519 out=97,446,846 elapsed=148.0s

  [11698/21087] intraday_19725.csv.gz  in=348,488,893 out=97,457,220 elapsed=148.0s

  [11699/21087] intraday_19727.csv.gz  in=348,501,253 out=97,469,580 elapsed=148.0s

  [11700/21087] intraday_19726.csv.gz  in=348,516,533 out=97,484,860 elapsed=148.0s

  [11701/21087] intraday_19728.csv.gz  in=348,530,514 out=97,498,841 elapsed=148.0s

  [11702/21087] intraday_19729.csv.gz  in=348,544,823 out=97,513,150 elapsed=148.0s

  [11703/21087] intraday_1973.csv.gz  in=348,558,434 out=97,513,150 elapsed=148.0s

  [11704/21087] intraday_19730.csv.gz  in=348,572,159 out=97,526,875 elapsed=148.0s

  [11705/21087] intraday_19731.csv.gz  in=348,581,708 out=97,536,424 elapsed=148.0s

  [11706/21087] intraday_19732.csv.gz  in=348,594,105 out=97,548,821 elapsed=148.0s

  [11707/21087] intraday_19733.csv.gz  in=348,607,161 out=97,561,877 elapsed=148.0s

  [11708/21087] intraday_19734.csv.gz  in=348,618,189 out=97,572,905 elapsed=148.0s

  [11709/21087] intraday_19735.csv.gz  in=348,628,542 out=97,583,258 elapsed=148.0s

  [11710/21087] intraday_19737.csv.gz  in=348,639,159 out=97,593,875 elapsed=148.1s

  [11711/21087] intraday_19736.csv.gz  in=348,650,890 out=97,605,606 elapsed=148.1s

  [11712/21087] intraday_19738.csv.gz  in=348,663,931 out=97,618,647 elapsed=148.1s

  [11713/21087] intraday_19739.csv.gz  in=348,675,998 out=97,630,714 elapsed=148.1s

  [11714/21087] intraday_1974.csv.gz  in=348,686,876 out=97,630,714 elapsed=148.1s

  [11715/21087] intraday_19740.csv.gz  in=348,699,408 out=97,643,246 elapsed=148.1s

  [11716/21087] intraday_19741.csv.gz  in=348,709,772 out=97,653,610 elapsed=148.1s

  [11717/21087] intraday_19743.csv.gz  in=348,723,286 out=97,667,124 elapsed=148.1s

  [11718/21087] intraday_19742.csv.gz  in=348,734,857 out=97,678,695 elapsed=148.1s

  [11719/21087] intraday_19744.csv.gz  in=348,749,903 out=97,693,741 elapsed=148.2s

  [11720/21087] intraday_19745.csv.gz  in=348,764,241 out=97,708,079 elapsed=148.2s

  [11721/21087] intraday_19746.csv.gz  in=348,777,759 out=97,721,597 elapsed=148.2s

  [11722/21087] intraday_19747.csv.gz  in=348,797,976 out=97,741,814 elapsed=148.2s

  [11723/21087] intraday_19748.csv.gz  in=348,812,024 out=97,755,862 elapsed=148.2s

  [11724/21087] intraday_19749.csv.gz  in=348,822,147 out=97,765,985 elapsed=148.2s

  [11725/21087] intraday_1975.csv.gz  in=348,837,228 out=97,765,985 elapsed=148.2s

  [11726/21087] intraday_19751.csv.gz  in=348,846,886 out=97,775,643 elapsed=148.2s

  [11727/21087] intraday_19750.csv.gz  in=348,861,465 out=97,790,222 elapsed=148.2s

  [11728/21087] intraday_19752.csv.gz  in=348,872,665 out=97,801,422 elapsed=148.2s

  [11729/21087] intraday_19753.csv.gz  in=348,885,256 out=97,814,013 elapsed=148.2s

  [11730/21087] intraday_19754.csv.gz  in=348,897,432 out=97,826,189 elapsed=148.3s

  [11731/21087] intraday_19755.csv.gz  in=348,909,123 out=97,837,880 elapsed=148.3s

  [11732/21087] intraday_19756.csv.gz  in=348,921,359 out=97,850,116 elapsed=148.3s

  [11733/21087] intraday_19757.csv.gz  in=348,933,937 out=97,862,694 elapsed=148.3s

  [11734/21087] intraday_19758.csv.gz  in=348,945,971 out=97,874,728 elapsed=148.3s

  [11735/21087] intraday_1976.csv.gz  in=348,958,701 out=97,874,728 elapsed=148.3s

  [11736/21087] intraday_19759.csv.gz  in=348,969,645 out=97,885,672 elapsed=148.3s

  [11737/21087] intraday_19760.csv.gz  in=348,981,216 out=97,897,243 elapsed=148.3s

  [11738/21087] intraday_19761.csv.gz  in=348,992,268 out=97,908,295 elapsed=148.4s

  [11739/21087] intraday_19762.csv.gz  in=349,003,832 out=97,919,859 elapsed=148.4s

  [11740/21087] intraday_19765.csv.gz  in=349,014,729 out=97,930,756 elapsed=148.4s

  [11741/21087] intraday_19763.csv.gz  in=349,026,844 out=97,942,871 elapsed=148.4s

  [11742/21087] intraday_19764.csv.gz  in=349,040,584 out=97,956,611 elapsed=148.4s

  [11743/21087] intraday_19766.csv.gz  in=349,052,891 out=97,968,918 elapsed=148.4s

  [11744/21087] intraday_19767.csv.gz  in=349,065,583 out=97,981,610 elapsed=148.4s

  [11745/21087] intraday_1977.csv.gz  in=349,077,662 out=97,981,610 elapsed=148.4s

  [11746/21087] intraday_19768.csv.gz  in=349,089,168 out=97,993,116 elapsed=148.4s

  [11747/21087] intraday_19769.csv.gz  in=349,102,418 out=98,006,366 elapsed=148.5s

  [11748/21087] intraday_19770.csv.gz  in=349,117,564 out=98,021,512 elapsed=148.5s

  [11749/21087] intraday_19771.csv.gz  in=349,132,413 out=98,036,361 elapsed=148.5s

  [11750/21087] intraday_19772.csv.gz  in=349,145,742 out=98,049,690 elapsed=148.5s

  [11751/21087] intraday_19773.csv.gz  in=349,158,697 out=98,062,645 elapsed=148.5s

  [11752/21087] intraday_19774.csv.gz  in=349,178,816 out=98,082,764 elapsed=148.5s

  [11753/21087] intraday_19775.csv.gz  in=349,192,392 out=98,096,340 elapsed=148.5s

  [11754/21087] intraday_19776.csv.gz  in=349,219,427 out=98,122,028 elapsed=148.5s

  [11755/21087] intraday_19777.csv.gz  in=349,238,079 out=98,140,680 elapsed=148.5s

  [11756/21087] intraday_19778.csv.gz  in=349,249,492 out=98,152,093 elapsed=148.5s

  [11757/21087] intraday_1978.csv.gz  in=349,262,388 out=98,152,093 elapsed=148.5s

  [11758/21087] intraday_19779.csv.gz  in=349,278,876 out=98,168,581 elapsed=148.5s

  [11759/21087] intraday_19782.csv.gz  in=349,290,669 out=98,180,374 elapsed=148.6s

  [11760/21087] intraday_19780.csv.gz  in=349,302,564 out=98,192,269 elapsed=148.6s

  [11761/21087] intraday_19783.csv.gz  in=349,315,356 out=98,205,061 elapsed=148.6s

  [11762/21087] intraday_19781.csv.gz  in=349,329,957 out=98,219,662 elapsed=148.6s

  [11763/21087] intraday_19784.csv.gz  in=349,340,157 out=98,229,862 elapsed=148.7s

  [11764/21087] intraday_19786.csv.gz  in=349,352,391 out=98,242,096 elapsed=148.7s

  [11765/21087] intraday_19785.csv.gz  in=349,364,994 out=98,254,699 elapsed=148.7s

  [11766/21087] intraday_19787.csv.gz  in=349,377,523 out=98,267,228 elapsed=148.7s

  [11767/21087] intraday_1979.csv.gz  in=349,390,217 out=98,267,228 elapsed=148.7s

  [11768/21087] intraday_19788.csv.gz  in=349,401,223 out=98,278,234 elapsed=148.7s

  [11769/21087] intraday_19790.csv.gz  in=349,415,661 out=98,292,672 elapsed=148.7s

  [11770/21087] intraday_19789.csv.gz  in=349,427,420 out=98,304,431 elapsed=148.7s

  [11771/21087] intraday_19791.csv.gz  in=349,440,015 out=98,317,026 elapsed=148.7s

  [11772/21087] intraday_19792.csv.gz  in=349,452,361 out=98,329,372 elapsed=148.7s

  [11773/21087] intraday_19793.csv.gz  in=349,465,711 out=98,342,722 elapsed=148.8s

  [11774/21087] intraday_19794.csv.gz  in=349,479,664 out=98,356,675 elapsed=148.8s

  [11775/21087] intraday_19795.csv.gz  in=349,492,027 out=98,369,038 elapsed=148.8s

  [11776/21087] intraday_19796.csv.gz  in=349,506,826 out=98,383,837 elapsed=148.8s

  [11777/21087] intraday_1980.csv.gz  in=349,519,790 out=98,383,837 elapsed=148.8s

  [11778/21087] intraday_19797.csv.gz  in=349,530,759 out=98,394,806 elapsed=148.8s

  [11779/21087] intraday_19799.csv.gz  in=349,542,616 out=98,406,663 elapsed=148.8s

  [11780/21087] intraday_19798.csv.gz  in=349,556,618 out=98,420,665 elapsed=148.8s

  [11781/21087] intraday_19800.csv.gz  in=349,568,527 out=98,432,574 elapsed=148.8s

  [11782/21087] intraday_19802.csv.gz  in=349,575,880 out=98,439,927 elapsed=148.9s

  [11783/21087] intraday_19801.csv.gz  in=349,588,045 out=98,452,092 elapsed=148.9s

  [11784/21087] intraday_19804.csv.gz  in=349,594,657 out=98,458,704 elapsed=148.9s

  [11785/21087] intraday_19803.csv.gz  in=349,605,928 out=98,469,975 elapsed=148.9s

  [11786/21087] intraday_19805.csv.gz  in=349,623,325 out=98,487,372 elapsed=148.9s

  [11787/21087] intraday_19808.csv.gz  in=349,637,158 out=98,501,205 elapsed=148.9s

  [11788/21087] intraday_19807.csv.gz  in=349,650,909 out=98,514,956 elapsed=148.9s

  [11789/21087] intraday_19806.csv.gz  in=349,666,107 out=98,530,154 elapsed=148.9s

  [11790/21087] intraday_19809.csv.gz  in=349,680,071 out=98,544,118 elapsed=148.9s

  [11791/21087] intraday_1981.csv.gz  in=349,691,089 out=98,544,118 elapsed=149.0s

  [11792/21087] intraday_19812.csv.gz  in=349,704,609 out=98,557,638 elapsed=149.0s

  [11793/21087] intraday_19810.csv.gz  in=349,720,949 out=98,573,978 elapsed=149.0s

  [11794/21087] intraday_19811.csv.gz  in=349,733,935 out=98,586,964 elapsed=149.0s

  [11795/21087] intraday_19813.csv.gz  in=349,746,156 out=98,599,185 elapsed=149.0s

  [11796/21087] intraday_19815.csv.gz  in=349,757,446 out=98,610,475 elapsed=149.0s

  [11797/21087] intraday_19814.csv.gz  in=349,772,382 out=98,625,411 elapsed=149.1s

  [11798/21087] intraday_19816.csv.gz  in=349,785,578 out=98,638,607 elapsed=149.1s

  [11799/21087] intraday_19817.csv.gz  in=349,799,649 out=98,652,678 elapsed=149.1s

  [11800/21087] intraday_19818.csv.gz  in=349,812,136 out=98,665,165 elapsed=149.1s

  [11801/21087] intraday_19819.csv.gz  in=349,824,227 out=98,677,256 elapsed=149.1s

  [11802/21087] intraday_1982.csv.gz  in=349,856,943 out=98,677,256 elapsed=149.1s

  [11803/21087] intraday_19820.csv.gz  in=349,867,183 out=98,687,496 elapsed=149.1s

  [11804/21087] intraday_19821.csv.gz  in=349,883,504 out=98,703,817 elapsed=149.1s

  [11805/21087] intraday_19822.csv.gz  in=349,898,686 out=98,718,999 elapsed=149.1s

  [11806/21087] intraday_19824.csv.gz  in=349,908,996 out=98,729,309 elapsed=149.2s

  [11807/21087] intraday_19823.csv.gz  in=349,920,055 out=98,740,368 elapsed=149.2s

  [11808/21087] intraday_19825.csv.gz  in=349,933,106 out=98,753,419 elapsed=149.2s

  [11809/21087] intraday_19826.csv.gz  in=349,946,286 out=98,766,599 elapsed=149.2s

  [11810/21087] intraday_19828.csv.gz  in=349,958,822 out=98,779,135 elapsed=149.2s

  [11811/21087] intraday_19827.csv.gz  in=349,972,340 out=98,792,653 elapsed=149.2s

  [11812/21087] intraday_1983.csv.gz  in=349,984,818 out=98,792,653 elapsed=149.2s

  [11813/21087] intraday_19829.csv.gz  in=349,997,670 out=98,805,505 elapsed=149.2s

  [11814/21087] intraday_19830.csv.gz  in=350,010,410 out=98,818,245 elapsed=149.2s

  [11815/21087] intraday_19832.csv.gz  in=350,022,448 out=98,830,283 elapsed=149.3s

  [11816/21087] intraday_19833.csv.gz  in=350,037,412 out=98,845,232 elapsed=149.3s

  [11817/21087] intraday_19831.csv.gz  in=350,050,275 out=98,858,095 elapsed=149.3s

  [11818/21087] intraday_19834.csv.gz  in=350,064,715 out=98,872,535 elapsed=149.3s

  [11819/21087] intraday_19836.csv.gz  in=350,076,193 out=98,884,013 elapsed=149.3s

  [11820/21087] intraday_19837.csv.gz  in=350,087,743 out=98,895,563 elapsed=149.3s

  [11821/21087] intraday_19835.csv.gz  in=350,102,128 out=98,909,948 elapsed=149.3s

  [11822/21087] intraday_19838.csv.gz  in=350,115,338 out=98,923,158 elapsed=149.3s

  [11823/21087] intraday_19839.csv.gz  in=350,128,990 out=98,936,810 elapsed=149.3s

  [11824/21087] intraday_1984.csv.gz  in=350,143,641 out=98,936,810 elapsed=149.3s

  [11825/21087] intraday_19841.csv.gz  in=350,155,368 out=98,948,537 elapsed=149.4s

  [11826/21087] intraday_19840.csv.gz  in=350,170,183 out=98,963,352 elapsed=149.4s

  [11827/21087] intraday_19842.csv.gz  in=350,180,845 out=98,974,014 elapsed=149.4s

  [11828/21087] intraday_19843.csv.gz  in=350,192,821 out=98,985,990 elapsed=149.4s

  [11829/21087] intraday_19844.csv.gz  in=350,203,633 out=98,996,802 elapsed=149.4s

  [11830/21087] intraday_19845.csv.gz  in=350,216,908 out=99,010,077 elapsed=149.4s

  [11831/21087] intraday_19846.csv.gz  in=350,229,343 out=99,022,512 elapsed=149.4s

  [11832/21087] intraday_19847.csv.gz  in=350,243,085 out=99,036,254 elapsed=149.4s

  [11833/21087] intraday_19848.csv.gz  in=350,257,730 out=99,050,899 elapsed=149.4s

  [11834/21087] intraday_1985.csv.gz  in=350,269,713 out=99,050,899 elapsed=149.4s

  [11835/21087] intraday_19849.csv.gz  in=350,282,488 out=99,063,674 elapsed=149.5s

  [11836/21087] intraday_19850.csv.gz  in=350,294,958 out=99,076,144 elapsed=149.5s

  [11837/21087] intraday_19851.csv.gz  in=350,306,498 out=99,087,684 elapsed=149.5s

  [11838/21087] intraday_19852.csv.gz  in=350,320,781 out=99,101,967 elapsed=149.5s

  [11839/21087] intraday_19854.csv.gz  in=350,333,288 out=99,114,474 elapsed=149.5s

  [11840/21087] intraday_19853.csv.gz  in=350,346,654 out=99,127,840 elapsed=149.5s

  [11841/21087] intraday_19855.csv.gz  in=350,356,860 out=99,138,046 elapsed=149.5s

  [11842/21087] intraday_19856.csv.gz  in=350,372,070 out=99,153,256 elapsed=149.5s

  [11843/21087] intraday_1986.csv.gz  in=350,384,614 out=99,153,256 elapsed=149.5s

  [11844/21087] intraday_19858.csv.gz  in=350,397,141 out=99,165,783 elapsed=149.5s

  [11845/21087] intraday_19859.csv.gz  in=350,411,987 out=99,180,629 elapsed=149.6s

  [11846/21087] intraday_19857.csv.gz  in=350,427,910 out=99,196,552 elapsed=149.6s

  [11847/21087] intraday_19860.csv.gz  in=350,438,824 out=99,207,466 elapsed=149.6s

  [11848/21087] intraday_19861.csv.gz  in=350,450,773 out=99,219,415 elapsed=149.6s

  [11849/21087] intraday_19862.csv.gz  in=350,463,125 out=99,231,767 elapsed=149.6s

  [11850/21087] intraday_19863.csv.gz  in=350,477,885 out=99,246,527 elapsed=149.6s

  [11851/21087] intraday_19864.csv.gz  in=350,490,190 out=99,258,832 elapsed=149.6s

  [11852/21087] intraday_19865.csv.gz  in=350,503,532 out=99,272,174 elapsed=149.6s

  [11853/21087] intraday_19867.csv.gz  in=350,514,737 out=99,283,379 elapsed=149.6s

  [11854/21087] intraday_19866.csv.gz  in=350,537,555 out=99,304,974 elapsed=149.6s

  [11855/21087] intraday_19868.csv.gz  in=350,549,015 out=99,316,434 elapsed=149.7s

  [11856/21087] intraday_19869.csv.gz  in=350,569,583 out=99,336,281 elapsed=149.7s

  [11857/21087] intraday_1987.csv.gz  in=350,581,885 out=99,336,281 elapsed=149.7s

  [11858/21087] intraday_19870.csv.gz  in=350,595,854 out=99,350,250 elapsed=149.7s

  [11859/21087] intraday_19871.csv.gz  in=350,610,468 out=99,364,864 elapsed=149.7s

  [11860/21087] intraday_19873.csv.gz  in=350,622,595 out=99,376,991 elapsed=149.7s

  [11861/21087] intraday_19872.csv.gz  in=350,637,100 out=99,391,496 elapsed=149.7s

  [11862/21087] intraday_19874.csv.gz  in=350,648,191 out=99,402,587 elapsed=149.7s

  [11863/21087] intraday_19875.csv.gz  in=350,661,435 out=99,415,831 elapsed=149.7s

  [11864/21087] intraday_19877.csv.gz  in=350,674,465 out=99,428,861 elapsed=149.8s

  [11865/21087] intraday_19876.csv.gz  in=350,687,688 out=99,442,084 elapsed=149.8s

  [11866/21087] intraday_19878.csv.gz  in=350,698,446 out=99,452,842 elapsed=149.8s

  [11867/21087] intraday_19879.csv.gz  in=350,710,910 out=99,465,306 elapsed=149.8s

  [11868/21087] intraday_1988.csv.gz  in=350,724,203 out=99,465,306 elapsed=149.8s

  [11869/21087] intraday_19880.csv.gz  in=350,735,405 out=99,476,508 elapsed=149.8s

  [11870/21087] intraday_19881.csv.gz  in=350,749,264 out=99,490,367 elapsed=149.8s

  [11871/21087] intraday_19882.csv.gz  in=350,762,451 out=99,503,554 elapsed=149.8s

  [11872/21087] intraday_19883.csv.gz  in=350,776,166 out=99,517,269 elapsed=149.8s

  [11873/21087] intraday_19884.csv.gz  in=350,786,356 out=99,527,459 elapsed=149.8s

  [11874/21087] intraday_19885.csv.gz  in=350,798,522 out=99,539,625 elapsed=149.9s

  [11875/21087] intraday_19886.csv.gz  in=350,813,075 out=99,554,178 elapsed=149.9s

  [11876/21087] intraday_19887.csv.gz  in=350,828,596 out=99,569,699 elapsed=149.9s

  [11877/21087] intraday_19888.csv.gz  in=350,845,304 out=99,586,407 elapsed=149.9s

  [11878/21087] intraday_19889.csv.gz  in=350,860,084 out=99,601,187 elapsed=149.9s

  [11879/21087] intraday_1989.csv.gz  in=350,872,530 out=99,601,187 elapsed=149.9s

  [11880/21087] intraday_19890.csv.gz  in=350,884,883 out=99,613,540 elapsed=149.9s

  [11881/21087] intraday_19892.csv.gz  in=350,895,967 out=99,624,624 elapsed=149.9s

  [11882/21087] intraday_19891.csv.gz  in=350,912,429 out=99,641,086 elapsed=150.0s

  [11883/21087] intraday_19893.csv.gz  in=350,927,918 out=99,656,575 elapsed=150.0s

  [11884/21087] intraday_19895.csv.gz  in=350,940,895 out=99,669,552 elapsed=150.0s

  [11885/21087] intraday_19894.csv.gz  in=350,952,101 out=99,680,758 elapsed=150.0s

  [11886/21087] intraday_19897.csv.gz  in=350,965,409 out=99,694,066 elapsed=150.0s

  [11887/21087] intraday_19896.csv.gz  in=350,977,446 out=99,706,103 elapsed=150.0s

  [11888/21087] intraday_19899.csv.gz  in=350,990,900 out=99,719,557 elapsed=150.0s

  [11889/21087] intraday_19898.csv.gz  in=351,004,011 out=99,732,668 elapsed=150.0s

  [11890/21087] intraday_1990.csv.gz  in=351,016,464 out=99,732,668 elapsed=150.0s

  [11891/21087] intraday_19900.csv.gz  in=351,031,073 out=99,747,277 elapsed=150.0s

  [11892/21087] intraday_19901.csv.gz  in=351,041,932 out=99,758,136 elapsed=150.1s

  [11893/21087] intraday_19902.csv.gz  in=351,054,067 out=99,770,271 elapsed=150.1s

  [11894/21087] intraday_19903.csv.gz  in=351,066,770 out=99,782,974 elapsed=150.1s

  [11895/21087] intraday_19904.csv.gz  in=351,079,249 out=99,795,453 elapsed=150.1s

  [11896/21087] intraday_19905.csv.gz  in=351,091,744 out=99,807,948 elapsed=150.1s

  [11897/21087] intraday_19907.csv.gz  in=351,104,822 out=99,821,026 elapsed=150.1s

  [11898/21087] intraday_19906.csv.gz  in=351,120,246 out=99,836,450 elapsed=150.1s

  [11899/21087] intraday_19908.csv.gz  in=351,132,222 out=99,848,426 elapsed=150.1s

  [11900/21087] intraday_19909.csv.gz  in=351,147,271 out=99,863,475 elapsed=150.1s

  [11901/21087] intraday_1991.csv.gz  in=351,158,312 out=99,863,475 elapsed=150.1s

  [11902/21087] intraday_19910.csv.gz  in=351,171,277 out=99,876,440 elapsed=150.2s

  [11903/21087] intraday_19911.csv.gz  in=351,183,722 out=99,888,885 elapsed=150.2s

  [11904/21087] intraday_19912.csv.gz  in=351,197,597 out=99,902,760 elapsed=150.2s

  [11905/21087] intraday_19913.csv.gz  in=351,214,081 out=99,919,244 elapsed=150.2s

  [11906/21087] intraday_19914.csv.gz  in=351,229,294 out=99,934,457 elapsed=150.2s

  [11907/21087] intraday_19915.csv.gz  in=351,243,046 out=99,948,209 elapsed=150.2s

  [11908/21087] intraday_19918.csv.gz  in=351,257,259 out=99,962,422 elapsed=150.2s

  [11909/21087] intraday_19916.csv.gz  in=351,271,516 out=99,976,679 elapsed=150.2s

  [11910/21087] intraday_19917.csv.gz  in=351,287,404 out=99,992,567 elapsed=150.2s

  [11911/21087] intraday_19919.csv.gz  in=351,303,935 out=100,009,098 elapsed=150.2s

  [11912/21087] intraday_1992.csv.gz  in=351,316,993 out=100,009,098 elapsed=150.2s

  [11913/21087] intraday_19921.csv.gz  in=351,332,855 out=100,024,960 elapsed=150.3s

  [11914/21087] intraday_19923.csv.gz  in=351,345,958 out=100,038,063 elapsed=150.3s

  [11915/21087] intraday_19922.csv.gz  in=351,361,023 out=100,053,128 elapsed=150.3s

  [11916/21087] intraday_19920.csv.gz  in=351,380,315 out=100,072,420 elapsed=150.3s

  [11917/21087] intraday_19924.csv.gz  in=351,399,497 out=100,091,602 elapsed=150.3s

  [11918/21087] intraday_19927.csv.gz  in=351,411,603 out=100,103,708 elapsed=150.4s

  [11919/21087] intraday_19925.csv.gz  in=351,423,649 out=100,115,754 elapsed=150.4s

  [11920/21087] intraday_19928.csv.gz  in=351,436,134 out=100,128,239 elapsed=150.4s

  [11921/21087] intraday_19926.csv.gz  in=351,450,500 out=100,142,605 elapsed=150.4s

  [11922/21087] intraday_1993.csv.gz  in=351,463,532 out=100,142,605 elapsed=150.4s

  [11923/21087] intraday_19929.csv.gz  in=351,477,269 out=100,156,342 elapsed=150.4s

  [11924/21087] intraday_19931.csv.gz  in=351,489,310 out=100,168,383 elapsed=150.4s

  [11925/21087] intraday_19930.csv.gz  in=351,503,336 out=100,182,409 elapsed=150.4s

  [11926/21087] intraday_19932.csv.gz  in=351,515,900 out=100,194,973 elapsed=150.4s

  [11927/21087] intraday_19934.csv.gz  in=351,529,325 out=100,208,398 elapsed=150.5s

  [11928/21087] intraday_19933.csv.gz  in=351,544,312 out=100,223,385 elapsed=150.5s

  [11929/21087] intraday_19935.csv.gz  in=351,557,556 out=100,236,629 elapsed=150.5s

  [11930/21087] intraday_19936.csv.gz  in=351,571,919 out=100,250,992 elapsed=150.5s

  [11931/21087] intraday_19937.csv.gz  in=351,587,078 out=100,266,151 elapsed=150.5s

  [11932/21087] intraday_1994.csv.gz  in=351,599,493 out=100,266,151 elapsed=150.5s

  [11933/21087] intraday_19938.csv.gz  in=351,612,403 out=100,279,061 elapsed=150.5s

  [11934/21087] intraday_19939.csv.gz  in=351,626,187 out=100,292,845 elapsed=150.5s

  [11935/21087] intraday_19940.csv.gz  in=351,640,416 out=100,307,074 elapsed=150.5s

  [11936/21087] intraday_19941.csv.gz  in=351,653,741 out=100,320,399 elapsed=150.5s

  [11937/21087] intraday_19942.csv.gz  in=351,665,271 out=100,331,929 elapsed=150.6s

  [11938/21087] intraday_19945.csv.gz  in=351,674,854 out=100,341,512 elapsed=150.6s

  [11939/21087] intraday_19944.csv.gz  in=351,684,798 out=100,351,456 elapsed=150.6s

  [11940/21087] intraday_19943.csv.gz  in=351,699,633 out=100,366,291 elapsed=150.6s

  [11941/21087] intraday_19947.csv.gz  in=351,703,233 out=100,369,891 elapsed=150.6s

  [11942/21087] intraday_19946.csv.gz  in=351,716,033 out=100,382,691 elapsed=150.6s

  [11943/21087] intraday_1995.csv.gz  in=351,727,472 out=100,382,691 elapsed=150.6s

  [11944/21087] intraday_19949.csv.gz  in=351,741,993 out=100,397,212 elapsed=150.6s

  [11945/21087] intraday_19948.csv.gz  in=351,759,912 out=100,415,131 elapsed=150.6s

  [11946/21087] intraday_19951.csv.gz  in=351,769,726 out=100,424,945 elapsed=150.7s

  [11947/21087] intraday_19950.csv.gz  in=351,784,243 out=100,439,462 elapsed=150.7s

  [11948/21087] intraday_19952.csv.gz  in=351,798,033 out=100,453,252 elapsed=150.7s

  [11949/21087] intraday_19953.csv.gz  in=351,812,888 out=100,468,107 elapsed=150.7s

  [11950/21087] intraday_19954.csv.gz  in=351,827,389 out=100,482,608 elapsed=150.7s

  [11951/21087] intraday_19955.csv.gz  in=351,840,036 out=100,495,255 elapsed=150.7s

  [11952/21087] intraday_19957.csv.gz  in=351,852,844 out=100,508,063 elapsed=150.7s

  [11953/21087] intraday_19956.csv.gz  in=351,866,848 out=100,522,067 elapsed=150.7s

  [11954/21087] intraday_19958.csv.gz  in=351,878,399 out=100,533,618 elapsed=150.7s

  [11955/21087] intraday_1996.csv.gz  in=351,889,126 out=100,533,618 elapsed=150.7s

  [11956/21087] intraday_19959.csv.gz  in=351,901,872 out=100,546,364 elapsed=150.8s

  [11957/21087] intraday_19961.csv.gz  in=351,914,875 out=100,559,367 elapsed=150.8s

  [11958/21087] intraday_19960.csv.gz  in=351,929,634 out=100,574,126 elapsed=150.8s

  [11959/21087] intraday_19962.csv.gz  in=351,941,887 out=100,586,379 elapsed=150.8s

  [11960/21087] intraday_19963.csv.gz  in=351,954,212 out=100,598,704 elapsed=150.8s

  [11961/21087] intraday_19964.csv.gz  in=351,969,020 out=100,613,512 elapsed=150.8s

  [11962/21087] intraday_19965.csv.gz  in=351,984,531 out=100,629,023 elapsed=150.8s

  [11963/21087] intraday_19967.csv.gz  in=351,995,105 out=100,639,597 elapsed=150.8s

  [11964/21087] intraday_19966.csv.gz  in=352,022,470 out=100,666,962 elapsed=150.9s

  [11965/21087] intraday_19968.csv.gz  in=352,035,690 out=100,680,182 elapsed=150.9s

  [11966/21087] intraday_1997.csv.gz  in=352,045,756 out=100,680,182 elapsed=150.9s

  [11967/21087] intraday_19969.csv.gz  in=352,058,784 out=100,693,210 elapsed=150.9s

  [11968/21087] intraday_19971.csv.gz  in=352,070,628 out=100,705,054 elapsed=150.9s

  [11969/21087] intraday_19970.csv.gz  in=352,084,269 out=100,718,695 elapsed=150.9s

  [11970/21087] intraday_19972.csv.gz  in=352,096,892 out=100,731,318 elapsed=150.9s

  [11971/21087] intraday_19973.csv.gz  in=352,110,232 out=100,744,658 elapsed=150.9s

  [11972/21087] intraday_19975.csv.gz  in=352,121,347 out=100,755,773 elapsed=150.9s

  [11973/21087] intraday_19976.csv.gz  in=352,135,815 out=100,770,241 elapsed=151.0s

  [11974/21087] intraday_19974.csv.gz  in=352,153,505 out=100,787,931 elapsed=151.0s

  [11975/21087] intraday_19977.csv.gz  in=352,168,397 out=100,802,823 elapsed=151.0s

  [11976/21087] intraday_19978.csv.gz  in=352,182,020 out=100,816,446 elapsed=151.0s

  [11977/21087] intraday_1998.csv.gz  in=352,195,734 out=100,816,446 elapsed=151.0s

  [11978/21087] intraday_19979.csv.gz  in=352,208,120 out=100,828,832 elapsed=151.0s

  [11979/21087] intraday_19980.csv.gz  in=352,219,645 out=100,840,357 elapsed=151.0s

  [11980/21087] intraday_19981.csv.gz  in=352,231,864 out=100,852,576 elapsed=151.0s

  [11981/21087] intraday_19982.csv.gz  in=352,251,580 out=100,871,447 elapsed=151.0s

  [11982/21087] intraday_19985.csv.gz  in=352,262,514 out=100,882,381 elapsed=151.1s

  [11983/21087] intraday_19984.csv.gz  in=352,275,769 out=100,895,636 elapsed=151.1s

  [11984/21087] intraday_19983.csv.gz  in=352,290,422 out=100,910,289 elapsed=151.1s

  [11985/21087] intraday_19986.csv.gz  in=352,301,448 out=100,921,315 elapsed=151.1s

  [11986/21087] intraday_19987.csv.gz  in=352,312,616 out=100,932,483 elapsed=151.1s

  [11987/21087] intraday_1999.csv.gz  in=352,324,351 out=100,932,483 elapsed=151.1s

  [11988/21087] intraday_19989.csv.gz  in=352,337,647 out=100,945,779 elapsed=151.1s

  [11989/21087] intraday_19988.csv.gz  in=352,350,588 out=100,958,720 elapsed=151.1s

  [11990/21087] intraday_19990.csv.gz  in=352,363,842 out=100,971,974 elapsed=151.1s

  [11991/21087] intraday_19991.csv.gz  in=352,379,249 out=100,987,381 elapsed=151.1s

  [11992/21087] intraday_19992.csv.gz  in=352,390,817 out=100,998,949 elapsed=151.1s

  [11993/21087] intraday_19993.csv.gz  in=352,403,654 out=101,011,786 elapsed=151.2s

  [11994/21087] intraday_19994.csv.gz  in=352,415,074 out=101,023,206 elapsed=151.2s

  [11995/21087] intraday_19995.csv.gz  in=352,429,845 out=101,037,977 elapsed=151.2s

  [11996/21087] intraday_19996.csv.gz  in=352,443,963 out=101,052,095 elapsed=151.2s

  [11997/21087] intraday_19998.csv.gz  in=352,453,489 out=101,061,621 elapsed=151.2s

  [11998/21087] intraday_19997.csv.gz  in=352,466,428 out=101,074,560 elapsed=151.2s

  [11999/21087] intraday_19999.csv.gz  in=352,482,401 out=101,090,533 elapsed=151.2s

  [12000/21087] intraday_2000.csv.gz  in=352,496,078 out=101,090,533 elapsed=151.2s

  [12001/21087] intraday_20001.csv.gz  in=352,508,223 out=101,102,678 elapsed=151.3s

  [12002/21087] intraday_20000.csv.gz  in=352,523,391 out=101,117,846 elapsed=151.3s

  [12003/21087] intraday_20002.csv.gz  in=352,538,381 out=101,132,836 elapsed=151.3s

  [12004/21087] intraday_20003.csv.gz  in=352,549,709 out=101,144,164 elapsed=151.3s

  [12005/21087] intraday_20004.csv.gz  in=352,562,408 out=101,156,863 elapsed=151.3s

  [12006/21087] intraday_20005.csv.gz  in=352,575,003 out=101,169,458 elapsed=151.3s

  [12007/21087] intraday_20007.csv.gz  in=352,587,775 out=101,182,230 elapsed=151.3s

  [12008/21087] intraday_20006.csv.gz  in=352,601,772 out=101,196,227 elapsed=151.3s

  [12009/21087] intraday_2001.csv.gz  in=352,615,420 out=101,196,227 elapsed=151.4s

  [12010/21087] intraday_20010.csv.gz  in=352,626,651 out=101,207,458 elapsed=151.4s

  [12011/21087] intraday_20009.csv.gz  in=352,638,961 out=101,219,768 elapsed=151.4s

  [12012/21087] intraday_20008.csv.gz  in=352,651,572 out=101,232,379 elapsed=151.4s

  [12013/21087] intraday_20011.csv.gz  in=352,662,121 out=101,242,928 elapsed=151.4s

  [12014/21087] intraday_20014.csv.gz  in=352,676,794 out=101,257,601 elapsed=151.4s

  [12015/21087] intraday_20012.csv.gz  in=352,692,605 out=101,273,412 elapsed=151.4s

  [12016/21087] intraday_20013.csv.gz  in=352,706,947 out=101,287,754 elapsed=151.4s

  [12017/21087] intraday_20015.csv.gz  in=352,721,749 out=101,302,556 elapsed=151.4s

  [12018/21087] intraday_20016.csv.gz  in=352,733,419 out=101,314,226 elapsed=151.5s

  [12019/21087] intraday_20019.csv.gz  in=352,746,655 out=101,327,462 elapsed=151.5s

  [12020/21087] intraday_20018.csv.gz  in=352,759,551 out=101,340,358 elapsed=151.5s

  [12021/21087] intraday_20017.csv.gz  in=352,769,969 out=101,350,776 elapsed=151.5s

  [12022/21087] intraday_2002.csv.gz  in=352,786,881 out=101,350,776 elapsed=151.5s

  [12023/21087] intraday_20021.csv.gz  in=352,798,607 out=101,362,502 elapsed=151.5s

  [12024/21087] intraday_20020.csv.gz  in=352,810,949 out=101,374,844 elapsed=151.5s

  [12025/21087] intraday_20022.csv.gz  in=352,823,266 out=101,387,161 elapsed=151.5s

  [12026/21087] intraday_20023.csv.gz  in=352,834,549 out=101,398,444 elapsed=151.5s

  [12027/21087] intraday_20024.csv.gz  in=352,848,639 out=101,412,534 elapsed=151.6s

  [12028/21087] intraday_20025.csv.gz  in=352,861,229 out=101,425,124 elapsed=151.6s

  [12029/21087] intraday_20026.csv.gz  in=352,874,932 out=101,438,827 elapsed=151.6s

  [12030/21087] intraday_20027.csv.gz  in=352,892,907 out=101,456,233 elapsed=151.6s

  [12031/21087] intraday_20028.csv.gz  in=352,905,079 out=101,468,405 elapsed=151.6s

  [12032/21087] intraday_2003.csv.gz  in=352,914,977 out=101,468,405 elapsed=151.6s

  [12033/21087] intraday_20029.csv.gz  in=352,929,740 out=101,483,168 elapsed=151.6s

  [12034/21087] intraday_20030.csv.gz  in=352,945,355 out=101,498,783 elapsed=151.6s

  [12035/21087] intraday_20031.csv.gz  in=352,961,513 out=101,514,941 elapsed=151.6s

  [12036/21087] intraday_20032.csv.gz  in=352,977,556 out=101,530,984 elapsed=151.7s

  [12037/21087] intraday_20033.csv.gz  in=352,989,668 out=101,543,096 elapsed=151.7s

  [12038/21087] intraday_20034.csv.gz  in=353,005,306 out=101,558,734 elapsed=151.7s

  [12039/21087] intraday_20038.csv.gz  in=353,018,572 out=101,572,000 elapsed=151.7s

  [12040/21087] intraday_20037.csv.gz  in=353,029,389 out=101,582,817 elapsed=151.7s

  [12041/21087] intraday_20035.csv.gz  in=353,040,525 out=101,593,953 elapsed=151.7s

  [12042/21087] intraday_20036.csv.gz  in=353,057,330 out=101,610,758 elapsed=151.7s

  [12043/21087] intraday_2004.csv.gz  in=353,070,298 out=101,610,758 elapsed=151.8s

  [12044/21087] intraday_20039.csv.gz  in=353,083,199 out=101,623,659 elapsed=151.8s

  [12045/21087] intraday_20040.csv.gz  in=353,096,839 out=101,637,299 elapsed=151.8s

  [12046/21087] intraday_20041.csv.gz  in=353,109,389 out=101,649,849 elapsed=151.8s

  [12047/21087] intraday_20042.csv.gz  in=353,122,447 out=101,662,907 elapsed=151.8s

  [12048/21087] intraday_20044.csv.gz  in=353,134,031 out=101,674,491 elapsed=151.8s

  [12049/21087] intraday_20043.csv.gz  in=353,147,919 out=101,688,379 elapsed=151.8s

  [12050/21087] intraday_20045.csv.gz  in=353,160,282 out=101,700,742 elapsed=151.8s

  [12051/21087] intraday_20046.csv.gz  in=353,172,763 out=101,713,223 elapsed=151.8s

  [12052/21087] intraday_20047.csv.gz  in=353,184,803 out=101,725,263 elapsed=151.8s

  [12053/21087] intraday_2005.csv.gz  in=353,196,292 out=101,725,263 elapsed=151.9s

  [12054/21087] intraday_20048.csv.gz  in=353,208,862 out=101,737,819 elapsed=151.9s

  [12055/21087] intraday_20049.csv.gz  in=353,223,060 out=101,752,017 elapsed=151.9s

  [12056/21087] intraday_20050.csv.gz  in=353,237,841 out=101,766,798 elapsed=151.9s

  [12057/21087] intraday_20051.csv.gz  in=353,250,485 out=101,779,442 elapsed=151.9s

  [12058/21087] intraday_20054.csv.gz  in=353,263,562 out=101,792,519 elapsed=151.9s

  [12059/21087] intraday_20053.csv.gz  in=353,276,675 out=101,805,632 elapsed=151.9s

  [12060/21087] intraday_20055.csv.gz  in=353,291,317 out=101,820,274 elapsed=151.9s

  [12061/21087] intraday_20052.csv.gz  in=353,305,459 out=101,834,416 elapsed=151.9s

  [12062/21087] intraday_20057.csv.gz  in=353,320,466 out=101,849,423 elapsed=152.0s

  [12063/21087] intraday_20056.csv.gz  in=353,337,067 out=101,866,024 elapsed=152.0s

  [12064/21087] intraday_20058.csv.gz  in=353,350,251 out=101,879,208 elapsed=152.0s

  [12065/21087] intraday_20059.csv.gz  in=353,366,735 out=101,895,692 elapsed=152.0s

  [12066/21087] intraday_2006.csv.gz  in=353,379,594 out=101,895,692 elapsed=152.0s

  [12067/21087] intraday_20060.csv.gz  in=353,394,775 out=101,910,873 elapsed=152.0s

  [12068/21087] intraday_20061.csv.gz  in=353,410,506 out=101,926,604 elapsed=152.0s

  [12069/21087] intraday_20062.csv.gz  in=353,427,340 out=101,943,438 elapsed=152.0s

  [12070/21087] intraday_20064.csv.gz  in=353,442,361 out=101,958,459 elapsed=152.1s

  [12071/21087] intraday_20063.csv.gz  in=353,462,585 out=101,978,683 elapsed=152.1s

  [12072/21087] intraday_20068.csv.gz  in=353,475,449 out=101,991,547 elapsed=152.1s

  [12073/21087] intraday_20066.csv.gz  in=353,488,789 out=102,004,887 elapsed=152.1s

  [12074/21087] intraday_20065.csv.gz  in=353,505,368 out=102,021,466 elapsed=152.1s

  [12075/21087] intraday_20067.csv.gz  in=353,520,424 out=102,036,522 elapsed=152.1s

  [12076/21087] intraday_2007.csv.gz  in=353,530,305 out=102,036,522 elapsed=152.1s

  [12077/21087] intraday_20070.csv.gz  in=353,541,886 out=102,048,103 elapsed=152.1s

  [12078/21087] intraday_20069.csv.gz  in=353,555,549 out=102,061,766 elapsed=152.1s

  [12079/21087] intraday_20071.csv.gz  in=353,569,695 out=102,075,912 elapsed=152.2s

  [12080/21087] intraday_20072.csv.gz  in=353,582,622 out=102,088,839 elapsed=152.2s

  [12081/21087] intraday_20074.csv.gz  in=353,593,916 out=102,100,133 elapsed=152.2s

  [12082/21087] intraday_20075.csv.gz  in=353,605,999 out=102,112,216 elapsed=152.2s

  [12083/21087] intraday_20076.csv.gz  in=353,620,742 out=102,126,959 elapsed=152.2s

  [12084/21087] intraday_20073.csv.gz  in=353,636,684 out=102,142,901 elapsed=152.2s

  [12085/21087] intraday_20077.csv.gz  in=353,650,587 out=102,156,804 elapsed=152.2s

  [12086/21087] intraday_20078.csv.gz  in=353,663,709 out=102,169,926 elapsed=152.2s

  [12087/21087] intraday_20079.csv.gz  in=353,678,048 out=102,184,265 elapsed=152.2s

  [12088/21087] intraday_2008.csv.gz  in=353,690,390 out=102,184,265 elapsed=152.2s

  [12089/21087] intraday_20080.csv.gz  in=353,705,433 out=102,199,308 elapsed=152.3s

  [12090/21087] intraday_20081.csv.gz  in=353,718,771 out=102,212,646 elapsed=152.3s

  [12091/21087] intraday_20082.csv.gz  in=353,732,216 out=102,226,091 elapsed=152.3s

  [12092/21087] intraday_20083.csv.gz  in=353,745,191 out=102,239,066 elapsed=152.3s

  [12093/21087] intraday_20084.csv.gz  in=353,759,654 out=102,253,529 elapsed=152.3s

  [12094/21087] intraday_20085.csv.gz  in=353,771,754 out=102,265,629 elapsed=152.3s

  [12095/21087] intraday_20087.csv.gz  in=353,781,749 out=102,275,624 elapsed=152.3s

  [12096/21087] intraday_20086.csv.gz  in=353,796,720 out=102,290,595 elapsed=152.3s

  [12097/21087] intraday_2009.csv.gz  in=353,807,597 out=102,290,595 elapsed=152.3s

  [12098/21087] intraday_20088.csv.gz  in=353,820,677 out=102,303,675 elapsed=152.3s

  [12099/21087] intraday_20089.csv.gz  in=353,833,681 out=102,316,679 elapsed=152.3s

  [12100/21087] intraday_20090.csv.gz  in=353,837,555 out=102,320,553 elapsed=152.4s

  [12101/21087] intraday_20093.csv.gz  in=353,850,593 out=102,333,591 elapsed=152.4s

  [12102/21087] intraday_20092.csv.gz  in=353,863,238 out=102,346,181 elapsed=152.4s

  [12103/21087] intraday_20091.csv.gz  in=353,879,751 out=102,362,694 elapsed=152.4s

  [12104/21087] intraday_20094.csv.gz  in=353,889,275 out=102,372,218 elapsed=152.4s

  [12105/21087] intraday_20097.csv.gz  in=353,900,648 out=102,383,591 elapsed=152.5s

  [12106/21087] intraday_20095.csv.gz  in=353,912,796 out=102,395,739 elapsed=152.5s

  [12107/21087] intraday_20098.csv.gz  in=353,925,278 out=102,408,221 elapsed=152.5s

  [12108/21087] intraday_20096.csv.gz  in=353,940,225 out=102,423,168 elapsed=152.5s

  [12109/21087] intraday_2010.csv.gz  in=353,952,484 out=102,423,168 elapsed=152.5s

  [12110/21087] intraday_20101.csv.gz  in=353,962,382 out=102,433,066 elapsed=152.5s

  [12111/21087] intraday_20099.csv.gz  in=353,975,326 out=102,446,010 elapsed=152.5s

  [12112/21087] intraday_20100.csv.gz  in=353,988,000 out=102,458,684 elapsed=152.5s

  [12113/21087] intraday_20102.csv.gz  in=353,999,528 out=102,470,212 elapsed=152.5s

  [12114/21087] intraday_20105.csv.gz  in=354,010,799 out=102,481,483 elapsed=152.5s

  [12115/21087] intraday_20103.csv.gz  in=354,023,823 out=102,494,507 elapsed=152.6s

  [12116/21087] intraday_20106.csv.gz  in=354,035,189 out=102,505,873 elapsed=152.6s

  [12117/21087] intraday_20104.csv.gz  in=354,055,571 out=102,525,811 elapsed=152.6s

  [12118/21087] intraday_20107.csv.gz  in=354,068,858 out=102,539,098 elapsed=152.6s

  [12119/21087] intraday_2011.csv.gz  in=354,079,820 out=102,539,098 elapsed=152.6s

  [12120/21087] intraday_20108.csv.gz  in=354,094,078 out=102,553,356 elapsed=152.6s

  [12121/21087] intraday_20109.csv.gz  in=354,105,286 out=102,564,564 elapsed=152.6s

  [12122/21087] intraday_20110.csv.gz  in=354,115,493 out=102,574,771 elapsed=152.6s

  [12123/21087] intraday_20111.csv.gz  in=354,127,412 out=102,586,690 elapsed=152.6s

  [12124/21087] intraday_20112.csv.gz  in=354,140,241 out=102,599,519 elapsed=152.6s

  [12125/21087] intraday_20113.csv.gz  in=354,152,647 out=102,611,925 elapsed=152.6s

  [12126/21087] intraday_20114.csv.gz  in=354,164,296 out=102,623,535 elapsed=152.6s

  [12127/21087] intraday_20116.csv.gz  in=354,176,268 out=102,635,507 elapsed=152.7s

  [12128/21087] intraday_20115.csv.gz  in=354,210,326 out=102,667,766 elapsed=152.7s

  [12129/21087] intraday_20117.csv.gz  in=354,221,604 out=102,679,044 elapsed=152.7s

  [12130/21087] intraday_20118.csv.gz  in=354,233,450 out=102,690,890 elapsed=152.7s

  [12131/21087] intraday_20119.csv.gz  in=354,245,819 out=102,703,259 elapsed=152.7s

  [12132/21087] intraday_2012.csv.gz  in=354,259,359 out=102,703,259 elapsed=152.7s

  [12133/21087] intraday_20120.csv.gz  in=354,271,901 out=102,715,801 elapsed=152.7s

  [12134/21087] intraday_20121.csv.gz  in=354,285,545 out=102,729,445 elapsed=152.7s

  [12135/21087] intraday_20122.csv.gz  in=354,297,681 out=102,741,581 elapsed=152.8s

  [12136/21087] intraday_20123.csv.gz  in=354,308,816 out=102,752,716 elapsed=152.8s

  [12137/21087] intraday_20124.csv.gz  in=354,320,292 out=102,764,192 elapsed=152.8s

  [12138/21087] intraday_20125.csv.gz  in=354,333,888 out=102,777,788 elapsed=152.8s

  [12139/21087] intraday_20126.csv.gz  in=354,347,519 out=102,791,419 elapsed=152.8s

  [12140/21087] intraday_20127.csv.gz  in=354,360,404 out=102,804,304 elapsed=152.8s

  [12141/21087] intraday_20128.csv.gz  in=354,370,535 out=102,814,435 elapsed=152.8s

  [12142/21087] intraday_20129.csv.gz  in=354,381,956 out=102,825,856 elapsed=152.8s

  [12143/21087] intraday_2013.csv.gz  in=354,393,373 out=102,825,856 elapsed=152.8s

  [12144/21087] intraday_20130.csv.gz  in=354,403,746 out=102,836,229 elapsed=152.8s

  [12145/21087] intraday_20131.csv.gz  in=354,415,402 out=102,847,885 elapsed=152.8s

  [12146/21087] intraday_20132.csv.gz  in=354,428,444 out=102,860,927 elapsed=152.9s

  [12147/21087] intraday_20133.csv.gz  in=354,441,037 out=102,873,520 elapsed=152.9s

  [12148/21087] intraday_20134.csv.gz  in=354,455,527 out=102,888,010 elapsed=152.9s

  [12149/21087] intraday_20135.csv.gz  in=354,467,035 out=102,899,518 elapsed=152.9s

  [12150/21087] intraday_20136.csv.gz  in=354,479,256 out=102,911,739 elapsed=152.9s

  [12151/21087] intraday_20138.csv.gz  in=354,492,267 out=102,924,750 elapsed=152.9s

  [12152/21087] intraday_20139.csv.gz  in=354,504,601 out=102,937,084 elapsed=152.9s

  [12153/21087] intraday_2014.csv.gz  in=354,515,619 out=102,937,084 elapsed=152.9s

  [12154/21087] intraday_20137.csv.gz  in=354,526,557 out=102,948,022 elapsed=152.9s

  [12155/21087] intraday_20143.csv.gz  in=354,539,079 out=102,960,544 elapsed=153.0s

  [12156/21087] intraday_20142.csv.gz  in=354,552,214 out=102,973,679 elapsed=153.0s

  [12157/21087] intraday_20140.csv.gz  in=354,567,592 out=102,988,792 elapsed=153.0s

  [12158/21087] intraday_20141.csv.gz  in=354,584,177 out=103,004,863 elapsed=153.0s

  [12159/21087] intraday_20144.csv.gz  in=354,595,714 out=103,016,400 elapsed=153.0s

  [12160/21087] intraday_20146.csv.gz  in=354,607,246 out=103,027,932 elapsed=153.0s

  [12161/21087] intraday_20147.csv.gz  in=354,618,211 out=103,038,897 elapsed=153.0s

  [12162/21087] intraday_20145.csv.gz  in=354,632,664 out=103,053,350 elapsed=153.0s

  [12163/21087] intraday_2015.csv.gz  in=354,643,799 out=103,053,350 elapsed=153.1s

  [12164/21087] intraday_20148.csv.gz  in=354,654,929 out=103,064,480 elapsed=153.1s

  [12165/21087] intraday_20150.csv.gz  in=354,667,102 out=103,076,653 elapsed=153.1s

  [12166/21087] intraday_20151.csv.gz  in=354,680,264 out=103,089,815 elapsed=153.1s

  [12167/21087] intraday_20149.csv.gz  in=354,694,490 out=103,104,041 elapsed=153.1s

  [12168/21087] intraday_20152.csv.gz  in=354,705,752 out=103,115,303 elapsed=153.1s

  [12169/21087] intraday_20153.csv.gz  in=354,717,514 out=103,127,065 elapsed=153.1s

  [12170/21087] intraday_20154.csv.gz  in=354,727,445 out=103,136,996 elapsed=153.2s

  [12171/21087] intraday_20155.csv.gz  in=354,741,154 out=103,150,705 elapsed=153.2s

  [12172/21087] intraday_20156.csv.gz  in=354,754,551 out=103,164,102 elapsed=153.2s

  [12173/21087] intraday_20157.csv.gz  in=354,768,291 out=103,177,842 elapsed=153.2s

  [12174/21087] intraday_2016.csv.gz  in=354,783,298 out=103,177,842 elapsed=153.2s

  [12175/21087] intraday_20159.csv.gz  in=354,794,422 out=103,188,966 elapsed=153.2s

  [12176/21087] intraday_20158.csv.gz  in=354,808,412 out=103,202,956 elapsed=153.2s

  [12177/21087] intraday_20160.csv.gz  in=354,817,485 out=103,212,029 elapsed=153.2s

  [12178/21087] intraday_20161.csv.gz  in=354,829,378 out=103,223,922 elapsed=153.2s

  [12179/21087] intraday_20163.csv.gz  in=354,840,433 out=103,234,977 elapsed=153.2s

  [12180/21087] intraday_20162.csv.gz  in=354,853,537 out=103,248,081 elapsed=153.3s

  [12181/21087] intraday_20164.csv.gz  in=354,863,931 out=103,258,475 elapsed=153.3s

  [12182/21087] intraday_20165.csv.gz  in=354,875,447 out=103,269,991 elapsed=153.3s

  [12183/21087] intraday_20166.csv.gz  in=354,886,130 out=103,280,674 elapsed=153.3s

  [12184/21087] intraday_20167.csv.gz  in=354,899,238 out=103,293,782 elapsed=153.3s

  [12185/21087] intraday_20168.csv.gz  in=354,911,506 out=103,306,050 elapsed=153.3s

  [12186/21087] intraday_2017.csv.gz  in=354,922,896 out=103,306,050 elapsed=153.3s

  [12187/21087] intraday_20169.csv.gz  in=354,935,478 out=103,318,632 elapsed=153.3s

  [12188/21087] intraday_20170.csv.gz  in=354,946,150 out=103,329,304 elapsed=153.3s

  [12189/21087] intraday_20171.csv.gz  in=354,957,079 out=103,340,233 elapsed=153.4s

  [12190/21087] intraday_20172.csv.gz  in=354,969,401 out=103,352,555 elapsed=153.4s

  [12191/21087] intraday_20173.csv.gz  in=354,984,369 out=103,367,523 elapsed=153.4s

  [12192/21087] intraday_20174.csv.gz  in=354,998,002 out=103,381,156 elapsed=153.4s

  [12193/21087] intraday_20176.csv.gz  in=355,010,308 out=103,393,462 elapsed=153.4s

  [12194/21087] intraday_20175.csv.gz  in=355,024,473 out=103,407,627 elapsed=153.4s

  [12195/21087] intraday_20177.csv.gz  in=355,039,050 out=103,422,204 elapsed=153.4s

  [12196/21087] intraday_20178.csv.gz  in=355,049,762 out=103,432,916 elapsed=153.4s

  [12197/21087] intraday_2018.csv.gz  in=355,061,728 out=103,432,916 elapsed=153.4s

  [12198/21087] intraday_20179.csv.gz  in=355,075,709 out=103,446,897 elapsed=153.5s

  [12199/21087] intraday_20180.csv.gz  in=355,086,491 out=103,457,679 elapsed=153.5s

  [12200/21087] intraday_20181.csv.gz  in=355,098,853 out=103,470,041 elapsed=153.5s

  [12201/21087] intraday_20182.csv.gz  in=355,110,676 out=103,481,864 elapsed=153.5s

  [12202/21087] intraday_20183.csv.gz  in=355,123,314 out=103,494,502 elapsed=153.5s

  [12203/21087] intraday_20185.csv.gz  in=355,135,282 out=103,506,470 elapsed=153.5s

  [12204/21087] intraday_20184.csv.gz  in=355,148,162 out=103,519,350 elapsed=153.5s

  [12205/21087] intraday_20186.csv.gz  in=355,161,353 out=103,532,541 elapsed=153.5s

  [12206/21087] intraday_20187.csv.gz  in=355,171,890 out=103,543,078 elapsed=153.5s

  [12207/21087] intraday_20188.csv.gz  in=355,183,113 out=103,554,301 elapsed=153.6s

  [12208/21087] intraday_2019.csv.gz  in=355,194,120 out=103,554,301 elapsed=153.6s

  [12209/21087] intraday_20189.csv.gz  in=355,206,295 out=103,566,476 elapsed=153.6s

  [12210/21087] intraday_20190.csv.gz  in=355,218,310 out=103,578,491 elapsed=153.6s

  [12211/21087] intraday_20192.csv.gz  in=355,231,441 out=103,591,622 elapsed=153.6s

  [12212/21087] intraday_20191.csv.gz  in=355,246,068 out=103,606,026 elapsed=153.6s

  [12213/21087] intraday_20194.csv.gz  in=355,257,063 out=103,617,021 elapsed=153.6s

  [12214/21087] intraday_20193.csv.gz  in=355,270,115 out=103,630,073 elapsed=153.6s

  [12215/21087] intraday_20195.csv.gz  in=355,283,431 out=103,643,389 elapsed=153.6s

  [12216/21087] intraday_20197.csv.gz  in=355,294,939 out=103,654,897 elapsed=153.7s

  [12217/21087] intraday_20196.csv.gz  in=355,307,216 out=103,667,174 elapsed=153.7s

  [12218/21087] intraday_20198.csv.gz  in=355,321,487 out=103,681,436 elapsed=153.7s

  [12219/21087] intraday_2020.csv.gz  in=355,333,304 out=103,681,436 elapsed=153.7s

  [12220/21087] intraday_20199.csv.gz  in=355,348,422 out=103,696,554 elapsed=153.7s

  [12221/21087] intraday_20200.csv.gz  in=355,362,388 out=103,710,520 elapsed=153.7s

  [12222/21087] intraday_20201.csv.gz  in=355,375,669 out=103,723,801 elapsed=153.7s

  [12223/21087] intraday_20203.csv.gz  in=355,390,017 out=103,738,149 elapsed=153.7s

  [12224/21087] intraday_20202.csv.gz  in=355,404,453 out=103,752,585 elapsed=153.7s

  [12225/21087] intraday_20204.csv.gz  in=355,417,824 out=103,765,956 elapsed=153.7s

  [12226/21087] intraday_20205.csv.gz  in=355,433,127 out=103,781,259 elapsed=153.7s

  [12227/21087] intraday_20206.csv.gz  in=355,450,719 out=103,798,851 elapsed=153.8s

  [12228/21087] intraday_20207.csv.gz  in=355,463,651 out=103,811,783 elapsed=153.8s

  [12229/21087] intraday_20209.csv.gz  in=355,475,669 out=103,823,801 elapsed=153.8s

  [12230/21087] intraday_20208.csv.gz  in=355,492,056 out=103,840,188 elapsed=153.8s

  [12231/21087] intraday_2021.csv.gz  in=355,504,363 out=103,840,188 elapsed=153.8s

  [12232/21087] intraday_20210.csv.gz  in=355,517,573 out=103,853,398 elapsed=153.8s

  [12233/21087] intraday_20211.csv.gz  in=355,528,490 out=103,864,315 elapsed=153.8s

  [12234/21087] intraday_20213.csv.gz  in=355,539,102 out=103,874,927 elapsed=153.8s

  [12235/21087] intraday_20212.csv.gz  in=355,553,180 out=103,889,005 elapsed=153.8s

  [12236/21087] intraday_20214.csv.gz  in=355,565,965 out=103,901,790 elapsed=153.8s

  [12237/21087] intraday_20215.csv.gz  in=355,578,327 out=103,914,152 elapsed=153.9s

  [12238/21087] intraday_20216.csv.gz  in=355,593,552 out=103,929,377 elapsed=153.9s

  [12239/21087] intraday_20217.csv.gz  in=355,604,305 out=103,940,130 elapsed=153.9s

  [12240/21087] intraday_20218.csv.gz  in=355,616,044 out=103,951,869 elapsed=153.9s

  [12241/21087] intraday_2022.csv.gz  in=355,631,573 out=103,951,869 elapsed=153.9s

  [12242/21087] intraday_20219.csv.gz  in=355,644,947 out=103,965,243 elapsed=153.9s

  [12243/21087] intraday_20220.csv.gz  in=355,657,336 out=103,977,632 elapsed=153.9s

  [12244/21087] intraday_20221.csv.gz  in=355,669,610 out=103,989,906 elapsed=153.9s

  [12245/21087] intraday_20222.csv.gz  in=355,686,362 out=104,006,303 elapsed=154.0s

  [12246/21087] intraday_20223.csv.gz  in=355,701,020 out=104,020,961 elapsed=154.0s

  [12247/21087] intraday_20224.csv.gz  in=355,713,510 out=104,033,451 elapsed=154.0s

  [12248/21087] intraday_20226.csv.gz  in=355,726,194 out=104,046,135 elapsed=154.0s

  [12249/21087] intraday_20225.csv.gz  in=355,740,263 out=104,060,204 elapsed=154.0s

  [12250/21087] intraday_20228.csv.gz  in=355,751,711 out=104,071,652 elapsed=154.0s

  [12251/21087] intraday_2023.csv.gz  in=355,762,795 out=104,071,652 elapsed=154.0s

  [12252/21087] intraday_20227.csv.gz  in=355,775,661 out=104,084,518 elapsed=154.0s

  [12253/21087] intraday_20229.csv.gz  in=355,790,139 out=104,098,996 elapsed=154.0s

  [12254/21087] intraday_20230.csv.gz  in=355,800,150 out=104,109,007 elapsed=154.0s

  [12255/21087] intraday_20231.csv.gz  in=355,808,784 out=104,117,641 elapsed=154.1s

  [12256/21087] intraday_20234.csv.gz  in=355,808,839 out=104,117,641 elapsed=154.1s

  [12257/21087] intraday_20233.csv.gz  in=355,812,704 out=104,121,506 elapsed=154.1s

  [12258/21087] intraday_20232.csv.gz  in=355,824,328 out=104,133,130 elapsed=154.1s

  [12259/21087] intraday_20236.csv.gz  in=355,824,545 out=104,133,347 elapsed=154.1s

  [12260/21087] intraday_20235.csv.gz  in=355,825,741 out=104,134,543 elapsed=154.1s

  [12261/21087] intraday_20237.csv.gz  in=355,826,155 out=104,134,957 elapsed=154.1s

  [12262/21087] intraday_20238.csv.gz  in=355,826,501 out=104,135,303 elapsed=154.1s

  [12263/21087] intraday_20239.csv.gz  in=355,826,805 out=104,135,607 elapsed=154.1s

  [12264/21087] intraday_20240.csv.gz  in=355,827,573 out=104,136,375 elapsed=154.1s

  [12265/21087] intraday_20241.csv.gz  in=355,828,090 out=104,136,892 elapsed=154.1s

  [12266/21087] intraday_20242.csv.gz  in=355,828,375 out=104,137,177 elapsed=154.1s

  [12267/21087] intraday_2024.csv.gz  in=355,842,913 out=104,137,177 elapsed=154.1s

  [12268/21087] intraday_20243.csv.gz  in=355,843,269 out=104,137,533 elapsed=154.1s

  [12269/21087] intraday_20244.csv.gz  in=355,843,682 out=104,137,946 elapsed=154.1s

  [12270/21087] intraday_20245.csv.gz  in=355,844,179 out=104,138,443 elapsed=154.1s

  [12271/21087] intraday_20246.csv.gz  in=355,845,731 out=104,139,985 elapsed=154.1s

  [12272/21087] intraday_20248.csv.gz  in=355,845,954 out=104,140,208 elapsed=154.1s

  [12273/21087] intraday_20247.csv.gz  in=355,846,656 out=104,140,910 elapsed=154.1s

  [12274/21087] intraday_20249.csv.gz  in=355,846,931 out=104,141,185 elapsed=154.1s

  [12275/21087] intraday_20250.csv.gz  in=355,847,199 out=104,141,453 elapsed=154.1s

  [12276/21087] intraday_20251.csv.gz  in=355,847,656 out=104,141,910 elapsed=154.1s

  [12277/21087] intraday_20252.csv.gz  in=355,848,123 out=104,142,377 elapsed=154.1s

  [12278/21087] intraday_2025.csv.gz  in=355,863,184 out=104,142,377 elapsed=154.2s

  [12279/21087] intraday_20254.csv.gz  in=355,863,358 out=104,142,551 elapsed=154.2s

  [12280/21087] intraday_20255.csv.gz  in=355,863,680 out=104,142,873 elapsed=154.2s

  [12281/21087] intraday_20253.csv.gz  in=355,863,993 out=104,143,186 elapsed=154.2s

  [12282/21087] intraday_20256.csv.gz  in=355,864,113 out=104,143,306 elapsed=154.2s

  [12283/21087] intraday_20258.csv.gz  in=355,864,428 out=104,143,620 elapsed=154.2s

  [12284/21087] intraday_20259.csv.gz  in=355,865,860 out=104,145,052 elapsed=154.2s

  [12285/21087] intraday_20260.csv.gz  in=355,866,262 out=104,145,454 elapsed=154.2s

  [12286/21087] intraday_2026.csv.gz  in=355,880,410 out=104,145,454 elapsed=154.2s

  [12287/21087] intraday_20257.csv.gz  in=355,893,767 out=104,158,482 elapsed=154.2s

  [12288/21087] intraday_20261.csv.gz  in=355,894,244 out=104,158,959 elapsed=154.2s

  [12289/21087] intraday_20262.csv.gz  in=355,894,314 out=104,159,029 elapsed=154.2s

  [12290/21087] intraday_20263.csv.gz  in=355,895,103 out=104,159,818 elapsed=154.2s

  [12291/21087] intraday_20264.csv.gz  in=355,895,402 out=104,160,117 elapsed=154.2s

  [12292/21087] intraday_20265.csv.gz  in=355,896,508 out=104,161,223 elapsed=154.2s

  [12293/21087] intraday_20266.csv.gz  in=355,896,697 out=104,161,412 elapsed=154.2s

  [12294/21087] intraday_20267.csv.gz  in=355,896,962 out=104,161,677 elapsed=154.2s

  [12295/21087] intraday_20269.csv.gz  in=355,897,257 out=104,161,972 elapsed=154.2s

  [12296/21087] intraday_20268.csv.gz  in=355,901,843 out=104,166,338 elapsed=154.2s

  [12297/21087] intraday_20270.csv.gz  in=355,902,311 out=104,166,806 elapsed=154.2s

  [12298/21087] intraday_2027.csv.gz  in=355,916,536 out=104,166,806 elapsed=154.2s

  [12299/21087] intraday_20272.csv.gz  in=355,916,642 out=104,166,912 elapsed=154.3s

  [12300/21087] intraday_20271.csv.gz  in=355,916,973 out=104,167,243 elapsed=154.3s

  [12301/21087] intraday_20274.csv.gz  in=355,917,090 out=104,167,360 elapsed=154.3s

  [12302/21087] intraday_20273.csv.gz  in=355,917,151 out=104,167,421 elapsed=154.3s

  [12303/21087] intraday_20276.csv.gz  in=355,917,308 out=104,167,578 elapsed=154.3s

  [12304/21087] intraday_20275.csv.gz  in=355,917,407 out=104,167,677 elapsed=154.3s

  [12305/21087] intraday_20277.csv.gz  in=355,917,886 out=104,168,156 elapsed=154.3s

  [12306/21087] intraday_20278.csv.gz  in=355,918,255 out=104,168,525 elapsed=154.3s

  [12307/21087] intraday_20279.csv.gz  in=355,918,399 out=104,168,669 elapsed=154.3s

  [12308/21087] intraday_20281.csv.gz  in=355,918,562 out=104,168,832 elapsed=154.3s

  [12309/21087] intraday_20283.csv.gz  in=355,918,771 out=104,169,041 elapsed=154.3s

  [12310/21087] intraday_2028.csv.gz  in=355,932,289 out=104,169,041 elapsed=154.3s

  [12311/21087] intraday_20280.csv.gz  in=355,938,160 out=104,174,557 elapsed=154.3s

  [12312/21087] intraday_20284.csv.gz  in=355,938,380 out=104,174,777 elapsed=154.3s

  [12313/21087] intraday_20285.csv.gz  in=355,938,522 out=104,174,919 elapsed=154.3s

  [12314/21087] intraday_20286.csv.gz  in=355,938,970 out=104,175,367 elapsed=154.3s

  [12315/21087] intraday_20282.csv.gz  in=355,958,381 out=104,193,462 elapsed=154.3s

  [12316/21087] intraday_20287.csv.gz  in=355,959,132 out=104,194,213 elapsed=154.3s

  [12317/21087] intraday_20289.csv.gz  in=355,959,573 out=104,194,654 elapsed=154.3s

  [12318/21087] intraday_20288.csv.gz  in=355,961,370 out=104,196,451 elapsed=154.3s

  [12319/21087] intraday_20290.csv.gz  in=355,961,499 out=104,196,580 elapsed=154.3s

  [12320/21087] intraday_20291.csv.gz  in=355,961,590 out=104,196,671 elapsed=154.4s

  [12321/21087] intraday_20292.csv.gz  in=355,961,803 out=104,196,884 elapsed=154.4s

  [12322/21087] intraday_2029.csv.gz  in=355,973,848 out=104,196,884 elapsed=154.4s

  [12323/21087] intraday_20293.csv.gz  in=355,975,574 out=104,198,610 elapsed=154.4s

  [12324/21087] intraday_20295.csv.gz  in=355,976,142 out=104,199,178 elapsed=154.4s

  [12325/21087] intraday_20296.csv.gz  in=355,976,192 out=104,199,228 elapsed=154.4s

  [12326/21087] intraday_20297.csv.gz  in=355,976,261 out=104,199,297 elapsed=154.4s

  [12327/21087] intraday_20294.csv.gz  in=355,980,860 out=104,203,708 elapsed=154.4s

  [12328/21087] intraday_20298.csv.gz  in=355,981,027 out=104,203,875 elapsed=154.4s

  [12329/21087] intraday_20300.csv.gz  in=355,981,683 out=104,204,531 elapsed=154.4s

  [12330/21087] intraday_20299.csv.gz  in=355,982,544 out=104,205,392 elapsed=154.4s

  [12331/21087] intraday_2030.csv.gz  in=355,994,815 out=104,205,392 elapsed=154.4s

  [12332/21087] intraday_20301.csv.gz  in=355,995,042 out=104,205,619 elapsed=154.4s

  [12333/21087] intraday_20302.csv.gz  in=355,995,240 out=104,205,817 elapsed=154.4s

  [12334/21087] intraday_20303.csv.gz  in=355,995,702 out=104,206,279 elapsed=154.4s

  [12335/21087] intraday_20304.csv.gz  in=355,995,829 out=104,206,406 elapsed=154.4s

  [12336/21087] intraday_20305.csv.gz  in=355,996,239 out=104,206,816 elapsed=154.5s

  [12337/21087] intraday_20306.csv.gz  in=355,996,586 out=104,207,163 elapsed=154.5s

  [12338/21087] intraday_20307.csv.gz  in=355,996,823 out=104,207,400 elapsed=154.5s

  [12339/21087] intraday_20308.csv.gz  in=355,997,105 out=104,207,682 elapsed=154.5s

  [12340/21087] intraday_20309.csv.gz  in=355,997,684 out=104,208,261 elapsed=154.5s

  [12341/21087] intraday_20310.csv.gz  in=355,997,939 out=104,208,516 elapsed=154.5s

  [12342/21087] intraday_20311.csv.gz  in=355,998,224 out=104,208,801 elapsed=154.5s

  [12343/21087] intraday_20312.csv.gz  in=355,998,561 out=104,209,138 elapsed=154.5s

  [12344/21087] intraday_2031.csv.gz  in=356,009,284 out=104,209,138 elapsed=154.5s

  [12345/21087] intraday_20313.csv.gz  in=356,009,704 out=104,209,558 elapsed=154.5s

  [12346/21087] intraday_20315.csv.gz  in=356,009,864 out=104,209,718 elapsed=154.5s

  [12347/21087] intraday_20314.csv.gz  in=356,010,917 out=104,210,771 elapsed=154.5s

  [12348/21087] intraday_20316.csv.gz  in=356,011,702 out=104,211,556 elapsed=154.5s

  [12349/21087] intraday_20317.csv.gz  in=356,012,793 out=104,212,647 elapsed=154.5s

  [12350/21087] intraday_20318.csv.gz  in=356,013,839 out=104,213,693 elapsed=154.5s

  [12351/21087] intraday_20319.csv.gz  in=356,014,709 out=104,214,563 elapsed=154.5s

  [12352/21087] intraday_20320.csv.gz  in=356,016,241 out=104,216,095 elapsed=154.5s

  [12353/21087] intraday_20321.csv.gz  in=356,016,887 out=104,216,741 elapsed=154.5s

  [12354/21087] intraday_20322.csv.gz  in=356,017,049 out=104,216,838 elapsed=154.5s

  [12355/21087] intraday_2032.csv.gz  in=356,028,889 out=104,216,838 elapsed=154.5s

  [12356/21087] intraday_20323.csv.gz  in=356,029,830 out=104,217,779 elapsed=154.6s

  [12357/21087] intraday_20324.csv.gz  in=356,030,220 out=104,218,169 elapsed=154.6s

  [12358/21087] intraday_20325.csv.gz  in=356,030,547 out=104,218,496 elapsed=154.6s

  [12359/21087] intraday_20328.csv.gz  in=356,030,850 out=104,218,799 elapsed=154.6s

  [12360/21087] intraday_20327.csv.gz  in=356,031,206 out=104,219,155 elapsed=154.6s

  [12361/21087] intraday_20326.csv.gz  in=356,034,096 out=104,222,045 elapsed=154.6s

  [12362/21087] intraday_20329.csv.gz  in=356,039,072 out=104,226,679 elapsed=154.6s

  [12363/21087] intraday_20330.csv.gz  in=356,039,441 out=104,227,048 elapsed=154.6s

  [12364/21087] intraday_20331.csv.gz  in=356,039,602 out=104,227,209 elapsed=154.6s

  [12365/21087] intraday_20332.csv.gz  in=356,040,158 out=104,227,765 elapsed=154.6s

  [12366/21087] intraday_2033.csv.gz  in=356,051,671 out=104,227,765 elapsed=154.6s

  [12367/21087] intraday_20333.csv.gz  in=356,051,789 out=104,227,883 elapsed=154.6s

  [12368/21087] intraday_20335.csv.gz  in=356,052,047 out=104,228,141 elapsed=154.6s

  [12369/21087] intraday_20337.csv.gz  in=356,052,740 out=104,228,834 elapsed=154.6s

  [12370/21087] intraday_20336.csv.gz  in=356,054,052 out=104,230,146 elapsed=154.6s

  [12371/21087] intraday_20339.csv.gz  in=356,054,316 out=104,230,410 elapsed=154.6s

  [12372/21087] intraday_20334.csv.gz  in=356,065,269 out=104,240,577 elapsed=154.6s

  [12373/21087] intraday_2034.csv.gz  in=356,079,379 out=104,240,577 elapsed=154.6s

  [12374/21087] intraday_20338.csv.gz  in=356,084,610 out=104,245,808 elapsed=154.6s

  [12375/21087] intraday_20340.csv.gz  in=356,085,197 out=104,246,395 elapsed=154.7s

  [12376/21087] intraday_20342.csv.gz  in=356,085,673 out=104,246,871 elapsed=154.7s

  [12377/21087] intraday_20341.csv.gz  in=356,085,842 out=104,247,040 elapsed=154.7s

  [12378/21087] intraday_20343.csv.gz  in=356,086,636 out=104,247,834 elapsed=154.7s

  [12379/21087] intraday_20344.csv.gz  in=356,087,363 out=104,248,561 elapsed=154.7s

  [12380/21087] intraday_20345.csv.gz  in=356,087,789 out=104,248,987 elapsed=154.7s

  [12381/21087] intraday_20346.csv.gz  in=356,088,118 out=104,249,316 elapsed=154.7s

  [12382/21087] intraday_20347.csv.gz  in=356,089,217 out=104,250,415 elapsed=154.7s

  [12383/21087] intraday_20348.csv.gz  in=356,090,189 out=104,251,387 elapsed=154.7s

  [12384/21087] intraday_20349.csv.gz  in=356,091,717 out=104,252,915 elapsed=154.7s

  [12385/21087] intraday_20350.csv.gz  in=356,093,240 out=104,254,438 elapsed=154.7s

  [12386/21087] intraday_2035.csv.gz  in=356,104,176 out=104,254,438 elapsed=154.7s

  [12387/21087] intraday_20351.csv.gz  in=356,104,789 out=104,255,051 elapsed=154.7s

  [12388/21087] intraday_20353.csv.gz  in=356,105,384 out=104,255,646 elapsed=154.7s

  [12389/21087] intraday_20354.csv.gz  in=356,105,707 out=104,255,969 elapsed=154.7s

  [12390/21087] intraday_20352.csv.gz  in=356,115,090 out=104,265,038 elapsed=154.7s

  [12391/21087] intraday_20355.csv.gz  in=356,115,166 out=104,265,114 elapsed=154.7s

  [12392/21087] intraday_20356.csv.gz  in=356,115,708 out=104,265,656 elapsed=154.7s

  [12393/21087] intraday_20357.csv.gz  in=356,115,891 out=104,265,839 elapsed=154.7s

  [12394/21087] intraday_20359.csv.gz  in=356,116,369 out=104,266,317 elapsed=154.8s

  [12395/21087] intraday_20358.csv.gz  in=356,116,845 out=104,266,793 elapsed=154.8s

  [12396/21087] intraday_20360.csv.gz  in=356,117,892 out=104,267,840 elapsed=154.8s

  [12397/21087] intraday_2036.csv.gz  in=356,130,775 out=104,267,840 elapsed=154.8s

  [12398/21087] intraday_20361.csv.gz  in=356,131,139 out=104,268,204 elapsed=154.8s

  [12399/21087] intraday_20362.csv.gz  in=356,131,459 out=104,268,524 elapsed=154.8s

  [12400/21087] intraday_20363.csv.gz  in=356,131,969 out=104,269,034 elapsed=154.8s

  [12401/21087] intraday_20364.csv.gz  in=356,132,536 out=104,269,601 elapsed=154.8s

  [12402/21087] intraday_20365.csv.gz  in=356,133,148 out=104,270,213 elapsed=154.8s

  [12403/21087] intraday_20366.csv.gz  in=356,133,419 out=104,270,484 elapsed=154.8s

  [12404/21087] intraday_20367.csv.gz  in=356,133,745 out=104,270,810 elapsed=154.8s

  [12405/21087] intraday_20368.csv.gz  in=356,134,059 out=104,271,124 elapsed=154.8s

  [12406/21087] intraday_20369.csv.gz  in=356,134,332 out=104,271,397 elapsed=154.8s

  [12407/21087] intraday_20370.csv.gz  in=356,134,731 out=104,271,796 elapsed=154.8s

  [12408/21087] intraday_20371.csv.gz  in=356,135,187 out=104,272,252 elapsed=154.8s

  [12409/21087] intraday_2037.csv.gz  in=356,147,577 out=104,272,252 elapsed=154.8s

  [12410/21087] intraday_20372.csv.gz  in=356,147,792 out=104,272,467 elapsed=154.8s

  [12411/21087] intraday_20373.csv.gz  in=356,148,428 out=104,273,103 elapsed=154.8s

  [12412/21087] intraday_20374.csv.gz  in=356,148,793 out=104,273,468 elapsed=154.8s

  [12413/21087] intraday_20375.csv.gz  in=356,149,238 out=104,273,913 elapsed=154.8s

  [12414/21087] intraday_20377.csv.gz  in=356,149,478 out=104,274,153 elapsed=154.8s

  [12415/21087] intraday_20376.csv.gz  in=356,149,670 out=104,274,345 elapsed=154.8s

  [12416/21087] intraday_2038.csv.gz  in=356,163,060 out=104,274,345 elapsed=154.9s

  [12417/21087] intraday_20378.csv.gz  in=356,180,323 out=104,291,608 elapsed=154.9s

  [12418/21087] intraday_20379.csv.gz  in=356,192,415 out=104,303,700 elapsed=154.9s

  [12419/21087] intraday_20380.csv.gz  in=356,205,539 out=104,316,824 elapsed=154.9s

  [12420/21087] intraday_20381.csv.gz  in=356,214,912 out=104,326,197 elapsed=154.9s

  [12421/21087] intraday_20383.csv.gz  in=356,229,359 out=104,340,644 elapsed=154.9s

  [12422/21087] intraday_20382.csv.gz  in=356,242,193 out=104,353,478 elapsed=155.0s

  [12423/21087] intraday_20384.csv.gz  in=356,254,820 out=104,366,105 elapsed=155.0s

  [12424/21087] intraday_20385.csv.gz  in=356,266,223 out=104,377,508 elapsed=155.0s

  [12425/21087] intraday_20386.csv.gz  in=356,278,494 out=104,389,779 elapsed=155.0s

  [12426/21087] intraday_20389.csv.gz  in=356,290,035 out=104,401,320 elapsed=155.0s

  [12427/21087] intraday_20388.csv.gz  in=356,299,054 out=104,410,339 elapsed=155.0s

  [12428/21087] intraday_20387.csv.gz  in=356,312,058 out=104,423,343 elapsed=155.0s

  [12429/21087] intraday_2039.csv.gz  in=356,330,279 out=104,423,343 elapsed=155.0s

  [12430/21087] intraday_20392.csv.gz  in=356,340,709 out=104,433,773 elapsed=155.1s

  [12431/21087] intraday_20391.csv.gz  in=356,352,040 out=104,445,104 elapsed=155.1s

  [12432/21087] intraday_20393.csv.gz  in=356,361,673 out=104,454,737 elapsed=155.1s

  [12433/21087] intraday_20390.csv.gz  in=356,374,625 out=104,467,689 elapsed=155.1s

  [12434/21087] intraday_20395.csv.gz  in=356,387,835 out=104,480,899 elapsed=155.1s

  [12435/21087] intraday_20397.csv.gz  in=356,397,721 out=104,490,785 elapsed=155.1s

  [12436/21087] intraday_20394.csv.gz  in=356,411,506 out=104,504,570 elapsed=155.1s

  [12437/21087] intraday_20396.csv.gz  in=356,422,058 out=104,515,122 elapsed=155.1s

  [12438/21087] intraday_2040.csv.gz  in=356,436,025 out=104,515,122 elapsed=155.1s

  [12439/21087] intraday_20400.csv.gz  in=356,447,575 out=104,526,672 elapsed=155.2s

  [12440/21087] intraday_20398.csv.gz  in=356,459,705 out=104,538,802 elapsed=155.2s

  [12441/21087] intraday_20399.csv.gz  in=356,472,390 out=104,551,487 elapsed=155.2s

  [12442/21087] intraday_20401.csv.gz  in=356,483,328 out=104,562,425 elapsed=155.2s

  [12443/21087] intraday_20402.csv.gz  in=356,495,638 out=104,574,735 elapsed=155.2s

  [12444/21087] intraday_20404.csv.gz  in=356,507,599 out=104,586,696 elapsed=155.2s

  [12445/21087] intraday_20403.csv.gz  in=356,519,223 out=104,598,320 elapsed=155.2s

  [12446/21087] intraday_20405.csv.gz  in=356,529,763 out=104,608,860 elapsed=155.2s

  [12447/21087] intraday_20409.csv.gz  in=356,540,884 out=104,619,981 elapsed=155.3s

  [12448/21087] intraday_20407.csv.gz  in=356,553,063 out=104,632,160 elapsed=155.3s

  [12449/21087] intraday_20408.csv.gz  in=356,566,534 out=104,645,631 elapsed=155.3s

  [12450/21087] intraday_20406.csv.gz  in=356,581,442 out=104,660,539 elapsed=155.3s

  [12451/21087] intraday_2041.csv.gz  in=356,596,276 out=104,660,539 elapsed=155.3s

  [12452/21087] intraday_20411.csv.gz  in=356,607,472 out=104,671,735 elapsed=155.3s

  [12453/21087] intraday_20410.csv.gz  in=356,618,777 out=104,683,040 elapsed=155.3s

  [12454/21087] intraday_20412.csv.gz  in=356,631,118 out=104,695,381 elapsed=155.3s

  [12455/21087] intraday_20413.csv.gz  in=356,644,948 out=104,709,211 elapsed=155.3s

  [12456/21087] intraday_20415.csv.gz  in=356,655,796 out=104,720,059 elapsed=155.4s

  [12457/21087] intraday_20414.csv.gz  in=356,667,378 out=104,731,641 elapsed=155.4s

  [12458/21087] intraday_20416.csv.gz  in=356,677,427 out=104,741,690 elapsed=155.4s

  [12459/21087] intraday_20417.csv.gz  in=356,687,734 out=104,751,997 elapsed=155.4s

  [12460/21087] intraday_20418.csv.gz  in=356,699,522 out=104,763,785 elapsed=155.4s

  [12461/21087] intraday_2042.csv.gz  in=356,712,919 out=104,763,785 elapsed=155.4s

  [12462/21087] intraday_20419.csv.gz  in=356,725,190 out=104,776,056 elapsed=155.4s

  [12463/21087] intraday_20420.csv.gz  in=356,738,288 out=104,789,154 elapsed=155.4s

  [12464/21087] intraday_20421.csv.gz  in=356,752,745 out=104,803,611 elapsed=155.4s

  [12465/21087] intraday_20422.csv.gz  in=356,763,315 out=104,814,181 elapsed=155.4s

  [12466/21087] intraday_20423.csv.gz  in=356,774,021 out=104,824,887 elapsed=155.5s

  [12467/21087] intraday_20424.csv.gz  in=356,786,166 out=104,837,032 elapsed=155.5s

  [12468/21087] intraday_20425.csv.gz  in=356,797,508 out=104,848,374 elapsed=155.5s

  [12469/21087] intraday_20427.csv.gz  in=356,808,754 out=104,859,620 elapsed=155.5s

  [12470/21087] intraday_20426.csv.gz  in=356,821,357 out=104,872,223 elapsed=155.5s

  [12471/21087] intraday_20428.csv.gz  in=356,831,992 out=104,882,858 elapsed=155.5s

  [12472/21087] intraday_20429.csv.gz  in=356,844,284 out=104,895,150 elapsed=155.5s

  [12473/21087] intraday_2043.csv.gz  in=356,856,708 out=104,895,150 elapsed=155.5s

  [12474/21087] intraday_20430.csv.gz  in=356,870,030 out=104,908,472 elapsed=155.5s

  [12475/21087] intraday_20431.csv.gz  in=356,881,953 out=104,920,395 elapsed=155.5s

  [12476/21087] intraday_20432.csv.gz  in=356,894,888 out=104,933,330 elapsed=155.6s

  [12477/21087] intraday_20434.csv.gz  in=356,904,399 out=104,942,841 elapsed=155.6s

  [12478/21087] intraday_20433.csv.gz  in=356,914,891 out=104,953,333 elapsed=155.6s

  [12479/21087] intraday_20435.csv.gz  in=356,927,375 out=104,965,817 elapsed=155.6s

  [12480/21087] intraday_20436.csv.gz  in=356,940,613 out=104,979,055 elapsed=155.6s

  [12481/21087] intraday_20437.csv.gz  in=356,952,060 out=104,990,502 elapsed=155.6s

  [12482/21087] intraday_20438.csv.gz  in=356,963,852 out=105,002,294 elapsed=155.6s

  [12483/21087] intraday_20439.csv.gz  in=356,975,006 out=105,013,448 elapsed=155.6s

  [12484/21087] intraday_2044.csv.gz  in=356,988,378 out=105,013,448 elapsed=155.6s

  [12485/21087] intraday_20440.csv.gz  in=356,998,992 out=105,024,062 elapsed=155.6s

  [12486/21087] intraday_20441.csv.gz  in=357,011,998 out=105,037,068 elapsed=155.6s

  [12487/21087] intraday_20442.csv.gz  in=357,024,308 out=105,049,378 elapsed=155.7s

  [12488/21087] intraday_20443.csv.gz  in=357,038,348 out=105,063,418 elapsed=155.7s

  [12489/21087] intraday_20444.csv.gz  in=357,052,062 out=105,077,132 elapsed=155.7s

  [12490/21087] intraday_20445.csv.gz  in=357,064,840 out=105,089,910 elapsed=155.7s

  [12491/21087] intraday_20446.csv.gz  in=357,074,609 out=105,099,679 elapsed=155.7s

  [12492/21087] intraday_20447.csv.gz  in=357,085,617 out=105,110,687 elapsed=155.7s

  [12493/21087] intraday_20448.csv.gz  in=357,099,075 out=105,124,145 elapsed=155.7s

  [12494/21087] intraday_2045.csv.gz  in=357,110,855 out=105,124,145 elapsed=155.7s

  [12495/21087] intraday_20449.csv.gz  in=357,121,170 out=105,134,460 elapsed=155.7s

  [12496/21087] intraday_20450.csv.gz  in=357,133,491 out=105,146,781 elapsed=155.8s

  [12497/21087] intraday_20451.csv.gz  in=357,144,560 out=105,157,850 elapsed=155.8s

  [12498/21087] intraday_20452.csv.gz  in=357,154,311 out=105,167,601 elapsed=155.8s

  [12499/21087] intraday_20453.csv.gz  in=357,165,116 out=105,178,406 elapsed=155.8s

  [12500/21087] intraday_20454.csv.gz  in=357,179,182 out=105,192,472 elapsed=155.8s

  [12501/21087] intraday_20455.csv.gz  in=357,191,762 out=105,205,052 elapsed=155.8s

  [12502/21087] intraday_20456.csv.gz  in=357,203,736 out=105,217,026 elapsed=155.8s

  [12503/21087] intraday_20457.csv.gz  in=357,213,343 out=105,226,633 elapsed=155.9s

  [12504/21087] intraday_2046.csv.gz  in=357,226,301 out=105,226,633 elapsed=155.9s

  [12505/21087] intraday_20458.csv.gz  in=357,238,071 out=105,238,403 elapsed=155.9s

  [12506/21087] intraday_20459.csv.gz  in=357,251,715 out=105,252,047 elapsed=155.9s

  [12507/21087] intraday_20461.csv.gz  in=357,265,027 out=105,265,359 elapsed=155.9s

  [12508/21087] intraday_20460.csv.gz  in=357,280,348 out=105,280,680 elapsed=155.9s

  [12509/21087] intraday_20463.csv.gz  in=357,291,894 out=105,292,226 elapsed=155.9s

  [12510/21087] intraday_20462.csv.gz  in=357,306,130 out=105,306,462 elapsed=155.9s

  [12511/21087] intraday_20467.csv.gz  in=357,316,190 out=105,316,522 elapsed=156.0s

  [12512/21087] intraday_20465.csv.gz  in=357,327,850 out=105,328,182 elapsed=156.0s

  [12513/21087] intraday_20466.csv.gz  in=357,340,841 out=105,341,173 elapsed=156.0s

  [12514/21087] intraday_20464.csv.gz  in=357,354,304 out=105,354,636 elapsed=156.0s

  [12515/21087] intraday_2047.csv.gz  in=357,366,856 out=105,354,636 elapsed=156.0s

  [12516/21087] intraday_20469.csv.gz  in=357,378,357 out=105,366,137 elapsed=156.0s

  [12517/21087] intraday_20468.csv.gz  in=357,391,838 out=105,379,618 elapsed=156.0s

  [12518/21087] intraday_20470.csv.gz  in=357,402,930 out=105,390,710 elapsed=156.0s

  [12519/21087] intraday_20471.csv.gz  in=357,415,624 out=105,403,404 elapsed=156.0s

  [12520/21087] intraday_20473.csv.gz  in=357,427,348 out=105,415,128 elapsed=156.1s

  [12521/21087] intraday_20474.csv.gz  in=357,439,474 out=105,427,254 elapsed=156.1s

  [12522/21087] intraday_20472.csv.gz  in=357,451,195 out=105,438,975 elapsed=156.1s

  [12523/21087] intraday_20475.csv.gz  in=357,462,553 out=105,450,333 elapsed=156.1s

  [12524/21087] intraday_20476.csv.gz  in=357,473,148 out=105,460,928 elapsed=156.1s

  [12525/21087] intraday_20477.csv.gz  in=357,484,929 out=105,472,709 elapsed=156.1s

  [12526/21087] intraday_20478.csv.gz  in=357,496,805 out=105,484,585 elapsed=156.1s

  [12527/21087] intraday_2048.csv.gz  in=357,511,881 out=105,484,585 elapsed=156.1s

  [12528/21087] intraday_20479.csv.gz  in=357,524,447 out=105,497,151 elapsed=156.1s

  [12529/21087] intraday_20480.csv.gz  in=357,537,350 out=105,510,054 elapsed=156.1s

  [12530/21087] intraday_20481.csv.gz  in=357,547,895 out=105,520,599 elapsed=156.2s

  [12531/21087] intraday_20483.csv.gz  in=357,558,008 out=105,530,712 elapsed=156.2s

  [12532/21087] intraday_20482.csv.gz  in=357,572,332 out=105,545,036 elapsed=156.2s

  [12533/21087] intraday_20484.csv.gz  in=357,586,040 out=105,558,744 elapsed=156.2s

  [12534/21087] intraday_20485.csv.gz  in=357,601,099 out=105,573,803 elapsed=156.2s

  [12535/21087] intraday_20486.csv.gz  in=357,614,577 out=105,587,281 elapsed=156.2s

  [12536/21087] intraday_20487.csv.gz  in=357,628,484 out=105,601,188 elapsed=156.2s

  [12537/21087] intraday_20488.csv.gz  in=357,642,919 out=105,615,623 elapsed=156.2s

  [12538/21087] intraday_20489.csv.gz  in=357,657,208 out=105,629,912 elapsed=156.2s

  [12539/21087] intraday_2049.csv.gz  in=357,672,958 out=105,629,912 elapsed=156.2s

  [12540/21087] intraday_20490.csv.gz  in=357,687,784 out=105,644,738 elapsed=156.3s

  [12541/21087] intraday_20492.csv.gz  in=357,703,567 out=105,660,521 elapsed=156.3s

  [12542/21087] intraday_20491.csv.gz  in=357,719,044 out=105,675,998 elapsed=156.3s

  [12543/21087] intraday_20493.csv.gz  in=357,733,437 out=105,690,391 elapsed=156.3s

  [12544/21087] intraday_20494.csv.gz  in=357,749,569 out=105,706,523 elapsed=156.3s

  [12545/21087] intraday_20495.csv.gz  in=357,761,487 out=105,718,441 elapsed=156.3s

  [12546/21087] intraday_20496.csv.gz  in=357,774,090 out=105,731,044 elapsed=156.3s

  [12547/21087] intraday_20497.csv.gz  in=357,785,202 out=105,742,156 elapsed=156.3s

  [12548/21087] intraday_20498.csv.gz  in=357,797,040 out=105,753,994 elapsed=156.3s

  [12549/21087] intraday_2050.csv.gz  in=357,809,858 out=105,753,994 elapsed=156.3s

  [12550/21087] intraday_20499.csv.gz  in=357,822,144 out=105,766,280 elapsed=156.3s

  [12551/21087] intraday_20500.csv.gz  in=357,834,135 out=105,778,271 elapsed=156.4s

  [12552/21087] intraday_20501.csv.gz  in=357,845,675 out=105,789,811 elapsed=156.4s

  [12553/21087] intraday_20503.csv.gz  in=357,856,775 out=105,800,911 elapsed=156.4s

  [12554/21087] intraday_20502.csv.gz  in=357,871,784 out=105,815,920 elapsed=156.4s

  [12555/21087] intraday_20504.csv.gz  in=357,883,151 out=105,827,287 elapsed=156.4s

  [12556/21087] intraday_20505.csv.gz  in=357,894,263 out=105,838,399 elapsed=156.4s

  [12557/21087] intraday_20506.csv.gz  in=357,907,827 out=105,851,963 elapsed=156.4s

  [12558/21087] intraday_20507.csv.gz  in=357,920,390 out=105,864,526 elapsed=156.4s

  [12559/21087] intraday_20508.csv.gz  in=357,933,698 out=105,877,834 elapsed=156.4s

  [12560/21087] intraday_2051.csv.gz  in=357,946,244 out=105,877,834 elapsed=156.5s

  [12561/21087] intraday_20509.csv.gz  in=357,959,804 out=105,891,394 elapsed=156.5s

  [12562/21087] intraday_20510.csv.gz  in=357,972,991 out=105,904,581 elapsed=156.5s

  [12563/21087] intraday_20511.csv.gz  in=357,987,622 out=105,919,212 elapsed=156.5s

  [12564/21087] intraday_20512.csv.gz  in=357,998,071 out=105,929,661 elapsed=156.5s

  [12565/21087] intraday_20513.csv.gz  in=358,011,115 out=105,942,705 elapsed=156.5s

  [12566/21087] intraday_20514.csv.gz  in=358,024,996 out=105,956,586 elapsed=156.5s

  [12567/21087] intraday_20517.csv.gz  in=358,032,731 out=105,964,321 elapsed=156.5s

  [12568/21087] intraday_20516.csv.gz  in=358,044,878 out=105,976,468 elapsed=156.6s

  [12569/21087] intraday_20515.csv.gz  in=358,057,479 out=105,989,069 elapsed=156.6s

  [12570/21087] intraday_20518.csv.gz  in=358,068,409 out=105,999,999 elapsed=156.6s

  [12571/21087] intraday_20519.csv.gz  in=358,075,547 out=106,007,137 elapsed=156.6s

  [12572/21087] intraday_2052.csv.gz  in=358,096,524 out=106,007,137 elapsed=156.6s

  [12573/21087] intraday_20521.csv.gz  in=358,108,775 out=106,019,388 elapsed=156.6s

  [12574/21087] intraday_20522.csv.gz  in=358,121,168 out=106,031,781 elapsed=156.6s

  [12575/21087] intraday_20520.csv.gz  in=358,137,535 out=106,048,148 elapsed=156.6s

  [12576/21087] intraday_20523.csv.gz  in=358,146,520 out=106,057,133 elapsed=156.6s

  [12577/21087] intraday_20524.csv.gz  in=358,160,056 out=106,070,669 elapsed=156.6s

  [12578/21087] intraday_20525.csv.gz  in=358,174,139 out=106,084,752 elapsed=156.7s

  [12579/21087] intraday_20526.csv.gz  in=358,186,268 out=106,096,881 elapsed=156.7s

  [12580/21087] intraday_20527.csv.gz  in=358,198,140 out=106,108,753 elapsed=156.7s

  [12581/21087] intraday_20528.csv.gz  in=358,209,691 out=106,120,304 elapsed=156.7s

  [12582/21087] intraday_2053.csv.gz  in=358,220,722 out=106,120,304 elapsed=156.7s

  [12583/21087] intraday_20529.csv.gz  in=358,233,220 out=106,132,802 elapsed=156.7s

  [12584/21087] intraday_20530.csv.gz  in=358,243,526 out=106,143,108 elapsed=156.7s

  [12585/21087] intraday_20531.csv.gz  in=358,254,531 out=106,154,113 elapsed=156.7s

  [12586/21087] intraday_20532.csv.gz  in=358,268,294 out=106,167,876 elapsed=156.8s

  [12587/21087] intraday_20534.csv.gz  in=358,278,207 out=106,177,789 elapsed=156.8s

  [12588/21087] intraday_20533.csv.gz  in=358,289,851 out=106,189,433 elapsed=156.8s

  [12589/21087] intraday_20535.csv.gz  in=358,299,802 out=106,199,384 elapsed=156.8s

  [12590/21087] intraday_20536.csv.gz  in=358,313,554 out=106,213,136 elapsed=156.8s

  [12591/21087] intraday_20537.csv.gz  in=358,326,387 out=106,225,969 elapsed=156.8s

  [12592/21087] intraday_20538.csv.gz  in=358,337,529 out=106,237,111 elapsed=156.8s

  [12593/21087] intraday_20539.csv.gz  in=358,347,323 out=106,246,905 elapsed=156.8s

  [12594/21087] intraday_2054.csv.gz  in=358,359,318 out=106,246,905 elapsed=156.8s

  [12595/21087] intraday_20540.csv.gz  in=358,371,147 out=106,258,734 elapsed=156.8s

  [12596/21087] intraday_20541.csv.gz  in=358,382,837 out=106,270,424 elapsed=156.9s

  [12597/21087] intraday_20542.csv.gz  in=358,394,639 out=106,282,226 elapsed=156.9s

  [12598/21087] intraday_20543.csv.gz  in=358,405,432 out=106,293,019 elapsed=156.9s

  [12599/21087] intraday_20544.csv.gz  in=358,417,389 out=106,304,976 elapsed=156.9s

  [12600/21087] intraday_20545.csv.gz  in=358,429,141 out=106,316,728 elapsed=156.9s

  [12601/21087] intraday_20546.csv.gz  in=358,441,537 out=106,329,124 elapsed=156.9s

  [12602/21087] intraday_20548.csv.gz  in=358,454,506 out=106,342,093 elapsed=156.9s

  [12603/21087] intraday_20547.csv.gz  in=358,466,337 out=106,353,924 elapsed=156.9s

  [12604/21087] intraday_2055.csv.gz  in=358,477,998 out=106,353,924 elapsed=156.9s

  [12605/21087] intraday_20549.csv.gz  in=358,491,392 out=106,367,318 elapsed=156.9s

  [12606/21087] intraday_20550.csv.gz  in=358,503,007 out=106,378,933 elapsed=157.0s

  [12607/21087] intraday_20553.csv.gz  in=358,514,365 out=106,390,291 elapsed=157.0s

  [12608/21087] intraday_20552.csv.gz  in=358,525,153 out=106,401,079 elapsed=157.0s

  [12609/21087] intraday_20551.csv.gz  in=358,536,744 out=106,412,670 elapsed=157.0s

  [12610/21087] intraday_20555.csv.gz  in=358,549,995 out=106,425,921 elapsed=157.1s

  [12611/21087] intraday_20554.csv.gz  in=358,561,993 out=106,437,919 elapsed=157.1s

  [12612/21087] intraday_20557.csv.gz  in=358,572,306 out=106,448,232 elapsed=157.1s

  [12613/21087] intraday_20556.csv.gz  in=358,584,671 out=106,460,597 elapsed=157.1s

  [12614/21087] intraday_2056.csv.gz  in=358,599,984 out=106,460,597 elapsed=157.1s

  [12615/21087] intraday_20558.csv.gz  in=358,611,831 out=106,472,444 elapsed=157.1s

  [12616/21087] intraday_20559.csv.gz  in=358,627,261 out=106,487,874 elapsed=157.1s

  [12617/21087] intraday_20560.csv.gz  in=358,639,146 out=106,499,759 elapsed=157.1s

  [12618/21087] intraday_20564.csv.gz  in=358,651,104 out=106,511,717 elapsed=157.2s

  [12619/21087] intraday_20563.csv.gz  in=358,665,576 out=106,526,189 elapsed=157.2s

  [12620/21087] intraday_20561.csv.gz  in=358,677,609 out=106,538,222 elapsed=157.2s

  [12621/21087] intraday_20562.csv.gz  in=358,704,265 out=106,563,919 elapsed=157.2s

  [12622/21087] intraday_20565.csv.gz  in=358,715,411 out=106,575,065 elapsed=157.2s

  [12623/21087] intraday_20568.csv.gz  in=358,728,366 out=106,588,020 elapsed=157.2s

  [12624/21087] intraday_20566.csv.gz  in=358,739,393 out=106,599,047 elapsed=157.2s

  [12625/21087] intraday_20567.csv.gz  in=358,751,851 out=106,611,505 elapsed=157.3s

  [12626/21087] intraday_20569.csv.gz  in=358,763,667 out=106,623,321 elapsed=157.3s

  [12627/21087] intraday_2057.csv.gz  in=358,776,724 out=106,623,321 elapsed=157.3s

  [12628/21087] intraday_20570.csv.gz  in=358,786,851 out=106,633,448 elapsed=157.3s

  [12629/21087] intraday_20572.csv.gz  in=358,799,568 out=106,646,165 elapsed=157.3s

  [12630/21087] intraday_20573.csv.gz  in=358,811,881 out=106,658,478 elapsed=157.3s

  [12631/21087] intraday_20571.csv.gz  in=358,825,960 out=106,672,557 elapsed=157.3s

  [12632/21087] intraday_20574.csv.gz  in=358,838,449 out=106,685,046 elapsed=157.3s

  [12633/21087] intraday_20575.csv.gz  in=358,849,230 out=106,695,827 elapsed=157.3s

  [12634/21087] intraday_20576.csv.gz  in=358,860,714 out=106,707,311 elapsed=157.3s

  [12635/21087] intraday_20577.csv.gz  in=358,871,855 out=106,718,452 elapsed=157.4s

  [12636/21087] intraday_2058.csv.gz  in=358,887,171 out=106,718,452 elapsed=157.4s

  [12637/21087] intraday_20578.csv.gz  in=358,900,851 out=106,732,132 elapsed=157.4s

  [12638/21087] intraday_20579.csv.gz  in=358,912,819 out=106,744,100 elapsed=157.4s

  [12639/21087] intraday_20580.csv.gz  in=358,925,842 out=106,757,123 elapsed=157.4s

  [12640/21087] intraday_20582.csv.gz  in=358,937,152 out=106,768,433 elapsed=157.4s

  [12641/21087] intraday_20583.csv.gz  in=358,947,829 out=106,779,110 elapsed=157.4s

  [12642/21087] intraday_20581.csv.gz  in=358,958,360 out=106,789,641 elapsed=157.4s

  [12643/21087] intraday_20584.csv.gz  in=358,971,928 out=106,803,209 elapsed=157.4s

  [12644/21087] intraday_20585.csv.gz  in=358,986,435 out=106,817,716 elapsed=157.5s

  [12645/21087] intraday_20587.csv.gz  in=358,999,299 out=106,830,580 elapsed=157.5s

  [12646/21087] intraday_20586.csv.gz  in=359,013,432 out=106,844,713 elapsed=157.5s

  [12647/21087] intraday_20588.csv.gz  in=359,024,192 out=106,855,473 elapsed=157.5s

  [12648/21087] intraday_20589.csv.gz  in=359,033,454 out=106,864,735 elapsed=157.5s

  [12649/21087] intraday_2059.csv.gz  in=359,045,851 out=106,864,735 elapsed=157.5s

  [12650/21087] intraday_20590.csv.gz  in=359,058,123 out=106,877,007 elapsed=157.5s

  [12651/21087] intraday_20593.csv.gz  in=359,067,464 out=106,886,348 elapsed=157.5s

  [12652/21087] intraday_20591.csv.gz  in=359,079,360 out=106,898,244 elapsed=157.5s

  [12653/21087] intraday_20592.csv.gz  in=359,091,311 out=106,910,195 elapsed=157.5s

  [12654/21087] intraday_20594.csv.gz  in=359,102,647 out=106,921,531 elapsed=157.6s

  [12655/21087] intraday_20595.csv.gz  in=359,113,446 out=106,932,330 elapsed=157.6s

  [12656/21087] intraday_20596.csv.gz  in=359,126,543 out=106,945,427 elapsed=157.6s

  [12657/21087] intraday_20597.csv.gz  in=359,138,598 out=106,957,482 elapsed=157.6s

  [12658/21087] intraday_20598.csv.gz  in=359,152,286 out=106,971,170 elapsed=157.6s

  [12659/21087] intraday_20599.csv.gz  in=359,161,012 out=106,979,896 elapsed=157.6s

  [12660/21087] intraday_2060.csv.gz  in=359,174,379 out=106,979,896 elapsed=157.6s

  [12661/21087] intraday_20600.csv.gz  in=359,185,680 out=106,991,197 elapsed=157.6s

  [12662/21087] intraday_20601.csv.gz  in=359,197,558 out=107,003,075 elapsed=157.6s

  [12663/21087] intraday_20602.csv.gz  in=359,211,309 out=107,016,826 elapsed=157.7s

  [12664/21087] intraday_20603.csv.gz  in=359,226,052 out=107,031,569 elapsed=157.7s

  [12665/21087] intraday_20605.csv.gz  in=359,236,414 out=107,041,931 elapsed=157.7s

  [12666/21087] intraday_20604.csv.gz  in=359,251,794 out=107,057,311 elapsed=157.7s

  [12667/21087] intraday_20607.csv.gz  in=359,261,026 out=107,066,543 elapsed=157.7s

  [12668/21087] intraday_20606.csv.gz  in=359,275,914 out=107,081,431 elapsed=157.7s

  [12669/21087] intraday_20608.csv.gz  in=359,290,061 out=107,095,578 elapsed=157.7s

  [12670/21087] intraday_2061.csv.gz  in=359,304,475 out=107,095,578 elapsed=157.7s

  [12671/21087] intraday_20609.csv.gz  in=359,315,184 out=107,106,287 elapsed=157.7s

  [12672/21087] intraday_20610.csv.gz  in=359,327,478 out=107,118,581 elapsed=157.7s

  [12673/21087] intraday_20611.csv.gz  in=359,337,693 out=107,128,796 elapsed=157.7s

  [12674/21087] intraday_20612.csv.gz  in=359,349,847 out=107,140,950 elapsed=157.8s

  [12675/21087] intraday_20613.csv.gz  in=359,361,869 out=107,152,972 elapsed=157.8s

  [12676/21087] intraday_20614.csv.gz  in=359,374,242 out=107,165,345 elapsed=157.8s

  [12677/21087] intraday_20615.csv.gz  in=359,387,276 out=107,178,379 elapsed=157.8s

  [12678/21087] intraday_20616.csv.gz  in=359,397,718 out=107,188,821 elapsed=157.8s

  [12679/21087] intraday_20617.csv.gz  in=359,409,163 out=107,200,266 elapsed=157.8s

  [12680/21087] intraday_20618.csv.gz  in=359,422,175 out=107,213,278 elapsed=157.8s

  [12681/21087] intraday_20619.csv.gz  in=359,433,662 out=107,224,765 elapsed=157.8s

  [12682/21087] intraday_2062.csv.gz  in=359,446,173 out=107,224,765 elapsed=157.8s

  [12683/21087] intraday_20620.csv.gz  in=359,456,028 out=107,234,620 elapsed=157.8s

  [12684/21087] intraday_20621.csv.gz  in=359,469,380 out=107,247,972 elapsed=157.9s

  [12685/21087] intraday_20622.csv.gz  in=359,482,742 out=107,261,334 elapsed=157.9s

  [12686/21087] intraday_20623.csv.gz  in=359,494,294 out=107,272,886 elapsed=157.9s

  [12687/21087] intraday_20624.csv.gz  in=359,508,234 out=107,286,826 elapsed=157.9s

  [12688/21087] intraday_20625.csv.gz  in=359,518,099 out=107,296,691 elapsed=157.9s

  [12689/21087] intraday_20626.csv.gz  in=359,531,001 out=107,309,593 elapsed=157.9s

  [12690/21087] intraday_20628.csv.gz  in=359,546,111 out=107,324,703 elapsed=157.9s

  [12691/21087] intraday_20627.csv.gz  in=359,560,813 out=107,339,405 elapsed=157.9s

  [12692/21087] intraday_2063.csv.gz  in=359,575,334 out=107,339,405 elapsed=157.9s

  [12693/21087] intraday_20629.csv.gz  in=359,588,507 out=107,352,578 elapsed=157.9s

  [12694/21087] intraday_20633.csv.gz  in=359,601,539 out=107,365,610 elapsed=158.0s

  [12695/21087] intraday_20632.csv.gz  in=359,615,946 out=107,380,017 elapsed=158.0s

  [12696/21087] intraday_20631.csv.gz  in=359,628,843 out=107,392,914 elapsed=158.0s

  [12697/21087] intraday_20630.csv.gz  in=359,642,815 out=107,406,886 elapsed=158.0s

  [12698/21087] intraday_20634.csv.gz  in=359,659,305 out=107,423,376 elapsed=158.0s

  [12699/21087] intraday_20637.csv.gz  in=359,673,001 out=107,437,072 elapsed=158.0s

  [12700/21087] intraday_20636.csv.gz  in=359,687,226 out=107,451,297 elapsed=158.0s

  [12701/21087] intraday_20635.csv.gz  in=359,706,160 out=107,470,231 elapsed=158.0s

  [12702/21087] intraday_20638.csv.gz  in=359,718,038 out=107,482,109 elapsed=158.1s

  [12703/21087] intraday_20639.csv.gz  in=359,731,530 out=107,495,601 elapsed=158.1s

  [12704/21087] intraday_2064.csv.gz  in=359,746,562 out=107,495,601 elapsed=158.1s

  [12705/21087] intraday_20640.csv.gz  in=359,756,840 out=107,505,879 elapsed=158.1s

  [12706/21087] intraday_20641.csv.gz  in=359,769,401 out=107,518,440 elapsed=158.1s

  [12707/21087] intraday_20642.csv.gz  in=359,780,213 out=107,529,252 elapsed=158.1s

  [12708/21087] intraday_20643.csv.gz  in=359,791,096 out=107,540,135 elapsed=158.1s

  [12709/21087] intraday_20644.csv.gz  in=359,803,574 out=107,552,613 elapsed=158.1s

  [12710/21087] intraday_20645.csv.gz  in=359,818,737 out=107,567,776 elapsed=158.1s

  [12711/21087] intraday_20646.csv.gz  in=359,829,603 out=107,578,642 elapsed=158.1s

  [12712/21087] intraday_20647.csv.gz  in=359,840,810 out=107,589,849 elapsed=158.2s

  [12713/21087] intraday_20648.csv.gz  in=359,853,994 out=107,603,033 elapsed=158.2s

  [12714/21087] intraday_2065.csv.gz  in=359,869,181 out=107,603,033 elapsed=158.2s

  [12715/21087] intraday_20649.csv.gz  in=359,880,986 out=107,614,838 elapsed=158.2s

  [12716/21087] intraday_20650.csv.gz  in=359,893,297 out=107,627,149 elapsed=158.2s

  [12717/21087] intraday_20651.csv.gz  in=359,906,179 out=107,640,031 elapsed=158.2s

  [12718/21087] intraday_20653.csv.gz  in=359,918,426 out=107,652,278 elapsed=158.2s

  [12719/21087] intraday_20652.csv.gz  in=359,932,593 out=107,666,445 elapsed=158.2s

  [12720/21087] intraday_20654.csv.gz  in=359,945,490 out=107,679,342 elapsed=158.2s

  [12721/21087] intraday_20655.csv.gz  in=359,958,629 out=107,692,481 elapsed=158.2s

  [12722/21087] intraday_20656.csv.gz  in=359,971,627 out=107,705,479 elapsed=158.3s

  [12723/21087] intraday_20657.csv.gz  in=359,981,475 out=107,715,327 elapsed=158.3s

  [12724/21087] intraday_20659.csv.gz  in=359,990,445 out=107,724,297 elapsed=158.3s

  [12725/21087] intraday_2066.csv.gz  in=360,003,914 out=107,724,297 elapsed=158.3s

  [12726/21087] intraday_20658.csv.gz  in=360,021,213 out=107,741,534 elapsed=158.3s

  [12727/21087] intraday_20661.csv.gz  in=360,032,233 out=107,752,554 elapsed=158.3s

  [12728/21087] intraday_20662.csv.gz  in=360,032,912 out=107,753,233 elapsed=158.3s

  [12729/21087] intraday_20660.csv.gz  in=360,040,860 out=107,761,181 elapsed=158.3s

  [12730/21087] intraday_20663.csv.gz  in=360,056,802 out=107,777,123 elapsed=158.3s

  [12731/21087] intraday_20665.csv.gz  in=360,069,244 out=107,789,565 elapsed=158.4s

  [12732/21087] intraday_20664.csv.gz  in=360,081,755 out=107,802,076 elapsed=158.4s

  [12733/21087] intraday_20666.csv.gz  in=360,092,708 out=107,813,029 elapsed=158.4s

  [12734/21087] intraday_20667.csv.gz  in=360,105,473 out=107,825,794 elapsed=158.4s

  [12735/21087] intraday_2067.csv.gz  in=360,117,445 out=107,825,794 elapsed=158.4s

  [12736/21087] intraday_20668.csv.gz  in=360,131,241 out=107,839,590 elapsed=158.4s

  [12737/21087] intraday_20669.csv.gz  in=360,143,871 out=107,852,220 elapsed=158.4s

  [12738/21087] intraday_20670.csv.gz  in=360,156,086 out=107,864,435 elapsed=158.4s

  [12739/21087] intraday_20671.csv.gz  in=360,168,623 out=107,876,972 elapsed=158.5s

  [12740/21087] intraday_20673.csv.gz  in=360,177,890 out=107,886,239 elapsed=158.5s

  [12741/21087] intraday_20672.csv.gz  in=360,190,104 out=107,898,453 elapsed=158.5s

  [12742/21087] intraday_20674.csv.gz  in=360,201,664 out=107,910,013 elapsed=158.5s

  [12743/21087] intraday_20675.csv.gz  in=360,214,712 out=107,923,061 elapsed=158.5s

  [12744/21087] intraday_20677.csv.gz  in=360,224,183 out=107,932,532 elapsed=158.5s

  [12745/21087] intraday_20678.csv.gz  in=360,234,811 out=107,943,160 elapsed=158.5s

  [12746/21087] intraday_20676.csv.gz  in=360,245,753 out=107,954,102 elapsed=158.5s

  [12747/21087] intraday_20679.csv.gz  in=360,260,971 out=107,969,320 elapsed=158.6s

  [12748/21087] intraday_2068.csv.gz  in=360,277,133 out=107,969,320 elapsed=158.6s

  [12749/21087] intraday_20681.csv.gz  in=360,287,555 out=107,979,742 elapsed=158.6s

  [12750/21087] intraday_20680.csv.gz  in=360,300,474 out=107,992,661 elapsed=158.6s

  [12751/21087] intraday_20682.csv.gz  in=360,310,541 out=108,002,728 elapsed=158.6s

  [12752/21087] intraday_20683.csv.gz  in=360,322,778 out=108,014,965 elapsed=158.6s

  [12753/21087] intraday_20685.csv.gz  in=360,333,753 out=108,025,940 elapsed=158.6s

  [12754/21087] intraday_20684.csv.gz  in=360,345,328 out=108,037,515 elapsed=158.6s

  [12755/21087] intraday_20687.csv.gz  in=360,358,306 out=108,050,493 elapsed=158.7s

  [12756/21087] intraday_20686.csv.gz  in=360,369,166 out=108,061,353 elapsed=158.7s

  [12757/21087] intraday_20688.csv.gz  in=360,381,321 out=108,073,508 elapsed=158.7s

  [12758/21087] intraday_2069.csv.gz  in=360,394,459 out=108,073,508 elapsed=158.7s

  [12759/21087] intraday_20689.csv.gz  in=360,407,014 out=108,086,063 elapsed=158.7s

  [12760/21087] intraday_20690.csv.gz  in=360,417,297 out=108,096,346 elapsed=158.7s

  [12761/21087] intraday_20691.csv.gz  in=360,430,975 out=108,110,024 elapsed=158.7s

  [12762/21087] intraday_20692.csv.gz  in=360,444,775 out=108,123,824 elapsed=158.7s

  [12763/21087] intraday_20693.csv.gz  in=360,457,252 out=108,136,301 elapsed=158.7s

  [12764/21087] intraday_20694.csv.gz  in=360,468,331 out=108,147,380 elapsed=158.7s

  [12765/21087] intraday_20695.csv.gz  in=360,480,074 out=108,159,123 elapsed=158.7s

  [12766/21087] intraday_20696.csv.gz  in=360,491,313 out=108,170,362 elapsed=158.8s

  [12767/21087] intraday_20697.csv.gz  in=360,503,289 out=108,182,338 elapsed=158.8s

  [12768/21087] intraday_20698.csv.gz  in=360,516,910 out=108,195,959 elapsed=158.8s

  [12769/21087] intraday_20699.csv.gz  in=360,526,729 out=108,205,778 elapsed=158.8s

  [12770/21087] intraday_2070.csv.gz  in=360,539,107 out=108,205,778 elapsed=158.8s

  [12771/21087] intraday_20700.csv.gz  in=360,549,861 out=108,216,532 elapsed=158.8s

  [12772/21087] intraday_20702.csv.gz  in=360,559,099 out=108,225,770 elapsed=158.8s

  [12773/21087] intraday_20701.csv.gz  in=360,569,295 out=108,235,966 elapsed=158.8s

  [12774/21087] intraday_20703.csv.gz  in=360,582,219 out=108,248,890 elapsed=158.8s

  [12775/21087] intraday_20704.csv.gz  in=360,593,285 out=108,259,956 elapsed=158.8s

  [12776/21087] intraday_20707.csv.gz  in=360,604,977 out=108,271,648 elapsed=158.9s

  [12777/21087] intraday_20706.csv.gz  in=360,618,280 out=108,284,951 elapsed=158.9s

  [12778/21087] intraday_20708.csv.gz  in=360,628,802 out=108,295,473 elapsed=158.9s

  [12779/21087] intraday_20705.csv.gz  in=360,642,285 out=108,308,956 elapsed=158.9s

  [12780/21087] intraday_20709.csv.gz  in=360,654,470 out=108,321,141 elapsed=158.9s

  [12781/21087] intraday_2071.csv.gz  in=360,669,850 out=108,321,141 elapsed=158.9s

  [12782/21087] intraday_20710.csv.gz  in=360,681,335 out=108,332,626 elapsed=158.9s

  [12783/21087] intraday_20711.csv.gz  in=360,694,967 out=108,346,258 elapsed=158.9s

  [12784/21087] intraday_20712.csv.gz  in=360,705,782 out=108,357,073 elapsed=159.0s

  [12785/21087] intraday_20713.csv.gz  in=360,717,753 out=108,369,044 elapsed=159.0s

  [12786/21087] intraday_20714.csv.gz  in=360,729,497 out=108,380,788 elapsed=159.0s

  [12787/21087] intraday_20715.csv.gz  in=360,742,312 out=108,393,603 elapsed=159.0s

  [12788/21087] intraday_20716.csv.gz  in=360,754,742 out=108,406,033 elapsed=159.0s

  [12789/21087] intraday_20717.csv.gz  in=360,766,354 out=108,417,645 elapsed=159.0s

  [12790/21087] intraday_20718.csv.gz  in=360,777,067 out=108,428,358 elapsed=159.0s

  [12791/21087] intraday_20719.csv.gz  in=360,793,063 out=108,444,354 elapsed=159.0s

  [12792/21087] intraday_2072.csv.gz  in=360,800,690 out=108,444,354 elapsed=159.0s

  [12793/21087] intraday_20720.csv.gz  in=360,813,196 out=108,456,860 elapsed=159.0s

  [12794/21087] intraday_20721.csv.gz  in=360,825,746 out=108,469,410 elapsed=159.1s

  [12795/21087] intraday_20722.csv.gz  in=360,837,438 out=108,481,102 elapsed=159.1s

  [12796/21087] intraday_20723.csv.gz  in=360,849,750 out=108,493,414 elapsed=159.1s

  [12797/21087] intraday_20724.csv.gz  in=360,861,367 out=108,505,031 elapsed=159.1s

  [12798/21087] intraday_20725.csv.gz  in=360,871,392 out=108,515,056 elapsed=159.1s

  [12799/21087] intraday_20726.csv.gz  in=360,884,502 out=108,528,166 elapsed=159.1s

  [12800/21087] intraday_20728.csv.gz  in=360,897,151 out=108,540,815 elapsed=159.1s

  [12801/21087] intraday_20727.csv.gz  in=360,911,043 out=108,554,707 elapsed=159.1s

  [12802/21087] intraday_2073.csv.gz  in=360,922,008 out=108,554,707 elapsed=159.1s

  [12803/21087] intraday_20729.csv.gz  in=360,935,690 out=108,568,389 elapsed=159.1s

  [12804/21087] intraday_20730.csv.gz  in=360,947,488 out=108,580,187 elapsed=159.2s

  [12805/21087] intraday_20731.csv.gz  in=360,961,992 out=108,594,691 elapsed=159.2s

  [12806/21087] intraday_20733.csv.gz  in=360,974,549 out=108,607,248 elapsed=159.2s

  [12807/21087] intraday_20734.csv.gz  in=360,985,677 out=108,618,375 elapsed=159.2s

  [12808/21087] intraday_20732.csv.gz  in=360,996,991 out=108,629,689 elapsed=159.2s

  [12809/21087] intraday_20735.csv.gz  in=361,008,006 out=108,640,704 elapsed=159.2s

  [12810/21087] intraday_20736.csv.gz  in=361,018,548 out=108,651,246 elapsed=159.2s

  [12811/21087] intraday_20737.csv.gz  in=361,029,108 out=108,661,806 elapsed=159.2s

  [12812/21087] intraday_20738.csv.gz  in=361,040,944 out=108,673,642 elapsed=159.2s

  [12813/21087] intraday_2074.csv.gz  in=361,047,061 out=108,673,642 elapsed=159.2s

  [12814/21087] intraday_20739.csv.gz  in=361,060,353 out=108,686,934 elapsed=159.3s

  [12815/21087] intraday_20740.csv.gz  in=361,071,866 out=108,698,447 elapsed=159.3s

  [12816/21087] intraday_20741.csv.gz  in=361,084,532 out=108,711,113 elapsed=159.3s

  [12817/21087] intraday_20743.csv.gz  in=361,094,582 out=108,721,163 elapsed=159.3s

  [12818/21087] intraday_20742.csv.gz  in=361,104,491 out=108,731,072 elapsed=159.3s

  [12819/21087] intraday_20744.csv.gz  in=361,117,241 out=108,743,822 elapsed=159.3s

  [12820/21087] intraday_20745.csv.gz  in=361,132,783 out=108,759,364 elapsed=159.4s

  [12821/21087] intraday_20747.csv.gz  in=361,147,081 out=108,773,662 elapsed=159.4s

  [12822/21087] intraday_20746.csv.gz  in=361,159,942 out=108,786,400 elapsed=159.4s

  [12823/21087] intraday_20748.csv.gz  in=361,171,724 out=108,798,182 elapsed=159.4s

  [12824/21087] intraday_2075.csv.gz  in=361,186,516 out=108,798,182 elapsed=159.4s

  [12825/21087] intraday_20750.csv.gz  in=361,198,404 out=108,810,070 elapsed=159.4s

  [12826/21087] intraday_20749.csv.gz  in=361,211,529 out=108,823,195 elapsed=159.4s

  [12827/21087] intraday_20751.csv.gz  in=361,224,398 out=108,836,064 elapsed=159.4s

  [12828/21087] intraday_20752.csv.gz  in=361,234,342 out=108,846,008 elapsed=159.4s

  [12829/21087] intraday_20753.csv.gz  in=361,247,265 out=108,858,931 elapsed=159.4s

  [12830/21087] intraday_20754.csv.gz  in=361,258,828 out=108,870,494 elapsed=159.5s

  [12831/21087] intraday_20756.csv.gz  in=361,270,922 out=108,882,588 elapsed=159.5s

  [12832/21087] intraday_20755.csv.gz  in=361,282,122 out=108,893,788 elapsed=159.5s

  [12833/21087] intraday_20757.csv.gz  in=361,294,214 out=108,905,880 elapsed=159.5s

  [12834/21087] intraday_20759.csv.gz  in=361,305,703 out=108,917,369 elapsed=159.5s

  [12835/21087] intraday_2076.csv.gz  in=361,320,259 out=108,917,369 elapsed=159.5s

  [12836/21087] intraday_20758.csv.gz  in=361,331,471 out=108,928,581 elapsed=159.5s

  [12837/21087] intraday_20760.csv.gz  in=361,342,586 out=108,939,696 elapsed=159.5s

  [12838/21087] intraday_20762.csv.gz  in=361,354,110 out=108,951,220 elapsed=159.6s

  [12839/21087] intraday_20761.csv.gz  in=361,368,076 out=108,965,186 elapsed=159.6s

  [12840/21087] intraday_20763.csv.gz  in=361,379,608 out=108,976,718 elapsed=159.6s

  [12841/21087] intraday_20764.csv.gz  in=361,391,391 out=108,988,501 elapsed=159.6s

  [12842/21087] intraday_20765.csv.gz  in=361,405,130 out=109,002,240 elapsed=159.6s

  [12843/21087] intraday_20767.csv.gz  in=361,418,777 out=109,015,887 elapsed=159.6s

  [12844/21087] intraday_20768.csv.gz  in=361,428,876 out=109,025,986 elapsed=159.6s

  [12845/21087] intraday_20766.csv.gz  in=361,439,878 out=109,036,988 elapsed=159.6s

  [12846/21087] intraday_20769.csv.gz  in=361,452,239 out=109,049,349 elapsed=159.6s

  [12847/21087] intraday_2077.csv.gz  in=361,464,221 out=109,049,349 elapsed=159.6s

  [12848/21087] intraday_20770.csv.gz  in=361,478,810 out=109,063,938 elapsed=159.6s

  [12849/21087] intraday_20771.csv.gz  in=361,492,305 out=109,077,433 elapsed=159.7s

  [12850/21087] intraday_20773.csv.gz  in=361,506,929 out=109,092,057 elapsed=159.7s

  [12851/21087] intraday_20772.csv.gz  in=361,520,247 out=109,105,375 elapsed=159.7s

  [12852/21087] intraday_20775.csv.gz  in=361,533,837 out=109,118,965 elapsed=159.7s

  [12853/21087] intraday_20774.csv.gz  in=361,547,282 out=109,132,410 elapsed=159.7s

  [12854/21087] intraday_20776.csv.gz  in=361,562,804 out=109,147,932 elapsed=159.7s

  [12855/21087] intraday_20777.csv.gz  in=361,578,016 out=109,163,144 elapsed=159.7s

  [12856/21087] intraday_20778.csv.gz  in=361,594,297 out=109,179,425 elapsed=159.7s

  [12857/21087] intraday_20779.csv.gz  in=361,609,877 out=109,195,005 elapsed=159.7s

  [12858/21087] intraday_2078.csv.gz  in=361,620,735 out=109,195,005 elapsed=159.7s

  [12859/21087] intraday_20780.csv.gz  in=361,633,502 out=109,207,768 elapsed=159.8s

  [12860/21087] intraday_20781.csv.gz  in=361,646,061 out=109,220,327 elapsed=159.8s

  [12861/21087] intraday_20782.csv.gz  in=361,658,154 out=109,232,420 elapsed=159.8s

  [12862/21087] intraday_20783.csv.gz  in=361,669,002 out=109,243,268 elapsed=159.8s

  [12863/21087] intraday_20784.csv.gz  in=361,680,254 out=109,254,520 elapsed=159.8s

  [12864/21087] intraday_20785.csv.gz  in=361,692,633 out=109,266,899 elapsed=159.8s

  [12865/21087] intraday_20786.csv.gz  in=361,703,783 out=109,278,049 elapsed=159.8s

  [12866/21087] intraday_20788.csv.gz  in=361,714,361 out=109,288,627 elapsed=159.8s

  [12867/21087] intraday_20787.csv.gz  in=361,730,286 out=109,304,552 elapsed=159.8s

  [12868/21087] intraday_20789.csv.gz  in=361,742,521 out=109,316,787 elapsed=159.9s

  [12869/21087] intraday_20791.csv.gz  in=361,755,496 out=109,329,762 elapsed=159.9s

  [12870/21087] intraday_20790.csv.gz  in=361,766,897 out=109,341,163 elapsed=159.9s

  [12871/21087] intraday_2079.csv.gz  in=361,780,974 out=109,341,163 elapsed=159.9s

  [12872/21087] intraday_20792.csv.gz  in=361,791,936 out=109,352,125 elapsed=159.9s

  [12873/21087] intraday_20795.csv.gz  in=361,805,293 out=109,365,482 elapsed=160.0s

  [12874/21087] intraday_20793.csv.gz  in=361,818,252 out=109,378,441 elapsed=160.0s

  [12875/21087] intraday_20794.csv.gz  in=361,832,073 out=109,392,262 elapsed=160.0s

  [12876/21087] intraday_20796.csv.gz  in=361,845,603 out=109,405,792 elapsed=160.0s

  [12877/21087] intraday_2080.csv.gz  in=361,859,998 out=109,405,792 elapsed=160.0s

  [12878/21087] intraday_20797.csv.gz  in=361,870,867 out=109,416,661 elapsed=160.0s

  [12879/21087] intraday_20799.csv.gz  in=361,883,242 out=109,429,036 elapsed=160.0s

  [12880/21087] intraday_20798.csv.gz  in=361,897,310 out=109,443,104 elapsed=160.0s

  [12881/21087] intraday_20800.csv.gz  in=361,907,973 out=109,453,767 elapsed=160.0s

  [12882/21087] intraday_20802.csv.gz  in=361,915,982 out=109,461,776 elapsed=160.1s

  [12883/21087] intraday_20804.csv.gz  in=361,923,754 out=109,469,548 elapsed=160.1s

  [12884/21087] intraday_20803.csv.gz  in=361,934,136 out=109,479,930 elapsed=160.1s

  [12885/21087] intraday_20801.csv.gz  in=361,946,743 out=109,492,537 elapsed=160.1s

  [12886/21087] intraday_20805.csv.gz  in=361,964,917 out=109,510,711 elapsed=160.1s

  [12887/21087] intraday_20807.csv.gz  in=361,979,332 out=109,525,126 elapsed=160.1s

  [12888/21087] intraday_20808.csv.gz  in=361,988,931 out=109,534,725 elapsed=160.1s

  [12889/21087] intraday_20806.csv.gz  in=362,003,033 out=109,548,827 elapsed=160.1s

  [12890/21087] intraday_20809.csv.gz  in=362,018,070 out=109,563,864 elapsed=160.1s

  [12891/21087] intraday_2081.csv.gz  in=362,030,313 out=109,563,864 elapsed=160.2s

  [12892/21087] intraday_20810.csv.gz  in=362,044,986 out=109,578,537 elapsed=160.2s

  [12893/21087] intraday_20812.csv.gz  in=362,056,955 out=109,590,506 elapsed=160.2s

  [12894/21087] intraday_20811.csv.gz  in=362,071,243 out=109,604,794 elapsed=160.2s

  [12895/21087] intraday_20813.csv.gz  in=362,083,879 out=109,617,430 elapsed=160.2s

  [12896/21087] intraday_20814.csv.gz  in=362,096,736 out=109,630,287 elapsed=160.2s

  [12897/21087] intraday_20815.csv.gz  in=362,108,094 out=109,641,645 elapsed=160.2s

  [12898/21087] intraday_20817.csv.gz  in=362,122,579 out=109,656,130 elapsed=160.3s

  [12899/21087] intraday_20816.csv.gz  in=362,134,983 out=109,668,534 elapsed=160.3s

  [12900/21087] intraday_20819.csv.gz  in=362,145,752 out=109,679,246 elapsed=160.3s

  [12901/21087] intraday_20818.csv.gz  in=362,158,851 out=109,692,345 elapsed=160.3s

  [12902/21087] intraday_2082.csv.gz  in=362,171,702 out=109,692,345 elapsed=160.3s

  [12903/21087] intraday_20820.csv.gz  in=362,182,742 out=109,703,382 elapsed=160.3s

  [12904/21087] intraday_20821.csv.gz  in=362,198,928 out=109,719,568 elapsed=160.3s

  [12905/21087] intraday_20822.csv.gz  in=362,212,921 out=109,733,561 elapsed=160.3s

  [12906/21087] intraday_20824.csv.gz  in=362,224,035 out=109,744,675 elapsed=160.3s

  [12907/21087] intraday_20823.csv.gz  in=362,235,918 out=109,756,558 elapsed=160.3s

  [12908/21087] intraday_20826.csv.gz  in=362,248,698 out=109,769,338 elapsed=160.4s

  [12909/21087] intraday_20825.csv.gz  in=362,261,699 out=109,782,339 elapsed=160.4s

  [12910/21087] intraday_20827.csv.gz  in=362,274,209 out=109,794,849 elapsed=160.4s

  [12911/21087] intraday_20828.csv.gz  in=362,285,510 out=109,806,150 elapsed=160.4s

  [12912/21087] intraday_20829.csv.gz  in=362,298,177 out=109,818,817 elapsed=160.4s

  [12913/21087] intraday_2083.csv.gz  in=362,312,597 out=109,818,817 elapsed=160.4s

  [12914/21087] intraday_20831.csv.gz  in=362,327,102 out=109,833,322 elapsed=160.4s

  [12915/21087] intraday_20830.csv.gz  in=362,354,612 out=109,860,459 elapsed=160.4s

  [12916/21087] intraday_20832.csv.gz  in=362,366,823 out=109,872,670 elapsed=160.4s

  [12917/21087] intraday_20833.csv.gz  in=362,380,351 out=109,886,198 elapsed=160.4s

  [12918/21087] intraday_20836.csv.gz  in=362,392,168 out=109,898,015 elapsed=160.5s

  [12919/21087] intraday_20837.csv.gz  in=362,403,475 out=109,909,322 elapsed=160.5s

  [12920/21087] intraday_20834.csv.gz  in=362,417,824 out=109,923,671 elapsed=160.5s

  [12921/21087] intraday_20835.csv.gz  in=362,432,253 out=109,938,100 elapsed=160.5s

  [12922/21087] intraday_20838.csv.gz  in=362,444,863 out=109,950,710 elapsed=160.5s

  [12923/21087] intraday_2084.csv.gz  in=362,460,179 out=109,950,710 elapsed=160.5s

  [12924/21087] intraday_20839.csv.gz  in=362,472,590 out=109,963,121 elapsed=160.5s

  [12925/21087] intraday_20840.csv.gz  in=362,486,078 out=109,976,609 elapsed=160.5s

  [12926/21087] intraday_20841.csv.gz  in=362,498,566 out=109,989,097 elapsed=160.6s

  [12927/21087] intraday_20844.csv.gz  in=362,508,561 out=109,999,092 elapsed=160.6s

  [12928/21087] intraday_20843.csv.gz  in=362,519,838 out=110,010,369 elapsed=160.6s

  [12929/21087] intraday_20842.csv.gz  in=362,531,019 out=110,021,550 elapsed=160.6s

  [12930/21087] intraday_20845.csv.gz  in=362,544,223 out=110,034,754 elapsed=160.6s

  [12931/21087] intraday_20846.csv.gz  in=362,556,768 out=110,047,299 elapsed=160.6s

  [12932/21087] intraday_20847.csv.gz  in=362,569,840 out=110,060,371 elapsed=160.6s

  [12933/21087] intraday_20849.csv.gz  in=362,582,327 out=110,072,858 elapsed=160.6s

  [12934/21087] intraday_20848.csv.gz  in=362,597,364 out=110,087,895 elapsed=160.6s

  [12935/21087] intraday_2085.csv.gz  in=362,607,282 out=110,087,895 elapsed=160.6s

  [12936/21087] intraday_20850.csv.gz  in=362,619,548 out=110,100,161 elapsed=160.7s

  [12937/21087] intraday_20851.csv.gz  in=362,631,218 out=110,111,831 elapsed=160.7s

  [12938/21087] intraday_20852.csv.gz  in=362,644,405 out=110,125,018 elapsed=160.7s

  [12939/21087] intraday_20853.csv.gz  in=362,658,123 out=110,138,736 elapsed=160.7s

  [12940/21087] intraday_20854.csv.gz  in=362,669,717 out=110,150,330 elapsed=160.7s

  [12941/21087] intraday_20855.csv.gz  in=362,682,816 out=110,163,429 elapsed=160.7s

  [12942/21087] intraday_20857.csv.gz  in=362,698,146 out=110,178,732 elapsed=160.7s

  [12943/21087] intraday_20856.csv.gz  in=362,713,219 out=110,193,805 elapsed=160.7s

  [12944/21087] intraday_20858.csv.gz  in=362,726,249 out=110,206,835 elapsed=160.7s

  [12945/21087] intraday_2086.csv.gz  in=362,738,040 out=110,206,835 elapsed=160.8s

  [12946/21087] intraday_20859.csv.gz  in=362,751,391 out=110,220,186 elapsed=160.8s

  [12947/21087] intraday_20861.csv.gz  in=362,769,841 out=110,238,418 elapsed=160.8s

  [12948/21087] intraday_20860.csv.gz  in=362,781,411 out=110,249,988 elapsed=160.8s

  [12949/21087] intraday_20862.csv.gz  in=362,793,331 out=110,261,908 elapsed=160.8s

  [12950/21087] intraday_20863.csv.gz  in=362,807,076 out=110,275,653 elapsed=160.8s

  [12951/21087] intraday_20864.csv.gz  in=362,820,240 out=110,288,817 elapsed=160.8s

  [12952/21087] intraday_20866.csv.gz  in=362,832,305 out=110,300,882 elapsed=160.8s

  [12953/21087] intraday_20865.csv.gz  in=362,845,286 out=110,313,863 elapsed=160.8s

  [12954/21087] intraday_20867.csv.gz  in=362,856,977 out=110,325,554 elapsed=160.8s

  [12955/21087] intraday_20868.csv.gz  in=362,869,228 out=110,337,805 elapsed=160.9s

  [12956/21087] intraday_2087.csv.gz  in=362,882,964 out=110,337,805 elapsed=160.9s

  [12957/21087] intraday_20869.csv.gz  in=362,896,763 out=110,351,604 elapsed=160.9s

  [12958/21087] intraday_20870.csv.gz  in=362,911,482 out=110,366,323 elapsed=160.9s

  [12959/21087] intraday_20871.csv.gz  in=362,926,039 out=110,380,880 elapsed=160.9s

  [12960/21087] intraday_20872.csv.gz  in=362,938,499 out=110,393,340 elapsed=160.9s

  [12961/21087] intraday_20873.csv.gz  in=362,949,700 out=110,404,541 elapsed=160.9s

  [12962/21087] intraday_20874.csv.gz  in=362,959,914 out=110,414,755 elapsed=161.0s

  [12963/21087] intraday_20876.csv.gz  in=362,972,469 out=110,427,310 elapsed=161.0s

  [12964/21087] intraday_20875.csv.gz  in=362,986,065 out=110,440,906 elapsed=161.0s

  [12965/21087] intraday_20877.csv.gz  in=362,997,973 out=110,452,814 elapsed=161.0s

  [12966/21087] intraday_2088.csv.gz  in=363,009,242 out=110,452,814 elapsed=161.0s

  [12967/21087] intraday_20878.csv.gz  in=363,019,784 out=110,463,356 elapsed=161.0s

  [12968/21087] intraday_20879.csv.gz  in=363,032,556 out=110,476,128 elapsed=161.0s

  [12969/21087] intraday_20880.csv.gz  in=363,043,437 out=110,487,009 elapsed=161.0s

  [12970/21087] intraday_20881.csv.gz  in=363,057,554 out=110,501,126 elapsed=161.0s

  [12971/21087] intraday_20884.csv.gz  in=363,066,922 out=110,510,494 elapsed=161.0s

  [12972/21087] intraday_20882.csv.gz  in=363,079,659 out=110,523,231 elapsed=161.1s

  [12973/21087] intraday_20883.csv.gz  in=363,094,276 out=110,537,848 elapsed=161.1s

  [12974/21087] intraday_20885.csv.gz  in=363,105,867 out=110,549,439 elapsed=161.1s

  [12975/21087] intraday_20886.csv.gz  in=363,120,069 out=110,563,641 elapsed=161.1s

  [12976/21087] intraday_2089.csv.gz  in=363,131,315 out=110,563,641 elapsed=161.1s

  [12977/21087] intraday_20887.csv.gz  in=363,148,027 out=110,580,353 elapsed=161.1s

  [12978/21087] intraday_20888.csv.gz  in=363,162,660 out=110,594,986 elapsed=161.1s

  [12979/21087] intraday_20889.csv.gz  in=363,180,531 out=110,612,857 elapsed=161.1s

  [12980/21087] intraday_20890.csv.gz  in=363,192,187 out=110,624,513 elapsed=161.1s

  [12981/21087] intraday_20892.csv.gz  in=363,204,210 out=110,636,536 elapsed=161.2s

  [12982/21087] intraday_20891.csv.gz  in=363,219,369 out=110,651,695 elapsed=161.2s

  [12983/21087] intraday_20893.csv.gz  in=363,234,468 out=110,666,794 elapsed=161.2s

  [12984/21087] intraday_20894.csv.gz  in=363,244,464 out=110,676,790 elapsed=161.2s

  [12985/21087] intraday_20895.csv.gz  in=363,259,063 out=110,691,389 elapsed=161.2s

  [12986/21087] intraday_20896.csv.gz  in=363,269,314 out=110,701,640 elapsed=161.3s

  [12987/21087] intraday_20897.csv.gz  in=363,282,108 out=110,714,434 elapsed=161.3s

  [12988/21087] intraday_20899.csv.gz  in=363,294,886 out=110,727,212 elapsed=161.3s

  [12989/21087] intraday_20898.csv.gz  in=363,308,709 out=110,741,035 elapsed=161.3s

  [12990/21087] intraday_2090.csv.gz  in=363,321,315 out=110,741,035 elapsed=161.3s

  [12991/21087] intraday_20900.csv.gz  in=363,335,327 out=110,755,047 elapsed=161.3s

  [12992/21087] intraday_20902.csv.gz  in=363,348,098 out=110,767,818 elapsed=161.3s

  [12993/21087] intraday_20903.csv.gz  in=363,359,809 out=110,779,529 elapsed=161.3s

  [12994/21087] intraday_20901.csv.gz  in=363,371,029 out=110,790,749 elapsed=161.3s

  [12995/21087] intraday_20904.csv.gz  in=363,383,250 out=110,802,970 elapsed=161.3s

  [12996/21087] intraday_20906.csv.gz  in=363,397,722 out=110,817,442 elapsed=161.4s

  [12997/21087] intraday_20907.csv.gz  in=363,412,819 out=110,832,539 elapsed=161.4s

  [12998/21087] intraday_20908.csv.gz  in=363,424,198 out=110,843,918 elapsed=161.4s

  [12999/21087] intraday_20905.csv.gz  in=363,445,086 out=110,864,541 elapsed=161.4s

  [13000/21087] intraday_20909.csv.gz  in=363,458,074 out=110,877,529 elapsed=161.4s

  [13001/21087] intraday_2091.csv.gz  in=363,470,645 out=110,877,529 elapsed=161.4s

  [13002/21087] intraday_20910.csv.gz  in=363,482,397 out=110,889,281 elapsed=161.4s

  [13003/21087] intraday_20911.csv.gz  in=363,494,804 out=110,901,688 elapsed=161.4s

  [13004/21087] intraday_20912.csv.gz  in=363,511,012 out=110,917,896 elapsed=161.4s

  [13005/21087] intraday_20913.csv.gz  in=363,527,273 out=110,934,157 elapsed=161.5s

  [13006/21087] intraday_20914.csv.gz  in=363,541,126 out=110,948,010 elapsed=161.5s

  [13007/21087] intraday_20915.csv.gz  in=363,556,292 out=110,963,176 elapsed=161.5s

  [13008/21087] intraday_20916.csv.gz  in=363,571,048 out=110,977,932 elapsed=161.5s

  [13009/21087] intraday_20917.csv.gz  in=363,586,184 out=110,993,068 elapsed=161.5s

  [13010/21087] intraday_2092.csv.gz  in=363,598,915 out=110,993,068 elapsed=161.5s

  [13011/21087] intraday_20918.csv.gz  in=363,613,650 out=111,007,803 elapsed=161.5s

  [13012/21087] intraday_20919.csv.gz  in=363,630,236 out=111,024,389 elapsed=161.6s

  [13013/21087] intraday_20920.csv.gz  in=363,649,723 out=111,043,876 elapsed=161.6s

  [13014/21087] intraday_20922.csv.gz  in=363,664,350 out=111,058,503 elapsed=161.6s

  [13015/21087] intraday_20921.csv.gz  in=363,681,385 out=111,075,538 elapsed=161.6s

  [13016/21087] intraday_20923.csv.gz  in=363,694,427 out=111,088,580 elapsed=161.6s

  [13017/21087] intraday_20924.csv.gz  in=363,708,737 out=111,102,890 elapsed=161.6s

  [13018/21087] intraday_20925.csv.gz  in=363,720,124 out=111,114,277 elapsed=161.6s

  [13019/21087] intraday_20926.csv.gz  in=363,732,574 out=111,126,727 elapsed=161.6s

  [13020/21087] intraday_20927.csv.gz  in=363,744,068 out=111,138,221 elapsed=161.6s

  [13021/21087] intraday_20928.csv.gz  in=363,756,055 out=111,150,208 elapsed=161.6s

  [13022/21087] intraday_2093.csv.gz  in=363,768,235 out=111,150,208 elapsed=161.6s

  [13023/21087] intraday_20929.csv.gz  in=363,783,596 out=111,165,569 elapsed=161.6s

  [13024/21087] intraday_20931.csv.gz  in=363,795,728 out=111,177,701 elapsed=161.7s

  [13025/21087] intraday_20930.csv.gz  in=363,811,258 out=111,193,231 elapsed=161.7s

  [13026/21087] intraday_20932.csv.gz  in=363,823,442 out=111,205,415 elapsed=161.7s

  [13027/21087] intraday_20933.csv.gz  in=363,838,438 out=111,220,411 elapsed=161.7s

  [13028/21087] intraday_20934.csv.gz  in=363,851,594 out=111,233,567 elapsed=161.7s

  [13029/21087] intraday_20935.csv.gz  in=363,864,181 out=111,246,154 elapsed=161.7s

  [13030/21087] intraday_20936.csv.gz  in=363,878,466 out=111,260,439 elapsed=161.7s

  [13031/21087] intraday_20937.csv.gz  in=363,893,441 out=111,275,414 elapsed=161.7s

  [13032/21087] intraday_20938.csv.gz  in=363,906,388 out=111,288,361 elapsed=161.7s

  [13033/21087] intraday_20939.csv.gz  in=363,919,431 out=111,301,404 elapsed=161.8s

  [13034/21087] intraday_2094.csv.gz  in=363,931,656 out=111,301,404 elapsed=161.8s

  [13035/21087] intraday_20941.csv.gz  in=363,945,534 out=111,315,282 elapsed=161.8s

  [13036/21087] intraday_20940.csv.gz  in=363,960,423 out=111,330,171 elapsed=161.8s

  [13037/21087] intraday_20942.csv.gz  in=363,971,159 out=111,340,907 elapsed=161.8s

  [13038/21087] intraday_20943.csv.gz  in=363,987,056 out=111,356,804 elapsed=161.8s

  [13039/21087] intraday_20945.csv.gz  in=363,996,652 out=111,366,400 elapsed=161.8s

  [13040/21087] intraday_20944.csv.gz  in=364,006,298 out=111,376,046 elapsed=161.9s

  [13041/21087] intraday_20946.csv.gz  in=364,017,070 out=111,386,818 elapsed=161.9s

  [13042/21087] intraday_20947.csv.gz  in=364,032,522 out=111,402,270 elapsed=161.9s

  [13043/21087] intraday_20948.csv.gz  in=364,045,435 out=111,415,183 elapsed=161.9s

  [13044/21087] intraday_20950.csv.gz  in=364,054,744 out=111,424,492 elapsed=161.9s

  [13045/21087] intraday_2095.csv.gz  in=364,068,246 out=111,424,492 elapsed=161.9s

  [13046/21087] intraday_20949.csv.gz  in=364,080,186 out=111,436,432 elapsed=161.9s

  [13047/21087] intraday_20951.csv.gz  in=364,093,471 out=111,449,717 elapsed=161.9s

  [13048/21087] intraday_20952.csv.gz  in=364,106,741 out=111,462,987 elapsed=161.9s

  [13049/21087] intraday_20953.csv.gz  in=364,118,561 out=111,474,807 elapsed=161.9s

  [13050/21087] intraday_20954.csv.gz  in=364,130,459 out=111,486,705 elapsed=161.9s

  [13051/21087] intraday_20955.csv.gz  in=364,141,707 out=111,497,953 elapsed=161.9s

  [13052/21087] intraday_20956.csv.gz  in=364,152,590 out=111,508,836 elapsed=162.0s

  [13053/21087] intraday_20957.csv.gz  in=364,162,606 out=111,518,852 elapsed=162.0s

  [13054/21087] intraday_20958.csv.gz  in=364,174,302 out=111,530,548 elapsed=162.0s

  [13055/21087] intraday_2096.csv.gz  in=364,186,627 out=111,530,548 elapsed=162.0s

  [13056/21087] intraday_20959.csv.gz  in=364,199,870 out=111,543,791 elapsed=162.0s

  [13057/21087] intraday_20960.csv.gz  in=364,210,943 out=111,554,864 elapsed=162.0s

  [13058/21087] intraday_20961.csv.gz  in=364,220,884 out=111,564,805 elapsed=162.0s

  [13059/21087] intraday_20962.csv.gz  in=364,230,923 out=111,574,844 elapsed=162.0s

  [13060/21087] intraday_20964.csv.gz  in=364,242,285 out=111,586,206 elapsed=162.0s

  [13061/21087] intraday_20963.csv.gz  in=364,257,077 out=111,600,998 elapsed=162.0s

  [13062/21087] intraday_20965.csv.gz  in=364,277,011 out=111,620,932 elapsed=162.1s

  [13063/21087] intraday_20966.csv.gz  in=364,287,139 out=111,631,060 elapsed=162.1s

  [13064/21087] intraday_20968.csv.gz  in=364,298,296 out=111,642,217 elapsed=162.1s

  [13065/21087] intraday_20967.csv.gz  in=364,310,599 out=111,654,520 elapsed=162.1s

  [13066/21087] intraday_20969.csv.gz  in=364,322,227 out=111,666,148 elapsed=162.1s

  [13067/21087] intraday_2097.csv.gz  in=364,334,613 out=111,666,148 elapsed=162.1s

  [13068/21087] intraday_20970.csv.gz  in=364,345,852 out=111,677,387 elapsed=162.1s

  [13069/21087] intraday_20972.csv.gz  in=364,358,262 out=111,689,797 elapsed=162.1s

  [13070/21087] intraday_20971.csv.gz  in=364,370,217 out=111,701,752 elapsed=162.1s

  [13071/21087] intraday_20973.csv.gz  in=364,382,992 out=111,714,527 elapsed=162.1s

  [13072/21087] intraday_20974.csv.gz  in=364,392,961 out=111,724,496 elapsed=162.1s

  [13073/21087] intraday_20975.csv.gz  in=364,406,448 out=111,737,983 elapsed=162.2s

  [13074/21087] intraday_20976.csv.gz  in=364,419,562 out=111,751,097 elapsed=162.2s

  [13075/21087] intraday_20977.csv.gz  in=364,431,847 out=111,763,382 elapsed=162.2s

  [13076/21087] intraday_20978.csv.gz  in=364,442,612 out=111,774,147 elapsed=162.2s

  [13077/21087] intraday_20979.csv.gz  in=364,453,917 out=111,785,452 elapsed=162.2s

  [13078/21087] intraday_20980.csv.gz  in=364,465,494 out=111,797,029 elapsed=162.2s

  [13079/21087] intraday_2098.csv.gz  in=364,478,000 out=111,797,029 elapsed=162.2s

  [13080/21087] intraday_20981.csv.gz  in=364,489,617 out=111,808,646 elapsed=162.2s

  [13081/21087] intraday_20982.csv.gz  in=364,502,861 out=111,821,890 elapsed=162.2s

  [13082/21087] intraday_20983.csv.gz  in=364,512,695 out=111,831,724 elapsed=162.2s

  [13083/21087] intraday_20984.csv.gz  in=364,523,685 out=111,842,714 elapsed=162.3s

  [13084/21087] intraday_20986.csv.gz  in=364,533,913 out=111,852,942 elapsed=162.3s

  [13085/21087] intraday_20985.csv.gz  in=364,544,728 out=111,863,757 elapsed=162.3s

  [13086/21087] intraday_20987.csv.gz  in=364,557,014 out=111,876,043 elapsed=162.3s

  [13087/21087] intraday_20988.csv.gz  in=364,568,874 out=111,887,903 elapsed=162.3s

  [13088/21087] intraday_20989.csv.gz  in=364,581,413 out=111,900,442 elapsed=162.3s

  [13089/21087] intraday_2099.csv.gz  in=364,593,904 out=111,900,442 elapsed=162.3s

  [13090/21087] intraday_20990.csv.gz  in=364,607,399 out=111,913,937 elapsed=162.3s

  [13091/21087] intraday_20991.csv.gz  in=364,617,780 out=111,924,318 elapsed=162.3s

  [13092/21087] intraday_20993.csv.gz  in=364,630,416 out=111,936,954 elapsed=162.4s

  [13093/21087] intraday_20992.csv.gz  in=364,653,860 out=111,960,398 elapsed=162.4s

  [13094/21087] intraday_20994.csv.gz  in=364,665,715 out=111,972,253 elapsed=162.4s

  [13095/21087] intraday_20995.csv.gz  in=364,678,002 out=111,984,540 elapsed=162.4s

  [13096/21087] intraday_20996.csv.gz  in=364,688,982 out=111,995,520 elapsed=162.4s

  [13097/21087] intraday_20997.csv.gz  in=364,700,192 out=112,006,730 elapsed=162.4s

  [13098/21087] intraday_20998.csv.gz  in=364,712,673 out=112,019,211 elapsed=162.4s

  [13099/21087] intraday_2100.csv.gz  in=364,721,929 out=112,019,211 elapsed=162.4s

  [13100/21087] intraday_20999.csv.gz  in=364,733,726 out=112,031,008 elapsed=162.4s

  [13101/21087] intraday_21000.csv.gz  in=364,745,985 out=112,043,267 elapsed=162.4s

  [13102/21087] intraday_21001.csv.gz  in=364,758,099 out=112,055,381 elapsed=162.4s

  [13103/21087] intraday_21002.csv.gz  in=364,768,482 out=112,065,764 elapsed=162.5s

  [13104/21087] intraday_21003.csv.gz  in=364,778,966 out=112,076,248 elapsed=162.5s

  [13105/21087] intraday_21004.csv.gz  in=364,790,806 out=112,088,088 elapsed=162.5s

  [13106/21087] intraday_21005.csv.gz  in=364,804,555 out=112,101,837 elapsed=162.5s

  [13107/21087] intraday_21007.csv.gz  in=364,815,283 out=112,112,565 elapsed=162.5s

  [13108/21087] intraday_21006.csv.gz  in=364,827,265 out=112,124,547 elapsed=162.5s

  [13109/21087] intraday_21008.csv.gz  in=364,839,772 out=112,137,054 elapsed=162.5s

  [13110/21087] intraday_21009.csv.gz  in=364,849,072 out=112,146,354 elapsed=162.5s

  [13111/21087] intraday_2101.csv.gz  in=364,861,301 out=112,146,354 elapsed=162.5s

  [13112/21087] intraday_21010.csv.gz  in=364,875,192 out=112,160,245 elapsed=162.5s

  [13113/21087] intraday_21012.csv.gz  in=364,886,677 out=112,171,730 elapsed=162.5s

  [13114/21087] intraday_21011.csv.gz  in=364,899,397 out=112,184,450 elapsed=162.6s

  [13115/21087] intraday_21013.csv.gz  in=364,912,159 out=112,197,212 elapsed=162.6s

  [13116/21087] intraday_21014.csv.gz  in=364,924,626 out=112,209,679 elapsed=162.6s

  [13117/21087] intraday_21015.csv.gz  in=364,932,578 out=112,217,631 elapsed=162.6s

  [13118/21087] intraday_21016.csv.gz  in=364,944,336 out=112,229,389 elapsed=162.6s

  [13119/21087] intraday_21017.csv.gz  in=364,957,466 out=112,242,519 elapsed=162.6s

  [13120/21087] intraday_21018.csv.gz  in=364,968,993 out=112,254,046 elapsed=162.6s

  [13121/21087] intraday_2102.csv.gz  in=364,981,540 out=112,254,046 elapsed=162.6s

  [13122/21087] intraday_21019.csv.gz  in=364,991,276 out=112,263,782 elapsed=162.6s

  [13123/21087] intraday_21020.csv.gz  in=365,003,201 out=112,275,707 elapsed=163.0s

  [13124/21087] intraday_21021.csv.gz  in=365,012,670 out=112,285,176 elapsed=163.0s

  [13125/21087] intraday_21023.csv.gz  in=365,025,308 out=112,297,814 elapsed=163.0s

  [13126/21087] intraday_21022.csv.gz  in=365,037,668 out=112,310,174 elapsed=163.0s

  [13127/21087] intraday_21024.csv.gz  in=365,048,816 out=112,321,322 elapsed=163.0s

  [13128/21087] intraday_21025.csv.gz  in=365,062,273 out=112,334,779 elapsed=163.0s

  [13129/21087] intraday_21026.csv.gz  in=365,072,015 out=112,344,521 elapsed=163.1s

  [13130/21087] intraday_21027.csv.gz  in=365,082,170 out=112,354,676 elapsed=163.1s

  [13131/21087] intraday_21028.csv.gz  in=365,097,014 out=112,369,520 elapsed=163.1s

  [13132/21087] intraday_21029.csv.gz  in=365,111,586 out=112,384,092 elapsed=163.1s

  [13133/21087] intraday_2103.csv.gz  in=365,125,107 out=112,384,092 elapsed=163.1s

  [13134/21087] intraday_21030.csv.gz  in=365,138,733 out=112,397,718 elapsed=163.1s

  [13135/21087] intraday_21031.csv.gz  in=365,149,817 out=112,408,802 elapsed=163.1s

  [13136/21087] intraday_21033.csv.gz  in=365,161,925 out=112,420,910 elapsed=163.1s

  [13137/21087] intraday_21034.csv.gz  in=365,175,074 out=112,434,059 elapsed=163.1s

  [13138/21087] intraday_21032.csv.gz  in=365,186,864 out=112,445,849 elapsed=163.1s

  [13139/21087] intraday_21035.csv.gz  in=365,198,694 out=112,457,679 elapsed=163.1s

  [13140/21087] intraday_21036.csv.gz  in=365,210,010 out=112,468,995 elapsed=163.2s

  [13141/21087] intraday_21037.csv.gz  in=365,221,245 out=112,480,230 elapsed=163.2s

  [13142/21087] intraday_21038.csv.gz  in=365,231,816 out=112,490,801 elapsed=163.2s

  [13143/21087] intraday_21039.csv.gz  in=365,244,267 out=112,503,252 elapsed=163.2s

  [13144/21087] intraday_2104.csv.gz  in=365,259,239 out=112,503,252 elapsed=163.2s

  [13145/21087] intraday_21040.csv.gz  in=365,271,287 out=112,515,300 elapsed=163.2s

  [13146/21087] intraday_21041.csv.gz  in=365,283,383 out=112,527,396 elapsed=163.2s

  [13147/21087] intraday_21043.csv.gz  in=365,292,359 out=112,536,372 elapsed=163.2s

  [13148/21087] intraday_21042.csv.gz  in=365,304,106 out=112,548,119 elapsed=163.2s

  [13149/21087] intraday_21044.csv.gz  in=365,316,507 out=112,560,520 elapsed=163.2s

  [13150/21087] intraday_21047.csv.gz  in=365,328,243 out=112,572,256 elapsed=163.3s

  [13151/21087] intraday_21045.csv.gz  in=365,338,908 out=112,582,921 elapsed=163.3s

  [13152/21087] intraday_21046.csv.gz  in=365,349,785 out=112,593,798 elapsed=163.3s

  [13153/21087] intraday_21048.csv.gz  in=365,362,237 out=112,606,250 elapsed=163.3s

  [13154/21087] intraday_2105.csv.gz  in=365,374,574 out=112,606,250 elapsed=163.3s

  [13155/21087] intraday_21049.csv.gz  in=365,385,372 out=112,617,048 elapsed=163.3s

  [13156/21087] intraday_21050.csv.gz  in=365,397,477 out=112,629,153 elapsed=163.3s

  [13157/21087] intraday_21051.csv.gz  in=365,409,493 out=112,641,169 elapsed=163.3s

  [13158/21087] intraday_21052.csv.gz  in=365,421,051 out=112,652,727 elapsed=163.3s

  [13159/21087] intraday_21054.csv.gz  in=365,435,639 out=112,667,315 elapsed=163.3s

  [13160/21087] intraday_21053.csv.gz  in=365,448,214 out=112,679,890 elapsed=163.3s

  [13161/21087] intraday_21055.csv.gz  in=365,461,287 out=112,692,963 elapsed=163.3s

  [13162/21087] intraday_21056.csv.gz  in=365,473,587 out=112,705,263 elapsed=163.4s

  [13163/21087] intraday_21057.csv.gz  in=365,487,899 out=112,719,575 elapsed=163.4s

  [13164/21087] intraday_21058.csv.gz  in=365,501,135 out=112,732,811 elapsed=163.4s

  [13165/21087] intraday_21059.csv.gz  in=365,514,481 out=112,746,157 elapsed=163.4s

  [13166/21087] intraday_2106.csv.gz  in=365,526,155 out=112,746,157 elapsed=163.4s

  [13167/21087] intraday_21060.csv.gz  in=365,540,719 out=112,760,721 elapsed=163.4s

  [13168/21087] intraday_21061.csv.gz  in=365,556,955 out=112,776,957 elapsed=163.5s

  [13169/21087] intraday_21062.csv.gz  in=365,570,664 out=112,790,666 elapsed=163.5s

  [13170/21087] intraday_21063.csv.gz  in=365,585,567 out=112,805,569 elapsed=163.5s

  [13171/21087] intraday_21064.csv.gz  in=365,596,841 out=112,816,843 elapsed=163.5s

  [13172/21087] intraday_21066.csv.gz  in=365,606,856 out=112,826,858 elapsed=163.5s

  [13173/21087] intraday_21065.csv.gz  in=365,620,079 out=112,840,081 elapsed=163.5s

  [13174/21087] intraday_21067.csv.gz  in=365,632,102 out=112,852,104 elapsed=163.5s

  [13175/21087] intraday_21068.csv.gz  in=365,642,786 out=112,862,788 elapsed=163.5s

  [13176/21087] intraday_2107.csv.gz  in=365,655,082 out=112,862,788 elapsed=163.5s

  [13177/21087] intraday_21070.csv.gz  in=365,667,557 out=112,875,263 elapsed=163.6s

  [13178/21087] intraday_21071.csv.gz  in=365,680,179 out=112,887,885 elapsed=163.6s

  [13179/21087] intraday_21069.csv.gz  in=365,692,178 out=112,899,884 elapsed=163.6s

  [13180/21087] intraday_21072.csv.gz  in=365,703,446 out=112,911,152 elapsed=163.6s

  [13181/21087] intraday_21073.csv.gz  in=365,714,656 out=112,922,362 elapsed=163.6s

  [13182/21087] intraday_21075.csv.gz  in=365,726,132 out=112,933,838 elapsed=163.6s

  [13183/21087] intraday_21074.csv.gz  in=365,739,193 out=112,946,899 elapsed=163.6s

  [13184/21087] intraday_21076.csv.gz  in=365,751,168 out=112,958,874 elapsed=163.6s

  [13185/21087] intraday_21077.csv.gz  in=365,764,168 out=112,971,874 elapsed=163.6s

  [13186/21087] intraday_2108.csv.gz  in=365,777,035 out=112,971,874 elapsed=163.6s

  [13187/21087] intraday_21079.csv.gz  in=365,789,374 out=112,984,213 elapsed=163.7s

  [13188/21087] intraday_21078.csv.gz  in=365,802,872 out=112,997,711 elapsed=163.7s

  [13189/21087] intraday_21080.csv.gz  in=365,815,009 out=113,009,848 elapsed=163.7s

  [13190/21087] intraday_21082.csv.gz  in=365,827,768 out=113,022,607 elapsed=163.7s

  [13191/21087] intraday_21084.csv.gz  in=365,842,587 out=113,037,426 elapsed=163.7s

  [13192/21087] intraday_21081.csv.gz  in=365,855,925 out=113,050,764 elapsed=163.7s

  [13193/21087] intraday_21083.csv.gz  in=365,865,155 out=113,059,994 elapsed=163.7s

  [13194/21087] intraday_21085.csv.gz  in=365,873,046 out=113,067,885 elapsed=163.7s

  [13195/21087] intraday_21086.csv.gz  in=365,883,396 out=113,078,235 elapsed=163.7s

  [13196/21087] intraday_2109.csv.gz  in=365,894,513 out=113,078,235 elapsed=163.7s

  [13197/21087] intraday_2110.csv.gz  in=365,907,531 out=113,078,235 elapsed=163.7s

  [13198/21087] intraday_21087.csv.gz  in=365,918,691 out=113,089,395 elapsed=163.7s

  [13199/21087] intraday_2112.csv.gz  in=365,929,878 out=113,089,395 elapsed=163.8s

  [13200/21087] intraday_2111.csv.gz  in=365,941,243 out=113,089,395 elapsed=163.8s

  [13201/21087] intraday_2113.csv.gz  in=365,954,016 out=113,089,395 elapsed=163.8s

  [13202/21087] intraday_2114.csv.gz  in=365,965,965 out=113,089,395 elapsed=163.8s

  [13203/21087] intraday_2116.csv.gz  in=365,978,036 out=113,089,395 elapsed=163.8s

  [13204/21087] intraday_2118.csv.gz  in=365,990,812 out=113,089,395 elapsed=163.8s

  [13205/21087] intraday_2115.csv.gz  in=366,005,553 out=113,089,395 elapsed=163.8s

  [13206/21087] intraday_2117.csv.gz  in=366,019,729 out=113,089,395 elapsed=163.8s

  [13207/21087] intraday_2119.csv.gz  in=366,032,502 out=113,089,395 elapsed=163.8s

  [13208/21087] intraday_2120.csv.gz  in=366,045,530 out=113,089,395 elapsed=163.8s

  [13209/21087] intraday_2121.csv.gz  in=366,056,633 out=113,089,395 elapsed=163.8s

  [13210/21087] intraday_2122.csv.gz  in=366,069,033 out=113,089,395 elapsed=163.8s

  [13211/21087] intraday_2123.csv.gz  in=366,081,375 out=113,089,395 elapsed=163.8s

  [13212/21087] intraday_2124.csv.gz  in=366,091,934 out=113,089,395 elapsed=163.9s

  [13213/21087] intraday_2126.csv.gz  in=366,104,037 out=113,089,395 elapsed=163.9s

  [13214/21087] intraday_2125.csv.gz  in=366,117,547 out=113,089,395 elapsed=163.9s

  [13215/21087] intraday_2127.csv.gz  in=366,128,581 out=113,089,395 elapsed=163.9s

  [13216/21087] intraday_2128.csv.gz  in=366,141,031 out=113,089,395 elapsed=163.9s

  [13217/21087] intraday_2129.csv.gz  in=366,154,991 out=113,089,395 elapsed=163.9s

  [13218/21087] intraday_2130.csv.gz  in=366,166,800 out=113,089,395 elapsed=163.9s

  [13219/21087] intraday_2131.csv.gz  in=366,178,482 out=113,089,395 elapsed=163.9s

  [13220/21087] intraday_2132.csv.gz  in=366,192,512 out=113,089,395 elapsed=163.9s

  [13221/21087] intraday_2133.csv.gz  in=366,204,292 out=113,089,395 elapsed=164.0s

  [13222/21087] intraday_2136.csv.gz  in=366,215,155 out=113,089,395 elapsed=164.0s

  [13223/21087] intraday_2135.csv.gz  in=366,227,706 out=113,089,395 elapsed=164.0s

  [13224/21087] intraday_2134.csv.gz  in=366,240,563 out=113,089,395 elapsed=164.0s

  [13225/21087] intraday_2137.csv.gz  in=366,251,178 out=113,089,395 elapsed=164.0s

  [13226/21087] intraday_2138.csv.gz  in=366,264,543 out=113,089,395 elapsed=164.0s

  [13227/21087] intraday_2140.csv.gz  in=366,279,315 out=113,089,395 elapsed=164.0s

  [13228/21087] intraday_2139.csv.gz  in=366,293,128 out=113,089,395 elapsed=164.0s

  [13229/21087] intraday_2141.csv.gz  in=366,307,527 out=113,089,395 elapsed=164.0s

  [13230/21087] intraday_2142.csv.gz  in=366,318,135 out=113,089,395 elapsed=164.0s

  [13231/21087] intraday_2144.csv.gz  in=366,329,624 out=113,089,395 elapsed=164.1s

  [13232/21087] intraday_2143.csv.gz  in=366,341,515 out=113,089,395 elapsed=164.1s

  [13233/21087] intraday_2145.csv.gz  in=366,353,944 out=113,089,395 elapsed=164.1s

  [13234/21087] intraday_2146.csv.gz  in=366,367,937 out=113,089,395 elapsed=164.1s

  [13235/21087] intraday_2147.csv.gz  in=366,379,361 out=113,089,395 elapsed=164.1s

  [13236/21087] intraday_2148.csv.gz  in=366,390,769 out=113,089,395 elapsed=164.1s

  [13237/21087] intraday_2149.csv.gz  in=366,402,616 out=113,089,395 elapsed=164.1s

  [13238/21087] intraday_2150.csv.gz  in=366,415,508 out=113,089,395 elapsed=164.1s

  [13239/21087] intraday_2152.csv.gz  in=366,428,516 out=113,089,395 elapsed=164.1s

  [13240/21087] intraday_2151.csv.gz  in=366,439,909 out=113,089,395 elapsed=164.1s

  [13241/21087] intraday_2153.csv.gz  in=366,450,814 out=113,089,395 elapsed=164.1s

  [13242/21087] intraday_2154.csv.gz  in=366,462,516 out=113,089,395 elapsed=164.1s

  [13243/21087] intraday_2155.csv.gz  in=366,474,676 out=113,089,395 elapsed=164.1s

  [13244/21087] intraday_2156.csv.gz  in=366,490,466 out=113,089,395 elapsed=164.1s

  [13245/21087] intraday_2157.csv.gz  in=366,501,073 out=113,089,395 elapsed=164.2s

  [13246/21087] intraday_2158.csv.gz  in=366,513,172 out=113,089,395 elapsed=164.2s

  [13247/21087] intraday_2159.csv.gz  in=366,522,963 out=113,089,395 elapsed=164.2s

  [13248/21087] intraday_2160.csv.gz  in=366,537,349 out=113,089,395 elapsed=164.2s

  [13249/21087] intraday_2161.csv.gz  in=366,549,026 out=113,089,395 elapsed=164.2s

  [13250/21087] intraday_2162.csv.gz  in=366,565,078 out=113,089,395 elapsed=164.2s

  [13251/21087] intraday_2163.csv.gz  in=366,577,372 out=113,089,395 elapsed=164.2s

  [13252/21087] intraday_2164.csv.gz  in=366,592,122 out=113,089,395 elapsed=164.2s

  [13253/21087] intraday_2165.csv.gz  in=366,605,551 out=113,089,395 elapsed=164.2s

  [13254/21087] intraday_2166.csv.gz  in=366,620,161 out=113,089,395 elapsed=164.2s

  [13255/21087] intraday_2167.csv.gz  in=366,633,800 out=113,089,395 elapsed=164.2s

  [13256/21087] intraday_2169.csv.gz  in=366,646,150 out=113,089,395 elapsed=164.2s

  [13257/21087] intraday_2168.csv.gz  in=366,658,581 out=113,089,395 elapsed=164.2s

  [13258/21087] intraday_2170.csv.gz  in=366,670,631 out=113,089,395 elapsed=164.3s

  [13259/21087] intraday_2171.csv.gz  in=366,683,531 out=113,089,395 elapsed=164.3s

  [13260/21087] intraday_2172.csv.gz  in=366,696,155 out=113,089,395 elapsed=164.3s

  [13261/21087] intraday_2173.csv.gz  in=366,707,585 out=113,089,395 elapsed=164.3s

  [13262/21087] intraday_2174.csv.gz  in=366,722,443 out=113,089,395 elapsed=164.3s

  [13263/21087] intraday_2175.csv.gz  in=366,734,723 out=113,089,395 elapsed=164.3s

  [13264/21087] intraday_2176.csv.gz  in=366,746,311 out=113,089,395 elapsed=164.3s

  [13265/21087] intraday_2177.csv.gz  in=366,761,732 out=113,089,395 elapsed=164.3s

  [13266/21087] intraday_2178.csv.gz  in=366,772,057 out=113,089,395 elapsed=164.3s

  [13267/21087] intraday_2179.csv.gz  in=366,785,063 out=113,089,395 elapsed=164.3s

  [13268/21087] intraday_2180.csv.gz  in=366,799,459 out=113,089,395 elapsed=164.3s

  [13269/21087] intraday_2181.csv.gz  in=366,814,437 out=113,089,395 elapsed=164.3s

  [13270/21087] intraday_2182.csv.gz  in=366,827,335 out=113,089,395 elapsed=164.3s

  [13271/21087] intraday_2183.csv.gz  in=366,840,856 out=113,089,395 elapsed=164.4s

  [13272/21087] intraday_2184.csv.gz  in=366,852,849 out=113,089,395 elapsed=164.4s

  [13273/21087] intraday_2185.csv.gz  in=366,865,923 out=113,089,395 elapsed=164.4s

  [13274/21087] intraday_2186.csv.gz  in=366,878,068 out=113,089,395 elapsed=164.4s

  [13275/21087] intraday_2187.csv.gz  in=366,892,285 out=113,089,395 elapsed=164.4s

  [13276/21087] intraday_2188.csv.gz  in=366,904,119 out=113,089,395 elapsed=164.4s

  [13277/21087] intraday_2189.csv.gz  in=366,920,761 out=113,089,395 elapsed=164.4s

  [13278/21087] intraday_2190.csv.gz  in=366,933,183 out=113,089,395 elapsed=164.4s

  [13279/21087] intraday_2191.csv.gz  in=366,947,659 out=113,089,395 elapsed=164.4s

  [13280/21087] intraday_2192.csv.gz  in=366,959,783 out=113,089,395 elapsed=164.4s

  [13281/21087] intraday_2194.csv.gz  in=366,970,679 out=113,089,395 elapsed=164.4s

  [13282/21087] intraday_2193.csv.gz  in=366,983,357 out=113,089,395 elapsed=164.5s

  [13283/21087] intraday_2196.csv.gz  in=366,996,630 out=113,089,395 elapsed=164.5s

  [13284/21087] intraday_2195.csv.gz  in=367,011,319 out=113,089,395 elapsed=164.5s

  [13285/21087] intraday_2197.csv.gz  in=367,026,891 out=113,089,395 elapsed=164.5s

  [13286/21087] intraday_2198.csv.gz  in=367,039,151 out=113,089,395 elapsed=164.5s

  [13287/21087] intraday_2200.csv.gz  in=367,052,401 out=113,089,395 elapsed=164.5s

  [13288/21087] intraday_2199.csv.gz  in=367,067,237 out=113,089,395 elapsed=164.5s

  [13289/21087] intraday_2201.csv.gz  in=367,080,646 out=113,089,395 elapsed=164.5s

  [13290/21087] intraday_2202.csv.gz  in=367,095,012 out=113,089,395 elapsed=164.5s

  [13291/21087] intraday_2203.csv.gz  in=367,110,551 out=113,089,395 elapsed=164.5s

  [13292/21087] intraday_2204.csv.gz  in=367,124,814 out=113,089,395 elapsed=164.5s

  [13293/21087] intraday_2205.csv.gz  in=367,138,953 out=113,089,395 elapsed=164.5s

  [13294/21087] intraday_2206.csv.gz  in=367,152,886 out=113,089,395 elapsed=164.5s

  [13295/21087] intraday_2207.csv.gz  in=367,164,557 out=113,089,395 elapsed=164.5s

  [13296/21087] intraday_2208.csv.gz  in=367,177,255 out=113,089,395 elapsed=164.6s

  [13297/21087] intraday_2209.csv.gz  in=367,187,842 out=113,089,395 elapsed=164.6s

  [13298/21087] intraday_2211.csv.gz  in=367,195,975 out=113,089,395 elapsed=164.6s

  [13299/21087] intraday_2210.csv.gz  in=367,210,670 out=113,089,395 elapsed=164.6s

  [13300/21087] intraday_2212.csv.gz  in=367,220,255 out=113,089,395 elapsed=164.6s

  [13301/21087] intraday_2213.csv.gz  in=367,230,223 out=113,089,395 elapsed=164.6s

  [13302/21087] intraday_2214.csv.gz  in=367,245,500 out=113,089,395 elapsed=164.6s

  [13303/21087] intraday_2215.csv.gz  in=367,259,346 out=113,089,395 elapsed=164.6s

  [13304/21087] intraday_2217.csv.gz  in=367,270,484 out=113,089,395 elapsed=164.6s

  [13305/21087] intraday_2216.csv.gz  in=367,282,757 out=113,089,395 elapsed=164.6s

  [13306/21087] intraday_2218.csv.gz  in=367,296,563 out=113,089,395 elapsed=164.6s

  [13307/21087] intraday_2220.csv.gz  in=367,309,295 out=113,089,395 elapsed=164.6s

  [13308/21087] intraday_2219.csv.gz  in=367,323,606 out=113,089,395 elapsed=164.7s

  [13309/21087] intraday_2221.csv.gz  in=367,336,387 out=113,089,395 elapsed=164.7s

  [13310/21087] intraday_2222.csv.gz  in=367,350,700 out=113,089,395 elapsed=164.7s

  [13311/21087] intraday_2224.csv.gz  in=367,360,247 out=113,089,395 elapsed=164.7s

  [13312/21087] intraday_2223.csv.gz  in=367,375,247 out=113,089,395 elapsed=164.7s

  [13313/21087] intraday_2225.csv.gz  in=367,387,001 out=113,089,395 elapsed=164.7s

  [13314/21087] intraday_2226.csv.gz  in=367,401,252 out=113,089,395 elapsed=164.7s

  [13315/21087] intraday_2228.csv.gz  in=367,413,127 out=113,089,395 elapsed=164.7s

  [13316/21087] intraday_2229.csv.gz  in=367,425,749 out=113,089,395 elapsed=164.7s

  [13317/21087] intraday_2227.csv.gz  in=367,443,386 out=113,089,395 elapsed=164.7s

  [13318/21087] intraday_2230.csv.gz  in=367,456,734 out=113,089,395 elapsed=164.7s

  [13319/21087] intraday_2231.csv.gz  in=367,469,318 out=113,089,395 elapsed=164.7s

  [13320/21087] intraday_2233.csv.gz  in=367,481,792 out=113,089,395 elapsed=164.8s

  [13321/21087] intraday_2234.csv.gz  in=367,495,079 out=113,089,395 elapsed=164.8s

  [13322/21087] intraday_2232.csv.gz  in=367,515,056 out=113,089,395 elapsed=164.8s

  [13323/21087] intraday_2235.csv.gz  in=367,527,653 out=113,089,395 elapsed=164.8s

  [13324/21087] intraday_2236.csv.gz  in=367,540,334 out=113,089,395 elapsed=164.8s

  [13325/21087] intraday_2237.csv.gz  in=367,553,680 out=113,089,395 elapsed=164.8s

  [13326/21087] intraday_2239.csv.gz  in=367,562,768 out=113,089,395 elapsed=164.8s

  [13327/21087] intraday_2238.csv.gz  in=367,575,427 out=113,089,395 elapsed=164.8s

  [13328/21087] intraday_2240.csv.gz  in=367,588,437 out=113,089,395 elapsed=164.8s

  [13329/21087] intraday_2242.csv.gz  in=367,600,402 out=113,089,395 elapsed=164.8s

  [13330/21087] intraday_2241.csv.gz  in=367,617,506 out=113,089,395 elapsed=164.8s

  [13331/21087] intraday_2243.csv.gz  in=367,632,053 out=113,089,395 elapsed=164.8s

  [13332/21087] intraday_2244.csv.gz  in=367,646,638 out=113,089,395 elapsed=164.8s

  [13333/21087] intraday_2245.csv.gz  in=367,658,972 out=113,089,395 elapsed=164.8s

  [13334/21087] intraday_2246.csv.gz  in=367,671,979 out=113,089,395 elapsed=164.9s

  [13335/21087] intraday_2248.csv.gz  in=367,683,150 out=113,089,395 elapsed=164.9s

  [13336/21087] intraday_2247.csv.gz  in=367,696,383 out=113,089,395 elapsed=164.9s

  [13337/21087] intraday_2249.csv.gz  in=367,709,543 out=113,089,395 elapsed=164.9s

  [13338/21087] intraday_2250.csv.gz  in=367,721,123 out=113,089,395 elapsed=164.9s

  [13339/21087] intraday_2251.csv.gz  in=367,732,223 out=113,089,395 elapsed=164.9s

  [13340/21087] intraday_2253.csv.gz  in=367,742,895 out=113,089,395 elapsed=164.9s

  [13341/21087] intraday_2252.csv.gz  in=367,758,023 out=113,089,395 elapsed=164.9s

  [13342/21087] intraday_2254.csv.gz  in=367,772,630 out=113,089,395 elapsed=164.9s

  [13343/21087] intraday_2255.csv.gz  in=367,785,431 out=113,089,395 elapsed=164.9s

  [13344/21087] intraday_2256.csv.gz  in=367,799,476 out=113,089,395 elapsed=164.9s

  [13345/21087] intraday_2257.csv.gz  in=367,812,092 out=113,089,395 elapsed=164.9s

  [13346/21087] intraday_2258.csv.gz  in=367,824,549 out=113,089,395 elapsed=165.0s

  [13347/21087] intraday_2259.csv.gz  in=367,837,941 out=113,089,395 elapsed=165.0s

  [13348/21087] intraday_2260.csv.gz  in=367,849,048 out=113,089,395 elapsed=165.0s

  [13349/21087] intraday_2261.csv.gz  in=367,861,713 out=113,089,395 elapsed=165.0s

  [13350/21087] intraday_2262.csv.gz  in=367,878,257 out=113,089,395 elapsed=165.0s

  [13351/21087] intraday_2263.csv.gz  in=367,889,059 out=113,089,395 elapsed=165.0s

  [13352/21087] intraday_2264.csv.gz  in=367,901,662 out=113,089,395 elapsed=165.0s

  [13353/21087] intraday_2265.csv.gz  in=367,913,540 out=113,089,395 elapsed=165.0s

  [13354/21087] intraday_2266.csv.gz  in=367,924,643 out=113,089,395 elapsed=165.0s

  [13355/21087] intraday_2267.csv.gz  in=367,937,958 out=113,089,395 elapsed=165.0s

  [13356/21087] intraday_2268.csv.gz  in=367,952,033 out=113,089,395 elapsed=165.0s

  [13357/21087] intraday_2269.csv.gz  in=367,963,297 out=113,089,395 elapsed=165.0s

  [13358/21087] intraday_2270.csv.gz  in=367,974,497 out=113,089,395 elapsed=165.0s

  [13359/21087] intraday_2271.csv.gz  in=367,987,678 out=113,089,395 elapsed=165.1s

  [13360/21087] intraday_2272.csv.gz  in=368,000,723 out=113,089,395 elapsed=165.1s

  [13361/21087] intraday_2273.csv.gz  in=368,013,846 out=113,089,395 elapsed=165.1s

  [13362/21087] intraday_2274.csv.gz  in=368,025,968 out=113,089,395 elapsed=165.1s

  [13363/21087] intraday_2275.csv.gz  in=368,037,759 out=113,089,395 elapsed=165.1s

  [13364/21087] intraday_2276.csv.gz  in=368,047,995 out=113,089,395 elapsed=165.1s

  [13365/21087] intraday_2277.csv.gz  in=368,062,218 out=113,089,395 elapsed=165.1s

  [13366/21087] intraday_2278.csv.gz  in=368,074,821 out=113,089,395 elapsed=165.1s

  [13367/21087] intraday_2279.csv.gz  in=368,090,827 out=113,089,395 elapsed=165.1s

  [13368/21087] intraday_2280.csv.gz  in=368,105,674 out=113,089,395 elapsed=165.1s

  [13369/21087] intraday_2281.csv.gz  in=368,116,821 out=113,089,395 elapsed=165.1s

  [13370/21087] intraday_2282.csv.gz  in=368,128,755 out=113,089,395 elapsed=165.1s

  [13371/21087] intraday_2283.csv.gz  in=368,140,791 out=113,089,395 elapsed=165.2s

  [13372/21087] intraday_2284.csv.gz  in=368,153,540 out=113,089,395 elapsed=165.2s

  [13373/21087] intraday_2286.csv.gz  in=368,164,345 out=113,089,395 elapsed=165.2s

  [13374/21087] intraday_2285.csv.gz  in=368,179,385 out=113,089,395 elapsed=165.2s

  [13375/21087] intraday_2287.csv.gz  in=368,194,989 out=113,089,395 elapsed=165.2s

  [13376/21087] intraday_2288.csv.gz  in=368,206,691 out=113,089,395 elapsed=165.2s

  [13377/21087] intraday_2289.csv.gz  in=368,220,903 out=113,089,395 elapsed=165.2s

  [13378/21087] intraday_2290.csv.gz  in=368,232,311 out=113,089,395 elapsed=165.2s

  [13379/21087] intraday_2291.csv.gz  in=368,245,674 out=113,089,395 elapsed=165.2s

  [13380/21087] intraday_2292.csv.gz  in=368,256,087 out=113,089,395 elapsed=165.2s

  [13381/21087] intraday_2293.csv.gz  in=368,267,854 out=113,089,395 elapsed=165.2s

  [13382/21087] intraday_2294.csv.gz  in=368,280,239 out=113,089,395 elapsed=165.2s

  [13383/21087] intraday_2295.csv.gz  in=368,293,881 out=113,089,395 elapsed=165.3s

  [13384/21087] intraday_2296.csv.gz  in=368,307,043 out=113,089,395 elapsed=165.3s

  [13385/21087] intraday_2297.csv.gz  in=368,320,292 out=113,089,395 elapsed=165.3s

  [13386/21087] intraday_2298.csv.gz  in=368,330,280 out=113,089,395 elapsed=165.3s

  [13387/21087] intraday_2299.csv.gz  in=368,352,207 out=113,089,395 elapsed=165.3s

  [13388/21087] intraday_2300.csv.gz  in=368,364,092 out=113,089,395 elapsed=165.3s

  [13389/21087] intraday_2301.csv.gz  in=368,379,970 out=113,089,395 elapsed=165.3s

  [13390/21087] intraday_2302.csv.gz  in=368,400,853 out=113,089,395 elapsed=165.3s

  [13391/21087] intraday_2304.csv.gz  in=368,413,332 out=113,089,395 elapsed=165.3s

  [13392/21087] intraday_2306.csv.gz  in=368,426,691 out=113,089,395 elapsed=165.3s

  [13393/21087] intraday_2303.csv.gz  in=368,442,290 out=113,089,395 elapsed=165.3s

  [13394/21087] intraday_2305.csv.gz  in=368,456,451 out=113,089,395 elapsed=165.3s

  [13395/21087] intraday_2308.csv.gz  in=368,468,573 out=113,089,395 elapsed=165.4s

  [13396/21087] intraday_2307.csv.gz  in=368,483,363 out=113,089,395 elapsed=165.4s

  [13397/21087] intraday_2309.csv.gz  in=368,496,043 out=113,089,395 elapsed=165.4s

  [13398/21087] intraday_2310.csv.gz  in=368,509,475 out=113,089,395 elapsed=165.4s

  [13399/21087] intraday_2311.csv.gz  in=368,522,895 out=113,089,395 elapsed=165.4s

  [13400/21087] intraday_2312.csv.gz  in=368,534,650 out=113,089,395 elapsed=165.4s

  [13401/21087] intraday_2313.csv.gz  in=368,547,899 out=113,089,395 elapsed=165.4s

  [13402/21087] intraday_2314.csv.gz  in=368,563,288 out=113,089,395 elapsed=165.4s

  [13403/21087] intraday_2315.csv.gz  in=368,575,194 out=113,089,395 elapsed=165.4s

  [13404/21087] intraday_2316.csv.gz  in=368,588,285 out=113,089,395 elapsed=165.4s

  [13405/21087] intraday_2317.csv.gz  in=368,600,747 out=113,089,395 elapsed=165.4s

  [13406/21087] intraday_2318.csv.gz  in=368,612,908 out=113,089,395 elapsed=165.4s

  [13407/21087] intraday_2319.csv.gz  in=368,627,536 out=113,089,395 elapsed=165.5s

  [13408/21087] intraday_2321.csv.gz  in=368,640,561 out=113,089,395 elapsed=165.5s

  [13409/21087] intraday_2320.csv.gz  in=368,656,128 out=113,089,395 elapsed=165.5s

  [13410/21087] intraday_2322.csv.gz  in=368,669,365 out=113,089,395 elapsed=165.5s

  [13411/21087] intraday_2323.csv.gz  in=368,682,737 out=113,089,395 elapsed=165.5s

  [13412/21087] intraday_2324.csv.gz  in=368,695,035 out=113,089,395 elapsed=165.5s

  [13413/21087] intraday_2325.csv.gz  in=368,707,557 out=113,089,395 elapsed=165.5s

  [13414/21087] intraday_2326.csv.gz  in=368,720,898 out=113,089,395 elapsed=165.5s

  [13415/21087] intraday_2327.csv.gz  in=368,735,976 out=113,089,395 elapsed=165.5s

  [13416/21087] intraday_2328.csv.gz  in=368,752,464 out=113,089,395 elapsed=165.5s

  [13417/21087] intraday_2329.csv.gz  in=368,765,150 out=113,089,395 elapsed=165.5s

  [13418/21087] intraday_2330.csv.gz  in=368,778,956 out=113,089,395 elapsed=165.5s

  [13419/21087] intraday_2331.csv.gz  in=368,791,945 out=113,089,395 elapsed=165.5s

  [13420/21087] intraday_2332.csv.gz  in=368,803,988 out=113,089,395 elapsed=165.6s

  [13421/21087] intraday_2333.csv.gz  in=368,815,803 out=113,089,395 elapsed=165.6s

  [13422/21087] intraday_2335.csv.gz  in=368,828,427 out=113,089,395 elapsed=165.6s

  [13423/21087] intraday_2334.csv.gz  in=368,846,442 out=113,089,395 elapsed=165.6s

  [13424/21087] intraday_2337.csv.gz  in=368,857,549 out=113,089,395 elapsed=165.6s

  [13425/21087] intraday_2336.csv.gz  in=368,874,216 out=113,089,395 elapsed=165.6s

  [13426/21087] intraday_2338.csv.gz  in=368,889,508 out=113,089,395 elapsed=165.6s

  [13427/21087] intraday_2339.csv.gz  in=368,901,908 out=113,089,395 elapsed=165.6s

  [13428/21087] intraday_2340.csv.gz  in=368,916,291 out=113,089,395 elapsed=165.6s

  [13429/21087] intraday_2341.csv.gz  in=368,929,630 out=113,089,395 elapsed=165.6s

  [13430/21087] intraday_2342.csv.gz  in=368,950,847 out=113,089,395 elapsed=165.6s

  [13431/21087] intraday_2343.csv.gz  in=368,965,364 out=113,089,395 elapsed=165.6s

  [13432/21087] intraday_2344.csv.gz  in=368,979,327 out=113,089,395 elapsed=165.7s

  [13433/21087] intraday_2345.csv.gz  in=368,994,270 out=113,089,395 elapsed=165.7s

  [13434/21087] intraday_2346.csv.gz  in=369,005,868 out=113,089,395 elapsed=165.7s

  [13435/21087] intraday_2347.csv.gz  in=369,017,493 out=113,089,395 elapsed=165.7s

  [13436/21087] intraday_2348.csv.gz  in=369,031,059 out=113,089,395 elapsed=165.7s

  [13437/21087] intraday_2349.csv.gz  in=369,044,905 out=113,089,395 elapsed=165.7s

  [13438/21087] intraday_2350.csv.gz  in=369,053,971 out=113,089,395 elapsed=165.7s

  [13439/21087] intraday_2351.csv.gz  in=369,062,918 out=113,089,395 elapsed=165.7s

  [13440/21087] intraday_2353.csv.gz  in=369,064,327 out=113,089,395 elapsed=165.7s

  [13441/21087] intraday_2352.csv.gz  in=369,076,190 out=113,089,395 elapsed=165.7s

  [13442/21087] intraday_2354.csv.gz  in=369,092,557 out=113,089,395 elapsed=165.7s

  [13443/21087] intraday_2355.csv.gz  in=369,106,651 out=113,089,395 elapsed=165.7s

  [13444/21087] intraday_2356.csv.gz  in=369,119,213 out=113,089,395 elapsed=165.7s

  [13445/21087] intraday_2357.csv.gz  in=369,130,464 out=113,089,395 elapsed=165.7s

  [13446/21087] intraday_2358.csv.gz  in=369,145,513 out=113,089,395 elapsed=165.8s

  [13447/21087] intraday_2360.csv.gz  in=369,158,481 out=113,089,395 elapsed=165.8s

  [13448/21087] intraday_2359.csv.gz  in=369,180,284 out=113,089,395 elapsed=165.8s

  [13449/21087] intraday_2361.csv.gz  in=369,192,974 out=113,089,395 elapsed=165.8s

  [13450/21087] intraday_2362.csv.gz  in=369,210,743 out=113,089,395 elapsed=165.8s

  [13451/21087] intraday_2364.csv.gz  in=369,220,558 out=113,089,395 elapsed=165.8s

  [13452/21087] intraday_2363.csv.gz  in=369,235,635 out=113,089,395 elapsed=165.8s

  [13453/21087] intraday_2365.csv.gz  in=369,248,282 out=113,089,395 elapsed=165.8s

  [13454/21087] intraday_2366.csv.gz  in=369,262,209 out=113,089,395 elapsed=165.8s

  [13455/21087] intraday_2367.csv.gz  in=369,272,874 out=113,089,395 elapsed=165.8s

  [13456/21087] intraday_2368.csv.gz  in=369,284,337 out=113,089,395 elapsed=165.8s

  [13457/21087] intraday_2369.csv.gz  in=369,296,898 out=113,089,395 elapsed=165.8s

  [13458/21087] intraday_2370.csv.gz  in=369,309,956 out=113,089,395 elapsed=165.8s

  [13459/21087] intraday_2372.csv.gz  in=369,320,871 out=113,089,395 elapsed=165.9s

  [13460/21087] intraday_2371.csv.gz  in=369,333,424 out=113,089,395 elapsed=165.9s

  [13461/21087] intraday_2373.csv.gz  in=369,345,490 out=113,089,395 elapsed=165.9s

  [13462/21087] intraday_2374.csv.gz  in=369,359,555 out=113,089,395 elapsed=165.9s

  [13463/21087] intraday_2375.csv.gz  in=369,371,587 out=113,089,395 elapsed=165.9s

  [13464/21087] intraday_2376.csv.gz  in=369,383,966 out=113,089,395 elapsed=165.9s

  [13465/21087] intraday_2377.csv.gz  in=369,402,245 out=113,089,395 elapsed=165.9s

  [13466/21087] intraday_2378.csv.gz  in=369,415,171 out=113,089,395 elapsed=165.9s

  [13467/21087] intraday_2379.csv.gz  in=369,424,656 out=113,089,395 elapsed=165.9s

  [13468/21087] intraday_2380.csv.gz  in=369,437,018 out=113,089,395 elapsed=165.9s

  [13469/21087] intraday_2381.csv.gz  in=369,453,151 out=113,089,395 elapsed=165.9s

  [13470/21087] intraday_2382.csv.gz  in=369,466,616 out=113,089,395 elapsed=165.9s

  [13471/21087] intraday_2384.csv.gz  in=369,481,133 out=113,089,395 elapsed=165.9s

  [13472/21087] intraday_2383.csv.gz  in=369,496,458 out=113,089,395 elapsed=165.9s

  [13473/21087] intraday_2385.csv.gz  in=369,508,516 out=113,089,395 elapsed=166.0s

  [13474/21087] intraday_2386.csv.gz  in=369,520,818 out=113,089,395 elapsed=166.0s

  [13475/21087] intraday_2388.csv.gz  in=369,532,445 out=113,089,395 elapsed=166.0s

  [13476/21087] intraday_2387.csv.gz  in=369,555,721 out=113,089,395 elapsed=166.0s

  [13477/21087] intraday_2389.csv.gz  in=369,568,018 out=113,089,395 elapsed=166.0s

  [13478/21087] intraday_2390.csv.gz  in=369,579,714 out=113,089,395 elapsed=166.0s

  [13479/21087] intraday_2391.csv.gz  in=369,591,111 out=113,089,395 elapsed=166.0s

  [13480/21087] intraday_2392.csv.gz  in=369,602,790 out=113,089,395 elapsed=166.0s

  [13481/21087] intraday_2393.csv.gz  in=369,614,736 out=113,089,395 elapsed=166.0s

  [13482/21087] intraday_2394.csv.gz  in=369,629,118 out=113,089,395 elapsed=166.0s

  [13483/21087] intraday_2395.csv.gz  in=369,643,118 out=113,089,395 elapsed=166.0s

  [13484/21087] intraday_2396.csv.gz  in=369,655,355 out=113,089,395 elapsed=166.0s

  [13485/21087] intraday_2397.csv.gz  in=369,669,029 out=113,089,395 elapsed=166.1s

  [13486/21087] intraday_2398.csv.gz  in=369,684,387 out=113,089,395 elapsed=166.1s

  [13487/21087] intraday_2399.csv.gz  in=369,698,067 out=113,089,395 elapsed=166.1s

  [13488/21087] intraday_2400.csv.gz  in=369,715,352 out=113,089,395 elapsed=166.1s

  [13489/21087] intraday_2401.csv.gz  in=369,735,896 out=113,089,395 elapsed=166.1s

  [13490/21087] intraday_2402.csv.gz  in=369,747,996 out=113,089,395 elapsed=166.1s

  [13491/21087] intraday_2403.csv.gz  in=369,760,203 out=113,089,395 elapsed=166.1s

  [13492/21087] intraday_2404.csv.gz  in=369,780,567 out=113,089,395 elapsed=166.1s

  [13493/21087] intraday_2405.csv.gz  in=369,792,745 out=113,089,395 elapsed=166.1s

  [13494/21087] intraday_2406.csv.gz  in=369,804,536 out=113,089,395 elapsed=166.1s

  [13495/21087] intraday_2407.csv.gz  in=369,818,177 out=113,089,395 elapsed=166.1s

  [13496/21087] intraday_2408.csv.gz  in=369,834,347 out=113,089,395 elapsed=166.1s

  [13497/21087] intraday_2409.csv.gz  in=369,847,647 out=113,089,395 elapsed=166.1s

  [13498/21087] intraday_2411.csv.gz  in=369,861,354 out=113,089,395 elapsed=166.2s

  [13499/21087] intraday_2410.csv.gz  in=369,881,492 out=113,089,395 elapsed=166.2s

  [13500/21087] intraday_2412.csv.gz  in=369,894,125 out=113,089,395 elapsed=166.2s

  [13501/21087] intraday_2413.csv.gz  in=369,907,525 out=113,089,395 elapsed=166.2s

  [13502/21087] intraday_2414.csv.gz  in=369,922,562 out=113,089,395 elapsed=166.2s

  [13503/21087] intraday_2415.csv.gz  in=369,935,099 out=113,089,395 elapsed=166.2s

  [13504/21087] intraday_2416.csv.gz  in=369,955,352 out=113,089,395 elapsed=166.2s

  [13505/21087] intraday_2417.csv.gz  in=369,983,871 out=113,089,395 elapsed=166.2s

  [13506/21087] intraday_2418.csv.gz  in=369,998,057 out=113,089,395 elapsed=166.2s

  [13507/21087] intraday_2419.csv.gz  in=370,012,437 out=113,089,395 elapsed=166.2s

  [13508/21087] intraday_2420.csv.gz  in=370,026,892 out=113,089,395 elapsed=166.2s

  [13509/21087] intraday_2422.csv.gz  in=370,036,862 out=113,089,395 elapsed=166.3s

  [13510/21087] intraday_2421.csv.gz  in=370,052,489 out=113,089,395 elapsed=166.3s

  [13511/21087] intraday_2423.csv.gz  in=370,064,468 out=113,089,395 elapsed=166.3s

  [13512/21087] intraday_2424.csv.gz  in=370,077,079 out=113,089,395 elapsed=166.3s

  [13513/21087] intraday_2425.csv.gz  in=370,091,726 out=113,089,395 elapsed=166.3s

  [13514/21087] intraday_2426.csv.gz  in=370,101,259 out=113,089,395 elapsed=166.3s

  [13515/21087] intraday_2427.csv.gz  in=370,113,724 out=113,089,395 elapsed=166.3s

  [13516/21087] intraday_2428.csv.gz  in=370,124,537 out=113,089,395 elapsed=166.3s

  [13517/21087] intraday_2431.csv.gz  in=370,136,910 out=113,089,395 elapsed=166.3s

  [13518/21087] intraday_2430.csv.gz  in=370,149,054 out=113,089,395 elapsed=166.3s

  [13519/21087] intraday_2429.csv.gz  in=370,165,640 out=113,089,395 elapsed=166.4s

  [13520/21087] intraday_2432.csv.gz  in=370,177,214 out=113,089,395 elapsed=166.4s

  [13521/21087] intraday_2433.csv.gz  in=370,187,950 out=113,089,395 elapsed=166.4s

  [13522/21087] intraday_2434.csv.gz  in=370,199,300 out=113,089,395 elapsed=166.4s

  [13523/21087] intraday_2435.csv.gz  in=370,213,950 out=113,089,395 elapsed=166.4s

  [13524/21087] intraday_2436.csv.gz  in=370,239,239 out=113,089,395 elapsed=166.4s

  [13525/21087] intraday_2437.csv.gz  in=370,251,892 out=113,089,395 elapsed=166.4s

  [13526/21087] intraday_2438.csv.gz  in=370,264,233 out=113,089,395 elapsed=166.4s

  [13527/21087] intraday_2439.csv.gz  in=370,275,586 out=113,089,395 elapsed=166.4s

  [13528/21087] intraday_2440.csv.gz  in=370,287,935 out=113,089,395 elapsed=166.4s

  [13529/21087] intraday_2441.csv.gz  in=370,302,668 out=113,089,395 elapsed=166.4s

  [13530/21087] intraday_2442.csv.gz  in=370,315,422 out=113,089,395 elapsed=166.4s

  [13531/21087] intraday_2443.csv.gz  in=370,329,154 out=113,089,395 elapsed=166.4s

  [13532/21087] intraday_2444.csv.gz  in=370,342,012 out=113,089,395 elapsed=166.5s

  [13533/21087] intraday_2445.csv.gz  in=370,356,445 out=113,089,395 elapsed=166.5s

  [13534/21087] intraday_2446.csv.gz  in=370,370,443 out=113,089,395 elapsed=166.5s

  [13535/21087] intraday_2447.csv.gz  in=370,385,075 out=113,089,395 elapsed=166.5s

  [13536/21087] intraday_2448.csv.gz  in=370,398,980 out=113,089,395 elapsed=166.5s

  [13537/21087] intraday_2450.csv.gz  in=370,411,629 out=113,089,395 elapsed=166.5s

  [13538/21087] intraday_2449.csv.gz  in=370,423,030 out=113,089,395 elapsed=166.5s

  [13539/21087] intraday_2451.csv.gz  in=370,436,946 out=113,089,395 elapsed=166.5s

  [13540/21087] intraday_2452.csv.gz  in=370,450,249 out=113,089,395 elapsed=166.5s

  [13541/21087] intraday_2453.csv.gz  in=370,461,539 out=113,089,395 elapsed=166.5s

  [13542/21087] intraday_2454.csv.gz  in=370,475,377 out=113,089,395 elapsed=166.5s

  [13543/21087] intraday_2455.csv.gz  in=370,490,504 out=113,089,395 elapsed=166.5s

  [13544/21087] intraday_2456.csv.gz  in=370,505,459 out=113,089,395 elapsed=166.5s

  [13545/21087] intraday_2457.csv.gz  in=370,521,722 out=113,089,395 elapsed=166.6s

  [13546/21087] intraday_2458.csv.gz  in=370,531,956 out=113,089,395 elapsed=166.6s

  [13547/21087] intraday_2459.csv.gz  in=370,544,723 out=113,089,395 elapsed=166.6s

  [13548/21087] intraday_2460.csv.gz  in=370,558,883 out=113,089,395 elapsed=166.6s

  [13549/21087] intraday_2461.csv.gz  in=370,573,819 out=113,089,395 elapsed=166.6s

  [13550/21087] intraday_2462.csv.gz  in=370,587,199 out=113,089,395 elapsed=166.6s

  [13551/21087] intraday_2463.csv.gz  in=370,601,632 out=113,089,395 elapsed=166.6s

  [13552/21087] intraday_2464.csv.gz  in=370,613,811 out=113,089,395 elapsed=166.6s

  [13553/21087] intraday_2465.csv.gz  in=370,627,243 out=113,089,395 elapsed=166.6s

  [13554/21087] intraday_2466.csv.gz  in=370,640,292 out=113,089,395 elapsed=166.6s

  [13555/21087] intraday_2467.csv.gz  in=370,654,621 out=113,089,395 elapsed=166.6s

  [13556/21087] intraday_2468.csv.gz  in=370,666,441 out=113,089,395 elapsed=166.6s

  [13557/21087] intraday_2469.csv.gz  in=370,683,669 out=113,089,395 elapsed=166.6s

  [13558/21087] intraday_2470.csv.gz  in=370,696,137 out=113,089,395 elapsed=166.7s

  [13559/21087] intraday_2471.csv.gz  in=370,710,350 out=113,089,395 elapsed=166.7s

  [13560/21087] intraday_2474.csv.gz  in=370,721,309 out=113,089,395 elapsed=166.7s

  [13561/21087] intraday_2473.csv.gz  in=370,734,416 out=113,089,395 elapsed=166.7s

  [13562/21087] intraday_2472.csv.gz  in=370,750,041 out=113,089,395 elapsed=166.7s

  [13563/21087] intraday_2475.csv.gz  in=370,764,539 out=113,089,395 elapsed=166.7s

  [13564/21087] intraday_2476.csv.gz  in=370,777,903 out=113,089,395 elapsed=166.7s

  [13565/21087] intraday_2477.csv.gz  in=370,794,037 out=113,089,395 elapsed=166.7s

  [13566/21087] intraday_2478.csv.gz  in=370,805,983 out=113,089,395 elapsed=166.7s

  [13567/21087] intraday_2479.csv.gz  in=370,820,085 out=113,089,395 elapsed=166.7s

  [13568/21087] intraday_2480.csv.gz  in=370,834,066 out=113,089,395 elapsed=166.7s

  [13569/21087] intraday_2481.csv.gz  in=370,849,600 out=113,089,395 elapsed=166.8s

  [13570/21087] intraday_2482.csv.gz  in=370,863,884 out=113,089,395 elapsed=166.8s

  [13571/21087] intraday_2483.csv.gz  in=370,878,786 out=113,089,395 elapsed=166.8s

  [13572/21087] intraday_2484.csv.gz  in=370,894,598 out=113,089,395 elapsed=166.8s

  [13573/21087] intraday_2486.csv.gz  in=370,908,955 out=113,089,395 elapsed=166.8s

  [13574/21087] intraday_2485.csv.gz  in=370,922,330 out=113,089,395 elapsed=166.8s

  [13575/21087] intraday_2487.csv.gz  in=370,934,119 out=113,089,395 elapsed=166.8s

  [13576/21087] intraday_2488.csv.gz  in=370,946,335 out=113,089,395 elapsed=166.8s

  [13577/21087] intraday_2489.csv.gz  in=370,958,140 out=113,089,395 elapsed=166.8s

  [13578/21087] intraday_2491.csv.gz  in=370,966,857 out=113,089,395 elapsed=166.8s

  [13579/21087] intraday_2492.csv.gz  in=370,974,919 out=113,089,395 elapsed=166.8s

  [13580/21087] intraday_2490.csv.gz  in=370,989,594 out=113,089,395 elapsed=166.8s

  [13581/21087] intraday_2493.csv.gz  in=371,001,083 out=113,089,395 elapsed=166.9s

  [13582/21087] intraday_2494.csv.gz  in=371,016,380 out=113,089,395 elapsed=166.9s

  [13583/21087] intraday_2495.csv.gz  in=371,030,295 out=113,089,395 elapsed=166.9s

  [13584/21087] intraday_2496.csv.gz  in=371,042,108 out=113,089,395 elapsed=166.9s

  [13585/21087] intraday_2497.csv.gz  in=371,053,097 out=113,089,395 elapsed=166.9s

  [13586/21087] intraday_2498.csv.gz  in=371,067,841 out=113,089,395 elapsed=166.9s

  [13587/21087] intraday_2499.csv.gz  in=371,081,744 out=113,089,395 elapsed=166.9s

  [13588/21087] intraday_2501.csv.gz  in=371,093,604 out=113,089,395 elapsed=166.9s

  [13589/21087] intraday_2500.csv.gz  in=371,106,054 out=113,089,395 elapsed=166.9s

  [13590/21087] intraday_2502.csv.gz  in=371,119,413 out=113,089,395 elapsed=166.9s

  [13591/21087] intraday_2503.csv.gz  in=371,133,837 out=113,089,395 elapsed=166.9s

  [13592/21087] intraday_2504.csv.gz  in=371,142,926 out=113,089,395 elapsed=166.9s

  [13593/21087] intraday_2505.csv.gz  in=371,154,092 out=113,089,395 elapsed=167.0s

  [13594/21087] intraday_2506.csv.gz  in=371,167,026 out=113,089,395 elapsed=167.0s

  [13595/21087] intraday_2507.csv.gz  in=371,177,766 out=113,089,395 elapsed=167.0s

  [13596/21087] intraday_2508.csv.gz  in=371,189,102 out=113,089,395 elapsed=167.0s

  [13597/21087] intraday_2510.csv.gz  in=371,201,228 out=113,089,395 elapsed=167.0s

  [13598/21087] intraday_2509.csv.gz  in=371,213,113 out=113,089,395 elapsed=167.0s

  [13599/21087] intraday_2511.csv.gz  in=371,225,122 out=113,089,395 elapsed=167.0s

  [13600/21087] intraday_2512.csv.gz  in=371,236,878 out=113,089,395 elapsed=167.0s

  [13601/21087] intraday_2513.csv.gz  in=371,248,155 out=113,089,395 elapsed=167.0s

  [13602/21087] intraday_2515.csv.gz  in=371,259,886 out=113,089,395 elapsed=167.0s

  [13603/21087] intraday_2514.csv.gz  in=371,272,932 out=113,089,395 elapsed=167.0s

  [13604/21087] intraday_2516.csv.gz  in=371,285,063 out=113,089,395 elapsed=167.0s

  [13605/21087] intraday_2519.csv.gz  in=371,293,880 out=113,089,395 elapsed=167.1s

  [13606/21087] intraday_2518.csv.gz  in=371,305,775 out=113,089,395 elapsed=167.1s

  [13607/21087] intraday_2517.csv.gz  in=371,318,361 out=113,089,395 elapsed=167.1s

  [13608/21087] intraday_2520.csv.gz  in=371,330,197 out=113,089,395 elapsed=167.1s

  [13609/21087] intraday_2521.csv.gz  in=371,343,668 out=113,089,395 elapsed=167.1s

  [13610/21087] intraday_2522.csv.gz  in=371,356,067 out=113,089,395 elapsed=167.1s

  [13611/21087] intraday_2523.csv.gz  in=371,370,542 out=113,089,395 elapsed=167.1s

  [13612/21087] intraday_2524.csv.gz  in=371,383,913 out=113,089,395 elapsed=167.1s

  [13613/21087] intraday_2525.csv.gz  in=371,395,284 out=113,089,395 elapsed=167.1s

  [13614/21087] intraday_2526.csv.gz  in=371,407,949 out=113,089,395 elapsed=167.1s

  [13615/21087] intraday_2527.csv.gz  in=371,420,780 out=113,089,395 elapsed=167.1s

  [13616/21087] intraday_2528.csv.gz  in=371,431,900 out=113,089,395 elapsed=167.1s

  [13617/21087] intraday_2529.csv.gz  in=371,444,986 out=113,089,395 elapsed=167.2s

  [13618/21087] intraday_2530.csv.gz  in=371,456,538 out=113,089,395 elapsed=167.2s

  [13619/21087] intraday_2531.csv.gz  in=371,466,915 out=113,089,395 elapsed=167.2s

  [13620/21087] intraday_2532.csv.gz  in=371,479,188 out=113,089,395 elapsed=167.2s

  [13621/21087] intraday_2533.csv.gz  in=371,489,141 out=113,089,395 elapsed=167.2s

  [13622/21087] intraday_2535.csv.gz  in=371,501,294 out=113,089,395 elapsed=167.2s

  [13623/21087] intraday_2534.csv.gz  in=371,516,356 out=113,089,395 elapsed=167.2s

  [13624/21087] intraday_2536.csv.gz  in=371,530,702 out=113,089,395 elapsed=167.2s

  [13625/21087] intraday_2537.csv.gz  in=371,542,487 out=113,089,395 elapsed=167.2s

  [13626/21087] intraday_2538.csv.gz  in=371,554,772 out=113,089,395 elapsed=167.2s

  [13627/21087] intraday_2539.csv.gz  in=371,566,825 out=113,089,395 elapsed=167.2s

  [13628/21087] intraday_2541.csv.gz  in=371,578,934 out=113,089,395 elapsed=167.2s

  [13629/21087] intraday_2540.csv.gz  in=371,589,193 out=113,089,395 elapsed=167.2s

  [13630/21087] intraday_2542.csv.gz  in=371,601,290 out=113,089,395 elapsed=167.3s

  [13631/21087] intraday_2543.csv.gz  in=371,611,490 out=113,089,395 elapsed=167.3s

  [13632/21087] intraday_2544.csv.gz  in=371,624,525 out=113,089,395 elapsed=167.3s

  [13633/21087] intraday_2545.csv.gz  in=371,635,435 out=113,089,395 elapsed=167.3s

  [13634/21087] intraday_2546.csv.gz  in=371,646,799 out=113,089,395 elapsed=167.3s

  [13635/21087] intraday_2547.csv.gz  in=371,660,410 out=113,089,395 elapsed=167.3s

  [13636/21087] intraday_2548.csv.gz  in=371,674,406 out=113,089,395 elapsed=167.3s

  [13637/21087] intraday_2549.csv.gz  in=371,685,313 out=113,089,395 elapsed=167.3s

  [13638/21087] intraday_2550.csv.gz  in=371,696,316 out=113,089,395 elapsed=167.3s

  [13639/21087] intraday_2551.csv.gz  in=371,709,718 out=113,089,395 elapsed=167.4s

  [13640/21087] intraday_2553.csv.gz  in=371,722,162 out=113,089,395 elapsed=167.4s

  [13641/21087] intraday_2554.csv.gz  in=371,732,926 out=113,089,395 elapsed=167.4s

  [13642/21087] intraday_2552.csv.gz  in=371,746,465 out=113,089,395 elapsed=167.4s

  [13643/21087] intraday_2555.csv.gz  in=371,757,400 out=113,089,395 elapsed=167.4s

  [13644/21087] intraday_2556.csv.gz  in=371,767,286 out=113,089,395 elapsed=167.4s

  [13645/21087] intraday_2558.csv.gz  in=371,779,107 out=113,089,395 elapsed=167.4s

  [13646/21087] intraday_2557.csv.gz  in=371,793,563 out=113,089,395 elapsed=167.4s

  [13647/21087] intraday_2559.csv.gz  in=371,806,642 out=113,089,395 elapsed=167.4s

  [13648/21087] intraday_2560.csv.gz  in=371,819,633 out=113,089,395 elapsed=167.4s

  [13649/21087] intraday_2561.csv.gz  in=371,831,089 out=113,089,395 elapsed=167.4s

  [13650/21087] intraday_2562.csv.gz  in=371,842,710 out=113,089,395 elapsed=167.4s

  [13651/21087] intraday_2563.csv.gz  in=371,855,246 out=113,089,395 elapsed=167.4s

  [13652/21087] intraday_2564.csv.gz  in=371,865,827 out=113,089,395 elapsed=167.5s

  [13653/21087] intraday_2565.csv.gz  in=371,878,476 out=113,089,395 elapsed=167.5s

  [13654/21087] intraday_2566.csv.gz  in=371,888,186 out=113,089,395 elapsed=167.5s

  [13655/21087] intraday_2567.csv.gz  in=371,899,831 out=113,089,395 elapsed=167.5s

  [13656/21087] intraday_2568.csv.gz  in=371,912,129 out=113,089,395 elapsed=167.5s

  [13657/21087] intraday_2569.csv.gz  in=371,923,815 out=113,089,395 elapsed=167.5s

  [13658/21087] intraday_2570.csv.gz  in=371,935,494 out=113,089,395 elapsed=167.5s

  [13659/21087] intraday_2571.csv.gz  in=371,947,685 out=113,089,395 elapsed=167.5s

  [13660/21087] intraday_2572.csv.gz  in=371,958,013 out=113,089,395 elapsed=167.5s

  [13661/21087] intraday_2573.csv.gz  in=371,969,180 out=113,089,395 elapsed=167.5s

  [13662/21087] intraday_2574.csv.gz  in=371,980,966 out=113,089,395 elapsed=167.5s

  [13663/21087] intraday_2575.csv.gz  in=371,995,433 out=113,089,395 elapsed=167.6s

  [13664/21087] intraday_2576.csv.gz  in=372,007,180 out=113,089,395 elapsed=167.6s

  [13665/21087] intraday_2577.csv.gz  in=372,019,567 out=113,089,395 elapsed=167.6s

  [13666/21087] intraday_2578.csv.gz  in=372,032,095 out=113,089,395 elapsed=167.6s

  [13667/21087] intraday_2579.csv.gz  in=372,043,832 out=113,089,395 elapsed=167.6s

  [13668/21087] intraday_2580.csv.gz  in=372,056,249 out=113,089,395 elapsed=167.6s

  [13669/21087] intraday_2581.csv.gz  in=372,071,533 out=113,089,395 elapsed=167.6s

  [13670/21087] intraday_2582.csv.gz  in=372,082,181 out=113,089,395 elapsed=167.6s

  [13671/21087] intraday_2583.csv.gz  in=372,096,648 out=113,089,395 elapsed=167.6s

  [13672/21087] intraday_2584.csv.gz  in=372,109,297 out=113,089,395 elapsed=167.6s

  [13673/21087] intraday_2585.csv.gz  in=372,122,724 out=113,089,395 elapsed=167.6s

  [13674/21087] intraday_2586.csv.gz  in=372,136,444 out=113,089,395 elapsed=167.6s

  [13675/21087] intraday_2587.csv.gz  in=372,149,263 out=113,089,395 elapsed=167.6s

  [13676/21087] intraday_2588.csv.gz  in=372,161,392 out=113,089,395 elapsed=167.7s

  [13677/21087] intraday_2589.csv.gz  in=372,173,841 out=113,089,395 elapsed=167.7s

  [13678/21087] intraday_2590.csv.gz  in=372,184,393 out=113,089,395 elapsed=167.7s

  [13679/21087] intraday_2591.csv.gz  in=372,195,919 out=113,089,395 elapsed=167.7s

  [13680/21087] intraday_2592.csv.gz  in=372,206,989 out=113,089,395 elapsed=167.7s

  [13681/21087] intraday_2593.csv.gz  in=372,220,271 out=113,089,395 elapsed=167.7s

  [13682/21087] intraday_2594.csv.gz  in=372,231,322 out=113,089,395 elapsed=167.7s

  [13683/21087] intraday_2595.csv.gz  in=372,244,466 out=113,089,395 elapsed=167.7s

  [13684/21087] intraday_2596.csv.gz  in=372,256,665 out=113,089,395 elapsed=167.7s

  [13685/21087] intraday_2598.csv.gz  in=372,267,763 out=113,089,395 elapsed=167.7s

  [13686/21087] intraday_2597.csv.gz  in=372,281,275 out=113,089,395 elapsed=167.7s

  [13687/21087] intraday_2599.csv.gz  in=372,294,168 out=113,089,395 elapsed=167.7s

  [13688/21087] intraday_2600.csv.gz  in=372,308,940 out=113,089,395 elapsed=167.7s

  [13689/21087] intraday_2601.csv.gz  in=372,322,691 out=113,089,395 elapsed=167.7s

  [13690/21087] intraday_2602.csv.gz  in=372,335,964 out=113,089,395 elapsed=167.8s

  [13691/21087] intraday_2603.csv.gz  in=372,349,527 out=113,089,395 elapsed=167.8s

  [13692/21087] intraday_2604.csv.gz  in=372,361,444 out=113,089,395 elapsed=167.8s

  [13693/21087] intraday_2605.csv.gz  in=372,374,043 out=113,089,395 elapsed=167.8s

  [13694/21087] intraday_2606.csv.gz  in=372,387,257 out=113,089,395 elapsed=167.8s

  [13695/21087] intraday_2607.csv.gz  in=372,399,829 out=113,089,395 elapsed=167.8s

  [13696/21087] intraday_2608.csv.gz  in=372,415,581 out=113,089,395 elapsed=167.8s

  [13697/21087] intraday_2609.csv.gz  in=372,429,200 out=113,089,395 elapsed=167.8s

  [13698/21087] intraday_2610.csv.gz  in=372,441,925 out=113,089,395 elapsed=167.8s

  [13699/21087] intraday_2611.csv.gz  in=372,455,958 out=113,089,395 elapsed=167.8s

  [13700/21087] intraday_2612.csv.gz  in=372,465,809 out=113,089,395 elapsed=167.8s

  [13701/21087] intraday_2613.csv.gz  in=372,478,405 out=113,089,395 elapsed=167.8s

  [13702/21087] intraday_2614.csv.gz  in=372,489,213 out=113,089,395 elapsed=167.8s

  [13703/21087] intraday_2615.csv.gz  in=372,503,654 out=113,089,395 elapsed=167.9s

  [13704/21087] intraday_2616.csv.gz  in=372,517,440 out=113,089,395 elapsed=167.9s

  [13705/21087] intraday_2618.csv.gz  in=372,529,381 out=113,089,395 elapsed=167.9s

  [13706/21087] intraday_2617.csv.gz  in=372,545,507 out=113,089,395 elapsed=167.9s

  [13707/21087] intraday_2619.csv.gz  in=372,559,448 out=113,089,395 elapsed=167.9s

  [13708/21087] intraday_2620.csv.gz  in=372,573,048 out=113,089,395 elapsed=167.9s

  [13709/21087] intraday_2622.csv.gz  in=372,586,142 out=113,089,395 elapsed=167.9s

  [13710/21087] intraday_2621.csv.gz  in=372,599,758 out=113,089,395 elapsed=167.9s

  [13711/21087] intraday_2623.csv.gz  in=372,615,352 out=113,089,395 elapsed=167.9s

  [13712/21087] intraday_2624.csv.gz  in=372,629,693 out=113,089,395 elapsed=167.9s

  [13713/21087] intraday_2625.csv.gz  in=372,643,286 out=113,089,395 elapsed=167.9s

  [13714/21087] intraday_2626.csv.gz  in=372,656,140 out=113,089,395 elapsed=167.9s

  [13715/21087] intraday_2627.csv.gz  in=372,666,045 out=113,089,395 elapsed=167.9s

  [13716/21087] intraday_2628.csv.gz  in=372,678,862 out=113,089,395 elapsed=168.0s

  [13717/21087] intraday_2631.csv.gz  in=372,685,933 out=113,089,395 elapsed=168.0s

  [13718/21087] intraday_2629.csv.gz  in=372,698,089 out=113,089,395 elapsed=168.0s

  [13719/21087] intraday_2630.csv.gz  in=372,709,966 out=113,089,395 elapsed=168.0s

  [13720/21087] intraday_2635.csv.gz  in=372,710,091 out=113,089,395 elapsed=168.0s

  [13721/21087] intraday_2634.csv.gz  in=372,712,292 out=113,089,395 elapsed=168.0s

  [13722/21087] intraday_2633.csv.gz  in=372,718,315 out=113,089,395 elapsed=168.0s

  [13723/21087] intraday_2632.csv.gz  in=372,728,578 out=113,089,395 elapsed=168.0s

  [13724/21087] intraday_2637.csv.gz  in=372,728,802 out=113,089,395 elapsed=168.0s

  [13725/21087] intraday_2636.csv.gz  in=372,741,264 out=113,089,395 elapsed=168.0s

  [13726/21087] intraday_2641.csv.gz  in=372,741,297 out=113,089,395 elapsed=168.0s

  [13727/21087] intraday_2639.csv.gz  in=372,741,408 out=113,089,395 elapsed=168.1s

  [13728/21087] intraday_2638.csv.gz  in=372,741,489 out=113,089,395 elapsed=168.1s

  [13729/21087] intraday_2640.csv.gz  in=372,747,978 out=113,089,395 elapsed=168.1s

  [13730/21087] intraday_2642.csv.gz  in=372,747,989 out=113,089,395 elapsed=168.1s

  [13731/21087] intraday_2644.csv.gz  in=372,748,031 out=113,089,395 elapsed=168.1s

  [13732/21087] intraday_2643.csv.gz  in=372,748,043 out=113,089,395 elapsed=168.1s

  [13733/21087] intraday_2645.csv.gz  in=372,748,819 out=113,089,395 elapsed=168.1s

  [13734/21087] intraday_2646.csv.gz  in=372,748,890 out=113,089,395 elapsed=168.1s

  [13735/21087] intraday_2648.csv.gz  in=372,748,934 out=113,089,395 elapsed=168.1s

  [13736/21087] intraday_2649.csv.gz  in=372,748,963 out=113,089,395 elapsed=168.1s

  [13737/21087] intraday_2647.csv.gz  in=372,760,106 out=113,089,395 elapsed=168.1s

  [13738/21087] intraday_2650.csv.gz  in=372,774,766 out=113,089,395 elapsed=168.1s

  [13739/21087] intraday_2652.csv.gz  in=372,774,781 out=113,089,395 elapsed=168.1s

  [13740/21087] intraday_2651.csv.gz  in=372,774,868 out=113,089,395 elapsed=168.1s

  [13741/21087] intraday_2654.csv.gz  in=372,775,199 out=113,089,395 elapsed=168.2s

  [13742/21087] intraday_2653.csv.gz  in=372,781,053 out=113,089,395 elapsed=168.2s

  [13743/21087] intraday_2655.csv.gz  in=372,781,219 out=113,089,395 elapsed=168.2s

  [13744/21087] intraday_2656.csv.gz  in=372,783,164 out=113,089,395 elapsed=168.2s

  [13745/21087] intraday_2659.csv.gz  in=372,783,187 out=113,089,395 elapsed=168.2s

  [13746/21087] intraday_2657.csv.gz  in=372,786,387 out=113,089,395 elapsed=168.2s

  [13747/21087] intraday_2658.csv.gz  in=372,790,547 out=113,089,395 elapsed=168.2s

  [13748/21087] intraday_2660.csv.gz  in=372,794,025 out=113,089,395 elapsed=168.2s

  [13749/21087] intraday_2662.csv.gz  in=372,794,068 out=113,089,395 elapsed=168.2s

  [13750/21087] intraday_2661.csv.gz  in=372,802,743 out=113,089,395 elapsed=168.2s

  [13751/21087] intraday_2663.csv.gz  in=372,802,903 out=113,089,395 elapsed=168.2s

  [13752/21087] intraday_2664.csv.gz  in=372,802,991 out=113,089,395 elapsed=168.2s

  [13753/21087] intraday_2665.csv.gz  in=372,817,825 out=113,089,395 elapsed=168.2s

  [13754/21087] intraday_2666.csv.gz  in=372,831,127 out=113,089,395 elapsed=168.2s

  [13755/21087] intraday_2668.csv.gz  in=372,841,428 out=113,089,395 elapsed=168.3s

  [13756/21087] intraday_2667.csv.gz  in=372,853,880 out=113,089,395 elapsed=168.3s

  [13757/21087] intraday_2669.csv.gz  in=372,867,785 out=113,089,395 elapsed=168.3s

  [13758/21087] intraday_2670.csv.gz  in=372,881,014 out=113,089,395 elapsed=168.3s

  [13759/21087] intraday_2671.csv.gz  in=372,892,457 out=113,089,395 elapsed=168.3s

  [13760/21087] intraday_2672.csv.gz  in=372,906,494 out=113,089,395 elapsed=168.3s

  [13761/21087] intraday_2673.csv.gz  in=372,919,260 out=113,089,395 elapsed=168.3s

  [13762/21087] intraday_2675.csv.gz  in=372,927,938 out=113,089,395 elapsed=168.3s

  [13763/21087] intraday_2674.csv.gz  in=372,941,155 out=113,089,395 elapsed=168.3s

  [13764/21087] intraday_2676.csv.gz  in=372,952,617 out=113,089,395 elapsed=168.3s

  [13765/21087] intraday_2677.csv.gz  in=372,963,620 out=113,089,395 elapsed=168.3s

  [13766/21087] intraday_2679.csv.gz  in=372,974,160 out=113,089,395 elapsed=168.3s

  [13767/21087] intraday_2678.csv.gz  in=372,991,022 out=113,089,395 elapsed=168.3s

  [13768/21087] intraday_2680.csv.gz  in=373,000,895 out=113,089,395 elapsed=168.4s

  [13769/21087] intraday_2681.csv.gz  in=373,013,219 out=113,089,395 elapsed=168.4s

  [13770/21087] intraday_2682.csv.gz  in=373,024,905 out=113,089,395 elapsed=168.4s

  [13771/21087] intraday_2683.csv.gz  in=373,035,163 out=113,089,395 elapsed=168.4s

  [13772/21087] intraday_2684.csv.gz  in=373,048,153 out=113,089,395 elapsed=168.4s

  [13773/21087] intraday_2685.csv.gz  in=373,060,076 out=113,089,395 elapsed=168.4s

  [13774/21087] intraday_2686.csv.gz  in=373,072,431 out=113,089,395 elapsed=168.4s

  [13775/21087] intraday_2687.csv.gz  in=373,083,753 out=113,089,395 elapsed=168.4s

  [13776/21087] intraday_2688.csv.gz  in=373,094,720 out=113,089,395 elapsed=168.4s

  [13777/21087] intraday_2689.csv.gz  in=373,105,965 out=113,089,395 elapsed=168.4s

  [13778/21087] intraday_2690.csv.gz  in=373,115,462 out=113,089,395 elapsed=168.4s

  [13779/21087] intraday_2691.csv.gz  in=373,127,252 out=113,089,395 elapsed=168.4s

  [13780/21087] intraday_2692.csv.gz  in=373,139,040 out=113,089,395 elapsed=168.4s

  [13781/21087] intraday_2693.csv.gz  in=373,151,271 out=113,089,395 elapsed=168.5s

  [13782/21087] intraday_2694.csv.gz  in=373,164,922 out=113,089,395 elapsed=168.5s

  [13783/21087] intraday_2695.csv.gz  in=373,177,570 out=113,089,395 elapsed=168.5s

  [13784/21087] intraday_2696.csv.gz  in=373,188,316 out=113,089,395 elapsed=168.5s

  [13785/21087] intraday_2697.csv.gz  in=373,200,143 out=113,089,395 elapsed=168.5s

  [13786/21087] intraday_2698.csv.gz  in=373,212,829 out=113,089,395 elapsed=168.5s

  [13787/21087] intraday_2699.csv.gz  in=373,223,638 out=113,089,395 elapsed=168.5s

  [13788/21087] intraday_2700.csv.gz  in=373,237,044 out=113,089,395 elapsed=168.5s

  [13789/21087] intraday_2701.csv.gz  in=373,245,945 out=113,089,395 elapsed=168.5s

  [13790/21087] intraday_2702.csv.gz  in=373,257,261 out=113,089,395 elapsed=168.5s

  [13791/21087] intraday_2703.csv.gz  in=373,266,899 out=113,089,395 elapsed=168.5s

  [13792/21087] intraday_2704.csv.gz  in=373,278,094 out=113,089,395 elapsed=168.5s

  [13793/21087] intraday_2705.csv.gz  in=373,290,598 out=113,089,395 elapsed=168.5s

  [13794/21087] intraday_2706.csv.gz  in=373,303,912 out=113,089,395 elapsed=168.6s

  [13795/21087] intraday_2707.csv.gz  in=373,319,884 out=113,089,395 elapsed=168.6s

  [13796/21087] intraday_2708.csv.gz  in=373,332,727 out=113,089,395 elapsed=168.6s

  [13797/21087] intraday_2709.csv.gz  in=373,343,892 out=113,089,395 elapsed=168.6s

  [13798/21087] intraday_2710.csv.gz  in=373,354,732 out=113,089,395 elapsed=168.6s

  [13799/21087] intraday_2711.csv.gz  in=373,366,225 out=113,089,395 elapsed=168.6s

  [13800/21087] intraday_2713.csv.gz  in=373,377,557 out=113,089,395 elapsed=168.6s

  [13801/21087] intraday_2712.csv.gz  in=373,404,560 out=113,089,395 elapsed=168.6s

  [13802/21087] intraday_2714.csv.gz  in=373,414,260 out=113,089,395 elapsed=168.6s

  [13803/21087] intraday_2715.csv.gz  in=373,425,439 out=113,089,395 elapsed=168.6s

  [13804/21087] intraday_2716.csv.gz  in=373,435,383 out=113,089,395 elapsed=168.6s

  [13805/21087] intraday_2718.csv.gz  in=373,445,774 out=113,089,395 elapsed=168.6s

  [13806/21087] intraday_2717.csv.gz  in=373,460,397 out=113,089,395 elapsed=168.6s

  [13807/21087] intraday_2719.csv.gz  in=373,472,934 out=113,089,395 elapsed=168.7s

  [13808/21087] intraday_2720.csv.gz  in=373,484,877 out=113,089,395 elapsed=168.7s

  [13809/21087] intraday_2721.csv.gz  in=373,493,793 out=113,089,395 elapsed=168.7s

  [13810/21087] intraday_2722.csv.gz  in=373,506,197 out=113,089,395 elapsed=168.7s

  [13811/21087] intraday_2723.csv.gz  in=373,517,868 out=113,089,395 elapsed=168.7s

  [13812/21087] intraday_2724.csv.gz  in=373,532,198 out=113,089,395 elapsed=168.7s

  [13813/21087] intraday_2725.csv.gz  in=373,543,236 out=113,089,395 elapsed=168.7s

  [13814/21087] intraday_2726.csv.gz  in=373,554,644 out=113,089,395 elapsed=168.7s

  [13815/21087] intraday_2727.csv.gz  in=373,564,056 out=113,089,395 elapsed=168.7s

  [13816/21087] intraday_2728.csv.gz  in=373,575,796 out=113,089,395 elapsed=168.7s

  [13817/21087] intraday_2730.csv.gz  in=373,585,402 out=113,089,395 elapsed=168.7s

  [13818/21087] intraday_2729.csv.gz  in=373,599,609 out=113,089,395 elapsed=168.7s

  [13819/21087] intraday_2731.csv.gz  in=373,612,990 out=113,089,395 elapsed=168.8s

  [13820/21087] intraday_2732.csv.gz  in=373,625,599 out=113,089,395 elapsed=168.8s

  [13821/21087] intraday_2733.csv.gz  in=373,634,830 out=113,089,395 elapsed=168.8s

  [13822/21087] intraday_2734.csv.gz  in=373,658,047 out=113,089,395 elapsed=168.8s

  [13823/21087] intraday_2735.csv.gz  in=373,669,266 out=113,089,395 elapsed=168.8s

  [13824/21087] intraday_2737.csv.gz  in=373,678,974 out=113,089,395 elapsed=168.8s

  [13825/21087] intraday_2736.csv.gz  in=373,691,090 out=113,089,395 elapsed=168.8s

  [13826/21087] intraday_2738.csv.gz  in=373,701,664 out=113,089,395 elapsed=168.8s

  [13827/21087] intraday_2739.csv.gz  in=373,712,741 out=113,089,395 elapsed=168.8s

  [13828/21087] intraday_2740.csv.gz  in=373,723,794 out=113,089,395 elapsed=168.8s

  [13829/21087] intraday_2741.csv.gz  in=373,735,461 out=113,089,395 elapsed=168.8s

  [13830/21087] intraday_2742.csv.gz  in=373,746,895 out=113,089,395 elapsed=168.8s

  [13831/21087] intraday_2743.csv.gz  in=373,758,573 out=113,089,395 elapsed=168.8s

  [13832/21087] intraday_2745.csv.gz  in=373,768,941 out=113,089,395 elapsed=168.9s

  [13833/21087] intraday_2744.csv.gz  in=373,779,157 out=113,089,395 elapsed=168.9s

  [13834/21087] intraday_2746.csv.gz  in=373,792,002 out=113,089,395 elapsed=168.9s

  [13835/21087] intraday_2747.csv.gz  in=373,806,684 out=113,089,395 elapsed=168.9s

  [13836/21087] intraday_2748.csv.gz  in=373,817,699 out=113,089,395 elapsed=168.9s

  [13837/21087] intraday_2749.csv.gz  in=373,826,490 out=113,089,395 elapsed=168.9s

  [13838/21087] intraday_2750.csv.gz  in=373,836,896 out=113,089,395 elapsed=168.9s

  [13839/21087] intraday_2751.csv.gz  in=373,848,691 out=113,089,395 elapsed=168.9s

  [13840/21087] intraday_2752.csv.gz  in=373,860,696 out=113,089,395 elapsed=168.9s

  [13841/21087] intraday_2753.csv.gz  in=373,874,328 out=113,089,395 elapsed=168.9s

  [13842/21087] intraday_2754.csv.gz  in=373,885,796 out=113,089,395 elapsed=168.9s

  [13843/21087] intraday_2755.csv.gz  in=373,898,374 out=113,089,395 elapsed=168.9s

  [13844/21087] intraday_2756.csv.gz  in=373,910,424 out=113,089,395 elapsed=169.0s

  [13845/21087] intraday_2757.csv.gz  in=373,923,363 out=113,089,395 elapsed=169.0s

  [13846/21087] intraday_2758.csv.gz  in=373,935,150 out=113,089,395 elapsed=169.0s

  [13847/21087] intraday_2759.csv.gz  in=373,946,750 out=113,089,395 elapsed=169.0s

  [13848/21087] intraday_2760.csv.gz  in=373,958,915 out=113,089,395 elapsed=169.0s

  [13849/21087] intraday_2761.csv.gz  in=373,970,017 out=113,089,395 elapsed=169.0s

  [13850/21087] intraday_2762.csv.gz  in=373,981,865 out=113,089,395 elapsed=169.0s

  [13851/21087] intraday_2763.csv.gz  in=373,993,556 out=113,089,395 elapsed=169.0s

  [13852/21087] intraday_2764.csv.gz  in=374,003,500 out=113,089,395 elapsed=169.0s

  [13853/21087] intraday_2765.csv.gz  in=374,015,558 out=113,089,395 elapsed=169.0s

  [13854/21087] intraday_2766.csv.gz  in=374,026,106 out=113,089,395 elapsed=169.0s

  [13855/21087] intraday_2767.csv.gz  in=374,037,556 out=113,089,395 elapsed=169.0s

  [13856/21087] intraday_2768.csv.gz  in=374,051,105 out=113,089,395 elapsed=169.0s

  [13857/21087] intraday_2769.csv.gz  in=374,060,464 out=113,089,395 elapsed=169.0s

  [13858/21087] intraday_2770.csv.gz  in=374,076,110 out=113,089,395 elapsed=169.1s

  [13859/21087] intraday_2771.csv.gz  in=374,090,529 out=113,089,395 elapsed=169.1s

  [13860/21087] intraday_2772.csv.gz  in=374,104,343 out=113,089,395 elapsed=169.1s

  [13861/21087] intraday_2773.csv.gz  in=374,116,906 out=113,089,395 elapsed=169.1s

  [13862/21087] intraday_2774.csv.gz  in=374,129,052 out=113,089,395 elapsed=169.1s

  [13863/21087] intraday_2775.csv.gz  in=374,140,835 out=113,089,395 elapsed=169.1s

  [13864/21087] intraday_2776.csv.gz  in=374,153,546 out=113,089,395 elapsed=169.1s

  [13865/21087] intraday_2778.csv.gz  in=374,164,491 out=113,089,395 elapsed=169.1s

  [13866/21087] intraday_2777.csv.gz  in=374,185,933 out=113,089,395 elapsed=169.1s

  [13867/21087] intraday_2779.csv.gz  in=374,198,876 out=113,089,395 elapsed=169.1s

  [13868/21087] intraday_2780.csv.gz  in=374,214,385 out=113,089,395 elapsed=169.1s

  [13869/21087] intraday_2781.csv.gz  in=374,226,426 out=113,089,395 elapsed=169.1s

  [13870/21087] intraday_2782.csv.gz  in=374,239,334 out=113,089,395 elapsed=169.2s

  [13871/21087] intraday_2783.csv.gz  in=374,250,676 out=113,089,395 elapsed=169.2s

  [13872/21087] intraday_2784.csv.gz  in=374,262,276 out=113,089,395 elapsed=169.2s

  [13873/21087] intraday_2787.csv.gz  in=374,274,509 out=113,089,395 elapsed=169.2s

  [13874/21087] intraday_2785.csv.gz  in=374,286,153 out=113,089,395 elapsed=169.2s

  [13875/21087] intraday_2786.csv.gz  in=374,299,433 out=113,089,395 elapsed=169.2s

  [13876/21087] intraday_2789.csv.gz  in=374,309,952 out=113,089,395 elapsed=169.2s

  [13877/21087] intraday_2788.csv.gz  in=374,325,824 out=113,089,395 elapsed=169.2s

  [13878/21087] intraday_2790.csv.gz  in=374,338,261 out=113,089,395 elapsed=169.2s

  [13879/21087] intraday_2791.csv.gz  in=374,350,255 out=113,089,395 elapsed=169.2s

  [13880/21087] intraday_2792.csv.gz  in=374,363,184 out=113,089,395 elapsed=169.3s

  [13881/21087] intraday_2793.csv.gz  in=374,374,390 out=113,089,395 elapsed=169.3s

  [13882/21087] intraday_2795.csv.gz  in=374,391,194 out=113,089,395 elapsed=169.3s

  [13883/21087] intraday_2794.csv.gz  in=374,406,329 out=113,089,395 elapsed=169.3s

  [13884/21087] intraday_2796.csv.gz  in=374,419,435 out=113,089,395 elapsed=169.3s

  [13885/21087] intraday_2798.csv.gz  in=374,430,402 out=113,089,395 elapsed=169.3s

  [13886/21087] intraday_2797.csv.gz  in=374,443,948 out=113,089,395 elapsed=169.3s

  [13887/21087] intraday_2799.csv.gz  in=374,454,027 out=113,089,395 elapsed=169.3s

  [13888/21087] intraday_2800.csv.gz  in=374,465,876 out=113,089,395 elapsed=169.3s

  [13889/21087] intraday_2802.csv.gz  in=374,473,817 out=113,089,395 elapsed=169.3s

  [13890/21087] intraday_2801.csv.gz  in=374,485,872 out=113,089,395 elapsed=169.3s

  [13891/21087] intraday_2803.csv.gz  in=374,494,180 out=113,089,395 elapsed=169.3s

  [13892/21087] intraday_2804.csv.gz  in=374,505,123 out=113,089,395 elapsed=169.4s

  [13893/21087] intraday_2805.csv.gz  in=374,507,386 out=113,089,395 elapsed=169.4s

  [13894/21087] intraday_2806.csv.gz  in=374,522,955 out=113,089,395 elapsed=169.4s

  [13895/21087] intraday_2807.csv.gz  in=374,537,821 out=113,089,395 elapsed=169.4s

  [13896/21087] intraday_2808.csv.gz  in=374,550,955 out=113,089,395 elapsed=169.4s

  [13897/21087] intraday_2809.csv.gz  in=374,561,736 out=113,089,395 elapsed=169.4s

  [13898/21087] intraday_2810.csv.gz  in=374,576,555 out=113,089,395 elapsed=169.4s

  [13899/21087] intraday_2813.csv.gz  in=374,588,587 out=113,089,395 elapsed=169.4s

  [13900/21087] intraday_2812.csv.gz  in=374,601,171 out=113,089,395 elapsed=169.4s

  [13901/21087] intraday_2811.csv.gz  in=374,614,908 out=113,089,395 elapsed=169.4s

  [13902/21087] intraday_2816.csv.gz  in=374,623,888 out=113,089,395 elapsed=169.5s

  [13903/21087] intraday_2814.csv.gz  in=374,637,909 out=113,089,395 elapsed=169.5s

  [13904/21087] intraday_2815.csv.gz  in=374,651,862 out=113,089,395 elapsed=169.5s

  [13905/21087] intraday_2817.csv.gz  in=374,665,000 out=113,089,395 elapsed=169.5s

  [13906/21087] intraday_2818.csv.gz  in=374,677,287 out=113,089,395 elapsed=169.5s

  [13907/21087] intraday_2819.csv.gz  in=374,688,329 out=113,089,395 elapsed=169.5s

  [13908/21087] intraday_2820.csv.gz  in=374,699,351 out=113,089,395 elapsed=169.5s

  [13909/21087] intraday_2821.csv.gz  in=374,710,492 out=113,089,395 elapsed=169.5s

  [13910/21087] intraday_2822.csv.gz  in=374,723,373 out=113,089,395 elapsed=169.5s

  [13911/21087] intraday_2823.csv.gz  in=374,735,673 out=113,089,395 elapsed=169.5s

  [13912/21087] intraday_2824.csv.gz  in=374,746,430 out=113,089,395 elapsed=169.5s

  [13913/21087] intraday_2825.csv.gz  in=374,759,275 out=113,089,395 elapsed=169.5s

  [13914/21087] intraday_2826.csv.gz  in=374,772,128 out=113,089,395 elapsed=169.5s

  [13915/21087] intraday_2827.csv.gz  in=374,784,040 out=113,089,395 elapsed=169.6s

  [13916/21087] intraday_2828.csv.gz  in=374,796,567 out=113,089,395 elapsed=169.6s

  [13917/21087] intraday_2829.csv.gz  in=374,809,469 out=113,089,395 elapsed=169.6s

  [13918/21087] intraday_2830.csv.gz  in=374,830,641 out=113,089,395 elapsed=169.6s

  [13919/21087] intraday_2831.csv.gz  in=374,840,421 out=113,089,395 elapsed=169.6s

  [13920/21087] intraday_2832.csv.gz  in=374,852,330 out=113,089,395 elapsed=169.6s

  [13921/21087] intraday_2833.csv.gz  in=374,864,557 out=113,089,395 elapsed=169.6s

  [13922/21087] intraday_2835.csv.gz  in=374,878,749 out=113,089,395 elapsed=169.6s

  [13923/21087] intraday_2834.csv.gz  in=374,897,741 out=113,089,395 elapsed=169.6s

  [13924/21087] intraday_2836.csv.gz  in=374,911,195 out=113,089,395 elapsed=169.6s

  [13925/21087] intraday_2837.csv.gz  in=374,924,522 out=113,089,395 elapsed=169.6s

  [13926/21087] intraday_2838.csv.gz  in=374,937,367 out=113,089,395 elapsed=169.6s

  [13927/21087] intraday_2839.csv.gz  in=374,950,404 out=113,089,395 elapsed=169.7s

  [13928/21087] intraday_2841.csv.gz  in=374,963,095 out=113,089,395 elapsed=169.7s

  [13929/21087] intraday_2840.csv.gz  in=374,992,275 out=113,089,395 elapsed=169.7s

  [13930/21087] intraday_2842.csv.gz  in=375,002,595 out=113,089,395 elapsed=169.7s

  [13931/21087] intraday_2843.csv.gz  in=375,013,116 out=113,089,395 elapsed=169.7s

  [13932/21087] intraday_2844.csv.gz  in=375,024,084 out=113,089,395 elapsed=169.7s

  [13933/21087] intraday_2845.csv.gz  in=375,034,891 out=113,089,395 elapsed=169.7s

  [13934/21087] intraday_2846.csv.gz  in=375,049,097 out=113,089,395 elapsed=169.7s

  [13935/21087] intraday_2847.csv.gz  in=375,062,594 out=113,089,395 elapsed=169.7s

  [13936/21087] intraday_2848.csv.gz  in=375,074,569 out=113,089,395 elapsed=169.7s

  [13937/21087] intraday_2849.csv.gz  in=375,088,488 out=113,089,395 elapsed=169.7s

  [13938/21087] intraday_2850.csv.gz  in=375,115,889 out=113,089,395 elapsed=169.7s

  [13939/21087] intraday_2851.csv.gz  in=375,132,493 out=113,089,395 elapsed=169.7s

  [13940/21087] intraday_2852.csv.gz  in=375,143,556 out=113,089,395 elapsed=169.7s

  [13941/21087] intraday_2853.csv.gz  in=375,154,939 out=113,089,395 elapsed=169.8s

  [13942/21087] intraday_2854.csv.gz  in=375,167,199 out=113,089,395 elapsed=169.8s

  [13943/21087] intraday_2855.csv.gz  in=375,177,821 out=113,089,395 elapsed=169.8s

  [13944/21087] intraday_2856.csv.gz  in=375,189,887 out=113,089,395 elapsed=169.8s

  [13945/21087] intraday_2857.csv.gz  in=375,200,500 out=113,089,395 elapsed=169.8s

  [13946/21087] intraday_2858.csv.gz  in=375,219,932 out=113,089,395 elapsed=169.8s

  [13947/21087] intraday_2859.csv.gz  in=375,231,116 out=113,089,395 elapsed=169.8s

  [13948/21087] intraday_2860.csv.gz  in=375,243,748 out=113,089,395 elapsed=169.8s

  [13949/21087] intraday_2862.csv.gz  in=375,253,592 out=113,089,395 elapsed=169.8s

  [13950/21087] intraday_2861.csv.gz  in=375,265,505 out=113,089,395 elapsed=169.8s

  [13951/21087] intraday_2863.csv.gz  in=375,278,209 out=113,089,395 elapsed=169.8s

  [13952/21087] intraday_2864.csv.gz  in=375,290,832 out=113,089,395 elapsed=169.9s

  [13953/21087] intraday_2866.csv.gz  in=375,303,295 out=113,089,395 elapsed=169.9s

  [13954/21087] intraday_2865.csv.gz  in=375,316,274 out=113,089,395 elapsed=169.9s

  [13955/21087] intraday_2867.csv.gz  in=375,327,667 out=113,089,395 elapsed=169.9s

  [13956/21087] intraday_2868.csv.gz  in=375,337,239 out=113,089,395 elapsed=169.9s

  [13957/21087] intraday_2869.csv.gz  in=375,349,721 out=113,089,395 elapsed=169.9s

  [13958/21087] intraday_2870.csv.gz  in=375,364,990 out=113,089,395 elapsed=169.9s

  [13959/21087] intraday_2871.csv.gz  in=375,375,232 out=113,089,395 elapsed=169.9s

  [13960/21087] intraday_2874.csv.gz  in=375,385,133 out=113,089,395 elapsed=169.9s

  [13961/21087] intraday_2872.csv.gz  in=375,399,104 out=113,089,395 elapsed=169.9s

  [13962/21087] intraday_2873.csv.gz  in=375,414,440 out=113,089,395 elapsed=169.9s

  [13963/21087] intraday_2875.csv.gz  in=375,426,758 out=113,089,395 elapsed=169.9s

  [13964/21087] intraday_2876.csv.gz  in=375,439,940 out=113,089,395 elapsed=169.9s

  [13965/21087] intraday_2878.csv.gz  in=375,450,498 out=113,089,395 elapsed=170.0s

  [13966/21087] intraday_2877.csv.gz  in=375,463,105 out=113,089,395 elapsed=170.0s

  [13967/21087] intraday_2879.csv.gz  in=375,474,335 out=113,089,395 elapsed=170.0s

  [13968/21087] intraday_2880.csv.gz  in=375,491,057 out=113,089,395 elapsed=170.0s

  [13969/21087] intraday_2881.csv.gz  in=375,503,234 out=113,089,395 elapsed=170.0s

  [13970/21087] intraday_2882.csv.gz  in=375,515,243 out=113,089,395 elapsed=170.0s

  [13971/21087] intraday_2883.csv.gz  in=375,527,261 out=113,089,395 elapsed=170.0s

  [13972/21087] intraday_2884.csv.gz  in=375,540,220 out=113,089,395 elapsed=170.0s

  [13973/21087] intraday_2885.csv.gz  in=375,550,791 out=113,089,395 elapsed=170.0s

  [13974/21087] intraday_2886.csv.gz  in=375,561,465 out=113,089,395 elapsed=170.0s

  [13975/21087] intraday_2887.csv.gz  in=375,573,972 out=113,089,395 elapsed=170.0s

  [13976/21087] intraday_2888.csv.gz  in=375,590,718 out=113,089,395 elapsed=170.0s

  [13977/21087] intraday_2889.csv.gz  in=375,601,224 out=113,089,395 elapsed=170.0s

  [13978/21087] intraday_2890.csv.gz  in=375,611,861 out=113,089,395 elapsed=170.1s

  [13979/21087] intraday_2891.csv.gz  in=375,622,342 out=113,089,395 elapsed=170.1s

  [13980/21087] intraday_2892.csv.gz  in=375,634,860 out=113,089,395 elapsed=170.1s

  [13981/21087] intraday_2893.csv.gz  in=375,646,195 out=113,089,395 elapsed=170.1s

  [13982/21087] intraday_2894.csv.gz  in=375,661,747 out=113,089,395 elapsed=170.1s

  [13983/21087] intraday_2895.csv.gz  in=375,673,003 out=113,089,395 elapsed=170.1s

  [13984/21087] intraday_2896.csv.gz  in=375,686,213 out=113,089,395 elapsed=170.1s

  [13985/21087] intraday_2897.csv.gz  in=375,699,658 out=113,089,395 elapsed=170.1s

  [13986/21087] intraday_2899.csv.gz  in=375,711,760 out=113,089,395 elapsed=170.1s

  [13987/21087] intraday_2900.csv.gz  in=375,724,166 out=113,089,395 elapsed=170.1s

  [13988/21087] intraday_2898.csv.gz  in=375,751,359 out=113,089,395 elapsed=170.1s

  [13989/21087] intraday_2902.csv.gz  in=375,766,100 out=113,089,395 elapsed=170.1s

  [13990/21087] intraday_2901.csv.gz  in=375,790,409 out=113,089,395 elapsed=170.1s

  [13991/21087] intraday_2903.csv.gz  in=375,803,115 out=113,089,395 elapsed=170.2s

  [13992/21087] intraday_2904.csv.gz  in=375,817,128 out=113,089,395 elapsed=170.2s

  [13993/21087] intraday_2906.csv.gz  in=375,829,592 out=113,089,395 elapsed=170.2s

  [13994/21087] intraday_2905.csv.gz  in=375,840,399 out=113,089,395 elapsed=170.2s

  [13995/21087] intraday_2907.csv.gz  in=375,852,281 out=113,089,395 elapsed=170.2s

  [13996/21087] intraday_2908.csv.gz  in=375,877,005 out=113,089,395 elapsed=170.2s

  [13997/21087] intraday_2909.csv.gz  in=375,890,263 out=113,089,395 elapsed=170.2s

  [13998/21087] intraday_2910.csv.gz  in=375,900,926 out=113,089,395 elapsed=170.2s

  [13999/21087] intraday_2911.csv.gz  in=375,912,147 out=113,089,395 elapsed=170.2s

  [14000/21087] intraday_2912.csv.gz  in=375,926,307 out=113,089,395 elapsed=170.2s

  [14001/21087] intraday_2914.csv.gz  in=375,939,140 out=113,089,395 elapsed=170.2s

  [14002/21087] intraday_2913.csv.gz  in=375,954,300 out=113,089,395 elapsed=170.2s

  [14003/21087] intraday_2915.csv.gz  in=375,966,971 out=113,089,395 elapsed=170.2s

  [14004/21087] intraday_2916.csv.gz  in=375,980,959 out=113,089,395 elapsed=170.3s

  [14005/21087] intraday_2917.csv.gz  in=375,994,316 out=113,089,395 elapsed=170.3s

  [14006/21087] intraday_2918.csv.gz  in=376,007,624 out=113,089,395 elapsed=170.3s

  [14007/21087] intraday_2919.csv.gz  in=376,019,862 out=113,089,395 elapsed=170.3s

  [14008/21087] intraday_2920.csv.gz  in=376,034,298 out=113,089,395 elapsed=170.3s

  [14009/21087] intraday_2922.csv.gz  in=376,047,083 out=113,089,395 elapsed=170.3s

  [14010/21087] intraday_2921.csv.gz  in=376,068,481 out=113,089,395 elapsed=170.3s

  [14011/21087] intraday_2924.csv.gz  in=376,080,904 out=113,089,395 elapsed=170.3s

  [14012/21087] intraday_2923.csv.gz  in=376,094,032 out=113,089,395 elapsed=170.3s

  [14013/21087] intraday_2925.csv.gz  in=376,106,528 out=113,089,395 elapsed=170.3s

  [14014/21087] intraday_2927.csv.gz  in=376,120,370 out=113,089,395 elapsed=170.3s

  [14015/21087] intraday_2926.csv.gz  in=376,131,706 out=113,089,395 elapsed=170.3s

  [14016/21087] intraday_2928.csv.gz  in=376,144,715 out=113,089,395 elapsed=170.3s

  [14017/21087] intraday_2929.csv.gz  in=376,161,364 out=113,089,395 elapsed=170.4s

  [14018/21087] intraday_2930.csv.gz  in=376,173,742 out=113,089,395 elapsed=170.4s

  [14019/21087] intraday_2931.csv.gz  in=376,187,607 out=113,089,395 elapsed=170.4s

  [14020/21087] intraday_2932.csv.gz  in=376,201,293 out=113,089,395 elapsed=170.4s

  [14021/21087] intraday_2933.csv.gz  in=376,213,738 out=113,089,395 elapsed=170.4s

  [14022/21087] intraday_2934.csv.gz  in=376,226,623 out=113,089,395 elapsed=170.4s

  [14023/21087] intraday_2935.csv.gz  in=376,248,734 out=113,089,395 elapsed=170.4s

  [14024/21087] intraday_2936.csv.gz  in=376,263,862 out=113,089,395 elapsed=170.4s

  [14025/21087] intraday_2937.csv.gz  in=376,277,282 out=113,089,395 elapsed=170.4s

  [14026/21087] intraday_2938.csv.gz  in=376,291,809 out=113,089,395 elapsed=170.4s

  [14027/21087] intraday_2939.csv.gz  in=376,302,815 out=113,089,395 elapsed=170.4s

  [14028/21087] intraday_2940.csv.gz  in=376,314,041 out=113,089,395 elapsed=170.4s

  [14029/21087] intraday_2941.csv.gz  in=376,326,983 out=113,089,395 elapsed=170.5s

  [14030/21087] intraday_2942.csv.gz  in=376,338,911 out=113,089,395 elapsed=170.5s

  [14031/21087] intraday_2943.csv.gz  in=376,349,858 out=113,089,395 elapsed=170.5s

  [14032/21087] intraday_2944.csv.gz  in=376,357,317 out=113,089,395 elapsed=170.5s

  [14033/21087] intraday_2945.csv.gz  in=376,366,814 out=113,089,395 elapsed=170.5s

  [14034/21087] intraday_2946.csv.gz  in=376,372,965 out=113,089,395 elapsed=170.5s

  [14035/21087] intraday_2947.csv.gz  in=376,389,719 out=113,089,395 elapsed=170.5s

  [14036/21087] intraday_2948.csv.gz  in=376,404,849 out=113,089,395 elapsed=170.5s

  [14037/21087] intraday_2949.csv.gz  in=376,418,788 out=113,089,395 elapsed=170.5s

  [14038/21087] intraday_2950.csv.gz  in=376,429,829 out=113,089,395 elapsed=170.5s

  [14039/21087] intraday_2951.csv.gz  in=376,444,911 out=113,089,395 elapsed=170.5s

  [14040/21087] intraday_2952.csv.gz  in=376,459,795 out=113,089,395 elapsed=170.5s

  [14041/21087] intraday_2954.csv.gz  in=376,473,023 out=113,089,395 elapsed=170.6s

  [14042/21087] intraday_2953.csv.gz  in=376,486,161 out=113,089,395 elapsed=170.6s

  [14043/21087] intraday_2955.csv.gz  in=376,501,031 out=113,089,395 elapsed=170.6s

  [14044/21087] intraday_2956.csv.gz  in=376,515,601 out=113,089,395 elapsed=170.6s

  [14045/21087] intraday_2957.csv.gz  in=376,525,578 out=113,089,395 elapsed=170.6s

  [14046/21087] intraday_2959.csv.gz  in=376,539,267 out=113,089,395 elapsed=170.6s

  [14047/21087] intraday_2958.csv.gz  in=376,553,242 out=113,089,395 elapsed=170.6s

  [14048/21087] intraday_2960.csv.gz  in=376,565,713 out=113,089,395 elapsed=170.6s

  [14049/21087] intraday_2961.csv.gz  in=376,577,156 out=113,089,395 elapsed=170.6s

  [14050/21087] intraday_2962.csv.gz  in=376,588,549 out=113,089,395 elapsed=170.6s

  [14051/21087] intraday_2963.csv.gz  in=376,602,648 out=113,089,395 elapsed=170.6s

  [14052/21087] intraday_2964.csv.gz  in=376,615,606 out=113,089,395 elapsed=170.6s

  [14053/21087] intraday_2965.csv.gz  in=376,626,801 out=113,089,395 elapsed=170.6s

  [14054/21087] intraday_2966.csv.gz  in=376,639,850 out=113,089,395 elapsed=170.7s

  [14055/21087] intraday_2967.csv.gz  in=376,653,892 out=113,089,395 elapsed=170.7s

  [14056/21087] intraday_2968.csv.gz  in=376,666,135 out=113,089,395 elapsed=170.7s

  [14057/21087] intraday_2969.csv.gz  in=376,678,827 out=113,089,395 elapsed=170.7s

  [14058/21087] intraday_2970.csv.gz  in=376,697,064 out=113,089,395 elapsed=170.7s

  [14059/21087] intraday_2971.csv.gz  in=376,709,565 out=113,089,395 elapsed=170.7s

  [14060/21087] intraday_2972.csv.gz  in=376,720,123 out=113,089,395 elapsed=170.7s

  [14061/21087] intraday_2973.csv.gz  in=376,733,214 out=113,089,395 elapsed=170.7s

  [14062/21087] intraday_2974.csv.gz  in=376,745,935 out=113,089,395 elapsed=170.7s

  [14063/21087] intraday_2975.csv.gz  in=376,759,524 out=113,089,395 elapsed=170.7s

  [14064/21087] intraday_2976.csv.gz  in=376,775,400 out=113,089,395 elapsed=170.7s

  [14065/21087] intraday_2977.csv.gz  in=376,789,484 out=113,089,395 elapsed=170.7s

  [14066/21087] intraday_2978.csv.gz  in=376,803,146 out=113,089,395 elapsed=170.8s

  [14067/21087] intraday_2979.csv.gz  in=376,818,104 out=113,089,395 elapsed=170.8s

  [14068/21087] intraday_2981.csv.gz  in=376,833,989 out=113,089,395 elapsed=170.8s

  [14069/21087] intraday_2980.csv.gz  in=376,864,947 out=113,089,395 elapsed=170.8s

  [14070/21087] intraday_2982.csv.gz  in=376,882,622 out=113,089,395 elapsed=170.8s

  [14071/21087] intraday_2983.csv.gz  in=376,893,204 out=113,089,395 elapsed=170.8s

  [14072/21087] intraday_2984.csv.gz  in=376,906,054 out=113,089,395 elapsed=170.8s

  [14073/21087] intraday_2985.csv.gz  in=376,918,353 out=113,089,395 elapsed=170.8s

  [14074/21087] intraday_2986.csv.gz  in=376,930,823 out=113,089,395 elapsed=170.8s

  [14075/21087] intraday_2987.csv.gz  in=376,945,354 out=113,089,395 elapsed=170.8s

  [14076/21087] intraday_2988.csv.gz  in=376,959,447 out=113,089,395 elapsed=170.8s

  [14077/21087] intraday_2989.csv.gz  in=376,971,620 out=113,089,395 elapsed=170.8s

  [14078/21087] intraday_2990.csv.gz  in=376,986,163 out=113,089,395 elapsed=170.9s

  [14079/21087] intraday_2991.csv.gz  in=376,997,852 out=113,089,395 elapsed=170.9s

  [14080/21087] intraday_2992.csv.gz  in=377,011,180 out=113,089,395 elapsed=170.9s

  [14081/21087] intraday_2993.csv.gz  in=377,023,408 out=113,089,395 elapsed=170.9s

  [14082/21087] intraday_2994.csv.gz  in=377,035,532 out=113,089,395 elapsed=170.9s

  [14083/21087] intraday_2996.csv.gz  in=377,047,139 out=113,089,395 elapsed=170.9s

  [14084/21087] intraday_2995.csv.gz  in=377,059,719 out=113,089,395 elapsed=170.9s

  [14085/21087] intraday_2997.csv.gz  in=377,072,725 out=113,089,395 elapsed=170.9s

  [14086/21087] intraday_2998.csv.gz  in=377,085,005 out=113,089,395 elapsed=170.9s

  [14087/21087] intraday_2999.csv.gz  in=377,097,587 out=113,089,395 elapsed=170.9s

  [14088/21087] intraday_3000.csv.gz  in=377,109,658 out=113,089,395 elapsed=170.9s

  [14089/21087] intraday_3001.csv.gz  in=377,123,534 out=113,089,395 elapsed=170.9s

  [14090/21087] intraday_3002.csv.gz  in=377,136,073 out=113,089,395 elapsed=170.9s

  [14091/21087] intraday_3003.csv.gz  in=377,147,052 out=113,089,395 elapsed=170.9s

  [14092/21087] intraday_3004.csv.gz  in=377,161,076 out=113,089,395 elapsed=171.0s

  [14093/21087] intraday_3005.csv.gz  in=377,175,046 out=113,089,395 elapsed=171.0s

  [14094/21087] intraday_3006.csv.gz  in=377,187,819 out=113,089,395 elapsed=171.0s

  [14095/21087] intraday_3007.csv.gz  in=377,200,501 out=113,089,395 elapsed=171.0s

  [14096/21087] intraday_3008.csv.gz  in=377,212,836 out=113,089,395 elapsed=171.0s

  [14097/21087] intraday_3009.csv.gz  in=377,222,964 out=113,089,395 elapsed=171.0s

  [14098/21087] intraday_3010.csv.gz  in=377,236,011 out=113,089,395 elapsed=171.0s

  [14099/21087] intraday_3011.csv.gz  in=377,252,548 out=113,089,395 elapsed=171.0s

  [14100/21087] intraday_3012.csv.gz  in=377,263,545 out=113,089,395 elapsed=171.0s

  [14101/21087] intraday_3013.csv.gz  in=377,277,286 out=113,089,395 elapsed=171.0s

  [14102/21087] intraday_3014.csv.gz  in=377,292,100 out=113,089,395 elapsed=171.0s

  [14103/21087] intraday_3015.csv.gz  in=377,301,468 out=113,089,395 elapsed=171.0s

  [14104/21087] intraday_3016.csv.gz  in=377,315,296 out=113,089,395 elapsed=171.1s

  [14105/21087] intraday_3017.csv.gz  in=377,328,681 out=113,089,395 elapsed=171.1s

  [14106/21087] intraday_3018.csv.gz  in=377,342,880 out=113,089,395 elapsed=171.1s

  [14107/21087] intraday_3019.csv.gz  in=377,353,750 out=113,089,395 elapsed=171.1s

  [14108/21087] intraday_3020.csv.gz  in=377,365,263 out=113,089,395 elapsed=171.1s

  [14109/21087] intraday_3021.csv.gz  in=377,377,348 out=113,089,395 elapsed=171.1s

  [14110/21087] intraday_3022.csv.gz  in=377,390,340 out=113,089,395 elapsed=171.1s

  [14111/21087] intraday_3023.csv.gz  in=377,403,825 out=113,089,395 elapsed=171.1s

  [14112/21087] intraday_3025.csv.gz  in=377,417,774 out=113,089,395 elapsed=171.1s

  [14113/21087] intraday_3024.csv.gz  in=377,429,940 out=113,089,395 elapsed=171.1s

  [14114/21087] intraday_3026.csv.gz  in=377,440,749 out=113,089,395 elapsed=171.1s

  [14115/21087] intraday_3027.csv.gz  in=377,451,717 out=113,089,395 elapsed=171.1s

  [14116/21087] intraday_3029.csv.gz  in=377,469,094 out=113,089,395 elapsed=171.2s

  [14117/21087] intraday_3028.csv.gz  in=377,482,795 out=113,089,395 elapsed=171.2s

  [14118/21087] intraday_3030.csv.gz  in=377,493,913 out=113,089,395 elapsed=171.2s

  [14119/21087] intraday_3031.csv.gz  in=377,505,656 out=113,089,395 elapsed=171.2s

  [14120/21087] intraday_3032.csv.gz  in=377,516,214 out=113,089,395 elapsed=171.2s

  [14121/21087] intraday_3033.csv.gz  in=377,530,031 out=113,089,395 elapsed=171.2s

  [14122/21087] intraday_3034.csv.gz  in=377,542,341 out=113,089,395 elapsed=171.2s

  [14123/21087] intraday_3035.csv.gz  in=377,572,458 out=113,089,395 elapsed=171.2s

  [14124/21087] intraday_3036.csv.gz  in=377,596,119 out=113,089,395 elapsed=171.2s

  [14125/21087] intraday_3037.csv.gz  in=377,612,531 out=113,089,395 elapsed=171.2s

  [14126/21087] intraday_3038.csv.gz  in=377,626,071 out=113,089,395 elapsed=171.2s

  [14127/21087] intraday_3039.csv.gz  in=377,641,032 out=113,089,395 elapsed=171.2s

  [14128/21087] intraday_3041.csv.gz  in=377,654,359 out=113,089,395 elapsed=171.3s

  [14129/21087] intraday_3040.csv.gz  in=377,667,636 out=113,089,395 elapsed=171.3s

  [14130/21087] intraday_3042.csv.gz  in=377,682,449 out=113,089,395 elapsed=171.3s

  [14131/21087] intraday_3043.csv.gz  in=377,695,174 out=113,089,395 elapsed=171.3s

  [14132/21087] intraday_3044.csv.gz  in=377,708,223 out=113,089,395 elapsed=171.3s

  [14133/21087] intraday_3045.csv.gz  in=377,721,291 out=113,089,395 elapsed=171.3s

  [14134/21087] intraday_3046.csv.gz  in=377,734,106 out=113,089,395 elapsed=171.3s

  [14135/21087] intraday_3047.csv.gz  in=377,746,580 out=113,089,395 elapsed=171.3s

  [14136/21087] intraday_3048.csv.gz  in=377,759,630 out=113,089,395 elapsed=171.3s

  [14137/21087] intraday_3049.csv.gz  in=377,772,754 out=113,089,395 elapsed=171.3s

  [14138/21087] intraday_3050.csv.gz  in=377,786,332 out=113,089,395 elapsed=171.3s

  [14139/21087] intraday_3051.csv.gz  in=377,798,799 out=113,089,395 elapsed=171.3s

  [14140/21087] intraday_3052.csv.gz  in=377,810,926 out=113,089,395 elapsed=171.3s

  [14141/21087] intraday_3053.csv.gz  in=377,826,151 out=113,089,395 elapsed=171.4s

  [14142/21087] intraday_3054.csv.gz  in=377,841,506 out=113,089,395 elapsed=171.4s

  [14143/21087] intraday_3055.csv.gz  in=377,858,742 out=113,089,395 elapsed=171.4s

  [14144/21087] intraday_3056.csv.gz  in=377,871,959 out=113,089,395 elapsed=171.4s

  [14145/21087] intraday_3057.csv.gz  in=377,886,428 out=113,089,395 elapsed=171.4s

  [14146/21087] intraday_3058.csv.gz  in=377,900,603 out=113,089,395 elapsed=171.4s

  [14147/21087] intraday_3059.csv.gz  in=377,914,453 out=113,089,395 elapsed=171.4s

  [14148/21087] intraday_3060.csv.gz  in=377,927,998 out=113,089,395 elapsed=171.4s

  [14149/21087] intraday_3061.csv.gz  in=377,942,281 out=113,089,395 elapsed=171.4s

  [14150/21087] intraday_3062.csv.gz  in=377,959,183 out=113,089,395 elapsed=171.4s

  [14151/21087] intraday_3063.csv.gz  in=377,972,053 out=113,089,395 elapsed=171.4s

  [14152/21087] intraday_3064.csv.gz  in=377,986,877 out=113,089,395 elapsed=171.4s

  [14153/21087] intraday_3065.csv.gz  in=378,000,510 out=113,089,395 elapsed=171.4s

  [14154/21087] intraday_3066.csv.gz  in=378,014,111 out=113,089,395 elapsed=171.4s

  [14155/21087] intraday_3067.csv.gz  in=378,025,830 out=113,089,395 elapsed=171.5s

  [14156/21087] intraday_3068.csv.gz  in=378,038,964 out=113,089,395 elapsed=171.5s

  [14157/21087] intraday_3069.csv.gz  in=378,055,394 out=113,089,395 elapsed=171.5s

  [14158/21087] intraday_3070.csv.gz  in=378,071,288 out=113,089,395 elapsed=171.5s

  [14159/21087] intraday_3071.csv.gz  in=378,085,942 out=113,089,395 elapsed=171.5s

  [14160/21087] intraday_3072.csv.gz  in=378,099,574 out=113,089,395 elapsed=171.5s

  [14161/21087] intraday_3073.csv.gz  in=378,114,535 out=113,089,395 elapsed=171.5s

  [14162/21087] intraday_3074.csv.gz  in=378,129,099 out=113,089,395 elapsed=171.5s

  [14163/21087] intraday_3075.csv.gz  in=378,142,533 out=113,089,395 elapsed=171.5s

  [14164/21087] intraday_3076.csv.gz  in=378,157,216 out=113,089,395 elapsed=171.5s

  [14165/21087] intraday_3077.csv.gz  in=378,172,754 out=113,089,395 elapsed=171.5s

  [14166/21087] intraday_3078.csv.gz  in=378,187,842 out=113,089,395 elapsed=171.5s

  [14167/21087] intraday_3079.csv.gz  in=378,204,715 out=113,089,395 elapsed=171.6s

  [14168/21087] intraday_3080.csv.gz  in=378,217,666 out=113,089,395 elapsed=171.6s

  [14169/21087] intraday_3081.csv.gz  in=378,228,394 out=113,089,395 elapsed=171.6s

  [14170/21087] intraday_3082.csv.gz  in=378,241,848 out=113,089,395 elapsed=171.6s

  [14171/21087] intraday_3084.csv.gz  in=378,254,340 out=113,089,395 elapsed=171.6s

  [14172/21087] intraday_3083.csv.gz  in=378,266,552 out=113,089,395 elapsed=171.6s

  [14173/21087] intraday_3085.csv.gz  in=378,274,685 out=113,089,395 elapsed=171.6s

  [14174/21087] intraday_3086.csv.gz  in=378,285,360 out=113,089,395 elapsed=171.6s

  [14175/21087] intraday_3087.csv.gz  in=378,292,322 out=113,089,395 elapsed=171.6s

  [14176/21087] intraday_3088.csv.gz  in=378,306,649 out=113,089,395 elapsed=171.6s

  [14177/21087] intraday_3090.csv.gz  in=378,318,961 out=113,089,395 elapsed=171.6s

  [14178/21087] intraday_3089.csv.gz  in=378,333,194 out=113,089,395 elapsed=171.6s

  [14179/21087] intraday_3091.csv.gz  in=378,343,441 out=113,089,395 elapsed=171.6s

  [14180/21087] intraday_3092.csv.gz  in=378,360,138 out=113,089,395 elapsed=171.7s

  [14181/21087] intraday_3093.csv.gz  in=378,374,420 out=113,089,395 elapsed=171.7s

  [14182/21087] intraday_3094.csv.gz  in=378,386,908 out=113,089,395 elapsed=171.7s

  [14183/21087] intraday_3095.csv.gz  in=378,399,052 out=113,089,395 elapsed=171.7s

  [14184/21087] intraday_3096.csv.gz  in=378,412,434 out=113,089,395 elapsed=171.7s

  [14185/21087] intraday_3098.csv.gz  in=378,422,171 out=113,089,395 elapsed=171.7s

  [14186/21087] intraday_3097.csv.gz  in=378,435,527 out=113,089,395 elapsed=171.7s

  [14187/21087] intraday_3099.csv.gz  in=378,447,550 out=113,089,395 elapsed=171.7s

  [14188/21087] intraday_3100.csv.gz  in=378,460,039 out=113,089,395 elapsed=171.7s

  [14189/21087] intraday_3101.csv.gz  in=378,472,214 out=113,089,395 elapsed=171.7s

  [14190/21087] intraday_3102.csv.gz  in=378,483,315 out=113,089,395 elapsed=171.7s

  [14191/21087] intraday_3103.csv.gz  in=378,493,392 out=113,089,395 elapsed=171.7s

  [14192/21087] intraday_3104.csv.gz  in=378,506,686 out=113,089,395 elapsed=171.8s

  [14193/21087] intraday_3105.csv.gz  in=378,518,580 out=113,089,395 elapsed=171.8s

  [14194/21087] intraday_3106.csv.gz  in=378,529,072 out=113,089,395 elapsed=171.8s

  [14195/21087] intraday_3107.csv.gz  in=378,540,769 out=113,089,395 elapsed=171.8s

  [14196/21087] intraday_3108.csv.gz  in=378,553,917 out=113,089,395 elapsed=171.8s

  [14197/21087] intraday_3109.csv.gz  in=378,565,017 out=113,089,395 elapsed=171.8s

  [14198/21087] intraday_3110.csv.gz  in=378,577,838 out=113,089,395 elapsed=171.8s

  [14199/21087] intraday_3111.csv.gz  in=378,590,862 out=113,089,395 elapsed=171.8s

  [14200/21087] intraday_3113.csv.gz  in=378,600,869 out=113,089,395 elapsed=171.8s

  [14201/21087] intraday_3112.csv.gz  in=378,613,429 out=113,089,395 elapsed=171.8s

  [14202/21087] intraday_3114.csv.gz  in=378,625,351 out=113,089,395 elapsed=171.8s

  [14203/21087] intraday_3115.csv.gz  in=378,637,893 out=113,089,395 elapsed=171.8s

  [14204/21087] intraday_3117.csv.gz  in=378,652,148 out=113,089,395 elapsed=171.8s

  [14205/21087] intraday_3116.csv.gz  in=378,664,126 out=113,089,395 elapsed=171.8s

  [14206/21087] intraday_3118.csv.gz  in=378,677,461 out=113,089,395 elapsed=171.9s

  [14207/21087] intraday_3119.csv.gz  in=378,690,280 out=113,089,395 elapsed=171.9s

  [14208/21087] intraday_3120.csv.gz  in=378,702,138 out=113,089,395 elapsed=171.9s

  [14209/21087] intraday_3121.csv.gz  in=378,715,116 out=113,089,395 elapsed=171.9s

  [14210/21087] intraday_3122.csv.gz  in=378,727,286 out=113,089,395 elapsed=171.9s

  [14211/21087] intraday_3123.csv.gz  in=378,740,192 out=113,089,395 elapsed=171.9s

  [14212/21087] intraday_3124.csv.gz  in=378,750,685 out=113,089,395 elapsed=171.9s

  [14213/21087] intraday_3125.csv.gz  in=378,761,498 out=113,089,395 elapsed=171.9s

  [14214/21087] intraday_3126.csv.gz  in=378,771,952 out=113,089,395 elapsed=171.9s

  [14215/21087] intraday_3127.csv.gz  in=378,789,265 out=113,089,395 elapsed=171.9s

  [14216/21087] intraday_3128.csv.gz  in=378,802,646 out=113,089,395 elapsed=171.9s

  [14217/21087] intraday_3129.csv.gz  in=378,815,987 out=113,089,395 elapsed=171.9s

  [14218/21087] intraday_3130.csv.gz  in=378,827,475 out=113,089,395 elapsed=171.9s

  [14219/21087] intraday_3131.csv.gz  in=378,840,381 out=113,089,395 elapsed=172.0s

  [14220/21087] intraday_3132.csv.gz  in=378,851,295 out=113,089,395 elapsed=172.0s

  [14221/21087] intraday_3133.csv.gz  in=378,863,611 out=113,089,395 elapsed=172.0s

  [14222/21087] intraday_3134.csv.gz  in=378,875,474 out=113,089,395 elapsed=172.0s

  [14223/21087] intraday_3135.csv.gz  in=378,886,283 out=113,089,395 elapsed=172.0s

  [14224/21087] intraday_3136.csv.gz  in=378,898,420 out=113,089,395 elapsed=172.0s

  [14225/21087] intraday_3137.csv.gz  in=378,909,191 out=113,089,395 elapsed=172.0s

  [14226/21087] intraday_3138.csv.gz  in=378,921,370 out=113,089,395 elapsed=172.0s

  [14227/21087] intraday_3139.csv.gz  in=378,931,911 out=113,089,395 elapsed=172.0s

  [14228/21087] intraday_3141.csv.gz  in=378,941,899 out=113,089,395 elapsed=172.0s

  [14229/21087] intraday_3140.csv.gz  in=378,955,905 out=113,089,395 elapsed=172.0s

  [14230/21087] intraday_3142.csv.gz  in=378,968,949 out=113,089,395 elapsed=172.0s

  [14231/21087] intraday_3143.csv.gz  in=378,981,754 out=113,089,395 elapsed=172.0s

  [14232/21087] intraday_3144.csv.gz  in=378,992,686 out=113,089,395 elapsed=172.1s

  [14233/21087] intraday_3145.csv.gz  in=379,004,672 out=113,089,395 elapsed=172.1s

  [14234/21087] intraday_3146.csv.gz  in=379,016,719 out=113,089,395 elapsed=172.1s

  [14235/21087] intraday_3147.csv.gz  in=379,028,289 out=113,089,395 elapsed=172.1s

  [14236/21087] intraday_3148.csv.gz  in=379,039,879 out=113,089,395 elapsed=172.1s

  [14237/21087] intraday_3149.csv.gz  in=379,052,106 out=113,089,395 elapsed=172.1s

  [14238/21087] intraday_3150.csv.gz  in=379,061,714 out=113,089,395 elapsed=172.1s

  [14239/21087] intraday_3151.csv.gz  in=379,073,759 out=113,089,395 elapsed=172.1s

  [14240/21087] intraday_3153.csv.gz  in=379,084,850 out=113,089,395 elapsed=172.1s

  [14241/21087] intraday_3152.csv.gz  in=379,098,580 out=113,089,395 elapsed=172.1s

  [14242/21087] intraday_3154.csv.gz  in=379,112,259 out=113,089,395 elapsed=172.1s

  [14243/21087] intraday_3155.csv.gz  in=379,125,374 out=113,089,395 elapsed=172.1s

  [14244/21087] intraday_3156.csv.gz  in=379,133,810 out=113,089,395 elapsed=172.2s

  [14245/21087] intraday_3157.csv.gz  in=379,146,691 out=113,089,395 elapsed=172.2s

  [14246/21087] intraday_3159.csv.gz  in=379,158,565 out=113,089,395 elapsed=172.2s

  [14247/21087] intraday_3158.csv.gz  in=379,170,556 out=113,089,395 elapsed=172.2s

  [14248/21087] intraday_3160.csv.gz  in=379,181,453 out=113,089,395 elapsed=172.2s

  [14249/21087] intraday_3161.csv.gz  in=379,192,079 out=113,089,395 elapsed=172.2s

  [14250/21087] intraday_3162.csv.gz  in=379,202,592 out=113,089,395 elapsed=172.2s

  [14251/21087] intraday_3163.csv.gz  in=379,213,168 out=113,089,395 elapsed=172.2s

  [14252/21087] intraday_3165.csv.gz  in=379,224,632 out=113,089,395 elapsed=172.2s

  [14253/21087] intraday_3164.csv.gz  in=379,237,213 out=113,089,395 elapsed=172.2s

  [14254/21087] intraday_3166.csv.gz  in=379,249,528 out=113,089,395 elapsed=172.2s

  [14255/21087] intraday_3167.csv.gz  in=379,260,482 out=113,089,395 elapsed=172.2s

  [14256/21087] intraday_3168.csv.gz  in=379,270,782 out=113,089,395 elapsed=172.3s

  [14257/21087] intraday_3169.csv.gz  in=379,284,279 out=113,089,395 elapsed=172.3s

  [14258/21087] intraday_3171.csv.gz  in=379,293,582 out=113,089,395 elapsed=172.3s

  [14259/21087] intraday_3170.csv.gz  in=379,309,210 out=113,089,395 elapsed=172.3s

  [14260/21087] intraday_3173.csv.gz  in=379,318,932 out=113,089,395 elapsed=172.3s

  [14261/21087] intraday_3172.csv.gz  in=379,331,345 out=113,089,395 elapsed=172.3s

  [14262/21087] intraday_3174.csv.gz  in=379,347,042 out=113,089,395 elapsed=172.3s

  [14263/21087] intraday_3175.csv.gz  in=379,357,950 out=113,089,395 elapsed=172.3s

  [14264/21087] intraday_3176.csv.gz  in=379,372,263 out=113,089,395 elapsed=172.3s

  [14265/21087] intraday_3177.csv.gz  in=379,383,615 out=113,089,395 elapsed=172.3s

  [14266/21087] intraday_3178.csv.gz  in=379,398,940 out=113,089,395 elapsed=172.3s

  [14267/21087] intraday_3179.csv.gz  in=379,410,807 out=113,089,395 elapsed=172.3s

  [14268/21087] intraday_3180.csv.gz  in=379,424,446 out=113,089,395 elapsed=172.3s

  [14269/21087] intraday_3181.csv.gz  in=379,436,832 out=113,089,395 elapsed=172.3s

  [14270/21087] intraday_3182.csv.gz  in=379,448,143 out=113,089,395 elapsed=172.4s

  [14271/21087] intraday_3183.csv.gz  in=379,460,291 out=113,089,395 elapsed=172.4s

  [14272/21087] intraday_3184.csv.gz  in=379,473,954 out=113,089,395 elapsed=172.4s

  [14273/21087] intraday_3185.csv.gz  in=379,485,318 out=113,089,395 elapsed=172.4s

  [14274/21087] intraday_3186.csv.gz  in=379,497,148 out=113,089,395 elapsed=172.4s

  [14275/21087] intraday_3187.csv.gz  in=379,508,946 out=113,089,395 elapsed=172.4s

  [14276/21087] intraday_3188.csv.gz  in=379,520,843 out=113,089,395 elapsed=172.4s

  [14277/21087] intraday_3189.csv.gz  in=379,531,781 out=113,089,395 elapsed=172.4s

  [14278/21087] intraday_3190.csv.gz  in=379,544,501 out=113,089,395 elapsed=172.4s

  [14279/21087] intraday_3191.csv.gz  in=379,556,929 out=113,089,395 elapsed=172.4s

  [14280/21087] intraday_3192.csv.gz  in=379,577,461 out=113,089,395 elapsed=172.4s

  [14281/21087] intraday_3194.csv.gz  in=379,590,922 out=113,089,395 elapsed=172.4s

  [14282/21087] intraday_3193.csv.gz  in=379,602,319 out=113,089,395 elapsed=172.5s

  [14283/21087] intraday_3195.csv.gz  in=379,616,243 out=113,089,395 elapsed=172.5s

  [14284/21087] intraday_3196.csv.gz  in=379,627,924 out=113,089,395 elapsed=172.5s

  [14285/21087] intraday_3197.csv.gz  in=379,640,536 out=113,089,395 elapsed=172.5s

  [14286/21087] intraday_3198.csv.gz  in=379,653,504 out=113,089,395 elapsed=172.5s

  [14287/21087] intraday_3199.csv.gz  in=379,665,213 out=113,089,395 elapsed=172.5s

  [14288/21087] intraday_3200.csv.gz  in=379,678,148 out=113,089,395 elapsed=172.5s

  [14289/21087] intraday_3201.csv.gz  in=379,690,839 out=113,089,395 elapsed=172.5s

  [14290/21087] intraday_3202.csv.gz  in=379,704,259 out=113,089,395 elapsed=172.5s

  [14291/21087] intraday_3203.csv.gz  in=379,719,128 out=113,089,395 elapsed=172.5s

  [14292/21087] intraday_3204.csv.gz  in=379,732,662 out=113,089,395 elapsed=172.5s

  [14293/21087] intraday_3205.csv.gz  in=379,744,327 out=113,089,395 elapsed=172.5s

  [14294/21087] intraday_3207.csv.gz  in=379,755,979 out=113,089,395 elapsed=172.6s

  [14295/21087] intraday_3206.csv.gz  in=379,768,673 out=113,089,395 elapsed=172.6s

  [14296/21087] intraday_3208.csv.gz  in=379,780,089 out=113,089,395 elapsed=172.6s

  [14297/21087] intraday_3209.csv.gz  in=379,791,766 out=113,089,395 elapsed=172.6s

  [14298/21087] intraday_3211.csv.gz  in=379,805,107 out=113,089,395 elapsed=172.6s

  [14299/21087] intraday_3210.csv.gz  in=379,829,101 out=113,089,395 elapsed=172.6s

  [14300/21087] intraday_3213.csv.gz  in=379,840,259 out=113,089,395 elapsed=172.6s

  [14301/21087] intraday_3212.csv.gz  in=379,855,010 out=113,089,395 elapsed=172.6s

  [14302/21087] intraday_3214.csv.gz  in=379,867,974 out=113,089,395 elapsed=172.6s

  [14303/21087] intraday_3215.csv.gz  in=379,880,696 out=113,089,395 elapsed=172.6s

  [14304/21087] intraday_3216.csv.gz  in=379,893,111 out=113,089,395 elapsed=172.6s

  [14305/21087] intraday_3217.csv.gz  in=379,906,146 out=113,089,395 elapsed=172.7s

  [14306/21087] intraday_3218.csv.gz  in=379,921,473 out=113,089,395 elapsed=172.7s

  [14307/21087] intraday_3219.csv.gz  in=379,934,973 out=113,089,395 elapsed=172.7s

  [14308/21087] intraday_3220.csv.gz  in=379,948,216 out=113,089,395 elapsed=172.7s

  [14309/21087] intraday_3221.csv.gz  in=379,960,898 out=113,089,395 elapsed=172.7s

  [14310/21087] intraday_3222.csv.gz  in=379,972,164 out=113,089,395 elapsed=172.7s

  [14311/21087] intraday_3223.csv.gz  in=379,984,622 out=113,089,395 elapsed=172.7s

  [14312/21087] intraday_3224.csv.gz  in=379,994,428 out=113,089,395 elapsed=172.7s

  [14313/21087] intraday_3225.csv.gz  in=380,008,170 out=113,089,395 elapsed=172.7s

  [14314/21087] intraday_3226.csv.gz  in=380,014,761 out=113,089,395 elapsed=172.7s

  [14315/21087] intraday_3227.csv.gz  in=380,025,102 out=113,089,395 elapsed=172.7s

  [14316/21087] intraday_3228.csv.gz  in=380,033,521 out=113,089,395 elapsed=172.7s

  [14317/21087] intraday_3229.csv.gz  in=380,047,875 out=113,089,395 elapsed=172.8s

  [14318/21087] intraday_3230.csv.gz  in=380,061,360 out=113,089,395 elapsed=172.8s

  [14319/21087] intraday_3232.csv.gz  in=380,071,257 out=113,089,395 elapsed=172.8s

  [14320/21087] intraday_3231.csv.gz  in=380,082,922 out=113,089,395 elapsed=172.8s

  [14321/21087] intraday_3233.csv.gz  in=380,096,949 out=113,089,395 elapsed=172.8s

  [14322/21087] intraday_3234.csv.gz  in=380,110,925 out=113,089,395 elapsed=172.8s

  [14323/21087] intraday_3235.csv.gz  in=380,123,356 out=113,089,395 elapsed=172.8s

  [14324/21087] intraday_3236.csv.gz  in=380,135,149 out=113,089,395 elapsed=172.8s

  [14325/21087] intraday_3237.csv.gz  in=380,148,098 out=113,089,395 elapsed=172.8s

  [14326/21087] intraday_3238.csv.gz  in=380,160,739 out=113,089,395 elapsed=172.8s

  [14327/21087] intraday_3239.csv.gz  in=380,170,199 out=113,089,395 elapsed=172.8s

  [14328/21087] intraday_3240.csv.gz  in=380,182,367 out=113,089,395 elapsed=172.8s

  [14329/21087] intraday_3241.csv.gz  in=380,194,293 out=113,089,395 elapsed=172.9s

  [14330/21087] intraday_3243.csv.gz  in=380,205,552 out=113,089,395 elapsed=172.9s

  [14331/21087] intraday_3242.csv.gz  in=380,217,156 out=113,089,395 elapsed=172.9s

  [14332/21087] intraday_3244.csv.gz  in=380,233,179 out=113,089,395 elapsed=172.9s

  [14333/21087] intraday_3245.csv.gz  in=380,246,027 out=113,089,395 elapsed=172.9s

  [14334/21087] intraday_3247.csv.gz  in=380,256,188 out=113,089,395 elapsed=172.9s

  [14335/21087] intraday_3246.csv.gz  in=380,267,428 out=113,089,395 elapsed=172.9s

  [14336/21087] intraday_3248.csv.gz  in=380,278,809 out=113,089,395 elapsed=172.9s

  [14337/21087] intraday_3249.csv.gz  in=380,291,658 out=113,089,395 elapsed=172.9s

  [14338/21087] intraday_3250.csv.gz  in=380,302,841 out=113,089,395 elapsed=172.9s

  [14339/21087] intraday_3251.csv.gz  in=380,314,554 out=113,089,395 elapsed=172.9s

  [14340/21087] intraday_3252.csv.gz  in=380,326,915 out=113,089,395 elapsed=172.9s

  [14341/21087] intraday_3253.csv.gz  in=380,338,973 out=113,089,395 elapsed=172.9s

  [14342/21087] intraday_3254.csv.gz  in=380,353,028 out=113,089,395 elapsed=173.0s

  [14343/21087] intraday_3255.csv.gz  in=380,364,998 out=113,089,395 elapsed=173.0s

  [14344/21087] intraday_3256.csv.gz  in=380,377,901 out=113,089,395 elapsed=173.0s

  [14345/21087] intraday_3257.csv.gz  in=380,389,241 out=113,089,395 elapsed=173.0s

  [14346/21087] intraday_3258.csv.gz  in=380,404,153 out=113,089,395 elapsed=173.0s

  [14347/21087] intraday_3259.csv.gz  in=380,417,906 out=113,089,395 elapsed=173.0s

  [14348/21087] intraday_3261.csv.gz  in=380,428,564 out=113,089,395 elapsed=173.0s

  [14349/21087] intraday_3260.csv.gz  in=380,441,663 out=113,089,395 elapsed=173.0s

  [14350/21087] intraday_3262.csv.gz  in=380,453,606 out=113,089,395 elapsed=173.0s

  [14351/21087] intraday_3263.csv.gz  in=380,465,778 out=113,089,395 elapsed=173.0s

  [14352/21087] intraday_3264.csv.gz  in=380,478,327 out=113,089,395 elapsed=173.0s

  [14353/21087] intraday_3266.csv.gz  in=380,489,131 out=113,089,395 elapsed=173.0s

  [14354/21087] intraday_3265.csv.gz  in=380,503,522 out=113,089,395 elapsed=173.0s

  [14355/21087] intraday_3267.csv.gz  in=380,519,121 out=113,089,395 elapsed=173.1s

  [14356/21087] intraday_3268.csv.gz  in=380,529,767 out=113,089,395 elapsed=173.1s

  [14357/21087] intraday_3270.csv.gz  in=380,542,229 out=113,089,395 elapsed=173.1s

  [14358/21087] intraday_3269.csv.gz  in=380,555,766 out=113,089,395 elapsed=173.1s

  [14359/21087] intraday_3271.csv.gz  in=380,566,283 out=113,089,395 elapsed=173.1s

  [14360/21087] intraday_3272.csv.gz  in=380,578,898 out=113,089,395 elapsed=173.1s

  [14361/21087] intraday_3273.csv.gz  in=380,589,037 out=113,089,395 elapsed=173.1s

  [14362/21087] intraday_3274.csv.gz  in=380,600,255 out=113,089,395 elapsed=173.1s

  [14363/21087] intraday_3275.csv.gz  in=380,612,036 out=113,089,395 elapsed=173.1s

  [14364/21087] intraday_3276.csv.gz  in=380,622,511 out=113,089,395 elapsed=173.1s

  [14365/21087] intraday_3278.csv.gz  in=380,633,417 out=113,089,395 elapsed=173.1s

  [14366/21087] intraday_3277.csv.gz  in=380,650,821 out=113,089,395 elapsed=173.2s

  [14367/21087] intraday_3279.csv.gz  in=380,661,785 out=113,089,395 elapsed=173.2s

  [14368/21087] intraday_3280.csv.gz  in=380,672,563 out=113,089,395 elapsed=173.2s

  [14369/21087] intraday_3281.csv.gz  in=380,685,229 out=113,089,395 elapsed=173.2s

  [14370/21087] intraday_3282.csv.gz  in=380,694,702 out=113,089,395 elapsed=173.2s

  [14371/21087] intraday_3283.csv.gz  in=380,709,177 out=113,089,395 elapsed=173.2s

  [14372/21087] intraday_3284.csv.gz  in=380,719,711 out=113,089,395 elapsed=173.2s

  [14373/21087] intraday_3285.csv.gz  in=380,729,558 out=113,089,395 elapsed=173.2s

  [14374/21087] intraday_3286.csv.gz  in=380,740,972 out=113,089,395 elapsed=173.2s

  [14375/21087] intraday_3287.csv.gz  in=380,752,785 out=113,089,395 elapsed=173.2s

  [14376/21087] intraday_3288.csv.gz  in=380,763,571 out=113,089,395 elapsed=173.2s

  [14377/21087] intraday_3290.csv.gz  in=380,774,766 out=113,089,395 elapsed=173.2s

  [14378/21087] intraday_3289.csv.gz  in=380,797,831 out=113,089,395 elapsed=173.2s

  [14379/21087] intraday_3291.csv.gz  in=380,807,390 out=113,089,395 elapsed=173.3s

  [14380/21087] intraday_3292.csv.gz  in=380,819,430 out=113,089,395 elapsed=173.3s

  [14381/21087] intraday_3293.csv.gz  in=380,832,610 out=113,089,395 elapsed=173.3s

  [14382/21087] intraday_3295.csv.gz  in=380,845,319 out=113,089,395 elapsed=173.3s

  [14383/21087] intraday_3294.csv.gz  in=380,862,821 out=113,089,395 elapsed=173.3s

  [14384/21087] intraday_3296.csv.gz  in=380,875,831 out=113,089,395 elapsed=173.3s

  [14385/21087] intraday_3297.csv.gz  in=380,885,272 out=113,089,395 elapsed=173.3s

  [14386/21087] intraday_3298.csv.gz  in=380,896,788 out=113,089,395 elapsed=173.3s

  [14387/21087] intraday_3299.csv.gz  in=380,907,547 out=113,089,395 elapsed=173.3s

  [14388/21087] intraday_3300.csv.gz  in=380,919,099 out=113,089,395 elapsed=173.3s

  [14389/21087] intraday_3301.csv.gz  in=380,930,506 out=113,089,395 elapsed=173.3s

  [14390/21087] intraday_3302.csv.gz  in=380,941,850 out=113,089,395 elapsed=173.3s

  [14391/21087] intraday_3303.csv.gz  in=380,951,696 out=113,089,395 elapsed=173.3s

  [14392/21087] intraday_3304.csv.gz  in=380,962,801 out=113,089,395 elapsed=173.4s

  [14393/21087] intraday_3305.csv.gz  in=380,975,483 out=113,089,395 elapsed=173.4s

  [14394/21087] intraday_3306.csv.gz  in=380,986,581 out=113,089,395 elapsed=173.4s

  [14395/21087] intraday_3307.csv.gz  in=380,998,504 out=113,089,395 elapsed=173.4s

  [14396/21087] intraday_3308.csv.gz  in=381,007,889 out=113,089,395 elapsed=173.4s

  [14397/21087] intraday_3309.csv.gz  in=381,018,468 out=113,089,395 elapsed=173.4s

  [14398/21087] intraday_3310.csv.gz  in=381,031,146 out=113,089,395 elapsed=173.4s

  [14399/21087] intraday_3311.csv.gz  in=381,045,253 out=113,089,395 elapsed=173.4s

  [14400/21087] intraday_3312.csv.gz  in=381,055,382 out=113,089,395 elapsed=173.4s

  [14401/21087] intraday_3313.csv.gz  in=381,066,637 out=113,089,395 elapsed=173.4s

  [14402/21087] intraday_3314.csv.gz  in=381,075,973 out=113,089,395 elapsed=173.4s

  [14403/21087] intraday_3315.csv.gz  in=381,089,248 out=113,089,395 elapsed=173.4s

  [14404/21087] intraday_3316.csv.gz  in=381,100,719 out=113,089,395 elapsed=173.4s

  [14405/21087] intraday_3317.csv.gz  in=381,115,388 out=113,089,395 elapsed=173.5s

  [14406/21087] intraday_3318.csv.gz  in=381,126,446 out=113,089,395 elapsed=173.5s

  [14407/21087] intraday_3319.csv.gz  in=381,140,916 out=113,089,395 elapsed=173.5s

  [14408/21087] intraday_3320.csv.gz  in=381,153,882 out=113,089,395 elapsed=173.5s

  [14409/21087] intraday_3321.csv.gz  in=381,166,583 out=113,089,395 elapsed=173.5s

  [14410/21087] intraday_3323.csv.gz  in=381,176,910 out=113,089,395 elapsed=173.5s

  [14411/21087] intraday_3324.csv.gz  in=381,188,418 out=113,089,395 elapsed=173.5s

  [14412/21087] intraday_3325.csv.gz  in=381,202,793 out=113,089,395 elapsed=173.5s

  [14413/21087] intraday_3322.csv.gz  in=381,215,503 out=113,089,395 elapsed=173.5s

  [14414/21087] intraday_3326.csv.gz  in=381,226,279 out=113,089,395 elapsed=173.5s

  [14415/21087] intraday_3327.csv.gz  in=381,236,936 out=113,089,395 elapsed=173.6s

  [14416/21087] intraday_3329.csv.gz  in=381,249,316 out=113,089,395 elapsed=173.6s

  [14417/21087] intraday_3328.csv.gz  in=381,260,895 out=113,089,395 elapsed=173.6s

  [14418/21087] intraday_3330.csv.gz  in=381,272,707 out=113,089,395 elapsed=173.6s

  [14419/21087] intraday_3331.csv.gz  in=381,284,537 out=113,089,395 elapsed=173.6s

  [14420/21087] intraday_3333.csv.gz  in=381,296,069 out=113,089,395 elapsed=173.6s

  [14421/21087] intraday_3332.csv.gz  in=381,307,714 out=113,089,395 elapsed=173.6s

  [14422/21087] intraday_3334.csv.gz  in=381,318,370 out=113,089,395 elapsed=173.6s

  [14423/21087] intraday_3335.csv.gz  in=381,332,149 out=113,089,395 elapsed=173.6s

  [14424/21087] intraday_3336.csv.gz  in=381,345,566 out=113,089,395 elapsed=173.6s

  [14425/21087] intraday_3337.csv.gz  in=381,356,999 out=113,089,395 elapsed=173.6s

  [14426/21087] intraday_3338.csv.gz  in=381,369,064 out=113,089,395 elapsed=173.6s

  [14427/21087] intraday_3340.csv.gz  in=381,380,312 out=113,089,395 elapsed=173.6s

  [14428/21087] intraday_3339.csv.gz  in=381,396,688 out=113,089,395 elapsed=173.7s

  [14429/21087] intraday_3341.csv.gz  in=381,409,113 out=113,089,395 elapsed=173.7s

  [14430/21087] intraday_3342.csv.gz  in=381,422,401 out=113,089,395 elapsed=173.7s

  [14431/21087] intraday_3344.csv.gz  in=381,437,266 out=113,089,395 elapsed=173.7s

  [14432/21087] intraday_3343.csv.gz  in=381,449,652 out=113,089,395 elapsed=173.7s

  [14433/21087] intraday_3346.csv.gz  in=381,461,639 out=113,089,395 elapsed=173.7s

  [14434/21087] intraday_3345.csv.gz  in=381,475,538 out=113,089,395 elapsed=173.7s

  [14435/21087] intraday_3347.csv.gz  in=381,488,172 out=113,089,395 elapsed=173.7s

  [14436/21087] intraday_3348.csv.gz  in=381,501,034 out=113,089,395 elapsed=173.7s

  [14437/21087] intraday_3350.csv.gz  in=381,511,048 out=113,089,395 elapsed=173.7s

  [14438/21087] intraday_3349.csv.gz  in=381,529,756 out=113,089,395 elapsed=173.8s

  [14439/21087] intraday_3351.csv.gz  in=381,543,103 out=113,089,395 elapsed=173.8s

  [14440/21087] intraday_3352.csv.gz  in=381,555,616 out=113,089,395 elapsed=173.8s

  [14441/21087] intraday_3353.csv.gz  in=381,571,519 out=113,089,395 elapsed=173.8s

  [14442/21087] intraday_3355.csv.gz  in=381,583,026 out=113,089,395 elapsed=173.8s

  [14443/21087] intraday_3354.csv.gz  in=381,594,480 out=113,089,395 elapsed=173.8s

  [14444/21087] intraday_3356.csv.gz  in=381,607,309 out=113,089,395 elapsed=173.8s

  [14445/21087] intraday_3357.csv.gz  in=381,619,846 out=113,089,395 elapsed=173.8s

  [14446/21087] intraday_3358.csv.gz  in=381,632,148 out=113,089,395 elapsed=173.8s

  [14447/21087] intraday_3359.csv.gz  in=381,646,912 out=113,089,395 elapsed=173.8s

  [14448/21087] intraday_3360.csv.gz  in=381,659,705 out=113,089,395 elapsed=173.8s

  [14449/21087] intraday_3361.csv.gz  in=381,672,321 out=113,089,395 elapsed=173.8s

  [14450/21087] intraday_3362.csv.gz  in=381,685,277 out=113,089,395 elapsed=173.8s

  [14451/21087] intraday_3363.csv.gz  in=381,696,079 out=113,089,395 elapsed=173.8s

  [14452/21087] intraday_3365.csv.gz  in=381,705,711 out=113,089,395 elapsed=173.9s

  [14453/21087] intraday_3364.csv.gz  in=381,721,925 out=113,089,395 elapsed=173.9s

  [14454/21087] intraday_3366.csv.gz  in=381,735,131 out=113,089,395 elapsed=173.9s

  [14455/21087] intraday_3367.csv.gz  in=381,741,808 out=113,089,395 elapsed=173.9s

  [14456/21087] intraday_3368.csv.gz  in=381,751,381 out=113,089,395 elapsed=173.9s

  [14457/21087] intraday_3369.csv.gz  in=381,761,749 out=113,089,395 elapsed=173.9s

  [14458/21087] intraday_3370.csv.gz  in=381,776,617 out=113,089,395 elapsed=173.9s

  [14459/21087] intraday_3371.csv.gz  in=381,790,396 out=113,089,395 elapsed=173.9s

  [14460/21087] intraday_3372.csv.gz  in=381,801,963 out=113,089,395 elapsed=173.9s

  [14461/21087] intraday_3373.csv.gz  in=381,812,307 out=113,089,395 elapsed=173.9s

  [14462/21087] intraday_3374.csv.gz  in=381,826,888 out=113,089,395 elapsed=173.9s

  [14463/21087] intraday_3375.csv.gz  in=381,841,474 out=113,089,395 elapsed=173.9s

  [14464/21087] intraday_3376.csv.gz  in=381,854,241 out=113,089,395 elapsed=173.9s

  [14465/21087] intraday_3377.csv.gz  in=381,866,408 out=113,089,395 elapsed=173.9s

  [14466/21087] intraday_3378.csv.gz  in=381,880,091 out=113,089,395 elapsed=174.0s

  [14467/21087] intraday_3379.csv.gz  in=381,893,640 out=113,089,395 elapsed=174.0s

  [14468/21087] intraday_3380.csv.gz  in=381,903,227 out=113,089,395 elapsed=174.0s

  [14469/21087] intraday_3381.csv.gz  in=381,915,087 out=113,089,395 elapsed=174.0s

  [14470/21087] intraday_3383.csv.gz  in=381,925,271 out=113,089,395 elapsed=174.0s

  [14471/21087] intraday_3382.csv.gz  in=381,938,066 out=113,089,395 elapsed=174.0s

  [14472/21087] intraday_3384.csv.gz  in=381,949,832 out=113,089,395 elapsed=174.0s

  [14473/21087] intraday_3385.csv.gz  in=381,961,163 out=113,089,395 elapsed=174.0s

  [14474/21087] intraday_3386.csv.gz  in=381,973,652 out=113,089,395 elapsed=174.0s

  [14475/21087] intraday_3387.csv.gz  in=381,985,807 out=113,089,395 elapsed=174.0s

  [14476/21087] intraday_3388.csv.gz  in=381,997,375 out=113,089,395 elapsed=174.0s

  [14477/21087] intraday_3389.csv.gz  in=382,009,771 out=113,089,395 elapsed=174.0s

  [14478/21087] intraday_3390.csv.gz  in=382,022,554 out=113,089,395 elapsed=174.0s

  [14479/21087] intraday_3391.csv.gz  in=382,033,924 out=113,089,395 elapsed=174.1s

  [14480/21087] intraday_3392.csv.gz  in=382,046,076 out=113,089,395 elapsed=174.1s

  [14481/21087] intraday_3393.csv.gz  in=382,058,802 out=113,089,395 elapsed=174.1s

  [14482/21087] intraday_3394.csv.gz  in=382,070,713 out=113,089,395 elapsed=174.1s

  [14483/21087] intraday_3395.csv.gz  in=382,081,868 out=113,089,395 elapsed=174.1s

  [14484/21087] intraday_3396.csv.gz  in=382,093,546 out=113,089,395 elapsed=174.1s

  [14485/21087] intraday_3398.csv.gz  in=382,107,619 out=113,089,395 elapsed=174.1s

  [14486/21087] intraday_3397.csv.gz  in=382,120,410 out=113,089,395 elapsed=174.1s

  [14487/21087] intraday_3399.csv.gz  in=382,136,738 out=113,089,395 elapsed=174.1s

  [14488/21087] intraday_3400.csv.gz  in=382,149,102 out=113,089,395 elapsed=174.1s

  [14489/21087] intraday_3401.csv.gz  in=382,161,679 out=113,089,395 elapsed=174.1s

  [14490/21087] intraday_3402.csv.gz  in=382,173,546 out=113,089,395 elapsed=174.1s

  [14491/21087] intraday_3403.csv.gz  in=382,186,656 out=113,089,395 elapsed=174.1s

  [14492/21087] intraday_3404.csv.gz  in=382,199,371 out=113,089,395 elapsed=174.2s

  [14493/21087] intraday_3405.csv.gz  in=382,211,599 out=113,089,395 elapsed=174.2s

  [14494/21087] intraday_3406.csv.gz  in=382,222,564 out=113,089,395 elapsed=174.2s

  [14495/21087] intraday_3407.csv.gz  in=382,232,370 out=113,089,395 elapsed=174.2s

  [14496/21087] intraday_3408.csv.gz  in=382,243,989 out=113,089,395 elapsed=174.2s

  [14497/21087] intraday_3409.csv.gz  in=382,253,564 out=113,089,395 elapsed=174.2s

  [14498/21087] intraday_3411.csv.gz  in=382,266,158 out=113,089,395 elapsed=174.2s

  [14499/21087] intraday_3410.csv.gz  in=382,280,648 out=113,089,395 elapsed=174.2s

  [14500/21087] intraday_3412.csv.gz  in=382,293,276 out=113,089,395 elapsed=174.2s

  [14501/21087] intraday_3413.csv.gz  in=382,304,708 out=113,089,395 elapsed=174.2s

  [14502/21087] intraday_3414.csv.gz  in=382,315,355 out=113,089,395 elapsed=174.2s

  [14503/21087] intraday_3415.csv.gz  in=382,328,306 out=113,089,395 elapsed=174.2s

  [14504/21087] intraday_3416.csv.gz  in=382,338,874 out=113,089,395 elapsed=174.2s

  [14505/21087] intraday_3417.csv.gz  in=382,349,387 out=113,089,395 elapsed=174.3s

  [14506/21087] intraday_3418.csv.gz  in=382,361,324 out=113,089,395 elapsed=174.3s

  [14507/21087] intraday_3419.csv.gz  in=382,372,874 out=113,089,395 elapsed=174.3s

  [14508/21087] intraday_3420.csv.gz  in=382,384,212 out=113,089,395 elapsed=174.3s

  [14509/21087] intraday_3421.csv.gz  in=382,396,178 out=113,089,395 elapsed=174.3s

  [14510/21087] intraday_3422.csv.gz  in=382,405,811 out=113,089,395 elapsed=174.3s

  [14511/21087] intraday_3423.csv.gz  in=382,419,273 out=113,089,395 elapsed=174.3s

  [14512/21087] intraday_3424.csv.gz  in=382,430,923 out=113,089,395 elapsed=174.3s

  [14513/21087] intraday_3425.csv.gz  in=382,441,536 out=113,089,395 elapsed=174.3s

  [14514/21087] intraday_3426.csv.gz  in=382,451,428 out=113,089,395 elapsed=174.3s

  [14515/21087] intraday_3427.csv.gz  in=382,463,571 out=113,089,395 elapsed=174.3s

  [14516/21087] intraday_3428.csv.gz  in=382,476,584 out=113,089,395 elapsed=174.3s

  [14517/21087] intraday_3429.csv.gz  in=382,487,809 out=113,089,395 elapsed=174.3s

  [14518/21087] intraday_3430.csv.gz  in=382,498,978 out=113,089,395 elapsed=174.3s

  [14519/21087] intraday_3432.csv.gz  in=382,508,509 out=113,089,395 elapsed=174.4s

  [14520/21087] intraday_3431.csv.gz  in=382,521,044 out=113,089,395 elapsed=174.4s

  [14521/21087] intraday_3433.csv.gz  in=382,534,994 out=113,089,395 elapsed=174.4s

  [14522/21087] intraday_3434.csv.gz  in=382,548,993 out=113,089,395 elapsed=174.4s

  [14523/21087] intraday_3435.csv.gz  in=382,559,436 out=113,089,395 elapsed=174.4s

  [14524/21087] intraday_3436.csv.gz  in=382,572,673 out=113,089,395 elapsed=174.4s

  [14525/21087] intraday_3437.csv.gz  in=382,585,881 out=113,089,395 elapsed=174.4s

  [14526/21087] intraday_3438.csv.gz  in=382,595,315 out=113,089,395 elapsed=174.4s

  [14527/21087] intraday_3439.csv.gz  in=382,606,525 out=113,089,395 elapsed=174.4s

  [14528/21087] intraday_3440.csv.gz  in=382,618,076 out=113,089,395 elapsed=174.4s

  [14529/21087] intraday_3442.csv.gz  in=382,627,151 out=113,089,395 elapsed=174.4s

  [14530/21087] intraday_3441.csv.gz  in=382,640,591 out=113,089,395 elapsed=174.4s

  [14531/21087] intraday_3443.csv.gz  in=382,651,947 out=113,089,395 elapsed=174.4s

  [14532/21087] intraday_3444.csv.gz  in=382,663,031 out=113,089,395 elapsed=174.5s

  [14533/21087] intraday_3446.csv.gz  in=382,675,181 out=113,089,395 elapsed=174.5s

  [14534/21087] intraday_3445.csv.gz  in=382,687,355 out=113,089,395 elapsed=174.5s

  [14535/21087] intraday_3447.csv.gz  in=382,700,010 out=113,089,395 elapsed=174.5s

  [14536/21087] intraday_3448.csv.gz  in=382,710,524 out=113,089,395 elapsed=174.5s

  [14537/21087] intraday_3449.csv.gz  in=382,720,009 out=113,089,395 elapsed=174.5s

  [14538/21087] intraday_3450.csv.gz  in=382,730,749 out=113,089,395 elapsed=174.5s

  [14539/21087] intraday_3451.csv.gz  in=382,746,689 out=113,089,395 elapsed=174.5s

  [14540/21087] intraday_3452.csv.gz  in=382,759,443 out=113,089,395 elapsed=174.5s

  [14541/21087] intraday_3453.csv.gz  in=382,770,877 out=113,089,395 elapsed=174.5s

  [14542/21087] intraday_3454.csv.gz  in=382,781,433 out=113,089,395 elapsed=174.5s

  [14543/21087] intraday_3455.csv.gz  in=382,791,900 out=113,089,395 elapsed=174.5s

  [14544/21087] intraday_3456.csv.gz  in=382,804,193 out=113,089,395 elapsed=174.6s

  [14545/21087] intraday_3457.csv.gz  in=382,817,966 out=113,089,395 elapsed=174.6s

  [14546/21087] intraday_3458.csv.gz  in=382,830,464 out=113,089,395 elapsed=174.6s

  [14547/21087] intraday_3459.csv.gz  in=382,843,216 out=113,089,395 elapsed=174.6s

  [14548/21087] intraday_3460.csv.gz  in=382,857,385 out=113,089,395 elapsed=174.6s

  [14549/21087] intraday_3461.csv.gz  in=382,870,917 out=113,089,395 elapsed=174.6s

  [14550/21087] intraday_3462.csv.gz  in=382,884,259 out=113,089,395 elapsed=174.6s

  [14551/21087] intraday_3463.csv.gz  in=382,896,056 out=113,089,395 elapsed=174.6s

  [14552/21087] intraday_3464.csv.gz  in=382,908,662 out=113,089,395 elapsed=174.6s

  [14553/21087] intraday_3465.csv.gz  in=382,919,214 out=113,089,395 elapsed=174.6s

  [14554/21087] intraday_3466.csv.gz  in=382,932,632 out=113,089,395 elapsed=174.6s

  [14555/21087] intraday_3467.csv.gz  in=382,944,349 out=113,089,395 elapsed=174.6s

  [14556/21087] intraday_3468.csv.gz  in=382,957,069 out=113,089,395 elapsed=174.6s

  [14557/21087] intraday_3469.csv.gz  in=382,967,280 out=113,089,395 elapsed=174.7s

  [14558/21087] intraday_3470.csv.gz  in=382,980,126 out=113,089,395 elapsed=174.7s

  [14559/21087] intraday_3471.csv.gz  in=382,992,478 out=113,089,395 elapsed=174.7s

  [14560/21087] intraday_3472.csv.gz  in=383,005,192 out=113,089,395 elapsed=174.7s

  [14561/21087] intraday_3473.csv.gz  in=383,019,278 out=113,089,395 elapsed=174.7s

  [14562/21087] intraday_3474.csv.gz  in=383,030,632 out=113,089,395 elapsed=174.7s

  [14563/21087] intraday_3475.csv.gz  in=383,042,675 out=113,089,395 elapsed=174.7s

  [14564/21087] intraday_3476.csv.gz  in=383,057,661 out=113,089,395 elapsed=174.7s

  [14565/21087] intraday_3477.csv.gz  in=383,071,603 out=113,089,395 elapsed=174.7s

  [14566/21087] intraday_3478.csv.gz  in=383,083,803 out=113,089,395 elapsed=174.7s

  [14567/21087] intraday_3479.csv.gz  in=383,096,466 out=113,089,395 elapsed=174.7s

  [14568/21087] intraday_3480.csv.gz  in=383,108,864 out=113,089,395 elapsed=174.7s

  [14569/21087] intraday_3481.csv.gz  in=383,121,280 out=113,089,395 elapsed=174.7s

  [14570/21087] intraday_3482.csv.gz  in=383,134,863 out=113,089,395 elapsed=174.8s

  [14571/21087] intraday_3483.csv.gz  in=383,149,718 out=113,089,395 elapsed=174.8s

  [14572/21087] intraday_3484.csv.gz  in=383,161,482 out=113,089,395 elapsed=174.8s

  [14573/21087] intraday_3485.csv.gz  in=383,177,712 out=113,089,395 elapsed=174.8s

  [14574/21087] intraday_3486.csv.gz  in=383,189,722 out=113,089,395 elapsed=174.8s

  [14575/21087] intraday_3487.csv.gz  in=383,202,180 out=113,089,395 elapsed=174.8s

  [14576/21087] intraday_3488.csv.gz  in=383,213,290 out=113,089,395 elapsed=174.8s

  [14577/21087] intraday_3489.csv.gz  in=383,226,277 out=113,089,395 elapsed=174.8s

  [14578/21087] intraday_3490.csv.gz  in=383,236,475 out=113,089,395 elapsed=174.8s

  [14579/21087] intraday_3491.csv.gz  in=383,251,243 out=113,089,395 elapsed=174.8s

  [14580/21087] intraday_3492.csv.gz  in=383,263,792 out=113,089,395 elapsed=174.8s

  [14581/21087] intraday_3493.csv.gz  in=383,278,276 out=113,089,395 elapsed=174.8s

  [14582/21087] intraday_3494.csv.gz  in=383,290,740 out=113,089,395 elapsed=174.8s

  [14583/21087] intraday_3495.csv.gz  in=383,303,739 out=113,089,395 elapsed=174.8s

  [14584/21087] intraday_3496.csv.gz  in=383,316,176 out=113,089,395 elapsed=174.9s

  [14585/21087] intraday_3497.csv.gz  in=383,329,306 out=113,089,395 elapsed=174.9s

  [14586/21087] intraday_3499.csv.gz  in=383,343,887 out=113,089,395 elapsed=174.9s

  [14587/21087] intraday_3498.csv.gz  in=383,356,528 out=113,089,395 elapsed=174.9s

  [14588/21087] intraday_3502.csv.gz  in=383,369,895 out=113,089,395 elapsed=174.9s

  [14589/21087] intraday_3501.csv.gz  in=383,383,041 out=113,089,395 elapsed=174.9s

  [14590/21087] intraday_3500.csv.gz  in=383,397,631 out=113,089,395 elapsed=174.9s

  [14591/21087] intraday_3503.csv.gz  in=383,409,361 out=113,089,395 elapsed=174.9s

  [14592/21087] intraday_3507.csv.gz  in=383,417,747 out=113,089,395 elapsed=175.0s

  [14593/21087] intraday_3504.csv.gz  in=383,428,425 out=113,089,395 elapsed=175.0s

  [14594/21087] intraday_3506.csv.gz  in=383,441,536 out=113,089,395 elapsed=175.0s

  [14595/21087] intraday_3505.csv.gz  in=383,453,375 out=113,089,395 elapsed=175.0s

  [14596/21087] intraday_3508.csv.gz  in=383,462,114 out=113,089,395 elapsed=175.0s

  [14597/21087] intraday_3509.csv.gz  in=383,474,635 out=113,089,395 elapsed=175.0s

  [14598/21087] intraday_3511.csv.gz  in=383,488,032 out=113,089,395 elapsed=175.0s

  [14599/21087] intraday_3510.csv.gz  in=383,502,239 out=113,089,395 elapsed=175.0s

  [14600/21087] intraday_3512.csv.gz  in=383,514,533 out=113,089,395 elapsed=175.0s

  [14601/21087] intraday_3513.csv.gz  in=383,524,521 out=113,089,395 elapsed=175.0s

  [14602/21087] intraday_3514.csv.gz  in=383,538,035 out=113,089,395 elapsed=175.0s

  [14603/21087] intraday_3515.csv.gz  in=383,551,633 out=113,089,395 elapsed=175.0s

  [14604/21087] intraday_3516.csv.gz  in=383,564,229 out=113,089,395 elapsed=175.0s

  [14605/21087] intraday_3517.csv.gz  in=383,576,258 out=113,089,395 elapsed=175.0s

  [14606/21087] intraday_3518.csv.gz  in=383,590,546 out=113,089,395 elapsed=175.1s

  [14607/21087] intraday_3520.csv.gz  in=383,599,790 out=113,089,395 elapsed=175.1s

  [14608/21087] intraday_3519.csv.gz  in=383,613,140 out=113,089,395 elapsed=175.1s

  [14609/21087] intraday_3521.csv.gz  in=383,625,577 out=113,089,395 elapsed=175.1s

  [14610/21087] intraday_3522.csv.gz  in=383,637,752 out=113,089,395 elapsed=175.1s

  [14611/21087] intraday_3523.csv.gz  in=383,648,257 out=113,089,395 elapsed=175.1s

  [14612/21087] intraday_3524.csv.gz  in=383,660,162 out=113,089,395 elapsed=175.1s

  [14613/21087] intraday_3525.csv.gz  in=383,671,496 out=113,089,395 elapsed=175.1s

  [14614/21087] intraday_3526.csv.gz  in=383,684,191 out=113,089,395 elapsed=175.1s

  [14615/21087] intraday_3527.csv.gz  in=383,696,552 out=113,089,395 elapsed=175.1s

  [14616/21087] intraday_3529.csv.gz  in=383,709,666 out=113,089,395 elapsed=175.1s

  [14617/21087] intraday_3528.csv.gz  in=383,721,388 out=113,089,395 elapsed=175.1s

  [14618/21087] intraday_3530.csv.gz  in=383,734,313 out=113,089,395 elapsed=175.2s

  [14619/21087] intraday_3531.csv.gz  in=383,745,693 out=113,089,395 elapsed=175.2s

  [14620/21087] intraday_3532.csv.gz  in=383,757,043 out=113,089,395 elapsed=175.2s

  [14621/21087] intraday_3533.csv.gz  in=383,770,027 out=113,089,395 elapsed=175.2s

  [14622/21087] intraday_3534.csv.gz  in=383,782,430 out=113,089,395 elapsed=175.2s

  [14623/21087] intraday_3535.csv.gz  in=383,793,035 out=113,089,395 elapsed=175.2s

  [14624/21087] intraday_3536.csv.gz  in=383,805,245 out=113,089,395 elapsed=175.2s

  [14625/21087] intraday_3537.csv.gz  in=383,817,577 out=113,089,395 elapsed=175.2s

  [14626/21087] intraday_3538.csv.gz  in=383,831,719 out=113,089,395 elapsed=175.2s

  [14627/21087] intraday_3540.csv.gz  in=383,844,790 out=113,089,395 elapsed=175.2s

  [14628/21087] intraday_3539.csv.gz  in=383,859,066 out=113,089,395 elapsed=175.2s

  [14629/21087] intraday_3541.csv.gz  in=383,870,640 out=113,089,395 elapsed=175.2s

  [14630/21087] intraday_3542.csv.gz  in=383,882,090 out=113,089,395 elapsed=175.2s

  [14631/21087] intraday_3543.csv.gz  in=383,894,679 out=113,089,395 elapsed=175.2s

  [14632/21087] intraday_3544.csv.gz  in=383,906,198 out=113,089,395 elapsed=175.3s

  [14633/21087] intraday_3545.csv.gz  in=383,918,522 out=113,089,395 elapsed=175.3s

  [14634/21087] intraday_3546.csv.gz  in=383,929,391 out=113,089,395 elapsed=175.3s

  [14635/21087] intraday_3547.csv.gz  in=383,940,078 out=113,089,395 elapsed=175.3s

  [14636/21087] intraday_3548.csv.gz  in=383,951,048 out=113,089,395 elapsed=175.3s

  [14637/21087] intraday_3549.csv.gz  in=383,961,366 out=113,089,395 elapsed=175.3s

  [14638/21087] intraday_3550.csv.gz  in=383,975,239 out=113,089,395 elapsed=175.3s

  [14639/21087] intraday_3551.csv.gz  in=383,987,505 out=113,089,395 elapsed=175.3s

  [14640/21087] intraday_3552.csv.gz  in=384,001,075 out=113,089,395 elapsed=175.3s

  [14641/21087] intraday_3553.csv.gz  in=384,012,356 out=113,089,395 elapsed=175.3s

  [14642/21087] intraday_3554.csv.gz  in=384,023,693 out=113,089,395 elapsed=175.3s

  [14643/21087] intraday_3556.csv.gz  in=384,033,885 out=113,089,395 elapsed=175.3s

  [14644/21087] intraday_3555.csv.gz  in=384,046,539 out=113,089,395 elapsed=175.3s

  [14645/21087] intraday_3557.csv.gz  in=384,058,323 out=113,089,395 elapsed=175.4s

  [14646/21087] intraday_3558.csv.gz  in=384,070,169 out=113,089,395 elapsed=175.4s

  [14647/21087] intraday_3560.csv.gz  in=384,081,596 out=113,089,395 elapsed=175.4s

  [14648/21087] intraday_3559.csv.gz  in=384,091,977 out=113,089,395 elapsed=175.4s

  [14649/21087] intraday_3561.csv.gz  in=384,102,873 out=113,089,395 elapsed=175.4s

  [14650/21087] intraday_3562.csv.gz  in=384,113,286 out=113,089,395 elapsed=175.4s

  [14651/21087] intraday_3563.csv.gz  in=384,126,128 out=113,089,395 elapsed=175.4s

  [14652/21087] intraday_3564.csv.gz  in=384,138,452 out=113,089,395 elapsed=175.4s

  [14653/21087] intraday_3565.csv.gz  in=384,148,888 out=113,089,395 elapsed=175.4s

  [14654/21087] intraday_3566.csv.gz  in=384,158,397 out=113,089,395 elapsed=175.4s

  [14655/21087] intraday_3567.csv.gz  in=384,172,185 out=113,089,395 elapsed=175.4s

  [14656/21087] intraday_3569.csv.gz  in=384,183,367 out=113,089,395 elapsed=175.4s

  [14657/21087] intraday_3568.csv.gz  in=384,196,666 out=113,089,395 elapsed=175.4s

  [14658/21087] intraday_3570.csv.gz  in=384,208,774 out=113,089,395 elapsed=175.4s

  [14659/21087] intraday_3571.csv.gz  in=384,220,186 out=113,089,395 elapsed=175.5s

  [14660/21087] intraday_3572.csv.gz  in=384,230,510 out=113,089,395 elapsed=175.5s

  [14661/21087] intraday_3573.csv.gz  in=384,243,872 out=113,089,395 elapsed=175.5s

  [14662/21087] intraday_3574.csv.gz  in=384,256,707 out=113,089,395 elapsed=175.5s

  [14663/21087] intraday_3575.csv.gz  in=384,269,239 out=113,089,395 elapsed=175.5s

  [14664/21087] intraday_3577.csv.gz  in=384,279,758 out=113,089,395 elapsed=175.5s

  [14665/21087] intraday_3578.csv.gz  in=384,290,049 out=113,089,395 elapsed=175.5s

  [14666/21087] intraday_3576.csv.gz  in=384,302,741 out=113,089,395 elapsed=175.5s

  [14667/21087] intraday_3579.csv.gz  in=384,314,576 out=113,089,395 elapsed=175.5s

  [14668/21087] intraday_3580.csv.gz  in=384,325,433 out=113,089,395 elapsed=175.5s

  [14669/21087] intraday_3581.csv.gz  in=384,338,725 out=113,089,395 elapsed=175.5s

  [14670/21087] intraday_3582.csv.gz  in=384,348,981 out=113,089,395 elapsed=175.5s

  [14671/21087] intraday_3583.csv.gz  in=384,358,714 out=113,089,395 elapsed=175.6s

  [14672/21087] intraday_3584.csv.gz  in=384,369,404 out=113,089,395 elapsed=175.6s

  [14673/21087] intraday_3585.csv.gz  in=384,382,129 out=113,089,395 elapsed=175.6s

  [14674/21087] intraday_3586.csv.gz  in=384,394,013 out=113,089,395 elapsed=175.6s

  [14675/21087] intraday_3587.csv.gz  in=384,406,814 out=113,089,395 elapsed=175.6s

  [14676/21087] intraday_3589.csv.gz  in=384,418,322 out=113,089,395 elapsed=175.6s

  [14677/21087] intraday_3590.csv.gz  in=384,429,538 out=113,089,395 elapsed=175.6s

  [14678/21087] intraday_3588.csv.gz  in=384,440,963 out=113,089,395 elapsed=175.6s

  [14679/21087] intraday_3591.csv.gz  in=384,454,643 out=113,089,395 elapsed=175.6s

  [14680/21087] intraday_3592.csv.gz  in=384,467,042 out=113,089,395 elapsed=175.6s

  [14681/21087] intraday_3593.csv.gz  in=384,477,901 out=113,089,395 elapsed=175.7s

  [14682/21087] intraday_3594.csv.gz  in=384,488,236 out=113,089,395 elapsed=175.7s

  [14683/21087] intraday_3595.csv.gz  in=384,500,238 out=113,089,395 elapsed=175.7s

  [14684/21087] intraday_3596.csv.gz  in=384,512,622 out=113,089,395 elapsed=175.7s

  [14685/21087] intraday_3597.csv.gz  in=384,527,732 out=113,089,395 elapsed=175.7s

  [14686/21087] intraday_3598.csv.gz  in=384,538,461 out=113,089,395 elapsed=175.7s

  [14687/21087] intraday_3599.csv.gz  in=384,555,769 out=113,089,395 elapsed=175.7s

  [14688/21087] intraday_3600.csv.gz  in=384,568,929 out=113,089,395 elapsed=175.7s

  [14689/21087] intraday_3601.csv.gz  in=384,583,200 out=113,089,395 elapsed=175.7s

  [14690/21087] intraday_3602.csv.gz  in=384,596,200 out=113,089,395 elapsed=175.7s

  [14691/21087] intraday_3603.csv.gz  in=384,607,582 out=113,089,395 elapsed=175.7s

  [14692/21087] intraday_3604.csv.gz  in=384,619,044 out=113,089,395 elapsed=175.7s

  [14693/21087] intraday_3605.csv.gz  in=384,631,291 out=113,089,395 elapsed=175.8s

  [14694/21087] intraday_3606.csv.gz  in=384,649,965 out=113,089,395 elapsed=175.8s

  [14695/21087] intraday_3607.csv.gz  in=384,661,187 out=113,089,395 elapsed=175.8s

  [14696/21087] intraday_3608.csv.gz  in=384,673,263 out=113,089,395 elapsed=175.8s

  [14697/21087] intraday_3609.csv.gz  in=384,685,938 out=113,089,395 elapsed=175.8s

  [14698/21087] intraday_3611.csv.gz  in=384,699,788 out=113,089,395 elapsed=175.8s

  [14699/21087] intraday_3610.csv.gz  in=384,710,916 out=113,089,395 elapsed=175.8s

  [14700/21087] intraday_3612.csv.gz  in=384,723,048 out=113,089,395 elapsed=175.8s

  [14701/21087] intraday_3613.csv.gz  in=384,736,281 out=113,089,395 elapsed=175.8s

  [14702/21087] intraday_3614.csv.gz  in=384,748,941 out=113,089,395 elapsed=175.8s

  [14703/21087] intraday_3615.csv.gz  in=384,761,542 out=113,089,395 elapsed=175.8s

  [14704/21087] intraday_3616.csv.gz  in=384,775,666 out=113,089,395 elapsed=175.8s

  [14705/21087] intraday_3617.csv.gz  in=384,788,633 out=113,089,395 elapsed=175.9s

  [14706/21087] intraday_3619.csv.gz  in=384,802,139 out=113,089,395 elapsed=175.9s

  [14707/21087] intraday_3620.csv.gz  in=384,813,942 out=113,089,395 elapsed=175.9s

  [14708/21087] intraday_3618.csv.gz  in=384,825,312 out=113,089,395 elapsed=175.9s

  [14709/21087] intraday_3621.csv.gz  in=384,837,945 out=113,089,395 elapsed=175.9s

  [14710/21087] intraday_3623.csv.gz  in=384,851,535 out=113,089,395 elapsed=175.9s

  [14711/21087] intraday_3622.csv.gz  in=384,865,634 out=113,089,395 elapsed=175.9s

  [14712/21087] intraday_3624.csv.gz  in=384,879,160 out=113,089,395 elapsed=175.9s

  [14713/21087] intraday_3625.csv.gz  in=384,893,059 out=113,089,395 elapsed=175.9s

  [14714/21087] intraday_3626.csv.gz  in=384,905,593 out=113,089,395 elapsed=175.9s

  [14715/21087] intraday_3627.csv.gz  in=384,917,559 out=113,089,395 elapsed=175.9s

  [14716/21087] intraday_3628.csv.gz  in=384,928,406 out=113,089,395 elapsed=175.9s

  [14717/21087] intraday_3629.csv.gz  in=384,941,086 out=113,089,395 elapsed=176.0s

  [14718/21087] intraday_3630.csv.gz  in=384,950,701 out=113,089,395 elapsed=176.0s

  [14719/21087] intraday_3631.csv.gz  in=384,963,585 out=113,089,395 elapsed=176.0s

  [14720/21087] intraday_3632.csv.gz  in=384,976,431 out=113,089,395 elapsed=176.0s

  [14721/21087] intraday_3633.csv.gz  in=384,994,941 out=113,089,395 elapsed=176.0s

  [14722/21087] intraday_3634.csv.gz  in=385,005,994 out=113,089,395 elapsed=176.0s

  [14723/21087] intraday_3635.csv.gz  in=385,018,894 out=113,089,395 elapsed=176.0s

  [14724/21087] intraday_3636.csv.gz  in=385,031,634 out=113,089,395 elapsed=176.0s

  [14725/21087] intraday_3637.csv.gz  in=385,043,402 out=113,089,395 elapsed=176.0s

  [14726/21087] intraday_3638.csv.gz  in=385,056,979 out=113,089,395 elapsed=176.0s

  [14727/21087] intraday_3639.csv.gz  in=385,074,849 out=113,089,395 elapsed=176.0s

  [14728/21087] intraday_3640.csv.gz  in=385,088,902 out=113,089,395 elapsed=176.0s

  [14729/21087] intraday_3641.csv.gz  in=385,101,662 out=113,089,395 elapsed=176.0s

  [14730/21087] intraday_3642.csv.gz  in=385,114,325 out=113,089,395 elapsed=176.1s

  [14731/21087] intraday_3643.csv.gz  in=385,125,541 out=113,089,395 elapsed=176.1s

  [14732/21087] intraday_3644.csv.gz  in=385,137,043 out=113,089,395 elapsed=176.1s

  [14733/21087] intraday_3645.csv.gz  in=385,148,092 out=113,089,395 elapsed=176.1s

  [14734/21087] intraday_3646.csv.gz  in=385,161,671 out=113,089,395 elapsed=176.1s

  [14735/21087] intraday_3647.csv.gz  in=385,170,538 out=113,089,395 elapsed=176.1s

  [14736/21087] intraday_3649.csv.gz  in=385,180,612 out=113,089,395 elapsed=176.1s

  [14737/21087] intraday_3648.csv.gz  in=385,189,077 out=113,089,395 elapsed=176.1s

  [14738/21087] intraday_3650.csv.gz  in=385,204,275 out=113,089,395 elapsed=176.1s

  [14739/21087] intraday_3652.csv.gz  in=385,217,614 out=113,089,395 elapsed=176.1s

  [14740/21087] intraday_3653.csv.gz  in=385,228,015 out=113,089,395 elapsed=176.1s

  [14741/21087] intraday_3651.csv.gz  in=385,242,191 out=113,089,395 elapsed=176.1s

  [14742/21087] intraday_3654.csv.gz  in=385,256,914 out=113,089,395 elapsed=176.2s

  [14743/21087] intraday_3655.csv.gz  in=385,271,343 out=113,089,395 elapsed=176.2s

  [14744/21087] intraday_3656.csv.gz  in=385,287,405 out=113,089,395 elapsed=176.2s

  [14745/21087] intraday_3657.csv.gz  in=385,299,988 out=113,089,395 elapsed=176.2s

  [14746/21087] intraday_3658.csv.gz  in=385,314,046 out=113,089,395 elapsed=176.2s

  [14747/21087] intraday_3659.csv.gz  in=385,329,154 out=113,089,395 elapsed=176.2s

  [14748/21087] intraday_3660.csv.gz  in=385,338,845 out=113,089,395 elapsed=176.2s

  [14749/21087] intraday_3661.csv.gz  in=385,351,415 out=113,089,395 elapsed=176.2s

  [14750/21087] intraday_3663.csv.gz  in=385,362,149 out=113,089,395 elapsed=176.2s

  [14751/21087] intraday_3664.csv.gz  in=385,374,097 out=113,089,395 elapsed=176.2s

  [14752/21087] intraday_3665.csv.gz  in=385,385,705 out=113,089,395 elapsed=176.2s

  [14753/21087] intraday_3662.csv.gz  in=385,398,659 out=113,089,395 elapsed=176.2s

  [14754/21087] intraday_3666.csv.gz  in=385,411,539 out=113,089,395 elapsed=176.3s

  [14755/21087] intraday_3668.csv.gz  in=385,422,342 out=113,089,395 elapsed=176.3s

  [14756/21087] intraday_3669.csv.gz  in=385,435,603 out=113,089,395 elapsed=176.3s

  [14757/21087] intraday_3667.csv.gz  in=385,448,588 out=113,089,395 elapsed=176.3s

  [14758/21087] intraday_3670.csv.gz  in=385,462,637 out=113,089,395 elapsed=176.3s

  [14759/21087] intraday_3671.csv.gz  in=385,473,964 out=113,089,395 elapsed=176.3s

  [14760/21087] intraday_3673.csv.gz  in=385,486,143 out=113,089,395 elapsed=176.3s

  [14761/21087] intraday_3672.csv.gz  in=385,498,447 out=113,089,395 elapsed=176.3s

  [14762/21087] intraday_3674.csv.gz  in=385,510,948 out=113,089,395 elapsed=176.3s

  [14763/21087] intraday_3675.csv.gz  in=385,521,929 out=113,089,395 elapsed=176.3s

  [14764/21087] intraday_3676.csv.gz  in=385,534,541 out=113,089,395 elapsed=176.4s

  [14765/21087] intraday_3677.csv.gz  in=385,547,311 out=113,089,395 elapsed=176.4s

  [14766/21087] intraday_3678.csv.gz  in=385,561,640 out=113,089,395 elapsed=176.4s

  [14767/21087] intraday_3679.csv.gz  in=385,578,123 out=113,089,395 elapsed=176.4s

  [14768/21087] intraday_3680.csv.gz  in=385,594,561 out=113,089,395 elapsed=176.4s

  [14769/21087] intraday_3682.csv.gz  in=385,606,121 out=113,089,395 elapsed=176.4s

  [14770/21087] intraday_3681.csv.gz  in=385,617,094 out=113,089,395 elapsed=176.4s

  [14771/21087] intraday_3683.csv.gz  in=385,629,711 out=113,089,395 elapsed=176.4s

  [14772/21087] intraday_3684.csv.gz  in=385,641,487 out=113,089,395 elapsed=176.4s

  [14773/21087] intraday_3686.csv.gz  in=385,656,125 out=113,089,395 elapsed=176.4s

  [14774/21087] intraday_3685.csv.gz  in=385,669,181 out=113,089,395 elapsed=176.4s

  [14775/21087] intraday_3687.csv.gz  in=385,678,887 out=113,089,395 elapsed=176.4s

  [14776/21087] intraday_3688.csv.gz  in=385,692,204 out=113,089,395 elapsed=176.5s

  [14777/21087] intraday_3689.csv.gz  in=385,702,630 out=113,089,395 elapsed=176.5s

  [14778/21087] intraday_3690.csv.gz  in=385,716,365 out=113,089,395 elapsed=176.5s

  [14779/21087] intraday_3691.csv.gz  in=385,728,706 out=113,089,395 elapsed=176.5s

  [14780/21087] intraday_3692.csv.gz  in=385,740,718 out=113,089,395 elapsed=176.5s

  [14781/21087] intraday_3693.csv.gz  in=385,752,396 out=113,089,395 elapsed=176.5s

  [14782/21087] intraday_3694.csv.gz  in=385,763,639 out=113,089,395 elapsed=176.5s

  [14783/21087] intraday_3695.csv.gz  in=385,776,897 out=113,089,395 elapsed=176.5s

  [14784/21087] intraday_3696.csv.gz  in=385,787,716 out=113,089,395 elapsed=176.5s

  [14785/21087] intraday_3697.csv.gz  in=385,799,876 out=113,089,395 elapsed=176.6s

  [14786/21087] intraday_3698.csv.gz  in=385,811,986 out=113,089,395 elapsed=176.6s

  [14787/21087] intraday_3699.csv.gz  in=385,823,250 out=113,089,395 elapsed=176.6s

  [14788/21087] intraday_3700.csv.gz  in=385,835,200 out=113,089,395 elapsed=176.6s

  [14789/21087] intraday_3701.csv.gz  in=385,849,779 out=113,089,395 elapsed=176.6s

  [14790/21087] intraday_3702.csv.gz  in=385,859,688 out=113,089,395 elapsed=176.6s

  [14791/21087] intraday_3703.csv.gz  in=385,873,338 out=113,089,395 elapsed=176.6s

  [14792/21087] intraday_3704.csv.gz  in=385,884,950 out=113,089,395 elapsed=176.6s

  [14793/21087] intraday_3706.csv.gz  in=385,895,828 out=113,089,395 elapsed=176.6s

  [14794/21087] intraday_3705.csv.gz  in=385,906,690 out=113,089,395 elapsed=176.6s

  [14795/21087] intraday_3708.csv.gz  in=385,919,990 out=113,089,395 elapsed=176.7s

  [14796/21087] intraday_3710.csv.gz  in=385,931,003 out=113,089,395 elapsed=176.7s

  [14797/21087] intraday_3709.csv.gz  in=385,942,798 out=113,089,395 elapsed=176.7s

  [14798/21087] intraday_3707.csv.gz  in=385,957,563 out=113,089,395 elapsed=176.7s

  [14799/21087] intraday_3714.csv.gz  in=385,970,901 out=113,089,395 elapsed=176.7s

  [14800/21087] intraday_3712.csv.gz  in=385,981,047 out=113,089,395 elapsed=176.7s

  [14801/21087] intraday_3713.csv.gz  in=385,997,770 out=113,089,395 elapsed=176.7s

  [14802/21087] intraday_3711.csv.gz  in=386,020,265 out=113,089,395 elapsed=176.7s

  [14803/21087] intraday_3715.csv.gz  in=386,032,768 out=113,089,395 elapsed=176.7s

  [14804/21087] intraday_3716.csv.gz  in=386,044,940 out=113,089,395 elapsed=176.7s

  [14805/21087] intraday_3718.csv.gz  in=386,054,836 out=113,089,395 elapsed=176.7s

  [14806/21087] intraday_3717.csv.gz  in=386,070,582 out=113,089,395 elapsed=176.8s

  [14807/21087] intraday_3719.csv.gz  in=386,082,627 out=113,089,395 elapsed=176.8s

  [14808/21087] intraday_3720.csv.gz  in=386,094,427 out=113,089,395 elapsed=176.8s

  [14809/21087] intraday_3722.csv.gz  in=386,104,858 out=113,089,395 elapsed=176.8s

  [14810/21087] intraday_3721.csv.gz  in=386,118,150 out=113,089,395 elapsed=176.8s

  [14811/21087] intraday_3723.csv.gz  in=386,130,302 out=113,089,395 elapsed=176.8s

  [14812/21087] intraday_3724.csv.gz  in=386,142,270 out=113,089,395 elapsed=176.8s

  [14813/21087] intraday_3725.csv.gz  in=386,155,170 out=113,089,395 elapsed=176.8s

  [14814/21087] intraday_3726.csv.gz  in=386,167,624 out=113,089,395 elapsed=176.8s

  [14815/21087] intraday_3727.csv.gz  in=386,181,247 out=113,089,395 elapsed=176.8s

  [14816/21087] intraday_3728.csv.gz  in=386,193,656 out=113,089,395 elapsed=176.8s

  [14817/21087] intraday_3729.csv.gz  in=386,207,147 out=113,089,395 elapsed=176.8s

  [14818/21087] intraday_3730.csv.gz  in=386,217,561 out=113,089,395 elapsed=176.8s

  [14819/21087] intraday_3731.csv.gz  in=386,234,066 out=113,089,395 elapsed=176.8s

  [14820/21087] intraday_3732.csv.gz  in=386,246,564 out=113,089,395 elapsed=176.9s

  [14821/21087] intraday_3733.csv.gz  in=386,258,658 out=113,089,395 elapsed=176.9s

  [14822/21087] intraday_3734.csv.gz  in=386,269,458 out=113,089,395 elapsed=176.9s

  [14823/21087] intraday_3735.csv.gz  in=386,281,392 out=113,089,395 elapsed=176.9s

  [14824/21087] intraday_3736.csv.gz  in=386,295,377 out=113,089,395 elapsed=176.9s

  [14825/21087] intraday_3737.csv.gz  in=386,310,138 out=113,089,395 elapsed=176.9s

  [14826/21087] intraday_3738.csv.gz  in=386,324,199 out=113,089,395 elapsed=176.9s

  [14827/21087] intraday_3739.csv.gz  in=386,334,991 out=113,089,395 elapsed=176.9s

  [14828/21087] intraday_3740.csv.gz  in=386,350,799 out=113,089,395 elapsed=176.9s

  [14829/21087] intraday_3741.csv.gz  in=386,365,047 out=113,089,395 elapsed=176.9s

  [14830/21087] intraday_3743.csv.gz  in=386,376,870 out=113,089,395 elapsed=176.9s

  [14831/21087] intraday_3742.csv.gz  in=386,390,933 out=113,089,395 elapsed=176.9s

  [14832/21087] intraday_3744.csv.gz  in=386,403,684 out=113,089,395 elapsed=176.9s

  [14833/21087] intraday_3745.csv.gz  in=386,415,472 out=113,089,395 elapsed=177.0s

  [14834/21087] intraday_3746.csv.gz  in=386,428,695 out=113,089,395 elapsed=177.0s

  [14835/21087] intraday_3747.csv.gz  in=386,441,154 out=113,089,395 elapsed=177.0s

  [14836/21087] intraday_3748.csv.gz  in=386,453,104 out=113,089,395 elapsed=177.0s

  [14837/21087] intraday_3751.csv.gz  in=386,466,629 out=113,089,395 elapsed=177.0s

  [14838/21087] intraday_3749.csv.gz  in=386,481,895 out=113,089,395 elapsed=177.0s

  [14839/21087] intraday_3750.csv.gz  in=386,495,419 out=113,089,395 elapsed=177.0s

  [14840/21087] intraday_3755.csv.gz  in=386,509,472 out=113,089,395 elapsed=177.0s

  [14841/21087] intraday_3754.csv.gz  in=386,521,378 out=113,089,395 elapsed=177.0s

  [14842/21087] intraday_3752.csv.gz  in=386,534,282 out=113,089,395 elapsed=177.0s

  [14843/21087] intraday_3753.csv.gz  in=386,550,082 out=113,089,395 elapsed=177.1s

  [14844/21087] intraday_3758.csv.gz  in=386,562,614 out=113,089,395 elapsed=177.1s

  [14845/21087] intraday_3759.csv.gz  in=386,575,031 out=113,089,395 elapsed=177.1s

  [14846/21087] intraday_3756.csv.gz  in=386,589,858 out=113,089,395 elapsed=177.1s

  [14847/21087] intraday_3757.csv.gz  in=386,604,018 out=113,089,395 elapsed=177.1s

  [14848/21087] intraday_3761.csv.gz  in=386,616,533 out=113,089,395 elapsed=177.1s

  [14849/21087] intraday_3762.csv.gz  in=386,632,061 out=113,089,395 elapsed=177.1s

  [14850/21087] intraday_3763.csv.gz  in=386,649,256 out=113,089,395 elapsed=177.1s

  [14851/21087] intraday_3760.csv.gz  in=386,673,118 out=113,089,395 elapsed=177.1s

  [14852/21087] intraday_3764.csv.gz  in=386,687,437 out=113,089,395 elapsed=177.1s

  [14853/21087] intraday_3765.csv.gz  in=386,702,835 out=113,089,395 elapsed=177.2s

  [14854/21087] intraday_3766.csv.gz  in=386,722,193 out=113,089,395 elapsed=177.2s

  [14855/21087] intraday_3767.csv.gz  in=386,735,851 out=113,089,395 elapsed=177.2s

  [14856/21087] intraday_3768.csv.gz  in=386,747,983 out=113,089,395 elapsed=177.2s

  [14857/21087] intraday_3769.csv.gz  in=386,765,632 out=113,089,395 elapsed=177.2s

  [14858/21087] intraday_3770.csv.gz  in=386,776,976 out=113,089,395 elapsed=177.2s

  [14859/21087] intraday_3771.csv.gz  in=386,789,525 out=113,089,395 elapsed=177.2s

  [14860/21087] intraday_3773.csv.gz  in=386,802,292 out=113,089,395 elapsed=177.2s

  [14861/21087] intraday_3772.csv.gz  in=386,815,367 out=113,089,395 elapsed=177.2s

  [14862/21087] intraday_3774.csv.gz  in=386,830,788 out=113,089,395 elapsed=177.2s

  [14863/21087] intraday_3775.csv.gz  in=386,842,933 out=113,089,395 elapsed=177.2s

  [14864/21087] intraday_3776.csv.gz  in=386,855,358 out=113,089,395 elapsed=177.2s

  [14865/21087] intraday_3777.csv.gz  in=386,869,096 out=113,089,395 elapsed=177.3s

  [14866/21087] intraday_3778.csv.gz  in=386,881,390 out=113,089,395 elapsed=177.3s

  [14867/21087] intraday_3779.csv.gz  in=386,894,098 out=113,089,395 elapsed=177.3s

  [14868/21087] intraday_3780.csv.gz  in=386,908,774 out=113,089,395 elapsed=177.3s

  [14869/21087] intraday_3781.csv.gz  in=386,922,659 out=113,089,395 elapsed=177.3s

  [14870/21087] intraday_3783.csv.gz  in=386,935,320 out=113,089,395 elapsed=177.3s

  [14871/21087] intraday_3782.csv.gz  in=386,948,869 out=113,089,395 elapsed=177.3s

  [14872/21087] intraday_3784.csv.gz  in=386,960,389 out=113,089,395 elapsed=177.3s

  [14873/21087] intraday_3785.csv.gz  in=386,972,134 out=113,089,395 elapsed=177.3s

  [14874/21087] intraday_3788.csv.gz  in=386,979,369 out=113,089,395 elapsed=177.3s

  [14875/21087] intraday_3786.csv.gz  in=386,990,595 out=113,089,395 elapsed=177.3s

  [14876/21087] intraday_3787.csv.gz  in=387,004,776 out=113,089,395 elapsed=177.3s

  [14877/21087] intraday_3789.csv.gz  in=387,016,348 out=113,089,395 elapsed=177.3s

  [14878/21087] intraday_3790.csv.gz  in=387,024,727 out=113,089,395 elapsed=177.4s

  [14879/21087] intraday_3791.csv.gz  in=387,040,215 out=113,089,395 elapsed=177.4s

  [14880/21087] intraday_3792.csv.gz  in=387,055,408 out=113,089,395 elapsed=177.4s

  [14881/21087] intraday_3793.csv.gz  in=387,068,201 out=113,089,395 elapsed=177.4s

  [14882/21087] intraday_3794.csv.gz  in=387,078,364 out=113,089,395 elapsed=177.4s

  [14883/21087] intraday_3797.csv.gz  in=387,090,791 out=113,089,395 elapsed=177.4s

  [14884/21087] intraday_3796.csv.gz  in=387,105,249 out=113,089,395 elapsed=177.4s

  [14885/21087] intraday_3798.csv.gz  in=387,117,173 out=113,089,395 elapsed=177.4s

  [14886/21087] intraday_3795.csv.gz  in=387,133,159 out=113,089,395 elapsed=177.4s

  [14887/21087] intraday_3799.csv.gz  in=387,147,949 out=113,089,395 elapsed=177.4s

  [14888/21087] intraday_3801.csv.gz  in=387,157,795 out=113,089,395 elapsed=177.5s

  [14889/21087] intraday_3802.csv.gz  in=387,169,552 out=113,089,395 elapsed=177.5s

  [14890/21087] intraday_3800.csv.gz  in=387,184,966 out=113,089,395 elapsed=177.5s

  [14891/21087] intraday_3803.csv.gz  in=387,198,127 out=113,089,395 elapsed=177.5s

  [14892/21087] intraday_3804.csv.gz  in=387,208,534 out=113,089,395 elapsed=177.5s

  [14893/21087] intraday_3805.csv.gz  in=387,219,926 out=113,089,395 elapsed=177.5s

  [14894/21087] intraday_3806.csv.gz  in=387,231,487 out=113,089,395 elapsed=177.5s

  [14895/21087] intraday_3807.csv.gz  in=387,244,556 out=113,089,395 elapsed=177.5s

  [14896/21087] intraday_3808.csv.gz  in=387,257,764 out=113,089,395 elapsed=177.5s

  [14897/21087] intraday_3809.csv.gz  in=387,268,321 out=113,089,395 elapsed=177.5s

  [14898/21087] intraday_3810.csv.gz  in=387,281,287 out=113,089,395 elapsed=177.5s

  [14899/21087] intraday_3811.csv.gz  in=387,295,740 out=113,089,395 elapsed=177.5s

  [14900/21087] intraday_3812.csv.gz  in=387,307,644 out=113,089,395 elapsed=177.6s

  [14901/21087] intraday_3813.csv.gz  in=387,319,783 out=113,089,395 elapsed=177.6s

  [14902/21087] intraday_3814.csv.gz  in=387,331,903 out=113,089,395 elapsed=177.6s

  [14903/21087] intraday_3815.csv.gz  in=387,344,346 out=113,089,395 elapsed=177.6s

  [14904/21087] intraday_3816.csv.gz  in=387,353,909 out=113,089,395 elapsed=177.6s

  [14905/21087] intraday_3817.csv.gz  in=387,366,899 out=113,089,395 elapsed=177.6s

  [14906/21087] intraday_3818.csv.gz  in=387,379,743 out=113,089,395 elapsed=177.6s

  [14907/21087] intraday_3820.csv.gz  in=387,394,606 out=113,089,395 elapsed=177.6s

  [14908/21087] intraday_3821.csv.gz  in=387,409,683 out=113,089,395 elapsed=177.6s

  [14909/21087] intraday_3819.csv.gz  in=387,429,327 out=113,089,395 elapsed=177.6s

  [14910/21087] intraday_3822.csv.gz  in=387,441,236 out=113,089,395 elapsed=177.6s

  [14911/21087] intraday_3823.csv.gz  in=387,453,481 out=113,089,395 elapsed=177.6s

  [14912/21087] intraday_3825.csv.gz  in=387,465,102 out=113,089,395 elapsed=177.7s

  [14913/21087] intraday_3826.csv.gz  in=387,478,668 out=113,089,395 elapsed=177.7s

  [14914/21087] intraday_3824.csv.gz  in=387,492,015 out=113,089,395 elapsed=177.7s

  [14915/21087] intraday_3827.csv.gz  in=387,502,393 out=113,089,395 elapsed=177.7s

  [14916/21087] intraday_3828.csv.gz  in=387,512,991 out=113,089,395 elapsed=177.7s

  [14917/21087] intraday_3829.csv.gz  in=387,524,427 out=113,089,395 elapsed=177.7s

  [14918/21087] intraday_3830.csv.gz  in=387,534,444 out=113,089,395 elapsed=177.7s

  [14919/21087] intraday_3831.csv.gz  in=387,549,115 out=113,089,395 elapsed=177.7s

  [14920/21087] intraday_3832.csv.gz  in=387,561,284 out=113,089,395 elapsed=177.7s

  [14921/21087] intraday_3833.csv.gz  in=387,583,305 out=113,089,395 elapsed=177.7s

  [14922/21087] intraday_3835.csv.gz  in=387,594,462 out=113,089,395 elapsed=177.7s

  [14923/21087] intraday_3836.csv.gz  in=387,607,591 out=113,089,395 elapsed=177.8s

  [14924/21087] intraday_3834.csv.gz  in=387,619,446 out=113,089,395 elapsed=177.8s

  [14925/21087] intraday_3837.csv.gz  in=387,630,642 out=113,089,395 elapsed=177.8s

  [14926/21087] intraday_3839.csv.gz  in=387,645,992 out=113,089,395 elapsed=177.8s

  [14927/21087] intraday_3838.csv.gz  in=387,658,270 out=113,089,395 elapsed=177.8s

  [14928/21087] intraday_3840.csv.gz  in=387,669,375 out=113,089,395 elapsed=177.8s

  [14929/21087] intraday_3841.csv.gz  in=387,680,461 out=113,089,395 elapsed=177.8s

  [14930/21087] intraday_3843.csv.gz  in=387,691,276 out=113,089,395 elapsed=177.8s

  [14931/21087] intraday_3842.csv.gz  in=387,703,106 out=113,089,395 elapsed=177.8s

  [14932/21087] intraday_3844.csv.gz  in=387,715,174 out=113,089,395 elapsed=177.8s

  [14933/21087] intraday_3845.csv.gz  in=387,728,126 out=113,089,395 elapsed=177.8s

  [14934/21087] intraday_3846.csv.gz  in=387,739,507 out=113,089,395 elapsed=177.9s

  [14935/21087] intraday_3847.csv.gz  in=387,750,053 out=113,089,395 elapsed=177.9s

  [14936/21087] intraday_3848.csv.gz  in=387,763,938 out=113,089,395 elapsed=177.9s

  [14937/21087] intraday_3849.csv.gz  in=387,777,638 out=113,089,395 elapsed=177.9s

  [14938/21087] intraday_3850.csv.gz  in=387,795,104 out=113,089,395 elapsed=177.9s

  [14939/21087] intraday_3852.csv.gz  in=387,807,873 out=113,089,395 elapsed=177.9s

  [14940/21087] intraday_3851.csv.gz  in=387,818,949 out=113,089,395 elapsed=177.9s

  [14941/21087] intraday_3853.csv.gz  in=387,830,524 out=113,089,395 elapsed=177.9s

  [14942/21087] intraday_3854.csv.gz  in=387,845,204 out=113,089,395 elapsed=177.9s

  [14943/21087] intraday_3856.csv.gz  in=387,856,509 out=113,089,395 elapsed=177.9s

  [14944/21087] intraday_3855.csv.gz  in=387,872,174 out=113,089,395 elapsed=177.9s

  [14945/21087] intraday_3858.csv.gz  in=387,885,282 out=113,089,395 elapsed=178.0s

  [14946/21087] intraday_3857.csv.gz  in=387,898,551 out=113,089,395 elapsed=178.0s

  [14947/21087] intraday_3860.csv.gz  in=387,909,840 out=113,089,395 elapsed=178.0s

  [14948/21087] intraday_3859.csv.gz  in=387,920,177 out=113,089,395 elapsed=178.0s

  [14949/21087] intraday_3861.csv.gz  in=387,931,675 out=113,089,395 elapsed=178.0s

  [14950/21087] intraday_3863.csv.gz  in=387,941,723 out=113,089,395 elapsed=178.0s

  [14951/21087] intraday_3862.csv.gz  in=387,955,270 out=113,089,395 elapsed=178.0s

  [14952/21087] intraday_3864.csv.gz  in=387,967,731 out=113,089,395 elapsed=178.0s

  [14953/21087] intraday_3865.csv.gz  in=387,979,147 out=113,089,395 elapsed=178.0s

  [14954/21087] intraday_3867.csv.gz  in=387,992,408 out=113,089,395 elapsed=178.0s

  [14955/21087] intraday_3866.csv.gz  in=388,005,279 out=113,089,395 elapsed=178.0s

  [14956/21087] intraday_3868.csv.gz  in=388,018,404 out=113,089,395 elapsed=178.0s

  [14957/21087] intraday_3869.csv.gz  in=388,030,113 out=113,089,395 elapsed=178.0s

  [14958/21087] intraday_3870.csv.gz  in=388,041,186 out=113,089,395 elapsed=178.1s

  [14959/21087] intraday_3871.csv.gz  in=388,051,697 out=113,089,395 elapsed=178.1s

  [14960/21087] intraday_3872.csv.gz  in=388,069,064 out=113,089,395 elapsed=178.1s

  [14961/21087] intraday_3873.csv.gz  in=388,088,844 out=113,089,395 elapsed=178.1s

  [14962/21087] intraday_3874.csv.gz  in=388,101,283 out=113,089,395 elapsed=178.1s

  [14963/21087] intraday_3875.csv.gz  in=388,111,727 out=113,089,395 elapsed=178.1s

  [14964/21087] intraday_3876.csv.gz  in=388,124,559 out=113,089,395 elapsed=178.1s

  [14965/21087] intraday_3877.csv.gz  in=388,138,292 out=113,089,395 elapsed=178.1s

  [14966/21087] intraday_3878.csv.gz  in=388,152,898 out=113,089,395 elapsed=178.1s

  [14967/21087] intraday_3879.csv.gz  in=388,166,600 out=113,089,395 elapsed=178.1s

  [14968/21087] intraday_3880.csv.gz  in=388,177,616 out=113,089,395 elapsed=178.1s

  [14969/21087] intraday_3881.csv.gz  in=388,199,387 out=113,089,395 elapsed=178.2s

  [14970/21087] intraday_3882.csv.gz  in=388,214,242 out=113,089,395 elapsed=178.2s

  [14971/21087] intraday_3883.csv.gz  in=388,230,428 out=113,089,395 elapsed=178.2s

  [14972/21087] intraday_3884.csv.gz  in=388,242,462 out=113,089,395 elapsed=178.2s

  [14973/21087] intraday_3886.csv.gz  in=388,254,184 out=113,089,395 elapsed=178.2s

  [14974/21087] intraday_3885.csv.gz  in=388,266,337 out=113,089,395 elapsed=178.2s

  [14975/21087] intraday_3887.csv.gz  in=388,279,789 out=113,089,395 elapsed=178.2s

  [14976/21087] intraday_3888.csv.gz  in=388,291,968 out=113,089,395 elapsed=178.2s

  [14977/21087] intraday_3889.csv.gz  in=388,304,470 out=113,089,395 elapsed=178.2s

  [14978/21087] intraday_3890.csv.gz  in=388,317,214 out=113,089,395 elapsed=178.2s

  [14979/21087] intraday_3891.csv.gz  in=388,331,410 out=113,089,395 elapsed=178.2s

  [14980/21087] intraday_3892.csv.gz  in=388,345,951 out=113,089,395 elapsed=178.2s

  [14981/21087] intraday_3893.csv.gz  in=388,359,470 out=113,089,395 elapsed=178.2s

  [14982/21087] intraday_3894.csv.gz  in=388,376,088 out=113,089,395 elapsed=178.3s

  [14983/21087] intraday_3895.csv.gz  in=388,387,563 out=113,089,395 elapsed=178.3s

  [14984/21087] intraday_3896.csv.gz  in=388,399,728 out=113,089,395 elapsed=178.3s

  [14985/21087] intraday_3898.csv.gz  in=388,414,428 out=113,089,395 elapsed=178.3s

  [14986/21087] intraday_3897.csv.gz  in=388,429,683 out=113,089,395 elapsed=178.3s

  [14987/21087] intraday_3899.csv.gz  in=388,440,667 out=113,089,395 elapsed=178.3s

  [14988/21087] intraday_3900.csv.gz  in=388,454,952 out=113,089,395 elapsed=178.3s

  [14989/21087] intraday_3901.csv.gz  in=388,467,490 out=113,089,395 elapsed=178.3s

  [14990/21087] intraday_3902.csv.gz  in=388,480,413 out=113,089,395 elapsed=178.3s

  [14991/21087] intraday_3904.csv.gz  in=388,494,513 out=113,089,395 elapsed=178.3s

  [14992/21087] intraday_3903.csv.gz  in=388,509,474 out=113,089,395 elapsed=178.3s

  [14993/21087] intraday_3905.csv.gz  in=388,526,519 out=113,089,395 elapsed=178.3s

  [14994/21087] intraday_3906.csv.gz  in=388,541,974 out=113,089,395 elapsed=178.3s

  [14995/21087] intraday_3907.csv.gz  in=388,553,378 out=113,089,395 elapsed=178.4s

  [14996/21087] intraday_3908.csv.gz  in=388,566,763 out=113,089,395 elapsed=178.4s

  [14997/21087] intraday_3909.csv.gz  in=388,579,275 out=113,089,395 elapsed=178.4s

  [14998/21087] intraday_3910.csv.gz  in=388,591,097 out=113,089,395 elapsed=178.4s

  [14999/21087] intraday_3911.csv.gz  in=388,602,247 out=113,089,395 elapsed=178.4s

  [15000/21087] intraday_3912.csv.gz  in=388,614,062 out=113,089,395 elapsed=178.4s

  [15001/21087] intraday_3913.csv.gz  in=388,627,822 out=113,089,395 elapsed=178.4s

  [15002/21087] intraday_3914.csv.gz  in=388,640,487 out=113,089,395 elapsed=178.4s

  [15003/21087] intraday_3916.csv.gz  in=388,652,264 out=113,089,395 elapsed=178.4s

  [15004/21087] intraday_3915.csv.gz  in=388,668,961 out=113,089,395 elapsed=178.4s

  [15005/21087] intraday_3918.csv.gz  in=388,682,255 out=113,089,395 elapsed=178.4s

  [15006/21087] intraday_3917.csv.gz  in=388,694,637 out=113,089,395 elapsed=178.4s

  [15007/21087] intraday_3919.csv.gz  in=388,706,495 out=113,089,395 elapsed=178.4s

  [15008/21087] intraday_3920.csv.gz  in=388,718,908 out=113,089,395 elapsed=178.5s

  [15009/21087] intraday_3921.csv.gz  in=388,733,657 out=113,089,395 elapsed=178.5s

  [15010/21087] intraday_3922.csv.gz  in=388,747,147 out=113,089,395 elapsed=178.5s

  [15011/21087] intraday_3923.csv.gz  in=388,760,818 out=113,089,395 elapsed=178.5s

  [15012/21087] intraday_3924.csv.gz  in=388,774,037 out=113,089,395 elapsed=178.5s

  [15013/21087] intraday_3925.csv.gz  in=388,785,801 out=113,089,395 elapsed=178.5s

  [15014/21087] intraday_3926.csv.gz  in=388,799,085 out=113,089,395 elapsed=178.5s

  [15015/21087] intraday_3927.csv.gz  in=388,809,663 out=113,089,395 elapsed=178.5s

  [15016/21087] intraday_3928.csv.gz  in=388,823,611 out=113,089,395 elapsed=178.5s

  [15017/21087] intraday_3929.csv.gz  in=388,832,080 out=113,089,395 elapsed=178.5s

  [15018/21087] intraday_3930.csv.gz  in=388,841,560 out=113,089,395 elapsed=178.5s

  [15019/21087] intraday_3931.csv.gz  in=388,852,504 out=113,089,395 elapsed=178.5s

  [15020/21087] intraday_3932.csv.gz  in=388,868,823 out=113,089,395 elapsed=178.6s

  [15021/21087] intraday_3933.csv.gz  in=388,883,482 out=113,089,395 elapsed=178.6s

  [15022/21087] intraday_3934.csv.gz  in=388,896,453 out=113,089,395 elapsed=178.6s

  [15023/21087] intraday_3935.csv.gz  in=388,907,125 out=113,089,395 elapsed=178.6s

  [15024/21087] intraday_3938.csv.gz  in=388,919,930 out=113,089,395 elapsed=178.6s

  [15025/21087] intraday_3936.csv.gz  in=388,935,120 out=113,089,395 elapsed=178.6s

  [15026/21087] intraday_3937.csv.gz  in=388,949,943 out=113,089,395 elapsed=178.6s

  [15027/21087] intraday_3939.csv.gz  in=388,962,890 out=113,089,395 elapsed=178.6s

  [15028/21087] intraday_3942.csv.gz  in=388,972,873 out=113,089,395 elapsed=178.6s

  [15029/21087] intraday_3940.csv.gz  in=388,987,774 out=113,089,395 elapsed=178.6s

  [15030/21087] intraday_3941.csv.gz  in=389,003,783 out=113,089,395 elapsed=178.6s

  [15031/21087] intraday_3943.csv.gz  in=389,017,390 out=113,089,395 elapsed=178.6s

  [15032/21087] intraday_3944.csv.gz  in=389,030,713 out=113,089,395 elapsed=178.7s

  [15033/21087] intraday_3945.csv.gz  in=389,042,732 out=113,089,395 elapsed=178.7s

  [15034/21087] intraday_3946.csv.gz  in=389,053,879 out=113,089,395 elapsed=178.7s

  [15035/21087] intraday_3947.csv.gz  in=389,067,088 out=113,089,395 elapsed=178.7s

  [15036/21087] intraday_3948.csv.gz  in=389,079,345 out=113,089,395 elapsed=178.7s

  [15037/21087] intraday_3949.csv.gz  in=389,092,767 out=113,089,395 elapsed=178.7s

  [15038/21087] intraday_3950.csv.gz  in=389,104,951 out=113,089,395 elapsed=178.7s

  [15039/21087] intraday_3951.csv.gz  in=389,119,287 out=113,089,395 elapsed=178.7s

  [15040/21087] intraday_3952.csv.gz  in=389,133,202 out=113,089,395 elapsed=178.7s

  [15041/21087] intraday_3953.csv.gz  in=389,146,454 out=113,089,395 elapsed=178.7s

  [15042/21087] intraday_3954.csv.gz  in=389,159,046 out=113,089,395 elapsed=178.7s

  [15043/21087] intraday_3955.csv.gz  in=389,172,138 out=113,089,395 elapsed=178.7s

  [15044/21087] intraday_3956.csv.gz  in=389,184,441 out=113,089,395 elapsed=178.8s

  [15045/21087] intraday_3957.csv.gz  in=389,195,058 out=113,089,395 elapsed=178.8s

  [15046/21087] intraday_3958.csv.gz  in=389,207,981 out=113,089,395 elapsed=178.8s

  [15047/21087] intraday_3959.csv.gz  in=389,221,851 out=113,089,395 elapsed=178.8s

  [15048/21087] intraday_3960.csv.gz  in=389,236,439 out=113,089,395 elapsed=178.8s

  [15049/21087] intraday_3961.csv.gz  in=389,252,154 out=113,089,395 elapsed=178.8s

  [15050/21087] intraday_3962.csv.gz  in=389,265,744 out=113,089,395 elapsed=178.8s

  [15051/21087] intraday_3963.csv.gz  in=389,277,870 out=113,089,395 elapsed=178.8s

  [15052/21087] intraday_3964.csv.gz  in=389,291,120 out=113,089,395 elapsed=178.8s

  [15053/21087] intraday_3965.csv.gz  in=389,305,821 out=113,089,395 elapsed=178.8s

  [15054/21087] intraday_3966.csv.gz  in=389,317,549 out=113,089,395 elapsed=178.8s

  [15055/21087] intraday_3967.csv.gz  in=389,330,888 out=113,089,395 elapsed=178.8s

  [15056/21087] intraday_3968.csv.gz  in=389,342,583 out=113,089,395 elapsed=178.8s

  [15057/21087] intraday_3969.csv.gz  in=389,353,783 out=113,089,395 elapsed=178.8s

  [15058/21087] intraday_3970.csv.gz  in=389,365,626 out=113,089,395 elapsed=178.9s

  [15059/21087] intraday_3971.csv.gz  in=389,378,812 out=113,089,395 elapsed=178.9s

  [15060/21087] intraday_3972.csv.gz  in=389,391,784 out=113,089,395 elapsed=178.9s

  [15061/21087] intraday_3973.csv.gz  in=389,404,765 out=113,089,395 elapsed=178.9s

  [15062/21087] intraday_3974.csv.gz  in=389,418,556 out=113,089,395 elapsed=178.9s

  [15063/21087] intraday_3975.csv.gz  in=389,430,562 out=113,089,395 elapsed=178.9s

  [15064/21087] intraday_3976.csv.gz  in=389,443,640 out=113,089,395 elapsed=178.9s

  [15065/21087] intraday_3977.csv.gz  in=389,456,223 out=113,089,395 elapsed=178.9s

  [15066/21087] intraday_3978.csv.gz  in=389,467,900 out=113,089,395 elapsed=178.9s

  [15067/21087] intraday_3981.csv.gz  in=389,478,555 out=113,089,395 elapsed=178.9s

  [15068/21087] intraday_3980.csv.gz  in=389,490,450 out=113,089,395 elapsed=178.9s

  [15069/21087] intraday_3979.csv.gz  in=389,503,271 out=113,089,395 elapsed=178.9s

  [15070/21087] intraday_3982.csv.gz  in=389,516,958 out=113,089,395 elapsed=179.0s

  [15071/21087] intraday_3984.csv.gz  in=389,527,997 out=113,089,395 elapsed=179.0s

  [15072/21087] intraday_3983.csv.gz  in=389,538,676 out=113,089,395 elapsed=179.0s

  [15073/21087] intraday_3985.csv.gz  in=389,552,793 out=113,089,395 elapsed=179.0s

  [15074/21087] intraday_3986.csv.gz  in=389,565,081 out=113,089,395 elapsed=179.0s

  [15075/21087] intraday_3987.csv.gz  in=389,577,352 out=113,089,395 elapsed=179.0s

  [15076/21087] intraday_3988.csv.gz  in=389,588,365 out=113,089,395 elapsed=179.0s

  [15077/21087] intraday_3989.csv.gz  in=389,603,534 out=113,089,395 elapsed=179.0s

  [15078/21087] intraday_3990.csv.gz  in=389,616,060 out=113,089,395 elapsed=179.0s

  [15079/21087] intraday_3991.csv.gz  in=389,628,538 out=113,089,395 elapsed=179.0s

  [15080/21087] intraday_3992.csv.gz  in=389,641,504 out=113,089,395 elapsed=179.0s

  [15081/21087] intraday_3993.csv.gz  in=389,654,484 out=113,089,395 elapsed=179.0s

  [15082/21087] intraday_3994.csv.gz  in=389,666,468 out=113,089,395 elapsed=179.1s

  [15083/21087] intraday_3996.csv.gz  in=389,680,764 out=113,089,395 elapsed=179.1s

  [15084/21087] intraday_3995.csv.gz  in=389,695,698 out=113,089,395 elapsed=179.1s

  [15085/21087] intraday_3997.csv.gz  in=389,709,110 out=113,089,395 elapsed=179.1s

  [15086/21087] intraday_3998.csv.gz  in=389,722,582 out=113,089,395 elapsed=179.1s

  [15087/21087] intraday_3999.csv.gz  in=389,733,319 out=113,089,395 elapsed=179.1s

  [15088/21087] intraday_4001.csv.gz  in=389,744,757 out=113,089,395 elapsed=179.1s

  [15089/21087] intraday_4000.csv.gz  in=389,757,473 out=113,089,395 elapsed=179.1s

  [15090/21087] intraday_4002.csv.gz  in=389,770,279 out=113,089,395 elapsed=179.1s

  [15091/21087] intraday_4003.csv.gz  in=389,784,519 out=113,089,395 elapsed=179.1s

  [15092/21087] intraday_4005.csv.gz  in=389,794,380 out=113,089,395 elapsed=179.1s

  [15093/21087] intraday_4004.csv.gz  in=389,806,628 out=113,089,395 elapsed=179.1s

  [15094/21087] intraday_4006.csv.gz  in=389,819,035 out=113,089,395 elapsed=179.1s

  [15095/21087] intraday_4007.csv.gz  in=389,834,703 out=113,089,395 elapsed=179.2s

  [15096/21087] intraday_4008.csv.gz  in=389,846,739 out=113,089,395 elapsed=179.2s

  [15097/21087] intraday_4010.csv.gz  in=389,858,090 out=113,089,395 elapsed=179.2s

  [15098/21087] intraday_4009.csv.gz  in=389,870,540 out=113,089,395 elapsed=179.2s

  [15099/21087] intraday_4011.csv.gz  in=389,882,535 out=113,089,395 elapsed=179.2s

  [15100/21087] intraday_4012.csv.gz  in=389,896,550 out=113,089,395 elapsed=179.2s

  [15101/21087] intraday_4013.csv.gz  in=389,912,543 out=113,089,395 elapsed=179.2s

  [15102/21087] intraday_4015.csv.gz  in=389,924,448 out=113,089,395 elapsed=179.2s

  [15103/21087] intraday_4014.csv.gz  in=389,936,519 out=113,089,395 elapsed=179.2s

  [15104/21087] intraday_4016.csv.gz  in=389,948,241 out=113,089,395 elapsed=179.2s

  [15105/21087] intraday_4017.csv.gz  in=389,962,338 out=113,089,395 elapsed=179.2s

  [15106/21087] intraday_4019.csv.gz  in=389,977,224 out=113,089,395 elapsed=179.2s

  [15107/21087] intraday_4018.csv.gz  in=389,991,916 out=113,089,395 elapsed=179.3s

  [15108/21087] intraday_4020.csv.gz  in=390,002,906 out=113,089,395 elapsed=179.3s

  [15109/21087] intraday_4021.csv.gz  in=390,017,450 out=113,089,395 elapsed=179.3s

  [15110/21087] intraday_4022.csv.gz  in=390,033,773 out=113,089,395 elapsed=179.3s

  [15111/21087] intraday_4023.csv.gz  in=390,047,599 out=113,089,395 elapsed=179.3s

  [15112/21087] intraday_4024.csv.gz  in=390,062,597 out=113,089,395 elapsed=179.3s

  [15113/21087] intraday_4025.csv.gz  in=390,074,724 out=113,089,395 elapsed=179.3s

  [15114/21087] intraday_4026.csv.gz  in=390,087,061 out=113,089,395 elapsed=179.3s

  [15115/21087] intraday_4027.csv.gz  in=390,100,312 out=113,089,395 elapsed=179.3s

  [15116/21087] intraday_4028.csv.gz  in=390,112,277 out=113,089,395 elapsed=179.3s

  [15117/21087] intraday_4029.csv.gz  in=390,124,460 out=113,089,395 elapsed=179.3s

  [15118/21087] intraday_4030.csv.gz  in=390,136,067 out=113,089,395 elapsed=179.4s

  [15119/21087] intraday_4031.csv.gz  in=390,150,022 out=113,089,395 elapsed=179.4s

  [15120/21087] intraday_4033.csv.gz  in=390,163,368 out=113,089,395 elapsed=179.4s

  [15121/21087] intraday_4035.csv.gz  in=390,177,275 out=113,089,395 elapsed=179.4s

  [15122/21087] intraday_4032.csv.gz  in=390,191,250 out=113,089,395 elapsed=179.4s

  [15123/21087] intraday_4034.csv.gz  in=390,204,188 out=113,089,395 elapsed=179.4s

  [15124/21087] intraday_4036.csv.gz  in=390,217,641 out=113,089,395 elapsed=179.4s

  [15125/21087] intraday_4037.csv.gz  in=390,230,893 out=113,089,395 elapsed=179.4s

  [15126/21087] intraday_4039.csv.gz  in=390,245,089 out=113,089,395 elapsed=179.5s

  [15127/21087] intraday_4038.csv.gz  in=390,259,696 out=113,089,395 elapsed=179.5s

  [15128/21087] intraday_4040.csv.gz  in=390,271,629 out=113,089,395 elapsed=179.5s

  [15129/21087] intraday_4041.csv.gz  in=390,285,974 out=113,089,395 elapsed=179.5s

  [15130/21087] intraday_4042.csv.gz  in=390,298,321 out=113,089,395 elapsed=179.5s

  [15131/21087] intraday_4043.csv.gz  in=390,312,249 out=113,089,395 elapsed=179.5s

  [15132/21087] intraday_4046.csv.gz  in=390,325,672 out=113,089,395 elapsed=179.5s

  [15133/21087] intraday_4044.csv.gz  in=390,341,878 out=113,089,395 elapsed=179.5s

  [15134/21087] intraday_4047.csv.gz  in=390,357,927 out=113,089,395 elapsed=179.5s

  [15135/21087] intraday_4045.csv.gz  in=390,372,888 out=113,089,395 elapsed=179.5s

  [15136/21087] intraday_4048.csv.gz  in=390,385,146 out=113,089,395 elapsed=179.5s

  [15137/21087] intraday_4050.csv.gz  in=390,396,233 out=113,089,395 elapsed=179.5s

  [15138/21087] intraday_4049.csv.gz  in=390,409,203 out=113,089,395 elapsed=179.6s

  [15139/21087] intraday_4051.csv.gz  in=390,423,436 out=113,089,395 elapsed=179.6s

  [15140/21087] intraday_4052.csv.gz  in=390,433,963 out=113,089,395 elapsed=179.6s

  [15141/21087] intraday_4053.csv.gz  in=390,447,520 out=113,089,395 elapsed=179.6s

  [15142/21087] intraday_4054.csv.gz  in=390,461,062 out=113,089,395 elapsed=179.6s

  [15143/21087] intraday_4055.csv.gz  in=390,477,739 out=113,089,395 elapsed=179.6s

  [15144/21087] intraday_4056.csv.gz  in=390,489,273 out=113,089,395 elapsed=179.6s

  [15145/21087] intraday_4057.csv.gz  in=390,502,708 out=113,089,395 elapsed=179.6s

  [15146/21087] intraday_4058.csv.gz  in=390,516,100 out=113,089,395 elapsed=179.6s

  [15147/21087] intraday_4059.csv.gz  in=390,528,565 out=113,089,395 elapsed=179.6s

  [15148/21087] intraday_4060.csv.gz  in=390,542,914 out=113,089,395 elapsed=179.6s

  [15149/21087] intraday_4061.csv.gz  in=390,557,779 out=113,089,395 elapsed=179.6s

  [15150/21087] intraday_4063.csv.gz  in=390,570,871 out=113,089,395 elapsed=179.6s

  [15151/21087] intraday_4062.csv.gz  in=390,585,693 out=113,089,395 elapsed=179.6s

  [15152/21087] intraday_4064.csv.gz  in=390,599,308 out=113,089,395 elapsed=179.7s

  [15153/21087] intraday_4065.csv.gz  in=390,610,830 out=113,089,395 elapsed=179.7s

  [15154/21087] intraday_4066.csv.gz  in=390,623,221 out=113,089,395 elapsed=179.7s

  [15155/21087] intraday_4067.csv.gz  in=390,635,983 out=113,089,395 elapsed=179.7s

  [15156/21087] intraday_4068.csv.gz  in=390,650,677 out=113,089,395 elapsed=179.7s

  [15157/21087] intraday_4069.csv.gz  in=390,660,349 out=113,089,395 elapsed=179.7s

  [15158/21087] intraday_4070.csv.gz  in=390,669,109 out=113,089,395 elapsed=179.7s

  [15159/21087] intraday_4072.csv.gz  in=390,669,182 out=113,089,395 elapsed=179.7s

  [15160/21087] intraday_4071.csv.gz  in=390,681,051 out=113,089,395 elapsed=179.7s

  [15161/21087] intraday_4074.csv.gz  in=390,681,089 out=113,089,395 elapsed=179.7s

  [15162/21087] intraday_4073.csv.gz  in=390,682,134 out=113,089,395 elapsed=179.7s

  [15163/21087] intraday_4076.csv.gz  in=390,682,165 out=113,089,395 elapsed=179.7s

  [15164/21087] intraday_4075.csv.gz  in=390,682,293 out=113,089,395 elapsed=179.7s

  [15165/21087] intraday_4078.csv.gz  in=390,682,445 out=113,089,395 elapsed=179.7s

  [15166/21087] intraday_4077.csv.gz  in=390,683,054 out=113,089,395 elapsed=179.8s

  [15167/21087] intraday_4080.csv.gz  in=390,683,083 out=113,089,395 elapsed=179.8s

  [15168/21087] intraday_4081.csv.gz  in=390,684,111 out=113,089,395 elapsed=179.8s

  [15169/21087] intraday_4079.csv.gz  in=390,684,190 out=113,089,395 elapsed=179.8s

  [15170/21087] intraday_4082.csv.gz  in=390,684,202 out=113,089,395 elapsed=179.8s

  [15171/21087] intraday_4085.csv.gz  in=390,684,305 out=113,089,395 elapsed=179.8s

  [15172/21087] intraday_4083.csv.gz  in=390,684,313 out=113,089,395 elapsed=179.8s

  [15173/21087] intraday_4086.csv.gz  in=390,684,346 out=113,089,395 elapsed=179.8s

  [15174/21087] intraday_4084.csv.gz  in=390,685,071 out=113,089,395 elapsed=179.8s

  [15175/21087] intraday_4087.csv.gz  in=390,685,632 out=113,089,395 elapsed=179.8s

  [15176/21087] intraday_4090.csv.gz  in=390,685,779 out=113,089,395 elapsed=179.8s

  [15177/21087] intraday_4089.csv.gz  in=390,694,659 out=113,089,395 elapsed=179.8s

  [15178/21087] intraday_4088.csv.gz  in=390,698,987 out=113,089,395 elapsed=179.8s

  [15179/21087] intraday_4091.csv.gz  in=390,699,516 out=113,089,395 elapsed=179.8s

  [15180/21087] intraday_4092.csv.gz  in=390,699,593 out=113,089,395 elapsed=179.8s

  [15181/21087] intraday_4093.csv.gz  in=390,699,657 out=113,089,395 elapsed=179.8s

  [15182/21087] intraday_4095.csv.gz  in=390,699,770 out=113,089,395 elapsed=179.9s

  [15183/21087] intraday_4094.csv.gz  in=390,700,968 out=113,089,395 elapsed=179.9s

  [15184/21087] intraday_4096.csv.gz  in=390,701,041 out=113,089,395 elapsed=179.9s

  [15185/21087] intraday_4098.csv.gz  in=390,701,060 out=113,089,395 elapsed=179.9s

  [15186/21087] intraday_4097.csv.gz  in=390,707,506 out=113,089,395 elapsed=179.9s

  [15187/21087] intraday_4099.csv.gz  in=390,708,457 out=113,089,395 elapsed=179.9s

  [15188/21087] intraday_4100.csv.gz  in=390,714,891 out=113,089,395 elapsed=179.9s

  [15189/21087] intraday_4101.csv.gz  in=390,715,047 out=113,089,395 elapsed=179.9s

  [15190/21087] intraday_4102.csv.gz  in=390,715,843 out=113,089,395 elapsed=179.9s

  [15191/21087] intraday_4103.csv.gz  in=390,718,328 out=113,089,395 elapsed=179.9s

  [15192/21087] intraday_4104.csv.gz  in=390,718,360 out=113,089,395 elapsed=179.9s

  [15193/21087] intraday_4105.csv.gz  in=390,718,474 out=113,089,395 elapsed=179.9s

  [15194/21087] intraday_4106.csv.gz  in=390,718,513 out=113,089,395 elapsed=179.9s

  [15195/21087] intraday_4108.csv.gz  in=390,718,926 out=113,089,395 elapsed=179.9s

  [15196/21087] intraday_4109.csv.gz  in=390,719,062 out=113,089,395 elapsed=180.0s

  [15197/21087] intraday_4107.csv.gz  in=390,726,832 out=113,089,395 elapsed=180.0s

  [15198/21087] intraday_4110.csv.gz  in=390,726,968 out=113,089,395 elapsed=180.0s

  [15199/21087] intraday_4111.csv.gz  in=390,727,063 out=113,089,395 elapsed=180.0s

  [15200/21087] intraday_4112.csv.gz  in=390,727,326 out=113,089,395 elapsed=180.0s

  [15201/21087] intraday_4113.csv.gz  in=390,727,465 out=113,089,395 elapsed=180.0s

  [15202/21087] intraday_4114.csv.gz  in=390,727,533 out=113,089,395 elapsed=180.0s

  [15203/21087] intraday_4115.csv.gz  in=390,743,103 out=113,089,395 elapsed=180.0s

  [15204/21087] intraday_4117.csv.gz  in=390,756,076 out=113,089,395 elapsed=180.0s

  [15205/21087] intraday_4116.csv.gz  in=390,770,967 out=113,089,395 elapsed=180.0s

  [15206/21087] intraday_4118.csv.gz  in=390,781,235 out=113,089,395 elapsed=180.0s

  [15207/21087] intraday_4119.csv.gz  in=390,795,843 out=113,089,395 elapsed=180.0s

  [15208/21087] intraday_4120.csv.gz  in=390,810,293 out=113,089,395 elapsed=180.0s

  [15209/21087] intraday_4121.csv.gz  in=390,822,466 out=113,089,395 elapsed=180.1s

  [15210/21087] intraday_4122.csv.gz  in=390,834,354 out=113,089,395 elapsed=180.1s

  [15211/21087] intraday_4123.csv.gz  in=390,848,647 out=113,089,395 elapsed=180.1s

  [15212/21087] intraday_4124.csv.gz  in=390,864,155 out=113,089,395 elapsed=180.1s

  [15213/21087] intraday_4125.csv.gz  in=390,874,826 out=113,089,395 elapsed=180.1s

  [15214/21087] intraday_4127.csv.gz  in=390,886,367 out=113,089,395 elapsed=180.1s

  [15215/21087] intraday_4126.csv.gz  in=390,900,384 out=113,089,395 elapsed=180.1s

  [15216/21087] intraday_4128.csv.gz  in=390,911,926 out=113,089,395 elapsed=180.1s

  [15217/21087] intraday_4129.csv.gz  in=390,922,915 out=113,089,395 elapsed=180.1s

  [15218/21087] intraday_4130.csv.gz  in=390,934,282 out=113,089,395 elapsed=180.1s

  [15219/21087] intraday_4131.csv.gz  in=390,948,058 out=113,089,395 elapsed=180.1s

  [15220/21087] intraday_4132.csv.gz  in=390,962,026 out=113,089,395 elapsed=180.1s

  [15221/21087] intraday_4133.csv.gz  in=390,972,733 out=113,089,395 elapsed=180.1s

  [15222/21087] intraday_4134.csv.gz  in=390,985,456 out=113,089,395 elapsed=180.1s

  [15223/21087] intraday_4135.csv.gz  in=390,999,617 out=113,089,395 elapsed=180.2s

  [15224/21087] intraday_4136.csv.gz  in=391,012,034 out=113,089,395 elapsed=180.2s

  [15225/21087] intraday_4137.csv.gz  in=391,023,670 out=113,089,395 elapsed=180.2s

  [15226/21087] intraday_4138.csv.gz  in=391,036,013 out=113,089,395 elapsed=180.2s

  [15227/21087] intraday_4140.csv.gz  in=391,045,817 out=113,089,395 elapsed=180.2s

  [15228/21087] intraday_4139.csv.gz  in=391,057,367 out=113,089,395 elapsed=180.2s

  [15229/21087] intraday_4141.csv.gz  in=391,070,461 out=113,089,395 elapsed=180.2s

  [15230/21087] intraday_4142.csv.gz  in=391,083,109 out=113,089,395 elapsed=180.2s

  [15231/21087] intraday_4143.csv.gz  in=391,095,369 out=113,089,395 elapsed=180.2s

  [15232/21087] intraday_4144.csv.gz  in=391,110,859 out=113,089,395 elapsed=180.2s

  [15233/21087] intraday_4146.csv.gz  in=391,122,946 out=113,089,395 elapsed=180.2s

  [15234/21087] intraday_4145.csv.gz  in=391,137,558 out=113,089,395 elapsed=180.2s

  [15235/21087] intraday_4147.csv.gz  in=391,149,505 out=113,089,395 elapsed=180.2s

  [15236/21087] intraday_4148.csv.gz  in=391,162,672 out=113,089,395 elapsed=180.3s

  [15237/21087] intraday_4149.csv.gz  in=391,174,630 out=113,089,395 elapsed=180.3s

  [15238/21087] intraday_4150.csv.gz  in=391,187,616 out=113,089,395 elapsed=180.3s

  [15239/21087] intraday_4151.csv.gz  in=391,197,788 out=113,089,395 elapsed=180.3s

  [15240/21087] intraday_4152.csv.gz  in=391,208,852 out=113,089,395 elapsed=180.3s

  [15241/21087] intraday_4153.csv.gz  in=391,221,136 out=113,089,395 elapsed=180.3s

  [15242/21087] intraday_4154.csv.gz  in=391,230,870 out=113,089,395 elapsed=180.3s

  [15243/21087] intraday_4157.csv.gz  in=391,242,977 out=113,089,395 elapsed=180.3s

  [15244/21087] intraday_4155.csv.gz  in=391,257,474 out=113,089,395 elapsed=180.3s

  [15245/21087] intraday_4156.csv.gz  in=391,270,347 out=113,089,395 elapsed=180.3s

  [15246/21087] intraday_4158.csv.gz  in=391,281,582 out=113,089,395 elapsed=180.3s

  [15247/21087] intraday_4159.csv.gz  in=391,293,175 out=113,089,395 elapsed=180.3s

  [15248/21087] intraday_4160.csv.gz  in=391,306,053 out=113,089,395 elapsed=180.4s

  [15249/21087] intraday_4161.csv.gz  in=391,316,898 out=113,089,395 elapsed=180.4s

  [15250/21087] intraday_4162.csv.gz  in=391,328,860 out=113,089,395 elapsed=180.4s

  [15251/21087] intraday_4163.csv.gz  in=391,340,233 out=113,089,395 elapsed=180.4s

  [15252/21087] intraday_4165.csv.gz  in=391,351,468 out=113,089,395 elapsed=180.4s

  [15253/21087] intraday_4164.csv.gz  in=391,362,194 out=113,089,395 elapsed=180.4s

  [15254/21087] intraday_4166.csv.gz  in=391,373,563 out=113,089,395 elapsed=180.4s

  [15255/21087] intraday_4167.csv.gz  in=391,384,834 out=113,089,395 elapsed=180.4s

  [15256/21087] intraday_4169.csv.gz  in=391,397,142 out=113,089,395 elapsed=180.4s

  [15257/21087] intraday_4168.csv.gz  in=391,410,478 out=113,089,395 elapsed=180.4s

  [15258/21087] intraday_4171.csv.gz  in=391,420,995 out=113,089,395 elapsed=180.4s

  [15259/21087] intraday_4170.csv.gz  in=391,431,567 out=113,089,395 elapsed=180.4s

  [15260/21087] intraday_4173.csv.gz  in=391,443,775 out=113,089,395 elapsed=180.5s

  [15261/21087] intraday_4172.csv.gz  in=391,457,236 out=113,089,395 elapsed=180.5s

  [15262/21087] intraday_4174.csv.gz  in=391,468,550 out=113,089,395 elapsed=180.5s

  [15263/21087] intraday_4175.csv.gz  in=391,479,969 out=113,089,395 elapsed=180.5s

  [15264/21087] intraday_4176.csv.gz  in=391,491,383 out=113,089,395 elapsed=180.5s

  [15265/21087] intraday_4179.csv.gz  in=391,504,443 out=113,089,395 elapsed=180.5s

  [15266/21087] intraday_4177.csv.gz  in=391,516,191 out=113,089,395 elapsed=180.5s

  [15267/21087] intraday_4178.csv.gz  in=391,531,578 out=113,089,395 elapsed=180.5s

  [15268/21087] intraday_4180.csv.gz  in=391,543,544 out=113,089,395 elapsed=180.5s

  [15269/21087] intraday_4181.csv.gz  in=391,555,050 out=113,089,395 elapsed=180.5s

  [15270/21087] intraday_4182.csv.gz  in=391,567,357 out=113,089,395 elapsed=180.5s

  [15271/21087] intraday_4183.csv.gz  in=391,577,355 out=113,089,395 elapsed=180.5s

  [15272/21087] intraday_4184.csv.gz  in=391,589,445 out=113,089,395 elapsed=180.6s

  [15273/21087] intraday_4185.csv.gz  in=391,600,919 out=113,089,395 elapsed=180.6s

  [15274/21087] intraday_4187.csv.gz  in=391,610,703 out=113,089,395 elapsed=180.6s

  [15275/21087] intraday_4186.csv.gz  in=391,624,259 out=113,089,395 elapsed=180.6s

  [15276/21087] intraday_4188.csv.gz  in=391,635,092 out=113,089,395 elapsed=180.6s

  [15277/21087] intraday_4189.csv.gz  in=391,645,299 out=113,089,395 elapsed=180.6s

  [15278/21087] intraday_4191.csv.gz  in=391,657,105 out=113,089,395 elapsed=180.6s

  [15279/21087] intraday_4190.csv.gz  in=391,671,394 out=113,089,395 elapsed=180.6s

  [15280/21087] intraday_4192.csv.gz  in=391,684,610 out=113,089,395 elapsed=180.6s

  [15281/21087] intraday_4193.csv.gz  in=391,694,932 out=113,089,395 elapsed=180.6s

  [15282/21087] intraday_4194.csv.gz  in=391,705,694 out=113,089,395 elapsed=180.6s

  [15283/21087] intraday_4195.csv.gz  in=391,717,566 out=113,089,395 elapsed=180.6s

  [15284/21087] intraday_4196.csv.gz  in=391,733,973 out=113,089,395 elapsed=180.6s

  [15285/21087] intraday_4197.csv.gz  in=391,745,494 out=113,089,395 elapsed=180.6s

  [15286/21087] intraday_4198.csv.gz  in=391,756,865 out=113,089,395 elapsed=180.6s

  [15287/21087] intraday_4199.csv.gz  in=391,768,491 out=113,089,395 elapsed=180.7s

  [15288/21087] intraday_4200.csv.gz  in=391,779,170 out=113,089,395 elapsed=180.7s

  [15289/21087] intraday_4201.csv.gz  in=391,792,521 out=113,089,395 elapsed=180.7s

  [15290/21087] intraday_4202.csv.gz  in=391,807,568 out=113,089,395 elapsed=180.7s

  [15291/21087] intraday_4203.csv.gz  in=391,819,408 out=113,089,395 elapsed=180.7s

  [15292/21087] intraday_4204.csv.gz  in=391,832,785 out=113,089,395 elapsed=180.7s

  [15293/21087] intraday_4205.csv.gz  in=391,845,949 out=113,089,395 elapsed=180.7s

  [15294/21087] intraday_4206.csv.gz  in=391,859,368 out=113,089,395 elapsed=180.7s

  [15295/21087] intraday_4208.csv.gz  in=391,872,420 out=113,089,395 elapsed=180.7s

  [15296/21087] intraday_4207.csv.gz  in=391,894,883 out=113,089,395 elapsed=180.7s

  [15297/21087] intraday_4209.csv.gz  in=391,906,716 out=113,089,395 elapsed=180.7s

  [15298/21087] intraday_4210.csv.gz  in=391,917,657 out=113,089,395 elapsed=180.7s

  [15299/21087] intraday_4211.csv.gz  in=391,929,584 out=113,089,395 elapsed=180.7s

  [15300/21087] intraday_4212.csv.gz  in=391,941,352 out=113,089,395 elapsed=180.8s

  [15301/21087] intraday_4214.csv.gz  in=391,952,984 out=113,089,395 elapsed=180.8s

  [15302/21087] intraday_4213.csv.gz  in=391,964,938 out=113,089,395 elapsed=180.8s

  [15303/21087] intraday_4215.csv.gz  in=391,978,224 out=113,089,395 elapsed=180.8s

  [15304/21087] intraday_4216.csv.gz  in=391,990,205 out=113,089,395 elapsed=180.8s

  [15305/21087] intraday_4218.csv.gz  in=392,005,607 out=113,089,395 elapsed=180.8s

  [15306/21087] intraday_4217.csv.gz  in=392,018,093 out=113,089,395 elapsed=180.8s

  [15307/21087] intraday_4219.csv.gz  in=392,029,172 out=113,089,395 elapsed=180.8s

  [15308/21087] intraday_4220.csv.gz  in=392,040,030 out=113,089,395 elapsed=180.8s

  [15309/21087] intraday_4221.csv.gz  in=392,054,505 out=113,089,395 elapsed=180.8s

  [15310/21087] intraday_4222.csv.gz  in=392,069,223 out=113,089,395 elapsed=180.8s

  [15311/21087] intraday_4223.csv.gz  in=392,080,944 out=113,089,395 elapsed=180.8s

  [15312/21087] intraday_4224.csv.gz  in=392,093,928 out=113,089,395 elapsed=180.8s

  [15313/21087] intraday_4225.csv.gz  in=392,107,316 out=113,089,395 elapsed=180.9s

  [15314/21087] intraday_4226.csv.gz  in=392,119,284 out=113,089,395 elapsed=180.9s

  [15315/21087] intraday_4228.csv.gz  in=392,132,675 out=113,089,395 elapsed=180.9s

  [15316/21087] intraday_4227.csv.gz  in=392,148,188 out=113,089,395 elapsed=180.9s

  [15317/21087] intraday_4229.csv.gz  in=392,161,584 out=113,089,395 elapsed=180.9s

  [15318/21087] intraday_4230.csv.gz  in=392,177,967 out=113,089,395 elapsed=180.9s

  [15319/21087] intraday_4232.csv.gz  in=392,190,111 out=113,089,395 elapsed=180.9s

  [15320/21087] intraday_4231.csv.gz  in=392,202,792 out=113,089,395 elapsed=180.9s

  [15321/21087] intraday_4233.csv.gz  in=392,213,783 out=113,089,395 elapsed=180.9s

  [15322/21087] intraday_4234.csv.gz  in=392,225,155 out=113,089,395 elapsed=180.9s

  [15323/21087] intraday_4235.csv.gz  in=392,236,677 out=113,089,395 elapsed=180.9s

  [15324/21087] intraday_4236.csv.gz  in=392,249,693 out=113,089,395 elapsed=180.9s

  [15325/21087] intraday_4237.csv.gz  in=392,261,983 out=113,089,395 elapsed=180.9s

  [15326/21087] intraday_4238.csv.gz  in=392,277,532 out=113,089,395 elapsed=181.0s

  [15327/21087] intraday_4239.csv.gz  in=392,290,329 out=113,089,395 elapsed=181.0s

  [15328/21087] intraday_4240.csv.gz  in=392,303,771 out=113,089,395 elapsed=181.0s

  [15329/21087] intraday_4241.csv.gz  in=392,316,261 out=113,089,395 elapsed=181.0s

  [15330/21087] intraday_4242.csv.gz  in=392,329,737 out=113,089,395 elapsed=181.0s

  [15331/21087] intraday_4243.csv.gz  in=392,341,639 out=113,089,395 elapsed=181.0s

  [15332/21087] intraday_4244.csv.gz  in=392,354,239 out=113,089,395 elapsed=181.0s

  [15333/21087] intraday_4245.csv.gz  in=392,368,613 out=113,089,395 elapsed=181.0s

  [15334/21087] intraday_4246.csv.gz  in=392,382,727 out=113,089,395 elapsed=181.0s

  [15335/21087] intraday_4247.csv.gz  in=392,395,856 out=113,089,395 elapsed=181.0s

  [15336/21087] intraday_4248.csv.gz  in=392,407,757 out=113,089,395 elapsed=181.0s

  [15337/21087] intraday_4249.csv.gz  in=392,418,063 out=113,089,395 elapsed=181.0s

  [15338/21087] intraday_4251.csv.gz  in=392,429,470 out=113,089,395 elapsed=181.1s

  [15339/21087] intraday_4250.csv.gz  in=392,442,392 out=113,089,395 elapsed=181.1s

  [15340/21087] intraday_4253.csv.gz  in=392,449,979 out=113,089,395 elapsed=181.1s

  [15341/21087] intraday_4252.csv.gz  in=392,462,446 out=113,089,395 elapsed=181.1s

  [15342/21087] intraday_4255.csv.gz  in=392,469,705 out=113,089,395 elapsed=181.1s

  [15343/21087] intraday_4254.csv.gz  in=392,480,010 out=113,089,395 elapsed=181.1s

  [15344/21087] intraday_4257.csv.gz  in=392,494,029 out=113,089,395 elapsed=181.1s

  [15345/21087] intraday_4256.csv.gz  in=392,509,812 out=113,089,395 elapsed=181.1s

  [15346/21087] intraday_4259.csv.gz  in=392,519,960 out=113,089,395 elapsed=181.1s

  [15347/21087] intraday_4258.csv.gz  in=392,532,423 out=113,089,395 elapsed=181.1s

  [15348/21087] intraday_4260.csv.gz  in=392,547,349 out=113,089,395 elapsed=181.1s

  [15349/21087] intraday_4261.csv.gz  in=392,561,748 out=113,089,395 elapsed=181.1s

  [15350/21087] intraday_4262.csv.gz  in=392,574,268 out=113,089,395 elapsed=181.1s

  [15351/21087] intraday_4263.csv.gz  in=392,586,478 out=113,089,395 elapsed=181.1s

  [15352/21087] intraday_4264.csv.gz  in=392,600,963 out=113,089,395 elapsed=181.2s

  [15353/21087] intraday_4265.csv.gz  in=392,616,653 out=113,089,395 elapsed=181.2s

  [15354/21087] intraday_4266.csv.gz  in=392,627,841 out=113,089,395 elapsed=181.2s

  [15355/21087] intraday_4267.csv.gz  in=392,640,918 out=113,089,395 elapsed=181.2s

  [15356/21087] intraday_4268.csv.gz  in=392,653,279 out=113,089,395 elapsed=181.2s

  [15357/21087] intraday_4269.csv.gz  in=392,665,291 out=113,089,395 elapsed=181.2s

  [15358/21087] intraday_4270.csv.gz  in=392,676,553 out=113,089,395 elapsed=181.2s

  [15359/21087] intraday_4271.csv.gz  in=392,688,049 out=113,089,395 elapsed=181.2s

  [15360/21087] intraday_4272.csv.gz  in=392,702,438 out=113,089,395 elapsed=181.2s

  [15361/21087] intraday_4273.csv.gz  in=392,715,623 out=113,089,395 elapsed=181.2s

  [15362/21087] intraday_4274.csv.gz  in=392,725,959 out=113,089,395 elapsed=181.2s

  [15363/21087] intraday_4275.csv.gz  in=392,738,712 out=113,089,395 elapsed=181.2s

  [15364/21087] intraday_4277.csv.gz  in=392,751,629 out=113,089,395 elapsed=181.2s

  [15365/21087] intraday_4276.csv.gz  in=392,765,743 out=113,089,395 elapsed=181.3s

  [15366/21087] intraday_4278.csv.gz  in=392,777,902 out=113,089,395 elapsed=181.3s

  [15367/21087] intraday_4279.csv.gz  in=392,790,585 out=113,089,395 elapsed=181.3s

  [15368/21087] intraday_4281.csv.gz  in=392,801,766 out=113,089,395 elapsed=181.3s

  [15369/21087] intraday_4280.csv.gz  in=392,814,142 out=113,089,395 elapsed=181.3s

  [15370/21087] intraday_4282.csv.gz  in=392,827,652 out=113,089,395 elapsed=181.3s

  [15371/21087] intraday_4283.csv.gz  in=392,840,742 out=113,089,395 elapsed=181.3s

  [15372/21087] intraday_4284.csv.gz  in=392,854,720 out=113,089,395 elapsed=181.3s

  [15373/21087] intraday_4285.csv.gz  in=392,869,110 out=113,089,395 elapsed=181.3s

  [15374/21087] intraday_4286.csv.gz  in=392,882,994 out=113,089,395 elapsed=181.3s

  [15375/21087] intraday_4287.csv.gz  in=392,894,081 out=113,089,395 elapsed=181.3s

  [15376/21087] intraday_4288.csv.gz  in=392,906,328 out=113,089,395 elapsed=181.3s

  [15377/21087] intraday_4290.csv.gz  in=392,918,190 out=113,089,395 elapsed=181.3s

  [15378/21087] intraday_4289.csv.gz  in=392,931,406 out=113,089,395 elapsed=181.4s

  [15379/21087] intraday_4291.csv.gz  in=392,943,532 out=113,089,395 elapsed=181.4s

  [15380/21087] intraday_4292.csv.gz  in=392,955,162 out=113,089,395 elapsed=181.4s

  [15381/21087] intraday_4293.csv.gz  in=392,968,420 out=113,089,395 elapsed=181.4s

  [15382/21087] intraday_4294.csv.gz  in=392,980,031 out=113,089,395 elapsed=181.4s

  [15383/21087] intraday_4295.csv.gz  in=392,991,546 out=113,089,395 elapsed=181.4s

  [15384/21087] intraday_4296.csv.gz  in=393,005,143 out=113,089,395 elapsed=181.4s

  [15385/21087] intraday_4297.csv.gz  in=393,016,311 out=113,089,395 elapsed=181.4s

  [15386/21087] intraday_4298.csv.gz  in=393,029,859 out=113,089,395 elapsed=181.4s

  [15387/21087] intraday_4299.csv.gz  in=393,041,168 out=113,089,395 elapsed=181.4s

  [15388/21087] intraday_4300.csv.gz  in=393,053,870 out=113,089,395 elapsed=181.4s

  [15389/21087] intraday_4301.csv.gz  in=393,066,477 out=113,089,395 elapsed=181.4s

  [15390/21087] intraday_4302.csv.gz  in=393,077,679 out=113,089,395 elapsed=181.4s

  [15391/21087] intraday_4303.csv.gz  in=393,090,176 out=113,089,395 elapsed=181.5s

  [15392/21087] intraday_4304.csv.gz  in=393,101,446 out=113,089,395 elapsed=181.5s

  [15393/21087] intraday_4305.csv.gz  in=393,110,974 out=113,089,395 elapsed=181.5s

  [15394/21087] intraday_4306.csv.gz  in=393,124,659 out=113,089,395 elapsed=181.5s

  [15395/21087] intraday_4307.csv.gz  in=393,135,903 out=113,089,395 elapsed=181.5s

  [15396/21087] intraday_4308.csv.gz  in=393,147,219 out=113,089,395 elapsed=181.5s

  [15397/21087] intraday_4309.csv.gz  in=393,160,228 out=113,089,395 elapsed=181.5s

  [15398/21087] intraday_4310.csv.gz  in=393,172,666 out=113,089,395 elapsed=181.5s

  [15399/21087] intraday_4311.csv.gz  in=393,183,580 out=113,089,395 elapsed=181.5s

  [15400/21087] intraday_4312.csv.gz  in=393,194,289 out=113,089,395 elapsed=181.5s

  [15401/21087] intraday_4313.csv.gz  in=393,208,597 out=113,089,395 elapsed=181.5s

  [15402/21087] intraday_4314.csv.gz  in=393,220,945 out=113,089,395 elapsed=181.5s

  [15403/21087] intraday_4315.csv.gz  in=393,233,211 out=113,089,395 elapsed=181.5s

  [15404/21087] intraday_4316.csv.gz  in=393,244,147 out=113,089,395 elapsed=181.6s

  [15405/21087] intraday_4317.csv.gz  in=393,256,039 out=113,089,395 elapsed=181.6s

  [15406/21087] intraday_4318.csv.gz  in=393,267,237 out=113,089,395 elapsed=181.6s

  [15407/21087] intraday_4319.csv.gz  in=393,281,737 out=113,089,395 elapsed=181.6s

  [15408/21087] intraday_4320.csv.gz  in=393,294,350 out=113,089,395 elapsed=181.6s

  [15409/21087] intraday_4321.csv.gz  in=393,307,530 out=113,089,395 elapsed=181.6s

  [15410/21087] intraday_4322.csv.gz  in=393,319,950 out=113,089,395 elapsed=181.6s

  [15411/21087] intraday_4323.csv.gz  in=393,336,628 out=113,089,395 elapsed=181.6s

  [15412/21087] intraday_4324.csv.gz  in=393,347,763 out=113,089,395 elapsed=181.6s

  [15413/21087] intraday_4325.csv.gz  in=393,359,282 out=113,089,395 elapsed=181.6s

  [15414/21087] intraday_4326.csv.gz  in=393,370,116 out=113,089,395 elapsed=181.6s

  [15415/21087] intraday_4327.csv.gz  in=393,383,788 out=113,089,395 elapsed=181.7s

  [15416/21087] intraday_4328.csv.gz  in=393,394,682 out=113,089,395 elapsed=181.7s

  [15417/21087] intraday_4329.csv.gz  in=393,405,172 out=113,089,395 elapsed=181.7s

  [15418/21087] intraday_4330.csv.gz  in=393,417,471 out=113,089,395 elapsed=181.7s

  [15419/21087] intraday_4332.csv.gz  in=393,428,532 out=113,089,395 elapsed=181.7s

  [15420/21087] intraday_4331.csv.gz  in=393,442,496 out=113,089,395 elapsed=181.7s

  [15421/21087] intraday_4333.csv.gz  in=393,454,409 out=113,089,395 elapsed=181.7s

  [15422/21087] intraday_4334.csv.gz  in=393,464,880 out=113,089,395 elapsed=181.7s

  [15423/21087] intraday_4335.csv.gz  in=393,477,018 out=113,089,395 elapsed=181.7s

  [15424/21087] intraday_4336.csv.gz  in=393,490,075 out=113,089,395 elapsed=181.7s

  [15425/21087] intraday_4337.csv.gz  in=393,505,182 out=113,089,395 elapsed=181.7s

  [15426/21087] intraday_4338.csv.gz  in=393,516,490 out=113,089,395 elapsed=181.7s

  [15427/21087] intraday_4339.csv.gz  in=393,527,377 out=113,089,395 elapsed=181.7s

  [15428/21087] intraday_4340.csv.gz  in=393,538,119 out=113,089,395 elapsed=181.7s

  [15429/21087] intraday_4341.csv.gz  in=393,551,257 out=113,089,395 elapsed=181.8s

  [15430/21087] intraday_4342.csv.gz  in=393,564,297 out=113,089,395 elapsed=181.8s

  [15431/21087] intraday_4343.csv.gz  in=393,579,353 out=113,089,395 elapsed=181.8s

  [15432/21087] intraday_4344.csv.gz  in=393,590,322 out=113,089,395 elapsed=181.8s

  [15433/21087] intraday_4345.csv.gz  in=393,604,420 out=113,089,395 elapsed=181.8s

  [15434/21087] intraday_4346.csv.gz  in=393,618,097 out=113,089,395 elapsed=181.8s

  [15435/21087] intraday_4347.csv.gz  in=393,632,678 out=113,089,395 elapsed=181.8s

  [15436/21087] intraday_4348.csv.gz  in=393,647,822 out=113,089,395 elapsed=181.8s

  [15437/21087] intraday_4349.csv.gz  in=393,660,557 out=113,089,395 elapsed=181.8s

  [15438/21087] intraday_4350.csv.gz  in=393,672,079 out=113,089,395 elapsed=181.8s

  [15439/21087] intraday_4351.csv.gz  in=393,684,638 out=113,089,395 elapsed=181.8s

  [15440/21087] intraday_4352.csv.gz  in=393,695,452 out=113,089,395 elapsed=181.8s

  [15441/21087] intraday_4353.csv.gz  in=393,706,493 out=113,089,395 elapsed=181.8s

  [15442/21087] intraday_4354.csv.gz  in=393,718,232 out=113,089,395 elapsed=181.9s

  [15443/21087] intraday_4355.csv.gz  in=393,731,293 out=113,089,395 elapsed=181.9s

  [15444/21087] intraday_4356.csv.gz  in=393,744,084 out=113,089,395 elapsed=181.9s

  [15445/21087] intraday_4357.csv.gz  in=393,756,157 out=113,089,395 elapsed=181.9s

  [15446/21087] intraday_4358.csv.gz  in=393,768,845 out=113,089,395 elapsed=181.9s

  [15447/21087] intraday_4359.csv.gz  in=393,782,189 out=113,089,395 elapsed=181.9s

  [15448/21087] intraday_4360.csv.gz  in=393,794,854 out=113,089,395 elapsed=181.9s

  [15449/21087] intraday_4361.csv.gz  in=393,807,760 out=113,089,395 elapsed=181.9s

  [15450/21087] intraday_4362.csv.gz  in=393,820,633 out=113,089,395 elapsed=181.9s

  [15451/21087] intraday_4363.csv.gz  in=393,834,591 out=113,089,395 elapsed=181.9s

  [15452/21087] intraday_4364.csv.gz  in=393,846,161 out=113,089,395 elapsed=181.9s

  [15453/21087] intraday_4365.csv.gz  in=393,861,400 out=113,089,395 elapsed=181.9s

  [15454/21087] intraday_4366.csv.gz  in=393,873,836 out=113,089,395 elapsed=182.0s

  [15455/21087] intraday_4367.csv.gz  in=393,887,381 out=113,089,395 elapsed=182.0s

  [15456/21087] intraday_4368.csv.gz  in=393,901,008 out=113,089,395 elapsed=182.0s

  [15457/21087] intraday_4369.csv.gz  in=393,915,266 out=113,089,395 elapsed=182.0s

  [15458/21087] intraday_4370.csv.gz  in=393,929,262 out=113,089,395 elapsed=182.0s

  [15459/21087] intraday_4371.csv.gz  in=393,944,761 out=113,089,395 elapsed=182.0s

  [15460/21087] intraday_4372.csv.gz  in=393,965,212 out=113,089,395 elapsed=182.0s

  [15461/21087] intraday_4373.csv.gz  in=393,977,008 out=113,089,395 elapsed=182.0s

  [15462/21087] intraday_4374.csv.gz  in=393,987,558 out=113,089,395 elapsed=182.0s

  [15463/21087] intraday_4375.csv.gz  in=394,001,417 out=113,089,395 elapsed=182.0s

  [15464/21087] intraday_4376.csv.gz  in=394,011,048 out=113,089,395 elapsed=182.0s

  [15465/21087] intraday_4377.csv.gz  in=394,024,389 out=113,089,395 elapsed=182.0s

  [15466/21087] intraday_4378.csv.gz  in=394,037,291 out=113,089,395 elapsed=182.0s

  [15467/21087] intraday_4379.csv.gz  in=394,052,079 out=113,089,395 elapsed=182.0s

  [15468/21087] intraday_4380.csv.gz  in=394,064,133 out=113,089,395 elapsed=182.1s

  [15469/21087] intraday_4381.csv.gz  in=394,076,984 out=113,089,395 elapsed=182.1s

  [15470/21087] intraday_4382.csv.gz  in=394,090,296 out=113,089,395 elapsed=182.1s

  [15471/21087] intraday_4383.csv.gz  in=394,103,507 out=113,089,395 elapsed=182.1s

  [15472/21087] intraday_4384.csv.gz  in=394,115,389 out=113,089,395 elapsed=182.1s

  [15473/21087] intraday_4385.csv.gz  in=394,129,811 out=113,089,395 elapsed=182.1s

  [15474/21087] intraday_4386.csv.gz  in=394,144,793 out=113,089,395 elapsed=182.1s

  [15475/21087] intraday_4387.csv.gz  in=394,157,149 out=113,089,395 elapsed=182.1s

  [15476/21087] intraday_4388.csv.gz  in=394,171,402 out=113,089,395 elapsed=182.1s

  [15477/21087] intraday_4389.csv.gz  in=394,182,444 out=113,089,395 elapsed=182.1s

  [15478/21087] intraday_4390.csv.gz  in=394,193,687 out=113,089,395 elapsed=182.1s

  [15479/21087] intraday_4391.csv.gz  in=394,206,512 out=113,089,395 elapsed=182.1s

  [15480/21087] intraday_4393.csv.gz  in=394,215,390 out=113,089,395 elapsed=182.1s

  [15481/21087] intraday_4392.csv.gz  in=394,228,442 out=113,089,395 elapsed=182.1s

  [15482/21087] intraday_4394.csv.gz  in=394,236,743 out=113,089,395 elapsed=182.2s

  [15483/21087] intraday_4396.csv.gz  in=394,238,065 out=113,089,395 elapsed=182.2s

  [15484/21087] intraday_4395.csv.gz  in=394,249,862 out=113,089,395 elapsed=182.2s

  [15485/21087] intraday_4397.csv.gz  in=394,264,776 out=113,089,395 elapsed=182.2s

  [15486/21087] intraday_4398.csv.gz  in=394,279,625 out=113,089,395 elapsed=182.2s

  [15487/21087] intraday_4399.csv.gz  in=394,292,290 out=113,089,395 elapsed=182.2s

  [15488/21087] intraday_4400.csv.gz  in=394,302,981 out=113,089,395 elapsed=182.2s

  [15489/21087] intraday_4401.csv.gz  in=394,318,166 out=113,089,395 elapsed=182.2s

  [15490/21087] intraday_4402.csv.gz  in=394,332,875 out=113,089,395 elapsed=182.2s

  [15491/21087] intraday_4403.csv.gz  in=394,345,528 out=113,089,395 elapsed=182.2s

  [15492/21087] intraday_4404.csv.gz  in=394,356,782 out=113,089,395 elapsed=182.2s

  [15493/21087] intraday_4405.csv.gz  in=394,370,536 out=113,089,395 elapsed=182.2s

  [15494/21087] intraday_4406.csv.gz  in=394,386,219 out=113,089,395 elapsed=182.3s

  [15495/21087] intraday_4407.csv.gz  in=394,396,182 out=113,089,395 elapsed=182.3s

  [15496/21087] intraday_4408.csv.gz  in=394,408,882 out=113,089,395 elapsed=182.3s

  [15497/21087] intraday_4409.csv.gz  in=394,423,099 out=113,089,395 elapsed=182.3s

  [15498/21087] intraday_4410.csv.gz  in=394,435,869 out=113,089,395 elapsed=182.3s

  [15499/21087] intraday_4411.csv.gz  in=394,446,809 out=113,089,395 elapsed=182.3s

  [15500/21087] intraday_4412.csv.gz  in=394,458,253 out=113,089,395 elapsed=182.3s

  [15501/21087] intraday_4413.csv.gz  in=394,471,506 out=113,089,395 elapsed=182.3s

  [15502/21087] intraday_4415.csv.gz  in=394,482,682 out=113,089,395 elapsed=182.3s

  [15503/21087] intraday_4414.csv.gz  in=394,495,741 out=113,089,395 elapsed=182.3s

  [15504/21087] intraday_4416.csv.gz  in=394,509,039 out=113,089,395 elapsed=182.3s

  [15505/21087] intraday_4417.csv.gz  in=394,522,498 out=113,089,395 elapsed=182.3s

  [15506/21087] intraday_4418.csv.gz  in=394,534,612 out=113,089,395 elapsed=182.3s

  [15507/21087] intraday_4419.csv.gz  in=394,546,246 out=113,089,395 elapsed=182.3s

  [15508/21087] intraday_4420.csv.gz  in=394,558,946 out=113,089,395 elapsed=182.4s

  [15509/21087] intraday_4421.csv.gz  in=394,570,912 out=113,089,395 elapsed=182.4s

  [15510/21087] intraday_4422.csv.gz  in=394,581,242 out=113,089,395 elapsed=182.4s

  [15511/21087] intraday_4423.csv.gz  in=394,594,157 out=113,089,395 elapsed=182.4s

  [15512/21087] intraday_4424.csv.gz  in=394,606,540 out=113,089,395 elapsed=182.4s

  [15513/21087] intraday_4425.csv.gz  in=394,620,789 out=113,089,395 elapsed=182.4s

  [15514/21087] intraday_4426.csv.gz  in=394,636,288 out=113,089,395 elapsed=182.4s

  [15515/21087] intraday_4428.csv.gz  in=394,647,862 out=113,089,395 elapsed=182.4s

  [15516/21087] intraday_4427.csv.gz  in=394,661,530 out=113,089,395 elapsed=182.4s

  [15517/21087] intraday_4429.csv.gz  in=394,673,695 out=113,089,395 elapsed=182.4s

  [15518/21087] intraday_4430.csv.gz  in=394,686,816 out=113,089,395 elapsed=182.4s

  [15519/21087] intraday_4431.csv.gz  in=394,698,261 out=113,089,395 elapsed=182.4s

  [15520/21087] intraday_4433.csv.gz  in=394,709,105 out=113,089,395 elapsed=182.4s

  [15521/21087] intraday_4432.csv.gz  in=394,721,158 out=113,089,395 elapsed=182.5s

  [15522/21087] intraday_4434.csv.gz  in=394,732,118 out=113,089,395 elapsed=182.5s

  [15523/21087] intraday_4435.csv.gz  in=394,743,022 out=113,089,395 elapsed=182.5s

  [15524/21087] intraday_4436.csv.gz  in=394,755,281 out=113,089,395 elapsed=182.5s

  [15525/21087] intraday_4437.csv.gz  in=394,773,894 out=113,089,395 elapsed=182.5s

  [15526/21087] intraday_4438.csv.gz  in=394,785,499 out=113,089,395 elapsed=182.5s

  [15527/21087] intraday_4440.csv.gz  in=394,796,472 out=113,089,395 elapsed=182.5s

  [15528/21087] intraday_4439.csv.gz  in=394,809,560 out=113,089,395 elapsed=182.5s

  [15529/21087] intraday_4441.csv.gz  in=394,821,433 out=113,089,395 elapsed=182.5s

  [15530/21087] intraday_4442.csv.gz  in=394,834,154 out=113,089,395 elapsed=182.5s

  [15531/21087] intraday_4444.csv.gz  in=394,846,544 out=113,089,395 elapsed=182.5s

  [15532/21087] intraday_4443.csv.gz  in=394,857,546 out=113,089,395 elapsed=182.5s

  [15533/21087] intraday_4445.csv.gz  in=394,871,424 out=113,089,395 elapsed=182.5s

  [15534/21087] intraday_4446.csv.gz  in=394,881,361 out=113,089,395 elapsed=182.6s

  [15535/21087] intraday_4447.csv.gz  in=394,894,563 out=113,089,395 elapsed=182.6s

  [15536/21087] intraday_4448.csv.gz  in=394,905,473 out=113,089,395 elapsed=182.6s

  [15537/21087] intraday_4449.csv.gz  in=394,916,532 out=113,089,395 elapsed=182.6s

  [15538/21087] intraday_4450.csv.gz  in=394,929,603 out=113,089,395 elapsed=182.6s

  [15539/21087] intraday_4452.csv.gz  in=394,941,157 out=113,089,395 elapsed=182.6s

  [15540/21087] intraday_4451.csv.gz  in=394,954,022 out=113,089,395 elapsed=182.6s

  [15541/21087] intraday_4453.csv.gz  in=394,964,147 out=113,089,395 elapsed=182.6s

  [15542/21087] intraday_4454.csv.gz  in=394,977,741 out=113,089,395 elapsed=182.6s

  [15543/21087] intraday_4455.csv.gz  in=394,989,596 out=113,089,395 elapsed=182.6s

  [15544/21087] intraday_4457.csv.gz  in=395,000,361 out=113,089,395 elapsed=182.6s

  [15545/21087] intraday_4456.csv.gz  in=395,012,442 out=113,089,395 elapsed=182.6s

  [15546/21087] intraday_4458.csv.gz  in=395,024,246 out=113,089,395 elapsed=182.6s

  [15547/21087] intraday_4459.csv.gz  in=395,035,338 out=113,089,395 elapsed=182.7s

  [15548/21087] intraday_4460.csv.gz  in=395,049,153 out=113,089,395 elapsed=182.7s

  [15549/21087] intraday_4461.csv.gz  in=395,062,009 out=113,089,395 elapsed=182.7s

  [15550/21087] intraday_4462.csv.gz  in=395,075,360 out=113,089,395 elapsed=182.7s

  [15551/21087] intraday_4463.csv.gz  in=395,087,588 out=113,089,395 elapsed=182.7s

  [15552/21087] intraday_4464.csv.gz  in=395,098,397 out=113,089,395 elapsed=182.7s

  [15553/21087] intraday_4465.csv.gz  in=395,109,856 out=113,089,395 elapsed=182.7s

  [15554/21087] intraday_4466.csv.gz  in=395,121,429 out=113,089,395 elapsed=182.7s

  [15555/21087] intraday_4467.csv.gz  in=395,132,796 out=113,089,395 elapsed=182.7s

  [15556/21087] intraday_4468.csv.gz  in=395,145,837 out=113,089,395 elapsed=182.7s

  [15557/21087] intraday_4469.csv.gz  in=395,156,772 out=113,089,395 elapsed=182.7s

  [15558/21087] intraday_4470.csv.gz  in=395,166,722 out=113,089,395 elapsed=182.7s

  [15559/21087] intraday_4471.csv.gz  in=395,178,894 out=113,089,395 elapsed=182.7s

  [15560/21087] intraday_4473.csv.gz  in=395,189,395 out=113,089,395 elapsed=182.8s

  [15561/21087] intraday_4472.csv.gz  in=395,204,482 out=113,089,395 elapsed=182.8s

  [15562/21087] intraday_4474.csv.gz  in=395,216,512 out=113,089,395 elapsed=182.8s

  [15563/21087] intraday_4475.csv.gz  in=395,226,515 out=113,089,395 elapsed=182.8s

  [15564/21087] intraday_4476.csv.gz  in=395,237,872 out=113,089,395 elapsed=182.8s

  [15565/21087] intraday_4477.csv.gz  in=395,251,152 out=113,089,395 elapsed=182.8s

  [15566/21087] intraday_4479.csv.gz  in=395,262,405 out=113,089,395 elapsed=182.8s

  [15567/21087] intraday_4478.csv.gz  in=395,277,673 out=113,089,395 elapsed=182.8s

  [15568/21087] intraday_4480.csv.gz  in=395,288,741 out=113,089,395 elapsed=182.8s

  [15569/21087] intraday_4481.csv.gz  in=395,307,378 out=113,089,395 elapsed=182.8s

  [15570/21087] intraday_4482.csv.gz  in=395,320,695 out=113,089,395 elapsed=182.8s

  [15571/21087] intraday_4484.csv.gz  in=395,335,643 out=113,089,395 elapsed=182.8s

  [15572/21087] intraday_4483.csv.gz  in=395,348,918 out=113,089,395 elapsed=182.8s

  [15573/21087] intraday_4485.csv.gz  in=395,359,463 out=113,089,395 elapsed=182.9s

  [15574/21087] intraday_4486.csv.gz  in=395,374,081 out=113,089,395 elapsed=182.9s

  [15575/21087] intraday_4487.csv.gz  in=395,387,121 out=113,089,395 elapsed=182.9s

  [15576/21087] intraday_4488.csv.gz  in=395,401,716 out=113,089,395 elapsed=182.9s

  [15577/21087] intraday_4489.csv.gz  in=395,414,735 out=113,089,395 elapsed=182.9s

  [15578/21087] intraday_4490.csv.gz  in=395,427,000 out=113,089,395 elapsed=182.9s

  [15579/21087] intraday_4491.csv.gz  in=395,438,488 out=113,089,395 elapsed=182.9s

  [15580/21087] intraday_4492.csv.gz  in=395,450,238 out=113,089,395 elapsed=182.9s

  [15581/21087] intraday_4493.csv.gz  in=395,461,513 out=113,089,395 elapsed=182.9s

  [15582/21087] intraday_4494.csv.gz  in=395,472,508 out=113,089,395 elapsed=182.9s

  [15583/21087] intraday_4495.csv.gz  in=395,484,511 out=113,089,395 elapsed=182.9s

  [15584/21087] intraday_4496.csv.gz  in=395,495,647 out=113,089,395 elapsed=182.9s

  [15585/21087] intraday_4497.csv.gz  in=395,508,853 out=113,089,395 elapsed=183.0s

  [15586/21087] intraday_4498.csv.gz  in=395,520,924 out=113,089,395 elapsed=183.0s

  [15587/21087] intraday_4499.csv.gz  in=395,533,673 out=113,089,395 elapsed=183.0s

  [15588/21087] intraday_4500.csv.gz  in=395,546,670 out=113,089,395 elapsed=183.0s

  [15589/21087] intraday_4501.csv.gz  in=395,559,757 out=113,089,395 elapsed=183.0s

  [15590/21087] intraday_4502.csv.gz  in=395,577,263 out=113,089,395 elapsed=183.0s

  [15591/21087] intraday_4503.csv.gz  in=395,590,356 out=113,089,395 elapsed=183.0s

  [15592/21087] intraday_4504.csv.gz  in=395,604,486 out=113,089,395 elapsed=183.0s

  [15593/21087] intraday_4505.csv.gz  in=395,615,061 out=113,089,395 elapsed=183.0s

  [15594/21087] intraday_4506.csv.gz  in=395,629,871 out=113,089,395 elapsed=183.0s

  [15595/21087] intraday_4507.csv.gz  in=395,641,891 out=113,089,395 elapsed=183.0s

  [15596/21087] intraday_4508.csv.gz  in=395,655,685 out=113,089,395 elapsed=183.1s

  [15597/21087] intraday_4509.csv.gz  in=395,669,337 out=113,089,395 elapsed=183.1s

  [15598/21087] intraday_4511.csv.gz  in=395,682,000 out=113,089,395 elapsed=183.1s

  [15599/21087] intraday_4510.csv.gz  in=395,696,185 out=113,089,395 elapsed=183.1s

  [15600/21087] intraday_4512.csv.gz  in=395,712,024 out=113,089,395 elapsed=183.1s

  [15601/21087] intraday_4513.csv.gz  in=395,724,782 out=113,089,395 elapsed=183.1s

  [15602/21087] intraday_4514.csv.gz  in=395,736,330 out=113,089,395 elapsed=183.1s

  [15603/21087] intraday_4515.csv.gz  in=395,747,594 out=113,089,395 elapsed=183.1s

  [15604/21087] intraday_4516.csv.gz  in=395,761,798 out=113,089,395 elapsed=183.1s

  [15605/21087] intraday_4517.csv.gz  in=395,771,797 out=113,089,395 elapsed=183.1s

  [15606/21087] intraday_4518.csv.gz  in=395,785,901 out=113,089,395 elapsed=183.1s

  [15607/21087] intraday_4519.csv.gz  in=395,799,827 out=113,089,395 elapsed=183.1s

  [15608/21087] intraday_4520.csv.gz  in=395,816,519 out=113,089,395 elapsed=183.2s

  [15609/21087] intraday_4521.csv.gz  in=395,827,526 out=113,089,395 elapsed=183.2s

  [15610/21087] intraday_4522.csv.gz  in=395,840,378 out=113,089,395 elapsed=183.2s

  [15611/21087] intraday_4523.csv.gz  in=395,853,609 out=113,089,395 elapsed=183.2s

  [15612/21087] intraday_4524.csv.gz  in=395,865,593 out=113,089,395 elapsed=183.2s

  [15613/21087] intraday_4525.csv.gz  in=395,877,341 out=113,089,395 elapsed=183.2s

  [15614/21087] intraday_4526.csv.gz  in=395,891,780 out=113,089,395 elapsed=183.2s

  [15615/21087] intraday_4527.csv.gz  in=395,906,951 out=113,089,395 elapsed=183.2s

  [15616/21087] intraday_4528.csv.gz  in=395,919,495 out=113,089,395 elapsed=183.2s

  [15617/21087] intraday_4529.csv.gz  in=395,933,249 out=113,089,395 elapsed=183.2s

  [15618/21087] intraday_4530.csv.gz  in=395,944,449 out=113,089,395 elapsed=183.2s

  [15619/21087] intraday_4531.csv.gz  in=395,955,654 out=113,089,395 elapsed=183.2s

  [15620/21087] intraday_4532.csv.gz  in=395,967,982 out=113,089,395 elapsed=183.2s

  [15621/21087] intraday_4533.csv.gz  in=395,980,732 out=113,089,395 elapsed=183.3s

  [15622/21087] intraday_4534.csv.gz  in=395,989,710 out=113,089,395 elapsed=183.3s

  [15623/21087] intraday_4535.csv.gz  in=395,998,569 out=113,089,395 elapsed=183.3s

  [15624/21087] intraday_4537.csv.gz  in=395,998,878 out=113,089,395 elapsed=183.3s

  [15625/21087] intraday_4536.csv.gz  in=396,010,693 out=113,089,395 elapsed=183.3s

  [15626/21087] intraday_4538.csv.gz  in=396,025,880 out=113,089,395 elapsed=183.3s

  [15627/21087] intraday_4539.csv.gz  in=396,039,769 out=113,089,395 elapsed=183.3s

  [15628/21087] intraday_4540.csv.gz  in=396,052,152 out=113,089,395 elapsed=183.3s

  [15629/21087] intraday_4541.csv.gz  in=396,062,698 out=113,089,395 elapsed=183.3s

  [15630/21087] intraday_4542.csv.gz  in=396,077,898 out=113,089,395 elapsed=183.3s

  [15631/21087] intraday_4543.csv.gz  in=396,099,659 out=113,089,395 elapsed=183.3s

  [15632/21087] intraday_4544.csv.gz  in=396,113,631 out=113,089,395 elapsed=183.3s

  [15633/21087] intraday_4545.csv.gz  in=396,126,365 out=113,089,395 elapsed=183.3s

  [15634/21087] intraday_4546.csv.gz  in=396,139,877 out=113,089,395 elapsed=183.3s

  [15635/21087] intraday_4547.csv.gz  in=396,155,011 out=113,089,395 elapsed=183.4s

  [15636/21087] intraday_4548.csv.gz  in=396,165,497 out=113,089,395 elapsed=183.4s

  [15637/21087] intraday_4550.csv.gz  in=396,178,074 out=113,089,395 elapsed=183.4s

  [15638/21087] intraday_4549.csv.gz  in=396,190,673 out=113,089,395 elapsed=183.4s

  [15639/21087] intraday_4551.csv.gz  in=396,201,858 out=113,089,395 elapsed=183.4s

  [15640/21087] intraday_4553.csv.gz  in=396,212,827 out=113,089,395 elapsed=183.4s

  [15641/21087] intraday_4554.csv.gz  in=396,225,958 out=113,089,395 elapsed=183.4s

  [15642/21087] intraday_4552.csv.gz  in=396,236,737 out=113,089,395 elapsed=183.4s

  [15643/21087] intraday_4555.csv.gz  in=396,249,451 out=113,089,395 elapsed=183.4s

  [15644/21087] intraday_4556.csv.gz  in=396,260,159 out=113,089,395 elapsed=183.4s

  [15645/21087] intraday_4558.csv.gz  in=396,273,428 out=113,089,395 elapsed=183.5s

  [15646/21087] intraday_4557.csv.gz  in=396,285,777 out=113,089,395 elapsed=183.5s

  [15647/21087] intraday_4559.csv.gz  in=396,298,908 out=113,089,395 elapsed=183.5s

  [15648/21087] intraday_4560.csv.gz  in=396,311,189 out=113,089,395 elapsed=183.5s

  [15649/21087] intraday_4562.csv.gz  in=396,322,556 out=113,089,395 elapsed=183.5s

  [15650/21087] intraday_4561.csv.gz  in=396,337,052 out=113,089,395 elapsed=183.5s

  [15651/21087] intraday_4563.csv.gz  in=396,347,818 out=113,089,395 elapsed=183.5s

  [15652/21087] intraday_4564.csv.gz  in=396,360,225 out=113,089,395 elapsed=183.5s

  [15653/21087] intraday_4565.csv.gz  in=396,372,660 out=113,089,395 elapsed=183.5s

  [15654/21087] intraday_4566.csv.gz  in=396,387,004 out=113,089,395 elapsed=183.5s

  [15655/21087] intraday_4567.csv.gz  in=396,401,958 out=113,089,395 elapsed=183.5s

  [15656/21087] intraday_4568.csv.gz  in=396,414,917 out=113,089,395 elapsed=183.5s

  [15657/21087] intraday_4569.csv.gz  in=396,426,380 out=113,089,395 elapsed=183.5s

  [15658/21087] intraday_4570.csv.gz  in=396,437,865 out=113,089,395 elapsed=183.6s

  [15659/21087] intraday_4571.csv.gz  in=396,451,739 out=113,089,395 elapsed=183.6s

  [15660/21087] intraday_4572.csv.gz  in=396,462,322 out=113,089,395 elapsed=183.6s

  [15661/21087] intraday_4573.csv.gz  in=396,475,267 out=113,089,395 elapsed=183.6s

  [15662/21087] intraday_4574.csv.gz  in=396,486,136 out=113,089,395 elapsed=183.6s

  [15663/21087] intraday_4575.csv.gz  in=396,496,709 out=113,089,395 elapsed=183.6s

  [15664/21087] intraday_4576.csv.gz  in=396,508,527 out=113,089,395 elapsed=183.6s

  [15665/21087] intraday_4577.csv.gz  in=396,520,585 out=113,089,395 elapsed=183.6s

  [15666/21087] intraday_4578.csv.gz  in=396,532,606 out=113,089,395 elapsed=183.6s

  [15667/21087] intraday_4579.csv.gz  in=396,545,491 out=113,089,395 elapsed=183.6s

  [15668/21087] intraday_4580.csv.gz  in=396,559,356 out=113,089,395 elapsed=183.6s

  [15669/21087] intraday_4581.csv.gz  in=396,570,239 out=113,089,395 elapsed=183.6s

  [15670/21087] intraday_4582.csv.gz  in=396,584,198 out=113,089,395 elapsed=183.7s

  [15671/21087] intraday_4583.csv.gz  in=396,595,903 out=113,089,395 elapsed=183.7s

  [15672/21087] intraday_4584.csv.gz  in=396,607,055 out=113,089,395 elapsed=183.7s

  [15673/21087] intraday_4585.csv.gz  in=396,619,139 out=113,089,395 elapsed=183.7s

  [15674/21087] intraday_4586.csv.gz  in=396,630,259 out=113,089,395 elapsed=183.7s

  [15675/21087] intraday_4587.csv.gz  in=396,639,867 out=113,089,395 elapsed=183.7s

  [15676/21087] intraday_4588.csv.gz  in=396,653,961 out=113,089,395 elapsed=183.7s

  [15677/21087] intraday_4589.csv.gz  in=396,663,785 out=113,089,395 elapsed=183.7s

  [15678/21087] intraday_4590.csv.gz  in=396,675,546 out=113,089,395 elapsed=183.7s

  [15679/21087] intraday_4591.csv.gz  in=396,687,053 out=113,089,395 elapsed=183.7s

  [15680/21087] intraday_4593.csv.gz  in=396,698,663 out=113,089,395 elapsed=183.7s

  [15681/21087] intraday_4592.csv.gz  in=396,710,597 out=113,089,395 elapsed=183.7s

  [15682/21087] intraday_4594.csv.gz  in=396,720,971 out=113,089,395 elapsed=183.7s

  [15683/21087] intraday_4596.csv.gz  in=396,731,680 out=113,089,395 elapsed=183.7s

  [15684/21087] intraday_4597.csv.gz  in=396,744,019 out=113,089,395 elapsed=183.8s

  [15685/21087] intraday_4595.csv.gz  in=396,759,957 out=113,089,395 elapsed=183.8s

  [15686/21087] intraday_4598.csv.gz  in=396,771,131 out=113,089,395 elapsed=183.8s

  [15687/21087] intraday_4600.csv.gz  in=396,782,325 out=113,089,395 elapsed=183.8s

  [15688/21087] intraday_4599.csv.gz  in=396,802,980 out=113,089,395 elapsed=183.8s

  [15689/21087] intraday_4601.csv.gz  in=396,816,949 out=113,089,395 elapsed=183.8s

  [15690/21087] intraday_4602.csv.gz  in=396,830,404 out=113,089,395 elapsed=183.8s

  [15691/21087] intraday_4603.csv.gz  in=396,843,963 out=113,089,395 elapsed=183.8s

  [15692/21087] intraday_4604.csv.gz  in=396,856,056 out=113,089,395 elapsed=183.8s

  [15693/21087] intraday_4605.csv.gz  in=396,865,808 out=113,089,395 elapsed=183.8s

  [15694/21087] intraday_4606.csv.gz  in=396,889,669 out=113,089,395 elapsed=183.8s

  [15695/21087] intraday_4607.csv.gz  in=396,900,795 out=113,089,395 elapsed=183.8s

  [15696/21087] intraday_4608.csv.gz  in=396,913,070 out=113,089,395 elapsed=183.8s

  [15697/21087] intraday_4609.csv.gz  in=396,925,751 out=113,089,395 elapsed=183.8s

  [15698/21087] intraday_4610.csv.gz  in=396,937,448 out=113,089,395 elapsed=183.9s

  [15699/21087] intraday_4611.csv.gz  in=396,947,460 out=113,089,395 elapsed=183.9s

  [15700/21087] intraday_4612.csv.gz  in=396,959,490 out=113,089,395 elapsed=183.9s

  [15701/21087] intraday_4613.csv.gz  in=396,973,893 out=113,089,395 elapsed=183.9s

  [15702/21087] intraday_4614.csv.gz  in=396,985,373 out=113,089,395 elapsed=183.9s

  [15703/21087] intraday_4615.csv.gz  in=396,997,847 out=113,089,395 elapsed=183.9s

  [15704/21087] intraday_4616.csv.gz  in=397,008,177 out=113,089,395 elapsed=183.9s

  [15705/21087] intraday_4617.csv.gz  in=397,019,624 out=113,089,395 elapsed=183.9s

  [15706/21087] intraday_4618.csv.gz  in=397,032,366 out=113,089,395 elapsed=183.9s

  [15707/21087] intraday_4619.csv.gz  in=397,049,397 out=113,089,395 elapsed=183.9s

  [15708/21087] intraday_4620.csv.gz  in=397,062,467 out=113,089,395 elapsed=183.9s

  [15709/21087] intraday_4621.csv.gz  in=397,073,825 out=113,089,395 elapsed=183.9s

  [15710/21087] intraday_4622.csv.gz  in=397,084,268 out=113,089,395 elapsed=184.0s

  [15711/21087] intraday_4623.csv.gz  in=397,098,301 out=113,089,395 elapsed=184.0s

  [15712/21087] intraday_4624.csv.gz  in=397,113,063 out=113,089,395 elapsed=184.0s

  [15713/21087] intraday_4625.csv.gz  in=397,127,502 out=113,089,395 elapsed=184.0s

  [15714/21087] intraday_4626.csv.gz  in=397,138,284 out=113,089,395 elapsed=184.0s

  [15715/21087] intraday_4627.csv.gz  in=397,154,941 out=113,089,395 elapsed=184.0s

  [15716/21087] intraday_4628.csv.gz  in=397,168,865 out=113,089,395 elapsed=184.0s

  [15717/21087] intraday_4630.csv.gz  in=397,182,929 out=113,089,395 elapsed=184.0s

  [15718/21087] intraday_4629.csv.gz  in=397,200,405 out=113,089,395 elapsed=184.0s

  [15719/21087] intraday_4631.csv.gz  in=397,212,432 out=113,089,395 elapsed=184.0s

  [15720/21087] intraday_4632.csv.gz  in=397,223,987 out=113,089,395 elapsed=184.0s

  [15721/21087] intraday_4634.csv.gz  in=397,235,208 out=113,089,395 elapsed=184.0s

  [15722/21087] intraday_4633.csv.gz  in=397,247,391 out=113,089,395 elapsed=184.1s

  [15723/21087] intraday_4635.csv.gz  in=397,258,780 out=113,089,395 elapsed=184.1s

  [15724/21087] intraday_4636.csv.gz  in=397,270,146 out=113,089,395 elapsed=184.1s

  [15725/21087] intraday_4637.csv.gz  in=397,282,458 out=113,089,395 elapsed=184.1s

  [15726/21087] intraday_4640.csv.gz  in=397,296,132 out=113,089,395 elapsed=184.1s

  [15727/21087] intraday_4638.csv.gz  in=397,312,563 out=113,089,395 elapsed=184.1s

  [15728/21087] intraday_4639.csv.gz  in=397,324,730 out=113,089,395 elapsed=184.1s

  [15729/21087] intraday_4641.csv.gz  in=397,337,502 out=113,089,395 elapsed=184.1s

  [15730/21087] intraday_4642.csv.gz  in=397,350,050 out=113,089,395 elapsed=184.1s

  [15731/21087] intraday_4643.csv.gz  in=397,362,555 out=113,089,395 elapsed=184.1s

  [15732/21087] intraday_4644.csv.gz  in=397,376,388 out=113,089,395 elapsed=184.1s

  [15733/21087] intraday_4645.csv.gz  in=397,389,443 out=113,089,395 elapsed=184.1s

  [15734/21087] intraday_4646.csv.gz  in=397,400,968 out=113,089,395 elapsed=184.2s

  [15735/21087] intraday_4647.csv.gz  in=397,415,140 out=113,089,395 elapsed=184.2s

  [15736/21087] intraday_4649.csv.gz  in=397,429,935 out=113,089,395 elapsed=184.2s

  [15737/21087] intraday_4648.csv.gz  in=397,443,177 out=113,089,395 elapsed=184.2s

  [15738/21087] intraday_4650.csv.gz  in=397,457,561 out=113,089,395 elapsed=184.2s

  [15739/21087] intraday_4651.csv.gz  in=397,470,564 out=113,089,395 elapsed=184.2s

  [15740/21087] intraday_4652.csv.gz  in=397,485,245 out=113,089,395 elapsed=184.2s

  [15741/21087] intraday_4653.csv.gz  in=397,499,613 out=113,089,395 elapsed=184.2s

  [15742/21087] intraday_4654.csv.gz  in=397,512,602 out=113,089,395 elapsed=184.2s

  [15743/21087] intraday_4655.csv.gz  in=397,524,209 out=113,089,395 elapsed=184.2s

  [15744/21087] intraday_4656.csv.gz  in=397,534,560 out=113,089,395 elapsed=184.2s

  [15745/21087] intraday_4657.csv.gz  in=397,547,560 out=113,089,395 elapsed=184.2s

  [15746/21087] intraday_4658.csv.gz  in=397,559,007 out=113,089,395 elapsed=184.3s

  [15747/21087] intraday_4660.csv.gz  in=397,572,647 out=113,089,395 elapsed=184.3s

  [15748/21087] intraday_4659.csv.gz  in=397,587,147 out=113,089,395 elapsed=184.3s

  [15749/21087] intraday_4661.csv.gz  in=397,604,576 out=113,089,395 elapsed=184.3s

  [15750/21087] intraday_4662.csv.gz  in=397,616,685 out=113,089,395 elapsed=184.3s

  [15751/21087] intraday_4663.csv.gz  in=397,630,254 out=113,089,395 elapsed=184.3s

  [15752/21087] intraday_4664.csv.gz  in=397,643,696 out=113,089,395 elapsed=184.3s

  [15753/21087] intraday_4665.csv.gz  in=397,655,078 out=113,089,395 elapsed=184.3s

  [15754/21087] intraday_4666.csv.gz  in=397,667,883 out=113,089,395 elapsed=184.3s

  [15755/21087] intraday_4667.csv.gz  in=397,682,932 out=113,089,395 elapsed=184.3s

  [15756/21087] intraday_4669.csv.gz  in=397,695,607 out=113,089,395 elapsed=184.3s

  [15757/21087] intraday_4668.csv.gz  in=397,709,794 out=113,089,395 elapsed=184.3s

  [15758/21087] intraday_4670.csv.gz  in=397,726,361 out=113,089,395 elapsed=184.3s

  [15759/21087] intraday_4671.csv.gz  in=397,737,220 out=113,089,395 elapsed=184.3s

  [15760/21087] intraday_4672.csv.gz  in=397,748,560 out=113,089,395 elapsed=184.4s

  [15761/21087] intraday_4673.csv.gz  in=397,760,155 out=113,089,395 elapsed=184.4s

  [15762/21087] intraday_4675.csv.gz  in=397,769,354 out=113,089,395 elapsed=184.4s

  [15763/21087] intraday_4674.csv.gz  in=397,782,762 out=113,089,395 elapsed=184.4s

  [15764/21087] intraday_4676.csv.gz  in=397,797,047 out=113,089,395 elapsed=184.4s

  [15765/21087] intraday_4678.csv.gz  in=397,797,319 out=113,089,395 elapsed=184.4s

  [15766/21087] intraday_4679.csv.gz  in=397,811,622 out=113,089,395 elapsed=184.4s

  [15767/21087] intraday_4677.csv.gz  in=397,823,085 out=113,089,395 elapsed=184.4s

  [15768/21087] intraday_4680.csv.gz  in=397,836,852 out=113,089,395 elapsed=184.4s

  [15769/21087] intraday_4681.csv.gz  in=397,848,665 out=113,089,395 elapsed=184.4s

  [15770/21087] intraday_4682.csv.gz  in=397,858,468 out=113,089,395 elapsed=184.4s

  [15771/21087] intraday_4683.csv.gz  in=397,873,423 out=113,089,395 elapsed=184.5s

  [15772/21087] intraday_4685.csv.gz  in=397,885,553 out=113,089,395 elapsed=184.5s

  [15773/21087] intraday_4684.csv.gz  in=397,901,729 out=113,089,395 elapsed=184.5s

  [15774/21087] intraday_4686.csv.gz  in=397,914,043 out=113,089,395 elapsed=184.5s

  [15775/21087] intraday_4687.csv.gz  in=397,927,593 out=113,089,395 elapsed=184.5s

  [15776/21087] intraday_4688.csv.gz  in=397,941,554 out=113,089,395 elapsed=184.5s

  [15777/21087] intraday_4689.csv.gz  in=397,952,202 out=113,089,395 elapsed=184.5s

  [15778/21087] intraday_4690.csv.gz  in=397,964,025 out=113,089,395 elapsed=184.5s

  [15779/21087] intraday_4691.csv.gz  in=397,977,136 out=113,089,395 elapsed=184.5s

  [15780/21087] intraday_4692.csv.gz  in=397,987,263 out=113,089,395 elapsed=184.5s

  [15781/21087] intraday_4693.csv.gz  in=397,997,892 out=113,089,395 elapsed=184.5s

  [15782/21087] intraday_4694.csv.gz  in=398,007,805 out=113,089,395 elapsed=184.5s

  [15783/21087] intraday_4695.csv.gz  in=398,020,862 out=113,089,395 elapsed=184.5s

  [15784/21087] intraday_4696.csv.gz  in=398,033,057 out=113,089,395 elapsed=184.6s

  [15785/21087] intraday_4697.csv.gz  in=398,043,029 out=113,089,395 elapsed=184.6s

  [15786/21087] intraday_4698.csv.gz  in=398,054,979 out=113,089,395 elapsed=184.6s

  [15787/21087] intraday_4699.csv.gz  in=398,067,865 out=113,089,395 elapsed=184.6s

  [15788/21087] intraday_4700.csv.gz  in=398,081,108 out=113,089,395 elapsed=184.6s

  [15789/21087] intraday_4701.csv.gz  in=398,095,066 out=113,089,395 elapsed=184.6s

  [15790/21087] intraday_4703.csv.gz  in=398,106,890 out=113,089,395 elapsed=184.6s

  [15791/21087] intraday_4702.csv.gz  in=398,118,687 out=113,089,395 elapsed=184.6s

  [15792/21087] intraday_4704.csv.gz  in=398,128,696 out=113,089,395 elapsed=184.6s

  [15793/21087] intraday_4705.csv.gz  in=398,140,832 out=113,089,395 elapsed=184.6s

  [15794/21087] intraday_4706.csv.gz  in=398,156,891 out=113,089,395 elapsed=184.6s

  [15795/21087] intraday_4707.csv.gz  in=398,169,465 out=113,089,395 elapsed=184.6s

  [15796/21087] intraday_4708.csv.gz  in=398,183,302 out=113,089,395 elapsed=184.6s

  [15797/21087] intraday_4709.csv.gz  in=398,198,092 out=113,089,395 elapsed=184.7s

  [15798/21087] intraday_4711.csv.gz  in=398,208,904 out=113,089,395 elapsed=184.7s

  [15799/21087] intraday_4710.csv.gz  in=398,219,854 out=113,089,395 elapsed=184.7s

  [15800/21087] intraday_4712.csv.gz  in=398,232,477 out=113,089,395 elapsed=184.7s

  [15801/21087] intraday_4714.csv.gz  in=398,244,775 out=113,089,395 elapsed=184.7s

  [15802/21087] intraday_4715.csv.gz  in=398,254,855 out=113,089,395 elapsed=184.7s

  [15803/21087] intraday_4713.csv.gz  in=398,280,914 out=113,089,395 elapsed=184.7s

  [15804/21087] intraday_4716.csv.gz  in=398,291,630 out=113,089,395 elapsed=184.7s

  [15805/21087] intraday_4718.csv.gz  in=398,303,134 out=113,089,395 elapsed=184.7s

  [15806/21087] intraday_4719.csv.gz  in=398,316,666 out=113,089,395 elapsed=184.7s

  [15807/21087] intraday_4717.csv.gz  in=398,347,014 out=113,089,395 elapsed=184.7s

  [15808/21087] intraday_4720.csv.gz  in=398,368,480 out=113,089,395 elapsed=184.7s

  [15809/21087] intraday_4721.csv.gz  in=398,380,535 out=113,089,395 elapsed=184.8s

  [15810/21087] intraday_4722.csv.gz  in=398,391,554 out=113,089,395 elapsed=184.8s

  [15811/21087] intraday_4723.csv.gz  in=398,402,898 out=113,089,395 elapsed=184.8s

  [15812/21087] intraday_4724.csv.gz  in=398,415,791 out=113,089,395 elapsed=184.8s

  [15813/21087] intraday_4725.csv.gz  in=398,425,846 out=113,089,395 elapsed=184.8s

  [15814/21087] intraday_4726.csv.gz  in=398,437,281 out=113,089,395 elapsed=184.8s

  [15815/21087] intraday_4727.csv.gz  in=398,448,544 out=113,089,395 elapsed=184.8s

  [15816/21087] intraday_4728.csv.gz  in=398,458,076 out=113,089,395 elapsed=184.8s

  [15817/21087] intraday_4729.csv.gz  in=398,469,235 out=113,089,395 elapsed=184.8s

  [15818/21087] intraday_4730.csv.gz  in=398,480,674 out=113,089,395 elapsed=184.8s

  [15819/21087] intraday_4731.csv.gz  in=398,496,389 out=113,089,395 elapsed=184.8s

  [15820/21087] intraday_4732.csv.gz  in=398,508,891 out=113,089,395 elapsed=184.8s

  [15821/21087] intraday_4733.csv.gz  in=398,520,948 out=113,089,395 elapsed=184.9s

  [15822/21087] intraday_4734.csv.gz  in=398,530,629 out=113,089,395 elapsed=184.9s

  [15823/21087] intraday_4735.csv.gz  in=398,541,443 out=113,089,395 elapsed=184.9s

  [15824/21087] intraday_4736.csv.gz  in=398,553,388 out=113,089,395 elapsed=184.9s

  [15825/21087] intraday_4737.csv.gz  in=398,565,860 out=113,089,395 elapsed=184.9s

  [15826/21087] intraday_4738.csv.gz  in=398,577,660 out=113,089,395 elapsed=184.9s

  [15827/21087] intraday_4739.csv.gz  in=398,589,950 out=113,089,395 elapsed=184.9s

  [15828/21087] intraday_4740.csv.gz  in=398,601,986 out=113,089,395 elapsed=184.9s

  [15829/21087] intraday_4741.csv.gz  in=398,612,409 out=113,089,395 elapsed=184.9s

  [15830/21087] intraday_4742.csv.gz  in=398,627,973 out=113,089,395 elapsed=184.9s

  [15831/21087] intraday_4743.csv.gz  in=398,641,182 out=113,089,395 elapsed=184.9s

  [15832/21087] intraday_4744.csv.gz  in=398,654,458 out=113,089,395 elapsed=184.9s

  [15833/21087] intraday_4745.csv.gz  in=398,665,480 out=113,089,395 elapsed=184.9s

  [15834/21087] intraday_4746.csv.gz  in=398,676,966 out=113,089,395 elapsed=185.0s

  [15835/21087] intraday_4747.csv.gz  in=398,686,462 out=113,089,395 elapsed=185.0s

  [15836/21087] intraday_4748.csv.gz  in=398,698,676 out=113,089,395 elapsed=185.0s

  [15837/21087] intraday_4749.csv.gz  in=398,709,987 out=113,089,395 elapsed=185.0s

  [15838/21087] intraday_4750.csv.gz  in=398,723,304 out=113,089,395 elapsed=185.0s

  [15839/21087] intraday_4751.csv.gz  in=398,733,896 out=113,089,395 elapsed=185.0s

  [15840/21087] intraday_4752.csv.gz  in=398,744,956 out=113,089,395 elapsed=185.0s

  [15841/21087] intraday_4753.csv.gz  in=398,755,401 out=113,089,395 elapsed=185.0s

  [15842/21087] intraday_4754.csv.gz  in=398,768,908 out=113,089,395 elapsed=185.0s

  [15843/21087] intraday_4755.csv.gz  in=398,780,797 out=113,089,395 elapsed=185.0s

  [15844/21087] intraday_4756.csv.gz  in=398,793,587 out=113,089,395 elapsed=185.0s

  [15845/21087] intraday_4757.csv.gz  in=398,803,815 out=113,089,395 elapsed=185.0s

  [15846/21087] intraday_4758.csv.gz  in=398,813,690 out=113,089,395 elapsed=185.0s

  [15847/21087] intraday_4759.csv.gz  in=398,824,928 out=113,089,395 elapsed=185.1s

  [15848/21087] intraday_4760.csv.gz  in=398,840,824 out=113,089,395 elapsed=185.1s

  [15849/21087] intraday_4761.csv.gz  in=398,855,111 out=113,089,395 elapsed=185.1s

  [15850/21087] intraday_4762.csv.gz  in=398,866,528 out=113,089,395 elapsed=185.1s

  [15851/21087] intraday_4763.csv.gz  in=398,877,515 out=113,089,395 elapsed=185.1s

  [15852/21087] intraday_4764.csv.gz  in=398,887,603 out=113,089,395 elapsed=185.1s

  [15853/21087] intraday_4765.csv.gz  in=398,900,782 out=113,089,395 elapsed=185.1s

  [15854/21087] intraday_4766.csv.gz  in=398,916,403 out=113,089,395 elapsed=185.1s

  [15855/21087] intraday_4767.csv.gz  in=398,928,522 out=113,089,395 elapsed=185.1s

  [15856/21087] intraday_4768.csv.gz  in=398,942,332 out=113,089,395 elapsed=185.1s

  [15857/21087] intraday_4769.csv.gz  in=398,955,017 out=113,089,395 elapsed=185.1s

  [15858/21087] intraday_4770.csv.gz  in=398,968,119 out=113,089,395 elapsed=185.1s

  [15859/21087] intraday_4771.csv.gz  in=398,985,138 out=113,089,395 elapsed=185.1s

  [15860/21087] intraday_4772.csv.gz  in=398,997,366 out=113,089,395 elapsed=185.2s

  [15861/21087] intraday_4773.csv.gz  in=399,017,023 out=113,089,395 elapsed=185.2s

  [15862/21087] intraday_4774.csv.gz  in=399,027,699 out=113,089,395 elapsed=185.2s

  [15863/21087] intraday_4775.csv.gz  in=399,038,629 out=113,089,395 elapsed=185.2s

  [15864/21087] intraday_4776.csv.gz  in=399,050,858 out=113,089,395 elapsed=185.2s

  [15865/21087] intraday_4777.csv.gz  in=399,062,089 out=113,089,395 elapsed=185.2s

  [15866/21087] intraday_4778.csv.gz  in=399,073,780 out=113,089,395 elapsed=185.2s

  [15867/21087] intraday_4779.csv.gz  in=399,087,838 out=113,089,395 elapsed=185.2s

  [15868/21087] intraday_4780.csv.gz  in=399,109,835 out=113,089,395 elapsed=185.2s

  [15869/21087] intraday_4781.csv.gz  in=399,138,473 out=113,089,395 elapsed=185.2s

  [15870/21087] intraday_4782.csv.gz  in=399,153,120 out=113,089,395 elapsed=185.2s

  [15871/21087] intraday_4783.csv.gz  in=399,163,553 out=113,089,395 elapsed=185.2s

  [15872/21087] intraday_4784.csv.gz  in=399,175,477 out=113,089,395 elapsed=185.3s

  [15873/21087] intraday_4785.csv.gz  in=399,188,346 out=113,089,395 elapsed=185.3s

  [15874/21087] intraday_4787.csv.gz  in=399,200,317 out=113,089,395 elapsed=185.3s

  [15875/21087] intraday_4786.csv.gz  in=399,214,614 out=113,089,395 elapsed=185.3s

  [15876/21087] intraday_4788.csv.gz  in=399,227,496 out=113,089,395 elapsed=185.3s

  [15877/21087] intraday_4789.csv.gz  in=399,240,453 out=113,089,395 elapsed=185.3s

  [15878/21087] intraday_4790.csv.gz  in=399,254,182 out=113,089,395 elapsed=185.3s

  [15879/21087] intraday_4791.csv.gz  in=399,269,118 out=113,089,395 elapsed=185.3s

  [15880/21087] intraday_4792.csv.gz  in=399,282,848 out=113,089,395 elapsed=185.3s

  [15881/21087] intraday_4793.csv.gz  in=399,293,715 out=113,089,395 elapsed=185.3s

  [15882/21087] intraday_4794.csv.gz  in=399,309,519 out=113,089,395 elapsed=185.3s

  [15883/21087] intraday_4795.csv.gz  in=399,321,767 out=113,089,395 elapsed=185.3s

  [15884/21087] intraday_4796.csv.gz  in=399,333,493 out=113,089,395 elapsed=185.4s

  [15885/21087] intraday_4797.csv.gz  in=399,344,025 out=113,089,395 elapsed=185.4s

  [15886/21087] intraday_4798.csv.gz  in=399,355,878 out=113,089,395 elapsed=185.4s

  [15887/21087] intraday_4799.csv.gz  in=399,369,858 out=113,089,395 elapsed=185.4s

  [15888/21087] intraday_4800.csv.gz  in=399,383,447 out=113,089,395 elapsed=185.4s

  [15889/21087] intraday_4801.csv.gz  in=399,410,407 out=113,089,395 elapsed=185.4s

  [15890/21087] intraday_4802.csv.gz  in=399,427,796 out=113,089,395 elapsed=185.4s

  [15891/21087] intraday_4803.csv.gz  in=399,439,170 out=113,089,395 elapsed=185.4s

  [15892/21087] intraday_4804.csv.gz  in=399,452,032 out=113,089,395 elapsed=185.4s

  [15893/21087] intraday_4805.csv.gz  in=399,462,996 out=113,089,395 elapsed=185.4s

  [15894/21087] intraday_4807.csv.gz  in=399,473,434 out=113,089,395 elapsed=185.4s

  [15895/21087] intraday_4806.csv.gz  in=399,486,332 out=113,089,395 elapsed=185.4s

  [15896/21087] intraday_4808.csv.gz  in=399,499,288 out=113,089,395 elapsed=185.5s

  [15897/21087] intraday_4809.csv.gz  in=399,513,595 out=113,089,395 elapsed=185.5s

  [15898/21087] intraday_4810.csv.gz  in=399,526,751 out=113,089,395 elapsed=185.5s

  [15899/21087] intraday_4811.csv.gz  in=399,540,074 out=113,089,395 elapsed=185.5s

  [15900/21087] intraday_4812.csv.gz  in=399,551,179 out=113,089,395 elapsed=185.5s

  [15901/21087] intraday_4813.csv.gz  in=399,562,986 out=113,089,395 elapsed=185.5s

  [15902/21087] intraday_4814.csv.gz  in=399,575,153 out=113,089,395 elapsed=185.5s

  [15903/21087] intraday_4815.csv.gz  in=399,586,521 out=113,089,395 elapsed=185.5s

  [15904/21087] intraday_4817.csv.gz  in=399,594,383 out=113,089,395 elapsed=185.5s

  [15905/21087] intraday_4816.csv.gz  in=399,605,504 out=113,089,395 elapsed=185.5s

  [15906/21087] intraday_4818.csv.gz  in=399,615,110 out=113,089,395 elapsed=185.5s

  [15907/21087] intraday_4819.csv.gz  in=399,628,876 out=113,089,395 elapsed=185.5s

  [15908/21087] intraday_4820.csv.gz  in=399,644,432 out=113,089,395 elapsed=185.6s

  [15909/21087] intraday_4821.csv.gz  in=399,658,604 out=113,089,395 elapsed=185.6s

  [15910/21087] intraday_4822.csv.gz  in=399,671,079 out=113,089,395 elapsed=185.6s

  [15911/21087] intraday_4823.csv.gz  in=399,680,537 out=113,089,395 elapsed=185.6s

  [15912/21087] intraday_4825.csv.gz  in=399,696,632 out=113,089,395 elapsed=185.6s

  [15913/21087] intraday_4824.csv.gz  in=399,711,465 out=113,089,395 elapsed=185.6s

  [15914/21087] intraday_4826.csv.gz  in=399,723,786 out=113,089,395 elapsed=185.6s

  [15915/21087] intraday_4827.csv.gz  in=399,735,177 out=113,089,395 elapsed=185.6s

  [15916/21087] intraday_4828.csv.gz  in=399,749,497 out=113,089,395 elapsed=185.6s

  [15917/21087] intraday_4829.csv.gz  in=399,763,204 out=113,089,395 elapsed=185.6s

  [15918/21087] intraday_4830.csv.gz  in=399,773,729 out=113,089,395 elapsed=185.6s

  [15919/21087] intraday_4831.csv.gz  in=399,785,820 out=113,089,395 elapsed=185.6s

  [15920/21087] intraday_4832.csv.gz  in=399,798,062 out=113,089,395 elapsed=185.7s

  [15921/21087] intraday_4833.csv.gz  in=399,811,838 out=113,089,395 elapsed=185.7s

  [15922/21087] intraday_4835.csv.gz  in=399,822,190 out=113,089,395 elapsed=185.7s

  [15923/21087] intraday_4834.csv.gz  in=399,832,952 out=113,089,395 elapsed=185.7s

  [15924/21087] intraday_4836.csv.gz  in=399,846,032 out=113,089,395 elapsed=185.7s

  [15925/21087] intraday_4837.csv.gz  in=399,858,004 out=113,089,395 elapsed=185.7s

  [15926/21087] intraday_4838.csv.gz  in=399,868,185 out=113,089,395 elapsed=185.7s

  [15927/21087] intraday_4839.csv.gz  in=399,879,803 out=113,089,395 elapsed=185.7s

  [15928/21087] intraday_4840.csv.gz  in=399,893,023 out=113,089,395 elapsed=185.7s

  [15929/21087] intraday_4841.csv.gz  in=399,906,119 out=113,089,395 elapsed=185.7s

  [15930/21087] intraday_4842.csv.gz  in=399,917,483 out=113,089,395 elapsed=185.7s

  [15931/21087] intraday_4843.csv.gz  in=399,929,812 out=113,089,395 elapsed=185.7s

  [15932/21087] intraday_4845.csv.gz  in=399,939,481 out=113,089,395 elapsed=185.8s

  [15933/21087] intraday_4847.csv.gz  in=399,951,127 out=113,089,395 elapsed=185.8s

  [15934/21087] intraday_4846.csv.gz  in=399,964,120 out=113,089,395 elapsed=185.8s

  [15935/21087] intraday_4844.csv.gz  in=399,996,375 out=113,089,395 elapsed=185.8s

  [15936/21087] intraday_4848.csv.gz  in=400,008,533 out=113,089,395 elapsed=185.8s

  [15937/21087] intraday_4852.csv.gz  in=400,019,630 out=113,089,395 elapsed=185.8s

  [15938/21087] intraday_4851.csv.gz  in=400,030,776 out=113,089,395 elapsed=185.8s

  [15939/21087] intraday_4850.csv.gz  in=400,045,438 out=113,089,395 elapsed=185.8s

  [15940/21087] intraday_4849.csv.gz  in=400,060,519 out=113,089,395 elapsed=185.8s

  [15941/21087] intraday_4853.csv.gz  in=400,072,849 out=113,089,395 elapsed=185.9s

  [15942/21087] intraday_4856.csv.gz  in=400,082,513 out=113,089,395 elapsed=185.9s

  [15943/21087] intraday_4854.csv.gz  in=400,094,796 out=113,089,395 elapsed=185.9s

  [15944/21087] intraday_4855.csv.gz  in=400,119,596 out=113,089,395 elapsed=185.9s

  [15945/21087] intraday_4857.csv.gz  in=400,130,744 out=113,089,395 elapsed=185.9s

  [15946/21087] intraday_4858.csv.gz  in=400,142,040 out=113,089,395 elapsed=185.9s

  [15947/21087] intraday_4859.csv.gz  in=400,153,043 out=113,089,395 elapsed=185.9s

  [15948/21087] intraday_4860.csv.gz  in=400,167,065 out=113,089,395 elapsed=185.9s

  [15949/21087] intraday_4861.csv.gz  in=400,179,379 out=113,089,395 elapsed=185.9s

  [15950/21087] intraday_4862.csv.gz  in=400,190,990 out=113,089,395 elapsed=185.9s

  [15951/21087] intraday_4863.csv.gz  in=400,201,947 out=113,089,395 elapsed=185.9s

  [15952/21087] intraday_4864.csv.gz  in=400,213,289 out=113,089,395 elapsed=185.9s

  [15953/21087] intraday_4865.csv.gz  in=400,232,511 out=113,089,395 elapsed=185.9s

  [15954/21087] intraday_4866.csv.gz  in=400,242,457 out=113,089,395 elapsed=186.0s

  [15955/21087] intraday_4868.csv.gz  in=400,254,467 out=113,089,395 elapsed=186.0s

  [15956/21087] intraday_4867.csv.gz  in=400,265,197 out=113,089,395 elapsed=186.0s

  [15957/21087] intraday_4869.csv.gz  in=400,274,512 out=113,089,395 elapsed=186.0s

  [15958/21087] intraday_4870.csv.gz  in=400,285,990 out=113,089,395 elapsed=186.0s

  [15959/21087] intraday_4871.csv.gz  in=400,296,750 out=113,089,395 elapsed=186.0s

  [15960/21087] intraday_4872.csv.gz  in=400,312,221 out=113,089,395 elapsed=186.0s

  [15961/21087] intraday_4873.csv.gz  in=400,326,255 out=113,089,395 elapsed=186.0s

  [15962/21087] intraday_4874.csv.gz  in=400,337,932 out=113,089,395 elapsed=186.0s

  [15963/21087] intraday_4875.csv.gz  in=400,347,814 out=113,089,395 elapsed=186.0s

  [15964/21087] intraday_4877.csv.gz  in=400,360,723 out=113,089,395 elapsed=186.0s

  [15965/21087] intraday_4876.csv.gz  in=400,371,434 out=113,089,395 elapsed=186.0s

  [15966/21087] intraday_4878.csv.gz  in=400,384,240 out=113,089,395 elapsed=186.0s

  [15967/21087] intraday_4879.csv.gz  in=400,395,648 out=113,089,395 elapsed=186.1s

  [15968/21087] intraday_4881.csv.gz  in=400,406,813 out=113,089,395 elapsed=186.1s

  [15969/21087] intraday_4880.csv.gz  in=400,417,647 out=113,089,395 elapsed=186.1s

  [15970/21087] intraday_4882.csv.gz  in=400,432,132 out=113,089,395 elapsed=186.1s

  [15971/21087] intraday_4883.csv.gz  in=400,446,930 out=113,089,395 elapsed=186.1s

  [15972/21087] intraday_4884.csv.gz  in=400,460,025 out=113,089,395 elapsed=186.1s

  [15973/21087] intraday_4885.csv.gz  in=400,472,423 out=113,089,395 elapsed=186.1s

  [15974/21087] intraday_4886.csv.gz  in=400,483,854 out=113,089,395 elapsed=186.1s

  [15975/21087] intraday_4887.csv.gz  in=400,495,033 out=113,089,395 elapsed=186.1s

  [15976/21087] intraday_4888.csv.gz  in=400,506,296 out=113,089,395 elapsed=186.1s

  [15977/21087] intraday_4889.csv.gz  in=400,518,581 out=113,089,395 elapsed=186.1s

  [15978/21087] intraday_4890.csv.gz  in=400,530,143 out=113,089,395 elapsed=186.1s

  [15979/21087] intraday_4891.csv.gz  in=400,543,497 out=113,089,395 elapsed=186.2s

  [15980/21087] intraday_4893.csv.gz  in=400,555,007 out=113,089,395 elapsed=186.2s

  [15981/21087] intraday_4892.csv.gz  in=400,565,708 out=113,089,395 elapsed=186.2s

  [15982/21087] intraday_4894.csv.gz  in=400,576,177 out=113,089,395 elapsed=186.2s

  [15983/21087] intraday_4895.csv.gz  in=400,589,665 out=113,089,395 elapsed=186.2s

  [15984/21087] intraday_4896.csv.gz  in=400,601,084 out=113,089,395 elapsed=186.2s

  [15985/21087] intraday_4897.csv.gz  in=400,613,217 out=113,089,395 elapsed=186.2s

  [15986/21087] intraday_4898.csv.gz  in=400,623,867 out=113,089,395 elapsed=186.2s

  [15987/21087] intraday_4899.csv.gz  in=400,634,547 out=113,089,395 elapsed=186.2s

  [15988/21087] intraday_4900.csv.gz  in=400,646,116 out=113,089,395 elapsed=186.2s

  [15989/21087] intraday_4903.csv.gz  in=400,657,029 out=113,089,395 elapsed=186.2s

  [15990/21087] intraday_4902.csv.gz  in=400,669,962 out=113,089,395 elapsed=186.2s

  [15991/21087] intraday_4901.csv.gz  in=400,685,711 out=113,089,395 elapsed=186.3s

  [15992/21087] intraday_4904.csv.gz  in=400,696,988 out=113,089,395 elapsed=186.3s

  [15993/21087] intraday_4905.csv.gz  in=400,708,330 out=113,089,395 elapsed=186.3s

  [15994/21087] intraday_4906.csv.gz  in=400,722,611 out=113,089,395 elapsed=186.3s

  [15995/21087] intraday_4907.csv.gz  in=400,738,416 out=113,089,395 elapsed=186.3s

  [15996/21087] intraday_4908.csv.gz  in=400,749,708 out=113,089,395 elapsed=186.3s

  [15997/21087] intraday_4909.csv.gz  in=400,764,013 out=113,089,395 elapsed=186.3s

  [15998/21087] intraday_4910.csv.gz  in=400,778,251 out=113,089,395 elapsed=186.3s

  [15999/21087] intraday_4911.csv.gz  in=400,792,569 out=113,089,395 elapsed=186.3s

  [16000/21087] intraday_4912.csv.gz  in=400,805,229 out=113,089,395 elapsed=186.3s

  [16001/21087] intraday_4913.csv.gz  in=400,817,141 out=113,089,395 elapsed=186.3s

  [16002/21087] intraday_4914.csv.gz  in=400,829,440 out=113,089,395 elapsed=186.3s

  [16003/21087] intraday_4915.csv.gz  in=400,839,294 out=113,089,395 elapsed=186.3s

  [16004/21087] intraday_4916.csv.gz  in=400,852,302 out=113,089,395 elapsed=186.4s

  [16005/21087] intraday_4917.csv.gz  in=400,862,942 out=113,089,395 elapsed=186.4s

  [16006/21087] intraday_4918.csv.gz  in=400,874,715 out=113,089,395 elapsed=186.4s

  [16007/21087] intraday_4919.csv.gz  in=400,888,023 out=113,089,395 elapsed=186.4s

  [16008/21087] intraday_4920.csv.gz  in=400,900,751 out=113,089,395 elapsed=186.4s

  [16009/21087] intraday_4921.csv.gz  in=400,916,859 out=113,089,395 elapsed=186.4s

  [16010/21087] intraday_4922.csv.gz  in=400,927,794 out=113,089,395 elapsed=186.4s

  [16011/21087] intraday_4923.csv.gz  in=400,943,270 out=113,089,395 elapsed=186.4s

  [16012/21087] intraday_4924.csv.gz  in=400,954,387 out=113,089,395 elapsed=186.4s

  [16013/21087] intraday_4925.csv.gz  in=400,966,386 out=113,089,395 elapsed=186.4s

  [16014/21087] intraday_4926.csv.gz  in=400,979,912 out=113,089,395 elapsed=186.4s

  [16015/21087] intraday_4927.csv.gz  in=400,993,995 out=113,089,395 elapsed=186.4s

  [16016/21087] intraday_4928.csv.gz  in=401,005,892 out=113,089,395 elapsed=186.4s

  [16017/21087] intraday_4929.csv.gz  in=401,019,816 out=113,089,395 elapsed=186.5s

  [16018/21087] intraday_4930.csv.gz  in=401,033,289 out=113,089,395 elapsed=186.5s

  [16019/21087] intraday_4931.csv.gz  in=401,046,573 out=113,089,395 elapsed=186.5s

  [16020/21087] intraday_4932.csv.gz  in=401,068,435 out=113,089,395 elapsed=186.5s

  [16021/21087] intraday_4933.csv.gz  in=401,083,047 out=113,089,395 elapsed=186.5s

  [16022/21087] intraday_4934.csv.gz  in=401,094,620 out=113,089,395 elapsed=186.5s

  [16023/21087] intraday_4935.csv.gz  in=401,110,190 out=113,089,395 elapsed=186.5s

  [16024/21087] intraday_4936.csv.gz  in=401,121,843 out=113,089,395 elapsed=186.5s

  [16025/21087] intraday_4938.csv.gz  in=401,132,308 out=113,089,395 elapsed=186.5s

  [16026/21087] intraday_4937.csv.gz  in=401,144,057 out=113,089,395 elapsed=186.5s

  [16027/21087] intraday_4939.csv.gz  in=401,157,032 out=113,089,395 elapsed=186.5s

  [16028/21087] intraday_4940.csv.gz  in=401,167,780 out=113,089,395 elapsed=186.6s

  [16029/21087] intraday_4942.csv.gz  in=401,180,487 out=113,089,395 elapsed=186.6s

  [16030/21087] intraday_4941.csv.gz  in=401,193,987 out=113,089,395 elapsed=186.6s

  [16031/21087] intraday_4943.csv.gz  in=401,210,478 out=113,089,395 elapsed=186.6s

  [16032/21087] intraday_4945.csv.gz  in=401,222,795 out=113,089,395 elapsed=186.6s

  [16033/21087] intraday_4944.csv.gz  in=401,234,126 out=113,089,395 elapsed=186.6s

  [16034/21087] intraday_4946.csv.gz  in=401,259,139 out=113,089,395 elapsed=186.6s

  [16035/21087] intraday_4947.csv.gz  in=401,273,305 out=113,089,395 elapsed=186.6s

  [16036/21087] intraday_4948.csv.gz  in=401,284,198 out=113,089,395 elapsed=186.6s

  [16037/21087] intraday_4949.csv.gz  in=401,297,944 out=113,089,395 elapsed=186.6s

  [16038/21087] intraday_4950.csv.gz  in=401,313,036 out=113,089,395 elapsed=186.6s

  [16039/21087] intraday_4951.csv.gz  in=401,326,163 out=113,089,395 elapsed=186.6s

  [16040/21087] intraday_4952.csv.gz  in=401,340,428 out=113,089,395 elapsed=186.7s

  [16041/21087] intraday_4953.csv.gz  in=401,351,048 out=113,089,395 elapsed=186.7s

  [16042/21087] intraday_4954.csv.gz  in=401,362,770 out=113,089,395 elapsed=186.7s

  [16043/21087] intraday_4955.csv.gz  in=401,376,066 out=113,089,395 elapsed=186.7s

  [16044/21087] intraday_4957.csv.gz  in=401,385,621 out=113,089,395 elapsed=186.7s

  [16045/21087] intraday_4956.csv.gz  in=401,398,856 out=113,089,395 elapsed=186.7s

  [16046/21087] intraday_4958.csv.gz  in=401,408,002 out=113,089,395 elapsed=186.7s

  [16047/21087] intraday_4959.csv.gz  in=401,418,401 out=113,089,395 elapsed=186.7s

  [16048/21087] intraday_4960.csv.gz  in=401,425,080 out=113,089,395 elapsed=186.7s

  [16049/21087] intraday_4962.csv.gz  in=401,594,969 out=113,089,395 elapsed=186.8s

  [16050/21087] intraday_4963.csv.gz  in=401,758,529 out=113,089,395 elapsed=186.8s

  [16051/21087] intraday_4961.csv.gz  in=401,961,529 out=113,089,395 elapsed=186.8s

  [16052/21087] intraday_4964.csv.gz  in=402,134,224 out=113,089,395 elapsed=186.8s

  [16053/21087] intraday_4965.csv.gz  in=402,321,103 out=113,089,395 elapsed=186.9s

  [16054/21087] intraday_4968.csv.gz  in=402,476,026 out=113,089,395 elapsed=187.0s

  [16055/21087] intraday_4967.csv.gz  in=402,661,832 out=113,089,395 elapsed=187.0s

  [16056/21087] intraday_4966.csv.gz  in=402,868,160 out=113,089,395 elapsed=187.0s

  [16057/21087] intraday_4969.csv.gz  in=403,048,303 out=113,089,395 elapsed=187.1s

  [16058/21087] intraday_4970.csv.gz  in=403,220,540 out=113,089,395 elapsed=187.1s

  [16059/21087] intraday_4972.csv.gz  in=403,378,229 out=113,089,395 elapsed=187.1s

  [16060/21087] intraday_4971.csv.gz  in=403,554,838 out=113,089,395 elapsed=187.1s

  [16061/21087] intraday_4974.csv.gz  in=403,702,684 out=113,089,395 elapsed=187.2s

  [16062/21087] intraday_4973.csv.gz  in=403,860,801 out=113,089,395 elapsed=187.2s

  [16063/21087] intraday_4975.csv.gz  in=403,993,373 out=113,089,395 elapsed=187.2s

  [16064/21087] intraday_4976.csv.gz  in=404,111,629 out=113,089,395 elapsed=187.2s

  [16065/21087] intraday_4979.csv.gz  in=404,243,012 out=113,089,395 elapsed=187.3s

  [16066/21087] intraday_4977.csv.gz  in=404,433,803 out=113,089,395 elapsed=187.4s

  [16067/21087] intraday_4978.csv.gz  in=404,605,856 out=113,089,395 elapsed=187.4s

  [16068/21087] intraday_4980.csv.gz  in=404,769,740 out=113,089,395 elapsed=187.4s

  [16069/21087] intraday_4981.csv.gz  in=404,916,862 out=113,089,395 elapsed=187.4s

  [16070/21087] intraday_4983.csv.gz  in=405,055,974 out=113,089,395 elapsed=187.5s

  [16071/21087] intraday_4984.csv.gz  in=405,207,408 out=113,089,395 elapsed=187.5s

  [16072/21087] intraday_4982.csv.gz  in=405,383,759 out=113,089,395 elapsed=187.5s

  [16073/21087] intraday_4985.csv.gz  in=405,545,506 out=113,089,395 elapsed=187.5s

  [16074/21087] intraday_4986.csv.gz  in=405,692,282 out=113,089,395 elapsed=187.6s

  [16075/21087] intraday_4987.csv.gz  in=405,852,782 out=113,089,395 elapsed=187.6s

  [16076/21087] intraday_4988.csv.gz  in=405,998,776 out=113,089,395 elapsed=187.6s

  [16077/21087] intraday_4989.csv.gz  in=406,181,248 out=113,089,395 elapsed=187.7s

  [16078/21087] intraday_4990.csv.gz  in=406,373,401 out=113,089,395 elapsed=187.7s

  [16079/21087] intraday_4992.csv.gz  in=406,525,026 out=113,089,395 elapsed=187.7s

  [16080/21087] intraday_4991.csv.gz  in=406,719,274 out=113,089,395 elapsed=187.7s

  [16081/21087] intraday_4993.csv.gz  in=406,870,772 out=113,089,395 elapsed=187.8s

  [16082/21087] intraday_4994.csv.gz  in=407,019,605 out=113,089,395 elapsed=187.8s

  [16083/21087] intraday_4995.csv.gz  in=407,198,376 out=113,089,395 elapsed=187.8s

  [16084/21087] intraday_4996.csv.gz  in=407,339,262 out=113,089,395 elapsed=187.8s

  [16085/21087] intraday_4997.csv.gz  in=407,497,215 out=113,089,395 elapsed=187.9s

  [16086/21087] intraday_4998.csv.gz  in=407,651,359 out=113,089,395 elapsed=187.9s

  [16087/21087] intraday_4999.csv.gz  in=407,778,749 out=113,089,395 elapsed=187.9s

  [16088/21087] intraday_5000.csv.gz  in=407,918,311 out=113,089,395 elapsed=187.9s

  [16089/21087] intraday_5001.csv.gz  in=408,079,492 out=113,089,395 elapsed=188.0s

  [16090/21087] intraday_5002.csv.gz  in=408,232,007 out=113,089,395 elapsed=188.0s

  [16091/21087] intraday_5003.csv.gz  in=408,388,957 out=113,089,395 elapsed=188.0s

  [16092/21087] intraday_5004.csv.gz  in=408,561,518 out=113,089,395 elapsed=188.1s

  [16093/21087] intraday_5005.csv.gz  in=408,727,451 out=113,089,395 elapsed=188.1s

  [16094/21087] intraday_5006.csv.gz  in=408,883,800 out=113,089,395 elapsed=188.1s

  [16095/21087] intraday_5007.csv.gz  in=409,023,379 out=113,089,395 elapsed=188.1s

  [16096/21087] intraday_5008.csv.gz  in=409,167,619 out=113,089,395 elapsed=188.2s

  [16097/21087] intraday_5009.csv.gz  in=409,327,338 out=113,089,395 elapsed=188.2s

  [16098/21087] intraday_5010.csv.gz  in=409,460,337 out=113,089,395 elapsed=188.2s

  [16099/21087] intraday_5011.csv.gz  in=409,600,526 out=113,089,395 elapsed=188.2s

  [16100/21087] intraday_5012.csv.gz  in=409,803,565 out=113,089,395 elapsed=188.3s

  [16101/21087] intraday_5013.csv.gz  in=409,934,714 out=113,089,395 elapsed=188.3s

  [16102/21087] intraday_5014.csv.gz  in=410,090,408 out=113,089,395 elapsed=188.3s

  [16103/21087] intraday_5015.csv.gz  in=410,253,725 out=113,089,395 elapsed=188.4s

  [16104/21087] intraday_5016.csv.gz  in=410,413,110 out=113,089,395 elapsed=188.4s

  [16105/21087] intraday_5017.csv.gz  in=410,555,526 out=113,089,395 elapsed=188.4s

  [16106/21087] intraday_5018.csv.gz  in=410,707,753 out=113,089,395 elapsed=188.4s

  [16107/21087] intraday_5019.csv.gz  in=410,881,484 out=113,089,395 elapsed=188.5s

  [16108/21087] intraday_5020.csv.gz  in=411,027,654 out=113,089,395 elapsed=188.5s

  [16109/21087] intraday_5021.csv.gz  in=411,190,291 out=113,089,395 elapsed=188.5s

  [16110/21087] intraday_5022.csv.gz  in=411,334,169 out=113,089,395 elapsed=188.6s

  [16111/21087] intraday_5023.csv.gz  in=411,471,756 out=113,089,395 elapsed=188.6s

  [16112/21087] intraday_5024.csv.gz  in=411,604,984 out=113,089,395 elapsed=188.6s

  [16113/21087] intraday_5025.csv.gz  in=411,796,652 out=113,089,395 elapsed=188.7s

  [16114/21087] intraday_5026.csv.gz  in=411,966,129 out=113,089,395 elapsed=188.7s

  [16115/21087] intraday_5027.csv.gz  in=412,137,172 out=113,089,395 elapsed=188.7s

  [16116/21087] intraday_5028.csv.gz  in=412,289,042 out=113,089,395 elapsed=188.7s

  [16117/21087] intraday_5029.csv.gz  in=412,439,304 out=113,089,395 elapsed=188.8s

  [16118/21087] intraday_5030.csv.gz  in=412,590,931 out=113,089,395 elapsed=188.8s

  [16119/21087] intraday_5031.csv.gz  in=412,743,264 out=113,089,395 elapsed=188.8s

  [16120/21087] intraday_5032.csv.gz  in=412,882,014 out=113,089,395 elapsed=188.8s

  [16121/21087] intraday_5033.csv.gz  in=413,053,031 out=113,089,395 elapsed=188.9s

  [16122/21087] intraday_5034.csv.gz  in=413,193,338 out=113,089,395 elapsed=188.9s

  [16123/21087] intraday_5036.csv.gz  in=413,336,452 out=113,089,395 elapsed=188.9s

  [16124/21087] intraday_5035.csv.gz  in=413,496,376 out=113,089,395 elapsed=188.9s

  [16125/21087] intraday_5037.csv.gz  in=413,652,979 out=113,089,395 elapsed=189.0s

  [16126/21087] intraday_5038.csv.gz  in=413,802,494 out=113,089,395 elapsed=189.0s

  [16127/21087] intraday_5040.csv.gz  in=413,924,636 out=113,089,395 elapsed=189.0s

  [16128/21087] intraday_5039.csv.gz  in=414,090,183 out=113,089,395 elapsed=189.0s

  [16129/21087] intraday_5041.csv.gz  in=414,236,680 out=113,089,395 elapsed=189.1s

  [16130/21087] intraday_5042.csv.gz  in=414,387,027 out=113,089,395 elapsed=189.1s

  [16131/21087] intraday_5043.csv.gz  in=414,594,542 out=113,089,395 elapsed=189.2s

  [16132/21087] intraday_5044.csv.gz  in=414,774,064 out=113,089,395 elapsed=189.2s

  [16133/21087] intraday_5045.csv.gz  in=414,937,230 out=113,089,395 elapsed=189.2s

  [16134/21087] intraday_5046.csv.gz  in=415,087,668 out=113,089,395 elapsed=189.2s

  [16135/21087] intraday_5047.csv.gz  in=415,233,322 out=113,089,395 elapsed=189.3s

  [16136/21087] intraday_5048.csv.gz  in=415,411,749 out=113,089,395 elapsed=189.3s

  [16137/21087] intraday_5050.csv.gz  in=415,554,535 out=113,089,395 elapsed=189.3s

  [16138/21087] intraday_5049.csv.gz  in=415,764,815 out=113,089,395 elapsed=189.4s

  [16139/21087] intraday_5051.csv.gz  in=415,937,994 out=113,089,395 elapsed=189.4s

  [16140/21087] intraday_5052.csv.gz  in=416,112,163 out=113,089,395 elapsed=189.4s

  [16141/21087] intraday_5053.csv.gz  in=416,292,118 out=113,089,395 elapsed=189.5s

  [16142/21087] intraday_5054.csv.gz  in=416,463,452 out=113,089,395 elapsed=189.5s

  [16143/21087] intraday_5055.csv.gz  in=416,617,132 out=113,089,395 elapsed=189.5s

  [16144/21087] intraday_5056.csv.gz  in=416,777,717 out=113,089,395 elapsed=189.6s

  [16145/21087] intraday_5057.csv.gz  in=416,916,623 out=113,089,395 elapsed=189.6s

  [16146/21087] intraday_5059.csv.gz  in=417,067,238 out=113,089,395 elapsed=189.6s

  [16147/21087] intraday_5058.csv.gz  in=417,258,408 out=113,089,395 elapsed=189.6s

  [16148/21087] intraday_5060.csv.gz  in=417,423,487 out=113,089,395 elapsed=189.7s

  [16149/21087] intraday_5061.csv.gz  in=417,594,299 out=113,089,395 elapsed=189.7s

  [16150/21087] intraday_5063.csv.gz  in=417,735,630 out=113,089,395 elapsed=189.7s

  [16151/21087] intraday_5062.csv.gz  in=417,915,235 out=113,089,395 elapsed=189.7s

  [16152/21087] intraday_5064.csv.gz  in=418,075,690 out=113,089,395 elapsed=189.8s

  [16153/21087] intraday_5066.csv.gz  in=418,217,457 out=113,089,395 elapsed=189.8s

  [16154/21087] intraday_5065.csv.gz  in=418,415,892 out=113,089,395 elapsed=189.8s

  [16155/21087] intraday_5067.csv.gz  in=418,565,853 out=113,089,395 elapsed=189.8s

  [16156/21087] intraday_5070.csv.gz  in=418,711,503 out=113,089,395 elapsed=190.0s

  [16157/21087] intraday_5068.csv.gz  in=418,912,186 out=113,089,395 elapsed=190.0s

  [16158/21087] intraday_5071.csv.gz  in=419,079,184 out=113,089,395 elapsed=190.0s

  [16159/21087] intraday_5069.csv.gz  in=419,255,890 out=113,089,395 elapsed=190.0s

  [16160/21087] intraday_5072.csv.gz  in=419,429,581 out=113,089,395 elapsed=190.1s

  [16161/21087] intraday_5073.csv.gz  in=419,591,205 out=113,089,395 elapsed=190.1s

  [16162/21087] intraday_5075.csv.gz  in=419,762,227 out=113,089,395 elapsed=190.1s

  [16163/21087] intraday_5074.csv.gz  in=419,980,300 out=113,089,395 elapsed=190.1s

  [16164/21087] intraday_5076.csv.gz  in=420,170,854 out=113,089,395 elapsed=190.2s

  [16165/21087] intraday_5078.csv.gz  in=420,340,271 out=113,089,395 elapsed=190.2s

  [16166/21087] intraday_5077.csv.gz  in=420,542,740 out=113,089,395 elapsed=190.2s

  [16167/21087] intraday_5079.csv.gz  in=420,699,041 out=113,089,395 elapsed=190.2s

  [16168/21087] intraday_5080.csv.gz  in=420,842,612 out=113,089,395 elapsed=190.3s

  [16169/21087] intraday_5081.csv.gz  in=420,999,114 out=113,089,395 elapsed=190.4s

  [16170/21087] intraday_5082.csv.gz  in=421,141,614 out=113,089,395 elapsed=190.4s

  [16171/21087] intraday_5083.csv.gz  in=421,300,857 out=113,089,395 elapsed=190.4s

  [16172/21087] intraday_5084.csv.gz  in=421,466,560 out=113,089,395 elapsed=190.4s

  [16173/21087] intraday_5085.csv.gz  in=421,641,455 out=113,089,395 elapsed=190.5s

  [16174/21087] intraday_5087.csv.gz  in=421,798,957 out=113,089,395 elapsed=190.5s

  [16175/21087] intraday_5086.csv.gz  in=421,988,147 out=113,089,395 elapsed=190.5s

  [16176/21087] intraday_5088.csv.gz  in=422,145,307 out=113,089,395 elapsed=190.6s

  [16177/21087] intraday_5090.csv.gz  in=422,304,772 out=113,089,395 elapsed=190.6s

  [16178/21087] intraday_5089.csv.gz  in=422,475,779 out=113,089,395 elapsed=190.6s

  [16179/21087] intraday_5091.csv.gz  in=422,636,184 out=113,089,395 elapsed=190.6s

  [16180/21087] intraday_5092.csv.gz  in=422,821,773 out=113,089,395 elapsed=190.7s

  [16181/21087] intraday_5093.csv.gz  in=422,984,854 out=113,089,395 elapsed=190.7s

  [16182/21087] intraday_5095.csv.gz  in=423,148,355 out=113,089,395 elapsed=190.7s

  [16183/21087] intraday_5094.csv.gz  in=423,320,942 out=113,089,395 elapsed=190.7s

  [16184/21087] intraday_5096.csv.gz  in=423,455,644 out=113,089,395 elapsed=190.8s

  [16185/21087] intraday_5097.csv.gz  in=423,603,159 out=113,089,395 elapsed=190.8s

  [16186/21087] intraday_5098.csv.gz  in=423,750,849 out=113,089,395 elapsed=190.8s

  [16187/21087] intraday_5100.csv.gz  in=423,859,624 out=113,089,395 elapsed=190.8s

  [16188/21087] intraday_5099.csv.gz  in=424,039,578 out=113,089,395 elapsed=190.9s

  [16189/21087] intraday_5103.csv.gz  in=424,054,956 out=113,089,395 elapsed=190.9s

  [16190/21087] intraday_5104.csv.gz  in=424,067,276 out=113,089,395 elapsed=190.9s

  [16191/21087] intraday_5105.csv.gz  in=424,081,141 out=113,089,395 elapsed=190.9s

  [16192/21087] intraday_5106.csv.gz  in=424,092,314 out=113,089,395 elapsed=190.9s

  [16193/21087] intraday_5101.csv.gz  in=424,206,275 out=113,089,395 elapsed=190.9s

  [16194/21087] intraday_5107.csv.gz  in=424,219,667 out=113,089,395 elapsed=190.9s

  [16195/21087] intraday_5102.csv.gz  in=424,332,456 out=113,089,395 elapsed=190.9s

  [16196/21087] intraday_5109.csv.gz  in=424,346,156 out=113,089,395 elapsed=191.0s

  [16197/21087] intraday_5110.csv.gz  in=424,357,797 out=113,089,395 elapsed=191.0s

  [16198/21087] intraday_5108.csv.gz  in=424,374,463 out=113,089,395 elapsed=191.0s

  [16199/21087] intraday_5111.csv.gz  in=424,388,361 out=113,089,395 elapsed=191.0s

  [16200/21087] intraday_5112.csv.gz  in=424,401,703 out=113,089,395 elapsed=191.0s

  [16201/21087] intraday_5113.csv.gz  in=424,415,635 out=113,089,395 elapsed=191.0s

  [16202/21087] intraday_5114.csv.gz  in=424,428,772 out=113,089,395 elapsed=191.0s

  [16203/21087] intraday_5115.csv.gz  in=424,441,755 out=113,089,395 elapsed=191.0s

  [16204/21087] intraday_5116.csv.gz  in=424,452,771 out=113,089,395 elapsed=191.0s

  [16205/21087] intraday_5117.csv.gz  in=424,462,870 out=113,089,395 elapsed=191.0s

  [16206/21087] intraday_5118.csv.gz  in=424,472,278 out=113,089,395 elapsed=191.0s

  [16207/21087] intraday_5119.csv.gz  in=424,492,510 out=113,089,395 elapsed=191.0s

  [16208/21087] intraday_5120.csv.gz  in=424,505,791 out=113,089,395 elapsed=191.0s

  [16209/21087] intraday_5122.csv.gz  in=424,517,681 out=113,089,395 elapsed=191.0s

  [16210/21087] intraday_5121.csv.gz  in=424,530,292 out=113,089,395 elapsed=191.1s

  [16211/21087] intraday_5123.csv.gz  in=424,551,715 out=113,089,395 elapsed=191.1s

  [16212/21087] intraday_5124.csv.gz  in=424,565,566 out=113,089,395 elapsed=191.1s

  [16213/21087] intraday_5126.csv.gz  in=424,577,654 out=113,089,395 elapsed=191.1s

  [16214/21087] intraday_5125.csv.gz  in=424,588,742 out=113,089,395 elapsed=191.1s

  [16215/21087] intraday_5127.csv.gz  in=424,601,861 out=113,089,395 elapsed=191.1s

  [16216/21087] intraday_5128.csv.gz  in=424,613,161 out=113,089,395 elapsed=191.1s

  [16217/21087] intraday_5130.csv.gz  in=424,625,186 out=113,089,395 elapsed=191.1s

  [16218/21087] intraday_5129.csv.gz  in=424,637,509 out=113,089,395 elapsed=191.1s

  [16219/21087] intraday_5131.csv.gz  in=424,651,417 out=113,089,395 elapsed=191.1s

  [16220/21087] intraday_5134.csv.gz  in=424,662,331 out=113,089,395 elapsed=191.2s

  [16221/21087] intraday_5132.csv.gz  in=424,677,339 out=113,089,395 elapsed=191.2s

  [16222/21087] intraday_5133.csv.gz  in=424,693,407 out=113,089,395 elapsed=191.2s

  [16223/21087] intraday_5135.csv.gz  in=424,705,743 out=113,089,395 elapsed=191.2s

  [16224/21087] intraday_5136.csv.gz  in=424,717,876 out=113,089,395 elapsed=191.2s

  [16225/21087] intraday_5138.csv.gz  in=424,728,767 out=113,089,395 elapsed=191.2s

  [16226/21087] intraday_5137.csv.gz  in=424,744,037 out=113,089,395 elapsed=191.2s

  [16227/21087] intraday_5139.csv.gz  in=424,756,771 out=113,089,395 elapsed=191.2s

  [16228/21087] intraday_5140.csv.gz  in=424,769,672 out=113,089,395 elapsed=191.2s

  [16229/21087] intraday_5142.csv.gz  in=424,782,315 out=113,089,395 elapsed=191.2s

  [16230/21087] intraday_5141.csv.gz  in=424,805,138 out=113,089,395 elapsed=191.2s

  [16231/21087] intraday_5143.csv.gz  in=424,818,021 out=113,089,395 elapsed=191.2s

  [16232/21087] intraday_5144.csv.gz  in=424,829,967 out=113,089,395 elapsed=191.3s

  [16233/21087] intraday_5145.csv.gz  in=424,843,253 out=113,089,395 elapsed=191.3s

  [16234/21087] intraday_5146.csv.gz  in=424,856,064 out=113,089,395 elapsed=191.3s

  [16235/21087] intraday_5147.csv.gz  in=424,869,637 out=113,089,395 elapsed=191.3s

  [16236/21087] intraday_5148.csv.gz  in=424,882,682 out=113,089,395 elapsed=191.3s

  [16237/21087] intraday_5149.csv.gz  in=424,894,481 out=113,089,395 elapsed=191.3s

  [16238/21087] intraday_5150.csv.gz  in=424,906,495 out=113,089,395 elapsed=191.3s

  [16239/21087] intraday_5151.csv.gz  in=424,920,256 out=113,089,395 elapsed=191.3s

  [16240/21087] intraday_5152.csv.gz  in=424,931,158 out=113,089,395 elapsed=191.3s

  [16241/21087] intraday_5153.csv.gz  in=424,942,576 out=113,089,395 elapsed=191.3s

  [16242/21087] intraday_5154.csv.gz  in=424,956,563 out=113,089,395 elapsed=191.3s

  [16243/21087] intraday_5155.csv.gz  in=424,967,203 out=113,089,395 elapsed=191.3s

  [16244/21087] intraday_5156.csv.gz  in=424,979,294 out=113,089,395 elapsed=191.4s

  [16245/21087] intraday_5157.csv.gz  in=424,992,682 out=113,089,395 elapsed=191.4s

  [16246/21087] intraday_5158.csv.gz  in=425,006,440 out=113,089,395 elapsed=191.4s

  [16247/21087] intraday_5159.csv.gz  in=425,019,845 out=113,089,395 elapsed=191.4s

  [16248/21087] intraday_5160.csv.gz  in=425,031,992 out=113,089,395 elapsed=191.4s

  [16249/21087] intraday_5161.csv.gz  in=425,045,609 out=113,089,395 elapsed=191.4s

  [16250/21087] intraday_5162.csv.gz  in=425,057,540 out=113,089,395 elapsed=191.4s

  [16251/21087] intraday_5163.csv.gz  in=425,070,502 out=113,089,395 elapsed=191.4s

  [16252/21087] intraday_5164.csv.gz  in=425,081,924 out=113,089,395 elapsed=191.4s

  [16253/21087] intraday_5165.csv.gz  in=425,092,658 out=113,089,395 elapsed=191.4s

  [16254/21087] intraday_5166.csv.gz  in=425,103,842 out=113,089,395 elapsed=191.4s

  [16255/21087] intraday_5167.csv.gz  in=425,120,301 out=113,089,395 elapsed=191.4s

  [16256/21087] intraday_5168.csv.gz  in=425,132,915 out=113,089,395 elapsed=191.4s

  [16257/21087] intraday_5169.csv.gz  in=425,146,687 out=113,089,395 elapsed=191.5s

  [16258/21087] intraday_5170.csv.gz  in=425,158,625 out=113,089,395 elapsed=191.5s

  [16259/21087] intraday_5171.csv.gz  in=425,168,518 out=113,089,395 elapsed=191.5s

  [16260/21087] intraday_5172.csv.gz  in=425,180,153 out=113,089,395 elapsed=191.5s

  [16261/21087] intraday_5173.csv.gz  in=425,192,340 out=113,089,395 elapsed=191.5s

  [16262/21087] intraday_5174.csv.gz  in=425,204,818 out=113,089,395 elapsed=191.5s

  [16263/21087] intraday_5175.csv.gz  in=425,218,314 out=113,089,395 elapsed=191.5s

  [16264/21087] intraday_5176.csv.gz  in=425,231,120 out=113,089,395 elapsed=191.5s

  [16265/21087] intraday_5177.csv.gz  in=425,244,215 out=113,089,395 elapsed=191.5s

  [16266/21087] intraday_5178.csv.gz  in=425,259,000 out=113,089,395 elapsed=191.5s

  [16267/21087] intraday_5179.csv.gz  in=425,272,126 out=113,089,395 elapsed=191.5s

  [16268/21087] intraday_5180.csv.gz  in=425,283,815 out=113,089,395 elapsed=191.5s

  [16269/21087] intraday_5181.csv.gz  in=425,296,755 out=113,089,395 elapsed=191.5s

  [16270/21087] intraday_5182.csv.gz  in=425,306,912 out=113,089,395 elapsed=191.6s

  [16271/21087] intraday_5183.csv.gz  in=425,319,005 out=113,089,395 elapsed=191.6s

  [16272/21087] intraday_5184.csv.gz  in=425,331,588 out=113,089,395 elapsed=191.6s

  [16273/21087] intraday_5185.csv.gz  in=425,346,897 out=113,089,395 elapsed=191.6s

  [16274/21087] intraday_5186.csv.gz  in=425,360,638 out=113,089,395 elapsed=191.6s

  [16275/21087] intraday_5187.csv.gz  in=425,373,075 out=113,089,395 elapsed=191.6s

  [16276/21087] intraday_5188.csv.gz  in=425,384,638 out=113,089,395 elapsed=191.6s

  [16277/21087] intraday_5189.csv.gz  in=425,395,792 out=113,089,395 elapsed=191.6s

  [16278/21087] intraday_5190.csv.gz  in=425,409,613 out=113,089,395 elapsed=191.6s

  [16279/21087] intraday_5191.csv.gz  in=425,427,015 out=113,089,395 elapsed=191.6s

  [16280/21087] intraday_5192.csv.gz  in=425,438,437 out=113,089,395 elapsed=191.6s

  [16281/21087] intraday_5193.csv.gz  in=425,452,192 out=113,089,395 elapsed=191.6s

  [16282/21087] intraday_5194.csv.gz  in=425,465,828 out=113,089,395 elapsed=191.6s

  [16283/21087] intraday_5195.csv.gz  in=425,480,250 out=113,089,395 elapsed=191.7s

  [16284/21087] intraday_5196.csv.gz  in=425,493,641 out=113,089,395 elapsed=191.7s

  [16285/21087] intraday_5198.csv.gz  in=425,506,549 out=113,089,395 elapsed=191.7s

  [16286/21087] intraday_5197.csv.gz  in=425,523,062 out=113,089,395 elapsed=191.7s

  [16287/21087] intraday_5199.csv.gz  in=425,533,372 out=113,089,395 elapsed=191.7s

  [16288/21087] intraday_5200.csv.gz  in=425,547,525 out=113,089,395 elapsed=191.7s

  [16289/21087] intraday_5201.csv.gz  in=425,560,521 out=113,089,395 elapsed=191.7s

  [16290/21087] intraday_5202.csv.gz  in=425,573,326 out=113,089,395 elapsed=191.7s

  [16291/21087] intraday_5203.csv.gz  in=425,586,491 out=113,089,395 elapsed=191.7s

  [16292/21087] intraday_5204.csv.gz  in=425,601,692 out=113,089,395 elapsed=191.7s

  [16293/21087] intraday_5205.csv.gz  in=425,612,439 out=113,089,395 elapsed=191.7s

  [16294/21087] intraday_5206.csv.gz  in=425,625,551 out=113,089,395 elapsed=191.7s

  [16295/21087] intraday_5207.csv.gz  in=425,642,902 out=113,089,395 elapsed=191.8s

  [16296/21087] intraday_5208.csv.gz  in=425,652,990 out=113,089,395 elapsed=191.8s

  [16297/21087] intraday_5209.csv.gz  in=425,665,234 out=113,089,395 elapsed=191.8s

  [16298/21087] intraday_5210.csv.gz  in=425,680,540 out=113,089,395 elapsed=191.8s

  [16299/21087] intraday_5211.csv.gz  in=425,694,605 out=113,089,395 elapsed=191.8s

  [16300/21087] intraday_5212.csv.gz  in=425,705,965 out=113,089,395 elapsed=191.8s

  [16301/21087] intraday_5213.csv.gz  in=425,718,652 out=113,089,395 elapsed=191.8s

  [16302/21087] intraday_5214.csv.gz  in=425,731,740 out=113,089,395 elapsed=191.8s

  [16303/21087] intraday_5215.csv.gz  in=425,744,476 out=113,089,395 elapsed=191.8s

  [16304/21087] intraday_5216.csv.gz  in=425,761,531 out=113,089,395 elapsed=191.8s

  [16305/21087] intraday_5217.csv.gz  in=425,774,454 out=113,089,395 elapsed=191.8s

  [16306/21087] intraday_5218.csv.gz  in=425,788,869 out=113,089,395 elapsed=191.8s

  [16307/21087] intraday_5219.csv.gz  in=425,804,463 out=113,089,395 elapsed=191.8s

  [16308/21087] intraday_5220.csv.gz  in=425,818,670 out=113,089,395 elapsed=191.9s

  [16309/21087] intraday_5221.csv.gz  in=425,830,488 out=113,089,395 elapsed=191.9s

  [16310/21087] intraday_5222.csv.gz  in=425,841,896 out=113,089,395 elapsed=191.9s

  [16311/21087] intraday_5224.csv.gz  in=425,852,704 out=113,089,395 elapsed=191.9s

  [16312/21087] intraday_5223.csv.gz  in=425,864,911 out=113,089,395 elapsed=191.9s

  [16313/21087] intraday_5226.csv.gz  in=425,877,754 out=113,089,395 elapsed=191.9s

  [16314/21087] intraday_5225.csv.gz  in=425,890,458 out=113,089,395 elapsed=191.9s

  [16315/21087] intraday_5228.csv.gz  in=425,906,045 out=113,089,395 elapsed=191.9s

  [16316/21087] intraday_5227.csv.gz  in=425,925,696 out=113,089,395 elapsed=191.9s

  [16317/21087] intraday_5229.csv.gz  in=425,937,348 out=113,089,395 elapsed=191.9s

  [16318/21087] intraday_5230.csv.gz  in=425,949,173 out=113,089,395 elapsed=191.9s

  [16319/21087] intraday_5231.csv.gz  in=425,962,916 out=113,089,395 elapsed=191.9s

  [16320/21087] intraday_5232.csv.gz  in=425,974,948 out=113,089,395 elapsed=192.0s

  [16321/21087] intraday_5233.csv.gz  in=425,987,200 out=113,089,395 elapsed=192.0s

  [16322/21087] intraday_5234.csv.gz  in=426,002,614 out=113,089,395 elapsed=192.0s

  [16323/21087] intraday_5235.csv.gz  in=426,015,873 out=113,089,395 elapsed=192.0s

  [16324/21087] intraday_5236.csv.gz  in=426,029,980 out=113,089,395 elapsed=192.0s

  [16325/21087] intraday_5237.csv.gz  in=426,042,351 out=113,089,395 elapsed=192.0s

  [16326/21087] intraday_5238.csv.gz  in=426,055,674 out=113,089,395 elapsed=192.0s

  [16327/21087] intraday_5239.csv.gz  in=426,069,264 out=113,089,395 elapsed=192.0s

  [16328/21087] intraday_5240.csv.gz  in=426,081,187 out=113,089,395 elapsed=192.0s

  [16329/21087] intraday_5241.csv.gz  in=426,095,672 out=113,089,395 elapsed=192.0s

  [16330/21087] intraday_5242.csv.gz  in=426,104,510 out=113,089,395 elapsed=192.0s

  [16331/21087] intraday_5243.csv.gz  in=426,116,293 out=113,089,395 elapsed=192.0s

  [16332/21087] intraday_5244.csv.gz  in=426,125,296 out=113,089,395 elapsed=192.0s

  [16333/21087] intraday_5246.csv.gz  in=426,138,465 out=113,089,395 elapsed=192.1s

  [16334/21087] intraday_5245.csv.gz  in=426,154,700 out=113,089,395 elapsed=192.1s

  [16335/21087] intraday_5247.csv.gz  in=426,169,358 out=113,089,395 elapsed=192.1s

  [16336/21087] intraday_5248.csv.gz  in=426,180,611 out=113,089,395 elapsed=192.1s

  [16337/21087] intraday_5249.csv.gz  in=426,193,939 out=113,089,395 elapsed=192.1s

  [16338/21087] intraday_5250.csv.gz  in=426,210,974 out=113,089,395 elapsed=192.1s

  [16339/21087] intraday_5251.csv.gz  in=426,225,117 out=113,089,395 elapsed=192.1s

  [16340/21087] intraday_5252.csv.gz  in=426,237,239 out=113,089,395 elapsed=192.1s

  [16341/21087] intraday_5253.csv.gz  in=426,251,576 out=113,089,395 elapsed=192.1s

  [16342/21087] intraday_5254.csv.gz  in=426,265,360 out=113,089,395 elapsed=192.1s

  [16343/21087] intraday_5255.csv.gz  in=426,279,153 out=113,089,395 elapsed=192.1s

  [16344/21087] intraday_5256.csv.gz  in=426,292,952 out=113,089,395 elapsed=192.1s

  [16345/21087] intraday_5257.csv.gz  in=426,306,161 out=113,089,395 elapsed=192.1s

  [16346/21087] intraday_5258.csv.gz  in=426,318,322 out=113,089,395 elapsed=192.1s

  [16347/21087] intraday_5259.csv.gz  in=426,329,630 out=113,089,395 elapsed=192.2s

  [16348/21087] intraday_5260.csv.gz  in=426,339,537 out=113,089,395 elapsed=192.2s

  [16349/21087] intraday_5261.csv.gz  in=426,355,022 out=113,089,395 elapsed=192.2s

  [16350/21087] intraday_5262.csv.gz  in=426,368,464 out=113,089,395 elapsed=192.2s

  [16351/21087] intraday_5263.csv.gz  in=426,380,174 out=113,089,395 elapsed=192.2s

  [16352/21087] intraday_5264.csv.gz  in=426,392,556 out=113,089,395 elapsed=192.2s

  [16353/21087] intraday_5265.csv.gz  in=426,405,041 out=113,089,395 elapsed=192.2s

  [16354/21087] intraday_5266.csv.gz  in=426,419,071 out=113,089,395 elapsed=192.2s

  [16355/21087] intraday_5267.csv.gz  in=426,430,766 out=113,089,395 elapsed=192.2s

  [16356/21087] intraday_5268.csv.gz  in=426,443,369 out=113,089,395 elapsed=192.2s

  [16357/21087] intraday_5269.csv.gz  in=426,456,505 out=113,089,395 elapsed=192.2s

  [16358/21087] intraday_5270.csv.gz  in=426,467,776 out=113,089,395 elapsed=192.2s

  [16359/21087] intraday_5271.csv.gz  in=426,479,946 out=113,089,395 elapsed=192.3s

  [16360/21087] intraday_5272.csv.gz  in=426,491,035 out=113,089,395 elapsed=192.3s

  [16361/21087] intraday_5273.csv.gz  in=426,506,214 out=113,089,395 elapsed=192.3s

  [16362/21087] intraday_5274.csv.gz  in=426,521,031 out=113,089,395 elapsed=192.3s

  [16363/21087] intraday_5275.csv.gz  in=426,537,641 out=113,089,395 elapsed=192.3s

  [16364/21087] intraday_5276.csv.gz  in=426,548,962 out=113,089,395 elapsed=192.3s

  [16365/21087] intraday_5277.csv.gz  in=426,561,179 out=113,089,395 elapsed=192.3s

  [16366/21087] intraday_5278.csv.gz  in=426,573,488 out=113,089,395 elapsed=192.3s

  [16367/21087] intraday_5279.csv.gz  in=426,588,518 out=113,089,395 elapsed=192.3s

  [16368/21087] intraday_5280.csv.gz  in=426,599,496 out=113,089,395 elapsed=192.3s

  [16369/21087] intraday_5281.csv.gz  in=426,612,182 out=113,089,395 elapsed=192.3s

  [16370/21087] intraday_5282.csv.gz  in=426,625,381 out=113,089,395 elapsed=192.3s

  [16371/21087] intraday_5284.csv.gz  in=426,637,320 out=113,089,395 elapsed=192.4s

  [16372/21087] intraday_5283.csv.gz  in=426,648,339 out=113,089,395 elapsed=192.4s

  [16373/21087] intraday_5285.csv.gz  in=426,661,353 out=113,089,395 elapsed=192.4s

  [16374/21087] intraday_5286.csv.gz  in=426,673,900 out=113,089,395 elapsed=192.4s

  [16375/21087] intraday_5287.csv.gz  in=426,687,645 out=113,089,395 elapsed=192.4s

  [16376/21087] intraday_5288.csv.gz  in=426,701,231 out=113,089,395 elapsed=192.4s

  [16377/21087] intraday_5289.csv.gz  in=426,714,456 out=113,089,395 elapsed=192.4s

  [16378/21087] intraday_5290.csv.gz  in=426,727,784 out=113,089,395 elapsed=192.4s

  [16379/21087] intraday_5291.csv.gz  in=426,740,330 out=113,089,395 elapsed=192.4s

  [16380/21087] intraday_5294.csv.gz  in=426,751,412 out=113,089,395 elapsed=192.4s

  [16381/21087] intraday_5292.csv.gz  in=426,763,653 out=113,089,395 elapsed=192.4s

  [16382/21087] intraday_5293.csv.gz  in=426,777,180 out=113,089,395 elapsed=192.4s

  [16383/21087] intraday_5295.csv.gz  in=426,789,269 out=113,089,395 elapsed=192.4s

  [16384/21087] intraday_5297.csv.gz  in=426,798,920 out=113,089,395 elapsed=192.5s

  [16385/21087] intraday_5296.csv.gz  in=426,815,463 out=113,089,395 elapsed=192.5s

  [16386/21087] intraday_5298.csv.gz  in=426,827,078 out=113,089,395 elapsed=192.5s

  [16387/21087] intraday_5299.csv.gz  in=426,840,700 out=113,089,395 elapsed=192.5s

  [16388/21087] intraday_5300.csv.gz  in=426,853,962 out=113,089,395 elapsed=192.5s

  [16389/21087] intraday_5301.csv.gz  in=426,868,179 out=113,089,395 elapsed=192.5s

  [16390/21087] intraday_5302.csv.gz  in=426,880,048 out=113,089,395 elapsed=192.5s

  [16391/21087] intraday_5303.csv.gz  in=426,893,746 out=113,089,395 elapsed=192.5s

  [16392/21087] intraday_5304.csv.gz  in=426,905,696 out=113,089,395 elapsed=192.5s

  [16393/21087] intraday_5306.csv.gz  in=426,917,697 out=113,089,395 elapsed=192.5s

  [16394/21087] intraday_5307.csv.gz  in=426,928,996 out=113,089,395 elapsed=192.5s

  [16395/21087] intraday_5305.csv.gz  in=426,941,666 out=113,089,395 elapsed=192.5s

  [16396/21087] intraday_5308.csv.gz  in=426,952,283 out=113,089,395 elapsed=192.5s

  [16397/21087] intraday_5310.csv.gz  in=426,966,049 out=113,089,395 elapsed=192.6s

  [16398/21087] intraday_5309.csv.gz  in=426,982,101 out=113,089,395 elapsed=192.6s

  [16399/21087] intraday_5311.csv.gz  in=426,996,290 out=113,089,395 elapsed=192.6s

  [16400/21087] intraday_5312.csv.gz  in=427,008,347 out=113,089,395 elapsed=192.6s

  [16401/21087] intraday_5313.csv.gz  in=427,018,956 out=113,089,395 elapsed=192.6s

  [16402/21087] intraday_5314.csv.gz  in=427,031,051 out=113,089,395 elapsed=192.6s

  [16403/21087] intraday_5315.csv.gz  in=427,043,705 out=113,089,395 elapsed=192.6s

  [16404/21087] intraday_5316.csv.gz  in=427,055,595 out=113,089,395 elapsed=192.6s

  [16405/21087] intraday_5317.csv.gz  in=427,068,846 out=113,089,395 elapsed=192.6s

  [16406/21087] intraday_5318.csv.gz  in=427,081,201 out=113,089,395 elapsed=192.6s

  [16407/21087] intraday_5319.csv.gz  in=427,094,106 out=113,089,395 elapsed=192.6s

  [16408/21087] intraday_5320.csv.gz  in=427,105,253 out=113,089,395 elapsed=192.6s

  [16409/21087] intraday_5321.csv.gz  in=427,119,307 out=113,089,395 elapsed=192.6s

  [16410/21087] intraday_5322.csv.gz  in=427,130,907 out=113,089,395 elapsed=192.7s

  [16411/21087] intraday_5324.csv.gz  in=427,141,469 out=113,089,395 elapsed=192.7s

  [16412/21087] intraday_5323.csv.gz  in=427,154,388 out=113,089,395 elapsed=192.7s

  [16413/21087] intraday_5325.csv.gz  in=427,167,450 out=113,089,395 elapsed=192.7s

  [16414/21087] intraday_5326.csv.gz  in=427,180,532 out=113,089,395 elapsed=192.7s

  [16415/21087] intraday_5327.csv.gz  in=427,196,678 out=113,089,395 elapsed=192.7s

  [16416/21087] intraday_5328.csv.gz  in=427,210,981 out=113,089,395 elapsed=192.7s

  [16417/21087] intraday_5329.csv.gz  in=427,223,988 out=113,089,395 elapsed=192.7s

  [16418/21087] intraday_5330.csv.gz  in=427,235,737 out=113,089,395 elapsed=192.7s

  [16419/21087] intraday_5332.csv.gz  in=427,249,795 out=113,089,395 elapsed=192.7s

  [16420/21087] intraday_5331.csv.gz  in=427,261,494 out=113,089,395 elapsed=192.7s

  [16421/21087] intraday_5333.csv.gz  in=427,279,502 out=113,089,395 elapsed=192.8s

  [16422/21087] intraday_5334.csv.gz  in=427,291,388 out=113,089,395 elapsed=192.8s

  [16423/21087] intraday_5335.csv.gz  in=427,305,167 out=113,089,395 elapsed=192.8s

  [16424/21087] intraday_5336.csv.gz  in=427,317,917 out=113,089,395 elapsed=192.8s

  [16425/21087] intraday_5337.csv.gz  in=427,332,549 out=113,089,395 elapsed=192.8s

  [16426/21087] intraday_5338.csv.gz  in=427,346,808 out=113,089,395 elapsed=192.8s

  [16427/21087] intraday_5339.csv.gz  in=427,359,214 out=113,089,395 elapsed=192.8s

  [16428/21087] intraday_5340.csv.gz  in=427,372,781 out=113,089,395 elapsed=192.8s

  [16429/21087] intraday_5341.csv.gz  in=427,384,560 out=113,089,395 elapsed=192.8s

  [16430/21087] intraday_5342.csv.gz  in=427,398,798 out=113,089,395 elapsed=192.8s

  [16431/21087] intraday_5343.csv.gz  in=427,411,632 out=113,089,395 elapsed=192.8s

  [16432/21087] intraday_5344.csv.gz  in=427,424,622 out=113,089,395 elapsed=192.8s

  [16433/21087] intraday_5345.csv.gz  in=427,437,873 out=113,089,395 elapsed=192.8s

  [16434/21087] intraday_5347.csv.gz  in=427,449,183 out=113,089,395 elapsed=192.9s

  [16435/21087] intraday_5346.csv.gz  in=427,464,964 out=113,089,395 elapsed=192.9s

  [16436/21087] intraday_5348.csv.gz  in=427,478,196 out=113,089,395 elapsed=192.9s

  [16437/21087] intraday_5349.csv.gz  in=427,494,624 out=113,089,395 elapsed=192.9s

  [16438/21087] intraday_5350.csv.gz  in=427,505,530 out=113,089,395 elapsed=192.9s

  [16439/21087] intraday_5351.csv.gz  in=427,517,696 out=113,089,395 elapsed=192.9s

  [16440/21087] intraday_5352.csv.gz  in=427,533,202 out=113,089,395 elapsed=192.9s

  [16441/21087] intraday_5353.csv.gz  in=427,548,090 out=113,089,395 elapsed=192.9s

  [16442/21087] intraday_5354.csv.gz  in=427,560,465 out=113,089,395 elapsed=192.9s

  [16443/21087] intraday_5355.csv.gz  in=427,574,042 out=113,089,395 elapsed=192.9s

  [16444/21087] intraday_5356.csv.gz  in=427,588,320 out=113,089,395 elapsed=192.9s

  [16445/21087] intraday_5357.csv.gz  in=427,603,362 out=113,089,395 elapsed=192.9s

  [16446/21087] intraday_5358.csv.gz  in=427,619,266 out=113,089,395 elapsed=193.0s

  [16447/21087] intraday_5359.csv.gz  in=427,633,782 out=113,089,395 elapsed=193.0s

  [16448/21087] intraday_5360.csv.gz  in=427,647,897 out=113,089,395 elapsed=193.0s

  [16449/21087] intraday_5361.csv.gz  in=427,664,855 out=113,089,395 elapsed=193.0s

  [16450/21087] intraday_5362.csv.gz  in=427,678,851 out=113,089,395 elapsed=193.0s

  [16451/21087] intraday_5363.csv.gz  in=427,691,713 out=113,089,395 elapsed=193.0s

  [16452/21087] intraday_5364.csv.gz  in=427,703,679 out=113,089,395 elapsed=193.0s

  [16453/21087] intraday_5365.csv.gz  in=427,716,982 out=113,089,395 elapsed=193.0s

  [16454/21087] intraday_5366.csv.gz  in=427,728,112 out=113,089,395 elapsed=193.0s

  [16455/21087] intraday_5367.csv.gz  in=427,741,876 out=113,089,395 elapsed=193.0s

  [16456/21087] intraday_5368.csv.gz  in=427,755,598 out=113,089,395 elapsed=193.0s

  [16457/21087] intraday_5369.csv.gz  in=427,769,942 out=113,089,395 elapsed=193.0s

  [16458/21087] intraday_5370.csv.gz  in=427,786,023 out=113,089,395 elapsed=193.0s

  [16459/21087] intraday_5371.csv.gz  in=427,798,703 out=113,089,395 elapsed=193.1s

  [16460/21087] intraday_5372.csv.gz  in=427,810,927 out=113,089,395 elapsed=193.1s

  [16461/21087] intraday_5373.csv.gz  in=427,825,534 out=113,089,395 elapsed=193.1s

  [16462/21087] intraday_5374.csv.gz  in=427,838,270 out=113,089,395 elapsed=193.1s

  [16463/21087] intraday_5375.csv.gz  in=427,850,787 out=113,089,395 elapsed=193.1s

  [16464/21087] intraday_5376.csv.gz  in=427,866,633 out=113,089,395 elapsed=193.1s

  [16465/21087] intraday_5377.csv.gz  in=427,880,763 out=113,089,395 elapsed=193.1s

  [16466/21087] intraday_5378.csv.gz  in=427,894,332 out=113,089,395 elapsed=193.1s

  [16467/21087] intraday_5379.csv.gz  in=427,907,244 out=113,089,395 elapsed=193.1s

  [16468/21087] intraday_5380.csv.gz  in=427,918,194 out=113,089,395 elapsed=193.1s

  [16469/21087] intraday_5381.csv.gz  in=427,931,895 out=113,089,395 elapsed=193.1s

  [16470/21087] intraday_5382.csv.gz  in=427,943,551 out=113,089,395 elapsed=193.1s

  [16471/21087] intraday_5384.csv.gz  in=427,952,423 out=113,089,395 elapsed=193.2s

  [16472/21087] intraday_5383.csv.gz  in=427,966,876 out=113,089,395 elapsed=193.2s

  [16473/21087] intraday_5385.csv.gz  in=427,978,396 out=113,089,395 elapsed=193.2s

  [16474/21087] intraday_5387.csv.gz  in=427,978,951 out=113,089,395 elapsed=193.2s

  [16475/21087] intraday_5388.csv.gz  in=427,979,751 out=113,089,395 elapsed=193.2s

  [16476/21087] intraday_5386.csv.gz  in=427,989,309 out=113,089,395 elapsed=193.2s

  [16477/21087] intraday_5389.csv.gz  in=427,991,083 out=113,089,395 elapsed=193.2s

  [16478/21087] intraday_5390.csv.gz  in=427,991,687 out=113,089,395 elapsed=193.2s

  [16479/21087] intraday_5391.csv.gz  in=427,991,854 out=113,089,395 elapsed=193.2s

  [16480/21087] intraday_5392.csv.gz  in=427,992,612 out=113,089,395 elapsed=193.2s

  [16481/21087] intraday_5393.csv.gz  in=427,992,967 out=113,089,395 elapsed=193.2s

  [16482/21087] intraday_5394.csv.gz  in=427,993,360 out=113,089,395 elapsed=193.2s

  [16483/21087] intraday_5395.csv.gz  in=427,993,390 out=113,089,395 elapsed=193.2s

  [16484/21087] intraday_5396.csv.gz  in=427,993,424 out=113,089,395 elapsed=193.2s

  [16485/21087] intraday_5397.csv.gz  in=428,009,170 out=113,089,395 elapsed=193.2s

  [16486/21087] intraday_5398.csv.gz  in=428,022,349 out=113,089,395 elapsed=193.3s

  [16487/21087] intraday_5399.csv.gz  in=428,035,775 out=113,089,395 elapsed=193.3s

  [16488/21087] intraday_5400.csv.gz  in=428,048,043 out=113,089,395 elapsed=193.3s

  [16489/21087] intraday_5401.csv.gz  in=428,060,830 out=113,089,395 elapsed=193.3s

  [16490/21087] intraday_5402.csv.gz  in=428,076,098 out=113,089,395 elapsed=193.3s

  [16491/21087] intraday_5404.csv.gz  in=428,087,880 out=113,089,395 elapsed=193.3s

  [16492/21087] intraday_5403.csv.gz  in=428,102,327 out=113,089,395 elapsed=193.3s

  [16493/21087] intraday_5405.csv.gz  in=428,116,340 out=113,089,395 elapsed=193.3s

  [16494/21087] intraday_5406.csv.gz  in=428,130,930 out=113,089,395 elapsed=193.3s

  [16495/21087] intraday_5407.csv.gz  in=428,145,186 out=113,089,395 elapsed=193.3s

  [16496/21087] intraday_5408.csv.gz  in=428,158,921 out=113,089,395 elapsed=193.3s

  [16497/21087] intraday_5409.csv.gz  in=428,170,999 out=113,089,395 elapsed=193.3s

  [16498/21087] intraday_5410.csv.gz  in=428,183,286 out=113,089,395 elapsed=193.4s

  [16499/21087] intraday_5411.csv.gz  in=428,193,900 out=113,089,395 elapsed=193.4s

  [16500/21087] intraday_5412.csv.gz  in=428,203,359 out=113,089,395 elapsed=193.4s

  [16501/21087] intraday_5413.csv.gz  in=428,218,816 out=113,089,395 elapsed=193.4s

  [16502/21087] intraday_5414.csv.gz  in=428,232,524 out=113,089,395 elapsed=193.4s

  [16503/21087] intraday_5415.csv.gz  in=428,244,144 out=113,089,395 elapsed=193.4s

  [16504/21087] intraday_5416.csv.gz  in=428,256,249 out=113,089,395 elapsed=193.4s

  [16505/21087] intraday_5417.csv.gz  in=428,269,485 out=113,089,395 elapsed=193.4s

  [16506/21087] intraday_5418.csv.gz  in=428,283,109 out=113,089,395 elapsed=193.4s

  [16507/21087] intraday_5419.csv.gz  in=428,296,392 out=113,089,395 elapsed=193.4s

  [16508/21087] intraday_5420.csv.gz  in=428,308,842 out=113,089,395 elapsed=193.4s

  [16509/21087] intraday_5421.csv.gz  in=428,322,338 out=113,089,395 elapsed=193.4s

  [16510/21087] intraday_5422.csv.gz  in=428,333,498 out=113,089,395 elapsed=193.4s

  [16511/21087] intraday_5423.csv.gz  in=428,345,961 out=113,089,395 elapsed=193.5s

  [16512/21087] intraday_5424.csv.gz  in=428,357,401 out=113,089,395 elapsed=193.5s

  [16513/21087] intraday_5425.csv.gz  in=428,371,809 out=113,089,395 elapsed=193.5s

  [16514/21087] intraday_5426.csv.gz  in=428,386,962 out=113,089,395 elapsed=193.5s

  [16515/21087] intraday_5427.csv.gz  in=428,402,346 out=113,089,395 elapsed=193.5s

  [16516/21087] intraday_5428.csv.gz  in=428,413,925 out=113,089,395 elapsed=193.5s

  [16517/21087] intraday_5429.csv.gz  in=428,425,876 out=113,089,395 elapsed=193.5s

  [16518/21087] intraday_5430.csv.gz  in=428,438,263 out=113,089,395 elapsed=193.5s

  [16519/21087] intraday_5431.csv.gz  in=428,452,755 out=113,089,395 elapsed=193.5s

  [16520/21087] intraday_5432.csv.gz  in=428,463,674 out=113,089,395 elapsed=193.5s

  [16521/21087] intraday_5433.csv.gz  in=428,476,304 out=113,089,395 elapsed=193.5s

  [16522/21087] intraday_5434.csv.gz  in=428,489,392 out=113,089,395 elapsed=193.5s

  [16523/21087] intraday_5435.csv.gz  in=428,500,289 out=113,089,395 elapsed=193.6s

  [16524/21087] intraday_5436.csv.gz  in=428,511,357 out=113,089,395 elapsed=193.6s

  [16525/21087] intraday_5437.csv.gz  in=428,524,522 out=113,089,395 elapsed=193.6s

  [16526/21087] intraday_5438.csv.gz  in=428,537,603 out=113,089,395 elapsed=193.6s

  [16527/21087] intraday_5439.csv.gz  in=428,551,356 out=113,089,395 elapsed=193.6s

  [16528/21087] intraday_5440.csv.gz  in=428,564,705 out=113,089,395 elapsed=193.6s

  [16529/21087] intraday_5441.csv.gz  in=428,578,343 out=113,089,395 elapsed=193.6s

  [16530/21087] intraday_5442.csv.gz  in=428,590,692 out=113,089,395 elapsed=193.6s

  [16531/21087] intraday_5443.csv.gz  in=428,602,925 out=113,089,395 elapsed=193.6s

  [16532/21087] intraday_5444.csv.gz  in=428,614,557 out=113,089,395 elapsed=193.6s

  [16533/21087] intraday_5445.csv.gz  in=428,627,160 out=113,089,395 elapsed=193.6s

  [16534/21087] intraday_5446.csv.gz  in=428,638,380 out=113,089,395 elapsed=193.6s

  [16535/21087] intraday_5447.csv.gz  in=428,650,339 out=113,089,395 elapsed=193.6s

  [16536/21087] intraday_5448.csv.gz  in=428,665,514 out=113,089,395 elapsed=193.7s

  [16537/21087] intraday_5449.csv.gz  in=428,675,236 out=113,089,395 elapsed=193.7s

  [16538/21087] intraday_5450.csv.gz  in=428,686,978 out=113,089,395 elapsed=193.7s

  [16539/21087] intraday_5451.csv.gz  in=428,701,258 out=113,089,395 elapsed=193.7s

  [16540/21087] intraday_5453.csv.gz  in=428,716,193 out=113,089,395 elapsed=193.7s

  [16541/21087] intraday_5452.csv.gz  in=428,738,090 out=113,089,395 elapsed=193.7s

  [16542/21087] intraday_5454.csv.gz  in=428,750,472 out=113,089,395 elapsed=193.7s

  [16543/21087] intraday_5455.csv.gz  in=428,763,725 out=113,089,395 elapsed=193.7s

  [16544/21087] intraday_5456.csv.gz  in=428,776,710 out=113,089,395 elapsed=193.7s

  [16545/21087] intraday_5457.csv.gz  in=428,789,757 out=113,089,395 elapsed=193.7s

  [16546/21087] intraday_5458.csv.gz  in=428,801,432 out=113,089,395 elapsed=193.7s

  [16547/21087] intraday_5459.csv.gz  in=428,812,210 out=113,089,395 elapsed=193.7s

  [16548/21087] intraday_5460.csv.gz  in=428,822,617 out=113,089,395 elapsed=193.7s

  [16549/21087] intraday_5462.csv.gz  in=428,836,061 out=113,089,395 elapsed=193.8s

  [16550/21087] intraday_5461.csv.gz  in=428,851,216 out=113,089,395 elapsed=193.8s

  [16551/21087] intraday_5463.csv.gz  in=428,865,728 out=113,089,395 elapsed=193.8s

  [16552/21087] intraday_5464.csv.gz  in=428,877,614 out=113,089,395 elapsed=193.8s

  [16553/21087] intraday_5465.csv.gz  in=428,887,774 out=113,089,395 elapsed=193.8s

  [16554/21087] intraday_5466.csv.gz  in=428,899,514 out=113,089,395 elapsed=193.8s

  [16555/21087] intraday_5467.csv.gz  in=428,911,964 out=113,089,395 elapsed=193.8s

  [16556/21087] intraday_5468.csv.gz  in=428,923,883 out=113,089,395 elapsed=193.8s

  [16557/21087] intraday_5469.csv.gz  in=428,937,808 out=113,089,395 elapsed=193.8s

  [16558/21087] intraday_5470.csv.gz  in=428,949,468 out=113,089,395 elapsed=193.8s

  [16559/21087] intraday_5471.csv.gz  in=428,961,099 out=113,089,395 elapsed=193.8s

  [16560/21087] intraday_5472.csv.gz  in=428,972,858 out=113,089,395 elapsed=193.8s

  [16561/21087] intraday_5473.csv.gz  in=428,986,465 out=113,089,395 elapsed=193.9s

  [16562/21087] intraday_5474.csv.gz  in=428,997,899 out=113,089,395 elapsed=193.9s

  [16563/21087] intraday_5475.csv.gz  in=429,011,168 out=113,089,395 elapsed=193.9s

  [16564/21087] intraday_5476.csv.gz  in=429,021,219 out=113,089,395 elapsed=193.9s

  [16565/21087] intraday_5478.csv.gz  in=429,033,261 out=113,089,395 elapsed=193.9s

  [16566/21087] intraday_5477.csv.gz  in=429,046,420 out=113,089,395 elapsed=193.9s

  [16567/21087] intraday_5479.csv.gz  in=429,062,605 out=113,089,395 elapsed=193.9s

  [16568/21087] intraday_5480.csv.gz  in=429,076,229 out=113,089,395 elapsed=193.9s

  [16569/21087] intraday_5481.csv.gz  in=429,088,583 out=113,089,395 elapsed=193.9s

  [16570/21087] intraday_5482.csv.gz  in=429,100,280 out=113,089,395 elapsed=193.9s

  [16571/21087] intraday_5483.csv.gz  in=429,111,964 out=113,089,395 elapsed=193.9s

  [16572/21087] intraday_5484.csv.gz  in=429,126,122 out=113,089,395 elapsed=194.0s

  [16573/21087] intraday_5486.csv.gz  in=429,138,258 out=113,089,395 elapsed=194.0s

  [16574/21087] intraday_5485.csv.gz  in=429,157,538 out=113,089,395 elapsed=194.0s

  [16575/21087] intraday_5487.csv.gz  in=429,171,097 out=113,089,395 elapsed=194.0s

  [16576/21087] intraday_5488.csv.gz  in=429,184,319 out=113,089,395 elapsed=194.0s

  [16577/21087] intraday_5489.csv.gz  in=429,198,455 out=113,089,395 elapsed=194.0s

  [16578/21087] intraday_5490.csv.gz  in=429,212,221 out=113,089,395 elapsed=194.0s

  [16579/21087] intraday_5491.csv.gz  in=429,224,560 out=113,089,395 elapsed=194.0s

  [16580/21087] intraday_5492.csv.gz  in=429,237,804 out=113,089,395 elapsed=194.0s

  [16581/21087] intraday_5493.csv.gz  in=429,249,206 out=113,089,395 elapsed=194.0s

  [16582/21087] intraday_5494.csv.gz  in=429,263,672 out=113,089,395 elapsed=194.0s

  [16583/21087] intraday_5495.csv.gz  in=429,276,195 out=113,089,395 elapsed=194.0s

  [16584/21087] intraday_5496.csv.gz  in=429,289,543 out=113,089,395 elapsed=194.0s

  [16585/21087] intraday_5497.csv.gz  in=429,320,270 out=113,089,395 elapsed=194.1s

  [16586/21087] intraday_5499.csv.gz  in=429,331,776 out=113,089,395 elapsed=194.1s

  [16587/21087] intraday_5498.csv.gz  in=429,347,040 out=113,089,395 elapsed=194.1s

  [16588/21087] intraday_5500.csv.gz  in=429,360,159 out=113,089,395 elapsed=194.1s

  [16589/21087] intraday_5501.csv.gz  in=429,376,687 out=113,089,395 elapsed=194.1s

  [16590/21087] intraday_5503.csv.gz  in=429,388,921 out=113,089,395 elapsed=194.1s

  [16591/21087] intraday_5504.csv.gz  in=429,405,203 out=113,089,395 elapsed=194.1s

  [16592/21087] intraday_5502.csv.gz  in=429,416,307 out=113,089,395 elapsed=194.1s

  [16593/21087] intraday_5506.csv.gz  in=429,428,652 out=113,089,395 elapsed=194.1s

  [16594/21087] intraday_5507.csv.gz  in=429,442,260 out=113,089,395 elapsed=194.1s

  [16595/21087] intraday_5505.csv.gz  in=429,457,049 out=113,089,395 elapsed=194.1s

  [16596/21087] intraday_5508.csv.gz  in=429,470,690 out=113,089,395 elapsed=194.1s

  [16597/21087] intraday_5509.csv.gz  in=429,483,685 out=113,089,395 elapsed=194.2s

  [16598/21087] intraday_5511.csv.gz  in=429,496,624 out=113,089,395 elapsed=194.2s

  [16599/21087] intraday_5510.csv.gz  in=429,513,017 out=113,089,395 elapsed=194.2s

  [16600/21087] intraday_5512.csv.gz  in=429,527,946 out=113,089,395 elapsed=194.2s

  [16601/21087] intraday_5513.csv.gz  in=429,544,291 out=113,089,395 elapsed=194.2s

  [16602/21087] intraday_5514.csv.gz  in=429,558,279 out=113,089,395 elapsed=194.2s

  [16603/21087] intraday_5515.csv.gz  in=429,570,436 out=113,089,395 elapsed=194.2s

  [16604/21087] intraday_5516.csv.gz  in=429,581,476 out=113,089,395 elapsed=194.2s

  [16605/21087] intraday_5517.csv.gz  in=429,596,028 out=113,089,395 elapsed=194.2s

  [16606/21087] intraday_5518.csv.gz  in=429,606,950 out=113,089,395 elapsed=194.2s

  [16607/21087] intraday_5519.csv.gz  in=429,620,392 out=113,089,395 elapsed=194.2s

  [16608/21087] intraday_5520.csv.gz  in=429,633,278 out=113,089,395 elapsed=194.2s

  [16609/21087] intraday_5521.csv.gz  in=429,649,748 out=113,089,395 elapsed=194.2s

  [16610/21087] intraday_5522.csv.gz  in=429,662,798 out=113,089,395 elapsed=194.3s

  [16611/21087] intraday_5523.csv.gz  in=429,675,549 out=113,089,395 elapsed=194.3s

  [16612/21087] intraday_5524.csv.gz  in=429,688,698 out=113,089,395 elapsed=194.3s

  [16613/21087] intraday_5525.csv.gz  in=429,702,285 out=113,089,395 elapsed=194.3s

  [16614/21087] intraday_5527.csv.gz  in=429,715,366 out=113,089,395 elapsed=194.3s

  [16615/21087] intraday_5526.csv.gz  in=429,730,788 out=113,089,395 elapsed=194.3s

  [16616/21087] intraday_5528.csv.gz  in=429,745,634 out=113,089,395 elapsed=194.3s

  [16617/21087] intraday_5529.csv.gz  in=429,760,489 out=113,089,395 elapsed=194.3s

  [16618/21087] intraday_5530.csv.gz  in=429,775,696 out=113,089,395 elapsed=194.3s

  [16619/21087] intraday_5531.csv.gz  in=429,786,992 out=113,089,395 elapsed=194.3s

  [16620/21087] intraday_5532.csv.gz  in=429,798,771 out=113,089,395 elapsed=194.3s

  [16621/21087] intraday_5533.csv.gz  in=429,812,539 out=113,089,395 elapsed=194.3s

  [16622/21087] intraday_5534.csv.gz  in=429,824,719 out=113,089,395 elapsed=194.3s

  [16623/21087] intraday_5536.csv.gz  in=429,832,334 out=113,089,395 elapsed=194.4s

  [16624/21087] intraday_5537.csv.gz  in=429,843,955 out=113,089,395 elapsed=194.4s

  [16625/21087] intraday_5535.csv.gz  in=429,877,637 out=113,089,395 elapsed=194.4s

  [16626/21087] intraday_5538.csv.gz  in=429,886,255 out=113,089,395 elapsed=194.4s

  [16627/21087] intraday_5539.csv.gz  in=429,900,682 out=113,089,395 elapsed=194.4s

  [16628/21087] intraday_5540.csv.gz  in=429,913,968 out=113,089,395 elapsed=194.4s

  [16629/21087] intraday_5541.csv.gz  in=429,926,363 out=113,089,395 elapsed=194.4s

  [16630/21087] intraday_5542.csv.gz  in=429,937,946 out=113,089,395 elapsed=194.4s

  [16631/21087] intraday_5543.csv.gz  in=429,950,262 out=113,089,395 elapsed=194.4s

  [16632/21087] intraday_5546.csv.gz  in=429,961,788 out=113,089,395 elapsed=194.4s

  [16633/21087] intraday_5545.csv.gz  in=429,977,212 out=113,089,395 elapsed=194.4s

  [16634/21087] intraday_5544.csv.gz  in=429,992,407 out=113,089,395 elapsed=194.4s

  [16635/21087] intraday_5547.csv.gz  in=430,005,253 out=113,089,395 elapsed=194.4s

  [16636/21087] intraday_5548.csv.gz  in=430,018,824 out=113,089,395 elapsed=194.5s

  [16637/21087] intraday_5551.csv.gz  in=430,030,792 out=113,089,395 elapsed=194.5s

  [16638/21087] intraday_5549.csv.gz  in=430,044,138 out=113,089,395 elapsed=194.5s

  [16639/21087] intraday_5550.csv.gz  in=430,061,085 out=113,089,395 elapsed=194.5s

  [16640/21087] intraday_5552.csv.gz  in=430,072,604 out=113,089,395 elapsed=194.5s

  [16641/21087] intraday_5554.csv.gz  in=430,081,597 out=113,089,395 elapsed=194.5s

  [16642/21087] intraday_5553.csv.gz  in=430,091,766 out=113,089,395 elapsed=194.5s

  [16643/21087] intraday_5555.csv.gz  in=430,106,070 out=113,089,395 elapsed=194.5s

  [16644/21087] intraday_5557.csv.gz  in=430,116,308 out=113,089,395 elapsed=194.5s

  [16645/21087] intraday_5556.csv.gz  in=430,129,825 out=113,089,395 elapsed=194.5s

  [16646/21087] intraday_5558.csv.gz  in=430,141,046 out=113,089,395 elapsed=194.5s

  [16647/21087] intraday_5559.csv.gz  in=430,153,074 out=113,089,395 elapsed=194.5s

  [16648/21087] intraday_5560.csv.gz  in=430,166,834 out=113,089,395 elapsed=194.6s

  [16649/21087] intraday_5561.csv.gz  in=430,179,363 out=113,089,395 elapsed=194.6s

  [16650/21087] intraday_5562.csv.gz  in=430,191,693 out=113,089,395 elapsed=194.6s

  [16651/21087] intraday_5563.csv.gz  in=430,205,405 out=113,089,395 elapsed=194.6s

  [16652/21087] intraday_5564.csv.gz  in=430,216,469 out=113,089,395 elapsed=194.6s

  [16653/21087] intraday_5565.csv.gz  in=430,228,863 out=113,089,395 elapsed=194.6s

  [16654/21087] intraday_5566.csv.gz  in=430,240,389 out=113,089,395 elapsed=194.6s

  [16655/21087] intraday_5567.csv.gz  in=430,253,415 out=113,089,395 elapsed=194.6s

  [16656/21087] intraday_5568.csv.gz  in=430,268,289 out=113,089,395 elapsed=194.6s

  [16657/21087] intraday_5569.csv.gz  in=430,283,192 out=113,089,395 elapsed=194.6s

  [16658/21087] intraday_5570.csv.gz  in=430,293,926 out=113,089,395 elapsed=194.6s

  [16659/21087] intraday_5571.csv.gz  in=430,305,576 out=113,089,395 elapsed=194.6s

  [16660/21087] intraday_5572.csv.gz  in=430,317,658 out=113,089,395 elapsed=194.6s

  [16661/21087] intraday_5573.csv.gz  in=430,331,506 out=113,089,395 elapsed=194.7s

  [16662/21087] intraday_5574.csv.gz  in=430,353,159 out=113,089,395 elapsed=194.7s

  [16663/21087] intraday_5575.csv.gz  in=430,364,938 out=113,089,395 elapsed=194.7s

  [16664/21087] intraday_5576.csv.gz  in=430,376,622 out=113,089,395 elapsed=194.7s

  [16665/21087] intraday_5577.csv.gz  in=430,387,288 out=113,089,395 elapsed=194.7s

  [16666/21087] intraday_5578.csv.gz  in=430,398,342 out=113,089,395 elapsed=194.7s

  [16667/21087] intraday_5579.csv.gz  in=430,414,897 out=113,089,395 elapsed=194.7s

  [16668/21087] intraday_5580.csv.gz  in=430,427,260 out=113,089,395 elapsed=194.7s

  [16669/21087] intraday_5581.csv.gz  in=430,439,468 out=113,089,395 elapsed=194.7s

  [16670/21087] intraday_5582.csv.gz  in=430,453,263 out=113,089,395 elapsed=194.7s

  [16671/21087] intraday_5583.csv.gz  in=430,465,922 out=113,089,395 elapsed=194.7s

  [16672/21087] intraday_5584.csv.gz  in=430,477,811 out=113,089,395 elapsed=194.8s

  [16673/21087] intraday_5585.csv.gz  in=430,489,636 out=113,089,395 elapsed=194.8s

  [16674/21087] intraday_5586.csv.gz  in=430,500,998 out=113,089,395 elapsed=194.8s

  [16675/21087] intraday_5587.csv.gz  in=430,513,053 out=113,089,395 elapsed=194.8s

  [16676/21087] intraday_5588.csv.gz  in=430,524,222 out=113,089,395 elapsed=194.8s

  [16677/21087] intraday_5589.csv.gz  in=430,535,542 out=113,089,395 elapsed=194.8s

  [16678/21087] intraday_5590.csv.gz  in=430,549,463 out=113,089,395 elapsed=194.8s

  [16679/21087] intraday_5592.csv.gz  in=430,559,503 out=113,089,395 elapsed=194.8s

  [16680/21087] intraday_5591.csv.gz  in=430,569,689 out=113,089,395 elapsed=194.8s

  [16681/21087] intraday_5593.csv.gz  in=430,584,091 out=113,089,395 elapsed=194.8s

  [16682/21087] intraday_5594.csv.gz  in=430,596,321 out=113,089,395 elapsed=194.8s

  [16683/21087] intraday_5595.csv.gz  in=430,610,450 out=113,089,395 elapsed=194.8s

  [16684/21087] intraday_5596.csv.gz  in=430,622,239 out=113,089,395 elapsed=194.8s

  [16685/21087] intraday_5597.csv.gz  in=430,634,990 out=113,089,395 elapsed=194.9s

  [16686/21087] intraday_5598.csv.gz  in=430,647,277 out=113,089,395 elapsed=194.9s

  [16687/21087] intraday_5599.csv.gz  in=430,659,867 out=113,089,395 elapsed=194.9s

  [16688/21087] intraday_5600.csv.gz  in=430,671,366 out=113,089,395 elapsed=194.9s

  [16689/21087] intraday_5601.csv.gz  in=430,682,104 out=113,089,395 elapsed=194.9s

  [16690/21087] intraday_5602.csv.gz  in=430,692,826 out=113,089,395 elapsed=194.9s

  [16691/21087] intraday_5603.csv.gz  in=430,707,376 out=113,089,395 elapsed=194.9s

  [16692/21087] intraday_5604.csv.gz  in=430,720,419 out=113,089,395 elapsed=194.9s

  [16693/21087] intraday_5605.csv.gz  in=430,734,463 out=113,089,395 elapsed=194.9s

  [16694/21087] intraday_5606.csv.gz  in=430,746,584 out=113,089,395 elapsed=194.9s

  [16695/21087] intraday_5607.csv.gz  in=430,756,260 out=113,089,395 elapsed=194.9s

  [16696/21087] intraday_5608.csv.gz  in=430,767,775 out=113,089,395 elapsed=194.9s

  [16697/21087] intraday_5609.csv.gz  in=430,779,473 out=113,089,395 elapsed=194.9s

  [16698/21087] intraday_5610.csv.gz  in=430,791,580 out=113,089,395 elapsed=194.9s

  [16699/21087] intraday_5611.csv.gz  in=430,805,012 out=113,089,395 elapsed=195.0s

  [16700/21087] intraday_5612.csv.gz  in=430,816,086 out=113,089,395 elapsed=195.0s

  [16701/21087] intraday_5613.csv.gz  in=430,827,683 out=113,089,395 elapsed=195.0s

  [16702/21087] intraday_5614.csv.gz  in=430,838,113 out=113,089,395 elapsed=195.0s

  [16703/21087] intraday_5616.csv.gz  in=430,849,021 out=113,089,395 elapsed=195.0s

  [16704/21087] intraday_5615.csv.gz  in=430,862,389 out=113,089,395 elapsed=195.0s

  [16705/21087] intraday_5617.csv.gz  in=430,875,023 out=113,089,395 elapsed=195.0s

  [16706/21087] intraday_5618.csv.gz  in=430,885,655 out=113,089,395 elapsed=195.0s

  [16707/21087] intraday_5619.csv.gz  in=430,897,296 out=113,089,395 elapsed=195.0s

  [16708/21087] intraday_5621.csv.gz  in=430,912,304 out=113,089,395 elapsed=195.0s

  [16709/21087] intraday_5620.csv.gz  in=430,923,714 out=113,089,395 elapsed=195.0s

  [16710/21087] intraday_5622.csv.gz  in=430,937,825 out=113,089,395 elapsed=195.0s

  [16711/21087] intraday_5623.csv.gz  in=430,949,791 out=113,089,395 elapsed=195.1s

  [16712/21087] intraday_5624.csv.gz  in=430,961,748 out=113,089,395 elapsed=195.1s

  [16713/21087] intraday_5625.csv.gz  in=430,972,862 out=113,089,395 elapsed=195.1s

  [16714/21087] intraday_5627.csv.gz  in=430,988,870 out=113,089,395 elapsed=195.1s

  [16715/21087] intraday_5626.csv.gz  in=431,002,497 out=113,089,395 elapsed=195.1s

  [16716/21087] intraday_5628.csv.gz  in=431,014,440 out=113,089,395 elapsed=195.1s

  [16717/21087] intraday_5629.csv.gz  in=431,027,649 out=113,089,395 elapsed=195.1s

  [16718/21087] intraday_5630.csv.gz  in=431,040,664 out=113,089,395 elapsed=195.1s

  [16719/21087] intraday_5631.csv.gz  in=431,054,213 out=113,089,395 elapsed=195.1s

  [16720/21087] intraday_5632.csv.gz  in=431,068,519 out=113,089,395 elapsed=195.1s

  [16721/21087] intraday_5633.csv.gz  in=431,080,921 out=113,089,395 elapsed=195.1s

  [16722/21087] intraday_5634.csv.gz  in=431,093,901 out=113,089,395 elapsed=195.1s

  [16723/21087] intraday_5635.csv.gz  in=431,105,454 out=113,089,395 elapsed=195.2s

  [16724/21087] intraday_5636.csv.gz  in=431,119,442 out=113,089,395 elapsed=195.2s

  [16725/21087] intraday_5638.csv.gz  in=431,132,155 out=113,089,395 elapsed=195.2s

  [16726/21087] intraday_5637.csv.gz  in=431,159,865 out=113,089,395 elapsed=195.2s

  [16727/21087] intraday_5639.csv.gz  in=431,171,842 out=113,089,395 elapsed=195.2s

  [16728/21087] intraday_5640.csv.gz  in=431,186,458 out=113,089,395 elapsed=195.2s

  [16729/21087] intraday_5641.csv.gz  in=431,197,404 out=113,089,395 elapsed=195.2s

  [16730/21087] intraday_5642.csv.gz  in=431,209,772 out=113,089,395 elapsed=195.2s

  [16731/21087] intraday_5644.csv.gz  in=431,220,469 out=113,089,395 elapsed=195.2s

  [16732/21087] intraday_5643.csv.gz  in=431,236,877 out=113,089,395 elapsed=195.2s

  [16733/21087] intraday_5645.csv.gz  in=431,250,582 out=113,089,395 elapsed=195.2s

  [16734/21087] intraday_5646.csv.gz  in=431,266,515 out=113,089,395 elapsed=195.2s

  [16735/21087] intraday_5647.csv.gz  in=431,281,454 out=113,089,395 elapsed=195.3s

  [16736/21087] intraday_5648.csv.gz  in=431,293,553 out=113,089,395 elapsed=195.3s

  [16737/21087] intraday_5649.csv.gz  in=431,306,699 out=113,089,395 elapsed=195.3s

  [16738/21087] intraday_5650.csv.gz  in=431,320,140 out=113,089,395 elapsed=195.3s

  [16739/21087] intraday_5651.csv.gz  in=431,332,927 out=113,089,395 elapsed=195.3s

  [16740/21087] intraday_5654.csv.gz  in=431,346,251 out=113,089,395 elapsed=195.3s

  [16741/21087] intraday_5652.csv.gz  in=431,362,000 out=113,089,395 elapsed=195.3s

  [16742/21087] intraday_5653.csv.gz  in=431,374,881 out=113,089,395 elapsed=195.3s

  [16743/21087] intraday_5655.csv.gz  in=431,390,457 out=113,089,395 elapsed=195.3s

  [16744/21087] intraday_5657.csv.gz  in=431,402,470 out=113,089,395 elapsed=195.3s

  [16745/21087] intraday_5656.csv.gz  in=431,415,816 out=113,089,395 elapsed=195.4s

  [16746/21087] intraday_5658.csv.gz  in=431,426,935 out=113,089,395 elapsed=195.4s

  [16747/21087] intraday_5659.csv.gz  in=431,440,989 out=113,089,395 elapsed=195.4s

  [16748/21087] intraday_5660.csv.gz  in=431,452,131 out=113,089,395 elapsed=195.4s

  [16749/21087] intraday_5661.csv.gz  in=431,465,451 out=113,089,395 elapsed=195.4s

  [16750/21087] intraday_5662.csv.gz  in=431,477,619 out=113,089,395 elapsed=195.4s

  [16751/21087] intraday_5663.csv.gz  in=431,494,490 out=113,089,395 elapsed=195.4s

  [16752/21087] intraday_5664.csv.gz  in=431,506,735 out=113,089,395 elapsed=195.4s

  [16753/21087] intraday_5665.csv.gz  in=431,519,333 out=113,089,395 elapsed=195.4s

  [16754/21087] intraday_5666.csv.gz  in=431,531,278 out=113,089,395 elapsed=195.4s

  [16755/21087] intraday_5667.csv.gz  in=431,543,688 out=113,089,395 elapsed=195.4s

  [16756/21087] intraday_5668.csv.gz  in=431,555,277 out=113,089,395 elapsed=195.4s

  [16757/21087] intraday_5670.csv.gz  in=431,569,282 out=113,089,395 elapsed=195.4s

  [16758/21087] intraday_5669.csv.gz  in=431,582,970 out=113,089,395 elapsed=195.5s

  [16759/21087] intraday_5671.csv.gz  in=431,598,508 out=113,089,395 elapsed=195.5s

  [16760/21087] intraday_5672.csv.gz  in=431,612,319 out=113,089,395 elapsed=195.5s

  [16761/21087] intraday_5674.csv.gz  in=431,624,112 out=113,089,395 elapsed=195.5s

  [16762/21087] intraday_5673.csv.gz  in=431,635,089 out=113,089,395 elapsed=195.5s

  [16763/21087] intraday_5675.csv.gz  in=431,648,705 out=113,089,395 elapsed=195.5s

  [16764/21087] intraday_5676.csv.gz  in=431,660,915 out=113,089,395 elapsed=195.5s

  [16765/21087] intraday_5678.csv.gz  in=431,668,294 out=113,089,395 elapsed=195.5s

  [16766/21087] intraday_5677.csv.gz  in=431,693,992 out=113,089,395 elapsed=195.5s

  [16767/21087] intraday_5680.csv.gz  in=431,701,697 out=113,089,395 elapsed=195.5s

  [16768/21087] intraday_5679.csv.gz  in=431,712,908 out=113,089,395 elapsed=195.5s

  [16769/21087] intraday_5681.csv.gz  in=431,728,404 out=113,089,395 elapsed=195.5s

  [16770/21087] intraday_5682.csv.gz  in=431,741,535 out=113,089,395 elapsed=195.5s

  [16771/21087] intraday_5683.csv.gz  in=431,753,773 out=113,089,395 elapsed=195.6s

  [16772/21087] intraday_5684.csv.gz  in=431,764,356 out=113,089,395 elapsed=195.6s

  [16773/21087] intraday_5685.csv.gz  in=431,776,741 out=113,089,395 elapsed=195.6s

  [16774/21087] intraday_5686.csv.gz  in=431,792,148 out=113,089,395 elapsed=195.6s

  [16775/21087] intraday_5687.csv.gz  in=431,807,864 out=113,089,395 elapsed=195.6s

  [16776/21087] intraday_5688.csv.gz  in=431,819,551 out=113,089,395 elapsed=195.6s

  [16777/21087] intraday_5689.csv.gz  in=431,833,186 out=113,089,395 elapsed=195.6s

  [16778/21087] intraday_5690.csv.gz  in=431,847,276 out=113,089,395 elapsed=195.6s

  [16779/21087] intraday_5691.csv.gz  in=431,859,954 out=113,089,395 elapsed=195.6s

  [16780/21087] intraday_5692.csv.gz  in=431,873,388 out=113,089,395 elapsed=195.6s

  [16781/21087] intraday_5693.csv.gz  in=431,887,570 out=113,089,395 elapsed=195.6s

  [16782/21087] intraday_5694.csv.gz  in=431,899,251 out=113,089,395 elapsed=195.6s

  [16783/21087] intraday_5695.csv.gz  in=431,909,911 out=113,089,395 elapsed=195.6s

  [16784/21087] intraday_5696.csv.gz  in=431,919,520 out=113,089,395 elapsed=195.7s

  [16785/21087] intraday_5697.csv.gz  in=431,933,300 out=113,089,395 elapsed=195.7s

  [16786/21087] intraday_5698.csv.gz  in=431,946,251 out=113,089,395 elapsed=195.7s

  [16787/21087] intraday_5700.csv.gz  in=431,958,311 out=113,089,395 elapsed=195.7s

  [16788/21087] intraday_5699.csv.gz  in=431,971,683 out=113,089,395 elapsed=195.7s

  [16789/21087] intraday_5701.csv.gz  in=431,983,540 out=113,089,395 elapsed=195.7s

  [16790/21087] intraday_5702.csv.gz  in=431,996,498 out=113,089,395 elapsed=195.7s

  [16791/21087] intraday_5703.csv.gz  in=432,009,626 out=113,089,395 elapsed=195.7s

  [16792/21087] intraday_5704.csv.gz  in=432,022,480 out=113,089,395 elapsed=195.7s

  [16793/21087] intraday_5705.csv.gz  in=432,035,486 out=113,089,395 elapsed=195.7s

  [16794/21087] intraday_5706.csv.gz  in=432,046,349 out=113,089,395 elapsed=195.7s

  [16795/21087] intraday_5707.csv.gz  in=432,058,239 out=113,089,395 elapsed=195.7s

  [16796/21087] intraday_5708.csv.gz  in=432,070,274 out=113,089,395 elapsed=195.7s

  [16797/21087] intraday_5709.csv.gz  in=432,084,506 out=113,089,395 elapsed=195.8s

  [16798/21087] intraday_5710.csv.gz  in=432,099,534 out=113,089,395 elapsed=195.8s

  [16799/21087] intraday_5711.csv.gz  in=432,114,954 out=113,089,395 elapsed=195.8s

  [16800/21087] intraday_5712.csv.gz  in=432,131,244 out=113,089,395 elapsed=195.8s

  [16801/21087] intraday_5713.csv.gz  in=432,143,268 out=113,089,395 elapsed=195.8s

  [16802/21087] intraday_5714.csv.gz  in=432,155,290 out=113,089,395 elapsed=195.8s

  [16803/21087] intraday_5716.csv.gz  in=432,164,803 out=113,089,395 elapsed=195.8s

  [16804/21087] intraday_5715.csv.gz  in=432,196,784 out=113,089,395 elapsed=195.8s

  [16805/21087] intraday_5718.csv.gz  in=432,207,663 out=113,089,395 elapsed=195.8s

  [16806/21087] intraday_5717.csv.gz  in=432,221,421 out=113,089,395 elapsed=195.8s

  [16807/21087] intraday_5719.csv.gz  in=432,231,727 out=113,089,395 elapsed=195.8s

  [16808/21087] intraday_5720.csv.gz  in=432,242,828 out=113,089,395 elapsed=195.9s

  [16809/21087] intraday_5721.csv.gz  in=432,255,366 out=113,089,395 elapsed=195.9s

  [16810/21087] intraday_5722.csv.gz  in=432,268,731 out=113,089,395 elapsed=195.9s

  [16811/21087] intraday_5723.csv.gz  in=432,280,343 out=113,089,395 elapsed=195.9s

  [16812/21087] intraday_5724.csv.gz  in=432,293,820 out=113,089,395 elapsed=195.9s

  [16813/21087] intraday_5725.csv.gz  in=432,306,410 out=113,089,395 elapsed=195.9s

  [16814/21087] intraday_5727.csv.gz  in=432,317,817 out=113,089,395 elapsed=195.9s

  [16815/21087] intraday_5726.csv.gz  in=432,329,779 out=113,089,395 elapsed=195.9s

  [16816/21087] intraday_5728.csv.gz  in=432,342,079 out=113,089,395 elapsed=195.9s

  [16817/21087] intraday_5729.csv.gz  in=432,352,627 out=113,089,395 elapsed=195.9s

  [16818/21087] intraday_5731.csv.gz  in=432,362,972 out=113,089,395 elapsed=195.9s

  [16819/21087] intraday_5730.csv.gz  in=432,376,656 out=113,089,395 elapsed=195.9s

  [16820/21087] intraday_5732.csv.gz  in=432,391,869 out=113,089,395 elapsed=196.0s

  [16821/21087] intraday_5733.csv.gz  in=432,402,969 out=113,089,395 elapsed=196.0s

  [16822/21087] intraday_5734.csv.gz  in=432,413,587 out=113,089,395 elapsed=196.0s

  [16823/21087] intraday_5735.csv.gz  in=432,428,058 out=113,089,395 elapsed=196.0s

  [16824/21087] intraday_5736.csv.gz  in=432,441,068 out=113,089,395 elapsed=196.0s

  [16825/21087] intraday_5738.csv.gz  in=432,451,986 out=113,089,395 elapsed=196.0s

  [16826/21087] intraday_5739.csv.gz  in=432,465,115 out=113,089,395 elapsed=196.0s

  [16827/21087] intraday_5737.csv.gz  in=432,478,382 out=113,089,395 elapsed=196.0s

  [16828/21087] intraday_5740.csv.gz  in=432,490,775 out=113,089,395 elapsed=196.0s

  [16829/21087] intraday_5741.csv.gz  in=432,503,858 out=113,089,395 elapsed=196.0s

  [16830/21087] intraday_5742.csv.gz  in=432,515,031 out=113,089,395 elapsed=196.0s

  [16831/21087] intraday_5743.csv.gz  in=432,529,457 out=113,089,395 elapsed=196.0s

  [16832/21087] intraday_5744.csv.gz  in=432,540,088 out=113,089,395 elapsed=196.0s

  [16833/21087] intraday_5745.csv.gz  in=432,555,926 out=113,089,395 elapsed=196.0s

  [16834/21087] intraday_5746.csv.gz  in=432,568,801 out=113,089,395 elapsed=196.1s

  [16835/21087] intraday_5747.csv.gz  in=432,582,290 out=113,089,395 elapsed=196.1s

  [16836/21087] intraday_5748.csv.gz  in=432,595,701 out=113,089,395 elapsed=196.1s

  [16837/21087] intraday_5749.csv.gz  in=432,607,166 out=113,089,395 elapsed=196.1s

  [16838/21087] intraday_5750.csv.gz  in=432,618,777 out=113,089,395 elapsed=196.1s

  [16839/21087] intraday_5751.csv.gz  in=432,630,736 out=113,089,395 elapsed=196.1s

  [16840/21087] intraday_5752.csv.gz  in=432,643,280 out=113,089,395 elapsed=196.1s

  [16841/21087] intraday_5753.csv.gz  in=432,656,247 out=113,089,395 elapsed=196.1s

  [16842/21087] intraday_5754.csv.gz  in=432,667,364 out=113,089,395 elapsed=196.1s

  [16843/21087] intraday_5755.csv.gz  in=432,678,949 out=113,089,395 elapsed=196.1s

  [16844/21087] intraday_5756.csv.gz  in=432,691,689 out=113,089,395 elapsed=196.1s

  [16845/21087] intraday_5757.csv.gz  in=432,704,786 out=113,089,395 elapsed=196.1s

  [16846/21087] intraday_5758.csv.gz  in=432,715,454 out=113,089,395 elapsed=196.2s

  [16847/21087] intraday_5760.csv.gz  in=432,725,493 out=113,089,395 elapsed=196.2s

  [16848/21087] intraday_5759.csv.gz  in=432,739,106 out=113,089,395 elapsed=196.2s

  [16849/21087] intraday_5761.csv.gz  in=432,751,168 out=113,089,395 elapsed=196.2s

  [16850/21087] intraday_5762.csv.gz  in=432,763,760 out=113,089,395 elapsed=196.2s

  [16851/21087] intraday_5763.csv.gz  in=432,777,848 out=113,089,395 elapsed=196.2s

  [16852/21087] intraday_5764.csv.gz  in=432,793,548 out=113,089,395 elapsed=196.2s

  [16853/21087] intraday_5765.csv.gz  in=432,806,683 out=113,089,395 elapsed=196.2s

  [16854/21087] intraday_5766.csv.gz  in=432,818,172 out=113,089,395 elapsed=196.2s

  [16855/21087] intraday_5767.csv.gz  in=432,829,654 out=113,089,395 elapsed=196.2s

  [16856/21087] intraday_5768.csv.gz  in=432,843,392 out=113,089,395 elapsed=196.2s

  [16857/21087] intraday_5769.csv.gz  in=432,860,018 out=113,089,395 elapsed=196.2s

  [16858/21087] intraday_5770.csv.gz  in=432,872,660 out=113,089,395 elapsed=196.2s

  [16859/21087] intraday_5771.csv.gz  in=432,889,260 out=113,089,395 elapsed=196.3s

  [16860/21087] intraday_5772.csv.gz  in=432,902,045 out=113,089,395 elapsed=196.3s

  [16861/21087] intraday_5773.csv.gz  in=432,915,525 out=113,089,395 elapsed=196.3s

  [16862/21087] intraday_5774.csv.gz  in=432,929,029 out=113,089,395 elapsed=196.3s

  [16863/21087] intraday_5775.csv.gz  in=432,941,383 out=113,089,395 elapsed=196.3s

  [16864/21087] intraday_5776.csv.gz  in=432,953,497 out=113,089,395 elapsed=196.3s

  [16865/21087] intraday_5777.csv.gz  in=432,966,467 out=113,089,395 elapsed=196.3s

  [16866/21087] intraday_5778.csv.gz  in=432,978,647 out=113,089,395 elapsed=196.3s

  [16867/21087] intraday_5779.csv.gz  in=432,992,556 out=113,089,395 elapsed=196.3s

  [16868/21087] intraday_5780.csv.gz  in=433,004,354 out=113,089,395 elapsed=196.3s

  [16869/21087] intraday_5781.csv.gz  in=433,017,461 out=113,089,395 elapsed=196.3s

  [16870/21087] intraday_5782.csv.gz  in=433,036,352 out=113,089,395 elapsed=196.4s

  [16871/21087] intraday_5783.csv.gz  in=433,049,046 out=113,089,395 elapsed=196.4s

  [16872/21087] intraday_5784.csv.gz  in=433,061,872 out=113,089,395 elapsed=196.4s

  [16873/21087] intraday_5785.csv.gz  in=433,077,622 out=113,089,395 elapsed=196.4s

  [16874/21087] intraday_5786.csv.gz  in=433,088,826 out=113,089,395 elapsed=196.4s

  [16875/21087] intraday_5787.csv.gz  in=433,102,586 out=113,089,395 elapsed=196.4s

  [16876/21087] intraday_5788.csv.gz  in=433,117,099 out=113,089,395 elapsed=196.4s

  [16877/21087] intraday_5789.csv.gz  in=433,132,665 out=113,089,395 elapsed=196.4s

  [16878/21087] intraday_5790.csv.gz  in=433,150,325 out=113,089,395 elapsed=196.4s

  [16879/21087] intraday_5793.csv.gz  in=433,163,056 out=113,089,395 elapsed=196.4s

  [16880/21087] intraday_5792.csv.gz  in=433,176,689 out=113,089,395 elapsed=196.4s

  [16881/21087] intraday_5791.csv.gz  in=433,189,023 out=113,089,395 elapsed=196.4s

  [16882/21087] intraday_5794.csv.gz  in=433,202,804 out=113,089,395 elapsed=196.4s

  [16883/21087] intraday_5797.csv.gz  in=433,217,638 out=113,089,395 elapsed=196.5s

  [16884/21087] intraday_5796.csv.gz  in=433,231,616 out=113,089,395 elapsed=196.5s

  [16885/21087] intraday_5795.csv.gz  in=433,246,320 out=113,089,395 elapsed=196.5s

  [16886/21087] intraday_5798.csv.gz  in=433,259,907 out=113,089,395 elapsed=196.5s

  [16887/21087] intraday_5800.csv.gz  in=433,272,084 out=113,089,395 elapsed=196.5s

  [16888/21087] intraday_5799.csv.gz  in=433,284,332 out=113,089,395 elapsed=196.5s

  [16889/21087] intraday_5801.csv.gz  in=433,297,370 out=113,089,395 elapsed=196.5s

  [16890/21087] intraday_5802.csv.gz  in=433,308,457 out=113,089,395 elapsed=196.5s

  [16891/21087] intraday_5803.csv.gz  in=433,321,402 out=113,089,395 elapsed=196.5s

  [16892/21087] intraday_5804.csv.gz  in=433,333,837 out=113,089,395 elapsed=196.5s

  [16893/21087] intraday_5805.csv.gz  in=433,348,414 out=113,089,395 elapsed=196.5s

  [16894/21087] intraday_5806.csv.gz  in=433,362,118 out=113,089,395 elapsed=196.5s

  [16895/21087] intraday_5807.csv.gz  in=433,374,302 out=113,089,395 elapsed=196.5s

  [16896/21087] intraday_5808.csv.gz  in=433,385,816 out=113,089,395 elapsed=196.5s

  [16897/21087] intraday_5809.csv.gz  in=433,399,526 out=113,089,395 elapsed=196.6s

  [16898/21087] intraday_5810.csv.gz  in=433,411,082 out=113,089,395 elapsed=196.6s

  [16899/21087] intraday_5811.csv.gz  in=433,423,314 out=113,089,395 elapsed=196.6s

  [16900/21087] intraday_5812.csv.gz  in=433,438,863 out=113,089,395 elapsed=196.6s

  [16901/21087] intraday_5813.csv.gz  in=433,453,070 out=113,089,395 elapsed=196.6s

  [16902/21087] intraday_5814.csv.gz  in=433,467,809 out=113,089,395 elapsed=196.6s

  [16903/21087] intraday_5815.csv.gz  in=433,480,494 out=113,089,395 elapsed=196.6s

  [16904/21087] intraday_5816.csv.gz  in=433,491,912 out=113,089,395 elapsed=196.6s

  [16905/21087] intraday_5817.csv.gz  in=433,505,710 out=113,089,395 elapsed=196.6s

  [16906/21087] intraday_5818.csv.gz  in=433,516,627 out=113,089,395 elapsed=196.6s

  [16907/21087] intraday_5820.csv.gz  in=433,524,073 out=113,089,395 elapsed=196.6s

  [16908/21087] intraday_5819.csv.gz  in=433,538,534 out=113,089,395 elapsed=196.6s

  [16909/21087] intraday_5821.csv.gz  in=433,547,667 out=113,089,395 elapsed=196.6s

  [16910/21087] intraday_5822.csv.gz  in=433,557,937 out=113,089,395 elapsed=196.6s

  [16911/21087] intraday_5826.csv.gz  in=433,568,676 out=113,089,395 elapsed=196.7s

  [16912/21087] intraday_5823.csv.gz  in=433,584,712 out=113,089,395 elapsed=196.7s

  [16913/21087] intraday_5825.csv.gz  in=433,596,373 out=113,089,395 elapsed=196.7s

  [16914/21087] intraday_5824.csv.gz  in=433,609,781 out=113,089,395 elapsed=196.7s

  [16915/21087] intraday_5827.csv.gz  in=433,623,256 out=113,089,395 elapsed=196.7s

  [16916/21087] intraday_5830.csv.gz  in=433,634,848 out=113,089,395 elapsed=196.7s

  [16917/21087] intraday_5828.csv.gz  in=433,650,642 out=113,089,395 elapsed=196.7s

  [16918/21087] intraday_5829.csv.gz  in=433,664,739 out=113,089,395 elapsed=196.7s

  [16919/21087] intraday_5831.csv.gz  in=433,678,092 out=113,089,395 elapsed=196.7s

  [16920/21087] intraday_5832.csv.gz  in=433,691,563 out=113,089,395 elapsed=196.7s

  [16921/21087] intraday_5833.csv.gz  in=433,706,039 out=113,089,395 elapsed=196.8s

  [16922/21087] intraday_5835.csv.gz  in=433,718,155 out=113,089,395 elapsed=196.8s

  [16923/21087] intraday_5834.csv.gz  in=433,731,838 out=113,089,395 elapsed=196.8s

  [16924/21087] intraday_5836.csv.gz  in=433,743,811 out=113,089,395 elapsed=196.8s

  [16925/21087] intraday_5837.csv.gz  in=433,753,859 out=113,089,395 elapsed=196.8s

  [16926/21087] intraday_5838.csv.gz  in=433,770,414 out=113,089,395 elapsed=196.8s

  [16927/21087] intraday_5839.csv.gz  in=433,784,409 out=113,089,395 elapsed=196.8s

  [16928/21087] intraday_5840.csv.gz  in=433,797,653 out=113,089,395 elapsed=196.8s

  [16929/21087] intraday_5842.csv.gz  in=433,808,995 out=113,089,395 elapsed=196.8s

  [16930/21087] intraday_5841.csv.gz  in=433,826,928 out=113,089,395 elapsed=196.8s

  [16931/21087] intraday_5843.csv.gz  in=433,839,314 out=113,089,395 elapsed=196.8s

  [16932/21087] intraday_5844.csv.gz  in=433,852,581 out=113,089,395 elapsed=196.8s

  [16933/21087] intraday_5845.csv.gz  in=433,865,092 out=113,089,395 elapsed=196.9s

  [16934/21087] intraday_5846.csv.gz  in=433,877,248 out=113,089,395 elapsed=196.9s

  [16935/21087] intraday_5847.csv.gz  in=433,890,120 out=113,089,395 elapsed=196.9s

  [16936/21087] intraday_5848.csv.gz  in=433,901,175 out=113,089,395 elapsed=196.9s

  [16937/21087] intraday_5849.csv.gz  in=433,912,915 out=113,089,395 elapsed=196.9s

  [16938/21087] intraday_5850.csv.gz  in=433,924,827 out=113,089,395 elapsed=196.9s

  [16939/21087] intraday_5851.csv.gz  in=433,937,965 out=113,089,395 elapsed=196.9s

  [16940/21087] intraday_5853.csv.gz  in=433,953,114 out=113,089,395 elapsed=196.9s

  [16941/21087] intraday_5852.csv.gz  in=433,967,089 out=113,089,395 elapsed=196.9s

  [16942/21087] intraday_5854.csv.gz  in=433,979,669 out=113,089,395 elapsed=196.9s

  [16943/21087] intraday_5855.csv.gz  in=433,991,789 out=113,089,395 elapsed=196.9s

  [16944/21087] intraday_5856.csv.gz  in=434,004,185 out=113,089,395 elapsed=196.9s

  [16945/21087] intraday_5858.csv.gz  in=434,014,710 out=113,089,395 elapsed=197.0s

  [16946/21087] intraday_5857.csv.gz  in=434,028,798 out=113,089,395 elapsed=197.0s

  [16947/21087] intraday_5859.csv.gz  in=434,040,955 out=113,089,395 elapsed=197.0s

  [16948/21087] intraday_5860.csv.gz  in=434,052,524 out=113,089,395 elapsed=197.0s

  [16949/21087] intraday_5861.csv.gz  in=434,063,277 out=113,089,395 elapsed=197.0s

  [16950/21087] intraday_5862.csv.gz  in=434,074,325 out=113,089,395 elapsed=197.0s

  [16951/21087] intraday_5863.csv.gz  in=434,087,072 out=113,089,395 elapsed=197.0s

  [16952/21087] intraday_5864.csv.gz  in=434,098,970 out=113,089,395 elapsed=197.0s

  [16953/21087] intraday_5865.csv.gz  in=434,111,729 out=113,089,395 elapsed=197.0s

  [16954/21087] intraday_5866.csv.gz  in=434,125,192 out=113,089,395 elapsed=197.0s

  [16955/21087] intraday_5867.csv.gz  in=434,137,680 out=113,089,395 elapsed=197.0s

  [16956/21087] intraday_5868.csv.gz  in=434,149,901 out=113,089,395 elapsed=197.0s

  [16957/21087] intraday_5869.csv.gz  in=434,160,597 out=113,089,395 elapsed=197.0s

  [16958/21087] intraday_5870.csv.gz  in=434,172,150 out=113,089,395 elapsed=197.0s

  [16959/21087] intraday_5871.csv.gz  in=434,183,672 out=113,089,395 elapsed=197.1s

  [16960/21087] intraday_5872.csv.gz  in=434,194,693 out=113,089,395 elapsed=197.1s

  [16961/21087] intraday_5873.csv.gz  in=434,205,708 out=113,089,395 elapsed=197.1s

  [16962/21087] intraday_5874.csv.gz  in=434,220,197 out=113,089,395 elapsed=197.1s

  [16963/21087] intraday_5875.csv.gz  in=434,230,640 out=113,089,395 elapsed=197.1s

  [16964/21087] intraday_5876.csv.gz  in=434,241,397 out=113,089,395 elapsed=197.1s

  [16965/21087] intraday_5877.csv.gz  in=434,255,849 out=113,089,395 elapsed=197.1s

  [16966/21087] intraday_5878.csv.gz  in=434,268,732 out=113,089,395 elapsed=197.1s

  [16967/21087] intraday_5879.csv.gz  in=434,281,720 out=113,089,395 elapsed=197.1s

  [16968/21087] intraday_5880.csv.gz  in=434,293,481 out=113,089,395 elapsed=197.1s

  [16969/21087] intraday_5881.csv.gz  in=434,306,138 out=113,089,395 elapsed=197.1s

  [16970/21087] intraday_5882.csv.gz  in=434,318,718 out=113,089,395 elapsed=197.1s

  [16971/21087] intraday_5883.csv.gz  in=434,332,481 out=113,089,395 elapsed=197.1s

  [16972/21087] intraday_5884.csv.gz  in=434,343,723 out=113,089,395 elapsed=197.1s

  [16973/21087] intraday_5885.csv.gz  in=434,354,067 out=113,089,395 elapsed=197.2s

  [16974/21087] intraday_5886.csv.gz  in=434,365,424 out=113,089,395 elapsed=197.2s

  [16975/21087] intraday_5887.csv.gz  in=434,380,992 out=113,089,395 elapsed=197.2s

  [16976/21087] intraday_5888.csv.gz  in=434,394,356 out=113,089,395 elapsed=197.2s

  [16977/21087] intraday_5889.csv.gz  in=434,407,803 out=113,089,395 elapsed=197.2s

  [16978/21087] intraday_5890.csv.gz  in=434,420,289 out=113,089,395 elapsed=197.2s

  [16979/21087] intraday_5891.csv.gz  in=434,448,804 out=113,089,395 elapsed=197.2s

  [16980/21087] intraday_5892.csv.gz  in=434,468,532 out=113,089,395 elapsed=197.2s

  [16981/21087] intraday_5893.csv.gz  in=434,480,135 out=113,089,395 elapsed=197.2s

  [16982/21087] intraday_5894.csv.gz  in=434,492,012 out=113,089,395 elapsed=197.2s

  [16983/21087] intraday_5895.csv.gz  in=434,505,587 out=113,089,395 elapsed=197.2s

  [16984/21087] intraday_5898.csv.gz  in=434,516,032 out=113,089,395 elapsed=197.3s

  [16985/21087] intraday_5897.csv.gz  in=434,527,734 out=113,089,395 elapsed=197.3s

  [16986/21087] intraday_5896.csv.gz  in=434,540,479 out=113,089,395 elapsed=197.3s

  [16987/21087] intraday_5899.csv.gz  in=434,554,203 out=113,089,395 elapsed=197.3s

  [16988/21087] intraday_5902.csv.gz  in=434,563,546 out=113,089,395 elapsed=197.3s

  [16989/21087] intraday_5900.csv.gz  in=434,574,602 out=113,089,395 elapsed=197.3s

  [16990/21087] intraday_5901.csv.gz  in=434,597,029 out=113,089,395 elapsed=197.3s

  [16991/21087] intraday_5903.csv.gz  in=434,608,818 out=113,089,395 elapsed=197.3s

  [16992/21087] intraday_5904.csv.gz  in=434,621,336 out=113,089,395 elapsed=197.3s

  [16993/21087] intraday_5905.csv.gz  in=434,636,098 out=113,089,395 elapsed=197.3s

  [16994/21087] intraday_5906.csv.gz  in=434,650,865 out=113,089,395 elapsed=197.3s

  [16995/21087] intraday_5907.csv.gz  in=434,664,891 out=113,089,395 elapsed=197.3s

  [16996/21087] intraday_5908.csv.gz  in=434,676,312 out=113,089,395 elapsed=197.3s

  [16997/21087] intraday_5909.csv.gz  in=434,688,639 out=113,089,395 elapsed=197.3s

  [16998/21087] intraday_5910.csv.gz  in=434,702,178 out=113,089,395 elapsed=197.4s

  [16999/21087] intraday_5912.csv.gz  in=434,715,294 out=113,089,395 elapsed=197.4s

  [17000/21087] intraday_5911.csv.gz  in=434,731,712 out=113,089,395 elapsed=197.4s

  [17001/21087] intraday_5913.csv.gz  in=434,744,870 out=113,089,395 elapsed=197.4s

  [17002/21087] intraday_5914.csv.gz  in=434,758,059 out=113,089,395 elapsed=197.4s

  [17003/21087] intraday_5916.csv.gz  in=434,771,560 out=113,089,395 elapsed=197.4s

  [17004/21087] intraday_5915.csv.gz  in=434,786,077 out=113,089,395 elapsed=197.4s

  [17005/21087] intraday_5918.csv.gz  in=434,798,529 out=113,089,395 elapsed=197.4s

  [17006/21087] intraday_5917.csv.gz  in=434,813,722 out=113,089,395 elapsed=197.4s

  [17007/21087] intraday_5920.csv.gz  in=434,825,694 out=113,089,395 elapsed=197.4s

  [17008/21087] intraday_5919.csv.gz  in=434,838,638 out=113,089,395 elapsed=197.4s

  [17009/21087] intraday_5922.csv.gz  in=434,850,817 out=113,089,395 elapsed=197.4s

  [17010/21087] intraday_5921.csv.gz  in=434,865,361 out=113,089,395 elapsed=197.4s

  [17011/21087] intraday_5923.csv.gz  in=434,879,575 out=113,089,395 elapsed=197.5s

  [17012/21087] intraday_5924.csv.gz  in=434,892,695 out=113,089,395 elapsed=197.5s

  [17013/21087] intraday_5925.csv.gz  in=434,906,203 out=113,089,395 elapsed=197.5s

  [17014/21087] intraday_5926.csv.gz  in=434,923,398 out=113,089,395 elapsed=197.5s

  [17015/21087] intraday_5927.csv.gz  in=434,938,034 out=113,089,395 elapsed=197.5s

  [17016/21087] intraday_5929.csv.gz  in=434,950,650 out=113,089,395 elapsed=197.5s

  [17017/21087] intraday_5928.csv.gz  in=434,964,284 out=113,089,395 elapsed=197.5s

  [17018/21087] intraday_5930.csv.gz  in=434,977,888 out=113,089,395 elapsed=197.5s

  [17019/21087] intraday_5931.csv.gz  in=434,995,307 out=113,089,395 elapsed=197.5s

  [17020/21087] intraday_5932.csv.gz  in=435,007,084 out=113,089,395 elapsed=197.5s

  [17021/21087] intraday_5933.csv.gz  in=435,019,195 out=113,089,395 elapsed=197.5s

  [17022/21087] intraday_5934.csv.gz  in=435,032,580 out=113,089,395 elapsed=197.5s

  [17023/21087] intraday_5935.csv.gz  in=435,044,691 out=113,089,395 elapsed=197.6s

  [17024/21087] intraday_5936.csv.gz  in=435,058,638 out=113,089,395 elapsed=197.6s

  [17025/21087] intraday_5937.csv.gz  in=435,073,084 out=113,089,395 elapsed=197.6s

  [17026/21087] intraday_5938.csv.gz  in=435,087,453 out=113,089,395 elapsed=197.6s

  [17027/21087] intraday_5939.csv.gz  in=435,102,401 out=113,089,395 elapsed=197.6s

  [17028/21087] intraday_5940.csv.gz  in=435,116,768 out=113,089,395 elapsed=197.6s

  [17029/21087] intraday_5941.csv.gz  in=435,128,531 out=113,089,395 elapsed=197.6s

  [17030/21087] intraday_5942.csv.gz  in=435,141,404 out=113,089,395 elapsed=197.6s

  [17031/21087] intraday_5944.csv.gz  in=435,153,325 out=113,089,395 elapsed=197.6s

  [17032/21087] intraday_5943.csv.gz  in=435,165,233 out=113,089,395 elapsed=197.6s

  [17033/21087] intraday_5945.csv.gz  in=435,177,282 out=113,089,395 elapsed=197.6s

  [17034/21087] intraday_5946.csv.gz  in=435,189,795 out=113,089,395 elapsed=197.7s

  [17035/21087] intraday_5947.csv.gz  in=435,203,300 out=113,089,395 elapsed=197.7s

  [17036/21087] intraday_5948.csv.gz  in=435,219,096 out=113,089,395 elapsed=197.7s

  [17037/21087] intraday_5949.csv.gz  in=435,230,477 out=113,089,395 elapsed=197.7s

  [17038/21087] intraday_5950.csv.gz  in=435,242,263 out=113,089,395 elapsed=197.7s

  [17039/21087] intraday_5951.csv.gz  in=435,256,164 out=113,089,395 elapsed=197.7s

  [17040/21087] intraday_5952.csv.gz  in=435,268,668 out=113,089,395 elapsed=197.7s

  [17041/21087] intraday_5953.csv.gz  in=435,281,022 out=113,089,395 elapsed=197.7s

  [17042/21087] intraday_5954.csv.gz  in=435,298,057 out=113,089,395 elapsed=197.7s

  [17043/21087] intraday_5955.csv.gz  in=435,311,770 out=113,089,395 elapsed=197.7s

  [17044/21087] intraday_5956.csv.gz  in=435,325,741 out=113,089,395 elapsed=197.7s

  [17045/21087] intraday_5957.csv.gz  in=435,338,188 out=113,089,395 elapsed=197.7s

  [17046/21087] intraday_5958.csv.gz  in=435,350,200 out=113,089,395 elapsed=197.8s

  [17047/21087] intraday_5959.csv.gz  in=435,364,652 out=113,089,395 elapsed=197.8s

  [17048/21087] intraday_5960.csv.gz  in=435,375,595 out=113,089,395 elapsed=197.8s

  [17049/21087] intraday_5961.csv.gz  in=435,389,606 out=113,089,395 elapsed=197.8s

  [17050/21087] intraday_5962.csv.gz  in=435,398,474 out=113,089,395 elapsed=197.8s

  [17051/21087] intraday_5963.csv.gz  in=435,406,911 out=113,089,395 elapsed=197.8s

  [17052/21087] intraday_5964.csv.gz  in=435,417,725 out=113,089,395 elapsed=197.8s

  [17053/21087] intraday_5965.csv.gz  in=435,433,062 out=113,089,395 elapsed=197.8s

  [17054/21087] intraday_5966.csv.gz  in=435,451,714 out=113,089,395 elapsed=197.8s

  [17055/21087] intraday_5967.csv.gz  in=435,465,233 out=113,089,395 elapsed=197.8s

  [17056/21087] intraday_5968.csv.gz  in=435,475,343 out=113,089,395 elapsed=197.8s

  [17057/21087] intraday_5969.csv.gz  in=435,488,516 out=113,089,395 elapsed=197.8s

  [17058/21087] intraday_5970.csv.gz  in=435,502,728 out=113,089,395 elapsed=197.8s

  [17059/21087] intraday_5971.csv.gz  in=435,517,278 out=113,089,395 elapsed=197.9s

  [17060/21087] intraday_5972.csv.gz  in=435,527,566 out=113,089,395 elapsed=197.9s

  [17061/21087] intraday_5973.csv.gz  in=435,540,506 out=113,089,395 elapsed=197.9s

  [17062/21087] intraday_5974.csv.gz  in=435,554,963 out=113,089,395 elapsed=197.9s

  [17063/21087] intraday_5975.csv.gz  in=435,569,039 out=113,089,395 elapsed=197.9s

  [17064/21087] intraday_5976.csv.gz  in=435,581,642 out=113,089,395 elapsed=197.9s

  [17065/21087] intraday_5977.csv.gz  in=435,596,599 out=113,089,395 elapsed=197.9s

  [17066/21087] intraday_5978.csv.gz  in=435,608,700 out=113,089,395 elapsed=197.9s

  [17067/21087] intraday_5979.csv.gz  in=435,619,595 out=113,089,395 elapsed=197.9s

  [17068/21087] intraday_5980.csv.gz  in=435,628,531 out=113,089,395 elapsed=197.9s

  [17069/21087] intraday_5981.csv.gz  in=435,642,586 out=113,089,395 elapsed=197.9s

  [17070/21087] intraday_5982.csv.gz  in=435,655,367 out=113,089,395 elapsed=197.9s

  [17071/21087] intraday_5983.csv.gz  in=435,665,454 out=113,089,395 elapsed=197.9s

  [17072/21087] intraday_5984.csv.gz  in=435,684,134 out=113,089,395 elapsed=198.0s

  [17073/21087] intraday_5985.csv.gz  in=435,696,971 out=113,089,395 elapsed=198.0s

  [17074/21087] intraday_5986.csv.gz  in=435,710,304 out=113,089,395 elapsed=198.0s

  [17075/21087] intraday_5987.csv.gz  in=435,726,171 out=113,089,395 elapsed=198.0s

  [17076/21087] intraday_5989.csv.gz  in=435,738,163 out=113,089,395 elapsed=198.0s

  [17077/21087] intraday_5988.csv.gz  in=435,751,091 out=113,089,395 elapsed=198.0s

  [17078/21087] intraday_5990.csv.gz  in=435,762,732 out=113,089,395 elapsed=198.0s

  [17079/21087] intraday_5991.csv.gz  in=435,773,603 out=113,089,395 elapsed=198.0s

  [17080/21087] intraday_5992.csv.gz  in=435,785,898 out=113,089,395 elapsed=198.0s

  [17081/21087] intraday_5993.csv.gz  in=435,797,919 out=113,089,395 elapsed=198.0s

  [17082/21087] intraday_5994.csv.gz  in=435,809,684 out=113,089,395 elapsed=198.0s

  [17083/21087] intraday_5997.csv.gz  in=435,820,606 out=113,089,395 elapsed=198.0s

  [17084/21087] intraday_5995.csv.gz  in=435,836,439 out=113,089,395 elapsed=198.0s

  [17085/21087] intraday_5996.csv.gz  in=435,848,381 out=113,089,395 elapsed=198.1s

  [17086/21087] intraday_5998.csv.gz  in=435,860,796 out=113,089,395 elapsed=198.1s

  [17087/21087] intraday_5999.csv.gz  in=435,873,474 out=113,089,395 elapsed=198.1s

  [17088/21087] intraday_6000.csv.gz  in=435,884,162 out=113,089,395 elapsed=198.1s

  [17089/21087] intraday_6001.csv.gz  in=435,907,512 out=113,089,395 elapsed=198.1s

  [17090/21087] intraday_6002.csv.gz  in=435,916,603 out=113,089,395 elapsed=198.1s

  [17091/21087] intraday_6003.csv.gz  in=435,928,431 out=113,089,395 elapsed=198.1s

  [17092/21087] intraday_6004.csv.gz  in=435,938,285 out=113,089,395 elapsed=198.1s

  [17093/21087] intraday_6005.csv.gz  in=435,949,524 out=113,089,395 elapsed=198.1s

  [17094/21087] intraday_6006.csv.gz  in=435,962,557 out=113,089,395 elapsed=198.1s

  [17095/21087] intraday_6007.csv.gz  in=435,974,386 out=113,089,395 elapsed=198.1s

  [17096/21087] intraday_6008.csv.gz  in=435,988,230 out=113,089,395 elapsed=198.1s

  [17097/21087] intraday_6009.csv.gz  in=436,007,468 out=113,089,395 elapsed=198.2s

  [17098/21087] intraday_6010.csv.gz  in=436,018,062 out=113,089,395 elapsed=198.2s

  [17099/21087] intraday_6011.csv.gz  in=436,030,192 out=113,089,395 elapsed=198.2s

  [17100/21087] intraday_6012.csv.gz  in=436,043,621 out=113,089,395 elapsed=198.2s

  [17101/21087] intraday_6013.csv.gz  in=436,056,823 out=113,089,395 elapsed=198.2s

  [17102/21087] intraday_6014.csv.gz  in=436,069,494 out=113,089,395 elapsed=198.2s

  [17103/21087] intraday_6015.csv.gz  in=436,081,080 out=113,089,395 elapsed=198.2s

  [17104/21087] intraday_6016.csv.gz  in=436,093,898 out=113,089,395 elapsed=198.2s

  [17105/21087] intraday_6017.csv.gz  in=436,106,317 out=113,089,395 elapsed=198.2s

  [17106/21087] intraday_6018.csv.gz  in=436,117,881 out=113,089,395 elapsed=198.2s

  [17107/21087] intraday_6019.csv.gz  in=436,130,607 out=113,089,395 elapsed=198.2s

  [17108/21087] intraday_6020.csv.gz  in=436,143,204 out=113,089,395 elapsed=198.2s

  [17109/21087] intraday_6021.csv.gz  in=436,155,498 out=113,089,395 elapsed=198.2s

  [17110/21087] intraday_6022.csv.gz  in=436,168,665 out=113,089,395 elapsed=198.3s

  [17111/21087] intraday_6023.csv.gz  in=436,194,534 out=113,089,395 elapsed=198.3s

  [17112/21087] intraday_6025.csv.gz  in=436,206,294 out=113,089,395 elapsed=198.3s

  [17113/21087] intraday_6024.csv.gz  in=436,218,730 out=113,089,395 elapsed=198.3s

  [17114/21087] intraday_6026.csv.gz  in=436,231,777 out=113,089,395 elapsed=198.3s

  [17115/21087] intraday_6027.csv.gz  in=436,244,345 out=113,089,395 elapsed=198.3s

  [17116/21087] intraday_6028.csv.gz  in=436,253,798 out=113,089,395 elapsed=198.3s

  [17117/21087] intraday_6030.csv.gz  in=436,269,857 out=113,089,395 elapsed=198.3s

  [17118/21087] intraday_6029.csv.gz  in=436,284,342 out=113,089,395 elapsed=198.3s

  [17119/21087] intraday_6031.csv.gz  in=436,294,217 out=113,089,395 elapsed=198.3s

  [17120/21087] intraday_6032.csv.gz  in=436,306,789 out=113,089,395 elapsed=198.3s

  [17121/21087] intraday_6034.csv.gz  in=436,317,437 out=113,089,395 elapsed=198.4s

  [17122/21087] intraday_6033.csv.gz  in=436,329,834 out=113,089,395 elapsed=198.4s

  [17123/21087] intraday_6035.csv.gz  in=436,341,648 out=113,089,395 elapsed=198.4s

  [17124/21087] intraday_6036.csv.gz  in=436,352,735 out=113,089,395 elapsed=198.4s

  [17125/21087] intraday_6037.csv.gz  in=436,366,358 out=113,089,395 elapsed=198.4s

  [17126/21087] intraday_6038.csv.gz  in=436,378,243 out=113,089,395 elapsed=198.4s

  [17127/21087] intraday_6039.csv.gz  in=436,391,321 out=113,089,395 elapsed=198.4s

  [17128/21087] intraday_6040.csv.gz  in=436,400,523 out=113,089,395 elapsed=198.4s

  [17129/21087] intraday_6041.csv.gz  in=436,412,958 out=113,089,395 elapsed=198.4s

  [17130/21087] intraday_6043.csv.gz  in=436,423,314 out=113,089,395 elapsed=198.4s

  [17131/21087] intraday_6042.csv.gz  in=436,435,247 out=113,089,395 elapsed=198.4s

  [17132/21087] intraday_6044.csv.gz  in=436,447,069 out=113,089,395 elapsed=198.4s

  [17133/21087] intraday_6045.csv.gz  in=436,456,160 out=113,089,395 elapsed=198.4s

  [17134/21087] intraday_6046.csv.gz  in=436,466,713 out=113,089,395 elapsed=198.5s

  [17135/21087] intraday_6047.csv.gz  in=436,480,808 out=113,089,395 elapsed=198.5s

  [17136/21087] intraday_6048.csv.gz  in=436,498,393 out=113,089,395 elapsed=198.5s

  [17137/21087] intraday_6049.csv.gz  in=436,509,899 out=113,089,395 elapsed=198.5s

  [17138/21087] intraday_6050.csv.gz  in=436,522,017 out=113,089,395 elapsed=198.5s

  [17139/21087] intraday_6051.csv.gz  in=436,532,329 out=113,089,395 elapsed=198.5s

  [17140/21087] intraday_6053.csv.gz  in=436,543,591 out=113,089,395 elapsed=198.5s

  [17141/21087] intraday_6052.csv.gz  in=436,559,216 out=113,089,395 elapsed=198.5s

  [17142/21087] intraday_6054.csv.gz  in=436,574,997 out=113,089,395 elapsed=198.5s

  [17143/21087] intraday_6055.csv.gz  in=436,586,760 out=113,089,395 elapsed=198.5s

  [17144/21087] intraday_6056.csv.gz  in=436,599,462 out=113,089,395 elapsed=198.5s

  [17145/21087] intraday_6057.csv.gz  in=436,612,647 out=113,089,395 elapsed=198.5s

  [17146/21087] intraday_6059.csv.gz  in=436,624,699 out=113,089,395 elapsed=198.6s

  [17147/21087] intraday_6058.csv.gz  in=436,645,614 out=113,089,395 elapsed=198.6s

  [17148/21087] intraday_6060.csv.gz  in=436,658,341 out=113,089,395 elapsed=198.6s

  [17149/21087] intraday_6061.csv.gz  in=436,671,502 out=113,089,395 elapsed=198.6s

  [17150/21087] intraday_6062.csv.gz  in=436,683,167 out=113,089,395 elapsed=198.6s

  [17151/21087] intraday_6063.csv.gz  in=436,696,565 out=113,089,395 elapsed=198.6s

  [17152/21087] intraday_6064.csv.gz  in=436,709,339 out=113,089,395 elapsed=198.6s

  [17153/21087] intraday_6065.csv.gz  in=436,722,136 out=113,089,395 elapsed=198.6s

  [17154/21087] intraday_6066.csv.gz  in=436,737,187 out=113,089,395 elapsed=198.6s

  [17155/21087] intraday_6068.csv.gz  in=436,747,574 out=113,089,395 elapsed=198.6s

  [17156/21087] intraday_6069.csv.gz  in=436,759,634 out=113,089,395 elapsed=198.6s

  [17157/21087] intraday_6067.csv.gz  in=436,775,456 out=113,089,395 elapsed=198.6s

  [17158/21087] intraday_6071.csv.gz  in=436,785,400 out=113,089,395 elapsed=198.7s

  [17159/21087] intraday_6070.csv.gz  in=436,803,793 out=113,089,395 elapsed=198.7s

  [17160/21087] intraday_6072.csv.gz  in=436,814,926 out=113,089,395 elapsed=198.7s

  [17161/21087] intraday_6073.csv.gz  in=436,830,467 out=113,089,395 elapsed=198.7s

  [17162/21087] intraday_6074.csv.gz  in=436,843,843 out=113,089,395 elapsed=198.7s

  [17163/21087] intraday_6075.csv.gz  in=436,857,175 out=113,089,395 elapsed=198.7s

  [17164/21087] intraday_6076.csv.gz  in=436,869,785 out=113,089,395 elapsed=198.7s

  [17165/21087] intraday_6077.csv.gz  in=436,881,945 out=113,089,395 elapsed=198.7s

  [17166/21087] intraday_6078.csv.gz  in=436,894,209 out=113,089,395 elapsed=198.7s

  [17167/21087] intraday_6079.csv.gz  in=436,908,925 out=113,089,395 elapsed=198.7s

  [17168/21087] intraday_6081.csv.gz  in=436,922,952 out=113,089,395 elapsed=198.7s

  [17169/21087] intraday_6080.csv.gz  in=436,934,648 out=113,089,395 elapsed=198.7s

  [17170/21087] intraday_6082.csv.gz  in=436,950,571 out=113,089,395 elapsed=198.7s

  [17171/21087] intraday_6083.csv.gz  in=436,963,187 out=113,089,395 elapsed=198.7s

  [17172/21087] intraday_6085.csv.gz  in=436,974,567 out=113,089,395 elapsed=198.8s

  [17173/21087] intraday_6084.csv.gz  in=436,985,629 out=113,089,395 elapsed=198.8s

  [17174/21087] intraday_6086.csv.gz  in=436,999,088 out=113,089,395 elapsed=198.8s

  [17175/21087] intraday_6087.csv.gz  in=437,010,218 out=113,089,395 elapsed=198.8s

  [17176/21087] intraday_6088.csv.gz  in=437,023,642 out=113,089,395 elapsed=198.8s

  [17177/21087] intraday_6089.csv.gz  in=437,041,647 out=113,089,395 elapsed=198.8s

  [17178/21087] intraday_6090.csv.gz  in=437,057,389 out=113,089,395 elapsed=198.8s

  [17179/21087] intraday_6091.csv.gz  in=437,069,929 out=113,089,395 elapsed=198.8s

  [17180/21087] intraday_6092.csv.gz  in=437,081,463 out=113,089,395 elapsed=198.8s

  [17181/21087] intraday_6093.csv.gz  in=437,093,557 out=113,089,395 elapsed=198.8s

  [17182/21087] intraday_6094.csv.gz  in=437,105,188 out=113,089,395 elapsed=198.8s

  [17183/21087] intraday_6095.csv.gz  in=437,117,514 out=113,089,395 elapsed=198.8s

  [17184/21087] intraday_6096.csv.gz  in=437,129,664 out=113,089,395 elapsed=198.8s

  [17185/21087] intraday_6097.csv.gz  in=437,148,449 out=113,089,395 elapsed=198.9s

  [17186/21087] intraday_6098.csv.gz  in=437,162,434 out=113,089,395 elapsed=198.9s

  [17187/21087] intraday_6099.csv.gz  in=437,175,394 out=113,089,395 elapsed=198.9s

  [17188/21087] intraday_6100.csv.gz  in=437,187,592 out=113,089,395 elapsed=198.9s

  [17189/21087] intraday_6101.csv.gz  in=437,199,390 out=113,089,395 elapsed=198.9s

  [17190/21087] intraday_6104.csv.gz  in=437,213,984 out=113,089,395 elapsed=198.9s

  [17191/21087] intraday_6103.csv.gz  in=437,225,021 out=113,089,395 elapsed=198.9s

  [17192/21087] intraday_6102.csv.gz  in=437,238,407 out=113,089,395 elapsed=198.9s

  [17193/21087] intraday_6105.csv.gz  in=437,246,740 out=113,089,395 elapsed=198.9s

  [17194/21087] intraday_6108.csv.gz  in=437,246,818 out=113,089,395 elapsed=198.9s

  [17195/21087] intraday_6109.csv.gz  in=437,246,838 out=113,089,395 elapsed=198.9s

  [17196/21087] intraday_6106.csv.gz  in=437,256,072 out=113,089,395 elapsed=198.9s

  [17197/21087] intraday_6107.csv.gz  in=437,264,980 out=113,089,395 elapsed=198.9s

  [17198/21087] intraday_6110.csv.gz  in=437,264,997 out=113,089,395 elapsed=198.9s

  [17199/21087] intraday_6111.csv.gz  in=437,265,012 out=113,089,395 elapsed=199.0s

  [17200/21087] intraday_6112.csv.gz  in=437,268,194 out=113,089,395 elapsed=199.0s

  [17201/21087] intraday_6113.csv.gz  in=437,271,824 out=113,089,395 elapsed=199.0s

  [17202/21087] intraday_6114.csv.gz  in=437,284,163 out=113,089,395 elapsed=199.0s

  [17203/21087] intraday_6115.csv.gz  in=437,289,655 out=113,089,395 elapsed=199.0s

  [17204/21087] intraday_6116.csv.gz  in=437,291,002 out=113,089,395 elapsed=199.0s

  [17205/21087] intraday_6117.csv.gz  in=437,291,941 out=113,089,395 elapsed=199.0s

  [17206/21087] intraday_6118.csv.gz  in=437,293,210 out=113,089,395 elapsed=199.0s

  [17207/21087] intraday_6120.csv.gz  in=437,294,565 out=113,089,395 elapsed=199.0s

  [17208/21087] intraday_6119.csv.gz  in=437,302,657 out=113,089,395 elapsed=199.0s

  [17209/21087] intraday_6121.csv.gz  in=437,302,978 out=113,089,395 elapsed=199.0s

  [17210/21087] intraday_6122.csv.gz  in=437,303,019 out=113,089,395 elapsed=199.0s

  [17211/21087] intraday_6124.csv.gz  in=437,303,040 out=113,089,395 elapsed=199.0s

  [17212/21087] intraday_6123.csv.gz  in=437,305,388 out=113,089,395 elapsed=199.0s

  [17213/21087] intraday_6126.csv.gz  in=437,305,502 out=113,089,395 elapsed=199.1s

  [17214/21087] intraday_6125.csv.gz  in=437,306,052 out=113,089,395 elapsed=199.1s

  [17215/21087] intraday_6127.csv.gz  in=437,315,281 out=113,089,395 elapsed=199.1s

  [17216/21087] intraday_6129.csv.gz  in=437,328,098 out=113,089,395 elapsed=199.1s

  [17217/21087] intraday_6130.csv.gz  in=437,342,439 out=113,089,395 elapsed=199.1s

  [17218/21087] intraday_6128.csv.gz  in=437,359,073 out=113,089,395 elapsed=199.1s

  [17219/21087] intraday_6131.csv.gz  in=437,370,498 out=113,089,395 elapsed=199.1s

  [17220/21087] intraday_6132.csv.gz  in=437,383,528 out=113,089,395 elapsed=199.1s

  [17221/21087] intraday_6134.csv.gz  in=437,400,467 out=113,089,395 elapsed=199.1s

  [17222/21087] intraday_6135.csv.gz  in=437,411,785 out=113,089,395 elapsed=199.1s

  [17223/21087] intraday_6133.csv.gz  in=437,426,970 out=113,089,395 elapsed=199.1s

  [17224/21087] intraday_6136.csv.gz  in=437,441,042 out=113,089,395 elapsed=199.2s

  [17225/21087] intraday_6137.csv.gz  in=437,456,983 out=113,089,395 elapsed=199.2s

  [17226/21087] intraday_6138.csv.gz  in=437,471,841 out=113,089,395 elapsed=199.2s

  [17227/21087] intraday_6139.csv.gz  in=437,485,245 out=113,089,395 elapsed=199.2s

  [17228/21087] intraday_6142.csv.gz  in=437,495,329 out=113,089,395 elapsed=199.2s

  [17229/21087] intraday_6143.csv.gz  in=437,504,286 out=113,089,395 elapsed=199.2s

  [17230/21087] intraday_6140.csv.gz  in=437,517,124 out=113,089,395 elapsed=199.2s

  [17231/21087] intraday_6141.csv.gz  in=437,529,626 out=113,089,395 elapsed=199.2s

  [17232/21087] intraday_6144.csv.gz  in=437,544,070 out=113,089,395 elapsed=199.2s

  [17233/21087] intraday_6145.csv.gz  in=437,558,094 out=113,089,395 elapsed=199.2s

  [17234/21087] intraday_6146.csv.gz  in=437,569,179 out=113,089,395 elapsed=199.2s

  [17235/21087] intraday_6147.csv.gz  in=437,581,501 out=113,089,395 elapsed=199.2s

  [17236/21087] intraday_6151.csv.gz  in=437,594,828 out=113,089,395 elapsed=199.3s

  [17237/21087] intraday_6149.csv.gz  in=437,608,296 out=113,089,395 elapsed=199.3s

  [17238/21087] intraday_6150.csv.gz  in=437,621,917 out=113,089,395 elapsed=199.3s

  [17239/21087] intraday_6148.csv.gz  in=437,650,324 out=113,089,395 elapsed=199.3s

  [17240/21087] intraday_6152.csv.gz  in=437,663,193 out=113,089,395 elapsed=199.3s

  [17241/21087] intraday_6153.csv.gz  in=437,674,995 out=113,089,395 elapsed=199.3s

  [17242/21087] intraday_6154.csv.gz  in=437,685,817 out=113,089,395 elapsed=199.3s

  [17243/21087] intraday_6155.csv.gz  in=437,698,180 out=113,089,395 elapsed=199.3s

  [17244/21087] intraday_6157.csv.gz  in=437,713,631 out=113,089,395 elapsed=199.3s

  [17245/21087] intraday_6156.csv.gz  in=437,727,823 out=113,089,395 elapsed=199.3s

  [17246/21087] intraday_6159.csv.gz  in=437,739,140 out=113,089,395 elapsed=199.4s

  [17247/21087] intraday_6158.csv.gz  in=437,754,469 out=113,089,395 elapsed=199.4s

  [17248/21087] intraday_6160.csv.gz  in=437,766,254 out=113,089,395 elapsed=199.4s

  [17249/21087] intraday_6161.csv.gz  in=437,779,011 out=113,089,395 elapsed=199.4s

  [17250/21087] intraday_6165.csv.gz  in=437,789,876 out=113,089,395 elapsed=199.4s

  [17251/21087] intraday_6163.csv.gz  in=437,801,249 out=113,089,395 elapsed=199.4s

  [17252/21087] intraday_6164.csv.gz  in=437,814,136 out=113,089,395 elapsed=199.4s

  [17253/21087] intraday_6162.csv.gz  in=437,828,972 out=113,089,395 elapsed=199.4s

  [17254/21087] intraday_6166.csv.gz  in=437,840,810 out=113,089,395 elapsed=199.4s

  [17255/21087] intraday_6167.csv.gz  in=437,851,579 out=113,089,395 elapsed=199.4s

  [17256/21087] intraday_6168.csv.gz  in=437,863,852 out=113,089,395 elapsed=199.4s

  [17257/21087] intraday_6169.csv.gz  in=437,877,055 out=113,089,395 elapsed=199.4s

  [17258/21087] intraday_6170.csv.gz  in=437,889,386 out=113,089,395 elapsed=199.4s

  [17259/21087] intraday_6172.csv.gz  in=437,902,387 out=113,089,395 elapsed=199.5s

  [17260/21087] intraday_6171.csv.gz  in=437,915,898 out=113,089,395 elapsed=199.5s

  [17261/21087] intraday_6173.csv.gz  in=437,927,760 out=113,089,395 elapsed=199.5s

  [17262/21087] intraday_6174.csv.gz  in=437,940,502 out=113,089,395 elapsed=199.5s

  [17263/21087] intraday_6175.csv.gz  in=437,953,184 out=113,089,395 elapsed=199.5s

  [17264/21087] intraday_6176.csv.gz  in=437,963,952 out=113,089,395 elapsed=199.5s

  [17265/21087] intraday_6177.csv.gz  in=437,976,435 out=113,089,395 elapsed=199.5s

  [17266/21087] intraday_6178.csv.gz  in=437,988,349 out=113,089,395 elapsed=199.5s

  [17267/21087] intraday_6179.csv.gz  in=438,001,958 out=113,089,395 elapsed=199.5s

  [17268/21087] intraday_6180.csv.gz  in=438,015,415 out=113,089,395 elapsed=199.5s

  [17269/21087] intraday_6181.csv.gz  in=438,027,195 out=113,089,395 elapsed=199.5s

  [17270/21087] intraday_6182.csv.gz  in=438,041,644 out=113,089,395 elapsed=199.5s

  [17271/21087] intraday_6183.csv.gz  in=438,054,608 out=113,089,395 elapsed=199.6s

  [17272/21087] intraday_6185.csv.gz  in=438,067,894 out=113,089,395 elapsed=199.6s

  [17273/21087] intraday_6184.csv.gz  in=438,080,658 out=113,089,395 elapsed=199.6s

  [17274/21087] intraday_6186.csv.gz  in=438,094,927 out=113,089,395 elapsed=199.6s

  [17275/21087] intraday_6187.csv.gz  in=438,108,740 out=113,089,395 elapsed=199.6s

  [17276/21087] intraday_6188.csv.gz  in=438,121,048 out=113,089,395 elapsed=199.6s

  [17277/21087] intraday_6189.csv.gz  in=438,133,626 out=113,089,395 elapsed=199.6s

  [17278/21087] intraday_6191.csv.gz  in=438,144,146 out=113,089,395 elapsed=199.6s

  [17279/21087] intraday_6190.csv.gz  in=438,156,468 out=113,089,395 elapsed=199.6s

  [17280/21087] intraday_6192.csv.gz  in=438,171,714 out=113,089,395 elapsed=199.6s

  [17281/21087] intraday_6194.csv.gz  in=438,184,358 out=113,089,395 elapsed=199.7s

  [17282/21087] intraday_6193.csv.gz  in=438,199,275 out=113,089,395 elapsed=199.7s

  [17283/21087] intraday_6195.csv.gz  in=438,211,862 out=113,089,395 elapsed=199.7s

  [17284/21087] intraday_6196.csv.gz  in=438,224,524 out=113,089,395 elapsed=199.7s

  [17285/21087] intraday_6197.csv.gz  in=438,234,929 out=113,089,395 elapsed=199.7s

  [17286/21087] intraday_6198.csv.gz  in=438,247,392 out=113,089,395 elapsed=199.7s

  [17287/21087] intraday_6199.csv.gz  in=438,260,284 out=113,089,395 elapsed=199.7s

  [17288/21087] intraday_6200.csv.gz  in=438,274,439 out=113,089,395 elapsed=199.7s

  [17289/21087] intraday_6201.csv.gz  in=438,285,562 out=113,089,395 elapsed=199.7s

  [17290/21087] intraday_6202.csv.gz  in=438,299,055 out=113,089,395 elapsed=199.7s

  [17291/21087] intraday_6203.csv.gz  in=438,309,408 out=113,089,395 elapsed=199.7s

  [17292/21087] intraday_6204.csv.gz  in=438,324,043 out=113,089,395 elapsed=199.7s

  [17293/21087] intraday_6206.csv.gz  in=438,338,693 out=113,089,395 elapsed=199.7s

  [17294/21087] intraday_6205.csv.gz  in=438,349,992 out=113,089,395 elapsed=199.7s

  [17295/21087] intraday_6207.csv.gz  in=438,359,863 out=113,089,395 elapsed=199.7s

  [17296/21087] intraday_6208.csv.gz  in=438,371,395 out=113,089,395 elapsed=199.8s

  [17297/21087] intraday_6209.csv.gz  in=438,383,758 out=113,089,395 elapsed=199.8s

  [17298/21087] intraday_6210.csv.gz  in=438,399,934 out=113,089,395 elapsed=199.8s

  [17299/21087] intraday_6211.csv.gz  in=438,416,578 out=113,089,395 elapsed=199.8s

  [17300/21087] intraday_6212.csv.gz  in=438,429,310 out=113,089,395 elapsed=199.8s

  [17301/21087] intraday_6213.csv.gz  in=438,441,677 out=113,089,395 elapsed=199.8s

  [17302/21087] intraday_6214.csv.gz  in=438,453,612 out=113,089,395 elapsed=199.8s

  [17303/21087] intraday_6215.csv.gz  in=438,467,821 out=113,089,395 elapsed=199.8s

  [17304/21087] intraday_6216.csv.gz  in=438,482,770 out=113,089,395 elapsed=199.8s

  [17305/21087] intraday_6217.csv.gz  in=438,496,983 out=113,089,395 elapsed=199.8s

  [17306/21087] intraday_6218.csv.gz  in=438,509,006 out=113,089,395 elapsed=199.8s

  [17307/21087] intraday_6219.csv.gz  in=438,523,314 out=113,089,395 elapsed=199.9s

  [17308/21087] intraday_6220.csv.gz  in=438,537,010 out=113,089,395 elapsed=199.9s

  [17309/21087] intraday_6222.csv.gz  in=438,549,543 out=113,089,395 elapsed=199.9s

  [17310/21087] intraday_6221.csv.gz  in=438,563,314 out=113,089,395 elapsed=199.9s

  [17311/21087] intraday_6223.csv.gz  in=438,576,419 out=113,089,395 elapsed=199.9s

  [17312/21087] intraday_6225.csv.gz  in=438,589,847 out=113,089,395 elapsed=199.9s

  [17313/21087] intraday_6224.csv.gz  in=438,603,076 out=113,089,395 elapsed=199.9s

  [17314/21087] intraday_6226.csv.gz  in=438,617,139 out=113,089,395 elapsed=199.9s

  [17315/21087] intraday_6227.csv.gz  in=438,628,732 out=113,089,395 elapsed=199.9s

  [17316/21087] intraday_6228.csv.gz  in=438,640,235 out=113,089,395 elapsed=199.9s

  [17317/21087] intraday_6230.csv.gz  in=438,653,923 out=113,089,395 elapsed=199.9s

  [17318/21087] intraday_6229.csv.gz  in=438,671,437 out=113,089,395 elapsed=199.9s

  [17319/21087] intraday_6231.csv.gz  in=438,684,501 out=113,089,395 elapsed=199.9s

  [17320/21087] intraday_6232.csv.gz  in=438,699,175 out=113,089,395 elapsed=200.0s

  [17321/21087] intraday_6233.csv.gz  in=438,713,996 out=113,089,395 elapsed=200.0s

  [17322/21087] intraday_6234.csv.gz  in=438,727,379 out=113,089,395 elapsed=200.0s

  [17323/21087] intraday_6235.csv.gz  in=438,740,945 out=113,089,395 elapsed=200.0s

  [17324/21087] intraday_6236.csv.gz  in=438,755,842 out=113,089,395 elapsed=200.0s

  [17325/21087] intraday_6237.csv.gz  in=438,770,503 out=113,089,395 elapsed=200.0s

  [17326/21087] intraday_6238.csv.gz  in=438,782,138 out=113,089,395 elapsed=200.0s

  [17327/21087] intraday_6239.csv.gz  in=438,797,490 out=113,089,395 elapsed=200.0s

  [17328/21087] intraday_6240.csv.gz  in=438,810,326 out=113,089,395 elapsed=200.0s

  [17329/21087] intraday_6241.csv.gz  in=438,824,487 out=113,089,395 elapsed=200.0s

  [17330/21087] intraday_6242.csv.gz  in=438,839,589 out=113,089,395 elapsed=200.0s

  [17331/21087] intraday_6243.csv.gz  in=438,854,895 out=113,089,395 elapsed=200.0s

  [17332/21087] intraday_6244.csv.gz  in=438,869,168 out=113,089,395 elapsed=200.0s

  [17333/21087] intraday_6245.csv.gz  in=438,883,423 out=113,089,395 elapsed=200.1s

  [17334/21087] intraday_6246.csv.gz  in=438,895,981 out=113,089,395 elapsed=200.1s

  [17335/21087] intraday_6247.csv.gz  in=438,908,412 out=113,089,395 elapsed=200.1s

  [17336/21087] intraday_6248.csv.gz  in=438,919,268 out=113,089,395 elapsed=200.1s

  [17337/21087] intraday_6249.csv.gz  in=438,934,761 out=113,089,395 elapsed=200.1s

  [17338/21087] intraday_6250.csv.gz  in=438,945,867 out=113,089,395 elapsed=200.1s

  [17339/21087] intraday_6251.csv.gz  in=438,959,648 out=113,089,395 elapsed=200.1s

  [17340/21087] intraday_6252.csv.gz  in=438,973,136 out=113,089,395 elapsed=200.1s

  [17341/21087] intraday_6253.csv.gz  in=438,988,800 out=113,089,395 elapsed=200.1s

  [17342/21087] intraday_6254.csv.gz  in=439,000,210 out=113,089,395 elapsed=200.1s

  [17343/21087] intraday_6255.csv.gz  in=439,013,756 out=113,089,395 elapsed=200.1s

  [17344/21087] intraday_6256.csv.gz  in=439,026,770 out=113,089,395 elapsed=200.1s

  [17345/21087] intraday_6258.csv.gz  in=439,041,047 out=113,089,395 elapsed=200.2s

  [17346/21087] intraday_6257.csv.gz  in=439,053,880 out=113,089,395 elapsed=200.2s

  [17347/21087] intraday_6259.csv.gz  in=439,068,883 out=113,089,395 elapsed=200.2s

  [17348/21087] intraday_6260.csv.gz  in=439,083,953 out=113,089,395 elapsed=200.2s

  [17349/21087] intraday_6262.csv.gz  in=439,098,234 out=113,089,395 elapsed=200.2s

  [17350/21087] intraday_6263.csv.gz  in=439,109,563 out=113,089,395 elapsed=200.2s

  [17351/21087] intraday_6261.csv.gz  in=439,123,651 out=113,089,395 elapsed=200.2s

  [17352/21087] intraday_6264.csv.gz  in=439,137,598 out=113,089,395 elapsed=200.2s

  [17353/21087] intraday_6265.csv.gz  in=439,149,974 out=113,089,395 elapsed=200.2s

  [17354/21087] intraday_6266.csv.gz  in=439,163,655 out=113,089,395 elapsed=200.2s

  [17355/21087] intraday_6267.csv.gz  in=439,174,410 out=113,089,395 elapsed=200.2s

  [17356/21087] intraday_6268.csv.gz  in=439,183,734 out=113,089,395 elapsed=200.3s

  [17357/21087] intraday_6269.csv.gz  in=439,195,609 out=113,089,395 elapsed=200.3s

  [17358/21087] intraday_6270.csv.gz  in=439,198,256 out=113,089,395 elapsed=200.3s

  [17359/21087] intraday_6272.csv.gz  in=439,211,747 out=113,089,395 elapsed=200.3s

  [17360/21087] intraday_6271.csv.gz  in=439,227,344 out=113,089,395 elapsed=200.3s

  [17361/21087] intraday_6273.csv.gz  in=439,249,131 out=113,089,395 elapsed=200.3s

  [17362/21087] intraday_6274.csv.gz  in=439,276,760 out=113,089,395 elapsed=200.3s

  [17363/21087] intraday_6275.csv.gz  in=439,289,879 out=113,089,395 elapsed=200.3s

  [17364/21087] intraday_6276.csv.gz  in=439,304,478 out=113,089,395 elapsed=200.3s

  [17365/21087] intraday_6278.csv.gz  in=439,315,293 out=113,089,395 elapsed=200.3s

  [17366/21087] intraday_6277.csv.gz  in=439,332,808 out=113,089,395 elapsed=200.3s

  [17367/21087] intraday_6280.csv.gz  in=439,347,756 out=113,089,395 elapsed=200.3s

  [17368/21087] intraday_6279.csv.gz  in=439,362,684 out=113,089,395 elapsed=200.4s

  [17369/21087] intraday_6281.csv.gz  in=439,379,259 out=113,089,395 elapsed=200.4s

  [17370/21087] intraday_6282.csv.gz  in=439,392,495 out=113,089,395 elapsed=200.4s

  [17371/21087] intraday_6283.csv.gz  in=439,405,022 out=113,089,395 elapsed=200.4s

  [17372/21087] intraday_6284.csv.gz  in=439,418,425 out=113,089,395 elapsed=200.4s

  [17373/21087] intraday_6285.csv.gz  in=439,427,851 out=113,089,395 elapsed=200.4s

  [17374/21087] intraday_6286.csv.gz  in=439,437,329 out=113,089,395 elapsed=200.4s

  [17375/21087] intraday_6287.csv.gz  in=439,451,245 out=113,089,395 elapsed=200.4s

  [17376/21087] intraday_6288.csv.gz  in=439,464,245 out=113,089,395 elapsed=200.4s

  [17377/21087] intraday_6289.csv.gz  in=439,475,313 out=113,089,395 elapsed=200.4s

  [17378/21087] intraday_6290.csv.gz  in=439,489,004 out=113,089,395 elapsed=200.4s

  [17379/21087] intraday_6291.csv.gz  in=439,501,652 out=113,089,395 elapsed=200.4s

  [17380/21087] intraday_6292.csv.gz  in=439,513,731 out=113,089,395 elapsed=200.5s

  [17381/21087] intraday_6293.csv.gz  in=439,527,663 out=113,089,395 elapsed=200.5s

  [17382/21087] intraday_6294.csv.gz  in=439,541,979 out=113,089,395 elapsed=200.5s

  [17383/21087] intraday_6295.csv.gz  in=439,555,057 out=113,089,395 elapsed=200.5s

  [17384/21087] intraday_6296.csv.gz  in=439,567,021 out=113,089,395 elapsed=200.5s

  [17385/21087] intraday_6297.csv.gz  in=439,578,627 out=113,089,395 elapsed=200.5s

  [17386/21087] intraday_6299.csv.gz  in=439,591,525 out=113,089,395 elapsed=200.5s

  [17387/21087] intraday_6298.csv.gz  in=439,605,597 out=113,089,395 elapsed=200.5s

  [17388/21087] intraday_6301.csv.gz  in=439,622,558 out=113,089,395 elapsed=200.5s

  [17389/21087] intraday_6300.csv.gz  in=439,646,540 out=113,089,395 elapsed=200.5s

  [17390/21087] intraday_6303.csv.gz  in=439,656,886 out=113,089,395 elapsed=200.5s

  [17391/21087] intraday_6302.csv.gz  in=439,669,744 out=113,089,395 elapsed=200.5s

  [17392/21087] intraday_6304.csv.gz  in=439,682,574 out=113,089,395 elapsed=200.5s

  [17393/21087] intraday_6307.csv.gz  in=439,694,450 out=113,089,395 elapsed=200.6s

  [17394/21087] intraday_6306.csv.gz  in=439,706,330 out=113,089,395 elapsed=200.6s

  [17395/21087] intraday_6305.csv.gz  in=439,729,630 out=113,089,395 elapsed=200.6s

  [17396/21087] intraday_6308.csv.gz  in=439,740,128 out=113,089,395 elapsed=200.6s

  [17397/21087] intraday_6309.csv.gz  in=439,752,788 out=113,089,395 elapsed=200.6s

  [17398/21087] intraday_6311.csv.gz  in=439,763,468 out=113,089,395 elapsed=200.6s

  [17399/21087] intraday_6310.csv.gz  in=439,785,364 out=113,089,395 elapsed=200.6s

  [17400/21087] intraday_6312.csv.gz  in=439,802,430 out=113,089,395 elapsed=200.6s

  [17401/21087] intraday_6313.csv.gz  in=439,816,638 out=113,089,395 elapsed=200.6s

  [17402/21087] intraday_6314.csv.gz  in=439,827,348 out=113,089,395 elapsed=200.6s

  [17403/21087] intraday_6315.csv.gz  in=439,841,004 out=113,089,395 elapsed=200.6s

  [17404/21087] intraday_6316.csv.gz  in=439,851,462 out=113,089,395 elapsed=200.6s

  [17405/21087] intraday_6317.csv.gz  in=439,866,223 out=113,089,395 elapsed=200.6s

  [17406/21087] intraday_6318.csv.gz  in=439,879,693 out=113,089,395 elapsed=200.7s

  [17407/21087] intraday_6319.csv.gz  in=439,894,109 out=113,089,395 elapsed=200.7s

  [17408/21087] intraday_6320.csv.gz  in=439,915,185 out=113,089,395 elapsed=200.7s

  [17409/21087] intraday_6321.csv.gz  in=439,926,945 out=113,089,395 elapsed=200.7s

  [17410/21087] intraday_6322.csv.gz  in=439,937,325 out=113,089,395 elapsed=200.7s

  [17411/21087] intraday_6323.csv.gz  in=439,951,616 out=113,089,395 elapsed=200.7s

  [17412/21087] intraday_6324.csv.gz  in=439,962,091 out=113,089,395 elapsed=200.7s

  [17413/21087] intraday_6325.csv.gz  in=439,976,546 out=113,089,395 elapsed=200.7s

  [17414/21087] intraday_6326.csv.gz  in=439,989,859 out=113,089,395 elapsed=200.7s

  [17415/21087] intraday_6327.csv.gz  in=440,002,495 out=113,089,395 elapsed=200.7s

  [17416/21087] intraday_6328.csv.gz  in=440,018,066 out=113,089,395 elapsed=200.7s

  [17417/21087] intraday_6329.csv.gz  in=440,030,948 out=113,089,395 elapsed=200.7s

  [17418/21087] intraday_6331.csv.gz  in=440,042,648 out=113,089,395 elapsed=200.8s

  [17419/21087] intraday_6330.csv.gz  in=440,057,028 out=113,089,395 elapsed=200.8s

  [17420/21087] intraday_6332.csv.gz  in=440,071,254 out=113,089,395 elapsed=200.8s

  [17421/21087] intraday_6333.csv.gz  in=440,082,890 out=113,089,395 elapsed=200.8s

  [17422/21087] intraday_6334.csv.gz  in=440,092,715 out=113,089,395 elapsed=200.8s

  [17423/21087] intraday_6335.csv.gz  in=440,104,489 out=113,089,395 elapsed=201.2s

  [17424/21087] intraday_6336.csv.gz  in=440,118,797 out=113,089,395 elapsed=201.2s

  [17425/21087] intraday_6337.csv.gz  in=440,133,753 out=113,089,395 elapsed=201.2s

  [17426/21087] intraday_6338.csv.gz  in=440,147,608 out=113,089,395 elapsed=201.2s

  [17427/21087] intraday_6339.csv.gz  in=440,160,300 out=113,089,395 elapsed=201.2s

  [17428/21087] intraday_6340.csv.gz  in=440,171,673 out=113,089,395 elapsed=201.2s

  [17429/21087] intraday_6341.csv.gz  in=440,183,386 out=113,089,395 elapsed=201.2s

  [17430/21087] intraday_6342.csv.gz  in=440,195,195 out=113,089,395 elapsed=201.3s

  [17431/21087] intraday_6343.csv.gz  in=440,207,453 out=113,089,395 elapsed=201.3s

  [17432/21087] intraday_6344.csv.gz  in=440,220,691 out=113,089,395 elapsed=201.3s

  [17433/21087] intraday_6345.csv.gz  in=440,233,485 out=113,089,395 elapsed=201.3s

  [17434/21087] intraday_6346.csv.gz  in=440,245,174 out=113,089,395 elapsed=201.3s

  [17435/21087] intraday_6347.csv.gz  in=440,255,697 out=113,089,395 elapsed=201.3s

  [17436/21087] intraday_6348.csv.gz  in=440,269,742 out=113,089,395 elapsed=201.3s

  [17437/21087] intraday_6349.csv.gz  in=440,281,243 out=113,089,395 elapsed=201.3s

  [17438/21087] intraday_6350.csv.gz  in=440,294,642 out=113,089,395 elapsed=201.3s

  [17439/21087] intraday_6351.csv.gz  in=440,304,316 out=113,089,395 elapsed=201.3s

  [17440/21087] intraday_6352.csv.gz  in=440,316,720 out=113,089,395 elapsed=201.3s

  [17441/21087] intraday_6353.csv.gz  in=440,329,983 out=113,089,395 elapsed=201.3s

  [17442/21087] intraday_6354.csv.gz  in=440,345,063 out=113,089,395 elapsed=201.4s

  [17443/21087] intraday_6355.csv.gz  in=440,360,660 out=113,089,395 elapsed=201.4s

  [17444/21087] intraday_6356.csv.gz  in=440,376,323 out=113,089,395 elapsed=201.4s

  [17445/21087] intraday_6357.csv.gz  in=440,387,785 out=113,089,395 elapsed=201.4s

  [17446/21087] intraday_6358.csv.gz  in=440,400,759 out=113,089,395 elapsed=201.4s

  [17447/21087] intraday_6359.csv.gz  in=440,414,286 out=113,089,395 elapsed=201.4s

  [17448/21087] intraday_6360.csv.gz  in=440,430,663 out=113,089,395 elapsed=201.4s

  [17449/21087] intraday_6361.csv.gz  in=440,452,023 out=113,089,395 elapsed=201.4s

  [17450/21087] intraday_6362.csv.gz  in=440,465,118 out=113,089,395 elapsed=201.4s

  [17451/21087] intraday_6363.csv.gz  in=440,478,410 out=113,089,395 elapsed=201.4s

  [17452/21087] intraday_6364.csv.gz  in=440,492,279 out=113,089,395 elapsed=201.4s

  [17453/21087] intraday_6365.csv.gz  in=440,506,889 out=113,089,395 elapsed=201.4s

  [17454/21087] intraday_6366.csv.gz  in=440,519,294 out=113,089,395 elapsed=201.4s

  [17455/21087] intraday_6367.csv.gz  in=440,532,238 out=113,089,395 elapsed=201.4s

  [17456/21087] intraday_6368.csv.gz  in=440,545,465 out=113,089,395 elapsed=201.5s

  [17457/21087] intraday_6369.csv.gz  in=440,557,857 out=113,089,395 elapsed=201.5s

  [17458/21087] intraday_6370.csv.gz  in=440,571,976 out=113,089,395 elapsed=201.5s

  [17459/21087] intraday_6371.csv.gz  in=440,583,862 out=113,089,395 elapsed=201.5s

  [17460/21087] intraday_6372.csv.gz  in=440,602,317 out=113,089,395 elapsed=201.5s

  [17461/21087] intraday_6373.csv.gz  in=440,616,972 out=113,089,395 elapsed=201.5s

  [17462/21087] intraday_6374.csv.gz  in=440,630,560 out=113,089,395 elapsed=201.5s

  [17463/21087] intraday_6375.csv.gz  in=440,643,672 out=113,089,395 elapsed=201.5s

  [17464/21087] intraday_6376.csv.gz  in=440,658,043 out=113,089,395 elapsed=201.5s

  [17465/21087] intraday_6377.csv.gz  in=440,672,542 out=113,089,395 elapsed=201.5s

  [17466/21087] intraday_6378.csv.gz  in=440,685,175 out=113,089,395 elapsed=201.5s

  [17467/21087] intraday_6379.csv.gz  in=440,698,676 out=113,089,395 elapsed=201.5s

  [17468/21087] intraday_6381.csv.gz  in=440,712,006 out=113,089,395 elapsed=201.5s

  [17469/21087] intraday_6380.csv.gz  in=440,727,516 out=113,089,395 elapsed=201.6s

  [17470/21087] intraday_6382.csv.gz  in=440,739,284 out=113,089,395 elapsed=201.6s

  [17471/21087] intraday_6383.csv.gz  in=440,753,617 out=113,089,395 elapsed=201.6s

  [17472/21087] intraday_6384.csv.gz  in=440,765,451 out=113,089,395 elapsed=201.6s

  [17473/21087] intraday_6385.csv.gz  in=440,779,794 out=113,089,395 elapsed=201.6s

  [17474/21087] intraday_6386.csv.gz  in=440,795,721 out=113,089,395 elapsed=201.6s

  [17475/21087] intraday_6387.csv.gz  in=440,810,476 out=113,089,395 elapsed=201.6s

  [17476/21087] intraday_6388.csv.gz  in=440,825,169 out=113,089,395 elapsed=201.6s

  [17477/21087] intraday_6389.csv.gz  in=440,838,125 out=113,089,395 elapsed=201.6s

  [17478/21087] intraday_6391.csv.gz  in=440,850,914 out=113,089,395 elapsed=201.6s

  [17479/21087] intraday_6390.csv.gz  in=440,868,140 out=113,089,395 elapsed=201.6s

  [17480/21087] intraday_6392.csv.gz  in=440,879,154 out=113,089,395 elapsed=201.6s

  [17481/21087] intraday_6393.csv.gz  in=440,892,956 out=113,089,395 elapsed=201.6s

  [17482/21087] intraday_6394.csv.gz  in=440,904,695 out=113,089,395 elapsed=201.7s

  [17483/21087] intraday_6396.csv.gz  in=440,918,656 out=113,089,395 elapsed=201.7s

  [17484/21087] intraday_6395.csv.gz  in=440,931,081 out=113,089,395 elapsed=201.7s

  [17485/21087] intraday_6397.csv.gz  in=440,957,591 out=113,089,395 elapsed=201.7s

  [17486/21087] intraday_6398.csv.gz  in=440,969,243 out=113,089,395 elapsed=201.7s

  [17487/21087] intraday_6399.csv.gz  in=440,981,314 out=113,089,395 elapsed=201.7s

  [17488/21087] intraday_6400.csv.gz  in=440,994,615 out=113,089,395 elapsed=201.7s

  [17489/21087] intraday_6401.csv.gz  in=441,006,341 out=113,089,395 elapsed=201.7s

  [17490/21087] intraday_6402.csv.gz  in=441,022,056 out=113,089,395 elapsed=201.7s

  [17491/21087] intraday_6403.csv.gz  in=441,036,230 out=113,089,395 elapsed=201.7s

  [17492/21087] intraday_6404.csv.gz  in=441,050,969 out=113,089,395 elapsed=201.7s

  [17493/21087] intraday_6406.csv.gz  in=441,064,964 out=113,089,395 elapsed=201.8s

  [17494/21087] intraday_6405.csv.gz  in=441,079,611 out=113,089,395 elapsed=201.8s

  [17495/21087] intraday_6407.csv.gz  in=441,091,083 out=113,089,395 elapsed=201.8s

  [17496/21087] intraday_6408.csv.gz  in=441,103,887 out=113,089,395 elapsed=201.8s

  [17497/21087] intraday_6409.csv.gz  in=441,116,329 out=113,089,395 elapsed=201.8s

  [17498/21087] intraday_6410.csv.gz  in=441,129,313 out=113,089,395 elapsed=201.8s

  [17499/21087] intraday_6411.csv.gz  in=441,139,553 out=113,089,395 elapsed=201.8s

  [17500/21087] intraday_6412.csv.gz  in=441,148,461 out=113,089,395 elapsed=201.8s

  [17501/21087] intraday_6413.csv.gz  in=441,161,032 out=113,089,395 elapsed=201.8s

  [17502/21087] intraday_6414.csv.gz  in=441,163,715 out=113,089,395 elapsed=201.8s

  [17503/21087] intraday_6416.csv.gz  in=441,176,616 out=113,089,395 elapsed=201.8s

  [17504/21087] intraday_6415.csv.gz  in=441,192,945 out=113,089,395 elapsed=201.8s

  [17505/21087] intraday_6417.csv.gz  in=441,206,932 out=113,089,395 elapsed=201.8s

  [17506/21087] intraday_6418.csv.gz  in=441,218,175 out=113,089,395 elapsed=201.8s

  [17507/21087] intraday_6419.csv.gz  in=441,231,046 out=113,089,395 elapsed=201.9s

  [17508/21087] intraday_6422.csv.gz  in=441,243,755 out=113,089,395 elapsed=201.9s

  [17509/21087] intraday_6420.csv.gz  in=441,258,033 out=113,089,395 elapsed=201.9s

  [17510/21087] intraday_6421.csv.gz  in=441,273,067 out=113,089,395 elapsed=201.9s

  [17511/21087] intraday_6423.csv.gz  in=441,287,020 out=113,089,395 elapsed=201.9s

  [17512/21087] intraday_6425.csv.gz  in=441,303,010 out=113,089,395 elapsed=201.9s

  [17513/21087] intraday_6424.csv.gz  in=441,317,507 out=113,089,395 elapsed=201.9s

  [17514/21087] intraday_6426.csv.gz  in=441,331,357 out=113,089,395 elapsed=201.9s

  [17515/21087] intraday_6427.csv.gz  in=441,345,075 out=113,089,395 elapsed=201.9s

  [17516/21087] intraday_6428.csv.gz  in=441,357,560 out=113,089,395 elapsed=201.9s

  [17517/21087] intraday_6429.csv.gz  in=441,368,452 out=113,089,395 elapsed=201.9s

  [17518/21087] intraday_6430.csv.gz  in=441,378,087 out=113,089,395 elapsed=201.9s

  [17519/21087] intraday_6431.csv.gz  in=441,391,870 out=113,089,395 elapsed=201.9s

  [17520/21087] intraday_6433.csv.gz  in=441,402,288 out=113,089,395 elapsed=202.0s

  [17521/21087] intraday_6432.csv.gz  in=441,416,229 out=113,089,395 elapsed=202.0s

  [17522/21087] intraday_6434.csv.gz  in=441,429,590 out=113,089,395 elapsed=202.0s

  [17523/21087] intraday_6435.csv.gz  in=441,441,975 out=113,089,395 elapsed=202.0s

  [17524/21087] intraday_6436.csv.gz  in=441,454,886 out=113,089,395 elapsed=202.0s

  [17525/21087] intraday_6437.csv.gz  in=441,467,128 out=113,089,395 elapsed=202.0s

  [17526/21087] intraday_6438.csv.gz  in=441,480,551 out=113,089,395 elapsed=202.0s

  [17527/21087] intraday_6439.csv.gz  in=441,492,884 out=113,089,395 elapsed=202.0s

  [17528/21087] intraday_6440.csv.gz  in=441,504,268 out=113,089,395 elapsed=202.0s

  [17529/21087] intraday_6441.csv.gz  in=441,515,720 out=113,089,395 elapsed=202.0s

  [17530/21087] intraday_6442.csv.gz  in=441,527,554 out=113,089,395 elapsed=202.0s

  [17531/21087] intraday_6443.csv.gz  in=441,540,355 out=113,089,395 elapsed=202.0s

  [17532/21087] intraday_6444.csv.gz  in=441,554,836 out=113,089,395 elapsed=202.0s

  [17533/21087] intraday_6445.csv.gz  in=441,572,140 out=113,089,395 elapsed=202.1s

  [17534/21087] intraday_6446.csv.gz  in=441,582,990 out=113,089,395 elapsed=202.1s

  [17535/21087] intraday_6447.csv.gz  in=441,593,715 out=113,089,395 elapsed=202.1s

  [17536/21087] intraday_6448.csv.gz  in=441,606,820 out=113,089,395 elapsed=202.1s

  [17537/21087] intraday_6450.csv.gz  in=441,618,763 out=113,089,395 elapsed=202.1s

  [17538/21087] intraday_6449.csv.gz  in=441,633,686 out=113,089,395 elapsed=202.1s

  [17539/21087] intraday_6451.csv.gz  in=441,647,369 out=113,089,395 elapsed=202.1s

  [17540/21087] intraday_6452.csv.gz  in=441,657,856 out=113,089,395 elapsed=202.1s

  [17541/21087] intraday_6453.csv.gz  in=441,670,259 out=113,089,395 elapsed=202.1s

  [17542/21087] intraday_6454.csv.gz  in=441,681,395 out=113,089,395 elapsed=202.1s

  [17543/21087] intraday_6455.csv.gz  in=441,693,355 out=113,089,395 elapsed=202.1s

  [17544/21087] intraday_6456.csv.gz  in=441,706,566 out=113,089,395 elapsed=202.1s

  [17545/21087] intraday_6457.csv.gz  in=441,719,823 out=113,089,395 elapsed=202.1s

  [17546/21087] intraday_6460.csv.gz  in=441,730,850 out=113,089,395 elapsed=202.2s

  [17547/21087] intraday_6459.csv.gz  in=441,743,871 out=113,089,395 elapsed=202.2s

  [17548/21087] intraday_6461.csv.gz  in=441,756,947 out=113,089,395 elapsed=202.2s

  [17549/21087] intraday_6458.csv.gz  in=441,770,478 out=113,089,395 elapsed=202.2s

  [17550/21087] intraday_6462.csv.gz  in=441,782,084 out=113,089,395 elapsed=202.2s

  [17551/21087] intraday_6463.csv.gz  in=441,793,096 out=113,089,395 elapsed=202.2s

  [17552/21087] intraday_6464.csv.gz  in=441,804,816 out=113,089,395 elapsed=202.2s

  [17553/21087] intraday_6465.csv.gz  in=441,816,756 out=113,089,395 elapsed=202.2s

  [17554/21087] intraday_6466.csv.gz  in=441,829,711 out=113,089,395 elapsed=202.2s

  [17555/21087] intraday_6469.csv.gz  in=441,844,707 out=113,089,395 elapsed=202.2s

  [17556/21087] intraday_6467.csv.gz  in=441,857,389 out=113,089,395 elapsed=202.2s

  [17557/21087] intraday_6468.csv.gz  in=441,869,132 out=113,089,395 elapsed=202.2s

  [17558/21087] intraday_6470.csv.gz  in=441,882,173 out=113,089,395 elapsed=202.3s

  [17559/21087] intraday_6472.csv.gz  in=441,893,162 out=113,089,395 elapsed=202.3s

  [17560/21087] intraday_6473.csv.gz  in=441,907,250 out=113,089,395 elapsed=202.3s

  [17561/21087] intraday_6471.csv.gz  in=441,919,174 out=113,089,395 elapsed=202.3s

  [17562/21087] intraday_6474.csv.gz  in=441,933,712 out=113,089,395 elapsed=202.3s

  [17563/21087] intraday_6477.csv.gz  in=441,945,990 out=113,089,395 elapsed=202.3s

  [17564/21087] intraday_6476.csv.gz  in=441,957,996 out=113,089,395 elapsed=202.3s

  [17565/21087] intraday_6475.csv.gz  in=441,970,239 out=113,089,395 elapsed=202.3s

  [17566/21087] intraday_6478.csv.gz  in=441,981,236 out=113,089,395 elapsed=202.3s

  [17567/21087] intraday_6479.csv.gz  in=441,995,309 out=113,089,395 elapsed=202.3s

  [17568/21087] intraday_6481.csv.gz  in=442,006,843 out=113,089,395 elapsed=202.3s

  [17569/21087] intraday_6480.csv.gz  in=442,023,185 out=113,089,395 elapsed=202.4s

  [17570/21087] intraday_6482.csv.gz  in=442,035,694 out=113,089,395 elapsed=202.4s

  [17571/21087] intraday_6483.csv.gz  in=442,048,880 out=113,089,395 elapsed=202.4s

  [17572/21087] intraday_6485.csv.gz  in=442,060,206 out=113,089,395 elapsed=202.4s

  [17573/21087] intraday_6486.csv.gz  in=442,072,087 out=113,089,395 elapsed=202.4s

  [17574/21087] intraday_6484.csv.gz  in=442,082,665 out=113,089,395 elapsed=202.4s

  [17575/21087] intraday_6487.csv.gz  in=442,097,489 out=113,089,395 elapsed=202.4s

  [17576/21087] intraday_6488.csv.gz  in=442,108,612 out=113,089,395 elapsed=202.4s

  [17577/21087] intraday_6489.csv.gz  in=442,121,606 out=113,089,395 elapsed=202.4s

  [17578/21087] intraday_6490.csv.gz  in=442,132,002 out=113,089,395 elapsed=202.4s

  [17579/21087] intraday_6491.csv.gz  in=442,146,133 out=113,089,395 elapsed=202.4s

  [17580/21087] intraday_6492.csv.gz  in=442,158,541 out=113,089,395 elapsed=202.4s

  [17581/21087] intraday_6493.csv.gz  in=442,172,428 out=113,089,395 elapsed=202.4s

  [17582/21087] intraday_6494.csv.gz  in=442,183,195 out=113,089,395 elapsed=202.4s

  [17583/21087] intraday_6495.csv.gz  in=442,193,837 out=113,089,395 elapsed=202.5s

  [17584/21087] intraday_6496.csv.gz  in=442,206,189 out=113,089,395 elapsed=202.5s

  [17585/21087] intraday_6497.csv.gz  in=442,222,384 out=113,089,395 elapsed=202.5s

  [17586/21087] intraday_6498.csv.gz  in=442,238,866 out=113,089,395 elapsed=202.5s

  [17587/21087] intraday_6499.csv.gz  in=442,252,857 out=113,089,395 elapsed=202.5s

  [17588/21087] intraday_6500.csv.gz  in=442,266,173 out=113,089,395 elapsed=202.5s

  [17589/21087] intraday_6501.csv.gz  in=442,277,641 out=113,089,395 elapsed=202.5s

  [17590/21087] intraday_6502.csv.gz  in=442,292,153 out=113,089,395 elapsed=202.5s

  [17591/21087] intraday_6503.csv.gz  in=442,306,408 out=113,089,395 elapsed=202.5s

  [17592/21087] intraday_6504.csv.gz  in=442,320,936 out=113,089,395 elapsed=202.5s

  [17593/21087] intraday_6505.csv.gz  in=442,333,008 out=113,089,395 elapsed=202.5s

  [17594/21087] intraday_6506.csv.gz  in=442,349,641 out=113,089,395 elapsed=202.5s

  [17595/21087] intraday_6508.csv.gz  in=442,363,342 out=113,089,395 elapsed=202.6s

  [17596/21087] intraday_6507.csv.gz  in=442,377,485 out=113,089,395 elapsed=202.6s

  [17597/21087] intraday_6509.csv.gz  in=442,390,055 out=113,089,395 elapsed=202.6s

  [17598/21087] intraday_6510.csv.gz  in=442,403,443 out=113,089,395 elapsed=202.6s

  [17599/21087] intraday_6511.csv.gz  in=442,415,752 out=113,089,395 elapsed=202.6s

  [17600/21087] intraday_6512.csv.gz  in=442,430,317 out=113,089,395 elapsed=202.6s

  [17601/21087] intraday_6513.csv.gz  in=442,442,870 out=113,089,395 elapsed=202.6s

  [17602/21087] intraday_6514.csv.gz  in=442,455,784 out=113,089,395 elapsed=202.6s

  [17603/21087] intraday_6515.csv.gz  in=442,467,879 out=113,089,395 elapsed=202.6s

  [17604/21087] intraday_6516.csv.gz  in=442,482,935 out=113,089,395 elapsed=202.6s

  [17605/21087] intraday_6517.csv.gz  in=442,498,185 out=113,089,395 elapsed=202.6s

  [17606/21087] intraday_6518.csv.gz  in=442,512,125 out=113,089,395 elapsed=202.6s

  [17607/21087] intraday_6519.csv.gz  in=442,522,955 out=113,089,395 elapsed=202.6s

  [17608/21087] intraday_6521.csv.gz  in=442,535,683 out=113,089,395 elapsed=202.6s

  [17609/21087] intraday_6522.csv.gz  in=442,547,270 out=113,089,395 elapsed=202.7s

  [17610/21087] intraday_6520.csv.gz  in=442,580,346 out=113,089,395 elapsed=202.7s

  [17611/21087] intraday_6523.csv.gz  in=442,595,313 out=113,089,395 elapsed=202.7s

  [17612/21087] intraday_6524.csv.gz  in=442,608,631 out=113,089,395 elapsed=202.7s

  [17613/21087] intraday_6525.csv.gz  in=442,620,603 out=113,089,395 elapsed=202.7s

  [17614/21087] intraday_6526.csv.gz  in=442,635,452 out=113,089,395 elapsed=202.7s

  [17615/21087] intraday_6528.csv.gz  in=442,648,997 out=113,089,395 elapsed=202.7s

  [17616/21087] intraday_6527.csv.gz  in=442,671,381 out=113,089,395 elapsed=202.7s

  [17617/21087] intraday_6529.csv.gz  in=442,687,351 out=113,089,395 elapsed=202.7s

  [17618/21087] intraday_6530.csv.gz  in=442,704,085 out=113,089,395 elapsed=202.7s

  [17619/21087] intraday_6531.csv.gz  in=442,716,584 out=113,089,395 elapsed=202.7s

  [17620/21087] intraday_6532.csv.gz  in=442,732,487 out=113,089,395 elapsed=202.7s

  [17621/21087] intraday_6533.csv.gz  in=442,744,143 out=113,089,395 elapsed=202.8s

  [17622/21087] intraday_6534.csv.gz  in=442,757,259 out=113,089,395 elapsed=202.8s

  [17623/21087] intraday_6535.csv.gz  in=442,768,544 out=113,089,395 elapsed=202.8s

  [17624/21087] intraday_6536.csv.gz  in=442,783,054 out=113,089,395 elapsed=202.8s

  [17625/21087] intraday_6537.csv.gz  in=442,794,305 out=113,089,395 elapsed=202.8s

  [17626/21087] intraday_6538.csv.gz  in=442,808,415 out=113,089,395 elapsed=202.8s

  [17627/21087] intraday_6539.csv.gz  in=442,820,732 out=113,089,395 elapsed=202.8s

  [17628/21087] intraday_6540.csv.gz  in=442,836,071 out=113,089,395 elapsed=202.8s

  [17629/21087] intraday_6541.csv.gz  in=442,849,281 out=113,089,395 elapsed=202.8s

  [17630/21087] intraday_6542.csv.gz  in=442,862,021 out=113,089,395 elapsed=202.8s

  [17631/21087] intraday_6543.csv.gz  in=442,875,092 out=113,089,395 elapsed=202.8s

  [17632/21087] intraday_6544.csv.gz  in=442,887,503 out=113,089,395 elapsed=202.8s

  [17633/21087] intraday_6545.csv.gz  in=442,900,695 out=113,089,395 elapsed=202.9s

  [17634/21087] intraday_6546.csv.gz  in=442,915,245 out=113,089,395 elapsed=202.9s

  [17635/21087] intraday_6547.csv.gz  in=442,928,766 out=113,089,395 elapsed=202.9s

  [17636/21087] intraday_6548.csv.gz  in=442,943,759 out=113,089,395 elapsed=202.9s

  [17637/21087] intraday_6549.csv.gz  in=442,957,604 out=113,089,395 elapsed=202.9s

  [17638/21087] intraday_6550.csv.gz  in=442,968,390 out=113,089,395 elapsed=202.9s

  [17639/21087] intraday_6551.csv.gz  in=442,982,043 out=113,089,395 elapsed=202.9s

  [17640/21087] intraday_6552.csv.gz  in=442,994,813 out=113,089,395 elapsed=202.9s

  [17641/21087] intraday_6553.csv.gz  in=443,006,581 out=113,089,395 elapsed=202.9s

  [17642/21087] intraday_6554.csv.gz  in=443,018,372 out=113,089,395 elapsed=202.9s

  [17643/21087] intraday_6555.csv.gz  in=443,026,912 out=113,089,395 elapsed=202.9s

  [17644/21087] intraday_6556.csv.gz  in=443,039,498 out=113,089,395 elapsed=202.9s

  [17645/21087] intraday_6557.csv.gz  in=443,044,748 out=113,089,395 elapsed=202.9s

  [17646/21087] intraday_6558.csv.gz  in=443,064,024 out=113,089,395 elapsed=203.0s

  [17647/21087] intraday_6559.csv.gz  in=443,077,399 out=113,089,395 elapsed=203.0s

  [17648/21087] intraday_6560.csv.gz  in=443,090,365 out=113,089,395 elapsed=203.0s

  [17649/21087] intraday_6561.csv.gz  in=443,101,853 out=113,089,395 elapsed=203.0s

  [17650/21087] intraday_6562.csv.gz  in=443,114,637 out=113,089,395 elapsed=203.0s

  [17651/21087] intraday_6563.csv.gz  in=443,130,018 out=113,089,395 elapsed=203.0s

  [17652/21087] intraday_6564.csv.gz  in=443,144,357 out=113,089,395 elapsed=203.0s

  [17653/21087] intraday_6565.csv.gz  in=443,156,409 out=113,089,395 elapsed=203.0s

  [17654/21087] intraday_6566.csv.gz  in=443,173,853 out=113,089,395 elapsed=203.0s

  [17655/21087] intraday_6567.csv.gz  in=443,187,686 out=113,089,395 elapsed=203.0s

  [17656/21087] intraday_6569.csv.gz  in=443,201,414 out=113,089,395 elapsed=203.1s

  [17657/21087] intraday_6568.csv.gz  in=443,217,847 out=113,089,395 elapsed=203.1s

  [17658/21087] intraday_6570.csv.gz  in=443,232,023 out=113,089,395 elapsed=203.1s

  [17659/21087] intraday_6571.csv.gz  in=443,244,352 out=113,089,395 elapsed=203.1s

  [17660/21087] intraday_6572.csv.gz  in=443,254,779 out=113,089,395 elapsed=203.1s

  [17661/21087] intraday_6573.csv.gz  in=443,263,995 out=113,089,395 elapsed=203.1s

  [17662/21087] intraday_6574.csv.gz  in=443,278,249 out=113,089,395 elapsed=203.1s

  [17663/21087] intraday_6575.csv.gz  in=443,291,452 out=113,089,395 elapsed=203.1s

  [17664/21087] intraday_6576.csv.gz  in=443,303,544 out=113,089,395 elapsed=203.1s

  [17665/21087] intraday_6577.csv.gz  in=443,316,282 out=113,089,395 elapsed=203.1s

  [17666/21087] intraday_6578.csv.gz  in=443,328,637 out=113,089,395 elapsed=203.1s

  [17667/21087] intraday_6579.csv.gz  in=443,341,097 out=113,089,395 elapsed=203.1s

  [17668/21087] intraday_6580.csv.gz  in=443,353,119 out=113,089,395 elapsed=203.1s

  [17669/21087] intraday_6581.csv.gz  in=443,366,693 out=113,089,395 elapsed=203.2s

  [17670/21087] intraday_6582.csv.gz  in=443,380,557 out=113,089,395 elapsed=203.2s

  [17671/21087] intraday_6584.csv.gz  in=443,392,117 out=113,089,395 elapsed=203.2s

  [17672/21087] intraday_6583.csv.gz  in=443,413,123 out=113,089,395 elapsed=203.2s

  [17673/21087] intraday_6585.csv.gz  in=443,425,324 out=113,089,395 elapsed=203.2s

  [17674/21087] intraday_6586.csv.gz  in=443,437,745 out=113,089,395 elapsed=203.2s

  [17675/21087] intraday_6587.csv.gz  in=443,450,330 out=113,089,395 elapsed=203.2s

  [17676/21087] intraday_6589.csv.gz  in=443,463,092 out=113,089,395 elapsed=203.2s

  [17677/21087] intraday_6590.csv.gz  in=443,474,768 out=113,089,395 elapsed=203.2s

  [17678/21087] intraday_6588.csv.gz  in=443,492,418 out=113,089,395 elapsed=203.2s

  [17679/21087] intraday_6591.csv.gz  in=443,505,322 out=113,089,395 elapsed=203.2s

  [17680/21087] intraday_6592.csv.gz  in=443,519,130 out=113,089,395 elapsed=203.2s

  [17681/21087] intraday_6593.csv.gz  in=443,530,740 out=113,089,395 elapsed=203.2s

  [17682/21087] intraday_6594.csv.gz  in=443,545,537 out=113,089,395 elapsed=203.3s

  [17683/21087] intraday_6595.csv.gz  in=443,556,752 out=113,089,395 elapsed=203.3s

  [17684/21087] intraday_6596.csv.gz  in=443,570,845 out=113,089,395 elapsed=203.3s

  [17685/21087] intraday_6597.csv.gz  in=443,583,058 out=113,089,395 elapsed=203.3s

  [17686/21087] intraday_6598.csv.gz  in=443,595,551 out=113,089,395 elapsed=203.3s

  [17687/21087] intraday_6599.csv.gz  in=443,612,140 out=113,089,395 elapsed=203.3s

  [17688/21087] intraday_6601.csv.gz  in=443,623,409 out=113,089,395 elapsed=203.3s

  [17689/21087] intraday_6602.csv.gz  in=443,637,245 out=113,089,395 elapsed=203.3s

  [17690/21087] intraday_6600.csv.gz  in=443,650,584 out=113,089,395 elapsed=203.3s

  [17691/21087] intraday_6603.csv.gz  in=443,661,710 out=113,089,395 elapsed=203.3s

  [17692/21087] intraday_6606.csv.gz  in=443,672,420 out=113,089,395 elapsed=203.3s

  [17693/21087] intraday_6604.csv.gz  in=443,684,795 out=113,089,395 elapsed=203.3s

  [17694/21087] intraday_6605.csv.gz  in=443,698,192 out=113,089,395 elapsed=203.4s

  [17695/21087] intraday_6607.csv.gz  in=443,709,741 out=113,089,395 elapsed=203.4s

  [17696/21087] intraday_6608.csv.gz  in=443,721,529 out=113,089,395 elapsed=203.4s

  [17697/21087] intraday_6609.csv.gz  in=443,733,923 out=113,089,395 elapsed=203.4s

  [17698/21087] intraday_6610.csv.gz  in=443,746,611 out=113,089,395 elapsed=203.4s

  [17699/21087] intraday_6611.csv.gz  in=443,758,966 out=113,089,395 elapsed=203.4s

  [17700/21087] intraday_6612.csv.gz  in=443,773,834 out=113,089,395 elapsed=203.4s

  [17701/21087] intraday_6613.csv.gz  in=443,787,773 out=113,089,395 elapsed=203.4s

  [17702/21087] intraday_6614.csv.gz  in=443,800,661 out=113,089,395 elapsed=203.4s

  [17703/21087] intraday_6615.csv.gz  in=443,812,046 out=113,089,395 elapsed=203.4s

  [17704/21087] intraday_6616.csv.gz  in=443,826,076 out=113,089,395 elapsed=203.4s

  [17705/21087] intraday_6617.csv.gz  in=443,840,865 out=113,089,395 elapsed=203.5s

  [17706/21087] intraday_6618.csv.gz  in=443,854,029 out=113,089,395 elapsed=203.5s

  [17707/21087] intraday_6619.csv.gz  in=443,867,711 out=113,089,395 elapsed=203.5s

  [17708/21087] intraday_6620.csv.gz  in=443,879,394 out=113,089,395 elapsed=203.5s

  [17709/21087] intraday_6621.csv.gz  in=443,891,078 out=113,089,395 elapsed=203.5s

  [17710/21087] intraday_6624.csv.gz  in=443,904,225 out=113,089,395 elapsed=203.5s

  [17711/21087] intraday_6622.csv.gz  in=443,920,896 out=113,089,395 elapsed=203.5s

  [17712/21087] intraday_6623.csv.gz  in=443,936,645 out=113,089,395 elapsed=203.5s

  [17713/21087] intraday_6625.csv.gz  in=443,949,883 out=113,089,395 elapsed=203.5s

  [17714/21087] intraday_6626.csv.gz  in=443,962,596 out=113,089,395 elapsed=203.6s

  [17715/21087] intraday_6628.csv.gz  in=443,974,860 out=113,089,395 elapsed=203.6s

  [17716/21087] intraday_6627.csv.gz  in=443,986,303 out=113,089,395 elapsed=203.6s

  [17717/21087] intraday_6629.csv.gz  in=443,997,288 out=113,089,395 elapsed=203.6s

  [17718/21087] intraday_6630.csv.gz  in=444,011,789 out=113,089,395 elapsed=203.6s

  [17719/21087] intraday_6632.csv.gz  in=444,023,841 out=113,089,395 elapsed=203.6s

  [17720/21087] intraday_6631.csv.gz  in=444,036,854 out=113,089,395 elapsed=203.6s

  [17721/21087] intraday_6633.csv.gz  in=444,047,186 out=113,089,395 elapsed=203.6s

  [17722/21087] intraday_6634.csv.gz  in=444,060,472 out=113,089,395 elapsed=203.6s

  [17723/21087] intraday_6636.csv.gz  in=444,072,634 out=113,089,395 elapsed=203.6s

  [17724/21087] intraday_6635.csv.gz  in=444,084,506 out=113,089,395 elapsed=203.6s

  [17725/21087] intraday_6637.csv.gz  in=444,101,230 out=113,089,395 elapsed=203.6s

  [17726/21087] intraday_6638.csv.gz  in=444,110,961 out=113,089,395 elapsed=203.6s

  [17727/21087] intraday_6639.csv.gz  in=444,123,164 out=113,089,395 elapsed=203.7s

  [17728/21087] intraday_6640.csv.gz  in=444,135,815 out=113,089,395 elapsed=203.7s

  [17729/21087] intraday_6641.csv.gz  in=444,151,559 out=113,089,395 elapsed=203.7s

  [17730/21087] intraday_6642.csv.gz  in=444,166,286 out=113,089,395 elapsed=203.7s

  [17731/21087] intraday_6643.csv.gz  in=444,179,707 out=113,089,395 elapsed=203.7s

  [17732/21087] intraday_6644.csv.gz  in=444,192,115 out=113,089,395 elapsed=203.7s

  [17733/21087] intraday_6645.csv.gz  in=444,206,246 out=113,089,395 elapsed=203.7s

  [17734/21087] intraday_6646.csv.gz  in=444,219,565 out=113,089,395 elapsed=203.7s

  [17735/21087] intraday_6647.csv.gz  in=444,235,822 out=113,089,395 elapsed=203.7s

  [17736/21087] intraday_6648.csv.gz  in=444,250,773 out=113,089,395 elapsed=203.7s

  [17737/21087] intraday_6649.csv.gz  in=444,268,141 out=113,089,395 elapsed=203.7s

  [17738/21087] intraday_6650.csv.gz  in=444,282,376 out=113,089,395 elapsed=203.7s

  [17739/21087] intraday_6651.csv.gz  in=444,296,738 out=113,089,395 elapsed=203.7s

  [17740/21087] intraday_6652.csv.gz  in=444,310,495 out=113,089,395 elapsed=203.8s

  [17741/21087] intraday_6653.csv.gz  in=444,323,553 out=113,089,395 elapsed=203.8s

  [17742/21087] intraday_6654.csv.gz  in=444,336,099 out=113,089,395 elapsed=203.8s

  [17743/21087] intraday_6655.csv.gz  in=444,349,251 out=113,089,395 elapsed=203.8s

  [17744/21087] intraday_6657.csv.gz  in=444,363,493 out=113,089,395 elapsed=203.8s

  [17745/21087] intraday_6656.csv.gz  in=444,377,667 out=113,089,395 elapsed=203.8s

  [17746/21087] intraday_6658.csv.gz  in=444,390,076 out=113,089,395 elapsed=203.8s

  [17747/21087] intraday_6659.csv.gz  in=444,403,760 out=113,089,395 elapsed=203.8s

  [17748/21087] intraday_6661.csv.gz  in=444,417,852 out=113,089,395 elapsed=203.8s

  [17749/21087] intraday_6660.csv.gz  in=444,432,554 out=113,089,395 elapsed=203.8s

  [17750/21087] intraday_6662.csv.gz  in=444,445,485 out=113,089,395 elapsed=203.8s

  [17751/21087] intraday_6663.csv.gz  in=444,460,227 out=113,089,395 elapsed=203.8s

  [17752/21087] intraday_6664.csv.gz  in=444,475,810 out=113,089,395 elapsed=203.9s

  [17753/21087] intraday_6665.csv.gz  in=444,488,032 out=113,089,395 elapsed=203.9s

  [17754/21087] intraday_6666.csv.gz  in=444,501,759 out=113,089,395 elapsed=203.9s

  [17755/21087] intraday_6667.csv.gz  in=444,517,141 out=113,089,395 elapsed=203.9s

  [17756/21087] intraday_6669.csv.gz  in=444,528,120 out=113,089,395 elapsed=203.9s

  [17757/21087] intraday_6668.csv.gz  in=444,541,175 out=113,089,395 elapsed=203.9s

  [17758/21087] intraday_6670.csv.gz  in=444,555,905 out=113,089,395 elapsed=203.9s

  [17759/21087] intraday_6671.csv.gz  in=444,567,621 out=113,089,395 elapsed=203.9s

  [17760/21087] intraday_6672.csv.gz  in=444,582,731 out=113,089,395 elapsed=203.9s

  [17761/21087] intraday_6673.csv.gz  in=444,598,323 out=113,089,395 elapsed=203.9s

  [17762/21087] intraday_6675.csv.gz  in=444,613,431 out=113,089,395 elapsed=203.9s

  [17763/21087] intraday_6674.csv.gz  in=444,629,987 out=113,089,395 elapsed=203.9s

  [17764/21087] intraday_6676.csv.gz  in=444,642,416 out=113,089,395 elapsed=203.9s

  [17765/21087] intraday_6677.csv.gz  in=444,654,685 out=113,089,395 elapsed=203.9s

  [17766/21087] intraday_6678.csv.gz  in=444,666,693 out=113,089,395 elapsed=204.0s

  [17767/21087] intraday_6679.csv.gz  in=444,677,850 out=113,089,395 elapsed=204.0s

  [17768/21087] intraday_6680.csv.gz  in=444,692,771 out=113,089,395 elapsed=204.0s

  [17769/21087] intraday_6681.csv.gz  in=444,703,600 out=113,089,395 elapsed=204.0s

  [17770/21087] intraday_6682.csv.gz  in=444,716,723 out=113,089,395 elapsed=204.0s

  [17771/21087] intraday_6683.csv.gz  in=444,729,598 out=113,089,395 elapsed=204.0s

  [17772/21087] intraday_6684.csv.gz  in=444,745,389 out=113,089,395 elapsed=204.0s

  [17773/21087] intraday_6685.csv.gz  in=444,761,926 out=113,089,395 elapsed=204.0s

  [17774/21087] intraday_6686.csv.gz  in=444,774,663 out=113,089,395 elapsed=204.0s

  [17775/21087] intraday_6687.csv.gz  in=444,788,293 out=113,089,395 elapsed=204.0s

  [17776/21087] intraday_6688.csv.gz  in=444,802,241 out=113,089,395 elapsed=204.0s

  [17777/21087] intraday_6689.csv.gz  in=444,815,052 out=113,089,395 elapsed=204.0s

  [17778/21087] intraday_6690.csv.gz  in=444,829,329 out=113,089,395 elapsed=204.1s

  [17779/21087] intraday_6691.csv.gz  in=444,843,733 out=113,089,395 elapsed=204.1s

  [17780/21087] intraday_6692.csv.gz  in=444,857,399 out=113,089,395 elapsed=204.1s

  [17781/21087] intraday_6693.csv.gz  in=444,870,926 out=113,089,395 elapsed=204.1s

  [17782/21087] intraday_6694.csv.gz  in=444,882,432 out=113,089,395 elapsed=204.1s

  [17783/21087] intraday_6695.csv.gz  in=444,896,184 out=113,089,395 elapsed=204.1s

  [17784/21087] intraday_6696.csv.gz  in=444,908,097 out=113,089,395 elapsed=204.1s

  [17785/21087] intraday_6697.csv.gz  in=444,920,254 out=113,089,395 elapsed=204.1s

  [17786/21087] intraday_6698.csv.gz  in=444,931,597 out=113,089,395 elapsed=204.1s

  [17787/21087] intraday_6699.csv.gz  in=444,939,795 out=113,089,395 elapsed=204.1s

  [17788/21087] intraday_6702.csv.gz  in=444,939,831 out=113,089,395 elapsed=204.1s

  [17789/21087] intraday_6703.csv.gz  in=444,940,040 out=113,089,395 elapsed=204.1s

  [17790/21087] intraday_6701.csv.gz  in=444,943,812 out=113,089,395 elapsed=204.2s

  [17791/21087] intraday_6700.csv.gz  in=444,956,858 out=113,089,395 elapsed=204.2s

  [17792/21087] intraday_6704.csv.gz  in=444,957,553 out=113,089,395 elapsed=204.2s

  [17793/21087] intraday_6705.csv.gz  in=444,957,577 out=113,089,395 elapsed=204.2s

  [17794/21087] intraday_6706.csv.gz  in=444,957,587 out=113,089,395 elapsed=204.2s

  [17795/21087] intraday_6707.csv.gz  in=444,957,608 out=113,089,395 elapsed=204.2s

  [17796/21087] intraday_6709.csv.gz  in=444,957,611 out=113,089,395 elapsed=204.2s

  [17797/21087] intraday_6708.csv.gz  in=444,957,939 out=113,089,395 elapsed=204.2s

  [17798/21087] intraday_6710.csv.gz  in=444,957,964 out=113,089,395 elapsed=204.2s

  [17799/21087] intraday_6711.csv.gz  in=444,975,672 out=113,089,395 elapsed=204.2s

  [17800/21087] intraday_6712.csv.gz  in=444,989,509 out=113,089,395 elapsed=204.2s

  [17801/21087] intraday_6713.csv.gz  in=445,003,404 out=113,089,395 elapsed=204.2s

  [17802/21087] intraday_6714.csv.gz  in=445,016,149 out=113,089,395 elapsed=204.2s

  [17803/21087] intraday_6715.csv.gz  in=445,028,274 out=113,089,395 elapsed=204.3s

  [17804/21087] intraday_6718.csv.gz  in=445,041,063 out=113,089,395 elapsed=204.3s

  [17805/21087] intraday_6717.csv.gz  in=445,057,430 out=113,089,395 elapsed=204.3s

  [17806/21087] intraday_6716.csv.gz  in=445,073,012 out=113,089,395 elapsed=204.3s

  [17807/21087] intraday_6719.csv.gz  in=445,087,294 out=113,089,395 elapsed=204.3s

  [17808/21087] intraday_6720.csv.gz  in=445,102,112 out=113,089,395 elapsed=204.3s

  [17809/21087] intraday_6721.csv.gz  in=445,118,067 out=113,089,395 elapsed=204.3s

  [17810/21087] intraday_6722.csv.gz  in=445,133,066 out=113,089,395 elapsed=204.3s

  [17811/21087] intraday_6723.csv.gz  in=445,146,701 out=113,089,395 elapsed=204.3s

  [17812/21087] intraday_6725.csv.gz  in=445,157,893 out=113,089,395 elapsed=204.3s

  [17813/21087] intraday_6724.csv.gz  in=445,171,638 out=113,089,395 elapsed=204.3s

  [17814/21087] intraday_6726.csv.gz  in=445,184,557 out=113,089,395 elapsed=204.3s

  [17815/21087] intraday_6727.csv.gz  in=445,199,392 out=113,089,395 elapsed=204.3s

  [17816/21087] intraday_6728.csv.gz  in=445,213,874 out=113,089,395 elapsed=204.4s

  [17817/21087] intraday_6729.csv.gz  in=445,225,527 out=113,089,395 elapsed=204.4s

  [17818/21087] intraday_6730.csv.gz  in=445,238,731 out=113,089,395 elapsed=204.4s

  [17819/21087] intraday_6731.csv.gz  in=445,250,994 out=113,089,395 elapsed=204.4s

  [17820/21087] intraday_6732.csv.gz  in=445,264,284 out=113,089,395 elapsed=204.4s

  [17821/21087] intraday_6733.csv.gz  in=445,276,786 out=113,089,395 elapsed=204.4s

  [17822/21087] intraday_6734.csv.gz  in=445,290,916 out=113,089,395 elapsed=204.4s

  [17823/21087] intraday_6735.csv.gz  in=445,305,066 out=113,089,395 elapsed=204.4s

  [17824/21087] intraday_6736.csv.gz  in=445,318,736 out=113,089,395 elapsed=204.4s

  [17825/21087] intraday_6737.csv.gz  in=445,330,022 out=113,089,395 elapsed=204.4s

  [17826/21087] intraday_6738.csv.gz  in=445,343,602 out=113,089,395 elapsed=204.4s

  [17827/21087] intraday_6739.csv.gz  in=445,356,391 out=113,089,395 elapsed=204.4s

  [17828/21087] intraday_6740.csv.gz  in=445,370,291 out=113,089,395 elapsed=204.5s

  [17829/21087] intraday_6742.csv.gz  in=445,385,321 out=113,089,395 elapsed=204.5s

  [17830/21087] intraday_6741.csv.gz  in=445,404,360 out=113,089,395 elapsed=204.5s

  [17831/21087] intraday_6743.csv.gz  in=445,414,907 out=113,089,395 elapsed=204.5s

  [17832/21087] intraday_6744.csv.gz  in=445,428,551 out=113,089,395 elapsed=204.5s

  [17833/21087] intraday_6745.csv.gz  in=445,444,149 out=113,089,395 elapsed=204.5s

  [17834/21087] intraday_6746.csv.gz  in=445,464,686 out=113,089,395 elapsed=204.5s

  [17835/21087] intraday_6747.csv.gz  in=445,478,685 out=113,089,395 elapsed=204.5s

  [17836/21087] intraday_6748.csv.gz  in=445,490,981 out=113,089,395 elapsed=204.5s

  [17837/21087] intraday_6749.csv.gz  in=445,504,316 out=113,089,395 elapsed=204.5s

  [17838/21087] intraday_6751.csv.gz  in=445,516,260 out=113,089,395 elapsed=204.5s

  [17839/21087] intraday_6750.csv.gz  in=445,527,664 out=113,089,395 elapsed=204.5s

  [17840/21087] intraday_6752.csv.gz  in=445,540,555 out=113,089,395 elapsed=204.5s

  [17841/21087] intraday_6753.csv.gz  in=445,554,375 out=113,089,395 elapsed=204.5s

  [17842/21087] intraday_6755.csv.gz  in=445,567,975 out=113,089,395 elapsed=204.6s

  [17843/21087] intraday_6756.csv.gz  in=445,580,868 out=113,089,395 elapsed=204.6s

  [17844/21087] intraday_6757.csv.gz  in=445,593,789 out=113,089,395 elapsed=204.6s

  [17845/21087] intraday_6754.csv.gz  in=445,617,603 out=113,089,395 elapsed=204.6s

  [17846/21087] intraday_6758.csv.gz  in=445,632,457 out=113,089,395 elapsed=204.6s

  [17847/21087] intraday_6759.csv.gz  in=445,644,723 out=113,089,395 elapsed=204.6s

  [17848/21087] intraday_6760.csv.gz  in=445,658,252 out=113,089,395 elapsed=204.6s

  [17849/21087] intraday_6761.csv.gz  in=445,669,922 out=113,089,395 elapsed=204.6s

  [17850/21087] intraday_6762.csv.gz  in=445,681,614 out=113,089,395 elapsed=204.6s

  [17851/21087] intraday_6763.csv.gz  in=445,696,936 out=113,089,395 elapsed=204.6s

  [17852/21087] intraday_6764.csv.gz  in=445,707,070 out=113,089,395 elapsed=204.6s

  [17853/21087] intraday_6765.csv.gz  in=445,723,795 out=113,089,395 elapsed=204.7s

  [17854/21087] intraday_6766.csv.gz  in=445,737,874 out=113,089,395 elapsed=204.7s

  [17855/21087] intraday_6767.csv.gz  in=445,751,488 out=113,089,395 elapsed=204.7s

  [17856/21087] intraday_6768.csv.gz  in=445,765,364 out=113,089,395 elapsed=204.7s

  [17857/21087] intraday_6769.csv.gz  in=445,779,101 out=113,089,395 elapsed=204.7s

  [17858/21087] intraday_6771.csv.gz  in=445,792,519 out=113,089,395 elapsed=204.7s

  [17859/21087] intraday_6770.csv.gz  in=445,825,969 out=113,089,395 elapsed=204.7s

  [17860/21087] intraday_6773.csv.gz  in=445,837,652 out=113,089,395 elapsed=204.7s

  [17861/21087] intraday_6772.csv.gz  in=445,872,552 out=113,089,395 elapsed=204.7s

  [17862/21087] intraday_6774.csv.gz  in=445,884,309 out=113,089,395 elapsed=204.7s

  [17863/21087] intraday_6775.csv.gz  in=445,896,278 out=113,089,395 elapsed=204.7s

  [17864/21087] intraday_6776.csv.gz  in=445,912,760 out=113,089,395 elapsed=204.7s

  [17865/21087] intraday_6777.csv.gz  in=445,925,875 out=113,089,395 elapsed=204.7s

  [17866/21087] intraday_6779.csv.gz  in=445,938,916 out=113,089,395 elapsed=204.8s

  [17867/21087] intraday_6778.csv.gz  in=445,953,558 out=113,089,395 elapsed=204.8s

  [17868/21087] intraday_6780.csv.gz  in=445,965,411 out=113,089,395 elapsed=204.8s

  [17869/21087] intraday_6781.csv.gz  in=445,977,122 out=113,089,395 elapsed=204.8s

  [17870/21087] intraday_6783.csv.gz  in=445,989,980 out=113,089,395 elapsed=204.8s

  [17871/21087] intraday_6782.csv.gz  in=446,003,125 out=113,089,395 elapsed=204.8s

  [17872/21087] intraday_6784.csv.gz  in=446,016,483 out=113,089,395 elapsed=204.8s

  [17873/21087] intraday_6785.csv.gz  in=446,028,328 out=113,089,395 elapsed=204.8s

  [17874/21087] intraday_6786.csv.gz  in=446,041,632 out=113,089,395 elapsed=204.8s

  [17875/21087] intraday_6787.csv.gz  in=446,052,437 out=113,089,395 elapsed=204.8s

  [17876/21087] intraday_6789.csv.gz  in=446,064,581 out=113,089,395 elapsed=204.9s

  [17877/21087] intraday_6788.csv.gz  in=446,078,425 out=113,089,395 elapsed=204.9s

  [17878/21087] intraday_6790.csv.gz  in=446,093,539 out=113,089,395 elapsed=204.9s

  [17879/21087] intraday_6791.csv.gz  in=446,103,764 out=113,089,395 elapsed=204.9s

  [17880/21087] intraday_6793.csv.gz  in=446,115,984 out=113,089,395 elapsed=204.9s

  [17881/21087] intraday_6792.csv.gz  in=446,127,614 out=113,089,395 elapsed=204.9s

  [17882/21087] intraday_6794.csv.gz  in=446,147,457 out=113,089,395 elapsed=204.9s

  [17883/21087] intraday_6795.csv.gz  in=446,163,500 out=113,089,395 elapsed=204.9s

  [17884/21087] intraday_6797.csv.gz  in=446,176,718 out=113,089,395 elapsed=204.9s

  [17885/21087] intraday_6796.csv.gz  in=446,191,896 out=113,089,395 elapsed=204.9s

  [17886/21087] intraday_6798.csv.gz  in=446,205,721 out=113,089,395 elapsed=204.9s

  [17887/21087] intraday_6799.csv.gz  in=446,220,307 out=113,089,395 elapsed=204.9s

  [17888/21087] intraday_6800.csv.gz  in=446,236,694 out=113,089,395 elapsed=205.0s

  [17889/21087] intraday_6801.csv.gz  in=446,250,597 out=113,089,395 elapsed=205.0s

  [17890/21087] intraday_6802.csv.gz  in=446,263,066 out=113,089,395 elapsed=205.0s

  [17891/21087] intraday_6803.csv.gz  in=446,279,578 out=113,089,395 elapsed=205.0s

  [17892/21087] intraday_6804.csv.gz  in=446,295,074 out=113,089,395 elapsed=205.0s

  [17893/21087] intraday_6805.csv.gz  in=446,308,714 out=113,089,395 elapsed=205.0s

  [17894/21087] intraday_6807.csv.gz  in=446,321,634 out=113,089,395 elapsed=205.0s

  [17895/21087] intraday_6806.csv.gz  in=446,335,883 out=113,089,395 elapsed=205.0s

  [17896/21087] intraday_6808.csv.gz  in=446,348,873 out=113,089,395 elapsed=205.0s

  [17897/21087] intraday_6811.csv.gz  in=446,362,321 out=113,089,395 elapsed=205.0s

  [17898/21087] intraday_6809.csv.gz  in=446,377,439 out=113,089,395 elapsed=205.0s

  [17899/21087] intraday_6810.csv.gz  in=446,391,510 out=113,089,395 elapsed=205.0s

  [17900/21087] intraday_6812.csv.gz  in=446,405,045 out=113,089,395 elapsed=205.0s

  [17901/21087] intraday_6814.csv.gz  in=446,419,084 out=113,089,395 elapsed=205.1s

  [17902/21087] intraday_6815.csv.gz  in=446,433,460 out=113,089,395 elapsed=205.1s

  [17903/21087] intraday_6813.csv.gz  in=446,450,136 out=113,089,395 elapsed=205.1s

  [17904/21087] intraday_6816.csv.gz  in=446,461,881 out=113,089,395 elapsed=205.1s

  [17905/21087] intraday_6818.csv.gz  in=446,474,761 out=113,089,395 elapsed=205.1s

  [17906/21087] intraday_6819.csv.gz  in=446,487,740 out=113,089,395 elapsed=205.1s

  [17907/21087] intraday_6817.csv.gz  in=446,506,455 out=113,089,395 elapsed=205.1s

  [17908/21087] intraday_6820.csv.gz  in=446,522,474 out=113,089,395 elapsed=205.1s

  [17909/21087] intraday_6821.csv.gz  in=446,535,937 out=113,089,395 elapsed=205.1s

  [17910/21087] intraday_6822.csv.gz  in=446,548,680 out=113,089,395 elapsed=205.1s

  [17911/21087] intraday_6823.csv.gz  in=446,563,110 out=113,089,395 elapsed=205.1s

  [17912/21087] intraday_6824.csv.gz  in=446,576,237 out=113,089,395 elapsed=205.1s

  [17913/21087] intraday_6825.csv.gz  in=446,590,642 out=113,089,395 elapsed=205.1s

  [17914/21087] intraday_6827.csv.gz  in=446,606,856 out=113,089,395 elapsed=205.2s

  [17915/21087] intraday_6826.csv.gz  in=446,624,191 out=113,089,395 elapsed=205.2s

  [17916/21087] intraday_6828.csv.gz  in=446,637,797 out=113,089,395 elapsed=205.2s

  [17917/21087] intraday_6829.csv.gz  in=446,654,693 out=113,089,395 elapsed=205.2s

  [17918/21087] intraday_6830.csv.gz  in=446,670,057 out=113,089,395 elapsed=205.2s

  [17919/21087] intraday_6832.csv.gz  in=446,681,768 out=113,089,395 elapsed=205.2s

  [17920/21087] intraday_6831.csv.gz  in=446,694,642 out=113,089,395 elapsed=205.2s

  [17921/21087] intraday_6833.csv.gz  in=446,709,425 out=113,089,395 elapsed=205.2s

  [17922/21087] intraday_6834.csv.gz  in=446,720,899 out=113,089,395 elapsed=205.2s

  [17923/21087] intraday_6836.csv.gz  in=446,733,037 out=113,089,395 elapsed=205.2s

  [17924/21087] intraday_6835.csv.gz  in=446,750,319 out=113,089,395 elapsed=205.3s

  [17925/21087] intraday_6837.csv.gz  in=446,767,310 out=113,089,395 elapsed=205.3s

  [17926/21087] intraday_6838.csv.gz  in=446,780,814 out=113,089,395 elapsed=205.3s

  [17927/21087] intraday_6839.csv.gz  in=446,793,820 out=113,089,395 elapsed=205.3s

  [17928/21087] intraday_6841.csv.gz  in=446,806,358 out=113,089,395 elapsed=205.3s

  [17929/21087] intraday_6840.csv.gz  in=446,819,511 out=113,089,395 elapsed=205.3s

  [17930/21087] intraday_6842.csv.gz  in=446,832,127 out=113,089,395 elapsed=205.3s

  [17931/21087] intraday_6845.csv.gz  in=446,847,157 out=113,089,395 elapsed=205.3s

  [17932/21087] intraday_6844.csv.gz  in=446,862,634 out=113,089,395 elapsed=205.3s

  [17933/21087] intraday_6843.csv.gz  in=446,879,542 out=113,089,395 elapsed=205.3s

  [17934/21087] intraday_6846.csv.gz  in=446,901,227 out=113,089,395 elapsed=205.3s

  [17935/21087] intraday_6847.csv.gz  in=446,915,580 out=113,089,395 elapsed=205.3s

  [17936/21087] intraday_6848.csv.gz  in=446,926,740 out=113,089,395 elapsed=205.3s

  [17937/21087] intraday_6850.csv.gz  in=446,938,112 out=113,089,395 elapsed=205.4s

  [17938/21087] intraday_6849.csv.gz  in=446,952,536 out=113,089,395 elapsed=205.4s

  [17939/21087] intraday_6851.csv.gz  in=446,967,634 out=113,089,395 elapsed=205.4s

  [17940/21087] intraday_6852.csv.gz  in=446,977,161 out=113,089,395 elapsed=205.4s

  [17941/21087] intraday_6853.csv.gz  in=446,987,383 out=113,089,395 elapsed=205.4s

  [17942/21087] intraday_6854.csv.gz  in=446,999,786 out=113,089,395 elapsed=205.4s

  [17943/21087] intraday_6857.csv.gz  in=447,013,027 out=113,089,395 elapsed=205.4s

  [17944/21087] intraday_6858.csv.gz  in=447,023,729 out=113,089,395 elapsed=205.4s

  [17945/21087] intraday_6856.csv.gz  in=447,036,740 out=113,089,395 elapsed=205.4s

  [17946/21087] intraday_6855.csv.gz  in=447,084,139 out=113,089,395 elapsed=205.4s

  [17947/21087] intraday_6859.csv.gz  in=447,098,048 out=113,089,395 elapsed=205.4s

  [17948/21087] intraday_6860.csv.gz  in=447,112,350 out=113,089,395 elapsed=205.5s

  [17949/21087] intraday_6861.csv.gz  in=447,128,766 out=113,089,395 elapsed=205.5s

  [17950/21087] intraday_6862.csv.gz  in=447,141,386 out=113,089,395 elapsed=205.5s

  [17951/21087] intraday_6863.csv.gz  in=447,154,137 out=113,089,395 elapsed=205.5s

  [17952/21087] intraday_6865.csv.gz  in=447,169,628 out=113,089,395 elapsed=205.5s

  [17953/21087] intraday_6866.csv.gz  in=447,184,542 out=113,089,395 elapsed=205.5s

  [17954/21087] intraday_6864.csv.gz  in=447,199,480 out=113,089,395 elapsed=205.5s

  [17955/21087] intraday_6867.csv.gz  in=447,213,281 out=113,089,395 elapsed=205.5s

  [17956/21087] intraday_6868.csv.gz  in=447,226,741 out=113,089,395 elapsed=205.5s

  [17957/21087] intraday_6869.csv.gz  in=447,237,103 out=113,089,395 elapsed=205.5s

  [17958/21087] intraday_6870.csv.gz  in=447,246,702 out=113,089,395 elapsed=205.5s

  [17959/21087] intraday_6871.csv.gz  in=447,262,322 out=113,089,395 elapsed=205.5s

  [17960/21087] intraday_6872.csv.gz  in=447,276,509 out=113,089,395 elapsed=205.6s

  [17961/21087] intraday_6873.csv.gz  in=447,287,218 out=113,089,395 elapsed=205.6s

  [17962/21087] intraday_6874.csv.gz  in=447,299,000 out=113,089,395 elapsed=205.6s

  [17963/21087] intraday_6875.csv.gz  in=447,312,248 out=113,089,395 elapsed=205.6s

  [17964/21087] intraday_6876.csv.gz  in=447,324,725 out=113,089,395 elapsed=205.6s

  [17965/21087] intraday_6877.csv.gz  in=447,335,770 out=113,089,395 elapsed=205.6s

  [17966/21087] intraday_6878.csv.gz  in=447,349,244 out=113,089,395 elapsed=205.6s

  [17967/21087] intraday_6879.csv.gz  in=447,362,844 out=113,089,395 elapsed=205.6s

  [17968/21087] intraday_6880.csv.gz  in=447,375,406 out=113,089,395 elapsed=205.6s

  [17969/21087] intraday_6881.csv.gz  in=447,387,392 out=113,089,395 elapsed=205.6s

  [17970/21087] intraday_6883.csv.gz  in=447,400,270 out=113,089,395 elapsed=205.6s

  [17971/21087] intraday_6882.csv.gz  in=447,412,410 out=113,089,395 elapsed=205.6s

  [17972/21087] intraday_6884.csv.gz  in=447,426,460 out=113,089,395 elapsed=205.6s

  [17973/21087] intraday_6885.csv.gz  in=447,444,225 out=113,089,395 elapsed=205.7s

  [17974/21087] intraday_6886.csv.gz  in=447,459,534 out=113,089,395 elapsed=205.7s

  [17975/21087] intraday_6887.csv.gz  in=447,469,952 out=113,089,395 elapsed=205.7s

  [17976/21087] intraday_6888.csv.gz  in=447,484,465 out=113,089,395 elapsed=205.7s

  [17977/21087] intraday_6889.csv.gz  in=447,499,350 out=113,089,395 elapsed=205.7s

  [17978/21087] intraday_6891.csv.gz  in=447,512,547 out=113,089,395 elapsed=205.7s

  [17979/21087] intraday_6890.csv.gz  in=447,524,812 out=113,089,395 elapsed=205.7s

  [17980/21087] intraday_6892.csv.gz  in=447,535,668 out=113,089,395 elapsed=205.7s

  [17981/21087] intraday_6893.csv.gz  in=447,549,192 out=113,089,395 elapsed=205.7s

  [17982/21087] intraday_6895.csv.gz  in=447,560,290 out=113,089,395 elapsed=205.7s

  [17983/21087] intraday_6894.csv.gz  in=447,571,195 out=113,089,395 elapsed=205.7s

  [17984/21087] intraday_6896.csv.gz  in=447,583,504 out=113,089,395 elapsed=205.7s

  [17985/21087] intraday_6897.csv.gz  in=447,597,605 out=113,089,395 elapsed=205.7s

  [17986/21087] intraday_6898.csv.gz  in=447,610,695 out=113,089,395 elapsed=205.8s

  [17987/21087] intraday_6899.csv.gz  in=447,624,037 out=113,089,395 elapsed=205.8s

  [17988/21087] intraday_6900.csv.gz  in=447,636,211 out=113,089,395 elapsed=205.8s

  [17989/21087] intraday_6901.csv.gz  in=447,647,894 out=113,089,395 elapsed=205.8s

  [17990/21087] intraday_6902.csv.gz  in=447,662,038 out=113,089,395 elapsed=205.8s

  [17991/21087] intraday_6903.csv.gz  in=447,673,870 out=113,089,395 elapsed=205.8s

  [17992/21087] intraday_6904.csv.gz  in=447,686,752 out=113,089,395 elapsed=205.8s

  [17993/21087] intraday_6905.csv.gz  in=447,698,078 out=113,089,395 elapsed=205.8s

  [17994/21087] intraday_6906.csv.gz  in=447,708,397 out=113,089,395 elapsed=205.8s

  [17995/21087] intraday_6908.csv.gz  in=447,717,933 out=113,089,395 elapsed=205.8s

  [17996/21087] intraday_6907.csv.gz  in=447,734,577 out=113,089,395 elapsed=205.8s

  [17997/21087] intraday_6909.csv.gz  in=447,751,373 out=113,089,395 elapsed=205.8s

  [17998/21087] intraday_6910.csv.gz  in=447,765,014 out=113,089,395 elapsed=205.8s

  [17999/21087] intraday_6912.csv.gz  in=447,777,140 out=113,089,395 elapsed=205.9s

  [18000/21087] intraday_6911.csv.gz  in=447,791,074 out=113,089,395 elapsed=205.9s

  [18001/21087] intraday_6913.csv.gz  in=447,804,818 out=113,089,395 elapsed=205.9s

  [18002/21087] intraday_6914.csv.gz  in=447,818,738 out=113,089,395 elapsed=205.9s

  [18003/21087] intraday_6915.csv.gz  in=447,832,176 out=113,089,395 elapsed=205.9s

  [18004/21087] intraday_6916.csv.gz  in=447,847,124 out=113,089,395 elapsed=205.9s

  [18005/21087] intraday_6917.csv.gz  in=447,858,575 out=113,089,395 elapsed=205.9s

  [18006/21087] intraday_6918.csv.gz  in=447,869,699 out=113,089,395 elapsed=205.9s

  [18007/21087] intraday_6919.csv.gz  in=447,880,935 out=113,089,395 elapsed=205.9s

  [18008/21087] intraday_6920.csv.gz  in=447,896,019 out=113,089,395 elapsed=205.9s

  [18009/21087] intraday_6921.csv.gz  in=447,909,080 out=113,089,395 elapsed=205.9s

  [18010/21087] intraday_6922.csv.gz  in=447,923,370 out=113,089,395 elapsed=205.9s

  [18011/21087] intraday_6923.csv.gz  in=447,935,644 out=113,089,395 elapsed=206.0s

  [18012/21087] intraday_6924.csv.gz  in=447,947,133 out=113,089,395 elapsed=206.0s

  [18013/21087] intraday_6925.csv.gz  in=447,960,098 out=113,089,395 elapsed=206.0s

  [18014/21087] intraday_6927.csv.gz  in=447,972,594 out=113,089,395 elapsed=206.0s

  [18015/21087] intraday_6926.csv.gz  in=447,985,067 out=113,089,395 elapsed=206.0s

  [18016/21087] intraday_6928.csv.gz  in=447,999,514 out=113,089,395 elapsed=206.0s

  [18017/21087] intraday_6929.csv.gz  in=448,011,443 out=113,089,395 elapsed=206.0s

  [18018/21087] intraday_6930.csv.gz  in=448,024,408 out=113,089,395 elapsed=206.0s

  [18019/21087] intraday_6931.csv.gz  in=448,035,421 out=113,089,395 elapsed=206.0s

  [18020/21087] intraday_6932.csv.gz  in=448,049,391 out=113,089,395 elapsed=206.0s

  [18021/21087] intraday_6933.csv.gz  in=448,061,413 out=113,089,395 elapsed=206.0s

  [18022/21087] intraday_6935.csv.gz  in=448,071,112 out=113,089,395 elapsed=206.0s

  [18023/21087] intraday_6934.csv.gz  in=448,084,993 out=113,089,395 elapsed=206.0s

  [18024/21087] intraday_6936.csv.gz  in=448,096,693 out=113,089,395 elapsed=206.0s

  [18025/21087] intraday_6937.csv.gz  in=448,110,035 out=113,089,395 elapsed=206.1s

  [18026/21087] intraday_6938.csv.gz  in=448,126,758 out=113,089,395 elapsed=206.1s

  [18027/21087] intraday_6939.csv.gz  in=448,142,377 out=113,089,395 elapsed=206.1s

  [18028/21087] intraday_6940.csv.gz  in=448,156,134 out=113,089,395 elapsed=206.1s

  [18029/21087] intraday_6941.csv.gz  in=448,169,151 out=113,089,395 elapsed=206.1s

  [18030/21087] intraday_6942.csv.gz  in=448,180,955 out=113,089,395 elapsed=206.1s

  [18031/21087] intraday_6943.csv.gz  in=448,195,295 out=113,089,395 elapsed=206.1s

  [18032/21087] intraday_6944.csv.gz  in=448,212,857 out=113,089,395 elapsed=206.1s

  [18033/21087] intraday_6945.csv.gz  in=448,244,369 out=113,089,395 elapsed=206.1s

  [18034/21087] intraday_6946.csv.gz  in=448,256,040 out=113,089,395 elapsed=206.1s

  [18035/21087] intraday_6947.csv.gz  in=448,271,496 out=113,089,395 elapsed=206.1s

  [18036/21087] intraday_6948.csv.gz  in=448,286,717 out=113,089,395 elapsed=206.1s

  [18037/21087] intraday_6949.csv.gz  in=448,301,196 out=113,089,395 elapsed=206.2s

  [18038/21087] intraday_6950.csv.gz  in=448,314,766 out=113,089,395 elapsed=206.2s

  [18039/21087] intraday_6951.csv.gz  in=448,327,851 out=113,089,395 elapsed=206.2s

  [18040/21087] intraday_6952.csv.gz  in=448,340,168 out=113,089,395 elapsed=206.2s

  [18041/21087] intraday_6953.csv.gz  in=448,354,438 out=113,089,395 elapsed=206.2s

  [18042/21087] intraday_6954.csv.gz  in=448,368,712 out=113,089,395 elapsed=206.2s

  [18043/21087] intraday_6955.csv.gz  in=448,379,948 out=113,089,395 elapsed=206.2s

  [18044/21087] intraday_6958.csv.gz  in=448,393,867 out=113,089,395 elapsed=206.2s

  [18045/21087] intraday_6956.csv.gz  in=448,406,987 out=113,089,395 elapsed=206.2s

  [18046/21087] intraday_6957.csv.gz  in=448,422,720 out=113,089,395 elapsed=206.2s

  [18047/21087] intraday_6959.csv.gz  in=448,436,619 out=113,089,395 elapsed=206.2s

  [18048/21087] intraday_6960.csv.gz  in=448,450,402 out=113,089,395 elapsed=206.3s

  [18049/21087] intraday_6962.csv.gz  in=448,463,035 out=113,089,395 elapsed=206.3s

  [18050/21087] intraday_6961.csv.gz  in=448,479,148 out=113,089,395 elapsed=206.3s

  [18051/21087] intraday_6963.csv.gz  in=448,492,169 out=113,089,395 elapsed=206.3s

  [18052/21087] intraday_6965.csv.gz  in=448,506,218 out=113,089,395 elapsed=206.3s

  [18053/21087] intraday_6966.csv.gz  in=448,517,185 out=113,089,395 elapsed=206.3s

  [18054/21087] intraday_6964.csv.gz  in=448,532,596 out=113,089,395 elapsed=206.3s

  [18055/21087] intraday_6967.csv.gz  in=448,547,793 out=113,089,395 elapsed=206.3s

  [18056/21087] intraday_6968.csv.gz  in=448,560,174 out=113,089,395 elapsed=206.3s

  [18057/21087] intraday_6969.csv.gz  in=448,574,157 out=113,089,395 elapsed=206.3s

  [18058/21087] intraday_6971.csv.gz  in=448,590,629 out=113,089,395 elapsed=206.3s

  [18059/21087] intraday_6970.csv.gz  in=448,606,347 out=113,089,395 elapsed=206.3s

  [18060/21087] intraday_6972.csv.gz  in=448,621,558 out=113,089,395 elapsed=206.3s

  [18061/21087] intraday_6974.csv.gz  in=448,634,236 out=113,089,395 elapsed=206.4s

  [18062/21087] intraday_6973.csv.gz  in=448,648,340 out=113,089,395 elapsed=206.4s

  [18063/21087] intraday_6975.csv.gz  in=448,661,224 out=113,089,395 elapsed=206.4s

  [18064/21087] intraday_6976.csv.gz  in=448,671,976 out=113,089,395 elapsed=206.4s

  [18065/21087] intraday_6977.csv.gz  in=448,687,012 out=113,089,395 elapsed=206.4s

  [18066/21087] intraday_6978.csv.gz  in=448,698,614 out=113,089,395 elapsed=206.4s

  [18067/21087] intraday_6979.csv.gz  in=448,712,406 out=113,089,395 elapsed=206.4s

  [18068/21087] intraday_6980.csv.gz  in=448,724,996 out=113,089,395 elapsed=206.4s

  [18069/21087] intraday_6981.csv.gz  in=448,740,485 out=113,089,395 elapsed=206.4s

  [18070/21087] intraday_6982.csv.gz  in=448,752,761 out=113,089,395 elapsed=206.4s

  [18071/21087] intraday_6983.csv.gz  in=448,764,710 out=113,089,395 elapsed=206.4s

  [18072/21087] intraday_6984.csv.gz  in=448,777,008 out=113,089,395 elapsed=206.4s

  [18073/21087] intraday_6985.csv.gz  in=448,790,382 out=113,089,395 elapsed=206.4s

  [18074/21087] intraday_6986.csv.gz  in=448,801,575 out=113,089,395 elapsed=206.5s

  [18075/21087] intraday_6987.csv.gz  in=448,817,131 out=113,089,395 elapsed=206.5s

  [18076/21087] intraday_6988.csv.gz  in=448,831,561 out=113,089,395 elapsed=206.5s

  [18077/21087] intraday_6989.csv.gz  in=448,846,482 out=113,089,395 elapsed=206.5s

  [18078/21087] intraday_6991.csv.gz  in=448,857,784 out=113,089,395 elapsed=206.5s

  [18079/21087] intraday_6992.csv.gz  in=448,869,694 out=113,089,395 elapsed=206.5s

  [18080/21087] intraday_6990.csv.gz  in=448,909,265 out=113,089,395 elapsed=206.5s

  [18081/21087] intraday_6993.csv.gz  in=448,922,880 out=113,089,395 elapsed=206.5s

  [18082/21087] intraday_6994.csv.gz  in=448,935,263 out=113,089,395 elapsed=206.5s

  [18083/21087] intraday_6995.csv.gz  in=448,947,430 out=113,089,395 elapsed=206.5s

  [18084/21087] intraday_6996.csv.gz  in=448,957,096 out=113,089,395 elapsed=206.5s

  [18085/21087] intraday_6997.csv.gz  in=448,970,452 out=113,089,395 elapsed=206.5s

  [18086/21087] intraday_6998.csv.gz  in=448,977,745 out=113,089,395 elapsed=206.5s

  [18087/21087] intraday_7000.csv.gz  in=448,990,074 out=113,089,395 elapsed=206.6s

  [18088/21087] intraday_6999.csv.gz  in=449,006,613 out=113,089,395 elapsed=206.6s

  [18089/21087] intraday_7002.csv.gz  in=449,017,045 out=113,089,395 elapsed=206.6s

  [18090/21087] intraday_7001.csv.gz  in=449,030,622 out=113,089,395 elapsed=206.6s

  [18091/21087] intraday_7003.csv.gz  in=449,044,282 out=113,089,395 elapsed=206.6s

  [18092/21087] intraday_7006.csv.gz  in=449,056,150 out=113,089,395 elapsed=206.6s

  [18093/21087] intraday_7005.csv.gz  in=449,073,006 out=113,089,395 elapsed=206.6s

  [18094/21087] intraday_7004.csv.gz  in=449,088,158 out=113,089,395 elapsed=206.6s

  [18095/21087] intraday_7007.csv.gz  in=449,101,658 out=113,089,395 elapsed=206.6s

  [18096/21087] intraday_7008.csv.gz  in=449,115,871 out=113,089,395 elapsed=206.6s

  [18097/21087] intraday_7010.csv.gz  in=449,131,106 out=113,089,395 elapsed=206.6s

  [18098/21087] intraday_7009.csv.gz  in=449,147,434 out=113,089,395 elapsed=206.6s

  [18099/21087] intraday_7011.csv.gz  in=449,160,065 out=113,089,395 elapsed=206.6s

  [18100/21087] intraday_7012.csv.gz  in=449,173,972 out=113,089,395 elapsed=206.7s

  [18101/21087] intraday_7014.csv.gz  in=449,184,086 out=113,089,395 elapsed=206.7s

  [18102/21087] intraday_7013.csv.gz  in=449,193,572 out=113,089,395 elapsed=206.7s

  [18103/21087] intraday_7015.csv.gz  in=449,208,800 out=113,089,395 elapsed=206.7s

  [18104/21087] intraday_7016.csv.gz  in=449,222,850 out=113,089,395 elapsed=206.7s

  [18105/21087] intraday_7017.csv.gz  in=449,234,955 out=113,089,395 elapsed=206.7s

  [18106/21087] intraday_7018.csv.gz  in=449,246,264 out=113,089,395 elapsed=206.7s

  [18107/21087] intraday_7019.csv.gz  in=449,258,430 out=113,089,395 elapsed=206.7s

  [18108/21087] intraday_7020.csv.gz  in=449,271,089 out=113,089,395 elapsed=206.7s

  [18109/21087] intraday_7021.csv.gz  in=449,283,029 out=113,089,395 elapsed=206.7s

  [18110/21087] intraday_7022.csv.gz  in=449,296,225 out=113,089,395 elapsed=206.7s

  [18111/21087] intraday_7023.csv.gz  in=449,309,561 out=113,089,395 elapsed=206.7s

  [18112/21087] intraday_7024.csv.gz  in=449,323,672 out=113,089,395 elapsed=206.8s

  [18113/21087] intraday_7025.csv.gz  in=449,335,218 out=113,089,395 elapsed=206.8s

  [18114/21087] intraday_7026.csv.gz  in=449,348,195 out=113,089,395 elapsed=206.8s

  [18115/21087] intraday_7027.csv.gz  in=449,359,480 out=113,089,395 elapsed=206.8s

  [18116/21087] intraday_7028.csv.gz  in=449,374,033 out=113,089,395 elapsed=206.8s

  [18117/21087] intraday_7029.csv.gz  in=449,392,236 out=113,089,395 elapsed=206.8s

  [18118/21087] intraday_7030.csv.gz  in=449,407,001 out=113,089,395 elapsed=206.8s

  [18119/21087] intraday_7031.csv.gz  in=449,417,992 out=113,089,395 elapsed=206.8s

  [18120/21087] intraday_7032.csv.gz  in=449,433,680 out=113,089,395 elapsed=206.8s

  [18121/21087] intraday_7034.csv.gz  in=449,446,117 out=113,089,395 elapsed=206.8s

  [18122/21087] intraday_7033.csv.gz  in=449,461,247 out=113,089,395 elapsed=206.8s

  [18123/21087] intraday_7035.csv.gz  in=449,473,721 out=113,089,395 elapsed=206.8s

  [18124/21087] intraday_7036.csv.gz  in=449,485,305 out=113,089,395 elapsed=206.8s

  [18125/21087] intraday_7037.csv.gz  in=449,498,143 out=113,089,395 elapsed=206.9s

  [18126/21087] intraday_7038.csv.gz  in=449,508,563 out=113,089,395 elapsed=206.9s

  [18127/21087] intraday_7039.csv.gz  in=449,520,024 out=113,089,395 elapsed=206.9s

  [18128/21087] intraday_7040.csv.gz  in=449,532,331 out=113,089,395 elapsed=206.9s

  [18129/21087] intraday_7042.csv.gz  in=449,546,010 out=113,089,395 elapsed=206.9s

  [18130/21087] intraday_7041.csv.gz  in=449,558,765 out=113,089,395 elapsed=206.9s

  [18131/21087] intraday_7043.csv.gz  in=449,572,110 out=113,089,395 elapsed=206.9s

  [18132/21087] intraday_7044.csv.gz  in=449,584,835 out=113,089,395 elapsed=206.9s

  [18133/21087] intraday_7045.csv.gz  in=449,597,090 out=113,089,395 elapsed=206.9s

  [18134/21087] intraday_7046.csv.gz  in=449,609,407 out=113,089,395 elapsed=206.9s

  [18135/21087] intraday_7047.csv.gz  in=449,623,367 out=113,089,395 elapsed=206.9s

  [18136/21087] intraday_7048.csv.gz  in=449,635,863 out=113,089,395 elapsed=206.9s

  [18137/21087] intraday_7049.csv.gz  in=449,647,432 out=113,089,395 elapsed=206.9s

  [18138/21087] intraday_7050.csv.gz  in=449,657,567 out=113,089,395 elapsed=207.0s

  [18139/21087] intraday_7052.csv.gz  in=449,667,474 out=113,089,395 elapsed=207.0s

  [18140/21087] intraday_7051.csv.gz  in=449,682,844 out=113,089,395 elapsed=207.0s

  [18141/21087] intraday_7053.csv.gz  in=449,697,582 out=113,089,395 elapsed=207.0s

  [18142/21087] intraday_7054.csv.gz  in=449,712,737 out=113,089,395 elapsed=207.0s

  [18143/21087] intraday_7055.csv.gz  in=449,725,944 out=113,089,395 elapsed=207.0s

  [18144/21087] intraday_7056.csv.gz  in=449,738,840 out=113,089,395 elapsed=207.0s

  [18145/21087] intraday_7057.csv.gz  in=449,751,849 out=113,089,395 elapsed=207.0s

  [18146/21087] intraday_7058.csv.gz  in=449,765,688 out=113,089,395 elapsed=207.0s

  [18147/21087] intraday_7059.csv.gz  in=449,779,630 out=113,089,395 elapsed=207.0s

  [18148/21087] intraday_7060.csv.gz  in=449,793,146 out=113,089,395 elapsed=207.0s

  [18149/21087] intraday_7061.csv.gz  in=449,805,248 out=113,089,395 elapsed=207.0s

  [18150/21087] intraday_7062.csv.gz  in=449,816,926 out=113,089,395 elapsed=207.1s

  [18151/21087] intraday_7063.csv.gz  in=449,828,245 out=113,089,395 elapsed=207.1s

  [18152/21087] intraday_7064.csv.gz  in=449,843,340 out=113,089,395 elapsed=207.1s

  [18153/21087] intraday_7065.csv.gz  in=449,856,278 out=113,089,395 elapsed=207.1s

  [18154/21087] intraday_7066.csv.gz  in=449,870,380 out=113,089,395 elapsed=207.1s

  [18155/21087] intraday_7067.csv.gz  in=449,884,010 out=113,089,395 elapsed=207.1s

  [18156/21087] intraday_7068.csv.gz  in=449,905,122 out=113,089,395 elapsed=207.1s

  [18157/21087] intraday_7069.csv.gz  in=449,916,592 out=113,089,395 elapsed=207.1s

  [18158/21087] intraday_7070.csv.gz  in=449,929,464 out=113,089,395 elapsed=207.1s

  [18159/21087] intraday_7071.csv.gz  in=449,942,370 out=113,089,395 elapsed=207.1s

  [18160/21087] intraday_7073.csv.gz  in=449,953,759 out=113,089,395 elapsed=207.1s

  [18161/21087] intraday_7072.csv.gz  in=449,968,286 out=113,089,395 elapsed=207.1s

  [18162/21087] intraday_7074.csv.gz  in=449,981,410 out=113,089,395 elapsed=207.2s

  [18163/21087] intraday_7075.csv.gz  in=449,992,163 out=113,089,395 elapsed=207.2s

  [18164/21087] intraday_7076.csv.gz  in=450,006,052 out=113,089,395 elapsed=207.2s

  [18165/21087] intraday_7078.csv.gz  in=450,018,663 out=113,089,395 elapsed=207.2s

  [18166/21087] intraday_7079.csv.gz  in=450,034,297 out=113,089,395 elapsed=207.2s

  [18167/21087] intraday_7077.csv.gz  in=450,056,958 out=113,089,395 elapsed=207.2s

  [18168/21087] intraday_7080.csv.gz  in=450,078,854 out=113,089,395 elapsed=207.2s

  [18169/21087] intraday_7081.csv.gz  in=450,090,295 out=113,089,395 elapsed=207.2s

  [18170/21087] intraday_7082.csv.gz  in=450,107,874 out=113,089,395 elapsed=207.2s

  [18171/21087] intraday_7083.csv.gz  in=450,124,781 out=113,089,395 elapsed=207.2s

  [18172/21087] intraday_7085.csv.gz  in=450,136,791 out=113,089,395 elapsed=207.2s

  [18173/21087] intraday_7084.csv.gz  in=450,151,196 out=113,089,395 elapsed=207.2s

  [18174/21087] intraday_7086.csv.gz  in=450,162,675 out=113,089,395 elapsed=207.2s

  [18175/21087] intraday_7088.csv.gz  in=450,175,653 out=113,089,395 elapsed=207.3s

  [18176/21087] intraday_7087.csv.gz  in=450,191,174 out=113,089,395 elapsed=207.3s

  [18177/21087] intraday_7089.csv.gz  in=450,207,195 out=113,089,395 elapsed=207.3s

  [18178/21087] intraday_7090.csv.gz  in=450,220,079 out=113,089,395 elapsed=207.3s

  [18179/21087] intraday_7092.csv.gz  in=450,235,225 out=113,089,395 elapsed=207.3s

  [18180/21087] intraday_7091.csv.gz  in=450,249,833 out=113,089,395 elapsed=207.3s

  [18181/21087] intraday_7093.csv.gz  in=450,262,890 out=113,089,395 elapsed=207.3s

  [18182/21087] intraday_7094.csv.gz  in=450,278,473 out=113,089,395 elapsed=207.3s

  [18183/21087] intraday_7096.csv.gz  in=450,292,285 out=113,089,395 elapsed=207.3s

  [18184/21087] intraday_7097.csv.gz  in=450,306,190 out=113,089,395 elapsed=207.3s

  [18185/21087] intraday_7098.csv.gz  in=450,319,682 out=113,089,395 elapsed=207.3s

  [18186/21087] intraday_7095.csv.gz  in=450,345,924 out=113,089,395 elapsed=207.3s

  [18187/21087] intraday_7099.csv.gz  in=450,358,117 out=113,089,395 elapsed=207.4s

  [18188/21087] intraday_7100.csv.gz  in=450,371,951 out=113,089,395 elapsed=207.4s

  [18189/21087] intraday_7101.csv.gz  in=450,388,890 out=113,089,395 elapsed=207.4s

  [18190/21087] intraday_7102.csv.gz  in=450,404,616 out=113,089,395 elapsed=207.4s

  [18191/21087] intraday_7103.csv.gz  in=450,416,204 out=113,089,395 elapsed=207.4s

  [18192/21087] intraday_7104.csv.gz  in=450,429,129 out=113,089,395 elapsed=207.4s

  [18193/21087] intraday_7106.csv.gz  in=450,440,961 out=113,089,395 elapsed=207.4s

  [18194/21087] intraday_7107.csv.gz  in=450,453,203 out=113,089,395 elapsed=207.4s

  [18195/21087] intraday_7105.csv.gz  in=450,471,348 out=113,089,395 elapsed=207.4s

  [18196/21087] intraday_7108.csv.gz  in=450,487,265 out=113,089,395 elapsed=207.4s

  [18197/21087] intraday_7109.csv.gz  in=450,502,322 out=113,089,395 elapsed=207.4s

  [18198/21087] intraday_7110.csv.gz  in=450,515,066 out=113,089,395 elapsed=207.4s

  [18199/21087] intraday_7111.csv.gz  in=450,528,154 out=113,089,395 elapsed=207.4s

  [18200/21087] intraday_7112.csv.gz  in=450,540,785 out=113,089,395 elapsed=207.4s

  [18201/21087] intraday_7113.csv.gz  in=450,552,737 out=113,089,395 elapsed=207.5s

  [18202/21087] intraday_7114.csv.gz  in=450,570,527 out=113,089,395 elapsed=207.5s

  [18203/21087] intraday_7115.csv.gz  in=450,584,811 out=113,089,395 elapsed=207.5s

  [18204/21087] intraday_7116.csv.gz  in=450,600,026 out=113,089,395 elapsed=207.5s

  [18205/21087] intraday_7117.csv.gz  in=450,616,182 out=113,089,395 elapsed=207.5s

  [18206/21087] intraday_7118.csv.gz  in=450,629,976 out=113,089,395 elapsed=207.5s

  [18207/21087] intraday_7119.csv.gz  in=450,641,982 out=113,089,395 elapsed=207.5s

  [18208/21087] intraday_7120.csv.gz  in=450,654,422 out=113,089,395 elapsed=207.5s

  [18209/21087] intraday_7121.csv.gz  in=450,667,683 out=113,089,395 elapsed=207.5s

  [18210/21087] intraday_7122.csv.gz  in=450,679,542 out=113,089,395 elapsed=207.5s

  [18211/21087] intraday_7124.csv.gz  in=450,692,974 out=113,089,395 elapsed=207.5s

  [18212/21087] intraday_7125.csv.gz  in=450,707,004 out=113,089,395 elapsed=207.5s

  [18213/21087] intraday_7123.csv.gz  in=450,742,476 out=113,089,395 elapsed=207.6s

  [18214/21087] intraday_7126.csv.gz  in=450,757,430 out=113,089,395 elapsed=207.6s

  [18215/21087] intraday_7127.csv.gz  in=450,770,164 out=113,089,395 elapsed=207.6s

  [18216/21087] intraday_7128.csv.gz  in=450,782,097 out=113,089,395 elapsed=207.6s

  [18217/21087] intraday_7129.csv.gz  in=450,796,060 out=113,089,395 elapsed=207.6s

  [18218/21087] intraday_7130.csv.gz  in=450,808,479 out=113,089,395 elapsed=207.6s

  [18219/21087] intraday_7131.csv.gz  in=450,820,785 out=113,089,395 elapsed=207.6s

  [18220/21087] intraday_7132.csv.gz  in=450,835,558 out=113,089,395 elapsed=207.6s

  [18221/21087] intraday_7133.csv.gz  in=450,850,856 out=113,089,395 elapsed=207.6s

  [18222/21087] intraday_7134.csv.gz  in=450,865,508 out=113,089,395 elapsed=207.6s

  [18223/21087] intraday_7135.csv.gz  in=450,879,304 out=113,089,395 elapsed=207.6s

  [18224/21087] intraday_7136.csv.gz  in=450,890,340 out=113,089,395 elapsed=207.6s

  [18225/21087] intraday_7137.csv.gz  in=450,903,935 out=113,089,395 elapsed=207.7s

  [18226/21087] intraday_7138.csv.gz  in=450,915,950 out=113,089,395 elapsed=207.7s

  [18227/21087] intraday_7140.csv.gz  in=450,925,632 out=113,089,395 elapsed=207.7s

  [18228/21087] intraday_7139.csv.gz  in=450,940,642 out=113,089,395 elapsed=207.7s

  [18229/21087] intraday_7141.csv.gz  in=450,950,352 out=113,089,395 elapsed=207.7s

  [18230/21087] intraday_7143.csv.gz  in=450,950,993 out=113,089,395 elapsed=207.7s

  [18231/21087] intraday_7142.csv.gz  in=450,964,749 out=113,089,395 elapsed=207.7s

  [18232/21087] intraday_7144.csv.gz  in=450,981,626 out=113,089,395 elapsed=207.7s

  [18233/21087] intraday_7145.csv.gz  in=450,996,117 out=113,089,395 elapsed=207.7s

  [18234/21087] intraday_7146.csv.gz  in=451,009,211 out=113,089,395 elapsed=207.7s

  [18235/21087] intraday_7147.csv.gz  in=451,020,505 out=113,089,395 elapsed=207.7s

  [18236/21087] intraday_7148.csv.gz  in=451,032,127 out=113,089,395 elapsed=207.7s

  [18237/21087] intraday_7149.csv.gz  in=451,046,693 out=113,089,395 elapsed=207.7s

  [18238/21087] intraday_7150.csv.gz  in=451,061,992 out=113,089,395 elapsed=207.8s

  [18239/21087] intraday_7151.csv.gz  in=451,073,985 out=113,089,395 elapsed=207.8s

  [18240/21087] intraday_7152.csv.gz  in=451,087,208 out=113,089,395 elapsed=207.8s

  [18241/21087] intraday_7153.csv.gz  in=451,100,682 out=113,089,395 elapsed=207.8s

  [18242/21087] intraday_7154.csv.gz  in=451,120,494 out=113,089,395 elapsed=207.8s

  [18243/21087] intraday_7155.csv.gz  in=451,136,483 out=113,089,395 elapsed=207.8s

  [18244/21087] intraday_7156.csv.gz  in=451,149,460 out=113,089,395 elapsed=207.8s

  [18245/21087] intraday_7157.csv.gz  in=451,162,416 out=113,089,395 elapsed=207.8s

  [18246/21087] intraday_7158.csv.gz  in=451,172,119 out=113,089,395 elapsed=207.8s

  [18247/21087] intraday_7159.csv.gz  in=451,181,012 out=113,089,395 elapsed=207.8s

  [18248/21087] intraday_7160.csv.gz  in=451,195,941 out=113,089,395 elapsed=207.8s

  [18249/21087] intraday_7161.csv.gz  in=451,209,278 out=113,089,395 elapsed=207.8s

  [18250/21087] intraday_7162.csv.gz  in=451,221,733 out=113,089,395 elapsed=207.8s

  [18251/21087] intraday_7163.csv.gz  in=451,232,271 out=113,089,395 elapsed=207.9s

  [18252/21087] intraday_7164.csv.gz  in=451,245,178 out=113,089,395 elapsed=207.9s

  [18253/21087] intraday_7165.csv.gz  in=451,258,836 out=113,089,395 elapsed=207.9s

  [18254/21087] intraday_7166.csv.gz  in=451,269,508 out=113,089,395 elapsed=207.9s

  [18255/21087] intraday_7167.csv.gz  in=451,282,049 out=113,089,395 elapsed=207.9s

  [18256/21087] intraday_7168.csv.gz  in=451,295,102 out=113,089,395 elapsed=207.9s

  [18257/21087] intraday_7169.csv.gz  in=451,308,499 out=113,089,395 elapsed=207.9s

  [18258/21087] intraday_7170.csv.gz  in=451,319,081 out=113,089,395 elapsed=207.9s

  [18259/21087] intraday_7171.csv.gz  in=451,334,064 out=113,089,395 elapsed=207.9s

  [18260/21087] intraday_7172.csv.gz  in=451,345,361 out=113,089,395 elapsed=207.9s

  [18261/21087] intraday_7173.csv.gz  in=451,358,689 out=113,089,395 elapsed=207.9s

  [18262/21087] intraday_7174.csv.gz  in=451,374,993 out=113,089,395 elapsed=208.0s

  [18263/21087] intraday_7175.csv.gz  in=451,388,561 out=113,089,395 elapsed=208.0s

  [18264/21087] intraday_7176.csv.gz  in=451,400,204 out=113,089,395 elapsed=208.0s

  [18265/21087] intraday_7177.csv.gz  in=451,411,861 out=113,089,395 elapsed=208.0s

  [18266/21087] intraday_7178.csv.gz  in=451,425,834 out=113,089,395 elapsed=208.0s

  [18267/21087] intraday_7179.csv.gz  in=451,436,902 out=113,089,395 elapsed=208.0s

  [18268/21087] intraday_7180.csv.gz  in=451,451,181 out=113,089,395 elapsed=208.0s

  [18269/21087] intraday_7181.csv.gz  in=451,460,940 out=113,089,395 elapsed=208.0s

  [18270/21087] intraday_7182.csv.gz  in=451,472,762 out=113,089,395 elapsed=208.0s

  [18271/21087] intraday_7183.csv.gz  in=451,483,786 out=113,089,395 elapsed=208.0s

  [18272/21087] intraday_7184.csv.gz  in=451,495,108 out=113,089,395 elapsed=208.0s

  [18273/21087] intraday_7185.csv.gz  in=451,507,495 out=113,089,395 elapsed=208.0s

  [18274/21087] intraday_7186.csv.gz  in=451,522,512 out=113,089,395 elapsed=208.0s

  [18275/21087] intraday_7187.csv.gz  in=451,533,915 out=113,089,395 elapsed=208.0s

  [18276/21087] intraday_7188.csv.gz  in=451,548,156 out=113,089,395 elapsed=208.1s

  [18277/21087] intraday_7189.csv.gz  in=451,560,808 out=113,089,395 elapsed=208.1s

  [18278/21087] intraday_7190.csv.gz  in=451,571,611 out=113,089,395 elapsed=208.1s

  [18279/21087] intraday_7191.csv.gz  in=451,585,151 out=113,089,395 elapsed=208.1s

  [18280/21087] intraday_7192.csv.gz  in=451,597,323 out=113,089,395 elapsed=208.1s

  [18281/21087] intraday_7193.csv.gz  in=451,609,045 out=113,089,395 elapsed=208.1s

  [18282/21087] intraday_7194.csv.gz  in=451,619,401 out=113,089,395 elapsed=208.1s

  [18283/21087] intraday_7195.csv.gz  in=451,630,440 out=113,089,395 elapsed=208.1s

  [18284/21087] intraday_7196.csv.gz  in=451,644,065 out=113,089,395 elapsed=208.1s

  [18285/21087] intraday_7197.csv.gz  in=451,655,387 out=113,089,395 elapsed=208.1s

  [18286/21087] intraday_7198.csv.gz  in=451,669,758 out=113,089,395 elapsed=208.1s

  [18287/21087] intraday_7199.csv.gz  in=451,683,506 out=113,089,395 elapsed=208.1s

  [18288/21087] intraday_7200.csv.gz  in=451,696,702 out=113,089,395 elapsed=208.2s

  [18289/21087] intraday_7201.csv.gz  in=451,707,379 out=113,089,395 elapsed=208.2s

  [18290/21087] intraday_7202.csv.gz  in=451,719,524 out=113,089,395 elapsed=208.2s

  [18291/21087] intraday_7203.csv.gz  in=451,734,004 out=113,089,395 elapsed=208.2s

  [18292/21087] intraday_7204.csv.gz  in=451,747,093 out=113,089,395 elapsed=208.2s

  [18293/21087] intraday_7205.csv.gz  in=451,759,872 out=113,089,395 elapsed=208.2s

  [18294/21087] intraday_7206.csv.gz  in=451,771,284 out=113,089,395 elapsed=208.2s

  [18295/21087] intraday_7207.csv.gz  in=451,781,070 out=113,089,395 elapsed=208.2s

  [18296/21087] intraday_7208.csv.gz  in=451,791,843 out=113,089,395 elapsed=208.2s

  [18297/21087] intraday_7210.csv.gz  in=451,804,989 out=113,089,395 elapsed=208.2s

  [18298/21087] intraday_7209.csv.gz  in=451,820,865 out=113,089,395 elapsed=208.2s

  [18299/21087] intraday_7211.csv.gz  in=451,834,219 out=113,089,395 elapsed=208.2s

  [18300/21087] intraday_7212.csv.gz  in=451,846,478 out=113,089,395 elapsed=208.2s

  [18301/21087] intraday_7214.csv.gz  in=451,859,189 out=113,089,395 elapsed=208.3s

  [18302/21087] intraday_7213.csv.gz  in=451,876,525 out=113,089,395 elapsed=208.3s

  [18303/21087] intraday_7215.csv.gz  in=451,888,241 out=113,089,395 elapsed=208.3s

  [18304/21087] intraday_7216.csv.gz  in=451,899,707 out=113,089,395 elapsed=208.3s

  [18305/21087] intraday_7217.csv.gz  in=451,913,000 out=113,089,395 elapsed=208.3s

  [18306/21087] intraday_7218.csv.gz  in=451,924,707 out=113,089,395 elapsed=208.3s

  [18307/21087] intraday_7219.csv.gz  in=451,938,286 out=113,089,395 elapsed=208.3s

  [18308/21087] intraday_7220.csv.gz  in=451,951,462 out=113,089,395 elapsed=208.3s

  [18309/21087] intraday_7222.csv.gz  in=451,962,091 out=113,089,395 elapsed=208.3s

  [18310/21087] intraday_7221.csv.gz  in=451,974,349 out=113,089,395 elapsed=208.3s

  [18311/21087] intraday_7223.csv.gz  in=451,987,462 out=113,089,395 elapsed=208.3s

  [18312/21087] intraday_7224.csv.gz  in=451,998,188 out=113,089,395 elapsed=208.3s

  [18313/21087] intraday_7225.csv.gz  in=452,010,138 out=113,089,395 elapsed=208.3s

  [18314/21087] intraday_7226.csv.gz  in=452,023,046 out=113,089,395 elapsed=208.3s

  [18315/21087] intraday_7227.csv.gz  in=452,039,286 out=113,089,395 elapsed=208.4s

  [18316/21087] intraday_7228.csv.gz  in=452,053,726 out=113,089,395 elapsed=208.4s

  [18317/21087] intraday_7229.csv.gz  in=452,067,267 out=113,089,395 elapsed=208.4s

  [18318/21087] intraday_7230.csv.gz  in=452,079,778 out=113,089,395 elapsed=208.4s

  [18319/21087] intraday_7231.csv.gz  in=452,091,259 out=113,089,395 elapsed=208.4s

  [18320/21087] intraday_7232.csv.gz  in=452,103,912 out=113,089,395 elapsed=208.4s

  [18321/21087] intraday_7233.csv.gz  in=452,120,825 out=113,089,395 elapsed=208.4s

  [18322/21087] intraday_7234.csv.gz  in=452,132,593 out=113,089,395 elapsed=208.4s

  [18323/21087] intraday_7235.csv.gz  in=452,144,121 out=113,089,395 elapsed=208.4s

  [18324/21087] intraday_7236.csv.gz  in=452,157,813 out=113,089,395 elapsed=208.4s

  [18325/21087] intraday_7237.csv.gz  in=452,171,180 out=113,089,395 elapsed=208.4s

  [18326/21087] intraday_7238.csv.gz  in=452,184,570 out=113,089,395 elapsed=208.5s

  [18327/21087] intraday_7239.csv.gz  in=452,196,960 out=113,089,395 elapsed=208.5s

  [18328/21087] intraday_7240.csv.gz  in=452,209,521 out=113,089,395 elapsed=208.5s

  [18329/21087] intraday_7241.csv.gz  in=452,220,881 out=113,089,395 elapsed=208.5s

  [18330/21087] intraday_7242.csv.gz  in=452,235,279 out=113,089,395 elapsed=208.5s

  [18331/21087] intraday_7244.csv.gz  in=452,245,477 out=113,089,395 elapsed=208.5s

  [18332/21087] intraday_7245.csv.gz  in=452,258,056 out=113,089,395 elapsed=208.5s

  [18333/21087] intraday_7243.csv.gz  in=452,293,957 out=113,089,395 elapsed=208.5s

  [18334/21087] intraday_7246.csv.gz  in=452,308,392 out=113,089,395 elapsed=208.5s

  [18335/21087] intraday_7247.csv.gz  in=452,321,264 out=113,089,395 elapsed=208.5s

  [18336/21087] intraday_7248.csv.gz  in=452,336,435 out=113,089,395 elapsed=208.5s

  [18337/21087] intraday_7249.csv.gz  in=452,348,911 out=113,089,395 elapsed=208.5s

  [18338/21087] intraday_7250.csv.gz  in=452,364,902 out=113,089,395 elapsed=208.5s

  [18339/21087] intraday_7251.csv.gz  in=452,378,026 out=113,089,395 elapsed=208.6s

  [18340/21087] intraday_7252.csv.gz  in=452,391,054 out=113,089,395 elapsed=208.6s

  [18341/21087] intraday_7253.csv.gz  in=452,406,628 out=113,089,395 elapsed=208.6s

  [18342/21087] intraday_7254.csv.gz  in=452,421,137 out=113,089,395 elapsed=208.6s

  [18343/21087] intraday_7255.csv.gz  in=452,431,463 out=113,089,395 elapsed=208.6s

  [18344/21087] intraday_7256.csv.gz  in=452,446,550 out=113,089,395 elapsed=208.6s

  [18345/21087] intraday_7257.csv.gz  in=452,456,966 out=113,089,395 elapsed=208.6s

  [18346/21087] intraday_7258.csv.gz  in=452,471,630 out=113,089,395 elapsed=208.6s

  [18347/21087] intraday_7259.csv.gz  in=452,487,739 out=113,089,395 elapsed=208.6s

  [18348/21087] intraday_7260.csv.gz  in=452,504,174 out=113,089,395 elapsed=208.6s

  [18349/21087] intraday_7261.csv.gz  in=452,518,713 out=113,089,395 elapsed=208.6s

  [18350/21087] intraday_7262.csv.gz  in=452,533,756 out=113,089,395 elapsed=208.6s

  [18351/21087] intraday_7263.csv.gz  in=452,547,298 out=113,089,395 elapsed=208.6s

  [18352/21087] intraday_7264.csv.gz  in=452,558,448 out=113,089,395 elapsed=208.7s

  [18353/21087] intraday_7265.csv.gz  in=452,569,085 out=113,089,395 elapsed=208.7s

  [18354/21087] intraday_7266.csv.gz  in=452,583,372 out=113,089,395 elapsed=208.7s

  [18355/21087] intraday_7267.csv.gz  in=452,594,471 out=113,089,395 elapsed=208.7s

  [18356/21087] intraday_7268.csv.gz  in=452,607,695 out=113,089,395 elapsed=208.7s

  [18357/21087] intraday_7269.csv.gz  in=452,620,167 out=113,089,395 elapsed=208.7s

  [18358/21087] intraday_7271.csv.gz  in=452,632,973 out=113,089,395 elapsed=208.7s

  [18359/21087] intraday_7270.csv.gz  in=452,648,227 out=113,089,395 elapsed=208.7s

  [18360/21087] intraday_7272.csv.gz  in=452,660,725 out=113,089,395 elapsed=208.7s

  [18361/21087] intraday_7273.csv.gz  in=452,672,532 out=113,089,395 elapsed=208.7s

  [18362/21087] intraday_7274.csv.gz  in=452,685,094 out=113,089,395 elapsed=208.7s

  [18363/21087] intraday_7275.csv.gz  in=452,696,951 out=113,089,395 elapsed=208.7s

  [18364/21087] intraday_7277.csv.gz  in=452,711,013 out=113,089,395 elapsed=208.7s

  [18365/21087] intraday_7276.csv.gz  in=452,727,519 out=113,089,395 elapsed=208.8s

  [18366/21087] intraday_7278.csv.gz  in=452,741,349 out=113,089,395 elapsed=208.8s

  [18367/21087] intraday_7279.csv.gz  in=452,755,922 out=113,089,395 elapsed=208.8s

  [18368/21087] intraday_7281.csv.gz  in=452,767,287 out=113,089,395 elapsed=208.8s

  [18369/21087] intraday_7280.csv.gz  in=452,778,956 out=113,089,395 elapsed=208.8s

  [18370/21087] intraday_7282.csv.gz  in=452,792,622 out=113,089,395 elapsed=208.8s

  [18371/21087] intraday_7283.csv.gz  in=452,804,535 out=113,089,395 elapsed=208.8s

  [18372/21087] intraday_7284.csv.gz  in=452,817,195 out=113,089,395 elapsed=208.8s

  [18373/21087] intraday_7285.csv.gz  in=452,825,091 out=113,089,395 elapsed=208.8s

  [18374/21087] intraday_7286.csv.gz  in=452,837,649 out=113,089,395 elapsed=208.8s

  [18375/21087] intraday_7287.csv.gz  in=452,844,400 out=113,089,395 elapsed=208.8s

  [18376/21087] intraday_7288.csv.gz  in=452,860,796 out=113,089,395 elapsed=208.8s

  [18377/21087] intraday_7289.csv.gz  in=452,876,138 out=113,089,395 elapsed=208.8s

  [18378/21087] intraday_7290.csv.gz  in=452,889,008 out=113,089,395 elapsed=208.9s

  [18379/21087] intraday_7291.csv.gz  in=452,900,731 out=113,089,395 elapsed=208.9s

  [18380/21087] intraday_7292.csv.gz  in=452,913,055 out=113,089,395 elapsed=208.9s

  [18381/21087] intraday_7293.csv.gz  in=452,927,249 out=113,089,395 elapsed=208.9s

  [18382/21087] intraday_7295.csv.gz  in=452,938,780 out=113,089,395 elapsed=208.9s

  [18383/21087] intraday_7294.csv.gz  in=452,955,175 out=113,089,395 elapsed=208.9s

  [18384/21087] intraday_7296.csv.gz  in=452,969,163 out=113,089,395 elapsed=208.9s

  [18385/21087] intraday_7297.csv.gz  in=452,983,766 out=113,089,395 elapsed=208.9s

  [18386/21087] intraday_7298.csv.gz  in=453,000,313 out=113,089,395 elapsed=208.9s

  [18387/21087] intraday_7299.csv.gz  in=453,015,415 out=113,089,395 elapsed=208.9s

  [18388/21087] intraday_7300.csv.gz  in=453,028,271 out=113,089,395 elapsed=208.9s

  [18389/21087] intraday_7301.csv.gz  in=453,045,244 out=113,089,395 elapsed=208.9s

  [18390/21087] intraday_7302.csv.gz  in=453,055,735 out=113,089,395 elapsed=208.9s

  [18391/21087] intraday_7303.csv.gz  in=453,067,379 out=113,089,395 elapsed=208.9s

  [18392/21087] intraday_7304.csv.gz  in=453,082,482 out=113,089,395 elapsed=209.0s

  [18393/21087] intraday_7305.csv.gz  in=453,095,710 out=113,089,395 elapsed=209.0s

  [18394/21087] intraday_7306.csv.gz  in=453,108,368 out=113,089,395 elapsed=209.0s

  [18395/21087] intraday_7307.csv.gz  in=453,120,908 out=113,089,395 elapsed=209.0s

  [18396/21087] intraday_7308.csv.gz  in=453,133,865 out=113,089,395 elapsed=209.0s

  [18397/21087] intraday_7309.csv.gz  in=453,146,876 out=113,089,395 elapsed=209.0s

  [18398/21087] intraday_7310.csv.gz  in=453,159,605 out=113,089,395 elapsed=209.0s

  [18399/21087] intraday_7311.csv.gz  in=453,172,200 out=113,089,395 elapsed=209.0s

  [18400/21087] intraday_7312.csv.gz  in=453,185,904 out=113,089,395 elapsed=209.0s

  [18401/21087] intraday_7313.csv.gz  in=453,199,431 out=113,089,395 elapsed=209.0s

  [18402/21087] intraday_7314.csv.gz  in=453,210,269 out=113,089,395 elapsed=209.0s

  [18403/21087] intraday_7315.csv.gz  in=453,222,793 out=113,089,395 elapsed=209.0s

  [18404/21087] intraday_7316.csv.gz  in=453,234,804 out=113,089,395 elapsed=209.1s

  [18405/21087] intraday_7317.csv.gz  in=453,248,999 out=113,089,395 elapsed=209.1s

  [18406/21087] intraday_7318.csv.gz  in=453,265,363 out=113,089,395 elapsed=209.1s

  [18407/21087] intraday_7319.csv.gz  in=453,279,404 out=113,089,395 elapsed=209.1s

  [18408/21087] intraday_7321.csv.gz  in=453,293,958 out=113,089,395 elapsed=209.1s

  [18409/21087] intraday_7320.csv.gz  in=453,303,951 out=113,089,395 elapsed=209.1s

  [18410/21087] intraday_7322.csv.gz  in=453,317,948 out=113,089,395 elapsed=209.1s

  [18411/21087] intraday_7323.csv.gz  in=453,330,787 out=113,089,395 elapsed=209.1s

  [18412/21087] intraday_7324.csv.gz  in=453,343,315 out=113,089,395 elapsed=209.1s

  [18413/21087] intraday_7325.csv.gz  in=453,354,924 out=113,089,395 elapsed=209.1s

  [18414/21087] intraday_7326.csv.gz  in=453,368,572 out=113,089,395 elapsed=209.1s

  [18415/21087] intraday_7327.csv.gz  in=453,381,053 out=113,089,395 elapsed=209.1s

  [18416/21087] intraday_7328.csv.gz  in=453,392,624 out=113,089,395 elapsed=209.2s

  [18417/21087] intraday_7329.csv.gz  in=453,405,203 out=113,089,395 elapsed=209.2s

  [18418/21087] intraday_7330.csv.gz  in=453,418,152 out=113,089,395 elapsed=209.2s

  [18419/21087] intraday_7331.csv.gz  in=453,432,612 out=113,089,395 elapsed=209.2s

  [18420/21087] intraday_7332.csv.gz  in=453,447,567 out=113,089,395 elapsed=209.2s

  [18421/21087] intraday_7333.csv.gz  in=453,459,686 out=113,089,395 elapsed=209.2s

  [18422/21087] intraday_7334.csv.gz  in=453,471,957 out=113,089,395 elapsed=209.2s

  [18423/21087] intraday_7335.csv.gz  in=453,485,560 out=113,089,395 elapsed=209.2s

  [18424/21087] intraday_7336.csv.gz  in=453,497,987 out=113,089,395 elapsed=209.2s

  [18425/21087] intraday_7337.csv.gz  in=453,510,716 out=113,089,395 elapsed=209.2s

  [18426/21087] intraday_7338.csv.gz  in=453,521,659 out=113,089,395 elapsed=209.2s

  [18427/21087] intraday_7339.csv.gz  in=453,533,463 out=113,089,395 elapsed=209.2s

  [18428/21087] intraday_7340.csv.gz  in=453,548,304 out=113,089,395 elapsed=209.3s

  [18429/21087] intraday_7341.csv.gz  in=453,558,514 out=113,089,395 elapsed=209.3s

  [18430/21087] intraday_7342.csv.gz  in=453,574,089 out=113,089,395 elapsed=209.3s

  [18431/21087] intraday_7343.csv.gz  in=453,587,152 out=113,089,395 elapsed=209.3s

  [18432/21087] intraday_7344.csv.gz  in=453,602,500 out=113,089,395 elapsed=209.3s

  [18433/21087] intraday_7345.csv.gz  in=453,614,550 out=113,089,395 elapsed=209.3s

  [18434/21087] intraday_7346.csv.gz  in=453,627,554 out=113,089,395 elapsed=209.3s

  [18435/21087] intraday_7347.csv.gz  in=453,640,845 out=113,089,395 elapsed=209.3s

  [18436/21087] intraday_7348.csv.gz  in=453,653,857 out=113,089,395 elapsed=209.3s

  [18437/21087] intraday_7349.csv.gz  in=453,667,839 out=113,089,395 elapsed=209.3s

  [18438/21087] intraday_7350.csv.gz  in=453,679,722 out=113,089,395 elapsed=209.3s

  [18439/21087] intraday_7351.csv.gz  in=453,690,889 out=113,089,395 elapsed=209.3s

  [18440/21087] intraday_7352.csv.gz  in=453,702,306 out=113,089,395 elapsed=209.3s

  [18441/21087] intraday_7353.csv.gz  in=453,717,526 out=113,089,395 elapsed=209.4s

  [18442/21087] intraday_7354.csv.gz  in=453,730,930 out=113,089,395 elapsed=209.4s

  [18443/21087] intraday_7355.csv.gz  in=453,745,897 out=113,089,395 elapsed=209.4s

  [18444/21087] intraday_7356.csv.gz  in=453,758,373 out=113,089,395 elapsed=209.4s

  [18445/21087] intraday_7357.csv.gz  in=453,771,043 out=113,089,395 elapsed=209.4s

  [18446/21087] intraday_7358.csv.gz  in=453,782,238 out=113,089,395 elapsed=209.4s

  [18447/21087] intraday_7359.csv.gz  in=453,794,261 out=113,089,395 elapsed=209.4s

  [18448/21087] intraday_7360.csv.gz  in=453,806,999 out=113,089,395 elapsed=209.4s

  [18449/21087] intraday_7361.csv.gz  in=453,820,946 out=113,089,395 elapsed=209.4s

  [18450/21087] intraday_7362.csv.gz  in=453,832,886 out=113,089,395 elapsed=209.4s

  [18451/21087] intraday_7363.csv.gz  in=453,844,821 out=113,089,395 elapsed=209.4s

  [18452/21087] intraday_7364.csv.gz  in=453,854,816 out=113,089,395 elapsed=209.4s

  [18453/21087] intraday_7365.csv.gz  in=453,869,780 out=113,089,395 elapsed=209.4s

  [18454/21087] intraday_7366.csv.gz  in=453,881,549 out=113,089,395 elapsed=209.5s

  [18455/21087] intraday_7368.csv.gz  in=453,892,448 out=113,089,395 elapsed=209.5s

  [18456/21087] intraday_7367.csv.gz  in=453,904,526 out=113,089,395 elapsed=209.5s

  [18457/21087] intraday_7369.csv.gz  in=453,914,094 out=113,089,395 elapsed=209.5s

  [18458/21087] intraday_7370.csv.gz  in=453,926,227 out=113,089,395 elapsed=209.5s

  [18459/21087] intraday_7373.csv.gz  in=453,940,040 out=113,089,395 elapsed=209.5s

  [18460/21087] intraday_7371.csv.gz  in=453,957,976 out=113,089,395 elapsed=209.5s

  [18461/21087] intraday_7372.csv.gz  in=453,975,755 out=113,089,395 elapsed=209.5s

  [18462/21087] intraday_7374.csv.gz  in=453,986,302 out=113,089,395 elapsed=209.5s

  [18463/21087] intraday_7375.csv.gz  in=453,999,119 out=113,089,395 elapsed=209.5s

  [18464/21087] intraday_7376.csv.gz  in=454,014,425 out=113,089,395 elapsed=209.6s

  [18465/21087] intraday_7378.csv.gz  in=454,029,364 out=113,089,395 elapsed=209.6s

  [18466/21087] intraday_7377.csv.gz  in=454,043,450 out=113,089,395 elapsed=209.6s

  [18467/21087] intraday_7379.csv.gz  in=454,058,092 out=113,089,395 elapsed=209.6s

  [18468/21087] intraday_7381.csv.gz  in=454,071,820 out=113,089,395 elapsed=209.6s

  [18469/21087] intraday_7380.csv.gz  in=454,085,321 out=113,089,395 elapsed=209.6s

  [18470/21087] intraday_7382.csv.gz  in=454,098,952 out=113,089,395 elapsed=209.6s

  [18471/21087] intraday_7383.csv.gz  in=454,112,694 out=113,089,395 elapsed=209.6s

  [18472/21087] intraday_7384.csv.gz  in=454,124,001 out=113,089,395 elapsed=209.6s

  [18473/21087] intraday_7385.csv.gz  in=454,137,764 out=113,089,395 elapsed=209.6s

  [18474/21087] intraday_7386.csv.gz  in=454,151,325 out=113,089,395 elapsed=209.6s

  [18475/21087] intraday_7387.csv.gz  in=454,164,791 out=113,089,395 elapsed=209.6s

  [18476/21087] intraday_7388.csv.gz  in=454,176,702 out=113,089,395 elapsed=209.6s

  [18477/21087] intraday_7389.csv.gz  in=454,191,122 out=113,089,395 elapsed=209.6s

  [18478/21087] intraday_7390.csv.gz  in=454,203,862 out=113,089,395 elapsed=209.7s

  [18479/21087] intraday_7392.csv.gz  in=454,215,928 out=113,089,395 elapsed=209.7s

  [18480/21087] intraday_7391.csv.gz  in=454,232,284 out=113,089,395 elapsed=209.7s

  [18481/21087] intraday_7393.csv.gz  in=454,244,929 out=113,089,395 elapsed=209.7s

  [18482/21087] intraday_7394.csv.gz  in=454,262,183 out=113,089,395 elapsed=209.7s

  [18483/21087] intraday_7395.csv.gz  in=454,275,323 out=113,089,395 elapsed=209.7s

  [18484/21087] intraday_7396.csv.gz  in=454,287,295 out=113,089,395 elapsed=209.7s

  [18485/21087] intraday_7397.csv.gz  in=454,303,344 out=113,089,395 elapsed=209.7s

  [18486/21087] intraday_7398.csv.gz  in=454,319,252 out=113,089,395 elapsed=209.7s

  [18487/21087] intraday_7399.csv.gz  in=454,331,819 out=113,089,395 elapsed=209.7s

  [18488/21087] intraday_7400.csv.gz  in=454,345,162 out=113,089,395 elapsed=209.7s

  [18489/21087] intraday_7401.csv.gz  in=454,358,847 out=113,089,395 elapsed=209.7s

  [18490/21087] intraday_7402.csv.gz  in=454,371,382 out=113,089,395 elapsed=209.7s

  [18491/21087] intraday_7403.csv.gz  in=454,390,420 out=113,089,395 elapsed=209.8s

  [18492/21087] intraday_7404.csv.gz  in=454,404,994 out=113,089,395 elapsed=209.8s

  [18493/21087] intraday_7405.csv.gz  in=454,420,230 out=113,089,395 elapsed=209.8s

  [18494/21087] intraday_7406.csv.gz  in=454,437,640 out=113,089,395 elapsed=209.8s

  [18495/21087] intraday_7407.csv.gz  in=454,452,579 out=113,089,395 elapsed=209.8s

  [18496/21087] intraday_7408.csv.gz  in=454,465,587 out=113,089,395 elapsed=209.8s

  [18497/21087] intraday_7409.csv.gz  in=454,477,735 out=113,089,395 elapsed=209.8s

  [18498/21087] intraday_7410.csv.gz  in=454,491,057 out=113,089,395 elapsed=209.8s

  [18499/21087] intraday_7411.csv.gz  in=454,502,551 out=113,089,395 elapsed=209.8s

  [18500/21087] intraday_7412.csv.gz  in=454,516,662 out=113,089,395 elapsed=209.8s

  [18501/21087] intraday_7413.csv.gz  in=454,529,353 out=113,089,395 elapsed=209.8s

  [18502/21087] intraday_7414.csv.gz  in=454,545,349 out=113,089,395 elapsed=209.8s

  [18503/21087] intraday_7415.csv.gz  in=454,559,518 out=113,089,395 elapsed=209.9s

  [18504/21087] intraday_7416.csv.gz  in=454,573,107 out=113,089,395 elapsed=209.9s

  [18505/21087] intraday_7417.csv.gz  in=454,584,913 out=113,089,395 elapsed=209.9s

  [18506/21087] intraday_7418.csv.gz  in=454,599,386 out=113,089,395 elapsed=209.9s

  [18507/21087] intraday_7419.csv.gz  in=454,611,484 out=113,089,395 elapsed=209.9s

  [18508/21087] intraday_7420.csv.gz  in=454,624,349 out=113,089,395 elapsed=209.9s

  [18509/21087] intraday_7421.csv.gz  in=454,640,160 out=113,089,395 elapsed=209.9s

  [18510/21087] intraday_7422.csv.gz  in=454,655,141 out=113,089,395 elapsed=209.9s

  [18511/21087] intraday_7423.csv.gz  in=454,675,252 out=113,089,395 elapsed=209.9s

  [18512/21087] intraday_7424.csv.gz  in=454,689,871 out=113,089,395 elapsed=209.9s

  [18513/21087] intraday_7425.csv.gz  in=454,702,852 out=113,089,395 elapsed=209.9s

  [18514/21087] intraday_7426.csv.gz  in=454,716,460 out=113,089,395 elapsed=209.9s

  [18515/21087] intraday_7427.csv.gz  in=454,727,161 out=113,089,395 elapsed=209.9s

  [18516/21087] intraday_7429.csv.gz  in=454,738,073 out=113,089,395 elapsed=210.0s

  [18517/21087] intraday_7428.csv.gz  in=454,752,685 out=113,089,395 elapsed=210.0s

  [18518/21087] intraday_7430.csv.gz  in=454,761,947 out=113,089,395 elapsed=210.0s

  [18519/21087] intraday_7432.csv.gz  in=454,764,040 out=113,089,395 elapsed=210.0s

  [18520/21087] intraday_7434.csv.gz  in=454,764,075 out=113,089,395 elapsed=210.0s

  [18521/21087] intraday_7433.csv.gz  in=454,764,183 out=113,089,395 elapsed=210.0s

  [18522/21087] intraday_7431.csv.gz  in=454,777,702 out=113,089,395 elapsed=210.0s

  [18523/21087] intraday_7435.csv.gz  in=454,777,724 out=113,089,395 elapsed=210.0s

  [18524/21087] intraday_7438.csv.gz  in=454,777,767 out=113,089,395 elapsed=210.0s

  [18525/21087] intraday_7436.csv.gz  in=454,785,650 out=113,089,395 elapsed=210.0s

  [18526/21087] intraday_7437.csv.gz  in=454,788,162 out=113,089,395 elapsed=210.0s

  [18527/21087] intraday_7439.csv.gz  in=454,789,981 out=113,089,395 elapsed=210.0s

  [18528/21087] intraday_7440.csv.gz  in=454,790,157 out=113,089,395 elapsed=210.0s

  [18529/21087] intraday_7442.csv.gz  in=454,790,291 out=113,089,395 elapsed=210.0s

  [18530/21087] intraday_7441.csv.gz  in=454,795,148 out=113,089,395 elapsed=210.1s

  [18531/21087] intraday_7443.csv.gz  in=454,796,304 out=113,089,395 elapsed=210.1s

  [18532/21087] intraday_7444.csv.gz  in=454,796,317 out=113,089,395 elapsed=210.1s

  [18533/21087] intraday_7446.csv.gz  in=454,796,419 out=113,089,395 elapsed=210.1s

  [18534/21087] intraday_7447.csv.gz  in=454,797,337 out=113,089,395 elapsed=210.1s

  [18535/21087] intraday_7445.csv.gz  in=454,797,360 out=113,089,395 elapsed=210.1s

  [18536/21087] intraday_7448.csv.gz  in=454,798,259 out=113,089,395 elapsed=210.1s

  [18537/21087] intraday_7450.csv.gz  in=454,798,267 out=113,089,395 elapsed=210.1s

  [18538/21087] intraday_7451.csv.gz  in=454,798,312 out=113,089,395 elapsed=210.1s

  [18539/21087] intraday_7449.csv.gz  in=454,798,475 out=113,089,395 elapsed=210.1s

  [18540/21087] intraday_7452.csv.gz  in=454,799,811 out=113,089,395 elapsed=210.1s

  [18541/21087] intraday_7453.csv.gz  in=454,804,267 out=113,089,395 elapsed=210.1s

  [18542/21087] intraday_7454.csv.gz  in=454,808,552 out=113,089,395 elapsed=210.1s

  [18543/21087] intraday_7455.csv.gz  in=454,809,272 out=113,089,395 elapsed=210.1s

  [18544/21087] intraday_7456.csv.gz  in=454,809,589 out=113,089,395 elapsed=210.1s

  [18545/21087] intraday_7458.csv.gz  in=454,809,612 out=113,089,395 elapsed=210.2s

  [18546/21087] intraday_7459.csv.gz  in=454,809,743 out=113,089,395 elapsed=210.2s

  [18547/21087] intraday_7457.csv.gz  in=454,813,966 out=113,089,395 elapsed=210.2s

  [18548/21087] intraday_7460.csv.gz  in=454,814,177 out=113,089,395 elapsed=210.2s

  [18549/21087] intraday_7461.csv.gz  in=454,814,483 out=113,089,395 elapsed=210.2s

  [18550/21087] intraday_7463.csv.gz  in=454,817,965 out=113,089,395 elapsed=210.2s

  [18551/21087] intraday_7464.csv.gz  in=454,820,786 out=113,089,395 elapsed=210.2s

  [18552/21087] intraday_7465.csv.gz  in=454,823,199 out=113,089,395 elapsed=210.2s

  [18553/21087] intraday_7462.csv.gz  in=454,854,942 out=113,089,395 elapsed=210.2s

  [18554/21087] intraday_7466.csv.gz  in=454,857,435 out=113,089,395 elapsed=210.2s

  [18555/21087] intraday_7467.csv.gz  in=454,859,876 out=113,089,395 elapsed=210.2s

  [18556/21087] intraday_7468.csv.gz  in=454,862,915 out=113,089,395 elapsed=210.2s

  [18557/21087] intraday_7469.csv.gz  in=454,866,945 out=113,089,395 elapsed=210.2s

  [18558/21087] intraday_7470.csv.gz  in=454,869,184 out=113,089,395 elapsed=210.2s

  [18559/21087] intraday_7471.csv.gz  in=454,871,878 out=113,089,395 elapsed=210.2s

  [18560/21087] intraday_7472.csv.gz  in=454,874,911 out=113,089,395 elapsed=210.2s

  [18561/21087] intraday_7473.csv.gz  in=454,879,179 out=113,089,395 elapsed=210.3s

  [18562/21087] intraday_7474.csv.gz  in=454,882,874 out=113,089,395 elapsed=210.3s

  [18563/21087] intraday_7475.csv.gz  in=454,885,885 out=113,089,395 elapsed=210.3s

  [18564/21087] intraday_7476.csv.gz  in=454,888,924 out=113,089,395 elapsed=210.3s

  [18565/21087] intraday_7478.csv.gz  in=454,891,012 out=113,089,395 elapsed=210.3s

  [18566/21087] intraday_7477.csv.gz  in=454,893,465 out=113,089,395 elapsed=210.3s

  [18567/21087] intraday_7479.csv.gz  in=454,896,741 out=113,089,395 elapsed=210.3s

  [18568/21087] intraday_7480.csv.gz  in=454,899,417 out=113,089,395 elapsed=210.3s

  [18569/21087] intraday_7481.csv.gz  in=454,901,468 out=113,089,395 elapsed=210.3s

  [18570/21087] intraday_7483.csv.gz  in=454,904,241 out=113,089,395 elapsed=210.3s

  [18571/21087] intraday_7482.csv.gz  in=454,906,356 out=113,089,395 elapsed=210.3s

  [18572/21087] intraday_7485.csv.gz  in=454,908,048 out=113,089,395 elapsed=210.3s

  [18573/21087] intraday_7484.csv.gz  in=454,911,274 out=113,089,395 elapsed=210.3s

  [18574/21087] intraday_7486.csv.gz  in=454,913,925 out=113,089,395 elapsed=210.3s

  [18575/21087] intraday_7487.csv.gz  in=454,916,218 out=113,089,395 elapsed=210.3s

  [18576/21087] intraday_7488.csv.gz  in=454,919,427 out=113,089,395 elapsed=210.4s

  [18577/21087] intraday_7489.csv.gz  in=454,921,862 out=113,089,395 elapsed=210.4s

  [18578/21087] intraday_7490.csv.gz  in=454,924,444 out=113,089,395 elapsed=210.4s

  [18579/21087] intraday_7491.csv.gz  in=454,927,015 out=113,089,395 elapsed=210.4s

  [18580/21087] intraday_7492.csv.gz  in=454,930,255 out=113,089,395 elapsed=210.4s

  [18581/21087] intraday_7494.csv.gz  in=454,932,706 out=113,089,395 elapsed=210.4s

  [18582/21087] intraday_7495.csv.gz  in=454,934,129 out=113,089,395 elapsed=210.4s

  [18583/21087] intraday_7493.csv.gz  in=454,938,087 out=113,089,395 elapsed=210.4s

  [18584/21087] intraday_7496.csv.gz  in=454,941,133 out=113,089,395 elapsed=210.4s

  [18585/21087] intraday_7497.csv.gz  in=454,943,594 out=113,089,395 elapsed=210.4s

  [18586/21087] intraday_7498.csv.gz  in=454,945,803 out=113,089,395 elapsed=210.4s

  [18587/21087] intraday_7499.csv.gz  in=454,948,093 out=113,089,395 elapsed=210.4s

  [18588/21087] intraday_7500.csv.gz  in=454,950,279 out=113,089,395 elapsed=210.4s

  [18589/21087] intraday_7501.csv.gz  in=454,952,715 out=113,089,395 elapsed=210.4s

  [18590/21087] intraday_7503.csv.gz  in=454,955,365 out=113,089,395 elapsed=210.4s

  [18591/21087] intraday_7502.csv.gz  in=454,957,350 out=113,089,395 elapsed=210.4s

  [18592/21087] intraday_7504.csv.gz  in=454,959,724 out=113,089,395 elapsed=210.4s

  [18593/21087] intraday_7505.csv.gz  in=454,962,604 out=113,089,395 elapsed=210.5s

  [18594/21087] intraday_7506.csv.gz  in=454,965,299 out=113,089,395 elapsed=210.5s

  [18595/21087] intraday_7507.csv.gz  in=454,967,550 out=113,089,395 elapsed=210.5s

  [18596/21087] intraday_7509.csv.gz  in=454,968,951 out=113,089,395 elapsed=210.5s

  [18597/21087] intraday_7511.csv.gz  in=454,970,972 out=113,089,395 elapsed=210.5s

  [18598/21087] intraday_7510.csv.gz  in=454,973,169 out=113,089,395 elapsed=210.5s

  [18599/21087] intraday_7508.csv.gz  in=454,975,315 out=113,089,395 elapsed=210.5s

  [18600/21087] intraday_7514.csv.gz  in=454,977,223 out=113,089,395 elapsed=210.5s

  [18601/21087] intraday_7513.csv.gz  in=454,979,222 out=113,089,395 elapsed=210.5s

  [18602/21087] intraday_7515.csv.gz  in=454,983,442 out=113,089,395 elapsed=210.5s

  [18603/21087] intraday_7512.csv.gz  in=454,986,978 out=113,089,395 elapsed=210.5s

  [18604/21087] intraday_7516.csv.gz  in=454,989,352 out=113,089,395 elapsed=210.5s

  [18605/21087] intraday_7519.csv.gz  in=454,991,793 out=113,089,395 elapsed=210.5s

  [18606/21087] intraday_7518.csv.gz  in=454,995,678 out=113,089,395 elapsed=210.6s

  [18607/21087] intraday_7517.csv.gz  in=455,002,579 out=113,089,395 elapsed=210.6s

  [18608/21087] intraday_7520.csv.gz  in=455,004,223 out=113,089,395 elapsed=210.6s

  [18609/21087] intraday_7522.csv.gz  in=455,006,877 out=113,089,395 elapsed=210.6s

  [18610/21087] intraday_7521.csv.gz  in=455,009,466 out=113,089,395 elapsed=210.6s

  [18611/21087] intraday_7523.csv.gz  in=455,011,167 out=113,089,395 elapsed=210.6s

  [18612/21087] intraday_7524.csv.gz  in=455,014,293 out=113,089,395 elapsed=210.6s

  [18613/21087] intraday_7526.csv.gz  in=455,015,950 out=113,089,395 elapsed=210.6s

  [18614/21087] intraday_7525.csv.gz  in=455,017,736 out=113,089,395 elapsed=210.6s

  [18615/21087] intraday_7527.csv.gz  in=455,019,979 out=113,089,395 elapsed=210.6s

  [18616/21087] intraday_7529.csv.gz  in=455,023,592 out=113,089,395 elapsed=210.6s

  [18617/21087] intraday_7528.csv.gz  in=455,027,353 out=113,089,395 elapsed=210.6s

  [18618/21087] intraday_7530.csv.gz  in=455,029,838 out=113,089,395 elapsed=210.6s

  [18619/21087] intraday_7531.csv.gz  in=455,032,476 out=113,089,395 elapsed=210.6s

  [18620/21087] intraday_7532.csv.gz  in=455,034,941 out=113,089,395 elapsed=210.6s

  [18621/21087] intraday_7533.csv.gz  in=455,037,375 out=113,089,395 elapsed=210.6s

  [18622/21087] intraday_7535.csv.gz  in=455,039,829 out=113,089,395 elapsed=210.7s

  [18623/21087] intraday_7534.csv.gz  in=455,042,292 out=113,089,395 elapsed=210.7s

  [18624/21087] intraday_7536.csv.gz  in=455,045,453 out=113,089,395 elapsed=210.7s

  [18625/21087] intraday_7537.csv.gz  in=455,047,402 out=113,089,395 elapsed=210.7s

  [18626/21087] intraday_7538.csv.gz  in=455,050,502 out=113,089,395 elapsed=210.7s

  [18627/21087] intraday_7539.csv.gz  in=455,052,418 out=113,089,395 elapsed=210.7s

  [18628/21087] intraday_7540.csv.gz  in=455,055,172 out=113,089,395 elapsed=210.7s

  [18629/21087] intraday_7543.csv.gz  in=455,057,327 out=113,089,395 elapsed=210.7s

  [18630/21087] intraday_7541.csv.gz  in=455,059,431 out=113,089,395 elapsed=210.7s

  [18631/21087] intraday_7542.csv.gz  in=455,061,598 out=113,089,395 elapsed=210.7s

  [18632/21087] intraday_7544.csv.gz  in=455,062,969 out=113,089,395 elapsed=210.7s

  [18633/21087] intraday_7545.csv.gz  in=455,065,744 out=113,089,395 elapsed=210.7s

  [18634/21087] intraday_7546.csv.gz  in=455,070,998 out=113,089,395 elapsed=210.7s

  [18635/21087] intraday_7547.csv.gz  in=455,076,631 out=113,089,395 elapsed=210.7s

  [18636/21087] intraday_7548.csv.gz  in=455,080,151 out=113,089,395 elapsed=210.7s

  [18637/21087] intraday_7550.csv.gz  in=455,082,818 out=113,089,395 elapsed=210.7s

  [18638/21087] intraday_7549.csv.gz  in=455,085,426 out=113,089,395 elapsed=210.7s

  [18639/21087] intraday_7551.csv.gz  in=455,089,557 out=113,089,395 elapsed=210.8s

  [18640/21087] intraday_7552.csv.gz  in=455,092,598 out=113,089,395 elapsed=210.8s

  [18641/21087] intraday_7554.csv.gz  in=455,094,806 out=113,089,395 elapsed=210.8s

  [18642/21087] intraday_7553.csv.gz  in=455,099,624 out=113,089,395 elapsed=210.8s

  [18643/21087] intraday_7556.csv.gz  in=455,102,738 out=113,089,395 elapsed=210.8s

  [18644/21087] intraday_7555.csv.gz  in=455,105,233 out=113,089,395 elapsed=210.8s

  [18645/21087] intraday_7558.csv.gz  in=455,107,669 out=113,089,395 elapsed=210.8s

  [18646/21087] intraday_7559.csv.gz  in=455,109,862 out=113,089,395 elapsed=210.8s

  [18647/21087] intraday_7560.csv.gz  in=455,112,393 out=113,089,395 elapsed=210.8s

  [18648/21087] intraday_7557.csv.gz  in=455,115,389 out=113,089,395 elapsed=210.8s

  [18649/21087] intraday_7561.csv.gz  in=455,118,277 out=113,089,395 elapsed=210.8s

  [18650/21087] intraday_7562.csv.gz  in=455,122,506 out=113,089,395 elapsed=210.8s

  [18651/21087] intraday_7563.csv.gz  in=455,123,892 out=113,089,395 elapsed=210.8s

  [18652/21087] intraday_7564.csv.gz  in=455,126,076 out=113,089,395 elapsed=210.8s

  [18653/21087] intraday_7565.csv.gz  in=455,129,854 out=113,089,395 elapsed=210.8s

  [18654/21087] intraday_7567.csv.gz  in=455,131,970 out=113,089,395 elapsed=210.8s

  [18655/21087] intraday_7566.csv.gz  in=455,136,683 out=113,089,395 elapsed=210.8s

  [18656/21087] intraday_7569.csv.gz  in=455,141,174 out=113,089,395 elapsed=210.9s

  [18657/21087] intraday_7568.csv.gz  in=455,143,946 out=113,089,395 elapsed=210.9s

  [18658/21087] intraday_7571.csv.gz  in=455,146,084 out=113,089,395 elapsed=210.9s

  [18659/21087] intraday_7570.csv.gz  in=455,152,112 out=113,089,395 elapsed=210.9s

  [18660/21087] intraday_7572.csv.gz  in=455,155,633 out=113,089,395 elapsed=210.9s

  [18661/21087] intraday_7573.csv.gz  in=455,159,994 out=113,089,395 elapsed=210.9s

  [18662/21087] intraday_7574.csv.gz  in=455,162,425 out=113,089,395 elapsed=210.9s

  [18663/21087] intraday_7575.csv.gz  in=455,164,920 out=113,089,395 elapsed=210.9s

  [18664/21087] intraday_7577.csv.gz  in=455,167,580 out=113,089,395 elapsed=210.9s

  [18665/21087] intraday_7576.csv.gz  in=455,175,098 out=113,089,395 elapsed=210.9s

  [18666/21087] intraday_7579.csv.gz  in=455,178,344 out=113,089,395 elapsed=210.9s

  [18667/21087] intraday_7578.csv.gz  in=455,184,842 out=113,089,395 elapsed=210.9s

  [18668/21087] intraday_7580.csv.gz  in=455,189,275 out=113,089,395 elapsed=210.9s

  [18669/21087] intraday_7581.csv.gz  in=455,193,639 out=113,089,395 elapsed=210.9s

  [18670/21087] intraday_7583.csv.gz  in=455,196,810 out=113,089,395 elapsed=210.9s

  [18671/21087] intraday_7582.csv.gz  in=455,199,660 out=113,089,395 elapsed=210.9s

  [18672/21087] intraday_7584.csv.gz  in=455,201,782 out=113,089,395 elapsed=210.9s

  [18673/21087] intraday_7585.csv.gz  in=455,204,177 out=113,089,395 elapsed=211.0s

  [18674/21087] intraday_7586.csv.gz  in=455,206,780 out=113,089,395 elapsed=211.0s

  [18675/21087] intraday_7587.csv.gz  in=455,208,870 out=113,089,395 elapsed=211.0s

  [18676/21087] intraday_7588.csv.gz  in=455,214,405 out=113,089,395 elapsed=211.0s

  [18677/21087] intraday_7589.csv.gz  in=455,218,360 out=113,089,395 elapsed=211.0s

  [18678/21087] intraday_7590.csv.gz  in=455,222,706 out=113,089,395 elapsed=211.0s

  [18679/21087] intraday_7591.csv.gz  in=455,227,981 out=113,089,395 elapsed=211.0s

  [18680/21087] intraday_7592.csv.gz  in=455,229,923 out=113,089,395 elapsed=211.0s

  [18681/21087] intraday_7593.csv.gz  in=455,233,062 out=113,089,395 elapsed=211.0s

  [18682/21087] intraday_7594.csv.gz  in=455,235,829 out=113,089,395 elapsed=211.0s

  [18683/21087] intraday_7595.csv.gz  in=455,238,353 out=113,089,395 elapsed=211.0s

  [18684/21087] intraday_7596.csv.gz  in=455,241,272 out=113,089,395 elapsed=211.0s

  [18685/21087] intraday_7598.csv.gz  in=455,243,901 out=113,089,395 elapsed=211.0s

  [18686/21087] intraday_7599.csv.gz  in=455,246,307 out=113,089,395 elapsed=211.0s

  [18687/21087] intraday_7597.csv.gz  in=455,249,109 out=113,089,395 elapsed=211.0s

  [18688/21087] intraday_7600.csv.gz  in=455,250,960 out=113,089,395 elapsed=211.0s

  [18689/21087] intraday_7602.csv.gz  in=455,253,011 out=113,089,395 elapsed=211.1s

  [18690/21087] intraday_7601.csv.gz  in=455,256,159 out=113,089,395 elapsed=211.1s

  [18691/21087] intraday_7603.csv.gz  in=455,258,775 out=113,089,395 elapsed=211.1s

  [18692/21087] intraday_7604.csv.gz  in=455,261,712 out=113,089,395 elapsed=211.1s

  [18693/21087] intraday_7605.csv.gz  in=455,263,705 out=113,089,395 elapsed=211.1s

  [18694/21087] intraday_7606.csv.gz  in=455,266,578 out=113,089,395 elapsed=211.1s

  [18695/21087] intraday_7608.csv.gz  in=455,266,583 out=113,089,395 elapsed=211.1s

  [18696/21087] intraday_7607.csv.gz  in=455,267,715 out=113,089,395 elapsed=211.1s

  [18697/21087] intraday_7609.csv.gz  in=455,285,583 out=113,089,395 elapsed=211.1s

  [18698/21087] intraday_7610.csv.gz  in=455,298,261 out=113,089,395 elapsed=211.1s

  [18699/21087] intraday_7611.csv.gz  in=455,311,638 out=113,089,395 elapsed=211.1s

  [18700/21087] intraday_7612.csv.gz  in=455,323,362 out=113,089,395 elapsed=211.1s

  [18701/21087] intraday_7613.csv.gz  in=455,338,197 out=113,089,395 elapsed=211.1s

  [18702/21087] intraday_7614.csv.gz  in=455,353,981 out=113,089,395 elapsed=211.2s

  [18703/21087] intraday_7615.csv.gz  in=455,367,638 out=113,089,395 elapsed=211.2s

  [18704/21087] intraday_7616.csv.gz  in=455,381,318 out=113,089,395 elapsed=211.2s

  [18705/21087] intraday_7617.csv.gz  in=455,394,577 out=113,089,395 elapsed=211.2s

  [18706/21087] intraday_7618.csv.gz  in=455,408,706 out=113,089,395 elapsed=211.2s

  [18707/21087] intraday_7619.csv.gz  in=455,422,924 out=113,089,395 elapsed=211.2s

  [18708/21087] intraday_7620.csv.gz  in=455,438,257 out=113,089,395 elapsed=211.2s

  [18709/21087] intraday_7621.csv.gz  in=455,451,538 out=113,089,395 elapsed=211.2s

  [18710/21087] intraday_7622.csv.gz  in=455,464,961 out=113,089,395 elapsed=211.2s

  [18711/21087] intraday_7623.csv.gz  in=455,476,114 out=113,089,395 elapsed=211.2s

  [18712/21087] intraday_7624.csv.gz  in=455,486,874 out=113,089,395 elapsed=211.2s

  [18713/21087] intraday_7625.csv.gz  in=455,501,195 out=113,089,395 elapsed=211.2s

  [18714/21087] intraday_7626.csv.gz  in=455,514,780 out=113,089,395 elapsed=211.3s

  [18715/21087] intraday_7628.csv.gz  in=455,525,318 out=113,089,395 elapsed=211.3s

  [18716/21087] intraday_7627.csv.gz  in=455,537,912 out=113,089,395 elapsed=211.3s

  [18717/21087] intraday_7629.csv.gz  in=455,551,245 out=113,089,395 elapsed=211.3s

  [18718/21087] intraday_7631.csv.gz  in=455,562,692 out=113,089,395 elapsed=211.3s

  [18719/21087] intraday_7630.csv.gz  in=455,576,794 out=113,089,395 elapsed=211.3s

  [18720/21087] intraday_7632.csv.gz  in=455,591,694 out=113,089,395 elapsed=211.3s

  [18721/21087] intraday_7633.csv.gz  in=455,605,373 out=113,089,395 elapsed=211.3s

  [18722/21087] intraday_7634.csv.gz  in=455,618,897 out=113,089,395 elapsed=211.3s

  [18723/21087] intraday_7635.csv.gz  in=455,632,435 out=113,089,395 elapsed=211.3s

  [18724/21087] intraday_7636.csv.gz  in=455,645,289 out=113,089,395 elapsed=211.3s

  [18725/21087] intraday_7637.csv.gz  in=455,657,801 out=113,089,395 elapsed=211.3s

  [18726/21087] intraday_7638.csv.gz  in=455,670,770 out=113,089,395 elapsed=211.3s

  [18727/21087] intraday_7639.csv.gz  in=455,685,969 out=113,089,395 elapsed=211.4s

  [18728/21087] intraday_7641.csv.gz  in=455,697,123 out=113,089,395 elapsed=211.4s

  [18729/21087] intraday_7640.csv.gz  in=455,710,177 out=113,089,395 elapsed=211.4s

  [18730/21087] intraday_7642.csv.gz  in=455,724,810 out=113,089,395 elapsed=211.4s

  [18731/21087] intraday_7643.csv.gz  in=455,739,198 out=113,089,395 elapsed=211.4s

  [18732/21087] intraday_7644.csv.gz  in=455,751,640 out=113,089,395 elapsed=211.4s

  [18733/21087] intraday_7645.csv.gz  in=455,765,802 out=113,089,395 elapsed=211.4s

  [18734/21087] intraday_7646.csv.gz  in=455,777,527 out=113,089,395 elapsed=211.4s

  [18735/21087] intraday_7648.csv.gz  in=455,788,091 out=113,089,395 elapsed=211.4s

  [18736/21087] intraday_7647.csv.gz  in=455,800,442 out=113,089,395 elapsed=211.4s

  [18737/21087] intraday_7649.csv.gz  in=455,813,480 out=113,089,395 elapsed=211.4s

  [18738/21087] intraday_7650.csv.gz  in=455,828,507 out=113,089,395 elapsed=211.4s

  [18739/21087] intraday_7652.csv.gz  in=455,840,808 out=113,089,395 elapsed=211.5s

  [18740/21087] intraday_7651.csv.gz  in=455,853,741 out=113,089,395 elapsed=211.5s

  [18741/21087] intraday_7654.csv.gz  in=455,866,411 out=113,089,395 elapsed=211.5s

  [18742/21087] intraday_7653.csv.gz  in=455,882,684 out=113,089,395 elapsed=211.5s

  [18743/21087] intraday_7655.csv.gz  in=455,895,421 out=113,089,395 elapsed=211.5s

  [18744/21087] intraday_7656.csv.gz  in=455,907,868 out=113,089,395 elapsed=211.5s

  [18745/21087] intraday_7657.csv.gz  in=455,920,239 out=113,089,395 elapsed=211.5s

  [18746/21087] intraday_7658.csv.gz  in=455,932,277 out=113,089,395 elapsed=211.5s

  [18747/21087] intraday_7659.csv.gz  in=455,944,001 out=113,089,395 elapsed=211.5s

  [18748/21087] intraday_7660.csv.gz  in=455,957,238 out=113,089,395 elapsed=211.5s

  [18749/21087] intraday_7661.csv.gz  in=455,969,921 out=113,089,395 elapsed=211.5s

  [18750/21087] intraday_7662.csv.gz  in=455,985,033 out=113,089,395 elapsed=211.5s

  [18751/21087] intraday_7663.csv.gz  in=456,000,174 out=113,089,395 elapsed=211.6s

  [18752/21087] intraday_7664.csv.gz  in=456,012,815 out=113,089,395 elapsed=211.6s

  [18753/21087] intraday_7665.csv.gz  in=456,026,484 out=113,089,395 elapsed=211.6s

  [18754/21087] intraday_7666.csv.gz  in=456,036,987 out=113,089,395 elapsed=211.6s

  [18755/21087] intraday_7667.csv.gz  in=456,051,133 out=113,089,395 elapsed=211.6s

  [18756/21087] intraday_7668.csv.gz  in=456,065,145 out=113,089,395 elapsed=211.6s

  [18757/21087] intraday_7669.csv.gz  in=456,077,070 out=113,089,395 elapsed=211.6s

  [18758/21087] intraday_7670.csv.gz  in=456,090,763 out=113,089,395 elapsed=211.6s

  [18759/21087] intraday_7671.csv.gz  in=456,103,389 out=113,089,395 elapsed=211.6s

  [18760/21087] intraday_7672.csv.gz  in=456,114,614 out=113,089,395 elapsed=211.6s

  [18761/21087] intraday_7673.csv.gz  in=456,127,719 out=113,089,395 elapsed=211.6s

  [18762/21087] intraday_7674.csv.gz  in=456,141,555 out=113,089,395 elapsed=211.6s

  [18763/21087] intraday_7676.csv.gz  in=456,156,858 out=113,089,395 elapsed=211.7s

  [18764/21087] intraday_7675.csv.gz  in=456,172,567 out=113,089,395 elapsed=211.7s

  [18765/21087] intraday_7677.csv.gz  in=456,186,330 out=113,089,395 elapsed=211.7s

  [18766/21087] intraday_7678.csv.gz  in=456,198,329 out=113,089,395 elapsed=211.7s

  [18767/21087] intraday_7679.csv.gz  in=456,210,300 out=113,089,395 elapsed=211.7s

  [18768/21087] intraday_7680.csv.gz  in=456,222,485 out=113,089,395 elapsed=211.7s

  [18769/21087] intraday_7681.csv.gz  in=456,235,158 out=113,089,395 elapsed=211.7s

  [18770/21087] intraday_7682.csv.gz  in=456,249,211 out=113,089,395 elapsed=211.7s

  [18771/21087] intraday_7683.csv.gz  in=456,262,084 out=113,089,395 elapsed=211.7s

  [18772/21087] intraday_7684.csv.gz  in=456,272,499 out=113,089,395 elapsed=211.7s

  [18773/21087] intraday_7685.csv.gz  in=456,284,246 out=113,089,395 elapsed=211.7s

  [18774/21087] intraday_7686.csv.gz  in=456,298,208 out=113,089,395 elapsed=211.7s

  [18775/21087] intraday_7687.csv.gz  in=456,309,240 out=113,089,395 elapsed=211.8s

  [18776/21087] intraday_7689.csv.gz  in=456,320,144 out=113,089,395 elapsed=211.8s

  [18777/21087] intraday_7688.csv.gz  in=456,332,559 out=113,089,395 elapsed=211.8s

  [18778/21087] intraday_7690.csv.gz  in=456,345,034 out=113,089,395 elapsed=211.8s

  [18779/21087] intraday_7691.csv.gz  in=456,358,212 out=113,089,395 elapsed=211.8s

  [18780/21087] intraday_7692.csv.gz  in=456,375,998 out=113,089,395 elapsed=211.8s

  [18781/21087] intraday_7693.csv.gz  in=456,391,594 out=113,089,395 elapsed=211.8s

  [18782/21087] intraday_7694.csv.gz  in=456,405,274 out=113,089,395 elapsed=211.8s

  [18783/21087] intraday_7695.csv.gz  in=456,416,991 out=113,089,395 elapsed=211.8s

  [18784/21087] intraday_7696.csv.gz  in=456,430,708 out=113,089,395 elapsed=211.8s

  [18785/21087] intraday_7698.csv.gz  in=456,447,286 out=113,089,395 elapsed=211.8s

  [18786/21087] intraday_7697.csv.gz  in=456,463,798 out=113,089,395 elapsed=211.8s

  [18787/21087] intraday_7699.csv.gz  in=456,477,492 out=113,089,395 elapsed=211.8s

  [18788/21087] intraday_7700.csv.gz  in=456,491,238 out=113,089,395 elapsed=211.8s

  [18789/21087] intraday_7701.csv.gz  in=456,505,127 out=113,089,395 elapsed=211.9s

  [18790/21087] intraday_7702.csv.gz  in=456,518,442 out=113,089,395 elapsed=211.9s

  [18791/21087] intraday_7704.csv.gz  in=456,532,004 out=113,089,395 elapsed=211.9s

  [18792/21087] intraday_7703.csv.gz  in=456,545,997 out=113,089,395 elapsed=211.9s

  [18793/21087] intraday_7705.csv.gz  in=456,558,816 out=113,089,395 elapsed=211.9s

  [18794/21087] intraday_7706.csv.gz  in=456,571,520 out=113,089,395 elapsed=211.9s

  [18795/21087] intraday_7708.csv.gz  in=456,585,298 out=113,089,395 elapsed=211.9s

  [18796/21087] intraday_7707.csv.gz  in=456,599,074 out=113,089,395 elapsed=211.9s

  [18797/21087] intraday_7709.csv.gz  in=456,609,497 out=113,089,395 elapsed=211.9s

  [18798/21087] intraday_7710.csv.gz  in=456,622,360 out=113,089,395 elapsed=211.9s

  [18799/21087] intraday_7711.csv.gz  in=456,638,153 out=113,089,395 elapsed=212.0s

  [18800/21087] intraday_7712.csv.gz  in=456,651,984 out=113,089,395 elapsed=212.0s

  [18801/21087] intraday_7713.csv.gz  in=456,666,196 out=113,089,395 elapsed=212.0s

  [18802/21087] intraday_7714.csv.gz  in=456,678,369 out=113,089,395 elapsed=212.0s

  [18803/21087] intraday_7715.csv.gz  in=456,694,862 out=113,089,395 elapsed=212.0s

  [18804/21087] intraday_7716.csv.gz  in=456,709,097 out=113,089,395 elapsed=212.0s

  [18805/21087] intraday_7718.csv.gz  in=456,724,174 out=113,089,395 elapsed=212.0s

  [18806/21087] intraday_7717.csv.gz  in=456,738,628 out=113,089,395 elapsed=212.0s

  [18807/21087] intraday_7719.csv.gz  in=456,752,959 out=113,089,395 elapsed=212.0s

  [18808/21087] intraday_7720.csv.gz  in=456,764,231 out=113,089,395 elapsed=212.0s

  [18809/21087] intraday_7721.csv.gz  in=456,779,144 out=113,089,395 elapsed=212.0s

  [18810/21087] intraday_7722.csv.gz  in=456,792,322 out=113,089,395 elapsed=212.0s

  [18811/21087] intraday_7723.csv.gz  in=456,805,936 out=113,089,395 elapsed=212.0s

  [18812/21087] intraday_7724.csv.gz  in=456,823,065 out=113,089,395 elapsed=212.1s

  [18813/21087] intraday_7725.csv.gz  in=456,838,789 out=113,089,395 elapsed=212.1s

  [18814/21087] intraday_7726.csv.gz  in=456,854,374 out=113,089,395 elapsed=212.1s

  [18815/21087] intraday_7727.csv.gz  in=456,869,536 out=113,089,395 elapsed=212.1s

  [18816/21087] intraday_7728.csv.gz  in=456,881,567 out=113,089,395 elapsed=212.1s

  [18817/21087] intraday_7730.csv.gz  in=456,893,083 out=113,089,395 elapsed=212.1s

  [18818/21087] intraday_7729.csv.gz  in=456,907,418 out=113,089,395 elapsed=212.1s

  [18819/21087] intraday_7731.csv.gz  in=456,922,861 out=113,089,395 elapsed=212.1s

  [18820/21087] intraday_7732.csv.gz  in=456,933,745 out=113,089,395 elapsed=212.1s

  [18821/21087] intraday_7733.csv.gz  in=456,948,922 out=113,089,395 elapsed=212.1s

  [18822/21087] intraday_7734.csv.gz  in=456,961,887 out=113,089,395 elapsed=212.1s

  [18823/21087] intraday_7735.csv.gz  in=456,977,497 out=113,089,395 elapsed=212.1s

  [18824/21087] intraday_7736.csv.gz  in=456,989,316 out=113,089,395 elapsed=212.1s

  [18825/21087] intraday_7737.csv.gz  in=457,002,986 out=113,089,395 elapsed=212.2s

  [18826/21087] intraday_7738.csv.gz  in=457,016,336 out=113,089,395 elapsed=212.2s

  [18827/21087] intraday_7740.csv.gz  in=457,029,405 out=113,089,395 elapsed=212.2s

  [18828/21087] intraday_7739.csv.gz  in=457,041,392 out=113,089,395 elapsed=212.2s

  [18829/21087] intraday_7741.csv.gz  in=457,056,244 out=113,089,395 elapsed=212.2s

  [18830/21087] intraday_7742.csv.gz  in=457,070,985 out=113,089,395 elapsed=212.2s

  [18831/21087] intraday_7743.csv.gz  in=457,085,748 out=113,089,395 elapsed=212.2s

  [18832/21087] intraday_7744.csv.gz  in=457,100,173 out=113,089,395 elapsed=212.2s

  [18833/21087] intraday_7745.csv.gz  in=457,111,884 out=113,089,395 elapsed=212.2s

  [18834/21087] intraday_7746.csv.gz  in=457,124,126 out=113,089,395 elapsed=212.2s

  [18835/21087] intraday_7747.csv.gz  in=457,138,499 out=113,089,395 elapsed=212.2s

  [18836/21087] intraday_7748.csv.gz  in=457,151,300 out=113,089,395 elapsed=212.3s

  [18837/21087] intraday_7749.csv.gz  in=457,163,826 out=113,089,395 elapsed=212.3s

  [18838/21087] intraday_7750.csv.gz  in=457,173,068 out=113,089,395 elapsed=212.3s

  [18839/21087] intraday_7752.csv.gz  in=457,181,536 out=113,089,395 elapsed=212.3s

  [18840/21087] intraday_7751.csv.gz  in=457,194,028 out=113,089,395 elapsed=212.3s

  [18841/21087] intraday_7753.csv.gz  in=457,209,771 out=113,089,395 elapsed=212.3s

  [18842/21087] intraday_7754.csv.gz  in=457,223,313 out=113,089,395 elapsed=212.3s

  [18843/21087] intraday_7755.csv.gz  in=457,235,468 out=113,089,395 elapsed=212.3s

  [18844/21087] intraday_7756.csv.gz  in=457,248,608 out=113,089,395 elapsed=212.3s

  [18845/21087] intraday_7758.csv.gz  in=457,262,599 out=113,089,395 elapsed=212.3s

  [18846/21087] intraday_7757.csv.gz  in=457,273,825 out=113,089,395 elapsed=212.3s

  [18847/21087] intraday_7759.csv.gz  in=457,291,191 out=113,089,395 elapsed=212.4s

  [18848/21087] intraday_7760.csv.gz  in=457,301,978 out=113,089,395 elapsed=212.4s

  [18849/21087] intraday_7761.csv.gz  in=457,315,284 out=113,089,395 elapsed=212.4s

  [18850/21087] intraday_7762.csv.gz  in=457,329,030 out=113,089,395 elapsed=212.4s

  [18851/21087] intraday_7764.csv.gz  in=457,340,901 out=113,089,395 elapsed=212.4s

  [18852/21087] intraday_7763.csv.gz  in=457,355,851 out=113,089,395 elapsed=212.4s

  [18853/21087] intraday_7765.csv.gz  in=457,369,855 out=113,089,395 elapsed=212.4s

  [18854/21087] intraday_7767.csv.gz  in=457,379,979 out=113,089,395 elapsed=212.4s

  [18855/21087] intraday_7766.csv.gz  in=457,392,941 out=113,089,395 elapsed=212.4s

  [18856/21087] intraday_7768.csv.gz  in=457,405,337 out=113,089,395 elapsed=212.4s

  [18857/21087] intraday_7769.csv.gz  in=457,419,718 out=113,089,395 elapsed=212.5s

  [18858/21087] intraday_7771.csv.gz  in=457,430,531 out=113,089,395 elapsed=212.5s

  [18859/21087] intraday_7770.csv.gz  in=457,444,781 out=113,089,395 elapsed=212.5s

  [18860/21087] intraday_7772.csv.gz  in=457,456,956 out=113,089,395 elapsed=212.5s

  [18861/21087] intraday_7773.csv.gz  in=457,468,878 out=113,089,395 elapsed=212.5s

  [18862/21087] intraday_7774.csv.gz  in=457,482,151 out=113,089,395 elapsed=212.5s

  [18863/21087] intraday_7776.csv.gz  in=457,497,392 out=113,089,395 elapsed=212.5s

  [18864/21087] intraday_7775.csv.gz  in=457,508,600 out=113,089,395 elapsed=212.5s

  [18865/21087] intraday_7777.csv.gz  in=457,521,582 out=113,089,395 elapsed=212.5s

  [18866/21087] intraday_7778.csv.gz  in=457,537,833 out=113,089,395 elapsed=212.5s

  [18867/21087] intraday_7779.csv.gz  in=457,549,421 out=113,089,395 elapsed=212.5s

  [18868/21087] intraday_7780.csv.gz  in=457,562,380 out=113,089,395 elapsed=212.5s

  [18869/21087] intraday_7781.csv.gz  in=457,575,625 out=113,089,395 elapsed=212.5s

  [18870/21087] intraday_7782.csv.gz  in=457,588,000 out=113,089,395 elapsed=212.5s

  [18871/21087] intraday_7783.csv.gz  in=457,603,934 out=113,089,395 elapsed=212.6s

  [18872/21087] intraday_7784.csv.gz  in=457,617,384 out=113,089,395 elapsed=212.6s

  [18873/21087] intraday_7785.csv.gz  in=457,627,878 out=113,089,395 elapsed=212.6s

  [18874/21087] intraday_7786.csv.gz  in=457,640,891 out=113,089,395 elapsed=212.6s

  [18875/21087] intraday_7787.csv.gz  in=457,654,739 out=113,089,395 elapsed=212.6s

  [18876/21087] intraday_7788.csv.gz  in=457,667,289 out=113,089,395 elapsed=212.6s

  [18877/21087] intraday_7789.csv.gz  in=457,681,209 out=113,089,395 elapsed=212.6s

  [18878/21087] intraday_7790.csv.gz  in=457,693,345 out=113,089,395 elapsed=212.6s

  [18879/21087] intraday_7791.csv.gz  in=457,706,022 out=113,089,395 elapsed=212.6s

  [18880/21087] intraday_7792.csv.gz  in=457,717,119 out=113,089,395 elapsed=212.6s

  [18881/21087] intraday_7793.csv.gz  in=457,729,280 out=113,089,395 elapsed=212.6s

  [18882/21087] intraday_7794.csv.gz  in=457,743,171 out=113,089,395 elapsed=212.6s

  [18883/21087] intraday_7795.csv.gz  in=457,757,334 out=113,089,395 elapsed=212.7s

  [18884/21087] intraday_7796.csv.gz  in=457,768,155 out=113,089,395 elapsed=212.7s

  [18885/21087] intraday_7797.csv.gz  in=457,783,866 out=113,089,395 elapsed=212.7s

  [18886/21087] intraday_7798.csv.gz  in=457,795,728 out=113,089,395 elapsed=212.7s

  [18887/21087] intraday_7799.csv.gz  in=457,807,848 out=113,089,395 elapsed=212.7s

  [18888/21087] intraday_7800.csv.gz  in=457,821,576 out=113,089,395 elapsed=212.7s

  [18889/21087] intraday_7801.csv.gz  in=457,832,779 out=113,089,395 elapsed=212.7s

  [18890/21087] intraday_7802.csv.gz  in=457,844,811 out=113,089,395 elapsed=212.7s

  [18891/21087] intraday_7803.csv.gz  in=457,856,683 out=113,089,395 elapsed=212.7s

  [18892/21087] intraday_7804.csv.gz  in=457,868,128 out=113,089,395 elapsed=212.7s

  [18893/21087] intraday_7805.csv.gz  in=457,883,015 out=113,089,395 elapsed=212.7s

  [18894/21087] intraday_7806.csv.gz  in=457,896,492 out=113,089,395 elapsed=212.7s

  [18895/21087] intraday_7807.csv.gz  in=457,910,324 out=113,089,395 elapsed=212.7s

  [18896/21087] intraday_7808.csv.gz  in=457,924,250 out=113,089,395 elapsed=212.8s

  [18897/21087] intraday_7809.csv.gz  in=457,937,538 out=113,089,395 elapsed=212.8s

  [18898/21087] intraday_7810.csv.gz  in=457,949,651 out=113,089,395 elapsed=212.8s

  [18899/21087] intraday_7811.csv.gz  in=457,964,635 out=113,089,395 elapsed=212.8s

  [18900/21087] intraday_7812.csv.gz  in=457,976,406 out=113,089,395 elapsed=212.8s

  [18901/21087] intraday_7813.csv.gz  in=457,991,843 out=113,089,395 elapsed=212.8s

  [18902/21087] intraday_7814.csv.gz  in=458,004,905 out=113,089,395 elapsed=212.8s

  [18903/21087] intraday_7815.csv.gz  in=458,016,191 out=113,089,395 elapsed=212.8s

  [18904/21087] intraday_7816.csv.gz  in=458,028,383 out=113,089,395 elapsed=212.8s

  [18905/21087] intraday_7817.csv.gz  in=458,039,242 out=113,089,395 elapsed=212.8s

  [18906/21087] intraday_7818.csv.gz  in=458,053,010 out=113,089,395 elapsed=212.8s

  [18907/21087] intraday_7819.csv.gz  in=458,067,708 out=113,089,395 elapsed=212.8s

  [18908/21087] intraday_7820.csv.gz  in=458,082,970 out=113,089,395 elapsed=212.9s

  [18909/21087] intraday_7821.csv.gz  in=458,095,720 out=113,089,395 elapsed=212.9s

  [18910/21087] intraday_7822.csv.gz  in=458,107,295 out=113,089,395 elapsed=212.9s

  [18911/21087] intraday_7823.csv.gz  in=458,119,816 out=113,089,395 elapsed=212.9s

  [18912/21087] intraday_7824.csv.gz  in=458,131,418 out=113,089,395 elapsed=212.9s

  [18913/21087] intraday_7825.csv.gz  in=458,144,785 out=113,089,395 elapsed=212.9s

  [18914/21087] intraday_7827.csv.gz  in=458,156,391 out=113,089,395 elapsed=212.9s

  [18915/21087] intraday_7826.csv.gz  in=458,170,230 out=113,089,395 elapsed=212.9s

  [18916/21087] intraday_7828.csv.gz  in=458,181,995 out=113,089,395 elapsed=212.9s

  [18917/21087] intraday_7829.csv.gz  in=458,193,097 out=113,089,395 elapsed=212.9s

  [18918/21087] intraday_7831.csv.gz  in=458,203,733 out=113,089,395 elapsed=212.9s

  [18919/21087] intraday_7832.csv.gz  in=458,215,482 out=113,089,395 elapsed=212.9s

  [18920/21087] intraday_7830.csv.gz  in=458,228,673 out=113,089,395 elapsed=213.0s

  [18921/21087] intraday_7833.csv.gz  in=458,239,442 out=113,089,395 elapsed=213.0s

  [18922/21087] intraday_7835.csv.gz  in=458,251,583 out=113,089,395 elapsed=213.0s

  [18923/21087] intraday_7834.csv.gz  in=458,264,830 out=113,089,395 elapsed=213.0s

  [18924/21087] intraday_7836.csv.gz  in=458,283,601 out=113,089,395 elapsed=213.0s

  [18925/21087] intraday_7837.csv.gz  in=458,299,953 out=113,089,395 elapsed=213.0s

  [18926/21087] intraday_7838.csv.gz  in=458,312,889 out=113,089,395 elapsed=213.0s

  [18927/21087] intraday_7839.csv.gz  in=458,324,725 out=113,089,395 elapsed=213.0s

  [18928/21087] intraday_7840.csv.gz  in=458,336,186 out=113,089,395 elapsed=213.0s

  [18929/21087] intraday_7841.csv.gz  in=458,352,178 out=113,089,395 elapsed=213.0s

  [18930/21087] intraday_7842.csv.gz  in=458,366,541 out=113,089,395 elapsed=213.0s

  [18931/21087] intraday_7844.csv.gz  in=458,378,262 out=113,089,395 elapsed=213.0s

  [18932/21087] intraday_7843.csv.gz  in=458,393,550 out=113,089,395 elapsed=213.1s

  [18933/21087] intraday_7845.csv.gz  in=458,408,486 out=113,089,395 elapsed=213.1s

  [18934/21087] intraday_7846.csv.gz  in=458,423,302 out=113,089,395 elapsed=213.1s

  [18935/21087] intraday_7847.csv.gz  in=458,435,346 out=113,089,395 elapsed=213.1s

  [18936/21087] intraday_7848.csv.gz  in=458,450,157 out=113,089,395 elapsed=213.1s

  [18937/21087] intraday_7849.csv.gz  in=458,461,860 out=113,089,395 elapsed=213.1s

  [18938/21087] intraday_7850.csv.gz  in=458,474,563 out=113,089,395 elapsed=213.1s

  [18939/21087] intraday_7852.csv.gz  in=458,487,103 out=113,089,395 elapsed=213.1s

  [18940/21087] intraday_7851.csv.gz  in=458,500,327 out=113,089,395 elapsed=213.1s

  [18941/21087] intraday_7853.csv.gz  in=458,512,120 out=113,089,395 elapsed=213.1s

  [18942/21087] intraday_7854.csv.gz  in=458,526,915 out=113,089,395 elapsed=213.1s

  [18943/21087] intraday_7855.csv.gz  in=458,538,882 out=113,089,395 elapsed=213.1s

  [18944/21087] intraday_7856.csv.gz  in=458,555,313 out=113,089,395 elapsed=213.2s

  [18945/21087] intraday_7857.csv.gz  in=458,566,894 out=113,089,395 elapsed=213.2s

  [18946/21087] intraday_7858.csv.gz  in=458,579,276 out=113,089,395 elapsed=213.2s

  [18947/21087] intraday_7859.csv.gz  in=458,596,035 out=113,089,395 elapsed=213.2s

  [18948/21087] intraday_7861.csv.gz  in=458,608,286 out=113,089,395 elapsed=213.2s

  [18949/21087] intraday_7860.csv.gz  in=458,623,469 out=113,089,395 elapsed=213.2s

  [18950/21087] intraday_7862.csv.gz  in=458,639,217 out=113,089,395 elapsed=213.2s

  [18951/21087] intraday_7863.csv.gz  in=458,653,848 out=113,089,395 elapsed=213.2s

  [18952/21087] intraday_7864.csv.gz  in=458,664,050 out=113,089,395 elapsed=213.2s

  [18953/21087] intraday_7865.csv.gz  in=458,677,461 out=113,089,395 elapsed=213.2s

  [18954/21087] intraday_7866.csv.gz  in=458,690,784 out=113,089,395 elapsed=213.2s

  [18955/21087] intraday_7867.csv.gz  in=458,705,455 out=113,089,395 elapsed=213.2s

  [18956/21087] intraday_7868.csv.gz  in=458,725,063 out=113,089,395 elapsed=213.2s

  [18957/21087] intraday_7869.csv.gz  in=458,740,790 out=113,089,395 elapsed=213.2s

  [18958/21087] intraday_7870.csv.gz  in=458,753,848 out=113,089,395 elapsed=213.3s

  [18959/21087] intraday_7871.csv.gz  in=458,770,704 out=113,089,395 elapsed=213.3s

  [18960/21087] intraday_7872.csv.gz  in=458,784,095 out=113,089,395 elapsed=213.3s

  [18961/21087] intraday_7873.csv.gz  in=458,795,938 out=113,089,395 elapsed=213.3s

  [18962/21087] intraday_7874.csv.gz  in=458,808,312 out=113,089,395 elapsed=213.3s

  [18963/21087] intraday_7875.csv.gz  in=458,822,326 out=113,089,395 elapsed=213.3s

  [18964/21087] intraday_7876.csv.gz  in=458,833,710 out=113,089,395 elapsed=213.3s

  [18965/21087] intraday_7877.csv.gz  in=458,847,767 out=113,089,395 elapsed=213.3s

  [18966/21087] intraday_7878.csv.gz  in=458,860,204 out=113,089,395 elapsed=213.3s

  [18967/21087] intraday_7879.csv.gz  in=458,873,928 out=113,089,395 elapsed=213.3s

  [18968/21087] intraday_7880.csv.gz  in=458,888,843 out=113,089,395 elapsed=213.3s

  [18969/21087] intraday_7881.csv.gz  in=458,900,427 out=113,089,395 elapsed=213.3s

  [18970/21087] intraday_7882.csv.gz  in=458,914,330 out=113,089,395 elapsed=213.3s

  [18971/21087] intraday_7883.csv.gz  in=458,927,059 out=113,089,395 elapsed=213.4s

  [18972/21087] intraday_7884.csv.gz  in=458,939,504 out=113,089,395 elapsed=213.4s

  [18973/21087] intraday_7885.csv.gz  in=458,951,953 out=113,089,395 elapsed=213.4s

  [18974/21087] intraday_7886.csv.gz  in=458,967,119 out=113,089,395 elapsed=213.4s

  [18975/21087] intraday_7887.csv.gz  in=458,980,771 out=113,089,395 elapsed=213.4s

  [18976/21087] intraday_7888.csv.gz  in=458,992,985 out=113,089,395 elapsed=213.4s

  [18977/21087] intraday_7889.csv.gz  in=459,007,932 out=113,089,395 elapsed=213.4s

  [18978/21087] intraday_7890.csv.gz  in=459,019,258 out=113,089,395 elapsed=213.4s

  [18979/21087] intraday_7891.csv.gz  in=459,032,415 out=113,089,395 elapsed=213.4s

  [18980/21087] intraday_7892.csv.gz  in=459,043,767 out=113,089,395 elapsed=213.4s

  [18981/21087] intraday_7893.csv.gz  in=459,058,162 out=113,089,395 elapsed=213.4s

  [18982/21087] intraday_7894.csv.gz  in=459,068,406 out=113,089,395 elapsed=213.4s

  [18983/21087] intraday_7895.csv.gz  in=459,079,051 out=113,089,395 elapsed=213.4s

  [18984/21087] intraday_7896.csv.gz  in=459,092,788 out=113,089,395 elapsed=213.5s

  [18985/21087] intraday_7897.csv.gz  in=459,094,449 out=113,089,395 elapsed=213.5s

  [18986/21087] intraday_7898.csv.gz  in=459,111,382 out=113,089,395 elapsed=213.5s

  [18987/21087] intraday_7899.csv.gz  in=459,127,542 out=113,089,395 elapsed=213.5s

  [18988/21087] intraday_7900.csv.gz  in=459,142,921 out=113,089,395 elapsed=213.5s

  [18989/21087] intraday_7901.csv.gz  in=459,156,177 out=113,089,395 elapsed=213.5s

  [18990/21087] intraday_7902.csv.gz  in=459,167,608 out=113,089,395 elapsed=213.5s

  [18991/21087] intraday_7903.csv.gz  in=459,178,197 out=113,089,395 elapsed=213.5s

  [18992/21087] intraday_7904.csv.gz  in=459,192,450 out=113,089,395 elapsed=213.5s

  [18993/21087] intraday_7905.csv.gz  in=459,208,074 out=113,089,395 elapsed=213.5s

  [18994/21087] intraday_7906.csv.gz  in=459,219,706 out=113,089,395 elapsed=213.5s

  [18995/21087] intraday_7907.csv.gz  in=459,233,483 out=113,089,395 elapsed=213.5s

  [18996/21087] intraday_7908.csv.gz  in=459,247,487 out=113,089,395 elapsed=213.5s

  [18997/21087] intraday_7909.csv.gz  in=459,262,892 out=113,089,395 elapsed=213.6s

  [18998/21087] intraday_7910.csv.gz  in=459,275,788 out=113,089,395 elapsed=213.6s

  [18999/21087] intraday_7911.csv.gz  in=459,289,305 out=113,089,395 elapsed=213.6s

  [19000/21087] intraday_7912.csv.gz  in=459,304,631 out=113,089,395 elapsed=213.6s

  [19001/21087] intraday_7914.csv.gz  in=459,314,568 out=113,089,395 elapsed=213.6s

  [19002/21087] intraday_7913.csv.gz  in=459,325,680 out=113,089,395 elapsed=213.6s

  [19003/21087] intraday_7915.csv.gz  in=459,339,942 out=113,089,395 elapsed=213.6s

  [19004/21087] intraday_7916.csv.gz  in=459,353,113 out=113,089,395 elapsed=213.6s

  [19005/21087] intraday_7917.csv.gz  in=459,363,919 out=113,089,395 elapsed=213.6s

  [19006/21087] intraday_7919.csv.gz  in=459,375,032 out=113,089,395 elapsed=213.6s

  [19007/21087] intraday_7918.csv.gz  in=459,386,464 out=113,089,395 elapsed=213.6s

  [19008/21087] intraday_7920.csv.gz  in=459,400,274 out=113,089,395 elapsed=213.6s

  [19009/21087] intraday_7921.csv.gz  in=459,412,384 out=113,089,395 elapsed=213.6s

  [19010/21087] intraday_7922.csv.gz  in=459,427,101 out=113,089,395 elapsed=213.7s

  [19011/21087] intraday_7923.csv.gz  in=459,441,392 out=113,089,395 elapsed=213.7s

  [19012/21087] intraday_7924.csv.gz  in=459,455,153 out=113,089,395 elapsed=213.7s

  [19013/21087] intraday_7925.csv.gz  in=459,468,467 out=113,089,395 elapsed=213.7s

  [19014/21087] intraday_7926.csv.gz  in=459,479,917 out=113,089,395 elapsed=213.7s

  [19015/21087] intraday_7927.csv.gz  in=459,492,047 out=113,089,395 elapsed=213.7s

  [19016/21087] intraday_7930.csv.gz  in=459,505,090 out=113,089,395 elapsed=213.7s

  [19017/21087] intraday_7928.csv.gz  in=459,519,341 out=113,089,395 elapsed=213.7s

  [19018/21087] intraday_7929.csv.gz  in=459,535,266 out=113,089,395 elapsed=213.7s

  [19019/21087] intraday_7931.csv.gz  in=459,545,078 out=113,089,395 elapsed=213.7s

  [19020/21087] intraday_7933.csv.gz  in=459,559,012 out=113,089,395 elapsed=213.7s

  [19021/21087] intraday_7932.csv.gz  in=459,573,501 out=113,089,395 elapsed=213.8s

  [19022/21087] intraday_7934.csv.gz  in=459,585,230 out=113,089,395 elapsed=213.8s

  [19023/21087] intraday_7935.csv.gz  in=459,598,373 out=113,089,395 elapsed=213.8s

  [19024/21087] intraday_7936.csv.gz  in=459,611,720 out=113,089,395 elapsed=213.8s

  [19025/21087] intraday_7938.csv.gz  in=459,622,420 out=113,089,395 elapsed=213.8s

  [19026/21087] intraday_7937.csv.gz  in=459,635,553 out=113,089,395 elapsed=213.8s

  [19027/21087] intraday_7939.csv.gz  in=459,647,834 out=113,089,395 elapsed=213.8s

  [19028/21087] intraday_7940.csv.gz  in=459,660,032 out=113,089,395 elapsed=213.8s

  [19029/21087] intraday_7942.csv.gz  in=459,672,070 out=113,089,395 elapsed=213.8s

  [19030/21087] intraday_7943.csv.gz  in=459,686,775 out=113,089,395 elapsed=213.8s

  [19031/21087] intraday_7941.csv.gz  in=459,701,349 out=113,089,395 elapsed=213.8s

  [19032/21087] intraday_7944.csv.gz  in=459,713,293 out=113,089,395 elapsed=213.8s

  [19033/21087] intraday_7945.csv.gz  in=459,724,551 out=113,089,395 elapsed=213.8s

  [19034/21087] intraday_7947.csv.gz  in=459,737,015 out=113,089,395 elapsed=213.9s

  [19035/21087] intraday_7946.csv.gz  in=459,751,648 out=113,089,395 elapsed=213.9s

  [19036/21087] intraday_7948.csv.gz  in=459,763,499 out=113,089,395 elapsed=213.9s

  [19037/21087] intraday_7949.csv.gz  in=459,776,523 out=113,089,395 elapsed=213.9s

  [19038/21087] intraday_7950.csv.gz  in=459,789,191 out=113,089,395 elapsed=213.9s

  [19039/21087] intraday_7951.csv.gz  in=459,802,939 out=113,089,395 elapsed=213.9s

  [19040/21087] intraday_7952.csv.gz  in=459,816,715 out=113,089,395 elapsed=213.9s

  [19041/21087] intraday_7953.csv.gz  in=459,831,521 out=113,089,395 elapsed=213.9s

  [19042/21087] intraday_7954.csv.gz  in=459,844,323 out=113,089,395 elapsed=213.9s

  [19043/21087] intraday_7955.csv.gz  in=459,856,471 out=113,089,395 elapsed=213.9s

  [19044/21087] intraday_7956.csv.gz  in=459,867,397 out=113,089,395 elapsed=213.9s

  [19045/21087] intraday_7957.csv.gz  in=459,881,704 out=113,089,395 elapsed=213.9s

  [19046/21087] intraday_7958.csv.gz  in=459,895,462 out=113,089,395 elapsed=213.9s

  [19047/21087] intraday_7959.csv.gz  in=459,908,349 out=113,089,395 elapsed=213.9s

  [19048/21087] intraday_7960.csv.gz  in=459,921,551 out=113,089,395 elapsed=214.0s

  [19049/21087] intraday_7961.csv.gz  in=459,933,555 out=113,089,395 elapsed=214.0s

  [19050/21087] intraday_7962.csv.gz  in=459,944,997 out=113,089,395 elapsed=214.0s

  [19051/21087] intraday_7963.csv.gz  in=459,956,518 out=113,089,395 elapsed=214.0s

  [19052/21087] intraday_7964.csv.gz  in=459,970,806 out=113,089,395 elapsed=214.0s

  [19053/21087] intraday_7965.csv.gz  in=459,984,461 out=113,089,395 elapsed=214.0s

  [19054/21087] intraday_7966.csv.gz  in=459,998,159 out=113,089,395 elapsed=214.0s

  [19055/21087] intraday_7967.csv.gz  in=460,013,424 out=113,089,395 elapsed=214.0s

  [19056/21087] intraday_7968.csv.gz  in=460,024,626 out=113,089,395 elapsed=214.0s

  [19057/21087] intraday_7969.csv.gz  in=460,037,288 out=113,089,395 elapsed=214.0s

  [19058/21087] intraday_7970.csv.gz  in=460,049,801 out=113,089,395 elapsed=214.0s

  [19059/21087] intraday_7971.csv.gz  in=460,062,065 out=113,089,395 elapsed=214.1s

  [19060/21087] intraday_7974.csv.gz  in=460,072,247 out=113,089,395 elapsed=214.1s

  [19061/21087] intraday_7972.csv.gz  in=460,086,250 out=113,089,395 elapsed=214.1s

  [19062/21087] intraday_7973.csv.gz  in=460,098,404 out=113,089,395 elapsed=214.1s

  [19063/21087] intraday_7975.csv.gz  in=460,112,310 out=113,089,395 elapsed=214.1s

  [19064/21087] intraday_7977.csv.gz  in=460,123,512 out=113,089,395 elapsed=214.1s

  [19065/21087] intraday_7976.csv.gz  in=460,135,411 out=113,089,395 elapsed=214.1s

  [19066/21087] intraday_7979.csv.gz  in=460,146,277 out=113,089,395 elapsed=214.1s

  [19067/21087] intraday_7978.csv.gz  in=460,162,141 out=113,089,395 elapsed=214.1s

  [19068/21087] intraday_7980.csv.gz  in=460,173,998 out=113,089,395 elapsed=214.1s

  [19069/21087] intraday_7981.csv.gz  in=460,187,144 out=113,089,395 elapsed=214.1s

  [19070/21087] intraday_7983.csv.gz  in=460,203,313 out=113,089,395 elapsed=214.1s

  [19071/21087] intraday_7982.csv.gz  in=460,219,741 out=113,089,395 elapsed=214.1s

  [19072/21087] intraday_7984.csv.gz  in=460,232,723 out=113,089,395 elapsed=214.2s

  [19073/21087] intraday_7985.csv.gz  in=460,245,681 out=113,089,395 elapsed=214.2s

  [19074/21087] intraday_7986.csv.gz  in=460,257,980 out=113,089,395 elapsed=214.2s

  [19075/21087] intraday_7987.csv.gz  in=460,270,818 out=113,089,395 elapsed=214.2s

  [19076/21087] intraday_7988.csv.gz  in=460,286,968 out=113,089,395 elapsed=214.2s

  [19077/21087] intraday_7989.csv.gz  in=460,299,243 out=113,089,395 elapsed=214.2s

  [19078/21087] intraday_7991.csv.gz  in=460,313,097 out=113,089,395 elapsed=214.2s

  [19079/21087] intraday_7990.csv.gz  in=460,325,598 out=113,089,395 elapsed=214.2s

  [19080/21087] intraday_7992.csv.gz  in=460,340,357 out=113,089,395 elapsed=214.2s

  [19081/21087] intraday_7993.csv.gz  in=460,355,630 out=113,089,395 elapsed=214.2s

  [19082/21087] intraday_7994.csv.gz  in=460,369,891 out=113,089,395 elapsed=214.2s

  [19083/21087] intraday_7995.csv.gz  in=460,381,687 out=113,089,395 elapsed=214.2s

  [19084/21087] intraday_7996.csv.gz  in=460,394,519 out=113,089,395 elapsed=214.3s

  [19085/21087] intraday_7997.csv.gz  in=460,407,727 out=113,089,395 elapsed=214.3s

  [19086/21087] intraday_7998.csv.gz  in=460,422,540 out=113,089,395 elapsed=214.3s

  [19087/21087] intraday_7999.csv.gz  in=460,434,869 out=113,089,395 elapsed=214.3s

  [19088/21087] intraday_8000.csv.gz  in=460,445,169 out=113,089,395 elapsed=214.3s

  [19089/21087] intraday_8001.csv.gz  in=460,461,223 out=113,089,395 elapsed=214.3s

  [19090/21087] intraday_8002.csv.gz  in=460,474,446 out=113,089,395 elapsed=214.3s

  [19091/21087] intraday_8003.csv.gz  in=460,489,417 out=113,089,395 elapsed=214.3s

  [19092/21087] intraday_8004.csv.gz  in=460,501,633 out=113,089,395 elapsed=214.3s

  [19093/21087] intraday_8005.csv.gz  in=460,520,452 out=113,089,395 elapsed=214.3s

  [19094/21087] intraday_8006.csv.gz  in=460,533,574 out=113,089,395 elapsed=214.3s

  [19095/21087] intraday_8007.csv.gz  in=460,546,684 out=113,089,395 elapsed=214.4s

  [19096/21087] intraday_8008.csv.gz  in=460,561,415 out=113,089,395 elapsed=214.4s

  [19097/21087] intraday_8009.csv.gz  in=460,575,823 out=113,089,395 elapsed=214.4s

  [19098/21087] intraday_8010.csv.gz  in=460,587,391 out=113,089,395 elapsed=214.4s

  [19099/21087] intraday_8012.csv.gz  in=460,601,818 out=113,089,395 elapsed=214.4s

  [19100/21087] intraday_8011.csv.gz  in=460,617,305 out=113,089,395 elapsed=214.4s

  [19101/21087] intraday_8013.csv.gz  in=460,632,253 out=113,089,395 elapsed=214.4s

  [19102/21087] intraday_8016.csv.gz  in=460,645,223 out=113,089,395 elapsed=214.4s

  [19103/21087] intraday_8015.csv.gz  in=460,660,437 out=113,089,395 elapsed=214.4s

  [19104/21087] intraday_8014.csv.gz  in=460,676,280 out=113,089,395 elapsed=214.4s

  [19105/21087] intraday_8017.csv.gz  in=460,694,937 out=113,089,395 elapsed=214.4s

  [19106/21087] intraday_8018.csv.gz  in=460,706,847 out=113,089,395 elapsed=214.5s

  [19107/21087] intraday_8020.csv.gz  in=460,719,801 out=113,089,395 elapsed=214.5s

  [19108/21087] intraday_8021.csv.gz  in=460,733,459 out=113,089,395 elapsed=214.5s

  [19109/21087] intraday_8019.csv.gz  in=460,747,074 out=113,089,395 elapsed=214.5s

  [19110/21087] intraday_8022.csv.gz  in=460,758,287 out=113,089,395 elapsed=214.5s

  [19111/21087] intraday_8023.csv.gz  in=460,773,352 out=113,089,395 elapsed=214.5s

  [19112/21087] intraday_8024.csv.gz  in=460,793,344 out=113,089,395 elapsed=214.5s

  [19113/21087] intraday_8025.csv.gz  in=460,809,733 out=113,089,395 elapsed=214.5s

  [19114/21087] intraday_8026.csv.gz  in=460,821,537 out=113,089,395 elapsed=214.5s

  [19115/21087] intraday_8027.csv.gz  in=460,835,307 out=113,089,395 elapsed=214.5s

  [19116/21087] intraday_8028.csv.gz  in=460,847,669 out=113,089,395 elapsed=214.5s

  [19117/21087] intraday_8030.csv.gz  in=460,859,476 out=113,089,395 elapsed=214.6s

  [19118/21087] intraday_8029.csv.gz  in=460,872,966 out=113,089,395 elapsed=214.6s

  [19119/21087] intraday_8031.csv.gz  in=460,887,211 out=113,089,395 elapsed=214.6s

  [19120/21087] intraday_8032.csv.gz  in=460,901,942 out=113,089,395 elapsed=214.6s

  [19121/21087] intraday_8033.csv.gz  in=460,916,016 out=113,089,395 elapsed=214.6s

  [19122/21087] intraday_8034.csv.gz  in=460,931,555 out=113,089,395 elapsed=214.6s

  [19123/21087] intraday_8036.csv.gz  in=460,941,840 out=113,089,395 elapsed=214.6s

  [19124/21087] intraday_8035.csv.gz  in=460,956,622 out=113,089,395 elapsed=214.6s

  [19125/21087] intraday_8037.csv.gz  in=460,970,310 out=113,089,395 elapsed=214.6s

  [19126/21087] intraday_8038.csv.gz  in=460,982,060 out=113,089,395 elapsed=214.6s

  [19127/21087] intraday_8039.csv.gz  in=460,997,469 out=113,089,395 elapsed=214.6s

  [19128/21087] intraday_8040.csv.gz  in=461,005,813 out=113,089,395 elapsed=214.7s

  [19129/21087] intraday_8041.csv.gz  in=461,018,062 out=113,089,395 elapsed=214.7s

  [19130/21087] intraday_8042.csv.gz  in=461,029,400 out=113,089,395 elapsed=214.7s

  [19131/21087] intraday_8043.csv.gz  in=461,039,397 out=113,089,395 elapsed=214.7s

  [19132/21087] intraday_8044.csv.gz  in=461,054,497 out=113,089,395 elapsed=214.7s

  [19133/21087] intraday_8045.csv.gz  in=461,068,799 out=113,089,395 elapsed=214.7s

  [19134/21087] intraday_8046.csv.gz  in=461,081,707 out=113,089,395 elapsed=214.7s

  [19135/21087] intraday_8047.csv.gz  in=461,092,964 out=113,089,395 elapsed=214.7s

  [19136/21087] intraday_8048.csv.gz  in=461,104,159 out=113,089,395 elapsed=214.7s

  [19137/21087] intraday_8049.csv.gz  in=461,118,903 out=113,089,395 elapsed=214.7s

  [19138/21087] intraday_8050.csv.gz  in=461,132,971 out=113,089,395 elapsed=214.7s

  [19139/21087] intraday_8051.csv.gz  in=461,145,447 out=113,089,395 elapsed=214.7s

  [19140/21087] intraday_8052.csv.gz  in=461,158,876 out=113,089,395 elapsed=214.8s

  [19141/21087] intraday_8053.csv.gz  in=461,174,389 out=113,089,395 elapsed=214.8s

  [19142/21087] intraday_8056.csv.gz  in=461,187,621 out=113,089,395 elapsed=214.8s

  [19143/21087] intraday_8055.csv.gz  in=461,200,808 out=113,089,395 elapsed=214.8s

  [19144/21087] intraday_8054.csv.gz  in=461,215,126 out=113,089,395 elapsed=214.8s

  [19145/21087] intraday_8057.csv.gz  in=461,228,404 out=113,089,395 elapsed=214.8s

  [19146/21087] intraday_8058.csv.gz  in=461,237,860 out=113,089,395 elapsed=214.8s

  [19147/21087] intraday_8059.csv.gz  in=461,247,896 out=113,089,395 elapsed=214.8s

  [19148/21087] intraday_8060.csv.gz  in=461,261,246 out=113,089,395 elapsed=214.8s

  [19149/21087] intraday_8061.csv.gz  in=461,273,641 out=113,089,395 elapsed=214.8s

  [19150/21087] intraday_8062.csv.gz  in=461,284,369 out=113,089,395 elapsed=214.8s

  [19151/21087] intraday_8063.csv.gz  in=461,296,529 out=113,089,395 elapsed=214.9s

  [19152/21087] intraday_8064.csv.gz  in=461,308,552 out=113,089,395 elapsed=214.9s

  [19153/21087] intraday_8065.csv.gz  in=461,321,105 out=113,089,395 elapsed=214.9s

  [19154/21087] intraday_8066.csv.gz  in=461,333,692 out=113,089,395 elapsed=214.9s

  [19155/21087] intraday_8067.csv.gz  in=461,346,919 out=113,089,395 elapsed=214.9s

  [19156/21087] intraday_8068.csv.gz  in=461,360,104 out=113,089,395 elapsed=214.9s

  [19157/21087] intraday_8069.csv.gz  in=461,373,705 out=113,089,395 elapsed=214.9s

  [19158/21087] intraday_8070.csv.gz  in=461,395,245 out=113,089,395 elapsed=214.9s

  [19159/21087] intraday_8071.csv.gz  in=461,406,815 out=113,089,395 elapsed=214.9s

  [19160/21087] intraday_8072.csv.gz  in=461,417,327 out=113,089,395 elapsed=214.9s

  [19161/21087] intraday_8073.csv.gz  in=461,431,657 out=113,089,395 elapsed=215.0s

  [19162/21087] intraday_8074.csv.gz  in=461,447,847 out=113,089,395 elapsed=215.0s

  [19163/21087] intraday_8076.csv.gz  in=461,458,433 out=113,089,395 elapsed=215.0s

  [19164/21087] intraday_8075.csv.gz  in=461,471,146 out=113,089,395 elapsed=215.0s

  [19165/21087] intraday_8077.csv.gz  in=461,484,157 out=113,089,395 elapsed=215.0s

  [19166/21087] intraday_8078.csv.gz  in=461,503,785 out=113,089,395 elapsed=215.0s

  [19167/21087] intraday_8079.csv.gz  in=461,516,267 out=113,089,395 elapsed=215.0s

  [19168/21087] intraday_8080.csv.gz  in=461,528,899 out=113,089,395 elapsed=215.0s

  [19169/21087] intraday_8081.csv.gz  in=461,541,262 out=113,089,395 elapsed=215.0s

  [19170/21087] intraday_8083.csv.gz  in=461,552,535 out=113,089,395 elapsed=215.0s

  [19171/21087] intraday_8082.csv.gz  in=461,565,313 out=113,089,395 elapsed=215.0s

  [19172/21087] intraday_8084.csv.gz  in=461,576,546 out=113,089,395 elapsed=215.0s

  [19173/21087] intraday_8085.csv.gz  in=461,588,617 out=113,089,395 elapsed=215.0s

  [19174/21087] intraday_8087.csv.gz  in=461,600,025 out=113,089,395 elapsed=215.1s

  [19175/21087] intraday_8086.csv.gz  in=461,612,643 out=113,089,395 elapsed=215.1s

  [19176/21087] intraday_8089.csv.gz  in=461,623,889 out=113,089,395 elapsed=215.1s

  [19177/21087] intraday_8088.csv.gz  in=461,637,533 out=113,089,395 elapsed=215.1s

  [19178/21087] intraday_8090.csv.gz  in=461,649,234 out=113,089,395 elapsed=215.1s

  [19179/21087] intraday_8091.csv.gz  in=461,662,606 out=113,089,395 elapsed=215.1s

  [19180/21087] intraday_8092.csv.gz  in=461,674,978 out=113,089,395 elapsed=215.1s

  [19181/21087] intraday_8093.csv.gz  in=461,687,215 out=113,089,395 elapsed=215.1s

  [19182/21087] intraday_8094.csv.gz  in=461,699,024 out=113,089,395 elapsed=215.1s

  [19183/21087] intraday_8095.csv.gz  in=461,709,794 out=113,089,395 elapsed=215.1s

  [19184/21087] intraday_8096.csv.gz  in=461,725,531 out=113,089,395 elapsed=215.1s

  [19185/21087] intraday_8097.csv.gz  in=461,737,004 out=113,089,395 elapsed=215.2s

  [19186/21087] intraday_8098.csv.gz  in=461,751,945 out=113,089,395 elapsed=215.2s

  [19187/21087] intraday_8100.csv.gz  in=461,766,466 out=113,089,395 elapsed=215.2s

  [19188/21087] intraday_8099.csv.gz  in=461,778,616 out=113,089,395 elapsed=215.2s

  [19189/21087] intraday_8102.csv.gz  in=461,791,102 out=113,089,395 elapsed=215.2s

  [19190/21087] intraday_8101.csv.gz  in=461,801,666 out=113,089,395 elapsed=215.2s

  [19191/21087] intraday_8103.csv.gz  in=461,813,937 out=113,089,395 elapsed=215.2s

  [19192/21087] intraday_8104.csv.gz  in=461,825,727 out=113,089,395 elapsed=215.2s

  [19193/21087] intraday_8106.csv.gz  in=461,837,557 out=113,089,395 elapsed=215.2s

  [19194/21087] intraday_8105.csv.gz  in=461,849,664 out=113,089,395 elapsed=215.2s

  [19195/21087] intraday_8107.csv.gz  in=461,866,117 out=113,089,395 elapsed=215.2s

  [19196/21087] intraday_8109.csv.gz  in=461,879,543 out=113,089,395 elapsed=215.3s

  [19197/21087] intraday_8110.csv.gz  in=461,893,199 out=113,089,395 elapsed=215.3s

  [19198/21087] intraday_8108.csv.gz  in=461,904,020 out=113,089,395 elapsed=215.3s

  [19199/21087] intraday_8111.csv.gz  in=461,917,493 out=113,089,395 elapsed=215.3s

  [19200/21087] intraday_8113.csv.gz  in=461,929,349 out=113,089,395 elapsed=215.3s

  [19201/21087] intraday_8112.csv.gz  in=461,942,047 out=113,089,395 elapsed=215.3s

  [19202/21087] intraday_8114.csv.gz  in=461,955,050 out=113,089,395 elapsed=215.3s

  [19203/21087] intraday_8115.csv.gz  in=461,968,025 out=113,089,395 elapsed=215.3s

  [19204/21087] intraday_8116.csv.gz  in=461,980,367 out=113,089,395 elapsed=215.3s

  [19205/21087] intraday_8117.csv.gz  in=461,993,513 out=113,089,395 elapsed=215.3s

  [19206/21087] intraday_8118.csv.gz  in=462,004,907 out=113,089,395 elapsed=215.3s

  [19207/21087] intraday_8119.csv.gz  in=462,019,055 out=113,089,395 elapsed=215.3s

  [19208/21087] intraday_8120.csv.gz  in=462,029,370 out=113,089,395 elapsed=215.3s

  [19209/21087] intraday_8121.csv.gz  in=462,042,301 out=113,089,395 elapsed=215.4s

  [19210/21087] intraday_8122.csv.gz  in=462,053,647 out=113,089,395 elapsed=215.4s

  [19211/21087] intraday_8123.csv.gz  in=462,065,313 out=113,089,395 elapsed=215.4s

  [19212/21087] intraday_8124.csv.gz  in=462,075,613 out=113,089,395 elapsed=215.4s

  [19213/21087] intraday_8125.csv.gz  in=462,086,210 out=113,089,395 elapsed=215.4s

  [19214/21087] intraday_8126.csv.gz  in=462,098,113 out=113,089,395 elapsed=215.4s

  [19215/21087] intraday_8127.csv.gz  in=462,112,341 out=113,089,395 elapsed=215.4s

  [19216/21087] intraday_8128.csv.gz  in=462,130,133 out=113,089,395 elapsed=215.4s

  [19217/21087] intraday_8129.csv.gz  in=462,143,710 out=113,089,395 elapsed=215.4s

  [19218/21087] intraday_8130.csv.gz  in=462,155,572 out=113,089,395 elapsed=215.4s

  [19219/21087] intraday_8131.csv.gz  in=462,166,943 out=113,089,395 elapsed=215.4s

  [19220/21087] intraday_8133.csv.gz  in=462,180,478 out=113,089,395 elapsed=215.4s

  [19221/21087] intraday_8132.csv.gz  in=462,193,744 out=113,089,395 elapsed=215.4s

  [19222/21087] intraday_8134.csv.gz  in=462,210,266 out=113,089,395 elapsed=215.5s

  [19223/21087] intraday_8135.csv.gz  in=462,222,734 out=113,089,395 elapsed=215.5s

  [19224/21087] intraday_8136.csv.gz  in=462,235,174 out=113,089,395 elapsed=215.5s

  [19225/21087] intraday_8137.csv.gz  in=462,247,457 out=113,089,395 elapsed=215.5s

  [19226/21087] intraday_8139.csv.gz  in=462,262,402 out=113,089,395 elapsed=215.5s

  [19227/21087] intraday_8138.csv.gz  in=462,276,533 out=113,089,395 elapsed=215.5s

  [19228/21087] intraday_8140.csv.gz  in=462,287,622 out=113,089,395 elapsed=215.5s

  [19229/21087] intraday_8141.csv.gz  in=462,303,515 out=113,089,395 elapsed=215.5s

  [19230/21087] intraday_8142.csv.gz  in=462,315,195 out=113,089,395 elapsed=215.5s

  [19231/21087] intraday_8144.csv.gz  in=462,327,743 out=113,089,395 elapsed=215.6s

  [19232/21087] intraday_8146.csv.gz  in=462,340,771 out=113,089,395 elapsed=215.6s

  [19233/21087] intraday_8145.csv.gz  in=462,352,634 out=113,089,395 elapsed=215.6s

  [19234/21087] intraday_8143.csv.gz  in=462,366,912 out=113,089,395 elapsed=215.6s

  [19235/21087] intraday_8147.csv.gz  in=462,380,915 out=113,089,395 elapsed=215.6s

  [19236/21087] intraday_8148.csv.gz  in=462,392,988 out=113,089,395 elapsed=215.6s

  [19237/21087] intraday_8149.csv.gz  in=462,405,556 out=113,089,395 elapsed=215.6s

  [19238/21087] intraday_8150.csv.gz  in=462,419,879 out=113,089,395 elapsed=215.6s

  [19239/21087] intraday_8151.csv.gz  in=462,434,511 out=113,089,395 elapsed=215.6s

  [19240/21087] intraday_8155.csv.gz  in=462,446,147 out=113,089,395 elapsed=215.6s

  [19241/21087] intraday_8153.csv.gz  in=462,459,979 out=113,089,395 elapsed=215.6s

  [19242/21087] intraday_8152.csv.gz  in=462,473,863 out=113,089,395 elapsed=215.6s

  [19243/21087] intraday_8154.csv.gz  in=462,490,215 out=113,089,395 elapsed=215.6s

  [19244/21087] intraday_8157.csv.gz  in=462,504,268 out=113,089,395 elapsed=215.7s

  [19245/21087] intraday_8156.csv.gz  in=462,517,645 out=113,089,395 elapsed=215.7s

  [19246/21087] intraday_8158.csv.gz  in=462,529,656 out=113,089,395 elapsed=215.7s

  [19247/21087] intraday_8159.csv.gz  in=462,543,334 out=113,089,395 elapsed=215.7s

  [19248/21087] intraday_8160.csv.gz  in=462,558,869 out=113,089,395 elapsed=215.7s

  [19249/21087] intraday_8163.csv.gz  in=462,571,795 out=113,089,395 elapsed=215.7s

  [19250/21087] intraday_8162.csv.gz  in=462,586,932 out=113,089,395 elapsed=215.7s

  [19251/21087] intraday_8161.csv.gz  in=462,603,588 out=113,089,395 elapsed=215.7s

  [19252/21087] intraday_8164.csv.gz  in=462,616,440 out=113,089,395 elapsed=215.7s

  [19253/21087] intraday_8166.csv.gz  in=462,627,604 out=113,089,395 elapsed=215.8s

  [19254/21087] intraday_8165.csv.gz  in=462,643,077 out=113,089,395 elapsed=215.8s

  [19255/21087] intraday_8167.csv.gz  in=462,657,640 out=113,089,395 elapsed=215.8s

  [19256/21087] intraday_8168.csv.gz  in=462,668,451 out=113,089,395 elapsed=215.8s

  [19257/21087] intraday_8169.csv.gz  in=462,682,728 out=113,089,395 elapsed=215.8s

  [19258/21087] intraday_8170.csv.gz  in=462,696,497 out=113,089,395 elapsed=215.8s

  [19259/21087] intraday_8171.csv.gz  in=462,711,815 out=113,089,395 elapsed=215.8s

  [19260/21087] intraday_8172.csv.gz  in=462,727,977 out=113,089,395 elapsed=215.8s

  [19261/21087] intraday_8173.csv.gz  in=462,740,298 out=113,089,395 elapsed=215.8s

  [19262/21087] intraday_8174.csv.gz  in=462,754,240 out=113,089,395 elapsed=215.8s

  [19263/21087] intraday_8175.csv.gz  in=462,765,884 out=113,089,395 elapsed=215.8s

  [19264/21087] intraday_8176.csv.gz  in=462,778,913 out=113,089,395 elapsed=215.8s

  [19265/21087] intraday_8177.csv.gz  in=462,792,822 out=113,089,395 elapsed=215.9s

  [19266/21087] intraday_8178.csv.gz  in=462,807,692 out=113,089,395 elapsed=215.9s

  [19267/21087] intraday_8179.csv.gz  in=462,821,403 out=113,089,395 elapsed=215.9s

  [19268/21087] intraday_8180.csv.gz  in=462,834,926 out=113,089,395 elapsed=215.9s

  [19269/21087] intraday_8181.csv.gz  in=462,847,515 out=113,089,395 elapsed=215.9s

  [19270/21087] intraday_8182.csv.gz  in=462,859,739 out=113,089,395 elapsed=215.9s

  [19271/21087] intraday_8183.csv.gz  in=462,872,832 out=113,089,395 elapsed=215.9s

  [19272/21087] intraday_8184.csv.gz  in=462,884,335 out=113,089,395 elapsed=215.9s

  [19273/21087] intraday_8186.csv.gz  in=462,891,779 out=113,089,395 elapsed=215.9s

  [19274/21087] intraday_8185.csv.gz  in=462,903,148 out=113,089,395 elapsed=215.9s

  [19275/21087] intraday_8188.csv.gz  in=462,909,828 out=113,089,395 elapsed=215.9s

  [19276/21087] intraday_8187.csv.gz  in=462,922,111 out=113,089,395 elapsed=215.9s

  [19277/21087] intraday_8189.csv.gz  in=462,922,150 out=113,089,395 elapsed=215.9s

  [19278/21087] intraday_8190.csv.gz  in=462,926,247 out=113,089,395 elapsed=215.9s

  [19279/21087] intraday_8191.csv.gz  in=462,928,735 out=113,089,395 elapsed=216.0s

  [19280/21087] intraday_8193.csv.gz  in=462,929,672 out=113,089,395 elapsed=216.0s

  [19281/21087] intraday_8192.csv.gz  in=462,930,687 out=113,089,395 elapsed=216.0s

  [19282/21087] intraday_8194.csv.gz  in=462,931,317 out=113,089,395 elapsed=216.0s

  [19283/21087] intraday_8195.csv.gz  in=462,931,402 out=113,089,395 elapsed=216.0s

  [19284/21087] intraday_8196.csv.gz  in=462,931,468 out=113,089,395 elapsed=216.0s

  [19285/21087] intraday_8198.csv.gz  in=462,931,822 out=113,089,395 elapsed=216.0s

  [19286/21087] intraday_8197.csv.gz  in=462,934,630 out=113,089,395 elapsed=216.0s

  [19287/21087] intraday_8199.csv.gz  in=462,939,242 out=113,089,395 elapsed=216.0s

  [19288/21087] intraday_8200.csv.gz  in=462,939,402 out=113,089,395 elapsed=216.0s

  [19289/21087] intraday_8202.csv.gz  in=462,940,725 out=113,089,395 elapsed=216.0s

  [19290/21087] intraday_8203.csv.gz  in=462,940,975 out=113,089,395 elapsed=216.0s

  [19291/21087] intraday_8201.csv.gz  in=462,945,743 out=113,089,395 elapsed=216.0s

  [19292/21087] intraday_8204.csv.gz  in=462,945,783 out=113,089,395 elapsed=216.0s

  [19293/21087] intraday_8206.csv.gz  in=462,945,784 out=113,089,395 elapsed=216.0s

  [19294/21087] intraday_8205.csv.gz  in=462,956,507 out=113,089,395 elapsed=216.0s

  [19295/21087] intraday_8208.csv.gz  in=462,964,959 out=113,089,395 elapsed=216.1s

  [19296/21087] intraday_8207.csv.gz  in=462,969,742 out=113,089,395 elapsed=216.1s

  [19297/21087] intraday_8209.csv.gz  in=462,970,325 out=113,089,395 elapsed=216.1s

  [19298/21087] intraday_8210.csv.gz  in=462,970,443 out=113,089,395 elapsed=216.1s

  [19299/21087] intraday_8211.csv.gz  in=462,971,421 out=113,089,395 elapsed=216.1s

  [19300/21087] intraday_8213.csv.gz  in=462,971,644 out=113,089,395 elapsed=216.1s

  [19301/21087] intraday_8214.csv.gz  in=462,973,259 out=113,089,395 elapsed=216.1s

  [19302/21087] intraday_8216.csv.gz  in=462,974,079 out=113,089,395 elapsed=216.1s

  [19303/21087] intraday_8215.csv.gz  in=462,974,645 out=113,089,395 elapsed=216.1s

  [19304/21087] intraday_8212.csv.gz  in=462,988,541 out=113,089,395 elapsed=216.1s

  [19305/21087] intraday_8217.csv.gz  in=462,989,110 out=113,089,395 elapsed=216.1s

  [19306/21087] intraday_8220.csv.gz  in=462,990,368 out=113,089,395 elapsed=216.1s

  [19307/21087] intraday_8218.csv.gz  in=462,991,453 out=113,089,395 elapsed=216.1s

  [19308/21087] intraday_8219.csv.gz  in=462,992,231 out=113,089,395 elapsed=216.1s

  [19309/21087] intraday_8221.csv.gz  in=462,992,909 out=113,089,395 elapsed=216.1s

  [19310/21087] intraday_8222.csv.gz  in=462,993,590 out=113,089,395 elapsed=216.1s

  [19311/21087] intraday_8224.csv.gz  in=462,994,951 out=113,089,395 elapsed=216.1s

  [19312/21087] intraday_8223.csv.gz  in=462,995,940 out=113,089,395 elapsed=216.1s

  [19313/21087] intraday_8225.csv.gz  in=462,996,780 out=113,089,395 elapsed=216.1s

  [19314/21087] intraday_8226.csv.gz  in=462,997,618 out=113,089,395 elapsed=216.1s

  [19315/21087] intraday_8227.csv.gz  in=462,998,682 out=113,089,395 elapsed=216.1s

  [19316/21087] intraday_8228.csv.gz  in=462,998,943 out=113,089,395 elapsed=216.1s

  [19317/21087] intraday_8229.csv.gz  in=462,999,283 out=113,089,395 elapsed=216.1s

  [19318/21087] intraday_8230.csv.gz  in=463,000,085 out=113,089,395 elapsed=216.2s

  [19319/21087] intraday_8231.csv.gz  in=463,000,898 out=113,089,395 elapsed=216.2s

  [19320/21087] intraday_8232.csv.gz  in=463,001,460 out=113,089,395 elapsed=216.2s

  [19321/21087] intraday_8233.csv.gz  in=463,001,845 out=113,089,395 elapsed=216.2s

  [19322/21087] intraday_8234.csv.gz  in=463,002,517 out=113,089,395 elapsed=216.2s

  [19323/21087] intraday_8235.csv.gz  in=463,003,160 out=113,089,395 elapsed=216.2s

  [19324/21087] intraday_8236.csv.gz  in=463,003,549 out=113,089,395 elapsed=216.2s

  [19325/21087] intraday_8237.csv.gz  in=463,004,447 out=113,089,395 elapsed=216.2s

  [19326/21087] intraday_8238.csv.gz  in=463,004,888 out=113,089,395 elapsed=216.2s

  [19327/21087] intraday_8239.csv.gz  in=463,005,856 out=113,089,395 elapsed=216.2s

  [19328/21087] intraday_8240.csv.gz  in=463,006,431 out=113,089,395 elapsed=216.2s

  [19329/21087] intraday_8241.csv.gz  in=463,006,626 out=113,089,395 elapsed=216.2s

  [19330/21087] intraday_8242.csv.gz  in=463,007,609 out=113,089,395 elapsed=216.2s

  [19331/21087] intraday_8243.csv.gz  in=463,008,699 out=113,089,395 elapsed=216.2s

  [19332/21087] intraday_8244.csv.gz  in=463,010,165 out=113,089,395 elapsed=216.2s

  [19333/21087] intraday_8245.csv.gz  in=463,011,128 out=113,089,395 elapsed=216.2s

  [19334/21087] intraday_8246.csv.gz  in=463,011,678 out=113,089,395 elapsed=216.2s

  [19335/21087] intraday_8247.csv.gz  in=463,012,255 out=113,089,395 elapsed=216.2s

  [19336/21087] intraday_8248.csv.gz  in=463,012,699 out=113,089,395 elapsed=216.2s

  [19337/21087] intraday_8249.csv.gz  in=463,013,432 out=113,089,395 elapsed=216.2s

  [19338/21087] intraday_8251.csv.gz  in=463,014,093 out=113,089,395 elapsed=216.2s

  [19339/21087] intraday_8250.csv.gz  in=463,014,497 out=113,089,395 elapsed=216.2s

  [19340/21087] intraday_8252.csv.gz  in=463,015,048 out=113,089,395 elapsed=216.2s

  [19341/21087] intraday_8253.csv.gz  in=463,015,379 out=113,089,395 elapsed=216.2s

  [19342/21087] intraday_8254.csv.gz  in=463,015,716 out=113,089,395 elapsed=216.2s

  [19343/21087] intraday_8255.csv.gz  in=463,016,206 out=113,089,395 elapsed=216.2s

  [19344/21087] intraday_8258.csv.gz  in=463,016,771 out=113,089,395 elapsed=216.3s

  [19345/21087] intraday_8257.csv.gz  in=463,017,267 out=113,089,395 elapsed=216.3s

  [19346/21087] intraday_8256.csv.gz  in=463,017,645 out=113,089,395 elapsed=216.3s

  [19347/21087] intraday_8259.csv.gz  in=463,018,255 out=113,089,395 elapsed=216.3s

  [19348/21087] intraday_8260.csv.gz  in=463,018,473 out=113,089,395 elapsed=216.3s

  [19349/21087] intraday_8261.csv.gz  in=463,018,992 out=113,089,395 elapsed=216.3s

  [19350/21087] intraday_8262.csv.gz  in=463,019,621 out=113,089,395 elapsed=216.3s

  [19351/21087] intraday_8264.csv.gz  in=463,019,948 out=113,089,395 elapsed=216.3s

  [19352/21087] intraday_8263.csv.gz  in=463,020,229 out=113,089,395 elapsed=216.3s

  [19353/21087] intraday_8265.csv.gz  in=463,020,752 out=113,089,395 elapsed=216.3s

  [19354/21087] intraday_8266.csv.gz  in=463,021,874 out=113,089,395 elapsed=216.3s

  [19355/21087] intraday_8269.csv.gz  in=463,022,447 out=113,089,395 elapsed=216.3s

  [19356/21087] intraday_8268.csv.gz  in=463,023,359 out=113,089,395 elapsed=216.3s

  [19357/21087] intraday_8267.csv.gz  in=463,024,525 out=113,089,395 elapsed=216.3s

  [19358/21087] intraday_8270.csv.gz  in=463,024,740 out=113,089,395 elapsed=216.3s

  [19359/21087] intraday_8271.csv.gz  in=463,024,945 out=113,089,395 elapsed=216.3s

  [19360/21087] intraday_8273.csv.gz  in=463,025,800 out=113,089,395 elapsed=216.3s

  [19361/21087] intraday_8272.csv.gz  in=463,026,771 out=113,089,395 elapsed=216.3s

  [19362/21087] intraday_8274.csv.gz  in=463,027,038 out=113,089,395 elapsed=216.3s

  [19363/21087] intraday_8275.csv.gz  in=463,028,005 out=113,089,395 elapsed=216.3s

  [19364/21087] intraday_8277.csv.gz  in=463,028,202 out=113,089,395 elapsed=216.3s

  [19365/21087] intraday_8276.csv.gz  in=463,028,330 out=113,089,395 elapsed=216.3s

  [19366/21087] intraday_8278.csv.gz  in=463,028,834 out=113,089,395 elapsed=216.3s

  [19367/21087] intraday_8279.csv.gz  in=463,030,310 out=113,089,395 elapsed=216.3s

  [19368/21087] intraday_8281.csv.gz  in=463,030,657 out=113,089,395 elapsed=216.3s

  [19369/21087] intraday_8280.csv.gz  in=463,031,784 out=113,089,395 elapsed=216.3s

  [19370/21087] intraday_8283.csv.gz  in=463,032,310 out=113,089,395 elapsed=216.3s

  [19371/21087] intraday_8282.csv.gz  in=463,032,965 out=113,089,395 elapsed=216.3s

  [19372/21087] intraday_8284.csv.gz  in=463,033,409 out=113,089,395 elapsed=216.4s

  [19373/21087] intraday_8286.csv.gz  in=463,033,782 out=113,089,395 elapsed=216.4s

  [19374/21087] intraday_8285.csv.gz  in=463,034,833 out=113,089,395 elapsed=216.4s

  [19375/21087] intraday_8287.csv.gz  in=463,035,442 out=113,089,395 elapsed=216.4s

  [19376/21087] intraday_8288.csv.gz  in=463,035,831 out=113,089,395 elapsed=216.4s

  [19377/21087] intraday_8290.csv.gz  in=463,036,346 out=113,089,395 elapsed=216.4s

  [19378/21087] intraday_8289.csv.gz  in=463,037,381 out=113,089,395 elapsed=216.4s

  [19379/21087] intraday_8291.csv.gz  in=463,038,134 out=113,089,395 elapsed=216.4s

  [19380/21087] intraday_8292.csv.gz  in=463,038,789 out=113,089,395 elapsed=216.4s

  [19381/21087] intraday_8294.csv.gz  in=463,038,887 out=113,089,395 elapsed=216.4s

  [19382/21087] intraday_8293.csv.gz  in=463,039,588 out=113,089,395 elapsed=216.4s

  [19383/21087] intraday_8296.csv.gz  in=463,040,233 out=113,089,395 elapsed=216.4s

  [19384/21087] intraday_8295.csv.gz  in=463,040,596 out=113,089,395 elapsed=216.4s

  [19385/21087] intraday_8297.csv.gz  in=463,042,926 out=113,089,395 elapsed=216.4s

  [19386/21087] intraday_8299.csv.gz  in=463,044,066 out=113,089,395 elapsed=216.4s

  [19387/21087] intraday_8298.csv.gz  in=463,045,532 out=113,089,395 elapsed=216.4s

  [19388/21087] intraday_8300.csv.gz  in=463,046,498 out=113,089,395 elapsed=216.4s

  [19389/21087] intraday_8301.csv.gz  in=463,046,973 out=113,089,395 elapsed=216.4s

  [19390/21087] intraday_8302.csv.gz  in=463,047,889 out=113,089,395 elapsed=216.4s

  [19391/21087] intraday_8303.csv.gz  in=463,048,999 out=113,089,395 elapsed=216.4s

  [19392/21087] intraday_8304.csv.gz  in=463,050,331 out=113,089,395 elapsed=216.4s

  [19393/21087] intraday_8305.csv.gz  in=463,050,604 out=113,089,395 elapsed=216.4s

  [19394/21087] intraday_8306.csv.gz  in=463,051,428 out=113,089,395 elapsed=216.4s

  [19395/21087] intraday_8308.csv.gz  in=463,052,009 out=113,089,395 elapsed=216.4s

  [19396/21087] intraday_8309.csv.gz  in=463,052,772 out=113,089,395 elapsed=216.4s

  [19397/21087] intraday_8307.csv.gz  in=463,053,983 out=113,089,395 elapsed=216.4s

  [19398/21087] intraday_8310.csv.gz  in=463,054,469 out=113,089,395 elapsed=216.4s

  [19399/21087] intraday_8311.csv.gz  in=463,054,807 out=113,089,395 elapsed=216.4s

  [19400/21087] intraday_8313.csv.gz  in=463,055,789 out=113,089,395 elapsed=216.4s

  [19401/21087] intraday_8312.csv.gz  in=463,060,054 out=113,089,395 elapsed=216.5s

  [19402/21087] intraday_8315.csv.gz  in=463,060,785 out=113,089,395 elapsed=216.5s

  [19403/21087] intraday_8314.csv.gz  in=463,060,970 out=113,089,395 elapsed=216.5s

  [19404/21087] intraday_8316.csv.gz  in=463,062,536 out=113,089,395 elapsed=216.5s

  [19405/21087] intraday_8318.csv.gz  in=463,063,382 out=113,089,395 elapsed=216.5s

  [19406/21087] intraday_8319.csv.gz  in=463,063,722 out=113,089,395 elapsed=216.5s

  [19407/21087] intraday_8317.csv.gz  in=463,065,453 out=113,089,395 elapsed=216.5s

  [19408/21087] intraday_8320.csv.gz  in=463,067,291 out=113,089,395 elapsed=216.5s

  [19409/21087] intraday_8321.csv.gz  in=463,067,788 out=113,089,395 elapsed=216.5s

  [19410/21087] intraday_8323.csv.gz  in=463,068,784 out=113,089,395 elapsed=216.5s

  [19411/21087] intraday_8322.csv.gz  in=463,069,299 out=113,089,395 elapsed=216.5s

  [19412/21087] intraday_8324.csv.gz  in=463,069,903 out=113,089,395 elapsed=216.5s

  [19413/21087] intraday_8325.csv.gz  in=463,070,689 out=113,089,395 elapsed=216.5s

  [19414/21087] intraday_8327.csv.gz  in=463,071,438 out=113,089,395 elapsed=216.5s

  [19415/21087] intraday_8326.csv.gz  in=463,072,235 out=113,089,395 elapsed=216.5s

  [19416/21087] intraday_8328.csv.gz  in=463,073,337 out=113,089,395 elapsed=216.5s

  [19417/21087] intraday_8331.csv.gz  in=463,074,040 out=113,089,395 elapsed=216.5s

  [19418/21087] intraday_8329.csv.gz  in=463,076,225 out=113,089,395 elapsed=216.5s

  [19419/21087] intraday_8330.csv.gz  in=463,077,685 out=113,089,395 elapsed=216.5s

  [19420/21087] intraday_8332.csv.gz  in=463,079,067 out=113,089,395 elapsed=216.5s

  [19421/21087] intraday_8333.csv.gz  in=463,079,939 out=113,089,395 elapsed=216.5s

  [19422/21087] intraday_8335.csv.gz  in=463,080,166 out=113,089,395 elapsed=216.5s

  [19423/21087] intraday_8334.csv.gz  in=463,080,618 out=113,089,395 elapsed=216.5s

  [19424/21087] intraday_8336.csv.gz  in=463,081,141 out=113,089,395 elapsed=216.5s

  [19425/21087] intraday_8337.csv.gz  in=463,081,581 out=113,089,395 elapsed=216.5s

  [19426/21087] intraday_8338.csv.gz  in=463,082,200 out=113,089,395 elapsed=216.5s

  [19427/21087] intraday_8340.csv.gz  in=463,083,181 out=113,089,395 elapsed=216.5s

  [19428/21087] intraday_8339.csv.gz  in=463,083,941 out=113,089,395 elapsed=216.5s

  [19429/21087] intraday_8341.csv.gz  in=463,085,052 out=113,089,395 elapsed=216.6s

  [19430/21087] intraday_8342.csv.gz  in=463,085,692 out=113,089,395 elapsed=216.6s

  [19431/21087] intraday_8343.csv.gz  in=463,086,694 out=113,089,395 elapsed=216.6s

  [19432/21087] intraday_8344.csv.gz  in=463,087,613 out=113,089,395 elapsed=216.6s

  [19433/21087] intraday_8345.csv.gz  in=463,088,478 out=113,089,395 elapsed=216.6s

  [19434/21087] intraday_8346.csv.gz  in=463,088,938 out=113,089,395 elapsed=216.6s

  [19435/21087] intraday_8348.csv.gz  in=463,089,356 out=113,089,395 elapsed=216.6s

  [19436/21087] intraday_8347.csv.gz  in=463,089,856 out=113,089,395 elapsed=216.6s

  [19437/21087] intraday_8349.csv.gz  in=463,091,100 out=113,089,395 elapsed=216.6s

  [19438/21087] intraday_8350.csv.gz  in=463,091,734 out=113,089,395 elapsed=216.6s

  [19439/21087] intraday_8352.csv.gz  in=463,092,535 out=113,089,395 elapsed=216.6s

  [19440/21087] intraday_8351.csv.gz  in=463,092,899 out=113,089,395 elapsed=216.6s

  [19441/21087] intraday_8353.csv.gz  in=463,093,252 out=113,089,395 elapsed=216.6s

  [19442/21087] intraday_8354.csv.gz  in=463,094,497 out=113,089,395 elapsed=216.6s

  [19443/21087] intraday_8355.csv.gz  in=463,094,895 out=113,089,395 elapsed=216.6s

  [19444/21087] intraday_8356.csv.gz  in=463,095,277 out=113,089,395 elapsed=216.6s

  [19445/21087] intraday_8357.csv.gz  in=463,096,279 out=113,089,395 elapsed=216.6s

  [19446/21087] intraday_8358.csv.gz  in=463,096,288 out=113,089,395 elapsed=216.6s

  [19447/21087] intraday_8359.csv.gz  in=463,111,787 out=113,089,395 elapsed=216.6s

  [19448/21087] intraday_8361.csv.gz  in=463,125,677 out=113,089,395 elapsed=216.6s

  [19449/21087] intraday_8360.csv.gz  in=463,138,165 out=113,089,395 elapsed=216.6s

  [19450/21087] intraday_8362.csv.gz  in=463,150,628 out=113,089,395 elapsed=216.6s

  [19451/21087] intraday_8363.csv.gz  in=463,163,755 out=113,089,395 elapsed=216.7s

  [19452/21087] intraday_8364.csv.gz  in=463,178,310 out=113,089,395 elapsed=216.7s

  [19453/21087] intraday_8365.csv.gz  in=463,193,704 out=113,089,395 elapsed=216.7s

  [19454/21087] intraday_8366.csv.gz  in=463,206,133 out=113,089,395 elapsed=216.7s

  [19455/21087] intraday_8367.csv.gz  in=463,219,354 out=113,089,395 elapsed=216.7s

  [19456/21087] intraday_8368.csv.gz  in=463,234,946 out=113,089,395 elapsed=216.7s

  [19457/21087] intraday_8370.csv.gz  in=463,248,576 out=113,089,395 elapsed=216.7s

  [19458/21087] intraday_8369.csv.gz  in=463,263,561 out=113,089,395 elapsed=216.7s

  [19459/21087] intraday_8371.csv.gz  in=463,278,134 out=113,089,395 elapsed=216.7s

  [19460/21087] intraday_8372.csv.gz  in=463,291,280 out=113,089,395 elapsed=216.7s

  [19461/21087] intraday_8373.csv.gz  in=463,300,988 out=113,089,395 elapsed=216.7s

  [19462/21087] intraday_8374.csv.gz  in=463,311,673 out=113,089,395 elapsed=216.7s

  [19463/21087] intraday_8376.csv.gz  in=463,325,293 out=113,089,395 elapsed=216.8s

  [19464/21087] intraday_8375.csv.gz  in=463,339,092 out=113,089,395 elapsed=216.8s

  [19465/21087] intraday_8377.csv.gz  in=463,350,546 out=113,089,395 elapsed=216.8s

  [19466/21087] intraday_8378.csv.gz  in=463,362,588 out=113,089,395 elapsed=216.8s

  [19467/21087] intraday_8379.csv.gz  in=463,375,168 out=113,089,395 elapsed=216.8s

  [19468/21087] intraday_8380.csv.gz  in=463,388,312 out=113,089,395 elapsed=216.8s

  [19469/21087] intraday_8381.csv.gz  in=463,401,066 out=113,089,395 elapsed=216.8s

  [19470/21087] intraday_8382.csv.gz  in=463,415,517 out=113,089,395 elapsed=216.8s

  [19471/21087] intraday_8383.csv.gz  in=463,429,375 out=113,089,395 elapsed=216.8s

  [19472/21087] intraday_8384.csv.gz  in=463,442,560 out=113,089,395 elapsed=216.8s

  [19473/21087] intraday_8385.csv.gz  in=463,454,726 out=113,089,395 elapsed=216.8s

  [19474/21087] intraday_8386.csv.gz  in=463,467,654 out=113,089,395 elapsed=216.8s

  [19475/21087] intraday_8387.csv.gz  in=463,479,650 out=113,089,395 elapsed=216.8s

  [19476/21087] intraday_8388.csv.gz  in=463,494,666 out=113,089,395 elapsed=216.9s

  [19477/21087] intraday_8389.csv.gz  in=463,511,523 out=113,089,395 elapsed=216.9s

  [19478/21087] intraday_8390.csv.gz  in=463,524,822 out=113,089,395 elapsed=216.9s

  [19479/21087] intraday_8391.csv.gz  in=463,536,626 out=113,089,395 elapsed=216.9s

  [19480/21087] intraday_8392.csv.gz  in=463,549,148 out=113,089,395 elapsed=216.9s

  [19481/21087] intraday_8393.csv.gz  in=463,563,538 out=113,089,395 elapsed=216.9s

  [19482/21087] intraday_8394.csv.gz  in=463,575,907 out=113,089,395 elapsed=216.9s

  [19483/21087] intraday_8395.csv.gz  in=463,588,354 out=113,089,395 elapsed=216.9s

  [19484/21087] intraday_8396.csv.gz  in=463,599,959 out=113,089,395 elapsed=216.9s

  [19485/21087] intraday_8397.csv.gz  in=463,613,417 out=113,089,395 elapsed=216.9s

  [19486/21087] intraday_8398.csv.gz  in=463,623,860 out=113,089,395 elapsed=216.9s

  [19487/21087] intraday_8399.csv.gz  in=463,636,182 out=113,089,395 elapsed=216.9s

  [19488/21087] intraday_8400.csv.gz  in=463,648,765 out=113,089,395 elapsed=217.0s

  [19489/21087] intraday_8401.csv.gz  in=463,662,678 out=113,089,395 elapsed=217.0s

  [19490/21087] intraday_8402.csv.gz  in=463,675,304 out=113,089,395 elapsed=217.0s

  [19491/21087] intraday_8404.csv.gz  in=463,686,618 out=113,089,395 elapsed=217.0s

  [19492/21087] intraday_8403.csv.gz  in=463,700,663 out=113,089,395 elapsed=217.0s

  [19493/21087] intraday_8405.csv.gz  in=463,712,499 out=113,089,395 elapsed=217.0s

  [19494/21087] intraday_8406.csv.gz  in=463,726,313 out=113,089,395 elapsed=217.0s

  [19495/21087] intraday_8407.csv.gz  in=463,737,955 out=113,089,395 elapsed=217.0s

  [19496/21087] intraday_8408.csv.gz  in=463,750,921 out=113,089,395 elapsed=217.0s

  [19497/21087] intraday_8409.csv.gz  in=463,762,794 out=113,089,395 elapsed=217.0s

  [19498/21087] intraday_8410.csv.gz  in=463,775,016 out=113,089,395 elapsed=217.0s

  [19499/21087] intraday_8411.csv.gz  in=463,789,981 out=113,089,395 elapsed=217.0s

  [19500/21087] intraday_8412.csv.gz  in=463,802,700 out=113,089,395 elapsed=217.1s

  [19501/21087] intraday_8413.csv.gz  in=463,817,333 out=113,089,395 elapsed=217.1s

  [19502/21087] intraday_8414.csv.gz  in=463,831,031 out=113,089,395 elapsed=217.1s

  [19503/21087] intraday_8415.csv.gz  in=463,842,803 out=113,089,395 elapsed=217.1s

  [19504/21087] intraday_8416.csv.gz  in=463,853,466 out=113,089,395 elapsed=217.1s

  [19505/21087] intraday_8417.csv.gz  in=463,868,582 out=113,089,395 elapsed=217.1s

  [19506/21087] intraday_8418.csv.gz  in=463,882,314 out=113,089,395 elapsed=217.1s

  [19507/21087] intraday_8419.csv.gz  in=463,894,138 out=113,089,395 elapsed=217.1s

  [19508/21087] intraday_8420.csv.gz  in=463,908,369 out=113,089,395 elapsed=217.1s

  [19509/21087] intraday_8421.csv.gz  in=463,919,782 out=113,089,395 elapsed=217.1s

  [19510/21087] intraday_8422.csv.gz  in=463,930,826 out=113,089,395 elapsed=217.1s

  [19511/21087] intraday_8423.csv.gz  in=463,941,969 out=113,089,395 elapsed=217.2s

  [19512/21087] intraday_8425.csv.gz  in=463,954,719 out=113,089,395 elapsed=217.2s

  [19513/21087] intraday_8424.csv.gz  in=463,969,138 out=113,089,395 elapsed=217.2s

  [19514/21087] intraday_8426.csv.gz  in=463,984,226 out=113,089,395 elapsed=217.2s

  [19515/21087] intraday_8427.csv.gz  in=463,996,984 out=113,089,395 elapsed=217.2s

  [19516/21087] intraday_8428.csv.gz  in=464,008,436 out=113,089,395 elapsed=217.2s

  [19517/21087] intraday_8429.csv.gz  in=464,019,909 out=113,089,395 elapsed=217.2s

  [19518/21087] intraday_8430.csv.gz  in=464,033,006 out=113,089,395 elapsed=217.2s

  [19519/21087] intraday_8431.csv.gz  in=464,045,730 out=113,089,395 elapsed=217.2s

  [19520/21087] intraday_8432.csv.gz  in=464,060,067 out=113,089,395 elapsed=217.2s

  [19521/21087] intraday_8433.csv.gz  in=464,071,843 out=113,089,395 elapsed=217.2s

  [19522/21087] intraday_8434.csv.gz  in=464,082,207 out=113,089,395 elapsed=217.2s

  [19523/21087] intraday_8435.csv.gz  in=464,093,273 out=113,089,395 elapsed=217.3s

  [19524/21087] intraday_8436.csv.gz  in=464,107,161 out=113,089,395 elapsed=217.3s

  [19525/21087] intraday_8437.csv.gz  in=464,118,024 out=113,089,395 elapsed=217.3s

  [19526/21087] intraday_8438.csv.gz  in=464,130,700 out=113,089,395 elapsed=217.3s

  [19527/21087] intraday_8439.csv.gz  in=464,140,904 out=113,089,395 elapsed=217.3s

  [19528/21087] intraday_8440.csv.gz  in=464,152,263 out=113,089,395 elapsed=217.3s

  [19529/21087] intraday_8441.csv.gz  in=464,164,739 out=113,089,395 elapsed=217.3s

  [19530/21087] intraday_8442.csv.gz  in=464,180,554 out=113,089,395 elapsed=217.3s

  [19531/21087] intraday_8443.csv.gz  in=464,197,581 out=113,089,395 elapsed=217.3s

  [19532/21087] intraday_8444.csv.gz  in=464,211,173 out=113,089,395 elapsed=217.3s

  [19533/21087] intraday_8445.csv.gz  in=464,222,972 out=113,089,395 elapsed=217.3s

  [19534/21087] intraday_8446.csv.gz  in=464,234,787 out=113,089,395 elapsed=217.3s

  [19535/21087] intraday_8447.csv.gz  in=464,249,342 out=113,089,395 elapsed=217.4s

  [19536/21087] intraday_8450.csv.gz  in=464,261,038 out=113,089,395 elapsed=217.4s

  [19537/21087] intraday_8449.csv.gz  in=464,275,820 out=113,089,395 elapsed=217.4s

  [19538/21087] intraday_8448.csv.gz  in=464,289,834 out=113,089,395 elapsed=217.4s

  [19539/21087] intraday_8451.csv.gz  in=464,304,209 out=113,089,395 elapsed=217.4s

  [19540/21087] intraday_8453.csv.gz  in=464,317,680 out=113,089,395 elapsed=217.4s

  [19541/21087] intraday_8454.csv.gz  in=464,331,933 out=113,089,395 elapsed=217.4s

  [19542/21087] intraday_8452.csv.gz  in=464,346,209 out=113,089,395 elapsed=217.4s

  [19543/21087] intraday_8455.csv.gz  in=464,358,555 out=113,089,395 elapsed=217.4s

  [19544/21087] intraday_8456.csv.gz  in=464,370,525 out=113,089,395 elapsed=217.4s

  [19545/21087] intraday_8457.csv.gz  in=464,383,377 out=113,089,395 elapsed=217.4s

  [19546/21087] intraday_8458.csv.gz  in=464,397,636 out=113,089,395 elapsed=217.4s

  [19547/21087] intraday_8459.csv.gz  in=464,410,580 out=113,089,395 elapsed=217.4s

  [19548/21087] intraday_8460.csv.gz  in=464,424,001 out=113,089,395 elapsed=217.4s

  [19549/21087] intraday_8462.csv.gz  in=464,437,821 out=113,089,395 elapsed=217.5s

  [19550/21087] intraday_8461.csv.gz  in=464,452,977 out=113,089,395 elapsed=217.5s

  [19551/21087] intraday_8463.csv.gz  in=464,465,654 out=113,089,395 elapsed=217.5s

  [19552/21087] intraday_8464.csv.gz  in=464,477,926 out=113,089,395 elapsed=217.5s

  [19553/21087] intraday_8465.csv.gz  in=464,496,970 out=113,089,395 elapsed=217.5s

  [19554/21087] intraday_8466.csv.gz  in=464,509,800 out=113,089,395 elapsed=217.5s

  [19555/21087] intraday_8467.csv.gz  in=464,523,317 out=113,089,395 elapsed=217.5s

  [19556/21087] intraday_8468.csv.gz  in=464,540,055 out=113,089,395 elapsed=217.5s

  [19557/21087] intraday_8469.csv.gz  in=464,553,869 out=113,089,395 elapsed=217.5s

  [19558/21087] intraday_8470.csv.gz  in=464,565,870 out=113,089,395 elapsed=217.5s

  [19559/21087] intraday_8471.csv.gz  in=464,580,186 out=113,089,395 elapsed=217.5s

  [19560/21087] intraday_8472.csv.gz  in=464,593,166 out=113,089,395 elapsed=217.6s

  [19561/21087] intraday_8473.csv.gz  in=464,606,599 out=113,089,395 elapsed=217.6s

  [19562/21087] intraday_8474.csv.gz  in=464,625,991 out=113,089,395 elapsed=217.6s

  [19563/21087] intraday_8475.csv.gz  in=464,639,905 out=113,089,395 elapsed=217.6s

  [19564/21087] intraday_8476.csv.gz  in=464,653,679 out=113,089,395 elapsed=217.6s

  [19565/21087] intraday_8477.csv.gz  in=464,670,106 out=113,089,395 elapsed=217.6s

  [19566/21087] intraday_8478.csv.gz  in=464,683,417 out=113,089,395 elapsed=217.6s

  [19567/21087] intraday_8479.csv.gz  in=464,695,260 out=113,089,395 elapsed=217.6s

  [19568/21087] intraday_8480.csv.gz  in=464,707,373 out=113,089,395 elapsed=217.6s

  [19569/21087] intraday_8481.csv.gz  in=464,720,557 out=113,089,395 elapsed=217.6s

  [19570/21087] intraday_8482.csv.gz  in=464,731,898 out=113,089,395 elapsed=217.6s

  [19571/21087] intraday_8483.csv.gz  in=464,744,478 out=113,089,395 elapsed=217.6s

  [19572/21087] intraday_8484.csv.gz  in=464,758,467 out=113,089,395 elapsed=217.6s

  [19573/21087] intraday_8485.csv.gz  in=464,774,594 out=113,089,395 elapsed=217.7s

  [19574/21087] intraday_8486.csv.gz  in=464,786,245 out=113,089,395 elapsed=217.7s

  [19575/21087] intraday_8487.csv.gz  in=464,799,855 out=113,089,395 elapsed=217.7s

  [19576/21087] intraday_8488.csv.gz  in=464,811,017 out=113,089,395 elapsed=217.7s

  [19577/21087] intraday_8489.csv.gz  in=464,826,283 out=113,089,395 elapsed=217.7s

  [19578/21087] intraday_8490.csv.gz  in=464,837,617 out=113,089,395 elapsed=217.7s

  [19579/21087] intraday_8491.csv.gz  in=464,851,192 out=113,089,395 elapsed=217.7s

  [19580/21087] intraday_8492.csv.gz  in=464,865,846 out=113,089,395 elapsed=217.7s

  [19581/21087] intraday_8493.csv.gz  in=464,880,392 out=113,089,395 elapsed=217.7s

  [19582/21087] intraday_8494.csv.gz  in=464,894,769 out=113,089,395 elapsed=217.7s

  [19583/21087] intraday_8495.csv.gz  in=464,908,904 out=113,089,395 elapsed=217.7s

  [19584/21087] intraday_8496.csv.gz  in=464,920,900 out=113,089,395 elapsed=217.7s

  [19585/21087] intraday_8497.csv.gz  in=464,935,147 out=113,089,395 elapsed=217.8s

  [19586/21087] intraday_8498.csv.gz  in=464,946,707 out=113,089,395 elapsed=217.8s

  [19587/21087] intraday_8499.csv.gz  in=464,961,397 out=113,089,395 elapsed=217.8s

  [19588/21087] intraday_8500.csv.gz  in=464,971,817 out=113,089,395 elapsed=217.8s

  [19589/21087] intraday_8501.csv.gz  in=464,980,495 out=113,089,395 elapsed=217.8s

  [19590/21087] intraday_8503.csv.gz  in=464,981,686 out=113,089,395 elapsed=217.8s

  [19591/21087] intraday_8502.csv.gz  in=464,995,567 out=113,089,395 elapsed=217.8s

  [19592/21087] intraday_8505.csv.gz  in=465,009,730 out=113,089,395 elapsed=217.8s

  [19593/21087] intraday_8507.csv.gz  in=465,021,706 out=113,089,395 elapsed=217.8s

  [19594/21087] intraday_8506.csv.gz  in=465,036,577 out=113,089,395 elapsed=217.8s

  [19595/21087] intraday_8504.csv.gz  in=465,083,298 out=113,089,395 elapsed=217.8s

  [19596/21087] intraday_8508.csv.gz  in=465,096,227 out=113,089,395 elapsed=217.8s

  [19597/21087] intraday_8509.csv.gz  in=465,107,196 out=113,089,395 elapsed=217.9s

  [19598/21087] intraday_8510.csv.gz  in=465,120,200 out=113,089,395 elapsed=217.9s

  [19599/21087] intraday_8511.csv.gz  in=465,134,963 out=113,089,395 elapsed=217.9s

  [19600/21087] intraday_8512.csv.gz  in=465,148,404 out=113,089,395 elapsed=217.9s

  [19601/21087] intraday_8514.csv.gz  in=465,160,082 out=113,089,395 elapsed=217.9s

  [19602/21087] intraday_8513.csv.gz  in=465,172,811 out=113,089,395 elapsed=217.9s

  [19603/21087] intraday_8515.csv.gz  in=465,187,279 out=113,089,395 elapsed=217.9s

  [19604/21087] intraday_8516.csv.gz  in=465,200,195 out=113,089,395 elapsed=217.9s

  [19605/21087] intraday_8517.csv.gz  in=465,213,406 out=113,089,395 elapsed=217.9s

  [19606/21087] intraday_8518.csv.gz  in=465,226,316 out=113,089,395 elapsed=217.9s

  [19607/21087] intraday_8519.csv.gz  in=465,239,060 out=113,089,395 elapsed=217.9s

  [19608/21087] intraday_8520.csv.gz  in=465,248,549 out=113,089,395 elapsed=217.9s

  [19609/21087] intraday_8521.csv.gz  in=465,258,848 out=113,089,395 elapsed=217.9s

  [19610/21087] intraday_8522.csv.gz  in=465,272,772 out=113,089,395 elapsed=218.0s

  [19611/21087] intraday_8523.csv.gz  in=465,285,041 out=113,089,395 elapsed=218.0s

  [19612/21087] intraday_8524.csv.gz  in=465,295,544 out=113,089,395 elapsed=218.0s

  [19613/21087] intraday_8525.csv.gz  in=465,306,211 out=113,089,395 elapsed=218.0s

  [19614/21087] intraday_8526.csv.gz  in=465,318,383 out=113,089,395 elapsed=218.0s

  [19615/21087] intraday_8527.csv.gz  in=465,331,037 out=113,089,395 elapsed=218.0s

  [19616/21087] intraday_8528.csv.gz  in=465,342,864 out=113,089,395 elapsed=218.0s

  [19617/21087] intraday_8529.csv.gz  in=465,356,295 out=113,089,395 elapsed=218.0s

  [19618/21087] intraday_8530.csv.gz  in=465,369,307 out=113,089,395 elapsed=218.0s

  [19619/21087] intraday_8531.csv.gz  in=465,382,748 out=113,089,395 elapsed=218.0s

  [19620/21087] intraday_8532.csv.gz  in=465,394,067 out=113,089,395 elapsed=218.0s

  [19621/21087] intraday_8533.csv.gz  in=465,405,749 out=113,089,395 elapsed=218.0s

  [19622/21087] intraday_8534.csv.gz  in=465,417,715 out=113,089,395 elapsed=218.0s

  [19623/21087] intraday_8535.csv.gz  in=465,431,126 out=113,089,395 elapsed=218.1s

  [19624/21087] intraday_8537.csv.gz  in=465,445,198 out=113,089,395 elapsed=218.1s

  [19625/21087] intraday_8536.csv.gz  in=465,460,749 out=113,089,395 elapsed=218.1s

  [19626/21087] intraday_8538.csv.gz  in=465,471,377 out=113,089,395 elapsed=218.1s

  [19627/21087] intraday_8539.csv.gz  in=465,483,598 out=113,089,395 elapsed=218.1s

  [19628/21087] intraday_8540.csv.gz  in=465,496,231 out=113,089,395 elapsed=218.1s

  [19629/21087] intraday_8541.csv.gz  in=465,507,746 out=113,089,395 elapsed=218.1s

  [19630/21087] intraday_8542.csv.gz  in=465,519,169 out=113,089,395 elapsed=218.1s

  [19631/21087] intraday_8543.csv.gz  in=465,529,419 out=113,089,395 elapsed=218.1s

  [19632/21087] intraday_8544.csv.gz  in=465,541,905 out=113,089,395 elapsed=218.1s

  [19633/21087] intraday_8545.csv.gz  in=465,551,833 out=113,089,395 elapsed=218.1s

  [19634/21087] intraday_8546.csv.gz  in=465,563,121 out=113,089,395 elapsed=218.1s

  [19635/21087] intraday_8547.csv.gz  in=465,575,004 out=113,089,395 elapsed=218.1s

  [19636/21087] intraday_8548.csv.gz  in=465,587,946 out=113,089,395 elapsed=218.2s

  [19637/21087] intraday_8549.csv.gz  in=465,599,539 out=113,089,395 elapsed=218.2s

  [19638/21087] intraday_8550.csv.gz  in=465,612,723 out=113,089,395 elapsed=218.2s

  [19639/21087] intraday_8551.csv.gz  in=465,623,134 out=113,089,395 elapsed=218.2s

  [19640/21087] intraday_8552.csv.gz  in=465,634,324 out=113,089,395 elapsed=218.2s

  [19641/21087] intraday_8553.csv.gz  in=465,647,014 out=113,089,395 elapsed=218.2s

  [19642/21087] intraday_8555.csv.gz  in=465,658,329 out=113,089,395 elapsed=218.2s

  [19643/21087] intraday_8554.csv.gz  in=465,670,059 out=113,089,395 elapsed=218.2s

  [19644/21087] intraday_8556.csv.gz  in=465,681,860 out=113,089,395 elapsed=218.2s

  [19645/21087] intraday_8557.csv.gz  in=465,692,936 out=113,089,395 elapsed=218.2s

  [19646/21087] intraday_8559.csv.gz  in=465,702,883 out=113,089,395 elapsed=218.2s

  [19647/21087] intraday_8558.csv.gz  in=465,716,630 out=113,089,395 elapsed=218.2s

  [19648/21087] intraday_8561.csv.gz  in=465,729,852 out=113,089,395 elapsed=218.3s

  [19649/21087] intraday_8560.csv.gz  in=465,742,913 out=113,089,395 elapsed=218.3s

  [19650/21087] intraday_8562.csv.gz  in=465,754,659 out=113,089,395 elapsed=218.3s

  [19651/21087] intraday_8563.csv.gz  in=465,765,316 out=113,089,395 elapsed=218.3s

  [19652/21087] intraday_8564.csv.gz  in=465,778,751 out=113,089,395 elapsed=218.3s

  [19653/21087] intraday_8565.csv.gz  in=465,790,619 out=113,089,395 elapsed=218.3s

  [19654/21087] intraday_8567.csv.gz  in=465,802,018 out=113,089,395 elapsed=218.3s

  [19655/21087] intraday_8566.csv.gz  in=465,814,649 out=113,089,395 elapsed=218.3s

  [19656/21087] intraday_8569.csv.gz  in=465,825,621 out=113,089,395 elapsed=218.3s

  [19657/21087] intraday_8568.csv.gz  in=465,837,009 out=113,089,395 elapsed=218.3s

  [19658/21087] intraday_8570.csv.gz  in=465,848,326 out=113,089,395 elapsed=218.3s

  [19659/21087] intraday_8571.csv.gz  in=465,861,064 out=113,089,395 elapsed=218.3s

  [19660/21087] intraday_8572.csv.gz  in=465,873,603 out=113,089,395 elapsed=218.4s

  [19661/21087] intraday_8573.csv.gz  in=465,888,648 out=113,089,395 elapsed=218.4s

  [19662/21087] intraday_8574.csv.gz  in=465,900,204 out=113,089,395 elapsed=218.4s

  [19663/21087] intraday_8575.csv.gz  in=465,911,776 out=113,089,395 elapsed=218.4s

  [19664/21087] intraday_8576.csv.gz  in=465,921,555 out=113,089,395 elapsed=218.4s

  [19665/21087] intraday_8577.csv.gz  in=465,934,193 out=113,089,395 elapsed=218.4s

  [19666/21087] intraday_8578.csv.gz  in=465,945,891 out=113,089,395 elapsed=218.4s

  [19667/21087] intraday_8579.csv.gz  in=465,959,475 out=113,089,395 elapsed=218.4s

  [19668/21087] intraday_8580.csv.gz  in=465,969,896 out=113,089,395 elapsed=218.4s

  [19669/21087] intraday_8581.csv.gz  in=465,981,279 out=113,089,395 elapsed=218.4s

  [19670/21087] intraday_8582.csv.gz  in=465,992,695 out=113,089,395 elapsed=218.4s

  [19671/21087] intraday_8583.csv.gz  in=466,005,601 out=113,089,395 elapsed=218.4s

  [19672/21087] intraday_8584.csv.gz  in=466,016,953 out=113,089,395 elapsed=218.4s

  [19673/21087] intraday_8585.csv.gz  in=466,027,438 out=113,089,395 elapsed=218.5s

  [19674/21087] intraday_8586.csv.gz  in=466,037,895 out=113,089,395 elapsed=218.5s

  [19675/21087] intraday_8587.csv.gz  in=466,048,394 out=113,089,395 elapsed=218.5s

  [19676/21087] intraday_8588.csv.gz  in=466,058,235 out=113,089,395 elapsed=218.5s

  [19677/21087] intraday_8589.csv.gz  in=466,072,743 out=113,089,395 elapsed=218.5s

  [19678/21087] intraday_8590.csv.gz  in=466,090,517 out=113,089,395 elapsed=218.5s

  [19679/21087] intraday_8591.csv.gz  in=466,104,255 out=113,089,395 elapsed=218.5s

  [19680/21087] intraday_8592.csv.gz  in=466,114,625 out=113,089,395 elapsed=218.5s

  [19681/21087] intraday_8593.csv.gz  in=466,126,258 out=113,089,395 elapsed=218.5s

  [19682/21087] intraday_8594.csv.gz  in=466,140,582 out=113,089,395 elapsed=218.5s

  [19683/21087] intraday_8595.csv.gz  in=466,152,167 out=113,089,395 elapsed=218.5s

  [19684/21087] intraday_8596.csv.gz  in=466,167,287 out=113,089,395 elapsed=218.5s

  [19685/21087] intraday_8597.csv.gz  in=466,178,943 out=113,089,395 elapsed=218.5s

  [19686/21087] intraday_8598.csv.gz  in=466,191,740 out=113,089,395 elapsed=218.6s

  [19687/21087] intraday_8599.csv.gz  in=466,203,585 out=113,089,395 elapsed=218.6s

  [19688/21087] intraday_8600.csv.gz  in=466,217,870 out=113,089,395 elapsed=218.6s

  [19689/21087] intraday_8601.csv.gz  in=466,231,448 out=113,089,395 elapsed=218.6s

  [19690/21087] intraday_8602.csv.gz  in=466,244,235 out=113,089,395 elapsed=218.6s

  [19691/21087] intraday_8603.csv.gz  in=466,256,613 out=113,089,395 elapsed=218.6s

  [19692/21087] intraday_8604.csv.gz  in=466,267,324 out=113,089,395 elapsed=218.6s

  [19693/21087] intraday_8605.csv.gz  in=466,280,612 out=113,089,395 elapsed=218.6s

  [19694/21087] intraday_8606.csv.gz  in=466,292,950 out=113,089,395 elapsed=218.6s

  [19695/21087] intraday_8607.csv.gz  in=466,305,076 out=113,089,395 elapsed=218.6s

  [19696/21087] intraday_8608.csv.gz  in=466,317,502 out=113,089,395 elapsed=218.6s

  [19697/21087] intraday_8609.csv.gz  in=466,331,860 out=113,089,395 elapsed=218.6s

  [19698/21087] intraday_8610.csv.gz  in=466,343,276 out=113,089,395 elapsed=218.6s

  [19699/21087] intraday_8611.csv.gz  in=466,355,491 out=113,089,395 elapsed=218.7s

  [19700/21087] intraday_8612.csv.gz  in=466,371,465 out=113,089,395 elapsed=218.7s

  [19701/21087] intraday_8613.csv.gz  in=466,383,450 out=113,089,395 elapsed=218.7s

  [19702/21087] intraday_8614.csv.gz  in=466,396,881 out=113,089,395 elapsed=218.7s

  [19703/21087] intraday_8615.csv.gz  in=466,410,816 out=113,089,395 elapsed=218.7s

  [19704/21087] intraday_8616.csv.gz  in=466,426,458 out=113,089,395 elapsed=218.7s

  [19705/21087] intraday_8617.csv.gz  in=466,436,754 out=113,089,395 elapsed=218.7s

  [19706/21087] intraday_8618.csv.gz  in=466,449,257 out=113,089,395 elapsed=218.7s

  [19707/21087] intraday_8619.csv.gz  in=466,462,060 out=113,089,395 elapsed=218.7s

  [19708/21087] intraday_8620.csv.gz  in=466,475,117 out=113,089,395 elapsed=218.7s

  [19709/21087] intraday_8621.csv.gz  in=466,489,555 out=113,089,395 elapsed=218.7s

  [19710/21087] intraday_8622.csv.gz  in=466,505,997 out=113,089,395 elapsed=218.7s

  [19711/21087] intraday_8624.csv.gz  in=466,519,821 out=113,089,395 elapsed=218.7s

  [19712/21087] intraday_8623.csv.gz  in=466,548,805 out=113,089,395 elapsed=218.8s

  [19713/21087] intraday_8626.csv.gz  in=466,561,264 out=113,089,395 elapsed=218.8s

  [19714/21087] intraday_8625.csv.gz  in=466,576,854 out=113,089,395 elapsed=218.8s

  [19715/21087] intraday_8627.csv.gz  in=466,590,267 out=113,089,395 elapsed=218.8s

  [19716/21087] intraday_8628.csv.gz  in=466,600,073 out=113,089,395 elapsed=218.8s

  [19717/21087] intraday_8630.csv.gz  in=466,609,831 out=113,089,395 elapsed=218.8s

  [19718/21087] intraday_8629.csv.gz  in=466,624,422 out=113,089,395 elapsed=218.8s

  [19719/21087] intraday_8631.csv.gz  in=466,637,295 out=113,089,395 elapsed=218.8s

  [19720/21087] intraday_8632.csv.gz  in=466,650,419 out=113,089,395 elapsed=218.8s

  [19721/21087] intraday_8634.csv.gz  in=466,661,592 out=113,089,395 elapsed=218.8s

  [19722/21087] intraday_8633.csv.gz  in=466,676,391 out=113,089,395 elapsed=218.8s

  [19723/21087] intraday_8635.csv.gz  in=466,688,487 out=113,089,395 elapsed=218.8s

  [19724/21087] intraday_8636.csv.gz  in=466,700,097 out=113,089,395 elapsed=218.8s

  [19725/21087] intraday_8637.csv.gz  in=466,712,270 out=113,089,395 elapsed=218.9s

  [19726/21087] intraday_8638.csv.gz  in=466,723,263 out=113,089,395 elapsed=218.9s

  [19727/21087] intraday_8639.csv.gz  in=466,737,654 out=113,089,395 elapsed=218.9s

  [19728/21087] intraday_8640.csv.gz  in=466,752,295 out=113,089,395 elapsed=218.9s

  [19729/21087] intraday_8641.csv.gz  in=466,764,936 out=113,089,395 elapsed=218.9s

  [19730/21087] intraday_8642.csv.gz  in=466,779,965 out=113,089,395 elapsed=218.9s

  [19731/21087] intraday_8643.csv.gz  in=466,792,654 out=113,089,395 elapsed=218.9s

  [19732/21087] intraday_8644.csv.gz  in=466,804,784 out=113,089,395 elapsed=218.9s

  [19733/21087] intraday_8645.csv.gz  in=466,818,533 out=113,089,395 elapsed=218.9s

  [19734/21087] intraday_8646.csv.gz  in=466,829,519 out=113,089,395 elapsed=218.9s

  [19735/21087] intraday_8647.csv.gz  in=466,840,825 out=113,089,395 elapsed=218.9s

  [19736/21087] intraday_8648.csv.gz  in=466,847,814 out=113,089,395 elapsed=218.9s

  [19737/21087] intraday_8649.csv.gz  in=466,859,065 out=113,089,395 elapsed=219.0s

  [19738/21087] intraday_8650.csv.gz  in=466,866,851 out=113,089,395 elapsed=219.0s

  [19739/21087] intraday_8651.csv.gz  in=466,882,131 out=113,089,395 elapsed=219.0s

  [19740/21087] intraday_8652.csv.gz  in=466,897,602 out=113,089,395 elapsed=219.0s

  [19741/21087] intraday_8653.csv.gz  in=466,910,004 out=113,089,395 elapsed=219.0s

  [19742/21087] intraday_8654.csv.gz  in=466,922,933 out=113,089,395 elapsed=219.0s

  [19743/21087] intraday_8655.csv.gz  in=466,935,300 out=113,089,395 elapsed=219.0s

  [19744/21087] intraday_8656.csv.gz  in=466,946,991 out=113,089,395 elapsed=219.0s

  [19745/21087] intraday_8657.csv.gz  in=466,962,075 out=113,089,395 elapsed=219.0s

  [19746/21087] intraday_8658.csv.gz  in=466,976,896 out=113,089,395 elapsed=219.0s

  [19747/21087] intraday_8659.csv.gz  in=466,988,774 out=113,089,395 elapsed=219.0s

  [19748/21087] intraday_8660.csv.gz  in=467,001,712 out=113,089,395 elapsed=219.0s

  [19749/21087] intraday_8661.csv.gz  in=467,015,905 out=113,089,395 elapsed=219.0s

  [19750/21087] intraday_8663.csv.gz  in=467,029,023 out=113,089,395 elapsed=219.1s

  [19751/21087] intraday_8662.csv.gz  in=467,043,115 out=113,089,395 elapsed=219.1s

  [19752/21087] intraday_8664.csv.gz  in=467,057,296 out=113,089,395 elapsed=219.1s

  [19753/21087] intraday_8665.csv.gz  in=467,071,326 out=113,089,395 elapsed=219.1s

  [19754/21087] intraday_8666.csv.gz  in=467,080,887 out=113,089,395 elapsed=219.1s

  [19755/21087] intraday_8667.csv.gz  in=467,092,775 out=113,089,395 elapsed=219.1s

  [19756/21087] intraday_8668.csv.gz  in=467,106,398 out=113,089,395 elapsed=219.1s

  [19757/21087] intraday_8669.csv.gz  in=467,120,087 out=113,089,395 elapsed=219.1s

  [19758/21087] intraday_8671.csv.gz  in=467,131,729 out=113,089,395 elapsed=219.1s

  [19759/21087] intraday_8670.csv.gz  in=467,143,411 out=113,089,395 elapsed=219.1s

  [19760/21087] intraday_8672.csv.gz  in=467,154,300 out=113,089,395 elapsed=219.1s

  [19761/21087] intraday_8673.csv.gz  in=467,168,992 out=113,089,395 elapsed=219.1s

  [19762/21087] intraday_8674.csv.gz  in=467,181,283 out=113,089,395 elapsed=219.1s

  [19763/21087] intraday_8675.csv.gz  in=467,194,420 out=113,089,395 elapsed=219.1s

  [19764/21087] intraday_8676.csv.gz  in=467,208,056 out=113,089,395 elapsed=219.2s

  [19765/21087] intraday_8677.csv.gz  in=467,220,602 out=113,089,395 elapsed=219.2s

  [19766/21087] intraday_8679.csv.gz  in=467,232,049 out=113,089,395 elapsed=219.2s

  [19767/21087] intraday_8678.csv.gz  in=467,244,983 out=113,089,395 elapsed=219.2s

  [19768/21087] intraday_8680.csv.gz  in=467,257,057 out=113,089,395 elapsed=219.2s

  [19769/21087] intraday_8681.csv.gz  in=467,270,362 out=113,089,395 elapsed=219.2s

  [19770/21087] intraday_8682.csv.gz  in=467,287,482 out=113,089,395 elapsed=219.2s

  [19771/21087] intraday_8683.csv.gz  in=467,302,009 out=113,089,395 elapsed=219.2s

  [19772/21087] intraday_8685.csv.gz  in=467,314,197 out=113,089,395 elapsed=219.2s

  [19773/21087] intraday_8684.csv.gz  in=467,324,570 out=113,089,395 elapsed=219.2s

  [19774/21087] intraday_8686.csv.gz  in=467,338,065 out=113,089,395 elapsed=219.2s

  [19775/21087] intraday_8687.csv.gz  in=467,349,236 out=113,089,395 elapsed=219.2s

  [19776/21087] intraday_8688.csv.gz  in=467,361,536 out=113,089,395 elapsed=219.2s

  [19777/21087] intraday_8689.csv.gz  in=467,372,275 out=113,089,395 elapsed=219.2s

  [19778/21087] intraday_8690.csv.gz  in=467,385,012 out=113,089,395 elapsed=219.3s

  [19779/21087] intraday_8692.csv.gz  in=467,396,964 out=113,089,395 elapsed=219.3s

  [19780/21087] intraday_8691.csv.gz  in=467,407,605 out=113,089,395 elapsed=219.3s

  [19781/21087] intraday_8693.csv.gz  in=467,419,532 out=113,089,395 elapsed=219.3s

  [19782/21087] intraday_8694.csv.gz  in=467,433,146 out=113,089,395 elapsed=219.3s

  [19783/21087] intraday_8695.csv.gz  in=467,445,179 out=113,089,395 elapsed=219.3s

  [19784/21087] intraday_8696.csv.gz  in=467,459,735 out=113,089,395 elapsed=219.3s

  [19785/21087] intraday_8697.csv.gz  in=467,470,603 out=113,089,395 elapsed=219.3s

  [19786/21087] intraday_8698.csv.gz  in=467,482,630 out=113,089,395 elapsed=219.3s

  [19787/21087] intraday_8699.csv.gz  in=467,495,981 out=113,089,395 elapsed=219.3s

  [19788/21087] intraday_8700.csv.gz  in=467,507,347 out=113,089,395 elapsed=219.3s

  [19789/21087] intraday_8701.csv.gz  in=467,518,788 out=113,089,395 elapsed=219.3s

  [19790/21087] intraday_8702.csv.gz  in=467,530,987 out=113,089,395 elapsed=219.4s

  [19791/21087] intraday_8703.csv.gz  in=467,541,825 out=113,089,395 elapsed=219.4s

  [19792/21087] intraday_8705.csv.gz  in=467,553,329 out=113,089,395 elapsed=219.4s

  [19793/21087] intraday_8704.csv.gz  in=467,568,790 out=113,089,395 elapsed=219.4s

  [19794/21087] intraday_8706.csv.gz  in=467,581,702 out=113,089,395 elapsed=219.4s

  [19795/21087] intraday_8707.csv.gz  in=467,594,902 out=113,089,395 elapsed=219.4s

  [19796/21087] intraday_8708.csv.gz  in=467,606,715 out=113,089,395 elapsed=219.4s

  [19797/21087] intraday_8709.csv.gz  in=467,617,418 out=113,089,395 elapsed=219.4s

  [19798/21087] intraday_8710.csv.gz  in=467,631,191 out=113,089,395 elapsed=219.4s

  [19799/21087] intraday_8711.csv.gz  in=467,644,500 out=113,089,395 elapsed=219.4s

  [19800/21087] intraday_8712.csv.gz  in=467,655,987 out=113,089,395 elapsed=219.4s

  [19801/21087] intraday_8713.csv.gz  in=467,669,303 out=113,089,395 elapsed=219.4s

  [19802/21087] intraday_8714.csv.gz  in=467,680,681 out=113,089,395 elapsed=219.5s

  [19803/21087] intraday_8715.csv.gz  in=467,693,344 out=113,089,395 elapsed=219.5s

  [19804/21087] intraday_8716.csv.gz  in=467,704,004 out=113,089,395 elapsed=219.5s

  [19805/21087] intraday_8717.csv.gz  in=467,719,114 out=113,089,395 elapsed=219.5s

  [19806/21087] intraday_8718.csv.gz  in=467,732,085 out=113,089,395 elapsed=219.5s

  [19807/21087] intraday_8720.csv.gz  in=467,743,896 out=113,089,395 elapsed=219.5s

  [19808/21087] intraday_8719.csv.gz  in=467,761,651 out=113,089,395 elapsed=219.5s

  [19809/21087] intraday_8721.csv.gz  in=467,773,076 out=113,089,395 elapsed=219.5s

  [19810/21087] intraday_8722.csv.gz  in=467,783,656 out=113,089,395 elapsed=219.5s

  [19811/21087] intraday_8723.csv.gz  in=467,796,722 out=113,089,395 elapsed=219.5s

  [19812/21087] intraday_8724.csv.gz  in=467,809,124 out=113,089,395 elapsed=219.5s

  [19813/21087] intraday_8725.csv.gz  in=467,823,228 out=113,089,395 elapsed=219.5s

  [19814/21087] intraday_8726.csv.gz  in=467,834,048 out=113,089,395 elapsed=219.5s

  [19815/21087] intraday_8727.csv.gz  in=467,846,662 out=113,089,395 elapsed=219.6s

  [19816/21087] intraday_8728.csv.gz  in=467,857,825 out=113,089,395 elapsed=219.6s

  [19817/21087] intraday_8730.csv.gz  in=467,868,178 out=113,089,395 elapsed=219.6s

  [19818/21087] intraday_8729.csv.gz  in=467,882,204 out=113,089,395 elapsed=219.6s

  [19819/21087] intraday_8731.csv.gz  in=467,893,874 out=113,089,395 elapsed=219.6s

  [19820/21087] intraday_8732.csv.gz  in=467,905,076 out=113,089,395 elapsed=219.6s

  [19821/21087] intraday_8733.csv.gz  in=467,915,478 out=113,089,395 elapsed=219.6s

  [19822/21087] intraday_8734.csv.gz  in=467,926,576 out=113,089,395 elapsed=219.6s

  [19823/21087] intraday_8735.csv.gz  in=467,942,677 out=113,089,395 elapsed=219.6s

  [19824/21087] intraday_8736.csv.gz  in=467,958,764 out=113,089,395 elapsed=219.6s

  [19825/21087] intraday_8738.csv.gz  in=467,970,101 out=113,089,395 elapsed=219.6s

  [19826/21087] intraday_8737.csv.gz  in=467,983,343 out=113,089,395 elapsed=219.6s

  [19827/21087] intraday_8739.csv.gz  in=467,995,979 out=113,089,395 elapsed=219.6s

  [19828/21087] intraday_8740.csv.gz  in=468,009,745 out=113,089,395 elapsed=219.6s

  [19829/21087] intraday_8741.csv.gz  in=468,021,819 out=113,089,395 elapsed=219.7s

  [19830/21087] intraday_8742.csv.gz  in=468,036,802 out=113,089,395 elapsed=219.7s

  [19831/21087] intraday_8743.csv.gz  in=468,048,986 out=113,089,395 elapsed=219.7s

  [19832/21087] intraday_8745.csv.gz  in=468,062,147 out=113,089,395 elapsed=219.7s

  [19833/21087] intraday_8744.csv.gz  in=468,076,759 out=113,089,395 elapsed=219.7s

  [19834/21087] intraday_8746.csv.gz  in=468,089,781 out=113,089,395 elapsed=219.7s

  [19835/21087] intraday_8747.csv.gz  in=468,103,404 out=113,089,395 elapsed=219.7s

  [19836/21087] intraday_8748.csv.gz  in=468,115,506 out=113,089,395 elapsed=219.7s

  [19837/21087] intraday_8750.csv.gz  in=468,127,529 out=113,089,395 elapsed=219.7s

  [19838/21087] intraday_8749.csv.gz  in=468,145,806 out=113,089,395 elapsed=219.7s

  [19839/21087] intraday_8751.csv.gz  in=468,158,704 out=113,089,395 elapsed=219.8s

  [19840/21087] intraday_8752.csv.gz  in=468,170,146 out=113,089,395 elapsed=219.8s

  [19841/21087] intraday_8753.csv.gz  in=468,183,854 out=113,089,395 elapsed=219.8s

  [19842/21087] intraday_8754.csv.gz  in=468,196,162 out=113,089,395 elapsed=219.8s

  [19843/21087] intraday_8756.csv.gz  in=468,207,752 out=113,089,395 elapsed=219.8s

  [19844/21087] intraday_8755.csv.gz  in=468,225,055 out=113,089,395 elapsed=219.8s

  [19845/21087] intraday_8757.csv.gz  in=468,237,648 out=113,089,395 elapsed=219.8s

  [19846/21087] intraday_8758.csv.gz  in=468,253,456 out=113,089,395 elapsed=219.8s

  [19847/21087] intraday_8759.csv.gz  in=468,266,035 out=113,089,395 elapsed=219.8s

  [19848/21087] intraday_8760.csv.gz  in=468,278,587 out=113,089,395 elapsed=219.8s

  [19849/21087] intraday_8761.csv.gz  in=468,293,717 out=113,089,395 elapsed=219.8s

  [19850/21087] intraday_8763.csv.gz  in=468,304,636 out=113,089,395 elapsed=219.9s

  [19851/21087] intraday_8764.csv.gz  in=468,317,755 out=113,089,395 elapsed=219.9s

  [19852/21087] intraday_8762.csv.gz  in=468,332,981 out=113,089,395 elapsed=219.9s

  [19853/21087] intraday_8765.csv.gz  in=468,345,893 out=113,089,395 elapsed=219.9s

  [19854/21087] intraday_8766.csv.gz  in=468,358,356 out=113,089,395 elapsed=219.9s

  [19855/21087] intraday_8768.csv.gz  in=468,373,964 out=113,089,395 elapsed=219.9s

  [19856/21087] intraday_8767.csv.gz  in=468,389,279 out=113,089,395 elapsed=219.9s

  [19857/21087] intraday_8769.csv.gz  in=468,410,871 out=113,089,395 elapsed=219.9s

  [19858/21087] intraday_8772.csv.gz  in=468,423,474 out=113,089,395 elapsed=219.9s

  [19859/21087] intraday_8770.csv.gz  in=468,438,831 out=113,089,395 elapsed=219.9s

  [19860/21087] intraday_8771.csv.gz  in=468,453,201 out=113,089,395 elapsed=219.9s

  [19861/21087] intraday_8773.csv.gz  in=468,465,653 out=113,089,395 elapsed=219.9s

  [19862/21087] intraday_8774.csv.gz  in=468,476,286 out=113,089,395 elapsed=220.0s

  [19863/21087] intraday_8775.csv.gz  in=468,490,910 out=113,089,395 elapsed=220.0s

  [19864/21087] intraday_8776.csv.gz  in=468,501,957 out=113,089,395 elapsed=220.0s

  [19865/21087] intraday_8777.csv.gz  in=468,514,755 out=113,089,395 elapsed=220.0s

  [19866/21087] intraday_8778.csv.gz  in=468,528,618 out=113,089,395 elapsed=220.0s

  [19867/21087] intraday_8779.csv.gz  in=468,543,152 out=113,089,395 elapsed=220.0s

  [19868/21087] intraday_8780.csv.gz  in=468,554,315 out=113,089,395 elapsed=220.0s

  [19869/21087] intraday_8781.csv.gz  in=468,566,161 out=113,089,395 elapsed=220.0s

  [19870/21087] intraday_8782.csv.gz  in=468,578,135 out=113,089,395 elapsed=220.0s

  [19871/21087] intraday_8783.csv.gz  in=468,590,390 out=113,089,395 elapsed=220.0s

  [19872/21087] intraday_8784.csv.gz  in=468,601,978 out=113,089,395 elapsed=220.0s

  [19873/21087] intraday_8785.csv.gz  in=468,616,063 out=113,089,395 elapsed=220.0s

  [19874/21087] intraday_8786.csv.gz  in=468,630,943 out=113,089,395 elapsed=220.0s

  [19875/21087] intraday_8787.csv.gz  in=468,644,641 out=113,089,395 elapsed=220.0s

  [19876/21087] intraday_8788.csv.gz  in=468,659,392 out=113,089,395 elapsed=220.1s

  [19877/21087] intraday_8789.csv.gz  in=468,671,664 out=113,089,395 elapsed=220.1s

  [19878/21087] intraday_8790.csv.gz  in=468,683,533 out=113,089,395 elapsed=220.1s

  [19879/21087] intraday_8792.csv.gz  in=468,694,776 out=113,089,395 elapsed=220.1s

  [19880/21087] intraday_8791.csv.gz  in=468,709,005 out=113,089,395 elapsed=220.1s

  [19881/21087] intraday_8793.csv.gz  in=468,720,638 out=113,089,395 elapsed=220.1s

  [19882/21087] intraday_8794.csv.gz  in=468,727,243 out=113,089,395 elapsed=220.1s

  [19883/21087] intraday_8796.csv.gz  in=468,733,901 out=113,089,395 elapsed=220.1s

  [19884/21087] intraday_8795.csv.gz  in=468,746,836 out=113,089,395 elapsed=220.1s

  [19885/21087] intraday_8797.csv.gz  in=468,762,228 out=113,089,395 elapsed=220.1s

  [19886/21087] intraday_8798.csv.gz  in=468,774,094 out=113,089,395 elapsed=220.1s

  [19887/21087] intraday_8799.csv.gz  in=468,788,432 out=113,089,395 elapsed=220.1s

  [19888/21087] intraday_8800.csv.gz  in=468,798,830 out=113,089,395 elapsed=220.1s

  [19889/21087] intraday_8801.csv.gz  in=468,811,065 out=113,089,395 elapsed=220.2s

  [19890/21087] intraday_8802.csv.gz  in=468,826,624 out=113,089,395 elapsed=220.2s

  [19891/21087] intraday_8803.csv.gz  in=468,840,807 out=113,089,395 elapsed=220.2s

  [19892/21087] intraday_8804.csv.gz  in=468,852,406 out=113,089,395 elapsed=220.2s

  [19893/21087] intraday_8805.csv.gz  in=468,864,888 out=113,089,395 elapsed=220.2s

  [19894/21087] intraday_8806.csv.gz  in=468,879,620 out=113,089,395 elapsed=220.2s

  [19895/21087] intraday_8807.csv.gz  in=468,893,885 out=113,089,395 elapsed=220.2s

  [19896/21087] intraday_8808.csv.gz  in=468,907,811 out=113,089,395 elapsed=220.2s

  [19897/21087] intraday_8809.csv.gz  in=468,921,285 out=113,089,395 elapsed=220.2s

  [19898/21087] intraday_8810.csv.gz  in=468,935,600 out=113,089,395 elapsed=220.2s

  [19899/21087] intraday_8811.csv.gz  in=468,945,494 out=113,089,395 elapsed=220.2s

  [19900/21087] intraday_8812.csv.gz  in=468,957,332 out=113,089,395 elapsed=220.2s

  [19901/21087] intraday_8813.csv.gz  in=468,971,246 out=113,089,395 elapsed=220.3s

  [19902/21087] intraday_8814.csv.gz  in=468,983,491 out=113,089,395 elapsed=220.3s

  [19903/21087] intraday_8815.csv.gz  in=468,995,752 out=113,089,395 elapsed=220.3s

  [19904/21087] intraday_8816.csv.gz  in=469,006,948 out=113,089,395 elapsed=220.3s

  [19905/21087] intraday_8817.csv.gz  in=469,019,081 out=113,089,395 elapsed=220.3s

  [19906/21087] intraday_8819.csv.gz  in=469,031,855 out=113,089,395 elapsed=220.3s

  [19907/21087] intraday_8820.csv.gz  in=469,045,491 out=113,089,395 elapsed=220.3s

  [19908/21087] intraday_8818.csv.gz  in=469,059,628 out=113,089,395 elapsed=220.3s

  [19909/21087] intraday_8821.csv.gz  in=469,073,051 out=113,089,395 elapsed=220.3s

  [19910/21087] intraday_8823.csv.gz  in=469,085,445 out=113,089,395 elapsed=220.3s

  [19911/21087] intraday_8822.csv.gz  in=469,098,749 out=113,089,395 elapsed=220.3s

  [19912/21087] intraday_8824.csv.gz  in=469,110,739 out=113,089,395 elapsed=220.3s

  [19913/21087] intraday_8825.csv.gz  in=469,127,711 out=113,089,395 elapsed=220.4s

  [19914/21087] intraday_8826.csv.gz  in=469,141,763 out=113,089,395 elapsed=220.4s

  [19915/21087] intraday_8827.csv.gz  in=469,157,573 out=113,089,395 elapsed=220.4s

  [19916/21087] intraday_8828.csv.gz  in=469,171,115 out=113,089,395 elapsed=220.4s

  [19917/21087] intraday_8829.csv.gz  in=469,182,555 out=113,089,395 elapsed=220.4s

  [19918/21087] intraday_8830.csv.gz  in=469,194,990 out=113,089,395 elapsed=220.4s

  [19919/21087] intraday_8832.csv.gz  in=469,205,951 out=113,089,395 elapsed=220.4s

  [19920/21087] intraday_8831.csv.gz  in=469,218,870 out=113,089,395 elapsed=220.4s

  [19921/21087] intraday_8833.csv.gz  in=469,231,737 out=113,089,395 elapsed=220.4s

  [19922/21087] intraday_8834.csv.gz  in=469,242,415 out=113,089,395 elapsed=220.4s

  [19923/21087] intraday_8835.csv.gz  in=469,254,681 out=113,089,395 elapsed=220.4s

  [19924/21087] intraday_8836.csv.gz  in=469,265,734 out=113,089,395 elapsed=220.5s

  [19925/21087] intraday_8837.csv.gz  in=469,277,561 out=113,089,395 elapsed=220.5s

  [19926/21087] intraday_8838.csv.gz  in=469,289,911 out=113,089,395 elapsed=220.5s

  [19927/21087] intraday_8839.csv.gz  in=469,303,654 out=113,089,395 elapsed=220.5s

  [19928/21087] intraday_8840.csv.gz  in=469,315,751 out=113,089,395 elapsed=220.5s

  [19929/21087] intraday_8841.csv.gz  in=469,329,529 out=113,089,395 elapsed=220.5s

  [19930/21087] intraday_8842.csv.gz  in=469,340,684 out=113,089,395 elapsed=220.5s

  [19931/21087] intraday_8843.csv.gz  in=469,351,797 out=113,089,395 elapsed=220.5s

  [19932/21087] intraday_8844.csv.gz  in=469,365,431 out=113,089,395 elapsed=220.5s

  [19933/21087] intraday_8845.csv.gz  in=469,375,942 out=113,089,395 elapsed=220.5s

  [19934/21087] intraday_8846.csv.gz  in=469,387,696 out=113,089,395 elapsed=220.5s

  [19935/21087] intraday_8847.csv.gz  in=469,399,733 out=113,089,395 elapsed=220.5s

  [19936/21087] intraday_8848.csv.gz  in=469,411,150 out=113,089,395 elapsed=220.5s

  [19937/21087] intraday_8849.csv.gz  in=469,427,032 out=113,089,395 elapsed=220.6s

  [19938/21087] intraday_8850.csv.gz  in=469,440,456 out=113,089,395 elapsed=220.6s

  [19939/21087] intraday_8851.csv.gz  in=469,453,843 out=113,089,395 elapsed=220.6s

  [19940/21087] intraday_8852.csv.gz  in=469,473,378 out=113,089,395 elapsed=220.6s

  [19941/21087] intraday_8854.csv.gz  in=469,484,510 out=113,089,395 elapsed=220.6s

  [19942/21087] intraday_8853.csv.gz  in=469,498,588 out=113,089,395 elapsed=220.6s

  [19943/21087] intraday_8855.csv.gz  in=469,510,796 out=113,089,395 elapsed=220.6s

  [19944/21087] intraday_8856.csv.gz  in=469,523,494 out=113,089,395 elapsed=220.6s

  [19945/21087] intraday_8857.csv.gz  in=469,535,928 out=113,089,395 elapsed=220.6s

  [19946/21087] intraday_8859.csv.gz  in=469,546,988 out=113,089,395 elapsed=220.6s

  [19947/21087] intraday_8858.csv.gz  in=469,563,949 out=113,089,395 elapsed=220.6s

  [19948/21087] intraday_8860.csv.gz  in=469,576,711 out=113,089,395 elapsed=220.6s

  [19949/21087] intraday_8861.csv.gz  in=469,587,582 out=113,089,395 elapsed=220.6s

  [19950/21087] intraday_8862.csv.gz  in=469,602,959 out=113,089,395 elapsed=220.7s

  [19951/21087] intraday_8863.csv.gz  in=469,615,018 out=113,089,395 elapsed=220.7s

  [19952/21087] intraday_8864.csv.gz  in=469,629,001 out=113,089,395 elapsed=220.7s

  [19953/21087] intraday_8865.csv.gz  in=469,642,631 out=113,089,395 elapsed=220.7s

  [19954/21087] intraday_8867.csv.gz  in=469,651,908 out=113,089,395 elapsed=220.7s

  [19955/21087] intraday_8866.csv.gz  in=469,663,055 out=113,089,395 elapsed=220.7s

  [19956/21087] intraday_8868.csv.gz  in=469,675,051 out=113,089,395 elapsed=220.7s

  [19957/21087] intraday_8869.csv.gz  in=469,688,141 out=113,089,395 elapsed=220.7s

  [19958/21087] intraday_8870.csv.gz  in=469,701,948 out=113,089,395 elapsed=220.7s

  [19959/21087] intraday_8871.csv.gz  in=469,716,481 out=113,089,395 elapsed=220.7s

  [19960/21087] intraday_8872.csv.gz  in=469,729,219 out=113,089,395 elapsed=220.7s

  [19961/21087] intraday_8873.csv.gz  in=469,742,430 out=113,089,395 elapsed=220.7s

  [19962/21087] intraday_8874.csv.gz  in=469,756,087 out=113,089,395 elapsed=220.7s

  [19963/21087] intraday_8875.csv.gz  in=469,766,797 out=113,089,395 elapsed=220.8s

  [19964/21087] intraday_8876.csv.gz  in=469,778,512 out=113,089,395 elapsed=220.8s

  [19965/21087] intraday_8877.csv.gz  in=469,794,552 out=113,089,395 elapsed=220.8s

  [19966/21087] intraday_8878.csv.gz  in=469,805,872 out=113,089,395 elapsed=220.8s

  [19967/21087] intraday_8879.csv.gz  in=469,817,265 out=113,089,395 elapsed=220.8s

  [19968/21087] intraday_8880.csv.gz  in=469,830,839 out=113,089,395 elapsed=220.8s

  [19969/21087] intraday_8881.csv.gz  in=469,849,183 out=113,089,395 elapsed=220.8s

  [19970/21087] intraday_8883.csv.gz  in=469,860,833 out=113,089,395 elapsed=220.8s

  [19971/21087] intraday_8882.csv.gz  in=469,873,699 out=113,089,395 elapsed=220.8s

  [19972/21087] intraday_8884.csv.gz  in=469,886,234 out=113,089,395 elapsed=220.8s

  [19973/21087] intraday_8886.csv.gz  in=469,898,771 out=113,089,395 elapsed=220.8s

  [19974/21087] intraday_8885.csv.gz  in=469,913,326 out=113,089,395 elapsed=220.8s

  [19975/21087] intraday_8887.csv.gz  in=469,928,561 out=113,089,395 elapsed=220.8s

  [19976/21087] intraday_8888.csv.gz  in=469,942,189 out=113,089,395 elapsed=220.8s

  [19977/21087] intraday_8889.csv.gz  in=469,955,055 out=113,089,395 elapsed=220.9s

  [19978/21087] intraday_8890.csv.gz  in=469,967,691 out=113,089,395 elapsed=220.9s

  [19979/21087] intraday_8891.csv.gz  in=469,981,040 out=113,089,395 elapsed=220.9s

  [19980/21087] intraday_8892.csv.gz  in=469,995,445 out=113,089,395 elapsed=220.9s

  [19981/21087] intraday_8893.csv.gz  in=470,008,795 out=113,089,395 elapsed=220.9s

  [19982/21087] intraday_8895.csv.gz  in=470,019,900 out=113,089,395 elapsed=220.9s

  [19983/21087] intraday_8894.csv.gz  in=470,033,540 out=113,089,395 elapsed=220.9s

  [19984/21087] intraday_8896.csv.gz  in=470,058,514 out=113,089,395 elapsed=220.9s

  [19985/21087] intraday_8897.csv.gz  in=470,071,873 out=113,089,395 elapsed=220.9s

  [19986/21087] intraday_8898.csv.gz  in=470,083,295 out=113,089,395 elapsed=220.9s

  [19987/21087] intraday_8899.csv.gz  in=470,098,093 out=113,089,395 elapsed=220.9s

  [19988/21087] intraday_8900.csv.gz  in=470,111,468 out=113,089,395 elapsed=220.9s

  [19989/21087] intraday_8901.csv.gz  in=470,125,407 out=113,089,395 elapsed=221.0s

  [19990/21087] intraday_8902.csv.gz  in=470,137,646 out=113,089,395 elapsed=221.0s

  [19991/21087] intraday_8903.csv.gz  in=470,151,247 out=113,089,395 elapsed=221.0s

  [19992/21087] intraday_8904.csv.gz  in=470,164,478 out=113,089,395 elapsed=221.0s

  [19993/21087] intraday_8905.csv.gz  in=470,176,870 out=113,089,395 elapsed=221.0s

  [19994/21087] intraday_8906.csv.gz  in=470,192,356 out=113,089,395 elapsed=221.0s

  [19995/21087] intraday_8907.csv.gz  in=470,207,336 out=113,089,395 elapsed=221.0s

  [19996/21087] intraday_8908.csv.gz  in=470,219,115 out=113,089,395 elapsed=221.0s

  [19997/21087] intraday_8909.csv.gz  in=470,231,295 out=113,089,395 elapsed=221.0s

  [19998/21087] intraday_8911.csv.gz  in=470,242,646 out=113,089,395 elapsed=221.0s

  [19999/21087] intraday_8910.csv.gz  in=470,257,145 out=113,089,395 elapsed=221.0s

  [20000/21087] intraday_8912.csv.gz  in=470,272,386 out=113,089,395 elapsed=221.0s

  [20001/21087] intraday_8913.csv.gz  in=470,288,656 out=113,089,395 elapsed=221.0s

  [20002/21087] intraday_8915.csv.gz  in=470,302,207 out=113,089,395 elapsed=221.1s

  [20003/21087] intraday_8914.csv.gz  in=470,324,966 out=113,089,395 elapsed=221.1s

  [20004/21087] intraday_8916.csv.gz  in=470,341,700 out=113,089,395 elapsed=221.1s

  [20005/21087] intraday_8917.csv.gz  in=470,353,549 out=113,089,395 elapsed=221.1s

  [20006/21087] intraday_8918.csv.gz  in=470,366,910 out=113,089,395 elapsed=221.1s

  [20007/21087] intraday_8919.csv.gz  in=470,378,221 out=113,089,395 elapsed=221.1s

  [20008/21087] intraday_8920.csv.gz  in=470,391,534 out=113,089,395 elapsed=221.1s

  [20009/21087] intraday_8922.csv.gz  in=470,405,247 out=113,089,395 elapsed=221.1s

  [20010/21087] intraday_8921.csv.gz  in=470,416,404 out=113,089,395 elapsed=221.1s

  [20011/21087] intraday_8923.csv.gz  in=470,428,830 out=113,089,395 elapsed=221.1s

  [20012/21087] intraday_8924.csv.gz  in=470,444,830 out=113,089,395 elapsed=221.1s

  [20013/21087] intraday_8927.csv.gz  in=470,455,727 out=113,089,395 elapsed=221.2s

  [20014/21087] intraday_8925.csv.gz  in=470,466,676 out=113,089,395 elapsed=221.2s

  [20015/21087] intraday_8926.csv.gz  in=470,479,222 out=113,089,395 elapsed=221.2s

  [20016/21087] intraday_8928.csv.gz  in=470,492,389 out=113,089,395 elapsed=221.2s

  [20017/21087] intraday_8929.csv.gz  in=470,504,363 out=113,089,395 elapsed=221.2s

  [20018/21087] intraday_8930.csv.gz  in=470,518,520 out=113,089,395 elapsed=221.2s

  [20019/21087] intraday_8931.csv.gz  in=470,533,019 out=113,089,395 elapsed=221.2s

  [20020/21087] intraday_8932.csv.gz  in=470,546,363 out=113,089,395 elapsed=221.2s

  [20021/21087] intraday_8933.csv.gz  in=470,560,906 out=113,089,395 elapsed=221.2s

  [20022/21087] intraday_8934.csv.gz  in=470,573,802 out=113,089,395 elapsed=221.2s

  [20023/21087] intraday_8935.csv.gz  in=470,585,635 out=113,089,395 elapsed=221.2s

  [20024/21087] intraday_8936.csv.gz  in=470,598,732 out=113,089,395 elapsed=221.2s

  [20025/21087] intraday_8937.csv.gz  in=470,609,338 out=113,089,395 elapsed=221.2s

  [20026/21087] intraday_8939.csv.gz  in=470,616,744 out=113,089,395 elapsed=221.2s

  [20027/21087] intraday_8940.csv.gz  in=470,627,545 out=113,089,395 elapsed=221.3s

  [20028/21087] intraday_8938.csv.gz  in=470,641,295 out=113,089,395 elapsed=221.3s

  [20029/21087] intraday_8941.csv.gz  in=470,651,866 out=113,089,395 elapsed=221.3s

  [20030/21087] intraday_8942.csv.gz  in=470,654,525 out=113,089,395 elapsed=221.3s

  [20031/21087] intraday_8944.csv.gz  in=470,655,398 out=113,089,395 elapsed=221.3s

  [20032/21087] intraday_8943.csv.gz  in=470,657,695 out=113,089,395 elapsed=221.3s

  [20033/21087] intraday_8945.csv.gz  in=470,657,983 out=113,089,395 elapsed=221.3s

  [20034/21087] intraday_8946.csv.gz  in=470,658,154 out=113,089,395 elapsed=221.3s

  [20035/21087] intraday_8948.csv.gz  in=470,658,231 out=113,089,395 elapsed=221.3s

  [20036/21087] intraday_8947.csv.gz  in=470,664,742 out=113,089,395 elapsed=221.3s

  [20037/21087] intraday_8949.csv.gz  in=470,664,811 out=113,089,395 elapsed=221.3s

  [20038/21087] intraday_8950.csv.gz  in=470,665,251 out=113,089,395 elapsed=221.3s

  [20039/21087] intraday_8952.csv.gz  in=470,665,591 out=113,089,395 elapsed=221.3s

  [20040/21087] intraday_8954.csv.gz  in=470,665,601 out=113,089,395 elapsed=221.3s

  [20041/21087] intraday_8953.csv.gz  in=470,665,842 out=113,089,395 elapsed=221.3s

  [20042/21087] intraday_8951.csv.gz  in=470,679,799 out=113,089,395 elapsed=221.4s

  [20043/21087] intraday_8955.csv.gz  in=470,680,643 out=113,089,395 elapsed=221.4s

  [20044/21087] intraday_8956.csv.gz  in=470,680,711 out=113,089,395 elapsed=221.4s

  [20045/21087] intraday_8957.csv.gz  in=470,680,730 out=113,089,395 elapsed=221.4s

  [20046/21087] intraday_8958.csv.gz  in=470,680,768 out=113,089,395 elapsed=221.4s

  [20047/21087] intraday_8959.csv.gz  in=470,682,793 out=113,089,395 elapsed=221.4s

  [20048/21087] intraday_8961.csv.gz  in=470,683,304 out=113,089,395 elapsed=221.4s

  [20049/21087] intraday_8960.csv.gz  in=470,686,834 out=113,089,395 elapsed=221.4s

  [20050/21087] intraday_8964.csv.gz  in=470,686,847 out=113,089,395 elapsed=221.4s

  [20051/21087] intraday_8962.csv.gz  in=470,691,612 out=113,089,395 elapsed=221.4s

  [20052/21087] intraday_8963.csv.gz  in=470,691,817 out=113,089,395 elapsed=221.4s

  [20053/21087] intraday_8965.csv.gz  in=470,695,579 out=113,089,395 elapsed=221.4s

  [20054/21087] intraday_8966.csv.gz  in=470,695,884 out=113,089,395 elapsed=221.4s

  [20055/21087] intraday_8969.csv.gz  in=470,695,915 out=113,089,395 elapsed=221.4s

  [20056/21087] intraday_8967.csv.gz  in=470,699,021 out=113,089,395 elapsed=221.4s

  [20057/21087] intraday_8968.csv.gz  in=470,699,284 out=113,089,395 elapsed=221.4s

  [20058/21087] intraday_8970.csv.gz  in=470,704,067 out=113,089,395 elapsed=221.5s

  [20059/21087] intraday_8972.csv.gz  in=470,705,965 out=113,089,395 elapsed=221.5s

  [20060/21087] intraday_8973.csv.gz  in=470,721,306 out=113,089,395 elapsed=221.5s

  [20061/21087] intraday_8971.csv.gz  in=470,752,374 out=113,089,395 elapsed=221.5s

  [20062/21087] intraday_8974.csv.gz  in=470,764,117 out=113,089,395 elapsed=221.5s

  [20063/21087] intraday_8975.csv.gz  in=470,777,914 out=113,089,395 elapsed=221.5s

  [20064/21087] intraday_8976.csv.gz  in=470,788,596 out=113,089,395 elapsed=221.5s

  [20065/21087] intraday_8977.csv.gz  in=470,801,930 out=113,089,395 elapsed=221.5s

  [20066/21087] intraday_8978.csv.gz  in=470,816,092 out=113,089,395 elapsed=221.5s

  [20067/21087] intraday_8980.csv.gz  in=470,828,618 out=113,089,395 elapsed=221.5s

  [20068/21087] intraday_8979.csv.gz  in=470,843,749 out=113,089,395 elapsed=221.5s

  [20069/21087] intraday_8981.csv.gz  in=470,856,494 out=113,089,395 elapsed=221.6s

  [20070/21087] intraday_8984.csv.gz  in=470,869,592 out=113,089,395 elapsed=221.6s

  [20071/21087] intraday_8983.csv.gz  in=470,884,086 out=113,089,395 elapsed=221.6s

  [20072/21087] intraday_8982.csv.gz  in=470,897,918 out=113,089,395 elapsed=221.6s

  [20073/21087] intraday_8987.csv.gz  in=470,907,767 out=113,089,395 elapsed=221.6s

  [20074/21087] intraday_8985.csv.gz  in=470,923,481 out=113,089,395 elapsed=221.6s

  [20075/21087] intraday_8988.csv.gz  in=470,935,171 out=113,089,395 elapsed=221.6s

  [20076/21087] intraday_8986.csv.gz  in=470,947,165 out=113,089,395 elapsed=221.6s

  [20077/21087] intraday_8989.csv.gz  in=470,960,452 out=113,089,395 elapsed=221.6s

  [20078/21087] intraday_8990.csv.gz  in=470,973,448 out=113,089,395 elapsed=221.6s

  [20079/21087] intraday_8991.csv.gz  in=470,984,065 out=113,089,395 elapsed=221.6s

  [20080/21087] intraday_8992.csv.gz  in=470,995,755 out=113,089,395 elapsed=221.6s

  [20081/21087] intraday_8993.csv.gz  in=471,007,179 out=113,089,395 elapsed=221.7s

  [20082/21087] intraday_8994.csv.gz  in=471,020,133 out=113,089,395 elapsed=221.7s

  [20083/21087] intraday_8995.csv.gz  in=471,033,937 out=113,089,395 elapsed=221.7s

  [20084/21087] intraday_8996.csv.gz  in=471,046,675 out=113,089,395 elapsed=221.7s

  [20085/21087] intraday_8997.csv.gz  in=471,060,869 out=113,089,395 elapsed=221.7s

  [20086/21087] intraday_8998.csv.gz  in=471,073,838 out=113,089,395 elapsed=221.7s

  [20087/21087] intraday_8999.csv.gz  in=471,085,621 out=113,089,395 elapsed=221.7s

  [20088/21087] intraday_9000.csv.gz  in=471,097,275 out=113,089,395 elapsed=221.7s

  [20089/21087] intraday_9001.csv.gz  in=471,109,152 out=113,089,395 elapsed=221.7s

  [20090/21087] intraday_9002.csv.gz  in=471,121,826 out=113,089,395 elapsed=221.7s

  [20091/21087] intraday_9003.csv.gz  in=471,137,966 out=113,089,395 elapsed=221.7s

  [20092/21087] intraday_9004.csv.gz  in=471,151,223 out=113,089,395 elapsed=221.7s

  [20093/21087] intraday_9005.csv.gz  in=471,162,152 out=113,089,395 elapsed=221.8s

  [20094/21087] intraday_9006.csv.gz  in=471,173,696 out=113,089,395 elapsed=221.8s

  [20095/21087] intraday_9007.csv.gz  in=471,186,172 out=113,089,395 elapsed=221.8s

  [20096/21087] intraday_9008.csv.gz  in=471,198,615 out=113,089,395 elapsed=221.8s

  [20097/21087] intraday_9009.csv.gz  in=471,210,668 out=113,089,395 elapsed=221.8s

  [20098/21087] intraday_9010.csv.gz  in=471,221,799 out=113,089,395 elapsed=221.8s

  [20099/21087] intraday_9012.csv.gz  in=471,232,655 out=113,089,395 elapsed=221.8s

  [20100/21087] intraday_9011.csv.gz  in=471,244,139 out=113,089,395 elapsed=221.8s

  [20101/21087] intraday_9013.csv.gz  in=471,256,358 out=113,089,395 elapsed=221.8s

  [20102/21087] intraday_9014.csv.gz  in=471,268,696 out=113,089,395 elapsed=221.8s

  [20103/21087] intraday_9016.csv.gz  in=471,281,443 out=113,089,395 elapsed=221.8s

  [20104/21087] intraday_9015.csv.gz  in=471,293,344 out=113,089,395 elapsed=221.8s

  [20105/21087] intraday_9017.csv.gz  in=471,307,732 out=113,089,395 elapsed=221.8s

  [20106/21087] intraday_9018.csv.gz  in=471,318,130 out=113,089,395 elapsed=221.9s

  [20107/21087] intraday_9019.csv.gz  in=471,330,204 out=113,089,395 elapsed=221.9s

  [20108/21087] intraday_9020.csv.gz  in=471,342,723 out=113,089,395 elapsed=221.9s

  [20109/21087] intraday_9021.csv.gz  in=471,354,173 out=113,089,395 elapsed=221.9s

  [20110/21087] intraday_9022.csv.gz  in=471,366,411 out=113,089,395 elapsed=221.9s

  [20111/21087] intraday_9023.csv.gz  in=471,379,527 out=113,089,395 elapsed=221.9s

  [20112/21087] intraday_9024.csv.gz  in=471,389,550 out=113,089,395 elapsed=221.9s

  [20113/21087] intraday_9026.csv.gz  in=471,400,923 out=113,089,395 elapsed=221.9s

  [20114/21087] intraday_9025.csv.gz  in=471,416,408 out=113,089,395 elapsed=221.9s

  [20115/21087] intraday_9027.csv.gz  in=471,429,237 out=113,089,395 elapsed=221.9s

  [20116/21087] intraday_9028.csv.gz  in=471,443,542 out=113,089,395 elapsed=221.9s

  [20117/21087] intraday_9029.csv.gz  in=471,455,789 out=113,089,395 elapsed=222.0s

  [20118/21087] intraday_9030.csv.gz  in=471,466,608 out=113,089,395 elapsed=222.0s

  [20119/21087] intraday_9031.csv.gz  in=471,477,285 out=113,089,395 elapsed=222.0s

  [20120/21087] intraday_9032.csv.gz  in=471,490,129 out=113,089,395 elapsed=222.0s

  [20121/21087] intraday_9033.csv.gz  in=471,503,204 out=113,089,395 elapsed=222.0s

  [20122/21087] intraday_9034.csv.gz  in=471,514,335 out=113,089,395 elapsed=222.0s

  [20123/21087] intraday_9035.csv.gz  in=471,527,290 out=113,089,395 elapsed=222.0s

  [20124/21087] intraday_9036.csv.gz  in=471,540,097 out=113,089,395 elapsed=222.0s

  [20125/21087] intraday_9037.csv.gz  in=471,550,274 out=113,089,395 elapsed=222.0s

  [20126/21087] intraday_9038.csv.gz  in=471,564,275 out=113,089,395 elapsed=222.0s

  [20127/21087] intraday_9039.csv.gz  in=471,579,053 out=113,089,395 elapsed=222.0s

  [20128/21087] intraday_9040.csv.gz  in=471,590,751 out=113,089,395 elapsed=222.0s

  [20129/21087] intraday_9041.csv.gz  in=471,604,045 out=113,089,395 elapsed=222.0s

  [20130/21087] intraday_9042.csv.gz  in=471,615,605 out=113,089,395 elapsed=222.0s

  [20131/21087] intraday_9043.csv.gz  in=471,624,968 out=113,089,395 elapsed=222.1s

  [20132/21087] intraday_9045.csv.gz  in=471,637,480 out=113,089,395 elapsed=222.1s

  [20133/21087] intraday_9044.csv.gz  in=471,650,405 out=113,089,395 elapsed=222.1s

  [20134/21087] intraday_9046.csv.gz  in=471,663,361 out=113,089,395 elapsed=222.1s

  [20135/21087] intraday_9047.csv.gz  in=471,675,868 out=113,089,395 elapsed=222.1s

  [20136/21087] intraday_9048.csv.gz  in=471,688,952 out=113,089,395 elapsed=222.1s

  [20137/21087] intraday_9049.csv.gz  in=471,700,255 out=113,089,395 elapsed=222.1s

  [20138/21087] intraday_9050.csv.gz  in=471,712,976 out=113,089,395 elapsed=222.1s

  [20139/21087] intraday_9051.csv.gz  in=471,725,837 out=113,089,395 elapsed=222.1s

  [20140/21087] intraday_9052.csv.gz  in=471,736,135 out=113,089,395 elapsed=222.1s

  [20141/21087] intraday_9053.csv.gz  in=471,748,264 out=113,089,395 elapsed=222.1s

  [20142/21087] intraday_9054.csv.gz  in=471,757,172 out=113,089,395 elapsed=222.1s

  [20143/21087] intraday_9055.csv.gz  in=471,768,736 out=113,089,395 elapsed=222.1s

  [20144/21087] intraday_9056.csv.gz  in=471,780,932 out=113,089,395 elapsed=222.2s

  [20145/21087] intraday_9057.csv.gz  in=471,797,055 out=113,089,395 elapsed=222.2s

  [20146/21087] intraday_9058.csv.gz  in=471,812,354 out=113,089,395 elapsed=222.2s

  [20147/21087] intraday_9060.csv.gz  in=471,824,886 out=113,089,395 elapsed=222.2s

  [20148/21087] intraday_9059.csv.gz  in=471,835,955 out=113,089,395 elapsed=222.2s

  [20149/21087] intraday_9062.csv.gz  in=471,848,010 out=113,089,395 elapsed=222.2s

  [20150/21087] intraday_9061.csv.gz  in=471,861,761 out=113,089,395 elapsed=222.2s

  [20151/21087] intraday_9063.csv.gz  in=471,876,212 out=113,089,395 elapsed=222.2s

  [20152/21087] intraday_9064.csv.gz  in=471,889,897 out=113,089,395 elapsed=222.2s

  [20153/21087] intraday_9065.csv.gz  in=471,901,726 out=113,089,395 elapsed=222.2s

  [20154/21087] intraday_9067.csv.gz  in=471,914,703 out=113,089,395 elapsed=222.2s

  [20155/21087] intraday_9066.csv.gz  in=471,929,368 out=113,089,395 elapsed=222.3s

  [20156/21087] intraday_9068.csv.gz  in=471,942,178 out=113,089,395 elapsed=222.3s

  [20157/21087] intraday_9069.csv.gz  in=471,955,242 out=113,089,395 elapsed=222.3s

  [20158/21087] intraday_9070.csv.gz  in=471,966,965 out=113,089,395 elapsed=222.3s

  [20159/21087] intraday_9071.csv.gz  in=471,979,263 out=113,089,395 elapsed=222.3s

  [20160/21087] intraday_9072.csv.gz  in=471,992,995 out=113,089,395 elapsed=222.3s

  [20161/21087] intraday_9073.csv.gz  in=472,004,581 out=113,089,395 elapsed=222.3s

  [20162/21087] intraday_9074.csv.gz  in=472,015,663 out=113,089,395 elapsed=222.3s

  [20163/21087] intraday_9075.csv.gz  in=472,028,156 out=113,089,395 elapsed=222.3s

  [20164/21087] intraday_9076.csv.gz  in=472,043,783 out=113,089,395 elapsed=222.3s

  [20165/21087] intraday_9078.csv.gz  in=472,055,925 out=113,089,395 elapsed=222.3s

  [20166/21087] intraday_9077.csv.gz  in=472,069,748 out=113,089,395 elapsed=222.3s

  [20167/21087] intraday_9079.csv.gz  in=472,082,047 out=113,089,395 elapsed=222.3s

  [20168/21087] intraday_9080.csv.gz  in=472,098,142 out=113,089,395 elapsed=222.4s

  [20169/21087] intraday_9082.csv.gz  in=472,111,287 out=113,089,395 elapsed=222.4s

  [20170/21087] intraday_9081.csv.gz  in=472,122,879 out=113,089,395 elapsed=222.4s

  [20171/21087] intraday_9083.csv.gz  in=472,137,665 out=113,089,395 elapsed=222.4s

  [20172/21087] intraday_9084.csv.gz  in=472,150,933 out=113,089,395 elapsed=222.4s

  [20173/21087] intraday_9085.csv.gz  in=472,160,994 out=113,089,395 elapsed=222.4s

  [20174/21087] intraday_9086.csv.gz  in=472,174,543 out=113,089,395 elapsed=222.4s

  [20175/21087] intraday_9087.csv.gz  in=472,186,369 out=113,089,395 elapsed=222.4s

  [20176/21087] intraday_9088.csv.gz  in=472,198,783 out=113,089,395 elapsed=222.4s

  [20177/21087] intraday_9089.csv.gz  in=472,217,164 out=113,089,395 elapsed=222.4s

  [20178/21087] intraday_9090.csv.gz  in=472,230,538 out=113,089,395 elapsed=222.4s

  [20179/21087] intraday_9091.csv.gz  in=472,251,052 out=113,089,395 elapsed=222.4s

  [20180/21087] intraday_9092.csv.gz  in=472,267,166 out=113,089,395 elapsed=222.5s

  [20181/21087] intraday_9093.csv.gz  in=472,280,199 out=113,089,395 elapsed=222.5s

  [20182/21087] intraday_9094.csv.gz  in=472,292,588 out=113,089,395 elapsed=222.5s

  [20183/21087] intraday_9095.csv.gz  in=472,305,525 out=113,089,395 elapsed=222.5s

  [20184/21087] intraday_9096.csv.gz  in=472,316,057 out=113,089,395 elapsed=222.5s

  [20185/21087] intraday_9098.csv.gz  in=472,325,949 out=113,089,395 elapsed=222.5s

  [20186/21087] intraday_9097.csv.gz  in=472,339,525 out=113,089,395 elapsed=222.5s

  [20187/21087] intraday_9099.csv.gz  in=472,354,413 out=113,089,395 elapsed=222.5s

  [20188/21087] intraday_9100.csv.gz  in=472,367,467 out=113,089,395 elapsed=222.5s

  [20189/21087] intraday_9101.csv.gz  in=472,382,588 out=113,089,395 elapsed=222.5s

  [20190/21087] intraday_9102.csv.gz  in=472,393,727 out=113,089,395 elapsed=222.5s

  [20191/21087] intraday_9103.csv.gz  in=472,405,864 out=113,089,395 elapsed=222.5s

  [20192/21087] intraday_9104.csv.gz  in=472,418,585 out=113,089,395 elapsed=222.5s

  [20193/21087] intraday_9105.csv.gz  in=472,429,972 out=113,089,395 elapsed=222.6s

  [20194/21087] intraday_9106.csv.gz  in=472,442,292 out=113,089,395 elapsed=222.6s

  [20195/21087] intraday_9107.csv.gz  in=472,456,376 out=113,089,395 elapsed=222.6s

  [20196/21087] intraday_9108.csv.gz  in=472,472,003 out=113,089,395 elapsed=222.6s

  [20197/21087] intraday_9109.csv.gz  in=472,484,868 out=113,089,395 elapsed=222.6s

  [20198/21087] intraday_9110.csv.gz  in=472,498,939 out=113,089,395 elapsed=222.6s

  [20199/21087] intraday_9111.csv.gz  in=472,511,593 out=113,089,395 elapsed=222.6s

  [20200/21087] intraday_9112.csv.gz  in=472,525,333 out=113,089,395 elapsed=222.6s

  [20201/21087] intraday_9113.csv.gz  in=472,538,450 out=113,089,395 elapsed=222.6s

  [20202/21087] intraday_9114.csv.gz  in=472,549,387 out=113,089,395 elapsed=222.6s

  [20203/21087] intraday_9115.csv.gz  in=472,560,952 out=113,089,395 elapsed=222.6s

  [20204/21087] intraday_9116.csv.gz  in=472,568,147 out=113,089,395 elapsed=222.6s

  [20205/21087] intraday_9117.csv.gz  in=472,579,351 out=113,089,395 elapsed=222.6s

  [20206/21087] intraday_9118.csv.gz  in=472,585,123 out=113,089,395 elapsed=222.7s

  [20207/21087] intraday_9120.csv.gz  in=472,601,041 out=113,089,395 elapsed=222.7s

  [20208/21087] intraday_9119.csv.gz  in=472,626,313 out=113,089,395 elapsed=222.7s

  [20209/21087] intraday_9121.csv.gz  in=472,638,649 out=113,089,395 elapsed=222.7s

  [20210/21087] intraday_9122.csv.gz  in=472,651,915 out=113,089,395 elapsed=222.7s

  [20211/21087] intraday_9123.csv.gz  in=472,661,826 out=113,089,395 elapsed=222.7s

  [20212/21087] intraday_9124.csv.gz  in=472,674,336 out=113,089,395 elapsed=222.7s

  [20213/21087] intraday_9125.csv.gz  in=472,689,813 out=113,089,395 elapsed=222.7s

  [20214/21087] intraday_9126.csv.gz  in=472,704,880 out=113,089,395 elapsed=222.7s

  [20215/21087] intraday_9127.csv.gz  in=472,716,862 out=113,089,395 elapsed=222.7s

  [20216/21087] intraday_9128.csv.gz  in=472,729,456 out=113,089,395 elapsed=222.7s

  [20217/21087] intraday_9129.csv.gz  in=472,744,165 out=113,089,395 elapsed=222.7s

  [20218/21087] intraday_9130.csv.gz  in=472,759,119 out=113,089,395 elapsed=222.8s

  [20219/21087] intraday_9131.csv.gz  in=472,771,613 out=113,089,395 elapsed=222.8s

  [20220/21087] intraday_9132.csv.gz  in=472,785,638 out=113,089,395 elapsed=222.8s

  [20221/21087] intraday_9133.csv.gz  in=472,800,036 out=113,089,395 elapsed=222.8s

  [20222/21087] intraday_9134.csv.gz  in=472,809,267 out=113,089,395 elapsed=222.8s

  [20223/21087] intraday_9135.csv.gz  in=472,821,122 out=113,089,395 elapsed=222.8s

  [20224/21087] intraday_9136.csv.gz  in=472,835,631 out=113,089,395 elapsed=222.8s

  [20225/21087] intraday_9137.csv.gz  in=472,848,738 out=113,089,395 elapsed=222.8s

  [20226/21087] intraday_9138.csv.gz  in=472,860,877 out=113,089,395 elapsed=222.8s

  [20227/21087] intraday_9139.csv.gz  in=472,871,280 out=113,089,395 elapsed=222.8s

  [20228/21087] intraday_9140.csv.gz  in=472,882,668 out=113,089,395 elapsed=222.8s

  [20229/21087] intraday_9141.csv.gz  in=472,896,280 out=113,089,395 elapsed=222.8s

  [20230/21087] intraday_9143.csv.gz  in=472,910,084 out=113,089,395 elapsed=222.8s

  [20231/21087] intraday_9142.csv.gz  in=472,922,743 out=113,089,395 elapsed=222.9s

  [20232/21087] intraday_9144.csv.gz  in=472,938,401 out=113,089,395 elapsed=222.9s

  [20233/21087] intraday_9145.csv.gz  in=472,951,072 out=113,089,395 elapsed=222.9s

  [20234/21087] intraday_9146.csv.gz  in=472,963,838 out=113,089,395 elapsed=222.9s

  [20235/21087] intraday_9147.csv.gz  in=472,975,745 out=113,089,395 elapsed=222.9s

  [20236/21087] intraday_9148.csv.gz  in=472,986,824 out=113,089,395 elapsed=222.9s

  [20237/21087] intraday_9149.csv.gz  in=473,000,073 out=113,089,395 elapsed=222.9s

  [20238/21087] intraday_9150.csv.gz  in=473,016,661 out=113,089,395 elapsed=222.9s

  [20239/21087] intraday_9151.csv.gz  in=473,031,740 out=113,089,395 elapsed=222.9s

  [20240/21087] intraday_9152.csv.gz  in=473,041,412 out=113,089,395 elapsed=222.9s

  [20241/21087] intraday_9153.csv.gz  in=473,053,456 out=113,089,395 elapsed=222.9s

  [20242/21087] intraday_9154.csv.gz  in=473,066,025 out=113,089,395 elapsed=223.0s

  [20243/21087] intraday_9155.csv.gz  in=473,080,551 out=113,089,395 elapsed=223.0s

  [20244/21087] intraday_9156.csv.gz  in=473,091,740 out=113,089,395 elapsed=223.0s

  [20245/21087] intraday_9157.csv.gz  in=473,103,819 out=113,089,395 elapsed=223.0s

  [20246/21087] intraday_9158.csv.gz  in=473,120,370 out=113,089,395 elapsed=223.0s

  [20247/21087] intraday_9159.csv.gz  in=473,130,938 out=113,089,395 elapsed=223.0s

  [20248/21087] intraday_9161.csv.gz  in=473,144,450 out=113,089,395 elapsed=223.0s

  [20249/21087] intraday_9160.csv.gz  in=473,157,780 out=113,089,395 elapsed=223.0s

  [20250/21087] intraday_9162.csv.gz  in=473,169,314 out=113,089,395 elapsed=223.0s

  [20251/21087] intraday_9163.csv.gz  in=473,182,107 out=113,089,395 elapsed=223.0s

  [20252/21087] intraday_9165.csv.gz  in=473,194,688 out=113,089,395 elapsed=223.0s

  [20253/21087] intraday_9164.csv.gz  in=473,208,749 out=113,089,395 elapsed=223.0s

  [20254/21087] intraday_9166.csv.gz  in=473,221,487 out=113,089,395 elapsed=223.1s

  [20255/21087] intraday_9167.csv.gz  in=473,232,588 out=113,089,395 elapsed=223.1s

  [20256/21087] intraday_9168.csv.gz  in=473,245,122 out=113,089,395 elapsed=223.1s

  [20257/21087] intraday_9169.csv.gz  in=473,257,737 out=113,089,395 elapsed=223.1s

  [20258/21087] intraday_9170.csv.gz  in=473,269,683 out=113,089,395 elapsed=223.1s

  [20259/21087] intraday_9171.csv.gz  in=473,280,708 out=113,089,395 elapsed=223.1s

  [20260/21087] intraday_9173.csv.gz  in=473,295,484 out=113,089,395 elapsed=223.1s

  [20261/21087] intraday_9172.csv.gz  in=473,308,533 out=113,089,395 elapsed=223.1s

  [20262/21087] intraday_9174.csv.gz  in=473,322,225 out=113,089,395 elapsed=223.1s

  [20263/21087] intraday_9175.csv.gz  in=473,335,444 out=113,089,395 elapsed=223.1s

  [20264/21087] intraday_9177.csv.gz  in=473,347,307 out=113,089,395 elapsed=223.1s

  [20265/21087] intraday_9176.csv.gz  in=473,359,990 out=113,089,395 elapsed=223.2s

  [20266/21087] intraday_9178.csv.gz  in=473,369,502 out=113,089,395 elapsed=223.2s

  [20267/21087] intraday_9179.csv.gz  in=473,382,885 out=113,089,395 elapsed=223.2s

  [20268/21087] intraday_9181.csv.gz  in=473,395,215 out=113,089,395 elapsed=223.2s

  [20269/21087] intraday_9180.csv.gz  in=473,408,918 out=113,089,395 elapsed=223.2s

  [20270/21087] intraday_9182.csv.gz  in=473,422,571 out=113,089,395 elapsed=223.2s

  [20271/21087] intraday_9183.csv.gz  in=473,434,288 out=113,089,395 elapsed=223.2s

  [20272/21087] intraday_9184.csv.gz  in=473,444,699 out=113,089,395 elapsed=223.2s

  [20273/21087] intraday_9185.csv.gz  in=473,458,174 out=113,089,395 elapsed=223.2s

  [20274/21087] intraday_9186.csv.gz  in=473,473,112 out=113,089,395 elapsed=223.2s

  [20275/21087] intraday_9187.csv.gz  in=473,484,855 out=113,089,395 elapsed=223.2s

  [20276/21087] intraday_9188.csv.gz  in=473,498,922 out=113,089,395 elapsed=223.2s

  [20277/21087] intraday_9189.csv.gz  in=473,511,205 out=113,089,395 elapsed=223.2s

  [20278/21087] intraday_9190.csv.gz  in=473,522,136 out=113,089,395 elapsed=223.3s

  [20279/21087] intraday_9191.csv.gz  in=473,533,909 out=113,089,395 elapsed=223.3s

  [20280/21087] intraday_9193.csv.gz  in=473,545,343 out=113,089,395 elapsed=223.3s

  [20281/21087] intraday_9192.csv.gz  in=473,558,967 out=113,089,395 elapsed=223.3s

  [20282/21087] intraday_9194.csv.gz  in=473,572,557 out=113,089,395 elapsed=223.3s

  [20283/21087] intraday_9195.csv.gz  in=473,584,309 out=113,089,395 elapsed=223.3s

  [20284/21087] intraday_9196.csv.gz  in=473,596,686 out=113,089,395 elapsed=223.3s

  [20285/21087] intraday_9197.csv.gz  in=473,607,955 out=113,089,395 elapsed=223.3s

  [20286/21087] intraday_9198.csv.gz  in=473,622,000 out=113,089,395 elapsed=223.3s

  [20287/21087] intraday_9199.csv.gz  in=473,632,996 out=113,089,395 elapsed=223.3s

  [20288/21087] intraday_9201.csv.gz  in=473,644,255 out=113,089,395 elapsed=223.3s

  [20289/21087] intraday_9200.csv.gz  in=473,656,380 out=113,089,395 elapsed=223.3s

  [20290/21087] intraday_9203.csv.gz  in=473,667,883 out=113,089,395 elapsed=223.4s

  [20291/21087] intraday_9202.csv.gz  in=473,678,823 out=113,089,395 elapsed=223.4s

  [20292/21087] intraday_9204.csv.gz  in=473,695,665 out=113,089,395 elapsed=223.4s

  [20293/21087] intraday_9205.csv.gz  in=473,711,952 out=113,089,395 elapsed=223.4s

  [20294/21087] intraday_9206.csv.gz  in=473,727,444 out=113,089,395 elapsed=223.4s

  [20295/21087] intraday_9207.csv.gz  in=473,738,073 out=113,089,395 elapsed=223.4s

  [20296/21087] intraday_9208.csv.gz  in=473,749,929 out=113,089,395 elapsed=223.4s

  [20297/21087] intraday_9209.csv.gz  in=473,764,387 out=113,089,395 elapsed=223.4s

  [20298/21087] intraday_9210.csv.gz  in=473,782,683 out=113,089,395 elapsed=223.4s

  [20299/21087] intraday_9212.csv.gz  in=473,794,810 out=113,089,395 elapsed=223.4s

  [20300/21087] intraday_9211.csv.gz  in=473,810,746 out=113,089,395 elapsed=223.4s

  [20301/21087] intraday_9213.csv.gz  in=473,824,441 out=113,089,395 elapsed=223.4s

  [20302/21087] intraday_9214.csv.gz  in=473,836,737 out=113,089,395 elapsed=223.5s

  [20303/21087] intraday_9216.csv.gz  in=473,850,513 out=113,089,395 elapsed=223.5s

  [20304/21087] intraday_9215.csv.gz  in=473,865,225 out=113,089,395 elapsed=223.5s

  [20305/21087] intraday_9217.csv.gz  in=473,876,448 out=113,089,395 elapsed=223.5s

  [20306/21087] intraday_9218.csv.gz  in=473,889,301 out=113,089,395 elapsed=223.5s

  [20307/21087] intraday_9219.csv.gz  in=473,900,869 out=113,089,395 elapsed=223.5s

  [20308/21087] intraday_9220.csv.gz  in=473,913,618 out=113,089,395 elapsed=223.5s

  [20309/21087] intraday_9221.csv.gz  in=473,926,395 out=113,089,395 elapsed=223.5s

  [20310/21087] intraday_9222.csv.gz  in=473,938,065 out=113,089,395 elapsed=223.5s

  [20311/21087] intraday_9223.csv.gz  in=473,953,021 out=113,089,395 elapsed=223.5s

  [20312/21087] intraday_9224.csv.gz  in=473,968,748 out=113,089,395 elapsed=223.5s

  [20313/21087] intraday_9225.csv.gz  in=473,981,364 out=113,089,395 elapsed=223.5s

  [20314/21087] intraday_9226.csv.gz  in=473,994,200 out=113,089,395 elapsed=223.6s

  [20315/21087] intraday_9227.csv.gz  in=474,007,397 out=113,089,395 elapsed=223.6s

  [20316/21087] intraday_9228.csv.gz  in=474,020,955 out=113,089,395 elapsed=223.6s

  [20317/21087] intraday_9229.csv.gz  in=474,034,045 out=113,089,395 elapsed=223.6s

  [20318/21087] intraday_9230.csv.gz  in=474,048,027 out=113,089,395 elapsed=223.6s

  [20319/21087] intraday_9231.csv.gz  in=474,063,268 out=113,089,395 elapsed=223.6s

  [20320/21087] intraday_9232.csv.gz  in=474,075,064 out=113,089,395 elapsed=223.6s

  [20321/21087] intraday_9233.csv.gz  in=474,086,094 out=113,089,395 elapsed=223.6s

  [20322/21087] intraday_9234.csv.gz  in=474,100,779 out=113,089,395 elapsed=223.6s

  [20323/21087] intraday_9235.csv.gz  in=474,111,851 out=113,089,395 elapsed=223.6s

  [20324/21087] intraday_9236.csv.gz  in=474,128,150 out=113,089,395 elapsed=223.6s

  [20325/21087] intraday_9237.csv.gz  in=474,143,500 out=113,089,395 elapsed=223.6s

  [20326/21087] intraday_9238.csv.gz  in=474,164,003 out=113,089,395 elapsed=223.6s

  [20327/21087] intraday_9239.csv.gz  in=474,176,893 out=113,089,395 elapsed=223.6s

  [20328/21087] intraday_9240.csv.gz  in=474,193,874 out=113,089,395 elapsed=223.7s

  [20329/21087] intraday_9241.csv.gz  in=474,210,418 out=113,089,395 elapsed=223.7s

  [20330/21087] intraday_9242.csv.gz  in=474,224,692 out=113,089,395 elapsed=223.7s

  [20331/21087] intraday_9243.csv.gz  in=474,235,965 out=113,089,395 elapsed=223.7s

  [20332/21087] intraday_9244.csv.gz  in=474,249,197 out=113,089,395 elapsed=223.7s

  [20333/21087] intraday_9245.csv.gz  in=474,261,249 out=113,089,395 elapsed=223.7s

  [20334/21087] intraday_9246.csv.gz  in=474,274,303 out=113,089,395 elapsed=223.7s

  [20335/21087] intraday_9247.csv.gz  in=474,288,321 out=113,089,395 elapsed=223.7s

  [20336/21087] intraday_9248.csv.gz  in=474,305,168 out=113,089,395 elapsed=223.7s

  [20337/21087] intraday_9249.csv.gz  in=474,316,515 out=113,089,395 elapsed=223.7s

  [20338/21087] intraday_9250.csv.gz  in=474,328,497 out=113,089,395 elapsed=223.7s

  [20339/21087] intraday_9251.csv.gz  in=474,340,247 out=113,089,395 elapsed=223.7s

  [20340/21087] intraday_9252.csv.gz  in=474,352,693 out=113,089,395 elapsed=223.8s

  [20341/21087] intraday_9253.csv.gz  in=474,364,815 out=113,089,395 elapsed=223.8s

  [20342/21087] intraday_9254.csv.gz  in=474,377,711 out=113,089,395 elapsed=223.8s

  [20343/21087] intraday_9255.csv.gz  in=474,392,911 out=113,089,395 elapsed=223.8s

  [20344/21087] intraday_9256.csv.gz  in=474,406,345 out=113,089,395 elapsed=223.8s

  [20345/21087] intraday_9257.csv.gz  in=474,422,689 out=113,089,395 elapsed=223.8s

  [20346/21087] intraday_9258.csv.gz  in=474,436,118 out=113,089,395 elapsed=223.8s

  [20347/21087] intraday_9259.csv.gz  in=474,447,069 out=113,089,395 elapsed=223.8s

  [20348/21087] intraday_9260.csv.gz  in=474,461,252 out=113,089,395 elapsed=223.8s

  [20349/21087] intraday_9261.csv.gz  in=474,472,038 out=113,089,395 elapsed=223.8s

  [20350/21087] intraday_9263.csv.gz  in=474,480,179 out=113,089,395 elapsed=223.8s

  [20351/21087] intraday_9262.csv.gz  in=474,494,202 out=113,089,395 elapsed=223.8s

  [20352/21087] intraday_9264.csv.gz  in=474,502,615 out=113,089,395 elapsed=223.8s

  [20353/21087] intraday_9266.csv.gz  in=474,503,897 out=113,089,395 elapsed=223.9s

  [20354/21087] intraday_9265.csv.gz  in=474,516,513 out=113,089,395 elapsed=223.9s

  [20355/21087] intraday_9268.csv.gz  in=474,532,457 out=113,089,395 elapsed=223.9s

  [20356/21087] intraday_9269.csv.gz  in=474,545,370 out=113,089,395 elapsed=223.9s

  [20357/21087] intraday_9270.csv.gz  in=474,557,975 out=113,089,395 elapsed=223.9s

  [20358/21087] intraday_9271.csv.gz  in=474,568,660 out=113,089,395 elapsed=223.9s

  [20359/21087] intraday_9267.csv.gz  in=474,627,935 out=113,089,395 elapsed=223.9s

  [20360/21087] intraday_9272.csv.gz  in=474,640,894 out=113,089,395 elapsed=223.9s

  [20361/21087] intraday_9273.csv.gz  in=474,655,677 out=113,089,395 elapsed=223.9s

  [20362/21087] intraday_9274.csv.gz  in=474,670,419 out=113,089,395 elapsed=223.9s

  [20363/21087] intraday_9275.csv.gz  in=474,683,474 out=113,089,395 elapsed=223.9s

  [20364/21087] intraday_9276.csv.gz  in=474,695,733 out=113,089,395 elapsed=224.0s

  [20365/21087] intraday_9277.csv.gz  in=474,710,269 out=113,089,395 elapsed=224.0s

  [20366/21087] intraday_9278.csv.gz  in=474,724,796 out=113,089,395 elapsed=224.0s

  [20367/21087] intraday_9279.csv.gz  in=474,738,248 out=113,089,395 elapsed=224.0s

  [20368/21087] intraday_9280.csv.gz  in=474,751,833 out=113,089,395 elapsed=224.0s

  [20369/21087] intraday_9281.csv.gz  in=474,765,882 out=113,089,395 elapsed=224.0s

  [20370/21087] intraday_9282.csv.gz  in=474,776,339 out=113,089,395 elapsed=224.0s

  [20371/21087] intraday_9283.csv.gz  in=474,786,877 out=113,089,395 elapsed=224.0s

  [20372/21087] intraday_9284.csv.gz  in=474,800,440 out=113,089,395 elapsed=224.0s

  [20373/21087] intraday_9285.csv.gz  in=474,813,742 out=113,089,395 elapsed=224.0s

  [20374/21087] intraday_9287.csv.gz  in=474,825,032 out=113,089,395 elapsed=224.0s

  [20375/21087] intraday_9286.csv.gz  in=474,837,914 out=113,089,395 elapsed=224.0s

  [20376/21087] intraday_9288.csv.gz  in=474,849,353 out=113,089,395 elapsed=224.0s

  [20377/21087] intraday_9289.csv.gz  in=474,863,083 out=113,089,395 elapsed=224.1s

  [20378/21087] intraday_9290.csv.gz  in=474,875,890 out=113,089,395 elapsed=224.1s

  [20379/21087] intraday_9291.csv.gz  in=474,890,126 out=113,089,395 elapsed=224.1s

  [20380/21087] intraday_9292.csv.gz  in=474,904,097 out=113,089,395 elapsed=224.1s

  [20381/21087] intraday_9293.csv.gz  in=474,916,753 out=113,089,395 elapsed=224.1s

  [20382/21087] intraday_9294.csv.gz  in=474,929,542 out=113,089,395 elapsed=224.1s

  [20383/21087] intraday_9296.csv.gz  in=474,940,905 out=113,089,395 elapsed=224.1s

  [20384/21087] intraday_9295.csv.gz  in=474,952,933 out=113,089,395 elapsed=224.1s

  [20385/21087] intraday_9297.csv.gz  in=474,966,407 out=113,089,395 elapsed=224.1s

  [20386/21087] intraday_9298.csv.gz  in=474,981,919 out=113,089,395 elapsed=224.1s

  [20387/21087] intraday_9300.csv.gz  in=474,993,110 out=113,089,395 elapsed=224.2s

  [20388/21087] intraday_9299.csv.gz  in=475,006,698 out=113,089,395 elapsed=224.2s

  [20389/21087] intraday_9301.csv.gz  in=475,018,939 out=113,089,395 elapsed=224.2s

  [20390/21087] intraday_9302.csv.gz  in=475,031,984 out=113,089,395 elapsed=224.2s

  [20391/21087] intraday_9303.csv.gz  in=475,043,815 out=113,089,395 elapsed=224.2s

  [20392/21087] intraday_9304.csv.gz  in=475,055,855 out=113,089,395 elapsed=224.2s

  [20393/21087] intraday_9305.csv.gz  in=475,067,568 out=113,089,395 elapsed=224.2s

  [20394/21087] intraday_9306.csv.gz  in=475,079,815 out=113,089,395 elapsed=224.2s

  [20395/21087] intraday_9307.csv.gz  in=475,090,849 out=113,089,395 elapsed=224.2s

  [20396/21087] intraday_9308.csv.gz  in=475,102,954 out=113,089,395 elapsed=224.2s

  [20397/21087] intraday_9309.csv.gz  in=475,115,798 out=113,089,395 elapsed=224.2s

  [20398/21087] intraday_9310.csv.gz  in=475,129,285 out=113,089,395 elapsed=224.2s

  [20399/21087] intraday_9311.csv.gz  in=475,142,908 out=113,089,395 elapsed=224.2s

  [20400/21087] intraday_9312.csv.gz  in=475,156,578 out=113,089,395 elapsed=224.3s

  [20401/21087] intraday_9313.csv.gz  in=475,167,823 out=113,089,395 elapsed=224.3s

  [20402/21087] intraday_9314.csv.gz  in=475,180,097 out=113,089,395 elapsed=224.3s

  [20403/21087] intraday_9315.csv.gz  in=475,193,419 out=113,089,395 elapsed=224.3s

  [20404/21087] intraday_9316.csv.gz  in=475,204,885 out=113,089,395 elapsed=224.3s

  [20405/21087] intraday_9317.csv.gz  in=475,217,458 out=113,089,395 elapsed=224.3s

  [20406/21087] intraday_9318.csv.gz  in=475,229,035 out=113,089,395 elapsed=224.3s

  [20407/21087] intraday_9319.csv.gz  in=475,239,780 out=113,089,395 elapsed=224.3s

  [20408/21087] intraday_9320.csv.gz  in=475,257,093 out=113,089,395 elapsed=224.3s

  [20409/21087] intraday_9321.csv.gz  in=475,268,646 out=113,089,395 elapsed=224.3s

  [20410/21087] intraday_9322.csv.gz  in=475,281,569 out=113,089,395 elapsed=224.3s

  [20411/21087] intraday_9323.csv.gz  in=475,294,483 out=113,089,395 elapsed=224.4s

  [20412/21087] intraday_9324.csv.gz  in=475,307,400 out=113,089,395 elapsed=224.4s

  [20413/21087] intraday_9325.csv.gz  in=475,318,899 out=113,089,395 elapsed=224.4s

  [20414/21087] intraday_9326.csv.gz  in=475,330,275 out=113,089,395 elapsed=224.4s

  [20415/21087] intraday_9328.csv.gz  in=475,343,338 out=113,089,395 elapsed=224.4s

  [20416/21087] intraday_9327.csv.gz  in=475,356,859 out=113,089,395 elapsed=224.4s

  [20417/21087] intraday_9329.csv.gz  in=475,368,484 out=113,089,395 elapsed=224.4s

  [20418/21087] intraday_9330.csv.gz  in=475,381,958 out=113,089,395 elapsed=224.4s

  [20419/21087] intraday_9331.csv.gz  in=475,394,189 out=113,089,395 elapsed=224.4s

  [20420/21087] intraday_9332.csv.gz  in=475,404,802 out=113,089,395 elapsed=224.4s

  [20421/21087] intraday_9333.csv.gz  in=475,419,925 out=113,089,395 elapsed=224.4s

  [20422/21087] intraday_9334.csv.gz  in=475,432,919 out=113,089,395 elapsed=224.4s

  [20423/21087] intraday_9335.csv.gz  in=475,446,498 out=113,089,395 elapsed=224.4s

  [20424/21087] intraday_9336.csv.gz  in=475,459,146 out=113,089,395 elapsed=224.5s

  [20425/21087] intraday_9337.csv.gz  in=475,471,409 out=113,089,395 elapsed=224.5s

  [20426/21087] intraday_9338.csv.gz  in=475,481,644 out=113,089,395 elapsed=224.5s

  [20427/21087] intraday_9339.csv.gz  in=475,493,012 out=113,089,395 elapsed=224.5s

  [20428/21087] intraday_9340.csv.gz  in=475,506,074 out=113,089,395 elapsed=224.5s

  [20429/21087] intraday_9341.csv.gz  in=475,519,630 out=113,089,395 elapsed=224.5s

  [20430/21087] intraday_9342.csv.gz  in=475,531,751 out=113,089,395 elapsed=224.5s

  [20431/21087] intraday_9343.csv.gz  in=475,544,529 out=113,089,395 elapsed=224.5s

  [20432/21087] intraday_9344.csv.gz  in=475,555,421 out=113,089,395 elapsed=224.5s

  [20433/21087] intraday_9345.csv.gz  in=475,568,920 out=113,089,395 elapsed=224.5s

  [20434/21087] intraday_9346.csv.gz  in=475,581,025 out=113,089,395 elapsed=224.5s

  [20435/21087] intraday_9347.csv.gz  in=475,592,270 out=113,089,395 elapsed=224.5s

  [20436/21087] intraday_9348.csv.gz  in=475,604,594 out=113,089,395 elapsed=224.6s

  [20437/21087] intraday_9349.csv.gz  in=475,613,827 out=113,089,395 elapsed=224.6s

  [20438/21087] intraday_9350.csv.gz  in=475,626,455 out=113,089,395 elapsed=224.6s

  [20439/21087] intraday_9351.csv.gz  in=475,639,750 out=113,089,395 elapsed=224.6s

  [20440/21087] intraday_9352.csv.gz  in=475,654,923 out=113,089,395 elapsed=224.6s

  [20441/21087] intraday_9353.csv.gz  in=475,669,576 out=113,089,395 elapsed=224.6s

  [20442/21087] intraday_9354.csv.gz  in=475,682,312 out=113,089,395 elapsed=224.6s

  [20443/21087] intraday_9355.csv.gz  in=475,694,383 out=113,089,395 elapsed=224.6s

  [20444/21087] intraday_9356.csv.gz  in=475,708,890 out=113,089,395 elapsed=224.6s

  [20445/21087] intraday_9357.csv.gz  in=475,719,791 out=113,089,395 elapsed=224.6s

  [20446/21087] intraday_9358.csv.gz  in=475,736,547 out=113,089,395 elapsed=224.6s

  [20447/21087] intraday_9359.csv.gz  in=475,748,894 out=113,089,395 elapsed=224.6s

  [20448/21087] intraday_9360.csv.gz  in=475,762,094 out=113,089,395 elapsed=224.6s

  [20449/21087] intraday_9361.csv.gz  in=475,775,765 out=113,089,395 elapsed=224.7s

  [20450/21087] intraday_9362.csv.gz  in=475,788,524 out=113,089,395 elapsed=224.7s

  [20451/21087] intraday_9363.csv.gz  in=475,801,768 out=113,089,395 elapsed=224.7s

  [20452/21087] intraday_9364.csv.gz  in=475,814,540 out=113,089,395 elapsed=224.7s

  [20453/21087] intraday_9365.csv.gz  in=475,827,057 out=113,089,395 elapsed=224.7s

  [20454/21087] intraday_9366.csv.gz  in=475,839,743 out=113,089,395 elapsed=224.7s

  [20455/21087] intraday_9367.csv.gz  in=475,852,243 out=113,089,395 elapsed=224.7s

  [20456/21087] intraday_9368.csv.gz  in=475,865,307 out=113,089,395 elapsed=224.7s

  [20457/21087] intraday_9369.csv.gz  in=475,876,342 out=113,089,395 elapsed=224.7s

  [20458/21087] intraday_9370.csv.gz  in=475,888,836 out=113,089,395 elapsed=224.7s

  [20459/21087] intraday_9371.csv.gz  in=475,905,866 out=113,089,395 elapsed=224.7s

  [20460/21087] intraday_9372.csv.gz  in=475,918,880 out=113,089,395 elapsed=224.7s

  [20461/21087] intraday_9373.csv.gz  in=475,932,238 out=113,089,395 elapsed=224.7s

  [20462/21087] intraday_9374.csv.gz  in=475,944,311 out=113,089,395 elapsed=224.8s

  [20463/21087] intraday_9375.csv.gz  in=475,958,824 out=113,089,395 elapsed=224.8s

  [20464/21087] intraday_9376.csv.gz  in=475,971,292 out=113,089,395 elapsed=224.8s

  [20465/21087] intraday_9377.csv.gz  in=475,984,272 out=113,089,395 elapsed=224.8s

  [20466/21087] intraday_9378.csv.gz  in=475,999,162 out=113,089,395 elapsed=224.8s

  [20467/21087] intraday_9379.csv.gz  in=476,012,694 out=113,089,395 elapsed=224.8s

  [20468/21087] intraday_9380.csv.gz  in=476,023,315 out=113,089,395 elapsed=224.8s

  [20469/21087] intraday_9381.csv.gz  in=476,036,812 out=113,089,395 elapsed=224.8s

  [20470/21087] intraday_9382.csv.gz  in=476,049,621 out=113,089,395 elapsed=224.8s

  [20471/21087] intraday_9383.csv.gz  in=476,063,340 out=113,089,395 elapsed=224.8s

  [20472/21087] intraday_9384.csv.gz  in=476,079,605 out=113,089,395 elapsed=224.8s

  [20473/21087] intraday_9385.csv.gz  in=476,094,301 out=113,089,395 elapsed=224.9s

  [20474/21087] intraday_9386.csv.gz  in=476,112,349 out=113,089,395 elapsed=224.9s

  [20475/21087] intraday_9387.csv.gz  in=476,127,531 out=113,089,395 elapsed=224.9s

  [20476/21087] intraday_9388.csv.gz  in=476,139,671 out=113,089,395 elapsed=224.9s

  [20477/21087] intraday_9389.csv.gz  in=476,152,311 out=113,089,395 elapsed=224.9s

  [20478/21087] intraday_9390.csv.gz  in=476,164,867 out=113,089,395 elapsed=224.9s

  [20479/21087] intraday_9391.csv.gz  in=476,175,880 out=113,089,395 elapsed=224.9s

  [20480/21087] intraday_9392.csv.gz  in=476,189,326 out=113,089,395 elapsed=224.9s

  [20481/21087] intraday_9393.csv.gz  in=476,199,680 out=113,089,395 elapsed=224.9s

  [20482/21087] intraday_9394.csv.gz  in=476,214,289 out=113,089,395 elapsed=224.9s

  [20483/21087] intraday_9395.csv.gz  in=476,227,887 out=113,089,395 elapsed=224.9s

  [20484/21087] intraday_9396.csv.gz  in=476,242,879 out=113,089,395 elapsed=224.9s

  [20485/21087] intraday_9397.csv.gz  in=476,254,449 out=113,089,395 elapsed=224.9s

  [20486/21087] intraday_9398.csv.gz  in=476,265,212 out=113,089,395 elapsed=224.9s

  [20487/21087] intraday_9399.csv.gz  in=476,278,824 out=113,089,395 elapsed=225.0s

  [20488/21087] intraday_9400.csv.gz  in=476,290,287 out=113,089,395 elapsed=225.0s

  [20489/21087] intraday_9401.csv.gz  in=476,302,653 out=113,089,395 elapsed=225.0s

  [20490/21087] intraday_9402.csv.gz  in=476,317,525 out=113,089,395 elapsed=225.0s

  [20491/21087] intraday_9403.csv.gz  in=476,332,473 out=113,089,395 elapsed=225.0s

  [20492/21087] intraday_9404.csv.gz  in=476,345,814 out=113,089,395 elapsed=225.0s

  [20493/21087] intraday_9405.csv.gz  in=476,360,552 out=113,089,395 elapsed=225.0s

  [20494/21087] intraday_9406.csv.gz  in=476,373,154 out=113,089,395 elapsed=225.0s

  [20495/21087] intraday_9407.csv.gz  in=476,386,650 out=113,089,395 elapsed=225.0s

  [20496/21087] intraday_9408.csv.gz  in=476,398,919 out=113,089,395 elapsed=225.0s

  [20497/21087] intraday_9409.csv.gz  in=476,411,770 out=113,089,395 elapsed=225.0s

  [20498/21087] intraday_9410.csv.gz  in=476,421,503 out=113,089,395 elapsed=225.0s

  [20499/21087] intraday_9411.csv.gz  in=476,429,736 out=113,089,395 elapsed=225.1s

  [20500/21087] intraday_9413.csv.gz  in=476,434,790 out=113,089,395 elapsed=225.1s

  [20501/21087] intraday_9412.csv.gz  in=476,445,180 out=113,089,395 elapsed=225.1s

  [20502/21087] intraday_9415.csv.gz  in=476,461,264 out=113,089,395 elapsed=225.1s

  [20503/21087] intraday_9414.csv.gz  in=476,489,622 out=113,089,395 elapsed=225.1s

  [20504/21087] intraday_9416.csv.gz  in=476,502,559 out=113,089,395 elapsed=225.1s

  [20505/21087] intraday_9417.csv.gz  in=476,513,307 out=113,089,395 elapsed=225.1s

  [20506/21087] intraday_9418.csv.gz  in=476,524,079 out=113,089,395 elapsed=225.1s

  [20507/21087] intraday_9419.csv.gz  in=476,536,340 out=113,089,395 elapsed=225.1s

  [20508/21087] intraday_9420.csv.gz  in=476,551,822 out=113,089,395 elapsed=225.1s

  [20509/21087] intraday_9421.csv.gz  in=476,565,848 out=113,089,395 elapsed=225.1s

  [20510/21087] intraday_9422.csv.gz  in=476,578,251 out=113,089,395 elapsed=225.1s

  [20511/21087] intraday_9423.csv.gz  in=476,590,127 out=113,089,395 elapsed=225.2s

  [20512/21087] intraday_9424.csv.gz  in=476,604,754 out=113,089,395 elapsed=225.2s

  [20513/21087] intraday_9425.csv.gz  in=476,619,434 out=113,089,395 elapsed=225.2s

  [20514/21087] intraday_9426.csv.gz  in=476,631,177 out=113,089,395 elapsed=225.2s

  [20515/21087] intraday_9427.csv.gz  in=476,645,611 out=113,089,395 elapsed=225.2s

  [20516/21087] intraday_9428.csv.gz  in=476,659,125 out=113,089,395 elapsed=225.2s

  [20517/21087] intraday_9429.csv.gz  in=476,669,933 out=113,089,395 elapsed=225.2s

  [20518/21087] intraday_9430.csv.gz  in=476,681,242 out=113,089,395 elapsed=225.2s

  [20519/21087] intraday_9431.csv.gz  in=476,694,448 out=113,089,395 elapsed=225.2s

  [20520/21087] intraday_9432.csv.gz  in=476,706,804 out=113,089,395 elapsed=225.2s

  [20521/21087] intraday_9433.csv.gz  in=476,719,207 out=113,089,395 elapsed=225.2s

  [20522/21087] intraday_9434.csv.gz  in=476,730,555 out=113,089,395 elapsed=225.2s

  [20523/21087] intraday_9435.csv.gz  in=476,742,200 out=113,089,395 elapsed=225.2s

  [20524/21087] intraday_9436.csv.gz  in=476,754,654 out=113,089,395 elapsed=225.3s

  [20525/21087] intraday_9437.csv.gz  in=476,767,426 out=113,089,395 elapsed=225.3s

  [20526/21087] intraday_9438.csv.gz  in=476,779,691 out=113,089,395 elapsed=225.3s

  [20527/21087] intraday_9439.csv.gz  in=476,793,707 out=113,089,395 elapsed=225.3s

  [20528/21087] intraday_9440.csv.gz  in=476,805,975 out=113,089,395 elapsed=225.3s

  [20529/21087] intraday_9441.csv.gz  in=476,817,551 out=113,089,395 elapsed=225.3s

  [20530/21087] intraday_9443.csv.gz  in=476,829,154 out=113,089,395 elapsed=225.3s

  [20531/21087] intraday_9444.csv.gz  in=476,841,644 out=113,089,395 elapsed=225.3s

  [20532/21087] intraday_9442.csv.gz  in=476,853,279 out=113,089,395 elapsed=225.3s

  [20533/21087] intraday_9445.csv.gz  in=476,868,272 out=113,089,395 elapsed=225.3s

  [20534/21087] intraday_9448.csv.gz  in=476,880,095 out=113,089,395 elapsed=225.3s

  [20535/21087] intraday_9446.csv.gz  in=476,893,315 out=113,089,395 elapsed=225.3s

  [20536/21087] intraday_9447.csv.gz  in=476,903,559 out=113,089,395 elapsed=225.3s

  [20537/21087] intraday_9449.csv.gz  in=476,915,812 out=113,089,395 elapsed=225.4s

  [20538/21087] intraday_9450.csv.gz  in=476,928,424 out=113,089,395 elapsed=225.4s

  [20539/21087] intraday_9451.csv.gz  in=476,940,278 out=113,089,395 elapsed=225.4s

  [20540/21087] intraday_9452.csv.gz  in=476,952,601 out=113,089,395 elapsed=225.4s

  [20541/21087] intraday_9453.csv.gz  in=476,963,763 out=113,089,395 elapsed=225.4s

  [20542/21087] intraday_9454.csv.gz  in=476,974,373 out=113,089,395 elapsed=225.4s

  [20543/21087] intraday_9455.csv.gz  in=476,986,167 out=113,089,395 elapsed=225.4s

  [20544/21087] intraday_9456.csv.gz  in=476,998,650 out=113,089,395 elapsed=225.4s

  [20545/21087] intraday_9457.csv.gz  in=477,010,964 out=113,089,395 elapsed=225.4s

  [20546/21087] intraday_9458.csv.gz  in=477,024,234 out=113,089,395 elapsed=225.4s

  [20547/21087] intraday_9459.csv.gz  in=477,037,826 out=113,089,395 elapsed=225.4s

  [20548/21087] intraday_9460.csv.gz  in=477,049,335 out=113,089,395 elapsed=225.4s

  [20549/21087] intraday_9461.csv.gz  in=477,061,722 out=113,089,395 elapsed=225.4s

  [20550/21087] intraday_9462.csv.gz  in=477,073,648 out=113,089,395 elapsed=225.4s

  [20551/21087] intraday_9464.csv.gz  in=477,083,894 out=113,089,395 elapsed=225.5s

  [20552/21087] intraday_9463.csv.gz  in=477,097,426 out=113,089,395 elapsed=225.5s

  [20553/21087] intraday_9465.csv.gz  in=477,110,043 out=113,089,395 elapsed=225.5s

  [20554/21087] intraday_9466.csv.gz  in=477,120,990 out=113,089,395 elapsed=225.5s

  [20555/21087] intraday_9467.csv.gz  in=477,133,888 out=113,089,395 elapsed=225.5s

  [20556/21087] intraday_9469.csv.gz  in=477,147,133 out=113,089,395 elapsed=225.5s

  [20557/21087] intraday_9468.csv.gz  in=477,159,494 out=113,089,395 elapsed=225.5s

  [20558/21087] intraday_9470.csv.gz  in=477,173,741 out=113,089,395 elapsed=225.5s

  [20559/21087] intraday_9471.csv.gz  in=477,185,299 out=113,089,395 elapsed=225.5s

  [20560/21087] intraday_9472.csv.gz  in=477,196,779 out=113,089,395 elapsed=225.5s

  [20561/21087] intraday_9473.csv.gz  in=477,207,028 out=113,089,395 elapsed=225.6s

  [20562/21087] intraday_9474.csv.gz  in=477,220,042 out=113,089,395 elapsed=225.6s

  [20563/21087] intraday_9475.csv.gz  in=477,232,417 out=113,089,395 elapsed=225.6s

  [20564/21087] intraday_9476.csv.gz  in=477,244,275 out=113,089,395 elapsed=225.6s

  [20565/21087] intraday_9477.csv.gz  in=477,257,599 out=113,089,395 elapsed=225.6s

  [20566/21087] intraday_9478.csv.gz  in=477,270,622 out=113,089,395 elapsed=225.6s

  [20567/21087] intraday_9479.csv.gz  in=477,281,169 out=113,089,395 elapsed=225.6s

  [20568/21087] intraday_9480.csv.gz  in=477,295,251 out=113,089,395 elapsed=225.6s

  [20569/21087] intraday_9481.csv.gz  in=477,311,434 out=113,089,395 elapsed=225.6s

  [20570/21087] intraday_9482.csv.gz  in=477,321,933 out=113,089,395 elapsed=225.6s

  [20571/21087] intraday_9483.csv.gz  in=477,336,441 out=113,089,395 elapsed=225.6s

  [20572/21087] intraday_9484.csv.gz  in=477,347,818 out=113,089,395 elapsed=225.6s

  [20573/21087] intraday_9485.csv.gz  in=477,358,161 out=113,089,395 elapsed=225.6s

  [20574/21087] intraday_9486.csv.gz  in=477,370,643 out=113,089,395 elapsed=225.6s

  [20575/21087] intraday_9488.csv.gz  in=477,383,622 out=113,089,395 elapsed=225.7s

  [20576/21087] intraday_9487.csv.gz  in=477,396,689 out=113,089,395 elapsed=225.7s

  [20577/21087] intraday_9490.csv.gz  in=477,409,290 out=113,089,395 elapsed=225.7s

  [20578/21087] intraday_9489.csv.gz  in=477,421,853 out=113,089,395 elapsed=225.7s

  [20579/21087] intraday_9491.csv.gz  in=477,431,483 out=113,089,395 elapsed=225.7s

  [20580/21087] intraday_9492.csv.gz  in=477,443,435 out=113,089,395 elapsed=225.7s

  [20581/21087] intraday_9494.csv.gz  in=477,454,840 out=113,089,395 elapsed=225.7s

  [20582/21087] intraday_9493.csv.gz  in=477,467,973 out=113,089,395 elapsed=225.7s

  [20583/21087] intraday_9495.csv.gz  in=477,479,692 out=113,089,395 elapsed=225.7s

  [20584/21087] intraday_9496.csv.gz  in=477,490,591 out=113,089,395 elapsed=225.7s

  [20585/21087] intraday_9497.csv.gz  in=477,502,150 out=113,089,395 elapsed=225.8s

  [20586/21087] intraday_9498.csv.gz  in=477,514,555 out=113,089,395 elapsed=225.8s

  [20587/21087] intraday_9499.csv.gz  in=477,530,334 out=113,089,395 elapsed=225.8s

  [20588/21087] intraday_9500.csv.gz  in=477,546,275 out=113,089,395 elapsed=225.8s

  [20589/21087] intraday_9501.csv.gz  in=477,557,450 out=113,089,395 elapsed=225.8s

  [20590/21087] intraday_9502.csv.gz  in=477,569,960 out=113,089,395 elapsed=225.8s

  [20591/21087] intraday_9503.csv.gz  in=477,582,690 out=113,089,395 elapsed=225.8s

  [20592/21087] intraday_9504.csv.gz  in=477,595,860 out=113,089,395 elapsed=225.8s

  [20593/21087] intraday_9506.csv.gz  in=477,607,762 out=113,089,395 elapsed=225.8s

  [20594/21087] intraday_9505.csv.gz  in=477,623,380 out=113,089,395 elapsed=225.8s

  [20595/21087] intraday_9507.csv.gz  in=477,635,594 out=113,089,395 elapsed=225.8s

  [20596/21087] intraday_9508.csv.gz  in=477,649,346 out=113,089,395 elapsed=225.8s

  [20597/21087] intraday_9509.csv.gz  in=477,662,779 out=113,089,395 elapsed=225.9s

  [20598/21087] intraday_9510.csv.gz  in=477,675,780 out=113,089,395 elapsed=225.9s

  [20599/21087] intraday_9511.csv.gz  in=477,688,345 out=113,089,395 elapsed=225.9s

  [20600/21087] intraday_9512.csv.gz  in=477,701,351 out=113,089,395 elapsed=225.9s

  [20601/21087] intraday_9513.csv.gz  in=477,714,279 out=113,089,395 elapsed=225.9s

  [20602/21087] intraday_9514.csv.gz  in=477,727,657 out=113,089,395 elapsed=225.9s

  [20603/21087] intraday_9515.csv.gz  in=477,738,241 out=113,089,395 elapsed=225.9s

  [20604/21087] intraday_9516.csv.gz  in=477,750,734 out=113,089,395 elapsed=225.9s

  [20605/21087] intraday_9517.csv.gz  in=477,764,519 out=113,089,395 elapsed=225.9s

  [20606/21087] intraday_9518.csv.gz  in=477,778,942 out=113,089,395 elapsed=225.9s

  [20607/21087] intraday_9519.csv.gz  in=477,792,233 out=113,089,395 elapsed=225.9s

  [20608/21087] intraday_9520.csv.gz  in=477,804,402 out=113,089,395 elapsed=225.9s

  [20609/21087] intraday_9521.csv.gz  in=477,817,418 out=113,089,395 elapsed=225.9s

  [20610/21087] intraday_9522.csv.gz  in=477,832,662 out=113,089,395 elapsed=226.0s

  [20611/21087] intraday_9523.csv.gz  in=477,844,610 out=113,089,395 elapsed=226.0s

  [20612/21087] intraday_9524.csv.gz  in=477,856,892 out=113,089,395 elapsed=226.0s

  [20613/21087] intraday_9525.csv.gz  in=477,872,011 out=113,089,395 elapsed=226.0s

  [20614/21087] intraday_9526.csv.gz  in=477,887,007 out=113,089,395 elapsed=226.0s

  [20615/21087] intraday_9527.csv.gz  in=477,896,360 out=113,089,395 elapsed=226.0s

  [20616/21087] intraday_9528.csv.gz  in=477,909,282 out=113,089,395 elapsed=226.0s

  [20617/21087] intraday_9529.csv.gz  in=477,922,916 out=113,089,395 elapsed=226.0s

  [20618/21087] intraday_9530.csv.gz  in=477,934,882 out=113,089,395 elapsed=226.0s

  [20619/21087] intraday_9531.csv.gz  in=477,948,613 out=113,089,395 elapsed=226.0s

  [20620/21087] intraday_9532.csv.gz  in=477,964,090 out=113,089,395 elapsed=226.0s

  [20621/21087] intraday_9533.csv.gz  in=477,982,308 out=113,089,395 elapsed=226.0s

  [20622/21087] intraday_9534.csv.gz  in=477,997,827 out=113,089,395 elapsed=226.0s

  [20623/21087] intraday_9535.csv.gz  in=478,011,261 out=113,089,395 elapsed=226.0s

  [20624/21087] intraday_9536.csv.gz  in=478,023,214 out=113,089,395 elapsed=226.1s

  [20625/21087] intraday_9537.csv.gz  in=478,036,097 out=113,089,395 elapsed=226.1s

  [20626/21087] intraday_9538.csv.gz  in=478,046,215 out=113,089,395 elapsed=226.1s

  [20627/21087] intraday_9539.csv.gz  in=478,059,986 out=113,089,395 elapsed=226.1s

  [20628/21087] intraday_9540.csv.gz  in=478,070,739 out=113,089,395 elapsed=226.1s

  [20629/21087] intraday_9542.csv.gz  in=478,083,491 out=113,089,395 elapsed=226.1s

  [20630/21087] intraday_9541.csv.gz  in=478,096,756 out=113,089,395 elapsed=226.1s

  [20631/21087] intraday_9543.csv.gz  in=478,112,489 out=113,089,395 elapsed=226.1s

  [20632/21087] intraday_9544.csv.gz  in=478,123,523 out=113,089,395 elapsed=226.1s

  [20633/21087] intraday_9545.csv.gz  in=478,135,750 out=113,089,395 elapsed=226.1s

  [20634/21087] intraday_9548.csv.gz  in=478,147,008 out=113,089,395 elapsed=226.2s

  [20635/21087] intraday_9547.csv.gz  in=478,159,424 out=113,089,395 elapsed=226.2s

  [20636/21087] intraday_9546.csv.gz  in=478,170,927 out=113,089,395 elapsed=226.2s

  [20637/21087] intraday_9549.csv.gz  in=478,184,456 out=113,089,395 elapsed=226.2s

  [20638/21087] intraday_9550.csv.gz  in=478,199,477 out=113,089,395 elapsed=226.2s

  [20639/21087] intraday_9551.csv.gz  in=478,213,292 out=113,089,395 elapsed=226.2s

  [20640/21087] intraday_9553.csv.gz  in=478,226,199 out=113,089,395 elapsed=226.2s

  [20641/21087] intraday_9552.csv.gz  in=478,241,139 out=113,089,395 elapsed=226.2s

  [20642/21087] intraday_9554.csv.gz  in=478,252,994 out=113,089,395 elapsed=226.2s

  [20643/21087] intraday_9556.csv.gz  in=478,264,825 out=113,089,395 elapsed=226.3s

  [20644/21087] intraday_9557.csv.gz  in=478,278,527 out=113,089,395 elapsed=226.3s

  [20645/21087] intraday_9555.csv.gz  in=478,291,927 out=113,089,395 elapsed=226.3s

  [20646/21087] intraday_9558.csv.gz  in=478,299,310 out=113,089,395 elapsed=226.3s

  [20647/21087] intraday_9559.csv.gz  in=478,308,853 out=113,089,395 elapsed=226.3s

  [20648/21087] intraday_9560.csv.gz  in=478,319,818 out=113,089,395 elapsed=226.3s

  [20649/21087] intraday_9562.csv.gz  in=478,331,884 out=113,089,395 elapsed=226.3s

  [20650/21087] intraday_9561.csv.gz  in=478,348,361 out=113,089,395 elapsed=226.3s

  [20651/21087] intraday_9563.csv.gz  in=478,360,911 out=113,089,395 elapsed=226.3s

  [20652/21087] intraday_9564.csv.gz  in=478,370,953 out=113,089,395 elapsed=226.3s

  [20653/21087] intraday_9565.csv.gz  in=478,383,529 out=113,089,395 elapsed=226.3s

  [20654/21087] intraday_9566.csv.gz  in=478,397,054 out=113,089,395 elapsed=226.4s

  [20655/21087] intraday_9567.csv.gz  in=478,411,786 out=113,089,395 elapsed=226.4s

  [20656/21087] intraday_9569.csv.gz  in=478,424,253 out=113,089,395 elapsed=226.4s

  [20657/21087] intraday_9568.csv.gz  in=478,436,664 out=113,089,395 elapsed=226.4s

  [20658/21087] intraday_9570.csv.gz  in=478,451,065 out=113,089,395 elapsed=226.4s

  [20659/21087] intraday_9571.csv.gz  in=478,464,538 out=113,089,395 elapsed=226.4s

  [20660/21087] intraday_9572.csv.gz  in=478,477,680 out=113,089,395 elapsed=226.4s

  [20661/21087] intraday_9573.csv.gz  in=478,491,183 out=113,089,395 elapsed=226.4s

  [20662/21087] intraday_9575.csv.gz  in=478,501,708 out=113,089,395 elapsed=226.4s

  [20663/21087] intraday_9574.csv.gz  in=478,516,216 out=113,089,395 elapsed=226.4s

  [20664/21087] intraday_9576.csv.gz  in=478,527,315 out=113,089,395 elapsed=226.4s

  [20665/21087] intraday_9577.csv.gz  in=478,540,655 out=113,089,395 elapsed=226.4s

  [20666/21087] intraday_9578.csv.gz  in=478,553,383 out=113,089,395 elapsed=226.5s

  [20667/21087] intraday_9580.csv.gz  in=478,564,226 out=113,089,395 elapsed=226.5s

  [20668/21087] intraday_9579.csv.gz  in=478,576,182 out=113,089,395 elapsed=226.5s

  [20669/21087] intraday_9581.csv.gz  in=478,587,881 out=113,089,395 elapsed=226.5s

  [20670/21087] intraday_9582.csv.gz  in=478,602,693 out=113,089,395 elapsed=226.5s

  [20671/21087] intraday_9583.csv.gz  in=478,615,969 out=113,089,395 elapsed=226.5s

  [20672/21087] intraday_9584.csv.gz  in=478,628,195 out=113,089,395 elapsed=226.5s

  [20673/21087] intraday_9585.csv.gz  in=478,640,967 out=113,089,395 elapsed=226.5s

  [20674/21087] intraday_9586.csv.gz  in=478,653,102 out=113,089,395 elapsed=226.5s

  [20675/21087] intraday_9587.csv.gz  in=478,669,903 out=113,089,395 elapsed=226.5s

  [20676/21087] intraday_9588.csv.gz  in=478,686,108 out=113,089,395 elapsed=226.6s

  [20677/21087] intraday_9589.csv.gz  in=478,698,600 out=113,089,395 elapsed=226.6s

  [20678/21087] intraday_9590.csv.gz  in=478,710,531 out=113,089,395 elapsed=226.6s

  [20679/21087] intraday_9591.csv.gz  in=478,725,924 out=113,089,395 elapsed=226.6s

  [20680/21087] intraday_9593.csv.gz  in=478,736,179 out=113,089,395 elapsed=226.6s

  [20681/21087] intraday_9592.csv.gz  in=478,749,471 out=113,089,395 elapsed=226.6s

  [20682/21087] intraday_9594.csv.gz  in=478,759,837 out=113,089,395 elapsed=226.6s

  [20683/21087] intraday_9595.csv.gz  in=478,773,445 out=113,089,395 elapsed=226.6s

  [20684/21087] intraday_9596.csv.gz  in=478,785,442 out=113,089,395 elapsed=226.6s

  [20685/21087] intraday_9597.csv.gz  in=478,797,515 out=113,089,395 elapsed=226.6s

  [20686/21087] intraday_9598.csv.gz  in=478,813,358 out=113,089,395 elapsed=226.6s

  [20687/21087] intraday_9599.csv.gz  in=478,824,384 out=113,089,395 elapsed=226.6s

  [20688/21087] intraday_9600.csv.gz  in=478,835,873 out=113,089,395 elapsed=226.7s

  [20689/21087] intraday_9601.csv.gz  in=478,847,438 out=113,089,395 elapsed=226.7s

  [20690/21087] intraday_9602.csv.gz  in=478,861,208 out=113,089,395 elapsed=226.7s

  [20691/21087] intraday_9603.csv.gz  in=478,873,563 out=113,089,395 elapsed=226.7s

  [20692/21087] intraday_9604.csv.gz  in=478,886,752 out=113,089,395 elapsed=226.7s

  [20693/21087] intraday_9605.csv.gz  in=478,902,332 out=113,089,395 elapsed=226.7s

  [20694/21087] intraday_9606.csv.gz  in=478,918,501 out=113,089,395 elapsed=226.7s

  [20695/21087] intraday_9607.csv.gz  in=478,933,086 out=113,089,395 elapsed=226.7s

  [20696/21087] intraday_9608.csv.gz  in=478,944,467 out=113,089,395 elapsed=226.7s

  [20697/21087] intraday_9610.csv.gz  in=478,954,448 out=113,089,395 elapsed=226.7s

  [20698/21087] intraday_9609.csv.gz  in=478,966,543 out=113,089,395 elapsed=226.7s

  [20699/21087] intraday_9611.csv.gz  in=478,978,565 out=113,089,395 elapsed=226.7s

  [20700/21087] intraday_9612.csv.gz  in=478,990,995 out=113,089,395 elapsed=226.8s

  [20701/21087] intraday_9613.csv.gz  in=479,002,320 out=113,089,395 elapsed=226.8s

  [20702/21087] intraday_9614.csv.gz  in=479,015,507 out=113,089,395 elapsed=226.8s

  [20703/21087] intraday_9615.csv.gz  in=479,027,657 out=113,089,395 elapsed=226.8s

  [20704/21087] intraday_9616.csv.gz  in=479,039,388 out=113,089,395 elapsed=226.8s

  [20705/21087] intraday_9617.csv.gz  in=479,052,584 out=113,089,395 elapsed=226.8s

  [20706/21087] intraday_9619.csv.gz  in=479,063,807 out=113,089,395 elapsed=226.8s

  [20707/21087] intraday_9618.csv.gz  in=479,075,409 out=113,089,395 elapsed=226.8s

  [20708/21087] intraday_9620.csv.gz  in=479,088,439 out=113,089,395 elapsed=226.8s

  [20709/21087] intraday_9621.csv.gz  in=479,101,214 out=113,089,395 elapsed=226.8s

  [20710/21087] intraday_9622.csv.gz  in=479,118,317 out=113,089,395 elapsed=226.8s

  [20711/21087] intraday_9623.csv.gz  in=479,130,891 out=113,089,395 elapsed=226.8s

  [20712/21087] intraday_9624.csv.gz  in=479,142,540 out=113,089,395 elapsed=226.8s

  [20713/21087] intraday_9625.csv.gz  in=479,154,801 out=113,089,395 elapsed=226.9s

  [20714/21087] intraday_9626.csv.gz  in=479,166,498 out=113,089,395 elapsed=226.9s

  [20715/21087] intraday_9628.csv.gz  in=479,179,972 out=113,089,395 elapsed=226.9s

  [20716/21087] intraday_9627.csv.gz  in=479,195,162 out=113,089,395 elapsed=226.9s

  [20717/21087] intraday_9629.csv.gz  in=479,209,682 out=113,089,395 elapsed=226.9s

  [20718/21087] intraday_9631.csv.gz  in=479,220,790 out=113,089,395 elapsed=226.9s

  [20719/21087] intraday_9630.csv.gz  in=479,242,728 out=113,089,395 elapsed=226.9s

  [20720/21087] intraday_9632.csv.gz  in=479,253,719 out=113,089,395 elapsed=226.9s

  [20721/21087] intraday_9633.csv.gz  in=479,265,846 out=113,089,395 elapsed=226.9s

  [20722/21087] intraday_9634.csv.gz  in=479,278,478 out=113,089,395 elapsed=226.9s

  [20723/21087] intraday_9636.csv.gz  in=479,290,999 out=113,089,395 elapsed=226.9s

  [20724/21087] intraday_9635.csv.gz  in=479,306,260 out=113,089,395 elapsed=226.9s

  [20725/21087] intraday_9637.csv.gz  in=479,317,587 out=113,089,395 elapsed=227.0s

  [20726/21087] intraday_9638.csv.gz  in=479,328,602 out=113,089,395 elapsed=227.0s

  [20727/21087] intraday_9639.csv.gz  in=479,341,501 out=113,089,395 elapsed=227.0s

  [20728/21087] intraday_9640.csv.gz  in=479,353,389 out=113,089,395 elapsed=227.0s

  [20729/21087] intraday_9641.csv.gz  in=479,365,916 out=113,089,395 elapsed=227.0s

  [20730/21087] intraday_9642.csv.gz  in=479,375,994 out=113,089,395 elapsed=227.0s

  [20731/21087] intraday_9644.csv.gz  in=479,387,268 out=113,089,395 elapsed=227.0s

  [20732/21087] intraday_9643.csv.gz  in=479,397,837 out=113,089,395 elapsed=227.0s

  [20733/21087] intraday_9645.csv.gz  in=479,415,769 out=113,089,395 elapsed=227.0s

  [20734/21087] intraday_9646.csv.gz  in=479,431,991 out=113,089,395 elapsed=227.0s

  [20735/21087] intraday_9647.csv.gz  in=479,444,176 out=113,089,395 elapsed=227.0s

  [20736/21087] intraday_9648.csv.gz  in=479,455,525 out=113,089,395 elapsed=227.0s

  [20737/21087] intraday_9649.csv.gz  in=479,467,617 out=113,089,395 elapsed=227.1s

  [20738/21087] intraday_9650.csv.gz  in=479,482,446 out=113,089,395 elapsed=227.1s

  [20739/21087] intraday_9651.csv.gz  in=479,494,648 out=113,089,395 elapsed=227.1s

  [20740/21087] intraday_9653.csv.gz  in=479,505,193 out=113,089,395 elapsed=227.1s

  [20741/21087] intraday_9652.csv.gz  in=479,521,065 out=113,089,395 elapsed=227.1s

  [20742/21087] intraday_9654.csv.gz  in=479,534,323 out=113,089,395 elapsed=227.1s

  [20743/21087] intraday_9655.csv.gz  in=479,547,550 out=113,089,395 elapsed=227.1s

  [20744/21087] intraday_9656.csv.gz  in=479,560,206 out=113,089,395 elapsed=227.1s

  [20745/21087] intraday_9657.csv.gz  in=479,573,807 out=113,089,395 elapsed=227.1s

  [20746/21087] intraday_9658.csv.gz  in=479,586,400 out=113,089,395 elapsed=227.1s

  [20747/21087] intraday_9659.csv.gz  in=479,599,764 out=113,089,395 elapsed=227.1s

  [20748/21087] intraday_9660.csv.gz  in=479,611,660 out=113,089,395 elapsed=227.2s

  [20749/21087] intraday_9662.csv.gz  in=479,624,227 out=113,089,395 elapsed=227.2s

  [20750/21087] intraday_9661.csv.gz  in=479,636,619 out=113,089,395 elapsed=227.2s

  [20751/21087] intraday_9663.csv.gz  in=479,648,432 out=113,089,395 elapsed=227.2s

  [20752/21087] intraday_9664.csv.gz  in=479,663,211 out=113,089,395 elapsed=227.2s

  [20753/21087] intraday_9665.csv.gz  in=479,678,288 out=113,089,395 elapsed=227.2s

  [20754/21087] intraday_9666.csv.gz  in=479,694,062 out=113,089,395 elapsed=227.2s

  [20755/21087] intraday_9667.csv.gz  in=479,707,404 out=113,089,395 elapsed=227.2s

  [20756/21087] intraday_9668.csv.gz  in=479,720,200 out=113,089,395 elapsed=227.2s

  [20757/21087] intraday_9669.csv.gz  in=479,733,721 out=113,089,395 elapsed=227.2s

  [20758/21087] intraday_9670.csv.gz  in=479,744,764 out=113,089,395 elapsed=227.2s

  [20759/21087] intraday_9671.csv.gz  in=479,760,066 out=113,089,395 elapsed=227.2s

  [20760/21087] intraday_9672.csv.gz  in=479,774,392 out=113,089,395 elapsed=227.2s

  [20761/21087] intraday_9673.csv.gz  in=479,787,741 out=113,089,395 elapsed=227.3s

  [20762/21087] intraday_9674.csv.gz  in=479,798,803 out=113,089,395 elapsed=227.3s

  [20763/21087] intraday_9675.csv.gz  in=479,813,716 out=113,089,395 elapsed=227.3s

  [20764/21087] intraday_9676.csv.gz  in=479,825,975 out=113,089,395 elapsed=227.3s

  [20765/21087] intraday_9677.csv.gz  in=479,840,138 out=113,089,395 elapsed=227.3s

  [20766/21087] intraday_9678.csv.gz  in=479,854,500 out=113,089,395 elapsed=227.3s

  [20767/21087] intraday_9679.csv.gz  in=479,872,113 out=113,089,395 elapsed=227.3s

  [20768/21087] intraday_9680.csv.gz  in=479,884,896 out=113,089,395 elapsed=227.3s

  [20769/21087] intraday_9682.csv.gz  in=479,896,372 out=113,089,395 elapsed=227.3s

  [20770/21087] intraday_9681.csv.gz  in=479,913,245 out=113,089,395 elapsed=227.3s

  [20771/21087] intraday_9683.csv.gz  in=479,926,538 out=113,089,395 elapsed=227.3s

  [20772/21087] intraday_9684.csv.gz  in=479,938,247 out=113,089,395 elapsed=227.3s

  [20773/21087] intraday_9685.csv.gz  in=479,950,665 out=113,089,395 elapsed=227.3s

  [20774/21087] intraday_9686.csv.gz  in=479,961,643 out=113,089,395 elapsed=227.3s

  [20775/21087] intraday_9687.csv.gz  in=479,974,378 out=113,089,395 elapsed=227.4s

  [20776/21087] intraday_9688.csv.gz  in=479,987,925 out=113,089,395 elapsed=227.4s

  [20777/21087] intraday_9689.csv.gz  in=480,004,152 out=113,089,395 elapsed=227.4s

  [20778/21087] intraday_9690.csv.gz  in=480,015,508 out=113,089,395 elapsed=227.4s

  [20779/21087] intraday_9691.csv.gz  in=480,027,811 out=113,089,395 elapsed=227.4s

  [20780/21087] intraday_9692.csv.gz  in=480,040,522 out=113,089,395 elapsed=227.4s

  [20781/21087] intraday_9693.csv.gz  in=480,053,319 out=113,089,395 elapsed=227.4s

  [20782/21087] intraday_9694.csv.gz  in=480,064,511 out=113,089,395 elapsed=227.4s

  [20783/21087] intraday_9695.csv.gz  in=480,077,353 out=113,089,395 elapsed=227.4s

  [20784/21087] intraday_9696.csv.gz  in=480,091,697 out=113,089,395 elapsed=227.4s

  [20785/21087] intraday_9697.csv.gz  in=480,105,660 out=113,089,395 elapsed=227.4s

  [20786/21087] intraday_9698.csv.gz  in=480,120,287 out=113,089,395 elapsed=227.4s

  [20787/21087] intraday_9699.csv.gz  in=480,133,700 out=113,089,395 elapsed=227.4s

  [20788/21087] intraday_9700.csv.gz  in=480,145,951 out=113,089,395 elapsed=227.5s

  [20789/21087] intraday_9701.csv.gz  in=480,159,480 out=113,089,395 elapsed=227.5s

  [20790/21087] intraday_9702.csv.gz  in=480,171,424 out=113,089,395 elapsed=227.5s

  [20791/21087] intraday_9703.csv.gz  in=480,184,876 out=113,089,395 elapsed=227.5s

  [20792/21087] intraday_9704.csv.gz  in=480,193,221 out=113,089,395 elapsed=227.5s

  [20793/21087] intraday_9705.csv.gz  in=480,200,709 out=113,089,395 elapsed=227.5s

  [20794/21087] intraday_9707.csv.gz  in=480,202,356 out=113,089,395 elapsed=227.5s

  [20795/21087] intraday_9708.csv.gz  in=480,202,377 out=113,089,395 elapsed=227.5s

  [20796/21087] intraday_9709.csv.gz  in=480,202,395 out=113,089,395 elapsed=227.5s

  [20797/21087] intraday_9706.csv.gz  in=480,214,959 out=113,089,395 elapsed=227.5s

  [20798/21087] intraday_9710.csv.gz  in=480,215,220 out=113,089,395 elapsed=227.5s

  [20799/21087] intraday_9712.csv.gz  in=480,215,325 out=113,089,395 elapsed=227.5s

  [20800/21087] intraday_9711.csv.gz  in=480,219,464 out=113,089,395 elapsed=227.5s

  [20801/21087] intraday_9713.csv.gz  in=480,220,962 out=113,089,395 elapsed=227.6s

  [20802/21087] intraday_9714.csv.gz  in=480,221,014 out=113,089,395 elapsed=227.6s

  [20803/21087] intraday_9715.csv.gz  in=480,221,452 out=113,089,395 elapsed=227.6s

  [20804/21087] intraday_9717.csv.gz  in=480,221,568 out=113,089,395 elapsed=227.6s

  [20805/21087] intraday_9716.csv.gz  in=480,222,077 out=113,089,395 elapsed=227.6s

  [20806/21087] intraday_9718.csv.gz  in=480,223,471 out=113,089,395 elapsed=227.6s

  [20807/21087] intraday_9719.csv.gz  in=480,223,570 out=113,089,395 elapsed=227.6s

  [20808/21087] intraday_9721.csv.gz  in=480,225,552 out=113,089,395 elapsed=227.6s

  [20809/21087] intraday_9720.csv.gz  in=480,230,679 out=113,089,395 elapsed=227.6s

  [20810/21087] intraday_9722.csv.gz  in=480,230,905 out=113,089,395 elapsed=227.6s

  [20811/21087] intraday_9723.csv.gz  in=480,230,918 out=113,089,395 elapsed=227.6s

  [20812/21087] intraday_9725.csv.gz  in=480,230,962 out=113,089,395 elapsed=227.6s

  [20813/21087] intraday_9724.csv.gz  in=480,241,362 out=113,089,395 elapsed=227.6s

  [20814/21087] intraday_9726.csv.gz  in=480,242,902 out=113,089,395 elapsed=227.6s

  [20815/21087] intraday_9727.csv.gz  in=480,244,106 out=113,089,395 elapsed=227.6s

  [20816/21087] intraday_9730.csv.gz  in=480,244,152 out=113,089,395 elapsed=227.6s

  [20817/21087] intraday_9728.csv.gz  in=480,244,982 out=113,089,395 elapsed=227.7s

  [20818/21087] intraday_9731.csv.gz  in=480,245,091 out=113,089,395 elapsed=227.7s

  [20819/21087] intraday_9729.csv.gz  in=480,246,387 out=113,089,395 elapsed=227.7s

  [20820/21087] intraday_9733.csv.gz  in=480,248,777 out=113,089,395 elapsed=227.7s

  [20821/21087] intraday_9732.csv.gz  in=480,248,881 out=113,089,395 elapsed=227.7s

  [20822/21087] intraday_9735.csv.gz  in=480,249,627 out=113,089,395 elapsed=227.7s

  [20823/21087] intraday_9734.csv.gz  in=480,250,835 out=113,089,395 elapsed=227.7s

  [20824/21087] intraday_9737.csv.gz  in=480,251,269 out=113,089,395 elapsed=227.7s

  [20825/21087] intraday_9736.csv.gz  in=480,251,695 out=113,089,395 elapsed=227.7s

  [20826/21087] intraday_9738.csv.gz  in=480,251,698 out=113,089,395 elapsed=227.7s

  [20827/21087] intraday_9739.csv.gz  in=480,262,150 out=113,089,395 elapsed=227.7s

  [20828/21087] intraday_9741.csv.gz  in=480,274,924 out=113,089,395 elapsed=227.7s

  [20829/21087] intraday_9740.csv.gz  in=480,289,977 out=113,089,395 elapsed=227.7s

  [20830/21087] intraday_9742.csv.gz  in=480,302,394 out=113,089,395 elapsed=227.7s

  [20831/21087] intraday_9743.csv.gz  in=480,311,617 out=113,089,395 elapsed=227.8s

  [20832/21087] intraday_9744.csv.gz  in=480,323,461 out=113,089,395 elapsed=227.8s

  [20833/21087] intraday_9745.csv.gz  in=480,339,017 out=113,089,395 elapsed=227.8s

  [20834/21087] intraday_9746.csv.gz  in=480,353,180 out=113,089,395 elapsed=227.8s

  [20835/21087] intraday_9747.csv.gz  in=480,364,393 out=113,089,395 elapsed=227.8s

  [20836/21087] intraday_9748.csv.gz  in=480,376,810 out=113,089,395 elapsed=227.8s

  [20837/21087] intraday_9749.csv.gz  in=480,391,848 out=113,089,395 elapsed=227.8s

  [20838/21087] intraday_9751.csv.gz  in=480,404,296 out=113,089,395 elapsed=227.8s

  [20839/21087] intraday_9750.csv.gz  in=480,419,610 out=113,089,395 elapsed=227.8s

  [20840/21087] intraday_9752.csv.gz  in=480,432,752 out=113,089,395 elapsed=227.8s

  [20841/21087] intraday_9753.csv.gz  in=480,448,271 out=113,089,395 elapsed=227.8s

  [20842/21087] intraday_9754.csv.gz  in=480,457,998 out=113,089,395 elapsed=227.9s

  [20843/21087] intraday_9755.csv.gz  in=480,469,755 out=113,089,395 elapsed=227.9s

  [20844/21087] intraday_9756.csv.gz  in=480,482,025 out=113,089,395 elapsed=227.9s

  [20845/21087] intraday_9757.csv.gz  in=480,496,221 out=113,089,395 elapsed=227.9s

  [20846/21087] intraday_9758.csv.gz  in=480,507,481 out=113,089,395 elapsed=227.9s

  [20847/21087] intraday_9760.csv.gz  in=480,519,355 out=113,089,395 elapsed=227.9s

  [20848/21087] intraday_9759.csv.gz  in=480,530,366 out=113,089,395 elapsed=227.9s

  [20849/21087] intraday_9761.csv.gz  in=480,544,393 out=113,089,395 elapsed=227.9s

  [20850/21087] intraday_9762.csv.gz  in=480,556,736 out=113,089,395 elapsed=227.9s

  [20851/21087] intraday_9764.csv.gz  in=480,569,940 out=113,089,395 elapsed=227.9s

  [20852/21087] intraday_9763.csv.gz  in=480,582,721 out=113,089,395 elapsed=227.9s

  [20853/21087] intraday_9765.csv.gz  in=480,594,942 out=113,089,395 elapsed=227.9s

  [20854/21087] intraday_9766.csv.gz  in=480,607,419 out=113,089,395 elapsed=227.9s

  [20855/21087] intraday_9767.csv.gz  in=480,619,141 out=113,089,395 elapsed=228.0s

  [20856/21087] intraday_9768.csv.gz  in=480,630,158 out=113,089,395 elapsed=228.0s

  [20857/21087] intraday_9769.csv.gz  in=480,642,976 out=113,089,395 elapsed=228.0s

  [20858/21087] intraday_9770.csv.gz  in=480,657,155 out=113,089,395 elapsed=228.0s

  [20859/21087] intraday_9771.csv.gz  in=480,671,863 out=113,089,395 elapsed=228.0s

  [20860/21087] intraday_9772.csv.gz  in=480,682,664 out=113,089,395 elapsed=228.0s

  [20861/21087] intraday_9773.csv.gz  in=480,693,537 out=113,089,395 elapsed=228.0s

  [20862/21087] intraday_9774.csv.gz  in=480,706,844 out=113,089,395 elapsed=228.0s

  [20863/21087] intraday_9775.csv.gz  in=480,720,417 out=113,089,395 elapsed=228.0s

  [20864/21087] intraday_9776.csv.gz  in=480,730,911 out=113,089,395 elapsed=228.0s

  [20865/21087] intraday_9777.csv.gz  in=480,743,437 out=113,089,395 elapsed=228.0s

  [20866/21087] intraday_9778.csv.gz  in=480,753,660 out=113,089,395 elapsed=228.0s

  [20867/21087] intraday_9779.csv.gz  in=480,763,979 out=113,089,395 elapsed=228.0s

  [20868/21087] intraday_9780.csv.gz  in=480,774,811 out=113,089,395 elapsed=228.1s

  [20869/21087] intraday_9781.csv.gz  in=480,785,889 out=113,089,395 elapsed=228.1s

  [20870/21087] intraday_9782.csv.gz  in=480,798,837 out=113,089,395 elapsed=228.1s

  [20871/21087] intraday_9783.csv.gz  in=480,811,560 out=113,089,395 elapsed=228.1s

  [20872/21087] intraday_9784.csv.gz  in=480,824,391 out=113,089,395 elapsed=228.1s

  [20873/21087] intraday_9785.csv.gz  in=480,837,490 out=113,089,395 elapsed=228.1s

  [20874/21087] intraday_9786.csv.gz  in=480,849,012 out=113,089,395 elapsed=228.1s

  [20875/21087] intraday_9787.csv.gz  in=480,860,277 out=113,089,395 elapsed=228.1s

  [20876/21087] intraday_9788.csv.gz  in=480,873,117 out=113,089,395 elapsed=228.1s

  [20877/21087] intraday_9789.csv.gz  in=480,883,807 out=113,089,395 elapsed=228.1s

  [20878/21087] intraday_9790.csv.gz  in=480,895,128 out=113,089,395 elapsed=228.1s

  [20879/21087] intraday_9791.csv.gz  in=480,906,621 out=113,089,395 elapsed=228.1s

  [20880/21087] intraday_9792.csv.gz  in=480,917,385 out=113,089,395 elapsed=228.1s

  [20881/21087] intraday_9793.csv.gz  in=480,930,744 out=113,089,395 elapsed=228.2s

  [20882/21087] intraday_9794.csv.gz  in=480,941,350 out=113,089,395 elapsed=228.2s

  [20883/21087] intraday_9795.csv.gz  in=480,954,675 out=113,089,395 elapsed=228.2s

  [20884/21087] intraday_9796.csv.gz  in=480,966,994 out=113,089,395 elapsed=228.2s

  [20885/21087] intraday_9797.csv.gz  in=480,979,385 out=113,089,395 elapsed=228.2s

  [20886/21087] intraday_9798.csv.gz  in=480,991,184 out=113,089,395 elapsed=228.2s

  [20887/21087] intraday_9799.csv.gz  in=481,003,426 out=113,089,395 elapsed=228.2s

  [20888/21087] intraday_9800.csv.gz  in=481,015,100 out=113,089,395 elapsed=228.2s

  [20889/21087] intraday_9801.csv.gz  in=481,028,188 out=113,089,395 elapsed=228.2s

  [20890/21087] intraday_9802.csv.gz  in=481,039,194 out=113,089,395 elapsed=228.2s

  [20891/21087] intraday_9803.csv.gz  in=481,051,863 out=113,089,395 elapsed=228.2s

  [20892/21087] intraday_9804.csv.gz  in=481,064,205 out=113,089,395 elapsed=228.2s

  [20893/21087] intraday_9805.csv.gz  in=481,075,440 out=113,089,395 elapsed=228.3s

  [20894/21087] intraday_9806.csv.gz  in=481,090,532 out=113,089,395 elapsed=228.3s

  [20895/21087] intraday_9807.csv.gz  in=481,103,225 out=113,089,395 elapsed=228.3s

  [20896/21087] intraday_9809.csv.gz  in=481,115,575 out=113,089,395 elapsed=228.3s

  [20897/21087] intraday_9808.csv.gz  in=481,130,327 out=113,089,395 elapsed=228.3s

  [20898/21087] intraday_9810.csv.gz  in=481,142,820 out=113,089,395 elapsed=228.3s

  [20899/21087] intraday_9811.csv.gz  in=481,153,399 out=113,089,395 elapsed=228.3s

  [20900/21087] intraday_9812.csv.gz  in=481,165,739 out=113,089,395 elapsed=228.3s

  [20901/21087] intraday_9813.csv.gz  in=481,178,596 out=113,089,395 elapsed=228.3s

  [20902/21087] intraday_9814.csv.gz  in=481,192,804 out=113,089,395 elapsed=228.3s

  [20903/21087] intraday_9815.csv.gz  in=481,204,984 out=113,089,395 elapsed=228.3s

  [20904/21087] intraday_9816.csv.gz  in=481,218,915 out=113,089,395 elapsed=228.4s

  [20905/21087] intraday_9817.csv.gz  in=481,229,037 out=113,089,395 elapsed=228.4s

  [20906/21087] intraday_9819.csv.gz  in=481,241,929 out=113,089,395 elapsed=228.4s

  [20907/21087] intraday_9818.csv.gz  in=481,255,362 out=113,089,395 elapsed=228.4s

  [20908/21087] intraday_9820.csv.gz  in=481,266,662 out=113,089,395 elapsed=228.4s

  [20909/21087] intraday_9821.csv.gz  in=481,278,437 out=113,089,395 elapsed=228.4s

  [20910/21087] intraday_9822.csv.gz  in=481,288,828 out=113,089,395 elapsed=228.4s

  [20911/21087] intraday_9823.csv.gz  in=481,300,220 out=113,089,395 elapsed=228.4s

  [20912/21087] intraday_9824.csv.gz  in=481,312,020 out=113,089,395 elapsed=228.4s

  [20913/21087] intraday_9825.csv.gz  in=481,328,586 out=113,089,395 elapsed=228.4s

  [20914/21087] intraday_9826.csv.gz  in=481,344,678 out=113,089,395 elapsed=228.4s

  [20915/21087] intraday_9827.csv.gz  in=481,355,861 out=113,089,395 elapsed=228.4s

  [20916/21087] intraday_9828.csv.gz  in=481,368,947 out=113,089,395 elapsed=228.5s

  [20917/21087] intraday_9830.csv.gz  in=481,381,857 out=113,089,395 elapsed=228.5s

  [20918/21087] intraday_9832.csv.gz  in=481,393,452 out=113,089,395 elapsed=228.5s

  [20919/21087] intraday_9829.csv.gz  in=481,408,084 out=113,089,395 elapsed=228.5s

  [20920/21087] intraday_9831.csv.gz  in=481,422,796 out=113,089,395 elapsed=228.5s

  [20921/21087] intraday_9833.csv.gz  in=481,435,154 out=113,089,395 elapsed=228.5s

  [20922/21087] intraday_9835.csv.gz  in=481,448,027 out=113,089,395 elapsed=228.5s

  [20923/21087] intraday_9834.csv.gz  in=481,461,654 out=113,089,395 elapsed=228.5s

  [20924/21087] intraday_9836.csv.gz  in=481,475,194 out=113,089,395 elapsed=228.5s

  [20925/21087] intraday_9837.csv.gz  in=481,488,233 out=113,089,395 elapsed=228.5s

  [20926/21087] intraday_9838.csv.gz  in=481,500,578 out=113,089,395 elapsed=228.5s

  [20927/21087] intraday_9839.csv.gz  in=481,513,353 out=113,089,395 elapsed=228.5s

  [20928/21087] intraday_9840.csv.gz  in=481,526,907 out=113,089,395 elapsed=228.6s

  [20929/21087] intraday_9841.csv.gz  in=481,538,788 out=113,089,395 elapsed=228.6s

  [20930/21087] intraday_9842.csv.gz  in=481,549,991 out=113,089,395 elapsed=228.6s

  [20931/21087] intraday_9843.csv.gz  in=481,563,657 out=113,089,395 elapsed=228.6s

  [20932/21087] intraday_9844.csv.gz  in=481,578,394 out=113,089,395 elapsed=228.6s

  [20933/21087] intraday_9845.csv.gz  in=481,592,328 out=113,089,395 elapsed=228.6s

  [20934/21087] intraday_9846.csv.gz  in=481,605,459 out=113,089,395 elapsed=228.6s

  [20935/21087] intraday_9847.csv.gz  in=481,618,269 out=113,089,395 elapsed=228.6s

  [20936/21087] intraday_9849.csv.gz  in=481,629,387 out=113,089,395 elapsed=228.6s

  [20937/21087] intraday_9848.csv.gz  in=481,645,763 out=113,089,395 elapsed=228.6s

  [20938/21087] intraday_9850.csv.gz  in=481,658,096 out=113,089,395 elapsed=228.6s

  [20939/21087] intraday_9851.csv.gz  in=481,672,667 out=113,089,395 elapsed=228.6s

  [20940/21087] intraday_9852.csv.gz  in=481,687,151 out=113,089,395 elapsed=228.6s

  [20941/21087] intraday_9853.csv.gz  in=481,697,220 out=113,089,395 elapsed=228.6s

  [20942/21087] intraday_9854.csv.gz  in=481,710,696 out=113,089,395 elapsed=228.7s

  [20943/21087] intraday_9855.csv.gz  in=481,723,121 out=113,089,395 elapsed=228.7s

  [20944/21087] intraday_9856.csv.gz  in=481,736,076 out=113,089,395 elapsed=228.7s

  [20945/21087] intraday_9857.csv.gz  in=481,751,293 out=113,089,395 elapsed=228.7s

  [20946/21087] intraday_9858.csv.gz  in=481,766,744 out=113,089,395 elapsed=228.7s

  [20947/21087] intraday_9859.csv.gz  in=481,784,030 out=113,089,395 elapsed=228.7s

  [20948/21087] intraday_9860.csv.gz  in=481,799,775 out=113,089,395 elapsed=228.7s

  [20949/21087] intraday_9861.csv.gz  in=481,811,823 out=113,089,395 elapsed=228.7s

  [20950/21087] intraday_9862.csv.gz  in=481,824,887 out=113,089,395 elapsed=228.7s

  [20951/21087] intraday_9863.csv.gz  in=481,837,415 out=113,089,395 elapsed=228.7s

  [20952/21087] intraday_9864.csv.gz  in=481,847,812 out=113,089,395 elapsed=228.7s

  [20953/21087] intraday_9865.csv.gz  in=481,861,205 out=113,089,395 elapsed=228.8s

  [20954/21087] intraday_9866.csv.gz  in=481,872,152 out=113,089,395 elapsed=228.8s

  [20955/21087] intraday_9867.csv.gz  in=481,887,159 out=113,089,395 elapsed=228.8s

  [20956/21087] intraday_9868.csv.gz  in=481,900,450 out=113,089,395 elapsed=228.8s

  [20957/21087] intraday_9869.csv.gz  in=481,915,734 out=113,089,395 elapsed=228.8s

  [20958/21087] intraday_9870.csv.gz  in=481,928,797 out=113,089,395 elapsed=228.8s

  [20959/21087] intraday_9871.csv.gz  in=481,939,817 out=113,089,395 elapsed=228.8s

  [20960/21087] intraday_9872.csv.gz  in=481,951,589 out=113,089,395 elapsed=228.8s

  [20961/21087] intraday_9873.csv.gz  in=481,965,596 out=113,089,395 elapsed=228.8s

  [20962/21087] intraday_9874.csv.gz  in=481,976,102 out=113,089,395 elapsed=228.8s

  [20963/21087] intraday_9875.csv.gz  in=481,990,405 out=113,089,395 elapsed=228.8s

  [20964/21087] intraday_9876.csv.gz  in=482,004,786 out=113,089,395 elapsed=228.8s

  [20965/21087] intraday_9877.csv.gz  in=482,018,727 out=113,089,395 elapsed=228.9s

  [20966/21087] intraday_9878.csv.gz  in=482,033,156 out=113,089,395 elapsed=228.9s

  [20967/21087] intraday_9879.csv.gz  in=482,045,361 out=113,089,395 elapsed=228.9s

  [20968/21087] intraday_9880.csv.gz  in=482,057,749 out=113,089,395 elapsed=228.9s

  [20969/21087] intraday_9882.csv.gz  in=482,068,603 out=113,089,395 elapsed=228.9s

  [20970/21087] intraday_9881.csv.gz  in=482,082,768 out=113,089,395 elapsed=228.9s

  [20971/21087] intraday_9883.csv.gz  in=482,096,077 out=113,089,395 elapsed=228.9s

  [20972/21087] intraday_9884.csv.gz  in=482,103,081 out=113,089,395 elapsed=228.9s

  [20973/21087] intraday_9885.csv.gz  in=482,111,455 out=113,089,395 elapsed=228.9s

  [20974/21087] intraday_9886.csv.gz  in=482,122,041 out=113,089,395 elapsed=228.9s

  [20975/21087] intraday_9887.csv.gz  in=482,136,636 out=113,089,395 elapsed=228.9s

  [20976/21087] intraday_9888.csv.gz  in=482,148,903 out=113,089,395 elapsed=228.9s

  [20977/21087] intraday_9889.csv.gz  in=482,160,525 out=113,089,395 elapsed=228.9s

  [20978/21087] intraday_9890.csv.gz  in=482,170,813 out=113,089,395 elapsed=228.9s

  [20979/21087] intraday_9891.csv.gz  in=482,182,377 out=113,089,395 elapsed=229.0s

  [20980/21087] intraday_9892.csv.gz  in=482,197,236 out=113,089,395 elapsed=229.0s

  [20981/21087] intraday_9894.csv.gz  in=482,207,867 out=113,089,395 elapsed=229.0s

  [20982/21087] intraday_9893.csv.gz  in=482,222,344 out=113,089,395 elapsed=229.0s

  [20983/21087] intraday_9895.csv.gz  in=482,234,224 out=113,089,395 elapsed=229.0s

  [20984/21087] intraday_9896.csv.gz  in=482,248,920 out=113,089,395 elapsed=229.0s

  [20985/21087] intraday_9898.csv.gz  in=482,260,915 out=113,089,395 elapsed=229.0s

  [20986/21087] intraday_9897.csv.gz  in=482,274,768 out=113,089,395 elapsed=229.0s

  [20987/21087] intraday_9899.csv.gz  in=482,288,610 out=113,089,395 elapsed=229.0s

  [20988/21087] intraday_9900.csv.gz  in=482,304,143 out=113,089,395 elapsed=229.0s

  [20989/21087] intraday_9902.csv.gz  in=482,317,185 out=113,089,395 elapsed=229.0s

  [20990/21087] intraday_9901.csv.gz  in=482,327,739 out=113,089,395 elapsed=229.0s

  [20991/21087] intraday_9903.csv.gz  in=482,340,934 out=113,089,395 elapsed=229.0s

  [20992/21087] intraday_9904.csv.gz  in=482,357,482 out=113,089,395 elapsed=229.1s

  [20993/21087] intraday_9906.csv.gz  in=482,368,229 out=113,089,395 elapsed=229.1s

  [20994/21087] intraday_9905.csv.gz  in=482,380,951 out=113,089,395 elapsed=229.1s

  [20995/21087] intraday_9907.csv.gz  in=482,395,868 out=113,089,395 elapsed=229.1s

  [20996/21087] intraday_9908.csv.gz  in=482,409,572 out=113,089,395 elapsed=229.1s

  [20997/21087] intraday_9909.csv.gz  in=482,424,007 out=113,089,395 elapsed=229.1s

  [20998/21087] intraday_9910.csv.gz  in=482,437,562 out=113,089,395 elapsed=229.1s

  [20999/21087] intraday_9911.csv.gz  in=482,450,280 out=113,089,395 elapsed=229.1s

  [21000/21087] intraday_9912.csv.gz  in=482,462,453 out=113,089,395 elapsed=229.1s

  [21001/21087] intraday_9913.csv.gz  in=482,473,593 out=113,089,395 elapsed=229.1s

  [21002/21087] intraday_9915.csv.gz  in=482,483,698 out=113,089,395 elapsed=229.1s

  [21003/21087] intraday_9914.csv.gz  in=482,495,464 out=113,089,395 elapsed=229.1s

  [21004/21087] intraday_9916.csv.gz  in=482,510,212 out=113,089,395 elapsed=229.2s

  [21005/21087] intraday_9917.csv.gz  in=482,526,142 out=113,089,395 elapsed=229.2s

  [21006/21087] intraday_9919.csv.gz  in=482,537,441 out=113,089,395 elapsed=229.2s

  [21007/21087] intraday_9918.csv.gz  in=482,550,523 out=113,089,395 elapsed=229.2s

  [21008/21087] intraday_9920.csv.gz  in=482,561,645 out=113,089,395 elapsed=229.2s

  [21009/21087] intraday_9921.csv.gz  in=482,573,796 out=113,089,395 elapsed=229.2s

  [21010/21087] intraday_9922.csv.gz  in=482,587,974 out=113,089,395 elapsed=229.2s

  [21011/21087] intraday_9923.csv.gz  in=482,599,063 out=113,089,395 elapsed=229.2s

  [21012/21087] intraday_9924.csv.gz  in=482,611,748 out=113,089,395 elapsed=229.2s

  [21013/21087] intraday_9925.csv.gz  in=482,622,710 out=113,089,395 elapsed=229.2s

  [21014/21087] intraday_9927.csv.gz  in=482,633,936 out=113,089,395 elapsed=229.2s

  [21015/21087] intraday_9926.csv.gz  in=482,660,511 out=113,089,395 elapsed=229.3s

  [21016/21087] intraday_9928.csv.gz  in=482,671,689 out=113,089,395 elapsed=229.3s

  [21017/21087] intraday_9929.csv.gz  in=482,685,092 out=113,089,395 elapsed=229.3s

  [21018/21087] intraday_9930.csv.gz  in=482,696,689 out=113,089,395 elapsed=229.3s

  [21019/21087] intraday_9931.csv.gz  in=482,710,641 out=113,089,395 elapsed=229.3s

  [21020/21087] intraday_9932.csv.gz  in=482,723,357 out=113,089,395 elapsed=229.3s

  [21021/21087] intraday_9933.csv.gz  in=482,734,090 out=113,089,395 elapsed=229.3s

  [21022/21087] intraday_9934.csv.gz  in=482,746,067 out=113,089,395 elapsed=229.3s

  [21023/21087] intraday_9935.csv.gz  in=482,757,794 out=113,089,395 elapsed=229.3s

  [21024/21087] intraday_9936.csv.gz  in=482,768,580 out=113,089,395 elapsed=229.3s

  [21025/21087] intraday_9937.csv.gz  in=482,779,588 out=113,089,395 elapsed=229.3s

  [21026/21087] intraday_9938.csv.gz  in=482,790,558 out=113,089,395 elapsed=229.3s

  [21027/21087] intraday_9939.csv.gz  in=482,802,507 out=113,089,395 elapsed=229.3s

  [21028/21087] intraday_9940.csv.gz  in=482,816,094 out=113,089,395 elapsed=229.4s

  [21029/21087] intraday_9941.csv.gz  in=482,828,091 out=113,089,395 elapsed=229.4s

  [21030/21087] intraday_9942.csv.gz  in=482,842,551 out=113,089,395 elapsed=229.4s

  [21031/21087] intraday_9943.csv.gz  in=482,856,028 out=113,089,395 elapsed=229.4s

  [21032/21087] intraday_9944.csv.gz  in=482,868,585 out=113,089,395 elapsed=229.4s

  [21033/21087] intraday_9945.csv.gz  in=482,879,566 out=113,089,395 elapsed=229.4s

  [21034/21087] intraday_9946.csv.gz  in=482,891,442 out=113,089,395 elapsed=229.4s

  [21035/21087] intraday_9947.csv.gz  in=482,903,734 out=113,089,395 elapsed=229.4s

  [21036/21087] intraday_9948.csv.gz  in=482,917,797 out=113,089,395 elapsed=229.4s

  [21037/21087] intraday_9949.csv.gz  in=482,930,295 out=113,089,395 elapsed=229.4s

  [21038/21087] intraday_9950.csv.gz  in=482,941,682 out=113,089,395 elapsed=229.4s

  [21039/21087] intraday_9951.csv.gz  in=482,953,341 out=113,089,395 elapsed=229.4s

  [21040/21087] intraday_9952.csv.gz  in=482,963,175 out=113,089,395 elapsed=229.4s

  [21041/21087] intraday_9954.csv.gz  in=482,976,208 out=113,089,395 elapsed=229.5s

  [21042/21087] intraday_9953.csv.gz  in=482,995,419 out=113,089,395 elapsed=229.5s

  [21043/21087] intraday_9955.csv.gz  in=483,010,292 out=113,089,395 elapsed=229.5s

  [21044/21087] intraday_9956.csv.gz  in=483,023,709 out=113,089,395 elapsed=229.5s

  [21045/21087] intraday_9958.csv.gz  in=483,033,505 out=113,089,395 elapsed=229.5s

  [21046/21087] intraday_9957.csv.gz  in=483,045,926 out=113,089,395 elapsed=229.5s

  [21047/21087] intraday_9959.csv.gz  in=483,058,884 out=113,089,395 elapsed=229.5s

  [21048/21087] intraday_9960.csv.gz  in=483,071,720 out=113,089,395 elapsed=229.5s

  [21049/21087] intraday_9961.csv.gz  in=483,085,849 out=113,089,395 elapsed=229.5s

  [21050/21087] intraday_9964.csv.gz  in=483,096,988 out=113,089,395 elapsed=229.5s

  [21051/21087] intraday_9963.csv.gz  in=483,109,707 out=113,089,395 elapsed=229.5s

  [21052/21087] intraday_9962.csv.gz  in=483,122,105 out=113,089,395 elapsed=229.5s

  [21053/21087] intraday_9965.csv.gz  in=483,135,755 out=113,089,395 elapsed=229.6s

  [21054/21087] intraday_9968.csv.gz  in=483,147,314 out=113,089,395 elapsed=229.6s

  [21055/21087] intraday_9966.csv.gz  in=483,158,362 out=113,089,395 elapsed=229.6s

  [21056/21087] intraday_9967.csv.gz  in=483,170,318 out=113,089,395 elapsed=229.6s

  [21057/21087] intraday_9969.csv.gz  in=483,179,473 out=113,089,395 elapsed=229.6s

  [21058/21087] intraday_9970.csv.gz  in=483,190,026 out=113,089,395 elapsed=229.6s

  [21059/21087] intraday_9972.csv.gz  in=483,207,936 out=113,089,395 elapsed=229.6s

  [21060/21087] intraday_9971.csv.gz  in=483,235,144 out=113,089,395 elapsed=229.6s

  [21061/21087] intraday_9973.csv.gz  in=483,249,596 out=113,089,395 elapsed=229.6s

  [21062/21087] intraday_9974.csv.gz  in=483,261,514 out=113,089,395 elapsed=229.6s

  [21063/21087] intraday_9975.csv.gz  in=483,272,475 out=113,089,395 elapsed=229.6s

  [21064/21087] intraday_9976.csv.gz  in=483,288,701 out=113,089,395 elapsed=229.6s

  [21065/21087] intraday_9977.csv.gz  in=483,308,900 out=113,089,395 elapsed=229.7s

  [21066/21087] intraday_9978.csv.gz  in=483,325,068 out=113,089,395 elapsed=229.7s

  [21067/21087] intraday_9979.csv.gz  in=483,335,954 out=113,089,395 elapsed=229.7s

  [21068/21087] intraday_9980.csv.gz  in=483,347,605 out=113,089,395 elapsed=229.7s

  [21069/21087] intraday_9981.csv.gz  in=483,360,921 out=113,089,395 elapsed=229.7s

  [21070/21087] intraday_9982.csv.gz  in=483,374,241 out=113,089,395 elapsed=229.7s

  [21071/21087] intraday_9983.csv.gz  in=483,386,648 out=113,089,395 elapsed=229.7s

  [21072/21087] intraday_9984.csv.gz  in=483,400,333 out=113,089,395 elapsed=229.7s

  [21073/21087] intraday_9985.csv.gz  in=483,412,695 out=113,089,395 elapsed=229.7s

  [21074/21087] intraday_9986.csv.gz  in=483,424,303 out=113,089,395 elapsed=229.7s

  [21075/21087] intraday_9987.csv.gz  in=483,437,492 out=113,089,395 elapsed=229.7s

  [21076/21087] intraday_9988.csv.gz  in=483,449,044 out=113,089,395 elapsed=229.7s

  [21077/21087] intraday_9989.csv.gz  in=483,460,066 out=113,089,395 elapsed=229.7s

  [21078/21087] intraday_9990.csv.gz  in=483,472,443 out=113,089,395 elapsed=229.7s

  [21079/21087] intraday_9991.csv.gz  in=483,489,159 out=113,089,395 elapsed=229.8s

  [21080/21087] intraday_9992.csv.gz  in=483,501,785 out=113,089,395 elapsed=229.8s

  [21081/21087] intraday_9993.csv.gz  in=483,516,277 out=113,089,395 elapsed=229.8s

  [21082/21087] intraday_9994.csv.gz  in=483,526,889 out=113,089,395 elapsed=229.8s

  [21083/21087] intraday_9995.csv.gz  in=483,542,774 out=113,089,395 elapsed=229.8s

  [21084/21087] intraday_9997.csv.gz  in=483,555,173 out=113,089,395 elapsed=229.8s

  [21085/21087] intraday_9996.csv.gz  in=483,566,839 out=113,089,395 elapsed=229.8s

  [21086/21087] intraday_9998.csv.gz  in=483,580,170 out=113,089,395 elapsed=229.8s

  [21087/21087] intraday_9999.csv.gz  in=483,595,253 out=113,089,395 elapsed=229.8s

✅ DONE  in=483,595,253 → out=113,089,395  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 243.2s

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [21]:
def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,      # лишено для сумісності виклику
    *,
    max_workers: int = 4,
) -> pd.DataFrame:
    """Денні open (перший бар 09:30–09:35) і close (останній бар 15:55–15:59).

    Раніше кожен відібраний рядок проходив через itertuples + оновлення python-словника;
    тепер редукція повністю векторна (sort + drop_duplicates у pyarrow/pandas).
    Клітинка 19 уже рахує це за один прохід — ця функція лишається як самостійний шлях.
    """
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    open_parts, close_parts = [], []
    lock = threading.Lock()

    def _handle(path):
        reader = _open_intraday_csv(path, 64 << 20)
        lo, lc = [], []
        while True:
            try:
                rb = reader.read_next_batch()
            except StopIteration:
                break
            o_df, c_df = _oc_from_table(pa.Table.from_batches([rb]))
            if len(o_df):
                lo.append(o_df)
            if len(c_df):
                lc.append(c_df)
        with lock:
            open_parts.extend(lo)
            close_parts.extend(lc)

    if max_workers and max_workers > 1:
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            list(ex.map(_handle, files))
    else:
        for p in files:
            _handle(p)

    out = _finalize_oc(open_parts, close_parts)

    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)
    return out

In [22]:
# oc.parquet уже побудовано в клітинці 19 (той самий прохід по файлах).
# Перебудовуємо лише якщо його немає.
_oc_path = str(WORK_DIR / "oc.parquet")
if os.path.exists(_oc_path):
    df_oc = pd.read_parquet(_oc_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(BATCH_DIR), out_path=_oc_path)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [23]:
import os
import gc
import time
import pandas as pd
import numpy as np

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def _prep_oc_prev_close(df_oc: pd.DataFrame) -> pd.DataFrame:
    """['ticker','date','open','prev_close','same_day_close'], date — звичайний рядок 'YYYY-MM-DD'.

    'prev_close' — close ПОПЕРЕДНЬОГО торгового дня (до 16:01).
    'same_day_close' — close ЦЬОГО Ж дня (від 16:01, коли сесія вже
    закрилась о 16:00 і референс-клоуз має перерахуватись на
    сьогоднішній)."""
    oc = df_oc[["ticker", "date", "open", "close"]].copy()
    oc["ticker"] = oc["ticker"].astype(str)
    oc["date"] = oc["date"].astype(str).str.slice(0, 10)
    oc = oc.sort_values(["ticker", "date"], kind="stable")
    oc["prev_close"] = oc.groupby("ticker", sort=False)["close"].shift(1)
    oc = oc.rename(columns={"close": "same_day_close"})
    return oc[["ticker", "date", "open", "prev_close", "same_day_close"]].reset_index(drop=True)


def _rebase_prev_close_after_session_close(df: pd.DataFrame,
                                           dt_col: str = "dt",
                                           prev_close_col: str = "prev_close",
                                           same_day_close_col: str = "same_day_close",
                                           close_boundary: str = "16:01") -> "pd.Series":
    """Від close_boundary (16:01, бо сесія закривається о 16:00) референс-клоуз
    кожного стака перераховується на клоуз ЦЬОГО Ж дня замість
    вчорашнього (інакше з 16:01 до півночі все й далі рахувалось би
    відносно вчорашнього клоуза). Час береться зрізом рядка 'dt'
    (без парсингу дат, як і решта пайплайну)."""
    time_str = df[dt_col].astype(str).str.slice(11, 16)
    after_close = time_str >= close_boundary
    return np.where(after_close, df[same_day_close_col], df[prev_close_col])


def _date_from_dt(s: pd.Series) -> pd.Series:
    """'YYYY-MM-DD' з 'dt'. Для рядкового dt це зріз (C-рівень), без парсингу дат."""
    if pd.api.types.is_string_dtype(s) or s.dtype == object:
        return s.astype(str).str.slice(0, 10)
    return s.dt.strftime("%Y-%m-%d")


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame,
                                        _oc_prepared: Optional[pd.DataFrame] = None,
                                        sort_out: bool = False) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' — референс-клоуз,
    відносно якого рахується Stack%.
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']

    Референс-клоуз перераховується о 16:01: до цього часу — клоуз попереднього
    дня, від 16:01 (сесія вже закрилась о 16:00) — клоуз ЦЬОГО Ж дня. Інакше з
    16:01 до півночі рядки й далі рахувались б відносно вчорашнього клоуза.

    Прискорення проти попередньої версії:
      - 'dt' лишається рядком: ні pd.to_datetime, ні .dt.date (це були python-об'єкти
        на кожен рядок — найдорожча операція в усьому пайплайні);
      - prev_close рахується ОДИН раз (передається через _oc_prepared), а не на кожен батч;
      - без per-batch sort_values (фінальне сортування робить клітинка 47).
    """
    right = _oc_prepared if _oc_prepared is not None else _prep_oc_prev_close(df_oc)
    out = df_intraday
    out = out[out["dt"].notna()]
    out = out.assign(date=_date_from_dt(out["dt"]))
    out = out.merge(right, on=["ticker", "date"], how="left")
    out["prev_close"] = _rebase_prev_close_after_session_close(out)
    out = out.drop(columns=["same_day_close"])
    if sort_out:
        out = out.sort_values(["ticker", "dt"], kind="stable").reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    sort_out: bool = False,
):
    """
    Читає великий Parquet батчами і мерджить денні open/prev_close з oc.parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    df_oc = pd.read_parquet(oc_parquet_path)
    missing = {"ticker", "date", "open", "close"} - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")
    oc_prepared = _prep_oc_prev_close(df_oc)      # рахуємо ОДИН раз, не на кожен батч

    if os.path.exists(out_path):
        os.remove(out_path)
    if not out_path.endswith((".csv", ".gz", ".parquet")):
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0

    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}", flush=True)

    for batch_idx, batch in enumerate(pf.iter_batches(batch_size=batch_rows, columns=cols), 1):
        df_batch = batch.to_pandas()
        df_enriched = enrich_with_day_open_and_prev_close(
            df_batch, None, _oc_prepared=oc_prepared, sort_out=sort_out)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched, preserve_index=False)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            df_enriched.to_csv(
                out_path, index=False, mode="a", header=(total_rows == 0),
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_enriched)
        if batch_idx % log_every_batches == 0:
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s", flush=True)


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [24]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
# print("Результат у файлі:", out_path)

In [25]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    Обчислення в numpy (без проміжних pandas-Series і .replace), без gc на кожен батч.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  "
          f"batch_rows≈{batch_rows:,}  using={value_col}", flush=True)

    for batches, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for c in ("prev_close", value_col):
            if c not in df.columns:
                raise KeyError(f"У вхідному файлі немає колонки '{c}'.")

        num = pd.to_numeric(df[value_col], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        den = pd.to_numeric(df["prev_close"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            pct = np.where(den == 0, np.nan, num / den - 1.0) * 100.0   # 0 → NaN, без ділення на 0
        if round_to is not None:
            pct = np.round(pct, int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s", flush=True)
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [26]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
# print("Готово:", out_path)

In [27]:
import os
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Read ticker->bench mapping from csv/xlsx and return ['ticker','bench'].
    """
    ext = os.path.splitext(mapping_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(mapping_path)
    else:
        try:
            df = pd.read_csv(mapping_path, sep=None, engine="python")
        except Exception:
            df = pd.read_csv(mapping_path)

    cols = {c.lower().strip(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol") or list(df.columns)[0]
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf") or list(df.columns)[1]

    out = df[[tcol, bcol]].rename(columns={tcol: "ticker", bcol: "bench"}).dropna()
    out["ticker"] = out["ticker"].astype(str).str.upper().str.strip()
    out["bench"] = out["bench"].astype(str).str.upper().str.strip()
    out = out[(out["ticker"] != "") & (out["bench"] != "")]
    return out.drop_duplicates(ignore_index=True)


def corr_beta_from_mapping_to_parquet(*args, **kwargs):
    """
    Deprecated API path removed.
    corr/beta is now computed locally in cell 12 and written in cell 13/28.
    """
    raise RuntimeError(
        "corr_beta_from_mapping_to_parquet is deprecated. "
        "Use local calculation in cell 12 and parquet output in cell 13/28."
    )

In [28]:
import os
import pandas as pd

out_path = str(WORK_DIR / "corr_beta_pairs.parquet")

# If parquet already exists from cell 13, keep it.
# Otherwise rebuild it from x_to_best_etf_by_lvl3.csv (no API calls).
if not os.path.exists(out_path):
    src_csv = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv")
    if not os.path.exists(src_csv):
        raise FileNotFoundError(f"Neither {out_path} nor {src_csv} exists")

    d = pd.read_csv(src_csv)
    need = ["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
    miss = [c for c in need if c not in d.columns]
    if miss:
        raise KeyError(f"Missing columns in {src_csv}: {miss}")

    d = d.rename(columns={
        "best_y_ticker": "y_ticker",
        "best_corr": "corr",
        "beta_with_best": "beta",
    })[["x_ticker", "y_ticker", "corr", "beta"]]
    d.to_parquet(out_path, index=False)

print("Result:", out_path)

Result: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [29]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    df = pq.read_table(path).to_pandas()
    inv = {c.strip().lower(): c for c in df.columns}

    has_api = ("x_ticker" in inv) and ("y_ticker" in inv)
    has_direct = ("ticker" in inv) and ("bench" in inv)
    if not (has_api or has_direct):
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={inv["x_ticker"]: "ticker", inv["y_ticker"]: "bench"})
    else:
        df = df.rename(columns={inv["ticker"]: "ticker", inv["bench"]: "bench"})

    for c in ("corr", "beta"):
        if c in inv:
            df = df.rename(columns={inv[c]: c})
        else:
            df[c] = pd.NA

    df = df[["ticker", "bench", "corr", "beta"]].copy()
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"] = df["bench"].astype(str).str.strip().str.upper()
    df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    return (df.sort_values(["ticker", "corr"], ascending=[True, False])
              .drop_duplicates(subset=["ticker"], keep="first")
              .reset_index(drop=True))


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), додає 'bench','corr','beta' по 'ticker'.

    Замість merge на кожен батч (+ strip/upper над мільйонами рядків) нормалізація і
    пошук у мапі йдуть по унікальних тікерах, а результат розгортається за кодами.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if mapping.empty:
        raise ValueError(
            f"Мапа bench/corr/beta порожня: {corrbeta_parquet_path}. "
            "Крок побудови x_to_best_etf_by_lvl3 не дав жодного рядка — "
            "інакше bench/corr/beta були б null у всіх рядках."
        )

    m_bench = dict(zip(mapping["ticker"], mapping["bench"]))
    m_corr = dict(zip(mapping["ticker"], mapping["corr"]))
    m_beta = dict(zip(mapping["ticker"], mapping["beta"]))

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_parquet_path}", flush=True)

    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        # dtype="string" тримає bench рядковим і в батчі без жодного збігу: інакше
        # суцільний None дає pyarrow-тип null і схема розійдеться з першим батчем
        df["bench"] = pd.array(_map_by_ticker(codes, cats, m_bench, numeric=False), dtype="string")
        df["corr"] = _map_by_ticker(codes, cats, m_corr, numeric=True)
        df["beta"] = _map_by_ticker(codes, cats, m_beta, numeric=True)

        cols = [c for c in df.columns if c not in ("bench", "corr", "beta")]
        if insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]]
        else:
            df = df[cols + ["bench", "corr", "beta"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        elif not table.schema.equals(writer.schema, check_metadata=False):
            table = table.cast(writer.schema)
        writer.write_table(table)

        total_rows += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_parquet_path


# опціональний аліас під старе ім'я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [30]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# out_path = attach_bench_corr_beta_parquet(
#     input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
#     corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
#     out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
#     batch_rows=2_000_000,
#     round_decimals=4,
#     insert_before="pct_vs_prev_close",
#     compression="snappy",
# )
# print("Готово:", out_path)

In [31]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [32]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Проміжного premarket_rows_final.parquet більше не існує: bench/corr/beta
# додаються за той самий прохід, що й решта. Готовий файл — у комірці 47.

In [33]:
# список тикерів
tickers = [
    'ARKK', 'COPX', 'DRAM', 'FCX', 'FXI', 'GDX', 'IBIT', 'IGV', 'ITA', 'IWM',
    'KRE', 'KWEB', 'NASA', 'QQQ', 'SLV', 'SOXX', 'SPY', 'UNG', 'URA', 'XBI',
    'XLB', 'XLE', 'XLF', 'XLP', 'XLU', 'XLV', 'XOP', 'XRT',
]

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [34]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=12,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

# Збої API більше не маскуються під «порожні дні»: усе, що тут перелічено, НЕ позначено
# готовим. Запускай клітинку повторно, доки errs не стане порожнім.
if errs is not None and len(errs):
    print(f"⚠️ {len(errs)} тікерів зі збоями — перезапусти клітинку:")
    print(errs.head(20).to_string())

▶ Починаємо: 28 тікерів (пропущено 0 по старому маніфесту) | 2026-07-24 00:00:00 → 2026-10-24 23:59:59 | interval=1 | next batch #0156 | run=3d459b38

   workers: tickers=12, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-07-24 → 2026-10-22 (91 днів)

   📈 обробляються дні: 2026-10-23 → 2026-10-24 (2 днів)

   psutil · старт · 🧠 RAM: 799.8 MB

[10/28] ✓ DRAM: 1,056 рядків |  35.71% | ETA 00:01

[20/28] ✓ XBI: 431 рядків |  71.43% | ETA 00:00

[28/28] ✓ XRT: 391 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 808.3 MB

💾 batch 156 → 17,498 рядків (всього 17,498 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\ETF\intraday_0156.csv.gz

   ✅ після flush · 🧠 RAM: 814.9 MB

   🔚 фінал · 🧠 RAM: 814.9 MB

🏁 Готово. Нових рядків: 17,498 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:02

In [35]:
# Один прохід по ETF-батчах: premarket-рядки + денні open/close.
_, df_oc = collect_premarket_and_oc(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    oc_out_path=str(WORK_DIR / "oc_etf.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    build_oc=True,
    max_workers=4,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  files=156 workers=4

  [1/156] intraday_0004.csv.gz  in=1,760 out=1,760 elapsed=0.0s

  [2/156] intraday_0003.csv.gz  in=10,518 out=10,518 elapsed=0.0s

  [3/156] intraday_0002.csv.gz  in=20,691 out=20,691 elapsed=0.1s

  [4/156] intraday_0005.csv.gz  in=31,264 out=31,264 elapsed=0.1s

  [5/156] intraday_0006.csv.gz  in=41,355 out=41,355 elapsed=0.1s

  [6/156] intraday_0008.csv.gz  in=52,039 out=52,039 elapsed=0.1s

  [7/156] intraday_0007.csv.gz  in=62,186 out=62,186 elapsed=0.1s

  [8/156] intraday_0009.csv.gz  in=70,760 out=70,760 elapsed=0.1s

  [9/156] intraday_0010.csv.gz  in=72,207 out=72,207 elapsed=0.1s

  [10/156] intraday_0011.csv.gz  in=81,941 out=81,941 elapsed=0.2s

  [11/156] intraday_0012.csv.gz  in=91,152 out=91,152 elapsed=0.2s

  [12/156] intraday_0013.csv.gz  in=100,754 out=100,754 elapsed=0.2s

  [13/156] intraday_0016.csv.gz  in=102,125 out=102,125 elapsed=0.2s

  [14/156] intraday_0014.csv.gz  in=111,758 out=111,758 elapsed=0.2s

  [15/156] intraday_0015.csv.gz  in=120,035 out=120,035 elapsed=0.2s

  [16/156] intraday_0019.csv.gz  in=129,531 out=129,531 elapsed=0.2s

  [17/156] intraday_0018.csv.gz  in=138,758 out=138,758 elapsed=0.2s

  [18/156] intraday_0017.csv.gz  in=148,074 out=148,074 elapsed=0.2s

  [19/156] intraday_0021.csv.gz  in=149,677 out=149,677 elapsed=0.2s

  [20/156] intraday_0020.csv.gz  in=157,847 out=157,847 elapsed=0.2s

  [21/156] intraday_0023.csv.gz  in=167,662 out=167,662 elapsed=0.3s

  [22/156] intraday_0022.csv.gz  in=196,862 out=196,862 elapsed=0.3s

  [23/156] intraday_0024.csv.gz  in=218,002 out=218,002 elapsed=0.3s

  [24/156] intraday_0026.csv.gz  in=226,279 out=226,279 elapsed=0.3s

  [25/156] intraday_0027.csv.gz  in=235,077 out=235,077 elapsed=0.3s

  [26/156] intraday_0028.csv.gz  in=244,053 out=244,053 elapsed=0.3s

  [27/156] intraday_0029.csv.gz  in=252,994 out=252,994 elapsed=0.3s

  [28/156] intraday_0025.csv.gz  in=357,436 out=357,436 elapsed=0.4s

  [29/156] intraday_0031.csv.gz  in=366,338 out=366,338 elapsed=0.4s

  [30/156] intraday_0030.csv.gz  in=375,587 out=375,587 elapsed=0.4s

  [31/156] intraday_0032.csv.gz  in=384,366 out=384,366 elapsed=0.4s

  [32/156] intraday_0034.csv.gz  in=393,019 out=393,019 elapsed=0.5s

  [33/156] intraday_0033.csv.gz  in=401,796 out=401,796 elapsed=0.5s

  [34/156] intraday_0035.csv.gz  in=410,508 out=410,508 elapsed=0.5s

  [35/156] intraday_0001.csv.gz  in=997,428 out=997,428 elapsed=0.7s

  [36/156] intraday_0037.csv.gz  in=1,006,350 out=1,006,350 elapsed=0.7s

  [37/156] intraday_0038.csv.gz  in=1,015,232 out=1,015,232 elapsed=0.7s

  [38/156] intraday_0036.csv.gz  in=1,024,157 out=1,024,157 elapsed=0.7s

  [39/156] intraday_0039.csv.gz  in=1,032,246 out=1,032,246 elapsed=0.7s

  [40/156] intraday_0042.csv.gz  in=1,040,425 out=1,040,425 elapsed=0.7s

  [41/156] intraday_0040.csv.gz  in=1,049,018 out=1,049,018 elapsed=0.7s

  [42/156] intraday_0041.csv.gz  in=1,058,326 out=1,058,326 elapsed=0.7s

  [43/156] intraday_0043.csv.gz  in=1,066,321 out=1,066,321 elapsed=0.8s

  [44/156] intraday_0045.csv.gz  in=1,073,502 out=1,073,502 elapsed=0.8s

  [45/156] intraday_0044.csv.gz  in=1,082,019 out=1,082,019 elapsed=0.8s

  [46/156] intraday_0046.csv.gz  in=1,090,385 out=1,090,385 elapsed=0.8s

  [47/156] intraday_0047.csv.gz  in=1,098,733 out=1,098,733 elapsed=0.8s

  [48/156] intraday_0048.csv.gz  in=1,107,041 out=1,107,041 elapsed=0.8s

  [49/156] intraday_0049.csv.gz  in=1,115,603 out=1,115,603 elapsed=0.8s

  [50/156] intraday_0050.csv.gz  in=1,123,880 out=1,123,880 elapsed=0.8s

  [51/156] intraday_0051.csv.gz  in=1,132,076 out=1,132,076 elapsed=0.8s

  [52/156] intraday_0052.csv.gz  in=1,140,350 out=1,140,350 elapsed=0.9s

  [53/156] intraday_0053.csv.gz  in=1,148,364 out=1,148,364 elapsed=0.9s

  [54/156] intraday_0054.csv.gz  in=1,156,344 out=1,156,344 elapsed=0.9s

  [55/156] intraday_0056.csv.gz  in=1,164,562 out=1,164,562 elapsed=0.9s

  [56/156] intraday_0057.csv.gz  in=1,173,385 out=1,173,385 elapsed=0.9s

  [57/156] intraday_0058.csv.gz  in=1,181,781 out=1,181,781 elapsed=0.9s

  [58/156] intraday_0059.csv.gz  in=1,189,748 out=1,189,748 elapsed=0.9s

  [59/156] intraday_0060.csv.gz  in=1,197,814 out=1,197,814 elapsed=0.9s

  [60/156] intraday_0061.csv.gz  in=1,206,064 out=1,206,064 elapsed=1.0s

  [61/156] intraday_0062.csv.gz  in=1,214,193 out=1,214,193 elapsed=1.0s

  [62/156] intraday_0055.csv.gz  in=1,328,002 out=1,328,002 elapsed=1.0s

  [63/156] intraday_0065.csv.gz  in=1,336,367 out=1,336,367 elapsed=1.0s

  [64/156] intraday_0064.csv.gz  in=1,344,589 out=1,344,589 elapsed=1.0s

  [65/156] intraday_0063.csv.gz  in=1,352,915 out=1,352,915 elapsed=1.0s

  [66/156] intraday_0066.csv.gz  in=1,360,697 out=1,360,697 elapsed=1.0s

  [67/156] intraday_0068.csv.gz  in=1,369,215 out=1,369,215 elapsed=1.1s

  [68/156] intraday_0067.csv.gz  in=1,377,472 out=1,377,472 elapsed=1.1s

  [69/156] intraday_0070.csv.gz  in=1,395,056 out=1,395,056 elapsed=1.1s

  [70/156] intraday_0071.csv.gz  in=1,412,694 out=1,412,694 elapsed=1.1s

  [71/156] intraday_0072.csv.gz  in=1,430,041 out=1,430,041 elapsed=1.1s

  [72/156] intraday_0073.csv.gz  in=1,447,121 out=1,447,121 elapsed=1.1s

  [73/156] intraday_0074.csv.gz  in=1,464,856 out=1,464,856 elapsed=1.2s

  [74/156] intraday_0077.csv.gz  in=1,467,224 out=1,467,224 elapsed=1.2s

  [75/156] intraday_0075.csv.gz  in=1,484,607 out=1,484,607 elapsed=1.2s

  [76/156] intraday_0076.csv.gz  in=1,501,364 out=1,501,364 elapsed=1.2s

  [77/156] intraday_0079.csv.gz  in=1,517,849 out=1,517,849 elapsed=1.2s

  [78/156] intraday_0078.csv.gz  in=1,535,445 out=1,535,445 elapsed=1.2s

  [79/156] intraday_0080.csv.gz  in=1,552,382 out=1,552,382 elapsed=1.2s

  [80/156] intraday_0083.csv.gz  in=1,570,331 out=1,570,331 elapsed=1.3s

  [81/156] intraday_0081.csv.gz  in=1,587,493 out=1,587,493 elapsed=1.3s

  [82/156] intraday_0082.csv.gz  in=1,604,362 out=1,604,362 elapsed=1.3s

  [83/156] intraday_0084.csv.gz  in=1,621,662 out=1,621,662 elapsed=1.3s

  [84/156] intraday_0085.csv.gz  in=1,638,586 out=1,638,586 elapsed=1.3s

  [85/156] intraday_0086.csv.gz  in=1,655,557 out=1,655,557 elapsed=1.3s

  [86/156] intraday_0087.csv.gz  in=1,672,374 out=1,672,374 elapsed=1.4s

  [87/156] intraday_0088.csv.gz  in=1,690,115 out=1,690,115 elapsed=1.4s

  [88/156] intraday_0090.csv.gz  in=1,706,513 out=1,706,513 elapsed=1.4s

  [89/156] intraday_0091.csv.gz  in=1,723,628 out=1,723,628 elapsed=1.4s

  [90/156] intraday_0092.csv.gz  in=1,739,843 out=1,739,843 elapsed=1.4s

  [91/156] intraday_0093.csv.gz  in=1,739,852 out=1,739,852 elapsed=1.4s

  [92/156] intraday_0089.csv.gz  in=1,867,411 out=1,867,411 elapsed=1.5s

  [93/156] intraday_0095.csv.gz  in=1,883,964 out=1,883,964 elapsed=1.5s

  [94/156] intraday_0094.csv.gz  in=1,902,926 out=1,902,926 elapsed=1.5s

  [95/156] intraday_0096.csv.gz  in=1,920,844 out=1,920,844 elapsed=1.5s

  [96/156] intraday_0097.csv.gz  in=1,937,006 out=1,937,006 elapsed=1.6s

  [97/156] intraday_0098.csv.gz  in=1,952,695 out=1,952,695 elapsed=1.6s

  [98/156] intraday_0099.csv.gz  in=1,954,305 out=1,954,305 elapsed=1.6s

  [99/156] intraday_0100.csv.gz  in=1,970,821 out=1,970,821 elapsed=1.6s

  [100/156] intraday_0101.csv.gz  in=1,987,634 out=1,987,634 elapsed=1.6s

  [101/156] intraday_0103.csv.gz  in=2,006,707 out=2,006,707 elapsed=1.6s

  [102/156] intraday_0105.csv.gz  in=2,025,920 out=2,025,920 elapsed=1.7s

  [103/156] intraday_0069.csv.gz  in=2,771,173 out=2,771,173 elapsed=1.9s

  [104/156] intraday_0102.csv.gz  in=3,003,258 out=3,003,258 elapsed=2.0s

  [105/156] intraday_0107.csv.gz  in=3,023,125 out=3,023,125 elapsed=2.0s

  [106/156] intraday_0106.csv.gz  in=3,043,135 out=3,043,135 elapsed=2.0s

  [107/156] intraday_0108.csv.gz  in=3,062,175 out=3,062,175 elapsed=2.0s

  [108/156] intraday_0109.csv.gz  in=3,079,631 out=3,079,631 elapsed=2.0s

  [109/156] intraday_0110.csv.gz  in=3,099,353 out=3,099,353 elapsed=2.0s

  [110/156] intraday_0112.csv.gz  in=3,101,522 out=3,101,522 elapsed=2.0s

  [111/156] intraday_0113.csv.gz  in=3,120,377 out=3,120,377 elapsed=2.0s

  [112/156] intraday_0114.csv.gz  in=3,140,120 out=3,140,120 elapsed=2.1s

  [113/156] intraday_0104.csv.gz  in=3,726,346 out=3,726,346 elapsed=2.2s

  [114/156] intraday_0115.csv.gz  in=3,745,321 out=3,745,321 elapsed=2.2s

  [115/156] intraday_0111.csv.gz  in=4,013,505 out=4,013,505 elapsed=2.3s

  [116/156] intraday_0117.csv.gz  in=4,030,681 out=4,030,681 elapsed=2.3s

  [117/156] intraday_0116.csv.gz  in=4,049,528 out=4,049,528 elapsed=2.3s

  [118/156] intraday_0118.csv.gz  in=4,067,862 out=4,067,862 elapsed=2.4s

  [119/156] intraday_0119.csv.gz  in=4,086,695 out=4,086,695 elapsed=2.4s

  [120/156] intraday_0120.csv.gz  in=4,106,177 out=4,106,177 elapsed=2.4s

  [121/156] intraday_0121.csv.gz  in=4,125,470 out=4,125,470 elapsed=2.4s

  [122/156] intraday_0122.csv.gz  in=4,145,198 out=4,145,198 elapsed=2.4s

  [123/156] intraday_0123.csv.gz  in=4,163,924 out=4,163,924 elapsed=2.4s

  [124/156] intraday_0124.csv.gz  in=4,182,997 out=4,182,997 elapsed=2.4s

  [125/156] intraday_0127.csv.gz  in=4,185,145 out=4,185,145 elapsed=2.4s

  [126/156] intraday_0125.csv.gz  in=4,204,144 out=4,204,144 elapsed=2.4s

  [127/156] intraday_0126.csv.gz  in=4,221,902 out=4,221,902 elapsed=2.4s

  [128/156] intraday_0128.csv.gz  in=4,242,000 out=4,242,000 elapsed=2.5s

  [129/156] intraday_0130.csv.gz  in=4,261,073 out=4,261,073 elapsed=2.5s

  [130/156] intraday_0129.csv.gz  in=4,281,039 out=4,281,039 elapsed=2.5s

  [131/156] intraday_0131.csv.gz  in=4,299,863 out=4,299,863 elapsed=2.5s

  [132/156] intraday_0132.csv.gz  in=4,316,710 out=4,316,710 elapsed=2.5s

  [133/156] intraday_0133.csv.gz  in=4,319,021 out=4,319,021 elapsed=2.5s

  [134/156] intraday_0134.csv.gz  in=4,338,543 out=4,338,543 elapsed=2.5s

  [135/156] intraday_0135.csv.gz  in=4,357,245 out=4,357,245 elapsed=2.5s

  [136/156] intraday_0136.csv.gz  in=4,375,988 out=4,375,988 elapsed=2.6s

  [137/156] intraday_0137.csv.gz  in=4,395,866 out=4,395,866 elapsed=2.6s

  [138/156] intraday_0139.csv.gz  in=4,397,772 out=4,397,772 elapsed=2.6s

  [139/156] intraday_0138.csv.gz  in=4,415,162 out=4,415,162 elapsed=2.6s

  [140/156] intraday_0140.csv.gz  in=4,433,539 out=4,433,539 elapsed=2.6s

  [141/156] intraday_0141.csv.gz  in=4,451,923 out=4,451,923 elapsed=2.6s

  [142/156] intraday_0142.csv.gz  in=4,471,105 out=4,471,105 elapsed=2.6s

  [143/156] intraday_0143.csv.gz  in=4,490,691 out=4,490,691 elapsed=2.6s

  [144/156] intraday_0145.csv.gz  in=4,492,539 out=4,492,539 elapsed=2.6s

  [145/156] intraday_0144.csv.gz  in=4,509,590 out=4,509,590 elapsed=2.6s

  [146/156] intraday_0146.csv.gz  in=4,528,417 out=4,528,417 elapsed=2.7s

  [147/156] intraday_0147.csv.gz  in=4,547,493 out=4,547,493 elapsed=2.7s

  [148/156] intraday_0148.csv.gz  in=4,567,631 out=4,567,631 elapsed=2.7s

  [149/156] intraday_0149.csv.gz  in=4,588,040 out=4,588,040 elapsed=2.7s

  [150/156] intraday_0151.csv.gz  in=4,590,136 out=4,590,136 elapsed=2.7s

  [151/156] intraday_0150.csv.gz  in=4,607,463 out=4,607,463 elapsed=2.7s

  [152/156] intraday_0154.csv.gz  in=4,625,848 out=4,625,848 elapsed=2.8s

  [153/156] intraday_0155.csv.gz  in=4,646,535 out=4,646,535 elapsed=2.8s

  [154/156] intraday_0152.csv.gz  in=4,665,444 out=4,665,444 elapsed=2.8s

  [155/156] intraday_0153.csv.gz  in=4,684,179 out=4,684,179 elapsed=2.8s

  [156/156] intraday_0156.csv.gz  in=4,701,677 out=4,701,677 elapsed=2.8s

✅ DONE  in=4,701,677 → out=4,701,677  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 2.8s

In [36]:
# oc_etf.parquet уже побудовано в клітинці 34 (той самий прохід по файлах).
_oc_etf_path = str(WORK_DIR / "oc_etf.parquet")
if os.path.exists(_oc_etf_path):
    df_oc = pd.read_parquet(_oc_etf_path)
else:
    df_oc = build_oc_from_intraday_folder(folder=str(ETF_DIR), out_path=_oc_etf_path)
print(df_oc.head())

  ticker        date   open  close
0   ARKK  2026-05-01  75.85  76.84
1   ARKK  2026-05-04  77.24  78.21
2   ARKK  2026-05-05  78.40  76.62
3   ARKK  2026-05-06  77.33  79.54
4   ARKK  2026-05-07  79.40  78.09

In [37]:
# Ті самі оптимізовані функції, що й у клітинці 22 — тут лише інші дефолти обгортки
# (ETF-файли замість акційних).
def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [38]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=4,701,677  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 8.6s

Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [39]:
# Та сама оптимізована add_pct_vs_prev_close_parquet із клітинки 24 —
# тут лише інші дефолти обгортки (ETF-файли, колонка Bench%).
def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",              # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [40]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=4,701,677  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 4.2s

Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [41]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий по ключах ('bench'↔'ticker', 'dt').

    Прискорення: ETF-мапа читається одним pq.read_table (лише 3 потрібні колонки)
    замість iter_batches + concat + gc; ключ 'dt' лишається рядком —
    лексикографічний порядок 'YYYY-MM-DD HH:MM:SS' збігається з хронологічним,
    тож per-row парсинг дат не потрібен (крім align_to_minute=True).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    t0 = time.time()

    # ---------- 1) Мапа з ETF-файла: (bench, dt) -> Bench% ----------
    etf_names = [f.name for f in pq.ParquetFile(etf_path).schema_arrow]
    cl = {c.lower().strip(): c for c in etf_names}
    for col in ("ticker", "dt"):
        if col not in cl:
            raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")
    val_col = cl.get("bench%") or cl.get("pct_vs_prev_close")
    if val_col is None:
        raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

    etf_map = pq.read_table(etf_path, columns=[cl["ticker"], cl["dt"], val_col]).to_pandas()
    etf_map.columns = ["bench", "dt", "Bench%"]
    etf_map["bench"] = etf_map["bench"].astype(str).str.strip().str.upper()
    etf_map["Bench%"] = pd.to_numeric(etf_map["Bench%"], errors="coerce")
    if round_decimals is not None:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    _dt_is_str = (etf_map["dt"].dtype == object) or pd.api.types.is_string_dtype(etf_map["dt"])
    if align_to_minute or not _dt_is_str:
        etf_map["dt"] = pd.to_datetime(etf_map["dt"], errors="coerce")
        if align_to_minute:
            etf_map["dt"] = etf_map["dt"].dt.floor("T")
    else:
        etf_map["dt"] = etf_map["dt"].astype(str)

    etf_map = (etf_map.dropna(subset=["dt"])
                      .sort_values(["bench", "dt"], kind="stable")
                      .drop_duplicates(subset=["bench", "dt"], keep="last")
                      .reset_index(drop=True))

    # ---------- 2) Потоково проходимо базовий файл ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0

    print(f"▶️ START merge → {out_path}", flush=True)
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        codes, cats = _ticker_codes(df["bench"])
        df["bench"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)

        _base_dt_is_str = (df["dt"].dtype == object) or pd.api.types.is_string_dtype(df["dt"])
        if align_to_minute or not _base_dt_is_str:
            df["dt"] = pd.to_datetime(df["dt"], errors="coerce")
            if align_to_minute:
                df["dt"] = df["dt"].dt.floor("T")
        else:
            df["dt"] = df["dt"].astype(str)

        merged = df.merge(etf_map, on=["bench", "dt"], how="left")

        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = [c for c in merged.columns if c != "Bench%"]
            pos = cols.index(insert_before)
            merged = merged[cols[:pos] + ["Bench%"] + cols[pos:]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [42]:
# ── ЗЛИТО В ОДИН ПРОХІД ─────────────────────────────────────────────
# Цей крок тепер робить build_final_in_one_pass у комірці 46: весь файл
# читається й пишеться ОДИН раз замість п'яти. Старий виклик лишено
# закоментованим — щоб відкотити, розкоментуй його і прибери виклик у 46.
# merge_bench_pct_from_etf(
#     base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
#     etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
#     out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
#     batch_rows=2_000_000,
#     align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
#     round_decimals=2,
#     insert_before=None,          # або, наприклад, "pct_vs_prev_close"
#     compression="snappy",
# )

In [43]:
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed


def _pick_first_existing(df: pd.DataFrame, candidates):
    cols_l = {c.lower().strip(): c for c in df.columns}
    for c in candidates:
        if c.lower() in cols_l:
            return cols_l[c.lower()]
    return None


_REPORT_FAILS = {"n": 0}
_GAP_FAILS = {"n": 0}


def _datum_request_retry(endpoint, params, *, max_retries=6, backoff=0.5):
    """Повторює запит при 429/мережевих збоях з наростаючою паузою.
    Вичерпавши спроби — кидає останній виняток."""
    import random, time
    for attempt in range(max_retries + 1):
        try:
            return DatumApi.data_request(endpoint, params)
        except Exception:
            if attempt == max_retries:
                raise
            time.sleep(backoff * (2 ** attempt) * (0.9 + 0.2 * random.random()))


def get_reports(ticker, last_n_reports, start_date, end_date):
    try:
        params = {
            "ticker": str(ticker),
            "start_move_date": str(start_date)[:10],
            "end_move_date": str(end_date)[:10],
        }
        reports_df = _datum_request_retry("/reports", params)
        if reports_df is None or reports_df.empty:
            return pd.DataFrame(columns=["ticker", "report_date"])

        date_col = _pick_first_existing(
            reports_df,
            ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"],
        )
        if date_col is None:
            return pd.DataFrame(columns=["ticker", "report_date"])

        out = reports_df.copy()
        out["report_date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
        out["ticker"] = str(ticker).upper()
        out = out.dropna(subset=["report_date"])
        out = out.sort_values("report_date").tail(int(last_n_reports))
        return out[["ticker", "report_date"]].reset_index(drop=True)
    except Exception as e:
        _REPORT_FAILS["n"] += 1
        print(f"Report fetch failed for {ticker}: {e}")
        return pd.DataFrame(columns=["ticker", "report_date"])


def get_reports_for_tickers(tickers_df, start_date, end_date, last_n_reports=20,
                            max_workers=8, max_fail_ratio=0.15):
    # 16 потоків без пауз давали суцільні 429; з retry вистачає меншого числа
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    parts = []
    _REPORT_FAILS["n"] = 0

    # Ті самі репорти вже завантажила комірка 11. Беремо їх лише коли вікно,
    # last_n_reports і набір тикерів збігаються; інакше — звичайний фетч.
    _c = globals().get("CRACEN_FETCH_CACHE") or {}
    if (_c.get("window") == (str(start_date)[:10], str(end_date)[:10])
            and _c.get("last_n_reports") == int(last_n_reports)
            and set(tickers) <= _c.get("tickers", set())):
        _r = _c["reports"].rename(columns={"date": "report_date"})
        _r = (_r[_r["ticker"].isin(tickers)]
                .drop_duplicates(["ticker", "report_date"]).reset_index(drop=True))
        print(f"Reports: узято з кешу комірки 11 ({len(_r)} рядків), фетч пропущено")
        return _r, _r.groupby("ticker")["report_date"].apply(set).to_dict()

    def fetch(t):
        return get_reports(ticker=t, last_n_reports=last_n_reports, start_date=start_date, end_date=end_date)

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Reports"):
            rep = f.result()
            if rep is not None and not rep.empty:
                parts.append(rep)

    if tickers and _REPORT_FAILS["n"] / len(tickers) > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив на {_REPORT_FAILS['n']} з {len(tickers)} тикерів "
            f"({_REPORT_FAILS['n'] / len(tickers) * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Репорти вийшли б неповними."
        )

    if not parts:
        return pd.DataFrame(columns=["ticker", "report_date"]), {}

    reports = pd.concat(parts, ignore_index=True).drop_duplicates(["ticker", "report_date"])
    report_days_map = reports.groupby("ticker")["report_date"].apply(set).to_dict()
    return reports, report_days_map


def get_gaps_for_tickers_excluding_reports(tickers_df, start_date, end_date, report_days_map,
                                           max_workers=8, max_fail_ratio=0.15):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    _GAP_FAILS["n"] = 0
    _GAP_FAILS["empty"] = 0

    # Кеш комірки 11 беремо для КОЖНОГО тикера, що в ньому є, а докачуємо лише відсутні. Раніше кеш
    # діяв за умови set(tickers) <= cache: один зайвий тикер викидав увесь кеш, і ~7000 тикерів
    # перекачувались наново; порожні відповіді API при цьому мовчки губились (fetch -> None без
    # лічильника збою) - так sigma лишилась лише у ~1200 тикерів (алфавітний хвіст STC..ZYME).
    _c = globals().get("CRACEN_FETCH_CACHE") or {}
    cached_part = None
    to_fetch = tickers
    if _c.get("window") == (str(start_date)[:10], str(end_date)[:10]) and "gaps" in _c:
        _have = set(_c.get("tickers", set()))
        _use = [t for t in tickers if t in _have]
        _g = _c["gaps"]
        _g = _g[_g["ticker"].isin(_use)].copy()
        _rep = pd.DataFrame([(t, d) for t, ds in (report_days_map or {}).items() for d in ds],
                            columns=["ticker", "date"])
        if len(_rep):
            _g = _g.merge(_rep.assign(_r=1), on=["ticker", "date"], how="left")
            _g = _g[_g["_r"].isna()].drop(columns="_r")
        cached_part = _g.reset_index(drop=True)
        to_fetch = [t for t in tickers if t not in _have]
        print(f"Gaps: з кешу комірки 11 {len(_use)} тикерів ({len(cached_part)} рядків), докачуємо {len(to_fetch)}")
        if not to_fetch:
            return cached_part

    def fetch(t):
        params = {
            "ticker": t,
            "start_date": str(start_date)[:10],
            "end_date": str(end_date)[:10],
            "format": "json_records",
        }
        try:
            df_gap = _datum_request_retry("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                # порожня відповідь під лімітом виглядає так само, як тикер без гепів - перепитуємо раз
                import time
                time.sleep(1.0)
                df_gap = _datum_request_retry("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                _GAP_FAILS["empty"] = _GAP_FAILS.get("empty", 0) + 1
                return None

            date_col = _pick_first_existing(df_gap, ["date", "move_date", "dt", "datetime", "day"])
            if date_col is None:
                return None

            out = df_gap.copy()
            out["ticker"] = out["ticker"].astype(str).str.upper() if "ticker" in out.columns else t
            out["date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
            out["gap"] = pd.to_numeric(out.get("gap"), errors="coerce")
            out = out.dropna(subset=["date", "gap"])

            report_days = report_days_map.get(t, set())
            if report_days:
                out = out[~out["date"].isin(report_days)]

            return out if not out.empty else None
        except Exception as e:
            _GAP_FAILS["n"] += 1
            print(f"Gap fetch failed for {t}: {e}")
            return None

    all_results = []
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in to_fetch}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Gaps (ex-reports)"):
            result = f.result()
            if result is not None:
                all_results.append(result)

    _bad = _GAP_FAILS["n"] + _GAP_FAILS.get("empty", 0)
    if to_fetch and _bad / len(to_fetch) > max_fail_ratio:
        raise RuntimeError(
            f"API відмовив/повернув порожньо на {_bad} з {len(to_fetch)} тикерів "
            f"({_bad / len(to_fetch) * 100:.1f}% > {max_fail_ratio * 100:.0f}%). "
            "Гепи вийшли б неповними."
        )

    if cached_part is not None:
        all_results.append(cached_part)
    if all_results:
        return pd.concat(all_results, ignore_index=True)
    return pd.DataFrame(columns=["ticker", "date", "gap"])


def add_rolling_sigma_cap(
    df,
    value_col,
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=None,
):
    """Rolling std по попередньому вікну з обрізанням хвостів на квантилі cap_q.

    Раніше це був rolling(...).apply(python_func) — окремий виклик Python на кожне
    вікно кожного тікера. Тепер вікна будуються через sliding_window_view і квантиль/
    clip/std рахуються одразу по всій матриці вікон групи (чисто numpy).
    Результат збігається з попередньою реалізацією до 1e-12.
    """
    if min_periods is None:
        min_periods = window

    out = df.sort_values([group_col, date_col], kind="stable").copy()
    col = f"{value_col}_sigma_{window}d_cap"

    # Рідкісний випадок min_periods != window має іншу семантику (часткові вікна) —
    # там лишаємо стару, повільну, але точну реалізацію.
    if min_periods != window:
        def compute_sigma(s):
            x = s.shift(1)

            def f(arr):
                arr = arr[~np.isnan(arr)]
                if len(arr) < min_periods:
                    return np.nan
                cap = np.quantile(np.abs(arr), cap_q)
                arr_capped = np.clip(arr, -cap, cap)
                return np.std(arr_capped, ddof=1)

            return x.rolling(window, min_periods=min_periods).apply(f, raw=True)

        out[col] = out.groupby(group_col)[value_col].transform(compute_sigma)
        return out

    vals = pd.to_numeric(out[value_col], errors="coerce").to_numpy(dtype="float64")
    codes, _ = pd.factorize(out[group_col], sort=False)
    res = np.full(vals.shape, np.nan)

    order = np.argsort(codes, kind="stable")
    bounds = np.flatnonzero(np.diff(codes[order])) + 1
    for sl in np.split(order, bounds):
        n = sl.size
        if n <= window:
            continue
        x = vals[sl]
        # вікно з ПОПЕРЕДНІХ значень (еквівалент shift(1) у старій версії)
        w = np.lib.stride_tricks.sliding_window_view(x[:-1], window)   # (n-window, window)
        cap = np.quantile(np.abs(w), cap_q, axis=1, keepdims=True)
        res[sl[window:]] = np.clip(w, -cap, cap).std(axis=1, ddof=1)

    out[col] = res
    return out


# 1) Report days in the working window
reports_df, report_days_map = get_reports_for_tickers(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
)
print("Report rows:", len(reports_df))

# 2) Gaps without report days
df_gaps_all = get_gaps_for_tickers_excluding_reports(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    report_days_map=report_days_map,
)
print("Rows in gaps (without report days):", len(df_gaps_all))

# 3) Rolling sigma
sigma_daily = add_rolling_sigma_cap(
    df=df_gaps_all,
    value_col="gap",
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.8,
    min_periods=20,
)

sigma_col = "gap_sigma_20d_cap"

std_by_ticker = (
    sigma_daily.dropna(subset=[sigma_col])
    .sort_values(["ticker", "date"])
    .groupby("ticker", as_index=False)
    .tail(1)[["ticker", sigma_col]]
    .rename(columns={sigma_col: "sigma"})
    .reset_index(drop=True)
)

# 4) Добір sigma для тикерів, що випали: гепи з oc.parquet (open / попередній close - те саме, з чого
# рахується Stack%), ті самі дні репортів, те саме вікно і та сама формула.
_all_tk = set(TICKERS["ticker"].dropna().astype(str).str.upper())
_missing = sorted(_all_tk - set(std_by_ticker["ticker"]))
print(f"Sigma з API-гепів: {len(std_by_ticker)} з {len(_all_tk)} тикерів, бракує {len(_missing)}")
if _missing:
    _oc = pd.read_parquet(WORK_DIR / "oc.parquet", columns=["ticker", "date", "open", "close"])
    _oc["ticker"] = _oc["ticker"].astype(str).str.upper()
    _oc["date"] = pd.to_datetime(_oc["date"], errors="coerce").dt.strftime("%Y-%m-%d")
    _oc = _oc.dropna(subset=["date"]).sort_values(["ticker", "date"], kind="stable")
    _oc["gap"] = (pd.to_numeric(_oc["open"], errors="coerce")
                  / pd.to_numeric(_oc.groupby("ticker")["close"].shift(1), errors="coerce") - 1.0) * 100.0
    _fb = _oc[_oc["ticker"].isin(_missing)
              & (_oc["date"] >= str(start_date_str)[:10]) & (_oc["date"] <= str(end_date_str)[:10])]
    _fb = _fb.replace([np.inf, -np.inf], np.nan).dropna(subset=["gap"])
    _rep_fb = pd.DataFrame([(t, d) for t, ds in report_days_map.items() for d in ds], columns=["ticker", "date"])
    if len(_rep_fb):
        _fb = _fb.merge(_rep_fb.assign(_r=1), on=["ticker", "date"], how="left")
        _fb = _fb[_fb["_r"].isna()].drop(columns="_r")
    _fb_sigma = add_rolling_sigma_cap(_fb[["ticker", "date", "gap"]], value_col="gap", window=20,
                                      group_col="ticker", date_col="date", cap_q=0.8, min_periods=20)
    _fb_std = (_fb_sigma.dropna(subset=[sigma_col]).sort_values(["ticker", "date"])
               .groupby("ticker", as_index=False).tail(1)[["ticker", sigma_col]]
               .rename(columns={sigma_col: "sigma"}))
    std_by_ticker = pd.concat([std_by_ticker, _fb_std], ignore_index=True).drop_duplicates("ticker", keep="first")
    print(f"Добрано з oc.parquet: {len(_fb_std)}")

_cov = len(std_by_ticker) / max(1, len(_all_tk))
print(f"Tickers with sigma: {len(std_by_ticker)} з {len(_all_tk)} ({_cov:.1%})")
if _cov < 0.85:
    raise RuntimeError(f"sigma є лише у {_cov:.1%} тикерів - гепи вийшли неповними, final.parquet не збирати")
std_by_ticker.head()

Reports: узято з кешу комірки 11 (4104 рядків), фетч пропущено
Report rows: 4104

Gaps: з кешу комірки 11 7050 тикерів (445849 рядків), докачуємо 0
Rows in gaps (without report days): 445849

Sigma з API-гепів: 6974 з 7050 тикерів, бракує 76

Добрано з oc.parquet: 0
Tickers with sigma: 6974 з 7050 (98.9%)

  ticker     sigma
0      A  0.595598
1     AA  0.906941
2   AAAU  0.835609
3   AACG  3.128495
4   AADX  0.677228

In [44]:
std_by_ticker

     ticker     sigma
0         A  0.595598
1        AA  0.906941
2      AAAU  0.835609
3      AACG  3.128495
4      AADX  0.677228
...     ...       ...
6969   ZVOL  0.481089
6970   ZVRA  0.378021
6971    ZWS  0.754290
6972   ZYBT  2.150252
6973   ZYME  0.630254

[6974 rows x 2 columns]

In [45]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"] = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet.

    Як і в клітинці 28: нормалізація тікера і пошук у мапі йдуть по унікальних
    значеннях, а не по кожному з мільйонів рядків; per-batch merge не потрібен.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)
    sd = dict(zip(sigma_map["ticker"], sigma_map["sigma"]))

    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}", flush=True)
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["sigma"] = _map_by_ticker(codes, cats, sd, numeric=True)

        cols = [c for c in df.columns if c != "sigma"]
        if insert_before and insert_before in cols:
            idx = cols.index(insert_before)
            df = df[cols[:idx] + ["sigma"] + cols[idx:]]
        else:
            df = df[cols + ["sigma"]]

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s", flush=True)

    if writer is not None:
        writer.close()

    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s", flush=True)
    return out_path

In [46]:
def build_final_in_one_pass(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    corrbeta_parquet_path: str,
    etf_parquet_path: str,
    out_parquet_path: str,
    *,
    sigma_df=None,
    sigma_path=None,
    batch_rows: int = 2_000_000,
    round_decimals=4,
    stack_round_to=None,
    bench_round_decimals=2,
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """Один потоковий прохід замість п'яти: oc-мердж → Stack% → bench/corr/beta
    → Bench% → sigma. Замінює merge_intraday_and_oc_to_file +
    add_pct_vs_prev_close_parquet + attach_bench_corr_beta_parquet +
    merge_bench_pct_from_etf + add_sigma_by_ticker_to_parquet.

    Результат побайтово збігається з ланцюжком; економія — у тому, що ~3 ГБ
    читаються й пишуться один раз, а не шість.
    """
    t0 = time.time()

    # ---------- side-входи: готуються ОДИН раз ----------
    oc_prepared = _prep_oc_prev_close(pq.read_table(oc_parquet_path).to_pandas())

    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if mapping.empty:
        raise ValueError(
            f"Мапа bench/corr/beta порожня: {corrbeta_parquet_path}. "
            "Крок побудови x_to_best_etf_by_lvl3 не дав жодного рядка."
        )
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)
    m_bench = dict(zip(mapping["ticker"], mapping["bench"]))
    m_corr = dict(zip(mapping["ticker"], mapping["corr"]))
    m_beta = dict(zip(mapping["ticker"], mapping["beta"]))

    etf_names = [f.name for f in pq.ParquetFile(etf_parquet_path).schema_arrow]
    cl = {c.lower().strip(): c for c in etf_names}
    val_col = cl.get("bench%") or cl.get("pct_vs_prev_close")
    etf_map = pq.read_table(etf_parquet_path,
                            columns=[cl["ticker"], cl["dt"], val_col]).to_pandas()
    etf_map.columns = ["bench", "dt", "Bench%"]
    etf_map["bench"] = etf_map["bench"].astype(str).str.strip().str.upper()
    etf_map["Bench%"] = pd.to_numeric(etf_map["Bench%"], errors="coerce")
    if bench_round_decimals is not None:
        etf_map["Bench%"] = etf_map["Bench%"].round(bench_round_decimals)
    etf_map["dt"] = etf_map["dt"].astype(str)
    etf_map = (etf_map.dropna(subset=["dt"])
                      .sort_values(["bench", "dt"], kind="stable")
                      .drop_duplicates(subset=["bench", "dt"], keep="last")
                      .reset_index(drop=True))

    sig = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    m_sigma = dict(zip(sig["ticker"], sig["sigma"]))

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    ORDER = ["ticker", "dt", "o", "h", "l", "c", "v", "date", "open", "prev_close",
             "Stack%", "bench", "corr", "beta", "Bench%", "sigma"]

    pf = pq.ParquetFile(intraday_parquet_path)
    writer = None
    total_rows = 0
    print(f"▶️ START one-pass → {out_parquet_path}", flush=True)

    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # 1) день + open/prev_close (ключ — сирий ticker, як у ланцюжку)
        df = df[df["dt"].notna()]
        df = df.assign(date=_date_from_dt(df["dt"]))
        df = df.merge(oc_prepared, on=["ticker", "date"], how="left")
        df["prev_close"] = _rebase_prev_close_after_session_close(df)

        # 2) Stack%
        num = pd.to_numeric(df["o"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        den = pd.to_numeric(df["prev_close"], errors="coerce").to_numpy(dtype="float64", na_value=np.nan)
        with np.errstate(divide="ignore", invalid="ignore"):
            pct = np.where(den == 0, np.nan, num / den - 1.0) * 100.0
        if stack_round_to is not None:
            pct = np.round(pct, int(stack_round_to))
        df["Stack%"] = pct

        # 3) bench/corr/beta (тут ticker нормалізується — як у ланцюжку)
        codes, cats = _ticker_codes(df["ticker"])
        df["ticker"] = _expand(np.asarray(cats.to_numpy(), dtype=object), codes, None)
        df["bench"] = _map_by_ticker(codes, cats, m_bench, numeric=False)
        df["corr"] = _map_by_ticker(codes, cats, m_corr, numeric=True)
        df["beta"] = _map_by_ticker(codes, cats, m_beta, numeric=True)

        # 4) sigma — теж по codes/cats, тому рахуємо ДО мерджа
        df["sigma"] = _map_by_ticker(codes, cats, m_sigma, numeric=True)

        # 5) Bench% по (bench, dt); bench лишається object для мерджа
        df["dt"] = df["dt"].astype(str)
        df = df.merge(etf_map, on=["bench", "dt"], how="left")

        # string-dtype один раз наприкінці: тримає тип bench стабільним між батчами
        df["bench"] = pd.array(df["bench"], dtype="string")

        df = df[[c for c in ORDER if c in df.columns]]
        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        elif not table.schema.equals(writer.schema, check_metadata=False):
            table = table.cast(writer.schema)
        writer.write_table(table)

        total_rows += len(df)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,} elapsed={time.time()-t0:,.1f}s", flush=True)
        del df, table, batch
        gc.collect()

    if writer is not None:
        writer.close()
    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path} in {time.time()-t0:,.1f}s", flush=True)
    return out_parquet_path

In [47]:
# std_by_ticker columns: ['ticker', 'sigma']
# Один прохід замість п'яти: oc-мердж → Stack% → bench/corr/beta → Bench% → sigma.
# Замінює комірки 23, 25, 29, 41 і колишній add_sigma_by_ticker_to_parquet.
sigma_out_path = build_final_in_one_pass(
    intraday_parquet_path=str(WORK_DIR / "premarket_rows.parquet"),
    oc_parquet_path=str(WORK_DIR / "oc.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    etf_parquet_path=str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    sigma_df=std_by_ticker,
    batch_rows=2_000_000,
    round_decimals=4,
    bench_round_decimals=2,
    compression="snappy",
)

# Validation: output parquet must contain sigma matching std_by_ticker
check_df = pd.read_parquet(sigma_out_path, columns=["ticker", "sigma"])
if "sigma" not in check_df.columns:
    raise KeyError("Column 'sigma' is missing in parquet after merge")

file_sigma = (
    check_df.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

exp_sigma = (
    std_by_ticker.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

common = file_sigma.index.intersection(exp_sigma.index)
if len(common) == 0:
    raise ValueError("No common tickers to validate sigma between std_by_ticker and parquet")

diff = (file_sigma.loc[common] - exp_sigma.loc[common]).abs()
max_diff = float(diff.max()) if len(diff) else 0.0
print("sigma_out_path:", sigma_out_path)
print("tickers in std_by_ticker:", len(exp_sigma))
print("tickers checked in parquet:", len(common))
print("max |file_sigma - expected_sigma|:", max_diff)

▶️ START one-pass → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000 elapsed=43.6s

[batch   10] rows=20,000,000 elapsed=78.2s

[batch   15] rows=30,000,000 elapsed=113.0s

[batch   20] rows=40,000,000 elapsed=147.7s

[batch   25] rows=50,000,000 elapsed=182.4s

[batch   30] rows=60,000,000 elapsed=217.6s

[batch   35] rows=70,000,000 elapsed=252.7s

[batch   40] rows=80,000,000 elapsed=287.7s

[batch   45] rows=90,000,000 elapsed=322.9s

[batch   50] rows=100,000,000 elapsed=358.4s

[batch   55] rows=110,000,000 elapsed=393.8s

✅ DONE rows=113,089,395 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet in 405.6s

sigma_out_path: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
tickers in std_by_ticker: 6974
tickers checked in parquet: 6972
max |file_sigma - expected_sigma|: 0.0

In [48]:
peek_parquet(str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"), n=21150)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 113,089,395
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 317/21150
NaN у 'corr' (у прев'ю): 317/21150
NaN у 'beta' (у прев'ю): 317/21150

Перші рядки:

      ticker                   dt           o           h           l           c          v        date    open  prev_close        Stack% bench    corr    beta  Bench%     sigma
0          A  2026-07-24 00:04:00  140.000000  140.000000  140.000000  140.000000        5.0  2026-07-24  140.46      139.73  1.932298e-01   XLV  0.5234  0.4964     NaN  0.595598
1          A  2026-07-24 00:05:00  140.039993  140.039993  140.039993  140.039993        5.0  2026-07-24  140.46      139.73  2.218516e-01   XLV  0.5234  0.4964     NaN  0.595598
2          A  2026-07-24 07:00:00  138.169998  138.169998  138.169998  138.169998      100.0  2026-07-24  140.46      139.73 -1.116440e+00   XLV  0.5234  0.4964     NaN  0.595598
3          A  2026-07-24 08:13:00  139.699997  139.699997  139.699997  139.699997      150.0  2026-07-24  140.46      139.73 -2.147216e-02   XLV  0.5234  0.4964     NaN  0.595598
4          A  2026-07-24 09:30:00  140.460007  140.460007  139.735001  139.735001    15257.0  2026-07-24  140.46      139.73  5.224409e-01   XLV  0.5234  0.4964    0.66  0.595598
5          A  2026-07-24 09:31:00  139.815002  140.479996  139.815002  140.479996      821.0  2026-07-24  140.46      139.73  6.083335e-02   XLV  0.5234  0.4964    0.71  0.595598
6          A  2026-07-24 09:32:00  140.479996  140.880005  140.184998  140.365005     7383.0  2026-07-24  140.46      139.73  5.367464e-01   XLV  0.5234  0.4964    0.87  0.595598
7          A  2026-07-24 09:33:00  140.365005  140.365005  139.494995  139.494995     3858.0  2026-07-24  140.46      139.73  4.544518e-01   XLV  0.5234  0.4964    0.83  0.595598
8          A  2026-07-24 09:34:00  138.970001  138.970001  138.839996  138.839996     1161.0  2026-07-24  140.46      139.73 -5.439052e-01   XLV  0.5234  0.4964    0.61  0.595598
9          A  2026-07-24 09:35:00  138.970001  139.119995  138.740005  139.005005     4729.0  2026-07-24  140.46      139.73 -5.439052e-01   XLV  0.5234  0.4964    0.18  0.595598
10         A  2026-07-24 09:36:00  138.860001  139.169998  138.860001  139.169998      994.0  2026-07-24  140.46      139.73 -6.226289e-01   XLV  0.5234  0.4964    0.26  0.595598
11         A  2026-07-24 09:37:00  139.035294  139.759995  139.035294  139.759995     1635.0  2026-07-24  140.46      139.73 -4.971777e-01   XLV  0.5234  0.4964    0.38  0.595598
12         A  2026-07-24 09:38:00  139.535004  139.679993  139.479996  139.630005      563.0  2026-07-24  140.46      139.73 -1.395522e-01   XLV  0.5234  0.4964    0.50  0.595598
13         A  2026-07-24 09:39:00  139.559998  139.559998  139.369995  139.369995      800.0  2026-07-24  140.46      139.73 -1.216650e-01   XLV  0.5234  0.4964    0.67  0.595598
14         A  2026-07-24 09:40:00  139.214996  139.279999  139.110001  139.110001     1482.0  2026-07-24  140.46      139.73 -3.685706e-01   XLV  0.5234  0.4964    0.55  0.595598
15         A  2026-07-24 09:41:00  139.199997  139.199997  139.104996  139.110001     1045.0  2026-07-24  140.46      139.73 -3.793051e-01   XLV  0.5234  0.4964    0.69  0.595598
16         A  2026-07-24 09:42:00  139.039993  139.179993  139.039993  139.179993      487.0  2026-07-24  140.46      139.73 -4.938143e-01   XLV  0.5234  0.4964    0.76  0.595598
17         A  2026-07-24 09:43:00  139.039993  139.179993  139.039993  139.059998     1196.0  2026-07-24  140.46      139.73 -4.938143e-01   XLV  0.5234  0.4964    0.66  0.595598
18         A  2026-07-24 09:44:00  139.014999  139.059998  138.860001  138.949997      900.0  2026-07-24  140.46      139.73 -5.117016e-01   XLV  0.5234  0.4964    0.65  0.595598
19         A  2026-07-24 09:45:00  138.949997  139.229996  138.949997  139.027496     1200.0  2026-07-24  140.46      139.73 -5.582216e-01   XLV  0.5234  0.4964    0.59  0.595598
20         A  2026-07-24 09:46:00  139.449905  139.461563  139.419998  139.461563     1775.0  2026-07-24  140.46      139.73 -2.004542e-01   XLV  0.5234  0.4964    0.83  0.595598
21         A  2026-07-24 09:47:00  139.520004  139.625000  139.360107  139.479996     2356.0  2026-07-24  140.46      139.73 -1.502868e-01   XLV  0.5234  0.4964    0.89  0.595598
22         A  2026-07-24 09:48:00  139.410004  139.735001  139.410004  139.639999      600.0  2026-07-24  140.46      139.73 -2.290105e-01   XLV  0.5234  0.4964    0.94  0.595598
23         A  2026-07-24 09:49:00  139.580002  139.625000  139.270004  139.360001      600.0  2026-07-24  140.46      139.73 -1.073486e-01   XLV  0.5234  0.4964    0.94  0.595598
24         A  2026-07-24 09:50:00  139.399994  139.399994  139.169998  139.169998      300.0  2026-07-24  140.46      139.73 -2.361741e-01   XLV  0.5234  0.4964    0.72  0.595598
25         A  2026-07-24 09:51:00  139.220001  139.220001  139.184998  139.184998      400.0  2026-07-24  140.46      139.73 -3.649887e-01   XLV  0.5234  0.4964    0.81  0.595598
26         A  2026-07-24 09:52:00  139.184998  139.339996  139.184998  139.339996      300.0  2026-07-24  140.46      139.73 -3.900397e-01   XLV  0.5234  0.4964    0.82  0.595598
27         A  2026-07-24 09:53:00  139.130005  139.309998  139.020004  139.309998     1300.0  2026-07-24  140.46      139.73 -4.293961e-01   XLV  0.5234  0.4964    0.84  0.595598
28         A  2026-07-24 09:54:00  139.250000  139.380005  139.169998  139.240005     3248.0  2026-07-24  140.46      139.73 -3.435196e-01   XLV  0.5234  0.4964    0.81  0.595598
29         A  2026-07-24 09:55:00  139.029999  139.029999  138.699997  138.770004     1241.0  2026-07-24  140.46      139.73 -5.009670e-01   XLV  0.5234  0.4964    0.81  0.595598
30         A  2026-07-24 09:56:00  138.770004  138.804993  138.529999  138.804993      609.0  2026-07-24  140.46      139.73 -6.870362e-01   XLV  0.5234  0.4964    0.79  0.595598
31         A  2026-07-24 09:57:00  138.809998  138.809998  138.809998  138.809998      100.0  2026-07-24  140.46      139.73 -6.584144e-01   XLV  0.5234  0.4964    0.71  0.595598
32         A  2026-07-24 09:58:00  138.940002  138.940002  138.761993  138.761993     1150.0  2026-07-24  140.46      139.73 -5.653743e-01   XLV  0.5234  0.4964    0.66  0.595598
33         A  2026-07-24 09:59:00  138.725006  138.910004  138.725006  138.779999     1157.0  2026-07-24  140.46      139.73 -7.192399e-01   XLV  0.5234  0.4964    0.65  0.595598
34         A  2026-07-24 10:00:00  138.910004  138.910004  138.824997  138.872498     1400.0  2026-07-24  140.46      139.73 -5.868434e-01   XLV  0.5234  0.4964    0.66  0.595598
35         A  2026-07-24 10:01:00  138.830002  138.875000  138.720001  138.720001     2406.0  2026-07-24  140.46      139.73 -6.440980e-01   XLV  0.5234  0.4964    0.66  0.595598
36         A  2026-07-24 10:02:00  138.632507  138.789993  138.559998  138.759995     2596.0  2026-07-24  140.46      139.73 -7.854381e-01   XLV  0.5234  0.4964    0.61  0.595598
37         A  2026-07-24 10:03:00  138.710007  138.830002  138.675003  138.679993     1320.0  2026-07-24  140.46      139.73 -7.299744e-01   XLV  0.5234  0.4964    0.69  0.595598
38         A  2026-07-24 10:04:00  138.679993  138.679993  138.320007  138.339996     3209.0  2026-07-24  140.46      139.73 -7.514545e-01   XLV  0.5234  0.4964    0.67  0.595598
39         A  2026-07-24 10:05:00  138.339996  138.539993  138.339996  138.479996      654.0  2026-07-24  140.46      139.73 -9.947783e-01   XLV  0.5234  0.4964    0.65  0.595598
40         A  2026-07-24 10:06:00  138.500000  138.531906  138.425003  138.425003      317.0  2026-07-24  140.46      139.73 -8.802691e-01   XLV  0.5234  0.4964    0.64  0.595598
41         A  2026-07-24 10:07:00  138.425003  138.550003  138.140106  138.440002     1475.0  2026-07-24  140.46      139.73 -9.339419e-01   XLV  0.5234  0.4964    0.70  0.595598
42         A  2026-07-24 10:08:00  138.520004  138.669998  138.520004  138.669998      600.0  2026-07-24  140.46      139.73 -8.659527e-01   XLV  0.5234  0.4964    0.69  0.595598
43         A  2026-07-24 10:09:00  138.589996  139.035004  138.589996  138.910004     2530.0  2026-07-24  140.46      139.73 -8.158618e-01   XLV  0.5234  0.4964    0.77  0.595598
44         A  2026-07-24 10:10:00  138.824997  138.865005  138.824997  138.865005      800.0  2026-07-24  140.46      139.73 -6.476798e-01   XLV  0.5234  0.4964    0.77  0.595598
45         A  2026-07-24 10:11:00  138.850006  138.884995  138.804993  138.884995      621.0  2026-07-24  140.46      139.73 -6.297816e-01   XLV  0.5234  0.4964    0.82  0.595598
46         A  2026-07-24 10:13:00  138.570007  138.570007  138.440002  138.464996     1701.0  2026-07-24  140.46      139.73 -8.301672e-01   XLV  0.5234  0.4964    0.81  0.595598
47         A  2026-07-24 10:14:00  138.419998  138.445007  138.419998  138.445007      500.0  2026-07-24  140.46      139.73 -9.375237e-01   XLV  0.5234  0.4964    0.83  0.595598
48         A  2026-07-24 10:15:00  138.419998  138.539993  138.350098  138.440002     1284.0  2026-07-24  140.46      139.73 -9.375237e-01   XLV  0.5234  0.4964    0.94  0.595598
49         A  2026-07-24 10:16:00  138.350006  138.470001  138.350006  138.470001      300.0  2026-07-24  140.46      139.73 -9.876146e-01   XLV  0.5234  0.4964    1.02  0.595598
50         A  2026-07-24 10:17:00  138.460007  138.460007  138.279999  138.419998     1596.0  2026-07-24  140.46      139.73 -9.088909e-01   XLV  0.5234  0.4964    1.08  0.595598
51         A  2026-07-24 10:18:00  138.350006  138.350006  138.350006  138.350006      100.0  2026-07-24  140.46      139.73 -9.876146e-01   XLV  0.5234  0.4964    1.08  0.595598
52         A  2026-07-24 10:19:00  138.419998  138.529999  138.354996  138.410004     2153.0  2026-07-24  140.46      139.73 -9.375237e-01   XLV  0.5234  0.4964    1.06  0.595598
53         A  2026-07-24 10:20:00  138.500000  138.639999  138.500000  138.639999     1216.0  2026-07-24  140.46      139.73 -8.802691e-01   XLV  0.5234  0.4964    1.07  0.595598
54         A  2026-07-24 10:21:00  138.615005  138.785004  138.610001  138.710007     1100.0  2026-07-24  140.46      139.73 -7.979636e-01   XLV  0.5234  0.4964    0.99  0.595598
55         A  2026-07-24 10:22:00  138.759995  138.759995  138.759995  138.759995      200.0  2026-07-24  140.46      139.73 -6.941999e-01   XLV  0.5234  0.4964    0.95  0.595598
56         A  2026-07-24 10:23:00  138.789993  138.875000  138.789993  138.869995     1600.0  2026-07-24  140.46      139.73 -6.727308e-01   XLV  0.5234  0.4964    0.99  0.595598
57         A  2026-07-24 10:24:00  138.779999  138.779999  138.547806  138.619995      748.0  2026-07-24  140.46      139.73 -6.798835e-01   XLV  0.5234  0.4964    0.96  0.595598
58         A  2026-07-24 10:26:00  138.740005  138.880005  138.740005  138.770004      805.0  2026-07-24  140.46      139.73 -7.085053e-01   XLV  0.5234  0.4964    1.05  0.595598
59         A  2026-07-24 10:27:00  138.889999  138.889999  138.750000  138.750000     1000.0  2026-07-24  140.46      139.73 -6.011598e-01   XLV  0.5234  0.4964    1.02  0.595598
60         A  2026-07-24 10:28:00  138.750000  138.750000  138.750000  138.750000      100.0  2026-07-24  140.46      139.73 -7.013526e-01   XLV  0.5234  0.4964    0.98  0.595598
61         A  2026-07-24 10:29:00  138.755005  138.755005  138.520004  138.520004      700.0  2026-07-24  140.46      139.73 -6.977708e-01   XLV  0.5234  0.4964    0.94  0.595598
62         A  2026-07-24 10:30:00  138.485001  138.600006  138.485001  138.550003     3013.0  2026-07-24  140.46      139.73 -8.910036e-01   XLV  0.5234  0.4964    0.92  0.595598
63         A  2026-07-24 10:31:00  138.550003  138.570007  138.259995  138.399994     6139.0  2026-07-24  140.46      139.73 -8.444836e-01   XLV  0.5234  0.4964    1.01  0.595598
64         A  2026-07-24 10:32:00  138.479996  138.589996  138.449997  138.589996     1600.0  2026-07-24  140.46      139.73 -8.945855e-01   XLV  0.5234  0.4964    1.00  0.595598
65         A  2026-07-24 10:33:00  138.552505  138.552505  138.475006  138.475006      500.0  2026-07-24  140.46      139.73 -8.426927e-01   XLV  0.5234  0.4964    1.02  0.595598
66         A  2026-07-24 10:34:00  138.449997  138.449997  138.222504  138.222504     1119.0  2026-07-24  140.46      139.73 -9.160546e-01   XLV  0.5234  0.4964    1.02  0.595598
67         A  2026-07-24 10:35:00  138.214996  138.240005  138.214996  138.240005      700.0  2026-07-24  140.46      139.73 -1.084237e+00   XLV  0.5234  0.4964    0.94  0.595598
68         A  2026-07-24 10:36:00  138.214996  138.410004  138.214996  138.285004     3621.0  2026-07-24  140.46      139.73 -1.084237e+00   XLV  0.5234  0.4964    0.84  0.595598
69         A  2026-07-24 10:37:00  138.244995  138.247498  138.244995  138.244995     1300.0  2026-07-24  140.46      139.73 -1.062767e+00   XLV  0.5234  0.4964    0.81  0.595598
70         A  2026-07-24 10:38:00  138.235001  138.235001  138.139999  138.154999     2800.0  2026-07-24  140.46      139.73 -1.069920e+00   XLV  0.5234  0.4964    0.85  0.595598
71         A  2026-07-24 10:39:00  138.149994  138.229996  138.149994  138.229996      900.0  2026-07-24  140.46      139.73 -1.130757e+00   XLV  0.5234  0.4964    0.84  0.595598
72         A  2026-07-24 10:40:00  138.330002  138.460007  138.330002  138.460007      500.0  2026-07-24  140.46      139.73 -1.001931e+00   XLV  0.5234  0.4964    0.83  0.595598
73         A  2026-07-24 10:41:00  138.520004  138.520004  138.520004  138.520004      100.0  2026-07-24  140.46      139.73 -8.659527e-01   XLV  0.5234  0.4964    0.90  0.595598
74         A  2026-07-24 10:42:00  138.360107  138.589996  138.360107  138.485001     1414.0  2026-07-24  140.46      139.73 -9.803854e-01   XLV  0.5234  0.4964    0.92  0.595598
75         A  2026-07-24 10:43:00  138.589996  138.600006  138.470001  138.470001     1200.0  2026-07-24  140.46      139.73 -8.158618e-01   XLV  0.5234  0.4964    0.86  0.595598
76         A  2026-07-24 10:44:00  138.550003  138.550003  138.279999  138.335007     1290.0  2026-07-24  140.46      139.73 -8.444836e-01   XLV  0.5234  0.4964    0.77  0.595598
77         A  2026-07-24 10:45:00  138.300003  138.300003  138.220001  138.220001      300.0  2026-07-24  140.46      139.73 -1.023400e+00   XLV  0.5234  0.4964    0.69  0.595598
78         A  2026-07-24 10:46:00  138.240005  138.240005  138.184998  138.214996      900.0  2026-07-24  140.46      139.73 -1.066338e+00   XLV  0.5234  0.4964    0.68  0.595598
79         A  2026-07-24 10:47:00  138.130005  138.130005  138.110001  138.110001     4466.0  2026-07-24  140.46      139.73 -1.145062e+00   XLV  0.5234  0.4964    0.67  0.595598
80         A  2026-07-24 10:48:00  138.100006  138.100006  138.020004  138.020004     1900.0  2026-07-24  140.46      139.73 -1.166531e+00   XLV  0.5234  0.4964    0.70  0.595598
81         A  2026-07-24 10:49:00  138.059998  138.369995  138.050003  138.327499     3160.0  2026-07-24  140.46      139.73 -1.195164e+00   XLV  0.5234  0.4964    0.69  0.595598
82         A  2026-07-24 10:50:00  138.324997  138.347504  138.320007  138.324997     1100.0  2026-07-24  140.46      139.73 -1.005513e+00   XLV  0.5234  0.4964    0.67  0.595598
83         A  2026-07-24 10:51:00  138.410004  138.500000  138.399994  138.449997     1372.0  2026-07-24  140.46      139.73 -9.446764e-01   XLV  0.5234  0.4964    0.64  0.595598
84         A  2026-07-24 10:52:00  138.585007  138.585007  138.500000  138.505005     1300.0  2026-07-24  140.46      139.73 -8.194327e-01   XLV  0.5234  0.4964    0.72  0.595598
85         A  2026-07-24 10:53:00  138.505005  138.619995  138.505005  138.550003      628.0  2026-07-24  140.46      139.73 -8.766873e-01   XLV  0.5234  0.4964    0.68  0.595598
86         A  2026-07-24 10:54:00  138.559998  138.559998  138.559998  138.559998      336.0  2026-07-24  140.46      139.73 -8.373309e-01   XLV  0.5234  0.4964    0.66  0.595598
87         A  2026-07-24 10:55:00  138.520004  138.610001  138.419998  138.517502     2227.0  2026-07-24  140.46      139.73 -8.659527e-01   XLV  0.5234  0.4964    0.65  0.595598
88         A  2026-07-24 10:56:00  138.429993  138.429993  138.414993  138.414993      300.0  2026-07-24  140.46      139.73 -9.303709e-01   XLV  0.5234  0.4964    0.59  0.595598
89         A  2026-07-24 10:57:00  138.414993  138.529999  138.414993  138.460007     1623.0  2026-07-24  140.46      139.73 -9.411055e-01   XLV  0.5234  0.4964    0.58  0.595598
90         A  2026-07-24 10:58:00  138.410004  138.410004  138.377502  138.377502      700.0  2026-07-24  140.46      139.73 -9.446764e-01   XLV  0.5234  0.4964    0.64  0.595598
91         A  2026-07-24 10:59:00  138.309998  138.375000  138.240005  138.240005     2671.0  2026-07-24  140.46      139.73 -1.016247e+00   XLV  0.5234  0.4964    0.60  0.595598
92         A  2026-07-24 11:00:00  138.365005  138.365005  138.300003  138.365005      427.0  2026-07-24  140.46      139.73 -9.768801e-01   XLV  0.5234  0.4964    0.60  0.595598
93         A  2026-07-24 11:01:00  138.365005  138.365005  138.164993  138.164993     3699.0  2026-07-24  140.46      139.73 -9.768801e-01   XLV  0.5234  0.4964    0.57  0.595598
94         A  2026-07-24 11:02:00  138.164993  138.264999  138.154999  138.220001     3200.0  2026-07-24  140.46      139.73 -1.120022e+00   XLV  0.5234  0.4964    0.58  0.595598
95         A  2026-07-24 11:03:00  138.139999  138.320007  138.139999  138.320007      800.0  2026-07-24  140.46      139.73 -1.137909e+00   XLV  0.5234  0.4964    0.60  0.595598
96         A  2026-07-24 11:04:00  138.307495  138.315002  138.210007  138.250000     1155.0  2026-07-24  140.46      139.73 -1.018038e+00   XLV  0.5234  0.4964    0.67  0.595598
97         A  2026-07-24 11:05:00  138.320007  138.460007  138.199997  138.460007      892.0  2026-07-24  140.46      139.73 -1.009084e+00   XLV  0.5234  0.4964    0.69  0.595598
98         A  2026-07-24 11:06:00  138.539993  138.539993  138.500000  138.500000      307.0  2026-07-24  140.46      139.73 -8.516473e-01   XLV  0.5234  0.4964    0.73  0.595598
99         A  2026-07-24 11:07:00  138.494995  138.520004  138.494995  138.494995      300.0  2026-07-24  140.46      139.73 -8.838509e-01   XLV  0.5234  0.4964    0.69  0.595598
100        A  2026-07-24 11:08:00  138.419998  138.539993  138.419998  138.494995     1301.0  2026-07-24  140.46      139.73 -9.375237e-01   XLV  0.5234  0.4964    0.66  0.595598
101        A  2026-07-24 11:09:00  138.494995  138.559998  138.419998  138.529999     1000.0  2026-07-24  140.46      139.73 -8.838509e-01   XLV  0.5234  0.4964    0.67  0.595598
102        A  2026-07-24 11:10:00  138.529999  138.529999  138.289993  138.470001     2200.0  2026-07-24  140.46      139.73 -8.588000e-01   XLV  0.5234  0.4964    0.72  0.595598
103        A  2026-07-24 11:11:00  138.414993  138.615005  138.414993  138.429993     2004.0  2026-07-24  140.46      139.73 -9.411055e-01   XLV  0.5234  0.4964    0.82  0.595598
104        A  2026-07-24 11:12:00  138.490005  138.490005  138.350006  138.350006      230.0  2026-07-24  140.46      139.73 -8.874218e-01   XLV  0.5234  0.4964    0.82  0.595598
105        A  2026-07-24 11:13:00  138.490005  138.490005  138.490005  138.490005      100.0  2026-07-24  140.46      139.73 -8.874218e-01   XLV  0.5234  0.4964    0.85  0.595598
106        A  2026-07-24 11:14:00  138.399994  138.699997  138.399994  138.699997     1580.0  2026-07-24  140.46      139.73 -9.518401e-01   XLV  0.5234  0.4964    0.85  0.595598
107        A  2026-07-24 11:15:00  138.610001  138.714996  138.600006  138.714996      900.0  2026-07-24  140.46      139.73 -8.015454e-01   XLV  0.5234  0.4964    0.93  0.595598
108        A  2026-07-24 11:16:00  138.684998  138.684998  138.684998  138.684998      100.0  2026-07-24  140.46      139.73 -7.478726e-01   XLV  0.5234  0.4964    0.95  0.595598
109        A  2026-07-24 11:17:00  138.699997  138.710007  138.580002  138.654999     2538.0  2026-07-24  140.46      139.73 -7.371381e-01   XLV  0.5234  0.4964    0.92  0.595598

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,A,2026-07-24 00:04:00,140.000000,140.000000,140.000000,140.000000,5.0,2026-07-24,140.46,139.73,0.193230,XLV,0.5234,0.4964,NaN,0.595598
1,A,2026-07-24 00:05:00,140.039993,140.039993,140.039993,140.039993,5.0,2026-07-24,140.46,139.73,0.221852,XLV,0.5234,0.4964,NaN,0.595598
2,A,2026-07-24 07:00:00,138.169998,138.169998,138.169998,138.169998,100.0,2026-07-24,140.46,139.73,-1.116440,XLV,0.5234,0.4964,NaN,0.595598
3,A,2026-07-24 08:13:00,139.699997,139.699997,139.699997,139.699997,150.0,2026-07-24,140.46,139.73,-0.021472,XLV,0.5234,0.4964,NaN,0.595598
4,A,2026-07-24 09:30:00,140.460007,140.460007,139.735001,139.735001,15257.0,2026-07-24,140.46,139.73,0.522441,XLV,0.5234,0.4964,0.66,0.595598
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,ACRS,2026-07-24 10:43:00,5.310000,5.310000,5.310000,5.310000,3000.0,2026-07-24,5.52,5.47,-2.925047,XBI,0.4850,0.4394,-1.14,0.955419
21146,ACRS,2026-07-24 10:44:00,5.315000,5.315000,5.315000,5.315000,242.0,2026-07-24,5.52,5.47,-2.833637,XBI,0.4850,0.4394,-1.13,0.955419
21147,ACRS,2026-07-24 10:45:00,5.310000,5.310000,5.310000,5.310000,385.0,2026-07-24,5.52,5.47,-2.925047,XBI,0.4850,0.4394,-1.28,0.955419
21148,ACRS,2026-07-24 10:46:00,5.310000,5.315000,5.310000,5.310000,800.0,2026-07-24,5.52,5.47,-2.925047,XBI,0.4850,0.4394,-1.41,0.955419
21149,ACRS,2026-07-24 10:47:00,5.320000,5.321500,5.300000,5.300000,2600.0,2026-07-24,5.52,5.47,-2.742227,XBI,0.4850,0.4394,-1.37,0.955419

In [49]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional, List

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
    import pyarrow.compute as pc
except Exception:
    pa = pq = ds = pc = None


def _as_f64(col):
    """ChunkedArray -> float64 без походу в pandas (fallback лише для нечислових типів)."""
    if pa.types.is_floating(col.type) or pa.types.is_integer(col.type):
        return col.cast(pa.float64()) if col.type != pa.float64() else col
    if pa.types.is_decimal(col.type):
        return col.cast(pa.float64())
    return pa.chunked_array([pa.array(
        pd.to_numeric(col.to_pandas(), errors="coerce").to_numpy(dtype="float64"))])


def _round_like_numpy(col, ndigits):
    """np.round над Arrow-колонкою + NaN -> null (як робив pa.Table.from_pandas)."""
    if len(col) == 0:
        return col
    v = col.to_numpy(zero_copy_only=False)   # може бути read-only zero-copy view
    if ndigits is not None:
        v = np.round(v, int(ndigits))
    return pa.array(v, from_pandas=True)


def _add_tp_deviation_devsig(table, *, round_tp_dev=2, round_devsig=6, dt_as_timestamp=False):
    """t_p / deviation / dev_sig як арифметика Arrow над колонками таблиці.

    Раніше кожен батч ходив у pandas і назад (batch.to_pandas() +
    pa.Table.from_pandas()). Для рядкових колонок ticker/dt/date/bench це означало
    матеріалізацію мільйонів python-об'єктів str на кожному батчі й повне
    перезбирання Arrow-масивів — найдорожча частина того циклу. Тут таблиця
    лишається в Arrow від читання до запису.
    """
    names = {n.strip().lower(): n for n in table.column_names}
    stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
    bench_col = names.get("bench%")
    beta_col = names.get("beta")
    sigma_col = names.get("sigma")

    need = {
        "stack%/pct_vs_prev_close": stack_col,
        "bench%": bench_col,
        "beta": beta_col,
        "sigma": sigma_col,
    }
    missing = [k for k, v in need.items() if v is None]
    if missing:
        raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

    drop = [c for c in ("t_p", "deviation", "dev_sig") if c in table.column_names]
    if drop:
        table = table.drop_columns(drop) if hasattr(table, "drop_columns") else table.drop(drop)

    stack = _as_f64(table[stack_col])
    beta = _as_f64(table[beta_col])
    bench = _as_f64(table[bench_col])
    sigma = _as_f64(table[sigma_col])

    tp = pc.multiply(stack, beta)
    dev = pc.subtract(tp, bench)
    denom = pc.if_else(pc.equal(sigma, 0), pa.scalar(None, pa.float64()), sigma)  # sigma 0 -> NaN
    dsg = pc.divide(dev, denom)

    # Округлення саме через np.round, а не pc.round: на значеннях, які вже округлені
    # вище по пайплайну (Stack% до 2 знаків, beta до 4), добуток лягає впритул до
    # межі .005, і pc.round подекуди дає результат на 1 ULP інший за np.round.
    # np.round тут ще й трохи швидший, а pa.array(..., from_pandas=True) відтворює
    # ту саму семантику NaN -> null, що давав старий pa.Table.from_pandas().
    tp = _round_like_numpy(tp, round_tp_dev)
    dev = _round_like_numpy(dev, round_tp_dev)
    dsg = _round_like_numpy(dsg, round_devsig)

    if dt_as_timestamp and "dt" in table.column_names and pa.types.is_string(table["dt"].type):
        i = table.column_names.index("dt")
        table = table.set_column(i, "dt", pc.strptime(table["dt"], format="%Y-%m-%d %H:%M:%S",
                                                      unit="ns", error_is_null=True))

    return (table.append_column("t_p", tp)
                 .append_column("deviation", dev)
                 .append_column("dev_sig", dsg))


def _drop_dup_ticker_dt(table):
    """Прибирає дублі (ticker, dt) у вже ВІДСОРТОВАНІЙ за (ticker, date, dt) таблиці.

    Дублі виникали, бо dedup у fetch працює лише в межах одного батча, а той самий
    (ticker, dt) лежав у кількох батчах (докачка / перекриття діапазонів): у final було
    ~8.1 млн ідентичних рядків у 2 479 тікерів (NVDA мав 780 хв замість 390 за сесію).
    Дублі ідентичні (перевірено на o/h/l/c/v), тому лишаємо перший.
    Повертає (table, кількість_видалених)."""
    n = table.num_rows
    if n < 2:
        return table, 0
    tk = table["ticker"].combine_chunks()
    dt = table["dt"].combine_chunks()
    same = pc.and_(pc.equal(tk.slice(1), tk.slice(0, n - 1)),
                   pc.equal(dt.slice(1), dt.slice(0, n - 1)))
    same = pc.fill_null(same, False)
    dropped = pc.sum(same.cast(pa.int64())).as_py() or 0
    if not dropped:
        return table, 0
    keep = pa.concat_arrays([pa.array([True]), pc.invert(same)])
    return table.filter(keep), int(dropped)


def _sort_keys(schema_names):
    keys = [("ticker", "ascending")]
    if "date" in schema_names:
        keys.append(("date", "ascending"))
    if "dt" in schema_names:
        keys.append(("dt", "ascending"))
    return keys


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # batch_rows для потокового режиму / бакетування
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,
    max_rows_in_memory: int = 20_000_000,
    dt_as_timestamp: bool = False,
    row_group_size: int = 2_000_000,
) -> str:
    """
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.

    Якщо sort_final_by_ticker=True, output_path фізично відсортований:
    ticker A→Z, всередині тикера date,dt.

    Що змінилось проти попередньої версії:
      1. Обчислення і сортування — ОДИН прохід. Раніше спершу писався повний
         tmp_unsorted, потім він читався назад і переписувався відсортованим:
         3 читання + 3 записи всього файла. Тепер 1 читання + 1 запис
         (або 2+2, якщо файл не влазить у пам'ять і потрібні бакети).
      2. Уся арифметика в Arrow — без batch.to_pandas()/pa.Table.from_pandas()
         на кожному батчі (це матеріалізувало рядкові колонки як python-об'єкти).
      3. Сортування ПЕРЕД додаванням t_p/deviation/dev_sig — take() переставляє
         на 3 float64-колонки менше.
      4. Бакетування по тикерах — через pc.index_in замість pandas .map по рядках.
      5. row_group_size=2M замість дефолтного 1M: менше row-груп → швидший запис,
         трохи менший файл, і стратегії-споживачі (вони читають
         iter_batches(batch_size=1_000_000)) теж читають його швидше.
    """
    if pq is None or pa is None or ds is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet, pyarrow.dataset).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    total_rows = dataset.count_rows()

    tmp_out = output_path + f".tmp_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    def _finish(rows, mode):
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_out, output_path)
        print(f"✅ DONE ({mode}): {rows:,} rows → {output_path} | "
              f"total_time={time.time()-t0:,.1f}s", flush=True)
        return output_path

    # ---------- 1) без сортування: чистий стрім, один прохід ----------
    # (УВАГА: у цьому режимі дублі (ticker, dt) не видаляються — для final лишай sort_final_by_ticker=True)
    if not sort_final_by_ticker:
        print(f"▶ START (stream): {input_path} → {output_path} | "
              f"rows={total_rows:,} batch={chunksize:,}", flush=True)
        writer = None
        written = 0
        try:
            for bi, rb in enumerate(dataset.to_batches(batch_size=chunksize), 1):
                if rb.num_rows == 0:
                    continue
                tbl = _add_tp_deviation_devsig(
                    pa.Table.from_batches([rb]), round_tp_dev=round_tp_dev,
                    round_devsig=round_devsig, dt_as_timestamp=dt_as_timestamp)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl, row_group_size=row_group_size)
                written += tbl.num_rows
                if bi % 5 == 0:
                    print(f"[batch {bi:>4}] rows={written:,}  "
                          f"elapsed={time.time()-t0:,.1f}s", flush=True)
        finally:
            if writer is not None:
                writer.close()
        return _finish(written, "stream")

    keys = _sort_keys(schema_names)
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    # ---------- 2) влазить у пам'ять: читання → сорт → рахунок → запис ----------
    if total_rows <= max_rows_in_memory:
        print(f"▶ START (in-memory sort): {input_path} → {output_path} | "
              f"rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        table, n_dup = _drop_dup_ticker_dt(table)
        if n_dup:
            print(f"🧹 видалено дублів (ticker, dt): {n_dup:,}", flush=True)
        table = _add_tp_deviation_devsig(
            table, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
            dt_as_timestamp=dt_as_timestamp)
        pq.write_table(table, tmp_out, compression=compression,
                       row_group_size=row_group_size)
        written = table.num_rows
        del table
        gc.collect()
        return _finish(written, "in-memory sort")

    # ---------- 3) не влазить: один прохід у бакети, далі сорт кожного ----------
    n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
    tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
    tickers = sorted(str(t) for t in tickers if t is not None)
    # суміжні діапазони тикерів → порядок бакетів = порядок тикерів
    edges = np.array_split(np.arange(len(tickers)), n_buckets)
    rank_to_bucket = np.zeros(len(tickers), dtype="int32")
    for b, idxs in enumerate(edges):
        rank_to_bucket[idxs] = b
    ticker_set = pa.array(tickers, type=pa.string())
    rank_to_bucket_arr = pa.array(rank_to_bucket)

    print(f"▶ START (bucketed sort): {input_path} → {output_path} | rows={total_rows:,} "
          f"tickers={len(tickers):,} buckets={n_buckets}", flush=True)

    bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
    bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
    try:
        for rb in dataset.to_batches(batch_size=chunksize):
            if rb.num_rows == 0:
                continue
            tbl = pa.Table.from_batches([rb])
            # ранг тикера в відсортованому списку → номер бакета, повністю в Arrow
            ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
            bidx = pc.take(rank_to_bucket_arr, ranks)
            for b in range(n_buckets):
                mask = pc.equal(bidx, b)
                if not pc.any(mask).as_py():
                    continue
                part = tbl.filter(mask)
                if part.num_rows == 0:
                    continue
                if bwriters[b] is None:
                    bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                   compression=compression)
                bwriters[b].write_table(part)
    finally:
        for w in bwriters:
            if w is not None:
                w.close()

    writer = None
    written = 0
    dup_total = 0
    try:
        for b, bp in enumerate(bucket_paths):
            if not os.path.exists(bp):
                continue
            tbl = pq.read_table(bp).sort_by(keys)
            tbl, n_dup = _drop_dup_ticker_dt(tbl)
            dup_total += n_dup
            tbl = _add_tp_deviation_devsig(
                tbl, round_tp_dev=round_tp_dev, round_devsig=round_devsig,
                dt_as_timestamp=dt_as_timestamp)
            if writer is None:
                writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
            writer.write_table(tbl, row_group_size=row_group_size)
            written += tbl.num_rows
            del tbl
            gc.collect()
            print(f"  bucket {b+1}/{n_buckets}  written={written:,}  dup_dropped={dup_total:,}  "
                  f"elapsed={time.time()-t0:,.1f}s", flush=True)
    finally:
        if writer is not None:
            writer.close()
        for bp in bucket_paths:
            if os.path.exists(bp):
                os.remove(bp)

    return _finish(written, "bucketed sort")


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    max_rows_in_memory: int = 20_000_000,
    log_every: int = 200,            # лишено для сумісності виклику
    roundtrip_pandas: bool = True,   # лишено для сумісності виклику
):
    """Лише сортування parquet: ticker A→Z, всередині тикера (date, dt).

    Обчислення t_p/deviation/dev_sig тепер робить сам recompute_tp_deviation_devsig
    у тому ж проході, тож окремо ця функція потрібна лише якщо треба відсортувати
    вже готовий файл.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")
    keys = _sort_keys(schema_names)

    total_rows = dataset.count_rows()
    t0 = time.time()
    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    if total_rows <= max_rows_in_memory:
        print(f"▶ SORT (in-memory): rows={total_rows:,}", flush=True)
        table = dataset.to_table().sort_by(keys)
        pq.write_table(table, tmp_out, compression=compression)
        written = table.num_rows
        del table
        gc.collect()
    else:
        n_buckets = int(np.ceil(total_rows / float(max_rows_in_memory)))
        tickers = pc.unique(dataset.to_table(columns=["ticker"]).column("ticker")).to_pylist()
        tickers = sorted(str(t) for t in tickers if t is not None)
        rank_to_bucket = np.zeros(len(tickers), dtype="int32")
        for b, idxs in enumerate(np.array_split(np.arange(len(tickers)), n_buckets)):
            rank_to_bucket[idxs] = b
        ticker_set = pa.array(tickers, type=pa.string())
        rank_to_bucket_arr = pa.array(rank_to_bucket)
        print(f"▶ SORT (bucketed): rows={total_rows:,} tickers={len(tickers):,} "
              f"buckets={n_buckets}", flush=True)

        bucket_paths = [tmp_out + f".b{b}" for b in range(n_buckets)]
        bwriters: List[Optional["pq.ParquetWriter"]] = [None] * n_buckets
        try:
            for rb in dataset.to_batches():
                if rb.num_rows == 0:
                    continue
                tbl = pa.Table.from_batches([rb])
                ranks = pc.index_in(tbl.column("ticker").cast(pa.string()), value_set=ticker_set)
                bidx = pc.take(rank_to_bucket_arr, ranks)
                for b in range(n_buckets):
                    mask = pc.equal(bidx, b)
                    if not pc.any(mask).as_py():
                        continue
                    part = tbl.filter(mask)
                    if part.num_rows == 0:
                        continue
                    if bwriters[b] is None:
                        bwriters[b] = pq.ParquetWriter(bucket_paths[b], part.schema,
                                                       compression=compression)
                    bwriters[b].write_table(part)
        finally:
            for w in bwriters:
                if w is not None:
                    w.close()

        writer = None
        written = 0
        try:
            for b, bp in enumerate(bucket_paths):
                if not os.path.exists(bp):
                    continue
                tbl = pq.read_table(bp).sort_by(keys)
                if writer is None:
                    writer = pq.ParquetWriter(tmp_out, tbl.schema, compression=compression)
                writer.write_table(tbl)
                written += tbl.num_rows
                del tbl
                gc.collect()
        finally:
            if writer is not None:
                writer.close()
            for bp in bucket_paths:
                if os.path.exists(bp):
                    os.remove(bp)

    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)
    print(f"✅ SORT DONE: {written:,} rows → {output_path} | time={time.time()-t0:,.1f}s", flush=True)
    return output_path

In [50]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (bucketed sort): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | rows=113,089,395 tickers=7,820 buckets=6

  bucket 1/6  written=18,835,652  dup_dropped=0  elapsed=99.1s

  bucket 2/6  written=37,055,671  dup_dropped=0  elapsed=120.0s

  bucket 3/6  written=54,854,510  dup_dropped=0  elapsed=140.2s

  bucket 4/6  written=73,760,787  dup_dropped=0  elapsed=161.8s

  bucket 5/6  written=94,075,288  dup_dropped=0  elapsed=185.0s

  bucket 6/6  written=113,089,395  dup_dropped=0  elapsed=206.7s

✅ DONE (bucketed sort): 113,089,395 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=207.0s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'

In [51]:
# ================== АУДИТ final.parquet: повнота днів / хвилин / o-h-l-c ==================
# Перевіряє ВСЕ, а не вибірково:
#   1) o,h,l,c,v не null; h >= max(o,c) та l <= min(o,c) (з допуском на float32);
#   2) жодних дублів (ticker, dt);
#   3) для «щільних» тікерів (>= min_rth_rows хв у сесії 09:30–15:59 у типовий день): будь-який
#      торговий день МІЖ їхнім першим і останнім днем, коли ринок торгується, а цей тікер — ні (саме так виглядав NVDA/AAPL без 10–28 серпня), та дні з неповною сесією;
#   4) кількість тікерів на день різко (<85% медіани сусідніх днів) просіла → підозра на дірку фетчу.
# Файл розріджений за задумом (бар є лише для хвилин, де були угоди), тому «хвилина без бару» для
# неліквідних тікерів — не помилка; повноту хвилин міряємо на щільних тікерах.
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import pyarrow.compute as pc

def audit_final_coverage(final_path, *, rth_from="09:30", rth_to="15:59", min_rth_rows=380,
                         alive_share=0.2, drop_ratio=0.85, raise_on_fail=False):
    pf = pq.ParquetFile(final_path)
    need = ["ticker", "dt", "o", "h", "l", "c", "v"]
    miss = [c for c in need if c not in pf.schema_arrow.names]
    if miss:
        raise KeyError(f"У final немає колонок: {miss}")
    n_rows = n_dup = n_null = n_bad = 0
    prev = None
    parts = []
    for gi in range(pf.num_row_groups):
        t = pf.read_row_group(gi, columns=need)
        n = t.num_rows
        if n == 0:
            continue
        n_rows += n
        for c in "ohlcv":
            n_null += t[c].null_count
        o, h, l, c_ = (t[x].to_numpy() .astype("float64") for x in "ohlc")
        with np.errstate(invalid="ignore"):
            n_bad += int(np.sum((h < np.maximum(o, c_) - 1e-3) | (l > np.minimum(o, c_) + 1e-3)))
        tk = t["ticker"].combine_chunks()
        dt = t["dt"].combine_chunks()
        if not pa.types.is_string(dt.type):
            dt = pc.strftime(dt, format="%Y-%m-%d %H:%M:%S")
        same = pc.fill_null(pc.and_(pc.equal(tk.slice(1), tk.slice(0, n - 1)),
                                    pc.equal(dt.slice(1), dt.slice(0, n - 1))), False)
        n_dup += pc.sum(same.cast(pa.int64())).as_py() or 0
        if prev is not None and prev == (tk[0].as_py(), dt[0].as_py()):
            n_dup += 1
        prev = (tk[n - 1].as_py(), dt[n - 1].as_py())
        hm = pc.utf8_slice_codeunits(dt, 11, 16)
        rth = pc.and_(pc.greater_equal(hm, rth_from), pc.less_equal(hm, rth_to)).cast(pa.int64())
        g = (pa.table({"ticker": tk, "date": pc.utf8_slice_codeunits(dt, 0, 10), "rth": rth, "rows": rth})
               .group_by(["ticker", "date"]).aggregate([("rth", "sum"), ("rows", "count")]))
        parts.append(g.to_pandas().rename(columns={"rth_sum": "rth", "rows_count": "rows"}))
    a = pd.concat(parts, ignore_index=True).groupby(["ticker", "date"], as_index=False).sum()
    a["wd"] = pd.to_datetime(a["date"]).dt.weekday

    problems = []
    print(f"рядків: {n_rows:,} | null у o/h/l/c/v: {n_null:,} | порушень OHLC: {n_bad:,} | дублів (ticker,dt): {n_dup:,}")
    if n_null:
        problems.append("null у OHLCV")
    if n_bad:
        problems.append("h/l не охоплюють o/c")
    if n_dup:
        problems.append("дублі (ticker,dt)")

    wk = a[a["wd"] < 5]
    days = sorted(wk["date"].unique())
    per_day = wk.groupby("date")["ticker"].nunique().reindex(days)
    sus = []
    for i, d in enumerate(days):
        nb = [per_day.iloc[j] for j in range(max(0, i - 10), min(len(days), i + 11)) if j != i]
        if nb and per_day.iloc[i] < drop_ratio * float(np.median(nb)):
            sus.append((d, int(per_day.iloc[i]), int(np.median(nb))))
    if sus:
        print("⚠ дні з різким провалом кількості тікерів (день, є, типово) — свято або дірка фетчу:")
        for d, v, m in sus:
            print(f"   {d}: {v:,} vs ~{m:,}")
        problems.append(f"{len(sus)} днів з провалом покриття")

    med = a[a["rth"] > 0].groupby("ticker")["rth"].median()
    dense = set(med[med >= min_rth_rows].index)
    dw = wk[wk["ticker"].isin(dense) & (wk["rth"] > 0)]
    # «торговий день» = хоч alive_share від максимуму тікерів із сесійними барами (свята/вихідні
    # відпадають, а тримісячна дірка половини універсу — ні, тож вона не маскується)
    sess_n = wk[wk["rth"] > 0].groupby("date")["ticker"].nunique()
    alive = set(sess_n[sess_n >= alive_share * sess_n.max()].index)
    exp_rth = dw.groupby("date")["rth"].median()
    have = set(zip(dw["ticker"], dw["date"]))
    span = dw.groupby("ticker")["date"].agg(["min", "max"])
    gaps = [(tk, d) for tk, r in span.iterrows() for d in days
            if r["min"] < d < r["max"] and d in alive and (tk, d) not in have]
    short = dw[dw["rth"] < 0.95 * dw["date"].map(exp_rth)]
    gdf = pd.DataFrame(gaps, columns=["ticker", "date"])
    print(f"щільних тікерів: {len(dense):,} | торгових днів: {len(alive)}")
    print(f"повністю пропущених днів усередині історії щільних тікерів: {len(gdf):,}")
    if len(gdf):
        print(gdf.groupby("date").size().to_string())
        print("приклад:", gdf.head(10).values.tolist())
        problems.append("пропущені дні")
    print(f"щільних тікер-днів із неповною сесією (<95% медіани дня): {len(short):,}")
    if len(short):
        print(short.sort_values("rth").head(10)[["ticker", "date", "rth"]].to_string(index=False))
        problems.append("неповні сесії")
    print("✅ аудит чистий" if not problems else "❌ проблеми: " + "; ".join(problems))
    if problems and raise_on_fail:
        raise AssertionError("; ".join(problems))
    return {"problems": problems, "missing_days": gdf, "short_sessions": short, "suspicious_days": sus}


audit_report = audit_final_coverage(str(FINAL_PATH))

рядків: 113,089,395 | null у o/h/l/c/v: 0 | порушень OHLC: 0 | дублів (ticker,dt): 0
⚠ дні з різким провалом кількості тікерів (день, є, типово) — свято або дірка фетчу:
   2026-08-11: 5,286 vs ~7,195
   2026-08-12: 5,285 vs ~6,876
   2026-08-13: 5,294 vs ~6,810
   2026-09-07: 57 vs ~7,253

щільних тікерів: 1,042 | торгових днів: 65
повністю пропущених днів усередині історії щільних тікерів: 2,788
date
2026-07-29      1
2026-08-11    331
2026-08-12    330
2026-08-13    330
2026-08-14     81
2026-08-17    188
2026-08-18    190
2026-08-19    171
2026-08-20    171
2026-08-21     94
2026-08-24     84
2026-08-25     57
2026-08-26     96
2026-08-27    124
2026-08-28    104
2026-09-15    161
2026-09-16    126
2026-09-17    123
2026-09-18     26
приклад: [['AGNC', '2026-08-11'], ['AGNC', '2026-08-12'], ['AGNC', '2026-08-13'], ['AGQ', '2026-08-11'], ['AGQ', '2026-08-12'], ['AGQ', '2026-08-13'], ['AI', '2026-08-11'], ['AI', '2026-08-12'], ['AI', '2026-08-13'], ['AIG', '2026-08-11']]
щільних тікер-днів із неповною сесією (<95% медіани дня): 2,445
ticker       date  rth
  JMKE 2026-07-30  176
  CYPH 2026-07-27  185
  CYPH 2026-08-10  208
  CYPH 2026-07-30  209
  CYPH 2026-08-06  214
  CYPH 2026-07-29  229
  CYPH 2026-08-04  231
  CYPH 2026-08-14  250
  CYPH 2026-07-31  251
  CYPH 2026-07-24  253
❌ проблеми: 4 днів з провалом покриття; пропущені дні; неповні сесії