In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2026-02-26 00:00:00
end   = 2026-05-26 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2026-02-26
end_date_str   = 2026-05-26

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker       value
0      A    39981.78
1     AA  1918340.34
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 12930

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,country,exchange,market_cap',
    'active': True,
    'us_exchange': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
tickers_df = tickers_df.dropna()

# --- крок 3: додаємо потрібні колонки у df_filtered
top1500 = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(top1500):,} рядків")
top1500.head()

Після фільтрації залишилось: 7,111 рядків

,ticker,value,lvl3,country,exchange,market_cap
0,A,39981.78,Medical Equipment & Devices,UNITED STATES,New York,32521.0
1,AA,1918340.34,Metals & Mining,UNITED STATES,New York,19678.0
2,AAAU,604532.02,NaN,NaN,NaN,NaN
3,AACG,12.37,Software,UNITED STATES,NASDAQ CM,51.0
4,AAL,6380496.67,Transportation & Logistics,UNITED STATES,NASDAQ GS,9818.0

In [7]:
top1500[top1500["ticker"] == "JD"]

,ticker,value,lvl3,country,exchange,market_cap
3400,JD,2534973.33,E-Commerce Discretionary,UNITED STATES,NASDAQ GS,36382.0

In [8]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [9]:
unique_lvl2 = get_unique_lvl2(top1500)
unique_lvl2

🔹 Знайдено 59 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Elec & Gas Marketing & Trading',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [10]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "SPY", "BITO"],
    "Banking": ["KRE", "XLF", "SPY", "BITO"],
    "Institutional Financial Svcs": ["XLF", "SPY", "BITO"],
    "Insurance": ["XLF", "SPY", "BITO"],
    "Specialty Finance": ["XLF", "SPY", "BITO"],

    # --- Tech / Internet / Growth ---
    "Software": ["QQQ", "IWM", "SPY"],
    "IT Services": ["QQQ", "IWM", "SPY"],
    "Semiconductors": ["SOXL", "QQQ", "IWM", "SPY"],
    "Technology Hardware": ["QQQ", "SOXL", "IWM", "SPY"],
    "Internet Media & Services": ["QQQ", "KWEB", "IWM", "SPY"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "IWM", "SPY"],
    "Cable & Satellite": ["QQQ", "KWEB", "IWM", "SPY"],
    "Telecommunications": ["QQQ", "KWEB", "IWM", "SPY"],
    "Publishing & Broadcasting": ["QQQ", "KWEB", "IWM", "SPY"],
    "Entertainment Content": ["QQQ", "KWEB", "IWM", "SPY"],
    "Advertising & Marketing": ["QQQ", "KWEB", "IWM", "SPY"],

    # --- Industrials ---
    "Aerospace & Defense": ["IWM", "SPY", "QQQ"],
    "Diversified Industrials": ["SPY", "IWM"],
    "Industrial Intermediate Prod": ["IWM", "SPY"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["IWM", "SPY"],
    "Machinery": ["IWM", "SPY"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["IWM", "SPY"],
    "Electrical Equipment": ["QQQ", "IWM", "SPY"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XLE", "IWM", "SPY"],
    "Oil & Gas Supply Chain": ["XLE", "IWM", "SPY"],
    "Elec & Gas Marketing & Trading": ["XLE", "IWM", "SPY"],
    "Electric Utilities": ["XLE", "IWM", "SPY"],
    "Gas & Water Utilities": ["XLE", "IWM", "SPY"],
    "Renewable Energy": ["XLE", "IWM", "SPY"],
    "Chemicals": ["XLE", "IWM", "SPY"],
    "Metals & Mining": ["GDX", "IWM", "SPY"],
    "Steel": ["GDX", "IWM", "SPY"],
    "Construction Materials": ["IWM", "SPY"],
    "Forestry, Paper & Wood Products": ["IWM", "SPY"],

    # --- Health Care ---
    "Biotech & Pharma": ["QQQ", "IWM", "SPY"],
    "Medical Equipment & Devices": ["QQQ", "IWM", "SPY"],
    "Health Care Facilities & Svcs": ["QQQ", "IWM", "SPY"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["XLP", "SPY", "IWM"],
    "Beverages": ["XLP", "SPY", "IWM"],
    "Household Products": ["XLP", "SPY", "IWM"],
    "Tobacco & Cannabis": ["XLP", "SPY", "IWM"],
    "Retail - Consumer Staples": ["XLP", "SPY", "IWM"],
    "Wholesale - Consumer Staples": ["XLP", "SPY", "IWM"],

    "Retail - Discretionary": ["SPY", "IWM", "QQQ"],
    "Wholesale - Discretionary": ["SPY", "IWM", "QQQ"],
    "Consumer Services": ["SPY", "IWM"],
    "Leisure Facilities & Services": ["SPY", "IWM"],
    "Leisure Products": ["SPY", "IWM"],
    "Apparel & Textile Products": ["SPY", "IWM", "QQQ"],
    "Automotive": ["SPY", "IWM", "QQQ"],
    "Home & Office Products": ["SPY", "IWM"],
    "Home Construction": ["IWM", "SPY"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [11]:
# ------------------------------------------------

In [12]:
import numpy as np
import pandas as pd


def calc_corr_beta_from_joined_gaps(df_pair: pd.DataFrame, x_col: str = "gap_x", y_col: str = "gap_y"):
    """
    Local corr/beta calculation without /calculations/corr_beta API.

    corr = Pearson(x, y)
    beta = cov(x, y) / var(y)
    """
    d = df_pair[[x_col, y_col]].copy()
    d[x_col] = pd.to_numeric(d[x_col], errors="coerce")
    d[y_col] = pd.to_numeric(d[y_col], errors="coerce")
    d = d.dropna()

    n = len(d)
    if n < 2:
        return np.nan, np.nan, n

    var_y = float(d[y_col].var(ddof=1))
    corr = float(d[x_col].corr(d[y_col]))

    if np.isnan(var_y) or var_y == 0:
        return corr, np.nan, n

    cov_xy = float(d[[x_col, y_col]].cov(ddof=1).iloc[0, 1])
    beta = cov_xy / var_y
    return corr, beta, n


def corr_beta_best_match_from_gaps(
    stock_gap_df: pd.DataFrame,
    etf_gap_df: pd.DataFrame,
    x_tickers,
    y_tickers,
    *,
    min_overlap: int = 20,
    output_path: str = None,
):
    """
    Pick best Y per X using local gaps.

    stock_gap_df: ['ticker','date','gap']
    etf_gap_df:   ['ticker','date','gap']
    """
    sx = stock_gap_df.copy()
    sy = etf_gap_df.copy()

    for df in (sx, sy):
        if not {"ticker", "date", "gap"}.issubset(df.columns):
            raise KeyError("Expected columns ['ticker','date','gap'] in gap data")
        df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.strftime("%Y-%m-%d")
        df["gap"] = pd.to_numeric(df["gap"], errors="coerce")

    s_map = {t: g[["date", "gap"]].copy() for t, g in sx.groupby("ticker")}
    e_map = {t: g[["date", "gap"]].copy() for t, g in sy.groupby("ticker")}

    rows_all = []
    rows_best = []

    for x in [str(v).upper() for v in x_tickers]:
        g_x = s_map.get(x)
        if g_x is None or g_x.empty:
            continue

        best = None
        for y in [str(v).upper() for v in y_tickers]:
            g_y = e_map.get(y)
            if g_y is None or g_y.empty:
                continue

            m = g_x.merge(g_y, on="date", how="inner", suffixes=("_x", "_y")).dropna()
            corr, beta, n = calc_corr_beta_from_joined_gaps(m, x_col="gap_x", y_col="gap_y")
            if n < int(min_overlap) or pd.isna(corr):
                continue

            row = {
                "x_ticker": x,
                "y_ticker": y,
                "corr": corr,
                "beta": beta,
                "n_overlap": n,
            }
            rows_all.append(row)
            if best is None or row["corr"] > best["corr"]:
                best = row

        if best is not None:
            rows_best.append({
                "x_ticker": best["x_ticker"],
                "best_y_ticker": best["y_ticker"],
                "best_corr": best["corr"],
                "beta_with_best": best["beta"],
                "n_overlap": best["n_overlap"],
            })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "n_overlap"])

    if output_path:
        df_pairs.to_csv(output_path, index=False)

    return df_all, df_pairs

In [13]:
def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
    start_date=None,
    end_date=None,
    last_n_reports=20,
    cap_q=0.95,
    min_hist_for_cap=20,
    min_overlap=20,
):
    """
    Local corr/beta from daily gaps:
    - stock gaps: exclude report days + exclude anomalous moves
    - etf gaps: plain gaps (no report-day exclusion)
    - per stock: choose ETF with max corr

    Outputs:
      output_path: x_ticker,best_y_ticker,best_corr,beta_with_best,lvl3,n_overlap
      bench_path:  ticker,benchmark
    """
    import numpy as np
    import pandas as pd

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]

    if start_date is None:
        start_date = globals().get("start_date_str")
    if end_date is None:
        end_date = globals().get("end_date_str")
    if not start_date or not end_date:
        raise ValueError("Provide start_date/end_date or define start_date_str/end_date_str")

    if sector_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{sector_col}' column")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{ticker_col}' column")

    def _pick_first_existing(df: pd.DataFrame, candidates):
        cols_l = {c.lower().strip(): c for c in df.columns}
        for c in candidates:
            if c.lower() in cols_l:
                return cols_l[c.lower()]
        return None

    def _fetch_gaps_for_tickers(tickers, s_date, e_date):
        parts = []
        for t in sorted(set(str(x).upper() for x in tickers if str(x).strip())):
            params = {
                "ticker": t,
                "start_date": str(s_date)[:10],
                "end_date": str(e_date)[:10],
                "format": "json_records",
            }
            try:
                dfg = DatumApi.data_request("/daily/gaps", params)
                if dfg is None or dfg.empty:
                    continue
                dcol = _pick_first_existing(dfg, ["date", "move_date", "dt", "datetime", "day"])
                if dcol is None or "gap" not in dfg.columns:
                    continue
                out = dfg.copy()
                out["ticker"] = t
                out["date"] = pd.to_datetime(out[dcol], errors="coerce").dt.strftime("%Y-%m-%d")
                out["gap"] = pd.to_numeric(out["gap"], errors="coerce")
                out = out.dropna(subset=["date", "gap"])
                if not out.empty:
                    parts.append(out[["ticker", "date", "gap"]])
            except Exception as e:
                print(f"WARN gaps fail {t}: {e}")
        return pd.concat(parts, ignore_index=True) if parts else pd.DataFrame(columns=["ticker", "date", "gap"])

    def _get_reports_for_tickers(tickers, s_date, e_date, n_reports):
        parts = []
        for t in sorted(set(str(x).upper() for x in tickers if str(x).strip())):
            try:
                params = {
                    "ticker": t,
                    "start_move_date": str(s_date)[:10],
                    "end_move_date": str(e_date)[:10],
                }
                rep = DatumApi.data_request("/reports", params)
                if rep is None or rep.empty:
                    continue
                dcol = _pick_first_existing(rep, ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"])
                if dcol is None:
                    continue
                r = rep.copy()
                r["date"] = pd.to_datetime(r[dcol], errors="coerce").dt.strftime("%Y-%m-%d")
                r = r.dropna(subset=["date"]).sort_values("date").tail(int(n_reports))
                if not r.empty:
                    r["ticker"] = t
                    parts.append(r[["ticker", "date"]])
            except Exception as e:
                print(f"WARN reports fail {t}: {e}")
        return pd.concat(parts, ignore_index=True).drop_duplicates() if parts else pd.DataFrame(columns=["ticker", "date"])

    def _drop_anomalies_by_ticker(df, q=0.95, min_hist=20):
        if df.empty:
            return df

        def _f(g):
            if len(g) < int(min_hist):
                return g
            a = np.abs(pd.to_numeric(g["gap"], errors="coerce").to_numpy(dtype=float))
            a = a[~np.isnan(a)]
            if len(a) < int(min_hist):
                return g
            cap = np.quantile(a, q)
            return g[np.abs(g["gap"]) <= cap]

        out = df.groupby("ticker", group_keys=False).apply(_f)
        return out.reset_index(drop=True)

    df_clean = tickers_df[[ticker_col, sector_col]].drop_duplicates().copy()
    df_clean[ticker_col] = df_clean[ticker_col].astype(str).str.strip().str.upper()
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)

    stocks = sorted(df_clean[ticker_col].dropna().unique().tolist())

    etf_candidates = set(fallback_etfs)
    for sec in df_clean[sector_col].unique().tolist():
        etf_candidates.update(sector_to_etf.get(sec, fallback_etfs) or fallback_etfs)
    etf_candidates = sorted(str(x).upper() for x in etf_candidates)

    print(f"START gaps: stocks={len(stocks)} etfs={len(etf_candidates)} window={start_date}..{end_date}")

    stock_gaps = _fetch_gaps_for_tickers(stocks, start_date, end_date)
    etf_gaps = _fetch_gaps_for_tickers(etf_candidates, start_date, end_date)

    reports = _get_reports_for_tickers(stocks, start_date, end_date, n_reports=last_n_reports)

    if not reports.empty and not stock_gaps.empty:
        m = stock_gaps.merge(reports.assign(_rep=1), on=["ticker", "date"], how="left")
        stock_gaps = m[m["_rep"].isna()][["ticker", "date", "gap"]].copy()

    stock_gaps = _drop_anomalies_by_ticker(stock_gaps, q=cap_q, min_hist=min_hist_for_cap)

    stock_map = {t: g[["date", "gap"]].copy() for t, g in stock_gaps.groupby("ticker")}
    etf_map = {t: g[["date", "gap"]].copy() for t, g in etf_gaps.groupby("ticker")}

    rows_all = []
    rows_best = []

    sectors_with_fallback = []
    for sec in sorted(df_clean[sector_col].unique().tolist()):
        etfs = sector_to_etf.get(sec)
        if not etfs:
            etfs = list(fallback_etfs)
            sectors_with_fallback.append(sec)
        etfs = [str(x).upper() for x in etfs]

        sec_stocks = sorted(df_clean.loc[df_clean[sector_col] == sec, ticker_col].unique().tolist())
        for st in sec_stocks:
            sx = stock_map.get(st)
            if sx is None or sx.empty:
                continue

            best_row = None
            for etf in etfs:
                sy = etf_map.get(etf)
                if sy is None or sy.empty:
                    continue

                m = sx.merge(sy, on="date", how="inner", suffixes=("_x", "_y")).dropna()
                n = len(m)
                if n < int(min_overlap):
                    continue

                var_y = float(m["gap_y"].var(ddof=1))
                if np.isnan(var_y) or var_y == 0:
                    continue

                corr = float(m["gap_x"].corr(m["gap_y"]))
                cov_xy = float(m[["gap_x", "gap_y"]].cov(ddof=1).iloc[0, 1])
                beta = cov_xy / var_y

                row = {
                    "x_ticker": st,
                    "y_ticker": etf,
                    "corr": corr,
                    "beta": beta,
                    "lvl3": sec,
                    "n_overlap": n,
                }
                rows_all.append(row)

                if (best_row is None) or (row["corr"] > best_row["corr"]):
                    best_row = row

            if best_row is not None:
                rows_best.append({
                    "x_ticker": best_row["x_ticker"],
                    "best_y_ticker": best_row["y_ticker"],
                    "best_corr": best_row["corr"],
                    "beta_with_best": best_row["beta"],
                    "lvl3": sec,
                    "n_overlap": best_row["n_overlap"],
                })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "lvl3", "n_overlap"])

    df_pairs.to_csv(output_path, index=False)
    df_bench = df_pairs.rename(columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"})[["ticker", "benchmark"]]
    df_bench.to_csv(bench_path, index=False)

    print(f"DONE pairs: {len(df_pairs)} -> {output_path}")
    print(f"DONE bench map: {len(df_bench)} -> {bench_path}")
    if sectors_with_fallback:
        print("Fallback ETF used for sectors:", ", ".join(map(str, sectors_with_fallback[:20])))

    return df_all, df_pairs

In [14]:
# Local corr/beta: stock gaps vs ETF gaps, excluding report days and stock outliers
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=top1500,
    sector_to_etf=sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path=str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path=str(WORK_DIR / "ticker_bench_.csv"),
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    cap_q=0.95,
    min_hist_for_cap=20,
    min_overlap=20,
)

# Prepare parquet for downstream merge (cell 31)
corr_beta_pairs = df_pairs.rename(columns={
    "best_y_ticker": "y_ticker",
    "best_corr": "corr",
    "beta_with_best": "beta",
})[["x_ticker", "y_ticker", "corr", "beta"]].copy()

corr_beta_pairs.to_parquet(str(WORK_DIR / "corr_beta_pairs.parquet"), index=False)

print(df_all.head())
print("Rows in raw stock-etf pairs:", len(df_all))
print(df_pairs.head())
print("Saved:", str(WORK_DIR / "corr_beta_pairs.parquet"))

START gaps: stocks=7111 etfs=11 window=2026-02-26..2026-05-26

DONE pairs: 6985 -> C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
DONE bench map: 6985 -> C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv
Fallback ETF used for sectors: UNKNOWN
  x_ticker y_ticker      corr      beta                     lvl3  n_overlap
0      ADV      QQQ  0.055022  0.102578  Advertising & Marketing         56
1      ADV     KWEB  0.146561  0.157502  Advertising & Marketing         56
2      ADV      IWM  0.068465  0.110590  Advertising & Marketing         56
3      ADV      SPY  0.084853  0.200480  Advertising & Marketing         56
4     AEHL      QQQ  0.366420  3.440080  Advertising & Marketing         58
Rows in raw stock-etf pairs: 20843
  x_ticker best_y_ticker  best_corr  beta_with_best                     lvl3  \
0      ADV          KWEB   0.146561        0.157502  Advertising & Marketing
1     AEHL           SPY   0.381415        4.502170  Advertising & Marketing
2      APP           SPY   0.525696        1.426375  Advertising & Marketing
3     AREN           SPY   0.457976        0.941346  Advertising & Marketing
4     BAOS           QQQ   0.156043        0.444622  Advertising & Marketing

   n_overlap
0         56
1         58
2         57
3         56
4         56
Saved: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [15]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [16]:
top1500

,ticker,value,lvl3,country,exchange,market_cap
0,A,39981.78,Medical Equipment & Devices,UNITED STATES,New York,32521.0
1,AA,1918340.34,Metals & Mining,UNITED STATES,New York,19678.0
2,AAAU,604532.02,NaN,NaN,NaN,NaN
3,AACG,12.37,Software,UNITED STATES,NASDAQ CM,51.0
4,AAL,6380496.67,Transportation & Logistics,UNITED STATES,NASDAQ GS,9818.0
...,...,...,...,...,...,...
7106,ZVOL,877.71,NaN,NaN,NaN,NaN
7107,ZVRA,17427.25,Biotech & Pharma,UNITED STATES,NASDAQ GS,610.0
7108,ZWS,1301.25,Machinery,UNITED STATES,New York,8148.0
7109,ZYBT,36.92,Biotech & Pharma,UNITED STATES,NASDAQ CM,43.0
7110,ZYME,45355.67,Biotech & Pharma,UNITED STATES,NASDAQ GS,1868.0

In [17]:
import pandas as pd

# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','XLP','SOXL']

# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

   ticker
0     SPY
1     IWM
2     GDX
3     XLF
4     QQQ
5     XLE
6     KRE
7    BITO
8    KWEB
9     XLP
10   SOXL

In [18]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=top1500,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=3,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 7111 тікерів (пропущено 0 по старому маніфесту) | 2026-02-26 00:00:00 → 2026-05-26 23:59:59 | interval=1 | next batch #6128 | run=8a8b4b40

   workers: tickers=3, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-02-26 → 2026-05-25 (89 днів)

   📈 обробляються дні: 2026-05-26 → 2026-05-26 (1 днів)

   psutil · старт · 🧠 RAM: 264.0 MB

[10/7111] ✓ AAON: 352 рядків |   0.14% | ETA 25:00

[20/7111] ✓ AAPY: 6 рядків |   0.28% | ETA 24:04

[30/7111] ✓ ABEO: 237 рядків |   0.42% | ETA 22:43

[40/7111] ✓ ABT: 434 рядків |   0.56% | ETA 22:32

[50/7111] ✓ ACB: 262 рядків |   0.70% | ETA 21:48

   • RAM · 🧠 RAM: 278.0 MB

   ⏳ перед flush · 🧠 RAM: 278.0 MB

💾 batch 6128 → 16,634 рядків (всього 16,634 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6128.csv.gz

   ✅ після flush · 🧠 RAM: 281.5 MB

[60/7111] ✓ ACHC: 386 рядків |   0.84% | ETA 21:18

[70/7111] ✓ ACM: 366 рядків |   0.98% | ETA 21:07

[80/7111] ✓ ACT: 178 рядків |   1.13% | ETA 21:02

[90/7111] ✓ ADBE: 627 рядків |   1.27% | ETA 21:05

[100/7111] ✓ ADM: 398 рядків |   1.41% | ETA 20:56

   • RAM · 🧠 RAM: 282.7 MB

   ⏳ перед flush · 🧠 RAM: 282.7 MB

💾 batch 6129 → 12,817 рядків (всього 29,451 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6129.csv.gz

   ✅ після flush · 🧠 RAM: 283.8 MB

[110/7111] ✓ ADV: 81 рядків |   1.55% | ETA 20:59

[120/7111] ✓ AEI: 19 рядків |   1.69% | ETA 20:56

[130/7111] ✓ AESI: 376 рядків |   1.83% | ETA 20:49

[140/7111] ✓ AFRM: 532 рядків |   1.97% | ETA 20:37

[150/7111] ✓ AGG: 412 рядків |   2.11% | ETA 20:33

   • RAM · 🧠 RAM: 285.2 MB

   ⏳ перед flush · 🧠 RAM: 285.2 MB

💾 batch 6130 → 14,341 рядків (всього 43,792 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6130.csv.gz

   ✅ після flush · 🧠 RAM: 287.3 MB

[160/7111] ✓ AGMI: 5 рядків |   2.25% | ETA 20:31

[170/7111] ✓ AGYS: 224 рядків |   2.39% | ETA 20:31

[180/7111] ✓ AIA: 200 рядків |   2.53% | ETA 20:25

[190/7111] ✓ AIFF: 142 рядків |   2.67% | ETA 20:20

[200/7111] ✓ AIN: 123 рядків |   2.81% | ETA 20:28

   • RAM · 🧠 RAM: 289.4 MB

   ⏳ перед flush · 🧠 RAM: 289.4 MB

💾 batch 6131 → 11,425 рядків (всього 55,217 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6131.csv.gz

   ✅ після flush · 🧠 RAM: 292.2 MB

[210/7111] ✓ AIRG: 90 рядків |   2.95% | ETA 20:26

[220/7111] ✓ AIXC: 56 рядків |   3.09% | ETA 20:23

[230/7111] ✓ AKTS: 102 рядків |   3.23% | ETA 20:21

[240/7111] ✓ ALCO: 18 рядків |   3.38% | ETA 20:17

[250/7111] ✓ ALHC: 384 рядків |   3.52% | ETA 20:12

   • RAM · 🧠 RAM: 293.3 MB

   ⏳ перед flush · 🧠 RAM: 293.4 MB

💾 batch 6132 → 13,030 рядків (всього 68,247 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6132.csv.gz

   ✅ після flush · 🧠 RAM: 294.4 MB

[260/7111] ✓ ALLW: 355 рядків |   3.66% | ETA 20:11

[270/7111] ✓ ALP: 1,162 рядків |   3.80% | ETA 20:05

[280/7111] ✓ ALVO: 214 рядків |   3.94% | ETA 20:19

[290/7111] ✓ AMBO: 19 рядків |   4.08% | ETA 20:29

[300/7111] ✓ AMDD: 476 рядків |   4.22% | ETA 20:26

   • RAM · 🧠 RAM: 295.7 MB

   ⏳ перед flush · 🧠 RAM: 295.7 MB

💾 batch 6133 → 15,185 рядків (всього 83,432 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6133.csv.gz

   ✅ після flush · 🧠 RAM: 295.8 MB

[310/7111] ✓ AMIX: 122 рядків |   4.36% | ETA 20:22

[320/7111] ✓ AMPL: 372 рядків |   4.50% | ETA 20:24

[330/7111] ✓ AMSC: 469 рядків |   4.64% | ETA 20:18

[340/7111] ✓ AMWD: 232 рядків |   4.78% | ETA 20:16

[350/7111] ✓ AMZU: 555 рядків |   4.92% | ETA 20:15

   • RAM · 🧠 RAM: 297.1 MB

   ⏳ перед flush · 🧠 RAM: 297.1 MB

💾 batch 6134 → 16,939 рядків (всього 100,371 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6134.csv.gz

   ✅ після flush · 🧠 RAM: 297.8 MB

[360/7111] ✓ ANET: 719 рядків |   5.06% | ETA 20:10

[370/7111] ✓ ANIX: 93 рядків |   5.20% | ETA 20:05

[380/7111] ✓ AOD: 244 рядків |   5.34% | ETA 20:06

[390/7111] ✓ AP: 198 рядків |   5.48% | ETA 20:03

[400/7111] ✓ API: 322 рядків |   5.63% | ETA 20:00

   • RAM · 🧠 RAM: 298.6 MB

   ⏳ перед flush · 🧠 RAM: 298.6 MB

💾 batch 6135 → 11,318 рядків (всього 111,689 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6135.csv.gz

   ✅ після flush · 🧠 RAM: 298.9 MB

[410/7111] ✓ APP: 671 рядків |   5.77% | ETA 20:01

[420/7111] ✓ AQB: 19 рядків |   5.91% | ETA 19:56

[430/7111] ✓ ARBE: 559 рядків |   6.05% | ETA 19:55

[440/7111] – AREB: empty |   6.19% | ETA 19:50

[450/7111] ✓ ARKF: 198 рядків |   6.33% | ETA 19:55

   • RAM · 🧠 RAM: 299.8 MB

   ⏳ перед flush · 🧠 RAM: 299.8 MB

💾 batch 6136 → 14,072 рядків (всього 125,761 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6136.csv.gz

   ✅ після flush · 🧠 RAM: 299.8 MB

[460/7111] ✓ ARMK: 382 рядків |   6.47% | ETA 19:51

[470/7111] ✓ ARQQW: 16 рядків |   6.61% | ETA 19:49

[480/7111] ✓ ARX: 359 рядків |   6.75% | ETA 19:49

[490/7111] ✓ ASGI: 165 рядків |   6.89% | ETA 19:48

[500/7111] ✓ ASML: 927 рядків |   7.03% | ETA 19:47

   • RAM · 🧠 RAM: 301.1 MB

   ⏳ перед flush · 🧠 RAM: 301.1 MB

💾 batch 6137 → 15,941 рядків (всього 141,702 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6137.csv.gz

   ✅ після flush · 🧠 RAM: 303.7 MB

[510/7111] ✓ ASTC: 101 рядків |   7.17% | ETA 19:45

[520/7111] ✓ ASUR: 89 рядків |   7.31% | ETA 19:43

[530/7111] ✓ ATEX: 162 рядків |   7.45% | ETA 19:38

[540/7111] ✓ ATNI: 103 рядків |   7.59% | ETA 19:39

[550/7111] ✓ ATS: 134 рядків |   7.73% | ETA 19:36

   • RAM · 🧠 RAM: 304.8 MB

   ⏳ перед flush · 🧠 RAM: 304.8 MB

💾 batch 6138 → 14,858 рядків (всього 156,560 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6138.csv.gz

   ✅ після flush · 🧠 RAM: 305.0 MB

[560/7111] ✓ AUMI: 16 рядків |   7.88% | ETA 19:34

[570/7111] ✓ AVAH: 316 рядків |   8.02% | ETA 19:30

[580/7111] ✓ AVES: 107 рядків |   8.16% | ETA 19:29

[590/7111] ✓ AVLN: 213 рядків |   8.30% | ETA 19:31

[600/7111] ✓ AVR: 374 рядків |   8.44% | ETA 19:28

   • RAM · 🧠 RAM: 305.8 MB

   ⏳ перед flush · 🧠 RAM: 305.8 MB

💾 batch 6139 → 13,404 рядків (всього 169,964 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6139.csv.gz

   ✅ після flush · 🧠 RAM: 306.9 MB

[610/7111] ✓ AWAY: 11 рядків |   8.58% | ETA 19:24

[620/7111] ✓ AXIA: 379 рядків |   8.72% | ETA 19:23

[630/7111] ✓ AXTU: 150 рядків |   8.86% | ETA 19:21

[640/7111] ✓ AZTA: 364 рядків |   9.00% | ETA 19:19

[650/7111] ✓ BABW: 3 рядків |   9.14% | ETA 19:16

   • RAM · 🧠 RAM: 307.2 MB

   ⏳ перед flush · 🧠 RAM: 307.2 MB

💾 batch 6140 → 12,838 рядків (всього 182,802 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6140.csv.gz

   ✅ після flush · 🧠 RAM: 307.2 MB

[660/7111] ✓ BAIG: 71 рядків |   9.28% | ETA 19:14

[670/7111] ✓ BAOS: 149 рядків |   9.42% | ETA 19:12

[680/7111] ✓ BBAI/W: 35 рядків |   9.56% | ETA 19:10

[690/7111] ✓ BBD: 409 рядків |   9.70% | ETA 19:08

[700/7111] ✓ BBSI: 157 рядків |   9.84% | ETA 19:07

   • RAM · 🧠 RAM: 303.2 MB

   ⏳ перед flush · 🧠 RAM: 303.2 MB

💾 batch 6141 → 12,502 рядків (всього 195,304 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6141.csv.gz

   ✅ після flush · 🧠 RAM: 303.8 MB

[710/7111] ✓ BCAR: 148 рядків |   9.98% | ETA 19:07

[720/7111] ✓ BCG: 31 рядків |  10.13% | ETA 19:04

[730/7111] ✓ BCSF: 141 рядків |  10.27% | ETA 19:01

[740/7111] ✓ BDRY: 49 рядків |  10.41% | ETA 19:00

[750/7111] ✓ BELFA: 103 рядків |  10.55% | ETA 18:59

   • RAM · 🧠 RAM: 302.5 MB

   ⏳ перед flush · 🧠 RAM: 302.5 MB

💾 batch 6142 → 10,084 рядків (всього 205,388 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6142.csv.gz

   ✅ після flush · 🧠 RAM: 303.4 MB

[760/7111] ✓ BETA: 376 рядків |  10.69% | ETA 18:57

[770/7111] ✓ BF.B: 387 рядків |  10.83% | ETA 18:54

[780/7111] ✓ BGI: 6 рядків |  10.97% | ETA 18:51

[790/7111] ✓ BGSI: 79 рядків |  11.11% | ETA 18:51

[800/7111] ✓ BHRB: 117 рядків |  11.25% | ETA 18:49

   • RAM · 🧠 RAM: 304.3 MB

   ⏳ перед flush · 🧠 RAM: 304.3 MB

💾 batch 6143 → 8,957 рядків (всього 214,345 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6143.csv.gz

   ✅ після flush · 🧠 RAM: 305.0 MB

[810/7111] ✓ BIL: 648 рядків |  11.39% | ETA 18:46

[820/7111] ✓ BIRD: 268 рядків |  11.53% | ETA 18:46

[830/7111] ✓ BITS: 8 рядків |  11.67% | ETA 18:42

[840/7111] ✓ BJDX: 55 рядків |  11.81% | ETA 18:40

[850/7111] ✓ BKLN: 385 рядків |  11.95% | ETA 18:39

   • RAM · 🧠 RAM: 306.3 MB

   ⏳ перед flush · 🧠 RAM: 306.3 MB

💾 batch 6144 → 14,444 рядків (всього 228,789 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6144.csv.gz

   ✅ після flush · 🧠 RAM: 307.7 MB

[860/7111] ✓ BLBD: 209 рядків |  12.09% | ETA 18:38

[870/7111] ✓ BLK: 350 рядків |  12.23% | ETA 18:35

[880/7111] ✓ BLSG: 75 рядків |  12.38% | ETA 18:34

[890/7111] ✓ BMEZ: 116 рядків |  12.52% | ETA 18:33

[900/7111] ✓ BMO: 367 рядків |  12.66% | ETA 18:29

   • RAM · 🧠 RAM: 308.9 MB

   ⏳ перед flush · 🧠 RAM: 308.9 MB

💾 batch 6145 → 14,024 рядків (всього 242,813 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6145.csv.gz

   ✅ після flush · 🧠 RAM: 309.8 MB

[910/7111] ✓ BND: 450 рядків |  12.80% | ETA 18:28

[920/7111] ✓ BNR: 15 рядків |  12.94% | ETA 18:27

[930/7111] ✓ BOC: 127 рядків |  13.08% | ETA 18:24

[940/7111] ✓ BOLT: 19 рядків |  13.22% | ETA 18:22

[950/7111] ✓ BOX: 498 рядків |  13.36% | ETA 18:21

   • RAM · 🧠 RAM: 304.5 MB

   ⏳ перед flush · 🧠 RAM: 304.5 MB

💾 batch 6146 → 11,085 рядків (всього 253,898 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6146.csv.gz

   ✅ після flush · 🧠 RAM: 305.5 MB

[960/7111] ✓ BRBR: 392 рядків |  13.50% | ETA 18:19

[970/7111] ✓ BRLS: 15 рядків |  13.64% | ETA 18:17

[980/7111] ✓ BRT: 26 рядків |  13.78% | ETA 18:15

[990/7111] ✓ BSCS: 210 рядків |  13.92% | ETA 18:13

[1000/7111] ✓ BTAI: 239 рядків |  14.06% | ETA 18:11

   • RAM · 🧠 RAM: 303.1 MB

   ⏳ перед flush · 🧠 RAM: 303.1 MB

💾 batch 6147 → 12,322 рядків (всього 266,220 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6147.csv.gz

   ✅ після flush · 🧠 RAM: 304.2 MB

[1010/7111] ✓ BTCT: 65 рядків |  14.20% | ETA 18:10

[1020/7111] ✓ BTI: 445 рядків |  14.34% | ETA 18:08

[1030/7111] ✓ BTTC: 43 рядків |  14.48% | ETA 18:08

[1040/7111] ✓ BULX: 64 рядків |  14.63% | ETA 18:06

[1050/7111] ✓ BVC: 3 рядків |  14.77% | ETA 18:04

   • RAM · 🧠 RAM: 308.1 MB

   ⏳ перед flush · 🧠 RAM: 308.1 MB

💾 batch 6148 → 28,407 рядків (всього 294,627 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6148.csv.gz

   ✅ після flush · 🧠 RAM: 310.0 MB

[1060/7111] ✓ BWIN: 370 рядків |  14.91% | ETA 18:02

[1070/7111] ✓ BXP: 312 рядків |  15.05% | ETA 18:00

[1080/7111] ✓ BZFD: 424 рядків |  15.19% | ETA 17:58

[1090/7111] ✓ CACC: 121 рядків |  15.33% | ETA 17:57

[1100/7111] ✓ CAKE: 350 рядків |  15.47% | ETA 17:56

   • RAM · 🧠 RAM: 304.3 MB

   ⏳ перед flush · 🧠 RAM: 304.3 MB

💾 batch 6149 → 13,468 рядків (всього 308,095 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6149.csv.gz

   ✅ після flush · 🧠 RAM: 303.1 MB

[1110/7111] ✓ CANF: 23 рядків |  15.61% | ETA 17:54

[1120/7111] ✓ CARR: 415 рядків |  15.75% | ETA 17:51

[1130/7111] ✓ CATY: 236 рядків |  15.89% | ETA 17:50

[1140/7111] ✓ CBNK: 52 рядків |  16.03% | ETA 17:47

[1150/7111] ✓ CBUS: 140 рядків |  16.17% | ETA 17:45

   • RAM · 🧠 RAM: 302.9 MB

   ⏳ перед flush · 🧠 RAM: 302.9 MB

💾 batch 6150 → 13,621 рядків (всього 321,716 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6150.csv.gz

   ✅ після flush · 🧠 RAM: 302.9 MB

[1160/7111] ✓ CCEP: 369 рядків |  16.31% | ETA 17:43

[1170/7111] ✓ CCO: 396 рядків |  16.45% | ETA 17:42

[1180/7111] ✓ CDIO: 87 рядків |  16.59% | ETA 17:40

[1190/7111] ✓ CDXS: 315 рядків |  16.73% | ETA 17:39

[1200/7111] – CELT: empty |  16.88% | ETA 17:37

   • RAM · 🧠 RAM: 299.7 MB

   ⏳ перед flush · 🧠 RAM: 299.7 MB

💾 batch 6151 → 13,327 рядків (всього 335,043 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6151.csv.gz

   ✅ після flush · 🧠 RAM: 299.7 MB

[1210/7111] ✓ CERS: 354 рядків |  17.02% | ETA 17:38

[1220/7111] – CFLT: empty |  17.16% | ETA 17:36

[1230/7111] ✓ CGDG: 320 рядків |  17.30% | ETA 17:34

[1240/7111] ✓ CGNT: 259 рядків |  17.44% | ETA 17:34

[1250/7111] ✓ CHAI: 68 рядків |  17.58% | ETA 17:32

   • RAM · 🧠 RAM: 299.3 MB

   ⏳ перед flush · 🧠 RAM: 299.3 MB

💾 batch 6152 → 12,869 рядків (всього 347,912 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6152.csv.gz

   ✅ після flush · 🧠 RAM: 299.5 MB

[1260/7111] ✓ CHI: 100 рядків |  17.72% | ETA 17:31

[1270/7111] ✓ CHRD: 241 рядків |  17.86% | ETA 17:32

[1280/7111] ✓ CI: 394 рядків |  18.00% | ETA 17:30

[1290/7111] ✓ CIG.C: 6 рядків |  18.14% | ETA 17:28

[1300/7111] ✓ CION: 182 рядків |  18.28% | ETA 17:28

   • RAM · 🧠 RAM: 299.2 MB

   ⏳ перед flush · 🧠 RAM: 299.2 MB

💾 batch 6153 → 11,802 рядків (всього 359,714 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6153.csv.gz

   ✅ після flush · 🧠 RAM: 301.4 MB

[1310/7111] ✓ CLDI: 409 рядків |  18.42% | ETA 17:28

[1320/7111] ✓ CLIR: 41 рядків |  18.56% | ETA 17:26

[1330/7111] ✓ CLPS: 11 рядків |  18.70% | ETA 17:26

[1340/7111] ✓ CLX: 405 рядків |  18.84% | ETA 17:29

[1350/7111] ✓ CMCT: 34 рядків |  18.98% | ETA 17:32

   • RAM · 🧠 RAM: 302.1 MB

   ⏳ перед flush · 🧠 RAM: 302.1 MB

💾 batch 6154 → 10,822 рядків (всього 370,536 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6154.csv.gz

   ✅ після flush · 🧠 RAM: 303.4 MB

[1360/7111] ✓ CMPR: 137 рядків |  19.13% | ETA 17:33

[1370/7111] ✓ CNCG: 1 рядків |  19.27% | ETA 17:35

[1380/7111] ✓ CNMD: 241 рядків |  19.41% | ETA 17:36

[1390/7111] ✓ CNTB: 181 рядків |  19.55% | ETA 17:37

[1400/7111] ✓ CNYA: 52 рядків |  19.69% | ETA 17:39

   • RAM · 🧠 RAM: 308.6 MB

   ⏳ перед flush · 🧠 RAM: 308.6 MB

💾 batch 6155 → 12,363 рядків (всього 382,899 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6155.csv.gz

   ✅ після flush · 🧠 RAM: 311.1 MB

[1410/7111] ✓ COF: 398 рядків |  19.83% | ETA 17:39

[1420/7111] ✓ COIG: 147 рядків |  19.97% | ETA 17:37

[1430/7111] ✓ COM: 148 рядків |  20.11% | ETA 17:35

[1440/7111] ✓ COOK: 72 рядків |  20.25% | ETA 17:34

[1450/7111] ✓ CORN: 249 рядків |  20.39% | ETA 17:32

   • RAM · 🧠 RAM: 313.5 MB

   ⏳ перед flush · 🧠 RAM: 313.5 MB

💾 batch 6156 → 14,192 рядків (всього 397,091 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6156.csv.gz

   ✅ після flush · 🧠 RAM: 313.2 MB

[1460/7111] ✓ COST: 498 рядків |  20.53% | ETA 17:29

[1470/7111] ✓ CPB: 445 рядків |  20.67% | ETA 17:28

[1480/7111] ✓ CPS: 126 рядків |  20.81% | ETA 17:26

[1490/7111] ✓ CRAI: 67 рядків |  20.95% | ETA 17:24

[1500/7111] ✓ CRCO: 132 рядків |  21.09% | ETA 17:23

   • RAM · 🧠 RAM: 305.7 MB

   ⏳ перед flush · 🧠 RAM: 305.7 MB

💾 batch 6157 → 15,451 рядків (всього 412,542 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6157.csv.gz

   ✅ після flush · 🧠 RAM: 305.9 MB

[1510/7111] ✓ CRF: 286 рядків |  21.23% | ETA 17:21

[1520/7111] ✓ CRMG: 522 рядків |  21.38% | ETA 17:19

[1530/7111] ✓ CRPT: 66 рядків |  21.52% | ETA 17:17

[1540/7111] ✓ CRVL: 133 рядків |  21.66% | ETA 17:15

[1550/7111] ✓ CSCL: 118 рядків |  21.80% | ETA 17:14

   • RAM · 🧠 RAM: 306.0 MB

   ⏳ перед flush · 🧠 RAM: 306.0 MB

💾 batch 6158 → 15,329 рядків (всього 427,871 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6158.csv.gz

   ✅ після flush · 🧠 RAM: 307.9 MB

[1560/7111] ✓ CSR: 61 рядків |  21.94% | ETA 17:12

[1570/7111] ✓ CTA: 324 рядків |  22.08% | ETA 17:10

[1580/7111] ✓ CTO: 171 рядків |  22.22% | ETA 17:09

[1590/7111] ✓ CTW: 10 рядків |  22.36% | ETA 17:07

[1600/7111] ✓ CURI: 193 рядків |  22.50% | ETA 17:04

   • RAM · 🧠 RAM: 302.9 MB

   ⏳ перед flush · 🧠 RAM: 302.9 MB

💾 batch 6159 → 11,317 рядків (всього 439,188 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6159.csv.gz

   ✅ після flush · 🧠 RAM: 304.4 MB

[1610/7111] ✓ CVGI: 249 рядків |  22.64% | ETA 17:02

[1620/7111] ✓ CVRX: 91 рядків |  22.78% | ETA 17:01

[1630/7111] ✓ CWEB: 340 рядків |  22.92% | ETA 16:59

[1640/7111] ✓ CWVX: 592 рядків |  23.06% | ETA 16:58

[1650/7111] ✓ CXW: 294 рядків |  23.20% | ETA 16:57

   • RAM · 🧠 RAM: 306.3 MB

   ⏳ перед flush · 🧠 RAM: 306.3 MB

💾 batch 6160 → 11,785 рядків (всього 450,973 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6160.csv.gz

   ✅ після flush · 🧠 RAM: 306.5 MB

[1660/7111] ✓ CZR: 374 рядків |  23.34% | ETA 16:58

[1670/7111] ✓ DAPP: 362 рядків |  23.48% | ETA 16:56

[1680/7111] ✓ DB: 447 рядків |  23.63% | ETA 16:55

[1690/7111] ✓ DBRG: 301 рядків |  23.77% | ETA 16:55

[1700/7111] ✓ DCOY: 37 рядків |  23.91% | ETA 16:53

   • RAM · 🧠 RAM: 308.0 MB

   ⏳ перед flush · 🧠 RAM: 308.0 MB

💾 batch 6161 → 12,757 рядків (всього 463,730 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6161.csv.gz

   ✅ після flush · 🧠 RAM: 308.2 MB

[1710/7111] ✓ DDOG: 460 рядків |  24.05% | ETA 16:51

[1720/7111] ✓ DEO: 366 рядків |  24.19% | ETA 16:50

[1730/7111] ✓ DFDV: 345 рядків |  24.33% | ETA 16:49

[1740/7111] ✓ DFSC: 121 рядків |  24.47% | ETA 16:47

[1750/7111] ✓ DGRW: 355 рядків |  24.61% | ETA 16:48

   • RAM · 🧠 RAM: 309.6 MB

   ⏳ перед flush · 🧠 RAM: 309.6 MB

💾 batch 6162 → 14,836 рядків (всього 478,566 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6162.csv.gz

   ✅ після flush · 🧠 RAM: 310.3 MB

[1760/7111] ✓ DHR: 399 рядків |  24.75% | ETA 16:46

[1770/7111] ✓ DIOD: 350 рядків |  24.89% | ETA 16:44

[1780/7111] ✓ DJP: 63 рядків |  25.03% | ETA 16:43

[1790/7111] ✓ DLHC: 7 рядків |  25.17% | ETA 16:42

[1800/7111] ✓ DLY: 135 рядків |  25.31% | ETA 16:40

   • RAM · 🧠 RAM: 311.1 MB

   ⏳ перед flush · 🧠 RAM: 311.1 MB

💾 batch 6163 → 11,373 рядків (всього 489,939 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6163.csv.gz

   ✅ після flush · 🧠 RAM: 312.7 MB

[1810/7111] ✓ DNOW: 387 рядків |  25.45% | ETA 16:39

[1820/7111] ✓ DOGZ: 39 рядків |  25.59% | ETA 16:37

[1830/7111] ✓ DOX: 333 рядків |  25.73% | ETA 16:35

[1840/7111] ✓ DRI: 339 рядків |  25.88% | ETA 16:33

[1850/7111] ✓ DRNZ: 167 рядків |  26.02% | ETA 16:32

   • RAM · 🧠 RAM: 313.8 MB

   ⏳ перед flush · 🧠 RAM: 313.8 MB

💾 batch 6164 → 12,887 рядків (всього 502,826 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6164.csv.gz

   ✅ після flush · 🧠 RAM: 314.0 MB

[1860/7111] ✓ DSS: 28 рядків |  26.16% | ETA 16:30

[1870/7111] ✓ DTIL: 261 рядків |  26.30% | ETA 16:29

[1880/7111] ✓ DUOG: 32 рядків |  26.44% | ETA 16:27

[1890/7111] ✓ DVY: 270 рядків |  26.58% | ETA 16:25

[1900/7111] ✓ DXLG: 25 рядків |  26.72% | ETA 16:23

   • RAM · 🧠 RAM: 315.0 MB

   ⏳ перед flush · 🧠 RAM: 315.0 MB

💾 batch 6165 → 10,865 рядків (всього 513,691 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6165.csv.gz

   ✅ після flush · 🧠 RAM: 316.3 MB

[1910/7111] ✓ EA: 356 рядків |  26.86% | ETA 16:22

[1920/7111] ✓ EBMT: 89 рядків |  27.00% | ETA 16:20

[1930/7111] ✓ ECL: 398 рядків |  27.14% | ETA 16:24

[1940/7111] ✓ EDGQ: 15 рядків |  27.28% | ETA 16:22

[1950/7111] ✓ EDU: 394 рядків |  27.42% | ETA 16:23

   • RAM · 🧠 RAM: 317.4 MB

   ⏳ перед flush · 🧠 RAM: 317.4 MB

💾 batch 6166 → 11,838 рядків (всього 525,529 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6166.csv.gz

   ✅ після flush · 🧠 RAM: 316.9 MB

[1960/7111] ✓ EFC: 335 рядків |  27.56% | ETA 16:20

[1970/7111] ✓ EFXT: 288 рядків |  27.70% | ETA 16:19

[1980/7111] ✓ EHC: 297 рядків |  27.84% | ETA 16:17

[1990/7111] ✓ EIX: 381 рядків |  27.98% | ETA 16:18

[2000/7111] – ELIS: empty |  28.13% | ETA 16:18

   • RAM · 🧠 RAM: 317.1 MB

   ⏳ перед flush · 🧠 RAM: 317.1 MB

💾 batch 6167 → 10,769 рядків (всього 536,298 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6167.csv.gz

   ✅ після flush · 🧠 RAM: 318.1 MB

[2010/7111] ✓ ELTK: 21 рядків |  28.27% | ETA 16:16

[2020/7111] ✓ EMBJ: 387 рядків |  28.41% | ETA 16:14

[2030/7111] ✓ EMXC: 399 рядків |  28.55% | ETA 16:12

[2040/7111] ✓ ENLV: 211 рядків |  28.69% | ETA 16:10

[2050/7111] ✓ ENTX: 29 рядків |  28.83% | ETA 16:09

   • RAM · 🧠 RAM: 309.4 MB

   ⏳ перед flush · 🧠 RAM: 309.4 MB

💾 batch 6168 → 12,273 рядків (всього 548,571 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6168.csv.gz

   ✅ після flush · 🧠 RAM: 310.5 MB

[2060/7111] ✓ EOSU: 148 рядків |  28.97% | ETA 16:07

[2070/7111] ✓ EPOW: 147 рядків |  29.11% | ETA 16:05

[2080/7111] ✓ EQH: 388 рядків |  29.25% | ETA 16:03

[2090/7111] ✓ ERII: 262 рядків |  29.39% | ETA 16:01

[2100/7111] ✓ ESEA: 122 рядків |  29.53% | ETA 15:59

   • RAM · 🧠 RAM: 306.4 MB

   ⏳ перед flush · 🧠 RAM: 306.4 MB

💾 batch 6169 → 13,203 рядків (всього 561,774 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6169.csv.gz

   ✅ після flush · 🧠 RAM: 308.4 MB

[2110/7111] ✓ ESPO: 58 рядків |  29.67% | ETA 15:57

[2120/7111] ✓ ETD: 197 рядків |  29.81% | ETA 15:55

[2130/7111] ✓ ETHV: 103 рядків |  29.95% | ETA 15:53

[2140/7111] ✓ ETS: 18 рядків |  30.09% | ETA 15:51

[2150/7111] ✓ EUM: 41 рядків |  30.23% | ETA 15:49

   • RAM · 🧠 RAM: 310.8 MB

   ⏳ перед flush · 🧠 RAM: 310.8 MB

💾 batch 6170 → 12,331 рядків (всього 574,105 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6170.csv.gz

   ✅ після flush · 🧠 RAM: 311.9 MB

[2160/7111] ✓ EVGO: 419 рядків |  30.38% | ETA 15:47

[2170/7111] ✓ EVTL: 474 рядків |  30.52% | ETA 15:44

[2180/7111] ✓ EWG: 260 рядків |  30.66% | ETA 15:43

[2190/7111] ✓ EWP: 223 рядків |  30.80% | ETA 15:41

[2200/7111] – EXAS: empty |  30.94% | ETA 15:39

   • RAM · 🧠 RAM: 313.0 MB

   ⏳ перед flush · 🧠 RAM: 313.0 MB

💾 batch 6171 → 13,511 рядків (всього 587,616 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6171.csv.gz

   ✅ після flush · 🧠 RAM: 313.1 MB

[2210/7111] ✓ EXPD: 300 рядків |  31.08% | ETA 15:38

[2220/7111] ✓ EZA: 134 рядків |  31.22% | ETA 15:35

[2230/7111] ✓ FABC: 385 рядків |  31.36% | ETA 15:33

[2240/7111] ✓ FATN: 224 рядків |  31.50% | ETA 15:31

[2250/7111] ✓ FBLG: 39 рядків |  31.64% | ETA 15:29

   • RAM · 🧠 RAM: 314.0 MB

   ⏳ перед flush · 🧠 RAM: 314.0 MB

💾 batch 6172 → 13,001 рядків (всього 600,617 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6172.csv.gz

   ✅ після flush · 🧠 RAM: 315.0 MB

[2260/7111] ✓ FC: 66 рядків |  31.78% | ETA 15:27

[2270/7111] – FCO: empty |  31.92% | ETA 15:26

[2280/7111] ✓ FDL: 355 рядків |  32.06% | ETA 15:24

[2290/7111] ✓ FEAM: 124 рядків |  32.20% | ETA 15:23

[2300/7111] ✓ FENY: 388 рядків |  32.34% | ETA 15:21

   • RAM · 🧠 RAM: 315.7 MB

   ⏳ перед flush · 🧠 RAM: 315.7 MB

💾 batch 6173 → 11,862 рядків (всього 612,479 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6173.csv.gz

   ✅ після flush · 🧠 RAM: 315.5 MB

[2310/7111] ✓ FFBC: 321 рядків |  32.48% | ETA 15:19

[2320/7111] ✓ FGL: 249 рядків |  32.63% | ETA 15:18

[2330/7111] ✓ FIBK: 348 рядків |  32.77% | ETA 15:16

[2340/7111] ✓ FINX: 99 рядків |  32.91% | ETA 15:14

[2350/7111] ✓ FIVY: 13 рядків |  33.05% | ETA 15:12

   • RAM · 🧠 RAM: 315.4 MB

   ⏳ перед flush · 🧠 RAM: 315.4 MB

💾 batch 6174 → 12,742 рядків (всього 625,221 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6174.csv.gz

   ✅ після flush · 🧠 RAM: 317.5 MB

[2360/7111] ✓ FLGB: 44 рядків |  33.19% | ETA 15:10

[2370/7111] ✓ FLNC: 767 рядків |  33.33% | ETA 15:08

[2380/7111] ✓ FLTW: 319 рядків |  33.47% | ETA 15:06

[2390/7111] ✓ FLYW: 403 рядків |  33.61% | ETA 15:05

[2400/7111] ✓ FMX: 224 рядків |  33.75% | ETA 15:03

   • RAM · 🧠 RAM: 318.4 MB

   ⏳ перед flush · 🧠 RAM: 318.4 MB

💾 batch 6175 → 12,682 рядків (всього 637,903 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6175.csv.gz

   ✅ після flush · 🧠 RAM: 318.5 MB

[2410/7111] ✓ FNDX: 403 рядків |  33.89% | ETA 15:01

[2420/7111] ✓ FNUC: 234 рядків |  34.03% | ETA 14:59

[2430/7111] ✓ FOUR: 321 рядків |  34.17% | ETA 14:57

[2440/7111] ✓ FR: 280 рядків |  34.31% | ETA 14:55

[2450/7111] ✓ FRMM: 273 рядків |  34.45% | ETA 14:54

   • RAM · 🧠 RAM: 319.6 MB

   ⏳ перед flush · 🧠 RAM: 319.6 MB

💾 batch 6176 → 10,768 рядків (всього 648,671 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6176.csv.gz

   ✅ після flush · 🧠 RAM: 319.7 MB

[2460/7111] ✓ FRT: 304 рядків |  34.59% | ETA 14:52

[2470/7111] ✓ FSTA: 168 рядків |  34.73% | ETA 14:50

[2480/7111] – FTEL: empty |  34.88% | ETA 14:48

[2490/7111] ✓ FTRE: 274 рядків |  35.02% | ETA 14:46

[2500/7111] ✓ FUL: 311 рядків |  35.16% | ETA 14:44

   • RAM · 🧠 RAM: 320.7 MB

   ⏳ перед flush · 🧠 RAM: 320.7 MB

💾 batch 6177 → 12,483 рядків (всього 661,154 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6177.csv.gz

   ✅ після flush · 🧠 RAM: 321.3 MB

[2510/7111] ✓ FVCB: 125 рядків |  35.30% | ETA 14:43

[2520/7111] ✓ FXA: 14 рядків |  35.44% | ETA 14:41

[2530/7111] ✓ FXY: 113 рядків |  35.58% | ETA 14:39

[2540/7111] ✓ GANX: 317 рядків |  35.72% | ETA 14:37

[2550/7111] ✓ GBFH: 54 рядків |  35.86% | ETA 14:35

   • RAM · 🧠 RAM: 322.2 MB

   ⏳ перед flush · 🧠 RAM: 322.2 MB

💾 batch 6178 → 11,914 рядків (всього 673,068 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6178.csv.gz

   ✅ після flush · 🧠 RAM: 323.4 MB

[2560/7111] ✓ GCL: 324 рядків |  36.00% | ETA 14:33

[2570/7111] ✓ GDC: 930 рядків |  36.14% | ETA 14:31

[2580/7111] ✓ GDXD: 388 рядків |  36.28% | ETA 14:30

[2590/7111] ✓ GEF.B: 21 рядків |  36.42% | ETA 14:29

[2600/7111] ✓ GENI: 415 рядків |  36.56% | ETA 14:27

   • RAM · 🧠 RAM: 320.4 MB

   ⏳ перед flush · 🧠 RAM: 320.4 MB

💾 batch 6179 → 13,609 рядків (всього 686,677 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6179.csv.gz

   ✅ після flush · 🧠 RAM: 318.5 MB

[2610/7111] ✓ GFF: 145 рядків |  36.70% | ETA 14:25

[2620/7111] ✓ GGN: 147 рядків |  36.84% | ETA 14:23

[2630/7111] ✓ GIB: 268 рядків |  36.98% | ETA 14:22

[2640/7111] ✓ GII: 40 рядків |  37.13% | ETA 14:20

[2650/7111] ✓ GLD: 928 рядків |  37.27% | ETA 14:18

   • RAM · 🧠 RAM: 314.7 MB

   ⏳ перед flush · 🧠 RAM: 314.7 MB

💾 batch 6180 → 13,457 рядків (всього 700,134 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6180.csv.gz

   ✅ після flush · 🧠 RAM: 314.8 MB

[2660/7111] ✓ GLIBA: 90 рядків |  37.41% | ETA 14:16

[2670/7111] ✓ GLOO: 56 рядків |  37.55% | ETA 14:14

[2680/7111] ✓ GLXG: 11 рядків |  37.69% | ETA 14:13

[2690/7111] ✓ GMEY: 2 рядків |  37.83% | ETA 14:11

[2700/7111] ✓ GNLX: 93 рядків |  37.97% | ETA 14:09

   • RAM · 🧠 RAM: 311.1 MB

   ⏳ перед flush · 🧠 RAM: 311.1 MB

💾 batch 6181 → 11,780 рядків (всього 711,914 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6181.csv.gz

   ✅ після flush · 🧠 RAM: 311.2 MB

[2710/7111] ✓ GO: 374 рядків |  38.11% | ETA 14:08

[2720/7111] ✓ GOLY: 69 рядків |  38.25% | ETA 14:07

[2730/7111] ✓ GOSS: 494 рядків |  38.39% | ETA 14:06

[2740/7111] ✓ GPIQ: 521 рядків |  38.53% | ETA 14:05

[2750/7111] ✓ GPT: 3 рядків |  38.67% | ETA 14:03

   • RAM · 🧠 RAM: 311.3 MB

   ⏳ перед flush · 🧠 RAM: 311.3 MB

💾 batch 6182 → 14,449 рядків (всього 726,363 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6182.csv.gz

   ✅ після flush · 🧠 RAM: 312.8 MB

[2760/7111] ✓ GRCE: 137 рядків |  38.81% | ETA 14:01

[2770/7111] ✓ GRNI: 29 рядків |  38.95% | ETA 14:00

[2780/7111] ✓ GRRR: 541 рядків |  39.09% | ETA 13:58

[2790/7111] ✓ GSL: 323 рядків |  39.23% | ETA 13:56

[2800/7111] ✓ GTEC: 58 рядків |  39.38% | ETA 13:54

   • RAM · 🧠 RAM: 313.7 MB

   ⏳ перед flush · 🧠 RAM: 313.7 MB

💾 batch 6183 → 12,964 рядків (всього 739,327 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6183.csv.gz

   ✅ після flush · 🧠 RAM: 313.9 MB

[2810/7111] ✓ GUSH: 426 рядків |  39.52% | ETA 13:52

[2820/7111] ✓ GWRS: 180 рядків |  39.66% | ETA 13:51

[2830/7111] ✓ HAFC: 141 рядків |  39.80% | ETA 13:49

[2840/7111] ✓ HAYW: 357 рядків |  39.94% | ETA 13:47

[2850/7111] ✓ HCC: 343 рядків |  40.08% | ETA 13:46

   • RAM · 🧠 RAM: 314.6 MB

   ⏳ перед flush · 🧠 RAM: 314.6 MB

💾 batch 6184 → 12,764 рядків (всього 752,091 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6184.csv.gz

   ✅ після flush · 🧠 RAM: 315.2 MB

[2860/7111] ✓ HDB: 418 рядків |  40.22% | ETA 13:44

[2870/7111] ✓ HELP: 315 рядків |  40.36% | ETA 13:43

[2880/7111] ✓ HG: 243 рядків |  40.50% | ETA 13:41

[2890/7111] ✓ HIHO: 15 рядків |  40.64% | ETA 13:39

[2900/7111] ✓ HIW: 361 рядків |  40.78% | ETA 13:37

   • RAM · 🧠 RAM: 317.8 MB

   ⏳ перед flush · 🧠 RAM: 317.8 MB

💾 batch 6185 → 13,286 рядків (всього 765,377 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6185.csv.gz

   ✅ після flush · 🧠 RAM: 320.3 MB

[2910/7111] ✓ HLF: 372 рядків |  40.92% | ETA 13:35

[2920/7111] ✓ HMC: 389 рядків |  41.06% | ETA 13:33

[2930/7111] ✓ HODU: 126 рядків |  41.20% | ETA 13:32

[2940/7111] ✓ HOOG: 360 рядків |  41.34% | ETA 13:30

[2950/7111] ✓ HOVR: 759 рядків |  41.49% | ETA 13:28

   • RAM · 🧠 RAM: 321.5 MB

   ⏳ перед flush · 🧠 RAM: 321.5 MB

💾 batch 6186 → 14,269 рядків (всього 779,646 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6186.csv.gz

   ✅ після flush · 🧠 RAM: 321.9 MB

[2960/7111] ✓ HQI: 19 рядків |  41.63% | ETA 13:26

[2970/7111] ✓ HSAI: 442 рядків |  41.77% | ETA 13:24

[2980/7111] ✓ HTB: 49 рядків |  41.91% | ETA 13:22

[2990/7111] ✓ HTLD: 283 рядків |  42.05% | ETA 13:20

[3000/7111] ✓ HUDI: 25 рядків |  42.19% | ETA 13:18

   • RAM · 🧠 RAM: 323.2 MB

   ⏳ перед flush · 🧠 RAM: 323.2 MB

💾 batch 6187 → 13,813 рядків (всього 793,459 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6187.csv.gz

   ✅ після flush · 🧠 RAM: 323.9 MB

[3010/7111] ✓ HUYA: 375 рядків |  42.33% | ETA 13:16

[3020/7111] ✓ HYDR: 247 рядків |  42.47% | ETA 13:14

[3030/7111] ✓ HYPR: 368 рядків |  42.61% | ETA 13:13

[3040/7111] ✓ IAT: 137 рядків |  42.75% | ETA 13:11

[3050/7111] ✓ IBG: 60 рядків |  42.89% | ETA 13:09

   • RAM · 🧠 RAM: 324.8 MB

   ⏳ перед flush · 🧠 RAM: 324.8 MB

💾 batch 6188 → 12,308 рядків (всього 805,767 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6188.csv.gz

   ✅ після flush · 🧠 RAM: 326.5 MB

[3060/7111] ✓ IBP: 280 рядків |  43.03% | ETA 13:07

[3070/7111] ✓ ICG: 31 рядків |  43.17% | ETA 13:05

[3080/7111] ✓ ICU: 115 рядків |  43.31% | ETA 13:04

[3090/7111] ✓ IDMO: 274 рядків |  43.45% | ETA 13:02

[3100/7111] ✓ IDYA: 272 рядків |  43.59% | ETA 13:00

   • RAM · 🧠 RAM: 331.5 MB

   ⏳ перед flush · 🧠 RAM: 331.5 MB

💾 batch 6189 → 12,578 рядків (всього 818,345 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6189.csv.gz

   ✅ після flush · 🧠 RAM: 333.2 MB

[3110/7111] ✓ IEUR: 367 рядків |  43.74% | ETA 12:58

[3120/7111] ✓ IGD: 231 рядків |  43.88% | ETA 12:56

[3130/7111] ✓ IGR: 380 рядків |  44.02% | ETA 12:54

[3140/7111] ✓ IHT: 7 рядків |  44.16% | ETA 12:53

[3150/7111] ✓ IJH: 407 рядків |  44.30% | ETA 12:51

   • RAM · 🧠 RAM: 323.0 MB

   ⏳ перед flush · 🧠 RAM: 323.0 MB

💾 batch 6190 → 12,322 рядків (всього 830,667 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6190.csv.gz

   ✅ після flush · 🧠 RAM: 324.1 MB

[3160/7111] ✓ ILPT: 244 рядків |  44.44% | ETA 12:49

[3170/7111] ✓ IMMX: 387 рядків |  44.58% | ETA 12:47

[3180/7111] ✓ IMST: 51 рядків |  44.72% | ETA 12:45

[3190/7111] ✓ INBS: 104 рядків |  44.86% | ETA 12:43

[3200/7111] ✓ INDP: 55 рядків |  45.00% | ETA 12:41

   • RAM · 🧠 RAM: 318.2 MB

   ⏳ перед flush · 🧠 RAM: 318.2 MB

💾 batch 6191 → 10,520 рядків (всього 841,187 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6191.csv.gz

   ✅ після flush · 🧠 RAM: 319.6 MB

[3210/7111] ✓ INGN: 204 рядків |  45.14% | ETA 12:39

[3220/7111] ✓ INN: 304 рядків |  45.28% | ETA 12:37

[3230/7111] ✓ INTA: 296 рядків |  45.42% | ETA 12:35

[3240/7111] ✓ INV: 487 рядків |  45.56% | ETA 12:33

[3250/7111] ✓ IONQ/W: 27 рядків |  45.70% | ETA 12:32

   • RAM · 🧠 RAM: 321.2 MB

   ⏳ перед flush · 🧠 RAM: 321.2 MB

💾 batch 6192 → 15,246 рядків (всього 856,433 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6192.csv.gz

   ✅ після flush · 🧠 RAM: 322.3 MB

[3260/7111] ✓ IOYY: 63 рядків |  45.84% | ETA 12:30

[3270/7111] ✓ IPST: 89 рядків |  45.99% | ETA 12:28

[3280/7111] ✓ IRD: 260 рядків |  46.13% | ETA 12:26

[3290/7111] ✓ IRON: 172 рядків |  46.27% | ETA 12:24

[3300/7111] ✓ ISRA: 14 рядків |  46.41% | ETA 12:22

   • RAM · 🧠 RAM: 323.7 MB

   ⏳ перед flush · 🧠 RAM: 323.7 MB

💾 batch 6193 → 14,917 рядків (всього 871,350 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6193.csv.gz

   ✅ після flush · 🧠 RAM: 323.9 MB

[3310/7111] ✓ ITDF: 35 рядків |  46.55% | ETA 12:21

[3320/7111] ✓ ITT: 260 рядків |  46.69% | ETA 12:19

[3330/7111] ✓ IVE: 346 рядків |  46.83% | ETA 12:17

[3340/7111] ✓ IVV: 572 рядків |  46.97% | ETA 12:15

[3350/7111] ✓ IWMY: 67 рядків |  47.11% | ETA 12:13

   • RAM · 🧠 RAM: 325.0 MB

   ⏳ перед flush · 🧠 RAM: 325.0 MB

💾 batch 6194 → 12,644 рядків (всього 883,994 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6194.csv.gz

   ✅ після flush · 🧠 RAM: 325.7 MB

[3360/7111] ✓ IXJ: 101 рядків |  47.25% | ETA 12:12

[3370/7111] ✓ IYRI: 98 рядків |  47.39% | ETA 12:10

[3380/7111] ✓ JAGU: 86 рядків |  47.53% | ETA 12:08

[3390/7111] ✓ JBIO: 291 рядків |  47.67% | ETA 12:06

[3400/7111] ✓ JCSE: 11 рядків |  47.81% | ETA 12:04

   • RAM · 🧠 RAM: 326.4 MB

   ⏳ перед flush · 🧠 RAM: 326.4 MB

💾 batch 6195 → 12,587 рядків (всього 896,581 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6195.csv.gz

   ✅ після flush · 🧠 RAM: 327.0 MB

[3410/7111] ✓ JETD: 70 рядків |  47.95% | ETA 12:02

[3420/7111] ✓ JGRO: 365 рядків |  48.09% | ETA 12:00

[3430/7111] ✓ JMBS: 247 рядків |  48.24% | ETA 11:58

[3440/7111] ✓ JOBX: 194 рядків |  48.38% | ETA 11:57

[3450/7111] ✓ JPIN: 24 рядків |  48.52% | ETA 11:55

   • RAM · 🧠 RAM: 328.2 MB

   ⏳ перед flush · 🧠 RAM: 328.2 MB

💾 batch 6196 → 12,662 рядків (всього 909,243 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6196.csv.gz

   ✅ після flush · 🧠 RAM: 330.8 MB

[3460/7111] ✓ JSI: 148 рядків |  48.66% | ETA 11:53

[3470/7111] ✓ JZ: 32 рядків |  48.80% | ETA 11:51

[3480/7111] ✓ KBA: 65 рядків |  48.94% | ETA 11:49

[3490/7111] ✓ KCOP: 49 рядків |  49.08% | ETA 11:47

[3500/7111] ✓ KELYA: 225 рядків |  49.22% | ETA 11:45

   • RAM · 🧠 RAM: 331.8 MB

   ⏳ перед flush · 🧠 RAM: 331.8 MB

💾 batch 6197 → 10,405 рядків (всього 919,648 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6197.csv.gz

   ✅ після flush · 🧠 RAM: 331.8 MB

[3510/7111] ✓ KGRN: 20 рядків |  49.36% | ETA 11:44

[3520/7111] ✓ KIO: 121 рядків |  49.50% | ETA 11:42

[3530/7111] ✓ KLRA: 275 рядків |  49.64% | ETA 11:40

[3540/7111] ✓ KMLM: 152 рядків |  49.78% | ETA 11:38

[3550/7111] ✓ KNOP: 115 рядків |  49.92% | ETA 11:36

   • RAM · 🧠 RAM: 332.8 MB

   ⏳ перед flush · 🧠 RAM: 332.8 MB

💾 batch 6198 → 12,463 рядків (всього 932,111 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6198.csv.gz

   ✅ після flush · 🧠 RAM: 333.8 MB

[3560/7111] ✓ KOID: 326 рядків |  50.06% | ETA 11:34

[3570/7111] ✓ KPDD: 189 рядків |  50.20% | ETA 11:33

[3580/7111] ✓ KRMD: 102 рядків |  50.34% | ETA 11:31

[3590/7111] ✓ KRP: 376 рядків |  50.49% | ETA 11:29

[3600/7111] ✓ KTB: 333 рядків |  50.63% | ETA 11:27

   • RAM · 🧠 RAM: 334.8 MB

   ⏳ перед flush · 🧠 RAM: 334.8 MB

💾 batch 6199 → 12,892 рядків (всього 945,003 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6199.csv.gz

   ✅ після flush · 🧠 RAM: 335.5 MB

[3610/7111] ✓ KVYO: 530 рядків |  50.77% | ETA 11:25

[3620/7111] ✓ KYNB: 15 рядків |  50.91% | ETA 11:23

[3630/7111] ✓ LACG: 34 рядків |  51.05% | ETA 11:21

[3640/7111] ✓ LAUR: 367 рядків |  51.19% | ETA 11:19

[3650/7111] ✓ LBTYA: 332 рядків |  51.33% | ETA 11:18

   • RAM · 🧠 RAM: 327.3 MB

   ⏳ перед flush · 🧠 RAM: 327.3 MB

💾 batch 6200 → 14,155 рядків (всього 959,158 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6200.csv.gz

   ✅ після flush · 🧠 RAM: 328.0 MB

[3660/7111] ✓ LCLN: 361 рядків |  51.47% | ETA 11:16

[3670/7111] ✓ LEGH: 97 рядків |  51.61% | ETA 11:14

[3680/7111] ✓ LFGY: 82 рядків |  51.75% | ETA 11:12

[3690/7111] ✓ LGCL: 24 рядків |  51.89% | ETA 11:10

[3700/7111] ✓ LHAI: 63 рядків |  52.03% | ETA 11:08

   • RAM · 🧠 RAM: 323.8 MB

   ⏳ перед flush · 🧠 RAM: 323.8 MB

💾 batch 6201 → 11,123 рядків (всього 970,281 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6201.csv.gz

   ✅ після flush · 🧠 RAM: 323.9 MB

[3710/7111] ✓ LILA: 253 рядків |  52.17% | ETA 11:06

[3720/7111] ✓ LIT: 258 рядків |  52.31% | ETA 11:04

[3730/7111] ✓ LKFT: 75 рядків |  52.45% | ETA 11:03

[3740/7111] ✓ LMFA: 109 рядків |  52.59% | ETA 11:01

[3750/7111] ✓ LNG: 446 рядків |  52.74% | ETA 10:59

   • RAM · 🧠 RAM: 321.0 MB

   ⏳ перед flush · 🧠 RAM: 321.0 MB

💾 batch 6202 → 13,493 рядків (всього 983,774 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6202.csv.gz

   ✅ після flush · 🧠 RAM: 321.9 MB

[3760/7111] ✓ LOAN: 28 рядків |  52.88% | ETA 10:57

[3770/7111] ✓ LOMA: 219 рядків |  53.02% | ETA 10:55

[3780/7111] ✓ LPG: 358 рядків |  53.16% | ETA 10:53

[3790/7111] ✓ LQDW: 38 рядків |  53.30% | ETA 10:51

[3800/7111] ✓ LSF: 44 рядків |  53.44% | ETA 10:49

   • RAM · 🧠 RAM: 322.7 MB

   ⏳ перед flush · 🧠 RAM: 322.7 MB

💾 batch 6203 → 10,353 рядків (всього 994,127 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6203.csv.gz

   ✅ після flush · 🧠 RAM: 323.6 MB

[3810/7111] ✓ LTRN: 194 рядків |  53.58% | ETA 10:47

[3820/7111] ✓ LUNL: 698 рядків |  53.72% | ETA 10:45

[3830/7111] ✓ LWAY: 73 рядків |  53.86% | ETA 10:44

[3840/7111] ✓ LYEL: 132 рядків |  54.00% | ETA 10:42

[3850/7111] ✓ M: 425 рядків |  54.14% | ETA 10:40

   • RAM · 🧠 RAM: 324.6 MB

   ⏳ перед flush · 🧠 RAM: 324.6 MB

💾 batch 6204 → 14,635 рядків (всього 1,008,762 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6204.csv.gz

   ✅ після flush · 🧠 RAM: 325.6 MB

[3860/7111] ✓ MAGY: 107 рядків |  54.28% | ETA 10:38

[3870/7111] ✓ MANU: 193 рядків |  54.42% | ETA 10:36

[3880/7111] ✓ MASS: 218 рядків |  54.56% | ETA 10:34

[3890/7111] ✓ MAZE: 240 рядків |  54.70% | ETA 10:32

[3900/7111] ✓ MBRX: 208 рядків |  54.84% | ETA 10:31

   • RAM · 🧠 RAM: 326.2 MB

   ⏳ перед flush · 🧠 RAM: 326.2 MB

💾 batch 6205 → 11,299 рядків (всього 1,020,061 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6205.csv.gz

   ✅ після flush · 🧠 RAM: 327.2 MB

[3910/7111] ✓ MCHB: 273 рядків |  54.99% | ETA 10:29

[3920/7111] ✓ MD: 266 рядків |  55.13% | ETA 10:27

[3930/7111] ✓ MDU: 370 рядків |  55.27% | ETA 10:25

[3940/7111] ✓ MEGL: 23 рядків |  55.41% | ETA 10:23

[3950/7111] ✓ META: 951 рядків |  55.55% | ETA 10:21

   • RAM · 🧠 RAM: 328.5 MB

   ⏳ перед flush · 🧠 RAM: 328.5 MB

💾 batch 6206 → 14,650 рядків (всього 1,034,711 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6206.csv.gz

   ✅ після flush · 🧠 RAM: 329.2 MB

[3960/7111] ✓ MFC: 386 рядків |  55.69% | ETA 10:19

[3970/7111] ✓ MGIH: 5 рядків |  55.83% | ETA 10:18

[3980/7111] ✓ MGRX: 184 рядків |  55.97% | ETA 10:16

[3990/7111] ✓ MICC: 348 рядків |  56.11% | ETA 10:14

[4000/7111] ✓ MISL: 117 рядків |  56.25% | ETA 10:12

   • RAM · 🧠 RAM: 330.0 MB

   ⏳ перед flush · 🧠 RAM: 330.0 MB

💾 batch 6207 → 9,871 рядків (всього 1,044,582 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6207.csv.gz

   ✅ після flush · 🧠 RAM: 330.9 MB

[4010/7111] ✓ MKOR: 67 рядків |  56.39% | ETA 10:10

[4020/7111] ✓ MLI: 193 рядків |  56.53% | ETA 10:08

[4030/7111] ✓ MMED: 247 рядків |  56.67% | ETA 10:06

[4040/7111] ✓ MNOV: 24 рядків |  56.81% | ETA 10:04

[4050/7111] ✓ MNVT: 74 рядків |  56.95% | ETA 10:03

   • RAM · 🧠 RAM: 332.2 MB

   ⏳ перед flush · 🧠 RAM: 332.2 MB

💾 batch 6208 → 11,532 рядків (всього 1,056,114 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6208.csv.gz

   ✅ після flush · 🧠 RAM: 333.4 MB

[4060/7111] ✓ MOH: 293 рядків |  57.09% | ETA 10:01

[4070/7111] ✓ MPB: 111 рядків |  57.24% | ETA 09:59

[4080/7111] – MPTI/R: empty |  57.38% | ETA 09:57

[4090/7111] ✓ MRCY: 265 рядків |  57.52% | ETA 09:55

[4100/7111] ✓ MRNY: 132 рядків |  57.66% | ETA 09:53

   • RAM · 🧠 RAM: 334.3 MB

   ⏳ перед flush · 🧠 RAM: 334.3 MB

💾 batch 6209 → 12,363 рядків (всього 1,068,477 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6209.csv.gz

   ✅ після flush · 🧠 RAM: 335.7 MB

[4110/7111] ✓ MSA: 140 рядків |  57.80% | ETA 09:51

[4120/7111] ✓ MSFO: 101 рядків |  57.94% | ETA 09:50

[4130/7111] ✓ MSI: 386 рядків |  58.08% | ETA 09:48

[4140/7111] ✓ MST: 99 рядків |  58.22% | ETA 09:46

[4150/7111] ✓ MT: 462 рядків |  58.36% | ETA 09:45

   • RAM · 🧠 RAM: 327.1 MB

   ⏳ перед flush · 🧠 RAM: 327.1 MB

💾 batch 6210 → 16,176 рядків (всього 1,084,653 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6210.csv.gz

   ✅ після flush · 🧠 RAM: 327.4 MB

[4160/7111] ✓ MTEX: 33 рядків |  58.50% | ETA 09:43

[4170/7111] ✓ MTW: 142 рядків |  58.64% | ETA 09:41

[4180/7111] ✓ MUSA: 264 рядків |  58.78% | ETA 09:40

[4190/7111] ✓ MWA: 294 рядків |  58.92% | ETA 09:38

[4200/7111] ✓ MYFW: 55 рядків |  59.06% | ETA 09:36

   • RAM · 🧠 RAM: 321.8 MB

   ⏳ перед flush · 🧠 RAM: 321.8 MB

💾 batch 6211 → 16,644 рядків (всього 1,101,297 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6211.csv.gz

   ✅ після flush · 🧠 RAM: 323.2 MB

[4210/7111] ✓ MYY: 10 рядків |  59.20% | ETA 09:34

[4220/7111] ✓ NAMI: 86 рядків |  59.34% | ETA 09:32

[4230/7111] ✓ NATR: 123 рядків |  59.49% | ETA 09:31

[4240/7111] ✓ NBIS: 962 рядків |  59.63% | ETA 09:29

[4250/7111] ✓ NBXG: 305 рядків |  59.77% | ETA 09:27

   • RAM · 🧠 RAM: 316.8 MB

   ⏳ перед flush · 🧠 RAM: 316.8 MB

💾 batch 6212 → 12,732 рядків (всього 1,114,029 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6212.csv.gz

   ✅ після flush · 🧠 RAM: 317.0 MB

[4260/7111] ✓ NCPL: 828 рядків |  59.91% | ETA 09:25

[4270/7111] ✓ NEA: 222 рядків |  60.05% | ETA 09:23

[4280/7111] ✓ NEOG: 359 рядків |  60.19% | ETA 09:22

[4290/7111] ✓ NEXA: 348 рядків |  60.33% | ETA 09:20

[4300/7111] ✓ NFLP: 9 рядків |  60.47% | ETA 09:18

   • RAM · 🧠 RAM: 317.2 MB

   ⏳ перед flush · 🧠 RAM: 317.2 MB

💾 batch 6213 → 12,367 рядків (всього 1,126,396 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6213.csv.gz

   ✅ після flush · 🧠 RAM: 318.8 MB

[4310/7111] ✓ NGEN: 515 рядків |  60.61% | ETA 09:16

[4320/7111] – NHS/R: empty |  60.75% | ETA 09:14

[4330/7111] ✓ NIO: 940 рядків |  60.89% | ETA 09:12

[4340/7111] ✓ NIQ: 313 рядків |  61.03% | ETA 09:11

[4350/7111] ✓ NMM: 116 рядків |  61.17% | ETA 09:09

   • RAM · 🧠 RAM: 319.4 MB

   ⏳ перед flush · 🧠 RAM: 319.4 MB

💾 batch 6214 → 11,935 рядків (всього 1,138,331 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6214.csv.gz

   ✅ після flush · 🧠 RAM: 320.5 MB

[4360/7111] – NNEX: empty |  61.31% | ETA 09:07

[4370/7111] ✓ NOK: 1,200 рядків |  61.45% | ETA 09:05

[4380/7111] ✓ NPCE: 97 рядків |  61.59% | ETA 09:03

[4390/7111] ✓ NRDY: 293 рядків |  61.74% | ETA 09:01

[4400/7111] ✓ NRXP: 457 рядків |  61.88% | ETA 08:59

   • RAM · 🧠 RAM: 335.4 MB

   ⏳ перед flush · 🧠 RAM: 335.4 MB

💾 batch 6215 → 14,209 рядків (всього 1,152,540 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6215.csv.gz

   ✅ після flush · 🧠 RAM: 338.4 MB

[4410/7111] ✓ NTCL: 197 рядків |  62.02% | ETA 08:58

[4420/7111] ✓ NTRB: 13 рядків |  62.16% | ETA 08:56

[4430/7111] ✓ NUG: 15 рядків |  62.30% | ETA 08:54

[4440/7111] ✓ NVA: 299 рядків |  62.44% | ETA 08:52

[4450/7111] ✓ NVDL: 1,103 рядків |  62.58% | ETA 08:50

   • RAM · 🧠 RAM: 342.7 MB

   ⏳ перед flush · 🧠 RAM: 342.7 MB

💾 batch 6216 → 14,949 рядків (всього 1,167,489 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6216.csv.gz

   ✅ після flush · 🧠 RAM: 344.0 MB

[4460/7111] ✓ NVIT: 10 рядків |  62.72% | ETA 08:48

[4470/7111] ✓ NVT: 407 рядків |  62.86% | ETA 08:47

[4480/7111] ✓ NWGL: 22 рядків |  63.00% | ETA 08:45

[4490/7111] ✓ NXDR: 361 рядків |  63.14% | ETA 08:43

[4500/7111] ✓ NXTT: 77 рядків |  63.28% | ETA 08:41

   • RAM · 🧠 RAM: 345.2 MB

   ⏳ перед flush · 🧠 RAM: 345.2 MB

💾 batch 6217 → 14,213 рядків (всього 1,181,702 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6217.csv.gz

   ✅ після flush · 🧠 RAM: 345.8 MB

[4510/7111] ✓ OARK: 37 рядків |  63.42% | ETA 08:39

[4520/7111] ✓ OCG: 71 рядків |  63.56% | ETA 08:37

[4530/7111] ✓ ODTE: 12 рядків |  63.70% | ETA 08:35

[4540/7111] ✓ OFS: 58 рядків |  63.84% | ETA 08:33

[4550/7111] ✓ OII: 328 рядків |  63.99% | ETA 08:31

   • RAM · 🧠 RAM: 346.9 MB

   ⏳ перед flush · 🧠 RAM: 346.9 MB

💾 batch 6218 → 12,023 рядків (всього 1,193,725 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6218.csv.gz

   ✅ після flush · 🧠 RAM: 348.0 MB

[4560/7111] ✓ OKLL: 1,075 рядків |  64.13% | ETA 08:29

[4570/7111] ✓ OLN: 377 рядків |  64.27% | ETA 08:28

[4580/7111] ✓ OMER: 404 рядків |  64.41% | ETA 08:26

[4590/7111] ✓ ONDL: 505 рядків |  64.55% | ETA 08:24

[4600/7111] ✓ ONMD: 107 рядків |  64.69% | ETA 08:22

   • RAM · 🧠 RAM: 349.4 MB

   ⏳ перед flush · 🧠 RAM: 349.4 MB

💾 batch 6219 → 14,308 рядків (всього 1,208,033 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6219.csv.gz

   ✅ після flush · 🧠 RAM: 349.5 MB

[4610/7111] ✓ OPEG: 26 рядків |  64.83% | ETA 08:20

[4620/7111] ✓ OPRA: 213 рядків |  64.97% | ETA 08:18

[4630/7111] ✓ ORA: 326 рядків |  65.11% | ETA 08:16

[4640/7111] ✓ ORGO: 252 рядків |  65.25% | ETA 08:14

[4650/7111] ✓ ORR: 131 рядків |  65.39% | ETA 08:12

   • RAM · 🧠 RAM: 348.3 MB

   ⏳ перед flush · 🧠 RAM: 348.3 MB

💾 batch 6220 → 13,696 рядків (всього 1,221,729 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6220.csv.gz

   ✅ після flush · 🧠 RAM: 348.5 MB

[4660/7111] ✓ OSPN: 315 рядків |  65.53% | ETA 08:10

[4670/7111] ✓ OTLK: 820 рядків |  65.67% | ETA 08:08

[4680/7111] ✓ OWL: 458 рядків |  65.81% | ETA 08:06

[4690/7111] ✓ OZK: 322 рядків |  65.95% | ETA 08:04

[4700/7111] ✓ PAG: 132 рядків |  66.09% | ETA 08:03

   • RAM · 🧠 RAM: 340.9 MB

   ⏳ перед flush · 🧠 RAM: 340.9 MB

💾 batch 6221 → 13,771 рядків (всього 1,235,500 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6221.csv.gz

   ✅ після flush · 🧠 RAM: 341.1 MB

[4710/7111] ✓ PANG: 107 рядків |  66.24% | ETA 08:01

[4720/7111] ✓ PATX: 98 рядків |  66.38% | ETA 07:59

[4730/7111] ✓ PAYS: 293 рядків |  66.52% | ETA 07:57

[4740/7111] ✓ PBM: 103 рядків |  66.66% | ETA 07:55

[4750/7111] ✓ PCB: 68 рядків |  66.80% | ETA 07:53

   • RAM · 🧠 RAM: 337.2 MB

   ⏳ перед flush · 🧠 RAM: 337.2 MB

💾 batch 6222 → 12,533 рядків (всього 1,248,033 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6222.csv.gz

   ✅ після flush · 🧠 RAM: 338.2 MB

[4760/7111] ✓ PCT: 420 рядків |  66.94% | ETA 07:51

[4770/7111] ✓ PDFS: 367 рядків |  67.08% | ETA 07:49

[4780/7111] ✓ PEBO: 165 рядків |  67.22% | ETA 07:47

[4790/7111] ✓ PEO: 125 рядків |  67.36% | ETA 07:46

[4800/7111] ✓ PFBC: 70 рядків |  67.50% | ETA 07:44

   • RAM · 🧠 RAM: 339.6 MB

   ⏳ перед flush · 🧠 RAM: 339.6 MB

💾 batch 6223 → 13,105 рядків (всього 1,261,138 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6223.csv.gz

   ✅ після flush · 🧠 RAM: 340.6 MB

[4810/7111] ✓ PFN: 154 рядків |  67.64% | ETA 07:42

[4820/7111] ✓ PGNY: 356 рядків |  67.78% | ETA 07:40

[4830/7111] ✓ PHIN: 100 рядків |  67.92% | ETA 07:38

[4840/7111] ✓ PHYS: 404 рядків |  68.06% | ETA 07:36

[4850/7111] ✓ PIT: 74 рядків |  68.20% | ETA 07:34

   • RAM · 🧠 RAM: 341.4 MB

   ⏳ перед flush · 🧠 RAM: 341.4 MB

💾 batch 6224 → 13,229 рядків (всього 1,274,367 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6224.csv.gz

   ✅ після flush · 🧠 RAM: 342.0 MB

[4860/7111] ✓ PL: 992 рядків |  68.34% | ETA 07:32

[4870/7111] ✓ PLOW: 132 рядків |  68.49% | ETA 07:31

[4880/7111] ✓ PLTM: 169 рядків |  68.63% | ETA 07:29

[4890/7111] ✓ PLUS: 131 рядків |  68.77% | ETA 07:27

[4900/7111] ✓ PMI: 754 рядків |  68.91% | ETA 07:25

   • RAM · 🧠 RAM: 343.7 MB

   ⏳ перед flush · 🧠 RAM: 343.7 MB

💾 batch 6225 → 13,428 рядків (всього 1,287,795 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6225.csv.gz

   ✅ після flush · 🧠 RAM: 345.7 MB

[4910/7111] ✓ PNNT: 283 рядків |  69.05% | ETA 07:23

[4920/7111] ✓ POLA: 92 рядків |  69.19% | ETA 07:21

[4930/7111] ✓ POWR: 266 рядків |  69.33% | ETA 07:19

[4940/7111] ✓ PPIH: 102 рядків |  69.47% | ETA 07:17

[4950/7111] ✓ PRCT: 330 рядків |  69.61% | ETA 07:15

   • RAM · 🧠 RAM: 346.7 MB

   ⏳ перед flush · 🧠 RAM: 346.7 MB

💾 batch 6226 → 14,063 рядків (всього 1,301,858 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6226.csv.gz

   ✅ після flush · 🧠 RAM: 347.7 MB

[4960/7111] ✓ PRK: 70 рядків |  69.75% | ETA 07:13

[4970/7111] ✓ PROP: 345 рядків |  69.89% | ETA 07:11

[4980/7111] ✓ PRU: 367 рядків |  70.03% | ETA 07:09

[4990/7111] ✓ PSHG: 49 рядків |  70.17% | ETA 07:07

[5000/7111] ✓ PSNYW: 3 рядків |  70.31% | ETA 07:05

   • RAM · 🧠 RAM: 349.0 MB

   ⏳ перед flush · 🧠 RAM: 349.0 MB

💾 batch 6227 → 11,593 рядків (всього 1,313,451 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6227.csv.gz

   ✅ після flush · 🧠 RAM: 349.1 MB

[5010/7111] ✓ PTC: 338 рядків |  70.45% | ETA 07:03

[5020/7111] ✓ PTRB: 143 рядків |  70.59% | ETA 07:01

[5030/7111] ✓ PUSA: 276 рядків |  70.74% | ETA 06:59

[5040/7111] ✓ PXED: 72 рядків |  70.88% | ETA 06:57

[5050/7111] ✓ PYPU: 7 рядків |  71.02% | ETA 06:56

   • RAM · 🧠 RAM: 350.2 MB

   ⏳ перед flush · 🧠 RAM: 350.2 MB

💾 batch 6228 → 11,503 рядків (всього 1,324,954 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6228.csv.gz

   ✅ після flush · 🧠 RAM: 350.3 MB

[5060/7111] ✓ QBTX: 917 рядків |  71.16% | ETA 06:54

[5070/7111] ✓ QDTE: 382 рядків |  71.30% | ETA 06:52

[5080/7111] ✓ QLDY: 65 рядків |  71.44% | ETA 06:50

[5090/7111] ✓ QPUX: 349 рядків |  71.58% | ETA 06:48

[5100/7111] ✓ QQQM: 795 рядків |  71.72% | ETA 06:46

   • RAM · 🧠 RAM: 348.2 MB

   ⏳ перед flush · 🧠 RAM: 348.2 MB

💾 batch 6229 → 17,514 рядків (всього 1,342,468 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6229.csv.gz

   ✅ після flush · 🧠 RAM: 349.6 MB

[5110/7111] ✓ QS: 807 рядків |  71.86% | ETA 06:44

[5120/7111] ✓ QTWO: 259 рядків |  72.00% | ETA 06:42

[5130/7111] ✓ QXL: 82 рядків |  72.14% | ETA 06:40

[5140/7111] ✓ RADX: 15 рядків |  72.28% | ETA 06:38

[5150/7111] ✓ RAYA: 23 рядків |  72.42% | ETA 06:36

   • RAM · 🧠 RAM: 343.6 MB

   ⏳ перед flush · 🧠 RAM: 343.6 MB

💾 batch 6230 → 13,688 рядків (всього 1,356,156 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6230.csv.gz

   ✅ після flush · 🧠 RAM: 344.3 MB

[5160/7111] ✓ RBNE: 173 рядків |  72.56% | ETA 06:34

[5170/7111] ✓ RCMT: 60 рядків |  72.70% | ETA 06:32

[5180/7111] ✓ RDIV: 75 рядків |  72.84% | ETA 06:30

[5190/7111] ✓ RDW: 1,198 рядків |  72.99% | ETA 06:28

[5200/7111] ✓ REE: 67 рядків |  73.13% | ETA 06:26

   • RAM · 🧠 RAM: 336.2 MB

   ⏳ перед flush · 🧠 RAM: 336.2 MB

💾 batch 6231 → 13,064 рядків (всього 1,369,220 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6231.csv.gz

   ✅ після flush · 🧠 RAM: 334.8 MB

[5210/7111] ✓ REKR: 489 рядків |  73.27% | ETA 06:25

[5220/7111] ✓ RERE: 301 рядків |  73.41% | ETA 06:23

[5230/7111] ✓ REZI: 362 рядків |  73.55% | ETA 06:21

[5240/7111] ✓ RGLD: 392 рядків |  73.69% | ETA 06:19

[5250/7111] ✓ RH: 312 рядків |  73.83% | ETA 06:17

   • RAM · 🧠 RAM: 334.6 MB

   ⏳ перед flush · 🧠 RAM: 334.6 MB

💾 batch 6232 → 14,674 рядків (всього 1,383,894 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6232.csv.gz

   ✅ після flush · 🧠 RAM: 335.6 MB

[5260/7111] ✓ RING: 315 рядків |  73.97% | ETA 06:15

[5270/7111] ✓ RKDA: 195 рядків |  74.11% | ETA 06:13

[5280/7111] ✓ RLMD: 285 рядків |  74.25% | ETA 06:11

[5290/7111] ✓ RMSG: 205 рядків |  74.39% | ETA 06:09

[5300/7111] ✓ RNTX: 208 рядків |  74.53% | ETA 06:07

   • RAM · 🧠 RAM: 336.4 MB

   ⏳ перед flush · 🧠 RAM: 336.4 MB

💾 batch 6233 → 14,821 рядків (всього 1,398,715 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6233.csv.gz

   ✅ після flush · 🧠 RAM: 337.2 MB

[5310/7111] ✓ ROCQ: 216 рядків |  74.67% | ETA 06:05

[5320/7111] ✓ ROMA: 22 рядків |  74.81% | ETA 06:03

[5330/7111] ✓ RPGL: 487 рядків |  74.95% | ETA 06:01

[5340/7111] ✓ RRX: 264 рядків |  75.09% | ETA 05:59

[5350/7111] ✓ RSSS: 43 рядків |  75.24% | ETA 05:57

   • RAM · 🧠 RAM: 337.5 MB

   ⏳ перед flush · 🧠 RAM: 337.5 MB

💾 batch 6234 → 13,383 рядків (всього 1,412,098 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6234.csv.gz

   ✅ після flush · 🧠 RAM: 338.1 MB

[5360/7111] ✓ RUBI: 328 рядків |  75.38% | ETA 05:56

[5370/7111] ✓ RVSB: 48 рядків |  75.52% | ETA 05:54

[5380/7111] ✓ RWT: 291 рядків |  75.66% | ETA 05:51

[5390/7111] ✓ RYET: 27 рядків |  75.80% | ETA 05:49

[5400/7111] ✓ SA: 358 рядків |  75.94% | ETA 05:48

   • RAM · 🧠 RAM: 339.3 MB

   ⏳ перед flush · 🧠 RAM: 339.3 MB

💾 batch 6235 → 13,566 рядків (всього 1,425,664 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6235.csv.gz

   ✅ після flush · 🧠 RAM: 339.9 MB

[5410/7111] ✓ SAIC: 310 рядків |  76.08% | ETA 05:46

[5420/7111] ✓ SARO: 397 рядків |  76.22% | ETA 05:44

[5430/7111] – SBDS: empty |  76.36% | ETA 05:42

[5440/7111] ✓ SBMT: 108 рядків |  76.50% | ETA 05:40

[5450/7111] ✓ SCC: 15 рядків |  76.64% | ETA 05:38

   • RAM · 🧠 RAM: 341.2 MB

   ⏳ перед flush · 🧠 RAM: 341.2 MB

💾 batch 6236 → 14,897 рядків (всього 1,440,561 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6236.csv.gz

   ✅ після flush · 🧠 RAM: 342.9 MB

[5460/7111] ✓ SCHH: 361 рядків |  76.78% | ETA 05:36

[5470/7111] ✓ SCHV: 350 рядків |  76.92% | ETA 05:34

[5480/7111] ✓ SCMB: 205 рядків |  77.06% | ETA 05:32

[5490/7111] ✓ SCYB: 326 рядків |  77.20% | ETA 05:30

[5500/7111] ✓ SDIV: 272 рядків |  77.34% | ETA 05:28

   • RAM · 🧠 RAM: 344.4 MB

   ⏳ перед flush · 🧠 RAM: 344.4 MB

💾 batch 6237 → 14,661 рядків (всього 1,455,222 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6237.csv.gz

   ✅ після flush · 🧠 RAM: 345.0 MB

[5510/7111] ✓ SEA: 14 рядків |  77.49% | ETA 05:26

[5520/7111] ✓ SELX: 75 рядків |  77.63% | ETA 05:24

[5530/7111] ✓ SETH: 61 рядків |  77.77% | ETA 05:22

[5540/7111] ✓ SFIX: 366 рядків |  77.91% | ETA 05:20

[5550/7111] ✓ SGDM: 55 рядків |  78.05% | ETA 05:18

   • RAM · 🧠 RAM: 345.9 MB

   ⏳ перед flush · 🧠 RAM: 345.9 MB

💾 batch 6238 → 11,635 рядків (всього 1,466,857 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6238.csv.gz

   ✅ після flush · 🧠 RAM: 346.9 MB

[5560/7111] ✓ SGP: 112 рядків |  78.19% | ETA 05:16

[5570/7111] ✓ SHFS: 80 рядків |  78.33% | ETA 05:14

[5580/7111] ✓ SHOC: 24 рядків |  78.47% | ETA 05:12

[5590/7111] ✓ SID: 331 рядків |  78.61% | ETA 05:10

[5600/7111] ✓ SILC: 160 рядків |  78.75% | ETA 05:08

   • RAM · 🧠 RAM: 342.2 MB

   ⏳ перед flush · 🧠 RAM: 342.2 MB

💾 batch 6239 → 15,352 рядків (всього 1,482,209 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6239.csv.gz

   ✅ після flush · 🧠 RAM: 342.8 MB

[5610/7111] ✓ SIVR: 485 рядків |  78.89% | ETA 05:06

[5620/7111] ✓ SKIN: 386 рядків |  79.03% | ETA 05:04

[5630/7111] ✓ SKYQ: 287 рядків |  79.17% | ETA 05:02

[5640/7111] ✓ SLB: 472 рядків |  79.31% | ETA 05:00

[5650/7111] ✓ SLM: 366 рядків |  79.45% | ETA 04:58

   • RAM · 🧠 RAM: 333.1 MB

   ⏳ перед flush · 🧠 RAM: 333.1 MB

💾 batch 6240 → 12,836 рядків (всього 1,495,045 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6240.csv.gz

   ✅ після flush · 🧠 RAM: 331.3 MB

[5660/7111] ✓ SLRC: 208 рядків |  79.59% | ETA 04:56

[5670/7111] ✓ SLX: 75 рядків |  79.74% | ETA 04:54

[5680/7111] ✓ SMCI: 1,051 рядків |  79.88% | ETA 04:52

[5690/7111] ✓ SMHI: 58 рядків |  80.02% | ETA 04:50

[5700/7111] ✓ SMST: 238 рядків |  80.16% | ETA 04:49

   • RAM · 🧠 RAM: 327.9 MB

   ⏳ перед flush · 🧠 RAM: 327.9 MB

💾 batch 6241 → 14,161 рядків (всього 1,509,206 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6241.csv.gz

   ✅ після flush · 🧠 RAM: 329.4 MB

[5710/7111] ✓ SMYY: 43 рядків |  80.30% | ETA 04:47

[5720/7111] ✓ SND: 173 рядків |  80.44% | ETA 04:45

[5730/7111] ✓ SNFCA: 37 рядків |  80.58% | ETA 04:43

[5740/7111] ✓ SNPS: 560 рядків |  80.72% | ETA 04:41

[5750/7111] ✓ SO: 399 рядків |  80.86% | ETA 04:39

   • RAM · 🧠 RAM: 335.4 MB

   ⏳ перед flush · 🧠 RAM: 335.4 MB

💾 batch 6242 → 15,102 рядків (всього 1,524,308 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6242.csv.gz

   ✅ після flush · 🧠 RAM: 336.6 MB

[5760/7111] ✓ SOGP: 35 рядків |  81.00% | ETA 04:37

[5770/7111] ✓ SONY: 488 рядків |  81.14% | ETA 04:35

[5780/7111] ✓ SOXQ: 521 рядків |  81.28% | ETA 04:33

[5790/7111] ✓ SPCI: 84 рядків |  81.42% | ETA 04:31

[5800/7111] ✓ SPGP: 67 рядків |  81.56% | ETA 04:29

   • RAM · 🧠 RAM: 338.1 MB

   ⏳ перед flush · 🧠 RAM: 338.1 MB

💾 batch 6243 → 15,306 рядків (всього 1,539,614 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6243.csv.gz

   ✅ після flush · 🧠 RAM: 339.1 MB

[5810/7111] ✓ SPIR: 576 рядків |  81.70% | ETA 04:26

[5820/7111] ✓ SPPP: 201 рядків |  81.85% | ETA 04:25

[5830/7111] ✓ SPSK: 115 рядків |  81.99% | ETA 04:22

[5840/7111] ✓ SPUS: 330 рядків |  82.13% | ETA 04:20

[5850/7111] ✓ SPYD: 366 рядків |  82.27% | ETA 04:18

   • RAM · 🧠 RAM: 340.1 MB

   ⏳ перед flush · 🧠 RAM: 340.1 MB

💾 batch 6244 → 14,273 рядків (всього 1,553,887 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6244.csv.gz

   ✅ після flush · 🧠 RAM: 340.6 MB

[5860/7111] ✓ SQM: 398 рядків |  82.41% | ETA 04:16

[5870/7111] ✓ SRPT: 429 рядків |  82.55% | ETA 04:14

[5880/7111] ✓ SRZN: 72 рядків |  82.69% | ETA 04:12

[5890/7111] ✓ SSP: 271 рядків |  82.83% | ETA 04:10

[5900/7111] ✓ STAK: 172 рядків |  82.97% | ETA 04:08

   • RAM · 🧠 RAM: 342.0 MB

   ⏳ перед flush · 🧠 RAM: 342.0 MB

💾 batch 6245 → 14,255 рядків (всього 1,568,142 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6245.csv.gz

   ✅ після flush · 🧠 RAM: 343.4 MB

[5910/7111] ✓ STFS: 227 рядків |  83.11% | ETA 04:06

[5920/7111] ✓ STLD: 337 рядків |  83.25% | ETA 04:04

[5930/7111] ✓ STRF: 129 рядків |  83.39% | ETA 04:02

[5940/7111] ✓ STTK: 252 рядків |  83.53% | ETA 04:00

[5950/7111] ✓ SU: 408 рядків |  83.67% | ETA 03:58

   • RAM · 🧠 RAM: 344.6 MB

   ⏳ перед flush · 🧠 RAM: 344.6 MB

💾 batch 6246 → 12,558 рядків (всього 1,580,700 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6246.csv.gz

   ✅ після flush · 🧠 RAM: 345.4 MB

[5960/7111] ✓ SUNS: 95 рядків |  83.81% | ETA 03:56

[5970/7111] ✓ SVM: 442 рядків |  83.95% | ETA 03:54

[5980/7111] ✓ SWBI: 213 рядків |  84.10% | ETA 03:52

[5990/7111] ✓ SWZ: 31 рядків |  84.24% | ETA 03:50

[6000/7111] ✓ SYNX: 41 рядків |  84.38% | ETA 03:48

   • RAM · 🧠 RAM: 346.6 MB

   ⏳ перед flush · 🧠 RAM: 346.6 MB

💾 batch 6247 → 12,431 рядків (всього 1,593,131 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6247.csv.gz

   ✅ після flush · 🧠 RAM: 348.4 MB

[6010/7111] ✓ TALK: 372 рядків |  84.52% | ETA 03:46

[6020/7111] ✓ TAP: 393 рядків |  84.66% | ETA 03:44

[6030/7111] ✓ TBLL: 119 рядків |  84.80% | ETA 03:42

[6040/7111] ✓ TCBI: 229 рядків |  84.94% | ETA 03:40

[6050/7111] ✓ TD: 377 рядків |  85.08% | ETA 03:38

   • RAM · 🧠 RAM: 347.7 MB

   ⏳ перед flush · 🧠 RAM: 347.7 MB

💾 batch 6248 → 10,856 рядків (всього 1,603,987 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6248.csv.gz

   ✅ після flush · 🧠 RAM: 348.7 MB

[6060/7111] ✓ TDTH: 151 рядків |  85.22% | ETA 03:36

[6070/7111] ✓ TECL: 487 рядків |  85.36% | ETA 03:34

[6080/7111] ✓ TENX: 244 рядків |  85.50% | ETA 03:32

[6090/7111] ✓ TEXU: 16 рядків |  85.64% | ETA 03:30

[6100/7111] ✓ TGB: 422 рядків |  85.78% | ETA 03:28

   • RAM · 🧠 RAM: 339.9 MB

   ⏳ перед flush · 🧠 RAM: 339.9 MB

💾 batch 6249 → 15,493 рядків (всього 1,619,480 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6249.csv.gz

   ✅ після flush · 🧠 RAM: 339.6 MB

[6110/7111] ✓ TH: 295 рядків |  85.92% | ETA 03:26

[6120/7111] ✓ THR: 237 рядків |  86.06% | ETA 03:24

[6130/7111] ✓ TII: 188 рядків |  86.20% | ETA 03:22

[6140/7111] ✓ TKC: 376 рядків |  86.35% | ETA 03:20

[6150/7111] ✓ TLPH: 164 рядків |  86.49% | ETA 03:18

   • RAM · 🧠 RAM: 336.3 MB

   ⏳ перед flush · 🧠 RAM: 336.3 MB

💾 batch 6250 → 11,106 рядків (всього 1,630,586 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6250.csv.gz

   ✅ після flush · 🧠 RAM: 337.3 MB

[6160/7111] ✓ TM: 291 рядків |  86.63% | ETA 03:16

[6170/7111] ✓ TMHC: 320 рядків |  86.77% | ETA 03:14

[6180/7111] ✓ TNET: 191 рядків |  86.91% | ETA 03:12

[6190/7111] ✓ TOL: 356 рядків |  87.05% | ETA 03:10

[6200/7111] ✓ TOUR: 11 рядків |  87.19% | ETA 03:08

   • RAM · 🧠 RAM: 338.9 MB

   ⏳ перед flush · 🧠 RAM: 338.9 MB

💾 batch 6251 → 13,781 рядків (всього 1,644,367 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6251.csv.gz

   ✅ після flush · 🧠 RAM: 339.0 MB

[6210/7111] ✓ TPIF: 31 рядків |  87.33% | ETA 03:06

[6220/7111] ✓ TRAX: 157 рядків |  87.47% | ETA 03:04

[6230/7111] ✓ TRIP: 392 рядків |  87.61% | ETA 03:02

[6240/7111] ✓ TROW: 371 рядків |  87.75% | ETA 03:00

[6250/7111] ✓ TRV: 385 рядків |  87.89% | ETA 02:58

   • RAM · 🧠 RAM: 340.0 MB

   ⏳ перед flush · 🧠 RAM: 340.0 MB

💾 batch 6252 → 13,488 рядків (всього 1,657,855 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6252.csv.gz

   ✅ після flush · 🧠 RAM: 340.9 MB

[6260/7111] ✓ TSEM: 509 рядків |  88.03% | ETA 02:56

[6270/7111] ✓ TSLL: 1,173 рядків |  88.17% | ETA 02:54

[6280/7111] ✓ TSM: 990 рядків |  88.31% | ETA 02:52

[6290/7111] ✓ TSSD: 25 рядків |  88.45% | ETA 02:50

[6300/7111] ✓ TTD: 556 рядків |  88.60% | ETA 02:48

   • RAM · 🧠 RAM: 341.1 MB

   ⏳ перед flush · 🧠 RAM: 341.1 MB

💾 batch 6253 → 15,664 рядків (всього 1,673,519 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6253.csv.gz

   ✅ після flush · 🧠 RAM: 342.5 MB

[6310/7111] ✓ TTWO: 499 рядків |  88.74% | ETA 02:45

[6320/7111] ✓ TVGNW: 4 рядків |  88.88% | ETA 02:43

[6330/7111] ✓ TWO: 303 рядків |  89.02% | ETA 02:41

[6340/7111] ✓ TXT: 313 рядків |  89.16% | ETA 02:39

[6350/7111] ✓ TZOO: 120 рядків |  89.30% | ETA 02:37

   • RAM · 🧠 RAM: 342.8 MB

   ⏳ перед flush · 🧠 RAM: 342.8 MB

💾 batch 6254 → 11,410 рядків (всього 1,684,929 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6254.csv.gz

   ✅ після flush · 🧠 RAM: 343.7 MB

[6360/7111] ✓ UBER: 693 рядків |  89.44% | ETA 02:35

[6370/7111] ✓ UCAR: 269 рядків |  89.58% | ETA 02:33

[6380/7111] ✓ UECG: 54 рядків |  89.72% | ETA 02:31

[6390/7111] ✓ UFPT: 133 рядків |  89.86% | ETA 02:29

[6400/7111] ✓ UHS: 324 рядків |  90.00% | ETA 02:27

   • RAM · 🧠 RAM: 344.9 MB

   ⏳ перед flush · 🧠 RAM: 344.9 MB

💾 batch 6255 → 13,546 рядків (всього 1,698,475 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6255.csv.gz

   ✅ після flush · 🧠 RAM: 345.6 MB

[6410/7111] ✓ ULS: 269 рядків |  90.14% | ETA 02:25

[6420/7111] ✓ UNCY: 379 рядків |  90.28% | ETA 02:23

[6430/7111] ✓ UNM: 322 рядків |  90.42% | ETA 02:21

[6440/7111] ✓ UPLD: 148 рядків |  90.56% | ETA 02:19

[6450/7111] ✓ URAN: 20 рядків |  90.70% | ETA 02:17

   • RAM · 🧠 RAM: 346.8 MB

   ⏳ перед flush · 🧠 RAM: 346.8 MB

💾 batch 6256 → 13,014 рядків (всього 1,711,489 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6256.csv.gz

   ✅ після flush · 🧠 RAM: 347.6 MB

[6460/7111] ✓ URTY: 345 рядків |  90.85% | ETA 02:15

[6470/7111] ✓ USCI: 19 рядків |  90.99% | ETA 02:13

[6480/7111] – USGOW: empty |  91.13% | ETA 02:11

[6490/7111] ✓ USO: 986 рядків |  91.27% | ETA 02:09

[6500/7111] ✓ UTHR: 301 рядків |  91.41% | ETA 02:07

   • RAM · 🧠 RAM: 347.1 MB

   ⏳ перед flush · 🧠 RAM: 347.1 MB

💾 batch 6257 → 12,833 рядків (всього 1,724,322 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6257.csv.gz

   ✅ після flush · 🧠 RAM: 347.3 MB

[6510/7111] ✓ UUUU: 665 рядків |  91.55% | ETA 02:04

[6520/7111] ✓ UZX: 961 рядків |  91.69% | ETA 02:02

[6530/7111] ✓ VAW: 83 рядків |  91.83% | ETA 02:00

[6540/7111] ✓ VCIT: 401 рядків |  91.97% | ETA 01:58

[6550/7111] ✓ VDE: 396 рядків |  92.11% | ETA 01:56

   • RAM · 🧠 RAM: 354.2 MB

   ⏳ перед flush · 🧠 RAM: 354.2 MB

💾 batch 6258 → 14,277 рядків (всього 1,738,599 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6258.csv.gz

   ✅ після flush · 🧠 RAM: 356.9 MB

[6560/7111] ✓ VEON: 70 рядків |  92.25% | ETA 01:54

[6570/7111] ✓ VFLO: 354 рядків |  92.39% | ETA 01:52

[6580/7111] ✓ VGNT: 349 рядків |  92.53% | ETA 01:50

[6590/7111] ✓ VICR: 448 рядків |  92.67% | ETA 01:48

[6600/7111] ✓ VIR: 335 рядків |  92.81% | ETA 01:46

   • RAM · 🧠 RAM: 349.1 MB

   ⏳ перед flush · 🧠 RAM: 349.1 MB

💾 batch 6259 → 15,003 рядків (всього 1,753,602 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6259.csv.gz

   ✅ після flush · 🧠 RAM: 350.2 MB

[6610/7111] ✓ VIVS: 38 рядків |  92.95% | ETA 01:44

[6620/7111] ✓ VLUE: 381 рядків |  93.10% | ETA 01:42

[6630/7111] ✓ VNET: 565 рядків |  93.24% | ETA 01:40

[6640/7111] ✓ VOC: 53 рядків |  93.38% | ETA 01:38

[6650/7111] ✓ VOT: 354 рядків |  93.52% | ETA 01:36

   • RAM · 🧠 RAM: 351.9 MB

   ⏳ перед flush · 🧠 RAM: 351.9 MB

💾 batch 6260 → 15,070 рядків (всього 1,768,672 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6260.csv.gz

   ✅ після flush · 🧠 RAM: 353.5 MB

[6660/7111] ✓ VPU: 238 рядків |  93.66% | ETA 01:34

[6670/7111] ✓ VRSN: 242 рядків |  93.80% | ETA 01:31

[6680/7111] ✓ VSEE: 348 рядків |  93.94% | ETA 01:29

[6690/7111] ✓ VSTD: 75 рядків |  94.08% | ETA 01:27

[6700/7111] ✓ VTGN: 127 рядків |  94.22% | ETA 01:25

   • RAM · 🧠 RAM: 355.1 MB

   ⏳ перед flush · 🧠 RAM: 355.1 MB

💾 batch 6261 → 14,088 рядків (всього 1,782,760 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6261.csv.gz

   ✅ після flush · 🧠 RAM: 355.5 MB

[6710/7111] – VTYX: empty |  94.36% | ETA 01:23

[6720/7111] ✓ VVX: 273 рядків |  94.50% | ETA 01:21

[6730/7111] ✓ VYNE: 64 рядків |  94.64% | ETA 01:19

[6740/7111] ✓ WAL: 285 рядків |  94.78% | ETA 01:17

[6750/7111] ✓ WB: 337 рядків |  94.92% | ETA 01:15

   • RAM · 🧠 RAM: 356.3 MB

   ⏳ перед flush · 🧠 RAM: 356.3 MB

💾 batch 6262 → 14,281 рядків (всього 1,797,041 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6262.csv.gz

   ✅ після flush · 🧠 RAM: 357.4 MB

[6760/7111] ✓ WCN: 350 рядків |  95.06% | ETA 01:13

[6770/7111] ✓ WDI: 94 рядків |  95.20% | ETA 01:11

[6780/7111] ✓ WEEI: 104 рядків |  95.35% | ETA 01:09

[6790/7111] ✓ WETO: 103 рядків |  95.49% | ETA 01:07

[6800/7111] ✓ WGS: 367 рядків |  95.63% | ETA 01:05

   • RAM · 🧠 RAM: 357.2 MB

   ⏳ перед flush · 🧠 RAM: 357.2 MB

💾 batch 6263 → 11,329 рядків (всього 1,808,370 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6263.csv.gz

   ✅ після flush · 🧠 RAM: 358.2 MB

[6810/7111] ✓ WING: 395 рядків |  95.77% | ETA 01:02

[6820/7111] ✓ WLDN: 150 рядків |  95.91% | ETA 01:00

[6830/7111] ✓ WMG: 381 рядків |  96.05% | ETA 00:58

[6840/7111] ✓ WOOF: 373 рядків |  96.19% | ETA 00:56

[6850/7111] ✓ WRBY: 420 рядків |  96.33% | ETA 00:54

   • RAM · 🧠 RAM: 359.7 MB

   ⏳ перед flush · 🧠 RAM: 359.7 MB

💾 batch 6264 → 13,947 рядків (всього 1,822,317 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6264.csv.gz

   ✅ після flush · 🧠 RAM: 360.4 MB

[6860/7111] ✓ WSFS: 180 рядків |  96.47% | ETA 00:52

[6870/7111] ✓ WTI: 531 рядків |  96.61% | ETA 00:50

[6880/7111] ✓ WU: 416 рядків |  96.75% | ETA 00:48

[6890/7111] ✓ WY: 388 рядків |  96.89% | ETA 00:46

[6900/7111] ✓ XBCI: 289 рядків |  97.03% | ETA 00:44

   • RAM · 🧠 RAM: 361.5 MB

   ⏳ перед flush · 🧠 RAM: 361.5 MB

💾 batch 6265 → 12,376 рядків (всього 1,834,693 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6265.csv.gz

   ✅ після flush · 🧠 RAM: 362.9 MB

[6910/7111] ✓ XE: 637 рядків |  97.17% | ETA 00:42

[6920/7111] ✓ XHG: 4 рядків |  97.31% | ETA 00:40

[6930/7111] ✓ XLK: 585 рядків |  97.45% | ETA 00:37

[6940/7111] ✓ XMAX: 372 рядків |  97.60% | ETA 00:35

[6950/7111] ✓ XNET: 123 рядків |  97.74% | ETA 00:33

   • RAM · 🧠 RAM: 362.8 MB

   ⏳ перед flush · 🧠 RAM: 362.8 MB

💾 batch 6266 → 13,681 рядків (всього 1,848,374 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6266.csv.gz

   ✅ після flush · 🧠 RAM: 363.0 MB

[6960/7111] ✓ XP: 403 рядків |  97.88% | ETA 00:31

[6970/7111] ✓ XPON: 117 рядків |  98.02% | ETA 00:29

[6980/7111] ✓ XRPN: 48 рядків |  98.16% | ETA 00:27

[6990/7111] ✓ XSHD: 23 рядків |  98.30% | ETA 00:25

[7000/7111] ✓ XTNT: 81 рядків |  98.44% | ETA 00:23

   • RAM · 🧠 RAM: 354.5 MB

   ⏳ перед flush · 🧠 RAM: 354.5 MB

💾 batch 6267 → 10,755 рядків (всього 1,859,129 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6267.csv.gz

   ✅ після flush · 🧠 RAM: 355.6 MB

[7010/7111] ✓ XYZG: 7 рядків |  98.58% | ETA 00:21

[7020/7111] ✓ YBTC: 103 рядків |  98.72% | ETA 00:19

[7030/7111] ✓ YETI: 393 рядків |  98.86% | ETA 00:17

[7040/7111] ✓ YOLO: 45 рядків |  99.00% | ETA 00:14

[7050/7111] ✓ YSPY: 29 рядків |  99.14% | ETA 00:12

   • RAM · 🧠 RAM: 354.3 MB

   ⏳ перед flush · 🧠 RAM: 354.3 MB

💾 batch 6268 → 9,324 рядків (всього 1,868,453 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6268.csv.gz

   ✅ після flush · 🧠 RAM: 356.3 MB

[7060/7111] ✓ YYY: 204 рядків |  99.28% | ETA 00:10

[7070/7111] ✓ ZDGE: 47 рядків |  99.42% | ETA 00:08

[7080/7111] ✓ ZIM: 340 рядків |  99.56% | ETA 00:06

[7090/7111] ✓ ZNTL: 290 рядків |  99.70% | ETA 00:04

[7100/7111] ✓ ZTG: 9 рядків |  99.85% | ETA 00:02

   • RAM · 🧠 RAM: 357.6 MB

   ⏳ перед flush · 🧠 RAM: 357.6 MB

💾 batch 6269 → 11,875 рядків (всього 1,880,328 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6269.csv.gz

   ✅ після flush · 🧠 RAM: 358.7 MB

[7110/7111] ✓ ZYBT: 5 рядків |  99.99% | ETA 00:00

[7111/7111] ✓ ZYME: 301 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 358.7 MB

💾 batch 6270 → 2,647 рядків (всього 1,882,975 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_6270.csv.gz

   ✅ після flush · 🧠 RAM: 358.7 MB

   🔚 фінал · 🧠 RAM: 358.7 MB

🏁 Готово. Нових рядків: 1,882,975 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 24:56

In [19]:
import os, glob, gc, time
from typing import Optional

import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str   = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    aggregate: bool = False,            # False → всі рядки, True → агрегація по (ticker,date)
    chunksize: int = 200_000,           # якщо мало RAM — ще зменш
    compression: str = "snappy",
    log_every: int = 5,
    sort_chunk: bool = True,            # sort within each chunk (ticker,dt)
):
    """
    Проходить по {folder}/{pattern}, фільтрує рядки:
      - за часовим вікном [start_time..end_time] по підрядку часу в 'dt'
      - опційно за датою [date_min..date_max] по підрядку дати в 'dt'
    і стрімово пише у один Parquet.

    Очікувані колонки у CSV: 'ticker','dt','o','h','l','c','v'.
    dt має формат 'YYYY-MM-DD HH:MM:SS' (string).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    # normalize dates (string compare works for YYYY-MM-DD)
    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    # читаємо тільки потрібне, даємо вузькі типи
    usecols = ["ticker", "dt", "o", "h", "l", "c", "v"]
    dtypes = {
        "ticker": "string",
        "dt": "string",         # важливо: фільтруємо по підрядку, без datetime-парсингу
        "o": "float32",
        "h": "float32",
        "l": "float32",
        "c": "float32",
        "v": "float32",
    }

    # підготовка виходу
    if os.path.exists(out_path):
        os.remove(out_path)
    writer = None

    t0 = time.time()
    total_in = total_out = 0
    file_idx = 0

    rng_str = ""
    if date_min or date_max:
        rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]"
    print(f"▶️ START: {folder}/{pattern} → {out_path}  chunksize={chunksize:,}{rng_str}")

    try:
        for path in files:
            file_idx += 1
            chunk_idx = 0

            reader = pd.read_csv(
                path,
                compression="infer",
                usecols=usecols,
                dtype=dtypes,
                chunksize=chunksize,
                low_memory=True,
                # engine="pyarrow",
            )

            for chunk in reader:
                chunk_idx += 1
                total_in += len(chunk)

                # швидке фільтрування по часу: 'YYYY-MM-DD HH:MM:SS'
                t = chunk["dt"].str.slice(11, 19)
                mask = (t >= start_time) & (t <= end_time)

                # фільтр по даті, також строками
                if date_min is not None or date_max is not None:
                    d = chunk["dt"].str.slice(0, 10)
                    if date_min is not None:
                        mask &= (d >= date_min)
                    if date_max is not None:
                        mask &= (d <= date_max)

                cut = chunk.loc[mask].copy()

                if cut.empty:
                    del chunk, t, mask, cut
                    gc.collect()
                    continue

                if aggregate:
                    # дата як рядок 'YYYY-MM-DD'
                    cut["date"] = cut["dt"].str.slice(0, 10)
                    # сорт для стабільності
                    if sort_chunk and {"ticker", "date"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "date"], kind="mergesort")
                    grp = (cut.groupby(["ticker", "date"], as_index=False, observed=True)
                              .agg({"v": "sum"}))  # приклад: сума обсягу; змінюй агрегацію за потреби
                    out_df = grp
                else:
                    # стабільний порядок в межах чанка
                    if sort_chunk and {"ticker", "dt"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "dt"], kind="mergesort")
                    out_df = cut

                table = pa.Table.from_pandas(out_df, preserve_index=False)
                if writer is None:
                    writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
                writer.write_table(table)
                total_out += len(out_df)

                if (chunk_idx % log_every) == 0:
                    elapsed = time.time() - t0
                    print(f"  [{file_idx}/{len(files)}] {os.path.basename(path)} "
                          f"chunk {chunk_idx}  in={total_in:,}  out={total_out:,}  "
                          f"elapsed={elapsed:,.1f}s")

                del chunk, t, mask, cut, out_df, table
                gc.collect()

    finally:
        if writer is not None:
            writer.close()

    print(f"✅ DONE  in={total_in:,} → out={total_out:,}  to {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [20]:
collect_premarket_by_day_stream(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,      # NEW
    date_max=end_date_str,        # NEW
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  chunksize=150,000  date=[2026-02-26..2026-05-26]

✅ DONE  in=261,260,891 → out=113,472,570  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 455.5s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows.parquet'

In [21]:
import os
import glob
import pandas as pd
from typing import Optional, Dict, Tuple

def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,
) -> pd.DataFrame:
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    OPEN_FROM, OPEN_TO   = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    best_open:  Dict[Tuple[str, str], Tuple[str, float]] = {}
    best_close: Dict[Tuple[str, str], Tuple[str, float]] = {}

    usecols = ["ticker", "dt", "o", "c"]

    for path in files:
        for chunk in pd.read_csv(path, compression="infer", low_memory=False,
                                 chunksize=chunksize, usecols=usecols):
            cols = set(map(str, chunk.columns))
            missing = set(usecols) - cols
            if missing:
                raise KeyError(f"{os.path.basename(path)}: відсутні колонки {missing}")

            dt = chunk["dt"].astype(str)
            if "o" in chunk.columns:
                chunk["o"] = pd.to_numeric(chunk["o"], errors="coerce")
            if "c" in chunk.columns:
                chunk["c"] = pd.to_numeric(chunk["c"], errors="coerce")

            hhmm = dt.str.slice(11, 16)
            date = dt.str.slice(0, 10)

            # OPEN
            mask_o = (hhmm >= OPEN_FROM) & (hhmm <= OPEN_TO) & chunk["o"].notna()
            if mask_o.any():
                cut = chunk.loc[mask_o, ["ticker", "o"]].copy()
                cut["date"] = date[mask_o].values
                cut["dt"]   = dt[mask_o].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="first")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_open.get(key)
                    if (cur is None) or (r.dt < cur[0]):
                        best_open[key] = (r.dt, float(r.o))

            # CLOSE
            mask_c = (hhmm >= CLOSE_FROM) & (hhmm <= CLOSE_TO) & chunk["c"].notna()
            if mask_c.any():
                cut = chunk.loc[mask_c, ["ticker", "c"]].copy()
                cut["date"] = date[mask_c].values
                cut["dt"]   = dt[mask_c].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="last")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_close.get(key)
                    if (cur is None) or (r.dt > cur[0]):
                        best_close[key] = (r.dt, float(r.c))

    opens_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_open.items()],
        columns=["ticker", "date", "open"]
    )
    closes_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_close.items()],
        columns=["ticker", "date", "close"]
    )

    out = pd.merge(opens_df, closes_df, on=["ticker","date"], how="outer") \
            .sort_values(["ticker","date"], kind="stable") \
            .reset_index(drop=True)

    # ⬇️ ОКРУГЛЕННЯ ДО 2 ЗНАКІВ
    if "open" in out.columns:
        out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    if "close" in out.columns:
        out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)

    # завжди Parquet
    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)

    return out

In [22]:
df_oc = build_oc_from_intraday_folder(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "oc.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [23]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [24]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=63.6s

[batch   10] rows=20,000,000  elapsed=128.0s

[batch   15] rows=30,000,000  elapsed=191.7s

[batch   20] rows=40,000,000  elapsed=256.5s

[batch   25] rows=50,000,000  elapsed=321.5s

[batch   30] rows=60,000,000  elapsed=385.3s

[batch   35] rows=70,000,000  elapsed=449.0s

[batch   40] rows=80,000,000  elapsed=513.5s

[batch   45] rows=90,000,000  elapsed=577.7s

[batch   50] rows=100,000,000  elapsed=641.7s

[batch   55] rows=110,000,000  elapsed=706.5s

✅ DONE  rows=113,472,570  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  in 731.0s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet

In [25]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        # нульовий prev_close → NaN, щоб не ділити на 0
        denom = df["prev_close"].replace({0: np.nan})

        # розрахунок % vs prev_close
        pct = (df[value_col] / denom - 1.0) * 100.0

        # ще раз гарантуємо float dtype (без object/pd.NA всередині)
        pct = pd.to_numeric(pct, errors="coerce")

        if round_to is not None:
            pct = pct.round(int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(
                output_path,
                table.schema,
                compression="snappy",
            )
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [26]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

[batch    5] rows=10,000,000  elapsed=7.1s

[batch   10] rows=20,000,000  elapsed=14.1s

[batch   15] rows=30,000,000  elapsed=21.2s

[batch   20] rows=40,000,000  elapsed=28.2s

[batch   25] rows=50,000,000  elapsed=35.5s

[batch   30] rows=60,000,000  elapsed=42.7s

[batch   35] rows=70,000,000  elapsed=49.8s

[batch   40] rows=80,000,000  elapsed=56.9s

[batch   45] rows=90,000,000  elapsed=64.0s

[batch   50] rows=100,000,000  elapsed=71.0s

[batch   55] rows=110,000,000  elapsed=78.2s

✅ DONE  rows=113,472,570  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  in 80.7s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet

In [27]:
import os
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Read ticker->bench mapping from csv/xlsx and return ['ticker','bench'].
    """
    ext = os.path.splitext(mapping_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(mapping_path)
    else:
        try:
            df = pd.read_csv(mapping_path, sep=None, engine="python")
        except Exception:
            df = pd.read_csv(mapping_path)

    cols = {c.lower().strip(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol") or list(df.columns)[0]
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf") or list(df.columns)[1]

    out = df[[tcol, bcol]].rename(columns={tcol: "ticker", bcol: "bench"}).dropna()
    out["ticker"] = out["ticker"].astype(str).str.upper().str.strip()
    out["bench"] = out["bench"].astype(str).str.upper().str.strip()
    out = out[(out["ticker"] != "") & (out["bench"] != "")]
    return out.drop_duplicates(ignore_index=True)


def corr_beta_from_mapping_to_parquet(*args, **kwargs):
    """
    Deprecated API path removed.
    corr/beta is now computed locally in cell 12 and written in cell 13/28.
    """
    raise RuntimeError(
        "corr_beta_from_mapping_to_parquet is deprecated. "
        "Use local calculation in cell 12 and parquet output in cell 13/28."
    )

In [28]:
import os
import pandas as pd

out_path = str(WORK_DIR / "corr_beta_pairs.parquet")

# If parquet already exists from cell 13, keep it.
# Otherwise rebuild it from x_to_best_etf_by_lvl3.csv (no API calls).
if not os.path.exists(out_path):
    src_csv = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv")
    if not os.path.exists(src_csv):
        raise FileNotFoundError(f"Neither {out_path} nor {src_csv} exists")

    d = pd.read_csv(src_csv)
    need = ["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
    miss = [c for c in need if c not in d.columns]
    if miss:
        raise KeyError(f"Missing columns in {src_csv}: {miss}")

    d = d.rename(columns={
        "best_y_ticker": "y_ticker",
        "best_corr": "corr",
        "beta_with_best": "beta",
    })[["x_ticker", "y_ticker", "corr", "beta"]]
    d.to_parquet(out_path, index=False)

print("Result:", out_path)

Result: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [29]:

y_list = ["SPY", "IWM", "GDX", "XLF", "QQQ", "XLE", "KRE", "BITO", "XLP", "SOXL"]

In [30]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    # Читаємо БЕЗ фільтра колонок — так надійніше для різних схем
    table = pq.read_table(path)
    df = table.to_pandas()

    # нормалізуємо імена колонок для пошуку
    name_map = {c: c.strip().lower() for c in df.columns}
    inv_map = {v: k for k, v in name_map.items()}

    has_api    = ("x_ticker" in inv_map) and ("y_ticker" in inv_map)
    has_direct = ("ticker" in inv_map) and ("bench" in inv_map)

    if not (has_api or has_direct):
        # допоміжна підказка, що саме є в файлі
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={
            inv_map["x_ticker"]: "ticker",
            inv_map["y_ticker"]: "bench"
        })
    else:
        df = df.rename(columns={
            inv_map["ticker"]: "ticker",
            inv_map["bench"]:  "bench"
        })

    # corr/beta можуть бути відсутні — створимо
    if "corr" not in name_map.values():
        df["corr"] = pd.NA
    else:
        df = df.rename(columns={inv_map["corr"]: "corr"})
    if "beta" not in name_map.values():
        df["beta"] = pd.NA
    else:
        df = df.rename(columns={inv_map["beta"]: "beta"})

    # залишаємо тільки потрібне
    keep = [c for c in ["ticker", "bench", "corr", "beta"] if c in df.columns]
    df = df[keep].copy()

    # нормалізація значень
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"]  = df["bench"].astype(str).str.strip().str.upper()
    if "corr" in df.columns:
        df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    if "beta" in df.columns:
        df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    # якщо раптом на один тикер кілька рядків — візьмемо з найбільшою corr
    if "corr" in df.columns:
        df = (df.sort_values(["ticker", "corr"], ascending=[True, False])
                .drop_duplicates(subset=["ticker"], keep="first")
                .reset_index(drop=True))
    else:
        df = df.drop_duplicates(subset=["ticker"], keep="first").reset_index(drop=True)

    # гарантуємо повний набір стовпців
    for c in ("corr", "beta"):
        if c not in df.columns:
            df[c] = pd.NA

    return df[["ticker", "bench", "corr", "beta"]]


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), мерджить 'bench','corr','beta' з іншого
    Parquet (мапа) по 'ticker' і пише новий Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0
    batches = 0

    print(f"▶️ START merge → {out_parquet_path}")

    for batch in pf.iter_batches(batch_size=batch_rows):  # читаємо всі колонки
        batches += 1
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")
        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(mapping, on="ticker", how="left", validate="m:1")

        # Переставимо нові колонки за потреби
        if insert_before in merged.columns:
            cols = list(merged.columns)
            for c in ("bench", "corr", "beta"):
                if c in cols: cols.remove(c)
            idx = cols.index(insert_before)
            new_cols = cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]
            merged = merged[new_cols]
        else:
            base = [c for c in merged.columns if c not in ("bench","corr","beta")]
            merged = merged[base + ["bench","corr","beta"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if batches % log_every_batches == 0:
            print(f"[batch {batches:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path


# опціональний аліас під старе ім’я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [31]:
out_path = attach_bench_corr_beta_parquet(
    input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    batch_rows=2_000_000,
    round_decimals=4,
    insert_before="pct_vs_prev_close",
    compression="snappy",
)
print("Готово:", out_path)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

[batch    5] rows=10,000,000  elapsed=16.7s

[batch   10] rows=20,000,000  elapsed=33.5s

[batch   15] rows=30,000,000  elapsed=50.5s

[batch   20] rows=40,000,000  elapsed=66.7s

[batch   25] rows=50,000,000  elapsed=83.6s

[batch   30] rows=60,000,000  elapsed=100.7s

[batch   35] rows=70,000,000  elapsed=116.5s

[batch   40] rows=80,000,000  elapsed=133.3s

[batch   45] rows=90,000,000  elapsed=150.4s

[batch   50] rows=100,000,000  elapsed=167.4s

[batch   55] rows=110,000,000  elapsed=184.3s

✅ DONE rows=113,472,570 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet  in 190.0s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

In [32]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [33]:
peek_parquet("CRACEN/work/premarket_rows_final.parquet", n=620)

Файл: CRACEN/work/premarket_rows_final.parquet
Рядків (meta): 113,472,570
Колонок: 14
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta
NaN у 'bench' (у прев'ю): 0/620
NaN у 'corr' (у прев'ю): 0/620
NaN у 'beta' (у прев'ю): 0/620

Перші рядки:
    ticker                  dt           o           h           l           c         v        date    open  prev_close  Stack% bench    corr    beta
0        A 2026-02-26 03:59:00  121.709999  121.709999  121.709999  121.709999       3.0  2026-02-26  121.89      124.68   -2.38   IWM  0.8056  0.6776
1        A 2026-02-26 07:21:00  122.750000  122.750000  122.750000  122.750000     200.0  2026-02-26  121.89      124.68   -1.55   IWM  0.8056  0.6776
2        A 2026-02-26 08:26:00  121.519997  121.519997  121.519997  121.519997     189.0  2026-02-26  121.89      124.68   -2.53   IWM  0.8056  0.6776
3        A 2026-02-26 08:41:00  120.940002  120.940002  120.820000  120.820000     200.0  2026-02-26  121.89      124.68   -3.00   IWM  0.8056  0.6776
4        A 2026-02-26 08:42:00  120.970001  120.980003  120.820198  120.820198     400.0  2026-02-26  121.89      124.68   -2.98   IWM  0.8056  0.6776
5        A 2026-02-26 08:45:00  120.750000  120.750000  120.750000  120.750000    1000.0  2026-02-26  121.89      124.68   -3.15   IWM  0.8056  0.6776
6        A 2026-02-26 09:11:00  120.639999  120.750000  120.639999  120.750000    1964.0  2026-02-26  121.89      124.68   -3.24   IWM  0.8056  0.6776
7        A 2026-02-26 09:12:00  120.779999  120.779999  120.779999  120.779999     100.0  2026-02-26  121.89      124.68   -3.13   IWM  0.8056  0.6776
8        A 2026-02-26 09:13:00  120.940002  121.000000  120.940002  121.000000     500.0  2026-02-26  121.89      124.68   -3.00   IWM  0.8056  0.6776
9        A 2026-02-26 09:15:00  120.750000  120.750000  118.709999  118.709999    1752.0  2026-02-26  121.89      124.68   -3.15   IWM  0.8056  0.6776
10       A 2026-02-26 09:19:00  120.000000  120.000000  120.000000  120.000000     120.0  2026-02-26  121.89      124.68   -3.75   IWM  0.8056  0.6776
11       A 2026-02-26 09:20:00  120.000000  120.019997  119.750000  119.750000    2721.0  2026-02-26  121.89      124.68   -3.75   IWM  0.8056  0.6776
12       A 2026-02-26 09:21:00  119.699997  119.699997  119.699997  119.699997    2000.0  2026-02-26  121.89      124.68   -3.99   IWM  0.8056  0.6776
13       A 2026-02-26 09:26:00  119.239998  119.239998  119.000000  119.000000     515.0  2026-02-26  121.89      124.68   -4.36   IWM  0.8056  0.6776
14       A 2026-02-26 09:27:00  119.059998  119.059998  119.000000  119.000000     610.0  2026-02-26  121.89      124.68   -4.51   IWM  0.8056  0.6776
15       A 2026-02-26 09:28:00  119.900002  119.900002  119.900002  119.900002     100.0  2026-02-26  121.89      124.68   -3.83   IWM  0.8056  0.6776
16       A 2026-02-26 09:29:00  120.980003  124.019997  120.879997  121.739998    3903.0  2026-02-26  121.89      124.68   -2.97   IWM  0.8056  0.6776
17       A 2026-02-26 09:30:00  121.889999  124.410004  119.745003  120.830002   90151.0  2026-02-26  121.89      124.68   -2.24   IWM  0.8056  0.6776
18       A 2026-02-26 09:31:00  120.540001  121.224998  118.190002  120.355003   22628.0  2026-02-26  121.89      124.68   -3.32   IWM  0.8056  0.6776
19       A 2026-02-26 09:32:00  120.269997  120.775002  120.269997  120.775002   72653.0  2026-02-26  121.89      124.68   -3.54   IWM  0.8056  0.6776
20       A 2026-02-26 09:33:00  120.775002  122.264999  120.775002  120.830002   23647.0  2026-02-26  121.89      124.68   -3.13   IWM  0.8056  0.6776
21       A 2026-02-26 09:34:00  121.269997  121.680000  119.849998  120.014999   35952.0  2026-02-26  121.89      124.68   -2.74   IWM  0.8056  0.6776
22       A 2026-02-26 09:35:00  120.014999  120.070000  118.382500  118.382500   33870.0  2026-02-26  121.89      124.68   -3.74   IWM  0.8056  0.6776
23       A 2026-02-26 09:36:00  118.870003  120.199997  118.492897  120.199997   17519.0  2026-02-26  121.89      124.68   -4.66   IWM  0.8056  0.6776
24       A 2026-02-26 09:37:00  119.839996  120.330002  119.279999  119.894997   16867.0  2026-02-26  121.89      124.68   -3.88   IWM  0.8056  0.6776
25       A 2026-02-26 09:38:00  120.029999  120.500000  119.000000  119.445000   33710.0  2026-02-26  121.89      124.68   -3.73   IWM  0.8056  0.6776
26       A 2026-02-26 09:39:00  119.584999  119.584999  118.610001  118.650002   13715.0  2026-02-26  121.89      124.68   -4.09   IWM  0.8056  0.6776
27       A 2026-02-26 09:40:00  118.650002  119.385002  118.309998  119.385002    8499.0  2026-02-26  121.89      124.68   -4.84   IWM  0.8056  0.6776
28       A 2026-02-26 09:41:00  119.169998  120.120003  119.000000  119.040001   77400.0  2026-02-26  121.89      124.68   -4.42   IWM  0.8056  0.6776
29       A 2026-02-26 09:42:00  119.010002  119.010002  118.419998  118.669998    3613.0  2026-02-26  121.89      124.68   -4.55   IWM  0.8056  0.6776
30       A 2026-02-26 09:43:00  118.714203  119.070000  118.669998  118.709999    5752.0  2026-02-26  121.89      124.68   -4.78   IWM  0.8056  0.6776
31       A 2026-02-26 09:44:00  118.550003  118.760002  118.510002  118.760002     500.0  2026-02-26  121.89      124.68   -4.92   IWM  0.8056  0.6776
32       A 2026-02-26 09:45:00  118.760002  118.779999  118.400002  118.400002    2733.0  2026-02-26  121.89      124.68   -4.75   IWM  0.8056  0.6776
33       A 2026-02-26 09:46:00  118.730003  119.010002  118.330002  118.709999   31136.0  2026-02-26  121.89      124.68   -4.77   IWM  0.8056  0.6776
34       A 2026-02-26 09:47:00  118.669998  119.009903  118.470001  118.470001    9642.0  2026-02-26  121.89      124.68   -4.82   IWM  0.8056  0.6776
35       A 2026-02-26 09:48:00  118.470001  118.639999  118.269997  118.550003    6287.0  2026-02-26  121.89      124.68   -4.98   IWM  0.8056  0.6776
36       A 2026-02-26 09:49:00  118.739998  118.750000  118.290001  118.605003    7137.0  2026-02-26  121.89      124.68   -4.76   IWM  0.8056  0.6776
37       A 2026-02-26 09:50:00  118.459999  118.830002  118.269997  118.779999    7030.0  2026-02-26  121.89      124.68   -4.99   IWM  0.8056  0.6776
38       A 2026-02-26 09:51:00  118.699997  119.025002  118.660004  118.705002    6040.0  2026-02-26  121.89      124.68   -4.80   IWM  0.8056  0.6776
39       A 2026-02-26 09:52:00  118.879997  119.150002  118.599998  118.699997   18910.0  2026-02-26  121.89      124.68   -4.65   IWM  0.8056  0.6776
40       A 2026-02-26 09:53:00  118.699997  118.760002  118.540001  118.760002    2599.0  2026-02-26  121.89      124.68   -4.80   IWM  0.8056  0.6776
41       A 2026-02-26 09:54:00  118.610001  118.809998  118.599998  118.790001    3935.0  2026-02-26  121.89      124.68   -4.87   IWM  0.8056  0.6776
42       A 2026-02-26 09:55:00  118.629997  118.910004  118.500000  118.589996    9696.0  2026-02-26  121.89      124.68   -4.85   IWM  0.8056  0.6776
43       A 2026-02-26 09:56:00  118.599998  118.720001  118.430000  118.595001    9715.0  2026-02-26  121.89      124.68   -4.88   IWM  0.8056  0.6776
44       A 2026-02-26 09:57:00  118.550003  118.739998  118.430000  118.559998    4249.0  2026-02-26  121.89      124.68   -4.92   IWM  0.8056  0.6776
45       A 2026-02-26 09:58:00  118.610001  118.959999  118.610001  118.800003    6108.0  2026-02-26  121.89      124.68   -4.87   IWM  0.8056  0.6776
46       A 2026-02-26 09:59:00  118.690002  119.120003  118.669998  119.040001   29910.0  2026-02-26  121.89      124.68   -4.80   IWM  0.8056  0.6776
47       A 2026-02-26 10:00:00  119.044998  119.114998  118.790001  118.870003    5414.0  2026-02-26  121.89      124.68   -4.52   IWM  0.8056  0.6776
48       A 2026-02-26 10:01:00  118.904999  118.904999  118.570000  118.660004    5594.0  2026-02-26  121.89      124.68   -4.63   IWM  0.8056  0.6776
49       A 2026-02-26 10:02:00  118.669998  118.724998  118.120003  118.485001   13831.0  2026-02-26  121.89      124.68   -4.82   IWM  0.8056  0.6776
50       A 2026-02-26 10:03:00  118.440002  118.660004  117.830002  117.910004   39587.0  2026-02-26  121.89      124.68   -5.00   IWM  0.8056  0.6776
51       A 2026-02-26 10:04:00  117.820000  118.099998  117.529099  117.750000   12595.0  2026-02-26  121.89      124.68   -5.50   IWM  0.8056  0.6776
52       A 2026-02-26 10:05:00  117.769997  117.800003  117.550003  117.750000    6412.0  2026-02-26  121.89      124.68   -5.54   IWM  0.8056  0.6776
53       A 2026-02-26 10:06:00  117.750000  118.000000  117.639999  118.000000    4999.0  2026-02-26  121.89      124.68   -5.56   IWM  0.8056  0.6776
54       A 2026-02-26 10:07:00  117.925003  117.989998  117.925003  117.989998     556.0  2026-02-26  121.89      124.68   -5.42   IWM  0.8056  0.6776
55       A 2026-02-26 10:08:00  118.014999  118.370003  117.989998  118.370003    7388.0  2026-02-26  121.89      124.68   -5.35   IWM  0.8056  0.6776
56       A 2026-02-26 10:09:00  118.209999  118.430000  118.139999  118.339996    7479.0  2026-02-26  121.89      124.68   -5.19   IWM  0.8056  0.6776
57       A 2026-02-26 10:10:00  118.410004  118.525002  118.370003  118.470001    7045.0  2026-02-26  121.89      124.68   -5.03   IWM  0.8056  0.6776
58       A 2026-02-26 10:11:00  118.514999  118.680000  118.514999  118.660004    4578.0  2026-02-26  121.89      124.68   -4.94   IWM  0.8056  0.6776
59       A 2026-02-26 10:12:00  118.699997  118.699997  118.339996  118.430000    1510.0  2026-02-26  121.89      124.68   -4.80   IWM  0.8056  0.6776
60       A 2026-02-26 10:13:00  118.410004  118.540001  118.070099  118.375000   41616.0  2026-02-26  121.89      124.68   -5.03   IWM  0.8056  0.6776
61       A 2026-02-26 10:14:00  118.379997  118.540001  118.330002  118.445000    6035.0  2026-02-26  121.89      124.68   -5.05   IWM  0.8056  0.6776
62       A 2026-02-26 10:15:00  118.309998  118.309998  118.169998  118.199997     800.0  2026-02-26  121.89      124.68   -5.11   IWM  0.8056  0.6776
63       A 2026-02-26 10:16:00  118.089996  118.099998  117.790001  117.794998    2660.0  2026-02-26  121.89      124.68   -5.29   IWM  0.8056  0.6776
64       A 2026-02-26 10:17:00  117.805000  117.805000  117.580002  117.680000    1878.0  2026-02-26  121.89      124.68   -5.51   IWM  0.8056  0.6776
65       A 2026-02-26 10:18:00  117.638397  117.730003  117.410004  117.730003   10975.0  2026-02-26  121.89      124.68   -5.65   IWM  0.8056  0.6776
66       A 2026-02-26 10:19:00  117.735001  117.820000  117.540001  117.684998    3325.0  2026-02-26  121.89      124.68   -5.57   IWM  0.8056  0.6776
67       A 2026-02-26 10:20:00  117.559998  117.790001  117.500000  117.684998    3465.0  2026-02-26  121.89      124.68   -5.71   IWM  0.8056  0.6776
68       A 2026-02-26 10:21:00  117.519997  117.519997  117.029999  117.029999    3448.0  2026-02-26  121.89      124.68   -5.74   IWM  0.8056  0.6776
69       A 2026-02-26 10:22:00  117.169998  117.169998  116.754997  116.827499    5713.0  2026-02-26  121.89      124.68   -6.02   IWM  0.8056  0.6776
70       A 2026-02-26 10:23:00  116.949997  116.970001  116.820000  116.934998    2432.0  2026-02-26  121.89      124.68   -6.20   IWM  0.8056  0.6776
71       A 2026-02-26 10:24:00  116.934998  117.014999  116.875000  116.940002    3782.0  2026-02-26  121.89      124.68   -6.21   IWM  0.8056  0.6776
72       A 2026-02-26 10:25:00  116.889999  116.889999  116.489998  116.519997    7142.0  2026-02-26  121.89      124.68   -6.25   IWM  0.8056  0.6776
73       A 2026-02-26 10:26:00  116.510002  116.769997  116.480003  116.684998   19128.0  2026-02-26  121.89      124.68   -6.55   IWM  0.8056  0.6776
74       A 2026-02-26 10:27:00  116.669998  116.805000  116.580002  116.714996    4210.0  2026-02-26  121.89      124.68   -6.42   IWM  0.8056  0.6776
75       A 2026-02-26 10:28:00  116.639999  116.714996  116.500000  116.592499    4593.0  2026-02-26  121.89      124.68   -6.45   IWM  0.8056  0.6776
76       A 2026-02-26 10:29:00  116.660004  116.760002  116.605003  116.709999    3572.0  2026-02-26  121.89      124.68   -6.43   IWM  0.8056  0.6776
77       A 2026-02-26 10:30:00  116.559998  116.599998  116.519997  116.599998    2952.0  2026-02-26  121.89      124.68   -6.51   IWM  0.8056  0.6776
78       A 2026-02-26 10:31:00  116.519997  116.889999  116.519997  116.820000    8386.0  2026-02-26  121.89      124.68   -6.54   IWM  0.8056  0.6776
79       A 2026-02-26 10:32:00  116.720001  116.860001  116.720001  116.839996    1740.0  2026-02-26  121.89      124.68   -6.38   IWM  0.8056  0.6776
80       A 2026-02-26 10:33:00  116.750000  117.070000  116.750000  117.070000    4340.0  2026-02-26  121.89      124.68   -6.36   IWM  0.8056  0.6776
81       A 2026-02-26 10:34:00  116.930000  117.175003  116.930000  117.095001    3150.0  2026-02-26  121.89      124.68   -6.22   IWM  0.8056  0.6776
82       A 2026-02-26 10:35:00  117.000000  117.000000  116.839996  116.940002    4981.0  2026-02-26  121.89      124.68   -6.16   IWM  0.8056  0.6776
83       A 2026-02-26 10:36:00  116.849998  116.910004  116.849998  116.910004     672.0  2026-02-26  121.89      124.68   -6.28   IWM  0.8056  0.6776
84       A 2026-02-26 10:37:00  116.980003  117.239998  116.910004  117.239998   19201.0  2026-02-26  121.89      124.68   -6.18   IWM  0.8056  0.6776
85       A 2026-02-26 10:38:00  117.260002  117.300003  117.169998  117.169998    1045.0  2026-02-26  121.89      124.68   -5.95   IWM  0.8056  0.6776
86       A 2026-02-26 10:39:00  117.239998  117.264999  117.110001  117.160004    1745.0  2026-02-26  121.89      124.68   -5.97   IWM  0.8056  0.6776
87       A 2026-02-26 10:40:00  117.099998  117.149902  116.919998  116.989998    1414.0  2026-02-26  121.89      124.68   -6.08   IWM  0.8056  0.6776
88       A 2026-02-26 10:41:00  117.097504  117.120003  117.044998  117.050003    1200.0  2026-02-26  121.89      124.68   -6.08   IWM  0.8056  0.6776
89       A 2026-02-26 10:42:00  117.068100  117.068100  116.959999  117.065002    1739.0  2026-02-26  121.89      124.68   -6.11   IWM  0.8056  0.6776
90       A 2026-02-26 10:43:00  117.029999  117.339996  117.029999  117.309998    7541.0  2026-02-26  121.89      124.68   -6.14   IWM  0.8056  0.6776
91       A 2026-02-26 10:44:00  117.324997  117.427498  117.324997  117.339996    1016.0  2026-02-26  121.89      124.68   -5.90   IWM  0.8056  0.6776
92       A 2026-02-26 10:45:00  117.290001  117.339996  117.279999  117.330002    3773.0  2026-02-26  121.89      124.68   -5.93   IWM  0.8056  0.6776
93       A 2026-02-26 10:46:00  117.330002  117.330002  117.019997  117.019997    2372.0  2026-02-26  121.89      124.68   -5.90   IWM  0.8056  0.6776
94       A 2026-02-26 10:47:00  117.099998  117.209999  117.099998  117.110001    7093.0  2026-02-26  121.89      124.68   -6.08   IWM  0.8056  0.6776
95       A 2026-02-26 10:48:00  117.099998  117.389999  117.099998  117.389999   11576.0  2026-02-26  121.89      124.68   -6.08   IWM  0.8056  0.6776
96       A 2026-02-26 10:49:00  117.355003  117.355003  117.260002  117.330002    1516.0  2026-02-26  121.89      124.68   -5.88   IWM  0.8056  0.6776
97       A 2026-02-26 10:50:00  117.260002  117.345001  117.260002  117.271698    1000.0  2026-02-26  121.89      124.68   -5.95   IWM  0.8056  0.6776
98       A 2026-02-26 10:51:00  117.330002  117.629997  117.300003  117.474998    9128.0  2026-02-26  121.89      124.68   -5.90   IWM  0.8056  0.6776
99       A 2026-02-26 10:52:00  117.449997  117.724998  117.449997  117.720001    2630.0  2026-02-26  121.89      124.68   -5.80   IWM  0.8056  0.6776
100      A 2026-02-26 10:53:00  117.644997  117.660004  117.514198  117.660004    3688.0  2026-02-26  121.89      124.68   -5.64   IWM  0.8056  0.6776
101      A 2026-02-26 10:54:00  117.724998  117.730003  117.699997  117.699997    1242.0  2026-02-26  121.89      124.68   -5.58   IWM  0.8056  0.6776
102      A 2026-02-26 10:55:00  117.669998  117.699898  117.529999  117.529999    1292.0  2026-02-26  121.89      124.68   -5.62   IWM  0.8056  0.6776
103      A 2026-02-26 10:56:00  117.510002  117.510002  117.330002  117.330002    7769.0  2026-02-26  121.89      124.68   -5.75   IWM  0.8056  0.6776
104      A 2026-02-26 10:57:00  117.300003  117.300003  117.199997  117.209999    2952.0  2026-02-26  121.89      124.68   -5.92   IWM  0.8056  0.6776
105      A 2026-02-26 10:58:00  117.190002  117.199997  117.150002  117.154999    4070.0  2026-02-26  121.89      124.68   -6.01   IWM  0.8056  0.6776
106      A 2026-02-26 10:59:00  117.154999  117.620003  117.129997  117.559998    8892.0  2026-02-26  121.89      124.68   -6.04   IWM  0.8056  0.6776
107      A 2026-02-26 11:00:00  117.519997  117.519997  117.430000  117.464996    1904.0  2026-02-26  121.89      124.68   -5.74   IWM  0.8056  0.6776
108      A 2026-02-26 11:01:00  117.349998  117.410004  117.260002  117.260002    1218.0  2026-02-26  121.89      124.68   -5.88   IWM  0.8056  0.6776
109      A 2026-02-26 11:02:00  117.209999  117.269997  117.169998  117.184998    3509.0  2026-02-26  121.89      124.68   -5.99   IWM  0.8056  0.6776
110      A 2026-02-26 11:03:00  117.190002  117.190002  117.080002  117.144997    1600.0  2026-02-26  121.89      124.68   -6.01   IWM  0.8056  0.6776
111      A 2026-02-26 11:04:00  117.080002  117.089996  116.949997  117.029999    4584.0  2026-02-26  121.89      124.68   -6.10   IWM  0.8056  0.6776
112      A 2026-02-26 11:05:00  117.000000  117.000000  116.800003  116.805000    5441.0  2026-02-26  121.89      124.68   -6.16   IWM  0.8056  0.6776
113      A 2026-02-26 11:06:00  116.724998  116.889999  116.629997  116.629997    3137.0  2026-02-26  121.89      124.68   -6.38   IWM  0.8056  0.6776
114      A 2026-02-26 11:07:00  116.665001  116.760002  116.570000  116.707497    5435.0  2026-02-26  121.89      124.68   -6.43   IWM  0.8056  0.6776
115      A 2026-02-26 11:08:00  116.669998  116.970001  116.660004  116.894997    3804.0  2026-02-26  121.89      124.68   -6.42   IWM  0.8056  0.6776
116      A 2026-02-26 11:09:00  116.780098  116.945000  116.780098  116.860001    1455.0  2026-02-26  121.89      124.68   -6.34   IWM  0.8056  0.6776
117      A 2026-02-26 11:10:00  116.809998  116.889999  116.730003  116.849998    4322.0  2026-02-26  121.89      124.68   -6.31   IWM  0.8056  0.6776
118      A 2026-02-26 11:11:00  116.882500  116.882500  116.820000  116.820000     262.0  2026-02-26  121.89      124.68   -6.25   IWM  0.8056  0.6776
119      A 2026-02-26 11:12:00  116.860001  116.885002  116.820000  116.820000    1437.0  2026-02-26  121.89      124.68   -6.27   IWM  0.8056  0.6776
120      A 2026-02-26 11:13:00  116.779999  116.864998  116.709999  116.720001    2375.0  2026-02-26  121.89      124.68   -6.34   IWM  0.8056  0.6776
121      A 2026-02-26 11:14:00  116.650002  116.860001  116.650002  116.839996    6907.0  2026-02-26  121.89      124.68   -6.44   IWM  0.8056  0.6776
122      A 2026-02-26 11:15:00  116.760002  116.790001  116.595001  116.720001    6882.0  2026-02-26  121.89      124.68   -6.35   IWM  0.8056  0.6776
123      A 2026-02-26 11:16:00  116.699997  116.800003  116.660004  116.800003    3431.0  2026-02-26  121.89      124.68   -6.40   IWM  0.8056  0.6776
124      A 2026-02-26 11:17:00  116.820000  116.849998  116.769997  116.809998    2476.0  2026-02-26  121.89      124.68   -6.30   IWM  0.8056  0.6776
125      A 2026-02-26 11:18:00  116.790001  116.830002  116.750000  116.830002    3071.0  2026-02-26  121.89      124.68   -6.33   IWM  0.8056  0.6776
126      A 2026-02-26 11:19:00  116.790001  116.830002  116.584999  116.584999   13541.0  2026-02-26  121.89      124.68   -6.33   IWM  0.8056  0.6776
127      A 2026-02-26 11:20:00  116.570000  116.709999  116.550003  116.650002    6095.0  2026-02-26  121.89      124.68   -6.50   IWM  0.8056  0.6776
128      A 2026-02-26 11:21:00  116.639999  116.654999  116.500000  116.519997    2691.0  2026-02-26  121.89      124.68   -6.45   IWM  0.8056  0.6776

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta
0,A,2026-02-26 03:59:00,121.709999,121.709999,121.709999,121.709999,3.0,2026-02-26,121.89,124.68,-2.38,IWM,0.8056,0.6776
1,A,2026-02-26 07:21:00,122.750000,122.750000,122.750000,122.750000,200.0,2026-02-26,121.89,124.68,-1.55,IWM,0.8056,0.6776
2,A,2026-02-26 08:26:00,121.519997,121.519997,121.519997,121.519997,189.0,2026-02-26,121.89,124.68,-2.53,IWM,0.8056,0.6776
3,A,2026-02-26 08:41:00,120.940002,120.940002,120.820000,120.820000,200.0,2026-02-26,121.89,124.68,-3.00,IWM,0.8056,0.6776
4,A,2026-02-26 08:42:00,120.970001,120.980003,120.820198,120.820198,400.0,2026-02-26,121.89,124.68,-2.98,IWM,0.8056,0.6776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,A,2026-02-27 12:58:00,121.129997,121.135002,121.080002,121.129997,2348.0,2026-02-27,119.09,120.97,0.13,IWM,0.8056,0.6776
616,A,2026-02-27 12:59:00,121.160004,121.440002,121.160004,121.389999,3491.0,2026-02-27,119.09,120.97,0.16,IWM,0.8056,0.6776
617,A,2026-02-27 13:00:00,121.394997,121.394997,121.300003,121.364998,20360.0,2026-02-27,119.09,120.97,0.35,IWM,0.8056,0.6776
618,A,2026-02-27 13:01:00,121.364998,121.434998,121.364998,121.379997,785.0,2026-02-27,119.09,120.97,0.33,IWM,0.8056,0.6776
619,A,2026-02-27 13:02:00,121.449997,121.470001,121.419998,121.459999,800.0,2026-02-27,119.09,120.97,0.40,IWM,0.8056,0.6776

In [34]:
# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','SOXL']

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [35]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=3,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,   # ⬅️ додай це
)

▶ Починаємо: 10 тікерів (пропущено 0 по старому маніфесту) | 2026-02-26 00:00:00 → 2026-05-26 23:59:59 | interval=1 | next batch #0063 | run=bbd20507

   workers: tickers=3, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2026-02-26 → 2026-05-25 (89 днів)

   📈 обробляються дні: 2026-05-26 → 2026-05-26 (1 днів)

   psutil · старт · 🧠 RAM: 1,588.7 MB

[10/10] ✓ SOXL: 1,198 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 1,595.9 MB

💾 batch 63 → 8,326 рядків (всього 8,326 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\ETF\intraday_0063.csv.gz

   ✅ після flush · 🧠 RAM: 1,598.6 MB

   🔚 фінал · 🧠 RAM: 1,598.6 MB

🏁 Готово. Нових рядків: 8,326 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:02

In [36]:
collect_premarket_by_day_stream(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  chunksize=150,000

✅ DONE  in=1,336,328 → out=1,336,328  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 3.4s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_etf_rows.parquet'

In [37]:
df_oc = build_oc_from_intraday_folder(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "oc_etf.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date   open  close
0   BITO  2025-10-28  18.96  18.72
1   BITO  2025-10-29  18.70  18.21
2   BITO  2025-10-30  17.83  17.53
3   BITO  2025-10-31  18.09  18.07
4   BITO  2025-11-03  16.89  16.74

In [38]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [39]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=1,336,328  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 4.1s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [40]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None

def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",   # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Benchk%",  # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        denom = df["prev_close"].replace({0: pd.NA})
        pct = (df[value_col] / denom - 1.0) * 100.0
        if round_to is not None:
            pct = pct.round(round_to)

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",   # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [41]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=1,336,328  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 1.0s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [42]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception as e:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий файл по ключах ('bench'↔'ticker', 'dt') і пише новий Parquet.
    - У ETF-файлі колонка з відсотком може називатись 'bench%' або 'pct_vs_prev_close' — обидва варіанти підтримуються.
    - Базовий файл не змінюється, додається тільки нова колонка 'Bench%'.
    """

    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    # ---------- 1) Збираємо мапу з ETF-файла: (bench, dt) -> Bench% ----------
    def _read_etf_mapping(etf_parquet: str) -> pd.DataFrame:
        pf = pq.ParquetFile(etf_parquet)
        parts = []
        # читаємо всі колонки, щоб не ловити різні схеми у row-groups
        for batch in pf.iter_batches():
            df = batch.to_pandas()
            # обов'язкові
            for col in ("ticker", "dt"):
                if col not in df.columns:
                    raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")

            # колонка відсотка: bench% або pct_vs_prev_close
            cols_l = {c.lower().strip(): c for c in df.columns}
            if "bench%" in cols_l:
                val_col = cols_l["bench%"]
            elif "pct_vs_prev_close" in cols_l:
                val_col = cols_l["pct_vs_prev_close"]
            else:
                raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

            d = df[["ticker", "dt", val_col]].copy()
            d["ticker"] = d["ticker"].astype(str).str.strip().str.upper()
            d["dt"]     = pd.to_datetime(d["dt"], errors="coerce")
            if align_to_minute:
                d["dt"] = d["dt"].dt.floor("T")
            d = d.dropna(subset=["dt"])
            d = d.rename(columns={"ticker": "bench", val_col: "Bench%"})
            d["Bench%"] = pd.to_numeric(d["Bench%"], errors="coerce")
            parts.append(d)

            del df, d, batch
            gc.collect()

        if not parts:
            return pd.DataFrame(columns=["bench","dt","Bench%"])

        etf_map = pd.concat(parts, ignore_index=True)
        # прибираємо дублікати — залишаємо пізніший запис
        etf_map = (etf_map.sort_values(["bench","dt"])
                           .drop_duplicates(subset=["bench","dt"], keep="last")
                           .reset_index(drop=True))
        return etf_map

    etf_map = _read_etf_mapping(etf_path)
    if round_decimals is not None and "Bench%" in etf_map.columns:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    # ---------- 2) Потоково проходимо базовий файл і підмерджуємо Bench% ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START merge → {out_path}")
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # ключі
        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        df["bench"] = df["bench"].astype(str).str.strip().str.upper()
        df["dt"]    = pd.to_datetime(df["dt"], errors="coerce")
        if align_to_minute:
            df["dt"] = df["dt"].dt.floor("T")

        merged = df.merge(etf_map, on=["bench","dt"], how="left", validate="m:1")

        # розташування 'Bench%'
        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("Bench%")
            pos = cols.index(insert_before)
            cols = cols[:pos] + ["Bench%"] + cols[pos:]
            merged = merged[cols]
        # інакше — залишаємо в кінці як є

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [43]:
merge_bench_pct_from_etf(
    base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    batch_rows=2_000_000,
    align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
    round_decimals=2,
    insert_before=None,          # або, наприклад, "pct_vs_prev_close"
    compression="snappy",
)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet

[batch    5] rows=10,000,000  elapsed=18.1s

[batch   10] rows=20,000,000  elapsed=36.5s

[batch   15] rows=30,000,000  elapsed=53.7s

[batch   20] rows=40,000,000  elapsed=71.8s

[batch   25] rows=50,000,000  elapsed=89.9s

[batch   30] rows=60,000,000  elapsed=107.3s

[batch   35] rows=70,000,000  elapsed=125.8s

[batch   40] rows=80,000,000  elapsed=144.0s

[batch   45] rows=90,000,000  elapsed=162.1s

[batch   50] rows=100,000,000  elapsed=180.4s

[batch   55] rows=110,000,000  elapsed=198.3s

✅ DONE rows=113,472,570 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet  in 204.4s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct.parquet'

In [44]:
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm


def _pick_first_existing(df: pd.DataFrame, candidates):
    cols_l = {c.lower().strip(): c for c in df.columns}
    for c in candidates:
        if c.lower() in cols_l:
            return cols_l[c.lower()]
    return None


def get_reports(ticker, last_n_reports, start_date, end_date):
    try:
        params = {
            "ticker": str(ticker),
            "start_move_date": str(start_date)[:10],
            "end_move_date": str(end_date)[:10],
        }

        reports_df = DatumApi.data_request("/reports", params)

        if reports_df is None or reports_df.empty:
            return pd.DataFrame(columns=["ticker", "report_date"])

        date_col = _pick_first_existing(
            reports_df,
            ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"],
        )
        if date_col is None:
            return pd.DataFrame(columns=["ticker", "report_date"])

        out = reports_df.copy()
        out["report_date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
        out["ticker"] = str(ticker).upper()
        out = out.dropna(subset=["report_date"])
        out = out.sort_values("report_date").tail(int(last_n_reports))
        return out[["ticker", "report_date"]].reset_index(drop=True)

    except Exception as e:
        print(f"Report fetch failed for {ticker}: {e}")
        return pd.DataFrame(columns=["ticker", "report_date"])


def get_reports_for_tickers(tickers_df, start_date, end_date, last_n_reports=20):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    parts = []

    for t in tqdm(tickers, desc="Reports"):
        rep = get_reports(ticker=t, last_n_reports=last_n_reports, start_date=start_date, end_date=end_date)
        if rep is not None and not rep.empty:
            parts.append(rep)

    if not parts:
        empty = pd.DataFrame(columns=["ticker", "report_date"])
        return empty, {}

    reports = pd.concat(parts, ignore_index=True).drop_duplicates(["ticker", "report_date"])
    report_days_map = reports.groupby("ticker")["report_date"].apply(set).to_dict()
    return reports, report_days_map


def get_gaps_for_tickers_excluding_reports(tickers_df, start_date, end_date, report_days_map):
    all_results = []
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()

    for t in tqdm(tickers, desc="Gaps (ex-reports)"):
        params = {
            "ticker": t,
            "start_date": str(start_date)[:10],
            "end_date": str(end_date)[:10],
            "format": "json_records",
        }

        try:
            df_gap = DatumApi.data_request("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                continue

            date_col = _pick_first_existing(df_gap, ["date", "move_date", "dt", "datetime", "day"])
            if date_col is None:
                continue

            out = df_gap.copy()
            out["ticker"] = out.get("ticker", t).astype(str).str.upper() if "ticker" in out.columns else t
            out["date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
            out["gap"] = pd.to_numeric(out.get("gap"), errors="coerce")
            out = out.dropna(subset=["date", "gap"])

            report_days = report_days_map.get(t, set())
            if report_days:
                out = out[~out["date"].isin(report_days)]

            if not out.empty:
                all_results.append(out)

        except Exception as e:
            print(f"Gap fetch failed for {t}: {e}")

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    return pd.DataFrame(columns=["ticker", "date", "gap"])


def add_rolling_sigma_cap(
    df,
    value_col,
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.95,
    min_periods=None,
):
    if min_periods is None:
        min_periods = window

    out = df.sort_values([group_col, date_col]).copy()

    def compute_sigma(s):
        x = s.shift(1)

        def f(arr):
            arr = arr[~np.isnan(arr)]
            if len(arr) < min_periods:
                return np.nan

            cap = np.quantile(np.abs(arr), cap_q)
            arr_capped = np.clip(arr, -cap, cap)

            return np.std(arr_capped, ddof=1)

        return x.rolling(window, min_periods=min_periods).apply(f, raw=True)

    out[f"{value_col}_sigma_{window}d_cap"] = (
        out.groupby(group_col)[value_col].transform(compute_sigma)
    )

    return out


# 1) Report days in the working window
reports_df, report_days_map = get_reports_for_tickers(
    top1500,
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
)
print("Report rows:", len(reports_df))

# 2) Gaps without report days
df_gaps_all = get_gaps_for_tickers_excluding_reports(
    top1500,
    start_date=start_date_str,
    end_date=end_date_str,
    report_days_map=report_days_map,
)
print("Rows in gaps (without report days):", len(df_gaps_all))

Reports:   0%|          | 0/7111 [00:00<?, ?it/s]

Reports:   0%|          | 1/7111 [00:00<31:22,  3.78it/s]

Reports:   0%|          | 2/7111 [00:00<33:49,  3.50it/s]

Reports:   0%|          | 3/7111 [00:00<33:11,  3.57it/s]

Reports:   0%|          | 4/7111 [00:01<29:12,  4.06it/s]

Reports:   0%|          | 5/7111 [00:01<27:09,  4.36it/s]

Reports:   0%|          | 6/7111 [00:01<25:42,  4.61it/s]

Reports:   0%|          | 7/7111 [00:01<24:47,  4.78it/s]

Reports:   0%|          | 8/7111 [00:01<24:18,  4.87it/s]

Reports:   0%|          | 9/7111 [00:02<26:21,  4.49it/s]

Reports:   0%|          | 10/7111 [00:02<25:42,  4.60it/s]

Reports:   0%|          | 11/7111 [00:02<25:59,  4.55it/s]

Reports:   0%|          | 12/7111 [00:02<25:00,  4.73it/s]

Reports:   0%|          | 13/7111 [00:02<25:27,  4.65it/s]

Reports:   0%|          | 14/7111 [00:03<24:38,  4.80it/s]

Reports:   0%|          | 15/7111 [00:03<23:55,  4.94it/s]

Reports:   0%|          | 16/7111 [00:03<23:49,  4.96it/s]

Reports:   0%|          | 17/7111 [00:03<23:27,  5.04it/s]

Reports:   0%|          | 18/7111 [00:03<22:47,  5.19it/s]

Reports:   0%|          | 19/7111 [00:04<22:37,  5.22it/s]

Reports:   0%|          | 20/7111 [00:04<22:32,  5.24it/s]

Reports:   0%|          | 21/7111 [00:04<22:40,  5.21it/s]

Reports:   0%|          | 22/7111 [00:04<22:57,  5.15it/s]

Reports:   0%|          | 23/7111 [00:04<22:54,  5.16it/s]

Reports:   0%|          | 24/7111 [00:05<23:01,  5.13it/s]

Reports:   0%|          | 25/7111 [00:05<22:58,  5.14it/s]

Reports:   0%|          | 26/7111 [00:05<23:09,  5.10it/s]

Reports:   0%|          | 27/7111 [00:05<22:56,  5.15it/s]

Reports:   0%|          | 28/7111 [00:05<22:59,  5.14it/s]

Reports:   0%|          | 29/7111 [00:06<23:37,  5.00it/s]

Reports:   0%|          | 30/7111 [00:06<23:47,  4.96it/s]

Reports:   0%|          | 31/7111 [00:06<23:22,  5.05it/s]

Reports:   0%|          | 32/7111 [00:06<23:44,  4.97it/s]

Reports:   0%|          | 33/7111 [00:06<23:48,  4.95it/s]

Reports:   0%|          | 34/7111 [00:07<23:44,  4.97it/s]

Reports:   0%|          | 35/7111 [00:07<23:39,  4.98it/s]

Reports:   1%|          | 36/7111 [00:07<23:12,  5.08it/s]

Reports:   1%|          | 37/7111 [00:07<23:49,  4.95it/s]

Reports:   1%|          | 38/7111 [00:07<23:55,  4.93it/s]

Reports:   1%|          | 39/7111 [00:08<23:42,  4.97it/s]

Reports:   1%|          | 40/7111 [00:08<23:19,  5.05it/s]

Reports:   1%|          | 41/7111 [00:08<23:53,  4.93it/s]

Reports:   1%|          | 42/7111 [00:08<23:28,  5.02it/s]

Reports:   1%|          | 43/7111 [00:08<23:08,  5.09it/s]

Reports:   1%|          | 44/7111 [00:09<22:42,  5.19it/s]

Reports:   1%|          | 45/7111 [00:09<22:33,  5.22it/s]

Reports:   1%|          | 46/7111 [00:09<22:34,  5.22it/s]

Reports:   1%|          | 47/7111 [00:09<22:28,  5.24it/s]

Reports:   1%|          | 48/7111 [00:09<22:18,  5.28it/s]

Reports:   1%|          | 49/7111 [00:09<22:46,  5.17it/s]

Reports:   1%|          | 50/7111 [00:10<22:58,  5.12it/s]

Reports:   1%|          | 51/7111 [00:10<22:29,  5.23it/s]

Reports:   1%|          | 52/7111 [00:10<22:56,  5.13it/s]

Reports:   1%|          | 53/7111 [00:10<22:45,  5.17it/s]

Reports:   1%|          | 54/7111 [00:10<22:30,  5.23it/s]

Reports:   1%|          | 55/7111 [00:11<22:46,  5.16it/s]

Reports:   1%|          | 56/7111 [00:11<22:31,  5.22it/s]

Reports:   1%|          | 57/7111 [00:11<22:43,  5.17it/s]

Reports:   1%|          | 58/7111 [00:11<23:03,  5.10it/s]

Reports:   1%|          | 59/7111 [00:11<22:58,  5.12it/s]

Reports:   1%|          | 60/7111 [00:12<23:02,  5.10it/s]

Reports:   1%|          | 61/7111 [00:12<22:47,  5.16it/s]

Reports:   1%|          | 62/7111 [00:12<22:47,  5.15it/s]

Reports:   1%|          | 63/7111 [00:12<23:26,  5.01it/s]

Reports:   1%|          | 64/7111 [00:12<23:12,  5.06it/s]

Reports:   1%|          | 65/7111 [00:13<24:10,  4.86it/s]

Reports:   1%|          | 66/7111 [00:13<24:02,  4.88it/s]

Reports:   1%|          | 67/7111 [00:13<23:40,  4.96it/s]

Reports:   1%|          | 68/7111 [00:13<23:29,  5.00it/s]

Reports:   1%|          | 69/7111 [00:13<23:38,  4.96it/s]

Reports:   1%|          | 70/7111 [00:14<23:35,  4.97it/s]

Reports:   1%|          | 71/7111 [00:14<23:24,  5.01it/s]

Reports:   1%|          | 72/7111 [00:14<23:00,  5.10it/s]

Reports:   1%|          | 73/7111 [00:14<23:21,  5.02it/s]

Reports:   1%|          | 74/7111 [00:14<23:13,  5.05it/s]

Reports:   1%|          | 75/7111 [00:15<23:33,  4.98it/s]

Reports:   1%|          | 76/7111 [00:15<23:35,  4.97it/s]

Reports:   1%|          | 77/7111 [00:15<23:42,  4.95it/s]

Reports:   1%|          | 78/7111 [00:15<23:54,  4.90it/s]

Reports:   1%|          | 79/7111 [00:15<23:27,  5.00it/s]

Reports:   1%|          | 80/7111 [00:16<22:59,  5.10it/s]

Reports:   1%|          | 81/7111 [00:16<22:50,  5.13it/s]

Reports:   1%|          | 82/7111 [00:16<22:39,  5.17it/s]

Reports:   1%|          | 83/7111 [00:16<24:41,  4.74it/s]

Reports:   1%|          | 84/7111 [00:16<23:59,  4.88it/s]

Reports:   1%|          | 85/7111 [00:17<23:26,  5.00it/s]

Reports:   1%|          | 86/7111 [00:17<23:05,  5.07it/s]

Reports:   1%|          | 87/7111 [00:17<22:54,  5.11it/s]

Reports:   1%|          | 88/7111 [00:17<22:57,  5.10it/s]

Reports:   1%|▏         | 89/7111 [00:17<22:59,  5.09it/s]

Reports:   1%|▏         | 90/7111 [00:18<22:57,  5.10it/s]

Reports:   1%|▏         | 91/7111 [00:18<22:37,  5.17it/s]

Reports:   1%|▏         | 92/7111 [00:18<22:23,  5.23it/s]

Reports:   1%|▏         | 93/7111 [00:18<22:16,  5.25it/s]

Reports:   1%|▏         | 94/7111 [00:18<22:15,  5.25it/s]

Reports:   1%|▏         | 95/7111 [00:19<22:08,  5.28it/s]

Reports:   1%|▏         | 96/7111 [00:19<22:05,  5.29it/s]

Reports:   1%|▏         | 97/7111 [00:19<22:35,  5.18it/s]

Reports:   1%|▏         | 98/7111 [00:19<22:39,  5.16it/s]

Reports:   1%|▏         | 99/7111 [00:19<22:49,  5.12it/s]

Reports:   1%|▏         | 100/7111 [00:20<22:49,  5.12it/s]

Reports:   1%|▏         | 101/7111 [00:20<22:32,  5.18it/s]

Reports:   1%|▏         | 102/7111 [00:20<22:44,  5.14it/s]

Reports:   1%|▏         | 103/7111 [00:20<23:02,  5.07it/s]

Reports:   1%|▏         | 104/7111 [00:20<22:40,  5.15it/s]

Reports:   1%|▏         | 105/7111 [00:20<22:42,  5.14it/s]

Reports:   1%|▏         | 106/7111 [00:21<22:54,  5.10it/s]

Reports:   2%|▏         | 107/7111 [00:21<23:02,  5.06it/s]

Reports:   2%|▏         | 108/7111 [00:21<22:38,  5.15it/s]

Reports:   2%|▏         | 109/7111 [00:21<22:31,  5.18it/s]

Reports:   2%|▏         | 110/7111 [00:21<22:57,  5.08it/s]

Reports:   2%|▏         | 111/7111 [00:22<23:06,  5.05it/s]

Reports:   2%|▏         | 112/7111 [00:22<22:36,  5.16it/s]

Reports:   2%|▏         | 113/7111 [00:22<22:16,  5.24it/s]

Reports:   2%|▏         | 114/7111 [00:22<22:16,  5.23it/s]

Reports:   2%|▏         | 115/7111 [00:22<22:17,  5.23it/s]

Reports:   2%|▏         | 116/7111 [00:23<22:43,  5.13it/s]

Reports:   2%|▏         | 117/7111 [00:23<23:05,  5.05it/s]

Reports:   2%|▏         | 118/7111 [00:23<22:40,  5.14it/s]

Reports:   2%|▏         | 119/7111 [00:23<22:29,  5.18it/s]

Reports:   2%|▏         | 120/7111 [00:23<22:39,  5.14it/s]

Reports:   2%|▏         | 121/7111 [00:24<22:51,  5.10it/s]

Reports:   2%|▏         | 122/7111 [00:24<22:53,  5.09it/s]

Reports:   2%|▏         | 123/7111 [00:24<22:44,  5.12it/s]

Reports:   2%|▏         | 124/7111 [00:24<22:49,  5.10it/s]

Reports:   2%|▏         | 125/7111 [00:24<23:03,  5.05it/s]

Reports:   2%|▏         | 126/7111 [00:25<23:12,  5.02it/s]

Reports:   2%|▏         | 127/7111 [00:25<23:11,  5.02it/s]

Reports:   2%|▏         | 128/7111 [00:25<22:45,  5.11it/s]

Reports:   2%|▏         | 129/7111 [00:25<22:40,  5.13it/s]

Reports:   2%|▏         | 130/7111 [00:25<22:39,  5.13it/s]

Reports:   2%|▏         | 131/7111 [00:26<22:33,  5.16it/s]

Reports:   2%|▏         | 132/7111 [00:26<22:38,  5.14it/s]

Reports:   2%|▏         | 133/7111 [00:26<22:49,  5.09it/s]

Reports:   2%|▏         | 134/7111 [00:26<22:42,  5.12it/s]

Reports:   2%|▏         | 135/7111 [00:26<22:57,  5.07it/s]

Reports:   2%|▏         | 136/7111 [00:27<23:07,  5.03it/s]

Reports:   2%|▏         | 137/7111 [00:27<22:47,  5.10it/s]

Reports:   2%|▏         | 138/7111 [00:27<22:22,  5.19it/s]

Reports:   2%|▏         | 139/7111 [00:27<22:30,  5.16it/s]

Reports:   2%|▏         | 140/7111 [00:27<22:43,  5.11it/s]

Reports:   2%|▏         | 141/7111 [00:28<22:28,  5.17it/s]

Reports:   2%|▏         | 142/7111 [00:28<22:26,  5.17it/s]

Reports:   2%|▏         | 143/7111 [00:28<22:30,  5.16it/s]

Reports:   2%|▏         | 144/7111 [00:28<22:56,  5.06it/s]

Reports:   2%|▏         | 145/7111 [00:28<22:46,  5.10it/s]

Reports:   2%|▏         | 146/7111 [00:28<23:02,  5.04it/s]

Reports:   2%|▏         | 147/7111 [00:29<22:39,  5.12it/s]

Reports:   2%|▏         | 148/7111 [00:29<23:06,  5.02it/s]

Reports:   2%|▏         | 149/7111 [00:29<22:41,  5.12it/s]

Reports:   2%|▏         | 150/7111 [00:29<22:39,  5.12it/s]

Reports:   2%|▏         | 151/7111 [00:29<22:19,  5.19it/s]

Reports:   2%|▏         | 152/7111 [00:30<22:16,  5.21it/s]

Reports:   2%|▏         | 153/7111 [00:30<22:43,  5.10it/s]

Reports:   2%|▏         | 154/7111 [00:30<22:54,  5.06it/s]

Reports:   2%|▏         | 155/7111 [00:30<22:31,  5.15it/s]

Reports:   2%|▏         | 156/7111 [00:30<22:21,  5.18it/s]

Reports:   2%|▏         | 157/7111 [00:31<22:30,  5.15it/s]

Reports:   2%|▏         | 158/7111 [00:31<22:27,  5.16it/s]

Reports:   2%|▏         | 159/7111 [00:31<22:21,  5.18it/s]

Reports:   2%|▏         | 160/7111 [00:31<22:39,  5.11it/s]

Reports:   2%|▏         | 161/7111 [00:31<22:33,  5.14it/s]

Reports:   2%|▏         | 162/7111 [00:32<22:37,  5.12it/s]

Reports:   2%|▏         | 163/7111 [00:32<22:47,  5.08it/s]

Reports:   2%|▏         | 164/7111 [00:32<23:29,  4.93it/s]

Reports:   2%|▏         | 165/7111 [00:32<23:45,  4.87it/s]

Reports:   2%|▏         | 166/7111 [00:32<23:36,  4.90it/s]

Reports:   2%|▏         | 167/7111 [00:33<23:41,  4.88it/s]

Reports:   2%|▏         | 168/7111 [00:33<23:34,  4.91it/s]

Reports:   2%|▏         | 169/7111 [00:33<23:44,  4.87it/s]

Reports:   2%|▏         | 170/7111 [00:33<23:29,  4.92it/s]

Reports:   2%|▏         | 171/7111 [00:33<23:43,  4.87it/s]

Reports:   2%|▏         | 172/7111 [00:34<23:09,  4.99it/s]

Reports:   2%|▏         | 173/7111 [00:34<22:45,  5.08it/s]

Reports:   2%|▏         | 174/7111 [00:34<23:19,  4.96it/s]

Reports:   2%|▏         | 175/7111 [00:34<23:17,  4.96it/s]

Reports:   2%|▏         | 176/7111 [00:34<22:43,  5.08it/s]

Reports:   2%|▏         | 177/7111 [00:35<23:28,  4.92it/s]

Reports:   3%|▎         | 178/7111 [00:35<22:52,  5.05it/s]

Reports:   3%|▎         | 179/7111 [00:35<22:50,  5.06it/s]

Reports:   3%|▎         | 180/7111 [00:35<22:54,  5.04it/s]

Reports:   3%|▎         | 181/7111 [00:35<22:21,  5.17it/s]

Reports:   3%|▎         | 182/7111 [00:36<22:24,  5.15it/s]

Reports:   3%|▎         | 183/7111 [00:36<22:37,  5.10it/s]

Reports:   3%|▎         | 184/7111 [00:36<22:27,  5.14it/s]

Reports:   3%|▎         | 185/7111 [00:36<22:47,  5.06it/s]

Reports:   3%|▎         | 186/7111 [00:36<22:26,  5.14it/s]

Reports:   3%|▎         | 187/7111 [00:37<22:10,  5.20it/s]

Reports:   3%|▎         | 188/7111 [00:37<22:27,  5.14it/s]

Reports:   3%|▎         | 189/7111 [00:37<22:14,  5.19it/s]

Reports:   3%|▎         | 190/7111 [00:37<22:19,  5.17it/s]

Reports:   3%|▎         | 191/7111 [00:37<21:58,  5.25it/s]

Reports:   3%|▎         | 192/7111 [00:38<22:07,  5.21it/s]

Reports:   3%|▎         | 193/7111 [00:38<22:14,  5.18it/s]

Reports:   3%|▎         | 194/7111 [00:38<22:03,  5.22it/s]

Reports:   3%|▎         | 195/7111 [00:38<22:04,  5.22it/s]

Reports:   3%|▎         | 196/7111 [00:38<22:06,  5.21it/s]

Reports:   3%|▎         | 197/7111 [00:39<22:12,  5.19it/s]

Reports:   3%|▎         | 198/7111 [00:39<21:52,  5.27it/s]

Reports:   3%|▎         | 199/7111 [00:39<22:14,  5.18it/s]

Reports:   3%|▎         | 200/7111 [00:39<22:19,  5.16it/s]

Reports:   3%|▎         | 201/7111 [00:39<22:52,  5.03it/s]

Reports:   3%|▎         | 202/7111 [00:40<23:01,  5.00it/s]

Reports:   3%|▎         | 203/7111 [00:40<23:12,  4.96it/s]

Reports:   3%|▎         | 204/7111 [00:40<22:51,  5.03it/s]

Reports:   3%|▎         | 205/7111 [00:40<22:50,  5.04it/s]

Reports:   3%|▎         | 206/7111 [00:40<22:26,  5.13it/s]

Reports:   3%|▎         | 207/7111 [00:40<22:39,  5.08it/s]

Reports:   3%|▎         | 208/7111 [00:41<22:24,  5.13it/s]

Reports:   3%|▎         | 209/7111 [00:41<22:15,  5.17it/s]

Reports:   3%|▎         | 210/7111 [00:41<22:12,  5.18it/s]

Reports:   3%|▎         | 211/7111 [00:41<21:53,  5.25it/s]

Reports:   3%|▎         | 212/7111 [00:41<21:46,  5.28it/s]

Reports:   3%|▎         | 213/7111 [00:42<22:25,  5.13it/s]

Reports:   3%|▎         | 214/7111 [00:42<22:24,  5.13it/s]

Reports:   3%|▎         | 215/7111 [00:42<22:12,  5.17it/s]

Reports:   3%|▎         | 216/7111 [00:42<21:56,  5.24it/s]

Reports:   3%|▎         | 217/7111 [00:42<21:40,  5.30it/s]

Reports:   3%|▎         | 218/7111 [00:43<21:56,  5.24it/s]

Reports:   3%|▎         | 219/7111 [00:43<22:02,  5.21it/s]

Reports:   3%|▎         | 220/7111 [00:43<22:03,  5.21it/s]

Reports:   3%|▎         | 221/7111 [00:43<21:56,  5.23it/s]

Reports:   3%|▎         | 222/7111 [00:43<21:57,  5.23it/s]

Reports:   3%|▎         | 223/7111 [00:44<21:54,  5.24it/s]

Reports:   3%|▎         | 224/7111 [00:44<21:53,  5.24it/s]

Reports:   3%|▎         | 225/7111 [00:44<21:52,  5.25it/s]

Reports:   3%|▎         | 226/7111 [00:44<22:23,  5.12it/s]

Reports:   3%|▎         | 227/7111 [00:44<22:41,  5.05it/s]

Reports:   3%|▎         | 228/7111 [00:45<22:13,  5.16it/s]

Reports:   3%|▎         | 229/7111 [00:45<21:56,  5.23it/s]

Reports:   3%|▎         | 230/7111 [00:45<21:53,  5.24it/s]

Reports:   3%|▎         | 231/7111 [00:45<22:05,  5.19it/s]

Reports:   3%|▎         | 232/7111 [00:45<22:17,  5.14it/s]

Reports:   3%|▎         | 233/7111 [00:45<22:12,  5.16it/s]

Reports:   3%|▎         | 234/7111 [00:46<22:12,  5.16it/s]

Reports:   3%|▎         | 235/7111 [00:46<22:06,  5.19it/s]

Reports:   3%|▎         | 236/7111 [00:46<22:22,  5.12it/s]

Reports:   3%|▎         | 237/7111 [00:46<22:12,  5.16it/s]

Reports:   3%|▎         | 238/7111 [00:46<21:55,  5.23it/s]

Reports:   3%|▎         | 239/7111 [00:47<22:17,  5.14it/s]

Reports:   3%|▎         | 240/7111 [00:47<22:12,  5.15it/s]

Reports:   3%|▎         | 241/7111 [00:47<22:24,  5.11it/s]

Reports:   3%|▎         | 242/7111 [00:47<22:15,  5.15it/s]

Reports:   3%|▎         | 243/7111 [00:47<22:44,  5.03it/s]

Reports:   3%|▎         | 244/7111 [00:48<22:35,  5.07it/s]

Reports:   3%|▎         | 245/7111 [00:48<22:35,  5.07it/s]

Reports:   3%|▎         | 246/7111 [00:48<22:50,  5.01it/s]

Reports:   3%|▎         | 247/7111 [00:49<55:02,  2.08it/s]

Reports:   3%|▎         | 248/7111 [00:49<45:40,  2.50it/s]

Reports:   4%|▎         | 249/7111 [00:50<38:25,  2.98it/s]

Reports:   4%|▎         | 250/7111 [00:50<34:10,  3.35it/s]

Reports:   4%|▎         | 251/7111 [00:50<31:06,  3.68it/s]

Reports:   4%|▎         | 252/7111 [00:50<28:46,  3.97it/s]

Reports:   4%|▎         | 253/7111 [00:50<27:45,  4.12it/s]

Reports:   4%|▎         | 254/7111 [00:51<26:29,  4.31it/s]

Reports:   4%|▎         | 255/7111 [00:51<25:40,  4.45it/s]

Reports:   4%|▎         | 256/7111 [00:51<24:35,  4.65it/s]

Reports:   4%|▎         | 257/7111 [00:51<23:45,  4.81it/s]

Reports:   4%|▎         | 258/7111 [00:51<23:11,  4.93it/s]

Reports:   4%|▎         | 259/7111 [00:52<22:51,  5.00it/s]

Reports:   4%|▎         | 260/7111 [00:52<23:10,  4.93it/s]

Reports:   4%|▎         | 261/7111 [00:52<22:41,  5.03it/s]

Reports:   4%|▎         | 262/7111 [00:52<22:26,  5.09it/s]

Reports:   4%|▎         | 263/7111 [00:52<22:19,  5.11it/s]

Reports:   4%|▎         | 264/7111 [00:53<22:13,  5.14it/s]

Reports:   4%|▎         | 265/7111 [00:53<22:10,  5.14it/s]

Reports:   4%|▎         | 266/7111 [00:53<22:41,  5.03it/s]

Reports:   4%|▍         | 267/7111 [00:53<22:45,  5.01it/s]

Reports:   4%|▍         | 268/7111 [00:53<22:30,  5.07it/s]

Reports:   4%|▍         | 269/7111 [00:54<22:24,  5.09it/s]

Reports:   4%|▍         | 270/7111 [00:54<21:57,  5.19it/s]

Reports:   4%|▍         | 271/7111 [00:54<21:50,  5.22it/s]

Reports:   4%|▍         | 272/7111 [00:54<24:33,  4.64it/s]

Reports:   4%|▍         | 273/7111 [00:54<24:02,  4.74it/s]

Reports:   4%|▍         | 274/7111 [00:55<23:36,  4.83it/s]

Reports:   4%|▍         | 275/7111 [00:55<23:50,  4.78it/s]

Reports:   4%|▍         | 276/7111 [00:55<23:43,  4.80it/s]

Reports:   4%|▍         | 277/7111 [00:55<23:10,  4.91it/s]

Reports:   4%|▍         | 278/7111 [00:55<22:25,  5.08it/s]

Reports:   4%|▍         | 279/7111 [00:56<22:21,  5.09it/s]

Reports:   4%|▍         | 280/7111 [00:56<22:57,  4.96it/s]

Reports:   4%|▍         | 281/7111 [00:56<23:11,  4.91it/s]

Reports:   4%|▍         | 282/7111 [00:56<22:31,  5.05it/s]

Reports:   4%|▍         | 283/7111 [00:56<22:49,  4.99it/s]

Reports:   4%|▍         | 284/7111 [00:57<22:43,  5.01it/s]

Reports:   4%|▍         | 285/7111 [00:57<22:19,  5.09it/s]

Reports:   4%|▍         | 286/7111 [00:57<22:10,  5.13it/s]

Reports:   4%|▍         | 287/7111 [00:57<22:12,  5.12it/s]

Reports:   4%|▍         | 288/7111 [00:57<21:53,  5.20it/s]

Reports:   4%|▍         | 289/7111 [00:58<22:02,  5.16it/s]

Reports:   4%|▍         | 290/7111 [00:58<22:10,  5.12it/s]

Reports:   4%|▍         | 291/7111 [00:58<22:12,  5.12it/s]

Reports:   4%|▍         | 292/7111 [00:58<22:35,  5.03it/s]

Reports:   4%|▍         | 293/7111 [00:58<22:42,  5.00it/s]

Reports:   4%|▍         | 294/7111 [00:59<22:35,  5.03it/s]

Reports:   4%|▍         | 295/7111 [00:59<22:18,  5.09it/s]

Reports:   4%|▍         | 296/7111 [00:59<22:10,  5.12it/s]

Reports:   4%|▍         | 297/7111 [00:59<22:32,  5.04it/s]

Reports:   4%|▍         | 298/7111 [00:59<22:35,  5.02it/s]

Reports:   4%|▍         | 299/7111 [01:00<22:29,  5.05it/s]

Reports:   4%|▍         | 300/7111 [01:00<22:24,  5.06it/s]

Reports:   4%|▍         | 301/7111 [01:00<22:31,  5.04it/s]

Reports:   4%|▍         | 302/7111 [01:01<39:02,  2.91it/s]

Reports:   4%|▍         | 303/7111 [01:01<34:00,  3.34it/s]

Reports:   4%|▍         | 304/7111 [01:01<30:19,  3.74it/s]

Reports:   4%|▍         | 305/7111 [01:01<27:41,  4.10it/s]

Reports:   4%|▍         | 306/7111 [01:01<25:41,  4.41it/s]

Reports:   4%|▍         | 307/7111 [01:02<24:15,  4.67it/s]

Reports:   4%|▍         | 308/7111 [01:02<24:03,  4.71it/s]

Reports:   4%|▍         | 309/7111 [01:02<23:32,  4.81it/s]

Reports:   4%|▍         | 310/7111 [01:02<23:26,  4.84it/s]

Reports:   4%|▍         | 311/7111 [01:02<23:13,  4.88it/s]

Reports:   4%|▍         | 312/7111 [01:03<22:34,  5.02it/s]

Reports:   4%|▍         | 313/7111 [01:03<22:34,  5.02it/s]

Reports:   4%|▍         | 314/7111 [01:03<22:27,  5.04it/s]

Reports:   4%|▍         | 315/7111 [01:03<22:11,  5.10it/s]

Reports:   4%|▍         | 316/7111 [01:03<22:40,  4.99it/s]

Reports:   4%|▍         | 317/7111 [01:04<22:17,  5.08it/s]

Reports:   4%|▍         | 318/7111 [01:04<22:25,  5.05it/s]

Reports:   4%|▍         | 319/7111 [01:04<22:30,  5.03it/s]

Reports:   5%|▍         | 320/7111 [01:04<22:28,  5.04it/s]

Reports:   5%|▍         | 321/7111 [01:04<22:21,  5.06it/s]

Reports:   5%|▍         | 322/7111 [01:05<22:42,  4.98it/s]

Reports:   5%|▍         | 323/7111 [01:05<22:59,  4.92it/s]

Reports:   5%|▍         | 324/7111 [01:05<23:11,  4.88it/s]

Reports:   5%|▍         | 325/7111 [01:05<23:04,  4.90it/s]

Reports:   5%|▍         | 326/7111 [01:05<22:58,  4.92it/s]

Reports:   5%|▍         | 327/7111 [01:06<22:52,  4.94it/s]

Reports:   5%|▍         | 328/7111 [01:06<22:20,  5.06it/s]

Reports:   5%|▍         | 329/7111 [01:06<22:26,  5.04it/s]

Reports:   5%|▍         | 330/7111 [01:06<22:35,  5.00it/s]

Reports:   5%|▍         | 331/7111 [01:06<22:25,  5.04it/s]

Reports:   5%|▍         | 332/7111 [01:07<22:21,  5.05it/s]

Reports:   5%|▍         | 333/7111 [01:07<22:17,  5.07it/s]

Reports:   5%|▍         | 334/7111 [01:07<22:12,  5.08it/s]

Reports:   5%|▍         | 335/7111 [01:07<22:05,  5.11it/s]

Reports:   5%|▍         | 336/7111 [01:07<21:58,  5.14it/s]

Reports:   5%|▍         | 337/7111 [01:08<21:57,  5.14it/s]

Reports:   5%|▍         | 338/7111 [01:08<21:42,  5.20it/s]

Reports:   5%|▍         | 339/7111 [01:08<21:44,  5.19it/s]

Reports:   5%|▍         | 340/7111 [01:08<21:39,  5.21it/s]

Reports:   5%|▍         | 341/7111 [01:08<21:54,  5.15it/s]

Reports:   5%|▍         | 342/7111 [01:09<22:01,  5.12it/s]

Reports:   5%|▍         | 343/7111 [01:09<21:48,  5.17it/s]

Reports:   5%|▍         | 344/7111 [01:09<22:07,  5.10it/s]

Reports:   5%|▍         | 345/7111 [01:09<22:13,  5.07it/s]

Reports:   5%|▍         | 346/7111 [01:09<22:47,  4.95it/s]

Reports:   5%|▍         | 347/7111 [01:10<22:22,  5.04it/s]

Reports:   5%|▍         | 348/7111 [01:10<22:11,  5.08it/s]

Reports:   5%|▍         | 349/7111 [01:10<22:11,  5.08it/s]

Reports:   5%|▍         | 350/7111 [01:10<22:57,  4.91it/s]

Reports:   5%|▍         | 351/7111 [01:10<22:26,  5.02it/s]

Reports:   5%|▍         | 352/7111 [01:11<23:03,  4.88it/s]

Reports:   5%|▍         | 353/7111 [01:11<22:44,  4.95it/s]

Reports:   5%|▍         | 354/7111 [01:11<22:09,  5.08it/s]

Reports:   5%|▍         | 355/7111 [01:11<22:23,  5.03it/s]

Reports:   5%|▌         | 356/7111 [01:11<23:02,  4.88it/s]

Reports:   5%|▌         | 357/7111 [01:12<22:49,  4.93it/s]

Reports:   5%|▌         | 358/7111 [01:12<22:41,  4.96it/s]

Reports:   5%|▌         | 359/7111 [01:12<22:25,  5.02it/s]

Reports:   5%|▌         | 360/7111 [01:12<22:40,  4.96it/s]

Reports:   5%|▌         | 361/7111 [01:12<23:10,  4.85it/s]

Reports:   5%|▌         | 362/7111 [01:13<23:01,  4.88it/s]

Reports:   5%|▌         | 363/7111 [01:13<22:25,  5.01it/s]

Reports:   5%|▌         | 364/7111 [01:13<22:27,  5.01it/s]

Reports:   5%|▌         | 365/7111 [01:13<22:50,  4.92it/s]

Reports:   5%|▌         | 366/7111 [01:13<23:25,  4.80it/s]

Reports:   5%|▌         | 367/7111 [01:14<22:45,  4.94it/s]

Reports:   5%|▌         | 368/7111 [01:14<22:14,  5.05it/s]

Reports:   5%|▌         | 369/7111 [01:14<22:06,  5.08it/s]

Reports:   5%|▌         | 370/7111 [01:14<22:27,  5.00it/s]

Reports:   5%|▌         | 371/7111 [01:14<22:34,  4.98it/s]

Reports:   5%|▌         | 372/7111 [01:15<22:18,  5.03it/s]

Reports:   5%|▌         | 373/7111 [01:15<22:14,  5.05it/s]

Reports:   5%|▌         | 374/7111 [01:15<21:56,  5.12it/s]

Reports:   5%|▌         | 375/7111 [01:15<22:00,  5.10it/s]

Reports:   5%|▌         | 376/7111 [01:15<22:04,  5.08it/s]

Reports:   5%|▌         | 377/7111 [01:16<22:03,  5.09it/s]

Reports:   5%|▌         | 378/7111 [01:16<22:02,  5.09it/s]

Reports:   5%|▌         | 379/7111 [01:16<21:52,  5.13it/s]

Reports:   5%|▌         | 380/7111 [01:16<21:45,  5.16it/s]

Reports:   5%|▌         | 381/7111 [01:16<21:36,  5.19it/s]

Reports:   5%|▌         | 382/7111 [01:16<21:27,  5.23it/s]

Reports:   5%|▌         | 383/7111 [01:17<21:35,  5.19it/s]

Reports:   5%|▌         | 384/7111 [01:17<21:37,  5.19it/s]

Reports:   5%|▌         | 385/7111 [01:17<21:34,  5.19it/s]

Reports:   5%|▌         | 386/7111 [01:17<21:46,  5.15it/s]

Reports:   5%|▌         | 387/7111 [01:17<21:55,  5.11it/s]

Reports:   5%|▌         | 388/7111 [01:18<21:51,  5.13it/s]

Reports:   5%|▌         | 389/7111 [01:18<22:03,  5.08it/s]

Reports:   5%|▌         | 390/7111 [01:18<21:44,  5.15it/s]

Reports:   5%|▌         | 391/7111 [01:18<22:14,  5.04it/s]

Reports:   6%|▌         | 392/7111 [01:18<22:26,  4.99it/s]

Reports:   6%|▌         | 393/7111 [01:19<22:15,  5.03it/s]

Reports:   6%|▌         | 394/7111 [01:19<22:30,  4.98it/s]

Reports:   6%|▌         | 395/7111 [01:19<22:31,  4.97it/s]

Reports:   6%|▌         | 396/7111 [01:19<22:10,  5.05it/s]

Reports:   6%|▌         | 397/7111 [01:19<22:09,  5.05it/s]

Reports:   6%|▌         | 398/7111 [01:20<22:36,  4.95it/s]

Reports:   6%|▌         | 399/7111 [01:20<23:44,  4.71it/s]

Reports:   6%|▌         | 400/7111 [01:20<23:41,  4.72it/s]

Reports:   6%|▌         | 401/7111 [01:20<23:26,  4.77it/s]

Reports:   6%|▌         | 402/7111 [01:20<22:55,  4.88it/s]

Reports:   6%|▌         | 403/7111 [01:21<23:10,  4.83it/s]

Reports:   6%|▌         | 404/7111 [01:21<22:38,  4.94it/s]

Reports:   6%|▌         | 405/7111 [01:21<22:46,  4.91it/s]

Reports:   6%|▌         | 406/7111 [01:21<22:13,  5.03it/s]

Reports:   6%|▌         | 407/7111 [01:21<22:06,  5.05it/s]

Reports:   6%|▌         | 408/7111 [01:22<22:34,  4.95it/s]

Reports:   6%|▌         | 409/7111 [01:22<22:40,  4.92it/s]

Reports:   6%|▌         | 410/7111 [01:22<22:47,  4.90it/s]

Reports:   6%|▌         | 411/7111 [01:22<22:59,  4.86it/s]

Reports:   6%|▌         | 412/7111 [01:23<22:45,  4.91it/s]

Reports:   6%|▌         | 413/7111 [01:23<22:23,  4.99it/s]

Reports:   6%|▌         | 414/7111 [01:23<22:20,  4.99it/s]

Reports:   6%|▌         | 415/7111 [01:23<22:44,  4.91it/s]

Reports:   6%|▌         | 416/7111 [01:23<22:32,  4.95it/s]

Reports:   6%|▌         | 417/7111 [01:24<22:08,  5.04it/s]

Reports:   6%|▌         | 418/7111 [01:24<21:53,  5.09it/s]

Reports:   6%|▌         | 419/7111 [01:24<21:41,  5.14it/s]

Reports:   6%|▌         | 420/7111 [01:24<22:13,  5.02it/s]

Reports:   6%|▌         | 421/7111 [01:24<21:50,  5.10it/s]

Reports:   6%|▌         | 422/7111 [01:24<21:34,  5.17it/s]

Reports:   6%|▌         | 423/7111 [01:25<21:26,  5.20it/s]

Reports:   6%|▌         | 424/7111 [01:25<21:16,  5.24it/s]

Reports:   6%|▌         | 425/7111 [01:25<21:29,  5.18it/s]

Reports:   6%|▌         | 426/7111 [01:25<21:11,  5.26it/s]

Reports:   6%|▌         | 427/7111 [01:25<21:51,  5.10it/s]

Reports:   6%|▌         | 428/7111 [01:26<21:34,  5.16it/s]

Reports:   6%|▌         | 429/7111 [01:26<20:49,  5.35it/s]

Reports:   6%|▌         | 430/7111 [01:26<21:18,  5.23it/s]

Reports:   6%|▌         | 431/7111 [01:26<21:33,  5.16it/s]

Reports:   6%|▌         | 432/7111 [01:26<21:18,  5.23it/s]

Reports:   6%|▌         | 433/7111 [01:27<21:40,  5.13it/s]

Reports:   6%|▌         | 434/7111 [01:27<21:45,  5.11it/s]

Reports:   6%|▌         | 435/7111 [01:27<21:32,  5.16it/s]

Reports:   6%|▌         | 436/7111 [01:27<21:26,  5.19it/s]

Reports:   6%|▌         | 437/7111 [01:27<21:41,  5.13it/s]

Reports:   6%|▌         | 438/7111 [01:28<21:27,  5.18it/s]

Reports:   6%|▌         | 439/7111 [01:28<21:41,  5.13it/s]

Reports:   6%|▌         | 440/7111 [01:28<21:48,  5.10it/s]

Reports:   6%|▌         | 441/7111 [01:28<21:23,  5.19it/s]

Reports:   6%|▌         | 442/7111 [01:28<21:19,  5.21it/s]

Reports:   6%|▌         | 443/7111 [01:29<21:32,  5.16it/s]

Reports:   6%|▌         | 444/7111 [01:29<21:48,  5.10it/s]

Reports:   6%|▋         | 445/7111 [01:29<21:38,  5.13it/s]

Reports:   6%|▋         | 446/7111 [01:29<21:38,  5.13it/s]

Reports:   6%|▋         | 447/7111 [01:29<22:03,  5.03it/s]

Reports:   6%|▋         | 448/7111 [01:30<22:23,  4.96it/s]

Reports:   6%|▋         | 449/7111 [01:30<22:20,  4.97it/s]

Reports:   6%|▋         | 450/7111 [01:30<22:10,  5.00it/s]

Reports:   6%|▋         | 451/7111 [01:30<21:53,  5.07it/s]

Reports:   6%|▋         | 452/7111 [01:30<21:39,  5.12it/s]

Reports:   6%|▋         | 453/7111 [01:31<21:30,  5.16it/s]

Reports:   6%|▋         | 454/7111 [01:31<22:00,  5.04it/s]

Reports:   6%|▋         | 455/7111 [01:31<21:33,  5.14it/s]

Reports:   6%|▋         | 456/7111 [01:31<21:44,  5.10it/s]

Reports:   6%|▋         | 457/7111 [01:31<21:42,  5.11it/s]

Reports:   6%|▋         | 458/7111 [01:32<22:07,  5.01it/s]

Reports:   6%|▋         | 459/7111 [01:32<22:12,  4.99it/s]

Reports:   6%|▋         | 460/7111 [01:32<22:29,  4.93it/s]

Reports:   6%|▋         | 461/7111 [01:32<21:44,  5.10it/s]

Reports:   6%|▋         | 462/7111 [01:32<21:39,  5.12it/s]

Reports:   7%|▋         | 463/7111 [01:32<21:30,  5.15it/s]

Reports:   7%|▋         | 464/7111 [01:33<21:19,  5.19it/s]

Reports:   7%|▋         | 465/7111 [01:33<21:04,  5.26it/s]

Reports:   7%|▋         | 466/7111 [01:33<20:55,  5.29it/s]

Reports:   7%|▋         | 467/7111 [01:33<20:54,  5.30it/s]

Reports:   7%|▋         | 468/7111 [01:33<21:29,  5.15it/s]

Reports:   7%|▋         | 469/7111 [01:34<21:58,  5.04it/s]

Reports:   7%|▋         | 470/7111 [01:34<21:44,  5.09it/s]

Reports:   7%|▋         | 471/7111 [01:34<22:01,  5.03it/s]

Reports:   7%|▋         | 472/7111 [01:34<21:35,  5.12it/s]

Reports:   7%|▋         | 473/7111 [01:34<21:34,  5.13it/s]

Reports:   7%|▋         | 474/7111 [01:35<22:01,  5.02it/s]

Reports:   7%|▋         | 475/7111 [01:35<22:30,  4.92it/s]

Reports:   7%|▋         | 476/7111 [01:35<22:27,  4.92it/s]

Reports:   7%|▋         | 477/7111 [01:35<22:11,  4.98it/s]

Reports:   7%|▋         | 478/7111 [01:35<21:47,  5.07it/s]

Reports:   7%|▋         | 479/7111 [01:36<22:13,  4.97it/s]

Reports:   7%|▋         | 480/7111 [01:36<21:59,  5.03it/s]

Reports:   7%|▋         | 481/7111 [01:36<22:15,  4.97it/s]

Reports:   7%|▋         | 482/7111 [01:36<22:08,  4.99it/s]

Reports:   7%|▋         | 483/7111 [01:36<22:04,  5.00it/s]

Reports:   7%|▋         | 484/7111 [01:37<21:33,  5.12it/s]

Reports:   7%|▋         | 485/7111 [01:37<21:55,  5.04it/s]

Reports:   7%|▋         | 486/7111 [01:37<22:12,  4.97it/s]

Reports:   7%|▋         | 487/7111 [01:37<22:02,  5.01it/s]

Reports:   7%|▋         | 488/7111 [01:37<22:05,  5.00it/s]

Reports:   7%|▋         | 489/7111 [01:38<21:38,  5.10it/s]

Reports:   7%|▋         | 490/7111 [01:38<21:44,  5.08it/s]

Reports:   7%|▋         | 491/7111 [01:38<21:04,  5.24it/s]

Reports:   7%|▋         | 492/7111 [01:38<21:32,  5.12it/s]

Reports:   7%|▋         | 493/7111 [01:38<21:15,  5.19it/s]

Reports:   7%|▋         | 494/7111 [01:39<21:08,  5.22it/s]

Reports:   7%|▋         | 495/7111 [01:39<21:21,  5.16it/s]

Reports:   7%|▋         | 496/7111 [01:39<21:14,  5.19it/s]

Reports:   7%|▋         | 497/7111 [01:39<21:01,  5.24it/s]

Reports:   7%|▋         | 498/7111 [01:39<20:47,  5.30it/s]

Reports:   7%|▋         | 499/7111 [01:40<45:15,  2.43it/s]

Reports:   7%|▋         | 500/7111 [01:40<37:58,  2.90it/s]

Reports:   7%|▋         | 501/7111 [01:41<33:35,  3.28it/s]

Reports:   7%|▋         | 502/7111 [01:41<29:51,  3.69it/s]

Reports:   7%|▋         | 503/7111 [01:41<27:44,  3.97it/s]

Reports:   7%|▋         | 504/7111 [01:41<25:47,  4.27it/s]

Reports:   7%|▋         | 505/7111 [01:41<24:27,  4.50it/s]

Reports:   7%|▋         | 506/7111 [01:42<23:56,  4.60it/s]

Reports:   7%|▋         | 507/7111 [01:42<23:14,  4.73it/s]

Reports:   7%|▋         | 508/7111 [01:42<23:06,  4.76it/s]

Reports:   7%|▋         | 509/7111 [01:42<22:50,  4.82it/s]

Reports:   7%|▋         | 510/7111 [01:42<22:11,  4.96it/s]

Reports:   7%|▋         | 511/7111 [01:43<21:47,  5.05it/s]

Reports:   7%|▋         | 512/7111 [01:43<21:41,  5.07it/s]

Reports:   7%|▋         | 513/7111 [01:43<21:42,  5.06it/s]

Reports:   7%|▋         | 514/7111 [01:43<21:34,  5.09it/s]

Reports:   7%|▋         | 515/7111 [01:43<22:01,  4.99it/s]

Reports:   7%|▋         | 516/7111 [01:44<21:30,  5.11it/s]

Reports:   7%|▋         | 517/7111 [01:44<21:47,  5.04it/s]

Reports:   7%|▋         | 518/7111 [01:45<47:19,  2.32it/s]

Reports:   7%|▋         | 519/7111 [01:45<39:20,  2.79it/s]

Reports:   7%|▋         | 520/7111 [01:45<33:47,  3.25it/s]

Reports:   7%|▋         | 521/7111 [01:45<30:15,  3.63it/s]

Reports:   7%|▋         | 522/7111 [01:46<28:15,  3.89it/s]

Reports:   7%|▋         | 523/7111 [01:46<26:29,  4.15it/s]

Reports:   7%|▋         | 524/7111 [01:46<24:56,  4.40it/s]

Reports:   7%|▋         | 525/7111 [01:46<25:41,  4.27it/s]

Reports:   7%|▋         | 526/7111 [01:46<24:39,  4.45it/s]

Reports:   7%|▋         | 527/7111 [01:47<23:36,  4.65it/s]

Reports:   7%|▋         | 528/7111 [01:47<23:39,  4.64it/s]

Reports:   7%|▋         | 529/7111 [01:47<23:04,  4.75it/s]

Reports:   7%|▋         | 530/7111 [01:47<22:52,  4.80it/s]

Reports:   7%|▋         | 531/7111 [01:47<21:58,  4.99it/s]

Reports:   7%|▋         | 532/7111 [01:48<21:58,  4.99it/s]

Reports:   7%|▋         | 533/7111 [01:48<21:59,  4.98it/s]

Reports:   8%|▊         | 534/7111 [01:48<22:07,  4.95it/s]

Reports:   8%|▊         | 535/7111 [01:48<22:06,  4.96it/s]

Reports:   8%|▊         | 536/7111 [01:48<21:33,  5.08it/s]

Reports:   8%|▊         | 537/7111 [01:49<21:19,  5.14it/s]

Reports:   8%|▊         | 538/7111 [01:49<21:59,  4.98it/s]

Reports:   8%|▊         | 539/7111 [01:49<21:28,  5.10it/s]

Reports:   8%|▊         | 540/7111 [01:49<21:56,  4.99it/s]

Reports:   8%|▊         | 541/7111 [01:49<21:48,  5.02it/s]

Reports:   8%|▊         | 542/7111 [01:50<21:39,  5.06it/s]

Reports:   8%|▊         | 543/7111 [01:51<51:32,  2.12it/s]

Reports:   8%|▊         | 544/7111 [01:51<42:44,  2.56it/s]

Reports:   8%|▊         | 545/7111 [01:51<36:41,  2.98it/s]

Reports:   8%|▊         | 546/7111 [01:51<32:52,  3.33it/s]

Reports:   8%|▊         | 547/7111 [01:52<29:17,  3.73it/s]

Reports:   8%|▊         | 548/7111 [01:52<27:22,  3.99it/s]

Reports:   8%|▊         | 549/7111 [01:53<58:17,  1.88it/s]

Reports:   8%|▊         | 550/7111 [01:53<49:07,  2.23it/s]

Reports:   8%|▊         | 551/7111 [01:54<46:42,  2.34it/s]

Reports:   8%|▊         | 552/7111 [01:54<38:47,  2.82it/s]

Reports:   8%|▊         | 553/7111 [01:54<33:09,  3.30it/s]

Reports:   8%|▊         | 554/7111 [01:54<29:53,  3.66it/s]

Reports:   8%|▊         | 555/7111 [01:54<27:10,  4.02it/s]

Reports:   8%|▊         | 556/7111 [01:55<25:24,  4.30it/s]

Reports:   8%|▊         | 557/7111 [01:55<24:06,  4.53it/s]

Reports:   8%|▊         | 558/7111 [01:55<23:07,  4.72it/s]

Reports:   8%|▊         | 559/7111 [01:55<22:26,  4.86it/s]

Reports:   8%|▊         | 560/7111 [01:55<21:53,  4.99it/s]

Reports:   8%|▊         | 561/7111 [01:55<21:28,  5.08it/s]

Reports:   8%|▊         | 562/7111 [01:56<21:39,  5.04it/s]

Reports:   8%|▊         | 563/7111 [01:56<22:18,  4.89it/s]

Reports:   8%|▊         | 564/7111 [01:57<57:33,  1.90it/s]

Reports:   8%|▊         | 565/7111 [01:57<46:49,  2.33it/s]

Reports:   8%|▊         | 566/7111 [01:58<38:59,  2.80it/s]

Reports:   8%|▊         | 567/7111 [01:58<33:54,  3.22it/s]

Reports:   8%|▊         | 568/7111 [01:59<1:00:50,  1.79it/s]

Reports:   8%|▊         | 569/7111 [01:59<49:00,  2.23it/s]

Reports:   8%|▊         | 570/7111 [01:59<40:57,  2.66it/s]

Reports:   8%|▊         | 571/7111 [02:00<34:58,  3.12it/s]

Reports:   8%|▊         | 572/7111 [02:00<39:05,  2.79it/s]

Reports:   8%|▊         | 573/7111 [02:00<33:52,  3.22it/s]

Reports:   8%|▊         | 574/7111 [02:00<29:53,  3.64it/s]

Reports:   8%|▊         | 575/7111 [02:01<43:25,  2.51it/s]

Reports:   8%|▊         | 576/7111 [02:01<37:02,  2.94it/s]

Reports:   8%|▊         | 577/7111 [02:01<32:06,  3.39it/s]

Reports:   8%|▊         | 578/7111 [02:02<28:43,  3.79it/s]

Reports:   8%|▊         | 579/7111 [02:02<26:15,  4.15it/s]

Reports:   8%|▊         | 580/7111 [02:02<24:03,  4.53it/s]

Reports:   8%|▊         | 581/7111 [02:02<23:05,  4.71it/s]

Reports:   8%|▊         | 582/7111 [02:02<22:35,  4.82it/s]

Reports:   8%|▊         | 583/7111 [02:03<21:47,  4.99it/s]

Reports:   8%|▊         | 584/7111 [02:03<21:51,  4.98it/s]

Reports:   8%|▊         | 585/7111 [02:03<21:22,  5.09it/s]

Reports:   8%|▊         | 586/7111 [02:03<21:11,  5.13it/s]

Reports:   8%|▊         | 587/7111 [02:03<20:50,  5.22it/s]

Reports:   8%|▊         | 588/7111 [02:04<20:55,  5.20it/s]

Reports:   8%|▊         | 589/7111 [02:04<31:00,  3.50it/s]

Reports:   8%|▊         | 590/7111 [02:04<28:04,  3.87it/s]

Reports:   8%|▊         | 591/7111 [02:04<25:51,  4.20it/s]

Reports:   8%|▊         | 592/7111 [02:05<24:03,  4.52it/s]

Reports:   8%|▊         | 593/7111 [02:05<23:05,  4.70it/s]

Reports:   8%|▊         | 594/7111 [02:05<29:07,  3.73it/s]

Reports:   8%|▊         | 595/7111 [02:05<26:29,  4.10it/s]

Reports:   8%|▊         | 596/7111 [02:06<24:57,  4.35it/s]

Reports:   8%|▊         | 597/7111 [02:06<23:46,  4.57it/s]

Reports:   8%|▊         | 598/7111 [02:06<22:54,  4.74it/s]

Reports:   8%|▊         | 599/7111 [02:06<22:26,  4.84it/s]

Reports:   8%|▊         | 600/7111 [02:07<32:49,  3.31it/s]

Reports:   8%|▊         | 601/7111 [02:07<29:00,  3.74it/s]

Reports:   8%|▊         | 602/7111 [02:07<26:32,  4.09it/s]

Reports:   8%|▊         | 603/7111 [02:07<24:58,  4.34it/s]

Reports:   8%|▊         | 604/7111 [02:07<23:51,  4.55it/s]

Reports:   9%|▊         | 605/7111 [02:08<23:59,  4.52it/s]

Reports:   9%|▊         | 606/7111 [02:08<22:58,  4.72it/s]

Reports:   9%|▊         | 607/7111 [02:08<22:31,  4.81it/s]

Reports:   9%|▊         | 608/7111 [02:08<22:13,  4.88it/s]

Reports:   9%|▊         | 609/7111 [02:08<21:42,  4.99it/s]

Reports:   9%|▊         | 610/7111 [02:09<21:30,  5.04it/s]

Reports:   9%|▊         | 611/7111 [02:09<21:48,  4.97it/s]

Reports:   9%|▊         | 612/7111 [02:09<21:17,  5.09it/s]

Reports:   9%|▊         | 613/7111 [02:09<21:06,  5.13it/s]

Reports:   9%|▊         | 614/7111 [02:09<21:47,  4.97it/s]

Reports:   9%|▊         | 615/7111 [02:10<21:36,  5.01it/s]

Reports:   9%|▊         | 616/7111 [02:10<21:50,  4.96it/s]

Reports:   9%|▊         | 617/7111 [02:10<21:32,  5.02it/s]

Reports:   9%|▊         | 618/7111 [02:10<21:17,  5.08it/s]

Reports:   9%|▊         | 619/7111 [02:10<20:59,  5.16it/s]

Reports:   9%|▊         | 620/7111 [02:11<20:56,  5.17it/s]

Reports:   9%|▊         | 621/7111 [02:11<21:42,  4.98it/s]

Reports:   9%|▊         | 622/7111 [02:11<21:09,  5.11it/s]

Reports:   9%|▉         | 623/7111 [02:11<24:43,  4.37it/s]

Reports:   9%|▉         | 624/7111 [02:12<23:39,  4.57it/s]

Reports:   9%|▉         | 625/7111 [02:12<22:49,  4.74it/s]

Reports:   9%|▉         | 626/7111 [02:12<22:08,  4.88it/s]

Reports:   9%|▉         | 627/7111 [02:12<21:29,  5.03it/s]

Reports:   9%|▉         | 628/7111 [02:12<21:12,  5.10it/s]

Reports:   9%|▉         | 629/7111 [02:12<20:56,  5.16it/s]

Reports:   9%|▉         | 630/7111 [02:13<21:06,  5.12it/s]

Reports:   9%|▉         | 631/7111 [02:13<21:14,  5.08it/s]

Reports:   9%|▉         | 632/7111 [02:13<21:02,  5.13it/s]

Reports:   9%|▉         | 633/7111 [02:13<20:35,  5.24it/s]

Reports:   9%|▉         | 634/7111 [02:13<20:54,  5.16it/s]

Reports:   9%|▉         | 635/7111 [02:14<20:55,  5.16it/s]

Reports:   9%|▉         | 636/7111 [02:14<20:47,  5.19it/s]

Reports:   9%|▉         | 637/7111 [02:14<20:46,  5.19it/s]

Reports:   9%|▉         | 638/7111 [02:14<21:00,  5.13it/s]

Reports:   9%|▉         | 639/7111 [02:14<20:53,  5.16it/s]

Reports:   9%|▉         | 640/7111 [02:15<21:08,  5.10it/s]

Reports:   9%|▉         | 641/7111 [02:15<21:05,  5.11it/s]

Reports:   9%|▉         | 642/7111 [02:15<21:25,  5.03it/s]

Reports:   9%|▉         | 643/7111 [02:15<21:48,  4.94it/s]

Reports:   9%|▉         | 644/7111 [02:15<21:21,  5.05it/s]

Reports:   9%|▉         | 645/7111 [02:16<21:08,  5.10it/s]

Reports:   9%|▉         | 646/7111 [02:16<21:01,  5.12it/s]

Reports:   9%|▉         | 647/7111 [02:16<20:46,  5.18it/s]

Reports:   9%|▉         | 648/7111 [02:16<21:05,  5.11it/s]

Reports:   9%|▉         | 649/7111 [02:16<20:49,  5.17it/s]

Reports:   9%|▉         | 650/7111 [02:17<30:35,  3.52it/s]

Reports:   9%|▉         | 651/7111 [02:17<27:30,  3.91it/s]

Reports:   9%|▉         | 652/7111 [02:17<25:38,  4.20it/s]

Reports:   9%|▉         | 653/7111 [02:17<24:30,  4.39it/s]

Reports:   9%|▉         | 654/7111 [02:18<23:26,  4.59it/s]

Reports:   9%|▉         | 655/7111 [02:18<22:19,  4.82it/s]

Reports:   9%|▉         | 656/7111 [02:18<21:55,  4.91it/s]

Reports:   9%|▉         | 657/7111 [02:18<21:38,  4.97it/s]

Reports:   9%|▉         | 658/7111 [02:18<21:25,  5.02it/s]

Reports:   9%|▉         | 659/7111 [02:19<21:04,  5.10it/s]

Reports:   9%|▉         | 660/7111 [02:19<20:44,  5.18it/s]

Reports:   9%|▉         | 661/7111 [02:19<20:43,  5.19it/s]

Reports:   9%|▉         | 662/7111 [02:19<20:56,  5.13it/s]

Reports:   9%|▉         | 663/7111 [02:19<20:44,  5.18it/s]

Reports:   9%|▉         | 664/7111 [02:20<20:37,  5.21it/s]

Reports:   9%|▉         | 665/7111 [02:20<21:32,  4.99it/s]

Reports:   9%|▉         | 666/7111 [02:20<21:23,  5.02it/s]

Reports:   9%|▉         | 667/7111 [02:20<21:00,  5.11it/s]

Reports:   9%|▉         | 668/7111 [02:20<21:00,  5.11it/s]

Reports:   9%|▉         | 669/7111 [02:21<20:40,  5.19it/s]

Reports:   9%|▉         | 670/7111 [02:21<20:52,  5.14it/s]

Reports:   9%|▉         | 671/7111 [02:21<20:43,  5.18it/s]

Reports:   9%|▉         | 672/7111 [02:21<20:49,  5.15it/s]

Reports:   9%|▉         | 673/7111 [02:21<21:27,  5.00it/s]

Reports:   9%|▉         | 674/7111 [02:22<21:47,  4.92it/s]

Reports:   9%|▉         | 675/7111 [02:22<21:13,  5.05it/s]

Reports:  10%|▉         | 676/7111 [02:22<21:41,  4.94it/s]

Reports:  10%|▉         | 677/7111 [02:22<21:11,  5.06it/s]

Reports:  10%|▉         | 678/7111 [02:22<21:12,  5.05it/s]

Reports:  10%|▉         | 679/7111 [02:23<20:56,  5.12it/s]

Reports:  10%|▉         | 680/7111 [02:23<21:15,  5.04it/s]

Reports:  10%|▉         | 681/7111 [02:23<21:19,  5.03it/s]

Reports:  10%|▉         | 682/7111 [02:23<21:16,  5.04it/s]

Reports:  10%|▉         | 683/7111 [02:23<20:56,  5.12it/s]

Reports:  10%|▉         | 684/7111 [02:23<20:42,  5.17it/s]

Reports:  10%|▉         | 685/7111 [02:24<21:08,  5.07it/s]

Reports:  10%|▉         | 686/7111 [02:24<20:46,  5.16it/s]

Reports:  10%|▉         | 687/7111 [02:24<20:29,  5.23it/s]

Reports:  10%|▉         | 688/7111 [02:24<20:43,  5.17it/s]

Reports:  10%|▉         | 689/7111 [02:24<20:28,  5.23it/s]

Reports:  10%|▉         | 690/7111 [02:25<20:54,  5.12it/s]

Reports:  10%|▉         | 691/7111 [02:25<21:10,  5.05it/s]

Reports:  10%|▉         | 692/7111 [02:25<20:41,  5.17it/s]

Reports:  10%|▉         | 693/7111 [02:25<20:42,  5.16it/s]

Reports:  10%|▉         | 694/7111 [02:25<20:52,  5.12it/s]

Reports:  10%|▉         | 695/7111 [02:26<21:06,  5.07it/s]

Reports:  10%|▉         | 696/7111 [02:26<20:51,  5.13it/s]

Reports:  10%|▉         | 697/7111 [02:26<20:51,  5.12it/s]

Reports:  10%|▉         | 698/7111 [02:26<20:34,  5.19it/s]

Reports:  10%|▉         | 699/7111 [02:26<20:44,  5.15it/s]

Reports:  10%|▉         | 700/7111 [02:27<20:36,  5.18it/s]

Reports:  10%|▉         | 701/7111 [02:27<20:34,  5.19it/s]

Reports:  10%|▉         | 702/7111 [02:27<20:16,  5.27it/s]

Reports:  10%|▉         | 703/7111 [02:27<20:10,  5.29it/s]

Reports:  10%|▉         | 704/7111 [02:27<20:07,  5.30it/s]

Reports:  10%|▉         | 705/7111 [02:28<20:28,  5.21it/s]

Reports:  10%|▉         | 706/7111 [02:28<20:18,  5.26it/s]

Reports:  10%|▉         | 707/7111 [02:28<20:18,  5.25it/s]

Reports:  10%|▉         | 708/7111 [02:28<20:28,  5.21it/s]

Reports:  10%|▉         | 709/7111 [02:28<20:22,  5.24it/s]

Reports:  10%|▉         | 710/7111 [02:29<20:43,  5.15it/s]

Reports:  10%|▉         | 711/7111 [02:29<20:33,  5.19it/s]

Reports:  10%|█         | 712/7111 [02:29<20:22,  5.24it/s]

Reports:  10%|█         | 713/7111 [02:29<20:50,  5.12it/s]

Reports:  10%|█         | 714/7111 [02:29<21:12,  5.03it/s]

Reports:  10%|█         | 715/7111 [02:30<21:17,  5.01it/s]

Reports:  10%|█         | 716/7111 [02:30<20:59,  5.08it/s]

Reports:  10%|█         | 717/7111 [02:30<20:33,  5.18it/s]

Reports:  10%|█         | 718/7111 [02:30<20:14,  5.26it/s]

Reports:  10%|█         | 719/7111 [02:30<20:44,  5.14it/s]

Reports:  10%|█         | 720/7111 [02:30<20:44,  5.14it/s]

Reports:  10%|█         | 721/7111 [02:31<20:38,  5.16it/s]

Reports:  10%|█         | 722/7111 [02:31<20:45,  5.13it/s]

Reports:  10%|█         | 723/7111 [02:31<20:28,  5.20it/s]

Reports:  10%|█         | 724/7111 [02:31<20:47,  5.12it/s]

Reports:  10%|█         | 725/7111 [02:31<20:37,  5.16it/s]

Reports:  10%|█         | 726/7111 [02:32<20:46,  5.12it/s]

Reports:  10%|█         | 727/7111 [02:32<20:30,  5.19it/s]

Reports:  10%|█         | 728/7111 [02:32<20:39,  5.15it/s]

Reports:  10%|█         | 729/7111 [02:32<21:33,  4.93it/s]

Reports:  10%|█         | 730/7111 [02:32<21:15,  5.00it/s]

Reports:  10%|█         | 731/7111 [02:33<21:09,  5.02it/s]

Reports:  10%|█         | 732/7111 [02:33<20:53,  5.09it/s]

Reports:  10%|█         | 733/7111 [02:33<20:33,  5.17it/s]

Reports:  10%|█         | 734/7111 [02:33<20:21,  5.22it/s]

Reports:  10%|█         | 735/7111 [02:33<20:43,  5.13it/s]

Reports:  10%|█         | 736/7111 [02:34<21:34,  4.93it/s]

Reports:  10%|█         | 737/7111 [02:34<21:13,  5.01it/s]

Reports:  10%|█         | 738/7111 [02:34<20:52,  5.09it/s]

Reports:  10%|█         | 739/7111 [02:34<20:45,  5.11it/s]

Reports:  10%|█         | 740/7111 [02:34<20:35,  5.16it/s]

Reports:  10%|█         | 741/7111 [02:35<20:21,  5.21it/s]

Reports:  10%|█         | 742/7111 [02:35<20:38,  5.14it/s]

Reports:  10%|█         | 743/7111 [02:35<20:42,  5.12it/s]

Reports:  10%|█         | 744/7111 [02:35<20:32,  5.17it/s]

Reports:  10%|█         | 745/7111 [02:35<20:28,  5.18it/s]

Reports:  10%|█         | 746/7111 [02:36<20:30,  5.17it/s]

Reports:  11%|█         | 747/7111 [02:36<20:16,  5.23it/s]

Reports:  11%|█         | 748/7111 [02:36<20:27,  5.19it/s]

Reports:  11%|█         | 749/7111 [02:36<20:30,  5.17it/s]

Reports:  11%|█         | 750/7111 [02:36<20:22,  5.20it/s]

Reports:  11%|█         | 751/7111 [02:36<20:14,  5.24it/s]

Reports:  11%|█         | 752/7111 [02:37<20:23,  5.20it/s]

Reports:  11%|█         | 753/7111 [02:37<20:19,  5.21it/s]

Reports:  11%|█         | 754/7111 [02:37<20:13,  5.24it/s]

Reports:  11%|█         | 755/7111 [02:37<20:32,  5.16it/s]

Reports:  11%|█         | 756/7111 [02:37<20:36,  5.14it/s]

Reports:  11%|█         | 757/7111 [02:38<20:44,  5.11it/s]

Reports:  11%|█         | 758/7111 [02:38<20:29,  5.17it/s]

Reports:  11%|█         | 759/7111 [02:38<21:08,  5.01it/s]

Reports:  11%|█         | 760/7111 [02:38<20:44,  5.10it/s]

Reports:  11%|█         | 761/7111 [02:38<20:41,  5.11it/s]

Reports:  11%|█         | 762/7111 [02:39<20:18,  5.21it/s]

Reports:  11%|█         | 763/7111 [02:39<20:12,  5.24it/s]

Reports:  11%|█         | 764/7111 [02:39<19:52,  5.32it/s]

Reports:  11%|█         | 765/7111 [02:39<20:13,  5.23it/s]

Reports:  11%|█         | 766/7111 [02:39<20:34,  5.14it/s]

Reports:  11%|█         | 767/7111 [02:40<20:44,  5.10it/s]

Reports:  11%|█         | 768/7111 [02:40<20:50,  5.07it/s]

Reports:  11%|█         | 769/7111 [02:40<20:52,  5.06it/s]

Reports:  11%|█         | 770/7111 [02:40<20:31,  5.15it/s]

Reports:  11%|█         | 771/7111 [02:40<20:30,  5.15it/s]

Reports:  11%|█         | 772/7111 [02:41<20:24,  5.18it/s]

Reports:  11%|█         | 773/7111 [02:41<20:28,  5.16it/s]

Reports:  11%|█         | 774/7111 [02:41<20:44,  5.09it/s]

Reports:  11%|█         | 775/7111 [02:41<20:49,  5.07it/s]

Reports:  11%|█         | 776/7111 [02:41<20:51,  5.06it/s]

Reports:  11%|█         | 777/7111 [02:42<20:57,  5.04it/s]

Reports:  11%|█         | 778/7111 [02:42<21:04,  5.01it/s]

Reports:  11%|█         | 779/7111 [02:42<20:45,  5.08it/s]

Reports:  11%|█         | 780/7111 [02:42<20:45,  5.08it/s]

Reports:  11%|█         | 781/7111 [02:42<20:41,  5.10it/s]

Reports:  11%|█         | 782/7111 [02:43<20:58,  5.03it/s]

Reports:  11%|█         | 783/7111 [02:43<20:47,  5.07it/s]

Reports:  11%|█         | 784/7111 [02:43<20:25,  5.16it/s]

Reports:  11%|█         | 785/7111 [02:43<20:26,  5.16it/s]

Reports:  11%|█         | 786/7111 [02:43<20:08,  5.23it/s]

Reports:  11%|█         | 787/7111 [02:44<20:09,  5.23it/s]

Reports:  11%|█         | 788/7111 [02:44<20:10,  5.22it/s]

Reports:  11%|█         | 789/7111 [02:44<20:34,  5.12it/s]

Reports:  11%|█         | 790/7111 [02:44<20:47,  5.07it/s]

Reports:  11%|█         | 791/7111 [02:44<20:57,  5.03it/s]

Reports:  11%|█         | 792/7111 [02:44<20:32,  5.13it/s]

Reports:  11%|█         | 793/7111 [02:45<20:16,  5.19it/s]

Reports:  11%|█         | 794/7111 [02:45<22:16,  4.73it/s]

Reports:  11%|█         | 795/7111 [02:45<21:33,  4.88it/s]

Reports:  11%|█         | 796/7111 [02:45<20:59,  5.01it/s]

Reports:  11%|█         | 797/7111 [02:46<21:05,  4.99it/s]

Reports:  11%|█         | 798/7111 [02:46<20:42,  5.08it/s]

Reports:  11%|█         | 799/7111 [02:46<20:33,  5.12it/s]

Reports:  11%|█▏        | 800/7111 [02:47<43:15,  2.43it/s]

Reports:  11%|█▏        | 801/7111 [02:47<36:43,  2.86it/s]

Reports:  11%|█▏        | 802/7111 [02:47<32:02,  3.28it/s]

Reports:  11%|█▏        | 803/7111 [02:47<28:18,  3.71it/s]

Reports:  11%|█▏        | 804/7111 [02:48<25:38,  4.10it/s]

Reports:  11%|█▏        | 805/7111 [02:48<24:17,  4.33it/s]

Reports:  11%|█▏        | 806/7111 [02:48<22:54,  4.59it/s]

Reports:  11%|█▏        | 807/7111 [02:48<21:48,  4.82it/s]

Reports:  11%|█▏        | 808/7111 [02:48<21:41,  4.84it/s]

Reports:  11%|█▏        | 809/7111 [02:49<21:07,  4.97it/s]

Reports:  11%|█▏        | 810/7111 [02:49<20:47,  5.05it/s]

Reports:  11%|█▏        | 811/7111 [02:49<20:16,  5.18it/s]

Reports:  11%|█▏        | 812/7111 [02:49<20:44,  5.06it/s]

Reports:  11%|█▏        | 813/7111 [02:49<20:56,  5.01it/s]

Reports:  11%|█▏        | 814/7111 [02:50<20:42,  5.07it/s]

Reports:  11%|█▏        | 815/7111 [02:50<20:21,  5.15it/s]

Reports:  11%|█▏        | 816/7111 [02:50<20:20,  5.16it/s]

Reports:  11%|█▏        | 817/7111 [02:50<20:46,  5.05it/s]

Reports:  12%|█▏        | 818/7111 [02:50<21:19,  4.92it/s]

Reports:  12%|█▏        | 819/7111 [02:51<20:50,  5.03it/s]

Reports:  12%|█▏        | 820/7111 [02:51<20:32,  5.10it/s]

Reports:  12%|█▏        | 821/7111 [02:51<21:00,  4.99it/s]

Reports:  12%|█▏        | 822/7111 [02:51<20:57,  5.00it/s]

Reports:  12%|█▏        | 823/7111 [02:51<20:29,  5.11it/s]

Reports:  12%|█▏        | 824/7111 [02:52<20:30,  5.11it/s]

Reports:  12%|█▏        | 825/7111 [02:52<20:07,  5.20it/s]

Reports:  12%|█▏        | 826/7111 [02:52<20:09,  5.20it/s]

Reports:  12%|█▏        | 827/7111 [02:52<19:54,  5.26it/s]

Reports:  12%|█▏        | 828/7111 [02:52<19:46,  5.30it/s]

Reports:  12%|█▏        | 829/7111 [02:52<19:45,  5.30it/s]

Reports:  12%|█▏        | 830/7111 [02:53<19:49,  5.28it/s]

Reports:  12%|█▏        | 831/7111 [02:53<19:36,  5.34it/s]

Reports:  12%|█▏        | 832/7111 [02:53<19:42,  5.31it/s]

Reports:  12%|█▏        | 833/7111 [02:53<19:49,  5.28it/s]

Reports:  12%|█▏        | 834/7111 [02:53<19:45,  5.29it/s]

Reports:  12%|█▏        | 835/7111 [02:54<19:41,  5.31it/s]

Reports:  12%|█▏        | 836/7111 [02:54<19:51,  5.27it/s]

Reports:  12%|█▏        | 837/7111 [02:54<20:15,  5.16it/s]

Reports:  12%|█▏        | 838/7111 [02:54<20:02,  5.22it/s]

Reports:  12%|█▏        | 839/7111 [02:54<19:56,  5.24it/s]

Reports:  12%|█▏        | 840/7111 [02:55<20:20,  5.14it/s]

Reports:  12%|█▏        | 841/7111 [02:55<20:15,  5.16it/s]

Reports:  12%|█▏        | 842/7111 [02:55<20:02,  5.21it/s]

Reports:  12%|█▏        | 843/7111 [02:55<20:14,  5.16it/s]

Reports:  12%|█▏        | 844/7111 [02:55<20:03,  5.21it/s]

Reports:  12%|█▏        | 845/7111 [02:56<20:37,  5.06it/s]

Reports:  12%|█▏        | 846/7111 [02:56<20:25,  5.11it/s]

Reports:  12%|█▏        | 847/7111 [02:56<20:17,  5.14it/s]

Reports:  12%|█▏        | 848/7111 [02:56<20:32,  5.08it/s]

Reports:  12%|█▏        | 849/7111 [02:56<20:14,  5.16it/s]

Reports:  12%|█▏        | 850/7111 [02:56<19:59,  5.22it/s]

Reports:  12%|█▏        | 851/7111 [02:57<19:52,  5.25it/s]

Reports:  12%|█▏        | 852/7111 [02:57<19:58,  5.22it/s]

Reports:  12%|█▏        | 853/7111 [02:57<19:52,  5.25it/s]

Reports:  12%|█▏        | 854/7111 [02:57<20:11,  5.16it/s]

Reports:  12%|█▏        | 855/7111 [02:57<20:48,  5.01it/s]

Reports:  12%|█▏        | 856/7111 [02:58<20:45,  5.02it/s]

Reports:  12%|█▏        | 857/7111 [02:58<20:38,  5.05it/s]

Reports:  12%|█▏        | 858/7111 [02:58<20:59,  4.96it/s]

Reports:  12%|█▏        | 859/7111 [02:58<21:12,  4.91it/s]

Reports:  12%|█▏        | 860/7111 [02:58<21:17,  4.89it/s]

Reports:  12%|█▏        | 861/7111 [02:59<20:47,  5.01it/s]

Reports:  12%|█▏        | 862/7111 [02:59<20:29,  5.08it/s]

Reports:  12%|█▏        | 863/7111 [02:59<20:33,  5.06it/s]

Reports:  12%|█▏        | 864/7111 [02:59<20:20,  5.12it/s]

Reports:  12%|█▏        | 865/7111 [02:59<20:38,  5.04it/s]

Reports:  12%|█▏        | 866/7111 [03:00<20:33,  5.06it/s]

Reports:  12%|█▏        | 867/7111 [03:00<20:17,  5.13it/s]

Reports:  12%|█▏        | 868/7111 [03:00<20:06,  5.17it/s]

Reports:  12%|█▏        | 869/7111 [03:00<20:05,  5.18it/s]

Reports:  12%|█▏        | 870/7111 [03:00<20:22,  5.10it/s]

Reports:  12%|█▏        | 871/7111 [03:01<20:35,  5.05it/s]

Reports:  12%|█▏        | 872/7111 [03:01<20:41,  5.03it/s]

Reports:  12%|█▏        | 873/7111 [03:01<20:43,  5.02it/s]

Reports:  12%|█▏        | 874/7111 [03:01<20:19,  5.11it/s]

Reports:  12%|█▏        | 875/7111 [03:01<20:13,  5.14it/s]

Reports:  12%|█▏        | 876/7111 [03:02<20:17,  5.12it/s]

Reports:  12%|█▏        | 877/7111 [03:02<20:53,  4.97it/s]

Reports:  12%|█▏        | 878/7111 [03:02<20:23,  5.09it/s]

Reports:  12%|█▏        | 879/7111 [03:02<20:10,  5.15it/s]

Reports:  12%|█▏        | 880/7111 [03:02<19:37,  5.29it/s]

Reports:  12%|█▏        | 881/7111 [03:04<1:16:40,  1.35it/s]

Reports:  12%|█▏        | 882/7111 [03:05<1:00:00,  1.73it/s]

Reports:  12%|█▏        | 883/7111 [03:05<47:51,  2.17it/s]

Reports:  12%|█▏        | 884/7111 [03:05<39:46,  2.61it/s]

Reports:  12%|█▏        | 885/7111 [03:05<34:17,  3.03it/s]

Reports:  12%|█▏        | 886/7111 [03:05<30:27,  3.41it/s]

Reports:  12%|█▏        | 887/7111 [03:06<27:04,  3.83it/s]

Reports:  12%|█▏        | 888/7111 [03:06<24:43,  4.20it/s]

Reports:  13%|█▎        | 889/7111 [03:06<23:33,  4.40it/s]

Reports:  13%|█▎        | 890/7111 [03:06<22:27,  4.62it/s]

Reports:  13%|█▎        | 891/7111 [03:06<21:33,  4.81it/s]

Reports:  13%|█▎        | 892/7111 [03:07<20:51,  4.97it/s]

Reports:  13%|█▎        | 893/7111 [03:07<20:26,  5.07it/s]

Reports:  13%|█▎        | 894/7111 [03:07<20:16,  5.11it/s]

Reports:  13%|█▎        | 895/7111 [03:07<20:35,  5.03it/s]

Reports:  13%|█▎        | 896/7111 [03:07<20:10,  5.14it/s]

Reports:  13%|█▎        | 897/7111 [03:07<19:53,  5.21it/s]

Reports:  13%|█▎        | 898/7111 [03:08<20:26,  5.07it/s]

Reports:  13%|█▎        | 899/7111 [03:08<20:03,  5.16it/s]

Reports:  13%|█▎        | 900/7111 [03:08<19:46,  5.24it/s]

Reports:  13%|█▎        | 901/7111 [03:08<20:08,  5.14it/s]

Reports:  13%|█▎        | 902/7111 [03:08<20:01,  5.17it/s]

Reports:  13%|█▎        | 903/7111 [03:09<21:55,  4.72it/s]

Reports:  13%|█▎        | 904/7111 [03:09<21:07,  4.90it/s]

Reports:  13%|█▎        | 905/7111 [03:09<21:41,  4.77it/s]

Reports:  13%|█▎        | 906/7111 [03:09<21:30,  4.81it/s]

Reports:  13%|█▎        | 907/7111 [03:10<21:00,  4.92it/s]

Reports:  13%|█▎        | 908/7111 [03:10<20:51,  4.96it/s]

Reports:  13%|█▎        | 909/7111 [03:10<20:28,  5.05it/s]

Reports:  13%|█▎        | 910/7111 [03:10<20:28,  5.05it/s]

Reports:  13%|█▎        | 911/7111 [03:10<20:07,  5.13it/s]

Reports:  13%|█▎        | 912/7111 [03:10<19:59,  5.17it/s]

Reports:  13%|█▎        | 913/7111 [03:11<19:49,  5.21it/s]

Reports:  13%|█▎        | 914/7111 [03:11<19:44,  5.23it/s]

Reports:  13%|█▎        | 915/7111 [03:11<19:35,  5.27it/s]

Reports:  13%|█▎        | 916/7111 [03:11<19:54,  5.19it/s]

Reports:  13%|█▎        | 917/7111 [03:11<19:57,  5.17it/s]

Reports:  13%|█▎        | 918/7111 [03:12<19:56,  5.18it/s]

Reports:  13%|█▎        | 919/7111 [03:12<19:58,  5.17it/s]

Reports:  13%|█▎        | 920/7111 [03:12<19:42,  5.24it/s]

Reports:  13%|█▎        | 921/7111 [03:12<19:51,  5.19it/s]

Reports:  13%|█▎        | 922/7111 [03:12<19:59,  5.16it/s]

Reports:  13%|█▎        | 923/7111 [03:13<20:09,  5.12it/s]

Reports:  13%|█▎        | 924/7111 [03:13<22:14,  4.64it/s]

Reports:  13%|█▎        | 925/7111 [03:13<23:55,  4.31it/s]

Reports:  13%|█▎        | 926/7111 [03:13<24:44,  4.17it/s]

Reports:  13%|█▎        | 927/7111 [03:14<23:27,  4.39it/s]

Reports:  13%|█▎        | 928/7111 [03:14<22:38,  4.55it/s]

Reports:  13%|█▎        | 929/7111 [03:14<21:40,  4.75it/s]

Reports:  13%|█▎        | 930/7111 [03:14<21:09,  4.87it/s]

Reports:  13%|█▎        | 931/7111 [03:14<20:44,  4.97it/s]

Reports:  13%|█▎        | 932/7111 [03:15<20:18,  5.07it/s]

Reports:  13%|█▎        | 933/7111 [03:15<20:32,  5.01it/s]

Reports:  13%|█▎        | 934/7111 [03:15<20:29,  5.02it/s]

Reports:  13%|█▎        | 935/7111 [03:15<20:07,  5.11it/s]

Reports:  13%|█▎        | 936/7111 [03:15<20:11,  5.10it/s]

Reports:  13%|█▎        | 937/7111 [03:16<20:33,  5.01it/s]

Reports:  13%|█▎        | 938/7111 [03:16<20:16,  5.07it/s]

Reports:  13%|█▎        | 939/7111 [03:16<20:16,  5.07it/s]

Reports:  13%|█▎        | 940/7111 [03:16<20:00,  5.14it/s]

Reports:  13%|█▎        | 941/7111 [03:16<19:48,  5.19it/s]

Reports:  13%|█▎        | 942/7111 [03:17<19:40,  5.23it/s]

Reports:  13%|█▎        | 943/7111 [03:17<19:42,  5.22it/s]

Reports:  13%|█▎        | 944/7111 [03:17<19:54,  5.16it/s]

Reports:  13%|█▎        | 945/7111 [03:17<19:58,  5.14it/s]

Reports:  13%|█▎        | 946/7111 [03:17<20:51,  4.93it/s]

Reports:  13%|█▎        | 947/7111 [03:18<20:57,  4.90it/s]

Reports:  13%|█▎        | 948/7111 [03:18<20:24,  5.03it/s]

Reports:  13%|█▎        | 949/7111 [03:18<19:56,  5.15it/s]

Reports:  13%|█▎        | 950/7111 [03:18<19:36,  5.24it/s]

Reports:  13%|█▎        | 951/7111 [03:18<19:47,  5.19it/s]

Reports:  13%|█▎        | 952/7111 [03:18<19:54,  5.15it/s]

Reports:  13%|█▎        | 953/7111 [03:19<19:48,  5.18it/s]

Reports:  13%|█▎        | 954/7111 [03:19<19:45,  5.19it/s]

Reports:  13%|█▎        | 955/7111 [03:19<19:32,  5.25it/s]

Reports:  13%|█▎        | 956/7111 [03:19<19:37,  5.23it/s]

Reports:  13%|█▎        | 957/7111 [03:19<19:34,  5.24it/s]

Reports:  13%|█▎        | 958/7111 [03:20<19:46,  5.19it/s]

Reports:  13%|█▎        | 959/7111 [03:20<19:44,  5.19it/s]

Reports:  14%|█▎        | 960/7111 [03:20<19:31,  5.25it/s]

Reports:  14%|█▎        | 961/7111 [03:20<19:51,  5.16it/s]

Reports:  14%|█▎        | 962/7111 [03:20<19:46,  5.18it/s]

Reports:  14%|█▎        | 963/7111 [03:21<20:16,  5.05it/s]

Reports:  14%|█▎        | 964/7111 [03:21<19:58,  5.13it/s]

Reports:  14%|█▎        | 965/7111 [03:21<19:56,  5.14it/s]

Reports:  14%|█▎        | 966/7111 [03:21<19:44,  5.19it/s]

Reports:  14%|█▎        | 967/7111 [03:21<19:29,  5.25it/s]

Reports:  14%|█▎        | 968/7111 [03:22<19:52,  5.15it/s]

Reports:  14%|█▎        | 969/7111 [03:22<19:34,  5.23it/s]

Reports:  14%|█▎        | 970/7111 [03:22<19:14,  5.32it/s]

Reports:  14%|█▎        | 971/7111 [03:22<19:43,  5.19it/s]

Reports:  14%|█▎        | 972/7111 [03:22<19:57,  5.12it/s]

Reports:  14%|█▎        | 973/7111 [03:23<20:11,  5.07it/s]

Reports:  14%|█▎        | 974/7111 [03:23<20:05,  5.09it/s]

Reports:  14%|█▎        | 975/7111 [03:23<19:45,  5.18it/s]

Reports:  14%|█▎        | 976/7111 [03:23<19:56,  5.13it/s]

Reports:  14%|█▎        | 977/7111 [03:23<19:52,  5.15it/s]

Reports:  14%|█▍        | 978/7111 [03:23<19:34,  5.22it/s]

Reports:  14%|█▍        | 979/7111 [03:24<19:37,  5.21it/s]

Reports:  14%|█▍        | 980/7111 [03:24<19:40,  5.19it/s]

Reports:  14%|█▍        | 981/7111 [03:24<19:39,  5.20it/s]

Reports:  14%|█▍        | 982/7111 [03:24<19:32,  5.23it/s]

Reports:  14%|█▍        | 983/7111 [03:24<19:28,  5.25it/s]

Reports:  14%|█▍        | 984/7111 [03:25<19:39,  5.19it/s]

Reports:  14%|█▍        | 985/7111 [03:25<19:35,  5.21it/s]

Reports:  14%|█▍        | 986/7111 [03:25<20:09,  5.07it/s]

Reports:  14%|█▍        | 987/7111 [03:25<20:18,  5.03it/s]

Reports:  14%|█▍        | 988/7111 [03:25<20:01,  5.10it/s]

Reports:  14%|█▍        | 989/7111 [03:26<19:51,  5.14it/s]

Reports:  14%|█▍        | 990/7111 [03:26<20:02,  5.09it/s]

Reports:  14%|█▍        | 991/7111 [03:26<19:51,  5.14it/s]

Reports:  14%|█▍        | 992/7111 [03:26<21:07,  4.83it/s]

Reports:  14%|█▍        | 993/7111 [03:26<20:53,  4.88it/s]

Reports:  14%|█▍        | 994/7111 [03:27<20:23,  5.00it/s]

Reports:  14%|█▍        | 995/7111 [03:27<19:57,  5.11it/s]

Reports:  14%|█▍        | 996/7111 [03:27<19:52,  5.13it/s]

Reports:  14%|█▍        | 997/7111 [03:27<19:35,  5.20it/s]

Reports:  14%|█▍        | 998/7111 [03:27<20:07,  5.06it/s]

Reports:  14%|█▍        | 999/7111 [03:28<19:57,  5.10it/s]

Reports:  14%|█▍        | 1000/7111 [03:28<19:52,  5.13it/s]

Reports:  14%|█▍        | 1001/7111 [03:28<19:34,  5.20it/s]

Reports:  14%|█▍        | 1002/7111 [03:28<19:24,  5.25it/s]

Reports:  14%|█▍        | 1003/7111 [03:28<19:37,  5.19it/s]

Reports:  14%|█▍        | 1004/7111 [03:29<21:08,  4.81it/s]

Reports:  14%|█▍        | 1005/7111 [03:29<20:39,  4.93it/s]

Reports:  14%|█▍        | 1006/7111 [03:29<20:35,  4.94it/s]

Reports:  14%|█▍        | 1007/7111 [03:29<20:07,  5.05it/s]

Reports:  14%|█▍        | 1008/7111 [03:29<20:31,  4.96it/s]

Reports:  14%|█▍        | 1009/7111 [03:30<21:03,  4.83it/s]

Reports:  14%|█▍        | 1010/7111 [03:30<20:38,  4.93it/s]

Reports:  14%|█▍        | 1011/7111 [03:30<20:03,  5.07it/s]

Reports:  14%|█▍        | 1012/7111 [03:30<19:57,  5.09it/s]

Reports:  14%|█▍        | 1013/7111 [03:30<19:43,  5.15it/s]

Reports:  14%|█▍        | 1014/7111 [03:31<19:44,  5.15it/s]

Reports:  14%|█▍        | 1015/7111 [03:31<20:01,  5.07it/s]

Reports:  14%|█▍        | 1016/7111 [03:31<19:51,  5.12it/s]

Reports:  14%|█▍        | 1017/7111 [03:31<19:44,  5.14it/s]

Reports:  14%|█▍        | 1018/7111 [03:31<19:39,  5.16it/s]

Reports:  14%|█▍        | 1019/7111 [03:32<19:43,  5.15it/s]

Reports:  14%|█▍        | 1020/7111 [03:32<20:07,  5.04it/s]

Reports:  14%|█▍        | 1021/7111 [03:32<20:01,  5.07it/s]

Reports:  14%|█▍        | 1022/7111 [03:32<19:40,  5.16it/s]

Reports:  14%|█▍        | 1023/7111 [03:32<19:36,  5.17it/s]

Reports:  14%|█▍        | 1024/7111 [03:33<19:35,  5.18it/s]

Reports:  14%|█▍        | 1025/7111 [03:33<19:47,  5.13it/s]

Reports:  14%|█▍        | 1026/7111 [03:33<19:38,  5.16it/s]

Reports:  14%|█▍        | 1027/7111 [03:33<19:43,  5.14it/s]

Reports:  14%|█▍        | 1028/7111 [03:33<20:19,  4.99it/s]

Reports:  14%|█▍        | 1029/7111 [03:34<20:01,  5.06it/s]

Reports:  14%|█▍        | 1030/7111 [03:34<19:58,  5.07it/s]

Reports:  14%|█▍        | 1031/7111 [03:34<19:58,  5.07it/s]

Reports:  15%|█▍        | 1032/7111 [03:34<19:43,  5.14it/s]

Reports:  15%|█▍        | 1033/7111 [03:34<19:42,  5.14it/s]

Reports:  15%|█▍        | 1034/7111 [03:34<19:53,  5.09it/s]

Reports:  15%|█▍        | 1035/7111 [03:35<19:39,  5.15it/s]

Reports:  15%|█▍        | 1036/7111 [03:35<19:27,  5.21it/s]

Reports:  15%|█▍        | 1037/7111 [03:35<19:22,  5.23it/s]

Reports:  15%|█▍        | 1038/7111 [03:35<19:31,  5.18it/s]

Reports:  15%|█▍        | 1039/7111 [03:35<19:52,  5.09it/s]

Reports:  15%|█▍        | 1040/7111 [03:36<19:45,  5.12it/s]

Reports:  15%|█▍        | 1041/7111 [03:36<19:32,  5.18it/s]

Reports:  15%|█▍        | 1042/7111 [03:36<19:17,  5.24it/s]

Reports:  15%|█▍        | 1043/7111 [03:36<19:48,  5.11it/s]

Reports:  15%|█▍        | 1044/7111 [03:36<19:57,  5.07it/s]

Reports:  15%|█▍        | 1045/7111 [03:37<19:47,  5.11it/s]

Reports:  15%|█▍        | 1046/7111 [03:37<20:09,  5.01it/s]

Reports:  15%|█▍        | 1047/7111 [03:37<19:35,  5.16it/s]

Reports:  15%|█▍        | 1048/7111 [03:37<19:29,  5.19it/s]

Reports:  15%|█▍        | 1049/7111 [03:37<19:20,  5.22it/s]

Reports:  15%|█▍        | 1050/7111 [03:38<19:20,  5.22it/s]

Reports:  15%|█▍        | 1051/7111 [03:38<19:18,  5.23it/s]

Reports:  15%|█▍        | 1052/7111 [03:38<19:18,  5.23it/s]

Reports:  15%|█▍        | 1053/7111 [03:38<19:19,  5.22it/s]

Reports:  15%|█▍        | 1054/7111 [03:38<19:28,  5.19it/s]

Reports:  15%|█▍        | 1055/7111 [03:39<19:26,  5.19it/s]

Reports:  15%|█▍        | 1056/7111 [03:39<19:15,  5.24it/s]

Reports:  15%|█▍        | 1057/7111 [03:39<19:25,  5.20it/s]

Reports:  15%|█▍        | 1058/7111 [03:39<19:26,  5.19it/s]

Reports:  15%|█▍        | 1059/7111 [03:39<19:28,  5.18it/s]

Reports:  15%|█▍        | 1060/7111 [03:40<19:28,  5.18it/s]

Reports:  15%|█▍        | 1061/7111 [03:40<19:36,  5.14it/s]

Reports:  15%|█▍        | 1062/7111 [03:40<19:18,  5.22it/s]

Reports:  15%|█▍        | 1063/7111 [03:40<19:39,  5.13it/s]

Reports:  15%|█▍        | 1064/7111 [03:40<19:29,  5.17it/s]

Reports:  15%|█▍        | 1065/7111 [03:40<19:28,  5.18it/s]

Reports:  15%|█▍        | 1066/7111 [03:41<19:26,  5.18it/s]

Reports:  15%|█▌        | 1067/7111 [03:41<19:24,  5.19it/s]

Reports:  15%|█▌        | 1068/7111 [03:41<19:12,  5.24it/s]

Reports:  15%|█▌        | 1069/7111 [03:41<19:09,  5.25it/s]

Reports:  15%|█▌        | 1070/7111 [03:41<19:31,  5.16it/s]

Reports:  15%|█▌        | 1071/7111 [03:42<20:20,  4.95it/s]

Reports:  15%|█▌        | 1072/7111 [03:42<20:10,  4.99it/s]

Reports:  15%|█▌        | 1073/7111 [03:42<19:40,  5.12it/s]

Reports:  15%|█▌        | 1074/7111 [03:42<19:33,  5.14it/s]

Reports:  15%|█▌        | 1075/7111 [03:42<19:42,  5.11it/s]

Reports:  15%|█▌        | 1076/7111 [03:43<19:36,  5.13it/s]

Reports:  15%|█▌        | 1077/7111 [03:43<19:58,  5.03it/s]

Reports:  15%|█▌        | 1078/7111 [03:43<22:48,  4.41it/s]

Reports:  15%|█▌        | 1079/7111 [03:43<21:40,  4.64it/s]

Reports:  15%|█▌        | 1080/7111 [03:44<21:41,  4.64it/s]

Reports:  15%|█▌        | 1081/7111 [03:44<21:05,  4.76it/s]

Reports:  15%|█▌        | 1082/7111 [03:44<20:51,  4.82it/s]

Reports:  15%|█▌        | 1083/7111 [03:44<20:38,  4.87it/s]

Reports:  15%|█▌        | 1084/7111 [03:44<19:59,  5.02it/s]

Reports:  15%|█▌        | 1085/7111 [03:45<19:48,  5.07it/s]

Reports:  15%|█▌        | 1086/7111 [03:45<20:06,  4.99it/s]

Reports:  15%|█▌        | 1087/7111 [03:45<20:04,  5.00it/s]

Reports:  15%|█▌        | 1088/7111 [03:45<20:17,  4.95it/s]

Reports:  15%|█▌        | 1089/7111 [03:45<20:02,  5.01it/s]

Reports:  15%|█▌        | 1090/7111 [03:46<20:08,  4.98it/s]

Reports:  15%|█▌        | 1091/7111 [03:46<20:15,  4.95it/s]

Reports:  15%|█▌        | 1092/7111 [03:46<19:49,  5.06it/s]

Reports:  15%|█▌        | 1093/7111 [03:46<19:51,  5.05it/s]

Reports:  15%|█▌        | 1094/7111 [03:46<20:13,  4.96it/s]

Reports:  15%|█▌        | 1095/7111 [03:47<20:03,  5.00it/s]

Reports:  15%|█▌        | 1096/7111 [03:47<20:14,  4.95it/s]

Reports:  15%|█▌        | 1097/7111 [03:47<20:19,  4.93it/s]

Reports:  15%|█▌        | 1098/7111 [03:47<20:20,  4.93it/s]

Reports:  15%|█▌        | 1099/7111 [03:47<19:50,  5.05it/s]

Reports:  15%|█▌        | 1100/7111 [03:48<19:37,  5.10it/s]

Reports:  15%|█▌        | 1101/7111 [03:48<19:32,  5.13it/s]

Reports:  15%|█▌        | 1102/7111 [03:48<19:29,  5.14it/s]

Reports:  16%|█▌        | 1103/7111 [03:48<19:53,  5.04it/s]

Reports:  16%|█▌        | 1104/7111 [03:48<19:33,  5.12it/s]

Reports:  16%|█▌        | 1105/7111 [03:48<19:29,  5.13it/s]

Reports:  16%|█▌        | 1106/7111 [03:49<19:28,  5.14it/s]

Reports:  16%|█▌        | 1107/7111 [03:49<19:27,  5.14it/s]

Reports:  16%|█▌        | 1108/7111 [03:49<19:22,  5.17it/s]

Reports:  16%|█▌        | 1109/7111 [03:49<19:23,  5.16it/s]

Reports:  16%|█▌        | 1110/7111 [03:49<19:16,  5.19it/s]

Reports:  16%|█▌        | 1111/7111 [03:50<19:18,  5.18it/s]

Reports:  16%|█▌        | 1112/7111 [03:50<19:05,  5.24it/s]

Reports:  16%|█▌        | 1113/7111 [03:50<18:52,  5.30it/s]

Reports:  16%|█▌        | 1114/7111 [03:50<19:38,  5.09it/s]

Reports:  16%|█▌        | 1115/7111 [03:50<19:54,  5.02it/s]

Reports:  16%|█▌        | 1116/7111 [03:51<19:29,  5.13it/s]

Reports:  16%|█▌        | 1117/7111 [03:51<19:42,  5.07it/s]

Reports:  16%|█▌        | 1118/7111 [03:51<19:39,  5.08it/s]

Reports:  16%|█▌        | 1119/7111 [03:51<20:12,  4.94it/s]

Reports:  16%|█▌        | 1120/7111 [03:51<20:09,  4.95it/s]

Reports:  16%|█▌        | 1121/7111 [03:52<19:59,  4.99it/s]

Reports:  16%|█▌        | 1122/7111 [03:52<19:32,  5.11it/s]

Reports:  16%|█▌        | 1123/7111 [03:52<19:36,  5.09it/s]

Reports:  16%|█▌        | 1124/7111 [03:52<19:16,  5.18it/s]

Reports:  16%|█▌        | 1125/7111 [03:52<19:17,  5.17it/s]

Reports:  16%|█▌        | 1126/7111 [03:53<19:08,  5.21it/s]

Reports:  16%|█▌        | 1127/7111 [03:53<19:32,  5.10it/s]

Reports:  16%|█▌        | 1128/7111 [03:53<19:46,  5.04it/s]

Reports:  16%|█▌        | 1129/7111 [03:53<19:29,  5.12it/s]

Reports:  16%|█▌        | 1130/7111 [03:53<19:20,  5.16it/s]

Reports:  16%|█▌        | 1131/7111 [03:54<19:39,  5.07it/s]

Reports:  16%|█▌        | 1132/7111 [03:54<26:05,  3.82it/s]

Reports:  16%|█▌        | 1133/7111 [03:54<24:30,  4.07it/s]

Reports:  16%|█▌        | 1134/7111 [03:54<22:44,  4.38it/s]

Reports:  16%|█▌        | 1135/7111 [03:55<21:35,  4.61it/s]

Reports:  16%|█▌        | 1136/7111 [03:55<20:43,  4.81it/s]

Reports:  16%|█▌        | 1137/7111 [03:55<20:25,  4.88it/s]

Reports:  16%|█▌        | 1138/7111 [03:55<20:09,  4.94it/s]

Reports:  16%|█▌        | 1139/7111 [03:55<19:47,  5.03it/s]

Reports:  16%|█▌        | 1140/7111 [03:56<19:27,  5.11it/s]

Reports:  16%|█▌        | 1141/7111 [03:56<19:13,  5.18it/s]

Reports:  16%|█▌        | 1142/7111 [03:56<19:12,  5.18it/s]

Reports:  16%|█▌        | 1143/7111 [03:56<19:11,  5.18it/s]

Reports:  16%|█▌        | 1144/7111 [03:56<19:07,  5.20it/s]

Reports:  16%|█▌        | 1145/7111 [03:56<18:57,  5.25it/s]

Reports:  16%|█▌        | 1146/7111 [03:57<28:18,  3.51it/s]

Reports:  16%|█▌        | 1147/7111 [03:57<25:43,  3.86it/s]

Reports:  16%|█▌        | 1148/7111 [03:57<23:35,  4.21it/s]

Reports:  16%|█▌        | 1149/7111 [03:58<22:20,  4.45it/s]

Reports:  16%|█▌        | 1150/7111 [03:58<21:25,  4.64it/s]

Reports:  16%|█▌        | 1151/7111 [03:58<20:54,  4.75it/s]

Reports:  16%|█▌        | 1152/7111 [03:58<20:27,  4.86it/s]

Reports:  16%|█▌        | 1153/7111 [03:58<19:49,  5.01it/s]

Reports:  16%|█▌        | 1154/7111 [03:59<19:53,  4.99it/s]

Reports:  16%|█▌        | 1155/7111 [03:59<19:35,  5.07it/s]

Reports:  16%|█▋        | 1156/7111 [03:59<19:31,  5.08it/s]

Reports:  16%|█▋        | 1157/7111 [03:59<19:23,  5.12it/s]

Reports:  16%|█▋        | 1158/7111 [03:59<19:11,  5.17it/s]

Reports:  16%|█▋        | 1159/7111 [04:00<18:57,  5.23it/s]

Reports:  16%|█▋        | 1160/7111 [04:00<19:04,  5.20it/s]

Reports:  16%|█▋        | 1161/7111 [04:00<19:05,  5.19it/s]

Reports:  16%|█▋        | 1162/7111 [04:00<19:32,  5.07it/s]

Reports:  16%|█▋        | 1163/7111 [04:00<19:30,  5.08it/s]

Reports:  16%|█▋        | 1164/7111 [04:00<19:14,  5.15it/s]

Reports:  16%|█▋        | 1165/7111 [04:01<19:01,  5.21it/s]

Reports:  16%|█▋        | 1166/7111 [04:01<19:30,  5.08it/s]

Reports:  16%|█▋        | 1167/7111 [04:01<19:09,  5.17it/s]

Reports:  16%|█▋        | 1168/7111 [04:01<19:31,  5.07it/s]

Reports:  16%|█▋        | 1169/7111 [04:01<19:31,  5.07it/s]

Reports:  16%|█▋        | 1170/7111 [04:02<19:41,  5.03it/s]

Reports:  16%|█▋        | 1171/7111 [04:02<19:49,  4.99it/s]

Reports:  16%|█▋        | 1172/7111 [04:02<19:53,  4.97it/s]

Reports:  16%|█▋        | 1173/7111 [04:02<20:02,  4.94it/s]

Reports:  17%|█▋        | 1174/7111 [04:02<19:42,  5.02it/s]

Reports:  17%|█▋        | 1175/7111 [04:03<20:01,  4.94it/s]

Reports:  17%|█▋        | 1176/7111 [04:03<19:28,  5.08it/s]

Reports:  17%|█▋        | 1177/7111 [04:03<21:26,  4.61it/s]

Reports:  17%|█▋        | 1178/7111 [04:03<20:45,  4.76it/s]

Reports:  17%|█▋        | 1179/7111 [04:04<21:06,  4.68it/s]

Reports:  17%|█▋        | 1180/7111 [04:04<20:28,  4.83it/s]

Reports:  17%|█▋        | 1181/7111 [04:04<20:30,  4.82it/s]

Reports:  17%|█▋        | 1182/7111 [04:04<20:08,  4.91it/s]

Reports:  17%|█▋        | 1183/7111 [04:04<20:14,  4.88it/s]

Reports:  17%|█▋        | 1184/7111 [04:05<19:44,  5.00it/s]

Reports:  17%|█▋        | 1185/7111 [04:05<20:11,  4.89it/s]

Reports:  17%|█▋        | 1186/7111 [04:05<22:00,  4.49it/s]

Reports:  17%|█▋        | 1187/7111 [04:05<20:49,  4.74it/s]

Reports:  17%|█▋        | 1188/7111 [04:05<20:22,  4.85it/s]

Reports:  17%|█▋        | 1189/7111 [04:06<20:07,  4.90it/s]

Reports:  17%|█▋        | 1190/7111 [04:06<19:35,  5.04it/s]

Reports:  17%|█▋        | 1191/7111 [04:06<19:37,  5.03it/s]

Reports:  17%|█▋        | 1192/7111 [04:06<19:14,  5.13it/s]

Reports:  17%|█▋        | 1193/7111 [04:06<19:18,  5.11it/s]

Reports:  17%|█▋        | 1194/7111 [04:07<19:30,  5.05it/s]

Reports:  17%|█▋        | 1195/7111 [04:07<19:18,  5.11it/s]

Reports:  17%|█▋        | 1196/7111 [04:07<19:06,  5.16it/s]

Reports:  17%|█▋        | 1197/7111 [04:07<18:56,  5.21it/s]

Reports:  17%|█▋        | 1198/7111 [04:07<18:50,  5.23it/s]

Reports:  17%|█▋        | 1199/7111 [04:08<18:48,  5.24it/s]

Reports:  17%|█▋        | 1200/7111 [04:08<18:52,  5.22it/s]

Reports:  17%|█▋        | 1201/7111 [04:08<18:43,  5.26it/s]

Reports:  17%|█▋        | 1202/7111 [04:08<18:37,  5.29it/s]

Reports:  17%|█▋        | 1203/7111 [04:08<18:25,  5.34it/s]

Reports:  17%|█▋        | 1204/7111 [04:08<18:29,  5.32it/s]

Reports:  17%|█▋        | 1205/7111 [04:09<18:38,  5.28it/s]

Reports:  17%|█▋        | 1206/7111 [04:09<18:34,  5.30it/s]

Reports:  17%|█▋        | 1207/7111 [04:09<18:23,  5.35it/s]

Reports:  17%|█▋        | 1208/7111 [04:09<18:24,  5.35it/s]

Reports:  17%|█▋        | 1209/7111 [04:09<18:39,  5.27it/s]

Reports:  17%|█▋        | 1210/7111 [04:10<18:37,  5.28it/s]

Reports:  17%|█▋        | 1211/7111 [04:10<18:46,  5.24it/s]

Reports:  17%|█▋        | 1212/7111 [04:10<18:44,  5.25it/s]

Reports:  17%|█▋        | 1213/7111 [04:10<18:54,  5.20it/s]

Reports:  17%|█▋        | 1214/7111 [04:10<19:24,  5.06it/s]

Reports:  17%|█▋        | 1215/7111 [04:11<19:08,  5.13it/s]

Reports:  17%|█▋        | 1216/7111 [04:11<18:56,  5.19it/s]

Reports:  17%|█▋        | 1217/7111 [04:11<19:02,  5.16it/s]

Reports:  17%|█▋        | 1218/7111 [04:11<18:44,  5.24it/s]

Reports:  17%|█▋        | 1219/7111 [04:11<19:03,  5.15it/s]

Reports:  17%|█▋        | 1220/7111 [04:12<18:49,  5.22it/s]

Reports:  17%|█▋        | 1221/7111 [04:12<18:59,  5.17it/s]

Reports:  17%|█▋        | 1222/7111 [04:12<18:52,  5.20it/s]

Reports:  17%|█▋        | 1223/7111 [04:12<18:59,  5.17it/s]

Reports:  17%|█▋        | 1224/7111 [04:12<19:05,  5.14it/s]

Reports:  17%|█▋        | 1225/7111 [04:13<19:10,  5.12it/s]

Reports:  17%|█▋        | 1226/7111 [04:13<19:20,  5.07it/s]

Reports:  17%|█▋        | 1227/7111 [04:13<19:00,  5.16it/s]

Reports:  17%|█▋        | 1228/7111 [04:13<18:47,  5.22it/s]

Reports:  17%|█▋        | 1229/7111 [04:13<18:39,  5.25it/s]

Reports:  17%|█▋        | 1230/7111 [04:13<18:37,  5.26it/s]

Reports:  17%|█▋        | 1231/7111 [04:14<18:27,  5.31it/s]

Reports:  17%|█▋        | 1232/7111 [04:15<43:59,  2.23it/s]

Reports:  17%|█▋        | 1233/7111 [04:15<36:45,  2.66it/s]

Reports:  17%|█▋        | 1234/7111 [04:15<31:58,  3.06it/s]

Reports:  17%|█▋        | 1235/7111 [04:15<28:01,  3.49it/s]

Reports:  17%|█▋        | 1236/7111 [04:15<25:02,  3.91it/s]

Reports:  17%|█▋        | 1237/7111 [04:16<23:04,  4.24it/s]

Reports:  17%|█▋        | 1238/7111 [04:16<21:39,  4.52it/s]

Reports:  17%|█▋        | 1239/7111 [04:16<20:39,  4.74it/s]

Reports:  17%|█▋        | 1240/7111 [04:16<19:59,  4.89it/s]

Reports:  17%|█▋        | 1241/7111 [04:16<19:28,  5.02it/s]

Reports:  17%|█▋        | 1242/7111 [04:17<19:11,  5.10it/s]

Reports:  17%|█▋        | 1243/7111 [04:17<19:28,  5.02it/s]

Reports:  17%|█▋        | 1244/7111 [04:17<19:08,  5.11it/s]

Reports:  18%|█▊        | 1245/7111 [04:17<19:01,  5.14it/s]

Reports:  18%|█▊        | 1246/7111 [04:17<19:00,  5.14it/s]

Reports:  18%|█▊        | 1247/7111 [04:18<18:50,  5.19it/s]

Reports:  18%|█▊        | 1248/7111 [04:18<18:44,  5.21it/s]

Reports:  18%|█▊        | 1249/7111 [04:18<19:10,  5.09it/s]

Reports:  18%|█▊        | 1250/7111 [04:18<18:53,  5.17it/s]

Reports:  18%|█▊        | 1251/7111 [04:18<18:43,  5.22it/s]

Reports:  18%|█▊        | 1252/7111 [04:19<18:46,  5.20it/s]

Reports:  18%|█▊        | 1253/7111 [04:19<18:46,  5.20it/s]

Reports:  18%|█▊        | 1254/7111 [04:19<18:44,  5.21it/s]

Reports:  18%|█▊        | 1255/7111 [04:19<18:59,  5.14it/s]

Reports:  18%|█▊        | 1256/7111 [04:19<18:48,  5.19it/s]

Reports:  18%|█▊        | 1257/7111 [04:20<18:45,  5.20it/s]

Reports:  18%|█▊        | 1258/7111 [04:20<18:37,  5.24it/s]

Reports:  18%|█▊        | 1259/7111 [04:20<18:49,  5.18it/s]

Reports:  18%|█▊        | 1260/7111 [04:20<19:08,  5.10it/s]

Reports:  18%|█▊        | 1261/7111 [04:20<18:50,  5.17it/s]

Reports:  18%|█▊        | 1262/7111 [04:20<18:36,  5.24it/s]

Reports:  18%|█▊        | 1263/7111 [04:21<18:31,  5.26it/s]

Reports:  18%|█▊        | 1264/7111 [04:21<18:34,  5.25it/s]

Reports:  18%|█▊        | 1265/7111 [04:21<18:48,  5.18it/s]

Reports:  18%|█▊        | 1266/7111 [04:21<18:38,  5.23it/s]

Reports:  18%|█▊        | 1267/7111 [04:21<18:38,  5.22it/s]

Reports:  18%|█▊        | 1268/7111 [04:22<19:18,  5.04it/s]

Reports:  18%|█▊        | 1269/7111 [04:22<19:06,  5.09it/s]

Reports:  18%|█▊        | 1270/7111 [04:22<18:55,  5.14it/s]

Reports:  18%|█▊        | 1271/7111 [04:22<19:24,  5.02it/s]

Reports:  18%|█▊        | 1272/7111 [04:22<19:17,  5.04it/s]

Reports:  18%|█▊        | 1273/7111 [04:23<19:12,  5.06it/s]

Reports:  18%|█▊        | 1274/7111 [04:23<21:56,  4.44it/s]

Reports:  18%|█▊        | 1275/7111 [04:23<21:10,  4.59it/s]

Reports:  18%|█▊        | 1276/7111 [04:23<20:16,  4.80it/s]

Reports:  18%|█▊        | 1277/7111 [04:23<19:46,  4.92it/s]

Reports:  18%|█▊        | 1278/7111 [04:24<19:25,  5.01it/s]

Reports:  18%|█▊        | 1279/7111 [04:24<19:12,  5.06it/s]

Reports:  18%|█▊        | 1280/7111 [04:25<48:18,  2.01it/s]

Reports:  18%|█▊        | 1281/7111 [04:25<39:50,  2.44it/s]

Reports:  18%|█▊        | 1282/7111 [04:25<33:38,  2.89it/s]

Reports:  18%|█▊        | 1283/7111 [04:26<29:18,  3.31it/s]

Reports:  18%|█▊        | 1284/7111 [04:26<26:02,  3.73it/s]

Reports:  18%|█▊        | 1285/7111 [04:26<23:44,  4.09it/s]

Reports:  18%|█▊        | 1286/7111 [04:26<22:42,  4.28it/s]

Reports:  18%|█▊        | 1287/7111 [04:26<22:04,  4.40it/s]

Reports:  18%|█▊        | 1288/7111 [04:27<21:17,  4.56it/s]

Reports:  18%|█▊        | 1289/7111 [04:27<20:42,  4.68it/s]

Reports:  18%|█▊        | 1290/7111 [04:27<20:26,  4.74it/s]

Reports:  18%|█▊        | 1291/7111 [04:27<19:57,  4.86it/s]

Reports:  18%|█▊        | 1292/7111 [04:27<19:50,  4.89it/s]

Reports:  18%|█▊        | 1293/7111 [04:28<19:13,  5.04it/s]

Reports:  18%|█▊        | 1294/7111 [04:28<18:48,  5.16it/s]

Reports:  18%|█▊        | 1295/7111 [04:28<18:43,  5.18it/s]

Reports:  18%|█▊        | 1296/7111 [04:29<40:05,  2.42it/s]

Reports:  18%|█▊        | 1297/7111 [04:29<33:23,  2.90it/s]

Reports:  18%|█▊        | 1298/7111 [04:29<28:50,  3.36it/s]

Reports:  18%|█▊        | 1299/7111 [04:30<25:46,  3.76it/s]

Reports:  18%|█▊        | 1300/7111 [04:30<23:36,  4.10it/s]

Reports:  18%|█▊        | 1301/7111 [04:30<21:59,  4.40it/s]

Reports:  18%|█▊        | 1302/7111 [04:30<21:27,  4.51it/s]

Reports:  18%|█▊        | 1303/7111 [04:31<45:07,  2.15it/s]

Reports:  18%|█▊        | 1304/7111 [04:31<37:13,  2.60it/s]

Reports:  18%|█▊        | 1305/7111 [04:32<51:38,  1.87it/s]

Reports:  18%|█▊        | 1306/7111 [04:34<1:36:46,  1.00s/it]

Reports:  18%|█▊        | 1307/7111 [04:35<1:13:25,  1.32it/s]

Reports:  18%|█▊        | 1308/7111 [04:35<57:20,  1.69it/s]

Reports:  18%|█▊        | 1309/7111 [04:35<45:37,  2.12it/s]

Reports:  18%|█▊        | 1310/7111 [04:37<1:25:09,  1.14it/s]

Reports:  18%|█▊        | 1311/7111 [04:37<1:05:24,  1.48it/s]

Reports:  18%|█▊        | 1312/7111 [04:37<51:16,  1.88it/s]

Reports:  18%|█▊        | 1313/7111 [04:37<41:24,  2.33it/s]

Reports:  18%|█▊        | 1314/7111 [04:38<35:07,  2.75it/s]

Reports:  18%|█▊        | 1315/7111 [04:38<30:13,  3.20it/s]

Reports:  19%|█▊        | 1316/7111 [04:38<26:55,  3.59it/s]

Reports:  19%|█▊        | 1317/7111 [04:38<24:29,  3.94it/s]

Reports:  19%|█▊        | 1318/7111 [04:38<22:44,  4.25it/s]

Reports:  19%|█▊        | 1319/7111 [04:39<21:14,  4.54it/s]

Reports:  19%|█▊        | 1320/7111 [04:39<20:36,  4.69it/s]

Reports:  19%|█▊        | 1321/7111 [04:39<19:56,  4.84it/s]

Reports:  19%|█▊        | 1322/7111 [04:39<20:02,  4.81it/s]

Reports:  19%|█▊        | 1323/7111 [04:39<19:29,  4.95it/s]

Reports:  19%|█▊        | 1324/7111 [04:39<19:24,  4.97it/s]

Reports:  19%|█▊        | 1325/7111 [04:40<19:08,  5.04it/s]

Reports:  19%|█▊        | 1326/7111 [04:40<19:06,  5.05it/s]

Reports:  19%|█▊        | 1327/7111 [04:40<19:27,  4.95it/s]

Reports:  19%|█▊        | 1328/7111 [04:40<19:21,  4.98it/s]

Reports:  19%|█▊        | 1329/7111 [04:41<30:48,  3.13it/s]

Reports:  19%|█▊        | 1330/7111 [04:42<55:20,  1.74it/s]

Reports:  19%|█▊        | 1331/7111 [04:43<1:14:09,  1.30it/s]

Reports:  19%|█▊        | 1332/7111 [04:43<57:26,  1.68it/s]

Reports:  19%|█▊        | 1333/7111 [04:44<45:52,  2.10it/s]

Reports:  19%|█▉        | 1334/7111 [04:44<37:56,  2.54it/s]

Reports:  19%|█▉        | 1335/7111 [04:44<32:40,  2.95it/s]

Reports:  19%|█▉        | 1336/7111 [04:44<29:07,  3.30it/s]

Reports:  19%|█▉        | 1337/7111 [04:45<26:39,  3.61it/s]

Reports:  19%|█▉        | 1338/7111 [04:45<24:32,  3.92it/s]

Reports:  19%|█▉        | 1339/7111 [04:45<22:56,  4.19it/s]

Reports:  19%|█▉        | 1340/7111 [04:45<24:06,  3.99it/s]

Reports:  19%|█▉        | 1341/7111 [04:45<22:57,  4.19it/s]

Reports:  19%|█▉        | 1342/7111 [04:46<21:24,  4.49it/s]

Reports:  19%|█▉        | 1343/7111 [04:46<20:41,  4.65it/s]

Reports:  19%|█▉        | 1344/7111 [04:46<20:01,  4.80it/s]

Reports:  19%|█▉        | 1345/7111 [04:46<19:16,  4.99it/s]

Reports:  19%|█▉        | 1346/7111 [04:47<42:14,  2.27it/s]

Reports:  19%|█▉        | 1347/7111 [04:47<35:14,  2.73it/s]

Reports:  19%|█▉        | 1348/7111 [04:48<42:20,  2.27it/s]

Reports:  19%|█▉        | 1349/7111 [04:48<35:08,  2.73it/s]

Reports:  19%|█▉        | 1350/7111 [04:49<51:01,  1.88it/s]

Reports:  19%|█▉        | 1351/7111 [04:51<1:45:08,  1.10s/it]

Reports:  19%|█▉        | 1352/7111 [04:52<1:19:00,  1.21it/s]

Reports:  19%|█▉        | 1353/7111 [04:52<1:00:55,  1.58it/s]

Reports:  19%|█▉        | 1354/7111 [04:52<48:07,  1.99it/s]

Reports:  19%|█▉        | 1355/7111 [04:52<39:16,  2.44it/s]

Reports:  19%|█▉        | 1356/7111 [04:52<33:01,  2.90it/s]

Reports:  19%|█▉        | 1357/7111 [04:53<28:29,  3.37it/s]

Reports:  19%|█▉        | 1358/7111 [04:54<57:55,  1.66it/s]

Reports:  19%|█▉        | 1359/7111 [04:54<46:33,  2.06it/s]

Reports:  19%|█▉        | 1360/7111 [04:54<38:10,  2.51it/s]

Reports:  19%|█▉        | 1361/7111 [04:55<32:26,  2.95it/s]

Reports:  19%|█▉        | 1362/7111 [04:56<1:07:44,  1.41it/s]

Reports:  19%|█▉        | 1363/7111 [04:56<53:05,  1.80it/s]

Reports:  19%|█▉        | 1364/7111 [04:57<43:16,  2.21it/s]

Reports:  19%|█▉        | 1365/7111 [04:59<1:47:59,  1.13s/it]

Reports:  19%|█▉        | 1366/7111 [04:59<1:21:18,  1.18it/s]

Reports:  19%|█▉        | 1367/7111 [05:00<1:02:51,  1.52it/s]

Reports:  19%|█▉        | 1368/7111 [05:00<50:05,  1.91it/s]

Reports:  19%|█▉        | 1369/7111 [05:00<40:32,  2.36it/s]

Reports:  19%|█▉        | 1370/7111 [05:01<42:56,  2.23it/s]

Reports:  19%|█▉        | 1371/7111 [05:01<35:29,  2.70it/s]

Reports:  19%|█▉        | 1372/7111 [05:01<30:15,  3.16it/s]

Reports:  19%|█▉        | 1373/7111 [05:01<27:01,  3.54it/s]

Reports:  19%|█▉        | 1374/7111 [05:01<24:37,  3.88it/s]

Reports:  19%|█▉        | 1375/7111 [05:02<22:30,  4.25it/s]

Reports:  19%|█▉        | 1376/7111 [05:02<21:13,  4.50it/s]

Reports:  19%|█▉        | 1377/7111 [05:03<1:05:45,  1.45it/s]

Reports:  19%|█▉        | 1378/7111 [05:04<51:44,  1.85it/s]

Reports:  19%|█▉        | 1379/7111 [05:04<42:07,  2.27it/s]

Reports:  19%|█▉        | 1380/7111 [05:04<35:37,  2.68it/s]

Reports:  19%|█▉        | 1381/7111 [05:04<30:20,  3.15it/s]

Reports:  19%|█▉        | 1382/7111 [05:05<27:38,  3.46it/s]

Reports:  19%|█▉        | 1383/7111 [05:05<40:54,  2.33it/s]

Reports:  19%|█▉        | 1384/7111 [05:05<34:05,  2.80it/s]

Reports:  19%|█▉        | 1385/7111 [05:06<29:14,  3.26it/s]

Reports:  19%|█▉        | 1386/7111 [05:06<26:36,  3.59it/s]

Reports:  20%|█▉        | 1387/7111 [05:06<24:59,  3.82it/s]

Reports:  20%|█▉        | 1388/7111 [05:06<22:54,  4.16it/s]

Reports:  20%|█▉        | 1389/7111 [05:06<21:57,  4.34it/s]

Reports:  20%|█▉        | 1390/7111 [05:07<20:50,  4.57it/s]

Reports:  20%|█▉        | 1391/7111 [05:08<53:15,  1.79it/s]

Reports:  20%|█▉        | 1392/7111 [05:08<42:56,  2.22it/s]

Reports:  20%|█▉        | 1393/7111 [05:08<36:05,  2.64it/s]

Reports:  20%|█▉        | 1394/7111 [05:09<30:57,  3.08it/s]

Reports:  20%|█▉        | 1395/7111 [05:09<27:44,  3.43it/s]

Reports:  20%|█▉        | 1396/7111 [05:09<27:12,  3.50it/s]

Reports:  20%|█▉        | 1397/7111 [05:09<25:14,  3.77it/s]

Reports:  20%|█▉        | 1398/7111 [05:10<23:30,  4.05it/s]

Reports:  20%|█▉        | 1399/7111 [05:10<22:39,  4.20it/s]

Reports:  20%|█▉        | 1400/7111 [05:10<21:21,  4.46it/s]

Reports:  20%|█▉        | 1401/7111 [05:10<20:12,  4.71it/s]

Reports:  20%|█▉        | 1402/7111 [05:10<19:56,  4.77it/s]

Reports:  20%|█▉        | 1403/7111 [05:11<19:35,  4.86it/s]

Reports:  20%|█▉        | 1404/7111 [05:11<18:56,  5.02it/s]

Reports:  20%|█▉        | 1405/7111 [05:11<19:04,  4.99it/s]

Reports:  20%|█▉        | 1406/7111 [05:11<19:08,  4.97it/s]

Reports:  20%|█▉        | 1407/7111 [05:12<41:22,  2.30it/s]

Reports:  20%|█▉        | 1408/7111 [05:12<34:39,  2.74it/s]

Reports:  20%|█▉        | 1409/7111 [05:13<30:26,  3.12it/s]

Reports:  20%|█▉        | 1410/7111 [05:13<26:56,  3.53it/s]

Reports:  20%|█▉        | 1411/7111 [05:14<48:55,  1.94it/s]

Reports:  20%|█▉        | 1412/7111 [05:14<39:37,  2.40it/s]

Reports:  20%|█▉        | 1413/7111 [05:14<33:13,  2.86it/s]

Reports:  20%|█▉        | 1414/7111 [05:14<28:46,  3.30it/s]

Reports:  20%|█▉        | 1415/7111 [05:15<26:05,  3.64it/s]

Reports:  20%|█▉        | 1416/7111 [05:15<24:25,  3.89it/s]

Reports:  20%|█▉        | 1417/7111 [05:15<22:40,  4.19it/s]

Reports:  20%|█▉        | 1418/7111 [05:16<30:45,  3.08it/s]

Reports:  20%|█▉        | 1419/7111 [05:16<27:01,  3.51it/s]

Reports:  20%|█▉        | 1420/7111 [05:16<24:23,  3.89it/s]

Reports:  20%|█▉        | 1421/7111 [05:16<33:13,  2.85it/s]

Reports:  20%|█▉        | 1422/7111 [05:17<28:37,  3.31it/s]

Reports:  20%|██        | 1423/7111 [05:17<25:54,  3.66it/s]

Reports:  20%|██        | 1424/7111 [05:17<34:55,  2.71it/s]

Reports:  20%|██        | 1425/7111 [05:19<1:05:11,  1.45it/s]

Reports:  20%|██        | 1426/7111 [05:19<51:42,  1.83it/s]

Reports:  20%|██        | 1427/7111 [05:19<41:56,  2.26it/s]

Reports:  20%|██        | 1428/7111 [05:20<35:22,  2.68it/s]

Reports:  20%|██        | 1429/7111 [05:20<30:21,  3.12it/s]

Reports:  20%|██        | 1430/7111 [05:20<27:19,  3.46it/s]

Reports:  20%|██        | 1431/7111 [05:20<25:01,  3.78it/s]

Reports:  20%|██        | 1432/7111 [05:20<24:13,  3.91it/s]

Reports:  20%|██        | 1433/7111 [05:21<48:37,  1.95it/s]

Reports:  20%|██        | 1434/7111 [05:22<39:56,  2.37it/s]

Reports:  20%|██        | 1435/7111 [05:22<33:28,  2.83it/s]

Reports:  20%|██        | 1436/7111 [05:22<29:00,  3.26it/s]

Reports:  20%|██        | 1437/7111 [05:22<26:29,  3.57it/s]

Reports:  20%|██        | 1438/7111 [05:22<23:55,  3.95it/s]

Reports:  20%|██        | 1439/7111 [05:23<22:49,  4.14it/s]

Reports:  20%|██        | 1440/7111 [05:23<37:07,  2.55it/s]

Reports:  20%|██        | 1441/7111 [05:24<31:37,  2.99it/s]

Reports:  20%|██        | 1442/7111 [05:24<27:27,  3.44it/s]

Reports:  20%|██        | 1443/7111 [05:24<24:51,  3.80it/s]

Reports:  20%|██        | 1444/7111 [05:24<23:12,  4.07it/s]

Reports:  20%|██        | 1445/7111 [05:24<22:01,  4.29it/s]

Reports:  20%|██        | 1446/7111 [05:25<20:43,  4.56it/s]

Reports:  20%|██        | 1447/7111 [05:25<20:17,  4.65it/s]

Reports:  20%|██        | 1448/7111 [05:25<19:37,  4.81it/s]

Reports:  20%|██        | 1449/7111 [05:25<19:05,  4.94it/s]

Reports:  20%|██        | 1450/7111 [05:25<19:30,  4.84it/s]

Reports:  20%|██        | 1451/7111 [05:26<19:22,  4.87it/s]

Reports:  20%|██        | 1452/7111 [05:26<19:09,  4.92it/s]

Reports:  20%|██        | 1453/7111 [05:26<19:00,  4.96it/s]

Reports:  20%|██        | 1454/7111 [05:27<27:30,  3.43it/s]

Reports:  20%|██        | 1455/7111 [05:27<35:42,  2.64it/s]

Reports:  20%|██        | 1456/7111 [05:27<30:29,  3.09it/s]

Reports:  20%|██        | 1457/7111 [05:28<27:04,  3.48it/s]

Reports:  21%|██        | 1458/7111 [05:28<24:26,  3.85it/s]

Reports:  21%|██        | 1459/7111 [05:29<45:07,  2.09it/s]

Reports:  21%|██        | 1460/7111 [05:29<37:06,  2.54it/s]

Reports:  21%|██        | 1461/7111 [05:29<32:14,  2.92it/s]

Reports:  21%|██        | 1462/7111 [05:30<38:41,  2.43it/s]

Reports:  21%|██        | 1463/7111 [05:30<32:42,  2.88it/s]

Reports:  21%|██        | 1464/7111 [05:33<2:02:34,  1.30s/it]

Reports:  21%|██        | 1465/7111 [05:35<2:02:32,  1.30s/it]

Reports:  21%|██        | 1466/7111 [05:35<1:31:55,  1.02it/s]

Reports:  21%|██        | 1467/7111 [05:35<1:10:09,  1.34it/s]

Reports:  21%|██        | 1468/7111 [05:36<1:08:32,  1.37it/s]

Reports:  21%|██        | 1469/7111 [05:36<53:59,  1.74it/s]

Reports:  21%|██        | 1470/7111 [05:37<1:11:57,  1.31it/s]

Reports:  21%|██        | 1471/7111 [05:37<56:19,  1.67it/s]

Reports:  21%|██        | 1472/7111 [05:38<45:12,  2.08it/s]

Reports:  21%|██        | 1473/7111 [05:38<37:02,  2.54it/s]

Reports:  21%|██        | 1474/7111 [05:38<31:37,  2.97it/s]

Reports:  21%|██        | 1475/7111 [05:38<28:00,  3.35it/s]

Reports:  21%|██        | 1476/7111 [05:38<25:11,  3.73it/s]

Reports:  21%|██        | 1477/7111 [05:39<22:43,  4.13it/s]

Reports:  21%|██        | 1478/7111 [05:39<21:48,  4.31it/s]

Reports:  21%|██        | 1479/7111 [05:39<20:43,  4.53it/s]

Reports:  21%|██        | 1480/7111 [05:39<20:13,  4.64it/s]

Reports:  21%|██        | 1481/7111 [05:39<19:34,  4.79it/s]

Reports:  21%|██        | 1482/7111 [05:40<19:04,  4.92it/s]

Reports:  21%|██        | 1483/7111 [05:40<18:40,  5.02it/s]

Reports:  21%|██        | 1484/7111 [05:40<18:33,  5.05it/s]

Reports:  21%|██        | 1485/7111 [05:40<18:22,  5.10it/s]

Reports:  21%|██        | 1486/7111 [05:41<45:12,  2.07it/s]

Reports:  21%|██        | 1487/7111 [05:42<37:02,  2.53it/s]

Reports:  21%|██        | 1488/7111 [05:42<31:13,  3.00it/s]

Reports:  21%|██        | 1489/7111 [05:42<31:39,  2.96it/s]

Reports:  21%|██        | 1490/7111 [05:43<50:19,  1.86it/s]

Reports:  21%|██        | 1491/7111 [05:43<40:54,  2.29it/s]

Reports:  21%|██        | 1492/7111 [05:43<33:59,  2.76it/s]

Reports:  21%|██        | 1493/7111 [05:44<29:23,  3.19it/s]

Reports:  21%|██        | 1494/7111 [05:44<26:00,  3.60it/s]

Reports:  21%|██        | 1495/7111 [05:44<24:20,  3.85it/s]

Reports:  21%|██        | 1496/7111 [05:44<22:35,  4.14it/s]

Reports:  21%|██        | 1497/7111 [05:44<21:08,  4.42it/s]

Reports:  21%|██        | 1498/7111 [05:45<20:14,  4.62it/s]

Reports:  21%|██        | 1499/7111 [05:45<19:34,  4.78it/s]

Reports:  21%|██        | 1500/7111 [05:45<26:54,  3.47it/s]

Reports:  21%|██        | 1501/7111 [05:46<24:27,  3.82it/s]

Reports:  21%|██        | 1502/7111 [05:46<22:43,  4.11it/s]

Reports:  21%|██        | 1503/7111 [05:46<21:33,  4.34it/s]

Reports:  21%|██        | 1504/7111 [05:46<20:42,  4.51it/s]

Reports:  21%|██        | 1505/7111 [05:46<20:12,  4.62it/s]

Reports:  21%|██        | 1506/7111 [05:47<19:45,  4.73it/s]

Reports:  21%|██        | 1507/7111 [05:47<19:01,  4.91it/s]

Reports:  21%|██        | 1508/7111 [05:47<18:30,  5.05it/s]

Reports:  21%|██        | 1509/7111 [05:47<18:25,  5.07it/s]

Reports:  21%|██        | 1510/7111 [05:48<27:24,  3.41it/s]

Reports:  21%|██        | 1511/7111 [05:48<24:31,  3.80it/s]

Reports:  21%|██▏       | 1512/7111 [05:48<22:50,  4.08it/s]

Reports:  21%|██▏       | 1513/7111 [05:48<21:27,  4.35it/s]

Reports:  21%|██▏       | 1514/7111 [05:48<20:12,  4.61it/s]

Reports:  21%|██▏       | 1515/7111 [05:49<19:48,  4.71it/s]

Reports:  21%|██▏       | 1516/7111 [05:49<35:19,  2.64it/s]

Reports:  21%|██▏       | 1517/7111 [05:50<30:20,  3.07it/s]

Reports:  21%|██▏       | 1518/7111 [05:50<36:46,  2.53it/s]

Reports:  21%|██▏       | 1519/7111 [05:51<52:42,  1.77it/s]

Reports:  21%|██▏       | 1520/7111 [05:52<1:02:24,  1.49it/s]

Reports:  21%|██▏       | 1521/7111 [05:53<1:10:27,  1.32it/s]

Reports:  21%|██▏       | 1522/7111 [05:53<54:48,  1.70it/s]

Reports:  21%|██▏       | 1523/7111 [05:53<43:47,  2.13it/s]

Reports:  21%|██▏       | 1524/7111 [05:54<36:06,  2.58it/s]

Reports:  21%|██▏       | 1525/7111 [05:54<30:37,  3.04it/s]

Reports:  21%|██▏       | 1526/7111 [05:54<26:31,  3.51it/s]

Reports:  21%|██▏       | 1527/7111 [05:54<24:14,  3.84it/s]

Reports:  21%|██▏       | 1528/7111 [05:54<22:11,  4.19it/s]

Reports:  22%|██▏       | 1529/7111 [05:55<21:02,  4.42it/s]

Reports:  22%|██▏       | 1530/7111 [05:55<20:08,  4.62it/s]

Reports:  22%|██▏       | 1531/7111 [05:55<19:53,  4.68it/s]

Reports:  22%|██▏       | 1532/7111 [05:57<1:23:11,  1.12it/s]

Reports:  22%|██▏       | 1533/7111 [05:58<1:14:56,  1.24it/s]

Reports:  22%|██▏       | 1534/7111 [05:58<58:13,  1.60it/s]

Reports:  22%|██▏       | 1535/7111 [05:58<46:08,  2.01it/s]

Reports:  22%|██▏       | 1536/7111 [05:59<38:08,  2.44it/s]

Reports:  22%|██▏       | 1537/7111 [05:59<31:56,  2.91it/s]

Reports:  22%|██▏       | 1538/7111 [06:00<45:52,  2.02it/s]

Reports:  22%|██▏       | 1539/7111 [06:00<37:27,  2.48it/s]

Reports:  22%|██▏       | 1540/7111 [06:00<31:21,  2.96it/s]

Reports:  22%|██▏       | 1541/7111 [06:01<1:01:56,  1.50it/s]

Reports:  22%|██▏       | 1542/7111 [06:02<48:37,  1.91it/s]

Reports:  22%|██▏       | 1543/7111 [06:02<39:51,  2.33it/s]

Reports:  22%|██▏       | 1544/7111 [06:02<33:08,  2.80it/s]

Reports:  22%|██▏       | 1545/7111 [06:02<28:40,  3.24it/s]

Reports:  22%|██▏       | 1546/7111 [06:02<25:08,  3.69it/s]

Reports:  22%|██▏       | 1547/7111 [06:03<46:12,  2.01it/s]

Reports:  22%|██▏       | 1548/7111 [06:05<1:02:52,  1.47it/s]

Reports:  22%|██▏       | 1549/7111 [06:05<49:21,  1.88it/s]

Reports:  22%|██▏       | 1550/7111 [06:05<39:59,  2.32it/s]

Reports:  22%|██▏       | 1551/7111 [06:05<34:36,  2.68it/s]

Reports:  22%|██▏       | 1552/7111 [06:05<29:39,  3.12it/s]

Reports:  22%|██▏       | 1553/7111 [06:06<26:12,  3.53it/s]

Reports:  22%|██▏       | 1554/7111 [06:06<23:24,  3.96it/s]

Reports:  22%|██▏       | 1555/7111 [06:06<21:55,  4.23it/s]

Reports:  22%|██▏       | 1556/7111 [06:06<21:22,  4.33it/s]

Reports:  22%|██▏       | 1557/7111 [06:06<20:10,  4.59it/s]

Reports:  22%|██▏       | 1558/7111 [06:07<19:33,  4.73it/s]

Reports:  22%|██▏       | 1559/7111 [06:07<19:11,  4.82it/s]

Reports:  22%|██▏       | 1560/7111 [06:07<18:58,  4.88it/s]

Reports:  22%|██▏       | 1561/7111 [06:08<45:02,  2.05it/s]

Reports:  22%|██▏       | 1562/7111 [06:08<37:20,  2.48it/s]

Reports:  22%|██▏       | 1563/7111 [06:09<32:04,  2.88it/s]

Reports:  22%|██▏       | 1564/7111 [06:09<31:26,  2.94it/s]

Reports:  22%|██▏       | 1565/7111 [06:09<27:47,  3.33it/s]

Reports:  22%|██▏       | 1566/7111 [06:09<24:58,  3.70it/s]

Reports:  22%|██▏       | 1567/7111 [06:09<23:00,  4.02it/s]

Reports:  22%|██▏       | 1568/7111 [06:10<21:24,  4.32it/s]

Reports:  22%|██▏       | 1569/7111 [06:10<20:24,  4.53it/s]

Reports:  22%|██▏       | 1570/7111 [06:10<19:47,  4.66it/s]

Reports:  22%|██▏       | 1571/7111 [06:10<19:02,  4.85it/s]

Reports:  22%|██▏       | 1572/7111 [06:10<18:50,  4.90it/s]

Reports:  22%|██▏       | 1573/7111 [06:11<18:29,  4.99it/s]

Reports:  22%|██▏       | 1574/7111 [06:11<18:36,  4.96it/s]

Reports:  22%|██▏       | 1575/7111 [06:11<25:27,  3.62it/s]

Reports:  22%|██▏       | 1576/7111 [06:11<23:10,  3.98it/s]

Reports:  22%|██▏       | 1577/7111 [06:12<21:44,  4.24it/s]

Reports:  22%|██▏       | 1578/7111 [06:12<20:26,  4.51it/s]

Reports:  22%|██▏       | 1579/7111 [06:12<19:36,  4.70it/s]

Reports:  22%|██▏       | 1580/7111 [06:12<19:27,  4.74it/s]

Reports:  22%|██▏       | 1581/7111 [06:13<42:34,  2.16it/s]

Reports:  22%|██▏       | 1582/7111 [06:14<40:12,  2.29it/s]

Reports:  22%|██▏       | 1583/7111 [06:14<33:14,  2.77it/s]

Reports:  22%|██▏       | 1584/7111 [06:15<46:10,  2.00it/s]

Reports:  22%|██▏       | 1585/7111 [06:15<49:55,  1.84it/s]

Reports:  22%|██▏       | 1586/7111 [06:16<40:32,  2.27it/s]

Reports:  22%|██▏       | 1587/7111 [06:16<33:47,  2.72it/s]

Reports:  22%|██▏       | 1588/7111 [06:16<33:32,  2.74it/s]

Reports:  22%|██▏       | 1589/7111 [06:17<38:06,  2.42it/s]

Reports:  22%|██▏       | 1590/7111 [06:17<32:05,  2.87it/s]

Reports:  22%|██▏       | 1591/7111 [06:17<27:37,  3.33it/s]

Reports:  22%|██▏       | 1592/7111 [06:18<40:43,  2.26it/s]

Reports:  22%|██▏       | 1593/7111 [06:18<34:11,  2.69it/s]

Reports:  22%|██▏       | 1594/7111 [06:18<29:46,  3.09it/s]

Reports:  22%|██▏       | 1595/7111 [06:18<26:36,  3.46it/s]

Reports:  22%|██▏       | 1596/7111 [06:19<23:50,  3.85it/s]

Reports:  22%|██▏       | 1597/7111 [06:19<25:44,  3.57it/s]

Reports:  22%|██▏       | 1598/7111 [06:19<23:34,  3.90it/s]

Reports:  22%|██▏       | 1599/7111 [06:19<21:35,  4.26it/s]

Reports:  23%|██▎       | 1600/7111 [06:21<1:13:56,  1.24it/s]

Reports:  23%|██▎       | 1601/7111 [06:22<1:00:30,  1.52it/s]

Reports:  23%|██▎       | 1602/7111 [06:22<48:05,  1.91it/s]

Reports:  23%|██▎       | 1603/7111 [06:23<1:12:47,  1.26it/s]

Reports:  23%|██▎       | 1604/7111 [06:24<56:43,  1.62it/s]

Reports:  23%|██▎       | 1605/7111 [06:24<44:57,  2.04it/s]

Reports:  23%|██▎       | 1606/7111 [06:25<1:09:53,  1.31it/s]

Reports:  23%|██▎       | 1607/7111 [06:25<54:35,  1.68it/s]

Reports:  23%|██▎       | 1608/7111 [06:26<43:37,  2.10it/s]

Reports:  23%|██▎       | 1609/7111 [06:26<36:12,  2.53it/s]

Reports:  23%|██▎       | 1610/7111 [06:26<31:03,  2.95it/s]

Reports:  23%|██▎       | 1611/7111 [06:26<27:03,  3.39it/s]

Reports:  23%|██▎       | 1612/7111 [06:26<24:03,  3.81it/s]

Reports:  23%|██▎       | 1613/7111 [06:27<22:09,  4.13it/s]

Reports:  23%|██▎       | 1614/7111 [06:27<21:03,  4.35it/s]

Reports:  23%|██▎       | 1615/7111 [06:27<20:16,  4.52it/s]

Reports:  23%|██▎       | 1616/7111 [06:27<19:46,  4.63it/s]

Reports:  23%|██▎       | 1617/7111 [06:28<34:58,  2.62it/s]

Reports:  23%|██▎       | 1618/7111 [06:28<30:06,  3.04it/s]

Reports:  23%|██▎       | 1619/7111 [06:28<26:07,  3.50it/s]

Reports:  23%|██▎       | 1620/7111 [06:29<23:49,  3.84it/s]

Reports:  23%|██▎       | 1621/7111 [06:29<22:00,  4.16it/s]

Reports:  23%|██▎       | 1622/7111 [06:29<20:50,  4.39it/s]

Reports:  23%|██▎       | 1623/7111 [06:29<20:06,  4.55it/s]

Reports:  23%|██▎       | 1624/7111 [06:30<25:27,  3.59it/s]

Reports:  23%|██▎       | 1625/7111 [06:30<23:28,  3.89it/s]

Reports:  23%|██▎       | 1626/7111 [06:30<21:49,  4.19it/s]

Reports:  23%|██▎       | 1627/7111 [06:31<35:17,  2.59it/s]

Reports:  23%|██▎       | 1628/7111 [06:31<30:04,  3.04it/s]

Reports:  23%|██▎       | 1629/7111 [06:31<26:29,  3.45it/s]

Reports:  23%|██▎       | 1630/7111 [06:33<1:10:03,  1.30it/s]

Reports:  23%|██▎       | 1631/7111 [06:33<54:58,  1.66it/s]

Reports:  23%|██▎       | 1632/7111 [06:34<50:32,  1.81it/s]

Reports:  23%|██▎       | 1633/7111 [06:34<40:49,  2.24it/s]

Reports:  23%|██▎       | 1634/7111 [06:34<34:09,  2.67it/s]

Reports:  23%|██▎       | 1635/7111 [06:34<33:33,  2.72it/s]

Reports:  23%|██▎       | 1636/7111 [06:35<28:36,  3.19it/s]

Reports:  23%|██▎       | 1637/7111 [06:36<47:19,  1.93it/s]

Reports:  23%|██▎       | 1638/7111 [06:36<38:48,  2.35it/s]

Reports:  23%|██▎       | 1639/7111 [06:38<1:33:40,  1.03s/it]

Reports:  23%|██▎       | 1640/7111 [06:39<1:26:22,  1.06it/s]

Reports:  23%|██▎       | 1641/7111 [06:39<1:05:56,  1.38it/s]

Reports:  23%|██▎       | 1642/7111 [06:39<51:33,  1.77it/s]

Reports:  23%|██▎       | 1643/7111 [06:42<1:45:11,  1.15s/it]

Reports:  23%|██▎       | 1644/7111 [06:42<1:19:12,  1.15it/s]

Reports:  23%|██▎       | 1645/7111 [06:42<1:00:45,  1.50it/s]

Reports:  23%|██▎       | 1646/7111 [06:42<47:39,  1.91it/s]

Reports:  23%|██▎       | 1647/7111 [06:43<38:38,  2.36it/s]

Reports:  23%|██▎       | 1648/7111 [06:44<50:47,  1.79it/s]

Reports:  23%|██▎       | 1649/7111 [06:44<52:12,  1.74it/s]

Reports:  23%|██▎       | 1650/7111 [06:44<42:22,  2.15it/s]

Reports:  23%|██▎       | 1651/7111 [06:45<58:22,  1.56it/s]

Reports:  23%|██▎       | 1652/7111 [06:46<1:08:24,  1.33it/s]

Reports:  23%|██▎       | 1653/7111 [06:47<53:29,  1.70it/s]

Reports:  23%|██▎       | 1654/7111 [06:47<43:07,  2.11it/s]

Reports:  23%|██▎       | 1655/7111 [06:47<35:44,  2.54it/s]

Reports:  23%|██▎       | 1656/7111 [06:47<30:22,  2.99it/s]

Reports:  23%|██▎       | 1657/7111 [06:48<44:01,  2.07it/s]

Reports:  23%|██▎       | 1658/7111 [06:48<36:06,  2.52it/s]

Reports:  23%|██▎       | 1659/7111 [06:49<42:54,  2.12it/s]

Reports:  23%|██▎       | 1660/7111 [06:49<45:13,  2.01it/s]

Reports:  23%|██▎       | 1661/7111 [06:50<37:02,  2.45it/s]

Reports:  23%|██▎       | 1662/7111 [06:50<31:11,  2.91it/s]

Reports:  23%|██▎       | 1663/7111 [06:50<27:17,  3.33it/s]

Reports:  23%|██▎       | 1664/7111 [06:50<24:10,  3.75it/s]

Reports:  23%|██▎       | 1665/7111 [06:50<22:25,  4.05it/s]

Reports:  23%|██▎       | 1666/7111 [06:52<48:56,  1.85it/s]

Reports:  23%|██▎       | 1667/7111 [06:52<39:53,  2.27it/s]

Reports:  23%|██▎       | 1668/7111 [06:52<35:18,  2.57it/s]

Reports:  23%|██▎       | 1669/7111 [06:52<29:47,  3.04it/s]

Reports:  23%|██▎       | 1670/7111 [06:53<27:58,  3.24it/s]

Reports:  23%|██▎       | 1671/7111 [06:53<25:12,  3.60it/s]

Reports:  24%|██▎       | 1672/7111 [06:53<23:09,  3.91it/s]

Reports:  24%|██▎       | 1673/7111 [06:54<34:53,  2.60it/s]

Reports:  24%|██▎       | 1674/7111 [06:54<29:35,  3.06it/s]

Reports:  24%|██▎       | 1675/7111 [06:54<25:53,  3.50it/s]

Reports:  24%|██▎       | 1676/7111 [06:54<24:03,  3.77it/s]

Reports:  24%|██▎       | 1677/7111 [06:54<21:47,  4.16it/s]

Reports:  24%|██▎       | 1678/7111 [06:55<20:20,  4.45it/s]

Reports:  24%|██▎       | 1679/7111 [06:55<19:36,  4.62it/s]

Reports:  24%|██▎       | 1680/7111 [06:55<18:54,  4.79it/s]

Reports:  24%|██▎       | 1681/7111 [06:55<18:33,  4.88it/s]

Reports:  24%|██▎       | 1682/7111 [06:55<18:21,  4.93it/s]

Reports:  24%|██▎       | 1683/7111 [06:56<18:15,  4.96it/s]

Reports:  24%|██▎       | 1684/7111 [06:56<17:54,  5.05it/s]

Reports:  24%|██▎       | 1685/7111 [06:56<17:41,  5.11it/s]

Reports:  24%|██▎       | 1686/7111 [06:56<17:18,  5.22it/s]

Reports:  24%|██▎       | 1687/7111 [06:57<20:23,  4.43it/s]

Reports:  24%|██▎       | 1688/7111 [06:57<31:58,  2.83it/s]

Reports:  24%|██▍       | 1689/7111 [06:57<30:17,  2.98it/s]

Reports:  24%|██▍       | 1690/7111 [06:58<26:35,  3.40it/s]

Reports:  24%|██▍       | 1691/7111 [06:58<36:35,  2.47it/s]

Reports:  24%|██▍       | 1692/7111 [07:01<1:24:59,  1.06it/s]

Reports:  24%|██▍       | 1693/7111 [07:01<1:04:47,  1.39it/s]

Reports:  24%|██▍       | 1694/7111 [07:01<50:59,  1.77it/s]

Reports:  24%|██▍       | 1695/7111 [07:01<41:34,  2.17it/s]

Reports:  24%|██▍       | 1696/7111 [07:01<34:28,  2.62it/s]

Reports:  24%|██▍       | 1697/7111 [07:02<33:13,  2.72it/s]

Reports:  24%|██▍       | 1698/7111 [07:02<28:45,  3.14it/s]

Reports:  24%|██▍       | 1699/7111 [07:02<25:18,  3.56it/s]

Reports:  24%|██▍       | 1700/7111 [07:02<23:19,  3.87it/s]

Reports:  24%|██▍       | 1701/7111 [07:02<21:22,  4.22it/s]

Reports:  24%|██▍       | 1702/7111 [07:03<20:07,  4.48it/s]

Reports:  24%|██▍       | 1703/7111 [07:03<19:48,  4.55it/s]

Reports:  24%|██▍       | 1704/7111 [07:05<1:00:08,  1.50it/s]

Reports:  24%|██▍       | 1705/7111 [07:08<2:13:17,  1.48s/it]

Reports:  24%|██▍       | 1706/7111 [07:09<2:04:26,  1.38s/it]

Reports:  24%|██▍       | 1707/7111 [07:09<1:32:32,  1.03s/it]

Reports:  24%|██▍       | 1708/7111 [07:10<1:19:10,  1.14it/s]

Reports:  24%|██▍       | 1709/7111 [07:10<1:00:33,  1.49it/s]

Reports:  24%|██▍       | 1710/7111 [07:10<47:41,  1.89it/s]

Reports:  24%|██▍       | 1711/7111 [07:10<38:43,  2.32it/s]

Reports:  24%|██▍       | 1712/7111 [07:11<50:16,  1.79it/s]

Reports:  24%|██▍       | 1713/7111 [07:11<40:59,  2.19it/s]

Reports:  24%|██▍       | 1714/7111 [07:12<34:25,  2.61it/s]

Reports:  24%|██▍       | 1715/7111 [07:12<29:32,  3.04it/s]

Reports:  24%|██▍       | 1716/7111 [07:12<26:39,  3.37it/s]

Reports:  24%|██▍       | 1717/7111 [07:12<23:46,  3.78it/s]

Reports:  24%|██▍       | 1718/7111 [07:13<22:15,  4.04it/s]

Reports:  24%|██▍       | 1719/7111 [07:13<20:55,  4.30it/s]

Reports:  24%|██▍       | 1720/7111 [07:13<27:19,  3.29it/s]

Reports:  24%|██▍       | 1721/7111 [07:13<24:27,  3.67it/s]

Reports:  24%|██▍       | 1722/7111 [07:14<22:48,  3.94it/s]

Reports:  24%|██▍       | 1723/7111 [07:14<27:18,  3.29it/s]

Reports:  24%|██▍       | 1724/7111 [07:14<24:49,  3.62it/s]

Reports:  24%|██▍       | 1725/7111 [07:14<22:34,  3.98it/s]

Reports:  24%|██▍       | 1726/7111 [07:15<27:47,  3.23it/s]

Reports:  24%|██▍       | 1727/7111 [07:15<24:44,  3.63it/s]

Reports:  24%|██▍       | 1728/7111 [07:15<22:36,  3.97it/s]

Reports:  24%|██▍       | 1729/7111 [07:15<20:53,  4.30it/s]

Reports:  24%|██▍       | 1730/7111 [07:16<19:51,  4.52it/s]

Reports:  24%|██▍       | 1731/7111 [07:16<19:04,  4.70it/s]

Reports:  24%|██▍       | 1732/7111 [07:16<25:29,  3.52it/s]

Reports:  24%|██▍       | 1733/7111 [07:17<31:05,  2.88it/s]

Reports:  24%|██▍       | 1734/7111 [07:17<26:57,  3.32it/s]

Reports:  24%|██▍       | 1735/7111 [07:18<34:16,  2.61it/s]

Reports:  24%|██▍       | 1736/7111 [07:18<29:39,  3.02it/s]

Reports:  24%|██▍       | 1737/7111 [07:18<26:25,  3.39it/s]

Reports:  24%|██▍       | 1738/7111 [07:18<25:21,  3.53it/s]

Reports:  24%|██▍       | 1739/7111 [07:18<22:50,  3.92it/s]

Reports:  24%|██▍       | 1740/7111 [07:19<21:19,  4.20it/s]

Reports:  24%|██▍       | 1741/7111 [07:19<20:05,  4.45it/s]

Reports:  24%|██▍       | 1742/7111 [07:19<19:06,  4.68it/s]

Reports:  25%|██▍       | 1743/7111 [07:19<18:31,  4.83it/s]

Reports:  25%|██▍       | 1744/7111 [07:20<26:57,  3.32it/s]

Reports:  25%|██▍       | 1745/7111 [07:20<23:59,  3.73it/s]

Reports:  25%|██▍       | 1746/7111 [07:20<22:22,  4.00it/s]

Reports:  25%|██▍       | 1747/7111 [07:20<20:44,  4.31it/s]

Reports:  25%|██▍       | 1748/7111 [07:21<43:48,  2.04it/s]

Reports:  25%|██▍       | 1749/7111 [07:22<36:06,  2.47it/s]

Reports:  25%|██▍       | 1750/7111 [07:22<30:15,  2.95it/s]

Reports:  25%|██▍       | 1751/7111 [07:22<26:15,  3.40it/s]

Reports:  25%|██▍       | 1752/7111 [07:22<23:56,  3.73it/s]

Reports:  25%|██▍       | 1753/7111 [07:22<21:52,  4.08it/s]

Reports:  25%|██▍       | 1754/7111 [07:23<20:31,  4.35it/s]

Reports:  25%|██▍       | 1755/7111 [07:23<19:22,  4.61it/s]

Reports:  25%|██▍       | 1756/7111 [07:23<18:36,  4.80it/s]

Reports:  25%|██▍       | 1757/7111 [07:23<18:21,  4.86it/s]

Reports:  25%|██▍       | 1758/7111 [07:23<18:27,  4.83it/s]

Reports:  25%|██▍       | 1759/7111 [07:24<18:36,  4.79it/s]

Reports:  25%|██▍       | 1760/7111 [07:24<18:18,  4.87it/s]

Reports:  25%|██▍       | 1761/7111 [07:24<17:51,  4.99it/s]

Reports:  25%|██▍       | 1762/7111 [07:24<17:36,  5.06it/s]

Reports:  25%|██▍       | 1763/7111 [07:27<1:15:49,  1.18it/s]

Reports:  25%|██▍       | 1764/7111 [07:27<58:27,  1.52it/s]

Reports:  25%|██▍       | 1765/7111 [07:27<46:11,  1.93it/s]

Reports:  25%|██▍       | 1766/7111 [07:27<37:40,  2.36it/s]

Reports:  25%|██▍       | 1767/7111 [07:30<1:31:06,  1.02s/it]

Reports:  25%|██▍       | 1768/7111 [07:30<1:26:24,  1.03it/s]

Reports:  25%|██▍       | 1769/7111 [07:31<1:15:33,  1.18it/s]

Reports:  25%|██▍       | 1770/7111 [07:31<58:24,  1.52it/s]

Reports:  25%|██▍       | 1771/7111 [07:31<46:18,  1.92it/s]

Reports:  25%|██▍       | 1772/7111 [07:32<37:49,  2.35it/s]

Reports:  25%|██▍       | 1773/7111 [07:32<49:41,  1.79it/s]

Reports:  25%|██▍       | 1774/7111 [07:33<39:50,  2.23it/s]

Reports:  25%|██▍       | 1775/7111 [07:33<33:13,  2.68it/s]

Reports:  25%|██▍       | 1776/7111 [07:33<28:16,  3.14it/s]

Reports:  25%|██▍       | 1777/7111 [07:33<24:56,  3.56it/s]

Reports:  25%|██▌       | 1778/7111 [07:34<39:20,  2.26it/s]

Reports:  25%|██▌       | 1779/7111 [07:34<32:53,  2.70it/s]

Reports:  25%|██▌       | 1780/7111 [07:34<28:09,  3.16it/s]

Reports:  25%|██▌       | 1781/7111 [07:35<25:09,  3.53it/s]

Reports:  25%|██▌       | 1782/7111 [07:35<23:14,  3.82it/s]

Reports:  25%|██▌       | 1783/7111 [07:35<21:14,  4.18it/s]

Reports:  25%|██▌       | 1784/7111 [07:35<20:11,  4.40it/s]

Reports:  25%|██▌       | 1785/7111 [07:35<19:41,  4.51it/s]

Reports:  25%|██▌       | 1786/7111 [07:36<19:34,  4.53it/s]

Reports:  25%|██▌       | 1787/7111 [07:36<18:40,  4.75it/s]

Reports:  25%|██▌       | 1788/7111 [07:37<48:17,  1.84it/s]

Reports:  25%|██▌       | 1789/7111 [07:37<39:07,  2.27it/s]

Reports:  25%|██▌       | 1790/7111 [07:38<32:58,  2.69it/s]

Reports:  25%|██▌       | 1791/7111 [07:38<28:07,  3.15it/s]

Reports:  25%|██▌       | 1792/7111 [07:38<24:51,  3.57it/s]

Reports:  25%|██▌       | 1793/7111 [07:38<22:18,  3.97it/s]

Reports:  25%|██▌       | 1794/7111 [07:38<21:08,  4.19it/s]

Reports:  25%|██▌       | 1795/7111 [07:39<19:47,  4.48it/s]

Reports:  25%|██▌       | 1796/7111 [07:40<45:54,  1.93it/s]

Reports:  25%|██▌       | 1797/7111 [07:41<1:12:07,  1.23it/s]

Reports:  25%|██▌       | 1798/7111 [07:42<1:09:47,  1.27it/s]

Reports:  25%|██▌       | 1799/7111 [07:42<1:01:03,  1.45it/s]

Reports:  25%|██▌       | 1800/7111 [07:43<47:43,  1.85it/s]

Reports:  25%|██▌       | 1801/7111 [07:43<38:29,  2.30it/s]

Reports:  25%|██▌       | 1802/7111 [07:43<32:05,  2.76it/s]

Reports:  25%|██▌       | 1803/7111 [07:43<27:31,  3.21it/s]

Reports:  25%|██▌       | 1804/7111 [07:43<24:36,  3.59it/s]

Reports:  25%|██▌       | 1805/7111 [07:44<22:40,  3.90it/s]

Reports:  25%|██▌       | 1806/7111 [07:44<21:08,  4.18it/s]

Reports:  25%|██▌       | 1807/7111 [07:44<20:06,  4.40it/s]

Reports:  25%|██▌       | 1808/7111 [07:44<19:32,  4.52it/s]

Reports:  25%|██▌       | 1809/7111 [07:44<18:48,  4.70it/s]

Reports:  25%|██▌       | 1810/7111 [07:45<19:05,  4.63it/s]

Reports:  25%|██▌       | 1811/7111 [07:45<19:00,  4.65it/s]

Reports:  25%|██▌       | 1812/7111 [07:45<30:21,  2.91it/s]

Reports:  25%|██▌       | 1813/7111 [07:46<26:17,  3.36it/s]

Reports:  26%|██▌       | 1814/7111 [07:46<23:33,  3.75it/s]

Reports:  26%|██▌       | 1815/7111 [07:46<21:41,  4.07it/s]

Reports:  26%|██▌       | 1816/7111 [07:46<20:12,  4.37it/s]

Reports:  26%|██▌       | 1817/7111 [07:46<19:21,  4.56it/s]

Reports:  26%|██▌       | 1818/7111 [07:47<21:52,  4.03it/s]

Reports:  26%|██▌       | 1819/7111 [07:48<45:00,  1.96it/s]

Reports:  26%|██▌       | 1820/7111 [07:48<36:57,  2.39it/s]

Reports:  26%|██▌       | 1821/7111 [07:48<33:49,  2.61it/s]

Reports:  26%|██▌       | 1822/7111 [07:49<29:48,  2.96it/s]

Reports:  26%|██▌       | 1823/7111 [07:49<26:05,  3.38it/s]

Reports:  26%|██▌       | 1824/7111 [07:49<23:22,  3.77it/s]

Reports:  26%|██▌       | 1825/7111 [07:49<21:42,  4.06it/s]

Reports:  26%|██▌       | 1826/7111 [07:49<20:27,  4.30it/s]

Reports:  26%|██▌       | 1827/7111 [07:50<19:19,  4.56it/s]

Reports:  26%|██▌       | 1828/7111 [07:50<19:04,  4.62it/s]

Reports:  26%|██▌       | 1829/7111 [07:50<18:33,  4.74it/s]

Reports:  26%|██▌       | 1830/7111 [07:51<37:50,  2.33it/s]

Reports:  26%|██▌       | 1831/7111 [07:51<31:56,  2.76it/s]

Reports:  26%|██▌       | 1832/7111 [07:52<38:14,  2.30it/s]

Reports:  26%|██▌       | 1833/7111 [07:52<32:02,  2.75it/s]

Reports:  26%|██▌       | 1834/7111 [07:52<27:53,  3.15it/s]

Reports:  26%|██▌       | 1835/7111 [07:52<24:38,  3.57it/s]

Reports:  26%|██▌       | 1836/7111 [07:53<22:21,  3.93it/s]

Reports:  26%|██▌       | 1837/7111 [07:53<38:55,  2.26it/s]

Reports:  26%|██▌       | 1838/7111 [07:54<34:03,  2.58it/s]

Reports:  26%|██▌       | 1839/7111 [07:54<36:29,  2.41it/s]

Reports:  26%|██▌       | 1840/7111 [07:54<30:43,  2.86it/s]

Reports:  26%|██▌       | 1841/7111 [07:55<26:37,  3.30it/s]

Reports:  26%|██▌       | 1842/7111 [07:56<49:06,  1.79it/s]

Reports:  26%|██▌       | 1843/7111 [07:57<1:13:22,  1.20it/s]

Reports:  26%|██▌       | 1844/7111 [07:59<1:35:55,  1.09s/it]

Reports:  26%|██▌       | 1845/7111 [07:59<1:12:52,  1.20it/s]

Reports:  26%|██▌       | 1846/7111 [07:59<56:13,  1.56it/s]

Reports:  26%|██▌       | 1847/7111 [08:00<44:31,  1.97it/s]

Reports:  26%|██▌       | 1848/7111 [08:02<1:31:37,  1.04s/it]

Reports:  26%|██▌       | 1849/7111 [08:02<1:16:14,  1.15it/s]

Reports:  26%|██▌       | 1850/7111 [08:02<58:20,  1.50it/s]

Reports:  26%|██▌       | 1851/7111 [08:03<55:07,  1.59it/s]

Reports:  26%|██▌       | 1852/7111 [08:04<52:14,  1.68it/s]

Reports:  26%|██▌       | 1853/7111 [08:04<41:44,  2.10it/s]

Reports:  26%|██▌       | 1854/7111 [08:04<34:32,  2.54it/s]

Reports:  26%|██▌       | 1855/7111 [08:04<36:03,  2.43it/s]

Reports:  26%|██▌       | 1856/7111 [08:05<33:29,  2.61it/s]

Reports:  26%|██▌       | 1857/7111 [08:05<43:40,  2.01it/s]

Reports:  26%|██▌       | 1858/7111 [08:06<35:34,  2.46it/s]

Reports:  26%|██▌       | 1859/7111 [08:07<1:00:06,  1.46it/s]

Reports:  26%|██▌       | 1860/7111 [08:07<47:27,  1.84it/s]

Reports:  26%|██▌       | 1861/7111 [08:08<45:10,  1.94it/s]

Reports:  26%|██▌       | 1862/7111 [08:08<36:48,  2.38it/s]

Reports:  26%|██▌       | 1863/7111 [08:08<30:42,  2.85it/s]

Reports:  26%|██▌       | 1864/7111 [08:08<27:22,  3.19it/s]

Reports:  26%|██▌       | 1865/7111 [08:08<24:39,  3.55it/s]

Reports:  26%|██▌       | 1866/7111 [08:09<22:23,  3.90it/s]

Reports:  26%|██▋       | 1867/7111 [08:09<20:51,  4.19it/s]

Reports:  26%|██▋       | 1868/7111 [08:09<19:33,  4.47it/s]

Reports:  26%|██▋       | 1869/7111 [08:09<20:43,  4.22it/s]

Reports:  26%|██▋       | 1870/7111 [08:10<19:55,  4.38it/s]

Reports:  26%|██▋       | 1871/7111 [08:10<20:38,  4.23it/s]

Reports:  26%|██▋       | 1872/7111 [08:11<34:45,  2.51it/s]

Reports:  26%|██▋       | 1873/7111 [08:11<29:13,  2.99it/s]

Reports:  26%|██▋       | 1874/7111 [08:11<25:19,  3.45it/s]

Reports:  26%|██▋       | 1875/7111 [08:12<49:06,  1.78it/s]

Reports:  26%|██▋       | 1876/7111 [08:13<1:05:11,  1.34it/s]

Reports:  26%|██▋       | 1877/7111 [08:14<50:48,  1.72it/s]

Reports:  26%|██▋       | 1878/7111 [08:14<40:45,  2.14it/s]

Reports:  26%|██▋       | 1879/7111 [08:14<33:28,  2.61it/s]

Reports:  26%|██▋       | 1880/7111 [08:14<29:21,  2.97it/s]

Reports:  26%|██▋       | 1881/7111 [08:14<25:43,  3.39it/s]

Reports:  26%|██▋       | 1882/7111 [08:15<23:32,  3.70it/s]

Reports:  26%|██▋       | 1883/7111 [08:15<22:03,  3.95it/s]

Reports:  26%|██▋       | 1884/7111 [08:15<20:40,  4.21it/s]

Reports:  27%|██▋       | 1885/7111 [08:15<24:18,  3.58it/s]

Reports:  27%|██▋       | 1886/7111 [08:16<40:11,  2.17it/s]

Reports:  27%|██▋       | 1887/7111 [08:16<33:25,  2.60it/s]

Reports:  27%|██▋       | 1888/7111 [08:17<34:43,  2.51it/s]

Reports:  27%|██▋       | 1889/7111 [08:17<29:37,  2.94it/s]

Reports:  27%|██▋       | 1890/7111 [08:17<25:57,  3.35it/s]

Reports:  27%|██▋       | 1891/7111 [08:19<52:08,  1.67it/s]

Reports:  27%|██▋       | 1892/7111 [08:19<56:32,  1.54it/s]

Reports:  27%|██▋       | 1893/7111 [08:20<57:54,  1.50it/s]

Reports:  27%|██▋       | 1894/7111 [08:21<1:03:04,  1.38it/s]

Reports:  27%|██▋       | 1895/7111 [08:21<49:25,  1.76it/s]

Reports:  27%|██▋       | 1896/7111 [08:21<40:03,  2.17it/s]

Reports:  27%|██▋       | 1897/7111 [08:23<1:20:23,  1.08it/s]

Reports:  27%|██▋       | 1898/7111 [08:24<1:10:21,  1.23it/s]

Reports:  27%|██▋       | 1899/7111 [08:24<54:11,  1.60it/s]

Reports:  27%|██▋       | 1900/7111 [08:25<56:02,  1.55it/s]

Reports:  27%|██▋       | 1901/7111 [08:25<44:18,  1.96it/s]

Reports:  27%|██▋       | 1902/7111 [08:25<36:11,  2.40it/s]

Reports:  27%|██▋       | 1903/7111 [08:26<40:10,  2.16it/s]

Reports:  27%|██▋       | 1904/7111 [08:26<33:43,  2.57it/s]

Reports:  27%|██▋       | 1905/7111 [08:26<29:00,  2.99it/s]

Reports:  27%|██▋       | 1906/7111 [08:27<30:52,  2.81it/s]

Reports:  27%|██▋       | 1907/7111 [08:28<50:19,  1.72it/s]

Reports:  27%|██▋       | 1908/7111 [08:28<40:56,  2.12it/s]

Reports:  27%|██▋       | 1909/7111 [08:28<33:48,  2.56it/s]

Reports:  27%|██▋       | 1910/7111 [08:29<44:33,  1.95it/s]

Reports:  27%|██▋       | 1911/7111 [08:29<36:33,  2.37it/s]

Reports:  27%|██▋       | 1912/7111 [08:29<30:42,  2.82it/s]

Reports:  27%|██▋       | 1913/7111 [08:29<26:21,  3.29it/s]

Reports:  27%|██▋       | 1914/7111 [08:30<23:29,  3.69it/s]

Reports:  27%|██▋       | 1915/7111 [08:30<21:22,  4.05it/s]

Reports:  27%|██▋       | 1916/7111 [08:30<23:30,  3.68it/s]

Reports:  27%|██▋       | 1917/7111 [08:31<38:16,  2.26it/s]

Reports:  27%|██▋       | 1918/7111 [08:31<33:09,  2.61it/s]

Reports:  27%|██▋       | 1919/7111 [08:31<28:36,  3.03it/s]

Reports:  27%|██▋       | 1920/7111 [08:32<25:02,  3.46it/s]

Reports:  27%|██▋       | 1921/7111 [08:33<43:40,  1.98it/s]

Reports:  27%|██▋       | 1922/7111 [08:33<36:25,  2.37it/s]

Reports:  27%|██▋       | 1923/7111 [08:34<43:56,  1.97it/s]

Reports:  27%|██▋       | 1924/7111 [08:34<36:08,  2.39it/s]

Reports:  27%|██▋       | 1925/7111 [08:34<41:59,  2.06it/s]

Reports:  27%|██▋       | 1926/7111 [08:35<34:20,  2.52it/s]

Reports:  27%|██▋       | 1927/7111 [08:35<29:16,  2.95it/s]

Reports:  27%|██▋       | 1928/7111 [08:35<33:58,  2.54it/s]

Reports:  27%|██▋       | 1929/7111 [08:36<31:46,  2.72it/s]

Reports:  27%|██▋       | 1930/7111 [08:36<27:18,  3.16it/s]

Reports:  27%|██▋       | 1931/7111 [08:36<24:15,  3.56it/s]

Reports:  27%|██▋       | 1932/7111 [08:36<21:54,  3.94it/s]

Reports:  27%|██▋       | 1933/7111 [08:36<20:29,  4.21it/s]

Reports:  27%|██▋       | 1934/7111 [08:37<19:16,  4.48it/s]

Reports:  27%|██▋       | 1935/7111 [08:37<18:19,  4.71it/s]

Reports:  27%|██▋       | 1936/7111 [08:37<17:45,  4.86it/s]

Reports:  27%|██▋       | 1937/7111 [08:37<17:42,  4.87it/s]

Reports:  27%|██▋       | 1938/7111 [08:39<1:03:09,  1.37it/s]

Reports:  27%|██▋       | 1939/7111 [08:39<49:43,  1.73it/s]

Reports:  27%|██▋       | 1940/7111 [08:40<40:31,  2.13it/s]

Reports:  27%|██▋       | 1941/7111 [08:40<41:41,  2.07it/s]

Reports:  27%|██▋       | 1942/7111 [08:40<34:14,  2.52it/s]

Reports:  27%|██▋       | 1943/7111 [08:41<44:23,  1.94it/s]

Reports:  27%|██▋       | 1944/7111 [08:41<35:54,  2.40it/s]

Reports:  27%|██▋       | 1945/7111 [08:42<30:11,  2.85it/s]

Reports:  27%|██▋       | 1946/7111 [08:42<26:01,  3.31it/s]

Reports:  27%|██▋       | 1947/7111 [08:42<23:25,  3.67it/s]

Reports:  27%|██▋       | 1948/7111 [08:42<27:08,  3.17it/s]

Reports:  27%|██▋       | 1949/7111 [08:43<32:05,  2.68it/s]

Reports:  27%|██▋       | 1950/7111 [08:43<27:33,  3.12it/s]

Reports:  27%|██▋       | 1951/7111 [08:43<24:35,  3.50it/s]

Reports:  27%|██▋       | 1952/7111 [08:44<33:48,  2.54it/s]

Reports:  27%|██▋       | 1953/7111 [08:45<53:30,  1.61it/s]

Reports:  27%|██▋       | 1954/7111 [08:45<42:49,  2.01it/s]

Reports:  27%|██▋       | 1955/7111 [08:45<34:49,  2.47it/s]

Reports:  28%|██▊       | 1956/7111 [08:46<29:07,  2.95it/s]

Reports:  28%|██▊       | 1957/7111 [08:46<25:17,  3.40it/s]

Reports:  28%|██▊       | 1958/7111 [08:46<22:34,  3.80it/s]

Reports:  28%|██▊       | 1959/7111 [08:46<20:56,  4.10it/s]

Reports:  28%|██▊       | 1960/7111 [08:46<19:55,  4.31it/s]

Reports:  28%|██▊       | 1961/7111 [08:47<19:00,  4.52it/s]

Reports:  28%|██▊       | 1962/7111 [08:47<18:28,  4.65it/s]

Reports:  28%|██▊       | 1963/7111 [08:47<18:07,  4.73it/s]

Reports:  28%|██▊       | 1964/7111 [08:47<17:37,  4.87it/s]

Reports:  28%|██▊       | 1965/7111 [08:47<17:41,  4.85it/s]

Reports:  28%|██▊       | 1966/7111 [08:48<17:49,  4.81it/s]

Reports:  28%|██▊       | 1967/7111 [08:48<23:08,  3.70it/s]

Reports:  28%|██▊       | 1968/7111 [08:48<20:59,  4.08it/s]

Reports:  28%|██▊       | 1969/7111 [08:49<28:05,  3.05it/s]

Reports:  28%|██▊       | 1970/7111 [08:49<24:43,  3.47it/s]

Reports:  28%|██▊       | 1971/7111 [08:49<22:44,  3.77it/s]

Reports:  28%|██▊       | 1972/7111 [08:49<21:15,  4.03it/s]

Reports:  28%|██▊       | 1973/7111 [08:50<23:38,  3.62it/s]

Reports:  28%|██▊       | 1974/7111 [08:50<21:44,  3.94it/s]

Reports:  28%|██▊       | 1975/7111 [08:50<20:23,  4.20it/s]

Reports:  28%|██▊       | 1976/7111 [08:50<19:24,  4.41it/s]

Reports:  28%|██▊       | 1977/7111 [08:51<19:04,  4.48it/s]

Reports:  28%|██▊       | 1978/7111 [08:51<18:28,  4.63it/s]

Reports:  28%|██▊       | 1979/7111 [08:51<17:46,  4.81it/s]

Reports:  28%|██▊       | 1980/7111 [08:51<17:23,  4.92it/s]

Reports:  28%|██▊       | 1981/7111 [08:51<17:01,  5.02it/s]

Reports:  28%|██▊       | 1982/7111 [08:51<16:39,  5.13it/s]

Reports:  28%|██▊       | 1983/7111 [08:52<16:53,  5.06it/s]

Reports:  28%|██▊       | 1984/7111 [08:52<16:35,  5.15it/s]

Reports:  28%|██▊       | 1985/7111 [08:52<16:32,  5.17it/s]

Reports:  28%|██▊       | 1986/7111 [08:52<16:53,  5.06it/s]

Reports:  28%|██▊       | 1987/7111 [08:53<31:31,  2.71it/s]

Reports:  28%|██▊       | 1988/7111 [08:53<26:53,  3.17it/s]

Reports:  28%|██▊       | 1989/7111 [08:53<23:57,  3.56it/s]

Reports:  28%|██▊       | 1990/7111 [08:54<21:44,  3.93it/s]

Reports:  28%|██▊       | 1991/7111 [08:54<19:55,  4.28it/s]

Reports:  28%|██▊       | 1992/7111 [08:54<18:58,  4.50it/s]

Reports:  28%|██▊       | 1993/7111 [08:54<17:58,  4.75it/s]

Reports:  28%|██▊       | 1994/7111 [08:54<17:36,  4.84it/s]

Reports:  28%|██▊       | 1995/7111 [08:55<18:07,  4.70it/s]

Reports:  28%|██▊       | 1996/7111 [08:55<17:26,  4.89it/s]

Reports:  28%|██▊       | 1997/7111 [08:56<42:02,  2.03it/s]

Reports:  28%|██▊       | 1998/7111 [08:56<34:09,  2.50it/s]

Reports:  28%|██▊       | 1999/7111 [08:56<28:59,  2.94it/s]

Reports:  28%|██▊       | 2000/7111 [08:57<25:25,  3.35it/s]

Reports:  28%|██▊       | 2001/7111 [08:57<22:39,  3.76it/s]

Reports:  28%|██▊       | 2002/7111 [08:57<20:40,  4.12it/s]

Reports:  28%|██▊       | 2003/7111 [08:57<19:53,  4.28it/s]

Reports:  28%|██▊       | 2004/7111 [08:57<18:58,  4.49it/s]

Reports:  28%|██▊       | 2005/7111 [08:58<17:59,  4.73it/s]

Reports:  28%|██▊       | 2006/7111 [08:58<17:40,  4.81it/s]

Reports:  28%|██▊       | 2007/7111 [08:58<17:27,  4.87it/s]

Reports:  28%|██▊       | 2008/7111 [08:58<17:07,  4.97it/s]

Reports:  28%|██▊       | 2009/7111 [08:58<17:03,  4.99it/s]

Reports:  28%|██▊       | 2010/7111 [08:58<16:58,  5.01it/s]

Reports:  28%|██▊       | 2011/7111 [08:59<16:34,  5.13it/s]

Reports:  28%|██▊       | 2012/7111 [08:59<16:37,  5.11it/s]

Reports:  28%|██▊       | 2013/7111 [08:59<16:32,  5.14it/s]

Reports:  28%|██▊       | 2014/7111 [08:59<16:24,  5.18it/s]

Reports:  28%|██▊       | 2015/7111 [08:59<16:18,  5.21it/s]

Reports:  28%|██▊       | 2016/7111 [09:00<16:28,  5.15it/s]

Reports:  28%|██▊       | 2017/7111 [09:00<16:17,  5.21it/s]

Reports:  28%|██▊       | 2018/7111 [09:00<17:11,  4.94it/s]

Reports:  28%|██▊       | 2019/7111 [09:00<17:06,  4.96it/s]

Reports:  28%|██▊       | 2020/7111 [09:00<16:56,  5.01it/s]

Reports:  28%|██▊       | 2021/7111 [09:01<17:05,  4.97it/s]

Reports:  28%|██▊       | 2022/7111 [09:01<16:49,  5.04it/s]

Reports:  28%|██▊       | 2023/7111 [09:01<16:36,  5.11it/s]

Reports:  28%|██▊       | 2024/7111 [09:01<16:25,  5.16it/s]

Reports:  28%|██▊       | 2025/7111 [09:01<16:36,  5.10it/s]

Reports:  28%|██▊       | 2026/7111 [09:02<16:37,  5.10it/s]

Reports:  29%|██▊       | 2027/7111 [09:02<16:31,  5.13it/s]

Reports:  29%|██▊       | 2028/7111 [09:02<24:09,  3.51it/s]

Reports:  29%|██▊       | 2029/7111 [09:03<21:55,  3.86it/s]

Reports:  29%|██▊       | 2030/7111 [09:03<20:07,  4.21it/s]

Reports:  29%|██▊       | 2031/7111 [09:03<19:02,  4.45it/s]

Reports:  29%|██▊       | 2032/7111 [09:03<18:27,  4.59it/s]

Reports:  29%|██▊       | 2033/7111 [09:03<18:11,  4.65it/s]

Reports:  29%|██▊       | 2034/7111 [09:04<40:24,  2.09it/s]

Reports:  29%|██▊       | 2035/7111 [09:05<32:52,  2.57it/s]

Reports:  29%|██▊       | 2036/7111 [09:05<27:41,  3.05it/s]

Reports:  29%|██▊       | 2037/7111 [09:05<24:55,  3.39it/s]

Reports:  29%|██▊       | 2038/7111 [09:05<22:14,  3.80it/s]

Reports:  29%|██▊       | 2039/7111 [09:05<20:25,  4.14it/s]

Reports:  29%|██▊       | 2040/7111 [09:06<19:11,  4.40it/s]

Reports:  29%|██▊       | 2041/7111 [09:06<18:07,  4.66it/s]

Reports:  29%|██▊       | 2042/7111 [09:06<17:45,  4.76it/s]

Reports:  29%|██▊       | 2043/7111 [09:06<17:20,  4.87it/s]

Reports:  29%|██▊       | 2044/7111 [09:06<16:47,  5.03it/s]

Reports:  29%|██▉       | 2045/7111 [09:07<16:39,  5.07it/s]

Reports:  29%|██▉       | 2046/7111 [09:07<17:57,  4.70it/s]

Reports:  29%|██▉       | 2047/7111 [09:07<17:30,  4.82it/s]

Reports:  29%|██▉       | 2048/7111 [09:07<17:24,  4.85it/s]

Reports:  29%|██▉       | 2049/7111 [09:07<17:05,  4.94it/s]

Reports:  29%|██▉       | 2050/7111 [09:08<16:47,  5.02it/s]

Reports:  29%|██▉       | 2051/7111 [09:08<16:46,  5.03it/s]

Reports:  29%|██▉       | 2052/7111 [09:08<16:43,  5.04it/s]

Reports:  29%|██▉       | 2053/7111 [09:08<16:33,  5.09it/s]

Reports:  29%|██▉       | 2054/7111 [09:08<16:43,  5.04it/s]

Reports:  29%|██▉       | 2055/7111 [09:09<16:50,  5.00it/s]

Reports:  29%|██▉       | 2056/7111 [09:09<17:04,  4.93it/s]

Reports:  29%|██▉       | 2057/7111 [09:09<16:55,  4.98it/s]

Reports:  29%|██▉       | 2058/7111 [09:09<16:29,  5.10it/s]

Reports:  29%|██▉       | 2059/7111 [09:09<17:01,  4.94it/s]

Reports:  29%|██▉       | 2060/7111 [09:10<17:01,  4.94it/s]

Reports:  29%|██▉       | 2061/7111 [09:10<16:43,  5.03it/s]

Reports:  29%|██▉       | 2062/7111 [09:10<16:56,  4.97it/s]

Reports:  29%|██▉       | 2063/7111 [09:10<16:53,  4.98it/s]

Reports:  29%|██▉       | 2064/7111 [09:10<16:37,  5.06it/s]

Reports:  29%|██▉       | 2065/7111 [09:11<16:51,  4.99it/s]

Reports:  29%|██▉       | 2066/7111 [09:11<16:48,  5.00it/s]

Reports:  29%|██▉       | 2067/7111 [09:11<16:51,  4.99it/s]

Reports:  29%|██▉       | 2068/7111 [09:11<16:38,  5.05it/s]

Reports:  29%|██▉       | 2069/7111 [09:11<16:45,  5.01it/s]

Reports:  29%|██▉       | 2070/7111 [09:12<16:34,  5.07it/s]

Reports:  29%|██▉       | 2071/7111 [09:12<16:51,  4.98it/s]

Reports:  29%|██▉       | 2072/7111 [09:12<16:31,  5.08it/s]

Reports:  29%|██▉       | 2073/7111 [09:12<16:29,  5.09it/s]

Reports:  29%|██▉       | 2074/7111 [09:12<16:18,  5.15it/s]

Reports:  29%|██▉       | 2075/7111 [09:12<16:01,  5.24it/s]

Reports:  29%|██▉       | 2076/7111 [09:13<16:29,  5.09it/s]

Reports:  29%|██▉       | 2077/7111 [09:13<16:16,  5.15it/s]

Reports:  29%|██▉       | 2078/7111 [09:13<16:36,  5.05it/s]

Reports:  29%|██▉       | 2079/7111 [09:13<16:17,  5.15it/s]

Reports:  29%|██▉       | 2080/7111 [09:13<16:16,  5.15it/s]

Reports:  29%|██▉       | 2081/7111 [09:14<16:03,  5.22it/s]

Reports:  29%|██▉       | 2082/7111 [09:14<16:03,  5.22it/s]

Reports:  29%|██▉       | 2083/7111 [09:14<16:18,  5.14it/s]

Reports:  29%|██▉       | 2084/7111 [09:14<16:23,  5.11it/s]

Reports:  29%|██▉       | 2085/7111 [09:14<16:35,  5.05it/s]

Reports:  29%|██▉       | 2086/7111 [09:15<16:51,  4.97it/s]

Reports:  29%|██▉       | 2087/7111 [09:15<16:56,  4.94it/s]

Reports:  29%|██▉       | 2088/7111 [09:15<16:58,  4.93it/s]

Reports:  29%|██▉       | 2089/7111 [09:15<16:40,  5.02it/s]

Reports:  29%|██▉       | 2090/7111 [09:15<16:47,  4.99it/s]

Reports:  29%|██▉       | 2091/7111 [09:16<16:39,  5.02it/s]

Reports:  29%|██▉       | 2092/7111 [09:16<16:58,  4.93it/s]

Reports:  29%|██▉       | 2093/7111 [09:16<17:00,  4.92it/s]

Reports:  29%|██▉       | 2094/7111 [09:16<16:37,  5.03it/s]

Reports:  29%|██▉       | 2095/7111 [09:16<16:10,  5.17it/s]

Reports:  29%|██▉       | 2096/7111 [09:17<16:17,  5.13it/s]

Reports:  29%|██▉       | 2097/7111 [09:17<16:37,  5.03it/s]

Reports:  30%|██▉       | 2098/7111 [09:17<16:43,  5.00it/s]

Reports:  30%|██▉       | 2099/7111 [09:17<16:36,  5.03it/s]

Reports:  30%|██▉       | 2100/7111 [09:17<16:40,  5.01it/s]

Reports:  30%|██▉       | 2101/7111 [09:18<19:40,  4.24it/s]

Reports:  30%|██▉       | 2102/7111 [09:18<19:19,  4.32it/s]

Reports:  30%|██▉       | 2103/7111 [09:18<18:11,  4.59it/s]

Reports:  30%|██▉       | 2104/7111 [09:18<17:34,  4.75it/s]

Reports:  30%|██▉       | 2105/7111 [09:19<17:17,  4.83it/s]

Reports:  30%|██▉       | 2106/7111 [09:19<17:08,  4.87it/s]

Reports:  30%|██▉       | 2107/7111 [09:19<17:02,  4.90it/s]

Reports:  30%|██▉       | 2108/7111 [09:19<17:01,  4.90it/s]

Reports:  30%|██▉       | 2109/7111 [09:19<17:09,  4.86it/s]

Reports:  30%|██▉       | 2110/7111 [09:20<17:09,  4.86it/s]

Reports:  30%|██▉       | 2111/7111 [09:20<16:55,  4.92it/s]

Reports:  30%|██▉       | 2112/7111 [09:20<16:28,  5.06it/s]

Reports:  30%|██▉       | 2113/7111 [09:20<16:17,  5.11it/s]

Reports:  30%|██▉       | 2114/7111 [09:20<16:21,  5.09it/s]

Reports:  30%|██▉       | 2115/7111 [09:21<16:08,  5.16it/s]

Reports:  30%|██▉       | 2116/7111 [09:21<16:08,  5.16it/s]

Reports:  30%|██▉       | 2117/7111 [09:21<16:16,  5.11it/s]

Reports:  30%|██▉       | 2118/7111 [09:21<16:00,  5.20it/s]

Reports:  30%|██▉       | 2119/7111 [09:21<16:27,  5.06it/s]

Reports:  30%|██▉       | 2120/7111 [09:22<16:38,  5.00it/s]

Reports:  30%|██▉       | 2121/7111 [09:22<16:26,  5.06it/s]

Reports:  30%|██▉       | 2122/7111 [09:22<16:13,  5.12it/s]

Reports:  30%|██▉       | 2123/7111 [09:22<16:05,  5.16it/s]

Reports:  30%|██▉       | 2124/7111 [09:22<16:05,  5.17it/s]

Reports:  30%|██▉       | 2125/7111 [09:23<16:06,  5.16it/s]

Reports:  30%|██▉       | 2126/7111 [09:23<16:06,  5.16it/s]

Reports:  30%|██▉       | 2127/7111 [09:23<15:54,  5.22it/s]

Reports:  30%|██▉       | 2128/7111 [09:23<16:12,  5.12it/s]

Reports:  30%|██▉       | 2129/7111 [09:23<16:02,  5.18it/s]

Reports:  30%|██▉       | 2130/7111 [09:24<21:06,  3.93it/s]

Reports:  30%|██▉       | 2131/7111 [09:24<19:32,  4.25it/s]

Reports:  30%|██▉       | 2132/7111 [09:24<18:21,  4.52it/s]

Reports:  30%|██▉       | 2133/7111 [09:24<17:36,  4.71it/s]

Reports:  30%|███       | 2134/7111 [09:24<16:59,  4.88it/s]

Reports:  30%|███       | 2135/7111 [09:25<16:52,  4.92it/s]

Reports:  30%|███       | 2136/7111 [09:25<16:34,  5.00it/s]

Reports:  30%|███       | 2137/7111 [09:25<16:38,  4.98it/s]

Reports:  30%|███       | 2138/7111 [09:25<16:34,  5.00it/s]

Reports:  30%|███       | 2139/7111 [09:25<16:25,  5.05it/s]

Reports:  30%|███       | 2140/7111 [09:26<16:19,  5.07it/s]

Reports:  30%|███       | 2141/7111 [09:26<16:25,  5.04it/s]

Reports:  30%|███       | 2142/7111 [09:26<16:17,  5.08it/s]

Reports:  30%|███       | 2143/7111 [09:26<16:08,  5.13it/s]

Reports:  30%|███       | 2144/7111 [09:26<15:55,  5.20it/s]

Reports:  30%|███       | 2145/7111 [09:27<16:06,  5.14it/s]

Reports:  30%|███       | 2146/7111 [09:27<16:12,  5.10it/s]

Reports:  30%|███       | 2147/7111 [09:27<15:57,  5.19it/s]

Reports:  30%|███       | 2148/7111 [09:27<15:52,  5.21it/s]

Reports:  30%|███       | 2149/7111 [09:27<16:08,  5.12it/s]

Reports:  30%|███       | 2150/7111 [09:28<15:56,  5.19it/s]

Reports:  30%|███       | 2151/7111 [09:28<15:49,  5.22it/s]

Reports:  30%|███       | 2152/7111 [09:28<21:12,  3.90it/s]

Reports:  30%|███       | 2153/7111 [09:28<19:38,  4.21it/s]

Reports:  30%|███       | 2154/7111 [09:29<18:29,  4.47it/s]

Reports:  30%|███       | 2155/7111 [09:29<17:55,  4.61it/s]

Reports:  30%|███       | 2156/7111 [09:29<17:11,  4.80it/s]

Reports:  30%|███       | 2157/7111 [09:29<17:01,  4.85it/s]

Reports:  30%|███       | 2158/7111 [09:29<16:54,  4.88it/s]

Reports:  30%|███       | 2159/7111 [09:30<16:58,  4.86it/s]

Reports:  30%|███       | 2160/7111 [09:30<16:34,  4.98it/s]

Reports:  30%|███       | 2161/7111 [09:30<16:34,  4.98it/s]

Reports:  30%|███       | 2162/7111 [09:30<16:32,  4.99it/s]

Reports:  30%|███       | 2163/7111 [09:30<16:15,  5.07it/s]

Reports:  30%|███       | 2164/7111 [09:31<16:18,  5.05it/s]

Reports:  30%|███       | 2165/7111 [09:31<16:02,  5.14it/s]

Reports:  30%|███       | 2166/7111 [09:31<15:52,  5.19it/s]

Reports:  30%|███       | 2167/7111 [09:31<16:25,  5.02it/s]

Reports:  30%|███       | 2168/7111 [09:31<16:15,  5.07it/s]

Reports:  31%|███       | 2169/7111 [09:31<15:56,  5.17it/s]

Reports:  31%|███       | 2170/7111 [09:32<16:05,  5.12it/s]

Reports:  31%|███       | 2171/7111 [09:32<16:04,  5.12it/s]

Reports:  31%|███       | 2172/7111 [09:32<15:53,  5.18it/s]

Reports:  31%|███       | 2173/7111 [09:32<16:16,  5.05it/s]

Reports:  31%|███       | 2174/7111 [09:32<15:57,  5.15it/s]

Reports:  31%|███       | 2175/7111 [09:33<15:59,  5.15it/s]

Reports:  31%|███       | 2176/7111 [09:33<16:21,  5.03it/s]

Reports:  31%|███       | 2177/7111 [09:33<16:43,  4.91it/s]

Reports:  31%|███       | 2178/7111 [09:34<33:54,  2.42it/s]

Reports:  31%|███       | 2179/7111 [09:34<28:28,  2.89it/s]

Reports:  31%|███       | 2180/7111 [09:34<24:31,  3.35it/s]

Reports:  31%|███       | 2181/7111 [09:35<21:49,  3.76it/s]

Reports:  31%|███       | 2182/7111 [09:35<19:49,  4.14it/s]

Reports:  31%|███       | 2183/7111 [09:35<18:22,  4.47it/s]

Reports:  31%|███       | 2184/7111 [09:35<18:01,  4.55it/s]

Reports:  31%|███       | 2185/7111 [09:37<50:48,  1.62it/s]

Reports:  31%|███       | 2186/7111 [09:37<40:07,  2.05it/s]

Reports:  31%|███       | 2187/7111 [09:37<32:55,  2.49it/s]

Reports:  31%|███       | 2188/7111 [09:38<34:11,  2.40it/s]

Reports:  31%|███       | 2189/7111 [09:38<29:12,  2.81it/s]

Reports:  31%|███       | 2190/7111 [09:38<27:30,  2.98it/s]

Reports:  31%|███       | 2191/7111 [09:38<25:48,  3.18it/s]

Reports:  31%|███       | 2192/7111 [09:39<23:54,  3.43it/s]

Reports:  31%|███       | 2193/7111 [09:39<23:27,  3.49it/s]

Reports:  31%|███       | 2194/7111 [09:39<23:08,  3.54it/s]

Reports:  31%|███       | 2195/7111 [09:39<23:01,  3.56it/s]

Reports:  31%|███       | 2196/7111 [09:40<22:46,  3.60it/s]

Reports:  31%|███       | 2197/7111 [09:40<23:53,  3.43it/s]

Reports:  31%|███       | 2198/7111 [09:40<23:43,  3.45it/s]

Reports:  31%|███       | 2199/7111 [09:40<23:23,  3.50it/s]

Reports:  31%|███       | 2200/7111 [09:42<46:45,  1.75it/s]

Reports:  31%|███       | 2201/7111 [09:42<38:37,  2.12it/s]

Reports:  31%|███       | 2202/7111 [09:42<31:27,  2.60it/s]

Reports:  31%|███       | 2203/7111 [09:42<26:56,  3.04it/s]

Reports:  31%|███       | 2204/7111 [09:43<24:15,  3.37it/s]

Reports:  31%|███       | 2205/7111 [09:43<23:24,  3.49it/s]

Reports:  31%|███       | 2206/7111 [09:43<21:07,  3.87it/s]

Reports:  31%|███       | 2207/7111 [09:43<19:57,  4.10it/s]

Reports:  31%|███       | 2208/7111 [09:44<35:31,  2.30it/s]

Reports:  31%|███       | 2209/7111 [09:44<29:56,  2.73it/s]

Reports:  31%|███       | 2210/7111 [09:45<25:37,  3.19it/s]

Reports:  31%|███       | 2211/7111 [09:45<22:44,  3.59it/s]

Reports:  31%|███       | 2212/7111 [09:45<20:48,  3.93it/s]

Reports:  31%|███       | 2213/7111 [09:45<19:38,  4.16it/s]

Reports:  31%|███       | 2214/7111 [09:45<18:33,  4.40it/s]

Reports:  31%|███       | 2215/7111 [09:46<17:44,  4.60it/s]

Reports:  31%|███       | 2216/7111 [09:46<17:29,  4.66it/s]

Reports:  31%|███       | 2217/7111 [09:46<16:51,  4.84it/s]

Reports:  31%|███       | 2218/7111 [09:46<17:18,  4.71it/s]

Reports:  31%|███       | 2219/7111 [09:46<17:11,  4.74it/s]

Reports:  31%|███       | 2220/7111 [09:47<16:56,  4.81it/s]

Reports:  31%|███       | 2221/7111 [09:47<16:24,  4.96it/s]

Reports:  31%|███       | 2222/7111 [09:47<16:49,  4.85it/s]

Reports:  31%|███▏      | 2223/7111 [09:47<16:41,  4.88it/s]

Reports:  31%|███▏      | 2224/7111 [09:47<16:13,  5.02it/s]

Reports:  31%|███▏      | 2225/7111 [09:48<16:04,  5.06it/s]

Reports:  31%|███▏      | 2226/7111 [09:48<16:20,  4.98it/s]

Reports:  31%|███▏      | 2227/7111 [09:48<16:07,  5.05it/s]

Reports:  31%|███▏      | 2228/7111 [09:48<15:56,  5.11it/s]

Reports:  31%|███▏      | 2229/7111 [09:48<16:01,  5.08it/s]

Reports:  31%|███▏      | 2230/7111 [09:49<15:46,  5.16it/s]

Reports:  31%|███▏      | 2231/7111 [09:49<15:36,  5.21it/s]

Reports:  31%|███▏      | 2232/7111 [09:49<15:41,  5.18it/s]

Reports:  31%|███▏      | 2233/7111 [09:49<15:29,  5.25it/s]

Reports:  31%|███▏      | 2234/7111 [09:49<15:28,  5.25it/s]

Reports:  31%|███▏      | 2235/7111 [09:49<15:25,  5.27it/s]

Reports:  31%|███▏      | 2236/7111 [09:50<15:28,  5.25it/s]

Reports:  31%|███▏      | 2237/7111 [09:50<15:28,  5.25it/s]

Reports:  31%|███▏      | 2238/7111 [09:51<30:39,  2.65it/s]

Reports:  31%|███▏      | 2239/7111 [09:51<26:17,  3.09it/s]

Reports:  32%|███▏      | 2240/7111 [09:51<24:44,  3.28it/s]

Reports:  32%|███▏      | 2241/7111 [09:51<22:12,  3.65it/s]

Reports:  32%|███▏      | 2242/7111 [09:52<20:19,  3.99it/s]

Reports:  32%|███▏      | 2243/7111 [09:52<18:43,  4.33it/s]

Reports:  32%|███▏      | 2244/7111 [09:52<17:43,  4.58it/s]

Reports:  32%|███▏      | 2245/7111 [09:52<17:01,  4.76it/s]

Reports:  32%|███▏      | 2246/7111 [09:52<16:32,  4.90it/s]

Reports:  32%|███▏      | 2247/7111 [09:52<16:26,  4.93it/s]

Reports:  32%|███▏      | 2248/7111 [09:53<16:13,  4.99it/s]

Reports:  32%|███▏      | 2249/7111 [09:54<50:36,  1.60it/s]

Reports:  32%|███▏      | 2250/7111 [09:54<40:24,  2.01it/s]

Reports:  32%|███▏      | 2251/7111 [09:55<32:48,  2.47it/s]

Reports:  32%|███▏      | 2252/7111 [09:55<27:36,  2.93it/s]

Reports:  32%|███▏      | 2253/7111 [09:55<24:04,  3.36it/s]

Reports:  32%|███▏      | 2254/7111 [09:55<21:30,  3.76it/s]

Reports:  32%|███▏      | 2255/7111 [09:55<20:16,  3.99it/s]

Reports:  32%|███▏      | 2256/7111 [09:56<19:03,  4.25it/s]

Reports:  32%|███▏      | 2257/7111 [09:56<18:00,  4.49it/s]

Reports:  32%|███▏      | 2258/7111 [09:58<55:15,  1.46it/s]

Reports:  32%|███▏      | 2259/7111 [09:58<44:56,  1.80it/s]

Reports:  32%|███▏      | 2260/7111 [09:58<35:59,  2.25it/s]

Reports:  32%|███▏      | 2261/7111 [09:58<30:00,  2.69it/s]

Reports:  32%|███▏      | 2262/7111 [09:58<25:34,  3.16it/s]

Reports:  32%|███▏      | 2263/7111 [09:59<24:19,  3.32it/s]

Reports:  32%|███▏      | 2264/7111 [09:59<21:41,  3.72it/s]

Reports:  32%|███▏      | 2265/7111 [09:59<20:15,  3.99it/s]

Reports:  32%|███▏      | 2266/7111 [09:59<19:15,  4.19it/s]

Reports:  32%|███▏      | 2267/7111 [10:00<18:12,  4.43it/s]

Reports:  32%|███▏      | 2268/7111 [10:00<17:36,  4.58it/s]

Reports:  32%|███▏      | 2269/7111 [10:00<17:30,  4.61it/s]

Reports:  32%|███▏      | 2270/7111 [10:00<18:11,  4.43it/s]

Reports:  32%|███▏      | 2271/7111 [10:00<17:40,  4.56it/s]

Reports:  32%|███▏      | 2272/7111 [10:01<17:00,  4.74it/s]

Reports:  32%|███▏      | 2273/7111 [10:01<17:26,  4.62it/s]

Reports:  32%|███▏      | 2274/7111 [10:01<16:43,  4.82it/s]

Reports:  32%|███▏      | 2275/7111 [10:01<17:54,  4.50it/s]

Reports:  32%|███▏      | 2276/7111 [10:01<18:42,  4.31it/s]

Reports:  32%|███▏      | 2277/7111 [10:02<17:36,  4.58it/s]

Reports:  32%|███▏      | 2278/7111 [10:02<17:16,  4.66it/s]

Reports:  32%|███▏      | 2279/7111 [10:02<16:33,  4.86it/s]

Reports:  32%|███▏      | 2280/7111 [10:02<16:12,  4.97it/s]

Reports:  32%|███▏      | 2281/7111 [10:02<16:00,  5.03it/s]

Reports:  32%|███▏      | 2282/7111 [10:03<16:06,  5.00it/s]

Reports:  32%|███▏      | 2283/7111 [10:03<16:15,  4.95it/s]

Reports:  32%|███▏      | 2284/7111 [10:03<16:35,  4.85it/s]

Reports:  32%|███▏      | 2285/7111 [10:03<17:07,  4.70it/s]

Reports:  32%|███▏      | 2286/7111 [10:04<16:37,  4.84it/s]

Reports:  32%|███▏      | 2287/7111 [10:04<23:35,  3.41it/s]

Reports:  32%|███▏      | 2288/7111 [10:04<21:06,  3.81it/s]

Reports:  32%|███▏      | 2289/7111 [10:04<19:16,  4.17it/s]

Reports:  32%|███▏      | 2290/7111 [10:05<26:23,  3.04it/s]

Reports:  32%|███▏      | 2291/7111 [10:05<29:32,  2.72it/s]

Reports:  32%|███▏      | 2292/7111 [10:06<25:19,  3.17it/s]

Reports:  32%|███▏      | 2293/7111 [10:06<22:12,  3.61it/s]

Reports:  32%|███▏      | 2294/7111 [10:06<20:15,  3.96it/s]

Reports:  32%|███▏      | 2295/7111 [10:06<18:54,  4.25it/s]

Reports:  32%|███▏      | 2296/7111 [10:06<18:06,  4.43it/s]

Reports:  32%|███▏      | 2297/7111 [10:07<17:20,  4.63it/s]

Reports:  32%|███▏      | 2298/7111 [10:07<17:05,  4.69it/s]

Reports:  32%|███▏      | 2299/7111 [10:07<17:14,  4.65it/s]

Reports:  32%|███▏      | 2300/7111 [10:07<16:33,  4.84it/s]

Reports:  32%|███▏      | 2301/7111 [10:07<16:04,  4.99it/s]

Reports:  32%|███▏      | 2302/7111 [10:08<15:40,  5.11it/s]

Reports:  32%|███▏      | 2303/7111 [10:08<15:32,  5.16it/s]

Reports:  32%|███▏      | 2304/7111 [10:08<15:18,  5.23it/s]

Reports:  32%|███▏      | 2305/7111 [10:08<15:37,  5.13it/s]

Reports:  32%|███▏      | 2306/7111 [10:08<17:16,  4.63it/s]

Reports:  32%|███▏      | 2307/7111 [10:09<16:48,  4.76it/s]

Reports:  32%|███▏      | 2308/7111 [10:09<16:33,  4.84it/s]

Reports:  32%|███▏      | 2309/7111 [10:09<16:13,  4.93it/s]

Reports:  32%|███▏      | 2310/7111 [10:09<16:08,  4.96it/s]

Reports:  32%|███▏      | 2311/7111 [10:09<15:43,  5.09it/s]

Reports:  33%|███▎      | 2312/7111 [10:10<15:46,  5.07it/s]

Reports:  33%|███▎      | 2313/7111 [10:10<15:57,  5.01it/s]

Reports:  33%|███▎      | 2314/7111 [10:10<15:30,  5.15it/s]

Reports:  33%|███▎      | 2315/7111 [10:10<15:35,  5.13it/s]

Reports:  33%|███▎      | 2316/7111 [10:11<35:19,  2.26it/s]

Reports:  33%|███▎      | 2317/7111 [10:11<29:21,  2.72it/s]

Reports:  33%|███▎      | 2318/7111 [10:12<25:27,  3.14it/s]

Reports:  33%|███▎      | 2319/7111 [10:12<22:13,  3.59it/s]

Reports:  33%|███▎      | 2320/7111 [10:12<30:50,  2.59it/s]

Reports:  33%|███▎      | 2321/7111 [10:13<25:57,  3.08it/s]

Reports:  33%|███▎      | 2322/7111 [10:13<22:32,  3.54it/s]

Reports:  33%|███▎      | 2323/7111 [10:13<20:13,  3.95it/s]

Reports:  33%|███▎      | 2324/7111 [10:13<19:13,  4.15it/s]

Reports:  33%|███▎      | 2325/7111 [10:13<17:58,  4.44it/s]

Reports:  33%|███▎      | 2326/7111 [10:14<18:10,  4.39it/s]

Reports:  33%|███▎      | 2327/7111 [10:15<39:58,  1.99it/s]

Reports:  33%|███▎      | 2328/7111 [10:15<32:32,  2.45it/s]

Reports:  33%|███▎      | 2329/7111 [10:15<27:25,  2.91it/s]

Reports:  33%|███▎      | 2330/7111 [10:15<23:45,  3.35it/s]

Reports:  33%|███▎      | 2331/7111 [10:15<21:28,  3.71it/s]

Reports:  33%|███▎      | 2332/7111 [10:16<19:37,  4.06it/s]

Reports:  33%|███▎      | 2333/7111 [10:16<18:15,  4.36it/s]

Reports:  33%|███▎      | 2334/7111 [10:16<17:11,  4.63it/s]

Reports:  33%|███▎      | 2335/7111 [10:16<16:53,  4.71it/s]

Reports:  33%|███▎      | 2336/7111 [10:16<16:29,  4.82it/s]

Reports:  33%|███▎      | 2337/7111 [10:17<16:26,  4.84it/s]

Reports:  33%|███▎      | 2338/7111 [10:17<16:19,  4.88it/s]

Reports:  33%|███▎      | 2339/7111 [10:17<16:08,  4.93it/s]

Reports:  33%|███▎      | 2340/7111 [10:17<15:42,  5.06it/s]

Reports:  33%|███▎      | 2341/7111 [10:17<16:19,  4.87it/s]

Reports:  33%|███▎      | 2342/7111 [10:18<15:49,  5.02it/s]

Reports:  33%|███▎      | 2343/7111 [10:18<15:59,  4.97it/s]

Reports:  33%|███▎      | 2344/7111 [10:18<16:05,  4.94it/s]

Reports:  33%|███▎      | 2345/7111 [10:18<16:15,  4.89it/s]

Reports:  33%|███▎      | 2346/7111 [10:18<16:14,  4.89it/s]

Reports:  33%|███▎      | 2347/7111 [10:19<17:08,  4.63it/s]

Reports:  33%|███▎      | 2348/7111 [10:19<16:19,  4.86it/s]

Reports:  33%|███▎      | 2349/7111 [10:19<16:37,  4.77it/s]

Reports:  33%|███▎      | 2350/7111 [10:19<17:20,  4.58it/s]

Reports:  33%|███▎      | 2351/7111 [10:20<24:43,  3.21it/s]

Reports:  33%|███▎      | 2352/7111 [10:20<21:43,  3.65it/s]

Reports:  33%|███▎      | 2353/7111 [10:20<19:59,  3.97it/s]

Reports:  33%|███▎      | 2354/7111 [10:20<19:01,  4.17it/s]

Reports:  33%|███▎      | 2355/7111 [10:21<17:39,  4.49it/s]

Reports:  33%|███▎      | 2356/7111 [10:21<16:49,  4.71it/s]

Reports:  33%|███▎      | 2357/7111 [10:21<16:35,  4.78it/s]

Reports:  33%|███▎      | 2358/7111 [10:21<16:24,  4.83it/s]

Reports:  33%|███▎      | 2359/7111 [10:21<15:52,  4.99it/s]

Reports:  33%|███▎      | 2360/7111 [10:22<15:35,  5.08it/s]

Reports:  33%|███▎      | 2361/7111 [10:22<15:58,  4.96it/s]

Reports:  33%|███▎      | 2362/7111 [10:22<15:45,  5.02it/s]

Reports:  33%|███▎      | 2363/7111 [10:22<15:25,  5.13it/s]

Reports:  33%|███▎      | 2364/7111 [10:22<16:21,  4.84it/s]

Reports:  33%|███▎      | 2365/7111 [10:23<17:06,  4.63it/s]

Reports:  33%|███▎      | 2366/7111 [10:23<17:08,  4.62it/s]

Reports:  33%|███▎      | 2367/7111 [10:23<16:32,  4.78it/s]

Reports:  33%|███▎      | 2368/7111 [10:23<18:24,  4.30it/s]

Reports:  33%|███▎      | 2369/7111 [10:24<21:06,  3.74it/s]

Reports:  33%|███▎      | 2370/7111 [10:24<19:05,  4.14it/s]

Reports:  33%|███▎      | 2371/7111 [10:24<18:10,  4.35it/s]

Reports:  33%|███▎      | 2372/7111 [10:24<17:20,  4.55it/s]

Reports:  33%|███▎      | 2373/7111 [10:24<16:43,  4.72it/s]

Reports:  33%|███▎      | 2374/7111 [10:25<16:04,  4.91it/s]

Reports:  33%|███▎      | 2375/7111 [10:25<17:12,  4.59it/s]

Reports:  33%|███▎      | 2376/7111 [10:25<16:47,  4.70it/s]

Reports:  33%|███▎      | 2377/7111 [10:25<16:17,  4.84it/s]

Reports:  33%|███▎      | 2378/7111 [10:26<15:48,  4.99it/s]

Reports:  33%|███▎      | 2379/7111 [10:26<19:32,  4.04it/s]

Reports:  33%|███▎      | 2380/7111 [10:26<18:15,  4.32it/s]

Reports:  33%|███▎      | 2381/7111 [10:26<17:52,  4.41it/s]

Reports:  33%|███▎      | 2382/7111 [10:26<17:00,  4.64it/s]

Reports:  34%|███▎      | 2383/7111 [10:27<16:22,  4.81it/s]

Reports:  34%|███▎      | 2384/7111 [10:27<16:56,  4.65it/s]

Reports:  34%|███▎      | 2385/7111 [10:27<17:31,  4.49it/s]

Reports:  34%|███▎      | 2386/7111 [10:27<17:01,  4.63it/s]

Reports:  34%|███▎      | 2387/7111 [10:28<16:29,  4.77it/s]

Reports:  34%|███▎      | 2388/7111 [10:28<15:57,  4.94it/s]

Reports:  34%|███▎      | 2389/7111 [10:28<15:41,  5.01it/s]

Reports:  34%|███▎      | 2390/7111 [10:28<15:59,  4.92it/s]

Reports:  34%|███▎      | 2391/7111 [10:28<16:00,  4.91it/s]

Reports:  34%|███▎      | 2392/7111 [10:29<15:36,  5.04it/s]

Reports:  34%|███▎      | 2393/7111 [10:29<16:07,  4.88it/s]

Reports:  34%|███▎      | 2394/7111 [10:29<16:55,  4.65it/s]

Reports:  34%|███▎      | 2395/7111 [10:29<16:12,  4.85it/s]

Reports:  34%|███▎      | 2396/7111 [10:29<15:54,  4.94it/s]

Reports:  34%|███▎      | 2397/7111 [10:30<15:32,  5.05it/s]

Reports:  34%|███▎      | 2398/7111 [10:30<15:16,  5.14it/s]

Reports:  34%|███▎      | 2399/7111 [10:30<15:00,  5.23it/s]

Reports:  34%|███▍      | 2400/7111 [10:30<15:05,  5.20it/s]

Reports:  34%|███▍      | 2401/7111 [10:30<15:05,  5.20it/s]

Reports:  34%|███▍      | 2402/7111 [10:30<15:00,  5.23it/s]

Reports:  34%|███▍      | 2403/7111 [10:31<16:07,  4.87it/s]

Reports:  34%|███▍      | 2404/7111 [10:31<15:39,  5.01it/s]

Reports:  34%|███▍      | 2405/7111 [10:31<16:13,  4.83it/s]

Reports:  34%|███▍      | 2406/7111 [10:31<16:25,  4.77it/s]

Reports:  34%|███▍      | 2407/7111 [10:32<18:47,  4.17it/s]

Reports:  34%|███▍      | 2408/7111 [10:32<17:48,  4.40it/s]

Reports:  34%|███▍      | 2409/7111 [10:32<18:21,  4.27it/s]

Reports:  34%|███▍      | 2410/7111 [10:32<17:46,  4.41it/s]

Reports:  34%|███▍      | 2411/7111 [10:32<16:57,  4.62it/s]

Reports:  34%|███▍      | 2412/7111 [10:33<16:51,  4.64it/s]

Reports:  34%|███▍      | 2413/7111 [10:33<16:11,  4.84it/s]

Reports:  34%|███▍      | 2414/7111 [10:33<16:21,  4.79it/s]

Reports:  34%|███▍      | 2415/7111 [10:33<15:53,  4.93it/s]

Reports:  34%|███▍      | 2416/7111 [10:34<15:50,  4.94it/s]

Reports:  34%|███▍      | 2417/7111 [10:34<15:48,  4.95it/s]

Reports:  34%|███▍      | 2418/7111 [10:34<15:29,  5.05it/s]

Reports:  34%|███▍      | 2419/7111 [10:34<15:45,  4.96it/s]

Reports:  34%|███▍      | 2420/7111 [10:34<15:51,  4.93it/s]

Reports:  34%|███▍      | 2421/7111 [10:34<15:30,  5.04it/s]

Reports:  34%|███▍      | 2422/7111 [10:35<16:41,  4.68it/s]

Reports:  34%|███▍      | 2423/7111 [10:35<16:18,  4.79it/s]

Reports:  34%|███▍      | 2424/7111 [10:35<18:17,  4.27it/s]

Reports:  34%|███▍      | 2425/7111 [10:35<17:13,  4.53it/s]

Reports:  34%|███▍      | 2426/7111 [10:36<17:36,  4.43it/s]

Reports:  34%|███▍      | 2427/7111 [10:36<18:05,  4.32it/s]

Reports:  34%|███▍      | 2428/7111 [10:36<24:37,  3.17it/s]

Reports:  34%|███▍      | 2429/7111 [10:37<21:54,  3.56it/s]

Reports:  34%|███▍      | 2430/7111 [10:37<20:42,  3.77it/s]

Reports:  34%|███▍      | 2431/7111 [10:37<21:03,  3.70it/s]

Reports:  34%|███▍      | 2432/7111 [10:37<19:24,  4.02it/s]

Reports:  34%|███▍      | 2433/7111 [10:38<30:03,  2.59it/s]

Reports:  34%|███▍      | 2434/7111 [10:38<27:03,  2.88it/s]

Reports:  34%|███▍      | 2435/7111 [10:38<23:15,  3.35it/s]

Reports:  34%|███▍      | 2436/7111 [10:39<20:37,  3.78it/s]

Reports:  34%|███▍      | 2437/7111 [10:39<21:51,  3.56it/s]

Reports:  34%|███▍      | 2438/7111 [10:39<19:59,  3.90it/s]

Reports:  34%|███▍      | 2439/7111 [10:40<33:03,  2.36it/s]

Reports:  34%|███▍      | 2440/7111 [10:40<28:51,  2.70it/s]

Reports:  34%|███▍      | 2441/7111 [10:40<26:01,  2.99it/s]

Reports:  34%|███▍      | 2442/7111 [10:41<22:38,  3.44it/s]

Reports:  34%|███▍      | 2443/7111 [10:41<20:10,  3.86it/s]

Reports:  34%|███▍      | 2444/7111 [10:41<18:20,  4.24it/s]

Reports:  34%|███▍      | 2445/7111 [10:41<17:20,  4.49it/s]

Reports:  34%|███▍      | 2446/7111 [10:41<16:39,  4.67it/s]

Reports:  34%|███▍      | 2447/7111 [10:42<16:01,  4.85it/s]

Reports:  34%|███▍      | 2448/7111 [10:44<59:30,  1.31it/s]

Reports:  34%|███▍      | 2449/7111 [10:44<46:06,  1.69it/s]

Reports:  34%|███▍      | 2450/7111 [10:44<38:36,  2.01it/s]

Reports:  34%|███▍      | 2451/7111 [10:44<31:36,  2.46it/s]

Reports:  34%|███▍      | 2452/7111 [10:45<26:37,  2.92it/s]

Reports:  34%|███▍      | 2453/7111 [10:45<23:18,  3.33it/s]

Reports:  35%|███▍      | 2454/7111 [10:45<21:43,  3.57it/s]

Reports:  35%|███▍      | 2455/7111 [10:45<20:22,  3.81it/s]

Reports:  35%|███▍      | 2456/7111 [10:45<18:53,  4.11it/s]

Reports:  35%|███▍      | 2457/7111 [10:46<18:51,  4.11it/s]

Reports:  35%|███▍      | 2458/7111 [10:46<19:37,  3.95it/s]

Reports:  35%|███▍      | 2459/7111 [10:46<18:39,  4.15it/s]

Reports:  35%|███▍      | 2460/7111 [10:46<18:01,  4.30it/s]

Reports:  35%|███▍      | 2461/7111 [10:47<19:12,  4.03it/s]

Reports:  35%|███▍      | 2462/7111 [10:47<18:03,  4.29it/s]

Reports:  35%|███▍      | 2463/7111 [10:47<16:53,  4.58it/s]

Reports:  35%|███▍      | 2464/7111 [10:48<26:34,  2.91it/s]

Reports:  35%|███▍      | 2465/7111 [10:48<24:09,  3.21it/s]

Reports:  35%|███▍      | 2466/7111 [10:48<21:19,  3.63it/s]

Reports:  35%|███▍      | 2467/7111 [10:48<19:45,  3.92it/s]

Reports:  35%|███▍      | 2468/7111 [10:48<18:17,  4.23it/s]

Reports:  35%|███▍      | 2469/7111 [10:49<17:07,  4.52it/s]

Reports:  35%|███▍      | 2470/7111 [10:49<16:29,  4.69it/s]

Reports:  35%|███▍      | 2471/7111 [10:49<16:07,  4.79it/s]

Reports:  35%|███▍      | 2472/7111 [10:49<15:59,  4.83it/s]

Reports:  35%|███▍      | 2473/7111 [10:49<15:49,  4.88it/s]

Reports:  35%|███▍      | 2474/7111 [10:50<16:06,  4.80it/s]

Reports:  35%|███▍      | 2475/7111 [10:50<15:43,  4.91it/s]

Reports:  35%|███▍      | 2476/7111 [10:50<15:32,  4.97it/s]

Reports:  35%|███▍      | 2477/7111 [10:50<15:21,  5.03it/s]

Reports:  35%|███▍      | 2478/7111 [10:50<15:08,  5.10it/s]

Reports:  35%|███▍      | 2479/7111 [10:51<15:06,  5.11it/s]

Reports:  35%|███▍      | 2480/7111 [10:51<15:01,  5.14it/s]

Reports:  35%|███▍      | 2481/7111 [10:51<16:02,  4.81it/s]

Reports:  35%|███▍      | 2482/7111 [10:51<18:28,  4.17it/s]

Reports:  35%|███▍      | 2483/7111 [10:52<17:31,  4.40it/s]

Reports:  35%|███▍      | 2484/7111 [10:52<16:36,  4.65it/s]

Reports:  35%|███▍      | 2485/7111 [10:52<16:27,  4.68it/s]

Reports:  35%|███▍      | 2486/7111 [10:52<15:49,  4.87it/s]

Reports:  35%|███▍      | 2487/7111 [10:52<15:45,  4.89it/s]

Reports:  35%|███▍      | 2488/7111 [10:53<15:27,  4.99it/s]

Reports:  35%|███▌      | 2489/7111 [10:53<16:24,  4.69it/s]

Reports:  35%|███▌      | 2490/7111 [10:53<15:49,  4.87it/s]

Reports:  35%|███▌      | 2491/7111 [10:54<45:48,  1.68it/s]

Reports:  35%|███▌      | 2492/7111 [10:55<36:20,  2.12it/s]

Reports:  35%|███▌      | 2493/7111 [10:55<31:11,  2.47it/s]

Reports:  35%|███▌      | 2494/7111 [10:55<26:40,  2.89it/s]

Reports:  35%|███▌      | 2495/7111 [10:55<23:31,  3.27it/s]

Reports:  35%|███▌      | 2496/7111 [10:56<21:01,  3.66it/s]

Reports:  35%|███▌      | 2497/7111 [10:56<19:05,  4.03it/s]

Reports:  35%|███▌      | 2498/7111 [10:56<19:26,  3.96it/s]

Reports:  35%|███▌      | 2499/7111 [10:56<18:21,  4.19it/s]

Reports:  35%|███▌      | 2500/7111 [10:56<18:05,  4.25it/s]

Reports:  35%|███▌      | 2501/7111 [10:57<17:17,  4.44it/s]

Reports:  35%|███▌      | 2502/7111 [10:57<17:32,  4.38it/s]

Reports:  35%|███▌      | 2503/7111 [10:57<16:47,  4.57it/s]

Reports:  35%|███▌      | 2504/7111 [10:57<16:09,  4.75it/s]

Reports:  35%|███▌      | 2505/7111 [10:57<16:37,  4.62it/s]

Reports:  35%|███▌      | 2506/7111 [10:58<16:51,  4.55it/s]

Reports:  35%|███▌      | 2507/7111 [10:58<15:59,  4.80it/s]

Reports:  35%|███▌      | 2508/7111 [10:58<15:30,  4.95it/s]

Reports:  35%|███▌      | 2509/7111 [10:59<28:15,  2.71it/s]

Reports:  35%|███▌      | 2510/7111 [10:59<24:17,  3.16it/s]

Reports:  35%|███▌      | 2511/7111 [11:00<46:04,  1.66it/s]

Reports:  35%|███▌      | 2512/7111 [11:01<37:21,  2.05it/s]

Reports:  35%|███▌      | 2513/7111 [11:01<32:11,  2.38it/s]

Reports:  35%|███▌      | 2514/7111 [11:01<26:58,  2.84it/s]

Reports:  35%|███▌      | 2515/7111 [11:01<25:46,  2.97it/s]

Reports:  35%|███▌      | 2516/7111 [11:01<22:32,  3.40it/s]

Reports:  35%|███▌      | 2517/7111 [11:02<20:49,  3.68it/s]

Reports:  35%|███▌      | 2518/7111 [11:02<19:05,  4.01it/s]

Reports:  35%|███▌      | 2519/7111 [11:02<19:22,  3.95it/s]

Reports:  35%|███▌      | 2520/7111 [11:02<19:07,  4.00it/s]

Reports:  35%|███▌      | 2521/7111 [11:03<18:35,  4.12it/s]

Reports:  35%|███▌      | 2522/7111 [11:03<17:26,  4.39it/s]

Reports:  35%|███▌      | 2523/7111 [11:03<17:58,  4.26it/s]

Reports:  35%|███▌      | 2524/7111 [11:03<16:49,  4.54it/s]

Reports:  36%|███▌      | 2525/7111 [11:03<16:03,  4.76it/s]

Reports:  36%|███▌      | 2526/7111 [11:04<16:33,  4.62it/s]

Reports:  36%|███▌      | 2527/7111 [11:04<16:17,  4.69it/s]

Reports:  36%|███▌      | 2528/7111 [11:04<15:51,  4.82it/s]

Reports:  36%|███▌      | 2529/7111 [11:04<15:15,  5.01it/s]

Reports:  36%|███▌      | 2530/7111 [11:04<14:55,  5.11it/s]

Reports:  36%|███▌      | 2531/7111 [11:05<14:51,  5.14it/s]

Reports:  36%|███▌      | 2532/7111 [11:05<18:07,  4.21it/s]

Reports:  36%|███▌      | 2533/7111 [11:05<17:17,  4.41it/s]

Reports:  36%|███▌      | 2534/7111 [11:05<16:43,  4.56it/s]

Reports:  36%|███▌      | 2535/7111 [11:06<18:36,  4.10it/s]

Reports:  36%|███▌      | 2536/7111 [11:06<19:09,  3.98it/s]

Reports:  36%|███▌      | 2537/7111 [11:06<20:54,  3.65it/s]

Reports:  36%|███▌      | 2538/7111 [11:06<19:14,  3.96it/s]

Reports:  36%|███▌      | 2539/7111 [11:07<18:02,  4.22it/s]

Reports:  36%|███▌      | 2540/7111 [11:07<17:23,  4.38it/s]

Reports:  36%|███▌      | 2541/7111 [11:07<18:08,  4.20it/s]

Reports:  36%|███▌      | 2542/7111 [11:07<17:00,  4.48it/s]

Reports:  36%|███▌      | 2543/7111 [11:08<17:24,  4.37it/s]

Reports:  36%|███▌      | 2544/7111 [11:08<16:44,  4.55it/s]

Reports:  36%|███▌      | 2545/7111 [11:08<16:06,  4.73it/s]

Reports:  36%|███▌      | 2546/7111 [11:08<16:52,  4.51it/s]

Reports:  36%|███▌      | 2547/7111 [11:08<15:54,  4.78it/s]

Reports:  36%|███▌      | 2548/7111 [11:09<15:34,  4.88it/s]

Reports:  36%|███▌      | 2549/7111 [11:09<18:45,  4.05it/s]

Reports:  36%|███▌      | 2550/7111 [11:09<19:07,  3.98it/s]

Reports:  36%|███▌      | 2551/7111 [11:09<17:51,  4.26it/s]

Reports:  36%|███▌      | 2552/7111 [11:10<16:38,  4.57it/s]

Reports:  36%|███▌      | 2553/7111 [11:10<16:10,  4.70it/s]

Reports:  36%|███▌      | 2554/7111 [11:10<15:37,  4.86it/s]

Reports:  36%|███▌      | 2555/7111 [11:10<15:14,  4.98it/s]

Reports:  36%|███▌      | 2556/7111 [11:11<31:27,  2.41it/s]

Reports:  36%|███▌      | 2557/7111 [11:11<26:15,  2.89it/s]

Reports:  36%|███▌      | 2558/7111 [11:11<22:51,  3.32it/s]

Reports:  36%|███▌      | 2559/7111 [11:12<20:16,  3.74it/s]

Reports:  36%|███▌      | 2560/7111 [11:12<18:24,  4.12it/s]

Reports:  36%|███▌      | 2561/7111 [11:12<17:11,  4.41it/s]

Reports:  36%|███▌      | 2562/7111 [11:12<16:28,  4.60it/s]

Reports:  36%|███▌      | 2563/7111 [11:12<15:47,  4.80it/s]

Reports:  36%|███▌      | 2564/7111 [11:13<15:17,  4.96it/s]

Reports:  36%|███▌      | 2565/7111 [11:13<16:10,  4.68it/s]

Reports:  36%|███▌      | 2566/7111 [11:13<15:34,  4.86it/s]

Reports:  36%|███▌      | 2567/7111 [11:13<15:25,  4.91it/s]

Reports:  36%|███▌      | 2568/7111 [11:13<15:19,  4.94it/s]

Reports:  36%|███▌      | 2569/7111 [11:14<17:53,  4.23it/s]

Reports:  36%|███▌      | 2570/7111 [11:14<16:52,  4.49it/s]

Reports:  36%|███▌      | 2571/7111 [11:14<19:16,  3.93it/s]

Reports:  36%|███▌      | 2572/7111 [11:14<17:37,  4.29it/s]

Reports:  36%|███▌      | 2573/7111 [11:15<16:33,  4.57it/s]

Reports:  36%|███▌      | 2574/7111 [11:15<15:55,  4.75it/s]

Reports:  36%|███▌      | 2575/7111 [11:15<15:24,  4.91it/s]

Reports:  36%|███▌      | 2576/7111 [11:15<17:42,  4.27it/s]

Reports:  36%|███▌      | 2577/7111 [11:15<17:04,  4.42it/s]

Reports:  36%|███▋      | 2578/7111 [11:16<16:28,  4.59it/s]

Reports:  36%|███▋      | 2579/7111 [11:16<15:46,  4.79it/s]

Reports:  36%|███▋      | 2580/7111 [11:16<17:12,  4.39it/s]

Reports:  36%|███▋      | 2581/7111 [11:16<16:57,  4.45it/s]

Reports:  36%|███▋      | 2582/7111 [11:17<16:01,  4.71it/s]

Reports:  36%|███▋      | 2583/7111 [11:17<15:36,  4.84it/s]

Reports:  36%|███▋      | 2584/7111 [11:17<15:09,  4.98it/s]

Reports:  36%|███▋      | 2585/7111 [11:17<14:53,  5.07it/s]

Reports:  36%|███▋      | 2586/7111 [11:17<14:34,  5.17it/s]

Reports:  36%|███▋      | 2587/7111 [11:17<14:28,  5.21it/s]

Reports:  36%|███▋      | 2588/7111 [11:18<14:32,  5.18it/s]

Reports:  36%|███▋      | 2589/7111 [11:18<14:25,  5.22it/s]

Reports:  36%|███▋      | 2590/7111 [11:18<14:43,  5.12it/s]

Reports:  36%|███▋      | 2591/7111 [11:18<14:48,  5.09it/s]

Reports:  36%|███▋      | 2592/7111 [11:18<14:44,  5.11it/s]

Reports:  36%|███▋      | 2593/7111 [11:19<14:41,  5.12it/s]

Reports:  36%|███▋      | 2594/7111 [11:19<14:29,  5.19it/s]

Reports:  36%|███▋      | 2595/7111 [11:19<14:17,  5.27it/s]

Reports:  37%|███▋      | 2596/7111 [11:19<14:34,  5.16it/s]

Reports:  37%|███▋      | 2597/7111 [11:20<17:52,  4.21it/s]

Reports:  37%|███▋      | 2598/7111 [11:20<16:39,  4.52it/s]

Reports:  37%|███▋      | 2599/7111 [11:20<16:45,  4.49it/s]

Reports:  37%|███▋      | 2600/7111 [11:20<16:05,  4.67it/s]

Reports:  37%|███▋      | 2601/7111 [11:20<15:36,  4.82it/s]

Reports:  37%|███▋      | 2602/7111 [11:21<15:39,  4.80it/s]

Reports:  37%|███▋      | 2603/7111 [11:21<15:14,  4.93it/s]

Reports:  37%|███▋      | 2604/7111 [11:21<15:19,  4.90it/s]

Reports:  37%|███▋      | 2605/7111 [11:21<15:18,  4.90it/s]

Reports:  37%|███▋      | 2606/7111 [11:21<15:08,  4.96it/s]

Reports:  37%|███▋      | 2607/7111 [11:22<14:52,  5.05it/s]

Reports:  37%|███▋      | 2608/7111 [11:22<14:56,  5.02it/s]

Reports:  37%|███▋      | 2609/7111 [11:22<14:48,  5.07it/s]

Reports:  37%|███▋      | 2610/7111 [11:22<14:54,  5.03it/s]

Reports:  37%|███▋      | 2611/7111 [11:22<15:24,  4.87it/s]

Reports:  37%|███▋      | 2612/7111 [11:23<15:05,  4.97it/s]

Reports:  37%|███▋      | 2613/7111 [11:23<14:57,  5.01it/s]

Reports:  37%|███▋      | 2614/7111 [11:23<15:26,  4.86it/s]

Reports:  37%|███▋      | 2615/7111 [11:23<15:32,  4.82it/s]

Reports:  37%|███▋      | 2616/7111 [11:23<15:13,  4.92it/s]

Reports:  37%|███▋      | 2617/7111 [11:24<14:56,  5.01it/s]

Reports:  37%|███▋      | 2618/7111 [11:24<15:06,  4.96it/s]

Reports:  37%|███▋      | 2619/7111 [11:24<14:50,  5.04it/s]

Reports:  37%|███▋      | 2620/7111 [11:24<14:53,  5.03it/s]

Reports:  37%|███▋      | 2621/7111 [11:24<14:36,  5.12it/s]

Reports:  37%|███▋      | 2622/7111 [11:25<14:32,  5.14it/s]

Reports:  37%|███▋      | 2623/7111 [11:25<14:35,  5.13it/s]

Reports:  37%|███▋      | 2624/7111 [11:25<15:00,  4.98it/s]

Reports:  37%|███▋      | 2625/7111 [11:25<14:54,  5.01it/s]

Reports:  37%|███▋      | 2626/7111 [11:25<16:14,  4.60it/s]

Reports:  37%|███▋      | 2627/7111 [11:26<15:35,  4.79it/s]

Reports:  37%|███▋      | 2628/7111 [11:26<15:09,  4.93it/s]

Reports:  37%|███▋      | 2629/7111 [11:26<15:01,  4.97it/s]

Reports:  37%|███▋      | 2630/7111 [11:26<14:45,  5.06it/s]

Reports:  37%|███▋      | 2631/7111 [11:26<14:41,  5.08it/s]

Reports:  37%|███▋      | 2632/7111 [11:27<14:27,  5.16it/s]

Reports:  37%|███▋      | 2633/7111 [11:27<14:35,  5.11it/s]

Reports:  37%|███▋      | 2634/7111 [11:27<14:25,  5.18it/s]

Reports:  37%|███▋      | 2635/7111 [11:27<14:15,  5.23it/s]

Reports:  37%|███▋      | 2636/7111 [11:27<14:14,  5.23it/s]

Reports:  37%|███▋      | 2637/7111 [11:28<14:32,  5.13it/s]

Reports:  37%|███▋      | 2638/7111 [11:28<15:01,  4.96it/s]

Reports:  37%|███▋      | 2639/7111 [11:28<15:00,  4.96it/s]

Reports:  37%|███▋      | 2640/7111 [11:28<15:02,  4.95it/s]

Reports:  37%|███▋      | 2641/7111 [11:29<18:32,  4.02it/s]

Reports:  37%|███▋      | 2642/7111 [11:29<17:33,  4.24it/s]

Reports:  37%|███▋      | 2643/7111 [11:29<16:27,  4.52it/s]

Reports:  37%|███▋      | 2644/7111 [11:29<15:52,  4.69it/s]

Reports:  37%|███▋      | 2645/7111 [11:29<15:23,  4.84it/s]

Reports:  37%|███▋      | 2646/7111 [11:30<15:18,  4.86it/s]

Reports:  37%|███▋      | 2647/7111 [11:30<15:23,  4.84it/s]

Reports:  37%|███▋      | 2648/7111 [11:30<14:59,  4.96it/s]

Reports:  37%|███▋      | 2649/7111 [11:30<14:53,  4.99it/s]

Reports:  37%|███▋      | 2650/7111 [11:30<14:37,  5.08it/s]

Reports:  37%|███▋      | 2651/7111 [11:30<14:28,  5.14it/s]

Reports:  37%|███▋      | 2652/7111 [11:31<14:13,  5.22it/s]

Reports:  37%|███▋      | 2653/7111 [11:31<14:22,  5.17it/s]

Reports:  37%|███▋      | 2654/7111 [11:31<14:15,  5.21it/s]

Reports:  37%|███▋      | 2655/7111 [11:31<14:18,  5.19it/s]

Reports:  37%|███▋      | 2656/7111 [11:31<14:01,  5.30it/s]

Reports:  37%|███▋      | 2657/7111 [11:32<14:27,  5.14it/s]

Reports:  37%|███▋      | 2658/7111 [11:32<14:37,  5.08it/s]

Reports:  37%|███▋      | 2659/7111 [11:32<14:29,  5.12it/s]

Reports:  37%|███▋      | 2660/7111 [11:32<14:21,  5.17it/s]

Reports:  37%|███▋      | 2661/7111 [11:32<14:27,  5.13it/s]

Reports:  37%|███▋      | 2662/7111 [11:33<14:59,  4.95it/s]

Reports:  37%|███▋      | 2663/7111 [11:33<14:41,  5.05it/s]

Reports:  37%|███▋      | 2664/7111 [11:33<14:46,  5.02it/s]

Reports:  37%|███▋      | 2665/7111 [11:33<14:51,  4.99it/s]

Reports:  37%|███▋      | 2666/7111 [11:33<14:31,  5.10it/s]

Reports:  38%|███▊      | 2667/7111 [11:34<14:37,  5.07it/s]

Reports:  38%|███▊      | 2668/7111 [11:34<14:19,  5.17it/s]

Reports:  38%|███▊      | 2669/7111 [11:34<14:12,  5.21it/s]

Reports:  38%|███▊      | 2670/7111 [11:34<14:21,  5.15it/s]

Reports:  38%|███▊      | 2671/7111 [11:34<14:25,  5.13it/s]

Reports:  38%|███▊      | 2672/7111 [11:35<14:31,  5.09it/s]

Reports:  38%|███▊      | 2673/7111 [11:37<1:03:45,  1.16it/s]

Reports:  38%|███▊      | 2674/7111 [11:37<49:12,  1.50it/s]

Reports:  38%|███▊      | 2675/7111 [11:37<39:11,  1.89it/s]

Reports:  38%|███▊      | 2676/7111 [11:38<32:09,  2.30it/s]

Reports:  38%|███▊      | 2677/7111 [11:38<26:42,  2.77it/s]

Reports:  38%|███▊      | 2678/7111 [11:38<22:59,  3.21it/s]

Reports:  38%|███▊      | 2679/7111 [11:38<20:28,  3.61it/s]

Reports:  38%|███▊      | 2680/7111 [11:38<18:26,  4.00it/s]

Reports:  38%|███▊      | 2681/7111 [11:39<17:08,  4.31it/s]

Reports:  38%|███▊      | 2682/7111 [11:39<16:08,  4.57it/s]

Reports:  38%|███▊      | 2683/7111 [11:39<15:24,  4.79it/s]

Reports:  38%|███▊      | 2684/7111 [11:39<15:04,  4.90it/s]

Reports:  38%|███▊      | 2685/7111 [11:39<15:00,  4.91it/s]

Reports:  38%|███▊      | 2686/7111 [11:40<14:53,  4.95it/s]

Reports:  38%|███▊      | 2687/7111 [11:40<14:38,  5.03it/s]

Reports:  38%|███▊      | 2688/7111 [11:41<47:18,  1.56it/s]

Reports:  38%|███▊      | 2689/7111 [11:42<37:14,  1.98it/s]

Reports:  38%|███▊      | 2690/7111 [11:42<30:46,  2.39it/s]

Reports:  38%|███▊      | 2691/7111 [11:42<25:51,  2.85it/s]

Reports:  38%|███▊      | 2692/7111 [11:42<22:17,  3.30it/s]

Reports:  38%|███▊      | 2693/7111 [11:42<19:45,  3.73it/s]

Reports:  38%|███▊      | 2694/7111 [11:43<18:06,  4.06it/s]

Reports:  38%|███▊      | 2695/7111 [11:43<16:53,  4.36it/s]

Reports:  38%|███▊      | 2696/7111 [11:43<16:29,  4.46it/s]

Reports:  38%|███▊      | 2697/7111 [11:43<15:44,  4.67it/s]

Reports:  38%|███▊      | 2698/7111 [11:43<15:31,  4.74it/s]

Reports:  38%|███▊      | 2699/7111 [11:44<15:37,  4.71it/s]

Reports:  38%|███▊      | 2700/7111 [11:44<15:34,  4.72it/s]

Reports:  38%|███▊      | 2701/7111 [11:44<15:04,  4.87it/s]

Reports:  38%|███▊      | 2702/7111 [11:44<14:47,  4.97it/s]

Reports:  38%|███▊      | 2703/7111 [11:44<14:35,  5.04it/s]

Reports:  38%|███▊      | 2704/7111 [11:45<14:29,  5.07it/s]

Reports:  38%|███▊      | 2705/7111 [11:45<14:40,  5.00it/s]

Reports:  38%|███▊      | 2706/7111 [11:45<14:28,  5.07it/s]

Reports:  38%|███▊      | 2707/7111 [11:45<14:21,  5.11it/s]

Reports:  38%|███▊      | 2708/7111 [11:45<14:25,  5.09it/s]

Reports:  38%|███▊      | 2709/7111 [11:46<14:35,  5.03it/s]

Reports:  38%|███▊      | 2710/7111 [11:46<14:29,  5.06it/s]

Reports:  38%|███▊      | 2711/7111 [11:46<14:35,  5.02it/s]

Reports:  38%|███▊      | 2712/7111 [11:46<14:23,  5.09it/s]

Reports:  38%|███▊      | 2713/7111 [11:46<14:23,  5.09it/s]

Reports:  38%|███▊      | 2714/7111 [11:47<14:26,  5.07it/s]

Reports:  38%|███▊      | 2715/7111 [11:47<14:31,  5.04it/s]

Reports:  38%|███▊      | 2716/7111 [11:47<14:15,  5.13it/s]

Reports:  38%|███▊      | 2717/7111 [11:47<14:31,  5.04it/s]

Reports:  38%|███▊      | 2718/7111 [11:47<14:33,  5.03it/s]

Reports:  38%|███▊      | 2719/7111 [11:48<14:36,  5.01it/s]

Reports:  38%|███▊      | 2720/7111 [11:48<14:34,  5.02it/s]

Reports:  38%|███▊      | 2721/7111 [11:48<14:32,  5.03it/s]

Reports:  38%|███▊      | 2722/7111 [11:49<33:43,  2.17it/s]

Reports:  38%|███▊      | 2723/7111 [11:49<28:18,  2.58it/s]

Reports:  38%|███▊      | 2724/7111 [11:49<23:59,  3.05it/s]

Reports:  38%|███▊      | 2725/7111 [11:50<21:10,  3.45it/s]

Reports:  38%|███▊      | 2726/7111 [11:50<18:53,  3.87it/s]

Reports:  38%|███▊      | 2727/7111 [11:50<17:20,  4.22it/s]

Reports:  38%|███▊      | 2728/7111 [11:50<16:14,  4.50it/s]

Reports:  38%|███▊      | 2729/7111 [11:50<15:27,  4.72it/s]

Reports:  38%|███▊      | 2730/7111 [11:51<15:33,  4.69it/s]

Reports:  38%|███▊      | 2731/7111 [11:51<15:07,  4.83it/s]

Reports:  38%|███▊      | 2732/7111 [11:51<14:48,  4.93it/s]

Reports:  38%|███▊      | 2733/7111 [11:51<14:37,  4.99it/s]

Reports:  38%|███▊      | 2734/7111 [11:51<14:33,  5.01it/s]

Reports:  38%|███▊      | 2735/7111 [11:52<14:16,  5.11it/s]

Reports:  38%|███▊      | 2736/7111 [11:52<14:04,  5.18it/s]

Reports:  38%|███▊      | 2737/7111 [11:52<14:07,  5.16it/s]

Reports:  39%|███▊      | 2738/7111 [11:52<14:06,  5.16it/s]

Reports:  39%|███▊      | 2739/7111 [11:52<13:59,  5.21it/s]

Reports:  39%|███▊      | 2740/7111 [11:53<13:57,  5.22it/s]

Reports:  39%|███▊      | 2741/7111 [11:53<14:03,  5.18it/s]

Reports:  39%|███▊      | 2742/7111 [11:53<13:56,  5.22it/s]

Reports:  39%|███▊      | 2743/7111 [11:53<13:50,  5.26it/s]

Reports:  39%|███▊      | 2744/7111 [11:53<13:48,  5.27it/s]

Reports:  39%|███▊      | 2745/7111 [11:53<13:51,  5.25it/s]

Reports:  39%|███▊      | 2746/7111 [11:54<13:59,  5.20it/s]

Reports:  39%|███▊      | 2747/7111 [11:54<14:05,  5.16it/s]

Reports:  39%|███▊      | 2748/7111 [11:54<13:49,  5.26it/s]

Reports:  39%|███▊      | 2749/7111 [11:54<14:12,  5.12it/s]

Reports:  39%|███▊      | 2750/7111 [11:54<14:05,  5.16it/s]

Reports:  39%|███▊      | 2751/7111 [11:55<13:57,  5.20it/s]

Reports:  39%|███▊      | 2752/7111 [11:55<16:15,  4.47it/s]

Reports:  39%|███▊      | 2753/7111 [11:55<15:49,  4.59it/s]

Reports:  39%|███▊      | 2754/7111 [11:55<15:20,  4.73it/s]

Reports:  39%|███▊      | 2755/7111 [11:56<15:10,  4.78it/s]

Reports:  39%|███▉      | 2756/7111 [11:56<14:55,  4.86it/s]

Reports:  39%|███▉      | 2757/7111 [11:56<14:53,  4.87it/s]

Reports:  39%|███▉      | 2758/7111 [11:56<14:42,  4.93it/s]

Reports:  39%|███▉      | 2759/7111 [11:56<14:43,  4.92it/s]

Reports:  39%|███▉      | 2760/7111 [11:57<14:51,  4.88it/s]

Reports:  39%|███▉      | 2761/7111 [11:57<14:29,  5.00it/s]

Reports:  39%|███▉      | 2762/7111 [11:57<14:25,  5.03it/s]

Reports:  39%|███▉      | 2763/7111 [11:57<14:13,  5.10it/s]

Reports:  39%|███▉      | 2764/7111 [11:57<14:21,  5.04it/s]

Reports:  39%|███▉      | 2765/7111 [11:58<14:19,  5.06it/s]

Reports:  39%|███▉      | 2766/7111 [11:58<14:25,  5.02it/s]

Reports:  39%|███▉      | 2767/7111 [11:58<14:21,  5.04it/s]

Reports:  39%|███▉      | 2768/7111 [11:58<14:22,  5.04it/s]

Reports:  39%|███▉      | 2769/7111 [11:58<14:10,  5.11it/s]

Reports:  39%|███▉      | 2770/7111 [11:59<14:29,  4.99it/s]

Reports:  39%|███▉      | 2771/7111 [11:59<14:37,  4.94it/s]

Reports:  39%|███▉      | 2772/7111 [11:59<14:18,  5.06it/s]

Reports:  39%|███▉      | 2773/7111 [11:59<14:26,  5.01it/s]

Reports:  39%|███▉      | 2774/7111 [12:00<26:37,  2.72it/s]

Reports:  39%|███▉      | 2775/7111 [12:00<22:41,  3.18it/s]

Reports:  39%|███▉      | 2776/7111 [12:00<20:01,  3.61it/s]

Reports:  39%|███▉      | 2777/7111 [12:00<18:10,  3.97it/s]

Reports:  39%|███▉      | 2778/7111 [12:01<17:17,  4.18it/s]

Reports:  39%|███▉      | 2779/7111 [12:01<16:18,  4.42it/s]

Reports:  39%|███▉      | 2780/7111 [12:01<15:44,  4.59it/s]

Reports:  39%|███▉      | 2781/7111 [12:01<15:42,  4.60it/s]

Reports:  39%|███▉      | 2782/7111 [12:01<14:59,  4.81it/s]

Reports:  39%|███▉      | 2783/7111 [12:02<14:49,  4.86it/s]

Reports:  39%|███▉      | 2784/7111 [12:02<14:36,  4.93it/s]

Reports:  39%|███▉      | 2785/7111 [12:02<14:26,  5.00it/s]

Reports:  39%|███▉      | 2786/7111 [12:02<14:03,  5.13it/s]

Reports:  39%|███▉      | 2787/7111 [12:02<14:07,  5.10it/s]

Reports:  39%|███▉      | 2788/7111 [12:03<13:58,  5.15it/s]

Reports:  39%|███▉      | 2789/7111 [12:03<13:54,  5.18it/s]

Reports:  39%|███▉      | 2790/7111 [12:03<13:53,  5.18it/s]

Reports:  39%|███▉      | 2791/7111 [12:03<13:44,  5.24it/s]

Reports:  39%|███▉      | 2792/7111 [12:04<23:59,  3.00it/s]

Reports:  39%|███▉      | 2793/7111 [12:04<20:58,  3.43it/s]

Reports:  39%|███▉      | 2794/7111 [12:04<18:54,  3.81it/s]

Reports:  39%|███▉      | 2795/7111 [12:04<17:17,  4.16it/s]

Reports:  39%|███▉      | 2796/7111 [12:05<16:46,  4.29it/s]

Reports:  39%|███▉      | 2797/7111 [12:05<15:53,  4.53it/s]

Reports:  39%|███▉      | 2798/7111 [12:05<15:21,  4.68it/s]

Reports:  39%|███▉      | 2799/7111 [12:05<14:49,  4.85it/s]

Reports:  39%|███▉      | 2800/7111 [12:05<14:39,  4.90it/s]

Reports:  39%|███▉      | 2801/7111 [12:06<15:28,  4.64it/s]

Reports:  39%|███▉      | 2802/7111 [12:06<15:16,  4.70it/s]

Reports:  39%|███▉      | 2803/7111 [12:06<15:45,  4.56it/s]

Reports:  39%|███▉      | 2804/7111 [12:06<15:04,  4.76it/s]

Reports:  39%|███▉      | 2805/7111 [12:06<14:44,  4.87it/s]

Reports:  39%|███▉      | 2806/7111 [12:07<14:37,  4.90it/s]

Reports:  39%|███▉      | 2807/7111 [12:07<14:18,  5.01it/s]

Reports:  39%|███▉      | 2808/7111 [12:07<14:35,  4.92it/s]

Reports:  40%|███▉      | 2809/7111 [12:07<14:27,  4.96it/s]

Reports:  40%|███▉      | 2810/7111 [12:07<14:28,  4.95it/s]

Reports:  40%|███▉      | 2811/7111 [12:08<14:21,  4.99it/s]

Reports:  40%|███▉      | 2812/7111 [12:08<14:01,  5.11it/s]

Reports:  40%|███▉      | 2813/7111 [12:08<13:55,  5.14it/s]

Reports:  40%|███▉      | 2814/7111 [12:08<13:42,  5.22it/s]

Reports:  40%|███▉      | 2815/7111 [12:08<13:42,  5.22it/s]

Reports:  40%|███▉      | 2816/7111 [12:09<14:03,  5.09it/s]

Reports:  40%|███▉      | 2817/7111 [12:09<14:12,  5.03it/s]

Reports:  40%|███▉      | 2818/7111 [12:09<14:19,  5.00it/s]

Reports:  40%|███▉      | 2819/7111 [12:09<14:24,  4.97it/s]

Reports:  40%|███▉      | 2820/7111 [12:09<14:12,  5.04it/s]

Reports:  40%|███▉      | 2821/7111 [12:10<14:19,  4.99it/s]

Reports:  40%|███▉      | 2822/7111 [12:10<14:08,  5.06it/s]

Reports:  40%|███▉      | 2823/7111 [12:10<13:57,  5.12it/s]

Reports:  40%|███▉      | 2824/7111 [12:10<13:48,  5.18it/s]

Reports:  40%|███▉      | 2825/7111 [12:10<13:57,  5.12it/s]

Reports:  40%|███▉      | 2826/7111 [12:11<13:52,  5.15it/s]

Reports:  40%|███▉      | 2827/7111 [12:11<13:49,  5.17it/s]

Reports:  40%|███▉      | 2828/7111 [12:11<13:50,  5.16it/s]

Reports:  40%|███▉      | 2829/7111 [12:11<13:44,  5.19it/s]

Reports:  40%|███▉      | 2830/7111 [12:11<13:40,  5.21it/s]

Reports:  40%|███▉      | 2831/7111 [12:12<13:38,  5.23it/s]

Reports:  40%|███▉      | 2832/7111 [12:12<13:45,  5.19it/s]

Reports:  40%|███▉      | 2833/7111 [12:12<13:41,  5.21it/s]

Reports:  40%|███▉      | 2834/7111 [12:12<13:35,  5.25it/s]

Reports:  40%|███▉      | 2835/7111 [12:12<13:40,  5.21it/s]

Reports:  40%|███▉      | 2836/7111 [12:13<13:33,  5.25it/s]

Reports:  40%|███▉      | 2837/7111 [12:13<13:29,  5.28it/s]

Reports:  40%|███▉      | 2838/7111 [12:13<13:23,  5.32it/s]

Reports:  40%|███▉      | 2839/7111 [12:13<13:40,  5.21it/s]

Reports:  40%|███▉      | 2840/7111 [12:13<13:37,  5.22it/s]

Reports:  40%|███▉      | 2841/7111 [12:13<13:49,  5.15it/s]

Reports:  40%|███▉      | 2842/7111 [12:14<13:43,  5.18it/s]

Reports:  40%|███▉      | 2843/7111 [12:14<14:04,  5.05it/s]

Reports:  40%|███▉      | 2844/7111 [12:14<13:51,  5.13it/s]

Reports:  40%|████      | 2845/7111 [12:14<14:06,  5.04it/s]

Reports:  40%|████      | 2846/7111 [12:14<14:00,  5.07it/s]

Reports:  40%|████      | 2847/7111 [12:15<13:55,  5.10it/s]

Reports:  40%|████      | 2848/7111 [12:15<13:53,  5.12it/s]

Reports:  40%|████      | 2849/7111 [12:15<13:41,  5.19it/s]

Reports:  40%|████      | 2850/7111 [12:15<13:34,  5.23it/s]

Reports:  40%|████      | 2851/7111 [12:15<13:31,  5.25it/s]

Reports:  40%|████      | 2852/7111 [12:16<14:14,  4.99it/s]

Reports:  40%|████      | 2853/7111 [12:16<14:05,  5.04it/s]

Reports:  40%|████      | 2854/7111 [12:16<14:48,  4.79it/s]

Reports:  40%|████      | 2855/7111 [12:16<14:32,  4.88it/s]

Reports:  40%|████      | 2856/7111 [12:17<14:55,  4.75it/s]

Reports:  40%|████      | 2857/7111 [12:17<14:34,  4.86it/s]

Reports:  40%|████      | 2858/7111 [12:17<14:17,  4.96it/s]

Reports:  40%|████      | 2859/7111 [12:17<14:00,  5.06it/s]

Reports:  40%|████      | 2860/7111 [12:17<13:49,  5.13it/s]

Reports:  40%|████      | 2861/7111 [12:17<13:46,  5.14it/s]

Reports:  40%|████      | 2862/7111 [12:18<13:40,  5.18it/s]

Reports:  40%|████      | 2863/7111 [12:18<13:42,  5.17it/s]

Reports:  40%|████      | 2864/7111 [12:18<13:49,  5.12it/s]

Reports:  40%|████      | 2865/7111 [12:18<13:42,  5.16it/s]

Reports:  40%|████      | 2866/7111 [12:18<13:36,  5.20it/s]

Reports:  40%|████      | 2867/7111 [12:19<13:46,  5.13it/s]

Reports:  40%|████      | 2868/7111 [12:19<14:10,  4.99it/s]

Reports:  40%|████      | 2869/7111 [12:19<14:03,  5.03it/s]

Reports:  40%|████      | 2870/7111 [12:19<14:44,  4.80it/s]

Reports:  40%|████      | 2871/7111 [12:19<14:21,  4.92it/s]

Reports:  40%|████      | 2872/7111 [12:20<14:15,  4.95it/s]

Reports:  40%|████      | 2873/7111 [12:20<14:15,  4.95it/s]

Reports:  40%|████      | 2874/7111 [12:20<13:56,  5.06it/s]

Reports:  40%|████      | 2875/7111 [12:20<13:41,  5.16it/s]

Reports:  40%|████      | 2876/7111 [12:20<13:35,  5.19it/s]

Reports:  40%|████      | 2877/7111 [12:21<13:44,  5.14it/s]

Reports:  40%|████      | 2878/7111 [12:21<13:37,  5.18it/s]

Reports:  40%|████      | 2879/7111 [12:21<13:36,  5.18it/s]

Reports:  41%|████      | 2880/7111 [12:21<14:32,  4.85it/s]

Reports:  41%|████      | 2881/7111 [12:21<14:20,  4.92it/s]

Reports:  41%|████      | 2882/7111 [12:22<14:20,  4.92it/s]

Reports:  41%|████      | 2883/7111 [12:22<14:05,  5.00it/s]

Reports:  41%|████      | 2884/7111 [12:22<14:09,  4.98it/s]

Reports:  41%|████      | 2885/7111 [12:22<14:27,  4.87it/s]

Reports:  41%|████      | 2886/7111 [12:22<14:10,  4.97it/s]

Reports:  41%|████      | 2887/7111 [12:23<14:01,  5.02it/s]

Reports:  41%|████      | 2888/7111 [12:23<13:45,  5.12it/s]

Reports:  41%|████      | 2889/7111 [12:23<14:01,  5.02it/s]

Reports:  41%|████      | 2890/7111 [12:23<13:57,  5.04it/s]

Reports:  41%|████      | 2891/7111 [12:23<14:03,  5.00it/s]

Reports:  41%|████      | 2892/7111 [12:24<13:53,  5.06it/s]

Reports:  41%|████      | 2893/7111 [12:24<13:51,  5.08it/s]

Reports:  41%|████      | 2894/7111 [12:24<13:36,  5.16it/s]

Reports:  41%|████      | 2895/7111 [12:24<13:24,  5.24it/s]

Reports:  41%|████      | 2896/7111 [12:24<13:24,  5.24it/s]

Reports:  41%|████      | 2897/7111 [12:25<13:16,  5.29it/s]

Reports:  41%|████      | 2898/7111 [12:25<13:38,  5.15it/s]

Reports:  41%|████      | 2899/7111 [12:25<13:43,  5.11it/s]

Reports:  41%|████      | 2900/7111 [12:25<13:33,  5.17it/s]

Reports:  41%|████      | 2901/7111 [12:25<13:24,  5.24it/s]

Reports:  41%|████      | 2902/7111 [12:26<14:05,  4.98it/s]

Reports:  41%|████      | 2903/7111 [12:26<13:46,  5.09it/s]

Reports:  41%|████      | 2904/7111 [12:26<13:45,  5.09it/s]

Reports:  41%|████      | 2905/7111 [12:26<13:33,  5.17it/s]

Reports:  41%|████      | 2906/7111 [12:26<13:54,  5.04it/s]

Reports:  41%|████      | 2907/7111 [12:27<13:53,  5.04it/s]

Reports:  41%|████      | 2908/7111 [12:27<13:51,  5.05it/s]

Reports:  41%|████      | 2909/7111 [12:27<13:41,  5.12it/s]

Reports:  41%|████      | 2910/7111 [12:27<13:59,  5.00it/s]

Reports:  41%|████      | 2911/7111 [12:27<13:54,  5.03it/s]

Reports:  41%|████      | 2912/7111 [12:28<13:46,  5.08it/s]

Reports:  41%|████      | 2913/7111 [12:28<13:45,  5.08it/s]

Reports:  41%|████      | 2914/7111 [12:28<13:32,  5.17it/s]

Reports:  41%|████      | 2915/7111 [12:28<13:52,  5.04it/s]

Reports:  41%|████      | 2916/7111 [12:28<13:49,  5.06it/s]

Reports:  41%|████      | 2917/7111 [12:29<13:39,  5.12it/s]

Reports:  41%|████      | 2918/7111 [12:29<13:43,  5.09it/s]

Reports:  41%|████      | 2919/7111 [12:29<13:58,  5.00it/s]

Reports:  41%|████      | 2920/7111 [12:29<13:58,  5.00it/s]

Reports:  41%|████      | 2921/7111 [12:29<14:07,  4.95it/s]

Reports:  41%|████      | 2922/7111 [12:30<13:58,  5.00it/s]

Reports:  41%|████      | 2923/7111 [12:30<14:01,  4.98it/s]

Reports:  41%|████      | 2924/7111 [12:30<13:51,  5.04it/s]

Reports:  41%|████      | 2925/7111 [12:30<13:39,  5.11it/s]

Reports:  41%|████      | 2926/7111 [12:30<13:25,  5.19it/s]

Reports:  41%|████      | 2927/7111 [12:30<13:31,  5.16it/s]

Reports:  41%|████      | 2928/7111 [12:31<13:37,  5.11it/s]

Reports:  41%|████      | 2929/7111 [12:31<13:21,  5.22it/s]

Reports:  41%|████      | 2930/7111 [12:31<13:38,  5.11it/s]

Reports:  41%|████      | 2931/7111 [12:31<13:39,  5.10it/s]

Reports:  41%|████      | 2932/7111 [12:31<13:34,  5.13it/s]

Reports:  41%|████      | 2933/7111 [12:32<15:20,  4.54it/s]

Reports:  41%|████▏     | 2934/7111 [12:32<14:40,  4.75it/s]

Reports:  41%|████▏     | 2935/7111 [12:32<14:26,  4.82it/s]

Reports:  41%|████▏     | 2936/7111 [12:32<14:16,  4.88it/s]

Reports:  41%|████▏     | 2937/7111 [12:33<13:51,  5.02it/s]

Reports:  41%|████▏     | 2938/7111 [12:33<13:55,  4.99it/s]

Reports:  41%|████▏     | 2939/7111 [12:33<13:57,  4.98it/s]

Reports:  41%|████▏     | 2940/7111 [12:33<14:08,  4.91it/s]

Reports:  41%|████▏     | 2941/7111 [12:33<13:51,  5.01it/s]

Reports:  41%|████▏     | 2942/7111 [12:34<13:41,  5.07it/s]

Reports:  41%|████▏     | 2943/7111 [12:34<13:28,  5.16it/s]

Reports:  41%|████▏     | 2944/7111 [12:34<13:21,  5.20it/s]

Reports:  41%|████▏     | 2945/7111 [12:34<13:12,  5.26it/s]

Reports:  41%|████▏     | 2946/7111 [12:34<13:09,  5.27it/s]

Reports:  41%|████▏     | 2947/7111 [12:34<13:16,  5.22it/s]

Reports:  41%|████▏     | 2948/7111 [12:35<13:20,  5.20it/s]

Reports:  41%|████▏     | 2949/7111 [12:35<13:10,  5.26it/s]

Reports:  41%|████▏     | 2950/7111 [12:35<13:14,  5.24it/s]

Reports:  41%|████▏     | 2951/7111 [12:35<13:22,  5.18it/s]

Reports:  42%|████▏     | 2952/7111 [12:35<13:28,  5.14it/s]

Reports:  42%|████▏     | 2953/7111 [12:36<13:29,  5.14it/s]

Reports:  42%|████▏     | 2954/7111 [12:36<13:29,  5.13it/s]

Reports:  42%|████▏     | 2955/7111 [12:36<13:29,  5.13it/s]

Reports:  42%|████▏     | 2956/7111 [12:36<14:23,  4.81it/s]

Reports:  42%|████▏     | 2957/7111 [12:36<14:00,  4.94it/s]

Reports:  42%|████▏     | 2958/7111 [12:37<14:00,  4.94it/s]

Reports:  42%|████▏     | 2959/7111 [12:37<13:51,  4.99it/s]

Reports:  42%|████▏     | 2960/7111 [12:37<13:37,  5.08it/s]

Reports:  42%|████▏     | 2961/7111 [12:37<13:33,  5.10it/s]

Reports:  42%|████▏     | 2962/7111 [12:37<13:32,  5.11it/s]

Reports:  42%|████▏     | 2963/7111 [12:38<13:41,  5.05it/s]

Reports:  42%|████▏     | 2964/7111 [12:38<13:49,  5.00it/s]

Reports:  42%|████▏     | 2965/7111 [12:38<13:55,  4.96it/s]

Reports:  42%|████▏     | 2966/7111 [12:38<13:52,  4.98it/s]

Reports:  42%|████▏     | 2967/7111 [12:38<13:33,  5.09it/s]

Reports:  42%|████▏     | 2968/7111 [12:39<13:42,  5.04it/s]

Reports:  42%|████▏     | 2969/7111 [12:39<13:31,  5.11it/s]

Reports:  42%|████▏     | 2970/7111 [12:39<13:20,  5.17it/s]

Reports:  42%|████▏     | 2971/7111 [12:39<13:19,  5.18it/s]

Reports:  42%|████▏     | 2972/7111 [12:39<13:15,  5.20it/s]

Reports:  42%|████▏     | 2973/7111 [12:40<13:18,  5.19it/s]

Reports:  42%|████▏     | 2974/7111 [12:40<13:18,  5.18it/s]

Reports:  42%|████▏     | 2975/7111 [12:40<13:06,  5.26it/s]

Reports:  42%|████▏     | 2976/7111 [12:40<13:19,  5.17it/s]

Reports:  42%|████▏     | 2977/7111 [12:40<13:17,  5.18it/s]

Reports:  42%|████▏     | 2978/7111 [12:41<13:19,  5.17it/s]

Reports:  42%|████▏     | 2979/7111 [12:41<13:17,  5.18it/s]

Reports:  42%|████▏     | 2980/7111 [12:41<13:15,  5.19it/s]

Reports:  42%|████▏     | 2981/7111 [12:41<13:24,  5.14it/s]

Reports:  42%|████▏     | 2982/7111 [12:41<13:21,  5.15it/s]

Reports:  42%|████▏     | 2983/7111 [12:41<13:11,  5.22it/s]

Reports:  42%|████▏     | 2984/7111 [12:42<13:03,  5.27it/s]

Reports:  42%|████▏     | 2985/7111 [12:42<13:03,  5.26it/s]

Reports:  42%|████▏     | 2986/7111 [12:42<13:36,  5.05it/s]

Reports:  42%|████▏     | 2987/7111 [12:42<14:21,  4.79it/s]

Reports:  42%|████▏     | 2988/7111 [12:43<13:54,  4.94it/s]

Reports:  42%|████▏     | 2989/7111 [12:43<13:33,  5.07it/s]

Reports:  42%|████▏     | 2990/7111 [12:43<13:14,  5.19it/s]

Reports:  42%|████▏     | 2991/7111 [12:43<13:01,  5.28it/s]

Reports:  42%|████▏     | 2992/7111 [12:43<13:18,  5.16it/s]

Reports:  42%|████▏     | 2993/7111 [12:43<13:05,  5.24it/s]

Reports:  42%|████▏     | 2994/7111 [12:44<13:27,  5.10it/s]

Reports:  42%|████▏     | 2995/7111 [12:44<13:09,  5.21it/s]

Reports:  42%|████▏     | 2996/7111 [12:44<13:18,  5.15it/s]

Reports:  42%|████▏     | 2997/7111 [12:44<13:07,  5.22it/s]

Reports:  42%|████▏     | 2998/7111 [12:44<12:58,  5.29it/s]

Reports:  42%|████▏     | 2999/7111 [12:45<13:35,  5.04it/s]

Reports:  42%|████▏     | 3000/7111 [12:45<13:25,  5.11it/s]

Reports:  42%|████▏     | 3001/7111 [12:45<13:25,  5.10it/s]

Reports:  42%|████▏     | 3002/7111 [12:45<13:25,  5.10it/s]

Reports:  42%|████▏     | 3003/7111 [12:45<13:39,  5.01it/s]

Reports:  42%|████▏     | 3004/7111 [12:46<13:38,  5.02it/s]

Reports:  42%|████▏     | 3005/7111 [12:46<13:31,  5.06it/s]

Reports:  42%|████▏     | 3006/7111 [12:46<13:32,  5.05it/s]

Reports:  42%|████▏     | 3007/7111 [12:46<13:19,  5.13it/s]

Reports:  42%|████▏     | 3008/7111 [12:46<13:21,  5.12it/s]

Reports:  42%|████▏     | 3009/7111 [12:47<13:30,  5.06it/s]

Reports:  42%|████▏     | 3010/7111 [12:47<13:19,  5.13it/s]

Reports:  42%|████▏     | 3011/7111 [12:47<13:21,  5.12it/s]

Reports:  42%|████▏     | 3012/7111 [12:47<13:24,  5.10it/s]

Reports:  42%|████▏     | 3013/7111 [12:47<13:11,  5.18it/s]

Reports:  42%|████▏     | 3014/7111 [12:48<13:23,  5.10it/s]

Reports:  42%|████▏     | 3015/7111 [12:48<13:10,  5.18it/s]

Reports:  42%|████▏     | 3016/7111 [12:48<13:21,  5.11it/s]

Reports:  42%|████▏     | 3017/7111 [12:48<13:43,  4.97it/s]

Reports:  42%|████▏     | 3018/7111 [12:48<13:28,  5.06it/s]

Reports:  42%|████▏     | 3019/7111 [12:49<13:23,  5.09it/s]

Reports:  42%|████▏     | 3020/7111 [12:49<13:30,  5.04it/s]

Reports:  42%|████▏     | 3021/7111 [12:49<13:15,  5.14it/s]

Reports:  42%|████▏     | 3022/7111 [12:49<13:22,  5.10it/s]

Reports:  43%|████▎     | 3023/7111 [12:49<13:14,  5.15it/s]

Reports:  43%|████▎     | 3024/7111 [12:50<13:05,  5.20it/s]

Reports:  43%|████▎     | 3025/7111 [12:50<13:09,  5.18it/s]

Reports:  43%|████▎     | 3026/7111 [12:50<13:07,  5.19it/s]

Reports:  43%|████▎     | 3027/7111 [12:50<13:11,  5.16it/s]

Reports:  43%|████▎     | 3028/7111 [12:50<13:13,  5.14it/s]

Reports:  43%|████▎     | 3029/7111 [12:50<13:09,  5.17it/s]

Reports:  43%|████▎     | 3030/7111 [12:51<13:04,  5.20it/s]

Reports:  43%|████▎     | 3031/7111 [12:51<13:07,  5.18it/s]

Reports:  43%|████▎     | 3032/7111 [12:51<13:05,  5.19it/s]

Reports:  43%|████▎     | 3033/7111 [12:51<15:32,  4.37it/s]

Reports:  43%|████▎     | 3034/7111 [12:52<14:48,  4.59it/s]

Reports:  43%|████▎     | 3035/7111 [12:52<14:23,  4.72it/s]

Reports:  43%|████▎     | 3036/7111 [12:52<13:53,  4.89it/s]

Reports:  43%|████▎     | 3037/7111 [12:52<13:40,  4.97it/s]

Reports:  43%|████▎     | 3038/7111 [12:52<13:25,  5.06it/s]

Reports:  43%|████▎     | 3039/7111 [12:53<13:25,  5.06it/s]

Reports:  43%|████▎     | 3040/7111 [12:53<13:37,  4.98it/s]

Reports:  43%|████▎     | 3041/7111 [12:53<13:21,  5.08it/s]

Reports:  43%|████▎     | 3042/7111 [12:53<13:28,  5.03it/s]

Reports:  43%|████▎     | 3043/7111 [12:53<13:25,  5.05it/s]

Reports:  43%|████▎     | 3044/7111 [12:54<13:13,  5.13it/s]

Reports:  43%|████▎     | 3045/7111 [12:54<13:07,  5.17it/s]

Reports:  43%|████▎     | 3046/7111 [12:54<13:15,  5.11it/s]

Reports:  43%|████▎     | 3047/7111 [12:54<13:11,  5.13it/s]

Reports:  43%|████▎     | 3048/7111 [12:54<13:01,  5.20it/s]

Reports:  43%|████▎     | 3049/7111 [12:54<12:52,  5.26it/s]

Reports:  43%|████▎     | 3050/7111 [12:55<13:09,  5.14it/s]

Reports:  43%|████▎     | 3051/7111 [12:55<13:06,  5.16it/s]

Reports:  43%|████▎     | 3052/7111 [12:55<13:03,  5.18it/s]

Reports:  43%|████▎     | 3053/7111 [12:55<13:26,  5.03it/s]

Reports:  43%|████▎     | 3054/7111 [12:55<13:11,  5.13it/s]

Reports:  43%|████▎     | 3055/7111 [12:56<12:58,  5.21it/s]

Reports:  43%|████▎     | 3056/7111 [12:56<13:06,  5.16it/s]

Reports:  43%|████▎     | 3057/7111 [12:56<12:49,  5.27it/s]

Reports:  43%|████▎     | 3058/7111 [12:56<13:06,  5.15it/s]

Reports:  43%|████▎     | 3059/7111 [12:56<13:06,  5.15it/s]

Reports:  43%|████▎     | 3060/7111 [12:57<13:03,  5.17it/s]

Reports:  43%|████▎     | 3061/7111 [12:57<13:08,  5.14it/s]

Reports:  43%|████▎     | 3062/7111 [12:57<13:01,  5.18it/s]

Reports:  43%|████▎     | 3063/7111 [12:57<12:51,  5.25it/s]

Reports:  43%|████▎     | 3064/7111 [12:57<12:45,  5.29it/s]

Reports:  43%|████▎     | 3065/7111 [12:58<12:46,  5.28it/s]

Reports:  43%|████▎     | 3066/7111 [12:58<12:44,  5.29it/s]

Reports:  43%|████▎     | 3067/7111 [12:58<12:52,  5.24it/s]

Reports:  43%|████▎     | 3068/7111 [12:58<12:51,  5.24it/s]

Reports:  43%|████▎     | 3069/7111 [12:58<12:50,  5.25it/s]

Reports:  43%|████▎     | 3070/7111 [12:59<12:49,  5.25it/s]

Reports:  43%|████▎     | 3071/7111 [12:59<13:01,  5.17it/s]

Reports:  43%|████▎     | 3072/7111 [12:59<13:03,  5.15it/s]

Reports:  43%|████▎     | 3073/7111 [12:59<13:33,  4.97it/s]

Reports:  43%|████▎     | 3074/7111 [12:59<13:28,  5.00it/s]

Reports:  43%|████▎     | 3075/7111 [13:00<13:09,  5.11it/s]

Reports:  43%|████▎     | 3076/7111 [13:00<13:11,  5.10it/s]

Reports:  43%|████▎     | 3077/7111 [13:00<13:08,  5.12it/s]

Reports:  43%|████▎     | 3078/7111 [13:00<12:45,  5.27it/s]

Reports:  43%|████▎     | 3079/7111 [13:00<12:54,  5.20it/s]

Reports:  43%|████▎     | 3080/7111 [13:00<13:18,  5.05it/s]

Reports:  43%|████▎     | 3081/7111 [13:01<13:03,  5.14it/s]

Reports:  43%|████▎     | 3082/7111 [13:01<13:08,  5.11it/s]

Reports:  43%|████▎     | 3083/7111 [13:01<13:07,  5.12it/s]

Reports:  43%|████▎     | 3084/7111 [13:01<13:19,  5.04it/s]

Reports:  43%|████▎     | 3085/7111 [13:01<13:04,  5.13it/s]

Reports:  43%|████▎     | 3086/7111 [13:02<13:19,  5.04it/s]

Reports:  43%|████▎     | 3087/7111 [13:02<13:06,  5.11it/s]

Reports:  43%|████▎     | 3088/7111 [13:02<12:57,  5.18it/s]

Reports:  43%|████▎     | 3089/7111 [13:02<12:52,  5.21it/s]

Reports:  43%|████▎     | 3090/7111 [13:02<12:47,  5.24it/s]

Reports:  43%|████▎     | 3091/7111 [13:03<12:54,  5.19it/s]

Reports:  43%|████▎     | 3092/7111 [13:03<13:10,  5.08it/s]

Reports:  43%|████▎     | 3093/7111 [13:03<12:55,  5.18it/s]

Reports:  44%|████▎     | 3094/7111 [13:03<13:03,  5.13it/s]

Reports:  44%|████▎     | 3095/7111 [13:03<12:51,  5.20it/s]

Reports:  44%|████▎     | 3096/7111 [13:04<12:59,  5.15it/s]

Reports:  44%|████▎     | 3097/7111 [13:04<12:52,  5.20it/s]

Reports:  44%|████▎     | 3098/7111 [13:04<12:41,  5.27it/s]

Reports:  44%|████▎     | 3099/7111 [13:04<12:46,  5.23it/s]

Reports:  44%|████▎     | 3100/7111 [13:04<13:11,  5.07it/s]

Reports:  44%|████▎     | 3101/7111 [13:05<13:05,  5.10it/s]

Reports:  44%|████▎     | 3102/7111 [13:05<12:56,  5.16it/s]

Reports:  44%|████▎     | 3103/7111 [13:05<12:45,  5.24it/s]

Reports:  44%|████▎     | 3104/7111 [13:05<12:44,  5.24it/s]

Reports:  44%|████▎     | 3105/7111 [13:05<13:00,  5.13it/s]

Reports:  44%|████▎     | 3106/7111 [13:06<13:12,  5.06it/s]

Reports:  44%|████▎     | 3107/7111 [13:06<12:58,  5.14it/s]

Reports:  44%|████▎     | 3108/7111 [13:06<13:12,  5.05it/s]

Reports:  44%|████▎     | 3109/7111 [13:06<13:06,  5.09it/s]

Reports:  44%|████▎     | 3110/7111 [13:06<13:33,  4.92it/s]

Reports:  44%|████▎     | 3111/7111 [13:07<13:16,  5.02it/s]

Reports:  44%|████▍     | 3112/7111 [13:07<12:59,  5.13it/s]

Reports:  44%|████▍     | 3113/7111 [13:07<12:44,  5.23it/s]

Reports:  44%|████▍     | 3114/7111 [13:07<13:12,  5.04it/s]

Reports:  44%|████▍     | 3115/7111 [13:07<13:04,  5.09it/s]

Reports:  44%|████▍     | 3116/7111 [13:07<12:57,  5.14it/s]

Reports:  44%|████▍     | 3117/7111 [13:08<12:57,  5.14it/s]

Reports:  44%|████▍     | 3118/7111 [13:08<12:53,  5.16it/s]

Reports:  44%|████▍     | 3119/7111 [13:08<13:01,  5.11it/s]

Reports:  44%|████▍     | 3120/7111 [13:08<13:05,  5.08it/s]

Reports:  44%|████▍     | 3121/7111 [13:08<12:54,  5.15it/s]

Reports:  44%|████▍     | 3122/7111 [13:09<12:47,  5.20it/s]

Reports:  44%|████▍     | 3123/7111 [13:09<12:51,  5.17it/s]

Reports:  44%|████▍     | 3124/7111 [13:09<12:45,  5.21it/s]

Reports:  44%|████▍     | 3125/7111 [13:09<12:54,  5.15it/s]

Reports:  44%|████▍     | 3126/7111 [13:09<12:48,  5.18it/s]

Reports:  44%|████▍     | 3127/7111 [13:10<13:33,  4.89it/s]

Reports:  44%|████▍     | 3128/7111 [13:10<13:15,  5.01it/s]

Reports:  44%|████▍     | 3129/7111 [13:10<13:04,  5.08it/s]

Reports:  44%|████▍     | 3130/7111 [13:10<12:52,  5.16it/s]

Reports:  44%|████▍     | 3131/7111 [13:10<12:36,  5.26it/s]

Reports:  44%|████▍     | 3132/7111 [13:11<12:34,  5.27it/s]

Reports:  44%|████▍     | 3133/7111 [13:11<12:27,  5.32it/s]

Reports:  44%|████▍     | 3134/7111 [13:11<12:56,  5.12it/s]

Reports:  44%|████▍     | 3135/7111 [13:11<12:49,  5.17it/s]

Reports:  44%|████▍     | 3136/7111 [13:11<12:46,  5.18it/s]

Reports:  44%|████▍     | 3137/7111 [13:12<12:53,  5.14it/s]

Reports:  44%|████▍     | 3138/7111 [13:12<12:56,  5.11it/s]

Reports:  44%|████▍     | 3139/7111 [13:12<12:53,  5.13it/s]

Reports:  44%|████▍     | 3140/7111 [13:14<56:19,  1.17it/s]

Reports:  44%|████▍     | 3141/7111 [13:15<43:05,  1.54it/s]

Reports:  44%|████▍     | 3142/7111 [13:15<33:57,  1.95it/s]

Reports:  44%|████▍     | 3143/7111 [13:15<28:56,  2.28it/s]

Reports:  44%|████▍     | 3144/7111 [13:15<24:13,  2.73it/s]

Reports:  44%|████▍     | 3145/7111 [13:15<20:52,  3.17it/s]

Reports:  44%|████▍     | 3146/7111 [13:16<18:39,  3.54it/s]

Reports:  44%|████▍     | 3147/7111 [13:16<16:50,  3.92it/s]

Reports:  44%|████▍     | 3148/7111 [13:16<15:47,  4.18it/s]

Reports:  44%|████▍     | 3149/7111 [13:16<14:57,  4.42it/s]

Reports:  44%|████▍     | 3150/7111 [13:16<14:14,  4.63it/s]

Reports:  44%|████▍     | 3151/7111 [13:17<13:46,  4.79it/s]

Reports:  44%|████▍     | 3152/7111 [13:17<13:23,  4.93it/s]

Reports:  44%|████▍     | 3153/7111 [13:17<13:11,  5.00it/s]

Reports:  44%|████▍     | 3154/7111 [13:17<12:58,  5.08it/s]

Reports:  44%|████▍     | 3155/7111 [13:17<13:02,  5.05it/s]

Reports:  44%|████▍     | 3156/7111 [13:18<12:47,  5.16it/s]

Reports:  44%|████▍     | 3157/7111 [13:18<12:38,  5.21it/s]

Reports:  44%|████▍     | 3158/7111 [13:18<12:41,  5.19it/s]

Reports:  44%|████▍     | 3159/7111 [13:18<12:29,  5.27it/s]

Reports:  44%|████▍     | 3160/7111 [13:18<12:32,  5.25it/s]

Reports:  44%|████▍     | 3161/7111 [13:18<12:32,  5.25it/s]

Reports:  44%|████▍     | 3162/7111 [13:19<12:51,  5.12it/s]

Reports:  44%|████▍     | 3163/7111 [13:19<12:57,  5.08it/s]

Reports:  44%|████▍     | 3164/7111 [13:19<13:01,  5.05it/s]

Reports:  45%|████▍     | 3165/7111 [13:19<16:36,  3.96it/s]

Reports:  45%|████▍     | 3166/7111 [13:20<15:18,  4.30it/s]

Reports:  45%|████▍     | 3167/7111 [13:20<14:22,  4.57it/s]

Reports:  45%|████▍     | 3168/7111 [13:20<13:56,  4.72it/s]

Reports:  45%|████▍     | 3169/7111 [13:20<13:56,  4.71it/s]

Reports:  45%|████▍     | 3170/7111 [13:20<13:28,  4.88it/s]

Reports:  45%|████▍     | 3171/7111 [13:21<13:12,  4.97it/s]

Reports:  45%|████▍     | 3172/7111 [13:21<12:58,  5.06it/s]

Reports:  45%|████▍     | 3173/7111 [13:21<12:48,  5.12it/s]

Reports:  45%|████▍     | 3174/7111 [13:21<13:10,  4.98it/s]

Reports:  45%|████▍     | 3175/7111 [13:21<13:10,  4.98it/s]

Reports:  45%|████▍     | 3176/7111 [13:22<12:51,  5.10it/s]

Reports:  45%|████▍     | 3177/7111 [13:22<12:45,  5.14it/s]

Reports:  45%|████▍     | 3178/7111 [13:22<12:40,  5.17it/s]

Reports:  45%|████▍     | 3179/7111 [13:22<12:32,  5.22it/s]

Reports:  45%|████▍     | 3180/7111 [13:22<12:36,  5.20it/s]

Reports:  45%|████▍     | 3181/7111 [13:23<12:43,  5.14it/s]

Reports:  45%|████▍     | 3182/7111 [13:23<12:29,  5.24it/s]

Reports:  45%|████▍     | 3183/7111 [13:23<12:30,  5.23it/s]

Reports:  45%|████▍     | 3184/7111 [13:23<12:40,  5.16it/s]

Reports:  45%|████▍     | 3185/7111 [13:23<12:45,  5.13it/s]

Reports:  45%|████▍     | 3186/7111 [13:24<12:43,  5.14it/s]

Reports:  45%|████▍     | 3187/7111 [13:24<12:45,  5.13it/s]

Reports:  45%|████▍     | 3188/7111 [13:24<12:50,  5.09it/s]

Reports:  45%|████▍     | 3189/7111 [13:24<13:17,  4.92it/s]

Reports:  45%|████▍     | 3190/7111 [13:24<13:22,  4.89it/s]

Reports:  45%|████▍     | 3191/7111 [13:25<13:03,  5.00it/s]

Reports:  45%|████▍     | 3192/7111 [13:25<12:53,  5.07it/s]

Reports:  45%|████▍     | 3193/7111 [13:25<12:50,  5.09it/s]

Reports:  45%|████▍     | 3194/7111 [13:25<14:13,  4.59it/s]

Reports:  45%|████▍     | 3195/7111 [13:25<13:37,  4.79it/s]

Reports:  45%|████▍     | 3196/7111 [13:26<13:13,  4.94it/s]

Reports:  45%|████▍     | 3197/7111 [13:27<32:43,  1.99it/s]

Reports:  45%|████▍     | 3198/7111 [13:27<27:08,  2.40it/s]

Reports:  45%|████▍     | 3199/7111 [13:27<22:41,  2.87it/s]

Reports:  45%|████▌     | 3200/7111 [13:27<19:38,  3.32it/s]

Reports:  45%|████▌     | 3201/7111 [13:28<17:38,  3.69it/s]

Reports:  45%|████▌     | 3202/7111 [13:28<16:03,  4.06it/s]

Reports:  45%|████▌     | 3203/7111 [13:28<14:58,  4.35it/s]

Reports:  45%|████▌     | 3204/7111 [13:28<14:08,  4.60it/s]

Reports:  45%|████▌     | 3205/7111 [13:28<13:37,  4.78it/s]

Reports:  45%|████▌     | 3206/7111 [13:29<13:35,  4.79it/s]

Reports:  45%|████▌     | 3207/7111 [13:29<13:19,  4.88it/s]

Reports:  45%|████▌     | 3208/7111 [13:29<13:13,  4.92it/s]

Reports:  45%|████▌     | 3209/7111 [13:29<14:01,  4.64it/s]

Reports:  45%|████▌     | 3210/7111 [13:29<13:42,  4.74it/s]

Reports:  45%|████▌     | 3211/7111 [13:30<26:56,  2.41it/s]

Reports:  45%|████▌     | 3212/7111 [13:30<22:54,  2.84it/s]

Reports:  45%|████▌     | 3213/7111 [13:31<19:59,  3.25it/s]

Reports:  45%|████▌     | 3214/7111 [13:31<17:37,  3.68it/s]

Reports:  45%|████▌     | 3215/7111 [13:31<16:01,  4.05it/s]

Reports:  45%|████▌     | 3216/7111 [13:31<14:55,  4.35it/s]

Reports:  45%|████▌     | 3217/7111 [13:31<14:06,  4.60it/s]

Reports:  45%|████▌     | 3218/7111 [13:32<14:02,  4.62it/s]

Reports:  45%|████▌     | 3219/7111 [13:32<13:36,  4.77it/s]

Reports:  45%|████▌     | 3220/7111 [13:32<13:22,  4.85it/s]

Reports:  45%|████▌     | 3221/7111 [13:32<13:15,  4.89it/s]

Reports:  45%|████▌     | 3222/7111 [13:32<13:00,  4.98it/s]

Reports:  45%|████▌     | 3223/7111 [13:33<13:06,  4.95it/s]

Reports:  45%|████▌     | 3224/7111 [13:33<12:52,  5.03it/s]

Reports:  45%|████▌     | 3225/7111 [13:33<12:50,  5.04it/s]

Reports:  45%|████▌     | 3226/7111 [13:33<12:42,  5.09it/s]

Reports:  45%|████▌     | 3227/7111 [13:33<12:31,  5.17it/s]

Reports:  45%|████▌     | 3228/7111 [13:34<21:27,  3.02it/s]

Reports:  45%|████▌     | 3229/7111 [13:34<18:53,  3.42it/s]

Reports:  45%|████▌     | 3230/7111 [13:36<42:45,  1.51it/s]

Reports:  45%|████▌     | 3231/7111 [13:36<33:51,  1.91it/s]

Reports:  45%|████▌     | 3232/7111 [13:36<27:34,  2.34it/s]

Reports:  45%|████▌     | 3233/7111 [13:36<22:57,  2.81it/s]

Reports:  45%|████▌     | 3234/7111 [13:37<20:05,  3.22it/s]

Reports:  45%|████▌     | 3235/7111 [13:37<18:03,  3.58it/s]

Reports:  46%|████▌     | 3236/7111 [13:37<16:18,  3.96it/s]

Reports:  46%|████▌     | 3237/7111 [13:37<15:11,  4.25it/s]

Reports:  46%|████▌     | 3238/7111 [13:37<14:24,  4.48it/s]

Reports:  46%|████▌     | 3239/7111 [13:38<13:59,  4.61it/s]

Reports:  46%|████▌     | 3240/7111 [13:38<13:38,  4.73it/s]

Reports:  46%|████▌     | 3241/7111 [13:38<13:15,  4.86it/s]

Reports:  46%|████▌     | 3242/7111 [13:38<12:58,  4.97it/s]

Reports:  46%|████▌     | 3243/7111 [13:38<13:06,  4.91it/s]

Reports:  46%|████▌     | 3244/7111 [13:39<13:12,  4.88it/s]

Reports:  46%|████▌     | 3245/7111 [13:39<18:28,  3.49it/s]

Reports:  46%|████▌     | 3246/7111 [13:39<16:54,  3.81it/s]

Reports:  46%|████▌     | 3247/7111 [13:39<15:24,  4.18it/s]

Reports:  46%|████▌     | 3248/7111 [13:40<14:28,  4.45it/s]

Reports:  46%|████▌     | 3249/7111 [13:40<13:48,  4.66it/s]

Reports:  46%|████▌     | 3250/7111 [13:40<13:12,  4.87it/s]

Reports:  46%|████▌     | 3251/7111 [13:40<13:03,  4.93it/s]

Reports:  46%|████▌     | 3252/7111 [13:40<13:04,  4.92it/s]

Reports:  46%|████▌     | 3253/7111 [13:41<12:48,  5.02it/s]

Reports:  46%|████▌     | 3254/7111 [13:41<12:38,  5.08it/s]

Reports:  46%|████▌     | 3255/7111 [13:41<16:29,  3.90it/s]

Reports:  46%|████▌     | 3256/7111 [13:42<25:33,  2.51it/s]

Reports:  46%|████▌     | 3257/7111 [13:42<21:57,  2.92it/s]

Reports:  46%|████▌     | 3258/7111 [13:42<19:07,  3.36it/s]

Reports:  46%|████▌     | 3259/7111 [13:42<17:00,  3.78it/s]

Reports:  46%|████▌     | 3260/7111 [13:43<15:49,  4.06it/s]

Reports:  46%|████▌     | 3261/7111 [13:43<14:41,  4.37it/s]

Reports:  46%|████▌     | 3262/7111 [13:43<14:03,  4.57it/s]

Reports:  46%|████▌     | 3263/7111 [13:43<13:40,  4.69it/s]

Reports:  46%|████▌     | 3264/7111 [13:43<13:32,  4.73it/s]

Reports:  46%|████▌     | 3265/7111 [13:44<13:26,  4.77it/s]

Reports:  46%|████▌     | 3266/7111 [13:44<13:01,  4.92it/s]

Reports:  46%|████▌     | 3267/7111 [13:44<12:58,  4.94it/s]

Reports:  46%|████▌     | 3268/7111 [13:44<12:52,  4.97it/s]

Reports:  46%|████▌     | 3269/7111 [13:44<12:53,  4.97it/s]

Reports:  46%|████▌     | 3270/7111 [13:45<12:55,  4.95it/s]

Reports:  46%|████▌     | 3271/7111 [13:45<12:38,  5.07it/s]

Reports:  46%|████▌     | 3272/7111 [13:45<12:29,  5.12it/s]

Reports:  46%|████▌     | 3273/7111 [13:45<12:34,  5.09it/s]

Reports:  46%|████▌     | 3274/7111 [13:45<12:27,  5.14it/s]

Reports:  46%|████▌     | 3275/7111 [13:46<12:32,  5.10it/s]

Reports:  46%|████▌     | 3276/7111 [13:46<12:19,  5.18it/s]

Reports:  46%|████▌     | 3277/7111 [13:46<12:11,  5.24it/s]

Reports:  46%|████▌     | 3278/7111 [13:46<12:20,  5.18it/s]

Reports:  46%|████▌     | 3279/7111 [13:46<12:19,  5.19it/s]

Reports:  46%|████▌     | 3280/7111 [13:47<12:34,  5.08it/s]

Reports:  46%|████▌     | 3281/7111 [13:47<12:46,  4.99it/s]

Reports:  46%|████▌     | 3282/7111 [13:47<12:38,  5.05it/s]

Reports:  46%|████▌     | 3283/7111 [13:47<12:30,  5.10it/s]

Reports:  46%|████▌     | 3284/7111 [13:47<12:19,  5.18it/s]

Reports:  46%|████▌     | 3285/7111 [13:48<12:21,  5.16it/s]

Reports:  46%|████▌     | 3286/7111 [13:48<12:21,  5.16it/s]

Reports:  46%|████▌     | 3287/7111 [13:48<12:15,  5.20it/s]

Reports:  46%|████▌     | 3288/7111 [13:48<12:22,  5.15it/s]

Reports:  46%|████▋     | 3289/7111 [13:48<12:16,  5.19it/s]

Reports:  46%|████▋     | 3290/7111 [13:49<12:17,  5.18it/s]

Reports:  46%|████▋     | 3291/7111 [13:49<12:10,  5.23it/s]

Reports:  46%|████▋     | 3292/7111 [13:49<12:05,  5.26it/s]

Reports:  46%|████▋     | 3293/7111 [13:49<12:22,  5.14it/s]

Reports:  46%|████▋     | 3294/7111 [13:49<12:13,  5.20it/s]

Reports:  46%|████▋     | 3295/7111 [13:50<12:12,  5.21it/s]

Reports:  46%|████▋     | 3296/7111 [13:50<12:20,  5.15it/s]

Reports:  46%|████▋     | 3297/7111 [13:50<12:07,  5.24it/s]

Reports:  46%|████▋     | 3298/7111 [13:50<12:15,  5.18it/s]

Reports:  46%|████▋     | 3299/7111 [13:50<12:35,  5.05it/s]

Reports:  46%|████▋     | 3300/7111 [13:51<13:33,  4.68it/s]

Reports:  46%|████▋     | 3301/7111 [13:51<13:15,  4.79it/s]

Reports:  46%|████▋     | 3302/7111 [13:51<13:20,  4.76it/s]

Reports:  46%|████▋     | 3303/7111 [13:51<12:54,  4.92it/s]

Reports:  46%|████▋     | 3304/7111 [13:51<13:08,  4.83it/s]

Reports:  46%|████▋     | 3305/7111 [13:52<12:49,  4.94it/s]

Reports:  46%|████▋     | 3306/7111 [13:52<12:51,  4.93it/s]

Reports:  47%|████▋     | 3307/7111 [13:52<12:30,  5.07it/s]

Reports:  47%|████▋     | 3308/7111 [13:52<12:28,  5.08it/s]

Reports:  47%|████▋     | 3309/7111 [13:52<12:32,  5.05it/s]

Reports:  47%|████▋     | 3310/7111 [13:53<12:17,  5.15it/s]

Reports:  47%|████▋     | 3311/7111 [13:53<12:25,  5.10it/s]

Reports:  47%|████▋     | 3312/7111 [13:53<12:28,  5.07it/s]

Reports:  47%|████▋     | 3313/7111 [13:53<12:31,  5.05it/s]

Reports:  47%|████▋     | 3314/7111 [13:53<12:36,  5.02it/s]

Reports:  47%|████▋     | 3315/7111 [13:54<12:18,  5.14it/s]

Reports:  47%|████▋     | 3316/7111 [13:54<12:05,  5.23it/s]

Reports:  47%|████▋     | 3317/7111 [13:54<12:05,  5.23it/s]

Reports:  47%|████▋     | 3318/7111 [13:54<11:58,  5.28it/s]

Reports:  47%|████▋     | 3319/7111 [13:54<11:59,  5.27it/s]

Reports:  47%|████▋     | 3320/7111 [13:54<12:03,  5.24it/s]

Reports:  47%|████▋     | 3321/7111 [13:55<12:01,  5.25it/s]

Reports:  47%|████▋     | 3322/7111 [13:55<12:15,  5.15it/s]

Reports:  47%|████▋     | 3323/7111 [13:55<12:09,  5.20it/s]

Reports:  47%|████▋     | 3324/7111 [13:55<12:20,  5.12it/s]

Reports:  47%|████▋     | 3325/7111 [13:55<12:08,  5.19it/s]

Reports:  47%|████▋     | 3326/7111 [13:56<12:05,  5.21it/s]

Reports:  47%|████▋     | 3327/7111 [13:56<12:03,  5.23it/s]

Reports:  47%|████▋     | 3328/7111 [13:56<12:16,  5.14it/s]

Reports:  47%|████▋     | 3329/7111 [13:56<12:05,  5.21it/s]

Reports:  47%|████▋     | 3330/7111 [13:56<11:55,  5.28it/s]

Reports:  47%|████▋     | 3331/7111 [13:57<12:09,  5.18it/s]

Reports:  47%|████▋     | 3332/7111 [13:57<12:12,  5.16it/s]

Reports:  47%|████▋     | 3333/7111 [13:58<23:13,  2.71it/s]

Reports:  47%|████▋     | 3334/7111 [13:58<19:46,  3.18it/s]

Reports:  47%|████▋     | 3335/7111 [13:58<17:22,  3.62it/s]

Reports:  47%|████▋     | 3336/7111 [13:58<15:45,  3.99it/s]

Reports:  47%|████▋     | 3337/7111 [13:58<14:43,  4.27it/s]

Reports:  47%|████▋     | 3338/7111 [13:59<14:11,  4.43it/s]

Reports:  47%|████▋     | 3339/7111 [13:59<13:35,  4.63it/s]

Reports:  47%|████▋     | 3340/7111 [13:59<13:12,  4.76it/s]

Reports:  47%|████▋     | 3341/7111 [13:59<13:06,  4.79it/s]

Reports:  47%|████▋     | 3342/7111 [13:59<12:56,  4.86it/s]

Reports:  47%|████▋     | 3343/7111 [13:59<12:30,  5.02it/s]

Reports:  47%|████▋     | 3344/7111 [14:00<12:21,  5.08it/s]

Reports:  47%|████▋     | 3345/7111 [14:00<12:27,  5.04it/s]

Reports:  47%|████▋     | 3346/7111 [14:00<12:15,  5.12it/s]

Reports:  47%|████▋     | 3347/7111 [14:00<12:06,  5.18it/s]

Reports:  47%|████▋     | 3348/7111 [14:00<12:23,  5.06it/s]

Reports:  47%|████▋     | 3349/7111 [14:01<12:11,  5.14it/s]

Reports:  47%|████▋     | 3350/7111 [14:01<12:16,  5.11it/s]

Reports:  47%|████▋     | 3351/7111 [14:01<12:14,  5.12it/s]

Reports:  47%|████▋     | 3352/7111 [14:01<12:00,  5.22it/s]

Reports:  47%|████▋     | 3353/7111 [14:01<11:54,  5.26it/s]

Reports:  47%|████▋     | 3354/7111 [14:02<11:55,  5.25it/s]

Reports:  47%|████▋     | 3355/7111 [14:02<11:49,  5.29it/s]

Reports:  47%|████▋     | 3356/7111 [14:02<12:00,  5.21it/s]

Reports:  47%|████▋     | 3357/7111 [14:02<12:06,  5.17it/s]

Reports:  47%|████▋     | 3358/7111 [14:02<12:05,  5.17it/s]

Reports:  47%|████▋     | 3359/7111 [14:03<11:59,  5.22it/s]

Reports:  47%|████▋     | 3360/7111 [14:03<12:00,  5.21it/s]

Reports:  47%|████▋     | 3361/7111 [14:03<18:05,  3.45it/s]

Reports:  47%|████▋     | 3362/7111 [14:03<16:37,  3.76it/s]

Reports:  47%|████▋     | 3363/7111 [14:04<15:11,  4.11it/s]

Reports:  47%|████▋     | 3364/7111 [14:04<14:05,  4.43it/s]

Reports:  47%|████▋     | 3365/7111 [14:04<13:46,  4.53it/s]

Reports:  47%|████▋     | 3366/7111 [14:05<22:36,  2.76it/s]

Reports:  47%|████▋     | 3367/7111 [14:05<19:23,  3.22it/s]

Reports:  47%|████▋     | 3368/7111 [14:05<17:22,  3.59it/s]

Reports:  47%|████▋     | 3369/7111 [14:05<15:45,  3.96it/s]

Reports:  47%|████▋     | 3370/7111 [14:06<14:40,  4.25it/s]

Reports:  47%|████▋     | 3371/7111 [14:06<13:54,  4.48it/s]

Reports:  47%|████▋     | 3372/7111 [14:06<13:08,  4.74it/s]

Reports:  47%|████▋     | 3373/7111 [14:06<12:55,  4.82it/s]

Reports:  47%|████▋     | 3374/7111 [14:06<12:34,  4.95it/s]

Reports:  47%|████▋     | 3375/7111 [14:06<12:14,  5.09it/s]

Reports:  47%|████▋     | 3376/7111 [14:07<12:04,  5.15it/s]

Reports:  47%|████▋     | 3377/7111 [14:07<11:59,  5.19it/s]

Reports:  48%|████▊     | 3378/7111 [14:07<11:57,  5.21it/s]

Reports:  48%|████▊     | 3379/7111 [14:07<11:50,  5.26it/s]

Reports:  48%|████▊     | 3380/7111 [14:07<11:59,  5.19it/s]

Reports:  48%|████▊     | 3381/7111 [14:08<11:50,  5.25it/s]

Reports:  48%|████▊     | 3382/7111 [14:09<25:47,  2.41it/s]

Reports:  48%|████▊     | 3383/7111 [14:09<21:31,  2.89it/s]

Reports:  48%|████▊     | 3384/7111 [14:09<18:35,  3.34it/s]

Reports:  48%|████▊     | 3385/7111 [14:09<16:42,  3.72it/s]

Reports:  48%|████▊     | 3386/7111 [14:09<15:08,  4.10it/s]

Reports:  48%|████▊     | 3387/7111 [14:10<14:11,  4.37it/s]

Reports:  48%|████▊     | 3388/7111 [14:10<13:31,  4.59it/s]

Reports:  48%|████▊     | 3389/7111 [14:10<13:07,  4.73it/s]

Reports:  48%|████▊     | 3390/7111 [14:10<12:52,  4.82it/s]

Reports:  48%|████▊     | 3391/7111 [14:10<12:33,  4.93it/s]

Reports:  48%|████▊     | 3392/7111 [14:11<12:28,  4.97it/s]

Reports:  48%|████▊     | 3393/7111 [14:11<12:10,  5.09it/s]

Reports:  48%|████▊     | 3394/7111 [14:11<12:21,  5.02it/s]

Reports:  48%|████▊     | 3395/7111 [14:11<12:08,  5.10it/s]

Reports:  48%|████▊     | 3396/7111 [14:11<12:08,  5.10it/s]

Reports:  48%|████▊     | 3397/7111 [14:11<12:22,  5.00it/s]

Reports:  48%|████▊     | 3398/7111 [14:12<12:20,  5.01it/s]

Reports:  48%|████▊     | 3399/7111 [14:12<12:15,  5.05it/s]

Reports:  48%|████▊     | 3400/7111 [14:12<15:44,  3.93it/s]

Reports:  48%|████▊     | 3401/7111 [14:12<14:35,  4.24it/s]

Reports:  48%|████▊     | 3402/7111 [14:13<14:04,  4.39it/s]

Reports:  48%|████▊     | 3403/7111 [14:13<13:19,  4.64it/s]

Reports:  48%|████▊     | 3404/7111 [14:13<12:50,  4.81it/s]

Reports:  48%|████▊     | 3405/7111 [14:13<12:29,  4.94it/s]

Reports:  48%|████▊     | 3406/7111 [14:13<12:27,  4.96it/s]

Reports:  48%|████▊     | 3407/7111 [14:14<12:40,  4.87it/s]

Reports:  48%|████▊     | 3408/7111 [14:14<12:18,  5.02it/s]

Reports:  48%|████▊     | 3409/7111 [14:14<12:08,  5.08it/s]

Reports:  48%|████▊     | 3410/7111 [14:14<11:59,  5.14it/s]

Reports:  48%|████▊     | 3411/7111 [14:14<11:58,  5.15it/s]

Reports:  48%|████▊     | 3412/7111 [14:15<11:57,  5.15it/s]

Reports:  48%|████▊     | 3413/7111 [14:15<11:44,  5.25it/s]

Reports:  48%|████▊     | 3414/7111 [14:15<11:45,  5.24it/s]

Reports:  48%|████▊     | 3415/7111 [14:15<12:05,  5.09it/s]

Reports:  48%|████▊     | 3416/7111 [14:15<11:55,  5.17it/s]

Reports:  48%|████▊     | 3417/7111 [14:16<12:02,  5.11it/s]

Reports:  48%|████▊     | 3418/7111 [14:16<11:57,  5.15it/s]

Reports:  48%|████▊     | 3419/7111 [14:16<11:50,  5.19it/s]

Reports:  48%|████▊     | 3420/7111 [14:16<11:43,  5.25it/s]

Reports:  48%|████▊     | 3421/7111 [14:16<11:34,  5.31it/s]

Reports:  48%|████▊     | 3422/7111 [14:17<12:05,  5.08it/s]

Reports:  48%|████▊     | 3423/7111 [14:17<11:57,  5.14it/s]

Reports:  48%|████▊     | 3424/7111 [14:17<11:48,  5.20it/s]

Reports:  48%|████▊     | 3425/7111 [14:17<12:16,  5.00it/s]

Reports:  48%|████▊     | 3426/7111 [14:17<12:00,  5.12it/s]

Reports:  48%|████▊     | 3427/7111 [14:18<12:07,  5.06it/s]

Reports:  48%|████▊     | 3428/7111 [14:18<12:01,  5.11it/s]

Reports:  48%|████▊     | 3429/7111 [14:18<12:06,  5.07it/s]

Reports:  48%|████▊     | 3430/7111 [14:18<12:10,  5.04it/s]

Reports:  48%|████▊     | 3431/7111 [14:18<12:00,  5.11it/s]

Reports:  48%|████▊     | 3432/7111 [14:18<11:52,  5.16it/s]

Reports:  48%|████▊     | 3433/7111 [14:19<12:12,  5.02it/s]

Reports:  48%|████▊     | 3434/7111 [14:19<11:57,  5.13it/s]

Reports:  48%|████▊     | 3435/7111 [14:19<11:44,  5.22it/s]

Reports:  48%|████▊     | 3436/7111 [14:19<11:45,  5.21it/s]

Reports:  48%|████▊     | 3437/7111 [14:19<11:45,  5.21it/s]

Reports:  48%|████▊     | 3438/7111 [14:20<11:42,  5.23it/s]

Reports:  48%|████▊     | 3439/7111 [14:20<11:48,  5.18it/s]

Reports:  48%|████▊     | 3440/7111 [14:20<11:43,  5.22it/s]

Reports:  48%|████▊     | 3441/7111 [14:20<12:10,  5.02it/s]

Reports:  48%|████▊     | 3442/7111 [14:20<12:16,  4.98it/s]

Reports:  48%|████▊     | 3443/7111 [14:21<21:17,  2.87it/s]

Reports:  48%|████▊     | 3444/7111 [14:22<31:52,  1.92it/s]

Reports:  48%|████▊     | 3445/7111 [14:22<25:45,  2.37it/s]

Reports:  48%|████▊     | 3446/7111 [14:22<21:39,  2.82it/s]

Reports:  48%|████▊     | 3447/7111 [14:23<18:48,  3.25it/s]

Reports:  48%|████▊     | 3448/7111 [14:23<16:34,  3.68it/s]

Reports:  49%|████▊     | 3449/7111 [14:23<14:55,  4.09it/s]

Reports:  49%|████▊     | 3450/7111 [14:23<13:56,  4.38it/s]

Reports:  49%|████▊     | 3451/7111 [14:23<13:12,  4.62it/s]

Reports:  49%|████▊     | 3452/7111 [14:24<12:47,  4.77it/s]

Reports:  49%|████▊     | 3453/7111 [14:24<12:28,  4.89it/s]

Reports:  49%|████▊     | 3454/7111 [14:24<12:15,  4.97it/s]

Reports:  49%|████▊     | 3455/7111 [14:24<12:02,  5.06it/s]

Reports:  49%|████▊     | 3456/7111 [14:24<11:48,  5.16it/s]

Reports:  49%|████▊     | 3457/7111 [14:25<18:56,  3.22it/s]

Reports:  49%|████▊     | 3458/7111 [14:25<16:50,  3.61it/s]

Reports:  49%|████▊     | 3459/7111 [14:25<15:38,  3.89it/s]

Reports:  49%|████▊     | 3460/7111 [14:26<14:26,  4.21it/s]

Reports:  49%|████▊     | 3461/7111 [14:26<13:54,  4.37it/s]

Reports:  49%|████▊     | 3462/7111 [14:26<13:23,  4.54it/s]

Reports:  49%|████▊     | 3463/7111 [14:26<12:46,  4.76it/s]

Reports:  49%|████▊     | 3464/7111 [14:26<12:35,  4.83it/s]

Reports:  49%|████▊     | 3465/7111 [14:27<12:12,  4.97it/s]

Reports:  49%|████▊     | 3466/7111 [14:27<12:03,  5.04it/s]

Reports:  49%|████▉     | 3467/7111 [14:27<12:00,  5.05it/s]

Reports:  49%|████▉     | 3468/7111 [14:27<12:08,  5.00it/s]

Reports:  49%|████▉     | 3469/7111 [14:27<12:04,  5.03it/s]

Reports:  49%|████▉     | 3470/7111 [14:28<11:54,  5.10it/s]

Reports:  49%|████▉     | 3471/7111 [14:28<11:49,  5.13it/s]

Reports:  49%|████▉     | 3472/7111 [14:28<18:11,  3.33it/s]

Reports:  49%|████▉     | 3473/7111 [14:28<16:18,  3.72it/s]

Reports:  49%|████▉     | 3474/7111 [14:29<14:45,  4.11it/s]

Reports:  49%|████▉     | 3475/7111 [14:29<13:54,  4.36it/s]

Reports:  49%|████▉     | 3476/7111 [14:29<13:11,  4.59it/s]

Reports:  49%|████▉     | 3477/7111 [14:29<12:42,  4.76it/s]

Reports:  49%|████▉     | 3478/7111 [14:29<12:36,  4.80it/s]

Reports:  49%|████▉     | 3479/7111 [14:30<12:20,  4.90it/s]

Reports:  49%|████▉     | 3480/7111 [14:30<12:01,  5.03it/s]

Reports:  49%|████▉     | 3481/7111 [14:30<11:46,  5.14it/s]

Reports:  49%|████▉     | 3482/7111 [14:30<11:41,  5.18it/s]

Reports:  49%|████▉     | 3483/7111 [14:30<11:38,  5.19it/s]

Reports:  49%|████▉     | 3484/7111 [14:31<11:31,  5.25it/s]

Reports:  49%|████▉     | 3485/7111 [14:31<11:44,  5.15it/s]

Reports:  49%|████▉     | 3486/7111 [14:31<18:53,  3.20it/s]

Reports:  49%|████▉     | 3487/7111 [14:32<16:36,  3.64it/s]

Reports:  49%|████▉     | 3488/7111 [14:32<15:17,  3.95it/s]

Reports:  49%|████▉     | 3489/7111 [14:32<14:17,  4.23it/s]

Reports:  49%|████▉     | 3490/7111 [14:32<13:34,  4.45it/s]

Reports:  49%|████▉     | 3491/7111 [14:32<12:55,  4.67it/s]

Reports:  49%|████▉     | 3492/7111 [14:33<12:40,  4.76it/s]

Reports:  49%|████▉     | 3493/7111 [14:33<12:18,  4.90it/s]

Reports:  49%|████▉     | 3494/7111 [14:33<12:06,  4.98it/s]

Reports:  49%|████▉     | 3495/7111 [14:33<12:23,  4.86it/s]

Reports:  49%|████▉     | 3496/7111 [14:33<12:13,  4.93it/s]

Reports:  49%|████▉     | 3497/7111 [14:34<12:14,  4.92it/s]

Reports:  49%|████▉     | 3498/7111 [14:34<12:07,  4.97it/s]

Reports:  49%|████▉     | 3499/7111 [14:34<11:52,  5.07it/s]

Reports:  49%|████▉     | 3500/7111 [14:34<11:55,  5.05it/s]

Reports:  49%|████▉     | 3501/7111 [14:34<12:00,  5.01it/s]

Reports:  49%|████▉     | 3502/7111 [14:35<12:10,  4.94it/s]

Reports:  49%|████▉     | 3503/7111 [14:35<12:20,  4.87it/s]

Reports:  49%|████▉     | 3504/7111 [14:35<12:04,  4.98it/s]

Reports:  49%|████▉     | 3505/7111 [14:35<12:18,  4.88it/s]

Reports:  49%|████▉     | 3506/7111 [14:35<12:08,  4.95it/s]

Reports:  49%|████▉     | 3507/7111 [14:36<11:49,  5.08it/s]

Reports:  49%|████▉     | 3508/7111 [14:36<11:43,  5.12it/s]

Reports:  49%|████▉     | 3509/7111 [14:36<11:38,  5.16it/s]

Reports:  49%|████▉     | 3510/7111 [14:36<11:34,  5.19it/s]

Reports:  49%|████▉     | 3511/7111 [14:36<11:26,  5.24it/s]

Reports:  49%|████▉     | 3512/7111 [14:36<11:21,  5.28it/s]

Reports:  49%|████▉     | 3513/7111 [14:37<11:23,  5.27it/s]

Reports:  49%|████▉     | 3514/7111 [14:37<11:25,  5.25it/s]

Reports:  49%|████▉     | 3515/7111 [14:37<11:43,  5.11it/s]

Reports:  49%|████▉     | 3516/7111 [14:37<11:58,  5.00it/s]

Reports:  49%|████▉     | 3517/7111 [14:37<11:50,  5.06it/s]

Reports:  49%|████▉     | 3518/7111 [14:38<11:55,  5.02it/s]

Reports:  49%|████▉     | 3519/7111 [14:38<11:51,  5.05it/s]

Reports:  50%|████▉     | 3520/7111 [14:38<12:05,  4.95it/s]

Reports:  50%|████▉     | 3521/7111 [14:38<11:51,  5.05it/s]

Reports:  50%|████▉     | 3522/7111 [14:38<12:02,  4.97it/s]

Reports:  50%|████▉     | 3523/7111 [14:39<11:50,  5.05it/s]

Reports:  50%|████▉     | 3524/7111 [14:39<12:08,  4.92it/s]

Reports:  50%|████▉     | 3525/7111 [14:39<11:56,  5.00it/s]

Reports:  50%|████▉     | 3526/7111 [14:39<11:41,  5.11it/s]

Reports:  50%|████▉     | 3527/7111 [14:39<11:49,  5.05it/s]

Reports:  50%|████▉     | 3528/7111 [14:40<13:13,  4.52it/s]

Reports:  50%|████▉     | 3529/7111 [14:40<12:58,  4.60it/s]

Reports:  50%|████▉     | 3530/7111 [14:40<12:36,  4.73it/s]

Reports:  50%|████▉     | 3531/7111 [14:40<12:23,  4.82it/s]

Reports:  50%|████▉     | 3532/7111 [14:41<12:13,  4.88it/s]

Reports:  50%|████▉     | 3533/7111 [14:41<12:00,  4.97it/s]

Reports:  50%|████▉     | 3534/7111 [14:41<11:59,  4.97it/s]

Reports:  50%|████▉     | 3535/7111 [14:41<12:02,  4.95it/s]

Reports:  50%|████▉     | 3536/7111 [14:41<12:13,  4.88it/s]

Reports:  50%|████▉     | 3537/7111 [14:42<11:55,  5.00it/s]

Reports:  50%|████▉     | 3538/7111 [14:42<11:47,  5.05it/s]

Reports:  50%|████▉     | 3539/7111 [14:42<11:41,  5.09it/s]

Reports:  50%|████▉     | 3540/7111 [14:42<11:24,  5.22it/s]

Reports:  50%|████▉     | 3541/7111 [14:42<11:25,  5.21it/s]

Reports:  50%|████▉     | 3542/7111 [14:42<11:20,  5.24it/s]

Reports:  50%|████▉     | 3543/7111 [14:43<11:27,  5.19it/s]

Reports:  50%|████▉     | 3544/7111 [14:43<11:35,  5.13it/s]

Reports:  50%|████▉     | 3545/7111 [14:43<11:58,  4.96it/s]

Reports:  50%|████▉     | 3546/7111 [14:43<11:43,  5.06it/s]

Reports:  50%|████▉     | 3547/7111 [14:43<11:36,  5.11it/s]

Reports:  50%|████▉     | 3548/7111 [14:44<11:45,  5.05it/s]

Reports:  50%|████▉     | 3549/7111 [14:44<11:43,  5.07it/s]

Reports:  50%|████▉     | 3550/7111 [14:44<11:34,  5.13it/s]

Reports:  50%|████▉     | 3551/7111 [14:44<11:43,  5.06it/s]

Reports:  50%|████▉     | 3552/7111 [14:44<11:28,  5.17it/s]

Reports:  50%|████▉     | 3553/7111 [14:45<11:28,  5.16it/s]

Reports:  50%|████▉     | 3554/7111 [14:45<11:23,  5.21it/s]

Reports:  50%|████▉     | 3555/7111 [14:45<11:21,  5.22it/s]

Reports:  50%|█████     | 3556/7111 [14:45<11:22,  5.21it/s]

Reports:  50%|█████     | 3557/7111 [14:45<11:28,  5.16it/s]

Reports:  50%|█████     | 3558/7111 [14:46<11:24,  5.19it/s]

Reports:  50%|█████     | 3559/7111 [14:46<11:19,  5.23it/s]

Reports:  50%|█████     | 3560/7111 [14:46<11:16,  5.25it/s]

Reports:  50%|█████     | 3561/7111 [14:46<11:15,  5.26it/s]

Reports:  50%|█████     | 3562/7111 [14:46<11:13,  5.27it/s]

Reports:  50%|█████     | 3563/7111 [14:47<11:15,  5.26it/s]

Reports:  50%|█████     | 3564/7111 [14:47<11:39,  5.07it/s]

Reports:  50%|█████     | 3565/7111 [14:47<11:39,  5.07it/s]

Reports:  50%|█████     | 3566/7111 [14:47<11:33,  5.11it/s]

Reports:  50%|█████     | 3567/7111 [14:47<11:34,  5.10it/s]

Reports:  50%|█████     | 3568/7111 [14:48<11:28,  5.15it/s]

Reports:  50%|█████     | 3569/7111 [14:48<11:22,  5.19it/s]

Reports:  50%|█████     | 3570/7111 [14:48<11:18,  5.22it/s]

Reports:  50%|█████     | 3571/7111 [14:48<11:31,  5.12it/s]

Reports:  50%|█████     | 3572/7111 [14:48<11:21,  5.19it/s]

Reports:  50%|█████     | 3573/7111 [14:48<11:22,  5.18it/s]

Reports:  50%|█████     | 3574/7111 [14:49<11:30,  5.13it/s]

Reports:  50%|█████     | 3575/7111 [14:49<11:16,  5.23it/s]

Reports:  50%|█████     | 3576/7111 [14:49<11:20,  5.19it/s]

Reports:  50%|█████     | 3577/7111 [14:49<11:28,  5.13it/s]

Reports:  50%|█████     | 3578/7111 [14:49<11:25,  5.16it/s]

Reports:  50%|█████     | 3579/7111 [14:50<11:15,  5.23it/s]

Reports:  50%|█████     | 3580/7111 [14:50<11:27,  5.14it/s]

Reports:  50%|█████     | 3581/7111 [14:50<11:22,  5.17it/s]

Reports:  50%|█████     | 3582/7111 [14:50<11:20,  5.19it/s]

Reports:  50%|█████     | 3583/7111 [14:50<11:14,  5.23it/s]

Reports:  50%|█████     | 3584/7111 [14:51<11:07,  5.29it/s]

Reports:  50%|█████     | 3585/7111 [14:51<11:20,  5.18it/s]

Reports:  50%|█████     | 3586/7111 [14:51<11:13,  5.23it/s]

Reports:  50%|█████     | 3587/7111 [14:51<11:13,  5.24it/s]

Reports:  50%|█████     | 3588/7111 [14:51<11:25,  5.14it/s]

Reports:  50%|█████     | 3589/7111 [14:52<11:15,  5.21it/s]

Reports:  50%|█████     | 3590/7111 [14:52<11:19,  5.18it/s]

Reports:  50%|█████     | 3591/7111 [14:52<11:21,  5.16it/s]

Reports:  51%|█████     | 3592/7111 [14:52<11:12,  5.23it/s]

Reports:  51%|█████     | 3593/7111 [14:52<11:16,  5.20it/s]

Reports:  51%|█████     | 3594/7111 [14:53<11:17,  5.19it/s]

Reports:  51%|█████     | 3595/7111 [14:53<11:12,  5.23it/s]

Reports:  51%|█████     | 3596/7111 [14:53<11:04,  5.29it/s]

Reports:  51%|█████     | 3597/7111 [14:53<11:04,  5.29it/s]

Reports:  51%|█████     | 3598/7111 [14:53<11:01,  5.31it/s]

Reports:  51%|█████     | 3599/7111 [14:53<11:05,  5.28it/s]

Reports:  51%|█████     | 3600/7111 [14:54<11:03,  5.29it/s]

Reports:  51%|█████     | 3601/7111 [14:54<11:01,  5.31it/s]

Reports:  51%|█████     | 3602/7111 [14:54<10:56,  5.35it/s]

Reports:  51%|█████     | 3603/7111 [14:54<11:12,  5.22it/s]

Reports:  51%|█████     | 3604/7111 [14:54<11:07,  5.25it/s]

Reports:  51%|█████     | 3605/7111 [14:55<11:06,  5.26it/s]

Reports:  51%|█████     | 3606/7111 [14:55<11:12,  5.21it/s]

Reports:  51%|█████     | 3607/7111 [14:55<11:22,  5.13it/s]

Reports:  51%|█████     | 3608/7111 [14:55<11:18,  5.16it/s]

Reports:  51%|█████     | 3609/7111 [14:55<11:17,  5.17it/s]

Reports:  51%|█████     | 3610/7111 [14:56<11:28,  5.08it/s]

Reports:  51%|█████     | 3611/7111 [14:57<38:42,  1.51it/s]

Reports:  51%|█████     | 3612/7111 [14:58<30:33,  1.91it/s]

Reports:  51%|█████     | 3613/7111 [14:58<24:58,  2.33it/s]

Reports:  51%|█████     | 3614/7111 [14:58<21:00,  2.77it/s]

Reports:  51%|█████     | 3615/7111 [14:58<17:57,  3.24it/s]

Reports:  51%|█████     | 3616/7111 [14:58<16:02,  3.63it/s]

Reports:  51%|█████     | 3617/7111 [14:59<14:55,  3.90it/s]

Reports:  51%|█████     | 3618/7111 [14:59<13:43,  4.24it/s]

Reports:  51%|█████     | 3619/7111 [14:59<13:06,  4.44it/s]

Reports:  51%|█████     | 3620/7111 [14:59<12:54,  4.51it/s]

Reports:  51%|█████     | 3621/7111 [14:59<12:26,  4.68it/s]

Reports:  51%|█████     | 3622/7111 [15:00<12:27,  4.67it/s]

Reports:  51%|█████     | 3623/7111 [15:00<12:06,  4.80it/s]

Reports:  51%|█████     | 3624/7111 [15:00<11:57,  4.86it/s]

Reports:  51%|█████     | 3625/7111 [15:00<11:52,  4.89it/s]

Reports:  51%|█████     | 3626/7111 [15:00<11:49,  4.91it/s]

Reports:  51%|█████     | 3627/7111 [15:01<11:52,  4.89it/s]

Reports:  51%|█████     | 3628/7111 [15:01<12:04,  4.81it/s]

Reports:  51%|█████     | 3629/7111 [15:01<11:45,  4.93it/s]

Reports:  51%|█████     | 3630/7111 [15:01<11:38,  4.98it/s]

Reports:  51%|█████     | 3631/7111 [15:01<11:27,  5.06it/s]

Reports:  51%|█████     | 3632/7111 [15:02<11:29,  5.05it/s]

Reports:  51%|█████     | 3633/7111 [15:02<11:33,  5.01it/s]

Reports:  51%|█████     | 3634/7111 [15:02<11:31,  5.03it/s]

Reports:  51%|█████     | 3635/7111 [15:02<11:19,  5.12it/s]

Reports:  51%|█████     | 3636/7111 [15:02<11:26,  5.06it/s]

Reports:  51%|█████     | 3637/7111 [15:03<11:20,  5.11it/s]

Reports:  51%|█████     | 3638/7111 [15:03<12:04,  4.80it/s]

Reports:  51%|█████     | 3639/7111 [15:03<12:14,  4.73it/s]

Reports:  51%|█████     | 3640/7111 [15:03<11:50,  4.89it/s]

Reports:  51%|█████     | 3641/7111 [15:03<11:41,  4.94it/s]

Reports:  51%|█████     | 3642/7111 [15:04<11:42,  4.94it/s]

Reports:  51%|█████     | 3643/7111 [15:04<11:24,  5.07it/s]

Reports:  51%|█████     | 3644/7111 [15:04<11:27,  5.05it/s]

Reports:  51%|█████▏    | 3645/7111 [15:04<11:32,  5.00it/s]

Reports:  51%|█████▏    | 3646/7111 [15:04<11:30,  5.02it/s]

Reports:  51%|█████▏    | 3647/7111 [15:05<11:34,  4.99it/s]

Reports:  51%|█████▏    | 3648/7111 [15:05<11:35,  4.98it/s]

Reports:  51%|█████▏    | 3649/7111 [15:05<11:35,  4.98it/s]

Reports:  51%|█████▏    | 3650/7111 [15:05<11:21,  5.08it/s]

Reports:  51%|█████▏    | 3651/7111 [15:05<11:29,  5.02it/s]

Reports:  51%|█████▏    | 3652/7111 [15:06<11:25,  5.05it/s]

Reports:  51%|█████▏    | 3653/7111 [15:06<11:28,  5.02it/s]

Reports:  51%|█████▏    | 3654/7111 [15:06<11:16,  5.11it/s]

Reports:  51%|█████▏    | 3655/7111 [15:06<11:09,  5.16it/s]

Reports:  51%|█████▏    | 3656/7111 [15:06<11:25,  5.04it/s]

Reports:  51%|█████▏    | 3657/7111 [15:07<11:18,  5.09it/s]

Reports:  51%|█████▏    | 3658/7111 [15:07<11:21,  5.07it/s]

Reports:  51%|█████▏    | 3659/7111 [15:07<11:21,  5.06it/s]

Reports:  51%|█████▏    | 3660/7111 [15:07<11:13,  5.13it/s]

Reports:  51%|█████▏    | 3661/7111 [15:07<11:08,  5.16it/s]

Reports:  51%|█████▏    | 3662/7111 [15:08<11:27,  5.02it/s]

Reports:  52%|█████▏    | 3663/7111 [15:08<12:35,  4.57it/s]

Reports:  52%|█████▏    | 3664/7111 [15:08<12:19,  4.66it/s]

Reports:  52%|█████▏    | 3665/7111 [15:08<12:09,  4.73it/s]

Reports:  52%|█████▏    | 3666/7111 [15:08<11:52,  4.84it/s]

Reports:  52%|█████▏    | 3667/7111 [15:09<11:50,  4.85it/s]

Reports:  52%|█████▏    | 3668/7111 [15:09<11:30,  4.99it/s]

Reports:  52%|█████▏    | 3669/7111 [15:09<11:25,  5.02it/s]

Reports:  52%|█████▏    | 3670/7111 [15:09<11:35,  4.95it/s]

Reports:  52%|█████▏    | 3671/7111 [15:09<11:18,  5.07it/s]

Reports:  52%|█████▏    | 3672/7111 [15:10<11:15,  5.09it/s]

Reports:  52%|█████▏    | 3673/7111 [15:10<11:10,  5.13it/s]

Reports:  52%|█████▏    | 3674/7111 [15:10<11:00,  5.21it/s]

Reports:  52%|█████▏    | 3675/7111 [15:10<11:04,  5.17it/s]

Reports:  52%|█████▏    | 3676/7111 [15:10<11:10,  5.12it/s]

Reports:  52%|█████▏    | 3677/7111 [15:11<10:57,  5.22it/s]

Reports:  52%|█████▏    | 3678/7111 [15:11<10:47,  5.30it/s]

Reports:  52%|█████▏    | 3679/7111 [15:11<10:44,  5.33it/s]

Reports:  52%|█████▏    | 3680/7111 [15:11<10:58,  5.21it/s]

Reports:  52%|█████▏    | 3681/7111 [15:11<10:51,  5.27it/s]

Reports:  52%|█████▏    | 3682/7111 [15:11<10:49,  5.28it/s]

Reports:  52%|█████▏    | 3683/7111 [15:12<11:04,  5.16it/s]

Reports:  52%|█████▏    | 3684/7111 [15:12<21:17,  2.68it/s]

Reports:  52%|█████▏    | 3685/7111 [15:13<18:24,  3.10it/s]

Reports:  52%|█████▏    | 3686/7111 [15:13<16:16,  3.51it/s]

Reports:  52%|█████▏    | 3687/7111 [15:13<15:25,  3.70it/s]

Reports:  52%|█████▏    | 3688/7111 [15:13<14:01,  4.07it/s]

Reports:  52%|█████▏    | 3689/7111 [15:14<16:51,  3.38it/s]

Reports:  52%|█████▏    | 3690/7111 [15:14<14:58,  3.81it/s]

Reports:  52%|█████▏    | 3691/7111 [15:14<13:50,  4.12it/s]

Reports:  52%|█████▏    | 3692/7111 [15:14<12:54,  4.41it/s]

Reports:  52%|█████▏    | 3693/7111 [15:14<12:13,  4.66it/s]

Reports:  52%|█████▏    | 3694/7111 [15:15<12:02,  4.73it/s]

Reports:  52%|█████▏    | 3695/7111 [15:15<11:47,  4.83it/s]

Reports:  52%|█████▏    | 3696/7111 [15:15<11:26,  4.97it/s]

Reports:  52%|█████▏    | 3697/7111 [15:15<11:16,  5.05it/s]

Reports:  52%|█████▏    | 3698/7111 [15:15<11:15,  5.05it/s]

Reports:  52%|█████▏    | 3699/7111 [15:16<11:27,  4.97it/s]

Reports:  52%|█████▏    | 3700/7111 [15:16<11:19,  5.02it/s]

Reports:  52%|█████▏    | 3701/7111 [15:16<11:06,  5.12it/s]

Reports:  52%|█████▏    | 3702/7111 [15:16<10:59,  5.17it/s]

Reports:  52%|█████▏    | 3703/7111 [15:16<10:56,  5.19it/s]

Reports:  52%|█████▏    | 3704/7111 [15:17<10:52,  5.22it/s]

Reports:  52%|█████▏    | 3705/7111 [15:17<10:54,  5.20it/s]

Reports:  52%|█████▏    | 3706/7111 [15:17<10:55,  5.19it/s]

Reports:  52%|█████▏    | 3707/7111 [15:17<11:21,  5.00it/s]

Reports:  52%|█████▏    | 3708/7111 [15:17<11:16,  5.03it/s]

Reports:  52%|█████▏    | 3709/7111 [15:18<11:07,  5.09it/s]

Reports:  52%|█████▏    | 3710/7111 [15:18<10:58,  5.16it/s]

Reports:  52%|█████▏    | 3711/7111 [15:18<10:57,  5.17it/s]

Reports:  52%|█████▏    | 3712/7111 [15:18<10:58,  5.16it/s]

Reports:  52%|█████▏    | 3713/7111 [15:18<10:53,  5.20it/s]

Reports:  52%|█████▏    | 3714/7111 [15:19<11:01,  5.13it/s]

Reports:  52%|█████▏    | 3715/7111 [15:19<11:19,  5.00it/s]

Reports:  52%|█████▏    | 3716/7111 [15:19<11:16,  5.02it/s]

Reports:  52%|█████▏    | 3717/7111 [15:19<11:10,  5.06it/s]

Reports:  52%|█████▏    | 3718/7111 [15:19<10:57,  5.16it/s]

Reports:  52%|█████▏    | 3719/7111 [15:20<17:49,  3.17it/s]

Reports:  52%|█████▏    | 3720/7111 [15:20<15:54,  3.55it/s]

Reports:  52%|█████▏    | 3721/7111 [15:20<14:19,  3.95it/s]

Reports:  52%|█████▏    | 3722/7111 [15:21<13:26,  4.20it/s]

Reports:  52%|█████▏    | 3723/7111 [15:21<12:40,  4.46it/s]

Reports:  52%|█████▏    | 3724/7111 [15:21<12:03,  4.68it/s]

Reports:  52%|█████▏    | 3725/7111 [15:21<11:43,  4.81it/s]

Reports:  52%|█████▏    | 3726/7111 [15:21<11:35,  4.86it/s]

Reports:  52%|█████▏    | 3727/7111 [15:22<11:26,  4.93it/s]

Reports:  52%|█████▏    | 3728/7111 [15:22<11:07,  5.07it/s]

Reports:  52%|█████▏    | 3729/7111 [15:22<11:19,  4.98it/s]

Reports:  52%|█████▏    | 3730/7111 [15:22<11:34,  4.87it/s]

Reports:  52%|█████▏    | 3731/7111 [15:22<11:17,  4.99it/s]

Reports:  52%|█████▏    | 3732/7111 [15:24<38:48,  1.45it/s]

Reports:  52%|█████▏    | 3733/7111 [15:24<30:38,  1.84it/s]

Reports:  53%|█████▎    | 3734/7111 [15:25<35:12,  1.60it/s]

Reports:  53%|█████▎    | 3735/7111 [15:25<27:49,  2.02it/s]

Reports:  53%|█████▎    | 3736/7111 [15:26<22:42,  2.48it/s]

Reports:  53%|█████▎    | 3737/7111 [15:26<19:16,  2.92it/s]

Reports:  53%|█████▎    | 3738/7111 [15:26<17:00,  3.31it/s]

Reports:  53%|█████▎    | 3739/7111 [15:26<15:14,  3.69it/s]

Reports:  53%|█████▎    | 3740/7111 [15:26<13:50,  4.06it/s]

Reports:  53%|█████▎    | 3741/7111 [15:27<12:58,  4.33it/s]

Reports:  53%|█████▎    | 3742/7111 [15:27<12:18,  4.56it/s]

Reports:  53%|█████▎    | 3743/7111 [15:27<11:53,  4.72it/s]

Reports:  53%|█████▎    | 3744/7111 [15:27<12:20,  4.54it/s]

Reports:  53%|█████▎    | 3745/7111 [15:27<12:02,  4.66it/s]

Reports:  53%|█████▎    | 3746/7111 [15:28<11:31,  4.86it/s]

Reports:  53%|█████▎    | 3747/7111 [15:28<11:14,  4.99it/s]

Reports:  53%|█████▎    | 3748/7111 [15:28<11:14,  4.98it/s]

Reports:  53%|█████▎    | 3749/7111 [15:28<11:03,  5.07it/s]

Reports:  53%|█████▎    | 3750/7111 [15:28<10:57,  5.11it/s]

Reports:  53%|█████▎    | 3751/7111 [15:29<11:07,  5.04it/s]

Reports:  53%|█████▎    | 3752/7111 [15:29<11:00,  5.09it/s]

Reports:  53%|█████▎    | 3753/7111 [15:29<10:58,  5.10it/s]

Reports:  53%|█████▎    | 3754/7111 [15:29<11:03,  5.06it/s]

Reports:  53%|█████▎    | 3755/7111 [15:29<10:59,  5.09it/s]

Reports:  53%|█████▎    | 3756/7111 [15:30<11:15,  4.97it/s]

Reports:  53%|█████▎    | 3757/7111 [15:30<11:16,  4.96it/s]

Reports:  53%|█████▎    | 3758/7111 [15:30<11:08,  5.01it/s]

Reports:  53%|█████▎    | 3759/7111 [15:30<12:56,  4.32it/s]

Reports:  53%|█████▎    | 3760/7111 [15:30<12:12,  4.57it/s]

Reports:  53%|█████▎    | 3761/7111 [15:31<11:53,  4.69it/s]

Reports:  53%|█████▎    | 3762/7111 [15:31<11:44,  4.76it/s]

Reports:  53%|█████▎    | 3763/7111 [15:31<11:25,  4.89it/s]

Reports:  53%|█████▎    | 3764/7111 [15:31<11:15,  4.96it/s]

Reports:  53%|█████▎    | 3765/7111 [15:31<11:17,  4.94it/s]

Reports:  53%|█████▎    | 3766/7111 [15:32<11:16,  4.95it/s]

Reports:  53%|█████▎    | 3767/7111 [15:32<11:02,  5.05it/s]

Reports:  53%|█████▎    | 3768/7111 [15:32<11:08,  5.00it/s]

Reports:  53%|█████▎    | 3769/7111 [15:32<11:03,  5.04it/s]

Reports:  53%|█████▎    | 3770/7111 [15:32<11:18,  4.92it/s]

Reports:  53%|█████▎    | 3771/7111 [15:33<11:13,  4.96it/s]

Reports:  53%|█████▎    | 3772/7111 [15:33<11:08,  5.00it/s]

Reports:  53%|█████▎    | 3773/7111 [15:34<25:32,  2.18it/s]

Reports:  53%|█████▎    | 3774/7111 [15:34<21:04,  2.64it/s]

Reports:  53%|█████▎    | 3775/7111 [15:34<18:00,  3.09it/s]

Reports:  53%|█████▎    | 3776/7111 [15:34<15:47,  3.52it/s]

Reports:  53%|█████▎    | 3777/7111 [15:35<14:23,  3.86it/s]

Reports:  53%|█████▎    | 3778/7111 [15:35<13:09,  4.22it/s]

Reports:  53%|█████▎    | 3779/7111 [15:35<12:40,  4.38it/s]

Reports:  53%|█████▎    | 3780/7111 [15:35<12:06,  4.59it/s]

Reports:  53%|█████▎    | 3781/7111 [15:35<11:48,  4.70it/s]

Reports:  53%|█████▎    | 3782/7111 [15:36<11:36,  4.78it/s]

Reports:  53%|█████▎    | 3783/7111 [15:36<11:16,  4.92it/s]

Reports:  53%|█████▎    | 3784/7111 [15:36<11:13,  4.94it/s]

Reports:  53%|█████▎    | 3785/7111 [15:37<20:51,  2.66it/s]

Reports:  53%|█████▎    | 3786/7111 [15:37<18:04,  3.06it/s]

Reports:  53%|█████▎    | 3787/7111 [15:37<16:45,  3.31it/s]

Reports:  53%|█████▎    | 3788/7111 [15:37<14:57,  3.70it/s]

Reports:  53%|█████▎    | 3789/7111 [15:38<13:54,  3.98it/s]

Reports:  53%|█████▎    | 3790/7111 [15:38<13:05,  4.23it/s]

Reports:  53%|█████▎    | 3791/7111 [15:38<12:19,  4.49it/s]

Reports:  53%|█████▎    | 3792/7111 [15:38<11:48,  4.69it/s]

Reports:  53%|█████▎    | 3793/7111 [15:38<11:35,  4.77it/s]

Reports:  53%|█████▎    | 3794/7111 [15:39<11:24,  4.85it/s]

Reports:  53%|█████▎    | 3795/7111 [15:39<11:06,  4.98it/s]

Reports:  53%|█████▎    | 3796/7111 [15:39<11:10,  4.95it/s]

Reports:  53%|█████▎    | 3797/7111 [15:39<10:58,  5.03it/s]

Reports:  53%|█████▎    | 3798/7111 [15:39<10:46,  5.12it/s]

Reports:  53%|█████▎    | 3799/7111 [15:40<11:01,  5.00it/s]

Reports:  53%|█████▎    | 3800/7111 [15:40<10:52,  5.08it/s]

Reports:  53%|█████▎    | 3801/7111 [15:40<10:32,  5.23it/s]

Reports:  53%|█████▎    | 3802/7111 [15:40<10:51,  5.08it/s]

Reports:  53%|█████▎    | 3803/7111 [15:40<10:58,  5.02it/s]

Reports:  53%|█████▎    | 3804/7111 [15:41<11:00,  5.01it/s]

Reports:  54%|█████▎    | 3805/7111 [15:41<11:04,  4.97it/s]

Reports:  54%|█████▎    | 3806/7111 [15:41<11:06,  4.96it/s]

Reports:  54%|█████▎    | 3807/7111 [15:41<10:52,  5.06it/s]

Reports:  54%|█████▎    | 3808/7111 [15:41<10:40,  5.16it/s]

Reports:  54%|█████▎    | 3809/7111 [15:42<10:50,  5.07it/s]

Reports:  54%|█████▎    | 3810/7111 [15:42<10:47,  5.10it/s]

Reports:  54%|█████▎    | 3811/7111 [15:42<10:41,  5.14it/s]

Reports:  54%|█████▎    | 3812/7111 [15:42<10:41,  5.14it/s]

Reports:  54%|█████▎    | 3813/7111 [15:42<10:55,  5.03it/s]

Reports:  54%|█████▎    | 3814/7111 [15:43<11:00,  4.99it/s]

Reports:  54%|█████▎    | 3815/7111 [15:43<11:07,  4.94it/s]

Reports:  54%|█████▎    | 3816/7111 [15:43<10:51,  5.06it/s]

Reports:  54%|█████▎    | 3817/7111 [15:43<10:38,  5.16it/s]

Reports:  54%|█████▎    | 3818/7111 [15:43<10:33,  5.20it/s]

Reports:  54%|█████▎    | 3819/7111 [15:44<10:34,  5.19it/s]

Reports:  54%|█████▎    | 3820/7111 [15:44<13:53,  3.95it/s]

Reports:  54%|█████▎    | 3821/7111 [15:44<13:00,  4.21it/s]

Reports:  54%|█████▎    | 3822/7111 [15:44<12:31,  4.37it/s]

Reports:  54%|█████▍    | 3823/7111 [15:45<12:05,  4.53it/s]

Reports:  54%|█████▍    | 3824/7111 [15:45<11:35,  4.73it/s]

Reports:  54%|█████▍    | 3825/7111 [15:45<11:22,  4.82it/s]

Reports:  54%|█████▍    | 3826/7111 [15:45<11:10,  4.90it/s]

Reports:  54%|█████▍    | 3827/7111 [15:45<11:20,  4.82it/s]

Reports:  54%|█████▍    | 3828/7111 [15:46<11:35,  4.72it/s]

Reports:  54%|█████▍    | 3829/7111 [15:46<11:17,  4.84it/s]

Reports:  54%|█████▍    | 3830/7111 [15:46<11:01,  4.96it/s]

Reports:  54%|█████▍    | 3831/7111 [15:46<10:57,  4.99it/s]

Reports:  54%|█████▍    | 3832/7111 [15:46<11:01,  4.96it/s]

Reports:  54%|█████▍    | 3833/7111 [15:47<11:02,  4.94it/s]

Reports:  54%|█████▍    | 3834/7111 [15:47<10:51,  5.03it/s]

Reports:  54%|█████▍    | 3835/7111 [15:47<10:46,  5.07it/s]

Reports:  54%|█████▍    | 3836/7111 [15:47<10:45,  5.07it/s]

Reports:  54%|█████▍    | 3837/7111 [15:47<11:51,  4.60it/s]

Reports:  54%|█████▍    | 3838/7111 [15:48<12:12,  4.47it/s]

Reports:  54%|█████▍    | 3839/7111 [15:48<11:51,  4.60it/s]

Reports:  54%|█████▍    | 3840/7111 [15:48<11:42,  4.65it/s]

Reports:  54%|█████▍    | 3841/7111 [15:48<11:44,  4.64it/s]

Reports:  54%|█████▍    | 3842/7111 [15:48<11:29,  4.74it/s]

Reports:  54%|█████▍    | 3843/7111 [15:49<11:07,  4.90it/s]

Reports:  54%|█████▍    | 3844/7111 [15:49<10:55,  4.99it/s]

Reports:  54%|█████▍    | 3845/7111 [15:49<10:49,  5.03it/s]

Reports:  54%|█████▍    | 3846/7111 [15:49<10:58,  4.96it/s]

Reports:  54%|█████▍    | 3847/7111 [15:49<10:57,  4.96it/s]

Reports:  54%|█████▍    | 3848/7111 [15:50<10:52,  5.00it/s]

Reports:  54%|█████▍    | 3849/7111 [15:50<10:59,  4.94it/s]

Reports:  54%|█████▍    | 3850/7111 [15:50<10:49,  5.02it/s]

Reports:  54%|█████▍    | 3851/7111 [15:50<10:39,  5.10it/s]

Reports:  54%|█████▍    | 3852/7111 [15:50<10:40,  5.09it/s]

Reports:  54%|█████▍    | 3853/7111 [15:51<11:01,  4.92it/s]

Reports:  54%|█████▍    | 3854/7111 [15:51<10:46,  5.03it/s]

Reports:  54%|█████▍    | 3855/7111 [15:51<10:55,  4.97it/s]

Reports:  54%|█████▍    | 3856/7111 [15:51<11:03,  4.91it/s]

Reports:  54%|█████▍    | 3857/7111 [15:51<10:43,  5.06it/s]

Reports:  54%|█████▍    | 3858/7111 [15:52<10:36,  5.11it/s]

Reports:  54%|█████▍    | 3859/7111 [15:52<10:36,  5.11it/s]

Reports:  54%|█████▍    | 3860/7111 [15:52<10:33,  5.13it/s]

Reports:  54%|█████▍    | 3861/7111 [15:52<10:40,  5.08it/s]

Reports:  54%|█████▍    | 3862/7111 [15:52<10:36,  5.10it/s]

Reports:  54%|█████▍    | 3863/7111 [15:53<10:29,  5.16it/s]

Reports:  54%|█████▍    | 3864/7111 [15:53<10:19,  5.24it/s]

Reports:  54%|█████▍    | 3865/7111 [15:53<10:23,  5.20it/s]

Reports:  54%|█████▍    | 3866/7111 [15:53<10:38,  5.08it/s]

Reports:  54%|█████▍    | 3867/7111 [15:53<10:35,  5.10it/s]

Reports:  54%|█████▍    | 3868/7111 [15:54<11:29,  4.70it/s]

Reports:  54%|█████▍    | 3869/7111 [15:54<11:05,  4.87it/s]

Reports:  54%|█████▍    | 3870/7111 [15:54<10:58,  4.92it/s]

Reports:  54%|█████▍    | 3871/7111 [15:54<10:40,  5.06it/s]

Reports:  54%|█████▍    | 3872/7111 [15:54<10:47,  5.00it/s]

Reports:  54%|█████▍    | 3873/7111 [15:55<10:35,  5.09it/s]

Reports:  54%|█████▍    | 3874/7111 [15:55<10:34,  5.10it/s]

Reports:  54%|█████▍    | 3875/7111 [15:55<10:27,  5.15it/s]

Reports:  55%|█████▍    | 3876/7111 [15:55<10:16,  5.24it/s]

Reports:  55%|█████▍    | 3877/7111 [15:55<10:09,  5.31it/s]

Reports:  55%|█████▍    | 3878/7111 [15:56<10:41,  5.04it/s]

Reports:  55%|█████▍    | 3879/7111 [15:56<10:41,  5.04it/s]

Reports:  55%|█████▍    | 3880/7111 [15:56<10:34,  5.09it/s]

Reports:  55%|█████▍    | 3881/7111 [15:56<10:31,  5.11it/s]

Reports:  55%|█████▍    | 3882/7111 [15:56<10:24,  5.17it/s]

Reports:  55%|█████▍    | 3883/7111 [15:57<10:20,  5.20it/s]

Reports:  55%|█████▍    | 3884/7111 [15:57<12:38,  4.25it/s]

Reports:  55%|█████▍    | 3885/7111 [15:59<39:22,  1.37it/s]

Reports:  55%|█████▍    | 3886/7111 [15:59<30:39,  1.75it/s]

Reports:  55%|█████▍    | 3887/7111 [15:59<24:29,  2.19it/s]

Reports:  55%|█████▍    | 3888/7111 [15:59<20:11,  2.66it/s]

Reports:  55%|█████▍    | 3889/7111 [16:00<25:15,  2.13it/s]

Reports:  55%|█████▍    | 3890/7111 [16:00<20:38,  2.60it/s]

Reports:  55%|█████▍    | 3891/7111 [16:00<17:40,  3.04it/s]

Reports:  55%|█████▍    | 3892/7111 [16:01<15:21,  3.49it/s]

Reports:  55%|█████▍    | 3893/7111 [16:01<13:55,  3.85it/s]

Reports:  55%|█████▍    | 3894/7111 [16:01<12:42,  4.22it/s]

Reports:  55%|█████▍    | 3895/7111 [16:01<12:11,  4.39it/s]

Reports:  55%|█████▍    | 3896/7111 [16:02<14:13,  3.77it/s]

Reports:  55%|█████▍    | 3897/7111 [16:02<12:57,  4.13it/s]

Reports:  55%|█████▍    | 3898/7111 [16:02<12:04,  4.43it/s]

Reports:  55%|█████▍    | 3899/7111 [16:02<11:39,  4.59it/s]

Reports:  55%|█████▍    | 3900/7111 [16:02<11:28,  4.67it/s]

Reports:  55%|█████▍    | 3901/7111 [16:03<11:07,  4.81it/s]

Reports:  55%|█████▍    | 3902/7111 [16:03<11:00,  4.86it/s]

Reports:  55%|█████▍    | 3903/7111 [16:04<26:04,  2.05it/s]

Reports:  55%|█████▍    | 3904/7111 [16:04<21:22,  2.50it/s]

Reports:  55%|█████▍    | 3905/7111 [16:04<18:12,  2.93it/s]

Reports:  55%|█████▍    | 3906/7111 [16:04<15:59,  3.34it/s]

Reports:  55%|█████▍    | 3907/7111 [16:05<14:34,  3.66it/s]

Reports:  55%|█████▍    | 3908/7111 [16:05<13:14,  4.03it/s]

Reports:  55%|█████▍    | 3909/7111 [16:05<12:33,  4.25it/s]

Reports:  55%|█████▍    | 3910/7111 [16:05<11:50,  4.50it/s]

Reports:  55%|█████▍    | 3911/7111 [16:05<11:14,  4.75it/s]

Reports:  55%|█████▌    | 3912/7111 [16:06<10:51,  4.91it/s]

Reports:  55%|█████▌    | 3913/7111 [16:06<10:42,  4.98it/s]

Reports:  55%|█████▌    | 3914/7111 [16:06<11:22,  4.68it/s]

Reports:  55%|█████▌    | 3915/7111 [16:06<12:22,  4.30it/s]

Reports:  55%|█████▌    | 3916/7111 [16:07<12:14,  4.35it/s]

Reports:  55%|█████▌    | 3917/7111 [16:07<12:03,  4.41it/s]

Reports:  55%|█████▌    | 3918/7111 [16:07<12:30,  4.26it/s]

Reports:  55%|█████▌    | 3919/7111 [16:07<12:36,  4.22it/s]

Reports:  55%|█████▌    | 3920/7111 [16:08<12:15,  4.34it/s]

Reports:  55%|█████▌    | 3921/7111 [16:08<11:36,  4.58it/s]

Reports:  55%|█████▌    | 3922/7111 [16:08<11:18,  4.70it/s]

Reports:  55%|█████▌    | 3923/7111 [16:08<11:18,  4.70it/s]

Reports:  55%|█████▌    | 3924/7111 [16:08<11:08,  4.77it/s]

Reports:  55%|█████▌    | 3925/7111 [16:09<11:00,  4.82it/s]

Reports:  55%|█████▌    | 3926/7111 [16:09<10:41,  4.97it/s]

Reports:  55%|█████▌    | 3927/7111 [16:09<10:38,  4.99it/s]

Reports:  55%|█████▌    | 3928/7111 [16:09<10:36,  5.00it/s]

Reports:  55%|█████▌    | 3929/7111 [16:09<10:24,  5.10it/s]

Reports:  55%|█████▌    | 3930/7111 [16:09<10:15,  5.17it/s]

Reports:  55%|█████▌    | 3931/7111 [16:10<10:08,  5.22it/s]

Reports:  55%|█████▌    | 3932/7111 [16:10<10:07,  5.23it/s]

Reports:  55%|█████▌    | 3933/7111 [16:10<10:23,  5.10it/s]

Reports:  55%|█████▌    | 3934/7111 [16:10<10:34,  5.01it/s]

Reports:  55%|█████▌    | 3935/7111 [16:10<10:21,  5.11it/s]

Reports:  55%|█████▌    | 3936/7111 [16:11<10:21,  5.11it/s]

Reports:  55%|█████▌    | 3937/7111 [16:11<10:41,  4.95it/s]

Reports:  55%|█████▌    | 3938/7111 [16:11<10:42,  4.94it/s]

Reports:  55%|█████▌    | 3939/7111 [16:11<10:26,  5.06it/s]

Reports:  55%|█████▌    | 3940/7111 [16:13<29:10,  1.81it/s]

Reports:  55%|█████▌    | 3941/7111 [16:13<23:32,  2.24it/s]

Reports:  55%|█████▌    | 3942/7111 [16:13<19:25,  2.72it/s]

Reports:  55%|█████▌    | 3943/7111 [16:13<16:58,  3.11it/s]

Reports:  55%|█████▌    | 3944/7111 [16:13<14:50,  3.56it/s]

Reports:  55%|█████▌    | 3945/7111 [16:14<13:37,  3.87it/s]

Reports:  55%|█████▌    | 3946/7111 [16:14<12:32,  4.21it/s]

Reports:  56%|█████▌    | 3947/7111 [16:14<11:54,  4.43it/s]

Reports:  56%|█████▌    | 3948/7111 [16:14<11:34,  4.55it/s]

Reports:  56%|█████▌    | 3949/7111 [16:14<11:18,  4.66it/s]

Reports:  56%|█████▌    | 3950/7111 [16:15<11:00,  4.78it/s]

Reports:  56%|█████▌    | 3951/7111 [16:15<10:30,  5.01it/s]

Reports:  56%|█████▌    | 3952/7111 [16:15<10:28,  5.03it/s]

Reports:  56%|█████▌    | 3953/7111 [16:15<10:28,  5.03it/s]

Reports:  56%|█████▌    | 3954/7111 [16:15<10:15,  5.13it/s]

Reports:  56%|█████▌    | 3955/7111 [16:16<10:01,  5.25it/s]

Reports:  56%|█████▌    | 3956/7111 [16:18<46:22,  1.13it/s]

Reports:  56%|█████▌    | 3957/7111 [16:18<35:26,  1.48it/s]

Reports:  56%|█████▌    | 3958/7111 [16:18<27:56,  1.88it/s]

Reports:  56%|█████▌    | 3959/7111 [16:19<22:32,  2.33it/s]

Reports:  56%|█████▌    | 3960/7111 [16:19<22:40,  2.32it/s]

Reports:  56%|█████▌    | 3961/7111 [16:19<19:21,  2.71it/s]

Reports:  56%|█████▌    | 3962/7111 [16:19<16:39,  3.15it/s]

Reports:  56%|█████▌    | 3963/7111 [16:20<14:32,  3.61it/s]

Reports:  56%|█████▌    | 3964/7111 [16:20<13:21,  3.92it/s]

Reports:  56%|█████▌    | 3965/7111 [16:20<12:28,  4.20it/s]

Reports:  56%|█████▌    | 3966/7111 [16:20<11:36,  4.52it/s]

Reports:  56%|█████▌    | 3967/7111 [16:20<11:08,  4.71it/s]

Reports:  56%|█████▌    | 3968/7111 [16:21<10:57,  4.78it/s]

Reports:  56%|█████▌    | 3969/7111 [16:21<10:49,  4.84it/s]

Reports:  56%|█████▌    | 3970/7111 [16:21<10:34,  4.95it/s]

Reports:  56%|█████▌    | 3971/7111 [16:21<10:18,  5.08it/s]

Reports:  56%|█████▌    | 3972/7111 [16:21<10:29,  4.98it/s]

Reports:  56%|█████▌    | 3973/7111 [16:22<10:21,  5.05it/s]

Reports:  56%|█████▌    | 3974/7111 [16:22<11:07,  4.70it/s]

Reports:  56%|█████▌    | 3975/7111 [16:22<11:03,  4.73it/s]

Reports:  56%|█████▌    | 3976/7111 [16:22<10:45,  4.85it/s]

Reports:  56%|█████▌    | 3977/7111 [16:22<10:31,  4.96it/s]

Reports:  56%|█████▌    | 3978/7111 [16:23<10:19,  5.06it/s]

Reports:  56%|█████▌    | 3979/7111 [16:23<10:38,  4.91it/s]

Reports:  56%|█████▌    | 3980/7111 [16:23<10:34,  4.93it/s]

Reports:  56%|█████▌    | 3981/7111 [16:24<15:42,  3.32it/s]

Reports:  56%|█████▌    | 3982/7111 [16:24<13:52,  3.76it/s]

Reports:  56%|█████▌    | 3983/7111 [16:24<12:39,  4.12it/s]

Reports:  56%|█████▌    | 3984/7111 [16:24<11:48,  4.42it/s]

Reports:  56%|█████▌    | 3985/7111 [16:24<11:26,  4.56it/s]

Reports:  56%|█████▌    | 3986/7111 [16:25<10:52,  4.79it/s]

Reports:  56%|█████▌    | 3987/7111 [16:25<10:45,  4.84it/s]

Reports:  56%|█████▌    | 3988/7111 [16:25<10:32,  4.94it/s]

Reports:  56%|█████▌    | 3989/7111 [16:25<10:19,  5.04it/s]

Reports:  56%|█████▌    | 3990/7111 [16:25<10:12,  5.09it/s]

Reports:  56%|█████▌    | 3991/7111 [16:26<10:08,  5.13it/s]

Reports:  56%|█████▌    | 3992/7111 [16:26<10:08,  5.13it/s]

Reports:  56%|█████▌    | 3993/7111 [16:26<09:57,  5.22it/s]

Reports:  56%|█████▌    | 3994/7111 [16:26<09:50,  5.28it/s]

Reports:  56%|█████▌    | 3995/7111 [16:26<09:47,  5.31it/s]

Reports:  56%|█████▌    | 3996/7111 [16:26<09:53,  5.25it/s]

Reports:  56%|█████▌    | 3997/7111 [16:27<09:51,  5.26it/s]

Reports:  56%|█████▌    | 3998/7111 [16:27<09:53,  5.24it/s]

Reports:  56%|█████▌    | 3999/7111 [16:27<10:01,  5.17it/s]

Reports:  56%|█████▋    | 4000/7111 [16:27<10:13,  5.07it/s]

Reports:  56%|█████▋    | 4001/7111 [16:27<10:19,  5.02it/s]

Reports:  56%|█████▋    | 4002/7111 [16:28<10:09,  5.10it/s]

Reports:  56%|█████▋    | 4003/7111 [16:28<10:03,  5.15it/s]

Reports:  56%|█████▋    | 4004/7111 [16:28<10:01,  5.16it/s]

Reports:  56%|█████▋    | 4005/7111 [16:28<09:54,  5.23it/s]

Reports:  56%|█████▋    | 4006/7111 [16:28<10:00,  5.17it/s]

Reports:  56%|█████▋    | 4007/7111 [16:29<10:07,  5.11it/s]

Reports:  56%|█████▋    | 4008/7111 [16:30<22:07,  2.34it/s]

Reports:  56%|█████▋    | 4009/7111 [16:30<18:39,  2.77it/s]

Reports:  56%|█████▋    | 4010/7111 [16:30<16:10,  3.20it/s]

Reports:  56%|█████▋    | 4011/7111 [16:30<15:21,  3.36it/s]

Reports:  56%|█████▋    | 4012/7111 [16:30<13:39,  3.78it/s]

Reports:  56%|█████▋    | 4013/7111 [16:31<12:58,  3.98it/s]

Reports:  56%|█████▋    | 4014/7111 [16:31<12:14,  4.22it/s]

Reports:  56%|█████▋    | 4015/7111 [16:31<11:41,  4.41it/s]

Reports:  56%|█████▋    | 4016/7111 [16:31<12:18,  4.19it/s]

Reports:  56%|█████▋    | 4017/7111 [16:32<11:33,  4.46it/s]

Reports:  57%|█████▋    | 4018/7111 [16:32<11:14,  4.58it/s]

Reports:  57%|█████▋    | 4019/7111 [16:32<11:02,  4.67it/s]

Reports:  57%|█████▋    | 4020/7111 [16:32<10:52,  4.74it/s]

Reports:  57%|█████▋    | 4021/7111 [16:33<22:48,  2.26it/s]

Reports:  57%|█████▋    | 4022/7111 [16:33<19:07,  2.69it/s]

Reports:  57%|█████▋    | 4023/7111 [16:34<16:30,  3.12it/s]

Reports:  57%|█████▋    | 4024/7111 [16:34<14:38,  3.51it/s]

Reports:  57%|█████▋    | 4025/7111 [16:34<13:09,  3.91it/s]

Reports:  57%|█████▋    | 4026/7111 [16:34<12:14,  4.20it/s]

Reports:  57%|█████▋    | 4027/7111 [16:34<11:38,  4.42it/s]

Reports:  57%|█████▋    | 4028/7111 [16:34<11:02,  4.66it/s]

Reports:  57%|█████▋    | 4029/7111 [16:35<10:38,  4.83it/s]

Reports:  57%|█████▋    | 4030/7111 [16:35<12:17,  4.18it/s]

Reports:  57%|█████▋    | 4031/7111 [16:35<11:29,  4.47it/s]

Reports:  57%|█████▋    | 4032/7111 [16:35<11:16,  4.55it/s]

Reports:  57%|█████▋    | 4033/7111 [16:36<11:05,  4.62it/s]

Reports:  57%|█████▋    | 4034/7111 [16:36<10:49,  4.74it/s]

Reports:  57%|█████▋    | 4035/7111 [16:36<10:25,  4.91it/s]

Reports:  57%|█████▋    | 4036/7111 [16:36<10:21,  4.95it/s]

Reports:  57%|█████▋    | 4037/7111 [16:36<10:08,  5.05it/s]

Reports:  57%|█████▋    | 4038/7111 [16:37<09:57,  5.14it/s]

Reports:  57%|█████▋    | 4039/7111 [16:37<10:04,  5.08it/s]

Reports:  57%|█████▋    | 4040/7111 [16:37<09:57,  5.14it/s]

Reports:  57%|█████▋    | 4041/7111 [16:37<09:55,  5.16it/s]

Reports:  57%|█████▋    | 4042/7111 [16:37<09:51,  5.19it/s]

Reports:  57%|█████▋    | 4043/7111 [16:38<09:49,  5.20it/s]

Reports:  57%|█████▋    | 4044/7111 [16:38<09:45,  5.24it/s]

Reports:  57%|█████▋    | 4045/7111 [16:38<09:52,  5.17it/s]

Reports:  57%|█████▋    | 4046/7111 [16:38<10:03,  5.08it/s]

Reports:  57%|█████▋    | 4047/7111 [16:38<10:05,  5.06it/s]

Reports:  57%|█████▋    | 4048/7111 [16:39<10:06,  5.05it/s]

Reports:  57%|█████▋    | 4049/7111 [16:39<10:10,  5.01it/s]

Reports:  57%|█████▋    | 4050/7111 [16:39<10:08,  5.03it/s]

Reports:  57%|█████▋    | 4051/7111 [16:39<10:08,  5.03it/s]

Reports:  57%|█████▋    | 4052/7111 [16:39<10:02,  5.07it/s]

Reports:  57%|█████▋    | 4053/7111 [16:39<10:00,  5.09it/s]

Reports:  57%|█████▋    | 4054/7111 [16:40<09:52,  5.16it/s]

Reports:  57%|█████▋    | 4055/7111 [16:40<09:48,  5.19it/s]

Reports:  57%|█████▋    | 4056/7111 [16:40<09:59,  5.10it/s]

Reports:  57%|█████▋    | 4057/7111 [16:40<09:54,  5.14it/s]

Reports:  57%|█████▋    | 4058/7111 [16:40<09:44,  5.23it/s]

Reports:  57%|█████▋    | 4059/7111 [16:41<09:42,  5.24it/s]

Reports:  57%|█████▋    | 4060/7111 [16:41<09:41,  5.25it/s]

Reports:  57%|█████▋    | 4061/7111 [16:41<09:45,  5.21it/s]

Reports:  57%|█████▋    | 4062/7111 [16:41<09:40,  5.25it/s]

Reports:  57%|█████▋    | 4063/7111 [16:41<09:49,  5.17it/s]

Reports:  57%|█████▋    | 4064/7111 [16:42<09:50,  5.16it/s]

Reports:  57%|█████▋    | 4065/7111 [16:42<09:59,  5.08it/s]

Reports:  57%|█████▋    | 4066/7111 [16:42<09:54,  5.12it/s]

Reports:  57%|█████▋    | 4067/7111 [16:42<09:59,  5.08it/s]

Reports:  57%|█████▋    | 4068/7111 [16:42<10:06,  5.02it/s]

Reports:  57%|█████▋    | 4069/7111 [16:43<10:22,  4.89it/s]

Reports:  57%|█████▋    | 4070/7111 [16:43<10:06,  5.01it/s]

Reports:  57%|█████▋    | 4071/7111 [16:43<09:59,  5.07it/s]

Reports:  57%|█████▋    | 4072/7111 [16:43<10:05,  5.02it/s]

Reports:  57%|█████▋    | 4073/7111 [16:43<10:05,  5.02it/s]

Reports:  57%|█████▋    | 4074/7111 [16:44<10:01,  5.05it/s]

Reports:  57%|█████▋    | 4075/7111 [16:44<09:57,  5.08it/s]

Reports:  57%|█████▋    | 4076/7111 [16:44<09:48,  5.16it/s]

Reports:  57%|█████▋    | 4077/7111 [16:44<09:51,  5.13it/s]

Reports:  57%|█████▋    | 4078/7111 [16:44<09:47,  5.16it/s]

Reports:  57%|█████▋    | 4079/7111 [16:45<09:42,  5.21it/s]

Reports:  57%|█████▋    | 4080/7111 [16:45<09:42,  5.21it/s]

Reports:  57%|█████▋    | 4081/7111 [16:45<09:35,  5.27it/s]

Reports:  57%|█████▋    | 4082/7111 [16:45<11:05,  4.55it/s]

Reports:  57%|█████▋    | 4083/7111 [16:45<10:38,  4.74it/s]

Reports:  57%|█████▋    | 4084/7111 [16:46<10:28,  4.82it/s]

Reports:  57%|█████▋    | 4085/7111 [16:46<10:14,  4.92it/s]

Reports:  57%|█████▋    | 4086/7111 [16:46<10:05,  5.00it/s]

Reports:  57%|█████▋    | 4087/7111 [16:46<10:23,  4.85it/s]

Reports:  57%|█████▋    | 4088/7111 [16:46<10:17,  4.89it/s]

Reports:  58%|█████▊    | 4089/7111 [16:47<10:05,  4.99it/s]

Reports:  58%|█████▊    | 4090/7111 [16:47<09:59,  5.04it/s]

Reports:  58%|█████▊    | 4091/7111 [16:47<09:50,  5.12it/s]

Reports:  58%|█████▊    | 4092/7111 [16:47<09:49,  5.12it/s]

Reports:  58%|█████▊    | 4093/7111 [16:47<09:39,  5.21it/s]

Reports:  58%|█████▊    | 4094/7111 [16:48<09:46,  5.14it/s]

Reports:  58%|█████▊    | 4095/7111 [16:48<09:39,  5.21it/s]

Reports:  58%|█████▊    | 4096/7111 [16:48<09:45,  5.15it/s]

Reports:  58%|█████▊    | 4097/7111 [16:48<09:36,  5.23it/s]

Reports:  58%|█████▊    | 4098/7111 [16:48<09:46,  5.14it/s]

Reports:  58%|█████▊    | 4099/7111 [16:49<09:49,  5.11it/s]

Reports:  58%|█████▊    | 4100/7111 [16:49<09:42,  5.17it/s]

Reports:  58%|█████▊    | 4101/7111 [16:49<09:57,  5.04it/s]

Reports:  58%|█████▊    | 4102/7111 [16:49<10:02,  4.99it/s]

Reports:  58%|█████▊    | 4103/7111 [16:49<10:04,  4.97it/s]

Reports:  58%|█████▊    | 4104/7111 [16:50<10:11,  4.91it/s]

Reports:  58%|█████▊    | 4105/7111 [16:50<09:57,  5.04it/s]

Reports:  58%|█████▊    | 4106/7111 [16:50<10:16,  4.87it/s]

Reports:  58%|█████▊    | 4107/7111 [16:50<10:01,  4.99it/s]

Reports:  58%|█████▊    | 4108/7111 [16:50<09:48,  5.10it/s]

Reports:  58%|█████▊    | 4109/7111 [16:51<10:04,  4.97it/s]

Reports:  58%|█████▊    | 4110/7111 [16:51<10:15,  4.87it/s]

Reports:  58%|█████▊    | 4111/7111 [16:52<18:50,  2.65it/s]

Reports:  58%|█████▊    | 4112/7111 [16:52<16:14,  3.08it/s]

Reports:  58%|█████▊    | 4113/7111 [16:52<14:23,  3.47it/s]

Reports:  58%|█████▊    | 4114/7111 [16:52<12:56,  3.86it/s]

Reports:  58%|█████▊    | 4115/7111 [16:52<12:02,  4.15it/s]

Reports:  58%|█████▊    | 4116/7111 [16:53<11:28,  4.35it/s]

Reports:  58%|█████▊    | 4117/7111 [16:53<11:00,  4.53it/s]

Reports:  58%|█████▊    | 4118/7111 [16:53<10:36,  4.71it/s]

Reports:  58%|█████▊    | 4119/7111 [16:53<10:27,  4.76it/s]

Reports:  58%|█████▊    | 4120/7111 [16:53<10:07,  4.92it/s]

Reports:  58%|█████▊    | 4121/7111 [16:54<09:53,  5.04it/s]

Reports:  58%|█████▊    | 4122/7111 [16:54<09:49,  5.07it/s]

Reports:  58%|█████▊    | 4123/7111 [16:54<09:37,  5.17it/s]

Reports:  58%|█████▊    | 4124/7111 [16:54<09:45,  5.10it/s]

Reports:  58%|█████▊    | 4125/7111 [16:54<09:37,  5.17it/s]

Reports:  58%|█████▊    | 4126/7111 [16:54<09:30,  5.23it/s]

Reports:  58%|█████▊    | 4127/7111 [16:55<09:23,  5.30it/s]

Reports:  58%|█████▊    | 4128/7111 [16:55<09:28,  5.24it/s]

Reports:  58%|█████▊    | 4129/7111 [16:55<09:28,  5.24it/s]

Reports:  58%|█████▊    | 4130/7111 [16:55<09:41,  5.13it/s]

Reports:  58%|█████▊    | 4131/7111 [16:55<09:36,  5.17it/s]

Reports:  58%|█████▊    | 4132/7111 [16:56<09:32,  5.20it/s]

Reports:  58%|█████▊    | 4133/7111 [16:56<09:42,  5.11it/s]

Reports:  58%|█████▊    | 4134/7111 [16:56<09:45,  5.09it/s]

Reports:  58%|█████▊    | 4135/7111 [16:56<09:46,  5.08it/s]

Reports:  58%|█████▊    | 4136/7111 [16:56<09:45,  5.08it/s]

Reports:  58%|█████▊    | 4137/7111 [16:57<09:41,  5.11it/s]

Reports:  58%|█████▊    | 4138/7111 [16:57<09:36,  5.16it/s]

Reports:  58%|█████▊    | 4139/7111 [16:57<09:30,  5.21it/s]

Reports:  58%|█████▊    | 4140/7111 [16:57<09:23,  5.27it/s]

Reports:  58%|█████▊    | 4141/7111 [16:57<09:21,  5.29it/s]

Reports:  58%|█████▊    | 4142/7111 [16:58<09:17,  5.32it/s]

Reports:  58%|█████▊    | 4143/7111 [16:58<09:20,  5.30it/s]

Reports:  58%|█████▊    | 4144/7111 [16:58<09:14,  5.35it/s]

Reports:  58%|█████▊    | 4145/7111 [16:58<09:15,  5.34it/s]

Reports:  58%|█████▊    | 4146/7111 [16:58<09:26,  5.23it/s]

Reports:  58%|█████▊    | 4147/7111 [16:59<09:29,  5.20it/s]

Reports:  58%|█████▊    | 4148/7111 [16:59<09:23,  5.26it/s]

Reports:  58%|█████▊    | 4149/7111 [16:59<09:31,  5.19it/s]

Reports:  58%|█████▊    | 4150/7111 [16:59<09:38,  5.12it/s]

Reports:  58%|█████▊    | 4151/7111 [17:00<13:15,  3.72it/s]

Reports:  58%|█████▊    | 4152/7111 [17:00<12:04,  4.08it/s]

Reports:  58%|█████▊    | 4153/7111 [17:00<11:23,  4.33it/s]

Reports:  58%|█████▊    | 4154/7111 [17:00<10:55,  4.51it/s]

Reports:  58%|█████▊    | 4155/7111 [17:00<10:32,  4.67it/s]

Reports:  58%|█████▊    | 4156/7111 [17:01<10:09,  4.85it/s]

Reports:  58%|█████▊    | 4157/7111 [17:01<09:59,  4.93it/s]

Reports:  58%|█████▊    | 4158/7111 [17:01<09:47,  5.03it/s]

Reports:  58%|█████▊    | 4159/7111 [17:01<09:34,  5.14it/s]

Reports:  59%|█████▊    | 4160/7111 [17:01<09:49,  5.01it/s]

Reports:  59%|█████▊    | 4161/7111 [17:01<09:38,  5.10it/s]

Reports:  59%|█████▊    | 4162/7111 [17:02<09:33,  5.14it/s]

Reports:  59%|█████▊    | 4163/7111 [17:02<09:25,  5.22it/s]

Reports:  59%|█████▊    | 4164/7111 [17:02<09:25,  5.21it/s]

Reports:  59%|█████▊    | 4165/7111 [17:02<09:31,  5.16it/s]

Reports:  59%|█████▊    | 4166/7111 [17:02<09:21,  5.25it/s]

Reports:  59%|█████▊    | 4167/7111 [17:03<09:22,  5.23it/s]

Reports:  59%|█████▊    | 4168/7111 [17:03<09:27,  5.18it/s]

Reports:  59%|█████▊    | 4169/7111 [17:03<09:27,  5.18it/s]

Reports:  59%|█████▊    | 4170/7111 [17:03<12:21,  3.96it/s]

Reports:  59%|█████▊    | 4171/7111 [17:04<11:35,  4.23it/s]

Reports:  59%|█████▊    | 4172/7111 [17:04<10:51,  4.51it/s]

Reports:  59%|█████▊    | 4173/7111 [17:04<10:14,  4.78it/s]

Reports:  59%|█████▊    | 4174/7111 [17:04<10:16,  4.76it/s]

Reports:  59%|█████▊    | 4175/7111 [17:04<09:55,  4.93it/s]

Reports:  59%|█████▊    | 4176/7111 [17:05<09:50,  4.97it/s]

Reports:  59%|█████▊    | 4177/7111 [17:05<09:41,  5.04it/s]

Reports:  59%|█████▉    | 4178/7111 [17:05<09:33,  5.12it/s]

Reports:  59%|█████▉    | 4179/7111 [17:05<09:36,  5.09it/s]

Reports:  59%|█████▉    | 4180/7111 [17:05<09:50,  4.96it/s]

Reports:  59%|█████▉    | 4181/7111 [17:06<09:45,  5.01it/s]

Reports:  59%|█████▉    | 4182/7111 [17:06<09:34,  5.10it/s]

Reports:  59%|█████▉    | 4183/7111 [17:06<09:27,  5.16it/s]

Reports:  59%|█████▉    | 4184/7111 [17:06<09:25,  5.18it/s]

Reports:  59%|█████▉    | 4185/7111 [17:06<09:37,  5.06it/s]

Reports:  59%|█████▉    | 4186/7111 [17:07<09:40,  5.04it/s]

Reports:  59%|█████▉    | 4187/7111 [17:07<09:27,  5.15it/s]

Reports:  59%|█████▉    | 4188/7111 [17:07<09:25,  5.17it/s]

Reports:  59%|█████▉    | 4189/7111 [17:07<09:36,  5.07it/s]

Reports:  59%|█████▉    | 4190/7111 [17:07<09:28,  5.13it/s]

Reports:  59%|█████▉    | 4191/7111 [17:07<09:31,  5.11it/s]

Reports:  59%|█████▉    | 4192/7111 [17:08<09:26,  5.15it/s]

Reports:  59%|█████▉    | 4193/7111 [17:08<09:19,  5.22it/s]

Reports:  59%|█████▉    | 4194/7111 [17:08<09:15,  5.25it/s]

Reports:  59%|█████▉    | 4195/7111 [17:08<09:23,  5.18it/s]

Reports:  59%|█████▉    | 4196/7111 [17:08<09:19,  5.21it/s]

Reports:  59%|█████▉    | 4197/7111 [17:09<09:16,  5.24it/s]

Reports:  59%|█████▉    | 4198/7111 [17:09<09:19,  5.20it/s]

Reports:  59%|█████▉    | 4199/7111 [17:09<09:29,  5.11it/s]

Reports:  59%|█████▉    | 4200/7111 [17:09<09:25,  5.14it/s]

Reports:  59%|█████▉    | 4201/7111 [17:09<09:29,  5.11it/s]

Reports:  59%|█████▉    | 4202/7111 [17:10<09:42,  4.99it/s]

Reports:  59%|█████▉    | 4203/7111 [17:10<09:32,  5.08it/s]

Reports:  59%|█████▉    | 4204/7111 [17:10<14:36,  3.32it/s]

Reports:  59%|█████▉    | 4205/7111 [17:11<12:56,  3.74it/s]

Reports:  59%|█████▉    | 4206/7111 [17:11<11:46,  4.11it/s]

Reports:  59%|█████▉    | 4207/7111 [17:11<11:04,  4.37it/s]

Reports:  59%|█████▉    | 4208/7111 [17:11<10:31,  4.59it/s]

Reports:  59%|█████▉    | 4209/7111 [17:11<10:07,  4.78it/s]

Reports:  59%|█████▉    | 4210/7111 [17:12<10:07,  4.78it/s]

Reports:  59%|█████▉    | 4211/7111 [17:12<09:43,  4.97it/s]

Reports:  59%|█████▉    | 4212/7111 [17:12<09:28,  5.10it/s]

Reports:  59%|█████▉    | 4213/7111 [17:12<09:33,  5.06it/s]

Reports:  59%|█████▉    | 4214/7111 [17:12<09:27,  5.10it/s]

Reports:  59%|█████▉    | 4215/7111 [17:12<09:21,  5.16it/s]

Reports:  59%|█████▉    | 4216/7111 [17:13<09:14,  5.22it/s]

Reports:  59%|█████▉    | 4217/7111 [17:13<09:29,  5.08it/s]

Reports:  59%|█████▉    | 4218/7111 [17:13<15:10,  3.18it/s]

Reports:  59%|█████▉    | 4219/7111 [17:14<13:19,  3.62it/s]

Reports:  59%|█████▉    | 4220/7111 [17:14<12:22,  3.89it/s]

Reports:  59%|█████▉    | 4221/7111 [17:14<11:29,  4.19it/s]

Reports:  59%|█████▉    | 4222/7111 [17:14<10:51,  4.44it/s]

Reports:  59%|█████▉    | 4223/7111 [17:14<10:19,  4.66it/s]

Reports:  59%|█████▉    | 4224/7111 [17:15<09:55,  4.85it/s]

Reports:  59%|█████▉    | 4225/7111 [17:15<09:45,  4.93it/s]

Reports:  59%|█████▉    | 4226/7111 [17:15<09:32,  5.04it/s]

Reports:  59%|█████▉    | 4227/7111 [17:15<09:38,  4.99it/s]

Reports:  59%|█████▉    | 4228/7111 [17:15<10:00,  4.80it/s]

Reports:  59%|█████▉    | 4229/7111 [17:16<09:52,  4.87it/s]

Reports:  59%|█████▉    | 4230/7111 [17:16<09:34,  5.01it/s]

Reports:  59%|█████▉    | 4231/7111 [17:16<09:31,  5.04it/s]

Reports:  60%|█████▉    | 4232/7111 [17:16<09:30,  5.05it/s]

Reports:  60%|█████▉    | 4233/7111 [17:16<09:23,  5.11it/s]

Reports:  60%|█████▉    | 4234/7111 [17:17<09:38,  4.97it/s]

Reports:  60%|█████▉    | 4235/7111 [17:17<09:39,  4.97it/s]

Reports:  60%|█████▉    | 4236/7111 [17:17<09:29,  5.05it/s]

Reports:  60%|█████▉    | 4237/7111 [17:17<09:25,  5.08it/s]

Reports:  60%|█████▉    | 4238/7111 [17:17<09:18,  5.14it/s]

Reports:  60%|█████▉    | 4239/7111 [17:18<09:36,  4.99it/s]

Reports:  60%|█████▉    | 4240/7111 [17:18<09:36,  4.98it/s]

Reports:  60%|█████▉    | 4241/7111 [17:18<09:42,  4.92it/s]

Reports:  60%|█████▉    | 4242/7111 [17:18<09:36,  4.98it/s]

Reports:  60%|█████▉    | 4243/7111 [17:18<09:32,  5.01it/s]

Reports:  60%|█████▉    | 4244/7111 [17:19<09:54,  4.82it/s]

Reports:  60%|█████▉    | 4245/7111 [17:19<09:44,  4.90it/s]

Reports:  60%|█████▉    | 4246/7111 [17:19<09:34,  4.99it/s]

Reports:  60%|█████▉    | 4247/7111 [17:19<09:36,  4.97it/s]

Reports:  60%|█████▉    | 4248/7111 [17:19<09:28,  5.04it/s]

Reports:  60%|█████▉    | 4249/7111 [17:20<09:22,  5.09it/s]

Reports:  60%|█████▉    | 4250/7111 [17:20<09:31,  5.00it/s]

Reports:  60%|█████▉    | 4251/7111 [17:20<09:22,  5.09it/s]

Reports:  60%|█████▉    | 4252/7111 [17:20<09:08,  5.21it/s]

Reports:  60%|█████▉    | 4253/7111 [17:20<09:16,  5.14it/s]

Reports:  60%|█████▉    | 4254/7111 [17:21<09:39,  4.93it/s]

Reports:  60%|█████▉    | 4255/7111 [17:21<09:24,  5.06it/s]

Reports:  60%|█████▉    | 4256/7111 [17:21<09:14,  5.15it/s]

Reports:  60%|█████▉    | 4257/7111 [17:21<09:21,  5.08it/s]

Reports:  60%|█████▉    | 4258/7111 [17:21<09:14,  5.15it/s]

Reports:  60%|█████▉    | 4259/7111 [17:22<09:13,  5.15it/s]

Reports:  60%|█████▉    | 4260/7111 [17:22<09:15,  5.14it/s]

Reports:  60%|█████▉    | 4261/7111 [17:22<09:14,  5.14it/s]

Reports:  60%|█████▉    | 4262/7111 [17:22<09:06,  5.21it/s]

Reports:  60%|█████▉    | 4263/7111 [17:22<09:05,  5.22it/s]

Reports:  60%|█████▉    | 4264/7111 [17:23<09:06,  5.21it/s]

Reports:  60%|█████▉    | 4265/7111 [17:23<09:06,  5.21it/s]

Reports:  60%|█████▉    | 4266/7111 [17:23<09:11,  5.16it/s]

Reports:  60%|██████    | 4267/7111 [17:23<09:07,  5.19it/s]

Reports:  60%|██████    | 4268/7111 [17:23<09:06,  5.20it/s]

Reports:  60%|██████    | 4269/7111 [17:24<09:21,  5.06it/s]

Reports:  60%|██████    | 4270/7111 [17:24<09:14,  5.12it/s]

Reports:  60%|██████    | 4271/7111 [17:24<09:10,  5.16it/s]

Reports:  60%|██████    | 4272/7111 [17:24<09:17,  5.09it/s]

Reports:  60%|██████    | 4273/7111 [17:24<09:06,  5.19it/s]

Reports:  60%|██████    | 4274/7111 [17:24<08:58,  5.27it/s]

Reports:  60%|██████    | 4275/7111 [17:25<09:08,  5.17it/s]

Reports:  60%|██████    | 4276/7111 [17:25<09:04,  5.20it/s]

Reports:  60%|██████    | 4277/7111 [17:25<08:59,  5.25it/s]

Reports:  60%|██████    | 4278/7111 [17:25<09:18,  5.07it/s]

Reports:  60%|██████    | 4279/7111 [17:25<09:21,  5.04it/s]

Reports:  60%|██████    | 4280/7111 [17:26<09:25,  5.01it/s]

Reports:  60%|██████    | 4281/7111 [17:26<09:33,  4.93it/s]

Reports:  60%|██████    | 4282/7111 [17:26<09:35,  4.92it/s]

Reports:  60%|██████    | 4283/7111 [17:26<09:28,  4.97it/s]

Reports:  60%|██████    | 4284/7111 [17:26<09:17,  5.07it/s]

Reports:  60%|██████    | 4285/7111 [17:27<09:10,  5.14it/s]

Reports:  60%|██████    | 4286/7111 [17:27<09:15,  5.09it/s]

Reports:  60%|██████    | 4287/7111 [17:27<09:13,  5.11it/s]

Reports:  60%|██████    | 4288/7111 [17:27<09:18,  5.06it/s]

Reports:  60%|██████    | 4289/7111 [17:27<09:11,  5.11it/s]

Reports:  60%|██████    | 4290/7111 [17:28<09:09,  5.14it/s]

Reports:  60%|██████    | 4291/7111 [17:28<09:14,  5.09it/s]

Reports:  60%|██████    | 4292/7111 [17:28<09:16,  5.06it/s]

Reports:  60%|██████    | 4293/7111 [17:28<09:14,  5.08it/s]

Reports:  60%|██████    | 4294/7111 [17:28<09:17,  5.05it/s]

Reports:  60%|██████    | 4295/7111 [17:29<09:13,  5.09it/s]

Reports:  60%|██████    | 4296/7111 [17:29<09:24,  4.99it/s]

Reports:  60%|██████    | 4297/7111 [17:29<09:23,  5.00it/s]

Reports:  60%|██████    | 4298/7111 [17:29<09:24,  4.98it/s]

Reports:  60%|██████    | 4299/7111 [17:29<09:15,  5.06it/s]

Reports:  60%|██████    | 4300/7111 [17:30<09:06,  5.15it/s]

Reports:  60%|██████    | 4301/7111 [17:30<08:59,  5.21it/s]

Reports:  60%|██████    | 4302/7111 [17:30<08:57,  5.23it/s]

Reports:  61%|██████    | 4303/7111 [17:30<09:01,  5.18it/s]

Reports:  61%|██████    | 4304/7111 [17:30<09:18,  5.02it/s]

Reports:  61%|██████    | 4305/7111 [17:31<09:08,  5.11it/s]

Reports:  61%|██████    | 4306/7111 [17:31<09:02,  5.17it/s]

Reports:  61%|██████    | 4307/7111 [17:31<09:12,  5.08it/s]

Reports:  61%|██████    | 4308/7111 [17:31<09:16,  5.04it/s]

Reports:  61%|██████    | 4309/7111 [17:32<19:41,  2.37it/s]

Reports:  61%|██████    | 4310/7111 [17:32<16:22,  2.85it/s]

Reports:  61%|██████    | 4311/7111 [17:32<14:04,  3.31it/s]

Reports:  61%|██████    | 4312/7111 [17:33<12:35,  3.71it/s]

Reports:  61%|██████    | 4313/7111 [17:33<11:29,  4.06it/s]

Reports:  61%|██████    | 4314/7111 [17:33<10:40,  4.37it/s]

Reports:  61%|██████    | 4315/7111 [17:33<10:06,  4.61it/s]

Reports:  61%|██████    | 4316/7111 [17:33<09:39,  4.83it/s]

Reports:  61%|██████    | 4317/7111 [17:34<09:23,  4.96it/s]

Reports:  61%|██████    | 4318/7111 [17:34<09:18,  5.00it/s]

Reports:  61%|██████    | 4319/7111 [17:34<09:21,  4.97it/s]

Reports:  61%|██████    | 4320/7111 [17:34<09:11,  5.06it/s]

Reports:  61%|██████    | 4321/7111 [17:34<09:06,  5.10it/s]

Reports:  61%|██████    | 4322/7111 [17:35<09:09,  5.08it/s]

Reports:  61%|██████    | 4323/7111 [17:35<09:04,  5.12it/s]

Reports:  61%|██████    | 4324/7111 [17:35<09:07,  5.09it/s]

Reports:  61%|██████    | 4325/7111 [17:35<09:00,  5.16it/s]

Reports:  61%|██████    | 4326/7111 [17:35<09:07,  5.08it/s]

Reports:  61%|██████    | 4327/7111 [17:36<08:58,  5.17it/s]

Reports:  61%|██████    | 4328/7111 [17:36<08:51,  5.24it/s]

Reports:  61%|██████    | 4329/7111 [17:36<08:48,  5.26it/s]

Reports:  61%|██████    | 4330/7111 [17:36<08:42,  5.32it/s]

Reports:  61%|██████    | 4331/7111 [17:36<08:50,  5.24it/s]

Reports:  61%|██████    | 4332/7111 [17:37<08:47,  5.27it/s]

Reports:  61%|██████    | 4333/7111 [17:37<08:57,  5.17it/s]

Reports:  61%|██████    | 4334/7111 [17:37<08:48,  5.25it/s]

Reports:  61%|██████    | 4335/7111 [17:37<08:59,  5.14it/s]

Reports:  61%|██████    | 4336/7111 [17:37<09:00,  5.13it/s]

Reports:  61%|██████    | 4337/7111 [17:38<09:05,  5.08it/s]

Reports:  61%|██████    | 4338/7111 [17:38<09:04,  5.10it/s]

Reports:  61%|██████    | 4339/7111 [17:38<09:01,  5.12it/s]

Reports:  61%|██████    | 4340/7111 [17:38<09:13,  5.01it/s]

Reports:  61%|██████    | 4341/7111 [17:38<09:15,  4.99it/s]

Reports:  61%|██████    | 4342/7111 [17:39<17:37,  2.62it/s]

Reports:  61%|██████    | 4343/7111 [17:39<15:01,  3.07it/s]

Reports:  61%|██████    | 4344/7111 [17:40<13:12,  3.49it/s]

Reports:  61%|██████    | 4345/7111 [17:40<11:50,  3.89it/s]

Reports:  61%|██████    | 4346/7111 [17:40<11:03,  4.17it/s]

Reports:  61%|██████    | 4347/7111 [17:40<10:25,  4.42it/s]

Reports:  61%|██████    | 4348/7111 [17:40<09:58,  4.61it/s]

Reports:  61%|██████    | 4349/7111 [17:40<09:31,  4.83it/s]

Reports:  61%|██████    | 4350/7111 [17:41<09:24,  4.89it/s]

Reports:  61%|██████    | 4351/7111 [17:41<09:07,  5.04it/s]

Reports:  61%|██████    | 4352/7111 [17:41<09:09,  5.02it/s]

Reports:  61%|██████    | 4353/7111 [17:41<09:13,  4.98it/s]

Reports:  61%|██████    | 4354/7111 [17:41<09:06,  5.05it/s]

Reports:  61%|██████    | 4355/7111 [17:42<09:05,  5.05it/s]

Reports:  61%|██████▏   | 4356/7111 [17:42<09:01,  5.09it/s]

Reports:  61%|██████▏   | 4357/7111 [17:42<09:05,  5.05it/s]

Reports:  61%|██████▏   | 4358/7111 [17:42<09:23,  4.89it/s]

Reports:  61%|██████▏   | 4359/7111 [17:42<09:19,  4.91it/s]

Reports:  61%|██████▏   | 4360/7111 [17:43<09:19,  4.92it/s]

Reports:  61%|██████▏   | 4361/7111 [17:43<09:14,  4.96it/s]

Reports:  61%|██████▏   | 4362/7111 [17:43<09:12,  4.97it/s]

Reports:  61%|██████▏   | 4363/7111 [17:43<09:07,  5.02it/s]

Reports:  61%|██████▏   | 4364/7111 [17:43<08:56,  5.12it/s]

Reports:  61%|██████▏   | 4365/7111 [17:44<09:00,  5.08it/s]

Reports:  61%|██████▏   | 4366/7111 [17:44<08:54,  5.14it/s]

Reports:  61%|██████▏   | 4367/7111 [17:44<08:48,  5.19it/s]

Reports:  61%|██████▏   | 4368/7111 [17:44<08:54,  5.13it/s]

Reports:  61%|██████▏   | 4369/7111 [17:44<08:52,  5.15it/s]

Reports:  61%|██████▏   | 4370/7111 [17:45<09:02,  5.05it/s]

Reports:  61%|██████▏   | 4371/7111 [17:45<09:03,  5.04it/s]

Reports:  61%|██████▏   | 4372/7111 [17:45<09:00,  5.07it/s]

Reports:  61%|██████▏   | 4373/7111 [17:45<08:50,  5.16it/s]

Reports:  62%|██████▏   | 4374/7111 [17:45<09:03,  5.03it/s]

Reports:  62%|██████▏   | 4375/7111 [17:46<09:17,  4.91it/s]

Reports:  62%|██████▏   | 4376/7111 [17:47<27:14,  1.67it/s]

Reports:  62%|██████▏   | 4377/7111 [17:47<21:45,  2.09it/s]

Reports:  62%|██████▏   | 4378/7111 [17:48<17:51,  2.55it/s]

Reports:  62%|██████▏   | 4379/7111 [17:48<15:23,  2.96it/s]

Reports:  62%|██████▏   | 4380/7111 [17:48<13:22,  3.40it/s]

Reports:  62%|██████▏   | 4381/7111 [17:48<12:07,  3.75it/s]

Reports:  62%|██████▏   | 4382/7111 [17:48<11:05,  4.10it/s]

Reports:  62%|██████▏   | 4383/7111 [17:49<10:25,  4.36it/s]

Reports:  62%|██████▏   | 4384/7111 [17:49<09:53,  4.59it/s]

Reports:  62%|██████▏   | 4385/7111 [17:49<09:30,  4.78it/s]

Reports:  62%|██████▏   | 4386/7111 [17:49<09:14,  4.91it/s]

Reports:  62%|██████▏   | 4387/7111 [17:49<09:26,  4.81it/s]

Reports:  62%|██████▏   | 4388/7111 [17:50<09:25,  4.82it/s]

Reports:  62%|██████▏   | 4389/7111 [17:50<09:22,  4.84it/s]

Reports:  62%|██████▏   | 4390/7111 [17:50<09:22,  4.84it/s]

Reports:  62%|██████▏   | 4391/7111 [17:50<09:11,  4.93it/s]

Reports:  62%|██████▏   | 4392/7111 [17:50<09:11,  4.93it/s]

Reports:  62%|██████▏   | 4393/7111 [17:51<14:27,  3.13it/s]

Reports:  62%|██████▏   | 4394/7111 [17:51<12:47,  3.54it/s]

Reports:  62%|██████▏   | 4395/7111 [17:51<11:44,  3.86it/s]

Reports:  62%|██████▏   | 4396/7111 [17:52<10:50,  4.17it/s]

Reports:  62%|██████▏   | 4397/7111 [17:52<10:30,  4.31it/s]

Reports:  62%|██████▏   | 4398/7111 [17:52<09:57,  4.54it/s]

Reports:  62%|██████▏   | 4399/7111 [17:52<09:41,  4.67it/s]

Reports:  62%|██████▏   | 4400/7111 [17:52<09:23,  4.81it/s]

Reports:  62%|██████▏   | 4401/7111 [17:53<09:18,  4.85it/s]

Reports:  62%|██████▏   | 4402/7111 [17:53<09:06,  4.96it/s]

Reports:  62%|██████▏   | 4403/7111 [17:53<09:10,  4.92it/s]

Reports:  62%|██████▏   | 4404/7111 [17:53<09:07,  4.95it/s]

Reports:  62%|██████▏   | 4405/7111 [17:53<08:54,  5.07it/s]

Reports:  62%|██████▏   | 4406/7111 [17:53<08:52,  5.08it/s]

Reports:  62%|██████▏   | 4407/7111 [17:54<09:01,  4.99it/s]

Reports:  62%|██████▏   | 4408/7111 [17:54<08:54,  5.06it/s]

Reports:  62%|██████▏   | 4409/7111 [17:54<08:53,  5.06it/s]

Reports:  62%|██████▏   | 4410/7111 [17:54<08:53,  5.06it/s]

Reports:  62%|██████▏   | 4411/7111 [17:54<08:50,  5.09it/s]

Reports:  62%|██████▏   | 4412/7111 [17:55<08:51,  5.08it/s]

Reports:  62%|██████▏   | 4413/7111 [17:55<08:58,  5.01it/s]

Reports:  62%|██████▏   | 4414/7111 [17:55<09:04,  4.96it/s]

Reports:  62%|██████▏   | 4415/7111 [17:55<08:53,  5.05it/s]

Reports:  62%|██████▏   | 4416/7111 [17:55<08:47,  5.11it/s]

Reports:  62%|██████▏   | 4417/7111 [17:56<11:53,  3.77it/s]

Reports:  62%|██████▏   | 4418/7111 [17:56<11:00,  4.08it/s]

Reports:  62%|██████▏   | 4419/7111 [17:56<10:31,  4.26it/s]

Reports:  62%|██████▏   | 4420/7111 [17:57<09:59,  4.49it/s]

Reports:  62%|██████▏   | 4421/7111 [17:57<09:28,  4.73it/s]

Reports:  62%|██████▏   | 4422/7111 [17:57<09:09,  4.89it/s]

Reports:  62%|██████▏   | 4423/7111 [17:57<09:01,  4.97it/s]

Reports:  62%|██████▏   | 4424/7111 [17:57<08:57,  5.00it/s]

Reports:  62%|██████▏   | 4425/7111 [17:57<08:49,  5.07it/s]

Reports:  62%|██████▏   | 4426/7111 [17:58<13:43,  3.26it/s]

Reports:  62%|██████▏   | 4427/7111 [17:58<12:13,  3.66it/s]

Reports:  62%|██████▏   | 4428/7111 [17:58<11:07,  4.02it/s]

Reports:  62%|██████▏   | 4429/7111 [17:59<10:15,  4.36it/s]

Reports:  62%|██████▏   | 4430/7111 [17:59<09:48,  4.56it/s]

Reports:  62%|██████▏   | 4431/7111 [17:59<09:26,  4.73it/s]

Reports:  62%|██████▏   | 4432/7111 [17:59<09:12,  4.85it/s]

Reports:  62%|██████▏   | 4433/7111 [17:59<09:03,  4.93it/s]

Reports:  62%|██████▏   | 4434/7111 [18:00<09:02,  4.94it/s]

Reports:  62%|██████▏   | 4435/7111 [18:00<08:55,  5.00it/s]

Reports:  62%|██████▏   | 4436/7111 [18:00<08:45,  5.09it/s]

Reports:  62%|██████▏   | 4437/7111 [18:00<08:45,  5.09it/s]

Reports:  62%|██████▏   | 4438/7111 [18:00<08:39,  5.15it/s]

Reports:  62%|██████▏   | 4439/7111 [18:01<08:40,  5.13it/s]

Reports:  62%|██████▏   | 4440/7111 [18:01<08:45,  5.08it/s]

Reports:  62%|██████▏   | 4441/7111 [18:01<08:43,  5.10it/s]

Reports:  62%|██████▏   | 4442/7111 [18:01<08:43,  5.10it/s]

Reports:  62%|██████▏   | 4443/7111 [18:01<08:38,  5.15it/s]

Reports:  62%|██████▏   | 4444/7111 [18:02<08:32,  5.21it/s]

Reports:  63%|██████▎   | 4445/7111 [18:02<08:26,  5.27it/s]

Reports:  63%|██████▎   | 4446/7111 [18:02<08:29,  5.23it/s]

Reports:  63%|██████▎   | 4447/7111 [18:02<08:22,  5.30it/s]

Reports:  63%|██████▎   | 4448/7111 [18:02<08:24,  5.27it/s]

Reports:  63%|██████▎   | 4449/7111 [18:02<08:19,  5.32it/s]

Reports:  63%|██████▎   | 4450/7111 [18:03<08:17,  5.35it/s]

Reports:  63%|██████▎   | 4451/7111 [18:03<08:29,  5.22it/s]

Reports:  63%|██████▎   | 4452/7111 [18:03<08:28,  5.23it/s]

Reports:  63%|██████▎   | 4453/7111 [18:03<08:43,  5.08it/s]

Reports:  63%|██████▎   | 4454/7111 [18:03<08:38,  5.13it/s]

Reports:  63%|██████▎   | 4455/7111 [18:04<08:40,  5.10it/s]

Reports:  63%|██████▎   | 4456/7111 [18:04<08:33,  5.17it/s]

Reports:  63%|██████▎   | 4457/7111 [18:04<08:39,  5.11it/s]

Reports:  63%|██████▎   | 4458/7111 [18:04<08:35,  5.14it/s]

Reports:  63%|██████▎   | 4459/7111 [18:04<08:42,  5.08it/s]

Reports:  63%|██████▎   | 4460/7111 [18:05<08:51,  4.98it/s]

Reports:  63%|██████▎   | 4461/7111 [18:05<08:45,  5.04it/s]

Reports:  63%|██████▎   | 4462/7111 [18:05<08:36,  5.13it/s]

Reports:  63%|██████▎   | 4463/7111 [18:05<08:32,  5.17it/s]

Reports:  63%|██████▎   | 4464/7111 [18:05<08:34,  5.14it/s]

Reports:  63%|██████▎   | 4465/7111 [18:06<08:38,  5.10it/s]

Reports:  63%|██████▎   | 4466/7111 [18:06<08:31,  5.17it/s]

Reports:  63%|██████▎   | 4467/7111 [18:06<08:46,  5.03it/s]

Reports:  63%|██████▎   | 4468/7111 [18:06<08:45,  5.03it/s]

Reports:  63%|██████▎   | 4469/7111 [18:06<08:47,  5.01it/s]

Reports:  63%|██████▎   | 4470/7111 [18:07<08:37,  5.10it/s]

Reports:  63%|██████▎   | 4471/7111 [18:07<08:33,  5.14it/s]

Reports:  63%|██████▎   | 4472/7111 [18:07<08:31,  5.16it/s]

Reports:  63%|██████▎   | 4473/7111 [18:07<08:23,  5.24it/s]

Reports:  63%|██████▎   | 4474/7111 [18:07<08:20,  5.27it/s]

Reports:  63%|██████▎   | 4475/7111 [18:08<08:25,  5.21it/s]

Reports:  63%|██████▎   | 4476/7111 [18:08<12:45,  3.44it/s]

Reports:  63%|██████▎   | 4477/7111 [18:08<11:28,  3.82it/s]

Reports:  63%|██████▎   | 4478/7111 [18:08<10:39,  4.11it/s]

Reports:  63%|██████▎   | 4479/7111 [18:09<10:16,  4.27it/s]

Reports:  63%|██████▎   | 4480/7111 [18:09<09:53,  4.43it/s]

Reports:  63%|██████▎   | 4481/7111 [18:09<09:19,  4.70it/s]

Reports:  63%|██████▎   | 4482/7111 [18:09<08:57,  4.89it/s]

Reports:  63%|██████▎   | 4483/7111 [18:09<08:42,  5.03it/s]

Reports:  63%|██████▎   | 4484/7111 [18:10<08:40,  5.04it/s]

Reports:  63%|██████▎   | 4485/7111 [18:10<08:31,  5.13it/s]

Reports:  63%|██████▎   | 4486/7111 [18:10<08:36,  5.09it/s]

Reports:  63%|██████▎   | 4487/7111 [18:10<08:31,  5.13it/s]

Reports:  63%|██████▎   | 4488/7111 [18:10<08:25,  5.19it/s]

Reports:  63%|██████▎   | 4489/7111 [18:11<08:26,  5.17it/s]

Reports:  63%|██████▎   | 4490/7111 [18:11<08:28,  5.15it/s]

Reports:  63%|██████▎   | 4491/7111 [18:11<08:31,  5.12it/s]

Reports:  63%|██████▎   | 4492/7111 [18:11<08:45,  4.98it/s]

Reports:  63%|██████▎   | 4493/7111 [18:11<08:43,  5.00it/s]

Reports:  63%|██████▎   | 4494/7111 [18:12<08:36,  5.07it/s]

Reports:  63%|██████▎   | 4495/7111 [18:12<08:42,  5.01it/s]

Reports:  63%|██████▎   | 4496/7111 [18:12<08:47,  4.96it/s]

Reports:  63%|██████▎   | 4497/7111 [18:12<08:37,  5.06it/s]

Reports:  63%|██████▎   | 4498/7111 [18:14<23:53,  1.82it/s]

Reports:  63%|██████▎   | 4499/7111 [18:14<19:20,  2.25it/s]

Reports:  63%|██████▎   | 4500/7111 [18:14<15:56,  2.73it/s]

Reports:  63%|██████▎   | 4501/7111 [18:14<14:03,  3.10it/s]

Reports:  63%|██████▎   | 4502/7111 [18:14<12:18,  3.53it/s]

Reports:  63%|██████▎   | 4503/7111 [18:15<11:04,  3.93it/s]

Reports:  63%|██████▎   | 4504/7111 [18:16<21:06,  2.06it/s]

Reports:  63%|██████▎   | 4505/7111 [18:16<17:16,  2.51it/s]

Reports:  63%|██████▎   | 4506/7111 [18:16<14:34,  2.98it/s]

Reports:  63%|██████▎   | 4507/7111 [18:16<12:45,  3.40it/s]

Reports:  63%|██████▎   | 4508/7111 [18:16<11:25,  3.79it/s]

Reports:  63%|██████▎   | 4509/7111 [18:17<10:40,  4.06it/s]

Reports:  63%|██████▎   | 4510/7111 [18:17<09:51,  4.39it/s]

Reports:  63%|██████▎   | 4511/7111 [18:17<09:36,  4.51it/s]

Reports:  63%|██████▎   | 4512/7111 [18:17<09:29,  4.56it/s]

Reports:  63%|██████▎   | 4513/7111 [18:17<09:04,  4.77it/s]

Reports:  63%|██████▎   | 4514/7111 [18:17<08:50,  4.90it/s]

Reports:  63%|██████▎   | 4515/7111 [18:18<08:43,  4.96it/s]

Reports:  64%|██████▎   | 4516/7111 [18:18<08:37,  5.01it/s]

Reports:  64%|██████▎   | 4517/7111 [18:18<08:22,  5.16it/s]

Reports:  64%|██████▎   | 4518/7111 [18:18<08:17,  5.21it/s]

Reports:  64%|██████▎   | 4519/7111 [18:18<08:19,  5.19it/s]

Reports:  64%|██████▎   | 4520/7111 [18:19<08:25,  5.13it/s]

Reports:  64%|██████▎   | 4521/7111 [18:19<08:29,  5.09it/s]

Reports:  64%|██████▎   | 4522/7111 [18:19<08:32,  5.05it/s]

Reports:  64%|██████▎   | 4523/7111 [18:19<08:20,  5.17it/s]

Reports:  64%|██████▎   | 4524/7111 [18:19<08:26,  5.11it/s]

Reports:  64%|██████▎   | 4525/7111 [18:20<08:27,  5.09it/s]

Reports:  64%|██████▎   | 4526/7111 [18:20<08:16,  5.20it/s]

Reports:  64%|██████▎   | 4527/7111 [18:20<08:15,  5.21it/s]

Reports:  64%|██████▎   | 4528/7111 [18:20<08:17,  5.20it/s]

Reports:  64%|██████▎   | 4529/7111 [18:21<18:07,  2.37it/s]

Reports:  64%|██████▎   | 4530/7111 [18:21<15:05,  2.85it/s]

Reports:  64%|██████▎   | 4531/7111 [18:22<13:03,  3.29it/s]

Reports:  64%|██████▎   | 4532/7111 [18:22<11:31,  3.73it/s]

Reports:  64%|██████▎   | 4533/7111 [18:22<10:25,  4.12it/s]

Reports:  64%|██████▍   | 4534/7111 [18:22<10:00,  4.29it/s]

Reports:  64%|██████▍   | 4535/7111 [18:22<09:40,  4.44it/s]

Reports:  64%|██████▍   | 4536/7111 [18:23<09:23,  4.57it/s]

Reports:  64%|██████▍   | 4537/7111 [18:23<08:57,  4.79it/s]

Reports:  64%|██████▍   | 4538/7111 [18:23<08:44,  4.90it/s]

Reports:  64%|██████▍   | 4539/7111 [18:23<08:46,  4.88it/s]

Reports:  64%|██████▍   | 4540/7111 [18:23<08:37,  4.97it/s]

Reports:  64%|██████▍   | 4541/7111 [18:23<08:29,  5.05it/s]

Reports:  64%|██████▍   | 4542/7111 [18:24<08:20,  5.13it/s]

Reports:  64%|██████▍   | 4543/7111 [18:24<08:24,  5.09it/s]

Reports:  64%|██████▍   | 4544/7111 [18:24<08:18,  5.15it/s]

Reports:  64%|██████▍   | 4545/7111 [18:24<08:11,  5.22it/s]

Reports:  64%|██████▍   | 4546/7111 [18:25<14:01,  3.05it/s]

Reports:  64%|██████▍   | 4547/7111 [18:25<12:20,  3.46it/s]

Reports:  64%|██████▍   | 4548/7111 [18:25<11:04,  3.86it/s]

Reports:  64%|██████▍   | 4549/7111 [18:25<10:17,  4.15it/s]

Reports:  64%|██████▍   | 4550/7111 [18:26<09:45,  4.38it/s]

Reports:  64%|██████▍   | 4551/7111 [18:26<09:17,  4.59it/s]

Reports:  64%|██████▍   | 4552/7111 [18:26<09:17,  4.59it/s]

Reports:  64%|██████▍   | 4553/7111 [18:26<08:56,  4.77it/s]

Reports:  64%|██████▍   | 4554/7111 [18:26<08:46,  4.85it/s]

Reports:  64%|██████▍   | 4555/7111 [18:27<17:05,  2.49it/s]

Reports:  64%|██████▍   | 4556/7111 [18:28<14:23,  2.96it/s]

Reports:  64%|██████▍   | 4557/7111 [18:28<12:30,  3.40it/s]

Reports:  64%|██████▍   | 4558/7111 [18:28<11:10,  3.81it/s]

Reports:  64%|██████▍   | 4559/7111 [18:28<10:23,  4.09it/s]

Reports:  64%|██████▍   | 4560/7111 [18:28<09:41,  4.39it/s]

Reports:  64%|██████▍   | 4561/7111 [18:29<09:20,  4.55it/s]

Reports:  64%|██████▍   | 4562/7111 [18:29<08:56,  4.75it/s]

Reports:  64%|██████▍   | 4563/7111 [18:29<08:42,  4.87it/s]

Reports:  64%|██████▍   | 4564/7111 [18:29<08:28,  5.01it/s]

Reports:  64%|██████▍   | 4565/7111 [18:29<08:46,  4.83it/s]

Reports:  64%|██████▍   | 4566/7111 [18:30<08:47,  4.83it/s]

Reports:  64%|██████▍   | 4567/7111 [18:30<08:42,  4.87it/s]

Reports:  64%|██████▍   | 4568/7111 [18:30<08:28,  5.00it/s]

Reports:  64%|██████▍   | 4569/7111 [18:30<08:35,  4.93it/s]

Reports:  64%|██████▍   | 4570/7111 [18:31<11:32,  3.67it/s]

Reports:  64%|██████▍   | 4571/7111 [18:31<16:07,  2.63it/s]

Reports:  64%|██████▍   | 4572/7111 [18:31<13:41,  3.09it/s]

Reports:  64%|██████▍   | 4573/7111 [18:32<12:09,  3.48it/s]

Reports:  64%|██████▍   | 4574/7111 [18:32<10:59,  3.85it/s]

Reports:  64%|██████▍   | 4575/7111 [18:32<10:14,  4.12it/s]

Reports:  64%|██████▍   | 4576/7111 [18:32<09:33,  4.42it/s]

Reports:  64%|██████▍   | 4577/7111 [18:32<10:45,  3.93it/s]

Reports:  64%|██████▍   | 4578/7111 [18:33<09:53,  4.27it/s]

Reports:  64%|██████▍   | 4579/7111 [18:33<09:29,  4.44it/s]

Reports:  64%|██████▍   | 4580/7111 [18:33<09:04,  4.65it/s]

Reports:  64%|██████▍   | 4581/7111 [18:33<08:52,  4.75it/s]

Reports:  64%|██████▍   | 4582/7111 [18:33<08:44,  4.82it/s]

Reports:  64%|██████▍   | 4583/7111 [18:34<08:32,  4.94it/s]

Reports:  64%|██████▍   | 4584/7111 [18:34<08:26,  4.99it/s]

Reports:  64%|██████▍   | 4585/7111 [18:34<08:35,  4.90it/s]

Reports:  64%|██████▍   | 4586/7111 [18:34<08:22,  5.02it/s]

Reports:  65%|██████▍   | 4587/7111 [18:34<08:24,  5.00it/s]

Reports:  65%|██████▍   | 4588/7111 [18:35<08:23,  5.02it/s]

Reports:  65%|██████▍   | 4589/7111 [18:35<08:15,  5.09it/s]

Reports:  65%|██████▍   | 4590/7111 [18:35<08:18,  5.05it/s]

Reports:  65%|██████▍   | 4591/7111 [18:35<08:18,  5.05it/s]

Reports:  65%|██████▍   | 4592/7111 [18:35<08:11,  5.13it/s]

Reports:  65%|██████▍   | 4593/7111 [18:36<08:17,  5.06it/s]

Reports:  65%|██████▍   | 4594/7111 [18:36<08:10,  5.13it/s]

Reports:  65%|██████▍   | 4595/7111 [18:36<08:07,  5.16it/s]

Reports:  65%|██████▍   | 4596/7111 [18:36<08:01,  5.22it/s]

Reports:  65%|██████▍   | 4597/7111 [18:36<08:04,  5.19it/s]

Reports:  65%|██████▍   | 4598/7111 [18:37<08:10,  5.12it/s]

Reports:  65%|██████▍   | 4599/7111 [18:37<08:08,  5.14it/s]

Reports:  65%|██████▍   | 4600/7111 [18:37<08:09,  5.13it/s]

Reports:  65%|██████▍   | 4601/7111 [18:37<08:01,  5.21it/s]

Reports:  65%|██████▍   | 4602/7111 [18:37<07:59,  5.23it/s]

Reports:  65%|██████▍   | 4603/7111 [18:38<07:58,  5.24it/s]

Reports:  65%|██████▍   | 4604/7111 [18:38<08:00,  5.22it/s]

Reports:  65%|██████▍   | 4605/7111 [18:38<12:39,  3.30it/s]

Reports:  65%|██████▍   | 4606/7111 [18:38<11:17,  3.70it/s]

Reports:  65%|██████▍   | 4607/7111 [18:39<10:26,  4.00it/s]

Reports:  65%|██████▍   | 4608/7111 [18:39<09:44,  4.28it/s]

Reports:  65%|██████▍   | 4609/7111 [18:39<09:08,  4.56it/s]

Reports:  65%|██████▍   | 4610/7111 [18:39<08:49,  4.73it/s]

Reports:  65%|██████▍   | 4611/7111 [18:39<08:33,  4.87it/s]

Reports:  65%|██████▍   | 4612/7111 [18:40<08:30,  4.89it/s]

Reports:  65%|██████▍   | 4613/7111 [18:40<08:19,  5.00it/s]

Reports:  65%|██████▍   | 4614/7111 [18:40<08:22,  4.97it/s]

Reports:  65%|██████▍   | 4615/7111 [18:40<08:31,  4.88it/s]

Reports:  65%|██████▍   | 4616/7111 [18:40<08:25,  4.94it/s]

Reports:  65%|██████▍   | 4617/7111 [18:41<08:26,  4.92it/s]

Reports:  65%|██████▍   | 4618/7111 [18:41<08:27,  4.91it/s]

Reports:  65%|██████▍   | 4619/7111 [18:41<08:37,  4.81it/s]

Reports:  65%|██████▍   | 4620/7111 [18:41<08:32,  4.86it/s]

Reports:  65%|██████▍   | 4621/7111 [18:41<08:15,  5.02it/s]

Reports:  65%|██████▍   | 4622/7111 [18:42<08:25,  4.92it/s]

Reports:  65%|██████▌   | 4623/7111 [18:42<08:28,  4.90it/s]

Reports:  65%|██████▌   | 4624/7111 [18:42<08:25,  4.92it/s]

Reports:  65%|██████▌   | 4625/7111 [18:42<08:08,  5.09it/s]

Reports:  65%|██████▌   | 4626/7111 [18:42<08:26,  4.91it/s]

Reports:  65%|██████▌   | 4627/7111 [18:44<19:51,  2.09it/s]

Reports:  65%|██████▌   | 4628/7111 [18:44<16:16,  2.54it/s]

Reports:  65%|██████▌   | 4629/7111 [18:44<13:56,  2.97it/s]

Reports:  65%|██████▌   | 4630/7111 [18:44<12:09,  3.40it/s]

Reports:  65%|██████▌   | 4631/7111 [18:44<10:54,  3.79it/s]

Reports:  65%|██████▌   | 4632/7111 [18:45<09:54,  4.17it/s]

Reports:  65%|██████▌   | 4633/7111 [18:45<09:18,  4.44it/s]

Reports:  65%|██████▌   | 4634/7111 [18:45<08:52,  4.66it/s]

Reports:  65%|██████▌   | 4635/7111 [18:45<08:28,  4.87it/s]

Reports:  65%|██████▌   | 4636/7111 [18:45<08:12,  5.02it/s]

Reports:  65%|██████▌   | 4637/7111 [18:46<08:14,  5.00it/s]

Reports:  65%|██████▌   | 4638/7111 [18:46<08:20,  4.94it/s]

Reports:  65%|██████▌   | 4639/7111 [18:46<08:15,  4.99it/s]

Reports:  65%|██████▌   | 4640/7111 [18:46<08:04,  5.10it/s]

Reports:  65%|██████▌   | 4641/7111 [18:46<08:07,  5.07it/s]

Reports:  65%|██████▌   | 4642/7111 [18:47<09:56,  4.14it/s]

Reports:  65%|██████▌   | 4643/7111 [18:47<09:35,  4.29it/s]

Reports:  65%|██████▌   | 4644/7111 [18:47<09:12,  4.46it/s]

Reports:  65%|██████▌   | 4645/7111 [18:47<08:50,  4.65it/s]

Reports:  65%|██████▌   | 4646/7111 [18:47<08:35,  4.79it/s]

Reports:  65%|██████▌   | 4647/7111 [18:48<08:23,  4.89it/s]

Reports:  65%|██████▌   | 4648/7111 [18:48<08:30,  4.82it/s]

Reports:  65%|██████▌   | 4649/7111 [18:48<08:19,  4.93it/s]

Reports:  65%|██████▌   | 4650/7111 [18:48<08:19,  4.93it/s]

Reports:  65%|██████▌   | 4651/7111 [18:48<08:15,  4.97it/s]

Reports:  65%|██████▌   | 4652/7111 [18:49<08:21,  4.91it/s]

Reports:  65%|██████▌   | 4653/7111 [18:49<08:20,  4.91it/s]

Reports:  65%|██████▌   | 4654/7111 [18:49<08:33,  4.78it/s]

Reports:  65%|██████▌   | 4655/7111 [18:49<08:13,  4.98it/s]

Reports:  65%|██████▌   | 4656/7111 [18:49<08:11,  4.99it/s]

Reports:  65%|██████▌   | 4657/7111 [18:50<08:01,  5.09it/s]

Reports:  66%|██████▌   | 4658/7111 [18:50<08:14,  4.96it/s]

Reports:  66%|██████▌   | 4659/7111 [18:50<08:25,  4.85it/s]

Reports:  66%|██████▌   | 4660/7111 [18:50<08:13,  4.96it/s]

Reports:  66%|██████▌   | 4661/7111 [18:50<08:06,  5.03it/s]

Reports:  66%|██████▌   | 4662/7111 [18:51<08:06,  5.04it/s]

Reports:  66%|██████▌   | 4663/7111 [18:51<07:52,  5.18it/s]

Reports:  66%|██████▌   | 4664/7111 [18:51<07:54,  5.16it/s]

Reports:  66%|██████▌   | 4665/7111 [18:51<07:54,  5.15it/s]

Reports:  66%|██████▌   | 4666/7111 [18:51<07:52,  5.18it/s]

Reports:  66%|██████▌   | 4667/7111 [18:52<07:59,  5.10it/s]

Reports:  66%|██████▌   | 4668/7111 [18:52<07:52,  5.17it/s]

Reports:  66%|██████▌   | 4669/7111 [18:52<07:47,  5.22it/s]

Reports:  66%|██████▌   | 4670/7111 [18:52<07:44,  5.26it/s]

Reports:  66%|██████▌   | 4671/7111 [18:52<07:42,  5.28it/s]

Reports:  66%|██████▌   | 4672/7111 [18:53<07:45,  5.24it/s]

Reports:  66%|██████▌   | 4673/7111 [18:53<07:39,  5.31it/s]

Reports:  66%|██████▌   | 4674/7111 [18:53<07:40,  5.29it/s]

Reports:  66%|██████▌   | 4675/7111 [18:53<07:41,  5.28it/s]

Reports:  66%|██████▌   | 4676/7111 [18:53<07:51,  5.17it/s]

Reports:  66%|██████▌   | 4677/7111 [18:54<07:46,  5.22it/s]

Reports:  66%|██████▌   | 4678/7111 [18:54<07:44,  5.24it/s]

Reports:  66%|██████▌   | 4679/7111 [18:54<07:36,  5.33it/s]

Reports:  66%|██████▌   | 4680/7111 [18:54<07:41,  5.27it/s]

Reports:  66%|██████▌   | 4681/7111 [18:54<07:46,  5.20it/s]

Reports:  66%|██████▌   | 4682/7111 [18:55<07:54,  5.12it/s]

Reports:  66%|██████▌   | 4683/7111 [18:55<07:50,  5.16it/s]

Reports:  66%|██████▌   | 4684/7111 [18:55<07:51,  5.15it/s]

Reports:  66%|██████▌   | 4685/7111 [18:55<07:56,  5.09it/s]

Reports:  66%|██████▌   | 4686/7111 [18:55<07:58,  5.07it/s]

Reports:  66%|██████▌   | 4687/7111 [18:55<07:50,  5.15it/s]

Reports:  66%|██████▌   | 4688/7111 [18:56<07:51,  5.14it/s]

Reports:  66%|██████▌   | 4689/7111 [18:56<07:45,  5.20it/s]

Reports:  66%|██████▌   | 4690/7111 [18:56<07:42,  5.23it/s]

Reports:  66%|██████▌   | 4691/7111 [18:56<07:52,  5.12it/s]

Reports:  66%|██████▌   | 4692/7111 [18:56<07:50,  5.14it/s]

Reports:  66%|██████▌   | 4693/7111 [18:57<07:47,  5.17it/s]

Reports:  66%|██████▌   | 4694/7111 [18:57<07:43,  5.21it/s]

Reports:  66%|██████▌   | 4695/7111 [18:57<07:46,  5.18it/s]

Reports:  66%|██████▌   | 4696/7111 [18:57<07:45,  5.19it/s]

Reports:  66%|██████▌   | 4697/7111 [18:57<07:42,  5.22it/s]

Reports:  66%|██████▌   | 4698/7111 [18:58<07:52,  5.11it/s]

Reports:  66%|██████▌   | 4699/7111 [18:58<07:47,  5.16it/s]

Reports:  66%|██████▌   | 4700/7111 [18:58<07:45,  5.18it/s]

Reports:  66%|██████▌   | 4701/7111 [18:58<07:57,  5.05it/s]

Reports:  66%|██████▌   | 4702/7111 [18:58<07:58,  5.03it/s]

Reports:  66%|██████▌   | 4703/7111 [18:59<07:57,  5.04it/s]

Reports:  66%|██████▌   | 4704/7111 [18:59<08:01,  5.00it/s]

Reports:  66%|██████▌   | 4705/7111 [18:59<07:52,  5.09it/s]

Reports:  66%|██████▌   | 4706/7111 [18:59<07:49,  5.12it/s]

Reports:  66%|██████▌   | 4707/7111 [18:59<07:43,  5.19it/s]

Reports:  66%|██████▌   | 4708/7111 [19:00<07:37,  5.25it/s]

Reports:  66%|██████▌   | 4709/7111 [19:00<07:36,  5.27it/s]

Reports:  66%|██████▌   | 4710/7111 [19:00<07:32,  5.30it/s]

Reports:  66%|██████▌   | 4711/7111 [19:00<07:30,  5.33it/s]

Reports:  66%|██████▋   | 4712/7111 [19:00<07:33,  5.30it/s]

Reports:  66%|██████▋   | 4713/7111 [19:01<07:28,  5.35it/s]

Reports:  66%|██████▋   | 4714/7111 [19:01<07:26,  5.37it/s]

Reports:  66%|██████▋   | 4715/7111 [19:01<07:30,  5.32it/s]

Reports:  66%|██████▋   | 4716/7111 [19:01<07:30,  5.31it/s]

Reports:  66%|██████▋   | 4717/7111 [19:01<07:27,  5.35it/s]

Reports:  66%|██████▋   | 4718/7111 [19:01<07:39,  5.21it/s]

Reports:  66%|██████▋   | 4719/7111 [19:02<07:39,  5.20it/s]

Reports:  66%|██████▋   | 4720/7111 [19:02<07:43,  5.16it/s]

Reports:  66%|██████▋   | 4721/7111 [19:02<07:48,  5.10it/s]

Reports:  66%|██████▋   | 4722/7111 [19:02<07:47,  5.11it/s]

Reports:  66%|██████▋   | 4723/7111 [19:02<07:42,  5.17it/s]

Reports:  66%|██████▋   | 4724/7111 [19:03<07:44,  5.14it/s]

Reports:  66%|██████▋   | 4725/7111 [19:03<07:48,  5.09it/s]

Reports:  66%|██████▋   | 4726/7111 [19:03<07:43,  5.15it/s]

Reports:  66%|██████▋   | 4727/7111 [19:03<07:44,  5.14it/s]

Reports:  66%|██████▋   | 4728/7111 [19:03<07:41,  5.16it/s]

Reports:  67%|██████▋   | 4729/7111 [19:04<07:50,  5.07it/s]

Reports:  67%|██████▋   | 4730/7111 [19:04<07:46,  5.10it/s]

Reports:  67%|██████▋   | 4731/7111 [19:04<07:49,  5.06it/s]

Reports:  67%|██████▋   | 4732/7111 [19:04<07:43,  5.13it/s]

Reports:  67%|██████▋   | 4733/7111 [19:04<07:52,  5.03it/s]

Reports:  67%|██████▋   | 4734/7111 [19:05<08:04,  4.91it/s]

Reports:  67%|██████▋   | 4735/7111 [19:05<07:53,  5.02it/s]

Reports:  67%|██████▋   | 4736/7111 [19:05<07:57,  4.98it/s]

Reports:  67%|██████▋   | 4737/7111 [19:05<07:50,  5.04it/s]

Reports:  67%|██████▋   | 4738/7111 [19:06<13:45,  2.88it/s]

Reports:  67%|██████▋   | 4739/7111 [19:06<12:04,  3.27it/s]

Reports:  67%|██████▋   | 4740/7111 [19:06<10:49,  3.65it/s]

Reports:  67%|██████▋   | 4741/7111 [19:06<09:49,  4.02it/s]

Reports:  67%|██████▋   | 4742/7111 [19:07<09:09,  4.31it/s]

Reports:  67%|██████▋   | 4743/7111 [19:07<08:45,  4.51it/s]

Reports:  67%|██████▋   | 4744/7111 [19:07<08:21,  4.72it/s]

Reports:  67%|██████▋   | 4745/7111 [19:07<08:07,  4.86it/s]

Reports:  67%|██████▋   | 4746/7111 [19:07<08:09,  4.83it/s]

Reports:  67%|██████▋   | 4747/7111 [19:08<07:55,  4.97it/s]

Reports:  67%|██████▋   | 4748/7111 [19:08<07:50,  5.02it/s]

Reports:  67%|██████▋   | 4749/7111 [19:08<07:43,  5.10it/s]

Reports:  67%|██████▋   | 4750/7111 [19:08<07:45,  5.07it/s]

Reports:  67%|██████▋   | 4751/7111 [19:08<07:37,  5.15it/s]

Reports:  67%|██████▋   | 4752/7111 [19:09<07:42,  5.10it/s]

Reports:  67%|██████▋   | 4753/7111 [19:09<07:35,  5.17it/s]

Reports:  67%|██████▋   | 4754/7111 [19:09<07:31,  5.22it/s]

Reports:  67%|██████▋   | 4755/7111 [19:09<07:34,  5.18it/s]

Reports:  67%|██████▋   | 4756/7111 [19:09<07:31,  5.21it/s]

Reports:  67%|██████▋   | 4757/7111 [19:10<07:31,  5.21it/s]

Reports:  67%|██████▋   | 4758/7111 [19:10<07:29,  5.23it/s]

Reports:  67%|██████▋   | 4759/7111 [19:10<07:42,  5.09it/s]

Reports:  67%|██████▋   | 4760/7111 [19:10<07:52,  4.98it/s]

Reports:  67%|██████▋   | 4761/7111 [19:10<07:56,  4.93it/s]

Reports:  67%|██████▋   | 4762/7111 [19:11<08:00,  4.89it/s]

Reports:  67%|██████▋   | 4763/7111 [19:11<07:52,  4.97it/s]

Reports:  67%|██████▋   | 4764/7111 [19:11<07:55,  4.93it/s]

Reports:  67%|██████▋   | 4765/7111 [19:11<07:43,  5.06it/s]

Reports:  67%|██████▋   | 4766/7111 [19:11<07:40,  5.09it/s]

Reports:  67%|██████▋   | 4767/7111 [19:12<07:32,  5.18it/s]

Reports:  67%|██████▋   | 4768/7111 [19:12<07:39,  5.10it/s]

Reports:  67%|██████▋   | 4769/7111 [19:12<07:40,  5.08it/s]

Reports:  67%|██████▋   | 4770/7111 [19:12<07:47,  5.01it/s]

Reports:  67%|██████▋   | 4771/7111 [19:12<07:49,  4.98it/s]

Reports:  67%|██████▋   | 4772/7111 [19:13<07:47,  5.00it/s]

Reports:  67%|██████▋   | 4773/7111 [19:13<07:45,  5.03it/s]

Reports:  67%|██████▋   | 4774/7111 [19:13<07:41,  5.06it/s]

Reports:  67%|██████▋   | 4775/7111 [19:13<07:35,  5.13it/s]

Reports:  67%|██████▋   | 4776/7111 [19:13<07:37,  5.11it/s]

Reports:  67%|██████▋   | 4777/7111 [19:14<07:35,  5.12it/s]

Reports:  67%|██████▋   | 4778/7111 [19:14<07:45,  5.01it/s]

Reports:  67%|██████▋   | 4779/7111 [19:14<07:48,  4.97it/s]

Reports:  67%|██████▋   | 4780/7111 [19:14<07:42,  5.04it/s]

Reports:  67%|██████▋   | 4781/7111 [19:14<07:41,  5.05it/s]

Reports:  67%|██████▋   | 4782/7111 [19:15<07:50,  4.95it/s]

Reports:  67%|██████▋   | 4783/7111 [19:15<07:51,  4.93it/s]

Reports:  67%|██████▋   | 4784/7111 [19:15<13:28,  2.88it/s]

Reports:  67%|██████▋   | 4785/7111 [19:16<11:35,  3.35it/s]

Reports:  67%|██████▋   | 4786/7111 [19:16<10:22,  3.73it/s]

Reports:  67%|██████▋   | 4787/7111 [19:16<09:27,  4.09it/s]

Reports:  67%|██████▋   | 4788/7111 [19:16<09:07,  4.24it/s]

Reports:  67%|██████▋   | 4789/7111 [19:16<08:46,  4.41it/s]

Reports:  67%|██████▋   | 4790/7111 [19:17<08:33,  4.52it/s]

Reports:  67%|██████▋   | 4791/7111 [19:17<08:13,  4.71it/s]

Reports:  67%|██████▋   | 4792/7111 [19:17<07:54,  4.89it/s]

Reports:  67%|██████▋   | 4793/7111 [19:17<07:49,  4.94it/s]

Reports:  67%|██████▋   | 4794/7111 [19:17<07:40,  5.03it/s]

Reports:  67%|██████▋   | 4795/7111 [19:18<07:37,  5.06it/s]

Reports:  67%|██████▋   | 4796/7111 [19:18<07:44,  4.99it/s]

Reports:  67%|██████▋   | 4797/7111 [19:18<07:34,  5.09it/s]

Reports:  67%|██████▋   | 4798/7111 [19:18<07:37,  5.06it/s]

Reports:  67%|██████▋   | 4799/7111 [19:18<07:29,  5.14it/s]

Reports:  68%|██████▊   | 4800/7111 [19:19<07:32,  5.10it/s]

Reports:  68%|██████▊   | 4801/7111 [19:19<07:30,  5.13it/s]

Reports:  68%|██████▊   | 4802/7111 [19:19<07:22,  5.22it/s]

Reports:  68%|██████▊   | 4803/7111 [19:19<07:18,  5.26it/s]

Reports:  68%|██████▊   | 4804/7111 [19:19<07:19,  5.25it/s]

Reports:  68%|██████▊   | 4805/7111 [19:20<07:20,  5.23it/s]

Reports:  68%|██████▊   | 4806/7111 [19:20<07:36,  5.05it/s]

Reports:  68%|██████▊   | 4807/7111 [19:20<10:16,  3.74it/s]

Reports:  68%|██████▊   | 4808/7111 [19:20<09:29,  4.04it/s]

Reports:  68%|██████▊   | 4809/7111 [19:21<08:47,  4.36it/s]

Reports:  68%|██████▊   | 4810/7111 [19:21<08:17,  4.63it/s]

Reports:  68%|██████▊   | 4811/7111 [19:21<08:05,  4.74it/s]

Reports:  68%|██████▊   | 4812/7111 [19:21<07:49,  4.90it/s]

Reports:  68%|██████▊   | 4813/7111 [19:21<07:45,  4.93it/s]

Reports:  68%|██████▊   | 4814/7111 [19:22<07:34,  5.05it/s]

Reports:  68%|██████▊   | 4815/7111 [19:22<07:35,  5.04it/s]

Reports:  68%|██████▊   | 4816/7111 [19:22<07:29,  5.10it/s]

Reports:  68%|██████▊   | 4817/7111 [19:22<07:34,  5.04it/s]

Reports:  68%|██████▊   | 4818/7111 [19:22<07:37,  5.01it/s]

Reports:  68%|██████▊   | 4819/7111 [19:23<07:42,  4.96it/s]

Reports:  68%|██████▊   | 4820/7111 [19:23<07:42,  4.95it/s]

Reports:  68%|██████▊   | 4821/7111 [19:23<07:45,  4.91it/s]

Reports:  68%|██████▊   | 4822/7111 [19:23<07:43,  4.94it/s]

Reports:  68%|██████▊   | 4823/7111 [19:23<07:31,  5.07it/s]

Reports:  68%|██████▊   | 4824/7111 [19:24<07:25,  5.13it/s]

Reports:  68%|██████▊   | 4825/7111 [19:24<07:29,  5.08it/s]

Reports:  68%|██████▊   | 4826/7111 [19:24<07:32,  5.05it/s]

Reports:  68%|██████▊   | 4827/7111 [19:24<07:44,  4.92it/s]

Reports:  68%|██████▊   | 4828/7111 [19:24<07:42,  4.94it/s]

Reports:  68%|██████▊   | 4829/7111 [19:25<07:30,  5.06it/s]

Reports:  68%|██████▊   | 4830/7111 [19:25<07:25,  5.12it/s]

Reports:  68%|██████▊   | 4831/7111 [19:25<07:28,  5.08it/s]

Reports:  68%|██████▊   | 4832/7111 [19:25<07:32,  5.04it/s]

Reports:  68%|██████▊   | 4833/7111 [19:25<07:25,  5.12it/s]

Reports:  68%|██████▊   | 4834/7111 [19:26<07:23,  5.13it/s]

Reports:  68%|██████▊   | 4835/7111 [19:26<07:25,  5.11it/s]

Reports:  68%|██████▊   | 4836/7111 [19:26<07:23,  5.13it/s]

Reports:  68%|██████▊   | 4837/7111 [19:26<07:32,  5.03it/s]

Reports:  68%|██████▊   | 4838/7111 [19:26<07:42,  4.92it/s]

Reports:  68%|██████▊   | 4839/7111 [19:27<07:36,  4.98it/s]

Reports:  68%|██████▊   | 4840/7111 [19:27<07:29,  5.06it/s]

Reports:  68%|██████▊   | 4841/7111 [19:27<07:31,  5.03it/s]

Reports:  68%|██████▊   | 4842/7111 [19:27<07:43,  4.90it/s]

Reports:  68%|██████▊   | 4843/7111 [19:27<07:35,  4.98it/s]

Reports:  68%|██████▊   | 4844/7111 [19:28<07:28,  5.06it/s]

Reports:  68%|██████▊   | 4845/7111 [19:28<07:30,  5.03it/s]

Reports:  68%|██████▊   | 4846/7111 [19:28<07:29,  5.04it/s]

Reports:  68%|██████▊   | 4847/7111 [19:28<07:35,  4.97it/s]

Reports:  68%|██████▊   | 4848/7111 [19:28<07:42,  4.89it/s]

Reports:  68%|██████▊   | 4849/7111 [19:29<07:46,  4.85it/s]

Reports:  68%|██████▊   | 4850/7111 [19:29<07:44,  4.87it/s]

Reports:  68%|██████▊   | 4851/7111 [19:29<07:37,  4.94it/s]

Reports:  68%|██████▊   | 4852/7111 [19:29<07:40,  4.90it/s]

Reports:  68%|██████▊   | 4853/7111 [19:29<07:32,  4.99it/s]

Reports:  68%|██████▊   | 4854/7111 [19:30<07:36,  4.94it/s]

Reports:  68%|██████▊   | 4855/7111 [19:30<07:31,  4.99it/s]

Reports:  68%|██████▊   | 4856/7111 [19:30<07:33,  4.97it/s]

Reports:  68%|██████▊   | 4857/7111 [19:30<07:36,  4.94it/s]

Reports:  68%|██████▊   | 4858/7111 [19:30<07:28,  5.03it/s]

Reports:  68%|██████▊   | 4859/7111 [19:31<07:42,  4.87it/s]

Reports:  68%|██████▊   | 4860/7111 [19:31<07:39,  4.90it/s]

Reports:  68%|██████▊   | 4861/7111 [19:31<07:27,  5.03it/s]

Reports:  68%|██████▊   | 4862/7111 [19:31<07:19,  5.12it/s]

Reports:  68%|██████▊   | 4863/7111 [19:31<07:30,  4.99it/s]

Reports:  68%|██████▊   | 4864/7111 [19:32<07:21,  5.09it/s]

Reports:  68%|██████▊   | 4865/7111 [19:32<07:34,  4.94it/s]

Reports:  68%|██████▊   | 4866/7111 [19:32<12:59,  2.88it/s]

Reports:  68%|██████▊   | 4867/7111 [19:33<11:17,  3.31it/s]

Reports:  68%|██████▊   | 4868/7111 [19:33<10:00,  3.73it/s]

Reports:  68%|██████▊   | 4869/7111 [19:33<09:13,  4.05it/s]

Reports:  68%|██████▊   | 4870/7111 [19:33<08:42,  4.29it/s]

Reports:  68%|██████▊   | 4871/7111 [19:33<08:19,  4.48it/s]

Reports:  69%|██████▊   | 4872/7111 [19:34<08:08,  4.58it/s]

Reports:  69%|██████▊   | 4873/7111 [19:34<07:50,  4.76it/s]

Reports:  69%|██████▊   | 4874/7111 [19:34<07:33,  4.93it/s]

Reports:  69%|██████▊   | 4875/7111 [19:34<07:41,  4.84it/s]

Reports:  69%|██████▊   | 4876/7111 [19:34<07:34,  4.92it/s]

Reports:  69%|██████▊   | 4877/7111 [19:35<07:30,  4.96it/s]

Reports:  69%|██████▊   | 4878/7111 [19:35<07:27,  4.99it/s]

Reports:  69%|██████▊   | 4879/7111 [19:35<07:23,  5.03it/s]

Reports:  69%|██████▊   | 4880/7111 [19:35<07:19,  5.08it/s]

Reports:  69%|██████▊   | 4881/7111 [19:35<07:13,  5.14it/s]

Reports:  69%|██████▊   | 4882/7111 [19:36<07:10,  5.18it/s]

Reports:  69%|██████▊   | 4883/7111 [19:36<07:06,  5.23it/s]

Reports:  69%|██████▊   | 4884/7111 [19:36<07:08,  5.20it/s]

Reports:  69%|██████▊   | 4885/7111 [19:36<07:05,  5.23it/s]

Reports:  69%|██████▊   | 4886/7111 [19:36<07:01,  5.28it/s]

Reports:  69%|██████▊   | 4887/7111 [19:37<07:01,  5.28it/s]

Reports:  69%|██████▊   | 4888/7111 [19:37<07:04,  5.24it/s]

Reports:  69%|██████▉   | 4889/7111 [19:37<07:09,  5.18it/s]

Reports:  69%|██████▉   | 4890/7111 [19:37<07:15,  5.10it/s]

Reports:  69%|██████▉   | 4891/7111 [19:37<07:14,  5.11it/s]

Reports:  69%|██████▉   | 4892/7111 [19:38<07:10,  5.15it/s]

Reports:  69%|██████▉   | 4893/7111 [19:38<07:06,  5.20it/s]

Reports:  69%|██████▉   | 4894/7111 [19:38<07:04,  5.22it/s]

Reports:  69%|██████▉   | 4895/7111 [19:38<07:00,  5.26it/s]

Reports:  69%|██████▉   | 4896/7111 [19:38<07:03,  5.24it/s]

Reports:  69%|██████▉   | 4897/7111 [19:39<11:05,  3.33it/s]

Reports:  69%|██████▉   | 4898/7111 [19:39<11:05,  3.33it/s]

Reports:  69%|██████▉   | 4899/7111 [19:39<09:48,  3.76it/s]

Reports:  69%|██████▉   | 4900/7111 [19:39<08:56,  4.12it/s]

Reports:  69%|██████▉   | 4901/7111 [19:40<08:20,  4.41it/s]

Reports:  69%|██████▉   | 4902/7111 [19:40<08:05,  4.55it/s]

Reports:  69%|██████▉   | 4903/7111 [19:40<07:45,  4.75it/s]

Reports:  69%|██████▉   | 4904/7111 [19:40<07:33,  4.86it/s]

Reports:  69%|██████▉   | 4905/7111 [19:40<07:32,  4.88it/s]

Reports:  69%|██████▉   | 4906/7111 [19:41<07:25,  4.95it/s]

Reports:  69%|██████▉   | 4907/7111 [19:41<07:17,  5.04it/s]

Reports:  69%|██████▉   | 4908/7111 [19:41<07:08,  5.14it/s]

Reports:  69%|██████▉   | 4909/7111 [19:41<07:53,  4.65it/s]

Reports:  69%|██████▉   | 4910/7111 [19:42<07:50,  4.67it/s]

Reports:  69%|██████▉   | 4911/7111 [19:42<07:45,  4.73it/s]

Reports:  69%|██████▉   | 4912/7111 [19:42<07:40,  4.78it/s]

Reports:  69%|██████▉   | 4913/7111 [19:42<07:31,  4.87it/s]

Reports:  69%|██████▉   | 4914/7111 [19:42<07:20,  4.99it/s]

Reports:  69%|██████▉   | 4915/7111 [19:43<07:22,  4.97it/s]

Reports:  69%|██████▉   | 4916/7111 [19:43<07:20,  4.99it/s]

Reports:  69%|██████▉   | 4917/7111 [19:43<07:27,  4.91it/s]

Reports:  69%|██████▉   | 4918/7111 [19:43<07:27,  4.90it/s]

Reports:  69%|██████▉   | 4919/7111 [19:43<07:19,  4.99it/s]

Reports:  69%|██████▉   | 4920/7111 [19:44<07:19,  4.98it/s]

Reports:  69%|██████▉   | 4921/7111 [19:44<07:13,  5.05it/s]

Reports:  69%|██████▉   | 4922/7111 [19:44<07:22,  4.95it/s]

Reports:  69%|██████▉   | 4923/7111 [19:44<07:58,  4.58it/s]

Reports:  69%|██████▉   | 4924/7111 [19:44<07:49,  4.66it/s]

Reports:  69%|██████▉   | 4925/7111 [19:45<07:41,  4.73it/s]

Reports:  69%|██████▉   | 4926/7111 [19:45<07:41,  4.73it/s]

Reports:  69%|██████▉   | 4927/7111 [19:45<07:26,  4.89it/s]

Reports:  69%|██████▉   | 4928/7111 [19:45<07:17,  4.99it/s]

Reports:  69%|██████▉   | 4929/7111 [19:45<07:48,  4.66it/s]

Reports:  69%|██████▉   | 4930/7111 [19:46<07:32,  4.82it/s]

Reports:  69%|██████▉   | 4931/7111 [19:46<07:43,  4.70it/s]

Reports:  69%|██████▉   | 4932/7111 [19:46<07:29,  4.85it/s]

Reports:  69%|██████▉   | 4933/7111 [19:46<07:13,  5.02it/s]

Reports:  69%|██████▉   | 4934/7111 [19:46<07:14,  5.02it/s]

Reports:  69%|██████▉   | 4935/7111 [19:47<07:12,  5.03it/s]

Reports:  69%|██████▉   | 4936/7111 [19:47<07:05,  5.11it/s]

Reports:  69%|██████▉   | 4937/7111 [19:47<07:08,  5.07it/s]

Reports:  69%|██████▉   | 4938/7111 [19:47<07:08,  5.07it/s]

Reports:  69%|██████▉   | 4939/7111 [19:47<07:02,  5.14it/s]

Reports:  69%|██████▉   | 4940/7111 [19:48<07:00,  5.17it/s]

Reports:  69%|██████▉   | 4941/7111 [19:48<07:01,  5.15it/s]

Reports:  69%|██████▉   | 4942/7111 [19:48<07:08,  5.06it/s]

Reports:  70%|██████▉   | 4943/7111 [19:48<07:05,  5.09it/s]

Reports:  70%|██████▉   | 4944/7111 [19:48<07:01,  5.14it/s]

Reports:  70%|██████▉   | 4945/7111 [19:49<06:55,  5.21it/s]

Reports:  70%|██████▉   | 4946/7111 [19:49<06:58,  5.18it/s]

Reports:  70%|██████▉   | 4947/7111 [19:49<06:53,  5.24it/s]

Reports:  70%|██████▉   | 4948/7111 [19:49<06:56,  5.19it/s]

Reports:  70%|██████▉   | 4949/7111 [19:49<06:57,  5.17it/s]

Reports:  70%|██████▉   | 4950/7111 [19:50<07:05,  5.08it/s]

Reports:  70%|██████▉   | 4951/7111 [19:50<07:04,  5.09it/s]

Reports:  70%|██████▉   | 4952/7111 [19:50<07:01,  5.12it/s]

Reports:  70%|██████▉   | 4953/7111 [19:50<07:04,  5.09it/s]

Reports:  70%|██████▉   | 4954/7111 [19:50<07:05,  5.07it/s]

Reports:  70%|██████▉   | 4955/7111 [19:51<07:16,  4.94it/s]

Reports:  70%|██████▉   | 4956/7111 [19:51<07:06,  5.05it/s]

Reports:  70%|██████▉   | 4957/7111 [19:51<07:02,  5.09it/s]

Reports:  70%|██████▉   | 4958/7111 [19:51<07:10,  5.01it/s]

Reports:  70%|██████▉   | 4959/7111 [19:51<07:09,  5.02it/s]

Reports:  70%|██████▉   | 4960/7111 [19:52<07:19,  4.89it/s]

Reports:  70%|██████▉   | 4961/7111 [19:52<07:10,  5.00it/s]

Reports:  70%|██████▉   | 4962/7111 [19:52<07:06,  5.03it/s]

Reports:  70%|██████▉   | 4963/7111 [19:52<07:12,  4.96it/s]

Reports:  70%|██████▉   | 4964/7111 [19:52<07:03,  5.07it/s]

Reports:  70%|██████▉   | 4965/7111 [19:53<07:01,  5.09it/s]

Reports:  70%|██████▉   | 4966/7111 [19:53<06:57,  5.14it/s]

Reports:  70%|██████▉   | 4967/7111 [19:53<06:51,  5.21it/s]

Reports:  70%|██████▉   | 4968/7111 [19:53<06:45,  5.28it/s]

Reports:  70%|██████▉   | 4969/7111 [19:53<06:45,  5.28it/s]

Reports:  70%|██████▉   | 4970/7111 [19:53<06:46,  5.26it/s]

Reports:  70%|██████▉   | 4971/7111 [19:54<06:43,  5.30it/s]

Reports:  70%|██████▉   | 4972/7111 [19:54<08:49,  4.04it/s]

Reports:  70%|██████▉   | 4973/7111 [19:54<08:10,  4.36it/s]

Reports:  70%|██████▉   | 4974/7111 [19:54<07:57,  4.48it/s]

Reports:  70%|██████▉   | 4975/7111 [19:55<07:42,  4.62it/s]

Reports:  70%|██████▉   | 4976/7111 [19:55<07:22,  4.82it/s]

Reports:  70%|██████▉   | 4977/7111 [19:55<07:08,  4.97it/s]

Reports:  70%|███████   | 4978/7111 [19:55<07:15,  4.90it/s]

Reports:  70%|███████   | 4979/7111 [19:55<07:03,  5.03it/s]

Reports:  70%|███████   | 4980/7111 [19:56<07:00,  5.07it/s]

Reports:  70%|███████   | 4981/7111 [19:56<06:59,  5.08it/s]

Reports:  70%|███████   | 4982/7111 [19:56<06:54,  5.14it/s]

Reports:  70%|███████   | 4983/7111 [19:56<06:48,  5.20it/s]

Reports:  70%|███████   | 4984/7111 [19:56<06:47,  5.22it/s]

Reports:  70%|███████   | 4985/7111 [19:57<06:52,  5.16it/s]

Reports:  70%|███████   | 4986/7111 [19:57<06:46,  5.22it/s]

Reports:  70%|███████   | 4987/7111 [19:57<06:49,  5.19it/s]

Reports:  70%|███████   | 4988/7111 [19:57<06:55,  5.10it/s]

Reports:  70%|███████   | 4989/7111 [19:57<06:50,  5.17it/s]

Reports:  70%|███████   | 4990/7111 [19:58<06:55,  5.11it/s]

Reports:  70%|███████   | 4991/7111 [19:58<06:48,  5.18it/s]

Reports:  70%|███████   | 4992/7111 [19:58<06:50,  5.16it/s]

Reports:  70%|███████   | 4993/7111 [19:58<06:49,  5.18it/s]

Reports:  70%|███████   | 4994/7111 [19:58<06:54,  5.11it/s]

Reports:  70%|███████   | 4995/7111 [19:58<06:46,  5.21it/s]

Reports:  70%|███████   | 4996/7111 [19:59<06:42,  5.25it/s]

Reports:  70%|███████   | 4997/7111 [19:59<06:46,  5.20it/s]

Reports:  70%|███████   | 4998/7111 [19:59<06:56,  5.07it/s]

Reports:  70%|███████   | 4999/7111 [19:59<06:50,  5.14it/s]

Reports:  70%|███████   | 5000/7111 [19:59<06:50,  5.14it/s]

Reports:  70%|███████   | 5001/7111 [20:00<06:59,  5.03it/s]

Reports:  70%|███████   | 5002/7111 [20:00<06:55,  5.08it/s]

Reports:  70%|███████   | 5003/7111 [20:00<06:58,  5.04it/s]

Reports:  70%|███████   | 5004/7111 [20:00<07:12,  4.87it/s]

Reports:  70%|███████   | 5005/7111 [20:00<06:58,  5.03it/s]

Reports:  70%|███████   | 5006/7111 [20:01<06:58,  5.03it/s]

Reports:  70%|███████   | 5007/7111 [20:01<06:59,  5.02it/s]

Reports:  70%|███████   | 5008/7111 [20:01<06:48,  5.15it/s]

Reports:  70%|███████   | 5009/7111 [20:01<06:42,  5.23it/s]

Reports:  70%|███████   | 5010/7111 [20:01<06:39,  5.26it/s]

Reports:  70%|███████   | 5011/7111 [20:02<06:46,  5.16it/s]

Reports:  70%|███████   | 5012/7111 [20:02<06:45,  5.18it/s]

Reports:  70%|███████   | 5013/7111 [20:02<06:42,  5.21it/s]

Reports:  71%|███████   | 5014/7111 [20:02<06:42,  5.21it/s]

Reports:  71%|███████   | 5015/7111 [20:02<06:51,  5.10it/s]

Reports:  71%|███████   | 5016/7111 [20:03<06:46,  5.16it/s]

Reports:  71%|███████   | 5017/7111 [20:03<06:42,  5.20it/s]

Reports:  71%|███████   | 5018/7111 [20:03<06:45,  5.16it/s]

Reports:  71%|███████   | 5019/7111 [20:03<06:50,  5.10it/s]

Reports:  71%|███████   | 5020/7111 [20:03<06:44,  5.17it/s]

Reports:  71%|███████   | 5021/7111 [20:04<06:49,  5.10it/s]

Reports:  71%|███████   | 5022/7111 [20:04<06:41,  5.21it/s]

Reports:  71%|███████   | 5023/7111 [20:04<06:48,  5.12it/s]

Reports:  71%|███████   | 5024/7111 [20:04<06:43,  5.17it/s]

Reports:  71%|███████   | 5025/7111 [20:04<06:48,  5.11it/s]

Reports:  71%|███████   | 5026/7111 [20:05<06:52,  5.05it/s]

Reports:  71%|███████   | 5027/7111 [20:05<06:47,  5.11it/s]

Reports:  71%|███████   | 5028/7111 [20:05<06:45,  5.13it/s]

Reports:  71%|███████   | 5029/7111 [20:05<06:50,  5.07it/s]

Reports:  71%|███████   | 5030/7111 [20:05<06:43,  5.16it/s]

Reports:  71%|███████   | 5031/7111 [20:06<06:45,  5.13it/s]

Reports:  71%|███████   | 5032/7111 [20:06<06:41,  5.18it/s]

Reports:  71%|███████   | 5033/7111 [20:06<06:45,  5.13it/s]

Reports:  71%|███████   | 5034/7111 [20:06<06:40,  5.19it/s]

Reports:  71%|███████   | 5035/7111 [20:06<06:41,  5.17it/s]

Reports:  71%|███████   | 5036/7111 [20:06<06:39,  5.19it/s]

Reports:  71%|███████   | 5037/7111 [20:07<06:48,  5.07it/s]

Reports:  71%|███████   | 5038/7111 [20:07<06:46,  5.10it/s]

Reports:  71%|███████   | 5039/7111 [20:07<06:42,  5.15it/s]

Reports:  71%|███████   | 5040/7111 [20:07<06:40,  5.17it/s]

Reports:  71%|███████   | 5041/7111 [20:07<06:43,  5.13it/s]

Reports:  71%|███████   | 5042/7111 [20:08<06:38,  5.19it/s]

Reports:  71%|███████   | 5043/7111 [20:08<06:35,  5.22it/s]

Reports:  71%|███████   | 5044/7111 [20:08<06:32,  5.27it/s]

Reports:  71%|███████   | 5045/7111 [20:08<06:31,  5.28it/s]

Reports:  71%|███████   | 5046/7111 [20:08<06:40,  5.16it/s]

Reports:  71%|███████   | 5047/7111 [20:09<06:47,  5.06it/s]

Reports:  71%|███████   | 5048/7111 [20:09<06:51,  5.01it/s]

Reports:  71%|███████   | 5049/7111 [20:09<06:43,  5.11it/s]

Reports:  71%|███████   | 5050/7111 [20:09<06:40,  5.15it/s]

Reports:  71%|███████   | 5051/7111 [20:09<06:40,  5.14it/s]

Reports:  71%|███████   | 5052/7111 [20:10<06:37,  5.18it/s]

Reports:  71%|███████   | 5053/7111 [20:10<06:36,  5.19it/s]

Reports:  71%|███████   | 5054/7111 [20:10<06:43,  5.10it/s]

Reports:  71%|███████   | 5055/7111 [20:10<06:44,  5.08it/s]

Reports:  71%|███████   | 5056/7111 [20:10<06:39,  5.15it/s]

Reports:  71%|███████   | 5057/7111 [20:11<06:43,  5.10it/s]

Reports:  71%|███████   | 5058/7111 [20:11<06:40,  5.13it/s]

Reports:  71%|███████   | 5059/7111 [20:11<06:47,  5.04it/s]

Reports:  71%|███████   | 5060/7111 [20:11<06:40,  5.12it/s]

Reports:  71%|███████   | 5061/7111 [20:11<06:39,  5.14it/s]

Reports:  71%|███████   | 5062/7111 [20:12<06:38,  5.14it/s]

Reports:  71%|███████   | 5063/7111 [20:12<06:42,  5.09it/s]

Reports:  71%|███████   | 5064/7111 [20:12<06:38,  5.13it/s]

Reports:  71%|███████   | 5065/7111 [20:12<06:36,  5.16it/s]

Reports:  71%|███████   | 5066/7111 [20:12<06:32,  5.21it/s]

Reports:  71%|███████▏  | 5067/7111 [20:13<06:37,  5.14it/s]

Reports:  71%|███████▏  | 5068/7111 [20:13<06:38,  5.13it/s]

Reports:  71%|███████▏  | 5069/7111 [20:13<07:54,  4.31it/s]

Reports:  71%|███████▏  | 5070/7111 [20:13<07:27,  4.56it/s]

Reports:  71%|███████▏  | 5071/7111 [20:13<07:15,  4.68it/s]

Reports:  71%|███████▏  | 5072/7111 [20:14<07:02,  4.83it/s]

Reports:  71%|███████▏  | 5073/7111 [20:14<06:49,  4.98it/s]

Reports:  71%|███████▏  | 5074/7111 [20:14<06:44,  5.03it/s]

Reports:  71%|███████▏  | 5075/7111 [20:14<06:38,  5.11it/s]

Reports:  71%|███████▏  | 5076/7111 [20:14<06:36,  5.13it/s]

Reports:  71%|███████▏  | 5077/7111 [20:15<06:34,  5.15it/s]

Reports:  71%|███████▏  | 5078/7111 [20:15<06:31,  5.19it/s]

Reports:  71%|███████▏  | 5079/7111 [20:15<06:26,  5.25it/s]

Reports:  71%|███████▏  | 5080/7111 [20:15<06:25,  5.27it/s]

Reports:  71%|███████▏  | 5081/7111 [20:15<06:23,  5.30it/s]

Reports:  71%|███████▏  | 5082/7111 [20:16<06:30,  5.20it/s]

Reports:  71%|███████▏  | 5083/7111 [20:16<06:28,  5.22it/s]

Reports:  71%|███████▏  | 5084/7111 [20:16<06:24,  5.27it/s]

Reports:  72%|███████▏  | 5085/7111 [20:16<06:21,  5.31it/s]

Reports:  72%|███████▏  | 5086/7111 [20:16<06:19,  5.33it/s]

Reports:  72%|███████▏  | 5087/7111 [20:16<06:19,  5.34it/s]

Reports:  72%|███████▏  | 5088/7111 [20:17<06:18,  5.34it/s]

Reports:  72%|███████▏  | 5089/7111 [20:17<06:17,  5.36it/s]

Reports:  72%|███████▏  | 5090/7111 [20:17<06:21,  5.30it/s]

Reports:  72%|███████▏  | 5091/7111 [20:17<06:20,  5.30it/s]

Reports:  72%|███████▏  | 5092/7111 [20:17<06:20,  5.31it/s]

Reports:  72%|███████▏  | 5093/7111 [20:18<06:15,  5.38it/s]

Reports:  72%|███████▏  | 5094/7111 [20:18<06:18,  5.33it/s]

Reports:  72%|███████▏  | 5095/7111 [20:18<06:18,  5.32it/s]

Reports:  72%|███████▏  | 5096/7111 [20:18<06:20,  5.30it/s]

Reports:  72%|███████▏  | 5097/7111 [20:18<06:20,  5.30it/s]

Reports:  72%|███████▏  | 5098/7111 [20:19<06:17,  5.33it/s]

Reports:  72%|███████▏  | 5099/7111 [20:19<06:21,  5.28it/s]

Reports:  72%|███████▏  | 5100/7111 [20:19<06:24,  5.24it/s]

Reports:  72%|███████▏  | 5101/7111 [20:19<06:18,  5.32it/s]

Reports:  72%|███████▏  | 5102/7111 [20:19<06:17,  5.32it/s]

Reports:  72%|███████▏  | 5103/7111 [20:19<06:29,  5.15it/s]

Reports:  72%|███████▏  | 5104/7111 [20:20<06:22,  5.24it/s]

Reports:  72%|███████▏  | 5105/7111 [20:20<06:24,  5.22it/s]

Reports:  72%|███████▏  | 5106/7111 [20:20<06:23,  5.23it/s]

Reports:  72%|███████▏  | 5107/7111 [20:20<06:24,  5.21it/s]

Reports:  72%|███████▏  | 5108/7111 [20:20<06:22,  5.24it/s]

Reports:  72%|███████▏  | 5109/7111 [20:21<06:27,  5.17it/s]

Reports:  72%|███████▏  | 5110/7111 [20:21<06:26,  5.17it/s]

Reports:  72%|███████▏  | 5111/7111 [20:21<06:30,  5.12it/s]

Reports:  72%|███████▏  | 5112/7111 [20:21<06:28,  5.14it/s]

Reports:  72%|███████▏  | 5113/7111 [20:21<06:28,  5.15it/s]

Reports:  72%|███████▏  | 5114/7111 [20:22<06:21,  5.24it/s]

Reports:  72%|███████▏  | 5115/7111 [20:22<06:22,  5.22it/s]

Reports:  72%|███████▏  | 5116/7111 [20:22<06:29,  5.12it/s]

Reports:  72%|███████▏  | 5117/7111 [20:22<06:25,  5.17it/s]

Reports:  72%|███████▏  | 5118/7111 [20:22<06:27,  5.14it/s]

Reports:  72%|███████▏  | 5119/7111 [20:23<06:22,  5.20it/s]

Reports:  72%|███████▏  | 5120/7111 [20:23<06:21,  5.22it/s]

Reports:  72%|███████▏  | 5121/7111 [20:23<06:17,  5.27it/s]

Reports:  72%|███████▏  | 5122/7111 [20:23<06:24,  5.17it/s]

Reports:  72%|███████▏  | 5123/7111 [20:23<06:26,  5.15it/s]

Reports:  72%|███████▏  | 5124/7111 [20:24<06:31,  5.08it/s]

Reports:  72%|███████▏  | 5125/7111 [20:24<06:23,  5.18it/s]

Reports:  72%|███████▏  | 5126/7111 [20:24<06:18,  5.24it/s]

Reports:  72%|███████▏  | 5127/7111 [20:24<06:17,  5.25it/s]

Reports:  72%|███████▏  | 5128/7111 [20:24<06:19,  5.22it/s]

Reports:  72%|███████▏  | 5129/7111 [20:24<06:18,  5.23it/s]

Reports:  72%|███████▏  | 5130/7111 [20:25<06:19,  5.22it/s]

Reports:  72%|███████▏  | 5131/7111 [20:25<06:18,  5.23it/s]

Reports:  72%|███████▏  | 5132/7111 [20:25<06:20,  5.20it/s]

Reports:  72%|███████▏  | 5133/7111 [20:25<06:16,  5.26it/s]

Reports:  72%|███████▏  | 5134/7111 [20:25<06:13,  5.30it/s]

Reports:  72%|███████▏  | 5135/7111 [20:26<06:14,  5.28it/s]

Reports:  72%|███████▏  | 5136/7111 [20:26<06:13,  5.28it/s]

Reports:  72%|███████▏  | 5137/7111 [20:26<06:16,  5.25it/s]

Reports:  72%|███████▏  | 5138/7111 [20:26<06:19,  5.20it/s]

Reports:  72%|███████▏  | 5139/7111 [20:26<06:14,  5.26it/s]

Reports:  72%|███████▏  | 5140/7111 [20:27<06:19,  5.19it/s]

Reports:  72%|███████▏  | 5141/7111 [20:27<06:18,  5.20it/s]

Reports:  72%|███████▏  | 5142/7111 [20:27<06:13,  5.26it/s]

Reports:  72%|███████▏  | 5143/7111 [20:27<06:12,  5.28it/s]

Reports:  72%|███████▏  | 5144/7111 [20:27<06:19,  5.19it/s]

Reports:  72%|███████▏  | 5145/7111 [20:28<06:14,  5.25it/s]

Reports:  72%|███████▏  | 5146/7111 [20:28<06:11,  5.29it/s]

Reports:  72%|███████▏  | 5147/7111 [20:28<06:15,  5.23it/s]

Reports:  72%|███████▏  | 5148/7111 [20:28<06:19,  5.18it/s]

Reports:  72%|███████▏  | 5149/7111 [20:28<06:21,  5.14it/s]

Reports:  72%|███████▏  | 5150/7111 [20:28<06:14,  5.24it/s]

Reports:  72%|███████▏  | 5151/7111 [20:29<06:12,  5.27it/s]

Reports:  72%|███████▏  | 5152/7111 [20:29<06:13,  5.24it/s]

Reports:  72%|███████▏  | 5153/7111 [20:29<06:14,  5.23it/s]

Reports:  72%|███████▏  | 5154/7111 [20:29<06:14,  5.23it/s]

Reports:  72%|███████▏  | 5155/7111 [20:29<06:12,  5.25it/s]

Reports:  73%|███████▎  | 5156/7111 [20:30<06:09,  5.29it/s]

Reports:  73%|███████▎  | 5157/7111 [20:30<06:09,  5.28it/s]

Reports:  73%|███████▎  | 5158/7111 [20:30<06:08,  5.30it/s]

Reports:  73%|███████▎  | 5159/7111 [20:30<06:04,  5.35it/s]

Reports:  73%|███████▎  | 5160/7111 [20:30<06:04,  5.36it/s]

Reports:  73%|███████▎  | 5161/7111 [20:31<06:14,  5.21it/s]

Reports:  73%|███████▎  | 5162/7111 [20:31<06:15,  5.19it/s]

Reports:  73%|███████▎  | 5163/7111 [20:31<06:15,  5.19it/s]

Reports:  73%|███████▎  | 5164/7111 [20:31<06:13,  5.21it/s]

Reports:  73%|███████▎  | 5165/7111 [20:31<06:12,  5.22it/s]

Reports:  73%|███████▎  | 5166/7111 [20:32<06:14,  5.20it/s]

Reports:  73%|███████▎  | 5167/7111 [20:32<06:12,  5.21it/s]

Reports:  73%|███████▎  | 5168/7111 [20:32<06:11,  5.23it/s]

Reports:  73%|███████▎  | 5169/7111 [20:32<06:14,  5.18it/s]

Reports:  73%|███████▎  | 5170/7111 [20:32<06:20,  5.11it/s]

Reports:  73%|███████▎  | 5171/7111 [20:33<06:24,  5.04it/s]

Reports:  73%|███████▎  | 5172/7111 [20:33<06:22,  5.07it/s]

Reports:  73%|███████▎  | 5173/7111 [20:33<06:14,  5.17it/s]

Reports:  73%|███████▎  | 5174/7111 [20:33<06:21,  5.08it/s]

Reports:  73%|███████▎  | 5175/7111 [20:33<06:17,  5.13it/s]

Reports:  73%|███████▎  | 5176/7111 [20:34<06:19,  5.09it/s]

Reports:  73%|███████▎  | 5177/7111 [20:34<06:23,  5.05it/s]

Reports:  73%|███████▎  | 5178/7111 [20:34<06:30,  4.95it/s]

Reports:  73%|███████▎  | 5179/7111 [20:34<06:32,  4.92it/s]

Reports:  73%|███████▎  | 5180/7111 [20:34<06:36,  4.88it/s]

Reports:  73%|███████▎  | 5181/7111 [20:35<06:28,  4.96it/s]

Reports:  73%|███████▎  | 5182/7111 [20:35<06:36,  4.86it/s]

Reports:  73%|███████▎  | 5183/7111 [20:35<06:27,  4.98it/s]

Reports:  73%|███████▎  | 5184/7111 [20:35<06:23,  5.02it/s]

Reports:  73%|███████▎  | 5185/7111 [20:35<06:20,  5.06it/s]

Reports:  73%|███████▎  | 5186/7111 [20:36<06:13,  5.15it/s]

Reports:  73%|███████▎  | 5187/7111 [20:36<06:11,  5.19it/s]

Reports:  73%|███████▎  | 5188/7111 [20:36<06:21,  5.04it/s]

Reports:  73%|███████▎  | 5189/7111 [20:36<06:23,  5.01it/s]

Reports:  73%|███████▎  | 5190/7111 [20:36<06:23,  5.00it/s]

Reports:  73%|███████▎  | 5191/7111 [20:37<06:21,  5.04it/s]

Reports:  73%|███████▎  | 5192/7111 [20:37<06:15,  5.12it/s]

Reports:  73%|███████▎  | 5193/7111 [20:37<06:13,  5.14it/s]

Reports:  73%|███████▎  | 5194/7111 [20:37<06:06,  5.23it/s]

Reports:  73%|███████▎  | 5195/7111 [20:37<06:16,  5.09it/s]

Reports:  73%|███████▎  | 5196/7111 [20:37<06:08,  5.19it/s]

Reports:  73%|███████▎  | 5197/7111 [20:38<06:09,  5.18it/s]

Reports:  73%|███████▎  | 5198/7111 [20:38<06:14,  5.11it/s]

Reports:  73%|███████▎  | 5199/7111 [20:38<06:05,  5.23it/s]

Reports:  73%|███████▎  | 5200/7111 [20:38<06:02,  5.27it/s]

Reports:  73%|███████▎  | 5201/7111 [20:38<06:07,  5.20it/s]

Reports:  73%|███████▎  | 5202/7111 [20:39<06:06,  5.21it/s]

Reports:  73%|███████▎  | 5203/7111 [20:39<06:05,  5.22it/s]

Reports:  73%|███████▎  | 5204/7111 [20:39<06:01,  5.27it/s]

Reports:  73%|███████▎  | 5205/7111 [20:39<06:00,  5.28it/s]

Reports:  73%|███████▎  | 5206/7111 [20:39<06:07,  5.19it/s]

Reports:  73%|███████▎  | 5207/7111 [20:40<06:02,  5.25it/s]

Reports:  73%|███████▎  | 5208/7111 [20:40<06:16,  5.05it/s]

Reports:  73%|███████▎  | 5209/7111 [20:40<06:11,  5.12it/s]

Reports:  73%|███████▎  | 5210/7111 [20:40<06:06,  5.18it/s]

Reports:  73%|███████▎  | 5211/7111 [20:40<06:09,  5.15it/s]

Reports:  73%|███████▎  | 5212/7111 [20:41<06:12,  5.10it/s]

Reports:  73%|███████▎  | 5213/7111 [20:41<06:06,  5.18it/s]

Reports:  73%|███████▎  | 5214/7111 [20:41<06:05,  5.19it/s]

Reports:  73%|███████▎  | 5215/7111 [20:41<06:05,  5.19it/s]

Reports:  73%|███████▎  | 5216/7111 [20:41<06:07,  5.16it/s]

Reports:  73%|███████▎  | 5217/7111 [20:42<06:03,  5.21it/s]

Reports:  73%|███████▎  | 5218/7111 [20:42<06:01,  5.23it/s]

Reports:  73%|███████▎  | 5219/7111 [20:42<05:57,  5.29it/s]

Reports:  73%|███████▎  | 5220/7111 [20:42<05:57,  5.29it/s]

Reports:  73%|███████▎  | 5221/7111 [20:42<06:00,  5.24it/s]

Reports:  73%|███████▎  | 5222/7111 [20:42<05:57,  5.28it/s]

Reports:  73%|███████▎  | 5223/7111 [20:43<05:56,  5.30it/s]

Reports:  73%|███████▎  | 5224/7111 [20:43<05:54,  5.32it/s]

Reports:  73%|███████▎  | 5225/7111 [20:43<05:53,  5.34it/s]

Reports:  73%|███████▎  | 5226/7111 [20:43<05:52,  5.35it/s]

Reports:  74%|███████▎  | 5227/7111 [20:43<05:59,  5.23it/s]

Reports:  74%|███████▎  | 5228/7111 [20:44<05:57,  5.26it/s]

Reports:  74%|███████▎  | 5229/7111 [20:44<05:56,  5.29it/s]

Reports:  74%|███████▎  | 5230/7111 [20:44<06:04,  5.17it/s]

Reports:  74%|███████▎  | 5231/7111 [20:44<06:01,  5.20it/s]

Reports:  74%|███████▎  | 5232/7111 [20:44<06:01,  5.20it/s]

Reports:  74%|███████▎  | 5233/7111 [20:45<06:05,  5.14it/s]

Reports:  74%|███████▎  | 5234/7111 [20:45<06:08,  5.09it/s]

Reports:  74%|███████▎  | 5235/7111 [20:45<06:07,  5.11it/s]

Reports:  74%|███████▎  | 5236/7111 [20:45<06:06,  5.11it/s]

Reports:  74%|███████▎  | 5237/7111 [20:45<06:03,  5.16it/s]

Reports:  74%|███████▎  | 5238/7111 [20:46<06:02,  5.16it/s]

Reports:  74%|███████▎  | 5239/7111 [20:46<06:04,  5.13it/s]

Reports:  74%|███████▎  | 5240/7111 [20:46<06:09,  5.07it/s]

Reports:  74%|███████▎  | 5241/7111 [20:46<06:06,  5.10it/s]

Reports:  74%|███████▎  | 5242/7111 [20:46<06:10,  5.04it/s]

Reports:  74%|███████▎  | 5243/7111 [20:47<06:13,  5.00it/s]

Reports:  74%|███████▎  | 5244/7111 [20:47<06:13,  5.00it/s]

Reports:  74%|███████▍  | 5245/7111 [20:47<06:12,  5.01it/s]

Reports:  74%|███████▍  | 5246/7111 [20:47<06:10,  5.04it/s]

Reports:  74%|███████▍  | 5247/7111 [20:47<06:02,  5.15it/s]

Reports:  74%|███████▍  | 5248/7111 [20:48<06:10,  5.03it/s]

Reports:  74%|███████▍  | 5249/7111 [20:48<06:09,  5.04it/s]

Reports:  74%|███████▍  | 5250/7111 [20:48<06:07,  5.06it/s]

Reports:  74%|███████▍  | 5251/7111 [20:48<06:13,  4.99it/s]

Reports:  74%|███████▍  | 5252/7111 [20:48<06:07,  5.06it/s]

Reports:  74%|███████▍  | 5253/7111 [20:49<06:01,  5.14it/s]

Reports:  74%|███████▍  | 5254/7111 [20:49<06:03,  5.10it/s]

Reports:  74%|███████▍  | 5255/7111 [20:49<06:05,  5.08it/s]

Reports:  74%|███████▍  | 5256/7111 [20:49<06:05,  5.07it/s]

Reports:  74%|███████▍  | 5257/7111 [20:49<06:00,  5.14it/s]

Reports:  74%|███████▍  | 5258/7111 [20:49<06:01,  5.13it/s]

Reports:  74%|███████▍  | 5259/7111 [20:50<06:07,  5.04it/s]

Reports:  74%|███████▍  | 5260/7111 [20:50<06:02,  5.10it/s]

Reports:  74%|███████▍  | 5261/7111 [20:50<05:59,  5.14it/s]

Reports:  74%|███████▍  | 5262/7111 [20:50<06:01,  5.11it/s]

Reports:  74%|███████▍  | 5263/7111 [20:50<05:56,  5.18it/s]

Reports:  74%|███████▍  | 5264/7111 [20:51<05:55,  5.19it/s]

Reports:  74%|███████▍  | 5265/7111 [20:51<05:54,  5.21it/s]

Reports:  74%|███████▍  | 5266/7111 [20:51<06:06,  5.03it/s]

Reports:  74%|███████▍  | 5267/7111 [20:51<06:10,  4.98it/s]

Reports:  74%|███████▍  | 5268/7111 [20:51<06:11,  4.96it/s]

Reports:  74%|███████▍  | 5269/7111 [20:52<06:06,  5.03it/s]

Reports:  74%|███████▍  | 5270/7111 [20:52<06:03,  5.07it/s]

Reports:  74%|███████▍  | 5271/7111 [20:52<05:55,  5.18it/s]

Reports:  74%|███████▍  | 5272/7111 [20:52<05:59,  5.11it/s]

Reports:  74%|███████▍  | 5273/7111 [20:52<05:56,  5.16it/s]

Reports:  74%|███████▍  | 5274/7111 [20:53<05:58,  5.13it/s]

Reports:  74%|███████▍  | 5275/7111 [20:53<05:59,  5.10it/s]

Reports:  74%|███████▍  | 5276/7111 [20:53<05:53,  5.19it/s]

Reports:  74%|███████▍  | 5277/7111 [20:53<05:50,  5.23it/s]

Reports:  74%|███████▍  | 5278/7111 [20:53<06:03,  5.05it/s]

Reports:  74%|███████▍  | 5279/7111 [20:54<06:03,  5.03it/s]

Reports:  74%|███████▍  | 5280/7111 [20:54<06:00,  5.08it/s]

Reports:  74%|███████▍  | 5281/7111 [20:54<06:00,  5.07it/s]

Reports:  74%|███████▍  | 5282/7111 [20:54<05:54,  5.16it/s]

Reports:  74%|███████▍  | 5283/7111 [20:54<05:55,  5.14it/s]

Reports:  74%|███████▍  | 5284/7111 [20:55<05:55,  5.14it/s]

Reports:  74%|███████▍  | 5285/7111 [20:55<05:58,  5.09it/s]

Reports:  74%|███████▍  | 5286/7111 [20:55<05:56,  5.12it/s]

Reports:  74%|███████▍  | 5287/7111 [20:55<05:58,  5.09it/s]

Reports:  74%|███████▍  | 5288/7111 [20:55<06:02,  5.03it/s]

Reports:  74%|███████▍  | 5289/7111 [20:56<06:05,  4.98it/s]

Reports:  74%|███████▍  | 5290/7111 [20:56<05:59,  5.06it/s]

Reports:  74%|███████▍  | 5291/7111 [20:56<05:52,  5.16it/s]

Reports:  74%|███████▍  | 5292/7111 [20:56<05:51,  5.18it/s]

Reports:  74%|███████▍  | 5293/7111 [20:56<05:54,  5.13it/s]

Reports:  74%|███████▍  | 5294/7111 [20:57<05:52,  5.16it/s]

Reports:  74%|███████▍  | 5295/7111 [20:57<05:46,  5.24it/s]

Reports:  74%|███████▍  | 5296/7111 [20:57<05:42,  5.29it/s]

Reports:  74%|███████▍  | 5297/7111 [20:57<05:48,  5.20it/s]

Reports:  75%|███████▍  | 5298/7111 [20:57<05:45,  5.24it/s]

Reports:  75%|███████▍  | 5299/7111 [20:57<05:50,  5.17it/s]

Reports:  75%|███████▍  | 5300/7111 [20:58<05:55,  5.10it/s]

Reports:  75%|███████▍  | 5301/7111 [20:58<05:49,  5.17it/s]

Reports:  75%|███████▍  | 5302/7111 [20:58<05:49,  5.18it/s]

Reports:  75%|███████▍  | 5303/7111 [20:58<05:50,  5.16it/s]

Reports:  75%|███████▍  | 5304/7111 [20:58<05:48,  5.19it/s]

Reports:  75%|███████▍  | 5305/7111 [20:59<05:47,  5.20it/s]

Reports:  75%|███████▍  | 5306/7111 [21:00<12:25,  2.42it/s]

Reports:  75%|███████▍  | 5307/7111 [21:00<10:25,  2.88it/s]

Reports:  75%|███████▍  | 5308/7111 [21:00<09:01,  3.33it/s]

Reports:  75%|███████▍  | 5309/7111 [21:00<08:11,  3.67it/s]

Reports:  75%|███████▍  | 5310/7111 [21:00<07:28,  4.01it/s]

Reports:  75%|███████▍  | 5311/7111 [21:01<06:59,  4.29it/s]

Reports:  75%|███████▍  | 5312/7111 [21:01<06:41,  4.48it/s]

Reports:  75%|███████▍  | 5313/7111 [21:01<06:24,  4.68it/s]

Reports:  75%|███████▍  | 5314/7111 [21:01<06:12,  4.83it/s]

Reports:  75%|███████▍  | 5315/7111 [21:01<06:04,  4.93it/s]

Reports:  75%|███████▍  | 5316/7111 [21:02<06:01,  4.97it/s]

Reports:  75%|███████▍  | 5317/7111 [21:02<05:53,  5.07it/s]

Reports:  75%|███████▍  | 5318/7111 [21:02<05:50,  5.12it/s]

Reports:  75%|███████▍  | 5319/7111 [21:02<05:57,  5.02it/s]

Reports:  75%|███████▍  | 5320/7111 [21:02<05:51,  5.09it/s]

Reports:  75%|███████▍  | 5321/7111 [21:02<05:45,  5.19it/s]

Reports:  75%|███████▍  | 5322/7111 [21:03<05:49,  5.11it/s]

Reports:  75%|███████▍  | 5323/7111 [21:03<05:48,  5.12it/s]

Reports:  75%|███████▍  | 5324/7111 [21:03<05:45,  5.17it/s]

Reports:  75%|███████▍  | 5325/7111 [21:03<05:48,  5.12it/s]

Reports:  75%|███████▍  | 5326/7111 [21:03<06:02,  4.92it/s]

Reports:  75%|███████▍  | 5327/7111 [21:04<05:59,  4.96it/s]

Reports:  75%|███████▍  | 5328/7111 [21:04<06:01,  4.93it/s]

Reports:  75%|███████▍  | 5329/7111 [21:05<11:50,  2.51it/s]

Reports:  75%|███████▍  | 5330/7111 [21:05<09:59,  2.97it/s]

Reports:  75%|███████▍  | 5331/7111 [21:05<08:43,  3.40it/s]

Reports:  75%|███████▍  | 5332/7111 [21:05<07:45,  3.82it/s]

Reports:  75%|███████▍  | 5333/7111 [21:06<07:09,  4.14it/s]

Reports:  75%|███████▌  | 5334/7111 [21:06<06:43,  4.40it/s]

Reports:  75%|███████▌  | 5335/7111 [21:06<06:24,  4.61it/s]

Reports:  75%|███████▌  | 5336/7111 [21:06<06:34,  4.50it/s]

Reports:  75%|███████▌  | 5337/7111 [21:06<06:19,  4.67it/s]

Reports:  75%|███████▌  | 5338/7111 [21:07<06:08,  4.81it/s]

Reports:  75%|███████▌  | 5339/7111 [21:07<05:58,  4.94it/s]

Reports:  75%|███████▌  | 5340/7111 [21:07<05:50,  5.05it/s]

Reports:  75%|███████▌  | 5341/7111 [21:07<07:43,  3.82it/s]

Reports:  75%|███████▌  | 5342/7111 [21:08<07:03,  4.17it/s]

Reports:  75%|███████▌  | 5343/7111 [21:08<06:40,  4.41it/s]

Reports:  75%|███████▌  | 5344/7111 [21:08<06:20,  4.64it/s]

Reports:  75%|███████▌  | 5345/7111 [21:08<06:22,  4.62it/s]

Reports:  75%|███████▌  | 5346/7111 [21:08<06:08,  4.78it/s]

Reports:  75%|███████▌  | 5347/7111 [21:08<05:58,  4.92it/s]

Reports:  75%|███████▌  | 5348/7111 [21:09<05:49,  5.05it/s]

Reports:  75%|███████▌  | 5349/7111 [21:09<05:44,  5.11it/s]

Reports:  75%|███████▌  | 5350/7111 [21:09<05:45,  5.10it/s]

Reports:  75%|███████▌  | 5351/7111 [21:09<05:43,  5.12it/s]

Reports:  75%|███████▌  | 5352/7111 [21:09<05:47,  5.07it/s]

Reports:  75%|███████▌  | 5353/7111 [21:10<05:42,  5.13it/s]

Reports:  75%|███████▌  | 5354/7111 [21:10<05:42,  5.13it/s]

Reports:  75%|███████▌  | 5355/7111 [21:10<05:39,  5.17it/s]

Reports:  75%|███████▌  | 5356/7111 [21:10<05:39,  5.17it/s]

Reports:  75%|███████▌  | 5357/7111 [21:10<05:50,  5.01it/s]

Reports:  75%|███████▌  | 5358/7111 [21:11<05:41,  5.13it/s]

Reports:  75%|███████▌  | 5359/7111 [21:11<05:46,  5.06it/s]

Reports:  75%|███████▌  | 5360/7111 [21:11<05:41,  5.12it/s]

Reports:  75%|███████▌  | 5361/7111 [21:11<05:43,  5.09it/s]

Reports:  75%|███████▌  | 5362/7111 [21:11<05:40,  5.14it/s]

Reports:  75%|███████▌  | 5363/7111 [21:12<05:38,  5.16it/s]

Reports:  75%|███████▌  | 5364/7111 [21:12<05:42,  5.10it/s]

Reports:  75%|███████▌  | 5365/7111 [21:12<05:37,  5.17it/s]

Reports:  75%|███████▌  | 5366/7111 [21:12<05:33,  5.24it/s]

Reports:  75%|███████▌  | 5367/7111 [21:12<05:35,  5.19it/s]

Reports:  75%|███████▌  | 5368/7111 [21:13<05:41,  5.10it/s]

Reports:  76%|███████▌  | 5369/7111 [21:13<05:39,  5.13it/s]

Reports:  76%|███████▌  | 5370/7111 [21:13<05:37,  5.16it/s]

Reports:  76%|███████▌  | 5371/7111 [21:13<05:40,  5.11it/s]

Reports:  76%|███████▌  | 5372/7111 [21:13<05:43,  5.07it/s]

Reports:  76%|███████▌  | 5373/7111 [21:14<05:41,  5.09it/s]

Reports:  76%|███████▌  | 5374/7111 [21:14<05:46,  5.01it/s]

Reports:  76%|███████▌  | 5375/7111 [21:14<06:21,  4.55it/s]

Reports:  76%|███████▌  | 5376/7111 [21:14<06:04,  4.76it/s]

Reports:  76%|███████▌  | 5377/7111 [21:14<05:51,  4.93it/s]

Reports:  76%|███████▌  | 5378/7111 [21:15<05:46,  5.00it/s]

Reports:  76%|███████▌  | 5379/7111 [21:15<05:48,  4.97it/s]

Reports:  76%|███████▌  | 5380/7111 [21:15<05:47,  4.98it/s]

Reports:  76%|███████▌  | 5381/7111 [21:15<05:38,  5.11it/s]

Reports:  76%|███████▌  | 5382/7111 [21:15<05:39,  5.09it/s]

Reports:  76%|███████▌  | 5383/7111 [21:16<05:31,  5.21it/s]

Reports:  76%|███████▌  | 5384/7111 [21:16<05:34,  5.17it/s]

Reports:  76%|███████▌  | 5385/7111 [21:16<05:32,  5.18it/s]

Reports:  76%|███████▌  | 5386/7111 [21:16<05:30,  5.23it/s]

Reports:  76%|███████▌  | 5387/7111 [21:16<05:40,  5.06it/s]

Reports:  76%|███████▌  | 5388/7111 [21:17<05:38,  5.09it/s]

Reports:  76%|███████▌  | 5389/7111 [21:17<05:34,  5.15it/s]

Reports:  76%|███████▌  | 5390/7111 [21:17<05:35,  5.13it/s]

Reports:  76%|███████▌  | 5391/7111 [21:17<05:35,  5.12it/s]

Reports:  76%|███████▌  | 5392/7111 [21:17<05:33,  5.16it/s]

Reports:  76%|███████▌  | 5393/7111 [21:18<05:39,  5.05it/s]

Reports:  76%|███████▌  | 5394/7111 [21:18<05:35,  5.12it/s]

Reports:  76%|███████▌  | 5395/7111 [21:18<05:41,  5.02it/s]

Reports:  76%|███████▌  | 5396/7111 [21:18<05:42,  5.01it/s]

Reports:  76%|███████▌  | 5397/7111 [21:18<05:37,  5.08it/s]

Reports:  76%|███████▌  | 5398/7111 [21:19<05:40,  5.03it/s]

Reports:  76%|███████▌  | 5399/7111 [21:19<05:35,  5.10it/s]

Reports:  76%|███████▌  | 5400/7111 [21:19<05:30,  5.17it/s]

Reports:  76%|███████▌  | 5401/7111 [21:19<05:33,  5.13it/s]

Reports:  76%|███████▌  | 5402/7111 [21:19<05:34,  5.12it/s]

Reports:  76%|███████▌  | 5403/7111 [21:19<05:28,  5.20it/s]

Reports:  76%|███████▌  | 5404/7111 [21:20<05:24,  5.25it/s]

Reports:  76%|███████▌  | 5405/7111 [21:20<05:30,  5.16it/s]

Reports:  76%|███████▌  | 5406/7111 [21:20<05:28,  5.20it/s]

Reports:  76%|███████▌  | 5407/7111 [21:20<05:44,  4.94it/s]

Reports:  76%|███████▌  | 5408/7111 [21:20<05:35,  5.07it/s]

Reports:  76%|███████▌  | 5409/7111 [21:21<05:38,  5.02it/s]

Reports:  76%|███████▌  | 5410/7111 [21:21<05:33,  5.10it/s]

Reports:  76%|███████▌  | 5411/7111 [21:21<05:29,  5.16it/s]

Reports:  76%|███████▌  | 5412/7111 [21:21<05:29,  5.15it/s]

Reports:  76%|███████▌  | 5413/7111 [21:21<05:28,  5.16it/s]

Reports:  76%|███████▌  | 5414/7111 [21:22<05:26,  5.19it/s]

Reports:  76%|███████▌  | 5415/7111 [21:22<05:48,  4.86it/s]

Reports:  76%|███████▌  | 5416/7111 [21:22<05:44,  4.92it/s]

Reports:  76%|███████▌  | 5417/7111 [21:22<05:47,  4.88it/s]

Reports:  76%|███████▌  | 5418/7111 [21:22<05:42,  4.94it/s]

Reports:  76%|███████▌  | 5419/7111 [21:23<05:37,  5.01it/s]

Reports:  76%|███████▌  | 5420/7111 [21:23<05:44,  4.91it/s]

Reports:  76%|███████▌  | 5421/7111 [21:23<05:36,  5.02it/s]

Reports:  76%|███████▌  | 5422/7111 [21:23<05:35,  5.03it/s]

Reports:  76%|███████▋  | 5423/7111 [21:23<05:30,  5.11it/s]

Reports:  76%|███████▋  | 5424/7111 [21:24<05:29,  5.13it/s]

Reports:  76%|███████▋  | 5425/7111 [21:24<05:34,  5.04it/s]

Reports:  76%|███████▋  | 5426/7111 [21:24<05:28,  5.13it/s]

Reports:  76%|███████▋  | 5427/7111 [21:24<05:28,  5.12it/s]

Reports:  76%|███████▋  | 5428/7111 [21:24<05:30,  5.09it/s]

Reports:  76%|███████▋  | 5429/7111 [21:25<05:27,  5.13it/s]

Reports:  76%|███████▋  | 5430/7111 [21:25<05:36,  5.00it/s]

Reports:  76%|███████▋  | 5431/7111 [21:25<05:36,  4.99it/s]

Reports:  76%|███████▋  | 5432/7111 [21:25<05:32,  5.05it/s]

Reports:  76%|███████▋  | 5433/7111 [21:25<05:28,  5.10it/s]

Reports:  76%|███████▋  | 5434/7111 [21:26<05:25,  5.14it/s]

Reports:  76%|███████▋  | 5435/7111 [21:26<05:24,  5.17it/s]

Reports:  76%|███████▋  | 5436/7111 [21:26<05:32,  5.04it/s]

Reports:  76%|███████▋  | 5437/7111 [21:26<05:28,  5.10it/s]

Reports:  76%|███████▋  | 5438/7111 [21:26<05:22,  5.18it/s]

Reports:  76%|███████▋  | 5439/7111 [21:27<05:35,  4.98it/s]

Reports:  77%|███████▋  | 5440/7111 [21:27<05:28,  5.08it/s]

Reports:  77%|███████▋  | 5441/7111 [21:27<05:24,  5.15it/s]

Reports:  77%|███████▋  | 5442/7111 [21:27<05:24,  5.14it/s]

Reports:  77%|███████▋  | 5443/7111 [21:27<05:25,  5.13it/s]

Reports:  77%|███████▋  | 5444/7111 [21:28<05:22,  5.17it/s]

Reports:  77%|███████▋  | 5445/7111 [21:28<05:22,  5.16it/s]

Reports:  77%|███████▋  | 5446/7111 [21:28<05:18,  5.23it/s]

Reports:  77%|███████▋  | 5447/7111 [21:28<05:18,  5.22it/s]

Reports:  77%|███████▋  | 5448/7111 [21:28<05:17,  5.24it/s]

Reports:  77%|███████▋  | 5449/7111 [21:29<05:20,  5.19it/s]

Reports:  77%|███████▋  | 5450/7111 [21:29<05:17,  5.22it/s]

Reports:  77%|███████▋  | 5451/7111 [21:29<05:18,  5.21it/s]

Reports:  77%|███████▋  | 5452/7111 [21:29<05:22,  5.15it/s]

Reports:  77%|███████▋  | 5453/7111 [21:29<06:17,  4.39it/s]

Reports:  77%|███████▋  | 5454/7111 [21:30<06:00,  4.60it/s]

Reports:  77%|███████▋  | 5455/7111 [21:30<05:47,  4.77it/s]

Reports:  77%|███████▋  | 5456/7111 [21:30<05:42,  4.84it/s]

Reports:  77%|███████▋  | 5457/7111 [21:30<05:30,  5.00it/s]

Reports:  77%|███████▋  | 5458/7111 [21:30<05:34,  4.94it/s]

Reports:  77%|███████▋  | 5459/7111 [21:31<05:28,  5.03it/s]

Reports:  77%|███████▋  | 5460/7111 [21:31<05:26,  5.06it/s]

Reports:  77%|███████▋  | 5461/7111 [21:31<05:18,  5.18it/s]

Reports:  77%|███████▋  | 5462/7111 [21:31<05:19,  5.15it/s]

Reports:  77%|███████▋  | 5463/7111 [21:31<05:20,  5.15it/s]

Reports:  77%|███████▋  | 5464/7111 [21:32<05:16,  5.20it/s]

Reports:  77%|███████▋  | 5465/7111 [21:32<05:18,  5.16it/s]

Reports:  77%|███████▋  | 5466/7111 [21:32<05:15,  5.22it/s]

Reports:  77%|███████▋  | 5467/7111 [21:32<05:23,  5.09it/s]

Reports:  77%|███████▋  | 5468/7111 [21:32<05:26,  5.03it/s]

Reports:  77%|███████▋  | 5469/7111 [21:33<05:22,  5.09it/s]

Reports:  77%|███████▋  | 5470/7111 [21:33<05:16,  5.18it/s]

Reports:  77%|███████▋  | 5471/7111 [21:33<05:08,  5.32it/s]

Reports:  77%|███████▋  | 5472/7111 [21:33<05:31,  4.95it/s]

Reports:  77%|███████▋  | 5473/7111 [21:33<05:25,  5.03it/s]

Reports:  77%|███████▋  | 5474/7111 [21:33<05:22,  5.08it/s]

Reports:  77%|███████▋  | 5475/7111 [21:34<05:21,  5.09it/s]

Reports:  77%|███████▋  | 5476/7111 [21:34<05:16,  5.16it/s]

Reports:  77%|███████▋  | 5477/7111 [21:34<05:12,  5.23it/s]

Reports:  77%|███████▋  | 5478/7111 [21:34<05:19,  5.11it/s]

Reports:  77%|███████▋  | 5479/7111 [21:34<05:20,  5.10it/s]

Reports:  77%|███████▋  | 5480/7111 [21:35<05:23,  5.04it/s]

Reports:  77%|███████▋  | 5481/7111 [21:35<05:23,  5.04it/s]

Reports:  77%|███████▋  | 5482/7111 [21:35<05:24,  5.01it/s]

Reports:  77%|███████▋  | 5483/7111 [21:35<05:19,  5.10it/s]

Reports:  77%|███████▋  | 5484/7111 [21:35<05:22,  5.04it/s]

Reports:  77%|███████▋  | 5485/7111 [21:36<05:18,  5.10it/s]

Reports:  77%|███████▋  | 5486/7111 [21:36<05:14,  5.17it/s]

Reports:  77%|███████▋  | 5487/7111 [21:36<05:10,  5.22it/s]

Reports:  77%|███████▋  | 5488/7111 [21:36<06:38,  4.07it/s]

Reports:  77%|███████▋  | 5489/7111 [21:37<06:15,  4.32it/s]

Reports:  77%|███████▋  | 5490/7111 [21:37<06:00,  4.50it/s]

Reports:  77%|███████▋  | 5491/7111 [21:37<05:41,  4.75it/s]

Reports:  77%|███████▋  | 5492/7111 [21:37<05:33,  4.86it/s]

Reports:  77%|███████▋  | 5493/7111 [21:37<05:21,  5.03it/s]

Reports:  77%|███████▋  | 5494/7111 [21:38<05:15,  5.12it/s]

Reports:  77%|███████▋  | 5495/7111 [21:38<05:14,  5.13it/s]

Reports:  77%|███████▋  | 5496/7111 [21:38<05:14,  5.14it/s]

Reports:  77%|███████▋  | 5497/7111 [21:38<05:11,  5.19it/s]

Reports:  77%|███████▋  | 5498/7111 [21:38<05:07,  5.24it/s]

Reports:  77%|███████▋  | 5499/7111 [21:39<05:10,  5.19it/s]

Reports:  77%|███████▋  | 5500/7111 [21:39<05:14,  5.13it/s]

Reports:  77%|███████▋  | 5501/7111 [21:39<05:12,  5.16it/s]

Reports:  77%|███████▋  | 5502/7111 [21:39<05:12,  5.14it/s]

Reports:  77%|███████▋  | 5503/7111 [21:39<05:15,  5.09it/s]

Reports:  77%|███████▋  | 5504/7111 [21:39<05:12,  5.14it/s]

Reports:  77%|███████▋  | 5505/7111 [21:40<05:10,  5.18it/s]

Reports:  77%|███████▋  | 5506/7111 [21:40<05:13,  5.12it/s]

Reports:  77%|███████▋  | 5507/7111 [21:40<05:05,  5.26it/s]

Reports:  77%|███████▋  | 5508/7111 [21:40<05:11,  5.15it/s]

Reports:  77%|███████▋  | 5509/7111 [21:40<05:10,  5.15it/s]

Reports:  77%|███████▋  | 5510/7111 [21:41<05:19,  5.02it/s]

Reports:  77%|███████▋  | 5511/7111 [21:41<05:15,  5.07it/s]

Reports:  78%|███████▊  | 5512/7111 [21:41<05:12,  5.11it/s]

Reports:  78%|███████▊  | 5513/7111 [21:41<05:11,  5.13it/s]

Reports:  78%|███████▊  | 5514/7111 [21:41<05:09,  5.16it/s]

Reports:  78%|███████▊  | 5515/7111 [21:42<05:09,  5.16it/s]

Reports:  78%|███████▊  | 5516/7111 [21:42<05:18,  5.01it/s]

Reports:  78%|███████▊  | 5517/7111 [21:42<05:16,  5.03it/s]

Reports:  78%|███████▊  | 5518/7111 [21:42<05:10,  5.14it/s]

Reports:  78%|███████▊  | 5519/7111 [21:42<05:07,  5.17it/s]

Reports:  78%|███████▊  | 5520/7111 [21:43<05:18,  5.00it/s]

Reports:  78%|███████▊  | 5521/7111 [21:43<05:15,  5.04it/s]

Reports:  78%|███████▊  | 5522/7111 [21:43<05:14,  5.05it/s]

Reports:  78%|███████▊  | 5523/7111 [21:43<05:12,  5.08it/s]

Reports:  78%|███████▊  | 5524/7111 [21:43<05:09,  5.13it/s]

Reports:  78%|███████▊  | 5525/7111 [21:44<05:08,  5.14it/s]

Reports:  78%|███████▊  | 5526/7111 [21:44<05:05,  5.19it/s]

Reports:  78%|███████▊  | 5527/7111 [21:44<05:12,  5.07it/s]

Reports:  78%|███████▊  | 5528/7111 [21:44<05:07,  5.14it/s]

Reports:  78%|███████▊  | 5529/7111 [21:44<05:10,  5.10it/s]

Reports:  78%|███████▊  | 5530/7111 [21:45<05:10,  5.10it/s]

Reports:  78%|███████▊  | 5531/7111 [21:45<05:15,  5.00it/s]

Reports:  78%|███████▊  | 5532/7111 [21:45<05:10,  5.09it/s]

Reports:  78%|███████▊  | 5533/7111 [21:45<05:06,  5.15it/s]

Reports:  78%|███████▊  | 5534/7111 [21:45<05:05,  5.17it/s]

Reports:  78%|███████▊  | 5535/7111 [21:46<05:06,  5.14it/s]

Reports:  78%|███████▊  | 5536/7111 [21:46<05:13,  5.03it/s]

Reports:  78%|███████▊  | 5537/7111 [21:46<05:12,  5.04it/s]

Reports:  78%|███████▊  | 5538/7111 [21:46<05:11,  5.04it/s]

Reports:  78%|███████▊  | 5539/7111 [21:46<05:08,  5.09it/s]

Reports:  78%|███████▊  | 5540/7111 [21:47<05:18,  4.93it/s]

Reports:  78%|███████▊  | 5541/7111 [21:47<05:12,  5.03it/s]

Reports:  78%|███████▊  | 5542/7111 [21:47<05:13,  5.01it/s]

Reports:  78%|███████▊  | 5543/7111 [21:47<05:09,  5.06it/s]

Reports:  78%|███████▊  | 5544/7111 [21:47<05:06,  5.11it/s]

Reports:  78%|███████▊  | 5545/7111 [21:48<05:04,  5.14it/s]

Reports:  78%|███████▊  | 5546/7111 [21:48<05:00,  5.20it/s]

Reports:  78%|███████▊  | 5547/7111 [21:48<05:01,  5.19it/s]

Reports:  78%|███████▊  | 5548/7111 [21:48<05:09,  5.05it/s]

Reports:  78%|███████▊  | 5549/7111 [21:48<05:11,  5.02it/s]

Reports:  78%|███████▊  | 5550/7111 [21:49<05:04,  5.12it/s]

Reports:  78%|███████▊  | 5551/7111 [21:49<05:10,  5.03it/s]

Reports:  78%|███████▊  | 5552/7111 [21:49<05:03,  5.14it/s]

Reports:  78%|███████▊  | 5553/7111 [21:49<05:11,  5.00it/s]

Reports:  78%|███████▊  | 5554/7111 [21:49<05:10,  5.02it/s]

Reports:  78%|███████▊  | 5555/7111 [21:49<05:03,  5.12it/s]

Reports:  78%|███████▊  | 5556/7111 [21:50<05:04,  5.10it/s]

Reports:  78%|███████▊  | 5557/7111 [21:50<05:10,  5.01it/s]

Reports:  78%|███████▊  | 5558/7111 [21:50<05:06,  5.07it/s]

Reports:  78%|███████▊  | 5559/7111 [21:50<05:02,  5.14it/s]

Reports:  78%|███████▊  | 5560/7111 [21:50<04:56,  5.24it/s]

Reports:  78%|███████▊  | 5561/7111 [21:51<05:02,  5.12it/s]

Reports:  78%|███████▊  | 5562/7111 [21:51<04:58,  5.18it/s]

Reports:  78%|███████▊  | 5563/7111 [21:51<04:57,  5.20it/s]

Reports:  78%|███████▊  | 5564/7111 [21:51<04:54,  5.25it/s]

Reports:  78%|███████▊  | 5565/7111 [21:51<04:57,  5.19it/s]

Reports:  78%|███████▊  | 5566/7111 [21:52<05:04,  5.08it/s]

Reports:  78%|███████▊  | 5567/7111 [21:52<05:02,  5.10it/s]

Reports:  78%|███████▊  | 5568/7111 [21:52<05:00,  5.14it/s]

Reports:  78%|███████▊  | 5569/7111 [21:52<05:00,  5.14it/s]

Reports:  78%|███████▊  | 5570/7111 [21:52<05:05,  5.04it/s]

Reports:  78%|███████▊  | 5571/7111 [21:53<05:00,  5.13it/s]

Reports:  78%|███████▊  | 5572/7111 [21:53<04:56,  5.19it/s]

Reports:  78%|███████▊  | 5573/7111 [21:53<04:58,  5.16it/s]

Reports:  78%|███████▊  | 5574/7111 [21:53<04:57,  5.16it/s]

Reports:  78%|███████▊  | 5575/7111 [21:53<04:55,  5.21it/s]

Reports:  78%|███████▊  | 5576/7111 [21:54<04:52,  5.25it/s]

Reports:  78%|███████▊  | 5577/7111 [21:54<04:52,  5.25it/s]

Reports:  78%|███████▊  | 5578/7111 [21:54<04:51,  5.27it/s]

Reports:  78%|███████▊  | 5579/7111 [21:54<04:50,  5.28it/s]

Reports:  78%|███████▊  | 5580/7111 [21:54<04:55,  5.18it/s]

Reports:  78%|███████▊  | 5581/7111 [21:55<05:00,  5.09it/s]

Reports:  78%|███████▊  | 5582/7111 [21:55<04:54,  5.19it/s]

Reports:  79%|███████▊  | 5583/7111 [21:55<04:55,  5.17it/s]

Reports:  79%|███████▊  | 5584/7111 [21:55<04:55,  5.16it/s]

Reports:  79%|███████▊  | 5585/7111 [21:55<04:58,  5.11it/s]

Reports:  79%|███████▊  | 5586/7111 [21:56<05:00,  5.07it/s]

Reports:  79%|███████▊  | 5587/7111 [21:56<04:56,  5.13it/s]

Reports:  79%|███████▊  | 5588/7111 [21:56<04:54,  5.17it/s]

Reports:  79%|███████▊  | 5589/7111 [21:56<04:56,  5.13it/s]

Reports:  79%|███████▊  | 5590/7111 [21:56<05:01,  5.05it/s]

Reports:  79%|███████▊  | 5591/7111 [21:56<04:55,  5.14it/s]

Reports:  79%|███████▊  | 5592/7111 [21:57<04:55,  5.13it/s]

Reports:  79%|███████▊  | 5593/7111 [21:57<04:52,  5.18it/s]

Reports:  79%|███████▊  | 5594/7111 [21:57<04:50,  5.22it/s]

Reports:  79%|███████▊  | 5595/7111 [21:57<04:53,  5.17it/s]

Reports:  79%|███████▊  | 5596/7111 [21:57<04:50,  5.22it/s]

Reports:  79%|███████▊  | 5597/7111 [21:58<04:53,  5.17it/s]

Reports:  79%|███████▊  | 5598/7111 [21:58<04:52,  5.17it/s]

Reports:  79%|███████▊  | 5599/7111 [21:58<04:51,  5.18it/s]

Reports:  79%|███████▉  | 5600/7111 [21:58<04:58,  5.06it/s]

Reports:  79%|███████▉  | 5601/7111 [21:58<04:59,  5.05it/s]

Reports:  79%|███████▉  | 5602/7111 [21:59<04:53,  5.14it/s]

Reports:  79%|███████▉  | 5603/7111 [21:59<04:50,  5.20it/s]

Reports:  79%|███████▉  | 5604/7111 [21:59<04:51,  5.18it/s]

Reports:  79%|███████▉  | 5605/7111 [21:59<04:50,  5.18it/s]

Reports:  79%|███████▉  | 5606/7111 [21:59<04:49,  5.19it/s]

Reports:  79%|███████▉  | 5607/7111 [22:00<04:48,  5.21it/s]

Reports:  79%|███████▉  | 5608/7111 [22:00<04:49,  5.19it/s]

Reports:  79%|███████▉  | 5609/7111 [22:00<04:52,  5.13it/s]

Reports:  79%|███████▉  | 5610/7111 [22:00<04:55,  5.09it/s]

Reports:  79%|███████▉  | 5611/7111 [22:00<04:52,  5.13it/s]

Reports:  79%|███████▉  | 5612/7111 [22:01<04:46,  5.23it/s]

Reports:  79%|███████▉  | 5613/7111 [22:01<04:48,  5.19it/s]

Reports:  79%|███████▉  | 5614/7111 [22:01<04:48,  5.19it/s]

Reports:  79%|███████▉  | 5615/7111 [22:01<04:47,  5.21it/s]

Reports:  79%|███████▉  | 5616/7111 [22:01<04:47,  5.21it/s]

Reports:  79%|███████▉  | 5617/7111 [22:02<04:44,  5.26it/s]

Reports:  79%|███████▉  | 5618/7111 [22:02<04:43,  5.26it/s]

Reports:  79%|███████▉  | 5619/7111 [22:02<04:40,  5.32it/s]

Reports:  79%|███████▉  | 5620/7111 [22:02<04:44,  5.24it/s]

Reports:  79%|███████▉  | 5621/7111 [22:02<04:44,  5.23it/s]

Reports:  79%|███████▉  | 5622/7111 [22:02<04:42,  5.28it/s]

Reports:  79%|███████▉  | 5623/7111 [22:03<04:41,  5.28it/s]

Reports:  79%|███████▉  | 5624/7111 [22:03<04:49,  5.14it/s]

Reports:  79%|███████▉  | 5625/7111 [22:03<04:43,  5.23it/s]

Reports:  79%|███████▉  | 5626/7111 [22:03<04:46,  5.18it/s]

Reports:  79%|███████▉  | 5627/7111 [22:03<04:44,  5.21it/s]

Reports:  79%|███████▉  | 5628/7111 [22:04<04:47,  5.17it/s]

Reports:  79%|███████▉  | 5629/7111 [22:04<04:45,  5.20it/s]

Reports:  79%|███████▉  | 5630/7111 [22:04<04:43,  5.22it/s]

Reports:  79%|███████▉  | 5631/7111 [22:04<04:45,  5.18it/s]

Reports:  79%|███████▉  | 5632/7111 [22:04<04:49,  5.11it/s]

Reports:  79%|███████▉  | 5633/7111 [22:05<04:48,  5.12it/s]

Reports:  79%|███████▉  | 5634/7111 [22:05<04:54,  5.02it/s]

Reports:  79%|███████▉  | 5635/7111 [22:05<04:48,  5.12it/s]

Reports:  79%|███████▉  | 5636/7111 [22:05<04:48,  5.12it/s]

Reports:  79%|███████▉  | 5637/7111 [22:05<04:46,  5.15it/s]

Reports:  79%|███████▉  | 5638/7111 [22:06<04:43,  5.20it/s]

Reports:  79%|███████▉  | 5639/7111 [22:06<04:46,  5.15it/s]

Reports:  79%|███████▉  | 5640/7111 [22:06<04:50,  5.06it/s]

Reports:  79%|███████▉  | 5641/7111 [22:06<04:46,  5.12it/s]

Reports:  79%|███████▉  | 5642/7111 [22:06<04:47,  5.11it/s]

Reports:  79%|███████▉  | 5643/7111 [22:07<04:47,  5.10it/s]

Reports:  79%|███████▉  | 5644/7111 [22:07<04:43,  5.18it/s]

Reports:  79%|███████▉  | 5645/7111 [22:07<04:41,  5.20it/s]

Reports:  79%|███████▉  | 5646/7111 [22:07<04:48,  5.09it/s]

Reports:  79%|███████▉  | 5647/7111 [22:07<04:43,  5.17it/s]

Reports:  79%|███████▉  | 5648/7111 [22:08<04:41,  5.19it/s]

Reports:  79%|███████▉  | 5649/7111 [22:08<04:47,  5.08it/s]

Reports:  79%|███████▉  | 5650/7111 [22:08<04:44,  5.14it/s]

Reports:  79%|███████▉  | 5651/7111 [22:08<04:49,  5.05it/s]

Reports:  79%|███████▉  | 5652/7111 [22:08<04:45,  5.10it/s]

Reports:  79%|███████▉  | 5653/7111 [22:08<04:46,  5.08it/s]

Reports:  80%|███████▉  | 5654/7111 [22:09<04:41,  5.17it/s]

Reports:  80%|███████▉  | 5655/7111 [22:09<04:41,  5.18it/s]

Reports:  80%|███████▉  | 5656/7111 [22:09<04:41,  5.17it/s]

Reports:  80%|███████▉  | 5657/7111 [22:09<04:45,  5.09it/s]

Reports:  80%|███████▉  | 5658/7111 [22:09<04:49,  5.01it/s]

Reports:  80%|███████▉  | 5659/7111 [22:10<04:44,  5.11it/s]

Reports:  80%|███████▉  | 5660/7111 [22:10<04:46,  5.07it/s]

Reports:  80%|███████▉  | 5661/7111 [22:10<04:43,  5.11it/s]

Reports:  80%|███████▉  | 5662/7111 [22:10<04:40,  5.17it/s]

Reports:  80%|███████▉  | 5663/7111 [22:10<04:39,  5.17it/s]

Reports:  80%|███████▉  | 5664/7111 [22:11<04:37,  5.21it/s]

Reports:  80%|███████▉  | 5665/7111 [22:11<04:34,  5.26it/s]

Reports:  80%|███████▉  | 5666/7111 [22:11<04:32,  5.29it/s]

Reports:  80%|███████▉  | 5667/7111 [22:11<04:32,  5.29it/s]

Reports:  80%|███████▉  | 5668/7111 [22:11<04:31,  5.32it/s]

Reports:  80%|███████▉  | 5669/7111 [22:12<04:31,  5.31it/s]

Reports:  80%|███████▉  | 5670/7111 [22:12<04:30,  5.32it/s]

Reports:  80%|███████▉  | 5671/7111 [22:12<04:29,  5.35it/s]

Reports:  80%|███████▉  | 5672/7111 [22:12<04:33,  5.26it/s]

Reports:  80%|███████▉  | 5673/7111 [22:12<04:34,  5.24it/s]

Reports:  80%|███████▉  | 5674/7111 [22:13<04:33,  5.26it/s]

Reports:  80%|███████▉  | 5675/7111 [22:13<04:36,  5.20it/s]

Reports:  80%|███████▉  | 5676/7111 [22:13<04:35,  5.20it/s]

Reports:  80%|███████▉  | 5677/7111 [22:13<04:39,  5.14it/s]

Reports:  80%|███████▉  | 5678/7111 [22:13<04:43,  5.05it/s]

Reports:  80%|███████▉  | 5679/7111 [22:13<04:38,  5.15it/s]

Reports:  80%|███████▉  | 5680/7111 [22:14<04:42,  5.07it/s]

Reports:  80%|███████▉  | 5681/7111 [22:14<04:41,  5.08it/s]

Reports:  80%|███████▉  | 5682/7111 [22:14<04:39,  5.11it/s]

Reports:  80%|███████▉  | 5683/7111 [22:14<04:35,  5.19it/s]

Reports:  80%|███████▉  | 5684/7111 [22:14<04:39,  5.11it/s]

Reports:  80%|███████▉  | 5685/7111 [22:15<04:37,  5.14it/s]

Reports:  80%|███████▉  | 5686/7111 [22:15<04:39,  5.11it/s]

Reports:  80%|███████▉  | 5687/7111 [22:15<04:36,  5.15it/s]

Reports:  80%|███████▉  | 5688/7111 [22:15<04:32,  5.22it/s]

Reports:  80%|████████  | 5689/7111 [22:15<04:30,  5.26it/s]

Reports:  80%|████████  | 5690/7111 [22:16<04:36,  5.13it/s]

Reports:  80%|████████  | 5691/7111 [22:16<04:38,  5.10it/s]

Reports:  80%|████████  | 5692/7111 [22:16<04:37,  5.12it/s]

Reports:  80%|████████  | 5693/7111 [22:16<04:34,  5.17it/s]

Reports:  80%|████████  | 5694/7111 [22:16<04:29,  5.25it/s]

Reports:  80%|████████  | 5695/7111 [22:17<04:41,  5.02it/s]

Reports:  80%|████████  | 5696/7111 [22:17<04:40,  5.05it/s]

Reports:  80%|████████  | 5697/7111 [22:17<04:43,  4.99it/s]

Reports:  80%|████████  | 5698/7111 [22:17<04:40,  5.03it/s]

Reports:  80%|████████  | 5699/7111 [22:17<04:43,  4.98it/s]

Reports:  80%|████████  | 5700/7111 [22:18<04:42,  5.00it/s]

Reports:  80%|████████  | 5701/7111 [22:18<04:53,  4.81it/s]

Reports:  80%|████████  | 5702/7111 [22:19<09:07,  2.57it/s]

Reports:  80%|████████  | 5703/7111 [22:19<07:48,  3.01it/s]

Reports:  80%|████████  | 5704/7111 [22:19<06:55,  3.39it/s]

Reports:  80%|████████  | 5705/7111 [22:19<06:09,  3.81it/s]

Reports:  80%|████████  | 5706/7111 [22:19<05:37,  4.17it/s]

Reports:  80%|████████  | 5707/7111 [22:20<05:14,  4.47it/s]

Reports:  80%|████████  | 5708/7111 [22:20<05:04,  4.60it/s]

Reports:  80%|████████  | 5709/7111 [22:20<04:52,  4.80it/s]

Reports:  80%|████████  | 5710/7111 [22:20<04:49,  4.85it/s]

Reports:  80%|████████  | 5711/7111 [22:20<04:39,  5.01it/s]

Reports:  80%|████████  | 5712/7111 [22:21<04:43,  4.93it/s]

Reports:  80%|████████  | 5713/7111 [22:21<04:45,  4.89it/s]

Reports:  80%|████████  | 5714/7111 [22:21<04:43,  4.93it/s]

Reports:  80%|████████  | 5715/7111 [22:21<04:44,  4.90it/s]

Reports:  80%|████████  | 5716/7111 [22:21<04:40,  4.97it/s]

Reports:  80%|████████  | 5717/7111 [22:22<04:37,  5.03it/s]

Reports:  80%|████████  | 5718/7111 [22:22<04:30,  5.14it/s]

Reports:  80%|████████  | 5719/7111 [22:22<04:30,  5.14it/s]

Reports:  80%|████████  | 5720/7111 [22:22<04:31,  5.13it/s]

Reports:  80%|████████  | 5721/7111 [22:22<04:34,  5.07it/s]

Reports:  80%|████████  | 5722/7111 [22:23<04:32,  5.11it/s]

Reports:  80%|████████  | 5723/7111 [22:23<04:30,  5.13it/s]

Reports:  80%|████████  | 5724/7111 [22:23<04:30,  5.13it/s]

Reports:  81%|████████  | 5725/7111 [22:23<04:31,  5.10it/s]

Reports:  81%|████████  | 5726/7111 [22:23<04:35,  5.03it/s]

Reports:  81%|████████  | 5727/7111 [22:24<04:31,  5.09it/s]

Reports:  81%|████████  | 5728/7111 [22:24<04:28,  5.15it/s]

Reports:  81%|████████  | 5729/7111 [22:24<04:28,  5.16it/s]

Reports:  81%|████████  | 5730/7111 [22:24<04:25,  5.20it/s]

Reports:  81%|████████  | 5731/7111 [22:24<04:29,  5.13it/s]

Reports:  81%|████████  | 5732/7111 [22:25<04:30,  5.10it/s]

Reports:  81%|████████  | 5733/7111 [22:25<04:27,  5.14it/s]

Reports:  81%|████████  | 5734/7111 [22:25<04:28,  5.14it/s]

Reports:  81%|████████  | 5735/7111 [22:25<04:30,  5.08it/s]

Reports:  81%|████████  | 5736/7111 [22:25<04:29,  5.10it/s]

Reports:  81%|████████  | 5737/7111 [22:26<04:26,  5.16it/s]

Reports:  81%|████████  | 5738/7111 [22:26<04:23,  5.20it/s]

Reports:  81%|████████  | 5739/7111 [22:26<04:24,  5.18it/s]

Reports:  81%|████████  | 5740/7111 [22:26<04:24,  5.19it/s]

Reports:  81%|████████  | 5741/7111 [22:26<04:24,  5.17it/s]

Reports:  81%|████████  | 5742/7111 [22:26<04:25,  5.16it/s]

Reports:  81%|████████  | 5743/7111 [22:27<04:26,  5.14it/s]

Reports:  81%|████████  | 5744/7111 [22:27<04:28,  5.10it/s]

Reports:  81%|████████  | 5745/7111 [22:27<04:27,  5.11it/s]

Reports:  81%|████████  | 5746/7111 [22:27<04:26,  5.11it/s]

Reports:  81%|████████  | 5747/7111 [22:27<04:22,  5.20it/s]

Reports:  81%|████████  | 5748/7111 [22:28<04:22,  5.20it/s]

Reports:  81%|████████  | 5749/7111 [22:28<04:23,  5.16it/s]

Reports:  81%|████████  | 5750/7111 [22:28<04:21,  5.20it/s]

Reports:  81%|████████  | 5751/7111 [22:28<04:24,  5.14it/s]

Reports:  81%|████████  | 5752/7111 [22:28<04:34,  4.96it/s]

Reports:  81%|████████  | 5753/7111 [22:29<04:29,  5.03it/s]

Reports:  81%|████████  | 5754/7111 [22:29<04:24,  5.14it/s]

Reports:  81%|████████  | 5755/7111 [22:29<04:29,  5.03it/s]

Reports:  81%|████████  | 5756/7111 [22:29<04:24,  5.12it/s]

Reports:  81%|████████  | 5757/7111 [22:29<04:21,  5.18it/s]

Reports:  81%|████████  | 5758/7111 [22:30<04:18,  5.23it/s]

Reports:  81%|████████  | 5759/7111 [22:30<04:17,  5.24it/s]

Reports:  81%|████████  | 5760/7111 [22:30<05:50,  3.85it/s]

Reports:  81%|████████  | 5761/7111 [22:30<05:26,  4.13it/s]

Reports:  81%|████████  | 5762/7111 [22:31<05:06,  4.39it/s]

Reports:  81%|████████  | 5763/7111 [22:31<05:23,  4.17it/s]

Reports:  81%|████████  | 5764/7111 [22:31<05:01,  4.46it/s]

Reports:  81%|████████  | 5765/7111 [22:31<04:56,  4.53it/s]

Reports:  81%|████████  | 5766/7111 [22:32<05:34,  4.02it/s]

Reports:  81%|████████  | 5767/7111 [22:32<05:29,  4.07it/s]

Reports:  81%|████████  | 5768/7111 [22:32<05:29,  4.08it/s]

Reports:  81%|████████  | 5769/7111 [22:32<05:25,  4.13it/s]

Reports:  81%|████████  | 5770/7111 [22:32<05:09,  4.33it/s]

Reports:  81%|████████  | 5771/7111 [22:33<04:57,  4.50it/s]

Reports:  81%|████████  | 5772/7111 [22:33<04:43,  4.72it/s]

Reports:  81%|████████  | 5773/7111 [22:33<04:37,  4.83it/s]

Reports:  81%|████████  | 5774/7111 [22:33<04:29,  4.97it/s]

Reports:  81%|████████  | 5775/7111 [22:33<04:24,  5.05it/s]

Reports:  81%|████████  | 5776/7111 [22:34<04:27,  5.00it/s]

Reports:  81%|████████  | 5777/7111 [22:34<04:26,  5.01it/s]

Reports:  81%|████████▏ | 5778/7111 [22:34<04:21,  5.10it/s]

Reports:  81%|████████▏ | 5779/7111 [22:34<04:19,  5.13it/s]

Reports:  81%|████████▏ | 5780/7111 [22:34<04:14,  5.22it/s]

Reports:  81%|████████▏ | 5781/7111 [22:35<04:41,  4.73it/s]

Reports:  81%|████████▏ | 5782/7111 [22:35<04:32,  4.88it/s]

Reports:  81%|████████▏ | 5783/7111 [22:35<04:25,  5.01it/s]

Reports:  81%|████████▏ | 5784/7111 [22:35<04:21,  5.08it/s]

Reports:  81%|████████▏ | 5785/7111 [22:35<04:16,  5.17it/s]

Reports:  81%|████████▏ | 5786/7111 [22:36<04:14,  5.21it/s]

Reports:  81%|████████▏ | 5787/7111 [22:36<04:18,  5.12it/s]

Reports:  81%|████████▏ | 5788/7111 [22:36<04:23,  5.03it/s]

Reports:  81%|████████▏ | 5789/7111 [22:36<04:20,  5.08it/s]

Reports:  81%|████████▏ | 5790/7111 [22:36<04:16,  5.14it/s]

Reports:  81%|████████▏ | 5791/7111 [22:37<04:16,  5.16it/s]

Reports:  81%|████████▏ | 5792/7111 [22:37<04:10,  5.26it/s]

Reports:  81%|████████▏ | 5793/7111 [22:37<04:11,  5.24it/s]

Reports:  81%|████████▏ | 5794/7111 [22:37<04:10,  5.26it/s]

Reports:  81%|████████▏ | 5795/7111 [22:37<04:10,  5.25it/s]

Reports:  82%|████████▏ | 5796/7111 [22:38<04:09,  5.28it/s]

Reports:  82%|████████▏ | 5797/7111 [22:38<04:13,  5.19it/s]

Reports:  82%|████████▏ | 5798/7111 [22:38<04:11,  5.23it/s]

Reports:  82%|████████▏ | 5799/7111 [22:38<04:12,  5.19it/s]

Reports:  82%|████████▏ | 5800/7111 [22:38<04:16,  5.10it/s]

Reports:  82%|████████▏ | 5801/7111 [22:39<04:12,  5.18it/s]

Reports:  82%|████████▏ | 5802/7111 [22:39<04:20,  5.03it/s]

Reports:  82%|████████▏ | 5803/7111 [22:39<04:16,  5.09it/s]

Reports:  82%|████████▏ | 5804/7111 [22:39<04:15,  5.11it/s]

Reports:  82%|████████▏ | 5805/7111 [22:39<04:09,  5.23it/s]

Reports:  82%|████████▏ | 5806/7111 [22:39<04:09,  5.24it/s]

Reports:  82%|████████▏ | 5807/7111 [22:40<04:08,  5.26it/s]

Reports:  82%|████████▏ | 5808/7111 [22:40<04:05,  5.31it/s]

Reports:  82%|████████▏ | 5809/7111 [22:40<04:05,  5.31it/s]

Reports:  82%|████████▏ | 5810/7111 [22:40<04:03,  5.34it/s]

Reports:  82%|████████▏ | 5811/7111 [22:40<04:07,  5.25it/s]

Reports:  82%|████████▏ | 5812/7111 [22:41<04:06,  5.27it/s]

Reports:  82%|████████▏ | 5813/7111 [22:41<04:05,  5.29it/s]

Reports:  82%|████████▏ | 5814/7111 [22:41<04:12,  5.14it/s]

Reports:  82%|████████▏ | 5815/7111 [22:41<04:09,  5.19it/s]

Reports:  82%|████████▏ | 5816/7111 [22:41<04:16,  5.06it/s]

Reports:  82%|████████▏ | 5817/7111 [22:42<04:22,  4.94it/s]

Reports:  82%|████████▏ | 5818/7111 [22:42<04:20,  4.96it/s]

Reports:  82%|████████▏ | 5819/7111 [22:42<04:22,  4.93it/s]

Reports:  82%|████████▏ | 5820/7111 [22:42<04:19,  4.98it/s]

Reports:  82%|████████▏ | 5821/7111 [22:42<04:17,  5.01it/s]

Reports:  82%|████████▏ | 5822/7111 [22:43<04:16,  5.02it/s]

Reports:  82%|████████▏ | 5823/7111 [22:43<04:20,  4.95it/s]

Reports:  82%|████████▏ | 5824/7111 [22:43<04:18,  4.98it/s]

Reports:  82%|████████▏ | 5825/7111 [22:43<04:20,  4.93it/s]

Reports:  82%|████████▏ | 5826/7111 [22:43<04:15,  5.03it/s]

Reports:  82%|████████▏ | 5827/7111 [22:44<04:13,  5.06it/s]

Reports:  82%|████████▏ | 5828/7111 [22:44<04:14,  5.03it/s]

Reports:  82%|████████▏ | 5829/7111 [22:44<04:14,  5.04it/s]

Reports:  82%|████████▏ | 5830/7111 [22:44<04:22,  4.89it/s]

Reports:  82%|████████▏ | 5831/7111 [22:44<04:14,  5.02it/s]

Reports:  82%|████████▏ | 5832/7111 [22:45<04:12,  5.07it/s]

Reports:  82%|████████▏ | 5833/7111 [22:45<04:14,  5.03it/s]

Reports:  82%|████████▏ | 5834/7111 [22:45<04:09,  5.11it/s]

Reports:  82%|████████▏ | 5835/7111 [22:45<04:06,  5.17it/s]

Reports:  82%|████████▏ | 5836/7111 [22:45<04:06,  5.17it/s]

Reports:  82%|████████▏ | 5837/7111 [22:46<04:05,  5.20it/s]

Reports:  82%|████████▏ | 5838/7111 [22:46<04:05,  5.18it/s]

Reports:  82%|████████▏ | 5839/7111 [22:46<06:06,  3.47it/s]

Reports:  82%|████████▏ | 5840/7111 [22:46<05:26,  3.89it/s]

Reports:  82%|████████▏ | 5841/7111 [22:47<05:02,  4.19it/s]

Reports:  82%|████████▏ | 5842/7111 [22:47<04:46,  4.42it/s]

Reports:  82%|████████▏ | 5843/7111 [22:47<04:32,  4.65it/s]

Reports:  82%|████████▏ | 5844/7111 [22:47<04:25,  4.76it/s]

Reports:  82%|████████▏ | 5845/7111 [22:47<04:24,  4.78it/s]

Reports:  82%|████████▏ | 5846/7111 [22:48<04:19,  4.88it/s]

Reports:  82%|████████▏ | 5847/7111 [22:48<04:17,  4.92it/s]

Reports:  82%|████████▏ | 5848/7111 [22:48<04:11,  5.03it/s]

Reports:  82%|████████▏ | 5849/7111 [22:48<04:07,  5.10it/s]

Reports:  82%|████████▏ | 5850/7111 [22:48<04:06,  5.11it/s]

Reports:  82%|████████▏ | 5851/7111 [22:49<04:04,  5.15it/s]

Reports:  82%|████████▏ | 5852/7111 [22:49<04:05,  5.13it/s]

Reports:  82%|████████▏ | 5853/7111 [22:49<04:02,  5.18it/s]

Reports:  82%|████████▏ | 5854/7111 [22:49<03:59,  5.25it/s]

Reports:  82%|████████▏ | 5855/7111 [22:49<03:58,  5.28it/s]

Reports:  82%|████████▏ | 5856/7111 [22:50<04:00,  5.23it/s]

Reports:  82%|████████▏ | 5857/7111 [22:50<03:58,  5.25it/s]

Reports:  82%|████████▏ | 5858/7111 [22:50<03:56,  5.30it/s]

Reports:  82%|████████▏ | 5859/7111 [22:50<03:56,  5.30it/s]

Reports:  82%|████████▏ | 5860/7111 [22:50<03:57,  5.26it/s]

Reports:  82%|████████▏ | 5861/7111 [22:51<04:01,  5.17it/s]

Reports:  82%|████████▏ | 5862/7111 [22:51<04:02,  5.16it/s]

Reports:  82%|████████▏ | 5863/7111 [22:51<04:00,  5.19it/s]

Reports:  82%|████████▏ | 5864/7111 [22:51<04:03,  5.13it/s]

Reports:  82%|████████▏ | 5865/7111 [22:51<04:06,  5.06it/s]

Reports:  82%|████████▏ | 5866/7111 [22:52<04:09,  4.99it/s]

Reports:  83%|████████▎ | 5867/7111 [22:52<04:05,  5.06it/s]

Reports:  83%|████████▎ | 5868/7111 [22:52<04:01,  5.16it/s]

Reports:  83%|████████▎ | 5869/7111 [22:52<04:06,  5.05it/s]

Reports:  83%|████████▎ | 5870/7111 [22:52<04:04,  5.07it/s]

Reports:  83%|████████▎ | 5871/7111 [22:53<04:07,  5.01it/s]

Reports:  83%|████████▎ | 5872/7111 [22:53<04:01,  5.13it/s]

Reports:  83%|████████▎ | 5873/7111 [22:53<04:07,  5.00it/s]

Reports:  83%|████████▎ | 5874/7111 [22:53<04:08,  4.98it/s]

Reports:  83%|████████▎ | 5875/7111 [22:53<04:07,  4.98it/s]

Reports:  83%|████████▎ | 5876/7111 [22:54<04:05,  5.02it/s]

Reports:  83%|████████▎ | 5877/7111 [22:54<04:03,  5.08it/s]

Reports:  83%|████████▎ | 5878/7111 [22:54<03:56,  5.21it/s]

Reports:  83%|████████▎ | 5879/7111 [22:54<03:56,  5.21it/s]

Reports:  83%|████████▎ | 5880/7111 [22:54<04:00,  5.11it/s]

Reports:  83%|████████▎ | 5881/7111 [22:54<04:04,  5.04it/s]

Reports:  83%|████████▎ | 5882/7111 [22:55<03:59,  5.12it/s]

Reports:  83%|████████▎ | 5883/7111 [22:55<03:59,  5.12it/s]

Reports:  83%|████████▎ | 5884/7111 [22:55<03:57,  5.17it/s]

Reports:  83%|████████▎ | 5885/7111 [22:55<04:00,  5.10it/s]

Reports:  83%|████████▎ | 5886/7111 [22:55<03:54,  5.22it/s]

Reports:  83%|████████▎ | 5887/7111 [22:56<03:58,  5.14it/s]

Reports:  83%|████████▎ | 5888/7111 [22:56<03:57,  5.16it/s]

Reports:  83%|████████▎ | 5889/7111 [22:56<03:54,  5.21it/s]

Reports:  83%|████████▎ | 5890/7111 [22:56<03:56,  5.15it/s]

Reports:  83%|████████▎ | 5891/7111 [22:56<03:55,  5.17it/s]

Reports:  83%|████████▎ | 5892/7111 [22:57<03:58,  5.11it/s]

Reports:  83%|████████▎ | 5893/7111 [22:57<03:59,  5.09it/s]

Reports:  83%|████████▎ | 5894/7111 [22:57<03:57,  5.12it/s]

Reports:  83%|████████▎ | 5895/7111 [22:57<04:02,  5.01it/s]

Reports:  83%|████████▎ | 5896/7111 [22:57<04:00,  5.06it/s]

Reports:  83%|████████▎ | 5897/7111 [22:58<03:55,  5.16it/s]

Reports:  83%|████████▎ | 5898/7111 [22:58<03:55,  5.16it/s]

Reports:  83%|████████▎ | 5899/7111 [22:58<03:54,  5.17it/s]

Reports:  83%|████████▎ | 5900/7111 [22:58<03:56,  5.12it/s]

Reports:  83%|████████▎ | 5901/7111 [22:58<03:53,  5.19it/s]

Reports:  83%|████████▎ | 5902/7111 [22:59<03:55,  5.13it/s]

Reports:  83%|████████▎ | 5903/7111 [22:59<03:54,  5.14it/s]

Reports:  83%|████████▎ | 5904/7111 [22:59<03:56,  5.10it/s]

Reports:  83%|████████▎ | 5905/7111 [22:59<03:55,  5.12it/s]

Reports:  83%|████████▎ | 5906/7111 [22:59<03:59,  5.04it/s]

Reports:  83%|████████▎ | 5907/7111 [23:00<04:02,  4.97it/s]

Reports:  83%|████████▎ | 5908/7111 [23:00<03:59,  5.02it/s]

Reports:  83%|████████▎ | 5909/7111 [23:00<03:55,  5.10it/s]

Reports:  83%|████████▎ | 5910/7111 [23:00<03:55,  5.11it/s]

Reports:  83%|████████▎ | 5911/7111 [23:00<03:51,  5.18it/s]

Reports:  83%|████████▎ | 5912/7111 [23:01<03:52,  5.15it/s]

Reports:  83%|████████▎ | 5913/7111 [23:01<03:52,  5.15it/s]

Reports:  83%|████████▎ | 5914/7111 [23:01<03:57,  5.05it/s]

Reports:  83%|████████▎ | 5915/7111 [23:01<03:54,  5.09it/s]

Reports:  83%|████████▎ | 5916/7111 [23:01<03:51,  5.17it/s]

Reports:  83%|████████▎ | 5917/7111 [23:01<03:48,  5.22it/s]

Reports:  83%|████████▎ | 5918/7111 [23:02<03:46,  5.27it/s]

Reports:  83%|████████▎ | 5919/7111 [23:02<03:46,  5.27it/s]

Reports:  83%|████████▎ | 5920/7111 [23:02<03:46,  5.26it/s]

Reports:  83%|████████▎ | 5921/7111 [23:02<03:51,  5.13it/s]

Reports:  83%|████████▎ | 5922/7111 [23:02<03:51,  5.13it/s]

Reports:  83%|████████▎ | 5923/7111 [23:03<03:51,  5.14it/s]

Reports:  83%|████████▎ | 5924/7111 [23:03<03:54,  5.07it/s]

Reports:  83%|████████▎ | 5925/7111 [23:03<03:49,  5.17it/s]

Reports:  83%|████████▎ | 5926/7111 [23:03<03:47,  5.22it/s]

Reports:  83%|████████▎ | 5927/7111 [23:03<03:56,  5.01it/s]

Reports:  83%|████████▎ | 5928/7111 [23:04<03:53,  5.06it/s]

Reports:  83%|████████▎ | 5929/7111 [23:04<03:49,  5.16it/s]

Reports:  83%|████████▎ | 5930/7111 [23:04<03:48,  5.17it/s]

Reports:  83%|████████▎ | 5931/7111 [23:04<03:48,  5.16it/s]

Reports:  83%|████████▎ | 5932/7111 [23:04<03:46,  5.19it/s]

Reports:  83%|████████▎ | 5933/7111 [23:05<03:50,  5.12it/s]

Reports:  83%|████████▎ | 5934/7111 [23:05<03:48,  5.16it/s]

Reports:  83%|████████▎ | 5935/7111 [23:05<03:44,  5.23it/s]

Reports:  83%|████████▎ | 5936/7111 [23:05<03:44,  5.24it/s]

Reports:  83%|████████▎ | 5937/7111 [23:05<03:47,  5.15it/s]

Reports:  84%|████████▎ | 5938/7111 [23:06<03:49,  5.12it/s]

Reports:  84%|████████▎ | 5939/7111 [23:06<03:47,  5.16it/s]

Reports:  84%|████████▎ | 5940/7111 [23:06<03:50,  5.09it/s]

Reports:  84%|████████▎ | 5941/7111 [23:06<03:47,  5.14it/s]

Reports:  84%|████████▎ | 5942/7111 [23:06<03:50,  5.08it/s]

Reports:  84%|████████▎ | 5943/7111 [23:07<03:50,  5.07it/s]

Reports:  84%|████████▎ | 5944/7111 [23:07<03:50,  5.05it/s]

Reports:  84%|████████▎ | 5945/7111 [23:07<03:52,  5.01it/s]

Reports:  84%|████████▎ | 5946/7111 [23:07<03:49,  5.08it/s]

Reports:  84%|████████▎ | 5947/7111 [23:07<03:47,  5.11it/s]

Reports:  84%|████████▎ | 5948/7111 [23:08<03:47,  5.12it/s]

Reports:  84%|████████▎ | 5949/7111 [23:08<03:45,  5.15it/s]

Reports:  84%|████████▎ | 5950/7111 [23:08<03:45,  5.15it/s]

Reports:  84%|████████▎ | 5951/7111 [23:08<03:48,  5.08it/s]

Reports:  84%|████████▎ | 5952/7111 [23:08<03:46,  5.13it/s]

Reports:  84%|████████▎ | 5953/7111 [23:08<03:43,  5.18it/s]

Reports:  84%|████████▎ | 5954/7111 [23:09<03:41,  5.23it/s]

Reports:  84%|████████▎ | 5955/7111 [23:09<03:44,  5.15it/s]

Reports:  84%|████████▍ | 5956/7111 [23:09<03:43,  5.18it/s]

Reports:  84%|████████▍ | 5957/7111 [23:09<03:41,  5.22it/s]

Reports:  84%|████████▍ | 5958/7111 [23:09<03:42,  5.18it/s]

Reports:  84%|████████▍ | 5959/7111 [23:10<03:44,  5.13it/s]

Reports:  84%|████████▍ | 5960/7111 [23:10<03:37,  5.29it/s]

Reports:  84%|████████▍ | 5961/7111 [23:10<03:42,  5.17it/s]

Reports:  84%|████████▍ | 5962/7111 [23:10<03:43,  5.15it/s]

Reports:  84%|████████▍ | 5963/7111 [23:10<03:44,  5.10it/s]

Reports:  84%|████████▍ | 5964/7111 [23:12<10:37,  1.80it/s]

Reports:  84%|████████▍ | 5965/7111 [23:12<08:36,  2.22it/s]

Reports:  84%|████████▍ | 5966/7111 [23:12<07:12,  2.65it/s]

Reports:  84%|████████▍ | 5967/7111 [23:12<06:08,  3.11it/s]

Reports:  84%|████████▍ | 5968/7111 [23:13<05:27,  3.49it/s]

Reports:  84%|████████▍ | 5969/7111 [23:13<04:55,  3.87it/s]

Reports:  84%|████████▍ | 5970/7111 [23:13<04:32,  4.19it/s]

Reports:  84%|████████▍ | 5971/7111 [23:13<04:14,  4.49it/s]

Reports:  84%|████████▍ | 5972/7111 [23:13<04:04,  4.65it/s]

Reports:  84%|████████▍ | 5973/7111 [23:14<03:55,  4.83it/s]

Reports:  84%|████████▍ | 5974/7111 [23:14<03:51,  4.92it/s]

Reports:  84%|████████▍ | 5975/7111 [23:14<03:45,  5.05it/s]

Reports:  84%|████████▍ | 5976/7111 [23:14<03:43,  5.08it/s]

Reports:  84%|████████▍ | 5977/7111 [23:14<03:47,  4.98it/s]

Reports:  84%|████████▍ | 5978/7111 [23:15<03:47,  4.98it/s]

Reports:  84%|████████▍ | 5979/7111 [23:15<03:45,  5.02it/s]

Reports:  84%|████████▍ | 5980/7111 [23:15<03:40,  5.13it/s]

Reports:  84%|████████▍ | 5981/7111 [23:15<03:36,  5.23it/s]

Reports:  84%|████████▍ | 5982/7111 [23:15<03:40,  5.11it/s]

Reports:  84%|████████▍ | 5983/7111 [23:16<03:40,  5.13it/s]

Reports:  84%|████████▍ | 5984/7111 [23:16<03:37,  5.17it/s]

Reports:  84%|████████▍ | 5985/7111 [23:16<03:38,  5.16it/s]

Reports:  84%|████████▍ | 5986/7111 [23:16<03:40,  5.10it/s]

Reports:  84%|████████▍ | 5987/7111 [23:16<03:40,  5.10it/s]

Reports:  84%|████████▍ | 5988/7111 [23:17<03:44,  5.01it/s]

Reports:  84%|████████▍ | 5989/7111 [23:17<07:32,  2.48it/s]

Reports:  84%|████████▍ | 5990/7111 [23:18<06:24,  2.91it/s]

Reports:  84%|████████▍ | 5991/7111 [23:18<05:35,  3.34it/s]

Reports:  84%|████████▍ | 5992/7111 [23:18<04:56,  3.78it/s]

Reports:  84%|████████▍ | 5993/7111 [23:18<04:35,  4.05it/s]

Reports:  84%|████████▍ | 5994/7111 [23:18<04:16,  4.35it/s]

Reports:  84%|████████▍ | 5995/7111 [23:19<04:02,  4.60it/s]

Reports:  84%|████████▍ | 5996/7111 [23:19<03:58,  4.68it/s]

Reports:  84%|████████▍ | 5997/7111 [23:19<03:50,  4.83it/s]

Reports:  84%|████████▍ | 5998/7111 [23:19<03:49,  4.86it/s]

Reports:  84%|████████▍ | 5999/7111 [23:19<03:42,  4.99it/s]

Reports:  84%|████████▍ | 6000/7111 [23:20<03:39,  5.05it/s]

Reports:  84%|████████▍ | 6001/7111 [23:20<03:37,  5.11it/s]

Reports:  84%|████████▍ | 6002/7111 [23:20<03:35,  5.14it/s]

Reports:  84%|████████▍ | 6003/7111 [23:20<03:34,  5.17it/s]

Reports:  84%|████████▍ | 6004/7111 [23:20<03:34,  5.17it/s]

Reports:  84%|████████▍ | 6005/7111 [23:21<03:38,  5.06it/s]

Reports:  84%|████████▍ | 6006/7111 [23:21<03:36,  5.10it/s]

Reports:  84%|████████▍ | 6007/7111 [23:21<03:35,  5.11it/s]

Reports:  84%|████████▍ | 6008/7111 [23:21<03:36,  5.10it/s]

Reports:  85%|████████▍ | 6009/7111 [23:21<03:38,  5.04it/s]

Reports:  85%|████████▍ | 6010/7111 [23:22<03:37,  5.07it/s]

Reports:  85%|████████▍ | 6011/7111 [23:22<03:40,  5.00it/s]

Reports:  85%|████████▍ | 6012/7111 [23:22<03:38,  5.04it/s]

Reports:  85%|████████▍ | 6013/7111 [23:22<03:36,  5.07it/s]

Reports:  85%|████████▍ | 6014/7111 [23:22<03:37,  5.03it/s]

Reports:  85%|████████▍ | 6015/7111 [23:23<03:38,  5.02it/s]

Reports:  85%|████████▍ | 6016/7111 [23:23<03:36,  5.05it/s]

Reports:  85%|████████▍ | 6017/7111 [23:23<03:41,  4.94it/s]

Reports:  85%|████████▍ | 6018/7111 [23:23<03:43,  4.89it/s]

Reports:  85%|████████▍ | 6019/7111 [23:23<03:37,  5.01it/s]

Reports:  85%|████████▍ | 6020/7111 [23:24<03:36,  5.04it/s]

Reports:  85%|████████▍ | 6021/7111 [23:24<03:37,  5.02it/s]

Reports:  85%|████████▍ | 6022/7111 [23:24<03:36,  5.02it/s]

Reports:  85%|████████▍ | 6023/7111 [23:24<03:37,  5.01it/s]

Reports:  85%|████████▍ | 6024/7111 [23:24<03:35,  5.04it/s]

Reports:  85%|████████▍ | 6025/7111 [23:24<03:32,  5.10it/s]

Reports:  85%|████████▍ | 6026/7111 [23:25<03:29,  5.19it/s]

Reports:  85%|████████▍ | 6027/7111 [23:25<03:27,  5.24it/s]

Reports:  85%|████████▍ | 6028/7111 [23:25<03:29,  5.17it/s]

Reports:  85%|████████▍ | 6029/7111 [23:25<03:29,  5.16it/s]

Reports:  85%|████████▍ | 6030/7111 [23:25<03:26,  5.23it/s]

Reports:  85%|████████▍ | 6031/7111 [23:26<03:25,  5.27it/s]

Reports:  85%|████████▍ | 6032/7111 [23:26<03:24,  5.28it/s]

Reports:  85%|████████▍ | 6033/7111 [23:26<03:25,  5.26it/s]

Reports:  85%|████████▍ | 6034/7111 [23:26<03:24,  5.26it/s]

Reports:  85%|████████▍ | 6035/7111 [23:26<03:26,  5.22it/s]

Reports:  85%|████████▍ | 6036/7111 [23:27<03:23,  5.27it/s]

Reports:  85%|████████▍ | 6037/7111 [23:27<03:22,  5.31it/s]

Reports:  85%|████████▍ | 6038/7111 [23:27<03:26,  5.19it/s]

Reports:  85%|████████▍ | 6039/7111 [23:27<03:27,  5.16it/s]

Reports:  85%|████████▍ | 6040/7111 [23:27<03:33,  5.01it/s]

Reports:  85%|████████▍ | 6041/7111 [23:28<03:32,  5.03it/s]

Reports:  85%|████████▍ | 6042/7111 [23:28<03:32,  5.03it/s]

Reports:  85%|████████▍ | 6043/7111 [23:28<03:33,  4.99it/s]

Reports:  85%|████████▍ | 6044/7111 [23:28<03:31,  5.05it/s]

Reports:  85%|████████▌ | 6045/7111 [23:28<03:32,  5.02it/s]

Reports:  85%|████████▌ | 6046/7111 [23:29<03:53,  4.56it/s]

Reports:  85%|████████▌ | 6047/7111 [23:29<03:48,  4.65it/s]

Reports:  85%|████████▌ | 6048/7111 [23:29<03:40,  4.82it/s]

Reports:  85%|████████▌ | 6049/7111 [23:29<03:36,  4.91it/s]

Reports:  85%|████████▌ | 6050/7111 [23:29<03:36,  4.89it/s]

Reports:  85%|████████▌ | 6051/7111 [23:30<03:37,  4.88it/s]

Reports:  85%|████████▌ | 6052/7111 [23:30<03:34,  4.93it/s]

Reports:  85%|████████▌ | 6053/7111 [23:30<03:28,  5.07it/s]

Reports:  85%|████████▌ | 6054/7111 [23:30<03:26,  5.11it/s]

Reports:  85%|████████▌ | 6055/7111 [23:30<03:28,  5.06it/s]

Reports:  85%|████████▌ | 6056/7111 [23:31<03:27,  5.08it/s]

Reports:  85%|████████▌ | 6057/7111 [23:31<03:25,  5.14it/s]

Reports:  85%|████████▌ | 6058/7111 [23:31<03:23,  5.18it/s]

Reports:  85%|████████▌ | 6059/7111 [23:31<03:26,  5.10it/s]

Reports:  85%|████████▌ | 6060/7111 [23:31<03:22,  5.18it/s]

Reports:  85%|████████▌ | 6061/7111 [23:32<03:20,  5.23it/s]

Reports:  85%|████████▌ | 6062/7111 [23:32<03:21,  5.22it/s]

Reports:  85%|████████▌ | 6063/7111 [23:32<03:23,  5.14it/s]

Reports:  85%|████████▌ | 6064/7111 [23:32<03:26,  5.07it/s]

Reports:  85%|████████▌ | 6065/7111 [23:32<03:24,  5.10it/s]

Reports:  85%|████████▌ | 6066/7111 [23:33<03:23,  5.14it/s]

Reports:  85%|████████▌ | 6067/7111 [23:33<03:23,  5.13it/s]

Reports:  85%|████████▌ | 6068/7111 [23:33<03:26,  5.05it/s]

Reports:  85%|████████▌ | 6069/7111 [23:33<03:24,  5.09it/s]

Reports:  85%|████████▌ | 6070/7111 [23:33<03:27,  5.01it/s]

Reports:  85%|████████▌ | 6071/7111 [23:34<03:22,  5.13it/s]

Reports:  85%|████████▌ | 6072/7111 [23:34<03:20,  5.19it/s]

Reports:  85%|████████▌ | 6073/7111 [23:34<03:19,  5.20it/s]

Reports:  85%|████████▌ | 6074/7111 [23:34<03:21,  5.16it/s]

Reports:  85%|████████▌ | 6075/7111 [23:34<03:23,  5.09it/s]

Reports:  85%|████████▌ | 6076/7111 [23:35<03:21,  5.15it/s]

Reports:  85%|████████▌ | 6077/7111 [23:35<03:21,  5.14it/s]

Reports:  85%|████████▌ | 6078/7111 [23:35<03:19,  5.18it/s]

Reports:  85%|████████▌ | 6079/7111 [23:35<03:18,  5.21it/s]

Reports:  86%|████████▌ | 6080/7111 [23:35<03:24,  5.04it/s]

Reports:  86%|████████▌ | 6081/7111 [23:35<03:25,  5.01it/s]

Reports:  86%|████████▌ | 6082/7111 [23:36<03:34,  4.79it/s]

Reports:  86%|████████▌ | 6083/7111 [23:36<03:28,  4.93it/s]

Reports:  86%|████████▌ | 6084/7111 [23:36<03:28,  4.92it/s]

Reports:  86%|████████▌ | 6085/7111 [23:36<03:24,  5.02it/s]

Reports:  86%|████████▌ | 6086/7111 [23:37<03:25,  5.00it/s]

Reports:  86%|████████▌ | 6087/7111 [23:37<03:23,  5.04it/s]

Reports:  86%|████████▌ | 6088/7111 [23:37<03:21,  5.08it/s]

Reports:  86%|████████▌ | 6089/7111 [23:37<03:24,  4.99it/s]

Reports:  86%|████████▌ | 6090/7111 [23:37<03:25,  4.98it/s]

Reports:  86%|████████▌ | 6091/7111 [23:37<03:21,  5.07it/s]

Reports:  86%|████████▌ | 6092/7111 [23:38<03:18,  5.13it/s]

Reports:  86%|████████▌ | 6093/7111 [23:38<03:16,  5.19it/s]

Reports:  86%|████████▌ | 6094/7111 [23:38<03:15,  5.21it/s]

Reports:  86%|████████▌ | 6095/7111 [23:38<03:13,  5.25it/s]

Reports:  86%|████████▌ | 6096/7111 [23:38<03:21,  5.03it/s]

Reports:  86%|████████▌ | 6097/7111 [23:39<03:17,  5.13it/s]

Reports:  86%|████████▌ | 6098/7111 [23:39<03:19,  5.08it/s]

Reports:  86%|████████▌ | 6099/7111 [23:39<03:18,  5.11it/s]

Reports:  86%|████████▌ | 6100/7111 [23:39<03:17,  5.13it/s]

Reports:  86%|████████▌ | 6101/7111 [23:39<03:16,  5.15it/s]

Reports:  86%|████████▌ | 6102/7111 [23:40<03:13,  5.20it/s]

Reports:  86%|████████▌ | 6103/7111 [23:40<03:11,  5.27it/s]

Reports:  86%|████████▌ | 6104/7111 [23:40<03:14,  5.18it/s]

Reports:  86%|████████▌ | 6105/7111 [23:40<03:18,  5.07it/s]

Reports:  86%|████████▌ | 6106/7111 [23:40<03:19,  5.03it/s]

Reports:  86%|████████▌ | 6107/7111 [23:41<03:22,  4.96it/s]

Reports:  86%|████████▌ | 6108/7111 [23:41<03:19,  5.03it/s]

Reports:  86%|████████▌ | 6109/7111 [23:41<03:21,  4.97it/s]

Reports:  86%|████████▌ | 6110/7111 [23:41<03:19,  5.02it/s]

Reports:  86%|████████▌ | 6111/7111 [23:41<03:18,  5.04it/s]

Reports:  86%|████████▌ | 6112/7111 [23:42<03:19,  5.02it/s]

Reports:  86%|████████▌ | 6113/7111 [23:42<03:17,  5.05it/s]

Reports:  86%|████████▌ | 6114/7111 [23:42<03:20,  4.98it/s]

Reports:  86%|████████▌ | 6115/7111 [23:42<03:14,  5.11it/s]

Reports:  86%|████████▌ | 6116/7111 [23:42<03:19,  4.99it/s]

Reports:  86%|████████▌ | 6117/7111 [23:43<03:17,  5.03it/s]

Reports:  86%|████████▌ | 6118/7111 [23:43<03:16,  5.06it/s]

Reports:  86%|████████▌ | 6119/7111 [23:43<03:14,  5.09it/s]

Reports:  86%|████████▌ | 6120/7111 [23:43<03:12,  5.16it/s]

Reports:  86%|████████▌ | 6121/7111 [23:43<03:16,  5.03it/s]

Reports:  86%|████████▌ | 6122/7111 [23:44<03:13,  5.10it/s]

Reports:  86%|████████▌ | 6123/7111 [23:44<03:13,  5.10it/s]

Reports:  86%|████████▌ | 6124/7111 [23:44<03:11,  5.14it/s]

Reports:  86%|████████▌ | 6125/7111 [23:44<03:10,  5.17it/s]

Reports:  86%|████████▌ | 6126/7111 [23:44<03:08,  5.23it/s]

Reports:  86%|████████▌ | 6127/7111 [23:45<03:12,  5.11it/s]

Reports:  86%|████████▌ | 6128/7111 [23:45<03:10,  5.15it/s]

Reports:  86%|████████▌ | 6129/7111 [23:45<03:09,  5.19it/s]

Reports:  86%|████████▌ | 6130/7111 [23:45<03:08,  5.22it/s]

Reports:  86%|████████▌ | 6131/7111 [23:45<03:09,  5.18it/s]

Reports:  86%|████████▌ | 6132/7111 [23:46<03:05,  5.28it/s]

Reports:  86%|████████▌ | 6133/7111 [23:46<03:05,  5.28it/s]

Reports:  86%|████████▋ | 6134/7111 [23:46<03:04,  5.30it/s]

Reports:  86%|████████▋ | 6135/7111 [23:46<03:03,  5.33it/s]

Reports:  86%|████████▋ | 6136/7111 [23:46<03:06,  5.23it/s]

Reports:  86%|████████▋ | 6137/7111 [23:46<03:04,  5.27it/s]

Reports:  86%|████████▋ | 6138/7111 [23:47<03:06,  5.21it/s]

Reports:  86%|████████▋ | 6139/7111 [23:47<03:09,  5.14it/s]

Reports:  86%|████████▋ | 6140/7111 [23:47<03:11,  5.06it/s]

Reports:  86%|████████▋ | 6141/7111 [23:47<03:09,  5.12it/s]

Reports:  86%|████████▋ | 6142/7111 [23:47<03:12,  5.04it/s]

Reports:  86%|████████▋ | 6143/7111 [23:48<03:11,  5.05it/s]

Reports:  86%|████████▋ | 6144/7111 [23:48<03:18,  4.88it/s]

Reports:  86%|████████▋ | 6145/7111 [23:48<03:12,  5.01it/s]

Reports:  86%|████████▋ | 6146/7111 [23:48<03:09,  5.10it/s]

Reports:  86%|████████▋ | 6147/7111 [23:48<03:07,  5.15it/s]

Reports:  86%|████████▋ | 6148/7111 [23:49<03:07,  5.15it/s]

Reports:  86%|████████▋ | 6149/7111 [23:49<03:07,  5.12it/s]

Reports:  86%|████████▋ | 6150/7111 [23:49<03:08,  5.09it/s]

Reports:  86%|████████▋ | 6151/7111 [23:49<03:06,  5.15it/s]

Reports:  87%|████████▋ | 6152/7111 [23:49<03:06,  5.14it/s]

Reports:  87%|████████▋ | 6153/7111 [23:50<03:10,  5.02it/s]

Reports:  87%|████████▋ | 6154/7111 [23:50<03:06,  5.13it/s]

Reports:  87%|████████▋ | 6155/7111 [23:50<03:07,  5.09it/s]

Reports:  87%|████████▋ | 6156/7111 [23:50<03:04,  5.17it/s]

Reports:  87%|████████▋ | 6157/7111 [23:50<03:02,  5.22it/s]

Reports:  87%|████████▋ | 6158/7111 [23:51<03:11,  4.98it/s]

Reports:  87%|████████▋ | 6159/7111 [23:51<03:06,  5.11it/s]

Reports:  87%|████████▋ | 6160/7111 [23:51<03:04,  5.17it/s]

Reports:  87%|████████▋ | 6161/7111 [23:51<03:01,  5.25it/s]

Reports:  87%|████████▋ | 6162/7111 [23:51<03:03,  5.16it/s]

Reports:  87%|████████▋ | 6163/7111 [23:52<03:08,  5.03it/s]

Reports:  87%|████████▋ | 6164/7111 [23:52<03:04,  5.15it/s]

Reports:  87%|████████▋ | 6165/7111 [23:52<03:03,  5.16it/s]

Reports:  87%|████████▋ | 6166/7111 [23:52<03:08,  5.02it/s]

Reports:  87%|████████▋ | 6167/7111 [23:52<03:05,  5.10it/s]

Reports:  87%|████████▋ | 6168/7111 [23:53<03:06,  5.05it/s]

Reports:  87%|████████▋ | 6169/7111 [23:53<03:02,  5.16it/s]

Reports:  87%|████████▋ | 6170/7111 [23:53<03:25,  4.59it/s]

Reports:  87%|████████▋ | 6171/7111 [23:53<03:21,  4.67it/s]

Reports:  87%|████████▋ | 6172/7111 [23:53<03:13,  4.85it/s]

Reports:  87%|████████▋ | 6173/7111 [23:54<03:10,  4.92it/s]

Reports:  87%|████████▋ | 6174/7111 [23:54<03:06,  5.03it/s]

Reports:  87%|████████▋ | 6175/7111 [23:54<03:01,  5.16it/s]

Reports:  87%|████████▋ | 6176/7111 [23:54<03:00,  5.18it/s]

Reports:  87%|████████▋ | 6177/7111 [23:54<02:59,  5.19it/s]

Reports:  87%|████████▋ | 6178/7111 [23:55<02:57,  5.26it/s]

Reports:  87%|████████▋ | 6179/7111 [23:55<03:03,  5.08it/s]

Reports:  87%|████████▋ | 6180/7111 [23:55<03:00,  5.16it/s]

Reports:  87%|████████▋ | 6181/7111 [23:55<03:02,  5.10it/s]

Reports:  87%|████████▋ | 6182/7111 [23:55<03:03,  5.06it/s]

Reports:  87%|████████▋ | 6183/7111 [23:56<03:01,  5.12it/s]

Reports:  87%|████████▋ | 6184/7111 [23:56<03:01,  5.10it/s]

Reports:  87%|████████▋ | 6185/7111 [23:56<02:58,  5.19it/s]

Reports:  87%|████████▋ | 6186/7111 [23:56<03:03,  5.03it/s]

Reports:  87%|████████▋ | 6187/7111 [23:56<03:04,  5.00it/s]

Reports:  87%|████████▋ | 6188/7111 [23:57<03:03,  5.02it/s]

Reports:  87%|████████▋ | 6189/7111 [23:57<03:02,  5.05it/s]

Reports:  87%|████████▋ | 6190/7111 [23:57<03:00,  5.10it/s]

Reports:  87%|████████▋ | 6191/7111 [23:57<03:01,  5.08it/s]

Reports:  87%|████████▋ | 6192/7111 [23:57<02:57,  5.17it/s]

Reports:  87%|████████▋ | 6193/7111 [23:57<03:01,  5.06it/s]

Reports:  87%|████████▋ | 6194/7111 [23:58<02:57,  5.17it/s]

Reports:  87%|████████▋ | 6195/7111 [23:58<02:58,  5.13it/s]

Reports:  87%|████████▋ | 6196/7111 [23:58<02:59,  5.09it/s]

Reports:  87%|████████▋ | 6197/7111 [23:58<02:58,  5.12it/s]

Reports:  87%|████████▋ | 6198/7111 [23:58<03:01,  5.03it/s]

Reports:  87%|████████▋ | 6199/7111 [23:59<03:02,  5.01it/s]

Reports:  87%|████████▋ | 6200/7111 [23:59<03:04,  4.93it/s]

Reports:  87%|████████▋ | 6201/7111 [23:59<03:02,  4.98it/s]

Reports:  87%|████████▋ | 6202/7111 [23:59<02:58,  5.10it/s]

Reports:  87%|████████▋ | 6203/7111 [23:59<02:57,  5.11it/s]

Reports:  87%|████████▋ | 6204/7111 [24:00<02:57,  5.11it/s]

Reports:  87%|████████▋ | 6205/7111 [24:00<02:57,  5.10it/s]

Reports:  87%|████████▋ | 6206/7111 [24:00<02:55,  5.15it/s]

Reports:  87%|████████▋ | 6207/7111 [24:00<02:55,  5.15it/s]

Reports:  87%|████████▋ | 6208/7111 [24:00<02:53,  5.21it/s]

Reports:  87%|████████▋ | 6209/7111 [24:01<02:55,  5.14it/s]

Reports:  87%|████████▋ | 6210/7111 [24:01<02:54,  5.15it/s]

Reports:  87%|████████▋ | 6211/7111 [24:01<02:53,  5.18it/s]

Reports:  87%|████████▋ | 6212/7111 [24:01<02:57,  5.06it/s]

Reports:  87%|████████▋ | 6213/7111 [24:01<02:59,  5.00it/s]

Reports:  87%|████████▋ | 6214/7111 [24:02<03:01,  4.95it/s]

Reports:  87%|████████▋ | 6215/7111 [24:02<03:03,  4.88it/s]

Reports:  87%|████████▋ | 6216/7111 [24:02<03:01,  4.94it/s]

Reports:  87%|████████▋ | 6217/7111 [24:02<03:01,  4.91it/s]

Reports:  87%|████████▋ | 6218/7111 [24:02<02:57,  5.02it/s]

Reports:  87%|████████▋ | 6219/7111 [24:03<02:55,  5.09it/s]

Reports:  87%|████████▋ | 6220/7111 [24:03<02:56,  5.04it/s]

Reports:  87%|████████▋ | 6221/7111 [24:03<02:57,  5.01it/s]

Reports:  87%|████████▋ | 6222/7111 [24:03<03:01,  4.91it/s]

Reports:  88%|████████▊ | 6223/7111 [24:03<02:58,  4.98it/s]

Reports:  88%|████████▊ | 6224/7111 [24:04<02:54,  5.08it/s]

Reports:  88%|████████▊ | 6225/7111 [24:04<02:53,  5.10it/s]

Reports:  88%|████████▊ | 6226/7111 [24:04<02:52,  5.12it/s]

Reports:  88%|████████▊ | 6227/7111 [24:04<02:51,  5.16it/s]

Reports:  88%|████████▊ | 6228/7111 [24:05<03:27,  4.25it/s]

Reports:  88%|████████▊ | 6229/7111 [24:05<03:15,  4.50it/s]

Reports:  88%|████████▊ | 6230/7111 [24:05<03:13,  4.56it/s]

Reports:  88%|████████▊ | 6231/7111 [24:05<03:05,  4.73it/s]

Reports:  88%|████████▊ | 6232/7111 [24:05<03:02,  4.82it/s]

Reports:  88%|████████▊ | 6233/7111 [24:06<03:03,  4.79it/s]

Reports:  88%|████████▊ | 6234/7111 [24:06<02:58,  4.90it/s]

Reports:  88%|████████▊ | 6235/7111 [24:06<03:00,  4.86it/s]

Reports:  88%|████████▊ | 6236/7111 [24:06<02:58,  4.90it/s]

Reports:  88%|████████▊ | 6237/7111 [24:06<02:57,  4.92it/s]

Reports:  88%|████████▊ | 6238/7111 [24:07<02:52,  5.07it/s]

Reports:  88%|████████▊ | 6239/7111 [24:07<02:51,  5.09it/s]

Reports:  88%|████████▊ | 6240/7111 [24:07<02:51,  5.09it/s]

Reports:  88%|████████▊ | 6241/7111 [24:07<02:52,  5.04it/s]

Reports:  88%|████████▊ | 6242/7111 [24:07<02:54,  4.98it/s]

Reports:  88%|████████▊ | 6243/7111 [24:08<02:53,  5.01it/s]

Reports:  88%|████████▊ | 6244/7111 [24:08<02:50,  5.10it/s]

Reports:  88%|████████▊ | 6245/7111 [24:08<02:53,  4.99it/s]

Reports:  88%|████████▊ | 6246/7111 [24:08<02:51,  5.04it/s]

Reports:  88%|████████▊ | 6247/7111 [24:08<02:49,  5.09it/s]

Reports:  88%|████████▊ | 6248/7111 [24:09<02:48,  5.13it/s]

Reports:  88%|████████▊ | 6249/7111 [24:09<02:51,  5.01it/s]

Reports:  88%|████████▊ | 6250/7111 [24:09<02:47,  5.13it/s]

Reports:  88%|████████▊ | 6251/7111 [24:09<02:50,  5.04it/s]

Reports:  88%|████████▊ | 6252/7111 [24:09<02:49,  5.05it/s]

Reports:  88%|████████▊ | 6253/7111 [24:10<02:50,  5.05it/s]

Reports:  88%|████████▊ | 6254/7111 [24:10<02:48,  5.10it/s]

Reports:  88%|████████▊ | 6255/7111 [24:10<02:54,  4.91it/s]

Reports:  88%|████████▊ | 6256/7111 [24:10<02:54,  4.91it/s]

Reports:  88%|████████▊ | 6257/7111 [24:10<02:49,  5.05it/s]

Reports:  88%|████████▊ | 6258/7111 [24:11<02:50,  5.00it/s]

Reports:  88%|████████▊ | 6259/7111 [24:11<02:46,  5.11it/s]

Reports:  88%|████████▊ | 6260/7111 [24:11<02:47,  5.08it/s]

Reports:  88%|████████▊ | 6261/7111 [24:11<02:45,  5.14it/s]

Reports:  88%|████████▊ | 6262/7111 [24:11<02:42,  5.21it/s]

Reports:  88%|████████▊ | 6263/7111 [24:11<02:41,  5.26it/s]

Reports:  88%|████████▊ | 6264/7111 [24:12<02:40,  5.29it/s]

Reports:  88%|████████▊ | 6265/7111 [24:12<02:38,  5.35it/s]

Reports:  88%|████████▊ | 6266/7111 [24:12<02:36,  5.38it/s]

Reports:  88%|████████▊ | 6267/7111 [24:12<02:40,  5.26it/s]

Reports:  88%|████████▊ | 6268/7111 [24:12<02:39,  5.27it/s]

Reports:  88%|████████▊ | 6269/7111 [24:13<02:40,  5.25it/s]

Reports:  88%|████████▊ | 6270/7111 [24:13<02:39,  5.27it/s]

Reports:  88%|████████▊ | 6271/7111 [24:13<02:38,  5.29it/s]

Reports:  88%|████████▊ | 6272/7111 [24:13<02:37,  5.33it/s]

Reports:  88%|████████▊ | 6273/7111 [24:13<02:38,  5.28it/s]

Reports:  88%|████████▊ | 6274/7111 [24:14<02:38,  5.29it/s]

Reports:  88%|████████▊ | 6275/7111 [24:14<02:37,  5.30it/s]

Reports:  88%|████████▊ | 6276/7111 [24:14<02:36,  5.33it/s]

Reports:  88%|████████▊ | 6277/7111 [24:14<02:37,  5.29it/s]

Reports:  88%|████████▊ | 6278/7111 [24:14<02:42,  5.14it/s]

Reports:  88%|████████▊ | 6279/7111 [24:14<02:39,  5.22it/s]

Reports:  88%|████████▊ | 6280/7111 [24:15<02:37,  5.27it/s]

Reports:  88%|████████▊ | 6281/7111 [24:15<02:40,  5.16it/s]

Reports:  88%|████████▊ | 6282/7111 [24:15<02:38,  5.24it/s]

Reports:  88%|████████▊ | 6283/7111 [24:15<02:37,  5.25it/s]

Reports:  88%|████████▊ | 6284/7111 [24:15<02:36,  5.28it/s]

Reports:  88%|████████▊ | 6285/7111 [24:16<02:35,  5.32it/s]

Reports:  88%|████████▊ | 6286/7111 [24:16<02:41,  5.11it/s]

Reports:  88%|████████▊ | 6287/7111 [24:16<02:40,  5.13it/s]

Reports:  88%|████████▊ | 6288/7111 [24:16<02:37,  5.22it/s]

Reports:  88%|████████▊ | 6289/7111 [24:16<02:41,  5.11it/s]

Reports:  88%|████████▊ | 6290/7111 [24:17<02:43,  5.02it/s]

Reports:  88%|████████▊ | 6291/7111 [24:17<02:40,  5.11it/s]

Reports:  88%|████████▊ | 6292/7111 [24:17<02:37,  5.19it/s]

Reports:  88%|████████▊ | 6293/7111 [24:17<02:40,  5.10it/s]

Reports:  89%|████████▊ | 6294/7111 [24:17<02:38,  5.17it/s]

Reports:  89%|████████▊ | 6295/7111 [24:18<02:36,  5.22it/s]

Reports:  89%|████████▊ | 6296/7111 [24:18<02:34,  5.27it/s]

Reports:  89%|████████▊ | 6297/7111 [24:18<02:34,  5.25it/s]

Reports:  89%|████████▊ | 6298/7111 [24:18<02:39,  5.10it/s]

Reports:  89%|████████▊ | 6299/7111 [24:18<02:37,  5.15it/s]

Reports:  89%|████████▊ | 6300/7111 [24:19<02:38,  5.12it/s]

Reports:  89%|████████▊ | 6301/7111 [24:19<02:38,  5.10it/s]

Reports:  89%|████████▊ | 6302/7111 [24:19<02:35,  5.19it/s]

Reports:  89%|████████▊ | 6303/7111 [24:19<02:35,  5.21it/s]

Reports:  89%|████████▊ | 6304/7111 [24:19<02:37,  5.12it/s]

Reports:  89%|████████▊ | 6305/7111 [24:20<06:29,  2.07it/s]

Reports:  89%|████████▊ | 6306/7111 [24:21<05:17,  2.53it/s]

Reports:  89%|████████▊ | 6307/7111 [24:21<04:31,  2.96it/s]

Reports:  89%|████████▊ | 6308/7111 [24:21<03:54,  3.43it/s]

Reports:  89%|████████▊ | 6309/7111 [24:21<03:43,  3.59it/s]

Reports:  89%|████████▊ | 6310/7111 [24:21<03:21,  3.98it/s]

Reports:  89%|████████▊ | 6311/7111 [24:22<03:05,  4.31it/s]

Reports:  89%|████████▉ | 6312/7111 [24:22<02:53,  4.61it/s]

Reports:  89%|████████▉ | 6313/7111 [24:22<02:46,  4.79it/s]

Reports:  89%|████████▉ | 6314/7111 [24:23<04:46,  2.78it/s]

Reports:  89%|████████▉ | 6315/7111 [24:23<04:08,  3.20it/s]

Reports:  89%|████████▉ | 6316/7111 [24:23<03:40,  3.60it/s]

Reports:  89%|████████▉ | 6317/7111 [24:23<03:18,  4.01it/s]

Reports:  89%|████████▉ | 6318/7111 [24:24<03:01,  4.37it/s]

Reports:  89%|████████▉ | 6319/7111 [24:24<02:56,  4.48it/s]

Reports:  89%|████████▉ | 6320/7111 [24:24<02:47,  4.71it/s]

Reports:  89%|████████▉ | 6321/7111 [24:24<02:44,  4.80it/s]

Reports:  89%|████████▉ | 6322/7111 [24:24<02:39,  4.95it/s]

Reports:  89%|████████▉ | 6323/7111 [24:25<02:37,  5.01it/s]

Reports:  89%|████████▉ | 6324/7111 [24:25<02:33,  5.11it/s]

Reports:  89%|████████▉ | 6325/7111 [24:25<02:32,  5.17it/s]

Reports:  89%|████████▉ | 6326/7111 [24:25<02:32,  5.14it/s]

Reports:  89%|████████▉ | 6327/7111 [24:25<02:32,  5.13it/s]

Reports:  89%|████████▉ | 6328/7111 [24:25<02:31,  5.18it/s]

Reports:  89%|████████▉ | 6329/7111 [24:26<02:29,  5.23it/s]

Reports:  89%|████████▉ | 6330/7111 [24:26<04:43,  2.76it/s]

Reports:  89%|████████▉ | 6331/7111 [24:27<04:08,  3.13it/s]

Reports:  89%|████████▉ | 6332/7111 [24:27<03:37,  3.58it/s]

Reports:  89%|████████▉ | 6333/7111 [24:27<03:18,  3.92it/s]

Reports:  89%|████████▉ | 6334/7111 [24:27<03:03,  4.24it/s]

Reports:  89%|████████▉ | 6335/7111 [24:27<02:52,  4.49it/s]

Reports:  89%|████████▉ | 6336/7111 [24:28<02:46,  4.66it/s]

Reports:  89%|████████▉ | 6337/7111 [24:28<02:40,  4.82it/s]

Reports:  89%|████████▉ | 6338/7111 [24:28<02:35,  4.98it/s]

Reports:  89%|████████▉ | 6339/7111 [24:28<02:34,  4.98it/s]

Reports:  89%|████████▉ | 6340/7111 [24:28<02:33,  5.02it/s]

Reports:  89%|████████▉ | 6341/7111 [24:29<02:33,  5.02it/s]

Reports:  89%|████████▉ | 6342/7111 [24:29<02:33,  5.00it/s]

Reports:  89%|████████▉ | 6343/7111 [24:29<02:30,  5.12it/s]

Reports:  89%|████████▉ | 6344/7111 [24:29<02:27,  5.19it/s]

Reports:  89%|████████▉ | 6345/7111 [24:29<02:25,  5.25it/s]

Reports:  89%|████████▉ | 6346/7111 [24:30<02:24,  5.29it/s]

Reports:  89%|████████▉ | 6347/7111 [24:30<02:26,  5.22it/s]

Reports:  89%|████████▉ | 6348/7111 [24:30<02:27,  5.16it/s]

Reports:  89%|████████▉ | 6349/7111 [24:30<02:28,  5.13it/s]

Reports:  89%|████████▉ | 6350/7111 [24:30<02:27,  5.15it/s]

Reports:  89%|████████▉ | 6351/7111 [24:30<02:25,  5.23it/s]

Reports:  89%|████████▉ | 6352/7111 [24:31<02:27,  5.14it/s]

Reports:  89%|████████▉ | 6353/7111 [24:31<02:27,  5.14it/s]

Reports:  89%|████████▉ | 6354/7111 [24:31<02:29,  5.07it/s]

Reports:  89%|████████▉ | 6355/7111 [24:31<02:26,  5.14it/s]

Reports:  89%|████████▉ | 6356/7111 [24:31<02:27,  5.12it/s]

Reports:  89%|████████▉ | 6357/7111 [24:32<02:26,  5.15it/s]

Reports:  89%|████████▉ | 6358/7111 [24:32<02:25,  5.17it/s]

Reports:  89%|████████▉ | 6359/7111 [24:32<02:26,  5.12it/s]

Reports:  89%|████████▉ | 6360/7111 [24:32<02:26,  5.11it/s]

Reports:  89%|████████▉ | 6361/7111 [24:32<02:26,  5.11it/s]

Reports:  89%|████████▉ | 6362/7111 [24:33<02:24,  5.17it/s]

Reports:  89%|████████▉ | 6363/7111 [24:33<02:26,  5.10it/s]

Reports:  89%|████████▉ | 6364/7111 [24:34<06:01,  2.07it/s]

Reports:  90%|████████▉ | 6365/7111 [24:34<04:56,  2.51it/s]

Reports:  90%|████████▉ | 6366/7111 [24:34<04:10,  2.98it/s]

Reports:  90%|████████▉ | 6367/7111 [24:35<03:38,  3.40it/s]

Reports:  90%|████████▉ | 6368/7111 [24:35<03:15,  3.81it/s]

Reports:  90%|████████▉ | 6369/7111 [24:35<02:59,  4.14it/s]

Reports:  90%|████████▉ | 6370/7111 [24:35<02:47,  4.41it/s]

Reports:  90%|████████▉ | 6371/7111 [24:35<02:39,  4.64it/s]

Reports:  90%|████████▉ | 6372/7111 [24:36<02:32,  4.84it/s]

Reports:  90%|████████▉ | 6373/7111 [24:36<02:29,  4.95it/s]

Reports:  90%|████████▉ | 6374/7111 [24:36<02:31,  4.87it/s]

Reports:  90%|████████▉ | 6375/7111 [24:36<02:28,  4.95it/s]

Reports:  90%|████████▉ | 6376/7111 [24:36<02:25,  5.06it/s]

Reports:  90%|████████▉ | 6377/7111 [24:37<02:24,  5.09it/s]

Reports:  90%|████████▉ | 6378/7111 [24:37<02:39,  4.59it/s]

Reports:  90%|████████▉ | 6379/7111 [24:37<02:34,  4.73it/s]

Reports:  90%|████████▉ | 6380/7111 [24:37<02:28,  4.94it/s]

Reports:  90%|████████▉ | 6381/7111 [24:37<02:29,  4.90it/s]

Reports:  90%|████████▉ | 6382/7111 [24:38<04:32,  2.68it/s]

Reports:  90%|████████▉ | 6383/7111 [24:38<03:56,  3.07it/s]

Reports:  90%|████████▉ | 6384/7111 [24:39<03:30,  3.45it/s]

Reports:  90%|████████▉ | 6385/7111 [24:39<03:08,  3.86it/s]

Reports:  90%|████████▉ | 6386/7111 [24:39<02:51,  4.22it/s]

Reports:  90%|████████▉ | 6387/7111 [24:39<02:44,  4.40it/s]

Reports:  90%|████████▉ | 6388/7111 [24:39<02:35,  4.65it/s]

Reports:  90%|████████▉ | 6389/7111 [24:40<02:31,  4.77it/s]

Reports:  90%|████████▉ | 6390/7111 [24:40<02:30,  4.79it/s]

Reports:  90%|████████▉ | 6391/7111 [24:40<04:08,  2.90it/s]

Reports:  90%|████████▉ | 6392/7111 [24:41<03:37,  3.30it/s]

Reports:  90%|████████▉ | 6393/7111 [24:41<03:13,  3.70it/s]

Reports:  90%|████████▉ | 6394/7111 [24:41<02:57,  4.04it/s]

Reports:  90%|████████▉ | 6395/7111 [24:41<02:43,  4.37it/s]

Reports:  90%|████████▉ | 6396/7111 [24:42<03:48,  3.13it/s]

Reports:  90%|████████▉ | 6397/7111 [24:42<03:21,  3.54it/s]

Reports:  90%|████████▉ | 6398/7111 [24:42<03:00,  3.95it/s]

Reports:  90%|████████▉ | 6399/7111 [24:42<02:46,  4.27it/s]

Reports:  90%|█████████ | 6400/7111 [24:42<02:39,  4.46it/s]

Reports:  90%|█████████ | 6401/7111 [24:43<02:32,  4.66it/s]

Reports:  90%|█████████ | 6402/7111 [24:43<02:27,  4.82it/s]

Reports:  90%|█████████ | 6403/7111 [24:43<02:22,  4.95it/s]

Reports:  90%|█████████ | 6404/7111 [24:43<02:21,  4.99it/s]

Reports:  90%|█████████ | 6405/7111 [24:43<02:19,  5.05it/s]

Reports:  90%|█████████ | 6406/7111 [24:44<02:18,  5.10it/s]

Reports:  90%|█████████ | 6407/7111 [24:44<02:18,  5.10it/s]

Reports:  90%|█████████ | 6408/7111 [24:44<02:21,  4.97it/s]

Reports:  90%|█████████ | 6409/7111 [24:44<02:19,  5.05it/s]

Reports:  90%|█████████ | 6410/7111 [24:45<03:07,  3.75it/s]

Reports:  90%|█████████ | 6411/7111 [24:45<02:52,  4.05it/s]

Reports:  90%|█████████ | 6412/7111 [24:45<02:40,  4.37it/s]

Reports:  90%|█████████ | 6413/7111 [24:45<02:32,  4.58it/s]

Reports:  90%|█████████ | 6414/7111 [24:45<02:26,  4.76it/s]

Reports:  90%|█████████ | 6415/7111 [24:46<02:23,  4.84it/s]

Reports:  90%|█████████ | 6416/7111 [24:46<02:21,  4.91it/s]

Reports:  90%|█████████ | 6417/7111 [24:46<02:18,  5.01it/s]

Reports:  90%|█████████ | 6418/7111 [24:46<02:15,  5.10it/s]

Reports:  90%|█████████ | 6419/7111 [24:46<02:13,  5.17it/s]

Reports:  90%|█████████ | 6420/7111 [24:47<02:13,  5.17it/s]

Reports:  90%|█████████ | 6421/7111 [24:47<02:13,  5.16it/s]

Reports:  90%|█████████ | 6422/7111 [24:47<02:12,  5.20it/s]

Reports:  90%|█████████ | 6423/7111 [24:47<02:13,  5.14it/s]

Reports:  90%|█████████ | 6424/7111 [24:47<02:13,  5.15it/s]

Reports:  90%|█████████ | 6425/7111 [24:48<02:12,  5.16it/s]

Reports:  90%|█████████ | 6426/7111 [24:48<02:10,  5.25it/s]

Reports:  90%|█████████ | 6427/7111 [24:48<02:11,  5.20it/s]

Reports:  90%|█████████ | 6428/7111 [24:49<03:44,  3.04it/s]

Reports:  90%|█████████ | 6429/7111 [24:49<03:17,  3.45it/s]

Reports:  90%|█████████ | 6430/7111 [24:49<04:49,  2.36it/s]

Reports:  90%|█████████ | 6431/7111 [24:50<04:04,  2.78it/s]

Reports:  90%|█████████ | 6432/7111 [24:50<03:29,  3.24it/s]

Reports:  90%|█████████ | 6433/7111 [24:50<03:06,  3.63it/s]

Reports:  90%|█████████ | 6434/7111 [24:50<02:48,  4.02it/s]

Reports:  90%|█████████ | 6435/7111 [24:50<02:35,  4.35it/s]

Reports:  91%|█████████ | 6436/7111 [24:51<02:28,  4.54it/s]

Reports:  91%|█████████ | 6437/7111 [24:51<02:26,  4.59it/s]

Reports:  91%|█████████ | 6438/7111 [24:51<02:20,  4.80it/s]

Reports:  91%|█████████ | 6439/7111 [24:51<02:15,  4.94it/s]

Reports:  91%|█████████ | 6440/7111 [24:51<02:12,  5.06it/s]

Reports:  91%|█████████ | 6441/7111 [24:52<02:12,  5.04it/s]

Reports:  91%|█████████ | 6442/7111 [24:52<02:12,  5.07it/s]

Reports:  91%|█████████ | 6443/7111 [24:52<02:11,  5.09it/s]

Reports:  91%|█████████ | 6444/7111 [24:52<02:11,  5.06it/s]

Reports:  91%|█████████ | 6445/7111 [24:52<02:10,  5.11it/s]

Reports:  91%|█████████ | 6446/7111 [24:53<02:10,  5.09it/s]

Reports:  91%|█████████ | 6447/7111 [24:53<02:08,  5.17it/s]

Reports:  91%|█████████ | 6448/7111 [24:53<02:06,  5.25it/s]

Reports:  91%|█████████ | 6449/7111 [24:53<02:10,  5.05it/s]

Reports:  91%|█████████ | 6450/7111 [24:53<02:08,  5.13it/s]

Reports:  91%|█████████ | 6451/7111 [24:54<02:08,  5.15it/s]

Reports:  91%|█████████ | 6452/7111 [24:54<02:09,  5.10it/s]

Reports:  91%|█████████ | 6453/7111 [24:54<02:08,  5.13it/s]

Reports:  91%|█████████ | 6454/7111 [24:54<02:08,  5.12it/s]

Reports:  91%|█████████ | 6455/7111 [24:54<02:06,  5.17it/s]

Reports:  91%|█████████ | 6456/7111 [24:55<02:05,  5.23it/s]

Reports:  91%|█████████ | 6457/7111 [24:55<02:05,  5.21it/s]

Reports:  91%|█████████ | 6458/7111 [24:56<05:47,  1.88it/s]

Reports:  91%|█████████ | 6459/7111 [24:56<04:39,  2.33it/s]

Reports:  91%|█████████ | 6460/7111 [24:56<03:52,  2.80it/s]

Reports:  91%|█████████ | 6461/7111 [24:57<03:18,  3.27it/s]

Reports:  91%|█████████ | 6462/7111 [24:57<02:58,  3.63it/s]

Reports:  91%|█████████ | 6463/7111 [24:57<02:41,  4.01it/s]

Reports:  91%|█████████ | 6464/7111 [24:57<02:29,  4.32it/s]

Reports:  91%|█████████ | 6465/7111 [24:57<02:22,  4.52it/s]

Reports:  91%|█████████ | 6466/7111 [24:58<02:17,  4.68it/s]

Reports:  91%|█████████ | 6467/7111 [24:58<02:12,  4.87it/s]

Reports:  91%|█████████ | 6468/7111 [24:58<02:07,  5.03it/s]

Reports:  91%|█████████ | 6469/7111 [24:58<02:05,  5.12it/s]

Reports:  91%|█████████ | 6470/7111 [24:58<02:05,  5.13it/s]

Reports:  91%|█████████ | 6471/7111 [24:59<02:03,  5.19it/s]

Reports:  91%|█████████ | 6472/7111 [24:59<02:01,  5.25it/s]

Reports:  91%|█████████ | 6473/7111 [24:59<02:00,  5.27it/s]

Reports:  91%|█████████ | 6474/7111 [24:59<02:05,  5.09it/s]

Reports:  91%|█████████ | 6475/7111 [24:59<02:03,  5.13it/s]

Reports:  91%|█████████ | 6476/7111 [25:00<02:05,  5.07it/s]

Reports:  91%|█████████ | 6477/7111 [25:00<02:03,  5.14it/s]

Reports:  91%|█████████ | 6478/7111 [25:00<02:01,  5.19it/s]

Reports:  91%|█████████ | 6479/7111 [25:00<01:59,  5.30it/s]

Reports:  91%|█████████ | 6480/7111 [25:00<02:03,  5.11it/s]

Reports:  91%|█████████ | 6481/7111 [25:00<02:01,  5.20it/s]

Reports:  91%|█████████ | 6482/7111 [25:01<02:00,  5.23it/s]

Reports:  91%|█████████ | 6483/7111 [25:01<01:59,  5.24it/s]

Reports:  91%|█████████ | 6484/7111 [25:01<02:03,  5.09it/s]

Reports:  91%|█████████ | 6485/7111 [25:01<02:02,  5.11it/s]

Reports:  91%|█████████ | 6486/7111 [25:01<02:02,  5.11it/s]

Reports:  91%|█████████ | 6487/7111 [25:02<02:00,  5.19it/s]

Reports:  91%|█████████ | 6488/7111 [25:02<02:01,  5.14it/s]

Reports:  91%|█████████▏| 6489/7111 [25:02<02:57,  3.50it/s]

Reports:  91%|█████████▏| 6490/7111 [25:03<02:42,  3.82it/s]

Reports:  91%|█████████▏| 6491/7111 [25:03<02:28,  4.18it/s]

Reports:  91%|█████████▏| 6492/7111 [25:03<02:29,  4.15it/s]

Reports:  91%|█████████▏| 6493/7111 [25:03<02:21,  4.36it/s]

Reports:  91%|█████████▏| 6494/7111 [25:03<02:14,  4.60it/s]

Reports:  91%|█████████▏| 6495/7111 [25:04<02:23,  4.28it/s]

Reports:  91%|█████████▏| 6496/7111 [25:04<02:15,  4.54it/s]

Reports:  91%|█████████▏| 6497/7111 [25:04<02:08,  4.77it/s]

Reports:  91%|█████████▏| 6498/7111 [25:04<02:04,  4.91it/s]

Reports:  91%|█████████▏| 6499/7111 [25:04<02:00,  5.07it/s]

Reports:  91%|█████████▏| 6500/7111 [25:05<01:58,  5.14it/s]

Reports:  91%|█████████▏| 6501/7111 [25:05<02:01,  5.00it/s]

Reports:  91%|█████████▏| 6502/7111 [25:05<02:04,  4.89it/s]

Reports:  91%|█████████▏| 6503/7111 [25:06<03:29,  2.90it/s]

Reports:  91%|█████████▏| 6504/7111 [25:06<03:03,  3.31it/s]

Reports:  91%|█████████▏| 6505/7111 [25:06<03:04,  3.29it/s]

Reports:  91%|█████████▏| 6506/7111 [25:06<02:48,  3.60it/s]

Reports:  92%|█████████▏| 6507/7111 [25:07<02:32,  3.96it/s]

Reports:  92%|█████████▏| 6508/7111 [25:07<03:59,  2.52it/s]

Reports:  92%|█████████▏| 6509/7111 [25:08<03:20,  3.00it/s]

Reports:  92%|█████████▏| 6510/7111 [25:08<02:56,  3.40it/s]

Reports:  92%|█████████▏| 6511/7111 [25:08<02:37,  3.80it/s]

Reports:  92%|█████████▏| 6512/7111 [25:08<02:31,  3.96it/s]

Reports:  92%|█████████▏| 6513/7111 [25:08<02:21,  4.22it/s]

Reports:  92%|█████████▏| 6514/7111 [25:09<02:14,  4.45it/s]

Reports:  92%|█████████▏| 6515/7111 [25:09<02:08,  4.64it/s]

Reports:  92%|█████████▏| 6516/7111 [25:09<02:05,  4.74it/s]

Reports:  92%|█████████▏| 6517/7111 [25:09<02:03,  4.83it/s]

Reports:  92%|█████████▏| 6518/7111 [25:09<02:04,  4.76it/s]

Reports:  92%|█████████▏| 6519/7111 [25:10<02:00,  4.90it/s]

Reports:  92%|█████████▏| 6520/7111 [25:10<01:57,  5.02it/s]

Reports:  92%|█████████▏| 6521/7111 [25:10<01:56,  5.08it/s]

Reports:  92%|█████████▏| 6522/7111 [25:10<01:55,  5.08it/s]

Reports:  92%|█████████▏| 6523/7111 [25:10<01:54,  5.15it/s]

Reports:  92%|█████████▏| 6524/7111 [25:10<01:53,  5.17it/s]

Reports:  92%|█████████▏| 6525/7111 [25:11<01:55,  5.07it/s]

Reports:  92%|█████████▏| 6526/7111 [25:11<01:56,  5.00it/s]

Reports:  92%|█████████▏| 6527/7111 [25:11<01:54,  5.11it/s]

Reports:  92%|█████████▏| 6528/7111 [25:11<02:07,  4.59it/s]

Reports:  92%|█████████▏| 6529/7111 [25:12<02:02,  4.76it/s]

Reports:  92%|█████████▏| 6530/7111 [25:12<02:36,  3.71it/s]

Reports:  92%|█████████▏| 6531/7111 [25:12<02:29,  3.88it/s]

Reports:  92%|█████████▏| 6532/7111 [25:12<02:20,  4.12it/s]

Reports:  92%|█████████▏| 6533/7111 [25:13<02:11,  4.39it/s]

Reports:  92%|█████████▏| 6534/7111 [25:13<02:06,  4.56it/s]

Reports:  92%|█████████▏| 6535/7111 [25:13<02:01,  4.73it/s]

Reports:  92%|█████████▏| 6536/7111 [25:13<01:57,  4.91it/s]

Reports:  92%|█████████▏| 6537/7111 [25:13<01:53,  5.05it/s]

Reports:  92%|█████████▏| 6538/7111 [25:14<01:53,  5.04it/s]

Reports:  92%|█████████▏| 6539/7111 [25:14<01:51,  5.14it/s]

Reports:  92%|█████████▏| 6540/7111 [25:14<01:50,  5.17it/s]

Reports:  92%|█████████▏| 6541/7111 [25:14<01:50,  5.17it/s]

Reports:  92%|█████████▏| 6542/7111 [25:14<01:50,  5.13it/s]

Reports:  92%|█████████▏| 6543/7111 [25:15<01:51,  5.10it/s]

Reports:  92%|█████████▏| 6544/7111 [25:15<01:49,  5.18it/s]

Reports:  92%|█████████▏| 6545/7111 [25:15<01:47,  5.25it/s]

Reports:  92%|█████████▏| 6546/7111 [25:15<01:49,  5.14it/s]

Reports:  92%|█████████▏| 6547/7111 [25:15<01:48,  5.19it/s]

Reports:  92%|█████████▏| 6548/7111 [25:15<01:47,  5.23it/s]

Reports:  92%|█████████▏| 6549/7111 [25:16<01:46,  5.26it/s]

Reports:  92%|█████████▏| 6550/7111 [25:16<01:47,  5.24it/s]

Reports:  92%|█████████▏| 6551/7111 [25:16<01:46,  5.26it/s]

Reports:  92%|█████████▏| 6552/7111 [25:16<01:45,  5.28it/s]

Reports:  92%|█████████▏| 6553/7111 [25:16<01:48,  5.14it/s]

Reports:  92%|█████████▏| 6554/7111 [25:17<01:47,  5.18it/s]

Reports:  92%|█████████▏| 6555/7111 [25:17<01:48,  5.12it/s]

Reports:  92%|█████████▏| 6556/7111 [25:17<01:48,  5.12it/s]

Reports:  92%|█████████▏| 6557/7111 [25:17<01:47,  5.13it/s]

Reports:  92%|█████████▏| 6558/7111 [25:17<01:46,  5.17it/s]

Reports:  92%|█████████▏| 6559/7111 [25:18<01:55,  4.80it/s]

Reports:  92%|█████████▏| 6560/7111 [25:18<01:54,  4.80it/s]

Reports:  92%|█████████▏| 6561/7111 [25:18<01:51,  4.94it/s]

Reports:  92%|█████████▏| 6562/7111 [25:18<01:52,  4.88it/s]

Reports:  92%|█████████▏| 6563/7111 [25:18<01:49,  4.99it/s]

Reports:  92%|█████████▏| 6564/7111 [25:19<01:48,  5.04it/s]

Reports:  92%|█████████▏| 6565/7111 [25:19<01:47,  5.09it/s]

Reports:  92%|█████████▏| 6566/7111 [25:19<01:45,  5.17it/s]

Reports:  92%|█████████▏| 6567/7111 [25:19<01:43,  5.27it/s]

Reports:  92%|█████████▏| 6568/7111 [25:19<01:43,  5.25it/s]

Reports:  92%|█████████▏| 6569/7111 [25:20<01:43,  5.24it/s]

Reports:  92%|█████████▏| 6570/7111 [25:20<01:43,  5.24it/s]

Reports:  92%|█████████▏| 6571/7111 [25:20<01:42,  5.27it/s]

Reports:  92%|█████████▏| 6572/7111 [25:20<01:43,  5.23it/s]

Reports:  92%|█████████▏| 6573/7111 [25:20<01:42,  5.23it/s]

Reports:  92%|█████████▏| 6574/7111 [25:21<01:44,  5.13it/s]

Reports:  92%|█████████▏| 6575/7111 [25:21<01:45,  5.09it/s]

Reports:  92%|█████████▏| 6576/7111 [25:21<01:44,  5.13it/s]

Reports:  92%|█████████▏| 6577/7111 [25:21<01:43,  5.17it/s]

Reports:  93%|█████████▎| 6578/7111 [25:21<01:42,  5.19it/s]

Reports:  93%|█████████▎| 6579/7111 [25:21<01:41,  5.23it/s]

Reports:  93%|█████████▎| 6580/7111 [25:22<01:40,  5.28it/s]

Reports:  93%|█████████▎| 6581/7111 [25:22<01:40,  5.25it/s]

Reports:  93%|█████████▎| 6582/7111 [25:22<01:41,  5.24it/s]

Reports:  93%|█████████▎| 6583/7111 [25:22<01:39,  5.31it/s]

Reports:  93%|█████████▎| 6584/7111 [25:22<01:40,  5.26it/s]

Reports:  93%|█████████▎| 6585/7111 [25:23<01:41,  5.18it/s]

Reports:  93%|█████████▎| 6586/7111 [25:23<01:41,  5.18it/s]

Reports:  93%|█████████▎| 6587/7111 [25:23<01:40,  5.22it/s]

Reports:  93%|█████████▎| 6588/7111 [25:23<01:41,  5.14it/s]

Reports:  93%|█████████▎| 6589/7111 [25:23<01:43,  5.06it/s]

Reports:  93%|█████████▎| 6590/7111 [25:24<01:44,  5.01it/s]

Reports:  93%|█████████▎| 6591/7111 [25:24<01:42,  5.07it/s]

Reports:  93%|█████████▎| 6592/7111 [25:24<01:41,  5.14it/s]

Reports:  93%|█████████▎| 6593/7111 [25:24<01:38,  5.25it/s]

Reports:  93%|█████████▎| 6594/7111 [25:24<01:40,  5.13it/s]

Reports:  93%|█████████▎| 6595/7111 [25:25<01:44,  4.94it/s]

Reports:  93%|█████████▎| 6596/7111 [25:25<01:41,  5.08it/s]

Reports:  93%|█████████▎| 6597/7111 [25:25<01:43,  4.98it/s]

Reports:  93%|█████████▎| 6598/7111 [25:25<01:43,  4.98it/s]

Reports:  93%|█████████▎| 6599/7111 [25:25<01:40,  5.09it/s]

Reports:  93%|█████████▎| 6600/7111 [25:26<01:43,  4.95it/s]

Reports:  93%|█████████▎| 6601/7111 [25:26<02:35,  3.27it/s]

Reports:  93%|█████████▎| 6602/7111 [25:26<02:16,  3.72it/s]

Reports:  93%|█████████▎| 6603/7111 [25:27<02:04,  4.09it/s]

Reports:  93%|█████████▎| 6604/7111 [25:27<01:54,  4.41it/s]

Reports:  93%|█████████▎| 6605/7111 [25:27<01:49,  4.62it/s]

Reports:  93%|█████████▎| 6606/7111 [25:27<01:48,  4.68it/s]

Reports:  93%|█████████▎| 6607/7111 [25:27<01:44,  4.81it/s]

Reports:  93%|█████████▎| 6608/7111 [25:28<01:41,  4.96it/s]

Reports:  93%|█████████▎| 6609/7111 [25:28<01:40,  4.99it/s]

Reports:  93%|█████████▎| 6610/7111 [25:28<01:38,  5.09it/s]

Reports:  93%|█████████▎| 6611/7111 [25:28<01:36,  5.19it/s]

Reports:  93%|█████████▎| 6612/7111 [25:28<01:36,  5.20it/s]

Reports:  93%|█████████▎| 6613/7111 [25:28<01:38,  5.07it/s]

Reports:  93%|█████████▎| 6614/7111 [25:29<01:38,  5.03it/s]

Reports:  93%|█████████▎| 6615/7111 [25:29<01:37,  5.07it/s]

Reports:  93%|█████████▎| 6616/7111 [25:29<01:37,  5.07it/s]

Reports:  93%|█████████▎| 6617/7111 [25:29<01:37,  5.06it/s]

Reports:  93%|█████████▎| 6618/7111 [25:29<01:36,  5.12it/s]

Reports:  93%|█████████▎| 6619/7111 [25:30<01:34,  5.20it/s]

Reports:  93%|█████████▎| 6620/7111 [25:30<01:35,  5.14it/s]

Reports:  93%|█████████▎| 6621/7111 [25:30<01:35,  5.13it/s]

Reports:  93%|█████████▎| 6622/7111 [25:30<01:36,  5.09it/s]

Reports:  93%|█████████▎| 6623/7111 [25:30<01:35,  5.12it/s]

Reports:  93%|█████████▎| 6624/7111 [25:31<01:35,  5.08it/s]

Reports:  93%|█████████▎| 6625/7111 [25:31<01:36,  5.04it/s]

Reports:  93%|█████████▎| 6626/7111 [25:31<01:35,  5.06it/s]

Reports:  93%|█████████▎| 6627/7111 [25:31<01:38,  4.92it/s]

Reports:  93%|█████████▎| 6628/7111 [25:31<01:35,  5.04it/s]

Reports:  93%|█████████▎| 6629/7111 [25:32<01:37,  4.95it/s]

Reports:  93%|█████████▎| 6630/7111 [25:32<01:38,  4.86it/s]

Reports:  93%|█████████▎| 6631/7111 [25:32<01:36,  4.96it/s]

Reports:  93%|█████████▎| 6632/7111 [25:32<01:36,  4.98it/s]

Reports:  93%|█████████▎| 6633/7111 [25:32<01:36,  4.97it/s]

Reports:  93%|█████████▎| 6634/7111 [25:33<01:35,  5.00it/s]

Reports:  93%|█████████▎| 6635/7111 [25:33<01:34,  5.06it/s]

Reports:  93%|█████████▎| 6636/7111 [25:33<01:31,  5.17it/s]

Reports:  93%|█████████▎| 6637/7111 [25:33<01:32,  5.13it/s]

Reports:  93%|█████████▎| 6638/7111 [25:33<01:31,  5.16it/s]

Reports:  93%|█████████▎| 6639/7111 [25:34<01:30,  5.23it/s]

Reports:  93%|█████████▎| 6640/7111 [25:34<01:29,  5.26it/s]

Reports:  93%|█████████▎| 6641/7111 [25:34<01:29,  5.23it/s]

Reports:  93%|█████████▎| 6642/7111 [25:34<01:30,  5.16it/s]

Reports:  93%|█████████▎| 6643/7111 [25:34<01:29,  5.20it/s]

Reports:  93%|█████████▎| 6644/7111 [25:35<01:28,  5.28it/s]

Reports:  93%|█████████▎| 6645/7111 [25:35<01:30,  5.17it/s]

Reports:  93%|█████████▎| 6646/7111 [25:35<01:29,  5.18it/s]

Reports:  93%|█████████▎| 6647/7111 [25:35<01:29,  5.17it/s]

Reports:  93%|█████████▎| 6648/7111 [25:35<01:29,  5.20it/s]

Reports:  94%|█████████▎| 6649/7111 [25:36<01:27,  5.26it/s]

Reports:  94%|█████████▎| 6650/7111 [25:36<01:29,  5.15it/s]

Reports:  94%|█████████▎| 6651/7111 [25:36<01:28,  5.20it/s]

Reports:  94%|█████████▎| 6652/7111 [25:36<01:28,  5.19it/s]

Reports:  94%|█████████▎| 6653/7111 [25:36<01:27,  5.22it/s]

Reports:  94%|█████████▎| 6654/7111 [25:36<01:27,  5.20it/s]

Reports:  94%|█████████▎| 6655/7111 [25:37<01:27,  5.21it/s]

Reports:  94%|█████████▎| 6656/7111 [25:37<01:27,  5.18it/s]

Reports:  94%|█████████▎| 6657/7111 [25:37<01:27,  5.19it/s]

Reports:  94%|█████████▎| 6658/7111 [25:37<01:27,  5.19it/s]

Reports:  94%|█████████▎| 6659/7111 [25:37<01:26,  5.20it/s]

Reports:  94%|█████████▎| 6660/7111 [25:38<01:25,  5.27it/s]

Reports:  94%|█████████▎| 6661/7111 [25:38<01:25,  5.28it/s]

Reports:  94%|█████████▎| 6662/7111 [25:38<01:25,  5.25it/s]

Reports:  94%|█████████▎| 6663/7111 [25:38<01:26,  5.18it/s]

Reports:  94%|█████████▎| 6664/7111 [25:38<01:25,  5.21it/s]

Reports:  94%|█████████▎| 6665/7111 [25:39<01:27,  5.10it/s]

Reports:  94%|█████████▎| 6666/7111 [25:39<01:26,  5.15it/s]

Reports:  94%|█████████▍| 6667/7111 [25:39<01:26,  5.11it/s]

Reports:  94%|█████████▍| 6668/7111 [25:39<01:26,  5.11it/s]

Reports:  94%|█████████▍| 6669/7111 [25:39<01:25,  5.17it/s]

Reports:  94%|█████████▍| 6670/7111 [25:40<01:26,  5.12it/s]

Reports:  94%|█████████▍| 6671/7111 [25:40<01:26,  5.09it/s]

Reports:  94%|█████████▍| 6672/7111 [25:40<01:26,  5.09it/s]

Reports:  94%|█████████▍| 6673/7111 [25:40<01:26,  5.08it/s]

Reports:  94%|█████████▍| 6674/7111 [25:40<01:24,  5.15it/s]

Reports:  94%|█████████▍| 6675/7111 [25:41<01:26,  5.05it/s]

Reports:  94%|█████████▍| 6676/7111 [25:41<01:26,  5.01it/s]

Reports:  94%|█████████▍| 6677/7111 [25:41<01:25,  5.06it/s]

Reports:  94%|█████████▍| 6678/7111 [25:41<01:24,  5.11it/s]

Reports:  94%|█████████▍| 6679/7111 [25:41<01:23,  5.15it/s]

Reports:  94%|█████████▍| 6680/7111 [25:42<01:22,  5.20it/s]

Reports:  94%|█████████▍| 6681/7111 [25:42<01:23,  5.15it/s]

Reports:  94%|█████████▍| 6682/7111 [25:42<01:22,  5.19it/s]

Reports:  94%|█████████▍| 6683/7111 [25:42<01:23,  5.11it/s]

Reports:  94%|█████████▍| 6684/7111 [25:42<01:22,  5.15it/s]

Reports:  94%|█████████▍| 6685/7111 [25:42<01:22,  5.16it/s]

Reports:  94%|█████████▍| 6686/7111 [25:43<01:23,  5.09it/s]

Reports:  94%|█████████▍| 6687/7111 [25:43<01:22,  5.13it/s]

Reports:  94%|█████████▍| 6688/7111 [25:43<01:22,  5.15it/s]

Reports:  94%|█████████▍| 6689/7111 [25:43<01:21,  5.18it/s]

Reports:  94%|█████████▍| 6690/7111 [25:43<01:22,  5.13it/s]

Reports:  94%|█████████▍| 6691/7111 [25:44<01:20,  5.22it/s]

Reports:  94%|█████████▍| 6692/7111 [25:44<01:20,  5.22it/s]

Reports:  94%|█████████▍| 6693/7111 [25:44<01:20,  5.19it/s]

Reports:  94%|█████████▍| 6694/7111 [25:44<01:19,  5.23it/s]

Reports:  94%|█████████▍| 6695/7111 [25:44<01:19,  5.24it/s]

Reports:  94%|█████████▍| 6696/7111 [25:45<01:18,  5.30it/s]

Reports:  94%|█████████▍| 6697/7111 [25:45<01:17,  5.34it/s]

Reports:  94%|█████████▍| 6698/7111 [25:45<01:17,  5.36it/s]

Reports:  94%|█████████▍| 6699/7111 [25:45<01:16,  5.36it/s]

Reports:  94%|█████████▍| 6700/7111 [25:45<01:17,  5.28it/s]

Reports:  94%|█████████▍| 6701/7111 [25:46<01:18,  5.24it/s]

Reports:  94%|█████████▍| 6702/7111 [25:46<01:18,  5.22it/s]

Reports:  94%|█████████▍| 6703/7111 [25:46<01:17,  5.29it/s]

Reports:  94%|█████████▍| 6704/7111 [25:46<01:17,  5.25it/s]

Reports:  94%|█████████▍| 6705/7111 [25:46<01:17,  5.22it/s]

Reports:  94%|█████████▍| 6706/7111 [25:47<01:18,  5.18it/s]

Reports:  94%|█████████▍| 6707/7111 [25:47<01:19,  5.05it/s]

Reports:  94%|█████████▍| 6708/7111 [25:47<01:21,  4.96it/s]

Reports:  94%|█████████▍| 6709/7111 [25:47<01:19,  5.06it/s]

Reports:  94%|█████████▍| 6710/7111 [25:47<01:18,  5.14it/s]

Reports:  94%|█████████▍| 6711/7111 [25:48<01:19,  5.06it/s]

Reports:  94%|█████████▍| 6712/7111 [25:48<01:19,  5.05it/s]

Reports:  94%|█████████▍| 6713/7111 [25:48<01:19,  4.99it/s]

Reports:  94%|█████████▍| 6714/7111 [25:48<01:19,  5.01it/s]

Reports:  94%|█████████▍| 6715/7111 [25:48<01:17,  5.13it/s]

Reports:  94%|█████████▍| 6716/7111 [25:48<01:16,  5.16it/s]

Reports:  94%|█████████▍| 6717/7111 [25:49<01:16,  5.18it/s]

Reports:  94%|█████████▍| 6718/7111 [25:49<01:14,  5.27it/s]

Reports:  94%|█████████▍| 6719/7111 [25:49<01:33,  4.21it/s]

Reports:  95%|█████████▍| 6720/7111 [25:49<01:26,  4.53it/s]

Reports:  95%|█████████▍| 6721/7111 [25:50<01:25,  4.58it/s]

Reports:  95%|█████████▍| 6722/7111 [25:50<01:21,  4.77it/s]

Reports:  95%|█████████▍| 6723/7111 [25:50<01:18,  4.96it/s]

Reports:  95%|█████████▍| 6724/7111 [25:50<01:16,  5.09it/s]

Reports:  95%|█████████▍| 6725/7111 [25:50<01:14,  5.16it/s]

Reports:  95%|█████████▍| 6726/7111 [25:51<01:14,  5.19it/s]

Reports:  95%|█████████▍| 6727/7111 [25:51<01:13,  5.22it/s]

Reports:  95%|█████████▍| 6728/7111 [25:51<01:13,  5.19it/s]

Reports:  95%|█████████▍| 6729/7111 [25:51<01:14,  5.10it/s]

Reports:  95%|█████████▍| 6730/7111 [25:51<01:15,  5.08it/s]

Reports:  95%|█████████▍| 6731/7111 [25:52<01:15,  5.00it/s]

Reports:  95%|█████████▍| 6732/7111 [25:52<01:14,  5.09it/s]

Reports:  95%|█████████▍| 6733/7111 [25:52<01:14,  5.09it/s]

Reports:  95%|█████████▍| 6734/7111 [25:52<01:14,  5.04it/s]

Reports:  95%|█████████▍| 6735/7111 [25:52<01:14,  5.02it/s]

Reports:  95%|█████████▍| 6736/7111 [25:53<01:14,  5.00it/s]

Reports:  95%|█████████▍| 6737/7111 [25:53<01:25,  4.40it/s]

Reports:  95%|█████████▍| 6738/7111 [25:53<01:20,  4.64it/s]

Reports:  95%|█████████▍| 6739/7111 [25:53<01:16,  4.85it/s]

Reports:  95%|█████████▍| 6740/7111 [25:53<01:15,  4.90it/s]

Reports:  95%|█████████▍| 6741/7111 [25:54<01:31,  4.04it/s]

Reports:  95%|█████████▍| 6742/7111 [25:54<01:52,  3.27it/s]

Reports:  95%|█████████▍| 6743/7111 [25:54<01:39,  3.72it/s]

Reports:  95%|█████████▍| 6744/7111 [25:55<01:30,  4.06it/s]

Reports:  95%|█████████▍| 6745/7111 [25:55<02:32,  2.40it/s]

Reports:  95%|█████████▍| 6746/7111 [25:56<02:09,  2.83it/s]

Reports:  95%|█████████▍| 6747/7111 [25:56<01:50,  3.28it/s]

Reports:  95%|█████████▍| 6748/7111 [25:56<01:38,  3.69it/s]

Reports:  95%|█████████▍| 6749/7111 [25:56<01:29,  4.05it/s]

Reports:  95%|█████████▍| 6750/7111 [25:56<01:22,  4.36it/s]

Reports:  95%|█████████▍| 6751/7111 [25:57<01:19,  4.54it/s]

Reports:  95%|█████████▍| 6752/7111 [25:57<01:14,  4.79it/s]

Reports:  95%|█████████▍| 6753/7111 [25:57<01:13,  4.86it/s]

Reports:  95%|█████████▍| 6754/7111 [25:57<01:12,  4.91it/s]

Reports:  95%|█████████▍| 6755/7111 [25:57<01:10,  5.05it/s]

Reports:  95%|█████████▌| 6756/7111 [25:57<01:08,  5.16it/s]

Reports:  95%|█████████▌| 6757/7111 [25:58<01:08,  5.18it/s]

Reports:  95%|█████████▌| 6758/7111 [25:58<01:07,  5.23it/s]

Reports:  95%|█████████▌| 6759/7111 [25:58<01:06,  5.28it/s]

Reports:  95%|█████████▌| 6760/7111 [25:58<01:06,  5.29it/s]

Reports:  95%|█████████▌| 6761/7111 [25:58<01:07,  5.19it/s]

Reports:  95%|█████████▌| 6762/7111 [25:59<01:07,  5.17it/s]

Reports:  95%|█████████▌| 6763/7111 [25:59<01:06,  5.21it/s]

Reports:  95%|█████████▌| 6764/7111 [25:59<01:06,  5.25it/s]

Reports:  95%|█████████▌| 6765/7111 [25:59<01:05,  5.27it/s]

Reports:  95%|█████████▌| 6766/7111 [25:59<01:05,  5.28it/s]

Reports:  95%|█████████▌| 6767/7111 [26:00<01:05,  5.25it/s]

Reports:  95%|█████████▌| 6768/7111 [26:00<01:05,  5.20it/s]

Reports:  95%|█████████▌| 6769/7111 [26:00<01:06,  5.12it/s]

Reports:  95%|█████████▌| 6770/7111 [26:00<01:05,  5.19it/s]

Reports:  95%|█████████▌| 6771/7111 [26:00<01:04,  5.27it/s]

Reports:  95%|█████████▌| 6772/7111 [26:01<01:04,  5.25it/s]

Reports:  95%|█████████▌| 6773/7111 [26:01<01:04,  5.27it/s]

Reports:  95%|█████████▌| 6774/7111 [26:01<01:03,  5.30it/s]

Reports:  95%|█████████▌| 6775/7111 [26:01<01:04,  5.21it/s]

Reports:  95%|█████████▌| 6776/7111 [26:01<01:03,  5.24it/s]

Reports:  95%|█████████▌| 6777/7111 [26:02<01:04,  5.16it/s]

Reports:  95%|█████████▌| 6778/7111 [26:02<01:03,  5.24it/s]

Reports:  95%|█████████▌| 6779/7111 [26:02<01:02,  5.30it/s]

Reports:  95%|█████████▌| 6780/7111 [26:02<01:02,  5.27it/s]

Reports:  95%|█████████▌| 6781/7111 [26:02<01:03,  5.21it/s]

Reports:  95%|█████████▌| 6782/7111 [26:02<01:03,  5.16it/s]

Reports:  95%|█████████▌| 6783/7111 [26:03<01:03,  5.19it/s]

Reports:  95%|█████████▌| 6784/7111 [26:03<01:03,  5.14it/s]

Reports:  95%|█████████▌| 6785/7111 [26:03<01:05,  5.01it/s]

Reports:  95%|█████████▌| 6786/7111 [26:03<01:04,  5.03it/s]

Reports:  95%|█████████▌| 6787/7111 [26:03<01:03,  5.11it/s]

Reports:  95%|█████████▌| 6788/7111 [26:04<01:03,  5.06it/s]

Reports:  95%|█████████▌| 6789/7111 [26:04<01:05,  4.93it/s]

Reports:  95%|█████████▌| 6790/7111 [26:04<01:03,  5.05it/s]

Reports:  95%|█████████▌| 6791/7111 [26:04<01:04,  4.97it/s]

Reports:  96%|█████████▌| 6792/7111 [26:04<01:03,  5.04it/s]

Reports:  96%|█████████▌| 6793/7111 [26:05<01:03,  5.00it/s]

Reports:  96%|█████████▌| 6794/7111 [26:05<01:02,  5.06it/s]

Reports:  96%|█████████▌| 6795/7111 [26:05<01:01,  5.13it/s]

Reports:  96%|█████████▌| 6796/7111 [26:05<01:00,  5.23it/s]

Reports:  96%|█████████▌| 6797/7111 [26:05<00:59,  5.27it/s]

Reports:  96%|█████████▌| 6798/7111 [26:06<00:59,  5.25it/s]

Reports:  96%|█████████▌| 6799/7111 [26:06<00:58,  5.30it/s]

Reports:  96%|█████████▌| 6800/7111 [26:06<01:00,  5.18it/s]

Reports:  96%|█████████▌| 6801/7111 [26:06<01:12,  4.28it/s]

Reports:  96%|█████████▌| 6802/7111 [26:07<01:09,  4.42it/s]

Reports:  96%|█████████▌| 6803/7111 [26:07<01:06,  4.61it/s]

Reports:  96%|█████████▌| 6804/7111 [26:07<01:04,  4.77it/s]

Reports:  96%|█████████▌| 6805/7111 [26:07<01:03,  4.82it/s]

Reports:  96%|█████████▌| 6806/7111 [26:07<01:01,  4.98it/s]

Reports:  96%|█████████▌| 6807/7111 [26:07<00:59,  5.07it/s]

Reports:  96%|█████████▌| 6808/7111 [26:08<00:59,  5.11it/s]

Reports:  96%|█████████▌| 6809/7111 [26:08<00:59,  5.09it/s]

Reports:  96%|█████████▌| 6810/7111 [26:08<00:58,  5.17it/s]

Reports:  96%|█████████▌| 6811/7111 [26:08<00:57,  5.22it/s]

Reports:  96%|█████████▌| 6812/7111 [26:08<00:56,  5.28it/s]

Reports:  96%|█████████▌| 6813/7111 [26:09<00:56,  5.29it/s]

Reports:  96%|█████████▌| 6814/7111 [26:09<00:56,  5.27it/s]

Reports:  96%|█████████▌| 6815/7111 [26:09<01:04,  4.62it/s]

Reports:  96%|█████████▌| 6816/7111 [26:09<01:01,  4.81it/s]

Reports:  96%|█████████▌| 6817/7111 [26:09<00:59,  4.91it/s]

Reports:  96%|█████████▌| 6818/7111 [26:10<00:59,  4.93it/s]

Reports:  96%|█████████▌| 6819/7111 [26:10<00:59,  4.95it/s]

Reports:  96%|█████████▌| 6820/7111 [26:10<00:59,  4.92it/s]

Reports:  96%|█████████▌| 6821/7111 [26:10<00:59,  4.87it/s]

Reports:  96%|█████████▌| 6822/7111 [26:10<00:58,  4.97it/s]

Reports:  96%|█████████▌| 6823/7111 [26:11<00:56,  5.10it/s]

Reports:  96%|█████████▌| 6824/7111 [26:11<01:15,  3.82it/s]

Reports:  96%|█████████▌| 6825/7111 [26:11<01:08,  4.16it/s]

Reports:  96%|█████████▌| 6826/7111 [26:11<01:05,  4.33it/s]

Reports:  96%|█████████▌| 6827/7111 [26:12<01:03,  4.48it/s]

Reports:  96%|█████████▌| 6828/7111 [26:12<01:01,  4.61it/s]

Reports:  96%|█████████▌| 6829/7111 [26:12<01:00,  4.64it/s]

Reports:  96%|█████████▌| 6830/7111 [26:12<00:58,  4.81it/s]

Reports:  96%|█████████▌| 6831/7111 [26:13<01:10,  3.96it/s]

Reports:  96%|█████████▌| 6832/7111 [26:13<01:11,  3.91it/s]

Reports:  96%|█████████▌| 6833/7111 [26:13<01:07,  4.12it/s]

Reports:  96%|█████████▌| 6834/7111 [26:13<01:02,  4.43it/s]

Reports:  96%|█████████▌| 6835/7111 [26:14<01:05,  4.24it/s]

Reports:  96%|█████████▌| 6836/7111 [26:14<01:00,  4.52it/s]

Reports:  96%|█████████▌| 6837/7111 [26:14<01:03,  4.31it/s]

Reports:  96%|█████████▌| 6838/7111 [26:14<00:59,  4.60it/s]

Reports:  96%|█████████▌| 6839/7111 [26:14<00:57,  4.75it/s]

Reports:  96%|█████████▌| 6840/7111 [26:15<01:02,  4.30it/s]

Reports:  96%|█████████▌| 6841/7111 [26:15<01:05,  4.14it/s]

Reports:  96%|█████████▌| 6842/7111 [26:15<01:01,  4.38it/s]

Reports:  96%|█████████▌| 6843/7111 [26:15<00:58,  4.58it/s]

Reports:  96%|█████████▌| 6844/7111 [26:16<00:56,  4.76it/s]

Reports:  96%|█████████▋| 6845/7111 [26:16<00:55,  4.79it/s]

Reports:  96%|█████████▋| 6846/7111 [26:16<00:54,  4.86it/s]

Reports:  96%|█████████▋| 6847/7111 [26:16<00:53,  4.90it/s]

Reports:  96%|█████████▋| 6848/7111 [26:16<00:51,  5.07it/s]

Reports:  96%|█████████▋| 6849/7111 [26:17<00:51,  5.07it/s]

Reports:  96%|█████████▋| 6850/7111 [26:17<00:53,  4.91it/s]

Reports:  96%|█████████▋| 6851/7111 [26:17<00:58,  4.43it/s]

Reports:  96%|█████████▋| 6852/7111 [26:17<01:00,  4.31it/s]

Reports:  96%|█████████▋| 6853/7111 [26:18<01:02,  4.10it/s]

Reports:  96%|█████████▋| 6854/7111 [26:18<01:03,  4.04it/s]

Reports:  96%|█████████▋| 6855/7111 [26:18<01:01,  4.19it/s]

Reports:  96%|█████████▋| 6856/7111 [26:18<01:01,  4.16it/s]

Reports:  96%|█████████▋| 6857/7111 [26:18<00:58,  4.37it/s]

Reports:  96%|█████████▋| 6858/7111 [26:19<00:54,  4.62it/s]

Reports:  96%|█████████▋| 6859/7111 [26:19<00:52,  4.80it/s]

Reports:  96%|█████████▋| 6860/7111 [26:19<00:50,  4.94it/s]

Reports:  96%|█████████▋| 6861/7111 [26:19<00:50,  4.95it/s]

Reports:  96%|█████████▋| 6862/7111 [26:19<00:49,  5.03it/s]

Reports:  97%|█████████▋| 6863/7111 [26:20<00:48,  5.10it/s]

Reports:  97%|█████████▋| 6864/7111 [26:20<00:48,  5.11it/s]

Reports:  97%|█████████▋| 6865/7111 [26:20<00:47,  5.20it/s]

Reports:  97%|█████████▋| 6866/7111 [26:20<00:46,  5.24it/s]

Reports:  97%|█████████▋| 6867/7111 [26:20<00:46,  5.26it/s]

Reports:  97%|█████████▋| 6868/7111 [26:21<00:45,  5.32it/s]

Reports:  97%|█████████▋| 6869/7111 [26:21<00:45,  5.32it/s]

Reports:  97%|█████████▋| 6870/7111 [26:21<00:45,  5.33it/s]

Reports:  97%|█████████▋| 6871/7111 [26:21<00:45,  5.26it/s]

Reports:  97%|█████████▋| 6872/7111 [26:21<00:44,  5.31it/s]

Reports:  97%|█████████▋| 6873/7111 [26:21<00:44,  5.34it/s]

Reports:  97%|█████████▋| 6874/7111 [26:22<00:44,  5.33it/s]

Reports:  97%|█████████▋| 6875/7111 [26:22<00:47,  5.00it/s]

Reports:  97%|█████████▋| 6876/7111 [26:22<00:46,  5.04it/s]

Reports:  97%|█████████▋| 6877/7111 [26:22<00:46,  5.07it/s]

Reports:  97%|█████████▋| 6878/7111 [26:22<00:46,  5.02it/s]

Reports:  97%|█████████▋| 6879/7111 [26:23<00:46,  5.02it/s]

Reports:  97%|█████████▋| 6880/7111 [26:23<00:46,  5.01it/s]

Reports:  97%|█████████▋| 6881/7111 [26:23<00:47,  4.82it/s]

Reports:  97%|█████████▋| 6882/7111 [26:23<00:46,  4.93it/s]

Reports:  97%|█████████▋| 6883/7111 [26:23<00:45,  5.01it/s]

Reports:  97%|█████████▋| 6884/7111 [26:24<00:44,  5.07it/s]

Reports:  97%|█████████▋| 6885/7111 [26:24<00:44,  5.12it/s]

Reports:  97%|█████████▋| 6886/7111 [26:24<00:43,  5.14it/s]

Reports:  97%|█████████▋| 6887/7111 [26:24<00:43,  5.19it/s]

Reports:  97%|█████████▋| 6888/7111 [26:24<00:43,  5.18it/s]

Reports:  97%|█████████▋| 6889/7111 [26:25<00:42,  5.23it/s]

Reports:  97%|█████████▋| 6890/7111 [26:25<00:42,  5.24it/s]

Reports:  97%|█████████▋| 6891/7111 [26:25<00:42,  5.18it/s]

Reports:  97%|█████████▋| 6892/7111 [26:25<00:42,  5.20it/s]

Reports:  97%|█████████▋| 6893/7111 [26:25<00:41,  5.19it/s]

Reports:  97%|█████████▋| 6894/7111 [26:26<00:42,  5.06it/s]

Reports:  97%|█████████▋| 6895/7111 [26:26<00:43,  5.02it/s]

Reports:  97%|█████████▋| 6896/7111 [26:26<00:43,  4.99it/s]

Reports:  97%|█████████▋| 6897/7111 [26:26<00:42,  5.09it/s]

Reports:  97%|█████████▋| 6898/7111 [26:26<00:42,  5.05it/s]

Reports:  97%|█████████▋| 6899/7111 [26:27<00:41,  5.13it/s]

Reports:  97%|█████████▋| 6900/7111 [26:27<00:40,  5.22it/s]

Reports:  97%|█████████▋| 6901/7111 [26:27<00:39,  5.28it/s]

Reports:  97%|█████████▋| 6902/7111 [26:27<00:39,  5.34it/s]

Reports:  97%|█████████▋| 6903/7111 [26:27<00:38,  5.38it/s]

Reports:  97%|█████████▋| 6904/7111 [26:28<00:39,  5.25it/s]

Reports:  97%|█████████▋| 6905/7111 [26:28<00:39,  5.28it/s]

Reports:  97%|█████████▋| 6906/7111 [26:28<00:38,  5.31it/s]

Reports:  97%|█████████▋| 6907/7111 [26:28<00:38,  5.34it/s]

Reports:  97%|█████████▋| 6908/7111 [26:28<00:38,  5.34it/s]

Reports:  97%|█████████▋| 6909/7111 [26:28<00:38,  5.26it/s]

Reports:  97%|█████████▋| 6910/7111 [26:29<00:37,  5.30it/s]

Reports:  97%|█████████▋| 6911/7111 [26:29<00:37,  5.33it/s]

Reports:  97%|█████████▋| 6912/7111 [26:29<00:38,  5.18it/s]

Reports:  97%|█████████▋| 6913/7111 [26:29<00:38,  5.16it/s]

Reports:  97%|█████████▋| 6914/7111 [26:29<00:37,  5.21it/s]

Reports:  97%|█████████▋| 6915/7111 [26:30<00:38,  5.11it/s]

Reports:  97%|█████████▋| 6916/7111 [26:30<00:37,  5.19it/s]

Reports:  97%|█████████▋| 6917/7111 [26:30<00:36,  5.26it/s]

Reports:  97%|█████████▋| 6918/7111 [26:30<00:37,  5.18it/s]

Reports:  97%|█████████▋| 6919/7111 [26:30<00:37,  5.13it/s]

Reports:  97%|█████████▋| 6920/7111 [26:31<00:36,  5.21it/s]

Reports:  97%|█████████▋| 6921/7111 [26:31<00:56,  3.37it/s]

Reports:  97%|█████████▋| 6922/7111 [26:31<00:50,  3.77it/s]

Reports:  97%|█████████▋| 6923/7111 [26:32<00:45,  4.10it/s]

Reports:  97%|█████████▋| 6924/7111 [26:32<00:42,  4.36it/s]

Reports:  97%|█████████▋| 6925/7111 [26:32<00:40,  4.62it/s]

Reports:  97%|█████████▋| 6926/7111 [26:32<00:39,  4.66it/s]

Reports:  97%|█████████▋| 6927/7111 [26:32<00:38,  4.74it/s]

Reports:  97%|█████████▋| 6928/7111 [26:33<00:38,  4.77it/s]

Reports:  97%|█████████▋| 6929/7111 [26:33<00:36,  4.94it/s]

Reports:  97%|█████████▋| 6930/7111 [26:33<00:35,  5.07it/s]

Reports:  97%|█████████▋| 6931/7111 [26:33<00:35,  5.13it/s]

Reports:  97%|█████████▋| 6932/7111 [26:33<00:34,  5.21it/s]

Reports:  97%|█████████▋| 6933/7111 [26:33<00:34,  5.20it/s]

Reports:  98%|█████████▊| 6934/7111 [26:34<00:34,  5.12it/s]

Reports:  98%|█████████▊| 6935/7111 [26:34<00:33,  5.21it/s]

Reports:  98%|█████████▊| 6936/7111 [26:34<00:33,  5.27it/s]

Reports:  98%|█████████▊| 6937/7111 [26:34<00:32,  5.27it/s]

Reports:  98%|█████████▊| 6938/7111 [26:34<00:32,  5.32it/s]

Reports:  98%|█████████▊| 6939/7111 [26:35<00:32,  5.33it/s]

Reports:  98%|█████████▊| 6940/7111 [26:35<00:32,  5.34it/s]

Reports:  98%|█████████▊| 6941/7111 [26:35<00:31,  5.36it/s]

Reports:  98%|█████████▊| 6942/7111 [26:35<00:31,  5.38it/s]

Reports:  98%|█████████▊| 6943/7111 [26:35<00:31,  5.30it/s]

Reports:  98%|█████████▊| 6944/7111 [26:36<00:31,  5.35it/s]

Reports:  98%|█████████▊| 6945/7111 [26:36<00:31,  5.33it/s]

Reports:  98%|█████████▊| 6946/7111 [26:36<00:31,  5.21it/s]

Reports:  98%|█████████▊| 6947/7111 [26:36<00:32,  5.07it/s]

Reports:  98%|█████████▊| 6948/7111 [26:36<00:31,  5.13it/s]

Reports:  98%|█████████▊| 6949/7111 [26:36<00:31,  5.21it/s]

Reports:  98%|█████████▊| 6950/7111 [26:37<00:30,  5.26it/s]

Reports:  98%|█████████▊| 6951/7111 [26:37<00:31,  5.12it/s]

Reports:  98%|█████████▊| 6952/7111 [26:37<00:30,  5.14it/s]

Reports:  98%|█████████▊| 6953/7111 [26:37<00:30,  5.19it/s]

Reports:  98%|█████████▊| 6954/7111 [26:37<00:30,  5.23it/s]

Reports:  98%|█████████▊| 6955/7111 [26:38<00:29,  5.27it/s]

Reports:  98%|█████████▊| 6956/7111 [26:38<00:29,  5.32it/s]

Reports:  98%|█████████▊| 6957/7111 [26:38<00:29,  5.20it/s]

Reports:  98%|█████████▊| 6958/7111 [26:38<00:29,  5.18it/s]

Reports:  98%|█████████▊| 6959/7111 [26:38<00:29,  5.12it/s]

Reports:  98%|█████████▊| 6960/7111 [26:39<00:31,  4.82it/s]

Reports:  98%|█████████▊| 6961/7111 [26:39<00:30,  4.93it/s]

Reports:  98%|█████████▊| 6962/7111 [26:39<00:29,  5.08it/s]

Reports:  98%|█████████▊| 6963/7111 [26:39<00:29,  5.05it/s]

Reports:  98%|█████████▊| 6964/7111 [26:39<00:29,  5.04it/s]

Reports:  98%|█████████▊| 6965/7111 [26:40<00:28,  5.09it/s]

Reports:  98%|█████████▊| 6966/7111 [26:40<00:28,  5.14it/s]

Reports:  98%|█████████▊| 6967/7111 [26:40<00:27,  5.20it/s]

Reports:  98%|█████████▊| 6968/7111 [26:40<00:27,  5.14it/s]

Reports:  98%|█████████▊| 6969/7111 [26:40<00:27,  5.16it/s]

Reports:  98%|█████████▊| 6970/7111 [26:41<00:27,  5.17it/s]

Reports:  98%|█████████▊| 6971/7111 [26:41<00:27,  5.13it/s]

Reports:  98%|█████████▊| 6972/7111 [26:41<00:27,  5.12it/s]

Reports:  98%|█████████▊| 6973/7111 [26:41<00:27,  5.07it/s]

Reports:  98%|█████████▊| 6974/7111 [26:41<00:26,  5.13it/s]

Reports:  98%|█████████▊| 6975/7111 [26:42<00:27,  5.02it/s]

Reports:  98%|█████████▊| 6976/7111 [26:42<00:26,  5.00it/s]

Reports:  98%|█████████▊| 6977/7111 [26:42<00:26,  5.02it/s]

Reports:  98%|█████████▊| 6978/7111 [26:42<00:26,  5.10it/s]

Reports:  98%|█████████▊| 6979/7111 [26:42<00:25,  5.16it/s]

Reports:  98%|█████████▊| 6980/7111 [26:43<00:25,  5.21it/s]

Reports:  98%|█████████▊| 6981/7111 [26:43<00:24,  5.23it/s]

Reports:  98%|█████████▊| 6982/7111 [26:43<00:24,  5.29it/s]

Reports:  98%|█████████▊| 6983/7111 [26:43<00:25,  5.12it/s]

Reports:  98%|█████████▊| 6984/7111 [26:43<00:24,  5.17it/s]

Reports:  98%|█████████▊| 6985/7111 [26:44<00:24,  5.15it/s]

Reports:  98%|█████████▊| 6986/7111 [26:44<00:24,  5.21it/s]

Reports:  98%|█████████▊| 6987/7111 [26:44<00:23,  5.27it/s]

Reports:  98%|█████████▊| 6988/7111 [26:44<00:23,  5.30it/s]

Reports:  98%|█████████▊| 6989/7111 [26:44<00:23,  5.18it/s]

Reports:  98%|█████████▊| 6990/7111 [26:44<00:23,  5.23it/s]

Reports:  98%|█████████▊| 6991/7111 [26:45<00:22,  5.29it/s]

Reports:  98%|█████████▊| 6992/7111 [26:45<00:39,  3.01it/s]

Reports:  98%|█████████▊| 6993/7111 [26:46<00:34,  3.43it/s]

Reports:  98%|█████████▊| 6994/7111 [26:46<00:32,  3.65it/s]

Reports:  98%|█████████▊| 6995/7111 [26:46<00:29,  3.99it/s]

Reports:  98%|█████████▊| 6996/7111 [26:46<00:26,  4.34it/s]

Reports:  98%|█████████▊| 6997/7111 [26:46<00:24,  4.61it/s]

Reports:  98%|█████████▊| 6998/7111 [26:46<00:23,  4.77it/s]

Reports:  98%|█████████▊| 6999/7111 [26:47<00:23,  4.81it/s]

Reports:  98%|█████████▊| 7000/7111 [26:47<00:22,  4.92it/s]

Reports:  98%|█████████▊| 7001/7111 [26:47<00:22,  4.82it/s]

Reports:  98%|█████████▊| 7002/7111 [26:47<00:21,  4.96it/s]

Reports:  98%|█████████▊| 7003/7111 [26:47<00:21,  5.10it/s]

Reports:  98%|█████████▊| 7004/7111 [26:48<00:20,  5.15it/s]

Reports:  99%|█████████▊| 7005/7111 [26:48<00:24,  4.40it/s]

Reports:  99%|█████████▊| 7006/7111 [26:48<00:22,  4.65it/s]

Reports:  99%|█████████▊| 7007/7111 [26:48<00:21,  4.75it/s]

Reports:  99%|█████████▊| 7008/7111 [26:49<00:21,  4.90it/s]

Reports:  99%|█████████▊| 7009/7111 [26:49<00:20,  4.94it/s]

Reports:  99%|█████████▊| 7010/7111 [26:49<00:19,  5.05it/s]

Reports:  99%|█████████▊| 7011/7111 [26:49<00:19,  5.12it/s]

Reports:  99%|█████████▊| 7012/7111 [26:49<00:19,  5.17it/s]

Reports:  99%|█████████▊| 7013/7111 [26:50<00:18,  5.18it/s]

Reports:  99%|█████████▊| 7014/7111 [26:50<00:18,  5.26it/s]

Reports:  99%|█████████▊| 7015/7111 [26:50<00:18,  5.12it/s]

Reports:  99%|█████████▊| 7016/7111 [26:50<00:18,  5.04it/s]

Reports:  99%|█████████▊| 7017/7111 [26:50<00:18,  5.13it/s]

Reports:  99%|█████████▊| 7018/7111 [26:50<00:17,  5.22it/s]

Reports:  99%|█████████▊| 7019/7111 [26:51<00:17,  5.25it/s]

Reports:  99%|█████████▊| 7020/7111 [26:51<00:17,  5.27it/s]

Reports:  99%|█████████▊| 7021/7111 [26:51<00:16,  5.31it/s]

Reports:  99%|█████████▊| 7022/7111 [26:51<00:16,  5.30it/s]

Reports:  99%|█████████▉| 7023/7111 [26:51<00:16,  5.35it/s]

Reports:  99%|█████████▉| 7024/7111 [26:52<00:16,  5.17it/s]

Reports:  99%|█████████▉| 7025/7111 [26:52<00:16,  5.21it/s]

Reports:  99%|█████████▉| 7026/7111 [26:52<00:16,  5.17it/s]

Reports:  99%|█████████▉| 7027/7111 [26:52<00:16,  5.23it/s]

Reports:  99%|█████████▉| 7028/7111 [26:52<00:16,  5.14it/s]

Reports:  99%|█████████▉| 7029/7111 [26:53<00:15,  5.18it/s]

Reports:  99%|█████████▉| 7030/7111 [26:53<00:15,  5.18it/s]

Reports:  99%|█████████▉| 7031/7111 [26:53<00:15,  5.20it/s]

Reports:  99%|█████████▉| 7032/7111 [26:53<00:15,  5.25it/s]

Reports:  99%|█████████▉| 7033/7111 [26:53<00:14,  5.29it/s]

Reports:  99%|█████████▉| 7034/7111 [26:54<00:14,  5.30it/s]

Reports:  99%|█████████▉| 7035/7111 [26:54<00:14,  5.26it/s]

Reports:  99%|█████████▉| 7036/7111 [26:54<00:14,  5.29it/s]

Reports:  99%|█████████▉| 7037/7111 [26:54<00:14,  5.22it/s]

Reports:  99%|█████████▉| 7038/7111 [26:54<00:13,  5.24it/s]

Reports:  99%|█████████▉| 7039/7111 [26:54<00:13,  5.19it/s]

Reports:  99%|█████████▉| 7040/7111 [26:55<00:13,  5.24it/s]

Reports:  99%|█████████▉| 7041/7111 [26:55<00:13,  5.27it/s]

Reports:  99%|█████████▉| 7042/7111 [26:55<00:13,  5.26it/s]

Reports:  99%|█████████▉| 7043/7111 [26:55<00:12,  5.26it/s]

Reports:  99%|█████████▉| 7044/7111 [26:56<00:15,  4.35it/s]

Reports:  99%|█████████▉| 7045/7111 [26:56<00:14,  4.55it/s]

Reports:  99%|█████████▉| 7046/7111 [26:56<00:14,  4.60it/s]

Reports:  99%|█████████▉| 7047/7111 [26:56<00:13,  4.69it/s]

Reports:  99%|█████████▉| 7048/7111 [26:56<00:13,  4.77it/s]

Reports:  99%|█████████▉| 7049/7111 [26:57<00:12,  4.81it/s]

Reports:  99%|█████████▉| 7050/7111 [26:57<00:12,  4.88it/s]

Reports:  99%|█████████▉| 7051/7111 [26:57<00:11,  5.02it/s]

Reports:  99%|█████████▉| 7052/7111 [26:57<00:11,  5.02it/s]

Reports:  99%|█████████▉| 7053/7111 [26:57<00:11,  5.10it/s]

Reports:  99%|█████████▉| 7054/7111 [26:58<00:11,  5.06it/s]

Reports:  99%|█████████▉| 7055/7111 [26:58<00:11,  5.07it/s]

Reports:  99%|█████████▉| 7056/7111 [26:58<00:10,  5.05it/s]

Reports:  99%|█████████▉| 7057/7111 [26:58<00:10,  5.08it/s]

Reports:  99%|█████████▉| 7058/7111 [26:58<00:10,  5.16it/s]

Reports:  99%|█████████▉| 7059/7111 [26:59<00:09,  5.21it/s]

Reports:  99%|█████████▉| 7060/7111 [26:59<00:09,  5.15it/s]

Reports:  99%|█████████▉| 7061/7111 [26:59<00:09,  5.20it/s]

Reports:  99%|█████████▉| 7062/7111 [26:59<00:09,  5.20it/s]

Reports:  99%|█████████▉| 7063/7111 [26:59<00:09,  5.27it/s]

Reports:  99%|█████████▉| 7064/7111 [26:59<00:09,  5.15it/s]

Reports:  99%|█████████▉| 7065/7111 [27:00<00:08,  5.16it/s]

Reports:  99%|█████████▉| 7066/7111 [27:00<00:08,  5.18it/s]

Reports:  99%|█████████▉| 7067/7111 [27:00<00:08,  5.17it/s]

Reports:  99%|█████████▉| 7068/7111 [27:00<00:08,  5.06it/s]

Reports:  99%|█████████▉| 7069/7111 [27:00<00:08,  5.08it/s]

Reports:  99%|█████████▉| 7070/7111 [27:01<00:07,  5.15it/s]

Reports:  99%|█████████▉| 7071/7111 [27:01<00:07,  5.21it/s]

Reports:  99%|█████████▉| 7072/7111 [27:01<00:07,  5.23it/s]

Reports:  99%|█████████▉| 7073/7111 [27:01<00:07,  5.25it/s]

Reports:  99%|█████████▉| 7074/7111 [27:01<00:06,  5.30it/s]

Reports:  99%|█████████▉| 7075/7111 [27:02<00:06,  5.22it/s]

Reports: 100%|█████████▉| 7076/7111 [27:02<00:06,  5.24it/s]

Reports: 100%|█████████▉| 7077/7111 [27:02<00:06,  5.26it/s]

Reports: 100%|█████████▉| 7078/7111 [27:02<00:06,  5.19it/s]

Reports: 100%|█████████▉| 7079/7111 [27:02<00:06,  5.25it/s]

Reports: 100%|█████████▉| 7080/7111 [27:03<00:05,  5.20it/s]

Reports: 100%|█████████▉| 7081/7111 [27:03<00:05,  5.07it/s]

Reports: 100%|█████████▉| 7082/7111 [27:03<00:05,  5.03it/s]

Reports: 100%|█████████▉| 7083/7111 [27:03<00:05,  5.02it/s]

Reports: 100%|█████████▉| 7084/7111 [27:03<00:05,  5.00it/s]

Reports: 100%|█████████▉| 7085/7111 [27:04<00:05,  4.69it/s]

Reports: 100%|█████████▉| 7086/7111 [27:04<00:05,  4.87it/s]

Reports: 100%|█████████▉| 7087/7111 [27:04<00:04,  5.04it/s]

Reports: 100%|█████████▉| 7088/7111 [27:04<00:04,  5.03it/s]

Reports: 100%|█████████▉| 7089/7111 [27:04<00:04,  5.07it/s]

Reports: 100%|█████████▉| 7090/7111 [27:05<00:04,  5.18it/s]

Reports: 100%|█████████▉| 7091/7111 [27:05<00:03,  5.15it/s]

Reports: 100%|█████████▉| 7092/7111 [27:05<00:03,  5.16it/s]

Reports: 100%|█████████▉| 7093/7111 [27:05<00:03,  5.22it/s]

Reports: 100%|█████████▉| 7094/7111 [27:05<00:03,  5.19it/s]

Reports: 100%|█████████▉| 7095/7111 [27:06<00:03,  5.13it/s]

Reports: 100%|█████████▉| 7096/7111 [27:06<00:02,  5.15it/s]

Reports: 100%|█████████▉| 7097/7111 [27:06<00:02,  5.17it/s]

Reports: 100%|█████████▉| 7098/7111 [27:06<00:02,  5.14it/s]

Reports: 100%|█████████▉| 7099/7111 [27:06<00:02,  5.20it/s]

Reports: 100%|█████████▉| 7100/7111 [27:06<00:02,  5.21it/s]

Reports: 100%|█████████▉| 7101/7111 [27:07<00:01,  5.27it/s]

Reports: 100%|█████████▉| 7102/7111 [27:07<00:01,  5.22it/s]

Reports: 100%|█████████▉| 7103/7111 [27:07<00:01,  5.16it/s]

Reports: 100%|█████████▉| 7104/7111 [27:07<00:01,  5.10it/s]

Reports: 100%|█████████▉| 7105/7111 [27:07<00:01,  5.08it/s]

Reports: 100%|█████████▉| 7106/7111 [27:08<00:00,  5.01it/s]

Reports: 100%|█████████▉| 7107/7111 [27:08<00:00,  5.14it/s]

Reports: 100%|█████████▉| 7108/7111 [27:08<00:00,  5.17it/s]

Reports: 100%|█████████▉| 7109/7111 [27:08<00:00,  5.09it/s]

Reports: 100%|█████████▉| 7110/7111 [27:08<00:00,  5.14it/s]

Reports: 100%|██████████| 7111/7111 [27:09<00:00,  5.14it/s]

Reports: 100%|██████████| 7111/7111 [27:09<00:00,  4.36it/s]

Report rows: 5658

Gaps (ex-reports):   0%|          | 0/7111 [00:00<?, ?it/s]

Gaps (ex-reports):   0%|          | 1/7111 [00:00<23:27,  5.05it/s]

Gaps (ex-reports):   0%|          | 2/7111 [00:00<25:16,  4.69it/s]

Gaps (ex-reports):   0%|          | 3/7111 [00:00<24:54,  4.76it/s]

Gaps (ex-reports):   0%|          | 4/7111 [00:00<24:43,  4.79it/s]

Gaps (ex-reports):   0%|          | 5/7111 [00:01<23:55,  4.95it/s]

Gaps (ex-reports):   0%|          | 6/7111 [00:01<24:00,  4.93it/s]

Gaps (ex-reports):   0%|          | 7/7111 [00:01<24:03,  4.92it/s]

Gaps (ex-reports):   0%|          | 8/7111 [00:01<24:14,  4.88it/s]

Gaps (ex-reports):   0%|          | 9/7111 [00:01<24:01,  4.93it/s]

Gaps (ex-reports):   0%|          | 10/7111 [00:02<23:48,  4.97it/s]

Gaps (ex-reports):   0%|          | 11/7111 [00:02<27:59,  4.23it/s]

Gaps (ex-reports):   0%|          | 12/7111 [00:02<26:59,  4.38it/s]

Gaps (ex-reports):   0%|          | 13/7111 [00:02<25:39,  4.61it/s]

Gaps (ex-reports):   0%|          | 14/7111 [00:02<24:56,  4.74it/s]

Gaps (ex-reports):   0%|          | 15/7111 [00:03<25:02,  4.72it/s]

Gaps (ex-reports):   0%|          | 16/7111 [00:03<24:43,  4.78it/s]

Gaps (ex-reports):   0%|          | 17/7111 [00:03<24:31,  4.82it/s]

Gaps (ex-reports):   0%|          | 18/7111 [00:03<24:01,  4.92it/s]

Gaps (ex-reports):   0%|          | 19/7111 [00:03<24:07,  4.90it/s]

Gaps (ex-reports):   0%|          | 20/7111 [00:04<23:45,  4.97it/s]

Gaps (ex-reports):   0%|          | 21/7111 [00:04<24:12,  4.88it/s]

Gaps (ex-reports):   0%|          | 22/7111 [00:04<24:17,  4.86it/s]

Gaps (ex-reports):   0%|          | 23/7111 [00:04<24:12,  4.88it/s]

Gaps (ex-reports):   0%|          | 24/7111 [00:04<23:43,  4.98it/s]

Gaps (ex-reports):   0%|          | 25/7111 [00:05<23:54,  4.94it/s]

Gaps (ex-reports):   0%|          | 26/7111 [00:05<23:31,  5.02it/s]

Gaps (ex-reports):   0%|          | 27/7111 [00:05<23:52,  4.95it/s]

Gaps (ex-reports):   0%|          | 28/7111 [00:05<23:58,  4.92it/s]

Gaps (ex-reports):   0%|          | 29/7111 [00:05<23:28,  5.03it/s]

Gaps (ex-reports):   0%|          | 30/7111 [00:06<24:00,  4.92it/s]

Gaps (ex-reports):   0%|          | 31/7111 [00:06<24:02,  4.91it/s]

Gaps (ex-reports):   0%|          | 32/7111 [00:06<23:36,  5.00it/s]

Gaps (ex-reports):   0%|          | 33/7111 [00:06<23:24,  5.04it/s]

Gaps (ex-reports):   0%|          | 34/7111 [00:06<23:41,  4.98it/s]

Gaps (ex-reports):   0%|          | 35/7111 [00:07<24:09,  4.88it/s]

Gaps (ex-reports):   1%|          | 36/7111 [00:07<24:00,  4.91it/s]

Gaps (ex-reports):   1%|          | 37/7111 [00:07<23:33,  5.00it/s]

Gaps (ex-reports):   1%|          | 38/7111 [00:07<23:27,  5.02it/s]

Gaps (ex-reports):   1%|          | 39/7111 [00:08<23:40,  4.98it/s]

Gaps (ex-reports):   1%|          | 40/7111 [00:08<23:58,  4.91it/s]

Gaps (ex-reports):   1%|          | 41/7111 [00:08<24:14,  4.86it/s]

Gaps (ex-reports):   1%|          | 42/7111 [00:08<24:09,  4.88it/s]

Gaps (ex-reports):   1%|          | 43/7111 [00:08<24:17,  4.85it/s]

Gaps (ex-reports):   1%|          | 44/7111 [00:09<24:27,  4.82it/s]

Gaps (ex-reports):   1%|          | 45/7111 [00:09<24:31,  4.80it/s]

Gaps (ex-reports):   1%|          | 46/7111 [00:09<24:24,  4.82it/s]

Gaps (ex-reports):   1%|          | 47/7111 [00:09<24:31,  4.80it/s]

Gaps (ex-reports):   1%|          | 48/7111 [00:09<24:12,  4.86it/s]

Gaps (ex-reports):   1%|          | 49/7111 [00:10<24:05,  4.89it/s]

Gaps (ex-reports):   1%|          | 50/7111 [00:10<23:56,  4.91it/s]

Gaps (ex-reports):   1%|          | 51/7111 [00:10<24:09,  4.87it/s]

Gaps (ex-reports):   1%|          | 52/7111 [00:10<24:36,  4.78it/s]

Gaps (ex-reports):   1%|          | 53/7111 [00:10<24:20,  4.83it/s]

Gaps (ex-reports):   1%|          | 54/7111 [00:11<24:05,  4.88it/s]

Gaps (ex-reports):   1%|          | 55/7111 [00:11<23:38,  4.98it/s]

Gaps (ex-reports):   1%|          | 56/7111 [00:11<23:28,  5.01it/s]

Gaps (ex-reports):   1%|          | 57/7111 [00:11<23:17,  5.05it/s]

Gaps (ex-reports):   1%|          | 58/7111 [00:11<23:32,  4.99it/s]

Gaps (ex-reports):   1%|          | 59/7111 [00:12<23:13,  5.06it/s]

Gaps (ex-reports):   1%|          | 60/7111 [00:12<23:32,  4.99it/s]

Gaps (ex-reports):   1%|          | 61/7111 [00:12<23:18,  5.04it/s]

Gaps (ex-reports):   1%|          | 62/7111 [00:12<23:35,  4.98it/s]

Gaps (ex-reports):   1%|          | 63/7111 [00:12<23:14,  5.05it/s]

Gaps (ex-reports):   1%|          | 64/7111 [00:13<22:58,  5.11it/s]

Gaps (ex-reports):   1%|          | 65/7111 [00:13<23:24,  5.02it/s]

Gaps (ex-reports):   1%|          | 66/7111 [00:13<23:23,  5.02it/s]

Gaps (ex-reports):   1%|          | 67/7111 [00:13<23:31,  4.99it/s]

Gaps (ex-reports):   1%|          | 68/7111 [00:13<23:45,  4.94it/s]

Gaps (ex-reports):   1%|          | 69/7111 [00:14<23:51,  4.92it/s]

Gaps (ex-reports):   1%|          | 70/7111 [00:14<26:36,  4.41it/s]

Gaps (ex-reports):   1%|          | 71/7111 [00:14<25:54,  4.53it/s]

Gaps (ex-reports):   1%|          | 72/7111 [00:14<25:31,  4.60it/s]

Gaps (ex-reports):   1%|          | 73/7111 [00:14<24:59,  4.69it/s]

Gaps (ex-reports):   1%|          | 74/7111 [00:15<25:00,  4.69it/s]

Gaps (ex-reports):   1%|          | 75/7111 [00:15<24:55,  4.70it/s]

Gaps (ex-reports):   1%|          | 76/7111 [00:15<24:34,  4.77it/s]

Gaps (ex-reports):   1%|          | 77/7111 [00:15<24:47,  4.73it/s]

Gaps (ex-reports):   1%|          | 78/7111 [00:16<25:06,  4.67it/s]

Gaps (ex-reports):   1%|          | 79/7111 [00:16<24:28,  4.79it/s]

Gaps (ex-reports):   1%|          | 80/7111 [00:16<24:05,  4.86it/s]

Gaps (ex-reports):   1%|          | 81/7111 [00:16<24:05,  4.86it/s]

Gaps (ex-reports):   1%|          | 82/7111 [00:16<24:05,  4.86it/s]

Gaps (ex-reports):   1%|          | 83/7111 [00:17<23:59,  4.88it/s]

Gaps (ex-reports):   1%|          | 84/7111 [00:17<23:36,  4.96it/s]

Gaps (ex-reports):   1%|          | 85/7111 [00:17<24:03,  4.87it/s]

Gaps (ex-reports):   1%|          | 86/7111 [00:17<24:03,  4.87it/s]

Gaps (ex-reports):   1%|          | 87/7111 [00:17<24:01,  4.87it/s]

Gaps (ex-reports):   1%|          | 88/7111 [00:18<24:07,  4.85it/s]

Gaps (ex-reports):   1%|▏         | 89/7111 [00:18<23:38,  4.95it/s]

Gaps (ex-reports):   1%|▏         | 90/7111 [00:18<23:52,  4.90it/s]

Gaps (ex-reports):   1%|▏         | 91/7111 [00:18<23:32,  4.97it/s]

Gaps (ex-reports):   1%|▏         | 92/7111 [00:18<23:43,  4.93it/s]

Gaps (ex-reports):   1%|▏         | 93/7111 [00:19<23:13,  5.04it/s]

Gaps (ex-reports):   1%|▏         | 94/7111 [00:19<25:16,  4.63it/s]

Gaps (ex-reports):   1%|▏         | 95/7111 [00:19<24:52,  4.70it/s]

Gaps (ex-reports):   1%|▏         | 96/7111 [00:19<24:19,  4.81it/s]

Gaps (ex-reports):   1%|▏         | 97/7111 [00:19<24:07,  4.85it/s]

Gaps (ex-reports):   1%|▏         | 98/7111 [00:20<24:09,  4.84it/s]

Gaps (ex-reports):   1%|▏         | 99/7111 [00:20<24:22,  4.79it/s]

Gaps (ex-reports):   1%|▏         | 100/7111 [00:20<24:16,  4.81it/s]

Gaps (ex-reports):   1%|▏         | 101/7111 [00:20<23:48,  4.91it/s]

Gaps (ex-reports):   1%|▏         | 102/7111 [00:21<24:53,  4.69it/s]

Gaps (ex-reports):   1%|▏         | 103/7111 [00:21<24:15,  4.81it/s]

Gaps (ex-reports):   1%|▏         | 104/7111 [00:21<24:17,  4.81it/s]

Gaps (ex-reports):   1%|▏         | 105/7111 [00:21<24:11,  4.83it/s]

Gaps (ex-reports):   1%|▏         | 106/7111 [00:21<23:44,  4.92it/s]

Gaps (ex-reports):   2%|▏         | 107/7111 [00:21<23:23,  4.99it/s]

Gaps (ex-reports):   2%|▏         | 108/7111 [00:22<23:31,  4.96it/s]

Gaps (ex-reports):   2%|▏         | 109/7111 [00:22<23:25,  4.98it/s]

Gaps (ex-reports):   2%|▏         | 110/7111 [00:22<23:46,  4.91it/s]

Gaps (ex-reports):   2%|▏         | 111/7111 [00:22<23:52,  4.89it/s]

Gaps (ex-reports):   2%|▏         | 112/7111 [00:23<23:41,  4.92it/s]

Gaps (ex-reports):   2%|▏         | 113/7111 [00:23<23:21,  4.99it/s]

Gaps (ex-reports):   2%|▏         | 114/7111 [00:23<23:45,  4.91it/s]

Gaps (ex-reports):   2%|▏         | 115/7111 [00:23<24:14,  4.81it/s]

Gaps (ex-reports):   2%|▏         | 116/7111 [00:23<24:23,  4.78it/s]

Gaps (ex-reports):   2%|▏         | 117/7111 [00:24<24:22,  4.78it/s]

Gaps (ex-reports):   2%|▏         | 118/7111 [00:24<25:00,  4.66it/s]

Gaps (ex-reports):   2%|▏         | 119/7111 [00:24<24:44,  4.71it/s]

Gaps (ex-reports):   2%|▏         | 120/7111 [00:24<24:25,  4.77it/s]

Gaps (ex-reports):   2%|▏         | 121/7111 [00:24<23:51,  4.88it/s]

Gaps (ex-reports):   2%|▏         | 122/7111 [00:25<23:20,  4.99it/s]

Gaps (ex-reports):   2%|▏         | 123/7111 [00:25<23:31,  4.95it/s]

Gaps (ex-reports):   2%|▏         | 124/7111 [00:25<23:41,  4.91it/s]

Gaps (ex-reports):   2%|▏         | 125/7111 [00:25<23:51,  4.88it/s]

Gaps (ex-reports):   2%|▏         | 126/7111 [00:25<23:57,  4.86it/s]

Gaps (ex-reports):   2%|▏         | 127/7111 [00:26<24:37,  4.73it/s]

Gaps (ex-reports):   2%|▏         | 128/7111 [00:26<24:45,  4.70it/s]

Gaps (ex-reports):   2%|▏         | 129/7111 [00:26<24:20,  4.78it/s]

Gaps (ex-reports):   2%|▏         | 130/7111 [00:26<24:05,  4.83it/s]

Gaps (ex-reports):   2%|▏         | 131/7111 [00:26<24:02,  4.84it/s]

Gaps (ex-reports):   2%|▏         | 132/7111 [00:27<24:27,  4.76it/s]

Gaps (ex-reports):   2%|▏         | 133/7111 [00:27<23:59,  4.85it/s]

Gaps (ex-reports):   2%|▏         | 134/7111 [00:27<23:56,  4.86it/s]

Gaps (ex-reports):   2%|▏         | 135/7111 [00:27<23:52,  4.87it/s]

Gaps (ex-reports):   2%|▏         | 136/7111 [00:27<23:41,  4.91it/s]

Gaps (ex-reports):   2%|▏         | 137/7111 [00:28<23:45,  4.89it/s]

Gaps (ex-reports):   2%|▏         | 138/7111 [00:28<23:16,  4.99it/s]

Gaps (ex-reports):   2%|▏         | 139/7111 [00:28<23:35,  4.93it/s]

Gaps (ex-reports):   2%|▏         | 140/7111 [00:28<24:06,  4.82it/s]

Gaps (ex-reports):   2%|▏         | 141/7111 [00:29<23:43,  4.90it/s]

Gaps (ex-reports):   2%|▏         | 142/7111 [00:29<23:22,  4.97it/s]

Gaps (ex-reports):   2%|▏         | 143/7111 [00:29<23:42,  4.90it/s]

Gaps (ex-reports):   2%|▏         | 144/7111 [00:29<23:33,  4.93it/s]

Gaps (ex-reports):   2%|▏         | 145/7111 [00:29<23:52,  4.86it/s]

Gaps (ex-reports):   2%|▏         | 146/7111 [00:30<24:03,  4.82it/s]

Gaps (ex-reports):   2%|▏         | 147/7111 [00:30<24:03,  4.82it/s]

Gaps (ex-reports):   2%|▏         | 148/7111 [00:30<24:02,  4.83it/s]

Gaps (ex-reports):   2%|▏         | 149/7111 [00:30<25:08,  4.61it/s]

Gaps (ex-reports):   2%|▏         | 150/7111 [00:30<24:29,  4.74it/s]

Gaps (ex-reports):   2%|▏         | 151/7111 [00:31<24:03,  4.82it/s]

Gaps (ex-reports):   2%|▏         | 152/7111 [00:31<24:15,  4.78it/s]

Gaps (ex-reports):   2%|▏         | 153/7111 [00:31<24:06,  4.81it/s]

Gaps (ex-reports):   2%|▏         | 154/7111 [00:31<23:28,  4.94it/s]

Gaps (ex-reports):   2%|▏         | 155/7111 [00:31<26:59,  4.29it/s]

Gaps (ex-reports):   2%|▏         | 156/7111 [00:32<26:40,  4.35it/s]

Gaps (ex-reports):   2%|▏         | 157/7111 [00:32<25:23,  4.56it/s]

Gaps (ex-reports):   2%|▏         | 158/7111 [00:32<25:21,  4.57it/s]

Gaps (ex-reports):   2%|▏         | 159/7111 [00:32<24:45,  4.68it/s]

Gaps (ex-reports):   2%|▏         | 160/7111 [00:33<24:51,  4.66it/s]

Gaps (ex-reports):   2%|▏         | 161/7111 [00:33<24:13,  4.78it/s]

Gaps (ex-reports):   2%|▏         | 162/7111 [00:33<23:37,  4.90it/s]

Gaps (ex-reports):   2%|▏         | 163/7111 [00:33<23:15,  4.98it/s]

Gaps (ex-reports):   2%|▏         | 164/7111 [00:33<22:48,  5.08it/s]

Gaps (ex-reports):   2%|▏         | 165/7111 [00:34<22:58,  5.04it/s]

Gaps (ex-reports):   2%|▏         | 166/7111 [00:34<22:56,  5.04it/s]

Gaps (ex-reports):   2%|▏         | 167/7111 [00:34<22:55,  5.05it/s]

Gaps (ex-reports):   2%|▏         | 168/7111 [00:34<23:13,  4.98it/s]

Gaps (ex-reports):   2%|▏         | 169/7111 [00:34<23:21,  4.95it/s]

Gaps (ex-reports):   2%|▏         | 170/7111 [00:35<23:19,  4.96it/s]

Gaps (ex-reports):   2%|▏         | 171/7111 [00:35<23:31,  4.92it/s]

Gaps (ex-reports):   2%|▏         | 172/7111 [00:35<22:50,  5.06it/s]

Gaps (ex-reports):   2%|▏         | 173/7111 [00:35<22:56,  5.04it/s]

Gaps (ex-reports):   2%|▏         | 174/7111 [00:35<23:24,  4.94it/s]

Gaps (ex-reports):   2%|▏         | 175/7111 [00:36<23:07,  5.00it/s]

Gaps (ex-reports):   2%|▏         | 176/7111 [00:36<22:54,  5.05it/s]

Gaps (ex-reports):   2%|▏         | 177/7111 [00:36<22:53,  5.05it/s]

Gaps (ex-reports):   3%|▎         | 178/7111 [00:36<22:53,  5.05it/s]

Gaps (ex-reports):   3%|▎         | 179/7111 [00:36<23:47,  4.86it/s]

Gaps (ex-reports):   3%|▎         | 180/7111 [00:37<23:29,  4.92it/s]

Gaps (ex-reports):   3%|▎         | 181/7111 [00:37<23:31,  4.91it/s]

Gaps (ex-reports):   3%|▎         | 182/7111 [00:37<23:18,  4.96it/s]

Gaps (ex-reports):   3%|▎         | 183/7111 [00:37<23:28,  4.92it/s]

Gaps (ex-reports):   3%|▎         | 184/7111 [00:37<23:34,  4.90it/s]

Gaps (ex-reports):   3%|▎         | 185/7111 [00:38<23:58,  4.82it/s]

Gaps (ex-reports):   3%|▎         | 186/7111 [00:38<23:33,  4.90it/s]

Gaps (ex-reports):   3%|▎         | 187/7111 [00:38<23:40,  4.87it/s]

Gaps (ex-reports):   3%|▎         | 188/7111 [00:38<23:26,  4.92it/s]

Gaps (ex-reports):   3%|▎         | 189/7111 [00:38<23:21,  4.94it/s]

Gaps (ex-reports):   3%|▎         | 190/7111 [00:39<23:47,  4.85it/s]

Gaps (ex-reports):   3%|▎         | 191/7111 [00:39<23:53,  4.83it/s]

Gaps (ex-reports):   3%|▎         | 192/7111 [00:39<23:55,  4.82it/s]

Gaps (ex-reports):   3%|▎         | 193/7111 [00:39<24:07,  4.78it/s]

Gaps (ex-reports):   3%|▎         | 194/7111 [00:39<23:36,  4.88it/s]

Gaps (ex-reports):   3%|▎         | 195/7111 [00:40<23:50,  4.84it/s]

Gaps (ex-reports):   3%|▎         | 196/7111 [00:40<23:52,  4.83it/s]

Gaps (ex-reports):   3%|▎         | 197/7111 [00:40<24:02,  4.79it/s]

Gaps (ex-reports):   3%|▎         | 198/7111 [00:40<23:47,  4.84it/s]

Gaps (ex-reports):   3%|▎         | 199/7111 [00:41<42:48,  2.69it/s]

Gaps (ex-reports):   3%|▎         | 200/7111 [00:41<37:04,  3.11it/s]

Gaps (ex-reports):   3%|▎         | 201/7111 [00:41<32:34,  3.54it/s]

Gaps (ex-reports):   3%|▎         | 202/7111 [00:42<29:32,  3.90it/s]

Gaps (ex-reports):   3%|▎         | 203/7111 [00:42<30:19,  3.80it/s]

Gaps (ex-reports):   3%|▎         | 204/7111 [00:42<28:12,  4.08it/s]

Gaps (ex-reports):   3%|▎         | 205/7111 [00:42<26:26,  4.35it/s]

Gaps (ex-reports):   3%|▎         | 206/7111 [00:43<28:26,  4.05it/s]

Gaps (ex-reports):   3%|▎         | 207/7111 [00:43<27:01,  4.26it/s]

Gaps (ex-reports):   3%|▎         | 208/7111 [00:43<26:12,  4.39it/s]

Gaps (ex-reports):   3%|▎         | 209/7111 [00:43<25:16,  4.55it/s]

Gaps (ex-reports):   3%|▎         | 210/7111 [00:43<24:35,  4.68it/s]

Gaps (ex-reports):   3%|▎         | 211/7111 [00:44<23:30,  4.89it/s]

Gaps (ex-reports):   3%|▎         | 212/7111 [00:44<23:31,  4.89it/s]

Gaps (ex-reports):   3%|▎         | 213/7111 [00:44<23:46,  4.84it/s]

Gaps (ex-reports):   3%|▎         | 214/7111 [00:44<23:15,  4.94it/s]

Gaps (ex-reports):   3%|▎         | 215/7111 [00:44<23:09,  4.96it/s]

Gaps (ex-reports):   3%|▎         | 216/7111 [00:45<23:57,  4.80it/s]

Gaps (ex-reports):   3%|▎         | 217/7111 [00:45<24:33,  4.68it/s]

Gaps (ex-reports):   3%|▎         | 218/7111 [00:45<24:09,  4.76it/s]

Gaps (ex-reports):   3%|▎         | 219/7111 [00:45<23:34,  4.87it/s]

Gaps (ex-reports):   3%|▎         | 220/7111 [00:45<23:33,  4.88it/s]

Gaps (ex-reports):   3%|▎         | 221/7111 [00:46<24:08,  4.76it/s]

Gaps (ex-reports):   3%|▎         | 222/7111 [00:46<23:28,  4.89it/s]

Gaps (ex-reports):   3%|▎         | 223/7111 [00:46<24:42,  4.65it/s]

Gaps (ex-reports):   3%|▎         | 224/7111 [00:46<24:16,  4.73it/s]

Gaps (ex-reports):   3%|▎         | 225/7111 [00:46<23:48,  4.82it/s]

Gaps (ex-reports):   3%|▎         | 226/7111 [00:47<23:15,  4.93it/s]

Gaps (ex-reports):   3%|▎         | 227/7111 [00:47<22:59,  4.99it/s]

Gaps (ex-reports):   3%|▎         | 228/7111 [00:48<1:06:04,  1.74it/s]

Gaps (ex-reports):   3%|▎         | 229/7111 [00:49<52:40,  2.18it/s]

Gaps (ex-reports):   3%|▎         | 230/7111 [00:49<44:23,  2.58it/s]

Gaps (ex-reports):   3%|▎         | 231/7111 [00:49<38:26,  2.98it/s]

Gaps (ex-reports):   3%|▎         | 232/7111 [00:49<33:14,  3.45it/s]

Gaps (ex-reports):   3%|▎         | 233/7111 [00:49<30:20,  3.78it/s]

Gaps (ex-reports):   3%|▎         | 234/7111 [00:50<28:24,  4.04it/s]

Gaps (ex-reports):   3%|▎         | 235/7111 [00:50<26:58,  4.25it/s]

Gaps (ex-reports):   3%|▎         | 236/7111 [00:50<26:07,  4.39it/s]

Gaps (ex-reports):   3%|▎         | 237/7111 [00:50<25:09,  4.55it/s]

Gaps (ex-reports):   3%|▎         | 238/7111 [00:50<24:52,  4.61it/s]

Gaps (ex-reports):   3%|▎         | 239/7111 [00:51<24:46,  4.62it/s]

Gaps (ex-reports):   3%|▎         | 240/7111 [00:51<24:41,  4.64it/s]

Gaps (ex-reports):   3%|▎         | 241/7111 [00:51<24:30,  4.67it/s]

Gaps (ex-reports):   3%|▎         | 242/7111 [00:52<34:42,  3.30it/s]

Gaps (ex-reports):   3%|▎         | 243/7111 [00:52<31:23,  3.65it/s]

Gaps (ex-reports):   3%|▎         | 244/7111 [00:52<28:39,  3.99it/s]

Gaps (ex-reports):   3%|▎         | 245/7111 [00:52<27:15,  4.20it/s]

Gaps (ex-reports):   3%|▎         | 246/7111 [00:52<26:06,  4.38it/s]

Gaps (ex-reports):   3%|▎         | 247/7111 [00:53<25:12,  4.54it/s]

Gaps (ex-reports):   3%|▎         | 248/7111 [00:53<24:58,  4.58it/s]

Gaps (ex-reports):   4%|▎         | 249/7111 [00:53<24:15,  4.71it/s]

Gaps (ex-reports):   4%|▎         | 250/7111 [00:53<23:51,  4.79it/s]

Gaps (ex-reports):   4%|▎         | 251/7111 [00:53<23:44,  4.81it/s]

Gaps (ex-reports):   4%|▎         | 252/7111 [00:54<23:38,  4.84it/s]

Gaps (ex-reports):   4%|▎         | 253/7111 [00:54<23:32,  4.86it/s]

Gaps (ex-reports):   4%|▎         | 254/7111 [00:54<23:09,  4.93it/s]

Gaps (ex-reports):   4%|▎         | 255/7111 [00:54<23:34,  4.85it/s]

Gaps (ex-reports):   4%|▎         | 256/7111 [00:54<23:24,  4.88it/s]

Gaps (ex-reports):   4%|▎         | 257/7111 [00:55<23:20,  4.89it/s]

Gaps (ex-reports):   4%|▎         | 258/7111 [00:55<23:16,  4.91it/s]

Gaps (ex-reports):   4%|▎         | 259/7111 [00:55<23:06,  4.94it/s]

Gaps (ex-reports):   4%|▎         | 260/7111 [00:55<22:44,  5.02it/s]

Gaps (ex-reports):   4%|▎         | 261/7111 [00:55<22:57,  4.97it/s]

Gaps (ex-reports):   4%|▎         | 262/7111 [00:56<22:54,  4.98it/s]

Gaps (ex-reports):   4%|▎         | 263/7111 [00:56<40:46,  2.80it/s]

Gaps (ex-reports):   4%|▎         | 264/7111 [00:56<35:26,  3.22it/s]

Gaps (ex-reports):   4%|▎         | 265/7111 [00:57<31:49,  3.59it/s]

Gaps (ex-reports):   4%|▎         | 266/7111 [00:58<1:19:57,  1.43it/s]

Gaps (ex-reports):   4%|▍         | 267/7111 [00:59<1:03:23,  1.80it/s]

Gaps (ex-reports):   4%|▍         | 268/7111 [00:59<50:52,  2.24it/s]

Gaps (ex-reports):   4%|▍         | 269/7111 [00:59<42:24,  2.69it/s]

Gaps (ex-reports):   4%|▍         | 270/7111 [00:59<36:08,  3.16it/s]

Gaps (ex-reports):   4%|▍         | 271/7111 [01:02<2:08:43,  1.13s/it]

Gaps (ex-reports):   4%|▍         | 272/7111 [01:02<1:36:43,  1.18it/s]

Gaps (ex-reports):   4%|▍         | 273/7111 [01:03<1:14:52,  1.52it/s]

Gaps (ex-reports):   4%|▍         | 274/7111 [01:03<59:29,  1.92it/s]

Gaps (ex-reports):   4%|▍         | 275/7111 [01:03<48:46,  2.34it/s]

Gaps (ex-reports):   4%|▍         | 276/7111 [01:03<41:10,  2.77it/s]

Gaps (ex-reports):   4%|▍         | 277/7111 [01:03<35:25,  3.22it/s]

Gaps (ex-reports):   4%|▍         | 278/7111 [01:04<31:13,  3.65it/s]

Gaps (ex-reports):   4%|▍         | 279/7111 [01:04<28:45,  3.96it/s]

Gaps (ex-reports):   4%|▍         | 280/7111 [01:04<26:52,  4.24it/s]

Gaps (ex-reports):   4%|▍         | 281/7111 [01:04<25:56,  4.39it/s]

Gaps (ex-reports):   4%|▍         | 282/7111 [01:08<2:30:47,  1.32s/it]

Gaps (ex-reports):   4%|▍         | 283/7111 [01:08<1:52:25,  1.01it/s]

Gaps (ex-reports):   4%|▍         | 284/7111 [01:09<1:26:33,  1.31it/s]

Gaps (ex-reports):   4%|▍         | 285/7111 [01:09<1:07:17,  1.69it/s]

Gaps (ex-reports):   4%|▍         | 286/7111 [01:09<54:19,  2.09it/s]

Gaps (ex-reports):   4%|▍         | 287/7111 [01:09<44:59,  2.53it/s]

Gaps (ex-reports):   4%|▍         | 288/7111 [01:09<38:32,  2.95it/s]

Gaps (ex-reports):   4%|▍         | 289/7111 [01:10<33:33,  3.39it/s]

Gaps (ex-reports):   4%|▍         | 290/7111 [01:10<30:42,  3.70it/s]

Gaps (ex-reports):   4%|▍         | 291/7111 [01:10<34:17,  3.31it/s]

Gaps (ex-reports):   4%|▍         | 292/7111 [01:10<31:48,  3.57it/s]

Gaps (ex-reports):   4%|▍         | 293/7111 [01:11<29:21,  3.87it/s]

Gaps (ex-reports):   4%|▍         | 294/7111 [01:11<27:28,  4.13it/s]

Gaps (ex-reports):   4%|▍         | 295/7111 [01:11<25:46,  4.41it/s]

Gaps (ex-reports):   4%|▍         | 296/7111 [01:11<25:08,  4.52it/s]

Gaps (ex-reports):   4%|▍         | 297/7111 [01:11<24:40,  4.60it/s]

Gaps (ex-reports):   4%|▍         | 298/7111 [01:12<23:47,  4.77it/s]

Gaps (ex-reports):   4%|▍         | 299/7111 [01:12<23:38,  4.80it/s]

Gaps (ex-reports):   4%|▍         | 300/7111 [01:12<23:29,  4.83it/s]

Gaps (ex-reports):   4%|▍         | 301/7111 [01:12<23:53,  4.75it/s]

Gaps (ex-reports):   4%|▍         | 302/7111 [01:12<23:58,  4.73it/s]

Gaps (ex-reports):   4%|▍         | 303/7111 [01:13<23:51,  4.76it/s]

Gaps (ex-reports):   4%|▍         | 304/7111 [01:13<23:46,  4.77it/s]

Gaps (ex-reports):   4%|▍         | 305/7111 [01:13<23:06,  4.91it/s]

Gaps (ex-reports):   4%|▍         | 306/7111 [01:13<23:27,  4.84it/s]

Gaps (ex-reports):   4%|▍         | 307/7111 [01:13<23:40,  4.79it/s]

Gaps (ex-reports):   4%|▍         | 308/7111 [01:14<23:21,  4.85it/s]

Gaps (ex-reports):   4%|▍         | 309/7111 [01:14<23:48,  4.76it/s]

Gaps (ex-reports):   4%|▍         | 310/7111 [01:14<24:17,  4.67it/s]

Gaps (ex-reports):   4%|▍         | 311/7111 [01:15<36:14,  3.13it/s]

Gaps (ex-reports):   4%|▍         | 312/7111 [01:15<32:06,  3.53it/s]

Gaps (ex-reports):   4%|▍         | 313/7111 [01:15<29:40,  3.82it/s]

Gaps (ex-reports):   4%|▍         | 314/7111 [01:15<27:45,  4.08it/s]

Gaps (ex-reports):   4%|▍         | 315/7111 [01:15<26:50,  4.22it/s]

Gaps (ex-reports):   4%|▍         | 316/7111 [01:16<26:40,  4.24it/s]

Gaps (ex-reports):   4%|▍         | 317/7111 [01:16<25:34,  4.43it/s]

Gaps (ex-reports):   4%|▍         | 318/7111 [01:16<24:34,  4.61it/s]

Gaps (ex-reports):   4%|▍         | 319/7111 [01:16<24:12,  4.68it/s]

Gaps (ex-reports):   5%|▍         | 320/7111 [01:17<24:01,  4.71it/s]

Gaps (ex-reports):   5%|▍         | 321/7111 [01:17<23:42,  4.77it/s]

Gaps (ex-reports):   5%|▍         | 322/7111 [01:17<23:13,  4.87it/s]

Gaps (ex-reports):   5%|▍         | 323/7111 [01:17<23:19,  4.85it/s]

Gaps (ex-reports):   5%|▍         | 324/7111 [01:17<22:50,  4.95it/s]

Gaps (ex-reports):   5%|▍         | 325/7111 [01:18<23:09,  4.89it/s]

Gaps (ex-reports):   5%|▍         | 326/7111 [01:18<23:18,  4.85it/s]

Gaps (ex-reports):   5%|▍         | 327/7111 [01:18<23:13,  4.87it/s]

Gaps (ex-reports):   5%|▍         | 328/7111 [01:18<23:29,  4.81it/s]

Gaps (ex-reports):   5%|▍         | 329/7111 [01:18<23:12,  4.87it/s]

Gaps (ex-reports):   5%|▍         | 330/7111 [01:19<35:57,  3.14it/s]

Gaps (ex-reports):   5%|▍         | 331/7111 [01:19<31:53,  3.54it/s]

Gaps (ex-reports):   5%|▍         | 332/7111 [01:19<29:24,  3.84it/s]

Gaps (ex-reports):   5%|▍         | 333/7111 [01:20<28:02,  4.03it/s]

Gaps (ex-reports):   5%|▍         | 334/7111 [01:20<26:14,  4.30it/s]

Gaps (ex-reports):   5%|▍         | 335/7111 [01:20<25:10,  4.49it/s]

Gaps (ex-reports):   5%|▍         | 336/7111 [01:20<24:54,  4.53it/s]

Gaps (ex-reports):   5%|▍         | 337/7111 [01:20<24:02,  4.69it/s]

Gaps (ex-reports):   5%|▍         | 338/7111 [01:21<23:41,  4.77it/s]

Gaps (ex-reports):   5%|▍         | 339/7111 [01:21<23:37,  4.78it/s]

Gaps (ex-reports):   5%|▍         | 340/7111 [01:21<23:01,  4.90it/s]

Gaps (ex-reports):   5%|▍         | 341/7111 [01:21<23:29,  4.80it/s]

Gaps (ex-reports):   5%|▍         | 342/7111 [01:21<23:31,  4.80it/s]

Gaps (ex-reports):   5%|▍         | 343/7111 [01:22<23:33,  4.79it/s]

Gaps (ex-reports):   5%|▍         | 344/7111 [01:22<23:19,  4.84it/s]

Gaps (ex-reports):   5%|▍         | 345/7111 [01:22<23:16,  4.85it/s]

Gaps (ex-reports):   5%|▍         | 346/7111 [01:22<23:21,  4.83it/s]

Gaps (ex-reports):   5%|▍         | 347/7111 [01:22<22:47,  4.95it/s]

Gaps (ex-reports):   5%|▍         | 348/7111 [01:23<23:15,  4.85it/s]

Gaps (ex-reports):   5%|▍         | 349/7111 [01:23<23:01,  4.89it/s]

Gaps (ex-reports):   5%|▍         | 350/7111 [01:23<23:02,  4.89it/s]

Gaps (ex-reports):   5%|▍         | 351/7111 [01:23<22:35,  4.99it/s]

Gaps (ex-reports):   5%|▍         | 352/7111 [01:23<22:22,  5.04it/s]

Gaps (ex-reports):   5%|▍         | 353/7111 [01:24<22:27,  5.01it/s]

Gaps (ex-reports):   5%|▍         | 354/7111 [01:24<22:26,  5.02it/s]

Gaps (ex-reports):   5%|▍         | 355/7111 [01:24<22:25,  5.02it/s]

Gaps (ex-reports):   5%|▌         | 356/7111 [01:24<22:27,  5.01it/s]

Gaps (ex-reports):   5%|▌         | 357/7111 [01:24<22:45,  4.95it/s]

Gaps (ex-reports):   5%|▌         | 358/7111 [01:25<23:09,  4.86it/s]

Gaps (ex-reports):   5%|▌         | 359/7111 [01:25<22:55,  4.91it/s]

Gaps (ex-reports):   5%|▌         | 360/7111 [01:25<22:44,  4.95it/s]

Gaps (ex-reports):   5%|▌         | 361/7111 [01:25<22:29,  5.00it/s]

Gaps (ex-reports):   5%|▌         | 362/7111 [01:25<22:53,  4.91it/s]

Gaps (ex-reports):   5%|▌         | 363/7111 [01:26<22:44,  4.94it/s]

Gaps (ex-reports):   5%|▌         | 364/7111 [01:26<23:00,  4.89it/s]

Gaps (ex-reports):   5%|▌         | 365/7111 [01:26<22:57,  4.90it/s]

Gaps (ex-reports):   5%|▌         | 366/7111 [01:26<23:32,  4.78it/s]

Gaps (ex-reports):   5%|▌         | 367/7111 [01:27<23:09,  4.85it/s]

Gaps (ex-reports):   5%|▌         | 368/7111 [01:27<23:14,  4.83it/s]

Gaps (ex-reports):   5%|▌         | 369/7111 [01:27<24:22,  4.61it/s]

Gaps (ex-reports):   5%|▌         | 370/7111 [01:27<23:58,  4.69it/s]

Gaps (ex-reports):   5%|▌         | 371/7111 [01:27<23:15,  4.83it/s]

Gaps (ex-reports):   5%|▌         | 372/7111 [01:28<22:56,  4.90it/s]

Gaps (ex-reports):   5%|▌         | 373/7111 [01:28<23:00,  4.88it/s]

Gaps (ex-reports):   5%|▌         | 374/7111 [01:28<23:10,  4.85it/s]

Gaps (ex-reports):   5%|▌         | 375/7111 [01:28<23:12,  4.84it/s]

Gaps (ex-reports):   5%|▌         | 376/7111 [01:28<23:16,  4.82it/s]

Gaps (ex-reports):   5%|▌         | 377/7111 [01:29<23:14,  4.83it/s]

Gaps (ex-reports):   5%|▌         | 378/7111 [01:29<23:19,  4.81it/s]

Gaps (ex-reports):   5%|▌         | 379/7111 [01:29<23:13,  4.83it/s]

Gaps (ex-reports):   5%|▌         | 380/7111 [01:29<23:09,  4.84it/s]

Gaps (ex-reports):   5%|▌         | 381/7111 [01:29<22:59,  4.88it/s]

Gaps (ex-reports):   5%|▌         | 382/7111 [01:30<22:50,  4.91it/s]

Gaps (ex-reports):   5%|▌         | 383/7111 [01:30<22:58,  4.88it/s]

Gaps (ex-reports):   5%|▌         | 384/7111 [01:30<22:45,  4.93it/s]

Gaps (ex-reports):   5%|▌         | 385/7111 [01:30<22:42,  4.94it/s]

Gaps (ex-reports):   5%|▌         | 386/7111 [01:30<22:54,  4.89it/s]

Gaps (ex-reports):   5%|▌         | 387/7111 [01:31<23:20,  4.80it/s]

Gaps (ex-reports):   5%|▌         | 388/7111 [01:31<22:47,  4.92it/s]

Gaps (ex-reports):   5%|▌         | 389/7111 [01:31<23:00,  4.87it/s]

Gaps (ex-reports):   5%|▌         | 390/7111 [01:31<22:54,  4.89it/s]

Gaps (ex-reports):   5%|▌         | 391/7111 [01:31<22:50,  4.90it/s]

Gaps (ex-reports):   6%|▌         | 392/7111 [01:32<22:41,  4.94it/s]

Gaps (ex-reports):   6%|▌         | 393/7111 [01:32<22:33,  4.96it/s]

Gaps (ex-reports):   6%|▌         | 394/7111 [01:32<22:50,  4.90it/s]

Gaps (ex-reports):   6%|▌         | 395/7111 [01:32<22:32,  4.97it/s]

Gaps (ex-reports):   6%|▌         | 396/7111 [01:32<22:13,  5.04it/s]

Gaps (ex-reports):   6%|▌         | 397/7111 [01:33<22:43,  4.92it/s]

Gaps (ex-reports):   6%|▌         | 398/7111 [01:33<22:32,  4.96it/s]

Gaps (ex-reports):   6%|▌         | 399/7111 [01:33<22:13,  5.03it/s]

Gaps (ex-reports):   6%|▌         | 400/7111 [01:33<21:56,  5.10it/s]

Gaps (ex-reports):   6%|▌         | 401/7111 [01:33<22:22,  5.00it/s]

Gaps (ex-reports):   6%|▌         | 402/7111 [01:34<22:51,  4.89it/s]

Gaps (ex-reports):   6%|▌         | 403/7111 [01:34<22:50,  4.89it/s]

Gaps (ex-reports):   6%|▌         | 404/7111 [01:34<22:59,  4.86it/s]

Gaps (ex-reports):   6%|▌         | 405/7111 [01:34<23:10,  4.82it/s]

Gaps (ex-reports):   6%|▌         | 406/7111 [01:34<23:04,  4.84it/s]

Gaps (ex-reports):   6%|▌         | 407/7111 [01:35<23:11,  4.82it/s]

Gaps (ex-reports):   6%|▌         | 408/7111 [01:35<23:01,  4.85it/s]

Gaps (ex-reports):   6%|▌         | 409/7111 [01:35<23:37,  4.73it/s]

Gaps (ex-reports):   6%|▌         | 410/7111 [01:35<23:17,  4.80it/s]

Gaps (ex-reports):   6%|▌         | 411/7111 [01:36<22:54,  4.88it/s]

Gaps (ex-reports):   6%|▌         | 412/7111 [01:36<22:30,  4.96it/s]

Gaps (ex-reports):   6%|▌         | 413/7111 [01:36<22:07,  5.05it/s]

Gaps (ex-reports):   6%|▌         | 414/7111 [01:36<22:05,  5.05it/s]

Gaps (ex-reports):   6%|▌         | 415/7111 [01:36<22:16,  5.01it/s]

Gaps (ex-reports):   6%|▌         | 416/7111 [01:37<22:28,  4.97it/s]

Gaps (ex-reports):   6%|▌         | 417/7111 [01:37<22:48,  4.89it/s]

Gaps (ex-reports):   6%|▌         | 418/7111 [01:37<22:24,  4.98it/s]

Gaps (ex-reports):   6%|▌         | 419/7111 [01:37<22:16,  5.01it/s]

Gaps (ex-reports):   6%|▌         | 420/7111 [01:37<22:14,  5.01it/s]

Gaps (ex-reports):   6%|▌         | 421/7111 [01:38<22:00,  5.07it/s]

Gaps (ex-reports):   6%|▌         | 422/7111 [01:38<21:54,  5.09it/s]

Gaps (ex-reports):   6%|▌         | 423/7111 [01:38<21:48,  5.11it/s]

Gaps (ex-reports):   6%|▌         | 424/7111 [01:38<22:22,  4.98it/s]

Gaps (ex-reports):   6%|▌         | 425/7111 [01:38<22:41,  4.91it/s]

Gaps (ex-reports):   6%|▌         | 426/7111 [01:39<22:47,  4.89it/s]

Gaps (ex-reports):   6%|▌         | 427/7111 [01:39<22:36,  4.93it/s]

Gaps (ex-reports):   6%|▌         | 428/7111 [01:39<22:06,  5.04it/s]

Gaps (ex-reports):   6%|▌         | 429/7111 [01:39<22:07,  5.04it/s]

Gaps (ex-reports):   6%|▌         | 430/7111 [01:39<22:27,  4.96it/s]

Gaps (ex-reports):   6%|▌         | 431/7111 [01:40<22:31,  4.94it/s]

Gaps (ex-reports):   6%|▌         | 432/7111 [01:40<22:37,  4.92it/s]

Gaps (ex-reports):   6%|▌         | 433/7111 [01:40<22:21,  4.98it/s]

Gaps (ex-reports):   6%|▌         | 434/7111 [01:40<22:07,  5.03it/s]

Gaps (ex-reports):   6%|▌         | 435/7111 [01:40<22:41,  4.90it/s]

Gaps (ex-reports):   6%|▌         | 436/7111 [01:41<22:13,  5.00it/s]

Gaps (ex-reports):   6%|▌         | 437/7111 [01:41<22:21,  4.97it/s]

Gaps (ex-reports):   6%|▌         | 438/7111 [01:41<22:34,  4.93it/s]

Gaps (ex-reports):   6%|▌         | 439/7111 [01:41<22:46,  4.88it/s]

Gaps (ex-reports):   6%|▌         | 440/7111 [01:41<23:08,  4.81it/s]

Gaps (ex-reports):   6%|▌         | 441/7111 [01:42<22:37,  4.91it/s]

Gaps (ex-reports):   6%|▌         | 442/7111 [01:42<22:26,  4.95it/s]

Gaps (ex-reports):   6%|▌         | 443/7111 [01:42<22:30,  4.94it/s]

Gaps (ex-reports):   6%|▌         | 444/7111 [01:42<22:36,  4.92it/s]

Gaps (ex-reports):   6%|▋         | 445/7111 [01:42<22:13,  5.00it/s]

Gaps (ex-reports):   6%|▋         | 446/7111 [01:43<21:53,  5.08it/s]

Gaps (ex-reports):   6%|▋         | 447/7111 [01:43<22:18,  4.98it/s]

Gaps (ex-reports):   6%|▋         | 448/7111 [01:43<22:01,  5.04it/s]

Gaps (ex-reports):   6%|▋         | 449/7111 [01:43<21:54,  5.07it/s]

Gaps (ex-reports):   6%|▋         | 450/7111 [01:43<22:17,  4.98it/s]

Gaps (ex-reports):   6%|▋         | 451/7111 [01:44<22:24,  4.95it/s]

Gaps (ex-reports):   6%|▋         | 452/7111 [01:44<21:59,  5.05it/s]

Gaps (ex-reports):   6%|▋         | 453/7111 [01:44<22:25,  4.95it/s]

Gaps (ex-reports):   6%|▋         | 454/7111 [01:44<22:41,  4.89it/s]

Gaps (ex-reports):   6%|▋         | 455/7111 [01:44<22:19,  4.97it/s]

Gaps (ex-reports):   6%|▋         | 456/7111 [01:45<22:24,  4.95it/s]

Gaps (ex-reports):   6%|▋         | 457/7111 [01:45<22:12,  4.99it/s]

Gaps (ex-reports):   6%|▋         | 458/7111 [01:45<22:27,  4.94it/s]

Gaps (ex-reports):   6%|▋         | 459/7111 [01:45<22:01,  5.03it/s]

Gaps (ex-reports):   6%|▋         | 460/7111 [01:45<22:31,  4.92it/s]

Gaps (ex-reports):   6%|▋         | 461/7111 [01:46<22:07,  5.01it/s]

Gaps (ex-reports):   6%|▋         | 462/7111 [01:46<22:43,  4.88it/s]

Gaps (ex-reports):   7%|▋         | 463/7111 [01:46<22:20,  4.96it/s]

Gaps (ex-reports):   7%|▋         | 464/7111 [01:46<22:25,  4.94it/s]

Gaps (ex-reports):   7%|▋         | 465/7111 [01:46<22:12,  4.99it/s]

Gaps (ex-reports):   7%|▋         | 466/7111 [01:47<21:57,  5.05it/s]

Gaps (ex-reports):   7%|▋         | 467/7111 [01:47<21:44,  5.09it/s]

Gaps (ex-reports):   7%|▋         | 468/7111 [01:47<23:07,  4.79it/s]

Gaps (ex-reports):   7%|▋         | 469/7111 [01:47<25:05,  4.41it/s]

Gaps (ex-reports):   7%|▋         | 470/7111 [01:48<26:06,  4.24it/s]

Gaps (ex-reports):   7%|▋         | 471/7111 [01:48<28:01,  3.95it/s]

Gaps (ex-reports):   7%|▋         | 472/7111 [01:48<25:55,  4.27it/s]

Gaps (ex-reports):   7%|▋         | 473/7111 [01:48<24:38,  4.49it/s]

Gaps (ex-reports):   7%|▋         | 474/7111 [01:48<23:39,  4.68it/s]

Gaps (ex-reports):   7%|▋         | 475/7111 [01:49<23:51,  4.64it/s]

Gaps (ex-reports):   7%|▋         | 476/7111 [01:49<23:09,  4.77it/s]

Gaps (ex-reports):   7%|▋         | 477/7111 [01:49<22:36,  4.89it/s]

Gaps (ex-reports):   7%|▋         | 478/7111 [01:49<22:17,  4.96it/s]

Gaps (ex-reports):   7%|▋         | 479/7111 [01:49<22:37,  4.89it/s]

Gaps (ex-reports):   7%|▋         | 480/7111 [01:50<22:18,  4.95it/s]

Gaps (ex-reports):   7%|▋         | 481/7111 [01:50<22:20,  4.95it/s]

Gaps (ex-reports):   7%|▋         | 482/7111 [01:50<22:06,  5.00it/s]

Gaps (ex-reports):   7%|▋         | 483/7111 [01:50<21:58,  5.03it/s]

Gaps (ex-reports):   7%|▋         | 484/7111 [01:50<22:28,  4.92it/s]

Gaps (ex-reports):   7%|▋         | 485/7111 [01:51<22:02,  5.01it/s]

Gaps (ex-reports):   7%|▋         | 486/7111 [01:51<22:07,  4.99it/s]

Gaps (ex-reports):   7%|▋         | 487/7111 [01:51<21:57,  5.03it/s]

Gaps (ex-reports):   7%|▋         | 488/7111 [01:51<22:11,  4.97it/s]

Gaps (ex-reports):   7%|▋         | 489/7111 [01:51<22:10,  4.98it/s]

Gaps (ex-reports):   7%|▋         | 490/7111 [01:52<22:06,  4.99it/s]

Gaps (ex-reports):   7%|▋         | 491/7111 [01:52<24:58,  4.42it/s]

Gaps (ex-reports):   7%|▋         | 492/7111 [01:52<24:29,  4.51it/s]

Gaps (ex-reports):   7%|▋         | 493/7111 [01:52<24:02,  4.59it/s]

Gaps (ex-reports):   7%|▋         | 494/7111 [01:53<24:06,  4.58it/s]

Gaps (ex-reports):   7%|▋         | 495/7111 [01:53<23:24,  4.71it/s]

Gaps (ex-reports):   7%|▋         | 496/7111 [01:53<23:07,  4.77it/s]

Gaps (ex-reports):   7%|▋         | 497/7111 [01:53<23:12,  4.75it/s]

Gaps (ex-reports):   7%|▋         | 498/7111 [01:54<50:07,  2.20it/s]

Gaps (ex-reports):   7%|▋         | 499/7111 [01:54<41:24,  2.66it/s]

Gaps (ex-reports):   7%|▋         | 500/7111 [01:55<35:38,  3.09it/s]

Gaps (ex-reports):   7%|▋         | 501/7111 [01:55<31:59,  3.44it/s]

Gaps (ex-reports):   7%|▋         | 502/7111 [01:55<29:09,  3.78it/s]

Gaps (ex-reports):   7%|▋         | 503/7111 [01:55<26:56,  4.09it/s]

Gaps (ex-reports):   7%|▋         | 504/7111 [01:55<25:28,  4.32it/s]

Gaps (ex-reports):   7%|▋         | 505/7111 [01:56<24:39,  4.47it/s]

Gaps (ex-reports):   7%|▋         | 506/7111 [01:56<23:49,  4.62it/s]

Gaps (ex-reports):   7%|▋         | 507/7111 [01:56<23:21,  4.71it/s]

Gaps (ex-reports):   7%|▋         | 508/7111 [01:56<23:24,  4.70it/s]

Gaps (ex-reports):   7%|▋         | 509/7111 [01:56<23:02,  4.77it/s]

Gaps (ex-reports):   7%|▋         | 510/7111 [01:57<22:35,  4.87it/s]

Gaps (ex-reports):   7%|▋         | 511/7111 [01:57<22:05,  4.98it/s]

Gaps (ex-reports):   7%|▋         | 512/7111 [01:57<22:03,  4.99it/s]

Gaps (ex-reports):   7%|▋         | 513/7111 [01:57<22:03,  4.98it/s]

Gaps (ex-reports):   7%|▋         | 514/7111 [01:57<22:24,  4.91it/s]

Gaps (ex-reports):   7%|▋         | 515/7111 [01:58<22:23,  4.91it/s]

Gaps (ex-reports):   7%|▋         | 516/7111 [01:58<22:03,  4.98it/s]

Gaps (ex-reports):   7%|▋         | 517/7111 [01:58<22:00,  4.99it/s]

Gaps (ex-reports):   7%|▋         | 518/7111 [01:58<21:44,  5.06it/s]

Gaps (ex-reports):   7%|▋         | 519/7111 [01:58<21:45,  5.05it/s]

Gaps (ex-reports):   7%|▋         | 520/7111 [01:59<21:30,  5.11it/s]

Gaps (ex-reports):   7%|▋         | 521/7111 [01:59<21:34,  5.09it/s]

Gaps (ex-reports):   7%|▋         | 522/7111 [01:59<22:26,  4.89it/s]

Gaps (ex-reports):   7%|▋         | 523/7111 [01:59<22:31,  4.88it/s]

Gaps (ex-reports):   7%|▋         | 524/7111 [01:59<22:05,  4.97it/s]

Gaps (ex-reports):   7%|▋         | 525/7111 [02:00<21:56,  5.00it/s]

Gaps (ex-reports):   7%|▋         | 526/7111 [02:00<22:15,  4.93it/s]

Gaps (ex-reports):   7%|▋         | 527/7111 [02:00<22:14,  4.93it/s]

Gaps (ex-reports):   7%|▋         | 528/7111 [02:00<27:35,  3.98it/s]

Gaps (ex-reports):   7%|▋         | 529/7111 [02:01<25:34,  4.29it/s]

Gaps (ex-reports):   7%|▋         | 530/7111 [02:01<24:18,  4.51it/s]

Gaps (ex-reports):   7%|▋         | 531/7111 [02:01<23:16,  4.71it/s]

Gaps (ex-reports):   7%|▋         | 532/7111 [02:01<22:58,  4.77it/s]

Gaps (ex-reports):   7%|▋         | 533/7111 [02:01<22:39,  4.84it/s]

Gaps (ex-reports):   8%|▊         | 534/7111 [02:02<22:49,  4.80it/s]

Gaps (ex-reports):   8%|▊         | 535/7111 [02:02<23:00,  4.76it/s]

Gaps (ex-reports):   8%|▊         | 536/7111 [02:02<22:19,  4.91it/s]

Gaps (ex-reports):   8%|▊         | 537/7111 [02:02<22:24,  4.89it/s]

Gaps (ex-reports):   8%|▊         | 538/7111 [02:02<22:11,  4.94it/s]

Gaps (ex-reports):   8%|▊         | 539/7111 [02:03<22:26,  4.88it/s]

Gaps (ex-reports):   8%|▊         | 540/7111 [02:03<21:56,  4.99it/s]

Gaps (ex-reports):   8%|▊         | 541/7111 [02:04<46:19,  2.36it/s]

Gaps (ex-reports):   8%|▊         | 542/7111 [02:04<38:46,  2.82it/s]

Gaps (ex-reports):   8%|▊         | 543/7111 [02:04<33:28,  3.27it/s]

Gaps (ex-reports):   8%|▊         | 544/7111 [02:04<29:39,  3.69it/s]

Gaps (ex-reports):   8%|▊         | 545/7111 [02:04<27:32,  3.97it/s]

Gaps (ex-reports):   8%|▊         | 546/7111 [02:05<25:34,  4.28it/s]

Gaps (ex-reports):   8%|▊         | 547/7111 [02:05<24:21,  4.49it/s]

Gaps (ex-reports):   8%|▊         | 548/7111 [02:05<23:15,  4.70it/s]

Gaps (ex-reports):   8%|▊         | 549/7111 [02:05<22:43,  4.81it/s]

Gaps (ex-reports):   8%|▊         | 550/7111 [02:05<22:33,  4.85it/s]

Gaps (ex-reports):   8%|▊         | 551/7111 [02:06<22:13,  4.92it/s]

Gaps (ex-reports):   8%|▊         | 552/7111 [02:06<22:28,  4.86it/s]

Gaps (ex-reports):   8%|▊         | 553/7111 [02:06<22:51,  4.78it/s]

Gaps (ex-reports):   8%|▊         | 554/7111 [02:06<22:25,  4.87it/s]

Gaps (ex-reports):   8%|▊         | 555/7111 [02:06<22:19,  4.89it/s]

Gaps (ex-reports):   8%|▊         | 556/7111 [02:07<21:55,  4.98it/s]

Gaps (ex-reports):   8%|▊         | 557/7111 [02:07<24:24,  4.47it/s]

Gaps (ex-reports):   8%|▊         | 558/7111 [02:07<23:55,  4.56it/s]

Gaps (ex-reports):   8%|▊         | 559/7111 [02:07<23:43,  4.60it/s]

Gaps (ex-reports):   8%|▊         | 560/7111 [02:08<23:43,  4.60it/s]

Gaps (ex-reports):   8%|▊         | 561/7111 [02:08<23:30,  4.64it/s]

Gaps (ex-reports):   8%|▊         | 562/7111 [02:08<23:08,  4.72it/s]

Gaps (ex-reports):   8%|▊         | 563/7111 [02:08<23:12,  4.70it/s]

Gaps (ex-reports):   8%|▊         | 564/7111 [02:08<23:04,  4.73it/s]

Gaps (ex-reports):   8%|▊         | 565/7111 [02:09<22:58,  4.75it/s]

Gaps (ex-reports):   8%|▊         | 566/7111 [02:09<22:41,  4.81it/s]

Gaps (ex-reports):   8%|▊         | 567/7111 [02:09<22:15,  4.90it/s]

Gaps (ex-reports):   8%|▊         | 568/7111 [02:09<22:24,  4.87it/s]

Gaps (ex-reports):   8%|▊         | 569/7111 [02:10<24:28,  4.45it/s]

Gaps (ex-reports):   8%|▊         | 570/7111 [02:10<47:41,  2.29it/s]

Gaps (ex-reports):   8%|▊         | 571/7111 [02:11<40:53,  2.67it/s]

Gaps (ex-reports):   8%|▊         | 572/7111 [02:11<35:03,  3.11it/s]

Gaps (ex-reports):   8%|▊         | 573/7111 [02:11<31:15,  3.49it/s]

Gaps (ex-reports):   8%|▊         | 574/7111 [02:13<1:40:18,  1.09it/s]

Gaps (ex-reports):   8%|▊         | 575/7111 [02:14<1:16:51,  1.42it/s]

Gaps (ex-reports):   8%|▊         | 576/7111 [02:14<1:00:58,  1.79it/s]

Gaps (ex-reports):   8%|▊         | 577/7111 [02:14<49:08,  2.22it/s]

Gaps (ex-reports):   8%|▊         | 578/7111 [02:14<43:10,  2.52it/s]

Gaps (ex-reports):   8%|▊         | 579/7111 [02:15<37:13,  2.92it/s]

Gaps (ex-reports):   8%|▊         | 580/7111 [02:15<32:42,  3.33it/s]

Gaps (ex-reports):   8%|▊         | 581/7111 [02:15<29:55,  3.64it/s]

Gaps (ex-reports):   8%|▊         | 582/7111 [02:16<43:30,  2.50it/s]

Gaps (ex-reports):   8%|▊         | 583/7111 [02:16<36:58,  2.94it/s]

Gaps (ex-reports):   8%|▊         | 584/7111 [02:16<32:40,  3.33it/s]

Gaps (ex-reports):   8%|▊         | 585/7111 [02:16<29:49,  3.65it/s]

Gaps (ex-reports):   8%|▊         | 586/7111 [02:17<27:53,  3.90it/s]

Gaps (ex-reports):   8%|▊         | 587/7111 [02:18<1:05:45,  1.65it/s]

Gaps (ex-reports):   8%|▊         | 588/7111 [02:18<52:35,  2.07it/s]

Gaps (ex-reports):   8%|▊         | 589/7111 [02:18<43:19,  2.51it/s]

Gaps (ex-reports):   8%|▊         | 590/7111 [02:19<36:45,  2.96it/s]

Gaps (ex-reports):   8%|▊         | 591/7111 [02:19<32:37,  3.33it/s]

Gaps (ex-reports):   8%|▊         | 592/7111 [02:19<29:21,  3.70it/s]

Gaps (ex-reports):   8%|▊         | 593/7111 [02:20<46:18,  2.35it/s]

Gaps (ex-reports):   8%|▊         | 594/7111 [02:20<38:23,  2.83it/s]

Gaps (ex-reports):   8%|▊         | 595/7111 [02:20<34:01,  3.19it/s]

Gaps (ex-reports):   8%|▊         | 596/7111 [02:20<30:31,  3.56it/s]

Gaps (ex-reports):   8%|▊         | 597/7111 [02:21<27:54,  3.89it/s]

Gaps (ex-reports):   8%|▊         | 598/7111 [02:21<26:30,  4.10it/s]

Gaps (ex-reports):   8%|▊         | 599/7111 [02:21<25:27,  4.26it/s]

Gaps (ex-reports):   8%|▊         | 600/7111 [02:21<24:23,  4.45it/s]

Gaps (ex-reports):   8%|▊         | 601/7111 [02:21<23:20,  4.65it/s]

Gaps (ex-reports):   8%|▊         | 602/7111 [02:22<23:57,  4.53it/s]

Gaps (ex-reports):   8%|▊         | 603/7111 [02:22<22:52,  4.74it/s]

Gaps (ex-reports):   8%|▊         | 604/7111 [02:22<22:18,  4.86it/s]

Gaps (ex-reports):   9%|▊         | 605/7111 [02:22<22:08,  4.90it/s]

Gaps (ex-reports):   9%|▊         | 606/7111 [02:22<21:41,  5.00it/s]

Gaps (ex-reports):   9%|▊         | 607/7111 [02:23<21:53,  4.95it/s]

Gaps (ex-reports):   9%|▊         | 608/7111 [02:23<21:31,  5.04it/s]

Gaps (ex-reports):   9%|▊         | 609/7111 [02:23<22:19,  4.85it/s]

Gaps (ex-reports):   9%|▊         | 610/7111 [02:23<22:27,  4.82it/s]

Gaps (ex-reports):   9%|▊         | 611/7111 [02:23<22:36,  4.79it/s]

Gaps (ex-reports):   9%|▊         | 612/7111 [02:24<39:00,  2.78it/s]

Gaps (ex-reports):   9%|▊         | 613/7111 [02:24<33:52,  3.20it/s]

Gaps (ex-reports):   9%|▊         | 614/7111 [02:25<30:48,  3.51it/s]

Gaps (ex-reports):   9%|▊         | 615/7111 [02:25<28:22,  3.82it/s]

Gaps (ex-reports):   9%|▊         | 616/7111 [02:25<26:24,  4.10it/s]

Gaps (ex-reports):   9%|▊         | 617/7111 [02:25<25:11,  4.30it/s]

Gaps (ex-reports):   9%|▊         | 618/7111 [02:25<24:27,  4.42it/s]

Gaps (ex-reports):   9%|▊         | 619/7111 [02:26<23:15,  4.65it/s]

Gaps (ex-reports):   9%|▊         | 620/7111 [02:26<22:57,  4.71it/s]

Gaps (ex-reports):   9%|▊         | 621/7111 [02:26<22:18,  4.85it/s]

Gaps (ex-reports):   9%|▊         | 622/7111 [02:26<21:49,  4.96it/s]

Gaps (ex-reports):   9%|▉         | 623/7111 [02:26<22:09,  4.88it/s]

Gaps (ex-reports):   9%|▉         | 624/7111 [02:27<22:01,  4.91it/s]

Gaps (ex-reports):   9%|▉         | 625/7111 [02:27<22:10,  4.88it/s]

Gaps (ex-reports):   9%|▉         | 626/7111 [02:27<22:11,  4.87it/s]

Gaps (ex-reports):   9%|▉         | 627/7111 [02:27<21:53,  4.94it/s]

Gaps (ex-reports):   9%|▉         | 628/7111 [02:27<21:40,  4.99it/s]

Gaps (ex-reports):   9%|▉         | 629/7111 [02:28<22:33,  4.79it/s]

Gaps (ex-reports):   9%|▉         | 630/7111 [02:28<22:14,  4.85it/s]

Gaps (ex-reports):   9%|▉         | 631/7111 [02:28<21:54,  4.93it/s]

Gaps (ex-reports):   9%|▉         | 632/7111 [02:28<22:04,  4.89it/s]

Gaps (ex-reports):   9%|▉         | 633/7111 [02:28<21:31,  5.02it/s]

Gaps (ex-reports):   9%|▉         | 634/7111 [02:29<21:36,  5.00it/s]

Gaps (ex-reports):   9%|▉         | 635/7111 [02:29<21:38,  4.99it/s]

Gaps (ex-reports):   9%|▉         | 636/7111 [02:29<21:17,  5.07it/s]

Gaps (ex-reports):   9%|▉         | 637/7111 [02:29<21:21,  5.05it/s]

Gaps (ex-reports):   9%|▉         | 638/7111 [02:29<21:38,  4.98it/s]

Gaps (ex-reports):   9%|▉         | 639/7111 [02:30<21:51,  4.94it/s]

Gaps (ex-reports):   9%|▉         | 640/7111 [02:30<21:51,  4.93it/s]

Gaps (ex-reports):   9%|▉         | 641/7111 [02:30<21:40,  4.98it/s]

Gaps (ex-reports):   9%|▉         | 642/7111 [02:30<21:43,  4.96it/s]

Gaps (ex-reports):   9%|▉         | 643/7111 [02:30<21:53,  4.92it/s]

Gaps (ex-reports):   9%|▉         | 644/7111 [02:31<21:36,  4.99it/s]

Gaps (ex-reports):   9%|▉         | 645/7111 [02:31<21:36,  4.99it/s]

Gaps (ex-reports):   9%|▉         | 646/7111 [02:31<22:04,  4.88it/s]

Gaps (ex-reports):   9%|▉         | 647/7111 [02:31<21:40,  4.97it/s]

Gaps (ex-reports):   9%|▉         | 648/7111 [02:31<21:53,  4.92it/s]

Gaps (ex-reports):   9%|▉         | 649/7111 [02:32<21:57,  4.90it/s]

Gaps (ex-reports):   9%|▉         | 650/7111 [02:32<21:49,  4.94it/s]

Gaps (ex-reports):   9%|▉         | 651/7111 [02:32<21:35,  4.98it/s]

Gaps (ex-reports):   9%|▉         | 652/7111 [02:33<47:17,  2.28it/s]

Gaps (ex-reports):   9%|▉         | 653/7111 [02:33<39:09,  2.75it/s]

Gaps (ex-reports):   9%|▉         | 654/7111 [02:33<33:47,  3.18it/s]

Gaps (ex-reports):   9%|▉         | 655/7111 [02:34<30:18,  3.55it/s]

Gaps (ex-reports):   9%|▉         | 656/7111 [02:34<27:43,  3.88it/s]

Gaps (ex-reports):   9%|▉         | 657/7111 [02:34<25:51,  4.16it/s]

Gaps (ex-reports):   9%|▉         | 658/7111 [02:36<1:35:12,  1.13it/s]

Gaps (ex-reports):   9%|▉         | 659/7111 [02:37<1:13:36,  1.46it/s]

Gaps (ex-reports):   9%|▉         | 660/7111 [02:37<57:39,  1.86it/s]

Gaps (ex-reports):   9%|▉         | 661/7111 [02:37<46:42,  2.30it/s]

Gaps (ex-reports):   9%|▉         | 662/7111 [02:37<39:24,  2.73it/s]

Gaps (ex-reports):   9%|▉         | 663/7111 [02:37<34:45,  3.09it/s]

Gaps (ex-reports):   9%|▉         | 664/7111 [02:38<31:00,  3.47it/s]

Gaps (ex-reports):   9%|▉         | 665/7111 [02:38<28:18,  3.80it/s]

Gaps (ex-reports):   9%|▉         | 666/7111 [02:38<26:13,  4.10it/s]

Gaps (ex-reports):   9%|▉         | 667/7111 [02:38<25:00,  4.29it/s]

Gaps (ex-reports):   9%|▉         | 668/7111 [02:38<24:18,  4.42it/s]

Gaps (ex-reports):   9%|▉         | 669/7111 [02:39<23:11,  4.63it/s]

Gaps (ex-reports):   9%|▉         | 670/7111 [02:39<36:51,  2.91it/s]

Gaps (ex-reports):   9%|▉         | 671/7111 [02:40<32:34,  3.30it/s]

Gaps (ex-reports):   9%|▉         | 672/7111 [02:40<28:58,  3.70it/s]

Gaps (ex-reports):   9%|▉         | 673/7111 [02:40<26:47,  4.00it/s]

Gaps (ex-reports):   9%|▉         | 674/7111 [02:40<25:28,  4.21it/s]

Gaps (ex-reports):   9%|▉         | 675/7111 [02:40<24:19,  4.41it/s]

Gaps (ex-reports):  10%|▉         | 676/7111 [02:41<23:41,  4.53it/s]

Gaps (ex-reports):  10%|▉         | 677/7111 [02:41<23:06,  4.64it/s]

Gaps (ex-reports):  10%|▉         | 678/7111 [02:41<22:48,  4.70it/s]

Gaps (ex-reports):  10%|▉         | 679/7111 [02:41<22:18,  4.81it/s]

Gaps (ex-reports):  10%|▉         | 680/7111 [02:41<22:20,  4.80it/s]

Gaps (ex-reports):  10%|▉         | 681/7111 [02:42<22:11,  4.83it/s]

Gaps (ex-reports):  10%|▉         | 682/7111 [02:42<21:39,  4.95it/s]

Gaps (ex-reports):  10%|▉         | 683/7111 [02:42<21:24,  5.01it/s]

Gaps (ex-reports):  10%|▉         | 684/7111 [02:42<21:34,  4.97it/s]

Gaps (ex-reports):  10%|▉         | 685/7111 [02:42<21:52,  4.90it/s]

Gaps (ex-reports):  10%|▉         | 686/7111 [02:43<21:51,  4.90it/s]

Gaps (ex-reports):  10%|▉         | 687/7111 [02:43<21:35,  4.96it/s]

Gaps (ex-reports):  10%|▉         | 688/7111 [02:43<21:44,  4.93it/s]

Gaps (ex-reports):  10%|▉         | 689/7111 [02:43<21:49,  4.90it/s]

Gaps (ex-reports):  10%|▉         | 690/7111 [02:43<21:37,  4.95it/s]

Gaps (ex-reports):  10%|▉         | 691/7111 [02:44<21:38,  4.95it/s]

Gaps (ex-reports):  10%|▉         | 692/7111 [02:44<21:13,  5.04it/s]

Gaps (ex-reports):  10%|▉         | 693/7111 [02:44<21:06,  5.07it/s]

Gaps (ex-reports):  10%|▉         | 694/7111 [02:45<40:50,  2.62it/s]

Gaps (ex-reports):  10%|▉         | 695/7111 [02:45<35:01,  3.05it/s]

Gaps (ex-reports):  10%|▉         | 696/7111 [02:45<31:07,  3.43it/s]

Gaps (ex-reports):  10%|▉         | 697/7111 [02:45<28:24,  3.76it/s]

Gaps (ex-reports):  10%|▉         | 698/7111 [02:46<26:24,  4.05it/s]

Gaps (ex-reports):  10%|▉         | 699/7111 [02:46<25:13,  4.24it/s]

Gaps (ex-reports):  10%|▉         | 700/7111 [02:46<24:14,  4.41it/s]

Gaps (ex-reports):  10%|▉         | 701/7111 [02:46<23:12,  4.60it/s]

Gaps (ex-reports):  10%|▉         | 702/7111 [02:46<22:21,  4.78it/s]

Gaps (ex-reports):  10%|▉         | 703/7111 [02:47<21:42,  4.92it/s]

Gaps (ex-reports):  10%|▉         | 704/7111 [02:47<23:50,  4.48it/s]

Gaps (ex-reports):  10%|▉         | 705/7111 [02:47<22:56,  4.65it/s]

Gaps (ex-reports):  10%|▉         | 706/7111 [02:47<22:13,  4.80it/s]

Gaps (ex-reports):  10%|▉         | 707/7111 [02:47<21:48,  4.89it/s]

Gaps (ex-reports):  10%|▉         | 708/7111 [02:48<21:54,  4.87it/s]

Gaps (ex-reports):  10%|▉         | 709/7111 [02:48<21:52,  4.88it/s]

Gaps (ex-reports):  10%|▉         | 710/7111 [02:48<21:57,  4.86it/s]

Gaps (ex-reports):  10%|▉         | 711/7111 [02:48<21:35,  4.94it/s]

Gaps (ex-reports):  10%|█         | 712/7111 [02:48<21:56,  4.86it/s]

Gaps (ex-reports):  10%|█         | 713/7111 [02:49<21:58,  4.85it/s]

Gaps (ex-reports):  10%|█         | 714/7111 [02:49<21:58,  4.85it/s]

Gaps (ex-reports):  10%|█         | 715/7111 [02:49<21:46,  4.90it/s]

Gaps (ex-reports):  10%|█         | 716/7111 [02:49<21:36,  4.93it/s]

Gaps (ex-reports):  10%|█         | 717/7111 [02:49<21:38,  4.92it/s]

Gaps (ex-reports):  10%|█         | 718/7111 [02:50<21:13,  5.02it/s]

Gaps (ex-reports):  10%|█         | 719/7111 [02:50<22:01,  4.84it/s]

Gaps (ex-reports):  10%|█         | 720/7111 [02:51<40:12,  2.65it/s]

Gaps (ex-reports):  10%|█         | 721/7111 [02:51<33:57,  3.14it/s]

Gaps (ex-reports):  10%|█         | 722/7111 [02:51<30:32,  3.49it/s]

Gaps (ex-reports):  10%|█         | 723/7111 [02:51<27:29,  3.87it/s]

Gaps (ex-reports):  10%|█         | 724/7111 [02:51<25:55,  4.11it/s]

Gaps (ex-reports):  10%|█         | 725/7111 [02:52<24:36,  4.32it/s]

Gaps (ex-reports):  10%|█         | 726/7111 [02:52<23:52,  4.46it/s]

Gaps (ex-reports):  10%|█         | 727/7111 [02:52<23:05,  4.61it/s]

Gaps (ex-reports):  10%|█         | 728/7111 [02:52<22:33,  4.72it/s]

Gaps (ex-reports):  10%|█         | 729/7111 [02:52<22:42,  4.68it/s]

Gaps (ex-reports):  10%|█         | 730/7111 [02:53<22:24,  4.75it/s]

Gaps (ex-reports):  10%|█         | 731/7111 [02:53<27:35,  3.85it/s]

Gaps (ex-reports):  10%|█         | 732/7111 [02:53<25:29,  4.17it/s]

Gaps (ex-reports):  10%|█         | 733/7111 [02:53<24:28,  4.34it/s]

Gaps (ex-reports):  10%|█         | 734/7111 [02:54<23:32,  4.51it/s]

Gaps (ex-reports):  10%|█         | 735/7111 [02:54<23:39,  4.49it/s]

Gaps (ex-reports):  10%|█         | 736/7111 [02:54<23:25,  4.53it/s]

Gaps (ex-reports):  10%|█         | 737/7111 [02:54<22:42,  4.68it/s]

Gaps (ex-reports):  10%|█         | 738/7111 [02:55<22:04,  4.81it/s]

Gaps (ex-reports):  10%|█         | 739/7111 [02:55<21:41,  4.90it/s]

Gaps (ex-reports):  10%|█         | 740/7111 [02:55<21:00,  5.05it/s]

Gaps (ex-reports):  10%|█         | 741/7111 [02:55<21:09,  5.02it/s]

Gaps (ex-reports):  10%|█         | 742/7111 [02:55<21:13,  5.00it/s]

Gaps (ex-reports):  10%|█         | 743/7111 [02:56<21:35,  4.92it/s]

Gaps (ex-reports):  10%|█         | 744/7111 [02:56<22:06,  4.80it/s]

Gaps (ex-reports):  10%|█         | 745/7111 [02:56<32:57,  3.22it/s]

Gaps (ex-reports):  10%|█         | 746/7111 [02:56<29:26,  3.60it/s]

Gaps (ex-reports):  11%|█         | 747/7111 [02:57<26:47,  3.96it/s]

Gaps (ex-reports):  11%|█         | 748/7111 [02:57<24:54,  4.26it/s]

Gaps (ex-reports):  11%|█         | 749/7111 [02:57<23:35,  4.50it/s]

Gaps (ex-reports):  11%|█         | 750/7111 [02:57<22:51,  4.64it/s]

Gaps (ex-reports):  11%|█         | 751/7111 [02:57<22:13,  4.77it/s]

Gaps (ex-reports):  11%|█         | 752/7111 [02:59<1:11:07,  1.49it/s]

Gaps (ex-reports):  11%|█         | 753/7111 [02:59<55:55,  1.89it/s]

Gaps (ex-reports):  11%|█         | 754/7111 [03:00<45:52,  2.31it/s]

Gaps (ex-reports):  11%|█         | 755/7111 [03:00<38:11,  2.77it/s]

Gaps (ex-reports):  11%|█         | 756/7111 [03:00<33:04,  3.20it/s]

Gaps (ex-reports):  11%|█         | 757/7111 [03:00<29:06,  3.64it/s]

Gaps (ex-reports):  11%|█         | 758/7111 [03:00<27:07,  3.90it/s]

Gaps (ex-reports):  11%|█         | 759/7111 [03:01<25:01,  4.23it/s]

Gaps (ex-reports):  11%|█         | 760/7111 [03:01<24:21,  4.35it/s]

Gaps (ex-reports):  11%|█         | 761/7111 [03:01<23:38,  4.48it/s]

Gaps (ex-reports):  11%|█         | 762/7111 [03:01<22:54,  4.62it/s]

Gaps (ex-reports):  11%|█         | 763/7111 [03:01<22:15,  4.75it/s]

Gaps (ex-reports):  11%|█         | 764/7111 [03:02<22:31,  4.70it/s]

Gaps (ex-reports):  11%|█         | 765/7111 [03:02<21:53,  4.83it/s]

Gaps (ex-reports):  11%|█         | 766/7111 [03:02<21:38,  4.89it/s]

Gaps (ex-reports):  11%|█         | 767/7111 [03:02<21:47,  4.85it/s]

Gaps (ex-reports):  11%|█         | 768/7111 [03:02<21:39,  4.88it/s]

Gaps (ex-reports):  11%|█         | 769/7111 [03:03<21:41,  4.87it/s]

Gaps (ex-reports):  11%|█         | 770/7111 [03:03<21:37,  4.89it/s]

Gaps (ex-reports):  11%|█         | 771/7111 [03:03<21:53,  4.83it/s]

Gaps (ex-reports):  11%|█         | 772/7111 [03:03<21:25,  4.93it/s]

Gaps (ex-reports):  11%|█         | 773/7111 [03:03<21:14,  4.97it/s]

Gaps (ex-reports):  11%|█         | 774/7111 [03:04<21:34,  4.90it/s]

Gaps (ex-reports):  11%|█         | 775/7111 [03:04<21:55,  4.82it/s]

Gaps (ex-reports):  11%|█         | 776/7111 [03:04<22:20,  4.73it/s]

Gaps (ex-reports):  11%|█         | 777/7111 [03:04<21:59,  4.80it/s]

Gaps (ex-reports):  11%|█         | 778/7111 [03:04<21:54,  4.82it/s]

Gaps (ex-reports):  11%|█         | 779/7111 [03:05<21:42,  4.86it/s]

Gaps (ex-reports):  11%|█         | 780/7111 [03:05<21:36,  4.88it/s]

Gaps (ex-reports):  11%|█         | 781/7111 [03:05<21:42,  4.86it/s]

Gaps (ex-reports):  11%|█         | 782/7111 [03:06<29:40,  3.55it/s]

Gaps (ex-reports):  11%|█         | 783/7111 [03:06<28:55,  3.65it/s]

Gaps (ex-reports):  11%|█         | 784/7111 [03:06<27:11,  3.88it/s]

Gaps (ex-reports):  11%|█         | 785/7111 [03:06<25:16,  4.17it/s]

Gaps (ex-reports):  11%|█         | 786/7111 [03:07<30:50,  3.42it/s]

Gaps (ex-reports):  11%|█         | 787/7111 [03:07<28:00,  3.76it/s]

Gaps (ex-reports):  11%|█         | 788/7111 [03:07<26:16,  4.01it/s]

Gaps (ex-reports):  11%|█         | 789/7111 [03:07<24:41,  4.27it/s]

Gaps (ex-reports):  11%|█         | 790/7111 [03:07<23:28,  4.49it/s]

Gaps (ex-reports):  11%|█         | 791/7111 [03:08<22:45,  4.63it/s]

Gaps (ex-reports):  11%|█         | 792/7111 [03:08<21:51,  4.82it/s]

Gaps (ex-reports):  11%|█         | 793/7111 [03:08<21:33,  4.88it/s]

Gaps (ex-reports):  11%|█         | 794/7111 [03:08<21:28,  4.90it/s]

Gaps (ex-reports):  11%|█         | 795/7111 [03:08<21:13,  4.96it/s]

Gaps (ex-reports):  11%|█         | 796/7111 [03:09<21:11,  4.97it/s]

Gaps (ex-reports):  11%|█         | 797/7111 [03:09<21:17,  4.94it/s]

Gaps (ex-reports):  11%|█         | 798/7111 [03:09<21:31,  4.89it/s]

Gaps (ex-reports):  11%|█         | 799/7111 [03:09<21:26,  4.91it/s]

Gaps (ex-reports):  11%|█▏        | 800/7111 [03:09<21:26,  4.91it/s]

Gaps (ex-reports):  11%|█▏        | 801/7111 [03:10<21:39,  4.85it/s]

Gaps (ex-reports):  11%|█▏        | 802/7111 [03:10<21:09,  4.97it/s]

Gaps (ex-reports):  11%|█▏        | 803/7111 [03:10<20:55,  5.02it/s]

Gaps (ex-reports):  11%|█▏        | 804/7111 [03:10<20:47,  5.06it/s]

Gaps (ex-reports):  11%|█▏        | 805/7111 [03:10<21:09,  4.97it/s]

Gaps (ex-reports):  11%|█▏        | 806/7111 [03:11<21:20,  4.92it/s]

Gaps (ex-reports):  11%|█▏        | 807/7111 [03:11<21:14,  4.95it/s]

Gaps (ex-reports):  11%|█▏        | 808/7111 [03:11<21:09,  4.96it/s]

Gaps (ex-reports):  11%|█▏        | 809/7111 [03:11<21:35,  4.87it/s]

Gaps (ex-reports):  11%|█▏        | 810/7111 [03:12<21:49,  4.81it/s]

Gaps (ex-reports):  11%|█▏        | 811/7111 [03:12<22:15,  4.72it/s]

Gaps (ex-reports):  11%|█▏        | 812/7111 [03:12<21:48,  4.81it/s]

Gaps (ex-reports):  11%|█▏        | 813/7111 [03:12<21:25,  4.90it/s]

Gaps (ex-reports):  11%|█▏        | 814/7111 [03:12<21:19,  4.92it/s]

Gaps (ex-reports):  11%|█▏        | 815/7111 [03:13<21:25,  4.90it/s]

Gaps (ex-reports):  11%|█▏        | 816/7111 [03:13<21:10,  4.96it/s]

Gaps (ex-reports):  11%|█▏        | 817/7111 [03:13<21:22,  4.91it/s]

Gaps (ex-reports):  12%|█▏        | 818/7111 [03:13<21:27,  4.89it/s]

Gaps (ex-reports):  12%|█▏        | 819/7111 [03:13<21:26,  4.89it/s]

Gaps (ex-reports):  12%|█▏        | 820/7111 [03:14<21:42,  4.83it/s]

Gaps (ex-reports):  12%|█▏        | 821/7111 [03:14<21:32,  4.87it/s]

Gaps (ex-reports):  12%|█▏        | 822/7111 [03:14<21:56,  4.78it/s]

Gaps (ex-reports):  12%|█▏        | 823/7111 [03:14<22:13,  4.71it/s]

Gaps (ex-reports):  12%|█▏        | 824/7111 [03:14<22:12,  4.72it/s]

Gaps (ex-reports):  12%|█▏        | 825/7111 [03:15<22:39,  4.62it/s]

Gaps (ex-reports):  12%|█▏        | 826/7111 [03:15<21:54,  4.78it/s]

Gaps (ex-reports):  12%|█▏        | 827/7111 [03:15<21:37,  4.84it/s]

Gaps (ex-reports):  12%|█▏        | 828/7111 [03:15<21:51,  4.79it/s]

Gaps (ex-reports):  12%|█▏        | 829/7111 [03:15<21:36,  4.85it/s]

Gaps (ex-reports):  12%|█▏        | 830/7111 [03:16<21:37,  4.84it/s]

Gaps (ex-reports):  12%|█▏        | 831/7111 [03:16<21:23,  4.89it/s]

Gaps (ex-reports):  12%|█▏        | 832/7111 [03:16<21:32,  4.86it/s]

Gaps (ex-reports):  12%|█▏        | 833/7111 [03:16<21:38,  4.83it/s]

Gaps (ex-reports):  12%|█▏        | 834/7111 [03:16<21:31,  4.86it/s]

Gaps (ex-reports):  12%|█▏        | 835/7111 [03:17<21:13,  4.93it/s]

Gaps (ex-reports):  12%|█▏        | 836/7111 [03:17<21:21,  4.90it/s]

Gaps (ex-reports):  12%|█▏        | 837/7111 [03:17<21:53,  4.78it/s]

Gaps (ex-reports):  12%|█▏        | 838/7111 [03:17<21:14,  4.92it/s]

Gaps (ex-reports):  12%|█▏        | 839/7111 [03:17<21:34,  4.84it/s]

Gaps (ex-reports):  12%|█▏        | 840/7111 [03:18<21:24,  4.88it/s]

Gaps (ex-reports):  12%|█▏        | 841/7111 [03:18<21:07,  4.95it/s]

Gaps (ex-reports):  12%|█▏        | 842/7111 [03:18<21:14,  4.92it/s]

Gaps (ex-reports):  12%|█▏        | 843/7111 [03:18<21:23,  4.88it/s]

Gaps (ex-reports):  12%|█▏        | 844/7111 [03:19<22:02,  4.74it/s]

Gaps (ex-reports):  12%|█▏        | 845/7111 [03:19<21:53,  4.77it/s]

Gaps (ex-reports):  12%|█▏        | 846/7111 [03:19<21:45,  4.80it/s]

Gaps (ex-reports):  12%|█▏        | 847/7111 [03:19<21:18,  4.90it/s]

Gaps (ex-reports):  12%|█▏        | 848/7111 [03:19<21:21,  4.89it/s]

Gaps (ex-reports):  12%|█▏        | 849/7111 [03:20<21:16,  4.90it/s]

Gaps (ex-reports):  12%|█▏        | 850/7111 [03:20<21:29,  4.86it/s]

Gaps (ex-reports):  12%|█▏        | 851/7111 [03:21<45:27,  2.30it/s]

Gaps (ex-reports):  12%|█▏        | 852/7111 [03:21<38:02,  2.74it/s]

Gaps (ex-reports):  12%|█▏        | 853/7111 [03:21<33:09,  3.15it/s]

Gaps (ex-reports):  12%|█▏        | 854/7111 [03:21<29:34,  3.53it/s]

Gaps (ex-reports):  12%|█▏        | 855/7111 [03:22<26:54,  3.88it/s]

Gaps (ex-reports):  12%|█▏        | 856/7111 [03:22<24:49,  4.20it/s]

Gaps (ex-reports):  12%|█▏        | 857/7111 [03:22<24:15,  4.30it/s]

Gaps (ex-reports):  12%|█▏        | 858/7111 [03:22<23:16,  4.48it/s]

Gaps (ex-reports):  12%|█▏        | 859/7111 [03:23<28:38,  3.64it/s]

Gaps (ex-reports):  12%|█▏        | 860/7111 [03:23<26:31,  3.93it/s]

Gaps (ex-reports):  12%|█▏        | 861/7111 [03:23<24:57,  4.17it/s]

Gaps (ex-reports):  12%|█▏        | 862/7111 [03:23<24:21,  4.28it/s]

Gaps (ex-reports):  12%|█▏        | 863/7111 [03:23<23:05,  4.51it/s]

Gaps (ex-reports):  12%|█▏        | 864/7111 [03:24<22:37,  4.60it/s]

Gaps (ex-reports):  12%|█▏        | 865/7111 [03:24<22:05,  4.71it/s]

Gaps (ex-reports):  12%|█▏        | 866/7111 [03:24<21:44,  4.79it/s]

Gaps (ex-reports):  12%|█▏        | 867/7111 [03:24<21:16,  4.89it/s]

Gaps (ex-reports):  12%|█▏        | 868/7111 [03:24<21:27,  4.85it/s]

Gaps (ex-reports):  12%|█▏        | 869/7111 [03:25<31:19,  3.32it/s]

Gaps (ex-reports):  12%|█▏        | 870/7111 [03:25<28:45,  3.62it/s]

Gaps (ex-reports):  12%|█▏        | 871/7111 [03:25<26:15,  3.96it/s]

Gaps (ex-reports):  12%|█▏        | 872/7111 [03:26<24:54,  4.17it/s]

Gaps (ex-reports):  12%|█▏        | 873/7111 [03:26<23:52,  4.35it/s]

Gaps (ex-reports):  12%|█▏        | 874/7111 [03:26<23:21,  4.45it/s]

Gaps (ex-reports):  12%|█▏        | 875/7111 [03:26<22:54,  4.54it/s]

Gaps (ex-reports):  12%|█▏        | 876/7111 [03:27<39:19,  2.64it/s]

Gaps (ex-reports):  12%|█▏        | 877/7111 [03:27<34:59,  2.97it/s]

Gaps (ex-reports):  12%|█▏        | 878/7111 [03:27<30:55,  3.36it/s]

Gaps (ex-reports):  12%|█▏        | 879/7111 [03:28<27:57,  3.72it/s]

Gaps (ex-reports):  12%|█▏        | 880/7111 [03:28<26:21,  3.94it/s]

Gaps (ex-reports):  12%|█▏        | 881/7111 [03:28<25:05,  4.14it/s]

Gaps (ex-reports):  12%|█▏        | 882/7111 [03:28<23:36,  4.40it/s]

Gaps (ex-reports):  12%|█▏        | 883/7111 [03:28<25:02,  4.14it/s]

Gaps (ex-reports):  12%|█▏        | 884/7111 [03:29<24:00,  4.32it/s]

Gaps (ex-reports):  12%|█▏        | 885/7111 [03:29<25:36,  4.05it/s]

Gaps (ex-reports):  12%|█▏        | 886/7111 [03:29<24:10,  4.29it/s]

Gaps (ex-reports):  12%|█▏        | 887/7111 [03:29<23:14,  4.46it/s]

Gaps (ex-reports):  12%|█▏        | 888/7111 [03:30<23:10,  4.48it/s]

Gaps (ex-reports):  13%|█▎        | 889/7111 [03:30<22:15,  4.66it/s]

Gaps (ex-reports):  13%|█▎        | 890/7111 [03:30<22:03,  4.70it/s]

Gaps (ex-reports):  13%|█▎        | 891/7111 [03:30<21:29,  4.82it/s]

Gaps (ex-reports):  13%|█▎        | 892/7111 [03:30<20:57,  4.94it/s]

Gaps (ex-reports):  13%|█▎        | 893/7111 [03:31<20:36,  5.03it/s]

Gaps (ex-reports):  13%|█▎        | 894/7111 [03:31<20:45,  4.99it/s]

Gaps (ex-reports):  13%|█▎        | 895/7111 [03:31<20:57,  4.94it/s]

Gaps (ex-reports):  13%|█▎        | 896/7111 [03:31<21:09,  4.90it/s]

Gaps (ex-reports):  13%|█▎        | 897/7111 [03:31<21:09,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 898/7111 [03:32<21:05,  4.91it/s]

Gaps (ex-reports):  13%|█▎        | 899/7111 [03:32<21:09,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 900/7111 [03:32<21:27,  4.82it/s]

Gaps (ex-reports):  13%|█▎        | 901/7111 [03:32<21:30,  4.81it/s]

Gaps (ex-reports):  13%|█▎        | 902/7111 [03:32<21:00,  4.93it/s]

Gaps (ex-reports):  13%|█▎        | 903/7111 [03:33<21:07,  4.90it/s]

Gaps (ex-reports):  13%|█▎        | 904/7111 [03:33<21:09,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 905/7111 [03:33<21:03,  4.91it/s]

Gaps (ex-reports):  13%|█▎        | 906/7111 [03:33<20:59,  4.92it/s]

Gaps (ex-reports):  13%|█▎        | 907/7111 [03:33<21:08,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 908/7111 [03:34<21:58,  4.70it/s]

Gaps (ex-reports):  13%|█▎        | 909/7111 [03:34<21:59,  4.70it/s]

Gaps (ex-reports):  13%|█▎        | 910/7111 [03:34<21:18,  4.85it/s]

Gaps (ex-reports):  13%|█▎        | 911/7111 [03:34<21:01,  4.91it/s]

Gaps (ex-reports):  13%|█▎        | 912/7111 [03:34<20:39,  5.00it/s]

Gaps (ex-reports):  13%|█▎        | 913/7111 [03:35<20:50,  4.96it/s]

Gaps (ex-reports):  13%|█▎        | 914/7111 [03:35<20:44,  4.98it/s]

Gaps (ex-reports):  13%|█▎        | 915/7111 [03:35<21:05,  4.90it/s]

Gaps (ex-reports):  13%|█▎        | 916/7111 [03:35<20:44,  4.98it/s]

Gaps (ex-reports):  13%|█▎        | 917/7111 [03:35<20:37,  5.01it/s]

Gaps (ex-reports):  13%|█▎        | 918/7111 [03:36<20:45,  4.97it/s]

Gaps (ex-reports):  13%|█▎        | 919/7111 [03:36<20:36,  5.01it/s]

Gaps (ex-reports):  13%|█▎        | 920/7111 [03:36<20:45,  4.97it/s]

Gaps (ex-reports):  13%|█▎        | 921/7111 [03:36<20:29,  5.04it/s]

Gaps (ex-reports):  13%|█▎        | 922/7111 [03:36<20:59,  4.91it/s]

Gaps (ex-reports):  13%|█▎        | 923/7111 [03:37<21:25,  4.81it/s]

Gaps (ex-reports):  13%|█▎        | 924/7111 [03:37<20:55,  4.93it/s]

Gaps (ex-reports):  13%|█▎        | 925/7111 [03:37<21:04,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 926/7111 [03:37<21:21,  4.83it/s]

Gaps (ex-reports):  13%|█▎        | 927/7111 [03:38<21:20,  4.83it/s]

Gaps (ex-reports):  13%|█▎        | 928/7111 [03:38<21:25,  4.81it/s]

Gaps (ex-reports):  13%|█▎        | 929/7111 [03:38<21:14,  4.85it/s]

Gaps (ex-reports):  13%|█▎        | 930/7111 [03:38<20:45,  4.96it/s]

Gaps (ex-reports):  13%|█▎        | 931/7111 [03:38<21:15,  4.85it/s]

Gaps (ex-reports):  13%|█▎        | 932/7111 [03:39<20:57,  4.91it/s]

Gaps (ex-reports):  13%|█▎        | 933/7111 [03:39<20:51,  4.94it/s]

Gaps (ex-reports):  13%|█▎        | 934/7111 [03:39<20:54,  4.92it/s]

Gaps (ex-reports):  13%|█▎        | 935/7111 [03:39<21:24,  4.81it/s]

Gaps (ex-reports):  13%|█▎        | 936/7111 [03:39<21:09,  4.87it/s]

Gaps (ex-reports):  13%|█▎        | 937/7111 [03:40<21:00,  4.90it/s]

Gaps (ex-reports):  13%|█▎        | 938/7111 [03:40<21:02,  4.89it/s]

Gaps (ex-reports):  13%|█▎        | 939/7111 [03:40<20:48,  4.95it/s]

Gaps (ex-reports):  13%|█▎        | 940/7111 [03:40<20:24,  5.04it/s]

Gaps (ex-reports):  13%|█▎        | 941/7111 [03:40<20:27,  5.02it/s]

Gaps (ex-reports):  13%|█▎        | 942/7111 [03:41<20:27,  5.03it/s]

Gaps (ex-reports):  13%|█▎        | 943/7111 [03:41<20:51,  4.93it/s]

Gaps (ex-reports):  13%|█▎        | 944/7111 [03:41<21:23,  4.80it/s]

Gaps (ex-reports):  13%|█▎        | 945/7111 [03:41<20:48,  4.94it/s]

Gaps (ex-reports):  13%|█▎        | 946/7111 [03:41<20:41,  4.97it/s]

Gaps (ex-reports):  13%|█▎        | 947/7111 [03:42<20:39,  4.97it/s]

Gaps (ex-reports):  13%|█▎        | 948/7111 [03:42<20:30,  5.01it/s]

Gaps (ex-reports):  13%|█▎        | 949/7111 [03:42<20:12,  5.08it/s]

Gaps (ex-reports):  13%|█▎        | 950/7111 [03:42<20:01,  5.13it/s]

Gaps (ex-reports):  13%|█▎        | 951/7111 [03:42<19:51,  5.17it/s]

Gaps (ex-reports):  13%|█▎        | 952/7111 [03:43<20:00,  5.13it/s]

Gaps (ex-reports):  13%|█▎        | 953/7111 [03:43<19:52,  5.16it/s]

Gaps (ex-reports):  13%|█▎        | 954/7111 [03:43<19:50,  5.17it/s]

Gaps (ex-reports):  13%|█▎        | 955/7111 [03:43<20:42,  4.95it/s]

Gaps (ex-reports):  13%|█▎        | 956/7111 [03:43<20:39,  4.97it/s]

Gaps (ex-reports):  13%|█▎        | 957/7111 [03:44<20:40,  4.96it/s]

Gaps (ex-reports):  13%|█▎        | 958/7111 [03:44<20:31,  5.00it/s]

Gaps (ex-reports):  13%|█▎        | 959/7111 [03:44<20:32,  4.99it/s]

Gaps (ex-reports):  14%|█▎        | 960/7111 [03:44<20:44,  4.94it/s]

Gaps (ex-reports):  14%|█▎        | 961/7111 [03:44<21:00,  4.88it/s]

Gaps (ex-reports):  14%|█▎        | 962/7111 [03:45<21:09,  4.84it/s]

Gaps (ex-reports):  14%|█▎        | 963/7111 [03:45<21:24,  4.79it/s]

Gaps (ex-reports):  14%|█▎        | 964/7111 [03:45<21:06,  4.85it/s]

Gaps (ex-reports):  14%|█▎        | 965/7111 [03:45<21:27,  4.77it/s]

Gaps (ex-reports):  14%|█▎        | 966/7111 [03:45<21:04,  4.86it/s]

Gaps (ex-reports):  14%|█▎        | 967/7111 [03:46<21:08,  4.84it/s]

Gaps (ex-reports):  14%|█▎        | 968/7111 [03:46<20:49,  4.92it/s]

Gaps (ex-reports):  14%|█▎        | 969/7111 [03:46<20:45,  4.93it/s]

Gaps (ex-reports):  14%|█▎        | 970/7111 [03:46<20:27,  5.00it/s]

Gaps (ex-reports):  14%|█▎        | 971/7111 [03:46<21:07,  4.84it/s]

Gaps (ex-reports):  14%|█▎        | 972/7111 [03:47<20:58,  4.88it/s]

Gaps (ex-reports):  14%|█▎        | 973/7111 [03:47<21:03,  4.86it/s]

Gaps (ex-reports):  14%|█▎        | 974/7111 [03:47<21:23,  4.78it/s]

Gaps (ex-reports):  14%|█▎        | 975/7111 [03:47<21:00,  4.87it/s]

Gaps (ex-reports):  14%|█▎        | 976/7111 [03:47<21:11,  4.83it/s]

Gaps (ex-reports):  14%|█▎        | 977/7111 [03:48<21:16,  4.80it/s]

Gaps (ex-reports):  14%|█▍        | 978/7111 [03:48<20:48,  4.91it/s]

Gaps (ex-reports):  14%|█▍        | 979/7111 [03:48<20:52,  4.90it/s]

Gaps (ex-reports):  14%|█▍        | 980/7111 [03:48<20:53,  4.89it/s]

Gaps (ex-reports):  14%|█▍        | 981/7111 [03:48<20:44,  4.93it/s]

Gaps (ex-reports):  14%|█▍        | 982/7111 [03:49<20:44,  4.93it/s]

Gaps (ex-reports):  14%|█▍        | 983/7111 [03:49<20:20,  5.02it/s]

Gaps (ex-reports):  14%|█▍        | 984/7111 [03:49<20:40,  4.94it/s]

Gaps (ex-reports):  14%|█▍        | 985/7111 [03:49<20:23,  5.01it/s]

Gaps (ex-reports):  14%|█▍        | 986/7111 [03:49<20:14,  5.04it/s]

Gaps (ex-reports):  14%|█▍        | 987/7111 [03:50<20:18,  5.02it/s]

Gaps (ex-reports):  14%|█▍        | 988/7111 [03:50<20:09,  5.06it/s]

Gaps (ex-reports):  14%|█▍        | 989/7111 [03:50<20:23,  5.00it/s]

Gaps (ex-reports):  14%|█▍        | 990/7111 [03:50<20:12,  5.05it/s]

Gaps (ex-reports):  14%|█▍        | 991/7111 [03:50<20:31,  4.97it/s]

Gaps (ex-reports):  14%|█▍        | 992/7111 [03:51<20:53,  4.88it/s]

Gaps (ex-reports):  14%|█▍        | 993/7111 [03:51<20:51,  4.89it/s]

Gaps (ex-reports):  14%|█▍        | 994/7111 [03:51<20:43,  4.92it/s]

Gaps (ex-reports):  14%|█▍        | 995/7111 [03:51<21:04,  4.84it/s]

Gaps (ex-reports):  14%|█▍        | 996/7111 [03:51<21:01,  4.85it/s]

Gaps (ex-reports):  14%|█▍        | 997/7111 [03:52<21:22,  4.77it/s]

Gaps (ex-reports):  14%|█▍        | 998/7111 [03:52<21:11,  4.81it/s]

Gaps (ex-reports):  14%|█▍        | 999/7111 [03:52<21:00,  4.85it/s]

Gaps (ex-reports):  14%|█▍        | 1000/7111 [03:52<20:48,  4.89it/s]

Gaps (ex-reports):  14%|█▍        | 1001/7111 [03:53<20:40,  4.92it/s]

Gaps (ex-reports):  14%|█▍        | 1002/7111 [03:53<21:01,  4.84it/s]

Gaps (ex-reports):  14%|█▍        | 1003/7111 [03:53<21:13,  4.80it/s]

Gaps (ex-reports):  14%|█▍        | 1004/7111 [03:53<21:16,  4.78it/s]

Gaps (ex-reports):  14%|█▍        | 1005/7111 [03:53<21:07,  4.82it/s]

Gaps (ex-reports):  14%|█▍        | 1006/7111 [03:54<20:47,  4.89it/s]

Gaps (ex-reports):  14%|█▍        | 1007/7111 [03:54<20:45,  4.90it/s]

Gaps (ex-reports):  14%|█▍        | 1008/7111 [03:54<20:15,  5.02it/s]

Gaps (ex-reports):  14%|█▍        | 1009/7111 [03:54<20:24,  4.98it/s]

Gaps (ex-reports):  14%|█▍        | 1010/7111 [03:54<20:26,  4.98it/s]

Gaps (ex-reports):  14%|█▍        | 1011/7111 [03:55<20:10,  5.04it/s]

Gaps (ex-reports):  14%|█▍        | 1012/7111 [03:55<20:23,  4.98it/s]

Gaps (ex-reports):  14%|█▍        | 1013/7111 [03:55<20:15,  5.02it/s]

Gaps (ex-reports):  14%|█▍        | 1014/7111 [03:55<20:40,  4.92it/s]

Gaps (ex-reports):  14%|█▍        | 1015/7111 [03:55<20:49,  4.88it/s]

Gaps (ex-reports):  14%|█▍        | 1016/7111 [03:56<20:27,  4.97it/s]

Gaps (ex-reports):  14%|█▍        | 1017/7111 [03:56<20:42,  4.90it/s]

Gaps (ex-reports):  14%|█▍        | 1018/7111 [03:56<20:21,  4.99it/s]

Gaps (ex-reports):  14%|█▍        | 1019/7111 [03:56<27:43,  3.66it/s]

Gaps (ex-reports):  14%|█▍        | 1020/7111 [03:57<25:30,  3.98it/s]

Gaps (ex-reports):  14%|█▍        | 1021/7111 [03:57<24:14,  4.19it/s]

Gaps (ex-reports):  14%|█▍        | 1022/7111 [03:58<50:48,  2.00it/s]

Gaps (ex-reports):  14%|█▍        | 1023/7111 [03:58<42:06,  2.41it/s]

Gaps (ex-reports):  14%|█▍        | 1024/7111 [03:58<35:24,  2.86it/s]

Gaps (ex-reports):  14%|█▍        | 1025/7111 [03:59<30:42,  3.30it/s]

Gaps (ex-reports):  14%|█▍        | 1026/7111 [03:59<27:48,  3.65it/s]

Gaps (ex-reports):  14%|█▍        | 1027/7111 [03:59<25:17,  4.01it/s]

Gaps (ex-reports):  14%|█▍        | 1028/7111 [03:59<24:08,  4.20it/s]

Gaps (ex-reports):  14%|█▍        | 1029/7111 [03:59<23:12,  4.37it/s]

Gaps (ex-reports):  14%|█▍        | 1030/7111 [04:00<22:22,  4.53it/s]

Gaps (ex-reports):  14%|█▍        | 1031/7111 [04:00<21:36,  4.69it/s]

Gaps (ex-reports):  15%|█▍        | 1032/7111 [04:00<21:22,  4.74it/s]

Gaps (ex-reports):  15%|█▍        | 1033/7111 [04:00<20:56,  4.84it/s]

Gaps (ex-reports):  15%|█▍        | 1034/7111 [04:00<20:56,  4.84it/s]

Gaps (ex-reports):  15%|█▍        | 1035/7111 [04:01<20:50,  4.86it/s]

Gaps (ex-reports):  15%|█▍        | 1036/7111 [04:01<20:51,  4.85it/s]

Gaps (ex-reports):  15%|█▍        | 1037/7111 [04:01<20:53,  4.85it/s]

Gaps (ex-reports):  15%|█▍        | 1038/7111 [04:01<20:40,  4.90it/s]

Gaps (ex-reports):  15%|█▍        | 1039/7111 [04:01<20:42,  4.89it/s]

Gaps (ex-reports):  15%|█▍        | 1040/7111 [04:02<20:44,  4.88it/s]

Gaps (ex-reports):  15%|█▍        | 1041/7111 [04:02<20:53,  4.84it/s]

Gaps (ex-reports):  15%|█▍        | 1042/7111 [04:02<20:59,  4.82it/s]

Gaps (ex-reports):  15%|█▍        | 1043/7111 [04:02<21:16,  4.75it/s]

Gaps (ex-reports):  15%|█▍        | 1044/7111 [04:02<20:41,  4.89it/s]

Gaps (ex-reports):  15%|█▍        | 1045/7111 [04:03<20:36,  4.91it/s]

Gaps (ex-reports):  15%|█▍        | 1046/7111 [04:03<20:28,  4.94it/s]

Gaps (ex-reports):  15%|█▍        | 1047/7111 [04:03<20:12,  5.00it/s]

Gaps (ex-reports):  15%|█▍        | 1048/7111 [04:03<19:58,  5.06it/s]

Gaps (ex-reports):  15%|█▍        | 1049/7111 [04:03<19:47,  5.10it/s]

Gaps (ex-reports):  15%|█▍        | 1050/7111 [04:04<19:50,  5.09it/s]

Gaps (ex-reports):  15%|█▍        | 1051/7111 [04:04<20:22,  4.96it/s]

Gaps (ex-reports):  15%|█▍        | 1052/7111 [04:04<20:10,  5.00it/s]

Gaps (ex-reports):  15%|█▍        | 1053/7111 [04:04<20:16,  4.98it/s]

Gaps (ex-reports):  15%|█▍        | 1054/7111 [04:04<20:24,  4.95it/s]

Gaps (ex-reports):  15%|█▍        | 1055/7111 [04:05<20:39,  4.88it/s]

Gaps (ex-reports):  15%|█▍        | 1056/7111 [04:05<20:44,  4.87it/s]

Gaps (ex-reports):  15%|█▍        | 1057/7111 [04:05<21:01,  4.80it/s]

Gaps (ex-reports):  15%|█▍        | 1058/7111 [04:05<20:35,  4.90it/s]

Gaps (ex-reports):  15%|█▍        | 1059/7111 [04:05<20:42,  4.87it/s]

Gaps (ex-reports):  15%|█▍        | 1060/7111 [04:06<20:50,  4.84it/s]

Gaps (ex-reports):  15%|█▍        | 1061/7111 [04:06<20:54,  4.82it/s]

Gaps (ex-reports):  15%|█▍        | 1062/7111 [04:06<20:45,  4.86it/s]

Gaps (ex-reports):  15%|█▍        | 1063/7111 [04:06<20:48,  4.85it/s]

Gaps (ex-reports):  15%|█▍        | 1064/7111 [04:07<26:09,  3.85it/s]

Gaps (ex-reports):  15%|█▍        | 1065/7111 [04:07<24:06,  4.18it/s]

Gaps (ex-reports):  15%|█▍        | 1066/7111 [04:07<23:06,  4.36it/s]

Gaps (ex-reports):  15%|█▌        | 1067/7111 [04:07<22:22,  4.50it/s]

Gaps (ex-reports):  15%|█▌        | 1068/7111 [04:07<21:27,  4.69it/s]

Gaps (ex-reports):  15%|█▌        | 1069/7111 [04:08<21:10,  4.75it/s]

Gaps (ex-reports):  15%|█▌        | 1070/7111 [04:08<21:01,  4.79it/s]

Gaps (ex-reports):  15%|█▌        | 1071/7111 [04:08<21:02,  4.79it/s]

Gaps (ex-reports):  15%|█▌        | 1072/7111 [04:08<21:05,  4.77it/s]

Gaps (ex-reports):  15%|█▌        | 1073/7111 [04:08<20:48,  4.84it/s]

Gaps (ex-reports):  15%|█▌        | 1074/7111 [04:09<20:58,  4.80it/s]

Gaps (ex-reports):  15%|█▌        | 1075/7111 [04:09<21:02,  4.78it/s]

Gaps (ex-reports):  15%|█▌        | 1076/7111 [04:09<20:55,  4.81it/s]

Gaps (ex-reports):  15%|█▌        | 1077/7111 [04:09<20:20,  4.94it/s]

Gaps (ex-reports):  15%|█▌        | 1078/7111 [04:09<20:07,  5.00it/s]

Gaps (ex-reports):  15%|█▌        | 1079/7111 [04:10<20:36,  4.88it/s]

Gaps (ex-reports):  15%|█▌        | 1080/7111 [04:10<29:23,  3.42it/s]

Gaps (ex-reports):  15%|█▌        | 1081/7111 [04:10<26:32,  3.79it/s]

Gaps (ex-reports):  15%|█▌        | 1082/7111 [04:11<25:24,  3.96it/s]

Gaps (ex-reports):  15%|█▌        | 1083/7111 [04:11<23:50,  4.21it/s]

Gaps (ex-reports):  15%|█▌        | 1084/7111 [04:11<22:47,  4.41it/s]

Gaps (ex-reports):  15%|█▌        | 1085/7111 [04:11<21:44,  4.62it/s]

Gaps (ex-reports):  15%|█▌        | 1086/7111 [04:11<21:14,  4.73it/s]

Gaps (ex-reports):  15%|█▌        | 1087/7111 [04:12<20:48,  4.82it/s]

Gaps (ex-reports):  15%|█▌        | 1088/7111 [04:12<20:58,  4.79it/s]

Gaps (ex-reports):  15%|█▌        | 1089/7111 [04:12<20:51,  4.81it/s]

Gaps (ex-reports):  15%|█▌        | 1090/7111 [04:12<20:40,  4.85it/s]

Gaps (ex-reports):  15%|█▌        | 1091/7111 [04:12<21:53,  4.58it/s]

Gaps (ex-reports):  15%|█▌        | 1092/7111 [04:13<21:24,  4.69it/s]

Gaps (ex-reports):  15%|█▌        | 1093/7111 [04:13<20:49,  4.81it/s]

Gaps (ex-reports):  15%|█▌        | 1094/7111 [04:13<20:22,  4.92it/s]

Gaps (ex-reports):  15%|█▌        | 1095/7111 [04:13<20:01,  5.01it/s]

Gaps (ex-reports):  15%|█▌        | 1096/7111 [04:13<19:50,  5.05it/s]

Gaps (ex-reports):  15%|█▌        | 1097/7111 [04:14<20:32,  4.88it/s]

Gaps (ex-reports):  15%|█▌        | 1098/7111 [04:14<20:16,  4.94it/s]

Gaps (ex-reports):  15%|█▌        | 1099/7111 [04:14<20:32,  4.88it/s]

Gaps (ex-reports):  15%|█▌        | 1100/7111 [04:14<20:35,  4.87it/s]

Gaps (ex-reports):  15%|█▌        | 1101/7111 [04:15<20:48,  4.82it/s]

Gaps (ex-reports):  15%|█▌        | 1102/7111 [04:15<20:50,  4.80it/s]

Gaps (ex-reports):  16%|█▌        | 1103/7111 [04:15<20:51,  4.80it/s]

Gaps (ex-reports):  16%|█▌        | 1104/7111 [04:15<21:09,  4.73it/s]

Gaps (ex-reports):  16%|█▌        | 1105/7111 [04:16<44:59,  2.23it/s]

Gaps (ex-reports):  16%|█▌        | 1106/7111 [04:16<37:42,  2.65it/s]

Gaps (ex-reports):  16%|█▌        | 1107/7111 [04:17<32:43,  3.06it/s]

Gaps (ex-reports):  16%|█▌        | 1108/7111 [04:17<29:10,  3.43it/s]

Gaps (ex-reports):  16%|█▌        | 1109/7111 [04:17<26:43,  3.74it/s]

Gaps (ex-reports):  16%|█▌        | 1110/7111 [04:17<24:53,  4.02it/s]

Gaps (ex-reports):  16%|█▌        | 1111/7111 [04:17<23:34,  4.24it/s]

Gaps (ex-reports):  16%|█▌        | 1112/7111 [04:18<22:44,  4.40it/s]

Gaps (ex-reports):  16%|█▌        | 1113/7111 [04:18<21:59,  4.54it/s]

Gaps (ex-reports):  16%|█▌        | 1114/7111 [04:18<21:27,  4.66it/s]

Gaps (ex-reports):  16%|█▌        | 1115/7111 [04:18<21:45,  4.59it/s]

Gaps (ex-reports):  16%|█▌        | 1116/7111 [04:18<21:32,  4.64it/s]

Gaps (ex-reports):  16%|█▌        | 1117/7111 [04:19<21:15,  4.70it/s]

Gaps (ex-reports):  16%|█▌        | 1118/7111 [04:19<21:07,  4.73it/s]

Gaps (ex-reports):  16%|█▌        | 1119/7111 [04:19<20:50,  4.79it/s]

Gaps (ex-reports):  16%|█▌        | 1120/7111 [04:19<20:24,  4.89it/s]

Gaps (ex-reports):  16%|█▌        | 1121/7111 [04:19<20:19,  4.91it/s]

Gaps (ex-reports):  16%|█▌        | 1122/7111 [04:20<20:18,  4.91it/s]

Gaps (ex-reports):  16%|█▌        | 1123/7111 [04:20<20:18,  4.91it/s]

Gaps (ex-reports):  16%|█▌        | 1124/7111 [04:20<19:56,  5.00it/s]

Gaps (ex-reports):  16%|█▌        | 1125/7111 [04:20<20:15,  4.92it/s]

Gaps (ex-reports):  16%|█▌        | 1126/7111 [04:20<20:19,  4.91it/s]

Gaps (ex-reports):  16%|█▌        | 1127/7111 [04:21<20:55,  4.76it/s]

Gaps (ex-reports):  16%|█▌        | 1128/7111 [04:21<20:25,  4.88it/s]

Gaps (ex-reports):  16%|█▌        | 1129/7111 [04:21<20:08,  4.95it/s]

Gaps (ex-reports):  16%|█▌        | 1130/7111 [04:21<20:37,  4.83it/s]

Gaps (ex-reports):  16%|█▌        | 1131/7111 [04:22<20:18,  4.91it/s]

Gaps (ex-reports):  16%|█▌        | 1132/7111 [04:22<20:41,  4.81it/s]

Gaps (ex-reports):  16%|█▌        | 1133/7111 [04:22<20:40,  4.82it/s]

Gaps (ex-reports):  16%|█▌        | 1134/7111 [04:22<20:41,  4.82it/s]

Gaps (ex-reports):  16%|█▌        | 1135/7111 [04:22<20:26,  4.87it/s]

Gaps (ex-reports):  16%|█▌        | 1136/7111 [04:23<20:02,  4.97it/s]

Gaps (ex-reports):  16%|█▌        | 1137/7111 [04:23<20:11,  4.93it/s]

Gaps (ex-reports):  16%|█▌        | 1138/7111 [04:23<20:13,  4.92it/s]

Gaps (ex-reports):  16%|█▌        | 1139/7111 [04:23<20:20,  4.89it/s]

Gaps (ex-reports):  16%|█▌        | 1140/7111 [04:23<20:19,  4.90it/s]

Gaps (ex-reports):  16%|█▌        | 1141/7111 [04:24<20:31,  4.85it/s]

Gaps (ex-reports):  16%|█▌        | 1142/7111 [04:24<20:27,  4.86it/s]

Gaps (ex-reports):  16%|█▌        | 1143/7111 [04:24<20:51,  4.77it/s]

Gaps (ex-reports):  16%|█▌        | 1144/7111 [04:24<20:42,  4.80it/s]

Gaps (ex-reports):  16%|█▌        | 1145/7111 [04:24<20:35,  4.83it/s]

Gaps (ex-reports):  16%|█▌        | 1146/7111 [04:25<20:40,  4.81it/s]

Gaps (ex-reports):  16%|█▌        | 1147/7111 [04:25<20:38,  4.82it/s]

Gaps (ex-reports):  16%|█▌        | 1148/7111 [04:25<20:47,  4.78it/s]

Gaps (ex-reports):  16%|█▌        | 1149/7111 [04:25<20:44,  4.79it/s]

Gaps (ex-reports):  16%|█▌        | 1150/7111 [04:25<20:29,  4.85it/s]

Gaps (ex-reports):  16%|█▌        | 1151/7111 [04:26<20:03,  4.95it/s]

Gaps (ex-reports):  16%|█▌        | 1152/7111 [04:26<20:12,  4.92it/s]

Gaps (ex-reports):  16%|█▌        | 1153/7111 [04:26<20:01,  4.96it/s]

Gaps (ex-reports):  16%|█▌        | 1154/7111 [04:26<20:10,  4.92it/s]

Gaps (ex-reports):  16%|█▌        | 1155/7111 [04:26<20:12,  4.91it/s]

Gaps (ex-reports):  16%|█▋        | 1156/7111 [04:27<20:51,  4.76it/s]

Gaps (ex-reports):  16%|█▋        | 1157/7111 [04:27<20:33,  4.83it/s]

Gaps (ex-reports):  16%|█▋        | 1158/7111 [04:27<20:23,  4.86it/s]

Gaps (ex-reports):  16%|█▋        | 1159/7111 [04:27<20:24,  4.86it/s]

Gaps (ex-reports):  16%|█▋        | 1160/7111 [04:27<20:08,  4.92it/s]

Gaps (ex-reports):  16%|█▋        | 1161/7111 [04:28<20:17,  4.89it/s]

Gaps (ex-reports):  16%|█▋        | 1162/7111 [04:28<20:24,  4.86it/s]

Gaps (ex-reports):  16%|█▋        | 1163/7111 [04:28<20:25,  4.85it/s]

Gaps (ex-reports):  16%|█▋        | 1164/7111 [04:28<20:03,  4.94it/s]

Gaps (ex-reports):  16%|█▋        | 1165/7111 [04:28<20:03,  4.94it/s]

Gaps (ex-reports):  16%|█▋        | 1166/7111 [04:29<20:25,  4.85it/s]

Gaps (ex-reports):  16%|█▋        | 1167/7111 [04:29<20:26,  4.85it/s]

Gaps (ex-reports):  16%|█▋        | 1168/7111 [04:29<20:35,  4.81it/s]

Gaps (ex-reports):  16%|█▋        | 1169/7111 [04:29<20:36,  4.80it/s]

Gaps (ex-reports):  16%|█▋        | 1170/7111 [04:30<20:27,  4.84it/s]

Gaps (ex-reports):  16%|█▋        | 1171/7111 [04:30<20:43,  4.78it/s]

Gaps (ex-reports):  16%|█▋        | 1172/7111 [04:30<20:20,  4.87it/s]

Gaps (ex-reports):  16%|█▋        | 1173/7111 [04:30<20:09,  4.91it/s]

Gaps (ex-reports):  17%|█▋        | 1174/7111 [04:30<20:17,  4.88it/s]

Gaps (ex-reports):  17%|█▋        | 1175/7111 [04:31<20:14,  4.89it/s]

Gaps (ex-reports):  17%|█▋        | 1176/7111 [04:31<19:57,  4.96it/s]

Gaps (ex-reports):  17%|█▋        | 1177/7111 [04:31<20:02,  4.93it/s]

Gaps (ex-reports):  17%|█▋        | 1178/7111 [04:31<20:15,  4.88it/s]

Gaps (ex-reports):  17%|█▋        | 1179/7111 [04:31<20:23,  4.85it/s]

Gaps (ex-reports):  17%|█▋        | 1180/7111 [04:32<20:32,  4.81it/s]

Gaps (ex-reports):  17%|█▋        | 1181/7111 [04:32<20:52,  4.73it/s]

Gaps (ex-reports):  17%|█▋        | 1182/7111 [04:32<20:46,  4.76it/s]

Gaps (ex-reports):  17%|█▋        | 1183/7111 [04:32<20:54,  4.73it/s]

Gaps (ex-reports):  17%|█▋        | 1184/7111 [04:32<20:44,  4.76it/s]

Gaps (ex-reports):  17%|█▋        | 1185/7111 [04:33<20:50,  4.74it/s]

Gaps (ex-reports):  17%|█▋        | 1186/7111 [04:33<20:31,  4.81it/s]

Gaps (ex-reports):  17%|█▋        | 1187/7111 [04:33<20:38,  4.78it/s]

Gaps (ex-reports):  17%|█▋        | 1188/7111 [04:33<20:35,  4.80it/s]

Gaps (ex-reports):  17%|█▋        | 1189/7111 [04:33<20:09,  4.90it/s]

Gaps (ex-reports):  17%|█▋        | 1190/7111 [04:34<19:58,  4.94it/s]

Gaps (ex-reports):  17%|█▋        | 1191/7111 [04:34<20:13,  4.88it/s]

Gaps (ex-reports):  17%|█▋        | 1192/7111 [04:34<20:09,  4.89it/s]

Gaps (ex-reports):  17%|█▋        | 1193/7111 [04:34<19:58,  4.94it/s]

Gaps (ex-reports):  17%|█▋        | 1194/7111 [04:34<20:07,  4.90it/s]

Gaps (ex-reports):  17%|█▋        | 1195/7111 [04:35<20:09,  4.89it/s]

Gaps (ex-reports):  17%|█▋        | 1196/7111 [04:35<19:50,  4.97it/s]

Gaps (ex-reports):  17%|█▋        | 1197/7111 [04:35<19:52,  4.96it/s]

Gaps (ex-reports):  17%|█▋        | 1198/7111 [04:35<20:24,  4.83it/s]

Gaps (ex-reports):  17%|█▋        | 1199/7111 [04:36<20:29,  4.81it/s]

Gaps (ex-reports):  17%|█▋        | 1200/7111 [04:36<20:06,  4.90it/s]

Gaps (ex-reports):  17%|█▋        | 1201/7111 [04:36<19:44,  4.99it/s]

Gaps (ex-reports):  17%|█▋        | 1202/7111 [04:36<19:30,  5.05it/s]

Gaps (ex-reports):  17%|█▋        | 1203/7111 [04:36<19:42,  5.00it/s]

Gaps (ex-reports):  17%|█▋        | 1204/7111 [04:37<19:58,  4.93it/s]

Gaps (ex-reports):  17%|█▋        | 1205/7111 [04:37<19:51,  4.96it/s]

Gaps (ex-reports):  17%|█▋        | 1206/7111 [04:37<20:25,  4.82it/s]

Gaps (ex-reports):  17%|█▋        | 1207/7111 [04:37<20:14,  4.86it/s]

Gaps (ex-reports):  17%|█▋        | 1208/7111 [04:37<20:23,  4.82it/s]

Gaps (ex-reports):  17%|█▋        | 1209/7111 [04:38<20:10,  4.87it/s]

Gaps (ex-reports):  17%|█▋        | 1210/7111 [04:38<20:35,  4.78it/s]

Gaps (ex-reports):  17%|█▋        | 1211/7111 [04:38<20:11,  4.87it/s]

Gaps (ex-reports):  17%|█▋        | 1212/7111 [04:38<20:36,  4.77it/s]

Gaps (ex-reports):  17%|█▋        | 1213/7111 [04:38<20:43,  4.74it/s]

Gaps (ex-reports):  17%|█▋        | 1214/7111 [04:39<20:27,  4.81it/s]

Gaps (ex-reports):  17%|█▋        | 1215/7111 [04:39<20:37,  4.77it/s]

Gaps (ex-reports):  17%|█▋        | 1216/7111 [04:39<20:32,  4.78it/s]

Gaps (ex-reports):  17%|█▋        | 1217/7111 [04:39<20:23,  4.82it/s]

Gaps (ex-reports):  17%|█▋        | 1218/7111 [04:39<20:10,  4.87it/s]

Gaps (ex-reports):  17%|█▋        | 1219/7111 [04:40<19:56,  4.92it/s]

Gaps (ex-reports):  17%|█▋        | 1220/7111 [04:40<19:58,  4.92it/s]

Gaps (ex-reports):  17%|█▋        | 1221/7111 [04:40<19:49,  4.95it/s]

Gaps (ex-reports):  17%|█▋        | 1222/7111 [04:40<19:27,  5.04it/s]

Gaps (ex-reports):  17%|█▋        | 1223/7111 [04:40<19:34,  5.01it/s]

Gaps (ex-reports):  17%|█▋        | 1224/7111 [04:41<19:54,  4.93it/s]

Gaps (ex-reports):  17%|█▋        | 1225/7111 [04:41<19:38,  5.00it/s]

Gaps (ex-reports):  17%|█▋        | 1226/7111 [04:41<19:23,  5.06it/s]

Gaps (ex-reports):  17%|█▋        | 1227/7111 [04:41<20:18,  4.83it/s]

Gaps (ex-reports):  17%|█▋        | 1228/7111 [04:41<19:47,  4.95it/s]

Gaps (ex-reports):  17%|█▋        | 1229/7111 [04:42<20:34,  4.76it/s]

Gaps (ex-reports):  17%|█▋        | 1230/7111 [04:42<20:24,  4.80it/s]

Gaps (ex-reports):  17%|█▋        | 1231/7111 [04:42<20:03,  4.89it/s]

Gaps (ex-reports):  17%|█▋        | 1232/7111 [04:42<19:53,  4.93it/s]

Gaps (ex-reports):  17%|█▋        | 1233/7111 [04:42<20:01,  4.89it/s]

Gaps (ex-reports):  17%|█▋        | 1234/7111 [04:44<45:03,  2.17it/s]

Gaps (ex-reports):  17%|█▋        | 1235/7111 [04:44<37:13,  2.63it/s]

Gaps (ex-reports):  17%|█▋        | 1236/7111 [04:44<31:51,  3.07it/s]

Gaps (ex-reports):  17%|█▋        | 1237/7111 [04:44<28:29,  3.44it/s]

Gaps (ex-reports):  17%|█▋        | 1238/7111 [04:44<26:02,  3.76it/s]

Gaps (ex-reports):  17%|█▋        | 1239/7111 [04:45<24:08,  4.05it/s]

Gaps (ex-reports):  17%|█▋        | 1240/7111 [04:45<22:40,  4.32it/s]

Gaps (ex-reports):  17%|█▋        | 1241/7111 [04:45<21:51,  4.48it/s]

Gaps (ex-reports):  17%|█▋        | 1242/7111 [04:45<21:20,  4.58it/s]

Gaps (ex-reports):  17%|█▋        | 1243/7111 [04:45<20:41,  4.73it/s]

Gaps (ex-reports):  17%|█▋        | 1244/7111 [04:46<20:29,  4.77it/s]

Gaps (ex-reports):  18%|█▊        | 1245/7111 [04:46<20:25,  4.79it/s]

Gaps (ex-reports):  18%|█▊        | 1246/7111 [04:46<19:59,  4.89it/s]

Gaps (ex-reports):  18%|█▊        | 1247/7111 [04:46<19:37,  4.98it/s]

Gaps (ex-reports):  18%|█▊        | 1248/7111 [04:46<19:50,  4.92it/s]

Gaps (ex-reports):  18%|█▊        | 1249/7111 [04:47<19:46,  4.94it/s]

Gaps (ex-reports):  18%|█▊        | 1250/7111 [04:47<19:44,  4.95it/s]

Gaps (ex-reports):  18%|█▊        | 1251/7111 [04:47<19:39,  4.97it/s]

Gaps (ex-reports):  18%|█▊        | 1252/7111 [04:47<19:33,  4.99it/s]

Gaps (ex-reports):  18%|█▊        | 1253/7111 [04:47<19:50,  4.92it/s]

Gaps (ex-reports):  18%|█▊        | 1254/7111 [04:48<19:45,  4.94it/s]

Gaps (ex-reports):  18%|█▊        | 1255/7111 [04:48<20:14,  4.82it/s]

Gaps (ex-reports):  18%|█▊        | 1256/7111 [04:48<19:57,  4.89it/s]

Gaps (ex-reports):  18%|█▊        | 1257/7111 [04:48<19:41,  4.95it/s]

Gaps (ex-reports):  18%|█▊        | 1258/7111 [04:48<19:23,  5.03it/s]

Gaps (ex-reports):  18%|█▊        | 1259/7111 [04:49<19:29,  5.00it/s]

Gaps (ex-reports):  18%|█▊        | 1260/7111 [04:49<19:32,  4.99it/s]

Gaps (ex-reports):  18%|█▊        | 1261/7111 [04:49<19:44,  4.94it/s]

Gaps (ex-reports):  18%|█▊        | 1262/7111 [04:49<19:58,  4.88it/s]

Gaps (ex-reports):  18%|█▊        | 1263/7111 [04:49<19:52,  4.91it/s]

Gaps (ex-reports):  18%|█▊        | 1264/7111 [04:50<20:06,  4.85it/s]

Gaps (ex-reports):  18%|█▊        | 1265/7111 [04:50<20:14,  4.81it/s]

Gaps (ex-reports):  18%|█▊        | 1266/7111 [04:50<20:23,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1267/7111 [04:50<20:15,  4.81it/s]

Gaps (ex-reports):  18%|█▊        | 1268/7111 [04:50<20:35,  4.73it/s]

Gaps (ex-reports):  18%|█▊        | 1269/7111 [04:51<20:43,  4.70it/s]

Gaps (ex-reports):  18%|█▊        | 1270/7111 [04:51<20:11,  4.82it/s]

Gaps (ex-reports):  18%|█▊        | 1271/7111 [04:51<19:56,  4.88it/s]

Gaps (ex-reports):  18%|█▊        | 1272/7111 [04:51<19:54,  4.89it/s]

Gaps (ex-reports):  18%|█▊        | 1273/7111 [04:51<20:01,  4.86it/s]

Gaps (ex-reports):  18%|█▊        | 1274/7111 [04:52<19:57,  4.88it/s]

Gaps (ex-reports):  18%|█▊        | 1275/7111 [04:52<19:43,  4.93it/s]

Gaps (ex-reports):  18%|█▊        | 1276/7111 [04:52<19:57,  4.87it/s]

Gaps (ex-reports):  18%|█▊        | 1277/7111 [04:52<19:59,  4.86it/s]

Gaps (ex-reports):  18%|█▊        | 1278/7111 [04:52<19:53,  4.89it/s]

Gaps (ex-reports):  18%|█▊        | 1279/7111 [04:53<19:23,  5.01it/s]

Gaps (ex-reports):  18%|█▊        | 1280/7111 [04:53<20:08,  4.83it/s]

Gaps (ex-reports):  18%|█▊        | 1281/7111 [04:53<19:41,  4.93it/s]

Gaps (ex-reports):  18%|█▊        | 1282/7111 [04:53<19:50,  4.90it/s]

Gaps (ex-reports):  18%|█▊        | 1283/7111 [04:54<20:05,  4.83it/s]

Gaps (ex-reports):  18%|█▊        | 1284/7111 [04:54<19:45,  4.91it/s]

Gaps (ex-reports):  18%|█▊        | 1285/7111 [04:54<19:45,  4.92it/s]

Gaps (ex-reports):  18%|█▊        | 1286/7111 [04:54<19:20,  5.02it/s]

Gaps (ex-reports):  18%|█▊        | 1287/7111 [04:54<19:48,  4.90it/s]

Gaps (ex-reports):  18%|█▊        | 1288/7111 [04:55<19:47,  4.90it/s]

Gaps (ex-reports):  18%|█▊        | 1289/7111 [04:55<20:03,  4.84it/s]

Gaps (ex-reports):  18%|█▊        | 1290/7111 [04:55<20:02,  4.84it/s]

Gaps (ex-reports):  18%|█▊        | 1291/7111 [04:55<20:17,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1292/7111 [04:55<19:43,  4.92it/s]

Gaps (ex-reports):  18%|█▊        | 1293/7111 [04:56<19:39,  4.93it/s]

Gaps (ex-reports):  18%|█▊        | 1294/7111 [04:56<20:03,  4.83it/s]

Gaps (ex-reports):  18%|█▊        | 1295/7111 [04:56<20:05,  4.82it/s]

Gaps (ex-reports):  18%|█▊        | 1296/7111 [04:56<19:53,  4.87it/s]

Gaps (ex-reports):  18%|█▊        | 1297/7111 [04:56<19:54,  4.87it/s]

Gaps (ex-reports):  18%|█▊        | 1298/7111 [04:57<20:08,  4.81it/s]

Gaps (ex-reports):  18%|█▊        | 1299/7111 [04:57<19:45,  4.90it/s]

Gaps (ex-reports):  18%|█▊        | 1300/7111 [04:57<20:16,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1301/7111 [04:57<19:51,  4.87it/s]

Gaps (ex-reports):  18%|█▊        | 1302/7111 [04:57<19:43,  4.91it/s]

Gaps (ex-reports):  18%|█▊        | 1303/7111 [04:58<19:32,  4.95it/s]

Gaps (ex-reports):  18%|█▊        | 1304/7111 [04:58<21:24,  4.52it/s]

Gaps (ex-reports):  18%|█▊        | 1305/7111 [04:58<20:43,  4.67it/s]

Gaps (ex-reports):  18%|█▊        | 1306/7111 [04:58<20:14,  4.78it/s]

Gaps (ex-reports):  18%|█▊        | 1307/7111 [04:58<20:30,  4.72it/s]

Gaps (ex-reports):  18%|█▊        | 1308/7111 [04:59<19:58,  4.84it/s]

Gaps (ex-reports):  18%|█▊        | 1309/7111 [04:59<19:33,  4.95it/s]

Gaps (ex-reports):  18%|█▊        | 1310/7111 [04:59<19:30,  4.96it/s]

Gaps (ex-reports):  18%|█▊        | 1311/7111 [04:59<19:29,  4.96it/s]

Gaps (ex-reports):  18%|█▊        | 1312/7111 [04:59<19:46,  4.89it/s]

Gaps (ex-reports):  18%|█▊        | 1313/7111 [05:00<19:40,  4.91it/s]

Gaps (ex-reports):  18%|█▊        | 1314/7111 [05:00<19:31,  4.95it/s]

Gaps (ex-reports):  18%|█▊        | 1315/7111 [05:00<19:31,  4.95it/s]

Gaps (ex-reports):  19%|█▊        | 1316/7111 [05:00<19:24,  4.98it/s]

Gaps (ex-reports):  19%|█▊        | 1317/7111 [05:00<19:26,  4.97it/s]

Gaps (ex-reports):  19%|█▊        | 1318/7111 [05:01<19:51,  4.86it/s]

Gaps (ex-reports):  19%|█▊        | 1319/7111 [05:01<20:07,  4.79it/s]

Gaps (ex-reports):  19%|█▊        | 1320/7111 [05:01<19:39,  4.91it/s]

Gaps (ex-reports):  19%|█▊        | 1321/7111 [05:01<19:22,  4.98it/s]

Gaps (ex-reports):  19%|█▊        | 1322/7111 [05:01<19:12,  5.02it/s]

Gaps (ex-reports):  19%|█▊        | 1323/7111 [05:02<19:08,  5.04it/s]

Gaps (ex-reports):  19%|█▊        | 1324/7111 [05:02<19:26,  4.96it/s]

Gaps (ex-reports):  19%|█▊        | 1325/7111 [05:02<19:25,  4.96it/s]

Gaps (ex-reports):  19%|█▊        | 1326/7111 [05:02<19:32,  4.93it/s]

Gaps (ex-reports):  19%|█▊        | 1327/7111 [05:02<19:15,  5.00it/s]

Gaps (ex-reports):  19%|█▊        | 1328/7111 [05:03<19:30,  4.94it/s]

Gaps (ex-reports):  19%|█▊        | 1329/7111 [05:03<19:31,  4.93it/s]

Gaps (ex-reports):  19%|█▊        | 1330/7111 [05:03<19:51,  4.85it/s]

Gaps (ex-reports):  19%|█▊        | 1331/7111 [05:03<19:36,  4.91it/s]

Gaps (ex-reports):  19%|█▊        | 1332/7111 [05:04<19:28,  4.95it/s]

Gaps (ex-reports):  19%|█▊        | 1333/7111 [05:04<19:42,  4.89it/s]

Gaps (ex-reports):  19%|█▉        | 1334/7111 [05:04<19:46,  4.87it/s]

Gaps (ex-reports):  19%|█▉        | 1335/7111 [05:04<20:01,  4.81it/s]

Gaps (ex-reports):  19%|█▉        | 1336/7111 [05:04<20:36,  4.67it/s]

Gaps (ex-reports):  19%|█▉        | 1337/7111 [05:05<20:03,  4.80it/s]

Gaps (ex-reports):  19%|█▉        | 1338/7111 [05:05<19:37,  4.90it/s]

Gaps (ex-reports):  19%|█▉        | 1339/7111 [05:05<19:17,  4.99it/s]

Gaps (ex-reports):  19%|█▉        | 1340/7111 [05:05<19:23,  4.96it/s]

Gaps (ex-reports):  19%|█▉        | 1341/7111 [05:05<19:10,  5.02it/s]

Gaps (ex-reports):  19%|█▉        | 1342/7111 [05:06<19:15,  4.99it/s]

Gaps (ex-reports):  19%|█▉        | 1343/7111 [05:06<19:31,  4.93it/s]

Gaps (ex-reports):  19%|█▉        | 1344/7111 [05:06<19:21,  4.97it/s]

Gaps (ex-reports):  19%|█▉        | 1345/7111 [05:06<19:46,  4.86it/s]

Gaps (ex-reports):  19%|█▉        | 1346/7111 [05:06<19:49,  4.85it/s]

Gaps (ex-reports):  19%|█▉        | 1347/7111 [05:07<20:05,  4.78it/s]

Gaps (ex-reports):  19%|█▉        | 1348/7111 [05:07<19:54,  4.82it/s]

Gaps (ex-reports):  19%|█▉        | 1349/7111 [05:07<19:34,  4.90it/s]

Gaps (ex-reports):  19%|█▉        | 1350/7111 [05:07<19:49,  4.84it/s]

Gaps (ex-reports):  19%|█▉        | 1351/7111 [05:07<19:46,  4.86it/s]

Gaps (ex-reports):  19%|█▉        | 1352/7111 [05:08<19:52,  4.83it/s]

Gaps (ex-reports):  19%|█▉        | 1353/7111 [05:08<19:24,  4.94it/s]

Gaps (ex-reports):  19%|█▉        | 1354/7111 [05:08<19:29,  4.92it/s]

Gaps (ex-reports):  19%|█▉        | 1355/7111 [05:08<19:55,  4.82it/s]

Gaps (ex-reports):  19%|█▉        | 1356/7111 [05:08<19:52,  4.83it/s]

Gaps (ex-reports):  19%|█▉        | 1357/7111 [05:09<19:41,  4.87it/s]

Gaps (ex-reports):  19%|█▉        | 1358/7111 [05:09<19:52,  4.82it/s]

Gaps (ex-reports):  19%|█▉        | 1359/7111 [05:09<19:44,  4.86it/s]

Gaps (ex-reports):  19%|█▉        | 1360/7111 [05:09<19:31,  4.91it/s]

Gaps (ex-reports):  19%|█▉        | 1361/7111 [05:09<19:43,  4.86it/s]

Gaps (ex-reports):  19%|█▉        | 1362/7111 [05:10<20:01,  4.79it/s]

Gaps (ex-reports):  19%|█▉        | 1363/7111 [05:10<20:04,  4.77it/s]

Gaps (ex-reports):  19%|█▉        | 1364/7111 [05:10<19:57,  4.80it/s]

Gaps (ex-reports):  19%|█▉        | 1365/7111 [05:10<19:57,  4.80it/s]

Gaps (ex-reports):  19%|█▉        | 1366/7111 [05:11<19:33,  4.89it/s]

Gaps (ex-reports):  19%|█▉        | 1367/7111 [05:11<19:35,  4.89it/s]

Gaps (ex-reports):  19%|█▉        | 1368/7111 [05:11<19:42,  4.86it/s]

Gaps (ex-reports):  19%|█▉        | 1369/7111 [05:11<19:42,  4.86it/s]

Gaps (ex-reports):  19%|█▉        | 1370/7111 [05:11<19:23,  4.93it/s]

Gaps (ex-reports):  19%|█▉        | 1371/7111 [05:12<19:22,  4.94it/s]

Gaps (ex-reports):  19%|█▉        | 1372/7111 [05:12<19:08,  4.99it/s]

Gaps (ex-reports):  19%|█▉        | 1373/7111 [05:12<19:41,  4.86it/s]

Gaps (ex-reports):  19%|█▉        | 1374/7111 [05:12<19:51,  4.82it/s]

Gaps (ex-reports):  19%|█▉        | 1375/7111 [05:12<19:13,  4.97it/s]

Gaps (ex-reports):  19%|█▉        | 1376/7111 [05:13<19:20,  4.94it/s]

Gaps (ex-reports):  19%|█▉        | 1377/7111 [05:13<19:25,  4.92it/s]

Gaps (ex-reports):  19%|█▉        | 1378/7111 [05:13<19:23,  4.93it/s]

Gaps (ex-reports):  19%|█▉        | 1379/7111 [05:13<19:20,  4.94it/s]

Gaps (ex-reports):  19%|█▉        | 1380/7111 [05:13<19:26,  4.91it/s]

Gaps (ex-reports):  19%|█▉        | 1381/7111 [05:14<19:55,  4.79it/s]

Gaps (ex-reports):  19%|█▉        | 1382/7111 [05:14<20:08,  4.74it/s]

Gaps (ex-reports):  19%|█▉        | 1383/7111 [05:14<19:43,  4.84it/s]

Gaps (ex-reports):  19%|█▉        | 1384/7111 [05:14<19:41,  4.85it/s]

Gaps (ex-reports):  19%|█▉        | 1385/7111 [05:14<19:52,  4.80it/s]

Gaps (ex-reports):  19%|█▉        | 1386/7111 [05:15<20:04,  4.75it/s]

Gaps (ex-reports):  20%|█▉        | 1387/7111 [05:15<19:54,  4.79it/s]

Gaps (ex-reports):  20%|█▉        | 1388/7111 [05:15<20:06,  4.74it/s]

Gaps (ex-reports):  20%|█▉        | 1389/7111 [05:15<19:39,  4.85it/s]

Gaps (ex-reports):  20%|█▉        | 1390/7111 [05:15<20:01,  4.76it/s]

Gaps (ex-reports):  20%|█▉        | 1391/7111 [05:16<19:40,  4.84it/s]

Gaps (ex-reports):  20%|█▉        | 1392/7111 [05:16<19:46,  4.82it/s]

Gaps (ex-reports):  20%|█▉        | 1393/7111 [05:16<19:46,  4.82it/s]

Gaps (ex-reports):  20%|█▉        | 1394/7111 [05:16<20:01,  4.76it/s]

Gaps (ex-reports):  20%|█▉        | 1395/7111 [05:16<19:34,  4.87it/s]

Gaps (ex-reports):  20%|█▉        | 1396/7111 [05:17<19:13,  4.96it/s]

Gaps (ex-reports):  20%|█▉        | 1397/7111 [05:17<19:36,  4.86it/s]

Gaps (ex-reports):  20%|█▉        | 1398/7111 [05:17<19:27,  4.89it/s]

Gaps (ex-reports):  20%|█▉        | 1399/7111 [05:17<19:39,  4.84it/s]

Gaps (ex-reports):  20%|█▉        | 1400/7111 [05:18<19:58,  4.77it/s]

Gaps (ex-reports):  20%|█▉        | 1401/7111 [05:18<19:35,  4.86it/s]

Gaps (ex-reports):  20%|█▉        | 1402/7111 [05:18<19:51,  4.79it/s]

Gaps (ex-reports):  20%|█▉        | 1403/7111 [05:18<19:48,  4.80it/s]

Gaps (ex-reports):  20%|█▉        | 1404/7111 [05:18<21:25,  4.44it/s]

Gaps (ex-reports):  20%|█▉        | 1405/7111 [05:19<20:31,  4.63it/s]

Gaps (ex-reports):  20%|█▉        | 1406/7111 [05:19<37:15,  2.55it/s]

Gaps (ex-reports):  20%|█▉        | 1407/7111 [05:20<32:16,  2.95it/s]

Gaps (ex-reports):  20%|█▉        | 1408/7111 [05:20<28:57,  3.28it/s]

Gaps (ex-reports):  20%|█▉        | 1409/7111 [05:20<25:48,  3.68it/s]

Gaps (ex-reports):  20%|█▉        | 1410/7111 [05:20<24:04,  3.95it/s]

Gaps (ex-reports):  20%|█▉        | 1411/7111 [05:20<22:53,  4.15it/s]

Gaps (ex-reports):  20%|█▉        | 1412/7111 [05:21<21:54,  4.34it/s]

Gaps (ex-reports):  20%|█▉        | 1413/7111 [05:21<21:04,  4.51it/s]

Gaps (ex-reports):  20%|█▉        | 1414/7111 [05:21<20:52,  4.55it/s]

Gaps (ex-reports):  20%|█▉        | 1415/7111 [05:21<20:37,  4.60it/s]

Gaps (ex-reports):  20%|█▉        | 1416/7111 [05:22<20:28,  4.63it/s]

Gaps (ex-reports):  20%|█▉        | 1417/7111 [05:22<20:00,  4.74it/s]

Gaps (ex-reports):  20%|█▉        | 1418/7111 [05:22<20:19,  4.67it/s]

Gaps (ex-reports):  20%|█▉        | 1419/7111 [05:22<19:45,  4.80it/s]

Gaps (ex-reports):  20%|█▉        | 1420/7111 [05:22<19:45,  4.80it/s]

Gaps (ex-reports):  20%|█▉        | 1421/7111 [05:23<19:11,  4.94it/s]

Gaps (ex-reports):  20%|█▉        | 1422/7111 [05:23<19:20,  4.90it/s]

Gaps (ex-reports):  20%|██        | 1423/7111 [05:23<19:07,  4.96it/s]

Gaps (ex-reports):  20%|██        | 1424/7111 [05:23<19:36,  4.83it/s]

Gaps (ex-reports):  20%|██        | 1425/7111 [05:23<19:53,  4.76it/s]

Gaps (ex-reports):  20%|██        | 1426/7111 [05:24<19:49,  4.78it/s]

Gaps (ex-reports):  20%|██        | 1427/7111 [05:24<38:45,  2.44it/s]

Gaps (ex-reports):  20%|██        | 1428/7111 [05:25<33:21,  2.84it/s]

Gaps (ex-reports):  20%|██        | 1429/7111 [05:25<28:49,  3.28it/s]

Gaps (ex-reports):  20%|██        | 1430/7111 [05:25<26:20,  3.59it/s]

Gaps (ex-reports):  20%|██        | 1431/7111 [05:25<24:14,  3.91it/s]

Gaps (ex-reports):  20%|██        | 1432/7111 [05:25<22:32,  4.20it/s]

Gaps (ex-reports):  20%|██        | 1433/7111 [05:26<21:50,  4.33it/s]

Gaps (ex-reports):  20%|██        | 1434/7111 [05:26<21:00,  4.51it/s]

Gaps (ex-reports):  20%|██        | 1435/7111 [05:26<20:20,  4.65it/s]

Gaps (ex-reports):  20%|██        | 1436/7111 [05:26<19:46,  4.78it/s]

Gaps (ex-reports):  20%|██        | 1437/7111 [05:27<20:06,  4.70it/s]

Gaps (ex-reports):  20%|██        | 1438/7111 [05:27<24:15,  3.90it/s]

Gaps (ex-reports):  20%|██        | 1439/7111 [05:27<23:06,  4.09it/s]

Gaps (ex-reports):  20%|██        | 1440/7111 [05:27<21:53,  4.32it/s]

Gaps (ex-reports):  20%|██        | 1441/7111 [05:27<21:02,  4.49it/s]

Gaps (ex-reports):  20%|██        | 1442/7111 [05:28<20:53,  4.52it/s]

Gaps (ex-reports):  20%|██        | 1443/7111 [05:28<20:14,  4.67it/s]

Gaps (ex-reports):  20%|██        | 1444/7111 [05:28<20:01,  4.72it/s]

Gaps (ex-reports):  20%|██        | 1445/7111 [05:28<19:56,  4.74it/s]

Gaps (ex-reports):  20%|██        | 1446/7111 [05:29<19:50,  4.76it/s]

Gaps (ex-reports):  20%|██        | 1447/7111 [05:29<19:20,  4.88it/s]

Gaps (ex-reports):  20%|██        | 1448/7111 [05:29<19:41,  4.79it/s]

Gaps (ex-reports):  20%|██        | 1449/7111 [05:29<19:42,  4.79it/s]

Gaps (ex-reports):  20%|██        | 1450/7111 [05:29<19:28,  4.85it/s]

Gaps (ex-reports):  20%|██        | 1451/7111 [05:30<19:24,  4.86it/s]

Gaps (ex-reports):  20%|██        | 1452/7111 [05:30<18:56,  4.98it/s]

Gaps (ex-reports):  20%|██        | 1453/7111 [05:30<18:57,  4.97it/s]

Gaps (ex-reports):  20%|██        | 1454/7111 [05:30<19:20,  4.88it/s]

Gaps (ex-reports):  20%|██        | 1455/7111 [05:30<19:11,  4.91it/s]

Gaps (ex-reports):  20%|██        | 1456/7111 [05:31<19:39,  4.79it/s]

Gaps (ex-reports):  20%|██        | 1457/7111 [05:31<19:46,  4.76it/s]

Gaps (ex-reports):  21%|██        | 1458/7111 [05:31<19:28,  4.84it/s]

Gaps (ex-reports):  21%|██        | 1459/7111 [05:31<19:53,  4.74it/s]

Gaps (ex-reports):  21%|██        | 1460/7111 [05:31<19:29,  4.83it/s]

Gaps (ex-reports):  21%|██        | 1461/7111 [05:32<19:05,  4.93it/s]

Gaps (ex-reports):  21%|██        | 1462/7111 [05:32<18:57,  4.97it/s]

Gaps (ex-reports):  21%|██        | 1463/7111 [05:32<18:42,  5.03it/s]

Gaps (ex-reports):  21%|██        | 1464/7111 [05:32<18:46,  5.02it/s]

Gaps (ex-reports):  21%|██        | 1465/7111 [05:32<18:39,  5.05it/s]

Gaps (ex-reports):  21%|██        | 1466/7111 [05:33<18:22,  5.12it/s]

Gaps (ex-reports):  21%|██        | 1467/7111 [05:33<19:10,  4.91it/s]

Gaps (ex-reports):  21%|██        | 1468/7111 [05:33<19:15,  4.88it/s]

Gaps (ex-reports):  21%|██        | 1469/7111 [05:33<19:05,  4.93it/s]

Gaps (ex-reports):  21%|██        | 1470/7111 [05:33<19:12,  4.89it/s]

Gaps (ex-reports):  21%|██        | 1471/7111 [05:34<19:18,  4.87it/s]

Gaps (ex-reports):  21%|██        | 1472/7111 [05:34<19:06,  4.92it/s]

Gaps (ex-reports):  21%|██        | 1473/7111 [05:34<19:18,  4.87it/s]

Gaps (ex-reports):  21%|██        | 1474/7111 [05:34<19:30,  4.81it/s]

Gaps (ex-reports):  21%|██        | 1475/7111 [05:34<19:16,  4.87it/s]

Gaps (ex-reports):  21%|██        | 1476/7111 [05:35<19:17,  4.87it/s]

Gaps (ex-reports):  21%|██        | 1477/7111 [05:35<18:53,  4.97it/s]

Gaps (ex-reports):  21%|██        | 1478/7111 [05:35<18:41,  5.02it/s]

Gaps (ex-reports):  21%|██        | 1479/7111 [05:35<18:27,  5.09it/s]

Gaps (ex-reports):  21%|██        | 1480/7111 [05:35<18:24,  5.10it/s]

Gaps (ex-reports):  21%|██        | 1481/7111 [05:36<18:54,  4.96it/s]

Gaps (ex-reports):  21%|██        | 1482/7111 [05:36<18:51,  4.97it/s]

Gaps (ex-reports):  21%|██        | 1483/7111 [05:36<19:29,  4.81it/s]

Gaps (ex-reports):  21%|██        | 1484/7111 [05:36<19:17,  4.86it/s]

Gaps (ex-reports):  21%|██        | 1485/7111 [05:36<19:10,  4.89it/s]

Gaps (ex-reports):  21%|██        | 1486/7111 [05:37<19:09,  4.89it/s]

Gaps (ex-reports):  21%|██        | 1487/7111 [05:37<19:07,  4.90it/s]

Gaps (ex-reports):  21%|██        | 1488/7111 [05:37<22:37,  4.14it/s]

Gaps (ex-reports):  21%|██        | 1489/7111 [05:37<21:19,  4.40it/s]

Gaps (ex-reports):  21%|██        | 1490/7111 [05:38<20:31,  4.56it/s]

Gaps (ex-reports):  21%|██        | 1491/7111 [05:38<19:49,  4.72it/s]

Gaps (ex-reports):  21%|██        | 1492/7111 [05:38<19:28,  4.81it/s]

Gaps (ex-reports):  21%|██        | 1493/7111 [05:38<19:18,  4.85it/s]

Gaps (ex-reports):  21%|██        | 1494/7111 [05:38<19:11,  4.88it/s]

Gaps (ex-reports):  21%|██        | 1495/7111 [05:39<19:25,  4.82it/s]

Gaps (ex-reports):  21%|██        | 1496/7111 [05:39<19:30,  4.80it/s]

Gaps (ex-reports):  21%|██        | 1497/7111 [05:39<19:25,  4.82it/s]

Gaps (ex-reports):  21%|██        | 1498/7111 [05:39<22:14,  4.21it/s]

Gaps (ex-reports):  21%|██        | 1499/7111 [05:40<21:13,  4.41it/s]

Gaps (ex-reports):  21%|██        | 1500/7111 [05:40<20:20,  4.60it/s]

Gaps (ex-reports):  21%|██        | 1501/7111 [05:40<20:00,  4.67it/s]

Gaps (ex-reports):  21%|██        | 1502/7111 [05:40<19:39,  4.75it/s]

Gaps (ex-reports):  21%|██        | 1503/7111 [05:40<19:59,  4.67it/s]

Gaps (ex-reports):  21%|██        | 1504/7111 [05:41<19:29,  4.80it/s]

Gaps (ex-reports):  21%|██        | 1505/7111 [05:41<19:26,  4.80it/s]

Gaps (ex-reports):  21%|██        | 1506/7111 [05:41<19:28,  4.80it/s]

Gaps (ex-reports):  21%|██        | 1507/7111 [05:41<19:15,  4.85it/s]

Gaps (ex-reports):  21%|██        | 1508/7111 [05:41<19:01,  4.91it/s]

Gaps (ex-reports):  21%|██        | 1509/7111 [05:42<19:39,  4.75it/s]

Gaps (ex-reports):  21%|██        | 1510/7111 [05:42<19:22,  4.82it/s]

Gaps (ex-reports):  21%|██        | 1511/7111 [05:42<19:12,  4.86it/s]

Gaps (ex-reports):  21%|██▏       | 1512/7111 [05:42<19:01,  4.91it/s]

Gaps (ex-reports):  21%|██▏       | 1513/7111 [05:42<19:11,  4.86it/s]

Gaps (ex-reports):  21%|██▏       | 1514/7111 [05:43<19:41,  4.74it/s]

Gaps (ex-reports):  21%|██▏       | 1515/7111 [05:43<19:10,  4.87it/s]

Gaps (ex-reports):  21%|██▏       | 1516/7111 [05:43<18:57,  4.92it/s]

Gaps (ex-reports):  21%|██▏       | 1517/7111 [05:43<19:10,  4.86it/s]

Gaps (ex-reports):  21%|██▏       | 1518/7111 [05:43<18:58,  4.91it/s]

Gaps (ex-reports):  21%|██▏       | 1519/7111 [05:44<18:52,  4.94it/s]

Gaps (ex-reports):  21%|██▏       | 1520/7111 [05:44<18:36,  5.01it/s]

Gaps (ex-reports):  21%|██▏       | 1521/7111 [05:44<18:33,  5.02it/s]

Gaps (ex-reports):  21%|██▏       | 1522/7111 [05:44<18:20,  5.08it/s]

Gaps (ex-reports):  21%|██▏       | 1523/7111 [05:44<18:35,  5.01it/s]

Gaps (ex-reports):  21%|██▏       | 1524/7111 [05:45<18:43,  4.97it/s]

Gaps (ex-reports):  21%|██▏       | 1525/7111 [05:45<18:43,  4.97it/s]

Gaps (ex-reports):  21%|██▏       | 1526/7111 [05:45<18:30,  5.03it/s]

Gaps (ex-reports):  21%|██▏       | 1527/7111 [05:45<18:36,  5.00it/s]

Gaps (ex-reports):  21%|██▏       | 1528/7111 [05:45<18:30,  5.03it/s]

Gaps (ex-reports):  22%|██▏       | 1529/7111 [05:46<18:43,  4.97it/s]

Gaps (ex-reports):  22%|██▏       | 1530/7111 [05:46<18:27,  5.04it/s]

Gaps (ex-reports):  22%|██▏       | 1531/7111 [05:46<18:24,  5.05it/s]

Gaps (ex-reports):  22%|██▏       | 1532/7111 [05:46<18:33,  5.01it/s]

Gaps (ex-reports):  22%|██▏       | 1533/7111 [05:46<18:43,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1534/7111 [05:47<19:13,  4.83it/s]

Gaps (ex-reports):  22%|██▏       | 1535/7111 [05:47<18:51,  4.93it/s]

Gaps (ex-reports):  22%|██▏       | 1536/7111 [05:47<18:43,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1537/7111 [05:47<18:29,  5.02it/s]

Gaps (ex-reports):  22%|██▏       | 1538/7111 [05:47<18:40,  4.97it/s]

Gaps (ex-reports):  22%|██▏       | 1539/7111 [05:48<18:38,  4.98it/s]

Gaps (ex-reports):  22%|██▏       | 1540/7111 [05:48<18:46,  4.95it/s]

Gaps (ex-reports):  22%|██▏       | 1541/7111 [05:48<19:03,  4.87it/s]

Gaps (ex-reports):  22%|██▏       | 1542/7111 [05:48<18:58,  4.89it/s]

Gaps (ex-reports):  22%|██▏       | 1543/7111 [05:48<18:44,  4.95it/s]

Gaps (ex-reports):  22%|██▏       | 1544/7111 [05:49<18:56,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1545/7111 [05:49<18:46,  4.94it/s]

Gaps (ex-reports):  22%|██▏       | 1546/7111 [05:49<18:27,  5.02it/s]

Gaps (ex-reports):  22%|██▏       | 1547/7111 [05:49<18:54,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1548/7111 [05:49<18:45,  4.94it/s]

Gaps (ex-reports):  22%|██▏       | 1549/7111 [05:50<18:47,  4.93it/s]

Gaps (ex-reports):  22%|██▏       | 1550/7111 [05:50<19:06,  4.85it/s]

Gaps (ex-reports):  22%|██▏       | 1551/7111 [05:50<19:03,  4.86it/s]

Gaps (ex-reports):  22%|██▏       | 1552/7111 [05:50<18:53,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1553/7111 [05:50<18:59,  4.88it/s]

Gaps (ex-reports):  22%|██▏       | 1554/7111 [05:51<19:03,  4.86it/s]

Gaps (ex-reports):  22%|██▏       | 1555/7111 [05:51<19:01,  4.87it/s]

Gaps (ex-reports):  22%|██▏       | 1556/7111 [05:51<18:45,  4.94it/s]

Gaps (ex-reports):  22%|██▏       | 1557/7111 [05:51<18:34,  4.98it/s]

Gaps (ex-reports):  22%|██▏       | 1558/7111 [05:51<18:40,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1559/7111 [05:52<19:09,  4.83it/s]

Gaps (ex-reports):  22%|██▏       | 1560/7111 [05:52<19:22,  4.77it/s]

Gaps (ex-reports):  22%|██▏       | 1561/7111 [05:52<19:13,  4.81it/s]

Gaps (ex-reports):  22%|██▏       | 1562/7111 [05:52<18:52,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1563/7111 [05:53<18:53,  4.89it/s]

Gaps (ex-reports):  22%|██▏       | 1564/7111 [05:53<18:38,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1565/7111 [05:53<18:26,  5.01it/s]

Gaps (ex-reports):  22%|██▏       | 1566/7111 [05:53<18:32,  4.99it/s]

Gaps (ex-reports):  22%|██▏       | 1567/7111 [05:53<18:50,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1568/7111 [05:54<19:08,  4.83it/s]

Gaps (ex-reports):  22%|██▏       | 1569/7111 [05:54<18:59,  4.86it/s]

Gaps (ex-reports):  22%|██▏       | 1570/7111 [05:54<18:54,  4.88it/s]

Gaps (ex-reports):  22%|██▏       | 1571/7111 [05:54<18:36,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1572/7111 [05:54<18:39,  4.95it/s]

Gaps (ex-reports):  22%|██▏       | 1573/7111 [05:55<18:49,  4.90it/s]

Gaps (ex-reports):  22%|██▏       | 1574/7111 [05:55<18:38,  4.95it/s]

Gaps (ex-reports):  22%|██▏       | 1575/7111 [05:55<18:38,  4.95it/s]

Gaps (ex-reports):  22%|██▏       | 1576/7111 [05:55<18:30,  4.98it/s]

Gaps (ex-reports):  22%|██▏       | 1577/7111 [05:55<18:24,  5.01it/s]

Gaps (ex-reports):  22%|██▏       | 1578/7111 [05:56<18:22,  5.02it/s]

Gaps (ex-reports):  22%|██▏       | 1579/7111 [05:56<18:35,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1580/7111 [05:56<18:19,  5.03it/s]

Gaps (ex-reports):  22%|██▏       | 1581/7111 [05:56<18:22,  5.02it/s]

Gaps (ex-reports):  22%|██▏       | 1582/7111 [05:56<18:22,  5.01it/s]

Gaps (ex-reports):  22%|██▏       | 1583/7111 [05:57<18:08,  5.08it/s]

Gaps (ex-reports):  22%|██▏       | 1584/7111 [05:57<18:06,  5.09it/s]

Gaps (ex-reports):  22%|██▏       | 1585/7111 [05:57<18:19,  5.02it/s]

Gaps (ex-reports):  22%|██▏       | 1586/7111 [05:57<18:45,  4.91it/s]

Gaps (ex-reports):  22%|██▏       | 1587/7111 [05:57<19:07,  4.82it/s]

Gaps (ex-reports):  22%|██▏       | 1588/7111 [05:58<18:48,  4.89it/s]

Gaps (ex-reports):  22%|██▏       | 1589/7111 [05:58<19:04,  4.82it/s]

Gaps (ex-reports):  22%|██▏       | 1590/7111 [05:58<18:57,  4.85it/s]

Gaps (ex-reports):  22%|██▏       | 1591/7111 [05:58<18:36,  4.94it/s]

Gaps (ex-reports):  22%|██▏       | 1592/7111 [05:58<18:32,  4.96it/s]

Gaps (ex-reports):  22%|██▏       | 1593/7111 [05:59<18:34,  4.95it/s]

Gaps (ex-reports):  22%|██▏       | 1594/7111 [05:59<18:39,  4.93it/s]

Gaps (ex-reports):  22%|██▏       | 1595/7111 [05:59<18:49,  4.88it/s]

Gaps (ex-reports):  22%|██▏       | 1596/7111 [05:59<18:48,  4.89it/s]

Gaps (ex-reports):  22%|██▏       | 1597/7111 [05:59<18:48,  4.88it/s]

Gaps (ex-reports):  22%|██▏       | 1598/7111 [06:00<18:54,  4.86it/s]

Gaps (ex-reports):  22%|██▏       | 1599/7111 [06:00<19:13,  4.78it/s]

Gaps (ex-reports):  23%|██▎       | 1600/7111 [06:00<19:11,  4.79it/s]

Gaps (ex-reports):  23%|██▎       | 1601/7111 [06:00<19:03,  4.82it/s]

Gaps (ex-reports):  23%|██▎       | 1602/7111 [06:00<18:57,  4.84it/s]

Gaps (ex-reports):  23%|██▎       | 1603/7111 [06:01<18:40,  4.92it/s]

Gaps (ex-reports):  23%|██▎       | 1604/7111 [06:01<18:49,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1605/7111 [06:01<18:46,  4.89it/s]

Gaps (ex-reports):  23%|██▎       | 1606/7111 [06:01<18:25,  4.98it/s]

Gaps (ex-reports):  23%|██▎       | 1607/7111 [06:01<18:39,  4.92it/s]

Gaps (ex-reports):  23%|██▎       | 1608/7111 [06:02<18:27,  4.97it/s]

Gaps (ex-reports):  23%|██▎       | 1609/7111 [06:02<18:48,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1610/7111 [06:02<18:36,  4.93it/s]

Gaps (ex-reports):  23%|██▎       | 1611/7111 [06:02<18:50,  4.87it/s]

Gaps (ex-reports):  23%|██▎       | 1612/7111 [06:03<19:02,  4.81it/s]

Gaps (ex-reports):  23%|██▎       | 1613/7111 [06:03<18:46,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1614/7111 [06:03<18:28,  4.96it/s]

Gaps (ex-reports):  23%|██▎       | 1615/7111 [06:03<18:14,  5.02it/s]

Gaps (ex-reports):  23%|██▎       | 1616/7111 [06:03<18:29,  4.95it/s]

Gaps (ex-reports):  23%|██▎       | 1617/7111 [06:03<18:15,  5.02it/s]

Gaps (ex-reports):  23%|██▎       | 1618/7111 [06:04<18:42,  4.89it/s]

Gaps (ex-reports):  23%|██▎       | 1619/7111 [06:04<18:40,  4.90it/s]

Gaps (ex-reports):  23%|██▎       | 1620/7111 [06:04<20:24,  4.49it/s]

Gaps (ex-reports):  23%|██▎       | 1621/7111 [06:04<19:40,  4.65it/s]

Gaps (ex-reports):  23%|██▎       | 1622/7111 [06:05<19:26,  4.71it/s]

Gaps (ex-reports):  23%|██▎       | 1623/7111 [06:05<18:43,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1624/7111 [06:06<55:03,  1.66it/s]

Gaps (ex-reports):  23%|██▎       | 1625/7111 [06:07<44:16,  2.07it/s]

Gaps (ex-reports):  23%|██▎       | 1626/7111 [06:07<36:45,  2.49it/s]

Gaps (ex-reports):  23%|██▎       | 1627/7111 [06:07<31:32,  2.90it/s]

Gaps (ex-reports):  23%|██▎       | 1628/7111 [06:07<27:21,  3.34it/s]

Gaps (ex-reports):  23%|██▎       | 1629/7111 [06:07<25:05,  3.64it/s]

Gaps (ex-reports):  23%|██▎       | 1630/7111 [06:08<23:32,  3.88it/s]

Gaps (ex-reports):  23%|██▎       | 1631/7111 [06:08<21:43,  4.20it/s]

Gaps (ex-reports):  23%|██▎       | 1632/7111 [06:08<20:51,  4.38it/s]

Gaps (ex-reports):  23%|██▎       | 1633/7111 [06:08<20:07,  4.54it/s]

Gaps (ex-reports):  23%|██▎       | 1634/7111 [06:08<19:42,  4.63it/s]

Gaps (ex-reports):  23%|██▎       | 1635/7111 [06:09<19:05,  4.78it/s]

Gaps (ex-reports):  23%|██▎       | 1636/7111 [06:09<18:57,  4.81it/s]

Gaps (ex-reports):  23%|██▎       | 1637/7111 [06:09<18:41,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1638/7111 [06:09<18:44,  4.87it/s]

Gaps (ex-reports):  23%|██▎       | 1639/7111 [06:09<18:43,  4.87it/s]

Gaps (ex-reports):  23%|██▎       | 1640/7111 [06:10<18:31,  4.92it/s]

Gaps (ex-reports):  23%|██▎       | 1641/7111 [06:10<18:40,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1642/7111 [06:10<18:46,  4.85it/s]

Gaps (ex-reports):  23%|██▎       | 1643/7111 [06:10<18:43,  4.87it/s]

Gaps (ex-reports):  23%|██▎       | 1644/7111 [06:10<18:53,  4.82it/s]

Gaps (ex-reports):  23%|██▎       | 1645/7111 [06:11<18:53,  4.82it/s]

Gaps (ex-reports):  23%|██▎       | 1646/7111 [06:11<18:40,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1647/7111 [06:11<18:52,  4.83it/s]

Gaps (ex-reports):  23%|██▎       | 1648/7111 [06:11<19:02,  4.78it/s]

Gaps (ex-reports):  23%|██▎       | 1649/7111 [06:11<18:34,  4.90it/s]

Gaps (ex-reports):  23%|██▎       | 1650/7111 [06:12<18:44,  4.86it/s]

Gaps (ex-reports):  23%|██▎       | 1651/7111 [06:12<18:38,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1652/7111 [06:12<18:45,  4.85it/s]

Gaps (ex-reports):  23%|██▎       | 1653/7111 [06:12<18:47,  4.84it/s]

Gaps (ex-reports):  23%|██▎       | 1654/7111 [06:12<18:48,  4.83it/s]

Gaps (ex-reports):  23%|██▎       | 1655/7111 [06:13<18:26,  4.93it/s]

Gaps (ex-reports):  23%|██▎       | 1656/7111 [06:13<18:30,  4.91it/s]

Gaps (ex-reports):  23%|██▎       | 1657/7111 [06:13<18:32,  4.90it/s]

Gaps (ex-reports):  23%|██▎       | 1658/7111 [06:13<18:22,  4.95it/s]

Gaps (ex-reports):  23%|██▎       | 1659/7111 [06:13<18:27,  4.92it/s]

Gaps (ex-reports):  23%|██▎       | 1660/7111 [06:14<18:23,  4.94it/s]

Gaps (ex-reports):  23%|██▎       | 1661/7111 [06:14<18:20,  4.95it/s]

Gaps (ex-reports):  23%|██▎       | 1662/7111 [06:14<18:27,  4.92it/s]

Gaps (ex-reports):  23%|██▎       | 1663/7111 [06:14<18:14,  4.98it/s]

Gaps (ex-reports):  23%|██▎       | 1664/7111 [06:14<17:57,  5.06it/s]

Gaps (ex-reports):  23%|██▎       | 1665/7111 [06:15<18:11,  4.99it/s]

Gaps (ex-reports):  23%|██▎       | 1666/7111 [06:15<18:05,  5.01it/s]

Gaps (ex-reports):  23%|██▎       | 1667/7111 [06:15<18:30,  4.90it/s]

Gaps (ex-reports):  23%|██▎       | 1668/7111 [06:15<18:34,  4.88it/s]

Gaps (ex-reports):  23%|██▎       | 1669/7111 [06:15<18:31,  4.90it/s]

Gaps (ex-reports):  23%|██▎       | 1670/7111 [06:16<18:45,  4.84it/s]

Gaps (ex-reports):  23%|██▎       | 1671/7111 [06:16<19:08,  4.74it/s]

Gaps (ex-reports):  24%|██▎       | 1672/7111 [06:16<18:48,  4.82it/s]

Gaps (ex-reports):  24%|██▎       | 1673/7111 [06:16<19:08,  4.73it/s]

Gaps (ex-reports):  24%|██▎       | 1674/7111 [06:17<18:32,  4.89it/s]

Gaps (ex-reports):  24%|██▎       | 1675/7111 [06:17<18:43,  4.84it/s]

Gaps (ex-reports):  24%|██▎       | 1676/7111 [06:17<18:30,  4.90it/s]

Gaps (ex-reports):  24%|██▎       | 1677/7111 [06:17<18:26,  4.91it/s]

Gaps (ex-reports):  24%|██▎       | 1678/7111 [06:17<18:10,  4.98it/s]

Gaps (ex-reports):  24%|██▎       | 1679/7111 [06:18<17:59,  5.03it/s]

Gaps (ex-reports):  24%|██▎       | 1680/7111 [06:18<18:19,  4.94it/s]

Gaps (ex-reports):  24%|██▎       | 1681/7111 [06:18<18:21,  4.93it/s]

Gaps (ex-reports):  24%|██▎       | 1682/7111 [06:18<18:33,  4.87it/s]

Gaps (ex-reports):  24%|██▎       | 1683/7111 [06:18<18:08,  4.99it/s]

Gaps (ex-reports):  24%|██▎       | 1684/7111 [06:19<18:11,  4.97it/s]

Gaps (ex-reports):  24%|██▎       | 1685/7111 [06:19<18:01,  5.02it/s]

Gaps (ex-reports):  24%|██▎       | 1686/7111 [06:19<18:16,  4.95it/s]

Gaps (ex-reports):  24%|██▎       | 1687/7111 [06:19<18:31,  4.88it/s]

Gaps (ex-reports):  24%|██▎       | 1688/7111 [06:19<18:13,  4.96it/s]

Gaps (ex-reports):  24%|██▍       | 1689/7111 [06:20<17:56,  5.03it/s]

Gaps (ex-reports):  24%|██▍       | 1690/7111 [06:20<18:21,  4.92it/s]

Gaps (ex-reports):  24%|██▍       | 1691/7111 [06:20<18:37,  4.85it/s]

Gaps (ex-reports):  24%|██▍       | 1692/7111 [06:20<18:28,  4.89it/s]

Gaps (ex-reports):  24%|██▍       | 1693/7111 [06:21<22:14,  4.06it/s]

Gaps (ex-reports):  24%|██▍       | 1694/7111 [06:21<20:53,  4.32it/s]

Gaps (ex-reports):  24%|██▍       | 1695/7111 [06:21<20:29,  4.41it/s]

Gaps (ex-reports):  24%|██▍       | 1696/7111 [06:21<19:53,  4.54it/s]

Gaps (ex-reports):  24%|██▍       | 1697/7111 [06:21<19:14,  4.69it/s]

Gaps (ex-reports):  24%|██▍       | 1698/7111 [06:22<19:26,  4.64it/s]

Gaps (ex-reports):  24%|██▍       | 1699/7111 [06:22<19:06,  4.72it/s]

Gaps (ex-reports):  24%|██▍       | 1700/7111 [06:22<18:50,  4.79it/s]

Gaps (ex-reports):  24%|██▍       | 1701/7111 [06:22<19:01,  4.74it/s]

Gaps (ex-reports):  24%|██▍       | 1702/7111 [06:22<18:43,  4.82it/s]

Gaps (ex-reports):  24%|██▍       | 1703/7111 [06:23<18:25,  4.89it/s]

Gaps (ex-reports):  24%|██▍       | 1704/7111 [06:23<18:39,  4.83it/s]

Gaps (ex-reports):  24%|██▍       | 1705/7111 [06:23<18:16,  4.93it/s]

Gaps (ex-reports):  24%|██▍       | 1706/7111 [06:23<21:59,  4.10it/s]

Gaps (ex-reports):  24%|██▍       | 1707/7111 [06:24<21:05,  4.27it/s]

Gaps (ex-reports):  24%|██▍       | 1708/7111 [06:24<20:16,  4.44it/s]

Gaps (ex-reports):  24%|██▍       | 1709/7111 [06:24<34:05,  2.64it/s]

Gaps (ex-reports):  24%|██▍       | 1710/7111 [06:25<29:14,  3.08it/s]

Gaps (ex-reports):  24%|██▍       | 1711/7111 [06:25<25:50,  3.48it/s]

Gaps (ex-reports):  24%|██▍       | 1712/7111 [06:25<23:52,  3.77it/s]

Gaps (ex-reports):  24%|██▍       | 1713/7111 [06:25<22:11,  4.05it/s]

Gaps (ex-reports):  24%|██▍       | 1714/7111 [06:25<21:05,  4.26it/s]

Gaps (ex-reports):  24%|██▍       | 1715/7111 [06:26<20:22,  4.41it/s]

Gaps (ex-reports):  24%|██▍       | 1716/7111 [06:26<19:53,  4.52it/s]

Gaps (ex-reports):  24%|██▍       | 1717/7111 [06:26<19:48,  4.54it/s]

Gaps (ex-reports):  24%|██▍       | 1718/7111 [06:26<19:33,  4.60it/s]

Gaps (ex-reports):  24%|██▍       | 1719/7111 [06:27<19:08,  4.70it/s]

Gaps (ex-reports):  24%|██▍       | 1720/7111 [06:27<19:21,  4.64it/s]

Gaps (ex-reports):  24%|██▍       | 1721/7111 [06:27<19:34,  4.59it/s]

Gaps (ex-reports):  24%|██▍       | 1722/7111 [06:27<26:14,  3.42it/s]

Gaps (ex-reports):  24%|██▍       | 1723/7111 [06:28<23:51,  3.76it/s]

Gaps (ex-reports):  24%|██▍       | 1724/7111 [06:28<21:58,  4.09it/s]

Gaps (ex-reports):  24%|██▍       | 1725/7111 [06:28<21:00,  4.27it/s]

Gaps (ex-reports):  24%|██▍       | 1726/7111 [06:28<20:06,  4.46it/s]

Gaps (ex-reports):  24%|██▍       | 1727/7111 [06:28<19:31,  4.60it/s]

Gaps (ex-reports):  24%|██▍       | 1728/7111 [06:29<19:22,  4.63it/s]

Gaps (ex-reports):  24%|██▍       | 1729/7111 [06:29<19:12,  4.67it/s]

Gaps (ex-reports):  24%|██▍       | 1730/7111 [06:29<18:54,  4.74it/s]

Gaps (ex-reports):  24%|██▍       | 1731/7111 [06:29<18:54,  4.74it/s]

Gaps (ex-reports):  24%|██▍       | 1732/7111 [06:30<18:40,  4.80it/s]

Gaps (ex-reports):  24%|██▍       | 1733/7111 [06:30<18:53,  4.74it/s]

Gaps (ex-reports):  24%|██▍       | 1734/7111 [06:30<18:40,  4.80it/s]

Gaps (ex-reports):  24%|██▍       | 1735/7111 [06:30<18:45,  4.78it/s]

Gaps (ex-reports):  24%|██▍       | 1736/7111 [06:30<18:24,  4.86it/s]

Gaps (ex-reports):  24%|██▍       | 1737/7111 [06:31<18:35,  4.82it/s]

Gaps (ex-reports):  24%|██▍       | 1738/7111 [06:31<18:45,  4.77it/s]

Gaps (ex-reports):  24%|██▍       | 1739/7111 [06:31<18:59,  4.71it/s]

Gaps (ex-reports):  24%|██▍       | 1740/7111 [06:31<18:39,  4.80it/s]

Gaps (ex-reports):  24%|██▍       | 1741/7111 [06:31<18:41,  4.79it/s]

Gaps (ex-reports):  24%|██▍       | 1742/7111 [06:32<18:18,  4.89it/s]

Gaps (ex-reports):  25%|██▍       | 1743/7111 [06:32<19:59,  4.48it/s]

Gaps (ex-reports):  25%|██▍       | 1744/7111 [06:32<19:25,  4.61it/s]

Gaps (ex-reports):  25%|██▍       | 1745/7111 [06:32<19:08,  4.67it/s]

Gaps (ex-reports):  25%|██▍       | 1746/7111 [06:32<18:51,  4.74it/s]

Gaps (ex-reports):  25%|██▍       | 1747/7111 [06:33<18:52,  4.74it/s]

Gaps (ex-reports):  25%|██▍       | 1748/7111 [06:33<18:34,  4.81it/s]

Gaps (ex-reports):  25%|██▍       | 1749/7111 [06:33<18:17,  4.89it/s]

Gaps (ex-reports):  25%|██▍       | 1750/7111 [06:33<18:23,  4.86it/s]

Gaps (ex-reports):  25%|██▍       | 1751/7111 [06:34<30:48,  2.90it/s]

Gaps (ex-reports):  25%|██▍       | 1752/7111 [06:34<27:25,  3.26it/s]

Gaps (ex-reports):  25%|██▍       | 1753/7111 [06:34<24:46,  3.60it/s]

Gaps (ex-reports):  25%|██▍       | 1754/7111 [06:35<31:11,  2.86it/s]

Gaps (ex-reports):  25%|██▍       | 1755/7111 [06:35<27:24,  3.26it/s]

Gaps (ex-reports):  25%|██▍       | 1756/7111 [06:35<24:40,  3.62it/s]

Gaps (ex-reports):  25%|██▍       | 1757/7111 [06:36<22:48,  3.91it/s]

Gaps (ex-reports):  25%|██▍       | 1758/7111 [06:36<21:32,  4.14it/s]

Gaps (ex-reports):  25%|██▍       | 1759/7111 [06:36<20:38,  4.32it/s]

Gaps (ex-reports):  25%|██▍       | 1760/7111 [06:36<20:23,  4.37it/s]

Gaps (ex-reports):  25%|██▍       | 1761/7111 [06:36<19:27,  4.58it/s]

Gaps (ex-reports):  25%|██▍       | 1762/7111 [06:37<19:15,  4.63it/s]

Gaps (ex-reports):  25%|██▍       | 1763/7111 [06:37<19:17,  4.62it/s]

Gaps (ex-reports):  25%|██▍       | 1764/7111 [06:37<18:41,  4.77it/s]

Gaps (ex-reports):  25%|██▍       | 1765/7111 [06:37<18:15,  4.88it/s]

Gaps (ex-reports):  25%|██▍       | 1766/7111 [06:37<17:53,  4.98it/s]

Gaps (ex-reports):  25%|██▍       | 1767/7111 [06:38<18:04,  4.93it/s]

Gaps (ex-reports):  25%|██▍       | 1768/7111 [06:38<17:54,  4.97it/s]

Gaps (ex-reports):  25%|██▍       | 1769/7111 [06:38<17:57,  4.96it/s]

Gaps (ex-reports):  25%|██▍       | 1770/7111 [06:38<18:05,  4.92it/s]

Gaps (ex-reports):  25%|██▍       | 1771/7111 [06:38<18:34,  4.79it/s]

Gaps (ex-reports):  25%|██▍       | 1772/7111 [06:39<18:10,  4.90it/s]

Gaps (ex-reports):  25%|██▍       | 1773/7111 [06:39<18:16,  4.87it/s]

Gaps (ex-reports):  25%|██▍       | 1774/7111 [06:40<35:57,  2.47it/s]

Gaps (ex-reports):  25%|██▍       | 1775/7111 [06:40<30:38,  2.90it/s]

Gaps (ex-reports):  25%|██▍       | 1776/7111 [06:40<27:03,  3.29it/s]

Gaps (ex-reports):  25%|██▍       | 1777/7111 [06:40<24:39,  3.61it/s]

Gaps (ex-reports):  25%|██▌       | 1778/7111 [06:40<22:43,  3.91it/s]

Gaps (ex-reports):  25%|██▌       | 1779/7111 [06:41<21:14,  4.18it/s]

Gaps (ex-reports):  25%|██▌       | 1780/7111 [06:41<20:49,  4.27it/s]

Gaps (ex-reports):  25%|██▌       | 1781/7111 [06:41<20:33,  4.32it/s]

Gaps (ex-reports):  25%|██▌       | 1782/7111 [06:41<19:39,  4.52it/s]

Gaps (ex-reports):  25%|██▌       | 1783/7111 [06:42<19:18,  4.60it/s]

Gaps (ex-reports):  25%|██▌       | 1784/7111 [06:42<18:34,  4.78it/s]

Gaps (ex-reports):  25%|██▌       | 1785/7111 [06:42<18:20,  4.84it/s]

Gaps (ex-reports):  25%|██▌       | 1786/7111 [06:42<18:38,  4.76it/s]

Gaps (ex-reports):  25%|██▌       | 1787/7111 [06:42<18:14,  4.86it/s]

Gaps (ex-reports):  25%|██▌       | 1788/7111 [06:43<18:12,  4.87it/s]

Gaps (ex-reports):  25%|██▌       | 1789/7111 [06:43<18:22,  4.83it/s]

Gaps (ex-reports):  25%|██▌       | 1790/7111 [06:43<18:21,  4.83it/s]

Gaps (ex-reports):  25%|██▌       | 1791/7111 [06:43<18:27,  4.80it/s]

Gaps (ex-reports):  25%|██▌       | 1792/7111 [06:43<18:15,  4.86it/s]

Gaps (ex-reports):  25%|██▌       | 1793/7111 [06:44<17:54,  4.95it/s]

Gaps (ex-reports):  25%|██▌       | 1794/7111 [06:44<18:14,  4.86it/s]

Gaps (ex-reports):  25%|██▌       | 1795/7111 [06:44<18:10,  4.88it/s]

Gaps (ex-reports):  25%|██▌       | 1796/7111 [06:44<18:18,  4.84it/s]

Gaps (ex-reports):  25%|██▌       | 1797/7111 [06:44<18:20,  4.83it/s]

Gaps (ex-reports):  25%|██▌       | 1798/7111 [06:45<18:01,  4.91it/s]

Gaps (ex-reports):  25%|██▌       | 1799/7111 [06:45<18:15,  4.85it/s]

Gaps (ex-reports):  25%|██▌       | 1800/7111 [06:45<17:56,  4.94it/s]

Gaps (ex-reports):  25%|██▌       | 1801/7111 [06:45<17:56,  4.93it/s]

Gaps (ex-reports):  25%|██▌       | 1802/7111 [06:45<17:49,  4.96it/s]

Gaps (ex-reports):  25%|██▌       | 1803/7111 [06:46<18:25,  4.80it/s]

Gaps (ex-reports):  25%|██▌       | 1804/7111 [06:46<17:55,  4.93it/s]

Gaps (ex-reports):  25%|██▌       | 1805/7111 [06:46<17:47,  4.97it/s]

Gaps (ex-reports):  25%|██▌       | 1806/7111 [06:46<18:02,  4.90it/s]

Gaps (ex-reports):  25%|██▌       | 1807/7111 [06:46<18:14,  4.85it/s]

Gaps (ex-reports):  25%|██▌       | 1808/7111 [06:47<18:10,  4.86it/s]

Gaps (ex-reports):  25%|██▌       | 1809/7111 [06:47<18:07,  4.88it/s]

Gaps (ex-reports):  25%|██▌       | 1810/7111 [06:47<18:09,  4.86it/s]

Gaps (ex-reports):  25%|██▌       | 1811/7111 [06:47<17:51,  4.95it/s]

Gaps (ex-reports):  25%|██▌       | 1812/7111 [06:47<17:38,  5.00it/s]

Gaps (ex-reports):  25%|██▌       | 1813/7111 [06:48<17:43,  4.98it/s]

Gaps (ex-reports):  26%|██▌       | 1814/7111 [06:48<17:41,  4.99it/s]

Gaps (ex-reports):  26%|██▌       | 1815/7111 [06:48<17:44,  4.97it/s]

Gaps (ex-reports):  26%|██▌       | 1816/7111 [06:48<17:32,  5.03it/s]

Gaps (ex-reports):  26%|██▌       | 1817/7111 [06:48<17:48,  4.95it/s]

Gaps (ex-reports):  26%|██▌       | 1818/7111 [06:49<17:54,  4.93it/s]

Gaps (ex-reports):  26%|██▌       | 1819/7111 [06:49<19:46,  4.46it/s]

Gaps (ex-reports):  26%|██▌       | 1820/7111 [06:49<19:45,  4.46it/s]

Gaps (ex-reports):  26%|██▌       | 1821/7111 [06:49<19:00,  4.64it/s]

Gaps (ex-reports):  26%|██▌       | 1822/7111 [06:50<18:25,  4.78it/s]

Gaps (ex-reports):  26%|██▌       | 1823/7111 [06:50<18:20,  4.81it/s]

Gaps (ex-reports):  26%|██▌       | 1824/7111 [06:50<17:56,  4.91it/s]

Gaps (ex-reports):  26%|██▌       | 1825/7111 [06:50<17:58,  4.90it/s]

Gaps (ex-reports):  26%|██▌       | 1826/7111 [06:50<18:13,  4.83it/s]

Gaps (ex-reports):  26%|██▌       | 1827/7111 [06:51<18:03,  4.88it/s]

Gaps (ex-reports):  26%|██▌       | 1828/7111 [06:51<18:29,  4.76it/s]

Gaps (ex-reports):  26%|██▌       | 1829/7111 [06:51<18:37,  4.73it/s]

Gaps (ex-reports):  26%|██▌       | 1830/7111 [06:51<18:27,  4.77it/s]

Gaps (ex-reports):  26%|██▌       | 1831/7111 [06:51<18:09,  4.85it/s]

Gaps (ex-reports):  26%|██▌       | 1832/7111 [06:52<18:40,  4.71it/s]

Gaps (ex-reports):  26%|██▌       | 1833/7111 [06:52<18:13,  4.83it/s]

Gaps (ex-reports):  26%|██▌       | 1834/7111 [06:52<18:00,  4.88it/s]

Gaps (ex-reports):  26%|██▌       | 1835/7111 [06:52<18:24,  4.78it/s]

Gaps (ex-reports):  26%|██▌       | 1836/7111 [06:52<18:24,  4.78it/s]

Gaps (ex-reports):  26%|██▌       | 1837/7111 [06:53<18:18,  4.80it/s]

Gaps (ex-reports):  26%|██▌       | 1838/7111 [06:53<18:30,  4.75it/s]

Gaps (ex-reports):  26%|██▌       | 1839/7111 [06:53<18:44,  4.69it/s]

Gaps (ex-reports):  26%|██▌       | 1840/7111 [06:53<18:28,  4.75it/s]

Gaps (ex-reports):  26%|██▌       | 1841/7111 [06:54<18:41,  4.70it/s]

Gaps (ex-reports):  26%|██▌       | 1842/7111 [06:54<18:21,  4.78it/s]

Gaps (ex-reports):  26%|██▌       | 1843/7111 [06:54<18:10,  4.83it/s]

Gaps (ex-reports):  26%|██▌       | 1844/7111 [06:54<17:59,  4.88it/s]

Gaps (ex-reports):  26%|██▌       | 1845/7111 [06:54<17:32,  5.00it/s]

Gaps (ex-reports):  26%|██▌       | 1846/7111 [06:55<17:37,  4.98it/s]

Gaps (ex-reports):  26%|██▌       | 1847/7111 [06:55<17:52,  4.91it/s]

Gaps (ex-reports):  26%|██▌       | 1848/7111 [06:55<21:44,  4.03it/s]

Gaps (ex-reports):  26%|██▌       | 1849/7111 [06:55<20:19,  4.31it/s]

Gaps (ex-reports):  26%|██▌       | 1850/7111 [06:55<19:37,  4.47it/s]

Gaps (ex-reports):  26%|██▌       | 1851/7111 [06:56<19:12,  4.56it/s]

Gaps (ex-reports):  26%|██▌       | 1852/7111 [06:56<18:32,  4.73it/s]

Gaps (ex-reports):  26%|██▌       | 1853/7111 [06:56<18:08,  4.83it/s]

Gaps (ex-reports):  26%|██▌       | 1854/7111 [06:56<17:58,  4.87it/s]

Gaps (ex-reports):  26%|██▌       | 1855/7111 [06:56<17:34,  4.98it/s]

Gaps (ex-reports):  26%|██▌       | 1856/7111 [06:57<17:38,  4.97it/s]

Gaps (ex-reports):  26%|██▌       | 1857/7111 [06:57<18:00,  4.86it/s]

Gaps (ex-reports):  26%|██▌       | 1858/7111 [06:57<17:45,  4.93it/s]

Gaps (ex-reports):  26%|██▌       | 1859/7111 [06:57<17:51,  4.90it/s]

Gaps (ex-reports):  26%|██▌       | 1860/7111 [06:58<17:56,  4.88it/s]

Gaps (ex-reports):  26%|██▌       | 1861/7111 [06:58<17:49,  4.91it/s]

Gaps (ex-reports):  26%|██▌       | 1862/7111 [06:58<17:45,  4.93it/s]

Gaps (ex-reports):  26%|██▌       | 1863/7111 [06:58<18:01,  4.85it/s]

Gaps (ex-reports):  26%|██▌       | 1864/7111 [06:58<18:03,  4.84it/s]

Gaps (ex-reports):  26%|██▌       | 1865/7111 [06:59<18:12,  4.80it/s]

Gaps (ex-reports):  26%|██▌       | 1866/7111 [06:59<18:04,  4.84it/s]

Gaps (ex-reports):  26%|██▋       | 1867/7111 [06:59<17:59,  4.86it/s]

Gaps (ex-reports):  26%|██▋       | 1868/7111 [06:59<17:53,  4.88it/s]

Gaps (ex-reports):  26%|██▋       | 1869/7111 [06:59<17:31,  4.99it/s]

Gaps (ex-reports):  26%|██▋       | 1870/7111 [07:00<17:22,  5.03it/s]

Gaps (ex-reports):  26%|██▋       | 1871/7111 [07:00<17:19,  5.04it/s]

Gaps (ex-reports):  26%|██▋       | 1872/7111 [07:00<17:29,  4.99it/s]

Gaps (ex-reports):  26%|██▋       | 1873/7111 [07:00<17:18,  5.04it/s]

Gaps (ex-reports):  26%|██▋       | 1874/7111 [07:00<17:27,  5.00it/s]

Gaps (ex-reports):  26%|██▋       | 1875/7111 [07:01<17:43,  4.92it/s]

Gaps (ex-reports):  26%|██▋       | 1876/7111 [07:01<17:41,  4.93it/s]

Gaps (ex-reports):  26%|██▋       | 1877/7111 [07:01<17:35,  4.96it/s]

Gaps (ex-reports):  26%|██▋       | 1878/7111 [07:01<19:30,  4.47it/s]

Gaps (ex-reports):  26%|██▋       | 1879/7111 [07:01<19:00,  4.59it/s]

Gaps (ex-reports):  26%|██▋       | 1880/7111 [07:02<19:03,  4.58it/s]

Gaps (ex-reports):  26%|██▋       | 1881/7111 [07:02<18:52,  4.62it/s]

Gaps (ex-reports):  26%|██▋       | 1882/7111 [07:02<18:36,  4.68it/s]

Gaps (ex-reports):  26%|██▋       | 1883/7111 [07:02<18:25,  4.73it/s]

Gaps (ex-reports):  26%|██▋       | 1884/7111 [07:02<17:59,  4.84it/s]

Gaps (ex-reports):  27%|██▋       | 1885/7111 [07:03<17:54,  4.86it/s]

Gaps (ex-reports):  27%|██▋       | 1886/7111 [07:03<17:42,  4.92it/s]

Gaps (ex-reports):  27%|██▋       | 1887/7111 [07:04<34:00,  2.56it/s]

Gaps (ex-reports):  27%|██▋       | 1888/7111 [07:04<29:24,  2.96it/s]

Gaps (ex-reports):  27%|██▋       | 1889/7111 [07:04<25:46,  3.38it/s]

Gaps (ex-reports):  27%|██▋       | 1890/7111 [07:04<23:14,  3.74it/s]

Gaps (ex-reports):  27%|██▋       | 1891/7111 [07:05<21:48,  3.99it/s]

Gaps (ex-reports):  27%|██▋       | 1892/7111 [07:05<21:19,  4.08it/s]

Gaps (ex-reports):  27%|██▋       | 1893/7111 [07:05<20:15,  4.29it/s]

Gaps (ex-reports):  27%|██▋       | 1894/7111 [07:05<19:10,  4.53it/s]

Gaps (ex-reports):  27%|██▋       | 1895/7111 [07:05<18:36,  4.67it/s]

Gaps (ex-reports):  27%|██▋       | 1896/7111 [07:06<18:19,  4.74it/s]

Gaps (ex-reports):  27%|██▋       | 1897/7111 [07:06<18:14,  4.76it/s]

Gaps (ex-reports):  27%|██▋       | 1898/7111 [07:06<18:12,  4.77it/s]

Gaps (ex-reports):  27%|██▋       | 1899/7111 [07:06<18:25,  4.72it/s]

Gaps (ex-reports):  27%|██▋       | 1900/7111 [07:06<17:58,  4.83it/s]

Gaps (ex-reports):  27%|██▋       | 1901/7111 [07:07<17:43,  4.90it/s]

Gaps (ex-reports):  27%|██▋       | 1902/7111 [07:07<17:38,  4.92it/s]

Gaps (ex-reports):  27%|██▋       | 1903/7111 [07:07<17:34,  4.94it/s]

Gaps (ex-reports):  27%|██▋       | 1904/7111 [07:07<17:40,  4.91it/s]

Gaps (ex-reports):  27%|██▋       | 1905/7111 [07:07<17:37,  4.92it/s]

Gaps (ex-reports):  27%|██▋       | 1906/7111 [07:08<17:24,  4.98it/s]

Gaps (ex-reports):  27%|██▋       | 1907/7111 [07:08<17:43,  4.89it/s]

Gaps (ex-reports):  27%|██▋       | 1908/7111 [07:08<17:43,  4.89it/s]

Gaps (ex-reports):  27%|██▋       | 1909/7111 [07:08<17:57,  4.83it/s]

Gaps (ex-reports):  27%|██▋       | 1910/7111 [07:08<18:01,  4.81it/s]

Gaps (ex-reports):  27%|██▋       | 1911/7111 [07:09<18:14,  4.75it/s]

Gaps (ex-reports):  27%|██▋       | 1912/7111 [07:09<18:35,  4.66it/s]

Gaps (ex-reports):  27%|██▋       | 1913/7111 [07:09<18:19,  4.73it/s]

Gaps (ex-reports):  27%|██▋       | 1914/7111 [07:09<17:51,  4.85it/s]

Gaps (ex-reports):  27%|██▋       | 1915/7111 [07:09<18:15,  4.74it/s]

Gaps (ex-reports):  27%|██▋       | 1916/7111 [07:10<17:57,  4.82it/s]

Gaps (ex-reports):  27%|██▋       | 1917/7111 [07:10<18:15,  4.74it/s]

Gaps (ex-reports):  27%|██▋       | 1918/7111 [07:10<18:09,  4.76it/s]

Gaps (ex-reports):  27%|██▋       | 1919/7111 [07:10<18:09,  4.77it/s]

Gaps (ex-reports):  27%|██▋       | 1920/7111 [07:11<18:03,  4.79it/s]

Gaps (ex-reports):  27%|██▋       | 1921/7111 [07:11<18:01,  4.80it/s]

Gaps (ex-reports):  27%|██▋       | 1922/7111 [07:11<18:22,  4.71it/s]

Gaps (ex-reports):  27%|██▋       | 1923/7111 [07:11<18:04,  4.78it/s]

Gaps (ex-reports):  27%|██▋       | 1924/7111 [07:11<18:06,  4.77it/s]

Gaps (ex-reports):  27%|██▋       | 1925/7111 [07:12<19:06,  4.52it/s]

Gaps (ex-reports):  27%|██▋       | 1926/7111 [07:12<18:53,  4.57it/s]

Gaps (ex-reports):  27%|██▋       | 1927/7111 [07:12<18:25,  4.69it/s]

Gaps (ex-reports):  27%|██▋       | 1928/7111 [07:12<17:57,  4.81it/s]

Gaps (ex-reports):  27%|██▋       | 1929/7111 [07:12<17:58,  4.81it/s]

Gaps (ex-reports):  27%|██▋       | 1930/7111 [07:13<18:14,  4.74it/s]

Gaps (ex-reports):  27%|██▋       | 1931/7111 [07:13<17:50,  4.84it/s]

Gaps (ex-reports):  27%|██▋       | 1932/7111 [07:13<17:25,  4.95it/s]

Gaps (ex-reports):  27%|██▋       | 1933/7111 [07:13<17:29,  4.93it/s]

Gaps (ex-reports):  27%|██▋       | 1934/7111 [07:13<17:19,  4.98it/s]

Gaps (ex-reports):  27%|██▋       | 1935/7111 [07:14<17:46,  4.85it/s]

Gaps (ex-reports):  27%|██▋       | 1936/7111 [07:14<17:53,  4.82it/s]

Gaps (ex-reports):  27%|██▋       | 1937/7111 [07:14<17:40,  4.88it/s]

Gaps (ex-reports):  27%|██▋       | 1938/7111 [07:14<17:37,  4.89it/s]

Gaps (ex-reports):  27%|██▋       | 1939/7111 [07:14<17:46,  4.85it/s]

Gaps (ex-reports):  27%|██▋       | 1940/7111 [07:15<17:41,  4.87it/s]

Gaps (ex-reports):  27%|██▋       | 1941/7111 [07:15<17:20,  4.97it/s]

Gaps (ex-reports):  27%|██▋       | 1942/7111 [07:15<17:04,  5.04it/s]

Gaps (ex-reports):  27%|██▋       | 1943/7111 [07:15<16:59,  5.07it/s]

Gaps (ex-reports):  27%|██▋       | 1944/7111 [07:15<17:11,  5.01it/s]

Gaps (ex-reports):  27%|██▋       | 1945/7111 [07:16<17:25,  4.94it/s]

Gaps (ex-reports):  27%|██▋       | 1946/7111 [07:16<17:35,  4.89it/s]

Gaps (ex-reports):  27%|██▋       | 1947/7111 [07:16<17:46,  4.84it/s]

Gaps (ex-reports):  27%|██▋       | 1948/7111 [07:16<17:47,  4.84it/s]

Gaps (ex-reports):  27%|██▋       | 1949/7111 [07:17<17:42,  4.86it/s]

Gaps (ex-reports):  27%|██▋       | 1950/7111 [07:17<17:19,  4.97it/s]

Gaps (ex-reports):  27%|██▋       | 1951/7111 [07:17<17:10,  5.01it/s]

Gaps (ex-reports):  27%|██▋       | 1952/7111 [07:17<16:59,  5.06it/s]

Gaps (ex-reports):  27%|██▋       | 1953/7111 [07:17<17:05,  5.03it/s]

Gaps (ex-reports):  27%|██▋       | 1954/7111 [07:18<17:41,  4.86it/s]

Gaps (ex-reports):  27%|██▋       | 1955/7111 [07:18<17:31,  4.90it/s]

Gaps (ex-reports):  28%|██▊       | 1956/7111 [07:18<17:46,  4.83it/s]

Gaps (ex-reports):  28%|██▊       | 1957/7111 [07:18<17:34,  4.89it/s]

Gaps (ex-reports):  28%|██▊       | 1958/7111 [07:18<17:15,  4.98it/s]

Gaps (ex-reports):  28%|██▊       | 1959/7111 [07:19<17:16,  4.97it/s]

Gaps (ex-reports):  28%|██▊       | 1960/7111 [07:19<17:22,  4.94it/s]

Gaps (ex-reports):  28%|██▊       | 1961/7111 [07:19<17:17,  4.97it/s]

Gaps (ex-reports):  28%|██▊       | 1962/7111 [07:19<17:24,  4.93it/s]

Gaps (ex-reports):  28%|██▊       | 1963/7111 [07:19<17:14,  4.98it/s]

Gaps (ex-reports):  28%|██▊       | 1964/7111 [07:20<17:13,  4.98it/s]

Gaps (ex-reports):  28%|██▊       | 1965/7111 [07:20<17:20,  4.94it/s]

Gaps (ex-reports):  28%|██▊       | 1966/7111 [07:20<18:00,  4.76it/s]

Gaps (ex-reports):  28%|██▊       | 1967/7111 [07:20<17:49,  4.81it/s]

Gaps (ex-reports):  28%|██▊       | 1968/7111 [07:20<17:51,  4.80it/s]

Gaps (ex-reports):  28%|██▊       | 1969/7111 [07:21<17:35,  4.87it/s]

Gaps (ex-reports):  28%|██▊       | 1970/7111 [07:21<17:20,  4.94it/s]

Gaps (ex-reports):  28%|██▊       | 1971/7111 [07:21<17:31,  4.89it/s]

Gaps (ex-reports):  28%|██▊       | 1972/7111 [07:21<17:05,  5.01it/s]

Gaps (ex-reports):  28%|██▊       | 1973/7111 [07:21<16:55,  5.06it/s]

Gaps (ex-reports):  28%|██▊       | 1974/7111 [07:22<17:23,  4.92it/s]

Gaps (ex-reports):  28%|██▊       | 1975/7111 [07:22<17:25,  4.91it/s]

Gaps (ex-reports):  28%|██▊       | 1976/7111 [07:22<17:28,  4.90it/s]

Gaps (ex-reports):  28%|██▊       | 1977/7111 [07:22<17:06,  5.00it/s]

Gaps (ex-reports):  28%|██▊       | 1978/7111 [07:22<17:12,  4.97it/s]

Gaps (ex-reports):  28%|██▊       | 1979/7111 [07:23<24:50,  3.44it/s]

Gaps (ex-reports):  28%|██▊       | 1980/7111 [07:23<22:28,  3.81it/s]

Gaps (ex-reports):  28%|██▊       | 1981/7111 [07:23<21:10,  4.04it/s]

Gaps (ex-reports):  28%|██▊       | 1982/7111 [07:23<20:01,  4.27it/s]

Gaps (ex-reports):  28%|██▊       | 1983/7111 [07:24<19:14,  4.44it/s]

Gaps (ex-reports):  28%|██▊       | 1984/7111 [07:24<18:58,  4.50it/s]

Gaps (ex-reports):  28%|██▊       | 1985/7111 [07:24<18:31,  4.61it/s]

Gaps (ex-reports):  28%|██▊       | 1986/7111 [07:24<18:45,  4.55it/s]

Gaps (ex-reports):  28%|██▊       | 1987/7111 [07:25<19:23,  4.41it/s]

Gaps (ex-reports):  28%|██▊       | 1988/7111 [07:25<18:38,  4.58it/s]

Gaps (ex-reports):  28%|██▊       | 1989/7111 [07:25<18:14,  4.68it/s]

Gaps (ex-reports):  28%|██▊       | 1990/7111 [07:25<18:05,  4.72it/s]

Gaps (ex-reports):  28%|██▊       | 1991/7111 [07:25<17:55,  4.76it/s]

Gaps (ex-reports):  28%|██▊       | 1992/7111 [07:26<17:51,  4.78it/s]

Gaps (ex-reports):  28%|██▊       | 1993/7111 [07:26<17:48,  4.79it/s]

Gaps (ex-reports):  28%|██▊       | 1994/7111 [07:26<18:00,  4.73it/s]

Gaps (ex-reports):  28%|██▊       | 1995/7111 [07:26<17:48,  4.79it/s]

Gaps (ex-reports):  28%|██▊       | 1996/7111 [07:26<17:40,  4.82it/s]

Gaps (ex-reports):  28%|██▊       | 1997/7111 [07:27<17:57,  4.75it/s]

Gaps (ex-reports):  28%|██▊       | 1998/7111 [07:27<17:43,  4.81it/s]

Gaps (ex-reports):  28%|██▊       | 1999/7111 [07:27<17:46,  4.79it/s]

Gaps (ex-reports):  28%|██▊       | 2000/7111 [07:27<18:00,  4.73it/s]

Gaps (ex-reports):  28%|██▊       | 2001/7111 [07:27<18:01,  4.72it/s]

Gaps (ex-reports):  28%|██▊       | 2002/7111 [07:28<18:00,  4.73it/s]

Gaps (ex-reports):  28%|██▊       | 2003/7111 [07:28<17:46,  4.79it/s]

Gaps (ex-reports):  28%|██▊       | 2004/7111 [07:28<17:23,  4.89it/s]

Gaps (ex-reports):  28%|██▊       | 2005/7111 [07:28<17:03,  4.99it/s]

Gaps (ex-reports):  28%|██▊       | 2006/7111 [07:28<16:49,  5.05it/s]

Gaps (ex-reports):  28%|██▊       | 2007/7111 [07:29<17:15,  4.93it/s]

Gaps (ex-reports):  28%|██▊       | 2008/7111 [07:29<17:13,  4.94it/s]

Gaps (ex-reports):  28%|██▊       | 2009/7111 [07:29<17:01,  4.99it/s]

Gaps (ex-reports):  28%|██▊       | 2010/7111 [07:29<17:00,  5.00it/s]

Gaps (ex-reports):  28%|██▊       | 2011/7111 [07:29<16:54,  5.02it/s]

Gaps (ex-reports):  28%|██▊       | 2012/7111 [07:30<16:47,  5.06it/s]

Gaps (ex-reports):  28%|██▊       | 2013/7111 [07:30<16:45,  5.07it/s]

Gaps (ex-reports):  28%|██▊       | 2014/7111 [07:30<16:52,  5.03it/s]

Gaps (ex-reports):  28%|██▊       | 2015/7111 [07:30<17:23,  4.88it/s]

Gaps (ex-reports):  28%|██▊       | 2016/7111 [07:31<17:25,  4.87it/s]

Gaps (ex-reports):  28%|██▊       | 2017/7111 [07:32<44:04,  1.93it/s]

Gaps (ex-reports):  28%|██▊       | 2018/7111 [07:32<35:49,  2.37it/s]

Gaps (ex-reports):  28%|██▊       | 2019/7111 [07:32<30:13,  2.81it/s]

Gaps (ex-reports):  28%|██▊       | 2020/7111 [07:32<25:57,  3.27it/s]

Gaps (ex-reports):  28%|██▊       | 2021/7111 [07:33<23:21,  3.63it/s]

Gaps (ex-reports):  28%|██▊       | 2022/7111 [07:33<21:15,  3.99it/s]

Gaps (ex-reports):  28%|██▊       | 2023/7111 [07:33<20:12,  4.20it/s]

Gaps (ex-reports):  28%|██▊       | 2024/7111 [07:33<19:14,  4.41it/s]

Gaps (ex-reports):  28%|██▊       | 2025/7111 [07:33<18:25,  4.60it/s]

Gaps (ex-reports):  28%|██▊       | 2026/7111 [07:34<18:00,  4.70it/s]

Gaps (ex-reports):  29%|██▊       | 2027/7111 [07:34<35:29,  2.39it/s]

Gaps (ex-reports):  29%|██▊       | 2028/7111 [07:35<30:16,  2.80it/s]

Gaps (ex-reports):  29%|██▊       | 2029/7111 [07:35<26:21,  3.21it/s]

Gaps (ex-reports):  29%|██▊       | 2030/7111 [07:35<23:24,  3.62it/s]

Gaps (ex-reports):  29%|██▊       | 2031/7111 [07:35<21:34,  3.92it/s]

Gaps (ex-reports):  29%|██▊       | 2032/7111 [07:35<20:22,  4.16it/s]

Gaps (ex-reports):  29%|██▊       | 2033/7111 [07:36<19:09,  4.42it/s]

Gaps (ex-reports):  29%|██▊       | 2034/7111 [07:36<18:21,  4.61it/s]

Gaps (ex-reports):  29%|██▊       | 2035/7111 [07:36<17:47,  4.75it/s]

Gaps (ex-reports):  29%|██▊       | 2036/7111 [07:36<17:39,  4.79it/s]

Gaps (ex-reports):  29%|██▊       | 2037/7111 [07:36<17:56,  4.71it/s]

Gaps (ex-reports):  29%|██▊       | 2038/7111 [07:37<17:36,  4.80it/s]

Gaps (ex-reports):  29%|██▊       | 2039/7111 [07:37<17:24,  4.85it/s]

Gaps (ex-reports):  29%|██▊       | 2040/7111 [07:37<16:59,  4.98it/s]

Gaps (ex-reports):  29%|██▊       | 2041/7111 [07:37<17:07,  4.93it/s]

Gaps (ex-reports):  29%|██▊       | 2042/7111 [07:37<17:00,  4.97it/s]

Gaps (ex-reports):  29%|██▊       | 2043/7111 [07:38<17:00,  4.97it/s]

Gaps (ex-reports):  29%|██▊       | 2044/7111 [07:38<17:18,  4.88it/s]

Gaps (ex-reports):  29%|██▉       | 2045/7111 [07:38<17:24,  4.85it/s]

Gaps (ex-reports):  29%|██▉       | 2046/7111 [07:38<17:38,  4.78it/s]

Gaps (ex-reports):  29%|██▉       | 2047/7111 [07:39<22:16,  3.79it/s]

Gaps (ex-reports):  29%|██▉       | 2048/7111 [07:39<20:46,  4.06it/s]

Gaps (ex-reports):  29%|██▉       | 2049/7111 [07:39<21:07,  3.99it/s]

Gaps (ex-reports):  29%|██▉       | 2050/7111 [07:39<20:06,  4.20it/s]

Gaps (ex-reports):  29%|██▉       | 2051/7111 [07:40<19:14,  4.38it/s]

Gaps (ex-reports):  29%|██▉       | 2052/7111 [07:40<18:52,  4.47it/s]

Gaps (ex-reports):  29%|██▉       | 2053/7111 [07:40<18:26,  4.57it/s]

Gaps (ex-reports):  29%|██▉       | 2054/7111 [07:40<18:05,  4.66it/s]

Gaps (ex-reports):  29%|██▉       | 2055/7111 [07:40<17:35,  4.79it/s]

Gaps (ex-reports):  29%|██▉       | 2056/7111 [07:41<17:51,  4.72it/s]

Gaps (ex-reports):  29%|██▉       | 2057/7111 [07:41<17:32,  4.80it/s]

Gaps (ex-reports):  29%|██▉       | 2058/7111 [07:41<17:15,  4.88it/s]

Gaps (ex-reports):  29%|██▉       | 2059/7111 [07:41<17:14,  4.89it/s]

Gaps (ex-reports):  29%|██▉       | 2060/7111 [07:41<17:20,  4.86it/s]

Gaps (ex-reports):  29%|██▉       | 2061/7111 [07:42<17:27,  4.82it/s]

Gaps (ex-reports):  29%|██▉       | 2062/7111 [07:42<17:23,  4.84it/s]

Gaps (ex-reports):  29%|██▉       | 2063/7111 [07:42<17:10,  4.90it/s]

Gaps (ex-reports):  29%|██▉       | 2064/7111 [07:42<16:57,  4.96it/s]

Gaps (ex-reports):  29%|██▉       | 2065/7111 [07:42<17:03,  4.93it/s]

Gaps (ex-reports):  29%|██▉       | 2066/7111 [07:43<16:57,  4.96it/s]

Gaps (ex-reports):  29%|██▉       | 2067/7111 [07:43<16:54,  4.97it/s]

Gaps (ex-reports):  29%|██▉       | 2068/7111 [07:43<17:09,  4.90it/s]

Gaps (ex-reports):  29%|██▉       | 2069/7111 [07:43<16:48,  5.00it/s]

Gaps (ex-reports):  29%|██▉       | 2070/7111 [07:43<16:49,  4.99it/s]

Gaps (ex-reports):  29%|██▉       | 2071/7111 [07:44<16:49,  4.99it/s]

Gaps (ex-reports):  29%|██▉       | 2072/7111 [07:44<17:48,  4.71it/s]

Gaps (ex-reports):  29%|██▉       | 2073/7111 [07:44<17:42,  4.74it/s]

Gaps (ex-reports):  29%|██▉       | 2074/7111 [07:44<17:10,  4.89it/s]

Gaps (ex-reports):  29%|██▉       | 2075/7111 [07:45<17:30,  4.79it/s]

Gaps (ex-reports):  29%|██▉       | 2076/7111 [07:45<17:25,  4.82it/s]

Gaps (ex-reports):  29%|██▉       | 2077/7111 [07:45<17:17,  4.85it/s]

Gaps (ex-reports):  29%|██▉       | 2078/7111 [07:45<16:59,  4.93it/s]

Gaps (ex-reports):  29%|██▉       | 2079/7111 [07:45<17:10,  4.88it/s]

Gaps (ex-reports):  29%|██▉       | 2080/7111 [07:46<17:05,  4.91it/s]

Gaps (ex-reports):  29%|██▉       | 2081/7111 [07:46<17:15,  4.86it/s]

Gaps (ex-reports):  29%|██▉       | 2082/7111 [07:46<17:20,  4.83it/s]

Gaps (ex-reports):  29%|██▉       | 2083/7111 [07:46<17:28,  4.80it/s]

Gaps (ex-reports):  29%|██▉       | 2084/7111 [07:46<17:47,  4.71it/s]

Gaps (ex-reports):  29%|██▉       | 2085/7111 [07:47<17:38,  4.75it/s]

Gaps (ex-reports):  29%|██▉       | 2086/7111 [07:47<17:34,  4.77it/s]

Gaps (ex-reports):  29%|██▉       | 2087/7111 [07:47<17:55,  4.67it/s]

Gaps (ex-reports):  29%|██▉       | 2088/7111 [07:47<18:20,  4.56it/s]

Gaps (ex-reports):  29%|██▉       | 2089/7111 [07:48<19:52,  4.21it/s]

Gaps (ex-reports):  29%|██▉       | 2090/7111 [07:48<19:01,  4.40it/s]

Gaps (ex-reports):  29%|██▉       | 2091/7111 [07:48<18:25,  4.54it/s]

Gaps (ex-reports):  29%|██▉       | 2092/7111 [07:48<18:10,  4.60it/s]

Gaps (ex-reports):  29%|██▉       | 2093/7111 [07:48<17:49,  4.69it/s]

Gaps (ex-reports):  29%|██▉       | 2094/7111 [07:49<17:31,  4.77it/s]

Gaps (ex-reports):  29%|██▉       | 2095/7111 [07:49<17:16,  4.84it/s]

Gaps (ex-reports):  29%|██▉       | 2096/7111 [07:49<17:12,  4.86it/s]

Gaps (ex-reports):  29%|██▉       | 2097/7111 [07:49<17:26,  4.79it/s]

Gaps (ex-reports):  30%|██▉       | 2098/7111 [07:49<17:18,  4.83it/s]

Gaps (ex-reports):  30%|██▉       | 2099/7111 [07:50<16:52,  4.95it/s]

Gaps (ex-reports):  30%|██▉       | 2100/7111 [07:50<16:47,  4.97it/s]

Gaps (ex-reports):  30%|██▉       | 2101/7111 [07:50<16:52,  4.95it/s]

Gaps (ex-reports):  30%|██▉       | 2102/7111 [07:50<16:47,  4.97it/s]

Gaps (ex-reports):  30%|██▉       | 2103/7111 [07:50<17:07,  4.88it/s]

Gaps (ex-reports):  30%|██▉       | 2104/7111 [07:51<16:51,  4.95it/s]

Gaps (ex-reports):  30%|██▉       | 2105/7111 [07:51<16:46,  4.97it/s]

Gaps (ex-reports):  30%|██▉       | 2106/7111 [07:51<16:46,  4.97it/s]

Gaps (ex-reports):  30%|██▉       | 2107/7111 [07:51<16:59,  4.91it/s]

Gaps (ex-reports):  30%|██▉       | 2108/7111 [07:51<16:42,  4.99it/s]

Gaps (ex-reports):  30%|██▉       | 2109/7111 [07:52<16:30,  5.05it/s]

Gaps (ex-reports):  30%|██▉       | 2110/7111 [07:52<16:32,  5.04it/s]

Gaps (ex-reports):  30%|██▉       | 2111/7111 [07:52<16:38,  5.01it/s]

Gaps (ex-reports):  30%|██▉       | 2112/7111 [07:52<16:22,  5.09it/s]

Gaps (ex-reports):  30%|██▉       | 2113/7111 [07:52<16:44,  4.98it/s]

Gaps (ex-reports):  30%|██▉       | 2114/7111 [07:53<16:42,  4.98it/s]

Gaps (ex-reports):  30%|██▉       | 2115/7111 [07:53<16:48,  4.95it/s]

Gaps (ex-reports):  30%|██▉       | 2116/7111 [07:53<16:57,  4.91it/s]

Gaps (ex-reports):  30%|██▉       | 2117/7111 [07:53<17:07,  4.86it/s]

Gaps (ex-reports):  30%|██▉       | 2118/7111 [07:53<17:21,  4.79it/s]

Gaps (ex-reports):  30%|██▉       | 2119/7111 [07:54<16:55,  4.91it/s]

Gaps (ex-reports):  30%|██▉       | 2120/7111 [07:54<16:35,  5.01it/s]

Gaps (ex-reports):  30%|██▉       | 2121/7111 [07:54<16:28,  5.05it/s]

Gaps (ex-reports):  30%|██▉       | 2122/7111 [07:54<16:46,  4.96it/s]

Gaps (ex-reports):  30%|██▉       | 2123/7111 [07:54<16:30,  5.04it/s]

Gaps (ex-reports):  30%|██▉       | 2124/7111 [07:55<17:15,  4.82it/s]

Gaps (ex-reports):  30%|██▉       | 2125/7111 [07:55<17:16,  4.81it/s]

Gaps (ex-reports):  30%|██▉       | 2126/7111 [07:55<16:37,  5.00it/s]

Gaps (ex-reports):  30%|██▉       | 2127/7111 [07:55<16:46,  4.95it/s]

Gaps (ex-reports):  30%|██▉       | 2128/7111 [07:55<17:07,  4.85it/s]

Gaps (ex-reports):  30%|██▉       | 2129/7111 [07:56<17:15,  4.81it/s]

Gaps (ex-reports):  30%|██▉       | 2130/7111 [07:56<17:06,  4.85it/s]

Gaps (ex-reports):  30%|██▉       | 2131/7111 [07:56<17:09,  4.84it/s]

Gaps (ex-reports):  30%|██▉       | 2132/7111 [07:56<17:11,  4.83it/s]

Gaps (ex-reports):  30%|██▉       | 2133/7111 [07:56<17:28,  4.75it/s]

Gaps (ex-reports):  30%|███       | 2134/7111 [07:57<17:23,  4.77it/s]

Gaps (ex-reports):  30%|███       | 2135/7111 [07:57<17:11,  4.83it/s]

Gaps (ex-reports):  30%|███       | 2136/7111 [07:57<17:14,  4.81it/s]

Gaps (ex-reports):  30%|███       | 2137/7111 [07:57<17:01,  4.87it/s]

Gaps (ex-reports):  30%|███       | 2138/7111 [07:57<16:35,  5.00it/s]

Gaps (ex-reports):  30%|███       | 2139/7111 [07:58<16:52,  4.91it/s]

Gaps (ex-reports):  30%|███       | 2140/7111 [07:58<16:53,  4.90it/s]

Gaps (ex-reports):  30%|███       | 2141/7111 [07:58<16:41,  4.96it/s]

Gaps (ex-reports):  30%|███       | 2142/7111 [07:58<16:57,  4.88it/s]

Gaps (ex-reports):  30%|███       | 2143/7111 [07:59<16:57,  4.88it/s]

Gaps (ex-reports):  30%|███       | 2144/7111 [07:59<16:36,  4.98it/s]

Gaps (ex-reports):  30%|███       | 2145/7111 [07:59<16:45,  4.94it/s]

Gaps (ex-reports):  30%|███       | 2146/7111 [07:59<16:26,  5.03it/s]

Gaps (ex-reports):  30%|███       | 2147/7111 [07:59<16:26,  5.03it/s]

Gaps (ex-reports):  30%|███       | 2148/7111 [08:00<16:56,  4.88it/s]

Gaps (ex-reports):  30%|███       | 2149/7111 [08:00<17:13,  4.80it/s]

Gaps (ex-reports):  30%|███       | 2150/7111 [08:00<17:02,  4.85it/s]

Gaps (ex-reports):  30%|███       | 2151/7111 [08:00<16:51,  4.90it/s]

Gaps (ex-reports):  30%|███       | 2152/7111 [08:00<16:30,  5.01it/s]

Gaps (ex-reports):  30%|███       | 2153/7111 [08:01<16:25,  5.03it/s]

Gaps (ex-reports):  30%|███       | 2154/7111 [08:01<16:27,  5.02it/s]

Gaps (ex-reports):  30%|███       | 2155/7111 [08:01<16:52,  4.89it/s]

Gaps (ex-reports):  30%|███       | 2156/7111 [08:01<16:55,  4.88it/s]

Gaps (ex-reports):  30%|███       | 2157/7111 [08:01<16:56,  4.87it/s]

Gaps (ex-reports):  30%|███       | 2158/7111 [08:02<17:21,  4.76it/s]

Gaps (ex-reports):  30%|███       | 2159/7111 [08:02<17:17,  4.77it/s]

Gaps (ex-reports):  30%|███       | 2160/7111 [08:02<16:55,  4.87it/s]

Gaps (ex-reports):  30%|███       | 2161/7111 [08:02<17:03,  4.83it/s]

Gaps (ex-reports):  30%|███       | 2162/7111 [08:02<17:04,  4.83it/s]

Gaps (ex-reports):  30%|███       | 2163/7111 [08:03<16:47,  4.91it/s]

Gaps (ex-reports):  30%|███       | 2164/7111 [08:03<16:36,  4.97it/s]

Gaps (ex-reports):  30%|███       | 2165/7111 [08:03<16:54,  4.88it/s]

Gaps (ex-reports):  30%|███       | 2166/7111 [08:03<16:55,  4.87it/s]

Gaps (ex-reports):  30%|███       | 2167/7111 [08:03<16:58,  4.85it/s]

Gaps (ex-reports):  30%|███       | 2168/7111 [08:04<16:58,  4.85it/s]

Gaps (ex-reports):  31%|███       | 2169/7111 [08:04<16:33,  4.97it/s]

Gaps (ex-reports):  31%|███       | 2170/7111 [08:04<16:26,  5.01it/s]

Gaps (ex-reports):  31%|███       | 2171/7111 [08:04<16:37,  4.95it/s]

Gaps (ex-reports):  31%|███       | 2172/7111 [08:04<16:52,  4.88it/s]

Gaps (ex-reports):  31%|███       | 2173/7111 [08:05<16:58,  4.85it/s]

Gaps (ex-reports):  31%|███       | 2174/7111 [08:05<16:48,  4.90it/s]

Gaps (ex-reports):  31%|███       | 2175/7111 [08:05<16:34,  4.96it/s]

Gaps (ex-reports):  31%|███       | 2176/7111 [08:05<16:55,  4.86it/s]

Gaps (ex-reports):  31%|███       | 2177/7111 [08:05<17:15,  4.77it/s]

Gaps (ex-reports):  31%|███       | 2178/7111 [08:06<17:13,  4.77it/s]

Gaps (ex-reports):  31%|███       | 2179/7111 [08:06<17:19,  4.75it/s]

Gaps (ex-reports):  31%|███       | 2180/7111 [08:06<17:05,  4.81it/s]

Gaps (ex-reports):  31%|███       | 2181/7111 [08:06<17:07,  4.80it/s]

Gaps (ex-reports):  31%|███       | 2182/7111 [08:06<16:47,  4.89it/s]

Gaps (ex-reports):  31%|███       | 2183/7111 [08:07<16:55,  4.85it/s]

Gaps (ex-reports):  31%|███       | 2184/7111 [08:07<16:45,  4.90it/s]

Gaps (ex-reports):  31%|███       | 2185/7111 [08:07<16:47,  4.89it/s]

Gaps (ex-reports):  31%|███       | 2186/7111 [08:07<16:29,  4.98it/s]

Gaps (ex-reports):  31%|███       | 2187/7111 [08:07<16:19,  5.03it/s]

Gaps (ex-reports):  31%|███       | 2188/7111 [08:08<16:10,  5.07it/s]

Gaps (ex-reports):  31%|███       | 2189/7111 [08:08<16:27,  4.98it/s]

Gaps (ex-reports):  31%|███       | 2190/7111 [08:08<16:37,  4.94it/s]

Gaps (ex-reports):  31%|███       | 2191/7111 [08:08<16:45,  4.89it/s]

Gaps (ex-reports):  31%|███       | 2192/7111 [08:09<16:31,  4.96it/s]

Gaps (ex-reports):  31%|███       | 2193/7111 [08:09<16:37,  4.93it/s]

Gaps (ex-reports):  31%|███       | 2194/7111 [08:09<16:49,  4.87it/s]

Gaps (ex-reports):  31%|███       | 2195/7111 [08:09<17:43,  4.62it/s]

Gaps (ex-reports):  31%|███       | 2196/7111 [08:09<17:19,  4.73it/s]

Gaps (ex-reports):  31%|███       | 2197/7111 [08:10<16:51,  4.86it/s]

Gaps (ex-reports):  31%|███       | 2198/7111 [08:10<16:42,  4.90it/s]

Gaps (ex-reports):  31%|███       | 2199/7111 [08:10<16:42,  4.90it/s]

Gaps (ex-reports):  31%|███       | 2200/7111 [08:10<16:46,  4.88it/s]

Gaps (ex-reports):  31%|███       | 2201/7111 [08:10<16:27,  4.97it/s]

Gaps (ex-reports):  31%|███       | 2202/7111 [08:11<16:31,  4.95it/s]

Gaps (ex-reports):  31%|███       | 2203/7111 [08:11<16:21,  5.00it/s]

Gaps (ex-reports):  31%|███       | 2204/7111 [08:11<16:32,  4.95it/s]

Gaps (ex-reports):  31%|███       | 2205/7111 [08:11<16:38,  4.91it/s]

Gaps (ex-reports):  31%|███       | 2206/7111 [08:11<16:40,  4.90it/s]

Gaps (ex-reports):  31%|███       | 2207/7111 [08:12<17:01,  4.80it/s]

Gaps (ex-reports):  31%|███       | 2208/7111 [08:12<17:09,  4.76it/s]

Gaps (ex-reports):  31%|███       | 2209/7111 [08:12<18:46,  4.35it/s]

Gaps (ex-reports):  31%|███       | 2210/7111 [08:12<19:44,  4.14it/s]

Gaps (ex-reports):  31%|███       | 2211/7111 [08:13<19:49,  4.12it/s]

Gaps (ex-reports):  31%|███       | 2212/7111 [08:13<21:05,  3.87it/s]

Gaps (ex-reports):  31%|███       | 2213/7111 [08:13<19:33,  4.17it/s]

Gaps (ex-reports):  31%|███       | 2214/7111 [08:13<18:20,  4.45it/s]

Gaps (ex-reports):  31%|███       | 2215/7111 [08:13<17:32,  4.65it/s]

Gaps (ex-reports):  31%|███       | 2216/7111 [08:14<17:05,  4.77it/s]

Gaps (ex-reports):  31%|███       | 2217/7111 [08:14<16:42,  4.88it/s]

Gaps (ex-reports):  31%|███       | 2218/7111 [08:14<16:24,  4.97it/s]

Gaps (ex-reports):  31%|███       | 2219/7111 [08:14<16:19,  5.00it/s]

Gaps (ex-reports):  31%|███       | 2220/7111 [08:14<16:14,  5.02it/s]

Gaps (ex-reports):  31%|███       | 2221/7111 [08:15<16:05,  5.07it/s]

Gaps (ex-reports):  31%|███       | 2222/7111 [08:15<16:26,  4.96it/s]

Gaps (ex-reports):  31%|███▏      | 2223/7111 [08:15<16:17,  5.00it/s]

Gaps (ex-reports):  31%|███▏      | 2224/7111 [08:15<16:20,  4.99it/s]

Gaps (ex-reports):  31%|███▏      | 2225/7111 [08:16<19:02,  4.28it/s]

Gaps (ex-reports):  31%|███▏      | 2226/7111 [08:16<18:18,  4.45it/s]

Gaps (ex-reports):  31%|███▏      | 2227/7111 [08:16<17:59,  4.53it/s]

Gaps (ex-reports):  31%|███▏      | 2228/7111 [08:16<17:50,  4.56it/s]

Gaps (ex-reports):  31%|███▏      | 2229/7111 [08:16<17:13,  4.72it/s]

Gaps (ex-reports):  31%|███▏      | 2230/7111 [08:17<16:48,  4.84it/s]

Gaps (ex-reports):  31%|███▏      | 2231/7111 [08:17<16:48,  4.84it/s]

Gaps (ex-reports):  31%|███▏      | 2232/7111 [08:17<16:23,  4.96it/s]

Gaps (ex-reports):  31%|███▏      | 2233/7111 [08:17<16:17,  4.99it/s]

Gaps (ex-reports):  31%|███▏      | 2234/7111 [08:17<16:26,  4.94it/s]

Gaps (ex-reports):  31%|███▏      | 2235/7111 [08:18<16:12,  5.02it/s]

Gaps (ex-reports):  31%|███▏      | 2236/7111 [08:18<16:05,  5.05it/s]

Gaps (ex-reports):  31%|███▏      | 2237/7111 [08:18<16:24,  4.95it/s]

Gaps (ex-reports):  31%|███▏      | 2238/7111 [08:18<16:33,  4.90it/s]

Gaps (ex-reports):  31%|███▏      | 2239/7111 [08:18<16:40,  4.87it/s]

Gaps (ex-reports):  32%|███▏      | 2240/7111 [08:19<17:31,  4.63it/s]

Gaps (ex-reports):  32%|███▏      | 2241/7111 [08:19<17:32,  4.63it/s]

Gaps (ex-reports):  32%|███▏      | 2242/7111 [08:19<17:22,  4.67it/s]

Gaps (ex-reports):  32%|███▏      | 2243/7111 [08:19<17:17,  4.69it/s]

Gaps (ex-reports):  32%|███▏      | 2244/7111 [08:19<17:10,  4.72it/s]

Gaps (ex-reports):  32%|███▏      | 2245/7111 [08:20<16:57,  4.78it/s]

Gaps (ex-reports):  32%|███▏      | 2246/7111 [08:20<17:04,  4.75it/s]

Gaps (ex-reports):  32%|███▏      | 2247/7111 [08:20<16:57,  4.78it/s]

Gaps (ex-reports):  32%|███▏      | 2248/7111 [08:20<17:10,  4.72it/s]

Gaps (ex-reports):  32%|███▏      | 2249/7111 [08:21<16:53,  4.80it/s]

Gaps (ex-reports):  32%|███▏      | 2250/7111 [08:21<16:49,  4.81it/s]

Gaps (ex-reports):  32%|███▏      | 2251/7111 [08:21<16:42,  4.85it/s]

Gaps (ex-reports):  32%|███▏      | 2252/7111 [08:21<16:33,  4.89it/s]

Gaps (ex-reports):  32%|███▏      | 2253/7111 [08:21<16:32,  4.89it/s]

Gaps (ex-reports):  32%|███▏      | 2254/7111 [08:22<33:05,  2.45it/s]

Gaps (ex-reports):  32%|███▏      | 2255/7111 [08:22<27:59,  2.89it/s]

Gaps (ex-reports):  32%|███▏      | 2256/7111 [08:23<24:53,  3.25it/s]

Gaps (ex-reports):  32%|███▏      | 2257/7111 [08:23<22:28,  3.60it/s]

Gaps (ex-reports):  32%|███▏      | 2258/7111 [08:23<20:53,  3.87it/s]

Gaps (ex-reports):  32%|███▏      | 2259/7111 [08:23<24:59,  3.23it/s]

Gaps (ex-reports):  32%|███▏      | 2260/7111 [08:24<22:30,  3.59it/s]

Gaps (ex-reports):  32%|███▏      | 2261/7111 [08:24<21:03,  3.84it/s]

Gaps (ex-reports):  32%|███▏      | 2262/7111 [08:24<19:28,  4.15it/s]

Gaps (ex-reports):  32%|███▏      | 2263/7111 [08:24<18:44,  4.31it/s]

Gaps (ex-reports):  32%|███▏      | 2264/7111 [08:25<18:24,  4.39it/s]

Gaps (ex-reports):  32%|███▏      | 2265/7111 [08:25<17:42,  4.56it/s]

Gaps (ex-reports):  32%|███▏      | 2266/7111 [08:25<17:15,  4.68it/s]

Gaps (ex-reports):  32%|███▏      | 2267/7111 [08:25<17:29,  4.62it/s]

Gaps (ex-reports):  32%|███▏      | 2268/7111 [08:25<16:54,  4.77it/s]

Gaps (ex-reports):  32%|███▏      | 2269/7111 [08:26<16:23,  4.92it/s]

Gaps (ex-reports):  32%|███▏      | 2270/7111 [08:26<16:27,  4.90it/s]

Gaps (ex-reports):  32%|███▏      | 2271/7111 [08:26<16:55,  4.77it/s]

Gaps (ex-reports):  32%|███▏      | 2272/7111 [08:26<16:32,  4.88it/s]

Gaps (ex-reports):  32%|███▏      | 2273/7111 [08:26<16:17,  4.95it/s]

Gaps (ex-reports):  32%|███▏      | 2274/7111 [08:27<16:22,  4.92it/s]

Gaps (ex-reports):  32%|███▏      | 2275/7111 [08:27<16:14,  4.96it/s]

Gaps (ex-reports):  32%|███▏      | 2276/7111 [08:27<16:16,  4.95it/s]

Gaps (ex-reports):  32%|███▏      | 2277/7111 [08:27<16:32,  4.87it/s]

Gaps (ex-reports):  32%|███▏      | 2278/7111 [08:27<16:24,  4.91it/s]

Gaps (ex-reports):  32%|███▏      | 2279/7111 [08:28<16:09,  4.98it/s]

Gaps (ex-reports):  32%|███▏      | 2280/7111 [08:28<16:23,  4.91it/s]

Gaps (ex-reports):  32%|███▏      | 2281/7111 [08:28<16:19,  4.93it/s]

Gaps (ex-reports):  32%|███▏      | 2282/7111 [08:28<16:19,  4.93it/s]

Gaps (ex-reports):  32%|███▏      | 2283/7111 [08:28<16:19,  4.93it/s]

Gaps (ex-reports):  32%|███▏      | 2284/7111 [08:29<16:06,  4.99it/s]

Gaps (ex-reports):  32%|███▏      | 2285/7111 [08:29<16:13,  4.96it/s]

Gaps (ex-reports):  32%|███▏      | 2286/7111 [08:29<16:00,  5.02it/s]

Gaps (ex-reports):  32%|███▏      | 2287/7111 [08:29<15:56,  5.05it/s]

Gaps (ex-reports):  32%|███▏      | 2288/7111 [08:29<16:14,  4.95it/s]

Gaps (ex-reports):  32%|███▏      | 2289/7111 [08:30<16:16,  4.94it/s]

Gaps (ex-reports):  32%|███▏      | 2290/7111 [08:30<16:50,  4.77it/s]

Gaps (ex-reports):  32%|███▏      | 2291/7111 [08:30<16:54,  4.75it/s]

Gaps (ex-reports):  32%|███▏      | 2292/7111 [08:30<16:44,  4.80it/s]

Gaps (ex-reports):  32%|███▏      | 2293/7111 [08:31<38:25,  2.09it/s]

Gaps (ex-reports):  32%|███▏      | 2294/7111 [08:32<31:53,  2.52it/s]

Gaps (ex-reports):  32%|███▏      | 2295/7111 [08:32<27:28,  2.92it/s]

Gaps (ex-reports):  32%|███▏      | 2296/7111 [08:32<24:25,  3.29it/s]

Gaps (ex-reports):  32%|███▏      | 2297/7111 [08:32<22:15,  3.60it/s]

Gaps (ex-reports):  32%|███▏      | 2298/7111 [08:32<20:40,  3.88it/s]

Gaps (ex-reports):  32%|███▏      | 2299/7111 [08:33<29:37,  2.71it/s]

Gaps (ex-reports):  32%|███▏      | 2300/7111 [08:33<25:40,  3.12it/s]

Gaps (ex-reports):  32%|███▏      | 2301/7111 [08:33<22:59,  3.49it/s]

Gaps (ex-reports):  32%|███▏      | 2302/7111 [08:34<21:15,  3.77it/s]

Gaps (ex-reports):  32%|███▏      | 2303/7111 [08:34<19:39,  4.08it/s]

Gaps (ex-reports):  32%|███▏      | 2304/7111 [08:34<18:40,  4.29it/s]

Gaps (ex-reports):  32%|███▏      | 2305/7111 [08:34<17:51,  4.49it/s]

Gaps (ex-reports):  32%|███▏      | 2306/7111 [08:34<17:33,  4.56it/s]

Gaps (ex-reports):  32%|███▏      | 2307/7111 [08:35<17:14,  4.64it/s]

Gaps (ex-reports):  32%|███▏      | 2308/7111 [08:35<17:04,  4.69it/s]

Gaps (ex-reports):  32%|███▏      | 2309/7111 [08:35<17:06,  4.68it/s]

Gaps (ex-reports):  32%|███▏      | 2310/7111 [08:35<16:48,  4.76it/s]

Gaps (ex-reports):  32%|███▏      | 2311/7111 [08:36<16:41,  4.79it/s]

Gaps (ex-reports):  33%|███▎      | 2312/7111 [08:36<16:33,  4.83it/s]

Gaps (ex-reports):  33%|███▎      | 2313/7111 [08:36<16:25,  4.87it/s]

Gaps (ex-reports):  33%|███▎      | 2314/7111 [08:36<16:43,  4.78it/s]

Gaps (ex-reports):  33%|███▎      | 2315/7111 [08:36<16:33,  4.83it/s]

Gaps (ex-reports):  33%|███▎      | 2316/7111 [08:37<16:42,  4.78it/s]

Gaps (ex-reports):  33%|███▎      | 2317/7111 [08:37<16:16,  4.91it/s]

Gaps (ex-reports):  33%|███▎      | 2318/7111 [08:37<16:22,  4.88it/s]

Gaps (ex-reports):  33%|███▎      | 2319/7111 [08:38<33:53,  2.36it/s]

Gaps (ex-reports):  33%|███▎      | 2320/7111 [08:38<28:18,  2.82it/s]

Gaps (ex-reports):  33%|███▎      | 2321/7111 [08:38<24:36,  3.24it/s]

Gaps (ex-reports):  33%|███▎      | 2322/7111 [08:39<22:18,  3.58it/s]

Gaps (ex-reports):  33%|███▎      | 2323/7111 [08:39<37:59,  2.10it/s]

Gaps (ex-reports):  33%|███▎      | 2324/7111 [08:40<31:38,  2.52it/s]

Gaps (ex-reports):  33%|███▎      | 2325/7111 [08:40<27:05,  2.94it/s]

Gaps (ex-reports):  33%|███▎      | 2326/7111 [08:40<24:04,  3.31it/s]

Gaps (ex-reports):  33%|███▎      | 2327/7111 [08:40<21:40,  3.68it/s]

Gaps (ex-reports):  33%|███▎      | 2328/7111 [08:40<20:13,  3.94it/s]

Gaps (ex-reports):  33%|███▎      | 2329/7111 [08:41<19:13,  4.15it/s]

Gaps (ex-reports):  33%|███▎      | 2330/7111 [08:41<18:30,  4.31it/s]

Gaps (ex-reports):  33%|███▎      | 2331/7111 [08:41<17:47,  4.48it/s]

Gaps (ex-reports):  33%|███▎      | 2332/7111 [08:42<23:33,  3.38it/s]

Gaps (ex-reports):  33%|███▎      | 2333/7111 [08:42<27:09,  2.93it/s]

Gaps (ex-reports):  33%|███▎      | 2334/7111 [08:42<24:01,  3.31it/s]

Gaps (ex-reports):  33%|███▎      | 2335/7111 [08:42<21:23,  3.72it/s]

Gaps (ex-reports):  33%|███▎      | 2336/7111 [08:43<20:07,  3.96it/s]

Gaps (ex-reports):  33%|███▎      | 2337/7111 [08:43<18:53,  4.21it/s]

Gaps (ex-reports):  33%|███▎      | 2338/7111 [08:43<18:19,  4.34it/s]

Gaps (ex-reports):  33%|███▎      | 2339/7111 [08:43<18:04,  4.40it/s]

Gaps (ex-reports):  33%|███▎      | 2340/7111 [08:43<17:25,  4.56it/s]

Gaps (ex-reports):  33%|███▎      | 2341/7111 [08:44<16:48,  4.73it/s]

Gaps (ex-reports):  33%|███▎      | 2342/7111 [08:44<16:50,  4.72it/s]

Gaps (ex-reports):  33%|███▎      | 2343/7111 [08:44<16:36,  4.78it/s]

Gaps (ex-reports):  33%|███▎      | 2344/7111 [08:45<21:41,  3.66it/s]

Gaps (ex-reports):  33%|███▎      | 2345/7111 [08:45<20:08,  3.94it/s]

Gaps (ex-reports):  33%|███▎      | 2346/7111 [08:45<18:37,  4.27it/s]

Gaps (ex-reports):  33%|███▎      | 2347/7111 [08:45<17:59,  4.41it/s]

Gaps (ex-reports):  33%|███▎      | 2348/7111 [08:45<17:18,  4.59it/s]

Gaps (ex-reports):  33%|███▎      | 2349/7111 [08:46<16:52,  4.70it/s]

Gaps (ex-reports):  33%|███▎      | 2350/7111 [08:46<16:50,  4.71it/s]

Gaps (ex-reports):  33%|███▎      | 2351/7111 [08:46<16:29,  4.81it/s]

Gaps (ex-reports):  33%|███▎      | 2352/7111 [08:46<16:15,  4.88it/s]

Gaps (ex-reports):  33%|███▎      | 2353/7111 [08:46<16:18,  4.86it/s]

Gaps (ex-reports):  33%|███▎      | 2354/7111 [08:47<16:27,  4.82it/s]

Gaps (ex-reports):  33%|███▎      | 2355/7111 [08:47<16:25,  4.83it/s]

Gaps (ex-reports):  33%|███▎      | 2356/7111 [08:47<16:20,  4.85it/s]

Gaps (ex-reports):  33%|███▎      | 2357/7111 [08:47<16:20,  4.85it/s]

Gaps (ex-reports):  33%|███▎      | 2358/7111 [08:47<16:00,  4.95it/s]

Gaps (ex-reports):  33%|███▎      | 2359/7111 [08:48<15:51,  4.99it/s]

Gaps (ex-reports):  33%|███▎      | 2360/7111 [08:48<15:44,  5.03it/s]

Gaps (ex-reports):  33%|███▎      | 2361/7111 [08:48<15:50,  5.00it/s]

Gaps (ex-reports):  33%|███▎      | 2362/7111 [08:48<15:57,  4.96it/s]

Gaps (ex-reports):  33%|███▎      | 2363/7111 [08:48<15:50,  5.00it/s]

Gaps (ex-reports):  33%|███▎      | 2364/7111 [08:49<16:03,  4.92it/s]

Gaps (ex-reports):  33%|███▎      | 2365/7111 [08:49<16:07,  4.91it/s]

Gaps (ex-reports):  33%|███▎      | 2366/7111 [08:49<15:54,  4.97it/s]

Gaps (ex-reports):  33%|███▎      | 2367/7111 [08:49<16:01,  4.93it/s]

Gaps (ex-reports):  33%|███▎      | 2368/7111 [08:49<16:07,  4.90it/s]

Gaps (ex-reports):  33%|███▎      | 2369/7111 [08:50<15:52,  4.98it/s]

Gaps (ex-reports):  33%|███▎      | 2370/7111 [08:50<16:03,  4.92it/s]

Gaps (ex-reports):  33%|███▎      | 2371/7111 [08:50<16:05,  4.91it/s]

Gaps (ex-reports):  33%|███▎      | 2372/7111 [08:50<15:46,  5.01it/s]

Gaps (ex-reports):  33%|███▎      | 2373/7111 [08:50<15:33,  5.07it/s]

Gaps (ex-reports):  33%|███▎      | 2374/7111 [08:51<26:13,  3.01it/s]

Gaps (ex-reports):  33%|███▎      | 2375/7111 [08:51<28:49,  2.74it/s]

Gaps (ex-reports):  33%|███▎      | 2376/7111 [08:52<25:35,  3.08it/s]

Gaps (ex-reports):  33%|███▎      | 2377/7111 [08:52<22:44,  3.47it/s]

Gaps (ex-reports):  33%|███▎      | 2378/7111 [08:52<20:30,  3.85it/s]

Gaps (ex-reports):  33%|███▎      | 2379/7111 [08:52<19:19,  4.08it/s]

Gaps (ex-reports):  33%|███▎      | 2380/7111 [08:53<22:03,  3.57it/s]

Gaps (ex-reports):  33%|███▎      | 2381/7111 [08:53<20:22,  3.87it/s]

Gaps (ex-reports):  33%|███▎      | 2382/7111 [08:53<25:18,  3.11it/s]

Gaps (ex-reports):  34%|███▎      | 2383/7111 [08:54<25:16,  3.12it/s]

Gaps (ex-reports):  34%|███▎      | 2384/7111 [08:54<22:53,  3.44it/s]

Gaps (ex-reports):  34%|███▎      | 2385/7111 [08:54<20:39,  3.81it/s]

Gaps (ex-reports):  34%|███▎      | 2386/7111 [08:54<19:22,  4.06it/s]

Gaps (ex-reports):  34%|███▎      | 2387/7111 [08:55<33:41,  2.34it/s]

Gaps (ex-reports):  34%|███▎      | 2388/7111 [08:55<28:22,  2.77it/s]

Gaps (ex-reports):  34%|███▎      | 2389/7111 [08:56<24:30,  3.21it/s]

Gaps (ex-reports):  34%|███▎      | 2390/7111 [08:56<22:10,  3.55it/s]

Gaps (ex-reports):  34%|███▎      | 2391/7111 [08:56<20:29,  3.84it/s]

Gaps (ex-reports):  34%|███▎      | 2392/7111 [08:56<18:52,  4.17it/s]

Gaps (ex-reports):  34%|███▎      | 2393/7111 [08:56<17:39,  4.45it/s]

Gaps (ex-reports):  34%|███▎      | 2394/7111 [08:57<17:18,  4.54it/s]

Gaps (ex-reports):  34%|███▎      | 2395/7111 [08:57<16:43,  4.70it/s]

Gaps (ex-reports):  34%|███▎      | 2396/7111 [08:57<16:33,  4.74it/s]

Gaps (ex-reports):  34%|███▎      | 2397/7111 [08:57<16:21,  4.80it/s]

Gaps (ex-reports):  34%|███▎      | 2398/7111 [08:57<16:20,  4.81it/s]

Gaps (ex-reports):  34%|███▎      | 2399/7111 [08:58<15:58,  4.92it/s]

Gaps (ex-reports):  34%|███▍      | 2400/7111 [08:58<15:48,  4.97it/s]

Gaps (ex-reports):  34%|███▍      | 2401/7111 [08:58<15:37,  5.02it/s]

Gaps (ex-reports):  34%|███▍      | 2402/7111 [08:59<33:54,  2.31it/s]

Gaps (ex-reports):  34%|███▍      | 2403/7111 [08:59<28:31,  2.75it/s]

Gaps (ex-reports):  34%|███▍      | 2404/7111 [08:59<24:57,  3.14it/s]

Gaps (ex-reports):  34%|███▍      | 2405/7111 [09:00<22:21,  3.51it/s]

Gaps (ex-reports):  34%|███▍      | 2406/7111 [09:00<20:38,  3.80it/s]

Gaps (ex-reports):  34%|███▍      | 2407/7111 [09:00<19:22,  4.05it/s]

Gaps (ex-reports):  34%|███▍      | 2408/7111 [09:00<18:20,  4.27it/s]

Gaps (ex-reports):  34%|███▍      | 2409/7111 [09:00<17:22,  4.51it/s]

Gaps (ex-reports):  34%|███▍      | 2410/7111 [09:01<17:12,  4.55it/s]

Gaps (ex-reports):  34%|███▍      | 2411/7111 [09:01<16:47,  4.66it/s]

Gaps (ex-reports):  34%|███▍      | 2412/7111 [09:01<16:45,  4.67it/s]

Gaps (ex-reports):  34%|███▍      | 2413/7111 [09:01<16:22,  4.78it/s]

Gaps (ex-reports):  34%|███▍      | 2414/7111 [09:01<16:01,  4.88it/s]

Gaps (ex-reports):  34%|███▍      | 2415/7111 [09:02<15:42,  4.98it/s]

Gaps (ex-reports):  34%|███▍      | 2416/7111 [09:02<15:28,  5.06it/s]

Gaps (ex-reports):  34%|███▍      | 2417/7111 [09:02<15:32,  5.03it/s]

Gaps (ex-reports):  34%|███▍      | 2418/7111 [09:02<15:36,  5.01it/s]

Gaps (ex-reports):  34%|███▍      | 2419/7111 [09:02<15:32,  5.03it/s]

Gaps (ex-reports):  34%|███▍      | 2420/7111 [09:03<16:24,  4.76it/s]

Gaps (ex-reports):  34%|███▍      | 2421/7111 [09:03<16:04,  4.86it/s]

Gaps (ex-reports):  34%|███▍      | 2422/7111 [09:03<16:14,  4.81it/s]

Gaps (ex-reports):  34%|███▍      | 2423/7111 [09:03<16:05,  4.86it/s]

Gaps (ex-reports):  34%|███▍      | 2424/7111 [09:03<16:06,  4.85it/s]

Gaps (ex-reports):  34%|███▍      | 2425/7111 [09:04<15:42,  4.97it/s]

Gaps (ex-reports):  34%|███▍      | 2426/7111 [09:04<15:50,  4.93it/s]

Gaps (ex-reports):  34%|███▍      | 2427/7111 [09:04<15:46,  4.95it/s]

Gaps (ex-reports):  34%|███▍      | 2428/7111 [09:04<17:45,  4.40it/s]

Gaps (ex-reports):  34%|███▍      | 2429/7111 [09:05<29:05,  2.68it/s]

Gaps (ex-reports):  34%|███▍      | 2430/7111 [09:05<25:14,  3.09it/s]

Gaps (ex-reports):  34%|███▍      | 2431/7111 [09:05<22:47,  3.42it/s]

Gaps (ex-reports):  34%|███▍      | 2432/7111 [09:06<20:52,  3.74it/s]

Gaps (ex-reports):  34%|███▍      | 2433/7111 [09:06<19:19,  4.03it/s]

Gaps (ex-reports):  34%|███▍      | 2434/7111 [09:06<18:27,  4.22it/s]

Gaps (ex-reports):  34%|███▍      | 2435/7111 [09:06<17:37,  4.42it/s]

Gaps (ex-reports):  34%|███▍      | 2436/7111 [09:06<16:51,  4.62it/s]

Gaps (ex-reports):  34%|███▍      | 2437/7111 [09:07<16:47,  4.64it/s]

Gaps (ex-reports):  34%|███▍      | 2438/7111 [09:07<16:45,  4.65it/s]

Gaps (ex-reports):  34%|███▍      | 2439/7111 [09:07<16:47,  4.64it/s]

Gaps (ex-reports):  34%|███▍      | 2440/7111 [09:07<16:35,  4.69it/s]

Gaps (ex-reports):  34%|███▍      | 2441/7111 [09:07<16:20,  4.76it/s]

Gaps (ex-reports):  34%|███▍      | 2442/7111 [09:08<15:55,  4.88it/s]

Gaps (ex-reports):  34%|███▍      | 2443/7111 [09:08<15:45,  4.93it/s]

Gaps (ex-reports):  34%|███▍      | 2444/7111 [09:08<15:50,  4.91it/s]

Gaps (ex-reports):  34%|███▍      | 2445/7111 [09:08<15:54,  4.89it/s]

Gaps (ex-reports):  34%|███▍      | 2446/7111 [09:08<15:37,  4.98it/s]

Gaps (ex-reports):  34%|███▍      | 2447/7111 [09:09<15:18,  5.08it/s]

Gaps (ex-reports):  34%|███▍      | 2448/7111 [09:09<15:36,  4.98it/s]

Gaps (ex-reports):  34%|███▍      | 2449/7111 [09:09<17:15,  4.50it/s]

Gaps (ex-reports):  34%|███▍      | 2450/7111 [09:09<16:51,  4.61it/s]

Gaps (ex-reports):  34%|███▍      | 2451/7111 [09:10<16:50,  4.61it/s]

Gaps (ex-reports):  34%|███▍      | 2452/7111 [09:10<16:26,  4.72it/s]

Gaps (ex-reports):  34%|███▍      | 2453/7111 [09:10<16:28,  4.71it/s]

Gaps (ex-reports):  35%|███▍      | 2454/7111 [09:10<16:27,  4.71it/s]

Gaps (ex-reports):  35%|███▍      | 2455/7111 [09:10<16:11,  4.79it/s]

Gaps (ex-reports):  35%|███▍      | 2456/7111 [09:11<16:00,  4.85it/s]

Gaps (ex-reports):  35%|███▍      | 2457/7111 [09:11<15:58,  4.86it/s]

Gaps (ex-reports):  35%|███▍      | 2458/7111 [09:11<15:43,  4.93it/s]

Gaps (ex-reports):  35%|███▍      | 2459/7111 [09:11<15:55,  4.87it/s]

Gaps (ex-reports):  35%|███▍      | 2460/7111 [09:11<15:46,  4.91it/s]

Gaps (ex-reports):  35%|███▍      | 2461/7111 [09:12<15:51,  4.89it/s]

Gaps (ex-reports):  35%|███▍      | 2462/7111 [09:12<15:35,  4.97it/s]

Gaps (ex-reports):  35%|███▍      | 2463/7111 [09:12<15:23,  5.04it/s]

Gaps (ex-reports):  35%|███▍      | 2464/7111 [09:12<15:34,  4.97it/s]

Gaps (ex-reports):  35%|███▍      | 2465/7111 [09:12<15:49,  4.89it/s]

Gaps (ex-reports):  35%|███▍      | 2466/7111 [09:13<16:10,  4.79it/s]

Gaps (ex-reports):  35%|███▍      | 2467/7111 [09:13<15:50,  4.89it/s]

Gaps (ex-reports):  35%|███▍      | 2468/7111 [09:13<15:40,  4.93it/s]

Gaps (ex-reports):  35%|███▍      | 2469/7111 [09:13<15:42,  4.92it/s]

Gaps (ex-reports):  35%|███▍      | 2470/7111 [09:13<15:41,  4.93it/s]

Gaps (ex-reports):  35%|███▍      | 2471/7111 [09:14<15:40,  4.94it/s]

Gaps (ex-reports):  35%|███▍      | 2472/7111 [09:14<15:40,  4.93it/s]

Gaps (ex-reports):  35%|███▍      | 2473/7111 [09:14<16:10,  4.78it/s]

Gaps (ex-reports):  35%|███▍      | 2474/7111 [09:14<15:54,  4.86it/s]

Gaps (ex-reports):  35%|███▍      | 2475/7111 [09:15<24:06,  3.20it/s]

Gaps (ex-reports):  35%|███▍      | 2476/7111 [09:15<21:53,  3.53it/s]

Gaps (ex-reports):  35%|███▍      | 2477/7111 [09:15<24:28,  3.16it/s]

Gaps (ex-reports):  35%|███▍      | 2478/7111 [09:16<21:57,  3.52it/s]

Gaps (ex-reports):  35%|███▍      | 2479/7111 [09:16<20:20,  3.79it/s]

Gaps (ex-reports):  35%|███▍      | 2480/7111 [09:16<18:35,  4.15it/s]

Gaps (ex-reports):  35%|███▍      | 2481/7111 [09:16<17:30,  4.41it/s]

Gaps (ex-reports):  35%|███▍      | 2482/7111 [09:16<16:44,  4.61it/s]

Gaps (ex-reports):  35%|███▍      | 2483/7111 [09:17<16:38,  4.64it/s]

Gaps (ex-reports):  35%|███▍      | 2484/7111 [09:17<16:32,  4.66it/s]

Gaps (ex-reports):  35%|███▍      | 2485/7111 [09:17<19:10,  4.02it/s]

Gaps (ex-reports):  35%|███▍      | 2486/7111 [09:17<18:12,  4.23it/s]

Gaps (ex-reports):  35%|███▍      | 2487/7111 [09:18<17:55,  4.30it/s]

Gaps (ex-reports):  35%|███▍      | 2488/7111 [09:18<28:52,  2.67it/s]

Gaps (ex-reports):  35%|███▌      | 2489/7111 [09:19<24:59,  3.08it/s]

Gaps (ex-reports):  35%|███▌      | 2490/7111 [09:19<37:02,  2.08it/s]

Gaps (ex-reports):  35%|███▌      | 2491/7111 [09:20<30:18,  2.54it/s]

Gaps (ex-reports):  35%|███▌      | 2492/7111 [09:20<25:41,  3.00it/s]

Gaps (ex-reports):  35%|███▌      | 2493/7111 [09:20<22:28,  3.42it/s]

Gaps (ex-reports):  35%|███▌      | 2494/7111 [09:20<20:37,  3.73it/s]

Gaps (ex-reports):  35%|███▌      | 2495/7111 [09:20<19:00,  4.05it/s]

Gaps (ex-reports):  35%|███▌      | 2496/7111 [09:21<17:52,  4.30it/s]

Gaps (ex-reports):  35%|███▌      | 2497/7111 [09:21<17:32,  4.39it/s]

Gaps (ex-reports):  35%|███▌      | 2498/7111 [09:21<16:46,  4.58it/s]

Gaps (ex-reports):  35%|███▌      | 2499/7111 [09:21<16:21,  4.70it/s]

Gaps (ex-reports):  35%|███▌      | 2500/7111 [09:21<16:10,  4.75it/s]

Gaps (ex-reports):  35%|███▌      | 2501/7111 [09:22<15:54,  4.83it/s]

Gaps (ex-reports):  35%|███▌      | 2502/7111 [09:22<15:37,  4.92it/s]

Gaps (ex-reports):  35%|███▌      | 2503/7111 [09:22<15:53,  4.83it/s]

Gaps (ex-reports):  35%|███▌      | 2504/7111 [09:22<22:01,  3.49it/s]

Gaps (ex-reports):  35%|███▌      | 2505/7111 [09:23<20:21,  3.77it/s]

Gaps (ex-reports):  35%|███▌      | 2506/7111 [09:23<19:00,  4.04it/s]

Gaps (ex-reports):  35%|███▌      | 2507/7111 [09:23<18:04,  4.24it/s]

Gaps (ex-reports):  35%|███▌      | 2508/7111 [09:23<17:17,  4.44it/s]

Gaps (ex-reports):  35%|███▌      | 2509/7111 [09:24<16:56,  4.53it/s]

Gaps (ex-reports):  35%|███▌      | 2510/7111 [09:24<16:17,  4.71it/s]

Gaps (ex-reports):  35%|███▌      | 2511/7111 [09:24<16:05,  4.76it/s]

Gaps (ex-reports):  35%|███▌      | 2512/7111 [09:24<16:26,  4.66it/s]

Gaps (ex-reports):  35%|███▌      | 2513/7111 [09:24<16:09,  4.74it/s]

Gaps (ex-reports):  35%|███▌      | 2514/7111 [09:25<16:04,  4.77it/s]

Gaps (ex-reports):  35%|███▌      | 2515/7111 [09:25<16:57,  4.52it/s]

Gaps (ex-reports):  35%|███▌      | 2516/7111 [09:25<16:19,  4.69it/s]

Gaps (ex-reports):  35%|███▌      | 2517/7111 [09:25<16:25,  4.66it/s]

Gaps (ex-reports):  35%|███▌      | 2518/7111 [09:25<16:08,  4.74it/s]

Gaps (ex-reports):  35%|███▌      | 2519/7111 [09:28<1:11:00,  1.08it/s]

Gaps (ex-reports):  35%|███▌      | 2520/7111 [09:28<54:19,  1.41it/s]

Gaps (ex-reports):  35%|███▌      | 2521/7111 [09:28<42:23,  1.80it/s]

Gaps (ex-reports):  35%|███▌      | 2522/7111 [09:30<1:06:21,  1.15it/s]

Gaps (ex-reports):  35%|███▌      | 2523/7111 [09:30<50:58,  1.50it/s]

Gaps (ex-reports):  35%|███▌      | 2524/7111 [09:30<40:26,  1.89it/s]

Gaps (ex-reports):  36%|███▌      | 2525/7111 [09:31<33:30,  2.28it/s]

Gaps (ex-reports):  36%|███▌      | 2526/7111 [09:31<28:22,  2.69it/s]

Gaps (ex-reports):  36%|███▌      | 2527/7111 [09:31<24:34,  3.11it/s]

Gaps (ex-reports):  36%|███▌      | 2528/7111 [09:31<21:51,  3.49it/s]

Gaps (ex-reports):  36%|███▌      | 2529/7111 [09:31<19:47,  3.86it/s]

Gaps (ex-reports):  36%|███▌      | 2530/7111 [09:32<18:42,  4.08it/s]

Gaps (ex-reports):  36%|███▌      | 2531/7111 [09:32<17:48,  4.29it/s]

Gaps (ex-reports):  36%|███▌      | 2532/7111 [09:32<16:59,  4.49it/s]

Gaps (ex-reports):  36%|███▌      | 2533/7111 [09:32<16:58,  4.50it/s]

Gaps (ex-reports):  36%|███▌      | 2534/7111 [09:32<16:22,  4.66it/s]

Gaps (ex-reports):  36%|███▌      | 2535/7111 [09:33<16:03,  4.75it/s]

Gaps (ex-reports):  36%|███▌      | 2536/7111 [09:33<15:42,  4.85it/s]

Gaps (ex-reports):  36%|███▌      | 2537/7111 [09:33<15:45,  4.84it/s]

Gaps (ex-reports):  36%|███▌      | 2538/7111 [09:33<16:00,  4.76it/s]

Gaps (ex-reports):  36%|███▌      | 2539/7111 [09:34<15:42,  4.85it/s]

Gaps (ex-reports):  36%|███▌      | 2540/7111 [09:34<15:44,  4.84it/s]

Gaps (ex-reports):  36%|███▌      | 2541/7111 [09:34<15:44,  4.84it/s]

Gaps (ex-reports):  36%|███▌      | 2542/7111 [09:34<15:44,  4.84it/s]

Gaps (ex-reports):  36%|███▌      | 2543/7111 [09:35<19:45,  3.85it/s]

Gaps (ex-reports):  36%|███▌      | 2544/7111 [09:35<18:19,  4.16it/s]

Gaps (ex-reports):  36%|███▌      | 2545/7111 [09:35<17:25,  4.37it/s]

Gaps (ex-reports):  36%|███▌      | 2546/7111 [09:35<17:17,  4.40it/s]

Gaps (ex-reports):  36%|███▌      | 2547/7111 [09:35<16:50,  4.52it/s]

Gaps (ex-reports):  36%|███▌      | 2548/7111 [09:36<16:14,  4.68it/s]

Gaps (ex-reports):  36%|███▌      | 2549/7111 [09:36<16:10,  4.70it/s]

Gaps (ex-reports):  36%|███▌      | 2550/7111 [09:36<16:13,  4.69it/s]

Gaps (ex-reports):  36%|███▌      | 2551/7111 [09:36<15:56,  4.77it/s]

Gaps (ex-reports):  36%|███▌      | 2552/7111 [09:36<15:57,  4.76it/s]

Gaps (ex-reports):  36%|███▌      | 2553/7111 [09:37<15:58,  4.76it/s]

Gaps (ex-reports):  36%|███▌      | 2554/7111 [09:37<15:51,  4.79it/s]

Gaps (ex-reports):  36%|███▌      | 2555/7111 [09:37<15:42,  4.83it/s]

Gaps (ex-reports):  36%|███▌      | 2556/7111 [09:37<15:45,  4.82it/s]

Gaps (ex-reports):  36%|███▌      | 2557/7111 [09:37<15:44,  4.82it/s]

Gaps (ex-reports):  36%|███▌      | 2558/7111 [09:38<16:02,  4.73it/s]

Gaps (ex-reports):  36%|███▌      | 2559/7111 [09:38<15:44,  4.82it/s]

Gaps (ex-reports):  36%|███▌      | 2560/7111 [09:38<16:07,  4.70it/s]

Gaps (ex-reports):  36%|███▌      | 2561/7111 [09:38<16:04,  4.72it/s]

Gaps (ex-reports):  36%|███▌      | 2562/7111 [09:38<15:51,  4.78it/s]

Gaps (ex-reports):  36%|███▌      | 2563/7111 [09:39<15:31,  4.88it/s]

Gaps (ex-reports):  36%|███▌      | 2564/7111 [09:39<15:36,  4.86it/s]

Gaps (ex-reports):  36%|███▌      | 2565/7111 [09:39<15:33,  4.87it/s]

Gaps (ex-reports):  36%|███▌      | 2566/7111 [09:39<15:40,  4.83it/s]

Gaps (ex-reports):  36%|███▌      | 2567/7111 [09:39<15:24,  4.92it/s]

Gaps (ex-reports):  36%|███▌      | 2568/7111 [09:40<27:11,  2.78it/s]

Gaps (ex-reports):  36%|███▌      | 2569/7111 [09:40<23:37,  3.21it/s]

Gaps (ex-reports):  36%|███▌      | 2570/7111 [09:41<21:29,  3.52it/s]

Gaps (ex-reports):  36%|███▌      | 2571/7111 [09:41<19:19,  3.91it/s]

Gaps (ex-reports):  36%|███▌      | 2572/7111 [09:41<17:47,  4.25it/s]

Gaps (ex-reports):  36%|███▌      | 2573/7111 [09:41<17:18,  4.37it/s]

Gaps (ex-reports):  36%|███▌      | 2574/7111 [09:41<16:54,  4.47it/s]

Gaps (ex-reports):  36%|███▌      | 2575/7111 [09:42<16:35,  4.56it/s]

Gaps (ex-reports):  36%|███▌      | 2576/7111 [09:42<16:00,  4.72it/s]

Gaps (ex-reports):  36%|███▌      | 2577/7111 [09:42<16:27,  4.59it/s]

Gaps (ex-reports):  36%|███▋      | 2578/7111 [09:42<16:01,  4.72it/s]

Gaps (ex-reports):  36%|███▋      | 2579/7111 [09:42<15:36,  4.84it/s]

Gaps (ex-reports):  36%|███▋      | 2580/7111 [09:43<15:23,  4.91it/s]

Gaps (ex-reports):  36%|███▋      | 2581/7111 [09:43<15:25,  4.89it/s]

Gaps (ex-reports):  36%|███▋      | 2582/7111 [09:43<15:37,  4.83it/s]

Gaps (ex-reports):  36%|███▋      | 2583/7111 [09:43<18:57,  3.98it/s]

Gaps (ex-reports):  36%|███▋      | 2584/7111 [09:44<18:00,  4.19it/s]

Gaps (ex-reports):  36%|███▋      | 2585/7111 [09:44<26:33,  2.84it/s]

Gaps (ex-reports):  36%|███▋      | 2586/7111 [09:44<23:15,  3.24it/s]

Gaps (ex-reports):  36%|███▋      | 2587/7111 [09:45<20:59,  3.59it/s]

Gaps (ex-reports):  36%|███▋      | 2588/7111 [09:45<19:37,  3.84it/s]

Gaps (ex-reports):  36%|███▋      | 2589/7111 [09:45<18:10,  4.15it/s]

Gaps (ex-reports):  36%|███▋      | 2590/7111 [09:45<17:11,  4.38it/s]

Gaps (ex-reports):  36%|███▋      | 2591/7111 [09:45<16:38,  4.53it/s]

Gaps (ex-reports):  36%|███▋      | 2592/7111 [09:46<16:18,  4.62it/s]

Gaps (ex-reports):  36%|███▋      | 2593/7111 [09:46<16:21,  4.60it/s]

Gaps (ex-reports):  36%|███▋      | 2594/7111 [09:46<16:11,  4.65it/s]

Gaps (ex-reports):  36%|███▋      | 2595/7111 [09:46<15:41,  4.79it/s]

Gaps (ex-reports):  37%|███▋      | 2596/7111 [09:47<29:19,  2.57it/s]

Gaps (ex-reports):  37%|███▋      | 2597/7111 [09:47<25:04,  3.00it/s]

Gaps (ex-reports):  37%|███▋      | 2598/7111 [09:48<22:06,  3.40it/s]

Gaps (ex-reports):  37%|███▋      | 2599/7111 [09:48<20:19,  3.70it/s]

Gaps (ex-reports):  37%|███▋      | 2600/7111 [09:48<18:52,  3.98it/s]

Gaps (ex-reports):  37%|███▋      | 2601/7111 [09:48<17:35,  4.27it/s]

Gaps (ex-reports):  37%|███▋      | 2602/7111 [09:48<17:24,  4.32it/s]

Gaps (ex-reports):  37%|███▋      | 2603/7111 [09:49<16:40,  4.50it/s]

Gaps (ex-reports):  37%|███▋      | 2604/7111 [09:50<36:09,  2.08it/s]

Gaps (ex-reports):  37%|███▋      | 2605/7111 [09:50<29:52,  2.51it/s]

Gaps (ex-reports):  37%|███▋      | 2606/7111 [09:50<25:58,  2.89it/s]

Gaps (ex-reports):  37%|███▋      | 2607/7111 [09:50<22:42,  3.31it/s]

Gaps (ex-reports):  37%|███▋      | 2608/7111 [09:50<20:06,  3.73it/s]

Gaps (ex-reports):  37%|███▋      | 2609/7111 [09:51<18:45,  4.00it/s]

Gaps (ex-reports):  37%|███▋      | 2610/7111 [09:51<17:59,  4.17it/s]

Gaps (ex-reports):  37%|███▋      | 2611/7111 [09:51<17:21,  4.32it/s]

Gaps (ex-reports):  37%|███▋      | 2612/7111 [09:51<16:46,  4.47it/s]

Gaps (ex-reports):  37%|███▋      | 2613/7111 [09:52<16:46,  4.47it/s]

Gaps (ex-reports):  37%|███▋      | 2614/7111 [09:52<16:14,  4.62it/s]

Gaps (ex-reports):  37%|███▋      | 2615/7111 [09:52<15:59,  4.69it/s]

Gaps (ex-reports):  37%|███▋      | 2616/7111 [09:52<15:35,  4.81it/s]

Gaps (ex-reports):  37%|███▋      | 2617/7111 [09:52<15:37,  4.80it/s]

Gaps (ex-reports):  37%|███▋      | 2618/7111 [09:53<15:52,  4.72it/s]

Gaps (ex-reports):  37%|███▋      | 2619/7111 [09:53<15:20,  4.88it/s]

Gaps (ex-reports):  37%|███▋      | 2620/7111 [09:53<15:17,  4.90it/s]

Gaps (ex-reports):  37%|███▋      | 2621/7111 [09:53<15:13,  4.92it/s]

Gaps (ex-reports):  37%|███▋      | 2622/7111 [09:53<15:17,  4.89it/s]

Gaps (ex-reports):  37%|███▋      | 2623/7111 [09:54<15:03,  4.97it/s]

Gaps (ex-reports):  37%|███▋      | 2624/7111 [09:54<15:26,  4.84it/s]

Gaps (ex-reports):  37%|███▋      | 2625/7111 [09:54<15:14,  4.90it/s]

Gaps (ex-reports):  37%|███▋      | 2626/7111 [09:54<15:03,  4.96it/s]

Gaps (ex-reports):  37%|███▋      | 2627/7111 [09:54<15:10,  4.92it/s]

Gaps (ex-reports):  37%|███▋      | 2628/7111 [09:55<15:17,  4.89it/s]

Gaps (ex-reports):  37%|███▋      | 2629/7111 [09:55<15:25,  4.84it/s]

Gaps (ex-reports):  37%|███▋      | 2630/7111 [09:55<15:27,  4.83it/s]

Gaps (ex-reports):  37%|███▋      | 2631/7111 [09:55<15:25,  4.84it/s]

Gaps (ex-reports):  37%|███▋      | 2632/7111 [09:55<15:28,  4.83it/s]

Gaps (ex-reports):  37%|███▋      | 2633/7111 [09:56<15:40,  4.76it/s]

Gaps (ex-reports):  37%|███▋      | 2634/7111 [09:56<15:23,  4.85it/s]

Gaps (ex-reports):  37%|███▋      | 2635/7111 [09:56<15:22,  4.85it/s]

Gaps (ex-reports):  37%|███▋      | 2636/7111 [09:56<15:26,  4.83it/s]

Gaps (ex-reports):  37%|███▋      | 2637/7111 [09:56<15:24,  4.84it/s]

Gaps (ex-reports):  37%|███▋      | 2638/7111 [09:57<27:32,  2.71it/s]

Gaps (ex-reports):  37%|███▋      | 2639/7111 [09:57<23:55,  3.12it/s]

Gaps (ex-reports):  37%|███▋      | 2640/7111 [09:58<21:38,  3.44it/s]

Gaps (ex-reports):  37%|███▋      | 2641/7111 [09:58<19:45,  3.77it/s]

Gaps (ex-reports):  37%|███▋      | 2642/7111 [09:58<18:22,  4.05it/s]

Gaps (ex-reports):  37%|███▋      | 2643/7111 [09:58<17:19,  4.30it/s]

Gaps (ex-reports):  37%|███▋      | 2644/7111 [09:58<16:46,  4.44it/s]

Gaps (ex-reports):  37%|███▋      | 2645/7111 [09:59<16:33,  4.50it/s]

Gaps (ex-reports):  37%|███▋      | 2646/7111 [09:59<16:10,  4.60it/s]

Gaps (ex-reports):  37%|███▋      | 2647/7111 [09:59<15:49,  4.70it/s]

Gaps (ex-reports):  37%|███▋      | 2648/7111 [09:59<15:58,  4.66it/s]

Gaps (ex-reports):  37%|███▋      | 2649/7111 [10:00<15:49,  4.70it/s]

Gaps (ex-reports):  37%|███▋      | 2650/7111 [10:00<15:43,  4.73it/s]

Gaps (ex-reports):  37%|███▋      | 2651/7111 [10:00<15:42,  4.73it/s]

Gaps (ex-reports):  37%|███▋      | 2652/7111 [10:00<15:37,  4.76it/s]

Gaps (ex-reports):  37%|███▋      | 2653/7111 [10:00<15:40,  4.74it/s]

Gaps (ex-reports):  37%|███▋      | 2654/7111 [10:01<15:11,  4.89it/s]

Gaps (ex-reports):  37%|███▋      | 2655/7111 [10:01<14:59,  4.95it/s]

Gaps (ex-reports):  37%|███▋      | 2656/7111 [10:01<14:59,  4.95it/s]

Gaps (ex-reports):  37%|███▋      | 2657/7111 [10:01<15:01,  4.94it/s]

Gaps (ex-reports):  37%|███▋      | 2658/7111 [10:01<14:48,  5.01it/s]

Gaps (ex-reports):  37%|███▋      | 2659/7111 [10:02<14:43,  5.04it/s]

Gaps (ex-reports):  37%|███▋      | 2660/7111 [10:02<15:11,  4.88it/s]

Gaps (ex-reports):  37%|███▋      | 2661/7111 [10:02<14:58,  4.96it/s]

Gaps (ex-reports):  37%|███▋      | 2662/7111 [10:02<15:23,  4.82it/s]

Gaps (ex-reports):  37%|███▋      | 2663/7111 [10:02<15:12,  4.87it/s]

Gaps (ex-reports):  37%|███▋      | 2664/7111 [10:03<15:24,  4.81it/s]

Gaps (ex-reports):  37%|███▋      | 2665/7111 [10:03<15:07,  4.90it/s]

Gaps (ex-reports):  37%|███▋      | 2666/7111 [10:03<15:17,  4.84it/s]

Gaps (ex-reports):  38%|███▊      | 2667/7111 [10:03<15:24,  4.80it/s]

Gaps (ex-reports):  38%|███▊      | 2668/7111 [10:03<15:16,  4.85it/s]

Gaps (ex-reports):  38%|███▊      | 2669/7111 [10:04<15:01,  4.93it/s]

Gaps (ex-reports):  38%|███▊      | 2670/7111 [10:04<15:20,  4.82it/s]

Gaps (ex-reports):  38%|███▊      | 2671/7111 [10:04<15:07,  4.89it/s]

Gaps (ex-reports):  38%|███▊      | 2672/7111 [10:04<15:31,  4.76it/s]

Gaps (ex-reports):  38%|███▊      | 2673/7111 [10:04<15:11,  4.87it/s]

Gaps (ex-reports):  38%|███▊      | 2674/7111 [10:05<15:25,  4.79it/s]

Gaps (ex-reports):  38%|███▊      | 2675/7111 [10:05<15:03,  4.91it/s]

Gaps (ex-reports):  38%|███▊      | 2676/7111 [10:05<15:11,  4.86it/s]

Gaps (ex-reports):  38%|███▊      | 2677/7111 [10:05<14:57,  4.94it/s]

Gaps (ex-reports):  38%|███▊      | 2678/7111 [10:05<15:17,  4.83it/s]

Gaps (ex-reports):  38%|███▊      | 2679/7111 [10:06<15:17,  4.83it/s]

Gaps (ex-reports):  38%|███▊      | 2680/7111 [10:06<15:06,  4.89it/s]

Gaps (ex-reports):  38%|███▊      | 2681/7111 [10:06<15:08,  4.87it/s]

Gaps (ex-reports):  38%|███▊      | 2682/7111 [10:07<22:59,  3.21it/s]

Gaps (ex-reports):  38%|███▊      | 2683/7111 [10:07<20:21,  3.62it/s]

Gaps (ex-reports):  38%|███▊      | 2684/7111 [10:07<18:48,  3.92it/s]

Gaps (ex-reports):  38%|███▊      | 2685/7111 [10:07<17:34,  4.20it/s]

Gaps (ex-reports):  38%|███▊      | 2686/7111 [10:07<16:53,  4.37it/s]

Gaps (ex-reports):  38%|███▊      | 2687/7111 [10:08<16:55,  4.36it/s]

Gaps (ex-reports):  38%|███▊      | 2688/7111 [10:08<21:59,  3.35it/s]

Gaps (ex-reports):  38%|███▊      | 2689/7111 [10:08<19:59,  3.69it/s]

Gaps (ex-reports):  38%|███▊      | 2690/7111 [10:09<18:27,  3.99it/s]

Gaps (ex-reports):  38%|███▊      | 2691/7111 [10:09<17:22,  4.24it/s]

Gaps (ex-reports):  38%|███▊      | 2692/7111 [10:09<16:40,  4.42it/s]

Gaps (ex-reports):  38%|███▊      | 2693/7111 [10:09<16:09,  4.56it/s]

Gaps (ex-reports):  38%|███▊      | 2694/7111 [10:09<16:04,  4.58it/s]

Gaps (ex-reports):  38%|███▊      | 2695/7111 [10:10<15:40,  4.70it/s]

Gaps (ex-reports):  38%|███▊      | 2696/7111 [10:10<15:12,  4.84it/s]

Gaps (ex-reports):  38%|███▊      | 2697/7111 [10:10<15:20,  4.79it/s]

Gaps (ex-reports):  38%|███▊      | 2698/7111 [10:10<15:15,  4.82it/s]

Gaps (ex-reports):  38%|███▊      | 2699/7111 [10:10<15:42,  4.68it/s]

Gaps (ex-reports):  38%|███▊      | 2700/7111 [10:11<15:25,  4.77it/s]

Gaps (ex-reports):  38%|███▊      | 2701/7111 [10:11<15:31,  4.73it/s]

Gaps (ex-reports):  38%|███▊      | 2702/7111 [10:11<15:34,  4.72it/s]

Gaps (ex-reports):  38%|███▊      | 2703/7111 [10:11<15:23,  4.77it/s]

Gaps (ex-reports):  38%|███▊      | 2704/7111 [10:11<15:19,  4.79it/s]

Gaps (ex-reports):  38%|███▊      | 2705/7111 [10:12<15:21,  4.78it/s]

Gaps (ex-reports):  38%|███▊      | 2706/7111 [10:12<15:07,  4.86it/s]

Gaps (ex-reports):  38%|███▊      | 2707/7111 [10:12<15:06,  4.86it/s]

Gaps (ex-reports):  38%|███▊      | 2708/7111 [10:12<15:03,  4.87it/s]

Gaps (ex-reports):  38%|███▊      | 2709/7111 [10:12<15:06,  4.86it/s]

Gaps (ex-reports):  38%|███▊      | 2710/7111 [10:13<15:12,  4.82it/s]

Gaps (ex-reports):  38%|███▊      | 2711/7111 [10:13<15:20,  4.78it/s]

Gaps (ex-reports):  38%|███▊      | 2712/7111 [10:13<15:05,  4.86it/s]

Gaps (ex-reports):  38%|███▊      | 2713/7111 [10:13<14:55,  4.91it/s]

Gaps (ex-reports):  38%|███▊      | 2714/7111 [10:13<14:52,  4.93it/s]

Gaps (ex-reports):  38%|███▊      | 2715/7111 [10:14<14:36,  5.02it/s]

Gaps (ex-reports):  38%|███▊      | 2716/7111 [10:14<14:21,  5.10it/s]

Gaps (ex-reports):  38%|███▊      | 2717/7111 [10:14<14:24,  5.09it/s]

Gaps (ex-reports):  38%|███▊      | 2718/7111 [10:14<14:38,  5.00it/s]

Gaps (ex-reports):  38%|███▊      | 2719/7111 [10:14<14:57,  4.89it/s]

Gaps (ex-reports):  38%|███▊      | 2720/7111 [10:15<22:40,  3.23it/s]

Gaps (ex-reports):  38%|███▊      | 2721/7111 [10:15<20:25,  3.58it/s]

Gaps (ex-reports):  38%|███▊      | 2722/7111 [10:15<18:44,  3.90it/s]

Gaps (ex-reports):  38%|███▊      | 2723/7111 [10:16<17:36,  4.15it/s]

Gaps (ex-reports):  38%|███▊      | 2724/7111 [10:16<16:43,  4.37it/s]

Gaps (ex-reports):  38%|███▊      | 2725/7111 [10:16<16:24,  4.45it/s]

Gaps (ex-reports):  38%|███▊      | 2726/7111 [10:16<16:02,  4.55it/s]

Gaps (ex-reports):  38%|███▊      | 2727/7111 [10:16<15:35,  4.69it/s]

Gaps (ex-reports):  38%|███▊      | 2728/7111 [10:17<15:32,  4.70it/s]

Gaps (ex-reports):  38%|███▊      | 2729/7111 [10:17<15:24,  4.74it/s]

Gaps (ex-reports):  38%|███▊      | 2730/7111 [10:17<15:38,  4.67it/s]

Gaps (ex-reports):  38%|███▊      | 2731/7111 [10:17<15:32,  4.70it/s]

Gaps (ex-reports):  38%|███▊      | 2732/7111 [10:18<15:11,  4.80it/s]

Gaps (ex-reports):  38%|███▊      | 2733/7111 [10:18<15:03,  4.85it/s]

Gaps (ex-reports):  38%|███▊      | 2734/7111 [10:18<15:12,  4.80it/s]

Gaps (ex-reports):  38%|███▊      | 2735/7111 [10:18<15:16,  4.78it/s]

Gaps (ex-reports):  38%|███▊      | 2736/7111 [10:18<15:17,  4.77it/s]

Gaps (ex-reports):  38%|███▊      | 2737/7111 [10:19<15:16,  4.77it/s]

Gaps (ex-reports):  39%|███▊      | 2738/7111 [10:19<15:02,  4.85it/s]

Gaps (ex-reports):  39%|███▊      | 2739/7111 [10:19<14:43,  4.95it/s]

Gaps (ex-reports):  39%|███▊      | 2740/7111 [10:19<14:49,  4.91it/s]

Gaps (ex-reports):  39%|███▊      | 2741/7111 [10:19<14:33,  5.00it/s]

Gaps (ex-reports):  39%|███▊      | 2742/7111 [10:20<14:33,  5.00it/s]

Gaps (ex-reports):  39%|███▊      | 2743/7111 [10:20<14:47,  4.92it/s]

Gaps (ex-reports):  39%|███▊      | 2744/7111 [10:20<26:12,  2.78it/s]

Gaps (ex-reports):  39%|███▊      | 2745/7111 [10:21<23:02,  3.16it/s]

Gaps (ex-reports):  39%|███▊      | 2746/7111 [10:21<21:03,  3.45it/s]

Gaps (ex-reports):  39%|███▊      | 2747/7111 [10:21<22:49,  3.19it/s]

Gaps (ex-reports):  39%|███▊      | 2748/7111 [10:21<20:10,  3.60it/s]

Gaps (ex-reports):  39%|███▊      | 2749/7111 [10:22<19:03,  3.81it/s]

Gaps (ex-reports):  39%|███▊      | 2750/7111 [10:22<17:46,  4.09it/s]

Gaps (ex-reports):  39%|███▊      | 2751/7111 [10:22<17:04,  4.26it/s]

Gaps (ex-reports):  39%|███▊      | 2752/7111 [10:22<16:27,  4.42it/s]

Gaps (ex-reports):  39%|███▊      | 2753/7111 [10:23<15:37,  4.65it/s]

Gaps (ex-reports):  39%|███▊      | 2754/7111 [10:23<15:23,  4.72it/s]

Gaps (ex-reports):  39%|███▊      | 2755/7111 [10:23<15:09,  4.79it/s]

Gaps (ex-reports):  39%|███▉      | 2756/7111 [10:23<15:03,  4.82it/s]

Gaps (ex-reports):  39%|███▉      | 2757/7111 [10:23<15:02,  4.82it/s]

Gaps (ex-reports):  39%|███▉      | 2758/7111 [10:24<14:59,  4.84it/s]

Gaps (ex-reports):  39%|███▉      | 2759/7111 [10:24<14:44,  4.92it/s]

Gaps (ex-reports):  39%|███▉      | 2760/7111 [10:24<14:32,  4.98it/s]

Gaps (ex-reports):  39%|███▉      | 2761/7111 [10:24<14:48,  4.90it/s]

Gaps (ex-reports):  39%|███▉      | 2762/7111 [10:24<14:58,  4.84it/s]

Gaps (ex-reports):  39%|███▉      | 2763/7111 [10:25<14:39,  4.94it/s]

Gaps (ex-reports):  39%|███▉      | 2764/7111 [10:25<14:22,  5.04it/s]

Gaps (ex-reports):  39%|███▉      | 2765/7111 [10:25<14:52,  4.87it/s]

Gaps (ex-reports):  39%|███▉      | 2766/7111 [10:25<14:53,  4.86it/s]

Gaps (ex-reports):  39%|███▉      | 2767/7111 [10:25<14:44,  4.91it/s]

Gaps (ex-reports):  39%|███▉      | 2768/7111 [10:26<14:36,  4.95it/s]

Gaps (ex-reports):  39%|███▉      | 2769/7111 [10:27<38:19,  1.89it/s]

Gaps (ex-reports):  39%|███▉      | 2770/7111 [10:27<31:16,  2.31it/s]

Gaps (ex-reports):  39%|███▉      | 2771/7111 [10:27<26:02,  2.78it/s]

Gaps (ex-reports):  39%|███▉      | 2772/7111 [10:27<22:29,  3.22it/s]

Gaps (ex-reports):  39%|███▉      | 2773/7111 [10:28<20:10,  3.58it/s]

Gaps (ex-reports):  39%|███▉      | 2774/7111 [10:28<18:15,  3.96it/s]

Gaps (ex-reports):  39%|███▉      | 2775/7111 [10:28<17:00,  4.25it/s]

Gaps (ex-reports):  39%|███▉      | 2776/7111 [10:28<16:19,  4.42it/s]

Gaps (ex-reports):  39%|███▉      | 2777/7111 [10:28<15:32,  4.65it/s]

Gaps (ex-reports):  39%|███▉      | 2778/7111 [10:29<15:20,  4.71it/s]

Gaps (ex-reports):  39%|███▉      | 2779/7111 [10:29<14:55,  4.84it/s]

Gaps (ex-reports):  39%|███▉      | 2780/7111 [10:29<14:38,  4.93it/s]

Gaps (ex-reports):  39%|███▉      | 2781/7111 [10:29<14:19,  5.04it/s]

Gaps (ex-reports):  39%|███▉      | 2782/7111 [10:29<14:48,  4.87it/s]

Gaps (ex-reports):  39%|███▉      | 2783/7111 [10:30<14:29,  4.98it/s]

Gaps (ex-reports):  39%|███▉      | 2784/7111 [10:30<14:35,  4.94it/s]

Gaps (ex-reports):  39%|███▉      | 2785/7111 [10:30<14:40,  4.91it/s]

Gaps (ex-reports):  39%|███▉      | 2786/7111 [10:30<14:44,  4.89it/s]

Gaps (ex-reports):  39%|███▉      | 2787/7111 [10:30<14:47,  4.87it/s]

Gaps (ex-reports):  39%|███▉      | 2788/7111 [10:31<15:08,  4.76it/s]

Gaps (ex-reports):  39%|███▉      | 2789/7111 [10:31<14:41,  4.90it/s]

Gaps (ex-reports):  39%|███▉      | 2790/7111 [10:31<15:24,  4.67it/s]

Gaps (ex-reports):  39%|███▉      | 2791/7111 [10:31<15:20,  4.69it/s]

Gaps (ex-reports):  39%|███▉      | 2792/7111 [10:32<14:55,  4.82it/s]

Gaps (ex-reports):  39%|███▉      | 2793/7111 [10:32<15:08,  4.75it/s]

Gaps (ex-reports):  39%|███▉      | 2794/7111 [10:32<21:40,  3.32it/s]

Gaps (ex-reports):  39%|███▉      | 2795/7111 [10:33<26:54,  2.67it/s]

Gaps (ex-reports):  39%|███▉      | 2796/7111 [10:33<23:11,  3.10it/s]

Gaps (ex-reports):  39%|███▉      | 2797/7111 [10:33<20:27,  3.51it/s]

Gaps (ex-reports):  39%|███▉      | 2798/7111 [10:33<18:36,  3.86it/s]

Gaps (ex-reports):  39%|███▉      | 2799/7111 [10:34<17:25,  4.12it/s]

Gaps (ex-reports):  39%|███▉      | 2800/7111 [10:34<16:40,  4.31it/s]

Gaps (ex-reports):  39%|███▉      | 2801/7111 [10:34<15:54,  4.51it/s]

Gaps (ex-reports):  39%|███▉      | 2802/7111 [10:34<15:30,  4.63it/s]

Gaps (ex-reports):  39%|███▉      | 2803/7111 [10:34<15:03,  4.77it/s]

Gaps (ex-reports):  39%|███▉      | 2804/7111 [10:35<15:16,  4.70it/s]

Gaps (ex-reports):  39%|███▉      | 2805/7111 [10:35<14:56,  4.81it/s]

Gaps (ex-reports):  39%|███▉      | 2806/7111 [10:35<15:08,  4.74it/s]

Gaps (ex-reports):  39%|███▉      | 2807/7111 [10:35<14:46,  4.85it/s]

Gaps (ex-reports):  39%|███▉      | 2808/7111 [10:35<14:28,  4.95it/s]

Gaps (ex-reports):  40%|███▉      | 2809/7111 [10:36<14:33,  4.93it/s]

Gaps (ex-reports):  40%|███▉      | 2810/7111 [10:36<14:15,  5.03it/s]

Gaps (ex-reports):  40%|███▉      | 2811/7111 [10:36<14:13,  5.04it/s]

Gaps (ex-reports):  40%|███▉      | 2812/7111 [10:36<14:04,  5.09it/s]

Gaps (ex-reports):  40%|███▉      | 2813/7111 [10:36<13:59,  5.12it/s]

Gaps (ex-reports):  40%|███▉      | 2814/7111 [10:37<13:56,  5.14it/s]

Gaps (ex-reports):  40%|███▉      | 2815/7111 [10:37<13:50,  5.17it/s]

Gaps (ex-reports):  40%|███▉      | 2816/7111 [10:37<14:28,  4.95it/s]

Gaps (ex-reports):  40%|███▉      | 2817/7111 [10:37<14:25,  4.96it/s]

Gaps (ex-reports):  40%|███▉      | 2818/7111 [10:37<14:30,  4.93it/s]

Gaps (ex-reports):  40%|███▉      | 2819/7111 [10:38<14:55,  4.79it/s]

Gaps (ex-reports):  40%|███▉      | 2820/7111 [10:38<14:31,  4.92it/s]

Gaps (ex-reports):  40%|███▉      | 2821/7111 [10:38<14:17,  5.00it/s]

Gaps (ex-reports):  40%|███▉      | 2822/7111 [10:38<14:07,  5.06it/s]

Gaps (ex-reports):  40%|███▉      | 2823/7111 [10:38<14:24,  4.96it/s]

Gaps (ex-reports):  40%|███▉      | 2824/7111 [10:39<14:32,  4.91it/s]

Gaps (ex-reports):  40%|███▉      | 2825/7111 [10:39<14:18,  4.99it/s]

Gaps (ex-reports):  40%|███▉      | 2826/7111 [10:39<14:21,  4.97it/s]

Gaps (ex-reports):  40%|███▉      | 2827/7111 [10:39<14:25,  4.95it/s]

Gaps (ex-reports):  40%|███▉      | 2828/7111 [10:39<14:19,  4.98it/s]

Gaps (ex-reports):  40%|███▉      | 2829/7111 [10:40<14:17,  4.99it/s]

Gaps (ex-reports):  40%|███▉      | 2830/7111 [10:40<14:04,  5.07it/s]

Gaps (ex-reports):  40%|███▉      | 2831/7111 [10:40<14:16,  5.00it/s]

Gaps (ex-reports):  40%|███▉      | 2832/7111 [10:40<14:20,  4.97it/s]

Gaps (ex-reports):  40%|███▉      | 2833/7111 [10:41<21:42,  3.28it/s]

Gaps (ex-reports):  40%|███▉      | 2834/7111 [10:41<19:35,  3.64it/s]

Gaps (ex-reports):  40%|███▉      | 2835/7111 [10:41<18:09,  3.92it/s]

Gaps (ex-reports):  40%|███▉      | 2836/7111 [10:41<17:06,  4.17it/s]

Gaps (ex-reports):  40%|███▉      | 2837/7111 [10:42<16:44,  4.26it/s]

Gaps (ex-reports):  40%|███▉      | 2838/7111 [10:42<16:07,  4.42it/s]

Gaps (ex-reports):  40%|███▉      | 2839/7111 [10:43<28:21,  2.51it/s]

Gaps (ex-reports):  40%|███▉      | 2840/7111 [10:43<24:15,  2.93it/s]

Gaps (ex-reports):  40%|███▉      | 2841/7111 [10:43<21:15,  3.35it/s]

Gaps (ex-reports):  40%|███▉      | 2842/7111 [10:43<19:23,  3.67it/s]

Gaps (ex-reports):  40%|███▉      | 2843/7111 [10:43<17:51,  3.98it/s]

Gaps (ex-reports):  40%|███▉      | 2844/7111 [10:44<16:53,  4.21it/s]

Gaps (ex-reports):  40%|████      | 2845/7111 [10:44<16:16,  4.37it/s]

Gaps (ex-reports):  40%|████      | 2846/7111 [10:44<15:38,  4.55it/s]

Gaps (ex-reports):  40%|████      | 2847/7111 [10:44<15:08,  4.69it/s]

Gaps (ex-reports):  40%|████      | 2848/7111 [10:44<15:06,  4.70it/s]

Gaps (ex-reports):  40%|████      | 2849/7111 [10:45<14:40,  4.84it/s]

Gaps (ex-reports):  40%|████      | 2850/7111 [10:45<14:48,  4.79it/s]

Gaps (ex-reports):  40%|████      | 2851/7111 [10:45<14:47,  4.80it/s]

Gaps (ex-reports):  40%|████      | 2852/7111 [10:45<14:31,  4.88it/s]

Gaps (ex-reports):  40%|████      | 2853/7111 [10:45<14:28,  4.90it/s]

Gaps (ex-reports):  40%|████      | 2854/7111 [10:46<14:21,  4.94it/s]

Gaps (ex-reports):  40%|████      | 2855/7111 [10:46<17:02,  4.16it/s]

Gaps (ex-reports):  40%|████      | 2856/7111 [10:46<16:06,  4.40it/s]

Gaps (ex-reports):  40%|████      | 2857/7111 [10:46<15:36,  4.54it/s]

Gaps (ex-reports):  40%|████      | 2858/7111 [10:47<15:02,  4.71it/s]

Gaps (ex-reports):  40%|████      | 2859/7111 [10:47<14:39,  4.83it/s]

Gaps (ex-reports):  40%|████      | 2860/7111 [10:47<14:36,  4.85it/s]

Gaps (ex-reports):  40%|████      | 2861/7111 [10:47<14:22,  4.93it/s]

Gaps (ex-reports):  40%|████      | 2862/7111 [10:47<14:33,  4.86it/s]

Gaps (ex-reports):  40%|████      | 2863/7111 [10:48<14:25,  4.91it/s]

Gaps (ex-reports):  40%|████      | 2864/7111 [10:48<14:13,  4.98it/s]

Gaps (ex-reports):  40%|████      | 2865/7111 [10:48<14:09,  5.00it/s]

Gaps (ex-reports):  40%|████      | 2866/7111 [10:48<14:11,  4.99it/s]

Gaps (ex-reports):  40%|████      | 2867/7111 [10:48<14:22,  4.92it/s]

Gaps (ex-reports):  40%|████      | 2868/7111 [10:49<14:07,  5.00it/s]

Gaps (ex-reports):  40%|████      | 2869/7111 [10:49<13:54,  5.08it/s]

Gaps (ex-reports):  40%|████      | 2870/7111 [10:49<13:48,  5.12it/s]

Gaps (ex-reports):  40%|████      | 2871/7111 [10:49<13:46,  5.13it/s]

Gaps (ex-reports):  40%|████      | 2872/7111 [10:49<13:44,  5.14it/s]

Gaps (ex-reports):  40%|████      | 2873/7111 [10:50<13:42,  5.15it/s]

Gaps (ex-reports):  40%|████      | 2874/7111 [10:50<13:38,  5.17it/s]

Gaps (ex-reports):  40%|████      | 2875/7111 [10:50<14:00,  5.04it/s]

Gaps (ex-reports):  40%|████      | 2876/7111 [10:50<14:16,  4.95it/s]

Gaps (ex-reports):  40%|████      | 2877/7111 [10:50<14:20,  4.92it/s]

Gaps (ex-reports):  40%|████      | 2878/7111 [10:51<14:41,  4.80it/s]

Gaps (ex-reports):  40%|████      | 2879/7111 [10:51<14:25,  4.89it/s]

Gaps (ex-reports):  41%|████      | 2880/7111 [10:51<14:07,  4.99it/s]

Gaps (ex-reports):  41%|████      | 2881/7111 [10:51<13:54,  5.07it/s]

Gaps (ex-reports):  41%|████      | 2882/7111 [10:51<13:49,  5.10it/s]

Gaps (ex-reports):  41%|████      | 2883/7111 [10:52<13:52,  5.08it/s]

Gaps (ex-reports):  41%|████      | 2884/7111 [10:52<14:59,  4.70it/s]

Gaps (ex-reports):  41%|████      | 2885/7111 [10:52<14:37,  4.81it/s]

Gaps (ex-reports):  41%|████      | 2886/7111 [10:52<14:48,  4.76it/s]

Gaps (ex-reports):  41%|████      | 2887/7111 [10:52<14:30,  4.85it/s]

Gaps (ex-reports):  41%|████      | 2888/7111 [10:53<22:56,  3.07it/s]

Gaps (ex-reports):  41%|████      | 2889/7111 [10:53<20:17,  3.47it/s]

Gaps (ex-reports):  41%|████      | 2890/7111 [10:53<18:43,  3.76it/s]

Gaps (ex-reports):  41%|████      | 2891/7111 [10:54<17:34,  4.00it/s]

Gaps (ex-reports):  41%|████      | 2892/7111 [10:54<16:33,  4.25it/s]

Gaps (ex-reports):  41%|████      | 2893/7111 [10:54<15:48,  4.45it/s]

Gaps (ex-reports):  41%|████      | 2894/7111 [10:54<15:26,  4.55it/s]

Gaps (ex-reports):  41%|████      | 2895/7111 [10:54<14:55,  4.71it/s]

Gaps (ex-reports):  41%|████      | 2896/7111 [10:55<14:43,  4.77it/s]

Gaps (ex-reports):  41%|████      | 2897/7111 [10:55<14:26,  4.86it/s]

Gaps (ex-reports):  41%|████      | 2898/7111 [10:55<14:30,  4.84it/s]

Gaps (ex-reports):  41%|████      | 2899/7111 [10:55<14:21,  4.89it/s]

Gaps (ex-reports):  41%|████      | 2900/7111 [10:55<14:39,  4.79it/s]

Gaps (ex-reports):  41%|████      | 2901/7111 [10:56<14:35,  4.81it/s]

Gaps (ex-reports):  41%|████      | 2902/7111 [10:56<14:10,  4.95it/s]

Gaps (ex-reports):  41%|████      | 2903/7111 [10:56<14:41,  4.77it/s]

Gaps (ex-reports):  41%|████      | 2904/7111 [10:56<14:42,  4.77it/s]

Gaps (ex-reports):  41%|████      | 2905/7111 [10:57<14:38,  4.79it/s]

Gaps (ex-reports):  41%|████      | 2906/7111 [10:57<14:43,  4.76it/s]

Gaps (ex-reports):  41%|████      | 2907/7111 [10:57<14:33,  4.81it/s]

Gaps (ex-reports):  41%|████      | 2908/7111 [10:57<14:30,  4.83it/s]

Gaps (ex-reports):  41%|████      | 2909/7111 [10:57<14:13,  4.92it/s]

Gaps (ex-reports):  41%|████      | 2910/7111 [10:58<14:25,  4.85it/s]

Gaps (ex-reports):  41%|████      | 2911/7111 [10:58<14:44,  4.75it/s]

Gaps (ex-reports):  41%|████      | 2912/7111 [10:58<14:39,  4.77it/s]

Gaps (ex-reports):  41%|████      | 2913/7111 [10:58<14:55,  4.69it/s]

Gaps (ex-reports):  41%|████      | 2914/7111 [10:58<14:46,  4.74it/s]

Gaps (ex-reports):  41%|████      | 2915/7111 [10:59<14:54,  4.69it/s]

Gaps (ex-reports):  41%|████      | 2916/7111 [10:59<14:34,  4.80it/s]

Gaps (ex-reports):  41%|████      | 2917/7111 [10:59<14:22,  4.86it/s]

Gaps (ex-reports):  41%|████      | 2918/7111 [10:59<14:14,  4.90it/s]

Gaps (ex-reports):  41%|████      | 2919/7111 [10:59<14:08,  4.94it/s]

Gaps (ex-reports):  41%|████      | 2920/7111 [11:00<14:21,  4.87it/s]

Gaps (ex-reports):  41%|████      | 2921/7111 [11:00<14:06,  4.95it/s]

Gaps (ex-reports):  41%|████      | 2922/7111 [11:00<14:32,  4.80it/s]

Gaps (ex-reports):  41%|████      | 2923/7111 [11:00<14:20,  4.87it/s]

Gaps (ex-reports):  41%|████      | 2924/7111 [11:00<14:33,  4.80it/s]

Gaps (ex-reports):  41%|████      | 2925/7111 [11:01<14:43,  4.74it/s]

Gaps (ex-reports):  41%|████      | 2926/7111 [11:01<14:35,  4.78it/s]

Gaps (ex-reports):  41%|████      | 2927/7111 [11:01<14:38,  4.76it/s]

Gaps (ex-reports):  41%|████      | 2928/7111 [11:01<14:36,  4.77it/s]

Gaps (ex-reports):  41%|████      | 2929/7111 [11:02<14:39,  4.76it/s]

Gaps (ex-reports):  41%|████      | 2930/7111 [11:02<14:26,  4.82it/s]

Gaps (ex-reports):  41%|████      | 2931/7111 [11:02<14:34,  4.78it/s]

Gaps (ex-reports):  41%|████      | 2932/7111 [11:02<14:39,  4.75it/s]

Gaps (ex-reports):  41%|████      | 2933/7111 [11:02<14:25,  4.83it/s]

Gaps (ex-reports):  41%|████▏     | 2934/7111 [11:03<14:20,  4.85it/s]

Gaps (ex-reports):  41%|████▏     | 2935/7111 [11:03<14:09,  4.92it/s]

Gaps (ex-reports):  41%|████▏     | 2936/7111 [11:03<13:54,  5.00it/s]

Gaps (ex-reports):  41%|████▏     | 2937/7111 [11:03<14:03,  4.95it/s]

Gaps (ex-reports):  41%|████▏     | 2938/7111 [11:03<14:17,  4.87it/s]

Gaps (ex-reports):  41%|████▏     | 2939/7111 [11:04<14:10,  4.91it/s]

Gaps (ex-reports):  41%|████▏     | 2940/7111 [11:04<13:55,  4.99it/s]

Gaps (ex-reports):  41%|████▏     | 2941/7111 [11:04<13:51,  5.01it/s]

Gaps (ex-reports):  41%|████▏     | 2942/7111 [11:04<13:55,  4.99it/s]

Gaps (ex-reports):  41%|████▏     | 2943/7111 [11:04<14:07,  4.92it/s]

Gaps (ex-reports):  41%|████▏     | 2944/7111 [11:05<14:07,  4.92it/s]

Gaps (ex-reports):  41%|████▏     | 2945/7111 [11:05<14:25,  4.81it/s]

Gaps (ex-reports):  41%|████▏     | 2946/7111 [11:05<14:16,  4.86it/s]

Gaps (ex-reports):  41%|████▏     | 2947/7111 [11:05<14:16,  4.86it/s]

Gaps (ex-reports):  41%|████▏     | 2948/7111 [11:05<13:58,  4.96it/s]

Gaps (ex-reports):  41%|████▏     | 2949/7111 [11:06<13:44,  5.05it/s]

Gaps (ex-reports):  41%|████▏     | 2950/7111 [11:06<13:59,  4.96it/s]

Gaps (ex-reports):  41%|████▏     | 2951/7111 [11:06<13:54,  4.99it/s]

Gaps (ex-reports):  42%|████▏     | 2952/7111 [11:06<13:41,  5.06it/s]

Gaps (ex-reports):  42%|████▏     | 2953/7111 [11:06<14:10,  4.89it/s]

Gaps (ex-reports):  42%|████▏     | 2954/7111 [11:07<14:01,  4.94it/s]

Gaps (ex-reports):  42%|████▏     | 2955/7111 [11:07<15:19,  4.52it/s]

Gaps (ex-reports):  42%|████▏     | 2956/7111 [11:07<14:52,  4.66it/s]

Gaps (ex-reports):  42%|████▏     | 2957/7111 [11:07<14:52,  4.65it/s]

Gaps (ex-reports):  42%|████▏     | 2958/7111 [11:07<14:30,  4.77it/s]

Gaps (ex-reports):  42%|████▏     | 2959/7111 [11:08<14:10,  4.88it/s]

Gaps (ex-reports):  42%|████▏     | 2960/7111 [11:08<14:22,  4.81it/s]

Gaps (ex-reports):  42%|████▏     | 2961/7111 [11:08<14:26,  4.79it/s]

Gaps (ex-reports):  42%|████▏     | 2962/7111 [11:08<14:21,  4.82it/s]

Gaps (ex-reports):  42%|████▏     | 2963/7111 [11:09<14:30,  4.76it/s]

Gaps (ex-reports):  42%|████▏     | 2964/7111 [11:09<14:28,  4.77it/s]

Gaps (ex-reports):  42%|████▏     | 2965/7111 [11:09<14:18,  4.83it/s]

Gaps (ex-reports):  42%|████▏     | 2966/7111 [11:09<14:04,  4.91it/s]

Gaps (ex-reports):  42%|████▏     | 2967/7111 [11:09<14:15,  4.85it/s]

Gaps (ex-reports):  42%|████▏     | 2968/7111 [11:10<14:22,  4.81it/s]

Gaps (ex-reports):  42%|████▏     | 2969/7111 [11:10<14:09,  4.88it/s]

Gaps (ex-reports):  42%|████▏     | 2970/7111 [11:10<14:30,  4.76it/s]

Gaps (ex-reports):  42%|████▏     | 2971/7111 [11:10<14:16,  4.84it/s]

Gaps (ex-reports):  42%|████▏     | 2972/7111 [11:10<14:31,  4.75it/s]

Gaps (ex-reports):  42%|████▏     | 2973/7111 [11:11<14:12,  4.85it/s]

Gaps (ex-reports):  42%|████▏     | 2974/7111 [11:11<15:00,  4.60it/s]

Gaps (ex-reports):  42%|████▏     | 2975/7111 [11:11<14:51,  4.64it/s]

Gaps (ex-reports):  42%|████▏     | 2976/7111 [11:11<14:34,  4.73it/s]

Gaps (ex-reports):  42%|████▏     | 2977/7111 [11:11<14:24,  4.78it/s]

Gaps (ex-reports):  42%|████▏     | 2978/7111 [11:12<14:13,  4.84it/s]

Gaps (ex-reports):  42%|████▏     | 2979/7111 [11:12<14:07,  4.87it/s]

Gaps (ex-reports):  42%|████▏     | 2980/7111 [11:12<14:20,  4.80it/s]

Gaps (ex-reports):  42%|████▏     | 2981/7111 [11:12<14:20,  4.80it/s]

Gaps (ex-reports):  42%|████▏     | 2982/7111 [11:12<14:11,  4.85it/s]

Gaps (ex-reports):  42%|████▏     | 2983/7111 [11:13<13:59,  4.92it/s]

Gaps (ex-reports):  42%|████▏     | 2984/7111 [11:13<14:14,  4.83it/s]

Gaps (ex-reports):  42%|████▏     | 2985/7111 [11:13<14:02,  4.90it/s]

Gaps (ex-reports):  42%|████▏     | 2986/7111 [11:13<14:07,  4.87it/s]

Gaps (ex-reports):  42%|████▏     | 2987/7111 [11:13<14:13,  4.83it/s]

Gaps (ex-reports):  42%|████▏     | 2988/7111 [11:14<14:20,  4.79it/s]

Gaps (ex-reports):  42%|████▏     | 2989/7111 [11:14<14:03,  4.89it/s]

Gaps (ex-reports):  42%|████▏     | 2990/7111 [11:14<14:29,  4.74it/s]

Gaps (ex-reports):  42%|████▏     | 2991/7111 [11:14<14:06,  4.87it/s]

Gaps (ex-reports):  42%|████▏     | 2992/7111 [11:15<13:54,  4.94it/s]

Gaps (ex-reports):  42%|████▏     | 2993/7111 [11:15<13:56,  4.92it/s]

Gaps (ex-reports):  42%|████▏     | 2994/7111 [11:15<13:44,  4.99it/s]

Gaps (ex-reports):  42%|████▏     | 2995/7111 [11:15<14:02,  4.89it/s]

Gaps (ex-reports):  42%|████▏     | 2996/7111 [11:16<30:54,  2.22it/s]

Gaps (ex-reports):  42%|████▏     | 2997/7111 [11:16<25:47,  2.66it/s]

Gaps (ex-reports):  42%|████▏     | 2998/7111 [11:17<22:33,  3.04it/s]

Gaps (ex-reports):  42%|████▏     | 2999/7111 [11:17<19:46,  3.46it/s]

Gaps (ex-reports):  42%|████▏     | 3000/7111 [11:17<18:07,  3.78it/s]

Gaps (ex-reports):  42%|████▏     | 3001/7111 [11:17<16:52,  4.06it/s]

Gaps (ex-reports):  42%|████▏     | 3002/7111 [11:17<16:02,  4.27it/s]

Gaps (ex-reports):  42%|████▏     | 3003/7111 [11:18<15:22,  4.45it/s]

Gaps (ex-reports):  42%|████▏     | 3004/7111 [11:18<14:54,  4.59it/s]

Gaps (ex-reports):  42%|████▏     | 3005/7111 [11:18<14:38,  4.68it/s]

Gaps (ex-reports):  42%|████▏     | 3006/7111 [11:19<27:24,  2.50it/s]

Gaps (ex-reports):  42%|████▏     | 3007/7111 [11:19<23:13,  2.95it/s]

Gaps (ex-reports):  42%|████▏     | 3008/7111 [11:19<20:28,  3.34it/s]

Gaps (ex-reports):  42%|████▏     | 3009/7111 [11:19<18:34,  3.68it/s]

Gaps (ex-reports):  42%|████▏     | 3010/7111 [11:20<17:33,  3.89it/s]

Gaps (ex-reports):  42%|████▏     | 3011/7111 [11:20<16:49,  4.06it/s]

Gaps (ex-reports):  42%|████▏     | 3012/7111 [11:20<15:46,  4.33it/s]

Gaps (ex-reports):  42%|████▏     | 3013/7111 [11:20<15:19,  4.45it/s]

Gaps (ex-reports):  42%|████▏     | 3014/7111 [11:20<15:00,  4.55it/s]

Gaps (ex-reports):  42%|████▏     | 3015/7111 [11:21<14:51,  4.59it/s]

Gaps (ex-reports):  42%|████▏     | 3016/7111 [11:21<14:20,  4.76it/s]

Gaps (ex-reports):  42%|████▏     | 3017/7111 [11:21<14:11,  4.81it/s]

Gaps (ex-reports):  42%|████▏     | 3018/7111 [11:21<14:10,  4.81it/s]

Gaps (ex-reports):  42%|████▏     | 3019/7111 [11:22<13:52,  4.91it/s]

Gaps (ex-reports):  42%|████▏     | 3020/7111 [11:22<14:05,  4.84it/s]

Gaps (ex-reports):  42%|████▏     | 3021/7111 [11:22<13:57,  4.89it/s]

Gaps (ex-reports):  42%|████▏     | 3022/7111 [11:22<14:08,  4.82it/s]

Gaps (ex-reports):  43%|████▎     | 3023/7111 [11:22<14:03,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3024/7111 [11:23<13:45,  4.95it/s]

Gaps (ex-reports):  43%|████▎     | 3025/7111 [11:23<13:30,  5.04it/s]

Gaps (ex-reports):  43%|████▎     | 3026/7111 [11:23<13:25,  5.07it/s]

Gaps (ex-reports):  43%|████▎     | 3027/7111 [11:23<14:02,  4.85it/s]

Gaps (ex-reports):  43%|████▎     | 3028/7111 [11:23<14:00,  4.86it/s]

Gaps (ex-reports):  43%|████▎     | 3029/7111 [11:24<14:03,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3030/7111 [11:24<14:11,  4.79it/s]

Gaps (ex-reports):  43%|████▎     | 3031/7111 [11:24<14:16,  4.76it/s]

Gaps (ex-reports):  43%|████▎     | 3032/7111 [11:24<13:54,  4.89it/s]

Gaps (ex-reports):  43%|████▎     | 3033/7111 [11:24<14:09,  4.80it/s]

Gaps (ex-reports):  43%|████▎     | 3034/7111 [11:25<14:01,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3035/7111 [11:25<14:14,  4.77it/s]

Gaps (ex-reports):  43%|████▎     | 3036/7111 [11:25<15:16,  4.45it/s]

Gaps (ex-reports):  43%|████▎     | 3037/7111 [11:25<15:03,  4.51it/s]

Gaps (ex-reports):  43%|████▎     | 3038/7111 [11:25<14:42,  4.62it/s]

Gaps (ex-reports):  43%|████▎     | 3039/7111 [11:26<14:17,  4.75it/s]

Gaps (ex-reports):  43%|████▎     | 3040/7111 [11:26<14:09,  4.79it/s]

Gaps (ex-reports):  43%|████▎     | 3041/7111 [11:26<13:49,  4.91it/s]

Gaps (ex-reports):  43%|████▎     | 3042/7111 [11:26<13:36,  4.98it/s]

Gaps (ex-reports):  43%|████▎     | 3043/7111 [11:26<13:33,  5.00it/s]

Gaps (ex-reports):  43%|████▎     | 3044/7111 [11:27<13:36,  4.98it/s]

Gaps (ex-reports):  43%|████▎     | 3045/7111 [11:27<13:42,  4.94it/s]

Gaps (ex-reports):  43%|████▎     | 3046/7111 [11:27<13:31,  5.01it/s]

Gaps (ex-reports):  43%|████▎     | 3047/7111 [11:27<13:18,  5.09it/s]

Gaps (ex-reports):  43%|████▎     | 3048/7111 [11:27<13:17,  5.09it/s]

Gaps (ex-reports):  43%|████▎     | 3049/7111 [11:28<13:26,  5.04it/s]

Gaps (ex-reports):  43%|████▎     | 3050/7111 [11:28<13:18,  5.08it/s]

Gaps (ex-reports):  43%|████▎     | 3051/7111 [11:28<13:22,  5.06it/s]

Gaps (ex-reports):  43%|████▎     | 3052/7111 [11:28<13:13,  5.11it/s]

Gaps (ex-reports):  43%|████▎     | 3053/7111 [11:28<13:33,  4.99it/s]

Gaps (ex-reports):  43%|████▎     | 3054/7111 [11:29<13:43,  4.92it/s]

Gaps (ex-reports):  43%|████▎     | 3055/7111 [11:29<13:43,  4.92it/s]

Gaps (ex-reports):  43%|████▎     | 3056/7111 [11:29<14:00,  4.83it/s]

Gaps (ex-reports):  43%|████▎     | 3057/7111 [11:29<13:47,  4.90it/s]

Gaps (ex-reports):  43%|████▎     | 3058/7111 [11:29<13:57,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3059/7111 [11:30<13:51,  4.87it/s]

Gaps (ex-reports):  43%|████▎     | 3060/7111 [11:30<13:54,  4.86it/s]

Gaps (ex-reports):  43%|████▎     | 3061/7111 [11:30<13:56,  4.84it/s]

Gaps (ex-reports):  43%|████▎     | 3062/7111 [11:30<13:51,  4.87it/s]

Gaps (ex-reports):  43%|████▎     | 3063/7111 [11:31<13:52,  4.86it/s]

Gaps (ex-reports):  43%|████▎     | 3064/7111 [11:31<13:44,  4.91it/s]

Gaps (ex-reports):  43%|████▎     | 3065/7111 [11:31<13:42,  4.92it/s]

Gaps (ex-reports):  43%|████▎     | 3066/7111 [11:31<13:33,  4.97it/s]

Gaps (ex-reports):  43%|████▎     | 3067/7111 [11:31<13:41,  4.92it/s]

Gaps (ex-reports):  43%|████▎     | 3068/7111 [11:32<13:47,  4.88it/s]

Gaps (ex-reports):  43%|████▎     | 3069/7111 [11:32<14:11,  4.75it/s]

Gaps (ex-reports):  43%|████▎     | 3070/7111 [11:32<14:06,  4.78it/s]

Gaps (ex-reports):  43%|████▎     | 3071/7111 [11:32<14:11,  4.75it/s]

Gaps (ex-reports):  43%|████▎     | 3072/7111 [11:32<14:00,  4.80it/s]

Gaps (ex-reports):  43%|████▎     | 3073/7111 [11:33<16:25,  4.10it/s]

Gaps (ex-reports):  43%|████▎     | 3074/7111 [11:33<15:26,  4.36it/s]

Gaps (ex-reports):  43%|████▎     | 3075/7111 [11:33<15:05,  4.45it/s]

Gaps (ex-reports):  43%|████▎     | 3076/7111 [11:33<14:40,  4.58it/s]

Gaps (ex-reports):  43%|████▎     | 3077/7111 [11:34<14:30,  4.64it/s]

Gaps (ex-reports):  43%|████▎     | 3078/7111 [11:34<14:02,  4.79it/s]

Gaps (ex-reports):  43%|████▎     | 3079/7111 [11:34<13:39,  4.92it/s]

Gaps (ex-reports):  43%|████▎     | 3080/7111 [11:34<13:30,  4.97it/s]

Gaps (ex-reports):  43%|████▎     | 3081/7111 [11:34<13:28,  4.98it/s]

Gaps (ex-reports):  43%|████▎     | 3082/7111 [11:35<13:40,  4.91it/s]

Gaps (ex-reports):  43%|████▎     | 3083/7111 [11:35<13:33,  4.95it/s]

Gaps (ex-reports):  43%|████▎     | 3084/7111 [11:35<13:33,  4.95it/s]

Gaps (ex-reports):  43%|████▎     | 3085/7111 [11:35<13:43,  4.89it/s]

Gaps (ex-reports):  43%|████▎     | 3086/7111 [11:35<13:43,  4.89it/s]

Gaps (ex-reports):  43%|████▎     | 3087/7111 [11:36<13:31,  4.96it/s]

Gaps (ex-reports):  43%|████▎     | 3088/7111 [11:36<13:36,  4.93it/s]

Gaps (ex-reports):  43%|████▎     | 3089/7111 [11:36<13:47,  4.86it/s]

Gaps (ex-reports):  43%|████▎     | 3090/7111 [11:36<13:49,  4.85it/s]

Gaps (ex-reports):  43%|████▎     | 3091/7111 [11:36<13:46,  4.86it/s]

Gaps (ex-reports):  43%|████▎     | 3092/7111 [11:37<13:41,  4.89it/s]

Gaps (ex-reports):  43%|████▎     | 3093/7111 [11:37<13:39,  4.90it/s]

Gaps (ex-reports):  44%|████▎     | 3094/7111 [11:37<13:27,  4.97it/s]

Gaps (ex-reports):  44%|████▎     | 3095/7111 [11:37<13:30,  4.96it/s]

Gaps (ex-reports):  44%|████▎     | 3096/7111 [11:37<13:19,  5.02it/s]

Gaps (ex-reports):  44%|████▎     | 3097/7111 [11:38<13:12,  5.06it/s]

Gaps (ex-reports):  44%|████▎     | 3098/7111 [11:38<13:23,  5.00it/s]

Gaps (ex-reports):  44%|████▎     | 3099/7111 [11:38<13:10,  5.07it/s]

Gaps (ex-reports):  44%|████▎     | 3100/7111 [11:38<16:16,  4.11it/s]

Gaps (ex-reports):  44%|████▎     | 3101/7111 [11:38<15:13,  4.39it/s]

Gaps (ex-reports):  44%|████▎     | 3102/7111 [11:39<15:11,  4.40it/s]

Gaps (ex-reports):  44%|████▎     | 3103/7111 [11:39<14:39,  4.56it/s]

Gaps (ex-reports):  44%|████▎     | 3104/7111 [11:39<14:53,  4.48it/s]

Gaps (ex-reports):  44%|████▎     | 3105/7111 [11:39<14:20,  4.66it/s]

Gaps (ex-reports):  44%|████▎     | 3106/7111 [11:40<13:56,  4.79it/s]

Gaps (ex-reports):  44%|████▎     | 3107/7111 [11:40<13:59,  4.77it/s]

Gaps (ex-reports):  44%|████▎     | 3108/7111 [11:40<13:56,  4.79it/s]

Gaps (ex-reports):  44%|████▎     | 3109/7111 [11:40<13:53,  4.80it/s]

Gaps (ex-reports):  44%|████▎     | 3110/7111 [11:40<14:00,  4.76it/s]

Gaps (ex-reports):  44%|████▎     | 3111/7111 [11:41<13:44,  4.85it/s]

Gaps (ex-reports):  44%|████▍     | 3112/7111 [11:41<13:46,  4.84it/s]

Gaps (ex-reports):  44%|████▍     | 3113/7111 [11:41<13:33,  4.91it/s]

Gaps (ex-reports):  44%|████▍     | 3114/7111 [11:41<13:40,  4.87it/s]

Gaps (ex-reports):  44%|████▍     | 3115/7111 [11:41<13:27,  4.95it/s]

Gaps (ex-reports):  44%|████▍     | 3116/7111 [11:42<13:21,  4.99it/s]

Gaps (ex-reports):  44%|████▍     | 3117/7111 [11:42<13:23,  4.97it/s]

Gaps (ex-reports):  44%|████▍     | 3118/7111 [11:42<13:45,  4.84it/s]

Gaps (ex-reports):  44%|████▍     | 3119/7111 [11:42<13:48,  4.82it/s]

Gaps (ex-reports):  44%|████▍     | 3120/7111 [11:42<14:17,  4.66it/s]

Gaps (ex-reports):  44%|████▍     | 3121/7111 [11:43<14:04,  4.73it/s]

Gaps (ex-reports):  44%|████▍     | 3122/7111 [11:43<13:39,  4.87it/s]

Gaps (ex-reports):  44%|████▍     | 3123/7111 [11:43<13:29,  4.93it/s]

Gaps (ex-reports):  44%|████▍     | 3124/7111 [11:43<13:32,  4.91it/s]

Gaps (ex-reports):  44%|████▍     | 3125/7111 [11:43<13:27,  4.94it/s]

Gaps (ex-reports):  44%|████▍     | 3126/7111 [11:44<20:21,  3.26it/s]

Gaps (ex-reports):  44%|████▍     | 3127/7111 [11:44<18:06,  3.67it/s]

Gaps (ex-reports):  44%|████▍     | 3128/7111 [11:44<16:36,  4.00it/s]

Gaps (ex-reports):  44%|████▍     | 3129/7111 [11:45<15:35,  4.25it/s]

Gaps (ex-reports):  44%|████▍     | 3130/7111 [11:45<15:01,  4.41it/s]

Gaps (ex-reports):  44%|████▍     | 3131/7111 [11:45<14:48,  4.48it/s]

Gaps (ex-reports):  44%|████▍     | 3132/7111 [11:45<14:16,  4.65it/s]

Gaps (ex-reports):  44%|████▍     | 3133/7111 [11:45<13:56,  4.75it/s]

Gaps (ex-reports):  44%|████▍     | 3134/7111 [11:46<14:08,  4.69it/s]

Gaps (ex-reports):  44%|████▍     | 3135/7111 [11:46<14:02,  4.72it/s]

Gaps (ex-reports):  44%|████▍     | 3136/7111 [11:46<13:44,  4.82it/s]

Gaps (ex-reports):  44%|████▍     | 3137/7111 [11:46<13:41,  4.83it/s]

Gaps (ex-reports):  44%|████▍     | 3138/7111 [11:46<13:58,  4.74it/s]

Gaps (ex-reports):  44%|████▍     | 3139/7111 [11:47<13:41,  4.83it/s]

Gaps (ex-reports):  44%|████▍     | 3140/7111 [11:47<13:44,  4.82it/s]

Gaps (ex-reports):  44%|████▍     | 3141/7111 [11:47<14:06,  4.69it/s]

Gaps (ex-reports):  44%|████▍     | 3142/7111 [11:47<13:52,  4.77it/s]

Gaps (ex-reports):  44%|████▍     | 3143/7111 [11:48<14:03,  4.71it/s]

Gaps (ex-reports):  44%|████▍     | 3144/7111 [11:48<13:38,  4.84it/s]

Gaps (ex-reports):  44%|████▍     | 3145/7111 [11:48<15:54,  4.16it/s]

Gaps (ex-reports):  44%|████▍     | 3146/7111 [11:48<15:03,  4.39it/s]

Gaps (ex-reports):  44%|████▍     | 3147/7111 [11:48<14:15,  4.63it/s]

Gaps (ex-reports):  44%|████▍     | 3148/7111 [11:49<14:29,  4.56it/s]

Gaps (ex-reports):  44%|████▍     | 3149/7111 [11:49<14:27,  4.57it/s]

Gaps (ex-reports):  44%|████▍     | 3150/7111 [11:49<14:06,  4.68it/s]

Gaps (ex-reports):  44%|████▍     | 3151/7111 [11:49<14:19,  4.61it/s]

Gaps (ex-reports):  44%|████▍     | 3152/7111 [11:49<14:10,  4.65it/s]

Gaps (ex-reports):  44%|████▍     | 3153/7111 [11:50<14:03,  4.69it/s]

Gaps (ex-reports):  44%|████▍     | 3154/7111 [11:50<13:47,  4.78it/s]

Gaps (ex-reports):  44%|████▍     | 3155/7111 [11:50<13:30,  4.88it/s]

Gaps (ex-reports):  44%|████▍     | 3156/7111 [11:50<13:29,  4.89it/s]

Gaps (ex-reports):  44%|████▍     | 3157/7111 [11:50<13:14,  4.97it/s]

Gaps (ex-reports):  44%|████▍     | 3158/7111 [11:51<13:42,  4.81it/s]

Gaps (ex-reports):  44%|████▍     | 3159/7111 [11:51<13:29,  4.88it/s]

Gaps (ex-reports):  44%|████▍     | 3160/7111 [11:51<13:33,  4.86it/s]

Gaps (ex-reports):  44%|████▍     | 3161/7111 [11:51<13:32,  4.86it/s]

Gaps (ex-reports):  44%|████▍     | 3162/7111 [11:52<30:30,  2.16it/s]

Gaps (ex-reports):  44%|████▍     | 3163/7111 [11:53<25:19,  2.60it/s]

Gaps (ex-reports):  44%|████▍     | 3164/7111 [11:53<21:54,  3.00it/s]

Gaps (ex-reports):  45%|████▍     | 3165/7111 [11:53<19:26,  3.38it/s]

Gaps (ex-reports):  45%|████▍     | 3166/7111 [11:53<19:07,  3.44it/s]

Gaps (ex-reports):  45%|████▍     | 3167/7111 [11:53<17:32,  3.75it/s]

Gaps (ex-reports):  45%|████▍     | 3168/7111 [11:54<16:21,  4.02it/s]

Gaps (ex-reports):  45%|████▍     | 3169/7111 [11:54<15:33,  4.22it/s]

Gaps (ex-reports):  45%|████▍     | 3170/7111 [11:54<16:08,  4.07it/s]

Gaps (ex-reports):  45%|████▍     | 3171/7111 [11:54<15:33,  4.22it/s]

Gaps (ex-reports):  45%|████▍     | 3172/7111 [11:55<14:42,  4.46it/s]

Gaps (ex-reports):  45%|████▍     | 3173/7111 [11:55<14:26,  4.54it/s]

Gaps (ex-reports):  45%|████▍     | 3174/7111 [11:55<14:02,  4.68it/s]

Gaps (ex-reports):  45%|████▍     | 3175/7111 [11:55<13:58,  4.69it/s]

Gaps (ex-reports):  45%|████▍     | 3176/7111 [11:55<13:35,  4.83it/s]

Gaps (ex-reports):  45%|████▍     | 3177/7111 [11:56<13:24,  4.89it/s]

Gaps (ex-reports):  45%|████▍     | 3178/7111 [11:57<33:38,  1.95it/s]

Gaps (ex-reports):  45%|████▍     | 3179/7111 [11:57<27:39,  2.37it/s]

Gaps (ex-reports):  45%|████▍     | 3180/7111 [11:57<23:26,  2.80it/s]

Gaps (ex-reports):  45%|████▍     | 3181/7111 [11:57<20:47,  3.15it/s]

Gaps (ex-reports):  45%|████▍     | 3182/7111 [11:58<18:40,  3.51it/s]

Gaps (ex-reports):  45%|████▍     | 3183/7111 [11:58<17:04,  3.84it/s]

Gaps (ex-reports):  45%|████▍     | 3184/7111 [11:58<16:24,  3.99it/s]

Gaps (ex-reports):  45%|████▍     | 3185/7111 [11:58<15:39,  4.18it/s]

Gaps (ex-reports):  45%|████▍     | 3186/7111 [11:59<15:18,  4.27it/s]

Gaps (ex-reports):  45%|████▍     | 3187/7111 [11:59<14:53,  4.39it/s]

Gaps (ex-reports):  45%|████▍     | 3188/7111 [11:59<14:18,  4.57it/s]

Gaps (ex-reports):  45%|████▍     | 3189/7111 [11:59<13:48,  4.73it/s]

Gaps (ex-reports):  45%|████▍     | 3190/7111 [11:59<13:48,  4.73it/s]

Gaps (ex-reports):  45%|████▍     | 3191/7111 [12:00<13:44,  4.75it/s]

Gaps (ex-reports):  45%|████▍     | 3192/7111 [12:00<13:38,  4.79it/s]

Gaps (ex-reports):  45%|████▍     | 3193/7111 [12:00<13:15,  4.93it/s]

Gaps (ex-reports):  45%|████▍     | 3194/7111 [12:00<13:04,  4.99it/s]

Gaps (ex-reports):  45%|████▍     | 3195/7111 [12:00<13:01,  5.01it/s]

Gaps (ex-reports):  45%|████▍     | 3196/7111 [12:01<12:55,  5.05it/s]

Gaps (ex-reports):  45%|████▍     | 3197/7111 [12:01<12:52,  5.06it/s]

Gaps (ex-reports):  45%|████▍     | 3198/7111 [12:01<13:02,  5.00it/s]

Gaps (ex-reports):  45%|████▍     | 3199/7111 [12:01<17:48,  3.66it/s]

Gaps (ex-reports):  45%|████▌     | 3200/7111 [12:02<33:32,  1.94it/s]

Gaps (ex-reports):  45%|████▌     | 3201/7111 [12:03<27:35,  2.36it/s]

Gaps (ex-reports):  45%|████▌     | 3202/7111 [12:03<23:15,  2.80it/s]

Gaps (ex-reports):  45%|████▌     | 3203/7111 [12:03<20:27,  3.18it/s]

Gaps (ex-reports):  45%|████▌     | 3204/7111 [12:03<18:17,  3.56it/s]

Gaps (ex-reports):  45%|████▌     | 3205/7111 [12:04<16:46,  3.88it/s]

Gaps (ex-reports):  45%|████▌     | 3206/7111 [12:04<15:35,  4.18it/s]

Gaps (ex-reports):  45%|████▌     | 3207/7111 [12:04<14:54,  4.36it/s]

Gaps (ex-reports):  45%|████▌     | 3208/7111 [12:04<14:29,  4.49it/s]

Gaps (ex-reports):  45%|████▌     | 3209/7111 [12:04<14:03,  4.62it/s]

Gaps (ex-reports):  45%|████▌     | 3210/7111 [12:05<13:47,  4.72it/s]

Gaps (ex-reports):  45%|████▌     | 3211/7111 [12:05<13:23,  4.85it/s]

Gaps (ex-reports):  45%|████▌     | 3212/7111 [12:05<13:08,  4.95it/s]

Gaps (ex-reports):  45%|████▌     | 3213/7111 [12:05<13:01,  4.98it/s]

Gaps (ex-reports):  45%|████▌     | 3214/7111 [12:05<13:26,  4.83it/s]

Gaps (ex-reports):  45%|████▌     | 3215/7111 [12:06<13:41,  4.74it/s]

Gaps (ex-reports):  45%|████▌     | 3216/7111 [12:06<23:04,  2.81it/s]

Gaps (ex-reports):  45%|████▌     | 3217/7111 [12:06<20:15,  3.20it/s]

Gaps (ex-reports):  45%|████▌     | 3218/7111 [12:07<18:03,  3.59it/s]

Gaps (ex-reports):  45%|████▌     | 3219/7111 [12:07<16:25,  3.95it/s]

Gaps (ex-reports):  45%|████▌     | 3220/7111 [12:07<15:30,  4.18it/s]

Gaps (ex-reports):  45%|████▌     | 3221/7111 [12:07<14:35,  4.44it/s]

Gaps (ex-reports):  45%|████▌     | 3222/7111 [12:07<14:16,  4.54it/s]

Gaps (ex-reports):  45%|████▌     | 3223/7111 [12:08<13:56,  4.65it/s]

Gaps (ex-reports):  45%|████▌     | 3224/7111 [12:08<13:41,  4.73it/s]

Gaps (ex-reports):  45%|████▌     | 3225/7111 [12:08<13:51,  4.68it/s]

Gaps (ex-reports):  45%|████▌     | 3226/7111 [12:08<13:22,  4.84it/s]

Gaps (ex-reports):  45%|████▌     | 3227/7111 [12:08<13:29,  4.80it/s]

Gaps (ex-reports):  45%|████▌     | 3228/7111 [12:09<13:22,  4.84it/s]

Gaps (ex-reports):  45%|████▌     | 3229/7111 [12:09<13:35,  4.76it/s]

Gaps (ex-reports):  45%|████▌     | 3230/7111 [12:09<13:25,  4.82it/s]

Gaps (ex-reports):  45%|████▌     | 3231/7111 [12:09<13:30,  4.79it/s]

Gaps (ex-reports):  45%|████▌     | 3232/7111 [12:10<13:26,  4.81it/s]

Gaps (ex-reports):  45%|████▌     | 3233/7111 [12:10<13:26,  4.81it/s]

Gaps (ex-reports):  45%|████▌     | 3234/7111 [12:10<13:17,  4.86it/s]

Gaps (ex-reports):  45%|████▌     | 3235/7111 [12:10<12:59,  4.97it/s]

Gaps (ex-reports):  46%|████▌     | 3236/7111 [12:10<13:07,  4.92it/s]

Gaps (ex-reports):  46%|████▌     | 3237/7111 [12:11<12:57,  4.98it/s]

Gaps (ex-reports):  46%|████▌     | 3238/7111 [12:11<13:08,  4.91it/s]

Gaps (ex-reports):  46%|████▌     | 3239/7111 [12:11<23:32,  2.74it/s]

Gaps (ex-reports):  46%|████▌     | 3240/7111 [12:12<20:22,  3.17it/s]

Gaps (ex-reports):  46%|████▌     | 3241/7111 [12:12<18:24,  3.50it/s]

Gaps (ex-reports):  46%|████▌     | 3242/7111 [12:12<16:48,  3.83it/s]

Gaps (ex-reports):  46%|████▌     | 3243/7111 [12:12<15:45,  4.09it/s]

Gaps (ex-reports):  46%|████▌     | 3244/7111 [12:13<15:09,  4.25it/s]

Gaps (ex-reports):  46%|████▌     | 3245/7111 [12:13<14:30,  4.44it/s]

Gaps (ex-reports):  46%|████▌     | 3246/7111 [12:13<14:04,  4.58it/s]

Gaps (ex-reports):  46%|████▌     | 3247/7111 [12:13<14:09,  4.55it/s]

Gaps (ex-reports):  46%|████▌     | 3248/7111 [12:13<14:03,  4.58it/s]

Gaps (ex-reports):  46%|████▌     | 3249/7111 [12:14<13:47,  4.67it/s]

Gaps (ex-reports):  46%|████▌     | 3250/7111 [12:14<13:27,  4.78it/s]

Gaps (ex-reports):  46%|████▌     | 3251/7111 [12:14<13:08,  4.89it/s]

Gaps (ex-reports):  46%|████▌     | 3252/7111 [12:14<13:10,  4.88it/s]

Gaps (ex-reports):  46%|████▌     | 3253/7111 [12:14<12:54,  4.98it/s]

Gaps (ex-reports):  46%|████▌     | 3254/7111 [12:15<12:46,  5.03it/s]

Gaps (ex-reports):  46%|████▌     | 3255/7111 [12:15<13:05,  4.91it/s]

Gaps (ex-reports):  46%|████▌     | 3256/7111 [12:15<12:54,  4.98it/s]

Gaps (ex-reports):  46%|████▌     | 3257/7111 [12:15<13:01,  4.93it/s]

Gaps (ex-reports):  46%|████▌     | 3258/7111 [12:15<13:03,  4.92it/s]

Gaps (ex-reports):  46%|████▌     | 3259/7111 [12:16<13:19,  4.82it/s]

Gaps (ex-reports):  46%|████▌     | 3260/7111 [12:16<15:38,  4.10it/s]

Gaps (ex-reports):  46%|████▌     | 3261/7111 [12:16<14:47,  4.34it/s]

Gaps (ex-reports):  46%|████▌     | 3262/7111 [12:16<14:15,  4.50it/s]

Gaps (ex-reports):  46%|████▌     | 3263/7111 [12:17<13:49,  4.64it/s]

Gaps (ex-reports):  46%|████▌     | 3264/7111 [12:17<13:45,  4.66it/s]

Gaps (ex-reports):  46%|████▌     | 3265/7111 [12:17<13:29,  4.75it/s]

Gaps (ex-reports):  46%|████▌     | 3266/7111 [12:17<14:04,  4.55it/s]

Gaps (ex-reports):  46%|████▌     | 3267/7111 [12:17<13:49,  4.63it/s]

Gaps (ex-reports):  46%|████▌     | 3268/7111 [12:18<13:29,  4.75it/s]

Gaps (ex-reports):  46%|████▌     | 3269/7111 [12:18<13:28,  4.75it/s]

Gaps (ex-reports):  46%|████▌     | 3270/7111 [12:18<19:40,  3.25it/s]

Gaps (ex-reports):  46%|████▌     | 3271/7111 [12:19<17:39,  3.62it/s]

Gaps (ex-reports):  46%|████▌     | 3272/7111 [12:19<16:02,  3.99it/s]

Gaps (ex-reports):  46%|████▌     | 3273/7111 [12:19<15:28,  4.13it/s]

Gaps (ex-reports):  46%|████▌     | 3274/7111 [12:19<14:50,  4.31it/s]

Gaps (ex-reports):  46%|████▌     | 3275/7111 [12:19<14:22,  4.45it/s]

Gaps (ex-reports):  46%|████▌     | 3276/7111 [12:20<14:03,  4.55it/s]

Gaps (ex-reports):  46%|████▌     | 3277/7111 [12:20<13:55,  4.59it/s]

Gaps (ex-reports):  46%|████▌     | 3278/7111 [12:20<13:38,  4.68it/s]

Gaps (ex-reports):  46%|████▌     | 3279/7111 [12:20<13:48,  4.63it/s]

Gaps (ex-reports):  46%|████▌     | 3280/7111 [12:20<13:35,  4.70it/s]

Gaps (ex-reports):  46%|████▌     | 3281/7111 [12:21<13:18,  4.80it/s]

Gaps (ex-reports):  46%|████▌     | 3282/7111 [12:21<13:29,  4.73it/s]

Gaps (ex-reports):  46%|████▌     | 3283/7111 [12:21<13:08,  4.86it/s]

Gaps (ex-reports):  46%|████▌     | 3284/7111 [12:21<12:53,  4.95it/s]

Gaps (ex-reports):  46%|████▌     | 3285/7111 [12:21<12:46,  4.99it/s]

Gaps (ex-reports):  46%|████▌     | 3286/7111 [12:22<12:32,  5.08it/s]

Gaps (ex-reports):  46%|████▌     | 3287/7111 [12:22<12:26,  5.12it/s]

Gaps (ex-reports):  46%|████▌     | 3288/7111 [12:22<12:39,  5.04it/s]

Gaps (ex-reports):  46%|████▋     | 3289/7111 [12:22<12:38,  5.04it/s]

Gaps (ex-reports):  46%|████▋     | 3290/7111 [12:22<12:45,  4.99it/s]

Gaps (ex-reports):  46%|████▋     | 3291/7111 [12:23<12:43,  5.01it/s]

Gaps (ex-reports):  46%|████▋     | 3292/7111 [12:23<13:02,  4.88it/s]

Gaps (ex-reports):  46%|████▋     | 3293/7111 [12:23<13:00,  4.89it/s]

Gaps (ex-reports):  46%|████▋     | 3294/7111 [12:23<13:27,  4.73it/s]

Gaps (ex-reports):  46%|████▋     | 3295/7111 [12:23<13:38,  4.66it/s]

Gaps (ex-reports):  46%|████▋     | 3296/7111 [12:24<13:30,  4.71it/s]

Gaps (ex-reports):  46%|████▋     | 3297/7111 [12:24<13:09,  4.83it/s]

Gaps (ex-reports):  46%|████▋     | 3298/7111 [12:24<12:58,  4.90it/s]

Gaps (ex-reports):  46%|████▋     | 3299/7111 [12:24<13:04,  4.86it/s]

Gaps (ex-reports):  46%|████▋     | 3300/7111 [12:24<13:05,  4.85it/s]

Gaps (ex-reports):  46%|████▋     | 3301/7111 [12:25<13:14,  4.80it/s]

Gaps (ex-reports):  46%|████▋     | 3302/7111 [12:25<12:57,  4.90it/s]

Gaps (ex-reports):  46%|████▋     | 3303/7111 [12:25<12:46,  4.97it/s]

Gaps (ex-reports):  46%|████▋     | 3304/7111 [12:25<12:34,  5.05it/s]

Gaps (ex-reports):  46%|████▋     | 3305/7111 [12:25<12:38,  5.01it/s]

Gaps (ex-reports):  46%|████▋     | 3306/7111 [12:26<12:39,  5.01it/s]

Gaps (ex-reports):  47%|████▋     | 3307/7111 [12:26<12:34,  5.04it/s]

Gaps (ex-reports):  47%|████▋     | 3308/7111 [12:26<12:49,  4.94it/s]

Gaps (ex-reports):  47%|████▋     | 3309/7111 [12:26<12:52,  4.92it/s]

Gaps (ex-reports):  47%|████▋     | 3310/7111 [12:27<13:11,  4.80it/s]

Gaps (ex-reports):  47%|████▋     | 3311/7111 [12:27<12:56,  4.89it/s]

Gaps (ex-reports):  47%|████▋     | 3312/7111 [12:27<12:51,  4.93it/s]

Gaps (ex-reports):  47%|████▋     | 3313/7111 [12:27<12:41,  4.99it/s]

Gaps (ex-reports):  47%|████▋     | 3314/7111 [12:27<13:05,  4.84it/s]

Gaps (ex-reports):  47%|████▋     | 3315/7111 [12:28<13:07,  4.82it/s]

Gaps (ex-reports):  47%|████▋     | 3316/7111 [12:28<12:47,  4.94it/s]

Gaps (ex-reports):  47%|████▋     | 3317/7111 [12:28<12:46,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3318/7111 [12:28<13:00,  4.86it/s]

Gaps (ex-reports):  47%|████▋     | 3319/7111 [12:28<13:24,  4.72it/s]

Gaps (ex-reports):  47%|████▋     | 3320/7111 [12:29<13:21,  4.73it/s]

Gaps (ex-reports):  47%|████▋     | 3321/7111 [12:29<13:14,  4.77it/s]

Gaps (ex-reports):  47%|████▋     | 3322/7111 [12:29<13:05,  4.82it/s]

Gaps (ex-reports):  47%|████▋     | 3323/7111 [12:29<12:58,  4.87it/s]

Gaps (ex-reports):  47%|████▋     | 3324/7111 [12:29<13:06,  4.82it/s]

Gaps (ex-reports):  47%|████▋     | 3325/7111 [12:30<12:59,  4.85it/s]

Gaps (ex-reports):  47%|████▋     | 3326/7111 [12:30<13:04,  4.82it/s]

Gaps (ex-reports):  47%|████▋     | 3327/7111 [12:30<13:15,  4.75it/s]

Gaps (ex-reports):  47%|████▋     | 3328/7111 [12:30<13:22,  4.71it/s]

Gaps (ex-reports):  47%|████▋     | 3329/7111 [12:30<13:10,  4.79it/s]

Gaps (ex-reports):  47%|████▋     | 3330/7111 [12:31<13:00,  4.84it/s]

Gaps (ex-reports):  47%|████▋     | 3331/7111 [12:31<12:48,  4.92it/s]

Gaps (ex-reports):  47%|████▋     | 3332/7111 [12:31<12:46,  4.93it/s]

Gaps (ex-reports):  47%|████▋     | 3333/7111 [12:31<12:42,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3334/7111 [12:31<12:29,  5.04it/s]

Gaps (ex-reports):  47%|████▋     | 3335/7111 [12:32<12:58,  4.85it/s]

Gaps (ex-reports):  47%|████▋     | 3336/7111 [12:32<12:53,  4.88it/s]

Gaps (ex-reports):  47%|████▋     | 3337/7111 [12:32<12:51,  4.89it/s]

Gaps (ex-reports):  47%|████▋     | 3338/7111 [12:32<12:50,  4.89it/s]

Gaps (ex-reports):  47%|████▋     | 3339/7111 [12:32<13:04,  4.81it/s]

Gaps (ex-reports):  47%|████▋     | 3340/7111 [12:33<12:57,  4.85it/s]

Gaps (ex-reports):  47%|████▋     | 3341/7111 [12:33<13:15,  4.74it/s]

Gaps (ex-reports):  47%|████▋     | 3342/7111 [12:33<13:32,  4.64it/s]

Gaps (ex-reports):  47%|████▋     | 3343/7111 [12:33<13:22,  4.70it/s]

Gaps (ex-reports):  47%|████▋     | 3344/7111 [12:34<13:50,  4.54it/s]

Gaps (ex-reports):  47%|████▋     | 3345/7111 [12:34<13:44,  4.57it/s]

Gaps (ex-reports):  47%|████▋     | 3346/7111 [12:34<13:26,  4.67it/s]

Gaps (ex-reports):  47%|████▋     | 3347/7111 [12:34<13:14,  4.74it/s]

Gaps (ex-reports):  47%|████▋     | 3348/7111 [12:34<13:17,  4.72it/s]

Gaps (ex-reports):  47%|████▋     | 3349/7111 [12:35<13:27,  4.66it/s]

Gaps (ex-reports):  47%|████▋     | 3350/7111 [12:35<13:03,  4.80it/s]

Gaps (ex-reports):  47%|████▋     | 3351/7111 [12:35<13:00,  4.82it/s]

Gaps (ex-reports):  47%|████▋     | 3352/7111 [12:35<13:00,  4.82it/s]

Gaps (ex-reports):  47%|████▋     | 3353/7111 [12:35<12:43,  4.92it/s]

Gaps (ex-reports):  47%|████▋     | 3354/7111 [12:36<12:45,  4.91it/s]

Gaps (ex-reports):  47%|████▋     | 3355/7111 [12:36<12:39,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3356/7111 [12:36<12:47,  4.89it/s]

Gaps (ex-reports):  47%|████▋     | 3357/7111 [12:36<12:53,  4.85it/s]

Gaps (ex-reports):  47%|████▋     | 3358/7111 [12:36<12:38,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3359/7111 [12:37<12:44,  4.91it/s]

Gaps (ex-reports):  47%|████▋     | 3360/7111 [12:37<12:36,  4.96it/s]

Gaps (ex-reports):  47%|████▋     | 3361/7111 [12:37<12:28,  5.01it/s]

Gaps (ex-reports):  47%|████▋     | 3362/7111 [12:37<12:34,  4.97it/s]

Gaps (ex-reports):  47%|████▋     | 3363/7111 [12:37<12:36,  4.95it/s]

Gaps (ex-reports):  47%|████▋     | 3364/7111 [12:38<12:44,  4.90it/s]

Gaps (ex-reports):  47%|████▋     | 3365/7111 [12:38<12:48,  4.88it/s]

Gaps (ex-reports):  47%|████▋     | 3366/7111 [12:38<13:12,  4.73it/s]

Gaps (ex-reports):  47%|████▋     | 3367/7111 [12:38<12:56,  4.82it/s]

Gaps (ex-reports):  47%|████▋     | 3368/7111 [12:39<13:12,  4.72it/s]

Gaps (ex-reports):  47%|████▋     | 3369/7111 [12:39<13:12,  4.72it/s]

Gaps (ex-reports):  47%|████▋     | 3370/7111 [12:39<13:06,  4.76it/s]

Gaps (ex-reports):  47%|████▋     | 3371/7111 [12:39<13:22,  4.66it/s]

Gaps (ex-reports):  47%|████▋     | 3372/7111 [12:39<13:12,  4.72it/s]

Gaps (ex-reports):  47%|████▋     | 3373/7111 [12:40<13:07,  4.75it/s]

Gaps (ex-reports):  47%|████▋     | 3374/7111 [12:40<12:52,  4.84it/s]

Gaps (ex-reports):  47%|████▋     | 3375/7111 [12:40<12:51,  4.84it/s]

Gaps (ex-reports):  47%|████▋     | 3376/7111 [12:40<12:54,  4.82it/s]

Gaps (ex-reports):  47%|████▋     | 3377/7111 [12:40<13:01,  4.78it/s]

Gaps (ex-reports):  48%|████▊     | 3378/7111 [12:41<12:59,  4.79it/s]

Gaps (ex-reports):  48%|████▊     | 3379/7111 [12:41<12:43,  4.89it/s]

Gaps (ex-reports):  48%|████▊     | 3380/7111 [12:41<12:35,  4.94it/s]

Gaps (ex-reports):  48%|████▊     | 3381/7111 [12:41<12:48,  4.85it/s]

Gaps (ex-reports):  48%|████▊     | 3382/7111 [12:42<24:07,  2.58it/s]

Gaps (ex-reports):  48%|████▊     | 3383/7111 [12:42<20:45,  2.99it/s]

Gaps (ex-reports):  48%|████▊     | 3384/7111 [12:42<18:42,  3.32it/s]

Gaps (ex-reports):  48%|████▊     | 3385/7111 [12:43<16:53,  3.68it/s]

Gaps (ex-reports):  48%|████▊     | 3386/7111 [12:43<15:20,  4.05it/s]

Gaps (ex-reports):  48%|████▊     | 3387/7111 [12:43<14:26,  4.30it/s]

Gaps (ex-reports):  48%|████▊     | 3388/7111 [12:43<13:49,  4.49it/s]

Gaps (ex-reports):  48%|████▊     | 3389/7111 [12:43<13:35,  4.57it/s]

Gaps (ex-reports):  48%|████▊     | 3390/7111 [12:44<13:05,  4.74it/s]

Gaps (ex-reports):  48%|████▊     | 3391/7111 [12:44<13:07,  4.72it/s]

Gaps (ex-reports):  48%|████▊     | 3392/7111 [12:44<13:03,  4.75it/s]

Gaps (ex-reports):  48%|████▊     | 3393/7111 [12:44<12:58,  4.78it/s]

Gaps (ex-reports):  48%|████▊     | 3394/7111 [12:44<12:40,  4.89it/s]

Gaps (ex-reports):  48%|████▊     | 3395/7111 [12:45<12:46,  4.85it/s]

Gaps (ex-reports):  48%|████▊     | 3396/7111 [12:45<12:48,  4.84it/s]

Gaps (ex-reports):  48%|████▊     | 3397/7111 [12:45<12:46,  4.84it/s]

Gaps (ex-reports):  48%|████▊     | 3398/7111 [12:45<12:58,  4.77it/s]

Gaps (ex-reports):  48%|████▊     | 3399/7111 [12:46<12:48,  4.83it/s]

Gaps (ex-reports):  48%|████▊     | 3400/7111 [12:46<12:39,  4.89it/s]

Gaps (ex-reports):  48%|████▊     | 3401/7111 [12:46<12:39,  4.88it/s]

Gaps (ex-reports):  48%|████▊     | 3402/7111 [12:46<12:44,  4.85it/s]

Gaps (ex-reports):  48%|████▊     | 3403/7111 [12:46<12:36,  4.90it/s]

Gaps (ex-reports):  48%|████▊     | 3404/7111 [12:47<12:28,  4.95it/s]

Gaps (ex-reports):  48%|████▊     | 3405/7111 [12:47<12:31,  4.93it/s]

Gaps (ex-reports):  48%|████▊     | 3406/7111 [12:47<12:36,  4.90it/s]

Gaps (ex-reports):  48%|████▊     | 3407/7111 [12:47<12:27,  4.96it/s]

Gaps (ex-reports):  48%|████▊     | 3408/7111 [12:47<12:18,  5.01it/s]

Gaps (ex-reports):  48%|████▊     | 3409/7111 [12:48<12:26,  4.96it/s]

Gaps (ex-reports):  48%|████▊     | 3410/7111 [12:48<12:19,  5.00it/s]

Gaps (ex-reports):  48%|████▊     | 3411/7111 [12:48<12:22,  4.98it/s]

Gaps (ex-reports):  48%|████▊     | 3412/7111 [12:48<12:08,  5.08it/s]

Gaps (ex-reports):  48%|████▊     | 3413/7111 [12:49<19:24,  3.18it/s]

Gaps (ex-reports):  48%|████▊     | 3414/7111 [12:49<17:11,  3.58it/s]

Gaps (ex-reports):  48%|████▊     | 3415/7111 [12:49<16:47,  3.67it/s]

Gaps (ex-reports):  48%|████▊     | 3416/7111 [12:49<15:48,  3.90it/s]

Gaps (ex-reports):  48%|████▊     | 3417/7111 [12:50<14:41,  4.19it/s]

Gaps (ex-reports):  48%|████▊     | 3418/7111 [12:50<14:11,  4.34it/s]

Gaps (ex-reports):  48%|████▊     | 3419/7111 [12:50<13:45,  4.47it/s]

Gaps (ex-reports):  48%|████▊     | 3420/7111 [12:50<13:37,  4.52it/s]

Gaps (ex-reports):  48%|████▊     | 3421/7111 [12:50<13:16,  4.63it/s]

Gaps (ex-reports):  48%|████▊     | 3422/7111 [12:51<13:25,  4.58it/s]

Gaps (ex-reports):  48%|████▊     | 3423/7111 [12:51<13:01,  4.72it/s]

Gaps (ex-reports):  48%|████▊     | 3424/7111 [12:51<13:04,  4.70it/s]

Gaps (ex-reports):  48%|████▊     | 3425/7111 [12:52<24:17,  2.53it/s]

Gaps (ex-reports):  48%|████▊     | 3426/7111 [12:52<20:43,  2.96it/s]

Gaps (ex-reports):  48%|████▊     | 3427/7111 [12:52<18:03,  3.40it/s]

Gaps (ex-reports):  48%|████▊     | 3428/7111 [12:52<16:20,  3.76it/s]

Gaps (ex-reports):  48%|████▊     | 3429/7111 [12:53<15:14,  4.03it/s]

Gaps (ex-reports):  48%|████▊     | 3430/7111 [12:53<14:14,  4.31it/s]

Gaps (ex-reports):  48%|████▊     | 3431/7111 [12:53<13:40,  4.48it/s]

Gaps (ex-reports):  48%|████▊     | 3432/7111 [12:53<13:36,  4.50it/s]

Gaps (ex-reports):  48%|████▊     | 3433/7111 [12:53<13:03,  4.69it/s]

Gaps (ex-reports):  48%|████▊     | 3434/7111 [12:54<12:57,  4.73it/s]

Gaps (ex-reports):  48%|████▊     | 3435/7111 [12:54<12:44,  4.81it/s]

Gaps (ex-reports):  48%|████▊     | 3436/7111 [12:54<12:54,  4.74it/s]

Gaps (ex-reports):  48%|████▊     | 3437/7111 [12:54<12:44,  4.81it/s]

Gaps (ex-reports):  48%|████▊     | 3438/7111 [12:55<12:31,  4.89it/s]

Gaps (ex-reports):  48%|████▊     | 3439/7111 [12:55<12:34,  4.86it/s]

Gaps (ex-reports):  48%|████▊     | 3440/7111 [12:55<12:22,  4.94it/s]

Gaps (ex-reports):  48%|████▊     | 3441/7111 [12:55<12:54,  4.74it/s]

Gaps (ex-reports):  48%|████▊     | 3442/7111 [12:55<12:45,  4.79it/s]

Gaps (ex-reports):  48%|████▊     | 3443/7111 [12:56<12:44,  4.80it/s]

Gaps (ex-reports):  48%|████▊     | 3444/7111 [12:56<12:26,  4.91it/s]

Gaps (ex-reports):  48%|████▊     | 3445/7111 [12:56<12:17,  4.97it/s]

Gaps (ex-reports):  48%|████▊     | 3446/7111 [12:56<12:21,  4.95it/s]

Gaps (ex-reports):  48%|████▊     | 3447/7111 [12:56<12:14,  4.99it/s]

Gaps (ex-reports):  48%|████▊     | 3448/7111 [12:57<12:27,  4.90it/s]

Gaps (ex-reports):  49%|████▊     | 3449/7111 [12:57<12:32,  4.86it/s]

Gaps (ex-reports):  49%|████▊     | 3450/7111 [12:57<12:26,  4.91it/s]

Gaps (ex-reports):  49%|████▊     | 3451/7111 [12:57<12:37,  4.83it/s]

Gaps (ex-reports):  49%|████▊     | 3452/7111 [12:57<12:27,  4.90it/s]

Gaps (ex-reports):  49%|████▊     | 3453/7111 [12:58<12:22,  4.93it/s]

Gaps (ex-reports):  49%|████▊     | 3454/7111 [12:58<12:29,  4.88it/s]

Gaps (ex-reports):  49%|████▊     | 3455/7111 [12:58<12:34,  4.85it/s]

Gaps (ex-reports):  49%|████▊     | 3456/7111 [12:58<12:30,  4.87it/s]

Gaps (ex-reports):  49%|████▊     | 3457/7111 [12:58<12:32,  4.86it/s]

Gaps (ex-reports):  49%|████▊     | 3458/7111 [12:59<12:12,  4.99it/s]

Gaps (ex-reports):  49%|████▊     | 3459/7111 [12:59<12:09,  5.00it/s]

Gaps (ex-reports):  49%|████▊     | 3460/7111 [12:59<12:28,  4.88it/s]

Gaps (ex-reports):  49%|████▊     | 3461/7111 [12:59<12:24,  4.90it/s]

Gaps (ex-reports):  49%|████▊     | 3462/7111 [12:59<12:30,  4.86it/s]

Gaps (ex-reports):  49%|████▊     | 3463/7111 [13:00<12:22,  4.91it/s]

Gaps (ex-reports):  49%|████▊     | 3464/7111 [13:00<12:23,  4.90it/s]

Gaps (ex-reports):  49%|████▊     | 3465/7111 [13:00<12:11,  4.99it/s]

Gaps (ex-reports):  49%|████▊     | 3466/7111 [13:00<12:06,  5.02it/s]

Gaps (ex-reports):  49%|████▉     | 3467/7111 [13:00<12:05,  5.02it/s]

Gaps (ex-reports):  49%|████▉     | 3468/7111 [13:01<12:37,  4.81it/s]

Gaps (ex-reports):  49%|████▉     | 3469/7111 [13:01<12:22,  4.90it/s]

Gaps (ex-reports):  49%|████▉     | 3470/7111 [13:01<12:34,  4.83it/s]

Gaps (ex-reports):  49%|████▉     | 3471/7111 [13:01<12:36,  4.81it/s]

Gaps (ex-reports):  49%|████▉     | 3472/7111 [13:01<12:39,  4.79it/s]

Gaps (ex-reports):  49%|████▉     | 3473/7111 [13:02<12:31,  4.84it/s]

Gaps (ex-reports):  49%|████▉     | 3474/7111 [13:02<12:43,  4.76it/s]

Gaps (ex-reports):  49%|████▉     | 3475/7111 [13:02<12:22,  4.90it/s]

Gaps (ex-reports):  49%|████▉     | 3476/7111 [13:02<12:20,  4.91it/s]

Gaps (ex-reports):  49%|████▉     | 3477/7111 [13:02<12:28,  4.85it/s]

Gaps (ex-reports):  49%|████▉     | 3478/7111 [13:03<19:48,  3.06it/s]

Gaps (ex-reports):  49%|████▉     | 3479/7111 [13:03<17:25,  3.47it/s]

Gaps (ex-reports):  49%|████▉     | 3480/7111 [13:04<15:56,  3.80it/s]

Gaps (ex-reports):  49%|████▉     | 3481/7111 [13:04<14:39,  4.13it/s]

Gaps (ex-reports):  49%|████▉     | 3482/7111 [13:04<14:02,  4.31it/s]

Gaps (ex-reports):  49%|████▉     | 3483/7111 [13:04<13:38,  4.43it/s]

Gaps (ex-reports):  49%|████▉     | 3484/7111 [13:04<13:10,  4.59it/s]

Gaps (ex-reports):  49%|████▉     | 3485/7111 [13:05<12:58,  4.66it/s]

Gaps (ex-reports):  49%|████▉     | 3486/7111 [13:05<13:04,  4.62it/s]

Gaps (ex-reports):  49%|████▉     | 3487/7111 [13:05<13:04,  4.62it/s]

Gaps (ex-reports):  49%|████▉     | 3488/7111 [13:05<12:48,  4.71it/s]

Gaps (ex-reports):  49%|████▉     | 3489/7111 [13:05<12:52,  4.69it/s]

Gaps (ex-reports):  49%|████▉     | 3490/7111 [13:06<12:52,  4.69it/s]

Gaps (ex-reports):  49%|████▉     | 3491/7111 [13:06<12:51,  4.69it/s]

Gaps (ex-reports):  49%|████▉     | 3492/7111 [13:06<12:42,  4.75it/s]

Gaps (ex-reports):  49%|████▉     | 3493/7111 [13:06<12:29,  4.83it/s]

Gaps (ex-reports):  49%|████▉     | 3494/7111 [13:06<12:23,  4.87it/s]

Gaps (ex-reports):  49%|████▉     | 3495/7111 [13:07<12:26,  4.85it/s]

Gaps (ex-reports):  49%|████▉     | 3496/7111 [13:07<12:19,  4.89it/s]

Gaps (ex-reports):  49%|████▉     | 3497/7111 [13:07<15:47,  3.81it/s]

Gaps (ex-reports):  49%|████▉     | 3498/7111 [13:07<14:41,  4.10it/s]

Gaps (ex-reports):  49%|████▉     | 3499/7111 [13:08<14:19,  4.20it/s]

Gaps (ex-reports):  49%|████▉     | 3500/7111 [13:08<13:43,  4.38it/s]

Gaps (ex-reports):  49%|████▉     | 3501/7111 [13:08<13:34,  4.43it/s]

Gaps (ex-reports):  49%|████▉     | 3502/7111 [13:08<13:29,  4.46it/s]

Gaps (ex-reports):  49%|████▉     | 3503/7111 [13:08<13:15,  4.54it/s]

Gaps (ex-reports):  49%|████▉     | 3504/7111 [13:09<13:03,  4.60it/s]

Gaps (ex-reports):  49%|████▉     | 3505/7111 [13:09<12:51,  4.67it/s]

Gaps (ex-reports):  49%|████▉     | 3506/7111 [13:09<12:49,  4.69it/s]

Gaps (ex-reports):  49%|████▉     | 3507/7111 [13:09<12:47,  4.69it/s]

Gaps (ex-reports):  49%|████▉     | 3508/7111 [13:10<12:43,  4.72it/s]

Gaps (ex-reports):  49%|████▉     | 3509/7111 [13:10<12:32,  4.78it/s]

Gaps (ex-reports):  49%|████▉     | 3510/7111 [13:10<12:34,  4.77it/s]

Gaps (ex-reports):  49%|████▉     | 3511/7111 [13:10<12:32,  4.79it/s]

Gaps (ex-reports):  49%|████▉     | 3512/7111 [13:10<12:32,  4.78it/s]

Gaps (ex-reports):  49%|████▉     | 3513/7111 [13:11<12:27,  4.81it/s]

Gaps (ex-reports):  49%|████▉     | 3514/7111 [13:11<12:34,  4.77it/s]

Gaps (ex-reports):  49%|████▉     | 3515/7111 [13:11<13:02,  4.60it/s]

Gaps (ex-reports):  49%|████▉     | 3516/7111 [13:11<12:56,  4.63it/s]

Gaps (ex-reports):  49%|████▉     | 3517/7111 [13:12<23:10,  2.59it/s]

Gaps (ex-reports):  49%|████▉     | 3518/7111 [13:12<20:13,  2.96it/s]

Gaps (ex-reports):  49%|████▉     | 3519/7111 [13:12<18:00,  3.33it/s]

Gaps (ex-reports):  50%|████▉     | 3520/7111 [13:13<16:12,  3.69it/s]

Gaps (ex-reports):  50%|████▉     | 3521/7111 [13:13<15:17,  3.91it/s]

Gaps (ex-reports):  50%|████▉     | 3522/7111 [13:13<14:24,  4.15it/s]

Gaps (ex-reports):  50%|████▉     | 3523/7111 [13:13<13:43,  4.36it/s]

Gaps (ex-reports):  50%|████▉     | 3524/7111 [13:14<13:21,  4.47it/s]

Gaps (ex-reports):  50%|████▉     | 3525/7111 [13:14<12:59,  4.60it/s]

Gaps (ex-reports):  50%|████▉     | 3526/7111 [13:14<12:42,  4.70it/s]

Gaps (ex-reports):  50%|████▉     | 3527/7111 [13:14<13:02,  4.58it/s]

Gaps (ex-reports):  50%|████▉     | 3528/7111 [13:14<12:40,  4.71it/s]

Gaps (ex-reports):  50%|████▉     | 3529/7111 [13:15<12:47,  4.66it/s]

Gaps (ex-reports):  50%|████▉     | 3530/7111 [13:15<12:46,  4.67it/s]

Gaps (ex-reports):  50%|████▉     | 3531/7111 [13:15<12:43,  4.69it/s]

Gaps (ex-reports):  50%|████▉     | 3532/7111 [13:15<12:31,  4.76it/s]

Gaps (ex-reports):  50%|████▉     | 3533/7111 [13:15<12:16,  4.85it/s]

Gaps (ex-reports):  50%|████▉     | 3534/7111 [13:16<12:21,  4.83it/s]

Gaps (ex-reports):  50%|████▉     | 3535/7111 [13:16<12:25,  4.80it/s]

Gaps (ex-reports):  50%|████▉     | 3536/7111 [13:16<12:31,  4.76it/s]

Gaps (ex-reports):  50%|████▉     | 3537/7111 [13:16<12:20,  4.83it/s]

Gaps (ex-reports):  50%|████▉     | 3538/7111 [13:16<12:18,  4.84it/s]

Gaps (ex-reports):  50%|████▉     | 3539/7111 [13:17<12:39,  4.70it/s]

Gaps (ex-reports):  50%|████▉     | 3540/7111 [13:17<12:30,  4.76it/s]

Gaps (ex-reports):  50%|████▉     | 3541/7111 [13:17<12:10,  4.89it/s]

Gaps (ex-reports):  50%|████▉     | 3542/7111 [13:17<12:02,  4.94it/s]

Gaps (ex-reports):  50%|████▉     | 3543/7111 [13:17<12:09,  4.89it/s]

Gaps (ex-reports):  50%|████▉     | 3544/7111 [13:18<12:28,  4.77it/s]

Gaps (ex-reports):  50%|████▉     | 3545/7111 [13:18<12:21,  4.81it/s]

Gaps (ex-reports):  50%|████▉     | 3546/7111 [13:18<12:12,  4.86it/s]

Gaps (ex-reports):  50%|████▉     | 3547/7111 [13:18<12:12,  4.86it/s]

Gaps (ex-reports):  50%|████▉     | 3548/7111 [13:18<12:11,  4.87it/s]

Gaps (ex-reports):  50%|████▉     | 3549/7111 [13:19<12:10,  4.88it/s]

Gaps (ex-reports):  50%|████▉     | 3550/7111 [13:19<12:15,  4.84it/s]

Gaps (ex-reports):  50%|████▉     | 3551/7111 [13:19<18:23,  3.22it/s]

Gaps (ex-reports):  50%|████▉     | 3552/7111 [13:20<16:35,  3.58it/s]

Gaps (ex-reports):  50%|████▉     | 3553/7111 [13:20<15:16,  3.88it/s]

Gaps (ex-reports):  50%|████▉     | 3554/7111 [13:20<14:36,  4.06it/s]

Gaps (ex-reports):  50%|████▉     | 3555/7111 [13:20<14:04,  4.21it/s]

Gaps (ex-reports):  50%|█████     | 3556/7111 [13:21<13:24,  4.42it/s]

Gaps (ex-reports):  50%|█████     | 3557/7111 [13:21<13:07,  4.51it/s]

Gaps (ex-reports):  50%|█████     | 3558/7111 [13:21<12:32,  4.72it/s]

Gaps (ex-reports):  50%|█████     | 3559/7111 [13:21<12:51,  4.60it/s]

Gaps (ex-reports):  50%|█████     | 3560/7111 [13:21<12:29,  4.74it/s]

Gaps (ex-reports):  50%|█████     | 3561/7111 [13:22<12:20,  4.79it/s]

Gaps (ex-reports):  50%|█████     | 3562/7111 [13:22<12:19,  4.80it/s]

Gaps (ex-reports):  50%|█████     | 3563/7111 [13:22<12:34,  4.70it/s]

Gaps (ex-reports):  50%|█████     | 3564/7111 [13:23<23:56,  2.47it/s]

Gaps (ex-reports):  50%|█████     | 3565/7111 [13:23<27:30,  2.15it/s]

Gaps (ex-reports):  50%|█████     | 3566/7111 [13:24<22:54,  2.58it/s]

Gaps (ex-reports):  50%|█████     | 3567/7111 [13:24<19:48,  2.98it/s]

Gaps (ex-reports):  50%|█████     | 3568/7111 [13:24<17:28,  3.38it/s]

Gaps (ex-reports):  50%|█████     | 3569/7111 [13:24<15:58,  3.69it/s]

Gaps (ex-reports):  50%|█████     | 3570/7111 [13:24<14:36,  4.04it/s]

Gaps (ex-reports):  50%|█████     | 3571/7111 [13:25<13:44,  4.30it/s]

Gaps (ex-reports):  50%|█████     | 3572/7111 [13:25<13:19,  4.43it/s]

Gaps (ex-reports):  50%|█████     | 3573/7111 [13:25<13:07,  4.50it/s]

Gaps (ex-reports):  50%|█████     | 3574/7111 [13:25<12:40,  4.65it/s]

Gaps (ex-reports):  50%|█████     | 3575/7111 [13:26<12:44,  4.62it/s]

Gaps (ex-reports):  50%|█████     | 3576/7111 [13:26<12:30,  4.71it/s]

Gaps (ex-reports):  50%|█████     | 3577/7111 [13:26<12:22,  4.76it/s]

Gaps (ex-reports):  50%|█████     | 3578/7111 [13:26<12:19,  4.78it/s]

Gaps (ex-reports):  50%|█████     | 3579/7111 [13:26<12:19,  4.78it/s]

Gaps (ex-reports):  50%|█████     | 3580/7111 [13:27<12:14,  4.81it/s]

Gaps (ex-reports):  50%|█████     | 3581/7111 [13:27<12:11,  4.83it/s]

Gaps (ex-reports):  50%|█████     | 3582/7111 [13:27<12:16,  4.79it/s]

Gaps (ex-reports):  50%|█████     | 3583/7111 [13:27<12:21,  4.76it/s]

Gaps (ex-reports):  50%|█████     | 3584/7111 [13:27<12:16,  4.79it/s]

Gaps (ex-reports):  50%|█████     | 3585/7111 [13:28<11:59,  4.90it/s]

Gaps (ex-reports):  50%|█████     | 3586/7111 [13:28<12:09,  4.84it/s]

Gaps (ex-reports):  50%|█████     | 3587/7111 [13:28<11:58,  4.91it/s]

Gaps (ex-reports):  50%|█████     | 3588/7111 [13:28<11:47,  4.98it/s]

Gaps (ex-reports):  50%|█████     | 3589/7111 [13:28<11:57,  4.91it/s]

Gaps (ex-reports):  50%|█████     | 3590/7111 [13:29<11:56,  4.91it/s]

Gaps (ex-reports):  50%|█████     | 3591/7111 [13:29<11:45,  4.99it/s]

Gaps (ex-reports):  51%|█████     | 3592/7111 [13:29<12:05,  4.85it/s]

Gaps (ex-reports):  51%|█████     | 3593/7111 [13:29<12:02,  4.87it/s]

Gaps (ex-reports):  51%|█████     | 3594/7111 [13:29<12:08,  4.83it/s]

Gaps (ex-reports):  51%|█████     | 3595/7111 [13:30<11:57,  4.90it/s]

Gaps (ex-reports):  51%|█████     | 3596/7111 [13:30<12:09,  4.82it/s]

Gaps (ex-reports):  51%|█████     | 3597/7111 [13:30<12:01,  4.87it/s]

Gaps (ex-reports):  51%|█████     | 3598/7111 [13:30<12:05,  4.84it/s]

Gaps (ex-reports):  51%|█████     | 3599/7111 [13:30<11:53,  4.92it/s]

Gaps (ex-reports):  51%|█████     | 3600/7111 [13:31<12:12,  4.79it/s]

Gaps (ex-reports):  51%|█████     | 3601/7111 [13:31<12:02,  4.86it/s]

Gaps (ex-reports):  51%|█████     | 3602/7111 [13:31<12:04,  4.84it/s]

Gaps (ex-reports):  51%|█████     | 3603/7111 [13:31<11:58,  4.88it/s]

Gaps (ex-reports):  51%|█████     | 3604/7111 [13:31<12:04,  4.84it/s]

Gaps (ex-reports):  51%|█████     | 3605/7111 [13:32<12:00,  4.87it/s]

Gaps (ex-reports):  51%|█████     | 3606/7111 [13:32<11:45,  4.97it/s]

Gaps (ex-reports):  51%|█████     | 3607/7111 [13:32<12:02,  4.85it/s]

Gaps (ex-reports):  51%|█████     | 3608/7111 [13:32<12:01,  4.86it/s]

Gaps (ex-reports):  51%|█████     | 3609/7111 [13:32<11:53,  4.91it/s]

Gaps (ex-reports):  51%|█████     | 3610/7111 [13:33<11:54,  4.90it/s]

Gaps (ex-reports):  51%|█████     | 3611/7111 [13:33<11:53,  4.91it/s]

Gaps (ex-reports):  51%|█████     | 3612/7111 [13:33<11:48,  4.94it/s]

Gaps (ex-reports):  51%|█████     | 3613/7111 [13:33<11:40,  4.99it/s]

Gaps (ex-reports):  51%|█████     | 3614/7111 [13:33<11:46,  4.95it/s]

Gaps (ex-reports):  51%|█████     | 3615/7111 [13:34<11:57,  4.87it/s]

Gaps (ex-reports):  51%|█████     | 3616/7111 [13:34<11:57,  4.87it/s]

Gaps (ex-reports):  51%|█████     | 3617/7111 [13:34<12:50,  4.53it/s]

Gaps (ex-reports):  51%|█████     | 3618/7111 [13:34<12:44,  4.57it/s]

Gaps (ex-reports):  51%|█████     | 3619/7111 [13:35<12:22,  4.70it/s]

Gaps (ex-reports):  51%|█████     | 3620/7111 [13:35<12:03,  4.83it/s]

Gaps (ex-reports):  51%|█████     | 3621/7111 [13:35<12:13,  4.76it/s]

Gaps (ex-reports):  51%|█████     | 3622/7111 [13:35<12:00,  4.84it/s]

Gaps (ex-reports):  51%|█████     | 3623/7111 [13:35<11:58,  4.85it/s]

Gaps (ex-reports):  51%|█████     | 3624/7111 [13:36<11:52,  4.90it/s]

Gaps (ex-reports):  51%|█████     | 3625/7111 [13:36<11:52,  4.89it/s]

Gaps (ex-reports):  51%|█████     | 3626/7111 [13:36<11:53,  4.88it/s]

Gaps (ex-reports):  51%|█████     | 3627/7111 [13:36<11:47,  4.92it/s]

Gaps (ex-reports):  51%|█████     | 3628/7111 [13:36<11:46,  4.93it/s]

Gaps (ex-reports):  51%|█████     | 3629/7111 [13:37<17:14,  3.36it/s]

Gaps (ex-reports):  51%|█████     | 3630/7111 [13:37<15:35,  3.72it/s]

Gaps (ex-reports):  51%|█████     | 3631/7111 [13:37<14:22,  4.03it/s]

Gaps (ex-reports):  51%|█████     | 3632/7111 [13:38<13:34,  4.27it/s]

Gaps (ex-reports):  51%|█████     | 3633/7111 [13:38<13:11,  4.39it/s]

Gaps (ex-reports):  51%|█████     | 3634/7111 [13:38<12:45,  4.54it/s]

Gaps (ex-reports):  51%|█████     | 3635/7111 [13:38<12:38,  4.58it/s]

Gaps (ex-reports):  51%|█████     | 3636/7111 [13:38<12:54,  4.49it/s]

Gaps (ex-reports):  51%|█████     | 3637/7111 [13:39<12:47,  4.53it/s]

Gaps (ex-reports):  51%|█████     | 3638/7111 [13:39<12:28,  4.64it/s]

Gaps (ex-reports):  51%|█████     | 3639/7111 [13:39<12:11,  4.75it/s]

Gaps (ex-reports):  51%|█████     | 3640/7111 [13:39<12:02,  4.81it/s]

Gaps (ex-reports):  51%|█████     | 3641/7111 [13:39<11:56,  4.85it/s]

Gaps (ex-reports):  51%|█████     | 3642/7111 [13:40<11:45,  4.91it/s]

Gaps (ex-reports):  51%|█████     | 3643/7111 [13:40<11:33,  5.00it/s]

Gaps (ex-reports):  51%|█████     | 3644/7111 [13:40<11:35,  4.98it/s]

Gaps (ex-reports):  51%|█████▏    | 3645/7111 [13:40<11:48,  4.89it/s]

Gaps (ex-reports):  51%|█████▏    | 3646/7111 [13:40<11:47,  4.90it/s]

Gaps (ex-reports):  51%|█████▏    | 3647/7111 [13:41<11:36,  4.97it/s]

Gaps (ex-reports):  51%|█████▏    | 3648/7111 [13:41<11:31,  5.01it/s]

Gaps (ex-reports):  51%|█████▏    | 3649/7111 [13:41<11:49,  4.88it/s]

Gaps (ex-reports):  51%|█████▏    | 3650/7111 [13:41<11:47,  4.89it/s]

Gaps (ex-reports):  51%|█████▏    | 3651/7111 [13:41<11:59,  4.81it/s]

Gaps (ex-reports):  51%|█████▏    | 3652/7111 [13:42<12:05,  4.77it/s]

Gaps (ex-reports):  51%|█████▏    | 3653/7111 [13:42<11:58,  4.81it/s]

Gaps (ex-reports):  51%|█████▏    | 3654/7111 [13:42<11:59,  4.81it/s]

Gaps (ex-reports):  51%|█████▏    | 3655/7111 [13:42<12:02,  4.78it/s]

Gaps (ex-reports):  51%|█████▏    | 3656/7111 [13:42<11:54,  4.84it/s]

Gaps (ex-reports):  51%|█████▏    | 3657/7111 [13:43<11:42,  4.92it/s]

Gaps (ex-reports):  51%|█████▏    | 3658/7111 [13:43<11:53,  4.84it/s]

Gaps (ex-reports):  51%|█████▏    | 3659/7111 [13:43<11:48,  4.87it/s]

Gaps (ex-reports):  51%|█████▏    | 3660/7111 [13:43<11:52,  4.84it/s]

Gaps (ex-reports):  51%|█████▏    | 3661/7111 [13:44<11:50,  4.86it/s]

Gaps (ex-reports):  51%|█████▏    | 3662/7111 [13:44<11:38,  4.94it/s]

Gaps (ex-reports):  52%|█████▏    | 3663/7111 [13:44<11:45,  4.89it/s]

Gaps (ex-reports):  52%|█████▏    | 3664/7111 [13:44<11:46,  4.88it/s]

Gaps (ex-reports):  52%|█████▏    | 3665/7111 [13:44<11:38,  4.93it/s]

Gaps (ex-reports):  52%|█████▏    | 3666/7111 [13:45<11:44,  4.89it/s]

Gaps (ex-reports):  52%|█████▏    | 3667/7111 [13:45<11:43,  4.89it/s]

Gaps (ex-reports):  52%|█████▏    | 3668/7111 [13:45<11:42,  4.90it/s]

Gaps (ex-reports):  52%|█████▏    | 3669/7111 [13:45<11:59,  4.79it/s]

Gaps (ex-reports):  52%|█████▏    | 3670/7111 [13:45<11:52,  4.83it/s]

Gaps (ex-reports):  52%|█████▏    | 3671/7111 [13:46<11:53,  4.82it/s]

Gaps (ex-reports):  52%|█████▏    | 3672/7111 [13:46<11:56,  4.80it/s]

Gaps (ex-reports):  52%|█████▏    | 3673/7111 [13:46<11:52,  4.82it/s]

Gaps (ex-reports):  52%|█████▏    | 3674/7111 [13:46<11:58,  4.78it/s]

Gaps (ex-reports):  52%|█████▏    | 3675/7111 [13:46<11:52,  4.82it/s]

Gaps (ex-reports):  52%|█████▏    | 3676/7111 [13:47<11:52,  4.82it/s]

Gaps (ex-reports):  52%|█████▏    | 3677/7111 [13:47<11:54,  4.81it/s]

Gaps (ex-reports):  52%|█████▏    | 3678/7111 [13:47<11:58,  4.78it/s]

Gaps (ex-reports):  52%|█████▏    | 3679/7111 [13:47<11:51,  4.82it/s]

Gaps (ex-reports):  52%|█████▏    | 3680/7111 [13:47<11:51,  4.82it/s]

Gaps (ex-reports):  52%|█████▏    | 3681/7111 [13:48<11:44,  4.87it/s]

Gaps (ex-reports):  52%|█████▏    | 3682/7111 [13:48<11:30,  4.97it/s]

Gaps (ex-reports):  52%|█████▏    | 3683/7111 [13:48<11:33,  4.94it/s]

Gaps (ex-reports):  52%|█████▏    | 3684/7111 [13:48<11:35,  4.93it/s]

Gaps (ex-reports):  52%|█████▏    | 3685/7111 [13:48<11:25,  5.00it/s]

Gaps (ex-reports):  52%|█████▏    | 3686/7111 [13:49<11:49,  4.83it/s]

Gaps (ex-reports):  52%|█████▏    | 3687/7111 [13:49<11:47,  4.84it/s]

Gaps (ex-reports):  52%|█████▏    | 3688/7111 [13:49<11:36,  4.92it/s]

Gaps (ex-reports):  52%|█████▏    | 3689/7111 [13:49<11:19,  5.04it/s]

Gaps (ex-reports):  52%|█████▏    | 3690/7111 [13:49<11:28,  4.97it/s]

Gaps (ex-reports):  52%|█████▏    | 3691/7111 [13:50<11:22,  5.01it/s]

Gaps (ex-reports):  52%|█████▏    | 3692/7111 [13:50<11:33,  4.93it/s]

Gaps (ex-reports):  52%|█████▏    | 3693/7111 [13:50<11:19,  5.03it/s]

Gaps (ex-reports):  52%|█████▏    | 3694/7111 [13:50<11:33,  4.92it/s]

Gaps (ex-reports):  52%|█████▏    | 3695/7111 [13:50<11:34,  4.92it/s]

Gaps (ex-reports):  52%|█████▏    | 3696/7111 [13:51<11:24,  4.99it/s]

Gaps (ex-reports):  52%|█████▏    | 3697/7111 [13:51<11:27,  4.97it/s]

Gaps (ex-reports):  52%|█████▏    | 3698/7111 [13:51<11:34,  4.91it/s]

Gaps (ex-reports):  52%|█████▏    | 3699/7111 [13:51<11:32,  4.93it/s]

Gaps (ex-reports):  52%|█████▏    | 3700/7111 [13:51<11:28,  4.96it/s]

Gaps (ex-reports):  52%|█████▏    | 3701/7111 [13:52<11:18,  5.03it/s]

Gaps (ex-reports):  52%|█████▏    | 3702/7111 [13:52<11:17,  5.03it/s]

Gaps (ex-reports):  52%|█████▏    | 3703/7111 [13:52<11:22,  4.99it/s]

Gaps (ex-reports):  52%|█████▏    | 3704/7111 [13:52<11:31,  4.93it/s]

Gaps (ex-reports):  52%|█████▏    | 3705/7111 [13:52<11:52,  4.78it/s]

Gaps (ex-reports):  52%|█████▏    | 3706/7111 [13:53<11:48,  4.81it/s]

Gaps (ex-reports):  52%|█████▏    | 3707/7111 [13:53<11:49,  4.80it/s]

Gaps (ex-reports):  52%|█████▏    | 3708/7111 [13:53<11:34,  4.90it/s]

Gaps (ex-reports):  52%|█████▏    | 3709/7111 [13:53<11:41,  4.85it/s]

Gaps (ex-reports):  52%|█████▏    | 3710/7111 [13:54<11:57,  4.74it/s]

Gaps (ex-reports):  52%|█████▏    | 3711/7111 [13:54<11:55,  4.75it/s]

Gaps (ex-reports):  52%|█████▏    | 3712/7111 [13:54<12:02,  4.71it/s]

Gaps (ex-reports):  52%|█████▏    | 3713/7111 [13:54<11:47,  4.80it/s]

Gaps (ex-reports):  52%|█████▏    | 3714/7111 [13:54<11:47,  4.80it/s]

Gaps (ex-reports):  52%|█████▏    | 3715/7111 [13:55<11:47,  4.80it/s]

Gaps (ex-reports):  52%|█████▏    | 3716/7111 [13:55<11:33,  4.90it/s]

Gaps (ex-reports):  52%|█████▏    | 3717/7111 [13:55<11:35,  4.88it/s]

Gaps (ex-reports):  52%|█████▏    | 3718/7111 [13:55<11:44,  4.82it/s]

Gaps (ex-reports):  52%|█████▏    | 3719/7111 [13:55<11:46,  4.80it/s]

Gaps (ex-reports):  52%|█████▏    | 3720/7111 [13:56<11:35,  4.87it/s]

Gaps (ex-reports):  52%|█████▏    | 3721/7111 [13:56<11:26,  4.94it/s]

Gaps (ex-reports):  52%|█████▏    | 3722/7111 [13:56<11:28,  4.92it/s]

Gaps (ex-reports):  52%|█████▏    | 3723/7111 [13:56<11:16,  5.01it/s]

Gaps (ex-reports):  52%|█████▏    | 3724/7111 [13:56<11:31,  4.90it/s]

Gaps (ex-reports):  52%|█████▏    | 3725/7111 [13:57<11:47,  4.78it/s]

Gaps (ex-reports):  52%|█████▏    | 3726/7111 [13:57<11:48,  4.78it/s]

Gaps (ex-reports):  52%|█████▏    | 3727/7111 [13:57<11:44,  4.80it/s]

Gaps (ex-reports):  52%|█████▏    | 3728/7111 [13:57<11:45,  4.80it/s]

Gaps (ex-reports):  52%|█████▏    | 3729/7111 [13:57<11:47,  4.78it/s]

Gaps (ex-reports):  52%|█████▏    | 3730/7111 [13:58<11:36,  4.85it/s]

Gaps (ex-reports):  52%|█████▏    | 3731/7111 [13:58<11:34,  4.87it/s]

Gaps (ex-reports):  52%|█████▏    | 3732/7111 [13:58<11:25,  4.93it/s]

Gaps (ex-reports):  52%|█████▏    | 3733/7111 [13:58<11:30,  4.89it/s]

Gaps (ex-reports):  53%|█████▎    | 3734/7111 [13:58<11:35,  4.86it/s]

Gaps (ex-reports):  53%|█████▎    | 3735/7111 [13:59<11:41,  4.81it/s]

Gaps (ex-reports):  53%|█████▎    | 3736/7111 [13:59<11:56,  4.71it/s]

Gaps (ex-reports):  53%|█████▎    | 3737/7111 [13:59<11:57,  4.70it/s]

Gaps (ex-reports):  53%|█████▎    | 3738/7111 [13:59<11:57,  4.70it/s]

Gaps (ex-reports):  53%|█████▎    | 3739/7111 [14:00<11:38,  4.83it/s]

Gaps (ex-reports):  53%|█████▎    | 3740/7111 [14:00<11:26,  4.91it/s]

Gaps (ex-reports):  53%|█████▎    | 3741/7111 [14:00<11:41,  4.81it/s]

Gaps (ex-reports):  53%|█████▎    | 3742/7111 [14:00<11:36,  4.83it/s]

Gaps (ex-reports):  53%|█████▎    | 3743/7111 [14:00<11:36,  4.84it/s]

Gaps (ex-reports):  53%|█████▎    | 3744/7111 [14:01<11:32,  4.86it/s]

Gaps (ex-reports):  53%|█████▎    | 3745/7111 [14:01<11:41,  4.80it/s]

Gaps (ex-reports):  53%|█████▎    | 3746/7111 [14:01<11:33,  4.85it/s]

Gaps (ex-reports):  53%|█████▎    | 3747/7111 [14:01<11:20,  4.95it/s]

Gaps (ex-reports):  53%|█████▎    | 3748/7111 [14:01<11:30,  4.87it/s]

Gaps (ex-reports):  53%|█████▎    | 3749/7111 [14:02<11:25,  4.91it/s]

Gaps (ex-reports):  53%|█████▎    | 3750/7111 [14:02<11:16,  4.97it/s]

Gaps (ex-reports):  53%|█████▎    | 3751/7111 [14:02<11:24,  4.91it/s]

Gaps (ex-reports):  53%|█████▎    | 3752/7111 [14:02<11:30,  4.86it/s]

Gaps (ex-reports):  53%|█████▎    | 3753/7111 [14:02<11:29,  4.87it/s]

Gaps (ex-reports):  53%|█████▎    | 3754/7111 [14:03<11:43,  4.77it/s]

Gaps (ex-reports):  53%|█████▎    | 3755/7111 [14:03<11:35,  4.83it/s]

Gaps (ex-reports):  53%|█████▎    | 3756/7111 [14:03<11:23,  4.91it/s]

Gaps (ex-reports):  53%|█████▎    | 3757/7111 [14:03<11:25,  4.90it/s]

Gaps (ex-reports):  53%|█████▎    | 3758/7111 [14:03<11:31,  4.85it/s]

Gaps (ex-reports):  53%|█████▎    | 3759/7111 [14:04<12:29,  4.47it/s]

Gaps (ex-reports):  53%|█████▎    | 3760/7111 [14:04<12:09,  4.59it/s]

Gaps (ex-reports):  53%|█████▎    | 3761/7111 [14:04<11:42,  4.77it/s]

Gaps (ex-reports):  53%|█████▎    | 3762/7111 [14:04<11:39,  4.79it/s]

Gaps (ex-reports):  53%|█████▎    | 3763/7111 [14:05<11:42,  4.77it/s]

Gaps (ex-reports):  53%|█████▎    | 3764/7111 [14:05<11:34,  4.82it/s]

Gaps (ex-reports):  53%|█████▎    | 3765/7111 [14:05<11:35,  4.81it/s]

Gaps (ex-reports):  53%|█████▎    | 3766/7111 [14:05<12:14,  4.56it/s]

Gaps (ex-reports):  53%|█████▎    | 3767/7111 [14:05<12:04,  4.62it/s]

Gaps (ex-reports):  53%|█████▎    | 3768/7111 [14:06<11:42,  4.76it/s]

Gaps (ex-reports):  53%|█████▎    | 3769/7111 [14:06<11:25,  4.87it/s]

Gaps (ex-reports):  53%|█████▎    | 3770/7111 [14:06<11:40,  4.77it/s]

Gaps (ex-reports):  53%|█████▎    | 3771/7111 [14:06<11:37,  4.79it/s]

Gaps (ex-reports):  53%|█████▎    | 3772/7111 [14:06<11:29,  4.84it/s]

Gaps (ex-reports):  53%|█████▎    | 3773/7111 [14:07<11:31,  4.83it/s]

Gaps (ex-reports):  53%|█████▎    | 3774/7111 [14:07<11:26,  4.86it/s]

Gaps (ex-reports):  53%|█████▎    | 3775/7111 [14:07<11:25,  4.86it/s]

Gaps (ex-reports):  53%|█████▎    | 3776/7111 [14:07<11:36,  4.79it/s]

Gaps (ex-reports):  53%|█████▎    | 3777/7111 [14:07<11:42,  4.74it/s]

Gaps (ex-reports):  53%|█████▎    | 3778/7111 [14:08<11:33,  4.80it/s]

Gaps (ex-reports):  53%|█████▎    | 3779/7111 [14:08<11:33,  4.81it/s]

Gaps (ex-reports):  53%|█████▎    | 3780/7111 [14:08<11:33,  4.80it/s]

Gaps (ex-reports):  53%|█████▎    | 3781/7111 [14:08<11:20,  4.89it/s]

Gaps (ex-reports):  53%|█████▎    | 3782/7111 [14:08<11:34,  4.80it/s]

Gaps (ex-reports):  53%|█████▎    | 3783/7111 [14:09<11:42,  4.74it/s]

Gaps (ex-reports):  53%|█████▎    | 3784/7111 [14:09<11:30,  4.82it/s]

Gaps (ex-reports):  53%|█████▎    | 3785/7111 [14:09<11:29,  4.82it/s]

Gaps (ex-reports):  53%|█████▎    | 3786/7111 [14:09<11:11,  4.95it/s]

Gaps (ex-reports):  53%|█████▎    | 3787/7111 [14:10<11:21,  4.88it/s]

Gaps (ex-reports):  53%|█████▎    | 3788/7111 [14:10<11:30,  4.81it/s]

Gaps (ex-reports):  53%|█████▎    | 3789/7111 [14:10<11:25,  4.85it/s]

Gaps (ex-reports):  53%|█████▎    | 3790/7111 [14:10<11:37,  4.76it/s]

Gaps (ex-reports):  53%|█████▎    | 3791/7111 [14:10<11:52,  4.66it/s]

Gaps (ex-reports):  53%|█████▎    | 3792/7111 [14:11<11:31,  4.80it/s]

Gaps (ex-reports):  53%|█████▎    | 3793/7111 [14:11<11:15,  4.91it/s]

Gaps (ex-reports):  53%|█████▎    | 3794/7111 [14:11<11:06,  4.98it/s]

Gaps (ex-reports):  53%|█████▎    | 3795/7111 [14:11<11:11,  4.94it/s]

Gaps (ex-reports):  53%|█████▎    | 3796/7111 [14:11<11:00,  5.02it/s]

Gaps (ex-reports):  53%|█████▎    | 3797/7111 [14:12<10:55,  5.06it/s]

Gaps (ex-reports):  53%|█████▎    | 3798/7111 [14:12<11:12,  4.93it/s]

Gaps (ex-reports):  53%|█████▎    | 3799/7111 [14:12<11:07,  4.96it/s]

Gaps (ex-reports):  53%|█████▎    | 3800/7111 [14:12<11:02,  5.00it/s]

Gaps (ex-reports):  53%|█████▎    | 3801/7111 [14:12<11:27,  4.81it/s]

Gaps (ex-reports):  53%|█████▎    | 3802/7111 [14:13<11:27,  4.81it/s]

Gaps (ex-reports):  53%|█████▎    | 3803/7111 [14:13<11:25,  4.83it/s]

Gaps (ex-reports):  53%|█████▎    | 3804/7111 [14:13<11:20,  4.86it/s]

Gaps (ex-reports):  54%|█████▎    | 3805/7111 [14:13<11:15,  4.89it/s]

Gaps (ex-reports):  54%|█████▎    | 3806/7111 [14:13<11:37,  4.74it/s]

Gaps (ex-reports):  54%|█████▎    | 3807/7111 [14:14<11:43,  4.69it/s]

Gaps (ex-reports):  54%|█████▎    | 3808/7111 [14:14<11:47,  4.67it/s]

Gaps (ex-reports):  54%|█████▎    | 3809/7111 [14:14<11:35,  4.75it/s]

Gaps (ex-reports):  54%|█████▎    | 3810/7111 [14:14<11:30,  4.78it/s]

Gaps (ex-reports):  54%|█████▎    | 3811/7111 [14:14<11:21,  4.84it/s]

Gaps (ex-reports):  54%|█████▎    | 3812/7111 [14:15<11:23,  4.83it/s]

Gaps (ex-reports):  54%|█████▎    | 3813/7111 [14:15<11:18,  4.86it/s]

Gaps (ex-reports):  54%|█████▎    | 3814/7111 [14:15<11:26,  4.80it/s]

Gaps (ex-reports):  54%|█████▎    | 3815/7111 [14:15<11:12,  4.90it/s]

Gaps (ex-reports):  54%|█████▎    | 3816/7111 [14:15<11:03,  4.96it/s]

Gaps (ex-reports):  54%|█████▎    | 3817/7111 [14:16<11:10,  4.91it/s]

Gaps (ex-reports):  54%|█████▎    | 3818/7111 [14:16<11:31,  4.76it/s]

Gaps (ex-reports):  54%|█████▎    | 3819/7111 [14:16<11:33,  4.75it/s]

Gaps (ex-reports):  54%|█████▎    | 3820/7111 [14:16<11:22,  4.82it/s]

Gaps (ex-reports):  54%|█████▎    | 3821/7111 [14:17<11:12,  4.89it/s]

Gaps (ex-reports):  54%|█████▎    | 3822/7111 [14:17<11:23,  4.81it/s]

Gaps (ex-reports):  54%|█████▍    | 3823/7111 [14:17<11:10,  4.90it/s]

Gaps (ex-reports):  54%|█████▍    | 3824/7111 [14:17<11:21,  4.82it/s]

Gaps (ex-reports):  54%|█████▍    | 3825/7111 [14:17<11:19,  4.84it/s]

Gaps (ex-reports):  54%|█████▍    | 3826/7111 [14:18<11:16,  4.86it/s]

Gaps (ex-reports):  54%|█████▍    | 3827/7111 [14:18<11:42,  4.67it/s]

Gaps (ex-reports):  54%|█████▍    | 3828/7111 [14:18<11:27,  4.78it/s]

Gaps (ex-reports):  54%|█████▍    | 3829/7111 [14:18<11:10,  4.89it/s]

Gaps (ex-reports):  54%|█████▍    | 3830/7111 [14:18<11:10,  4.90it/s]

Gaps (ex-reports):  54%|█████▍    | 3831/7111 [14:19<11:02,  4.95it/s]

Gaps (ex-reports):  54%|█████▍    | 3832/7111 [14:19<11:12,  4.87it/s]

Gaps (ex-reports):  54%|█████▍    | 3833/7111 [14:19<11:19,  4.82it/s]

Gaps (ex-reports):  54%|█████▍    | 3834/7111 [14:19<11:13,  4.86it/s]

Gaps (ex-reports):  54%|█████▍    | 3835/7111 [14:19<11:08,  4.90it/s]

Gaps (ex-reports):  54%|█████▍    | 3836/7111 [14:20<11:09,  4.89it/s]

Gaps (ex-reports):  54%|█████▍    | 3837/7111 [14:20<11:05,  4.92it/s]

Gaps (ex-reports):  54%|█████▍    | 3838/7111 [14:20<10:52,  5.02it/s]

Gaps (ex-reports):  54%|█████▍    | 3839/7111 [14:20<11:04,  4.93it/s]

Gaps (ex-reports):  54%|█████▍    | 3840/7111 [14:20<11:07,  4.90it/s]

Gaps (ex-reports):  54%|█████▍    | 3841/7111 [14:21<11:30,  4.73it/s]

Gaps (ex-reports):  54%|█████▍    | 3842/7111 [14:21<11:37,  4.69it/s]

Gaps (ex-reports):  54%|█████▍    | 3843/7111 [14:21<11:20,  4.80it/s]

Gaps (ex-reports):  54%|█████▍    | 3844/7111 [14:21<11:25,  4.77it/s]

Gaps (ex-reports):  54%|█████▍    | 3845/7111 [14:21<11:13,  4.85it/s]

Gaps (ex-reports):  54%|█████▍    | 3846/7111 [14:22<11:26,  4.75it/s]

Gaps (ex-reports):  54%|█████▍    | 3847/7111 [14:22<11:20,  4.80it/s]

Gaps (ex-reports):  54%|█████▍    | 3848/7111 [14:22<11:23,  4.78it/s]

Gaps (ex-reports):  54%|█████▍    | 3849/7111 [14:22<11:12,  4.85it/s]

Gaps (ex-reports):  54%|█████▍    | 3850/7111 [14:23<11:06,  4.89it/s]

Gaps (ex-reports):  54%|█████▍    | 3851/7111 [14:23<11:04,  4.91it/s]

Gaps (ex-reports):  54%|█████▍    | 3852/7111 [14:23<16:08,  3.36it/s]

Gaps (ex-reports):  54%|█████▍    | 3853/7111 [14:23<14:36,  3.71it/s]

Gaps (ex-reports):  54%|█████▍    | 3854/7111 [14:24<13:38,  3.98it/s]

Gaps (ex-reports):  54%|█████▍    | 3855/7111 [14:24<12:57,  4.19it/s]

Gaps (ex-reports):  54%|█████▍    | 3856/7111 [14:24<12:30,  4.34it/s]

Gaps (ex-reports):  54%|█████▍    | 3857/7111 [14:24<12:01,  4.51it/s]

Gaps (ex-reports):  54%|█████▍    | 3858/7111 [14:24<11:39,  4.65it/s]

Gaps (ex-reports):  54%|█████▍    | 3859/7111 [14:25<11:25,  4.75it/s]

Gaps (ex-reports):  54%|█████▍    | 3860/7111 [14:25<11:13,  4.83it/s]

Gaps (ex-reports):  54%|█████▍    | 3861/7111 [14:25<11:06,  4.88it/s]

Gaps (ex-reports):  54%|█████▍    | 3862/7111 [14:25<10:52,  4.98it/s]

Gaps (ex-reports):  54%|█████▍    | 3863/7111 [14:25<10:52,  4.98it/s]

Gaps (ex-reports):  54%|█████▍    | 3864/7111 [14:26<10:55,  4.96it/s]

Gaps (ex-reports):  54%|█████▍    | 3865/7111 [14:26<10:51,  4.98it/s]

Gaps (ex-reports):  54%|█████▍    | 3866/7111 [14:26<10:50,  4.98it/s]

Gaps (ex-reports):  54%|█████▍    | 3867/7111 [14:26<11:03,  4.89it/s]

Gaps (ex-reports):  54%|█████▍    | 3868/7111 [14:26<11:13,  4.81it/s]

Gaps (ex-reports):  54%|█████▍    | 3869/7111 [14:27<11:01,  4.90it/s]

Gaps (ex-reports):  54%|█████▍    | 3870/7111 [14:27<11:08,  4.85it/s]

Gaps (ex-reports):  54%|█████▍    | 3871/7111 [14:27<11:06,  4.86it/s]

Gaps (ex-reports):  54%|█████▍    | 3872/7111 [14:27<11:20,  4.76it/s]

Gaps (ex-reports):  54%|█████▍    | 3873/7111 [14:28<11:33,  4.67it/s]

Gaps (ex-reports):  54%|█████▍    | 3874/7111 [14:28<11:15,  4.79it/s]

Gaps (ex-reports):  54%|█████▍    | 3875/7111 [14:28<11:14,  4.79it/s]

Gaps (ex-reports):  55%|█████▍    | 3876/7111 [14:28<11:33,  4.66it/s]

Gaps (ex-reports):  55%|█████▍    | 3877/7111 [14:28<13:25,  4.02it/s]

Gaps (ex-reports):  55%|█████▍    | 3878/7111 [14:29<12:38,  4.26it/s]

Gaps (ex-reports):  55%|█████▍    | 3879/7111 [14:29<12:15,  4.40it/s]

Gaps (ex-reports):  55%|█████▍    | 3880/7111 [14:29<11:43,  4.59it/s]

Gaps (ex-reports):  55%|█████▍    | 3881/7111 [14:29<11:21,  4.74it/s]

Gaps (ex-reports):  55%|█████▍    | 3882/7111 [14:30<11:21,  4.74it/s]

Gaps (ex-reports):  55%|█████▍    | 3883/7111 [14:30<11:11,  4.81it/s]

Gaps (ex-reports):  55%|█████▍    | 3884/7111 [14:30<11:09,  4.82it/s]

Gaps (ex-reports):  55%|█████▍    | 3885/7111 [14:30<11:16,  4.77it/s]

Gaps (ex-reports):  55%|█████▍    | 3886/7111 [14:30<11:08,  4.83it/s]

Gaps (ex-reports):  55%|█████▍    | 3887/7111 [14:31<11:21,  4.73it/s]

Gaps (ex-reports):  55%|█████▍    | 3888/7111 [14:31<11:10,  4.81it/s]

Gaps (ex-reports):  55%|█████▍    | 3889/7111 [14:31<11:14,  4.78it/s]

Gaps (ex-reports):  55%|█████▍    | 3890/7111 [14:31<11:09,  4.81it/s]

Gaps (ex-reports):  55%|█████▍    | 3891/7111 [14:31<11:14,  4.78it/s]

Gaps (ex-reports):  55%|█████▍    | 3892/7111 [14:32<11:13,  4.78it/s]

Gaps (ex-reports):  55%|█████▍    | 3893/7111 [14:32<10:58,  4.88it/s]

Gaps (ex-reports):  55%|█████▍    | 3894/7111 [14:32<10:48,  4.96it/s]

Gaps (ex-reports):  55%|█████▍    | 3895/7111 [14:32<10:51,  4.94it/s]

Gaps (ex-reports):  55%|█████▍    | 3896/7111 [14:32<10:42,  5.00it/s]

Gaps (ex-reports):  55%|█████▍    | 3897/7111 [14:33<10:53,  4.92it/s]

Gaps (ex-reports):  55%|█████▍    | 3898/7111 [14:33<10:43,  4.99it/s]

Gaps (ex-reports):  55%|█████▍    | 3899/7111 [14:33<10:52,  4.92it/s]

Gaps (ex-reports):  55%|█████▍    | 3900/7111 [14:33<10:43,  4.99it/s]

Gaps (ex-reports):  55%|█████▍    | 3901/7111 [14:33<10:51,  4.93it/s]

Gaps (ex-reports):  55%|█████▍    | 3902/7111 [14:34<11:04,  4.83it/s]

Gaps (ex-reports):  55%|█████▍    | 3903/7111 [14:34<11:03,  4.84it/s]

Gaps (ex-reports):  55%|█████▍    | 3904/7111 [14:34<11:03,  4.83it/s]

Gaps (ex-reports):  55%|█████▍    | 3905/7111 [14:34<11:01,  4.84it/s]

Gaps (ex-reports):  55%|█████▍    | 3906/7111 [14:34<10:57,  4.88it/s]

Gaps (ex-reports):  55%|█████▍    | 3907/7111 [14:35<11:01,  4.84it/s]

Gaps (ex-reports):  55%|█████▍    | 3908/7111 [14:35<11:07,  4.80it/s]

Gaps (ex-reports):  55%|█████▍    | 3909/7111 [14:35<10:59,  4.86it/s]

Gaps (ex-reports):  55%|█████▍    | 3910/7111 [14:35<11:00,  4.85it/s]

Gaps (ex-reports):  55%|█████▍    | 3911/7111 [14:35<10:43,  4.97it/s]

Gaps (ex-reports):  55%|█████▌    | 3912/7111 [14:36<10:41,  4.98it/s]

Gaps (ex-reports):  55%|█████▌    | 3913/7111 [14:36<10:44,  4.96it/s]

Gaps (ex-reports):  55%|█████▌    | 3914/7111 [14:36<11:02,  4.82it/s]

Gaps (ex-reports):  55%|█████▌    | 3915/7111 [14:36<11:13,  4.75it/s]

Gaps (ex-reports):  55%|█████▌    | 3916/7111 [14:37<11:02,  4.82it/s]

Gaps (ex-reports):  55%|█████▌    | 3917/7111 [14:37<11:07,  4.79it/s]

Gaps (ex-reports):  55%|█████▌    | 3918/7111 [14:37<11:08,  4.78it/s]

Gaps (ex-reports):  55%|█████▌    | 3919/7111 [14:37<11:57,  4.45it/s]

Gaps (ex-reports):  55%|█████▌    | 3920/7111 [14:37<12:08,  4.38it/s]

Gaps (ex-reports):  55%|█████▌    | 3921/7111 [14:38<12:29,  4.26it/s]

Gaps (ex-reports):  55%|█████▌    | 3922/7111 [14:38<12:18,  4.32it/s]

Gaps (ex-reports):  55%|█████▌    | 3923/7111 [14:38<11:49,  4.49it/s]

Gaps (ex-reports):  55%|█████▌    | 3924/7111 [14:38<11:27,  4.64it/s]

Gaps (ex-reports):  55%|█████▌    | 3925/7111 [14:39<11:19,  4.69it/s]

Gaps (ex-reports):  55%|█████▌    | 3926/7111 [14:39<11:14,  4.72it/s]

Gaps (ex-reports):  55%|█████▌    | 3927/7111 [14:39<11:07,  4.77it/s]

Gaps (ex-reports):  55%|█████▌    | 3928/7111 [14:39<11:05,  4.78it/s]

Gaps (ex-reports):  55%|█████▌    | 3929/7111 [14:39<11:11,  4.74it/s]

Gaps (ex-reports):  55%|█████▌    | 3930/7111 [14:40<11:02,  4.80it/s]

Gaps (ex-reports):  55%|█████▌    | 3931/7111 [14:40<11:09,  4.75it/s]

Gaps (ex-reports):  55%|█████▌    | 3932/7111 [14:40<11:02,  4.80it/s]

Gaps (ex-reports):  55%|█████▌    | 3933/7111 [14:40<10:37,  4.98it/s]

Gaps (ex-reports):  55%|█████▌    | 3934/7111 [14:40<10:55,  4.85it/s]

Gaps (ex-reports):  55%|█████▌    | 3935/7111 [14:41<10:50,  4.88it/s]

Gaps (ex-reports):  55%|█████▌    | 3936/7111 [14:41<10:34,  5.00it/s]

Gaps (ex-reports):  55%|█████▌    | 3937/7111 [14:41<10:34,  5.01it/s]

Gaps (ex-reports):  55%|█████▌    | 3938/7111 [14:41<10:43,  4.93it/s]

Gaps (ex-reports):  55%|█████▌    | 3939/7111 [14:41<11:26,  4.62it/s]

Gaps (ex-reports):  55%|█████▌    | 3940/7111 [14:42<11:27,  4.61it/s]

Gaps (ex-reports):  55%|█████▌    | 3941/7111 [14:42<11:07,  4.75it/s]

Gaps (ex-reports):  55%|█████▌    | 3942/7111 [14:42<11:10,  4.73it/s]

Gaps (ex-reports):  55%|█████▌    | 3943/7111 [14:42<11:04,  4.77it/s]

Gaps (ex-reports):  55%|█████▌    | 3944/7111 [14:42<11:05,  4.76it/s]

Gaps (ex-reports):  55%|█████▌    | 3945/7111 [14:43<10:57,  4.81it/s]

Gaps (ex-reports):  55%|█████▌    | 3946/7111 [14:43<10:50,  4.86it/s]

Gaps (ex-reports):  56%|█████▌    | 3947/7111 [14:43<10:50,  4.86it/s]

Gaps (ex-reports):  56%|█████▌    | 3948/7111 [14:43<10:54,  4.83it/s]

Gaps (ex-reports):  56%|█████▌    | 3949/7111 [14:43<10:48,  4.88it/s]

Gaps (ex-reports):  56%|█████▌    | 3950/7111 [14:44<10:38,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 3951/7111 [14:44<10:41,  4.92it/s]

Gaps (ex-reports):  56%|█████▌    | 3952/7111 [14:44<10:53,  4.84it/s]

Gaps (ex-reports):  56%|█████▌    | 3953/7111 [14:44<10:37,  4.96it/s]

Gaps (ex-reports):  56%|█████▌    | 3954/7111 [14:44<10:40,  4.93it/s]

Gaps (ex-reports):  56%|█████▌    | 3955/7111 [14:45<10:37,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 3956/7111 [14:45<10:44,  4.90it/s]

Gaps (ex-reports):  56%|█████▌    | 3957/7111 [14:45<10:32,  4.98it/s]

Gaps (ex-reports):  56%|█████▌    | 3958/7111 [14:45<10:32,  4.99it/s]

Gaps (ex-reports):  56%|█████▌    | 3959/7111 [14:45<10:37,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 3960/7111 [14:46<10:43,  4.89it/s]

Gaps (ex-reports):  56%|█████▌    | 3961/7111 [14:46<10:50,  4.84it/s]

Gaps (ex-reports):  56%|█████▌    | 3962/7111 [14:46<10:48,  4.86it/s]

Gaps (ex-reports):  56%|█████▌    | 3963/7111 [14:46<10:38,  4.93it/s]

Gaps (ex-reports):  56%|█████▌    | 3964/7111 [14:47<10:38,  4.93it/s]

Gaps (ex-reports):  56%|█████▌    | 3965/7111 [14:47<10:26,  5.03it/s]

Gaps (ex-reports):  56%|█████▌    | 3966/7111 [14:47<10:29,  5.00it/s]

Gaps (ex-reports):  56%|█████▌    | 3967/7111 [14:47<10:33,  4.97it/s]

Gaps (ex-reports):  56%|█████▌    | 3968/7111 [14:47<10:36,  4.94it/s]

Gaps (ex-reports):  56%|█████▌    | 3969/7111 [14:48<10:41,  4.89it/s]

Gaps (ex-reports):  56%|█████▌    | 3970/7111 [14:48<10:28,  5.00it/s]

Gaps (ex-reports):  56%|█████▌    | 3971/7111 [14:48<10:19,  5.07it/s]

Gaps (ex-reports):  56%|█████▌    | 3972/7111 [14:48<10:36,  4.94it/s]

Gaps (ex-reports):  56%|█████▌    | 3973/7111 [14:48<10:38,  4.91it/s]

Gaps (ex-reports):  56%|█████▌    | 3974/7111 [14:49<10:39,  4.91it/s]

Gaps (ex-reports):  56%|█████▌    | 3975/7111 [14:49<10:25,  5.01it/s]

Gaps (ex-reports):  56%|█████▌    | 3976/7111 [14:49<10:20,  5.05it/s]

Gaps (ex-reports):  56%|█████▌    | 3977/7111 [14:49<10:18,  5.07it/s]

Gaps (ex-reports):  56%|█████▌    | 3978/7111 [14:49<10:28,  4.99it/s]

Gaps (ex-reports):  56%|█████▌    | 3979/7111 [14:50<10:32,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 3980/7111 [14:50<10:47,  4.83it/s]

Gaps (ex-reports):  56%|█████▌    | 3981/7111 [14:50<10:42,  4.87it/s]

Gaps (ex-reports):  56%|█████▌    | 3982/7111 [14:50<10:38,  4.90it/s]

Gaps (ex-reports):  56%|█████▌    | 3983/7111 [14:50<10:27,  4.98it/s]

Gaps (ex-reports):  56%|█████▌    | 3984/7111 [14:51<10:33,  4.94it/s]

Gaps (ex-reports):  56%|█████▌    | 3985/7111 [14:51<10:36,  4.91it/s]

Gaps (ex-reports):  56%|█████▌    | 3986/7111 [14:51<10:28,  4.97it/s]

Gaps (ex-reports):  56%|█████▌    | 3987/7111 [14:51<10:31,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 3988/7111 [14:51<10:39,  4.88it/s]

Gaps (ex-reports):  56%|█████▌    | 3989/7111 [14:52<10:42,  4.86it/s]

Gaps (ex-reports):  56%|█████▌    | 3990/7111 [14:52<10:45,  4.84it/s]

Gaps (ex-reports):  56%|█████▌    | 3991/7111 [14:52<10:37,  4.90it/s]

Gaps (ex-reports):  56%|█████▌    | 3992/7111 [14:52<10:37,  4.89it/s]

Gaps (ex-reports):  56%|█████▌    | 3993/7111 [14:52<10:21,  5.02it/s]

Gaps (ex-reports):  56%|█████▌    | 3994/7111 [14:53<10:21,  5.01it/s]

Gaps (ex-reports):  56%|█████▌    | 3995/7111 [14:53<10:22,  5.00it/s]

Gaps (ex-reports):  56%|█████▌    | 3996/7111 [14:53<10:22,  5.00it/s]

Gaps (ex-reports):  56%|█████▌    | 3997/7111 [14:53<10:29,  4.95it/s]

Gaps (ex-reports):  56%|█████▌    | 3998/7111 [14:53<10:40,  4.86it/s]

Gaps (ex-reports):  56%|█████▌    | 3999/7111 [14:54<10:37,  4.88it/s]

Gaps (ex-reports):  56%|█████▋    | 4000/7111 [14:54<10:40,  4.86it/s]

Gaps (ex-reports):  56%|█████▋    | 4001/7111 [14:54<10:40,  4.85it/s]

Gaps (ex-reports):  56%|█████▋    | 4002/7111 [14:54<10:33,  4.91it/s]

Gaps (ex-reports):  56%|█████▋    | 4003/7111 [14:54<10:36,  4.88it/s]

Gaps (ex-reports):  56%|█████▋    | 4004/7111 [14:55<10:36,  4.88it/s]

Gaps (ex-reports):  56%|█████▋    | 4005/7111 [14:55<10:40,  4.85it/s]

Gaps (ex-reports):  56%|█████▋    | 4006/7111 [14:55<10:35,  4.89it/s]

Gaps (ex-reports):  56%|█████▋    | 4007/7111 [14:55<10:38,  4.86it/s]

Gaps (ex-reports):  56%|█████▋    | 4008/7111 [14:55<10:56,  4.73it/s]

Gaps (ex-reports):  56%|█████▋    | 4009/7111 [14:56<10:37,  4.87it/s]

Gaps (ex-reports):  56%|█████▋    | 4010/7111 [14:56<10:40,  4.84it/s]

Gaps (ex-reports):  56%|█████▋    | 4011/7111 [14:56<10:44,  4.81it/s]

Gaps (ex-reports):  56%|█████▋    | 4012/7111 [14:56<10:44,  4.81it/s]

Gaps (ex-reports):  56%|█████▋    | 4013/7111 [14:56<10:44,  4.81it/s]

Gaps (ex-reports):  56%|█████▋    | 4014/7111 [14:57<10:41,  4.83it/s]

Gaps (ex-reports):  56%|█████▋    | 4015/7111 [14:57<10:43,  4.81it/s]

Gaps (ex-reports):  56%|█████▋    | 4016/7111 [14:57<10:43,  4.81it/s]

Gaps (ex-reports):  56%|█████▋    | 4017/7111 [14:57<10:41,  4.82it/s]

Gaps (ex-reports):  57%|█████▋    | 4018/7111 [14:58<10:31,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4019/7111 [14:58<10:35,  4.86it/s]

Gaps (ex-reports):  57%|█████▋    | 4020/7111 [14:58<10:39,  4.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4021/7111 [14:58<10:41,  4.81it/s]

Gaps (ex-reports):  57%|█████▋    | 4022/7111 [14:58<10:38,  4.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4023/7111 [14:59<10:32,  4.88it/s]

Gaps (ex-reports):  57%|█████▋    | 4024/7111 [14:59<10:22,  4.96it/s]

Gaps (ex-reports):  57%|█████▋    | 4025/7111 [14:59<10:11,  5.04it/s]

Gaps (ex-reports):  57%|█████▋    | 4026/7111 [14:59<10:18,  4.99it/s]

Gaps (ex-reports):  57%|█████▋    | 4027/7111 [14:59<10:19,  4.98it/s]

Gaps (ex-reports):  57%|█████▋    | 4028/7111 [15:00<10:19,  4.98it/s]

Gaps (ex-reports):  57%|█████▋    | 4029/7111 [15:00<10:11,  5.04it/s]

Gaps (ex-reports):  57%|█████▋    | 4030/7111 [15:00<10:07,  5.07it/s]

Gaps (ex-reports):  57%|█████▋    | 4031/7111 [15:00<10:11,  5.03it/s]

Gaps (ex-reports):  57%|█████▋    | 4032/7111 [15:00<10:17,  4.98it/s]

Gaps (ex-reports):  57%|█████▋    | 4033/7111 [15:01<10:26,  4.91it/s]

Gaps (ex-reports):  57%|█████▋    | 4034/7111 [15:01<10:35,  4.85it/s]

Gaps (ex-reports):  57%|█████▋    | 4035/7111 [15:01<10:32,  4.87it/s]

Gaps (ex-reports):  57%|█████▋    | 4036/7111 [15:01<10:38,  4.81it/s]

Gaps (ex-reports):  57%|█████▋    | 4037/7111 [15:01<10:46,  4.75it/s]

Gaps (ex-reports):  57%|█████▋    | 4038/7111 [15:02<10:37,  4.82it/s]

Gaps (ex-reports):  57%|█████▋    | 4039/7111 [15:02<10:34,  4.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4040/7111 [15:02<10:35,  4.83it/s]

Gaps (ex-reports):  57%|█████▋    | 4041/7111 [15:02<10:27,  4.89it/s]

Gaps (ex-reports):  57%|█████▋    | 4042/7111 [15:02<10:30,  4.87it/s]

Gaps (ex-reports):  57%|█████▋    | 4043/7111 [15:03<10:42,  4.77it/s]

Gaps (ex-reports):  57%|█████▋    | 4044/7111 [15:03<10:31,  4.86it/s]

Gaps (ex-reports):  57%|█████▋    | 4045/7111 [15:03<10:28,  4.88it/s]

Gaps (ex-reports):  57%|█████▋    | 4046/7111 [15:03<10:18,  4.96it/s]

Gaps (ex-reports):  57%|█████▋    | 4047/7111 [15:03<10:42,  4.77it/s]

Gaps (ex-reports):  57%|█████▋    | 4048/7111 [15:04<10:39,  4.79it/s]

Gaps (ex-reports):  57%|█████▋    | 4049/7111 [15:04<10:38,  4.79it/s]

Gaps (ex-reports):  57%|█████▋    | 4050/7111 [15:04<10:35,  4.82it/s]

Gaps (ex-reports):  57%|█████▋    | 4051/7111 [15:04<10:29,  4.86it/s]

Gaps (ex-reports):  57%|█████▋    | 4052/7111 [15:05<10:44,  4.74it/s]

Gaps (ex-reports):  57%|█████▋    | 4053/7111 [15:05<10:42,  4.76it/s]

Gaps (ex-reports):  57%|█████▋    | 4054/7111 [15:05<10:25,  4.88it/s]

Gaps (ex-reports):  57%|█████▋    | 4055/7111 [15:05<10:15,  4.97it/s]

Gaps (ex-reports):  57%|█████▋    | 4056/7111 [15:05<10:07,  5.03it/s]

Gaps (ex-reports):  57%|█████▋    | 4057/7111 [15:05<10:01,  5.07it/s]

Gaps (ex-reports):  57%|█████▋    | 4058/7111 [15:06<10:00,  5.09it/s]

Gaps (ex-reports):  57%|█████▋    | 4059/7111 [15:06<10:17,  4.94it/s]

Gaps (ex-reports):  57%|█████▋    | 4060/7111 [15:06<10:14,  4.97it/s]

Gaps (ex-reports):  57%|█████▋    | 4061/7111 [15:06<10:18,  4.93it/s]

Gaps (ex-reports):  57%|█████▋    | 4062/7111 [15:07<10:22,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4063/7111 [15:07<10:31,  4.83it/s]

Gaps (ex-reports):  57%|█████▋    | 4064/7111 [15:07<10:21,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4065/7111 [15:07<10:10,  4.99it/s]

Gaps (ex-reports):  57%|█████▋    | 4066/7111 [15:07<10:14,  4.95it/s]

Gaps (ex-reports):  57%|█████▋    | 4067/7111 [15:08<10:12,  4.97it/s]

Gaps (ex-reports):  57%|█████▋    | 4068/7111 [15:08<10:20,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4069/7111 [15:08<10:22,  4.89it/s]

Gaps (ex-reports):  57%|█████▋    | 4070/7111 [15:08<10:20,  4.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4071/7111 [15:08<10:30,  4.82it/s]

Gaps (ex-reports):  57%|█████▋    | 4072/7111 [15:09<14:20,  3.53it/s]

Gaps (ex-reports):  57%|█████▋    | 4073/7111 [15:09<13:18,  3.81it/s]

Gaps (ex-reports):  57%|█████▋    | 4074/7111 [15:09<12:23,  4.08it/s]

Gaps (ex-reports):  57%|█████▋    | 4075/7111 [15:09<11:55,  4.25it/s]

Gaps (ex-reports):  57%|█████▋    | 4076/7111 [15:10<11:23,  4.44it/s]

Gaps (ex-reports):  57%|█████▋    | 4077/7111 [15:10<11:11,  4.52it/s]

Gaps (ex-reports):  57%|█████▋    | 4078/7111 [15:10<10:55,  4.63it/s]

Gaps (ex-reports):  57%|█████▋    | 4079/7111 [15:10<10:48,  4.67it/s]

Gaps (ex-reports):  57%|█████▋    | 4080/7111 [15:10<10:38,  4.75it/s]

Gaps (ex-reports):  57%|█████▋    | 4081/7111 [15:11<10:25,  4.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4082/7111 [15:11<10:32,  4.79it/s]

Gaps (ex-reports):  57%|█████▋    | 4083/7111 [15:11<10:26,  4.83it/s]

Gaps (ex-reports):  57%|█████▋    | 4084/7111 [15:11<10:13,  4.93it/s]

Gaps (ex-reports):  57%|█████▋    | 4085/7111 [15:11<10:14,  4.92it/s]

Gaps (ex-reports):  57%|█████▋    | 4086/7111 [15:12<10:06,  4.99it/s]

Gaps (ex-reports):  57%|█████▋    | 4087/7111 [15:12<10:02,  5.02it/s]

Gaps (ex-reports):  57%|█████▋    | 4088/7111 [15:12<10:13,  4.92it/s]

Gaps (ex-reports):  58%|█████▊    | 4089/7111 [15:12<10:11,  4.94it/s]

Gaps (ex-reports):  58%|█████▊    | 4090/7111 [15:12<10:18,  4.88it/s]

Gaps (ex-reports):  58%|█████▊    | 4091/7111 [15:13<10:19,  4.87it/s]

Gaps (ex-reports):  58%|█████▊    | 4092/7111 [15:13<10:08,  4.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4093/7111 [15:13<10:08,  4.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4094/7111 [15:13<10:00,  5.02it/s]

Gaps (ex-reports):  58%|█████▊    | 4095/7111 [15:13<09:54,  5.08it/s]

Gaps (ex-reports):  58%|█████▊    | 4096/7111 [15:14<09:57,  5.05it/s]

Gaps (ex-reports):  58%|█████▊    | 4097/7111 [15:14<09:57,  5.04it/s]

Gaps (ex-reports):  58%|█████▊    | 4098/7111 [15:14<09:53,  5.08it/s]

Gaps (ex-reports):  58%|█████▊    | 4099/7111 [15:14<10:06,  4.97it/s]

Gaps (ex-reports):  58%|█████▊    | 4100/7111 [15:14<10:07,  4.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4101/7111 [15:15<09:56,  5.05it/s]

Gaps (ex-reports):  58%|█████▊    | 4102/7111 [15:15<09:53,  5.07it/s]

Gaps (ex-reports):  58%|█████▊    | 4103/7111 [15:15<09:46,  5.13it/s]

Gaps (ex-reports):  58%|█████▊    | 4104/7111 [15:15<09:45,  5.13it/s]

Gaps (ex-reports):  58%|█████▊    | 4105/7111 [15:15<09:42,  5.16it/s]

Gaps (ex-reports):  58%|█████▊    | 4106/7111 [15:16<09:53,  5.06it/s]

Gaps (ex-reports):  58%|█████▊    | 4107/7111 [15:16<09:52,  5.07it/s]

Gaps (ex-reports):  58%|█████▊    | 4108/7111 [15:16<10:06,  4.95it/s]

Gaps (ex-reports):  58%|█████▊    | 4109/7111 [15:16<10:04,  4.97it/s]

Gaps (ex-reports):  58%|█████▊    | 4110/7111 [15:16<10:01,  4.99it/s]

Gaps (ex-reports):  58%|█████▊    | 4111/7111 [15:17<10:06,  4.94it/s]

Gaps (ex-reports):  58%|█████▊    | 4112/7111 [15:17<10:08,  4.93it/s]

Gaps (ex-reports):  58%|█████▊    | 4113/7111 [15:17<10:04,  4.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4114/7111 [15:17<10:04,  4.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4115/7111 [15:17<10:09,  4.91it/s]

Gaps (ex-reports):  58%|█████▊    | 4116/7111 [15:18<10:01,  4.98it/s]

Gaps (ex-reports):  58%|█████▊    | 4117/7111 [15:18<10:08,  4.92it/s]

Gaps (ex-reports):  58%|█████▊    | 4118/7111 [15:18<10:06,  4.93it/s]

Gaps (ex-reports):  58%|█████▊    | 4119/7111 [15:18<10:07,  4.92it/s]

Gaps (ex-reports):  58%|█████▊    | 4120/7111 [15:18<10:10,  4.90it/s]

Gaps (ex-reports):  58%|█████▊    | 4121/7111 [15:19<10:16,  4.85it/s]

Gaps (ex-reports):  58%|█████▊    | 4122/7111 [15:19<10:09,  4.90it/s]

Gaps (ex-reports):  58%|█████▊    | 4123/7111 [15:19<10:02,  4.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4124/7111 [15:19<10:13,  4.87it/s]

Gaps (ex-reports):  58%|█████▊    | 4125/7111 [15:21<36:47,  1.35it/s]

Gaps (ex-reports):  58%|█████▊    | 4126/7111 [15:22<28:46,  1.73it/s]

Gaps (ex-reports):  58%|█████▊    | 4127/7111 [15:22<23:17,  2.13it/s]

Gaps (ex-reports):  58%|█████▊    | 4128/7111 [15:22<19:14,  2.58it/s]

Gaps (ex-reports):  58%|█████▊    | 4129/7111 [15:22<16:36,  2.99it/s]

Gaps (ex-reports):  58%|█████▊    | 4130/7111 [15:22<14:47,  3.36it/s]

Gaps (ex-reports):  58%|█████▊    | 4131/7111 [15:23<13:33,  3.66it/s]

Gaps (ex-reports):  58%|█████▊    | 4132/7111 [15:23<12:31,  3.96it/s]

Gaps (ex-reports):  58%|█████▊    | 4133/7111 [15:23<11:58,  4.14it/s]

Gaps (ex-reports):  58%|█████▊    | 4134/7111 [15:23<11:14,  4.41it/s]

Gaps (ex-reports):  58%|█████▊    | 4135/7111 [15:23<11:01,  4.50it/s]

Gaps (ex-reports):  58%|█████▊    | 4136/7111 [15:24<10:39,  4.65it/s]

Gaps (ex-reports):  58%|█████▊    | 4137/7111 [15:24<10:42,  4.63it/s]

Gaps (ex-reports):  58%|█████▊    | 4138/7111 [15:24<10:33,  4.69it/s]

Gaps (ex-reports):  58%|█████▊    | 4139/7111 [15:24<10:18,  4.81it/s]

Gaps (ex-reports):  58%|█████▊    | 4140/7111 [15:24<10:10,  4.86it/s]

Gaps (ex-reports):  58%|█████▊    | 4141/7111 [15:25<09:59,  4.95it/s]

Gaps (ex-reports):  58%|█████▊    | 4142/7111 [15:25<10:02,  4.93it/s]

Gaps (ex-reports):  58%|█████▊    | 4143/7111 [15:25<10:14,  4.83it/s]

Gaps (ex-reports):  58%|█████▊    | 4144/7111 [15:25<10:13,  4.83it/s]

Gaps (ex-reports):  58%|█████▊    | 4145/7111 [15:25<10:08,  4.88it/s]

Gaps (ex-reports):  58%|█████▊    | 4146/7111 [15:26<09:59,  4.95it/s]

Gaps (ex-reports):  58%|█████▊    | 4147/7111 [15:26<10:06,  4.89it/s]

Gaps (ex-reports):  58%|█████▊    | 4148/7111 [15:26<10:05,  4.90it/s]

Gaps (ex-reports):  58%|█████▊    | 4149/7111 [15:26<09:56,  4.97it/s]

Gaps (ex-reports):  58%|█████▊    | 4150/7111 [15:26<10:00,  4.93it/s]

Gaps (ex-reports):  58%|█████▊    | 4151/7111 [15:27<10:12,  4.83it/s]

Gaps (ex-reports):  58%|█████▊    | 4152/7111 [15:27<10:04,  4.90it/s]

Gaps (ex-reports):  58%|█████▊    | 4153/7111 [15:27<09:54,  4.98it/s]

Gaps (ex-reports):  58%|█████▊    | 4154/7111 [15:27<09:50,  5.01it/s]

Gaps (ex-reports):  58%|█████▊    | 4155/7111 [15:27<09:50,  5.00it/s]

Gaps (ex-reports):  58%|█████▊    | 4156/7111 [15:28<09:57,  4.95it/s]

Gaps (ex-reports):  58%|█████▊    | 4157/7111 [15:28<09:56,  4.95it/s]

Gaps (ex-reports):  58%|█████▊    | 4158/7111 [15:28<09:48,  5.02it/s]

Gaps (ex-reports):  58%|█████▊    | 4159/7111 [15:28<09:54,  4.96it/s]

Gaps (ex-reports):  59%|█████▊    | 4160/7111 [15:28<10:06,  4.86it/s]

Gaps (ex-reports):  59%|█████▊    | 4161/7111 [15:29<10:00,  4.91it/s]

Gaps (ex-reports):  59%|█████▊    | 4162/7111 [15:29<10:04,  4.88it/s]

Gaps (ex-reports):  59%|█████▊    | 4163/7111 [15:29<10:04,  4.88it/s]

Gaps (ex-reports):  59%|█████▊    | 4164/7111 [15:29<10:12,  4.81it/s]

Gaps (ex-reports):  59%|█████▊    | 4165/7111 [15:29<10:07,  4.85it/s]

Gaps (ex-reports):  59%|█████▊    | 4166/7111 [15:30<09:55,  4.95it/s]

Gaps (ex-reports):  59%|█████▊    | 4167/7111 [15:30<09:50,  4.99it/s]

Gaps (ex-reports):  59%|█████▊    | 4168/7111 [15:30<09:52,  4.97it/s]

Gaps (ex-reports):  59%|█████▊    | 4169/7111 [15:30<09:59,  4.91it/s]

Gaps (ex-reports):  59%|█████▊    | 4170/7111 [15:30<10:02,  4.88it/s]

Gaps (ex-reports):  59%|█████▊    | 4171/7111 [15:31<09:54,  4.95it/s]

Gaps (ex-reports):  59%|█████▊    | 4172/7111 [15:31<10:00,  4.89it/s]

Gaps (ex-reports):  59%|█████▊    | 4173/7111 [15:31<10:03,  4.87it/s]

Gaps (ex-reports):  59%|█████▊    | 4174/7111 [15:31<10:09,  4.82it/s]

Gaps (ex-reports):  59%|█████▊    | 4175/7111 [15:32<10:02,  4.87it/s]

Gaps (ex-reports):  59%|█████▊    | 4176/7111 [15:32<10:06,  4.84it/s]

Gaps (ex-reports):  59%|█████▊    | 4177/7111 [15:32<10:13,  4.78it/s]

Gaps (ex-reports):  59%|█████▉    | 4178/7111 [15:32<10:08,  4.82it/s]

Gaps (ex-reports):  59%|█████▉    | 4179/7111 [15:32<10:17,  4.75it/s]

Gaps (ex-reports):  59%|█████▉    | 4180/7111 [15:33<10:00,  4.88it/s]

Gaps (ex-reports):  59%|█████▉    | 4181/7111 [15:33<10:06,  4.83it/s]

Gaps (ex-reports):  59%|█████▉    | 4182/7111 [15:33<09:51,  4.96it/s]

Gaps (ex-reports):  59%|█████▉    | 4183/7111 [15:33<09:45,  5.00it/s]

Gaps (ex-reports):  59%|█████▉    | 4184/7111 [15:33<09:51,  4.95it/s]

Gaps (ex-reports):  59%|█████▉    | 4185/7111 [15:34<09:52,  4.94it/s]

Gaps (ex-reports):  59%|█████▉    | 4186/7111 [15:34<15:52,  3.07it/s]

Gaps (ex-reports):  59%|█████▉    | 4187/7111 [15:34<14:05,  3.46it/s]

Gaps (ex-reports):  59%|█████▉    | 4188/7111 [15:35<12:37,  3.86it/s]

Gaps (ex-reports):  59%|█████▉    | 4189/7111 [15:35<11:50,  4.11it/s]

Gaps (ex-reports):  59%|█████▉    | 4190/7111 [15:35<11:18,  4.30it/s]

Gaps (ex-reports):  59%|█████▉    | 4191/7111 [15:35<10:50,  4.49it/s]

Gaps (ex-reports):  59%|█████▉    | 4192/7111 [15:35<10:33,  4.61it/s]

Gaps (ex-reports):  59%|█████▉    | 4193/7111 [15:36<10:27,  4.65it/s]

Gaps (ex-reports):  59%|█████▉    | 4194/7111 [15:36<10:17,  4.72it/s]

Gaps (ex-reports):  59%|█████▉    | 4195/7111 [15:36<10:18,  4.71it/s]

Gaps (ex-reports):  59%|█████▉    | 4196/7111 [15:36<10:12,  4.76it/s]

Gaps (ex-reports):  59%|█████▉    | 4197/7111 [15:36<10:10,  4.77it/s]

Gaps (ex-reports):  59%|█████▉    | 4198/7111 [15:37<10:09,  4.78it/s]

Gaps (ex-reports):  59%|█████▉    | 4199/7111 [15:37<09:58,  4.87it/s]

Gaps (ex-reports):  59%|█████▉    | 4200/7111 [15:37<09:51,  4.92it/s]

Gaps (ex-reports):  59%|█████▉    | 4201/7111 [15:37<10:00,  4.85it/s]

Gaps (ex-reports):  59%|█████▉    | 4202/7111 [15:37<09:51,  4.92it/s]

Gaps (ex-reports):  59%|█████▉    | 4203/7111 [15:38<10:00,  4.84it/s]

Gaps (ex-reports):  59%|█████▉    | 4204/7111 [15:38<09:48,  4.94it/s]

Gaps (ex-reports):  59%|█████▉    | 4205/7111 [15:39<17:31,  2.76it/s]

Gaps (ex-reports):  59%|█████▉    | 4206/7111 [15:39<21:56,  2.21it/s]

Gaps (ex-reports):  59%|█████▉    | 4207/7111 [15:39<18:31,  2.61it/s]

Gaps (ex-reports):  59%|█████▉    | 4208/7111 [15:40<15:53,  3.05it/s]

Gaps (ex-reports):  59%|█████▉    | 4209/7111 [15:40<13:58,  3.46it/s]

Gaps (ex-reports):  59%|█████▉    | 4210/7111 [15:40<12:38,  3.82it/s]

Gaps (ex-reports):  59%|█████▉    | 4211/7111 [15:40<11:36,  4.16it/s]

Gaps (ex-reports):  59%|█████▉    | 4212/7111 [15:40<10:52,  4.44it/s]

Gaps (ex-reports):  59%|█████▉    | 4213/7111 [15:41<10:38,  4.54it/s]

Gaps (ex-reports):  59%|█████▉    | 4214/7111 [15:41<10:14,  4.71it/s]

Gaps (ex-reports):  59%|█████▉    | 4215/7111 [15:41<09:58,  4.84it/s]

Gaps (ex-reports):  59%|█████▉    | 4216/7111 [15:41<09:46,  4.93it/s]

Gaps (ex-reports):  59%|█████▉    | 4217/7111 [15:41<09:51,  4.89it/s]

Gaps (ex-reports):  59%|█████▉    | 4218/7111 [15:42<09:53,  4.87it/s]

Gaps (ex-reports):  59%|█████▉    | 4219/7111 [15:42<09:40,  4.98it/s]

Gaps (ex-reports):  59%|█████▉    | 4220/7111 [15:42<09:54,  4.87it/s]

Gaps (ex-reports):  59%|█████▉    | 4221/7111 [15:42<09:51,  4.88it/s]

Gaps (ex-reports):  59%|█████▉    | 4222/7111 [15:42<09:43,  4.95it/s]

Gaps (ex-reports):  59%|█████▉    | 4223/7111 [15:43<09:46,  4.92it/s]

Gaps (ex-reports):  59%|█████▉    | 4224/7111 [15:43<10:18,  4.67it/s]

Gaps (ex-reports):  59%|█████▉    | 4225/7111 [15:43<10:16,  4.68it/s]

Gaps (ex-reports):  59%|█████▉    | 4226/7111 [15:43<10:21,  4.64it/s]

Gaps (ex-reports):  59%|█████▉    | 4227/7111 [15:44<10:13,  4.70it/s]

Gaps (ex-reports):  59%|█████▉    | 4228/7111 [15:44<09:56,  4.83it/s]

Gaps (ex-reports):  59%|█████▉    | 4229/7111 [15:44<15:06,  3.18it/s]

Gaps (ex-reports):  59%|█████▉    | 4230/7111 [15:45<13:31,  3.55it/s]

Gaps (ex-reports):  59%|█████▉    | 4231/7111 [15:45<13:53,  3.46it/s]

Gaps (ex-reports):  60%|█████▉    | 4232/7111 [15:45<12:39,  3.79it/s]

Gaps (ex-reports):  60%|█████▉    | 4233/7111 [15:45<11:50,  4.05it/s]

Gaps (ex-reports):  60%|█████▉    | 4234/7111 [15:45<11:09,  4.30it/s]

Gaps (ex-reports):  60%|█████▉    | 4235/7111 [15:46<10:52,  4.41it/s]

Gaps (ex-reports):  60%|█████▉    | 4236/7111 [15:46<10:32,  4.54it/s]

Gaps (ex-reports):  60%|█████▉    | 4237/7111 [15:46<10:24,  4.60it/s]

Gaps (ex-reports):  60%|█████▉    | 4238/7111 [15:46<10:05,  4.74it/s]

Gaps (ex-reports):  60%|█████▉    | 4239/7111 [15:46<09:51,  4.86it/s]

Gaps (ex-reports):  60%|█████▉    | 4240/7111 [15:47<10:02,  4.77it/s]

Gaps (ex-reports):  60%|█████▉    | 4241/7111 [15:47<09:48,  4.88it/s]

Gaps (ex-reports):  60%|█████▉    | 4242/7111 [15:47<09:40,  4.94it/s]

Gaps (ex-reports):  60%|█████▉    | 4243/7111 [15:47<09:45,  4.90it/s]

Gaps (ex-reports):  60%|█████▉    | 4244/7111 [15:47<09:30,  5.02it/s]

Gaps (ex-reports):  60%|█████▉    | 4245/7111 [15:48<09:42,  4.92it/s]

Gaps (ex-reports):  60%|█████▉    | 4246/7111 [15:48<09:44,  4.90it/s]

Gaps (ex-reports):  60%|█████▉    | 4247/7111 [15:48<09:48,  4.86it/s]

Gaps (ex-reports):  60%|█████▉    | 4248/7111 [15:48<09:51,  4.84it/s]

Gaps (ex-reports):  60%|█████▉    | 4249/7111 [15:48<09:52,  4.83it/s]

Gaps (ex-reports):  60%|█████▉    | 4250/7111 [15:49<09:53,  4.82it/s]

Gaps (ex-reports):  60%|█████▉    | 4251/7111 [15:49<10:06,  4.72it/s]

Gaps (ex-reports):  60%|█████▉    | 4252/7111 [15:49<14:33,  3.27it/s]

Gaps (ex-reports):  60%|█████▉    | 4253/7111 [15:50<13:12,  3.61it/s]

Gaps (ex-reports):  60%|█████▉    | 4254/7111 [15:50<12:19,  3.87it/s]

Gaps (ex-reports):  60%|█████▉    | 4255/7111 [15:50<11:22,  4.19it/s]

Gaps (ex-reports):  60%|█████▉    | 4256/7111 [15:50<10:53,  4.37it/s]

Gaps (ex-reports):  60%|█████▉    | 4257/7111 [15:50<10:23,  4.58it/s]

Gaps (ex-reports):  60%|█████▉    | 4258/7111 [15:51<10:04,  4.72it/s]

Gaps (ex-reports):  60%|█████▉    | 4259/7111 [15:51<10:06,  4.70it/s]

Gaps (ex-reports):  60%|█████▉    | 4260/7111 [15:51<09:45,  4.87it/s]

Gaps (ex-reports):  60%|█████▉    | 4261/7111 [15:51<09:45,  4.87it/s]

Gaps (ex-reports):  60%|█████▉    | 4262/7111 [15:51<09:49,  4.83it/s]

Gaps (ex-reports):  60%|█████▉    | 4263/7111 [15:52<09:36,  4.94it/s]

Gaps (ex-reports):  60%|█████▉    | 4264/7111 [15:52<09:40,  4.91it/s]

Gaps (ex-reports):  60%|█████▉    | 4265/7111 [15:52<09:41,  4.89it/s]

Gaps (ex-reports):  60%|█████▉    | 4266/7111 [15:52<09:37,  4.93it/s]

Gaps (ex-reports):  60%|██████    | 4267/7111 [15:52<09:41,  4.89it/s]

Gaps (ex-reports):  60%|██████    | 4268/7111 [15:53<09:46,  4.84it/s]

Gaps (ex-reports):  60%|██████    | 4269/7111 [15:53<09:47,  4.84it/s]

Gaps (ex-reports):  60%|██████    | 4270/7111 [15:53<09:43,  4.87it/s]

Gaps (ex-reports):  60%|██████    | 4271/7111 [15:53<09:46,  4.84it/s]

Gaps (ex-reports):  60%|██████    | 4272/7111 [15:54<09:45,  4.85it/s]

Gaps (ex-reports):  60%|██████    | 4273/7111 [15:54<09:32,  4.96it/s]

Gaps (ex-reports):  60%|██████    | 4274/7111 [15:54<09:32,  4.96it/s]

Gaps (ex-reports):  60%|██████    | 4275/7111 [15:54<09:24,  5.02it/s]

Gaps (ex-reports):  60%|██████    | 4276/7111 [15:54<09:51,  4.79it/s]

Gaps (ex-reports):  60%|██████    | 4277/7111 [15:55<09:35,  4.92it/s]

Gaps (ex-reports):  60%|██████    | 4278/7111 [15:55<09:28,  4.98it/s]

Gaps (ex-reports):  60%|██████    | 4279/7111 [15:55<09:36,  4.91it/s]

Gaps (ex-reports):  60%|██████    | 4280/7111 [15:55<09:26,  4.99it/s]

Gaps (ex-reports):  60%|██████    | 4281/7111 [15:55<09:35,  4.92it/s]

Gaps (ex-reports):  60%|██████    | 4282/7111 [15:56<09:54,  4.76it/s]

Gaps (ex-reports):  60%|██████    | 4283/7111 [15:56<09:38,  4.89it/s]

Gaps (ex-reports):  60%|██████    | 4284/7111 [15:56<09:43,  4.84it/s]

Gaps (ex-reports):  60%|██████    | 4285/7111 [15:56<09:39,  4.88it/s]

Gaps (ex-reports):  60%|██████    | 4286/7111 [15:56<09:40,  4.86it/s]

Gaps (ex-reports):  60%|██████    | 4287/7111 [15:57<09:40,  4.86it/s]

Gaps (ex-reports):  60%|██████    | 4288/7111 [15:57<09:44,  4.83it/s]

Gaps (ex-reports):  60%|██████    | 4289/7111 [15:57<09:47,  4.81it/s]

Gaps (ex-reports):  60%|██████    | 4290/7111 [15:57<09:44,  4.82it/s]

Gaps (ex-reports):  60%|██████    | 4291/7111 [15:57<09:45,  4.81it/s]

Gaps (ex-reports):  60%|██████    | 4292/7111 [15:58<09:57,  4.71it/s]

Gaps (ex-reports):  60%|██████    | 4293/7111 [15:58<10:10,  4.62it/s]

Gaps (ex-reports):  60%|██████    | 4294/7111 [15:58<12:08,  3.87it/s]

Gaps (ex-reports):  60%|██████    | 4295/7111 [15:58<11:17,  4.16it/s]

Gaps (ex-reports):  60%|██████    | 4296/7111 [15:59<10:49,  4.33it/s]

Gaps (ex-reports):  60%|██████    | 4297/7111 [15:59<10:19,  4.54it/s]

Gaps (ex-reports):  60%|██████    | 4298/7111 [15:59<10:11,  4.60it/s]

Gaps (ex-reports):  60%|██████    | 4299/7111 [15:59<10:06,  4.63it/s]

Gaps (ex-reports):  60%|██████    | 4300/7111 [15:59<10:03,  4.65it/s]

Gaps (ex-reports):  60%|██████    | 4301/7111 [16:00<09:46,  4.79it/s]

Gaps (ex-reports):  60%|██████    | 4302/7111 [16:00<09:39,  4.85it/s]

Gaps (ex-reports):  61%|██████    | 4303/7111 [16:00<09:51,  4.74it/s]

Gaps (ex-reports):  61%|██████    | 4304/7111 [16:00<09:44,  4.80it/s]

Gaps (ex-reports):  61%|██████    | 4305/7111 [16:00<09:48,  4.77it/s]

Gaps (ex-reports):  61%|██████    | 4306/7111 [16:01<09:40,  4.83it/s]

Gaps (ex-reports):  61%|██████    | 4307/7111 [16:01<09:36,  4.86it/s]

Gaps (ex-reports):  61%|██████    | 4308/7111 [16:01<09:34,  4.88it/s]

Gaps (ex-reports):  61%|██████    | 4309/7111 [16:02<13:38,  3.42it/s]

Gaps (ex-reports):  61%|██████    | 4310/7111 [16:02<12:12,  3.82it/s]

Gaps (ex-reports):  61%|██████    | 4311/7111 [16:02<11:30,  4.05it/s]

Gaps (ex-reports):  61%|██████    | 4312/7111 [16:02<10:56,  4.27it/s]

Gaps (ex-reports):  61%|██████    | 4313/7111 [16:02<10:32,  4.43it/s]

Gaps (ex-reports):  61%|██████    | 4314/7111 [16:03<10:06,  4.61it/s]

Gaps (ex-reports):  61%|██████    | 4315/7111 [16:03<09:57,  4.68it/s]

Gaps (ex-reports):  61%|██████    | 4316/7111 [16:03<09:49,  4.74it/s]

Gaps (ex-reports):  61%|██████    | 4317/7111 [16:03<09:37,  4.84it/s]

Gaps (ex-reports):  61%|██████    | 4318/7111 [16:03<09:29,  4.90it/s]

Gaps (ex-reports):  61%|██████    | 4319/7111 [16:04<09:28,  4.91it/s]

Gaps (ex-reports):  61%|██████    | 4320/7111 [16:04<09:41,  4.80it/s]

Gaps (ex-reports):  61%|██████    | 4321/7111 [16:04<09:38,  4.82it/s]

Gaps (ex-reports):  61%|██████    | 4322/7111 [16:04<09:44,  4.77it/s]

Gaps (ex-reports):  61%|██████    | 4323/7111 [16:04<09:46,  4.75it/s]

Gaps (ex-reports):  61%|██████    | 4324/7111 [16:05<09:43,  4.78it/s]

Gaps (ex-reports):  61%|██████    | 4325/7111 [16:05<09:37,  4.82it/s]

Gaps (ex-reports):  61%|██████    | 4326/7111 [16:05<09:29,  4.89it/s]

Gaps (ex-reports):  61%|██████    | 4327/7111 [16:05<09:24,  4.93it/s]

Gaps (ex-reports):  61%|██████    | 4328/7111 [16:05<09:26,  4.92it/s]

Gaps (ex-reports):  61%|██████    | 4329/7111 [16:06<09:27,  4.91it/s]

Gaps (ex-reports):  61%|██████    | 4330/7111 [16:06<09:20,  4.96it/s]

Gaps (ex-reports):  61%|██████    | 4331/7111 [16:06<09:21,  4.96it/s]

Gaps (ex-reports):  61%|██████    | 4332/7111 [16:06<09:22,  4.94it/s]

Gaps (ex-reports):  61%|██████    | 4333/7111 [16:07<09:44,  4.75it/s]

Gaps (ex-reports):  61%|██████    | 4334/7111 [16:07<09:46,  4.74it/s]

Gaps (ex-reports):  61%|██████    | 4335/7111 [16:07<09:52,  4.68it/s]

Gaps (ex-reports):  61%|██████    | 4336/7111 [16:07<09:41,  4.77it/s]

Gaps (ex-reports):  61%|██████    | 4337/7111 [16:07<09:43,  4.75it/s]

Gaps (ex-reports):  61%|██████    | 4338/7111 [16:08<09:27,  4.89it/s]

Gaps (ex-reports):  61%|██████    | 4339/7111 [16:08<09:24,  4.91it/s]

Gaps (ex-reports):  61%|██████    | 4340/7111 [16:08<09:17,  4.97it/s]

Gaps (ex-reports):  61%|██████    | 4341/7111 [16:08<09:20,  4.94it/s]

Gaps (ex-reports):  61%|██████    | 4342/7111 [16:08<09:23,  4.91it/s]

Gaps (ex-reports):  61%|██████    | 4343/7111 [16:09<09:14,  4.99it/s]

Gaps (ex-reports):  61%|██████    | 4344/7111 [16:09<09:16,  4.97it/s]

Gaps (ex-reports):  61%|██████    | 4345/7111 [16:09<10:27,  4.41it/s]

Gaps (ex-reports):  61%|██████    | 4346/7111 [16:09<10:20,  4.46it/s]

Gaps (ex-reports):  61%|██████    | 4347/7111 [16:09<10:02,  4.59it/s]

Gaps (ex-reports):  61%|██████    | 4348/7111 [16:10<09:53,  4.66it/s]

Gaps (ex-reports):  61%|██████    | 4349/7111 [16:10<09:47,  4.70it/s]

Gaps (ex-reports):  61%|██████    | 4350/7111 [16:10<09:47,  4.70it/s]

Gaps (ex-reports):  61%|██████    | 4351/7111 [16:10<09:42,  4.73it/s]

Gaps (ex-reports):  61%|██████    | 4352/7111 [16:11<09:43,  4.73it/s]

Gaps (ex-reports):  61%|██████    | 4353/7111 [16:11<09:37,  4.78it/s]

Gaps (ex-reports):  61%|██████    | 4354/7111 [16:11<09:31,  4.83it/s]

Gaps (ex-reports):  61%|██████    | 4355/7111 [16:11<09:34,  4.80it/s]

Gaps (ex-reports):  61%|██████▏   | 4356/7111 [16:11<09:30,  4.83it/s]

Gaps (ex-reports):  61%|██████▏   | 4357/7111 [16:12<09:39,  4.75it/s]

Gaps (ex-reports):  61%|██████▏   | 4358/7111 [16:12<17:02,  2.69it/s]

Gaps (ex-reports):  61%|██████▏   | 4359/7111 [16:12<14:43,  3.12it/s]

Gaps (ex-reports):  61%|██████▏   | 4360/7111 [16:13<13:10,  3.48it/s]

Gaps (ex-reports):  61%|██████▏   | 4361/7111 [16:13<12:03,  3.80it/s]

Gaps (ex-reports):  61%|██████▏   | 4362/7111 [16:13<11:24,  4.01it/s]

Gaps (ex-reports):  61%|██████▏   | 4363/7111 [16:13<10:41,  4.29it/s]

Gaps (ex-reports):  61%|██████▏   | 4364/7111 [16:14<16:21,  2.80it/s]

Gaps (ex-reports):  61%|██████▏   | 4365/7111 [16:14<14:16,  3.21it/s]

Gaps (ex-reports):  61%|██████▏   | 4366/7111 [16:14<12:52,  3.56it/s]

Gaps (ex-reports):  61%|██████▏   | 4367/7111 [16:15<11:54,  3.84it/s]

Gaps (ex-reports):  61%|██████▏   | 4368/7111 [16:15<11:02,  4.14it/s]

Gaps (ex-reports):  61%|██████▏   | 4369/7111 [16:15<10:34,  4.32it/s]

Gaps (ex-reports):  61%|██████▏   | 4370/7111 [16:15<10:07,  4.51it/s]

Gaps (ex-reports):  61%|██████▏   | 4371/7111 [16:15<09:48,  4.66it/s]

Gaps (ex-reports):  61%|██████▏   | 4372/7111 [16:16<09:34,  4.77it/s]

Gaps (ex-reports):  61%|██████▏   | 4373/7111 [16:16<09:19,  4.89it/s]

Gaps (ex-reports):  62%|██████▏   | 4374/7111 [16:16<09:23,  4.86it/s]

Gaps (ex-reports):  62%|██████▏   | 4375/7111 [16:17<15:31,  2.94it/s]

Gaps (ex-reports):  62%|██████▏   | 4376/7111 [16:17<13:50,  3.29it/s]

Gaps (ex-reports):  62%|██████▏   | 4377/7111 [16:17<12:26,  3.66it/s]

Gaps (ex-reports):  62%|██████▏   | 4378/7111 [16:17<11:31,  3.95it/s]

Gaps (ex-reports):  62%|██████▏   | 4379/7111 [16:18<11:11,  4.07it/s]

Gaps (ex-reports):  62%|██████▏   | 4380/7111 [16:18<10:37,  4.28it/s]

Gaps (ex-reports):  62%|██████▏   | 4381/7111 [16:18<10:12,  4.45it/s]

Gaps (ex-reports):  62%|██████▏   | 4382/7111 [16:18<09:51,  4.61it/s]

Gaps (ex-reports):  62%|██████▏   | 4383/7111 [16:18<09:53,  4.60it/s]

Gaps (ex-reports):  62%|██████▏   | 4384/7111 [16:19<09:34,  4.74it/s]

Gaps (ex-reports):  62%|██████▏   | 4385/7111 [16:19<09:27,  4.80it/s]

Gaps (ex-reports):  62%|██████▏   | 4386/7111 [16:19<09:11,  4.94it/s]

Gaps (ex-reports):  62%|██████▏   | 4387/7111 [16:19<09:01,  5.03it/s]

Gaps (ex-reports):  62%|██████▏   | 4388/7111 [16:19<08:57,  5.07it/s]

Gaps (ex-reports):  62%|██████▏   | 4389/7111 [16:20<08:58,  5.06it/s]

Gaps (ex-reports):  62%|██████▏   | 4390/7111 [16:20<08:59,  5.04it/s]

Gaps (ex-reports):  62%|██████▏   | 4391/7111 [16:20<09:05,  4.98it/s]

Gaps (ex-reports):  62%|██████▏   | 4392/7111 [16:20<09:01,  5.02it/s]

Gaps (ex-reports):  62%|██████▏   | 4393/7111 [16:20<08:58,  5.05it/s]

Gaps (ex-reports):  62%|██████▏   | 4394/7111 [16:21<09:05,  4.98it/s]

Gaps (ex-reports):  62%|██████▏   | 4395/7111 [16:21<09:20,  4.85it/s]

Gaps (ex-reports):  62%|██████▏   | 4396/7111 [16:21<09:17,  4.87it/s]

Gaps (ex-reports):  62%|██████▏   | 4397/7111 [16:21<09:20,  4.84it/s]

Gaps (ex-reports):  62%|██████▏   | 4398/7111 [16:21<09:27,  4.78it/s]

Gaps (ex-reports):  62%|██████▏   | 4399/7111 [16:22<09:46,  4.62it/s]

Gaps (ex-reports):  62%|██████▏   | 4400/7111 [16:22<11:05,  4.07it/s]

Gaps (ex-reports):  62%|██████▏   | 4401/7111 [16:22<10:33,  4.28it/s]

Gaps (ex-reports):  62%|██████▏   | 4402/7111 [16:22<10:08,  4.45it/s]

Gaps (ex-reports):  62%|██████▏   | 4403/7111 [16:23<10:26,  4.33it/s]

Gaps (ex-reports):  62%|██████▏   | 4404/7111 [16:23<09:58,  4.52it/s]

Gaps (ex-reports):  62%|██████▏   | 4405/7111 [16:23<09:37,  4.69it/s]

Gaps (ex-reports):  62%|██████▏   | 4406/7111 [16:24<19:23,  2.33it/s]

Gaps (ex-reports):  62%|██████▏   | 4407/7111 [16:24<16:22,  2.75it/s]

Gaps (ex-reports):  62%|██████▏   | 4408/7111 [16:24<14:20,  3.14it/s]

Gaps (ex-reports):  62%|██████▏   | 4409/7111 [16:25<12:40,  3.55it/s]

Gaps (ex-reports):  62%|██████▏   | 4410/7111 [16:25<11:27,  3.93it/s]

Gaps (ex-reports):  62%|██████▏   | 4411/7111 [16:25<10:36,  4.24it/s]

Gaps (ex-reports):  62%|██████▏   | 4412/7111 [16:25<10:15,  4.38it/s]

Gaps (ex-reports):  62%|██████▏   | 4413/7111 [16:25<10:03,  4.47it/s]

Gaps (ex-reports):  62%|██████▏   | 4414/7111 [16:26<09:50,  4.57it/s]

Gaps (ex-reports):  62%|██████▏   | 4415/7111 [16:26<09:38,  4.66it/s]

Gaps (ex-reports):  62%|██████▏   | 4416/7111 [16:26<09:32,  4.70it/s]

Gaps (ex-reports):  62%|██████▏   | 4417/7111 [16:26<09:27,  4.74it/s]

Gaps (ex-reports):  62%|██████▏   | 4418/7111 [16:26<09:25,  4.76it/s]

Gaps (ex-reports):  62%|██████▏   | 4419/7111 [16:27<10:00,  4.48it/s]

Gaps (ex-reports):  62%|██████▏   | 4420/7111 [16:27<09:34,  4.68it/s]

Gaps (ex-reports):  62%|██████▏   | 4421/7111 [16:27<09:34,  4.69it/s]

Gaps (ex-reports):  62%|██████▏   | 4422/7111 [16:27<09:32,  4.70it/s]

Gaps (ex-reports):  62%|██████▏   | 4423/7111 [16:27<09:27,  4.74it/s]

Gaps (ex-reports):  62%|██████▏   | 4424/7111 [16:28<09:36,  4.66it/s]

Gaps (ex-reports):  62%|██████▏   | 4425/7111 [16:28<09:33,  4.68it/s]

Gaps (ex-reports):  62%|██████▏   | 4426/7111 [16:28<09:20,  4.79it/s]

Gaps (ex-reports):  62%|██████▏   | 4427/7111 [16:28<09:17,  4.82it/s]

Gaps (ex-reports):  62%|██████▏   | 4428/7111 [16:28<09:12,  4.85it/s]

Gaps (ex-reports):  62%|██████▏   | 4429/7111 [16:29<09:01,  4.96it/s]

Gaps (ex-reports):  62%|██████▏   | 4430/7111 [16:29<09:07,  4.89it/s]

Gaps (ex-reports):  62%|██████▏   | 4431/7111 [16:29<09:03,  4.93it/s]

Gaps (ex-reports):  62%|██████▏   | 4432/7111 [16:29<09:04,  4.92it/s]

Gaps (ex-reports):  62%|██████▏   | 4433/7111 [16:29<09:18,  4.79it/s]

Gaps (ex-reports):  62%|██████▏   | 4434/7111 [16:30<09:05,  4.90it/s]

Gaps (ex-reports):  62%|██████▏   | 4435/7111 [16:30<09:23,  4.75it/s]

Gaps (ex-reports):  62%|██████▏   | 4436/7111 [16:30<09:17,  4.80it/s]

Gaps (ex-reports):  62%|██████▏   | 4437/7111 [16:30<09:18,  4.79it/s]

Gaps (ex-reports):  62%|██████▏   | 4438/7111 [16:31<09:08,  4.88it/s]

Gaps (ex-reports):  62%|██████▏   | 4439/7111 [16:31<09:05,  4.90it/s]

Gaps (ex-reports):  62%|██████▏   | 4440/7111 [16:31<08:57,  4.97it/s]

Gaps (ex-reports):  62%|██████▏   | 4441/7111 [16:31<09:10,  4.85it/s]

Gaps (ex-reports):  62%|██████▏   | 4442/7111 [16:31<09:04,  4.90it/s]

Gaps (ex-reports):  62%|██████▏   | 4443/7111 [16:32<09:21,  4.75it/s]

Gaps (ex-reports):  62%|██████▏   | 4444/7111 [16:32<09:23,  4.74it/s]

Gaps (ex-reports):  63%|██████▎   | 4445/7111 [16:32<09:14,  4.81it/s]

Gaps (ex-reports):  63%|██████▎   | 4446/7111 [16:32<09:10,  4.84it/s]

Gaps (ex-reports):  63%|██████▎   | 4447/7111 [16:32<09:03,  4.90it/s]

Gaps (ex-reports):  63%|██████▎   | 4448/7111 [16:35<38:04,  1.17it/s]

Gaps (ex-reports):  63%|██████▎   | 4449/7111 [16:35<29:14,  1.52it/s]

Gaps (ex-reports):  63%|██████▎   | 4450/7111 [16:36<31:35,  1.40it/s]

Gaps (ex-reports):  63%|██████▎   | 4451/7111 [16:36<24:40,  1.80it/s]

Gaps (ex-reports):  63%|██████▎   | 4452/7111 [16:36<20:00,  2.22it/s]

Gaps (ex-reports):  63%|██████▎   | 4453/7111 [16:36<16:51,  2.63it/s]

Gaps (ex-reports):  63%|██████▎   | 4454/7111 [16:37<14:39,  3.02it/s]

Gaps (ex-reports):  63%|██████▎   | 4455/7111 [16:37<12:55,  3.43it/s]

Gaps (ex-reports):  63%|██████▎   | 4456/7111 [16:37<11:47,  3.75it/s]

Gaps (ex-reports):  63%|██████▎   | 4457/7111 [16:37<11:01,  4.01it/s]

Gaps (ex-reports):  63%|██████▎   | 4458/7111 [16:37<10:16,  4.30it/s]

Gaps (ex-reports):  63%|██████▎   | 4459/7111 [16:38<09:55,  4.46it/s]

Gaps (ex-reports):  63%|██████▎   | 4460/7111 [16:38<09:41,  4.56it/s]

Gaps (ex-reports):  63%|██████▎   | 4461/7111 [16:38<09:32,  4.63it/s]

Gaps (ex-reports):  63%|██████▎   | 4462/7111 [16:38<09:24,  4.69it/s]

Gaps (ex-reports):  63%|██████▎   | 4463/7111 [16:39<17:57,  2.46it/s]

Gaps (ex-reports):  63%|██████▎   | 4464/7111 [16:39<15:10,  2.91it/s]

Gaps (ex-reports):  63%|██████▎   | 4465/7111 [16:40<13:17,  3.32it/s]

Gaps (ex-reports):  63%|██████▎   | 4466/7111 [16:40<12:11,  3.61it/s]

Gaps (ex-reports):  63%|██████▎   | 4467/7111 [16:40<11:15,  3.91it/s]

Gaps (ex-reports):  63%|██████▎   | 4468/7111 [16:40<10:32,  4.18it/s]

Gaps (ex-reports):  63%|██████▎   | 4469/7111 [16:40<10:09,  4.33it/s]

Gaps (ex-reports):  63%|██████▎   | 4470/7111 [16:41<09:51,  4.47it/s]

Gaps (ex-reports):  63%|██████▎   | 4471/7111 [16:41<09:35,  4.59it/s]

Gaps (ex-reports):  63%|██████▎   | 4472/7111 [16:41<09:17,  4.73it/s]

Gaps (ex-reports):  63%|██████▎   | 4473/7111 [16:41<09:05,  4.84it/s]

Gaps (ex-reports):  63%|██████▎   | 4474/7111 [16:41<08:57,  4.91it/s]

Gaps (ex-reports):  63%|██████▎   | 4475/7111 [16:42<08:56,  4.91it/s]

Gaps (ex-reports):  63%|██████▎   | 4476/7111 [16:42<09:08,  4.81it/s]

Gaps (ex-reports):  63%|██████▎   | 4477/7111 [16:42<08:53,  4.93it/s]

Gaps (ex-reports):  63%|██████▎   | 4478/7111 [16:42<09:04,  4.84it/s]

Gaps (ex-reports):  63%|██████▎   | 4479/7111 [16:42<09:00,  4.87it/s]

Gaps (ex-reports):  63%|██████▎   | 4480/7111 [16:43<17:09,  2.56it/s]

Gaps (ex-reports):  63%|██████▎   | 4481/7111 [16:43<14:53,  2.94it/s]

Gaps (ex-reports):  63%|██████▎   | 4482/7111 [16:44<13:04,  3.35it/s]

Gaps (ex-reports):  63%|██████▎   | 4483/7111 [16:44<11:40,  3.75it/s]

Gaps (ex-reports):  63%|██████▎   | 4484/7111 [16:44<11:05,  3.95it/s]

Gaps (ex-reports):  63%|██████▎   | 4485/7111 [16:44<10:28,  4.18it/s]

Gaps (ex-reports):  63%|██████▎   | 4486/7111 [16:44<09:59,  4.38it/s]

Gaps (ex-reports):  63%|██████▎   | 4487/7111 [16:45<09:41,  4.51it/s]

Gaps (ex-reports):  63%|██████▎   | 4488/7111 [16:45<09:31,  4.59it/s]

Gaps (ex-reports):  63%|██████▎   | 4489/7111 [16:45<09:23,  4.65it/s]

Gaps (ex-reports):  63%|██████▎   | 4490/7111 [16:45<09:20,  4.68it/s]

Gaps (ex-reports):  63%|██████▎   | 4491/7111 [16:45<09:15,  4.72it/s]

Gaps (ex-reports):  63%|██████▎   | 4492/7111 [16:46<09:07,  4.79it/s]

Gaps (ex-reports):  63%|██████▎   | 4493/7111 [16:46<09:01,  4.83it/s]

Gaps (ex-reports):  63%|██████▎   | 4494/7111 [16:47<20:14,  2.16it/s]

Gaps (ex-reports):  63%|██████▎   | 4495/7111 [16:47<16:51,  2.59it/s]

Gaps (ex-reports):  63%|██████▎   | 4496/7111 [16:47<14:39,  2.97it/s]

Gaps (ex-reports):  63%|██████▎   | 4497/7111 [16:48<12:55,  3.37it/s]

Gaps (ex-reports):  63%|██████▎   | 4498/7111 [16:48<11:37,  3.74it/s]

Gaps (ex-reports):  63%|██████▎   | 4499/7111 [16:48<11:01,  3.95it/s]

Gaps (ex-reports):  63%|██████▎   | 4500/7111 [16:48<10:26,  4.17it/s]

Gaps (ex-reports):  63%|██████▎   | 4501/7111 [16:48<10:02,  4.33it/s]

Gaps (ex-reports):  63%|██████▎   | 4502/7111 [16:49<09:49,  4.42it/s]

Gaps (ex-reports):  63%|██████▎   | 4503/7111 [16:49<09:35,  4.53it/s]

Gaps (ex-reports):  63%|██████▎   | 4504/7111 [16:49<09:25,  4.61it/s]

Gaps (ex-reports):  63%|██████▎   | 4505/7111 [16:49<09:16,  4.68it/s]

Gaps (ex-reports):  63%|██████▎   | 4506/7111 [16:49<09:16,  4.68it/s]

Gaps (ex-reports):  63%|██████▎   | 4507/7111 [16:50<09:07,  4.76it/s]

Gaps (ex-reports):  63%|██████▎   | 4508/7111 [16:50<09:05,  4.77it/s]

Gaps (ex-reports):  63%|██████▎   | 4509/7111 [16:50<09:05,  4.77it/s]

Gaps (ex-reports):  63%|██████▎   | 4510/7111 [16:50<09:05,  4.77it/s]

Gaps (ex-reports):  63%|██████▎   | 4511/7111 [16:50<08:49,  4.91it/s]

Gaps (ex-reports):  63%|██████▎   | 4512/7111 [16:51<08:54,  4.87it/s]

Gaps (ex-reports):  63%|██████▎   | 4513/7111 [16:51<08:50,  4.90it/s]

Gaps (ex-reports):  63%|██████▎   | 4514/7111 [16:51<08:41,  4.98it/s]

Gaps (ex-reports):  63%|██████▎   | 4515/7111 [16:51<08:54,  4.86it/s]

Gaps (ex-reports):  64%|██████▎   | 4516/7111 [16:52<08:58,  4.82it/s]

Gaps (ex-reports):  64%|██████▎   | 4517/7111 [16:52<08:52,  4.87it/s]

Gaps (ex-reports):  64%|██████▎   | 4518/7111 [16:52<08:41,  4.97it/s]

Gaps (ex-reports):  64%|██████▎   | 4519/7111 [16:52<08:55,  4.84it/s]

Gaps (ex-reports):  64%|██████▎   | 4520/7111 [16:52<08:43,  4.95it/s]

Gaps (ex-reports):  64%|██████▎   | 4521/7111 [16:53<08:54,  4.84it/s]

Gaps (ex-reports):  64%|██████▎   | 4522/7111 [16:53<08:50,  4.88it/s]

Gaps (ex-reports):  64%|██████▎   | 4523/7111 [16:53<08:45,  4.92it/s]

Gaps (ex-reports):  64%|██████▎   | 4524/7111 [16:53<08:49,  4.88it/s]

Gaps (ex-reports):  64%|██████▎   | 4525/7111 [16:53<09:12,  4.68it/s]

Gaps (ex-reports):  64%|██████▎   | 4526/7111 [16:54<09:07,  4.72it/s]

Gaps (ex-reports):  64%|██████▎   | 4527/7111 [16:54<08:54,  4.84it/s]

Gaps (ex-reports):  64%|██████▎   | 4528/7111 [16:54<08:45,  4.91it/s]

Gaps (ex-reports):  64%|██████▎   | 4529/7111 [16:54<08:53,  4.84it/s]

Gaps (ex-reports):  64%|██████▎   | 4530/7111 [16:54<08:46,  4.91it/s]

Gaps (ex-reports):  64%|██████▎   | 4531/7111 [16:55<16:02,  2.68it/s]

Gaps (ex-reports):  64%|██████▎   | 4532/7111 [16:55<14:03,  3.06it/s]

Gaps (ex-reports):  64%|██████▎   | 4533/7111 [16:56<12:29,  3.44it/s]

Gaps (ex-reports):  64%|██████▍   | 4534/7111 [16:56<11:14,  3.82it/s]

Gaps (ex-reports):  64%|██████▍   | 4535/7111 [16:56<10:34,  4.06it/s]

Gaps (ex-reports):  64%|██████▍   | 4536/7111 [16:56<09:53,  4.34it/s]

Gaps (ex-reports):  64%|██████▍   | 4537/7111 [16:56<09:36,  4.46it/s]

Gaps (ex-reports):  64%|██████▍   | 4538/7111 [16:57<09:30,  4.51it/s]

Gaps (ex-reports):  64%|██████▍   | 4539/7111 [16:57<09:21,  4.58it/s]

Gaps (ex-reports):  64%|██████▍   | 4540/7111 [16:57<09:04,  4.73it/s]

Gaps (ex-reports):  64%|██████▍   | 4541/7111 [16:57<08:48,  4.87it/s]

Gaps (ex-reports):  64%|██████▍   | 4542/7111 [16:57<08:37,  4.97it/s]

Gaps (ex-reports):  64%|██████▍   | 4543/7111 [16:58<08:27,  5.06it/s]

Gaps (ex-reports):  64%|██████▍   | 4544/7111 [16:58<08:19,  5.14it/s]

Gaps (ex-reports):  64%|██████▍   | 4545/7111 [16:58<08:19,  5.13it/s]

Gaps (ex-reports):  64%|██████▍   | 4546/7111 [16:58<08:24,  5.08it/s]

Gaps (ex-reports):  64%|██████▍   | 4547/7111 [16:58<08:31,  5.02it/s]

Gaps (ex-reports):  64%|██████▍   | 4548/7111 [16:59<08:38,  4.94it/s]

Gaps (ex-reports):  64%|██████▍   | 4549/7111 [16:59<08:42,  4.90it/s]

Gaps (ex-reports):  64%|██████▍   | 4550/7111 [16:59<08:42,  4.90it/s]

Gaps (ex-reports):  64%|██████▍   | 4551/7111 [16:59<08:52,  4.81it/s]

Gaps (ex-reports):  64%|██████▍   | 4552/7111 [16:59<08:57,  4.76it/s]

Gaps (ex-reports):  64%|██████▍   | 4553/7111 [17:00<08:55,  4.77it/s]

Gaps (ex-reports):  64%|██████▍   | 4554/7111 [17:00<08:46,  4.85it/s]

Gaps (ex-reports):  64%|██████▍   | 4555/7111 [17:00<08:43,  4.88it/s]

Gaps (ex-reports):  64%|██████▍   | 4556/7111 [17:00<08:42,  4.89it/s]

Gaps (ex-reports):  64%|██████▍   | 4557/7111 [17:00<08:41,  4.90it/s]

Gaps (ex-reports):  64%|██████▍   | 4558/7111 [17:01<08:40,  4.91it/s]

Gaps (ex-reports):  64%|██████▍   | 4559/7111 [17:01<08:35,  4.95it/s]

Gaps (ex-reports):  64%|██████▍   | 4560/7111 [17:02<14:55,  2.85it/s]

Gaps (ex-reports):  64%|██████▍   | 4561/7111 [17:02<13:02,  3.26it/s]

Gaps (ex-reports):  64%|██████▍   | 4562/7111 [17:02<11:49,  3.59it/s]

Gaps (ex-reports):  64%|██████▍   | 4563/7111 [17:02<11:00,  3.86it/s]

Gaps (ex-reports):  64%|██████▍   | 4564/7111 [17:02<10:15,  4.14it/s]

Gaps (ex-reports):  64%|██████▍   | 4565/7111 [17:03<09:38,  4.40it/s]

Gaps (ex-reports):  64%|██████▍   | 4566/7111 [17:03<09:33,  4.43it/s]

Gaps (ex-reports):  64%|██████▍   | 4567/7111 [17:03<09:07,  4.64it/s]

Gaps (ex-reports):  64%|██████▍   | 4568/7111 [17:03<08:52,  4.78it/s]

Gaps (ex-reports):  64%|██████▍   | 4569/7111 [17:03<08:47,  4.82it/s]

Gaps (ex-reports):  64%|██████▍   | 4570/7111 [17:04<08:35,  4.93it/s]

Gaps (ex-reports):  64%|██████▍   | 4571/7111 [17:04<08:28,  5.00it/s]

Gaps (ex-reports):  64%|██████▍   | 4572/7111 [17:04<08:44,  4.84it/s]

Gaps (ex-reports):  64%|██████▍   | 4573/7111 [17:04<08:44,  4.84it/s]

Gaps (ex-reports):  64%|██████▍   | 4574/7111 [17:04<08:39,  4.88it/s]

Gaps (ex-reports):  64%|██████▍   | 4575/7111 [17:06<29:22,  1.44it/s]

Gaps (ex-reports):  64%|██████▍   | 4576/7111 [17:06<23:07,  1.83it/s]

Gaps (ex-reports):  64%|██████▍   | 4577/7111 [17:07<18:43,  2.26it/s]

Gaps (ex-reports):  64%|██████▍   | 4578/7111 [17:07<15:54,  2.65it/s]

Gaps (ex-reports):  64%|██████▍   | 4579/7111 [17:07<13:56,  3.03it/s]

Gaps (ex-reports):  64%|██████▍   | 4580/7111 [17:07<12:14,  3.45it/s]

Gaps (ex-reports):  64%|██████▍   | 4581/7111 [17:07<11:08,  3.78it/s]

Gaps (ex-reports):  64%|██████▍   | 4582/7111 [17:08<10:16,  4.10it/s]

Gaps (ex-reports):  64%|██████▍   | 4583/7111 [17:08<09:45,  4.32it/s]

Gaps (ex-reports):  64%|██████▍   | 4584/7111 [17:08<09:17,  4.54it/s]

Gaps (ex-reports):  64%|██████▍   | 4585/7111 [17:08<08:55,  4.72it/s]

Gaps (ex-reports):  64%|██████▍   | 4586/7111 [17:08<08:56,  4.71it/s]

Gaps (ex-reports):  65%|██████▍   | 4587/7111 [17:09<08:50,  4.75it/s]

Gaps (ex-reports):  65%|██████▍   | 4588/7111 [17:09<08:53,  4.73it/s]

Gaps (ex-reports):  65%|██████▍   | 4589/7111 [17:09<08:49,  4.76it/s]

Gaps (ex-reports):  65%|██████▍   | 4590/7111 [17:09<08:47,  4.78it/s]

Gaps (ex-reports):  65%|██████▍   | 4591/7111 [17:10<08:35,  4.89it/s]

Gaps (ex-reports):  65%|██████▍   | 4592/7111 [17:10<08:34,  4.90it/s]

Gaps (ex-reports):  65%|██████▍   | 4593/7111 [17:10<08:27,  4.96it/s]

Gaps (ex-reports):  65%|██████▍   | 4594/7111 [17:10<09:18,  4.51it/s]

Gaps (ex-reports):  65%|██████▍   | 4595/7111 [17:10<08:54,  4.70it/s]

Gaps (ex-reports):  65%|██████▍   | 4596/7111 [17:11<08:46,  4.78it/s]

Gaps (ex-reports):  65%|██████▍   | 4597/7111 [17:11<08:43,  4.80it/s]

Gaps (ex-reports):  65%|██████▍   | 4598/7111 [17:11<08:42,  4.81it/s]

Gaps (ex-reports):  65%|██████▍   | 4599/7111 [17:11<08:47,  4.76it/s]

Gaps (ex-reports):  65%|██████▍   | 4600/7111 [17:11<08:45,  4.77it/s]

Gaps (ex-reports):  65%|██████▍   | 4601/7111 [17:12<08:44,  4.78it/s]

Gaps (ex-reports):  65%|██████▍   | 4602/7111 [17:12<08:45,  4.78it/s]

Gaps (ex-reports):  65%|██████▍   | 4603/7111 [17:12<08:43,  4.79it/s]

Gaps (ex-reports):  65%|██████▍   | 4604/7111 [17:12<09:44,  4.29it/s]

Gaps (ex-reports):  65%|██████▍   | 4605/7111 [17:13<09:38,  4.33it/s]

Gaps (ex-reports):  65%|██████▍   | 4606/7111 [17:13<09:21,  4.46it/s]

Gaps (ex-reports):  65%|██████▍   | 4607/7111 [17:13<09:13,  4.53it/s]

Gaps (ex-reports):  65%|██████▍   | 4608/7111 [17:13<08:56,  4.67it/s]

Gaps (ex-reports):  65%|██████▍   | 4609/7111 [17:13<08:58,  4.65it/s]

Gaps (ex-reports):  65%|██████▍   | 4610/7111 [17:14<08:49,  4.72it/s]

Gaps (ex-reports):  65%|██████▍   | 4611/7111 [17:14<08:42,  4.78it/s]

Gaps (ex-reports):  65%|██████▍   | 4612/7111 [17:14<09:18,  4.47it/s]

Gaps (ex-reports):  65%|██████▍   | 4613/7111 [17:14<09:03,  4.60it/s]

Gaps (ex-reports):  65%|██████▍   | 4614/7111 [17:14<08:48,  4.72it/s]

Gaps (ex-reports):  65%|██████▍   | 4615/7111 [17:15<08:46,  4.74it/s]

Gaps (ex-reports):  65%|██████▍   | 4616/7111 [17:15<08:37,  4.82it/s]

Gaps (ex-reports):  65%|██████▍   | 4617/7111 [17:15<08:34,  4.84it/s]

Gaps (ex-reports):  65%|██████▍   | 4618/7111 [17:15<08:43,  4.76it/s]

Gaps (ex-reports):  65%|██████▍   | 4619/7111 [17:16<08:47,  4.72it/s]

Gaps (ex-reports):  65%|██████▍   | 4620/7111 [17:16<08:36,  4.82it/s]

Gaps (ex-reports):  65%|██████▍   | 4621/7111 [17:16<08:33,  4.85it/s]

Gaps (ex-reports):  65%|██████▍   | 4622/7111 [17:16<08:21,  4.96it/s]

Gaps (ex-reports):  65%|██████▌   | 4623/7111 [17:16<08:44,  4.74it/s]

Gaps (ex-reports):  65%|██████▌   | 4624/7111 [17:17<08:37,  4.81it/s]

Gaps (ex-reports):  65%|██████▌   | 4625/7111 [17:17<08:38,  4.80it/s]

Gaps (ex-reports):  65%|██████▌   | 4626/7111 [17:17<08:34,  4.83it/s]

Gaps (ex-reports):  65%|██████▌   | 4627/7111 [17:17<08:23,  4.93it/s]

Gaps (ex-reports):  65%|██████▌   | 4628/7111 [17:17<08:14,  5.02it/s]

Gaps (ex-reports):  65%|██████▌   | 4629/7111 [17:18<08:24,  4.92it/s]

Gaps (ex-reports):  65%|██████▌   | 4630/7111 [17:18<08:30,  4.86it/s]

Gaps (ex-reports):  65%|██████▌   | 4631/7111 [17:18<08:29,  4.87it/s]

Gaps (ex-reports):  65%|██████▌   | 4632/7111 [17:18<08:32,  4.83it/s]

Gaps (ex-reports):  65%|██████▌   | 4633/7111 [17:18<08:33,  4.83it/s]

Gaps (ex-reports):  65%|██████▌   | 4634/7111 [17:19<08:29,  4.87it/s]

Gaps (ex-reports):  65%|██████▌   | 4635/7111 [17:19<08:28,  4.87it/s]

Gaps (ex-reports):  65%|██████▌   | 4636/7111 [17:19<08:25,  4.89it/s]

Gaps (ex-reports):  65%|██████▌   | 4637/7111 [17:19<08:27,  4.87it/s]

Gaps (ex-reports):  65%|██████▌   | 4638/7111 [17:19<08:26,  4.88it/s]

Gaps (ex-reports):  65%|██████▌   | 4639/7111 [17:20<08:21,  4.93it/s]

Gaps (ex-reports):  65%|██████▌   | 4640/7111 [17:20<08:20,  4.93it/s]

Gaps (ex-reports):  65%|██████▌   | 4641/7111 [17:20<08:24,  4.89it/s]

Gaps (ex-reports):  65%|██████▌   | 4642/7111 [17:20<08:26,  4.87it/s]

Gaps (ex-reports):  65%|██████▌   | 4643/7111 [17:20<08:30,  4.83it/s]

Gaps (ex-reports):  65%|██████▌   | 4644/7111 [17:21<08:30,  4.83it/s]

Gaps (ex-reports):  65%|██████▌   | 4645/7111 [17:21<08:26,  4.87it/s]

Gaps (ex-reports):  65%|██████▌   | 4646/7111 [17:21<08:24,  4.88it/s]

Gaps (ex-reports):  65%|██████▌   | 4647/7111 [17:21<08:31,  4.82it/s]

Gaps (ex-reports):  65%|██████▌   | 4648/7111 [17:21<08:23,  4.90it/s]

Gaps (ex-reports):  65%|██████▌   | 4649/7111 [17:22<08:28,  4.84it/s]

Gaps (ex-reports):  65%|██████▌   | 4650/7111 [17:22<08:29,  4.83it/s]

Gaps (ex-reports):  65%|██████▌   | 4651/7111 [17:22<08:29,  4.83it/s]

Gaps (ex-reports):  65%|██████▌   | 4652/7111 [17:22<08:16,  4.95it/s]

Gaps (ex-reports):  65%|██████▌   | 4653/7111 [17:22<08:20,  4.91it/s]

Gaps (ex-reports):  65%|██████▌   | 4654/7111 [17:23<08:13,  4.98it/s]

Gaps (ex-reports):  65%|██████▌   | 4655/7111 [17:23<08:20,  4.91it/s]

Gaps (ex-reports):  65%|██████▌   | 4656/7111 [17:25<27:17,  1.50it/s]

Gaps (ex-reports):  65%|██████▌   | 4657/7111 [17:25<21:36,  1.89it/s]

Gaps (ex-reports):  66%|██████▌   | 4658/7111 [17:25<17:36,  2.32it/s]

Gaps (ex-reports):  66%|██████▌   | 4659/7111 [17:25<15:14,  2.68it/s]

Gaps (ex-reports):  66%|██████▌   | 4660/7111 [17:25<13:01,  3.14it/s]

Gaps (ex-reports):  66%|██████▌   | 4661/7111 [17:26<11:30,  3.55it/s]

Gaps (ex-reports):  66%|██████▌   | 4662/7111 [17:26<10:33,  3.86it/s]

Gaps (ex-reports):  66%|██████▌   | 4663/7111 [17:26<10:02,  4.06it/s]

Gaps (ex-reports):  66%|██████▌   | 4664/7111 [17:26<09:30,  4.29it/s]

Gaps (ex-reports):  66%|██████▌   | 4665/7111 [17:26<09:11,  4.44it/s]

Gaps (ex-reports):  66%|██████▌   | 4666/7111 [17:27<09:02,  4.51it/s]

Gaps (ex-reports):  66%|██████▌   | 4667/7111 [17:27<08:50,  4.61it/s]

Gaps (ex-reports):  66%|██████▌   | 4668/7111 [17:27<08:43,  4.67it/s]

Gaps (ex-reports):  66%|██████▌   | 4669/7111 [17:27<10:40,  3.81it/s]

Gaps (ex-reports):  66%|██████▌   | 4670/7111 [17:28<09:53,  4.11it/s]

Gaps (ex-reports):  66%|██████▌   | 4671/7111 [17:28<09:22,  4.34it/s]

Gaps (ex-reports):  66%|██████▌   | 4672/7111 [17:28<09:12,  4.42it/s]

Gaps (ex-reports):  66%|██████▌   | 4673/7111 [17:28<08:56,  4.54it/s]

Gaps (ex-reports):  66%|██████▌   | 4674/7111 [17:29<08:47,  4.62it/s]

Gaps (ex-reports):  66%|██████▌   | 4675/7111 [17:29<08:46,  4.63it/s]

Gaps (ex-reports):  66%|██████▌   | 4676/7111 [17:29<08:36,  4.71it/s]

Gaps (ex-reports):  66%|██████▌   | 4677/7111 [17:29<08:37,  4.71it/s]

Gaps (ex-reports):  66%|██████▌   | 4678/7111 [17:29<08:22,  4.84it/s]

Gaps (ex-reports):  66%|██████▌   | 4679/7111 [17:30<08:13,  4.93it/s]

Gaps (ex-reports):  66%|██████▌   | 4680/7111 [17:30<08:11,  4.94it/s]

Gaps (ex-reports):  66%|██████▌   | 4681/7111 [17:30<08:11,  4.95it/s]

Gaps (ex-reports):  66%|██████▌   | 4682/7111 [17:30<08:34,  4.72it/s]

Gaps (ex-reports):  66%|██████▌   | 4683/7111 [17:30<08:29,  4.76it/s]

Gaps (ex-reports):  66%|██████▌   | 4684/7111 [17:31<08:26,  4.79it/s]

Gaps (ex-reports):  66%|██████▌   | 4685/7111 [17:31<08:12,  4.92it/s]

Gaps (ex-reports):  66%|██████▌   | 4686/7111 [17:31<08:20,  4.84it/s]

Gaps (ex-reports):  66%|██████▌   | 4687/7111 [17:31<08:17,  4.87it/s]

Gaps (ex-reports):  66%|██████▌   | 4688/7111 [17:31<08:19,  4.85it/s]

Gaps (ex-reports):  66%|██████▌   | 4689/7111 [17:32<08:30,  4.74it/s]

Gaps (ex-reports):  66%|██████▌   | 4690/7111 [17:32<08:27,  4.77it/s]

Gaps (ex-reports):  66%|██████▌   | 4691/7111 [17:32<08:29,  4.75it/s]

Gaps (ex-reports):  66%|██████▌   | 4692/7111 [17:32<08:22,  4.81it/s]

Gaps (ex-reports):  66%|██████▌   | 4693/7111 [17:32<08:18,  4.85it/s]

Gaps (ex-reports):  66%|██████▌   | 4694/7111 [17:33<08:22,  4.81it/s]

Gaps (ex-reports):  66%|██████▌   | 4695/7111 [17:33<08:18,  4.85it/s]

Gaps (ex-reports):  66%|██████▌   | 4696/7111 [17:33<08:17,  4.86it/s]

Gaps (ex-reports):  66%|██████▌   | 4697/7111 [17:33<08:14,  4.88it/s]

Gaps (ex-reports):  66%|██████▌   | 4698/7111 [17:33<08:08,  4.94it/s]

Gaps (ex-reports):  66%|██████▌   | 4699/7111 [17:34<08:18,  4.83it/s]

Gaps (ex-reports):  66%|██████▌   | 4700/7111 [17:34<08:13,  4.88it/s]

Gaps (ex-reports):  66%|██████▌   | 4701/7111 [17:34<08:15,  4.86it/s]

Gaps (ex-reports):  66%|██████▌   | 4702/7111 [17:34<08:14,  4.88it/s]

Gaps (ex-reports):  66%|██████▌   | 4703/7111 [17:34<08:04,  4.97it/s]

Gaps (ex-reports):  66%|██████▌   | 4704/7111 [17:35<08:02,  4.99it/s]

Gaps (ex-reports):  66%|██████▌   | 4705/7111 [17:35<08:08,  4.93it/s]

Gaps (ex-reports):  66%|██████▌   | 4706/7111 [17:35<08:09,  4.92it/s]

Gaps (ex-reports):  66%|██████▌   | 4707/7111 [17:35<08:01,  5.00it/s]

Gaps (ex-reports):  66%|██████▌   | 4708/7111 [17:36<08:11,  4.89it/s]

Gaps (ex-reports):  66%|██████▌   | 4709/7111 [17:36<08:08,  4.92it/s]

Gaps (ex-reports):  66%|██████▌   | 4710/7111 [17:36<08:03,  4.97it/s]

Gaps (ex-reports):  66%|██████▌   | 4711/7111 [17:36<08:07,  4.92it/s]

Gaps (ex-reports):  66%|██████▋   | 4712/7111 [17:36<08:10,  4.89it/s]

Gaps (ex-reports):  66%|██████▋   | 4713/7111 [17:37<08:18,  4.81it/s]

Gaps (ex-reports):  66%|██████▋   | 4714/7111 [17:37<08:23,  4.76it/s]

Gaps (ex-reports):  66%|██████▋   | 4715/7111 [17:37<08:18,  4.81it/s]

Gaps (ex-reports):  66%|██████▋   | 4716/7111 [17:37<08:14,  4.85it/s]

Gaps (ex-reports):  66%|██████▋   | 4717/7111 [17:37<08:19,  4.79it/s]

Gaps (ex-reports):  66%|██████▋   | 4718/7111 [17:38<08:06,  4.92it/s]

Gaps (ex-reports):  66%|██████▋   | 4719/7111 [17:38<08:23,  4.75it/s]

Gaps (ex-reports):  66%|██████▋   | 4720/7111 [17:38<08:23,  4.74it/s]

Gaps (ex-reports):  66%|██████▋   | 4721/7111 [17:38<08:32,  4.66it/s]

Gaps (ex-reports):  66%|██████▋   | 4722/7111 [17:38<08:32,  4.66it/s]

Gaps (ex-reports):  66%|██████▋   | 4723/7111 [17:39<08:19,  4.79it/s]

Gaps (ex-reports):  66%|██████▋   | 4724/7111 [17:39<08:13,  4.84it/s]

Gaps (ex-reports):  66%|██████▋   | 4725/7111 [17:39<08:12,  4.84it/s]

Gaps (ex-reports):  66%|██████▋   | 4726/7111 [17:39<08:12,  4.85it/s]

Gaps (ex-reports):  66%|██████▋   | 4727/7111 [17:39<08:09,  4.87it/s]

Gaps (ex-reports):  66%|██████▋   | 4728/7111 [17:40<08:05,  4.91it/s]

Gaps (ex-reports):  67%|██████▋   | 4729/7111 [17:40<08:21,  4.75it/s]

Gaps (ex-reports):  67%|██████▋   | 4730/7111 [17:40<08:10,  4.86it/s]

Gaps (ex-reports):  67%|██████▋   | 4731/7111 [17:40<08:14,  4.81it/s]

Gaps (ex-reports):  67%|██████▋   | 4732/7111 [17:40<08:14,  4.81it/s]

Gaps (ex-reports):  67%|██████▋   | 4733/7111 [17:41<08:18,  4.77it/s]

Gaps (ex-reports):  67%|██████▋   | 4734/7111 [17:41<08:13,  4.82it/s]

Gaps (ex-reports):  67%|██████▋   | 4735/7111 [17:41<08:09,  4.86it/s]

Gaps (ex-reports):  67%|██████▋   | 4736/7111 [17:41<08:01,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4737/7111 [17:41<07:56,  4.98it/s]

Gaps (ex-reports):  67%|██████▋   | 4738/7111 [17:42<08:01,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4739/7111 [17:42<08:10,  4.84it/s]

Gaps (ex-reports):  67%|██████▋   | 4740/7111 [17:42<08:07,  4.86it/s]

Gaps (ex-reports):  67%|██████▋   | 4741/7111 [17:42<08:09,  4.84it/s]

Gaps (ex-reports):  67%|██████▋   | 4742/7111 [17:43<08:03,  4.90it/s]

Gaps (ex-reports):  67%|██████▋   | 4743/7111 [17:43<08:01,  4.92it/s]

Gaps (ex-reports):  67%|██████▋   | 4744/7111 [17:43<08:06,  4.86it/s]

Gaps (ex-reports):  67%|██████▋   | 4745/7111 [17:43<08:06,  4.86it/s]

Gaps (ex-reports):  67%|██████▋   | 4746/7111 [17:43<08:02,  4.90it/s]

Gaps (ex-reports):  67%|██████▋   | 4747/7111 [17:44<07:59,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4748/7111 [17:44<08:02,  4.90it/s]

Gaps (ex-reports):  67%|██████▋   | 4749/7111 [17:44<08:04,  4.87it/s]

Gaps (ex-reports):  67%|██████▋   | 4750/7111 [17:44<08:06,  4.85it/s]

Gaps (ex-reports):  67%|██████▋   | 4751/7111 [17:44<08:08,  4.83it/s]

Gaps (ex-reports):  67%|██████▋   | 4752/7111 [17:45<08:07,  4.84it/s]

Gaps (ex-reports):  67%|██████▋   | 4753/7111 [17:45<08:10,  4.80it/s]

Gaps (ex-reports):  67%|██████▋   | 4754/7111 [17:45<08:07,  4.83it/s]

Gaps (ex-reports):  67%|██████▋   | 4755/7111 [17:45<07:57,  4.94it/s]

Gaps (ex-reports):  67%|██████▋   | 4756/7111 [17:45<08:01,  4.89it/s]

Gaps (ex-reports):  67%|██████▋   | 4757/7111 [17:46<07:50,  5.00it/s]

Gaps (ex-reports):  67%|██████▋   | 4758/7111 [17:46<07:44,  5.07it/s]

Gaps (ex-reports):  67%|██████▋   | 4759/7111 [17:46<07:42,  5.08it/s]

Gaps (ex-reports):  67%|██████▋   | 4760/7111 [17:46<07:52,  4.97it/s]

Gaps (ex-reports):  67%|██████▋   | 4761/7111 [17:46<07:51,  4.98it/s]

Gaps (ex-reports):  67%|██████▋   | 4762/7111 [17:47<07:45,  5.05it/s]

Gaps (ex-reports):  67%|██████▋   | 4763/7111 [17:47<07:58,  4.91it/s]

Gaps (ex-reports):  67%|██████▋   | 4764/7111 [17:47<08:01,  4.88it/s]

Gaps (ex-reports):  67%|██████▋   | 4765/7111 [17:47<08:02,  4.86it/s]

Gaps (ex-reports):  67%|██████▋   | 4766/7111 [17:47<07:54,  4.94it/s]

Gaps (ex-reports):  67%|██████▋   | 4767/7111 [17:48<08:05,  4.83it/s]

Gaps (ex-reports):  67%|██████▋   | 4768/7111 [17:48<07:53,  4.95it/s]

Gaps (ex-reports):  67%|██████▋   | 4769/7111 [17:48<08:07,  4.80it/s]

Gaps (ex-reports):  67%|██████▋   | 4770/7111 [17:48<07:54,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4771/7111 [17:48<07:49,  4.98it/s]

Gaps (ex-reports):  67%|██████▋   | 4772/7111 [17:49<08:03,  4.84it/s]

Gaps (ex-reports):  67%|██████▋   | 4773/7111 [17:49<07:53,  4.94it/s]

Gaps (ex-reports):  67%|██████▋   | 4774/7111 [17:49<07:48,  4.99it/s]

Gaps (ex-reports):  67%|██████▋   | 4775/7111 [17:49<07:52,  4.94it/s]

Gaps (ex-reports):  67%|██████▋   | 4776/7111 [17:49<07:50,  4.96it/s]

Gaps (ex-reports):  67%|██████▋   | 4777/7111 [17:50<07:51,  4.95it/s]

Gaps (ex-reports):  67%|██████▋   | 4778/7111 [17:50<07:53,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4779/7111 [17:50<07:45,  5.01it/s]

Gaps (ex-reports):  67%|██████▋   | 4780/7111 [17:50<07:52,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4781/7111 [17:50<08:01,  4.84it/s]

Gaps (ex-reports):  67%|██████▋   | 4782/7111 [17:51<07:54,  4.91it/s]

Gaps (ex-reports):  67%|██████▋   | 4783/7111 [17:51<07:51,  4.93it/s]

Gaps (ex-reports):  67%|██████▋   | 4784/7111 [17:51<07:50,  4.95it/s]

Gaps (ex-reports):  67%|██████▋   | 4785/7111 [17:51<08:33,  4.53it/s]

Gaps (ex-reports):  67%|██████▋   | 4786/7111 [17:52<08:21,  4.64it/s]

Gaps (ex-reports):  67%|██████▋   | 4787/7111 [17:52<08:10,  4.73it/s]

Gaps (ex-reports):  67%|██████▋   | 4788/7111 [17:52<07:58,  4.85it/s]

Gaps (ex-reports):  67%|██████▋   | 4789/7111 [17:52<08:10,  4.73it/s]

Gaps (ex-reports):  67%|██████▋   | 4790/7111 [17:52<07:59,  4.84it/s]

Gaps (ex-reports):  67%|██████▋   | 4791/7111 [17:53<11:58,  3.23it/s]

Gaps (ex-reports):  67%|██████▋   | 4792/7111 [17:53<10:42,  3.61it/s]

Gaps (ex-reports):  67%|██████▋   | 4793/7111 [17:53<09:38,  4.00it/s]

Gaps (ex-reports):  67%|██████▋   | 4794/7111 [17:53<09:04,  4.25it/s]

Gaps (ex-reports):  67%|██████▋   | 4795/7111 [17:54<08:44,  4.41it/s]

Gaps (ex-reports):  67%|██████▋   | 4796/7111 [17:54<08:34,  4.50it/s]

Gaps (ex-reports):  67%|██████▋   | 4797/7111 [17:54<08:24,  4.59it/s]

Gaps (ex-reports):  67%|██████▋   | 4798/7111 [17:54<08:20,  4.62it/s]

Gaps (ex-reports):  67%|██████▋   | 4799/7111 [17:55<08:09,  4.72it/s]

Gaps (ex-reports):  68%|██████▊   | 4800/7111 [17:55<08:10,  4.72it/s]

Gaps (ex-reports):  68%|██████▊   | 4801/7111 [17:55<08:05,  4.75it/s]

Gaps (ex-reports):  68%|██████▊   | 4802/7111 [17:55<07:57,  4.83it/s]

Gaps (ex-reports):  68%|██████▊   | 4803/7111 [17:55<07:49,  4.91it/s]

Gaps (ex-reports):  68%|██████▊   | 4804/7111 [17:56<07:42,  4.99it/s]

Gaps (ex-reports):  68%|██████▊   | 4805/7111 [17:56<07:55,  4.84it/s]

Gaps (ex-reports):  68%|██████▊   | 4806/7111 [17:56<07:46,  4.94it/s]

Gaps (ex-reports):  68%|██████▊   | 4807/7111 [17:56<07:53,  4.87it/s]

Gaps (ex-reports):  68%|██████▊   | 4808/7111 [17:56<07:53,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4809/7111 [17:57<11:14,  3.41it/s]

Gaps (ex-reports):  68%|██████▊   | 4810/7111 [17:57<10:14,  3.74it/s]

Gaps (ex-reports):  68%|██████▊   | 4811/7111 [17:57<09:36,  3.99it/s]

Gaps (ex-reports):  68%|██████▊   | 4812/7111 [17:57<08:54,  4.30it/s]

Gaps (ex-reports):  68%|██████▊   | 4813/7111 [17:58<08:35,  4.46it/s]

Gaps (ex-reports):  68%|██████▊   | 4814/7111 [17:58<08:12,  4.66it/s]

Gaps (ex-reports):  68%|██████▊   | 4815/7111 [17:58<08:07,  4.71it/s]

Gaps (ex-reports):  68%|██████▊   | 4816/7111 [17:58<08:17,  4.61it/s]

Gaps (ex-reports):  68%|██████▊   | 4817/7111 [17:59<08:09,  4.68it/s]

Gaps (ex-reports):  68%|██████▊   | 4818/7111 [17:59<08:03,  4.74it/s]

Gaps (ex-reports):  68%|██████▊   | 4819/7111 [17:59<07:51,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4820/7111 [17:59<07:44,  4.93it/s]

Gaps (ex-reports):  68%|██████▊   | 4821/7111 [17:59<09:44,  3.92it/s]

Gaps (ex-reports):  68%|██████▊   | 4822/7111 [18:00<09:26,  4.04it/s]

Gaps (ex-reports):  68%|██████▊   | 4823/7111 [18:00<08:56,  4.27it/s]

Gaps (ex-reports):  68%|██████▊   | 4824/7111 [18:00<08:28,  4.50it/s]

Gaps (ex-reports):  68%|██████▊   | 4825/7111 [18:00<08:21,  4.56it/s]

Gaps (ex-reports):  68%|██████▊   | 4826/7111 [18:01<08:11,  4.65it/s]

Gaps (ex-reports):  68%|██████▊   | 4827/7111 [18:01<08:04,  4.71it/s]

Gaps (ex-reports):  68%|██████▊   | 4828/7111 [18:01<07:57,  4.78it/s]

Gaps (ex-reports):  68%|██████▊   | 4829/7111 [18:02<12:36,  3.02it/s]

Gaps (ex-reports):  68%|██████▊   | 4830/7111 [18:02<11:09,  3.41it/s]

Gaps (ex-reports):  68%|██████▊   | 4831/7111 [18:02<10:01,  3.79it/s]

Gaps (ex-reports):  68%|██████▊   | 4832/7111 [18:02<09:24,  4.04it/s]

Gaps (ex-reports):  68%|██████▊   | 4833/7111 [18:02<08:43,  4.35it/s]

Gaps (ex-reports):  68%|██████▊   | 4834/7111 [18:03<08:31,  4.45it/s]

Gaps (ex-reports):  68%|██████▊   | 4835/7111 [18:03<08:06,  4.68it/s]

Gaps (ex-reports):  68%|██████▊   | 4836/7111 [18:03<07:51,  4.82it/s]

Gaps (ex-reports):  68%|██████▊   | 4837/7111 [18:03<07:56,  4.77it/s]

Gaps (ex-reports):  68%|██████▊   | 4838/7111 [18:03<07:51,  4.82it/s]

Gaps (ex-reports):  68%|██████▊   | 4839/7111 [18:04<07:57,  4.76it/s]

Gaps (ex-reports):  68%|██████▊   | 4840/7111 [18:04<08:14,  4.59it/s]

Gaps (ex-reports):  68%|██████▊   | 4841/7111 [18:04<08:08,  4.64it/s]

Gaps (ex-reports):  68%|██████▊   | 4842/7111 [18:04<07:58,  4.74it/s]

Gaps (ex-reports):  68%|██████▊   | 4843/7111 [18:04<08:31,  4.43it/s]

Gaps (ex-reports):  68%|██████▊   | 4844/7111 [18:05<08:22,  4.51it/s]

Gaps (ex-reports):  68%|██████▊   | 4845/7111 [18:05<08:19,  4.54it/s]

Gaps (ex-reports):  68%|██████▊   | 4846/7111 [18:05<08:13,  4.59it/s]

Gaps (ex-reports):  68%|██████▊   | 4847/7111 [18:05<08:13,  4.59it/s]

Gaps (ex-reports):  68%|██████▊   | 4848/7111 [18:06<08:03,  4.68it/s]

Gaps (ex-reports):  68%|██████▊   | 4849/7111 [18:06<07:54,  4.77it/s]

Gaps (ex-reports):  68%|██████▊   | 4850/7111 [18:06<08:05,  4.66it/s]

Gaps (ex-reports):  68%|██████▊   | 4851/7111 [18:06<08:00,  4.70it/s]

Gaps (ex-reports):  68%|██████▊   | 4852/7111 [18:06<07:58,  4.72it/s]

Gaps (ex-reports):  68%|██████▊   | 4853/7111 [18:07<07:49,  4.81it/s]

Gaps (ex-reports):  68%|██████▊   | 4854/7111 [18:07<07:55,  4.75it/s]

Gaps (ex-reports):  68%|██████▊   | 4855/7111 [18:07<07:48,  4.82it/s]

Gaps (ex-reports):  68%|██████▊   | 4856/7111 [18:07<07:43,  4.87it/s]

Gaps (ex-reports):  68%|██████▊   | 4857/7111 [18:07<07:50,  4.79it/s]

Gaps (ex-reports):  68%|██████▊   | 4858/7111 [18:08<07:48,  4.81it/s]

Gaps (ex-reports):  68%|██████▊   | 4859/7111 [18:08<07:43,  4.86it/s]

Gaps (ex-reports):  68%|██████▊   | 4860/7111 [18:08<07:36,  4.93it/s]

Gaps (ex-reports):  68%|██████▊   | 4861/7111 [18:08<07:59,  4.69it/s]

Gaps (ex-reports):  68%|██████▊   | 4862/7111 [18:08<07:49,  4.79it/s]

Gaps (ex-reports):  68%|██████▊   | 4863/7111 [18:09<07:46,  4.82it/s]

Gaps (ex-reports):  68%|██████▊   | 4864/7111 [18:09<07:46,  4.81it/s]

Gaps (ex-reports):  68%|██████▊   | 4865/7111 [18:09<07:57,  4.70it/s]

Gaps (ex-reports):  68%|██████▊   | 4866/7111 [18:10<16:24,  2.28it/s]

Gaps (ex-reports):  68%|██████▊   | 4867/7111 [18:10<13:48,  2.71it/s]

Gaps (ex-reports):  68%|██████▊   | 4868/7111 [18:10<11:58,  3.12it/s]

Gaps (ex-reports):  68%|██████▊   | 4869/7111 [18:11<10:48,  3.46it/s]

Gaps (ex-reports):  68%|██████▊   | 4870/7111 [18:11<09:47,  3.82it/s]

Gaps (ex-reports):  68%|██████▊   | 4871/7111 [18:11<09:28,  3.94it/s]

Gaps (ex-reports):  69%|██████▊   | 4872/7111 [18:11<09:08,  4.08it/s]

Gaps (ex-reports):  69%|██████▊   | 4873/7111 [18:12<08:32,  4.36it/s]

Gaps (ex-reports):  69%|██████▊   | 4874/7111 [18:12<08:09,  4.57it/s]

Gaps (ex-reports):  69%|██████▊   | 4875/7111 [18:12<08:11,  4.55it/s]

Gaps (ex-reports):  69%|██████▊   | 4876/7111 [18:12<07:56,  4.69it/s]

Gaps (ex-reports):  69%|██████▊   | 4877/7111 [18:12<07:41,  4.84it/s]

Gaps (ex-reports):  69%|██████▊   | 4878/7111 [18:13<07:33,  4.92it/s]

Gaps (ex-reports):  69%|██████▊   | 4879/7111 [18:13<07:33,  4.92it/s]

Gaps (ex-reports):  69%|██████▊   | 4880/7111 [18:13<08:27,  4.39it/s]

Gaps (ex-reports):  69%|██████▊   | 4881/7111 [18:13<08:09,  4.56it/s]

Gaps (ex-reports):  69%|██████▊   | 4882/7111 [18:13<07:46,  4.77it/s]

Gaps (ex-reports):  69%|██████▊   | 4883/7111 [18:14<07:42,  4.82it/s]

Gaps (ex-reports):  69%|██████▊   | 4884/7111 [18:14<07:37,  4.87it/s]

Gaps (ex-reports):  69%|██████▊   | 4885/7111 [18:14<07:37,  4.87it/s]

Gaps (ex-reports):  69%|██████▊   | 4886/7111 [18:14<07:38,  4.85it/s]

Gaps (ex-reports):  69%|██████▊   | 4887/7111 [18:14<07:30,  4.94it/s]

Gaps (ex-reports):  69%|██████▊   | 4888/7111 [18:15<07:39,  4.83it/s]

Gaps (ex-reports):  69%|██████▉   | 4889/7111 [18:15<07:30,  4.93it/s]

Gaps (ex-reports):  69%|██████▉   | 4890/7111 [18:15<07:27,  4.97it/s]

Gaps (ex-reports):  69%|██████▉   | 4891/7111 [18:15<07:37,  4.86it/s]

Gaps (ex-reports):  69%|██████▉   | 4892/7111 [18:15<07:36,  4.86it/s]

Gaps (ex-reports):  69%|██████▉   | 4893/7111 [18:16<07:37,  4.85it/s]

Gaps (ex-reports):  69%|██████▉   | 4894/7111 [18:16<07:34,  4.88it/s]

Gaps (ex-reports):  69%|██████▉   | 4895/7111 [18:16<07:50,  4.71it/s]

Gaps (ex-reports):  69%|██████▉   | 4896/7111 [18:16<07:41,  4.79it/s]

Gaps (ex-reports):  69%|██████▉   | 4897/7111 [18:16<07:30,  4.92it/s]

Gaps (ex-reports):  69%|██████▉   | 4898/7111 [18:17<07:24,  4.98it/s]

Gaps (ex-reports):  69%|██████▉   | 4899/7111 [18:17<07:36,  4.85it/s]

Gaps (ex-reports):  69%|██████▉   | 4900/7111 [18:17<07:28,  4.93it/s]

Gaps (ex-reports):  69%|██████▉   | 4901/7111 [18:17<07:33,  4.87it/s]

Gaps (ex-reports):  69%|██████▉   | 4902/7111 [18:18<07:38,  4.82it/s]

Gaps (ex-reports):  69%|██████▉   | 4903/7111 [18:18<07:37,  4.83it/s]

Gaps (ex-reports):  69%|██████▉   | 4904/7111 [18:18<07:40,  4.79it/s]

Gaps (ex-reports):  69%|██████▉   | 4905/7111 [18:18<07:43,  4.76it/s]

Gaps (ex-reports):  69%|██████▉   | 4906/7111 [18:18<07:47,  4.71it/s]

Gaps (ex-reports):  69%|██████▉   | 4907/7111 [18:19<07:46,  4.72it/s]

Gaps (ex-reports):  69%|██████▉   | 4908/7111 [18:19<07:33,  4.86it/s]

Gaps (ex-reports):  69%|██████▉   | 4909/7111 [18:19<07:39,  4.79it/s]

Gaps (ex-reports):  69%|██████▉   | 4910/7111 [18:19<07:39,  4.79it/s]

Gaps (ex-reports):  69%|██████▉   | 4911/7111 [18:19<07:45,  4.72it/s]

Gaps (ex-reports):  69%|██████▉   | 4912/7111 [18:20<07:37,  4.80it/s]

Gaps (ex-reports):  69%|██████▉   | 4913/7111 [18:20<07:44,  4.73it/s]

Gaps (ex-reports):  69%|██████▉   | 4914/7111 [18:20<07:41,  4.76it/s]

Gaps (ex-reports):  69%|██████▉   | 4915/7111 [18:20<07:35,  4.82it/s]

Gaps (ex-reports):  69%|██████▉   | 4916/7111 [18:20<07:32,  4.85it/s]

Gaps (ex-reports):  69%|██████▉   | 4917/7111 [18:21<07:34,  4.83it/s]

Gaps (ex-reports):  69%|██████▉   | 4918/7111 [18:21<07:39,  4.77it/s]

Gaps (ex-reports):  69%|██████▉   | 4919/7111 [18:21<07:34,  4.82it/s]

Gaps (ex-reports):  69%|██████▉   | 4920/7111 [18:21<07:26,  4.90it/s]

Gaps (ex-reports):  69%|██████▉   | 4921/7111 [18:21<07:22,  4.95it/s]

Gaps (ex-reports):  69%|██████▉   | 4922/7111 [18:22<07:27,  4.90it/s]

Gaps (ex-reports):  69%|██████▉   | 4923/7111 [18:22<07:25,  4.91it/s]

Gaps (ex-reports):  69%|██████▉   | 4924/7111 [18:22<07:24,  4.92it/s]

Gaps (ex-reports):  69%|██████▉   | 4925/7111 [18:22<07:34,  4.81it/s]

Gaps (ex-reports):  69%|██████▉   | 4926/7111 [18:23<07:41,  4.73it/s]

Gaps (ex-reports):  69%|██████▉   | 4927/7111 [18:23<07:36,  4.78it/s]

Gaps (ex-reports):  69%|██████▉   | 4928/7111 [18:23<07:33,  4.82it/s]

Gaps (ex-reports):  69%|██████▉   | 4929/7111 [18:23<07:32,  4.82it/s]

Gaps (ex-reports):  69%|██████▉   | 4930/7111 [18:23<07:30,  4.84it/s]

Gaps (ex-reports):  69%|██████▉   | 4931/7111 [18:24<07:39,  4.75it/s]

Gaps (ex-reports):  69%|██████▉   | 4932/7111 [18:24<07:34,  4.80it/s]

Gaps (ex-reports):  69%|██████▉   | 4933/7111 [18:24<07:22,  4.92it/s]

Gaps (ex-reports):  69%|██████▉   | 4934/7111 [18:24<07:34,  4.79it/s]

Gaps (ex-reports):  69%|██████▉   | 4935/7111 [18:24<07:42,  4.70it/s]

Gaps (ex-reports):  69%|██████▉   | 4936/7111 [18:25<07:32,  4.81it/s]

Gaps (ex-reports):  69%|██████▉   | 4937/7111 [18:25<07:47,  4.65it/s]

Gaps (ex-reports):  69%|██████▉   | 4938/7111 [18:25<07:44,  4.68it/s]

Gaps (ex-reports):  69%|██████▉   | 4939/7111 [18:25<07:36,  4.76it/s]

Gaps (ex-reports):  69%|██████▉   | 4940/7111 [18:25<07:26,  4.86it/s]

Gaps (ex-reports):  69%|██████▉   | 4941/7111 [18:26<07:34,  4.78it/s]

Gaps (ex-reports):  69%|██████▉   | 4942/7111 [18:26<07:30,  4.81it/s]

Gaps (ex-reports):  70%|██████▉   | 4943/7111 [18:26<07:19,  4.94it/s]

Gaps (ex-reports):  70%|██████▉   | 4944/7111 [18:26<07:17,  4.95it/s]

Gaps (ex-reports):  70%|██████▉   | 4945/7111 [18:26<07:17,  4.95it/s]

Gaps (ex-reports):  70%|██████▉   | 4946/7111 [18:27<07:26,  4.85it/s]

Gaps (ex-reports):  70%|██████▉   | 4947/7111 [18:27<11:26,  3.15it/s]

Gaps (ex-reports):  70%|██████▉   | 4948/7111 [18:27<10:15,  3.51it/s]

Gaps (ex-reports):  70%|██████▉   | 4949/7111 [18:28<09:17,  3.88it/s]

Gaps (ex-reports):  70%|██████▉   | 4950/7111 [18:28<08:43,  4.12it/s]

Gaps (ex-reports):  70%|██████▉   | 4951/7111 [18:28<08:21,  4.31it/s]

Gaps (ex-reports):  70%|██████▉   | 4952/7111 [18:28<08:09,  4.41it/s]

Gaps (ex-reports):  70%|██████▉   | 4953/7111 [18:28<07:45,  4.64it/s]

Gaps (ex-reports):  70%|██████▉   | 4954/7111 [18:29<07:44,  4.64it/s]

Gaps (ex-reports):  70%|██████▉   | 4955/7111 [18:29<07:45,  4.63it/s]

Gaps (ex-reports):  70%|██████▉   | 4956/7111 [18:29<07:29,  4.79it/s]

Gaps (ex-reports):  70%|██████▉   | 4957/7111 [18:29<07:20,  4.89it/s]

Gaps (ex-reports):  70%|██████▉   | 4958/7111 [18:29<07:15,  4.95it/s]

Gaps (ex-reports):  70%|██████▉   | 4959/7111 [18:30<07:16,  4.93it/s]

Gaps (ex-reports):  70%|██████▉   | 4960/7111 [18:30<07:25,  4.83it/s]

Gaps (ex-reports):  70%|██████▉   | 4961/7111 [18:30<07:22,  4.86it/s]

Gaps (ex-reports):  70%|██████▉   | 4962/7111 [18:30<07:17,  4.91it/s]

Gaps (ex-reports):  70%|██████▉   | 4963/7111 [18:31<07:15,  4.94it/s]

Gaps (ex-reports):  70%|██████▉   | 4964/7111 [18:31<07:20,  4.87it/s]

Gaps (ex-reports):  70%|██████▉   | 4965/7111 [18:31<07:16,  4.92it/s]

Gaps (ex-reports):  70%|██████▉   | 4966/7111 [18:32<11:51,  3.01it/s]

Gaps (ex-reports):  70%|██████▉   | 4967/7111 [18:32<10:37,  3.36it/s]

Gaps (ex-reports):  70%|██████▉   | 4968/7111 [18:32<09:32,  3.74it/s]

Gaps (ex-reports):  70%|██████▉   | 4969/7111 [18:32<08:57,  3.98it/s]

Gaps (ex-reports):  70%|██████▉   | 4970/7111 [18:32<08:26,  4.23it/s]

Gaps (ex-reports):  70%|██████▉   | 4971/7111 [18:33<08:14,  4.33it/s]

Gaps (ex-reports):  70%|██████▉   | 4972/7111 [18:33<07:56,  4.49it/s]

Gaps (ex-reports):  70%|██████▉   | 4973/7111 [18:33<07:41,  4.63it/s]

Gaps (ex-reports):  70%|██████▉   | 4974/7111 [18:33<07:39,  4.65it/s]

Gaps (ex-reports):  70%|██████▉   | 4975/7111 [18:33<07:40,  4.64it/s]

Gaps (ex-reports):  70%|██████▉   | 4976/7111 [18:34<07:38,  4.65it/s]

Gaps (ex-reports):  70%|██████▉   | 4977/7111 [18:34<07:26,  4.77it/s]

Gaps (ex-reports):  70%|███████   | 4978/7111 [18:34<07:28,  4.75it/s]

Gaps (ex-reports):  70%|███████   | 4979/7111 [18:34<07:20,  4.84it/s]

Gaps (ex-reports):  70%|███████   | 4980/7111 [18:34<07:20,  4.84it/s]

Gaps (ex-reports):  70%|███████   | 4981/7111 [18:35<07:15,  4.89it/s]

Gaps (ex-reports):  70%|███████   | 4982/7111 [18:35<07:14,  4.90it/s]

Gaps (ex-reports):  70%|███████   | 4983/7111 [18:35<07:15,  4.89it/s]

Gaps (ex-reports):  70%|███████   | 4984/7111 [18:35<07:06,  4.98it/s]

Gaps (ex-reports):  70%|███████   | 4985/7111 [18:35<07:03,  5.02it/s]

Gaps (ex-reports):  70%|███████   | 4986/7111 [18:36<07:12,  4.92it/s]

Gaps (ex-reports):  70%|███████   | 4987/7111 [18:36<07:11,  4.92it/s]

Gaps (ex-reports):  70%|███████   | 4988/7111 [18:36<07:16,  4.87it/s]

Gaps (ex-reports):  70%|███████   | 4989/7111 [18:36<07:15,  4.88it/s]

Gaps (ex-reports):  70%|███████   | 4990/7111 [18:36<07:15,  4.87it/s]

Gaps (ex-reports):  70%|███████   | 4991/7111 [18:37<07:17,  4.85it/s]

Gaps (ex-reports):  70%|███████   | 4992/7111 [18:37<07:17,  4.84it/s]

Gaps (ex-reports):  70%|███████   | 4993/7111 [18:37<07:21,  4.79it/s]

Gaps (ex-reports):  70%|███████   | 4994/7111 [18:37<07:18,  4.82it/s]

Gaps (ex-reports):  70%|███████   | 4995/7111 [18:38<07:22,  4.78it/s]

Gaps (ex-reports):  70%|███████   | 4996/7111 [18:38<07:32,  4.67it/s]

Gaps (ex-reports):  70%|███████   | 4997/7111 [18:38<07:23,  4.77it/s]

Gaps (ex-reports):  70%|███████   | 4998/7111 [18:38<07:15,  4.85it/s]

Gaps (ex-reports):  70%|███████   | 4999/7111 [18:38<07:11,  4.89it/s]

Gaps (ex-reports):  70%|███████   | 5000/7111 [18:39<07:15,  4.85it/s]

Gaps (ex-reports):  70%|███████   | 5001/7111 [18:39<07:03,  4.98it/s]

Gaps (ex-reports):  70%|███████   | 5002/7111 [18:39<08:06,  4.34it/s]

Gaps (ex-reports):  70%|███████   | 5003/7111 [18:39<07:48,  4.50it/s]

Gaps (ex-reports):  70%|███████   | 5004/7111 [18:39<07:36,  4.61it/s]

Gaps (ex-reports):  70%|███████   | 5005/7111 [18:40<07:28,  4.70it/s]

Gaps (ex-reports):  70%|███████   | 5006/7111 [18:40<07:32,  4.65it/s]

Gaps (ex-reports):  70%|███████   | 5007/7111 [18:40<07:20,  4.78it/s]

Gaps (ex-reports):  70%|███████   | 5008/7111 [18:40<07:10,  4.89it/s]

Gaps (ex-reports):  70%|███████   | 5009/7111 [18:40<07:16,  4.82it/s]

Gaps (ex-reports):  70%|███████   | 5010/7111 [18:41<07:10,  4.88it/s]

Gaps (ex-reports):  70%|███████   | 5011/7111 [18:41<07:07,  4.91it/s]

Gaps (ex-reports):  70%|███████   | 5012/7111 [18:41<07:10,  4.87it/s]

Gaps (ex-reports):  70%|███████   | 5013/7111 [18:41<07:16,  4.80it/s]

Gaps (ex-reports):  71%|███████   | 5014/7111 [18:42<07:12,  4.84it/s]

Gaps (ex-reports):  71%|███████   | 5015/7111 [18:42<07:16,  4.80it/s]

Gaps (ex-reports):  71%|███████   | 5016/7111 [18:42<07:12,  4.84it/s]

Gaps (ex-reports):  71%|███████   | 5017/7111 [18:42<07:20,  4.76it/s]

Gaps (ex-reports):  71%|███████   | 5018/7111 [18:42<07:21,  4.74it/s]

Gaps (ex-reports):  71%|███████   | 5019/7111 [18:43<07:17,  4.79it/s]

Gaps (ex-reports):  71%|███████   | 5020/7111 [18:43<07:21,  4.73it/s]

Gaps (ex-reports):  71%|███████   | 5021/7111 [18:43<07:10,  4.86it/s]

Gaps (ex-reports):  71%|███████   | 5022/7111 [18:43<07:02,  4.95it/s]

Gaps (ex-reports):  71%|███████   | 5023/7111 [18:43<07:06,  4.90it/s]

Gaps (ex-reports):  71%|███████   | 5024/7111 [18:44<06:57,  5.00it/s]

Gaps (ex-reports):  71%|███████   | 5025/7111 [18:44<06:53,  5.04it/s]

Gaps (ex-reports):  71%|███████   | 5026/7111 [18:44<06:55,  5.02it/s]

Gaps (ex-reports):  71%|███████   | 5027/7111 [18:44<06:52,  5.05it/s]

Gaps (ex-reports):  71%|███████   | 5028/7111 [18:44<06:50,  5.08it/s]

Gaps (ex-reports):  71%|███████   | 5029/7111 [18:45<06:47,  5.11it/s]

Gaps (ex-reports):  71%|███████   | 5030/7111 [18:45<06:55,  5.00it/s]

Gaps (ex-reports):  71%|███████   | 5031/7111 [18:45<07:02,  4.92it/s]

Gaps (ex-reports):  71%|███████   | 5032/7111 [18:45<06:59,  4.96it/s]

Gaps (ex-reports):  71%|███████   | 5033/7111 [18:45<07:01,  4.93it/s]

Gaps (ex-reports):  71%|███████   | 5034/7111 [18:46<07:03,  4.90it/s]

Gaps (ex-reports):  71%|███████   | 5035/7111 [18:46<07:06,  4.87it/s]

Gaps (ex-reports):  71%|███████   | 5036/7111 [18:46<07:08,  4.85it/s]

Gaps (ex-reports):  71%|███████   | 5037/7111 [18:46<07:15,  4.77it/s]

Gaps (ex-reports):  71%|███████   | 5038/7111 [18:46<07:20,  4.71it/s]

Gaps (ex-reports):  71%|███████   | 5039/7111 [18:47<07:14,  4.77it/s]

Gaps (ex-reports):  71%|███████   | 5040/7111 [18:47<07:13,  4.78it/s]

Gaps (ex-reports):  71%|███████   | 5041/7111 [18:47<07:08,  4.83it/s]

Gaps (ex-reports):  71%|███████   | 5042/7111 [18:47<07:11,  4.79it/s]

Gaps (ex-reports):  71%|███████   | 5043/7111 [18:47<06:59,  4.93it/s]

Gaps (ex-reports):  71%|███████   | 5044/7111 [18:48<07:05,  4.86it/s]

Gaps (ex-reports):  71%|███████   | 5045/7111 [18:48<06:57,  4.95it/s]

Gaps (ex-reports):  71%|███████   | 5046/7111 [18:48<07:02,  4.89it/s]

Gaps (ex-reports):  71%|███████   | 5047/7111 [18:48<06:57,  4.94it/s]

Gaps (ex-reports):  71%|███████   | 5048/7111 [18:48<06:52,  5.01it/s]

Gaps (ex-reports):  71%|███████   | 5049/7111 [18:49<07:00,  4.91it/s]

Gaps (ex-reports):  71%|███████   | 5050/7111 [18:49<07:02,  4.88it/s]

Gaps (ex-reports):  71%|███████   | 5051/7111 [18:49<07:01,  4.89it/s]

Gaps (ex-reports):  71%|███████   | 5052/7111 [18:49<07:06,  4.83it/s]

Gaps (ex-reports):  71%|███████   | 5053/7111 [18:49<07:01,  4.88it/s]

Gaps (ex-reports):  71%|███████   | 5054/7111 [18:50<07:07,  4.81it/s]

Gaps (ex-reports):  71%|███████   | 5055/7111 [18:50<06:55,  4.94it/s]

Gaps (ex-reports):  71%|███████   | 5056/7111 [18:50<06:58,  4.90it/s]

Gaps (ex-reports):  71%|███████   | 5057/7111 [18:50<06:51,  4.99it/s]

Gaps (ex-reports):  71%|███████   | 5058/7111 [18:50<06:47,  5.04it/s]

Gaps (ex-reports):  71%|███████   | 5059/7111 [18:51<06:44,  5.07it/s]

Gaps (ex-reports):  71%|███████   | 5060/7111 [18:51<06:39,  5.13it/s]

Gaps (ex-reports):  71%|███████   | 5061/7111 [18:51<06:42,  5.09it/s]

Gaps (ex-reports):  71%|███████   | 5062/7111 [18:51<06:45,  5.05it/s]

Gaps (ex-reports):  71%|███████   | 5063/7111 [18:51<06:52,  4.96it/s]

Gaps (ex-reports):  71%|███████   | 5064/7111 [18:52<06:54,  4.93it/s]

Gaps (ex-reports):  71%|███████   | 5065/7111 [18:52<06:47,  5.02it/s]

Gaps (ex-reports):  71%|███████   | 5066/7111 [18:52<06:42,  5.08it/s]

Gaps (ex-reports):  71%|███████▏  | 5067/7111 [18:52<06:40,  5.10it/s]

Gaps (ex-reports):  71%|███████▏  | 5068/7111 [18:52<06:48,  5.00it/s]

Gaps (ex-reports):  71%|███████▏  | 5069/7111 [18:53<06:52,  4.95it/s]

Gaps (ex-reports):  71%|███████▏  | 5070/7111 [18:53<06:48,  5.00it/s]

Gaps (ex-reports):  71%|███████▏  | 5071/7111 [18:53<06:52,  4.94it/s]

Gaps (ex-reports):  71%|███████▏  | 5072/7111 [18:53<06:56,  4.89it/s]

Gaps (ex-reports):  71%|███████▏  | 5073/7111 [18:53<06:55,  4.91it/s]

Gaps (ex-reports):  71%|███████▏  | 5074/7111 [18:54<06:48,  4.98it/s]

Gaps (ex-reports):  71%|███████▏  | 5075/7111 [18:54<07:00,  4.84it/s]

Gaps (ex-reports):  71%|███████▏  | 5076/7111 [18:54<06:54,  4.91it/s]

Gaps (ex-reports):  71%|███████▏  | 5077/7111 [18:54<06:55,  4.90it/s]

Gaps (ex-reports):  71%|███████▏  | 5078/7111 [18:59<53:46,  1.59s/it]

Gaps (ex-reports):  71%|███████▏  | 5079/7111 [18:59<39:43,  1.17s/it]

Gaps (ex-reports):  71%|███████▏  | 5080/7111 [19:00<29:57,  1.13it/s]

Gaps (ex-reports):  71%|███████▏  | 5081/7111 [19:00<23:07,  1.46it/s]

Gaps (ex-reports):  71%|███████▏  | 5082/7111 [19:00<18:12,  1.86it/s]

Gaps (ex-reports):  71%|███████▏  | 5083/7111 [19:00<14:53,  2.27it/s]

Gaps (ex-reports):  71%|███████▏  | 5084/7111 [19:00<12:29,  2.70it/s]

Gaps (ex-reports):  72%|███████▏  | 5085/7111 [19:01<10:47,  3.13it/s]

Gaps (ex-reports):  72%|███████▏  | 5086/7111 [19:01<09:39,  3.49it/s]

Gaps (ex-reports):  72%|███████▏  | 5087/7111 [19:01<08:44,  3.86it/s]

Gaps (ex-reports):  72%|███████▏  | 5088/7111 [19:01<08:11,  4.11it/s]

Gaps (ex-reports):  72%|███████▏  | 5089/7111 [19:01<07:43,  4.36it/s]

Gaps (ex-reports):  72%|███████▏  | 5090/7111 [19:02<10:00,  3.36it/s]

Gaps (ex-reports):  72%|███████▏  | 5091/7111 [19:02<08:58,  3.75it/s]

Gaps (ex-reports):  72%|███████▏  | 5092/7111 [19:02<08:14,  4.09it/s]

Gaps (ex-reports):  72%|███████▏  | 5093/7111 [19:02<07:41,  4.37it/s]

Gaps (ex-reports):  72%|███████▏  | 5094/7111 [19:03<07:24,  4.53it/s]

Gaps (ex-reports):  72%|███████▏  | 5095/7111 [19:03<07:11,  4.67it/s]

Gaps (ex-reports):  72%|███████▏  | 5096/7111 [19:03<06:57,  4.83it/s]

Gaps (ex-reports):  72%|███████▏  | 5097/7111 [19:04<14:42,  2.28it/s]

Gaps (ex-reports):  72%|███████▏  | 5098/7111 [19:04<12:13,  2.74it/s]

Gaps (ex-reports):  72%|███████▏  | 5099/7111 [19:04<10:28,  3.20it/s]

Gaps (ex-reports):  72%|███████▏  | 5100/7111 [19:05<09:15,  3.62it/s]

Gaps (ex-reports):  72%|███████▏  | 5101/7111 [19:05<08:24,  3.98it/s]

Gaps (ex-reports):  72%|███████▏  | 5102/7111 [19:05<08:04,  4.15it/s]

Gaps (ex-reports):  72%|███████▏  | 5103/7111 [19:05<07:40,  4.36it/s]

Gaps (ex-reports):  72%|███████▏  | 5104/7111 [19:05<07:34,  4.42it/s]

Gaps (ex-reports):  72%|███████▏  | 5105/7111 [19:06<07:13,  4.63it/s]

Gaps (ex-reports):  72%|███████▏  | 5106/7111 [19:06<07:04,  4.72it/s]

Gaps (ex-reports):  72%|███████▏  | 5107/7111 [19:06<06:53,  4.85it/s]

Gaps (ex-reports):  72%|███████▏  | 5108/7111 [19:06<06:48,  4.90it/s]

Gaps (ex-reports):  72%|███████▏  | 5109/7111 [19:06<06:49,  4.88it/s]

Gaps (ex-reports):  72%|███████▏  | 5110/7111 [19:07<06:42,  4.97it/s]

Gaps (ex-reports):  72%|███████▏  | 5111/7111 [19:07<06:49,  4.89it/s]

Gaps (ex-reports):  72%|███████▏  | 5112/7111 [19:07<06:55,  4.81it/s]

Gaps (ex-reports):  72%|███████▏  | 5113/7111 [19:07<06:50,  4.87it/s]

Gaps (ex-reports):  72%|███████▏  | 5114/7111 [19:07<06:51,  4.85it/s]

Gaps (ex-reports):  72%|███████▏  | 5115/7111 [19:08<06:40,  4.98it/s]

Gaps (ex-reports):  72%|███████▏  | 5116/7111 [19:08<06:32,  5.08it/s]

Gaps (ex-reports):  72%|███████▏  | 5117/7111 [19:08<06:28,  5.14it/s]

Gaps (ex-reports):  72%|███████▏  | 5118/7111 [19:08<06:31,  5.09it/s]

Gaps (ex-reports):  72%|███████▏  | 5119/7111 [19:08<06:30,  5.10it/s]

Gaps (ex-reports):  72%|███████▏  | 5120/7111 [19:09<06:40,  4.97it/s]

Gaps (ex-reports):  72%|███████▏  | 5121/7111 [19:09<07:23,  4.49it/s]

Gaps (ex-reports):  72%|███████▏  | 5122/7111 [19:09<07:15,  4.56it/s]

Gaps (ex-reports):  72%|███████▏  | 5123/7111 [19:09<07:04,  4.69it/s]

Gaps (ex-reports):  72%|███████▏  | 5124/7111 [19:09<06:56,  4.77it/s]

Gaps (ex-reports):  72%|███████▏  | 5125/7111 [19:10<06:53,  4.80it/s]

Gaps (ex-reports):  72%|███████▏  | 5126/7111 [19:10<06:46,  4.88it/s]

Gaps (ex-reports):  72%|███████▏  | 5127/7111 [19:10<06:39,  4.97it/s]

Gaps (ex-reports):  72%|███████▏  | 5128/7111 [19:10<06:41,  4.94it/s]

Gaps (ex-reports):  72%|███████▏  | 5129/7111 [19:11<16:13,  2.04it/s]

Gaps (ex-reports):  72%|███████▏  | 5130/7111 [19:12<13:22,  2.47it/s]

Gaps (ex-reports):  72%|███████▏  | 5131/7111 [19:12<11:46,  2.80it/s]

Gaps (ex-reports):  72%|███████▏  | 5132/7111 [19:12<10:22,  3.18it/s]

Gaps (ex-reports):  72%|███████▏  | 5133/7111 [19:12<09:20,  3.53it/s]

Gaps (ex-reports):  72%|███████▏  | 5134/7111 [19:13<09:00,  3.66it/s]

Gaps (ex-reports):  72%|███████▏  | 5135/7111 [19:13<08:23,  3.92it/s]

Gaps (ex-reports):  72%|███████▏  | 5136/7111 [19:13<07:50,  4.20it/s]

Gaps (ex-reports):  72%|███████▏  | 5137/7111 [19:13<07:23,  4.45it/s]

Gaps (ex-reports):  72%|███████▏  | 5138/7111 [19:13<08:16,  3.98it/s]

Gaps (ex-reports):  72%|███████▏  | 5139/7111 [19:14<07:44,  4.25it/s]

Gaps (ex-reports):  72%|███████▏  | 5140/7111 [19:14<07:18,  4.50it/s]

Gaps (ex-reports):  72%|███████▏  | 5141/7111 [19:14<07:01,  4.67it/s]

Gaps (ex-reports):  72%|███████▏  | 5142/7111 [19:14<06:55,  4.74it/s]

Gaps (ex-reports):  72%|███████▏  | 5143/7111 [19:14<06:45,  4.85it/s]

Gaps (ex-reports):  72%|███████▏  | 5144/7111 [19:15<06:36,  4.96it/s]

Gaps (ex-reports):  72%|███████▏  | 5145/7111 [19:15<06:30,  5.03it/s]

Gaps (ex-reports):  72%|███████▏  | 5146/7111 [19:15<06:28,  5.05it/s]

Gaps (ex-reports):  72%|███████▏  | 5147/7111 [19:15<06:33,  4.99it/s]

Gaps (ex-reports):  72%|███████▏  | 5148/7111 [19:15<06:29,  5.04it/s]

Gaps (ex-reports):  72%|███████▏  | 5149/7111 [19:16<11:04,  2.95it/s]

Gaps (ex-reports):  72%|███████▏  | 5150/7111 [19:16<09:42,  3.37it/s]

Gaps (ex-reports):  72%|███████▏  | 5151/7111 [19:17<08:52,  3.68it/s]

Gaps (ex-reports):  72%|███████▏  | 5152/7111 [19:17<08:15,  3.96it/s]

Gaps (ex-reports):  72%|███████▏  | 5153/7111 [19:17<07:50,  4.16it/s]

Gaps (ex-reports):  72%|███████▏  | 5154/7111 [19:17<07:24,  4.40it/s]

Gaps (ex-reports):  72%|███████▏  | 5155/7111 [19:17<07:06,  4.59it/s]

Gaps (ex-reports):  73%|███████▎  | 5156/7111 [19:18<07:06,  4.58it/s]

Gaps (ex-reports):  73%|███████▎  | 5157/7111 [19:18<06:50,  4.76it/s]

Gaps (ex-reports):  73%|███████▎  | 5158/7111 [19:18<06:52,  4.73it/s]

Gaps (ex-reports):  73%|███████▎  | 5159/7111 [19:18<06:45,  4.82it/s]

Gaps (ex-reports):  73%|███████▎  | 5160/7111 [19:18<06:41,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5161/7111 [19:19<06:35,  4.93it/s]

Gaps (ex-reports):  73%|███████▎  | 5162/7111 [19:19<06:36,  4.91it/s]

Gaps (ex-reports):  73%|███████▎  | 5163/7111 [19:19<06:38,  4.89it/s]

Gaps (ex-reports):  73%|███████▎  | 5164/7111 [19:19<06:40,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5165/7111 [19:19<06:40,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5166/7111 [19:20<06:32,  4.96it/s]

Gaps (ex-reports):  73%|███████▎  | 5167/7111 [19:20<11:14,  2.88it/s]

Gaps (ex-reports):  73%|███████▎  | 5168/7111 [19:20<09:50,  3.29it/s]

Gaps (ex-reports):  73%|███████▎  | 5169/7111 [19:21<08:56,  3.62it/s]

Gaps (ex-reports):  73%|███████▎  | 5170/7111 [19:21<08:13,  3.93it/s]

Gaps (ex-reports):  73%|███████▎  | 5171/7111 [19:21<07:52,  4.11it/s]

Gaps (ex-reports):  73%|███████▎  | 5172/7111 [19:21<07:33,  4.28it/s]

Gaps (ex-reports):  73%|███████▎  | 5173/7111 [19:22<07:14,  4.46it/s]

Gaps (ex-reports):  73%|███████▎  | 5174/7111 [19:22<07:08,  4.52it/s]

Gaps (ex-reports):  73%|███████▎  | 5175/7111 [19:22<06:55,  4.65it/s]

Gaps (ex-reports):  73%|███████▎  | 5176/7111 [19:22<06:48,  4.74it/s]

Gaps (ex-reports):  73%|███████▎  | 5177/7111 [19:22<06:44,  4.79it/s]

Gaps (ex-reports):  73%|███████▎  | 5178/7111 [19:23<06:41,  4.82it/s]

Gaps (ex-reports):  73%|███████▎  | 5179/7111 [19:23<06:34,  4.90it/s]

Gaps (ex-reports):  73%|███████▎  | 5180/7111 [19:23<06:37,  4.85it/s]

Gaps (ex-reports):  73%|███████▎  | 5181/7111 [19:23<06:42,  4.80it/s]

Gaps (ex-reports):  73%|███████▎  | 5182/7111 [19:23<06:40,  4.82it/s]

Gaps (ex-reports):  73%|███████▎  | 5183/7111 [19:24<06:38,  4.84it/s]

Gaps (ex-reports):  73%|███████▎  | 5184/7111 [19:24<06:36,  4.87it/s]

Gaps (ex-reports):  73%|███████▎  | 5185/7111 [19:24<06:29,  4.95it/s]

Gaps (ex-reports):  73%|███████▎  | 5186/7111 [19:24<06:23,  5.02it/s]

Gaps (ex-reports):  73%|███████▎  | 5187/7111 [19:24<06:26,  4.98it/s]

Gaps (ex-reports):  73%|███████▎  | 5188/7111 [19:25<06:27,  4.97it/s]

Gaps (ex-reports):  73%|███████▎  | 5189/7111 [19:25<06:27,  4.96it/s]

Gaps (ex-reports):  73%|███████▎  | 5190/7111 [19:25<06:28,  4.95it/s]

Gaps (ex-reports):  73%|███████▎  | 5191/7111 [19:25<06:34,  4.87it/s]

Gaps (ex-reports):  73%|███████▎  | 5192/7111 [19:25<06:31,  4.90it/s]

Gaps (ex-reports):  73%|███████▎  | 5193/7111 [19:26<06:37,  4.82it/s]

Gaps (ex-reports):  73%|███████▎  | 5194/7111 [19:26<06:40,  4.79it/s]

Gaps (ex-reports):  73%|███████▎  | 5195/7111 [19:26<06:40,  4.78it/s]

Gaps (ex-reports):  73%|███████▎  | 5196/7111 [19:26<06:39,  4.80it/s]

Gaps (ex-reports):  73%|███████▎  | 5197/7111 [19:26<06:37,  4.81it/s]

Gaps (ex-reports):  73%|███████▎  | 5198/7111 [19:27<06:39,  4.79it/s]

Gaps (ex-reports):  73%|███████▎  | 5199/7111 [19:27<06:45,  4.72it/s]

Gaps (ex-reports):  73%|███████▎  | 5200/7111 [19:27<06:44,  4.72it/s]

Gaps (ex-reports):  73%|███████▎  | 5201/7111 [19:27<06:37,  4.80it/s]

Gaps (ex-reports):  73%|███████▎  | 5202/7111 [19:27<06:40,  4.77it/s]

Gaps (ex-reports):  73%|███████▎  | 5203/7111 [19:28<06:39,  4.78it/s]

Gaps (ex-reports):  73%|███████▎  | 5204/7111 [19:28<06:38,  4.79it/s]

Gaps (ex-reports):  73%|███████▎  | 5205/7111 [19:28<06:35,  4.82it/s]

Gaps (ex-reports):  73%|███████▎  | 5206/7111 [19:28<06:32,  4.86it/s]

Gaps (ex-reports):  73%|███████▎  | 5207/7111 [19:29<06:24,  4.96it/s]

Gaps (ex-reports):  73%|███████▎  | 5208/7111 [19:29<06:27,  4.91it/s]

Gaps (ex-reports):  73%|███████▎  | 5209/7111 [19:29<06:25,  4.93it/s]

Gaps (ex-reports):  73%|███████▎  | 5210/7111 [19:29<06:43,  4.71it/s]

Gaps (ex-reports):  73%|███████▎  | 5211/7111 [19:29<06:36,  4.79it/s]

Gaps (ex-reports):  73%|███████▎  | 5212/7111 [19:30<06:32,  4.84it/s]

Gaps (ex-reports):  73%|███████▎  | 5213/7111 [19:30<06:26,  4.90it/s]

Gaps (ex-reports):  73%|███████▎  | 5214/7111 [19:30<06:29,  4.87it/s]

Gaps (ex-reports):  73%|███████▎  | 5215/7111 [19:30<06:29,  4.87it/s]

Gaps (ex-reports):  73%|███████▎  | 5216/7111 [19:30<06:25,  4.92it/s]

Gaps (ex-reports):  73%|███████▎  | 5217/7111 [19:31<06:24,  4.92it/s]

Gaps (ex-reports):  73%|███████▎  | 5218/7111 [19:31<06:29,  4.87it/s]

Gaps (ex-reports):  73%|███████▎  | 5219/7111 [19:31<06:20,  4.97it/s]

Gaps (ex-reports):  73%|███████▎  | 5220/7111 [19:31<06:17,  5.01it/s]

Gaps (ex-reports):  73%|███████▎  | 5221/7111 [19:31<06:17,  5.01it/s]

Gaps (ex-reports):  73%|███████▎  | 5222/7111 [19:32<06:24,  4.91it/s]

Gaps (ex-reports):  73%|███████▎  | 5223/7111 [19:32<06:19,  4.97it/s]

Gaps (ex-reports):  73%|███████▎  | 5224/7111 [19:32<06:21,  4.94it/s]

Gaps (ex-reports):  73%|███████▎  | 5225/7111 [19:32<06:20,  4.96it/s]

Gaps (ex-reports):  73%|███████▎  | 5226/7111 [19:32<06:14,  5.03it/s]

Gaps (ex-reports):  74%|███████▎  | 5227/7111 [19:33<06:27,  4.86it/s]

Gaps (ex-reports):  74%|███████▎  | 5228/7111 [19:33<06:21,  4.93it/s]

Gaps (ex-reports):  74%|███████▎  | 5229/7111 [19:33<06:18,  4.98it/s]

Gaps (ex-reports):  74%|███████▎  | 5230/7111 [19:33<06:13,  5.03it/s]

Gaps (ex-reports):  74%|███████▎  | 5231/7111 [19:33<06:08,  5.10it/s]

Gaps (ex-reports):  74%|███████▎  | 5232/7111 [19:34<06:15,  5.00it/s]

Gaps (ex-reports):  74%|███████▎  | 5233/7111 [19:34<06:19,  4.95it/s]

Gaps (ex-reports):  74%|███████▎  | 5234/7111 [19:34<06:20,  4.93it/s]

Gaps (ex-reports):  74%|███████▎  | 5235/7111 [19:34<06:26,  4.86it/s]

Gaps (ex-reports):  74%|███████▎  | 5236/7111 [19:34<06:28,  4.82it/s]

Gaps (ex-reports):  74%|███████▎  | 5237/7111 [19:35<06:30,  4.80it/s]

Gaps (ex-reports):  74%|███████▎  | 5238/7111 [19:35<06:33,  4.76it/s]

Gaps (ex-reports):  74%|███████▎  | 5239/7111 [19:35<06:26,  4.85it/s]

Gaps (ex-reports):  74%|███████▎  | 5240/7111 [19:35<06:34,  4.74it/s]

Gaps (ex-reports):  74%|███████▎  | 5241/7111 [19:35<06:35,  4.73it/s]

Gaps (ex-reports):  74%|███████▎  | 5242/7111 [19:36<06:30,  4.78it/s]

Gaps (ex-reports):  74%|███████▎  | 5243/7111 [19:36<06:20,  4.91it/s]

Gaps (ex-reports):  74%|███████▎  | 5244/7111 [19:36<06:19,  4.93it/s]

Gaps (ex-reports):  74%|███████▍  | 5245/7111 [19:36<06:12,  5.02it/s]

Gaps (ex-reports):  74%|███████▍  | 5246/7111 [19:36<06:15,  4.97it/s]

Gaps (ex-reports):  74%|███████▍  | 5247/7111 [19:37<06:17,  4.94it/s]

Gaps (ex-reports):  74%|███████▍  | 5248/7111 [19:37<06:31,  4.76it/s]

Gaps (ex-reports):  74%|███████▍  | 5249/7111 [19:37<06:28,  4.80it/s]

Gaps (ex-reports):  74%|███████▍  | 5250/7111 [19:37<06:34,  4.72it/s]

Gaps (ex-reports):  74%|███████▍  | 5251/7111 [19:38<06:31,  4.75it/s]

Gaps (ex-reports):  74%|███████▍  | 5252/7111 [19:38<06:23,  4.85it/s]

Gaps (ex-reports):  74%|███████▍  | 5253/7111 [19:38<06:17,  4.92it/s]

Gaps (ex-reports):  74%|███████▍  | 5254/7111 [19:38<06:14,  4.96it/s]

Gaps (ex-reports):  74%|███████▍  | 5255/7111 [19:38<06:19,  4.89it/s]

Gaps (ex-reports):  74%|███████▍  | 5256/7111 [19:39<06:22,  4.85it/s]

Gaps (ex-reports):  74%|███████▍  | 5257/7111 [19:39<06:23,  4.83it/s]

Gaps (ex-reports):  74%|███████▍  | 5258/7111 [19:39<06:23,  4.83it/s]

Gaps (ex-reports):  74%|███████▍  | 5259/7111 [19:39<06:26,  4.79it/s]

Gaps (ex-reports):  74%|███████▍  | 5260/7111 [19:39<06:24,  4.81it/s]

Gaps (ex-reports):  74%|███████▍  | 5261/7111 [19:40<06:29,  4.75it/s]

Gaps (ex-reports):  74%|███████▍  | 5262/7111 [19:40<06:22,  4.83it/s]

Gaps (ex-reports):  74%|███████▍  | 5263/7111 [19:40<06:09,  5.01it/s]

Gaps (ex-reports):  74%|███████▍  | 5264/7111 [19:40<06:12,  4.96it/s]

Gaps (ex-reports):  74%|███████▍  | 5265/7111 [19:40<06:16,  4.90it/s]

Gaps (ex-reports):  74%|███████▍  | 5266/7111 [19:41<06:22,  4.83it/s]

Gaps (ex-reports):  74%|███████▍  | 5267/7111 [19:41<06:21,  4.84it/s]

Gaps (ex-reports):  74%|███████▍  | 5268/7111 [19:41<06:22,  4.82it/s]

Gaps (ex-reports):  74%|███████▍  | 5269/7111 [19:41<06:19,  4.85it/s]

Gaps (ex-reports):  74%|███████▍  | 5270/7111 [19:41<06:22,  4.81it/s]

Gaps (ex-reports):  74%|███████▍  | 5271/7111 [19:42<06:28,  4.74it/s]

Gaps (ex-reports):  74%|███████▍  | 5272/7111 [19:42<06:29,  4.72it/s]

Gaps (ex-reports):  74%|███████▍  | 5273/7111 [19:42<06:26,  4.75it/s]

Gaps (ex-reports):  74%|███████▍  | 5274/7111 [19:42<06:16,  4.87it/s]

Gaps (ex-reports):  74%|███████▍  | 5275/7111 [19:43<07:22,  4.15it/s]

Gaps (ex-reports):  74%|███████▍  | 5276/7111 [19:43<07:01,  4.36it/s]

Gaps (ex-reports):  74%|███████▍  | 5277/7111 [19:43<06:47,  4.50it/s]

Gaps (ex-reports):  74%|███████▍  | 5278/7111 [19:43<06:45,  4.52it/s]

Gaps (ex-reports):  74%|███████▍  | 5279/7111 [19:43<06:34,  4.65it/s]

Gaps (ex-reports):  74%|███████▍  | 5280/7111 [19:44<06:34,  4.64it/s]

Gaps (ex-reports):  74%|███████▍  | 5281/7111 [19:44<06:24,  4.76it/s]

Gaps (ex-reports):  74%|███████▍  | 5282/7111 [19:44<06:24,  4.76it/s]

Gaps (ex-reports):  74%|███████▍  | 5283/7111 [19:44<06:18,  4.82it/s]

Gaps (ex-reports):  74%|███████▍  | 5284/7111 [19:44<06:13,  4.89it/s]

Gaps (ex-reports):  74%|███████▍  | 5285/7111 [19:45<06:17,  4.83it/s]

Gaps (ex-reports):  74%|███████▍  | 5286/7111 [19:45<06:15,  4.86it/s]

Gaps (ex-reports):  74%|███████▍  | 5287/7111 [19:46<10:43,  2.84it/s]

Gaps (ex-reports):  74%|███████▍  | 5288/7111 [19:46<09:21,  3.25it/s]

Gaps (ex-reports):  74%|███████▍  | 5289/7111 [19:46<08:27,  3.59it/s]

Gaps (ex-reports):  74%|███████▍  | 5290/7111 [19:46<07:47,  3.90it/s]

Gaps (ex-reports):  74%|███████▍  | 5291/7111 [19:46<07:17,  4.16it/s]

Gaps (ex-reports):  74%|███████▍  | 5292/7111 [19:47<07:06,  4.27it/s]

Gaps (ex-reports):  74%|███████▍  | 5293/7111 [19:47<06:51,  4.42it/s]

Gaps (ex-reports):  74%|███████▍  | 5294/7111 [19:47<06:37,  4.57it/s]

Gaps (ex-reports):  74%|███████▍  | 5295/7111 [19:47<06:48,  4.44it/s]

Gaps (ex-reports):  74%|███████▍  | 5296/7111 [19:47<06:43,  4.50it/s]

Gaps (ex-reports):  74%|███████▍  | 5297/7111 [19:48<06:33,  4.61it/s]

Gaps (ex-reports):  75%|███████▍  | 5298/7111 [19:48<06:25,  4.70it/s]

Gaps (ex-reports):  75%|███████▍  | 5299/7111 [19:48<06:24,  4.71it/s]

Gaps (ex-reports):  75%|███████▍  | 5300/7111 [19:48<06:22,  4.74it/s]

Gaps (ex-reports):  75%|███████▍  | 5301/7111 [19:48<06:17,  4.80it/s]

Gaps (ex-reports):  75%|███████▍  | 5302/7111 [19:49<06:08,  4.91it/s]

Gaps (ex-reports):  75%|███████▍  | 5303/7111 [19:49<08:46,  3.44it/s]

Gaps (ex-reports):  75%|███████▍  | 5304/7111 [19:49<07:56,  3.80it/s]

Gaps (ex-reports):  75%|███████▍  | 5305/7111 [19:50<07:22,  4.08it/s]

Gaps (ex-reports):  75%|███████▍  | 5306/7111 [19:50<07:05,  4.25it/s]

Gaps (ex-reports):  75%|███████▍  | 5307/7111 [19:50<06:47,  4.43it/s]

Gaps (ex-reports):  75%|███████▍  | 5308/7111 [19:50<06:37,  4.54it/s]

Gaps (ex-reports):  75%|███████▍  | 5309/7111 [19:50<06:34,  4.57it/s]

Gaps (ex-reports):  75%|███████▍  | 5310/7111 [19:51<06:34,  4.56it/s]

Gaps (ex-reports):  75%|███████▍  | 5311/7111 [19:51<06:28,  4.63it/s]

Gaps (ex-reports):  75%|███████▍  | 5312/7111 [19:51<06:15,  4.80it/s]

Gaps (ex-reports):  75%|███████▍  | 5313/7111 [19:51<06:16,  4.78it/s]

Gaps (ex-reports):  75%|███████▍  | 5314/7111 [19:51<06:11,  4.83it/s]

Gaps (ex-reports):  75%|███████▍  | 5315/7111 [19:52<06:07,  4.88it/s]

Gaps (ex-reports):  75%|███████▍  | 5316/7111 [19:52<06:06,  4.90it/s]

Gaps (ex-reports):  75%|███████▍  | 5317/7111 [19:52<06:09,  4.85it/s]

Gaps (ex-reports):  75%|███████▍  | 5318/7111 [19:52<06:08,  4.86it/s]

Gaps (ex-reports):  75%|███████▍  | 5319/7111 [19:52<06:13,  4.80it/s]

Gaps (ex-reports):  75%|███████▍  | 5320/7111 [19:53<06:08,  4.87it/s]

Gaps (ex-reports):  75%|███████▍  | 5321/7111 [19:53<06:06,  4.88it/s]

Gaps (ex-reports):  75%|███████▍  | 5322/7111 [19:53<06:05,  4.89it/s]

Gaps (ex-reports):  75%|███████▍  | 5323/7111 [19:53<06:07,  4.87it/s]

Gaps (ex-reports):  75%|███████▍  | 5324/7111 [19:53<06:06,  4.88it/s]

Gaps (ex-reports):  75%|███████▍  | 5325/7111 [19:54<05:59,  4.97it/s]

Gaps (ex-reports):  75%|███████▍  | 5326/7111 [19:54<05:59,  4.96it/s]

Gaps (ex-reports):  75%|███████▍  | 5327/7111 [19:54<06:00,  4.95it/s]

Gaps (ex-reports):  75%|███████▍  | 5328/7111 [19:54<05:58,  4.98it/s]

Gaps (ex-reports):  75%|███████▍  | 5329/7111 [19:55<06:05,  4.87it/s]

Gaps (ex-reports):  75%|███████▍  | 5330/7111 [19:55<06:05,  4.88it/s]

Gaps (ex-reports):  75%|███████▍  | 5331/7111 [19:55<06:07,  4.85it/s]

Gaps (ex-reports):  75%|███████▍  | 5332/7111 [19:55<06:15,  4.73it/s]

Gaps (ex-reports):  75%|███████▍  | 5333/7111 [19:55<06:15,  4.73it/s]

Gaps (ex-reports):  75%|███████▌  | 5334/7111 [19:56<06:09,  4.80it/s]

Gaps (ex-reports):  75%|███████▌  | 5335/7111 [19:56<06:00,  4.92it/s]

Gaps (ex-reports):  75%|███████▌  | 5336/7111 [19:56<05:55,  4.99it/s]

Gaps (ex-reports):  75%|███████▌  | 5337/7111 [19:56<09:02,  3.27it/s]

Gaps (ex-reports):  75%|███████▌  | 5338/7111 [19:57<08:05,  3.65it/s]

Gaps (ex-reports):  75%|███████▌  | 5339/7111 [19:57<07:31,  3.93it/s]

Gaps (ex-reports):  75%|███████▌  | 5340/7111 [19:57<06:56,  4.25it/s]

Gaps (ex-reports):  75%|███████▌  | 5341/7111 [19:57<06:43,  4.39it/s]

Gaps (ex-reports):  75%|███████▌  | 5342/7111 [19:58<06:30,  4.53it/s]

Gaps (ex-reports):  75%|███████▌  | 5343/7111 [19:58<06:23,  4.61it/s]

Gaps (ex-reports):  75%|███████▌  | 5344/7111 [19:58<06:14,  4.72it/s]

Gaps (ex-reports):  75%|███████▌  | 5345/7111 [19:58<06:02,  4.87it/s]

Gaps (ex-reports):  75%|███████▌  | 5346/7111 [19:58<06:08,  4.79it/s]

Gaps (ex-reports):  75%|███████▌  | 5347/7111 [19:59<06:07,  4.80it/s]

Gaps (ex-reports):  75%|███████▌  | 5348/7111 [19:59<06:00,  4.89it/s]

Gaps (ex-reports):  75%|███████▌  | 5349/7111 [19:59<06:02,  4.87it/s]

Gaps (ex-reports):  75%|███████▌  | 5350/7111 [19:59<05:58,  4.92it/s]

Gaps (ex-reports):  75%|███████▌  | 5351/7111 [19:59<05:59,  4.90it/s]

Gaps (ex-reports):  75%|███████▌  | 5352/7111 [20:00<05:59,  4.89it/s]

Gaps (ex-reports):  75%|███████▌  | 5353/7111 [20:00<05:54,  4.97it/s]

Gaps (ex-reports):  75%|███████▌  | 5354/7111 [20:00<05:56,  4.93it/s]

Gaps (ex-reports):  75%|███████▌  | 5355/7111 [20:00<05:53,  4.97it/s]

Gaps (ex-reports):  75%|███████▌  | 5356/7111 [20:00<05:56,  4.92it/s]

Gaps (ex-reports):  75%|███████▌  | 5357/7111 [20:01<05:55,  4.93it/s]

Gaps (ex-reports):  75%|███████▌  | 5358/7111 [20:01<05:59,  4.87it/s]

Gaps (ex-reports):  75%|███████▌  | 5359/7111 [20:01<06:00,  4.86it/s]

Gaps (ex-reports):  75%|███████▌  | 5360/7111 [20:01<06:00,  4.85it/s]

Gaps (ex-reports):  75%|███████▌  | 5361/7111 [20:02<15:45,  1.85it/s]

Gaps (ex-reports):  75%|███████▌  | 5362/7111 [20:03<12:45,  2.28it/s]

Gaps (ex-reports):  75%|███████▌  | 5363/7111 [20:03<10:42,  2.72it/s]

Gaps (ex-reports):  75%|███████▌  | 5364/7111 [20:03<09:12,  3.16it/s]

Gaps (ex-reports):  75%|███████▌  | 5365/7111 [20:03<08:07,  3.58it/s]

Gaps (ex-reports):  75%|███████▌  | 5366/7111 [20:03<07:32,  3.85it/s]

Gaps (ex-reports):  75%|███████▌  | 5367/7111 [20:04<07:07,  4.08it/s]

Gaps (ex-reports):  75%|███████▌  | 5368/7111 [20:04<06:50,  4.24it/s]

Gaps (ex-reports):  76%|███████▌  | 5369/7111 [20:04<06:45,  4.29it/s]

Gaps (ex-reports):  76%|███████▌  | 5370/7111 [20:04<06:29,  4.47it/s]

Gaps (ex-reports):  76%|███████▌  | 5371/7111 [20:05<06:11,  4.68it/s]

Gaps (ex-reports):  76%|███████▌  | 5372/7111 [20:05<06:02,  4.79it/s]

Gaps (ex-reports):  76%|███████▌  | 5373/7111 [20:05<06:03,  4.78it/s]

Gaps (ex-reports):  76%|███████▌  | 5374/7111 [20:05<06:02,  4.79it/s]

Gaps (ex-reports):  76%|███████▌  | 5375/7111 [20:05<05:59,  4.83it/s]

Gaps (ex-reports):  76%|███████▌  | 5376/7111 [20:06<06:00,  4.81it/s]

Gaps (ex-reports):  76%|███████▌  | 5377/7111 [20:06<06:04,  4.76it/s]

Gaps (ex-reports):  76%|███████▌  | 5378/7111 [20:06<05:54,  4.89it/s]

Gaps (ex-reports):  76%|███████▌  | 5379/7111 [20:06<05:47,  4.98it/s]

Gaps (ex-reports):  76%|███████▌  | 5380/7111 [20:06<05:51,  4.93it/s]

Gaps (ex-reports):  76%|███████▌  | 5381/7111 [20:07<05:47,  4.98it/s]

Gaps (ex-reports):  76%|███████▌  | 5382/7111 [20:07<05:44,  5.02it/s]

Gaps (ex-reports):  76%|███████▌  | 5383/7111 [20:07<05:44,  5.02it/s]

Gaps (ex-reports):  76%|███████▌  | 5384/7111 [20:07<05:48,  4.95it/s]

Gaps (ex-reports):  76%|███████▌  | 5385/7111 [20:07<05:47,  4.97it/s]

Gaps (ex-reports):  76%|███████▌  | 5386/7111 [20:08<05:50,  4.92it/s]

Gaps (ex-reports):  76%|███████▌  | 5387/7111 [20:08<07:55,  3.63it/s]

Gaps (ex-reports):  76%|███████▌  | 5388/7111 [20:08<07:14,  3.97it/s]

Gaps (ex-reports):  76%|███████▌  | 5389/7111 [20:08<06:51,  4.19it/s]

Gaps (ex-reports):  76%|███████▌  | 5390/7111 [20:09<06:37,  4.33it/s]

Gaps (ex-reports):  76%|███████▌  | 5391/7111 [20:10<12:42,  2.25it/s]

Gaps (ex-reports):  76%|███████▌  | 5392/7111 [20:10<10:38,  2.69it/s]

Gaps (ex-reports):  76%|███████▌  | 5393/7111 [20:10<09:13,  3.10it/s]

Gaps (ex-reports):  76%|███████▌  | 5394/7111 [20:10<08:12,  3.49it/s]

Gaps (ex-reports):  76%|███████▌  | 5395/7111 [20:12<19:38,  1.46it/s]

Gaps (ex-reports):  76%|███████▌  | 5396/7111 [20:12<15:20,  1.86it/s]

Gaps (ex-reports):  76%|███████▌  | 5397/7111 [20:12<12:30,  2.28it/s]

Gaps (ex-reports):  76%|███████▌  | 5398/7111 [20:12<10:36,  2.69it/s]

Gaps (ex-reports):  76%|███████▌  | 5399/7111 [20:13<09:18,  3.06it/s]

Gaps (ex-reports):  76%|███████▌  | 5400/7111 [20:13<08:15,  3.46it/s]

Gaps (ex-reports):  76%|███████▌  | 5401/7111 [20:13<07:42,  3.70it/s]

Gaps (ex-reports):  76%|███████▌  | 5402/7111 [20:13<07:09,  3.98it/s]

Gaps (ex-reports):  76%|███████▌  | 5403/7111 [20:13<06:46,  4.20it/s]

Gaps (ex-reports):  76%|███████▌  | 5404/7111 [20:14<06:23,  4.45it/s]

Gaps (ex-reports):  76%|███████▌  | 5405/7111 [20:14<06:13,  4.56it/s]

Gaps (ex-reports):  76%|███████▌  | 5406/7111 [20:14<06:05,  4.67it/s]

Gaps (ex-reports):  76%|███████▌  | 5407/7111 [20:14<05:54,  4.80it/s]

Gaps (ex-reports):  76%|███████▌  | 5408/7111 [20:15<06:02,  4.69it/s]

Gaps (ex-reports):  76%|███████▌  | 5409/7111 [20:15<05:57,  4.76it/s]

Gaps (ex-reports):  76%|███████▌  | 5410/7111 [20:15<05:51,  4.84it/s]

Gaps (ex-reports):  76%|███████▌  | 5411/7111 [20:15<05:53,  4.81it/s]

Gaps (ex-reports):  76%|███████▌  | 5412/7111 [20:15<05:55,  4.78it/s]

Gaps (ex-reports):  76%|███████▌  | 5413/7111 [20:16<05:57,  4.75it/s]

Gaps (ex-reports):  76%|███████▌  | 5414/7111 [20:16<05:56,  4.75it/s]

Gaps (ex-reports):  76%|███████▌  | 5415/7111 [20:16<05:54,  4.78it/s]

Gaps (ex-reports):  76%|███████▌  | 5416/7111 [20:16<05:47,  4.87it/s]

Gaps (ex-reports):  76%|███████▌  | 5417/7111 [20:16<05:51,  4.82it/s]

Gaps (ex-reports):  76%|███████▌  | 5418/7111 [20:17<05:47,  4.87it/s]

Gaps (ex-reports):  76%|███████▌  | 5419/7111 [20:17<05:49,  4.84it/s]

Gaps (ex-reports):  76%|███████▌  | 5420/7111 [20:17<05:43,  4.92it/s]

Gaps (ex-reports):  76%|███████▌  | 5421/7111 [20:17<05:43,  4.92it/s]

Gaps (ex-reports):  76%|███████▌  | 5422/7111 [20:17<05:37,  5.00it/s]

Gaps (ex-reports):  76%|███████▋  | 5423/7111 [20:18<05:38,  4.99it/s]

Gaps (ex-reports):  76%|███████▋  | 5424/7111 [20:18<05:36,  5.01it/s]

Gaps (ex-reports):  76%|███████▋  | 5425/7111 [20:18<05:32,  5.08it/s]

Gaps (ex-reports):  76%|███████▋  | 5426/7111 [20:18<05:39,  4.96it/s]

Gaps (ex-reports):  76%|███████▋  | 5427/7111 [20:18<05:45,  4.88it/s]

Gaps (ex-reports):  76%|███████▋  | 5428/7111 [20:19<05:38,  4.98it/s]

Gaps (ex-reports):  76%|███████▋  | 5429/7111 [20:19<05:39,  4.95it/s]

Gaps (ex-reports):  76%|███████▋  | 5430/7111 [20:19<05:43,  4.90it/s]

Gaps (ex-reports):  76%|███████▋  | 5431/7111 [20:19<05:49,  4.81it/s]

Gaps (ex-reports):  76%|███████▋  | 5432/7111 [20:19<05:43,  4.89it/s]

Gaps (ex-reports):  76%|███████▋  | 5433/7111 [20:20<05:38,  4.96it/s]

Gaps (ex-reports):  76%|███████▋  | 5434/7111 [20:20<07:22,  3.79it/s]

Gaps (ex-reports):  76%|███████▋  | 5435/7111 [20:20<06:49,  4.09it/s]

Gaps (ex-reports):  76%|███████▋  | 5436/7111 [20:20<06:33,  4.26it/s]

Gaps (ex-reports):  76%|███████▋  | 5437/7111 [20:21<06:26,  4.33it/s]

Gaps (ex-reports):  76%|███████▋  | 5438/7111 [20:21<06:05,  4.58it/s]

Gaps (ex-reports):  76%|███████▋  | 5439/7111 [20:21<05:53,  4.73it/s]

Gaps (ex-reports):  77%|███████▋  | 5440/7111 [20:21<05:42,  4.88it/s]

Gaps (ex-reports):  77%|███████▋  | 5441/7111 [20:21<05:43,  4.87it/s]

Gaps (ex-reports):  77%|███████▋  | 5442/7111 [20:43<3:01:21,  6.52s/it]

Gaps (ex-reports):  77%|███████▋  | 5443/7111 [20:43<2:08:30,  4.62s/it]

Gaps (ex-reports):  77%|███████▋  | 5444/7111 [20:43<1:31:29,  3.29s/it]

Gaps (ex-reports):  77%|███████▋  | 5445/7111 [20:43<1:05:48,  2.37s/it]

Gaps (ex-reports):  77%|███████▋  | 5446/7111 [20:43<47:45,  1.72s/it]

Gaps (ex-reports):  77%|███████▋  | 5447/7111 [20:44<35:05,  1.27s/it]

Gaps (ex-reports):  77%|███████▋  | 5448/7111 [20:44<26:08,  1.06it/s]

Gaps (ex-reports):  77%|███████▋  | 5449/7111 [20:44<22:13,  1.25it/s]

Gaps (ex-reports):  77%|███████▋  | 5450/7111 [20:45<17:11,  1.61it/s]

Gaps (ex-reports):  77%|███████▋  | 5451/7111 [20:45<13:39,  2.02it/s]

Gaps (ex-reports):  77%|███████▋  | 5452/7111 [20:45<11:45,  2.35it/s]

Gaps (ex-reports):  77%|███████▋  | 5453/7111 [20:45<09:54,  2.79it/s]

Gaps (ex-reports):  77%|███████▋  | 5454/7111 [20:45<08:39,  3.19it/s]

Gaps (ex-reports):  77%|███████▋  | 5455/7111 [20:46<07:49,  3.53it/s]

Gaps (ex-reports):  77%|███████▋  | 5456/7111 [20:46<07:04,  3.90it/s]

Gaps (ex-reports):  77%|███████▋  | 5457/7111 [20:46<06:36,  4.17it/s]

Gaps (ex-reports):  77%|███████▋  | 5458/7111 [20:46<06:18,  4.37it/s]

Gaps (ex-reports):  77%|███████▋  | 5459/7111 [20:46<06:13,  4.43it/s]

Gaps (ex-reports):  77%|███████▋  | 5460/7111 [20:47<05:57,  4.62it/s]

Gaps (ex-reports):  77%|███████▋  | 5461/7111 [20:47<05:51,  4.70it/s]

Gaps (ex-reports):  77%|███████▋  | 5462/7111 [20:47<05:42,  4.81it/s]

Gaps (ex-reports):  77%|███████▋  | 5463/7111 [20:47<05:46,  4.75it/s]

Gaps (ex-reports):  77%|███████▋  | 5464/7111 [20:47<05:39,  4.85it/s]

Gaps (ex-reports):  77%|███████▋  | 5465/7111 [20:48<05:44,  4.77it/s]

Gaps (ex-reports):  77%|███████▋  | 5466/7111 [20:48<05:43,  4.79it/s]

Gaps (ex-reports):  77%|███████▋  | 5467/7111 [20:48<05:35,  4.90it/s]

Gaps (ex-reports):  77%|███████▋  | 5468/7111 [20:48<05:36,  4.89it/s]

Gaps (ex-reports):  77%|███████▋  | 5469/7111 [20:48<05:37,  4.87it/s]

Gaps (ex-reports):  77%|███████▋  | 5470/7111 [20:49<05:41,  4.81it/s]

Gaps (ex-reports):  77%|███████▋  | 5471/7111 [20:49<05:41,  4.80it/s]

Gaps (ex-reports):  77%|███████▋  | 5472/7111 [20:49<06:47,  4.03it/s]

Gaps (ex-reports):  77%|███████▋  | 5473/7111 [20:50<07:45,  3.52it/s]

Gaps (ex-reports):  77%|███████▋  | 5474/7111 [20:50<07:02,  3.88it/s]

Gaps (ex-reports):  77%|███████▋  | 5475/7111 [20:50<06:34,  4.15it/s]

Gaps (ex-reports):  77%|███████▋  | 5476/7111 [20:50<06:10,  4.42it/s]

Gaps (ex-reports):  77%|███████▋  | 5477/7111 [20:50<06:02,  4.50it/s]

Gaps (ex-reports):  77%|███████▋  | 5478/7111 [20:51<05:58,  4.55it/s]

Gaps (ex-reports):  77%|███████▋  | 5479/7111 [20:51<05:55,  4.59it/s]

Gaps (ex-reports):  77%|███████▋  | 5480/7111 [20:51<05:52,  4.63it/s]

Gaps (ex-reports):  77%|███████▋  | 5481/7111 [20:51<05:48,  4.67it/s]

Gaps (ex-reports):  77%|███████▋  | 5482/7111 [20:51<05:46,  4.70it/s]

Gaps (ex-reports):  77%|███████▋  | 5483/7111 [20:52<06:31,  4.16it/s]

Gaps (ex-reports):  77%|███████▋  | 5484/7111 [20:52<06:15,  4.34it/s]

Gaps (ex-reports):  77%|███████▋  | 5485/7111 [20:53<10:02,  2.70it/s]

Gaps (ex-reports):  77%|███████▋  | 5486/7111 [20:53<08:38,  3.13it/s]

Gaps (ex-reports):  77%|███████▋  | 5487/7111 [20:53<07:44,  3.49it/s]

Gaps (ex-reports):  77%|███████▋  | 5488/7111 [20:53<07:04,  3.82it/s]

Gaps (ex-reports):  77%|███████▋  | 5489/7111 [20:54<06:39,  4.06it/s]

Gaps (ex-reports):  77%|███████▋  | 5490/7111 [20:54<06:19,  4.27it/s]

Gaps (ex-reports):  77%|███████▋  | 5491/7111 [20:54<06:03,  4.45it/s]

Gaps (ex-reports):  77%|███████▋  | 5492/7111 [20:54<05:57,  4.53it/s]

Gaps (ex-reports):  77%|███████▋  | 5493/7111 [20:55<07:32,  3.58it/s]

Gaps (ex-reports):  77%|███████▋  | 5494/7111 [20:55<06:58,  3.87it/s]

Gaps (ex-reports):  77%|███████▋  | 5495/7111 [20:55<06:40,  4.03it/s]

Gaps (ex-reports):  77%|███████▋  | 5496/7111 [20:55<06:23,  4.21it/s]

Gaps (ex-reports):  77%|███████▋  | 5497/7111 [20:55<06:10,  4.35it/s]

Gaps (ex-reports):  77%|███████▋  | 5498/7111 [20:56<06:02,  4.45it/s]

Gaps (ex-reports):  77%|███████▋  | 5499/7111 [20:56<05:51,  4.58it/s]

Gaps (ex-reports):  77%|███████▋  | 5500/7111 [20:56<05:54,  4.55it/s]

Gaps (ex-reports):  77%|███████▋  | 5501/7111 [20:56<05:50,  4.60it/s]

Gaps (ex-reports):  77%|███████▋  | 5502/7111 [20:56<05:50,  4.59it/s]

Gaps (ex-reports):  77%|███████▋  | 5503/7111 [20:57<05:40,  4.72it/s]

Gaps (ex-reports):  77%|███████▋  | 5504/7111 [20:57<05:41,  4.70it/s]

Gaps (ex-reports):  77%|███████▋  | 5505/7111 [20:57<05:39,  4.73it/s]

Gaps (ex-reports):  77%|███████▋  | 5506/7111 [20:57<05:35,  4.78it/s]

Gaps (ex-reports):  77%|███████▋  | 5507/7111 [20:58<05:32,  4.82it/s]

Gaps (ex-reports):  77%|███████▋  | 5508/7111 [20:58<05:28,  4.88it/s]

Gaps (ex-reports):  77%|███████▋  | 5509/7111 [20:58<05:27,  4.89it/s]

Gaps (ex-reports):  77%|███████▋  | 5510/7111 [20:58<05:25,  4.93it/s]

Gaps (ex-reports):  77%|███████▋  | 5511/7111 [20:58<05:24,  4.93it/s]

Gaps (ex-reports):  78%|███████▊  | 5512/7111 [20:59<05:20,  4.99it/s]

Gaps (ex-reports):  78%|███████▊  | 5513/7111 [20:59<05:21,  4.97it/s]

Gaps (ex-reports):  78%|███████▊  | 5514/7111 [20:59<07:19,  3.63it/s]

Gaps (ex-reports):  78%|███████▊  | 5515/7111 [20:59<06:43,  3.96it/s]

Gaps (ex-reports):  78%|███████▊  | 5516/7111 [21:00<06:20,  4.19it/s]

Gaps (ex-reports):  78%|███████▊  | 5517/7111 [21:00<06:04,  4.37it/s]

Gaps (ex-reports):  78%|███████▊  | 5518/7111 [21:01<11:05,  2.39it/s]

Gaps (ex-reports):  78%|███████▊  | 5519/7111 [21:01<09:25,  2.82it/s]

Gaps (ex-reports):  78%|███████▊  | 5520/7111 [21:01<08:15,  3.21it/s]

Gaps (ex-reports):  78%|███████▊  | 5521/7111 [21:01<07:50,  3.38it/s]

Gaps (ex-reports):  78%|███████▊  | 5522/7111 [21:02<07:12,  3.68it/s]

Gaps (ex-reports):  78%|███████▊  | 5523/7111 [21:02<06:37,  4.00it/s]

Gaps (ex-reports):  78%|███████▊  | 5524/7111 [21:02<06:16,  4.22it/s]

Gaps (ex-reports):  78%|███████▊  | 5525/7111 [21:02<06:35,  4.01it/s]

Gaps (ex-reports):  78%|███████▊  | 5526/7111 [21:02<06:28,  4.08it/s]

Gaps (ex-reports):  78%|███████▊  | 5527/7111 [21:03<06:53,  3.83it/s]

Gaps (ex-reports):  78%|███████▊  | 5528/7111 [21:04<10:54,  2.42it/s]

Gaps (ex-reports):  78%|███████▊  | 5529/7111 [21:04<09:24,  2.80it/s]

Gaps (ex-reports):  78%|███████▊  | 5530/7111 [21:04<08:10,  3.22it/s]

Gaps (ex-reports):  78%|███████▊  | 5531/7111 [21:04<07:18,  3.61it/s]

Gaps (ex-reports):  78%|███████▊  | 5532/7111 [21:04<06:41,  3.94it/s]

Gaps (ex-reports):  78%|███████▊  | 5533/7111 [21:05<06:21,  4.14it/s]

Gaps (ex-reports):  78%|███████▊  | 5534/7111 [21:05<06:02,  4.35it/s]

Gaps (ex-reports):  78%|███████▊  | 5535/7111 [21:05<05:53,  4.46it/s]

Gaps (ex-reports):  78%|███████▊  | 5536/7111 [21:05<05:42,  4.60it/s]

Gaps (ex-reports):  78%|███████▊  | 5537/7111 [21:05<05:39,  4.63it/s]

Gaps (ex-reports):  78%|███████▊  | 5538/7111 [21:06<05:38,  4.65it/s]

Gaps (ex-reports):  78%|███████▊  | 5539/7111 [21:06<05:54,  4.43it/s]

Gaps (ex-reports):  78%|███████▊  | 5540/7111 [21:06<05:46,  4.54it/s]

Gaps (ex-reports):  78%|███████▊  | 5541/7111 [21:06<05:39,  4.63it/s]

Gaps (ex-reports):  78%|███████▊  | 5542/7111 [21:06<05:40,  4.61it/s]

Gaps (ex-reports):  78%|███████▊  | 5543/7111 [21:07<05:34,  4.68it/s]

Gaps (ex-reports):  78%|███████▊  | 5544/7111 [21:07<05:30,  4.74it/s]

Gaps (ex-reports):  78%|███████▊  | 5545/7111 [21:07<05:26,  4.80it/s]

Gaps (ex-reports):  78%|███████▊  | 5546/7111 [21:07<05:19,  4.89it/s]

Gaps (ex-reports):  78%|███████▊  | 5547/7111 [21:08<05:24,  4.82it/s]

Gaps (ex-reports):  78%|███████▊  | 5548/7111 [21:08<05:19,  4.89it/s]

Gaps (ex-reports):  78%|███████▊  | 5549/7111 [21:08<05:18,  4.90it/s]

Gaps (ex-reports):  78%|███████▊  | 5550/7111 [21:08<05:18,  4.90it/s]

Gaps (ex-reports):  78%|███████▊  | 5551/7111 [21:08<05:19,  4.88it/s]

Gaps (ex-reports):  78%|███████▊  | 5552/7111 [21:09<05:25,  4.79it/s]

Gaps (ex-reports):  78%|███████▊  | 5553/7111 [21:09<05:19,  4.88it/s]

Gaps (ex-reports):  78%|███████▊  | 5554/7111 [21:09<05:19,  4.88it/s]

Gaps (ex-reports):  78%|███████▊  | 5555/7111 [21:09<05:12,  4.97it/s]

Gaps (ex-reports):  78%|███████▊  | 5556/7111 [21:09<05:16,  4.92it/s]

Gaps (ex-reports):  78%|███████▊  | 5557/7111 [21:10<05:25,  4.77it/s]

Gaps (ex-reports):  78%|███████▊  | 5558/7111 [21:10<05:26,  4.75it/s]

Gaps (ex-reports):  78%|███████▊  | 5559/7111 [21:10<07:58,  3.24it/s]

Gaps (ex-reports):  78%|███████▊  | 5560/7111 [21:11<07:05,  3.65it/s]

Gaps (ex-reports):  78%|███████▊  | 5561/7111 [21:11<06:34,  3.93it/s]

Gaps (ex-reports):  78%|███████▊  | 5562/7111 [21:11<06:14,  4.14it/s]

Gaps (ex-reports):  78%|███████▊  | 5563/7111 [21:11<05:57,  4.33it/s]

Gaps (ex-reports):  78%|███████▊  | 5564/7111 [21:11<05:47,  4.46it/s]

Gaps (ex-reports):  78%|███████▊  | 5565/7111 [21:12<05:46,  4.46it/s]

Gaps (ex-reports):  78%|███████▊  | 5566/7111 [21:12<05:40,  4.53it/s]

Gaps (ex-reports):  78%|███████▊  | 5567/7111 [21:12<05:41,  4.53it/s]

Gaps (ex-reports):  78%|███████▊  | 5568/7111 [21:12<05:35,  4.60it/s]

Gaps (ex-reports):  78%|███████▊  | 5569/7111 [21:12<05:28,  4.69it/s]

Gaps (ex-reports):  78%|███████▊  | 5570/7111 [21:13<05:32,  4.63it/s]

Gaps (ex-reports):  78%|███████▊  | 5571/7111 [21:13<05:34,  4.60it/s]

Gaps (ex-reports):  78%|███████▊  | 5572/7111 [21:13<05:24,  4.74it/s]

Gaps (ex-reports):  78%|███████▊  | 5573/7111 [21:13<05:24,  4.74it/s]

Gaps (ex-reports):  78%|███████▊  | 5574/7111 [21:13<05:18,  4.82it/s]

Gaps (ex-reports):  78%|███████▊  | 5575/7111 [21:14<05:25,  4.71it/s]

Gaps (ex-reports):  78%|███████▊  | 5576/7111 [21:14<05:16,  4.85it/s]

Gaps (ex-reports):  78%|███████▊  | 5577/7111 [21:14<05:16,  4.84it/s]

Gaps (ex-reports):  78%|███████▊  | 5578/7111 [21:14<05:11,  4.92it/s]

Gaps (ex-reports):  78%|███████▊  | 5579/7111 [21:14<05:14,  4.87it/s]

Gaps (ex-reports):  78%|███████▊  | 5580/7111 [21:15<05:14,  4.87it/s]

Gaps (ex-reports):  78%|███████▊  | 5581/7111 [21:15<05:19,  4.79it/s]

Gaps (ex-reports):  78%|███████▊  | 5582/7111 [21:15<05:17,  4.81it/s]

Gaps (ex-reports):  79%|███████▊  | 5583/7111 [21:15<05:14,  4.87it/s]

Gaps (ex-reports):  79%|███████▊  | 5584/7111 [21:16<05:07,  4.96it/s]

Gaps (ex-reports):  79%|███████▊  | 5585/7111 [21:16<05:09,  4.93it/s]

Gaps (ex-reports):  79%|███████▊  | 5586/7111 [21:16<05:08,  4.94it/s]

Gaps (ex-reports):  79%|███████▊  | 5587/7111 [21:16<05:12,  4.88it/s]

Gaps (ex-reports):  79%|███████▊  | 5588/7111 [21:16<05:49,  4.36it/s]

Gaps (ex-reports):  79%|███████▊  | 5589/7111 [21:17<05:38,  4.50it/s]

Gaps (ex-reports):  79%|███████▊  | 5590/7111 [21:17<05:25,  4.68it/s]

Gaps (ex-reports):  79%|███████▊  | 5591/7111 [21:17<05:15,  4.82it/s]

Gaps (ex-reports):  79%|███████▊  | 5592/7111 [21:17<05:55,  4.27it/s]

Gaps (ex-reports):  79%|███████▊  | 5593/7111 [21:18<05:41,  4.44it/s]

Gaps (ex-reports):  79%|███████▊  | 5594/7111 [21:18<05:27,  4.63it/s]

Gaps (ex-reports):  79%|███████▊  | 5595/7111 [21:18<05:19,  4.74it/s]

Gaps (ex-reports):  79%|███████▊  | 5596/7111 [21:18<05:17,  4.77it/s]

Gaps (ex-reports):  79%|███████▊  | 5597/7111 [21:18<05:17,  4.77it/s]

Gaps (ex-reports):  79%|███████▊  | 5598/7111 [21:19<06:12,  4.06it/s]

Gaps (ex-reports):  79%|███████▊  | 5599/7111 [21:19<05:47,  4.36it/s]

Gaps (ex-reports):  79%|███████▉  | 5600/7111 [21:19<05:32,  4.54it/s]

Gaps (ex-reports):  79%|███████▉  | 5601/7111 [21:19<05:24,  4.65it/s]

Gaps (ex-reports):  79%|███████▉  | 5602/7111 [21:19<05:20,  4.71it/s]

Gaps (ex-reports):  79%|███████▉  | 5603/7111 [21:20<05:58,  4.21it/s]

Gaps (ex-reports):  79%|███████▉  | 5604/7111 [21:20<07:25,  3.38it/s]

Gaps (ex-reports):  79%|███████▉  | 5605/7111 [21:20<06:55,  3.62it/s]

Gaps (ex-reports):  79%|███████▉  | 5606/7111 [21:21<06:28,  3.88it/s]

Gaps (ex-reports):  79%|███████▉  | 5607/7111 [21:21<06:08,  4.08it/s]

Gaps (ex-reports):  79%|███████▉  | 5608/7111 [21:21<05:48,  4.32it/s]

Gaps (ex-reports):  79%|███████▉  | 5609/7111 [21:21<05:38,  4.44it/s]

Gaps (ex-reports):  79%|███████▉  | 5610/7111 [21:21<05:26,  4.59it/s]

Gaps (ex-reports):  79%|███████▉  | 5611/7111 [21:22<05:27,  4.58it/s]

Gaps (ex-reports):  79%|███████▉  | 5612/7111 [21:22<05:40,  4.40it/s]

Gaps (ex-reports):  79%|███████▉  | 5613/7111 [21:22<05:31,  4.52it/s]

Gaps (ex-reports):  79%|███████▉  | 5614/7111 [21:22<05:21,  4.66it/s]

Gaps (ex-reports):  79%|███████▉  | 5615/7111 [21:23<05:11,  4.81it/s]

Gaps (ex-reports):  79%|███████▉  | 5616/7111 [21:23<05:16,  4.72it/s]

Gaps (ex-reports):  79%|███████▉  | 5617/7111 [21:23<05:11,  4.79it/s]

Gaps (ex-reports):  79%|███████▉  | 5618/7111 [21:23<05:14,  4.75it/s]

Gaps (ex-reports):  79%|███████▉  | 5619/7111 [21:23<05:14,  4.74it/s]

Gaps (ex-reports):  79%|███████▉  | 5620/7111 [21:24<05:07,  4.85it/s]

Gaps (ex-reports):  79%|███████▉  | 5621/7111 [21:24<05:01,  4.94it/s]

Gaps (ex-reports):  79%|███████▉  | 5622/7111 [21:24<05:07,  4.84it/s]

Gaps (ex-reports):  79%|███████▉  | 5623/7111 [21:24<05:08,  4.82it/s]

Gaps (ex-reports):  79%|███████▉  | 5624/7111 [21:24<05:05,  4.87it/s]

Gaps (ex-reports):  79%|███████▉  | 5625/7111 [21:25<05:05,  4.87it/s]

Gaps (ex-reports):  79%|███████▉  | 5626/7111 [21:25<05:13,  4.74it/s]

Gaps (ex-reports):  79%|███████▉  | 5627/7111 [21:25<05:07,  4.83it/s]

Gaps (ex-reports):  79%|███████▉  | 5628/7111 [21:25<05:07,  4.83it/s]

Gaps (ex-reports):  79%|███████▉  | 5629/7111 [21:25<05:07,  4.82it/s]

Gaps (ex-reports):  79%|███████▉  | 5630/7111 [21:26<05:18,  4.65it/s]

Gaps (ex-reports):  79%|███████▉  | 5631/7111 [21:26<05:11,  4.76it/s]

Gaps (ex-reports):  79%|███████▉  | 5632/7111 [21:26<05:07,  4.81it/s]

Gaps (ex-reports):  79%|███████▉  | 5633/7111 [21:26<05:02,  4.88it/s]

Gaps (ex-reports):  79%|███████▉  | 5634/7111 [21:26<05:02,  4.89it/s]

Gaps (ex-reports):  79%|███████▉  | 5635/7111 [21:27<05:06,  4.82it/s]

Gaps (ex-reports):  79%|███████▉  | 5636/7111 [21:27<05:04,  4.85it/s]

Gaps (ex-reports):  79%|███████▉  | 5637/7111 [21:27<05:05,  4.82it/s]

Gaps (ex-reports):  79%|███████▉  | 5638/7111 [21:27<05:09,  4.77it/s]

Gaps (ex-reports):  79%|███████▉  | 5639/7111 [21:28<05:10,  4.75it/s]

Gaps (ex-reports):  79%|███████▉  | 5640/7111 [21:28<05:07,  4.79it/s]

Gaps (ex-reports):  79%|███████▉  | 5641/7111 [21:28<05:12,  4.71it/s]

Gaps (ex-reports):  79%|███████▉  | 5642/7111 [21:28<05:11,  4.72it/s]

Gaps (ex-reports):  79%|███████▉  | 5643/7111 [21:28<05:06,  4.79it/s]

Gaps (ex-reports):  79%|███████▉  | 5644/7111 [21:29<05:04,  4.81it/s]

Gaps (ex-reports):  79%|███████▉  | 5645/7111 [21:29<05:08,  4.75it/s]

Gaps (ex-reports):  79%|███████▉  | 5646/7111 [21:29<05:23,  4.52it/s]

Gaps (ex-reports):  79%|███████▉  | 5647/7111 [21:29<05:17,  4.61it/s]

Gaps (ex-reports):  79%|███████▉  | 5648/7111 [21:29<05:14,  4.66it/s]

Gaps (ex-reports):  79%|███████▉  | 5649/7111 [21:30<05:13,  4.66it/s]

Gaps (ex-reports):  79%|███████▉  | 5650/7111 [21:30<05:15,  4.63it/s]

Gaps (ex-reports):  79%|███████▉  | 5651/7111 [21:30<05:07,  4.75it/s]

Gaps (ex-reports):  79%|███████▉  | 5652/7111 [21:30<05:03,  4.80it/s]

Gaps (ex-reports):  79%|███████▉  | 5653/7111 [21:30<05:03,  4.80it/s]

Gaps (ex-reports):  80%|███████▉  | 5654/7111 [21:31<04:53,  4.96it/s]

Gaps (ex-reports):  80%|███████▉  | 5655/7111 [21:31<04:57,  4.90it/s]

Gaps (ex-reports):  80%|███████▉  | 5656/7111 [21:31<04:51,  4.98it/s]

Gaps (ex-reports):  80%|███████▉  | 5657/7111 [21:31<04:55,  4.92it/s]

Gaps (ex-reports):  80%|███████▉  | 5658/7111 [21:31<04:52,  4.97it/s]

Gaps (ex-reports):  80%|███████▉  | 5659/7111 [21:32<04:52,  4.96it/s]

Gaps (ex-reports):  80%|███████▉  | 5660/7111 [21:32<04:54,  4.93it/s]

Gaps (ex-reports):  80%|███████▉  | 5661/7111 [21:32<04:50,  4.99it/s]

Gaps (ex-reports):  80%|███████▉  | 5662/7111 [21:32<04:49,  5.01it/s]

Gaps (ex-reports):  80%|███████▉  | 5663/7111 [21:32<04:56,  4.89it/s]

Gaps (ex-reports):  80%|███████▉  | 5664/7111 [21:33<04:52,  4.94it/s]

Gaps (ex-reports):  80%|███████▉  | 5665/7111 [21:33<04:55,  4.89it/s]

Gaps (ex-reports):  80%|███████▉  | 5666/7111 [21:33<05:00,  4.82it/s]

Gaps (ex-reports):  80%|███████▉  | 5667/7111 [21:33<05:10,  4.65it/s]

Gaps (ex-reports):  80%|███████▉  | 5668/7111 [21:34<05:10,  4.65it/s]

Gaps (ex-reports):  80%|███████▉  | 5669/7111 [21:34<05:02,  4.77it/s]

Gaps (ex-reports):  80%|███████▉  | 5670/7111 [21:34<04:58,  4.82it/s]

Gaps (ex-reports):  80%|███████▉  | 5671/7111 [21:34<04:55,  4.87it/s]

Gaps (ex-reports):  80%|███████▉  | 5672/7111 [21:34<04:53,  4.91it/s]

Gaps (ex-reports):  80%|███████▉  | 5673/7111 [21:35<05:01,  4.77it/s]

Gaps (ex-reports):  80%|███████▉  | 5674/7111 [21:35<04:59,  4.80it/s]

Gaps (ex-reports):  80%|███████▉  | 5675/7111 [21:35<04:50,  4.94it/s]

Gaps (ex-reports):  80%|███████▉  | 5676/7111 [21:35<04:55,  4.86it/s]

Gaps (ex-reports):  80%|███████▉  | 5677/7111 [21:35<04:53,  4.89it/s]

Gaps (ex-reports):  80%|███████▉  | 5678/7111 [21:36<04:55,  4.84it/s]

Gaps (ex-reports):  80%|███████▉  | 5679/7111 [21:36<04:57,  4.81it/s]

Gaps (ex-reports):  80%|███████▉  | 5680/7111 [21:36<04:57,  4.81it/s]

Gaps (ex-reports):  80%|███████▉  | 5681/7111 [21:36<04:55,  4.84it/s]

Gaps (ex-reports):  80%|███████▉  | 5682/7111 [21:36<04:54,  4.86it/s]

Gaps (ex-reports):  80%|███████▉  | 5683/7111 [21:37<04:52,  4.88it/s]

Gaps (ex-reports):  80%|███████▉  | 5684/7111 [21:37<04:50,  4.91it/s]

Gaps (ex-reports):  80%|███████▉  | 5685/7111 [21:38<08:17,  2.87it/s]

Gaps (ex-reports):  80%|███████▉  | 5686/7111 [21:38<07:10,  3.31it/s]

Gaps (ex-reports):  80%|███████▉  | 5687/7111 [21:38<06:25,  3.70it/s]

Gaps (ex-reports):  80%|███████▉  | 5688/7111 [21:38<05:59,  3.95it/s]

Gaps (ex-reports):  80%|████████  | 5689/7111 [21:38<05:41,  4.16it/s]

Gaps (ex-reports):  80%|████████  | 5690/7111 [21:39<05:24,  4.38it/s]

Gaps (ex-reports):  80%|████████  | 5691/7111 [21:39<05:08,  4.60it/s]

Gaps (ex-reports):  80%|████████  | 5692/7111 [21:39<04:58,  4.75it/s]

Gaps (ex-reports):  80%|████████  | 5693/7111 [21:39<04:56,  4.78it/s]

Gaps (ex-reports):  80%|████████  | 5694/7111 [21:39<04:48,  4.91it/s]

Gaps (ex-reports):  80%|████████  | 5695/7111 [21:40<04:53,  4.82it/s]

Gaps (ex-reports):  80%|████████  | 5696/7111 [21:40<04:52,  4.83it/s]

Gaps (ex-reports):  80%|████████  | 5697/7111 [21:40<04:52,  4.84it/s]

Gaps (ex-reports):  80%|████████  | 5698/7111 [21:40<04:49,  4.88it/s]

Gaps (ex-reports):  80%|████████  | 5699/7111 [21:40<04:47,  4.91it/s]

Gaps (ex-reports):  80%|████████  | 5700/7111 [21:41<04:42,  4.99it/s]

Gaps (ex-reports):  80%|████████  | 5701/7111 [21:41<04:39,  5.05it/s]

Gaps (ex-reports):  80%|████████  | 5702/7111 [21:41<04:42,  4.99it/s]

Gaps (ex-reports):  80%|████████  | 5703/7111 [21:41<04:39,  5.03it/s]

Gaps (ex-reports):  80%|████████  | 5704/7111 [21:41<04:48,  4.88it/s]

Gaps (ex-reports):  80%|████████  | 5705/7111 [21:42<04:42,  4.98it/s]

Gaps (ex-reports):  80%|████████  | 5706/7111 [21:42<04:40,  5.01it/s]

Gaps (ex-reports):  80%|████████  | 5707/7111 [21:42<04:44,  4.93it/s]

Gaps (ex-reports):  80%|████████  | 5708/7111 [21:42<04:46,  4.90it/s]

Gaps (ex-reports):  80%|████████  | 5709/7111 [21:42<04:48,  4.86it/s]

Gaps (ex-reports):  80%|████████  | 5710/7111 [21:43<04:39,  5.00it/s]

Gaps (ex-reports):  80%|████████  | 5711/7111 [21:43<04:38,  5.02it/s]

Gaps (ex-reports):  80%|████████  | 5712/7111 [21:43<04:40,  4.99it/s]

Gaps (ex-reports):  80%|████████  | 5713/7111 [21:43<04:39,  5.01it/s]

Gaps (ex-reports):  80%|████████  | 5714/7111 [21:43<04:42,  4.95it/s]

Gaps (ex-reports):  80%|████████  | 5715/7111 [21:44<04:43,  4.92it/s]

Gaps (ex-reports):  80%|████████  | 5716/7111 [21:44<04:45,  4.88it/s]

Gaps (ex-reports):  80%|████████  | 5717/7111 [21:44<04:49,  4.82it/s]

Gaps (ex-reports):  80%|████████  | 5718/7111 [21:44<04:43,  4.91it/s]

Gaps (ex-reports):  80%|████████  | 5719/7111 [21:44<04:50,  4.78it/s]

Gaps (ex-reports):  80%|████████  | 5720/7111 [21:45<04:48,  4.82it/s]

Gaps (ex-reports):  80%|████████  | 5721/7111 [21:45<04:43,  4.90it/s]

Gaps (ex-reports):  80%|████████  | 5722/7111 [21:45<04:45,  4.87it/s]

Gaps (ex-reports):  80%|████████  | 5723/7111 [21:45<04:49,  4.80it/s]

Gaps (ex-reports):  80%|████████  | 5724/7111 [21:45<04:47,  4.83it/s]

Gaps (ex-reports):  81%|████████  | 5725/7111 [21:46<04:50,  4.77it/s]

Gaps (ex-reports):  81%|████████  | 5726/7111 [21:46<04:46,  4.83it/s]

Gaps (ex-reports):  81%|████████  | 5727/7111 [21:46<04:44,  4.87it/s]

Gaps (ex-reports):  81%|████████  | 5728/7111 [21:46<04:43,  4.88it/s]

Gaps (ex-reports):  81%|████████  | 5729/7111 [21:46<04:41,  4.91it/s]

Gaps (ex-reports):  81%|████████  | 5730/7111 [21:47<04:37,  4.98it/s]

Gaps (ex-reports):  81%|████████  | 5731/7111 [21:47<04:41,  4.91it/s]

Gaps (ex-reports):  81%|████████  | 5732/7111 [21:47<04:38,  4.95it/s]

Gaps (ex-reports):  81%|████████  | 5733/7111 [21:47<04:37,  4.97it/s]

Gaps (ex-reports):  81%|████████  | 5734/7111 [21:47<04:39,  4.93it/s]

Gaps (ex-reports):  81%|████████  | 5735/7111 [21:48<04:37,  4.96it/s]

Gaps (ex-reports):  81%|████████  | 5736/7111 [21:48<04:40,  4.91it/s]

Gaps (ex-reports):  81%|████████  | 5737/7111 [21:48<04:47,  4.79it/s]

Gaps (ex-reports):  81%|████████  | 5738/7111 [21:48<04:53,  4.68it/s]

Gaps (ex-reports):  81%|████████  | 5739/7111 [21:49<04:49,  4.73it/s]

Gaps (ex-reports):  81%|████████  | 5740/7111 [21:49<04:49,  4.74it/s]

Gaps (ex-reports):  81%|████████  | 5741/7111 [21:49<04:47,  4.76it/s]

Gaps (ex-reports):  81%|████████  | 5742/7111 [21:49<04:48,  4.75it/s]

Gaps (ex-reports):  81%|████████  | 5743/7111 [21:49<04:46,  4.77it/s]

Gaps (ex-reports):  81%|████████  | 5744/7111 [21:50<04:47,  4.75it/s]

Gaps (ex-reports):  81%|████████  | 5745/7111 [21:50<04:40,  4.87it/s]

Gaps (ex-reports):  81%|████████  | 5746/7111 [21:50<04:35,  4.95it/s]

Gaps (ex-reports):  81%|████████  | 5747/7111 [21:50<04:33,  4.99it/s]

Gaps (ex-reports):  81%|████████  | 5748/7111 [21:50<04:33,  4.98it/s]

Gaps (ex-reports):  81%|████████  | 5749/7111 [21:51<04:29,  5.05it/s]

Gaps (ex-reports):  81%|████████  | 5750/7111 [21:51<04:29,  5.06it/s]

Gaps (ex-reports):  81%|████████  | 5751/7111 [21:52<11:08,  2.03it/s]

Gaps (ex-reports):  81%|████████  | 5752/7111 [21:52<09:08,  2.48it/s]

Gaps (ex-reports):  81%|████████  | 5753/7111 [21:53<10:54,  2.07it/s]

Gaps (ex-reports):  81%|████████  | 5754/7111 [21:53<09:00,  2.51it/s]

Gaps (ex-reports):  81%|████████  | 5755/7111 [21:53<07:41,  2.94it/s]

Gaps (ex-reports):  81%|████████  | 5756/7111 [21:53<06:47,  3.33it/s]

Gaps (ex-reports):  81%|████████  | 5757/7111 [21:54<06:08,  3.68it/s]

Gaps (ex-reports):  81%|████████  | 5758/7111 [21:54<05:33,  4.06it/s]

Gaps (ex-reports):  81%|████████  | 5759/7111 [21:54<05:15,  4.28it/s]

Gaps (ex-reports):  81%|████████  | 5760/7111 [21:54<05:02,  4.46it/s]

Gaps (ex-reports):  81%|████████  | 5761/7111 [21:54<04:56,  4.55it/s]

Gaps (ex-reports):  81%|████████  | 5762/7111 [21:55<04:54,  4.58it/s]

Gaps (ex-reports):  81%|████████  | 5763/7111 [21:55<04:43,  4.76it/s]

Gaps (ex-reports):  81%|████████  | 5764/7111 [21:55<04:41,  4.78it/s]

Gaps (ex-reports):  81%|████████  | 5765/7111 [21:55<04:41,  4.78it/s]

Gaps (ex-reports):  81%|████████  | 5766/7111 [21:56<05:26,  4.12it/s]

Gaps (ex-reports):  81%|████████  | 5767/7111 [21:56<05:10,  4.33it/s]

Gaps (ex-reports):  81%|████████  | 5768/7111 [21:56<04:59,  4.48it/s]

Gaps (ex-reports):  81%|████████  | 5769/7111 [21:56<04:51,  4.61it/s]

Gaps (ex-reports):  81%|████████  | 5770/7111 [21:56<04:44,  4.71it/s]

Gaps (ex-reports):  81%|████████  | 5771/7111 [21:57<04:42,  4.75it/s]

Gaps (ex-reports):  81%|████████  | 5772/7111 [21:57<04:42,  4.74it/s]

Gaps (ex-reports):  81%|████████  | 5773/7111 [21:57<04:38,  4.80it/s]

Gaps (ex-reports):  81%|████████  | 5774/7111 [21:57<04:40,  4.77it/s]

Gaps (ex-reports):  81%|████████  | 5775/7111 [21:57<04:35,  4.84it/s]

Gaps (ex-reports):  81%|████████  | 5776/7111 [21:58<04:32,  4.90it/s]

Gaps (ex-reports):  81%|████████  | 5777/7111 [21:58<04:33,  4.88it/s]

Gaps (ex-reports):  81%|████████▏ | 5778/7111 [21:58<04:33,  4.87it/s]

Gaps (ex-reports):  81%|████████▏ | 5779/7111 [21:58<04:33,  4.88it/s]

Gaps (ex-reports):  81%|████████▏ | 5780/7111 [21:58<04:36,  4.82it/s]

Gaps (ex-reports):  81%|████████▏ | 5781/7111 [21:59<04:42,  4.70it/s]

Gaps (ex-reports):  81%|████████▏ | 5782/7111 [21:59<04:45,  4.66it/s]

Gaps (ex-reports):  81%|████████▏ | 5783/7111 [21:59<04:41,  4.71it/s]

Gaps (ex-reports):  81%|████████▏ | 5784/7111 [21:59<04:36,  4.79it/s]

Gaps (ex-reports):  81%|████████▏ | 5785/7111 [21:59<04:31,  4.88it/s]

Gaps (ex-reports):  81%|████████▏ | 5786/7111 [22:00<04:31,  4.88it/s]

Gaps (ex-reports):  81%|████████▏ | 5787/7111 [22:00<04:34,  4.83it/s]

Gaps (ex-reports):  81%|████████▏ | 5788/7111 [22:00<04:43,  4.67it/s]

Gaps (ex-reports):  81%|████████▏ | 5789/7111 [22:00<04:46,  4.62it/s]

Gaps (ex-reports):  81%|████████▏ | 5790/7111 [22:01<04:39,  4.72it/s]

Gaps (ex-reports):  81%|████████▏ | 5791/7111 [22:01<04:42,  4.67it/s]

Gaps (ex-reports):  81%|████████▏ | 5792/7111 [22:01<04:42,  4.66it/s]

Gaps (ex-reports):  81%|████████▏ | 5793/7111 [22:01<04:37,  4.75it/s]

Gaps (ex-reports):  81%|████████▏ | 5794/7111 [22:01<04:30,  4.87it/s]

Gaps (ex-reports):  81%|████████▏ | 5795/7111 [22:02<04:47,  4.57it/s]

Gaps (ex-reports):  82%|████████▏ | 5796/7111 [22:02<04:38,  4.72it/s]

Gaps (ex-reports):  82%|████████▏ | 5797/7111 [22:02<04:34,  4.79it/s]

Gaps (ex-reports):  82%|████████▏ | 5798/7111 [22:02<04:31,  4.84it/s]

Gaps (ex-reports):  82%|████████▏ | 5799/7111 [22:02<04:34,  4.79it/s]

Gaps (ex-reports):  82%|████████▏ | 5800/7111 [22:03<04:33,  4.80it/s]

Gaps (ex-reports):  82%|████████▏ | 5801/7111 [22:03<04:27,  4.89it/s]

Gaps (ex-reports):  82%|████████▏ | 5802/7111 [22:03<04:23,  4.97it/s]

Gaps (ex-reports):  82%|████████▏ | 5803/7111 [22:03<04:20,  5.02it/s]

Gaps (ex-reports):  82%|████████▏ | 5804/7111 [22:03<04:22,  4.98it/s]

Gaps (ex-reports):  82%|████████▏ | 5805/7111 [22:04<04:29,  4.85it/s]

Gaps (ex-reports):  82%|████████▏ | 5806/7111 [22:04<04:32,  4.79it/s]

Gaps (ex-reports):  82%|████████▏ | 5807/7111 [22:04<04:25,  4.90it/s]

Gaps (ex-reports):  82%|████████▏ | 5808/7111 [22:04<04:23,  4.95it/s]

Gaps (ex-reports):  82%|████████▏ | 5809/7111 [22:04<04:26,  4.89it/s]

Gaps (ex-reports):  82%|████████▏ | 5810/7111 [22:05<04:24,  4.92it/s]

Gaps (ex-reports):  82%|████████▏ | 5811/7111 [22:05<04:23,  4.94it/s]

Gaps (ex-reports):  82%|████████▏ | 5812/7111 [22:05<04:23,  4.94it/s]

Gaps (ex-reports):  82%|████████▏ | 5813/7111 [22:05<04:22,  4.94it/s]

Gaps (ex-reports):  82%|████████▏ | 5814/7111 [22:05<04:33,  4.75it/s]

Gaps (ex-reports):  82%|████████▏ | 5815/7111 [22:06<04:33,  4.75it/s]

Gaps (ex-reports):  82%|████████▏ | 5816/7111 [22:06<04:26,  4.86it/s]

Gaps (ex-reports):  82%|████████▏ | 5817/7111 [22:06<04:24,  4.89it/s]

Gaps (ex-reports):  82%|████████▏ | 5818/7111 [22:06<04:26,  4.84it/s]

Gaps (ex-reports):  82%|████████▏ | 5819/7111 [22:07<04:20,  4.96it/s]

Gaps (ex-reports):  82%|████████▏ | 5820/7111 [22:07<04:21,  4.94it/s]

Gaps (ex-reports):  82%|████████▏ | 5821/7111 [22:07<04:18,  5.00it/s]

Gaps (ex-reports):  82%|████████▏ | 5822/7111 [22:07<04:22,  4.90it/s]

Gaps (ex-reports):  82%|████████▏ | 5823/7111 [22:07<04:27,  4.81it/s]

Gaps (ex-reports):  82%|████████▏ | 5824/7111 [22:08<04:23,  4.88it/s]

Gaps (ex-reports):  82%|████████▏ | 5825/7111 [22:08<04:25,  4.85it/s]

Gaps (ex-reports):  82%|████████▏ | 5826/7111 [22:08<04:33,  4.70it/s]

Gaps (ex-reports):  82%|████████▏ | 5827/7111 [22:08<04:26,  4.82it/s]

Gaps (ex-reports):  82%|████████▏ | 5828/7111 [22:08<04:22,  4.89it/s]

Gaps (ex-reports):  82%|████████▏ | 5829/7111 [22:09<04:23,  4.87it/s]

Gaps (ex-reports):  82%|████████▏ | 5830/7111 [22:09<04:24,  4.84it/s]

Gaps (ex-reports):  82%|████████▏ | 5831/7111 [22:09<04:24,  4.84it/s]

Gaps (ex-reports):  82%|████████▏ | 5832/7111 [22:09<04:25,  4.82it/s]

Gaps (ex-reports):  82%|████████▏ | 5833/7111 [22:09<04:24,  4.82it/s]

Gaps (ex-reports):  82%|████████▏ | 5834/7111 [22:10<04:27,  4.78it/s]

Gaps (ex-reports):  82%|████████▏ | 5835/7111 [22:10<04:25,  4.81it/s]

Gaps (ex-reports):  82%|████████▏ | 5836/7111 [22:10<04:22,  4.86it/s]

Gaps (ex-reports):  82%|████████▏ | 5837/7111 [22:10<04:19,  4.92it/s]

Gaps (ex-reports):  82%|████████▏ | 5838/7111 [22:10<04:26,  4.78it/s]

Gaps (ex-reports):  82%|████████▏ | 5839/7111 [22:11<04:27,  4.75it/s]

Gaps (ex-reports):  82%|████████▏ | 5840/7111 [22:11<04:22,  4.84it/s]

Gaps (ex-reports):  82%|████████▏ | 5841/7111 [22:11<04:17,  4.93it/s]

Gaps (ex-reports):  82%|████████▏ | 5842/7111 [22:11<04:12,  5.03it/s]

Gaps (ex-reports):  82%|████████▏ | 5843/7111 [22:11<04:12,  5.03it/s]

Gaps (ex-reports):  82%|████████▏ | 5844/7111 [22:12<04:16,  4.93it/s]

Gaps (ex-reports):  82%|████████▏ | 5845/7111 [22:12<04:15,  4.96it/s]

Gaps (ex-reports):  82%|████████▏ | 5846/7111 [22:12<04:10,  5.04it/s]

Gaps (ex-reports):  82%|████████▏ | 5847/7111 [22:12<04:12,  5.01it/s]

Gaps (ex-reports):  82%|████████▏ | 5848/7111 [22:12<04:11,  5.01it/s]

Gaps (ex-reports):  82%|████████▏ | 5849/7111 [22:13<04:14,  4.96it/s]

Gaps (ex-reports):  82%|████████▏ | 5850/7111 [22:13<04:56,  4.25it/s]

Gaps (ex-reports):  82%|████████▏ | 5851/7111 [22:13<04:40,  4.49it/s]

Gaps (ex-reports):  82%|████████▏ | 5852/7111 [22:13<04:32,  4.62it/s]

Gaps (ex-reports):  82%|████████▏ | 5853/7111 [22:14<04:23,  4.77it/s]

Gaps (ex-reports):  82%|████████▏ | 5854/7111 [22:14<04:25,  4.74it/s]

Gaps (ex-reports):  82%|████████▏ | 5855/7111 [22:14<04:23,  4.77it/s]

Gaps (ex-reports):  82%|████████▏ | 5856/7111 [22:14<04:18,  4.86it/s]

Gaps (ex-reports):  82%|████████▏ | 5857/7111 [22:14<04:11,  4.98it/s]

Gaps (ex-reports):  82%|████████▏ | 5858/7111 [22:15<04:12,  4.97it/s]

Gaps (ex-reports):  82%|████████▏ | 5859/7111 [22:15<04:12,  4.97it/s]

Gaps (ex-reports):  82%|████████▏ | 5860/7111 [22:15<04:13,  4.93it/s]

Gaps (ex-reports):  82%|████████▏ | 5861/7111 [22:15<04:20,  4.79it/s]

Gaps (ex-reports):  82%|████████▏ | 5862/7111 [22:15<04:15,  4.88it/s]

Gaps (ex-reports):  82%|████████▏ | 5863/7111 [22:16<04:11,  4.96it/s]

Gaps (ex-reports):  82%|████████▏ | 5864/7111 [22:16<04:13,  4.91it/s]

Gaps (ex-reports):  82%|████████▏ | 5865/7111 [22:16<04:09,  5.00it/s]

Gaps (ex-reports):  82%|████████▏ | 5866/7111 [22:16<04:12,  4.92it/s]

Gaps (ex-reports):  83%|████████▎ | 5867/7111 [22:16<04:14,  4.89it/s]

Gaps (ex-reports):  83%|████████▎ | 5868/7111 [22:17<04:13,  4.91it/s]

Gaps (ex-reports):  83%|████████▎ | 5869/7111 [22:17<04:11,  4.94it/s]

Gaps (ex-reports):  83%|████████▎ | 5870/7111 [22:17<04:10,  4.95it/s]

Gaps (ex-reports):  83%|████████▎ | 5871/7111 [22:17<04:07,  5.01it/s]

Gaps (ex-reports):  83%|████████▎ | 5872/7111 [22:17<04:06,  5.03it/s]

Gaps (ex-reports):  83%|████████▎ | 5873/7111 [22:18<04:09,  4.97it/s]

Gaps (ex-reports):  83%|████████▎ | 5874/7111 [22:18<04:17,  4.80it/s]

Gaps (ex-reports):  83%|████████▎ | 5875/7111 [22:18<04:20,  4.75it/s]

Gaps (ex-reports):  83%|████████▎ | 5876/7111 [22:18<04:17,  4.80it/s]

Gaps (ex-reports):  83%|████████▎ | 5877/7111 [22:18<04:11,  4.90it/s]

Gaps (ex-reports):  83%|████████▎ | 5878/7111 [22:19<04:08,  4.95it/s]

Gaps (ex-reports):  83%|████████▎ | 5879/7111 [22:19<04:05,  5.02it/s]

Gaps (ex-reports):  83%|████████▎ | 5880/7111 [22:19<04:10,  4.91it/s]

Gaps (ex-reports):  83%|████████▎ | 5881/7111 [22:19<04:11,  4.88it/s]

Gaps (ex-reports):  83%|████████▎ | 5882/7111 [22:19<04:11,  4.88it/s]

Gaps (ex-reports):  83%|████████▎ | 5883/7111 [22:20<05:06,  4.01it/s]

Gaps (ex-reports):  83%|████████▎ | 5884/7111 [22:20<04:44,  4.32it/s]

Gaps (ex-reports):  83%|████████▎ | 5885/7111 [22:20<04:37,  4.42it/s]

Gaps (ex-reports):  83%|████████▎ | 5886/7111 [22:20<04:28,  4.57it/s]

Gaps (ex-reports):  83%|████████▎ | 5887/7111 [22:21<04:30,  4.52it/s]

Gaps (ex-reports):  83%|████████▎ | 5888/7111 [22:21<04:20,  4.69it/s]

Gaps (ex-reports):  83%|████████▎ | 5889/7111 [22:21<04:18,  4.72it/s]

Gaps (ex-reports):  83%|████████▎ | 5890/7111 [22:21<04:21,  4.66it/s]

Gaps (ex-reports):  83%|████████▎ | 5891/7111 [22:21<04:14,  4.80it/s]

Gaps (ex-reports):  83%|████████▎ | 5892/7111 [22:22<04:15,  4.77it/s]

Gaps (ex-reports):  83%|████████▎ | 5893/7111 [22:22<04:13,  4.80it/s]

Gaps (ex-reports):  83%|████████▎ | 5894/7111 [22:22<04:08,  4.90it/s]

Gaps (ex-reports):  83%|████████▎ | 5895/7111 [22:22<04:12,  4.82it/s]

Gaps (ex-reports):  83%|████████▎ | 5896/7111 [22:23<04:53,  4.14it/s]

Gaps (ex-reports):  83%|████████▎ | 5897/7111 [22:23<04:34,  4.42it/s]

Gaps (ex-reports):  83%|████████▎ | 5898/7111 [22:23<04:31,  4.47it/s]

Gaps (ex-reports):  83%|████████▎ | 5899/7111 [22:23<04:26,  4.55it/s]

Gaps (ex-reports):  83%|████████▎ | 5900/7111 [22:23<04:23,  4.60it/s]

Gaps (ex-reports):  83%|████████▎ | 5901/7111 [22:24<04:23,  4.59it/s]

Gaps (ex-reports):  83%|████████▎ | 5902/7111 [22:24<04:16,  4.72it/s]

Gaps (ex-reports):  83%|████████▎ | 5903/7111 [22:24<04:20,  4.64it/s]

Gaps (ex-reports):  83%|████████▎ | 5904/7111 [22:24<04:12,  4.77it/s]

Gaps (ex-reports):  83%|████████▎ | 5905/7111 [22:24<04:14,  4.74it/s]

Gaps (ex-reports):  83%|████████▎ | 5906/7111 [22:25<04:12,  4.77it/s]

Gaps (ex-reports):  83%|████████▎ | 5907/7111 [22:25<04:11,  4.79it/s]

Gaps (ex-reports):  83%|████████▎ | 5908/7111 [22:25<04:13,  4.75it/s]

Gaps (ex-reports):  83%|████████▎ | 5909/7111 [22:25<04:11,  4.78it/s]

Gaps (ex-reports):  83%|████████▎ | 5910/7111 [22:26<04:08,  4.82it/s]

Gaps (ex-reports):  83%|████████▎ | 5911/7111 [22:26<04:10,  4.79it/s]

Gaps (ex-reports):  83%|████████▎ | 5912/7111 [22:26<04:11,  4.77it/s]

Gaps (ex-reports):  83%|████████▎ | 5913/7111 [22:26<04:14,  4.71it/s]

Gaps (ex-reports):  83%|████████▎ | 5914/7111 [22:26<04:13,  4.72it/s]

Gaps (ex-reports):  83%|████████▎ | 5915/7111 [22:27<04:10,  4.78it/s]

Gaps (ex-reports):  83%|████████▎ | 5916/7111 [22:27<04:04,  4.89it/s]

Gaps (ex-reports):  83%|████████▎ | 5917/7111 [22:27<04:07,  4.81it/s]

Gaps (ex-reports):  83%|████████▎ | 5918/7111 [22:27<04:04,  4.87it/s]

Gaps (ex-reports):  83%|████████▎ | 5919/7111 [22:27<04:00,  4.96it/s]

Gaps (ex-reports):  83%|████████▎ | 5920/7111 [22:28<03:56,  5.03it/s]

Gaps (ex-reports):  83%|████████▎ | 5921/7111 [22:28<03:59,  4.97it/s]

Gaps (ex-reports):  83%|████████▎ | 5922/7111 [22:28<04:02,  4.91it/s]

Gaps (ex-reports):  83%|████████▎ | 5923/7111 [22:28<03:58,  4.98it/s]

Gaps (ex-reports):  83%|████████▎ | 5924/7111 [22:28<03:59,  4.95it/s]

Gaps (ex-reports):  83%|████████▎ | 5925/7111 [22:29<03:56,  5.02it/s]

Gaps (ex-reports):  83%|████████▎ | 5926/7111 [22:29<03:53,  5.07it/s]

Gaps (ex-reports):  83%|████████▎ | 5927/7111 [22:29<03:57,  4.98it/s]

Gaps (ex-reports):  83%|████████▎ | 5928/7111 [22:29<04:00,  4.91it/s]

Gaps (ex-reports):  83%|████████▎ | 5929/7111 [22:29<04:05,  4.81it/s]

Gaps (ex-reports):  83%|████████▎ | 5930/7111 [22:30<04:03,  4.86it/s]

Gaps (ex-reports):  83%|████████▎ | 5931/7111 [22:30<04:02,  4.87it/s]

Gaps (ex-reports):  83%|████████▎ | 5932/7111 [22:30<03:57,  4.96it/s]

Gaps (ex-reports):  83%|████████▎ | 5933/7111 [22:30<04:01,  4.87it/s]

Gaps (ex-reports):  83%|████████▎ | 5934/7111 [22:31<04:29,  4.37it/s]

Gaps (ex-reports):  83%|████████▎ | 5935/7111 [22:31<04:25,  4.43it/s]

Gaps (ex-reports):  83%|████████▎ | 5936/7111 [22:31<04:18,  4.55it/s]

Gaps (ex-reports):  83%|████████▎ | 5937/7111 [22:31<04:09,  4.70it/s]

Gaps (ex-reports):  84%|████████▎ | 5938/7111 [22:31<04:04,  4.80it/s]

Gaps (ex-reports):  84%|████████▎ | 5939/7111 [22:32<04:19,  4.51it/s]

Gaps (ex-reports):  84%|████████▎ | 5940/7111 [22:33<09:37,  2.03it/s]

Gaps (ex-reports):  84%|████████▎ | 5941/7111 [22:33<07:54,  2.46it/s]

Gaps (ex-reports):  84%|████████▎ | 5942/7111 [22:33<06:44,  2.89it/s]

Gaps (ex-reports):  84%|████████▎ | 5943/7111 [22:33<05:56,  3.28it/s]

Gaps (ex-reports):  84%|████████▎ | 5944/7111 [22:34<05:20,  3.64it/s]

Gaps (ex-reports):  84%|████████▎ | 5945/7111 [22:34<04:59,  3.90it/s]

Gaps (ex-reports):  84%|████████▎ | 5946/7111 [22:34<04:41,  4.15it/s]

Gaps (ex-reports):  84%|████████▎ | 5947/7111 [22:34<04:30,  4.31it/s]

Gaps (ex-reports):  84%|████████▎ | 5948/7111 [22:34<04:22,  4.44it/s]

Gaps (ex-reports):  84%|████████▎ | 5949/7111 [22:35<04:14,  4.56it/s]

Gaps (ex-reports):  84%|████████▎ | 5950/7111 [22:35<04:09,  4.66it/s]

Gaps (ex-reports):  84%|████████▎ | 5951/7111 [22:35<04:03,  4.76it/s]

Gaps (ex-reports):  84%|████████▎ | 5952/7111 [22:35<04:01,  4.80it/s]

Gaps (ex-reports):  84%|████████▎ | 5953/7111 [22:35<03:59,  4.84it/s]

Gaps (ex-reports):  84%|████████▎ | 5954/7111 [22:36<03:58,  4.85it/s]

Gaps (ex-reports):  84%|████████▎ | 5955/7111 [22:36<03:56,  4.90it/s]

Gaps (ex-reports):  84%|████████▍ | 5956/7111 [22:36<03:51,  4.99it/s]

Gaps (ex-reports):  84%|████████▍ | 5957/7111 [22:36<03:58,  4.85it/s]

Gaps (ex-reports):  84%|████████▍ | 5958/7111 [22:36<03:53,  4.95it/s]

Gaps (ex-reports):  84%|████████▍ | 5959/7111 [22:37<03:55,  4.89it/s]

Gaps (ex-reports):  84%|████████▍ | 5960/7111 [22:37<03:55,  4.88it/s]

Gaps (ex-reports):  84%|████████▍ | 5961/7111 [22:37<03:53,  4.92it/s]

Gaps (ex-reports):  84%|████████▍ | 5962/7111 [22:37<03:54,  4.90it/s]

Gaps (ex-reports):  84%|████████▍ | 5963/7111 [22:37<03:57,  4.83it/s]

Gaps (ex-reports):  84%|████████▍ | 5964/7111 [22:38<03:55,  4.87it/s]

Gaps (ex-reports):  84%|████████▍ | 5965/7111 [22:38<03:57,  4.82it/s]

Gaps (ex-reports):  84%|████████▍ | 5966/7111 [22:38<03:52,  4.91it/s]

Gaps (ex-reports):  84%|████████▍ | 5967/7111 [22:38<03:51,  4.94it/s]

Gaps (ex-reports):  84%|████████▍ | 5968/7111 [22:38<03:48,  4.99it/s]

Gaps (ex-reports):  84%|████████▍ | 5969/7111 [22:39<03:54,  4.87it/s]

Gaps (ex-reports):  84%|████████▍ | 5970/7111 [22:39<03:51,  4.93it/s]

Gaps (ex-reports):  84%|████████▍ | 5971/7111 [22:39<03:48,  5.00it/s]

Gaps (ex-reports):  84%|████████▍ | 5972/7111 [22:39<03:50,  4.93it/s]

Gaps (ex-reports):  84%|████████▍ | 5973/7111 [22:39<03:51,  4.91it/s]

Gaps (ex-reports):  84%|████████▍ | 5974/7111 [22:40<03:54,  4.84it/s]

Gaps (ex-reports):  84%|████████▍ | 5975/7111 [22:40<03:55,  4.82it/s]

Gaps (ex-reports):  84%|████████▍ | 5976/7111 [22:40<03:50,  4.92it/s]

Gaps (ex-reports):  84%|████████▍ | 5977/7111 [22:40<03:50,  4.92it/s]

Gaps (ex-reports):  84%|████████▍ | 5978/7111 [22:40<03:53,  4.86it/s]

Gaps (ex-reports):  84%|████████▍ | 5979/7111 [22:41<04:40,  4.04it/s]

Gaps (ex-reports):  84%|████████▍ | 5980/7111 [22:41<04:22,  4.30it/s]

Gaps (ex-reports):  84%|████████▍ | 5981/7111 [22:41<04:14,  4.44it/s]

Gaps (ex-reports):  84%|████████▍ | 5982/7111 [22:41<04:07,  4.57it/s]

Gaps (ex-reports):  84%|████████▍ | 5983/7111 [22:42<04:02,  4.65it/s]

Gaps (ex-reports):  84%|████████▍ | 5984/7111 [22:42<03:55,  4.78it/s]

Gaps (ex-reports):  84%|████████▍ | 5985/7111 [22:42<03:55,  4.79it/s]

Gaps (ex-reports):  84%|████████▍ | 5986/7111 [22:42<03:50,  4.89it/s]

Gaps (ex-reports):  84%|████████▍ | 5987/7111 [22:42<03:49,  4.89it/s]

Gaps (ex-reports):  84%|████████▍ | 5988/7111 [22:43<04:48,  3.89it/s]

Gaps (ex-reports):  84%|████████▍ | 5989/7111 [22:43<04:27,  4.19it/s]

Gaps (ex-reports):  84%|████████▍ | 5990/7111 [22:43<04:16,  4.37it/s]

Gaps (ex-reports):  84%|████████▍ | 5991/7111 [22:43<04:09,  4.50it/s]

Gaps (ex-reports):  84%|████████▍ | 5992/7111 [22:44<04:02,  4.61it/s]

Gaps (ex-reports):  84%|████████▍ | 5993/7111 [22:44<03:58,  4.69it/s]

Gaps (ex-reports):  84%|████████▍ | 5994/7111 [22:44<04:01,  4.63it/s]

Gaps (ex-reports):  84%|████████▍ | 5995/7111 [22:44<03:59,  4.67it/s]

Gaps (ex-reports):  84%|████████▍ | 5996/7111 [22:44<03:54,  4.76it/s]

Gaps (ex-reports):  84%|████████▍ | 5997/7111 [22:45<03:57,  4.69it/s]

Gaps (ex-reports):  84%|████████▍ | 5998/7111 [22:45<03:53,  4.77it/s]

Gaps (ex-reports):  84%|████████▍ | 5999/7111 [22:45<03:50,  4.83it/s]

Gaps (ex-reports):  84%|████████▍ | 6000/7111 [22:45<03:46,  4.91it/s]

Gaps (ex-reports):  84%|████████▍ | 6001/7111 [22:45<03:44,  4.95it/s]

Gaps (ex-reports):  84%|████████▍ | 6002/7111 [22:46<03:45,  4.91it/s]

Gaps (ex-reports):  84%|████████▍ | 6003/7111 [22:46<03:44,  4.93it/s]

Gaps (ex-reports):  84%|████████▍ | 6004/7111 [22:46<03:49,  4.83it/s]

Gaps (ex-reports):  84%|████████▍ | 6005/7111 [22:46<03:49,  4.82it/s]

Gaps (ex-reports):  84%|████████▍ | 6006/7111 [22:47<03:47,  4.87it/s]

Gaps (ex-reports):  84%|████████▍ | 6007/7111 [22:47<03:46,  4.88it/s]

Gaps (ex-reports):  84%|████████▍ | 6008/7111 [22:47<03:46,  4.88it/s]

Gaps (ex-reports):  85%|████████▍ | 6009/7111 [22:47<03:46,  4.87it/s]

Gaps (ex-reports):  85%|████████▍ | 6010/7111 [22:47<03:45,  4.87it/s]

Gaps (ex-reports):  85%|████████▍ | 6011/7111 [22:48<03:41,  4.96it/s]

Gaps (ex-reports):  85%|████████▍ | 6012/7111 [22:48<03:43,  4.92it/s]

Gaps (ex-reports):  85%|████████▍ | 6013/7111 [22:48<03:41,  4.95it/s]

Gaps (ex-reports):  85%|████████▍ | 6014/7111 [22:48<03:43,  4.91it/s]

Gaps (ex-reports):  85%|████████▍ | 6015/7111 [22:48<03:46,  4.84it/s]

Gaps (ex-reports):  85%|████████▍ | 6016/7111 [22:49<03:44,  4.89it/s]

Gaps (ex-reports):  85%|████████▍ | 6017/7111 [22:49<03:38,  5.00it/s]

Gaps (ex-reports):  85%|████████▍ | 6018/7111 [22:49<03:42,  4.91it/s]

Gaps (ex-reports):  85%|████████▍ | 6019/7111 [22:49<03:47,  4.80it/s]

Gaps (ex-reports):  85%|████████▍ | 6020/7111 [22:49<03:43,  4.89it/s]

Gaps (ex-reports):  85%|████████▍ | 6021/7111 [22:50<03:39,  4.96it/s]

Gaps (ex-reports):  85%|████████▍ | 6022/7111 [22:50<03:36,  5.02it/s]

Gaps (ex-reports):  85%|████████▍ | 6023/7111 [22:50<03:38,  4.99it/s]

Gaps (ex-reports):  85%|████████▍ | 6024/7111 [22:50<03:37,  4.99it/s]

Gaps (ex-reports):  85%|████████▍ | 6025/7111 [22:50<03:39,  4.94it/s]

Gaps (ex-reports):  85%|████████▍ | 6026/7111 [22:51<03:39,  4.95it/s]

Gaps (ex-reports):  85%|████████▍ | 6027/7111 [22:51<03:38,  4.96it/s]

Gaps (ex-reports):  85%|████████▍ | 6028/7111 [22:51<03:37,  4.99it/s]

Gaps (ex-reports):  85%|████████▍ | 6029/7111 [22:51<03:35,  5.01it/s]

Gaps (ex-reports):  85%|████████▍ | 6030/7111 [22:51<03:42,  4.85it/s]

Gaps (ex-reports):  85%|████████▍ | 6031/7111 [22:52<03:38,  4.95it/s]

Gaps (ex-reports):  85%|████████▍ | 6032/7111 [22:52<03:55,  4.59it/s]

Gaps (ex-reports):  85%|████████▍ | 6033/7111 [22:52<03:47,  4.74it/s]

Gaps (ex-reports):  85%|████████▍ | 6034/7111 [22:52<03:46,  4.75it/s]

Gaps (ex-reports):  85%|████████▍ | 6035/7111 [22:52<03:45,  4.77it/s]

Gaps (ex-reports):  85%|████████▍ | 6036/7111 [22:53<03:48,  4.70it/s]

Gaps (ex-reports):  85%|████████▍ | 6037/7111 [22:53<03:48,  4.71it/s]

Gaps (ex-reports):  85%|████████▍ | 6038/7111 [22:53<03:47,  4.72it/s]

Gaps (ex-reports):  85%|████████▍ | 6039/7111 [22:53<03:45,  4.76it/s]

Gaps (ex-reports):  85%|████████▍ | 6040/7111 [22:54<03:51,  4.63it/s]

Gaps (ex-reports):  85%|████████▍ | 6041/7111 [22:54<03:46,  4.72it/s]

Gaps (ex-reports):  85%|████████▍ | 6042/7111 [22:54<03:39,  4.86it/s]

Gaps (ex-reports):  85%|████████▍ | 6043/7111 [22:54<03:35,  4.96it/s]

Gaps (ex-reports):  85%|████████▍ | 6044/7111 [22:54<03:32,  5.03it/s]

Gaps (ex-reports):  85%|████████▌ | 6045/7111 [22:55<03:30,  5.06it/s]

Gaps (ex-reports):  85%|████████▌ | 6046/7111 [22:55<03:33,  4.99it/s]

Gaps (ex-reports):  85%|████████▌ | 6047/7111 [22:55<03:36,  4.92it/s]

Gaps (ex-reports):  85%|████████▌ | 6048/7111 [22:55<03:37,  4.89it/s]

Gaps (ex-reports):  85%|████████▌ | 6049/7111 [22:55<03:36,  4.91it/s]

Gaps (ex-reports):  85%|████████▌ | 6050/7111 [22:56<03:34,  4.95it/s]

Gaps (ex-reports):  85%|████████▌ | 6051/7111 [22:56<03:35,  4.91it/s]

Gaps (ex-reports):  85%|████████▌ | 6052/7111 [22:56<03:32,  4.99it/s]

Gaps (ex-reports):  85%|████████▌ | 6053/7111 [22:56<03:36,  4.88it/s]

Gaps (ex-reports):  85%|████████▌ | 6054/7111 [22:56<03:35,  4.91it/s]

Gaps (ex-reports):  85%|████████▌ | 6055/7111 [22:57<03:35,  4.89it/s]

Gaps (ex-reports):  85%|████████▌ | 6056/7111 [22:57<03:35,  4.90it/s]

Gaps (ex-reports):  85%|████████▌ | 6057/7111 [22:57<03:32,  4.96it/s]

Gaps (ex-reports):  85%|████████▌ | 6058/7111 [22:57<03:32,  4.97it/s]

Gaps (ex-reports):  85%|████████▌ | 6059/7111 [22:57<03:31,  4.96it/s]

Gaps (ex-reports):  85%|████████▌ | 6060/7111 [22:58<03:33,  4.92it/s]

Gaps (ex-reports):  85%|████████▌ | 6061/7111 [22:58<03:31,  4.96it/s]

Gaps (ex-reports):  85%|████████▌ | 6062/7111 [22:58<03:38,  4.79it/s]

Gaps (ex-reports):  85%|████████▌ | 6063/7111 [22:58<03:37,  4.81it/s]

Gaps (ex-reports):  85%|████████▌ | 6064/7111 [22:58<03:37,  4.82it/s]

Gaps (ex-reports):  85%|████████▌ | 6065/7111 [22:59<03:36,  4.82it/s]

Gaps (ex-reports):  85%|████████▌ | 6066/7111 [22:59<03:36,  4.83it/s]

Gaps (ex-reports):  85%|████████▌ | 6067/7111 [22:59<03:36,  4.82it/s]

Gaps (ex-reports):  85%|████████▌ | 6068/7111 [22:59<03:36,  4.82it/s]

Gaps (ex-reports):  85%|████████▌ | 6069/7111 [22:59<03:36,  4.82it/s]

Gaps (ex-reports):  85%|████████▌ | 6070/7111 [23:00<03:42,  4.67it/s]

Gaps (ex-reports):  85%|████████▌ | 6071/7111 [23:00<03:41,  4.70it/s]

Gaps (ex-reports):  85%|████████▌ | 6072/7111 [23:00<03:38,  4.76it/s]

Gaps (ex-reports):  85%|████████▌ | 6073/7111 [23:00<03:36,  4.79it/s]

Gaps (ex-reports):  85%|████████▌ | 6074/7111 [23:01<03:40,  4.71it/s]

Gaps (ex-reports):  85%|████████▌ | 6075/7111 [23:01<03:35,  4.80it/s]

Gaps (ex-reports):  85%|████████▌ | 6076/7111 [23:01<03:29,  4.93it/s]

Gaps (ex-reports):  85%|████████▌ | 6077/7111 [23:01<03:30,  4.91it/s]

Gaps (ex-reports):  85%|████████▌ | 6078/7111 [23:01<03:32,  4.87it/s]

Gaps (ex-reports):  85%|████████▌ | 6079/7111 [23:02<03:32,  4.86it/s]

Gaps (ex-reports):  86%|████████▌ | 6080/7111 [23:02<03:34,  4.81it/s]

Gaps (ex-reports):  86%|████████▌ | 6081/7111 [23:02<03:32,  4.84it/s]

Gaps (ex-reports):  86%|████████▌ | 6082/7111 [23:02<03:30,  4.89it/s]

Gaps (ex-reports):  86%|████████▌ | 6083/7111 [23:02<03:31,  4.86it/s]

Gaps (ex-reports):  86%|████████▌ | 6084/7111 [23:03<03:29,  4.90it/s]

Gaps (ex-reports):  86%|████████▌ | 6085/7111 [23:03<03:32,  4.83it/s]

Gaps (ex-reports):  86%|████████▌ | 6086/7111 [23:03<03:30,  4.86it/s]

Gaps (ex-reports):  86%|████████▌ | 6087/7111 [23:03<03:27,  4.93it/s]

Gaps (ex-reports):  86%|████████▌ | 6088/7111 [23:03<03:27,  4.93it/s]

Gaps (ex-reports):  86%|████████▌ | 6089/7111 [23:04<03:27,  4.92it/s]

Gaps (ex-reports):  86%|████████▌ | 6090/7111 [23:04<03:26,  4.94it/s]

Gaps (ex-reports):  86%|████████▌ | 6091/7111 [23:04<03:27,  4.91it/s]

Gaps (ex-reports):  86%|████████▌ | 6092/7111 [23:04<03:28,  4.89it/s]

Gaps (ex-reports):  86%|████████▌ | 6093/7111 [23:04<03:24,  4.98it/s]

Gaps (ex-reports):  86%|████████▌ | 6094/7111 [23:05<03:25,  4.94it/s]

Gaps (ex-reports):  86%|████████▌ | 6095/7111 [23:05<03:22,  5.01it/s]

Gaps (ex-reports):  86%|████████▌ | 6096/7111 [23:05<03:22,  5.01it/s]

Gaps (ex-reports):  86%|████████▌ | 6097/7111 [23:05<03:23,  4.99it/s]

Gaps (ex-reports):  86%|████████▌ | 6098/7111 [23:05<03:25,  4.93it/s]

Gaps (ex-reports):  86%|████████▌ | 6099/7111 [23:06<03:26,  4.91it/s]

Gaps (ex-reports):  86%|████████▌ | 6100/7111 [23:06<03:26,  4.89it/s]

Gaps (ex-reports):  86%|████████▌ | 6101/7111 [23:06<03:29,  4.82it/s]

Gaps (ex-reports):  86%|████████▌ | 6102/7111 [23:06<03:24,  4.94it/s]

Gaps (ex-reports):  86%|████████▌ | 6103/7111 [23:06<03:20,  5.03it/s]

Gaps (ex-reports):  86%|████████▌ | 6104/7111 [23:07<03:20,  5.02it/s]

Gaps (ex-reports):  86%|████████▌ | 6105/7111 [23:07<03:21,  5.00it/s]

Gaps (ex-reports):  86%|████████▌ | 6106/7111 [23:07<03:22,  4.97it/s]

Gaps (ex-reports):  86%|████████▌ | 6107/7111 [23:07<03:19,  5.02it/s]

Gaps (ex-reports):  86%|████████▌ | 6108/7111 [23:07<03:23,  4.93it/s]

Gaps (ex-reports):  86%|████████▌ | 6109/7111 [23:08<03:25,  4.87it/s]

Gaps (ex-reports):  86%|████████▌ | 6110/7111 [23:08<03:30,  4.76it/s]

Gaps (ex-reports):  86%|████████▌ | 6111/7111 [23:08<03:27,  4.82it/s]

Gaps (ex-reports):  86%|████████▌ | 6112/7111 [23:08<03:26,  4.84it/s]

Gaps (ex-reports):  86%|████████▌ | 6113/7111 [23:08<03:22,  4.92it/s]

Gaps (ex-reports):  86%|████████▌ | 6114/7111 [23:09<03:22,  4.92it/s]

Gaps (ex-reports):  86%|████████▌ | 6115/7111 [23:09<03:22,  4.91it/s]

Gaps (ex-reports):  86%|████████▌ | 6116/7111 [23:09<03:23,  4.89it/s]

Gaps (ex-reports):  86%|████████▌ | 6117/7111 [23:09<03:24,  4.85it/s]

Gaps (ex-reports):  86%|████████▌ | 6118/7111 [23:09<03:25,  4.83it/s]

Gaps (ex-reports):  86%|████████▌ | 6119/7111 [23:10<03:23,  4.87it/s]

Gaps (ex-reports):  86%|████████▌ | 6120/7111 [23:10<03:29,  4.73it/s]

Gaps (ex-reports):  86%|████████▌ | 6121/7111 [23:10<03:25,  4.82it/s]

Gaps (ex-reports):  86%|████████▌ | 6122/7111 [23:10<03:23,  4.86it/s]

Gaps (ex-reports):  86%|████████▌ | 6123/7111 [23:11<07:49,  2.10it/s]

Gaps (ex-reports):  86%|████████▌ | 6124/7111 [23:12<06:31,  2.52it/s]

Gaps (ex-reports):  86%|████████▌ | 6125/7111 [23:12<05:34,  2.95it/s]

Gaps (ex-reports):  86%|████████▌ | 6126/7111 [23:12<04:57,  3.32it/s]

Gaps (ex-reports):  86%|████████▌ | 6127/7111 [23:12<04:27,  3.68it/s]

Gaps (ex-reports):  86%|████████▌ | 6128/7111 [23:12<04:08,  3.96it/s]

Gaps (ex-reports):  86%|████████▌ | 6129/7111 [23:13<03:58,  4.12it/s]

Gaps (ex-reports):  86%|████████▌ | 6130/7111 [23:13<03:48,  4.29it/s]

Gaps (ex-reports):  86%|████████▌ | 6131/7111 [23:13<03:36,  4.53it/s]

Gaps (ex-reports):  86%|████████▌ | 6132/7111 [23:13<03:28,  4.70it/s]

Gaps (ex-reports):  86%|████████▌ | 6133/7111 [23:13<03:20,  4.88it/s]

Gaps (ex-reports):  86%|████████▋ | 6134/7111 [23:14<03:21,  4.86it/s]

Gaps (ex-reports):  86%|████████▋ | 6135/7111 [23:14<03:21,  4.84it/s]

Gaps (ex-reports):  86%|████████▋ | 6136/7111 [23:14<03:23,  4.79it/s]

Gaps (ex-reports):  86%|████████▋ | 6137/7111 [23:14<03:22,  4.80it/s]

Gaps (ex-reports):  86%|████████▋ | 6138/7111 [23:15<03:28,  4.67it/s]

Gaps (ex-reports):  86%|████████▋ | 6139/7111 [23:15<03:26,  4.71it/s]

Gaps (ex-reports):  86%|████████▋ | 6140/7111 [23:15<03:25,  4.72it/s]

Gaps (ex-reports):  86%|████████▋ | 6141/7111 [23:15<03:23,  4.77it/s]

Gaps (ex-reports):  86%|████████▋ | 6142/7111 [23:15<03:22,  4.78it/s]

Gaps (ex-reports):  86%|████████▋ | 6143/7111 [23:16<03:20,  4.82it/s]

Gaps (ex-reports):  86%|████████▋ | 6144/7111 [23:16<03:16,  4.92it/s]

Gaps (ex-reports):  86%|████████▋ | 6145/7111 [23:16<03:16,  4.90it/s]

Gaps (ex-reports):  86%|████████▋ | 6146/7111 [23:16<03:12,  5.01it/s]

Gaps (ex-reports):  86%|████████▋ | 6147/7111 [23:17<07:17,  2.20it/s]

Gaps (ex-reports):  86%|████████▋ | 6148/7111 [23:17<06:03,  2.65it/s]

Gaps (ex-reports):  86%|████████▋ | 6149/7111 [23:18<05:10,  3.10it/s]

Gaps (ex-reports):  86%|████████▋ | 6150/7111 [23:18<04:38,  3.45it/s]

Gaps (ex-reports):  86%|████████▋ | 6151/7111 [23:18<04:14,  3.78it/s]

Gaps (ex-reports):  87%|████████▋ | 6152/7111 [23:18<03:56,  4.05it/s]

Gaps (ex-reports):  87%|████████▋ | 6153/7111 [23:18<03:44,  4.27it/s]

Gaps (ex-reports):  87%|████████▋ | 6154/7111 [23:19<03:36,  4.41it/s]

Gaps (ex-reports):  87%|████████▋ | 6155/7111 [23:19<03:27,  4.61it/s]

Gaps (ex-reports):  87%|████████▋ | 6156/7111 [23:19<03:29,  4.56it/s]

Gaps (ex-reports):  87%|████████▋ | 6157/7111 [23:19<03:29,  4.55it/s]

Gaps (ex-reports):  87%|████████▋ | 6158/7111 [23:19<03:30,  4.53it/s]

Gaps (ex-reports):  87%|████████▋ | 6159/7111 [23:20<03:26,  4.61it/s]

Gaps (ex-reports):  87%|████████▋ | 6160/7111 [23:20<03:24,  4.65it/s]

Gaps (ex-reports):  87%|████████▋ | 6161/7111 [23:20<03:27,  4.58it/s]

Gaps (ex-reports):  87%|████████▋ | 6162/7111 [23:20<03:23,  4.66it/s]

Gaps (ex-reports):  87%|████████▋ | 6163/7111 [23:21<03:17,  4.80it/s]

Gaps (ex-reports):  87%|████████▋ | 6164/7111 [23:21<03:21,  4.71it/s]

Gaps (ex-reports):  87%|████████▋ | 6165/7111 [23:21<03:20,  4.72it/s]

Gaps (ex-reports):  87%|████████▋ | 6166/7111 [23:21<03:13,  4.88it/s]

Gaps (ex-reports):  87%|████████▋ | 6167/7111 [23:21<03:09,  4.98it/s]

Gaps (ex-reports):  87%|████████▋ | 6168/7111 [23:22<03:07,  5.02it/s]

Gaps (ex-reports):  87%|████████▋ | 6169/7111 [23:22<03:12,  4.89it/s]

Gaps (ex-reports):  87%|████████▋ | 6170/7111 [23:22<03:09,  4.97it/s]

Gaps (ex-reports):  87%|████████▋ | 6171/7111 [23:22<03:18,  4.72it/s]

Gaps (ex-reports):  87%|████████▋ | 6172/7111 [23:22<03:15,  4.81it/s]

Gaps (ex-reports):  87%|████████▋ | 6173/7111 [23:23<03:14,  4.81it/s]

Gaps (ex-reports):  87%|████████▋ | 6174/7111 [23:23<03:13,  4.84it/s]

Gaps (ex-reports):  87%|████████▋ | 6175/7111 [23:23<03:14,  4.80it/s]

Gaps (ex-reports):  87%|████████▋ | 6176/7111 [23:23<03:15,  4.77it/s]

Gaps (ex-reports):  87%|████████▋ | 6177/7111 [23:23<03:10,  4.90it/s]

Gaps (ex-reports):  87%|████████▋ | 6178/7111 [23:24<03:08,  4.94it/s]

Gaps (ex-reports):  87%|████████▋ | 6179/7111 [23:24<03:12,  4.83it/s]

Gaps (ex-reports):  87%|████████▋ | 6180/7111 [23:24<03:08,  4.93it/s]

Gaps (ex-reports):  87%|████████▋ | 6181/7111 [23:24<03:09,  4.92it/s]

Gaps (ex-reports):  87%|████████▋ | 6182/7111 [23:24<03:10,  4.87it/s]

Gaps (ex-reports):  87%|████████▋ | 6183/7111 [23:25<06:10,  2.50it/s]

Gaps (ex-reports):  87%|████████▋ | 6184/7111 [23:25<05:15,  2.94it/s]

Gaps (ex-reports):  87%|████████▋ | 6185/7111 [23:26<04:38,  3.33it/s]

Gaps (ex-reports):  87%|████████▋ | 6186/7111 [23:26<04:10,  3.69it/s]

Gaps (ex-reports):  87%|████████▋ | 6187/7111 [23:26<03:57,  3.90it/s]

Gaps (ex-reports):  87%|████████▋ | 6188/7111 [23:26<03:39,  4.20it/s]

Gaps (ex-reports):  87%|████████▋ | 6189/7111 [23:27<03:36,  4.25it/s]

Gaps (ex-reports):  87%|████████▋ | 6190/7111 [23:27<03:32,  4.34it/s]

Gaps (ex-reports):  87%|████████▋ | 6191/7111 [23:27<03:20,  4.58it/s]

Gaps (ex-reports):  87%|████████▋ | 6192/7111 [23:27<03:22,  4.55it/s]

Gaps (ex-reports):  87%|████████▋ | 6193/7111 [23:27<03:15,  4.69it/s]

Gaps (ex-reports):  87%|████████▋ | 6194/7111 [23:28<03:15,  4.68it/s]

Gaps (ex-reports):  87%|████████▋ | 6195/7111 [23:28<03:13,  4.74it/s]

Gaps (ex-reports):  87%|████████▋ | 6196/7111 [23:28<03:11,  4.78it/s]

Gaps (ex-reports):  87%|████████▋ | 6197/7111 [23:28<03:06,  4.89it/s]

Gaps (ex-reports):  87%|████████▋ | 6198/7111 [23:28<03:08,  4.85it/s]

Gaps (ex-reports):  87%|████████▋ | 6199/7111 [23:29<03:08,  4.85it/s]

Gaps (ex-reports):  87%|████████▋ | 6200/7111 [23:29<03:02,  4.98it/s]

Gaps (ex-reports):  87%|████████▋ | 6201/7111 [23:29<03:03,  4.95it/s]

Gaps (ex-reports):  87%|████████▋ | 6202/7111 [23:29<03:00,  5.03it/s]

Gaps (ex-reports):  87%|████████▋ | 6203/7111 [23:29<02:59,  5.07it/s]

Gaps (ex-reports):  87%|████████▋ | 6204/7111 [23:30<03:00,  5.04it/s]

Gaps (ex-reports):  87%|████████▋ | 6205/7111 [23:30<02:58,  5.06it/s]

Gaps (ex-reports):  87%|████████▋ | 6206/7111 [23:30<03:01,  4.99it/s]

Gaps (ex-reports):  87%|████████▋ | 6207/7111 [23:30<03:00,  5.00it/s]

Gaps (ex-reports):  87%|████████▋ | 6208/7111 [23:30<03:02,  4.95it/s]

Gaps (ex-reports):  87%|████████▋ | 6209/7111 [23:31<03:03,  4.92it/s]

Gaps (ex-reports):  87%|████████▋ | 6210/7111 [23:31<03:06,  4.83it/s]

Gaps (ex-reports):  87%|████████▋ | 6211/7111 [23:31<03:02,  4.92it/s]

Gaps (ex-reports):  87%|████████▋ | 6212/7111 [23:31<03:02,  4.92it/s]

Gaps (ex-reports):  87%|████████▋ | 6213/7111 [23:31<03:03,  4.90it/s]

Gaps (ex-reports):  87%|████████▋ | 6214/7111 [23:32<03:08,  4.76it/s]

Gaps (ex-reports):  87%|████████▋ | 6215/7111 [23:32<03:08,  4.75it/s]

Gaps (ex-reports):  87%|████████▋ | 6216/7111 [23:32<03:05,  4.83it/s]

Gaps (ex-reports):  87%|████████▋ | 6217/7111 [23:34<08:57,  1.66it/s]

Gaps (ex-reports):  87%|████████▋ | 6218/7111 [23:34<07:07,  2.09it/s]

Gaps (ex-reports):  87%|████████▋ | 6219/7111 [23:34<05:49,  2.55it/s]

Gaps (ex-reports):  87%|████████▋ | 6220/7111 [23:34<04:58,  2.99it/s]

Gaps (ex-reports):  87%|████████▋ | 6221/7111 [23:35<08:44,  1.70it/s]

Gaps (ex-reports):  87%|████████▋ | 6222/7111 [23:36<07:00,  2.12it/s]

Gaps (ex-reports):  88%|████████▊ | 6223/7111 [23:36<05:49,  2.54it/s]

Gaps (ex-reports):  88%|████████▊ | 6224/7111 [23:36<04:58,  2.97it/s]

Gaps (ex-reports):  88%|████████▊ | 6225/7111 [23:36<04:25,  3.34it/s]

Gaps (ex-reports):  88%|████████▊ | 6226/7111 [23:36<03:56,  3.74it/s]

Gaps (ex-reports):  88%|████████▊ | 6227/7111 [23:37<03:41,  3.99it/s]

Gaps (ex-reports):  88%|████████▊ | 6228/7111 [23:37<03:30,  4.20it/s]

Gaps (ex-reports):  88%|████████▊ | 6229/7111 [23:37<03:19,  4.41it/s]

Gaps (ex-reports):  88%|████████▊ | 6230/7111 [23:37<03:10,  4.61it/s]

Gaps (ex-reports):  88%|████████▊ | 6231/7111 [23:37<03:07,  4.68it/s]

Gaps (ex-reports):  88%|████████▊ | 6232/7111 [23:38<03:02,  4.81it/s]

Gaps (ex-reports):  88%|████████▊ | 6233/7111 [23:38<03:02,  4.80it/s]

Gaps (ex-reports):  88%|████████▊ | 6234/7111 [23:38<02:57,  4.94it/s]

Gaps (ex-reports):  88%|████████▊ | 6235/7111 [23:38<04:05,  3.56it/s]

Gaps (ex-reports):  88%|████████▊ | 6236/7111 [23:39<05:34,  2.61it/s]

Gaps (ex-reports):  88%|████████▊ | 6237/7111 [23:39<04:48,  3.03it/s]

Gaps (ex-reports):  88%|████████▊ | 6238/7111 [23:39<04:15,  3.42it/s]

Gaps (ex-reports):  88%|████████▊ | 6239/7111 [23:40<03:54,  3.72it/s]

Gaps (ex-reports):  88%|████████▊ | 6240/7111 [23:40<03:34,  4.06it/s]

Gaps (ex-reports):  88%|████████▊ | 6241/7111 [23:40<03:25,  4.24it/s]

Gaps (ex-reports):  88%|████████▊ | 6242/7111 [23:40<03:16,  4.43it/s]

Gaps (ex-reports):  88%|████████▊ | 6243/7111 [23:40<03:12,  4.52it/s]

Gaps (ex-reports):  88%|████████▊ | 6244/7111 [23:41<03:09,  4.57it/s]

Gaps (ex-reports):  88%|████████▊ | 6245/7111 [23:41<03:04,  4.68it/s]

Gaps (ex-reports):  88%|████████▊ | 6246/7111 [23:41<03:03,  4.71it/s]

Gaps (ex-reports):  88%|████████▊ | 6247/7111 [23:41<03:02,  4.72it/s]

Gaps (ex-reports):  88%|████████▊ | 6248/7111 [23:42<03:00,  4.78it/s]

Gaps (ex-reports):  88%|████████▊ | 6249/7111 [23:42<02:56,  4.89it/s]

Gaps (ex-reports):  88%|████████▊ | 6250/7111 [23:42<02:58,  4.82it/s]

Gaps (ex-reports):  88%|████████▊ | 6251/7111 [23:42<02:58,  4.82it/s]

Gaps (ex-reports):  88%|████████▊ | 6252/7111 [23:42<02:57,  4.85it/s]

Gaps (ex-reports):  88%|████████▊ | 6253/7111 [23:43<02:57,  4.84it/s]

Gaps (ex-reports):  88%|████████▊ | 6254/7111 [23:43<02:52,  4.96it/s]

Gaps (ex-reports):  88%|████████▊ | 6255/7111 [23:43<02:51,  5.00it/s]

Gaps (ex-reports):  88%|████████▊ | 6256/7111 [23:43<02:54,  4.90it/s]

Gaps (ex-reports):  88%|████████▊ | 6257/7111 [23:43<02:54,  4.90it/s]

Gaps (ex-reports):  88%|████████▊ | 6258/7111 [23:44<02:54,  4.89it/s]

Gaps (ex-reports):  88%|████████▊ | 6259/7111 [23:44<05:48,  2.44it/s]

Gaps (ex-reports):  88%|████████▊ | 6260/7111 [23:45<04:55,  2.88it/s]

Gaps (ex-reports):  88%|████████▊ | 6261/7111 [23:45<04:21,  3.25it/s]

Gaps (ex-reports):  88%|████████▊ | 6262/7111 [23:45<03:59,  3.55it/s]

Gaps (ex-reports):  88%|████████▊ | 6263/7111 [23:45<03:42,  3.81it/s]

Gaps (ex-reports):  88%|████████▊ | 6264/7111 [23:46<03:28,  4.07it/s]

Gaps (ex-reports):  88%|████████▊ | 6265/7111 [23:46<03:14,  4.35it/s]

Gaps (ex-reports):  88%|████████▊ | 6266/7111 [23:46<03:03,  4.60it/s]

Gaps (ex-reports):  88%|████████▊ | 6267/7111 [23:46<02:57,  4.75it/s]

Gaps (ex-reports):  88%|████████▊ | 6268/7111 [23:46<02:58,  4.73it/s]

Gaps (ex-reports):  88%|████████▊ | 6269/7111 [23:47<02:57,  4.75it/s]

Gaps (ex-reports):  88%|████████▊ | 6270/7111 [23:47<02:57,  4.73it/s]

Gaps (ex-reports):  88%|████████▊ | 6271/7111 [23:47<02:52,  4.88it/s]

Gaps (ex-reports):  88%|████████▊ | 6272/7111 [23:47<02:57,  4.73it/s]

Gaps (ex-reports):  88%|████████▊ | 6273/7111 [23:47<02:53,  4.83it/s]

Gaps (ex-reports):  88%|████████▊ | 6274/7111 [23:48<02:53,  4.82it/s]

Gaps (ex-reports):  88%|████████▊ | 6275/7111 [23:48<02:57,  4.72it/s]

Gaps (ex-reports):  88%|████████▊ | 6276/7111 [23:48<02:56,  4.74it/s]

Gaps (ex-reports):  88%|████████▊ | 6277/7111 [23:48<02:54,  4.78it/s]

Gaps (ex-reports):  88%|████████▊ | 6278/7111 [23:48<02:55,  4.74it/s]

Gaps (ex-reports):  88%|████████▊ | 6279/7111 [23:49<02:52,  4.82it/s]

Gaps (ex-reports):  88%|████████▊ | 6280/7111 [23:49<02:55,  4.73it/s]

Gaps (ex-reports):  88%|████████▊ | 6281/7111 [23:49<02:50,  4.85it/s]

Gaps (ex-reports):  88%|████████▊ | 6282/7111 [23:49<02:49,  4.89it/s]

Gaps (ex-reports):  88%|████████▊ | 6283/7111 [23:49<02:48,  4.92it/s]

Gaps (ex-reports):  88%|████████▊ | 6284/7111 [23:50<02:52,  4.78it/s]

Gaps (ex-reports):  88%|████████▊ | 6285/7111 [23:50<02:48,  4.91it/s]

Gaps (ex-reports):  88%|████████▊ | 6286/7111 [23:50<02:49,  4.86it/s]

Gaps (ex-reports):  88%|████████▊ | 6287/7111 [23:50<02:46,  4.95it/s]

Gaps (ex-reports):  88%|████████▊ | 6288/7111 [23:50<02:42,  5.05it/s]

Gaps (ex-reports):  88%|████████▊ | 6289/7111 [23:51<02:41,  5.08it/s]

Gaps (ex-reports):  88%|████████▊ | 6290/7111 [23:51<02:44,  5.00it/s]

Gaps (ex-reports):  88%|████████▊ | 6291/7111 [23:51<02:44,  4.99it/s]

Gaps (ex-reports):  88%|████████▊ | 6292/7111 [23:51<02:45,  4.96it/s]

Gaps (ex-reports):  88%|████████▊ | 6293/7111 [23:51<02:51,  4.78it/s]

Gaps (ex-reports):  89%|████████▊ | 6294/7111 [23:52<02:50,  4.79it/s]

Gaps (ex-reports):  89%|████████▊ | 6295/7111 [23:52<02:51,  4.76it/s]

Gaps (ex-reports):  89%|████████▊ | 6296/7111 [23:52<02:48,  4.83it/s]

Gaps (ex-reports):  89%|████████▊ | 6297/7111 [23:52<02:50,  4.77it/s]

Gaps (ex-reports):  89%|████████▊ | 6298/7111 [23:52<02:49,  4.79it/s]

Gaps (ex-reports):  89%|████████▊ | 6299/7111 [23:53<02:47,  4.83it/s]

Gaps (ex-reports):  89%|████████▊ | 6300/7111 [23:53<02:47,  4.84it/s]

Gaps (ex-reports):  89%|████████▊ | 6301/7111 [23:53<02:47,  4.84it/s]

Gaps (ex-reports):  89%|████████▊ | 6302/7111 [23:53<02:47,  4.82it/s]

Gaps (ex-reports):  89%|████████▊ | 6303/7111 [23:54<02:47,  4.82it/s]

Gaps (ex-reports):  89%|████████▊ | 6304/7111 [23:54<02:47,  4.83it/s]

Gaps (ex-reports):  89%|████████▊ | 6305/7111 [23:54<02:44,  4.90it/s]

Gaps (ex-reports):  89%|████████▊ | 6306/7111 [23:54<02:48,  4.79it/s]

Gaps (ex-reports):  89%|████████▊ | 6307/7111 [23:54<02:44,  4.88it/s]

Gaps (ex-reports):  89%|████████▊ | 6308/7111 [23:55<02:44,  4.89it/s]

Gaps (ex-reports):  89%|████████▊ | 6309/7111 [23:55<02:41,  4.95it/s]

Gaps (ex-reports):  89%|████████▊ | 6310/7111 [23:55<03:02,  4.38it/s]

Gaps (ex-reports):  89%|████████▊ | 6311/7111 [23:55<02:59,  4.45it/s]

Gaps (ex-reports):  89%|████████▉ | 6312/7111 [23:55<02:53,  4.60it/s]

Gaps (ex-reports):  89%|████████▉ | 6313/7111 [23:56<02:51,  4.65it/s]

Gaps (ex-reports):  89%|████████▉ | 6314/7111 [23:56<02:47,  4.75it/s]

Gaps (ex-reports):  89%|████████▉ | 6315/7111 [23:56<02:48,  4.73it/s]

Gaps (ex-reports):  89%|████████▉ | 6316/7111 [23:56<02:45,  4.80it/s]

Gaps (ex-reports):  89%|████████▉ | 6317/7111 [23:56<02:42,  4.87it/s]

Gaps (ex-reports):  89%|████████▉ | 6318/7111 [23:57<02:42,  4.89it/s]

Gaps (ex-reports):  89%|████████▉ | 6319/7111 [23:57<02:43,  4.84it/s]

Gaps (ex-reports):  89%|████████▉ | 6320/7111 [23:57<02:41,  4.90it/s]

Gaps (ex-reports):  89%|████████▉ | 6321/7111 [23:58<04:55,  2.67it/s]

Gaps (ex-reports):  89%|████████▉ | 6322/7111 [23:58<04:17,  3.06it/s]

Gaps (ex-reports):  89%|████████▉ | 6323/7111 [23:58<03:45,  3.50it/s]

Gaps (ex-reports):  89%|████████▉ | 6324/7111 [23:58<03:29,  3.76it/s]

Gaps (ex-reports):  89%|████████▉ | 6325/7111 [23:59<03:14,  4.03it/s]

Gaps (ex-reports):  89%|████████▉ | 6326/7111 [23:59<03:09,  4.14it/s]

Gaps (ex-reports):  89%|████████▉ | 6327/7111 [23:59<03:03,  4.26it/s]

Gaps (ex-reports):  89%|████████▉ | 6328/7111 [23:59<02:55,  4.46it/s]

Gaps (ex-reports):  89%|████████▉ | 6329/7111 [24:00<02:48,  4.65it/s]

Gaps (ex-reports):  89%|████████▉ | 6330/7111 [24:00<02:44,  4.76it/s]

Gaps (ex-reports):  89%|████████▉ | 6331/7111 [24:00<02:44,  4.74it/s]

Gaps (ex-reports):  89%|████████▉ | 6332/7111 [24:00<02:47,  4.64it/s]

Gaps (ex-reports):  89%|████████▉ | 6333/7111 [24:00<02:43,  4.75it/s]

Gaps (ex-reports):  89%|████████▉ | 6334/7111 [24:01<02:38,  4.89it/s]

Gaps (ex-reports):  89%|████████▉ | 6335/7111 [24:01<02:41,  4.81it/s]

Gaps (ex-reports):  89%|████████▉ | 6336/7111 [24:01<02:39,  4.87it/s]

Gaps (ex-reports):  89%|████████▉ | 6337/7111 [24:01<02:36,  4.93it/s]

Gaps (ex-reports):  89%|████████▉ | 6338/7111 [24:01<02:37,  4.91it/s]

Gaps (ex-reports):  89%|████████▉ | 6339/7111 [24:02<02:37,  4.91it/s]

Gaps (ex-reports):  89%|████████▉ | 6340/7111 [24:02<02:50,  4.52it/s]

Gaps (ex-reports):  89%|████████▉ | 6341/7111 [24:02<02:48,  4.57it/s]

Gaps (ex-reports):  89%|████████▉ | 6342/7111 [24:02<02:43,  4.72it/s]

Gaps (ex-reports):  89%|████████▉ | 6343/7111 [24:02<02:41,  4.75it/s]

Gaps (ex-reports):  89%|████████▉ | 6344/7111 [24:03<02:42,  4.73it/s]

Gaps (ex-reports):  89%|████████▉ | 6345/7111 [24:03<02:41,  4.76it/s]

Gaps (ex-reports):  89%|████████▉ | 6346/7111 [24:03<02:40,  4.78it/s]

Gaps (ex-reports):  89%|████████▉ | 6347/7111 [24:03<02:39,  4.79it/s]

Gaps (ex-reports):  89%|████████▉ | 6348/7111 [24:03<02:38,  4.80it/s]

Gaps (ex-reports):  89%|████████▉ | 6349/7111 [24:04<02:35,  4.89it/s]

Gaps (ex-reports):  89%|████████▉ | 6350/7111 [24:04<02:36,  4.86it/s]

Gaps (ex-reports):  89%|████████▉ | 6351/7111 [24:04<02:36,  4.85it/s]

Gaps (ex-reports):  89%|████████▉ | 6352/7111 [24:04<02:37,  4.82it/s]

Gaps (ex-reports):  89%|████████▉ | 6353/7111 [24:05<02:33,  4.93it/s]

Gaps (ex-reports):  89%|████████▉ | 6354/7111 [24:05<02:31,  4.98it/s]

Gaps (ex-reports):  89%|████████▉ | 6355/7111 [24:05<02:31,  5.00it/s]

Gaps (ex-reports):  89%|████████▉ | 6356/7111 [24:05<02:58,  4.23it/s]

Gaps (ex-reports):  89%|████████▉ | 6357/7111 [24:05<02:48,  4.47it/s]

Gaps (ex-reports):  89%|████████▉ | 6358/7111 [24:06<02:47,  4.50it/s]

Gaps (ex-reports):  89%|████████▉ | 6359/7111 [24:06<02:41,  4.65it/s]

Gaps (ex-reports):  89%|████████▉ | 6360/7111 [24:06<02:40,  4.67it/s]

Gaps (ex-reports):  89%|████████▉ | 6361/7111 [24:06<02:36,  4.78it/s]

Gaps (ex-reports):  89%|████████▉ | 6362/7111 [24:06<02:33,  4.88it/s]

Gaps (ex-reports):  89%|████████▉ | 6363/7111 [24:07<02:37,  4.76it/s]

Gaps (ex-reports):  89%|████████▉ | 6364/7111 [24:07<02:33,  4.87it/s]

Gaps (ex-reports):  90%|████████▉ | 6365/7111 [24:07<02:30,  4.96it/s]

Gaps (ex-reports):  90%|████████▉ | 6366/7111 [24:07<02:30,  4.94it/s]

Gaps (ex-reports):  90%|████████▉ | 6367/7111 [24:07<02:28,  5.00it/s]

Gaps (ex-reports):  90%|████████▉ | 6368/7111 [24:08<02:29,  4.96it/s]

Gaps (ex-reports):  90%|████████▉ | 6369/7111 [24:08<02:28,  4.98it/s]

Gaps (ex-reports):  90%|████████▉ | 6370/7111 [24:08<02:27,  5.03it/s]

Gaps (ex-reports):  90%|████████▉ | 6371/7111 [24:08<02:27,  5.00it/s]

Gaps (ex-reports):  90%|████████▉ | 6372/7111 [24:08<02:26,  5.05it/s]

Gaps (ex-reports):  90%|████████▉ | 6373/7111 [24:09<02:26,  5.03it/s]

Gaps (ex-reports):  90%|████████▉ | 6374/7111 [24:09<02:27,  5.00it/s]

Gaps (ex-reports):  90%|████████▉ | 6375/7111 [24:09<02:29,  4.93it/s]

Gaps (ex-reports):  90%|████████▉ | 6376/7111 [24:09<02:31,  4.84it/s]

Gaps (ex-reports):  90%|████████▉ | 6377/7111 [24:09<02:29,  4.90it/s]

Gaps (ex-reports):  90%|████████▉ | 6378/7111 [24:10<02:29,  4.89it/s]

Gaps (ex-reports):  90%|████████▉ | 6379/7111 [24:10<02:29,  4.89it/s]

Gaps (ex-reports):  90%|████████▉ | 6380/7111 [24:10<02:29,  4.90it/s]

Gaps (ex-reports):  90%|████████▉ | 6381/7111 [24:10<02:28,  4.90it/s]

Gaps (ex-reports):  90%|████████▉ | 6382/7111 [24:10<02:25,  5.02it/s]

Gaps (ex-reports):  90%|████████▉ | 6383/7111 [24:11<02:25,  5.02it/s]

Gaps (ex-reports):  90%|████████▉ | 6384/7111 [24:11<02:24,  5.02it/s]

Gaps (ex-reports):  90%|████████▉ | 6385/7111 [24:11<02:24,  5.01it/s]

Gaps (ex-reports):  90%|████████▉ | 6386/7111 [24:11<02:25,  4.99it/s]

Gaps (ex-reports):  90%|████████▉ | 6387/7111 [24:11<02:24,  5.01it/s]

Gaps (ex-reports):  90%|████████▉ | 6388/7111 [24:12<02:24,  4.99it/s]

Gaps (ex-reports):  90%|████████▉ | 6389/7111 [24:12<02:27,  4.88it/s]

Gaps (ex-reports):  90%|████████▉ | 6390/7111 [24:12<02:27,  4.89it/s]

Gaps (ex-reports):  90%|████████▉ | 6391/7111 [24:12<02:28,  4.84it/s]

Gaps (ex-reports):  90%|████████▉ | 6392/7111 [24:13<02:40,  4.48it/s]

Gaps (ex-reports):  90%|████████▉ | 6393/7111 [24:13<02:34,  4.65it/s]

Gaps (ex-reports):  90%|████████▉ | 6394/7111 [24:13<02:33,  4.66it/s]

Gaps (ex-reports):  90%|████████▉ | 6395/7111 [24:13<02:28,  4.82it/s]

Gaps (ex-reports):  90%|████████▉ | 6396/7111 [24:13<02:29,  4.80it/s]

Gaps (ex-reports):  90%|████████▉ | 6397/7111 [24:14<02:28,  4.81it/s]

Gaps (ex-reports):  90%|████████▉ | 6398/7111 [24:14<02:25,  4.91it/s]

Gaps (ex-reports):  90%|████████▉ | 6399/7111 [24:14<02:24,  4.94it/s]

Gaps (ex-reports):  90%|█████████ | 6400/7111 [24:14<02:21,  5.02it/s]

Gaps (ex-reports):  90%|█████████ | 6401/7111 [24:14<02:24,  4.91it/s]

Gaps (ex-reports):  90%|█████████ | 6402/7111 [24:15<02:24,  4.90it/s]

Gaps (ex-reports):  90%|█████████ | 6403/7111 [24:15<02:25,  4.88it/s]

Gaps (ex-reports):  90%|█████████ | 6404/7111 [24:15<02:25,  4.86it/s]

Gaps (ex-reports):  90%|█████████ | 6405/7111 [24:15<02:27,  4.79it/s]

Gaps (ex-reports):  90%|█████████ | 6406/7111 [24:15<02:25,  4.85it/s]

Gaps (ex-reports):  90%|█████████ | 6407/7111 [24:16<02:24,  4.89it/s]

Gaps (ex-reports):  90%|█████████ | 6408/7111 [24:16<02:20,  5.00it/s]

Gaps (ex-reports):  90%|█████████ | 6409/7111 [24:16<02:20,  5.01it/s]

Gaps (ex-reports):  90%|█████████ | 6410/7111 [24:16<02:21,  4.95it/s]

Gaps (ex-reports):  90%|█████████ | 6411/7111 [24:16<02:19,  5.02it/s]

Gaps (ex-reports):  90%|█████████ | 6412/7111 [24:17<02:22,  4.91it/s]

Gaps (ex-reports):  90%|█████████ | 6413/7111 [24:17<02:21,  4.93it/s]

Gaps (ex-reports):  90%|█████████ | 6414/7111 [24:17<02:18,  5.03it/s]

Gaps (ex-reports):  90%|█████████ | 6415/7111 [24:17<02:18,  5.04it/s]

Gaps (ex-reports):  90%|█████████ | 6416/7111 [24:17<02:21,  4.91it/s]

Gaps (ex-reports):  90%|█████████ | 6417/7111 [24:18<02:21,  4.89it/s]

Gaps (ex-reports):  90%|█████████ | 6418/7111 [24:18<02:21,  4.88it/s]

Gaps (ex-reports):  90%|█████████ | 6419/7111 [24:18<02:19,  4.95it/s]

Gaps (ex-reports):  90%|█████████ | 6420/7111 [24:18<02:22,  4.84it/s]

Gaps (ex-reports):  90%|█████████ | 6421/7111 [24:18<02:22,  4.85it/s]

Gaps (ex-reports):  90%|█████████ | 6422/7111 [24:19<02:21,  4.87it/s]

Gaps (ex-reports):  90%|█████████ | 6423/7111 [24:19<02:22,  4.84it/s]

Gaps (ex-reports):  90%|█████████ | 6424/7111 [24:19<02:22,  4.83it/s]

Gaps (ex-reports):  90%|█████████ | 6425/7111 [24:19<02:21,  4.84it/s]

Gaps (ex-reports):  90%|█████████ | 6426/7111 [24:19<02:20,  4.89it/s]

Gaps (ex-reports):  90%|█████████ | 6427/7111 [24:20<02:20,  4.85it/s]

Gaps (ex-reports):  90%|█████████ | 6428/7111 [24:20<02:21,  4.82it/s]

Gaps (ex-reports):  90%|█████████ | 6429/7111 [24:20<02:22,  4.78it/s]

Gaps (ex-reports):  90%|█████████ | 6430/7111 [24:20<02:21,  4.80it/s]

Gaps (ex-reports):  90%|█████████ | 6431/7111 [24:21<02:18,  4.91it/s]

Gaps (ex-reports):  90%|█████████ | 6432/7111 [24:21<02:16,  4.98it/s]

Gaps (ex-reports):  90%|█████████ | 6433/7111 [24:21<02:17,  4.93it/s]

Gaps (ex-reports):  90%|█████████ | 6434/7111 [24:21<02:20,  4.80it/s]

Gaps (ex-reports):  90%|█████████ | 6435/7111 [24:21<02:17,  4.92it/s]

Gaps (ex-reports):  91%|█████████ | 6436/7111 [24:22<02:15,  5.00it/s]

Gaps (ex-reports):  91%|█████████ | 6437/7111 [24:22<02:17,  4.90it/s]

Gaps (ex-reports):  91%|█████████ | 6438/7111 [24:22<02:16,  4.92it/s]

Gaps (ex-reports):  91%|█████████ | 6439/7111 [24:22<02:18,  4.85it/s]

Gaps (ex-reports):  91%|█████████ | 6440/7111 [24:22<02:16,  4.93it/s]

Gaps (ex-reports):  91%|█████████ | 6441/7111 [24:23<02:16,  4.90it/s]

Gaps (ex-reports):  91%|█████████ | 6442/7111 [24:23<02:16,  4.90it/s]

Gaps (ex-reports):  91%|█████████ | 6443/7111 [24:23<02:18,  4.82it/s]

Gaps (ex-reports):  91%|█████████ | 6444/7111 [24:23<02:19,  4.77it/s]

Gaps (ex-reports):  91%|█████████ | 6445/7111 [24:23<02:19,  4.77it/s]

Gaps (ex-reports):  91%|█████████ | 6446/7111 [24:24<02:17,  4.83it/s]

Gaps (ex-reports):  91%|█████████ | 6447/7111 [24:24<02:17,  4.81it/s]

Gaps (ex-reports):  91%|█████████ | 6448/7111 [24:24<02:16,  4.86it/s]

Gaps (ex-reports):  91%|█████████ | 6449/7111 [24:24<02:15,  4.88it/s]

Gaps (ex-reports):  91%|█████████ | 6450/7111 [24:24<02:14,  4.92it/s]

Gaps (ex-reports):  91%|█████████ | 6451/7111 [24:25<02:16,  4.85it/s]

Gaps (ex-reports):  91%|█████████ | 6452/7111 [24:25<02:14,  4.91it/s]

Gaps (ex-reports):  91%|█████████ | 6453/7111 [24:25<02:15,  4.84it/s]

Gaps (ex-reports):  91%|█████████ | 6454/7111 [24:25<02:15,  4.86it/s]

Gaps (ex-reports):  91%|█████████ | 6455/7111 [24:25<02:15,  4.84it/s]

Gaps (ex-reports):  91%|█████████ | 6456/7111 [24:26<02:15,  4.82it/s]

Gaps (ex-reports):  91%|█████████ | 6457/7111 [24:26<02:14,  4.86it/s]

Gaps (ex-reports):  91%|█████████ | 6458/7111 [24:26<02:15,  4.81it/s]

Gaps (ex-reports):  91%|█████████ | 6459/7111 [24:26<02:15,  4.81it/s]

Gaps (ex-reports):  91%|█████████ | 6460/7111 [24:26<02:14,  4.83it/s]

Gaps (ex-reports):  91%|█████████ | 6461/7111 [24:27<02:16,  4.77it/s]

Gaps (ex-reports):  91%|█████████ | 6462/7111 [24:27<02:14,  4.82it/s]

Gaps (ex-reports):  91%|█████████ | 6463/7111 [24:27<02:13,  4.84it/s]

Gaps (ex-reports):  91%|█████████ | 6464/7111 [24:27<02:11,  4.92it/s]

Gaps (ex-reports):  91%|█████████ | 6465/7111 [24:28<02:12,  4.87it/s]

Gaps (ex-reports):  91%|█████████ | 6466/7111 [24:28<02:11,  4.89it/s]

Gaps (ex-reports):  91%|█████████ | 6467/7111 [24:28<02:09,  4.98it/s]

Gaps (ex-reports):  91%|█████████ | 6468/7111 [24:28<02:21,  4.56it/s]

Gaps (ex-reports):  91%|█████████ | 6469/7111 [24:28<02:17,  4.65it/s]

Gaps (ex-reports):  91%|█████████ | 6470/7111 [24:29<02:15,  4.72it/s]

Gaps (ex-reports):  91%|█████████ | 6471/7111 [24:29<02:14,  4.76it/s]

Gaps (ex-reports):  91%|█████████ | 6472/7111 [24:29<02:12,  4.82it/s]

Gaps (ex-reports):  91%|█████████ | 6473/7111 [24:29<02:11,  4.84it/s]

Gaps (ex-reports):  91%|█████████ | 6474/7111 [24:29<02:14,  4.75it/s]

Gaps (ex-reports):  91%|█████████ | 6475/7111 [24:30<02:16,  4.65it/s]

Gaps (ex-reports):  91%|█████████ | 6476/7111 [24:30<02:15,  4.68it/s]

Gaps (ex-reports):  91%|█████████ | 6477/7111 [24:30<02:15,  4.67it/s]

Gaps (ex-reports):  91%|█████████ | 6478/7111 [24:30<02:13,  4.75it/s]

Gaps (ex-reports):  91%|█████████ | 6479/7111 [24:30<02:13,  4.75it/s]

Gaps (ex-reports):  91%|█████████ | 6480/7111 [24:31<02:09,  4.86it/s]

Gaps (ex-reports):  91%|█████████ | 6481/7111 [24:31<02:09,  4.86it/s]

Gaps (ex-reports):  91%|█████████ | 6482/7111 [24:31<02:09,  4.84it/s]

Gaps (ex-reports):  91%|█████████ | 6483/7111 [24:31<02:09,  4.85it/s]

Gaps (ex-reports):  91%|█████████ | 6484/7111 [24:31<02:08,  4.86it/s]

Gaps (ex-reports):  91%|█████████ | 6485/7111 [24:32<02:06,  4.94it/s]

Gaps (ex-reports):  91%|█████████ | 6486/7111 [24:32<02:04,  5.01it/s]

Gaps (ex-reports):  91%|█████████ | 6487/7111 [24:32<02:04,  5.03it/s]

Gaps (ex-reports):  91%|█████████ | 6488/7111 [24:32<02:05,  4.95it/s]

Gaps (ex-reports):  91%|█████████▏| 6489/7111 [24:32<02:05,  4.97it/s]

Gaps (ex-reports):  91%|█████████▏| 6490/7111 [24:33<02:06,  4.93it/s]

Gaps (ex-reports):  91%|█████████▏| 6491/7111 [24:33<02:23,  4.33it/s]

Gaps (ex-reports):  91%|█████████▏| 6492/7111 [24:33<02:17,  4.51it/s]

Gaps (ex-reports):  91%|█████████▏| 6493/7111 [24:33<02:14,  4.60it/s]

Gaps (ex-reports):  91%|█████████▏| 6494/7111 [24:34<02:09,  4.76it/s]

Gaps (ex-reports):  91%|█████████▏| 6495/7111 [24:34<02:06,  4.86it/s]

Gaps (ex-reports):  91%|█████████▏| 6496/7111 [24:34<02:04,  4.95it/s]

Gaps (ex-reports):  91%|█████████▏| 6497/7111 [24:34<02:03,  4.96it/s]

Gaps (ex-reports):  91%|█████████▏| 6498/7111 [24:34<02:06,  4.83it/s]

Gaps (ex-reports):  91%|█████████▏| 6499/7111 [24:35<02:04,  4.93it/s]

Gaps (ex-reports):  91%|█████████▏| 6500/7111 [24:35<02:03,  4.97it/s]

Gaps (ex-reports):  91%|█████████▏| 6501/7111 [24:35<02:01,  5.00it/s]

Gaps (ex-reports):  91%|█████████▏| 6502/7111 [24:35<02:01,  4.99it/s]

Gaps (ex-reports):  91%|█████████▏| 6503/7111 [24:35<02:03,  4.94it/s]

Gaps (ex-reports):  91%|█████████▏| 6504/7111 [24:36<02:02,  4.97it/s]

Gaps (ex-reports):  91%|█████████▏| 6505/7111 [24:36<02:02,  4.95it/s]

Gaps (ex-reports):  91%|█████████▏| 6506/7111 [24:36<02:01,  4.98it/s]

Gaps (ex-reports):  92%|█████████▏| 6507/7111 [24:36<02:02,  4.94it/s]

Gaps (ex-reports):  92%|█████████▏| 6508/7111 [24:36<02:02,  4.92it/s]

Gaps (ex-reports):  92%|█████████▏| 6509/7111 [24:37<02:05,  4.78it/s]

Gaps (ex-reports):  92%|█████████▏| 6510/7111 [24:37<02:04,  4.81it/s]

Gaps (ex-reports):  92%|█████████▏| 6511/7111 [24:37<02:03,  4.87it/s]

Gaps (ex-reports):  92%|█████████▏| 6512/7111 [24:37<02:04,  4.82it/s]

Gaps (ex-reports):  92%|█████████▏| 6513/7111 [24:37<02:05,  4.77it/s]

Gaps (ex-reports):  92%|█████████▏| 6514/7111 [24:38<02:05,  4.76it/s]

Gaps (ex-reports):  92%|█████████▏| 6515/7111 [24:38<02:01,  4.89it/s]

Gaps (ex-reports):  92%|█████████▏| 6516/7111 [24:38<02:02,  4.85it/s]

Gaps (ex-reports):  92%|█████████▏| 6517/7111 [24:38<02:02,  4.83it/s]

Gaps (ex-reports):  92%|█████████▏| 6518/7111 [24:38<02:03,  4.80it/s]

Gaps (ex-reports):  92%|█████████▏| 6519/7111 [24:39<02:02,  4.81it/s]

Gaps (ex-reports):  92%|█████████▏| 6520/7111 [24:39<02:03,  4.79it/s]

Gaps (ex-reports):  92%|█████████▏| 6521/7111 [24:39<02:20,  4.20it/s]

Gaps (ex-reports):  92%|█████████▏| 6522/7111 [24:39<02:13,  4.41it/s]

Gaps (ex-reports):  92%|█████████▏| 6523/7111 [24:40<02:12,  4.44it/s]

Gaps (ex-reports):  92%|█████████▏| 6524/7111 [24:40<02:07,  4.61it/s]

Gaps (ex-reports):  92%|█████████▏| 6525/7111 [24:40<02:05,  4.68it/s]

Gaps (ex-reports):  92%|█████████▏| 6526/7111 [24:40<02:02,  4.79it/s]

Gaps (ex-reports):  92%|█████████▏| 6527/7111 [24:40<02:00,  4.84it/s]

Gaps (ex-reports):  92%|█████████▏| 6528/7111 [24:41<02:04,  4.70it/s]

Gaps (ex-reports):  92%|█████████▏| 6529/7111 [24:41<02:03,  4.71it/s]

Gaps (ex-reports):  92%|█████████▏| 6530/7111 [24:41<02:01,  4.77it/s]

Gaps (ex-reports):  92%|█████████▏| 6531/7111 [24:41<01:58,  4.89it/s]

Gaps (ex-reports):  92%|█████████▏| 6532/7111 [24:41<01:58,  4.90it/s]

Gaps (ex-reports):  92%|█████████▏| 6533/7111 [24:42<02:17,  4.20it/s]

Gaps (ex-reports):  92%|█████████▏| 6534/7111 [24:42<02:10,  4.43it/s]

Gaps (ex-reports):  92%|█████████▏| 6535/7111 [24:42<02:04,  4.63it/s]

Gaps (ex-reports):  92%|█████████▏| 6536/7111 [24:42<02:02,  4.70it/s]

Gaps (ex-reports):  92%|█████████▏| 6537/7111 [24:43<02:02,  4.67it/s]

Gaps (ex-reports):  92%|█████████▏| 6538/7111 [24:43<02:00,  4.76it/s]

Gaps (ex-reports):  92%|█████████▏| 6539/7111 [24:43<01:58,  4.84it/s]

Gaps (ex-reports):  92%|█████████▏| 6540/7111 [24:43<01:55,  4.93it/s]

Gaps (ex-reports):  92%|█████████▏| 6541/7111 [24:43<01:55,  4.95it/s]

Gaps (ex-reports):  92%|█████████▏| 6542/7111 [24:44<01:55,  4.94it/s]

Gaps (ex-reports):  92%|█████████▏| 6543/7111 [24:44<01:55,  4.94it/s]

Gaps (ex-reports):  92%|█████████▏| 6544/7111 [24:44<01:55,  4.91it/s]

Gaps (ex-reports):  92%|█████████▏| 6545/7111 [24:44<01:55,  4.89it/s]

Gaps (ex-reports):  92%|█████████▏| 6546/7111 [24:44<01:53,  5.00it/s]

Gaps (ex-reports):  92%|█████████▏| 6547/7111 [24:45<01:54,  4.93it/s]

Gaps (ex-reports):  92%|█████████▏| 6548/7111 [24:45<01:55,  4.87it/s]

Gaps (ex-reports):  92%|█████████▏| 6549/7111 [24:45<01:54,  4.89it/s]

Gaps (ex-reports):  92%|█████████▏| 6550/7111 [24:45<01:52,  4.99it/s]

Gaps (ex-reports):  92%|█████████▏| 6551/7111 [24:45<01:52,  4.96it/s]

Gaps (ex-reports):  92%|█████████▏| 6552/7111 [24:46<01:54,  4.90it/s]

Gaps (ex-reports):  92%|█████████▏| 6553/7111 [24:46<01:52,  4.96it/s]

Gaps (ex-reports):  92%|█████████▏| 6554/7111 [24:46<01:50,  5.04it/s]

Gaps (ex-reports):  92%|█████████▏| 6555/7111 [24:46<01:49,  5.08it/s]

Gaps (ex-reports):  92%|█████████▏| 6556/7111 [24:46<01:48,  5.11it/s]

Gaps (ex-reports):  92%|█████████▏| 6557/7111 [24:47<01:53,  4.90it/s]

Gaps (ex-reports):  92%|█████████▏| 6558/7111 [24:47<01:51,  4.96it/s]

Gaps (ex-reports):  92%|█████████▏| 6559/7111 [24:47<01:52,  4.92it/s]

Gaps (ex-reports):  92%|█████████▏| 6560/7111 [24:47<01:53,  4.86it/s]

Gaps (ex-reports):  92%|█████████▏| 6561/7111 [24:47<01:52,  4.91it/s]

Gaps (ex-reports):  92%|█████████▏| 6562/7111 [24:48<01:52,  4.86it/s]

Gaps (ex-reports):  92%|█████████▏| 6563/7111 [24:48<01:50,  4.97it/s]

Gaps (ex-reports):  92%|█████████▏| 6564/7111 [24:48<01:47,  5.07it/s]

Gaps (ex-reports):  92%|█████████▏| 6565/7111 [24:48<01:51,  4.89it/s]

Gaps (ex-reports):  92%|█████████▏| 6566/7111 [24:48<01:49,  4.97it/s]

Gaps (ex-reports):  92%|█████████▏| 6567/7111 [24:49<01:57,  4.62it/s]

Gaps (ex-reports):  92%|█████████▏| 6568/7111 [24:49<01:55,  4.70it/s]

Gaps (ex-reports):  92%|█████████▏| 6569/7111 [24:49<01:54,  4.75it/s]

Gaps (ex-reports):  92%|█████████▏| 6570/7111 [24:49<01:53,  4.75it/s]

Gaps (ex-reports):  92%|█████████▏| 6571/7111 [24:50<01:54,  4.71it/s]

Gaps (ex-reports):  92%|█████████▏| 6572/7111 [24:50<01:52,  4.80it/s]

Gaps (ex-reports):  92%|█████████▏| 6573/7111 [24:50<02:27,  3.65it/s]

Gaps (ex-reports):  92%|█████████▏| 6574/7111 [24:50<02:16,  3.95it/s]

Gaps (ex-reports):  92%|█████████▏| 6575/7111 [24:51<02:06,  4.23it/s]

Gaps (ex-reports):  92%|█████████▏| 6576/7111 [24:51<01:59,  4.48it/s]

Gaps (ex-reports):  92%|█████████▏| 6577/7111 [24:51<02:11,  4.07it/s]

Gaps (ex-reports):  93%|█████████▎| 6578/7111 [24:51<02:02,  4.36it/s]

Gaps (ex-reports):  93%|█████████▎| 6579/7111 [24:51<01:57,  4.54it/s]

Gaps (ex-reports):  93%|█████████▎| 6580/7111 [24:52<01:55,  4.58it/s]

Gaps (ex-reports):  93%|█████████▎| 6581/7111 [24:52<01:52,  4.71it/s]

Gaps (ex-reports):  93%|█████████▎| 6582/7111 [24:52<01:51,  4.76it/s]

Gaps (ex-reports):  93%|█████████▎| 6583/7111 [24:52<01:49,  4.80it/s]

Gaps (ex-reports):  93%|█████████▎| 6584/7111 [24:52<01:47,  4.89it/s]

Gaps (ex-reports):  93%|█████████▎| 6585/7111 [24:53<01:46,  4.96it/s]

Gaps (ex-reports):  93%|█████████▎| 6586/7111 [24:53<01:44,  5.03it/s]

Gaps (ex-reports):  93%|█████████▎| 6587/7111 [24:53<01:45,  4.97it/s]

Gaps (ex-reports):  93%|█████████▎| 6588/7111 [24:53<01:43,  5.03it/s]

Gaps (ex-reports):  93%|█████████▎| 6589/7111 [24:53<01:45,  4.94it/s]

Gaps (ex-reports):  93%|█████████▎| 6590/7111 [24:54<01:44,  4.96it/s]

Gaps (ex-reports):  93%|█████████▎| 6591/7111 [24:54<01:44,  4.96it/s]

Gaps (ex-reports):  93%|█████████▎| 6592/7111 [24:54<01:45,  4.92it/s]

Gaps (ex-reports):  93%|█████████▎| 6593/7111 [24:54<01:45,  4.93it/s]

Gaps (ex-reports):  93%|█████████▎| 6594/7111 [24:54<01:43,  4.99it/s]

Gaps (ex-reports):  93%|█████████▎| 6595/7111 [24:55<01:44,  4.93it/s]

Gaps (ex-reports):  93%|█████████▎| 6596/7111 [24:55<01:42,  5.01it/s]

Gaps (ex-reports):  93%|█████████▎| 6597/7111 [24:55<01:43,  4.95it/s]

Gaps (ex-reports):  93%|█████████▎| 6598/7111 [24:55<01:44,  4.91it/s]

Gaps (ex-reports):  93%|█████████▎| 6599/7111 [24:56<01:46,  4.82it/s]

Gaps (ex-reports):  93%|█████████▎| 6600/7111 [24:56<01:44,  4.91it/s]

Gaps (ex-reports):  93%|█████████▎| 6601/7111 [24:56<01:45,  4.83it/s]

Gaps (ex-reports):  93%|█████████▎| 6602/7111 [24:56<01:44,  4.87it/s]

Gaps (ex-reports):  93%|█████████▎| 6603/7111 [24:56<01:43,  4.93it/s]

Gaps (ex-reports):  93%|█████████▎| 6604/7111 [24:57<01:43,  4.90it/s]

Gaps (ex-reports):  93%|█████████▎| 6605/7111 [24:57<01:46,  4.75it/s]

Gaps (ex-reports):  93%|█████████▎| 6606/7111 [24:57<01:47,  4.70it/s]

Gaps (ex-reports):  93%|█████████▎| 6607/7111 [24:57<01:45,  4.79it/s]

Gaps (ex-reports):  93%|█████████▎| 6608/7111 [24:57<01:47,  4.69it/s]

Gaps (ex-reports):  93%|█████████▎| 6609/7111 [24:58<01:45,  4.74it/s]

Gaps (ex-reports):  93%|█████████▎| 6610/7111 [24:58<01:44,  4.78it/s]

Gaps (ex-reports):  93%|█████████▎| 6611/7111 [24:58<01:45,  4.74it/s]

Gaps (ex-reports):  93%|█████████▎| 6612/7111 [24:58<01:42,  4.89it/s]

Gaps (ex-reports):  93%|█████████▎| 6613/7111 [24:58<01:42,  4.88it/s]

Gaps (ex-reports):  93%|█████████▎| 6614/7111 [24:59<01:43,  4.82it/s]

Gaps (ex-reports):  93%|█████████▎| 6615/7111 [24:59<01:43,  4.81it/s]

Gaps (ex-reports):  93%|█████████▎| 6616/7111 [24:59<01:43,  4.78it/s]

Gaps (ex-reports):  93%|█████████▎| 6617/7111 [24:59<01:41,  4.85it/s]

Gaps (ex-reports):  93%|█████████▎| 6618/7111 [24:59<01:41,  4.86it/s]

Gaps (ex-reports):  93%|█████████▎| 6619/7111 [25:00<01:40,  4.88it/s]

Gaps (ex-reports):  93%|█████████▎| 6620/7111 [25:00<01:40,  4.90it/s]

Gaps (ex-reports):  93%|█████████▎| 6621/7111 [25:00<01:39,  4.92it/s]

Gaps (ex-reports):  93%|█████████▎| 6622/7111 [25:00<01:40,  4.89it/s]

Gaps (ex-reports):  93%|█████████▎| 6623/7111 [25:00<01:40,  4.85it/s]

Gaps (ex-reports):  93%|█████████▎| 6624/7111 [25:01<01:39,  4.90it/s]

Gaps (ex-reports):  93%|█████████▎| 6625/7111 [25:01<01:40,  4.82it/s]

Gaps (ex-reports):  93%|█████████▎| 6626/7111 [25:01<01:38,  4.93it/s]

Gaps (ex-reports):  93%|█████████▎| 6627/7111 [25:01<01:36,  4.99it/s]

Gaps (ex-reports):  93%|█████████▎| 6628/7111 [25:01<01:35,  5.04it/s]

Gaps (ex-reports):  93%|█████████▎| 6629/7111 [25:02<01:37,  4.96it/s]

Gaps (ex-reports):  93%|█████████▎| 6630/7111 [25:02<01:39,  4.81it/s]

Gaps (ex-reports):  93%|█████████▎| 6631/7111 [25:03<03:48,  2.10it/s]

Gaps (ex-reports):  93%|█████████▎| 6632/7111 [25:03<03:08,  2.55it/s]

Gaps (ex-reports):  93%|█████████▎| 6633/7111 [25:03<02:40,  2.98it/s]

Gaps (ex-reports):  93%|█████████▎| 6634/7111 [25:04<02:36,  3.05it/s]

Gaps (ex-reports):  93%|█████████▎| 6635/7111 [25:04<02:19,  3.42it/s]

Gaps (ex-reports):  93%|█████████▎| 6636/7111 [25:04<02:03,  3.83it/s]

Gaps (ex-reports):  93%|█████████▎| 6637/7111 [25:04<01:54,  4.15it/s]

Gaps (ex-reports):  93%|█████████▎| 6638/7111 [25:05<01:50,  4.30it/s]

Gaps (ex-reports):  93%|█████████▎| 6639/7111 [25:05<01:46,  4.44it/s]

Gaps (ex-reports):  93%|█████████▎| 6640/7111 [25:05<01:45,  4.46it/s]

Gaps (ex-reports):  93%|█████████▎| 6641/7111 [25:05<01:41,  4.64it/s]

Gaps (ex-reports):  93%|█████████▎| 6642/7111 [25:05<01:41,  4.63it/s]

Gaps (ex-reports):  93%|█████████▎| 6643/7111 [25:06<01:41,  4.60it/s]

Gaps (ex-reports):  93%|█████████▎| 6644/7111 [25:06<01:39,  4.71it/s]

Gaps (ex-reports):  93%|█████████▎| 6645/7111 [25:06<01:37,  4.79it/s]

Gaps (ex-reports):  93%|█████████▎| 6646/7111 [25:06<01:34,  4.90it/s]

Gaps (ex-reports):  93%|█████████▎| 6647/7111 [25:06<01:33,  4.97it/s]

Gaps (ex-reports):  93%|█████████▎| 6648/7111 [25:07<01:34,  4.91it/s]

Gaps (ex-reports):  94%|█████████▎| 6649/7111 [25:07<01:34,  4.87it/s]

Gaps (ex-reports):  94%|█████████▎| 6650/7111 [25:07<01:34,  4.90it/s]

Gaps (ex-reports):  94%|█████████▎| 6651/7111 [25:07<01:32,  4.98it/s]

Gaps (ex-reports):  94%|█████████▎| 6652/7111 [25:07<01:33,  4.91it/s]

Gaps (ex-reports):  94%|█████████▎| 6653/7111 [25:08<01:33,  4.90it/s]

Gaps (ex-reports):  94%|█████████▎| 6654/7111 [25:08<01:33,  4.91it/s]

Gaps (ex-reports):  94%|█████████▎| 6655/7111 [25:08<01:31,  4.98it/s]

Gaps (ex-reports):  94%|█████████▎| 6656/7111 [25:08<01:30,  5.01it/s]

Gaps (ex-reports):  94%|█████████▎| 6657/7111 [25:08<01:32,  4.92it/s]

Gaps (ex-reports):  94%|█████████▎| 6658/7111 [25:09<01:30,  5.00it/s]

Gaps (ex-reports):  94%|█████████▎| 6659/7111 [25:09<01:29,  5.05it/s]

Gaps (ex-reports):  94%|█████████▎| 6660/7111 [25:09<01:32,  4.88it/s]

Gaps (ex-reports):  94%|█████████▎| 6661/7111 [25:09<01:30,  4.99it/s]

Gaps (ex-reports):  94%|█████████▎| 6662/7111 [25:09<01:32,  4.88it/s]

Gaps (ex-reports):  94%|█████████▎| 6663/7111 [25:10<03:09,  2.36it/s]

Gaps (ex-reports):  94%|█████████▎| 6664/7111 [25:11<02:38,  2.82it/s]

Gaps (ex-reports):  94%|█████████▎| 6665/7111 [25:11<02:19,  3.21it/s]

Gaps (ex-reports):  94%|█████████▎| 6666/7111 [25:11<02:04,  3.58it/s]

Gaps (ex-reports):  94%|█████████▍| 6667/7111 [25:11<01:52,  3.94it/s]

Gaps (ex-reports):  94%|█████████▍| 6668/7111 [25:11<01:46,  4.17it/s]

Gaps (ex-reports):  94%|█████████▍| 6669/7111 [25:12<01:41,  4.36it/s]

Gaps (ex-reports):  94%|█████████▍| 6670/7111 [25:12<01:36,  4.57it/s]

Gaps (ex-reports):  94%|█████████▍| 6671/7111 [25:12<01:33,  4.73it/s]

Gaps (ex-reports):  94%|█████████▍| 6672/7111 [25:12<01:32,  4.76it/s]

Gaps (ex-reports):  94%|█████████▍| 6673/7111 [25:12<01:30,  4.86it/s]

Gaps (ex-reports):  94%|█████████▍| 6674/7111 [25:13<01:29,  4.88it/s]

Gaps (ex-reports):  94%|█████████▍| 6675/7111 [25:13<01:27,  4.96it/s]

Gaps (ex-reports):  94%|█████████▍| 6676/7111 [25:13<01:26,  5.05it/s]

Gaps (ex-reports):  94%|█████████▍| 6677/7111 [25:13<01:26,  5.03it/s]

Gaps (ex-reports):  94%|█████████▍| 6678/7111 [25:13<01:28,  4.92it/s]

Gaps (ex-reports):  94%|█████████▍| 6679/7111 [25:14<01:26,  4.98it/s]

Gaps (ex-reports):  94%|█████████▍| 6680/7111 [25:14<01:27,  4.93it/s]

Gaps (ex-reports):  94%|█████████▍| 6681/7111 [25:14<01:28,  4.86it/s]

Gaps (ex-reports):  94%|█████████▍| 6682/7111 [25:14<01:28,  4.87it/s]

Gaps (ex-reports):  94%|█████████▍| 6683/7111 [25:14<01:26,  4.96it/s]

Gaps (ex-reports):  94%|█████████▍| 6684/7111 [25:15<01:27,  4.90it/s]

Gaps (ex-reports):  94%|█████████▍| 6685/7111 [25:15<01:27,  4.89it/s]

Gaps (ex-reports):  94%|█████████▍| 6686/7111 [25:15<01:27,  4.88it/s]

Gaps (ex-reports):  94%|█████████▍| 6687/7111 [25:15<01:25,  4.94it/s]

Gaps (ex-reports):  94%|█████████▍| 6688/7111 [25:15<01:27,  4.83it/s]

Gaps (ex-reports):  94%|█████████▍| 6689/7111 [25:16<01:28,  4.78it/s]

Gaps (ex-reports):  94%|█████████▍| 6690/7111 [25:16<01:25,  4.90it/s]

Gaps (ex-reports):  94%|█████████▍| 6691/7111 [25:16<01:25,  4.92it/s]

Gaps (ex-reports):  94%|█████████▍| 6692/7111 [25:16<01:26,  4.83it/s]

Gaps (ex-reports):  94%|█████████▍| 6693/7111 [25:17<01:35,  4.40it/s]

Gaps (ex-reports):  94%|█████████▍| 6694/7111 [25:17<01:31,  4.54it/s]

Gaps (ex-reports):  94%|█████████▍| 6695/7111 [25:17<01:30,  4.62it/s]

Gaps (ex-reports):  94%|█████████▍| 6696/7111 [25:17<01:28,  4.66it/s]

Gaps (ex-reports):  94%|█████████▍| 6697/7111 [25:17<01:27,  4.73it/s]

Gaps (ex-reports):  94%|█████████▍| 6698/7111 [25:18<01:27,  4.73it/s]

Gaps (ex-reports):  94%|█████████▍| 6699/7111 [25:18<01:25,  4.80it/s]

Gaps (ex-reports):  94%|█████████▍| 6700/7111 [25:18<01:23,  4.90it/s]

Gaps (ex-reports):  94%|█████████▍| 6701/7111 [25:18<01:22,  4.96it/s]

Gaps (ex-reports):  94%|█████████▍| 6702/7111 [25:18<01:20,  5.07it/s]

Gaps (ex-reports):  94%|█████████▍| 6703/7111 [25:19<01:23,  4.90it/s]

Gaps (ex-reports):  94%|█████████▍| 6704/7111 [25:19<01:23,  4.86it/s]

Gaps (ex-reports):  94%|█████████▍| 6705/7111 [25:19<01:23,  4.86it/s]

Gaps (ex-reports):  94%|█████████▍| 6706/7111 [25:19<01:21,  4.98it/s]

Gaps (ex-reports):  94%|█████████▍| 6707/7111 [25:19<01:23,  4.83it/s]

Gaps (ex-reports):  94%|█████████▍| 6708/7111 [25:20<01:22,  4.87it/s]

Gaps (ex-reports):  94%|█████████▍| 6709/7111 [25:20<01:22,  4.86it/s]

Gaps (ex-reports):  94%|█████████▍| 6710/7111 [25:20<01:22,  4.86it/s]

Gaps (ex-reports):  94%|█████████▍| 6711/7111 [25:20<01:37,  4.12it/s]

Gaps (ex-reports):  94%|█████████▍| 6712/7111 [25:21<01:31,  4.36it/s]

Gaps (ex-reports):  94%|█████████▍| 6713/7111 [25:21<01:28,  4.48it/s]

Gaps (ex-reports):  94%|█████████▍| 6714/7111 [25:21<01:25,  4.65it/s]

Gaps (ex-reports):  94%|█████████▍| 6715/7111 [25:22<02:12,  2.98it/s]

Gaps (ex-reports):  94%|█████████▍| 6716/7111 [25:22<01:56,  3.39it/s]

Gaps (ex-reports):  94%|█████████▍| 6717/7111 [25:22<01:44,  3.76it/s]

Gaps (ex-reports):  94%|█████████▍| 6718/7111 [25:22<01:36,  4.06it/s]

Gaps (ex-reports):  94%|█████████▍| 6719/7111 [25:22<01:32,  4.23it/s]

Gaps (ex-reports):  95%|█████████▍| 6720/7111 [25:23<01:27,  4.46it/s]

Gaps (ex-reports):  95%|█████████▍| 6721/7111 [25:23<01:26,  4.52it/s]

Gaps (ex-reports):  95%|█████████▍| 6722/7111 [25:23<01:23,  4.68it/s]

Gaps (ex-reports):  95%|█████████▍| 6723/7111 [25:23<01:21,  4.78it/s]

Gaps (ex-reports):  95%|█████████▍| 6724/7111 [25:23<01:20,  4.78it/s]

Gaps (ex-reports):  95%|█████████▍| 6725/7111 [25:24<02:12,  2.91it/s]

Gaps (ex-reports):  95%|█████████▍| 6726/7111 [25:24<01:56,  3.31it/s]

Gaps (ex-reports):  95%|█████████▍| 6727/7111 [25:24<01:45,  3.65it/s]

Gaps (ex-reports):  95%|█████████▍| 6728/7111 [25:25<01:37,  3.92it/s]

Gaps (ex-reports):  95%|█████████▍| 6729/7111 [25:25<01:31,  4.17it/s]

Gaps (ex-reports):  95%|█████████▍| 6730/7111 [25:25<01:26,  4.41it/s]

Gaps (ex-reports):  95%|█████████▍| 6731/7111 [25:25<01:25,  4.45it/s]

Gaps (ex-reports):  95%|█████████▍| 6732/7111 [25:25<01:22,  4.58it/s]

Gaps (ex-reports):  95%|█████████▍| 6733/7111 [25:26<01:21,  4.65it/s]

Gaps (ex-reports):  95%|█████████▍| 6734/7111 [25:26<01:20,  4.68it/s]

Gaps (ex-reports):  95%|█████████▍| 6735/7111 [25:26<01:18,  4.81it/s]

Gaps (ex-reports):  95%|█████████▍| 6736/7111 [25:26<01:18,  4.76it/s]

Gaps (ex-reports):  95%|█████████▍| 6737/7111 [25:26<01:18,  4.79it/s]

Gaps (ex-reports):  95%|█████████▍| 6738/7111 [25:27<01:17,  4.82it/s]

Gaps (ex-reports):  95%|█████████▍| 6739/7111 [25:27<01:17,  4.83it/s]

Gaps (ex-reports):  95%|█████████▍| 6740/7111 [25:27<01:15,  4.92it/s]

Gaps (ex-reports):  95%|█████████▍| 6741/7111 [25:27<01:15,  4.87it/s]

Gaps (ex-reports):  95%|█████████▍| 6742/7111 [25:28<01:15,  4.86it/s]

Gaps (ex-reports):  95%|█████████▍| 6743/7111 [25:28<01:16,  4.84it/s]

Gaps (ex-reports):  95%|█████████▍| 6744/7111 [25:28<01:16,  4.81it/s]

Gaps (ex-reports):  95%|█████████▍| 6745/7111 [25:28<01:18,  4.69it/s]

Gaps (ex-reports):  95%|█████████▍| 6746/7111 [25:28<01:17,  4.73it/s]

Gaps (ex-reports):  95%|█████████▍| 6747/7111 [25:29<01:17,  4.72it/s]

Gaps (ex-reports):  95%|█████████▍| 6748/7111 [25:29<01:17,  4.70it/s]

Gaps (ex-reports):  95%|█████████▍| 6749/7111 [25:29<01:17,  4.70it/s]

Gaps (ex-reports):  95%|█████████▍| 6750/7111 [25:29<01:15,  4.79it/s]

Gaps (ex-reports):  95%|█████████▍| 6751/7111 [25:29<01:14,  4.84it/s]

Gaps (ex-reports):  95%|█████████▍| 6752/7111 [25:30<01:13,  4.87it/s]

Gaps (ex-reports):  95%|█████████▍| 6753/7111 [25:30<01:12,  4.91it/s]

Gaps (ex-reports):  95%|█████████▍| 6754/7111 [25:30<01:12,  4.94it/s]

Gaps (ex-reports):  95%|█████████▍| 6755/7111 [25:30<01:11,  5.01it/s]

Gaps (ex-reports):  95%|█████████▌| 6756/7111 [25:30<01:12,  4.87it/s]

Gaps (ex-reports):  95%|█████████▌| 6757/7111 [25:31<01:14,  4.78it/s]

Gaps (ex-reports):  95%|█████████▌| 6758/7111 [25:31<01:14,  4.77it/s]

Gaps (ex-reports):  95%|█████████▌| 6759/7111 [25:31<01:12,  4.87it/s]

Gaps (ex-reports):  95%|█████████▌| 6760/7111 [25:31<01:11,  4.90it/s]

Gaps (ex-reports):  95%|█████████▌| 6761/7111 [25:31<01:10,  4.97it/s]

Gaps (ex-reports):  95%|█████████▌| 6762/7111 [25:32<01:12,  4.85it/s]

Gaps (ex-reports):  95%|█████████▌| 6763/7111 [25:32<01:10,  4.94it/s]

Gaps (ex-reports):  95%|█████████▌| 6764/7111 [25:32<01:10,  4.96it/s]

Gaps (ex-reports):  95%|█████████▌| 6765/7111 [25:32<01:10,  4.93it/s]

Gaps (ex-reports):  95%|█████████▌| 6766/7111 [25:32<01:10,  4.87it/s]

Gaps (ex-reports):  95%|█████████▌| 6767/7111 [25:33<01:10,  4.91it/s]

Gaps (ex-reports):  95%|█████████▌| 6768/7111 [25:33<01:11,  4.76it/s]

Gaps (ex-reports):  95%|█████████▌| 6769/7111 [25:33<01:11,  4.82it/s]

Gaps (ex-reports):  95%|█████████▌| 6770/7111 [25:33<01:10,  4.87it/s]

Gaps (ex-reports):  95%|█████████▌| 6771/7111 [25:33<01:09,  4.88it/s]

Gaps (ex-reports):  95%|█████████▌| 6772/7111 [25:34<01:09,  4.85it/s]

Gaps (ex-reports):  95%|█████████▌| 6773/7111 [25:34<01:09,  4.84it/s]

Gaps (ex-reports):  95%|█████████▌| 6774/7111 [25:34<01:09,  4.87it/s]

Gaps (ex-reports):  95%|█████████▌| 6775/7111 [25:34<01:09,  4.86it/s]

Gaps (ex-reports):  95%|█████████▌| 6776/7111 [25:35<01:08,  4.86it/s]

Gaps (ex-reports):  95%|█████████▌| 6777/7111 [25:35<01:09,  4.81it/s]

Gaps (ex-reports):  95%|█████████▌| 6778/7111 [25:35<01:08,  4.88it/s]

Gaps (ex-reports):  95%|█████████▌| 6779/7111 [25:35<01:06,  4.98it/s]

Gaps (ex-reports):  95%|█████████▌| 6780/7111 [25:35<01:05,  5.04it/s]

Gaps (ex-reports):  95%|█████████▌| 6781/7111 [25:36<01:05,  5.05it/s]

Gaps (ex-reports):  95%|█████████▌| 6782/7111 [25:36<01:05,  4.99it/s]

Gaps (ex-reports):  95%|█████████▌| 6783/7111 [25:36<01:06,  4.93it/s]

Gaps (ex-reports):  95%|█████████▌| 6784/7111 [25:36<01:07,  4.87it/s]

Gaps (ex-reports):  95%|█████████▌| 6785/7111 [25:36<01:06,  4.88it/s]

Gaps (ex-reports):  95%|█████████▌| 6786/7111 [25:37<01:06,  4.86it/s]

Gaps (ex-reports):  95%|█████████▌| 6787/7111 [25:37<01:05,  4.95it/s]

Gaps (ex-reports):  95%|█████████▌| 6788/7111 [25:37<01:05,  4.92it/s]

Gaps (ex-reports):  95%|█████████▌| 6789/7111 [25:37<01:05,  4.89it/s]

Gaps (ex-reports):  95%|█████████▌| 6790/7111 [25:37<01:04,  4.97it/s]

Gaps (ex-reports):  95%|█████████▌| 6791/7111 [25:38<01:04,  5.00it/s]

Gaps (ex-reports):  96%|█████████▌| 6792/7111 [25:38<01:03,  4.98it/s]

Gaps (ex-reports):  96%|█████████▌| 6793/7111 [25:38<01:04,  4.94it/s]

Gaps (ex-reports):  96%|█████████▌| 6794/7111 [25:38<01:05,  4.82it/s]

Gaps (ex-reports):  96%|█████████▌| 6795/7111 [25:38<01:05,  4.83it/s]

Gaps (ex-reports):  96%|█████████▌| 6796/7111 [25:39<01:05,  4.84it/s]

Gaps (ex-reports):  96%|█████████▌| 6797/7111 [25:39<01:04,  4.85it/s]

Gaps (ex-reports):  96%|█████████▌| 6798/7111 [25:39<01:04,  4.85it/s]

Gaps (ex-reports):  96%|█████████▌| 6799/7111 [25:39<01:03,  4.91it/s]

Gaps (ex-reports):  96%|█████████▌| 6800/7111 [25:39<01:03,  4.89it/s]

Gaps (ex-reports):  96%|█████████▌| 6801/7111 [25:40<01:03,  4.86it/s]

Gaps (ex-reports):  96%|█████████▌| 6802/7111 [25:40<01:02,  4.95it/s]

Gaps (ex-reports):  96%|█████████▌| 6803/7111 [25:40<01:03,  4.84it/s]

Gaps (ex-reports):  96%|█████████▌| 6804/7111 [25:40<01:04,  4.76it/s]

Gaps (ex-reports):  96%|█████████▌| 6805/7111 [25:40<01:04,  4.76it/s]

Gaps (ex-reports):  96%|█████████▌| 6806/7111 [25:41<01:03,  4.82it/s]

Gaps (ex-reports):  96%|█████████▌| 6807/7111 [25:41<01:03,  4.80it/s]

Gaps (ex-reports):  96%|█████████▌| 6808/7111 [25:41<01:05,  4.65it/s]

Gaps (ex-reports):  96%|█████████▌| 6809/7111 [25:41<01:02,  4.82it/s]

Gaps (ex-reports):  96%|█████████▌| 6810/7111 [25:41<01:01,  4.89it/s]

Gaps (ex-reports):  96%|█████████▌| 6811/7111 [25:42<01:00,  4.95it/s]

Gaps (ex-reports):  96%|█████████▌| 6812/7111 [25:42<00:59,  5.05it/s]

Gaps (ex-reports):  96%|█████████▌| 6813/7111 [25:42<01:00,  4.94it/s]

Gaps (ex-reports):  96%|█████████▌| 6814/7111 [25:42<00:59,  4.96it/s]

Gaps (ex-reports):  96%|█████████▌| 6815/7111 [25:42<00:58,  5.03it/s]

Gaps (ex-reports):  96%|█████████▌| 6816/7111 [25:43<00:59,  4.97it/s]

Gaps (ex-reports):  96%|█████████▌| 6817/7111 [25:43<00:59,  4.94it/s]

Gaps (ex-reports):  96%|█████████▌| 6818/7111 [25:43<00:59,  4.96it/s]

Gaps (ex-reports):  96%|█████████▌| 6819/7111 [25:43<01:00,  4.83it/s]

Gaps (ex-reports):  96%|█████████▌| 6820/7111 [25:44<00:59,  4.92it/s]

Gaps (ex-reports):  96%|█████████▌| 6821/7111 [25:44<00:58,  4.96it/s]

Gaps (ex-reports):  96%|█████████▌| 6822/7111 [25:44<00:57,  5.00it/s]

Gaps (ex-reports):  96%|█████████▌| 6823/7111 [25:44<00:57,  5.00it/s]

Gaps (ex-reports):  96%|█████████▌| 6824/7111 [25:44<00:56,  5.08it/s]

Gaps (ex-reports):  96%|█████████▌| 6825/7111 [25:44<00:55,  5.11it/s]

Gaps (ex-reports):  96%|█████████▌| 6826/7111 [25:45<00:56,  5.01it/s]

Gaps (ex-reports):  96%|█████████▌| 6827/7111 [25:45<00:56,  5.06it/s]

Gaps (ex-reports):  96%|█████████▌| 6828/7111 [25:45<00:56,  4.98it/s]

Gaps (ex-reports):  96%|█████████▌| 6829/7111 [25:45<00:55,  5.05it/s]

Gaps (ex-reports):  96%|█████████▌| 6830/7111 [25:45<00:56,  4.98it/s]

Gaps (ex-reports):  96%|█████████▌| 6831/7111 [25:46<00:58,  4.76it/s]

Gaps (ex-reports):  96%|█████████▌| 6832/7111 [25:46<01:02,  4.43it/s]

Gaps (ex-reports):  96%|█████████▌| 6833/7111 [25:46<01:00,  4.61it/s]

Gaps (ex-reports):  96%|█████████▌| 6834/7111 [25:46<01:02,  4.41it/s]

Gaps (ex-reports):  96%|█████████▌| 6835/7111 [25:47<01:02,  4.45it/s]

Gaps (ex-reports):  96%|█████████▌| 6836/7111 [25:47<00:59,  4.61it/s]

Gaps (ex-reports):  96%|█████████▌| 6837/7111 [25:47<00:57,  4.78it/s]

Gaps (ex-reports):  96%|█████████▌| 6838/7111 [25:47<00:55,  4.90it/s]

Gaps (ex-reports):  96%|█████████▌| 6839/7111 [25:47<00:56,  4.81it/s]

Gaps (ex-reports):  96%|█████████▌| 6840/7111 [25:48<00:56,  4.76it/s]

Gaps (ex-reports):  96%|█████████▌| 6841/7111 [25:48<00:55,  4.87it/s]

Gaps (ex-reports):  96%|█████████▌| 6842/7111 [25:48<00:58,  4.60it/s]

Gaps (ex-reports):  96%|█████████▌| 6843/7111 [25:48<00:56,  4.72it/s]

Gaps (ex-reports):  96%|█████████▌| 6844/7111 [25:48<00:55,  4.83it/s]

Gaps (ex-reports):  96%|█████████▋| 6845/7111 [25:49<01:10,  3.76it/s]

Gaps (ex-reports):  96%|█████████▋| 6846/7111 [25:49<01:05,  4.06it/s]

Gaps (ex-reports):  96%|█████████▋| 6847/7111 [25:49<01:02,  4.25it/s]

Gaps (ex-reports):  96%|█████████▋| 6848/7111 [25:49<00:58,  4.52it/s]

Gaps (ex-reports):  96%|█████████▋| 6849/7111 [25:50<00:56,  4.62it/s]

Gaps (ex-reports):  96%|█████████▋| 6850/7111 [25:50<00:55,  4.69it/s]

Gaps (ex-reports):  96%|█████████▋| 6851/7111 [25:50<00:54,  4.75it/s]

Gaps (ex-reports):  96%|█████████▋| 6852/7111 [25:50<00:53,  4.82it/s]

Gaps (ex-reports):  96%|█████████▋| 6853/7111 [25:51<00:53,  4.82it/s]

Gaps (ex-reports):  96%|█████████▋| 6854/7111 [25:51<00:53,  4.77it/s]

Gaps (ex-reports):  96%|█████████▋| 6855/7111 [25:51<00:52,  4.84it/s]

Gaps (ex-reports):  96%|█████████▋| 6856/7111 [25:51<00:51,  4.96it/s]

Gaps (ex-reports):  96%|█████████▋| 6857/7111 [25:51<00:52,  4.86it/s]

Gaps (ex-reports):  96%|█████████▋| 6858/7111 [25:52<00:52,  4.84it/s]

Gaps (ex-reports):  96%|█████████▋| 6859/7111 [25:52<00:51,  4.87it/s]

Gaps (ex-reports):  96%|█████████▋| 6860/7111 [25:52<00:50,  4.97it/s]

Gaps (ex-reports):  96%|█████████▋| 6861/7111 [25:52<00:49,  5.06it/s]

Gaps (ex-reports):  96%|█████████▋| 6862/7111 [25:52<00:50,  4.98it/s]

Gaps (ex-reports):  97%|█████████▋| 6863/7111 [25:53<01:42,  2.41it/s]

Gaps (ex-reports):  97%|█████████▋| 6864/7111 [25:53<01:27,  2.82it/s]

Gaps (ex-reports):  97%|█████████▋| 6865/7111 [25:54<01:17,  3.18it/s]

Gaps (ex-reports):  97%|█████████▋| 6866/7111 [25:54<01:09,  3.53it/s]

Gaps (ex-reports):  97%|█████████▋| 6867/7111 [25:54<01:03,  3.87it/s]

Gaps (ex-reports):  97%|█████████▋| 6868/7111 [25:54<00:59,  4.10it/s]

Gaps (ex-reports):  97%|█████████▋| 6869/7111 [25:55<00:56,  4.29it/s]

Gaps (ex-reports):  97%|█████████▋| 6870/7111 [25:55<00:53,  4.51it/s]

Gaps (ex-reports):  97%|█████████▋| 6871/7111 [25:55<00:50,  4.72it/s]

Gaps (ex-reports):  97%|█████████▋| 6872/7111 [25:55<00:51,  4.63it/s]

Gaps (ex-reports):  97%|█████████▋| 6873/7111 [25:55<00:49,  4.81it/s]

Gaps (ex-reports):  97%|█████████▋| 6874/7111 [25:56<00:48,  4.93it/s]

Gaps (ex-reports):  97%|█████████▋| 6875/7111 [25:56<00:48,  4.85it/s]

Gaps (ex-reports):  97%|█████████▋| 6876/7111 [25:56<00:49,  4.74it/s]

Gaps (ex-reports):  97%|█████████▋| 6877/7111 [25:56<00:49,  4.76it/s]

Gaps (ex-reports):  97%|█████████▋| 6878/7111 [25:56<00:47,  4.90it/s]

Gaps (ex-reports):  97%|█████████▋| 6879/7111 [25:57<00:47,  4.94it/s]

Gaps (ex-reports):  97%|█████████▋| 6880/7111 [25:57<00:47,  4.85it/s]

Gaps (ex-reports):  97%|█████████▋| 6881/7111 [25:57<00:46,  4.95it/s]

Gaps (ex-reports):  97%|█████████▋| 6882/7111 [25:57<00:45,  5.01it/s]

Gaps (ex-reports):  97%|█████████▋| 6883/7111 [25:57<00:45,  4.99it/s]

Gaps (ex-reports):  97%|█████████▋| 6884/7111 [25:58<00:45,  4.99it/s]

Gaps (ex-reports):  97%|█████████▋| 6885/7111 [25:58<00:44,  5.03it/s]

Gaps (ex-reports):  97%|█████████▋| 6886/7111 [25:58<00:45,  4.99it/s]

Gaps (ex-reports):  97%|█████████▋| 6887/7111 [25:58<00:46,  4.84it/s]

Gaps (ex-reports):  97%|█████████▋| 6888/7111 [25:58<00:46,  4.82it/s]

Gaps (ex-reports):  97%|█████████▋| 6889/7111 [25:59<00:45,  4.89it/s]

Gaps (ex-reports):  97%|█████████▋| 6890/7111 [25:59<00:44,  4.92it/s]

Gaps (ex-reports):  97%|█████████▋| 6891/7111 [25:59<00:44,  4.94it/s]

Gaps (ex-reports):  97%|█████████▋| 6892/7111 [25:59<00:44,  4.87it/s]

Gaps (ex-reports):  97%|█████████▋| 6893/7111 [25:59<00:44,  4.88it/s]

Gaps (ex-reports):  97%|█████████▋| 6894/7111 [26:00<00:44,  4.89it/s]

Gaps (ex-reports):  97%|█████████▋| 6895/7111 [26:00<00:44,  4.83it/s]

Gaps (ex-reports):  97%|█████████▋| 6896/7111 [26:00<00:44,  4.87it/s]

Gaps (ex-reports):  97%|█████████▋| 6897/7111 [26:00<00:44,  4.82it/s]

Gaps (ex-reports):  97%|█████████▋| 6898/7111 [26:00<00:44,  4.83it/s]

Gaps (ex-reports):  97%|█████████▋| 6899/7111 [26:01<00:44,  4.80it/s]

Gaps (ex-reports):  97%|█████████▋| 6900/7111 [26:01<00:43,  4.80it/s]

Gaps (ex-reports):  97%|█████████▋| 6901/7111 [26:01<00:43,  4.84it/s]

Gaps (ex-reports):  97%|█████████▋| 6902/7111 [26:01<00:43,  4.83it/s]

Gaps (ex-reports):  97%|█████████▋| 6903/7111 [26:01<00:42,  4.92it/s]

Gaps (ex-reports):  97%|█████████▋| 6904/7111 [26:02<00:42,  4.91it/s]

Gaps (ex-reports):  97%|█████████▋| 6905/7111 [26:02<00:42,  4.81it/s]

Gaps (ex-reports):  97%|█████████▋| 6906/7111 [26:02<00:42,  4.83it/s]

Gaps (ex-reports):  97%|█████████▋| 6907/7111 [26:02<00:41,  4.91it/s]

Gaps (ex-reports):  97%|█████████▋| 6908/7111 [26:02<00:42,  4.81it/s]

Gaps (ex-reports):  97%|█████████▋| 6909/7111 [26:03<00:41,  4.82it/s]

Gaps (ex-reports):  97%|█████████▋| 6910/7111 [26:03<00:41,  4.90it/s]

Gaps (ex-reports):  97%|█████████▋| 6911/7111 [26:03<00:40,  4.88it/s]

Gaps (ex-reports):  97%|█████████▋| 6912/7111 [26:03<00:40,  4.97it/s]

Gaps (ex-reports):  97%|█████████▋| 6913/7111 [26:04<00:40,  4.84it/s]

Gaps (ex-reports):  97%|█████████▋| 6914/7111 [26:04<00:40,  4.89it/s]

Gaps (ex-reports):  97%|█████████▋| 6915/7111 [26:04<00:40,  4.87it/s]

Gaps (ex-reports):  97%|█████████▋| 6916/7111 [26:05<02:00,  1.62it/s]

Gaps (ex-reports):  97%|█████████▋| 6917/7111 [26:06<01:35,  2.03it/s]

Gaps (ex-reports):  97%|█████████▋| 6918/7111 [26:06<01:18,  2.47it/s]

Gaps (ex-reports):  97%|█████████▋| 6919/7111 [26:06<01:05,  2.92it/s]

Gaps (ex-reports):  97%|█████████▋| 6920/7111 [26:06<00:57,  3.32it/s]

Gaps (ex-reports):  97%|█████████▋| 6921/7111 [26:07<00:51,  3.66it/s]

Gaps (ex-reports):  97%|█████████▋| 6922/7111 [26:07<00:48,  3.89it/s]

Gaps (ex-reports):  97%|█████████▋| 6923/7111 [26:07<00:45,  4.16it/s]

Gaps (ex-reports):  97%|█████████▋| 6924/7111 [26:07<00:42,  4.36it/s]

Gaps (ex-reports):  97%|█████████▋| 6925/7111 [26:07<00:41,  4.48it/s]

Gaps (ex-reports):  97%|█████████▋| 6926/7111 [26:08<00:39,  4.68it/s]

Gaps (ex-reports):  97%|█████████▋| 6927/7111 [26:08<00:38,  4.77it/s]

Gaps (ex-reports):  97%|█████████▋| 6928/7111 [26:08<00:38,  4.76it/s]

Gaps (ex-reports):  97%|█████████▋| 6929/7111 [26:08<00:37,  4.80it/s]

Gaps (ex-reports):  97%|█████████▋| 6930/7111 [26:08<00:38,  4.75it/s]

Gaps (ex-reports):  97%|█████████▋| 6931/7111 [26:09<00:38,  4.65it/s]

Gaps (ex-reports):  97%|█████████▋| 6932/7111 [26:09<00:37,  4.78it/s]

Gaps (ex-reports):  97%|█████████▋| 6933/7111 [26:09<00:37,  4.77it/s]

Gaps (ex-reports):  98%|█████████▊| 6934/7111 [26:09<00:36,  4.89it/s]

Gaps (ex-reports):  98%|█████████▊| 6935/7111 [26:09<00:36,  4.80it/s]

Gaps (ex-reports):  98%|█████████▊| 6936/7111 [26:10<00:35,  4.87it/s]

Gaps (ex-reports):  98%|█████████▊| 6937/7111 [26:10<00:35,  4.87it/s]

Gaps (ex-reports):  98%|█████████▊| 6938/7111 [26:10<00:34,  4.99it/s]

Gaps (ex-reports):  98%|█████████▊| 6939/7111 [26:10<00:35,  4.90it/s]

Gaps (ex-reports):  98%|█████████▊| 6940/7111 [26:10<00:35,  4.87it/s]

Gaps (ex-reports):  98%|█████████▊| 6941/7111 [26:11<00:36,  4.63it/s]

Gaps (ex-reports):  98%|█████████▊| 6942/7111 [26:11<00:36,  4.64it/s]

Gaps (ex-reports):  98%|█████████▊| 6943/7111 [26:11<00:36,  4.64it/s]

Gaps (ex-reports):  98%|█████████▊| 6944/7111 [26:11<00:35,  4.70it/s]

Gaps (ex-reports):  98%|█████████▊| 6945/7111 [26:12<00:34,  4.75it/s]

Gaps (ex-reports):  98%|█████████▊| 6946/7111 [26:12<00:34,  4.83it/s]

Gaps (ex-reports):  98%|█████████▊| 6947/7111 [26:12<00:34,  4.78it/s]

Gaps (ex-reports):  98%|█████████▊| 6948/7111 [26:12<00:33,  4.84it/s]

Gaps (ex-reports):  98%|█████████▊| 6949/7111 [26:12<00:33,  4.77it/s]

Gaps (ex-reports):  98%|█████████▊| 6950/7111 [26:13<00:32,  4.93it/s]

Gaps (ex-reports):  98%|█████████▊| 6951/7111 [26:13<00:33,  4.78it/s]

Gaps (ex-reports):  98%|█████████▊| 6952/7111 [26:13<00:33,  4.73it/s]

Gaps (ex-reports):  98%|█████████▊| 6953/7111 [26:13<00:32,  4.81it/s]

Gaps (ex-reports):  98%|█████████▊| 6954/7111 [26:13<00:32,  4.85it/s]

Gaps (ex-reports):  98%|█████████▊| 6955/7111 [26:14<00:31,  4.94it/s]

Gaps (ex-reports):  98%|█████████▊| 6956/7111 [26:14<00:31,  4.89it/s]

Gaps (ex-reports):  98%|█████████▊| 6957/7111 [26:14<00:32,  4.71it/s]

Gaps (ex-reports):  98%|█████████▊| 6958/7111 [26:14<00:32,  4.70it/s]

Gaps (ex-reports):  98%|█████████▊| 6959/7111 [26:14<00:32,  4.72it/s]

Gaps (ex-reports):  98%|█████████▊| 6960/7111 [26:15<00:32,  4.67it/s]

Gaps (ex-reports):  98%|█████████▊| 6961/7111 [26:15<00:31,  4.80it/s]

Gaps (ex-reports):  98%|█████████▊| 6962/7111 [26:15<00:34,  4.35it/s]

Gaps (ex-reports):  98%|█████████▊| 6963/7111 [26:15<00:34,  4.32it/s]

Gaps (ex-reports):  98%|█████████▊| 6964/7111 [26:16<00:32,  4.46it/s]

Gaps (ex-reports):  98%|█████████▊| 6965/7111 [26:16<00:31,  4.63it/s]

Gaps (ex-reports):  98%|█████████▊| 6966/7111 [26:16<00:30,  4.72it/s]

Gaps (ex-reports):  98%|█████████▊| 6967/7111 [26:16<00:31,  4.61it/s]

Gaps (ex-reports):  98%|█████████▊| 6968/7111 [26:16<00:30,  4.72it/s]

Gaps (ex-reports):  98%|█████████▊| 6969/7111 [26:17<00:30,  4.66it/s]

Gaps (ex-reports):  98%|█████████▊| 6970/7111 [26:17<00:31,  4.53it/s]

Gaps (ex-reports):  98%|█████████▊| 6971/7111 [26:17<00:30,  4.64it/s]

Gaps (ex-reports):  98%|█████████▊| 6972/7111 [26:17<00:28,  4.80it/s]

Gaps (ex-reports):  98%|█████████▊| 6973/7111 [26:17<00:28,  4.92it/s]

Gaps (ex-reports):  98%|█████████▊| 6974/7111 [26:18<00:27,  4.90it/s]

Gaps (ex-reports):  98%|█████████▊| 6975/7111 [26:18<00:27,  4.94it/s]

Gaps (ex-reports):  98%|█████████▊| 6976/7111 [26:18<00:27,  4.87it/s]

Gaps (ex-reports):  98%|█████████▊| 6977/7111 [26:18<00:27,  4.91it/s]

Gaps (ex-reports):  98%|█████████▊| 6978/7111 [26:18<00:26,  4.99it/s]

Gaps (ex-reports):  98%|█████████▊| 6979/7111 [26:19<00:26,  4.95it/s]

Gaps (ex-reports):  98%|█████████▊| 6980/7111 [26:19<00:25,  5.05it/s]

Gaps (ex-reports):  98%|█████████▊| 6981/7111 [26:19<00:25,  5.04it/s]

Gaps (ex-reports):  98%|█████████▊| 6982/7111 [26:19<00:25,  5.01it/s]

Gaps (ex-reports):  98%|█████████▊| 6983/7111 [26:19<00:25,  4.95it/s]

Gaps (ex-reports):  98%|█████████▊| 6984/7111 [26:20<00:26,  4.80it/s]

Gaps (ex-reports):  98%|█████████▊| 6985/7111 [26:20<00:26,  4.84it/s]

Gaps (ex-reports):  98%|█████████▊| 6986/7111 [26:20<00:25,  4.96it/s]

Gaps (ex-reports):  98%|█████████▊| 6987/7111 [26:20<00:24,  5.00it/s]

Gaps (ex-reports):  98%|█████████▊| 6988/7111 [26:20<00:24,  4.95it/s]

Gaps (ex-reports):  98%|█████████▊| 6989/7111 [26:21<00:25,  4.84it/s]

Gaps (ex-reports):  98%|█████████▊| 6990/7111 [26:21<00:26,  4.61it/s]

Gaps (ex-reports):  98%|█████████▊| 6991/7111 [26:21<00:24,  4.81it/s]

Gaps (ex-reports):  98%|█████████▊| 6992/7111 [26:21<00:24,  4.76it/s]

Gaps (ex-reports):  98%|█████████▊| 6993/7111 [26:22<00:24,  4.81it/s]

Gaps (ex-reports):  98%|█████████▊| 6994/7111 [26:22<00:23,  4.93it/s]

Gaps (ex-reports):  98%|█████████▊| 6995/7111 [26:22<00:23,  4.94it/s]

Gaps (ex-reports):  98%|█████████▊| 6996/7111 [26:22<00:23,  4.90it/s]

Gaps (ex-reports):  98%|█████████▊| 6997/7111 [26:22<00:23,  4.81it/s]

Gaps (ex-reports):  98%|█████████▊| 6998/7111 [26:23<00:23,  4.88it/s]

Gaps (ex-reports):  98%|█████████▊| 6999/7111 [26:23<00:22,  4.95it/s]

Gaps (ex-reports):  98%|█████████▊| 7000/7111 [26:23<00:22,  4.90it/s]

Gaps (ex-reports):  98%|█████████▊| 7001/7111 [26:23<00:22,  4.80it/s]

Gaps (ex-reports):  98%|█████████▊| 7002/7111 [26:23<00:22,  4.86it/s]

Gaps (ex-reports):  98%|█████████▊| 7003/7111 [26:24<00:21,  5.00it/s]

Gaps (ex-reports):  98%|█████████▊| 7004/7111 [26:24<00:21,  4.99it/s]

Gaps (ex-reports):  99%|█████████▊| 7005/7111 [26:24<00:21,  4.93it/s]

Gaps (ex-reports):  99%|█████████▊| 7006/7111 [26:24<00:21,  4.85it/s]

Gaps (ex-reports):  99%|█████████▊| 7007/7111 [26:24<00:21,  4.77it/s]

Gaps (ex-reports):  99%|█████████▊| 7008/7111 [26:25<00:21,  4.83it/s]

Gaps (ex-reports):  99%|█████████▊| 7009/7111 [26:25<00:20,  4.88it/s]

Gaps (ex-reports):  99%|█████████▊| 7010/7111 [26:25<00:20,  4.87it/s]

Gaps (ex-reports):  99%|█████████▊| 7011/7111 [26:25<00:20,  4.83it/s]

Gaps (ex-reports):  99%|█████████▊| 7012/7111 [26:25<00:20,  4.88it/s]

Gaps (ex-reports):  99%|█████████▊| 7013/7111 [26:26<00:20,  4.76it/s]

Gaps (ex-reports):  99%|█████████▊| 7014/7111 [26:26<00:20,  4.85it/s]

Gaps (ex-reports):  99%|█████████▊| 7015/7111 [26:26<00:19,  4.89it/s]

Gaps (ex-reports):  99%|█████████▊| 7016/7111 [26:26<00:19,  4.85it/s]

Gaps (ex-reports):  99%|█████████▊| 7017/7111 [26:26<00:19,  4.82it/s]

Gaps (ex-reports):  99%|█████████▊| 7018/7111 [26:27<00:18,  4.91it/s]

Gaps (ex-reports):  99%|█████████▊| 7019/7111 [26:27<00:19,  4.83it/s]

Gaps (ex-reports):  99%|█████████▊| 7020/7111 [26:27<00:18,  4.94it/s]

Gaps (ex-reports):  99%|█████████▊| 7021/7111 [26:27<00:18,  4.90it/s]

Gaps (ex-reports):  99%|█████████▊| 7022/7111 [26:27<00:18,  4.93it/s]

Gaps (ex-reports):  99%|█████████▉| 7023/7111 [26:28<00:17,  4.98it/s]

Gaps (ex-reports):  99%|█████████▉| 7024/7111 [26:28<00:17,  4.88it/s]

Gaps (ex-reports):  99%|█████████▉| 7025/7111 [26:28<00:20,  4.16it/s]

Gaps (ex-reports):  99%|█████████▉| 7026/7111 [26:28<00:19,  4.43it/s]

Gaps (ex-reports):  99%|█████████▉| 7027/7111 [26:29<00:18,  4.62it/s]

Gaps (ex-reports):  99%|█████████▉| 7028/7111 [26:29<00:17,  4.69it/s]

Gaps (ex-reports):  99%|█████████▉| 7029/7111 [26:29<00:17,  4.70it/s]

Gaps (ex-reports):  99%|█████████▉| 7030/7111 [26:29<00:17,  4.62it/s]

Gaps (ex-reports):  99%|█████████▉| 7031/7111 [26:29<00:16,  4.78it/s]

Gaps (ex-reports):  99%|█████████▉| 7032/7111 [26:30<00:16,  4.84it/s]

Gaps (ex-reports):  99%|█████████▉| 7033/7111 [26:30<00:15,  4.92it/s]

Gaps (ex-reports):  99%|█████████▉| 7034/7111 [26:30<00:15,  5.00it/s]

Gaps (ex-reports):  99%|█████████▉| 7035/7111 [26:30<00:15,  5.03it/s]

Gaps (ex-reports):  99%|█████████▉| 7036/7111 [26:30<00:14,  5.01it/s]

Gaps (ex-reports):  99%|█████████▉| 7037/7111 [26:31<00:14,  5.07it/s]

Gaps (ex-reports):  99%|█████████▉| 7038/7111 [26:31<00:14,  5.11it/s]

Gaps (ex-reports):  99%|█████████▉| 7039/7111 [26:31<00:14,  5.14it/s]

Gaps (ex-reports):  99%|█████████▉| 7040/7111 [26:31<00:13,  5.13it/s]

Gaps (ex-reports):  99%|█████████▉| 7041/7111 [26:31<00:13,  5.03it/s]

Gaps (ex-reports):  99%|█████████▉| 7042/7111 [26:32<00:13,  4.95it/s]

Gaps (ex-reports):  99%|█████████▉| 7043/7111 [26:32<00:14,  4.82it/s]

Gaps (ex-reports):  99%|█████████▉| 7044/7111 [26:32<00:13,  4.91it/s]

Gaps (ex-reports):  99%|█████████▉| 7045/7111 [26:32<00:13,  4.94it/s]

Gaps (ex-reports):  99%|█████████▉| 7046/7111 [26:32<00:13,  5.00it/s]

Gaps (ex-reports):  99%|█████████▉| 7047/7111 [26:33<00:14,  4.53it/s]

Gaps (ex-reports):  99%|█████████▉| 7048/7111 [26:33<00:14,  4.48it/s]

Gaps (ex-reports):  99%|█████████▉| 7049/7111 [26:33<00:13,  4.65it/s]

Gaps (ex-reports):  99%|█████████▉| 7050/7111 [26:33<00:12,  4.79it/s]

Gaps (ex-reports):  99%|█████████▉| 7051/7111 [26:34<00:12,  4.81it/s]

Gaps (ex-reports):  99%|█████████▉| 7052/7111 [26:34<00:12,  4.90it/s]

Gaps (ex-reports):  99%|█████████▉| 7053/7111 [26:34<00:11,  4.88it/s]

Gaps (ex-reports):  99%|█████████▉| 7054/7111 [26:34<00:11,  4.93it/s]

Gaps (ex-reports):  99%|█████████▉| 7055/7111 [26:34<00:11,  4.94it/s]

Gaps (ex-reports):  99%|█████████▉| 7056/7111 [26:35<00:11,  4.99it/s]

Gaps (ex-reports):  99%|█████████▉| 7057/7111 [26:35<00:10,  4.96it/s]

Gaps (ex-reports):  99%|█████████▉| 7058/7111 [26:35<00:10,  4.91it/s]

Gaps (ex-reports):  99%|█████████▉| 7059/7111 [26:35<00:10,  4.98it/s]

Gaps (ex-reports):  99%|█████████▉| 7060/7111 [26:35<00:10,  4.84it/s]

Gaps (ex-reports):  99%|█████████▉| 7061/7111 [26:36<00:10,  4.69it/s]

Gaps (ex-reports):  99%|█████████▉| 7062/7111 [26:36<00:10,  4.81it/s]

Gaps (ex-reports):  99%|█████████▉| 7063/7111 [26:36<00:09,  4.92it/s]

Gaps (ex-reports):  99%|█████████▉| 7064/7111 [26:36<00:09,  4.94it/s]

Gaps (ex-reports):  99%|█████████▉| 7065/7111 [26:36<00:09,  4.99it/s]

Gaps (ex-reports):  99%|█████████▉| 7066/7111 [26:37<00:09,  4.94it/s]

Gaps (ex-reports):  99%|█████████▉| 7067/7111 [26:37<00:08,  5.01it/s]

Gaps (ex-reports):  99%|█████████▉| 7068/7111 [26:37<00:08,  5.03it/s]

Gaps (ex-reports):  99%|█████████▉| 7069/7111 [26:37<00:08,  4.94it/s]

Gaps (ex-reports):  99%|█████████▉| 7070/7111 [26:37<00:08,  4.87it/s]

Gaps (ex-reports):  99%|█████████▉| 7071/7111 [26:38<00:08,  4.94it/s]

Gaps (ex-reports):  99%|█████████▉| 7072/7111 [26:38<00:07,  4.92it/s]

Gaps (ex-reports):  99%|█████████▉| 7073/7111 [26:38<00:07,  4.99it/s]

Gaps (ex-reports):  99%|█████████▉| 7074/7111 [26:38<00:07,  5.04it/s]

Gaps (ex-reports):  99%|█████████▉| 7075/7111 [26:38<00:07,  4.95it/s]

Gaps (ex-reports): 100%|█████████▉| 7076/7111 [26:39<00:07,  4.83it/s]

Gaps (ex-reports): 100%|█████████▉| 7077/7111 [26:39<00:06,  4.94it/s]

Gaps (ex-reports): 100%|█████████▉| 7078/7111 [26:39<00:06,  5.01it/s]

Gaps (ex-reports): 100%|█████████▉| 7079/7111 [26:39<00:06,  4.95it/s]

Gaps (ex-reports): 100%|█████████▉| 7080/7111 [26:39<00:06,  4.87it/s]

Gaps (ex-reports): 100%|█████████▉| 7081/7111 [26:40<00:06,  4.91it/s]

Gaps (ex-reports): 100%|█████████▉| 7082/7111 [26:40<00:05,  4.96it/s]

Gaps (ex-reports): 100%|█████████▉| 7083/7111 [26:40<00:05,  4.89it/s]

Gaps (ex-reports): 100%|█████████▉| 7084/7111 [26:40<00:05,  4.89it/s]

Gaps (ex-reports): 100%|█████████▉| 7085/7111 [26:40<00:05,  4.91it/s]

Gaps (ex-reports): 100%|█████████▉| 7086/7111 [26:41<00:05,  4.97it/s]

Gaps (ex-reports): 100%|█████████▉| 7087/7111 [26:41<00:04,  4.94it/s]

Gaps (ex-reports): 100%|█████████▉| 7088/7111 [26:41<00:04,  4.77it/s]

Gaps (ex-reports): 100%|█████████▉| 7089/7111 [26:41<00:04,  4.85it/s]

Gaps (ex-reports): 100%|█████████▉| 7090/7111 [26:41<00:04,  4.88it/s]

Gaps (ex-reports): 100%|█████████▉| 7091/7111 [26:42<00:04,  4.75it/s]

Gaps (ex-reports): 100%|█████████▉| 7092/7111 [26:42<00:03,  4.84it/s]

Gaps (ex-reports): 100%|█████████▉| 7093/7111 [26:42<00:03,  4.92it/s]

Gaps (ex-reports): 100%|█████████▉| 7094/7111 [26:42<00:03,  4.96it/s]

Gaps (ex-reports): 100%|█████████▉| 7095/7111 [26:42<00:03,  4.83it/s]

Gaps (ex-reports): 100%|█████████▉| 7096/7111 [26:43<00:03,  4.60it/s]

Gaps (ex-reports): 100%|█████████▉| 7097/7111 [26:43<00:02,  4.68it/s]

Gaps (ex-reports): 100%|█████████▉| 7098/7111 [26:43<00:02,  4.66it/s]

Gaps (ex-reports): 100%|█████████▉| 7099/7111 [26:43<00:02,  4.77it/s]

Gaps (ex-reports): 100%|█████████▉| 7100/7111 [26:44<00:02,  4.87it/s]

Gaps (ex-reports): 100%|█████████▉| 7101/7111 [26:44<00:02,  4.89it/s]

Gaps (ex-reports): 100%|█████████▉| 7102/7111 [26:44<00:01,  4.83it/s]

Gaps (ex-reports): 100%|█████████▉| 7103/7111 [26:44<00:01,  4.89it/s]

Gaps (ex-reports): 100%|█████████▉| 7104/7111 [26:44<00:01,  4.95it/s]

Gaps (ex-reports): 100%|█████████▉| 7105/7111 [26:45<00:01,  4.93it/s]

Gaps (ex-reports): 100%|█████████▉| 7106/7111 [26:45<00:01,  4.99it/s]

Gaps (ex-reports): 100%|█████████▉| 7107/7111 [26:45<00:00,  4.90it/s]

Gaps (ex-reports): 100%|█████████▉| 7108/7111 [26:45<00:00,  4.84it/s]

Gaps (ex-reports): 100%|█████████▉| 7109/7111 [26:45<00:00,  4.92it/s]

Gaps (ex-reports): 100%|█████████▉| 7110/7111 [26:46<00:00,  4.89it/s]

Gaps (ex-reports): 100%|██████████| 7111/7111 [26:46<00:00,  4.92it/s]

Gaps (ex-reports): 100%|██████████| 7111/7111 [26:46<00:00,  4.43it/s]

Rows in gaps (without report days): 424620

In [45]:
sigma_daily = add_rolling_sigma_cap(
    df=df_gaps_all,
    value_col="gap",
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.95,
    min_periods=20,
)

sigma_col = "gap_sigma_20d_cap"

# Use latest available rolling sigma per ticker
std_by_ticker = (
    sigma_daily.dropna(subset=[sigma_col])
    .sort_values(["ticker", "date"])
    .groupby("ticker", as_index=False)
    .tail(1)[["ticker", sigma_col]]
    .rename(columns={sigma_col: "sigma"})
    .reset_index(drop=True)
)

print("Tickers with sigma:", len(std_by_ticker))
std_by_ticker.head()

Tickers with sigma: 6987

  ticker     sigma
0      A  0.795920
1     AA  1.466606
2   AAAU  1.215236
3   AACG  3.665603
4    AAL  1.406358

In [46]:
std_by_ticker

     ticker     sigma
0         A  0.795920
1        AA  1.466606
2      AAAU  1.215236
3      AACG  3.665603
4       AAL  1.406358
...     ...       ...
6982   ZVOL  0.507251
6983   ZVRA  0.841274
6984    ZWS  0.654181
6985   ZYBT  3.766242
6986   ZYME  0.829663

[6987 rows x 2 columns]

In [47]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    # знайдемо колонки гнучко
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"]  = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker зі скріна
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%" або "pct_vs_prev_close"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet та зберігає новий файл.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    # вихідний шлях
    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    # підготовка мапи sigma
    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)

    # запис у тимчасовий файл → атомарна заміна
    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}")
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(sigma_map, on="ticker", how="left", validate="m:1")

        # розташувати 'sigma' за бажанням
        if insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("sigma")
            idx = cols.index(insert_before)
            cols = cols[:idx] + ["sigma"] + cols[idx:]
            merged = merged[cols]
        else:
            base_cols = [c for c in merged.columns if c != "sigma"]
            merged = merged[base_cols + ["sigma"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # атомарна заміна
    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [48]:
# std_by_ticker columns: ['ticker', 'sigma']
sigma_out_path = add_sigma_by_ticker_to_parquet(
    base_path=str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    sigma_df=std_by_ticker,
    insert_before=None,
)

# Validation: output parquet must contain sigma matching std_by_ticker
check_df = pd.read_parquet(sigma_out_path, columns=["ticker", "sigma"])
if "sigma" not in check_df.columns:
    raise KeyError("Column 'sigma' is missing in parquet after merge")

file_sigma = (
    check_df.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

exp_sigma = (
    std_by_ticker.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

common = file_sigma.index.intersection(exp_sigma.index)
if len(common) == 0:
    raise ValueError("No common tickers to validate sigma between std_by_ticker and parquet")

diff = (file_sigma.loc[common] - exp_sigma.loc[common]).abs()
max_diff = float(diff.max()) if len(diff) else 0.0
print("sigma_out_path:", sigma_out_path)
print("tickers in std_by_ticker:", len(exp_sigma))
print("tickers checked in parquet:", len(common))
print("max |file_sigma - expected_sigma|:", max_diff)

▶️ START merge sigma → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000  elapsed=17.1s

[batch   10] rows=20,000,000  elapsed=34.5s

[batch   15] rows=30,000,000  elapsed=50.7s

[batch   20] rows=40,000,000  elapsed=68.2s

[batch   25] rows=50,000,000  elapsed=85.3s

[batch   30] rows=60,000,000  elapsed=102.9s

[batch   35] rows=70,000,000  elapsed=120.4s

[batch   40] rows=80,000,000  elapsed=136.8s

[batch   45] rows=90,000,000  elapsed=154.2s

[batch   50] rows=100,000,000  elapsed=171.5s

[batch   55] rows=110,000,000  elapsed=189.0s

✅ DONE rows=113,472,570 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  in 194.9s

sigma_out_path: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
tickers in std_by_ticker: 6987
tickers checked in parquet: 6986
max |file_sigma - expected_sigma|: 4.999684005690952e-07

In [49]:
peek_parquet(str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"), n=21150)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 113,472,570
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 0/21150
NaN у 'corr' (у прев'ю): 0/21150
NaN у 'beta' (у прев'ю): 0/21150

Перші рядки:

      ticker                  dt           o           h           l           c           v        date    open  prev_close  Stack% bench    corr    beta  Bench%     sigma
0          A 2026-02-26 03:59:00  121.709999  121.709999  121.709999  121.709999         3.0  2026-02-26  121.89      124.68   -2.38   IWM  0.8056  0.6776    0.08  0.795920
1          A 2026-02-26 07:21:00  122.750000  122.750000  122.750000  122.750000       200.0  2026-02-26  121.89      124.68   -1.55   IWM  0.8056  0.6776    0.23  0.795920
2          A 2026-02-26 08:26:00  121.519997  121.519997  121.519997  121.519997       189.0  2026-02-26  121.89      124.68   -2.53   IWM  0.8056  0.6776    0.25  0.795920
3          A 2026-02-26 08:41:00  120.940002  120.940002  120.820000  120.820000       200.0  2026-02-26  121.89      124.68   -3.00   IWM  0.8056  0.6776    0.28  0.795920
4          A 2026-02-26 08:42:00  120.970001  120.980003  120.820198  120.820198       400.0  2026-02-26  121.89      124.68   -2.98   IWM  0.8056  0.6776    0.24  0.795920
5          A 2026-02-26 08:45:00  120.750000  120.750000  120.750000  120.750000      1000.0  2026-02-26  121.89      124.68   -3.15   IWM  0.8056  0.6776    0.20  0.795920
6          A 2026-02-26 09:11:00  120.639999  120.750000  120.639999  120.750000      1964.0  2026-02-26  121.89      124.68   -3.24   IWM  0.8056  0.6776    0.23  0.795920
7          A 2026-02-26 09:12:00  120.779999  120.779999  120.779999  120.779999       100.0  2026-02-26  121.89      124.68   -3.13   IWM  0.8056  0.6776     NaN  0.795920
8          A 2026-02-26 09:13:00  120.940002  121.000000  120.940002  121.000000       500.0  2026-02-26  121.89      124.68   -3.00   IWM  0.8056  0.6776    0.27  0.795920
9          A 2026-02-26 09:15:00  120.750000  120.750000  118.709999  118.709999      1752.0  2026-02-26  121.89      124.68   -3.15   IWM  0.8056  0.6776    0.26  0.795920
10         A 2026-02-26 09:19:00  120.000000  120.000000  120.000000  120.000000       120.0  2026-02-26  121.89      124.68   -3.75   IWM  0.8056  0.6776    0.29  0.795920
11         A 2026-02-26 09:20:00  120.000000  120.019997  119.750000  119.750000      2721.0  2026-02-26  121.89      124.68   -3.75   IWM  0.8056  0.6776    0.31  0.795920
12         A 2026-02-26 09:21:00  119.699997  119.699997  119.699997  119.699997      2000.0  2026-02-26  121.89      124.68   -3.99   IWM  0.8056  0.6776    0.29  0.795920
13         A 2026-02-26 09:26:00  119.239998  119.239998  119.000000  119.000000       515.0  2026-02-26  121.89      124.68   -4.36   IWM  0.8056  0.6776    0.31  0.795920
14         A 2026-02-26 09:27:00  119.059998  119.059998  119.000000  119.000000       610.0  2026-02-26  121.89      124.68   -4.51   IWM  0.8056  0.6776    0.26  0.795920
15         A 2026-02-26 09:28:00  119.900002  119.900002  119.900002  119.900002       100.0  2026-02-26  121.89      124.68   -3.83   IWM  0.8056  0.6776    0.23  0.795920
16         A 2026-02-26 09:29:00  120.980003  124.019997  120.879997  121.739998      3903.0  2026-02-26  121.89      124.68   -2.97   IWM  0.8056  0.6776    0.23  0.795920
17         A 2026-02-26 09:30:00  121.889999  124.410004  119.745003  120.830002     90151.0  2026-02-26  121.89      124.68   -2.24   IWM  0.8056  0.6776    0.17  0.795920
18         A 2026-02-26 09:31:00  120.540001  121.224998  118.190002  120.355003     22628.0  2026-02-26  121.89      124.68   -3.32   IWM  0.8056  0.6776   -0.14  0.795920
19         A 2026-02-26 09:32:00  120.269997  120.775002  120.269997  120.775002     72653.0  2026-02-26  121.89      124.68   -3.54   IWM  0.8056  0.6776    0.04  0.795920
20         A 2026-02-26 09:33:00  120.775002  122.264999  120.775002  120.830002     23647.0  2026-02-26  121.89      124.68   -3.13   IWM  0.8056  0.6776    0.11  0.795920
21         A 2026-02-26 09:34:00  121.269997  121.680000  119.849998  120.014999     35952.0  2026-02-26  121.89      124.68   -2.74   IWM  0.8056  0.6776    0.12  0.795920
22         A 2026-02-26 09:35:00  120.014999  120.070000  118.382500  118.382500     33870.0  2026-02-26  121.89      124.68   -3.74   IWM  0.8056  0.6776    0.27  0.795920
23         A 2026-02-26 09:36:00  118.870003  120.199997  118.492897  120.199997     17519.0  2026-02-26  121.89      124.68   -4.66   IWM  0.8056  0.6776    0.39  0.795920
24         A 2026-02-26 09:37:00  119.839996  120.330002  119.279999  119.894997     16867.0  2026-02-26  121.89      124.68   -3.88   IWM  0.8056  0.6776    0.44  0.795920
25         A 2026-02-26 09:38:00  120.029999  120.500000  119.000000  119.445000     33710.0  2026-02-26  121.89      124.68   -3.73   IWM  0.8056  0.6776    0.53  0.795920
26         A 2026-02-26 09:39:00  119.584999  119.584999  118.610001  118.650002     13715.0  2026-02-26  121.89      124.68   -4.09   IWM  0.8056  0.6776    0.46  0.795920
27         A 2026-02-26 09:40:00  118.650002  119.385002  118.309998  119.385002      8499.0  2026-02-26  121.89      124.68   -4.84   IWM  0.8056  0.6776    0.42  0.795920
28         A 2026-02-26 09:41:00  119.169998  120.120003  119.000000  119.040001     77400.0  2026-02-26  121.89      124.68   -4.42   IWM  0.8056  0.6776    0.32  0.795920
29         A 2026-02-26 09:42:00  119.010002  119.010002  118.419998  118.669998      3613.0  2026-02-26  121.89      124.68   -4.55   IWM  0.8056  0.6776    0.32  0.795920
30         A 2026-02-26 09:43:00  118.714203  119.070000  118.669998  118.709999      5752.0  2026-02-26  121.89      124.68   -4.78   IWM  0.8056  0.6776    0.31  0.795920
31         A 2026-02-26 09:44:00  118.550003  118.760002  118.510002  118.760002       500.0  2026-02-26  121.89      124.68   -4.92   IWM  0.8056  0.6776    0.15  0.795920
32         A 2026-02-26 09:45:00  118.760002  118.779999  118.400002  118.400002      2733.0  2026-02-26  121.89      124.68   -4.75   IWM  0.8056  0.6776    0.06  0.795920
33         A 2026-02-26 09:46:00  118.730003  119.010002  118.330002  118.709999     31136.0  2026-02-26  121.89      124.68   -4.77   IWM  0.8056  0.6776   -0.10  0.795920
34         A 2026-02-26 09:47:00  118.669998  119.009903  118.470001  118.470001      9642.0  2026-02-26  121.89      124.68   -4.82   IWM  0.8056  0.6776   -0.00  0.795920
35         A 2026-02-26 09:48:00  118.470001  118.639999  118.269997  118.550003      6287.0  2026-02-26  121.89      124.68   -4.98   IWM  0.8056  0.6776   -0.03  0.795920
36         A 2026-02-26 09:49:00  118.739998  118.750000  118.290001  118.605003      7137.0  2026-02-26  121.89      124.68   -4.76   IWM  0.8056  0.6776   -0.02  0.795920
37         A 2026-02-26 09:50:00  118.459999  118.830002  118.269997  118.779999      7030.0  2026-02-26  121.89      124.68   -4.99   IWM  0.8056  0.6776    0.05  0.795920
38         A 2026-02-26 09:51:00  118.699997  119.025002  118.660004  118.705002      6040.0  2026-02-26  121.89      124.68   -4.80   IWM  0.8056  0.6776   -0.04  0.795920
39         A 2026-02-26 09:52:00  118.879997  119.150002  118.599998  118.699997     18910.0  2026-02-26  121.89      124.68   -4.65   IWM  0.8056  0.6776    0.02  0.795920
40         A 2026-02-26 09:53:00  118.699997  118.760002  118.540001  118.760002      2599.0  2026-02-26  121.89      124.68   -4.80   IWM  0.8056  0.6776   -0.02  0.795920
41         A 2026-02-26 09:54:00  118.610001  118.809998  118.599998  118.790001      3935.0  2026-02-26  121.89      124.68   -4.87   IWM  0.8056  0.6776    0.03  0.795920
42         A 2026-02-26 09:55:00  118.629997  118.910004  118.500000  118.589996      9696.0  2026-02-26  121.89      124.68   -4.85   IWM  0.8056  0.6776   -0.03  0.795920
43         A 2026-02-26 09:56:00  118.599998  118.720001  118.430000  118.595001      9715.0  2026-02-26  121.89      124.68   -4.88   IWM  0.8056  0.6776   -0.08  0.795920
44         A 2026-02-26 09:57:00  118.550003  118.739998  118.430000  118.559998      4249.0  2026-02-26  121.89      124.68   -4.92   IWM  0.8056  0.6776   -0.09  0.795920
45         A 2026-02-26 09:58:00  118.610001  118.959999  118.610001  118.800003      6108.0  2026-02-26  121.89      124.68   -4.87   IWM  0.8056  0.6776   -0.22  0.795920
46         A 2026-02-26 09:59:00  118.690002  119.120003  118.669998  119.040001     29910.0  2026-02-26  121.89      124.68   -4.80   IWM  0.8056  0.6776   -0.15  0.795920
47         A 2026-02-26 10:00:00  119.044998  119.114998  118.790001  118.870003      5414.0  2026-02-26  121.89      124.68   -4.52   IWM  0.8056  0.6776   -0.17  0.795920
48         A 2026-02-26 10:01:00  118.904999  118.904999  118.570000  118.660004      5594.0  2026-02-26  121.89      124.68   -4.63   IWM  0.8056  0.6776   -0.09  0.795920
49         A 2026-02-26 10:02:00  118.669998  118.724998  118.120003  118.485001     13831.0  2026-02-26  121.89      124.68   -4.82   IWM  0.8056  0.6776   -0.14  0.795920
50         A 2026-02-26 10:03:00  118.440002  118.660004  117.830002  117.910004     39587.0  2026-02-26  121.89      124.68   -5.00   IWM  0.8056  0.6776   -0.15  0.795920
51         A 2026-02-26 10:04:00  117.820000  118.099998  117.529099  117.750000     12595.0  2026-02-26  121.89      124.68   -5.50   IWM  0.8056  0.6776   -0.10  0.795920
52         A 2026-02-26 10:05:00  117.769997  117.800003  117.550003  117.750000      6412.0  2026-02-26  121.89      124.68   -5.54   IWM  0.8056  0.6776   -0.07  0.795920
53         A 2026-02-26 10:06:00  117.750000  118.000000  117.639999  118.000000      4999.0  2026-02-26  121.89      124.68   -5.56   IWM  0.8056  0.6776   -0.09  0.795920
54         A 2026-02-26 10:07:00  117.925003  117.989998  117.925003  117.989998       556.0  2026-02-26  121.89      124.68   -5.42   IWM  0.8056  0.6776   -0.03  0.795920
55         A 2026-02-26 10:08:00  118.014999  118.370003  117.989998  118.370003      7388.0  2026-02-26  121.89      124.68   -5.35   IWM  0.8056  0.6776   -0.16  0.795920
56         A 2026-02-26 10:09:00  118.209999  118.430000  118.139999  118.339996      7479.0  2026-02-26  121.89      124.68   -5.19   IWM  0.8056  0.6776   -0.10  0.795920
57         A 2026-02-26 10:10:00  118.410004  118.525002  118.370003  118.470001      7045.0  2026-02-26  121.89      124.68   -5.03   IWM  0.8056  0.6776   -0.15  0.795920
58         A 2026-02-26 10:11:00  118.514999  118.680000  118.514999  118.660004      4578.0  2026-02-26  121.89      124.68   -4.94   IWM  0.8056  0.6776    0.01  0.795920
59         A 2026-02-26 10:12:00  118.699997  118.699997  118.339996  118.430000      1510.0  2026-02-26  121.89      124.68   -4.80   IWM  0.8056  0.6776    0.02  0.795920
60         A 2026-02-26 10:13:00  118.410004  118.540001  118.070099  118.375000     41616.0  2026-02-26  121.89      124.68   -5.03   IWM  0.8056  0.6776   -0.18  0.795920
61         A 2026-02-26 10:14:00  118.379997  118.540001  118.330002  118.445000      6035.0  2026-02-26  121.89      124.68   -5.05   IWM  0.8056  0.6776   -0.17  0.795920
62         A 2026-02-26 10:15:00  118.309998  118.309998  118.169998  118.199997       800.0  2026-02-26  121.89      124.68   -5.11   IWM  0.8056  0.6776   -0.21  0.795920
63         A 2026-02-26 10:16:00  118.089996  118.099998  117.790001  117.794998      2660.0  2026-02-26  121.89      124.68   -5.29   IWM  0.8056  0.6776   -0.34  0.795920
64         A 2026-02-26 10:17:00  117.805000  117.805000  117.580002  117.680000      1878.0  2026-02-26  121.89      124.68   -5.51   IWM  0.8056  0.6776   -0.47  0.795920
65         A 2026-02-26 10:18:00  117.638397  117.730003  117.410004  117.730003     10975.0  2026-02-26  121.89      124.68   -5.65   IWM  0.8056  0.6776   -0.46  0.795920
66         A 2026-02-26 10:19:00  117.735001  117.820000  117.540001  117.684998      3325.0  2026-02-26  121.89      124.68   -5.57   IWM  0.8056  0.6776   -0.51  0.795920
67         A 2026-02-26 10:20:00  117.559998  117.790001  117.500000  117.684998      3465.0  2026-02-26  121.89      124.68   -5.71   IWM  0.8056  0.6776   -0.46  0.795920
68         A 2026-02-26 10:21:00  117.519997  117.519997  117.029999  117.029999      3448.0  2026-02-26  121.89      124.68   -5.74   IWM  0.8056  0.6776   -0.52  0.795920
69         A 2026-02-26 10:22:00  117.169998  117.169998  116.754997  116.827499      5713.0  2026-02-26  121.89      124.68   -6.02   IWM  0.8056  0.6776   -0.65  0.795920
70         A 2026-02-26 10:23:00  116.949997  116.970001  116.820000  116.934998      2432.0  2026-02-26  121.89      124.68   -6.20   IWM  0.8056  0.6776   -0.64  0.795920
71         A 2026-02-26 10:24:00  116.934998  117.014999  116.875000  116.940002      3782.0  2026-02-26  121.89      124.68   -6.21   IWM  0.8056  0.6776   -0.61  0.795920
72         A 2026-02-26 10:25:00  116.889999  116.889999  116.489998  116.519997      7142.0  2026-02-26  121.89      124.68   -6.25   IWM  0.8056  0.6776   -0.64  0.795920
73         A 2026-02-26 10:26:00  116.510002  116.769997  116.480003  116.684998     19128.0  2026-02-26  121.89      124.68   -6.55   IWM  0.8056  0.6776   -0.74  0.795920
74         A 2026-02-26 10:27:00  116.669998  116.805000  116.580002  116.714996      4210.0  2026-02-26  121.89      124.68   -6.42   IWM  0.8056  0.6776   -0.54  0.795920
75         A 2026-02-26 10:28:00  116.639999  116.714996  116.500000  116.592499      4593.0  2026-02-26  121.89      124.68   -6.45   IWM  0.8056  0.6776   -0.81  0.795920
76         A 2026-02-26 10:29:00  116.660004  116.760002  116.605003  116.709999      3572.0  2026-02-26  121.89      124.68   -6.43   IWM  0.8056  0.6776   -0.82  0.795920
77         A 2026-02-26 10:30:00  116.559998  116.599998  116.519997  116.599998      2952.0  2026-02-26  121.89      124.68   -6.51   IWM  0.8056  0.6776   -0.75  0.795920
78         A 2026-02-26 10:31:00  116.519997  116.889999  116.519997  116.820000      8386.0  2026-02-26  121.89      124.68   -6.54   IWM  0.8056  0.6776   -0.69  0.795920
79         A 2026-02-26 10:32:00  116.720001  116.860001  116.720001  116.839996      1740.0  2026-02-26  121.89      124.68   -6.38   IWM  0.8056  0.6776   -0.60  0.795920
80         A 2026-02-26 10:33:00  116.750000  117.070000  116.750000  117.070000      4340.0  2026-02-26  121.89      124.68   -6.36   IWM  0.8056  0.6776   -0.66  0.795920
81         A 2026-02-26 10:34:00  116.930000  117.175003  116.930000  117.095001      3150.0  2026-02-26  121.89      124.68   -6.22   IWM  0.8056  0.6776   -0.61  0.795920
82         A 2026-02-26 10:35:00  117.000000  117.000000  116.839996  116.940002      4981.0  2026-02-26  121.89      124.68   -6.16   IWM  0.8056  0.6776   -0.74  0.795920
83         A 2026-02-26 10:36:00  116.849998  116.910004  116.849998  116.910004       672.0  2026-02-26  121.89      124.68   -6.28   IWM  0.8056  0.6776   -0.57  0.795920
84         A 2026-02-26 10:37:00  116.980003  117.239998  116.910004  117.239998     19201.0  2026-02-26  121.89      124.68   -6.18   IWM  0.8056  0.6776   -0.52  0.795920
85         A 2026-02-26 10:38:00  117.260002  117.300003  117.169998  117.169998      1045.0  2026-02-26  121.89      124.68   -5.95   IWM  0.8056  0.6776   -0.42  0.795920
86         A 2026-02-26 10:39:00  117.239998  117.264999  117.110001  117.160004      1745.0  2026-02-26  121.89      124.68   -5.97   IWM  0.8056  0.6776   -0.31  0.795920
87         A 2026-02-26 10:40:00  117.099998  117.149902  116.919998  116.989998      1414.0  2026-02-26  121.89      124.68   -6.08   IWM  0.8056  0.6776   -0.27  0.795920
88         A 2026-02-26 10:41:00  117.097504  117.120003  117.044998  117.050003      1200.0  2026-02-26  121.89      124.68   -6.08   IWM  0.8056  0.6776   -0.25  0.795920
89         A 2026-02-26 10:42:00  117.068100  117.068100  116.959999  117.065002      1739.0  2026-02-26  121.89      124.68   -6.11   IWM  0.8056  0.6776   -0.20  0.795920
90         A 2026-02-26 10:43:00  117.029999  117.339996  117.029999  117.309998      7541.0  2026-02-26  121.89      124.68   -6.14   IWM  0.8056  0.6776   -0.26  0.795920
91         A 2026-02-26 10:44:00  117.324997  117.427498  117.324997  117.339996      1016.0  2026-02-26  121.89      124.68   -5.90   IWM  0.8056  0.6776   -0.22  0.795920
92         A 2026-02-26 10:45:00  117.290001  117.339996  117.279999  117.330002      3773.0  2026-02-26  121.89      124.68   -5.93   IWM  0.8056  0.6776   -0.22  0.795920
93         A 2026-02-26 10:46:00  117.330002  117.330002  117.019997  117.019997      2372.0  2026-02-26  121.89      124.68   -5.90   IWM  0.8056  0.6776   -0.11  0.795920
94         A 2026-02-26 10:47:00  117.099998  117.209999  117.099998  117.110001      7093.0  2026-02-26  121.89      124.68   -6.08   IWM  0.8056  0.6776   -0.19  0.795920
95         A 2026-02-26 10:48:00  117.099998  117.389999  117.099998  117.389999     11576.0  2026-02-26  121.89      124.68   -6.08   IWM  0.8056  0.6776   -0.11  0.795920
96         A 2026-02-26 10:49:00  117.355003  117.355003  117.260002  117.330002      1516.0  2026-02-26  121.89      124.68   -5.88   IWM  0.8056  0.6776   -0.06  0.795920
97         A 2026-02-26 10:50:00  117.260002  117.345001  117.260002  117.271698      1000.0  2026-02-26  121.89      124.68   -5.95   IWM  0.8056  0.6776   -0.05  0.795920
98         A 2026-02-26 10:51:00  117.330002  117.629997  117.300003  117.474998      9128.0  2026-02-26  121.89      124.68   -5.90   IWM  0.8056  0.6776    0.01  0.795920
99         A 2026-02-26 10:52:00  117.449997  117.724998  117.449997  117.720001      2630.0  2026-02-26  121.89      124.68   -5.80   IWM  0.8056  0.6776   -0.01  0.795920
100        A 2026-02-26 10:53:00  117.644997  117.660004  117.514198  117.660004      3688.0  2026-02-26  121.89      124.68   -5.64   IWM  0.8056  0.6776    0.16  0.795920
101        A 2026-02-26 10:54:00  117.724998  117.730003  117.699997  117.699997      1242.0  2026-02-26  121.89      124.68   -5.58   IWM  0.8056  0.6776    0.11  0.795920
102        A 2026-02-26 10:55:00  117.669998  117.699898  117.529999  117.529999      1292.0  2026-02-26  121.89      124.68   -5.62   IWM  0.8056  0.6776    0.16  0.795920
103        A 2026-02-26 10:56:00  117.510002  117.510002  117.330002  117.330002      7769.0  2026-02-26  121.89      124.68   -5.75   IWM  0.8056  0.6776    0.19  0.795920
104        A 2026-02-26 10:57:00  117.300003  117.300003  117.199997  117.209999      2952.0  2026-02-26  121.89      124.68   -5.92   IWM  0.8056  0.6776    0.11  0.795920
105        A 2026-02-26 10:58:00  117.190002  117.199997  117.150002  117.154999      4070.0  2026-02-26  121.89      124.68   -6.01   IWM  0.8056  0.6776    0.19  0.795920
106        A 2026-02-26 10:59:00  117.154999  117.620003  117.129997  117.559998      8892.0  2026-02-26  121.89      124.68   -6.04   IWM  0.8056  0.6776    0.20  0.795920
107        A 2026-02-26 11:00:00  117.519997  117.519997  117.430000  117.464996      1904.0  2026-02-26  121.89      124.68   -5.74   IWM  0.8056  0.6776    0.14  0.795920
108        A 2026-02-26 11:01:00  117.349998  117.410004  117.260002  117.260002      1218.0  2026-02-26  121.89      124.68   -5.88   IWM  0.8056  0.6776    0.20  0.795920
109        A 2026-02-26 11:02:00  117.209999  117.269997  117.169998  117.184998      3509.0  2026-02-26  121.89      124.68   -5.99   IWM  0.8056  0.6776    0.19  0.795920
110        A 2026-02-26 11:03:00  117.190002  117.190002  117.080002  117.144997      1600.0  2026-02-26  121.89      124.68   -6.01   IWM  0.8056  0.6776    0.12  0.795920
111        A 2026-02-26 11:04:00  117.080002  117.089996  116.949997  117.029999      4584.0  2026-02-26  121.89      124.68   -6.10   IWM  0.8056  0.6776    0.06  0.795920
112        A 2026-02-26 11:05:00  117.000000  117.000000  116.800003  116.805000      5441.0  2026-02-26  121.89      124.68   -6.16   IWM  0.8056  0.6776    0.07  0.795920
113        A 2026-02-26 11:06:00  116.724998  116.889999  116.629997  116.629997      3137.0  2026-02-26  121.89      124.68   -6.38   IWM  0.8056  0.6776    0.01  0.795920

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,A,2026-02-26 03:59:00,121.709999,121.709999,121.709999,121.709999,3.0,2026-02-26,121.89,124.68,-2.38,IWM,0.8056,0.6776,0.08,0.795920
1,A,2026-02-26 07:21:00,122.750000,122.750000,122.750000,122.750000,200.0,2026-02-26,121.89,124.68,-1.55,IWM,0.8056,0.6776,0.23,0.795920
2,A,2026-02-26 08:26:00,121.519997,121.519997,121.519997,121.519997,189.0,2026-02-26,121.89,124.68,-2.53,IWM,0.8056,0.6776,0.25,0.795920
3,A,2026-02-26 08:41:00,120.940002,120.940002,120.820000,120.820000,200.0,2026-02-26,121.89,124.68,-3.00,IWM,0.8056,0.6776,0.28,0.795920
4,A,2026-02-26 08:42:00,120.970001,120.980003,120.820198,120.820198,400.0,2026-02-26,121.89,124.68,-2.98,IWM,0.8056,0.6776,0.24,0.795920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,AAUC,2026-02-26 14:01:00,31.459999,31.459999,31.450001,31.450001,417.0,2026-02-26,31.40,31.54,-0.25,GDX,0.6853,0.1542,0.85,0.607204
21146,AAUC,2026-02-26 14:09:00,31.440001,31.440001,31.430000,31.430000,531.0,2026-02-26,31.40,31.54,-0.32,GDX,0.6853,0.1542,1.12,0.607204
21147,AAUC,2026-02-26 14:14:00,31.459999,31.490000,31.445000,31.450001,5076.0,2026-02-26,31.40,31.54,-0.25,GDX,0.6853,0.1542,1.22,0.607204
21148,AAUC,2026-02-26 14:15:00,31.459999,31.490000,31.459999,31.469999,956.0,2026-02-26,31.40,31.54,-0.25,GDX,0.6853,0.1542,1.19,0.607204
21149,AAUC,2026-02-26 14:17:00,31.490000,31.490000,31.490000,31.490000,100.0,2026-02-26,31.40,31.54,-0.16,GDX,0.6853,0.1542,1.17,0.607204

In [50]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
except Exception:
    pa = pq = ds = None


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    roundtrip_pandas: bool = True,   # найнадійніше для sort_values
    log_every: int = 200,
):
    """
    Rewrites input parquet into output parquet in strict physical order:
      ticker A→Z, then (date, dt) within each ticker (or dt only).
    Uses dataset scanning per ticker to avoid global in-memory sort.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")

    # Discover columns
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    has_date = ("date" in schema_names)
    has_dt   = ("dt" in schema_names)

    # get unique tickers (safe, but could be heavy; acceptable for your use-case)
    tickers_tbl = dataset.to_table(columns=["ticker"])
    tickers = sorted(pd.unique(tickers_tbl.column("ticker").to_pandas().astype(str)))
    del tickers_tbl
    gc.collect()

    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    writer = None
    total_written = 0
    t0 = time.time()

    print(f"▶ SORT: {input_path} → {output_path} | tickers={len(tickers):,} | has_date={has_date} has_dt={has_dt}")

    try:
        for i, tk in enumerate(tickers, 1):
            # Filter rows for this ticker
            filt = (ds.field("ticker") == tk)
            table = dataset.to_table(filter=filt)
            if table.num_rows == 0:
                continue

            if roundtrip_pandas:
                df = table.to_pandas()
                # Ensure date exists if needed
                if has_date:
                    # keep as-is; assume date is string 'YYYY-MM-DD'
                    pass
                elif has_dt and ("date" not in df.columns):
                    # If no date column exists, optionally derive it (not required for sort)
                    pass

                if has_date and has_dt and {"date", "dt"}.issubset(df.columns):
                    df.sort_values(["date", "dt"], kind="mergesort", inplace=True)
                elif has_dt and "dt" in df.columns:
                    df.sort_values(["dt"], kind="mergesort", inplace=True)
                else:
                    # fallback: stable sort by all columns
                    df.sort_values(list(df.columns), kind="mergesort", inplace=True)

                out_table = pa.Table.from_pandas(df, preserve_index=False)
                del df
            else:
                # Arrow-only fallback (less flexible)
                out_table = table

            if writer is None:
                writer = pq.ParquetWriter(tmp_out, out_table.schema, compression=compression)

            writer.write_table(out_table)
            total_written += out_table.num_rows

            if (i % log_every) == 0:
                print(f"  [{i:>6}/{len(tickers):,}] {tk}  written={total_written:,}  elapsed={time.time()-t0:,.1f}s")

            del table, out_table
            gc.collect()

    finally:
        if writer is not None:
            writer.close()

    # atomic replace
    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)

    print(f"✅ SORT DONE: {total_written:,} rows → {output_path} | time={time.time()-t0:,.1f}s")
    return output_path


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # використовується як batch_rows для Parquet
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,      # NEW: rewrite final sorted
) -> str:
    """
    Parquet-версія.
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.
    Працює потоково.

    NEW:
      - якщо sort_final_by_ticker=True, то фінальний output_path буде фізично
        відсортований: ticker A→Z, всередині тикера date,dt (або dt).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    batch_rows = chunksize

    # 1) write unsorted tmp parquet
    tmp_unsorted = output_path + f".tmp_unsorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_unsorted):
        os.remove(tmp_unsorted)

    pf = pq.ParquetFile(input_path)
    writer = None
    total = 0

    print(f"▶ START (Parquet): {input_path}  →  {output_path} | batch_rows≈{batch_rows:,}")

    for bi, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # гнучке визначення колонок
        names = {c.lower().strip(): c for c in df.columns}
        stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
        bench_col = names.get("bench%")
        beta_col  = names.get("beta")
        sigma_col = names.get("sigma")

        need = {
            "stack%/pct_vs_prev_close": stack_col,
            "bench%": bench_col,
            "beta": beta_col,
            "sigma": sigma_col,
        }
        missing = [k for k, v in need.items() if v is None]
        if missing:
            raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

        # приберемо старі результати, якщо були
        for col in ("t_p", "deviation", "dev_sig"):
            if col in df.columns:
                del df[col]

        # числові типи
        df[stack_col] = pd.to_numeric(df[stack_col], errors="coerce")
        df[bench_col] = pd.to_numeric(df[bench_col], errors="coerce")
        df[beta_col]  = pd.to_numeric(df[beta_col],  errors="coerce")
        df[sigma_col] = pd.to_numeric(df[sigma_col], errors="coerce")

        # обчислення
        tp  = df[stack_col] * df[beta_col]
        dev = tp - df[bench_col]
        denom = df[sigma_col].replace({0: np.nan})
        dsg = dev / denom

        # округлення
        if round_tp_dev is not None:
            tp  = tp.round(round_tp_dev)
            dev = dev.round(round_tp_dev)
        if round_devsig is not None:
            dsg = dsg.round(round_devsig)

        # додати в кінець
        df["t_p"] = tp
        df["deviation"] = dev
        df["dev_sig"] = dsg

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_unsorted, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if bi % 5 == 0:
            print(f"[batch {bi:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # 2) sort & finalize
    if sort_final_by_ticker:
        # rewrite sorted to output_path
        _write_final_sorted_alphabetical(
            tmp_unsorted,
            output_path,
            compression=compression,
            roundtrip_pandas=True,
            log_every=200,
        )
        # cleanup unsorted tmp
        try:
            os.remove(tmp_unsorted)
        except Exception:
            pass
    else:
        # atomic replace unsorted as final
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_unsorted, output_path)

    print(f"✅ DONE: {total:,} rows → {output_path} | total_time={time.time()-t0:,.1f}s")
    return output_path

In [51]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (Parquet): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\final.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=9.3s

[batch   10] rows=20,000,000  elapsed=18.7s

[batch   15] rows=30,000,000  elapsed=28.2s

[batch   20] rows=40,000,000  elapsed=37.8s

[batch   25] rows=50,000,000  elapsed=47.3s

[batch   30] rows=60,000,000  elapsed=56.9s

[batch   35] rows=70,000,000  elapsed=66.0s

[batch   40] rows=80,000,000  elapsed=75.6s

[batch   45] rows=90,000,000  elapsed=85.0s

[batch   50] rows=100,000,000  elapsed=94.7s

[batch   55] rows=110,000,000  elapsed=104.3s

▶ SORT: C:\datum-api-examples-main\OriON\CRACEN\final.parquet.tmp_unsorted_6864_1779868177 → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | tickers=7,532 | has_date=True has_dt=True

  [   200/7,532] AIFF  written=3,163,206  elapsed=227.4s

  [   400/7,532] AOSL  written=6,356,975  elapsed=463.3s

  [   600/7,532] AVES  written=9,567,336  elapsed=700.2s

  [   800/7,532] BF.B  written=12,393,060  elapsed=936.2s

  [  1000/7,532] BPRE  written=15,314,739  elapsed=1,174.1s

  [  1200/7,532] CB  written=18,137,440  elapsed=1,412.8s

  [  1400/7,532] CLMT  written=21,011,679  elapsed=1,650.8s

  [  1600/7,532] CRH  written=24,150,328  elapsed=1,889.2s

  [  1800/7,532] DDL  written=27,247,056  elapsed=2,130.0s

  [  2000/7,532] DVYE  written=30,195,708  elapsed=2,372.5s

  [  2200/7,532] EPSN  written=32,983,465  elapsed=2,619.5s

  [  2400/7,532] FCFS  written=36,143,663  elapsed=2,863.0s

  [  2600/7,532] FROG  written=38,980,397  elapsed=3,102.2s

  [  2800/7,532] GIX  written=41,758,483  elapsed=3,343.1s

  [  3000/7,532] HAKY  written=44,694,588  elapsed=3,587.6s

  [  3200/7,532] HWH  written=47,546,064  elapsed=3,827.3s

  [  3400/7,532] INDA  written=50,187,249  elapsed=4,063.9s

  [  3600/7,532] JACK  written=53,433,104  elapsed=4,299.8s

  [  3800/7,532] KOMP  written=56,188,260  elapsed=4,519.7s

  [  4000/7,532] LNKB  written=59,057,947  elapsed=4,726.5s

  [  4200/7,532] MEME  written=61,949,884  elapsed=4,928.1s

  [  4400/7,532] MSS  written=64,850,219  elapsed=5,129.5s

  [  4600/7,532] NIC  written=67,850,990  elapsed=5,321.6s

  [  4800/7,532] OBIL  written=71,066,077  elapsed=5,508.5s

  [  5000/7,532] PALI  written=74,286,480  elapsed=5,688.5s

  [  5200/7,532] PMCB  written=77,313,109  elapsed=5,869.2s

  [  5400/7,532] QNC  written=80,241,580  elapsed=6,050.7s

  [  5600/7,532] RL  written=83,437,184  elapsed=6,232.7s

  [  5800/7,532] SCHP  written=86,596,143  elapsed=6,412.5s

  [  6000/7,532] SLRC  written=89,780,571  elapsed=6,587.7s

  [  6200/7,532] SPYM  written=93,355,634  elapsed=6,762.4s

  [  6400/7,532] TCPC  written=96,357,000  elapsed=6,936.6s

  [  6600/7,532] TRIB  written=99,334,203  elapsed=7,109.6s

  [  6800/7,532] UNF  written=102,660,359  elapsed=7,284.0s

  [  7000/7,532] VIXM  written=105,892,284  elapsed=7,457.6s

  [  7200/7,532] WHD  written=109,124,374  elapsed=7,633.0s

  [  7400/7,532] XRXDW  written=111,900,175  elapsed=7,803.9s

✅ SORT DONE: 113,472,570 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | time=7,913.2s

✅ DONE: 113,472,570 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=8,032.6s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'