In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=2)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 2, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2026-04-16 00:00:00
end   = 2026-06-16 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2026-04-16
end_date_str   = 2026-06-16

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker       value
0      A    56375.62
1     AA  1575737.43
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 13134

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,market_cap',
    'active': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
tickers_df = tickers_df.dropna()

# --- крок 3: додаємо потрібні колонки у df_filtered
TICKERS = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(TICKERS):,} рядків")
TICKERS.head()

Після фільтрації залишилось: 7,232 рядків

  ticker       value                         lvl3  market_cap
0      A    56375.62  Medical Equipment & Devices     35114.0
1     AA  1575737.43              Metals & Mining     16289.0
2   AAAU   412161.29                          NaN         NaN
3   AACG       23.80                     Software        43.0
4   AADX   120874.92          Aerospace & Defense      3454.0

In [7]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [8]:
unique_lvl2 = get_unique_lvl2(TICKERS)
unique_lvl2

🔹 Знайдено 59 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Elec & Gas Marketing & Trading',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [9]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "SPY", "IBIT"],
    "Banking": ["KRE", "XLF", "SPY", "IBIT"],
    "Institutional Financial Svcs": ["XLF", "SPY", "IBIT"],
    "Insurance": ["XLF", "SPY", "IBIT"],
    "Specialty Finance": ["XLF", "SPY", "IBIT"],

    # --- Tech / Internet / Growth ---
    "Software": ["IGV", "QQQ", "IWM", "SPY"],  
    "IT Services": ["IGV", "QQQ", "IWM", "SPY"],
    "Semiconductors": ["SMH", "SOXX", "QQQ", "IWM", "SPY"],  
    "Technology Hardware": ["XLK", "QQQ", "SOXX", "IWM", "SPY"],
    "Internet Media & Services": ["QQQ", "KWEB", "IWM", "SPY"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "IWM", "SPY"],
    "Cable & Satellite": ["QQQ", "KWEB", "IWM", "SPY"],
    "Telecommunications": ["QQQ", "KWEB", "IWM", "SPY"],
    "Publishing & Broadcasting": ["QQQ", "KWEB", "IWM", "SPY"],
    "Entertainment Content": ["QQQ", "KWEB", "IWM", "SPY"],
    "Advertising & Marketing": ["QQQ", "KWEB", "IWM", "SPY"],

    # --- Industrials ---
    "Aerospace & Defense": ["ITA", "XLI", "IWM", "SPY"], 
    "Diversified Industrials": ["XLI", "SPY", "IWM"],
    "Industrial Intermediate Prod": ["XLI", "IWM", "SPY"],
    "Industrial Support Services": ["XLI", "IWM", "SPY"],
    "Engineering & Construction": ["XLI", "IWM", "SPY"],
    "Machinery": ["XLI", "IWM", "SPY"],
    "Transportation & Logistics": ["XTN", "XLI", "IWM", "SPY"],  
    "Transportation Equipment": ["XLI", "IWM", "SPY"],
    "Commercial Support Services": ["XLI", "IWM", "SPY"],
    "Containers & Packaging": ["XLI", "IWM", "SPY"],
    "Electrical Equipment": ["XLI", "QQQ", "IWM", "SPY"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["OIH", "XLE", "IWM", "SPY"],  
    "Oil & Gas Supply Chain": ["XLE", "IWM", "SPY"],
    "Elec & Gas Marketing & Trading": ["XLU", "XLE", "IWM", "SPY"],
    "Electric Utilities": ["XLU", "XLE", "IWM", "SPY"],         
    "Gas & Water Utilities": ["XLU", "IWM", "SPY"],
    "Renewable Energy": ["ICLN", "XLE", "IWM", "SPY"],           
    "Chemicals": ["XLB", "XLE", "IWM", "SPY"],                  
    "Metals & Mining": ["GDX", "XLB", "IWM", "SPY"],
    "Steel": ["SLX", "GDX", "XLB", "IWM", "SPY"],             
    "Construction Materials": ["XLB", "IWM", "SPY"],
    "Forestry, Paper & Wood Products": ["XLB", "IWM", "SPY"],

    # --- Health Care ---
    "Biotech & Pharma": ["IBB", "XBI", "QQQ", "IWM", "SPY"], 
    "Medical Equipment & Devices": ["IHI", "XLV", "IWM", "SPY"], 
    "Health Care Facilities & Svcs": ["IHF", "XLV", "IWM", "SPY"], 

    # --- Consumer Staples / Discretionary ---
    "Food": ["XLP", "SPY", "IWM"],
    "Beverages": ["XLP", "SPY", "IWM"],
    "Household Products": ["XLP", "SPY", "IWM"],
    "Tobacco & Cannabis": ["XLP", "SPY", "IWM"],
    "Retail - Consumer Staples": ["XLP", "SPY", "IWM"],
    "Wholesale - Consumer Staples": ["XLP", "SPY", "IWM"],

    "Retail - Discretionary": ["XRT", "XLY", "SPY", "IWM"], 
    "Wholesale - Discretionary": ["XLY", "SPY", "IWM"],
    "Consumer Services": ["XLY", "SPY", "IWM"],
    "Leisure Facilities & Services": ["XLY", "SPY", "IWM"],
    "Leisure Products": ["XLY", "SPY", "IWM"],
    "Apparel & Textile Products": ["XLY", "SPY", "IWM", "QQQ"],
    "Automotive": ["XLY", "SPY", "IWM", "QQQ"],
    "Home & Office Products": ["XLY", "SPY", "IWM"],
    "Home Construction": ["XHB", "IWM", "SPY"],          

    # --- Real Estate ---
    "REIT": ["VNQ", "IWM", "SPY"], 
    "Real Estate Owners & Developers": ["VNQ", "IWM", "SPY"],
    "Real Estate Services": ["VNQ", "IWM", "SPY"],
}

In [10]:
# ------------------------------------------------

In [11]:
import numpy as np
import pandas as pd


def calc_corr_beta_from_joined_gaps(df_pair: pd.DataFrame, x_col: str = "gap_x", y_col: str = "gap_y"):
    """
    Local corr/beta calculation without /calculations/corr_beta API.

    corr = Pearson(x, y)
    beta = cov(x, y) / var(y)
    """
    d = df_pair[[x_col, y_col]].copy()
    d[x_col] = pd.to_numeric(d[x_col], errors="coerce")
    d[y_col] = pd.to_numeric(d[y_col], errors="coerce")
    d = d.dropna()

    n = len(d)
    if n < 2:
        return np.nan, np.nan, n

    var_y = float(d[y_col].var(ddof=1))
    corr = float(d[x_col].corr(d[y_col]))

    if np.isnan(var_y) or var_y == 0:
        return corr, np.nan, n

    cov_xy = float(d[[x_col, y_col]].cov(ddof=1).iloc[0, 1])
    beta = cov_xy / var_y
    return corr, beta, n


def corr_beta_best_match_from_gaps(
    stock_gap_df: pd.DataFrame,
    etf_gap_df: pd.DataFrame,
    x_tickers,
    y_tickers,
    *,
    min_overlap: int = 20,
    output_path: str = None,
):
    """
    Pick best Y per X using local gaps.

    stock_gap_df: ['ticker','date','gap']
    etf_gap_df:   ['ticker','date','gap']
    """
    sx = stock_gap_df.copy()
    sy = etf_gap_df.copy()

    for df in (sx, sy):
        if not {"ticker", "date", "gap"}.issubset(df.columns):
            raise KeyError("Expected columns ['ticker','date','gap'] in gap data")
        df["ticker"] = df["ticker"].astype(str).str.upper().str.strip()
        df["date"] = pd.to_datetime(df["date"], errors="coerce").dt.strftime("%Y-%m-%d")
        df["gap"] = pd.to_numeric(df["gap"], errors="coerce")

    s_map = {t: g[["date", "gap"]].copy() for t, g in sx.groupby("ticker")}
    e_map = {t: g[["date", "gap"]].copy() for t, g in sy.groupby("ticker")}

    rows_all = []
    rows_best = []

    for x in [str(v).upper() for v in x_tickers]:
        g_x = s_map.get(x)
        if g_x is None or g_x.empty:
            continue

        best = None
        for y in [str(v).upper() for v in y_tickers]:
            g_y = e_map.get(y)
            if g_y is None or g_y.empty:
                continue

            m = g_x.merge(g_y, on="date", how="inner", suffixes=("_x", "_y")).dropna()
            corr, beta, n = calc_corr_beta_from_joined_gaps(m, x_col="gap_x", y_col="gap_y")
            if n < int(min_overlap) or pd.isna(corr):
                continue

            row = {
                "x_ticker": x,
                "y_ticker": y,
                "corr": corr,
                "beta": beta,
                "n_overlap": n,
            }
            rows_all.append(row)
            if best is None or row["corr"] > best["corr"]:
                best = row

        if best is not None:
            rows_best.append({
                "x_ticker": best["x_ticker"],
                "best_y_ticker": best["y_ticker"],
                "best_corr": best["corr"],
                "beta_with_best": best["beta"],
                "n_overlap": best["n_overlap"],
            })

    df_all = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best)

    if df_pairs.empty:
        df_pairs = pd.DataFrame(columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "n_overlap"])

    if output_path:
        df_pairs.to_csv(output_path, index=False)

    return df_all, df_pairs

In [12]:
def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
    start_date=None,
    end_date=None,
    last_n_reports=20,
    cap_q=0.95,
    min_hist_for_cap=20,
    min_overlap=20,
):
    import numpy as np
    import pandas as pd
    from concurrent.futures import ThreadPoolExecutor

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]
    if start_date is None:
        start_date = globals().get("start_date_str")
    if end_date is None:
        end_date = globals().get("end_date_str")
    if not start_date or not end_date:
        raise ValueError("Provide start_date/end_date or define start_date_str/end_date_str")
    if sector_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{sector_col}' column")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"tickers_df has no '{ticker_col}' column")

    s_date, e_date = str(start_date)[:10], str(end_date)[:10]

    def _pick_col(df, candidates):
        cols_l = {c.lower().strip(): c for c in df.columns}
        return next((cols_l[c.lower()] for c in candidates if c.lower() in cols_l), None)

    def _fetch_gap(t):
        try:
            dfg = DatumApi.data_request("/daily/gaps", {
                "ticker": t, "start_date": s_date, "end_date": e_date, "format": "json_records",
            })
            if dfg is None or dfg.empty:
                return None
            dcol = _pick_col(dfg, ["date", "move_date", "dt", "datetime", "day"])
            if dcol is None or "gap" not in dfg.columns:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(dfg[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
                "gap": pd.to_numeric(dfg["gap"], errors="coerce"),
            }).dropna()
            return out if not out.empty else None
        except Exception as ex:
            print(f"WARN gaps fail {t}: {ex}")
            return None

    def _fetch_report(t):
        try:
            rep = DatumApi.data_request("/reports", {
                "ticker": t, "start_move_date": s_date, "end_move_date": e_date,
            })
            if rep is None or rep.empty:
                return None
            dcol = _pick_col(rep, ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"])
            if dcol is None:
                return None
            out = pd.DataFrame({
                "ticker": t,
                "date": pd.to_datetime(rep[dcol], errors="coerce").dt.strftime("%Y-%m-%d"),
            }).dropna().sort_values("date").tail(int(last_n_reports))
            return out if not out.empty else None
        except Exception as ex:
            print(f"WARN reports fail {t}: {ex}")
            return None

    # ── prepare ──────────────────────────────────────────────────────────────
    df_clean = tickers_df[[ticker_col, sector_col]].drop_duplicates().copy()
    df_clean[ticker_col] = df_clean[ticker_col].astype(str).str.strip().str.upper()
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)

    stocks = sorted(df_clean[ticker_col].dropna().unique())
    etf_candidates = set(fallback_etfs)
    for sec in df_clean[sector_col].unique():
        etf_candidates.update(sector_to_etf.get(sec, fallback_etfs) or fallback_etfs)
    etf_candidates = sorted(str(x).upper() for x in etf_candidates)

    print(f"START gaps: stocks={len(stocks)} etfs={len(etf_candidates)} window={s_date}..{e_date}")

    # ── parallel fetch: all gaps + reports in one pool ────────────────────────
    all_gap_tickers = sorted(set(stocks) | set(etf_candidates))
    with ThreadPoolExecutor(max_workers=min(64, len(all_gap_tickers) + len(stocks))) as ex:
        gap_futs  = {t: ex.submit(_fetch_gap,    t) for t in all_gap_tickers}
        rep_futs  = {t: ex.submit(_fetch_report, t) for t in stocks}

    gap_res = {t: f.result() for t, f in gap_futs.items()}
    rep_res = {t: f.result() for t, f in rep_futs.items()}

    def _concat(parts, cols):
        valid = [p for p in parts if p is not None]
        return pd.concat(valid, ignore_index=True) if valid else pd.DataFrame(columns=cols)

    stock_gaps = _concat([gap_res.get(t) for t in stocks],         ["ticker", "date", "gap"])
    etf_gaps   = _concat([gap_res.get(t) for t in etf_candidates], ["ticker", "date", "gap"])
    reports    = _concat([rep_res.get(t) for t in stocks],          ["ticker", "date"]).drop_duplicates()

    # ── exclude report days ──────────────────────────────────────────────────
    if not reports.empty and not stock_gaps.empty:
        m = stock_gaps.merge(reports.assign(_rep=1), on=["ticker", "date"], how="left")
        stock_gaps = m[m["_rep"].isna()][["ticker", "date", "gap"]].copy()

    # ── drop anomalies (vectorised) ──────────────────────────────────────────
    if not stock_gaps.empty:
        stock_gaps["gap"] = pd.to_numeric(stock_gaps["gap"], errors="coerce")
        abs_gap = stock_gaps["gap"].abs()
        cnts = stock_gaps.groupby("ticker")["gap"].transform("count")
        eligible = cnts >= min_hist_for_cap
        if eligible.any():
            caps = (stock_gaps[eligible]
                    .groupby("ticker")["gap"]
                    .agg(lambda x: np.quantile(x.abs(), cap_q)))
            cap_mapped = stock_gaps["ticker"].map(caps)
            stock_gaps = stock_gaps[(~eligible) | (abs_gap <= cap_mapped)].reset_index(drop=True)

    # ── build ETF numpy matrix: rows=dates, cols=etfs ───────────────────────
    if not etf_gaps.empty:
        etf_pivot = etf_gaps.pivot_table(index="date", columns="ticker", values="gap", aggfunc="first")
        date_to_row = {d: i for i, d in enumerate(etf_pivot.index)}
        etf_to_col  = {c: i for i, c in enumerate(etf_pivot.columns)}
        etf_arr     = etf_pivot.to_numpy(dtype=float)
    else:
        date_to_row = {}; etf_to_col = {}; etf_arr = np.empty((0, 0))

    stock_map = (
        {t: g.set_index("date")["gap"] for t, g in stock_gaps.groupby("ticker")}
        if not stock_gaps.empty else {}
    )

    # ── corr/beta loop ───────────────────────────────────────────────────────
    rows_all = []
    rows_best = []
    sectors_with_fallback = []

    for sec in sorted(df_clean[sector_col].unique()):
        etfs_raw = sector_to_etf.get(sec)
        if not etfs_raw:
            etfs_raw = list(fallback_etfs)
            sectors_with_fallback.append(sec)
        etfs = [str(e).upper() for e in etfs_raw]
        etfs_ok  = [e for e in etfs if e in etf_to_col]
        col_idxs = [etf_to_col[e] for e in etfs_ok]
        if not col_idxs:
            continue

        for st in sorted(df_clean.loc[df_clean[sector_col] == sec, ticker_col].unique()):
            sx = stock_map.get(st)
            if sx is None or sx.empty:
                continue

            st_dates = [d for d in sx.index if d in date_to_row]
            if not st_dates:
                continue

            row_idxs = [date_to_row[d] for d in st_dates]
            x_vals   = sx[st_dates].to_numpy(dtype=float)
            y_mat    = etf_arr[np.ix_(row_idxs, col_idxs)]   # (n_dates, n_etfs)
            valid_x  = ~np.isnan(x_vals)

            best_corr = -np.inf
            best_etf  = None
            best_beta = np.nan
            best_n    = 0

            for j, etf in enumerate(etfs_ok):
                mask = valid_x & ~np.isnan(y_mat[:, j])
                n = int(mask.sum())
                if n < min_overlap:
                    continue

                xv = x_vals[mask];  yv = y_mat[mask, j]
                xc = xv - xv.mean(); yc = yv - yv.mean()
                var_y = float((yc * yc).sum() / (n - 1))
                if var_y == 0 or np.isnan(var_y):
                    continue
                cov_xy = float((xc * yc).sum() / (n - 1))
                std_x  = float(np.sqrt((xc * xc).sum() / (n - 1)))
                if std_x == 0:
                    continue
                corr = cov_xy / (std_x * np.sqrt(var_y))
                beta = cov_xy / var_y

                rows_all.append({"x_ticker": st, "y_ticker": etf, "corr": corr, "beta": beta, "lvl3": sec, "n_overlap": n})

                if corr > best_corr:
                    best_corr, best_etf, best_beta, best_n = corr, etf, beta, n

            if best_etf is not None:
                rows_best.append({"x_ticker": st, "best_y_ticker": best_etf, "best_corr": best_corr,
                                  "beta_with_best": best_beta, "lvl3": sec, "n_overlap": best_n})

    # ── output ───────────────────────────────────────────────────────────────
    df_all   = pd.DataFrame(rows_all)
    df_pairs = pd.DataFrame(rows_best) if rows_best else pd.DataFrame(
        columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", "lvl3", "n_overlap"])

    df_pairs.to_csv(output_path, index=False)
    df_bench = df_pairs.rename(columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"})[["ticker", "benchmark"]]
    df_bench.to_csv(bench_path, index=False)

    print(f"DONE pairs: {len(df_pairs)} -> {output_path}")
    print(f"DONE bench map: {len(df_bench)} -> {bench_path}")
    if sectors_with_fallback:
        print("Fallback ETF used for sectors:", ", ".join(map(str, sectors_with_fallback[:20])))

    return df_all, df_pairs

In [13]:
# Local corr/beta: stock gaps vs ETF gaps, excluding report days and stock outliers
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=TICKERS,
    sector_to_etf=sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    output_path=str(WORK_DIR / "x_to_best_etf_by_lvl3.csv"),
    bench_path=str(WORK_DIR / "ticker_bench_.csv"),
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    cap_q=0.95,
    min_hist_for_cap=20,
    min_overlap=20,
)

# Prepare parquet for downstream merge (cell 31)
corr_beta_pairs = df_pairs.rename(columns={
    "best_y_ticker": "y_ticker",
    "best_corr": "corr",
    "beta_with_best": "beta",
})[["x_ticker", "y_ticker", "corr", "beta"]].copy()

corr_beta_pairs.to_parquet(str(WORK_DIR / "corr_beta_pairs.parquet"), index=False)

print(df_all.head())
print("Rows in raw stock-etf pairs:", len(df_all))
print(df_pairs.head())
print("Saved:", str(WORK_DIR / "corr_beta_pairs.parquet"))

START gaps: stocks=7232 etfs=31 window=2026-04-16..2026-06-16

DONE pairs: 7045 -> C:\datum-api-examples-main\OriON\CRACEN\work\x_to_best_etf_by_lvl3.csv
DONE bench map: 7045 -> C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv
Fallback ETF used for sectors: UNKNOWN
  x_ticker y_ticker      corr      beta                     lvl3  n_overlap
0      ADV      QQQ  0.201924  0.260481  Advertising & Marketing         39
1      ADV     KWEB  0.123241  0.080102  Advertising & Marketing         39
2      ADV      IWM  0.215865  0.341001  Advertising & Marketing         39
3      ADV      SPY  0.249759  0.578492  Advertising & Marketing         39
4     AEHL      QQQ  0.208615  1.583663  Advertising & Marketing         40
Rows in raw stock-etf pairs: 25284
  x_ticker best_y_ticker  best_corr  beta_with_best                     lvl3  \
0      ADV           SPY   0.249759        0.578492  Advertising & Marketing
1     AEHL          KWEB   0.335495        1.372771  Advertising & Marketing
2      APP           SPY   0.460612        1.442668  Advertising & Marketing
3     AREN           IWM   0.252308        0.549276  Advertising & Marketing
4     BAOS           QQQ   0.051785        0.159516  Advertising & Marketing

   n_overlap
0         39
1         40
2         39
3         39
4         39
Saved: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [14]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [15]:
TICKERS

     ticker       value                         lvl3  market_cap
0         A    56375.62  Medical Equipment & Devices     35114.0
1        AA  1575737.43              Metals & Mining     16289.0
2      AAAU   412161.29                          NaN         NaN
3      AACG       23.80                     Software        43.0
4      AADX   120874.92          Aerospace & Defense      3454.0
...     ...         ...                          ...         ...
7227   ZVOL     1004.23                          NaN         NaN
7228   ZVRA    26949.30             Biotech & Pharma       745.0
7229    ZWS     1320.50                    Machinery      8071.0
7230   ZYBT       81.20             Biotech & Pharma        23.0
7231   ZYME    51867.16             Biotech & Pharma      1702.0

[7232 rows x 4 columns]

In [16]:
import pandas as pd

# список тикерів
tickers = [
    'SPY', 'IWM', 'GDX', 'XLF', 'QQQ', 'XLE', 'KRE', 'IBIT', 'KWEB', 'XLP', 'SOXX',
    'IGV', 'SMH', 'XLK', 'ITA', 'XLI', 'XTN', 'OIH', 'XLU', 'ICLN', 'XLB', 'SLX',
    'IBB', 'XBI', 'IHI', 'XLV', 'IHF', 'XRT', 'XLY', 'XHB', 'VNQ',
]


# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

   ticker
0     SPY
1     IWM
2     GDX
3     XLF
4     QQQ
5     XLE
6     KRE
7    IBIT
8    KWEB
9     XLP
10   SOXX
11    IGV
12    SMH
13    XLK
14    ITA
15    XLI
16    XTN
17    OIH
18    XLU
19   ICLN
20    XLB
21    SLX
22    IBB
23    XBI
24    IHI
25    XLV
26    IHF
27    XRT
28    XLY
29    XHB
30    VNQ

In [17]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=TICKERS,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=16,
    parallel_tickers=True,
    max_workers_tickers=16,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 47 тікерів (пропущено 0 по старому маніфесту) | 2026-04-16 00:00:00 → 2026-06-16 23:59:59 | interval=1 | next batch #8651 | run=140a4be1

   workers: tickers=16, chunks=16 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 7185

   📉 пропущені дні (в межах window): 2026-04-16 → 2026-06-16 (62 днів)

   📈 обробляються дні: –

   psutil · старт · 🧠 RAM: 284.5 MB

[10/47] – FNDB: empty |  21.28% | ETA 00:05

[20/47] – MSB: empty |  42.55% | ETA 00:03

[30/47] – SNK: empty |  63.83% | ETA 00:02

[40/47] – SPCQ: empty |  85.11% | ETA 00:00

[47/47] – STLU: empty | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 333.1 MB

💾 batch 8651 → 15,280 рядків (всього 15,280 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_8651.csv.gz

   ✅ після flush · 🧠 RAM: 334.8 MB

   🔚 фінал · 🧠 RAM: 334.8 MB

🏁 Готово. Нових рядків: 15,280 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 00:05

In [18]:
import os, glob, gc, time
from typing import Optional

import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str   = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    aggregate: bool = False,            # False → всі рядки, True → агрегація по (ticker,date)
    chunksize: int = 200_000,           # якщо мало RAM — ще зменш
    compression: str = "snappy",
    log_every: int = 5,
    sort_chunk: bool = True,            # sort within each chunk (ticker,dt)
):
    """
    Проходить по {folder}/{pattern}, фільтрує рядки:
      - за часовим вікном [start_time..end_time] по підрядку часу в 'dt'
      - опційно за датою [date_min..date_max] по підрядку дати в 'dt'
    і стрімово пише у один Parquet.

    Очікувані колонки у CSV: 'ticker','dt','o','h','l','c','v'.
    dt має формат 'YYYY-MM-DD HH:MM:SS' (string).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    # normalize dates (string compare works for YYYY-MM-DD)
    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    # читаємо тільки потрібне, даємо вузькі типи
    usecols = ["ticker", "dt", "o", "h", "l", "c", "v"]
    dtypes = {
        "ticker": "string",
        "dt": "string",         # важливо: фільтруємо по підрядку, без datetime-парсингу
        "o": "float32",
        "h": "float32",
        "l": "float32",
        "c": "float32",
        "v": "float32",
    }

    # підготовка виходу
    if os.path.exists(out_path):
        os.remove(out_path)
    writer = None

    t0 = time.time()
    total_in = total_out = 0
    file_idx = 0

    rng_str = ""
    if date_min or date_max:
        rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]"
    print(f"▶️ START: {folder}/{pattern} → {out_path}  chunksize={chunksize:,}{rng_str}")

    try:
        for path in files:
            file_idx += 1
            chunk_idx = 0

            reader = pd.read_csv(
                path,
                compression="infer",
                usecols=usecols,
                dtype=dtypes,
                chunksize=chunksize,
                low_memory=True,
                # engine="pyarrow",
            )

            for chunk in reader:
                chunk_idx += 1
                total_in += len(chunk)

                # швидке фільтрування по часу: 'YYYY-MM-DD HH:MM:SS'
                t = chunk["dt"].str.slice(11, 19)
                mask = (t >= start_time) & (t <= end_time)

                # фільтр по даті, також строками
                if date_min is not None or date_max is not None:
                    d = chunk["dt"].str.slice(0, 10)
                    if date_min is not None:
                        mask &= (d >= date_min)
                    if date_max is not None:
                        mask &= (d <= date_max)

                cut = chunk.loc[mask].copy()

                if cut.empty:
                    del chunk, t, mask, cut
                    gc.collect()
                    continue

                if aggregate:
                    # дата як рядок 'YYYY-MM-DD'
                    cut["date"] = cut["dt"].str.slice(0, 10)
                    # сорт для стабільності
                    if sort_chunk and {"ticker", "date"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "date"], kind="mergesort")
                    grp = (cut.groupby(["ticker", "date"], as_index=False, observed=True)
                              .agg({"v": "sum"}))  # приклад: сума обсягу; змінюй агрегацію за потреби
                    out_df = grp
                else:
                    # стабільний порядок в межах чанка
                    if sort_chunk and {"ticker", "dt"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "dt"], kind="mergesort")
                    out_df = cut

                table = pa.Table.from_pandas(out_df, preserve_index=False)
                if writer is None:
                    writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
                writer.write_table(table)
                total_out += len(out_df)

                if (chunk_idx % log_every) == 0:
                    elapsed = time.time() - t0
                    print(f"  [{file_idx}/{len(files)}] {os.path.basename(path)} "
                          f"chunk {chunk_idx}  in={total_in:,}  out={total_out:,}  "
                          f"elapsed={elapsed:,.1f}s")

                del chunk, t, mask, cut, out_df, table
                gc.collect()

    finally:
        if writer is not None:
            writer.close()

    print(f"✅ DONE  in={total_in:,} → out={total_out:,}  to {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [19]:
collect_premarket_by_day_stream(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,      # NEW
    date_max=end_date_str,        # NEW
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  chunksize=150,000  date=[2026-04-16..2026-06-16]

✅ DONE  in=288,944,766 → out=78,652,730  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 1,589.7s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows.parquet'

In [20]:
import os
import glob
import pandas as pd
from typing import Optional, Dict, Tuple

def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,
) -> pd.DataFrame:
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    OPEN_FROM, OPEN_TO   = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    best_open:  Dict[Tuple[str, str], Tuple[str, float]] = {}
    best_close: Dict[Tuple[str, str], Tuple[str, float]] = {}

    usecols = ["ticker", "dt", "o", "c"]

    for path in files:
        for chunk in pd.read_csv(path, compression="infer", low_memory=False,
                                 chunksize=chunksize, usecols=usecols):
            cols = set(map(str, chunk.columns))
            missing = set(usecols) - cols
            if missing:
                raise KeyError(f"{os.path.basename(path)}: відсутні колонки {missing}")

            dt = chunk["dt"].astype(str)
            if "o" in chunk.columns:
                chunk["o"] = pd.to_numeric(chunk["o"], errors="coerce")
            if "c" in chunk.columns:
                chunk["c"] = pd.to_numeric(chunk["c"], errors="coerce")

            hhmm = dt.str.slice(11, 16)
            date = dt.str.slice(0, 10)

            # OPEN
            mask_o = (hhmm >= OPEN_FROM) & (hhmm <= OPEN_TO) & chunk["o"].notna()
            if mask_o.any():
                cut = chunk.loc[mask_o, ["ticker", "o"]].copy()
                cut["date"] = date[mask_o].values
                cut["dt"]   = dt[mask_o].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="first")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_open.get(key)
                    if (cur is None) or (r.dt < cur[0]):
                        best_open[key] = (r.dt, float(r.o))

            # CLOSE
            mask_c = (hhmm >= CLOSE_FROM) & (hhmm <= CLOSE_TO) & chunk["c"].notna()
            if mask_c.any():
                cut = chunk.loc[mask_c, ["ticker", "c"]].copy()
                cut["date"] = date[mask_c].values
                cut["dt"]   = dt[mask_c].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="last")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_close.get(key)
                    if (cur is None) or (r.dt > cur[0]):
                        best_close[key] = (r.dt, float(r.c))

    opens_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_open.items()],
        columns=["ticker", "date", "open"]
    )
    closes_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_close.items()],
        columns=["ticker", "date", "close"]
    )

    out = pd.merge(opens_df, closes_df, on=["ticker","date"], how="outer") \
            .sort_values(["ticker","date"], kind="stable") \
            .reset_index(drop=True)

    # ⬇️ ОКРУГЛЕННЯ ДО 2 ЗНАКІВ
    if "open" in out.columns:
        out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    if "close" in out.columns:
        out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)

    # завжди Parquet
    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)

    return out

In [21]:
df_oc = build_oc_from_intraday_folder(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "oc.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [22]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [23]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=83.8s

[batch   10] rows=20,000,000  elapsed=168.2s

[batch   15] rows=30,000,000  elapsed=248.8s

[batch   20] rows=40,000,000  elapsed=330.4s

[batch   25] rows=50,000,000  elapsed=411.8s

[batch   30] rows=60,000,000  elapsed=495.0s

[batch   35] rows=70,000,000  elapsed=579.8s

[batch   40] rows=78,652,730  elapsed=656.4s
✅ DONE  rows=78,652,730  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  in 656.5s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet

In [24]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        # нульовий prev_close → NaN, щоб не ділити на 0
        denom = df["prev_close"].replace({0: np.nan})

        # розрахунок % vs prev_close
        pct = (df[value_col] / denom - 1.0) * 100.0

        # ще раз гарантуємо float dtype (без object/pd.NA всередині)
        pct = pd.to_numeric(pct, errors="coerce")

        if round_to is not None:
            pct = pct.round(int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(
                output_path,
                table.schema,
                compression="snappy",
            )
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [25]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

[batch    5] rows=10,000,000  elapsed=9.4s

[batch   10] rows=20,000,000  elapsed=18.3s

[batch   15] rows=30,000,000  elapsed=27.3s

[batch   20] rows=40,000,000  elapsed=36.2s

[batch   25] rows=50,000,000  elapsed=45.9s

[batch   30] rows=60,000,000  elapsed=54.9s

[batch   35] rows=70,000,000  elapsed=64.1s

[batch   40] rows=78,652,730  elapsed=72.2s
✅ DONE  rows=78,652,730  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  in 72.2s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet

In [26]:
import os
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Read ticker->bench mapping from csv/xlsx and return ['ticker','bench'].
    """
    ext = os.path.splitext(mapping_path)[1].lower()
    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(mapping_path)
    else:
        try:
            df = pd.read_csv(mapping_path, sep=None, engine="python")
        except Exception:
            df = pd.read_csv(mapping_path)

    cols = {c.lower().strip(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol") or list(df.columns)[0]
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf") or list(df.columns)[1]

    out = df[[tcol, bcol]].rename(columns={tcol: "ticker", bcol: "bench"}).dropna()
    out["ticker"] = out["ticker"].astype(str).str.upper().str.strip()
    out["bench"] = out["bench"].astype(str).str.upper().str.strip()
    out = out[(out["ticker"] != "") & (out["bench"] != "")]
    return out.drop_duplicates(ignore_index=True)


def corr_beta_from_mapping_to_parquet(*args, **kwargs):
    """
    Deprecated API path removed.
    corr/beta is now computed locally in cell 12 and written in cell 13/28.
    """
    raise RuntimeError(
        "corr_beta_from_mapping_to_parquet is deprecated. "
        "Use local calculation in cell 12 and parquet output in cell 13/28."
    )

In [27]:
import os
import pandas as pd

out_path = str(WORK_DIR / "corr_beta_pairs.parquet")

# If parquet already exists from cell 13, keep it.
# Otherwise rebuild it from x_to_best_etf_by_lvl3.csv (no API calls).
if not os.path.exists(out_path):
    src_csv = str(WORK_DIR / "x_to_best_etf_by_lvl3.csv")
    if not os.path.exists(src_csv):
        raise FileNotFoundError(f"Neither {out_path} nor {src_csv} exists")

    d = pd.read_csv(src_csv)
    need = ["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
    miss = [c for c in need if c not in d.columns]
    if miss:
        raise KeyError(f"Missing columns in {src_csv}: {miss}")

    d = d.rename(columns={
        "best_y_ticker": "y_ticker",
        "best_corr": "corr",
        "beta_with_best": "beta",
    })[["x_ticker", "y_ticker", "corr", "beta"]]
    d.to_parquet(out_path, index=False)

print("Result:", out_path)

Result: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [28]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    # Читаємо БЕЗ фільтра колонок — так надійніше для різних схем
    table = pq.read_table(path)
    df = table.to_pandas()

    # нормалізуємо імена колонок для пошуку
    name_map = {c: c.strip().lower() for c in df.columns}
    inv_map = {v: k for k, v in name_map.items()}

    has_api    = ("x_ticker" in inv_map) and ("y_ticker" in inv_map)
    has_direct = ("ticker" in inv_map) and ("bench" in inv_map)

    if not (has_api or has_direct):
        # допоміжна підказка, що саме є в файлі
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={
            inv_map["x_ticker"]: "ticker",
            inv_map["y_ticker"]: "bench"
        })
    else:
        df = df.rename(columns={
            inv_map["ticker"]: "ticker",
            inv_map["bench"]:  "bench"
        })

    # corr/beta можуть бути відсутні — створимо
    if "corr" not in name_map.values():
        df["corr"] = pd.NA
    else:
        df = df.rename(columns={inv_map["corr"]: "corr"})
    if "beta" not in name_map.values():
        df["beta"] = pd.NA
    else:
        df = df.rename(columns={inv_map["beta"]: "beta"})

    # залишаємо тільки потрібне
    keep = [c for c in ["ticker", "bench", "corr", "beta"] if c in df.columns]
    df = df[keep].copy()

    # нормалізація значень
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"]  = df["bench"].astype(str).str.strip().str.upper()
    if "corr" in df.columns:
        df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    if "beta" in df.columns:
        df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    # якщо раптом на один тикер кілька рядків — візьмемо з найбільшою corr
    if "corr" in df.columns:
        df = (df.sort_values(["ticker", "corr"], ascending=[True, False])
                .drop_duplicates(subset=["ticker"], keep="first")
                .reset_index(drop=True))
    else:
        df = df.drop_duplicates(subset=["ticker"], keep="first").reset_index(drop=True)

    # гарантуємо повний набір стовпців
    for c in ("corr", "beta"):
        if c not in df.columns:
            df[c] = pd.NA

    return df[["ticker", "bench", "corr", "beta"]]


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), мерджить 'bench','corr','beta' з іншого
    Parquet (мапа) по 'ticker' і пише новий Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0
    batches = 0

    print(f"▶️ START merge → {out_parquet_path}")

    for batch in pf.iter_batches(batch_size=batch_rows):  # читаємо всі колонки
        batches += 1
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")
        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(mapping, on="ticker", how="left", validate="m:1")

        # Переставимо нові колонки за потреби
        if insert_before in merged.columns:
            cols = list(merged.columns)
            for c in ("bench", "corr", "beta"):
                if c in cols: cols.remove(c)
            idx = cols.index(insert_before)
            new_cols = cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]
            merged = merged[new_cols]
        else:
            base = [c for c in merged.columns if c not in ("bench","corr","beta")]
            merged = merged[base + ["bench","corr","beta"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if batches % log_every_batches == 0:
            print(f"[batch {batches:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path


# опціональний аліас під старе ім’я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [29]:
out_path = attach_bench_corr_beta_parquet(
    input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    batch_rows=2_000_000,
    round_decimals=4,
    insert_before="pct_vs_prev_close",
    compression="snappy",
)
print("Готово:", out_path)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

[batch    5] rows=10,000,000  elapsed=21.3s

[batch   10] rows=20,000,000  elapsed=42.5s

[batch   15] rows=30,000,000  elapsed=62.7s

[batch   20] rows=40,000,000  elapsed=83.7s

[batch   25] rows=50,000,000  elapsed=104.8s

[batch   30] rows=60,000,000  elapsed=125.6s

[batch   35] rows=70,000,000  elapsed=147.1s

[batch   40] rows=78,652,730  elapsed=164.8s
✅ DONE rows=78,652,730 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet  in 164.8s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

In [30]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [31]:
peek_parquet(str(WORK_DIR / "premarket_rows_final.parquet"), n=620)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet
Рядків (meta): 78,652,730
Колонок: 14
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta

NaN у 'bench' (у прев'ю): 0/620
NaN у 'corr' (у прев'ю): 0/620
NaN у 'beta' (у прев'ю): 0/620

Перші рядки:

    ticker                  dt           o           h           l           c         v        date    open  prev_close  Stack% bench    corr    beta
0        A 2026-04-16 00:00:00  119.129997  119.129997  119.129997  119.129997      10.0  2026-04-16  121.12      119.77   -0.53   IWM  0.5962  0.6161
1        A 2026-04-16 01:37:00  119.440002  119.440002  119.440002  119.440002       5.0  2026-04-16  121.12      119.77   -0.28   IWM  0.5962  0.6161
2        A 2026-04-16 01:54:00  119.349998  119.349998  119.349998  119.349998       5.0  2026-04-16  121.12      119.77   -0.35   IWM  0.5962  0.6161
3        A 2026-04-16 02:00:00  119.349998  119.349998  119.349998  119.349998       5.0  2026-04-16  121.12      119.77   -0.35   IWM  0.5962  0.6161
4        A 2026-04-16 02:04:00  119.410004  119.410004  119.410004  119.410004      10.0  2026-04-16  121.12      119.77   -0.30   IWM  0.5962  0.6161
5        A 2026-04-16 03:05:00  119.540001  119.540001  119.540001  119.540001       5.0  2026-04-16  121.12      119.77   -0.19   IWM  0.5962  0.6161
6        A 2026-04-16 03:06:00  119.599998  119.599998  119.599998  119.599998       5.0  2026-04-16  121.12      119.77   -0.14   IWM  0.5962  0.6161
7        A 2026-04-16 09:30:00  121.120003  121.120003  119.040001  119.364998   18444.0  2026-04-16  121.12      119.77    1.13   IWM  0.5962  0.6161
8        A 2026-04-16 09:31:00  119.099998  119.099998  119.080002  119.080002     703.0  2026-04-16  121.12      119.77   -0.56   IWM  0.5962  0.6161
9        A 2026-04-16 09:32:00  119.080002  119.625000  119.080002  119.625000     400.0  2026-04-16  121.12      119.77   -0.58   IWM  0.5962  0.6161
10       A 2026-04-16 09:33:00  119.889999  119.889999  119.080002  119.080002    1800.0  2026-04-16  121.12      119.77    0.10   IWM  0.5962  0.6161
11       A 2026-04-16 09:34:00  119.389999  119.389999  118.750000  119.175003    4718.0  2026-04-16  121.12      119.77   -0.32   IWM  0.5962  0.6161
12       A 2026-04-16 09:35:00  118.290001  119.074997  118.290001  118.525002    1700.0  2026-04-16  121.12      119.77   -1.24   IWM  0.5962  0.6161
13       A 2026-04-16 09:36:00  118.567497  118.919998  118.567497  118.635002    1602.0  2026-04-16  121.12      119.77   -1.00   IWM  0.5962  0.6161
14       A 2026-04-16 09:37:00  118.635002  118.635002  118.502502  118.540001    4256.0  2026-04-16  121.12      119.77   -0.95   IWM  0.5962  0.6161
15       A 2026-04-16 09:38:00  118.370003  118.540001  118.370003  118.540001    1049.0  2026-04-16  121.12      119.77   -1.17   IWM  0.5962  0.6161
16       A 2026-04-16 09:39:00  118.709999  118.760002  118.709999  118.760002     500.0  2026-04-16  121.12      119.77   -0.89   IWM  0.5962  0.6161
17       A 2026-04-16 09:40:00  118.910004  118.919998  118.529999  118.529999    2252.0  2026-04-16  121.12      119.77   -0.72   IWM  0.5962  0.6161
18       A 2026-04-16 09:41:00  118.379997  118.379997  118.379997  118.379997     100.0  2026-04-16  121.12      119.77   -1.16   IWM  0.5962  0.6161
19       A 2026-04-16 09:42:00  118.309998  118.419998  118.309998  118.309998    2407.0  2026-04-16  121.12      119.77   -1.22   IWM  0.5962  0.6161
20       A 2026-04-16 09:43:00  118.320000  118.449997  118.290001  118.410004    1911.0  2026-04-16  121.12      119.77   -1.21   IWM  0.5962  0.6161
21       A 2026-04-16 09:44:00  118.415001  118.500000  118.169998  118.285004    5873.0  2026-04-16  121.12      119.77   -1.13   IWM  0.5962  0.6161
22       A 2026-04-16 09:45:00  118.150002  118.180000  118.135002  118.144997    3305.0  2026-04-16  121.12      119.77   -1.35   IWM  0.5962  0.6161
23       A 2026-04-16 09:46:00  118.135002  118.540001  117.980003  118.430000   38765.0  2026-04-16  121.12      119.77   -1.37   IWM  0.5962  0.6161
24       A 2026-04-16 09:47:00  118.425003  118.425003  118.019997  118.019997    3229.0  2026-04-16  121.12      119.77   -1.12   IWM  0.5962  0.6161
25       A 2026-04-16 09:48:00  118.239998  118.239998  117.949997  117.949997    1200.0  2026-04-16  121.12      119.77   -1.28   IWM  0.5962  0.6161
26       A 2026-04-16 09:49:00  118.165001  118.165001  118.165001  118.165001     600.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161
27       A 2026-04-16 09:50:00  118.114998  118.370003  118.114998  118.224998    7239.0  2026-04-16  121.12      119.77   -1.38   IWM  0.5962  0.6161
28       A 2026-04-16 09:51:00  118.224998  118.639999  118.199997  118.639999    8364.0  2026-04-16  121.12      119.77   -1.29   IWM  0.5962  0.6161
29       A 2026-04-16 09:52:00  118.695000  118.695000  118.550003  118.550003    1473.0  2026-04-16  121.12      119.77   -0.90   IWM  0.5962  0.6161
30       A 2026-04-16 09:53:00  118.550003  118.550003  118.349998  118.349998    1500.0  2026-04-16  121.12      119.77   -1.02   IWM  0.5962  0.6161
31       A 2026-04-16 09:54:00  118.339996  118.339996  118.099998  118.099998    2027.0  2026-04-16  121.12      119.77   -1.19   IWM  0.5962  0.6161
32       A 2026-04-16 09:55:00  117.879997  118.004997  117.879997  117.989998     831.0  2026-04-16  121.12      119.77   -1.58   IWM  0.5962  0.6161
33       A 2026-04-16 09:56:00  118.000000  118.000000  117.970001  117.970001     300.0  2026-04-16  121.12      119.77   -1.48   IWM  0.5962  0.6161
34       A 2026-04-16 09:57:00  118.139999  118.160004  118.089996  118.160004    1277.0  2026-04-16  121.12      119.77   -1.36   IWM  0.5962  0.6161
35       A 2026-04-16 09:58:00  118.175003  118.175003  118.175003  118.175003     300.0  2026-04-16  121.12      119.77   -1.33   IWM  0.5962  0.6161
36       A 2026-04-16 09:59:00  118.375000  118.375000  118.180000  118.339996    1790.0  2026-04-16  121.12      119.77   -1.16   IWM  0.5962  0.6161
37       A 2026-04-16 10:00:00  118.190002  118.279999  118.125000  118.125000    1969.0  2026-04-16  121.12      119.77   -1.32   IWM  0.5962  0.6161
38       A 2026-04-16 10:01:00  118.029999  118.029999  117.625000  117.730003    1900.0  2026-04-16  121.12      119.77   -1.45   IWM  0.5962  0.6161
39       A 2026-04-16 10:02:00  117.794998  117.970001  117.794998  117.940002     512.0  2026-04-16  121.12      119.77   -1.65   IWM  0.5962  0.6161
40       A 2026-04-16 10:03:00  118.129997  118.360001  118.110001  118.330002    1843.0  2026-04-16  121.12      119.77   -1.37   IWM  0.5962  0.6161
41       A 2026-04-16 10:04:00  118.214996  118.214996  118.214996  118.214996     200.0  2026-04-16  121.12      119.77   -1.30   IWM  0.5962  0.6161
42       A 2026-04-16 10:05:00  118.371002  118.371002  118.214996  118.220001     400.0  2026-04-16  121.12      119.77   -1.17   IWM  0.5962  0.6161
43       A 2026-04-16 10:06:00  118.199997  118.209999  118.105003  118.105003     600.0  2026-04-16  121.12      119.77   -1.31   IWM  0.5962  0.6161
44       A 2026-04-16 10:07:00  118.019997  118.019997  118.019997  118.019997     400.0  2026-04-16  121.12      119.77   -1.46   IWM  0.5962  0.6161
45       A 2026-04-16 10:08:00  118.120003  118.470001  118.120003  118.470001    2636.0  2026-04-16  121.12      119.77   -1.38   IWM  0.5962  0.6161
46       A 2026-04-16 10:10:00  118.459999  118.550003  118.459999  118.474998    1774.0  2026-04-16  121.12      119.77   -1.09   IWM  0.5962  0.6161
47       A 2026-04-16 10:11:00  118.510002  118.510002  118.300003  118.440002    1766.0  2026-04-16  121.12      119.77   -1.05   IWM  0.5962  0.6161
48       A 2026-04-16 10:12:00  118.389999  118.449997  118.375000  118.449997     500.0  2026-04-16  121.12      119.77   -1.15   IWM  0.5962  0.6161
49       A 2026-04-16 10:13:00  118.379997  118.470001  118.379997  118.470001     600.0  2026-04-16  121.12      119.77   -1.16   IWM  0.5962  0.6161
50       A 2026-04-16 10:14:00  118.379997  118.470001  118.379997  118.470001     300.0  2026-04-16  121.12      119.77   -1.16   IWM  0.5962  0.6161
51       A 2026-04-16 10:15:00  118.589996  118.620003  118.589996  118.620003     700.0  2026-04-16  121.12      119.77   -0.99   IWM  0.5962  0.6161
52       A 2026-04-16 10:16:00  118.589996  118.660004  118.559998  118.660004    1257.0  2026-04-16  121.12      119.77   -0.99   IWM  0.5962  0.6161
53       A 2026-04-16 10:17:00  118.559998  118.660004  118.559998  118.610001    1363.0  2026-04-16  121.12      119.77   -1.01   IWM  0.5962  0.6161
54       A 2026-04-16 10:18:00  118.610001  118.720001  118.589996  118.669998     900.0  2026-04-16  121.12      119.77   -0.97   IWM  0.5962  0.6161
55       A 2026-04-16 10:19:00  118.610001  118.610001  118.610001  118.610001     303.0  2026-04-16  121.12      119.77   -0.97   IWM  0.5962  0.6161
56       A 2026-04-16 10:20:00  118.599998  118.690002  118.599998  118.614998    2450.0  2026-04-16  121.12      119.77   -0.98   IWM  0.5962  0.6161
57       A 2026-04-16 10:21:00  118.709999  118.709999  118.580002  118.610001    5041.0  2026-04-16  121.12      119.77   -0.89   IWM  0.5962  0.6161
58       A 2026-04-16 10:22:00  118.709999  118.709999  118.599998  118.610001    1100.0  2026-04-16  121.12      119.77   -0.89   IWM  0.5962  0.6161
59       A 2026-04-16 10:23:00  118.584999  118.584999  118.239998  118.489998    5760.0  2026-04-16  121.12      119.77   -0.99   IWM  0.5962  0.6161
60       A 2026-04-16 10:24:00  118.425003  118.425003  118.360001  118.360001     686.0  2026-04-16  121.12      119.77   -1.12   IWM  0.5962  0.6161
61       A 2026-04-16 10:25:00  118.360001  118.360001  118.360001  118.360001     100.0  2026-04-16  121.12      119.77   -1.18   IWM  0.5962  0.6161
62       A 2026-04-16 10:27:00  118.389999  118.389999  118.360001  118.379997     300.0  2026-04-16  121.12      119.77   -1.15   IWM  0.5962  0.6161
63       A 2026-04-16 10:28:00  118.470001  118.470001  118.470001  118.470001     100.0  2026-04-16  121.12      119.77   -1.09   IWM  0.5962  0.6161
64       A 2026-04-16 10:29:00  118.410004  118.410004  118.410004  118.410004     100.0  2026-04-16  121.12      119.77   -1.14   IWM  0.5962  0.6161
65       A 2026-04-16 10:30:00  118.394997  118.459999  118.394997  118.459999     300.0  2026-04-16  121.12      119.77   -1.15   IWM  0.5962  0.6161
66       A 2026-04-16 10:31:00  118.400002  118.400002  118.260002  118.290001    1205.0  2026-04-16  121.12      119.77   -1.14   IWM  0.5962  0.6161
67       A 2026-04-16 10:32:00  118.294998  118.294998  118.294998  118.294998     100.0  2026-04-16  121.12      119.77   -1.23   IWM  0.5962  0.6161
68       A 2026-04-16 10:34:00  118.297501  118.419998  118.297501  118.320000    1148.0  2026-04-16  121.12      119.77   -1.23   IWM  0.5962  0.6161
69       A 2026-04-16 10:35:00  118.339996  118.339996  118.220001  118.220001     600.0  2026-04-16  121.12      119.77   -1.19   IWM  0.5962  0.6161
70       A 2026-04-16 10:36:00  118.180000  118.180000  118.169998  118.175003    1350.0  2026-04-16  121.12      119.77   -1.33   IWM  0.5962  0.6161
71       A 2026-04-16 10:37:00  118.129997  118.150002  118.114998  118.114998    2455.0  2026-04-16  121.12      119.77   -1.37   IWM  0.5962  0.6161
72       A 2026-04-16 10:38:00  118.070000  118.070000  118.050003  118.050003    1400.0  2026-04-16  121.12      119.77   -1.42   IWM  0.5962  0.6161
73       A 2026-04-16 10:39:00  117.974998  117.974998  117.974998  117.974998     260.0  2026-04-16  121.12      119.77   -1.50   IWM  0.5962  0.6161
74       A 2026-04-16 10:40:00  117.970001  117.970001  117.739998  117.849998    1600.0  2026-04-16  121.12      119.77   -1.50   IWM  0.5962  0.6161
75       A 2026-04-16 10:41:00  117.970001  117.970001  117.919998  117.919998     246.0  2026-04-16  121.12      119.77   -1.50   IWM  0.5962  0.6161
76       A 2026-04-16 10:42:00  118.120003  118.120003  118.120003  118.120003     200.0  2026-04-16  121.12      119.77   -1.38   IWM  0.5962  0.6161
77       A 2026-04-16 10:43:00  118.089996  118.114998  118.089996  118.114998     367.0  2026-04-16  121.12      119.77   -1.40   IWM  0.5962  0.6161
78       A 2026-04-16 10:44:00  118.120003  118.239998  118.120003  118.239998     200.0  2026-04-16  121.12      119.77   -1.38   IWM  0.5962  0.6161
79       A 2026-04-16 10:46:00  118.169998  118.169998  118.169998  118.169998     100.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161
80       A 2026-04-16 10:48:00  118.169998  118.169998  118.169998  118.169998     100.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161
81       A 2026-04-16 10:49:00  118.160004  118.160004  118.160004  118.160004     100.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161
82       A 2026-04-16 10:50:00  118.139999  118.330002  118.110001  118.330002    1564.0  2026-04-16  121.12      119.77   -1.36   IWM  0.5962  0.6161
83       A 2026-04-16 10:51:00  118.279999  118.279999  118.279999  118.279999     300.0  2026-04-16  121.12      119.77   -1.24   IWM  0.5962  0.6161
84       A 2026-04-16 10:52:00  118.169998  118.180000  118.089996  118.089996     905.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161
85       A 2026-04-16 10:54:00  118.089996  118.089996  118.084999  118.084999     200.0  2026-04-16  121.12      119.77   -1.40   IWM  0.5962  0.6161
86       A 2026-04-16 10:55:00  118.086502  118.086502  118.029999  118.029999     225.0  2026-04-16  121.12      119.77   -1.41   IWM  0.5962  0.6161
87       A 2026-04-16 10:56:00  117.959999  118.010002  117.949997  117.959999    1705.0  2026-04-16  121.12      119.77   -1.51   IWM  0.5962  0.6161
88       A 2026-04-16 10:57:00  117.849998  117.849998  117.614998  117.620003    2057.0  2026-04-16  121.12      119.77   -1.60   IWM  0.5962  0.6161
89       A 2026-04-16 10:58:00  117.650002  117.989998  117.650002  117.989998    1600.0  2026-04-16  121.12      119.77   -1.77   IWM  0.5962  0.6161
90       A 2026-04-16 10:59:00  117.980003  117.980003  117.980003  117.980003     100.0  2026-04-16  121.12      119.77   -1.49   IWM  0.5962  0.6161
91       A 2026-04-16 11:00:00  117.980003  117.980003  117.980003  117.980003     300.0  2026-04-16  121.12      119.77   -1.49   IWM  0.5962  0.6161
92       A 2026-04-16 11:01:00  118.010002  118.040001  117.995003  117.995003    1505.0  2026-04-16  121.12      119.77   -1.47   IWM  0.5962  0.6161
93       A 2026-04-16 11:02:00  118.050003  118.050003  117.995003  117.995003     200.0  2026-04-16  121.12      119.77   -1.44   IWM  0.5962  0.6161
94       A 2026-04-16 11:03:00  117.989998  117.989998  117.989998  117.989998     100.0  2026-04-16  121.12      119.77   -1.49   IWM  0.5962  0.6161
95       A 2026-04-16 11:04:00  117.900002  118.250000  117.879997  118.250000    3359.0  2026-04-16  121.12      119.77   -1.56   IWM  0.5962  0.6161
96       A 2026-04-16 11:05:00  118.279999  118.349998  118.199997  118.269997   17862.0  2026-04-16  121.12      119.77   -1.24   IWM  0.5962  0.6161
97       A 2026-04-16 11:06:00  118.254997  118.254997  118.230003  118.230003     200.0  2026-04-16  121.12      119.77   -1.26   IWM  0.5962  0.6161
98       A 2026-04-16 11:07:00  118.250000  118.315002  118.180000  118.220001    4809.0  2026-04-16  121.12      119.77   -1.27   IWM  0.5962  0.6161
99       A 2026-04-16 11:08:00  118.220001  118.220001  118.099998  118.099998    4205.0  2026-04-16  121.12      119.77   -1.29   IWM  0.5962  0.6161
100      A 2026-04-16 11:09:00  118.220001  118.279999  118.220001  118.279999     300.0  2026-04-16  121.12      119.77   -1.29   IWM  0.5962  0.6161
101      A 2026-04-16 11:10:00  118.360001  118.459999  118.360001  118.459999     852.0  2026-04-16  121.12      119.77   -1.18   IWM  0.5962  0.6161
102      A 2026-04-16 11:11:00  118.464996  118.464996  118.440002  118.440002     841.0  2026-04-16  121.12      119.77   -1.09   IWM  0.5962  0.6161
103      A 2026-04-16 11:12:00  118.440002  118.440002  118.440002  118.440002     300.0  2026-04-16  121.12      119.77   -1.11   IWM  0.5962  0.6161
104      A 2026-04-16 11:13:00  118.584999  118.605003  118.584999  118.605003     300.0  2026-04-16  121.12      119.77   -0.99   IWM  0.5962  0.6161
105      A 2026-04-16 11:14:00  118.660004  118.675003  118.550102  118.550102     706.0  2026-04-16  121.12      119.77   -0.93   IWM  0.5962  0.6161
106      A 2026-04-16 11:15:00  118.599998  118.925003  118.599998  118.820000    2911.0  2026-04-16  121.12      119.77   -0.98   IWM  0.5962  0.6161
107      A 2026-04-16 11:16:00  118.790001  118.790001  118.770149  118.790001     534.0  2026-04-16  121.12      119.77   -0.82   IWM  0.5962  0.6161
108      A 2026-04-16 11:17:00  118.790001  118.889999  118.790001  118.889999    1398.0  2026-04-16  121.12      119.77   -0.82   IWM  0.5962  0.6161
109      A 2026-04-16 11:18:00  118.849998  118.849998  118.815002  118.815002    1300.0  2026-04-16  121.12      119.77   -0.77   IWM  0.5962  0.6161
110      A 2026-04-16 11:19:00  118.815002  118.940002  118.709999  118.900002    3074.0  2026-04-16  121.12      119.77   -0.80   IWM  0.5962  0.6161
111      A 2026-04-16 11:20:00  118.845001  119.129997  118.845001  119.089996    9452.0  2026-04-16  121.12      119.77   -0.77   IWM  0.5962  0.6161
112      A 2026-04-16 11:21:00  119.059998  119.059998  118.930000  118.959999    4245.0  2026-04-16  121.12      119.77   -0.59   IWM  0.5962  0.6161
113      A 2026-04-16 11:22:00  118.980003  118.989998  118.974998  118.980003    1001.0  2026-04-16  121.12      119.77   -0.66   IWM  0.5962  0.6161
114      A 2026-04-16 11:23:00  118.980003  118.980003  118.900002  118.919998    2215.0  2026-04-16  121.12      119.77   -0.66   IWM  0.5962  0.6161
115      A 2026-04-16 11:24:00  118.919998  118.919998  118.919998  118.919998     100.0  2026-04-16  121.12      119.77   -0.71   IWM  0.5962  0.6161
116      A 2026-04-16 11:25:00  118.925003  118.925003  118.919998  118.919998     200.0  2026-04-16  121.12      119.77   -0.71   IWM  0.5962  0.6161
117      A 2026-04-16 11:27:00  118.952499  118.980003  118.910004  118.910004     500.0  2026-04-16  121.12      119.77   -0.68   IWM  0.5962  0.6161
118      A 2026-04-16 11:28:00  118.910004  118.980003  118.904999  118.959999    1419.0  2026-04-16  121.12      119.77   -0.72   IWM  0.5962  0.6161
119      A 2026-04-16 11:29:00  118.949997  118.949997  118.820000  118.860001    3130.0  2026-04-16  121.12      119.77   -0.68   IWM  0.5962  0.6161
120      A 2026-04-16 11:30:00  118.820000  118.870003  118.790001  118.860001     800.0  2026-04-16  121.12      119.77   -0.79   IWM  0.5962  0.6161
121      A 2026-04-16 11:31:00  118.834999  118.834999  118.834999  118.834999     100.0  2026-04-16  121.12      119.77   -0.78   IWM  0.5962  0.6161
122      A 2026-04-16 11:32:00  118.834999  118.834999  118.834999  118.834999     995.0  2026-04-16  121.12      119.77   -0.78   IWM  0.5962  0.6161
123      A 2026-04-16 11:33:00  118.834999  118.875000  118.760002  118.760002    1870.0  2026-04-16  121.12      119.77   -0.78   IWM  0.5962  0.6161
124      A 2026-04-16 11:34:00  118.739998  118.750000  118.709999  118.732498    1800.0  2026-04-16  121.12      119.77   -0.86   IWM  0.5962  0.6161
125      A 2026-04-16 11:35:00  118.709999  118.709999  118.620003  118.635002     794.0  2026-04-16  121.12      119.77   -0.89   IWM  0.5962  0.6161
126      A 2026-04-16 11:36:00  118.655502  118.690002  118.617500  118.644997     722.0  2026-04-16  121.12      119.77   -0.93   IWM  0.5962  0.6161
127      A 2026-04-16 11:37:00  118.860001  118.947502  118.860001  118.947502     559.0  2026-04-16  121.12      119.77   -0.76   IWM  0.5962  0.6161
128      A 2026-04-16 11:38:00  118.879997  118.879997  118.839996  118.839996     300.0  2026-04-16  121.12      119.77   -0.74   IWM  0.5962  0.6161
129      A 2026-04-16 11:39:00  118.790001  118.790001  118.790001  118.790001     104.0  2026-04-16  121.12      119.77   -0.82   IWM  0.5962  0.6161
130      A 2026-04-16 11:40:00  118.785004  118.785004  118.785004  118.785004     100.0  2026-04-16  121.12      119.77   -0.82   IWM  0.5962  0.6161

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta
0,A,2026-04-16 00:00:00,119.129997,119.129997,119.129997,119.129997,10.0,2026-04-16,121.12,119.77,-0.53,IWM,0.5962,0.6161
1,A,2026-04-16 01:37:00,119.440002,119.440002,119.440002,119.440002,5.0,2026-04-16,121.12,119.77,-0.28,IWM,0.5962,0.6161
2,A,2026-04-16 01:54:00,119.349998,119.349998,119.349998,119.349998,5.0,2026-04-16,121.12,119.77,-0.35,IWM,0.5962,0.6161
3,A,2026-04-16 02:00:00,119.349998,119.349998,119.349998,119.349998,5.0,2026-04-16,121.12,119.77,-0.35,IWM,0.5962,0.6161
4,A,2026-04-16 02:04:00,119.410004,119.410004,119.410004,119.410004,10.0,2026-04-16,121.12,119.77,-0.30,IWM,0.5962,0.6161
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,A,2026-04-17 13:36:00,121.154999,121.199997,121.154999,121.199997,200.0,2026-04-17,119.47,118.23,2.47,IWM,0.5962,0.6161
616,A,2026-04-17 13:37:00,121.169998,121.230003,121.169998,121.209999,500.0,2026-04-17,119.47,118.23,2.49,IWM,0.5962,0.6161
617,A,2026-04-17 13:38:00,121.227501,121.227501,121.184998,121.184998,1499.0,2026-04-17,119.47,118.23,2.54,IWM,0.5962,0.6161
618,A,2026-04-17 13:40:00,121.139999,121.139999,121.139999,121.139999,200.0,2026-04-17,119.47,118.23,2.46,IWM,0.5962,0.6161
619,A,2026-04-17 13:41:00,121.070000,121.070000,121.029999,121.029999,300.0,2026-04-17,119.47,118.23,2.40,IWM,0.5962,0.6161

In [32]:
# список тикерів
tickers = [
    'SPY', 'IWM', 'GDX', 'XLF', 'QQQ', 'XLE', 'KRE', 'IBIT', 'KWEB', 'XLP', 'SOXX',
    'IGV', 'SMH', 'XLK', 'ITA', 'XLI', 'XTN', 'OIH', 'XLU', 'ICLN', 'XLB', 'SLX',
    'IBB', 'XBI', 'IHI', 'XLV', 'IHF', 'XRT', 'XLY', 'XHB', 'VNQ',
]

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [33]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=12,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 0 тікерів (пропущено 0 по старому маніфесту) | 2026-04-16 00:00:00 → 2026-06-16 23:59:59 | interval=1 | next batch #0080 | run=92e1b930

   workers: tickers=12, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 31

   📉 пропущені дні (в межах window): 2026-04-16 → 2026-06-16 (62 днів)

   📈 обробляються дні: –

   psutil · старт · 🧠 RAM: 1,362.7 MB

   🔚 фінал · 🧠 RAM: 1,362.7 MB

🏁 Готово. Нових рядків: 0 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:00

In [34]:
collect_premarket_by_day_stream(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  chunksize=150,000

  [69/79] intraday_0069.csv.gz chunk 5  in=2,122,725  out=2,122,725  elapsed=17.4s

✅ DONE  in=2,280,698 → out=2,280,698  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 18.8s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_etf_rows.parquet'

In [35]:
df_oc = build_oc_from_intraday_folder(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "oc_etf.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date   open  close
0   BITO  2025-10-28  18.96  18.72
1   BITO  2025-10-29  18.70  18.21
2   BITO  2025-10-30  17.83  17.53
3   BITO  2025-10-31  18.09  18.07
4   BITO  2025-11-03  16.89  16.74

In [36]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [37]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=2,280,698  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 7.9s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [38]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None

def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",   # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Benchk%",  # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        denom = df["prev_close"].replace({0: pd.NA})
        pct = (df[value_col] / denom - 1.0) * 100.0
        if round_to is not None:
            pct = pct.round(round_to)

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",   # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [39]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=2,280,698  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 2.0s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [40]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception as e:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий файл по ключах ('bench'↔'ticker', 'dt') і пише новий Parquet.
    - У ETF-файлі колонка з відсотком може називатись 'bench%' або 'pct_vs_prev_close' — обидва варіанти підтримуються.
    - Базовий файл не змінюється, додається тільки нова колонка 'Bench%'.
    """

    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    # ---------- 1) Збираємо мапу з ETF-файла: (bench, dt) -> Bench% ----------
    def _read_etf_mapping(etf_parquet: str) -> pd.DataFrame:
        pf = pq.ParquetFile(etf_parquet)
        parts = []
        # читаємо всі колонки, щоб не ловити різні схеми у row-groups
        for batch in pf.iter_batches():
            df = batch.to_pandas()
            # обов'язкові
            for col in ("ticker", "dt"):
                if col not in df.columns:
                    raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")

            # колонка відсотка: bench% або pct_vs_prev_close
            cols_l = {c.lower().strip(): c for c in df.columns}
            if "bench%" in cols_l:
                val_col = cols_l["bench%"]
            elif "pct_vs_prev_close" in cols_l:
                val_col = cols_l["pct_vs_prev_close"]
            else:
                raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

            d = df[["ticker", "dt", val_col]].copy()
            d["ticker"] = d["ticker"].astype(str).str.strip().str.upper()
            d["dt"]     = pd.to_datetime(d["dt"], errors="coerce")
            if align_to_minute:
                d["dt"] = d["dt"].dt.floor("T")
            d = d.dropna(subset=["dt"])
            d = d.rename(columns={"ticker": "bench", val_col: "Bench%"})
            d["Bench%"] = pd.to_numeric(d["Bench%"], errors="coerce")
            parts.append(d)

            del df, d, batch
            gc.collect()

        if not parts:
            return pd.DataFrame(columns=["bench","dt","Bench%"])

        etf_map = pd.concat(parts, ignore_index=True)
        # прибираємо дублікати — залишаємо пізніший запис
        etf_map = (etf_map.sort_values(["bench","dt"])
                           .drop_duplicates(subset=["bench","dt"], keep="last")
                           .reset_index(drop=True))
        return etf_map

    etf_map = _read_etf_mapping(etf_path)
    if round_decimals is not None and "Bench%" in etf_map.columns:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    # ---------- 2) Потоково проходимо базовий файл і підмерджуємо Bench% ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START merge → {out_path}")
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # ключі
        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        df["bench"] = df["bench"].astype(str).str.strip().str.upper()
        df["dt"]    = pd.to_datetime(df["dt"], errors="coerce")
        if align_to_minute:
            df["dt"] = df["dt"].dt.floor("T")

        merged = df.merge(etf_map, on=["bench","dt"], how="left", validate="m:1")

        # розташування 'Bench%'
        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("Bench%")
            pos = cols.index(insert_before)
            cols = cols[:pos] + ["Bench%"] + cols[pos:]
            merged = merged[cols]
        # інакше — залишаємо в кінці як є

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [41]:
merge_bench_pct_from_etf(
    base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    batch_rows=2_000_000,
    align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
    round_decimals=2,
    insert_before=None,          # або, наприклад, "pct_vs_prev_close"
    compression="snappy",
)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet

[batch    5] rows=10,000,000  elapsed=24.9s

[batch   10] rows=20,000,000  elapsed=49.0s

[batch   15] rows=30,000,000  elapsed=75.0s

[batch   20] rows=40,000,000  elapsed=100.4s

[batch   25] rows=50,000,000  elapsed=125.6s

[batch   30] rows=60,000,000  elapsed=150.7s

[batch   35] rows=70,000,000  elapsed=174.5s

[batch   40] rows=78,652,730  elapsed=196.4s
✅ DONE rows=78,652,730 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet  in 196.4s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct.parquet'

In [42]:
import datetime
import numpy as np
import pandas as pd
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed


def _pick_first_existing(df: pd.DataFrame, candidates):
    cols_l = {c.lower().strip(): c for c in df.columns}
    for c in candidates:
        if c.lower() in cols_l:
            return cols_l[c.lower()]
    return None


def get_reports(ticker, last_n_reports, start_date, end_date):
    try:
        params = {
            "ticker": str(ticker),
            "start_move_date": str(start_date)[:10],
            "end_move_date": str(end_date)[:10],
        }
        reports_df = DatumApi.data_request("/reports", params)
        if reports_df is None or reports_df.empty:
            return pd.DataFrame(columns=["ticker", "report_date"])

        date_col = _pick_first_existing(
            reports_df,
            ["report_date", "move_date", "date", "dt", "datetime", "published_at", "created_at"],
        )
        if date_col is None:
            return pd.DataFrame(columns=["ticker", "report_date"])

        out = reports_df.copy()
        out["report_date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
        out["ticker"] = str(ticker).upper()
        out = out.dropna(subset=["report_date"])
        out = out.sort_values("report_date").tail(int(last_n_reports))
        return out[["ticker", "report_date"]].reset_index(drop=True)
    except Exception as e:
        print(f"Report fetch failed for {ticker}: {e}")
        return pd.DataFrame(columns=["ticker", "report_date"])


def get_reports_for_tickers(tickers_df, start_date, end_date, last_n_reports=20, max_workers=16):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()
    parts = []

    def fetch(t):
        return get_reports(ticker=t, last_n_reports=last_n_reports, start_date=start_date, end_date=end_date)

    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Reports"):
            rep = f.result()
            if rep is not None and not rep.empty:
                parts.append(rep)

    if not parts:
        return pd.DataFrame(columns=["ticker", "report_date"]), {}

    reports = pd.concat(parts, ignore_index=True).drop_duplicates(["ticker", "report_date"])
    report_days_map = reports.groupby("ticker")["report_date"].apply(set).to_dict()
    return reports, report_days_map


def get_gaps_for_tickers_excluding_reports(tickers_df, start_date, end_date, report_days_map, max_workers=16):
    tickers = tickers_df["ticker"].dropna().astype(str).str.upper().unique().tolist()

    def fetch(t):
        params = {
            "ticker": t,
            "start_date": str(start_date)[:10],
            "end_date": str(end_date)[:10],
            "format": "json_records",
        }
        try:
            df_gap = DatumApi.data_request("/daily/gaps", params)
            if df_gap is None or df_gap.empty:
                return None

            date_col = _pick_first_existing(df_gap, ["date", "move_date", "dt", "datetime", "day"])
            if date_col is None:
                return None

            out = df_gap.copy()
            out["ticker"] = out["ticker"].astype(str).str.upper() if "ticker" in out.columns else t
            out["date"] = pd.to_datetime(out[date_col], errors="coerce").dt.strftime("%Y-%m-%d")
            out["gap"] = pd.to_numeric(out.get("gap"), errors="coerce")
            out = out.dropna(subset=["date", "gap"])

            report_days = report_days_map.get(t, set())
            if report_days:
                out = out[~out["date"].isin(report_days)]

            return out if not out.empty else None
        except Exception as e:
            print(f"Gap fetch failed for {t}: {e}")
            return None

    all_results = []
    with ThreadPoolExecutor(max_workers=max_workers) as ex:
        futures = {ex.submit(fetch, t): t for t in tickers}
        for f in tqdm(as_completed(futures), total=len(futures), desc="Gaps (ex-reports)"):
            result = f.result()
            if result is not None:
                all_results.append(result)

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    return pd.DataFrame(columns=["ticker", "date", "gap"])


def add_rolling_sigma_cap(
    df,
    value_col,
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.95,
    min_periods=None,
):
    if min_periods is None:
        min_periods = window

    out = df.sort_values([group_col, date_col]).copy()

    def compute_sigma(s):
        x = s.shift(1)

        def f(arr):
            arr = arr[~np.isnan(arr)]
            if len(arr) < min_periods:
                return np.nan
            cap = np.quantile(np.abs(arr), cap_q)
            arr_capped = np.clip(arr, -cap, cap)
            return np.std(arr_capped, ddof=1)

        return x.rolling(window, min_periods=min_periods).apply(f, raw=True)

    out[f"{value_col}_sigma_{window}d_cap"] = (
        out.groupby(group_col)[value_col].transform(compute_sigma)
    )
    return out


# 1) Report days in the working window
reports_df, report_days_map = get_reports_for_tickers(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    last_n_reports=20,
    max_workers=16,
)
print("Report rows:", len(reports_df))

# 2) Gaps without report days
df_gaps_all = get_gaps_for_tickers_excluding_reports(
    TICKERS,
    start_date=start_date_str,
    end_date=end_date_str,
    report_days_map=report_days_map,
    max_workers=16,
)
print("Rows in gaps (without report days):", len(df_gaps_all))

# 3) Rolling sigma
sigma_daily = add_rolling_sigma_cap(
    df=df_gaps_all,
    value_col="gap",
    window=20,
    group_col="ticker",
    date_col="date",
    cap_q=0.95,
    min_periods=20,
)

sigma_col = "gap_sigma_20d_cap"

std_by_ticker = (
    sigma_daily.dropna(subset=[sigma_col])
    .sort_values(["ticker", "date"])
    .groupby("ticker", as_index=False)
    .tail(1)[["ticker", sigma_col]]
    .rename(columns={sigma_col: "sigma"})
    .reset_index(drop=True)
)

print("Tickers with sigma:", len(std_by_ticker))
std_by_ticker.head()

Reports:   0%|          | 0/7232 [00:00<?, ?it/s]

Reports:   0%|          | 1/7232 [00:00<38:25,  3.14it/s]

Reports:   0%|          | 17/7232 [00:00<02:49, 42.55it/s]

Reports:   0%|          | 23/7232 [00:00<02:42, 44.37it/s]

Reports:   0%|          | 31/7232 [00:00<03:16, 36.58it/s]

Reports:   1%|          | 45/7232 [00:01<02:19, 51.35it/s]

Reports:   1%|          | 51/7232 [00:01<02:36, 45.76it/s]

Reports:   1%|          | 62/7232 [00:01<02:10, 54.85it/s]

Reports:   1%|          | 69/7232 [00:01<02:13, 53.74it/s]

Reports:   1%|          | 79/7232 [00:01<02:05, 56.83it/s]

Reports:   1%|▏         | 91/7232 [00:01<01:41, 70.59it/s]

Reports:   1%|▏         | 99/7232 [00:01<02:05, 56.78it/s]

Reports:   2%|▏         | 112/7232 [00:02<01:42, 69.38it/s]

Reports:   2%|▏         | 120/7232 [00:02<01:49, 64.77it/s]

Reports:   2%|▏         | 130/7232 [00:02<01:59, 59.36it/s]

Reports:   2%|▏         | 137/7232 [00:02<01:56, 61.06it/s]

Reports:   2%|▏         | 146/7232 [00:02<01:48, 65.57it/s]

Reports:   2%|▏         | 153/7232 [00:02<02:00, 58.93it/s]

Reports:   2%|▏         | 166/7232 [00:02<01:42, 68.88it/s]

Reports:   2%|▏         | 176/7232 [00:03<01:33, 75.80it/s]

Reports:   3%|▎         | 184/7232 [00:03<01:43, 67.79it/s]

Reports:   3%|▎         | 192/7232 [00:03<01:54, 61.47it/s]

Reports:   3%|▎         | 201/7232 [00:03<01:46, 65.95it/s]

Reports:   3%|▎         | 208/7232 [00:03<01:51, 62.97it/s]

Reports:   3%|▎         | 218/7232 [00:03<01:49, 64.14it/s]

Reports:   3%|▎         | 232/7232 [00:03<01:27, 79.84it/s]

Reports:   3%|▎         | 241/7232 [00:04<01:32, 75.95it/s]

Reports:   3%|▎         | 249/7232 [00:04<01:33, 74.96it/s]

Reports:   4%|▎         | 258/7232 [00:04<01:35, 72.72it/s]

Reports:   4%|▎         | 267/7232 [00:04<01:31, 76.23it/s]

Reports:   4%|▍         | 275/7232 [00:04<01:35, 72.53it/s]

Reports:   4%|▍         | 286/7232 [00:04<01:31, 76.24it/s]

Reports:   4%|▍         | 294/7232 [00:04<01:38, 70.74it/s]

Reports:   4%|▍         | 302/7232 [00:04<01:44, 66.52it/s]

Reports:   4%|▍         | 310/7232 [00:05<01:42, 67.79it/s]

Reports:   4%|▍         | 319/7232 [00:05<01:38, 70.18it/s]

Reports:   5%|▍         | 327/7232 [00:05<01:36, 71.74it/s]

Reports:   5%|▍         | 335/7232 [00:05<01:38, 70.27it/s]

Reports:   5%|▍         | 345/7232 [00:05<01:32, 74.37it/s]

Reports:   5%|▍         | 353/7232 [00:05<01:34, 72.71it/s]

Reports:   5%|▌         | 362/7232 [00:05<01:34, 72.55it/s]

Reports:   5%|▌         | 370/7232 [00:05<01:32, 74.23it/s]

Reports:   5%|▌         | 378/7232 [00:06<02:31, 45.10it/s]

Reports:   5%|▌         | 384/7232 [00:06<02:32, 44.91it/s]

Reports:   5%|▌         | 393/7232 [00:06<02:11, 51.87it/s]

Reports:   6%|▌         | 400/7232 [00:06<02:21, 48.16it/s]

Reports:   6%|▌         | 406/7232 [00:06<02:20, 48.52it/s]

Reports:   6%|▌         | 414/7232 [00:06<02:03, 55.04it/s]

Reports:   6%|▌         | 421/7232 [00:06<02:16, 49.99it/s]

Reports:   6%|▌         | 433/7232 [00:07<01:44, 65.05it/s]

Reports:   6%|▌         | 441/7232 [00:07<01:47, 63.06it/s]

Reports:   6%|▌         | 450/7232 [00:07<01:37, 69.39it/s]

Reports:   6%|▋         | 458/7232 [00:07<01:56, 57.98it/s]

Reports:   6%|▋         | 468/7232 [00:07<01:52, 60.33it/s]

Reports:   7%|▋         | 476/7232 [00:07<01:50, 61.31it/s]

Reports:   7%|▋         | 485/7232 [00:07<01:55, 58.43it/s]

Reports:   7%|▋         | 495/7232 [00:08<01:44, 64.60it/s]

Reports:   7%|▋         | 502/7232 [00:08<01:54, 58.86it/s]

Reports:   7%|▋         | 509/7232 [00:08<01:57, 57.09it/s]

Reports:   7%|▋         | 515/7232 [00:08<01:59, 56.10it/s]

Reports:   7%|▋         | 524/7232 [00:08<01:47, 62.29it/s]

Reports:   7%|▋         | 531/7232 [00:08<01:51, 60.17it/s]

Reports:   7%|▋         | 541/7232 [00:08<01:43, 64.70it/s]

Reports:   8%|▊         | 549/7232 [00:09<01:54, 58.41it/s]

Reports:   8%|▊         | 557/7232 [00:09<01:49, 61.07it/s]

Reports:   8%|▊         | 566/7232 [00:09<01:38, 67.60it/s]

Reports:   8%|▊         | 573/7232 [00:09<01:38, 67.44it/s]

Reports:   8%|▊         | 580/7232 [00:09<01:40, 65.91it/s]

Reports:   8%|▊         | 590/7232 [00:09<01:33, 71.23it/s]

Reports:   8%|▊         | 598/7232 [00:09<01:35, 69.79it/s]

Reports:   8%|▊         | 607/7232 [00:09<01:36, 68.54it/s]

Reports:   8%|▊         | 614/7232 [00:10<01:49, 60.36it/s]

Reports:   9%|▊         | 626/7232 [00:10<01:37, 67.86it/s]

Reports:   9%|▉         | 638/7232 [00:10<01:30, 72.78it/s]

Reports:   9%|▉         | 646/7232 [00:10<01:30, 72.87it/s]

Reports:   9%|▉         | 655/7232 [00:10<01:30, 72.33it/s]

Reports:   9%|▉         | 663/7232 [00:10<01:35, 68.64it/s]

Reports:   9%|▉         | 673/7232 [00:10<01:26, 75.55it/s]

Reports:   9%|▉         | 681/7232 [00:10<01:42, 63.85it/s]

Reports:  10%|▉         | 691/7232 [00:11<01:30, 72.01it/s]

Reports:  10%|▉         | 700/7232 [00:11<02:21, 46.16it/s]

Reports:  10%|▉         | 708/7232 [00:11<02:05, 52.03it/s]

Reports:  10%|▉         | 715/7232 [00:11<02:20, 46.51it/s]

Reports:  10%|█         | 725/7232 [00:11<02:03, 52.62it/s]

Reports:  10%|█         | 732/7232 [00:11<02:00, 53.97it/s]

Reports:  10%|█         | 739/7232 [00:12<01:55, 56.19it/s]

Reports:  10%|█         | 746/7232 [00:12<02:02, 52.85it/s]

Reports:  10%|█         | 757/7232 [00:12<01:48, 59.68it/s]

Reports:  11%|█         | 768/7232 [00:12<01:36, 67.25it/s]

Reports:  11%|█         | 775/7232 [00:12<01:39, 64.75it/s]

Reports:  11%|█         | 786/7232 [00:12<01:26, 74.55it/s]

Reports:  11%|█         | 794/7232 [00:12<01:29, 71.67it/s]

Reports:  11%|█         | 803/7232 [00:13<01:39, 64.54it/s]

Reports:  11%|█         | 813/7232 [00:13<01:28, 72.71it/s]

Reports:  11%|█▏        | 821/7232 [00:13<01:35, 67.07it/s]

Reports:  11%|█▏        | 830/7232 [00:13<01:35, 67.28it/s]

Reports:  12%|█▏        | 837/7232 [00:13<01:34, 67.54it/s]

Reports:  12%|█▏        | 846/7232 [00:13<01:28, 72.40it/s]

Reports:  12%|█▏        | 854/7232 [00:13<01:32, 69.16it/s]

Reports:  12%|█▏        | 864/7232 [00:13<01:29, 70.95it/s]

Reports:  12%|█▏        | 872/7232 [00:13<01:32, 68.69it/s]

Reports:  12%|█▏        | 881/7232 [00:14<01:37, 64.84it/s]

Reports:  12%|█▏        | 888/7232 [00:14<01:38, 64.12it/s]

Reports:  12%|█▏        | 897/7232 [00:14<01:34, 67.20it/s]

Reports:  13%|█▎        | 905/7232 [00:14<01:34, 66.77it/s]

Reports:  13%|█▎        | 914/7232 [00:14<01:28, 71.37it/s]

Reports:  13%|█▎        | 922/7232 [00:14<01:36, 65.50it/s]

Reports:  13%|█▎        | 931/7232 [00:14<01:32, 68.14it/s]

Reports:  13%|█▎        | 938/7232 [00:15<01:40, 62.58it/s]

Reports:  13%|█▎        | 947/7232 [00:15<01:30, 69.17it/s]

Reports:  13%|█▎        | 955/7232 [00:15<01:33, 67.11it/s]

Reports:  13%|█▎        | 963/7232 [00:15<01:30, 69.29it/s]

Reports:  13%|█▎        | 973/7232 [00:15<01:21, 76.76it/s]

Reports:  14%|█▎        | 981/7232 [00:15<01:30, 69.35it/s]

Reports:  14%|█▎        | 994/7232 [00:15<01:14, 83.65it/s]

Reports:  14%|█▍        | 1003/7232 [00:15<01:18, 79.45it/s]

Reports:  14%|█▍        | 1012/7232 [00:16<01:34, 65.74it/s]

Reports:  14%|█▍        | 1020/7232 [00:16<01:34, 65.77it/s]

Reports:  14%|█▍        | 1028/7232 [00:16<01:30, 68.61it/s]

Reports:  14%|█▍        | 1037/7232 [00:16<01:24, 73.59it/s]

Reports:  14%|█▍        | 1045/7232 [00:16<01:23, 73.85it/s]

Reports:  15%|█▍        | 1053/7232 [00:16<02:17, 44.84it/s]

Reports:  15%|█▍        | 1060/7232 [00:16<02:19, 44.15it/s]

Reports:  15%|█▍        | 1072/7232 [00:17<01:58, 51.90it/s]

Reports:  15%|█▍        | 1081/7232 [00:17<01:44, 58.60it/s]

Reports:  15%|█▌        | 1088/7232 [00:17<01:57, 52.26it/s]

Reports:  15%|█▌        | 1097/7232 [00:17<01:42, 59.75it/s]

Reports:  15%|█▌        | 1104/7232 [00:17<01:43, 59.44it/s]

Reports:  15%|█▌        | 1111/7232 [00:17<01:47, 56.72it/s]

Reports:  16%|█▌        | 1124/7232 [00:17<01:24, 72.48it/s]

Reports:  16%|█▌        | 1132/7232 [00:18<01:32, 66.22it/s]

Reports:  16%|█▌        | 1140/7232 [00:18<01:27, 69.46it/s]

Reports:  16%|█▌        | 1148/7232 [00:18<01:24, 71.69it/s]

Reports:  16%|█▌        | 1156/7232 [00:18<01:28, 68.61it/s]

Reports:  16%|█▌        | 1164/7232 [00:18<01:28, 68.62it/s]

Reports:  16%|█▌        | 1172/7232 [00:18<01:28, 68.59it/s]

Reports:  16%|█▋        | 1180/7232 [00:18<01:25, 71.12it/s]

Reports:  16%|█▋        | 1188/7232 [00:18<01:26, 69.87it/s]

Reports:  17%|█▋        | 1196/7232 [00:18<01:23, 71.98it/s]

Reports:  17%|█▋        | 1204/7232 [00:19<01:30, 66.55it/s]

Reports:  17%|█▋        | 1212/7232 [00:19<01:27, 68.58it/s]

Reports:  17%|█▋        | 1219/7232 [00:19<01:28, 67.81it/s]

Reports:  17%|█▋        | 1227/7232 [00:19<01:24, 70.89it/s]

Reports:  17%|█▋        | 1235/7232 [00:19<01:35, 62.82it/s]

Reports:  17%|█▋        | 1244/7232 [00:19<01:35, 62.87it/s]

Reports:  17%|█▋        | 1253/7232 [00:19<01:37, 61.08it/s]

Reports:  17%|█▋        | 1263/7232 [00:20<01:34, 63.38it/s]

Reports:  18%|█▊        | 1276/7232 [00:20<01:21, 73.36it/s]

Reports:  18%|█▊        | 1284/7232 [00:20<01:19, 74.67it/s]

Reports:  18%|█▊        | 1292/7232 [00:20<01:19, 74.83it/s]

Reports:  18%|█▊        | 1300/7232 [00:20<01:21, 72.84it/s]

Reports:  18%|█▊        | 1308/7232 [00:20<01:36, 61.33it/s]

Reports:  18%|█▊        | 1319/7232 [00:20<01:24, 70.39it/s]

Reports:  18%|█▊        | 1327/7232 [00:20<01:27, 67.68it/s]

Reports:  18%|█▊        | 1335/7232 [00:21<01:25, 68.57it/s]

Reports:  19%|█▊        | 1343/7232 [00:21<01:25, 68.95it/s]

Reports:  19%|█▊        | 1352/7232 [00:21<01:29, 65.80it/s]

Reports:  19%|█▉        | 1360/7232 [00:21<01:29, 65.63it/s]

Reports:  19%|█▉        | 1370/7232 [00:21<01:22, 71.32it/s]

Reports:  19%|█▉        | 1378/7232 [00:21<01:19, 73.48it/s]

Reports:  19%|█▉        | 1387/7232 [00:21<01:15, 77.36it/s]

Reports:  19%|█▉        | 1395/7232 [00:22<02:24, 40.53it/s]

Reports:  19%|█▉        | 1402/7232 [00:22<02:24, 40.48it/s]

Reports:  20%|█▉        | 1412/7232 [00:22<01:54, 50.72it/s]

Reports:  20%|█▉        | 1419/7232 [00:22<01:56, 50.06it/s]

Reports:  20%|█▉        | 1426/7232 [00:22<01:51, 52.18it/s]

Reports:  20%|█▉        | 1434/7232 [00:22<01:44, 55.35it/s]

Reports:  20%|█▉        | 1444/7232 [00:23<01:49, 52.65it/s]

Reports:  20%|██        | 1457/7232 [00:23<01:24, 68.41it/s]

Reports:  20%|██        | 1465/7232 [00:23<01:23, 69.11it/s]

Reports:  20%|██        | 1474/7232 [00:23<01:24, 67.91it/s]

Reports:  20%|██        | 1482/7232 [00:23<01:37, 59.22it/s]

Reports:  21%|██        | 1493/7232 [00:23<01:25, 67.29it/s]

Reports:  21%|██        | 1501/7232 [00:23<01:34, 60.71it/s]

Reports:  21%|██        | 1512/7232 [00:23<01:20, 71.01it/s]

Reports:  21%|██        | 1520/7232 [00:24<01:19, 71.92it/s]

Reports:  21%|██        | 1528/7232 [00:24<01:19, 71.73it/s]

Reports:  21%|██        | 1536/7232 [00:24<01:20, 70.62it/s]

Reports:  21%|██▏       | 1544/7232 [00:24<01:24, 67.41it/s]

Reports:  21%|██▏       | 1551/7232 [00:24<01:26, 65.92it/s]

Reports:  22%|██▏       | 1560/7232 [00:24<01:21, 69.54it/s]

Reports:  22%|██▏       | 1568/7232 [00:24<01:19, 70.93it/s]

Reports:  22%|██▏       | 1576/7232 [00:24<01:43, 54.79it/s]

Reports:  22%|██▏       | 1584/7232 [00:25<01:36, 58.25it/s]

Reports:  22%|██▏       | 1591/7232 [00:25<01:35, 59.32it/s]

Reports:  22%|██▏       | 1599/7232 [00:25<01:28, 63.31it/s]

Reports:  22%|██▏       | 1606/7232 [00:25<01:41, 55.21it/s]

Reports:  22%|██▏       | 1616/7232 [00:25<01:26, 65.15it/s]

Reports:  22%|██▏       | 1623/7232 [00:25<01:30, 62.06it/s]

Reports:  23%|██▎       | 1631/7232 [00:25<01:26, 64.57it/s]

Reports:  23%|██▎       | 1638/7232 [00:25<01:32, 60.55it/s]

Reports:  23%|██▎       | 1647/7232 [00:26<01:35, 58.78it/s]

Reports:  23%|██▎       | 1659/7232 [00:26<01:17, 71.71it/s]

Reports:  23%|██▎       | 1667/7232 [00:26<01:29, 62.34it/s]

Reports:  23%|██▎       | 1675/7232 [00:26<01:34, 58.74it/s]

Reports:  23%|██▎       | 1687/7232 [00:26<01:17, 71.52it/s]

Reports:  23%|██▎       | 1695/7232 [00:26<01:26, 63.66it/s]

Reports:  24%|██▎       | 1703/7232 [00:26<01:32, 59.66it/s]

Reports:  24%|██▍       | 1719/7232 [00:27<01:42, 53.64it/s]

Reports:  24%|██▍       | 1725/7232 [00:27<02:11, 41.96it/s]

Reports:  24%|██▍       | 1730/7232 [00:27<02:12, 41.44it/s]

Reports:  24%|██▍       | 1735/7232 [00:27<02:19, 39.40it/s]

Reports:  24%|██▍       | 1743/7232 [00:28<02:17, 39.96it/s]

Reports:  24%|██▍       | 1751/7232 [00:28<02:17, 39.93it/s]

Reports:  24%|██▍       | 1765/7232 [00:28<01:51, 49.22it/s]

Reports:  25%|██▍       | 1777/7232 [00:28<01:34, 57.70it/s]

Reports:  25%|██▍       | 1784/7232 [00:28<01:40, 54.30it/s]

Reports:  25%|██▍       | 1793/7232 [00:28<01:38, 55.41it/s]

Reports:  25%|██▍       | 1804/7232 [00:29<01:25, 63.77it/s]

Reports:  25%|██▌       | 1811/7232 [00:29<01:30, 59.63it/s]

Reports:  25%|██▌       | 1821/7232 [00:29<01:19, 68.23it/s]

Reports:  25%|██▌       | 1829/7232 [00:29<01:26, 62.26it/s]

Reports:  25%|██▌       | 1841/7232 [00:29<01:21, 66.05it/s]

Reports:  26%|██▌       | 1848/7232 [00:29<01:20, 66.84it/s]

Reports:  26%|██▌       | 1857/7232 [00:29<01:14, 72.01it/s]

Reports:  26%|██▌       | 1865/7232 [00:29<01:24, 63.25it/s]

Reports:  26%|██▌       | 1875/7232 [00:30<01:14, 71.53it/s]

Reports:  26%|██▌       | 1883/7232 [00:30<01:20, 66.85it/s]

Reports:  26%|██▌       | 1891/7232 [00:30<01:17, 68.62it/s]

Reports:  26%|██▋       | 1899/7232 [00:30<01:21, 65.47it/s]

Reports:  26%|██▋       | 1909/7232 [00:30<01:24, 62.71it/s]

Reports:  26%|██▋       | 1916/7232 [00:30<01:35, 55.50it/s]

Reports:  27%|██▋       | 1929/7232 [00:30<01:19, 67.12it/s]

Reports:  27%|██▋       | 1936/7232 [00:31<01:28, 59.67it/s]

Reports:  27%|██▋       | 1946/7232 [00:31<01:18, 67.37it/s]

Reports:  27%|██▋       | 1954/7232 [00:31<01:16, 68.74it/s]

Reports:  27%|██▋       | 1962/7232 [00:31<01:17, 68.07it/s]

Reports:  27%|██▋       | 1970/7232 [00:31<01:14, 70.44it/s]

Reports:  27%|██▋       | 1978/7232 [00:31<01:18, 67.15it/s]

Reports:  27%|██▋       | 1985/7232 [00:31<01:24, 62.17it/s]

Reports:  28%|██▊       | 1996/7232 [00:31<01:10, 73.75it/s]

Reports:  28%|██▊       | 2004/7232 [00:32<01:15, 69.09it/s]

Reports:  28%|██▊       | 2012/7232 [00:32<01:17, 66.93it/s]

Reports:  28%|██▊       | 2020/7232 [00:32<01:16, 68.58it/s]

Reports:  28%|██▊       | 2028/7232 [00:32<01:17, 67.32it/s]

Reports:  28%|██▊       | 2035/7232 [00:32<01:20, 64.18it/s]

Reports:  28%|██▊       | 2045/7232 [00:32<01:17, 66.87it/s]

Reports:  28%|██▊       | 2052/7232 [00:32<01:30, 57.55it/s]

Reports:  29%|██▊       | 2062/7232 [00:32<01:24, 61.35it/s]

Reports:  29%|██▊       | 2073/7232 [00:33<01:13, 70.41it/s]

Reports:  29%|██▉       | 2081/7232 [00:33<01:14, 68.72it/s]

Reports:  29%|██▉       | 2092/7232 [00:33<01:05, 78.60it/s]

Reports:  29%|██▉       | 2101/7232 [00:33<01:50, 46.28it/s]

Reports:  29%|██▉       | 2108/7232 [00:33<01:46, 47.90it/s]

Reports:  29%|██▉       | 2116/7232 [00:33<01:38, 51.68it/s]

Reports:  29%|██▉       | 2123/7232 [00:34<01:49, 46.83it/s]

Reports:  29%|██▉       | 2132/7232 [00:34<01:39, 51.15it/s]

Reports:  30%|██▉       | 2138/7232 [00:34<01:41, 50.08it/s]

Reports:  30%|██▉       | 2151/7232 [00:34<01:25, 59.52it/s]

Reports:  30%|██▉       | 2164/7232 [00:34<01:08, 74.39it/s]

Reports:  30%|███       | 2173/7232 [00:35<01:35, 53.03it/s]

Reports:  30%|███       | 2184/7232 [00:35<01:27, 57.76it/s]

Reports:  30%|███       | 2191/7232 [00:35<01:24, 59.49it/s]

Reports:  30%|███       | 2200/7232 [00:35<01:20, 62.31it/s]

Reports:  31%|███       | 2207/7232 [00:35<01:21, 61.86it/s]

Reports:  31%|███       | 2216/7232 [00:35<01:17, 64.36it/s]

Reports:  31%|███       | 2228/7232 [00:35<01:10, 71.36it/s]

Reports:  31%|███       | 2236/7232 [00:35<01:10, 70.74it/s]

Reports:  31%|███       | 2245/7232 [00:35<01:06, 74.46it/s]

Reports:  31%|███       | 2253/7232 [00:36<01:10, 71.06it/s]

Reports:  31%|███▏      | 2263/7232 [00:36<01:03, 77.94it/s]

Reports:  31%|███▏      | 2271/7232 [00:36<01:10, 70.35it/s]

Reports:  32%|███▏      | 2280/7232 [00:36<01:06, 74.29it/s]

Reports:  32%|███▏      | 2288/7232 [00:36<01:11, 68.87it/s]

Reports:  32%|███▏      | 2297/7232 [00:36<01:08, 72.51it/s]

Reports:  32%|███▏      | 2305/7232 [00:36<01:09, 70.72it/s]

Reports:  32%|███▏      | 2315/7232 [00:37<01:12, 68.12it/s]

Reports:  32%|███▏      | 2326/7232 [00:37<01:03, 77.37it/s]

Reports:  32%|███▏      | 2334/7232 [00:37<01:13, 66.34it/s]

Reports:  32%|███▏      | 2346/7232 [00:37<01:02, 77.98it/s]

Reports:  33%|███▎      | 2355/7232 [00:37<01:08, 71.62it/s]

Reports:  33%|███▎      | 2363/7232 [00:37<01:08, 71.33it/s]

Reports:  33%|███▎      | 2371/7232 [00:37<01:11, 67.92it/s]

Reports:  33%|███▎      | 2382/7232 [00:37<01:06, 73.26it/s]

Reports:  33%|███▎      | 2390/7232 [00:38<01:11, 67.87it/s]

Reports:  33%|███▎      | 2398/7232 [00:38<01:11, 67.59it/s]

Reports:  33%|███▎      | 2405/7232 [00:38<01:13, 65.47it/s]

Reports:  33%|███▎      | 2415/7232 [00:38<01:10, 68.70it/s]

Reports:  33%|███▎      | 2422/7232 [00:38<01:12, 66.75it/s]

Reports:  34%|███▎      | 2431/7232 [00:38<01:07, 70.84it/s]

Reports:  34%|███▎      | 2439/7232 [00:38<01:10, 68.39it/s]

Reports:  34%|███▍      | 2446/7232 [00:39<01:46, 44.92it/s]

Reports:  34%|███▍      | 2452/7232 [00:39<01:56, 41.19it/s]

Reports:  34%|███▍      | 2460/7232 [00:39<01:38, 48.47it/s]

Reports:  34%|███▍      | 2466/7232 [00:39<01:43, 45.97it/s]

Reports:  34%|███▍      | 2473/7232 [00:39<01:40, 47.24it/s]

Reports:  34%|███▍      | 2479/7232 [00:39<01:39, 47.95it/s]

Reports:  34%|███▍      | 2485/7232 [00:39<01:48, 43.94it/s]

Reports:  34%|███▍      | 2495/7232 [00:40<01:27, 54.07it/s]

Reports:  35%|███▍      | 2502/7232 [00:40<01:23, 56.34it/s]

Reports:  35%|███▍      | 2511/7232 [00:40<01:18, 59.97it/s]

Reports:  35%|███▍      | 2520/7232 [00:40<01:15, 62.43it/s]

Reports:  35%|███▍      | 2529/7232 [00:40<01:09, 67.45it/s]

Reports:  35%|███▌      | 2536/7232 [00:40<01:23, 56.18it/s]

Reports:  35%|███▌      | 2542/7232 [00:40<01:22, 56.87it/s]

Reports:  35%|███▌      | 2551/7232 [00:40<01:23, 55.78it/s]

Reports:  35%|███▌      | 2557/7232 [00:41<01:22, 56.33it/s]

Reports:  36%|███▌      | 2568/7232 [00:41<01:15, 62.09it/s]

Reports:  36%|███▌      | 2579/7232 [00:41<01:07, 69.32it/s]

Reports:  36%|███▌      | 2587/7232 [00:41<01:10, 66.00it/s]

Reports:  36%|███▌      | 2598/7232 [00:41<01:12, 63.76it/s]

Reports:  36%|███▌      | 2606/7232 [00:41<01:08, 67.16it/s]

Reports:  36%|███▌      | 2614/7232 [00:41<01:17, 59.63it/s]

Reports:  36%|███▋      | 2624/7232 [00:42<01:11, 64.35it/s]

Reports:  36%|███▋      | 2632/7232 [00:42<01:10, 65.18it/s]

Reports:  37%|███▋      | 2642/7232 [00:42<01:06, 69.30it/s]

Reports:  37%|███▋      | 2650/7232 [00:42<01:10, 64.93it/s]

Reports:  37%|███▋      | 2661/7232 [00:42<01:01, 73.74it/s]

Reports:  37%|███▋      | 2669/7232 [00:42<01:08, 66.39it/s]

Reports:  37%|███▋      | 2679/7232 [00:42<01:01, 74.06it/s]

Reports:  37%|███▋      | 2687/7232 [00:42<01:05, 69.07it/s]

Reports:  37%|███▋      | 2696/7232 [00:43<01:07, 67.58it/s]

Reports:  37%|███▋      | 2705/7232 [00:43<01:07, 67.30it/s]

Reports:  38%|███▊      | 2715/7232 [00:43<01:09, 65.10it/s]

Reports:  38%|███▊      | 2723/7232 [00:43<01:07, 66.77it/s]

Reports:  38%|███▊      | 2731/7232 [00:43<01:05, 69.12it/s]

Reports:  38%|███▊      | 2741/7232 [00:43<01:13, 61.33it/s]

Reports:  38%|███▊      | 2748/7232 [00:43<01:17, 58.18it/s]

Reports:  38%|███▊      | 2757/7232 [00:44<01:09, 64.32it/s]

Reports:  38%|███▊      | 2764/7232 [00:44<02:20, 31.70it/s]

Reports:  38%|███▊      | 2773/7232 [00:44<01:59, 37.26it/s]

Reports:  38%|███▊      | 2779/7232 [00:44<01:57, 38.03it/s]

Reports:  39%|███▊      | 2786/7232 [00:45<01:52, 39.38it/s]

Reports:  39%|███▊      | 2797/7232 [00:45<01:50, 40.06it/s]

Reports:  39%|███▉      | 2806/7232 [00:45<01:32, 47.65it/s]

Reports:  39%|███▉      | 2815/7232 [00:45<01:33, 47.20it/s]

Reports:  39%|███▉      | 2831/7232 [00:45<01:26, 51.16it/s]

Reports:  39%|███▉      | 2847/7232 [00:46<01:06, 65.71it/s]

Reports:  40%|███▉      | 2860/7232 [00:46<00:56, 77.53it/s]

Reports:  40%|███▉      | 2870/7232 [00:46<01:00, 71.85it/s]

Reports:  40%|███▉      | 2879/7232 [00:46<01:00, 71.57it/s]

Reports:  40%|███▉      | 2887/7232 [00:46<01:00, 71.66it/s]

Reports:  40%|████      | 2897/7232 [00:46<01:03, 68.76it/s]

Reports:  40%|████      | 2910/7232 [00:46<00:56, 76.50it/s]

Reports:  40%|████      | 2918/7232 [00:47<01:07, 63.78it/s]

Reports:  40%|████      | 2927/7232 [00:47<01:02, 68.44it/s]

Reports:  41%|████      | 2935/7232 [00:47<01:10, 61.31it/s]

Reports:  41%|████      | 2946/7232 [00:47<01:01, 69.55it/s]

Reports:  41%|████      | 2954/7232 [00:47<01:04, 66.29it/s]

Reports:  41%|████      | 2963/7232 [00:47<01:08, 62.66it/s]

Reports:  41%|████      | 2977/7232 [00:47<00:54, 77.97it/s]

Reports:  41%|████▏     | 2986/7232 [00:48<01:09, 60.88it/s]

Reports:  41%|████▏     | 2995/7232 [00:48<01:06, 63.91it/s]

Reports:  42%|████▏     | 3003/7232 [00:48<01:15, 55.91it/s]

Reports:  42%|████▏     | 3017/7232 [00:48<00:58, 71.95it/s]

Reports:  42%|████▏     | 3026/7232 [00:48<01:06, 63.65it/s]

Reports:  42%|████▏     | 3034/7232 [00:48<01:03, 66.31it/s]

Reports:  42%|████▏     | 3042/7232 [00:48<01:01, 67.87it/s]

Reports:  42%|████▏     | 3050/7232 [00:49<01:08, 61.38it/s]

Reports:  42%|████▏     | 3057/7232 [00:49<01:07, 61.85it/s]

Reports:  42%|████▏     | 3066/7232 [00:49<01:10, 59.40it/s]

Reports:  42%|████▏     | 3073/7232 [00:49<01:45, 39.40it/s]

Reports:  43%|████▎     | 3078/7232 [00:49<01:43, 39.96it/s]

Reports:  43%|████▎     | 3083/7232 [00:50<02:04, 33.42it/s]

Reports:  43%|████▎     | 3090/7232 [00:50<01:43, 39.88it/s]

Reports:  43%|████▎     | 3095/7232 [00:50<01:44, 39.48it/s]

Reports:  43%|████▎     | 3103/7232 [00:50<01:27, 47.08it/s]

Reports:  43%|████▎     | 3112/7232 [00:50<01:20, 50.98it/s]

Reports:  43%|████▎     | 3121/7232 [00:50<01:15, 54.74it/s]

Reports:  43%|████▎     | 3130/7232 [00:50<01:05, 62.30it/s]

Reports:  43%|████▎     | 3138/7232 [00:50<01:10, 57.66it/s]

Reports:  44%|████▎     | 3149/7232 [00:51<00:59, 68.42it/s]

Reports:  44%|████▎     | 3157/7232 [00:51<01:01, 66.06it/s]

Reports:  44%|████▍     | 3168/7232 [00:51<00:54, 73.98it/s]

Reports:  44%|████▍     | 3176/7232 [00:51<00:58, 69.67it/s]

Reports:  44%|████▍     | 3185/7232 [00:51<00:54, 74.64it/s]

Reports:  44%|████▍     | 3193/7232 [00:51<00:59, 67.45it/s]

Reports:  44%|████▍     | 3201/7232 [00:51<00:59, 67.54it/s]

Reports:  44%|████▍     | 3208/7232 [00:52<01:09, 57.87it/s]

Reports:  44%|████▍     | 3215/7232 [00:52<01:08, 58.80it/s]

Reports:  45%|████▍     | 3222/7232 [00:52<01:08, 58.12it/s]

Reports:  45%|████▍     | 3231/7232 [00:52<01:04, 62.50it/s]

Reports:  45%|████▍     | 3243/7232 [00:52<00:57, 69.81it/s]

Reports:  45%|████▍     | 3251/7232 [00:52<00:58, 68.28it/s]

Reports:  45%|████▌     | 3259/7232 [00:52<00:58, 67.99it/s]

Reports:  45%|████▌     | 3266/7232 [00:52<01:06, 59.65it/s]

Reports:  45%|████▌     | 3277/7232 [00:53<00:55, 71.51it/s]

Reports:  45%|████▌     | 3285/7232 [00:53<01:03, 62.23it/s]

Reports:  46%|████▌     | 3297/7232 [00:53<00:52, 74.35it/s]

Reports:  46%|████▌     | 3305/7232 [00:53<01:00, 64.38it/s]

Reports:  46%|████▌     | 3315/7232 [00:53<00:57, 68.24it/s]

Reports:  46%|████▌     | 3323/7232 [00:53<01:01, 64.00it/s]

Reports:  46%|████▌     | 3332/7232 [00:53<00:58, 66.75it/s]

Reports:  46%|████▌     | 3340/7232 [00:53<00:58, 66.54it/s]

Reports:  46%|████▋     | 3348/7232 [00:54<00:58, 65.84it/s]

Reports:  46%|████▋     | 3359/7232 [00:54<00:52, 73.21it/s]

Reports:  47%|████▋     | 3367/7232 [00:54<00:57, 67.30it/s]

Reports:  47%|████▋     | 3375/7232 [00:54<01:00, 63.26it/s]

Reports:  47%|████▋     | 3384/7232 [00:54<00:58, 65.54it/s]

Reports:  47%|████▋     | 3393/7232 [00:54<00:57, 67.31it/s]

Reports:  47%|████▋     | 3400/7232 [00:55<01:24, 45.53it/s]

Reports:  47%|████▋     | 3406/7232 [00:55<01:32, 41.33it/s]

Reports:  47%|████▋     | 3417/7232 [00:55<01:13, 51.74it/s]

Reports:  47%|████▋     | 3423/7232 [00:55<01:17, 48.91it/s]

Reports:  47%|████▋     | 3435/7232 [00:55<01:02, 60.34it/s]

Reports:  48%|████▊     | 3442/7232 [00:55<01:04, 58.75it/s]

Reports:  48%|████▊     | 3451/7232 [00:55<01:06, 56.72it/s]

Reports:  48%|████▊     | 3467/7232 [00:56<00:58, 64.35it/s]

Reports:  48%|████▊     | 3475/7232 [00:56<00:56, 66.57it/s]

Reports:  48%|████▊     | 3482/7232 [00:56<01:10, 53.15it/s]

Reports:  48%|████▊     | 3492/7232 [00:56<01:14, 50.48it/s]

Reports:  49%|████▊     | 3508/7232 [00:56<01:00, 61.13it/s]

Reports:  49%|████▊     | 3522/7232 [00:57<00:50, 72.87it/s]

Reports:  49%|████▉     | 3530/7232 [00:57<00:52, 70.01it/s]

Reports:  49%|████▉     | 3538/7232 [00:57<00:53, 69.21it/s]

Reports:  49%|████▉     | 3548/7232 [00:57<00:56, 65.70it/s]

Reports:  49%|████▉     | 3556/7232 [00:57<00:54, 67.72it/s]

Reports:  49%|████▉     | 3566/7232 [00:57<00:51, 71.27it/s]

Reports:  49%|████▉     | 3574/7232 [00:57<00:54, 67.59it/s]

Reports:  50%|████▉     | 3581/7232 [00:57<00:53, 68.16it/s]

Reports:  50%|████▉     | 3589/7232 [00:58<00:54, 67.28it/s]

Reports:  50%|████▉     | 3596/7232 [00:58<00:58, 62.68it/s]

Reports:  50%|████▉     | 3608/7232 [00:58<00:47, 76.34it/s]

Reports:  50%|█████     | 3616/7232 [00:58<00:49, 73.62it/s]

Reports:  50%|█████     | 3625/7232 [00:58<00:51, 69.41it/s]

Reports:  50%|█████     | 3637/7232 [00:58<00:43, 82.12it/s]

Reports:  50%|█████     | 3646/7232 [00:58<00:49, 72.86it/s]

Reports:  51%|█████     | 3657/7232 [00:58<00:47, 74.81it/s]

Reports:  51%|█████     | 3665/7232 [00:59<00:49, 71.99it/s]

Reports:  51%|█████     | 3674/7232 [00:59<00:47, 75.12it/s]

Reports:  51%|█████     | 3682/7232 [00:59<00:50, 70.93it/s]

Reports:  51%|█████     | 3690/7232 [00:59<00:51, 69.29it/s]

Reports:  51%|█████     | 3698/7232 [00:59<00:51, 68.24it/s]

Reports:  51%|█████▏    | 3707/7232 [00:59<00:47, 73.68it/s]

Reports:  51%|█████▏    | 3715/7232 [00:59<00:52, 66.69it/s]

Reports:  52%|█████▏    | 3725/7232 [00:59<00:46, 74.95it/s]

Reports:  52%|█████▏    | 3733/7232 [01:00<00:49, 70.09it/s]

Reports:  52%|█████▏    | 3745/7232 [01:00<01:05, 53.58it/s]

Reports:  52%|█████▏    | 3752/7232 [01:00<01:03, 54.42it/s]

Reports:  52%|█████▏    | 3759/7232 [01:00<01:10, 49.12it/s]

Reports:  52%|█████▏    | 3770/7232 [01:00<00:59, 58.10it/s]

Reports:  52%|█████▏    | 3777/7232 [01:00<01:00, 57.55it/s]

Reports:  52%|█████▏    | 3787/7232 [01:01<01:04, 53.44it/s]

Reports:  53%|█████▎    | 3802/7232 [01:01<00:54, 63.07it/s]

Reports:  53%|█████▎    | 3810/7232 [01:01<00:52, 65.26it/s]

Reports:  53%|█████▎    | 3818/7232 [01:01<00:56, 59.94it/s]

Reports:  53%|█████▎    | 3828/7232 [01:01<00:51, 66.70it/s]

Reports:  53%|█████▎    | 3836/7232 [01:01<00:49, 68.51it/s]

Reports:  53%|█████▎    | 3844/7232 [01:01<00:49, 69.10it/s]

Reports:  53%|█████▎    | 3852/7232 [01:01<00:47, 71.75it/s]

Reports:  53%|█████▎    | 3860/7232 [01:02<00:47, 71.07it/s]

Reports:  53%|█████▎    | 3868/7232 [01:02<00:55, 60.73it/s]

Reports:  54%|█████▎    | 3879/7232 [01:02<00:54, 62.01it/s]

Reports:  54%|█████▎    | 3886/7232 [01:02<00:53, 62.84it/s]

Reports:  54%|█████▍    | 3895/7232 [01:02<00:48, 68.21it/s]

Reports:  54%|█████▍    | 3903/7232 [01:02<00:49, 66.80it/s]

Reports:  54%|█████▍    | 3912/7232 [01:02<00:45, 72.60it/s]

Reports:  54%|█████▍    | 3920/7232 [01:03<00:49, 66.51it/s]

Reports:  54%|█████▍    | 3928/7232 [01:03<00:49, 66.74it/s]

Reports:  54%|█████▍    | 3935/7232 [01:03<00:56, 58.69it/s]

Reports:  55%|█████▍    | 3948/7232 [01:03<00:50, 65.54it/s]

Reports:  55%|█████▍    | 3961/7232 [01:03<00:42, 77.32it/s]

Reports:  55%|█████▍    | 3969/7232 [01:03<00:49, 65.51it/s]

Reports:  55%|█████▌    | 3980/7232 [01:03<00:48, 66.57it/s]

Reports:  55%|█████▌    | 3990/7232 [01:04<00:44, 72.47it/s]

Reports:  55%|█████▌    | 3998/7232 [01:04<00:44, 72.24it/s]

Reports:  55%|█████▌    | 4010/7232 [01:04<00:38, 83.85it/s]

Reports:  56%|█████▌    | 4019/7232 [01:04<00:46, 69.77it/s]

Reports:  56%|█████▌    | 4028/7232 [01:04<00:45, 70.83it/s]

Reports:  56%|█████▌    | 4037/7232 [01:04<00:42, 74.86it/s]

Reports:  56%|█████▌    | 4045/7232 [01:04<00:43, 72.52it/s]

Reports:  56%|█████▌    | 4053/7232 [01:04<00:45, 69.18it/s]

Reports:  56%|█████▌    | 4063/7232 [01:05<00:43, 72.34it/s]

Reports:  56%|█████▋    | 4074/7232 [01:05<00:39, 80.66it/s]

Reports:  56%|█████▋    | 4083/7232 [01:05<00:43, 72.32it/s]

Reports:  57%|█████▋    | 4094/7232 [01:05<00:42, 74.71it/s]

Reports:  57%|█████▋    | 4102/7232 [01:05<00:43, 72.35it/s]

Reports:  57%|█████▋    | 4112/7232 [01:05<00:42, 73.69it/s]

Reports:  57%|█████▋    | 4120/7232 [01:05<00:42, 73.29it/s]

Reports:  57%|█████▋    | 4128/7232 [01:05<00:42, 73.62it/s]

Reports:  57%|█████▋    | 4137/7232 [01:06<00:44, 68.88it/s]

Reports:  57%|█████▋    | 4146/7232 [01:06<00:43, 71.33it/s]

Reports:  57%|█████▋    | 4154/7232 [01:06<00:42, 73.06it/s]

Reports:  58%|█████▊    | 4162/7232 [01:06<00:43, 70.21it/s]

Reports:  58%|█████▊    | 4170/7232 [01:06<00:44, 68.11it/s]

Reports:  58%|█████▊    | 4185/7232 [01:06<00:42, 72.40it/s]

Reports:  58%|█████▊    | 4193/7232 [01:07<01:12, 42.17it/s]

Reports:  58%|█████▊    | 4201/7232 [01:07<01:05, 46.25it/s]

Reports:  58%|█████▊    | 4208/7232 [01:07<01:03, 47.82it/s]

Reports:  58%|█████▊    | 4216/7232 [01:07<00:56, 53.82it/s]

Reports:  58%|█████▊    | 4225/7232 [01:07<00:50, 59.60it/s]

Reports:  59%|█████▊    | 4232/7232 [01:07<00:51, 57.85it/s]

Reports:  59%|█████▊    | 4242/7232 [01:07<00:44, 67.47it/s]

Reports:  59%|█████▉    | 4250/7232 [01:07<00:43, 68.58it/s]

Reports:  59%|█████▉    | 4259/7232 [01:08<00:40, 73.54it/s]

Reports:  59%|█████▉    | 4267/7232 [01:08<00:40, 72.98it/s]

Reports:  59%|█████▉    | 4277/7232 [01:08<00:40, 73.41it/s]

Reports:  59%|█████▉    | 4285/7232 [01:08<00:43, 68.12it/s]

Reports:  59%|█████▉    | 4295/7232 [01:08<00:39, 73.58it/s]

Reports:  59%|█████▉    | 4303/7232 [01:08<00:46, 63.58it/s]

Reports:  60%|█████▉    | 4316/7232 [01:08<00:41, 70.59it/s]

Reports:  60%|█████▉    | 4325/7232 [01:09<00:41, 70.44it/s]

Reports:  60%|█████▉    | 4335/7232 [01:09<00:40, 72.14it/s]

Reports:  60%|██████    | 4348/7232 [01:09<00:41, 68.80it/s]

Reports:  60%|██████    | 4359/7232 [01:09<00:37, 77.52it/s]

Reports:  60%|██████    | 4368/7232 [01:09<00:41, 69.35it/s]

Reports:  61%|██████    | 4380/7232 [01:09<00:40, 70.45it/s]

Reports:  61%|██████    | 4394/7232 [01:09<00:33, 85.33it/s]

Reports:  61%|██████    | 4404/7232 [01:10<00:37, 74.94it/s]

Reports:  61%|██████    | 4413/7232 [01:10<00:40, 70.29it/s]

Reports:  61%|██████    | 4422/7232 [01:10<00:38, 73.17it/s]

Reports:  61%|██████▏   | 4430/7232 [01:10<00:43, 64.75it/s]

Reports:  61%|██████▏   | 4437/7232 [01:10<00:46, 59.98it/s]

Reports:  62%|██████▏   | 4448/7232 [01:10<00:41, 66.64it/s]

Reports:  62%|██████▏   | 4457/7232 [01:10<00:38, 71.65it/s]

Reports:  62%|██████▏   | 4465/7232 [01:10<00:38, 72.44it/s]

Reports:  62%|██████▏   | 4474/7232 [01:11<00:35, 76.85it/s]

Reports:  62%|██████▏   | 4482/7232 [01:11<00:38, 71.20it/s]

Reports:  62%|██████▏   | 4490/7232 [01:11<00:37, 72.62it/s]

Reports:  62%|██████▏   | 4501/7232 [01:11<00:37, 72.16it/s]

Reports:  62%|██████▏   | 4512/7232 [01:11<00:33, 80.16it/s]

Reports:  63%|██████▎   | 4521/7232 [01:11<00:37, 72.40it/s]

Reports:  63%|██████▎   | 4533/7232 [01:11<00:36, 73.18it/s]

Reports:  63%|██████▎   | 4547/7232 [01:12<00:30, 87.47it/s]

Reports:  63%|██████▎   | 4557/7232 [01:12<01:02, 42.84it/s]

Reports:  63%|██████▎   | 4564/7232 [01:12<00:58, 45.56it/s]

Reports:  63%|██████▎   | 4573/7232 [01:12<00:53, 49.78it/s]

Reports:  63%|██████▎   | 4583/7232 [01:12<00:44, 58.88it/s]

Reports:  63%|██████▎   | 4591/7232 [01:13<00:49, 53.02it/s]

Reports:  64%|██████▎   | 4598/7232 [01:13<00:47, 55.87it/s]

Reports:  64%|██████▎   | 4607/7232 [01:13<00:46, 57.05it/s]

Reports:  64%|██████▍   | 4614/7232 [01:13<00:43, 59.66it/s]

Reports:  64%|██████▍   | 4623/7232 [01:13<00:40, 65.03it/s]

Reports:  64%|██████▍   | 4631/7232 [01:13<00:38, 67.07it/s]

Reports:  64%|██████▍   | 4639/7232 [01:13<00:45, 56.84it/s]

Reports:  64%|██████▍   | 4654/7232 [01:13<00:33, 77.37it/s]

Reports:  64%|██████▍   | 4663/7232 [01:14<00:37, 68.11it/s]

Reports:  65%|██████▍   | 4671/7232 [01:14<00:39, 65.25it/s]

Reports:  65%|██████▍   | 4680/7232 [01:14<00:38, 65.92it/s]

Reports:  65%|██████▍   | 4688/7232 [01:14<00:37, 67.65it/s]

Reports:  65%|██████▍   | 4696/7232 [01:14<00:36, 70.42it/s]

Reports:  65%|██████▌   | 4704/7232 [01:14<00:37, 67.13it/s]

Reports:  65%|██████▌   | 4711/7232 [01:14<00:40, 62.48it/s]

Reports:  65%|██████▌   | 4723/7232 [01:15<00:36, 69.06it/s]

Reports:  65%|██████▌   | 4732/7232 [01:15<00:33, 74.08it/s]

Reports:  66%|██████▌   | 4740/7232 [01:15<00:35, 69.54it/s]

Reports:  66%|██████▌   | 4748/7232 [01:15<00:35, 69.23it/s]

Reports:  66%|██████▌   | 4757/7232 [01:15<00:33, 72.88it/s]

Reports:  66%|██████▌   | 4765/7232 [01:15<00:36, 67.05it/s]

Reports:  66%|██████▌   | 4773/7232 [01:15<00:39, 61.79it/s]

Reports:  66%|██████▌   | 4782/7232 [01:15<00:39, 62.25it/s]

Reports:  66%|██████▋   | 4792/7232 [01:16<00:37, 65.41it/s]

Reports:  66%|██████▋   | 4799/7232 [01:16<00:38, 63.17it/s]

Reports:  66%|██████▋   | 4807/7232 [01:16<00:36, 66.31it/s]

Reports:  67%|██████▋   | 4815/7232 [01:16<00:35, 67.24it/s]

Reports:  67%|██████▋   | 4823/7232 [01:16<00:36, 65.57it/s]

Reports:  67%|██████▋   | 4830/7232 [01:16<00:37, 63.30it/s]

Reports:  67%|██████▋   | 4840/7232 [01:16<00:43, 55.07it/s]

Reports:  67%|██████▋   | 4855/7232 [01:17<00:36, 65.56it/s]

Reports:  67%|██████▋   | 4869/7232 [01:17<00:29, 80.21it/s]

Reports:  67%|██████▋   | 4878/7232 [01:17<00:36, 65.34it/s]

Reports:  68%|██████▊   | 4886/7232 [01:17<00:47, 49.81it/s]

Reports:  68%|██████▊   | 4892/7232 [01:17<00:46, 50.65it/s]

Reports:  68%|██████▊   | 4899/7232 [01:17<00:42, 54.34it/s]

Reports:  68%|██████▊   | 4907/7232 [01:18<00:39, 58.74it/s]

Reports:  68%|██████▊   | 4916/7232 [01:18<00:36, 63.03it/s]

Reports:  68%|██████▊   | 4924/7232 [01:18<00:35, 64.52it/s]

Reports:  68%|██████▊   | 4932/7232 [01:18<00:34, 67.16it/s]

Reports:  68%|██████▊   | 4939/7232 [01:18<00:34, 65.76it/s]

Reports:  68%|██████▊   | 4946/7232 [01:18<00:34, 65.76it/s]

Reports:  68%|██████▊   | 4953/7232 [01:18<00:35, 64.82it/s]

Reports:  69%|██████▊   | 4960/7232 [01:18<00:34, 65.33it/s]

Reports:  69%|██████▊   | 4967/7232 [01:18<00:34, 65.42it/s]

Reports:  69%|██████▉   | 4975/7232 [01:19<00:33, 67.07it/s]

Reports:  69%|██████▉   | 4982/7232 [01:19<00:33, 67.39it/s]

Reports:  69%|██████▉   | 4991/7232 [01:19<00:30, 73.64it/s]

Reports:  69%|██████▉   | 4999/7232 [01:19<00:32, 69.19it/s]

Reports:  69%|██████▉   | 5010/7232 [01:19<00:28, 78.90it/s]

Reports:  69%|██████▉   | 5019/7232 [01:19<00:33, 65.28it/s]

Reports:  70%|██████▉   | 5030/7232 [01:19<00:30, 72.19it/s]

Reports:  70%|██████▉   | 5038/7232 [01:19<00:29, 73.77it/s]

Reports:  70%|██████▉   | 5046/7232 [01:20<00:32, 67.74it/s]

Reports:  70%|██████▉   | 5054/7232 [01:20<00:33, 64.91it/s]

Reports:  70%|███████   | 5063/7232 [01:20<00:36, 60.11it/s]

Reports:  70%|███████   | 5076/7232 [01:20<00:29, 72.46it/s]

Reports:  70%|███████   | 5084/7232 [01:20<00:34, 63.14it/s]

Reports:  70%|███████   | 5092/7232 [01:20<00:34, 62.23it/s]

Reports:  71%|███████   | 5103/7232 [01:20<00:30, 70.06it/s]

Reports:  71%|███████   | 5111/7232 [01:20<00:29, 71.54it/s]

Reports:  71%|███████   | 5121/7232 [01:21<00:27, 76.32it/s]

Reports:  71%|███████   | 5129/7232 [01:21<00:30, 68.75it/s]

Reports:  71%|███████   | 5138/7232 [01:21<00:32, 63.99it/s]

Reports:  71%|███████   | 5147/7232 [01:21<00:31, 66.30it/s]

Reports:  71%|███████▏  | 5155/7232 [01:21<00:29, 69.31it/s]

Reports:  71%|███████▏  | 5163/7232 [01:21<00:29, 70.45it/s]

Reports:  72%|███████▏  | 5171/7232 [01:21<00:30, 68.02it/s]

Reports:  72%|███████▏  | 5180/7232 [01:21<00:28, 72.52it/s]

Reports:  72%|███████▏  | 5188/7232 [01:22<00:34, 58.85it/s]

Reports:  72%|███████▏  | 5198/7232 [01:22<00:33, 60.16it/s]

Reports:  72%|███████▏  | 5205/7232 [01:22<00:34, 59.02it/s]

Reports:  72%|███████▏  | 5218/7232 [01:22<00:28, 69.85it/s]

Reports:  72%|███████▏  | 5226/7232 [01:22<00:28, 71.10it/s]

Reports:  72%|███████▏  | 5234/7232 [01:23<00:49, 40.66it/s]

Reports:  72%|███████▏  | 5240/7232 [01:23<00:51, 38.31it/s]

Reports:  73%|███████▎  | 5246/7232 [01:23<00:48, 40.66it/s]

Reports:  73%|███████▎  | 5251/7232 [01:23<00:48, 40.71it/s]

Reports:  73%|███████▎  | 5257/7232 [01:23<00:47, 41.98it/s]

Reports:  73%|███████▎  | 5264/7232 [01:23<00:43, 44.92it/s]

Reports:  73%|███████▎  | 5271/7232 [01:23<00:39, 49.77it/s]

Reports:  73%|███████▎  | 5281/7232 [01:24<00:32, 59.50it/s]

Reports:  73%|███████▎  | 5290/7232 [01:24<00:29, 65.76it/s]

Reports:  73%|███████▎  | 5297/7232 [01:24<00:30, 64.38it/s]

Reports:  73%|███████▎  | 5304/7232 [01:24<00:32, 59.18it/s]

Reports:  73%|███████▎  | 5314/7232 [01:24<00:30, 61.93it/s]

Reports:  74%|███████▎  | 5323/7232 [01:24<00:30, 62.20it/s]

Reports:  74%|███████▎  | 5332/7232 [01:24<00:30, 62.77it/s]

Reports:  74%|███████▍  | 5341/7232 [01:24<00:29, 63.70it/s]

Reports:  74%|███████▍  | 5348/7232 [01:25<00:33, 56.86it/s]

Reports:  74%|███████▍  | 5362/7232 [01:25<00:24, 75.52it/s]

Reports:  74%|███████▍  | 5371/7232 [01:25<00:27, 68.81it/s]

Reports:  74%|███████▍  | 5379/7232 [01:25<00:28, 64.57it/s]

Reports:  74%|███████▍  | 5386/7232 [01:25<00:28, 64.09it/s]

Reports:  75%|███████▍  | 5395/7232 [01:25<00:26, 70.29it/s]

Reports:  75%|███████▍  | 5403/7232 [01:25<00:29, 62.70it/s]

Reports:  75%|███████▍  | 5411/7232 [01:26<00:27, 66.04it/s]

Reports:  75%|███████▍  | 5418/7232 [01:26<00:28, 63.78it/s]

Reports:  75%|███████▌  | 5428/7232 [01:26<00:25, 69.64it/s]

Reports:  75%|███████▌  | 5436/7232 [01:26<00:25, 69.79it/s]

Reports:  75%|███████▌  | 5445/7232 [01:26<00:27, 65.26it/s]

Reports:  75%|███████▌  | 5455/7232 [01:26<00:24, 72.21it/s]

Reports:  76%|███████▌  | 5463/7232 [01:26<00:24, 71.28it/s]

Reports:  76%|███████▌  | 5474/7232 [01:26<00:21, 80.67it/s]

Reports:  76%|███████▌  | 5483/7232 [01:26<00:22, 78.84it/s]

Reports:  76%|███████▌  | 5492/7232 [01:27<00:22, 76.83it/s]

Reports:  76%|███████▌  | 5500/7232 [01:27<00:22, 75.79it/s]

Reports:  76%|███████▌  | 5510/7232 [01:27<00:21, 80.01it/s]

Reports:  76%|███████▋  | 5519/7232 [01:27<00:21, 79.44it/s]

Reports:  76%|███████▋  | 5527/7232 [01:27<00:21, 78.09it/s]

Reports:  77%|███████▋  | 5535/7232 [01:27<00:22, 75.75it/s]

Reports:  77%|███████▋  | 5546/7232 [01:27<00:20, 82.39it/s]

Reports:  77%|███████▋  | 5555/7232 [01:28<00:29, 56.85it/s]

Reports:  77%|███████▋  | 5562/7232 [01:28<00:42, 39.70it/s]

Reports:  77%|███████▋  | 5569/7232 [01:28<00:39, 41.73it/s]

Reports:  77%|███████▋  | 5577/7232 [01:28<00:34, 48.44it/s]

Reports:  77%|███████▋  | 5585/7232 [01:28<00:33, 49.03it/s]

Reports:  77%|███████▋  | 5593/7232 [01:28<00:30, 53.26it/s]

Reports:  77%|███████▋  | 5601/7232 [01:29<00:28, 57.83it/s]

Reports:  78%|███████▊  | 5610/7232 [01:29<00:25, 64.87it/s]

Reports:  78%|███████▊  | 5618/7232 [01:29<00:24, 66.76it/s]

Reports:  78%|███████▊  | 5627/7232 [01:29<00:22, 72.66it/s]

Reports:  78%|███████▊  | 5635/7232 [01:29<00:22, 70.63it/s]

Reports:  78%|███████▊  | 5644/7232 [01:29<00:21, 72.51it/s]

Reports:  78%|███████▊  | 5653/7232 [01:29<00:22, 69.48it/s]

Reports:  78%|███████▊  | 5664/7232 [01:29<00:22, 68.74it/s]

Reports:  78%|███████▊  | 5675/7232 [01:29<00:19, 78.56it/s]

Reports:  79%|███████▊  | 5684/7232 [01:30<00:21, 73.09it/s]

Reports:  79%|███████▊  | 5695/7232 [01:30<00:19, 79.63it/s]

Reports:  79%|███████▉  | 5704/7232 [01:30<00:20, 74.52it/s]

Reports:  79%|███████▉  | 5712/7232 [01:30<00:21, 71.57it/s]

Reports:  79%|███████▉  | 5720/7232 [01:30<00:21, 68.75it/s]

Reports:  79%|███████▉  | 5729/7232 [01:30<00:24, 61.79it/s]

Reports:  79%|███████▉  | 5736/7232 [01:30<00:24, 61.90it/s]

Reports:  79%|███████▉  | 5746/7232 [01:31<00:22, 65.63it/s]

Reports:  80%|███████▉  | 5754/7232 [01:31<00:22, 64.71it/s]

Reports:  80%|███████▉  | 5762/7232 [01:31<00:22, 64.46it/s]

Reports:  80%|███████▉  | 5776/7232 [01:31<00:17, 82.28it/s]

Reports:  80%|███████▉  | 5785/7232 [01:31<00:20, 70.33it/s]

Reports:  80%|████████  | 5793/7232 [01:31<00:19, 72.14it/s]

Reports:  80%|████████  | 5801/7232 [01:31<00:20, 68.72it/s]

Reports:  80%|████████  | 5810/7232 [01:31<00:22, 63.61it/s]

Reports:  80%|████████  | 5817/7232 [01:32<00:23, 60.93it/s]

Reports:  81%|████████  | 5826/7232 [01:32<00:22, 61.68it/s]

Reports:  81%|████████  | 5835/7232 [01:32<00:20, 68.21it/s]

Reports:  81%|████████  | 5843/7232 [01:32<00:20, 66.36it/s]

Reports:  81%|████████  | 5854/7232 [01:32<00:18, 76.02it/s]

Reports:  81%|████████  | 5862/7232 [01:32<00:20, 67.80it/s]

Reports:  81%|████████  | 5874/7232 [01:32<00:18, 72.45it/s]

Reports:  81%|████████▏ | 5882/7232 [01:33<00:20, 65.58it/s]

Reports:  81%|████████▏ | 5891/7232 [01:33<00:19, 67.50it/s]

Reports:  82%|████████▏ | 5900/7232 [01:33<00:19, 69.70it/s]

Reports:  82%|████████▏ | 5908/7232 [01:33<00:29, 44.54it/s]

Reports:  82%|████████▏ | 5916/7232 [01:33<00:30, 42.89it/s]

Reports:  82%|████████▏ | 5923/7232 [01:33<00:28, 46.61it/s]

Reports:  82%|████████▏ | 5929/7232 [01:34<00:26, 48.65it/s]

Reports:  82%|████████▏ | 5937/7232 [01:34<00:23, 55.33it/s]

Reports:  82%|████████▏ | 5944/7232 [01:34<00:24, 53.41it/s]

Reports:  82%|████████▏ | 5950/7232 [01:34<00:23, 53.65it/s]

Reports:  82%|████████▏ | 5956/7232 [01:34<00:25, 50.30it/s]

Reports:  82%|████████▏ | 5964/7232 [01:34<00:23, 54.03it/s]

Reports:  83%|████████▎ | 5971/7232 [01:34<00:22, 56.42it/s]

Reports:  83%|████████▎ | 5980/7232 [01:34<00:20, 61.55it/s]

Reports:  83%|████████▎ | 5988/7232 [01:35<00:20, 62.04it/s]

Reports:  83%|████████▎ | 5997/7232 [01:35<00:20, 61.34it/s]

Reports:  83%|████████▎ | 6005/7232 [01:35<00:19, 63.19it/s]

Reports:  83%|████████▎ | 6014/7232 [01:35<00:17, 68.04it/s]

Reports:  83%|████████▎ | 6022/7232 [01:35<00:17, 70.06it/s]

Reports:  83%|████████▎ | 6030/7232 [01:35<00:16, 71.73it/s]

Reports:  83%|████████▎ | 6038/7232 [01:35<00:18, 65.82it/s]

Reports:  84%|████████▎ | 6045/7232 [01:35<00:17, 66.81it/s]

Reports:  84%|████████▎ | 6054/7232 [01:36<00:17, 65.84it/s]

Reports:  84%|████████▍ | 6066/7232 [01:36<00:17, 68.04it/s]

Reports:  84%|████████▍ | 6076/7232 [01:36<00:15, 73.32it/s]

Reports:  84%|████████▍ | 6084/7232 [01:36<00:16, 69.24it/s]

Reports:  84%|████████▍ | 6093/7232 [01:36<00:15, 72.42it/s]

Reports:  84%|████████▍ | 6101/7232 [01:36<00:15, 73.60it/s]

Reports:  84%|████████▍ | 6109/7232 [01:36<00:16, 69.87it/s]

Reports:  85%|████████▍ | 6117/7232 [01:36<00:16, 67.35it/s]

Reports:  85%|████████▍ | 6128/7232 [01:37<00:14, 77.26it/s]

Reports:  85%|████████▍ | 6136/7232 [01:37<00:16, 65.99it/s]

Reports:  85%|████████▍ | 6146/7232 [01:37<00:16, 66.08it/s]

Reports:  85%|████████▌ | 6157/7232 [01:37<00:14, 75.79it/s]

Reports:  85%|████████▌ | 6165/7232 [01:37<00:15, 70.04it/s]

Reports:  85%|████████▌ | 6174/7232 [01:37<00:15, 67.46it/s]

Reports:  85%|████████▌ | 6181/7232 [01:37<00:15, 66.70it/s]

Reports:  86%|████████▌ | 6190/7232 [01:37<00:14, 70.34it/s]

Reports:  86%|████████▌ | 6198/7232 [01:38<00:16, 63.69it/s]

Reports:  86%|████████▌ | 6211/7232 [01:38<00:13, 74.62it/s]

Reports:  86%|████████▌ | 6219/7232 [01:38<00:15, 65.44it/s]

Reports:  86%|████████▌ | 6230/7232 [01:38<00:14, 71.03it/s]

Reports:  86%|████████▋ | 6240/7232 [01:38<00:12, 77.71it/s]

Reports:  86%|████████▋ | 6249/7232 [01:39<00:22, 44.22it/s]

Reports:  87%|████████▋ | 6261/7232 [01:39<00:17, 54.11it/s]

Reports:  87%|████████▋ | 6270/7232 [01:39<00:16, 58.28it/s]

Reports:  87%|████████▋ | 6279/7232 [01:39<00:15, 63.14it/s]

Reports:  87%|████████▋ | 6289/7232 [01:39<00:13, 69.98it/s]

Reports:  87%|████████▋ | 6298/7232 [01:39<00:13, 69.76it/s]

Reports:  87%|████████▋ | 6306/7232 [01:39<00:14, 66.13it/s]

Reports:  87%|████████▋ | 6315/7232 [01:39<00:14, 64.09it/s]

Reports:  87%|████████▋ | 6322/7232 [01:40<00:14, 63.02it/s]

Reports:  88%|████████▊ | 6329/7232 [01:40<00:14, 63.72it/s]

Reports:  88%|████████▊ | 6336/7232 [01:40<00:14, 61.86it/s]

Reports:  88%|████████▊ | 6344/7232 [01:40<00:13, 63.56it/s]

Reports:  88%|████████▊ | 6353/7232 [01:40<00:12, 68.33it/s]

Reports:  88%|████████▊ | 6360/7232 [01:40<00:14, 58.20it/s]

Reports:  88%|████████▊ | 6367/7232 [01:40<00:14, 58.06it/s]

Reports:  88%|████████▊ | 6376/7232 [01:40<00:13, 61.70it/s]

Reports:  88%|████████▊ | 6388/7232 [01:41<00:11, 74.42it/s]

Reports:  88%|████████▊ | 6396/7232 [01:41<00:11, 69.76it/s]

Reports:  89%|████████▊ | 6407/7232 [01:41<00:11, 71.93it/s]

Reports:  89%|████████▊ | 6417/7232 [01:41<00:10, 76.54it/s]

Reports:  89%|████████▉ | 6425/7232 [01:41<00:10, 74.03it/s]

Reports:  89%|████████▉ | 6436/7232 [01:41<00:09, 82.85it/s]

Reports:  89%|████████▉ | 6445/7232 [01:41<00:11, 66.59it/s]

Reports:  89%|████████▉ | 6454/7232 [01:41<00:10, 71.76it/s]

Reports:  89%|████████▉ | 6462/7232 [01:42<00:11, 69.42it/s]

Reports:  89%|████████▉ | 6470/7232 [01:42<00:10, 70.86it/s]

Reports:  90%|████████▉ | 6478/7232 [01:42<00:11, 64.64it/s]

Reports:  90%|████████▉ | 6487/7232 [01:42<00:11, 65.90it/s]

Reports:  90%|████████▉ | 6497/7232 [01:42<00:10, 71.94it/s]

Reports:  90%|████████▉ | 6505/7232 [01:42<00:10, 71.08it/s]

Reports:  90%|█████████ | 6513/7232 [01:42<00:09, 72.39it/s]

Reports:  90%|█████████ | 6521/7232 [01:42<00:10, 69.10it/s]

Reports:  90%|█████████ | 6529/7232 [01:43<00:11, 63.90it/s]

Reports:  90%|█████████ | 6541/7232 [01:43<00:09, 71.37it/s]

Reports:  91%|█████████ | 6550/7232 [01:43<00:09, 75.01it/s]

Reports:  91%|█████████ | 6558/7232 [01:43<00:09, 71.44it/s]

Reports:  91%|█████████ | 6567/7232 [01:43<00:09, 72.54it/s]

Reports:  91%|█████████ | 6575/7232 [01:43<00:09, 72.57it/s]

Reports:  91%|█████████ | 6584/7232 [01:43<00:08, 74.13it/s]

Reports:  91%|█████████ | 6592/7232 [01:43<00:08, 72.50it/s]

Reports:  91%|█████████▏| 6600/7232 [01:44<00:17, 36.65it/s]

Reports:  91%|█████████▏| 6608/7232 [01:44<00:14, 43.15it/s]

Reports:  91%|█████████▏| 6615/7232 [01:44<00:12, 47.78it/s]

Reports:  92%|█████████▏| 6622/7232 [01:44<00:12, 48.50it/s]

Reports:  92%|█████████▏| 6628/7232 [01:44<00:12, 50.09it/s]

Reports:  92%|█████████▏| 6639/7232 [01:44<00:09, 60.18it/s]

Reports:  92%|█████████▏| 6646/7232 [01:45<00:11, 49.35it/s]

Reports:  92%|█████████▏| 6657/7232 [01:45<00:10, 52.52it/s]

Reports:  92%|█████████▏| 6672/7232 [01:45<00:08, 67.95it/s]

Reports:  92%|█████████▏| 6680/7232 [01:45<00:08, 63.72it/s]

Reports:  92%|█████████▏| 6689/7232 [01:45<00:08, 64.45it/s]

Reports:  93%|█████████▎| 6696/7232 [01:45<00:08, 65.50it/s]

Reports:  93%|█████████▎| 6704/7232 [01:46<00:08, 62.56it/s]

Reports:  93%|█████████▎| 6714/7232 [01:46<00:07, 69.21it/s]

Reports:  93%|█████████▎| 6722/7232 [01:46<00:08, 60.30it/s]

Reports:  93%|█████████▎| 6736/7232 [01:46<00:06, 71.01it/s]

Reports:  93%|█████████▎| 6744/7232 [01:46<00:07, 68.23it/s]

Reports:  93%|█████████▎| 6754/7232 [01:46<00:06, 68.87it/s]

Reports:  93%|█████████▎| 6761/7232 [01:46<00:06, 68.76it/s]

Reports:  94%|█████████▎| 6770/7232 [01:47<00:06, 66.63it/s]

Reports:  94%|█████████▎| 6778/7232 [01:47<00:06, 69.79it/s]

Reports:  94%|█████████▍| 6787/7232 [01:47<00:06, 68.22it/s]

Reports:  94%|█████████▍| 6797/7232 [01:47<00:06, 67.16it/s]

Reports:  94%|█████████▍| 6807/7232 [01:47<00:05, 70.96it/s]

Reports:  94%|█████████▍| 6815/7232 [01:47<00:06, 68.34it/s]

Reports:  94%|█████████▍| 6823/7232 [01:47<00:06, 66.87it/s]

Reports:  94%|█████████▍| 6833/7232 [01:47<00:05, 73.58it/s]

Reports:  95%|█████████▍| 6841/7232 [01:48<00:05, 69.65it/s]

Reports:  95%|█████████▍| 6854/7232 [01:48<00:04, 76.76it/s]

Reports:  95%|█████████▍| 6865/7232 [01:48<00:04, 73.71it/s]

Reports:  95%|█████████▌| 6873/7232 [01:48<00:05, 65.49it/s]

Reports:  95%|█████████▌| 6885/7232 [01:48<00:04, 77.27it/s]

Reports:  95%|█████████▌| 6894/7232 [01:48<00:04, 68.15it/s]

Reports:  95%|█████████▌| 6902/7232 [01:48<00:04, 68.79it/s]

Reports:  96%|█████████▌| 6910/7232 [01:48<00:04, 69.56it/s]

Reports:  96%|█████████▌| 6918/7232 [01:49<00:04, 68.86it/s]

Reports:  96%|█████████▌| 6926/7232 [01:49<00:07, 39.92it/s]

Reports:  96%|█████████▌| 6932/7232 [01:49<00:07, 39.08it/s]

Reports:  96%|█████████▌| 6944/7232 [01:49<00:05, 52.12it/s]

Reports:  96%|█████████▌| 6951/7232 [01:49<00:05, 48.92it/s]

Reports:  96%|█████████▌| 6959/7232 [01:50<00:04, 55.02it/s]

Reports:  96%|█████████▋| 6966/7232 [01:50<00:05, 52.18it/s]

Reports:  96%|█████████▋| 6975/7232 [01:50<00:04, 59.76it/s]

Reports:  97%|█████████▋| 6982/7232 [01:50<00:04, 60.05it/s]

Reports:  97%|█████████▋| 6992/7232 [01:50<00:03, 68.52it/s]

Reports:  97%|█████████▋| 7000/7232 [01:50<00:03, 62.84it/s]

Reports:  97%|█████████▋| 7007/7232 [01:50<00:03, 63.73it/s]

Reports:  97%|█████████▋| 7014/7232 [01:50<00:03, 61.37it/s]

Reports:  97%|█████████▋| 7024/7232 [01:51<00:02, 71.22it/s]

Reports:  97%|█████████▋| 7032/7232 [01:51<00:02, 72.04it/s]

Reports:  97%|█████████▋| 7042/7232 [01:51<00:02, 78.56it/s]

Reports:  97%|█████████▋| 7051/7232 [01:51<00:02, 72.17it/s]

Reports:  98%|█████████▊| 7059/7232 [01:51<00:02, 73.54it/s]

Reports:  98%|█████████▊| 7067/7232 [01:51<00:02, 70.31it/s]

Reports:  98%|█████████▊| 7076/7232 [01:51<00:02, 70.97it/s]

Reports:  98%|█████████▊| 7086/7232 [01:51<00:01, 76.49it/s]

Reports:  98%|█████████▊| 7094/7232 [01:51<00:01, 73.57it/s]

Reports:  98%|█████████▊| 7107/7232 [01:52<00:01, 87.06it/s]

Reports:  98%|█████████▊| 7116/7232 [01:52<00:01, 70.51it/s]

Reports:  99%|█████████▊| 7125/7232 [01:52<00:01, 74.59it/s]

Reports:  99%|█████████▊| 7133/7232 [01:52<00:01, 70.76it/s]

Reports:  99%|█████████▉| 7144/7232 [01:52<00:01, 71.10it/s]

Reports:  99%|█████████▉| 7156/7232 [01:52<00:01, 75.75it/s]

Reports:  99%|█████████▉| 7164/7232 [01:52<00:00, 68.66it/s]

Reports:  99%|█████████▉| 7176/7232 [01:53<00:00, 71.94it/s]

Reports:  99%|█████████▉| 7184/7232 [01:53<00:00, 71.78it/s]

Reports:  99%|█████████▉| 7193/7232 [01:53<00:00, 70.67it/s]

Reports: 100%|█████████▉| 7204/7232 [01:53<00:00, 77.38it/s]

Reports: 100%|█████████▉| 7212/7232 [01:53<00:00, 72.30it/s]

Reports: 100%|█████████▉| 7223/7232 [01:53<00:00, 80.00it/s]

Reports: 100%|██████████| 7232/7232 [01:53<00:00, 75.35it/s]

Reports: 100%|██████████| 7232/7232 [01:53<00:00, 63.53it/s]

Report rows: 4012

Gaps (ex-reports):   0%|          | 0/7232 [00:00<?, ?it/s]

Gaps (ex-reports):   0%|          | 1/7232 [00:00<18:13,  6.61it/s]

Gaps (ex-reports):   0%|          | 4/7232 [00:00<13:05,  9.20it/s]

Gaps (ex-reports):   0%|          | 8/7232 [00:00<07:19, 16.44it/s]

Gaps (ex-reports):   0%|          | 20/7232 [00:00<03:02, 39.53it/s]

Gaps (ex-reports):   0%|          | 25/7232 [00:00<02:55, 41.12it/s]

Gaps (ex-reports):   0%|          | 30/7232 [00:00<02:51, 42.04it/s]

Gaps (ex-reports):   1%|          | 40/7232 [00:01<02:08, 55.76it/s]

Gaps (ex-reports):   1%|          | 46/7232 [00:01<02:12, 54.13it/s]

Gaps (ex-reports):   1%|          | 57/7232 [00:01<01:46, 67.35it/s]

Gaps (ex-reports):   1%|          | 65/7232 [00:01<02:10, 55.12it/s]

Gaps (ex-reports):   1%|          | 76/7232 [00:01<01:53, 63.04it/s]

Gaps (ex-reports):   1%|          | 83/7232 [00:01<01:59, 59.77it/s]

Gaps (ex-reports):   1%|▏         | 92/7232 [00:01<01:51, 63.75it/s]

Gaps (ex-reports):   1%|▏         | 99/7232 [00:01<01:53, 62.60it/s]

Gaps (ex-reports):   2%|▏         | 109/7232 [00:02<01:45, 67.44it/s]

Gaps (ex-reports):   2%|▏         | 116/7232 [00:02<01:46, 66.63it/s]

Gaps (ex-reports):   2%|▏         | 126/7232 [00:02<01:47, 66.30it/s]

Gaps (ex-reports):   2%|▏         | 133/7232 [00:02<02:02, 58.03it/s]

Gaps (ex-reports):   2%|▏         | 144/7232 [00:02<01:57, 60.49it/s]

Gaps (ex-reports):   2%|▏         | 160/7232 [00:02<01:43, 68.12it/s]

Gaps (ex-reports):   2%|▏         | 170/7232 [00:03<01:35, 74.12it/s]

Gaps (ex-reports):   2%|▏         | 178/7232 [00:03<01:37, 72.45it/s]

Gaps (ex-reports):   3%|▎         | 186/7232 [00:03<01:35, 73.87it/s]

Gaps (ex-reports):   3%|▎         | 194/7232 [00:03<01:40, 70.16it/s]

Gaps (ex-reports):   3%|▎         | 202/7232 [00:03<01:36, 72.53it/s]

Gaps (ex-reports):   3%|▎         | 210/7232 [00:03<01:57, 59.85it/s]

Gaps (ex-reports):   3%|▎         | 217/7232 [00:03<01:53, 61.63it/s]

Gaps (ex-reports):   3%|▎         | 226/7232 [00:03<02:00, 58.20it/s]

Gaps (ex-reports):   3%|▎         | 241/7232 [00:04<01:29, 77.87it/s]

Gaps (ex-reports):   3%|▎         | 250/7232 [00:04<01:53, 61.76it/s]

Gaps (ex-reports):   4%|▎         | 259/7232 [00:04<01:44, 66.49it/s]

Gaps (ex-reports):   4%|▎         | 267/7232 [00:04<01:47, 64.54it/s]

Gaps (ex-reports):   4%|▍         | 275/7232 [00:04<01:50, 62.83it/s]

Gaps (ex-reports):   4%|▍         | 282/7232 [00:04<01:49, 63.46it/s]

Gaps (ex-reports):   4%|▍         | 289/7232 [00:04<01:52, 61.62it/s]

Gaps (ex-reports):   4%|▍         | 300/7232 [00:04<01:35, 72.81it/s]

Gaps (ex-reports):   4%|▍         | 308/7232 [00:05<01:46, 65.10it/s]

Gaps (ex-reports):   4%|▍         | 317/7232 [00:05<01:38, 70.39it/s]

Gaps (ex-reports):   4%|▍         | 325/7232 [00:05<01:50, 62.67it/s]

Gaps (ex-reports):   5%|▍         | 334/7232 [00:05<02:20, 49.13it/s]

Gaps (ex-reports):   5%|▍         | 340/7232 [00:05<02:18, 49.59it/s]

Gaps (ex-reports):   5%|▍         | 346/7232 [00:05<02:40, 42.88it/s]

Gaps (ex-reports):   5%|▍         | 355/7232 [00:06<02:22, 48.09it/s]

Gaps (ex-reports):   5%|▍         | 361/7232 [00:06<02:28, 46.26it/s]

Gaps (ex-reports):   5%|▌         | 367/7232 [00:06<02:22, 48.24it/s]

Gaps (ex-reports):   5%|▌         | 375/7232 [00:06<02:06, 54.40it/s]

Gaps (ex-reports):   5%|▌         | 383/7232 [00:06<01:55, 59.19it/s]

Gaps (ex-reports):   5%|▌         | 390/7232 [00:06<02:00, 56.74it/s]

Gaps (ex-reports):   6%|▌         | 398/7232 [00:06<01:55, 59.09it/s]

Gaps (ex-reports):   6%|▌         | 406/7232 [00:06<01:50, 61.87it/s]

Gaps (ex-reports):   6%|▌         | 413/7232 [00:07<01:57, 57.88it/s]

Gaps (ex-reports):   6%|▌         | 419/7232 [00:07<02:14, 50.47it/s]

Gaps (ex-reports):   6%|▌         | 426/7232 [00:07<02:07, 53.29it/s]

Gaps (ex-reports):   6%|▌         | 434/7232 [00:07<02:15, 50.32it/s]

Gaps (ex-reports):   6%|▌         | 448/7232 [00:07<01:36, 70.11it/s]

Gaps (ex-reports):   6%|▋         | 456/7232 [00:07<01:53, 59.80it/s]

Gaps (ex-reports):   6%|▋         | 466/7232 [00:07<01:45, 63.88it/s]

Gaps (ex-reports):   7%|▋         | 473/7232 [00:08<01:48, 62.49it/s]

Gaps (ex-reports):   7%|▋         | 483/7232 [00:08<01:37, 69.57it/s]

Gaps (ex-reports):   7%|▋         | 492/7232 [00:08<01:35, 70.92it/s]

Gaps (ex-reports):   7%|▋         | 500/7232 [00:08<01:38, 68.03it/s]

Gaps (ex-reports):   7%|▋         | 508/7232 [00:08<01:41, 66.33it/s]

Gaps (ex-reports):   7%|▋         | 517/7232 [00:08<01:40, 67.01it/s]

Gaps (ex-reports):   7%|▋         | 527/7232 [00:08<01:39, 67.55it/s]

Gaps (ex-reports):   7%|▋         | 534/7232 [00:09<01:50, 60.58it/s]

Gaps (ex-reports):   8%|▊         | 545/7232 [00:09<01:34, 70.87it/s]

Gaps (ex-reports):   8%|▊         | 553/7232 [00:09<01:47, 62.26it/s]

Gaps (ex-reports):   8%|▊         | 564/7232 [00:09<01:32, 72.30it/s]

Gaps (ex-reports):   8%|▊         | 572/7232 [00:09<01:45, 63.04it/s]

Gaps (ex-reports):   8%|▊         | 582/7232 [00:09<01:39, 66.63it/s]

Gaps (ex-reports):   8%|▊         | 590/7232 [00:09<01:39, 66.90it/s]

Gaps (ex-reports):   8%|▊         | 599/7232 [00:09<01:44, 63.32it/s]

Gaps (ex-reports):   8%|▊         | 606/7232 [00:10<01:48, 61.33it/s]

Gaps (ex-reports):   9%|▊         | 615/7232 [00:10<01:39, 66.66it/s]

Gaps (ex-reports):   9%|▊         | 623/7232 [00:10<01:35, 69.00it/s]

Gaps (ex-reports):   9%|▊         | 631/7232 [00:10<01:38, 67.04it/s]

Gaps (ex-reports):   9%|▉         | 640/7232 [00:10<01:31, 71.90it/s]

Gaps (ex-reports):   9%|▉         | 648/7232 [00:10<01:47, 61.13it/s]

Gaps (ex-reports):   9%|▉         | 656/7232 [00:11<02:55, 37.54it/s]

Gaps (ex-reports):   9%|▉         | 662/7232 [00:11<02:40, 40.95it/s]

Gaps (ex-reports):   9%|▉         | 670/7232 [00:11<02:26, 44.85it/s]

Gaps (ex-reports):   9%|▉         | 676/7232 [00:11<02:24, 45.32it/s]

Gaps (ex-reports):   9%|▉         | 683/7232 [00:11<02:10, 50.31it/s]

Gaps (ex-reports):  10%|▉         | 691/7232 [00:11<02:06, 51.51it/s]

Gaps (ex-reports):  10%|▉         | 699/7232 [00:11<02:06, 51.72it/s]

Gaps (ex-reports):  10%|▉         | 708/7232 [00:12<01:49, 59.37it/s]

Gaps (ex-reports):  10%|▉         | 715/7232 [00:12<01:49, 59.26it/s]

Gaps (ex-reports):  10%|█         | 727/7232 [00:12<01:32, 70.42it/s]

Gaps (ex-reports):  10%|█         | 735/7232 [00:12<01:34, 68.60it/s]

Gaps (ex-reports):  10%|█         | 744/7232 [00:12<01:36, 67.38it/s]

Gaps (ex-reports):  10%|█         | 752/7232 [00:12<01:39, 65.31it/s]

Gaps (ex-reports):  11%|█         | 761/7232 [00:12<01:36, 66.95it/s]

Gaps (ex-reports):  11%|█         | 770/7232 [00:12<01:30, 71.02it/s]

Gaps (ex-reports):  11%|█         | 778/7232 [00:13<01:44, 61.82it/s]

Gaps (ex-reports):  11%|█         | 791/7232 [00:13<01:35, 67.58it/s]

Gaps (ex-reports):  11%|█         | 798/7232 [00:13<01:39, 64.35it/s]

Gaps (ex-reports):  11%|█         | 807/7232 [00:13<01:34, 68.34it/s]

Gaps (ex-reports):  11%|█▏        | 814/7232 [00:13<01:45, 61.06it/s]

Gaps (ex-reports):  11%|█▏        | 827/7232 [00:13<01:34, 67.87it/s]

Gaps (ex-reports):  12%|█▏        | 834/7232 [00:13<01:36, 66.33it/s]

Gaps (ex-reports):  12%|█▏        | 844/7232 [00:14<01:37, 65.21it/s]

Gaps (ex-reports):  12%|█▏        | 851/7232 [00:14<01:39, 63.83it/s]

Gaps (ex-reports):  12%|█▏        | 861/7232 [00:14<01:34, 67.56it/s]

Gaps (ex-reports):  12%|█▏        | 868/7232 [00:14<01:36, 66.08it/s]

Gaps (ex-reports):  12%|█▏        | 878/7232 [00:14<01:26, 73.62it/s]

Gaps (ex-reports):  12%|█▏        | 886/7232 [00:14<01:43, 61.57it/s]

Gaps (ex-reports):  12%|█▏        | 895/7232 [00:14<01:39, 63.75it/s]

Gaps (ex-reports):  13%|█▎        | 906/7232 [00:14<01:25, 74.10it/s]

Gaps (ex-reports):  13%|█▎        | 914/7232 [00:15<01:36, 65.29it/s]

Gaps (ex-reports):  13%|█▎        | 923/7232 [00:15<01:34, 67.11it/s]

Gaps (ex-reports):  13%|█▎        | 931/7232 [00:15<01:47, 58.68it/s]

Gaps (ex-reports):  13%|█▎        | 944/7232 [00:15<01:28, 70.85it/s]

Gaps (ex-reports):  13%|█▎        | 952/7232 [00:15<01:40, 62.45it/s]

Gaps (ex-reports):  13%|█▎        | 962/7232 [00:15<01:41, 61.52it/s]

Gaps (ex-reports):  13%|█▎        | 969/7232 [00:16<01:45, 59.39it/s]

Gaps (ex-reports):  14%|█▎        | 978/7232 [00:16<02:17, 45.34it/s]

Gaps (ex-reports):  14%|█▎        | 984/7232 [00:16<02:11, 47.36it/s]

Gaps (ex-reports):  14%|█▎        | 990/7232 [00:16<02:20, 44.41it/s]

Gaps (ex-reports):  14%|█▍        | 995/7232 [00:16<02:30, 41.48it/s]

Gaps (ex-reports):  14%|█▍        | 1007/7232 [00:16<01:49, 56.98it/s]

Gaps (ex-reports):  14%|█▍        | 1014/7232 [00:17<01:55, 53.94it/s]

Gaps (ex-reports):  14%|█▍        | 1025/7232 [00:17<01:36, 64.56it/s]

Gaps (ex-reports):  14%|█▍        | 1033/7232 [00:17<02:04, 49.76it/s]

Gaps (ex-reports):  14%|█▍        | 1047/7232 [00:17<01:40, 61.84it/s]

Gaps (ex-reports):  15%|█▍        | 1057/7232 [00:17<01:40, 61.28it/s]

Gaps (ex-reports):  15%|█▍        | 1064/7232 [00:17<01:52, 54.81it/s]

Gaps (ex-reports):  15%|█▍        | 1078/7232 [00:17<01:26, 71.24it/s]

Gaps (ex-reports):  15%|█▌        | 1087/7232 [00:18<01:38, 62.18it/s]

Gaps (ex-reports):  15%|█▌        | 1096/7232 [00:18<01:38, 62.50it/s]

Gaps (ex-reports):  15%|█▌        | 1106/7232 [00:18<01:35, 63.99it/s]

Gaps (ex-reports):  15%|█▌        | 1114/7232 [00:18<01:30, 67.47it/s]

Gaps (ex-reports):  16%|█▌        | 1122/7232 [00:18<01:30, 67.57it/s]

Gaps (ex-reports):  16%|█▌        | 1130/7232 [00:18<01:31, 66.57it/s]

Gaps (ex-reports):  16%|█▌        | 1137/7232 [00:18<01:40, 60.69it/s]

Gaps (ex-reports):  16%|█▌        | 1147/7232 [00:19<01:31, 66.50it/s]

Gaps (ex-reports):  16%|█▌        | 1158/7232 [00:19<01:19, 76.11it/s]

Gaps (ex-reports):  16%|█▌        | 1166/7232 [00:19<01:21, 74.13it/s]

Gaps (ex-reports):  16%|█▌        | 1174/7232 [00:19<01:22, 73.53it/s]

Gaps (ex-reports):  16%|█▋        | 1182/7232 [00:19<01:24, 71.19it/s]

Gaps (ex-reports):  16%|█▋        | 1190/7232 [00:19<01:37, 61.87it/s]

Gaps (ex-reports):  17%|█▋        | 1197/7232 [00:19<01:35, 63.24it/s]

Gaps (ex-reports):  17%|█▋        | 1207/7232 [00:19<01:29, 67.39it/s]

Gaps (ex-reports):  17%|█▋        | 1216/7232 [00:20<01:31, 65.64it/s]

Gaps (ex-reports):  17%|█▋        | 1228/7232 [00:20<01:23, 72.20it/s]

Gaps (ex-reports):  17%|█▋        | 1236/7232 [00:20<01:38, 60.68it/s]

Gaps (ex-reports):  17%|█▋        | 1249/7232 [00:20<01:25, 69.69it/s]

Gaps (ex-reports):  17%|█▋        | 1257/7232 [00:20<01:28, 67.29it/s]

Gaps (ex-reports):  18%|█▊        | 1267/7232 [00:20<01:25, 69.69it/s]

Gaps (ex-reports):  18%|█▊        | 1275/7232 [00:20<01:26, 68.85it/s]

Gaps (ex-reports):  18%|█▊        | 1284/7232 [00:21<01:31, 65.23it/s]

Gaps (ex-reports):  18%|█▊        | 1293/7232 [00:21<01:23, 70.73it/s]

Gaps (ex-reports):  18%|█▊        | 1301/7232 [00:21<01:26, 68.57it/s]

Gaps (ex-reports):  18%|█▊        | 1310/7232 [00:21<01:25, 69.59it/s]

Gaps (ex-reports):  18%|█▊        | 1318/7232 [00:21<02:25, 40.63it/s]

Gaps (ex-reports):  18%|█▊        | 1327/7232 [00:22<02:22, 41.39it/s]

Gaps (ex-reports):  18%|█▊        | 1335/7232 [00:22<02:21, 41.69it/s]

Gaps (ex-reports):  19%|█▊        | 1340/7232 [00:22<02:34, 38.13it/s]

Gaps (ex-reports):  19%|█▊        | 1351/7232 [00:22<01:56, 50.54it/s]

Gaps (ex-reports):  19%|█▉        | 1358/7232 [00:22<02:11, 44.55it/s]

Gaps (ex-reports):  19%|█▉        | 1369/7232 [00:22<01:43, 56.46it/s]

Gaps (ex-reports):  19%|█▉        | 1377/7232 [00:22<01:39, 59.08it/s]

Gaps (ex-reports):  19%|█▉        | 1385/7232 [00:23<01:31, 63.70it/s]

Gaps (ex-reports):  19%|█▉        | 1393/7232 [00:23<01:31, 63.86it/s]

Gaps (ex-reports):  19%|█▉        | 1400/7232 [00:23<01:38, 59.05it/s]

Gaps (ex-reports):  19%|█▉        | 1407/7232 [00:23<01:50, 52.75it/s]

Gaps (ex-reports):  20%|█▉        | 1416/7232 [00:23<01:41, 57.36it/s]

Gaps (ex-reports):  20%|█▉        | 1423/7232 [00:23<01:48, 53.35it/s]

Gaps (ex-reports):  20%|█▉        | 1430/7232 [00:23<01:46, 54.23it/s]

Gaps (ex-reports):  20%|█▉        | 1439/7232 [00:24<01:35, 60.96it/s]

Gaps (ex-reports):  20%|█▉        | 1446/7232 [00:24<01:34, 61.47it/s]

Gaps (ex-reports):  20%|██        | 1454/7232 [00:24<01:31, 63.42it/s]

Gaps (ex-reports):  20%|██        | 1461/7232 [00:24<01:36, 59.66it/s]

Gaps (ex-reports):  20%|██        | 1468/7232 [00:24<01:33, 61.50it/s]

Gaps (ex-reports):  20%|██        | 1475/7232 [00:24<01:53, 50.54it/s]

Gaps (ex-reports):  21%|██        | 1484/7232 [00:24<01:36, 59.36it/s]

Gaps (ex-reports):  21%|██        | 1491/7232 [00:24<01:51, 51.57it/s]

Gaps (ex-reports):  21%|██        | 1504/7232 [00:25<01:36, 59.39it/s]

Gaps (ex-reports):  21%|██        | 1512/7232 [00:25<01:36, 59.17it/s]

Gaps (ex-reports):  21%|██        | 1520/7232 [00:25<01:46, 53.81it/s]

Gaps (ex-reports):  21%|██        | 1528/7232 [00:25<01:36, 59.36it/s]

Gaps (ex-reports):  21%|██        | 1536/7232 [00:25<01:42, 55.59it/s]

Gaps (ex-reports):  21%|██▏       | 1542/7232 [00:25<01:49, 52.07it/s]

Gaps (ex-reports):  21%|██▏       | 1553/7232 [00:25<01:32, 61.61it/s]

Gaps (ex-reports):  22%|██▏       | 1560/7232 [00:26<01:41, 55.88it/s]

Gaps (ex-reports):  22%|██▏       | 1572/7232 [00:26<01:33, 60.83it/s]

Gaps (ex-reports):  22%|██▏       | 1580/7232 [00:26<01:29, 63.41it/s]

Gaps (ex-reports):  22%|██▏       | 1589/7232 [00:26<01:40, 55.95it/s]

Gaps (ex-reports):  22%|██▏       | 1604/7232 [00:26<01:15, 74.95it/s]

Gaps (ex-reports):  22%|██▏       | 1613/7232 [00:27<02:47, 33.62it/s]

Gaps (ex-reports):  22%|██▏       | 1620/7232 [00:27<02:36, 35.77it/s]

Gaps (ex-reports):  22%|██▏       | 1626/7232 [00:27<02:50, 32.89it/s]

Gaps (ex-reports):  23%|██▎       | 1632/7232 [00:27<02:51, 32.72it/s]

Gaps (ex-reports):  23%|██▎       | 1647/7232 [00:28<01:49, 50.79it/s]

Gaps (ex-reports):  23%|██▎       | 1655/7232 [00:28<02:04, 44.71it/s]

Gaps (ex-reports):  23%|██▎       | 1665/7232 [00:28<01:48, 51.48it/s]

Gaps (ex-reports):  23%|██▎       | 1672/7232 [00:28<01:54, 48.50it/s]

Gaps (ex-reports):  23%|██▎       | 1682/7232 [00:28<01:47, 51.46it/s]

Gaps (ex-reports):  23%|██▎       | 1692/7232 [00:28<01:32, 60.07it/s]

Gaps (ex-reports):  23%|██▎       | 1699/7232 [00:29<01:37, 56.86it/s]

Gaps (ex-reports):  24%|██▎       | 1706/7232 [00:29<01:33, 58.98it/s]

Gaps (ex-reports):  24%|██▎       | 1715/7232 [00:29<01:39, 55.33it/s]

Gaps (ex-reports):  24%|██▍       | 1728/7232 [00:29<01:17, 70.88it/s]

Gaps (ex-reports):  24%|██▍       | 1736/7232 [00:29<01:24, 65.02it/s]

Gaps (ex-reports):  24%|██▍       | 1744/7232 [00:29<01:23, 65.65it/s]

Gaps (ex-reports):  24%|██▍       | 1751/7232 [00:29<01:35, 57.17it/s]

Gaps (ex-reports):  24%|██▍       | 1758/7232 [00:30<01:37, 56.16it/s]

Gaps (ex-reports):  24%|██▍       | 1767/7232 [00:30<01:26, 62.82it/s]

Gaps (ex-reports):  25%|██▍       | 1774/7232 [00:30<01:27, 62.22it/s]

Gaps (ex-reports):  25%|██▍       | 1782/7232 [00:30<01:24, 64.17it/s]

Gaps (ex-reports):  25%|██▍       | 1789/7232 [00:30<01:23, 65.40it/s]

Gaps (ex-reports):  25%|██▍       | 1797/7232 [00:30<01:21, 66.52it/s]

Gaps (ex-reports):  25%|██▍       | 1804/7232 [00:30<01:28, 61.33it/s]

Gaps (ex-reports):  25%|██▌       | 1815/7232 [00:30<01:18, 68.73it/s]

Gaps (ex-reports):  25%|██▌       | 1822/7232 [00:30<01:23, 64.58it/s]

Gaps (ex-reports):  25%|██▌       | 1831/7232 [00:31<01:20, 67.46it/s]

Gaps (ex-reports):  25%|██▌       | 1838/7232 [00:31<01:21, 66.47it/s]

Gaps (ex-reports):  26%|██▌       | 1845/7232 [00:31<01:31, 59.15it/s]

Gaps (ex-reports):  26%|██▌       | 1852/7232 [00:31<01:30, 59.23it/s]

Gaps (ex-reports):  26%|██▌       | 1859/7232 [00:31<01:41, 52.79it/s]

Gaps (ex-reports):  26%|██▌       | 1872/7232 [00:31<01:15, 70.97it/s]

Gaps (ex-reports):  26%|██▌       | 1880/7232 [00:31<01:22, 64.60it/s]

Gaps (ex-reports):  26%|██▌       | 1887/7232 [00:32<01:21, 65.63it/s]

Gaps (ex-reports):  26%|██▌       | 1894/7232 [00:32<02:02, 43.56it/s]

Gaps (ex-reports):  26%|██▋       | 1900/7232 [00:32<02:23, 37.13it/s]

Gaps (ex-reports):  26%|██▋       | 1907/7232 [00:32<02:06, 42.11it/s]

Gaps (ex-reports):  26%|██▋       | 1913/7232 [00:32<02:00, 44.06it/s]

Gaps (ex-reports):  27%|██▋       | 1920/7232 [00:32<01:51, 47.55it/s]

Gaps (ex-reports):  27%|██▋       | 1926/7232 [00:33<01:50, 47.88it/s]

Gaps (ex-reports):  27%|██▋       | 1935/7232 [00:33<01:53, 46.55it/s]

Gaps (ex-reports):  27%|██▋       | 1945/7232 [00:33<01:31, 57.78it/s]

Gaps (ex-reports):  27%|██▋       | 1952/7232 [00:33<01:40, 52.79it/s]

Gaps (ex-reports):  27%|██▋       | 1963/7232 [00:33<01:25, 61.86it/s]

Gaps (ex-reports):  27%|██▋       | 1970/7232 [00:33<01:23, 63.20it/s]

Gaps (ex-reports):  27%|██▋       | 1981/7232 [00:33<01:10, 74.30it/s]

Gaps (ex-reports):  28%|██▊       | 1989/7232 [00:34<01:27, 60.10it/s]

Gaps (ex-reports):  28%|██▊       | 1998/7232 [00:34<01:21, 63.85it/s]

Gaps (ex-reports):  28%|██▊       | 2005/7232 [00:34<01:24, 61.59it/s]

Gaps (ex-reports):  28%|██▊       | 2014/7232 [00:34<01:31, 56.86it/s]

Gaps (ex-reports):  28%|██▊       | 2027/7232 [00:34<01:13, 71.26it/s]

Gaps (ex-reports):  28%|██▊       | 2035/7232 [00:34<01:39, 52.35it/s]

Gaps (ex-reports):  28%|██▊       | 2047/7232 [00:34<01:22, 62.57it/s]

Gaps (ex-reports):  28%|██▊       | 2055/7232 [00:35<01:28, 58.52it/s]

Gaps (ex-reports):  29%|██▊       | 2064/7232 [00:35<01:21, 63.77it/s]

Gaps (ex-reports):  29%|██▊       | 2072/7232 [00:35<01:25, 60.15it/s]

Gaps (ex-reports):  29%|██▉       | 2084/7232 [00:35<01:20, 64.17it/s]

Gaps (ex-reports):  29%|██▉       | 2091/7232 [00:35<01:22, 62.04it/s]

Gaps (ex-reports):  29%|██▉       | 2100/7232 [00:35<01:18, 65.46it/s]

Gaps (ex-reports):  29%|██▉       | 2107/7232 [00:35<01:28, 58.02it/s]

Gaps (ex-reports):  29%|██▉       | 2118/7232 [00:36<01:27, 58.20it/s]

Gaps (ex-reports):  29%|██▉       | 2128/7232 [00:36<01:20, 63.56it/s]

Gaps (ex-reports):  30%|██▉       | 2135/7232 [00:36<01:19, 64.06it/s]

Gaps (ex-reports):  30%|██▉       | 2142/7232 [00:36<01:23, 61.05it/s]

Gaps (ex-reports):  30%|██▉       | 2150/7232 [00:36<01:20, 63.18it/s]

Gaps (ex-reports):  30%|██▉       | 2162/7232 [00:36<01:16, 66.29it/s]

Gaps (ex-reports):  30%|██▉       | 2169/7232 [00:36<01:18, 64.47it/s]

Gaps (ex-reports):  30%|███       | 2178/7232 [00:37<01:15, 66.90it/s]

Gaps (ex-reports):  30%|███       | 2185/7232 [00:37<01:16, 65.74it/s]

Gaps (ex-reports):  30%|███       | 2194/7232 [00:37<01:11, 69.99it/s]

Gaps (ex-reports):  30%|███       | 2202/7232 [00:37<01:15, 66.30it/s]

Gaps (ex-reports):  31%|███       | 2209/7232 [00:37<02:25, 34.56it/s]

Gaps (ex-reports):  31%|███       | 2220/7232 [00:37<01:49, 45.80it/s]

Gaps (ex-reports):  31%|███       | 2227/7232 [00:38<01:50, 45.19it/s]

Gaps (ex-reports):  31%|███       | 2238/7232 [00:38<01:37, 51.36it/s]

Gaps (ex-reports):  31%|███       | 2245/7232 [00:38<01:31, 54.33it/s]

Gaps (ex-reports):  31%|███       | 2253/7232 [00:38<01:32, 53.94it/s]

Gaps (ex-reports):  31%|███▏      | 2260/7232 [00:38<01:36, 51.55it/s]

Gaps (ex-reports):  31%|███▏      | 2270/7232 [00:38<01:38, 50.21it/s]

Gaps (ex-reports):  32%|███▏      | 2285/7232 [00:39<01:19, 62.48it/s]

Gaps (ex-reports):  32%|███▏      | 2292/7232 [00:39<01:35, 51.76it/s]

Gaps (ex-reports):  32%|███▏      | 2303/7232 [00:39<01:29, 55.01it/s]

Gaps (ex-reports):  32%|███▏      | 2309/7232 [00:39<01:39, 49.47it/s]

Gaps (ex-reports):  32%|███▏      | 2321/7232 [00:39<01:35, 51.66it/s]

Gaps (ex-reports):  32%|███▏      | 2337/7232 [00:40<01:20, 60.87it/s]

Gaps (ex-reports):  32%|███▏      | 2344/7232 [00:40<01:23, 58.73it/s]

Gaps (ex-reports):  33%|███▎      | 2353/7232 [00:40<01:15, 64.80it/s]

Gaps (ex-reports):  33%|███▎      | 2360/7232 [00:40<01:16, 63.42it/s]

Gaps (ex-reports):  33%|███▎      | 2369/7232 [00:40<01:14, 65.14it/s]

Gaps (ex-reports):  33%|███▎      | 2376/7232 [00:40<01:25, 57.10it/s]

Gaps (ex-reports):  33%|███▎      | 2386/7232 [00:40<01:26, 56.04it/s]

Gaps (ex-reports):  33%|███▎      | 2392/7232 [00:40<01:27, 55.35it/s]

Gaps (ex-reports):  33%|███▎      | 2402/7232 [00:41<01:17, 62.27it/s]

Gaps (ex-reports):  33%|███▎      | 2412/7232 [00:41<01:08, 70.07it/s]

Gaps (ex-reports):  33%|███▎      | 2420/7232 [00:41<01:14, 64.29it/s]

Gaps (ex-reports):  34%|███▎      | 2429/7232 [00:41<01:09, 68.85it/s]

Gaps (ex-reports):  34%|███▎      | 2437/7232 [00:41<01:11, 67.24it/s]

Gaps (ex-reports):  34%|███▍      | 2446/7232 [00:41<01:05, 72.88it/s]

Gaps (ex-reports):  34%|███▍      | 2454/7232 [00:41<01:12, 65.79it/s]

Gaps (ex-reports):  34%|███▍      | 2461/7232 [00:41<01:17, 61.30it/s]

Gaps (ex-reports):  34%|███▍      | 2471/7232 [00:42<01:09, 68.34it/s]

Gaps (ex-reports):  34%|███▍      | 2479/7232 [00:42<01:18, 60.37it/s]

Gaps (ex-reports):  34%|███▍      | 2488/7232 [00:42<01:11, 66.46it/s]

Gaps (ex-reports):  34%|███▍      | 2495/7232 [00:42<01:12, 65.37it/s]

Gaps (ex-reports):  35%|███▍      | 2504/7232 [00:42<01:10, 67.36it/s]

Gaps (ex-reports):  35%|███▍      | 2511/7232 [00:43<02:07, 36.91it/s]

Gaps (ex-reports):  35%|███▍      | 2517/7232 [00:43<01:55, 40.68it/s]

Gaps (ex-reports):  35%|███▍      | 2527/7232 [00:43<01:37, 48.31it/s]

Gaps (ex-reports):  35%|███▌      | 2534/7232 [00:43<01:31, 51.45it/s]

Gaps (ex-reports):  35%|███▌      | 2543/7232 [00:43<01:25, 54.93it/s]

Gaps (ex-reports):  35%|███▌      | 2550/7232 [00:43<01:23, 56.16it/s]

Gaps (ex-reports):  35%|███▌      | 2557/7232 [00:43<01:20, 58.34it/s]

Gaps (ex-reports):  35%|███▌      | 2566/7232 [00:43<01:10, 65.94it/s]

Gaps (ex-reports):  36%|███▌      | 2574/7232 [00:44<01:10, 65.85it/s]

Gaps (ex-reports):  36%|███▌      | 2581/7232 [00:44<01:20, 57.81it/s]

Gaps (ex-reports):  36%|███▌      | 2588/7232 [00:44<01:17, 60.09it/s]

Gaps (ex-reports):  36%|███▌      | 2597/7232 [00:44<01:11, 65.12it/s]

Gaps (ex-reports):  36%|███▌      | 2604/7232 [00:44<01:16, 60.23it/s]

Gaps (ex-reports):  36%|███▌      | 2614/7232 [00:44<01:15, 61.18it/s]

Gaps (ex-reports):  36%|███▋      | 2626/7232 [00:44<01:02, 73.54it/s]

Gaps (ex-reports):  36%|███▋      | 2634/7232 [00:44<01:08, 66.93it/s]

Gaps (ex-reports):  37%|███▋      | 2643/7232 [00:45<01:03, 72.43it/s]

Gaps (ex-reports):  37%|███▋      | 2651/7232 [00:45<01:09, 66.23it/s]

Gaps (ex-reports):  37%|███▋      | 2662/7232 [00:45<01:04, 71.32it/s]

Gaps (ex-reports):  37%|███▋      | 2670/7232 [00:45<01:07, 67.62it/s]

Gaps (ex-reports):  37%|███▋      | 2678/7232 [00:45<01:08, 66.18it/s]

Gaps (ex-reports):  37%|███▋      | 2685/7232 [00:45<01:08, 66.05it/s]

Gaps (ex-reports):  37%|███▋      | 2692/7232 [00:45<01:14, 60.83it/s]

Gaps (ex-reports):  37%|███▋      | 2701/7232 [00:45<01:10, 63.86it/s]

Gaps (ex-reports):  37%|███▋      | 2708/7232 [00:46<01:12, 62.31it/s]

Gaps (ex-reports):  38%|███▊      | 2718/7232 [00:46<01:17, 58.14it/s]

Gaps (ex-reports):  38%|███▊      | 2724/7232 [00:46<01:17, 58.04it/s]

Gaps (ex-reports):  38%|███▊      | 2735/7232 [00:46<01:08, 65.35it/s]

Gaps (ex-reports):  38%|███▊      | 2742/7232 [00:46<01:14, 60.34it/s]

Gaps (ex-reports):  38%|███▊      | 2749/7232 [00:46<01:13, 61.04it/s]

Gaps (ex-reports):  38%|███▊      | 2756/7232 [00:46<01:20, 55.81it/s]

Gaps (ex-reports):  38%|███▊      | 2762/7232 [00:47<01:26, 51.42it/s]

Gaps (ex-reports):  38%|███▊      | 2773/7232 [00:47<01:09, 63.92it/s]

Gaps (ex-reports):  38%|███▊      | 2781/7232 [00:47<01:14, 59.89it/s]

Gaps (ex-reports):  39%|███▊      | 2791/7232 [00:47<01:13, 60.39it/s]

Gaps (ex-reports):  39%|███▉      | 2803/7232 [00:47<00:59, 73.92it/s]

Gaps (ex-reports):  39%|███▉      | 2811/7232 [00:47<01:14, 59.31it/s]

Gaps (ex-reports):  39%|███▉      | 2820/7232 [00:48<01:39, 44.38it/s]

Gaps (ex-reports):  39%|███▉      | 2826/7232 [00:48<01:57, 37.40it/s]

Gaps (ex-reports):  39%|███▉      | 2833/7232 [00:48<01:52, 39.26it/s]

Gaps (ex-reports):  39%|███▉      | 2838/7232 [00:48<01:49, 40.05it/s]

Gaps (ex-reports):  39%|███▉      | 2844/7232 [00:48<01:40, 43.51it/s]

Gaps (ex-reports):  39%|███▉      | 2849/7232 [00:48<01:44, 41.87it/s]

Gaps (ex-reports):  40%|███▉      | 2857/7232 [00:49<01:35, 45.89it/s]

Gaps (ex-reports):  40%|███▉      | 2864/7232 [00:49<01:37, 45.01it/s]

Gaps (ex-reports):  40%|███▉      | 2875/7232 [00:49<01:22, 53.02it/s]

Gaps (ex-reports):  40%|███▉      | 2881/7232 [00:49<01:23, 52.14it/s]

Gaps (ex-reports):  40%|████      | 2894/7232 [00:49<01:08, 63.78it/s]

Gaps (ex-reports):  40%|████      | 2901/7232 [00:49<01:18, 55.14it/s]

Gaps (ex-reports):  40%|████      | 2915/7232 [00:49<00:59, 73.01it/s]

Gaps (ex-reports):  40%|████      | 2924/7232 [00:50<01:02, 69.19it/s]

Gaps (ex-reports):  41%|████      | 2932/7232 [00:50<01:05, 65.55it/s]

Gaps (ex-reports):  41%|████      | 2941/7232 [00:50<01:07, 64.02it/s]

Gaps (ex-reports):  41%|████      | 2948/7232 [00:50<01:08, 62.26it/s]

Gaps (ex-reports):  41%|████      | 2959/7232 [00:50<01:00, 70.14it/s]

Gaps (ex-reports):  41%|████      | 2967/7232 [00:50<01:02, 68.31it/s]

Gaps (ex-reports):  41%|████      | 2976/7232 [00:50<01:04, 66.26it/s]

Gaps (ex-reports):  41%|████      | 2983/7232 [00:50<01:05, 65.16it/s]

Gaps (ex-reports):  41%|████▏     | 2992/7232 [00:51<01:00, 69.69it/s]

Gaps (ex-reports):  41%|████▏     | 3000/7232 [00:51<01:11, 58.94it/s]

Gaps (ex-reports):  42%|████▏     | 3010/7232 [00:51<01:05, 64.60it/s]

Gaps (ex-reports):  42%|████▏     | 3017/7232 [00:51<01:04, 65.50it/s]

Gaps (ex-reports):  42%|████▏     | 3026/7232 [00:51<00:58, 71.44it/s]

Gaps (ex-reports):  42%|████▏     | 3034/7232 [00:51<01:03, 65.95it/s]

Gaps (ex-reports):  42%|████▏     | 3044/7232 [00:51<01:07, 61.95it/s]

Gaps (ex-reports):  42%|████▏     | 3053/7232 [00:52<01:10, 59.42it/s]

Gaps (ex-reports):  42%|████▏     | 3060/7232 [00:52<01:08, 60.56it/s]

Gaps (ex-reports):  42%|████▏     | 3068/7232 [00:52<01:06, 62.32it/s]

Gaps (ex-reports):  43%|████▎     | 3077/7232 [00:52<01:07, 61.75it/s]

Gaps (ex-reports):  43%|████▎     | 3088/7232 [00:52<00:58, 71.13it/s]

Gaps (ex-reports):  43%|████▎     | 3096/7232 [00:52<01:01, 67.27it/s]

Gaps (ex-reports):  43%|████▎     | 3103/7232 [00:52<01:12, 56.77it/s]

Gaps (ex-reports):  43%|████▎     | 3109/7232 [00:53<01:16, 53.61it/s]

Gaps (ex-reports):  43%|████▎     | 3115/7232 [00:53<01:16, 53.71it/s]

Gaps (ex-reports):  43%|████▎     | 3125/7232 [00:53<01:59, 34.47it/s]

Gaps (ex-reports):  43%|████▎     | 3139/7232 [00:53<01:27, 46.73it/s]

Gaps (ex-reports):  44%|████▎     | 3147/7232 [00:53<01:20, 50.85it/s]

Gaps (ex-reports):  44%|████▎     | 3154/7232 [00:53<01:17, 52.75it/s]

Gaps (ex-reports):  44%|████▎     | 3162/7232 [00:54<01:11, 56.59it/s]

Gaps (ex-reports):  44%|████▍     | 3169/7232 [00:54<01:12, 56.20it/s]

Gaps (ex-reports):  44%|████▍     | 3176/7232 [00:54<01:10, 57.43it/s]

Gaps (ex-reports):  44%|████▍     | 3184/7232 [00:54<01:06, 60.99it/s]

Gaps (ex-reports):  44%|████▍     | 3191/7232 [00:54<01:06, 60.62it/s]

Gaps (ex-reports):  44%|████▍     | 3198/7232 [00:54<01:08, 58.79it/s]

Gaps (ex-reports):  44%|████▍     | 3205/7232 [00:54<01:12, 55.28it/s]

Gaps (ex-reports):  44%|████▍     | 3217/7232 [00:54<00:57, 70.35it/s]

Gaps (ex-reports):  45%|████▍     | 3225/7232 [00:55<01:05, 61.47it/s]

Gaps (ex-reports):  45%|████▍     | 3235/7232 [00:55<00:56, 70.16it/s]

Gaps (ex-reports):  45%|████▍     | 3243/7232 [00:55<01:05, 61.24it/s]

Gaps (ex-reports):  45%|████▍     | 3252/7232 [00:55<01:00, 66.22it/s]

Gaps (ex-reports):  45%|████▌     | 3260/7232 [00:55<01:10, 56.55it/s]

Gaps (ex-reports):  45%|████▌     | 3270/7232 [00:55<00:59, 66.07it/s]

Gaps (ex-reports):  45%|████▌     | 3278/7232 [00:55<01:01, 63.84it/s]

Gaps (ex-reports):  45%|████▌     | 3287/7232 [00:56<00:59, 66.53it/s]

Gaps (ex-reports):  46%|████▌     | 3295/7232 [00:56<01:04, 61.32it/s]

Gaps (ex-reports):  46%|████▌     | 3305/7232 [00:56<01:01, 63.84it/s]

Gaps (ex-reports):  46%|████▌     | 3312/7232 [00:56<01:08, 57.28it/s]

Gaps (ex-reports):  46%|████▌     | 3323/7232 [00:56<01:01, 63.57it/s]

Gaps (ex-reports):  46%|████▌     | 3330/7232 [00:56<01:09, 56.21it/s]

Gaps (ex-reports):  46%|████▌     | 3339/7232 [00:56<01:02, 62.23it/s]

Gaps (ex-reports):  46%|████▋     | 3346/7232 [00:57<01:00, 63.86it/s]

Gaps (ex-reports):  46%|████▋     | 3355/7232 [00:57<00:57, 67.88it/s]

Gaps (ex-reports):  46%|████▋     | 3362/7232 [00:57<01:02, 62.15it/s]

Gaps (ex-reports):  47%|████▋     | 3372/7232 [00:57<00:58, 65.83it/s]

Gaps (ex-reports):  47%|████▋     | 3379/7232 [00:57<01:00, 63.24it/s]

Gaps (ex-reports):  47%|████▋     | 3389/7232 [00:57<00:59, 64.44it/s]

Gaps (ex-reports):  47%|████▋     | 3396/7232 [00:57<01:06, 57.92it/s]

Gaps (ex-reports):  47%|████▋     | 3407/7232 [00:57<01:01, 62.32it/s]

Gaps (ex-reports):  47%|████▋     | 3414/7232 [00:58<01:05, 58.02it/s]

Gaps (ex-reports):  47%|████▋     | 3423/7232 [00:58<01:01, 62.04it/s]

Gaps (ex-reports):  47%|████▋     | 3430/7232 [00:58<01:03, 59.65it/s]

Gaps (ex-reports):  48%|████▊     | 3437/7232 [00:58<01:03, 59.58it/s]

Gaps (ex-reports):  48%|████▊     | 3443/7232 [00:58<01:59, 31.79it/s]

Gaps (ex-reports):  48%|████▊     | 3448/7232 [00:59<01:55, 32.82it/s]

Gaps (ex-reports):  48%|████▊     | 3456/7232 [00:59<01:37, 38.55it/s]

Gaps (ex-reports):  48%|████▊     | 3461/7232 [00:59<01:35, 39.31it/s]

Gaps (ex-reports):  48%|████▊     | 3470/7232 [00:59<01:25, 44.12it/s]

Gaps (ex-reports):  48%|████▊     | 3477/7232 [00:59<01:20, 46.92it/s]

Gaps (ex-reports):  48%|████▊     | 3486/7232 [00:59<01:09, 53.93it/s]

Gaps (ex-reports):  48%|████▊     | 3496/7232 [00:59<00:59, 62.50it/s]

Gaps (ex-reports):  48%|████▊     | 3504/7232 [00:59<00:56, 65.99it/s]

Gaps (ex-reports):  49%|████▊     | 3511/7232 [01:00<00:57, 65.01it/s]

Gaps (ex-reports):  49%|████▊     | 3518/7232 [01:00<01:00, 61.68it/s]

Gaps (ex-reports):  49%|████▉     | 3526/7232 [01:00<00:59, 62.60it/s]

Gaps (ex-reports):  49%|████▉     | 3533/7232 [01:00<00:59, 62.56it/s]

Gaps (ex-reports):  49%|████▉     | 3542/7232 [01:00<00:56, 65.00it/s]

Gaps (ex-reports):  49%|████▉     | 3549/7232 [01:00<00:55, 66.06it/s]

Gaps (ex-reports):  49%|████▉     | 3559/7232 [01:00<00:50, 72.32it/s]

Gaps (ex-reports):  49%|████▉     | 3567/7232 [01:00<00:57, 63.73it/s]

Gaps (ex-reports):  49%|████▉     | 3577/7232 [01:01<00:56, 64.80it/s]

Gaps (ex-reports):  50%|████▉     | 3584/7232 [01:01<01:00, 59.93it/s]

Gaps (ex-reports):  50%|████▉     | 3594/7232 [01:01<01:14, 48.81it/s]

Gaps (ex-reports):  50%|████▉     | 3610/7232 [01:01<00:58, 61.41it/s]

Gaps (ex-reports):  50%|█████     | 3617/7232 [01:01<01:05, 55.52it/s]

Gaps (ex-reports):  50%|█████     | 3626/7232 [01:02<01:03, 56.97it/s]

Gaps (ex-reports):  50%|█████     | 3633/7232 [01:02<01:05, 54.89it/s]

Gaps (ex-reports):  50%|█████     | 3644/7232 [01:02<00:55, 64.90it/s]

Gaps (ex-reports):  50%|█████     | 3651/7232 [01:02<00:54, 65.35it/s]

Gaps (ex-reports):  51%|█████     | 3658/7232 [01:02<00:54, 65.41it/s]

Gaps (ex-reports):  51%|█████     | 3665/7232 [01:02<00:56, 63.33it/s]

Gaps (ex-reports):  51%|█████     | 3674/7232 [01:02<00:52, 67.59it/s]

Gaps (ex-reports):  51%|█████     | 3681/7232 [01:02<00:55, 63.76it/s]

Gaps (ex-reports):  51%|█████     | 3691/7232 [01:02<00:51, 69.00it/s]

Gaps (ex-reports):  51%|█████     | 3699/7232 [01:03<00:52, 67.57it/s]

Gaps (ex-reports):  51%|█████▏    | 3709/7232 [01:03<00:50, 70.29it/s]

Gaps (ex-reports):  51%|█████▏    | 3717/7232 [01:03<00:52, 66.37it/s]

Gaps (ex-reports):  52%|█████▏    | 3726/7232 [01:03<00:54, 64.84it/s]

Gaps (ex-reports):  52%|█████▏    | 3733/7232 [01:03<00:54, 64.69it/s]

Gaps (ex-reports):  52%|█████▏    | 3742/7232 [01:03<00:54, 63.76it/s]

Gaps (ex-reports):  52%|█████▏    | 3749/7232 [01:04<01:42, 33.86it/s]

Gaps (ex-reports):  52%|█████▏    | 3758/7232 [01:04<01:27, 39.62it/s]

Gaps (ex-reports):  52%|█████▏    | 3767/7232 [01:04<01:15, 46.20it/s]

Gaps (ex-reports):  52%|█████▏    | 3773/7232 [01:04<01:25, 40.45it/s]

Gaps (ex-reports):  52%|█████▏    | 3784/7232 [01:04<01:19, 43.60it/s]

Gaps (ex-reports):  53%|█████▎    | 3799/7232 [01:05<00:55, 61.77it/s]

Gaps (ex-reports):  53%|█████▎    | 3807/7232 [01:05<01:02, 54.72it/s]

Gaps (ex-reports):  53%|█████▎    | 3816/7232 [01:05<00:59, 57.72it/s]

Gaps (ex-reports):  53%|█████▎    | 3824/7232 [01:05<00:55, 61.69it/s]

Gaps (ex-reports):  53%|█████▎    | 3832/7232 [01:05<00:57, 59.10it/s]

Gaps (ex-reports):  53%|█████▎    | 3840/7232 [01:05<00:53, 63.71it/s]

Gaps (ex-reports):  53%|█████▎    | 3850/7232 [01:05<00:51, 65.33it/s]

Gaps (ex-reports):  53%|█████▎    | 3858/7232 [01:06<00:54, 62.13it/s]

Gaps (ex-reports):  53%|█████▎    | 3869/7232 [01:06<00:45, 73.29it/s]

Gaps (ex-reports):  54%|█████▎    | 3877/7232 [01:06<00:57, 58.39it/s]

Gaps (ex-reports):  54%|█████▍    | 3889/7232 [01:06<00:52, 64.12it/s]

Gaps (ex-reports):  54%|█████▍    | 3897/7232 [01:06<00:52, 63.30it/s]

Gaps (ex-reports):  54%|█████▍    | 3905/7232 [01:06<00:49, 66.55it/s]

Gaps (ex-reports):  54%|█████▍    | 3913/7232 [01:06<00:58, 56.74it/s]

Gaps (ex-reports):  54%|█████▍    | 3922/7232 [01:07<00:55, 59.23it/s]

Gaps (ex-reports):  54%|█████▍    | 3929/7232 [01:07<01:05, 50.40it/s]

Gaps (ex-reports):  54%|█████▍    | 3941/7232 [01:07<00:53, 61.17it/s]

Gaps (ex-reports):  55%|█████▍    | 3948/7232 [01:07<01:01, 53.38it/s]

Gaps (ex-reports):  55%|█████▍    | 3959/7232 [01:07<00:53, 61.03it/s]

Gaps (ex-reports):  55%|█████▍    | 3966/7232 [01:07<01:02, 52.19it/s]

Gaps (ex-reports):  55%|█████▍    | 3975/7232 [01:08<00:57, 56.46it/s]

Gaps (ex-reports):  55%|█████▌    | 3982/7232 [01:08<00:56, 57.66it/s]

Gaps (ex-reports):  55%|█████▌    | 3991/7232 [01:08<00:57, 56.57it/s]

Gaps (ex-reports):  55%|█████▌    | 3998/7232 [01:08<00:59, 54.41it/s]

Gaps (ex-reports):  55%|█████▌    | 4007/7232 [01:08<00:52, 61.50it/s]

Gaps (ex-reports):  56%|█████▌    | 4015/7232 [01:08<00:51, 62.92it/s]

Gaps (ex-reports):  56%|█████▌    | 4024/7232 [01:08<00:56, 56.91it/s]

Gaps (ex-reports):  56%|█████▌    | 4039/7232 [01:09<00:44, 71.76it/s]

Gaps (ex-reports):  56%|█████▌    | 4047/7232 [01:09<00:57, 55.60it/s]

Gaps (ex-reports):  56%|█████▌    | 4054/7232 [01:09<01:18, 40.38it/s]

Gaps (ex-reports):  56%|█████▌    | 4067/7232 [01:09<01:02, 50.50it/s]

Gaps (ex-reports):  56%|█████▋    | 4074/7232 [01:09<01:00, 52.28it/s]

Gaps (ex-reports):  56%|█████▋    | 4083/7232 [01:10<01:01, 51.33it/s]

Gaps (ex-reports):  57%|█████▋    | 4089/7232 [01:10<01:00, 51.90it/s]

Gaps (ex-reports):  57%|█████▋    | 4099/7232 [01:10<00:53, 58.32it/s]

Gaps (ex-reports):  57%|█████▋    | 4106/7232 [01:10<00:53, 58.22it/s]

Gaps (ex-reports):  57%|█████▋    | 4115/7232 [01:10<00:51, 60.84it/s]

Gaps (ex-reports):  57%|█████▋    | 4122/7232 [01:10<00:50, 61.77it/s]

Gaps (ex-reports):  57%|█████▋    | 4131/7232 [01:10<00:46, 66.20it/s]

Gaps (ex-reports):  57%|█████▋    | 4138/7232 [01:10<00:54, 56.79it/s]

Gaps (ex-reports):  57%|█████▋    | 4147/7232 [01:11<00:48, 63.34it/s]

Gaps (ex-reports):  57%|█████▋    | 4154/7232 [01:11<01:00, 51.16it/s]

Gaps (ex-reports):  58%|█████▊    | 4166/7232 [01:11<00:52, 58.36it/s]

Gaps (ex-reports):  58%|█████▊    | 4173/7232 [01:11<00:50, 60.66it/s]

Gaps (ex-reports):  58%|█████▊    | 4182/7232 [01:11<00:49, 62.14it/s]

Gaps (ex-reports):  58%|█████▊    | 4189/7232 [01:11<00:48, 63.15it/s]

Gaps (ex-reports):  58%|█████▊    | 4198/7232 [01:11<00:44, 67.80it/s]

Gaps (ex-reports):  58%|█████▊    | 4205/7232 [01:11<00:45, 67.05it/s]

Gaps (ex-reports):  58%|█████▊    | 4212/7232 [01:12<00:47, 64.16it/s]

Gaps (ex-reports):  58%|█████▊    | 4220/7232 [01:12<00:44, 67.85it/s]

Gaps (ex-reports):  58%|█████▊    | 4227/7232 [01:12<00:54, 55.11it/s]

Gaps (ex-reports):  59%|█████▊    | 4239/7232 [01:12<00:47, 63.03it/s]

Gaps (ex-reports):  59%|█████▊    | 4246/7232 [01:12<00:47, 62.46it/s]

Gaps (ex-reports):  59%|█████▉    | 4256/7232 [01:12<00:49, 60.26it/s]

Gaps (ex-reports):  59%|█████▉    | 4266/7232 [01:12<00:44, 66.82it/s]

Gaps (ex-reports):  59%|█████▉    | 4273/7232 [01:13<00:50, 58.06it/s]

Gaps (ex-reports):  59%|█████▉    | 4286/7232 [01:13<00:39, 74.29it/s]

Gaps (ex-reports):  59%|█████▉    | 4295/7232 [01:13<00:45, 63.88it/s]

Gaps (ex-reports):  60%|█████▉    | 4305/7232 [01:13<00:46, 63.46it/s]

Gaps (ex-reports):  60%|█████▉    | 4312/7232 [01:13<00:45, 64.39it/s]

Gaps (ex-reports):  60%|█████▉    | 4321/7232 [01:13<00:44, 65.73it/s]

Gaps (ex-reports):  60%|█████▉    | 4328/7232 [01:13<00:48, 59.46it/s]

Gaps (ex-reports):  60%|█████▉    | 4339/7232 [01:14<00:41, 69.79it/s]

Gaps (ex-reports):  60%|██████    | 4347/7232 [01:14<00:48, 59.36it/s]

Gaps (ex-reports):  60%|██████    | 4357/7232 [01:14<00:44, 64.40it/s]

Gaps (ex-reports):  60%|██████    | 4364/7232 [01:14<00:44, 64.41it/s]

Gaps (ex-reports):  60%|██████    | 4371/7232 [01:14<01:09, 41.12it/s]

Gaps (ex-reports):  61%|██████    | 4377/7232 [01:14<01:08, 41.49it/s]

Gaps (ex-reports):  61%|██████    | 4383/7232 [01:15<01:04, 44.06it/s]

Gaps (ex-reports):  61%|██████    | 4391/7232 [01:15<00:55, 51.62it/s]

Gaps (ex-reports):  61%|██████    | 4397/7232 [01:15<00:56, 50.19it/s]

Gaps (ex-reports):  61%|██████    | 4405/7232 [01:15<00:59, 47.14it/s]

Gaps (ex-reports):  61%|██████    | 4413/7232 [01:15<00:53, 53.18it/s]

Gaps (ex-reports):  61%|██████    | 4420/7232 [01:15<00:51, 55.02it/s]

Gaps (ex-reports):  61%|██████    | 4428/7232 [01:15<00:47, 58.45it/s]

Gaps (ex-reports):  61%|██████▏   | 4436/7232 [01:15<00:44, 63.24it/s]

Gaps (ex-reports):  61%|██████▏   | 4444/7232 [01:16<00:41, 67.45it/s]

Gaps (ex-reports):  62%|██████▏   | 4452/7232 [01:16<00:49, 56.53it/s]

Gaps (ex-reports):  62%|██████▏   | 4462/7232 [01:16<00:41, 66.72it/s]

Gaps (ex-reports):  62%|██████▏   | 4470/7232 [01:16<00:44, 61.93it/s]

Gaps (ex-reports):  62%|██████▏   | 4478/7232 [01:16<00:44, 62.55it/s]

Gaps (ex-reports):  62%|██████▏   | 4490/7232 [01:16<00:37, 74.05it/s]

Gaps (ex-reports):  62%|██████▏   | 4498/7232 [01:16<00:46, 59.19it/s]

Gaps (ex-reports):  62%|██████▏   | 4505/7232 [01:17<00:45, 60.26it/s]

Gaps (ex-reports):  62%|██████▏   | 4512/7232 [01:17<00:45, 60.43it/s]

Gaps (ex-reports):  63%|██████▎   | 4521/7232 [01:17<00:42, 63.07it/s]

Gaps (ex-reports):  63%|██████▎   | 4528/7232 [01:17<00:47, 57.40it/s]

Gaps (ex-reports):  63%|██████▎   | 4542/7232 [01:17<00:38, 69.17it/s]

Gaps (ex-reports):  63%|██████▎   | 4550/7232 [01:17<00:40, 66.32it/s]

Gaps (ex-reports):  63%|██████▎   | 4557/7232 [01:17<00:40, 65.82it/s]

Gaps (ex-reports):  63%|██████▎   | 4564/7232 [01:17<00:41, 64.22it/s]

Gaps (ex-reports):  63%|██████▎   | 4571/7232 [01:18<00:45, 58.25it/s]

Gaps (ex-reports):  63%|██████▎   | 4581/7232 [01:18<00:43, 61.21it/s]

Gaps (ex-reports):  63%|██████▎   | 4588/7232 [01:18<00:43, 60.17it/s]

Gaps (ex-reports):  64%|██████▎   | 4600/7232 [01:18<00:38, 68.05it/s]

Gaps (ex-reports):  64%|██████▎   | 4607/7232 [01:18<00:38, 67.82it/s]

Gaps (ex-reports):  64%|██████▍   | 4616/7232 [01:18<00:41, 63.29it/s]

Gaps (ex-reports):  64%|██████▍   | 4625/7232 [01:18<00:38, 67.03it/s]

Gaps (ex-reports):  64%|██████▍   | 4632/7232 [01:19<00:45, 57.27it/s]

Gaps (ex-reports):  64%|██████▍   | 4641/7232 [01:19<00:40, 64.77it/s]

Gaps (ex-reports):  64%|██████▍   | 4648/7232 [01:19<00:43, 58.94it/s]

Gaps (ex-reports):  64%|██████▍   | 4659/7232 [01:19<00:40, 63.36it/s]

Gaps (ex-reports):  65%|██████▍   | 4668/7232 [01:19<00:37, 68.00it/s]

Gaps (ex-reports):  65%|██████▍   | 4677/7232 [01:19<00:37, 68.47it/s]

Gaps (ex-reports):  65%|██████▍   | 4685/7232 [01:19<00:35, 70.82it/s]

Gaps (ex-reports):  65%|██████▍   | 4693/7232 [01:19<00:35, 71.53it/s]

Gaps (ex-reports):  65%|██████▌   | 4701/7232 [01:20<00:37, 67.27it/s]

Gaps (ex-reports):  65%|██████▌   | 4708/7232 [01:20<00:37, 67.73it/s]

Gaps (ex-reports):  65%|██████▌   | 4715/7232 [01:20<00:39, 63.71it/s]

Gaps (ex-reports):  65%|██████▌   | 4724/7232 [01:20<00:36, 68.44it/s]

Gaps (ex-reports):  65%|██████▌   | 4731/7232 [01:20<00:38, 65.24it/s]

Gaps (ex-reports):  66%|██████▌   | 4740/7232 [01:20<00:34, 71.73it/s]

Gaps (ex-reports):  66%|██████▌   | 4748/7232 [01:20<00:41, 59.50it/s]

Gaps (ex-reports):  66%|██████▌   | 4759/7232 [01:20<00:35, 69.80it/s]

Gaps (ex-reports):  66%|██████▌   | 4767/7232 [01:21<00:35, 69.80it/s]

Gaps (ex-reports):  66%|██████▌   | 4777/7232 [01:21<00:34, 70.94it/s]

Gaps (ex-reports):  66%|██████▌   | 4785/7232 [01:21<00:34, 71.69it/s]

Gaps (ex-reports):  66%|██████▋   | 4794/7232 [01:21<00:33, 73.03it/s]

Gaps (ex-reports):  66%|██████▋   | 4802/7232 [01:21<00:34, 70.20it/s]

Gaps (ex-reports):  67%|██████▋   | 4810/7232 [01:21<00:33, 71.53it/s]

Gaps (ex-reports):  67%|██████▋   | 4819/7232 [01:21<00:31, 75.98it/s]

Gaps (ex-reports):  67%|██████▋   | 4827/7232 [01:21<00:33, 71.09it/s]

Gaps (ex-reports):  67%|██████▋   | 4837/7232 [01:21<00:31, 76.47it/s]

Gaps (ex-reports):  67%|██████▋   | 4845/7232 [01:22<00:32, 73.89it/s]

Gaps (ex-reports):  67%|██████▋   | 4854/7232 [01:22<00:33, 70.66it/s]

Gaps (ex-reports):  67%|██████▋   | 4862/7232 [01:22<00:33, 71.42it/s]

Gaps (ex-reports):  67%|██████▋   | 4870/7232 [01:22<00:33, 70.92it/s]

Gaps (ex-reports):  67%|██████▋   | 4878/7232 [01:22<00:32, 72.22it/s]

Gaps (ex-reports):  68%|██████▊   | 4886/7232 [01:22<00:33, 70.66it/s]

Gaps (ex-reports):  68%|██████▊   | 4895/7232 [01:22<00:33, 69.00it/s]

Gaps (ex-reports):  68%|██████▊   | 4902/7232 [01:22<00:34, 66.72it/s]

Gaps (ex-reports):  68%|██████▊   | 4911/7232 [01:23<00:33, 69.55it/s]

Gaps (ex-reports):  68%|██████▊   | 4918/7232 [01:23<00:35, 64.68it/s]

Gaps (ex-reports):  68%|██████▊   | 4927/7232 [01:23<00:33, 67.92it/s]

Gaps (ex-reports):  68%|██████▊   | 4934/7232 [01:23<00:37, 61.18it/s]

Gaps (ex-reports):  68%|██████▊   | 4945/7232 [01:23<00:31, 72.71it/s]

Gaps (ex-reports):  68%|██████▊   | 4953/7232 [01:24<01:01, 36.97it/s]

Gaps (ex-reports):  69%|██████▊   | 4961/7232 [01:24<00:52, 43.00it/s]

Gaps (ex-reports):  69%|██████▊   | 4969/7232 [01:24<00:48, 46.70it/s]

Gaps (ex-reports):  69%|██████▉   | 4977/7232 [01:24<00:45, 49.66it/s]

Gaps (ex-reports):  69%|██████▉   | 4985/7232 [01:24<00:45, 49.09it/s]

Gaps (ex-reports):  69%|██████▉   | 4996/7232 [01:24<00:36, 60.85it/s]

Gaps (ex-reports):  69%|██████▉   | 5004/7232 [01:24<00:41, 54.07it/s]

Gaps (ex-reports):  69%|██████▉   | 5015/7232 [01:25<00:34, 64.94it/s]

Gaps (ex-reports):  69%|██████▉   | 5023/7232 [01:25<00:34, 64.18it/s]

Gaps (ex-reports):  70%|██████▉   | 5032/7232 [01:25<00:35, 61.70it/s]

Gaps (ex-reports):  70%|██████▉   | 5039/7232 [01:25<00:36, 59.68it/s]

Gaps (ex-reports):  70%|██████▉   | 5048/7232 [01:25<00:36, 59.36it/s]

Gaps (ex-reports):  70%|██████▉   | 5060/7232 [01:25<00:31, 68.92it/s]

Gaps (ex-reports):  70%|███████   | 5068/7232 [01:25<00:31, 69.51it/s]

Gaps (ex-reports):  70%|███████   | 5076/7232 [01:25<00:31, 68.24it/s]

Gaps (ex-reports):  70%|███████   | 5084/7232 [01:26<00:36, 58.21it/s]

Gaps (ex-reports):  70%|███████   | 5093/7232 [01:26<00:36, 58.68it/s]

Gaps (ex-reports):  71%|███████   | 5105/7232 [01:26<00:32, 64.64it/s]

Gaps (ex-reports):  71%|███████   | 5112/7232 [01:26<00:37, 56.12it/s]

Gaps (ex-reports):  71%|███████   | 5123/7232 [01:26<00:34, 61.02it/s]

Gaps (ex-reports):  71%|███████   | 5130/7232 [01:26<00:34, 60.96it/s]

Gaps (ex-reports):  71%|███████   | 5137/7232 [01:26<00:34, 61.53it/s]

Gaps (ex-reports):  71%|███████   | 5145/7232 [01:27<00:33, 62.28it/s]

Gaps (ex-reports):  71%|███████▏  | 5153/7232 [01:27<00:33, 62.76it/s]

Gaps (ex-reports):  71%|███████▏  | 5161/7232 [01:27<00:33, 62.68it/s]

Gaps (ex-reports):  71%|███████▏  | 5169/7232 [01:27<00:31, 64.53it/s]

Gaps (ex-reports):  72%|███████▏  | 5176/7232 [01:27<00:33, 61.33it/s]

Gaps (ex-reports):  72%|███████▏  | 5188/7232 [01:27<00:30, 67.13it/s]

Gaps (ex-reports):  72%|███████▏  | 5195/7232 [01:27<00:37, 53.75it/s]

Gaps (ex-reports):  72%|███████▏  | 5206/7232 [01:28<00:41, 48.55it/s]

Gaps (ex-reports):  72%|███████▏  | 5221/7232 [01:28<00:32, 62.08it/s]

Gaps (ex-reports):  72%|███████▏  | 5228/7232 [01:28<00:33, 60.11it/s]

Gaps (ex-reports):  72%|███████▏  | 5238/7232 [01:28<00:30, 66.24it/s]

Gaps (ex-reports):  73%|███████▎  | 5246/7232 [01:28<00:32, 60.71it/s]

Gaps (ex-reports):  73%|███████▎  | 5256/7232 [01:28<00:31, 62.20it/s]

Gaps (ex-reports):  73%|███████▎  | 5264/7232 [01:29<00:30, 63.95it/s]

Gaps (ex-reports):  73%|███████▎  | 5271/7232 [01:29<00:30, 64.64it/s]

Gaps (ex-reports):  73%|███████▎  | 5278/7232 [01:29<00:31, 62.91it/s]

Gaps (ex-reports):  73%|███████▎  | 5286/7232 [01:29<00:31, 62.63it/s]

Gaps (ex-reports):  73%|███████▎  | 5293/7232 [01:29<00:32, 59.90it/s]

Gaps (ex-reports):  73%|███████▎  | 5300/7232 [01:29<00:35, 53.73it/s]

Gaps (ex-reports):  73%|███████▎  | 5306/7232 [01:29<00:35, 54.27it/s]

Gaps (ex-reports):  73%|███████▎  | 5313/7232 [01:29<00:34, 55.68it/s]

Gaps (ex-reports):  74%|███████▎  | 5321/7232 [01:30<00:31, 60.77it/s]

Gaps (ex-reports):  74%|███████▎  | 5328/7232 [01:30<00:30, 63.11it/s]

Gaps (ex-reports):  74%|███████▍  | 5335/7232 [01:30<00:29, 63.35it/s]

Gaps (ex-reports):  74%|███████▍  | 5343/7232 [01:30<00:28, 65.94it/s]

Gaps (ex-reports):  74%|███████▍  | 5352/7232 [01:30<00:27, 67.80it/s]

Gaps (ex-reports):  74%|███████▍  | 5359/7232 [01:30<00:27, 68.00it/s]

Gaps (ex-reports):  74%|███████▍  | 5367/7232 [01:30<00:26, 70.16it/s]

Gaps (ex-reports):  74%|███████▍  | 5375/7232 [01:30<00:26, 70.75it/s]

Gaps (ex-reports):  74%|███████▍  | 5383/7232 [01:30<00:26, 69.34it/s]

Gaps (ex-reports):  75%|███████▍  | 5390/7232 [01:31<00:33, 54.54it/s]

Gaps (ex-reports):  75%|███████▍  | 5404/7232 [01:31<00:27, 66.77it/s]

Gaps (ex-reports):  75%|███████▍  | 5415/7232 [01:31<00:27, 66.72it/s]

Gaps (ex-reports):  75%|███████▍  | 5422/7232 [01:31<00:28, 63.21it/s]

Gaps (ex-reports):  75%|███████▌  | 5434/7232 [01:31<00:26, 66.89it/s]

Gaps (ex-reports):  75%|███████▌  | 5442/7232 [01:31<00:26, 68.61it/s]

Gaps (ex-reports):  75%|███████▌  | 5449/7232 [01:31<00:28, 63.07it/s]

Gaps (ex-reports):  75%|███████▌  | 5460/7232 [01:32<00:27, 64.99it/s]

Gaps (ex-reports):  76%|███████▌  | 5467/7232 [01:32<00:28, 61.66it/s]

Gaps (ex-reports):  76%|███████▌  | 5474/7232 [01:32<00:27, 63.43it/s]

Gaps (ex-reports):  76%|███████▌  | 5481/7232 [01:32<00:30, 57.54it/s]

Gaps (ex-reports):  76%|███████▌  | 5492/7232 [01:32<00:25, 67.85it/s]

Gaps (ex-reports):  76%|███████▌  | 5499/7232 [01:32<00:26, 65.30it/s]

Gaps (ex-reports):  76%|███████▌  | 5507/7232 [01:32<00:25, 67.54it/s]

Gaps (ex-reports):  76%|███████▌  | 5514/7232 [01:33<00:28, 61.05it/s]

Gaps (ex-reports):  76%|███████▋  | 5523/7232 [01:33<00:25, 66.22it/s]

Gaps (ex-reports):  76%|███████▋  | 5530/7232 [01:33<00:27, 62.97it/s]

Gaps (ex-reports):  77%|███████▋  | 5537/7232 [01:33<00:26, 64.12it/s]

Gaps (ex-reports):  77%|███████▋  | 5544/7232 [01:33<00:31, 53.14it/s]

Gaps (ex-reports):  77%|███████▋  | 5551/7232 [01:33<00:30, 55.59it/s]

Gaps (ex-reports):  77%|███████▋  | 5559/7232 [01:33<00:29, 57.20it/s]

Gaps (ex-reports):  77%|███████▋  | 5568/7232 [01:33<00:25, 64.61it/s]

Gaps (ex-reports):  77%|███████▋  | 5575/7232 [01:34<00:52, 31.83it/s]

Gaps (ex-reports):  77%|███████▋  | 5581/7232 [01:34<00:51, 32.30it/s]

Gaps (ex-reports):  77%|███████▋  | 5588/7232 [01:34<00:43, 38.02it/s]

Gaps (ex-reports):  77%|███████▋  | 5594/7232 [01:34<00:43, 37.91it/s]

Gaps (ex-reports):  77%|███████▋  | 5599/7232 [01:35<00:44, 36.58it/s]

Gaps (ex-reports):  78%|███████▊  | 5608/7232 [01:35<00:35, 45.66it/s]

Gaps (ex-reports):  78%|███████▊  | 5614/7232 [01:35<00:34, 46.66it/s]

Gaps (ex-reports):  78%|███████▊  | 5621/7232 [01:35<00:31, 51.13it/s]

Gaps (ex-reports):  78%|███████▊  | 5629/7232 [01:35<00:28, 55.87it/s]

Gaps (ex-reports):  78%|███████▊  | 5635/7232 [01:35<00:29, 54.03it/s]

Gaps (ex-reports):  78%|███████▊  | 5644/7232 [01:35<00:27, 57.57it/s]

Gaps (ex-reports):  78%|███████▊  | 5650/7232 [01:35<00:29, 54.16it/s]

Gaps (ex-reports):  78%|███████▊  | 5659/7232 [01:35<00:25, 62.86it/s]

Gaps (ex-reports):  78%|███████▊  | 5666/7232 [01:36<00:26, 58.27it/s]

Gaps (ex-reports):  78%|███████▊  | 5673/7232 [01:36<00:26, 59.69it/s]

Gaps (ex-reports):  79%|███████▊  | 5680/7232 [01:36<00:27, 57.44it/s]

Gaps (ex-reports):  79%|███████▊  | 5688/7232 [01:36<00:25, 61.23it/s]

Gaps (ex-reports):  79%|███████▉  | 5697/7232 [01:36<00:22, 68.54it/s]

Gaps (ex-reports):  79%|███████▉  | 5705/7232 [01:36<00:24, 61.37it/s]

Gaps (ex-reports):  79%|███████▉  | 5715/7232 [01:36<00:22, 67.42it/s]

Gaps (ex-reports):  79%|███████▉  | 5725/7232 [01:36<00:20, 74.61it/s]

Gaps (ex-reports):  79%|███████▉  | 5733/7232 [01:37<00:22, 67.77it/s]

Gaps (ex-reports):  79%|███████▉  | 5742/7232 [01:37<00:20, 71.96it/s]

Gaps (ex-reports):  80%|███████▉  | 5750/7232 [01:37<00:20, 71.75it/s]

Gaps (ex-reports):  80%|███████▉  | 5758/7232 [01:37<00:20, 71.26it/s]

Gaps (ex-reports):  80%|███████▉  | 5766/7232 [01:37<00:23, 62.33it/s]

Gaps (ex-reports):  80%|███████▉  | 5777/7232 [01:37<00:20, 69.33it/s]

Gaps (ex-reports):  80%|███████▉  | 5785/7232 [01:37<00:20, 69.07it/s]

Gaps (ex-reports):  80%|████████  | 5793/7232 [01:38<00:23, 60.58it/s]

Gaps (ex-reports):  80%|████████  | 5802/7232 [01:38<00:22, 64.60it/s]

Gaps (ex-reports):  80%|████████  | 5809/7232 [01:38<00:22, 62.42it/s]

Gaps (ex-reports):  80%|████████  | 5816/7232 [01:38<00:23, 59.81it/s]

Gaps (ex-reports):  81%|████████  | 5823/7232 [01:38<00:26, 53.08it/s]

Gaps (ex-reports):  81%|████████  | 5835/7232 [01:38<00:20, 66.87it/s]

Gaps (ex-reports):  81%|████████  | 5843/7232 [01:38<00:24, 56.33it/s]

Gaps (ex-reports):  81%|████████  | 5853/7232 [01:39<00:23, 59.20it/s]

Gaps (ex-reports):  81%|████████  | 5860/7232 [01:39<00:23, 57.49it/s]

Gaps (ex-reports):  81%|████████  | 5869/7232 [01:39<00:22, 60.02it/s]

Gaps (ex-reports):  81%|████████▏ | 5876/7232 [01:39<00:35, 38.42it/s]

Gaps (ex-reports):  81%|████████▏ | 5881/7232 [01:39<00:37, 35.87it/s]

Gaps (ex-reports):  81%|████████▏ | 5894/7232 [01:40<00:29, 44.71it/s]

Gaps (ex-reports):  82%|████████▏ | 5907/7232 [01:40<00:22, 58.95it/s]

Gaps (ex-reports):  82%|████████▏ | 5915/7232 [01:40<00:22, 57.69it/s]

Gaps (ex-reports):  82%|████████▏ | 5923/7232 [01:40<00:21, 61.32it/s]

Gaps (ex-reports):  82%|████████▏ | 5930/7232 [01:40<00:23, 56.50it/s]

Gaps (ex-reports):  82%|████████▏ | 5939/7232 [01:40<00:22, 57.01it/s]

Gaps (ex-reports):  82%|████████▏ | 5946/7232 [01:40<00:21, 59.18it/s]

Gaps (ex-reports):  82%|████████▏ | 5954/7232 [01:40<00:21, 58.57it/s]

Gaps (ex-reports):  82%|████████▏ | 5961/7232 [01:41<00:22, 56.52it/s]

Gaps (ex-reports):  83%|████████▎ | 5969/7232 [01:41<00:21, 58.57it/s]

Gaps (ex-reports):  83%|████████▎ | 5975/7232 [01:41<00:21, 57.67it/s]

Gaps (ex-reports):  83%|████████▎ | 5984/7232 [01:41<00:21, 59.01it/s]

Gaps (ex-reports):  83%|████████▎ | 5992/7232 [01:41<00:21, 58.99it/s]

Gaps (ex-reports):  83%|████████▎ | 5999/7232 [01:41<00:20, 61.14it/s]

Gaps (ex-reports):  83%|████████▎ | 6006/7232 [01:41<00:19, 62.08it/s]

Gaps (ex-reports):  83%|████████▎ | 6014/7232 [01:41<00:18, 66.06it/s]

Gaps (ex-reports):  83%|████████▎ | 6021/7232 [01:42<00:22, 54.95it/s]

Gaps (ex-reports):  83%|████████▎ | 6031/7232 [01:42<00:20, 57.35it/s]

Gaps (ex-reports):  83%|████████▎ | 6038/7232 [01:42<00:19, 59.79it/s]

Gaps (ex-reports):  84%|████████▎ | 6046/7232 [01:42<00:20, 59.05it/s]

Gaps (ex-reports):  84%|████████▍ | 6058/7232 [01:42<00:17, 68.30it/s]

Gaps (ex-reports):  84%|████████▍ | 6065/7232 [01:42<00:20, 58.02it/s]

Gaps (ex-reports):  84%|████████▍ | 6075/7232 [01:42<00:17, 67.37it/s]

Gaps (ex-reports):  84%|████████▍ | 6083/7232 [01:43<00:19, 60.32it/s]

Gaps (ex-reports):  84%|████████▍ | 6094/7232 [01:43<00:17, 66.68it/s]

Gaps (ex-reports):  84%|████████▍ | 6102/7232 [01:43<00:16, 69.35it/s]

Gaps (ex-reports):  84%|████████▍ | 6110/7232 [01:43<00:17, 63.02it/s]

Gaps (ex-reports):  85%|████████▍ | 6122/7232 [01:43<00:14, 76.24it/s]

Gaps (ex-reports):  85%|████████▍ | 6131/7232 [01:43<00:19, 56.38it/s]

Gaps (ex-reports):  85%|████████▍ | 6139/7232 [01:43<00:19, 57.35it/s]

Gaps (ex-reports):  85%|████████▍ | 6147/7232 [01:44<00:17, 61.44it/s]

Gaps (ex-reports):  85%|████████▌ | 6154/7232 [01:44<00:17, 60.91it/s]

Gaps (ex-reports):  85%|████████▌ | 6163/7232 [01:44<00:16, 65.23it/s]

Gaps (ex-reports):  85%|████████▌ | 6170/7232 [01:44<00:17, 60.68it/s]

Gaps (ex-reports):  85%|████████▌ | 6178/7232 [01:44<00:16, 63.99it/s]

Gaps (ex-reports):  86%|████████▌ | 6185/7232 [01:45<00:32, 32.27it/s]

Gaps (ex-reports):  86%|████████▌ | 6191/7232 [01:45<00:29, 35.76it/s]

Gaps (ex-reports):  86%|████████▌ | 6197/7232 [01:45<00:29, 35.15it/s]

Gaps (ex-reports):  86%|████████▌ | 6207/7232 [01:45<00:22, 45.59it/s]

Gaps (ex-reports):  86%|████████▌ | 6213/7232 [01:45<00:23, 44.05it/s]

Gaps (ex-reports):  86%|████████▌ | 6219/7232 [01:45<00:23, 42.64it/s]

Gaps (ex-reports):  86%|████████▌ | 6232/7232 [01:45<00:16, 59.67it/s]

Gaps (ex-reports):  86%|████████▋ | 6239/7232 [01:46<00:17, 55.38it/s]

Gaps (ex-reports):  86%|████████▋ | 6249/7232 [01:46<00:17, 56.46it/s]

Gaps (ex-reports):  87%|████████▋ | 6260/7232 [01:46<00:14, 67.92it/s]

Gaps (ex-reports):  87%|████████▋ | 6268/7232 [01:46<00:14, 64.65it/s]

Gaps (ex-reports):  87%|████████▋ | 6279/7232 [01:46<00:12, 75.18it/s]

Gaps (ex-reports):  87%|████████▋ | 6288/7232 [01:46<00:14, 66.35it/s]

Gaps (ex-reports):  87%|████████▋ | 6296/7232 [01:46<00:14, 64.33it/s]

Gaps (ex-reports):  87%|████████▋ | 6309/7232 [01:46<00:11, 77.45it/s]

Gaps (ex-reports):  87%|████████▋ | 6318/7232 [01:47<00:13, 66.88it/s]

Gaps (ex-reports):  88%|████████▊ | 6328/7232 [01:47<00:13, 67.04it/s]

Gaps (ex-reports):  88%|████████▊ | 6336/7232 [01:47<00:14, 63.81it/s]

Gaps (ex-reports):  88%|████████▊ | 6344/7232 [01:47<00:14, 60.50it/s]

Gaps (ex-reports):  88%|████████▊ | 6351/7232 [01:47<00:14, 61.55it/s]

Gaps (ex-reports):  88%|████████▊ | 6360/7232 [01:47<00:12, 67.58it/s]

Gaps (ex-reports):  88%|████████▊ | 6367/7232 [01:47<00:13, 63.23it/s]

Gaps (ex-reports):  88%|████████▊ | 6374/7232 [01:48<00:13, 63.39it/s]

Gaps (ex-reports):  88%|████████▊ | 6383/7232 [01:48<00:12, 68.94it/s]

Gaps (ex-reports):  88%|████████▊ | 6391/7232 [01:48<00:12, 66.67it/s]

Gaps (ex-reports):  89%|████████▊ | 6401/7232 [01:48<00:12, 66.56it/s]

Gaps (ex-reports):  89%|████████▊ | 6413/7232 [01:48<00:10, 75.14it/s]

Gaps (ex-reports):  89%|████████▉ | 6421/7232 [01:48<00:11, 71.38it/s]

Gaps (ex-reports):  89%|████████▉ | 6433/7232 [01:48<00:10, 78.26it/s]

Gaps (ex-reports):  89%|████████▉ | 6441/7232 [01:48<00:11, 69.94it/s]

Gaps (ex-reports):  89%|████████▉ | 6451/7232 [01:49<00:11, 69.81it/s]

Gaps (ex-reports):  89%|████████▉ | 6464/7232 [01:49<00:09, 83.22it/s]

Gaps (ex-reports):  90%|████████▉ | 6473/7232 [01:49<00:09, 77.48it/s]

Gaps (ex-reports):  90%|████████▉ | 6482/7232 [01:49<00:09, 78.50it/s]

Gaps (ex-reports):  90%|████████▉ | 6491/7232 [01:49<00:10, 67.49it/s]

Gaps (ex-reports):  90%|████████▉ | 6503/7232 [01:49<00:09, 78.86it/s]

Gaps (ex-reports):  90%|█████████ | 6512/7232 [01:49<00:09, 73.30it/s]

Gaps (ex-reports):  90%|█████████ | 6520/7232 [01:50<00:14, 47.97it/s]

Gaps (ex-reports):  90%|█████████ | 6527/7232 [01:50<00:15, 45.44it/s]

Gaps (ex-reports):  90%|█████████ | 6535/7232 [01:50<00:15, 44.80it/s]

Gaps (ex-reports):  91%|█████████ | 6546/7232 [01:50<00:12, 55.30it/s]

Gaps (ex-reports):  91%|█████████ | 6553/7232 [01:50<00:13, 49.99it/s]

Gaps (ex-reports):  91%|█████████ | 6561/7232 [01:51<00:13, 48.17it/s]

Gaps (ex-reports):  91%|█████████ | 6567/7232 [01:51<00:13, 48.29it/s]

Gaps (ex-reports):  91%|█████████ | 6577/7232 [01:51<00:11, 55.42it/s]

Gaps (ex-reports):  91%|█████████ | 6588/7232 [01:51<00:09, 64.99it/s]

Gaps (ex-reports):  91%|█████████ | 6595/7232 [01:51<00:10, 59.57it/s]

Gaps (ex-reports):  91%|█████████▏| 6604/7232 [01:51<00:09, 65.98it/s]

Gaps (ex-reports):  91%|█████████▏| 6611/7232 [01:51<00:09, 66.20it/s]

Gaps (ex-reports):  92%|█████████▏| 6623/7232 [01:51<00:07, 79.55it/s]

Gaps (ex-reports):  92%|█████████▏| 6632/7232 [01:52<00:07, 76.82it/s]

Gaps (ex-reports):  92%|█████████▏| 6640/7232 [01:52<00:07, 74.83it/s]

Gaps (ex-reports):  92%|█████████▏| 6648/7232 [01:52<00:08, 65.76it/s]

Gaps (ex-reports):  92%|█████████▏| 6657/7232 [01:52<00:08, 71.48it/s]

Gaps (ex-reports):  92%|█████████▏| 6665/7232 [01:52<00:09, 60.83it/s]

Gaps (ex-reports):  92%|█████████▏| 6674/7232 [01:52<00:09, 61.23it/s]

Gaps (ex-reports):  92%|█████████▏| 6681/7232 [01:52<00:09, 56.64it/s]

Gaps (ex-reports):  93%|█████████▎| 6691/7232 [01:52<00:08, 64.48it/s]

Gaps (ex-reports):  93%|█████████▎| 6698/7232 [01:53<00:09, 55.74it/s]

Gaps (ex-reports):  93%|█████████▎| 6710/7232 [01:53<00:07, 65.63it/s]

Gaps (ex-reports):  93%|█████████▎| 6717/7232 [01:53<00:08, 60.53it/s]

Gaps (ex-reports):  93%|█████████▎| 6727/7232 [01:53<00:08, 62.28it/s]

Gaps (ex-reports):  93%|█████████▎| 6734/7232 [01:53<00:08, 59.42it/s]

Gaps (ex-reports):  93%|█████████▎| 6743/7232 [01:53<00:07, 64.25it/s]

Gaps (ex-reports):  93%|█████████▎| 6750/7232 [01:54<00:08, 55.98it/s]

Gaps (ex-reports):  94%|█████████▎| 6763/7232 [01:54<00:06, 71.42it/s]

Gaps (ex-reports):  94%|█████████▎| 6771/7232 [01:54<00:07, 62.41it/s]

Gaps (ex-reports):  94%|█████████▍| 6780/7232 [01:54<00:07, 62.80it/s]

Gaps (ex-reports):  94%|█████████▍| 6787/7232 [01:54<00:08, 54.53it/s]

Gaps (ex-reports):  94%|█████████▍| 6799/7232 [01:54<00:07, 61.45it/s]

Gaps (ex-reports):  94%|█████████▍| 6813/7232 [01:54<00:05, 71.16it/s]

Gaps (ex-reports):  94%|█████████▍| 6821/7232 [01:55<00:05, 71.79it/s]

Gaps (ex-reports):  94%|█████████▍| 6830/7232 [01:55<00:05, 68.57it/s]

Gaps (ex-reports):  95%|█████████▍| 6840/7232 [01:55<00:05, 75.65it/s]

Gaps (ex-reports):  95%|█████████▍| 6848/7232 [01:55<00:05, 73.54it/s]

Gaps (ex-reports):  95%|█████████▍| 6856/7232 [01:55<00:09, 38.24it/s]

Gaps (ex-reports):  95%|█████████▍| 6862/7232 [01:55<00:08, 41.57it/s]

Gaps (ex-reports):  95%|█████████▍| 6868/7232 [01:56<00:08, 42.62it/s]

Gaps (ex-reports):  95%|█████████▌| 6874/7232 [01:56<00:08, 40.35it/s]

Gaps (ex-reports):  95%|█████████▌| 6881/7232 [01:56<00:07, 44.23it/s]

Gaps (ex-reports):  95%|█████████▌| 6887/7232 [01:56<00:08, 41.56it/s]

Gaps (ex-reports):  95%|█████████▌| 6898/7232 [01:56<00:06, 53.48it/s]

Gaps (ex-reports):  95%|█████████▌| 6904/7232 [01:56<00:06, 54.28it/s]

Gaps (ex-reports):  96%|█████████▌| 6914/7232 [01:56<00:04, 64.05it/s]

Gaps (ex-reports):  96%|█████████▌| 6922/7232 [01:57<00:04, 63.42it/s]

Gaps (ex-reports):  96%|█████████▌| 6929/7232 [01:57<00:04, 64.30it/s]

Gaps (ex-reports):  96%|█████████▌| 6939/7232 [01:57<00:04, 65.64it/s]

Gaps (ex-reports):  96%|█████████▌| 6948/7232 [01:57<00:04, 64.85it/s]

Gaps (ex-reports):  96%|█████████▌| 6957/7232 [01:57<00:04, 68.10it/s]

Gaps (ex-reports):  96%|█████████▋| 6967/7232 [01:57<00:03, 72.24it/s]

Gaps (ex-reports):  96%|█████████▋| 6977/7232 [01:57<00:03, 75.42it/s]

Gaps (ex-reports):  97%|█████████▋| 6985/7232 [01:57<00:03, 70.67it/s]

Gaps (ex-reports):  97%|█████████▋| 6994/7232 [01:58<00:03, 68.27it/s]

Gaps (ex-reports):  97%|█████████▋| 7002/7232 [01:58<00:03, 69.47it/s]

Gaps (ex-reports):  97%|█████████▋| 7010/7232 [01:58<00:03, 70.90it/s]

Gaps (ex-reports):  97%|█████████▋| 7018/7232 [01:58<00:03, 70.01it/s]

Gaps (ex-reports):  97%|█████████▋| 7026/7232 [01:58<00:02, 70.35it/s]

Gaps (ex-reports):  97%|█████████▋| 7034/7232 [01:58<00:03, 54.97it/s]

Gaps (ex-reports):  97%|█████████▋| 7041/7232 [01:58<00:03, 55.17it/s]

Gaps (ex-reports):  97%|█████████▋| 7047/7232 [01:59<00:04, 43.02it/s]

Gaps (ex-reports):  98%|█████████▊| 7063/7232 [01:59<00:02, 56.40it/s]

Gaps (ex-reports):  98%|█████████▊| 7069/7232 [01:59<00:02, 54.35it/s]

Gaps (ex-reports):  98%|█████████▊| 7079/7232 [01:59<00:02, 58.37it/s]

Gaps (ex-reports):  98%|█████████▊| 7085/7232 [01:59<00:03, 45.91it/s]

Gaps (ex-reports):  98%|█████████▊| 7097/7232 [01:59<00:02, 57.95it/s]

Gaps (ex-reports):  98%|█████████▊| 7104/7232 [02:00<00:02, 60.34it/s]

Gaps (ex-reports):  98%|█████████▊| 7113/7232 [02:00<00:01, 63.83it/s]

Gaps (ex-reports):  98%|█████████▊| 7120/7232 [02:00<00:01, 61.90it/s]

Gaps (ex-reports):  99%|█████████▊| 7130/7232 [02:00<00:01, 66.80it/s]

Gaps (ex-reports):  99%|█████████▊| 7139/7232 [02:00<00:01, 69.70it/s]

Gaps (ex-reports):  99%|█████████▉| 7148/7232 [02:00<00:01, 68.35it/s]

Gaps (ex-reports):  99%|█████████▉| 7160/7232 [02:00<00:00, 78.99it/s]

Gaps (ex-reports):  99%|█████████▉| 7169/7232 [02:01<00:01, 39.50it/s]

Gaps (ex-reports):  99%|█████████▉| 7176/7232 [02:01<00:01, 43.94it/s]

Gaps (ex-reports):  99%|█████████▉| 7183/7232 [02:01<00:01, 46.13it/s]

Gaps (ex-reports):  99%|█████████▉| 7192/7232 [02:01<00:00, 51.54it/s]

Gaps (ex-reports): 100%|█████████▉| 7199/7232 [02:01<00:00, 51.88it/s]

Gaps (ex-reports): 100%|█████████▉| 7206/7232 [02:01<00:00, 52.85it/s]

Gaps (ex-reports): 100%|█████████▉| 7214/7232 [02:01<00:00, 58.02it/s]

Gaps (ex-reports): 100%|█████████▉| 7222/7232 [02:02<00:00, 62.19it/s]

Gaps (ex-reports): 100%|█████████▉| 7229/7232 [02:02<00:00, 63.52it/s]

Gaps (ex-reports): 100%|██████████| 7232/7232 [02:02<00:00, 59.18it/s]

Rows in gaps (without report days): 298292

Tickers with sigma: 7045

  ticker     sigma
0      A  0.848391
1     AA  2.153685
2   AAAU  1.269111
3   AACG  2.683325
4    AAL  1.880970

In [43]:
std_by_ticker

     ticker     sigma
0         A  0.848391
1        AA  2.153685
2      AAAU  1.269111
3      AACG  2.683325
4       AAL  1.880970
...     ...       ...
7040   ZVOL  0.775055
7041   ZVRA  0.966714
7042    ZWS  0.967341
7043   ZYBT  3.491555
7044   ZYME  0.817743

[7045 rows x 2 columns]

In [44]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    # знайдемо колонки гнучко
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"]  = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker зі скріна
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%" або "pct_vs_prev_close"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet та зберігає новий файл.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    # вихідний шлях
    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    # підготовка мапи sigma
    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)

    # запис у тимчасовий файл → атомарна заміна
    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}")
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(sigma_map, on="ticker", how="left", validate="m:1")

        # розташувати 'sigma' за бажанням
        if insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("sigma")
            idx = cols.index(insert_before)
            cols = cols[:idx] + ["sigma"] + cols[idx:]
            merged = merged[cols]
        else:
            base_cols = [c for c in merged.columns if c != "sigma"]
            merged = merged[base_cols + ["sigma"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # атомарна заміна
    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [45]:
# std_by_ticker columns: ['ticker', 'sigma']
sigma_out_path = add_sigma_by_ticker_to_parquet(
    base_path=str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    sigma_df=std_by_ticker,
    insert_before=None,
)

# Validation: output parquet must contain sigma matching std_by_ticker
check_df = pd.read_parquet(sigma_out_path, columns=["ticker", "sigma"])
if "sigma" not in check_df.columns:
    raise KeyError("Column 'sigma' is missing in parquet after merge")

file_sigma = (
    check_df.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

exp_sigma = (
    std_by_ticker.dropna(subset=["ticker"])
    .assign(ticker=lambda d: d["ticker"].astype(str).str.upper().str.strip())
    .drop_duplicates(subset=["ticker"], keep="last")
    .set_index("ticker")["sigma"]
)

common = file_sigma.index.intersection(exp_sigma.index)
if len(common) == 0:
    raise ValueError("No common tickers to validate sigma between std_by_ticker and parquet")

diff = (file_sigma.loc[common] - exp_sigma.loc[common]).abs()
max_diff = float(diff.max()) if len(diff) else 0.0
print("sigma_out_path:", sigma_out_path)
print("tickers in std_by_ticker:", len(exp_sigma))
print("tickers checked in parquet:", len(common))
print("max |file_sigma - expected_sigma|:", max_diff)

▶️ START merge sigma → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000  elapsed=20.9s

[batch   10] rows=20,000,000  elapsed=41.8s

[batch   15] rows=30,000,000  elapsed=62.5s

[batch   20] rows=40,000,000  elapsed=82.8s

[batch   25] rows=50,000,000  elapsed=103.7s

[batch   30] rows=60,000,000  elapsed=123.9s

[batch   35] rows=70,000,000  elapsed=144.3s

[batch   40] rows=78,652,730  elapsed=162.4s
✅ DONE rows=78,652,730 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  in 162.5s

sigma_out_path: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
tickers in std_by_ticker: 7045
tickers checked in parquet: 7039
max |file_sigma - expected_sigma|: 4.999710104813815e-07

In [46]:
peek_parquet(str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"), n=21150)

Файл: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 78,652,730
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 0/21150
NaN у 'corr' (у прев'ю): 8/21150
NaN у 'beta' (у прев'ю): 8/21150

Перші рядки:

      ticker                  dt           o           h           l           c          v        date    open  prev_close  Stack% bench    corr    beta  Bench%     sigma
0          A 2026-04-16 00:00:00  119.129997  119.129997  119.129997  119.129997       10.0  2026-04-16  121.12      119.77   -0.53   IWM  0.5962  0.6161    0.08  0.848391
1          A 2026-04-16 01:37:00  119.440002  119.440002  119.440002  119.440002        5.0  2026-04-16  121.12      119.77   -0.28   IWM  0.5962  0.6161    0.11  0.848391
2          A 2026-04-16 01:54:00  119.349998  119.349998  119.349998  119.349998        5.0  2026-04-16  121.12      119.77   -0.35   IWM  0.5962  0.6161    0.09  0.848391
3          A 2026-04-16 02:00:00  119.349998  119.349998  119.349998  119.349998        5.0  2026-04-16  121.12      119.77   -0.35   IWM  0.5962  0.6161    0.14  0.848391
4          A 2026-04-16 02:04:00  119.410004  119.410004  119.410004  119.410004       10.0  2026-04-16  121.12      119.77   -0.30   IWM  0.5962  0.6161    0.17  0.848391
5          A 2026-04-16 03:05:00  119.540001  119.540001  119.540001  119.540001        5.0  2026-04-16  121.12      119.77   -0.19   IWM  0.5962  0.6161    0.11  0.848391
6          A 2026-04-16 03:06:00  119.599998  119.599998  119.599998  119.599998        5.0  2026-04-16  121.12      119.77   -0.14   IWM  0.5962  0.6161    0.09  0.848391
7          A 2026-04-16 09:30:00  121.120003  121.120003  119.040001  119.364998    18444.0  2026-04-16  121.12      119.77    1.13   IWM  0.5962  0.6161    0.01  0.848391
8          A 2026-04-16 09:31:00  119.099998  119.099998  119.080002  119.080002      703.0  2026-04-16  121.12      119.77   -0.56   IWM  0.5962  0.6161    0.12  0.848391
9          A 2026-04-16 09:32:00  119.080002  119.625000  119.080002  119.625000      400.0  2026-04-16  121.12      119.77   -0.58   IWM  0.5962  0.6161    0.16  0.848391
10         A 2026-04-16 09:33:00  119.889999  119.889999  119.080002  119.080002     1800.0  2026-04-16  121.12      119.77    0.10   IWM  0.5962  0.6161    0.10  0.848391
11         A 2026-04-16 09:34:00  119.389999  119.389999  118.750000  119.175003     4718.0  2026-04-16  121.12      119.77   -0.32   IWM  0.5962  0.6161    0.19  0.848391
12         A 2026-04-16 09:35:00  118.290001  119.074997  118.290001  118.525002     1700.0  2026-04-16  121.12      119.77   -1.24   IWM  0.5962  0.6161    0.26  0.848391
13         A 2026-04-16 09:36:00  118.567497  118.919998  118.567497  118.635002     1602.0  2026-04-16  121.12      119.77   -1.00   IWM  0.5962  0.6161    0.29  0.848391
14         A 2026-04-16 09:37:00  118.635002  118.635002  118.502502  118.540001     4256.0  2026-04-16  121.12      119.77   -0.95   IWM  0.5962  0.6161    0.19  0.848391
15         A 2026-04-16 09:38:00  118.370003  118.540001  118.370003  118.540001     1049.0  2026-04-16  121.12      119.77   -1.17   IWM  0.5962  0.6161    0.16  0.848391
16         A 2026-04-16 09:39:00  118.709999  118.760002  118.709999  118.760002      500.0  2026-04-16  121.12      119.77   -0.89   IWM  0.5962  0.6161    0.13  0.848391
17         A 2026-04-16 09:40:00  118.910004  118.919998  118.529999  118.529999     2252.0  2026-04-16  121.12      119.77   -0.72   IWM  0.5962  0.6161    0.10  0.848391
18         A 2026-04-16 09:41:00  118.379997  118.379997  118.379997  118.379997      100.0  2026-04-16  121.12      119.77   -1.16   IWM  0.5962  0.6161    0.22  0.848391
19         A 2026-04-16 09:42:00  118.309998  118.419998  118.309998  118.309998     2407.0  2026-04-16  121.12      119.77   -1.22   IWM  0.5962  0.6161    0.06  0.848391
20         A 2026-04-16 09:43:00  118.320000  118.449997  118.290001  118.410004     1911.0  2026-04-16  121.12      119.77   -1.21   IWM  0.5962  0.6161    0.07  0.848391
21         A 2026-04-16 09:44:00  118.415001  118.500000  118.169998  118.285004     5873.0  2026-04-16  121.12      119.77   -1.13   IWM  0.5962  0.6161    0.07  0.848391
22         A 2026-04-16 09:45:00  118.150002  118.180000  118.135002  118.144997     3305.0  2026-04-16  121.12      119.77   -1.35   IWM  0.5962  0.6161    0.09  0.848391
23         A 2026-04-16 09:46:00  118.135002  118.540001  117.980003  118.430000    38765.0  2026-04-16  121.12      119.77   -1.37   IWM  0.5962  0.6161    0.10  0.848391
24         A 2026-04-16 09:47:00  118.425003  118.425003  118.019997  118.019997     3229.0  2026-04-16  121.12      119.77   -1.12   IWM  0.5962  0.6161    0.09  0.848391
25         A 2026-04-16 09:48:00  118.239998  118.239998  117.949997  117.949997     1200.0  2026-04-16  121.12      119.77   -1.28   IWM  0.5962  0.6161   -0.02  0.848391
26         A 2026-04-16 09:49:00  118.165001  118.165001  118.165001  118.165001      600.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161    0.10  0.848391
27         A 2026-04-16 09:50:00  118.114998  118.370003  118.114998  118.224998     7239.0  2026-04-16  121.12      119.77   -1.38   IWM  0.5962  0.6161    0.10  0.848391
28         A 2026-04-16 09:51:00  118.224998  118.639999  118.199997  118.639999     8364.0  2026-04-16  121.12      119.77   -1.29   IWM  0.5962  0.6161    0.07  0.848391
29         A 2026-04-16 09:52:00  118.695000  118.695000  118.550003  118.550003     1473.0  2026-04-16  121.12      119.77   -0.90   IWM  0.5962  0.6161   -0.01  0.848391
30         A 2026-04-16 09:53:00  118.550003  118.550003  118.349998  118.349998     1500.0  2026-04-16  121.12      119.77   -1.02   IWM  0.5962  0.6161   -0.13  0.848391
31         A 2026-04-16 09:54:00  118.339996  118.339996  118.099998  118.099998     2027.0  2026-04-16  121.12      119.77   -1.19   IWM  0.5962  0.6161   -0.23  0.848391
32         A 2026-04-16 09:55:00  117.879997  118.004997  117.879997  117.989998      831.0  2026-04-16  121.12      119.77   -1.58   IWM  0.5962  0.6161   -0.32  0.848391
33         A 2026-04-16 09:56:00  118.000000  118.000000  117.970001  117.970001      300.0  2026-04-16  121.12      119.77   -1.48   IWM  0.5962  0.6161   -0.26  0.848391
34         A 2026-04-16 09:57:00  118.139999  118.160004  118.089996  118.160004     1277.0  2026-04-16  121.12      119.77   -1.36   IWM  0.5962  0.6161   -0.24  0.848391
35         A 2026-04-16 09:58:00  118.175003  118.175003  118.175003  118.175003      300.0  2026-04-16  121.12      119.77   -1.33   IWM  0.5962  0.6161   -0.26  0.848391
36         A 2026-04-16 09:59:00  118.375000  118.375000  118.180000  118.339996     1790.0  2026-04-16  121.12      119.77   -1.16   IWM  0.5962  0.6161   -0.15  0.848391
37         A 2026-04-16 10:00:00  118.190002  118.279999  118.125000  118.125000     1969.0  2026-04-16  121.12      119.77   -1.32   IWM  0.5962  0.6161   -0.09  0.848391
38         A 2026-04-16 10:01:00  118.029999  118.029999  117.625000  117.730003     1900.0  2026-04-16  121.12      119.77   -1.45   IWM  0.5962  0.6161   -0.22  0.848391
39         A 2026-04-16 10:02:00  117.794998  117.970001  117.794998  117.940002      512.0  2026-04-16  121.12      119.77   -1.65   IWM  0.5962  0.6161   -0.22  0.848391
40         A 2026-04-16 10:03:00  118.129997  118.360001  118.110001  118.330002     1843.0  2026-04-16  121.12      119.77   -1.37   IWM  0.5962  0.6161   -0.23  0.848391
41         A 2026-04-16 10:04:00  118.214996  118.214996  118.214996  118.214996      200.0  2026-04-16  121.12      119.77   -1.30   IWM  0.5962  0.6161   -0.23  0.848391
42         A 2026-04-16 10:05:00  118.371002  118.371002  118.214996  118.220001      400.0  2026-04-16  121.12      119.77   -1.17   IWM  0.5962  0.6161   -0.26  0.848391
43         A 2026-04-16 10:06:00  118.199997  118.209999  118.105003  118.105003      600.0  2026-04-16  121.12      119.77   -1.31   IWM  0.5962  0.6161   -0.23  0.848391
44         A 2026-04-16 10:07:00  118.019997  118.019997  118.019997  118.019997      400.0  2026-04-16  121.12      119.77   -1.46   IWM  0.5962  0.6161   -0.25  0.848391
45         A 2026-04-16 10:08:00  118.120003  118.470001  118.120003  118.470001     2636.0  2026-04-16  121.12      119.77   -1.38   IWM  0.5962  0.6161   -0.22  0.848391
46         A 2026-04-16 10:10:00  118.459999  118.550003  118.459999  118.474998     1774.0  2026-04-16  121.12      119.77   -1.09   IWM  0.5962  0.6161   -0.26  0.848391
47         A 2026-04-16 10:11:00  118.510002  118.510002  118.300003  118.440002     1766.0  2026-04-16  121.12      119.77   -1.05   IWM  0.5962  0.6161   -0.23  0.848391
48         A 2026-04-16 10:12:00  118.389999  118.449997  118.375000  118.449997      500.0  2026-04-16  121.12      119.77   -1.15   IWM  0.5962  0.6161   -0.24  0.848391
49         A 2026-04-16 10:13:00  118.379997  118.470001  118.379997  118.470001      600.0  2026-04-16  121.12      119.77   -1.16   IWM  0.5962  0.6161   -0.14  0.848391
50         A 2026-04-16 10:14:00  118.379997  118.470001  118.379997  118.470001      300.0  2026-04-16  121.12      119.77   -1.16   IWM  0.5962  0.6161   -0.18  0.848391
51         A 2026-04-16 10:15:00  118.589996  118.620003  118.589996  118.620003      700.0  2026-04-16  121.12      119.77   -0.99   IWM  0.5962  0.6161   -0.19  0.848391
52         A 2026-04-16 10:16:00  118.589996  118.660004  118.559998  118.660004     1257.0  2026-04-16  121.12      119.77   -0.99   IWM  0.5962  0.6161   -0.19  0.848391
53         A 2026-04-16 10:17:00  118.559998  118.660004  118.559998  118.610001     1363.0  2026-04-16  121.12      119.77   -1.01   IWM  0.5962  0.6161   -0.26  0.848391
54         A 2026-04-16 10:18:00  118.610001  118.720001  118.589996  118.669998      900.0  2026-04-16  121.12      119.77   -0.97   IWM  0.5962  0.6161   -0.29  0.848391
55         A 2026-04-16 10:19:00  118.610001  118.610001  118.610001  118.610001      303.0  2026-04-16  121.12      119.77   -0.97   IWM  0.5962  0.6161   -0.29  0.848391
56         A 2026-04-16 10:20:00  118.599998  118.690002  118.599998  118.614998     2450.0  2026-04-16  121.12      119.77   -0.98   IWM  0.5962  0.6161   -0.38  0.848391
57         A 2026-04-16 10:21:00  118.709999  118.709999  118.580002  118.610001     5041.0  2026-04-16  121.12      119.77   -0.89   IWM  0.5962  0.6161   -0.42  0.848391
58         A 2026-04-16 10:22:00  118.709999  118.709999  118.599998  118.610001     1100.0  2026-04-16  121.12      119.77   -0.89   IWM  0.5962  0.6161   -0.34  0.848391
59         A 2026-04-16 10:23:00  118.584999  118.584999  118.239998  118.489998     5760.0  2026-04-16  121.12      119.77   -0.99   IWM  0.5962  0.6161   -0.39  0.848391
60         A 2026-04-16 10:24:00  118.425003  118.425003  118.360001  118.360001      686.0  2026-04-16  121.12      119.77   -1.12   IWM  0.5962  0.6161   -0.36  0.848391
61         A 2026-04-16 10:25:00  118.360001  118.360001  118.360001  118.360001      100.0  2026-04-16  121.12      119.77   -1.18   IWM  0.5962  0.6161   -0.41  0.848391
62         A 2026-04-16 10:27:00  118.389999  118.389999  118.360001  118.379997      300.0  2026-04-16  121.12      119.77   -1.15   IWM  0.5962  0.6161   -0.42  0.848391
63         A 2026-04-16 10:28:00  118.470001  118.470001  118.470001  118.470001      100.0  2026-04-16  121.12      119.77   -1.09   IWM  0.5962  0.6161   -0.40  0.848391
64         A 2026-04-16 10:29:00  118.410004  118.410004  118.410004  118.410004      100.0  2026-04-16  121.12      119.77   -1.14   IWM  0.5962  0.6161   -0.33  0.848391
65         A 2026-04-16 10:30:00  118.394997  118.459999  118.394997  118.459999      300.0  2026-04-16  121.12      119.77   -1.15   IWM  0.5962  0.6161   -0.36  0.848391
66         A 2026-04-16 10:31:00  118.400002  118.400002  118.260002  118.290001     1205.0  2026-04-16  121.12      119.77   -1.14   IWM  0.5962  0.6161   -0.36  0.848391
67         A 2026-04-16 10:32:00  118.294998  118.294998  118.294998  118.294998      100.0  2026-04-16  121.12      119.77   -1.23   IWM  0.5962  0.6161   -0.47  0.848391
68         A 2026-04-16 10:34:00  118.297501  118.419998  118.297501  118.320000     1148.0  2026-04-16  121.12      119.77   -1.23   IWM  0.5962  0.6161   -0.39  0.848391
69         A 2026-04-16 10:35:00  118.339996  118.339996  118.220001  118.220001      600.0  2026-04-16  121.12      119.77   -1.19   IWM  0.5962  0.6161   -0.35  0.848391
70         A 2026-04-16 10:36:00  118.180000  118.180000  118.169998  118.175003     1350.0  2026-04-16  121.12      119.77   -1.33   IWM  0.5962  0.6161   -0.40  0.848391
71         A 2026-04-16 10:37:00  118.129997  118.150002  118.114998  118.114998     2455.0  2026-04-16  121.12      119.77   -1.37   IWM  0.5962  0.6161   -0.42  0.848391
72         A 2026-04-16 10:38:00  118.070000  118.070000  118.050003  118.050003     1400.0  2026-04-16  121.12      119.77   -1.42   IWM  0.5962  0.6161   -0.41  0.848391
73         A 2026-04-16 10:39:00  117.974998  117.974998  117.974998  117.974998      260.0  2026-04-16  121.12      119.77   -1.50   IWM  0.5962  0.6161   -0.41  0.848391
74         A 2026-04-16 10:40:00  117.970001  117.970001  117.739998  117.849998     1600.0  2026-04-16  121.12      119.77   -1.50   IWM  0.5962  0.6161   -0.44  0.848391
75         A 2026-04-16 10:41:00  117.970001  117.970001  117.919998  117.919998      246.0  2026-04-16  121.12      119.77   -1.50   IWM  0.5962  0.6161   -0.45  0.848391
76         A 2026-04-16 10:42:00  118.120003  118.120003  118.120003  118.120003      200.0  2026-04-16  121.12      119.77   -1.38   IWM  0.5962  0.6161   -0.45  0.848391
77         A 2026-04-16 10:43:00  118.089996  118.114998  118.089996  118.114998      367.0  2026-04-16  121.12      119.77   -1.40   IWM  0.5962  0.6161   -0.43  0.848391
78         A 2026-04-16 10:44:00  118.120003  118.239998  118.120003  118.239998      200.0  2026-04-16  121.12      119.77   -1.38   IWM  0.5962  0.6161   -0.40  0.848391
79         A 2026-04-16 10:46:00  118.169998  118.169998  118.169998  118.169998      100.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161   -0.22  0.848391
80         A 2026-04-16 10:48:00  118.169998  118.169998  118.169998  118.169998      100.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161   -0.26  0.848391
81         A 2026-04-16 10:49:00  118.160004  118.160004  118.160004  118.160004      100.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161   -0.25  0.848391
82         A 2026-04-16 10:50:00  118.139999  118.330002  118.110001  118.330002     1564.0  2026-04-16  121.12      119.77   -1.36   IWM  0.5962  0.6161   -0.20  0.848391
83         A 2026-04-16 10:51:00  118.279999  118.279999  118.279999  118.279999      300.0  2026-04-16  121.12      119.77   -1.24   IWM  0.5962  0.6161   -0.16  0.848391
84         A 2026-04-16 10:52:00  118.169998  118.180000  118.089996  118.089996      905.0  2026-04-16  121.12      119.77   -1.34   IWM  0.5962  0.6161   -0.10  0.848391
85         A 2026-04-16 10:54:00  118.089996  118.089996  118.084999  118.084999      200.0  2026-04-16  121.12      119.77   -1.40   IWM  0.5962  0.6161   -0.15  0.848391
86         A 2026-04-16 10:55:00  118.086502  118.086502  118.029999  118.029999      225.0  2026-04-16  121.12      119.77   -1.41   IWM  0.5962  0.6161   -0.12  0.848391
87         A 2026-04-16 10:56:00  117.959999  118.010002  117.949997  117.959999     1705.0  2026-04-16  121.12      119.77   -1.51   IWM  0.5962  0.6161   -0.18  0.848391
88         A 2026-04-16 10:57:00  117.849998  117.849998  117.614998  117.620003     2057.0  2026-04-16  121.12      119.77   -1.60   IWM  0.5962  0.6161   -0.19  0.848391
89         A 2026-04-16 10:58:00  117.650002  117.989998  117.650002  117.989998     1600.0  2026-04-16  121.12      119.77   -1.77   IWM  0.5962  0.6161   -0.21  0.848391
90         A 2026-04-16 10:59:00  117.980003  117.980003  117.980003  117.980003      100.0  2026-04-16  121.12      119.77   -1.49   IWM  0.5962  0.6161   -0.19  0.848391
91         A 2026-04-16 11:00:00  117.980003  117.980003  117.980003  117.980003      300.0  2026-04-16  121.12      119.77   -1.49   IWM  0.5962  0.6161   -0.18  0.848391
92         A 2026-04-16 11:01:00  118.010002  118.040001  117.995003  117.995003     1505.0  2026-04-16  121.12      119.77   -1.47   IWM  0.5962  0.6161   -0.12  0.848391
93         A 2026-04-16 11:02:00  118.050003  118.050003  117.995003  117.995003      200.0  2026-04-16  121.12      119.77   -1.44   IWM  0.5962  0.6161   -0.16  0.848391
94         A 2026-04-16 11:03:00  117.989998  117.989998  117.989998  117.989998      100.0  2026-04-16  121.12      119.77   -1.49   IWM  0.5962  0.6161   -0.10  0.848391
95         A 2026-04-16 11:04:00  117.900002  118.250000  117.879997  118.250000     3359.0  2026-04-16  121.12      119.77   -1.56   IWM  0.5962  0.6161   -0.08  0.848391
96         A 2026-04-16 11:05:00  118.279999  118.349998  118.199997  118.269997    17862.0  2026-04-16  121.12      119.77   -1.24   IWM  0.5962  0.6161   -0.07  0.848391
97         A 2026-04-16 11:06:00  118.254997  118.254997  118.230003  118.230003      200.0  2026-04-16  121.12      119.77   -1.26   IWM  0.5962  0.6161   -0.03  0.848391
98         A 2026-04-16 11:07:00  118.250000  118.315002  118.180000  118.220001     4809.0  2026-04-16  121.12      119.77   -1.27   IWM  0.5962  0.6161   -0.06  0.848391
99         A 2026-04-16 11:08:00  118.220001  118.220001  118.099998  118.099998     4205.0  2026-04-16  121.12      119.77   -1.29   IWM  0.5962  0.6161   -0.03  0.848391
100        A 2026-04-16 11:09:00  118.220001  118.279999  118.220001  118.279999      300.0  2026-04-16  121.12      119.77   -1.29   IWM  0.5962  0.6161    0.00  0.848391
101        A 2026-04-16 11:10:00  118.360001  118.459999  118.360001  118.459999      852.0  2026-04-16  121.12      119.77   -1.18   IWM  0.5962  0.6161    0.05  0.848391
102        A 2026-04-16 11:11:00  118.464996  118.464996  118.440002  118.440002      841.0  2026-04-16  121.12      119.77   -1.09   IWM  0.5962  0.6161    0.12  0.848391
103        A 2026-04-16 11:12:00  118.440002  118.440002  118.440002  118.440002      300.0  2026-04-16  121.12      119.77   -1.11   IWM  0.5962  0.6161    0.11  0.848391
104        A 2026-04-16 11:13:00  118.584999  118.605003  118.584999  118.605003      300.0  2026-04-16  121.12      119.77   -0.99   IWM  0.5962  0.6161    0.08  0.848391
105        A 2026-04-16 11:14:00  118.660004  118.675003  118.550102  118.550102      706.0  2026-04-16  121.12      119.77   -0.93   IWM  0.5962  0.6161    0.09  0.848391
106        A 2026-04-16 11:15:00  118.599998  118.925003  118.599998  118.820000     2911.0  2026-04-16  121.12      119.77   -0.98   IWM  0.5962  0.6161    0.09  0.848391
107        A 2026-04-16 11:16:00  118.790001  118.790001  118.770149  118.790001      534.0  2026-04-16  121.12      119.77   -0.82   IWM  0.5962  0.6161    0.14  0.848391
108        A 2026-04-16 11:17:00  118.790001  118.889999  118.790001  118.889999     1398.0  2026-04-16  121.12      119.77   -0.82   IWM  0.5962  0.6161    0.21  0.848391
109        A 2026-04-16 11:18:00  118.849998  118.849998  118.815002  118.815002     1300.0  2026-04-16  121.12      119.77   -0.77   IWM  0.5962  0.6161    0.21  0.848391
110        A 2026-04-16 11:19:00  118.815002  118.940002  118.709999  118.900002     3074.0  2026-04-16  121.12      119.77   -0.80   IWM  0.5962  0.6161    0.19  0.848391
111        A 2026-04-16 11:20:00  118.845001  119.129997  118.845001  119.089996     9452.0  2026-04-16  121.12      119.77   -0.77   IWM  0.5962  0.6161    0.14  0.848391
112        A 2026-04-16 11:21:00  119.059998  119.059998  118.930000  118.959999     4245.0  2026-04-16  121.12      119.77   -0.59   IWM  0.5962  0.6161    0.19  0.848391
113        A 2026-04-16 11:22:00  118.980003  118.989998  118.974998  118.980003     1001.0  2026-04-16  121.12      119.77   -0.66   IWM  0.5962  0.6161    0.23  0.848391
114        A 2026-04-16 11:23:00  118.980003  118.980003  118.900002  118.919998     2215.0  2026-04-16  121.12      119.77   -0.66   IWM  0.5962  0.6161    0.23  0.848391

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,A,2026-04-16 00:00:00,119.129997,119.129997,119.129997,119.129997,10.0,2026-04-16,121.12,119.77,-0.53,IWM,0.5962,0.6161,0.08,0.848391
1,A,2026-04-16 01:37:00,119.440002,119.440002,119.440002,119.440002,5.0,2026-04-16,121.12,119.77,-0.28,IWM,0.5962,0.6161,0.11,0.848391
2,A,2026-04-16 01:54:00,119.349998,119.349998,119.349998,119.349998,5.0,2026-04-16,121.12,119.77,-0.35,IWM,0.5962,0.6161,0.09,0.848391
3,A,2026-04-16 02:00:00,119.349998,119.349998,119.349998,119.349998,5.0,2026-04-16,121.12,119.77,-0.35,IWM,0.5962,0.6161,0.14,0.848391
4,A,2026-04-16 02:04:00,119.410004,119.410004,119.410004,119.410004,10.0,2026-04-16,121.12,119.77,-0.30,IWM,0.5962,0.6161,0.17,0.848391
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,ABM,2026-04-17 12:25:00,40.759998,40.770000,40.759998,40.770000,687.0,2026-04-17,39.96,39.48,3.24,XLI,0.3296,0.2925,2.54,0.553937
21146,ABM,2026-04-17 12:31:00,40.709999,40.740002,40.709999,40.740002,600.0,2026-04-17,39.96,39.48,3.12,XLI,0.3296,0.2925,2.55,0.553937
21147,ABM,2026-04-17 12:36:00,40.755001,40.755001,40.755001,40.755001,100.0,2026-04-17,39.96,39.48,3.23,XLI,0.3296,0.2925,2.62,0.553937
21148,ABM,2026-04-17 12:37:00,40.755001,40.755001,40.755001,40.755001,200.0,2026-04-17,39.96,39.48,3.23,XLI,0.3296,0.2925,2.65,0.553937
21149,ABM,2026-04-17 12:39:00,40.740002,40.740002,40.689999,40.689999,1200.0,2026-04-17,39.96,39.48,3.19,XLI,0.3296,0.2925,2.67,0.553937

In [47]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
except Exception:
    pa = pq = ds = None


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    roundtrip_pandas: bool = True,   # найнадійніше для sort_values
    log_every: int = 200,
):
    """
    Rewrites input parquet into output parquet in strict physical order:
      ticker A→Z, then (date, dt) within each ticker (or dt only).
    Uses dataset scanning per ticker to avoid global in-memory sort.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")

    # Discover columns
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    has_date = ("date" in schema_names)
    has_dt   = ("dt" in schema_names)

    # get unique tickers (safe, but could be heavy; acceptable for your use-case)
    tickers_tbl = dataset.to_table(columns=["ticker"])
    tickers = sorted(pd.unique(tickers_tbl.column("ticker").to_pandas().astype(str)))
    del tickers_tbl
    gc.collect()

    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    writer = None
    total_written = 0
    t0 = time.time()

    print(f"▶ SORT: {input_path} → {output_path} | tickers={len(tickers):,} | has_date={has_date} has_dt={has_dt}")

    try:
        for i, tk in enumerate(tickers, 1):
            # Filter rows for this ticker
            filt = (ds.field("ticker") == tk)
            table = dataset.to_table(filter=filt)
            if table.num_rows == 0:
                continue

            if roundtrip_pandas:
                df = table.to_pandas()
                # Ensure date exists if needed
                if has_date:
                    # keep as-is; assume date is string 'YYYY-MM-DD'
                    pass
                elif has_dt and ("date" not in df.columns):
                    # If no date column exists, optionally derive it (not required for sort)
                    pass

                if has_date and has_dt and {"date", "dt"}.issubset(df.columns):
                    df.sort_values(["date", "dt"], kind="mergesort", inplace=True)
                elif has_dt and "dt" in df.columns:
                    df.sort_values(["dt"], kind="mergesort", inplace=True)
                else:
                    # fallback: stable sort by all columns
                    df.sort_values(list(df.columns), kind="mergesort", inplace=True)

                out_table = pa.Table.from_pandas(df, preserve_index=False)
                del df
            else:
                # Arrow-only fallback (less flexible)
                out_table = table

            if writer is None:
                writer = pq.ParquetWriter(tmp_out, out_table.schema, compression=compression)

            writer.write_table(out_table)
            total_written += out_table.num_rows

            if (i % log_every) == 0:
                print(f"  [{i:>6}/{len(tickers):,}] {tk}  written={total_written:,}  elapsed={time.time()-t0:,.1f}s")

            del table, out_table
            gc.collect()

    finally:
        if writer is not None:
            writer.close()

    # atomic replace
    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)

    print(f"✅ SORT DONE: {total_written:,} rows → {output_path} | time={time.time()-t0:,.1f}s")
    return output_path


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # використовується як batch_rows для Parquet
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,      # NEW: rewrite final sorted
) -> str:
    """
    Parquet-версія.
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.
    Працює потоково.

    NEW:
      - якщо sort_final_by_ticker=True, то фінальний output_path буде фізично
        відсортований: ticker A→Z, всередині тикера date,dt (або dt).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    batch_rows = chunksize

    # 1) write unsorted tmp parquet
    tmp_unsorted = output_path + f".tmp_unsorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_unsorted):
        os.remove(tmp_unsorted)

    pf = pq.ParquetFile(input_path)
    writer = None
    total = 0

    print(f"▶ START (Parquet): {input_path}  →  {output_path} | batch_rows≈{batch_rows:,}")

    for bi, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # гнучке визначення колонок
        names = {c.lower().strip(): c for c in df.columns}
        stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
        bench_col = names.get("bench%")
        beta_col  = names.get("beta")
        sigma_col = names.get("sigma")

        need = {
            "stack%/pct_vs_prev_close": stack_col,
            "bench%": bench_col,
            "beta": beta_col,
            "sigma": sigma_col,
        }
        missing = [k for k, v in need.items() if v is None]
        if missing:
            raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

        # приберемо старі результати, якщо були
        for col in ("t_p", "deviation", "dev_sig"):
            if col in df.columns:
                del df[col]

        # числові типи
        df[stack_col] = pd.to_numeric(df[stack_col], errors="coerce")
        df[bench_col] = pd.to_numeric(df[bench_col], errors="coerce")
        df[beta_col]  = pd.to_numeric(df[beta_col],  errors="coerce")
        df[sigma_col] = pd.to_numeric(df[sigma_col], errors="coerce")

        # обчислення
        tp  = df[stack_col] * df[beta_col]
        dev = tp - df[bench_col]
        denom = df[sigma_col].replace({0: np.nan})
        dsg = dev / denom

        # округлення
        if round_tp_dev is not None:
            tp  = tp.round(round_tp_dev)
            dev = dev.round(round_tp_dev)
        if round_devsig is not None:
            dsg = dsg.round(round_devsig)

        # додати в кінець
        df["t_p"] = tp
        df["deviation"] = dev
        df["dev_sig"] = dsg

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_unsorted, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if bi % 5 == 0:
            print(f"[batch {bi:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # 2) sort & finalize
    if sort_final_by_ticker:
        # rewrite sorted to output_path
        _write_final_sorted_alphabetical(
            tmp_unsorted,
            output_path,
            compression=compression,
            roundtrip_pandas=True,
            log_every=200,
        )
        # cleanup unsorted tmp
        try:
            os.remove(tmp_unsorted)
        except Exception:
            pass
    else:
        # atomic replace unsorted as final
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_unsorted, output_path)

    print(f"✅ DONE: {total:,} rows → {output_path} | total_time={time.time()-t0:,.1f}s")
    return output_path

In [48]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (Parquet): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\final.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=11.4s

[batch   10] rows=20,000,000  elapsed=23.5s

[batch   15] rows=30,000,000  elapsed=35.2s

[batch   20] rows=40,000,000  elapsed=46.9s

[batch   25] rows=50,000,000  elapsed=58.9s

[batch   30] rows=60,000,000  elapsed=70.4s

[batch   35] rows=70,000,000  elapsed=82.2s

[batch   40] rows=78,652,730  elapsed=92.2s

▶ SORT: C:\datum-api-examples-main\OriON\CRACEN\final.parquet.tmp_unsorted_27120_1781747165 → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | tickers=7,525 | has_date=True has_dt=True

  [   200/7,525] AIDX  written=2,175,929  elapsed=199.1s

  [   400/7,525] AORT  written=4,466,923  elapsed=397.3s

  [   600/7,525] AVBH  written=6,712,839  elapsed=593.7s

  [   800/7,525] BFAM  written=8,744,259  elapsed=795.8s

  [  1000/7,525] BREZU  written=10,763,675  elapsed=1,000.3s

  [  1200/7,525] CBRL  written=12,736,787  elapsed=1,200.0s

  [  1400/7,525] CLVT  written=14,820,303  elapsed=1,403.4s

  [  1600/7,525] CRPT  written=17,081,116  elapsed=1,603.9s

  [  1800/7,525] DFAI  written=19,209,193  elapsed=1,807.9s

  [  2000/7,525] EA  written=21,173,168  elapsed=2,007.2s

  [  2200/7,525] ES  written=23,091,538  elapsed=2,212.0s

  [  2400/7,525] FDTX  written=25,111,764  elapsed=2,413.6s

  [  2600/7,525] FSTA  written=27,058,386  elapsed=2,617.7s

  [  2800/7,525] GLNDW  written=29,000,879  elapsed=2,834.9s

  [  3000/7,525] HCHL  written=31,064,430  elapsed=3,044.9s

  [  3200/7,525] HYPR  written=33,017,644  elapsed=3,253.4s

  [  3400/7,525] INMD  written=34,902,873  elapsed=3,457.1s

  [  3600/7,525] JEDI  written=37,126,258  elapsed=3,665.3s

  [  3800/7,525] KRP  written=38,986,987  elapsed=3,880.3s

  [  4000/7,525] LPG  written=40,948,526  elapsed=4,068.6s

  [  4200/7,525] MGK  written=43,048,025  elapsed=4,261.2s

  [  4400/7,525] MTNB  written=45,167,553  elapsed=4,428.7s

  [  4600/7,525] NN  written=47,275,359  elapsed=4,592.1s

  [  4800/7,525] OFRM  written=49,465,614  elapsed=4,766.6s

  [  5000/7,525] PAYX  written=51,741,654  elapsed=4,937.8s

  [  5200/7,525] POLA  written=53,794,637  elapsed=5,101.6s

  [  5400/7,525] QRVO  written=55,879,096  elapsed=5,269.1s

  [  5600/7,525] RMTI  written=58,098,188  elapsed=5,433.1s

  [  5800/7,525] SCO  written=60,302,603  elapsed=5,599.0s

  [  6000/7,525] SLYV  written=62,416,803  elapsed=5,770.2s

  [  6200/7,525] SPYX  written=64,885,659  elapsed=5,934.7s

  [  6400/7,525] TCMD  written=66,856,607  elapsed=6,095.4s

  [  6600/7,525] TRIN  written=68,943,891  elapsed=6,256.7s

  [  6800/7,525] UMMA  written=71,171,097  elapsed=6,428.6s

  [  7000/7,525] VIV  written=73,307,779  elapsed=6,593.9s

  [  7200/7,525] WFRD  written=75,503,108  elapsed=6,759.0s

  [  7400/7,525] XSD  written=77,567,474  elapsed=6,917.6s

✅ SORT DONE: 78,652,730 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | time=7,021.8s

✅ DONE: 78,652,730 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=7,124.9s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'