In [1]:
# Parameters
run_date = "2026-01-01"  # papermill replacement
import os
output_dir = os.environ.get("ORION_SIGNALS_DIR", "../signals")
config_path = os.environ.get("DATUM_API_CONFIG_PATH", "../ops/datum_api_config.json")
dry_run = False

# ensure output exists
os.makedirs(output_dir, exist_ok=True)

In [2]:
# Import basic modules
import pandas as pd
from datum_api_client import DatumApi
import datetime
from datetime import timedelta

# Import warnings
import warnings
warnings.filterwarnings("ignore")
# pip install xlrd
# pip install openpyxl

# Download excel with ticker

In [3]:
import os
from pathlib import Path

def find_orion_home() -> Path:
    # 1) найнадійніше — env var
    env = os.environ.get("ORION_HOME")
    if env:
        p = Path(env).expanduser().resolve()
        if not p.exists():
            raise FileNotFoundError(f"ORION_HOME points to missing path: {p}")
        return p

    # 2) fallback: шукаємо папку OriON вгору від поточної директорії
    here = Path.cwd().resolve()
    for parent in [here] + list(here.parents):
        if parent.name.lower() == "orion":
            return parent
        cand = parent / "OriON"
        if cand.exists() and cand.is_dir():
            return cand.resolve()

    raise RuntimeError("Cannot locate OriON. Set ORION_HOME env var.")

ORION_HOME = find_orion_home()

CRACEN_DIR = ORION_HOME / "CRACEN"
WORK_DIR   = CRACEN_DIR / "work"     # батчі/маніфести/тимчасові файли
FINAL_PATH = CRACEN_DIR / "final.parquet"

CRACEN_DIR.mkdir(parents=True, exist_ok=True)
WORK_DIR.mkdir(parents=True, exist_ok=True)

BATCH_DIR = WORK_DIR / "CRACEN_batch"
BATCH_DIR.mkdir(parents=True, exist_ok=True)
ETF_DIR = WORK_DIR / "ETF"
ETF_DIR.mkdir(parents=True, exist_ok=True)


print("ORION_HOME:", ORION_HOME)
print("CRACEN_DIR :", CRACEN_DIR)
print("WORK_DIR  :", WORK_DIR)
print("FINAL_PATH:", FINAL_PATH)

ORION_HOME: C:\datum-api-examples-main\OriON
CRACEN_DIR : C:\datum-api-examples-main\OriON\CRACEN
WORK_DIR  : C:\datum-api-examples-main\OriON\CRACEN\work
FINAL_PATH: C:\datum-api-examples-main\OriON\CRACEN\final.parquet

In [4]:
from datetime import datetime, timedelta, date, time
from calendar import monthrange

# === ТЗ користувача: Europe/Kyiv ===
tz = None  # якщо нема zoneinfo, все одно працює локально

now_local = datetime.now(tz) if tz else datetime.now()
yesterday = (now_local - timedelta(days=1)).date()

# три місяці назад від учора (коректно для різної довжини місяців)
try:
    from dateutil.relativedelta import relativedelta
    start_date = (datetime.combine(yesterday, time(0, 0, 0)) - relativedelta(months=3)).date()
except Exception:
    # fallback без dateutil
    y, m, d = yesterday.year, yesterday.month - 3, yesterday.day
    while m <= 0:
        m += 12
        y -= 1
    d = min(d, monthrange(y, m)[1])
    start_date = date(y, m, d)

# формати з часом
start = f"{start_date:%Y-%m-%d} 00:00:00"
end   = f"{yesterday:%Y-%m-%d} 23:59:59"

# формати без часу
start_date_str = f"{start_date:%Y-%m-%d}"
end_date_str   = f"{yesterday:%Y-%m-%d}"

# вивід
print("🕓 Повні дати (з часом):")
print("start =", start)
print("end   =", end)
print("\n📅 Короткі дати (без часу):")
print("start_date_str =", start_date_str)
print("end_date_str   =", end_date_str)

🕓 Повні дати (з часом):
start = 2025-12-20 00:00:00
end   = 2026-03-20 23:59:59

📅 Короткі дати (без часу):
start_date_str = 2025-12-20
end_date_str   = 2026-03-20

In [5]:
import datetime

yesterday = (datetime.date.today() - datetime.timedelta(days=1)).strftime("%Y-%m-%d")

params = {
    "date_as_of": yesterday,
    "format": "json_records"
}

df = DatumApi.data_request("/calculations/median_premarket_value_traded_ex_finr_3m", params)

print(df.head())
print("Рядків:", len(df))

Signature has expired

  ticker       value
0      A    62213.55
1     AA  2248598.85
2    AAA        0.00
3   AAAA        0.00
4   AAAC        0.00
Рядків: 12693

In [6]:
def filter_nonzero(df: pd.DataFrame) -> pd.DataFrame:
    """
    Повертає копію датафрейму лише з тими рядками,
    де колонка 'value' не дорівнює нулю.
    """
    if "value" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'value'")
    return df[df["value"].fillna(0) != 0].copy()


# --- крок 1: фільтруємо df (де 'value' != 0)
df_filtered = filter_nonzero(df)

# --- крок 2: тягнемо дані по тікерах
ticker_params = {
    'fields': 'lvl3,country,exchange,market_cap',
    'active': True,
    'us_exchange': True,
    'listed': True
}
tickers_df = DatumApi.data_request('/tickers', ticker_params)
tickers_df = tickers_df.dropna()

# --- крок 3: додаємо потрібні колонки у df_filtered
top1500 = df_filtered.merge(
    tickers_df,
    how='left',
    on='ticker'
)

print(f"Після фільтрації залишилось: {len(top1500):,} рядків")
top1500.head()

Після фільтрації залишилось: 6,932 рядків

,ticker,value,lvl3,country,exchange,market_cap
0,A,62213.55,Medical Equipment & Devices,UNITED STATES,New York,31462.0
1,AA,2248598.85,Metals & Mining,UNITED STATES,New York,14893.0
2,AAAU,1150687.46,NaN,NaN,NaN,NaN
3,AACG,3.61,Software,UNITED STATES,NASDAQ CM,32.0
4,AAL,1494863.10,Transportation & Logistics,UNITED STATES,NASDAQ GS,6886.0

In [7]:
top1500[top1500["ticker"] == "JD"]

,ticker,value,lvl3,country,exchange,market_cap
3325,JD,2824630.91,E-Commerce Discretionary,UNITED STATES,NASDAQ GS,37115.0

In [8]:
def get_unique_lvl2(df: pd.DataFrame) -> list:
    """
    Повертає список унікальних значень з колонки 'lvl3' у датафреймі.
    Пропуски (NaN) ігноруються.
    """
    if "lvl3" not in df.columns:
        raise ValueError("У датафреймі немає колонки 'lvl3'")
    
    unique_vals = sorted(df["lvl3"].dropna().unique().tolist())
    print(f"🔹 Знайдено {len(unique_vals)} унікальних значень у колонці 'lvl3'")
    return unique_vals

In [9]:
unique_lvl2 = get_unique_lvl2(top1500)
unique_lvl2

🔹 Знайдено 58 унікальних значень у колонці 'lvl3'

['Advertising & Marketing',
 'Aerospace & Defense',
 'Apparel & Textile Products',
 'Asset Management',
 'Automotive',
 'Banking',
 'Beverages',
 'Biotech & Pharma',
 'Cable & Satellite',
 'Chemicals',
 'Commercial Support Services',
 'Construction Materials',
 'Consumer Services',
 'Containers & Packaging',
 'Diversified Industrials',
 'E-Commerce Discretionary',
 'Electric Utilities',
 'Electrical Equipment',
 'Engineering & Construction',
 'Entertainment Content',
 'Food',
 'Forestry, Paper & Wood Products',
 'Gas & Water Utilities',
 'Health Care Facilities & Svcs',
 'Home & Office Products',
 'Home Construction',
 'Household Products',
 'IT Services',
 'Industrial Intermediate Prod',
 'Industrial Support Services',
 'Institutional Financial Svcs',
 'Insurance',
 'Internet Media & Services',
 'Leisure Facilities & Services',
 'Leisure Products',
 'Machinery',
 'Medical Equipment & Devices',
 'Metals & Mining',
 'Oil & Gas Services & Equip',
 'Oil & Gas Supply Chain',
 'Publishing & Broadcasting',
 'REIT',
 'Real Estate Owners & Developers',
 'Real Estate Services',
 'Renewable Energy',
 'Retail - Consumer Staples',
 'Retail - Discretionary',
 'Semiconductors',
 'Software',
 'Specialty Finance',
 'Steel',
 'Technology Hardware',
 'Telecommunications',
 'Tobacco & Cannabis',
 'Transportation & Logistics',
 'Transportation Equipment',
 'Wholesale - Consumer Staples',
 'Wholesale - Discretionary']

In [10]:
sector_to_etf = {
    # --- Finance ---
    "Asset Management": ["XLF", "SPY", "BITO"],
    "Banking": ["KRE", "XLF", "SPY", "BITO"],
    "Institutional Financial Svcs": ["XLF", "SPY", "BITO"],
    "Insurance": ["XLF", "SPY", "BITO"],
    "Specialty Finance": ["XLF", "SPY", "BITO"],

    # --- Tech / Internet / Growth ---
    "Software": ["QQQ", "IWM", "SPY"],
    "IT Services": ["QQQ", "IWM", "SPY"],
    "Semiconductors": ["SOXL", "QQQ", "IWM", "SPY"],
    "Technology Hardware": ["QQQ", "SOXL", "IWM", "SPY"],
    "Internet Media & Services": ["QQQ", "KWEB", "IWM", "SPY"],
    "E-Commerce Discretionary": ["QQQ", "KWEB", "IWM", "SPY"],
    "Cable & Satellite": ["QQQ", "KWEB", "IWM", "SPY"],
    "Telecommunications": ["QQQ", "KWEB", "IWM", "SPY"],
    "Publishing & Broadcasting": ["QQQ", "KWEB", "IWM", "SPY"],
    "Entertainment Content": ["QQQ", "KWEB", "IWM", "SPY"],
    "Advertising & Marketing": ["QQQ", "KWEB", "IWM", "SPY"],

    # --- Industrials ---
    "Aerospace & Defense": ["IWM", "SPY", "QQQ"],
    "Diversified Industrials": ["SPY", "IWM"],
    "Industrial Intermediate Prod": ["IWM", "SPY"],
    "Industrial Support Services": ["IWM", "SPY"],
    "Engineering & Construction": ["IWM", "SPY"],
    "Machinery": ["IWM", "SPY"],
    "Transportation & Logistics": ["IWM", "SPY"],
    "Transportation Equipment": ["IWM", "SPY"],
    "Commercial Support Services": ["IWM", "SPY"],
    "Containers & Packaging": ["IWM", "SPY"],
    "Electrical Equipment": ["QQQ", "IWM", "SPY"],

    # --- Energy / Materials / Commodities ---
    "Oil & Gas Services & Equip": ["XLE", "IWM", "SPY"],
    "Oil & Gas Supply Chain": ["XLE", "IWM", "SPY"],
    "Elec & Gas Marketing & Trading": ["XLE", "IWM", "SPY"],
    "Electric Utilities": ["XLE", "IWM", "SPY"],
    "Gas & Water Utilities": ["XLE", "IWM", "SPY"],
    "Renewable Energy": ["XLE", "IWM", "SPY"],
    "Chemicals": ["XLE", "IWM", "SPY"],
    "Metals & Mining": ["GDX", "IWM", "SPY"],
    "Steel": ["GDX", "IWM", "SPY"],
    "Construction Materials": ["IWM", "SPY"],
    "Forestry, Paper & Wood Products": ["IWM", "SPY"],

    # --- Health Care ---
    "Biotech & Pharma": ["QQQ", "IWM", "SPY"],
    "Medical Equipment & Devices": ["QQQ", "IWM", "SPY"],
    "Health Care Facilities & Svcs": ["QQQ", "IWM", "SPY"],

    # --- Consumer Staples / Discretionary ---
    "Food": ["SPY", "IWM"],
    "Beverages": ["SPY", "IWM"],
    "Household Products": ["SPY", "IWM"],
    "Tobacco & Cannabis": ["SPY", "IWM"],
    "Retail - Consumer Staples": ["SPY", "IWM"],
    "Wholesale - Consumer Staples": ["SPY", "IWM"],

    "Retail - Discretionary": ["SPY", "IWM", "QQQ"],
    "Wholesale - Discretionary": ["SPY", "IWM", "QQQ"],
    "Consumer Services": ["SPY", "IWM"],
    "Leisure Facilities & Services": ["SPY", "IWM"],
    "Leisure Products": ["SPY", "IWM"],
    "Apparel & Textile Products": ["SPY", "IWM", "QQQ"],
    "Automotive": ["SPY", "IWM", "QQQ"],
    "Home & Office Products": ["SPY", "IWM"],
    "Home Construction": ["IWM", "SPY"],

    # --- Real Estate ---
    "REIT": ["IWM", "SPY"],
    "Real Estate Owners & Developers": ["IWM", "SPY"],
    "Real Estate Services": ["IWM", "SPY"],
}

In [11]:
# ------------------------------------------------

In [12]:
import time
import math
import pandas as pd

def corr_beta_best_match_batched(
    x_tickers,
    y_tickers,
    period="3 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.15,
    max_retries=3,
    output_path=None,          # 🔹 тепер дефолт = None
):
    """
    Викликає /calculations/corr_beta/v2 батчами, об'єднує результати в один DataFrame,
    для кожного X-тікера знаходить Y з максимальною кореляцією.

    Повертає (df_all, df_pairs):
      - df_all   : сирий об'єднаний датафрейм з API
      - df_pairs : мапінг X -> найкращий Y
    """
    # --- валідації ---
    if not x_tickers:
        empty_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
        )
        if output_path:
            empty_pairs.to_csv(output_path, index=False)
        return pd.DataFrame(), empty_pairs

    if not y_tickers:
        raise ValueError("y_tickers не може бути порожнім")

    # --- батчинг (індексний підхід, щоб не губити/дублювати X) ---
    y_str = ",".join(map(str, y_tickers))
    results = []
    i = 0
    n = len(x_tickers)
    bs = max(1, int(batch_size))

    while i < n:
        xs = list(map(str, x_tickers[i : i + bs]))
        x_str = ",".join(xs)

        params = {
            "x_tickers": x_str,
            "y_tickers": y_str,
            "period": period,
            "as_pivot": as_pivot,
            "format": fmt,
        }

        attempt = 0
        while True:
            try:
                df_chunk = DatumApi.data_request("/calculations/corr_beta/v2", params)

                # підстраховка типів
                if df_chunk is None:
                    fetched_ok = False
                elif isinstance(df_chunk, pd.DataFrame):
                    fetched_ok = not df_chunk.empty
                else:
                    df_chunk = pd.DataFrame(df_chunk)
                    fetched_ok = not df_chunk.empty

                if fetched_ok:
                    results.append(df_chunk)

                i += len(xs)
                print(f"[{i}/{n}] fetched batch of {len(xs)} X тикерів")
                time.sleep(pause)
                break

            except Exception as e:
                msg = str(e).lower()
                attempt += 1

                if "414" in msg or "uri too large" in msg or "request-uri too large" in msg:
                    new_bs = max(1, bs // 2)
                    if new_bs == bs:
                        if attempt >= max_retries:
                            print(
                                f"⚠️  Пропускаю {len(xs)} X-тикерів (i={i}) "
                                f"після {max_retries} 414-помилок. Помилка: {e}"
                            )
                            i += len(xs)
                            break
                    else:
                        print(
                            f"⚠️  414 на i={i}. Зменшую batch_size {bs} → {new_bs} "
                            f"і формую партію заново."
                        )
                        bs = new_bs
                        break
                else:
                    if attempt >= max_retries:
                        print(
                            f"⚠️  Пропускаю {len(xs)} X-тикерів (i={i}) "
                            f"після {max_retries} спроб. Помилка: {e}"
                        )
                        i += len(xs)
                        break
                    time.sleep(0.5 * attempt)

    df_all = pd.concat(results, ignore_index=True) if results else pd.DataFrame()

    # --- нормалізація назв колонок ---
    def _col(options, cols_lower):
        for c in options:
            if c.lower() in cols_lower:
                return next(cc for cc in df_all.columns if cc.lower() == c.lower())
        return None

    if df_all.empty:
        empty_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]
        )
        if output_path:
            empty_pairs.to_csv(output_path, index=False)
        return df_all, empty_pairs

    cols_lower = {c.lower() for c in df_all.columns}

    x_col    = _col(["x_ticker", "x", "ticker_x", "subject", "symbol_x"], cols_lower)
    y_col    = _col(["y_ticker", "y", "ticker_y", "benchmark", "symbol_y"], cols_lower)
    corr_col = _col(["corr", "correlation", "pearson_corr"], cols_lower)
    beta_col = _col(["beta", "beta_coeff"], cols_lower)

    missing = [
        name
        for name, val in [("x_ticker", x_col), ("y_ticker", y_col), ("corr", corr_col)]
        if val is None
    ]
    if missing:
        raise ValueError(
            f"Від API бракує очікуваних колонок: {', '.join(missing)}. "
            f"Є колонки: {list(df_all.columns)}"
        )

    # --- вибір найкращого Y для кожного X за corr ---
    df_sorted = df_all.sort_values(by=corr_col, ascending=False)
    idx_best = df_sorted.groupby(x_col, as_index=False)[corr_col].idxmax()[corr_col]
    df_best = df_sorted.loc[
        idx_best, [x_col, y_col, corr_col] + ([beta_col] if beta_col else [])
    ].copy()

    rename_map = {
        x_col: "x_ticker",
        y_col: "best_y_ticker",
        corr_col: "best_corr",
    }
    if beta_col:
        rename_map[beta_col] = "beta_with_best"
    df_pairs = df_best.rename(columns=rename_map)

    if "beta_with_best" not in df_pairs.columns:
        df_pairs["beta_with_best"] = pd.NA

    df_pairs = df_pairs[["x_ticker", "best_y_ticker", "best_corr", "beta_with_best"]]

    if output_path:
        df_pairs.to_csv(output_path, index=False)
        print(f"✅ Збережено {len(df_pairs)} пар у файл: {output_path}")

    return df_all, df_pairs

In [13]:
def corr_beta_best_etf_by_lvl3(
    tickers_df,
    sector_to_etf,
    sector_col="lvl3",
    ticker_col="ticker",
    period="3 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.15,
    max_retries=3,
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",
    bench_path="ticker_bench.csv",
    fallback_etfs=None,
):
    """
    Створює два файли:
      1) output_path (за замовчуванням x_to_best_etf_by_lvl3.csv):
         x_ticker, best_y_ticker, best_corr, beta_with_best, lvl3

      2) bench_path (за замовчуванням ticker_bench.csv):
         ticker, benchmark

    Логіка:
      - Для кожного lvl3-сектора збираємо X-список тікерів.
      - Y-список ETF-ів беремо з sector_to_etf[lvl3].
      - Якщо сектору немає в мапі або список порожній → використовуємо fallback_etfs
        (за замовчуванням ["SPY", "QQQ", "IWM"]).
      - Для кожного тикера залишаємо ETF з максимальною кореляцією.
      - Тікери без lvl3 (NaN) обробляються як сектор 'UNKNOWN' з fallback ETF-ами.
    """

    import pandas as pd  # на випадок, якщо не імпортнуто вище

    if fallback_etfs is None:
        fallback_etfs = ["SPY", "QQQ", "IWM"]

    if sector_col not in tickers_df.columns:
        raise ValueError(f"У tickers_df немає колонки '{sector_col}'")
    if ticker_col not in tickers_df.columns:
        raise ValueError(f"У tickers_df немає колонки '{ticker_col}'")

    # Беремо лише тикер і сектор, але НЕ дропаємо NaN — замінимо їх на 'UNKNOWN'
    df_clean = (
        tickers_df[[ticker_col, sector_col]]
        .drop_duplicates()
        .copy()
    )

    # 🔥 Тікери без сектора → 'UNKNOWN'
    df_clean[sector_col] = df_clean[sector_col].fillna("UNKNOWN").astype(str)
    df_clean[ticker_col] = df_clean[ticker_col].astype(str)

    all_sectors = sorted(df_clean[sector_col].unique().tolist())

    all_chunks = []
    all_pairs = []
    sectors_with_fallback = []

    for sector in all_sectors:
        etfs = sector_to_etf.get(sector)

        if not etfs:
            etfs = list(fallback_etfs)
            sectors_with_fallback.append(sector)
            print(
                f"⚠️  Для сектора '{sector}' немає ETF-ів у sector_to_etf — "
                f"використовую fallback: {etfs}"
            )
        else:
            print(f"✅ lvl3: {sector} → ETF-и з мапи: {etfs}")

        x_tickers = (
            df_clean.loc[df_clean[sector_col] == sector, ticker_col]
            .astype(str)
            .unique()
            .tolist()
        )
        if not x_tickers:
            continue

        print(f"\n=== lvl3: {sector} | X-тикерів: {len(x_tickers)} | ETF-и: {etfs} ===")

        df_all_sec, df_pairs_sec = corr_beta_best_match_batched(
            x_tickers=x_tickers,
            y_tickers=etfs,
            period=period,
            as_pivot=as_pivot,
            fmt=fmt,
            batch_size=batch_size,
            pause=pause,
            max_retries=max_retries,
            output_path=None,   # тут не пишемо окремі файли
        )

        if not df_all_sec.empty:
            df_all_sec = df_all_sec.copy()
            df_all_sec[sector_col] = sector
            all_chunks.append(df_all_sec)

        if not df_pairs_sec.empty:
            df_pairs_sec = df_pairs_sec.copy()
            df_pairs_sec[sector_col] = sector
            all_pairs.append(df_pairs_sec)

    df_all = pd.concat(all_chunks, ignore_index=True) if all_chunks else pd.DataFrame()

    if all_pairs:
        df_pairs = pd.concat(all_pairs, ignore_index=True)

        # на випадок дублів по x_ticker — лишаємо найбільшу кореляцію
        df_pairs_sorted = df_pairs.sort_values(by="best_corr", ascending=False)
        idx_best = (
            df_pairs_sorted.groupby("x_ticker", as_index=False)["best_corr"]
            .idxmax()["best_corr"]
        )
        df_pairs = df_pairs_sorted.loc[idx_best].reset_index(drop=True)

        # ⚙️ детальний файл
        df_pairs.to_csv(output_path, index=False)
        print(f"\n✅ Збережено {len(df_pairs)} X→ETF пар у файл: {output_path}")

        # ⚙️ спрощений файл вигляду ticker,benchmark
        df_bench = df_pairs.rename(
            columns={"x_ticker": "ticker", "best_y_ticker": "benchmark"}
        )[["ticker", "benchmark"]]

        df_bench.to_csv(bench_path, index=False)
        print(f"✅ Збережено {len(df_bench)} записів у файл: {bench_path}")

    else:
        df_pairs = pd.DataFrame(
            columns=["x_ticker", "best_y_ticker", "best_corr", "beta_with_best", sector_col]
        )
        df_pairs.to_csv(output_path, index=False)
        pd.DataFrame(columns=["ticker", "benchmark"]).to_csv(bench_path, index=False)
        print("\n⚠️ Не вдалося знайти жодної пари X→ETF. Створено порожні файли.")

    if sectors_with_fallback:
        print("\n⚠️ Для цих lvl3 використано fallback ETF-и (SPY, QQQ, IWM):")
        for s in sectors_with_fallback:
            print("   -", s)

    return df_all, df_pairs

In [14]:
# нове: працюємо напряму з таблицею top1500 (ticker + lvl3)
df_all, df_pairs = corr_beta_best_etf_by_lvl3(
    tickers_df=top1500,          # DataFrame з колонками ticker, lvl3, ...
    sector_to_etf=sector_to_etf, # мапа lvl3 -> список ETF-ів
    sector_col="lvl3",           # Yазва колонки сектора в top1500
    ticker_col="ticker",         # назва колонки з тикером
    period="3 months",
    as_pivot=False,
    fmt="json_records",
    batch_size=150,
    pause=0.1,
    max_retries=3,
    output_path="CRACEN/work/x_to_best_etf_by_lvl3.csv",  # детальна інфа
    bench_path=str(WORK_DIR / "ticker_bench_.csv")
            # простий файл ticker,benchmark
)

print(df_all.head())
print("Рядків у сирих даних:", len(df_all))
print(df_pairs.head())

✅ lvl3: Advertising & Marketing → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Advertising & Marketing | X-тикерів: 34 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[34/34] fetched batch of 34 X тикерів
✅ lvl3: Aerospace & Defense → ETF-и з мапи: ['IWM', 'SPY', 'QQQ']

=== lvl3: Aerospace & Defense | X-тикерів: 73 | ETF-и: ['IWM', 'SPY', 'QQQ'] ===

[73/73] fetched batch of 73 X тикерів
✅ lvl3: Apparel & Textile Products → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Apparel & Textile Products | X-тикерів: 35 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[35/35] fetched batch of 35 X тикерів
✅ lvl3: Asset Management → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Asset Management | X-тикерів: 194 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[150/194] fetched batch of 150 X тикерів

[194/194] fetched batch of 44 X тикерів
✅ lvl3: Automotive → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Automotive | X-тикерів: 73 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[73/73] fetched batch of 73 X тикерів
✅ lvl3: Banking → ETF-и з мапи: ['KRE', 'XLF', 'SPY', 'BITO']

=== lvl3: Banking | X-тикерів: 227 | ETF-и: ['KRE', 'XLF', 'SPY', 'BITO'] ===

[150/227] fetched batch of 150 X тикерів

[227/227] fetched batch of 77 X тикерів
✅ lvl3: Beverages → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Beverages | X-тикерів: 36 | ETF-и: ['SPY', 'IWM'] ===

[36/36] fetched batch of 36 X тикерів
✅ lvl3: Biotech & Pharma → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Biotech & Pharma | X-тикерів: 663 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/663] fetched batch of 150 X тикерів

[300/663] fetched batch of 150 X тикерів

[450/663] fetched batch of 150 X тикерів

[600/663] fetched batch of 150 X тикерів

[663/663] fetched batch of 63 X тикерів
✅ lvl3: Cable & Satellite → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Cable & Satellite | X-тикерів: 13 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[13/13] fetched batch of 13 X тикерів
✅ lvl3: Chemicals → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Chemicals | X-тикерів: 85 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[85/85] fetched batch of 85 X тикерів
✅ lvl3: Commercial Support Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Commercial Support Services | X-тикерів: 110 | ETF-и: ['IWM', 'SPY'] ===

[110/110] fetched batch of 110 X тикерів
✅ lvl3: Construction Materials → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Construction Materials | X-тикерів: 21 | ETF-и: ['IWM', 'SPY'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Consumer Services → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Consumer Services | X-тикерів: 40 | ETF-и: ['SPY', 'IWM'] ===

[40/40] fetched batch of 40 X тикерів
✅ lvl3: Containers & Packaging → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Containers & Packaging | X-тикерів: 21 | ETF-и: ['IWM', 'SPY'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Diversified Industrials → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Diversified Industrials | X-тикерів: 7 | ETF-и: ['SPY', 'IWM'] ===

[7/7] fetched batch of 7 X тикерів
✅ lvl3: E-Commerce Discretionary → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: E-Commerce Discretionary | X-тикерів: 49 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[49/49] fetched batch of 49 X тикерів
✅ lvl3: Electric Utilities → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Electric Utilities | X-тикерів: 69 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[69/69] fetched batch of 69 X тикерів
✅ lvl3: Electrical Equipment → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Electrical Equipment | X-тикерів: 93 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[93/93] fetched batch of 93 X тикерів
✅ lvl3: Engineering & Construction → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Engineering & Construction | X-тикерів: 55 | ETF-и: ['IWM', 'SPY'] ===

[55/55] fetched batch of 55 X тикерів
✅ lvl3: Entertainment Content → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Entertainment Content | X-тикерів: 43 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[43/43] fetched batch of 43 X тикерів
✅ lvl3: Food → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Food | X-тикерів: 67 | ETF-и: ['SPY', 'IWM'] ===

[67/67] fetched batch of 67 X тикерів
✅ lvl3: Forestry, Paper & Wood Products → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Forestry, Paper & Wood Products | X-тикерів: 10 | ETF-и: ['IWM', 'SPY'] ===

[10/10] fetched batch of 10 X тикерів
✅ lvl3: Gas & Water Utilities → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Gas & Water Utilities | X-тикерів: 24 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[24/24] fetched batch of 24 X тикерів
✅ lvl3: Health Care Facilities & Svcs → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Health Care Facilities & Svcs | X-тикерів: 99 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[99/99] fetched batch of 99 X тикерів
✅ lvl3: Home & Office Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Home & Office Products | X-тикерів: 21 | ETF-и: ['SPY', 'IWM'] ===

[21/21] fetched batch of 21 X тикерів
✅ lvl3: Home Construction → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Home Construction | X-тикерів: 36 | ETF-и: ['IWM', 'SPY'] ===

[36/36] fetched batch of 36 X тикерів
✅ lvl3: Household Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Household Products | X-тикерів: 39 | ETF-и: ['SPY', 'IWM'] ===

[39/39] fetched batch of 39 X тикерів
✅ lvl3: IT Services → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: IT Services | X-тикерів: 68 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[68/68] fetched batch of 68 X тикерів
✅ lvl3: Industrial Intermediate Prod → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Industrial Intermediate Prod | X-тикерів: 23 | ETF-и: ['IWM', 'SPY'] ===

[23/23] fetched batch of 23 X тикерів
✅ lvl3: Industrial Support Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Industrial Support Services | X-тикерів: 32 | ETF-и: ['IWM', 'SPY'] ===

[32/32] fetched batch of 32 X тикерів
✅ lvl3: Institutional Financial Svcs → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Institutional Financial Svcs | X-тикерів: 38 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[38/38] fetched batch of 38 X тикерів
✅ lvl3: Insurance → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Insurance | X-тикерів: 90 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[90/90] fetched batch of 90 X тикерів
✅ lvl3: Internet Media & Services → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Internet Media & Services | X-тикерів: 107 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[107/107] fetched batch of 107 X тикерів
✅ lvl3: Leisure Facilities & Services → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Leisure Facilities & Services | X-тикерів: 114 | ETF-и: ['SPY', 'IWM'] ===

[114/114] fetched batch of 114 X тикерів
✅ lvl3: Leisure Products → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Leisure Products | X-тикерів: 33 | ETF-и: ['SPY', 'IWM'] ===

[33/33] fetched batch of 33 X тикерів
✅ lvl3: Machinery → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Machinery | X-тикерів: 86 | ETF-и: ['IWM', 'SPY'] ===

[86/86] fetched batch of 86 X тикерів
✅ lvl3: Medical Equipment & Devices → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Medical Equipment & Devices | X-тикерів: 202 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/202] fetched batch of 150 X тикерів

[202/202] fetched batch of 52 X тикерів
✅ lvl3: Metals & Mining → ETF-и з мапи: ['GDX', 'IWM', 'SPY']

=== lvl3: Metals & Mining | X-тикерів: 150 | ETF-и: ['GDX', 'IWM', 'SPY'] ===

[150/150] fetched batch of 150 X тикерів
✅ lvl3: Oil & Gas Services & Equip → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Oil & Gas Services & Equip | X-тикерів: 56 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[56/56] fetched batch of 56 X тикерів
✅ lvl3: Oil & Gas Supply Chain → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Oil & Gas Supply Chain | X-тикерів: 145 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[145/145] fetched batch of 145 X тикерів
✅ lvl3: Publishing & Broadcasting → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Publishing & Broadcasting | X-тикерів: 20 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[20/20] fetched batch of 20 X тикерів
✅ lvl3: REIT → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: REIT | X-тикерів: 132 | ETF-и: ['IWM', 'SPY'] ===

[132/132] fetched batch of 132 X тикерів
✅ lvl3: Real Estate Owners & Developers → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Real Estate Owners & Developers | X-тикерів: 14 | ETF-и: ['IWM', 'SPY'] ===

[14/14] fetched batch of 14 X тикерів
✅ lvl3: Real Estate Services → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Real Estate Services | X-тикерів: 19 | ETF-и: ['IWM', 'SPY'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: Renewable Energy → ETF-и з мапи: ['XLE', 'IWM', 'SPY']

=== lvl3: Renewable Energy | X-тикерів: 61 | ETF-и: ['XLE', 'IWM', 'SPY'] ===

[61/61] fetched batch of 61 X тикерів
✅ lvl3: Retail - Consumer Staples → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Retail - Consumer Staples | X-тикерів: 24 | ETF-и: ['SPY', 'IWM'] ===

[24/24] fetched batch of 24 X тикерів
✅ lvl3: Retail - Discretionary → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Retail - Discretionary | X-тикерів: 102 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[102/102] fetched batch of 102 X тикерів
✅ lvl3: Semiconductors → ETF-и з мапи: ['SOXL', 'QQQ', 'IWM', 'SPY']

=== lvl3: Semiconductors | X-тикерів: 104 | ETF-и: ['SOXL', 'QQQ', 'IWM', 'SPY'] ===

[104/104] fetched batch of 104 X тикерів
✅ lvl3: Software → ETF-и з мапи: ['QQQ', 'IWM', 'SPY']

=== lvl3: Software | X-тикерів: 324 | ETF-и: ['QQQ', 'IWM', 'SPY'] ===

[150/324] fetched batch of 150 X тикерів

[300/324] fetched batch of 150 X тикерів

[324/324] fetched batch of 24 X тикерів
✅ lvl3: Specialty Finance → ETF-и з мапи: ['XLF', 'SPY', 'BITO']

=== lvl3: Specialty Finance | X-тикерів: 176 | ETF-и: ['XLF', 'SPY', 'BITO'] ===

[150/176] fetched batch of 150 X тикерів

[176/176] fetched batch of 26 X тикерів
✅ lvl3: Steel → ETF-и з мапи: ['GDX', 'IWM', 'SPY']

=== lvl3: Steel | X-тикерів: 20 | ETF-и: ['GDX', 'IWM', 'SPY'] ===

[20/20] fetched batch of 20 X тикерів
✅ lvl3: Technology Hardware → ETF-и з мапи: ['QQQ', 'SOXL', 'IWM', 'SPY']

=== lvl3: Technology Hardware | X-тикерів: 138 | ETF-и: ['QQQ', 'SOXL', 'IWM', 'SPY'] ===

[138/138] fetched batch of 138 X тикерів
✅ lvl3: Telecommunications → ETF-и з мапи: ['QQQ', 'KWEB', 'IWM', 'SPY']

=== lvl3: Telecommunications | X-тикерів: 45 | ETF-и: ['QQQ', 'KWEB', 'IWM', 'SPY'] ===

[45/45] fetched batch of 45 X тикерів
✅ lvl3: Tobacco & Cannabis → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Tobacco & Cannabis | X-тикерів: 19 | ETF-и: ['SPY', 'IWM'] ===

[19/19] fetched batch of 19 X тикерів
✅ lvl3: Transportation & Logistics → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Transportation & Logistics | X-тикерів: 124 | ETF-и: ['IWM', 'SPY'] ===

[124/124] fetched batch of 124 X тикерів
✅ lvl3: Transportation Equipment → ETF-и з мапи: ['IWM', 'SPY']

=== lvl3: Transportation Equipment | X-тикерів: 21 | ETF-и: ['IWM', 'SPY'] ===

[21/21] fetched batch of 21 X тикерів
⚠️  Для сектора 'UNKNOWN' немає ETF-ів у sector_to_etf — використовую fallback: ['SPY', 'QQQ', 'IWM']

=== lvl3: UNKNOWN | X-тикерів: 2180 | ETF-и: ['SPY', 'QQQ', 'IWM'] ===

[150/2180] fetched batch of 150 X тикерів

[300/2180] fetched batch of 150 X тикерів

[450/2180] fetched batch of 150 X тикерів

[600/2180] fetched batch of 150 X тикерів

[750/2180] fetched batch of 150 X тикерів

[900/2180] fetched batch of 150 X тикерів

[1050/2180] fetched batch of 150 X тикерів

[1200/2180] fetched batch of 150 X тикерів

[1350/2180] fetched batch of 150 X тикерів

[1500/2180] fetched batch of 150 X тикерів

[1650/2180] fetched batch of 150 X тикерів

[1800/2180] fetched batch of 150 X тикерів

[1950/2180] fetched batch of 150 X тикерів

[2100/2180] fetched batch of 150 X тикерів

[2180/2180] fetched batch of 80 X тикерів

✅ lvl3: Wholesale - Consumer Staples → ETF-и з мапи: ['SPY', 'IWM']

=== lvl3: Wholesale - Consumer Staples | X-тикерів: 13 | ETF-и: ['SPY', 'IWM'] ===

[13/13] fetched batch of 13 X тикерів
✅ lvl3: Wholesale - Discretionary → ETF-и з мапи: ['SPY', 'IWM', 'QQQ']

=== lvl3: Wholesale - Discretionary | X-тикерів: 15 | ETF-и: ['SPY', 'IWM', 'QQQ'] ===

[15/15] fetched batch of 15 X тикерів

✅ Збережено 6774 X→ETF пар у файл: CRACEN/work/x_to_best_etf_by_lvl3.csv
✅ Збережено 6774 записів у файл: C:\datum-api-examples-main\OriON\CRACEN\work\ticker_bench_.csv

⚠️ Для цих lvl3 використано fallback ETF-и (SPY, QQQ, IWM):
   - UNKNOWN
  x_ticker y_ticker  corr  beta                     lvl3
0      ADV      QQQ  0.13  0.17  Advertising & Marketing
1      ADV      IWM  0.08  0.07  Advertising & Marketing
2      ADV     KWEB -0.08  0.00  Advertising & Marketing
3      ADV      SPY  0.06  0.15  Advertising & Marketing
4     AEHL     KWEB  0.32  0.00  Advertising & Marketing
Рядків у сирих даних: 19982
  x_ticker best_y_ticker  best_corr  beta_with_best  \
0        A           SPY       0.81            0.93
1       AA           SPY       0.76            2.60
2     AAAU           IWM       0.44            0.73
3     AACG           QQQ       0.05           -0.02
4      AAL           IWM       0.89            1.56

                          lvl3
0  Medical Equipment & Devices
1              Metals & Mining
2                      UNKNOWN
3                     Software
4   Transportation & Logistics

In [15]:
# ================== FAST INTRADAY SUITE w/ BLUE OCEAN (updated + rolling prune) ==================
import os, gc, time, glob, re, csv, uuid, random
import pandas as pd
from datetime import timedelta
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Optional, Tuple

# ---------- utils ----------
def _p(*args, **kwargs):
    kwargs.setdefault("flush", True)
    print(*args, **kwargs)

_PSUTIL = False
try:
    import psutil
    _PSUTIL = True
except Exception:
    psutil = None

def _proc_rss_mb() -> float:
    if _PSUTIL:
        try:
            return psutil.Process(os.getpid()).memory_info().rss / (1024**2)
        except Exception:
            pass
    try:
        import resource
        ru = resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
        if ru > 10**9:
            return ru / (1024**2)
        return ru / 1024.0
    except Exception:
        pass
    try:
        import tracemalloc
        if not tracemalloc.is_tracing():
            tracemalloc.start()
        cur, _ = tracemalloc.get_traced_memory()
        return cur / (1024**2)
    except Exception:
        return float('nan')

def _mem_str(prefix: str = "") -> str:
    mb = _proc_rss_mb()
    if mb != mb:
        return f"{prefix}🧠 RAM: n/a"
    return f"{prefix}🧠 RAM: {mb:,.1f} MB"

def _ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def _fmt_eta(sec: float) -> str:
    sec = max(0, int(sec))
    d, r = divmod(sec, 86400)
    h, r = divmod(r, 3600)
    m, s = divmod(r, 60)
    if d > 0: return f"{d}d {h:02d}:{m:02d}:{s:02d}"
    if h > 0: return f"{h:02d}:{m:02d}:{s:02d}"
    return f"{m:02d}:{s:02d}"

def _next_batch_index(out_dir: str, out_prefix: str) -> int:
    pat_csv = os.path.join(out_dir, f"{out_prefix}_*.csv")
    pat_gz  = os.path.join(out_dir, f"{out_prefix}_*.csv.gz")
    files = glob.glob(pat_csv) + glob.glob(pat_gz)
    mx = 0
    rx = re.compile(rf'^{re.escape(out_prefix)}_(\d+)\.csv(?:\.gz)?$')
    for f in files:
        m = rx.match(os.path.basename(f))
        if m:
            mx = max(mx, int(m.group(1)))
    return mx + 1 if mx > 0 else 1

# ---------- manifest helpers (old ticker-level) ----------
def _manifest_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_tickers.txt")

def _load_done_tickers_manifest(out_dir: str) -> Optional[set]:
    path = _manifest_path(out_dir)
    if not os.path.exists(path):
        return None
    done = set()
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            t = line.strip()
            if t:
                done.add(t)
    return done

def _append_done_tickers_manifest(out_dir: str, tickers: List[str]):
    if not tickers:
        return
    path = _manifest_path(out_dir)
    existing = set()
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            for line in f:
                s = line.strip()
                if s:
                    existing.add(s)
    new_ones = [t for t in set(tickers) if t not in existing]
    if not new_ones:
        return
    with open(path, "a", encoding="utf-8") as f:
        for t in new_ones:
            f.write(t + "\n")

# ---------- day-manifest helpers (NEW) ----------
def _manifest_days_path(out_dir: str) -> str:
    return os.path.join(out_dir, "done_days.csv")

def _load_done_days_manifest(out_dir: str) -> dict:
    """
    Return dict: ticker -> set({'YYYY-MM-DD', ...})
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}
    done = {}
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        if header and "ticker" in header and "date" in header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            f.seek(0); rdr = csv.reader(f)
        for row in rdr:
            if not row:
                continue
            tk = row[col_idx["ticker"]].strip()
            dt = row[col_idx["date"]].strip()
            if tk and dt:
                done.setdefault(tk, set()).add(dt)
    return done

def _append_done_days_manifest(out_dir: str, df: pd.DataFrame):
    """
    From df uses 'ticker' and 'dt' (YYYY-MM-DD HH:MM:SS) to append (ticker,date) to done_days.csv
    """
    if df is None or df.empty or "dt" not in df.columns or "ticker" not in df.columns:
        return
    path = _manifest_days_path(out_dir)
    _ensure_dir(out_dir)

    tmp = df[["ticker","dt"]].copy()
    tmp["date"] = tmp["dt"].astype(str).str.slice(0,10)
    tmp = tmp.drop_duplicates(subset=["ticker","date"])

    need_header = not os.path.exists(path)
    with open(path, "a", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        if need_header:
            wr.writerow(["ticker","date"])
        for _, r in tmp.iterrows():
            wr.writerow([str(r["ticker"]).strip(), str(r["date"]).strip()])

def prune_done_days_manifest(out_dir: str, start_date_str: str, end_date_str: str) -> dict:
    """
    Rolling-window prune for done_days.csv:
    - keep only rows where start_date_str <= date <= end_date_str
    - returns refreshed dict: ticker -> set(dates)
    Safe to call even if file doesn't exist.
    """
    path = _manifest_days_path(out_dir)
    if not os.path.exists(path):
        return {}

    # normalize inputs
    start_date_str = str(start_date_str)[:10]
    end_date_str   = str(end_date_str)[:10]
    if start_date_str > end_date_str:
        # swap just in case
        start_date_str, end_date_str = end_date_str, start_date_str

    rows = []
    with open(path, "r", encoding="utf-8", newline="") as f:
        rdr = csv.reader(f)
        header = next(rdr, None)
        col_idx = {"ticker": 0, "date": 1}
        has_header = bool(header and "ticker" in header and "date" in header)
        if has_header:
            col_idx["ticker"] = header.index("ticker")
            col_idx["date"]   = header.index("date")
        else:
            # no header; treat first row as data
            if header:
                rdr = [header] + list(rdr)  # include first row back as data
            else:
                rdr = []
        for row in rdr:
            if not row:
                continue
            try:
                tk = str(row[col_idx["ticker"]]).strip().upper()
                dt = str(row[col_idx["date"]]).strip()[:10]
            except Exception:
                continue
            if not tk or not dt:
                continue
            if start_date_str <= dt <= end_date_str:
                rows.append((tk, dt))

    # rewrite file (dedup)
    _ensure_dir(out_dir)
    tmp_path = path + ".tmp"
    seen = set()
    with open(tmp_path, "w", encoding="utf-8", newline="") as f:
        wr = csv.writer(f)
        wr.writerow(["ticker","date"])
        for tk, dt in rows:
            key = (tk, dt)
            if key in seen:
                continue
            seen.add(key)
            wr.writerow([tk, dt])
    os.replace(tmp_path, path)

    # build dict cache
    done = {}
    for tk, dt in seen:
        done.setdefault(tk, set()).add(dt)
    return done

def _dates_between(start: str, end: str) -> List[pd.Timestamp]:
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    days = pd.date_range(start=s.normalize(), end=e.normalize(), freq="D")
    return list(days)

def _group_consecutive_dates(dates: List[pd.Timestamp], max_span_days: int) -> List[Tuple[str, str]]:
    """
    Build [start_dt, end_dt] ranges from a list of dates, merging consecutive days,
    capped by max_span_days per range. Datetimes are ISO to seconds.
    """
    if not dates:
        return []
    dates = sorted(pd.to_datetime(dates))
    out = []
    run_start = dates[0]
    run_end = dates[0]
    for d in dates[1:]:
        consecutive = (d - run_end).days == 1
        span_len = (d - run_start).days + 1
        if consecutive and span_len <= max_span_days:
            run_end = d
        else:
            a = run_start.strftime("%Y-%m-%d 00:00:00")
            b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
            out.append((a, b))
            run_start = d
            run_end = d
    a = run_start.strftime("%Y-%m-%d 00:00:00")
    b = (run_end + pd.Timedelta(hours=23, minutes=59, seconds=59)).strftime("%Y-%m-%d %H:%M:%S")
    out.append((a, b))
    return out

# ================== SMALL (low-level) FUNCTIONS ==================
def _build_ranges(start: str, end: str, chunk_days: int) -> List[Tuple[str, str]]:
    """Розбиває [start,end] на неперекривні відрізки по chunk_days днів."""
    chunk_days = max(1, int(chunk_days))
    s = pd.to_datetime(start)
    e = pd.to_datetime(end)
    if pd.isna(s) or pd.isna(e) or s > e:
        return []
    out: List[Tuple[str, str]] = []
    cur = s
    step = timedelta(days=chunk_days) - timedelta(seconds=1)
    while cur <= e:
        r_end = min(cur + step, e)
        out.append((cur.strftime("%Y-%m-%d %H:%M:%S"), r_end.strftime("%Y-%m-%d %H:%M:%S")))
        cur = r_end + timedelta(seconds=1)
    return out

def _one_call_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    max_retries: int = 2,
    retry_backoff: float = 0.5,     # сек
    normalize_ohlcv: bool = False,  # дефолт: ВИМКНЕНО (швидкість)
) -> pd.DataFrame:
    """Основний ендпоінт: /intraday/v3."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "include_boats": bool(include_boats),
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def _one_call_blue_ocean_v3_dt_fast(
    ticker: str,
    start_dt: str,
    end_dt: str,
    interval: int,
    *,
    chart_type: str = "ohlcv",
    max_retries: int = 2,
    retry_backoff: float = 0.5,
    normalize_ohlcv: bool = False,
) -> pd.DataFrame:
    """Blue Ocean ендпоінт: /intraday/v3/blue_ocean (20:00–04:00)."""
    params = {
        "ticker": ticker.upper(),
        "interval": int(interval),
        "chart_type": chart_type,
        "start_datetime": start_dt,
        "end_datetime": end_dt,
        "format": "json_records",
    }
    attempts = max(0, int(max_retries)) + 1
    for attempt in range(attempts):
        try:
            df = DatumApi.data_request("/intraday/v3/blue_ocean", params)
            if isinstance(df, pd.DataFrame) and not df.empty:
                if "ticker" not in df.columns:
                    df.insert(0, "ticker", ticker.upper())
                if normalize_ohlcv:
                    for col in ("o","h","l","c","v"):
                        if col in df.columns:
                            df[col] = pd.to_numeric(df[col], errors="ignore")
                return df
            return pd.DataFrame()
        except Exception:
            if attempt == attempts - 1:
                return pd.DataFrame()
            sleep_s = retry_backoff * (2 ** attempt)
            sleep_s *= (0.9 + 0.2 * random.random())
            time.sleep(sleep_s)

def fetch_intraday_v3_datetime_fast(
    ticker: str,
    start: str,
    end: str,
    interval: int = 1,
    *,
    chunk_days: int = 14,
    parallel: bool = True,
    max_workers: int = 12,
    chart_type: str = "ohlcv",
    include_boats: bool = False,
    sort_by_dt: bool = False,   # дефолт: викл (швидкість)
    dedup_dt: bool = False,     # дефолт: викл (швидкість)
    normalize_ohlcv: bool = False,  # дефолт: викл (швидкість)
    include_blue_ocean: bool = False,   # ⬅️ НОВЕ
) -> pd.DataFrame:
    """
    Тягне інтрадійні дані основного вікна і, опційно, Blue Ocean (20:00–04:00),
    зшиває в один DF. За замовчуванням без зайвих перетворень.
    """
    ranges = _build_ranges(start, end, chunk_days)
    if not ranges:
        return pd.DataFrame()

    worker_count = max(1, min(int(max_workers), len(ranges) * (2 if include_blue_ocean else 1))) if parallel else 1
    parts: List[pd.DataFrame] = []

    if parallel and (len(ranges) > 1 or include_blue_ocean):
        with ThreadPoolExecutor(max_workers=worker_count) as ex:
            futs = []
            for (a, b) in ranges:
                futs.append(ex.submit(
                    _one_call_v3_dt_fast, ticker, a, b, interval,
                    chart_type=chart_type, include_boats=include_boats,
                    normalize_ohlcv=normalize_ohlcv
                ))
                if include_blue_ocean:
                    futs.append(ex.submit(
                        _one_call_blue_ocean_v3_dt_fast, ticker, a, b, interval,
                        chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                    ))
            for f in as_completed(futs):
                df = f.result()
                if df is not None and not df.empty:
                    parts.append(df)
    else:
        for (a, b) in ranges:
            df_main = _one_call_v3_dt_fast(
                ticker, a, b, interval,
                chart_type=chart_type, include_boats=include_boats,
                normalize_ohlcv=normalize_ohlcv
            )
            if df_main is not None and not df_main.empty:
                parts.append(df_main)
            if include_blue_ocean:
                df_bo = _one_call_blue_ocean_v3_dt_fast(
                    ticker, a, b, interval,
                    chart_type=chart_type, normalize_ohlcv=normalize_ohlcv
                )
                if df_bo is not None and not df_bo.empty:
                    parts.append(df_bo)

    if not parts:
        return pd.DataFrame()

    out = pd.concat(parts, ignore_index=True)

    # Якщо підмішували Blue Ocean — відсортуємо по 'dt'
    if "dt" in out.columns and (include_blue_ocean or sort_by_dt or dedup_dt):
        if dedup_dt:
            out = out.drop_duplicates(subset=["ticker", "dt"], keep="last")
        out = out.sort_values("dt", kind="mergesort").reset_index(drop=True)

    return out

# ================== BIG (all tickers, batch writer) [UPDATED + rolling prune] ==================
def fetch_intraday_v3_for_all_tickers(
    tickers_df: pd.DataFrame,
    start: str,
    end: str,
    *,
    interval: int = 1,
    chunk_days: int = 30,
    parallel_chunks: bool = True,
    max_workers_chunks: int = 12,
    parallel_tickers: bool = True,
    max_workers_tickers: int = 6,
    save_every: int = 50,
    out_dir: str = "intraday_batches",
    out_prefix: str = "batch",
    gzip: bool = True,
    keep_columns: Optional[List[str]] = None,
    verbose: bool = True,
    progress_every: int = 10,
    mem_log_every: int = 50,
    use_manifest: bool = False,            # old ticker-level manifest (off by default)
    use_day_manifest: bool = True,         # NEW: day-level manifest (on by default)
    flush_when_rows: Optional[int] = None,
    flush_every_seconds: Optional[int] = None,
    include_blue_ocean: bool = False,      # pass-through
) -> pd.DataFrame:
    assert "ticker" in tickers_df.columns, "tickers_df має містити колонку 'ticker'"

    # ⬆️ НОРМАЛІЗАЦІЯ: тікери у верхній регістр одразу на вході
    tickers: List[str] = [str(t).strip().upper() for t in tickers_df["ticker"].dropna().unique()]
    if not tickers:
        return pd.DataFrame(columns=["ticker","error"])

    _ensure_dir(out_dir)

    # --- rolling window bounds as YYYY-MM-DD for manifest prune ---
    start_date_str = str(start)[:10]
    end_date_str   = str(end)[:10]

    has_batches = bool(glob.glob(os.path.join(out_dir, f"{out_prefix}_*.csv*")))
    done_tickers = set()
    if use_manifest:
        m = _load_done_tickers_manifest(out_dir)
        if m and has_batches:
            done_tickers = m
        elif m and not has_batches and verbose:
            _p("⚠️ Знайшов done_tickers.txt, але немає batch-файлів → ігнорую маніфест.")
        # apply old manifest only if explicitly enabled
        tickers = [t for t in tickers if t not in done_tickers]

    # NEW: day manifest load (+ rolling prune)
    if use_day_manifest:
        # prune done_days.csv to the current rolling window and get fresh dict
        done_days_by_ticker = prune_done_days_manifest(out_dir, start_date_str, end_date_str)
    else:
        done_days_by_ticker = {}

    # ⬆️ НОРМАЛІЗАЦІЯ: ключі маніфесту у верхній регістр
    if use_day_manifest and done_days_by_ticker:
        done_days_by_ticker = {str(k).upper(): set(v) for k, v in done_days_by_ticker.items()}

    # --- попереднє відсікання повністю готових тікерів ---
    all_days_list = _dates_between(start, end)
    all_days_str = [d.strftime("%Y-%m-%d") for d in all_days_list]

    def _ticker_fully_done(tk: str) -> bool:
        if not use_day_manifest:
            return False
        s = done_days_by_ticker.get(str(tk).upper(), set())
        return bool(s) and all(dd in s for dd in all_days_str)

    fully_done = [t for t in tickers if _ticker_fully_done(t)]
    tickers = [t for t in tickers if t not in fully_done]

    total = len(tickers)
    batch_idx = _next_batch_index(out_dir, out_prefix)
    run_id = str(uuid.uuid4())[:8]

    errors, buffer = [], []
    written_total = 0
    start_time = time.time()
    last_flush_at = start_time
    rows_in_buffer = 0

    if verbose:
        psutil_note = "psutil" if _PSUTIL else "fallback"

        # логіка визначення діапазонів дат для логів
        if use_day_manifest and done_days_by_ticker:
            # усі дні в маніфесті
            all_done_dates = sorted({d for s in done_days_by_ticker.values() for d in s})
            skipped_days_str = (
                f"{all_done_dates[0]} → {all_done_dates[-1]} ({len(all_done_dates)} днів)"
                if all_done_dates else "–"
            )
            # усі дні, які ще не оброблені (порівняно з повним діапазоном)
            all_days_full = [d.strftime("%Y-%m-%d") for d in _dates_between(start, end)]
            remaining_days = sorted(set(all_days_full) - set(all_done_dates))
            remaining_days_str = (
                f"{remaining_days[0]} → {remaining_days[-1]} ({len(remaining_days)} днів)"
                if remaining_days else "–"
            )
        else:
            skipped_days_str = "–"
            remaining_days_str = f"{start[:10]} → {end[:10]}"

        _p(f"▶ Починаємо: {total} тікерів (пропущено {len(done_tickers)} по старому маніфесту) | {start} → {end} | interval={interval} | next batch #{batch_idx:04d} | run={run_id}")
        _p(f"   workers: tickers={max_workers_tickers if parallel_tickers else 1}, chunks={max_workers_chunks if parallel_chunks else 0} | blue_ocean={include_blue_ocean} | day-manifest={use_day_manifest}")
        _p(f"   day-manifest: повністю готових тікерів пропущено = {len(fully_done)}")
        _p(f"   📉 пропущені дні (в межах window): {skipped_days_str}")
        _p(f"   📈 обробляються дні: {remaining_days_str}")
        _p(_mem_str(f"   {psutil_note} · старт · "))

    def _make_batch_path(idx: int) -> str:
        fname = f"{out_prefix}_{idx:04d}.csv" + (".gz" if gzip else "")
        return os.path.join(out_dir, fname)

    def _append_df_for_buffer(dfi: pd.DataFrame):
        nonlocal rows_in_buffer
        if dfi is None or dfi.empty:
            return
        buffer.append(dfi)
        rows_in_buffer += len(dfi)

    # NEW: миттєво оновлюємо in-memory кеш днів із нових рядків
    def _update_day_cache_from_df(dfi: pd.DataFrame):
        if not use_day_manifest or dfi is None or dfi.empty:
            return
        if "ticker" not in dfi.columns or "dt" not in dfi.columns:
            return
        tmp = dfi[["ticker", "dt"]].copy()
        tmp["date"] = tmp["dt"].astype(str).str.slice(0, 10)
        for tk, grp in tmp.groupby("ticker"):
            done_days_by_ticker.setdefault(str(tk).upper(), set()).update(grp["date"].astype(str).tolist())

    def _flush():
        nonlocal buffer, batch_idx, written_total, rows_in_buffer, last_flush_at
        if not buffer:
            return None
        path = _make_batch_path(batch_idx)
        while os.path.exists(path):
            batch_idx += 1
            path = _make_batch_path(batch_idx)

        if verbose:
            _p(_mem_str("   ⏳ перед flush · "))

        out = pd.concat(buffer, ignore_index=True)

        # Stable order & dedup
        if "dt" in out.columns:
            out = out.drop_duplicates(subset=["ticker","dt"], keep="last")
            out = out.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

        tmp_path = path + ".tmp"
        if gzip:
            out.to_csv(tmp_path, index=False, compression={"method": "gzip", "compresslevel": 1})
        else:
            out.to_csv(tmp_path, index=False, compression=None)
        os.replace(tmp_path, path)

        written_total += len(out)
        if verbose:
            _p(f"💾 batch {batch_idx} → {len(out):,} рядків (всього {written_total:,} у цьому запуску) → {path}")

        # NEW: update day-manifest (та одразу оновити кеш у пам'яті)
        if use_day_manifest:
            if "dt" not in out.columns:
                for alt in ("datetime", "time", "t"):
                    if alt in out.columns:
                        out = out.rename(columns={alt: "dt"})
                        break
            _append_done_days_manifest(out_dir, out)
            _update_day_cache_from_df(out)
        else:
            if "ticker" in out.columns:
                _append_done_tickers_manifest(out_dir, out["ticker"].astype(str).unique().tolist())

        # (опційно) відмічати повністю закриті тікери у старому маніфесті, якщо він увімкнений
        if use_manifest and use_day_manifest:
            def _ticker_fully_done_local(tk: str) -> bool:
                s = done_days_by_ticker.get(str(tk).upper(), set())
                return bool(s) and all(dd in s for dd in all_days_str)
            fully_done_now = []
            for tk in out.get("ticker", pd.Series(dtype=str)).astype(str).str.upper().unique():
                if _ticker_fully_done_local(tk):
                    fully_done_now.append(tk)
            _append_done_tickers_manifest(out_dir, fully_done_now)

        batch_idx += 1
        buffer.clear()
        rows_in_buffer = 0
        del out
        gc.collect()
        last_flush_at = time.time()

        if verbose:
            _p(_mem_str("   ✅ після flush · "))
        return path

    def _progress_line(done: int) -> str:
        pct = (done / total * 100) if total else 100.0
        elapsed = time.time() - start_time
        per_item = elapsed / done if done > 0 else 0.0
        remaining = (total - done) * per_item if done > 0 else 0.0
        return f"{pct:6.2f}% | ETA {_fmt_eta(remaining)}"

    def _should_print(idx: int, is_error: bool, is_last: bool) -> bool:
        if is_error or is_last:
            return True
        if progress_every and progress_every > 0:
            return (idx % progress_every == 0)
        return True

    def _maybe_log_mem(idx: int):
        if not verbose:
            return
        if mem_log_every and mem_log_every > 0 and idx % mem_log_every == 0:
            _p(_mem_str("   • RAM · "))

    def _maybe_flush_by_thresholds(processed: int):
        if not buffer:
            return
        need_rows = (flush_when_rows is not None and rows_in_buffer >= flush_when_rows)
        need_time = (flush_every_seconds is not None and (time.time() - last_flush_at) >= flush_every_seconds)
        need_periodic = (save_every and processed % save_every == 0)
        if need_rows or need_time or need_periodic:
            _flush()

    # NEW: якщо за діапазон взагалі не прийшли дані — позначаємо дні як виконані
    def _mark_days_done(tk: str, days_list: List[pd.Timestamp]):
        if not use_day_manifest or not days_list:
            return
        df_mark = pd.DataFrame({
            "ticker": str(tk).upper(),
            "dt": [pd.Timestamp(d).strftime("%Y-%m-%d 00:00:00") for d in days_list],
        })
        _append_done_days_manifest(out_dir, df_mark)
        done_days_by_ticker.setdefault(str(tk).upper(), set()).update(
            [pd.Timestamp(d).strftime("%Y-%m-%d") for d in days_list]
        )

    # --- per-ticker worker (respects day-manifest gaps) ---
    def _one(tk: str):
        try:
            # determine which days to fetch
            all_days = all_days_list
            if use_day_manifest:
                done_set = done_days_by_ticker.get(str(tk).upper(), set())
                todo_days = [d for d in all_days if d.strftime("%Y-%m-%d") not in done_set]
            else:
                todo_days = all_days

            if not todo_days:
                return tk, pd.DataFrame(), None

            # group missing days into ranges (capped by chunk_days)
            todo_ranges = _group_consecutive_dates(todo_days, max_span_days=max(1, int(chunk_days)))

            parts: List[pd.DataFrame] = []
            if parallel_chunks and len(todo_ranges) > 1:
                w = max(1, min(int(max_workers_chunks), len(todo_ranges) * (2 if include_blue_ocean else 1)))
                with ThreadPoolExecutor(max_workers=w) as ex:
                    futs = []
                    for (a, b) in todo_ranges:
                        futs.append(ex.submit(
                            _one_call_v3_dt_fast, tk, a, b, interval,
                            chart_type="ohlcv", include_boats=False, normalize_ohlcv=False
                        ))
                        if include_blue_ocean:
                            futs.append(ex.submit(
                                _one_call_blue_ocean_v3_dt_fast, tk, a, b, interval,
                                chart_type="ohlcv", normalize_ohlcv=False
                            ))
                    for f in as_completed(futs):
                        df = f.result()
                        if df is not None and not df.empty:
                            parts.append(df)
            else:
                for (a, b) in todo_ranges:
                    df_main = _one_call_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", include_boats=False, normalize_ohlcv=False)
                    if df_main is not None and not df_main.empty:
                        parts.append(df_main)
                    if include_blue_ocean:
                        df_bo = _one_call_blue_ocean_v3_dt_fast(tk, a, b, interval, chart_type="ohlcv", normalize_ohlcv=False)
                        if df_bo is not None and not df_bo.empty:
                            parts.append(df_bo)

            if not parts:
                # не прийшло даних — позначаємо ці дні відпрацьованими, щоб більше не ходити
                _mark_days_done(tk, todo_days)  # NEW
                return tk, pd.DataFrame(), None

            dfo = pd.concat(parts, ignore_index=True)

            if "dt" in dfo.columns:
                dfo = dfo.drop_duplicates(subset=["ticker","dt"], keep="last")
                dfo = dfo.sort_values(["ticker","dt"], kind="mergesort").reset_index(drop=True)

            # завжди залишаємо 'ticker' та 'dt' (щоб маніфест працював)
            if keep_columns:
                base = ["ticker", "dt"]
                cols = base + [c for c in keep_columns if c in dfo.columns and c not in base]
                cols = [c for c in cols if c in dfo.columns]
                dfo = dfo[cols]

            return tk, dfo, None
        except Exception as e:
            return tk, None, str(e)

    if parallel_tickers:
        with ThreadPoolExecutor(max_workers=max_workers_tickers) as ex:
            futs = {ex.submit(_one, tk): tk for tk in tickers}
            processed = 0
            for f in as_completed(futs):
                tk = futs[f]
                processed += 1
                is_last = (processed == total)
                try:
                    tk_, df, err = f.result()
                except Exception as e:
                    errors.append({"ticker": tk, "error": str(e)})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk}: {e} | {_progress_line(processed)}")
                    _maybe_log_mem(processed)
                    continue

                if err:
                    errors.append({"ticker": tk_, "error": err})
                    if _should_print(processed, True, is_last) and verbose:
                        _p(f"[{processed}/{total}] ✗ {tk_}: {err} | {_progress_line(processed)}")
                else:
                    if df is not None and not df.empty:
                        _append_df_for_buffer(df)
                        _update_day_cache_from_df(df)
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(processed)}")
                    else:
                        if _should_print(processed, False, is_last) and verbose:
                            _p(f"[{processed}/{total}] – {tk_}: empty | {_progress_line(processed)}")

                del df
                gc.collect()
                _maybe_log_mem(processed)
                _maybe_flush_by_thresholds(processed)
    else:
        for i, tk in enumerate(tickers, 1):
            is_last = (i == total)
            tk_, df, err = _one(tk)
            if err:
                errors.append({"ticker": tk_, "error": err})
                if _should_print(i, True, is_last) and verbose:
                    _p(f"[{i}/{total}] ✗ {tk_}: {err} | {_progress_line(i)}")
            else:
                if df is not None and not df.empty:
                    _append_df_for_buffer(df)
                    _update_day_cache_from_df(df)
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] ✓ {tk_}: {len(df):,} рядків | {_progress_line(i)}")
                else:
                    if _should_print(i, False, is_last) and verbose:
                        _p(f"[{i}/{total}] – {tk_}: empty | {_progress_line(i)}")

            del df
            gc.collect()
            _maybe_log_mem(i)
            _maybe_flush_by_thresholds(i)

    _flush()
    total_elapsed = time.time() - start_time
    if verbose:
        _p(_mem_str("   🔚 фінал · "))
        _p(f"🏁 Готово. Нових рядків: {written_total:,} → {out_dir} | Час: {_fmt_eta(total_elapsed)}")
    return pd.DataFrame(errors)

In [16]:
top1500

,ticker,value,lvl3,country,exchange,market_cap
0,A,62213.55,Medical Equipment & Devices,UNITED STATES,New York,31462.0
1,AA,2248598.85,Metals & Mining,UNITED STATES,New York,14893.0
2,AAAU,1150687.46,NaN,NaN,NaN,NaN
3,AACG,3.61,Software,UNITED STATES,NASDAQ CM,32.0
4,AAL,1494863.10,Transportation & Logistics,UNITED STATES,NASDAQ GS,6886.0
...,...,...,...,...,...,...
6927,ZWS,186.38,Machinery,UNITED STATES,New York,7304.0
6928,ZYBT,15.76,Biotech & Pharma,UNITED STATES,NASDAQ CM,33.0
6929,ZYME,42490.18,Biotech & Pharma,UNITED STATES,NASDAQ GS,1732.0
6930,ZYXI,81017.67,NaN,NaN,NaN,NaN
6931,ZYXIQ,81017.67,NaN,NaN,NaN,NaN

In [17]:
import pandas as pd

# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','SOXL']

# створення DataFrame
df = pd.DataFrame(tickers, columns=['ticker'])

print(df)

  ticker
0    SPY
1    IWM
2    GDX
3    XLF
4    QQQ
5    XLE
6    KRE
7   BITO
8   KWEB
9   SOXL

In [18]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=top1500,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=3,
    save_every=50,
    out_dir=str(BATCH_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,
)

▶ Починаємо: 6932 тікерів (пропущено 0 по старому маніфесту) | 2025-12-20 00:00:00 → 2026-03-20 23:59:59 | interval=1 | next batch #1231 | run=0e6451f6

   workers: tickers=3, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2025-12-20 → 2026-03-19 (90 днів)

   📈 обробляються дні: 2026-03-20 → 2026-03-20 (1 днів)

   psutil · старт · 🧠 RAM: 262.6 MB

[10/6932] ✓ AAP: 376 рядків |   0.14% | ETA 27:17

[20/6932] ✓ AAUC: 292 рядків |   0.29% | ETA 23:34

[30/6932] – ABL: empty |   0.43% | ETA 22:29

[40/6932] ✓ ABTS: 5 рядків |   0.58% | ETA 22:39

[50/6932] ✓ ACCL: 29 рядків |   0.72% | ETA 22:02

   • RAM · 🧠 RAM: 277.4 MB

   ⏳ перед flush · 🧠 RAM: 277.4 MB

💾 batch 1231 → 15,279 рядків (всього 15,279 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1231.csv.gz

   ✅ після flush · 🧠 RAM: 280.7 MB

[60/6932] ✓ ACI: 395 рядків |   0.87% | ETA 21:33

[70/6932] ✓ ACNB: 45 рядків |   1.01% | ETA 21:25

[80/6932] ✓ ACWI: 395 рядків |   1.15% | ETA 21:10

[90/6932] ✓ ADEA: 322 рядків |   1.30% | ETA 21:09

[100/6932] ✓ ADT: 394 рядків |   1.44% | ETA 21:05

   • RAM · 🧠 RAM: 281.8 MB

   ⏳ перед flush · 🧠 RAM: 281.8 MB

💾 batch 1232 → 14,513 рядків (всього 29,792 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1232.csv.gz

   ✅ після flush · 🧠 RAM: 283.4 MB

[110/6932] ✓ AEC: 64 рядків |   1.59% | ETA 20:58

[120/6932] ✓ AEO: 411 рядків |   1.73% | ETA 20:53

[130/6932] ✓ AEYE: 155 рядків |   1.88% | ETA 20:44

[140/6932] ✓ AG: 693 рядків |   2.02% | ETA 20:46

[150/6932] ✓ AGIO: 224 рядків |   2.16% | ETA 20:38

   • RAM · 🧠 RAM: 289.6 MB

   ⏳ перед flush · 🧠 RAM: 289.6 MB

💾 batch 1233 → 11,201 рядків (всього 40,993 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1233.csv.gz

   ✅ після flush · 🧠 RAM: 292.8 MB

[160/6932] ✓ AGO: 175 рядків |   2.31% | ETA 20:40

[170/6932] ✓ AHMA: 16 рядків |   2.45% | ETA 20:30

[180/6932] ✓ AIEQ: 11 рядків |   2.60% | ETA 20:28

[190/6932] ✓ AIN: 265 рядків |   2.74% | ETA 20:18

[200/6932] ✓ AIRJ: 184 рядків |   2.89% | ETA 20:17

   • RAM · 🧠 RAM: 289.5 MB

   ⏳ перед flush · 🧠 RAM: 289.5 MB

💾 batch 1234 → 11,298 рядків (всього 52,291 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1234.csv.gz

   ✅ після flush · 🧠 RAM: 293.9 MB

[210/6932] ✓ AIYY: 84 рядків |   3.03% | ETA 20:18

[220/6932] ✓ AL: 367 рядків |   3.17% | ETA 20:13

[230/6932] ✓ ALG: 71 рядків |   3.32% | ETA 20:12

[240/6932] ✓ ALK: 449 рядків |   3.46% | ETA 20:07

[250/6932] ✓ ALMS: 379 рядків |   3.61% | ETA 20:08

   • RAM · 🧠 RAM: 295.8 MB

   ⏳ перед flush · 🧠 RAM: 295.8 MB

💾 batch 1235 → 14,503 рядків (всього 66,794 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1235.csv.gz

   ✅ після flush · 🧠 RAM: 296.7 MB

[260/6932] ✓ ALTO: 368 рядків |   3.75% | ETA 20:07

[270/6932] ✓ AMAT: 524 рядків |   3.89% | ETA 20:02

[280/6932] ✓ AMD: 942 рядків |   4.04% | ETA 20:02

[290/6932] ✓ AMIX: 71 рядків |   4.18% | ETA 19:58

[300/6932] ✓ AMPL: 392 рядків |   4.33% | ETA 19:56

   • RAM · 🧠 RAM: 298.2 MB

   ⏳ перед flush · 🧠 RAM: 298.2 MB

💾 batch 1236 → 14,053 рядків (всього 80,847 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1236.csv.gz

   ✅ після flush · 🧠 RAM: 298.5 MB

[310/6932] ✓ AMT: 398 рядків |   4.47% | ETA 19:56

[320/6932] ✓ AMZD: 345 рядків |   4.62% | ETA 19:51

[330/6932] ✓ ANDE: 216 рядків |   4.76% | ETA 19:49

[340/6932] ✓ ANIK: 100 рядків |   4.90% | ETA 19:49

[350/6932] ✓ ANV: 2 рядків |   5.05% | ETA 19:45

   • RAM · 🧠 RAM: 301.4 MB

   ⏳ перед flush · 🧠 RAM: 301.4 MB

💾 batch 1237 → 12,315 рядків (всього 93,162 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1237.csv.gz

   ✅ після flush · 🧠 RAM: 302.4 MB

[360/6932] ✓ AORT: 200 рядків |   5.19% | ETA 19:44

[370/6932] – APED: empty |   5.34% | ETA 19:43

[380/6932] – APLT: empty |   5.48% | ETA 19:43

[390/6932] ✓ APPS: 389 рядків |   5.63% | ETA 19:44

[400/6932] ✓ AQST: 353 рядків |   5.77% | ETA 19:37

   • RAM · 🧠 RAM: 302.3 MB

   ⏳ перед flush · 🧠 RAM: 302.3 MB

💾 batch 1238 → 12,100 рядків (всього 105,262 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1238.csv.gz

   ✅ після flush · 🧠 RAM: 304.9 MB

[410/6932] ✓ ARCT: 297 рядків |   5.91% | ETA 19:37

[420/6932] ✓ ARHS: 333 рядків |   6.06% | ETA 19:37

[430/6932] ✓ ARKX: 370 рядків |   6.20% | ETA 19:37

[440/6932] ✓ AROC: 355 рядків |   6.35% | ETA 19:35

[450/6932] ✓ ARTY: 307 рядків |   6.49% | ETA 19:36

   • RAM · 🧠 RAM: 303.4 MB

   ⏳ перед flush · 🧠 RAM: 303.4 MB

💾 batch 1239 → 14,708 рядків (всього 119,970 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1239.csv.gz

   ✅ після flush · 🧠 RAM: 304.0 MB

[460/6932] ✓ ASEA: 31 рядків |   6.64% | ETA 19:33

[470/6932] ✓ ASM: 503 рядків |   6.78% | ETA 19:30

[480/6932] ✓ ASPN: 325 рядків |   6.92% | ETA 19:29

[490/6932] ✓ ASTS: 811 рядків |   7.07% | ETA 19:28

[500/6932] ✓ ATER: 31 рядків |   7.21% | ETA 19:25

   • RAM · 🧠 RAM: 305.7 MB

   ⏳ перед flush · 🧠 RAM: 305.7 MB

💾 batch 1240 → 14,058 рядків (всього 134,028 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1240.csv.gz

   ✅ після flush · 🧠 RAM: 307.0 MB

[510/6932] ✓ ATLC: 78 рядків |   7.36% | ETA 19:21

[520/6932] ✓ ATOS: 133 рядків |   7.50% | ETA 19:21

[530/6932] ✓ AU: 596 рядків |   7.65% | ETA 19:19

[540/6932] ✓ AURE: 21 рядків |   7.79% | ETA 19:16

[550/6932] ✓ AVBP: 149 рядків |   7.93% | ETA 19:13

   • RAM · 🧠 RAM: 304.8 MB

   ⏳ перед flush · 🧠 RAM: 304.8 MB

💾 batch 1241 → 9,771 рядків (всього 143,799 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1241.csv.gz

   ✅ після flush · 🧠 RAM: 306.6 MB

[560/6932] ✓ AVGW: 61 рядків |   8.08% | ETA 19:13

[570/6932] ✓ AVNT: 334 рядків |   8.22% | ETA 19:10

[580/6932] ✓ AVUV: 396 рядків |   8.37% | ETA 19:13

[590/6932] ✓ AWR: 174 рядків |   8.51% | ETA 19:09

[600/6932] ✓ AXPG: 9 рядків |   8.66% | ETA 19:08

   • RAM · 🧠 RAM: 306.6 MB

   ⏳ перед flush · 🧠 RAM: 306.6 MB

💾 batch 1242 → 14,986 рядків (всього 158,785 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1242.csv.gz

   ✅ після flush · 🧠 RAM: 308.7 MB

[610/6932] ✓ AZI: 407 рядків |   8.80% | ETA 19:06

[620/6932] ✓ BABO: 72 рядків |   8.94% | ETA 19:06

[630/6932] ✓ BAH: 360 рядків |   9.09% | ETA 19:05

[640/6932] ✓ BANL: 127 рядків |   9.23% | ETA 19:01

[650/6932] ✓ BATT: 64 рядків |   9.38% | ETA 19:02

   • RAM · 🧠 RAM: 303.8 MB

   ⏳ перед flush · 🧠 RAM: 303.8 MB

💾 batch 1243 → 15,270 рядків (всього 174,055 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1243.csv.gz

   ✅ після flush · 🧠 RAM: 303.3 MB

[660/6932] ✓ BBD: 393 рядків |   9.52% | ETA 19:00

[670/6932] ✓ BBNX: 311 рядків |   9.67% | ETA 18:57

[680/6932] ✓ BC: 319 рядків |   9.81% | ETA 18:55

[690/6932] ✓ BCG: 6 рядків |   9.95% | ETA 18:54

[700/6932] ✓ BCSF: 267 рядків |  10.10% | ETA 18:53

   • RAM · 🧠 RAM: 303.1 MB

   ⏳ перед flush · 🧠 RAM: 303.1 MB

💾 batch 1244 → 11,057 рядків (всього 185,112 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1244.csv.gz

   ✅ після flush · 🧠 RAM: 304.3 MB

[710/6932] ✓ BDN: 357 рядків |  10.24% | ETA 18:49

[720/6932] ✓ BEG: 84 рядків |  10.39% | ETA 18:49

[730/6932] ✓ BEPC: 381 рядків |  10.53% | ETA 18:45

[740/6932] ✓ BFAM: 298 рядків |  10.68% | ETA 18:44

[750/6932] ✓ BG: 360 рядків |  10.82% | ETA 18:41

   • RAM · 🧠 RAM: 305.1 MB

   ⏳ перед flush · 🧠 RAM: 305.1 MB

💾 batch 1245 → 10,681 рядків (всього 195,793 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1245.csv.gz

   ✅ після flush · 🧠 RAM: 305.3 MB

[760/6932] ✓ BGS: 377 рядків |  10.96% | ETA 18:37

[770/6932] ✓ BHR: 133 рядків |  11.11% | ETA 18:35

[780/6932] ✓ BIL: 585 рядків |  11.25% | ETA 18:34

[790/6932] ✓ BIRK: 391 рядків |  11.40% | ETA 18:32

[800/6932] ✓ BITW: 124 рядків |  11.54% | ETA 18:31

   • RAM · 🧠 RAM: 306.4 MB

   ⏳ перед flush · 🧠 RAM: 306.4 MB

💾 batch 1246 → 11,531 рядків (всього 207,324 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1246.csv.gz

   ✅ після flush · 🧠 RAM: 307.7 MB

[810/6932] ✓ BJDX: 28 рядків |  11.68% | ETA 18:29

[820/6932] ✓ BKNG: 418 рядків |  11.83% | ETA 18:28

[830/6932] ✓ BLBD: 208 рядків |  11.97% | ETA 18:24

[840/6932] ✓ BLKB: 268 рядків |  12.12% | ETA 18:23

[850/6932] – BLSX: empty |  12.26% | ETA 18:21

   • RAM · 🧠 RAM: 308.7 MB

   ⏳ перед flush · 🧠 RAM: 308.7 MB

💾 batch 1247 → 12,984 рядків (всього 220,308 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1247.csv.gz

   ✅ після flush · 🧠 RAM: 309.1 MB

[860/6932] ✓ BMEZ: 143 рядків |  12.41% | ETA 18:18

[870/6932] ✓ BMO: 364 рядків |  12.55% | ETA 18:17

[880/6932] ✓ BNDI: 25 рядків |  12.69% | ETA 18:16

[890/6932] ✓ BNR: 11 рядків |  12.84% | ETA 18:13

[900/6932] ✓ BOC: 76 рядків |  12.98% | ETA 18:11

   • RAM · 🧠 RAM: 316.6 MB

   ⏳ перед flush · 🧠 RAM: 316.6 MB

💾 batch 1248 → 13,055 рядків (всього 233,363 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1248.csv.gz

   ✅ після flush · 🧠 RAM: 317.2 MB

[910/6932] ✓ BON: 23 рядків |  13.13% | ETA 18:09

[920/6932] ✓ BOW: 187 рядків |  13.27% | ETA 18:06

[930/6932] ✓ BRCC: 272 рядків |  13.42% | ETA 18:07

[940/6932] ✓ BRN: 136 рядків |  13.56% | ETA 18:03

[950/6932] ✓ BRZE: 380 рядків |  13.70% | ETA 18:01

   • RAM · 🧠 RAM: 309.3 MB

   ⏳ перед flush · 🧠 RAM: 309.3 MB

💾 batch 1249 → 11,609 рядків (всього 244,972 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1249.csv.gz

   ✅ після flush · 🧠 RAM: 312.5 MB

[960/6932] ✓ BSOL: 391 рядків |  13.85% | ETA 18:00

[970/6932] ✓ BTBT: 473 рядків |  13.99% | ETA 17:58

[980/6932] ✓ BTDR: 457 рядків |  14.14% | ETA 17:55

[990/6932] ✓ BTMWW: 31 рядків |  14.28% | ETA 17:54

[1000/6932] ✓ BTYB: 3 рядків |  14.43% | ETA 17:51

   • RAM · 🧠 RAM: 305.2 MB

   ⏳ перед flush · 🧠 RAM: 305.2 MB

💾 batch 1250 → 10,809 рядків (всього 255,781 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1250.csv.gz

   ✅ після flush · 🧠 RAM: 305.6 MB

[1010/6932] ✓ BULL: 581 рядків |  14.57% | ETA 17:50

[1020/6932] ✓ BVC: 9 рядків |  14.71% | ETA 17:48

[1030/6932] ✓ BWIN: 476 рядків |  14.86% | ETA 17:47

[1040/6932] ✓ BYAH: 35 рядків |  15.00% | ETA 17:45

[1050/6932] ✓ BZUN: 155 рядків |  15.15% | ETA 17:43

   • RAM · 🧠 RAM: 297.0 MB

   ⏳ перед flush · 🧠 RAM: 297.0 MB

💾 batch 1251 → 12,834 рядків (всього 268,615 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1251.csv.gz

   ✅ після flush · 🧠 RAM: 296.6 MB

[1060/6932] – CADE: empty |  15.29% | ETA 17:42

[1070/6932] ✓ CALC: 127 рядків |  15.44% | ETA 17:40

[1080/6932] ✓ CANG: 227 рядків |  15.58% | ETA 17:39

[1090/6932] ✓ CART: 393 рядків |  15.72% | ETA 17:36

[1100/6932] ✓ CATY: 298 рядків |  15.87% | ETA 17:34

   • RAM · 🧠 RAM: 295.1 MB

   ⏳ перед flush · 🧠 RAM: 295.1 MB

💾 batch 1252 → 11,968 рядків (всього 280,583 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1252.csv.gz

   ✅ після flush · 🧠 RAM: 296.4 MB

[1110/6932] ✓ CBSH: 377 рядків |  16.01% | ETA 17:33

[1120/6932] – CCCX: empty |  16.16% | ETA 17:30

[1130/6932] ✓ CCK: 267 рядків |  16.30% | ETA 17:29

[1140/6932] ✓ CCU: 285 рядків |  16.45% | ETA 17:27

[1150/6932] ✓ CDNS: 415 рядків |  16.59% | ETA 17:25

   • RAM · 🧠 RAM: 296.9 MB

   ⏳ перед flush · 🧠 RAM: 296.9 MB

💾 batch 1253 → 12,781 рядків (всього 293,364 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1253.csv.gz

   ✅ після flush · 🧠 RAM: 297.4 MB

[1160/6932] ✓ CECO: 291 рядків |  16.73% | ETA 17:23

[1170/6932] ✓ CENN: 213 рядків |  16.88% | ETA 17:22

[1180/6932] ✓ CEVA: 274 рядків |  17.02% | ETA 17:20

[1190/6932] ✓ CGC: 463 рядків |  17.17% | ETA 17:18

[1200/6932] ✓ CGIC: 263 рядків |  17.31% | ETA 17:16

   • RAM · 🧠 RAM: 298.9 MB

   ⏳ перед flush · 🧠 RAM: 298.9 MB

💾 batch 1254 → 12,549 рядків (всього 305,913 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1254.csv.gz

   ✅ після flush · 🧠 RAM: 302.2 MB

[1210/6932] ✓ CGW: 42 рядків |  17.46% | ETA 17:16

[1220/6932] ✓ CHDN: 359 рядків |  17.60% | ETA 17:13

[1230/6932] ✓ CHPS: 25 рядків |  17.74% | ETA 17:12

[1240/6932] ✓ CHWY: 431 рядків |  17.89% | ETA 17:10

[1250/6932] – CIFRW: empty |  18.03% | ETA 17:08

   • RAM · 🧠 RAM: 302.6 MB

   ⏳ перед flush · 🧠 RAM: 302.6 MB

💾 batch 1255 → 12,493 рядків (всього 318,406 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1255.csv.gz

   ✅ після flush · 🧠 RAM: 305.6 MB

[1260/6932] – CIMG: empty |  18.18% | ETA 17:07

[1270/6932] ✓ CLB: 235 рядків |  18.32% | ETA 17:05

[1280/6932] ✓ CLIK: 50 рядків |  18.47% | ETA 17:03

[1290/6932] ✓ CLNN: 108 рядків |  18.61% | ETA 17:00

[1300/6932] ✓ CLSX: 215 рядків |  18.75% | ETA 16:59

   • RAM · 🧠 RAM: 307.0 MB

   ⏳ перед flush · 🧠 RAM: 307.0 MB

💾 batch 1256 → 19,564 рядків (всього 337,970 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1256.csv.gz

   ✅ після flush · 🧠 RAM: 308.0 MB

[1310/6932] ✓ CMBT: 392 рядків |  18.90% | ETA 16:57

[1320/6932] ✓ CMG: 521 рядків |  19.04% | ETA 16:55

[1330/6932] ✓ CMS: 397 рядків |  19.19% | ETA 16:53

[1340/6932] ✓ CNI: 393 рядків |  19.33% | ETA 16:52

[1350/6932] ✓ CNQQ: 16 рядків |  19.47% | ETA 16:49

   • RAM · 🧠 RAM: 307.9 MB

   ⏳ перед flush · 🧠 RAM: 307.9 MB

💾 batch 1257 → 17,570 рядків (всього 355,540 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1257.csv.gz

   ✅ після flush · 🧠 RAM: 307.4 MB

[1360/6932] ✓ CNXN: 78 рядків |  19.62% | ETA 16:48

[1370/6932] ✓ COF: 418 рядків |  19.76% | ETA 16:48

[1380/6932] ✓ COIN: 951 рядків |  19.91% | ETA 16:46

[1390/6932] ✓ COMP: 405 рядків |  20.05% | ETA 16:44

[1400/6932] ✓ COPA: 23 рядків |  20.20% | ETA 16:43

   • RAM · 🧠 RAM: 308.4 MB

   ⏳ перед flush · 🧠 RAM: 308.4 MB

💾 batch 1258 → 12,836 рядків (всього 368,376 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1258.csv.gz

   ✅ після flush · 🧠 RAM: 309.9 MB

[1410/6932] – CORX: empty |  20.34% | ETA 16:41

[1420/6932] ✓ COWZ: 393 рядків |  20.48% | ETA 16:39

[1430/6932] ✓ CPIX: 55 рядків |  20.63% | ETA 16:37

[1440/6932] ✓ CPXR: 64 рядків |  20.77% | ETA 16:35

[1450/6932] ✓ CRCA: 611 рядків |  20.92% | ETA 16:33

   • RAM · 🧠 RAM: 311.2 MB

   ⏳ перед flush · 🧠 RAM: 311.2 MB

💾 batch 1259 → 13,444 рядків (всього 381,820 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1259.csv.gz

   ✅ після flush · 🧠 RAM: 311.7 MB

[1460/6932] ✓ CRDU: 268 рядків |  21.06% | ETA 16:32

[1470/6932] ✓ CRH: 457 рядків |  21.21% | ETA 16:30

[1480/6932] ✓ CRMX: 172 рядків |  21.35% | ETA 16:30

[1490/6932] ✓ CRSP: 436 рядків |  21.49% | ETA 16:28

[1500/6932] ✓ CRWU: 420 рядків |  21.64% | ETA 16:26

   • RAM · 🧠 RAM: 312.7 MB

   ⏳ перед flush · 🧠 RAM: 312.7 MB

💾 batch 1260 → 15,197 рядків (всього 397,017 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1260.csv.gz

   ✅ після flush · 🧠 RAM: 315.1 MB

[1510/6932] ✓ CSIQ: 618 рядків |  21.78% | ETA 16:25

[1520/6932] ✓ CTA: 326 рядків |  21.93% | ETA 16:23

[1530/6932] ✓ CTMX: 458 рядків |  22.07% | ETA 16:21

[1540/6932] ✓ CTVA: 397 рядків |  22.22% | ETA 16:19

[1550/6932] ✓ CURI: 172 рядків |  22.36% | ETA 16:17

   • RAM · 🧠 RAM: 307.0 MB

   ⏳ перед flush · 🧠 RAM: 307.0 MB

💾 batch 1261 → 13,310 рядків (всього 410,327 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1261.csv.gz

   ✅ після flush · 🧠 RAM: 307.3 MB

[1560/6932] ✓ CVGW: 146 рядків |  22.50% | ETA 16:15

[1570/6932] ✓ CVU: 81 рядків |  22.65% | ETA 16:13

[1580/6932] ✓ CWEN.A: 276 рядків |  22.79% | ETA 16:11

[1590/6932] ✓ CXAI: 431 рядків |  22.94% | ETA 16:09

[1600/6932] ✓ CYD: 171 рядків |  23.08% | ETA 16:08

   • RAM · 🧠 RAM: 306.4 MB

   ⏳ перед flush · 🧠 RAM: 306.4 MB

💾 batch 1262 → 12,076 рядків (всього 422,403 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1262.csv.gz

   ✅ після flush · 🧠 RAM: 307.6 MB

[1610/6932] ✓ DAC: 64 рядків |  23.23% | ETA 16:06

[1620/6932] ✓ DASH: 438 рядків |  23.37% | ETA 16:05

[1630/6932] ✓ DBD: 227 рядків |  23.51% | ETA 16:03

[1640/6932] ✓ DBVT: 168 рядків |  23.66% | ETA 16:01

[1650/6932] ✓ DCTH: 200 рядків |  23.80% | ETA 15:59

   • RAM · 🧠 RAM: 305.5 MB

   ⏳ перед flush · 🧠 RAM: 305.5 MB

💾 batch 1263 → 13,297 рядків (всього 435,700 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1263.csv.gz

   ✅ після flush · 🧠 RAM: 308.0 MB

[1660/6932] ✓ DDS: 141 рядків |  23.95% | ETA 15:57

[1670/6932] ✓ DERM: 167 рядків |  24.09% | ETA 15:56

[1680/6932] ✓ DFEN: 287 рядків |  24.24% | ETA 15:54

[1690/6932] ✓ DFSV: 383 рядків |  24.38% | ETA 15:53

[1700/6932] ✓ DGS: 136 рядків |  24.52% | ETA 15:50

   • RAM · 🧠 RAM: 308.9 MB

   ⏳ перед flush · 🧠 RAM: 308.9 MB

💾 batch 1264 → 14,574 рядків (всього 450,274 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1264.csv.gz

   ✅ після flush · 🧠 RAM: 309.6 MB

[1710/6932] ✓ DHR: 397 рядків |  24.67% | ETA 15:48

[1720/6932] ✓ DISO: 13 рядків |  24.81% | ETA 15:47

[1730/6932] ✓ DJIA: 131 рядків |  24.96% | ETA 15:45

[1740/6932] – DKUP: empty |  25.10% | ETA 15:43

[1750/6932] – DMAT: empty |  25.25% | ETA 15:41

   • RAM · 🧠 RAM: 310.3 MB

   ⏳ перед flush · 🧠 RAM: 310.3 MB

💾 batch 1265 → 11,596 рядків (всього 461,870 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1265.csv.gz

   ✅ після flush · 🧠 RAM: 311.3 MB

[1760/6932] ✓ DNTH: 281 рядків |  25.39% | ETA 15:39

[1770/6932] ✓ DOLE: 284 рядків |  25.53% | ETA 15:37

[1780/6932] ✓ DOYU: 1,102 рядків |  25.68% | ETA 15:36

[1790/6932] ✓ DRIP: 517 рядків |  25.82% | ETA 15:34

[1800/6932] ✓ DRS: 331 рядків |  25.97% | ETA 15:32

   • RAM · 🧠 RAM: 312.5 MB

   ⏳ перед flush · 🧠 RAM: 312.5 MB

💾 batch 1266 → 14,775 рядків (всього 476,645 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1266.csv.gz

   ✅ після flush · 🧠 RAM: 312.3 MB

[1810/6932] ✓ DSU: 124 рядків |  26.11% | ETA 15:31

[1820/6932] ✓ DTIL: 237 рядків |  26.26% | ETA 15:29

[1830/6932] ✓ DUOT: 262 рядків |  26.40% | ETA 15:28

[1840/6932] ✓ DWSN: 198 рядків |  26.54% | ETA 15:26

[1850/6932] ✓ DXPE: 123 рядків |  26.69% | ETA 15:24

   • RAM · 🧠 RAM: 312.1 MB

   ⏳ перед flush · 🧠 RAM: 312.1 MB

💾 batch 1267 → 12,320 рядків (всього 488,965 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1267.csv.gz

   ✅ після flush · 🧠 RAM: 314.6 MB

[1860/6932] ✓ EA: 391 рядків |  26.83% | ETA 15:22

[1870/6932] ✓ EBMT: 98 рядків |  26.98% | ETA 15:20

[1880/6932] ✓ ECL: 399 рядків |  27.12% | ETA 15:19

[1890/6932] ✓ EDC: 203 рядків |  27.26% | ETA 15:17

[1900/6932] ✓ EDZ: 239 рядків |  27.41% | ETA 15:15

   • RAM · 🧠 RAM: 314.2 MB

   ⏳ перед flush · 🧠 RAM: 314.2 MB

💾 batch 1268 → 11,131 рядків (всього 500,096 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1268.csv.gz

   ✅ після flush · 🧠 RAM: 315.5 MB

[1910/6932] ✓ EFC: 404 рядків |  27.55% | ETA 15:13

[1920/6932] ✓ EGBN: 174 рядків |  27.70% | ETA 15:11

[1930/6932] ✓ EHTH: 268 рядків |  27.84% | ETA 15:10

[1940/6932] ✓ ELA: 238 рядків |  27.99% | ETA 15:08

[1950/6932] ✓ ELMD: 46 рядків |  28.13% | ETA 15:06

   • RAM · 🧠 RAM: 316.4 MB

   ⏳ перед flush · 🧠 RAM: 316.4 MB

💾 batch 1269 → 11,237 рядків (всього 511,333 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1269.csv.gz

   ✅ після flush · 🧠 RAM: 316.6 MB

[1960/6932] ✓ ELVA: 192 рядків |  28.27% | ETA 15:04

[1970/6932] ✓ EMD: 112 рядків |  28.42% | ETA 15:02

[1980/6932] ✓ EMR: 420 рядків |  28.56% | ETA 15:01

[1990/6932] ✓ ENPX: 56 рядків |  28.71% | ETA 14:59

[2000/6932] ✓ ENVB: 27 рядків |  28.85% | ETA 14:57

   • RAM · 🧠 RAM: 317.5 MB

   ⏳ перед flush · 🧠 RAM: 317.5 MB

💾 batch 1270 → 10,756 рядків (всього 522,089 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1270.csv.gz

   ✅ після flush · 🧠 RAM: 319.1 MB

[2010/6932] ✓ EPAM: 343 рядків |  29.00% | ETA 14:56

[2020/6932] ✓ EPRX: 146 рядків |  29.14% | ETA 14:54

[2030/6932] ✓ EQIX: 373 рядків |  29.28% | ETA 14:52

[2040/6932] ✓ ERII: 327 рядків |  29.43% | ETA 14:51

[2050/6932] ✓ ESGD: 288 рядків |  29.57% | ETA 14:50

   • RAM · 🧠 RAM: 321.7 MB

   ⏳ перед flush · 🧠 RAM: 321.7 MB

💾 batch 1271 → 23,551 рядків (всього 545,640 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1271.csv.gz

   ✅ після flush · 🧠 RAM: 325.0 MB

[2060/6932] ✓ ESOA: 136 рядків |  29.72% | ETA 14:48

[2070/6932] ✓ ETCO: 11 рядків |  29.86% | ETA 14:47

[2080/6932] ✓ ETHT: 703 рядків |  30.01% | ETA 14:45

[2090/6932] – ETQ: empty |  30.15% | ETA 14:43

[2100/6932] ✓ EUFN: 385 рядків |  30.29% | ETA 14:42

   • RAM · 🧠 RAM: 318.7 MB

   ⏳ перед flush · 🧠 RAM: 318.7 MB

💾 batch 1272 → 13,196 рядків (всього 558,836 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1272.csv.gz

   ✅ після flush · 🧠 RAM: 319.2 MB

[2110/6932] ✓ EVH: 331 рядків |  30.44% | ETA 14:40

[2120/6932] ✓ EVTL: 283 рядків |  30.58% | ETA 14:38

[2130/6932] ✓ EWG: 404 рядків |  30.73% | ETA 14:37

[2140/6932] ✓ EWQ: 345 рядків |  30.87% | ETA 14:35

[2150/6932] ✓ EXAS: 423 рядків |  31.02% | ETA 14:34

   • RAM · 🧠 RAM: 316.6 MB

   ⏳ перед flush · 🧠 RAM: 316.6 MB

💾 batch 1273 → 18,075 рядків (всього 576,911 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1273.csv.gz

   ✅ після flush · 🧠 RAM: 317.8 MB

[2160/6932] ✓ EXP: 225 рядків |  31.16% | ETA 14:32

[2170/6932] ✓ EZBC: 95 рядків |  31.30% | ETA 14:30

[2180/6932] – FABTQ: empty |  31.45% | ETA 14:29

[2190/6932] – FATAQ: empty |  31.59% | ETA 14:27

[2200/6932] ✓ FBL: 471 рядків |  31.74% | ETA 14:25

   • RAM · 🧠 RAM: 312.7 MB

   ⏳ перед flush · 🧠 RAM: 312.7 MB

💾 batch 1274 → 16,220 рядків (всього 593,131 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1274.csv.gz

   ✅ після flush · 🧠 RAM: 314.8 MB

[2210/6932] ✓ FBYD: 84 рядків |  31.88% | ETA 14:23

[2220/6932] ✓ FCLD: 38 рядків |  32.03% | ETA 14:21

[2230/6932] ✓ FDL: 384 рядків |  32.17% | ETA 14:19

[2240/6932] ✓ FEAT: 10 рядків |  32.31% | ETA 14:18

[2250/6932] ✓ FENI: 377 рядків |  32.46% | ETA 14:16

   • RAM · 🧠 RAM: 314.5 MB

   ⏳ перед flush · 🧠 RAM: 314.5 MB

💾 batch 1275 → 11,550 рядків (всього 604,681 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1275.csv.gz

   ✅ після flush · 🧠 RAM: 314.6 MB

[2260/6932] ✓ FFAI: 594 рядків |  32.60% | ETA 14:14

[2270/6932] ✓ FGMC: 23 рядків |  32.75% | ETA 14:12

[2280/6932] ✓ FIDI: 121 рядків |  32.89% | ETA 14:10

[2290/6932] ✓ FIP: 303 рядків |  33.04% | ETA 14:08

[2300/6932] ✓ FIW: 84 рядків |  33.18% | ETA 14:07

   • RAM · 🧠 RAM: 315.6 MB

   ⏳ перед flush · 🧠 RAM: 315.6 MB

💾 batch 1276 → 12,827 рядків (всього 617,508 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1276.csv.gz

   ✅ після flush · 🧠 RAM: 315.7 MB

[2310/6932] – FLGC: empty |  33.32% | ETA 14:05

[2320/6932] ✓ FLNG: 369 рядків |  33.47% | ETA 14:03

[2330/6932] ✓ FLUT: 418 рядків |  33.61% | ETA 14:01

[2340/6932] ✓ FMAO: 34 рядків |  33.76% | ETA 13:59

[2350/6932] ✓ FNCL: 213 рядків |  33.90% | ETA 13:58

   • RAM · 🧠 RAM: 316.8 MB

   ⏳ перед flush · 🧠 RAM: 316.8 MB

💾 batch 1277 → 11,929 рядків (всього 629,437 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1277.csv.gz

   ✅ після flush · 🧠 RAM: 318.3 MB

[2360/6932] ✓ FNGG: 13 рядків |  34.05% | ETA 13:56

[2370/6932] ✓ FONR: 57 рядків |  34.19% | ETA 13:54

[2380/6932] ✓ FOXF: 304 рядків |  34.33% | ETA 13:52

[2390/6932] ✓ FRHC: 91 рядків |  34.48% | ETA 13:50

[2400/6932] ✓ FRT: 294 рядків |  34.62% | ETA 13:49

   • RAM · 🧠 RAM: 318.8 MB

   ⏳ перед flush · 🧠 RAM: 318.8 MB

💾 batch 1278 → 12,660 рядків (всього 642,097 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1278.csv.gz

   ✅ після flush · 🧠 RAM: 319.2 MB

[2410/6932] ✓ FSUN: 128 рядків |  34.77% | ETA 13:47

[2420/6932] ✓ FTGC: 337 рядків |  34.91% | ETA 13:45

[2430/6932] ✓ FTSM: 261 рядків |  35.05% | ETA 13:43

[2440/6932] ✓ FULT: 386 рядків |  35.20% | ETA 13:41

[2450/6932] ✓ FVRR: 296 рядків |  35.34% | ETA 13:40

   • RAM · 🧠 RAM: 319.7 MB

   ⏳ перед flush · 🧠 RAM: 319.8 MB

💾 batch 1279 → 11,911 рядків (всього 654,008 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1279.csv.gz

   ✅ після flush · 🧠 RAM: 322.3 MB

[2460/6932] ✓ FXC: 50 рядків |  35.49% | ETA 13:39

[2470/6932] ✓ G: 382 рядків |  35.63% | ETA 13:37

[2480/6932] ✓ GATX: 139 рядків |  35.78% | ETA 13:35

[2490/6932] ✓ GBTG: 338 рядків |  35.92% | ETA 13:33

[2500/6932] ✓ GCT: 335 рядків |  36.06% | ETA 13:31

   • RAM · 🧠 RAM: 322.7 MB

   ⏳ перед flush · 🧠 RAM: 322.7 MB

💾 batch 1280 → 10,801 рядків (всього 664,809 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1280.csv.gz

   ✅ після flush · 🧠 RAM: 324.0 MB

[2510/6932] ✓ GDOG: 19 рядків |  36.21% | ETA 13:29

[2520/6932] ✓ GDXY: 502 рядків |  36.35% | ETA 13:28

[2530/6932] ✓ GENB: 247 рядків |  36.50% | ETA 13:26

[2540/6932] ✓ GEVG: 54 рядків |  36.64% | ETA 13:24

[2550/6932] ✓ GGB: 381 рядків |  36.79% | ETA 13:22

   • RAM · 🧠 RAM: 325.3 MB

   ⏳ перед flush · 🧠 RAM: 325.3 MB

💾 batch 1281 → 14,621 рядків (всього 679,430 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1281.csv.gz

   ✅ після flush · 🧠 RAM: 325.5 MB

[2560/6932] ✓ GHI: 249 рядків |  36.93% | ETA 13:21

[2570/6932] ✓ GIII: 258 рядків |  37.07% | ETA 13:19

[2580/6932] ✓ GLBE: 337 рядків |  37.22% | ETA 13:17

[2590/6932] ✓ GLDY: 130 рядків |  37.36% | ETA 13:15

[2600/6932] ✓ GLPG: 144 рядків |  37.51% | ETA 13:14

   • RAM · 🧠 RAM: 326.4 MB

   ⏳ перед flush · 🧠 RAM: 326.4 MB

💾 batch 1282 → 11,379 рядків (всього 690,809 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1282.csv.gz

   ✅ після flush · 🧠 RAM: 329.0 MB

[2610/6932] ✓ GLXY: 499 рядків |  37.65% | ETA 13:12

[2620/6932] – GMGI: empty |  37.80% | ETA 13:10

[2630/6932] ✓ GNR: 388 рядків |  37.94% | ETA 13:08

[2640/6932] ✓ GOCO: 55 рядків |  38.08% | ETA 13:06

[2650/6932] ✓ GOOP: 25 рядків |  38.23% | ETA 13:05

   • RAM · 🧠 RAM: 329.9 MB

   ⏳ перед flush · 🧠 RAM: 329.9 MB

💾 batch 1283 → 11,871 рядків (всього 702,680 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1283.csv.gz

   ✅ після flush · 🧠 RAM: 330.0 MB

[2660/6932] ✓ GOVI: 93 рядків |  38.37% | ETA 13:03

[2670/6932] ✓ GPIX: 360 рядків |  38.52% | ETA 13:01

[2680/6932] ✓ GPZ: 160 рядків |  38.66% | ETA 12:59

[2690/6932] ✓ GREE: 56 рядків |  38.81% | ETA 12:57

[2700/6932] ✓ GRNQ: 21 рядків |  38.95% | ETA 12:56

   • RAM · 🧠 RAM: 321.8 MB

   ⏳ перед flush · 🧠 RAM: 321.8 MB

💾 batch 1284 → 11,874 рядків (всього 714,554 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1284.csv.gz

   ✅ після flush · 🧠 RAM: 322.6 MB

[2710/6932] ✓ GSAT: 329 рядків |  39.09% | ETA 12:54

[2720/6932] ✓ GSUI: 3 рядків |  39.24% | ETA 12:52

[2730/6932] ✓ GTLS: 392 рядків |  39.38% | ETA 12:50

[2740/6932] ✓ GUTS: 281 рядків |  39.53% | ETA 12:48

[2750/6932] ✓ GXAI: 362 рядків |  39.67% | ETA 12:46

   • RAM · 🧠 RAM: 319.8 MB

   ⏳ перед flush · 🧠 RAM: 319.8 MB

💾 batch 1285 → 13,154 рядків (всього 727,708 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1285.csv.gz

   ✅ після flush · 🧠 RAM: 320.1 MB

[2760/6932] ✓ HAIN: 314 рядків |  39.82% | ETA 12:44

[2770/6932] ✓ HBM: 414 рядків |  39.96% | ETA 12:43

[2780/6932] ✓ HCKT: 196 рядків |  40.10% | ETA 12:41

[2790/6932] ✓ HE: 418 рядків |  40.25% | ETA 12:39

[2800/6932] ✓ HERO: 48 рядків |  40.39% | ETA 12:38

   • RAM · 🧠 RAM: 323.2 MB

   ⏳ перед flush · 🧠 RAM: 323.2 MB

💾 batch 1286 → 32,814 рядків (всього 760,522 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1286.csv.gz

   ✅ після flush · 🧠 RAM: 324.8 MB

[2810/6932] ✓ HGV: 303 рядків |  40.54% | ETA 12:36

[2820/6932] ✓ HIMX: 437 рядків |  40.68% | ETA 12:35

[2830/6932] ✓ HIW: 399 рядків |  40.83% | ETA 12:33

[2840/6932] ✓ HLIO: 255 рядків |  40.97% | ETA 12:31

[2850/6932] ✓ HMR: 36 рядків |  41.11% | ETA 12:29

   • RAM · 🧠 RAM: 324.6 MB

   ⏳ перед flush · 🧠 RAM: 324.6 MB

💾 batch 1287 → 20,874 рядків (всього 781,396 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1287.csv.gz

   ✅ після flush · 🧠 RAM: 324.6 MB

[2860/6932] ✓ HOII: 5 рядків |  41.26% | ETA 12:28

[2870/6932] ✓ HOOY: 112 рядків |  41.40% | ETA 12:26

[2880/6932] ✓ HOYY: 26 рядків |  41.55% | ETA 12:24

[2890/6932] ✓ HRI: 227 рядків |  41.69% | ETA 12:22

[2900/6932] ✓ HSDT: 153 рядків |  41.83% | ETA 12:20

   • RAM · 🧠 RAM: 324.7 MB

   ⏳ перед flush · 🧠 RAM: 324.7 MB

💾 batch 1288 → 13,282 рядків (всього 794,678 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1288.csv.gz

   ✅ після flush · 🧠 RAM: 324.7 MB

[2910/6932] ✓ HTD: 142 рядків |  41.98% | ETA 12:18

[2920/6932] ✓ HTZWW: 38 рядків |  42.12% | ETA 12:16

[2930/6932] ✓ HURN: 106 рядків |  42.27% | ETA 12:15

[2940/6932] ✓ HXHX: 36 рядків |  42.41% | ETA 12:13

[2950/6932] ✓ HYLN: 319 рядків |  42.56% | ETA 12:11

   • RAM · 🧠 RAM: 329.5 MB

   ⏳ перед flush · 🧠 RAM: 329.5 MB

💾 batch 1289 → 14,317 рядків (всього 808,995 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1289.csv.gz

   ✅ після flush · 🧠 RAM: 330.6 MB

[2960/6932] ✓ IAGG: 339 рядків |  42.70% | ETA 12:09

[2970/6932] ✓ IAUX: 446 рядків |  42.84% | ETA 12:07

[2980/6932] ✓ IBN: 405 рядків |  42.99% | ETA 12:06

[2990/6932] ✓ IBTM: 104 рядків |  43.13% | ETA 12:04

[3000/6932] ✓ ICLR: 272 рядків |  43.28% | ETA 12:02

   • RAM · 🧠 RAM: 331.1 MB

   ⏳ перед flush · 🧠 RAM: 331.1 MB

💾 batch 1290 → 13,942 рядків (всього 822,937 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1290.csv.gz

   ✅ після flush · 🧠 RAM: 331.2 MB

[3010/6932] ✓ IDCC: 341 рядків |  43.42% | ETA 12:01

[3020/6932] ✓ IDU: 152 рядків |  43.57% | ETA 11:59

[3030/6932] ✓ IEMG: 413 рядків |  43.71% | ETA 11:57

[3040/6932] ✓ IEZ: 328 рядків |  43.85% | ETA 11:56

[3050/6932] ✓ IGLD: 200 рядків |  44.00% | ETA 11:54

   • RAM · 🧠 RAM: 335.9 MB

   ⏳ перед flush · 🧠 RAM: 335.9 MB

💾 batch 1291 → 19,496 рядків (всього 842,433 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1291.csv.gz

   ✅ після flush · 🧠 RAM: 338.6 MB

[3060/6932] ✓ IHF: 208 рядків |  44.14% | ETA 11:52

[3070/6932] ✓ IIPR/PA: 68 рядків |  44.29% | ETA 11:50

[3080/6932] ✓ ILMN: 363 рядків |  44.43% | ETA 11:48

[3090/6932] ✓ IMNM: 377 рядків |  44.58% | ETA 11:46

[3100/6932] ✓ IMTE: 10 рядків |  44.72% | ETA 11:45

   • RAM · 🧠 RAM: 338.9 MB

   ⏳ перед flush · 🧠 RAM: 338.9 MB

💾 batch 1292 → 9,991 рядків (всього 852,424 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1292.csv.gz

   ✅ після flush · 🧠 RAM: 338.9 MB

[3110/6932] ✓ INCO: 89 рядків |  44.86% | ETA 11:43

[3120/6932] – INDV_20260123: empty |  45.01% | ETA 11:41

[3130/6932] ✓ INGR: 265 рядків |  45.15% | ETA 11:39

[3140/6932] ✓ INQQ: 38 рядків |  45.30% | ETA 11:37

[3150/6932] ✓ INTT: 95 рядків |  45.44% | ETA 11:36

   • RAM · 🧠 RAM: 340.2 MB

   ⏳ перед flush · 🧠 RAM: 340.2 MB

💾 batch 1293 → 12,094 рядків (всього 864,518 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1293.csv.gz

   ✅ після flush · 🧠 RAM: 341.2 MB

[3160/6932] ✓ INVH: 396 рядків |  45.59% | ETA 11:34

[3170/6932] ✓ IONZ: 467 рядків |  45.73% | ETA 11:32

[3180/6932] ✓ IPAY: 28 рядків |  45.87% | ETA 11:30

[3190/6932] ✓ IPW: 87 рядків |  46.02% | ETA 11:28

[3200/6932] ✓ IRDM: 404 рядків |  46.16% | ETA 11:26

   • RAM · 🧠 RAM: 342.2 MB

   ⏳ перед flush · 🧠 RAM: 342.2 MB

💾 batch 1294 → 12,440 рядків (всього 876,958 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1294.csv.gz

   ✅ після flush · 🧠 RAM: 342.4 MB

[3210/6932] ✓ IRS: 134 рядків |  46.31% | ETA 11:25

[3220/6932] ✓ ISRA: 29 рядків |  46.45% | ETA 11:23

[3230/6932] ✓ ITDF: 22 рядків |  46.60% | ETA 11:21

[3240/6932] ✓ ITRI: 390 рядків |  46.74% | ETA 11:19

[3250/6932] ✓ IVDA: 151 рядків |  46.88% | ETA 11:17

   • RAM · 🧠 RAM: 335.7 MB

   ⏳ перед flush · 🧠 RAM: 335.7 MB

💾 batch 1295 → 12,457 рядків (всього 889,415 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1295.csv.gz

   ✅ після flush · 🧠 RAM: 335.9 MB

[3260/6932] ✓ IVT: 262 рядків |  47.03% | ETA 11:16

[3270/6932] ✓ IWMI: 314 рядків |  47.17% | ETA 11:14

[3280/6932] ✓ IX: 335 рядків |  47.32% | ETA 11:12

[3290/6932] ✓ IYH: 391 рядків |  47.46% | ETA 11:10

[3300/6932] ✓ IZM: 68 рядків |  47.61% | ETA 11:08

   • RAM · 🧠 RAM: 335.5 MB

   ⏳ перед flush · 🧠 RAM: 335.5 MB

💾 batch 1296 → 16,838 рядків (всього 906,253 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1296.csv.gz

   ✅ після flush · 🧠 RAM: 338.5 MB

[3310/6932] ✓ JAZZ: 257 рядків |  47.75% | ETA 11:07

[3320/6932] ✓ JBSS: 63 рядків |  47.89% | ETA 11:05

[3330/6932] ✓ JEF: 384 рядків |  48.04% | ETA 11:03

[3340/6932] ✓ JFLI: 16 рядків |  48.18% | ETA 11:01

[3350/6932] ✓ JKHY: 295 рядків |  48.33% | ETA 11:00

   • RAM · 🧠 RAM: 338.7 MB

   ⏳ перед flush · 🧠 RAM: 338.7 MB

💾 batch 1297 → 20,855 рядків (всього 927,108 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1297.csv.gz

   ✅ після flush · 🧠 RAM: 341.3 MB

[3360/6932] ✓ JNK: 392 рядків |  48.47% | ETA 10:58

[3370/6932] – JPMO: empty |  48.62% | ETA 10:56

[3380/6932] ✓ JSPR: 148 рядків |  48.76% | ETA 10:54

[3390/6932] ✓ JYD: 6 рядків |  48.90% | ETA 10:53

[3400/6932] ✓ KARS: 29 рядків |  49.05% | ETA 10:51

   • RAM · 🧠 RAM: 335.6 MB

   ⏳ перед flush · 🧠 RAM: 335.6 MB

💾 batch 1298 → 18,889 рядків (всього 945,997 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1298.csv.gz

   ✅ після flush · 🧠 RAM: 337.5 MB

[3410/6932] ✓ KBWB: 399 рядків |  49.19% | ETA 10:49

[3420/6932] ✓ KELYA: 225 рядків |  49.34% | ETA 10:47

[3430/6932] ✓ KGC: 489 рядків |  49.48% | ETA 10:45

[3440/6932] ✓ KIO: 173 рядків |  49.62% | ETA 10:43

[3450/6932] ✓ KLIP: 53 рядків |  49.77% | ETA 10:42

   • RAM · 🧠 RAM: 337.9 MB

   ⏳ перед flush · 🧠 RAM: 337.9 MB

💾 batch 1299 → 14,608 рядків (всього 960,605 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1299.csv.gz

   ✅ після flush · 🧠 RAM: 338.1 MB

[3460/6932] ✓ KMPR: 288 рядків |  49.91% | ETA 10:40

[3470/6932] ✓ KNRX: 105 рядків |  50.06% | ETA 10:38

[3480/6932] ✓ KOLD: 828 рядків |  50.20% | ETA 10:36

[3490/6932] ✓ KPLT: 27 рядків |  50.35% | ETA 10:34

[3500/6932] ✓ KRG: 371 рядків |  50.49% | ETA 10:32

   • RAM · 🧠 RAM: 339.0 MB

   ⏳ перед flush · 🧠 RAM: 339.0 MB

💾 batch 1300 → 12,509 рядків (всього 973,114 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1300.csv.gz

   ✅ після flush · 🧠 RAM: 339.0 MB

[3510/6932] ✓ KRYS: 211 рядків |  50.63% | ETA 10:30

[3520/6932] ✓ KTTA: 169 рядків |  50.78% | ETA 10:29

[3530/6932] ✓ KWM: 77 рядків |  50.92% | ETA 10:27

[3540/6932] ✓ KZIA: 43 рядків |  51.07% | ETA 10:25

[3550/6932] ✓ LAKE: 110 рядків |  51.21% | ETA 10:23

   • RAM · 🧠 RAM: 340.1 MB

   ⏳ перед flush · 🧠 RAM: 340.1 MB

💾 batch 1301 → 12,500 рядків (всього 985,614 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1301.csv.gz

   ✅ після flush · 🧠 RAM: 340.2 MB

[3560/6932] – LAZR: empty |  51.36% | ETA 10:22

[3570/6932] ✓ LBTYB: 25 рядків |  51.50% | ETA 10:20

[3580/6932] ✓ LDI: 375 рядків |  51.64% | ETA 10:18

[3590/6932] ✓ LEN: 410 рядків |  51.79% | ETA 10:16

[3600/6932] ✓ LFS: 82 рядків |  51.93% | ETA 10:14

   • RAM · 🧠 RAM: 341.2 MB

   ⏳ перед flush · 🧠 RAM: 341.2 MB

💾 batch 1302 → 13,247 рядків (всього 998,861 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1302.csv.gz

   ✅ після flush · 🧠 RAM: 343.5 MB

[3610/6932] ✓ LGIH: 343 рядків |  52.08% | ETA 10:12

[3620/6932] ✓ LICN: 2 рядків |  52.22% | ETA 10:10

[3630/6932] ✓ LIMN: 265 рядків |  52.37% | ETA 10:08

[3640/6932] – LITM: empty |  52.51% | ETA 10:07

[3650/6932] ✓ LLYX: 196 рядків |  52.65% | ETA 10:05

   • RAM · 🧠 RAM: 344.6 MB

   ⏳ перед flush · 🧠 RAM: 344.6 MB

💾 batch 1303 → 12,668 рядків (всього 1,011,529 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1303.csv.gz

   ✅ після flush · 🧠 RAM: 344.6 MB

[3660/6932] ✓ LMT: 467 рядків |  52.80% | ETA 10:03

[3670/6932] ✓ LNKS: 717 рядків |  52.94% | ETA 10:01

[3680/6932] ✓ LOMA: 195 рядків |  53.09% | ETA 10:00

[3690/6932] ✓ LPG: 289 рядків |  53.23% | ETA 09:58

[3700/6932] ✓ LRCU: 137 рядків |  53.38% | ETA 09:56

   • RAM · 🧠 RAM: 345.6 MB

   ⏳ перед flush · 🧠 RAM: 345.6 MB

💾 batch 1304 → 11,174 рядків (всього 1,022,703 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1304.csv.gz

   ✅ після flush · 🧠 RAM: 346.6 MB

[3710/6932] ✓ LSPD: 308 рядків |  53.52% | ETA 09:54

[3720/6932] ✓ LU: 395 рядків |  53.66% | ETA 09:52

[3730/6932] ✓ LUNL: 315 рядків |  53.81% | ETA 09:50

[3740/6932] ✓ LVS: 393 рядків |  53.95% | ETA 09:49

[3750/6932] ✓ LXU: 385 рядків |  54.10% | ETA 09:47

   • RAM · 🧠 RAM: 347.7 MB

   ⏳ перед flush · 🧠 RAM: 347.7 MB

💾 batch 1305 → 11,774 рядків (всього 1,034,477 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1305.csv.gz

   ✅ після flush · 🧠 RAM: 348.0 MB

[3760/6932] ✓ LZB: 245 рядків |  54.24% | ETA 09:45

[3770/6932] ✓ MAGC: 6 рядків |  54.39% | ETA 09:43

[3780/6932] ✓ MANE: 223 рядків |  54.53% | ETA 09:41

[3790/6932] ✓ MASI: 372 рядків |  54.67% | ETA 09:40

[3800/6932] ✓ MAXN: 99 рядків |  54.82% | ETA 09:38

   • RAM · 🧠 RAM: 343.8 MB

   ⏳ перед flush · 🧠 RAM: 343.8 MB

💾 batch 1306 → 11,859 рядків (всього 1,046,336 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1306.csv.gz

   ✅ після flush · 🧠 RAM: 343.9 MB

[3810/6932] ✓ MBRX: 92 рядків |  54.96% | ETA 09:36

[3820/6932] ✓ MCHB: 186 рядків |  55.11% | ETA 09:34

[3830/6932] ✓ MCW: 380 рядків |  55.25% | ETA 09:32

[3840/6932] ✓ MDLZ: 420 рядків |  55.40% | ETA 09:30

[3850/6932] ✓ MEGL: 9 рядків |  55.54% | ETA 09:29

   • RAM · 🧠 RAM: 343.2 MB

   ⏳ перед flush · 🧠 RAM: 343.2 MB

💾 batch 1307 → 12,115 рядків (всього 1,058,451 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1307.csv.gz

   ✅ після flush · 🧠 RAM: 346.6 MB

[3860/6932] ✓ META: 901 рядків |  55.68% | ETA 09:27

[3870/6932] ✓ MFC: 397 рядків |  55.83% | ETA 09:25

[3880/6932] – MGIC: empty |  55.97% | ETA 09:23

[3890/6932] ✓ MGRT: 15 рядків |  56.12% | ETA 09:21

[3900/6932] ✓ MIAX: 287 рядків |  56.26% | ETA 09:20

   • RAM · 🧠 RAM: 346.1 MB

   ⏳ перед flush · 🧠 RAM: 346.1 MB

💾 batch 1308 → 11,885 рядків (всього 1,070,336 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1308.csv.gz

   ✅ після flush · 🧠 RAM: 346.1 MB

[3910/6932] ✓ MIR: 384 рядків |  56.41% | ETA 09:18

[3920/6932] ✓ MKDW: 53 рядків |  56.55% | ETA 09:16

[3930/6932] ✓ MLGO: 107 рядків |  56.69% | ETA 09:14

[3940/6932] ✓ MLTX: 272 рядків |  56.84% | ETA 09:12

[3950/6932] ✓ MNDY: 355 рядків |  56.98% | ETA 09:10

   • RAM · 🧠 RAM: 331.4 MB

   ⏳ перед flush · 🧠 RAM: 331.4 MB

💾 batch 1309 → 10,732 рядків (всього 1,081,068 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1309.csv.gz

   ✅ після flush · 🧠 RAM: 331.4 MB

[3960/6932] ✓ MNST: 412 рядків |  57.13% | ETA 09:09

[3970/6932] ✓ MOBX: 1,123 рядків |  57.27% | ETA 09:07

[3980/6932] ✓ MORN: 250 рядків |  57.41% | ETA 09:05

[3990/6932] ✓ MPG: 52 рядків |  57.56% | ETA 09:03

[4000/6932] ✓ MRAL: 436 рядків |  57.70% | ETA 09:01

   • RAM · 🧠 RAM: 329.7 MB

   ⏳ перед flush · 🧠 RAM: 329.7 MB

💾 batch 1310 → 11,647 рядків (всього 1,092,715 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1310.csv.gz

   ✅ після flush · 🧠 RAM: 330.8 MB

[4010/6932] ✓ MRM: 46 рядків |  57.85% | ETA 08:59

[4020/6932] ✓ MRVI: 330 рядків |  57.99% | ETA 08:58

[4030/6932] ✓ MSDD: 9 рядків |  58.14% | ETA 08:56

[4040/6932] ✓ MSFY: 20 рядків |  58.28% | ETA 08:54

[4050/6932] ✓ MSOS: 466 рядків |  58.42% | ETA 08:52

   • RAM · 🧠 RAM: 331.9 MB

   ⏳ перед flush · 🧠 RAM: 331.9 MB

💾 batch 1311 → 11,450 рядків (всього 1,104,165 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1311.csv.gz

   ✅ після flush · 🧠 RAM: 333.9 MB

[4060/6932] ✓ MSTY: 498 рядків |  58.57% | ETA 08:51

[4070/6932] ✓ MTD: 402 рядків |  58.71% | ETA 08:49

[4080/6932] ✓ MTNB: 15 рядків |  58.86% | ETA 08:47

[4090/6932] ✓ MUB: 391 рядків |  59.00% | ETA 08:45

[4100/6932] ✓ MVLL: 139 рядків |  59.15% | ETA 08:43

   • RAM · 🧠 RAM: 334.3 MB

   ⏳ перед flush · 🧠 RAM: 334.3 MB

💾 batch 1312 → 17,244 рядків (всього 1,121,409 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1312.csv.gz

   ✅ після flush · 🧠 RAM: 336.2 MB

[4110/6932] ✓ MXCT: 260 рядків |  59.29% | ETA 08:41

[4120/6932] ✓ MYSE: 36 рядків |  59.43% | ETA 08:40

[4130/6932] ✓ NAK: 443 рядків |  59.58% | ETA 08:38

[4140/6932] ✓ NATR: 67 рядків |  59.72% | ETA 08:36

[4150/6932] ✓ NBN: 109 рядків |  59.87% | ETA 08:34

   • RAM · 🧠 RAM: 336.4 MB

   ⏳ перед flush · 🧠 RAM: 336.4 MB

💾 batch 1313 → 11,296 рядків (всього 1,132,705 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1313.csv.gz

   ✅ після flush · 🧠 RAM: 337.6 MB

[4160/6932] ✓ NCIQ: 17 рядків |  60.01% | ETA 08:32

[4170/6932] ✓ NDAQ: 416 рядків |  60.16% | ETA 08:30

[4180/6932] ✓ NEGG: 55 рядків |  60.30% | ETA 08:29

[4190/6932] ✓ NERD: 7 рядків |  60.44% | ETA 08:27

[4200/6932] ✓ NEXA: 295 рядків |  60.59% | ETA 08:25

   • RAM · 🧠 RAM: 338.6 MB

   ⏳ перед flush · 🧠 RAM: 338.6 MB

💾 batch 1314 → 9,547 рядків (всього 1,142,252 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1314.csv.gz

   ✅ після flush · 🧠 RAM: 339.7 MB

[4210/6932] ✓ NFLW: 29 рядків |  60.73% | ETA 08:23

[4220/6932] ✓ NGL: 173 рядків |  60.88% | ETA 08:21

[4230/6932] ✓ NIHI: 147 рядків |  61.02% | ETA 08:20

[4240/6932] ✓ NIU: 237 рядків |  61.17% | ETA 08:18

[4250/6932] ✓ NLY: 471 рядків |  61.31% | ETA 08:16

   • RAM · 🧠 RAM: 340.8 MB

   ⏳ перед flush · 🧠 RAM: 340.8 MB

💾 batch 1315 → 11,859 рядків (всього 1,154,111 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1315.csv.gz

   ✅ після flush · 🧠 RAM: 341.9 MB

[4260/6932] ✓ NMZ: 189 рядків |  61.45% | ETA 08:14

[4270/6932] ✓ NOA: 165 рядків |  61.60% | ETA 08:12

[4280/6932] ✓ NOVT: 239 рядків |  61.74% | ETA 08:11

[4290/6932] ✓ NRDY: 167 рядків |  61.89% | ETA 08:09

[4300/6932] ✓ NRO: 191 рядків |  62.03% | ETA 08:07

   • RAM · 🧠 RAM: 343.0 MB

   ⏳ перед flush · 🧠 RAM: 343.0 MB

💾 batch 1316 → 12,878 рядків (всього 1,166,989 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1316.csv.gz

   ✅ після flush · 🧠 RAM: 343.1 MB

[4310/6932] ✓ NTCL: 138 рядків |  62.18% | ETA 08:05

[4320/6932] ✓ NTRS: 298 рядків |  62.32% | ETA 08:03

[4330/6932] ✓ NUGY: 71 рядків |  62.46% | ETA 08:02

[4340/6932] ✓ NVAX: 445 рядків |  62.61% | ETA 08:00

[4350/6932] ✓ NVDQ: 491 рядків |  62.75% | ETA 07:58

   • RAM · 🧠 RAM: 342.9 MB

   ⏳ перед flush · 🧠 RAM: 342.9 MB

💾 batch 1317 → 15,016 рядків (всього 1,182,005 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1317.csv.gz

   ✅ після flush · 🧠 RAM: 343.7 MB

[4360/6932] ✓ NVNI: 48 рядків |  62.90% | ETA 07:57

[4370/6932] ✓ NVT: 389 рядків |  63.04% | ETA 07:55

[4380/6932] ✓ NWGL: 98 рядків |  63.19% | ETA 07:53

[4390/6932] ✓ NXE: 423 рядків |  63.33% | ETA 07:51

[4400/6932] ✓ NXXT: 450 рядків |  63.47% | ETA 07:49

   • RAM · 🧠 RAM: 340.4 MB

   ⏳ перед flush · 🧠 RAM: 340.4 MB

💾 batch 1318 → 13,994 рядків (всього 1,195,999 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1318.csv.gz

   ✅ після flush · 🧠 RAM: 342.2 MB

[4410/6932] ✓ OBIL: 42 рядків |  63.62% | ETA 07:48

[4420/6932] ✓ OCGN: 525 рядків |  63.76% | ETA 07:46

[4430/6932] ✓ OEC: 294 рядків |  63.91% | ETA 07:44

[4440/6932] ✓ OHI: 392 рядків |  64.05% | ETA 07:42

[4450/6932] ✓ OKLL: 840 рядків |  64.20% | ETA 07:41

   • RAM · 🧠 RAM: 342.0 MB

   ⏳ перед flush · 🧠 RAM: 342.0 MB

💾 batch 1319 → 12,889 рядків (всього 1,208,888 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1319.csv.gz

   ✅ після flush · 🧠 RAM: 342.9 MB

[4460/6932] ✓ OLN: 396 рядків |  64.34% | ETA 07:39

[4470/6932] ✓ OMH: 12 рядків |  64.48% | ETA 07:37

[4480/6932] ✓ ONDL: 469 рядків |  64.63% | ETA 07:35

[4490/6932] ✓ ONON: 418 рядків |  64.77% | ETA 07:33

[4500/6932] ✓ OPENW: 147 рядків |  64.92% | ETA 07:31

   • RAM · 🧠 RAM: 335.8 MB

   ⏳ перед flush · 🧠 RAM: 335.8 MB

💾 batch 1320 → 13,195 рядків (всього 1,222,083 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1320.csv.gz

   ✅ після flush · 🧠 RAM: 336.5 MB

[4510/6932] ✓ OPRX: 189 рядків |  65.06% | ETA 07:30

[4520/6932] ✓ ORCS: 51 рядків |  65.20% | ETA 07:28

[4530/6932] ✓ ORKT: 49 рядків |  65.35% | ETA 07:26

[4540/6932] ✓ OSCX: 43 рядків |  65.49% | ETA 07:24

[4550/6932] ✓ OTF: 398 рядків |  65.64% | ETA 07:22

   • RAM · 🧠 RAM: 333.3 MB

   ⏳ перед flush · 🧠 RAM: 333.3 MB

💾 batch 1321 → 13,872 рядків (всього 1,235,955 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1321.csv.gz

   ✅ після flush · 🧠 RAM: 334.2 MB

[4560/6932] ✓ OVID: 464 рядків |  65.78% | ETA 07:21

[4570/6932] ✓ OZEM: 35 рядків |  65.93% | ETA 07:19

[4580/6932] ✓ PAG: 190 рядків |  66.07% | ETA 07:17

[4590/6932] ✓ PANL: 257 рядків |  66.21% | ETA 07:15

[4600/6932] ✓ PATX: 32 рядків |  66.36% | ETA 07:13

   • RAM · 🧠 RAM: 335.3 MB

   ⏳ перед flush · 🧠 RAM: 335.3 MB

💾 batch 1322 → 13,539 рядків (всього 1,249,494 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1322.csv.gz

   ✅ після flush · 🧠 RAM: 335.5 MB

[4610/6932] ✓ PAYS: 176 рядків |  66.50% | ETA 07:12

[4620/6932] ✓ PBR: 616 рядків |  66.65% | ETA 07:10

[4630/6932] ✓ PCLA: 19 рядків |  66.79% | ETA 07:08

[4640/6932] ✓ PD: 376 рядків |  66.94% | ETA 07:06

[4650/6932] ✓ PDO: 365 рядків |  67.08% | ETA 07:04

   • RAM · 🧠 RAM: 336.6 MB

   ⏳ перед flush · 🧠 RAM: 336.6 MB

💾 batch 1323 → 13,162 рядків (всього 1,262,656 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1323.csv.gz

   ✅ після flush · 🧠 RAM: 337.3 MB

[4660/6932] ✓ PEGA: 379 рядків |  67.22% | ETA 07:02

[4670/6932] ✓ PERI: 323 рядків |  67.37% | ETA 07:01

[4680/6932] ✓ PFFD: 288 рядків |  67.51% | ETA 06:59

[4690/6932] ✓ PFSI: 196 рядків |  67.66% | ETA 06:57

[4700/6932] ✓ PH: 369 рядків |  67.80% | ETA 06:55

   • RAM · 🧠 RAM: 338.1 MB

   ⏳ перед flush · 🧠 RAM: 338.1 MB

💾 batch 1324 → 13,379 рядків (всього 1,276,035 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1324.csv.gz

   ✅ після flush · 🧠 RAM: 338.8 MB

[4710/6932] ✓ PHUN: 170 рядків |  67.95% | ETA 06:53

[4720/6932] ✓ PIII: 25 рядків |  68.09% | ETA 06:51

[4730/6932] ✓ PKG: 339 рядків |  68.23% | ETA 06:50

[4740/6932] ✓ PLD: 391 рядків |  68.38% | ETA 06:48

[4750/6932] ✓ PLTA: 41 рядків |  68.52% | ETA 06:46

   • RAM · 🧠 RAM: 344.8 MB

   ⏳ перед flush · 🧠 RAM: 344.8 MB

💾 batch 1325 → 10,885 рядків (всього 1,286,920 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1325.csv.gz

   ✅ після flush · 🧠 RAM: 347.5 MB

[4760/6932] ✓ PLTZ: 430 рядків |  68.67% | ETA 06:44

[4770/6932] ✓ PM: 414 рядків |  68.81% | ETA 06:42

[4780/6932] ✓ PMVP: 137 рядків |  68.96% | ETA 06:40

[4790/6932] ✓ PNTG: 144 рядків |  69.10% | ETA 06:39

[4800/6932] ✓ POR: 336 рядків |  69.24% | ETA 06:37

   • RAM · 🧠 RAM: 349.2 MB

   ⏳ перед flush · 🧠 RAM: 349.2 MB

💾 batch 1326 → 12,236 рядків (всього 1,299,156 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1326.csv.gz

   ✅ після flush · 🧠 RAM: 351.2 MB

[4810/6932] ✓ PPG: 395 рядків |  69.39% | ETA 06:35

[4820/6932] ✓ PRAX: 216 рядків |  69.53% | ETA 06:33

[4830/6932] ✓ PRI: 292 рядків |  69.68% | ETA 06:31

[4840/6932] ✓ PROK: 290 рядків |  69.82% | ETA 06:29

[4850/6932] ✓ PRTS: 107 рядків |  69.97% | ETA 06:27

   • RAM · 🧠 RAM: 353.0 MB

   ⏳ перед flush · 🧠 RAM: 353.0 MB

💾 batch 1327 → 13,184 рядків (всього 1,312,340 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1327.csv.gz

   ✅ після flush · 🧠 RAM: 353.0 MB

[4860/6932] ✓ PSIL: 16 рядків |  70.11% | ETA 06:26

[4870/6932] ✓ PSQ: 585 рядків |  70.25% | ETA 06:24

[4880/6932] ✓ PTGX: 313 рядків |  70.40% | ETA 06:22

[4890/6932] ✓ PTRB: 96 рядків |  70.54% | ETA 06:20

[4900/6932] ✓ PVL: 75 рядків |  70.69% | ETA 06:18

   • RAM · 🧠 RAM: 352.3 MB

   ⏳ перед flush · 🧠 RAM: 352.3 MB

💾 batch 1328 → 13,656 рядків (всього 1,325,996 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1328.csv.gz

   ✅ після flush · 🧠 RAM: 352.5 MB

[4910/6932] – PXIU: empty |  70.83% | ETA 06:16

[4920/6932] ✓ PZG: 358 рядків |  70.98% | ETA 06:14

[4930/6932] ✓ QCMD: 1 рядків |  71.12% | ETA 06:13

[4940/6932] ✓ QETH: 104 рядків |  71.26% | ETA 06:11

[4950/6932] ✓ QMCO: 163 рядків |  71.41% | ETA 06:09

   • RAM · 🧠 RAM: 351.1 MB

   ⏳ перед flush · 🧠 RAM: 351.1 MB

💾 batch 1329 → 10,963 рядків (всього 1,336,959 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1329.csv.gz

   ✅ після flush · 🧠 RAM: 352.2 MB

[4960/6932] ✓ QQQ: 1,197 рядків |  71.55% | ETA 06:07

[4970/6932] ✓ QQQU: 96 рядків |  71.70% | ETA 06:05

[4980/6932] ✓ QSR: 395 рядків |  71.84% | ETA 06:03

[4990/6932] ✓ QUBX: 113 рядків |  71.98% | ETA 06:02

[5000/6932] ✓ RA: 121 рядків |  72.13% | ETA 06:00

   • RAM · 🧠 RAM: 351.7 MB

   ⏳ перед flush · 🧠 RAM: 351.7 MB

💾 batch 1330 → 13,082 рядків (всього 1,350,041 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1330.csv.gz

   ✅ після flush · 🧠 RAM: 351.8 MB

[5010/6932] ✓ RANI: 320 рядків |  72.27% | ETA 05:58

[5020/6932] ✓ RBLU: 151 рядків |  72.42% | ETA 05:56

[5030/6932] ✓ RCI: 375 рядків |  72.56% | ETA 05:54

[5040/6932] ✓ RDI: 13 рядків |  72.71% | ETA 05:52

[5050/6932] ✓ RDWR: 267 рядків |  72.85% | ETA 05:51

   • RAM · 🧠 RAM: 347.6 MB

   ⏳ перед flush · 🧠 RAM: 347.6 MB

💾 batch 1331 → 19,043 рядків (всього 1,369,084 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1331.csv.gz

   ✅ після flush · 🧠 RAM: 350.4 MB

[5060/6932] ✓ REET: 385 рядків |  72.99% | ETA 05:49

[5070/6932] ✓ RELL: 124 рядків |  73.14% | ETA 05:47

[5080/6932] ✓ RES: 376 рядків |  73.28% | ETA 05:45

[5090/6932] ✓ RFIL: 196 рядків |  73.43% | ETA 05:43

[5100/6932] ✓ RGNX: 295 рядків |  73.57% | ETA 05:41

   • RAM · 🧠 RAM: 345.7 MB

   ⏳ перед flush · 🧠 RAM: 345.7 MB

💾 batch 1332 → 11,678 рядків (всього 1,380,762 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1332.csv.gz

   ✅ після flush · 🧠 RAM: 345.7 MB

[5110/6932] ✓ RHLD: 167 рядків |  73.72% | ETA 05:40

[5120/6932] ✓ RIO: 472 рядків |  73.86% | ETA 05:38

[5130/6932] ✓ RKLX: 808 рядків |  74.00% | ETA 05:36

[5140/6932] ✓ RLX: 363 рядків |  74.15% | ETA 05:34

[5150/6932] ✓ RMSG: 22 рядків |  74.29% | ETA 05:32

   • RAM · 🧠 RAM: 346.1 MB

   ⏳ перед flush · 🧠 RAM: 346.1 MB

💾 batch 1333 → 15,177 рядків (всього 1,395,939 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1333.csv.gz

   ✅ після flush · 🧠 RAM: 346.6 MB

[5160/6932] ✓ RNST: 262 рядків |  74.44% | ETA 05:30

[5170/6932] ✓ ROG: 121 рядків |  74.58% | ETA 05:28

[5180/6932] ✓ ROOT: 259 рядків |  74.73% | ETA 05:27

[5190/6932] – RPTX: empty |  74.87% | ETA 05:25

[5200/6932] ✓ RSG: 359 рядків |  75.01% | ETA 05:23

   • RAM · 🧠 RAM: 347.8 MB

   ⏳ перед flush · 🧠 RAM: 347.8 MB

💾 batch 1334 → 12,213 рядків (всього 1,408,152 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1334.csv.gz

   ✅ після flush · 🧠 RAM: 348.9 MB

[5210/6932] ✓ RTAC: 96 рядків |  75.16% | ETA 05:21

[5220/6932] ✓ RUSHB: 32 рядків |  75.30% | ETA 05:19

[5230/6932] ✓ RVTY: 267 рядків |  75.45% | ETA 05:17

[5240/6932] ✓ RXT: 513 рядків |  75.59% | ETA 05:16

[5250/6932] ✓ RYOJ: 8 рядків |  75.74% | ETA 05:14

   • RAM · 🧠 RAM: 349.7 MB

   ⏳ перед flush · 🧠 RAM: 349.7 MB

💾 batch 1335 → 12,026 рядків (всього 1,420,178 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1335.csv.gz

   ✅ після flush · 🧠 RAM: 352.8 MB

[5260/6932] ✓ SAFT: 131 рядків |  75.88% | ETA 05:12

[5270/6932] ✓ SANA: 378 рядків |  76.02% | ETA 05:10

[5280/6932] – SAVA: empty |  76.17% | ETA 05:08

[5290/6932] ✓ SBIO: 33 рядків |  76.31% | ETA 05:06

[5300/6932] ✓ SBU: 3 рядків |  76.46% | ETA 05:04

   • RAM · 🧠 RAM: 354.2 MB

   ⏳ перед flush · 🧠 RAM: 354.2 MB

💾 batch 1336 → 13,979 рядків (всього 1,434,157 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1336.csv.gz

   ✅ після flush · 🧠 RAM: 355.7 MB

[5310/6932] ✓ SCHD: 869 рядків |  76.60% | ETA 05:03

[5320/6932] ✓ SCHP: 390 рядків |  76.75% | ETA 05:01

[5330/6932] ✓ SCKT: 19 рядків |  76.89% | ETA 04:59

[5340/6932] ✓ SCVL: 226 рядків |  77.03% | ETA 04:57

[5350/6932] ✓ SDOT: 18 рядків |  77.18% | ETA 04:55

   • RAM · 🧠 RAM: 357.2 MB

   ⏳ перед flush · 🧠 RAM: 357.2 MB

💾 batch 1337 → 14,868 рядків (всього 1,449,025 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1337.csv.gz

   ✅ після flush · 🧠 RAM: 357.6 MB

[5360/6932] ✓ SEAT: 82 рядків |  77.32% | ETA 04:53

[5370/6932] ✓ SEMR: 289 рядків |  77.47% | ETA 04:52

[5380/6932] ✓ SETM: 297 рядків |  77.61% | ETA 04:50

[5390/6932] ✓ SFNC: 373 рядків |  77.76% | ETA 04:48

[5400/6932] ✓ SGHC: 374 рядків |  77.90% | ETA 04:46

   • RAM · 🧠 RAM: 358.6 MB

   ⏳ перед flush · 🧠 RAM: 358.6 MB

💾 batch 1338 → 12,620 рядків (всього 1,461,645 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1338.csv.gz

   ✅ після flush · 🧠 RAM: 358.9 MB

[5410/6932] ✓ SGRT: 44 рядків |  78.04% | ETA 04:44

[5420/6932] ✓ SHFS: 26 рядків |  78.19% | ETA 04:42

[5430/6932] ✓ SHOC: 29 рядків |  78.33% | ETA 04:40

[5440/6932] ✓ SIBN: 207 рядків |  78.48% | ETA 04:39

[5450/6932] ✓ SIL: 524 рядків |  78.62% | ETA 04:37

   • RAM · 🧠 RAM: 360.5 MB

   ⏳ перед flush · 🧠 RAM: 360.5 MB

💾 batch 1339 → 14,242 рядків (всього 1,475,887 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1339.csv.gz

   ✅ після flush · 🧠 RAM: 363.1 MB

[5460/6932] ✓ SITC: 301 рядків |  78.77% | ETA 04:35

[5470/6932] ✓ SKF: 80 рядків |  78.91% | ETA 04:33

[5480/6932] ✓ SKY: 299 рядків |  79.05% | ETA 04:31

[5490/6932] ✓ SLDE: 338 рядків |  79.20% | ETA 04:29

[5500/6932] ✓ SLMT: 247 рядків |  79.34% | ETA 04:27

   • RAM · 🧠 RAM: 360.5 MB

   ⏳ перед flush · 🧠 RAM: 360.5 MB

💾 batch 1340 → 11,930 рядків (всього 1,487,817 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1340.csv.gz

   ✅ після flush · 🧠 RAM: 362.3 MB

[5510/6932] – SLRX: empty |  79.49% | ETA 04:26

[5520/6932] ✓ SLVP: 389 рядків |  79.63% | ETA 04:24

[5530/6932] – SMCC: empty |  79.77% | ETA 04:22

[5540/6932] ✓ SMHB: 26 рядків |  79.92% | ETA 04:20

[5550/6932] ✓ SMRF: 6 рядків |  80.06% | ETA 04:18

   • RAM · 🧠 RAM: 362.0 MB

   ⏳ перед flush · 🧠 RAM: 362.0 MB

💾 batch 1341 → 16,160 рядків (всього 1,503,977 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1341.csv.gz

   ✅ після flush · 🧠 RAM: 362.6 MB

[5560/6932] ✓ SMXT: 108 рядків |  80.21% | ETA 04:17

[5570/6932] ✓ SNBR: 306 рядків |  80.35% | ETA 04:15

[5580/6932] ✓ SNGX: 54 рядків |  80.50% | ETA 04:13

[5590/6932] ✓ SNT: 10 рядків |  80.64% | ETA 04:11

[5600/6932] ✓ SO: 396 рядків |  80.78% | ETA 04:09

   • RAM · 🧠 RAM: 359.3 MB

   ⏳ перед flush · 🧠 RAM: 359.3 MB

💾 batch 1342 → 11,498 рядків (всього 1,515,475 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1342.csv.gz

   ✅ після flush · 🧠 RAM: 362.7 MB

[5610/6932] ✓ SOFX: 411 рядків |  80.93% | ETA 04:07

[5620/6932] ✓ SONO: 339 рядків |  81.07% | ETA 04:05

[5630/6932] ✓ SOWG: 60 рядків |  81.22% | ETA 04:03

[5640/6932] ✓ SPCB: 62 рядків |  81.36% | ETA 04:01

[5650/6932] ✓ SPG: 380 рядків |  81.51% | ETA 03:59

   • RAM · 🧠 RAM: 358.4 MB

   ⏳ перед flush · 🧠 RAM: 358.7 MB

💾 batch 1343 → 13,239 рядків (всього 1,528,714 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1343.csv.gz

   ✅ після flush · 🧠 RAM: 361.5 MB

[5660/6932] ✓ SPIB: 329 рядків |  81.65% | ETA 03:57

[5670/6932] ✓ SPOK: 156 рядків |  81.79% | ETA 03:55

[5680/6932] ✓ SPSB: 359 рядків |  81.94% | ETA 03:53

[5690/6932] ✓ SPUU: 72 рядків |  82.08% | ETA 03:51

[5700/6932] ✓ SPYD: 412 рядків |  82.23% | ETA 03:49

   • RAM · 🧠 RAM: 359.5 MB

   ⏳ перед flush · 🧠 RAM: 359.5 MB

💾 batch 1344 → 15,256 рядків (всього 1,543,970 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1344.csv.gz

   ✅ після flush · 🧠 RAM: 362.2 MB

[5710/6932] ✓ SQM: 291 рядків |  82.37% | ETA 03:47

[5720/6932] ✓ SRPT: 401 рядків |  82.52% | ETA 03:46

[5730/6932] ✓ SSD: 196 рядків |  82.66% | ETA 03:44

[5740/6932] ✓ SSO: 690 рядків |  82.80% | ETA 03:42

[5750/6932] ✓ STAK: 186 рядків |  82.95% | ETA 03:40

   • RAM · 🧠 RAM: 365.2 MB

   ⏳ перед flush · 🧠 RAM: 365.2 MB

💾 batch 1345 → 14,344 рядків (всього 1,558,314 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1345.csv.gz

   ✅ після flush · 🧠 RAM: 367.8 MB

[5760/6932] ✓ STGW: 345 рядків |  83.09% | ETA 03:38

[5770/6932] ✓ STM: 497 рядків |  83.24% | ETA 03:36

[5780/6932] ✓ STRO: 122 рядків |  83.38% | ETA 03:34

[5790/6932] ✓ STWD: 411 рядків |  83.53% | ETA 03:32

[5800/6932] ✓ SUNC: 304 рядків |  83.67% | ETA 03:30

   • RAM · 🧠 RAM: 369.7 MB

   ⏳ перед flush · 🧠 RAM: 369.8 MB

💾 batch 1346 → 12,550 рядків (всього 1,570,864 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1346.csv.gz

   ✅ після flush · 🧠 RAM: 372.4 MB

[5810/6932] ✓ SUZ: 391 рядків |  83.81% | ETA 03:28

[5820/6932] ✓ SVV: 307 рядків |  83.96% | ETA 03:26

[5830/6932] ✓ SWZ: 41 рядків |  84.10% | ETA 03:24

[5840/6932] ✓ SYM: 396 рядків |  84.25% | ETA 03:22

[5850/6932] ✓ TAK: 379 рядків |  84.39% | ETA 03:21

   • RAM · 🧠 RAM: 373.3 MB

   ⏳ перед flush · 🧠 RAM: 373.3 MB

💾 batch 1347 → 15,368 рядків (всього 1,586,232 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1347.csv.gz

   ✅ після flush · 🧠 RAM: 376.3 MB

[5860/6932] ✓ TARK: 43 рядків |  84.54% | ETA 03:19

[5870/6932] ✓ TBHC: 27 рядків |  84.68% | ETA 03:17

[5880/6932] ✓ TCBI: 358 рядків |  84.82% | ETA 03:15

[5890/6932] ✓ TCRX: 234 рядків |  84.97% | ETA 03:13

[5900/6932] ✓ TDOG: 3 рядків |  85.11% | ETA 03:11

   • RAM · 🧠 RAM: 377.1 MB

   ⏳ перед flush · 🧠 RAM: 377.1 MB

💾 batch 1348 → 10,878 рядків (всього 1,597,110 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1348.csv.gz

   ✅ після flush · 🧠 RAM: 379.8 MB

[5910/6932] ✓ TECH: 373 рядків |  85.26% | ETA 03:09

[5920/6932] – TELFY: empty |  85.40% | ETA 03:07

[5930/6932] ✓ TERN: 402 рядків |  85.55% | ETA 03:05

[5940/6932] ✓ TFLO: 382 рядків |  85.69% | ETA 03:03

[5950/6932] ✓ TGLS: 266 рядків |  85.83% | ETA 03:02

   • RAM · 🧠 RAM: 380.9 MB

   ⏳ перед flush · 🧠 RAM: 381.0 MB

💾 batch 1349 → 12,282 рядків (всього 1,609,392 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1349.csv.gz

   ✅ після flush · 🧠 RAM: 382.7 MB

[5960/6932] ✓ THH: 167 рядків |  85.98% | ETA 03:00

[5970/6932] ✓ TIC: 390 рядків |  86.12% | ETA 02:58

[5980/6932] ✓ TIVC: 29 рядків |  86.27% | ETA 02:56

[5990/6932] ✓ TLH: 398 рядків |  86.41% | ETA 02:54

[6000/6932] ✓ TLT: 864 рядків |  86.56% | ETA 02:52

   • RAM · 🧠 RAM: 383.9 MB

   ⏳ перед flush · 🧠 RAM: 383.9 MB

💾 batch 1350 → 11,436 рядків (всього 1,620,828 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1350.csv.gz

   ✅ після flush · 🧠 RAM: 384.0 MB

[6010/6932] ✓ TME: 529 рядків |  86.70% | ETA 02:50

[6020/6932] ✓ TNET: 234 рядків |  86.84% | ETA 02:48

[6030/6932] ✓ TOL: 378 рядків |  86.99% | ETA 02:46

[6040/6932] ✓ TOUR: 259 рядків |  87.13% | ETA 02:44

[6050/6932] ✓ TPH: 365 рядків |  87.28% | ETA 02:43

   • RAM · 🧠 RAM: 386.1 MB

   ⏳ перед flush · 🧠 RAM: 385.9 MB

💾 batch 1351 → 15,226 рядків (всього 1,636,054 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1351.csv.gz

   ✅ після flush · 🧠 RAM: 389.4 MB

[6060/6932] ✓ TRAW: 48 рядків |  87.42% | ETA 02:41

[6070/6932] ✓ TRIP: 402 рядків |  87.56% | ETA 02:39

[6080/6932] ✓ TROX: 398 рядків |  87.71% | ETA 02:37

[6090/6932] ✓ TRVG: 19 рядків |  87.85% | ETA 02:35

[6100/6932] – TSEOF: empty |  88.00% | ETA 02:33

   • RAM · 🧠 RAM: 390.3 MB

   ⏳ перед flush · 🧠 RAM: 390.4 MB

💾 batch 1352 → 13,482 рядків (всього 1,649,536 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1352.csv.gz

   ✅ після flush · 🧠 RAM: 390.9 MB

[6110/6932] ✓ TSLL: 1,191 рядків |  88.14% | ETA 02:31

[6120/6932] ✓ TSM: 965 рядків |  88.29% | ETA 02:29

[6130/6932] ✓ TSQ: 172 рядків |  88.43% | ETA 02:27

[6140/6932] ✓ TTDU: 328 рядків |  88.57% | ETA 02:26

[6150/6932] ✓ TTWO: 399 рядків |  88.72% | ETA 02:24

   • RAM · 🧠 RAM: 391.0 MB

   ⏳ перед flush · 🧠 RAM: 391.0 MB

💾 batch 1353 → 16,326 рядків (всього 1,665,862 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1353.csv.gz

   ✅ після flush · 🧠 RAM: 391.6 MB

[6160/6932] ✓ TVRD: 36 рядків |  88.86% | ETA 02:22

[6170/6932] – TWNPQ: empty |  89.01% | ETA 02:20

[6180/6932] ✓ TXT: 378 рядків |  89.15% | ETA 02:18

[6190/6932] ✓ TZA: 887 рядків |  89.30% | ETA 02:16

[6200/6932] ✓ UBER: 551 рядків |  89.44% | ETA 02:14

   • RAM · 🧠 RAM: 392.3 MB

   ⏳ перед flush · 🧠 RAM: 391.8 MB

💾 batch 1354 → 13,320 рядків (всього 1,679,182 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1354.csv.gz

   ✅ після flush · 🧠 RAM: 394.7 MB

[6210/6932] ✓ UCB: 325 рядків |  89.58% | ETA 02:12

[6220/6932] ✓ UEC: 519 рядків |  89.73% | ETA 02:11

[6230/6932] ✓ UGI: 360 рядків |  89.87% | ETA 02:09

[6240/6932] ✓ UL: 564 рядків |  90.02% | ETA 02:07

[6250/6932] ✓ UMBF: 252 рядків |  90.16% | ETA 02:05

   • RAM · 🧠 RAM: 390.7 MB

   ⏳ перед flush · 🧠 RAM: 390.8 MB

💾 batch 1355 → 12,505 рядків (всього 1,691,687 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1355.csv.gz

   ✅ після flush · 🧠 RAM: 391.2 MB

[6260/6932] ✓ UNH: 655 рядків |  90.31% | ETA 02:03

[6270/6932] ✓ UONEK: 9 рядків |  90.45% | ETA 02:01

[6280/6932] ✓ UPW: 43 рядків |  90.59% | ETA 01:59

[6290/6932] ✓ URI: 348 рядків |  90.74% | ETA 01:57

[6300/6932] ✓ USAU: 232 рядків |  90.88% | ETA 01:56

   • RAM · 🧠 RAM: 382.3 MB

   ⏳ перед flush · 🧠 RAM: 382.4 MB

💾 batch 1356 → 15,188 рядків (всього 1,706,875 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1356.csv.gz

   ✅ після flush · 🧠 RAM: 383.3 MB

[6310/6932] ✓ USFR: 451 рядків |  91.03% | ETA 01:54

[6320/6932] ✓ USMV: 401 рядків |  91.17% | ETA 01:52

[6330/6932] ✓ UTES: 208 рядків |  91.32% | ETA 01:50

[6340/6932] ✓ UUP: 350 рядків |  91.46% | ETA 01:48

[6350/6932] ✓ UXRP: 213 рядків |  91.60% | ETA 01:46

   • RAM · 🧠 RAM: 380.0 MB

   ⏳ перед flush · 🧠 RAM: 380.1 MB

💾 batch 1357 → 13,380 рядків (всього 1,720,255 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1357.csv.gz

   ✅ після flush · 🧠 RAM: 382.7 MB

[6360/6932] ✓ VAVX: 4 рядків |  91.75% | ETA 01:44

[6370/6932] ✓ VCIG: 211 рядків |  91.89% | ETA 01:43

[6380/6932] ✓ VDE: 408 рядків |  92.04% | ETA 01:41

[6390/6932] ✓ VERI: 325 рядків |  92.18% | ETA 01:39

[6400/6932] ✓ VFLO: 352 рядків |  92.33% | ETA 01:37

   • RAM · 🧠 RAM: 383.1 MB

   ⏳ перед flush · 🧠 RAM: 383.1 MB

💾 batch 1358 → 13,308 рядків (всього 1,733,563 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1358.csv.gz

   ✅ після flush · 🧠 RAM: 385.1 MB

[6410/6932] ✓ VHT: 308 рядків |  92.47% | ETA 01:35

[6420/6932] ✓ VIK: 391 рядків |  92.61% | ETA 01:33

[6430/6932] ✓ VITL: 400 рядків |  92.76% | ETA 01:32

[6440/6932] ✓ VLRS: 328 рядків |  92.90% | ETA 01:30

[6450/6932] ✓ VNAM: 32 рядків |  93.05% | ETA 01:28

   • RAM · 🧠 RAM: 388.8 MB

   ⏳ перед flush · 🧠 RAM: 388.9 MB

💾 batch 1359 → 15,736 рядків (всього 1,749,299 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1359.csv.gz

   ✅ після flush · 🧠 RAM: 391.9 MB

[6460/6932] ✓ VNRX: 773 рядків |  93.19% | ETA 01:26

[6470/6932] ✓ VOOG: 367 рядків |  93.34% | ETA 01:24

[6480/6932] ✓ VPL: 388 рядків |  93.48% | ETA 01:22

[6490/6932] ✓ VRIG: 158 рядків |  93.62% | ETA 01:20

[6500/6932] ✓ VS: 15 рядків |  93.77% | ETA 01:19

   • RAM · 🧠 RAM: 392.9 MB

   ⏳ перед flush · 🧠 RAM: 392.9 MB

💾 batch 1360 → 14,374 рядків (всього 1,763,673 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1360.csv.gz

   ✅ після flush · 🧠 RAM: 393.5 MB

[6510/6932] ✓ VSNT: 383 рядків |  93.91% | ETA 01:17

[6520/6932] ✓ VTAK: 82 рядків |  94.06% | ETA 01:15

[6530/6932] ✓ VTSI: 52 рядків |  94.20% | ETA 01:13

[6540/6932] ✓ VVOS: 64 рядків |  94.35% | ETA 01:11

[6550/6932] ✓ VXZ: 1,171 рядків |  94.49% | ETA 01:09

   • RAM · 🧠 RAM: 394.0 MB

   ⏳ перед flush · 🧠 RAM: 393.8 MB

💾 batch 1361 → 14,445 рядків (всього 1,778,118 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1361.csv.gz

   ✅ після flush · 🧠 RAM: 395.0 MB

[6560/6932] ✓ WABC: 175 рядків |  94.63% | ETA 01:07

[6570/6932] ✓ WAR: 40 рядків |  94.78% | ETA 01:06

[6580/6932] ✓ WBTN: 176 рядків |  94.92% | ETA 01:04

[6590/6932] ✓ WDAY: 410 рядків |  95.07% | ETA 01:02

[6600/6932] ✓ WEAT: 415 рядків |  95.21% | ETA 01:00

   • RAM · 🧠 RAM: 395.7 MB

   ⏳ перед flush · 🧠 RAM: 395.8 MB

💾 batch 1362 → 12,420 рядків (всього 1,790,538 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1362.csv.gz

   ✅ після flush · 🧠 RAM: 397.3 MB

[6610/6932] ✓ WEPN: 24 рядків |  95.35% | ETA 00:58

[6620/6932] ✓ WFF: 11 рядків |  95.50% | ETA 00:56

[6630/6932] ✓ WHLR: 140 рядків |  95.64% | ETA 00:55

[6640/6932] ✓ WKEY: 143 рядків |  95.79% | ETA 00:53

[6650/6932] ✓ WLTH: 392 рядків |  95.93% | ETA 00:51

   • RAM · 🧠 RAM: 398.0 MB

   ⏳ перед flush · 🧠 RAM: 398.1 MB

💾 batch 1363 → 10,630 рядків (всього 1,801,168 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1363.csv.gz

   ✅ після flush · 🧠 RAM: 400.7 MB

[6660/6932] ✓ WNEB: 55 рядків |  96.08% | ETA 00:49

[6670/6932] ✓ WPC: 345 рядків |  96.22% | ETA 00:47

[6680/6932] ✓ WS: 188 рядків |  96.36% | ETA 00:45

[6690/6932] ✓ WST: 372 рядків |  96.51% | ETA 00:44

[6700/6932] ✓ WTRG: 375 рядків |  96.65% | ETA 00:42

   • RAM · 🧠 RAM: 401.9 MB

   ⏳ перед flush · 🧠 RAM: 402.0 MB

💾 batch 1364 → 13,115 рядків (всього 1,814,283 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1364.csv.gz

   ✅ після flush · 🧠 RAM: 403.1 MB

[6710/6932] ✓ WWD: 249 рядків |  96.80% | ETA 00:40

[6720/6932] ✓ XAIX: 25 рядків |  96.94% | ETA 00:38

[6730/6932] ✓ XCH: 22 рядків |  97.09% | ETA 00:36

[6740/6932] ✓ XGN: 145 рядків |  97.23% | ETA 00:34

[6750/6932] ✓ XLE: 829 рядків |  97.37% | ETA 00:33

   • RAM · 🧠 RAM: 404.2 MB

   ⏳ перед flush · 🧠 RAM: 404.2 MB

💾 batch 1365 → 11,544 рядків (всього 1,825,827 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1365.csv.gz

   ✅ після flush · 🧠 RAM: 405.9 MB

[6760/6932] ✓ XLVI: 15 рядків |  97.52% | ETA 00:31

[6770/6932] ✓ XNCR: 291 рядків |  97.66% | ETA 00:29

[6780/6932] ✓ XP: 401 рядків |  97.81% | ETA 00:27

[6790/6932] ✓ XPP: 15 рядків |  97.95% | ETA 00:25

[6800/6932] ✓ XRPR: 31 рядків |  98.10% | ETA 00:23

   • RAM · 🧠 RAM: 404.7 MB

   ⏳ перед flush · 🧠 RAM: 404.5 MB

💾 batch 1366 → 12,258 рядків (всього 1,838,085 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1366.csv.gz

   ✅ після flush · 🧠 RAM: 406.0 MB

[6810/6932] ✓ XSLL: 4 рядків |  98.24% | ETA 00:22

[6820/6932] ✓ XTNT: 135 рядків |  98.38% | ETA 00:20

[6830/6932] ✓ XYLD: 363 рядків |  98.53% | ETA 00:18

[6840/6932] ✓ YBTC: 101 рядків |  98.67% | ETA 00:16

[6850/6932] ✓ YETI: 312 рядків |  98.82% | ETA 00:14

   • RAM · 🧠 RAM: 405.5 MB

   ⏳ перед flush · 🧠 RAM: 405.5 MB

💾 batch 1367 → 7,888 рядків (всього 1,845,973 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1367.csv.gz

   ✅ після flush · 🧠 RAM: 405.6 MB

[6860/6932] ✓ YJ: 10 рядків |  98.96% | ETA 00:13

[6870/6932] ✓ YSPY: 61 рядків |  99.11% | ETA 00:11

[6880/6932] ✓ Z: 402 рядків |  99.25% | ETA 00:09

[6890/6932] ✓ ZDGE: 46 рядків |  99.39% | ETA 00:07

[6900/6932] ✓ ZH: 265 рядків |  99.54% | ETA 00:05

   • RAM · 🧠 RAM: 404.2 MB

   ⏳ перед flush · 🧠 RAM: 404.2 MB

💾 batch 1368 → 11,059 рядків (всього 1,857,032 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1368.csv.gz

   ✅ після flush · 🧠 RAM: 406.3 MB

[6910/6932] ✓ ZNB: 86 рядків |  99.68% | ETA 00:03

[6920/6932] ✓ ZTEK: 32 рядків |  99.83% | ETA 00:02

[6930/6932] ✓ ZYME: 382 рядків |  99.97% | ETA 00:00

[6932/6932] – ZYXIQ: empty | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 401.5 MB

💾 batch 1369 → 7,522 рядків (всього 1,864,554 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch\intraday_1369.csv.gz

   ✅ після flush · 🧠 RAM: 401.5 MB

   🔚 фінал · 🧠 RAM: 401.5 MB

🏁 Готово. Нових рядків: 1,864,554 → C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch | Час: 20:56

In [19]:
import os, glob, gc, time
from typing import Optional

import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def collect_premarket_by_day_stream(
    folder: str,
    out_path: str = "CRACEN/work/premarket_rows.parquet",
    pattern: str = "intraday_*.csv.gz",
    start_time: str = "00:00:00",
    end_time: str   = "23:59:00",
    *,
    date_min: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    date_max: Optional[str] = None,     # 'YYYY-MM-DD' inclusive
    aggregate: bool = False,            # False → всі рядки, True → агрегація по (ticker,date)
    chunksize: int = 200_000,           # якщо мало RAM — ще зменш
    compression: str = "snappy",
    log_every: int = 5,
    sort_chunk: bool = True,            # sort within each chunk (ticker,dt)
):
    """
    Проходить по {folder}/{pattern}, фільтрує рядки:
      - за часовим вікном [start_time..end_time] по підрядку часу в 'dt'
      - опційно за датою [date_min..date_max] по підрядку дати в 'dt'
    і стрімово пише у один Parquet.

    Очікувані колонки у CSV: 'ticker','dt','o','h','l','c','v'.
    dt має формат 'YYYY-MM-DD HH:MM:SS' (string).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    files = sorted(glob.glob(os.path.join(folder, pattern)))
    if not files:
        raise FileNotFoundError(f"Не знайдено файлів {pattern} у {folder}")

    # normalize dates (string compare works for YYYY-MM-DD)
    if date_min is not None:
        date_min = str(date_min)[:10]
    if date_max is not None:
        date_max = str(date_max)[:10]
    if date_min is not None and date_max is not None and date_min > date_max:
        date_min, date_max = date_max, date_min

    # читаємо тільки потрібне, даємо вузькі типи
    usecols = ["ticker", "dt", "o", "h", "l", "c", "v"]
    dtypes = {
        "ticker": "string",
        "dt": "string",         # важливо: фільтруємо по підрядку, без datetime-парсингу
        "o": "float32",
        "h": "float32",
        "l": "float32",
        "c": "float32",
        "v": "float32",
    }

    # підготовка виходу
    if os.path.exists(out_path):
        os.remove(out_path)
    writer = None

    t0 = time.time()
    total_in = total_out = 0
    file_idx = 0

    rng_str = ""
    if date_min or date_max:
        rng_str = f"  date=[{date_min or '…'}..{date_max or '…'}]"
    print(f"▶️ START: {folder}/{pattern} → {out_path}  chunksize={chunksize:,}{rng_str}")

    try:
        for path in files:
            file_idx += 1
            chunk_idx = 0

            reader = pd.read_csv(
                path,
                compression="infer",
                usecols=usecols,
                dtype=dtypes,
                chunksize=chunksize,
                low_memory=True,
                # engine="pyarrow",
            )

            for chunk in reader:
                chunk_idx += 1
                total_in += len(chunk)

                # швидке фільтрування по часу: 'YYYY-MM-DD HH:MM:SS'
                t = chunk["dt"].str.slice(11, 19)
                mask = (t >= start_time) & (t <= end_time)

                # фільтр по даті, також строками
                if date_min is not None or date_max is not None:
                    d = chunk["dt"].str.slice(0, 10)
                    if date_min is not None:
                        mask &= (d >= date_min)
                    if date_max is not None:
                        mask &= (d <= date_max)

                cut = chunk.loc[mask].copy()

                if cut.empty:
                    del chunk, t, mask, cut
                    gc.collect()
                    continue

                if aggregate:
                    # дата як рядок 'YYYY-MM-DD'
                    cut["date"] = cut["dt"].str.slice(0, 10)
                    # сорт для стабільності
                    if sort_chunk and {"ticker", "date"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "date"], kind="mergesort")
                    grp = (cut.groupby(["ticker", "date"], as_index=False, observed=True)
                              .agg({"v": "sum"}))  # приклад: сума обсягу; змінюй агрегацію за потреби
                    out_df = grp
                else:
                    # стабільний порядок в межах чанка
                    if sort_chunk and {"ticker", "dt"}.issubset(cut.columns):
                        cut = cut.sort_values(["ticker", "dt"], kind="mergesort")
                    out_df = cut

                table = pa.Table.from_pandas(out_df, preserve_index=False)
                if writer is None:
                    writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
                writer.write_table(table)
                total_out += len(out_df)

                if (chunk_idx % log_every) == 0:
                    elapsed = time.time() - t0
                    print(f"  [{file_idx}/{len(files)}] {os.path.basename(path)} "
                          f"chunk {chunk_idx}  in={total_in:,}  out={total_out:,}  "
                          f"elapsed={elapsed:,.1f}s")

                del chunk, t, mask, cut, out_df, table
                gc.collect()

    finally:
        if writer is not None:
            writer.close()

    print(f"✅ DONE  in={total_in:,} → out={total_out:,}  to {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [20]:
collect_premarket_by_day_stream(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "premarket_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    date_min=start_date_str,      # NEW
    date_max=end_date_str,        # NEW
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\CRACEN_batch/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  chunksize=150,000  date=[2025-12-20..2026-03-20]

  [1/1369] intraday_0001.csv.gz chunk 5  in=750,000  out=293,618  elapsed=1.2s

  [2/1369] intraday_0002.csv.gz chunk 5  in=1,725,827  out=678,873  elapsed=2.5s

  [3/1369] intraday_0003.csv.gz chunk 5  in=2,590,424  out=1,029,323  elapsed=3.7s

  [4/1369] intraday_0004.csv.gz chunk 5  in=3,333,452  out=1,334,749  elapsed=5.0s

  [5/1369] intraday_0005.csv.gz chunk 5  in=4,083,452  out=1,618,039  elapsed=6.0s

  [6/1369] intraday_0006.csv.gz chunk 5  in=4,957,443  out=1,961,699  elapsed=7.2s

  [7/1369] intraday_0007.csv.gz chunk 5  in=5,912,526  out=2,333,416  elapsed=8.5s

  [8/1369] intraday_0008.csv.gz chunk 5  in=6,673,107  out=2,630,997  elapsed=9.5s

  [9/1369] intraday_0009.csv.gz chunk 5  in=7,482,671  out=2,948,270  elapsed=10.7s

  [10/1369] intraday_0010.csv.gz chunk 5  in=8,422,497  out=3,322,436  elapsed=12.0s

  [11/1369] intraday_0011.csv.gz chunk 5  in=9,348,724  out=3,715,140  elapsed=13.3s

  [12/1369] intraday_0012.csv.gz chunk 5  in=10,098,724  out=4,020,505  elapsed=14.3s

  [13/1369] intraday_0013.csv.gz chunk 5  in=10,952,410  out=4,360,368  elapsed=15.4s

  [14/1369] intraday_0014.csv.gz chunk 5  in=11,729,573  out=4,670,680  elapsed=16.5s

  [15/1369] intraday_0015.csv.gz chunk 5  in=12,333,647  out=4,906,727  elapsed=17.3s

  [16/1369] intraday_0016.csv.gz chunk 5  in=13,083,647  out=5,194,746  elapsed=18.3s

  [17/1369] intraday_0017.csv.gz chunk 5  in=14,119,434  out=5,573,166  elapsed=19.7s

  [18/1369] intraday_0018.csv.gz chunk 5  in=14,987,474  out=5,955,069  elapsed=20.9s

  [19/1369] intraday_0019.csv.gz chunk 5  in=15,723,943  out=6,232,973  elapsed=21.9s

  [20/1369] intraday_0020.csv.gz chunk 5  in=16,473,943  out=6,515,524  elapsed=22.9s

  [21/1369] intraday_0021.csv.gz chunk 5  in=17,305,781  out=6,843,093  elapsed=24.1s

  [22/1369] intraday_0022.csv.gz chunk 5  in=18,114,555  out=7,157,349  elapsed=25.2s

  [23/1369] intraday_0023.csv.gz chunk 5  in=18,864,555  out=7,446,336  elapsed=26.1s

  [24/1369] intraday_0024.csv.gz chunk 5  in=19,645,557  out=7,757,520  elapsed=27.2s

  [25/1369] intraday_0025.csv.gz chunk 5  in=20,416,242  out=8,044,906  elapsed=28.2s

  [26/1369] intraday_0026.csv.gz chunk 5  in=21,166,242  out=8,315,243  elapsed=29.2s

  [27/1369] intraday_0027.csv.gz chunk 5  in=21,935,669  out=8,615,508  elapsed=30.3s

  [28/1369] intraday_0028.csv.gz chunk 5  in=22,685,669  out=8,914,990  elapsed=31.3s

  [29/1369] intraday_0029.csv.gz chunk 5  in=23,693,087  out=9,318,500  elapsed=32.8s

  [30/1369] intraday_0030.csv.gz chunk 5  in=24,639,604  out=9,692,964  elapsed=34.1s

  [31/1369] intraday_0031.csv.gz chunk 5  in=25,543,444  out=10,047,497  elapsed=35.3s

  [32/1369] intraday_0032.csv.gz chunk 5  in=26,293,444  out=10,337,282  elapsed=36.3s

  [33/1369] intraday_0033.csv.gz chunk 5  in=27,109,346  out=10,645,019  elapsed=37.4s

  [34/1369] intraday_0034.csv.gz chunk 5  in=27,922,589  out=10,964,962  elapsed=38.5s

  [35/1369] intraday_0035.csv.gz chunk 5  in=28,672,589  out=11,261,973  elapsed=39.5s

  [36/1369] intraday_0036.csv.gz chunk 5  in=29,491,745  out=11,606,562  elapsed=40.7s

  [37/1369] intraday_0037.csv.gz chunk 5  in=30,234,721  out=11,897,120  elapsed=41.7s

  [38/1369] intraday_0038.csv.gz chunk 5  in=30,924,778  out=12,174,076  elapsed=42.7s

  [39/1369] intraday_0039.csv.gz chunk 5  in=31,674,778  out=12,460,119  elapsed=43.7s

  [40/1369] intraday_0040.csv.gz chunk 5  in=32,407,718  out=12,738,570  elapsed=44.6s

  [41/1369] intraday_0041.csv.gz chunk 5  in=33,157,718  out=13,015,417  elapsed=45.6s

  [42/1369] intraday_0042.csv.gz chunk 5  in=34,051,794  out=13,378,824  elapsed=46.8s

  [43/1369] intraday_0043.csv.gz chunk 5  in=34,960,739  out=13,735,930  elapsed=48.0s

  [44/1369] intraday_0044.csv.gz chunk 5  in=35,710,739  out=14,033,508  elapsed=49.1s

  [45/1369] intraday_0045.csv.gz chunk 5  in=36,516,274  out=14,351,264  elapsed=50.1s

  [46/1369] intraday_0046.csv.gz chunk 5  in=37,318,713  out=14,662,717  elapsed=51.2s

  [47/1369] intraday_0047.csv.gz chunk 5  in=38,133,804  out=14,976,206  elapsed=52.3s

  [48/1369] intraday_0048.csv.gz chunk 5  in=38,906,436  out=15,287,839  elapsed=53.3s

  [49/1369] intraday_0049.csv.gz chunk 5  in=39,656,436  out=15,592,337  elapsed=54.5s

  [50/1369] intraday_0050.csv.gz chunk 5  in=40,601,960  out=15,967,576  elapsed=55.8s

  [51/1369] intraday_0051.csv.gz chunk 5  in=41,414,383  out=16,291,589  elapsed=56.9s

  [52/1369] intraday_0052.csv.gz chunk 5  in=42,164,383  out=16,584,890  elapsed=57.9s

  [53/1369] intraday_0053.csv.gz chunk 5  in=42,998,896  out=16,920,616  elapsed=59.0s

  [54/1369] intraday_0054.csv.gz chunk 5  in=43,729,514  out=17,208,282  elapsed=60.0s

  [55/1369] intraday_0055.csv.gz chunk 5  in=44,479,514  out=17,485,876  elapsed=61.0s

  [56/1369] intraday_0056.csv.gz chunk 5  in=45,292,383  out=17,799,232  elapsed=62.0s

  [57/1369] intraday_0057.csv.gz chunk 5  in=46,110,329  out=18,128,080  elapsed=63.1s

  [58/1369] intraday_0058.csv.gz chunk 5  in=46,830,377  out=18,423,851  elapsed=64.2s

  [59/1369] intraday_0059.csv.gz chunk 5  in=47,580,377  out=18,719,738  elapsed=65.2s

  [60/1369] intraday_0060.csv.gz chunk 5  in=48,264,439  out=19,000,250  elapsed=66.2s

  [61/1369] intraday_0061.csv.gz chunk 5  in=49,014,439  out=19,284,279  elapsed=67.2s

  [62/1369] intraday_0062.csv.gz chunk 5  in=50,022,323  out=19,670,141  elapsed=68.6s

  [63/1369] intraday_0063.csv.gz chunk 5  in=50,772,323  out=19,964,702  elapsed=69.6s

  [64/1369] intraday_0064.csv.gz chunk 5  in=51,725,856  out=20,341,650  elapsed=70.9s

  [65/1369] intraday_0065.csv.gz chunk 5  in=52,611,073  out=20,701,800  elapsed=72.1s

  [66/1369] intraday_0066.csv.gz chunk 5  in=53,344,110  out=20,989,773  elapsed=73.1s

  [67/1369] intraday_0067.csv.gz chunk 5  in=54,094,110  out=21,287,213  elapsed=74.1s

  [68/1369] intraday_0068.csv.gz chunk 5  in=54,864,222  out=21,588,107  elapsed=75.2s

  [69/1369] intraday_0069.csv.gz chunk 5  in=55,688,820  out=21,892,639  elapsed=76.3s

  [70/1369] intraday_0070.csv.gz chunk 5  in=56,497,048  out=22,211,300  elapsed=77.5s

  [71/1369] intraday_0071.csv.gz chunk 5  in=57,135,058  out=22,454,782  elapsed=78.3s

  [72/1369] intraday_0072.csv.gz chunk 5  in=57,879,667  out=22,754,480  elapsed=79.4s

  [73/1369] intraday_0073.csv.gz chunk 5  in=58,629,667  out=23,051,380  elapsed=80.4s

  [74/1369] intraday_0074.csv.gz chunk 5  in=59,409,405  out=23,350,991  elapsed=81.4s

  [75/1369] intraday_0075.csv.gz chunk 5  in=60,159,405  out=23,634,308  elapsed=82.4s

  [76/1369] intraday_0076.csv.gz chunk 5  in=60,866,670  out=23,913,320  elapsed=83.4s

  [77/1369] intraday_0077.csv.gz chunk 5  in=61,616,670  out=24,216,550  elapsed=84.4s

  [78/1369] intraday_0078.csv.gz chunk 5  in=62,426,095  out=24,515,246  elapsed=85.5s

  [79/1369] intraday_0079.csv.gz chunk 5  in=63,486,689  out=24,931,575  elapsed=87.0s

  [80/1369] intraday_0080.csv.gz chunk 5  in=64,355,814  out=25,287,036  elapsed=88.3s

  [81/1369] intraday_0081.csv.gz chunk 5  in=65,105,814  out=25,584,805  elapsed=89.3s

  [82/1369] intraday_0082.csv.gz chunk 5  in=65,923,353  out=25,914,456  elapsed=90.4s

  [83/1369] intraday_0083.csv.gz chunk 5  in=66,712,271  out=26,223,356  elapsed=91.5s

  [84/1369] intraday_0084.csv.gz chunk 5  in=67,498,390  out=26,525,865  elapsed=92.6s

  [85/1369] intraday_0085.csv.gz chunk 5  in=68,668,886  out=26,981,497  elapsed=94.2s

  [86/1369] intraday_0086.csv.gz chunk 5  in=69,443,048  out=27,289,556  elapsed=95.2s

  [87/1369] intraday_0087.csv.gz chunk 5  in=70,370,846  out=27,670,105  elapsed=96.5s

  [88/1369] intraday_0088.csv.gz chunk 5  in=71,314,187  out=28,055,814  elapsed=97.8s

  [89/1369] intraday_0089.csv.gz chunk 5  in=72,147,243  out=28,402,376  elapsed=99.0s

  [90/1369] intraday_0090.csv.gz chunk 5  in=73,031,904  out=28,757,594  elapsed=100.2s

  [91/1369] intraday_0091.csv.gz chunk 5  in=73,819,473  out=29,064,835  elapsed=101.2s

  [92/1369] intraday_0092.csv.gz chunk 5  in=74,749,201  out=29,423,743  elapsed=102.5s

  [93/1369] intraday_0093.csv.gz chunk 5  in=75,581,839  out=29,745,389  elapsed=103.6s

  [94/1369] intraday_0094.csv.gz chunk 5  in=76,397,498  out=30,058,484  elapsed=104.7s

  [95/1369] intraday_0095.csv.gz chunk 5  in=77,278,738  out=30,397,293  elapsed=105.9s

  [96/1369] intraday_0096.csv.gz chunk 5  in=78,128,774  out=30,721,397  elapsed=107.1s

  [97/1369] intraday_0097.csv.gz chunk 5  in=79,010,543  out=31,058,654  elapsed=108.3s

  [98/1369] intraday_0098.csv.gz chunk 5  in=79,782,923  out=31,375,965  elapsed=109.3s

  [99/1369] intraday_0099.csv.gz chunk 5  in=80,552,827  out=31,678,118  elapsed=110.4s

  [100/1369] intraday_0100.csv.gz chunk 5  in=81,613,945  out=32,119,242  elapsed=111.9s

  [101/1369] intraday_0101.csv.gz chunk 5  in=82,411,660  out=32,414,378  elapsed=112.9s

  [102/1369] intraday_0102.csv.gz chunk 5  in=83,343,388  out=32,798,596  elapsed=114.2s

  [103/1369] intraday_0103.csv.gz chunk 5  in=84,277,121  out=33,162,216  elapsed=115.5s

  [104/1369] intraday_0104.csv.gz chunk 5  in=85,067,945  out=33,478,492  elapsed=116.6s

  [105/1369] intraday_0105.csv.gz chunk 5  in=85,909,844  out=33,836,596  elapsed=117.8s

  [106/1369] intraday_0106.csv.gz chunk 5  in=86,782,104  out=34,186,373  elapsed=118.9s

  [107/1369] intraday_0107.csv.gz chunk 5  in=87,571,848  out=34,501,867  elapsed=120.0s

  [108/1369] intraday_0108.csv.gz chunk 5  in=88,635,246  out=34,914,455  elapsed=121.5s

  [109/1369] intraday_0109.csv.gz chunk 5  in=89,429,847  out=35,223,656  elapsed=122.6s

  [110/1369] intraday_0110.csv.gz chunk 5  in=90,369,231  out=35,586,531  elapsed=123.9s

  [111/1369] intraday_0111.csv.gz chunk 5  in=91,390,909  out=35,973,162  elapsed=125.2s

  [112/1369] intraday_0112.csv.gz chunk 5  in=92,177,941  out=36,291,116  elapsed=126.3s

  [113/1369] intraday_0113.csv.gz chunk 5  in=93,009,949  out=36,622,091  elapsed=127.4s

  [114/1369] intraday_0114.csv.gz chunk 5  in=93,772,660  out=36,920,400  elapsed=128.4s

  [115/1369] intraday_0115.csv.gz chunk 5  in=94,609,984  out=37,256,870  elapsed=129.6s

  [116/1369] intraday_0116.csv.gz chunk 5  in=95,366,153  out=37,552,666  elapsed=130.6s

  [117/1369] intraday_0117.csv.gz chunk 5  in=96,314,921  out=37,931,476  elapsed=131.9s

  [118/1369] intraday_0118.csv.gz chunk 5  in=97,100,237  out=38,237,928  elapsed=133.0s

  [119/1369] intraday_0119.csv.gz chunk 5  in=98,245,742  out=38,694,932  elapsed=134.6s

  [120/1369] intraday_0120.csv.gz chunk 5  in=98,995,742  out=39,001,433  elapsed=135.6s

  [121/1369] intraday_0121.csv.gz chunk 5  in=99,855,343  out=39,333,978  elapsed=136.7s

  [122/1369] intraday_0122.csv.gz chunk 5  in=100,900,376  out=39,755,868  elapsed=138.1s

  [123/1369] intraday_0123.csv.gz chunk 5  in=101,688,876  out=40,069,521  elapsed=139.2s

  [124/1369] intraday_0124.csv.gz chunk 5  in=102,540,604  out=40,397,996  elapsed=140.4s

  [125/1369] intraday_0125.csv.gz chunk 5  in=103,517,055  out=40,790,500  elapsed=141.7s

  [126/1369] intraday_0126.csv.gz chunk 5  in=104,398,833  out=41,127,840  elapsed=142.9s

  [127/1369] intraday_0127.csv.gz chunk 5  in=105,314,012  out=41,487,982  elapsed=144.2s

  [128/1369] intraday_0128.csv.gz chunk 5  in=106,064,012  out=41,773,889  elapsed=145.2s

  [129/1369] intraday_0129.csv.gz chunk 5  in=106,816,285  out=42,055,098  elapsed=146.2s

  [130/1369] intraday_0130.csv.gz chunk 5  in=107,676,182  out=42,395,184  elapsed=147.3s

  [131/1369] intraday_0131.csv.gz chunk 5  in=108,498,465  out=42,735,496  elapsed=148.5s

  [132/1369] intraday_0132.csv.gz chunk 5  in=109,165,533  out=42,964,849  elapsed=149.4s

  [133/1369] intraday_0133.csv.gz chunk 5  in=109,915,533  out=43,262,468  elapsed=150.4s

✅ DONE  in=178,339,237 → out=111,034,041  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows.parquet  in 283.7s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows.parquet'

In [21]:
import os
import glob
import pandas as pd
from typing import Optional, Dict, Tuple

def build_oc_from_intraday_folder(
    folder: str,
    out_path: Optional[str] = None,
    chunksize: int = 250_000,
) -> pd.DataFrame:
    files = sorted(
        glob.glob(os.path.join(folder, "intraday_*.csv")) +
        glob.glob(os.path.join(folder, "intraday_*.csv.gz"))
    )
    if not files:
        raise FileNotFoundError(f"Не знайдено intraday_*.csv[.gz] у: {folder}")

    OPEN_FROM, OPEN_TO   = "09:30", "09:35"
    CLOSE_FROM, CLOSE_TO = "15:55", "15:59"

    best_open:  Dict[Tuple[str, str], Tuple[str, float]] = {}
    best_close: Dict[Tuple[str, str], Tuple[str, float]] = {}

    usecols = ["ticker", "dt", "o", "c"]

    for path in files:
        for chunk in pd.read_csv(path, compression="infer", low_memory=False,
                                 chunksize=chunksize, usecols=usecols):
            cols = set(map(str, chunk.columns))
            missing = set(usecols) - cols
            if missing:
                raise KeyError(f"{os.path.basename(path)}: відсутні колонки {missing}")

            dt = chunk["dt"].astype(str)
            if "o" in chunk.columns:
                chunk["o"] = pd.to_numeric(chunk["o"], errors="coerce")
            if "c" in chunk.columns:
                chunk["c"] = pd.to_numeric(chunk["c"], errors="coerce")

            hhmm = dt.str.slice(11, 16)
            date = dt.str.slice(0, 10)

            # OPEN
            mask_o = (hhmm >= OPEN_FROM) & (hhmm <= OPEN_TO) & chunk["o"].notna()
            if mask_o.any():
                cut = chunk.loc[mask_o, ["ticker", "o"]].copy()
                cut["date"] = date[mask_o].values
                cut["dt"]   = dt[mask_o].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="first")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_open.get(key)
                    if (cur is None) or (r.dt < cur[0]):
                        best_open[key] = (r.dt, float(r.o))

            # CLOSE
            mask_c = (hhmm >= CLOSE_FROM) & (hhmm <= CLOSE_TO) & chunk["c"].notna()
            if mask_c.any():
                cut = chunk.loc[mask_c, ["ticker", "c"]].copy()
                cut["date"] = date[mask_c].values
                cut["dt"]   = dt[mask_c].values
                cut = cut.sort_values("dt").drop_duplicates(["ticker","date"], keep="last")
                for r in cut.itertuples(index=False):
                    key = (r.ticker, r.date)
                    cur = best_close.get(key)
                    if (cur is None) or (r.dt > cur[0]):
                        best_close[key] = (r.dt, float(r.c))

    opens_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_open.items()],
        columns=["ticker", "date", "open"]
    )
    closes_df = pd.DataFrame(
        [(t, d, v) for (t, d), (_, v) in best_close.items()],
        columns=["ticker", "date", "close"]
    )

    out = pd.merge(opens_df, closes_df, on=["ticker","date"], how="outer") \
            .sort_values(["ticker","date"], kind="stable") \
            .reset_index(drop=True)

    # ⬇️ ОКРУГЛЕННЯ ДО 2 ЗНАКІВ
    if "open" in out.columns:
        out["open"] = pd.to_numeric(out["open"], errors="coerce").round(2)
    if "close" in out.columns:
        out["close"] = pd.to_numeric(out["close"], errors="coerce").round(2)

    # завжди Parquet
    if out_path is None:
        out_path = os.path.join(folder, "oc.parquet")
    if not out_path.endswith(".parquet"):
        out_path += ".parquet"
    os.makedirs(os.path.dirname(out_path) or ".", exist_ok=True)
    out.to_parquet(out_path, index=False)

    return out

In [22]:
df_oc = build_oc_from_intraday_folder(
    folder=str(BATCH_DIR),
    out_path=str(WORK_DIR / "oc.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date    open   close
0      A  2025-10-28  145.74  145.85
1      A  2025-10-29  145.52  143.23
2      A  2025-10-30  142.93  143.39
3      A  2025-10-31  143.10  146.36
4      A  2025-11-03  145.07  144.72

In [23]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_rows.parquet",
    oc_filename: str = "oc.parquet",
    out_filename: str = "premarket_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [24]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=31.3s

[batch   10] rows=20,000,000  elapsed=62.8s

[batch   15] rows=30,000,000  elapsed=93.8s

[batch   20] rows=40,000,000  elapsed=124.9s

[batch   25] rows=50,000,000  elapsed=155.9s

[batch   30] rows=60,000,000  elapsed=187.3s

[batch   35] rows=70,000,000  elapsed=218.4s

[batch   40] rows=80,000,000  elapsed=250.0s

[batch   45] rows=90,000,000  elapsed=281.0s

[batch   50] rows=100,000,000  elapsed=312.6s

[batch   55] rows=110,000,000  elapsed=343.8s

✅ DONE  rows=111,034,041  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  in 348.6s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet

In [25]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",        # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Stack%",     # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        # нульовий prev_close → NaN, щоб не ділити на 0
        denom = df["prev_close"].replace({0: np.nan})

        # розрахунок % vs prev_close
        pct = (df[value_col] / denom - 1.0) * 100.0

        # ще раз гарантуємо float dtype (без object/pd.NA всередині)
        pct = pd.to_numeric(pct, errors="coerce")

        if round_to is not None:
            pct = pct.round(int(round_to))

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(
                output_path,
                table.schema,
                compression="snappy",
            )
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_rows_enriched.parquet",
    output_filename: str = "premarket_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",          # ← open vs prev_close
    out_col: str = "Stack%",       # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [26]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

[batch    5] rows=10,000,000  elapsed=4.4s

[batch   10] rows=20,000,000  elapsed=8.8s

[batch   15] rows=30,000,000  elapsed=13.3s

[batch   20] rows=40,000,000  elapsed=17.6s

[batch   25] rows=50,000,000  elapsed=22.0s

[batch   30] rows=60,000,000  elapsed=26.3s

[batch   35] rows=70,000,000  elapsed=30.6s

[batch   40] rows=80,000,000  elapsed=35.0s

[batch   45] rows=90,000,000  elapsed=39.4s

[batch   50] rows=100,000,000  elapsed=43.7s

[batch   55] rows=110,000,000  elapsed=48.0s

✅ DONE  rows=111,034,041  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet  in 48.5s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_enriched_with_pct.parquet

In [27]:
import os, re, time, math
import pandas as pd
from typing import Dict, List, Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


# ---------- НАДІЙНЕ ЧИТАННЯ МАПІНГУ (ticker, bench) ----------

def _read_mapping(mapping_path: str) -> pd.DataFrame:
    """
    Читає файл з відповідностями тікер↔бенч. Підтримка:
      - CSV (роздільник ; або , або \t), з/без заголовка
      - XLSX
      - Випадок "все в одній колонці": 'AAPL;SPY' / 'AAPL,SPY'
    Повертає DF: ['ticker','bench'] (UPPER, без дублікатів).
    """
    p = mapping_path
    ext = os.path.splitext(p)[1].lower()

    if ext in (".xlsx", ".xls"):
        df = pd.read_excel(p)
    else:
        # 1) спроба autodetect
        try:
            df = pd.read_csv(p, sep=None, engine="python")
        except Exception:
            # 2) спроби з явними роздільниками
            for sep_try in (";", ",", "\t", "|"):
                try:
                    df = pd.read_csv(p, sep=sep_try, engine="python")
                    break
                except Exception:
                    df = None
            if df is None:
                # 3) можливо, файл без заголовка
                try:
                    df = pd.read_csv(p, header=None, sep=None, engine="python")
                except Exception:
                    # 4) остання спроба — явні сепаратори без заголовка
                    for sep_try in (";", ",", "\t", "|"):
                        try:
                            df = pd.read_csv(p, header=None, sep=sep_try, engine="python")
                            break
                        except Exception:
                            df = None
                    if df is None:
                        raise

    # Якщо одна колонка і виглядає як "AAPL;SPY" — сплітимо
    if df.shape[1] == 1:
        col = df.columns[0]
        # намагаємось розбити за ; або , або \t
        s = df[col].astype(str)
        if s.str.contains(";").any():
            parts = s.str.split(";", n=1, expand=True)
        elif s.str.contains(",").any():
            parts = s.str.split(",", n=1, expand=True)
        elif s.str.contains("\t").any():
            parts = s.str.split("\t", n=1, expand=True)
        else:
            raise KeyError("Не можу знайти роздільник між 'ticker' і 'bench'.")
        df = pd.DataFrame({"ticker": parts[0], "bench": parts[1]})

    # Вгадуємо назви колонок
    cols = {c.lower(): c for c in df.columns}
    tcol = cols.get("ticker") or cols.get("symbol")
    bcol = cols.get("bench") or cols.get("benchmark") or cols.get("etf")

    # Якщо заголовків нема, але 2 колонки — приймаємо їх як ticker/bench
    if tcol is None or bcol is None:
        if df.shape[1] >= 2:
            tcol = df.columns[0]
            bcol = df.columns[1]
        else:
            raise KeyError("Потрібні колонки 'ticker' і 'bench' у mapping-файлі.")

    out = (
        df[[tcol, bcol]]
        .rename(columns={tcol: "ticker", bcol: "bench"})
        .dropna()
    )
    out["ticker"] = out["ticker"].astype(str).str.strip().str.upper()
    out["bench"]  = out["bench"].astype(str).str.strip().str.upper()
    out = out[out["ticker"] != ""]
    out = out[out["bench"]  != ""]
    return out.drop_duplicates(ignore_index=True)


# ---------- ВИТЯГ corr/beta ДЛЯ ПАР (X, ФІКСОВАНИЙ BENCH) ----------

def _fetch_corr_beta_pairs(
    x_list: List[str],
    bench: str,
    *,
    period: str = "6 months",
    fmt: str = "json_records",
    batch_size: int = 150,
    min_batch_size: int = 10,
    pause: float = 0.15,
    max_retries: int = 3,
    retry_backoff: float = 0.6,
) -> pd.DataFrame:
    results: List[pd.DataFrame] = []
    i, n = 0, len(x_list)
    b = bench

    while i < n:
        cur_bs = min(batch_size, n - i)
        attempt = 0
        while True:
            xs = x_list[i : i + cur_bs]
            params = {
                "x_tickers": ",".join(xs),
                "y_tickers": b,
                "period": period,
                "as_pivot": False,
                "format": fmt,
            }
            try:
                df_chunk = DatumApi.data_request("/calculations/corr_beta/v2", params)
                if df_chunk is not None and not df_chunk.empty:
                    # лишаємо тільки рядки для потрібного bench (на випадок, якщо API поверне зайве)
                    if "y_ticker" in df_chunk.columns:
                        df_chunk = df_chunk[df_chunk["y_ticker"].astype(str).str.upper() == b]
                    results.append(df_chunk)
                i += len(xs)
                time.sleep(pause)  # пауза тільки після успішного батча
                break
            except Exception as e:
                msg = str(e).lower()
                # 414: зменшуємо ЛИШЕ поточний батч
                if "414" in msg or "uri too large" in msg:
                    if cur_bs <= min_batch_size:
                        print(f"⚠️ 414 навіть при batch={cur_bs}. Пропускаю X[{i}:{i+cur_bs}] для {b}.")
                        i += cur_bs
                        break
                    new_bs = max(min_batch_size, cur_bs // 2)
                    print(f"⚠️ 414 → shrink {cur_bs} → {new_bs} для {b} і повторюю.")
                    cur_bs = new_bs
                    continue

                attempt += 1
                if attempt > max_retries:
                    print(f"⚠️  Пропуск X[{i}:{i+cur_bs}] для {b} після {max_reTRIES} ретраїв. Помилка: {e}")
                    i += cur_bs
                    break
                sleep_s = retry_backoff * (2 ** (attempt - 1))
                print(f"⚠️  {e} → retry {attempt}/{max_retries} через {sleep_s:.1f}s")
                time.sleep(sleep_s)

    return pd.concat(results, ignore_index=True) if results else pd.DataFrame()


# ---------- ГОЛОВНА ФУНКЦІЯ ----------

def corr_beta_from_mapping_to_parquet(
    mapping_path: str,
    out_parquet_path: str,
    *,
    period: str = "3 months",
    batch_size: int = 150,
    min_batch_size: int = 10,
    pause: float = 0.15,
    max_retries: int = 3,
    retry_backoff: float = 0.6,
) -> str:
    """
    Читає mapping (ticker, bench) будь-якого адекватного формату,
    групує тікери по бенчу, витягує corr/beta для кожної групи
    і потоково пише результат у Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для запису .parquet")

    map_df = _read_mapping(mapping_path)

    groups: Dict[str, List[str]] = (
        map_df.groupby("bench")["ticker"].apply(lambda s: sorted(set(s.tolist()))).to_dict()
    )

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    writer: Optional[pq.ParquetWriter] = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START corr/beta → {out_parquet_path} | період={period} | бенчів={len(groups)}")

    for b, xs in sorted(groups.items()):
        if not xs:
            continue
        print(f"— Bench {b}: {len(xs)} тикерів")
        df_b = _fetch_corr_beta_pairs(
            xs, b,
            period=period,
            batch_size=batch_size,
            min_batch_size=min_batch_size,
            pause=pause,
            max_retries=max_retries,
            retry_backoff=retry_backoff,
        )
        if df_b is None or df_b.empty:
            continue

        # типи
        for col in ("corr", "beta"):
            if col in df_b.columns:
                df_b[col] = pd.to_numeric(df_b[col], errors="coerce")

        table = pa.Table.from_pandas(df_b, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression="snappy")
        writer.write_table(table)
        total_rows += len(df_b)

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path

In [28]:
out_path = corr_beta_from_mapping_to_parquet(
    mapping_path=str(WORK_DIR / "ticker_bench_.csv"),
    out_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    period="3 months",
    batch_size=150,
    pause=0.15,
)
print("Результат:", out_path)

▶️ START corr/beta → C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet | період=3 months | бенчів=10
— Bench BITO: 44 тикерів

— Bench GDX: 125 тикерів

— Bench IWM: 1939 тикерів

— Bench KRE: 185 тикерів

— Bench KWEB: 38 тикерів

— Bench QQQ: 722 тикерів

— Bench SOXL: 16 тикерів

— Bench SPY: 3263 тикерів

— Bench XLE: 193 тикерів

— Bench XLF: 248 тикерів

✅ DONE rows=6,773 → C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet  in 19.2s
Результат: C:\datum-api-examples-main\OriON\CRACEN\work\corr_beta_pairs.parquet

In [29]:

y_list = ["SPY", "IWM", "GDX", "XLF", "QQQ", "XLE", "KRE", "BITO", "SOXL"]

In [30]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _load_corrbeta_mapping_parquet(path: str) -> pd.DataFrame:
    """
    Читає parquet з мапою:
      A) ['x_ticker','y_ticker','corr','beta'] (API-форма), або
      B) ['ticker','bench','corr','beta'] (вже нормалізована).
    Повертає DF: ['ticker','bench','corr','beta'] (UPPER, без дублікатів; при дублях
    лишаємо рядок із найбільшою corr).
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow для читання parquet.")

    # Читаємо БЕЗ фільтра колонок — так надійніше для різних схем
    table = pq.read_table(path)
    df = table.to_pandas()

    # нормалізуємо імена колонок для пошуку
    name_map = {c: c.strip().lower() for c in df.columns}
    inv_map = {v: k for k, v in name_map.items()}

    has_api    = ("x_ticker" in inv_map) and ("y_ticker" in inv_map)
    has_direct = ("ticker" in inv_map) and ("bench" in inv_map)

    if not (has_api or has_direct):
        # допоміжна підказка, що саме є в файлі
        available = ", ".join(df.columns.astype(str).tolist())
        raise KeyError(
            "Mapping parquet повинен містити або ['x_ticker','y_ticker','corr','beta'], "
            "або ['ticker','bench','corr','beta'].\n"
            f"У файлі наявні колонки: {available}"
        )

    if has_api:
        df = df.rename(columns={
            inv_map["x_ticker"]: "ticker",
            inv_map["y_ticker"]: "bench"
        })
    else:
        df = df.rename(columns={
            inv_map["ticker"]: "ticker",
            inv_map["bench"]:  "bench"
        })

    # corr/beta можуть бути відсутні — створимо
    if "corr" not in name_map.values():
        df["corr"] = pd.NA
    else:
        df = df.rename(columns={inv_map["corr"]: "corr"})
    if "beta" not in name_map.values():
        df["beta"] = pd.NA
    else:
        df = df.rename(columns={inv_map["beta"]: "beta"})

    # залишаємо тільки потрібне
    keep = [c for c in ["ticker", "bench", "corr", "beta"] if c in df.columns]
    df = df[keep].copy()

    # нормалізація значень
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["bench"]  = df["bench"].astype(str).str.strip().str.upper()
    if "corr" in df.columns:
        df["corr"] = pd.to_numeric(df["corr"], errors="coerce")
    if "beta" in df.columns:
        df["beta"] = pd.to_numeric(df["beta"], errors="coerce")

    # якщо раптом на один тикер кілька рядків — візьмемо з найбільшою corr
    if "corr" in df.columns:
        df = (df.sort_values(["ticker", "corr"], ascending=[True, False])
                .drop_duplicates(subset=["ticker"], keep="first")
                .reset_index(drop=True))
    else:
        df = df.drop_duplicates(subset=["ticker"], keep="first").reset_index(drop=True)

    # гарантуємо повний набір стовпців
    for c in ("corr", "beta"):
        if c not in df.columns:
            df[c] = pd.NA

    return df[["ticker", "bench", "corr", "beta"]]


def attach_bench_corr_beta_parquet(
    input_parquet_path: str,
    corrbeta_parquet_path: str,
    out_parquet_path: str,
    *,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 4,
    insert_before: str = "pct_vs_prev_close",
    compression: str = "snappy",
) -> str:
    """
    Потоково читає великий Parquet (інтрадеї), мерджить 'bench','corr','beta' з іншого
    Parquet (мапа) по 'ticker' і пише новий Parquet.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pa, pq) для роботи з Parquet.")

    t0 = time.time()
    mapping = _load_corrbeta_mapping_parquet(corrbeta_parquet_path)
    if round_decimals is not None:
        mapping["corr"] = mapping["corr"].round(round_decimals)
        mapping["beta"] = mapping["beta"].round(round_decimals)

    if os.path.exists(out_parquet_path):
        os.remove(out_parquet_path)

    pf = pq.ParquetFile(input_parquet_path)
    writer = None
    total_rows = 0
    batches = 0

    print(f"▶️ START merge → {out_parquet_path}")

    for batch in pf.iter_batches(batch_size=batch_rows):  # читаємо всі колонки
        batches += 1
        df = batch.to_pandas()

        if "ticker" not in df.columns:
            raise KeyError("У вхідному parquet відсутній стовпець 'ticker'.")
        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(mapping, on="ticker", how="left", validate="m:1")

        # Переставимо нові колонки за потреби
        if insert_before in merged.columns:
            cols = list(merged.columns)
            for c in ("bench", "corr", "beta"):
                if c in cols: cols.remove(c)
            idx = cols.index(insert_before)
            new_cols = cols[:idx] + ["bench", "corr", "beta"] + cols[idx:]
            merged = merged[new_cols]
        else:
            base = [c for c in merged.columns if c not in ("bench","corr","beta")]
            merged = merged[base + ["bench","corr","beta"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_parquet_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if batches % log_every_batches == 0:
            print(f"[batch {batches:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_parquet_path}  in {time.time()-t0:,.1f}s")
    return out_parquet_path


# опціональний аліас під старе ім’я (щоб існуючий код не міняти)
def attach_bench_corr_beta_file(**kwargs) -> str:
    return attach_bench_corr_beta_parquet(**kwargs)

In [31]:
out_path = attach_bench_corr_beta_parquet(
    input_parquet_path=str(WORK_DIR / "premarket_rows_enriched_with_pct.parquet"),
    corrbeta_parquet_path=str(WORK_DIR / "corr_beta_pairs.parquet"),
    out_parquet_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    batch_rows=2_000_000,
    round_decimals=4,
    insert_before="pct_vs_prev_close",
    compression="snappy",
)
print("Готово:", out_path)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

[batch    5] rows=10,000,000  elapsed=9.8s

[batch   10] rows=20,000,000  elapsed=19.4s

[batch   15] rows=30,000,000  elapsed=29.1s

[batch   20] rows=40,000,000  elapsed=38.7s

[batch   25] rows=50,000,000  elapsed=48.4s

[batch   30] rows=60,000,000  elapsed=58.2s

[batch   35] rows=70,000,000  elapsed=68.0s

[batch   40] rows=80,000,000  elapsed=77.7s

[batch   45] rows=90,000,000  elapsed=87.3s

[batch   50] rows=100,000,000  elapsed=97.0s

[batch   55] rows=110,000,000  elapsed=106.7s

✅ DONE rows=111,034,041 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet  in 107.8s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_final.parquet

In [32]:
import os
import pandas as pd

def peek_parquet(path: str, n: int = 20, columns=None):
    """
    Легкий перегляд великого Parquet:
      - друкує шлях, кількість рядків (із метаданих), кількість колонок і їх назви
      - потоково читає і показує перші n рядків (optionally лише вказані columns)
      - повертає DataFrame із прев’ю (n рядків)
    Вимагає pyarrow.
    """
    try:
        import pyarrow.parquet as pq
    except Exception as e:
        raise RuntimeError(
            "Потрібен пакет 'pyarrow' для читання parquet. Встанови: pip install pyarrow"
        ) from e

    if not os.path.exists(path):
        raise FileNotFoundError(path)

    pf = pq.ParquetFile(path)
    total_rows = pf.metadata.num_rows if pf.metadata is not None else None
    schema_cols = [f.name for f in pf.schema_arrow]
    print(f"Файл: {path}")
    if total_rows is not None:
        print(f"Рядків (meta): {total_rows:,}")
    print(f"Колонок: {len(schema_cols)}")
    print("Схема:", ", ".join(schema_cols))

    # Збираємо перші n рядків потоково
    need = n
    parts = []
    for batch in pf.iter_batches(batch_size=min(100_000, max(1, n)), columns=columns):
        df_part = batch.to_pandas()
        parts.append(df_part)
        need -= len(df_part)
        if need <= 0:
            break

    head_df = pd.concat(parts, ignore_index=True).head(n) if parts else pd.DataFrame()
    # Коротка діагностика по ключових нових стовпцях (якщо є)
    for c in ["bench", "corr", "beta", "pct_vs_prev_close"]:
        if c in head_df.columns:
            na = int(head_df[c].isna().sum())
            print(f"NaN у '{c}' (у прев'ю): {na}/{len(head_df)}")

    print("\nПерші рядки:")
    with pd.option_context("display.max_rows", n, "display.max_columns", 200, "display.width", 200):
        print(head_df)

    return head_df

In [33]:
peek_parquet("CRACEN/work/premarket_rows_final.parquet", n=620)

Файл: CRACEN/work/premarket_rows_final.parquet
Рядків (meta): 111,034,041
Колонок: 14
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta
NaN у 'bench' (у прев'ю): 0/620
NaN у 'corr' (у прев'ю): 0/620
NaN у 'beta' (у прев'ю): 0/620

Перші рядки:
    ticker                  dt           o           h           l           c         v        date    open  prev_close  Stack% bench  corr  beta
0        A 2025-12-21 20:52:00  137.809998  137.809998  137.800003  137.800003       5.0  2025-12-21     NaN         NaN     NaN   SPY  0.81  0.93
1        A 2025-12-21 20:55:00  137.800003  137.800003  137.800003  137.800003       2.0  2025-12-21     NaN         NaN     NaN   SPY  0.81  0.93
2        A 2025-12-21 21:13:00  136.410004  136.410004  136.410004  136.410004       1.0  2025-12-21     NaN         NaN     NaN   SPY  0.81  0.93
3        A 2025-12-22 01:27:00  136.990005  136.990005  136.990005  136.990005      36.0  2025-12-22  137.62      137.22   -0.17   SPY  0.81  0.93
4        A 2025-12-22 03:38:00  137.179993  137.179993  137.179993  137.179993       1.0  2025-12-22  137.62      137.22   -0.03   SPY  0.81  0.93
5        A 2025-12-22 09:29:00  137.460007  137.470001  137.460007  137.470001     531.0  2025-12-22  137.62      137.22    0.17   SPY  0.81  0.93
6        A 2025-12-22 09:30:00  137.619995  137.619995  137.229996  137.229996   10639.0  2025-12-22  137.62      137.22    0.29   SPY  0.81  0.93
7        A 2025-12-22 09:31:00  137.399994  137.399994  137.205002  137.205002     200.0  2025-12-22  137.62      137.22    0.13   SPY  0.81  0.93
8        A 2025-12-22 09:32:00  137.516998  137.990005  137.516998  137.990005     220.0  2025-12-22  137.62      137.22    0.22   SPY  0.81  0.93
9        A 2025-12-22 09:33:00  137.899994  138.139999  137.824997  137.824997     900.0  2025-12-22  137.62      137.22    0.50   SPY  0.81  0.93
10       A 2025-12-22 09:34:00  138.279999  138.279999  137.789993  137.789993    1862.0  2025-12-22  137.62      137.22    0.77   SPY  0.81  0.93
11       A 2025-12-22 09:35:00  138.020004  138.020004  138.020004  138.020004     300.0  2025-12-22  137.62      137.22    0.58   SPY  0.81  0.93
12       A 2025-12-22 09:36:00  138.080002  138.080002  138.020004  138.039993    1672.0  2025-12-22  137.62      137.22    0.63   SPY  0.81  0.93
13       A 2025-12-22 09:37:00  138.039993  138.039993  137.431000  137.714996    1811.0  2025-12-22  137.62      137.22    0.60   SPY  0.81  0.93
14       A 2025-12-22 09:38:00  137.809998  137.809998  137.699997  137.699997     200.0  2025-12-22  137.62      137.22    0.43   SPY  0.81  0.93
15       A 2025-12-22 09:40:00  137.550003  137.615005  137.544998  137.544998     600.0  2025-12-22  137.62      137.22    0.24   SPY  0.81  0.93
16       A 2025-12-22 09:41:00  137.544998  137.544998  137.544998  137.544998     396.0  2025-12-22  137.62      137.22    0.24   SPY  0.81  0.93
17       A 2025-12-22 09:43:00  137.639999  137.639999  137.350006  137.350006    1357.0  2025-12-22  137.62      137.22    0.31   SPY  0.81  0.93
18       A 2025-12-22 09:44:00  137.470001  137.479996  137.320007  137.479996    1228.0  2025-12-22  137.62      137.22    0.18   SPY  0.81  0.93
19       A 2025-12-22 09:46:00  137.509995  137.509995  137.369995  137.395004     715.0  2025-12-22  137.62      137.22    0.21   SPY  0.81  0.93
20       A 2025-12-22 09:47:00  137.395004  137.509995  137.339996  137.509995     420.0  2025-12-22  137.62      137.22    0.13   SPY  0.81  0.93
21       A 2025-12-22 09:48:00  137.429993  137.429993  137.380005  137.380005     200.0  2025-12-22  137.62      137.22    0.15   SPY  0.81  0.93
22       A 2025-12-22 09:49:00  137.360001  137.559998  137.360001  137.559998     968.0  2025-12-22  137.62      137.22    0.10   SPY  0.81  0.93
23       A 2025-12-22 09:50:00  137.639999  137.660004  137.570007  137.639999    1079.0  2025-12-22  137.62      137.22    0.31   SPY  0.81  0.93
24       A 2025-12-22 09:51:00  137.610001  137.639999  137.479996  137.509995     974.0  2025-12-22  137.62      137.22    0.28   SPY  0.81  0.93
25       A 2025-12-22 09:52:00  137.470001  137.470001  137.470001  137.470001     270.0  2025-12-22  137.62      137.22    0.18   SPY  0.81  0.93
26       A 2025-12-22 09:53:00  137.410004  137.550003  137.410004  137.550003     901.0  2025-12-22  137.62      137.22    0.14   SPY  0.81  0.93
27       A 2025-12-22 09:54:00  137.565002  137.565002  137.565002  137.565002     200.0  2025-12-22  137.62      137.22    0.25   SPY  0.81  0.93
28       A 2025-12-22 09:55:00  137.669998  137.690002  137.669998  137.690002     865.0  2025-12-22  137.62      137.22    0.33   SPY  0.81  0.93
29       A 2025-12-22 09:56:00  137.770004  137.770004  137.705002  137.710007    2045.0  2025-12-22  137.62      137.22    0.40   SPY  0.81  0.93
30       A 2025-12-22 09:57:00  137.809998  137.820007  137.720001  137.729996    2131.0  2025-12-22  137.62      137.22    0.43   SPY  0.81  0.93
31       A 2025-12-22 09:58:00  137.839996  137.839996  137.779999  137.789993    1130.0  2025-12-22  137.62      137.22    0.45   SPY  0.81  0.93
32       A 2025-12-22 09:59:00  137.750000  137.750000  137.600006  137.669998    1437.0  2025-12-22  137.62      137.22    0.39   SPY  0.81  0.93
33       A 2025-12-22 10:00:00  137.580002  137.580002  137.382507  137.382507    1079.0  2025-12-22  137.62      137.22    0.26   SPY  0.81  0.93
34       A 2025-12-22 10:01:00  137.440002  137.440002  137.440002  137.440002     120.0  2025-12-22  137.62      137.22    0.16   SPY  0.81  0.93
35       A 2025-12-22 10:02:00  137.539993  137.539993  137.539993  137.539993     425.0  2025-12-22  137.62      137.22    0.23   SPY  0.81  0.93
36       A 2025-12-22 10:04:00  137.589996  137.589996  137.524994  137.524994     300.0  2025-12-22  137.62      137.22    0.27   SPY  0.81  0.93
37       A 2025-12-22 10:05:00  137.479996  137.479996  137.479996  137.479996     100.0  2025-12-22  137.62      137.22    0.19   SPY  0.81  0.93
38       A 2025-12-22 10:06:00  137.410004  137.455002  137.309998  137.350006    2348.0  2025-12-22  137.62      137.22    0.14   SPY  0.81  0.93
39       A 2025-12-22 10:07:00  137.365005  137.389999  137.365005  137.369995    1628.0  2025-12-22  137.62      137.22    0.11   SPY  0.81  0.93
40       A 2025-12-22 10:08:00  137.365005  137.470001  137.362503  137.365005    2788.0  2025-12-22  137.62      137.22    0.11   SPY  0.81  0.93
41       A 2025-12-22 10:09:00  137.365005  137.369995  137.350006  137.369995     600.0  2025-12-22  137.62      137.22    0.11   SPY  0.81  0.93
42       A 2025-12-22 10:10:00  137.389999  137.389999  137.380005  137.380005     200.0  2025-12-22  137.62      137.22    0.12   SPY  0.81  0.93
43       A 2025-12-22 10:12:00  137.320007  137.320007  137.320007  137.320007     100.0  2025-12-22  137.62      137.22    0.07   SPY  0.81  0.93
44       A 2025-12-22 10:13:00  137.309998  137.479996  137.309998  137.479996     246.0  2025-12-22  137.62      137.22    0.07   SPY  0.81  0.93
45       A 2025-12-22 10:14:00  137.410004  137.472504  137.350006  137.472504    1347.0  2025-12-22  137.62      137.22    0.14   SPY  0.81  0.93
46       A 2025-12-22 10:15:00  137.339996  137.389999  137.309998  137.352997     922.0  2025-12-22  137.62      137.22    0.09   SPY  0.81  0.93
47       A 2025-12-22 10:16:00  137.309998  137.520004  137.309998  137.520004    1445.0  2025-12-22  137.62      137.22    0.07   SPY  0.81  0.93
48       A 2025-12-22 10:17:00  137.600693  137.714996  137.600693  137.714996     285.0  2025-12-22  137.62      137.22    0.28   SPY  0.81  0.93
49       A 2025-12-22 10:18:00  137.630005  137.630005  137.619995  137.619995     600.0  2025-12-22  137.62      137.22    0.30   SPY  0.81  0.93
50       A 2025-12-22 10:19:00  137.625000  137.710007  137.559998  137.710007    1601.0  2025-12-22  137.62      137.22    0.30   SPY  0.81  0.93
51       A 2025-12-22 10:20:00  137.755005  137.779999  137.755005  137.774994     450.0  2025-12-22  137.62      137.22    0.39   SPY  0.81  0.93
52       A 2025-12-22 10:21:00  137.772507  137.860001  137.772507  137.860001     200.0  2025-12-22  137.62      137.22    0.40   SPY  0.81  0.93
53       A 2025-12-22 10:22:00  137.877502  138.020004  137.877502  138.020004    2000.0  2025-12-22  137.62      137.22    0.48   SPY  0.81  0.93
54       A 2025-12-22 10:23:00  138.020004  138.100006  137.960007  138.100006    1125.0  2025-12-22  137.62      137.22    0.58   SPY  0.81  0.93
55       A 2025-12-22 10:24:00  138.100006  138.279999  138.089996  138.149994    3817.0  2025-12-22  137.62      137.22    0.64   SPY  0.81  0.93
56       A 2025-12-22 10:25:00  138.080002  138.164993  138.000000  138.020004     900.0  2025-12-22  137.62      137.22    0.63   SPY  0.81  0.93
57       A 2025-12-22 10:26:00  138.050003  138.190002  138.050003  138.190002    1143.0  2025-12-22  137.62      137.22    0.60   SPY  0.81  0.93
58       A 2025-12-22 10:27:00  138.040100  138.330002  138.040100  138.330002    1650.0  2025-12-22  137.62      137.22    0.60   SPY  0.81  0.93
59       A 2025-12-22 10:28:00  138.335007  138.335007  138.179993  138.179993    5249.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93
60       A 2025-12-22 10:29:00  138.320007  138.320007  138.110001  138.210007    1333.0  2025-12-22  137.62      137.22    0.80   SPY  0.81  0.93
61       A 2025-12-22 10:30:00  138.289993  138.365005  138.199997  138.289993   13039.0  2025-12-22  137.62      137.22    0.78   SPY  0.81  0.93
62       A 2025-12-22 10:31:00  138.315002  138.354996  138.169998  138.190002    4200.0  2025-12-22  137.62      137.22    0.80   SPY  0.81  0.93
63       A 2025-12-22 10:32:00  138.190002  138.389999  138.190002  138.369995    1928.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93
64       A 2025-12-22 10:33:00  138.354996  138.354996  138.270004  138.270004     200.0  2025-12-22  137.62      137.22    0.83   SPY  0.81  0.93
65       A 2025-12-22 10:34:00  138.270004  138.270004  138.255005  138.255005     404.0  2025-12-22  137.62      137.22    0.77   SPY  0.81  0.93
66       A 2025-12-22 10:35:00  138.139999  138.199997  138.139999  138.199997     700.0  2025-12-22  137.62      137.22    0.67   SPY  0.81  0.93
67       A 2025-12-22 10:36:00  138.250000  138.255005  138.225006  138.225006     300.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93
68       A 2025-12-22 10:37:00  138.119995  138.220001  138.119995  138.220001     303.0  2025-12-22  137.62      137.22    0.66   SPY  0.81  0.93
69       A 2025-12-22 10:38:00  138.110001  138.169998  138.100006  138.169998     900.0  2025-12-22  137.62      137.22    0.65   SPY  0.81  0.93
70       A 2025-12-22 10:39:00  138.169998  138.169998  138.169998  138.169998     100.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93
71       A 2025-12-22 10:40:00  138.190002  138.210007  138.190002  138.190002    1597.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93
72       A 2025-12-22 10:41:00  138.195007  138.279999  138.080002  138.205002    2970.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93
73       A 2025-12-22 10:42:00  138.199997  138.240005  138.199997  138.240005     600.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93
74       A 2025-12-22 10:43:00  138.255005  138.309998  138.255005  138.309998     672.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93
75       A 2025-12-22 10:44:00  138.255005  138.259995  138.255005  138.259995     900.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93
76       A 2025-12-22 10:45:00  138.235001  138.380005  138.190002  138.324997    4648.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93
77       A 2025-12-22 10:46:00  138.324997  138.330002  138.324997  138.330002     200.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93
78       A 2025-12-22 10:47:00  138.330002  138.490005  138.300003  138.490005   12601.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93
79       A 2025-12-22 10:48:00  138.429993  138.520004  138.429993  138.520004    1929.0  2025-12-22  137.62      137.22    0.88   SPY  0.81  0.93
80       A 2025-12-22 10:49:00  138.520004  138.524994  138.470001  138.470001     520.0  2025-12-22  137.62      137.22    0.95   SPY  0.81  0.93
81       A 2025-12-22 10:50:00  138.524994  138.524994  138.524994  138.524994     100.0  2025-12-22  137.62      137.22    0.95   SPY  0.81  0.93
82       A 2025-12-22 10:51:00  138.550003  138.660004  138.544998  138.630005    1818.0  2025-12-22  137.62      137.22    0.97   SPY  0.81  0.93
83       A 2025-12-22 10:52:00  138.615005  138.615005  138.615005  138.615005     100.0  2025-12-22  137.62      137.22    1.02   SPY  0.81  0.93
84       A 2025-12-22 10:53:00  138.610001  138.615005  138.610001  138.615005     600.0  2025-12-22  137.62      137.22    1.01   SPY  0.81  0.93
85       A 2025-12-22 10:54:00  138.654999  138.660004  138.610001  138.660004    1855.0  2025-12-22  137.62      137.22    1.05   SPY  0.81  0.93
86       A 2025-12-22 10:55:00  138.699997  138.710007  138.699997  138.710007     500.0  2025-12-22  137.62      137.22    1.08   SPY  0.81  0.93
87       A 2025-12-22 10:56:00  138.679993  138.679993  138.229996  138.229996    7661.0  2025-12-22  137.62      137.22    1.06   SPY  0.81  0.93
88       A 2025-12-22 10:57:00  138.229996  138.259995  138.210007  138.229996    1313.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93
89       A 2025-12-22 10:58:00  138.210007  138.210007  138.210007  138.210007     100.0  2025-12-22  137.62      137.22    0.72   SPY  0.81  0.93
90       A 2025-12-22 10:59:00  138.210007  138.279999  138.070007  138.080002    4665.0  2025-12-22  137.62      137.22    0.72   SPY  0.81  0.93
91       A 2025-12-22 11:00:00  138.110001  138.130005  137.940002  137.990005    7578.0  2025-12-22  137.62      137.22    0.65   SPY  0.81  0.93
92       A 2025-12-22 11:01:00  137.979996  137.979996  137.940002  137.940002     757.0  2025-12-22  137.62      137.22    0.55   SPY  0.81  0.93
93       A 2025-12-22 11:02:00  137.945007  138.199997  137.945007  138.199997    5810.0  2025-12-22  137.62      137.22    0.53   SPY  0.81  0.93
94       A 2025-12-22 11:03:00  138.289993  138.289993  138.289993  138.289993    2680.0  2025-12-22  137.62      137.22    0.78   SPY  0.81  0.93
95       A 2025-12-22 11:04:00  138.080002  138.080002  138.080002  138.080002     117.0  2025-12-22  137.62      137.22    0.63   SPY  0.81  0.93
96       A 2025-12-22 11:06:00  138.169998  138.214996  138.169998  138.214996     652.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93
97       A 2025-12-22 11:07:00  138.214996  138.214996  138.214996  138.214996     200.0  2025-12-22  137.62      137.22    0.73   SPY  0.81  0.93
98       A 2025-12-22 11:08:00  138.149994  138.179993  138.130005  138.179993    1208.0  2025-12-22  137.62      137.22    0.68   SPY  0.81  0.93
99       A 2025-12-22 11:09:00  138.289993  138.289993  138.229996  138.270004     400.0  2025-12-22  137.62      137.22    0.78   SPY  0.81  0.93
100      A 2025-12-22 11:10:00  138.330002  138.429993  138.330002  138.429993     900.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93
101      A 2025-12-22 11:11:00  138.330002  138.360001  138.309998  138.309998    2250.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93
102      A 2025-12-22 11:13:00  138.240005  138.315994  138.240005  138.315002    1560.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93
103      A 2025-12-22 11:14:00  138.315002  138.315002  138.315002  138.315002     388.0  2025-12-22  137.62      137.22    0.80   SPY  0.81  0.93
104      A 2025-12-22 11:15:00  138.380005  138.380005  138.324997  138.324997     333.0  2025-12-22  137.62      137.22    0.85   SPY  0.81  0.93
105      A 2025-12-22 11:16:00  138.250000  138.309998  138.190002  138.190002    1300.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93
106      A 2025-12-22 11:17:00  138.199997  138.199997  138.199997  138.199997     200.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93
107      A 2025-12-22 11:18:00  138.164993  138.164993  138.164993  138.164993     200.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93
108      A 2025-12-22 11:19:00  138.110001  138.110001  138.110001  138.110001     100.0  2025-12-22  137.62      137.22    0.65   SPY  0.81  0.93
109      A 2025-12-22 11:20:00  138.160004  138.160004  138.110001  138.110001    1209.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93
110      A 2025-12-22 11:21:00  138.110001  138.169998  138.110001  138.169998     200.0  2025-12-22  137.62      137.22    0.65   SPY  0.81  0.93
111      A 2025-12-22 11:22:00  138.250000  138.250000  138.250000  138.250000     200.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93
112      A 2025-12-22 11:23:00  138.229996  138.240005  138.172501  138.172501     550.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93
113      A 2025-12-22 11:24:00  138.179993  138.179993  138.179993  138.179993     100.0  2025-12-22  137.62      137.22    0.70   SPY  0.81  0.93
114      A 2025-12-22 11:25:00  138.229996  138.229996  138.139999  138.139999     277.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93
115      A 2025-12-22 11:26:00  138.164993  138.164993  138.164993  138.164993     200.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93
116      A 2025-12-22 11:27:00  138.164993  138.164993  138.164993  138.164993     100.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93
117      A 2025-12-22 11:28:00  138.169998  138.175003  138.169998  138.175003     400.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93
118      A 2025-12-22 11:29:00  138.160004  138.250000  138.160004  138.214996    1043.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93
119      A 2025-12-22 11:30:00  138.214996  138.220001  138.214996  138.220001     546.0  2025-12-22  137.62      137.22    0.73   SPY  0.81  0.93
120      A 2025-12-22 11:31:00  138.250000  138.369995  138.250000  138.330002    1068.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93
121      A 2025-12-22 11:32:00  138.289993  138.440002  138.279999  138.429993    4000.0  2025-12-22  137.62      137.22    0.78   SPY  0.81  0.93
122      A 2025-12-22 11:33:00  138.365005  138.365005  138.365005  138.365005     200.0  2025-12-22  137.62      137.22    0.83   SPY  0.81  0.93
123      A 2025-12-22 11:34:00  138.270004  138.389999  138.250000  138.274994    1357.0  2025-12-22  137.62      137.22    0.77   SPY  0.81  0.93
124      A 2025-12-22 11:35:00  138.335007  138.335007  138.335007  138.335007     100.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93
125      A 2025-12-22 11:36:00  138.270004  138.270004  138.259995  138.259995     400.0  2025-12-22  137.62      137.22    0.77   SPY  0.81  0.93
126      A 2025-12-22 11:37:00  138.259995  138.500000  138.220001  138.440002    7079.0  2025-12-22  137.62      137.22    0.76   SPY  0.81  0.93
127      A 2025-12-22 11:38:00  138.529999  138.529999  138.388000  138.388000     700.0  2025-12-22  137.62      137.22    0.95   SPY  0.81  0.93
128      A 2025-12-22 11:39:00  138.470001  138.660004  138.470001  138.630005    6674.0  2025-12-22  137.62      137.22    0.91   SPY  0.81  0.93
129      A 2025-12-22 11:40:00  138.630005  138.669998  138.600006  138.669998    6837.0  2025-12-22  137.62      137.22    1.03   SPY  0.81  0.93
130      A 2025-12-22 11:41:00  138.600006  138.709900  138.500000  138.500000    1470.0  2025-12-22  137.62      137.22    1.01   SPY  0.81  0.93
131      A 2025-12-22 11:42:00  138.460007  138.470001  138.449997  138.470001     681.0  2025-12-22  137.62      137.22    0.90   SPY  0.81  0.93
132      A 2025-12-22 11:43:00  138.440002  138.440002  138.410004  138.429993     878.0  2025-12-22  137.62      137.22    0.89   SPY  0.81  0.93

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta
0,A,2025-12-21 20:52:00,137.809998,137.809998,137.800003,137.800003,5.0,2025-12-21,NaN,NaN,NaN,SPY,0.81,0.93
1,A,2025-12-21 20:55:00,137.800003,137.800003,137.800003,137.800003,2.0,2025-12-21,NaN,NaN,NaN,SPY,0.81,0.93
2,A,2025-12-21 21:13:00,136.410004,136.410004,136.410004,136.410004,1.0,2025-12-21,NaN,NaN,NaN,SPY,0.81,0.93
3,A,2025-12-22 01:27:00,136.990005,136.990005,136.990005,136.990005,36.0,2025-12-22,137.62,137.22,-0.17,SPY,0.81,0.93
4,A,2025-12-22 03:38:00,137.179993,137.179993,137.179993,137.179993,1.0,2025-12-22,137.62,137.22,-0.03,SPY,0.81,0.93
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,A,2025-12-23 14:08:00,138.520004,138.520004,138.520004,138.520004,694.0,2025-12-23,138.17,138.50,0.01,SPY,0.81,0.93
616,A,2025-12-23 14:09:00,138.580002,138.580002,138.580002,138.580002,100.0,2025-12-23,138.17,138.50,0.06,SPY,0.81,0.93
617,A,2025-12-23 14:10:00,138.580002,138.580002,138.490005,138.490005,1505.0,2025-12-23,138.17,138.50,0.06,SPY,0.81,0.93
618,A,2025-12-23 14:11:00,138.554993,138.565506,138.550003,138.550003,480.0,2025-12-23,138.17,138.50,0.04,SPY,0.81,0.93
619,A,2025-12-23 14:12:00,138.500000,138.500000,138.500000,138.500000,213.0,2025-12-23,138.17,138.50,0.00,SPY,0.81,0.93

In [34]:
# список тикерів
tickers = ['SPY','IWM','GDX','XLF','QQQ','XLE','KRE','BITO','KWEB','SOXL']

# створення DataFrame
df_bench = pd.DataFrame(tickers, columns=['ticker'])

In [35]:
keep = ["ticker","dt","o","h","l","c","v"]

errs = fetch_intraday_v3_for_all_tickers(
    tickers_df=df_bench,
    start= start,
    end= end,
    interval=1,
    chunk_days=30,
    parallel_chunks=True,
    max_workers_chunks=12,
    parallel_tickers=True,
    max_workers_tickers=3,
    save_every=50,
    out_dir=str(ETF_DIR),
    out_prefix="intraday",
    gzip=True,
    keep_columns=keep,
    verbose=True,
    include_blue_ocean=True,   # ⬅️ додай це
)

▶ Починаємо: 10 тікерів (пропущено 0 по старому маніфесту) | 2025-12-20 00:00:00 → 2026-03-20 23:59:59 | interval=1 | next batch #0029 | run=4954504a

   workers: tickers=3, chunks=12 | blue_ocean=True | day-manifest=True

   day-manifest: повністю готових тікерів пропущено = 0

   📉 пропущені дні (в межах window): 2025-12-20 → 2026-03-19 (90 днів)

   📈 обробляються дні: 2026-03-20 → 2026-03-20 (1 днів)

   psutil · старт · 🧠 RAM: 2,459.2 MB

[10/10] ✓ SOXL: 1,200 рядків | 100.00% | ETA 00:00

   ⏳ перед flush · 🧠 RAM: 2,442.3 MB

💾 batch 29 → 8,941 рядків (всього 8,941 у цьому запуску) → C:\datum-api-examples-main\OriON\CRACEN\work\ETF\intraday_0029.csv.gz

   ✅ після flush · 🧠 RAM: 2,446.1 MB

   🔚 фінал · 🧠 RAM: 2,446.1 MB

🏁 Готово. Нових рядків: 8,941 → C:\datum-api-examples-main\OriON\CRACEN\work\ETF | Час: 00:02

In [36]:
collect_premarket_by_day_stream(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "premarket_etf_rows.parquet"),
    start_time="00:00:00",
    end_time="23:59:00",
    aggregate=False,
    chunksize=150_000,
)

▶️ START: C:\datum-api-examples-main\OriON\CRACEN\work\ETF/intraday_*.csv.gz → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  chunksize=150,000

✅ DONE  in=944,356 → out=944,356  to C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows.parquet  in 2.1s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_etf_rows.parquet'

In [37]:
df_oc = build_oc_from_intraday_folder(
    folder=str(ETF_DIR),
    out_path=str(WORK_DIR / "oc_etf.parquet"),
    chunksize=250_000
)
print(df_oc.head())

  ticker        date   open  close
0   BITO  2025-10-28  18.96  18.72
1   BITO  2025-10-29  18.70  18.21
2   BITO  2025-10-30  17.83  17.53
3   BITO  2025-10-31  18.09  18.07
4   BITO  2025-11-03  16.89  16.74

In [38]:
import os
import gc
import time
import pandas as pd

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None


def enrich_with_day_open_and_prev_close(df_intraday: pd.DataFrame,
                                        df_oc: pd.DataFrame) -> pd.DataFrame:
    """
    Додає до кожного рядка інтрадею 'open' дня та 'prev_close' (учорашній close).
    Очікує в df_intraday: ['ticker','dt',...]
              в df_oc:       ['ticker','date','open','close']
    """
    out = df_intraday.copy()
    out["dt"] = pd.to_datetime(out["dt"], errors="coerce")
    out = out[out["dt"].notna()].copy()
    out["date"] = out["dt"].dt.date.astype("string")

    oc = df_oc.copy()
    oc["date"] = pd.to_datetime(oc["date"], errors="coerce").dt.date.astype("string")

    oc_sorted = (
        oc.sort_values(["ticker", "date"])
          .groupby("ticker", as_index=False, group_keys=False)
          .apply(lambda d: d.assign(prev_close=d["close"].shift(1)))
    )

    right = oc_sorted[["ticker", "date", "open", "prev_close"]].copy()
    out = out.merge(right, on=["ticker", "date"], how="left", validate="m:1")
    out = out.sort_values(["ticker", "dt"]).reset_index(drop=True)
    return out


def merge_intraday_and_oc_to_file(
    intraday_parquet_path: str,
    oc_parquet_path: str,
    out_path: str,
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
):
    """
    Читає великий Parquet батчами (через pyarrow.parquet.ParquetFile.iter_batches),
    мерджить із денними open/prev_close з oc.parquet і пише у out_path
    (.parquet або .csv/.csv.gz).

    intraday_parquet_path  — шлях до CRACEN/premarket_rows.parquet
    oc_parquet_path        — шлях до CRACEN/oc.parquet
    out_path               — шлях для результату (у тій же папці)
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()

    # 1) Денний OC (у пам'яті)
    df_oc = pd.read_parquet(oc_parquet_path)
    req_oc = {"ticker", "date", "open", "close"}
    missing = req_oc - set(df_oc.columns)
    if missing:
        raise KeyError(f"OC-файл не містить колонок: {sorted(missing)}")

    # 2) Підготовка вихідного файла
    if os.path.exists(out_path):
        os.remove(out_path)
    _, ext = os.path.splitext(out_path.lower())
    if ext not in [".csv", ".gz", ".parquet", ".csv.gz"]:
        raise ValueError("Підтримані формати: .csv, .csv.gz, .parquet")

    parquet_writer = None
    total_rows = 0
    batch_idx = 0

    # 3) Потокове читання parquet
    pf = pq.ParquetFile(intraday_parquet_path)
    cols = ["ticker", "dt", "o", "h", "l", "c", "v"]

    print(f"▶️ START: merge → {out_path} | batch_rows≈{batch_rows:,}")

    for batch in pf.iter_batches(batch_size=batch_rows, columns=cols):
        batch_idx += 1
        df_batch = batch.to_pandas()

        df_enriched = enrich_with_day_open_and_prev_close(df_batch, df_oc)

        if out_path.endswith(".parquet"):
            table = pa.Table.from_pandas(df_enriched)
            if parquet_writer is None:
                parquet_writer = pq.ParquetWriter(out_path, table.schema, compression="snappy")
            parquet_writer.write_table(table)
        else:
            header = not os.path.exists(out_path)
            df_enriched.to_csv(
                out_path,
                index=False,
                mode="a",
                header=header,
                compression="infer" if out_path.endswith(".gz") else None,
            )

        total_rows += len(df_batch)
        if batch_idx % log_every_batches == 0:
            elapsed = time.time() - t0
            print(f"[batch {batch_idx:>4}] rows={total_rows:,}  elapsed={elapsed:,.1f}s")

        del df_batch, df_enriched, batch
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total_rows:,}  -> {out_path}  in {time.time()-t0:,.1f}s")


def merge_intraday_and_oc_in_folder(
    folder: str = "CRACEN",
    intraday_filename: str = "premarket_etf_rows.parquet",
    oc_filename: str = "oc_etf.parquet",
    out_filename: str = "premarket_etf_rows_enriched.parquet",
    batch_rows: int = 2_000_000,
    log_every_batches: int = 5,
) -> str:
    """
    Зручний обгортник саме під твою папку зі скріну.
    Шукає:
      - {folder}/{intraday_filename}
      - {folder}/{oc_filename}
    і пише:
      - {folder}/{out_filename}
    Повертає шлях до результату.
    """
    intraday_path = os.path.join(folder, intraday_filename)
    oc_path = os.path.join(folder, oc_filename)
    out_path = os.path.join(folder, out_filename)

    if not os.path.exists(intraday_path):
        raise FileNotFoundError(f"Не знайдено інтрадей: {intraday_path}")
    if not os.path.exists(oc_path):
        raise FileNotFoundError(f"Не знайдено OC-файл: {oc_path}")
    os.makedirs(folder, exist_ok=True)

    merge_intraday_and_oc_to_file(
        intraday_parquet_path=intraday_path,
        oc_parquet_path=oc_path,
        out_path=out_path,
        batch_rows=batch_rows,
        log_every_batches=log_every_batches,
    )
    return out_path

In [39]:
out_path = merge_intraday_and_oc_in_folder(folder=str(WORK_DIR))
print("Результат у файлі:", out_path)

▶️ START: merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet | batch_rows≈2,000,000

✅ DONE  rows=944,356  -> C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  in 1.6s
Результат у файлі: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet

In [40]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pq = None

def add_pct_vs_prev_close_parquet(
    input_path: str,
    output_path: str,
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = None,
    log_every: int = 5,
    value_col: str = "o",   # ← що порівнюємо з prev_close (дефолт: open)
    out_col: str = "Benchk%",  # назва колонки з відсотком
) -> str:
    """
    Потоково читає великий Parquet, додає колонку:
        out_col = (value_col / prev_close - 1) * 100
    і пише новий Parquet.
    """
    if pq is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow.parquet).")

    t0 = time.time()
    if os.path.exists(output_path):
        os.remove(output_path)

    pf = pq.ParquetFile(input_path)
    parquet_writer = None
    total = 0
    batches = 0

    print(f"▶️ START  file={input_path}  →  {output_path}  batch_rows≈{batch_rows:,}  using={value_col}")

    for batch in pf.iter_batches(batch_size=batch_rows):
        batches += 1
        df = batch.to_pandas()

        # перевірки на наявність колонок
        if "prev_close" not in df.columns:
            raise KeyError("У вхідному файлі немає колонки 'prev_close'.")
        if value_col not in df.columns:
            raise KeyError(f"У вхідному файлі немає колонки '{value_col}'.")

        # числові типи
        df["prev_close"] = pd.to_numeric(df["prev_close"], errors="coerce")
        df[value_col]    = pd.to_numeric(df[value_col],    errors="coerce")

        denom = df["prev_close"].replace({0: pd.NA})
        pct = (df[value_col] / denom - 1.0) * 100.0
        if round_to is not None:
            pct = pct.round(round_to)

        df[out_col] = pct

        table = pa.Table.from_pandas(df, preserve_index=False)
        if parquet_writer is None:
            parquet_writer = pq.ParquetWriter(output_path, table.schema, compression="snappy")
        parquet_writer.write_table(table)

        total += len(df)
        if batches % log_every == 0:
            print(f"[batch {batches:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if parquet_writer is not None:
        parquet_writer.close()

    print(f"✅ DONE  rows={total:,}  →  {output_path}  in {time.time()-t0:,.1f}s")
    return output_path


def add_pct_vs_prev_close_in_folder(
    folder: str = "CRACEN",
    input_filename: str = "premarket_etf_rows_enriched.parquet",
    output_filename: str = "premarket_etf_rows_enriched_with_pct.parquet",
    batch_rows: int = 2_000_000,
    round_to: Optional[int] = 2,
    log_every: int = 5,
    value_col: str = "o",                 # ← open vs prev_close
    out_col: str = "Bench%",   # назва нової колонки
) -> str:
    """Обгортка під твою папку CRACEN."""
    os.makedirs(folder, exist_ok=True)
    src = os.path.join(folder, input_filename)
    dst = os.path.join(folder, output_filename)
    if not os.path.exists(src):
        raise FileNotFoundError(f"Не знайдено вхідний файл: {src}")
    return add_pct_vs_prev_close_parquet(
        input_path=src,
        output_path=dst,
        batch_rows=batch_rows,
        round_to=round_to,
        log_every=log_every,
        value_col=value_col,
        out_col=out_col,
    )

In [41]:
out_path = add_pct_vs_prev_close_in_folder(folder=str(WORK_DIR))
print("Готово:", out_path)

▶️ START  file=C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  batch_rows≈2,000,000  using=o

✅ DONE  rows=944,356  →  C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet  in 0.4s
Готово: C:\datum-api-examples-main\OriON\CRACEN\work\premarket_etf_rows_enriched_with_pct.parquet

In [42]:
import os, gc, time
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception as e:
    pa = pq = None


def merge_bench_pct_from_etf(
    base_path: str = "CRACEN/work/premarket_rows_enriched_with_pct.parquet",
    etf_path:  str = "CRACEN/work/premarket_etf_rows_enriched_with_pct.parquet",
    out_path:  str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    *,
    batch_rows: int = 2_000_000,
    align_to_minute: bool = False,        # якщо в секундах відрізняється — підрівняти до хвилини
    round_decimals: Optional[int] = 2,    # округлити Bench% до 2 знаків
    insert_before: Optional[str] = None,  # наприклад, "pct_vs_prev_close"; інакше в кінець
    compression: str = "snappy",
    log_every_batches: int = 5,
) -> str:
    """
    Мерджить Bench% із ETF-файла у базовий файл по ключах ('bench'↔'ticker', 'dt') і пише новий Parquet.
    - У ETF-файлі колонка з відсотком може називатись 'bench%' або 'pct_vs_prev_close' — обидва варіанти підтримуються.
    - Базовий файл не змінюється, додається тільки нова колонка 'Bench%'.
    """

    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow: pip install pyarrow")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)
    if not os.path.exists(etf_path):
        raise FileNotFoundError(etf_path)

    # ---------- 1) Збираємо мапу з ETF-файла: (bench, dt) -> Bench% ----------
    def _read_etf_mapping(etf_parquet: str) -> pd.DataFrame:
        pf = pq.ParquetFile(etf_parquet)
        parts = []
        # читаємо всі колонки, щоб не ловити різні схеми у row-groups
        for batch in pf.iter_batches():
            df = batch.to_pandas()
            # обов'язкові
            for col in ("ticker", "dt"):
                if col not in df.columns:
                    raise KeyError(f"У ETF-файлі відсутня колонка '{col}'")

            # колонка відсотка: bench% або pct_vs_prev_close
            cols_l = {c.lower().strip(): c for c in df.columns}
            if "bench%" in cols_l:
                val_col = cols_l["bench%"]
            elif "pct_vs_prev_close" in cols_l:
                val_col = cols_l["pct_vs_prev_close"]
            else:
                raise KeyError("У ETF-файлі не знайдено 'bench%' або 'pct_vs_prev_close'.")

            d = df[["ticker", "dt", val_col]].copy()
            d["ticker"] = d["ticker"].astype(str).str.strip().str.upper()
            d["dt"]     = pd.to_datetime(d["dt"], errors="coerce")
            if align_to_minute:
                d["dt"] = d["dt"].dt.floor("T")
            d = d.dropna(subset=["dt"])
            d = d.rename(columns={"ticker": "bench", val_col: "Bench%"})
            d["Bench%"] = pd.to_numeric(d["Bench%"], errors="coerce")
            parts.append(d)

            del df, d, batch
            gc.collect()

        if not parts:
            return pd.DataFrame(columns=["bench","dt","Bench%"])

        etf_map = pd.concat(parts, ignore_index=True)
        # прибираємо дублікати — залишаємо пізніший запис
        etf_map = (etf_map.sort_values(["bench","dt"])
                           .drop_duplicates(subset=["bench","dt"], keep="last")
                           .reset_index(drop=True))
        return etf_map

    etf_map = _read_etf_mapping(etf_path)
    if round_decimals is not None and "Bench%" in etf_map.columns:
        etf_map["Bench%"] = etf_map["Bench%"].round(round_decimals)

    # ---------- 2) Потоково проходимо базовий файл і підмерджуємо Bench% ----------
    if os.path.exists(out_path):
        os.remove(out_path)

    pf_base = pq.ParquetFile(base_path)
    writer = None
    total_rows = 0
    t0 = time.time()

    print(f"▶️ START merge → {out_path}")
    for i, batch in enumerate(pf_base.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # ключі
        for col in ("bench", "dt"):
            if col not in df.columns:
                raise KeyError(f"У базовому файлі відсутня колонка '{col}'")

        df["bench"] = df["bench"].astype(str).str.strip().str.upper()
        df["dt"]    = pd.to_datetime(df["dt"], errors="coerce")
        if align_to_minute:
            df["dt"] = df["dt"].dt.floor("T")

        merged = df.merge(etf_map, on=["bench","dt"], how="left", validate="m:1")

        # розташування 'Bench%'
        if "Bench%" in merged.columns and insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("Bench%")
            pos = cols.index(insert_before)
            cols = cols[:pos] + ["Bench%"] + cols[pos:]
            merged = merged[cols]
        # інакше — залишаємо в кінці як є

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(out_path, table.schema, compression=compression)
        writer.write_table(table)

        total_rows += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total_rows:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    print(f"✅ DONE rows={total_rows:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [43]:
merge_bench_pct_from_etf(
    base_path=str(WORK_DIR / "premarket_rows_final.parquet"),
    etf_path =str(WORK_DIR / "premarket_etf_rows_enriched_with_pct.parquet"),
    out_path =str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    batch_rows=2_000_000,
    align_to_minute=False,       # вмикай, якщо секунди/мілісекунди «пливуть»
    round_decimals=2,
    insert_before=None,          # або, наприклад, "pct_vs_prev_close"
    compression="snappy",
)

▶️ START merge → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet

[batch    5] rows=10,000,000  elapsed=11.1s

[batch   10] rows=20,000,000  elapsed=22.2s

[batch   15] rows=30,000,000  elapsed=33.2s

[batch   20] rows=40,000,000  elapsed=43.9s

[batch   25] rows=50,000,000  elapsed=54.8s

[batch   30] rows=60,000,000  elapsed=65.8s

[batch   35] rows=70,000,000  elapsed=76.7s

[batch   40] rows=80,000,000  elapsed=87.5s

[batch   45] rows=90,000,000  elapsed=98.2s

[batch   50] rows=100,000,000  elapsed=109.1s

[batch   55] rows=110,000,000  elapsed=119.9s

✅ DONE rows=111,034,041 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct.parquet  in 121.3s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct.parquet'

In [44]:
import pandas as pd
from tqdm import tqdm   # прогрес-бар

def get_gaps_for_tickers(tickers_df, start_date, end_date):
    """
    Отримує гепи для всіх тикерів із DataFrame tickers_df (колонка 'ticker').
    Використовує ендпоінт /daily/gaps і об’єднує всі результати у один DataFrame.
    """
    all_results = []

    tickers = tickers_df["ticker"].dropna().astype(str).unique().tolist()

    for t in tqdm(tickers, desc="Processing tickers"):
        params = {
            "ticker": t,
            "start_date": start_date,
            "end_date": end_date,
            "format": "json_records"
        }

        try:
            df_gap = DatumApi.data_request("/daily/gaps", params)
            if df_gap is not None and not df_gap.empty:
                all_results.append(df_gap)
        except Exception as e:
            print(f"⚠️ Проблема з {t}: {e}")

    if all_results:
        return pd.concat(all_results, ignore_index=True)
    else:
        return pd.DataFrame()

# === приклад використання ===
df_gaps_all = get_gaps_for_tickers(top1500, start_date = start_date_str, end_date = end_date_str)

print(df_gaps_all.head())
print("Загалом рядків:", len(df_gaps_all))

Processing tickers:   0%|          | 0/6932 [00:00<?, ?it/s]

Processing tickers:   0%|          | 1/6932 [00:00<23:55,  4.83it/s]

Processing tickers:   0%|          | 2/6932 [00:00<25:55,  4.45it/s]

Processing tickers:   0%|          | 3/6932 [00:00<25:52,  4.46it/s]

Processing tickers:   0%|          | 4/6932 [00:00<25:22,  4.55it/s]

Processing tickers:   0%|          | 5/6932 [00:01<25:11,  4.58it/s]

Processing tickers:   0%|          | 6/6932 [00:01<24:42,  4.67it/s]

Processing tickers:   0%|          | 7/6932 [00:01<25:02,  4.61it/s]

Processing tickers:   0%|          | 8/6932 [00:01<24:42,  4.67it/s]

Processing tickers:   0%|          | 9/6932 [00:01<24:29,  4.71it/s]

Processing tickers:   0%|          | 10/6932 [00:02<24:55,  4.63it/s]

Processing tickers:   0%|          | 11/6932 [00:02<25:10,  4.58it/s]

Processing tickers:   0%|          | 12/6932 [00:02<24:50,  4.64it/s]

Processing tickers:   0%|          | 13/6932 [00:02<24:49,  4.64it/s]

Processing tickers:   0%|          | 14/6932 [00:03<24:20,  4.74it/s]

Processing tickers:   0%|          | 15/6932 [00:03<25:19,  4.55it/s]

Processing tickers:   0%|          | 16/6932 [00:03<24:57,  4.62it/s]

Processing tickers:   0%|          | 17/6932 [00:03<24:49,  4.64it/s]

Processing tickers:   0%|          | 18/6932 [00:03<24:26,  4.71it/s]

Processing tickers:   0%|          | 19/6932 [00:04<24:52,  4.63it/s]

Processing tickers:   0%|          | 20/6932 [00:04<25:11,  4.57it/s]

Processing tickers:   0%|          | 21/6932 [00:04<24:47,  4.65it/s]

Processing tickers:   0%|          | 22/6932 [00:04<24:21,  4.73it/s]

Processing tickers:   0%|          | 23/6932 [00:04<24:13,  4.75it/s]

Processing tickers:   0%|          | 24/6932 [00:05<24:25,  4.71it/s]

Processing tickers:   0%|          | 25/6932 [00:05<24:00,  4.80it/s]

Processing tickers:   0%|          | 26/6932 [00:05<25:06,  4.58it/s]

Processing tickers:   0%|          | 27/6932 [00:05<24:46,  4.65it/s]

Processing tickers:   0%|          | 28/6932 [00:06<24:30,  4.70it/s]

Processing tickers:   0%|          | 29/6932 [00:06<24:52,  4.62it/s]

Processing tickers:   0%|          | 30/6932 [00:06<25:04,  4.59it/s]

Processing tickers:   0%|          | 31/6932 [00:06<24:41,  4.66it/s]

Processing tickers:   0%|          | 32/6932 [00:06<24:33,  4.68it/s]

Processing tickers:   0%|          | 33/6932 [00:07<24:22,  4.72it/s]

Processing tickers:   0%|          | 34/6932 [00:07<24:14,  4.74it/s]

Processing tickers:   1%|          | 35/6932 [00:07<24:22,  4.72it/s]

Processing tickers:   1%|          | 36/6932 [00:07<24:20,  4.72it/s]

Processing tickers:   1%|          | 37/6932 [00:07<24:25,  4.71it/s]

Processing tickers:   1%|          | 38/6932 [00:08<24:17,  4.73it/s]

Processing tickers:   1%|          | 39/6932 [00:08<24:06,  4.77it/s]

Processing tickers:   1%|          | 40/6932 [00:08<24:02,  4.78it/s]

Processing tickers:   1%|          | 41/6932 [00:08<23:59,  4.79it/s]

Processing tickers:   1%|          | 42/6932 [00:08<23:57,  4.79it/s]

Processing tickers:   1%|          | 43/6932 [00:09<23:59,  4.78it/s]

Processing tickers:   1%|          | 44/6932 [00:09<24:08,  4.75it/s]

Processing tickers:   1%|          | 45/6932 [00:09<24:23,  4.71it/s]

Processing tickers:   1%|          | 46/6932 [00:09<24:22,  4.71it/s]

Processing tickers:   1%|          | 47/6932 [00:10<24:32,  4.68it/s]

Processing tickers:   1%|          | 48/6932 [00:10<24:28,  4.69it/s]

Processing tickers:   1%|          | 49/6932 [00:10<24:25,  4.70it/s]

Processing tickers:   1%|          | 50/6932 [00:10<24:06,  4.76it/s]

Processing tickers:   1%|          | 51/6932 [00:10<24:00,  4.78it/s]

Processing tickers:   1%|          | 52/6932 [00:11<24:32,  4.67it/s]

Processing tickers:   1%|          | 53/6932 [00:11<24:19,  4.71it/s]

Processing tickers:   1%|          | 54/6932 [00:11<24:32,  4.67it/s]

Processing tickers:   1%|          | 55/6932 [00:11<24:01,  4.77it/s]

Processing tickers:   1%|          | 56/6932 [00:11<24:03,  4.76it/s]

Processing tickers:   1%|          | 57/6932 [00:12<23:56,  4.79it/s]

Processing tickers:   1%|          | 58/6932 [00:12<23:55,  4.79it/s]

Processing tickers:   1%|          | 59/6932 [00:12<24:27,  4.68it/s]

Processing tickers:   1%|          | 60/6932 [00:12<24:15,  4.72it/s]

Processing tickers:   1%|          | 61/6932 [00:13<24:41,  4.64it/s]

Processing tickers:   1%|          | 62/6932 [00:13<25:00,  4.58it/s]

Processing tickers:   1%|          | 63/6932 [00:13<24:41,  4.64it/s]

Processing tickers:   1%|          | 64/6932 [00:13<24:25,  4.69it/s]

Processing tickers:   1%|          | 65/6932 [00:13<24:16,  4.71it/s]

Processing tickers:   1%|          | 66/6932 [00:14<24:15,  4.72it/s]

Processing tickers:   1%|          | 67/6932 [00:14<23:58,  4.77it/s]

Processing tickers:   1%|          | 68/6932 [00:14<23:54,  4.79it/s]

Processing tickers:   1%|          | 69/6932 [00:14<24:19,  4.70it/s]

Processing tickers:   1%|          | 70/6932 [00:14<24:16,  4.71it/s]

Processing tickers:   1%|          | 71/6932 [00:15<23:35,  4.85it/s]

Processing tickers:   1%|          | 72/6932 [00:15<24:12,  4.72it/s]

Processing tickers:   1%|          | 73/6932 [00:15<24:11,  4.73it/s]

Processing tickers:   1%|          | 74/6932 [00:15<24:31,  4.66it/s]

Processing tickers:   1%|          | 75/6932 [00:15<24:14,  4.71it/s]

Processing tickers:   1%|          | 76/6932 [00:16<24:05,  4.74it/s]

Processing tickers:   1%|          | 77/6932 [00:16<24:02,  4.75it/s]

Processing tickers:   1%|          | 78/6932 [00:16<24:27,  4.67it/s]

Processing tickers:   1%|          | 79/6932 [00:16<24:12,  4.72it/s]

Processing tickers:   1%|          | 80/6932 [00:17<24:40,  4.63it/s]

Processing tickers:   1%|          | 81/6932 [00:17<24:15,  4.71it/s]

Processing tickers:   1%|          | 82/6932 [00:17<24:05,  4.74it/s]

Processing tickers:   1%|          | 83/6932 [00:17<24:52,  4.59it/s]

Processing tickers:   1%|          | 84/6932 [00:17<24:44,  4.61it/s]

Processing tickers:   1%|          | 85/6932 [00:18<25:01,  4.56it/s]

Processing tickers:   1%|          | 86/6932 [00:18<25:19,  4.51it/s]

Processing tickers:   1%|▏         | 87/6932 [00:18<24:46,  4.61it/s]

Processing tickers:   1%|▏         | 88/6932 [00:18<25:04,  4.55it/s]

Processing tickers:   1%|▏         | 89/6932 [00:19<24:31,  4.65it/s]

Processing tickers:   1%|▏         | 90/6932 [00:19<24:55,  4.58it/s]

Processing tickers:   1%|▏         | 91/6932 [00:19<25:01,  4.56it/s]

Processing tickers:   1%|▏         | 92/6932 [00:19<24:34,  4.64it/s]

Processing tickers:   1%|▏         | 93/6932 [00:19<24:18,  4.69it/s]

Processing tickers:   1%|▏         | 94/6932 [00:20<24:40,  4.62it/s]

Processing tickers:   1%|▏         | 95/6932 [00:20<24:24,  4.67it/s]

Processing tickers:   1%|▏         | 96/6932 [00:20<25:07,  4.54it/s]

Processing tickers:   1%|▏         | 97/6932 [00:20<24:51,  4.58it/s]

Processing tickers:   1%|▏         | 98/6932 [00:20<24:28,  4.65it/s]

Processing tickers:   1%|▏         | 99/6932 [00:21<24:32,  4.64it/s]

Processing tickers:   1%|▏         | 100/6932 [00:21<24:32,  4.64it/s]

Processing tickers:   1%|▏         | 101/6932 [00:21<24:22,  4.67it/s]

Processing tickers:   1%|▏         | 102/6932 [00:21<25:35,  4.45it/s]

Processing tickers:   1%|▏         | 103/6932 [00:22<25:27,  4.47it/s]

Processing tickers:   2%|▏         | 104/6932 [00:22<24:55,  4.57it/s]

Processing tickers:   2%|▏         | 105/6932 [00:22<25:14,  4.51it/s]

Processing tickers:   2%|▏         | 106/6932 [00:22<24:55,  4.57it/s]

Processing tickers:   2%|▏         | 107/6932 [00:22<24:14,  4.69it/s]

Processing tickers:   2%|▏         | 108/6932 [00:23<24:44,  4.60it/s]

Processing tickers:   2%|▏         | 109/6932 [00:23<24:50,  4.58it/s]

Processing tickers:   2%|▏         | 110/6932 [00:23<24:27,  4.65it/s]

Processing tickers:   2%|▏         | 111/6932 [00:23<24:27,  4.65it/s]

Processing tickers:   2%|▏         | 112/6932 [00:24<24:31,  4.63it/s]

Processing tickers:   2%|▏         | 113/6932 [00:24<24:48,  4.58it/s]

Processing tickers:   2%|▏         | 114/6932 [00:24<24:34,  4.62it/s]

Processing tickers:   2%|▏         | 115/6932 [00:24<24:40,  4.61it/s]

Processing tickers:   2%|▏         | 116/6932 [00:24<24:58,  4.55it/s]

Processing tickers:   2%|▏         | 117/6932 [00:25<25:39,  4.43it/s]

Processing tickers:   2%|▏         | 118/6932 [00:25<25:32,  4.45it/s]

Processing tickers:   2%|▏         | 119/6932 [00:25<25:02,  4.53it/s]

Processing tickers:   2%|▏         | 120/6932 [00:25<25:13,  4.50it/s]

Processing tickers:   2%|▏         | 121/6932 [00:26<25:18,  4.49it/s]

Processing tickers:   2%|▏         | 122/6932 [00:26<25:14,  4.50it/s]

Processing tickers:   2%|▏         | 123/6932 [00:26<25:16,  4.49it/s]

Processing tickers:   2%|▏         | 124/6932 [00:26<24:39,  4.60it/s]

Processing tickers:   2%|▏         | 125/6932 [00:26<24:22,  4.65it/s]

Processing tickers:   2%|▏         | 126/6932 [00:27<25:14,  4.49it/s]

Processing tickers:   2%|▏         | 127/6932 [00:27<25:16,  4.49it/s]

Processing tickers:   2%|▏         | 128/6932 [00:27<25:19,  4.48it/s]

Processing tickers:   2%|▏         | 129/6932 [00:27<25:20,  4.48it/s]

Processing tickers:   2%|▏         | 130/6932 [00:28<25:21,  4.47it/s]

Processing tickers:   2%|▏         | 131/6932 [00:28<26:28,  4.28it/s]

Processing tickers:   2%|▏         | 132/6932 [00:28<26:07,  4.34it/s]

Processing tickers:   2%|▏         | 133/6932 [00:28<25:21,  4.47it/s]

Processing tickers:   2%|▏         | 134/6932 [00:28<24:48,  4.57it/s]

Processing tickers:   2%|▏         | 135/6932 [00:29<24:58,  4.54it/s]

Processing tickers:   2%|▏         | 136/6932 [00:29<24:32,  4.62it/s]

Processing tickers:   2%|▏         | 137/6932 [00:29<24:49,  4.56it/s]

Processing tickers:   2%|▏         | 138/6932 [00:29<24:56,  4.54it/s]

Processing tickers:   2%|▏         | 139/6932 [00:29<24:39,  4.59it/s]

Processing tickers:   2%|▏         | 140/6932 [00:30<25:11,  4.49it/s]

Processing tickers:   2%|▏         | 141/6932 [00:30<25:14,  4.48it/s]

Processing tickers:   2%|▏         | 142/6932 [00:30<25:15,  4.48it/s]

Processing tickers:   2%|▏         | 143/6932 [00:30<24:44,  4.57it/s]

Processing tickers:   2%|▏         | 144/6932 [00:31<23:58,  4.72it/s]

Processing tickers:   2%|▏         | 145/6932 [00:31<24:50,  4.55it/s]

Processing tickers:   2%|▏         | 146/6932 [00:31<24:59,  4.53it/s]

Processing tickers:   2%|▏         | 147/6932 [00:31<24:31,  4.61it/s]

Processing tickers:   2%|▏         | 148/6932 [00:31<24:41,  4.58it/s]

Processing tickers:   2%|▏         | 149/6932 [00:32<24:22,  4.64it/s]

Processing tickers:   2%|▏         | 150/6932 [00:32<24:36,  4.59it/s]

Processing tickers:   2%|▏         | 151/6932 [00:32<24:37,  4.59it/s]

Processing tickers:   2%|▏         | 152/6932 [00:32<24:33,  4.60it/s]

Processing tickers:   2%|▏         | 153/6932 [00:33<24:43,  4.57it/s]

Processing tickers:   2%|▏         | 154/6932 [00:33<24:54,  4.54it/s]

Processing tickers:   2%|▏         | 155/6932 [00:33<25:07,  4.50it/s]

Processing tickers:   2%|▏         | 156/6932 [00:33<25:34,  4.41it/s]

Processing tickers:   2%|▏         | 157/6932 [00:33<25:16,  4.47it/s]

Processing tickers:   2%|▏         | 158/6932 [00:34<24:57,  4.52it/s]

Processing tickers:   2%|▏         | 159/6932 [00:34<25:05,  4.50it/s]

Processing tickers:   2%|▏         | 160/6932 [00:34<25:08,  4.49it/s]

Processing tickers:   2%|▏         | 161/6932 [00:34<24:46,  4.56it/s]

Processing tickers:   2%|▏         | 162/6932 [00:35<25:53,  4.36it/s]

Processing tickers:   2%|▏         | 163/6932 [00:35<24:39,  4.58it/s]

Processing tickers:   2%|▏         | 164/6932 [00:35<24:50,  4.54it/s]

Processing tickers:   2%|▏         | 165/6932 [00:35<24:57,  4.52it/s]

Processing tickers:   2%|▏         | 166/6932 [00:35<25:35,  4.41it/s]

Processing tickers:   2%|▏         | 167/6932 [00:36<25:35,  4.41it/s]

Processing tickers:   2%|▏         | 168/6932 [00:36<24:57,  4.52it/s]

Processing tickers:   2%|▏         | 169/6932 [00:36<25:01,  4.50it/s]

Processing tickers:   2%|▏         | 170/6932 [00:36<24:28,  4.60it/s]

Processing tickers:   2%|▏         | 171/6932 [00:37<24:15,  4.65it/s]

Processing tickers:   2%|▏         | 172/6932 [00:37<23:57,  4.70it/s]

Processing tickers:   2%|▏         | 173/6932 [00:37<24:20,  4.63it/s]

Processing tickers:   3%|▎         | 174/6932 [00:37<24:04,  4.68it/s]

Processing tickers:   3%|▎         | 175/6932 [00:37<24:32,  4.59it/s]

Processing tickers:   3%|▎         | 176/6932 [00:38<24:39,  4.57it/s]

Processing tickers:   3%|▎         | 177/6932 [00:38<24:54,  4.52it/s]

Processing tickers:   3%|▎         | 178/6932 [00:38<25:20,  4.44it/s]

Processing tickers:   3%|▎         | 179/6932 [00:38<24:20,  4.62it/s]

Processing tickers:   3%|▎         | 180/6932 [00:39<24:35,  4.58it/s]

Processing tickers:   3%|▎         | 181/6932 [00:39<25:21,  4.44it/s]

Processing tickers:   3%|▎         | 182/6932 [00:39<25:21,  4.44it/s]

Processing tickers:   3%|▎         | 183/6932 [00:39<24:40,  4.56it/s]

Processing tickers:   3%|▎         | 184/6932 [00:39<25:06,  4.48it/s]

Processing tickers:   3%|▎         | 185/6932 [00:40<24:50,  4.53it/s]

Processing tickers:   3%|▎         | 186/6932 [00:40<24:27,  4.60it/s]

Processing tickers:   3%|▎         | 187/6932 [00:40<24:37,  4.57it/s]

Processing tickers:   3%|▎         | 188/6932 [00:40<24:15,  4.63it/s]

Processing tickers:   3%|▎         | 189/6932 [00:41<24:31,  4.58it/s]

Processing tickers:   3%|▎         | 190/6932 [00:41<24:43,  4.55it/s]

Processing tickers:   3%|▎         | 191/6932 [00:41<24:51,  4.52it/s]

Processing tickers:   3%|▎         | 192/6932 [00:41<24:43,  4.54it/s]

Processing tickers:   3%|▎         | 193/6932 [00:41<24:46,  4.53it/s]

Processing tickers:   3%|▎         | 194/6932 [00:42<24:44,  4.54it/s]

Processing tickers:   3%|▎         | 195/6932 [00:42<24:49,  4.52it/s]

Processing tickers:   3%|▎         | 196/6932 [00:42<25:02,  4.48it/s]

Processing tickers:   3%|▎         | 197/6932 [00:42<26:37,  4.22it/s]

Processing tickers:   3%|▎         | 198/6932 [00:43<26:04,  4.31it/s]

Processing tickers:   3%|▎         | 199/6932 [00:43<26:16,  4.27it/s]

Processing tickers:   3%|▎         | 200/6932 [00:43<25:54,  4.33it/s]

Processing tickers:   3%|▎         | 201/6932 [00:43<25:40,  4.37it/s]

Processing tickers:   3%|▎         | 202/6932 [00:43<25:04,  4.47it/s]

Processing tickers:   3%|▎         | 203/6932 [00:44<25:12,  4.45it/s]

Processing tickers:   3%|▎         | 204/6932 [00:44<25:39,  4.37it/s]

Processing tickers:   3%|▎         | 205/6932 [00:44<24:48,  4.52it/s]

Processing tickers:   3%|▎         | 206/6932 [00:44<24:21,  4.60it/s]

Processing tickers:   3%|▎         | 207/6932 [00:45<24:42,  4.54it/s]

Processing tickers:   3%|▎         | 208/6932 [00:45<24:43,  4.53it/s]

Processing tickers:   3%|▎         | 209/6932 [00:45<24:15,  4.62it/s]

Processing tickers:   3%|▎         | 210/6932 [00:45<24:30,  4.57it/s]

Processing tickers:   3%|▎         | 211/6932 [00:45<24:49,  4.51it/s]

Processing tickers:   3%|▎         | 212/6932 [00:46<24:56,  4.49it/s]

Processing tickers:   3%|▎         | 213/6932 [00:46<24:50,  4.51it/s]

Processing tickers:   3%|▎         | 214/6932 [00:46<24:54,  4.50it/s]

Processing tickers:   3%|▎         | 215/6932 [00:46<24:33,  4.56it/s]

Processing tickers:   3%|▎         | 216/6932 [00:47<24:36,  4.55it/s]

Processing tickers:   3%|▎         | 217/6932 [00:47<24:12,  4.62it/s]

Processing tickers:   3%|▎         | 218/6932 [00:47<24:56,  4.49it/s]

Processing tickers:   3%|▎         | 219/6932 [00:47<24:33,  4.55it/s]

Processing tickers:   3%|▎         | 220/6932 [00:47<24:34,  4.55it/s]

Processing tickers:   3%|▎         | 221/6932 [00:48<24:19,  4.60it/s]

Processing tickers:   3%|▎         | 222/6932 [00:48<23:53,  4.68it/s]

Processing tickers:   3%|▎         | 223/6932 [00:48<24:13,  4.62it/s]

Processing tickers:   3%|▎         | 224/6932 [00:48<23:54,  4.67it/s]

Processing tickers:   3%|▎         | 225/6932 [00:49<24:23,  4.58it/s]

Processing tickers:   3%|▎         | 226/6932 [00:49<24:27,  4.57it/s]

Processing tickers:   3%|▎         | 227/6932 [00:49<24:47,  4.51it/s]

Processing tickers:   3%|▎         | 228/6932 [00:49<25:08,  4.44it/s]

Processing tickers:   3%|▎         | 229/6932 [00:49<24:41,  4.52it/s]

Processing tickers:   3%|▎         | 230/6932 [00:50<24:56,  4.48it/s]

Processing tickers:   3%|▎         | 231/6932 [00:50<25:21,  4.40it/s]

Processing tickers:   3%|▎         | 232/6932 [00:50<25:03,  4.46it/s]

Processing tickers:   3%|▎         | 233/6932 [00:50<26:50,  4.16it/s]

Processing tickers:   3%|▎         | 234/6932 [00:51<25:45,  4.33it/s]

Processing tickers:   3%|▎         | 235/6932 [00:51<25:30,  4.37it/s]

Processing tickers:   3%|▎         | 236/6932 [00:51<24:48,  4.50it/s]

Processing tickers:   3%|▎         | 237/6932 [00:51<25:50,  4.32it/s]

Processing tickers:   3%|▎         | 238/6932 [00:51<25:02,  4.46it/s]

Processing tickers:   3%|▎         | 239/6932 [00:52<24:59,  4.46it/s]

Processing tickers:   3%|▎         | 240/6932 [00:52<25:10,  4.43it/s]

Processing tickers:   3%|▎         | 241/6932 [00:52<24:27,  4.56it/s]

Processing tickers:   3%|▎         | 242/6932 [00:52<24:34,  4.54it/s]

Processing tickers:   4%|▎         | 243/6932 [00:53<24:16,  4.59it/s]

Processing tickers:   4%|▎         | 244/6932 [00:53<24:27,  4.56it/s]

Processing tickers:   4%|▎         | 245/6932 [00:53<23:59,  4.64it/s]

Processing tickers:   4%|▎         | 246/6932 [00:53<24:17,  4.59it/s]

Processing tickers:   4%|▎         | 247/6932 [00:53<23:56,  4.65it/s]

Processing tickers:   4%|▎         | 248/6932 [00:54<23:42,  4.70it/s]

Processing tickers:   4%|▎         | 249/6932 [00:54<24:03,  4.63it/s]

Processing tickers:   4%|▎         | 250/6932 [00:54<23:50,  4.67it/s]

Processing tickers:   4%|▎         | 251/6932 [00:54<23:53,  4.66it/s]

Processing tickers:   4%|▎         | 252/6932 [00:54<24:23,  4.56it/s]

Processing tickers:   4%|▎         | 253/6932 [00:55<24:35,  4.53it/s]

Processing tickers:   4%|▎         | 254/6932 [00:55<24:08,  4.61it/s]

Processing tickers:   4%|▎         | 255/6932 [00:55<24:19,  4.57it/s]

Processing tickers:   4%|▎         | 256/6932 [00:55<24:06,  4.62it/s]

Processing tickers:   4%|▎         | 257/6932 [00:56<23:49,  4.67it/s]

Processing tickers:   4%|▎         | 258/6932 [00:56<24:07,  4.61it/s]

Processing tickers:   4%|▎         | 259/6932 [00:56<24:49,  4.48it/s]

Processing tickers:   4%|▍         | 260/6932 [00:56<25:03,  4.44it/s]

Processing tickers:   4%|▍         | 261/6932 [00:56<25:28,  4.36it/s]

Processing tickers:   4%|▍         | 262/6932 [00:57<26:09,  4.25it/s]

Processing tickers:   4%|▍         | 263/6932 [00:57<25:10,  4.41it/s]

Processing tickers:   4%|▍         | 264/6932 [00:57<25:22,  4.38it/s]

Processing tickers:   4%|▍         | 265/6932 [00:57<25:08,  4.42it/s]

Processing tickers:   4%|▍         | 266/6932 [00:58<24:21,  4.56it/s]

Processing tickers:   4%|▍         | 267/6932 [00:58<23:58,  4.63it/s]

Processing tickers:   4%|▍         | 268/6932 [00:58<24:13,  4.58it/s]

Processing tickers:   4%|▍         | 269/6932 [00:58<23:59,  4.63it/s]

Processing tickers:   4%|▍         | 270/6932 [00:58<24:11,  4.59it/s]

Processing tickers:   4%|▍         | 271/6932 [00:59<23:47,  4.67it/s]

Processing tickers:   4%|▍         | 272/6932 [00:59<23:35,  4.70it/s]

Processing tickers:   4%|▍         | 273/6932 [00:59<23:25,  4.74it/s]

Processing tickers:   4%|▍         | 274/6932 [00:59<23:18,  4.76it/s]

Processing tickers:   4%|▍         | 275/6932 [01:00<23:47,  4.66it/s]

Processing tickers:   4%|▍         | 276/6932 [01:00<24:06,  4.60it/s]

Processing tickers:   4%|▍         | 277/6932 [01:00<24:17,  4.57it/s]

Processing tickers:   4%|▍         | 278/6932 [01:00<23:53,  4.64it/s]

Processing tickers:   4%|▍         | 279/6932 [01:00<24:19,  4.56it/s]

Processing tickers:   4%|▍         | 280/6932 [01:01<24:20,  4.55it/s]

Processing tickers:   4%|▍         | 281/6932 [01:01<23:56,  4.63it/s]

Processing tickers:   4%|▍         | 282/6932 [01:01<23:41,  4.68it/s]

Processing tickers:   4%|▍         | 283/6932 [01:01<23:58,  4.62it/s]

Processing tickers:   4%|▍         | 284/6932 [01:01<23:41,  4.68it/s]

Processing tickers:   4%|▍         | 285/6932 [01:02<23:58,  4.62it/s]

Processing tickers:   4%|▍         | 286/6932 [01:02<24:14,  4.57it/s]

Processing tickers:   4%|▍         | 287/6932 [01:02<23:52,  4.64it/s]

Processing tickers:   4%|▍         | 288/6932 [01:02<23:37,  4.69it/s]

Processing tickers:   4%|▍         | 289/6932 [01:03<23:59,  4.61it/s]

Processing tickers:   4%|▍         | 290/6932 [01:03<23:41,  4.67it/s]

Processing tickers:   4%|▍         | 291/6932 [01:03<35:26,  3.12it/s]

Processing tickers:   4%|▍         | 292/6932 [01:04<32:02,  3.45it/s]

Processing tickers:   4%|▍         | 293/6932 [01:04<29:51,  3.71it/s]

Processing tickers:   4%|▍         | 294/6932 [01:04<28:22,  3.90it/s]

Processing tickers:   4%|▍         | 295/6932 [01:04<27:16,  4.06it/s]

Processing tickers:   4%|▍         | 296/6932 [01:04<26:12,  4.22it/s]

Processing tickers:   4%|▍         | 297/6932 [01:05<26:02,  4.25it/s]

Processing tickers:   4%|▍         | 298/6932 [01:05<25:04,  4.41it/s]

Processing tickers:   4%|▍         | 299/6932 [01:05<25:09,  4.40it/s]

Processing tickers:   4%|▍         | 300/6932 [01:05<24:41,  4.48it/s]

Processing tickers:   4%|▍         | 301/6932 [01:06<24:23,  4.53it/s]

Processing tickers:   4%|▍         | 302/6932 [01:06<24:15,  4.55it/s]

Processing tickers:   4%|▍         | 303/6932 [01:06<23:59,  4.60it/s]

Processing tickers:   4%|▍         | 304/6932 [01:06<23:45,  4.65it/s]

Processing tickers:   4%|▍         | 305/6932 [01:06<23:41,  4.66it/s]

Processing tickers:   4%|▍         | 306/6932 [01:07<23:56,  4.61it/s]

Processing tickers:   4%|▍         | 307/6932 [01:07<23:45,  4.65it/s]

Processing tickers:   4%|▍         | 308/6932 [01:07<23:49,  4.63it/s]

Processing tickers:   4%|▍         | 309/6932 [01:07<23:41,  4.66it/s]

Processing tickers:   4%|▍         | 310/6932 [01:07<23:46,  4.64it/s]

Processing tickers:   4%|▍         | 311/6932 [01:08<23:18,  4.73it/s]

Processing tickers:   5%|▍         | 312/6932 [01:08<23:06,  4.78it/s]

Processing tickers:   5%|▍         | 313/6932 [01:08<23:34,  4.68it/s]

Processing tickers:   5%|▍         | 314/6932 [01:08<23:24,  4.71it/s]

Processing tickers:   5%|▍         | 315/6932 [01:09<23:47,  4.64it/s]

Processing tickers:   5%|▍         | 316/6932 [01:09<23:39,  4.66it/s]

Processing tickers:   5%|▍         | 317/6932 [01:09<23:17,  4.73it/s]

Processing tickers:   5%|▍         | 318/6932 [01:09<23:51,  4.62it/s]

Processing tickers:   5%|▍         | 319/6932 [01:09<23:23,  4.71it/s]

Processing tickers:   5%|▍         | 320/6932 [01:10<23:45,  4.64it/s]

Processing tickers:   5%|▍         | 321/6932 [01:10<24:02,  4.58it/s]

Processing tickers:   5%|▍         | 322/6932 [01:10<23:55,  4.60it/s]

Processing tickers:   5%|▍         | 323/6932 [01:10<23:53,  4.61it/s]

Processing tickers:   5%|▍         | 324/6932 [01:10<24:07,  4.57it/s]

Processing tickers:   5%|▍         | 325/6932 [01:11<23:47,  4.63it/s]

Processing tickers:   5%|▍         | 326/6932 [01:11<23:49,  4.62it/s]

Processing tickers:   5%|▍         | 327/6932 [01:11<23:45,  4.63it/s]

Processing tickers:   5%|▍         | 328/6932 [01:11<23:30,  4.68it/s]

Processing tickers:   5%|▍         | 329/6932 [01:12<23:19,  4.72it/s]

Processing tickers:   5%|▍         | 330/6932 [01:12<23:11,  4.74it/s]

Processing tickers:   5%|▍         | 331/6932 [01:12<24:08,  4.56it/s]

Processing tickers:   5%|▍         | 332/6932 [01:12<24:15,  4.53it/s]

Processing tickers:   5%|▍         | 333/6932 [01:12<24:06,  4.56it/s]

Processing tickers:   5%|▍         | 334/6932 [01:13<24:08,  4.56it/s]

Processing tickers:   5%|▍         | 335/6932 [01:13<24:10,  4.55it/s]

Processing tickers:   5%|▍         | 336/6932 [01:13<24:17,  4.52it/s]

Processing tickers:   5%|▍         | 337/6932 [01:13<23:50,  4.61it/s]

Processing tickers:   5%|▍         | 338/6932 [01:14<24:04,  4.57it/s]

Processing tickers:   5%|▍         | 339/6932 [01:14<23:43,  4.63it/s]

Processing tickers:   5%|▍         | 340/6932 [01:14<24:02,  4.57it/s]

Processing tickers:   5%|▍         | 341/6932 [01:14<23:56,  4.59it/s]

Processing tickers:   5%|▍         | 342/6932 [01:14<23:53,  4.60it/s]

Processing tickers:   5%|▍         | 343/6932 [01:15<23:30,  4.67it/s]

Processing tickers:   5%|▍         | 344/6932 [01:15<23:53,  4.59it/s]

Processing tickers:   5%|▍         | 345/6932 [01:15<24:03,  4.56it/s]

Processing tickers:   5%|▍         | 346/6932 [01:15<24:14,  4.53it/s]

Processing tickers:   5%|▌         | 347/6932 [01:15<24:22,  4.50it/s]

Processing tickers:   5%|▌         | 348/6932 [01:16<23:51,  4.60it/s]

Processing tickers:   5%|▌         | 349/6932 [01:16<23:33,  4.66it/s]

Processing tickers:   5%|▌         | 350/6932 [01:16<23:54,  4.59it/s]

Processing tickers:   5%|▌         | 351/6932 [01:16<23:29,  4.67it/s]

Processing tickers:   5%|▌         | 352/6932 [01:17<23:15,  4.71it/s]

Processing tickers:   5%|▌         | 353/6932 [01:17<23:38,  4.64it/s]

Processing tickers:   5%|▌         | 354/6932 [01:17<23:25,  4.68it/s]

Processing tickers:   5%|▌         | 355/6932 [01:17<23:10,  4.73it/s]

Processing tickers:   5%|▌         | 356/6932 [01:17<23:40,  4.63it/s]

Processing tickers:   5%|▌         | 357/6932 [01:18<23:28,  4.67it/s]

Processing tickers:   5%|▌         | 358/6932 [01:18<24:17,  4.51it/s]

Processing tickers:   5%|▌         | 359/6932 [01:18<32:40,  3.35it/s]

Processing tickers:   5%|▌         | 360/6932 [01:19<29:42,  3.69it/s]

Processing tickers:   5%|▌         | 361/6932 [01:19<28:10,  3.89it/s]

Processing tickers:   5%|▌         | 362/6932 [01:19<26:39,  4.11it/s]

Processing tickers:   5%|▌         | 363/6932 [01:19<26:09,  4.19it/s]

Processing tickers:   5%|▌         | 364/6932 [01:19<24:53,  4.40it/s]

Processing tickers:   5%|▌         | 365/6932 [01:20<24:47,  4.42it/s]

Processing tickers:   5%|▌         | 366/6932 [01:20<24:39,  4.44it/s]

Processing tickers:   5%|▌         | 367/6932 [01:20<25:05,  4.36it/s]

Processing tickers:   5%|▌         | 368/6932 [01:20<24:56,  4.39it/s]

Processing tickers:   5%|▌         | 369/6932 [01:21<24:46,  4.41it/s]

Processing tickers:   5%|▌         | 370/6932 [01:21<24:26,  4.48it/s]

Processing tickers:   5%|▌         | 371/6932 [01:21<23:40,  4.62it/s]

Processing tickers:   5%|▌         | 372/6932 [01:21<26:31,  4.12it/s]

Processing tickers:   5%|▌         | 373/6932 [01:21<25:52,  4.22it/s]

Processing tickers:   5%|▌         | 374/6932 [01:22<24:53,  4.39it/s]

Processing tickers:   5%|▌         | 375/6932 [01:22<24:43,  4.42it/s]

Processing tickers:   5%|▌         | 376/6932 [01:22<24:02,  4.54it/s]

Processing tickers:   5%|▌         | 377/6932 [01:22<24:05,  4.53it/s]

Processing tickers:   5%|▌         | 378/6932 [01:23<23:45,  4.60it/s]

Processing tickers:   5%|▌         | 379/6932 [01:23<23:55,  4.56it/s]

Processing tickers:   5%|▌         | 380/6932 [01:23<23:33,  4.64it/s]

Processing tickers:   5%|▌         | 381/6932 [01:23<23:19,  4.68it/s]

Processing tickers:   6%|▌         | 382/6932 [01:23<23:46,  4.59it/s]

Processing tickers:   6%|▌         | 383/6932 [01:24<23:50,  4.58it/s]

Processing tickers:   6%|▌         | 384/6932 [01:24<23:30,  4.64it/s]

Processing tickers:   6%|▌         | 385/6932 [01:24<23:46,  4.59it/s]

Processing tickers:   6%|▌         | 386/6932 [01:24<23:25,  4.66it/s]

Processing tickers:   6%|▌         | 387/6932 [01:25<23:26,  4.65it/s]

Processing tickers:   6%|▌         | 388/6932 [01:25<23:09,  4.71it/s]

Processing tickers:   6%|▌         | 389/6932 [01:25<22:50,  4.77it/s]

Processing tickers:   6%|▌         | 390/6932 [01:25<23:20,  4.67it/s]

Processing tickers:   6%|▌         | 391/6932 [01:25<23:38,  4.61it/s]

Processing tickers:   6%|▌         | 392/6932 [01:26<23:19,  4.67it/s]

Processing tickers:   6%|▌         | 393/6932 [01:26<23:38,  4.61it/s]

Processing tickers:   6%|▌         | 394/6932 [01:26<23:21,  4.67it/s]

Processing tickers:   6%|▌         | 395/6932 [01:26<23:08,  4.71it/s]

Processing tickers:   6%|▌         | 396/6932 [01:26<23:25,  4.65it/s]

Processing tickers:   6%|▌         | 397/6932 [01:27<24:10,  4.51it/s]

Processing tickers:   6%|▌         | 398/6932 [01:27<24:42,  4.41it/s]

Processing tickers:   6%|▌         | 399/6932 [01:27<24:31,  4.44it/s]

Processing tickers:   6%|▌         | 400/6932 [01:27<24:25,  4.46it/s]

Processing tickers:   6%|▌         | 401/6932 [01:28<23:50,  4.57it/s]

Processing tickers:   6%|▌         | 402/6932 [01:28<23:26,  4.64it/s]

Processing tickers:   6%|▌         | 403/6932 [01:28<23:11,  4.69it/s]

Processing tickers:   6%|▌         | 404/6932 [01:28<23:03,  4.72it/s]

Processing tickers:   6%|▌         | 405/6932 [01:28<23:16,  4.67it/s]

Processing tickers:   6%|▌         | 406/6932 [01:29<23:13,  4.68it/s]

Processing tickers:   6%|▌         | 407/6932 [01:29<23:01,  4.72it/s]

Processing tickers:   6%|▌         | 408/6932 [01:29<22:53,  4.75it/s]

Processing tickers:   6%|▌         | 409/6932 [01:29<22:50,  4.76it/s]

Processing tickers:   6%|▌         | 410/6932 [01:29<22:45,  4.78it/s]

Processing tickers:   6%|▌         | 411/6932 [01:30<22:42,  4.78it/s]

Processing tickers:   6%|▌         | 412/6932 [01:30<23:11,  4.69it/s]

Processing tickers:   6%|▌         | 413/6932 [01:30<23:16,  4.67it/s]

Processing tickers:   6%|▌         | 414/6932 [01:30<23:17,  4.67it/s]

Processing tickers:   6%|▌         | 415/6932 [01:31<23:41,  4.58it/s]

Processing tickers:   6%|▌         | 416/6932 [01:31<23:54,  4.54it/s]

Processing tickers:   6%|▌         | 417/6932 [01:31<24:19,  4.46it/s]

Processing tickers:   6%|▌         | 418/6932 [01:31<24:01,  4.52it/s]

Processing tickers:   6%|▌         | 419/6932 [01:31<23:45,  4.57it/s]

Processing tickers:   6%|▌         | 420/6932 [01:32<23:01,  4.71it/s]

Processing tickers:   6%|▌         | 421/6932 [01:32<23:56,  4.53it/s]

Processing tickers:   6%|▌         | 422/6932 [01:32<24:01,  4.52it/s]

Processing tickers:   6%|▌         | 423/6932 [01:32<23:45,  4.57it/s]

Processing tickers:   6%|▌         | 424/6932 [01:33<23:46,  4.56it/s]

Processing tickers:   6%|▌         | 425/6932 [01:33<23:24,  4.63it/s]

Processing tickers:   6%|▌         | 426/6932 [01:33<23:39,  4.58it/s]

Processing tickers:   6%|▌         | 427/6932 [01:33<23:17,  4.65it/s]

Processing tickers:   6%|▌         | 428/6932 [01:33<23:02,  4.70it/s]

Processing tickers:   6%|▌         | 429/6932 [01:34<23:12,  4.67it/s]

Processing tickers:   6%|▌         | 430/6932 [01:34<23:14,  4.66it/s]

Processing tickers:   6%|▌         | 431/6932 [01:34<23:32,  4.60it/s]

Processing tickers:   6%|▌         | 432/6932 [01:34<23:15,  4.66it/s]

Processing tickers:   6%|▌         | 433/6932 [01:34<23:40,  4.57it/s]

Processing tickers:   6%|▋         | 434/6932 [01:35<23:44,  4.56it/s]

Processing tickers:   6%|▋         | 435/6932 [01:35<23:25,  4.62it/s]

Processing tickers:   6%|▋         | 436/6932 [01:35<23:04,  4.69it/s]

Processing tickers:   6%|▋         | 437/6932 [01:35<23:29,  4.61it/s]

Processing tickers:   6%|▋         | 438/6932 [01:36<23:06,  4.68it/s]

Processing tickers:   6%|▋         | 439/6932 [01:36<23:25,  4.62it/s]

Processing tickers:   6%|▋         | 440/6932 [01:36<23:08,  4.67it/s]

Processing tickers:   6%|▋         | 441/6932 [01:36<23:35,  4.58it/s]

Processing tickers:   6%|▋         | 442/6932 [01:36<23:15,  4.65it/s]

Processing tickers:   6%|▋         | 443/6932 [01:37<23:27,  4.61it/s]

Processing tickers:   6%|▋         | 444/6932 [01:37<23:07,  4.68it/s]

Processing tickers:   6%|▋         | 445/6932 [01:37<23:31,  4.60it/s]

Processing tickers:   6%|▋         | 446/6932 [01:37<23:08,  4.67it/s]

Processing tickers:   6%|▋         | 447/6932 [01:37<23:25,  4.61it/s]

Processing tickers:   6%|▋         | 448/6932 [01:38<23:28,  4.60it/s]

Processing tickers:   6%|▋         | 449/6932 [01:38<23:24,  4.62it/s]

Processing tickers:   6%|▋         | 450/6932 [01:38<23:31,  4.59it/s]

Processing tickers:   7%|▋         | 451/6932 [01:38<23:21,  4.63it/s]

Processing tickers:   7%|▋         | 452/6932 [01:39<23:11,  4.66it/s]

Processing tickers:   7%|▋         | 453/6932 [01:39<23:37,  4.57it/s]

Processing tickers:   7%|▋         | 454/6932 [01:39<23:28,  4.60it/s]

Processing tickers:   7%|▋         | 455/6932 [01:40<56:18,  1.92it/s]

Processing tickers:   7%|▋         | 456/6932 [01:40<46:08,  2.34it/s]

Processing tickers:   7%|▋         | 457/6932 [01:41<39:21,  2.74it/s]

Processing tickers:   7%|▋         | 458/6932 [01:41<34:44,  3.11it/s]

Processing tickers:   7%|▋         | 459/6932 [01:41<31:23,  3.44it/s]

Processing tickers:   7%|▋         | 460/6932 [01:41<29:05,  3.71it/s]

Processing tickers:   7%|▋         | 461/6932 [01:42<27:42,  3.89it/s]

Processing tickers:   7%|▋         | 462/6932 [01:42<26:33,  4.06it/s]

Processing tickers:   7%|▋         | 463/6932 [01:42<25:48,  4.18it/s]

Processing tickers:   7%|▋         | 464/6932 [01:42<25:15,  4.27it/s]

Processing tickers:   7%|▋         | 465/6932 [01:42<24:24,  4.42it/s]

Processing tickers:   7%|▋         | 466/6932 [01:43<23:47,  4.53it/s]

Processing tickers:   7%|▋         | 467/6932 [01:43<24:22,  4.42it/s]

Processing tickers:   7%|▋         | 468/6932 [01:43<23:46,  4.53it/s]

Processing tickers:   7%|▋         | 469/6932 [01:43<23:53,  4.51it/s]

Processing tickers:   7%|▋         | 470/6932 [01:43<23:26,  4.59it/s]

Processing tickers:   7%|▋         | 471/6932 [01:44<26:32,  4.06it/s]

Processing tickers:   7%|▋         | 472/6932 [01:44<26:01,  4.14it/s]

Processing tickers:   7%|▋         | 473/6932 [01:44<25:08,  4.28it/s]

Processing tickers:   7%|▋         | 474/6932 [01:44<24:35,  4.38it/s]

Processing tickers:   7%|▋         | 475/6932 [01:45<23:59,  4.49it/s]

Processing tickers:   7%|▋         | 476/6932 [01:45<23:26,  4.59it/s]

Processing tickers:   7%|▋         | 477/6932 [01:45<23:45,  4.53it/s]

Processing tickers:   7%|▋         | 478/6932 [01:45<23:56,  4.49it/s]

Processing tickers:   7%|▋         | 479/6932 [01:46<23:16,  4.62it/s]

Processing tickers:   7%|▋         | 480/6932 [01:46<23:31,  4.57it/s]

Processing tickers:   7%|▋         | 481/6932 [01:46<23:41,  4.54it/s]

Processing tickers:   7%|▋         | 482/6932 [01:46<23:16,  4.62it/s]

Processing tickers:   7%|▋         | 483/6932 [01:47<55:59,  1.92it/s]

Processing tickers:   7%|▋         | 484/6932 [01:48<45:52,  2.34it/s]

Processing tickers:   7%|▋         | 485/6932 [01:48<39:21,  2.73it/s]

Processing tickers:   7%|▋         | 486/6932 [01:48<34:27,  3.12it/s]

Processing tickers:   7%|▋         | 487/6932 [01:48<30:36,  3.51it/s]

Processing tickers:   7%|▋         | 488/6932 [01:49<28:46,  3.73it/s]

Processing tickers:   7%|▋         | 489/6932 [01:49<27:15,  3.94it/s]

Processing tickers:   7%|▋         | 490/6932 [01:49<25:46,  4.16it/s]

Processing tickers:   7%|▋         | 491/6932 [01:49<25:42,  4.18it/s]

Processing tickers:   7%|▋         | 492/6932 [01:49<25:10,  4.26it/s]

Processing tickers:   7%|▋         | 493/6932 [01:50<24:24,  4.40it/s]

Processing tickers:   7%|▋         | 494/6932 [01:50<24:22,  4.40it/s]

Processing tickers:   7%|▋         | 495/6932 [01:50<24:17,  4.42it/s]

Processing tickers:   7%|▋         | 496/6932 [01:50<24:12,  4.43it/s]

Processing tickers:   7%|▋         | 497/6932 [01:50<23:36,  4.54it/s]

Processing tickers:   7%|▋         | 498/6932 [01:51<23:45,  4.51it/s]

Processing tickers:   7%|▋         | 499/6932 [01:51<24:05,  4.45it/s]

Processing tickers:   7%|▋         | 500/6932 [01:51<23:49,  4.50it/s]

Processing tickers:   7%|▋         | 501/6932 [01:52<56:09,  1.91it/s]

Processing tickers:   7%|▋         | 502/6932 [01:53<45:53,  2.34it/s]

Processing tickers:   7%|▋         | 503/6932 [01:53<38:49,  2.76it/s]

Processing tickers:   7%|▋         | 504/6932 [01:53<34:28,  3.11it/s]

Processing tickers:   7%|▋         | 505/6932 [01:53<31:01,  3.45it/s]

Processing tickers:   7%|▋         | 506/6932 [01:53<28:53,  3.71it/s]

Processing tickers:   7%|▋         | 507/6932 [01:54<27:06,  3.95it/s]

Processing tickers:   7%|▋         | 508/6932 [01:54<26:08,  4.10it/s]

Processing tickers:   7%|▋         | 509/6932 [01:54<25:23,  4.22it/s]

Processing tickers:   7%|▋         | 510/6932 [01:54<24:31,  4.36it/s]

Processing tickers:   7%|▋         | 511/6932 [01:55<24:32,  4.36it/s]

Processing tickers:   7%|▋         | 512/6932 [01:55<23:54,  4.48it/s]

Processing tickers:   7%|▋         | 513/6932 [01:55<23:11,  4.61it/s]

Processing tickers:   7%|▋         | 514/6932 [01:55<23:26,  4.56it/s]

Processing tickers:   7%|▋         | 515/6932 [01:55<23:35,  4.53it/s]

Processing tickers:   7%|▋         | 516/6932 [01:56<24:05,  4.44it/s]

Processing tickers:   7%|▋         | 517/6932 [01:56<23:09,  4.62it/s]

Processing tickers:   7%|▋         | 518/6932 [01:56<23:31,  4.55it/s]

Processing tickers:   7%|▋         | 519/6932 [01:56<22:59,  4.65it/s]

Processing tickers:   8%|▊         | 520/6932 [01:57<23:15,  4.59it/s]

Processing tickers:   8%|▊         | 521/6932 [01:57<23:27,  4.55it/s]

Processing tickers:   8%|▊         | 522/6932 [01:57<23:35,  4.53it/s]

Processing tickers:   8%|▊         | 523/6932 [01:57<23:41,  4.51it/s]

Processing tickers:   8%|▊         | 524/6932 [01:57<23:13,  4.60it/s]

Processing tickers:   8%|▊         | 525/6932 [01:58<23:19,  4.58it/s]

Processing tickers:   8%|▊         | 526/6932 [01:58<23:12,  4.60it/s]

Processing tickers:   8%|▊         | 527/6932 [01:58<22:47,  4.68it/s]

Processing tickers:   8%|▊         | 528/6932 [01:58<22:59,  4.64it/s]

Processing tickers:   8%|▊         | 529/6932 [01:58<23:21,  4.57it/s]

Processing tickers:   8%|▊         | 530/6932 [01:59<23:32,  4.53it/s]

Processing tickers:   8%|▊         | 531/6932 [01:59<23:27,  4.55it/s]

Processing tickers:   8%|▊         | 532/6932 [01:59<23:18,  4.58it/s]

Processing tickers:   8%|▊         | 533/6932 [01:59<23:27,  4.55it/s]

Processing tickers:   8%|▊         | 534/6932 [02:00<24:25,  4.37it/s]

Processing tickers:   8%|▊         | 535/6932 [02:00<24:08,  4.42it/s]

Processing tickers:   8%|▊         | 536/6932 [02:00<23:18,  4.57it/s]

Processing tickers:   8%|▊         | 537/6932 [02:00<24:00,  4.44it/s]

Processing tickers:   8%|▊         | 538/6932 [02:00<23:27,  4.54it/s]

Processing tickers:   8%|▊         | 539/6932 [02:01<24:15,  4.39it/s]

Processing tickers:   8%|▊         | 540/6932 [02:01<23:29,  4.54it/s]

Processing tickers:   8%|▊         | 541/6932 [02:01<23:05,  4.61it/s]

Processing tickers:   8%|▊         | 542/6932 [02:01<22:46,  4.68it/s]

Processing tickers:   8%|▊         | 543/6932 [02:02<23:11,  4.59it/s]

Processing tickers:   8%|▊         | 544/6932 [02:02<22:42,  4.69it/s]

Processing tickers:   8%|▊         | 545/6932 [02:02<22:31,  4.73it/s]

Processing tickers:   8%|▊         | 546/6932 [02:02<22:24,  4.75it/s]

Processing tickers:   8%|▊         | 547/6932 [02:02<22:50,  4.66it/s]

Processing tickers:   8%|▊         | 548/6932 [02:03<22:35,  4.71it/s]

Processing tickers:   8%|▊         | 549/6932 [02:03<22:25,  4.75it/s]

Processing tickers:   8%|▊         | 550/6932 [02:03<22:52,  4.65it/s]

Processing tickers:   8%|▊         | 551/6932 [02:03<23:09,  4.59it/s]

Processing tickers:   8%|▊         | 552/6932 [02:04<23:12,  4.58it/s]

Processing tickers:   8%|▊         | 553/6932 [02:04<24:02,  4.42it/s]

Processing tickers:   8%|▊         | 554/6932 [02:04<23:59,  4.43it/s]

Processing tickers:   8%|▊         | 555/6932 [02:04<23:24,  4.54it/s]

Processing tickers:   8%|▊         | 556/6932 [02:04<23:31,  4.52it/s]

Processing tickers:   8%|▊         | 557/6932 [02:05<23:11,  4.58it/s]

Processing tickers:   8%|▊         | 558/6932 [02:05<22:50,  4.65it/s]

Processing tickers:   8%|▊         | 559/6932 [02:05<22:34,  4.71it/s]

Processing tickers:   8%|▊         | 560/6932 [02:05<22:56,  4.63it/s]

Processing tickers:   8%|▊         | 561/6932 [02:05<22:41,  4.68it/s]

Processing tickers:   8%|▊         | 562/6932 [02:06<22:29,  4.72it/s]

Processing tickers:   8%|▊         | 563/6932 [02:06<22:53,  4.64it/s]

Processing tickers:   8%|▊         | 564/6932 [02:06<22:35,  4.70it/s]

Processing tickers:   8%|▊         | 565/6932 [02:06<22:49,  4.65it/s]

Processing tickers:   8%|▊         | 566/6932 [02:07<22:36,  4.69it/s]

Processing tickers:   8%|▊         | 567/6932 [02:07<23:27,  4.52it/s]

Processing tickers:   8%|▊         | 568/6932 [02:07<23:02,  4.60it/s]

Processing tickers:   8%|▊         | 569/6932 [02:07<22:44,  4.66it/s]

Processing tickers:   8%|▊         | 570/6932 [02:07<22:43,  4.67it/s]

Processing tickers:   8%|▊         | 571/6932 [02:08<22:38,  4.68it/s]

Processing tickers:   8%|▊         | 572/6932 [02:08<22:34,  4.69it/s]

Processing tickers:   8%|▊         | 573/6932 [02:08<22:42,  4.67it/s]

Processing tickers:   8%|▊         | 574/6932 [02:08<22:49,  4.64it/s]

Processing tickers:   8%|▊         | 575/6932 [02:08<23:00,  4.60it/s]

Processing tickers:   8%|▊         | 576/6932 [02:09<23:12,  4.56it/s]

Processing tickers:   8%|▊         | 577/6932 [02:09<23:09,  4.57it/s]

Processing tickers:   8%|▊         | 578/6932 [02:09<22:59,  4.61it/s]

Processing tickers:   8%|▊         | 579/6932 [02:09<23:09,  4.57it/s]

Processing tickers:   8%|▊         | 580/6932 [02:10<23:21,  4.53it/s]

Processing tickers:   8%|▊         | 581/6932 [02:10<23:00,  4.60it/s]

Processing tickers:   8%|▊         | 582/6932 [02:10<23:09,  4.57it/s]

Processing tickers:   8%|▊         | 583/6932 [02:10<23:09,  4.57it/s]

Processing tickers:   8%|▊         | 584/6932 [02:10<22:29,  4.70it/s]

Processing tickers:   8%|▊         | 585/6932 [02:11<23:15,  4.55it/s]

Processing tickers:   8%|▊         | 586/6932 [02:11<22:31,  4.70it/s]

Processing tickers:   8%|▊         | 587/6932 [02:11<22:52,  4.62it/s]

Processing tickers:   8%|▊         | 588/6932 [02:11<23:21,  4.52it/s]

Processing tickers:   8%|▊         | 589/6932 [02:12<22:58,  4.60it/s]

Processing tickers:   9%|▊         | 590/6932 [02:12<22:55,  4.61it/s]

Processing tickers:   9%|▊         | 591/6932 [02:12<22:38,  4.67it/s]

Processing tickers:   9%|▊         | 592/6932 [02:12<22:29,  4.70it/s]

Processing tickers:   9%|▊         | 593/6932 [02:12<22:51,  4.62it/s]

Processing tickers:   9%|▊         | 594/6932 [02:13<22:38,  4.67it/s]

Processing tickers:   9%|▊         | 595/6932 [02:13<22:48,  4.63it/s]

Processing tickers:   9%|▊         | 596/6932 [02:13<22:47,  4.63it/s]

Processing tickers:   9%|▊         | 597/6932 [02:13<22:17,  4.74it/s]

Processing tickers:   9%|▊         | 598/6932 [02:13<22:11,  4.76it/s]

Processing tickers:   9%|▊         | 599/6932 [02:14<22:44,  4.64it/s]

Processing tickers:   9%|▊         | 600/6932 [02:14<22:21,  4.72it/s]

Processing tickers:   9%|▊         | 601/6932 [02:14<22:46,  4.63it/s]

Processing tickers:   9%|▊         | 602/6932 [02:14<22:31,  4.68it/s]

Processing tickers:   9%|▊         | 603/6932 [02:15<22:44,  4.64it/s]

Processing tickers:   9%|▊         | 604/6932 [02:15<22:49,  4.62it/s]

Processing tickers:   9%|▊         | 605/6932 [02:15<22:21,  4.72it/s]

Processing tickers:   9%|▊         | 606/6932 [02:15<22:41,  4.64it/s]

Processing tickers:   9%|▉         | 607/6932 [02:15<23:29,  4.49it/s]

Processing tickers:   9%|▉         | 608/6932 [02:16<23:01,  4.58it/s]

Processing tickers:   9%|▉         | 609/6932 [02:16<22:40,  4.65it/s]

Processing tickers:   9%|▉         | 610/6932 [02:16<22:52,  4.61it/s]

Processing tickers:   9%|▉         | 611/6932 [02:16<22:41,  4.64it/s]

Processing tickers:   9%|▉         | 612/6932 [02:16<22:38,  4.65it/s]

Processing tickers:   9%|▉         | 613/6932 [02:17<22:22,  4.71it/s]

Processing tickers:   9%|▉         | 614/6932 [02:17<22:16,  4.73it/s]

Processing tickers:   9%|▉         | 615/6932 [02:17<22:42,  4.64it/s]

Processing tickers:   9%|▉         | 616/6932 [02:17<22:12,  4.74it/s]

Processing tickers:   9%|▉         | 617/6932 [02:18<22:37,  4.65it/s]

Processing tickers:   9%|▉         | 618/6932 [02:18<22:29,  4.68it/s]

Processing tickers:   9%|▉         | 619/6932 [02:18<22:14,  4.73it/s]

Processing tickers:   9%|▉         | 620/6932 [02:18<22:45,  4.62it/s]

Processing tickers:   9%|▉         | 621/6932 [02:18<22:51,  4.60it/s]

Processing tickers:   9%|▉         | 622/6932 [02:19<23:08,  4.54it/s]

Processing tickers:   9%|▉         | 623/6932 [02:19<23:13,  4.53it/s]

Processing tickers:   9%|▉         | 624/6932 [02:19<22:55,  4.58it/s]

Processing tickers:   9%|▉         | 625/6932 [02:19<22:55,  4.58it/s]

Processing tickers:   9%|▉         | 626/6932 [02:19<22:58,  4.57it/s]

Processing tickers:   9%|▉         | 627/6932 [02:20<23:16,  4.52it/s]

Processing tickers:   9%|▉         | 628/6932 [02:20<23:19,  4.51it/s]

Processing tickers:   9%|▉         | 629/6932 [02:20<23:12,  4.53it/s]

Processing tickers:   9%|▉         | 630/6932 [02:20<23:05,  4.55it/s]

Processing tickers:   9%|▉         | 631/6932 [02:21<23:12,  4.53it/s]

Processing tickers:   9%|▉         | 632/6932 [02:21<22:50,  4.60it/s]

Processing tickers:   9%|▉         | 633/6932 [02:21<22:36,  4.64it/s]

Processing tickers:   9%|▉         | 634/6932 [02:21<22:05,  4.75it/s]

Processing tickers:   9%|▉         | 635/6932 [02:21<21:56,  4.78it/s]

Processing tickers:   9%|▉         | 636/6932 [02:22<22:25,  4.68it/s]

Processing tickers:   9%|▉         | 637/6932 [02:22<22:13,  4.72it/s]

Processing tickers:   9%|▉         | 638/6932 [02:22<22:48,  4.60it/s]

Processing tickers:   9%|▉         | 639/6932 [02:22<22:18,  4.70it/s]

Processing tickers:   9%|▉         | 640/6932 [02:23<22:45,  4.61it/s]

Processing tickers:   9%|▉         | 641/6932 [02:23<23:23,  4.48it/s]

Processing tickers:   9%|▉         | 642/6932 [02:23<22:53,  4.58it/s]

Processing tickers:   9%|▉         | 643/6932 [02:23<22:32,  4.65it/s]

Processing tickers:   9%|▉         | 644/6932 [02:23<22:50,  4.59it/s]

Processing tickers:   9%|▉         | 645/6932 [02:24<23:32,  4.45it/s]

Processing tickers:   9%|▉         | 646/6932 [02:24<23:07,  4.53it/s]

Processing tickers:   9%|▉         | 647/6932 [02:24<23:04,  4.54it/s]

Processing tickers:   9%|▉         | 648/6932 [02:24<22:40,  4.62it/s]

Processing tickers:   9%|▉         | 649/6932 [02:24<22:23,  4.68it/s]

Processing tickers:   9%|▉         | 650/6932 [02:25<22:43,  4.61it/s]

Processing tickers:   9%|▉         | 651/6932 [02:25<22:43,  4.61it/s]

Processing tickers:   9%|▉         | 652/6932 [02:25<22:41,  4.61it/s]

Processing tickers:   9%|▉         | 653/6932 [02:25<22:54,  4.57it/s]

Processing tickers:   9%|▉         | 654/6932 [02:26<22:37,  4.63it/s]

Processing tickers:   9%|▉         | 655/6932 [02:26<22:16,  4.70it/s]

Processing tickers:   9%|▉         | 656/6932 [02:26<22:36,  4.63it/s]

Processing tickers:   9%|▉         | 657/6932 [02:26<22:19,  4.68it/s]

Processing tickers:   9%|▉         | 658/6932 [02:26<22:39,  4.61it/s]

Processing tickers:  10%|▉         | 659/6932 [02:27<23:02,  4.54it/s]

Processing tickers:  10%|▉         | 660/6932 [02:27<22:30,  4.64it/s]

Processing tickers:  10%|▉         | 661/6932 [02:27<22:16,  4.69it/s]

Processing tickers:  10%|▉         | 662/6932 [02:27<22:46,  4.59it/s]

Processing tickers:  10%|▉         | 663/6932 [02:28<22:23,  4.67it/s]

Processing tickers:  10%|▉         | 664/6932 [02:28<22:51,  4.57it/s]

Processing tickers:  10%|▉         | 665/6932 [02:28<23:16,  4.49it/s]

Processing tickers:  10%|▉         | 666/6932 [02:28<22:49,  4.57it/s]

Processing tickers:  10%|▉         | 667/6932 [02:28<22:57,  4.55it/s]

Processing tickers:  10%|▉         | 668/6932 [02:29<22:36,  4.62it/s]

Processing tickers:  10%|▉         | 669/6932 [02:29<22:50,  4.57it/s]

Processing tickers:  10%|▉         | 670/6932 [02:29<22:28,  4.64it/s]

Processing tickers:  10%|▉         | 671/6932 [02:29<22:48,  4.57it/s]

Processing tickers:  10%|▉         | 672/6932 [02:29<22:26,  4.65it/s]

Processing tickers:  10%|▉         | 673/6932 [02:30<22:25,  4.65it/s]

Processing tickers:  10%|▉         | 674/6932 [02:30<22:38,  4.61it/s]

Processing tickers:  10%|▉         | 675/6932 [02:30<22:42,  4.59it/s]

Processing tickers:  10%|▉         | 676/6932 [02:30<22:49,  4.57it/s]

Processing tickers:  10%|▉         | 677/6932 [02:31<22:59,  4.53it/s]

Processing tickers:  10%|▉         | 678/6932 [02:31<23:11,  4.49it/s]

Processing tickers:  10%|▉         | 679/6932 [02:31<22:55,  4.54it/s]

Processing tickers:  10%|▉         | 680/6932 [02:31<22:16,  4.68it/s]

Processing tickers:  10%|▉         | 681/6932 [02:31<22:28,  4.64it/s]

Processing tickers:  10%|▉         | 682/6932 [02:32<22:24,  4.65it/s]

Processing tickers:  10%|▉         | 683/6932 [02:32<21:59,  4.73it/s]

Processing tickers:  10%|▉         | 684/6932 [02:32<22:27,  4.64it/s]

Processing tickers:  10%|▉         | 685/6932 [02:32<22:09,  4.70it/s]

Processing tickers:  10%|▉         | 686/6932 [02:32<21:59,  4.73it/s]

Processing tickers:  10%|▉         | 687/6932 [02:33<22:24,  4.65it/s]

Processing tickers:  10%|▉         | 688/6932 [02:33<22:41,  4.59it/s]

Processing tickers:  10%|▉         | 689/6932 [02:33<22:52,  4.55it/s]

Processing tickers:  10%|▉         | 690/6932 [02:33<22:30,  4.62it/s]

Processing tickers:  10%|▉         | 691/6932 [02:34<22:44,  4.57it/s]

Processing tickers:  10%|▉         | 692/6932 [02:34<22:25,  4.64it/s]

Processing tickers:  10%|▉         | 693/6932 [02:34<23:12,  4.48it/s]

Processing tickers:  10%|█         | 694/6932 [02:34<22:44,  4.57it/s]

Processing tickers:  10%|█         | 695/6932 [02:34<23:04,  4.51it/s]

Processing tickers:  10%|█         | 696/6932 [02:35<22:28,  4.62it/s]

Processing tickers:  10%|█         | 697/6932 [02:35<22:43,  4.57it/s]

Processing tickers:  10%|█         | 698/6932 [02:36<53:50,  1.93it/s]

Processing tickers:  10%|█         | 699/6932 [02:36<44:02,  2.36it/s]

Processing tickers:  10%|█         | 700/6932 [02:37<37:48,  2.75it/s]

Processing tickers:  10%|█         | 701/6932 [02:37<32:58,  3.15it/s]

Processing tickers:  10%|█         | 702/6932 [02:37<29:33,  3.51it/s]

Processing tickers:  10%|█         | 703/6932 [02:37<27:53,  3.72it/s]

Processing tickers:  10%|█         | 704/6932 [02:37<26:10,  3.96it/s]

Processing tickers:  10%|█         | 705/6932 [02:38<24:51,  4.18it/s]

Processing tickers:  10%|█         | 706/6932 [02:38<24:01,  4.32it/s]

Processing tickers:  10%|█         | 707/6932 [02:38<23:27,  4.42it/s]

Processing tickers:  10%|█         | 708/6932 [02:38<23:21,  4.44it/s]

Processing tickers:  10%|█         | 709/6932 [02:38<22:54,  4.53it/s]

Processing tickers:  10%|█         | 710/6932 [02:39<22:25,  4.62it/s]

Processing tickers:  10%|█         | 711/6932 [02:39<22:10,  4.68it/s]

Processing tickers:  10%|█         | 712/6932 [02:39<22:40,  4.57it/s]

Processing tickers:  10%|█         | 713/6932 [02:39<22:10,  4.68it/s]

Processing tickers:  10%|█         | 714/6932 [02:40<22:29,  4.61it/s]

Processing tickers:  10%|█         | 715/6932 [02:40<22:12,  4.67it/s]

Processing tickers:  10%|█         | 716/6932 [02:40<22:01,  4.70it/s]

Processing tickers:  10%|█         | 717/6932 [02:40<21:52,  4.73it/s]

Processing tickers:  10%|█         | 718/6932 [02:40<21:46,  4.76it/s]

Processing tickers:  10%|█         | 719/6932 [02:41<22:01,  4.70it/s]

Processing tickers:  10%|█         | 720/6932 [02:41<22:03,  4.69it/s]

Processing tickers:  10%|█         | 721/6932 [02:41<22:31,  4.60it/s]

Processing tickers:  10%|█         | 722/6932 [02:41<23:41,  4.37it/s]

Processing tickers:  10%|█         | 723/6932 [02:42<23:24,  4.42it/s]

Processing tickers:  10%|█         | 724/6932 [02:42<23:19,  4.44it/s]

Processing tickers:  10%|█         | 725/6932 [02:42<23:47,  4.35it/s]

Processing tickers:  10%|█         | 726/6932 [02:42<23:34,  4.39it/s]

Processing tickers:  10%|█         | 727/6932 [02:42<23:04,  4.48it/s]

Processing tickers:  11%|█         | 728/6932 [02:43<22:23,  4.62it/s]

Processing tickers:  11%|█         | 729/6932 [02:43<22:40,  4.56it/s]

Processing tickers:  11%|█         | 730/6932 [02:43<22:45,  4.54it/s]

Processing tickers:  11%|█         | 731/6932 [02:43<22:53,  4.51it/s]

Processing tickers:  11%|█         | 732/6932 [02:44<22:26,  4.60it/s]

Processing tickers:  11%|█         | 733/6932 [02:44<22:37,  4.57it/s]

Processing tickers:  11%|█         | 734/6932 [02:44<22:16,  4.64it/s]

Processing tickers:  11%|█         | 735/6932 [02:44<22:40,  4.55it/s]

Processing tickers:  11%|█         | 736/6932 [02:44<22:46,  4.54it/s]

Processing tickers:  11%|█         | 737/6932 [02:45<22:17,  4.63it/s]

Processing tickers:  11%|█         | 738/6932 [02:45<22:32,  4.58it/s]

Processing tickers:  11%|█         | 739/6932 [02:45<22:12,  4.65it/s]

Processing tickers:  11%|█         | 740/6932 [02:45<22:33,  4.58it/s]

Processing tickers:  11%|█         | 741/6932 [02:45<22:07,  4.66it/s]

Processing tickers:  11%|█         | 742/6932 [02:46<22:24,  4.60it/s]

Processing tickers:  11%|█         | 743/6932 [02:46<22:09,  4.65it/s]

Processing tickers:  11%|█         | 744/6932 [02:46<22:26,  4.60it/s]

Processing tickers:  11%|█         | 745/6932 [02:46<22:07,  4.66it/s]

Processing tickers:  11%|█         | 746/6932 [02:47<23:00,  4.48it/s]

Processing tickers:  11%|█         | 747/6932 [02:47<22:47,  4.52it/s]

Processing tickers:  11%|█         | 748/6932 [02:47<22:34,  4.57it/s]

Processing tickers:  11%|█         | 749/6932 [02:47<22:14,  4.63it/s]

Processing tickers:  11%|█         | 750/6932 [02:47<22:18,  4.62it/s]

Processing tickers:  11%|█         | 751/6932 [02:48<22:13,  4.63it/s]

Processing tickers:  11%|█         | 752/6932 [02:48<22:29,  4.58it/s]

Processing tickers:  11%|█         | 753/6932 [02:48<22:34,  4.56it/s]

Processing tickers:  11%|█         | 754/6932 [02:48<22:27,  4.59it/s]

Processing tickers:  11%|█         | 755/6932 [02:49<22:01,  4.67it/s]

Processing tickers:  11%|█         | 756/6932 [02:49<22:49,  4.51it/s]

Processing tickers:  11%|█         | 757/6932 [02:49<22:53,  4.49it/s]

Processing tickers:  11%|█         | 758/6932 [02:49<22:42,  4.53it/s]

Processing tickers:  11%|█         | 759/6932 [02:49<22:40,  4.54it/s]

Processing tickers:  11%|█         | 760/6932 [02:50<22:11,  4.64it/s]

Processing tickers:  11%|█         | 761/6932 [02:50<22:27,  4.58it/s]

Processing tickers:  11%|█         | 762/6932 [02:50<22:36,  4.55it/s]

Processing tickers:  11%|█         | 763/6932 [02:50<22:34,  4.56it/s]

Processing tickers:  11%|█         | 764/6932 [02:50<22:21,  4.60it/s]

Processing tickers:  11%|█         | 765/6932 [02:51<22:36,  4.55it/s]

Processing tickers:  11%|█         | 766/6932 [02:51<22:20,  4.60it/s]

Processing tickers:  11%|█         | 767/6932 [02:51<21:52,  4.70it/s]

Processing tickers:  11%|█         | 768/6932 [02:51<21:43,  4.73it/s]

Processing tickers:  11%|█         | 769/6932 [02:52<21:38,  4.75it/s]

Processing tickers:  11%|█         | 770/6932 [02:52<21:58,  4.67it/s]

Processing tickers:  11%|█         | 771/6932 [02:52<22:13,  4.62it/s]

Processing tickers:  11%|█         | 772/6932 [02:52<22:50,  4.49it/s]

Processing tickers:  11%|█         | 773/6932 [02:52<22:26,  4.57it/s]

Processing tickers:  11%|█         | 774/6932 [02:53<24:05,  4.26it/s]

Processing tickers:  11%|█         | 775/6932 [02:53<23:22,  4.39it/s]

Processing tickers:  11%|█         | 776/6932 [02:53<23:07,  4.44it/s]

Processing tickers:  11%|█         | 777/6932 [02:53<22:41,  4.52it/s]

Processing tickers:  11%|█         | 778/6932 [02:54<22:28,  4.56it/s]

Processing tickers:  11%|█         | 779/6932 [02:54<22:11,  4.62it/s]

Processing tickers:  11%|█▏        | 780/6932 [02:54<22:09,  4.63it/s]

Processing tickers:  11%|█▏        | 781/6932 [02:54<22:23,  4.58it/s]

Processing tickers:  11%|█▏        | 782/6932 [02:54<21:56,  4.67it/s]

Processing tickers:  11%|█▏        | 783/6932 [02:55<22:14,  4.61it/s]

Processing tickers:  11%|█▏        | 784/6932 [02:55<21:58,  4.66it/s]

Processing tickers:  11%|█▏        | 785/6932 [02:55<22:15,  4.60it/s]

Processing tickers:  11%|█▏        | 786/6932 [02:55<21:56,  4.67it/s]

Processing tickers:  11%|█▏        | 787/6932 [02:55<21:45,  4.71it/s]

Processing tickers:  11%|█▏        | 788/6932 [02:56<22:36,  4.53it/s]

Processing tickers:  11%|█▏        | 789/6932 [02:56<22:36,  4.53it/s]

Processing tickers:  11%|█▏        | 790/6932 [02:56<22:19,  4.58it/s]

Processing tickers:  11%|█▏        | 791/6932 [02:56<22:28,  4.56it/s]

Processing tickers:  11%|█▏        | 792/6932 [02:57<22:39,  4.52it/s]

Processing tickers:  11%|█▏        | 793/6932 [02:57<22:13,  4.60it/s]

Processing tickers:  11%|█▏        | 794/6932 [02:57<22:14,  4.60it/s]

Processing tickers:  11%|█▏        | 795/6932 [02:57<22:14,  4.60it/s]

Processing tickers:  11%|█▏        | 796/6932 [02:57<21:50,  4.68it/s]

Processing tickers:  11%|█▏        | 797/6932 [02:58<22:15,  4.59it/s]

Processing tickers:  12%|█▏        | 798/6932 [02:58<21:54,  4.67it/s]

Processing tickers:  12%|█▏        | 799/6932 [02:58<21:48,  4.69it/s]

Processing tickers:  12%|█▏        | 800/6932 [02:58<22:00,  4.64it/s]

Processing tickers:  12%|█▏        | 801/6932 [02:59<22:17,  4.59it/s]

Processing tickers:  12%|█▏        | 802/6932 [02:59<22:16,  4.59it/s]

Processing tickers:  12%|█▏        | 803/6932 [02:59<22:08,  4.62it/s]

Processing tickers:  12%|█▏        | 804/6932 [02:59<22:20,  4.57it/s]

Processing tickers:  12%|█▏        | 805/6932 [02:59<22:07,  4.62it/s]

Processing tickers:  12%|█▏        | 806/6932 [03:00<21:44,  4.69it/s]

Processing tickers:  12%|█▏        | 807/6932 [03:00<22:05,  4.62it/s]

Processing tickers:  12%|█▏        | 808/6932 [03:00<22:29,  4.54it/s]

Processing tickers:  12%|█▏        | 809/6932 [03:00<22:16,  4.58it/s]

Processing tickers:  12%|█▏        | 810/6932 [03:01<22:05,  4.62it/s]

Processing tickers:  12%|█▏        | 811/6932 [03:01<22:20,  4.57it/s]

Processing tickers:  12%|█▏        | 812/6932 [03:01<21:57,  4.64it/s]

Processing tickers:  12%|█▏        | 813/6932 [03:01<22:10,  4.60it/s]

Processing tickers:  12%|█▏        | 814/6932 [03:01<22:18,  4.57it/s]

Processing tickers:  12%|█▏        | 815/6932 [03:02<22:19,  4.57it/s]

Processing tickers:  12%|█▏        | 816/6932 [03:02<21:58,  4.64it/s]

Processing tickers:  12%|█▏        | 817/6932 [03:02<21:55,  4.65it/s]

Processing tickers:  12%|█▏        | 818/6932 [03:02<21:43,  4.69it/s]

Processing tickers:  12%|█▏        | 819/6932 [03:02<22:02,  4.62it/s]

Processing tickers:  12%|█▏        | 820/6932 [03:03<21:54,  4.65it/s]

Processing tickers:  12%|█▏        | 821/6932 [03:03<22:17,  4.57it/s]

Processing tickers:  12%|█▏        | 822/6932 [03:03<22:15,  4.57it/s]

Processing tickers:  12%|█▏        | 823/6932 [03:03<22:26,  4.54it/s]

Processing tickers:  12%|█▏        | 824/6932 [03:04<22:26,  4.54it/s]

Processing tickers:  12%|█▏        | 825/6932 [03:04<26:28,  3.85it/s]

Processing tickers:  12%|█▏        | 826/6932 [03:04<25:21,  4.01it/s]

Processing tickers:  12%|█▏        | 827/6932 [03:04<24:12,  4.20it/s]

Processing tickers:  12%|█▏        | 828/6932 [03:05<23:11,  4.39it/s]

Processing tickers:  12%|█▏        | 829/6932 [03:05<23:04,  4.41it/s]

Processing tickers:  12%|█▏        | 830/6932 [03:05<23:07,  4.40it/s]

Processing tickers:  12%|█▏        | 831/6932 [03:05<22:40,  4.49it/s]

Processing tickers:  12%|█▏        | 832/6932 [03:05<21:57,  4.63it/s]

Processing tickers:  12%|█▏        | 833/6932 [03:06<21:43,  4.68it/s]

Processing tickers:  12%|█▏        | 834/6932 [03:06<22:02,  4.61it/s]

Processing tickers:  12%|█▏        | 835/6932 [03:06<22:09,  4.59it/s]

Processing tickers:  12%|█▏        | 836/6932 [03:06<21:55,  4.64it/s]

Processing tickers:  12%|█▏        | 837/6932 [03:06<21:39,  4.69it/s]

Processing tickers:  12%|█▏        | 838/6932 [03:07<22:09,  4.58it/s]

Processing tickers:  12%|█▏        | 839/6932 [03:07<22:09,  4.58it/s]

Processing tickers:  12%|█▏        | 840/6932 [03:07<22:39,  4.48it/s]

Processing tickers:  12%|█▏        | 841/6932 [03:07<22:21,  4.54it/s]

Processing tickers:  12%|█▏        | 842/6932 [03:08<21:58,  4.62it/s]

Processing tickers:  12%|█▏        | 843/6932 [03:08<22:12,  4.57it/s]

Processing tickers:  12%|█▏        | 844/6932 [03:08<21:51,  4.64it/s]

Processing tickers:  12%|█▏        | 845/6932 [03:08<22:08,  4.58it/s]

Processing tickers:  12%|█▏        | 846/6932 [03:08<21:50,  4.64it/s]

Processing tickers:  12%|█▏        | 847/6932 [03:09<21:36,  4.69it/s]

Processing tickers:  12%|█▏        | 848/6932 [03:09<21:24,  4.73it/s]

Processing tickers:  12%|█▏        | 849/6932 [03:09<21:49,  4.65it/s]

Processing tickers:  12%|█▏        | 850/6932 [03:09<21:35,  4.69it/s]

Processing tickers:  12%|█▏        | 851/6932 [03:10<21:54,  4.63it/s]

Processing tickers:  12%|█▏        | 852/6932 [03:10<22:41,  4.47it/s]

Processing tickers:  12%|█▏        | 853/6932 [03:10<22:10,  4.57it/s]

Processing tickers:  12%|█▏        | 854/6932 [03:10<22:04,  4.59it/s]

Processing tickers:  12%|█▏        | 855/6932 [03:10<21:35,  4.69it/s]

Processing tickers:  12%|█▏        | 856/6932 [03:11<22:02,  4.59it/s]

Processing tickers:  12%|█▏        | 857/6932 [03:11<22:04,  4.59it/s]

Processing tickers:  12%|█▏        | 858/6932 [03:11<22:05,  4.58it/s]

Processing tickers:  12%|█▏        | 859/6932 [03:11<21:54,  4.62it/s]

Processing tickers:  12%|█▏        | 860/6932 [03:11<21:40,  4.67it/s]

Processing tickers:  12%|█▏        | 861/6932 [03:12<22:27,  4.51it/s]

Processing tickers:  12%|█▏        | 862/6932 [03:12<22:31,  4.49it/s]

Processing tickers:  12%|█▏        | 863/6932 [03:12<22:22,  4.52it/s]

Processing tickers:  12%|█▏        | 864/6932 [03:12<22:11,  4.56it/s]

Processing tickers:  12%|█▏        | 865/6932 [03:13<22:19,  4.53it/s]

Processing tickers:  12%|█▏        | 866/6932 [03:13<21:54,  4.62it/s]

Processing tickers:  13%|█▎        | 867/6932 [03:13<22:06,  4.57it/s]

Processing tickers:  13%|█▎        | 868/6932 [03:13<21:49,  4.63it/s]

Processing tickers:  13%|█▎        | 869/6932 [03:13<21:31,  4.69it/s]

Processing tickers:  13%|█▎        | 870/6932 [03:14<21:49,  4.63it/s]

Processing tickers:  13%|█▎        | 871/6932 [03:14<21:35,  4.68it/s]

Processing tickers:  13%|█▎        | 872/6932 [03:14<22:01,  4.59it/s]

Processing tickers:  13%|█▎        | 873/6932 [03:14<21:35,  4.68it/s]

Processing tickers:  13%|█▎        | 874/6932 [03:15<21:56,  4.60it/s]

Processing tickers:  13%|█▎        | 875/6932 [03:15<22:49,  4.42it/s]

Processing tickers:  13%|█▎        | 876/6932 [03:15<23:01,  4.38it/s]

Processing tickers:  13%|█▎        | 877/6932 [03:15<22:55,  4.40it/s]

Processing tickers:  13%|█▎        | 878/6932 [03:15<22:47,  4.43it/s]

Processing tickers:  13%|█▎        | 879/6932 [03:16<22:27,  4.49it/s]

Processing tickers:  13%|█▎        | 880/6932 [03:16<21:47,  4.63it/s]

Processing tickers:  13%|█▎        | 881/6932 [03:16<21:32,  4.68it/s]

Processing tickers:  13%|█▎        | 882/6932 [03:16<21:50,  4.62it/s]

Processing tickers:  13%|█▎        | 883/6932 [03:17<21:33,  4.68it/s]

Processing tickers:  13%|█▎        | 884/6932 [03:17<22:22,  4.51it/s]

Processing tickers:  13%|█▎        | 885/6932 [03:17<22:05,  4.56it/s]

Processing tickers:  13%|█▎        | 886/6932 [03:17<21:35,  4.67it/s]

Processing tickers:  13%|█▎        | 887/6932 [03:17<21:24,  4.71it/s]

Processing tickers:  13%|█▎        | 888/6932 [03:18<21:49,  4.61it/s]

Processing tickers:  13%|█▎        | 889/6932 [03:18<21:33,  4.67it/s]

Processing tickers:  13%|█▎        | 890/6932 [03:18<21:18,  4.73it/s]

Processing tickers:  13%|█▎        | 891/6932 [03:18<21:21,  4.71it/s]

Processing tickers:  13%|█▎        | 892/6932 [03:18<21:44,  4.63it/s]

Processing tickers:  13%|█▎        | 893/6932 [03:19<21:51,  4.61it/s]

Processing tickers:  13%|█▎        | 894/6932 [03:19<21:59,  4.58it/s]

Processing tickers:  13%|█▎        | 895/6932 [03:19<21:54,  4.59it/s]

Processing tickers:  13%|█▎        | 896/6932 [03:19<21:22,  4.71it/s]

Processing tickers:  13%|█▎        | 897/6932 [03:20<22:12,  4.53it/s]

Processing tickers:  13%|█▎        | 898/6932 [03:20<23:10,  4.34it/s]

Processing tickers:  13%|█▎        | 899/6932 [03:20<22:36,  4.45it/s]

Processing tickers:  13%|█▎        | 900/6932 [03:20<22:04,  4.55it/s]

Processing tickers:  13%|█▎        | 901/6932 [03:20<21:51,  4.60it/s]

Processing tickers:  13%|█▎        | 902/6932 [03:21<21:56,  4.58it/s]

Processing tickers:  13%|█▎        | 903/6932 [03:21<21:38,  4.64it/s]

Processing tickers:  13%|█▎        | 904/6932 [03:21<21:42,  4.63it/s]

Processing tickers:  13%|█▎        | 905/6932 [03:21<21:42,  4.63it/s]

Processing tickers:  13%|█▎        | 906/6932 [03:22<22:19,  4.50it/s]

Processing tickers:  13%|█▎        | 907/6932 [03:22<21:45,  4.61it/s]

Processing tickers:  13%|█▎        | 908/6932 [03:22<21:58,  4.57it/s]

Processing tickers:  13%|█▎        | 909/6932 [03:22<22:15,  4.51it/s]

Processing tickers:  13%|█▎        | 910/6932 [03:22<22:07,  4.54it/s]

Processing tickers:  13%|█▎        | 911/6932 [03:23<22:10,  4.52it/s]

Processing tickers:  13%|█▎        | 912/6932 [03:23<22:40,  4.42it/s]

Processing tickers:  13%|█▎        | 913/6932 [03:23<22:21,  4.49it/s]

Processing tickers:  13%|█▎        | 914/6932 [03:23<22:15,  4.51it/s]

Processing tickers:  13%|█▎        | 915/6932 [03:24<21:42,  4.62it/s]

Processing tickers:  13%|█▎        | 916/6932 [03:24<22:02,  4.55it/s]

Processing tickers:  13%|█▎        | 917/6932 [03:24<22:08,  4.53it/s]

Processing tickers:  13%|█▎        | 918/6932 [03:24<21:50,  4.59it/s]

Processing tickers:  13%|█▎        | 919/6932 [03:24<21:20,  4.70it/s]

Processing tickers:  13%|█▎        | 920/6932 [03:25<21:11,  4.73it/s]

Processing tickers:  13%|█▎        | 921/6932 [03:25<21:50,  4.59it/s]

Processing tickers:  13%|█▎        | 922/6932 [03:25<21:51,  4.58it/s]

Processing tickers:  13%|█▎        | 923/6932 [03:25<21:59,  4.55it/s]

Processing tickers:  13%|█▎        | 924/6932 [03:25<21:45,  4.60it/s]

Processing tickers:  13%|█▎        | 925/6932 [03:26<21:18,  4.70it/s]

Processing tickers:  13%|█▎        | 926/6932 [03:26<21:39,  4.62it/s]

Processing tickers:  13%|█▎        | 927/6932 [03:26<21:49,  4.59it/s]

Processing tickers:  13%|█▎        | 928/6932 [03:26<21:31,  4.65it/s]

Processing tickers:  13%|█▎        | 929/6932 [03:27<21:46,  4.59it/s]

Processing tickers:  13%|█▎        | 930/6932 [03:27<22:05,  4.53it/s]

Processing tickers:  13%|█▎        | 931/6932 [03:27<21:33,  4.64it/s]

Processing tickers:  13%|█▎        | 932/6932 [03:27<21:55,  4.56it/s]

Processing tickers:  13%|█▎        | 933/6932 [03:27<21:28,  4.65it/s]

Processing tickers:  13%|█▎        | 934/6932 [03:28<21:16,  4.70it/s]

Processing tickers:  13%|█▎        | 935/6932 [03:28<21:40,  4.61it/s]

Processing tickers:  14%|█▎        | 936/6932 [03:28<22:05,  4.52it/s]

Processing tickers:  14%|█▎        | 937/6932 [03:28<21:58,  4.55it/s]

Processing tickers:  14%|█▎        | 938/6932 [03:29<21:33,  4.64it/s]

Processing tickers:  14%|█▎        | 939/6932 [03:29<22:18,  4.48it/s]

Processing tickers:  14%|█▎        | 940/6932 [03:29<21:51,  4.57it/s]

Processing tickers:  14%|█▎        | 941/6932 [03:29<22:16,  4.48it/s]

Processing tickers:  14%|█▎        | 942/6932 [03:29<21:32,  4.63it/s]

Processing tickers:  14%|█▎        | 943/6932 [03:30<21:19,  4.68it/s]

Processing tickers:  14%|█▎        | 944/6932 [03:30<21:39,  4.61it/s]

Processing tickers:  14%|█▎        | 945/6932 [03:30<21:25,  4.66it/s]

Processing tickers:  14%|█▎        | 946/6932 [03:30<21:55,  4.55it/s]

Processing tickers:  14%|█▎        | 947/6932 [03:31<22:37,  4.41it/s]

Processing tickers:  14%|█▎        | 948/6932 [03:31<24:56,  4.00it/s]

Processing tickers:  14%|█▎        | 949/6932 [03:31<24:10,  4.12it/s]

Processing tickers:  14%|█▎        | 950/6932 [03:31<23:52,  4.18it/s]

Processing tickers:  14%|█▎        | 951/6932 [03:31<23:37,  4.22it/s]

Processing tickers:  14%|█▎        | 952/6932 [03:32<23:11,  4.30it/s]

Processing tickers:  14%|█▎        | 953/6932 [03:32<22:51,  4.36it/s]

Processing tickers:  14%|█▍        | 954/6932 [03:32<22:48,  4.37it/s]

Processing tickers:  14%|█▍        | 955/6932 [03:32<22:04,  4.51it/s]

Processing tickers:  14%|█▍        | 956/6932 [03:33<22:06,  4.51it/s]

Processing tickers:  14%|█▍        | 957/6932 [03:33<21:42,  4.59it/s]

Processing tickers:  14%|█▍        | 958/6932 [03:33<21:23,  4.65it/s]

Processing tickers:  14%|█▍        | 959/6932 [03:33<21:49,  4.56it/s]

Processing tickers:  14%|█▍        | 960/6932 [03:33<21:49,  4.56it/s]

Processing tickers:  14%|█▍        | 961/6932 [03:34<21:42,  4.59it/s]

Processing tickers:  14%|█▍        | 962/6932 [03:34<21:49,  4.56it/s]

Processing tickers:  14%|█▍        | 963/6932 [03:34<21:49,  4.56it/s]

Processing tickers:  14%|█▍        | 964/6932 [03:34<21:43,  4.58it/s]

Processing tickers:  14%|█▍        | 965/6932 [03:35<21:36,  4.60it/s]

Processing tickers:  14%|█▍        | 966/6932 [03:35<21:21,  4.65it/s]

Processing tickers:  14%|█▍        | 967/6932 [03:35<21:39,  4.59it/s]

Processing tickers:  14%|█▍        | 968/6932 [03:35<21:49,  4.55it/s]

Processing tickers:  14%|█▍        | 969/6932 [03:35<21:40,  4.59it/s]

Processing tickers:  14%|█▍        | 970/6932 [03:36<21:22,  4.65it/s]

Processing tickers:  14%|█▍        | 971/6932 [03:36<21:09,  4.70it/s]

Processing tickers:  14%|█▍        | 972/6932 [03:36<21:02,  4.72it/s]

Processing tickers:  14%|█▍        | 973/6932 [03:36<21:30,  4.62it/s]

Processing tickers:  14%|█▍        | 974/6932 [03:36<21:09,  4.69it/s]

Processing tickers:  14%|█▍        | 975/6932 [03:37<21:35,  4.60it/s]

Processing tickers:  14%|█▍        | 976/6932 [03:37<21:21,  4.65it/s]

Processing tickers:  14%|█▍        | 977/6932 [03:37<21:01,  4.72it/s]

Processing tickers:  14%|█▍        | 978/6932 [03:37<21:13,  4.68it/s]

Processing tickers:  14%|█▍        | 979/6932 [03:38<21:19,  4.65it/s]

Processing tickers:  14%|█▍        | 980/6932 [03:38<20:58,  4.73it/s]

Processing tickers:  14%|█▍        | 981/6932 [03:38<21:17,  4.66it/s]

Processing tickers:  14%|█▍        | 982/6932 [03:38<21:09,  4.69it/s]

Processing tickers:  14%|█▍        | 983/6932 [03:38<21:27,  4.62it/s]

Processing tickers:  14%|█▍        | 984/6932 [03:39<21:20,  4.65it/s]

Processing tickers:  14%|█▍        | 985/6932 [03:39<21:35,  4.59it/s]

Processing tickers:  14%|█▍        | 986/6932 [03:39<21:47,  4.55it/s]

Processing tickers:  14%|█▍        | 987/6932 [03:39<21:53,  4.53it/s]

Processing tickers:  14%|█▍        | 988/6932 [03:40<21:24,  4.63it/s]

Processing tickers:  14%|█▍        | 989/6932 [03:40<21:11,  4.68it/s]

Processing tickers:  14%|█▍        | 990/6932 [03:40<21:18,  4.65it/s]

Processing tickers:  14%|█▍        | 991/6932 [03:40<21:16,  4.66it/s]

Processing tickers:  14%|█▍        | 992/6932 [03:40<21:03,  4.70it/s]

Processing tickers:  14%|█▍        | 993/6932 [03:41<20:54,  4.73it/s]

Processing tickers:  14%|█▍        | 994/6932 [03:41<20:49,  4.75it/s]

Processing tickers:  14%|█▍        | 995/6932 [03:41<20:46,  4.76it/s]

Processing tickers:  14%|█▍        | 996/6932 [03:41<21:00,  4.71it/s]

Processing tickers:  14%|█▍        | 997/6932 [03:41<21:14,  4.66it/s]

Processing tickers:  14%|█▍        | 998/6932 [03:42<20:50,  4.75it/s]

Processing tickers:  14%|█▍        | 999/6932 [03:42<21:19,  4.64it/s]

Processing tickers:  14%|█▍        | 1000/6932 [03:42<21:26,  4.61it/s]

Processing tickers:  14%|█▍        | 1001/6932 [03:42<21:36,  4.57it/s]

Processing tickers:  14%|█▍        | 1002/6932 [03:43<22:00,  4.49it/s]

Processing tickers:  14%|█▍        | 1003/6932 [03:43<21:47,  4.54it/s]

Processing tickers:  14%|█▍        | 1004/6932 [03:43<21:52,  4.52it/s]

Processing tickers:  14%|█▍        | 1005/6932 [03:43<22:26,  4.40it/s]

Processing tickers:  15%|█▍        | 1006/6932 [03:43<21:53,  4.51it/s]

Processing tickers:  15%|█▍        | 1007/6932 [03:44<22:01,  4.48it/s]

Processing tickers:  15%|█▍        | 1008/6932 [03:44<21:28,  4.60it/s]

Processing tickers:  15%|█▍        | 1009/6932 [03:44<21:42,  4.55it/s]

Processing tickers:  15%|█▍        | 1010/6932 [03:44<21:27,  4.60it/s]

Processing tickers:  15%|█▍        | 1011/6932 [03:44<21:32,  4.58it/s]

Processing tickers:  15%|█▍        | 1012/6932 [03:45<22:10,  4.45it/s]

Processing tickers:  15%|█▍        | 1013/6932 [03:45<21:45,  4.54it/s]

Processing tickers:  15%|█▍        | 1014/6932 [03:45<21:16,  4.64it/s]

Processing tickers:  15%|█▍        | 1015/6932 [03:45<21:02,  4.69it/s]

Processing tickers:  15%|█▍        | 1016/6932 [03:46<21:07,  4.67it/s]

Processing tickers:  15%|█▍        | 1017/6932 [03:46<21:09,  4.66it/s]

Processing tickers:  15%|█▍        | 1018/6932 [03:46<20:58,  4.70it/s]

Processing tickers:  15%|█▍        | 1019/6932 [03:46<20:48,  4.73it/s]

Processing tickers:  15%|█▍        | 1020/6932 [03:46<20:41,  4.76it/s]

Processing tickers:  15%|█▍        | 1021/6932 [03:47<20:49,  4.73it/s]

Processing tickers:  15%|█▍        | 1022/6932 [03:47<20:41,  4.76it/s]

Processing tickers:  15%|█▍        | 1023/6932 [03:47<20:29,  4.81it/s]

Processing tickers:  15%|█▍        | 1024/6932 [03:47<20:29,  4.81it/s]

Processing tickers:  15%|█▍        | 1025/6932 [03:47<20:29,  4.80it/s]

Processing tickers:  15%|█▍        | 1026/6932 [03:48<20:55,  4.70it/s]

Processing tickers:  15%|█▍        | 1027/6932 [03:48<21:19,  4.62it/s]

Processing tickers:  15%|█▍        | 1028/6932 [03:48<21:27,  4.59it/s]

Processing tickers:  15%|█▍        | 1029/6932 [03:48<21:44,  4.53it/s]

Processing tickers:  15%|█▍        | 1030/6932 [03:49<21:32,  4.57it/s]

Processing tickers:  15%|█▍        | 1031/6932 [03:49<20:55,  4.70it/s]

Processing tickers:  15%|█▍        | 1032/6932 [03:49<21:15,  4.63it/s]

Processing tickers:  15%|█▍        | 1033/6932 [03:49<20:58,  4.69it/s]

Processing tickers:  15%|█▍        | 1034/6932 [03:49<20:48,  4.72it/s]

Processing tickers:  15%|█▍        | 1035/6932 [03:50<21:27,  4.58it/s]

Processing tickers:  15%|█▍        | 1036/6932 [03:50<21:15,  4.62it/s]

Processing tickers:  15%|█▍        | 1037/6932 [03:50<21:06,  4.65it/s]

Processing tickers:  15%|█▍        | 1038/6932 [03:50<20:52,  4.70it/s]

Processing tickers:  15%|█▍        | 1039/6932 [03:51<21:12,  4.63it/s]

Processing tickers:  15%|█▌        | 1040/6932 [03:51<21:27,  4.58it/s]

Processing tickers:  15%|█▌        | 1041/6932 [03:51<21:08,  4.65it/s]

Processing tickers:  15%|█▌        | 1042/6932 [03:51<20:56,  4.69it/s]

Processing tickers:  15%|█▌        | 1043/6932 [03:51<20:50,  4.71it/s]

Processing tickers:  15%|█▌        | 1044/6932 [03:52<20:49,  4.71it/s]

Processing tickers:  15%|█▌        | 1045/6932 [03:52<21:38,  4.54it/s]

Processing tickers:  15%|█▌        | 1046/6932 [03:52<21:08,  4.64it/s]

Processing tickers:  15%|█▌        | 1047/6932 [03:52<20:51,  4.70it/s]

Processing tickers:  15%|█▌        | 1048/6932 [03:52<20:37,  4.75it/s]

Processing tickers:  15%|█▌        | 1049/6932 [03:53<21:25,  4.58it/s]

Processing tickers:  15%|█▌        | 1050/6932 [03:53<21:04,  4.65it/s]

Processing tickers:  15%|█▌        | 1051/6932 [03:53<20:53,  4.69it/s]

Processing tickers:  15%|█▌        | 1052/6932 [03:53<20:44,  4.72it/s]

Processing tickers:  15%|█▌        | 1053/6932 [03:53<20:36,  4.76it/s]

Processing tickers:  15%|█▌        | 1054/6932 [03:54<20:33,  4.76it/s]

Processing tickers:  15%|█▌        | 1055/6932 [03:54<20:35,  4.76it/s]

Processing tickers:  15%|█▌        | 1056/6932 [03:54<20:26,  4.79it/s]

Processing tickers:  15%|█▌        | 1057/6932 [03:54<20:25,  4.79it/s]

Processing tickers:  15%|█▌        | 1058/6932 [03:55<20:24,  4.80it/s]

Processing tickers:  15%|█▌        | 1059/6932 [03:55<21:05,  4.64it/s]

Processing tickers:  15%|█▌        | 1060/6932 [03:55<21:01,  4.65it/s]

Processing tickers:  15%|█▌        | 1061/6932 [03:55<20:28,  4.78it/s]

Processing tickers:  15%|█▌        | 1062/6932 [03:55<21:00,  4.66it/s]

Processing tickers:  15%|█▌        | 1063/6932 [03:56<20:42,  4.72it/s]

Processing tickers:  15%|█▌        | 1064/6932 [03:56<20:36,  4.75it/s]

Processing tickers:  15%|█▌        | 1065/6932 [03:56<20:59,  4.66it/s]

Processing tickers:  15%|█▌        | 1066/6932 [03:56<20:58,  4.66it/s]

Processing tickers:  15%|█▌        | 1067/6932 [03:56<21:37,  4.52it/s]

Processing tickers:  15%|█▌        | 1068/6932 [03:57<21:42,  4.50it/s]

Processing tickers:  15%|█▌        | 1069/6932 [03:57<21:12,  4.61it/s]

Processing tickers:  15%|█▌        | 1070/6932 [03:57<21:24,  4.56it/s]

Processing tickers:  15%|█▌        | 1071/6932 [03:57<21:34,  4.53it/s]

Processing tickers:  15%|█▌        | 1072/6932 [03:58<21:40,  4.51it/s]

Processing tickers:  15%|█▌        | 1073/6932 [03:58<21:15,  4.59it/s]

Processing tickers:  15%|█▌        | 1074/6932 [03:58<21:54,  4.46it/s]

Processing tickers:  16%|█▌        | 1075/6932 [03:58<21:24,  4.56it/s]

Processing tickers:  16%|█▌        | 1076/6932 [03:58<21:33,  4.53it/s]

Processing tickers:  16%|█▌        | 1077/6932 [03:59<21:38,  4.51it/s]

Processing tickers:  16%|█▌        | 1078/6932 [03:59<21:31,  4.53it/s]

Processing tickers:  16%|█▌        | 1079/6932 [03:59<21:19,  4.58it/s]

Processing tickers:  16%|█▌        | 1080/6932 [03:59<21:00,  4.64it/s]

Processing tickers:  16%|█▌        | 1081/6932 [04:00<21:14,  4.59it/s]

Processing tickers:  16%|█▌        | 1082/6932 [04:00<21:01,  4.64it/s]

Processing tickers:  16%|█▌        | 1083/6932 [04:00<21:12,  4.60it/s]

Processing tickers:  16%|█▌        | 1084/6932 [04:00<20:56,  4.65it/s]

Processing tickers:  16%|█▌        | 1085/6932 [04:00<20:44,  4.70it/s]

Processing tickers:  16%|█▌        | 1086/6932 [04:01<21:57,  4.44it/s]

Processing tickers:  16%|█▌        | 1087/6932 [04:01<21:56,  4.44it/s]

Processing tickers:  16%|█▌        | 1088/6932 [04:01<22:16,  4.37it/s]

Processing tickers:  16%|█▌        | 1089/6932 [04:01<21:43,  4.48it/s]

Processing tickers:  16%|█▌        | 1090/6932 [04:02<21:48,  4.46it/s]

Processing tickers:  16%|█▌        | 1091/6932 [04:02<21:19,  4.56it/s]

Processing tickers:  16%|█▌        | 1092/6932 [04:02<21:00,  4.63it/s]

Processing tickers:  16%|█▌        | 1093/6932 [04:02<20:44,  4.69it/s]

Processing tickers:  16%|█▌        | 1094/6932 [04:02<20:35,  4.72it/s]

Processing tickers:  16%|█▌        | 1095/6932 [04:03<20:27,  4.76it/s]

Processing tickers:  16%|█▌        | 1096/6932 [04:03<20:48,  4.67it/s]

Processing tickers:  16%|█▌        | 1097/6932 [04:03<20:38,  4.71it/s]

Processing tickers:  16%|█▌        | 1098/6932 [04:03<20:30,  4.74it/s]

Processing tickers:  16%|█▌        | 1099/6932 [04:03<21:09,  4.60it/s]

Processing tickers:  16%|█▌        | 1100/6932 [04:04<21:04,  4.61it/s]

Processing tickers:  16%|█▌        | 1101/6932 [04:04<21:24,  4.54it/s]

Processing tickers:  16%|█▌        | 1102/6932 [04:04<21:03,  4.61it/s]

Processing tickers:  16%|█▌        | 1103/6932 [04:04<20:58,  4.63it/s]

Processing tickers:  16%|█▌        | 1104/6932 [04:05<20:49,  4.66it/s]

Processing tickers:  16%|█▌        | 1105/6932 [04:05<21:12,  4.58it/s]

Processing tickers:  16%|█▌        | 1106/6932 [04:05<20:58,  4.63it/s]

Processing tickers:  16%|█▌        | 1107/6932 [04:05<20:34,  4.72it/s]

Processing tickers:  16%|█▌        | 1108/6932 [04:05<20:28,  4.74it/s]

Processing tickers:  16%|█▌        | 1109/6932 [04:06<20:49,  4.66it/s]

Processing tickers:  16%|█▌        | 1110/6932 [04:06<20:39,  4.70it/s]

Processing tickers:  16%|█▌        | 1111/6932 [04:06<20:02,  4.84it/s]

Processing tickers:  16%|█▌        | 1112/6932 [04:06<20:07,  4.82it/s]

Processing tickers:  16%|█▌        | 1113/6932 [04:06<20:08,  4.82it/s]

Processing tickers:  16%|█▌        | 1114/6932 [04:07<20:07,  4.82it/s]

Processing tickers:  16%|█▌        | 1115/6932 [04:07<20:07,  4.82it/s]

Processing tickers:  16%|█▌        | 1116/6932 [04:07<20:33,  4.71it/s]

Processing tickers:  16%|█▌        | 1117/6932 [04:07<20:26,  4.74it/s]

Processing tickers:  16%|█▌        | 1118/6932 [04:08<20:27,  4.74it/s]

Processing tickers:  16%|█▌        | 1119/6932 [04:08<20:16,  4.78it/s]

Processing tickers:  16%|█▌        | 1120/6932 [04:08<20:13,  4.79it/s]

Processing tickers:  16%|█▌        | 1121/6932 [04:08<20:18,  4.77it/s]

Processing tickers:  16%|█▌        | 1122/6932 [04:08<20:08,  4.81it/s]

Processing tickers:  16%|█▌        | 1123/6932 [04:09<20:07,  4.81it/s]

Processing tickers:  16%|█▌        | 1124/6932 [04:09<20:45,  4.66it/s]

Processing tickers:  16%|█▌        | 1125/6932 [04:09<20:22,  4.75it/s]

Processing tickers:  16%|█▌        | 1126/6932 [04:09<20:39,  4.68it/s]

Processing tickers:  16%|█▋        | 1127/6932 [04:09<20:06,  4.81it/s]

Processing tickers:  16%|█▋        | 1128/6932 [04:10<20:06,  4.81it/s]

Processing tickers:  16%|█▋        | 1129/6932 [04:10<20:24,  4.74it/s]

Processing tickers:  16%|█▋        | 1130/6932 [04:10<20:29,  4.72it/s]

Processing tickers:  16%|█▋        | 1131/6932 [04:10<20:21,  4.75it/s]

Processing tickers:  16%|█▋        | 1132/6932 [04:10<20:17,  4.77it/s]

Processing tickers:  16%|█▋        | 1133/6932 [04:11<20:14,  4.77it/s]

Processing tickers:  16%|█▋        | 1134/6932 [04:11<20:18,  4.76it/s]

Processing tickers:  16%|█▋        | 1135/6932 [04:11<20:37,  4.68it/s]

Processing tickers:  16%|█▋        | 1136/6932 [04:11<20:28,  4.72it/s]

Processing tickers:  16%|█▋        | 1137/6932 [04:12<20:42,  4.66it/s]

Processing tickers:  16%|█▋        | 1138/6932 [04:12<20:36,  4.68it/s]

Processing tickers:  16%|█▋        | 1139/6932 [04:12<20:57,  4.60it/s]

Processing tickers:  16%|█▋        | 1140/6932 [04:12<20:43,  4.66it/s]

Processing tickers:  16%|█▋        | 1141/6932 [04:12<20:51,  4.63it/s]

Processing tickers:  16%|█▋        | 1142/6932 [04:13<20:42,  4.66it/s]

Processing tickers:  16%|█▋        | 1143/6932 [04:13<20:31,  4.70it/s]

Processing tickers:  17%|█▋        | 1144/6932 [04:13<20:21,  4.74it/s]

Processing tickers:  17%|█▋        | 1145/6932 [04:13<20:21,  4.74it/s]

Processing tickers:  17%|█▋        | 1146/6932 [04:13<20:17,  4.75it/s]

Processing tickers:  17%|█▋        | 1147/6932 [04:14<20:11,  4.77it/s]

Processing tickers:  17%|█▋        | 1148/6932 [04:14<20:07,  4.79it/s]

Processing tickers:  17%|█▋        | 1149/6932 [04:14<20:01,  4.81it/s]

Processing tickers:  17%|█▋        | 1150/6932 [04:14<20:01,  4.81it/s]

Processing tickers:  17%|█▋        | 1151/6932 [04:14<20:03,  4.80it/s]

Processing tickers:  17%|█▋        | 1152/6932 [04:15<20:04,  4.80it/s]

Processing tickers:  17%|█▋        | 1153/6932 [04:15<28:55,  3.33it/s]

Processing tickers:  17%|█▋        | 1154/6932 [04:15<26:15,  3.67it/s]

Processing tickers:  17%|█▋        | 1155/6932 [04:16<24:45,  3.89it/s]

Processing tickers:  17%|█▋        | 1156/6932 [04:16<23:18,  4.13it/s]

Processing tickers:  17%|█▋        | 1157/6932 [04:16<22:13,  4.33it/s]

Processing tickers:  17%|█▋        | 1158/6932 [04:16<22:04,  4.36it/s]

Processing tickers:  17%|█▋        | 1159/6932 [04:16<21:47,  4.42it/s]

Processing tickers:  17%|█▋        | 1160/6932 [04:17<21:17,  4.52it/s]

Processing tickers:  17%|█▋        | 1161/6932 [04:17<21:21,  4.50it/s]

Processing tickers:  17%|█▋        | 1162/6932 [04:17<21:11,  4.54it/s]

Processing tickers:  17%|█▋        | 1163/6932 [04:17<20:57,  4.59it/s]

Processing tickers:  17%|█▋        | 1164/6932 [04:18<20:39,  4.65it/s]

Processing tickers:  17%|█▋        | 1165/6932 [04:18<21:00,  4.57it/s]

Processing tickers:  17%|█▋        | 1166/6932 [04:18<21:10,  4.54it/s]

Processing tickers:  17%|█▋        | 1167/6932 [04:18<21:10,  4.54it/s]

Processing tickers:  17%|█▋        | 1168/6932 [04:18<20:50,  4.61it/s]

Processing tickers:  17%|█▋        | 1169/6932 [04:19<20:53,  4.60it/s]

Processing tickers:  17%|█▋        | 1170/6932 [04:19<20:49,  4.61it/s]

Processing tickers:  17%|█▋        | 1171/6932 [04:19<20:28,  4.69it/s]

Processing tickers:  17%|█▋        | 1172/6932 [04:19<21:00,  4.57it/s]

Processing tickers:  17%|█▋        | 1173/6932 [04:20<21:14,  4.52it/s]

Processing tickers:  17%|█▋        | 1174/6932 [04:20<21:08,  4.54it/s]

Processing tickers:  17%|█▋        | 1175/6932 [04:20<21:06,  4.55it/s]

Processing tickers:  17%|█▋        | 1176/6932 [04:20<20:51,  4.60it/s]

Processing tickers:  17%|█▋        | 1177/6932 [04:20<20:31,  4.67it/s]

Processing tickers:  17%|█▋        | 1178/6932 [04:21<20:37,  4.65it/s]

Processing tickers:  17%|█▋        | 1179/6932 [04:21<20:33,  4.67it/s]

Processing tickers:  17%|█▋        | 1180/6932 [04:21<20:21,  4.71it/s]

Processing tickers:  17%|█▋        | 1181/6932 [04:21<21:09,  4.53it/s]

Processing tickers:  17%|█▋        | 1182/6932 [04:21<21:15,  4.51it/s]

Processing tickers:  17%|█▋        | 1183/6932 [04:22<21:27,  4.47it/s]

Processing tickers:  17%|█▋        | 1184/6932 [04:22<20:47,  4.61it/s]

Processing tickers:  17%|█▋        | 1185/6932 [04:22<21:24,  4.47it/s]

Processing tickers:  17%|█▋        | 1186/6932 [04:22<21:22,  4.48it/s]

Processing tickers:  17%|█▋        | 1187/6932 [04:23<21:49,  4.39it/s]

Processing tickers:  17%|█▋        | 1188/6932 [04:23<21:42,  4.41it/s]

Processing tickers:  17%|█▋        | 1189/6932 [04:23<21:37,  4.43it/s]

Processing tickers:  17%|█▋        | 1190/6932 [04:23<21:38,  4.42it/s]

Processing tickers:  17%|█▋        | 1191/6932 [04:23<21:03,  4.54it/s]

Processing tickers:  17%|█▋        | 1192/6932 [04:24<21:39,  4.42it/s]

Processing tickers:  17%|█▋        | 1193/6932 [04:24<21:31,  4.44it/s]

Processing tickers:  17%|█▋        | 1194/6932 [04:24<21:21,  4.48it/s]

Processing tickers:  17%|█▋        | 1195/6932 [04:24<20:39,  4.63it/s]

Processing tickers:  17%|█▋        | 1196/6932 [04:25<20:27,  4.67it/s]

Processing tickers:  17%|█▋        | 1197/6932 [04:25<20:13,  4.73it/s]

Processing tickers:  17%|█▋        | 1198/6932 [04:25<20:06,  4.75it/s]

Processing tickers:  17%|█▋        | 1199/6932 [04:25<20:06,  4.75it/s]

Processing tickers:  17%|█▋        | 1200/6932 [04:25<20:25,  4.68it/s]

Processing tickers:  17%|█▋        | 1201/6932 [04:26<20:14,  4.72it/s]

Processing tickers:  17%|█▋        | 1202/6932 [04:26<20:10,  4.73it/s]

Processing tickers:  17%|█▋        | 1203/6932 [04:26<20:05,  4.75it/s]

Processing tickers:  17%|█▋        | 1204/6932 [04:26<20:00,  4.77it/s]

Processing tickers:  17%|█▋        | 1205/6932 [04:26<20:25,  4.67it/s]

Processing tickers:  17%|█▋        | 1206/6932 [04:27<22:36,  4.22it/s]

Processing tickers:  17%|█▋        | 1207/6932 [04:27<21:46,  4.38it/s]

Processing tickers:  17%|█▋        | 1208/6932 [04:27<21:13,  4.49it/s]

Processing tickers:  17%|█▋        | 1209/6932 [04:27<20:44,  4.60it/s]

Processing tickers:  17%|█▋        | 1210/6932 [04:28<20:28,  4.66it/s]

Processing tickers:  17%|█▋        | 1211/6932 [04:28<20:16,  4.70it/s]

Processing tickers:  17%|█▋        | 1212/6932 [04:28<20:22,  4.68it/s]

Processing tickers:  17%|█▋        | 1213/6932 [04:28<20:06,  4.74it/s]

Processing tickers:  18%|█▊        | 1214/6932 [04:28<20:24,  4.67it/s]

Processing tickers:  18%|█▊        | 1215/6932 [04:29<20:44,  4.59it/s]

Processing tickers:  18%|█▊        | 1216/6932 [04:29<20:24,  4.67it/s]

Processing tickers:  18%|█▊        | 1217/6932 [04:29<20:15,  4.70it/s]

Processing tickers:  18%|█▊        | 1218/6932 [04:29<20:06,  4.74it/s]

Processing tickers:  18%|█▊        | 1219/6932 [04:30<20:01,  4.76it/s]

Processing tickers:  18%|█▊        | 1220/6932 [04:30<20:24,  4.67it/s]

Processing tickers:  18%|█▊        | 1221/6932 [04:30<20:13,  4.71it/s]

Processing tickers:  18%|█▊        | 1222/6932 [04:30<20:11,  4.71it/s]

Processing tickers:  18%|█▊        | 1223/6932 [04:30<19:59,  4.76it/s]

Processing tickers:  18%|█▊        | 1224/6932 [04:31<20:23,  4.67it/s]

Processing tickers:  18%|█▊        | 1225/6932 [04:31<20:12,  4.71it/s]

Processing tickers:  18%|█▊        | 1226/6932 [04:31<20:03,  4.74it/s]

Processing tickers:  18%|█▊        | 1227/6932 [04:31<19:56,  4.77it/s]

Processing tickers:  18%|█▊        | 1228/6932 [04:31<20:20,  4.67it/s]

Processing tickers:  18%|█▊        | 1229/6932 [04:32<19:43,  4.82it/s]

Processing tickers:  18%|█▊        | 1230/6932 [04:32<20:17,  4.68it/s]

Processing tickers:  18%|█▊        | 1231/6932 [04:32<20:17,  4.68it/s]

Processing tickers:  18%|█▊        | 1232/6932 [04:32<19:49,  4.79it/s]

Processing tickers:  18%|█▊        | 1233/6932 [04:32<19:44,  4.81it/s]

Processing tickers:  18%|█▊        | 1234/6932 [04:33<19:44,  4.81it/s]

Processing tickers:  18%|█▊        | 1235/6932 [04:33<20:14,  4.69it/s]

Processing tickers:  18%|█▊        | 1236/6932 [04:33<20:04,  4.73it/s]

Processing tickers:  18%|█▊        | 1237/6932 [04:33<20:26,  4.64it/s]

Processing tickers:  18%|█▊        | 1238/6932 [04:34<20:13,  4.69it/s]

Processing tickers:  18%|█▊        | 1239/6932 [04:34<20:33,  4.62it/s]

Processing tickers:  18%|█▊        | 1240/6932 [04:34<20:19,  4.67it/s]

Processing tickers:  18%|█▊        | 1241/6932 [04:34<19:41,  4.82it/s]

Processing tickers:  18%|█▊        | 1242/6932 [04:34<20:04,  4.72it/s]

Processing tickers:  18%|█▊        | 1243/6932 [04:35<20:04,  4.72it/s]

Processing tickers:  18%|█▊        | 1244/6932 [04:35<19:57,  4.75it/s]

Processing tickers:  18%|█▊        | 1245/6932 [04:35<19:52,  4.77it/s]

Processing tickers:  18%|█▊        | 1246/6932 [04:35<19:50,  4.77it/s]

Processing tickers:  18%|█▊        | 1247/6932 [04:35<20:17,  4.67it/s]

Processing tickers:  18%|█▊        | 1248/6932 [04:36<20:06,  4.71it/s]

Processing tickers:  18%|█▊        | 1249/6932 [04:36<19:55,  4.75it/s]

Processing tickers:  18%|█▊        | 1250/6932 [04:36<19:51,  4.77it/s]

Processing tickers:  18%|█▊        | 1251/6932 [04:36<19:48,  4.78it/s]

Processing tickers:  18%|█▊        | 1252/6932 [04:36<19:49,  4.78it/s]

Processing tickers:  18%|█▊        | 1253/6932 [04:37<19:48,  4.78it/s]

Processing tickers:  18%|█▊        | 1254/6932 [04:37<19:41,  4.81it/s]

Processing tickers:  18%|█▊        | 1255/6932 [04:37<19:40,  4.81it/s]

Processing tickers:  18%|█▊        | 1256/6932 [04:37<20:08,  4.70it/s]

Processing tickers:  18%|█▊        | 1257/6932 [04:38<20:16,  4.67it/s]

Processing tickers:  18%|█▊        | 1258/6932 [04:38<20:08,  4.70it/s]

Processing tickers:  18%|█▊        | 1259/6932 [04:38<20:01,  4.72it/s]

Processing tickers:  18%|█▊        | 1260/6932 [04:38<19:34,  4.83it/s]

Processing tickers:  18%|█▊        | 1261/6932 [04:38<19:36,  4.82it/s]

Processing tickers:  18%|█▊        | 1262/6932 [04:39<19:38,  4.81it/s]

Processing tickers:  18%|█▊        | 1263/6932 [04:39<19:37,  4.82it/s]

Processing tickers:  18%|█▊        | 1264/6932 [04:39<19:37,  4.81it/s]

Processing tickers:  18%|█▊        | 1265/6932 [04:39<20:04,  4.70it/s]

Processing tickers:  18%|█▊        | 1266/6932 [04:39<19:57,  4.73it/s]

Processing tickers:  18%|█▊        | 1267/6932 [04:40<19:52,  4.75it/s]

Processing tickers:  18%|█▊        | 1268/6932 [04:40<19:51,  4.76it/s]

Processing tickers:  18%|█▊        | 1269/6932 [04:40<19:43,  4.78it/s]

Processing tickers:  18%|█▊        | 1270/6932 [04:40<20:14,  4.66it/s]

Processing tickers:  18%|█▊        | 1271/6932 [04:40<19:57,  4.73it/s]

Processing tickers:  18%|█▊        | 1272/6932 [04:41<20:00,  4.72it/s]

Processing tickers:  18%|█▊        | 1273/6932 [04:41<19:56,  4.73it/s]

Processing tickers:  18%|█▊        | 1274/6932 [04:41<19:39,  4.80it/s]

Processing tickers:  18%|█▊        | 1275/6932 [04:41<19:38,  4.80it/s]

Processing tickers:  18%|█▊        | 1276/6932 [04:42<19:58,  4.72it/s]

Processing tickers:  18%|█▊        | 1277/6932 [04:42<20:18,  4.64it/s]

Processing tickers:  18%|█▊        | 1278/6932 [04:42<20:11,  4.67it/s]

Processing tickers:  18%|█▊        | 1279/6932 [04:42<20:00,  4.71it/s]

Processing tickers:  18%|█▊        | 1280/6932 [04:42<19:51,  4.74it/s]

Processing tickers:  18%|█▊        | 1281/6932 [04:43<20:37,  4.57it/s]

Processing tickers:  18%|█▊        | 1282/6932 [04:43<20:17,  4.64it/s]

Processing tickers:  19%|█▊        | 1283/6932 [04:43<20:05,  4.69it/s]

Processing tickers:  19%|█▊        | 1284/6932 [04:43<20:09,  4.67it/s]

Processing tickers:  19%|█▊        | 1285/6932 [04:43<19:46,  4.76it/s]

Processing tickers:  19%|█▊        | 1286/6932 [04:44<20:14,  4.65it/s]

Processing tickers:  19%|█▊        | 1287/6932 [04:44<20:20,  4.62it/s]

Processing tickers:  19%|█▊        | 1288/6932 [04:44<20:21,  4.62it/s]

Processing tickers:  19%|█▊        | 1289/6932 [04:44<20:23,  4.61it/s]

Processing tickers:  19%|█▊        | 1290/6932 [04:45<20:10,  4.66it/s]

Processing tickers:  19%|█▊        | 1291/6932 [04:45<19:59,  4.70it/s]

Processing tickers:  19%|█▊        | 1292/6932 [04:45<20:19,  4.63it/s]

Processing tickers:  19%|█▊        | 1293/6932 [04:45<20:05,  4.68it/s]

Processing tickers:  19%|█▊        | 1294/6932 [04:45<20:22,  4.61it/s]

Processing tickers:  19%|█▊        | 1295/6932 [04:46<20:14,  4.64it/s]

Processing tickers:  19%|█▊        | 1296/6932 [04:46<20:29,  4.58it/s]

Processing tickers:  19%|█▊        | 1297/6932 [04:46<20:34,  4.57it/s]

Processing tickers:  19%|█▊        | 1298/6932 [04:46<19:49,  4.74it/s]

Processing tickers:  19%|█▊        | 1299/6932 [04:46<19:42,  4.76it/s]

Processing tickers:  19%|█▉        | 1300/6932 [04:47<19:58,  4.70it/s]

Processing tickers:  19%|█▉        | 1301/6932 [04:47<19:58,  4.70it/s]

Processing tickers:  19%|█▉        | 1302/6932 [04:47<20:23,  4.60it/s]

Processing tickers:  19%|█▉        | 1303/6932 [04:47<20:22,  4.60it/s]

Processing tickers:  19%|█▉        | 1304/6932 [04:48<20:39,  4.54it/s]

Processing tickers:  19%|█▉        | 1305/6932 [04:48<20:35,  4.55it/s]

Processing tickers:  19%|█▉        | 1306/6932 [04:48<20:30,  4.57it/s]

Processing tickers:  19%|█▉        | 1307/6932 [04:48<20:42,  4.53it/s]

Processing tickers:  19%|█▉        | 1308/6932 [04:48<20:32,  4.56it/s]

Processing tickers:  19%|█▉        | 1309/6932 [04:49<19:56,  4.70it/s]

Processing tickers:  19%|█▉        | 1310/6932 [04:49<19:43,  4.75it/s]

Processing tickers:  19%|█▉        | 1311/6932 [04:49<19:59,  4.69it/s]

Processing tickers:  19%|█▉        | 1312/6932 [04:49<19:56,  4.70it/s]

Processing tickers:  19%|█▉        | 1313/6932 [04:49<19:54,  4.70it/s]

Processing tickers:  19%|█▉        | 1314/6932 [04:50<20:08,  4.65it/s]

Processing tickers:  19%|█▉        | 1315/6932 [04:50<20:23,  4.59it/s]

Processing tickers:  19%|█▉        | 1316/6932 [04:50<20:08,  4.65it/s]

Processing tickers:  19%|█▉        | 1317/6932 [04:50<20:09,  4.64it/s]

Processing tickers:  19%|█▉        | 1318/6932 [04:51<20:14,  4.62it/s]

Processing tickers:  19%|█▉        | 1319/6932 [04:51<20:17,  4.61it/s]

Processing tickers:  19%|█▉        | 1320/6932 [04:51<20:19,  4.60it/s]

Processing tickers:  19%|█▉        | 1321/6932 [04:51<20:36,  4.54it/s]

Processing tickers:  19%|█▉        | 1322/6932 [04:51<20:15,  4.61it/s]

Processing tickers:  19%|█▉        | 1323/6932 [04:52<20:27,  4.57it/s]

Processing tickers:  19%|█▉        | 1324/6932 [04:52<20:40,  4.52it/s]

Processing tickers:  19%|█▉        | 1325/6932 [04:52<20:10,  4.63it/s]

Processing tickers:  19%|█▉        | 1326/6932 [04:52<19:58,  4.68it/s]

Processing tickers:  19%|█▉        | 1327/6932 [04:53<19:46,  4.72it/s]

Processing tickers:  19%|█▉        | 1328/6932 [04:53<20:05,  4.65it/s]

Processing tickers:  19%|█▉        | 1329/6932 [04:53<19:49,  4.71it/s]

Processing tickers:  19%|█▉        | 1330/6932 [04:53<20:06,  4.64it/s]

Processing tickers:  19%|█▉        | 1331/6932 [04:53<20:35,  4.53it/s]

Processing tickers:  19%|█▉        | 1332/6932 [04:54<20:24,  4.57it/s]

Processing tickers:  19%|█▉        | 1333/6932 [04:54<20:12,  4.62it/s]

Processing tickers:  19%|█▉        | 1334/6932 [04:54<20:07,  4.64it/s]

Processing tickers:  19%|█▉        | 1335/6932 [04:54<19:39,  4.75it/s]

Processing tickers:  19%|█▉        | 1336/6932 [04:54<19:32,  4.77it/s]

Processing tickers:  19%|█▉        | 1337/6932 [04:55<19:59,  4.66it/s]

Processing tickers:  19%|█▉        | 1338/6932 [04:55<20:13,  4.61it/s]

Processing tickers:  19%|█▉        | 1339/6932 [04:55<19:56,  4.67it/s]

Processing tickers:  19%|█▉        | 1340/6932 [04:55<19:47,  4.71it/s]

Processing tickers:  19%|█▉        | 1341/6932 [04:56<20:09,  4.62it/s]

Processing tickers:  19%|█▉        | 1342/6932 [04:56<20:15,  4.60it/s]

Processing tickers:  19%|█▉        | 1343/6932 [04:56<19:36,  4.75it/s]

Processing tickers:  19%|█▉        | 1344/6932 [04:56<20:09,  4.62it/s]

Processing tickers:  19%|█▉        | 1345/6932 [04:56<20:12,  4.61it/s]

Processing tickers:  19%|█▉        | 1346/6932 [04:57<20:00,  4.65it/s]

Processing tickers:  19%|█▉        | 1347/6932 [04:57<19:46,  4.71it/s]

Processing tickers:  19%|█▉        | 1348/6932 [04:57<20:07,  4.62it/s]

Processing tickers:  19%|█▉        | 1349/6932 [04:57<19:51,  4.68it/s]

Processing tickers:  19%|█▉        | 1350/6932 [04:57<19:46,  4.70it/s]

Processing tickers:  19%|█▉        | 1351/6932 [04:58<19:39,  4.73it/s]

Processing tickers:  20%|█▉        | 1352/6932 [04:58<19:30,  4.77it/s]

Processing tickers:  20%|█▉        | 1353/6932 [04:58<19:40,  4.72it/s]

Processing tickers:  20%|█▉        | 1354/6932 [04:58<19:47,  4.70it/s]

Processing tickers:  20%|█▉        | 1355/6932 [04:59<19:39,  4.73it/s]

Processing tickers:  20%|█▉        | 1356/6932 [04:59<20:46,  4.47it/s]

Processing tickers:  20%|█▉        | 1357/6932 [04:59<20:15,  4.59it/s]

Processing tickers:  20%|█▉        | 1358/6932 [04:59<20:03,  4.63it/s]

Processing tickers:  20%|█▉        | 1359/6932 [04:59<20:00,  4.64it/s]

Processing tickers:  20%|█▉        | 1360/6932 [05:00<19:45,  4.70it/s]

Processing tickers:  20%|█▉        | 1361/6932 [05:00<19:36,  4.73it/s]

Processing tickers:  20%|█▉        | 1362/6932 [05:00<19:45,  4.70it/s]

Processing tickers:  20%|█▉        | 1363/6932 [05:00<19:27,  4.77it/s]

Processing tickers:  20%|█▉        | 1364/6932 [05:00<19:23,  4.79it/s]

Processing tickers:  20%|█▉        | 1365/6932 [05:01<19:46,  4.69it/s]

Processing tickers:  20%|█▉        | 1366/6932 [05:01<19:09,  4.84it/s]

Processing tickers:  20%|█▉        | 1367/6932 [05:01<19:36,  4.73it/s]

Processing tickers:  20%|█▉        | 1368/6932 [05:01<19:29,  4.76it/s]

Processing tickers:  20%|█▉        | 1369/6932 [05:02<19:32,  4.74it/s]

Processing tickers:  20%|█▉        | 1370/6932 [05:02<20:08,  4.60it/s]

Processing tickers:  20%|█▉        | 1371/6932 [05:02<19:37,  4.72it/s]

Processing tickers:  20%|█▉        | 1372/6932 [05:02<19:50,  4.67it/s]

Processing tickers:  20%|█▉        | 1373/6932 [05:02<20:04,  4.62it/s]

Processing tickers:  20%|█▉        | 1374/6932 [05:03<19:48,  4.67it/s]

Processing tickers:  20%|█▉        | 1375/6932 [05:03<20:00,  4.63it/s]

Processing tickers:  20%|█▉        | 1376/6932 [05:03<19:55,  4.65it/s]

Processing tickers:  20%|█▉        | 1377/6932 [05:03<19:47,  4.68it/s]

Processing tickers:  20%|█▉        | 1378/6932 [05:03<19:48,  4.67it/s]

Processing tickers:  20%|█▉        | 1379/6932 [05:04<20:15,  4.57it/s]

Processing tickers:  20%|█▉        | 1380/6932 [05:04<20:18,  4.56it/s]

Processing tickers:  20%|█▉        | 1381/6932 [05:04<19:59,  4.63it/s]

Processing tickers:  20%|█▉        | 1382/6932 [05:04<19:45,  4.68it/s]

Processing tickers:  20%|█▉        | 1383/6932 [05:05<20:02,  4.61it/s]

Processing tickers:  20%|█▉        | 1384/6932 [05:05<20:14,  4.57it/s]

Processing tickers:  20%|█▉        | 1385/6932 [05:05<19:55,  4.64it/s]

Processing tickers:  20%|█▉        | 1386/6932 [05:05<19:43,  4.69it/s]

Processing tickers:  20%|██        | 1387/6932 [05:05<19:35,  4.72it/s]

Processing tickers:  20%|██        | 1388/6932 [05:06<19:44,  4.68it/s]

Processing tickers:  20%|██        | 1389/6932 [05:06<19:31,  4.73it/s]

Processing tickers:  20%|██        | 1390/6932 [05:06<19:43,  4.68it/s]

Processing tickers:  20%|██        | 1391/6932 [05:06<19:31,  4.73it/s]

Processing tickers:  20%|██        | 1392/6932 [05:06<19:24,  4.76it/s]

Processing tickers:  20%|██        | 1393/6932 [05:07<19:45,  4.67it/s]

Processing tickers:  20%|██        | 1394/6932 [05:07<19:35,  4.71it/s]

Processing tickers:  20%|██        | 1395/6932 [05:07<19:28,  4.74it/s]

Processing tickers:  20%|██        | 1396/6932 [05:07<19:26,  4.75it/s]

Processing tickers:  20%|██        | 1397/6932 [05:08<19:29,  4.73it/s]

Processing tickers:  20%|██        | 1398/6932 [05:08<19:12,  4.80it/s]

Processing tickers:  20%|██        | 1399/6932 [05:08<19:12,  4.80it/s]

Processing tickers:  20%|██        | 1400/6932 [05:08<19:11,  4.81it/s]

Processing tickers:  20%|██        | 1401/6932 [05:08<19:11,  4.80it/s]

Processing tickers:  20%|██        | 1402/6932 [05:09<19:12,  4.80it/s]

Processing tickers:  20%|██        | 1403/6932 [05:09<19:39,  4.69it/s]

Processing tickers:  20%|██        | 1404/6932 [05:09<19:33,  4.71it/s]

Processing tickers:  20%|██        | 1405/6932 [05:09<19:31,  4.72it/s]

Processing tickers:  20%|██        | 1406/6932 [05:09<19:13,  4.79it/s]

Processing tickers:  20%|██        | 1407/6932 [05:10<19:13,  4.79it/s]

Processing tickers:  20%|██        | 1408/6932 [05:10<19:12,  4.79it/s]

Processing tickers:  20%|██        | 1409/6932 [05:10<19:33,  4.71it/s]

Processing tickers:  20%|██        | 1410/6932 [05:10<19:05,  4.82it/s]

Processing tickers:  20%|██        | 1411/6932 [05:10<19:32,  4.71it/s]

Processing tickers:  20%|██        | 1412/6932 [05:11<19:28,  4.72it/s]

Processing tickers:  20%|██        | 1413/6932 [05:11<19:10,  4.80it/s]

Processing tickers:  20%|██        | 1414/6932 [05:11<19:29,  4.72it/s]

Processing tickers:  20%|██        | 1415/6932 [05:11<19:02,  4.83it/s]

Processing tickers:  20%|██        | 1416/6932 [05:11<19:26,  4.73it/s]

Processing tickers:  20%|██        | 1417/6932 [05:12<19:53,  4.62it/s]

Processing tickers:  20%|██        | 1418/6932 [05:12<20:04,  4.58it/s]

Processing tickers:  20%|██        | 1419/6932 [05:12<19:42,  4.66it/s]

Processing tickers:  20%|██        | 1420/6932 [05:12<19:57,  4.60it/s]

Processing tickers:  20%|██        | 1421/6932 [05:13<19:43,  4.66it/s]

Processing tickers:  21%|██        | 1422/6932 [05:13<19:31,  4.70it/s]

Processing tickers:  21%|██        | 1423/6932 [05:13<19:22,  4.74it/s]

Processing tickers:  21%|██        | 1424/6932 [05:13<19:18,  4.75it/s]

Processing tickers:  21%|██        | 1425/6932 [05:13<19:15,  4.77it/s]

Processing tickers:  21%|██        | 1426/6932 [05:14<19:12,  4.78it/s]

Processing tickers:  21%|██        | 1427/6932 [05:14<19:11,  4.78it/s]

Processing tickers:  21%|██        | 1428/6932 [05:14<19:08,  4.79it/s]

Processing tickers:  21%|██        | 1429/6932 [05:14<19:31,  4.70it/s]

Processing tickers:  21%|██        | 1430/6932 [05:14<18:56,  4.84it/s]

Processing tickers:  21%|██        | 1431/6932 [05:15<18:59,  4.83it/s]

Processing tickers:  21%|██        | 1432/6932 [05:15<19:00,  4.82it/s]

Processing tickers:  21%|██        | 1433/6932 [05:15<19:28,  4.71it/s]

Processing tickers:  21%|██        | 1434/6932 [05:15<19:31,  4.69it/s]

Processing tickers:  21%|██        | 1435/6932 [05:16<19:13,  4.77it/s]

Processing tickers:  21%|██        | 1436/6932 [05:16<19:45,  4.64it/s]

Processing tickers:  21%|██        | 1437/6932 [05:16<19:56,  4.59it/s]

Processing tickers:  21%|██        | 1438/6932 [05:16<19:32,  4.69it/s]

Processing tickers:  21%|██        | 1439/6932 [05:16<19:57,  4.59it/s]

Processing tickers:  21%|██        | 1440/6932 [05:17<19:34,  4.68it/s]

Processing tickers:  21%|██        | 1441/6932 [05:17<19:24,  4.72it/s]

Processing tickers:  21%|██        | 1442/6932 [05:17<19:43,  4.64it/s]

Processing tickers:  21%|██        | 1443/6932 [05:17<19:30,  4.69it/s]

Processing tickers:  21%|██        | 1444/6932 [05:17<19:23,  4.72it/s]

Processing tickers:  21%|██        | 1445/6932 [05:18<19:35,  4.67it/s]

Processing tickers:  21%|██        | 1446/6932 [05:18<19:08,  4.78it/s]

Processing tickers:  21%|██        | 1447/6932 [05:18<19:32,  4.68it/s]

Processing tickers:  21%|██        | 1448/6932 [05:18<19:22,  4.72it/s]

Processing tickers:  21%|██        | 1449/6932 [05:19<19:15,  4.74it/s]

Processing tickers:  21%|██        | 1450/6932 [05:19<20:03,  4.55it/s]

Processing tickers:  21%|██        | 1451/6932 [05:19<19:44,  4.63it/s]

Processing tickers:  21%|██        | 1452/6932 [05:19<20:02,  4.56it/s]

Processing tickers:  21%|██        | 1453/6932 [05:19<19:35,  4.66it/s]

Processing tickers:  21%|██        | 1454/6932 [05:20<19:42,  4.63it/s]

Processing tickers:  21%|██        | 1455/6932 [05:20<19:40,  4.64it/s]

Processing tickers:  21%|██        | 1456/6932 [05:20<19:02,  4.79it/s]

Processing tickers:  21%|██        | 1457/6932 [05:20<19:27,  4.69it/s]

Processing tickers:  21%|██        | 1458/6932 [05:20<18:53,  4.83it/s]

Processing tickers:  21%|██        | 1459/6932 [05:21<18:54,  4.82it/s]

Processing tickers:  21%|██        | 1460/6932 [05:21<18:55,  4.82it/s]

Processing tickers:  21%|██        | 1461/6932 [05:21<18:58,  4.81it/s]

Processing tickers:  21%|██        | 1462/6932 [05:21<19:03,  4.78it/s]

Processing tickers:  21%|██        | 1463/6932 [05:21<18:55,  4.82it/s]

Processing tickers:  21%|██        | 1464/6932 [05:22<18:58,  4.80it/s]

Processing tickers:  21%|██        | 1465/6932 [05:22<18:28,  4.93it/s]

Processing tickers:  21%|██        | 1466/6932 [05:22<19:02,  4.78it/s]

Processing tickers:  21%|██        | 1467/6932 [05:22<19:01,  4.79it/s]

Processing tickers:  21%|██        | 1468/6932 [05:23<18:59,  4.79it/s]

Processing tickers:  21%|██        | 1469/6932 [05:23<19:32,  4.66it/s]

Processing tickers:  21%|██        | 1470/6932 [05:23<19:58,  4.56it/s]

Processing tickers:  21%|██        | 1471/6932 [05:23<19:48,  4.59it/s]

Processing tickers:  21%|██        | 1472/6932 [05:23<19:31,  4.66it/s]

Processing tickers:  21%|██        | 1473/6932 [05:24<19:17,  4.72it/s]

Processing tickers:  21%|██▏       | 1474/6932 [05:24<19:34,  4.65it/s]

Processing tickers:  21%|██▏       | 1475/6932 [05:24<19:54,  4.57it/s]

Processing tickers:  21%|██▏       | 1476/6932 [05:24<19:59,  4.55it/s]

Processing tickers:  21%|██▏       | 1477/6932 [05:24<20:00,  4.55it/s]

Processing tickers:  21%|██▏       | 1478/6932 [05:25<19:48,  4.59it/s]

Processing tickers:  21%|██▏       | 1479/6932 [05:25<20:16,  4.48it/s]

Processing tickers:  21%|██▏       | 1480/6932 [05:25<20:17,  4.48it/s]

Processing tickers:  21%|██▏       | 1481/6932 [05:25<19:51,  4.57it/s]

Processing tickers:  21%|██▏       | 1482/6932 [05:26<20:00,  4.54it/s]

Processing tickers:  21%|██▏       | 1483/6932 [05:26<19:44,  4.60it/s]

Processing tickers:  21%|██▏       | 1484/6932 [05:26<19:43,  4.60it/s]

Processing tickers:  21%|██▏       | 1485/6932 [05:26<19:10,  4.73it/s]

Processing tickers:  21%|██▏       | 1486/6932 [05:26<19:04,  4.76it/s]

Processing tickers:  21%|██▏       | 1487/6932 [05:27<19:26,  4.67it/s]

Processing tickers:  21%|██▏       | 1488/6932 [05:27<18:50,  4.82it/s]

Processing tickers:  21%|██▏       | 1489/6932 [05:27<19:42,  4.60it/s]

Processing tickers:  21%|██▏       | 1490/6932 [05:27<19:27,  4.66it/s]

Processing tickers:  22%|██▏       | 1491/6932 [05:27<19:15,  4.71it/s]

Processing tickers:  22%|██▏       | 1492/6932 [05:28<19:07,  4.74it/s]

Processing tickers:  22%|██▏       | 1493/6932 [05:28<19:21,  4.68it/s]

Processing tickers:  22%|██▏       | 1494/6932 [05:28<18:53,  4.80it/s]

Processing tickers:  22%|██▏       | 1495/6932 [05:28<18:53,  4.80it/s]

Processing tickers:  22%|██▏       | 1496/6932 [05:29<18:52,  4.80it/s]

Processing tickers:  22%|██▏       | 1497/6932 [05:29<19:17,  4.69it/s]

Processing tickers:  22%|██▏       | 1498/6932 [05:29<19:08,  4.73it/s]

Processing tickers:  22%|██▏       | 1499/6932 [05:29<19:02,  4.75it/s]

Processing tickers:  22%|██▏       | 1500/6932 [05:29<19:19,  4.69it/s]

Processing tickers:  22%|██▏       | 1501/6932 [05:30<18:50,  4.80it/s]

Processing tickers:  22%|██▏       | 1502/6932 [05:30<19:17,  4.69it/s]

Processing tickers:  22%|██▏       | 1503/6932 [05:30<19:08,  4.73it/s]

Processing tickers:  22%|██▏       | 1504/6932 [05:30<19:02,  4.75it/s]

Processing tickers:  22%|██▏       | 1505/6932 [05:30<18:58,  4.77it/s]

Processing tickers:  22%|██▏       | 1506/6932 [05:31<18:54,  4.78it/s]

Processing tickers:  22%|██▏       | 1507/6932 [05:31<18:52,  4.79it/s]

Processing tickers:  22%|██▏       | 1508/6932 [05:31<18:50,  4.80it/s]

Processing tickers:  22%|██▏       | 1509/6932 [05:31<18:48,  4.81it/s]

Processing tickers:  22%|██▏       | 1510/6932 [05:31<18:52,  4.79it/s]

Processing tickers:  22%|██▏       | 1511/6932 [05:32<18:58,  4.76it/s]

Processing tickers:  22%|██▏       | 1512/6932 [05:32<18:42,  4.83it/s]

Processing tickers:  22%|██▏       | 1513/6932 [05:32<18:44,  4.82it/s]

Processing tickers:  22%|██▏       | 1514/6932 [05:32<18:46,  4.81it/s]

Processing tickers:  22%|██▏       | 1515/6932 [05:33<18:45,  4.81it/s]

Processing tickers:  22%|██▏       | 1516/6932 [05:33<19:10,  4.71it/s]

Processing tickers:  22%|██▏       | 1517/6932 [05:33<19:27,  4.64it/s]

Processing tickers:  22%|██▏       | 1518/6932 [05:33<19:40,  4.59it/s]

Processing tickers:  22%|██▏       | 1519/6932 [05:33<19:23,  4.65it/s]

Processing tickers:  22%|██▏       | 1520/6932 [05:34<19:41,  4.58it/s]

Processing tickers:  22%|██▏       | 1521/6932 [05:34<19:21,  4.66it/s]

Processing tickers:  22%|██▏       | 1522/6932 [05:34<19:18,  4.67it/s]

Processing tickers:  22%|██▏       | 1523/6932 [05:34<19:21,  4.66it/s]

Processing tickers:  22%|██▏       | 1524/6932 [05:34<19:26,  4.63it/s]

Processing tickers:  22%|██▏       | 1525/6932 [05:35<19:35,  4.60it/s]

Processing tickers:  22%|██▏       | 1526/6932 [05:35<19:12,  4.69it/s]

Processing tickers:  22%|██▏       | 1527/6932 [05:35<19:23,  4.64it/s]

Processing tickers:  22%|██▏       | 1528/6932 [05:35<19:20,  4.66it/s]

Processing tickers:  22%|██▏       | 1529/6932 [05:36<19:09,  4.70it/s]

Processing tickers:  22%|██▏       | 1530/6932 [05:36<19:25,  4.63it/s]

Processing tickers:  22%|██▏       | 1531/6932 [05:36<19:12,  4.69it/s]

Processing tickers:  22%|██▏       | 1532/6932 [05:36<19:04,  4.72it/s]

Processing tickers:  22%|██▏       | 1533/6932 [05:36<19:21,  4.65it/s]

Processing tickers:  22%|██▏       | 1534/6932 [05:37<18:46,  4.79it/s]

Processing tickers:  22%|██▏       | 1535/6932 [05:37<18:50,  4.77it/s]

Processing tickers:  22%|██▏       | 1536/6932 [05:37<19:07,  4.70it/s]

Processing tickers:  22%|██▏       | 1537/6932 [05:37<19:00,  4.73it/s]

Processing tickers:  22%|██▏       | 1538/6932 [05:38<22:25,  4.01it/s]

Processing tickers:  22%|██▏       | 1539/6932 [05:38<21:41,  4.14it/s]

Processing tickers:  22%|██▏       | 1540/6932 [05:38<20:44,  4.33it/s]

Processing tickers:  22%|██▏       | 1541/6932 [05:38<20:07,  4.47it/s]

Processing tickers:  22%|██▏       | 1542/6932 [05:38<20:07,  4.46it/s]

Processing tickers:  22%|██▏       | 1543/6932 [05:39<19:41,  4.56it/s]

Processing tickers:  22%|██▏       | 1544/6932 [05:39<18:56,  4.74it/s]

Processing tickers:  22%|██▏       | 1545/6932 [05:39<24:01,  3.74it/s]

Processing tickers:  22%|██▏       | 1546/6932 [05:39<22:43,  3.95it/s]

Processing tickers:  22%|██▏       | 1547/6932 [05:40<21:38,  4.15it/s]

Processing tickers:  22%|██▏       | 1548/6932 [05:40<20:48,  4.31it/s]

Processing tickers:  22%|██▏       | 1549/6932 [05:40<20:04,  4.47it/s]

Processing tickers:  22%|██▏       | 1550/6932 [05:40<20:05,  4.46it/s]

Processing tickers:  22%|██▏       | 1551/6932 [05:41<20:03,  4.47it/s]

Processing tickers:  22%|██▏       | 1552/6932 [05:41<19:55,  4.50it/s]

Processing tickers:  22%|██▏       | 1553/6932 [05:41<19:42,  4.55it/s]

Processing tickers:  22%|██▏       | 1554/6932 [05:41<19:23,  4.62it/s]

Processing tickers:  22%|██▏       | 1555/6932 [05:41<19:08,  4.68it/s]

Processing tickers:  22%|██▏       | 1556/6932 [05:42<18:57,  4.72it/s]

Processing tickers:  22%|██▏       | 1557/6932 [05:42<18:51,  4.75it/s]

Processing tickers:  22%|██▏       | 1558/6932 [05:42<19:07,  4.68it/s]

Processing tickers:  22%|██▏       | 1559/6932 [05:42<18:57,  4.72it/s]

Processing tickers:  23%|██▎       | 1560/6932 [05:42<20:46,  4.31it/s]

Processing tickers:  23%|██▎       | 1561/6932 [05:43<20:00,  4.47it/s]

Processing tickers:  23%|██▎       | 1562/6932 [05:43<19:52,  4.50it/s]

Processing tickers:  23%|██▎       | 1563/6932 [05:43<20:03,  4.46it/s]

Processing tickers:  23%|██▎       | 1564/6932 [05:43<19:31,  4.58it/s]

Processing tickers:  23%|██▎       | 1565/6932 [05:44<23:48,  3.76it/s]

Processing tickers:  23%|██▎       | 1566/6932 [05:44<21:58,  4.07it/s]

Processing tickers:  23%|██▎       | 1567/6932 [05:44<21:29,  4.16it/s]

Processing tickers:  23%|██▎       | 1568/6932 [05:44<20:32,  4.35it/s]

Processing tickers:  23%|██▎       | 1569/6932 [05:45<19:59,  4.47it/s]

Processing tickers:  23%|██▎       | 1570/6932 [05:45<19:56,  4.48it/s]

Processing tickers:  23%|██▎       | 1571/6932 [05:45<19:43,  4.53it/s]

Processing tickers:  23%|██▎       | 1572/6932 [05:45<19:21,  4.61it/s]

Processing tickers:  23%|██▎       | 1573/6932 [05:45<19:20,  4.62it/s]

Processing tickers:  23%|██▎       | 1574/6932 [05:46<19:06,  4.67it/s]

Processing tickers:  23%|██▎       | 1575/6932 [05:46<18:58,  4.71it/s]

Processing tickers:  23%|██▎       | 1576/6932 [05:46<18:52,  4.73it/s]

Processing tickers:  23%|██▎       | 1577/6932 [05:46<19:11,  4.65it/s]

Processing tickers:  23%|██▎       | 1578/6932 [05:47<19:28,  4.58it/s]

Processing tickers:  23%|██▎       | 1579/6932 [05:47<19:07,  4.66it/s]

Processing tickers:  23%|██▎       | 1580/6932 [05:47<19:09,  4.65it/s]

Processing tickers:  23%|██▎       | 1581/6932 [05:47<19:02,  4.68it/s]

Processing tickers:  23%|██▎       | 1582/6932 [05:47<19:16,  4.63it/s]

Processing tickers:  23%|██▎       | 1583/6932 [05:48<18:53,  4.72it/s]

Processing tickers:  23%|██▎       | 1584/6932 [05:48<18:43,  4.76it/s]

Processing tickers:  23%|██▎       | 1585/6932 [05:48<18:41,  4.77it/s]

Processing tickers:  23%|██▎       | 1586/6932 [05:48<19:30,  4.57it/s]

Processing tickers:  23%|██▎       | 1587/6932 [05:48<19:13,  4.63it/s]

Processing tickers:  23%|██▎       | 1588/6932 [05:49<19:03,  4.67it/s]

Processing tickers:  23%|██▎       | 1589/6932 [05:49<18:50,  4.73it/s]

Processing tickers:  23%|██▎       | 1590/6932 [05:49<18:52,  4.72it/s]

Processing tickers:  23%|██▎       | 1591/6932 [05:49<18:40,  4.76it/s]

Processing tickers:  23%|██▎       | 1592/6932 [05:49<18:34,  4.79it/s]

Processing tickers:  23%|██▎       | 1593/6932 [05:50<18:44,  4.75it/s]

Processing tickers:  23%|██▎       | 1594/6932 [05:50<18:29,  4.81it/s]

Processing tickers:  23%|██▎       | 1595/6932 [05:50<18:29,  4.81it/s]

Processing tickers:  23%|██▎       | 1596/6932 [05:50<18:30,  4.81it/s]

Processing tickers:  23%|██▎       | 1597/6932 [05:51<18:33,  4.79it/s]

Processing tickers:  23%|██▎       | 1598/6932 [05:51<19:01,  4.67it/s]

Processing tickers:  23%|██▎       | 1599/6932 [05:51<18:43,  4.75it/s]

Processing tickers:  23%|██▎       | 1600/6932 [05:51<18:46,  4.73it/s]

Processing tickers:  23%|██▎       | 1601/6932 [05:51<18:58,  4.68it/s]

Processing tickers:  23%|██▎       | 1602/6932 [05:52<19:17,  4.60it/s]

Processing tickers:  23%|██▎       | 1603/6932 [05:52<19:00,  4.67it/s]

Processing tickers:  23%|██▎       | 1604/6932 [05:52<18:53,  4.70it/s]

Processing tickers:  23%|██▎       | 1605/6932 [05:52<18:48,  4.72it/s]

Processing tickers:  23%|██▎       | 1606/6932 [05:52<18:34,  4.78it/s]

Processing tickers:  23%|██▎       | 1607/6932 [05:53<18:45,  4.73it/s]

Processing tickers:  23%|██▎       | 1608/6932 [05:53<18:53,  4.70it/s]

Processing tickers:  23%|██▎       | 1609/6932 [05:53<18:44,  4.73it/s]

Processing tickers:  23%|██▎       | 1610/6932 [05:53<18:59,  4.67it/s]

Processing tickers:  23%|██▎       | 1611/6932 [05:54<19:11,  4.62it/s]

Processing tickers:  23%|██▎       | 1612/6932 [05:54<19:21,  4.58it/s]

Processing tickers:  23%|██▎       | 1613/6932 [05:54<19:47,  4.48it/s]

Processing tickers:  23%|██▎       | 1614/6932 [05:54<19:44,  4.49it/s]

Processing tickers:  23%|██▎       | 1615/6932 [05:54<19:06,  4.64it/s]

Processing tickers:  23%|██▎       | 1616/6932 [05:55<19:07,  4.63it/s]

Processing tickers:  23%|██▎       | 1617/6932 [05:55<18:40,  4.74it/s]

Processing tickers:  23%|██▎       | 1618/6932 [05:55<19:04,  4.64it/s]

Processing tickers:  23%|██▎       | 1619/6932 [05:55<19:04,  4.64it/s]

Processing tickers:  23%|██▎       | 1620/6932 [05:55<18:35,  4.76it/s]

Processing tickers:  23%|██▎       | 1621/6932 [05:56<18:55,  4.68it/s]

Processing tickers:  23%|██▎       | 1622/6932 [05:56<19:05,  4.63it/s]

Processing tickers:  23%|██▎       | 1623/6932 [05:56<19:00,  4.66it/s]

Processing tickers:  23%|██▎       | 1624/6932 [05:56<18:24,  4.80it/s]

Processing tickers:  23%|██▎       | 1625/6932 [05:57<18:45,  4.71it/s]

Processing tickers:  23%|██▎       | 1626/6932 [05:57<18:39,  4.74it/s]

Processing tickers:  23%|██▎       | 1627/6932 [05:57<18:34,  4.76it/s]

Processing tickers:  23%|██▎       | 1628/6932 [05:57<18:56,  4.67it/s]

Processing tickers:  23%|██▎       | 1629/6932 [05:57<19:01,  4.64it/s]

Processing tickers:  24%|██▎       | 1630/6932 [05:58<18:59,  4.65it/s]

Processing tickers:  24%|██▎       | 1631/6932 [05:58<18:47,  4.70it/s]

Processing tickers:  24%|██▎       | 1632/6932 [05:58<18:47,  4.70it/s]

Processing tickers:  24%|██▎       | 1633/6932 [05:58<18:45,  4.71it/s]

Processing tickers:  24%|██▎       | 1634/6932 [05:58<18:24,  4.79it/s]

Processing tickers:  24%|██▎       | 1635/6932 [05:59<18:25,  4.79it/s]

Processing tickers:  24%|██▎       | 1636/6932 [05:59<18:49,  4.69it/s]

Processing tickers:  24%|██▎       | 1637/6932 [05:59<19:31,  4.52it/s]

Processing tickers:  24%|██▎       | 1638/6932 [05:59<19:09,  4.61it/s]

Processing tickers:  24%|██▎       | 1639/6932 [06:00<19:19,  4.57it/s]

Processing tickers:  24%|██▎       | 1640/6932 [06:00<19:26,  4.54it/s]

Processing tickers:  24%|██▎       | 1641/6932 [06:00<19:12,  4.59it/s]

Processing tickers:  24%|██▎       | 1642/6932 [06:00<19:17,  4.57it/s]

Processing tickers:  24%|██▎       | 1643/6932 [06:00<18:59,  4.64it/s]

Processing tickers:  24%|██▎       | 1644/6932 [06:01<19:02,  4.63it/s]

Processing tickers:  24%|██▎       | 1645/6932 [06:01<19:02,  4.63it/s]

Processing tickers:  24%|██▎       | 1646/6932 [06:01<18:49,  4.68it/s]

Processing tickers:  24%|██▍       | 1647/6932 [06:01<18:38,  4.73it/s]

Processing tickers:  24%|██▍       | 1648/6932 [06:01<18:30,  4.76it/s]

Processing tickers:  24%|██▍       | 1649/6932 [06:02<18:23,  4.79it/s]

Processing tickers:  24%|██▍       | 1650/6932 [06:02<18:20,  4.80it/s]

Processing tickers:  24%|██▍       | 1651/6932 [06:02<18:37,  4.73it/s]

Processing tickers:  24%|██▍       | 1652/6932 [06:02<18:42,  4.70it/s]

Processing tickers:  24%|██▍       | 1653/6932 [06:02<18:33,  4.74it/s]

Processing tickers:  24%|██▍       | 1654/6932 [06:03<18:36,  4.73it/s]

Processing tickers:  24%|██▍       | 1655/6932 [06:03<18:37,  4.72it/s]

Processing tickers:  24%|██▍       | 1656/6932 [06:03<18:40,  4.71it/s]

Processing tickers:  24%|██▍       | 1657/6932 [06:03<18:32,  4.74it/s]

Processing tickers:  24%|██▍       | 1658/6932 [06:04<18:51,  4.66it/s]

Processing tickers:  24%|██▍       | 1659/6932 [06:04<19:16,  4.56it/s]

Processing tickers:  24%|██▍       | 1660/6932 [06:04<18:46,  4.68it/s]

Processing tickers:  24%|██▍       | 1661/6932 [06:04<18:45,  4.68it/s]

Processing tickers:  24%|██▍       | 1662/6932 [06:04<18:29,  4.75it/s]

Processing tickers:  24%|██▍       | 1663/6932 [06:05<18:47,  4.67it/s]

Processing tickers:  24%|██▍       | 1664/6932 [06:05<18:26,  4.76it/s]

Processing tickers:  24%|██▍       | 1665/6932 [06:05<18:24,  4.77it/s]

Processing tickers:  24%|██▍       | 1666/6932 [06:05<18:37,  4.71it/s]

Processing tickers:  24%|██▍       | 1667/6932 [06:05<18:14,  4.81it/s]

Processing tickers:  24%|██▍       | 1668/6932 [06:06<18:18,  4.79it/s]

Processing tickers:  24%|██▍       | 1669/6932 [06:06<18:38,  4.70it/s]

Processing tickers:  24%|██▍       | 1670/6932 [06:06<18:31,  4.73it/s]

Processing tickers:  24%|██▍       | 1671/6932 [06:06<18:49,  4.66it/s]

Processing tickers:  24%|██▍       | 1672/6932 [06:07<18:58,  4.62it/s]

Processing tickers:  24%|██▍       | 1673/6932 [06:07<19:14,  4.55it/s]

Processing tickers:  24%|██▍       | 1674/6932 [06:07<18:56,  4.63it/s]

Processing tickers:  24%|██▍       | 1675/6932 [06:07<18:43,  4.68it/s]

Processing tickers:  24%|██▍       | 1676/6932 [06:07<18:35,  4.71it/s]

Processing tickers:  24%|██▍       | 1677/6932 [06:08<18:28,  4.74it/s]

Processing tickers:  24%|██▍       | 1678/6932 [06:08<18:23,  4.76it/s]

Processing tickers:  24%|██▍       | 1679/6932 [06:08<18:42,  4.68it/s]

Processing tickers:  24%|██▍       | 1680/6932 [06:08<18:10,  4.82it/s]

Processing tickers:  24%|██▍       | 1681/6932 [06:08<18:36,  4.70it/s]

Processing tickers:  24%|██▍       | 1682/6932 [06:09<18:37,  4.70it/s]

Processing tickers:  24%|██▍       | 1683/6932 [06:09<18:20,  4.77it/s]

Processing tickers:  24%|██▍       | 1684/6932 [06:09<18:19,  4.78it/s]

Processing tickers:  24%|██▍       | 1685/6932 [06:09<18:37,  4.70it/s]

Processing tickers:  24%|██▍       | 1686/6932 [06:10<18:33,  4.71it/s]

Processing tickers:  24%|██▍       | 1687/6932 [06:10<18:26,  4.74it/s]

Processing tickers:  24%|██▍       | 1688/6932 [06:10<18:48,  4.65it/s]

Processing tickers:  24%|██▍       | 1689/6932 [06:10<18:33,  4.71it/s]

Processing tickers:  24%|██▍       | 1690/6932 [06:10<18:27,  4.73it/s]

Processing tickers:  24%|██▍       | 1691/6932 [06:11<18:21,  4.76it/s]

Processing tickers:  24%|██▍       | 1692/6932 [06:11<18:43,  4.67it/s]

Processing tickers:  24%|██▍       | 1693/6932 [06:11<18:32,  4.71it/s]

Processing tickers:  24%|██▍       | 1694/6932 [06:11<18:31,  4.71it/s]

Processing tickers:  24%|██▍       | 1695/6932 [06:11<18:19,  4.76it/s]

Processing tickers:  24%|██▍       | 1696/6932 [06:12<18:19,  4.76it/s]

Processing tickers:  24%|██▍       | 1697/6932 [06:12<18:12,  4.79it/s]

Processing tickers:  24%|██▍       | 1698/6932 [06:12<18:35,  4.69it/s]

Processing tickers:  25%|██▍       | 1699/6932 [06:12<18:43,  4.66it/s]

Processing tickers:  25%|██▍       | 1700/6932 [06:12<18:17,  4.77it/s]

Processing tickers:  25%|██▍       | 1701/6932 [06:13<18:21,  4.75it/s]

Processing tickers:  25%|██▍       | 1702/6932 [06:13<18:35,  4.69it/s]

Processing tickers:  25%|██▍       | 1703/6932 [06:13<18:28,  4.72it/s]

Processing tickers:  25%|██▍       | 1704/6932 [06:13<18:20,  4.75it/s]

Processing tickers:  25%|██▍       | 1705/6932 [06:14<18:50,  4.62it/s]

Processing tickers:  25%|██▍       | 1706/6932 [06:14<18:54,  4.61it/s]

Processing tickers:  25%|██▍       | 1707/6932 [06:14<19:03,  4.57it/s]

Processing tickers:  25%|██▍       | 1708/6932 [06:14<19:08,  4.55it/s]

Processing tickers:  25%|██▍       | 1709/6932 [06:14<18:26,  4.72it/s]

Processing tickers:  25%|██▍       | 1710/6932 [06:15<18:44,  4.64it/s]

Processing tickers:  25%|██▍       | 1711/6932 [06:15<18:32,  4.69it/s]

Processing tickers:  25%|██▍       | 1712/6932 [06:15<18:34,  4.69it/s]

Processing tickers:  25%|██▍       | 1713/6932 [06:15<18:17,  4.76it/s]

Processing tickers:  25%|██▍       | 1714/6932 [06:15<18:13,  4.77it/s]

Processing tickers:  25%|██▍       | 1715/6932 [06:16<18:36,  4.67it/s]

Processing tickers:  25%|██▍       | 1716/6932 [06:16<18:39,  4.66it/s]

Processing tickers:  25%|██▍       | 1717/6932 [06:16<18:15,  4.76it/s]

Processing tickers:  25%|██▍       | 1718/6932 [06:16<18:36,  4.67it/s]

Processing tickers:  25%|██▍       | 1719/6932 [06:17<18:26,  4.71it/s]

Processing tickers:  25%|██▍       | 1720/6932 [06:17<18:19,  4.74it/s]

Processing tickers:  25%|██▍       | 1721/6932 [06:17<18:40,  4.65it/s]

Processing tickers:  25%|██▍       | 1722/6932 [06:17<18:28,  4.70it/s]

Processing tickers:  25%|██▍       | 1723/6932 [06:17<18:21,  4.73it/s]

Processing tickers:  25%|██▍       | 1724/6932 [06:18<19:05,  4.54it/s]

Processing tickers:  25%|██▍       | 1725/6932 [06:18<18:51,  4.60it/s]

Processing tickers:  25%|██▍       | 1726/6932 [06:18<18:35,  4.67it/s]

Processing tickers:  25%|██▍       | 1727/6932 [06:18<18:28,  4.70it/s]

Processing tickers:  25%|██▍       | 1728/6932 [06:18<18:44,  4.63it/s]

Processing tickers:  25%|██▍       | 1729/6932 [06:19<18:32,  4.68it/s]

Processing tickers:  25%|██▍       | 1730/6932 [06:19<18:19,  4.73it/s]

Processing tickers:  25%|██▍       | 1731/6932 [06:19<18:37,  4.65it/s]

Processing tickers:  25%|██▍       | 1732/6932 [06:19<18:28,  4.69it/s]

Processing tickers:  25%|██▌       | 1733/6932 [06:20<18:19,  4.73it/s]

Processing tickers:  25%|██▌       | 1734/6932 [06:20<18:40,  4.64it/s]

Processing tickers:  25%|██▌       | 1735/6932 [06:20<18:28,  4.69it/s]

Processing tickers:  25%|██▌       | 1736/6932 [06:20<18:20,  4.72it/s]

Processing tickers:  25%|██▌       | 1737/6932 [06:20<18:14,  4.74it/s]

Processing tickers:  25%|██▌       | 1738/6932 [06:21<18:37,  4.65it/s]

Processing tickers:  25%|██▌       | 1739/6932 [06:21<18:30,  4.68it/s]

Processing tickers:  25%|██▌       | 1740/6932 [06:21<18:16,  4.74it/s]

Processing tickers:  25%|██▌       | 1741/6932 [06:21<18:12,  4.75it/s]

Processing tickers:  25%|██▌       | 1742/6932 [06:21<18:22,  4.71it/s]

Processing tickers:  25%|██▌       | 1743/6932 [06:22<18:03,  4.79it/s]

Processing tickers:  25%|██▌       | 1744/6932 [06:22<18:00,  4.80it/s]

Processing tickers:  25%|██▌       | 1745/6932 [06:22<17:59,  4.81it/s]

Processing tickers:  25%|██▌       | 1746/6932 [06:22<17:59,  4.81it/s]

Processing tickers:  25%|██▌       | 1747/6932 [06:22<18:03,  4.79it/s]

Processing tickers:  25%|██▌       | 1748/6932 [06:23<18:23,  4.70it/s]

Processing tickers:  25%|██▌       | 1749/6932 [06:23<18:13,  4.74it/s]

Processing tickers:  25%|██▌       | 1750/6932 [06:23<18:31,  4.66it/s]

Processing tickers:  25%|██▌       | 1751/6932 [06:23<18:43,  4.61it/s]

Processing tickers:  25%|██▌       | 1752/6932 [06:24<19:08,  4.51it/s]

Processing tickers:  25%|██▌       | 1753/6932 [06:24<18:32,  4.65it/s]

Processing tickers:  25%|██▌       | 1754/6932 [06:24<18:52,  4.57it/s]

Processing tickers:  25%|██▌       | 1755/6932 [06:24<18:28,  4.67it/s]

Processing tickers:  25%|██▌       | 1756/6932 [06:24<18:17,  4.71it/s]

Processing tickers:  25%|██▌       | 1757/6932 [06:25<18:36,  4.64it/s]

Processing tickers:  25%|██▌       | 1758/6932 [06:25<18:24,  4.68it/s]

Processing tickers:  25%|██▌       | 1759/6932 [06:25<18:14,  4.72it/s]

Processing tickers:  25%|██▌       | 1760/6932 [06:25<18:09,  4.75it/s]

Processing tickers:  25%|██▌       | 1761/6932 [06:25<18:29,  4.66it/s]

Processing tickers:  25%|██▌       | 1762/6932 [06:26<18:18,  4.71it/s]

Processing tickers:  25%|██▌       | 1763/6932 [06:26<18:12,  4.73it/s]

Processing tickers:  25%|██▌       | 1764/6932 [06:26<18:06,  4.76it/s]

Processing tickers:  25%|██▌       | 1765/6932 [06:26<18:19,  4.70it/s]

Processing tickers:  25%|██▌       | 1766/6932 [06:27<17:55,  4.80it/s]

Processing tickers:  25%|██▌       | 1767/6932 [06:27<18:41,  4.61it/s]

Processing tickers:  26%|██▌       | 1768/6932 [06:27<18:33,  4.64it/s]

Processing tickers:  26%|██▌       | 1769/6932 [06:27<18:21,  4.69it/s]

Processing tickers:  26%|██▌       | 1770/6932 [06:27<18:13,  4.72it/s]

Processing tickers:  26%|██▌       | 1771/6932 [06:28<18:08,  4.74it/s]

Processing tickers:  26%|██▌       | 1772/6932 [06:28<18:05,  4.76it/s]

Processing tickers:  26%|██▌       | 1773/6932 [06:28<18:32,  4.64it/s]

Processing tickers:  26%|██▌       | 1774/6932 [06:28<18:14,  4.71it/s]

Processing tickers:  26%|██▌       | 1775/6932 [06:28<18:24,  4.67it/s]

Processing tickers:  26%|██▌       | 1776/6932 [06:29<17:59,  4.78it/s]

Processing tickers:  26%|██▌       | 1777/6932 [06:29<18:21,  4.68it/s]

Processing tickers:  26%|██▌       | 1778/6932 [06:29<18:21,  4.68it/s]

Processing tickers:  26%|██▌       | 1779/6932 [06:29<18:02,  4.76it/s]

Processing tickers:  26%|██▌       | 1780/6932 [06:30<18:00,  4.77it/s]

Processing tickers:  26%|██▌       | 1781/6932 [06:30<18:23,  4.67it/s]

Processing tickers:  26%|██▌       | 1782/6932 [06:30<18:13,  4.71it/s]

Processing tickers:  26%|██▌       | 1783/6932 [06:30<18:30,  4.64it/s]

Processing tickers:  26%|██▌       | 1784/6932 [06:30<18:19,  4.68it/s]

Processing tickers:  26%|██▌       | 1785/6932 [06:31<18:23,  4.66it/s]

Processing tickers:  26%|██▌       | 1786/6932 [06:31<18:22,  4.67it/s]

Processing tickers:  26%|██▌       | 1787/6932 [06:31<18:12,  4.71it/s]

Processing tickers:  26%|██▌       | 1788/6932 [06:31<18:04,  4.74it/s]

Processing tickers:  26%|██▌       | 1789/6932 [06:31<17:58,  4.77it/s]

Processing tickers:  26%|██▌       | 1790/6932 [06:32<17:54,  4.78it/s]

Processing tickers:  26%|██▌       | 1791/6932 [06:32<17:53,  4.79it/s]

Processing tickers:  26%|██▌       | 1792/6932 [06:32<18:16,  4.69it/s]

Processing tickers:  26%|██▌       | 1793/6932 [06:32<18:06,  4.73it/s]

Processing tickers:  26%|██▌       | 1794/6932 [06:32<18:01,  4.75it/s]

Processing tickers:  26%|██▌       | 1795/6932 [06:33<18:22,  4.66it/s]

Processing tickers:  26%|██▌       | 1796/6932 [06:33<18:14,  4.69it/s]

Processing tickers:  26%|██▌       | 1797/6932 [06:33<18:04,  4.74it/s]

Processing tickers:  26%|██▌       | 1798/6932 [06:33<17:56,  4.77it/s]

Processing tickers:  26%|██▌       | 1799/6932 [06:34<18:17,  4.68it/s]

Processing tickers:  26%|██▌       | 1800/6932 [06:34<18:14,  4.69it/s]

Processing tickers:  26%|██▌       | 1801/6932 [06:34<18:00,  4.75it/s]

Processing tickers:  26%|██▌       | 1802/6932 [06:34<17:56,  4.77it/s]

Processing tickers:  26%|██▌       | 1803/6932 [06:34<18:19,  4.67it/s]

Processing tickers:  26%|██▌       | 1804/6932 [06:35<18:09,  4.71it/s]

Processing tickers:  26%|██▌       | 1805/6932 [06:35<18:02,  4.74it/s]

Processing tickers:  26%|██▌       | 1806/6932 [06:35<17:56,  4.76it/s]

Processing tickers:  26%|██▌       | 1807/6932 [06:35<17:52,  4.78it/s]

Processing tickers:  26%|██▌       | 1808/6932 [06:35<17:50,  4.79it/s]

Processing tickers:  26%|██▌       | 1809/6932 [06:36<17:55,  4.76it/s]

Processing tickers:  26%|██▌       | 1810/6932 [06:36<17:46,  4.80it/s]

Processing tickers:  26%|██▌       | 1811/6932 [06:36<17:59,  4.74it/s]

Processing tickers:  26%|██▌       | 1812/6932 [06:36<18:07,  4.71it/s]

Processing tickers:  26%|██▌       | 1813/6932 [06:36<18:00,  4.74it/s]

Processing tickers:  26%|██▌       | 1814/6932 [06:37<17:55,  4.76it/s]

Processing tickers:  26%|██▌       | 1815/6932 [06:37<18:16,  4.67it/s]

Processing tickers:  26%|██▌       | 1816/6932 [06:37<18:07,  4.70it/s]

Processing tickers:  26%|██▌       | 1817/6932 [06:37<18:01,  4.73it/s]

Processing tickers:  26%|██▌       | 1818/6932 [06:38<17:57,  4.75it/s]

Processing tickers:  26%|██▌       | 1819/6932 [06:38<18:17,  4.66it/s]

Processing tickers:  26%|██▋       | 1820/6932 [06:38<24:26,  3.49it/s]

Processing tickers:  26%|██▋       | 1821/6932 [06:38<22:14,  3.83it/s]

Processing tickers:  26%|██▋       | 1822/6932 [06:39<21:08,  4.03it/s]

Processing tickers:  26%|██▋       | 1823/6932 [06:39<20:40,  4.12it/s]

Processing tickers:  26%|██▋       | 1824/6932 [06:39<19:46,  4.30it/s]

Processing tickers:  26%|██▋       | 1825/6932 [06:39<19:09,  4.44it/s]

Processing tickers:  26%|██▋       | 1826/6932 [06:40<19:03,  4.46it/s]

Processing tickers:  26%|██▋       | 1827/6932 [06:40<19:09,  4.44it/s]

Processing tickers:  26%|██▋       | 1828/6932 [06:40<18:41,  4.55it/s]

Processing tickers:  26%|██▋       | 1829/6932 [06:40<18:23,  4.62it/s]

Processing tickers:  26%|██▋       | 1830/6932 [06:40<18:30,  4.59it/s]

Processing tickers:  26%|██▋       | 1831/6932 [06:41<17:55,  4.74it/s]

Processing tickers:  26%|██▋       | 1832/6932 [06:41<17:51,  4.76it/s]

Processing tickers:  26%|██▋       | 1833/6932 [06:41<18:13,  4.66it/s]

Processing tickers:  26%|██▋       | 1834/6932 [06:41<18:05,  4.70it/s]

Processing tickers:  26%|██▋       | 1835/6932 [06:41<17:54,  4.74it/s]

Processing tickers:  26%|██▋       | 1836/6932 [06:42<17:50,  4.76it/s]

Processing tickers:  27%|██▋       | 1837/6932 [06:42<17:25,  4.87it/s]

Processing tickers:  27%|██▋       | 1838/6932 [06:42<17:53,  4.74it/s]

Processing tickers:  27%|██▋       | 1839/6932 [06:42<18:12,  4.66it/s]

Processing tickers:  27%|██▋       | 1840/6932 [06:42<18:00,  4.71it/s]

Processing tickers:  27%|██▋       | 1841/6932 [06:43<18:24,  4.61it/s]

Processing tickers:  27%|██▋       | 1842/6932 [06:43<18:04,  4.70it/s]

Processing tickers:  27%|██▋       | 1843/6932 [06:43<17:57,  4.72it/s]

Processing tickers:  27%|██▋       | 1844/6932 [06:43<17:55,  4.73it/s]

Processing tickers:  27%|██▋       | 1845/6932 [06:44<17:44,  4.78it/s]

Processing tickers:  27%|██▋       | 1846/6932 [06:44<17:43,  4.78it/s]

Processing tickers:  27%|██▋       | 1847/6932 [06:44<18:06,  4.68it/s]

Processing tickers:  27%|██▋       | 1848/6932 [06:44<18:22,  4.61it/s]

Processing tickers:  27%|██▋       | 1849/6932 [06:44<18:09,  4.67it/s]

Processing tickers:  27%|██▋       | 1850/6932 [06:45<18:13,  4.65it/s]

Processing tickers:  27%|██▋       | 1851/6932 [06:45<18:14,  4.64it/s]

Processing tickers:  27%|██▋       | 1852/6932 [06:45<18:04,  4.69it/s]

Processing tickers:  27%|██▋       | 1853/6932 [06:45<18:32,  4.56it/s]

Processing tickers:  27%|██▋       | 1854/6932 [06:45<18:23,  4.60it/s]

Processing tickers:  27%|██▋       | 1855/6932 [06:46<18:13,  4.64it/s]

Processing tickers:  27%|██▋       | 1856/6932 [06:46<18:09,  4.66it/s]

Processing tickers:  27%|██▋       | 1857/6932 [06:46<17:46,  4.76it/s]

Processing tickers:  27%|██▋       | 1858/6932 [06:46<18:30,  4.57it/s]

Processing tickers:  27%|██▋       | 1859/6932 [06:47<18:22,  4.60it/s]

Processing tickers:  27%|██▋       | 1860/6932 [06:47<18:00,  4.70it/s]

Processing tickers:  27%|██▋       | 1861/6932 [06:47<17:53,  4.73it/s]

Processing tickers:  27%|██▋       | 1862/6932 [06:47<18:18,  4.62it/s]

Processing tickers:  27%|██▋       | 1863/6932 [06:47<18:22,  4.60it/s]

Processing tickers:  27%|██▋       | 1864/6932 [06:48<18:06,  4.67it/s]

Processing tickers:  27%|██▋       | 1865/6932 [06:48<17:55,  4.71it/s]

Processing tickers:  27%|██▋       | 1866/6932 [06:48<17:49,  4.74it/s]

Processing tickers:  27%|██▋       | 1867/6932 [06:48<17:57,  4.70it/s]

Processing tickers:  27%|██▋       | 1868/6932 [06:48<17:35,  4.80it/s]

Processing tickers:  27%|██▋       | 1869/6932 [06:49<18:02,  4.68it/s]

Processing tickers:  27%|██▋       | 1870/6932 [06:49<17:50,  4.73it/s]

Processing tickers:  27%|██▋       | 1871/6932 [06:49<17:44,  4.75it/s]

Processing tickers:  27%|██▋       | 1872/6932 [06:49<17:55,  4.70it/s]

Processing tickers:  27%|██▋       | 1873/6932 [06:50<17:58,  4.69it/s]

Processing tickers:  27%|██▋       | 1874/6932 [06:50<17:49,  4.73it/s]

Processing tickers:  27%|██▋       | 1875/6932 [06:50<18:14,  4.62it/s]

Processing tickers:  27%|██▋       | 1876/6932 [06:50<17:55,  4.70it/s]

Processing tickers:  27%|██▋       | 1877/6932 [06:50<17:47,  4.74it/s]

Processing tickers:  27%|██▋       | 1878/6932 [06:51<18:05,  4.66it/s]

Processing tickers:  27%|██▋       | 1879/6932 [06:51<18:02,  4.67it/s]

Processing tickers:  27%|██▋       | 1880/6932 [06:51<17:45,  4.74it/s]

Processing tickers:  27%|██▋       | 1881/6932 [06:51<17:41,  4.76it/s]

Processing tickers:  27%|██▋       | 1882/6932 [06:51<18:02,  4.66it/s]

Processing tickers:  27%|██▋       | 1883/6932 [06:52<18:08,  4.64it/s]

Processing tickers:  27%|██▋       | 1884/6932 [06:52<18:06,  4.65it/s]

Processing tickers:  27%|██▋       | 1885/6932 [06:52<18:17,  4.60it/s]

Processing tickers:  27%|██▋       | 1886/6932 [06:52<18:48,  4.47it/s]

Processing tickers:  27%|██▋       | 1887/6932 [06:53<18:24,  4.57it/s]

Processing tickers:  27%|██▋       | 1888/6932 [06:53<18:27,  4.55it/s]

Processing tickers:  27%|██▋       | 1889/6932 [06:53<18:30,  4.54it/s]

Processing tickers:  27%|██▋       | 1890/6932 [06:53<18:09,  4.63it/s]

Processing tickers:  27%|██▋       | 1891/6932 [06:53<18:14,  4.61it/s]

Processing tickers:  27%|██▋       | 1892/6932 [06:54<17:44,  4.74it/s]

Processing tickers:  27%|██▋       | 1893/6932 [06:54<17:37,  4.77it/s]

Processing tickers:  27%|██▋       | 1894/6932 [06:54<17:55,  4.68it/s]

Processing tickers:  27%|██▋       | 1895/6932 [06:54<18:09,  4.62it/s]

Processing tickers:  27%|██▋       | 1896/6932 [06:54<17:53,  4.69it/s]

Processing tickers:  27%|██▋       | 1897/6932 [06:55<18:05,  4.64it/s]

Processing tickers:  27%|██▋       | 1898/6932 [06:55<18:16,  4.59it/s]

Processing tickers:  27%|██▋       | 1899/6932 [06:55<18:09,  4.62it/s]

Processing tickers:  27%|██▋       | 1900/6932 [06:55<18:41,  4.49it/s]

Processing tickers:  27%|██▋       | 1901/6932 [06:56<18:14,  4.60it/s]

Processing tickers:  27%|██▋       | 1902/6932 [06:56<18:22,  4.56it/s]

Processing tickers:  27%|██▋       | 1903/6932 [06:56<18:06,  4.63it/s]

Processing tickers:  27%|██▋       | 1904/6932 [06:56<17:53,  4.68it/s]

Processing tickers:  27%|██▋       | 1905/6932 [06:56<17:44,  4.72it/s]

Processing tickers:  27%|██▋       | 1906/6932 [06:57<17:40,  4.74it/s]

Processing tickers:  28%|██▊       | 1907/6932 [06:57<17:37,  4.75it/s]

Processing tickers:  28%|██▊       | 1908/6932 [06:57<17:57,  4.66it/s]

Processing tickers:  28%|██▊       | 1909/6932 [06:57<17:43,  4.72it/s]

Processing tickers:  28%|██▊       | 1910/6932 [06:57<17:59,  4.65it/s]

Processing tickers:  28%|██▊       | 1911/6932 [06:58<18:11,  4.60it/s]

Processing tickers:  28%|██▊       | 1912/6932 [06:58<18:21,  4.56it/s]

Processing tickers:  28%|██▊       | 1913/6932 [06:58<18:26,  4.54it/s]

Processing tickers:  28%|██▊       | 1914/6932 [06:58<18:06,  4.62it/s]

Processing tickers:  28%|██▊       | 1915/6932 [06:59<17:52,  4.68it/s]

Processing tickers:  28%|██▊       | 1916/6932 [06:59<17:44,  4.71it/s]

Processing tickers:  28%|██▊       | 1917/6932 [06:59<18:00,  4.64it/s]

Processing tickers:  28%|██▊       | 1918/6932 [06:59<17:50,  4.69it/s]

Processing tickers:  28%|██▊       | 1919/6932 [06:59<17:41,  4.72it/s]

Processing tickers:  28%|██▊       | 1920/6932 [07:00<17:37,  4.74it/s]

Processing tickers:  28%|██▊       | 1921/6932 [07:00<17:34,  4.75it/s]

Processing tickers:  28%|██▊       | 1922/6932 [07:00<17:54,  4.66it/s]

Processing tickers:  28%|██▊       | 1923/6932 [07:00<18:08,  4.60it/s]

Processing tickers:  28%|██▊       | 1924/6932 [07:01<17:51,  4.67it/s]

Processing tickers:  28%|██▊       | 1925/6932 [07:01<17:52,  4.67it/s]

Processing tickers:  28%|██▊       | 1926/6932 [07:01<17:50,  4.68it/s]

Processing tickers:  28%|██▊       | 1927/6932 [07:01<17:50,  4.68it/s]

Processing tickers:  28%|██▊       | 1928/6932 [07:01<18:00,  4.63it/s]

Processing tickers:  28%|██▊       | 1929/6932 [07:02<17:49,  4.68it/s]

Processing tickers:  28%|██▊       | 1930/6932 [07:02<18:02,  4.62it/s]

Processing tickers:  28%|██▊       | 1931/6932 [07:02<18:21,  4.54it/s]

Processing tickers:  28%|██▊       | 1932/6932 [07:02<17:55,  4.65it/s]

Processing tickers:  28%|██▊       | 1933/6932 [07:02<18:10,  4.58it/s]

Processing tickers:  28%|██▊       | 1934/6932 [07:03<18:01,  4.62it/s]

Processing tickers:  28%|██▊       | 1935/6932 [07:03<18:02,  4.62it/s]

Processing tickers:  28%|██▊       | 1936/6932 [07:03<17:46,  4.68it/s]

Processing tickers:  28%|██▊       | 1937/6932 [07:03<18:00,  4.62it/s]

Processing tickers:  28%|██▊       | 1938/6932 [07:04<17:48,  4.68it/s]

Processing tickers:  28%|██▊       | 1939/6932 [07:04<18:03,  4.61it/s]

Processing tickers:  28%|██▊       | 1940/6932 [07:04<18:18,  4.54it/s]

Processing tickers:  28%|██▊       | 1941/6932 [07:04<18:00,  4.62it/s]

Processing tickers:  28%|██▊       | 1942/6932 [07:04<17:42,  4.70it/s]

Processing tickers:  28%|██▊       | 1943/6932 [07:05<17:43,  4.69it/s]

Processing tickers:  28%|██▊       | 1944/6932 [07:05<17:32,  4.74it/s]

Processing tickers:  28%|██▊       | 1945/6932 [07:05<17:31,  4.74it/s]

Processing tickers:  28%|██▊       | 1946/6932 [07:05<17:40,  4.70it/s]

Processing tickers:  28%|██▊       | 1947/6932 [07:05<17:35,  4.73it/s]

Processing tickers:  28%|██▊       | 1948/6932 [07:06<17:28,  4.75it/s]

Processing tickers:  28%|██▊       | 1949/6932 [07:06<17:53,  4.64it/s]

Processing tickers:  28%|██▊       | 1950/6932 [07:06<17:37,  4.71it/s]

Processing tickers:  28%|██▊       | 1951/6932 [07:06<17:30,  4.74it/s]

Processing tickers:  28%|██▊       | 1952/6932 [07:07<17:54,  4.63it/s]

Processing tickers:  28%|██▊       | 1953/6932 [07:07<18:01,  4.60it/s]

Processing tickers:  28%|██▊       | 1954/6932 [07:07<17:52,  4.64it/s]

Processing tickers:  28%|██▊       | 1955/6932 [07:07<17:35,  4.71it/s]

Processing tickers:  28%|██▊       | 1956/6932 [07:07<17:31,  4.73it/s]

Processing tickers:  28%|██▊       | 1957/6932 [07:08<17:51,  4.64it/s]

Processing tickers:  28%|██▊       | 1958/6932 [07:08<17:39,  4.70it/s]

Processing tickers:  28%|██▊       | 1959/6932 [07:08<17:54,  4.63it/s]

Processing tickers:  28%|██▊       | 1960/6932 [07:08<17:42,  4.68it/s]

Processing tickers:  28%|██▊       | 1961/6932 [07:08<17:33,  4.72it/s]

Processing tickers:  28%|██▊       | 1962/6932 [07:09<17:27,  4.74it/s]

Processing tickers:  28%|██▊       | 1963/6932 [07:09<17:22,  4.76it/s]

Processing tickers:  28%|██▊       | 1964/6932 [07:09<17:20,  4.78it/s]

Processing tickers:  28%|██▊       | 1965/6932 [07:09<17:42,  4.68it/s]

Processing tickers:  28%|██▊       | 1966/6932 [07:09<17:32,  4.72it/s]

Processing tickers:  28%|██▊       | 1967/6932 [07:10<17:26,  4.74it/s]

Processing tickers:  28%|██▊       | 1968/6932 [07:10<17:23,  4.76it/s]

Processing tickers:  28%|██▊       | 1969/6932 [07:10<17:31,  4.72it/s]

Processing tickers:  28%|██▊       | 1970/6932 [07:10<17:44,  4.66it/s]

Processing tickers:  28%|██▊       | 1971/6932 [07:11<17:33,  4.71it/s]

Processing tickers:  28%|██▊       | 1972/6932 [07:11<17:36,  4.70it/s]

Processing tickers:  28%|██▊       | 1973/6932 [07:11<17:14,  4.80it/s]

Processing tickers:  28%|██▊       | 1974/6932 [07:11<17:36,  4.69it/s]

Processing tickers:  28%|██▊       | 1975/6932 [07:11<17:52,  4.62it/s]

Processing tickers:  29%|██▊       | 1976/6932 [07:12<19:15,  4.29it/s]

Processing tickers:  29%|██▊       | 1977/6932 [07:12<18:38,  4.43it/s]

Processing tickers:  29%|██▊       | 1978/6932 [07:12<18:33,  4.45it/s]

Processing tickers:  29%|██▊       | 1979/6932 [07:12<18:12,  4.53it/s]

Processing tickers:  29%|██▊       | 1980/6932 [07:13<18:12,  4.53it/s]

Processing tickers:  29%|██▊       | 1981/6932 [07:13<17:54,  4.61it/s]

Processing tickers:  29%|██▊       | 1982/6932 [07:13<18:10,  4.54it/s]

Processing tickers:  29%|██▊       | 1983/6932 [07:13<17:48,  4.63it/s]

Processing tickers:  29%|██▊       | 1984/6932 [07:13<17:35,  4.69it/s]

Processing tickers:  29%|██▊       | 1985/6932 [07:14<17:31,  4.71it/s]

Processing tickers:  29%|██▊       | 1986/6932 [07:14<17:21,  4.75it/s]

Processing tickers:  29%|██▊       | 1987/6932 [07:14<17:21,  4.75it/s]

Processing tickers:  29%|██▊       | 1988/6932 [07:14<17:38,  4.67it/s]

Processing tickers:  29%|██▊       | 1989/6932 [07:14<17:28,  4.72it/s]

Processing tickers:  29%|██▊       | 1990/6932 [07:15<17:21,  4.74it/s]

Processing tickers:  29%|██▊       | 1991/6932 [07:15<17:16,  4.77it/s]

Processing tickers:  29%|██▊       | 1992/6932 [07:15<17:37,  4.67it/s]

Processing tickers:  29%|██▉       | 1993/6932 [07:15<17:29,  4.71it/s]

Processing tickers:  29%|██▉       | 1994/6932 [07:16<17:22,  4.74it/s]

Processing tickers:  29%|██▉       | 1995/6932 [07:16<17:41,  4.65it/s]

Processing tickers:  29%|██▉       | 1996/6932 [07:16<17:33,  4.69it/s]

Processing tickers:  29%|██▉       | 1997/6932 [07:16<17:24,  4.73it/s]

Processing tickers:  29%|██▉       | 1998/6932 [07:16<17:17,  4.75it/s]

Processing tickers:  29%|██▉       | 1999/6932 [07:17<17:14,  4.77it/s]

Processing tickers:  29%|██▉       | 2000/6932 [07:17<17:11,  4.78it/s]

Processing tickers:  29%|██▉       | 2001/6932 [07:17<17:36,  4.67it/s]

Processing tickers:  29%|██▉       | 2002/6932 [07:17<17:48,  4.61it/s]

Processing tickers:  29%|██▉       | 2003/6932 [07:17<17:35,  4.67it/s]

Processing tickers:  29%|██▉       | 2004/6932 [07:18<17:26,  4.71it/s]

Processing tickers:  29%|██▉       | 2005/6932 [07:18<17:44,  4.63it/s]

Processing tickers:  29%|██▉       | 2006/6932 [07:18<17:33,  4.68it/s]

Processing tickers:  29%|██▉       | 2007/6932 [07:18<17:24,  4.72it/s]

Processing tickers:  29%|██▉       | 2008/6932 [07:18<17:27,  4.70it/s]

Processing tickers:  29%|██▉       | 2009/6932 [07:19<17:11,  4.77it/s]

Processing tickers:  29%|██▉       | 2010/6932 [07:19<17:31,  4.68it/s]

Processing tickers:  29%|██▉       | 2011/6932 [07:19<17:23,  4.72it/s]

Processing tickers:  29%|██▉       | 2012/6932 [07:19<17:22,  4.72it/s]

Processing tickers:  29%|██▉       | 2013/6932 [07:20<17:35,  4.66it/s]

Processing tickers:  29%|██▉       | 2014/6932 [07:20<17:25,  4.70it/s]

Processing tickers:  29%|██▉       | 2015/6932 [07:20<17:23,  4.71it/s]

Processing tickers:  29%|██▉       | 2016/6932 [07:20<17:12,  4.76it/s]

Processing tickers:  29%|██▉       | 2017/6932 [07:20<17:08,  4.78it/s]

Processing tickers:  29%|██▉       | 2018/6932 [07:21<17:06,  4.79it/s]

Processing tickers:  29%|██▉       | 2019/6932 [07:21<17:05,  4.79it/s]

Processing tickers:  29%|██▉       | 2020/6932 [07:21<17:05,  4.79it/s]

Processing tickers:  29%|██▉       | 2021/6932 [07:21<17:26,  4.69it/s]

Processing tickers:  29%|██▉       | 2022/6932 [07:21<16:56,  4.83it/s]

Processing tickers:  29%|██▉       | 2023/6932 [07:22<16:56,  4.83it/s]

Processing tickers:  29%|██▉       | 2024/6932 [07:22<17:18,  4.73it/s]

Processing tickers:  29%|██▉       | 2025/6932 [07:22<17:15,  4.74it/s]

Processing tickers:  29%|██▉       | 2026/6932 [07:22<17:10,  4.76it/s]

Processing tickers:  29%|██▉       | 2027/6932 [07:22<17:06,  4.78it/s]

Processing tickers:  29%|██▉       | 2028/6932 [07:23<17:04,  4.79it/s]

Processing tickers:  29%|██▉       | 2029/6932 [07:23<17:03,  4.79it/s]

Processing tickers:  29%|██▉       | 2030/6932 [07:23<17:09,  4.76it/s]

Processing tickers:  29%|██▉       | 2031/6932 [07:23<17:22,  4.70it/s]

Processing tickers:  29%|██▉       | 2032/6932 [07:24<17:12,  4.74it/s]

Processing tickers:  29%|██▉       | 2033/6932 [07:24<17:07,  4.77it/s]

Processing tickers:  29%|██▉       | 2034/6932 [07:24<17:28,  4.67it/s]

Processing tickers:  29%|██▉       | 2035/6932 [07:24<17:18,  4.72it/s]

Processing tickers:  29%|██▉       | 2036/6932 [07:24<17:12,  4.74it/s]

Processing tickers:  29%|██▉       | 2037/6932 [07:25<16:42,  4.88it/s]

Processing tickers:  29%|██▉       | 2038/6932 [07:25<17:24,  4.69it/s]

Processing tickers:  29%|██▉       | 2039/6932 [07:25<17:02,  4.79it/s]

Processing tickers:  29%|██▉       | 2040/6932 [07:25<17:46,  4.59it/s]

Processing tickers:  29%|██▉       | 2041/6932 [07:25<17:08,  4.76it/s]

Processing tickers:  29%|██▉       | 2042/6932 [07:26<17:06,  4.76it/s]

Processing tickers:  29%|██▉       | 2043/6932 [07:26<17:03,  4.78it/s]

Processing tickers:  29%|██▉       | 2044/6932 [07:26<17:23,  4.68it/s]

Processing tickers:  30%|██▉       | 2045/6932 [07:26<17:16,  4.72it/s]

Processing tickers:  30%|██▉       | 2046/6932 [07:26<17:10,  4.74it/s]

Processing tickers:  30%|██▉       | 2047/6932 [07:27<17:29,  4.65it/s]

Processing tickers:  30%|██▉       | 2048/6932 [07:27<18:03,  4.51it/s]

Processing tickers:  30%|██▉       | 2049/6932 [07:27<17:45,  4.58it/s]

Processing tickers:  30%|██▉       | 2050/6932 [07:27<17:30,  4.65it/s]

Processing tickers:  30%|██▉       | 2051/6932 [07:28<17:37,  4.61it/s]

Processing tickers:  30%|██▉       | 2052/6932 [07:28<17:29,  4.65it/s]

Processing tickers:  30%|██▉       | 2053/6932 [07:28<18:05,  4.49it/s]

Processing tickers:  30%|██▉       | 2054/6932 [07:28<18:07,  4.49it/s]

Processing tickers:  30%|██▉       | 2055/6932 [07:28<18:09,  4.48it/s]

Processing tickers:  30%|██▉       | 2056/6932 [07:29<17:45,  4.58it/s]

Processing tickers:  30%|██▉       | 2057/6932 [07:29<17:30,  4.64it/s]

Processing tickers:  30%|██▉       | 2058/6932 [07:29<17:23,  4.67it/s]

Processing tickers:  30%|██▉       | 2059/6932 [07:29<17:12,  4.72it/s]

Processing tickers:  30%|██▉       | 2060/6932 [07:30<17:07,  4.74it/s]

Processing tickers:  30%|██▉       | 2061/6932 [07:30<17:03,  4.76it/s]

Processing tickers:  30%|██▉       | 2062/6932 [07:30<17:06,  4.75it/s]

Processing tickers:  30%|██▉       | 2063/6932 [07:30<17:06,  4.74it/s]

Processing tickers:  30%|██▉       | 2064/6932 [07:30<17:05,  4.75it/s]

Processing tickers:  30%|██▉       | 2065/6932 [07:31<17:10,  4.72it/s]

Processing tickers:  30%|██▉       | 2066/6932 [07:31<17:20,  4.68it/s]

Processing tickers:  30%|██▉       | 2067/6932 [07:31<17:20,  4.68it/s]

Processing tickers:  30%|██▉       | 2068/6932 [07:31<17:20,  4.67it/s]

Processing tickers:  30%|██▉       | 2069/6932 [07:31<17:26,  4.65it/s]

Processing tickers:  30%|██▉       | 2070/6932 [07:32<17:13,  4.70it/s]

Processing tickers:  30%|██▉       | 2071/6932 [07:32<17:14,  4.70it/s]

Processing tickers:  30%|██▉       | 2072/6932 [07:32<17:16,  4.69it/s]

Processing tickers:  30%|██▉       | 2073/6932 [07:32<17:36,  4.60it/s]

Processing tickers:  30%|██▉       | 2074/6932 [07:33<17:39,  4.59it/s]

Processing tickers:  30%|██▉       | 2075/6932 [07:33<17:26,  4.64it/s]

Processing tickers:  30%|██▉       | 2076/6932 [07:33<17:38,  4.59it/s]

Processing tickers:  30%|██▉       | 2077/6932 [07:33<17:23,  4.65it/s]

Processing tickers:  30%|██▉       | 2078/6932 [07:33<17:13,  4.70it/s]

Processing tickers:  30%|██▉       | 2079/6932 [07:34<17:05,  4.73it/s]

Processing tickers:  30%|███       | 2080/6932 [07:34<16:59,  4.76it/s]

Processing tickers:  30%|███       | 2081/6932 [07:34<17:18,  4.67it/s]

Processing tickers:  30%|███       | 2082/6932 [07:34<17:32,  4.61it/s]

Processing tickers:  30%|███       | 2083/6932 [07:34<17:19,  4.67it/s]

Processing tickers:  30%|███       | 2084/6932 [07:35<17:10,  4.71it/s]

Processing tickers:  30%|███       | 2085/6932 [07:35<17:03,  4.73it/s]

Processing tickers:  30%|███       | 2086/6932 [07:35<17:21,  4.65it/s]

Processing tickers:  30%|███       | 2087/6932 [07:35<17:18,  4.66it/s]

Processing tickers:  30%|███       | 2088/6932 [07:36<17:02,  4.74it/s]

Processing tickers:  30%|███       | 2089/6932 [07:36<17:21,  4.65it/s]

Processing tickers:  30%|███       | 2090/6932 [07:36<17:11,  4.69it/s]

Processing tickers:  30%|███       | 2091/6932 [07:36<17:26,  4.63it/s]

Processing tickers:  30%|███       | 2092/6932 [07:36<17:12,  4.69it/s]

Processing tickers:  30%|███       | 2093/6932 [07:37<17:03,  4.73it/s]

Processing tickers:  30%|███       | 2094/6932 [07:37<16:57,  4.75it/s]

Processing tickers:  30%|███       | 2095/6932 [07:37<16:54,  4.77it/s]

Processing tickers:  30%|███       | 2096/6932 [07:37<16:51,  4.78it/s]

Processing tickers:  30%|███       | 2097/6932 [07:37<16:49,  4.79it/s]

Processing tickers:  30%|███       | 2098/6932 [07:38<16:49,  4.79it/s]

Processing tickers:  30%|███       | 2099/6932 [07:38<16:48,  4.79it/s]

Processing tickers:  30%|███       | 2100/6932 [07:38<17:11,  4.68it/s]

Processing tickers:  30%|███       | 2101/6932 [07:38<17:03,  4.72it/s]

Processing tickers:  30%|███       | 2102/6932 [07:38<16:56,  4.75it/s]

Processing tickers:  30%|███       | 2103/6932 [07:39<16:55,  4.76it/s]

Processing tickers:  30%|███       | 2104/6932 [07:39<16:49,  4.78it/s]

Processing tickers:  30%|███       | 2105/6932 [07:39<16:48,  4.79it/s]

Processing tickers:  30%|███       | 2106/6932 [07:39<17:10,  4.68it/s]

Processing tickers:  30%|███       | 2107/6932 [07:40<17:01,  4.73it/s]

Processing tickers:  30%|███       | 2108/6932 [07:40<17:18,  4.65it/s]

Processing tickers:  30%|███       | 2109/6932 [07:40<17:10,  4.68it/s]

Processing tickers:  30%|███       | 2110/6932 [07:40<17:00,  4.72it/s]

Processing tickers:  30%|███       | 2111/6932 [07:40<16:55,  4.75it/s]

Processing tickers:  30%|███       | 2112/6932 [07:41<16:52,  4.76it/s]

Processing tickers:  30%|███       | 2113/6932 [07:41<16:50,  4.77it/s]

Processing tickers:  30%|███       | 2114/6932 [07:41<17:11,  4.67it/s]

Processing tickers:  31%|███       | 2115/6932 [07:41<17:02,  4.71it/s]

Processing tickers:  31%|███       | 2116/6932 [07:41<16:55,  4.74it/s]

Processing tickers:  31%|███       | 2117/6932 [07:42<17:01,  4.71it/s]

Processing tickers:  31%|███       | 2118/6932 [07:42<17:12,  4.66it/s]

Processing tickers:  31%|███       | 2119/6932 [07:42<17:18,  4.63it/s]

Processing tickers:  31%|███       | 2120/6932 [07:42<17:43,  4.53it/s]

Processing tickers:  31%|███       | 2121/6932 [07:43<17:08,  4.68it/s]

Processing tickers:  31%|███       | 2122/6932 [07:43<17:23,  4.61it/s]

Processing tickers:  31%|███       | 2123/6932 [07:43<17:11,  4.66it/s]

Processing tickers:  31%|███       | 2124/6932 [07:43<17:24,  4.60it/s]

Processing tickers:  31%|███       | 2125/6932 [07:43<17:13,  4.65it/s]

Processing tickers:  31%|███       | 2126/6932 [07:44<17:23,  4.61it/s]

Processing tickers:  31%|███       | 2127/6932 [07:44<17:10,  4.66it/s]

Processing tickers:  31%|███       | 2128/6932 [07:44<17:00,  4.71it/s]

Processing tickers:  31%|███       | 2129/6932 [07:44<16:54,  4.74it/s]

Processing tickers:  31%|███       | 2130/6932 [07:44<17:13,  4.65it/s]

Processing tickers:  31%|███       | 2131/6932 [07:45<17:26,  4.59it/s]

Processing tickers:  31%|███       | 2132/6932 [07:45<17:11,  4.65it/s]

Processing tickers:  31%|███       | 2133/6932 [07:45<17:01,  4.70it/s]

Processing tickers:  31%|███       | 2134/6932 [07:45<17:17,  4.62it/s]

Processing tickers:  31%|███       | 2135/6932 [07:46<17:05,  4.68it/s]

Processing tickers:  31%|███       | 2136/6932 [07:46<16:57,  4.71it/s]

Processing tickers:  31%|███       | 2137/6932 [07:46<17:12,  4.64it/s]

Processing tickers:  31%|███       | 2138/6932 [07:46<17:25,  4.59it/s]

Processing tickers:  31%|███       | 2139/6932 [07:46<17:23,  4.59it/s]

Processing tickers:  31%|███       | 2140/6932 [07:47<16:57,  4.71it/s]

Processing tickers:  31%|███       | 2141/6932 [07:47<17:19,  4.61it/s]

Processing tickers:  31%|███       | 2142/6932 [07:47<17:01,  4.69it/s]

Processing tickers:  31%|███       | 2143/6932 [07:47<16:54,  4.72it/s]

Processing tickers:  31%|███       | 2144/6932 [07:47<17:15,  4.62it/s]

Processing tickers:  31%|███       | 2145/6932 [07:48<17:08,  4.65it/s]

Processing tickers:  31%|███       | 2146/6932 [07:48<16:49,  4.74it/s]

Processing tickers:  31%|███       | 2147/6932 [07:48<17:06,  4.66it/s]

Processing tickers:  31%|███       | 2148/6932 [07:48<17:04,  4.67it/s]

Processing tickers:  31%|███       | 2149/6932 [07:49<16:49,  4.74it/s]

Processing tickers:  31%|███       | 2150/6932 [07:49<17:10,  4.64it/s]

Processing tickers:  31%|███       | 2151/6932 [07:49<16:54,  4.71it/s]

Processing tickers:  31%|███       | 2152/6932 [07:49<17:09,  4.65it/s]

Processing tickers:  31%|███       | 2153/6932 [07:49<17:05,  4.66it/s]

Processing tickers:  31%|███       | 2154/6932 [07:50<16:55,  4.71it/s]

Processing tickers:  31%|███       | 2155/6932 [07:50<16:42,  4.76it/s]

Processing tickers:  31%|███       | 2156/6932 [07:50<16:40,  4.77it/s]

Processing tickers:  31%|███       | 2157/6932 [07:50<16:53,  4.71it/s]

Processing tickers:  31%|███       | 2158/6932 [07:50<16:53,  4.71it/s]

Processing tickers:  31%|███       | 2159/6932 [07:51<17:12,  4.62it/s]

Processing tickers:  31%|███       | 2160/6932 [07:51<17:06,  4.65it/s]

Processing tickers:  31%|███       | 2161/6932 [07:51<17:13,  4.62it/s]

Processing tickers:  31%|███       | 2162/6932 [07:51<17:02,  4.67it/s]

Processing tickers:  31%|███       | 2163/6932 [07:52<17:08,  4.64it/s]

Processing tickers:  31%|███       | 2164/6932 [07:52<17:15,  4.61it/s]

Processing tickers:  31%|███       | 2165/6932 [07:52<16:53,  4.70it/s]

Processing tickers:  31%|███       | 2166/6932 [07:52<17:07,  4.64it/s]

Processing tickers:  31%|███▏      | 2167/6932 [07:52<17:08,  4.63it/s]

Processing tickers:  31%|███▏      | 2168/6932 [07:53<16:46,  4.74it/s]

Processing tickers:  31%|███▏      | 2169/6932 [07:53<16:41,  4.75it/s]

Processing tickers:  31%|███▏      | 2170/6932 [07:53<16:49,  4.72it/s]

Processing tickers:  31%|███▏      | 2171/6932 [07:53<16:29,  4.81it/s]

Processing tickers:  31%|███▏      | 2172/6932 [07:53<16:49,  4.71it/s]

Processing tickers:  31%|███▏      | 2173/6932 [07:54<16:42,  4.75it/s]

Processing tickers:  31%|███▏      | 2174/6932 [07:54<17:01,  4.66it/s]

Processing tickers:  31%|███▏      | 2175/6932 [07:54<16:51,  4.70it/s]

Processing tickers:  31%|███▏      | 2176/6932 [07:54<16:47,  4.72it/s]

Processing tickers:  31%|███▏      | 2177/6932 [07:55<16:57,  4.67it/s]

Processing tickers:  31%|███▏      | 2178/6932 [07:55<17:33,  4.51it/s]

Processing tickers:  31%|███▏      | 2179/6932 [07:55<17:21,  4.56it/s]

Processing tickers:  31%|███▏      | 2180/6932 [07:55<16:58,  4.67it/s]

Processing tickers:  31%|███▏      | 2181/6932 [07:55<17:12,  4.60it/s]

Processing tickers:  31%|███▏      | 2182/6932 [07:56<16:59,  4.66it/s]

Processing tickers:  31%|███▏      | 2183/6932 [07:56<16:49,  4.71it/s]

Processing tickers:  32%|███▏      | 2184/6932 [07:56<16:43,  4.73it/s]

Processing tickers:  32%|███▏      | 2185/6932 [07:56<16:38,  4.75it/s]

Processing tickers:  32%|███▏      | 2186/6932 [07:56<16:58,  4.66it/s]

Processing tickers:  32%|███▏      | 2187/6932 [07:57<16:49,  4.70it/s]

Processing tickers:  32%|███▏      | 2188/6932 [07:57<16:43,  4.73it/s]

Processing tickers:  32%|███▏      | 2189/6932 [07:57<17:05,  4.62it/s]

Processing tickers:  32%|███▏      | 2190/6932 [07:57<16:49,  4.70it/s]

Processing tickers:  32%|███▏      | 2191/6932 [07:57<16:42,  4.73it/s]

Processing tickers:  32%|███▏      | 2192/6932 [07:58<16:59,  4.65it/s]

Processing tickers:  32%|███▏      | 2193/6932 [07:58<17:03,  4.63it/s]

Processing tickers:  32%|███▏      | 2194/6932 [07:58<16:39,  4.74it/s]

Processing tickers:  32%|███▏      | 2195/6932 [07:58<16:34,  4.76it/s]

Processing tickers:  32%|███▏      | 2196/6932 [07:59<16:55,  4.67it/s]

Processing tickers:  32%|███▏      | 2197/6932 [07:59<17:07,  4.61it/s]

Processing tickers:  32%|███▏      | 2198/6932 [07:59<17:17,  4.56it/s]

Processing tickers:  32%|███▏      | 2199/6932 [07:59<17:02,  4.63it/s]

Processing tickers:  32%|███▏      | 2200/6932 [07:59<17:05,  4.62it/s]

Processing tickers:  32%|███▏      | 2201/6932 [08:00<16:34,  4.76it/s]

Processing tickers:  32%|███▏      | 2202/6932 [08:00<16:53,  4.67it/s]

Processing tickers:  32%|███▏      | 2203/6932 [08:00<16:44,  4.71it/s]

Processing tickers:  32%|███▏      | 2204/6932 [08:00<16:37,  4.74it/s]

Processing tickers:  32%|███▏      | 2205/6932 [08:00<16:33,  4.76it/s]

Processing tickers:  32%|███▏      | 2206/6932 [08:01<16:30,  4.77it/s]

Processing tickers:  32%|███▏      | 2207/6932 [08:01<16:50,  4.68it/s]

Processing tickers:  32%|███▏      | 2208/6932 [08:01<16:55,  4.65it/s]

Processing tickers:  32%|███▏      | 2209/6932 [08:01<16:47,  4.69it/s]

Processing tickers:  32%|███▏      | 2210/6932 [08:02<16:22,  4.80it/s]

Processing tickers:  32%|███▏      | 2211/6932 [08:02<16:20,  4.81it/s]

Processing tickers:  32%|███▏      | 2212/6932 [08:02<16:19,  4.82it/s]

Processing tickers:  32%|███▏      | 2213/6932 [08:02<16:47,  4.68it/s]

Processing tickers:  32%|███▏      | 2214/6932 [08:02<16:38,  4.72it/s]

Processing tickers:  32%|███▏      | 2215/6932 [08:03<16:30,  4.76it/s]

Processing tickers:  32%|███▏      | 2216/6932 [08:03<16:49,  4.67it/s]

Processing tickers:  32%|███▏      | 2217/6932 [08:03<16:49,  4.67it/s]

Processing tickers:  32%|███▏      | 2218/6932 [08:03<16:56,  4.64it/s]

Processing tickers:  32%|███▏      | 2219/6932 [08:03<16:48,  4.67it/s]

Processing tickers:  32%|███▏      | 2220/6932 [08:04<16:34,  4.74it/s]

Processing tickers:  32%|███▏      | 2221/6932 [08:04<16:30,  4.76it/s]

Processing tickers:  32%|███▏      | 2222/6932 [08:04<16:32,  4.75it/s]

Processing tickers:  32%|███▏      | 2223/6932 [08:04<16:53,  4.65it/s]

Processing tickers:  32%|███▏      | 2224/6932 [08:05<16:42,  4.70it/s]

Processing tickers:  32%|███▏      | 2225/6932 [08:05<16:26,  4.77it/s]

Processing tickers:  32%|███▏      | 2226/6932 [08:05<16:56,  4.63it/s]

Processing tickers:  32%|███▏      | 2227/6932 [08:05<16:33,  4.74it/s]

Processing tickers:  32%|███▏      | 2228/6932 [08:05<16:51,  4.65it/s]

Processing tickers:  32%|███▏      | 2229/6932 [08:06<16:55,  4.63it/s]

Processing tickers:  32%|███▏      | 2230/6932 [08:06<16:52,  4.65it/s]

Processing tickers:  32%|███▏      | 2231/6932 [08:06<16:50,  4.65it/s]

Processing tickers:  32%|███▏      | 2232/6932 [08:06<16:34,  4.73it/s]

Processing tickers:  32%|███▏      | 2233/6932 [08:06<16:28,  4.76it/s]

Processing tickers:  32%|███▏      | 2234/6932 [08:07<16:24,  4.77it/s]

Processing tickers:  32%|███▏      | 2235/6932 [08:07<16:41,  4.69it/s]

Processing tickers:  32%|███▏      | 2236/6932 [08:07<16:36,  4.71it/s]

Processing tickers:  32%|███▏      | 2237/6932 [08:07<16:30,  4.74it/s]

Processing tickers:  32%|███▏      | 2238/6932 [08:07<16:29,  4.74it/s]

Processing tickers:  32%|███▏      | 2239/6932 [08:08<16:23,  4.77it/s]

Processing tickers:  32%|███▏      | 2240/6932 [08:08<16:41,  4.69it/s]

Processing tickers:  32%|███▏      | 2241/6932 [08:08<16:32,  4.73it/s]

Processing tickers:  32%|███▏      | 2242/6932 [08:08<16:39,  4.69it/s]

Processing tickers:  32%|███▏      | 2243/6932 [08:09<16:39,  4.69it/s]

Processing tickers:  32%|███▏      | 2244/6932 [08:09<16:12,  4.82it/s]

Processing tickers:  32%|███▏      | 2245/6932 [08:09<16:36,  4.70it/s]

Processing tickers:  32%|███▏      | 2246/6932 [08:09<16:30,  4.73it/s]

Processing tickers:  32%|███▏      | 2247/6932 [08:09<16:03,  4.86it/s]

Processing tickers:  32%|███▏      | 2248/6932 [08:10<16:28,  4.74it/s]

Processing tickers:  32%|███▏      | 2249/6932 [08:10<16:45,  4.66it/s]

Processing tickers:  32%|███▏      | 2250/6932 [08:10<16:55,  4.61it/s]

Processing tickers:  32%|███▏      | 2251/6932 [08:10<16:41,  4.67it/s]

Processing tickers:  32%|███▏      | 2252/6932 [08:10<17:02,  4.58it/s]

Processing tickers:  33%|███▎      | 2253/6932 [08:11<16:49,  4.63it/s]

Processing tickers:  33%|███▎      | 2254/6932 [08:11<16:36,  4.69it/s]

Processing tickers:  33%|███▎      | 2255/6932 [08:11<16:57,  4.60it/s]

Processing tickers:  33%|███▎      | 2256/6932 [08:11<16:37,  4.69it/s]

Processing tickers:  33%|███▎      | 2257/6932 [08:12<16:37,  4.69it/s]

Processing tickers:  33%|███▎      | 2258/6932 [08:12<16:23,  4.75it/s]

Processing tickers:  33%|███▎      | 2259/6932 [08:12<16:19,  4.77it/s]

Processing tickers:  33%|███▎      | 2260/6932 [08:12<16:16,  4.79it/s]

Processing tickers:  33%|███▎      | 2261/6932 [08:12<16:14,  4.79it/s]

Processing tickers:  33%|███▎      | 2262/6932 [08:13<16:13,  4.80it/s]

Processing tickers:  33%|███▎      | 2263/6932 [08:13<16:54,  4.60it/s]

Processing tickers:  33%|███▎      | 2264/6932 [08:13<16:45,  4.64it/s]

Processing tickers:  33%|███▎      | 2265/6932 [08:13<16:37,  4.68it/s]

Processing tickers:  33%|███▎      | 2266/6932 [08:13<16:25,  4.73it/s]

Processing tickers:  33%|███▎      | 2267/6932 [08:14<15:57,  4.87it/s]

Processing tickers:  33%|███▎      | 2268/6932 [08:14<16:01,  4.85it/s]

Processing tickers:  33%|███▎      | 2269/6932 [08:14<16:25,  4.73it/s]

Processing tickers:  33%|███▎      | 2270/6932 [08:14<16:21,  4.75it/s]

Processing tickers:  33%|███▎      | 2271/6932 [08:14<16:15,  4.78it/s]

Processing tickers:  33%|███▎      | 2272/6932 [08:15<16:13,  4.79it/s]

Processing tickers:  33%|███▎      | 2273/6932 [08:15<16:11,  4.79it/s]

Processing tickers:  33%|███▎      | 2274/6932 [08:15<16:10,  4.80it/s]

Processing tickers:  33%|███▎      | 2275/6932 [08:15<16:30,  4.70it/s]

Processing tickers:  33%|███▎      | 2276/6932 [08:16<16:27,  4.71it/s]

Processing tickers:  33%|███▎      | 2277/6932 [08:16<16:42,  4.64it/s]

Processing tickers:  33%|███▎      | 2278/6932 [08:16<16:32,  4.69it/s]

Processing tickers:  33%|███▎      | 2279/6932 [08:16<16:46,  4.62it/s]

Processing tickers:  33%|███▎      | 2280/6932 [08:16<16:35,  4.67it/s]

Processing tickers:  33%|███▎      | 2281/6932 [08:17<16:30,  4.70it/s]

Processing tickers:  33%|███▎      | 2282/6932 [08:17<16:40,  4.65it/s]

Processing tickers:  33%|███▎      | 2283/6932 [08:17<16:32,  4.68it/s]

Processing tickers:  33%|███▎      | 2284/6932 [08:17<16:35,  4.67it/s]

Processing tickers:  33%|███▎      | 2285/6932 [08:17<16:35,  4.67it/s]

Processing tickers:  33%|███▎      | 2286/6932 [08:18<16:29,  4.69it/s]

Processing tickers:  33%|███▎      | 2287/6932 [08:18<16:18,  4.75it/s]

Processing tickers:  33%|███▎      | 2288/6932 [08:18<16:21,  4.73it/s]

Processing tickers:  33%|███▎      | 2289/6932 [08:18<16:34,  4.67it/s]

Processing tickers:  33%|███▎      | 2290/6932 [08:19<16:22,  4.73it/s]

Processing tickers:  33%|███▎      | 2291/6932 [08:19<16:44,  4.62it/s]

Processing tickers:  33%|███▎      | 2292/6932 [08:19<16:26,  4.71it/s]

Processing tickers:  33%|███▎      | 2293/6932 [08:19<16:20,  4.73it/s]

Processing tickers:  33%|███▎      | 2294/6932 [08:19<16:15,  4.75it/s]

Processing tickers:  33%|███▎      | 2295/6932 [08:20<16:43,  4.62it/s]

Processing tickers:  33%|███▎      | 2296/6932 [08:20<16:25,  4.71it/s]

Processing tickers:  33%|███▎      | 2297/6932 [08:20<16:19,  4.73it/s]

Processing tickers:  33%|███▎      | 2298/6932 [08:20<16:15,  4.75it/s]

Processing tickers:  33%|███▎      | 2299/6932 [08:20<16:12,  4.76it/s]

Processing tickers:  33%|███▎      | 2300/6932 [08:21<16:12,  4.76it/s]

Processing tickers:  33%|███▎      | 2301/6932 [08:21<16:27,  4.69it/s]

Processing tickers:  33%|███▎      | 2302/6932 [08:21<16:26,  4.69it/s]

Processing tickers:  33%|███▎      | 2303/6932 [08:21<16:34,  4.65it/s]

Processing tickers:  33%|███▎      | 2304/6932 [08:22<16:24,  4.70it/s]

Processing tickers:  33%|███▎      | 2305/6932 [08:22<17:03,  4.52it/s]

Processing tickers:  33%|███▎      | 2306/6932 [08:22<16:45,  4.60it/s]

Processing tickers:  33%|███▎      | 2307/6932 [08:22<16:31,  4.66it/s]

Processing tickers:  33%|███▎      | 2308/6932 [08:22<16:23,  4.70it/s]

Processing tickers:  33%|███▎      | 2309/6932 [08:23<16:56,  4.55it/s]

Processing tickers:  33%|███▎      | 2310/6932 [08:23<16:21,  4.71it/s]

Processing tickers:  33%|███▎      | 2311/6932 [08:23<16:34,  4.65it/s]

Processing tickers:  33%|███▎      | 2312/6932 [08:23<16:51,  4.57it/s]

Processing tickers:  33%|███▎      | 2313/6932 [08:23<16:53,  4.56it/s]

Processing tickers:  33%|███▎      | 2314/6932 [08:24<16:38,  4.63it/s]

Processing tickers:  33%|███▎      | 2315/6932 [08:24<16:25,  4.68it/s]

Processing tickers:  33%|███▎      | 2316/6932 [08:24<16:37,  4.63it/s]

Processing tickers:  33%|███▎      | 2317/6932 [08:24<16:22,  4.70it/s]

Processing tickers:  33%|███▎      | 2318/6932 [08:25<16:38,  4.62it/s]

Processing tickers:  33%|███▎      | 2319/6932 [08:25<16:25,  4.68it/s]

Processing tickers:  33%|███▎      | 2320/6932 [08:25<16:28,  4.67it/s]

Processing tickers:  33%|███▎      | 2321/6932 [08:25<16:26,  4.67it/s]

Processing tickers:  33%|███▎      | 2322/6932 [08:25<16:20,  4.70it/s]

Processing tickers:  34%|███▎      | 2323/6932 [08:26<16:12,  4.74it/s]

Processing tickers:  34%|███▎      | 2324/6932 [08:26<16:10,  4.75it/s]

Processing tickers:  34%|███▎      | 2325/6932 [08:26<16:10,  4.75it/s]

Processing tickers:  34%|███▎      | 2326/6932 [08:26<16:00,  4.79it/s]

Processing tickers:  34%|███▎      | 2327/6932 [08:26<16:15,  4.72it/s]

Processing tickers:  34%|███▎      | 2328/6932 [08:27<15:54,  4.82it/s]

Processing tickers:  34%|███▎      | 2329/6932 [08:27<16:16,  4.71it/s]

Processing tickers:  34%|███▎      | 2330/6932 [08:27<16:11,  4.74it/s]

Processing tickers:  34%|███▎      | 2331/6932 [08:27<16:08,  4.75it/s]

Processing tickers:  34%|███▎      | 2332/6932 [08:27<16:04,  4.77it/s]

Processing tickers:  34%|███▎      | 2333/6932 [08:28<16:01,  4.78it/s]

Processing tickers:  34%|███▎      | 2334/6932 [08:28<16:00,  4.79it/s]

Processing tickers:  34%|███▎      | 2335/6932 [08:28<16:21,  4.69it/s]

Processing tickers:  34%|███▎      | 2336/6932 [08:28<16:25,  4.66it/s]

Processing tickers:  34%|███▎      | 2337/6932 [08:29<16:20,  4.69it/s]

Processing tickers:  34%|███▎      | 2338/6932 [08:29<16:18,  4.69it/s]

Processing tickers:  34%|███▎      | 2339/6932 [08:29<16:11,  4.73it/s]

Processing tickers:  34%|███▍      | 2340/6932 [08:29<16:12,  4.72it/s]

Processing tickers:  34%|███▍      | 2341/6932 [08:29<16:00,  4.78it/s]

Processing tickers:  34%|███▍      | 2342/6932 [08:30<16:21,  4.68it/s]

Processing tickers:  34%|███▍      | 2343/6932 [08:30<16:12,  4.72it/s]

Processing tickers:  34%|███▍      | 2344/6932 [08:30<16:29,  4.64it/s]

Processing tickers:  34%|███▍      | 2345/6932 [08:30<16:25,  4.65it/s]

Processing tickers:  34%|███▍      | 2346/6932 [08:30<16:13,  4.71it/s]

Processing tickers:  34%|███▍      | 2347/6932 [08:31<16:03,  4.76it/s]

Processing tickers:  34%|███▍      | 2348/6932 [08:31<16:02,  4.76it/s]

Processing tickers:  34%|███▍      | 2349/6932 [08:31<15:56,  4.79it/s]

Processing tickers:  34%|███▍      | 2350/6932 [08:31<15:59,  4.77it/s]

Processing tickers:  34%|███▍      | 2351/6932 [08:32<15:54,  4.80it/s]

Processing tickers:  34%|███▍      | 2352/6932 [08:32<16:20,  4.67it/s]

Processing tickers:  34%|███▍      | 2353/6932 [08:32<16:08,  4.73it/s]

Processing tickers:  34%|███▍      | 2354/6932 [08:32<16:01,  4.76it/s]

Processing tickers:  34%|███▍      | 2355/6932 [08:32<15:57,  4.78it/s]

Processing tickers:  34%|███▍      | 2356/6932 [08:33<16:17,  4.68it/s]

Processing tickers:  34%|███▍      | 2357/6932 [08:33<16:09,  4.72it/s]

Processing tickers:  34%|███▍      | 2358/6932 [08:33<16:02,  4.75it/s]

Processing tickers:  34%|███▍      | 2359/6932 [08:33<15:58,  4.77it/s]

Processing tickers:  34%|███▍      | 2360/6932 [08:33<15:55,  4.78it/s]

Processing tickers:  34%|███▍      | 2361/6932 [08:34<16:14,  4.69it/s]

Processing tickers:  34%|███▍      | 2362/6932 [08:34<16:07,  4.72it/s]

Processing tickers:  34%|███▍      | 2363/6932 [08:34<15:39,  4.86it/s]

Processing tickers:  34%|███▍      | 2364/6932 [08:34<16:09,  4.71it/s]

Processing tickers:  34%|███▍      | 2365/6932 [08:34<15:58,  4.77it/s]

Processing tickers:  34%|███▍      | 2366/6932 [08:35<15:55,  4.78it/s]

Processing tickers:  34%|███▍      | 2367/6932 [08:35<15:56,  4.77it/s]

Processing tickers:  34%|███▍      | 2368/6932 [08:35<15:52,  4.79it/s]

Processing tickers:  34%|███▍      | 2369/6932 [08:35<15:51,  4.80it/s]

Processing tickers:  34%|███▍      | 2370/6932 [08:36<16:10,  4.70it/s]

Processing tickers:  34%|███▍      | 2371/6932 [08:36<16:28,  4.61it/s]

Processing tickers:  34%|███▍      | 2372/6932 [08:36<16:19,  4.65it/s]

Processing tickers:  34%|███▍      | 2373/6932 [08:36<16:24,  4.63it/s]

Processing tickers:  34%|███▍      | 2374/6932 [08:36<15:51,  4.79it/s]

Processing tickers:  34%|███▍      | 2375/6932 [08:37<15:50,  4.79it/s]

Processing tickers:  34%|███▍      | 2376/6932 [08:37<16:11,  4.69it/s]

Processing tickers:  34%|███▍      | 2377/6932 [08:37<16:04,  4.72it/s]

Processing tickers:  34%|███▍      | 2378/6932 [08:37<16:00,  4.74it/s]

Processing tickers:  34%|███▍      | 2379/6932 [08:37<15:55,  4.77it/s]

Processing tickers:  34%|███▍      | 2380/6932 [08:38<15:53,  4.77it/s]

Processing tickers:  34%|███▍      | 2381/6932 [08:38<16:01,  4.74it/s]

Processing tickers:  34%|███▍      | 2382/6932 [08:38<16:07,  4.70it/s]

Processing tickers:  34%|███▍      | 2383/6932 [08:38<16:08,  4.70it/s]

Processing tickers:  34%|███▍      | 2384/6932 [08:38<16:02,  4.73it/s]

Processing tickers:  34%|███▍      | 2385/6932 [08:39<16:04,  4.72it/s]

Processing tickers:  34%|███▍      | 2386/6932 [08:39<15:43,  4.82it/s]

Processing tickers:  34%|███▍      | 2387/6932 [08:39<15:43,  4.82it/s]

Processing tickers:  34%|███▍      | 2388/6932 [08:39<16:06,  4.70it/s]

Processing tickers:  34%|███▍      | 2389/6932 [08:40<16:08,  4.69it/s]

Processing tickers:  34%|███▍      | 2390/6932 [08:40<16:12,  4.67it/s]

Processing tickers:  34%|███▍      | 2391/6932 [08:40<16:27,  4.60it/s]

Processing tickers:  35%|███▍      | 2392/6932 [08:40<16:16,  4.65it/s]

Processing tickers:  35%|███▍      | 2393/6932 [08:40<16:01,  4.72it/s]

Processing tickers:  35%|███▍      | 2394/6932 [08:41<16:24,  4.61it/s]

Processing tickers:  35%|███▍      | 2395/6932 [08:41<16:28,  4.59it/s]

Processing tickers:  35%|███▍      | 2396/6932 [08:41<16:14,  4.66it/s]

Processing tickers:  35%|███▍      | 2397/6932 [08:41<16:04,  4.70it/s]

Processing tickers:  35%|███▍      | 2398/6932 [08:41<16:33,  4.56it/s]

Processing tickers:  35%|███▍      | 2399/6932 [08:42<16:07,  4.68it/s]

Processing tickers:  35%|███▍      | 2400/6932 [08:42<16:15,  4.64it/s]

Processing tickers:  35%|███▍      | 2401/6932 [08:42<16:10,  4.67it/s]

Processing tickers:  35%|███▍      | 2402/6932 [08:42<16:02,  4.71it/s]

Processing tickers:  35%|███▍      | 2403/6932 [08:43<16:37,  4.54it/s]

Processing tickers:  35%|███▍      | 2404/6932 [08:43<16:22,  4.61it/s]

Processing tickers:  35%|███▍      | 2405/6932 [08:43<16:08,  4.67it/s]

Processing tickers:  35%|███▍      | 2406/6932 [08:43<16:00,  4.71it/s]

Processing tickers:  35%|███▍      | 2407/6932 [08:43<15:54,  4.74it/s]

Processing tickers:  35%|███▍      | 2408/6932 [08:44<16:08,  4.67it/s]

Processing tickers:  35%|███▍      | 2409/6932 [08:44<16:00,  4.71it/s]

Processing tickers:  35%|███▍      | 2410/6932 [08:44<16:19,  4.62it/s]

Processing tickers:  35%|███▍      | 2411/6932 [08:44<16:06,  4.68it/s]

Processing tickers:  35%|███▍      | 2412/6932 [08:44<16:20,  4.61it/s]

Processing tickers:  35%|███▍      | 2413/6932 [08:45<16:28,  4.57it/s]

Processing tickers:  35%|███▍      | 2414/6932 [08:45<16:16,  4.63it/s]

Processing tickers:  35%|███▍      | 2415/6932 [08:45<16:03,  4.69it/s]

Processing tickers:  35%|███▍      | 2416/6932 [08:45<15:55,  4.72it/s]

Processing tickers:  35%|███▍      | 2417/6932 [08:46<15:53,  4.73it/s]

Processing tickers:  35%|███▍      | 2418/6932 [08:46<15:47,  4.76it/s]

Processing tickers:  35%|███▍      | 2419/6932 [08:46<16:17,  4.62it/s]

Processing tickers:  35%|███▍      | 2420/6932 [08:46<15:57,  4.71it/s]

Processing tickers:  35%|███▍      | 2421/6932 [08:46<15:52,  4.74it/s]

Processing tickers:  35%|███▍      | 2422/6932 [08:47<16:01,  4.69it/s]

Processing tickers:  35%|███▍      | 2423/6932 [08:47<15:40,  4.79it/s]

Processing tickers:  35%|███▍      | 2424/6932 [08:47<16:00,  4.69it/s]

Processing tickers:  35%|███▍      | 2425/6932 [08:47<15:56,  4.71it/s]

Processing tickers:  35%|███▍      | 2426/6932 [08:47<15:47,  4.76it/s]

Processing tickers:  35%|███▌      | 2427/6932 [08:48<15:43,  4.77it/s]

Processing tickers:  35%|███▌      | 2428/6932 [08:48<15:42,  4.78it/s]

Processing tickers:  35%|███▌      | 2429/6932 [08:48<15:41,  4.78it/s]

Processing tickers:  35%|███▌      | 2430/6932 [08:48<16:02,  4.68it/s]

Processing tickers:  35%|███▌      | 2431/6932 [08:49<15:54,  4.72it/s]

Processing tickers:  35%|███▌      | 2432/6932 [08:49<16:10,  4.64it/s]

Processing tickers:  35%|███▌      | 2433/6932 [08:49<15:59,  4.69it/s]

Processing tickers:  35%|███▌      | 2434/6932 [08:49<15:52,  4.72it/s]

Processing tickers:  35%|███▌      | 2435/6932 [08:49<16:08,  4.64it/s]

Processing tickers:  35%|███▌      | 2436/6932 [08:50<15:58,  4.69it/s]

Processing tickers:  35%|███▌      | 2437/6932 [08:50<15:52,  4.72it/s]

Processing tickers:  35%|███▌      | 2438/6932 [08:50<16:00,  4.68it/s]

Processing tickers:  35%|███▌      | 2439/6932 [08:50<16:01,  4.67it/s]

Processing tickers:  35%|███▌      | 2440/6932 [08:50<16:14,  4.61it/s]

Processing tickers:  35%|███▌      | 2441/6932 [08:51<16:03,  4.66it/s]

Processing tickers:  35%|███▌      | 2442/6932 [08:51<15:54,  4.70it/s]

Processing tickers:  35%|███▌      | 2443/6932 [08:51<16:02,  4.67it/s]

Processing tickers:  35%|███▌      | 2444/6932 [08:51<15:46,  4.74it/s]

Processing tickers:  35%|███▌      | 2445/6932 [08:52<15:58,  4.68it/s]

Processing tickers:  35%|███▌      | 2446/6932 [08:52<16:16,  4.59it/s]

Processing tickers:  35%|███▌      | 2447/6932 [08:52<15:59,  4.67it/s]

Processing tickers:  35%|███▌      | 2448/6932 [08:52<15:51,  4.71it/s]

Processing tickers:  35%|███▌      | 2449/6932 [08:52<15:45,  4.74it/s]

Processing tickers:  35%|███▌      | 2450/6932 [08:53<16:10,  4.62it/s]

Processing tickers:  35%|███▌      | 2451/6932 [08:53<15:57,  4.68it/s]

Processing tickers:  35%|███▌      | 2452/6932 [08:53<15:41,  4.76it/s]

Processing tickers:  35%|███▌      | 2453/6932 [08:53<15:38,  4.77it/s]

Processing tickers:  35%|███▌      | 2454/6932 [08:53<15:34,  4.79it/s]

Processing tickers:  35%|███▌      | 2455/6932 [08:54<15:33,  4.80it/s]

Processing tickers:  35%|███▌      | 2456/6932 [08:54<15:29,  4.81it/s]

Processing tickers:  35%|███▌      | 2457/6932 [08:54<15:48,  4.72it/s]

Processing tickers:  35%|███▌      | 2458/6932 [08:54<16:10,  4.61it/s]

Processing tickers:  35%|███▌      | 2459/6932 [08:54<15:50,  4.70it/s]

Processing tickers:  35%|███▌      | 2460/6932 [08:55<15:47,  4.72it/s]

Processing tickers:  36%|███▌      | 2461/6932 [08:55<15:40,  4.75it/s]

Processing tickers:  36%|███▌      | 2462/6932 [08:55<15:34,  4.78it/s]

Processing tickers:  36%|███▌      | 2463/6932 [08:55<15:34,  4.78it/s]

Processing tickers:  36%|███▌      | 2464/6932 [08:56<15:31,  4.80it/s]

Processing tickers:  36%|███▌      | 2465/6932 [08:56<16:16,  4.58it/s]

Processing tickers:  36%|███▌      | 2466/6932 [08:56<15:58,  4.66it/s]

Processing tickers:  36%|███▌      | 2467/6932 [08:56<15:50,  4.70it/s]

Processing tickers:  36%|███▌      | 2468/6932 [08:56<15:43,  4.73it/s]

Processing tickers:  36%|███▌      | 2469/6932 [08:57<16:01,  4.64it/s]

Processing tickers:  36%|███▌      | 2470/6932 [08:57<15:51,  4.69it/s]

Processing tickers:  36%|███▌      | 2471/6932 [08:57<15:44,  4.72it/s]

Processing tickers:  36%|███▌      | 2472/6932 [08:57<15:39,  4.75it/s]

Processing tickers:  36%|███▌      | 2473/6932 [08:58<23:34,  3.15it/s]

Processing tickers:  36%|███▌      | 2474/6932 [08:58<21:02,  3.53it/s]

Processing tickers:  36%|███▌      | 2475/6932 [08:58<19:36,  3.79it/s]

Processing tickers:  36%|███▌      | 2476/6932 [08:58<18:28,  4.02it/s]

Processing tickers:  36%|███▌      | 2477/6932 [08:59<17:36,  4.22it/s]

Processing tickers:  36%|███▌      | 2478/6932 [08:59<17:02,  4.35it/s]

Processing tickers:  36%|███▌      | 2479/6932 [08:59<16:46,  4.43it/s]

Processing tickers:  36%|███▌      | 2480/6932 [08:59<16:20,  4.54it/s]

Processing tickers:  36%|███▌      | 2481/6932 [08:59<16:06,  4.61it/s]

Processing tickers:  36%|███▌      | 2482/6932 [09:00<15:34,  4.76it/s]

Processing tickers:  36%|███▌      | 2483/6932 [09:00<15:49,  4.69it/s]

Processing tickers:  36%|███▌      | 2484/6932 [09:00<16:04,  4.61it/s]

Processing tickers:  36%|███▌      | 2485/6932 [09:00<15:53,  4.67it/s]

Processing tickers:  36%|███▌      | 2486/6932 [09:01<15:43,  4.71it/s]

Processing tickers:  36%|███▌      | 2487/6932 [09:01<15:38,  4.74it/s]

Processing tickers:  36%|███▌      | 2488/6932 [09:01<15:54,  4.65it/s]

Processing tickers:  36%|███▌      | 2489/6932 [09:01<15:48,  4.68it/s]

Processing tickers:  36%|███▌      | 2490/6932 [09:01<15:44,  4.70it/s]

Processing tickers:  36%|███▌      | 2491/6932 [09:02<15:36,  4.74it/s]

Processing tickers:  36%|███▌      | 2492/6932 [09:02<15:26,  4.79it/s]

Processing tickers:  36%|███▌      | 2493/6932 [09:02<15:25,  4.80it/s]

Processing tickers:  36%|███▌      | 2494/6932 [09:02<15:24,  4.80it/s]

Processing tickers:  36%|███▌      | 2495/6932 [09:02<15:23,  4.81it/s]

Processing tickers:  36%|███▌      | 2496/6932 [09:03<15:55,  4.64it/s]

Processing tickers:  36%|███▌      | 2497/6932 [09:03<15:34,  4.75it/s]

Processing tickers:  36%|███▌      | 2498/6932 [09:03<15:50,  4.67it/s]

Processing tickers:  36%|███▌      | 2499/6932 [09:03<15:41,  4.71it/s]

Processing tickers:  36%|███▌      | 2500/6932 [09:03<15:36,  4.73it/s]

Processing tickers:  36%|███▌      | 2501/6932 [09:04<15:31,  4.76it/s]

Processing tickers:  36%|███▌      | 2502/6932 [09:04<15:32,  4.75it/s]

Processing tickers:  36%|███▌      | 2503/6932 [09:04<15:25,  4.79it/s]

Processing tickers:  36%|███▌      | 2504/6932 [09:04<15:41,  4.70it/s]

Processing tickers:  36%|███▌      | 2505/6932 [09:05<15:32,  4.75it/s]

Processing tickers:  36%|███▌      | 2506/6932 [09:05<15:11,  4.86it/s]

Processing tickers:  36%|███▌      | 2507/6932 [09:05<15:34,  4.74it/s]

Processing tickers:  36%|███▌      | 2508/6932 [09:05<15:48,  4.67it/s]

Processing tickers:  36%|███▌      | 2509/6932 [09:05<15:59,  4.61it/s]

Processing tickers:  36%|███▌      | 2510/6932 [09:06<15:46,  4.67it/s]

Processing tickers:  36%|███▌      | 2511/6932 [09:06<15:37,  4.72it/s]

Processing tickers:  36%|███▌      | 2512/6932 [09:06<15:31,  4.75it/s]

Processing tickers:  36%|███▋      | 2513/6932 [09:06<15:27,  4.76it/s]

Processing tickers:  36%|███▋      | 2514/6932 [09:06<15:41,  4.69it/s]

Processing tickers:  36%|███▋      | 2515/6932 [09:07<15:39,  4.70it/s]

Processing tickers:  36%|███▋      | 2516/6932 [09:07<15:39,  4.70it/s]

Processing tickers:  36%|███▋      | 2517/6932 [09:07<15:34,  4.72it/s]

Processing tickers:  36%|███▋      | 2518/6932 [09:07<15:42,  4.69it/s]

Processing tickers:  36%|███▋      | 2519/6932 [09:08<15:34,  4.72it/s]

Processing tickers:  36%|███▋      | 2520/6932 [09:08<15:50,  4.64it/s]

Processing tickers:  36%|███▋      | 2521/6932 [09:08<15:40,  4.69it/s]

Processing tickers:  36%|███▋      | 2522/6932 [09:08<15:35,  4.72it/s]

Processing tickers:  36%|███▋      | 2523/6932 [09:08<15:27,  4.75it/s]

Processing tickers:  36%|███▋      | 2524/6932 [09:09<15:33,  4.72it/s]

Processing tickers:  36%|███▋      | 2525/6932 [09:09<15:18,  4.80it/s]

Processing tickers:  36%|███▋      | 2526/6932 [09:09<15:18,  4.80it/s]

Processing tickers:  36%|███▋      | 2527/6932 [09:09<15:34,  4.71it/s]

Processing tickers:  36%|███▋      | 2528/6932 [09:09<15:32,  4.72it/s]

Processing tickers:  36%|███▋      | 2529/6932 [09:10<15:26,  4.75it/s]

Processing tickers:  36%|███▋      | 2530/6932 [09:10<15:22,  4.77it/s]

Processing tickers:  37%|███▋      | 2531/6932 [09:10<15:20,  4.78it/s]

Processing tickers:  37%|███▋      | 2532/6932 [09:10<15:57,  4.60it/s]

Processing tickers:  37%|███▋      | 2533/6932 [09:10<15:50,  4.63it/s]

Processing tickers:  37%|███▋      | 2534/6932 [09:11<15:35,  4.70it/s]

Processing tickers:  37%|███▋      | 2535/6932 [09:11<15:29,  4.73it/s]

Processing tickers:  37%|███▋      | 2536/6932 [09:11<15:37,  4.69it/s]

Processing tickers:  37%|███▋      | 2537/6932 [09:11<15:17,  4.79it/s]

Processing tickers:  37%|███▋      | 2538/6932 [09:12<15:15,  4.80it/s]

Processing tickers:  37%|███▋      | 2539/6932 [09:12<15:36,  4.69it/s]

Processing tickers:  37%|███▋      | 2540/6932 [09:12<15:30,  4.72it/s]

Processing tickers:  37%|███▋      | 2541/6932 [09:12<15:25,  4.75it/s]

Processing tickers:  37%|███▋      | 2542/6932 [09:12<15:44,  4.65it/s]

Processing tickers:  37%|███▋      | 2543/6932 [09:13<15:33,  4.70it/s]

Processing tickers:  37%|███▋      | 2544/6932 [09:13<15:27,  4.73it/s]

Processing tickers:  37%|███▋      | 2545/6932 [09:13<15:22,  4.76it/s]

Processing tickers:  37%|███▋      | 2546/6932 [09:13<15:18,  4.77it/s]

Processing tickers:  37%|███▋      | 2547/6932 [09:13<15:16,  4.79it/s]

Processing tickers:  37%|███▋      | 2548/6932 [09:14<15:14,  4.80it/s]

Processing tickers:  37%|███▋      | 2549/6932 [09:14<15:34,  4.69it/s]

Processing tickers:  37%|███▋      | 2550/6932 [09:14<15:39,  4.66it/s]

Processing tickers:  37%|███▋      | 2551/6932 [09:14<15:20,  4.76it/s]

Processing tickers:  37%|███▋      | 2552/6932 [09:14<15:17,  4.78it/s]

Processing tickers:  37%|███▋      | 2553/6932 [09:15<15:36,  4.68it/s]

Processing tickers:  37%|███▋      | 2554/6932 [09:15<15:50,  4.61it/s]

Processing tickers:  37%|███▋      | 2555/6932 [09:15<15:38,  4.66it/s]

Processing tickers:  37%|███▋      | 2556/6932 [09:15<15:51,  4.60it/s]

Processing tickers:  37%|███▋      | 2557/6932 [09:16<15:38,  4.66it/s]

Processing tickers:  37%|███▋      | 2558/6932 [09:16<15:30,  4.70it/s]

Processing tickers:  37%|███▋      | 2559/6932 [09:16<15:44,  4.63it/s]

Processing tickers:  37%|███▋      | 2560/6932 [09:16<15:13,  4.78it/s]

Processing tickers:  37%|███▋      | 2561/6932 [09:16<15:32,  4.69it/s]

Processing tickers:  37%|███▋      | 2562/6932 [09:17<15:25,  4.72it/s]

Processing tickers:  37%|███▋      | 2563/6932 [09:17<15:20,  4.75it/s]

Processing tickers:  37%|███▋      | 2564/6932 [09:17<15:26,  4.71it/s]

Processing tickers:  37%|███▋      | 2565/6932 [09:17<15:12,  4.79it/s]

Processing tickers:  37%|███▋      | 2566/6932 [09:17<15:24,  4.72it/s]

Processing tickers:  37%|███▋      | 2567/6932 [09:18<15:09,  4.80it/s]

Processing tickers:  37%|███▋      | 2568/6932 [09:18<15:26,  4.71it/s]

Processing tickers:  37%|███▋      | 2569/6932 [09:18<15:19,  4.75it/s]

Processing tickers:  37%|███▋      | 2570/6932 [09:18<15:14,  4.77it/s]

Processing tickers:  37%|███▋      | 2571/6932 [09:19<15:11,  4.78it/s]

Processing tickers:  37%|███▋      | 2572/6932 [09:19<15:31,  4.68it/s]

Processing tickers:  37%|███▋      | 2573/6932 [09:19<15:24,  4.71it/s]

Processing tickers:  37%|███▋      | 2574/6932 [09:19<15:19,  4.74it/s]

Processing tickers:  37%|███▋      | 2575/6932 [09:19<15:44,  4.61it/s]

Processing tickers:  37%|███▋      | 2576/6932 [09:20<15:23,  4.72it/s]

Processing tickers:  37%|███▋      | 2577/6932 [09:20<15:18,  4.74it/s]

Processing tickers:  37%|███▋      | 2578/6932 [09:20<15:14,  4.76it/s]

Processing tickers:  37%|███▋      | 2579/6932 [09:20<15:14,  4.76it/s]

Processing tickers:  37%|███▋      | 2580/6932 [09:20<15:30,  4.68it/s]

Processing tickers:  37%|███▋      | 2581/6932 [09:21<15:22,  4.72it/s]

Processing tickers:  37%|███▋      | 2582/6932 [09:21<15:16,  4.75it/s]

Processing tickers:  37%|███▋      | 2583/6932 [09:21<15:26,  4.70it/s]

Processing tickers:  37%|███▋      | 2584/6932 [09:21<15:36,  4.64it/s]

Processing tickers:  37%|███▋      | 2585/6932 [09:22<15:16,  4.74it/s]

Processing tickers:  37%|███▋      | 2586/6932 [09:22<15:35,  4.64it/s]

Processing tickers:  37%|███▋      | 2587/6932 [09:22<15:34,  4.65it/s]

Processing tickers:  37%|███▋      | 2588/6932 [09:22<15:23,  4.70it/s]

Processing tickers:  37%|███▋      | 2589/6932 [09:22<15:13,  4.75it/s]

Processing tickers:  37%|███▋      | 2590/6932 [09:23<15:06,  4.79it/s]

Processing tickers:  37%|███▋      | 2591/6932 [09:23<15:05,  4.80it/s]

Processing tickers:  37%|███▋      | 2592/6932 [09:23<15:05,  4.79it/s]

Processing tickers:  37%|███▋      | 2593/6932 [09:23<15:17,  4.73it/s]

Processing tickers:  37%|███▋      | 2594/6932 [09:23<15:00,  4.82it/s]

Processing tickers:  37%|███▋      | 2595/6932 [09:24<15:13,  4.75it/s]

Processing tickers:  37%|███▋      | 2596/6932 [09:24<15:20,  4.71it/s]

Processing tickers:  37%|███▋      | 2597/6932 [09:24<15:11,  4.75it/s]

Processing tickers:  37%|███▋      | 2598/6932 [09:24<15:01,  4.81it/s]

Processing tickers:  37%|███▋      | 2599/6932 [09:24<15:08,  4.77it/s]

Processing tickers:  38%|███▊      | 2600/6932 [09:25<15:03,  4.79it/s]

Processing tickers:  38%|███▊      | 2601/6932 [09:25<15:21,  4.70it/s]

Processing tickers:  38%|███▊      | 2602/6932 [09:25<15:50,  4.55it/s]

Processing tickers:  38%|███▊      | 2603/6932 [09:25<15:39,  4.61it/s]

Processing tickers:  38%|███▊      | 2604/6932 [09:26<15:27,  4.67it/s]

Processing tickers:  38%|███▊      | 2605/6932 [09:26<15:40,  4.60it/s]

Processing tickers:  38%|███▊      | 2606/6932 [09:26<15:29,  4.65it/s]

Processing tickers:  38%|███▊      | 2607/6932 [09:26<15:22,  4.69it/s]

Processing tickers:  38%|███▊      | 2608/6932 [09:26<16:13,  4.44it/s]

Processing tickers:  38%|███▊      | 2609/6932 [09:27<15:51,  4.54it/s]

Processing tickers:  38%|███▊      | 2610/6932 [09:27<15:47,  4.56it/s]

Processing tickers:  38%|███▊      | 2611/6932 [09:27<15:20,  4.69it/s]

Processing tickers:  38%|███▊      | 2612/6932 [09:27<16:00,  4.50it/s]

Processing tickers:  38%|███▊      | 2613/6932 [09:28<15:36,  4.61it/s]

Processing tickers:  38%|███▊      | 2614/6932 [09:28<15:25,  4.67it/s]

Processing tickers:  38%|███▊      | 2615/6932 [09:28<15:18,  4.70it/s]

Processing tickers:  38%|███▊      | 2616/6932 [09:28<15:12,  4.73it/s]

Processing tickers:  38%|███▊      | 2617/6932 [09:28<15:27,  4.65it/s]

Processing tickers:  38%|███▊      | 2618/6932 [09:29<15:18,  4.70it/s]

Processing tickers:  38%|███▊      | 2619/6932 [09:29<15:12,  4.73it/s]

Processing tickers:  38%|███▊      | 2620/6932 [09:29<15:29,  4.64it/s]

Processing tickers:  38%|███▊      | 2621/6932 [09:29<15:19,  4.69it/s]

Processing tickers:  38%|███▊      | 2622/6932 [09:29<15:46,  4.55it/s]

Processing tickers:  38%|███▊      | 2623/6932 [09:30<15:15,  4.71it/s]

Processing tickers:  38%|███▊      | 2624/6932 [09:30<15:11,  4.73it/s]

Processing tickers:  38%|███▊      | 2625/6932 [09:30<15:14,  4.71it/s]

Processing tickers:  38%|███▊      | 2626/6932 [09:30<15:02,  4.77it/s]

Processing tickers:  38%|███▊      | 2627/6932 [09:30<14:59,  4.79it/s]

Processing tickers:  38%|███▊      | 2628/6932 [09:31<15:14,  4.70it/s]

Processing tickers:  38%|███▊      | 2629/6932 [09:31<15:10,  4.73it/s]

Processing tickers:  38%|███▊      | 2630/6932 [09:31<15:05,  4.75it/s]

Processing tickers:  38%|███▊      | 2631/6932 [09:31<15:05,  4.75it/s]

Processing tickers:  38%|███▊      | 2632/6932 [09:32<15:00,  4.78it/s]

Processing tickers:  38%|███▊      | 2633/6932 [09:32<15:18,  4.68it/s]

Processing tickers:  38%|███▊      | 2634/6932 [09:32<15:10,  4.72it/s]

Processing tickers:  38%|███▊      | 2635/6932 [09:32<15:26,  4.64it/s]

Processing tickers:  38%|███▊      | 2636/6932 [09:32<15:41,  4.56it/s]

Processing tickers:  38%|███▊      | 2637/6932 [09:33<15:21,  4.66it/s]

Processing tickers:  38%|███▊      | 2638/6932 [09:33<15:18,  4.68it/s]

Processing tickers:  38%|███▊      | 2639/6932 [09:33<15:05,  4.74it/s]

Processing tickers:  38%|███▊      | 2640/6932 [09:33<15:23,  4.65it/s]

Processing tickers:  38%|███▊      | 2641/6932 [09:33<15:14,  4.69it/s]

Processing tickers:  38%|███▊      | 2642/6932 [09:34<15:07,  4.73it/s]

Processing tickers:  38%|███▊      | 2643/6932 [09:34<15:02,  4.75it/s]

Processing tickers:  38%|███▊      | 2644/6932 [09:34<15:24,  4.64it/s]

Processing tickers:  38%|███▊      | 2645/6932 [09:34<15:13,  4.69it/s]

Processing tickers:  38%|███▊      | 2646/6932 [09:35<15:04,  4.74it/s]

Processing tickers:  38%|███▊      | 2647/6932 [09:35<14:59,  4.76it/s]

Processing tickers:  38%|███▊      | 2648/6932 [09:35<15:18,  4.67it/s]

Processing tickers:  38%|███▊      | 2649/6932 [09:35<15:09,  4.71it/s]

Processing tickers:  38%|███▊      | 2650/6932 [09:35<15:09,  4.71it/s]

Processing tickers:  38%|███▊      | 2651/6932 [09:36<15:02,  4.75it/s]

Processing tickers:  38%|███▊      | 2652/6932 [09:36<14:52,  4.80it/s]

Processing tickers:  38%|███▊      | 2653/6932 [09:36<15:08,  4.71it/s]

Processing tickers:  38%|███▊      | 2654/6932 [09:36<15:17,  4.66it/s]

Processing tickers:  38%|███▊      | 2655/6932 [09:36<14:55,  4.77it/s]

Processing tickers:  38%|███▊      | 2656/6932 [09:37<14:53,  4.78it/s]

Processing tickers:  38%|███▊      | 2657/6932 [09:37<15:13,  4.68it/s]

Processing tickers:  38%|███▊      | 2658/6932 [09:37<15:05,  4.72it/s]

Processing tickers:  38%|███▊      | 2659/6932 [09:37<15:00,  4.75it/s]

Processing tickers:  38%|███▊      | 2660/6932 [09:37<15:16,  4.66it/s]

Processing tickers:  38%|███▊      | 2661/6932 [09:38<15:51,  4.49it/s]

Processing tickers:  38%|███▊      | 2662/6932 [09:38<15:30,  4.59it/s]

Processing tickers:  38%|███▊      | 2663/6932 [09:38<15:36,  4.56it/s]

Processing tickers:  38%|███▊      | 2664/6932 [09:38<15:26,  4.61it/s]

Processing tickers:  38%|███▊      | 2665/6932 [09:39<15:30,  4.59it/s]

Processing tickers:  38%|███▊      | 2666/6932 [09:39<15:17,  4.65it/s]

Processing tickers:  38%|███▊      | 2667/6932 [09:39<14:48,  4.80it/s]

Processing tickers:  38%|███▊      | 2668/6932 [09:39<15:08,  4.69it/s]

Processing tickers:  39%|███▊      | 2669/6932 [09:39<15:10,  4.68it/s]

Processing tickers:  39%|███▊      | 2670/6932 [09:40<14:54,  4.77it/s]

Processing tickers:  39%|███▊      | 2671/6932 [09:40<14:52,  4.78it/s]

Processing tickers:  39%|███▊      | 2672/6932 [09:40<14:50,  4.78it/s]

Processing tickers:  39%|███▊      | 2673/6932 [09:40<14:49,  4.79it/s]

Processing tickers:  39%|███▊      | 2674/6932 [09:40<14:48,  4.79it/s]

Processing tickers:  39%|███▊      | 2675/6932 [09:41<14:47,  4.79it/s]

Processing tickers:  39%|███▊      | 2676/6932 [09:41<15:13,  4.66it/s]

Processing tickers:  39%|███▊      | 2677/6932 [09:41<15:26,  4.59it/s]

Processing tickers:  39%|███▊      | 2678/6932 [09:41<15:07,  4.69it/s]

Processing tickers:  39%|███▊      | 2679/6932 [09:42<15:11,  4.67it/s]

Processing tickers:  39%|███▊      | 2680/6932 [09:42<15:13,  4.66it/s]

Processing tickers:  39%|███▊      | 2681/6932 [09:42<15:02,  4.71it/s]

Processing tickers:  39%|███▊      | 2682/6932 [09:42<14:53,  4.75it/s]

Processing tickers:  39%|███▊      | 2683/6932 [09:42<14:50,  4.77it/s]

Processing tickers:  39%|███▊      | 2684/6932 [09:43<15:09,  4.67it/s]

Processing tickers:  39%|███▊      | 2685/6932 [09:43<15:02,  4.71it/s]

Processing tickers:  39%|███▊      | 2686/6932 [09:43<14:55,  4.74it/s]

Processing tickers:  39%|███▉      | 2687/6932 [09:43<14:52,  4.76it/s]

Processing tickers:  39%|███▉      | 2688/6932 [09:43<14:50,  4.77it/s]

Processing tickers:  39%|███▉      | 2689/6932 [09:44<14:55,  4.74it/s]

Processing tickers:  39%|███▉      | 2690/6932 [09:44<14:45,  4.79it/s]

Processing tickers:  39%|███▉      | 2691/6932 [09:44<14:50,  4.76it/s]

Processing tickers:  39%|███▉      | 2692/6932 [09:44<14:41,  4.81it/s]

Processing tickers:  39%|███▉      | 2693/6932 [09:44<15:02,  4.70it/s]

Processing tickers:  39%|███▉      | 2694/6932 [09:45<15:22,  4.60it/s]

Processing tickers:  39%|███▉      | 2695/6932 [09:45<15:04,  4.69it/s]

Processing tickers:  39%|███▉      | 2696/6932 [09:45<15:13,  4.64it/s]

Processing tickers:  39%|███▉      | 2697/6932 [09:45<15:10,  4.65it/s]

Processing tickers:  39%|███▉      | 2698/6932 [09:46<14:59,  4.71it/s]

Processing tickers:  39%|███▉      | 2699/6932 [09:46<14:53,  4.74it/s]

Processing tickers:  39%|███▉      | 2700/6932 [09:46<15:00,  4.70it/s]

Processing tickers:  39%|███▉      | 2701/6932 [09:46<14:42,  4.79it/s]

Processing tickers:  39%|███▉      | 2702/6932 [09:46<14:42,  4.80it/s]

Processing tickers:  39%|███▉      | 2703/6932 [09:47<14:42,  4.79it/s]

Processing tickers:  39%|███▉      | 2704/6932 [09:47<14:51,  4.74it/s]

Processing tickers:  39%|███▉      | 2705/6932 [09:47<15:06,  4.66it/s]

Processing tickers:  39%|███▉      | 2706/6932 [09:47<14:48,  4.76it/s]

Processing tickers:  39%|███▉      | 2707/6932 [09:47<15:04,  4.67it/s]

Processing tickers:  39%|███▉      | 2708/6932 [09:48<15:23,  4.58it/s]

Processing tickers:  39%|███▉      | 2709/6932 [09:48<15:22,  4.58it/s]

Processing tickers:  39%|███▉      | 2710/6932 [09:48<15:10,  4.64it/s]

Processing tickers:  39%|███▉      | 2711/6932 [09:48<14:59,  4.69it/s]

Processing tickers:  39%|███▉      | 2712/6932 [09:49<14:51,  4.73it/s]

Processing tickers:  39%|███▉      | 2713/6932 [09:49<14:48,  4.75it/s]

Processing tickers:  39%|███▉      | 2714/6932 [09:49<14:47,  4.75it/s]

Processing tickers:  39%|███▉      | 2715/6932 [09:49<14:48,  4.74it/s]

Processing tickers:  39%|███▉      | 2716/6932 [09:49<14:42,  4.78it/s]

Processing tickers:  39%|███▉      | 2717/6932 [09:50<14:45,  4.76it/s]

Processing tickers:  39%|███▉      | 2718/6932 [09:50<14:54,  4.71it/s]

Processing tickers:  39%|███▉      | 2719/6932 [09:50<14:53,  4.72it/s]

Processing tickers:  39%|███▉      | 2720/6932 [09:50<15:01,  4.67it/s]

Processing tickers:  39%|███▉      | 2721/6932 [09:50<14:52,  4.72it/s]

Processing tickers:  39%|███▉      | 2722/6932 [09:51<14:31,  4.83it/s]

Processing tickers:  39%|███▉      | 2723/6932 [09:51<14:52,  4.72it/s]

Processing tickers:  39%|███▉      | 2724/6932 [09:51<14:46,  4.74it/s]

Processing tickers:  39%|███▉      | 2725/6932 [09:51<15:03,  4.66it/s]

Processing tickers:  39%|███▉      | 2726/6932 [09:52<14:56,  4.69it/s]

Processing tickers:  39%|███▉      | 2727/6932 [09:52<15:30,  4.52it/s]

Processing tickers:  39%|███▉      | 2728/6932 [09:52<15:13,  4.60it/s]

Processing tickers:  39%|███▉      | 2729/6932 [09:52<15:01,  4.66it/s]

Processing tickers:  39%|███▉      | 2730/6932 [09:52<14:53,  4.71it/s]

Processing tickers:  39%|███▉      | 2731/6932 [09:53<14:47,  4.74it/s]

Processing tickers:  39%|███▉      | 2732/6932 [09:53<14:47,  4.73it/s]

Processing tickers:  39%|███▉      | 2733/6932 [09:53<15:00,  4.66it/s]

Processing tickers:  39%|███▉      | 2734/6932 [09:53<14:52,  4.71it/s]

Processing tickers:  39%|███▉      | 2735/6932 [09:53<14:47,  4.73it/s]

Processing tickers:  39%|███▉      | 2736/6932 [09:54<14:40,  4.76it/s]

Processing tickers:  39%|███▉      | 2737/6932 [09:54<14:59,  4.67it/s]

Processing tickers:  39%|███▉      | 2738/6932 [09:54<14:57,  4.67it/s]

Processing tickers:  40%|███▉      | 2739/6932 [09:54<14:42,  4.75it/s]

Processing tickers:  40%|███▉      | 2740/6932 [09:54<14:37,  4.78it/s]

Processing tickers:  40%|███▉      | 2741/6932 [09:55<14:52,  4.69it/s]

Processing tickers:  40%|███▉      | 2742/6932 [09:55<15:05,  4.63it/s]

Processing tickers:  40%|███▉      | 2743/6932 [09:55<14:55,  4.68it/s]

Processing tickers:  40%|███▉      | 2744/6932 [09:55<14:48,  4.71it/s]

Processing tickers:  40%|███▉      | 2745/6932 [09:56<14:42,  4.74it/s]

Processing tickers:  40%|███▉      | 2746/6932 [09:56<14:39,  4.76it/s]

Processing tickers:  40%|███▉      | 2747/6932 [09:56<14:57,  4.66it/s]

Processing tickers:  40%|███▉      | 2748/6932 [09:56<14:52,  4.69it/s]

Processing tickers:  40%|███▉      | 2749/6932 [09:56<14:59,  4.65it/s]

Processing tickers:  40%|███▉      | 2750/6932 [09:57<14:57,  4.66it/s]

Processing tickers:  40%|███▉      | 2751/6932 [09:57<15:09,  4.60it/s]

Processing tickers:  40%|███▉      | 2752/6932 [09:57<15:11,  4.59it/s]

Processing tickers:  40%|███▉      | 2753/6932 [09:57<14:45,  4.72it/s]

Processing tickers:  40%|███▉      | 2754/6932 [09:57<15:00,  4.64it/s]

Processing tickers:  40%|███▉      | 2755/6932 [09:58<14:56,  4.66it/s]

Processing tickers:  40%|███▉      | 2756/6932 [09:58<14:47,  4.70it/s]

Processing tickers:  40%|███▉      | 2757/6932 [09:58<14:36,  4.76it/s]

Processing tickers:  40%|███▉      | 2758/6932 [09:58<14:34,  4.78it/s]

Processing tickers:  40%|███▉      | 2759/6932 [09:59<14:37,  4.76it/s]

Processing tickers:  40%|███▉      | 2760/6932 [09:59<14:30,  4.79it/s]

Processing tickers:  40%|███▉      | 2761/6932 [09:59<14:30,  4.79it/s]

Processing tickers:  40%|███▉      | 2762/6932 [09:59<14:41,  4.73it/s]

Processing tickers:  40%|███▉      | 2763/6932 [09:59<14:37,  4.75it/s]

Processing tickers:  40%|███▉      | 2764/6932 [10:00<14:20,  4.84it/s]

Processing tickers:  40%|███▉      | 2765/6932 [10:00<14:21,  4.83it/s]

Processing tickers:  40%|███▉      | 2766/6932 [10:00<14:22,  4.83it/s]

Processing tickers:  40%|███▉      | 2767/6932 [10:00<14:42,  4.72it/s]

Processing tickers:  40%|███▉      | 2768/6932 [10:00<14:38,  4.74it/s]

Processing tickers:  40%|███▉      | 2769/6932 [10:01<14:36,  4.75it/s]

Processing tickers:  40%|███▉      | 2770/6932 [10:01<14:52,  4.66it/s]

Processing tickers:  40%|███▉      | 2771/6932 [10:01<14:48,  4.68it/s]

Processing tickers:  40%|███▉      | 2772/6932 [10:01<14:36,  4.75it/s]

Processing tickers:  40%|████      | 2773/6932 [10:01<14:33,  4.76it/s]

Processing tickers:  40%|████      | 2774/6932 [10:02<14:33,  4.76it/s]

Processing tickers:  40%|████      | 2775/6932 [10:02<14:27,  4.79it/s]

Processing tickers:  40%|████      | 2776/6932 [10:02<14:42,  4.71it/s]

Processing tickers:  40%|████      | 2777/6932 [10:02<14:41,  4.72it/s]

Processing tickers:  40%|████      | 2778/6932 [10:03<14:53,  4.65it/s]

Processing tickers:  40%|████      | 2779/6932 [10:03<15:03,  4.60it/s]

Processing tickers:  40%|████      | 2780/6932 [10:03<15:01,  4.61it/s]

Processing tickers:  40%|████      | 2781/6932 [10:03<15:00,  4.61it/s]

Processing tickers:  40%|████      | 2782/6932 [10:03<15:10,  4.56it/s]

Processing tickers:  40%|████      | 2783/6932 [10:04<15:11,  4.55it/s]

Processing tickers:  40%|████      | 2784/6932 [10:04<15:13,  4.54it/s]

Processing tickers:  40%|████      | 2785/6932 [10:04<14:57,  4.62it/s]

Processing tickers:  40%|████      | 2786/6932 [10:04<14:47,  4.67it/s]

Processing tickers:  40%|████      | 2787/6932 [10:04<14:28,  4.77it/s]

Processing tickers:  40%|████      | 2788/6932 [10:05<14:46,  4.67it/s]

Processing tickers:  40%|████      | 2789/6932 [10:05<14:39,  4.71it/s]

Processing tickers:  40%|████      | 2790/6932 [10:05<14:46,  4.67it/s]

Processing tickers:  40%|████      | 2791/6932 [10:05<14:40,  4.70it/s]

Processing tickers:  40%|████      | 2792/6932 [10:06<14:21,  4.81it/s]

Processing tickers:  40%|████      | 2793/6932 [10:06<14:24,  4.79it/s]

Processing tickers:  40%|████      | 2794/6932 [10:06<14:40,  4.70it/s]

Processing tickers:  40%|████      | 2795/6932 [10:06<14:13,  4.85it/s]

Processing tickers:  40%|████      | 2796/6932 [10:06<14:36,  4.72it/s]

Processing tickers:  40%|████      | 2797/6932 [10:07<14:28,  4.76it/s]

Processing tickers:  40%|████      | 2798/6932 [10:07<14:23,  4.79it/s]

Processing tickers:  40%|████      | 2799/6932 [10:07<14:22,  4.79it/s]

Processing tickers:  40%|████      | 2800/6932 [10:07<14:21,  4.79it/s]

Processing tickers:  40%|████      | 2801/6932 [10:07<14:42,  4.68it/s]

Processing tickers:  40%|████      | 2802/6932 [10:08<14:40,  4.69it/s]

Processing tickers:  40%|████      | 2803/6932 [10:08<14:42,  4.68it/s]

Processing tickers:  40%|████      | 2804/6932 [10:08<14:41,  4.68it/s]

Processing tickers:  40%|████      | 2805/6932 [10:08<14:32,  4.73it/s]

Processing tickers:  40%|████      | 2806/6932 [10:09<14:35,  4.71it/s]

Processing tickers:  40%|████      | 2807/6932 [10:09<15:02,  4.57it/s]

Processing tickers:  41%|████      | 2808/6932 [10:09<14:57,  4.60it/s]

Processing tickers:  41%|████      | 2809/6932 [10:09<14:53,  4.61it/s]

Processing tickers:  41%|████      | 2810/6932 [10:09<14:52,  4.62it/s]

Processing tickers:  41%|████      | 2811/6932 [10:10<14:35,  4.71it/s]

Processing tickers:  41%|████      | 2812/6932 [10:10<14:29,  4.74it/s]

Processing tickers:  41%|████      | 2813/6932 [10:10<14:25,  4.76it/s]

Processing tickers:  41%|████      | 2814/6932 [10:10<14:23,  4.77it/s]

Processing tickers:  41%|████      | 2815/6932 [10:10<14:20,  4.78it/s]

Processing tickers:  41%|████      | 2816/6932 [10:11<14:20,  4.78it/s]

Processing tickers:  41%|████      | 2817/6932 [10:11<14:36,  4.69it/s]

Processing tickers:  41%|████      | 2818/6932 [10:11<14:30,  4.73it/s]

Processing tickers:  41%|████      | 2819/6932 [10:11<14:26,  4.75it/s]

Processing tickers:  41%|████      | 2820/6932 [10:11<14:25,  4.75it/s]

Processing tickers:  41%|████      | 2821/6932 [10:12<14:18,  4.79it/s]

Processing tickers:  41%|████      | 2822/6932 [10:12<14:35,  4.69it/s]

Processing tickers:  41%|████      | 2823/6932 [10:12<14:12,  4.82it/s]

Processing tickers:  41%|████      | 2824/6932 [10:12<14:30,  4.72it/s]

Processing tickers:  41%|████      | 2825/6932 [10:13<14:37,  4.68it/s]

Processing tickers:  41%|████      | 2826/6932 [10:13<14:19,  4.78it/s]

Processing tickers:  41%|████      | 2827/6932 [10:13<14:17,  4.79it/s]

Processing tickers:  41%|████      | 2828/6932 [10:13<14:42,  4.65it/s]

Processing tickers:  41%|████      | 2829/6932 [10:13<14:42,  4.65it/s]

Processing tickers:  41%|████      | 2830/6932 [10:14<14:35,  4.69it/s]

Processing tickers:  41%|████      | 2831/6932 [10:14<14:32,  4.70it/s]

Processing tickers:  41%|████      | 2832/6932 [10:14<14:44,  4.63it/s]

Processing tickers:  41%|████      | 2833/6932 [10:14<14:34,  4.69it/s]

Processing tickers:  41%|████      | 2834/6932 [10:14<14:31,  4.70it/s]

Processing tickers:  41%|████      | 2835/6932 [10:15<14:26,  4.73it/s]

Processing tickers:  41%|████      | 2836/6932 [10:15<14:24,  4.74it/s]

Processing tickers:  41%|████      | 2837/6932 [10:15<14:16,  4.78it/s]

Processing tickers:  41%|████      | 2838/6932 [10:15<14:13,  4.80it/s]

Processing tickers:  41%|████      | 2839/6932 [10:15<14:12,  4.80it/s]

Processing tickers:  41%|████      | 2840/6932 [10:16<14:12,  4.80it/s]

Processing tickers:  41%|████      | 2841/6932 [10:16<14:29,  4.70it/s]

Processing tickers:  41%|████      | 2842/6932 [10:16<14:24,  4.73it/s]

Processing tickers:  41%|████      | 2843/6932 [10:16<14:20,  4.75it/s]

Processing tickers:  41%|████      | 2844/6932 [10:17<14:16,  4.78it/s]

Processing tickers:  41%|████      | 2845/6932 [10:17<14:33,  4.68it/s]

Processing tickers:  41%|████      | 2846/6932 [10:17<14:25,  4.72it/s]

Processing tickers:  41%|████      | 2847/6932 [10:17<14:20,  4.75it/s]

Processing tickers:  41%|████      | 2848/6932 [10:17<14:18,  4.76it/s]

Processing tickers:  41%|████      | 2849/6932 [10:18<14:14,  4.78it/s]

Processing tickers:  41%|████      | 2850/6932 [10:18<14:31,  4.69it/s]

Processing tickers:  41%|████      | 2851/6932 [10:18<14:28,  4.70it/s]

Processing tickers:  41%|████      | 2852/6932 [10:18<14:18,  4.75it/s]

Processing tickers:  41%|████      | 2853/6932 [10:18<14:17,  4.76it/s]

Processing tickers:  41%|████      | 2854/6932 [10:19<14:18,  4.75it/s]

Processing tickers:  41%|████      | 2855/6932 [10:19<14:30,  4.68it/s]

Processing tickers:  41%|████      | 2856/6932 [10:19<14:24,  4.72it/s]

Processing tickers:  41%|████      | 2857/6932 [10:19<14:19,  4.74it/s]

Processing tickers:  41%|████      | 2858/6932 [10:20<14:35,  4.65it/s]

Processing tickers:  41%|████      | 2859/6932 [10:20<14:27,  4.70it/s]

Processing tickers:  41%|████▏     | 2860/6932 [10:20<14:41,  4.62it/s]

Processing tickers:  41%|████▏     | 2861/6932 [10:20<14:30,  4.68it/s]

Processing tickers:  41%|████▏     | 2862/6932 [10:20<14:26,  4.69it/s]

Processing tickers:  41%|████▏     | 2863/6932 [10:21<14:25,  4.70it/s]

Processing tickers:  41%|████▏     | 2864/6932 [10:21<14:11,  4.78it/s]

Processing tickers:  41%|████▏     | 2865/6932 [10:21<14:29,  4.68it/s]

Processing tickers:  41%|████▏     | 2866/6932 [10:21<14:29,  4.67it/s]

Processing tickers:  41%|████▏     | 2867/6932 [10:21<14:30,  4.67it/s]

Processing tickers:  41%|████▏     | 2868/6932 [10:22<14:08,  4.79it/s]

Processing tickers:  41%|████▏     | 2869/6932 [10:22<14:08,  4.79it/s]

Processing tickers:  41%|████▏     | 2870/6932 [10:22<14:19,  4.72it/s]

Processing tickers:  41%|████▏     | 2871/6932 [10:22<14:23,  4.70it/s]

Processing tickers:  41%|████▏     | 2872/6932 [10:22<14:17,  4.73it/s]

Processing tickers:  41%|████▏     | 2873/6932 [10:23<14:13,  4.76it/s]

Processing tickers:  41%|████▏     | 2874/6932 [10:23<14:09,  4.78it/s]

Processing tickers:  41%|████▏     | 2875/6932 [10:23<14:07,  4.79it/s]

Processing tickers:  41%|████▏     | 2876/6932 [10:23<14:07,  4.79it/s]

Processing tickers:  42%|████▏     | 2877/6932 [10:24<14:05,  4.80it/s]

Processing tickers:  42%|████▏     | 2878/6932 [10:24<14:15,  4.74it/s]

Processing tickers:  42%|████▏     | 2879/6932 [10:24<14:15,  4.74it/s]

Processing tickers:  42%|████▏     | 2880/6932 [10:24<14:08,  4.78it/s]

Processing tickers:  42%|████▏     | 2881/6932 [10:24<15:21,  4.40it/s]

Processing tickers:  42%|████▏     | 2882/6932 [10:25<14:57,  4.51it/s]

Processing tickers:  42%|████▏     | 2883/6932 [10:25<14:44,  4.58it/s]

Processing tickers:  42%|████▏     | 2884/6932 [10:25<14:48,  4.56it/s]

Processing tickers:  42%|████▏     | 2885/6932 [10:25<14:34,  4.63it/s]

Processing tickers:  42%|████▏     | 2886/6932 [10:25<14:24,  4.68it/s]

Processing tickers:  42%|████▏     | 2887/6932 [10:26<14:20,  4.70it/s]

Processing tickers:  42%|████▏     | 2888/6932 [10:26<14:14,  4.73it/s]

Processing tickers:  42%|████▏     | 2889/6932 [10:26<14:25,  4.67it/s]

Processing tickers:  42%|████▏     | 2890/6932 [10:26<14:17,  4.71it/s]

Processing tickers:  42%|████▏     | 2891/6932 [10:27<14:11,  4.75it/s]

Processing tickers:  42%|████▏     | 2892/6932 [10:27<14:27,  4.66it/s]

Processing tickers:  42%|████▏     | 2893/6932 [10:27<14:18,  4.70it/s]

Processing tickers:  42%|████▏     | 2894/6932 [10:27<14:13,  4.73it/s]

Processing tickers:  42%|████▏     | 2895/6932 [10:27<14:09,  4.75it/s]

Processing tickers:  42%|████▏     | 2896/6932 [10:28<14:25,  4.66it/s]

Processing tickers:  42%|████▏     | 2897/6932 [10:28<14:17,  4.70it/s]

Processing tickers:  42%|████▏     | 2898/6932 [10:28<14:12,  4.73it/s]

Processing tickers:  42%|████▏     | 2899/6932 [10:28<14:27,  4.65it/s]

Processing tickers:  42%|████▏     | 2900/6932 [10:28<14:17,  4.70it/s]

Processing tickers:  42%|████▏     | 2901/6932 [10:29<14:13,  4.72it/s]

Processing tickers:  42%|████▏     | 2902/6932 [10:29<14:24,  4.66it/s]

Processing tickers:  42%|████▏     | 2903/6932 [10:29<14:17,  4.70it/s]

Processing tickers:  42%|████▏     | 2904/6932 [10:29<14:11,  4.73it/s]

Processing tickers:  42%|████▏     | 2905/6932 [10:30<14:08,  4.75it/s]

Processing tickers:  42%|████▏     | 2906/6932 [10:30<14:41,  4.57it/s]

Processing tickers:  42%|████▏     | 2907/6932 [10:30<14:11,  4.73it/s]

Processing tickers:  42%|████▏     | 2908/6932 [10:30<14:25,  4.65it/s]

Processing tickers:  42%|████▏     | 2909/6932 [10:30<14:16,  4.70it/s]

Processing tickers:  42%|████▏     | 2910/6932 [10:31<14:08,  4.74it/s]

Processing tickers:  42%|████▏     | 2911/6932 [10:31<14:05,  4.76it/s]

Processing tickers:  42%|████▏     | 2912/6932 [10:31<14:21,  4.67it/s]

Processing tickers:  42%|████▏     | 2913/6932 [10:31<14:15,  4.70it/s]

Processing tickers:  42%|████▏     | 2914/6932 [10:31<14:07,  4.74it/s]

Processing tickers:  42%|████▏     | 2915/6932 [10:32<14:27,  4.63it/s]

Processing tickers:  42%|████▏     | 2916/6932 [10:32<14:14,  4.70it/s]

Processing tickers:  42%|████▏     | 2917/6932 [10:32<14:08,  4.73it/s]

Processing tickers:  42%|████▏     | 2918/6932 [10:32<14:05,  4.75it/s]

Processing tickers:  42%|████▏     | 2919/6932 [10:33<14:02,  4.77it/s]

Processing tickers:  42%|████▏     | 2920/6932 [10:33<14:24,  4.64it/s]

Processing tickers:  42%|████▏     | 2921/6932 [10:33<14:06,  4.74it/s]

Processing tickers:  42%|████▏     | 2922/6932 [10:33<14:02,  4.76it/s]

Processing tickers:  42%|████▏     | 2923/6932 [10:33<13:59,  4.78it/s]

Processing tickers:  42%|████▏     | 2924/6932 [10:34<13:57,  4.78it/s]

Processing tickers:  42%|████▏     | 2925/6932 [10:34<14:15,  4.68it/s]

Processing tickers:  42%|████▏     | 2926/6932 [10:34<14:08,  4.72it/s]

Processing tickers:  42%|████▏     | 2927/6932 [10:34<14:03,  4.75it/s]

Processing tickers:  42%|████▏     | 2928/6932 [10:34<14:00,  4.77it/s]

Processing tickers:  42%|████▏     | 2929/6932 [10:35<13:57,  4.78it/s]

Processing tickers:  42%|████▏     | 2930/6932 [10:35<14:04,  4.74it/s]

Processing tickers:  42%|████▏     | 2931/6932 [10:35<14:13,  4.69it/s]

Processing tickers:  42%|████▏     | 2932/6932 [10:35<14:24,  4.63it/s]

Processing tickers:  42%|████▏     | 2933/6932 [10:35<14:21,  4.64it/s]

Processing tickers:  42%|████▏     | 2934/6932 [10:36<14:07,  4.72it/s]

Processing tickers:  42%|████▏     | 2935/6932 [10:36<14:00,  4.76it/s]

Processing tickers:  42%|████▏     | 2936/6932 [10:36<14:15,  4.67it/s]

Processing tickers:  42%|████▏     | 2937/6932 [10:36<14:25,  4.62it/s]

Processing tickers:  42%|████▏     | 2938/6932 [10:37<14:42,  4.53it/s]

Processing tickers:  42%|████▏     | 2939/6932 [10:37<14:16,  4.66it/s]

Processing tickers:  42%|████▏     | 2940/6932 [10:37<14:28,  4.60it/s]

Processing tickers:  42%|████▏     | 2941/6932 [10:37<14:20,  4.64it/s]

Processing tickers:  42%|████▏     | 2942/6932 [10:37<14:27,  4.60it/s]

Processing tickers:  42%|████▏     | 2943/6932 [10:38<14:14,  4.67it/s]

Processing tickers:  42%|████▏     | 2944/6932 [10:38<14:09,  4.70it/s]

Processing tickers:  42%|████▏     | 2945/6932 [10:38<14:19,  4.64it/s]

Processing tickers:  42%|████▏     | 2946/6932 [10:38<14:14,  4.67it/s]

Processing tickers:  43%|████▎     | 2947/6932 [10:38<14:12,  4.67it/s]

Processing tickers:  43%|████▎     | 2948/6932 [10:39<14:17,  4.65it/s]

Processing tickers:  43%|████▎     | 2949/6932 [10:39<14:09,  4.69it/s]

Processing tickers:  43%|████▎     | 2950/6932 [10:39<14:03,  4.72it/s]

Processing tickers:  43%|████▎     | 2951/6932 [10:39<13:52,  4.78it/s]

Processing tickers:  43%|████▎     | 2952/6932 [10:40<13:53,  4.77it/s]

Processing tickers:  43%|████▎     | 2953/6932 [10:40<14:07,  4.69it/s]

Processing tickers:  43%|████▎     | 2954/6932 [10:40<14:02,  4.72it/s]

Processing tickers:  43%|████▎     | 2955/6932 [10:40<14:08,  4.69it/s]

Processing tickers:  43%|████▎     | 2956/6932 [10:40<13:52,  4.77it/s]

Processing tickers:  43%|████▎     | 2957/6932 [10:41<14:01,  4.73it/s]

Processing tickers:  43%|████▎     | 2958/6932 [10:41<14:06,  4.70it/s]

Processing tickers:  43%|████▎     | 2959/6932 [10:41<13:58,  4.74it/s]

Processing tickers:  43%|████▎     | 2960/6932 [10:41<13:54,  4.76it/s]

Processing tickers:  43%|████▎     | 2961/6932 [10:41<13:54,  4.76it/s]

Processing tickers:  43%|████▎     | 2962/6932 [10:42<13:48,  4.79it/s]

Processing tickers:  43%|████▎     | 2963/6932 [10:42<14:05,  4.69it/s]

Processing tickers:  43%|████▎     | 2964/6932 [10:42<13:40,  4.83it/s]

Processing tickers:  43%|████▎     | 2965/6932 [10:42<14:57,  4.42it/s]

Processing tickers:  43%|████▎     | 2966/6932 [10:43<14:33,  4.54it/s]

Processing tickers:  43%|████▎     | 2967/6932 [10:43<14:42,  4.49it/s]

Processing tickers:  43%|████▎     | 2968/6932 [10:43<14:22,  4.60it/s]

Processing tickers:  43%|████▎     | 2969/6932 [10:43<14:21,  4.60it/s]

Processing tickers:  43%|████▎     | 2970/6932 [10:43<14:14,  4.63it/s]

Processing tickers:  43%|████▎     | 2971/6932 [10:44<14:01,  4.71it/s]

Processing tickers:  43%|████▎     | 2972/6932 [10:44<14:03,  4.70it/s]

Processing tickers:  43%|████▎     | 2973/6932 [10:44<13:39,  4.83it/s]

Processing tickers:  43%|████▎     | 2974/6932 [10:44<14:04,  4.69it/s]

Processing tickers:  43%|████▎     | 2975/6932 [10:44<13:54,  4.74it/s]

Processing tickers:  43%|████▎     | 2976/6932 [10:45<13:31,  4.87it/s]

Processing tickers:  43%|████▎     | 2977/6932 [10:45<13:54,  4.74it/s]

Processing tickers:  43%|████▎     | 2978/6932 [10:45<13:50,  4.76it/s]

Processing tickers:  43%|████▎     | 2979/6932 [10:45<13:48,  4.77it/s]

Processing tickers:  43%|████▎     | 2980/6932 [10:46<14:06,  4.67it/s]

Processing tickers:  43%|████▎     | 2981/6932 [10:46<13:58,  4.71it/s]

Processing tickers:  43%|████▎     | 2982/6932 [10:46<13:53,  4.74it/s]

Processing tickers:  43%|████▎     | 2983/6932 [10:46<13:50,  4.76it/s]

Processing tickers:  43%|████▎     | 2984/6932 [10:46<13:46,  4.78it/s]

Processing tickers:  43%|████▎     | 2985/6932 [10:47<13:44,  4.79it/s]

Processing tickers:  43%|████▎     | 2986/6932 [10:47<13:43,  4.79it/s]

Processing tickers:  43%|████▎     | 2987/6932 [10:47<13:42,  4.79it/s]

Processing tickers:  43%|████▎     | 2988/6932 [10:47<13:41,  4.80it/s]

Processing tickers:  43%|████▎     | 2989/6932 [10:47<13:41,  4.80it/s]

Processing tickers:  43%|████▎     | 2990/6932 [10:48<13:40,  4.81it/s]

Processing tickers:  43%|████▎     | 2991/6932 [10:48<13:58,  4.70it/s]

Processing tickers:  43%|████▎     | 2992/6932 [10:48<13:52,  4.73it/s]

Processing tickers:  43%|████▎     | 2993/6932 [10:48<13:57,  4.71it/s]

Processing tickers:  43%|████▎     | 2994/6932 [10:48<13:57,  4.70it/s]

Processing tickers:  43%|████▎     | 2995/6932 [10:49<13:55,  4.71it/s]

Processing tickers:  43%|████▎     | 2996/6932 [10:49<13:50,  4.74it/s]

Processing tickers:  43%|████▎     | 2997/6932 [10:49<13:28,  4.87it/s]

Processing tickers:  43%|████▎     | 2998/6932 [10:49<13:49,  4.74it/s]

Processing tickers:  43%|████▎     | 2999/6932 [10:49<13:27,  4.87it/s]

Processing tickers:  43%|████▎     | 3000/6932 [10:50<13:49,  4.74it/s]

Processing tickers:  43%|████▎     | 3001/6932 [10:50<13:45,  4.76it/s]

Processing tickers:  43%|████▎     | 3002/6932 [10:50<13:41,  4.78it/s]

Processing tickers:  43%|████▎     | 3003/6932 [10:50<13:45,  4.76it/s]

Processing tickers:  43%|████▎     | 3004/6932 [10:51<13:56,  4.69it/s]

Processing tickers:  43%|████▎     | 3005/6932 [10:51<13:49,  4.73it/s]

Processing tickers:  43%|████▎     | 3006/6932 [10:51<13:45,  4.75it/s]

Processing tickers:  43%|████▎     | 3007/6932 [10:51<13:55,  4.70it/s]

Processing tickers:  43%|████▎     | 3008/6932 [10:51<13:36,  4.80it/s]

Processing tickers:  43%|████▎     | 3009/6932 [10:52<13:52,  4.71it/s]

Processing tickers:  43%|████▎     | 3010/6932 [10:52<13:32,  4.83it/s]

Processing tickers:  43%|████▎     | 3011/6932 [10:52<14:13,  4.60it/s]

Processing tickers:  43%|████▎     | 3012/6932 [10:52<13:59,  4.67it/s]

Processing tickers:  43%|████▎     | 3013/6932 [10:52<13:52,  4.71it/s]

Processing tickers:  43%|████▎     | 3014/6932 [10:53<13:59,  4.67it/s]

Processing tickers:  43%|████▎     | 3015/6932 [10:53<13:58,  4.67it/s]

Processing tickers:  44%|████▎     | 3016/6932 [10:53<13:50,  4.71it/s]

Processing tickers:  44%|████▎     | 3017/6932 [10:53<13:45,  4.74it/s]

Processing tickers:  44%|████▎     | 3018/6932 [10:54<13:40,  4.77it/s]

Processing tickers:  44%|████▎     | 3019/6932 [10:54<13:19,  4.89it/s]

Processing tickers:  44%|████▎     | 3020/6932 [10:54<13:41,  4.76it/s]

Processing tickers:  44%|████▎     | 3021/6932 [10:54<13:45,  4.74it/s]

Processing tickers:  44%|████▎     | 3022/6932 [10:54<13:34,  4.80it/s]

Processing tickers:  44%|████▎     | 3023/6932 [10:55<13:33,  4.80it/s]

Processing tickers:  44%|████▎     | 3024/6932 [10:55<13:50,  4.71it/s]

Processing tickers:  44%|████▎     | 3025/6932 [10:55<14:00,  4.65it/s]

Processing tickers:  44%|████▎     | 3026/6932 [10:55<13:50,  4.70it/s]

Processing tickers:  44%|████▎     | 3027/6932 [10:55<13:44,  4.73it/s]

Processing tickers:  44%|████▎     | 3028/6932 [10:56<13:57,  4.66it/s]

Processing tickers:  44%|████▎     | 3029/6932 [10:56<13:58,  4.66it/s]

Processing tickers:  44%|████▎     | 3030/6932 [10:56<13:49,  4.71it/s]

Processing tickers:  44%|████▎     | 3031/6932 [10:56<13:56,  4.67it/s]

Processing tickers:  44%|████▎     | 3032/6932 [10:56<14:08,  4.60it/s]

Processing tickers:  44%|████▍     | 3033/6932 [10:57<13:55,  4.67it/s]

Processing tickers:  44%|████▍     | 3034/6932 [10:57<13:52,  4.68it/s]

Processing tickers:  44%|████▍     | 3035/6932 [10:57<13:41,  4.75it/s]

Processing tickers:  44%|████▍     | 3036/6932 [10:57<13:38,  4.76it/s]

Processing tickers:  44%|████▍     | 3037/6932 [10:58<19:33,  3.32it/s]

Processing tickers:  44%|████▍     | 3038/6932 [10:58<17:42,  3.66it/s]

Processing tickers:  44%|████▍     | 3039/6932 [10:58<16:26,  3.95it/s]

Processing tickers:  44%|████▍     | 3040/6932 [10:58<15:44,  4.12it/s]

Processing tickers:  44%|████▍     | 3041/6932 [10:59<15:13,  4.26it/s]

Processing tickers:  44%|████▍     | 3042/6932 [10:59<14:39,  4.42it/s]

Processing tickers:  44%|████▍     | 3043/6932 [10:59<14:18,  4.53it/s]

Processing tickers:  44%|████▍     | 3044/6932 [10:59<14:05,  4.60it/s]

Processing tickers:  44%|████▍     | 3045/6932 [11:00<13:52,  4.67it/s]

Processing tickers:  44%|████▍     | 3046/6932 [11:00<14:09,  4.58it/s]

Processing tickers:  44%|████▍     | 3047/6932 [11:00<13:57,  4.64it/s]

Processing tickers:  44%|████▍     | 3048/6932 [11:00<13:53,  4.66it/s]

Processing tickers:  44%|████▍     | 3049/6932 [11:00<13:37,  4.75it/s]

Processing tickers:  44%|████▍     | 3050/6932 [11:01<13:45,  4.70it/s]

Processing tickers:  44%|████▍     | 3051/6932 [11:01<13:27,  4.80it/s]

Processing tickers:  44%|████▍     | 3052/6932 [11:01<13:27,  4.80it/s]

Processing tickers:  44%|████▍     | 3053/6932 [11:01<13:26,  4.81it/s]

Processing tickers:  44%|████▍     | 3054/6932 [11:01<13:45,  4.70it/s]

Processing tickers:  44%|████▍     | 3055/6932 [11:02<13:52,  4.66it/s]

Processing tickers:  44%|████▍     | 3056/6932 [11:02<13:58,  4.62it/s]

Processing tickers:  44%|████▍     | 3057/6932 [11:02<13:40,  4.72it/s]

Processing tickers:  44%|████▍     | 3058/6932 [11:02<13:54,  4.64it/s]

Processing tickers:  44%|████▍     | 3059/6932 [11:02<13:45,  4.69it/s]

Processing tickers:  44%|████▍     | 3060/6932 [11:03<13:39,  4.73it/s]

Processing tickers:  44%|████▍     | 3061/6932 [11:03<13:32,  4.77it/s]

Processing tickers:  44%|████▍     | 3062/6932 [11:03<13:45,  4.69it/s]

Processing tickers:  44%|████▍     | 3063/6932 [11:03<13:57,  4.62it/s]

Processing tickers:  44%|████▍     | 3064/6932 [11:04<13:50,  4.66it/s]

Processing tickers:  44%|████▍     | 3065/6932 [11:04<13:40,  4.71it/s]

Processing tickers:  44%|████▍     | 3066/6932 [11:04<13:35,  4.74it/s]

Processing tickers:  44%|████▍     | 3067/6932 [11:04<13:32,  4.75it/s]

Processing tickers:  44%|████▍     | 3068/6932 [11:04<13:37,  4.73it/s]

Processing tickers:  44%|████▍     | 3069/6932 [11:05<13:40,  4.71it/s]

Processing tickers:  44%|████▍     | 3070/6932 [11:05<13:38,  4.72it/s]

Processing tickers:  44%|████▍     | 3071/6932 [11:05<13:36,  4.73it/s]

Processing tickers:  44%|████▍     | 3072/6932 [11:05<13:11,  4.87it/s]

Processing tickers:  44%|████▍     | 3073/6932 [11:05<13:16,  4.85it/s]

Processing tickers:  44%|████▍     | 3074/6932 [11:06<13:36,  4.73it/s]

Processing tickers:  44%|████▍     | 3075/6932 [11:06<13:31,  4.76it/s]

Processing tickers:  44%|████▍     | 3076/6932 [11:06<13:26,  4.78it/s]

Processing tickers:  44%|████▍     | 3077/6932 [11:06<13:22,  4.80it/s]

Processing tickers:  44%|████▍     | 3078/6932 [11:06<13:22,  4.80it/s]

Processing tickers:  44%|████▍     | 3079/6932 [11:07<13:22,  4.80it/s]

Processing tickers:  44%|████▍     | 3080/6932 [11:07<13:22,  4.80it/s]

Processing tickers:  44%|████▍     | 3081/6932 [11:07<13:34,  4.73it/s]

Processing tickers:  44%|████▍     | 3082/6932 [11:07<13:36,  4.71it/s]

Processing tickers:  44%|████▍     | 3083/6932 [11:08<13:32,  4.73it/s]

Processing tickers:  44%|████▍     | 3084/6932 [11:08<13:28,  4.76it/s]

Processing tickers:  45%|████▍     | 3085/6932 [11:08<13:26,  4.77it/s]

Processing tickers:  45%|████▍     | 3086/6932 [11:08<13:39,  4.69it/s]

Processing tickers:  45%|████▍     | 3087/6932 [11:08<13:32,  4.73it/s]

Processing tickers:  45%|████▍     | 3088/6932 [11:09<13:33,  4.72it/s]

Processing tickers:  45%|████▍     | 3089/6932 [11:09<13:32,  4.73it/s]

Processing tickers:  45%|████▍     | 3090/6932 [11:09<13:24,  4.77it/s]

Processing tickers:  45%|████▍     | 3091/6932 [11:09<13:41,  4.68it/s]

Processing tickers:  45%|████▍     | 3092/6932 [11:09<13:33,  4.72it/s]

Processing tickers:  45%|████▍     | 3093/6932 [11:10<13:46,  4.65it/s]

Processing tickers:  45%|████▍     | 3094/6932 [11:10<13:41,  4.67it/s]

Processing tickers:  45%|████▍     | 3095/6932 [11:10<13:32,  4.72it/s]

Processing tickers:  45%|████▍     | 3096/6932 [11:10<13:31,  4.73it/s]

Processing tickers:  45%|████▍     | 3097/6932 [11:11<13:26,  4.76it/s]

Processing tickers:  45%|████▍     | 3098/6932 [11:11<13:39,  4.68it/s]

Processing tickers:  45%|████▍     | 3099/6932 [11:11<13:30,  4.73it/s]

Processing tickers:  45%|████▍     | 3100/6932 [11:11<13:26,  4.75it/s]

Processing tickers:  45%|████▍     | 3101/6932 [11:11<13:23,  4.77it/s]

Processing tickers:  45%|████▍     | 3102/6932 [11:12<13:21,  4.78it/s]

Processing tickers:  45%|████▍     | 3103/6932 [11:12<13:19,  4.79it/s]

Processing tickers:  45%|████▍     | 3104/6932 [11:12<13:17,  4.80it/s]

Processing tickers:  45%|████▍     | 3105/6932 [11:12<13:17,  4.80it/s]

Processing tickers:  45%|████▍     | 3106/6932 [11:12<13:34,  4.70it/s]

Processing tickers:  45%|████▍     | 3107/6932 [11:13<13:27,  4.74it/s]

Processing tickers:  45%|████▍     | 3108/6932 [11:13<13:46,  4.62it/s]

Processing tickers:  45%|████▍     | 3109/6932 [11:13<13:32,  4.71it/s]

Processing tickers:  45%|████▍     | 3110/6932 [11:13<13:27,  4.74it/s]

Processing tickers:  45%|████▍     | 3111/6932 [11:13<13:41,  4.65it/s]

Processing tickers:  45%|████▍     | 3112/6932 [11:14<13:39,  4.66it/s]

Processing tickers:  45%|████▍     | 3113/6932 [11:14<13:29,  4.72it/s]

Processing tickers:  45%|████▍     | 3114/6932 [11:14<13:21,  4.76it/s]

Processing tickers:  45%|████▍     | 3115/6932 [11:14<13:19,  4.77it/s]

Processing tickers:  45%|████▍     | 3116/6932 [11:15<13:18,  4.78it/s]

Processing tickers:  45%|████▍     | 3117/6932 [11:15<13:38,  4.66it/s]

Processing tickers:  45%|████▍     | 3118/6932 [11:15<13:27,  4.72it/s]

Processing tickers:  45%|████▍     | 3119/6932 [11:15<13:22,  4.75it/s]

Processing tickers:  45%|████▌     | 3120/6932 [11:15<13:25,  4.73it/s]

Processing tickers:  45%|████▌     | 3121/6932 [11:16<13:15,  4.79it/s]

Processing tickers:  45%|████▌     | 3122/6932 [11:16<13:32,  4.69it/s]

Processing tickers:  45%|████▌     | 3123/6932 [11:16<13:30,  4.70it/s]

Processing tickers:  45%|████▌     | 3124/6932 [11:16<13:37,  4.66it/s]

Processing tickers:  45%|████▌     | 3125/6932 [11:16<13:31,  4.69it/s]

Processing tickers:  45%|████▌     | 3126/6932 [11:17<13:26,  4.72it/s]

Processing tickers:  45%|████▌     | 3127/6932 [11:17<13:23,  4.74it/s]

Processing tickers:  45%|████▌     | 3128/6932 [11:17<13:19,  4.76it/s]

Processing tickers:  45%|████▌     | 3129/6932 [11:17<13:23,  4.73it/s]

Processing tickers:  45%|████▌     | 3130/6932 [11:17<13:13,  4.79it/s]

Processing tickers:  45%|████▌     | 3131/6932 [11:18<13:14,  4.78it/s]

Processing tickers:  45%|████▌     | 3132/6932 [11:18<13:29,  4.69it/s]

Processing tickers:  45%|████▌     | 3133/6932 [11:18<13:24,  4.72it/s]

Processing tickers:  45%|████▌     | 3134/6932 [11:18<13:40,  4.63it/s]

Processing tickers:  45%|████▌     | 3135/6932 [11:19<13:29,  4.69it/s]

Processing tickers:  45%|████▌     | 3136/6932 [11:19<13:36,  4.65it/s]

Processing tickers:  45%|████▌     | 3137/6932 [11:19<13:16,  4.76it/s]

Processing tickers:  45%|████▌     | 3138/6932 [11:19<13:13,  4.78it/s]

Processing tickers:  45%|████▌     | 3139/6932 [11:19<13:12,  4.79it/s]

Processing tickers:  45%|████▌     | 3140/6932 [11:20<13:11,  4.79it/s]

Processing tickers:  45%|████▌     | 3141/6932 [11:20<13:13,  4.78it/s]

Processing tickers:  45%|████▌     | 3142/6932 [11:20<13:13,  4.78it/s]

Processing tickers:  45%|████▌     | 3143/6932 [11:20<13:09,  4.80it/s]

Processing tickers:  45%|████▌     | 3144/6932 [11:20<13:18,  4.75it/s]

Processing tickers:  45%|████▌     | 3145/6932 [11:21<13:06,  4.82it/s]

Processing tickers:  45%|████▌     | 3146/6932 [11:21<13:21,  4.72it/s]

Processing tickers:  45%|████▌     | 3147/6932 [11:21<13:02,  4.84it/s]

Processing tickers:  45%|████▌     | 3148/6932 [11:21<13:22,  4.71it/s]

Processing tickers:  45%|████▌     | 3149/6932 [11:21<12:59,  4.85it/s]

Processing tickers:  45%|████▌     | 3150/6932 [11:22<13:19,  4.73it/s]

Processing tickers:  45%|████▌     | 3151/6932 [11:22<13:14,  4.76it/s]

Processing tickers:  45%|████▌     | 3152/6932 [11:22<13:19,  4.73it/s]

Processing tickers:  45%|████▌     | 3153/6932 [11:22<13:06,  4.81it/s]

Processing tickers:  45%|████▌     | 3154/6932 [11:23<13:22,  4.71it/s]

Processing tickers:  46%|████▌     | 3155/6932 [11:23<13:36,  4.62it/s]

Processing tickers:  46%|████▌     | 3156/6932 [11:23<13:27,  4.68it/s]

Processing tickers:  46%|████▌     | 3157/6932 [11:23<13:20,  4.71it/s]

Processing tickers:  46%|████▌     | 3158/6932 [11:23<13:15,  4.74it/s]

Processing tickers:  46%|████▌     | 3159/6932 [11:24<13:25,  4.68it/s]

Processing tickers:  46%|████▌     | 3160/6932 [11:24<13:06,  4.80it/s]

Processing tickers:  46%|████▌     | 3161/6932 [11:24<13:22,  4.70it/s]

Processing tickers:  46%|████▌     | 3162/6932 [11:24<13:26,  4.67it/s]

Processing tickers:  46%|████▌     | 3163/6932 [11:24<13:25,  4.68it/s]

Processing tickers:  46%|████▌     | 3164/6932 [11:25<13:30,  4.65it/s]

Processing tickers:  46%|████▌     | 3165/6932 [11:25<13:10,  4.77it/s]

Processing tickers:  46%|████▌     | 3166/6932 [11:25<13:08,  4.78it/s]

Processing tickers:  46%|████▌     | 3167/6932 [11:25<13:06,  4.79it/s]

Processing tickers:  46%|████▌     | 3168/6932 [11:25<13:03,  4.80it/s]

Processing tickers:  46%|████▌     | 3169/6932 [11:26<13:18,  4.71it/s]

Processing tickers:  46%|████▌     | 3170/6932 [11:26<13:32,  4.63it/s]

Processing tickers:  46%|████▌     | 3171/6932 [11:26<13:41,  4.58it/s]

Processing tickers:  46%|████▌     | 3172/6932 [11:26<13:29,  4.65it/s]

Processing tickers:  46%|████▌     | 3173/6932 [11:27<13:21,  4.69it/s]

Processing tickers:  46%|████▌     | 3174/6932 [11:27<13:15,  4.72it/s]

Processing tickers:  46%|████▌     | 3175/6932 [11:27<13:11,  4.75it/s]

Processing tickers:  46%|████▌     | 3176/6932 [11:27<13:07,  4.77it/s]

Processing tickers:  46%|████▌     | 3177/6932 [11:27<13:05,  4.78it/s]

Processing tickers:  46%|████▌     | 3178/6932 [11:28<13:04,  4.79it/s]

Processing tickers:  46%|████▌     | 3179/6932 [11:28<13:20,  4.69it/s]

Processing tickers:  46%|████▌     | 3180/6932 [11:28<13:14,  4.72it/s]

Processing tickers:  46%|████▌     | 3181/6932 [11:28<13:09,  4.75it/s]

Processing tickers:  46%|████▌     | 3182/6932 [11:28<13:24,  4.66it/s]

Processing tickers:  46%|████▌     | 3183/6932 [11:29<13:17,  4.70it/s]

Processing tickers:  46%|████▌     | 3184/6932 [11:29<13:46,  4.53it/s]

Processing tickers:  46%|████▌     | 3185/6932 [11:29<13:32,  4.61it/s]

Processing tickers:  46%|████▌     | 3186/6932 [11:29<13:22,  4.67it/s]

Processing tickers:  46%|████▌     | 3187/6932 [11:30<13:33,  4.61it/s]

Processing tickers:  46%|████▌     | 3188/6932 [11:30<13:25,  4.65it/s]

Processing tickers:  46%|████▌     | 3189/6932 [11:30<13:14,  4.71it/s]

Processing tickers:  46%|████▌     | 3190/6932 [11:30<13:10,  4.73it/s]

Processing tickers:  46%|████▌     | 3191/6932 [11:30<13:06,  4.76it/s]

Processing tickers:  46%|████▌     | 3192/6932 [11:31<13:39,  4.56it/s]

Processing tickers:  46%|████▌     | 3193/6932 [11:31<13:26,  4.63it/s]

Processing tickers:  46%|████▌     | 3194/6932 [11:31<13:18,  4.68it/s]

Processing tickers:  46%|████▌     | 3195/6932 [11:31<13:12,  4.72it/s]

Processing tickers:  46%|████▌     | 3196/6932 [11:31<13:07,  4.74it/s]

Processing tickers:  46%|████▌     | 3197/6932 [11:32<13:06,  4.75it/s]

Processing tickers:  46%|████▌     | 3198/6932 [11:32<13:18,  4.68it/s]

Processing tickers:  46%|████▌     | 3199/6932 [11:32<13:15,  4.69it/s]

Processing tickers:  46%|████▌     | 3200/6932 [11:32<13:29,  4.61it/s]

Processing tickers:  46%|████▌     | 3201/6932 [11:33<13:14,  4.69it/s]

Processing tickers:  46%|████▌     | 3202/6932 [11:33<13:08,  4.73it/s]

Processing tickers:  46%|████▌     | 3203/6932 [11:33<13:15,  4.69it/s]

Processing tickers:  46%|████▌     | 3204/6932 [11:33<13:21,  4.65it/s]

Processing tickers:  46%|████▌     | 3205/6932 [11:33<13:40,  4.54it/s]

Processing tickers:  46%|████▌     | 3206/6932 [11:34<14:37,  4.25it/s]

Processing tickers:  46%|████▋     | 3207/6932 [11:34<14:06,  4.40it/s]

Processing tickers:  46%|████▋     | 3208/6932 [11:34<14:02,  4.42it/s]

Processing tickers:  46%|████▋     | 3209/6932 [11:34<13:42,  4.53it/s]

Processing tickers:  46%|████▋     | 3210/6932 [11:35<13:28,  4.60it/s]

Processing tickers:  46%|████▋     | 3211/6932 [11:35<13:37,  4.55it/s]

Processing tickers:  46%|████▋     | 3212/6932 [11:35<13:28,  4.60it/s]

Processing tickers:  46%|████▋     | 3213/6932 [11:35<13:13,  4.69it/s]

Processing tickers:  46%|████▋     | 3214/6932 [11:36<16:28,  3.76it/s]

Processing tickers:  46%|████▋     | 3215/6932 [11:36<15:56,  3.89it/s]

Processing tickers:  46%|████▋     | 3216/6932 [11:36<15:01,  4.12it/s]

Processing tickers:  46%|████▋     | 3217/6932 [11:36<14:04,  4.40it/s]

Processing tickers:  46%|████▋     | 3218/6932 [11:36<13:43,  4.51it/s]

Processing tickers:  46%|████▋     | 3219/6932 [11:37<13:46,  4.49it/s]

Processing tickers:  46%|████▋     | 3220/6932 [11:37<13:25,  4.61it/s]

Processing tickers:  46%|████▋     | 3221/6932 [11:37<13:17,  4.65it/s]

Processing tickers:  46%|████▋     | 3222/6932 [11:37<13:07,  4.71it/s]

Processing tickers:  46%|████▋     | 3223/6932 [11:37<13:01,  4.75it/s]

Processing tickers:  47%|████▋     | 3224/6932 [11:38<13:04,  4.73it/s]

Processing tickers:  47%|████▋     | 3225/6932 [11:38<12:53,  4.79it/s]

Processing tickers:  47%|████▋     | 3226/6932 [11:38<13:10,  4.69it/s]

Processing tickers:  47%|████▋     | 3227/6932 [11:38<13:04,  4.72it/s]

Processing tickers:  47%|████▋     | 3228/6932 [11:39<13:00,  4.74it/s]

Processing tickers:  47%|████▋     | 3229/6932 [11:39<12:58,  4.76it/s]

Processing tickers:  47%|████▋     | 3230/6932 [11:39<13:13,  4.67it/s]

Processing tickers:  47%|████▋     | 3231/6932 [11:39<13:10,  4.68it/s]

Processing tickers:  47%|████▋     | 3232/6932 [11:39<13:00,  4.74it/s]

Processing tickers:  47%|████▋     | 3233/6932 [11:40<13:05,  4.71it/s]

Processing tickers:  47%|████▋     | 3234/6932 [11:40<13:13,  4.66it/s]

Processing tickers:  47%|████▋     | 3235/6932 [11:40<13:02,  4.72it/s]

Processing tickers:  47%|████▋     | 3236/6932 [11:40<12:58,  4.75it/s]

Processing tickers:  47%|████▋     | 3237/6932 [11:40<13:12,  4.66it/s]

Processing tickers:  47%|████▋     | 3238/6932 [11:41<13:05,  4.70it/s]

Processing tickers:  47%|████▋     | 3239/6932 [11:41<13:00,  4.73it/s]

Processing tickers:  47%|████▋     | 3240/6932 [11:41<13:15,  4.64it/s]

Processing tickers:  47%|████▋     | 3241/6932 [11:41<13:10,  4.67it/s]

Processing tickers:  47%|████▋     | 3242/6932 [11:42<12:57,  4.74it/s]

Processing tickers:  47%|████▋     | 3243/6932 [11:42<13:11,  4.66it/s]

Processing tickers:  47%|████▋     | 3244/6932 [11:42<13:02,  4.71it/s]

Processing tickers:  47%|████▋     | 3245/6932 [11:42<13:16,  4.63it/s]

Processing tickers:  47%|████▋     | 3246/6932 [11:42<13:21,  4.60it/s]

Processing tickers:  47%|████▋     | 3247/6932 [11:43<13:28,  4.56it/s]

Processing tickers:  47%|████▋     | 3248/6932 [11:43<12:58,  4.73it/s]

Processing tickers:  47%|████▋     | 3249/6932 [11:43<13:12,  4.65it/s]

Processing tickers:  47%|████▋     | 3250/6932 [11:43<12:47,  4.80it/s]

Processing tickers:  47%|████▋     | 3251/6932 [11:43<13:05,  4.69it/s]

Processing tickers:  47%|████▋     | 3252/6932 [11:44<12:59,  4.72it/s]

Processing tickers:  47%|████▋     | 3253/6932 [11:44<12:55,  4.74it/s]

Processing tickers:  47%|████▋     | 3254/6932 [11:44<13:15,  4.62it/s]

Processing tickers:  47%|████▋     | 3255/6932 [11:44<13:17,  4.61it/s]

Processing tickers:  47%|████▋     | 3256/6932 [11:45<13:10,  4.65it/s]

Processing tickers:  47%|████▋     | 3257/6932 [11:45<13:21,  4.59it/s]

Processing tickers:  47%|████▋     | 3258/6932 [11:45<13:08,  4.66it/s]

Processing tickers:  47%|████▋     | 3259/6932 [11:45<13:01,  4.70it/s]

Processing tickers:  47%|████▋     | 3260/6932 [11:45<12:56,  4.73it/s]

Processing tickers:  47%|████▋     | 3261/6932 [11:46<12:53,  4.74it/s]

Processing tickers:  47%|████▋     | 3262/6932 [11:46<13:02,  4.69it/s]

Processing tickers:  47%|████▋     | 3263/6932 [11:46<12:56,  4.72it/s]

Processing tickers:  47%|████▋     | 3264/6932 [11:46<12:42,  4.81it/s]

Processing tickers:  47%|████▋     | 3265/6932 [11:46<12:48,  4.77it/s]

Processing tickers:  47%|████▋     | 3266/6932 [11:47<12:42,  4.81it/s]

Processing tickers:  47%|████▋     | 3267/6932 [11:47<12:42,  4.81it/s]

Processing tickers:  47%|████▋     | 3268/6932 [11:47<12:40,  4.81it/s]

Processing tickers:  47%|████▋     | 3269/6932 [11:47<12:41,  4.81it/s]

Processing tickers:  47%|████▋     | 3270/6932 [11:47<12:41,  4.81it/s]

Processing tickers:  47%|████▋     | 3271/6932 [11:48<12:41,  4.81it/s]

Processing tickers:  47%|████▋     | 3272/6932 [11:48<12:42,  4.80it/s]

Processing tickers:  47%|████▋     | 3273/6932 [11:48<12:43,  4.79it/s]

Processing tickers:  47%|████▋     | 3274/6932 [11:48<12:39,  4.82it/s]

Processing tickers:  47%|████▋     | 3275/6932 [11:48<12:39,  4.82it/s]

Processing tickers:  47%|████▋     | 3276/6932 [11:49<12:41,  4.80it/s]

Processing tickers:  47%|████▋     | 3277/6932 [11:49<12:38,  4.82it/s]

Processing tickers:  47%|████▋     | 3278/6932 [11:49<12:37,  4.82it/s]

Processing tickers:  47%|████▋     | 3279/6932 [11:49<12:37,  4.82it/s]

Processing tickers:  47%|████▋     | 3280/6932 [11:50<12:37,  4.82it/s]

Processing tickers:  47%|████▋     | 3281/6932 [11:50<12:55,  4.71it/s]

Processing tickers:  47%|████▋     | 3282/6932 [11:50<12:52,  4.72it/s]

Processing tickers:  47%|████▋     | 3283/6932 [11:50<12:46,  4.76it/s]

Processing tickers:  47%|████▋     | 3284/6932 [11:50<12:43,  4.78it/s]

Processing tickers:  47%|████▋     | 3285/6932 [11:51<12:42,  4.79it/s]

Processing tickers:  47%|████▋     | 3286/6932 [11:51<12:42,  4.78it/s]

Processing tickers:  47%|████▋     | 3287/6932 [11:51<12:42,  4.78it/s]

Processing tickers:  47%|████▋     | 3288/6932 [11:51<12:43,  4.77it/s]

Processing tickers:  47%|████▋     | 3289/6932 [11:51<12:34,  4.83it/s]

Processing tickers:  47%|████▋     | 3290/6932 [11:52<12:35,  4.82it/s]

Processing tickers:  47%|████▋     | 3291/6932 [11:52<12:35,  4.82it/s]

Processing tickers:  47%|████▋     | 3292/6932 [11:52<12:52,  4.71it/s]

Processing tickers:  48%|████▊     | 3293/6932 [11:52<12:47,  4.74it/s]

Processing tickers:  48%|████▊     | 3294/6932 [11:52<13:00,  4.66it/s]

Processing tickers:  48%|████▊     | 3295/6932 [11:53<12:56,  4.68it/s]

Processing tickers:  48%|████▊     | 3296/6932 [11:53<13:04,  4.63it/s]

Processing tickers:  48%|████▊     | 3297/6932 [11:53<12:56,  4.68it/s]

Processing tickers:  48%|████▊     | 3298/6932 [11:53<12:51,  4.71it/s]

Processing tickers:  48%|████▊     | 3299/6932 [11:54<12:44,  4.75it/s]

Processing tickers:  48%|████▊     | 3300/6932 [11:54<12:41,  4.77it/s]

Processing tickers:  48%|████▊     | 3301/6932 [11:54<12:39,  4.78it/s]

Processing tickers:  48%|████▊     | 3302/6932 [11:54<12:36,  4.80it/s]

Processing tickers:  48%|████▊     | 3303/6932 [11:54<12:54,  4.69it/s]

Processing tickers:  48%|████▊     | 3304/6932 [11:55<12:54,  4.69it/s]

Processing tickers:  48%|████▊     | 3305/6932 [11:55<12:38,  4.78it/s]

Processing tickers:  48%|████▊     | 3306/6932 [11:55<12:36,  4.79it/s]

Processing tickers:  48%|████▊     | 3307/6932 [11:55<12:34,  4.80it/s]

Processing tickers:  48%|████▊     | 3308/6932 [11:55<12:32,  4.81it/s]

Processing tickers:  48%|████▊     | 3309/6932 [11:56<12:51,  4.69it/s]

Processing tickers:  48%|████▊     | 3310/6932 [11:56<13:02,  4.63it/s]

Processing tickers:  48%|████▊     | 3311/6932 [11:56<12:53,  4.68it/s]

Processing tickers:  48%|████▊     | 3312/6932 [11:56<12:49,  4.71it/s]

Processing tickers:  48%|████▊     | 3313/6932 [11:56<12:41,  4.75it/s]

Processing tickers:  48%|████▊     | 3314/6932 [11:57<12:38,  4.77it/s]

Processing tickers:  48%|████▊     | 3315/6932 [11:57<12:36,  4.78it/s]

Processing tickers:  48%|████▊     | 3316/6932 [11:57<12:50,  4.69it/s]

Processing tickers:  48%|████▊     | 3317/6932 [11:57<12:46,  4.72it/s]

Processing tickers:  48%|████▊     | 3318/6932 [11:58<12:43,  4.73it/s]

Processing tickers:  48%|████▊     | 3319/6932 [11:58<12:39,  4.76it/s]

Processing tickers:  48%|████▊     | 3320/6932 [11:58<12:36,  4.77it/s]

Processing tickers:  48%|████▊     | 3321/6932 [11:58<12:42,  4.74it/s]

Processing tickers:  48%|████▊     | 3322/6932 [11:58<12:50,  4.69it/s]

Processing tickers:  48%|████▊     | 3323/6932 [11:59<12:43,  4.73it/s]

Processing tickers:  48%|████▊     | 3324/6932 [11:59<12:42,  4.73it/s]

Processing tickers:  48%|████▊     | 3325/6932 [11:59<12:34,  4.78it/s]

Processing tickers:  48%|████▊     | 3326/6932 [11:59<12:32,  4.79it/s]

Processing tickers:  48%|████▊     | 3327/6932 [11:59<13:06,  4.58it/s]

Processing tickers:  48%|████▊     | 3328/6932 [12:00<12:56,  4.64it/s]

Processing tickers:  48%|████▊     | 3329/6932 [12:00<12:54,  4.65it/s]

Processing tickers:  48%|████▊     | 3330/6932 [12:00<12:53,  4.66it/s]

Processing tickers:  48%|████▊     | 3331/6932 [12:00<12:50,  4.67it/s]

Processing tickers:  48%|████▊     | 3332/6932 [12:01<12:48,  4.69it/s]

Processing tickers:  48%|████▊     | 3333/6932 [12:01<12:53,  4.65it/s]

Processing tickers:  48%|████▊     | 3334/6932 [12:01<12:46,  4.69it/s]

Processing tickers:  48%|████▊     | 3335/6932 [12:01<12:38,  4.74it/s]

Processing tickers:  48%|████▊     | 3336/6932 [12:01<12:54,  4.65it/s]

Processing tickers:  48%|████▊     | 3337/6932 [12:02<12:42,  4.72it/s]

Processing tickers:  48%|████▊     | 3338/6932 [12:02<12:35,  4.76it/s]

Processing tickers:  48%|████▊     | 3339/6932 [12:02<12:33,  4.77it/s]

Processing tickers:  48%|████▊     | 3340/6932 [12:02<12:30,  4.78it/s]

Processing tickers:  48%|████▊     | 3341/6932 [12:02<12:47,  4.68it/s]

Processing tickers:  48%|████▊     | 3342/6932 [12:03<12:37,  4.74it/s]

Processing tickers:  48%|████▊     | 3343/6932 [12:03<12:21,  4.84it/s]

Processing tickers:  48%|████▊     | 3344/6932 [12:03<12:39,  4.72it/s]

Processing tickers:  48%|████▊     | 3345/6932 [12:03<12:35,  4.75it/s]

Processing tickers:  48%|████▊     | 3346/6932 [12:03<12:30,  4.78it/s]

Processing tickers:  48%|████▊     | 3347/6932 [12:04<12:26,  4.80it/s]

Processing tickers:  48%|████▊     | 3348/6932 [12:04<12:43,  4.69it/s]

Processing tickers:  48%|████▊     | 3349/6932 [12:04<12:37,  4.73it/s]

Processing tickers:  48%|████▊     | 3350/6932 [12:04<12:32,  4.76it/s]

Processing tickers:  48%|████▊     | 3351/6932 [12:05<12:30,  4.77it/s]

Processing tickers:  48%|████▊     | 3352/6932 [12:05<12:45,  4.68it/s]

Processing tickers:  48%|████▊     | 3353/6932 [12:05<12:53,  4.63it/s]

Processing tickers:  48%|████▊     | 3354/6932 [12:05<12:43,  4.68it/s]

Processing tickers:  48%|████▊     | 3355/6932 [12:05<12:37,  4.72it/s]

Processing tickers:  48%|████▊     | 3356/6932 [12:06<12:33,  4.74it/s]

Processing tickers:  48%|████▊     | 3357/6932 [12:06<12:47,  4.66it/s]

Processing tickers:  48%|████▊     | 3358/6932 [12:06<12:47,  4.66it/s]

Processing tickers:  48%|████▊     | 3359/6932 [12:06<12:46,  4.66it/s]

Processing tickers:  48%|████▊     | 3360/6932 [12:06<12:47,  4.66it/s]

Processing tickers:  48%|████▊     | 3361/6932 [12:07<12:35,  4.73it/s]

Processing tickers:  48%|████▊     | 3362/6932 [12:07<12:49,  4.64it/s]

Processing tickers:  49%|████▊     | 3363/6932 [12:07<12:42,  4.68it/s]

Processing tickers:  49%|████▊     | 3364/6932 [12:07<12:36,  4.72it/s]

Processing tickers:  49%|████▊     | 3365/6932 [12:08<12:48,  4.64it/s]

Processing tickers:  49%|████▊     | 3366/6932 [12:08<12:36,  4.71it/s]

Processing tickers:  49%|████▊     | 3367/6932 [12:08<12:31,  4.74it/s]

Processing tickers:  49%|████▊     | 3368/6932 [12:08<13:02,  4.56it/s]

Processing tickers:  49%|████▊     | 3369/6932 [12:08<13:07,  4.53it/s]

Processing tickers:  49%|████▊     | 3370/6932 [12:09<12:57,  4.58it/s]

Processing tickers:  49%|████▊     | 3371/6932 [12:09<12:58,  4.57it/s]

Processing tickers:  49%|████▊     | 3372/6932 [12:09<12:47,  4.64it/s]

Processing tickers:  49%|████▊     | 3373/6932 [12:09<12:38,  4.69it/s]

Processing tickers:  49%|████▊     | 3374/6932 [12:09<12:43,  4.66it/s]

Processing tickers:  49%|████▊     | 3375/6932 [12:10<12:28,  4.75it/s]

Processing tickers:  49%|████▊     | 3376/6932 [12:10<12:40,  4.67it/s]

Processing tickers:  49%|████▊     | 3377/6932 [12:10<12:45,  4.64it/s]

Processing tickers:  49%|████▊     | 3378/6932 [12:10<12:41,  4.67it/s]

Processing tickers:  49%|████▊     | 3379/6932 [12:11<12:35,  4.70it/s]

Processing tickers:  49%|████▉     | 3380/6932 [12:11<12:30,  4.73it/s]

Processing tickers:  49%|████▉     | 3381/6932 [12:11<12:29,  4.74it/s]

Processing tickers:  49%|████▉     | 3382/6932 [12:11<12:23,  4.77it/s]

Processing tickers:  49%|████▉     | 3383/6932 [12:11<12:22,  4.78it/s]

Processing tickers:  49%|████▉     | 3384/6932 [12:12<12:37,  4.68it/s]

Processing tickers:  49%|████▉     | 3385/6932 [12:12<12:40,  4.66it/s]

Processing tickers:  49%|████▉     | 3386/6932 [12:12<12:34,  4.70it/s]

Processing tickers:  49%|████▉     | 3387/6932 [12:12<12:39,  4.67it/s]

Processing tickers:  49%|████▉     | 3388/6932 [12:12<12:29,  4.73it/s]

Processing tickers:  49%|████▉     | 3389/6932 [12:13<12:25,  4.75it/s]

Processing tickers:  49%|████▉     | 3390/6932 [12:13<12:22,  4.77it/s]

Processing tickers:  49%|████▉     | 3391/6932 [12:13<12:28,  4.73it/s]

Processing tickers:  49%|████▉     | 3392/6932 [12:13<12:16,  4.81it/s]

Processing tickers:  49%|████▉     | 3393/6932 [12:13<12:16,  4.80it/s]

Processing tickers:  49%|████▉     | 3394/6932 [12:14<12:41,  4.64it/s]

Processing tickers:  49%|████▉     | 3395/6932 [12:14<12:26,  4.74it/s]

Processing tickers:  49%|████▉     | 3396/6932 [12:14<12:23,  4.76it/s]

Processing tickers:  49%|████▉     | 3397/6932 [12:14<12:20,  4.77it/s]

Processing tickers:  49%|████▉     | 3398/6932 [12:15<12:37,  4.67it/s]

Processing tickers:  49%|████▉     | 3399/6932 [12:15<12:28,  4.72it/s]

Processing tickers:  49%|████▉     | 3400/6932 [12:15<12:24,  4.74it/s]

Processing tickers:  49%|████▉     | 3401/6932 [12:15<12:48,  4.60it/s]

Processing tickers:  49%|████▉     | 3402/6932 [12:16<14:59,  3.92it/s]

Processing tickers:  49%|████▉     | 3403/6932 [12:16<14:44,  3.99it/s]

Processing tickers:  49%|████▉     | 3404/6932 [12:16<13:42,  4.29it/s]

Processing tickers:  49%|████▉     | 3405/6932 [12:16<13:32,  4.34it/s]

Processing tickers:  49%|████▉     | 3406/6932 [12:16<13:09,  4.47it/s]

Processing tickers:  49%|████▉     | 3407/6932 [12:17<13:09,  4.47it/s]

Processing tickers:  49%|████▉     | 3408/6932 [12:17<12:52,  4.56it/s]

Processing tickers:  49%|████▉     | 3409/6932 [12:17<12:40,  4.63it/s]

Processing tickers:  49%|████▉     | 3410/6932 [12:17<12:31,  4.68it/s]

Processing tickers:  49%|████▉     | 3411/6932 [12:17<12:26,  4.71it/s]

Processing tickers:  49%|████▉     | 3412/6932 [12:18<12:24,  4.73it/s]

Processing tickers:  49%|████▉     | 3413/6932 [12:18<12:33,  4.67it/s]

Processing tickers:  49%|████▉     | 3414/6932 [12:18<12:29,  4.70it/s]

Processing tickers:  49%|████▉     | 3415/6932 [12:18<12:28,  4.70it/s]

Processing tickers:  49%|████▉     | 3416/6932 [12:19<12:18,  4.76it/s]

Processing tickers:  49%|████▉     | 3417/6932 [12:19<12:33,  4.67it/s]

Processing tickers:  49%|████▉     | 3418/6932 [12:19<12:35,  4.65it/s]

Processing tickers:  49%|████▉     | 3419/6932 [12:19<12:18,  4.76it/s]

Processing tickers:  49%|████▉     | 3420/6932 [12:19<12:19,  4.75it/s]

Processing tickers:  49%|████▉     | 3421/6932 [12:20<12:29,  4.68it/s]

Processing tickers:  49%|████▉     | 3422/6932 [12:20<12:07,  4.83it/s]

Processing tickers:  49%|████▉     | 3423/6932 [12:20<12:07,  4.82it/s]

Processing tickers:  49%|████▉     | 3424/6932 [12:20<12:24,  4.71it/s]

Processing tickers:  49%|████▉     | 3425/6932 [12:20<12:19,  4.74it/s]

Processing tickers:  49%|████▉     | 3426/6932 [12:21<12:15,  4.77it/s]

Processing tickers:  49%|████▉     | 3427/6932 [12:21<12:34,  4.65it/s]

Processing tickers:  49%|████▉     | 3428/6932 [12:21<12:35,  4.64it/s]

Processing tickers:  49%|████▉     | 3429/6932 [12:21<12:14,  4.77it/s]

Processing tickers:  49%|████▉     | 3430/6932 [12:22<12:29,  4.67it/s]

Processing tickers:  49%|████▉     | 3431/6932 [12:22<12:22,  4.71it/s]

Processing tickers:  50%|████▉     | 3432/6932 [12:22<12:35,  4.64it/s]

Processing tickers:  50%|████▉     | 3433/6932 [12:22<12:27,  4.68it/s]

Processing tickers:  50%|████▉     | 3434/6932 [12:22<12:20,  4.72it/s]

Processing tickers:  50%|████▉     | 3435/6932 [12:23<12:16,  4.75it/s]

Processing tickers:  50%|████▉     | 3436/6932 [12:23<12:30,  4.66it/s]

Processing tickers:  50%|████▉     | 3437/6932 [12:23<12:21,  4.71it/s]

Processing tickers:  50%|████▉     | 3438/6932 [12:23<12:16,  4.74it/s]

Processing tickers:  50%|████▉     | 3439/6932 [12:23<12:12,  4.77it/s]

Processing tickers:  50%|████▉     | 3440/6932 [12:24<12:10,  4.78it/s]

Processing tickers:  50%|████▉     | 3441/6932 [12:24<12:24,  4.69it/s]

Processing tickers:  50%|████▉     | 3442/6932 [12:24<12:17,  4.73it/s]

Processing tickers:  50%|████▉     | 3443/6932 [12:24<12:29,  4.65it/s]

Processing tickers:  50%|████▉     | 3444/6932 [12:24<12:21,  4.70it/s]

Processing tickers:  50%|████▉     | 3445/6932 [12:25<12:32,  4.64it/s]

Processing tickers:  50%|████▉     | 3446/6932 [12:25<12:24,  4.68it/s]

Processing tickers:  50%|████▉     | 3447/6932 [12:25<12:16,  4.73it/s]

Processing tickers:  50%|████▉     | 3448/6932 [12:25<12:32,  4.63it/s]

Processing tickers:  50%|████▉     | 3449/6932 [12:26<12:21,  4.70it/s]

Processing tickers:  50%|████▉     | 3450/6932 [12:26<12:16,  4.73it/s]

Processing tickers:  50%|████▉     | 3451/6932 [12:26<12:29,  4.64it/s]

Processing tickers:  50%|████▉     | 3452/6932 [12:26<12:23,  4.68it/s]

Processing tickers:  50%|████▉     | 3453/6932 [12:26<12:39,  4.58it/s]

Processing tickers:  50%|████▉     | 3454/6932 [12:27<12:23,  4.68it/s]

Processing tickers:  50%|████▉     | 3455/6932 [12:27<12:17,  4.72it/s]

Processing tickers:  50%|████▉     | 3456/6932 [12:27<12:12,  4.75it/s]

Processing tickers:  50%|████▉     | 3457/6932 [12:27<12:25,  4.66it/s]

Processing tickers:  50%|████▉     | 3458/6932 [12:27<12:19,  4.70it/s]

Processing tickers:  50%|████▉     | 3459/6932 [12:28<12:25,  4.66it/s]

Processing tickers:  50%|████▉     | 3460/6932 [12:28<12:07,  4.77it/s]

Processing tickers:  50%|████▉     | 3461/6932 [12:28<12:26,  4.65it/s]

Processing tickers:  50%|████▉     | 3462/6932 [12:28<12:20,  4.69it/s]

Processing tickers:  50%|████▉     | 3463/6932 [12:29<12:10,  4.75it/s]

Processing tickers:  50%|████▉     | 3464/6932 [12:29<12:24,  4.66it/s]

Processing tickers:  50%|████▉     | 3465/6932 [12:29<12:34,  4.60it/s]

Processing tickers:  50%|█████     | 3466/6932 [12:29<12:25,  4.65it/s]

Processing tickers:  50%|█████     | 3467/6932 [12:29<12:32,  4.61it/s]

Processing tickers:  50%|█████     | 3468/6932 [12:30<12:21,  4.67it/s]

Processing tickers:  50%|█████     | 3469/6932 [12:30<12:28,  4.62it/s]

Processing tickers:  50%|█████     | 3470/6932 [12:30<12:24,  4.65it/s]

Processing tickers:  50%|█████     | 3471/6932 [12:30<12:20,  4.67it/s]

Processing tickers:  50%|█████     | 3472/6932 [12:30<12:16,  4.70it/s]

Processing tickers:  50%|█████     | 3473/6932 [12:31<12:26,  4.64it/s]

Processing tickers:  50%|█████     | 3474/6932 [12:31<12:20,  4.67it/s]

Processing tickers:  50%|█████     | 3475/6932 [12:31<12:08,  4.75it/s]

Processing tickers:  50%|█████     | 3476/6932 [12:31<12:09,  4.74it/s]

Processing tickers:  50%|█████     | 3477/6932 [12:32<12:01,  4.79it/s]

Processing tickers:  50%|█████     | 3478/6932 [12:32<12:16,  4.69it/s]

Processing tickers:  50%|█████     | 3479/6932 [12:32<12:12,  4.71it/s]

Processing tickers:  50%|█████     | 3480/6932 [12:32<12:06,  4.75it/s]

Processing tickers:  50%|█████     | 3481/6932 [12:32<12:03,  4.77it/s]

Processing tickers:  50%|█████     | 3482/6932 [12:33<11:44,  4.89it/s]

Processing tickers:  50%|█████     | 3483/6932 [12:33<12:04,  4.76it/s]

Processing tickers:  50%|█████     | 3484/6932 [12:33<12:01,  4.78it/s]

Processing tickers:  50%|█████     | 3485/6932 [12:33<11:59,  4.79it/s]

Processing tickers:  50%|█████     | 3486/6932 [12:33<11:57,  4.80it/s]

Processing tickers:  50%|█████     | 3487/6932 [12:34<12:03,  4.76it/s]

Processing tickers:  50%|█████     | 3488/6932 [12:34<12:06,  4.74it/s]

Processing tickers:  50%|█████     | 3489/6932 [12:34<12:04,  4.76it/s]

Processing tickers:  50%|█████     | 3490/6932 [12:34<12:01,  4.77it/s]

Processing tickers:  50%|█████     | 3491/6932 [12:34<11:59,  4.78it/s]

Processing tickers:  50%|█████     | 3492/6932 [12:35<12:16,  4.67it/s]

Processing tickers:  50%|█████     | 3493/6932 [12:35<12:23,  4.62it/s]

Processing tickers:  50%|█████     | 3494/6932 [12:35<12:16,  4.67it/s]

Processing tickers:  50%|█████     | 3495/6932 [12:35<12:08,  4.72it/s]

Processing tickers:  50%|█████     | 3496/6932 [12:36<12:04,  4.74it/s]

Processing tickers:  50%|█████     | 3497/6932 [12:36<12:23,  4.62it/s]

Processing tickers:  50%|█████     | 3498/6932 [12:36<12:09,  4.71it/s]

Processing tickers:  50%|█████     | 3499/6932 [12:36<12:05,  4.73it/s]

Processing tickers:  50%|█████     | 3500/6932 [12:36<12:01,  4.75it/s]

Processing tickers:  51%|█████     | 3501/6932 [12:37<12:18,  4.65it/s]

Processing tickers:  51%|█████     | 3502/6932 [12:37<12:09,  4.70it/s]

Processing tickers:  51%|█████     | 3503/6932 [12:37<12:04,  4.73it/s]

Processing tickers:  51%|█████     | 3504/6932 [12:37<12:00,  4.76it/s]

Processing tickers:  51%|█████     | 3505/6932 [12:37<12:12,  4.68it/s]

Processing tickers:  51%|█████     | 3506/6932 [12:38<12:17,  4.64it/s]

Processing tickers:  51%|█████     | 3507/6932 [12:38<12:28,  4.57it/s]

Processing tickers:  51%|█████     | 3508/6932 [12:38<12:21,  4.62it/s]

Processing tickers:  51%|█████     | 3509/6932 [12:38<12:15,  4.66it/s]

Processing tickers:  51%|█████     | 3510/6932 [12:39<12:05,  4.72it/s]

Processing tickers:  51%|█████     | 3511/6932 [12:39<12:26,  4.59it/s]

Processing tickers:  51%|█████     | 3512/6932 [12:39<12:20,  4.62it/s]

Processing tickers:  51%|█████     | 3513/6932 [12:39<11:58,  4.76it/s]

Processing tickers:  51%|█████     | 3514/6932 [12:39<12:12,  4.67it/s]

Processing tickers:  51%|█████     | 3515/6932 [12:40<12:05,  4.71it/s]

Processing tickers:  51%|█████     | 3516/6932 [12:40<12:02,  4.73it/s]

Processing tickers:  51%|█████     | 3517/6932 [12:40<11:59,  4.75it/s]

Processing tickers:  51%|█████     | 3518/6932 [12:40<11:55,  4.77it/s]

Processing tickers:  51%|█████     | 3519/6932 [12:40<12:26,  4.57it/s]

Processing tickers:  51%|█████     | 3520/6932 [12:41<12:33,  4.53it/s]

Processing tickers:  51%|█████     | 3521/6932 [12:41<12:18,  4.62it/s]

Processing tickers:  51%|█████     | 3522/6932 [12:41<12:08,  4.68it/s]

Processing tickers:  51%|█████     | 3523/6932 [12:41<12:02,  4.72it/s]

Processing tickers:  51%|█████     | 3524/6932 [12:42<12:08,  4.68it/s]

Processing tickers:  51%|█████     | 3525/6932 [12:42<12:08,  4.67it/s]

Processing tickers:  51%|█████     | 3526/6932 [12:42<12:02,  4.71it/s]

Processing tickers:  51%|█████     | 3527/6932 [12:42<12:50,  4.42it/s]

Processing tickers:  51%|█████     | 3528/6932 [12:42<12:27,  4.55it/s]

Processing tickers:  51%|█████     | 3529/6932 [12:43<12:30,  4.53it/s]

Processing tickers:  51%|█████     | 3530/6932 [12:43<12:17,  4.62it/s]

Processing tickers:  51%|█████     | 3531/6932 [12:43<12:27,  4.55it/s]

Processing tickers:  51%|█████     | 3532/6932 [12:43<12:12,  4.64it/s]

Processing tickers:  51%|█████     | 3533/6932 [12:43<12:22,  4.58it/s]

Processing tickers:  51%|█████     | 3534/6932 [12:44<12:09,  4.66it/s]

Processing tickers:  51%|█████     | 3535/6932 [12:44<12:22,  4.58it/s]

Processing tickers:  51%|█████     | 3536/6932 [12:44<12:08,  4.66it/s]

Processing tickers:  51%|█████     | 3537/6932 [12:44<12:01,  4.71it/s]

Processing tickers:  51%|█████     | 3538/6932 [12:45<12:15,  4.61it/s]

Processing tickers:  51%|█████     | 3539/6932 [12:45<12:03,  4.69it/s]

Processing tickers:  51%|█████     | 3540/6932 [12:45<11:58,  4.72it/s]

Processing tickers:  51%|█████     | 3541/6932 [12:45<12:02,  4.70it/s]

Processing tickers:  51%|█████     | 3542/6932 [12:45<11:49,  4.78it/s]

Processing tickers:  51%|█████     | 3543/6932 [12:46<12:04,  4.68it/s]

Processing tickers:  51%|█████     | 3544/6932 [12:46<11:57,  4.72it/s]

Processing tickers:  51%|█████     | 3545/6932 [12:46<11:53,  4.75it/s]

Processing tickers:  51%|█████     | 3546/6932 [12:46<11:50,  4.77it/s]

Processing tickers:  51%|█████     | 3547/6932 [12:46<11:47,  4.79it/s]

Processing tickers:  51%|█████     | 3548/6932 [12:47<11:45,  4.80it/s]

Processing tickers:  51%|█████     | 3549/6932 [12:47<11:45,  4.80it/s]

Processing tickers:  51%|█████     | 3550/6932 [12:47<12:00,  4.69it/s]

Processing tickers:  51%|█████     | 3551/6932 [12:47<11:55,  4.73it/s]

Processing tickers:  51%|█████     | 3552/6932 [12:48<12:07,  4.65it/s]

Processing tickers:  51%|█████▏    | 3553/6932 [12:48<12:00,  4.69it/s]

Processing tickers:  51%|█████▏    | 3554/6932 [12:48<12:14,  4.60it/s]

Processing tickers:  51%|█████▏    | 3555/6932 [12:48<12:00,  4.68it/s]

Processing tickers:  51%|█████▏    | 3556/6932 [12:48<12:08,  4.63it/s]

Processing tickers:  51%|█████▏    | 3557/6932 [12:49<12:01,  4.68it/s]

Processing tickers:  51%|█████▏    | 3558/6932 [12:49<12:03,  4.67it/s]

Processing tickers:  51%|█████▏    | 3559/6932 [12:49<11:51,  4.74it/s]

Processing tickers:  51%|█████▏    | 3560/6932 [12:49<11:57,  4.70it/s]

Processing tickers:  51%|█████▏    | 3561/6932 [12:49<11:42,  4.80it/s]

Processing tickers:  51%|█████▏    | 3562/6932 [12:50<11:56,  4.71it/s]

Processing tickers:  51%|█████▏    | 3563/6932 [12:50<11:51,  4.73it/s]

Processing tickers:  51%|█████▏    | 3564/6932 [12:50<11:47,  4.76it/s]

Processing tickers:  51%|█████▏    | 3565/6932 [12:50<11:54,  4.71it/s]

Processing tickers:  51%|█████▏    | 3566/6932 [12:50<11:40,  4.81it/s]

Processing tickers:  51%|█████▏    | 3567/6932 [12:51<11:43,  4.78it/s]

Processing tickers:  51%|█████▏    | 3568/6932 [12:51<11:36,  4.83it/s]

Processing tickers:  51%|█████▏    | 3569/6932 [12:51<11:52,  4.72it/s]

Processing tickers:  52%|█████▏    | 3570/6932 [12:51<11:49,  4.74it/s]

Processing tickers:  52%|█████▏    | 3571/6932 [12:52<11:30,  4.87it/s]

Processing tickers:  52%|█████▏    | 3572/6932 [12:52<11:47,  4.75it/s]

Processing tickers:  52%|█████▏    | 3573/6932 [12:52<11:44,  4.77it/s]

Processing tickers:  52%|█████▏    | 3574/6932 [12:52<11:54,  4.70it/s]

Processing tickers:  52%|█████▏    | 3575/6932 [12:52<11:49,  4.73it/s]

Processing tickers:  52%|█████▏    | 3576/6932 [12:53<11:35,  4.82it/s]

Processing tickers:  52%|█████▏    | 3577/6932 [12:53<11:36,  4.82it/s]

Processing tickers:  52%|█████▏    | 3578/6932 [12:53<11:37,  4.81it/s]

Processing tickers:  52%|█████▏    | 3579/6932 [12:53<11:51,  4.71it/s]

Processing tickers:  52%|█████▏    | 3580/6932 [12:53<11:47,  4.74it/s]

Processing tickers:  52%|█████▏    | 3581/6932 [12:54<11:45,  4.75it/s]

Processing tickers:  52%|█████▏    | 3582/6932 [12:54<11:42,  4.77it/s]

Processing tickers:  52%|█████▏    | 3583/6932 [12:54<11:40,  4.78it/s]

Processing tickers:  52%|█████▏    | 3584/6932 [12:54<11:38,  4.79it/s]

Processing tickers:  52%|█████▏    | 3585/6932 [12:54<11:36,  4.80it/s]

Processing tickers:  52%|█████▏    | 3586/6932 [12:55<11:34,  4.82it/s]

Processing tickers:  52%|█████▏    | 3587/6932 [12:55<11:55,  4.67it/s]

Processing tickers:  52%|█████▏    | 3588/6932 [12:55<11:59,  4.65it/s]

Processing tickers:  52%|█████▏    | 3589/6932 [12:55<11:55,  4.67it/s]

Processing tickers:  52%|█████▏    | 3590/6932 [12:56<11:44,  4.74it/s]

Processing tickers:  52%|█████▏    | 3591/6932 [12:56<11:56,  4.66it/s]

Processing tickers:  52%|█████▏    | 3592/6932 [12:56<11:47,  4.72it/s]

Processing tickers:  52%|█████▏    | 3593/6932 [12:56<11:43,  4.74it/s]

Processing tickers:  52%|█████▏    | 3594/6932 [12:56<11:51,  4.69it/s]

Processing tickers:  52%|█████▏    | 3595/6932 [12:57<11:36,  4.79it/s]

Processing tickers:  52%|█████▏    | 3596/6932 [12:57<11:33,  4.81it/s]

Processing tickers:  52%|█████▏    | 3597/6932 [12:57<11:35,  4.80it/s]

Processing tickers:  52%|█████▏    | 3598/6932 [12:57<11:50,  4.70it/s]

Processing tickers:  52%|█████▏    | 3599/6932 [12:57<11:45,  4.73it/s]

Processing tickers:  52%|█████▏    | 3600/6932 [12:58<11:48,  4.70it/s]

Processing tickers:  52%|█████▏    | 3601/6932 [12:58<11:36,  4.78it/s]

Processing tickers:  52%|█████▏    | 3602/6932 [12:58<11:37,  4.77it/s]

Processing tickers:  52%|█████▏    | 3603/6932 [12:58<11:33,  4.80it/s]

Processing tickers:  52%|█████▏    | 3604/6932 [12:58<11:35,  4.79it/s]

Processing tickers:  52%|█████▏    | 3605/6932 [12:59<11:35,  4.78it/s]

Processing tickers:  52%|█████▏    | 3606/6932 [12:59<11:47,  4.70it/s]

Processing tickers:  52%|█████▏    | 3607/6932 [12:59<11:58,  4.63it/s]

Processing tickers:  52%|█████▏    | 3608/6932 [12:59<11:53,  4.66it/s]

Processing tickers:  52%|█████▏    | 3609/6932 [13:00<11:43,  4.72it/s]

Processing tickers:  52%|█████▏    | 3610/6932 [13:00<11:39,  4.75it/s]

Processing tickers:  52%|█████▏    | 3611/6932 [13:00<11:37,  4.76it/s]

Processing tickers:  52%|█████▏    | 3612/6932 [13:00<11:34,  4.78it/s]

Processing tickers:  52%|█████▏    | 3613/6932 [13:00<11:49,  4.68it/s]

Processing tickers:  52%|█████▏    | 3614/6932 [13:01<11:43,  4.72it/s]

Processing tickers:  52%|█████▏    | 3615/6932 [13:01<11:39,  4.74it/s]

Processing tickers:  52%|█████▏    | 3616/6932 [13:01<11:36,  4.76it/s]

Processing tickers:  52%|█████▏    | 3617/6932 [13:01<11:34,  4.77it/s]

Processing tickers:  52%|█████▏    | 3618/6932 [13:01<11:32,  4.78it/s]

Processing tickers:  52%|█████▏    | 3619/6932 [13:02<11:31,  4.79it/s]

Processing tickers:  52%|█████▏    | 3620/6932 [13:02<11:43,  4.71it/s]

Processing tickers:  52%|█████▏    | 3621/6932 [13:02<11:43,  4.71it/s]

Processing tickers:  52%|█████▏    | 3622/6932 [13:02<11:37,  4.75it/s]

Processing tickers:  52%|█████▏    | 3623/6932 [13:02<11:34,  4.77it/s]

Processing tickers:  52%|█████▏    | 3624/6932 [13:03<11:31,  4.78it/s]

Processing tickers:  52%|█████▏    | 3625/6932 [13:03<11:46,  4.68it/s]

Processing tickers:  52%|█████▏    | 3626/6932 [13:03<11:40,  4.72it/s]

Processing tickers:  52%|█████▏    | 3627/6932 [13:03<11:52,  4.64it/s]

Processing tickers:  52%|█████▏    | 3628/6932 [13:04<11:45,  4.68it/s]

Processing tickers:  52%|█████▏    | 3629/6932 [13:04<11:37,  4.73it/s]

Processing tickers:  52%|█████▏    | 3630/6932 [13:04<11:33,  4.76it/s]

Processing tickers:  52%|█████▏    | 3631/6932 [13:04<12:00,  4.58it/s]

Processing tickers:  52%|█████▏    | 3632/6932 [13:04<11:53,  4.63it/s]

Processing tickers:  52%|█████▏    | 3633/6932 [13:05<11:40,  4.71it/s]

Processing tickers:  52%|█████▏    | 3634/6932 [13:05<11:35,  4.74it/s]

Processing tickers:  52%|█████▏    | 3635/6932 [13:05<11:32,  4.76it/s]

Processing tickers:  52%|█████▏    | 3636/6932 [13:05<11:40,  4.70it/s]

Processing tickers:  52%|█████▏    | 3637/6932 [13:05<11:26,  4.80it/s]

Processing tickers:  52%|█████▏    | 3638/6932 [13:06<11:35,  4.74it/s]

Processing tickers:  52%|█████▏    | 3639/6932 [13:06<11:22,  4.83it/s]

Processing tickers:  53%|█████▎    | 3640/6932 [13:06<11:23,  4.82it/s]

Processing tickers:  53%|█████▎    | 3641/6932 [13:06<11:37,  4.72it/s]

Processing tickers:  53%|█████▎    | 3642/6932 [13:07<11:33,  4.75it/s]

Processing tickers:  53%|█████▎    | 3643/6932 [13:07<11:43,  4.68it/s]

Processing tickers:  53%|█████▎    | 3644/6932 [13:07<11:42,  4.68it/s]

Processing tickers:  53%|█████▎    | 3645/6932 [13:07<11:50,  4.63it/s]

Processing tickers:  53%|█████▎    | 3646/6932 [13:07<11:42,  4.67it/s]

Processing tickers:  53%|█████▎    | 3647/6932 [13:08<11:37,  4.71it/s]

Processing tickers:  53%|█████▎    | 3648/6932 [13:08<11:39,  4.70it/s]

Processing tickers:  53%|█████▎    | 3649/6932 [13:08<11:42,  4.67it/s]

Processing tickers:  53%|█████▎    | 3650/6932 [13:08<11:36,  4.71it/s]

Processing tickers:  53%|█████▎    | 3651/6932 [13:08<11:29,  4.76it/s]

Processing tickers:  53%|█████▎    | 3652/6932 [13:09<11:29,  4.75it/s]

Processing tickers:  53%|█████▎    | 3653/6932 [13:09<11:27,  4.77it/s]

Processing tickers:  53%|█████▎    | 3654/6932 [13:09<11:26,  4.78it/s]

Processing tickers:  53%|█████▎    | 3655/6932 [13:09<11:34,  4.72it/s]

Processing tickers:  53%|█████▎    | 3656/6932 [13:09<11:35,  4.71it/s]

Processing tickers:  53%|█████▎    | 3657/6932 [13:10<11:17,  4.83it/s]

Processing tickers:  53%|█████▎    | 3658/6932 [13:10<11:30,  4.74it/s]

Processing tickers:  53%|█████▎    | 3659/6932 [13:10<11:38,  4.69it/s]

Processing tickers:  53%|█████▎    | 3660/6932 [13:10<11:31,  4.73it/s]

Processing tickers:  53%|█████▎    | 3661/6932 [13:11<11:19,  4.81it/s]

Processing tickers:  53%|█████▎    | 3662/6932 [13:11<11:34,  4.71it/s]

Processing tickers:  53%|█████▎    | 3663/6932 [13:11<11:35,  4.70it/s]

Processing tickers:  53%|█████▎    | 3664/6932 [13:11<11:44,  4.64it/s]

Processing tickers:  53%|█████▎    | 3665/6932 [13:11<11:58,  4.55it/s]

Processing tickers:  53%|█████▎    | 3666/6932 [13:12<11:45,  4.63it/s]

Processing tickers:  53%|█████▎    | 3667/6932 [13:12<11:42,  4.65it/s]

Processing tickers:  53%|█████▎    | 3668/6932 [13:12<11:36,  4.69it/s]

Processing tickers:  53%|█████▎    | 3669/6932 [13:12<11:30,  4.73it/s]

Processing tickers:  53%|█████▎    | 3670/6932 [13:12<11:27,  4.74it/s]

Processing tickers:  53%|█████▎    | 3671/6932 [13:13<12:43,  4.27it/s]

Processing tickers:  53%|█████▎    | 3672/6932 [13:13<12:18,  4.41it/s]

Processing tickers:  53%|█████▎    | 3673/6932 [13:13<12:51,  4.22it/s]

Processing tickers:  53%|█████▎    | 3674/6932 [13:13<12:18,  4.41it/s]

Processing tickers:  53%|█████▎    | 3675/6932 [13:14<12:00,  4.52it/s]

Processing tickers:  53%|█████▎    | 3676/6932 [13:14<11:48,  4.60it/s]

Processing tickers:  53%|█████▎    | 3677/6932 [13:14<11:41,  4.64it/s]

Processing tickers:  53%|█████▎    | 3678/6932 [13:14<11:31,  4.71it/s]

Processing tickers:  53%|█████▎    | 3679/6932 [13:14<11:27,  4.73it/s]

Processing tickers:  53%|█████▎    | 3680/6932 [13:15<11:27,  4.73it/s]

Processing tickers:  53%|█████▎    | 3681/6932 [13:15<11:21,  4.77it/s]

Processing tickers:  53%|█████▎    | 3682/6932 [13:15<11:19,  4.78it/s]

Processing tickers:  53%|█████▎    | 3683/6932 [13:15<11:18,  4.79it/s]

Processing tickers:  53%|█████▎    | 3684/6932 [13:16<11:21,  4.76it/s]

Processing tickers:  53%|█████▎    | 3685/6932 [13:16<11:31,  4.69it/s]

Processing tickers:  53%|█████▎    | 3686/6932 [13:16<11:30,  4.70it/s]

Processing tickers:  53%|█████▎    | 3687/6932 [13:16<12:42,  4.25it/s]

Processing tickers:  53%|█████▎    | 3688/6932 [13:16<12:13,  4.42it/s]

Processing tickers:  53%|█████▎    | 3689/6932 [13:17<11:55,  4.54it/s]

Processing tickers:  53%|█████▎    | 3690/6932 [13:17<11:42,  4.62it/s]

Processing tickers:  53%|█████▎    | 3691/6932 [13:17<11:18,  4.78it/s]

Processing tickers:  53%|█████▎    | 3692/6932 [13:17<11:33,  4.67it/s]

Processing tickers:  53%|█████▎    | 3693/6932 [13:17<11:26,  4.72it/s]

Processing tickers:  53%|█████▎    | 3694/6932 [13:18<11:24,  4.73it/s]

Processing tickers:  53%|█████▎    | 3695/6932 [13:18<11:19,  4.77it/s]

Processing tickers:  53%|█████▎    | 3696/6932 [13:18<11:19,  4.76it/s]

Processing tickers:  53%|█████▎    | 3697/6932 [13:18<11:15,  4.79it/s]

Processing tickers:  53%|█████▎    | 3698/6932 [13:19<11:14,  4.79it/s]

Processing tickers:  53%|█████▎    | 3699/6932 [13:19<11:31,  4.67it/s]

Processing tickers:  53%|█████▎    | 3700/6932 [13:19<11:25,  4.72it/s]

Processing tickers:  53%|█████▎    | 3701/6932 [13:19<11:19,  4.75it/s]

Processing tickers:  53%|█████▎    | 3702/6932 [13:19<11:17,  4.77it/s]

Processing tickers:  53%|█████▎    | 3703/6932 [13:20<11:15,  4.78it/s]

Processing tickers:  53%|█████▎    | 3704/6932 [13:20<11:13,  4.79it/s]

Processing tickers:  53%|█████▎    | 3705/6932 [13:20<11:13,  4.79it/s]

Processing tickers:  53%|█████▎    | 3706/6932 [13:20<11:13,  4.79it/s]

Processing tickers:  53%|█████▎    | 3707/6932 [13:20<11:12,  4.79it/s]

Processing tickers:  53%|█████▎    | 3708/6932 [13:21<11:16,  4.76it/s]

Processing tickers:  54%|█████▎    | 3709/6932 [13:21<11:26,  4.70it/s]

Processing tickers:  54%|█████▎    | 3710/6932 [13:21<11:21,  4.73it/s]

Processing tickers:  54%|█████▎    | 3711/6932 [13:21<11:30,  4.66it/s]

Processing tickers:  54%|█████▎    | 3712/6932 [13:21<11:27,  4.69it/s]

Processing tickers:  54%|█████▎    | 3713/6932 [13:22<11:05,  4.83it/s]

Processing tickers:  54%|█████▎    | 3714/6932 [13:22<11:25,  4.70it/s]

Processing tickers:  54%|█████▎    | 3715/6932 [13:22<11:17,  4.74it/s]

Processing tickers:  54%|█████▎    | 3716/6932 [13:22<11:00,  4.87it/s]

Processing tickers:  54%|█████▎    | 3717/6932 [13:23<11:18,  4.74it/s]

Processing tickers:  54%|█████▎    | 3718/6932 [13:23<11:31,  4.65it/s]

Processing tickers:  54%|█████▎    | 3719/6932 [13:23<11:40,  4.59it/s]

Processing tickers:  54%|█████▎    | 3720/6932 [13:23<11:30,  4.65it/s]

Processing tickers:  54%|█████▎    | 3721/6932 [13:23<11:23,  4.70it/s]

Processing tickers:  54%|█████▎    | 3722/6932 [13:24<11:18,  4.73it/s]

Processing tickers:  54%|█████▎    | 3723/6932 [13:24<11:14,  4.75it/s]

Processing tickers:  54%|█████▎    | 3724/6932 [13:24<11:28,  4.66it/s]

Processing tickers:  54%|█████▎    | 3725/6932 [13:24<11:20,  4.71it/s]

Processing tickers:  54%|█████▍    | 3726/6932 [13:24<11:29,  4.65it/s]

Processing tickers:  54%|█████▍    | 3727/6932 [13:25<11:22,  4.70it/s]

Processing tickers:  54%|█████▍    | 3728/6932 [13:25<11:37,  4.59it/s]

Processing tickers:  54%|█████▍    | 3729/6932 [13:25<11:23,  4.68it/s]

Processing tickers:  54%|█████▍    | 3730/6932 [13:25<11:25,  4.67it/s]

Processing tickers:  54%|█████▍    | 3731/6932 [13:26<11:12,  4.76it/s]

Processing tickers:  54%|█████▍    | 3732/6932 [13:26<11:26,  4.66it/s]

Processing tickers:  54%|█████▍    | 3733/6932 [13:26<11:22,  4.69it/s]

Processing tickers:  54%|█████▍    | 3734/6932 [13:26<11:16,  4.73it/s]

Processing tickers:  54%|█████▍    | 3735/6932 [13:26<11:09,  4.77it/s]

Processing tickers:  54%|█████▍    | 3736/6932 [13:27<11:21,  4.69it/s]

Processing tickers:  54%|█████▍    | 3737/6932 [13:27<11:16,  4.72it/s]

Processing tickers:  54%|█████▍    | 3738/6932 [13:27<11:13,  4.74it/s]

Processing tickers:  54%|█████▍    | 3739/6932 [13:27<11:09,  4.77it/s]

Processing tickers:  54%|█████▍    | 3740/6932 [13:27<11:10,  4.76it/s]

Processing tickers:  54%|█████▍    | 3741/6932 [13:28<10:50,  4.90it/s]

Processing tickers:  54%|█████▍    | 3742/6932 [13:28<10:54,  4.87it/s]

Processing tickers:  54%|█████▍    | 3743/6932 [13:28<11:14,  4.73it/s]

Processing tickers:  54%|█████▍    | 3744/6932 [13:28<11:11,  4.75it/s]

Processing tickers:  54%|█████▍    | 3745/6932 [13:28<11:05,  4.79it/s]

Processing tickers:  54%|█████▍    | 3746/6932 [13:29<11:07,  4.77it/s]

Processing tickers:  54%|█████▍    | 3747/6932 [13:29<11:02,  4.81it/s]

Processing tickers:  54%|█████▍    | 3748/6932 [13:29<11:18,  4.70it/s]

Processing tickers:  54%|█████▍    | 3749/6932 [13:29<11:14,  4.72it/s]

Processing tickers:  54%|█████▍    | 3750/6932 [13:30<11:09,  4.75it/s]

Processing tickers:  54%|█████▍    | 3751/6932 [13:30<11:07,  4.77it/s]

Processing tickers:  54%|█████▍    | 3752/6932 [13:30<11:18,  4.69it/s]

Processing tickers:  54%|█████▍    | 3753/6932 [13:30<11:16,  4.70it/s]

Processing tickers:  54%|█████▍    | 3754/6932 [13:30<11:12,  4.73it/s]

Processing tickers:  54%|█████▍    | 3755/6932 [13:31<11:08,  4.75it/s]

Processing tickers:  54%|█████▍    | 3756/6932 [13:31<11:21,  4.66it/s]

Processing tickers:  54%|█████▍    | 3757/6932 [13:31<11:15,  4.70it/s]

Processing tickers:  54%|█████▍    | 3758/6932 [13:31<11:10,  4.73it/s]

Processing tickers:  54%|█████▍    | 3759/6932 [13:31<11:23,  4.65it/s]

Processing tickers:  54%|█████▍    | 3760/6932 [13:32<11:15,  4.69it/s]

Processing tickers:  54%|█████▍    | 3761/6932 [13:32<11:10,  4.73it/s]

Processing tickers:  54%|█████▍    | 3762/6932 [13:32<11:12,  4.72it/s]

Processing tickers:  54%|█████▍    | 3763/6932 [13:32<11:03,  4.78it/s]

Processing tickers:  54%|█████▍    | 3764/6932 [13:32<11:02,  4.78it/s]

Processing tickers:  54%|█████▍    | 3765/6932 [13:33<11:02,  4.78it/s]

Processing tickers:  54%|█████▍    | 3766/6932 [13:33<10:59,  4.80it/s]

Processing tickers:  54%|█████▍    | 3767/6932 [13:33<11:11,  4.71it/s]

Processing tickers:  54%|█████▍    | 3768/6932 [13:33<11:10,  4.72it/s]

Processing tickers:  54%|█████▍    | 3769/6932 [13:34<11:06,  4.75it/s]

Processing tickers:  54%|█████▍    | 3770/6932 [13:34<11:02,  4.77it/s]

Processing tickers:  54%|█████▍    | 3771/6932 [13:34<11:15,  4.68it/s]

Processing tickers:  54%|█████▍    | 3772/6932 [13:34<11:22,  4.63it/s]

Processing tickers:  54%|█████▍    | 3773/6932 [13:34<11:13,  4.69it/s]

Processing tickers:  54%|█████▍    | 3774/6932 [13:35<11:07,  4.73it/s]

Processing tickers:  54%|█████▍    | 3775/6932 [13:35<11:04,  4.75it/s]

Processing tickers:  54%|█████▍    | 3776/6932 [13:35<11:08,  4.72it/s]

Processing tickers:  54%|█████▍    | 3777/6932 [13:35<11:01,  4.77it/s]

Processing tickers:  55%|█████▍    | 3778/6932 [13:35<10:58,  4.79it/s]

Processing tickers:  55%|█████▍    | 3779/6932 [13:36<10:57,  4.80it/s]

Processing tickers:  55%|█████▍    | 3780/6932 [13:36<10:56,  4.80it/s]

Processing tickers:  55%|█████▍    | 3781/6932 [13:36<11:01,  4.76it/s]

Processing tickers:  55%|█████▍    | 3782/6932 [13:36<10:53,  4.82it/s]

Processing tickers:  55%|█████▍    | 3783/6932 [13:36<11:08,  4.71it/s]

Processing tickers:  55%|█████▍    | 3784/6932 [13:37<11:04,  4.74it/s]

Processing tickers:  55%|█████▍    | 3785/6932 [13:37<11:01,  4.76it/s]

Processing tickers:  55%|█████▍    | 3786/6932 [13:37<10:59,  4.77it/s]

Processing tickers:  55%|█████▍    | 3787/6932 [13:37<10:57,  4.78it/s]

Processing tickers:  55%|█████▍    | 3788/6932 [13:38<11:25,  4.58it/s]

Processing tickers:  55%|█████▍    | 3789/6932 [13:38<11:14,  4.66it/s]

Processing tickers:  55%|█████▍    | 3790/6932 [13:38<11:09,  4.69it/s]

Processing tickers:  55%|█████▍    | 3791/6932 [13:38<11:17,  4.63it/s]

Processing tickers:  55%|█████▍    | 3792/6932 [13:38<11:10,  4.69it/s]

Processing tickers:  55%|█████▍    | 3793/6932 [13:39<11:04,  4.72it/s]

Processing tickers:  55%|█████▍    | 3794/6932 [13:39<11:02,  4.74it/s]

Processing tickers:  55%|█████▍    | 3795/6932 [13:39<10:57,  4.77it/s]

Processing tickers:  55%|█████▍    | 3796/6932 [13:39<10:55,  4.78it/s]

Processing tickers:  55%|█████▍    | 3797/6932 [13:39<10:58,  4.76it/s]

Processing tickers:  55%|█████▍    | 3798/6932 [13:40<10:51,  4.81it/s]

Processing tickers:  55%|█████▍    | 3799/6932 [13:40<10:51,  4.81it/s]

Processing tickers:  55%|█████▍    | 3800/6932 [13:40<10:53,  4.79it/s]

Processing tickers:  55%|█████▍    | 3801/6932 [13:40<10:55,  4.78it/s]

Processing tickers:  55%|█████▍    | 3802/6932 [13:40<10:51,  4.81it/s]

Processing tickers:  55%|█████▍    | 3803/6932 [13:41<10:55,  4.77it/s]

Processing tickers:  55%|█████▍    | 3804/6932 [13:41<11:01,  4.73it/s]

Processing tickers:  55%|█████▍    | 3805/6932 [13:41<11:13,  4.64it/s]

Processing tickers:  55%|█████▍    | 3806/6932 [13:41<11:09,  4.67it/s]

Processing tickers:  55%|█████▍    | 3807/6932 [13:42<10:59,  4.74it/s]

Processing tickers:  55%|█████▍    | 3808/6932 [13:42<10:56,  4.76it/s]

Processing tickers:  55%|█████▍    | 3809/6932 [13:42<10:53,  4.78it/s]

Processing tickers:  55%|█████▍    | 3810/6932 [13:42<10:59,  4.73it/s]

Processing tickers:  55%|█████▍    | 3811/6932 [13:42<10:48,  4.81it/s]

Processing tickers:  55%|█████▍    | 3812/6932 [13:43<10:48,  4.81it/s]

Processing tickers:  55%|█████▌    | 3813/6932 [13:43<11:02,  4.71it/s]

Processing tickers:  55%|█████▌    | 3814/6932 [13:43<11:14,  4.62it/s]

Processing tickers:  55%|█████▌    | 3815/6932 [13:43<11:07,  4.67it/s]

Processing tickers:  55%|█████▌    | 3816/6932 [13:43<10:59,  4.72it/s]

Processing tickers:  55%|█████▌    | 3817/6932 [13:44<10:55,  4.76it/s]

Processing tickers:  55%|█████▌    | 3818/6932 [13:44<11:09,  4.65it/s]

Processing tickers:  55%|█████▌    | 3819/6932 [13:44<10:59,  4.72it/s]

Processing tickers:  55%|█████▌    | 3820/6932 [13:44<10:44,  4.83it/s]

Processing tickers:  55%|█████▌    | 3821/6932 [13:45<10:58,  4.72it/s]

Processing tickers:  55%|█████▌    | 3822/6932 [13:45<10:54,  4.75it/s]

Processing tickers:  55%|█████▌    | 3823/6932 [13:45<10:58,  4.72it/s]

Processing tickers:  55%|█████▌    | 3824/6932 [13:45<11:02,  4.69it/s]

Processing tickers:  55%|█████▌    | 3825/6932 [13:45<10:59,  4.71it/s]

Processing tickers:  55%|█████▌    | 3826/6932 [13:46<10:57,  4.73it/s]

Processing tickers:  55%|█████▌    | 3827/6932 [13:46<10:49,  4.78it/s]

Processing tickers:  55%|█████▌    | 3828/6932 [13:46<11:03,  4.68it/s]

Processing tickers:  55%|█████▌    | 3829/6932 [13:46<10:59,  4.71it/s]

Processing tickers:  55%|█████▌    | 3830/6932 [13:46<10:55,  4.74it/s]

Processing tickers:  55%|█████▌    | 3831/6932 [13:47<10:52,  4.76it/s]

Processing tickers:  55%|█████▌    | 3832/6932 [13:47<10:53,  4.75it/s]

Processing tickers:  55%|█████▌    | 3833/6932 [13:47<10:51,  4.75it/s]

Processing tickers:  55%|█████▌    | 3834/6932 [13:47<10:46,  4.79it/s]

Processing tickers:  55%|█████▌    | 3835/6932 [13:47<10:44,  4.81it/s]

Processing tickers:  55%|█████▌    | 3836/6932 [13:48<10:48,  4.77it/s]

Processing tickers:  55%|█████▌    | 3837/6932 [13:48<10:42,  4.81it/s]

Processing tickers:  55%|█████▌    | 3838/6932 [13:48<10:43,  4.81it/s]

Processing tickers:  55%|█████▌    | 3839/6932 [13:48<11:01,  4.68it/s]

Processing tickers:  55%|█████▌    | 3840/6932 [13:49<11:09,  4.62it/s]

Processing tickers:  55%|█████▌    | 3841/6932 [13:49<11:30,  4.47it/s]

Processing tickers:  55%|█████▌    | 3842/6932 [13:49<11:14,  4.58it/s]

Processing tickers:  55%|█████▌    | 3843/6932 [13:49<11:03,  4.65it/s]

Processing tickers:  55%|█████▌    | 3844/6932 [13:49<11:02,  4.66it/s]

Processing tickers:  55%|█████▌    | 3845/6932 [13:50<10:54,  4.72it/s]

Processing tickers:  55%|█████▌    | 3846/6932 [13:50<10:57,  4.69it/s]

Processing tickers:  55%|█████▌    | 3847/6932 [13:50<10:53,  4.72it/s]

Processing tickers:  56%|█████▌    | 3848/6932 [13:50<10:55,  4.70it/s]

Processing tickers:  56%|█████▌    | 3849/6932 [13:50<10:47,  4.76it/s]

Processing tickers:  56%|█████▌    | 3850/6932 [13:51<10:48,  4.75it/s]

Processing tickers:  56%|█████▌    | 3851/6932 [13:51<10:43,  4.79it/s]

Processing tickers:  56%|█████▌    | 3852/6932 [13:51<10:56,  4.69it/s]

Processing tickers:  56%|█████▌    | 3853/6932 [13:51<10:51,  4.72it/s]

Processing tickers:  56%|█████▌    | 3854/6932 [13:51<10:33,  4.86it/s]

Processing tickers:  56%|█████▌    | 3855/6932 [13:52<11:04,  4.63it/s]

Processing tickers:  56%|█████▌    | 3856/6932 [13:52<10:57,  4.68it/s]

Processing tickers:  56%|█████▌    | 3857/6932 [13:52<10:51,  4.72it/s]

Processing tickers:  56%|█████▌    | 3858/6932 [13:52<10:49,  4.73it/s]

Processing tickers:  56%|█████▌    | 3859/6932 [13:53<10:47,  4.75it/s]

Processing tickers:  56%|█████▌    | 3860/6932 [13:53<10:51,  4.72it/s]

Processing tickers:  56%|█████▌    | 3861/6932 [13:53<10:37,  4.82it/s]

Processing tickers:  56%|█████▌    | 3862/6932 [13:53<10:37,  4.82it/s]

Processing tickers:  56%|█████▌    | 3863/6932 [13:53<10:55,  4.68it/s]

Processing tickers:  56%|█████▌    | 3864/6932 [13:54<10:47,  4.74it/s]

Processing tickers:  56%|█████▌    | 3865/6932 [13:54<11:00,  4.64it/s]

Processing tickers:  56%|█████▌    | 3866/6932 [13:54<10:50,  4.72it/s]

Processing tickers:  56%|█████▌    | 3867/6932 [13:54<10:45,  4.75it/s]

Processing tickers:  56%|█████▌    | 3868/6932 [13:54<10:45,  4.74it/s]

Processing tickers:  56%|█████▌    | 3869/6932 [13:55<10:47,  4.73it/s]

Processing tickers:  56%|█████▌    | 3870/6932 [13:55<10:53,  4.69it/s]

Processing tickers:  56%|█████▌    | 3871/6932 [13:55<10:47,  4.73it/s]

Processing tickers:  56%|█████▌    | 3872/6932 [13:55<10:44,  4.75it/s]

Processing tickers:  56%|█████▌    | 3873/6932 [13:56<10:42,  4.76it/s]

Processing tickers:  56%|█████▌    | 3874/6932 [13:56<10:55,  4.66it/s]

Processing tickers:  56%|█████▌    | 3875/6932 [13:56<10:57,  4.65it/s]

Processing tickers:  56%|█████▌    | 3876/6932 [13:56<10:40,  4.77it/s]

Processing tickers:  56%|█████▌    | 3877/6932 [13:56<10:51,  4.69it/s]

Processing tickers:  56%|█████▌    | 3878/6932 [13:57<10:49,  4.70it/s]

Processing tickers:  56%|█████▌    | 3879/6932 [13:57<10:42,  4.75it/s]

Processing tickers:  56%|█████▌    | 3880/6932 [13:57<10:48,  4.71it/s]

Processing tickers:  56%|█████▌    | 3881/6932 [13:57<10:44,  4.74it/s]

Processing tickers:  56%|█████▌    | 3882/6932 [13:57<10:34,  4.81it/s]

Processing tickers:  56%|█████▌    | 3883/6932 [13:58<10:34,  4.81it/s]

Processing tickers:  56%|█████▌    | 3884/6932 [13:58<10:48,  4.70it/s]

Processing tickers:  56%|█████▌    | 3885/6932 [13:58<10:44,  4.73it/s]

Processing tickers:  56%|█████▌    | 3886/6932 [13:58<10:55,  4.65it/s]

Processing tickers:  56%|█████▌    | 3887/6932 [13:58<10:45,  4.72it/s]

Processing tickers:  56%|█████▌    | 3888/6932 [13:59<10:41,  4.75it/s]

Processing tickers:  56%|█████▌    | 3889/6932 [13:59<10:38,  4.77it/s]

Processing tickers:  56%|█████▌    | 3890/6932 [13:59<11:06,  4.57it/s]

Processing tickers:  56%|█████▌    | 3891/6932 [13:59<10:55,  4.64it/s]

Processing tickers:  56%|█████▌    | 3892/6932 [14:00<10:47,  4.70it/s]

Processing tickers:  56%|█████▌    | 3893/6932 [14:00<10:42,  4.73it/s]

Processing tickers:  56%|█████▌    | 3894/6932 [14:00<10:38,  4.76it/s]

Processing tickers:  56%|█████▌    | 3895/6932 [14:00<10:51,  4.66it/s]

Processing tickers:  56%|█████▌    | 3896/6932 [14:00<10:46,  4.69it/s]

Processing tickers:  56%|█████▌    | 3897/6932 [14:01<10:40,  4.74it/s]

Processing tickers:  56%|█████▌    | 3898/6932 [14:01<10:37,  4.76it/s]

Processing tickers:  56%|█████▌    | 3899/6932 [14:01<10:46,  4.69it/s]

Processing tickers:  56%|█████▋    | 3900/6932 [14:01<10:40,  4.73it/s]

Processing tickers:  56%|█████▋    | 3901/6932 [14:01<10:26,  4.83it/s]

Processing tickers:  56%|█████▋    | 3902/6932 [14:02<10:28,  4.82it/s]

Processing tickers:  56%|█████▋    | 3903/6932 [14:02<10:41,  4.72it/s]

Processing tickers:  56%|█████▋    | 3904/6932 [14:02<10:46,  4.68it/s]

Processing tickers:  56%|█████▋    | 3905/6932 [14:02<10:33,  4.78it/s]

Processing tickers:  56%|█████▋    | 3906/6932 [14:03<10:32,  4.79it/s]

Processing tickers:  56%|█████▋    | 3907/6932 [14:03<10:50,  4.65it/s]

Processing tickers:  56%|█████▋    | 3908/6932 [14:03<10:52,  4.63it/s]

Processing tickers:  56%|█████▋    | 3909/6932 [14:03<10:45,  4.68it/s]

Processing tickers:  56%|█████▋    | 3910/6932 [14:03<10:44,  4.69it/s]

Processing tickers:  56%|█████▋    | 3911/6932 [14:04<10:34,  4.76it/s]

Processing tickers:  56%|█████▋    | 3912/6932 [14:04<10:32,  4.78it/s]

Processing tickers:  56%|█████▋    | 3913/6932 [14:04<10:30,  4.79it/s]

Processing tickers:  56%|█████▋    | 3914/6932 [14:04<10:29,  4.80it/s]

Processing tickers:  56%|█████▋    | 3915/6932 [14:04<10:26,  4.81it/s]

Processing tickers:  56%|█████▋    | 3916/6932 [14:05<10:39,  4.72it/s]

Processing tickers:  57%|█████▋    | 3917/6932 [14:05<10:48,  4.65it/s]

Processing tickers:  57%|█████▋    | 3918/6932 [14:05<10:44,  4.68it/s]

Processing tickers:  57%|█████▋    | 3919/6932 [14:05<10:38,  4.72it/s]

Processing tickers:  57%|█████▋    | 3920/6932 [14:05<10:34,  4.75it/s]

Processing tickers:  57%|█████▋    | 3921/6932 [14:06<10:32,  4.76it/s]

Processing tickers:  57%|█████▋    | 3922/6932 [14:06<10:28,  4.79it/s]

Processing tickers:  57%|█████▋    | 3923/6932 [14:06<10:28,  4.79it/s]

Processing tickers:  57%|█████▋    | 3924/6932 [14:06<10:26,  4.80it/s]

Processing tickers:  57%|█████▋    | 3925/6932 [14:07<10:26,  4.80it/s]

Processing tickers:  57%|█████▋    | 3926/6932 [14:07<10:41,  4.68it/s]

Processing tickers:  57%|█████▋    | 3927/6932 [14:07<10:38,  4.70it/s]

Processing tickers:  57%|█████▋    | 3928/6932 [14:07<10:30,  4.76it/s]

Processing tickers:  57%|█████▋    | 3929/6932 [14:07<10:29,  4.77it/s]

Processing tickers:  57%|█████▋    | 3930/6932 [14:08<10:25,  4.80it/s]

Processing tickers:  57%|█████▋    | 3931/6932 [14:08<10:27,  4.78it/s]

Processing tickers:  57%|█████▋    | 3932/6932 [14:08<10:28,  4.78it/s]

Processing tickers:  57%|█████▋    | 3933/6932 [14:08<10:21,  4.82it/s]

Processing tickers:  57%|█████▋    | 3934/6932 [14:08<10:28,  4.77it/s]

Processing tickers:  57%|█████▋    | 3935/6932 [14:09<10:25,  4.79it/s]

Processing tickers:  57%|█████▋    | 3936/6932 [14:09<10:19,  4.84it/s]

Processing tickers:  57%|█████▋    | 3937/6932 [14:09<10:21,  4.82it/s]

Processing tickers:  57%|█████▋    | 3938/6932 [14:09<10:21,  4.82it/s]

Processing tickers:  57%|█████▋    | 3939/6932 [14:09<10:25,  4.78it/s]

Processing tickers:  57%|█████▋    | 3940/6932 [14:10<10:35,  4.71it/s]

Processing tickers:  57%|█████▋    | 3941/6932 [14:10<10:31,  4.73it/s]

Processing tickers:  57%|█████▋    | 3942/6932 [14:10<10:31,  4.73it/s]

Processing tickers:  57%|█████▋    | 3943/6932 [14:10<10:26,  4.77it/s]

Processing tickers:  57%|█████▋    | 3944/6932 [14:10<10:24,  4.78it/s]

Processing tickers:  57%|█████▋    | 3945/6932 [14:11<10:23,  4.79it/s]

Processing tickers:  57%|█████▋    | 3946/6932 [14:11<10:22,  4.80it/s]

Processing tickers:  57%|█████▋    | 3947/6932 [14:11<10:21,  4.80it/s]

Processing tickers:  57%|█████▋    | 3948/6932 [14:11<10:20,  4.81it/s]

Processing tickers:  57%|█████▋    | 3949/6932 [14:12<10:37,  4.68it/s]

Processing tickers:  57%|█████▋    | 3950/6932 [14:12<10:32,  4.71it/s]

Processing tickers:  57%|█████▋    | 3951/6932 [14:12<10:26,  4.76it/s]

Processing tickers:  57%|█████▋    | 3952/6932 [14:12<10:24,  4.77it/s]

Processing tickers:  57%|█████▋    | 3953/6932 [14:12<10:22,  4.79it/s]

Processing tickers:  57%|█████▋    | 3954/6932 [14:13<10:23,  4.78it/s]

Processing tickers:  57%|█████▋    | 3955/6932 [14:13<10:19,  4.81it/s]

Processing tickers:  57%|█████▋    | 3956/6932 [14:13<10:19,  4.80it/s]

Processing tickers:  57%|█████▋    | 3957/6932 [14:13<10:19,  4.80it/s]

Processing tickers:  57%|█████▋    | 3958/6932 [14:13<10:19,  4.80it/s]

Processing tickers:  57%|█████▋    | 3959/6932 [14:14<10:32,  4.70it/s]

Processing tickers:  57%|█████▋    | 3960/6932 [14:14<10:27,  4.74it/s]

Processing tickers:  57%|█████▋    | 3961/6932 [14:14<10:52,  4.55it/s]

Processing tickers:  57%|█████▋    | 3962/6932 [14:14<10:27,  4.73it/s]

Processing tickers:  57%|█████▋    | 3963/6932 [14:14<10:24,  4.75it/s]

Processing tickers:  57%|█████▋    | 3964/6932 [14:15<10:36,  4.66it/s]

Processing tickers:  57%|█████▋    | 3965/6932 [14:15<10:30,  4.71it/s]

Processing tickers:  57%|█████▋    | 3966/6932 [14:15<10:30,  4.70it/s]

Processing tickers:  57%|█████▋    | 3967/6932 [14:15<10:22,  4.76it/s]

Processing tickers:  57%|█████▋    | 3968/6932 [14:16<10:20,  4.77it/s]

Processing tickers:  57%|█████▋    | 3969/6932 [14:16<10:19,  4.78it/s]

Processing tickers:  57%|█████▋    | 3970/6932 [14:16<10:32,  4.69it/s]

Processing tickers:  57%|█████▋    | 3971/6932 [14:16<10:27,  4.72it/s]

Processing tickers:  57%|█████▋    | 3972/6932 [14:16<10:24,  4.74it/s]

Processing tickers:  57%|█████▋    | 3973/6932 [14:17<10:20,  4.77it/s]

Processing tickers:  57%|█████▋    | 3974/6932 [14:17<10:19,  4.78it/s]

Processing tickers:  57%|█████▋    | 3975/6932 [14:17<10:19,  4.77it/s]

Processing tickers:  57%|█████▋    | 3976/6932 [14:17<10:15,  4.80it/s]

Processing tickers:  57%|█████▋    | 3977/6932 [14:17<10:22,  4.75it/s]

Processing tickers:  57%|█████▋    | 3978/6932 [14:18<10:15,  4.80it/s]

Processing tickers:  57%|█████▋    | 3979/6932 [14:18<10:26,  4.71it/s]

Processing tickers:  57%|█████▋    | 3980/6932 [14:18<10:23,  4.73it/s]

Processing tickers:  57%|█████▋    | 3981/6932 [14:18<10:25,  4.72it/s]

Processing tickers:  57%|█████▋    | 3982/6932 [14:18<10:16,  4.79it/s]

Processing tickers:  57%|█████▋    | 3983/6932 [14:19<10:14,  4.80it/s]

Processing tickers:  57%|█████▋    | 3984/6932 [14:19<10:30,  4.68it/s]

Processing tickers:  57%|█████▋    | 3985/6932 [14:19<10:23,  4.73it/s]

Processing tickers:  58%|█████▊    | 3986/6932 [14:19<10:19,  4.75it/s]

Processing tickers:  58%|█████▊    | 3987/6932 [14:20<10:18,  4.76it/s]

Processing tickers:  58%|█████▊    | 3988/6932 [14:20<10:32,  4.65it/s]

Processing tickers:  58%|█████▊    | 3989/6932 [14:20<10:36,  4.63it/s]

Processing tickers:  58%|█████▊    | 3990/6932 [14:20<10:31,  4.66it/s]

Processing tickers:  58%|█████▊    | 3991/6932 [14:20<10:24,  4.71it/s]

Processing tickers:  58%|█████▊    | 3992/6932 [14:21<10:36,  4.62it/s]

Processing tickers:  58%|█████▊    | 3993/6932 [14:21<10:30,  4.66it/s]

Processing tickers:  58%|█████▊    | 3994/6932 [14:21<10:22,  4.72it/s]

Processing tickers:  58%|█████▊    | 3995/6932 [14:21<10:18,  4.75it/s]

Processing tickers:  58%|█████▊    | 3996/6932 [14:21<10:15,  4.77it/s]

Processing tickers:  58%|█████▊    | 3997/6932 [14:22<10:24,  4.70it/s]

Processing tickers:  58%|█████▊    | 3998/6932 [14:22<10:09,  4.81it/s]

Processing tickers:  58%|█████▊    | 3999/6932 [14:22<10:30,  4.65it/s]

Processing tickers:  58%|█████▊    | 4000/6932 [14:22<10:31,  4.65it/s]

Processing tickers:  58%|█████▊    | 4001/6932 [14:23<10:28,  4.66it/s]

Processing tickers:  58%|█████▊    | 4002/6932 [14:23<10:18,  4.74it/s]

Processing tickers:  58%|█████▊    | 4003/6932 [14:23<10:16,  4.75it/s]

Processing tickers:  58%|█████▊    | 4004/6932 [14:23<10:25,  4.68it/s]

Processing tickers:  58%|█████▊    | 4005/6932 [14:23<10:23,  4.69it/s]

Processing tickers:  58%|█████▊    | 4006/6932 [14:24<10:06,  4.82it/s]

Processing tickers:  58%|█████▊    | 4007/6932 [14:24<10:18,  4.73it/s]

Processing tickers:  58%|█████▊    | 4008/6932 [14:24<10:15,  4.75it/s]

Processing tickers:  58%|█████▊    | 4009/6932 [14:24<10:13,  4.77it/s]

Processing tickers:  58%|█████▊    | 4010/6932 [14:24<10:11,  4.78it/s]

Processing tickers:  58%|█████▊    | 4011/6932 [14:25<10:11,  4.78it/s]

Processing tickers:  58%|█████▊    | 4012/6932 [14:25<10:08,  4.80it/s]

Processing tickers:  58%|█████▊    | 4013/6932 [14:25<10:20,  4.70it/s]

Processing tickers:  58%|█████▊    | 4014/6932 [14:25<10:16,  4.73it/s]

Processing tickers:  58%|█████▊    | 4015/6932 [14:26<10:28,  4.64it/s]

Processing tickers:  58%|█████▊    | 4016/6932 [14:26<10:35,  4.59it/s]

Processing tickers:  58%|█████▊    | 4017/6932 [14:26<10:24,  4.67it/s]

Processing tickers:  58%|█████▊    | 4018/6932 [14:26<10:18,  4.71it/s]

Processing tickers:  58%|█████▊    | 4019/6932 [14:26<10:14,  4.74it/s]

Processing tickers:  58%|█████▊    | 4020/6932 [14:27<10:32,  4.60it/s]

Processing tickers:  58%|█████▊    | 4021/6932 [14:27<10:22,  4.68it/s]

Processing tickers:  58%|█████▊    | 4022/6932 [14:27<10:11,  4.76it/s]

Processing tickers:  58%|█████▊    | 4023/6932 [14:27<10:09,  4.77it/s]

Processing tickers:  58%|█████▊    | 4024/6932 [14:27<10:08,  4.78it/s]

Processing tickers:  58%|█████▊    | 4025/6932 [14:28<10:08,  4.77it/s]

Processing tickers:  58%|█████▊    | 4026/6932 [14:28<10:19,  4.69it/s]

Processing tickers:  58%|█████▊    | 4027/6932 [14:28<10:04,  4.81it/s]

Processing tickers:  58%|█████▊    | 4028/6932 [14:28<10:13,  4.73it/s]

Processing tickers:  58%|█████▊    | 4029/6932 [14:28<10:10,  4.75it/s]

Processing tickers:  58%|█████▊    | 4030/6932 [14:29<10:09,  4.76it/s]

Processing tickers:  58%|█████▊    | 4031/6932 [14:29<10:07,  4.78it/s]

Processing tickers:  58%|█████▊    | 4032/6932 [14:29<10:11,  4.74it/s]

Processing tickers:  58%|█████▊    | 4033/6932 [14:29<10:03,  4.80it/s]

Processing tickers:  58%|█████▊    | 4034/6932 [14:30<10:17,  4.69it/s]

Processing tickers:  58%|█████▊    | 4035/6932 [14:30<10:19,  4.67it/s]

Processing tickers:  58%|█████▊    | 4036/6932 [14:30<10:18,  4.68it/s]

Processing tickers:  58%|█████▊    | 4037/6932 [14:30<10:14,  4.71it/s]

Processing tickers:  58%|█████▊    | 4038/6932 [14:30<10:15,  4.70it/s]

Processing tickers:  58%|█████▊    | 4039/6932 [14:31<10:11,  4.73it/s]

Processing tickers:  58%|█████▊    | 4040/6932 [14:31<10:04,  4.79it/s]

Processing tickers:  58%|█████▊    | 4041/6932 [14:31<10:02,  4.80it/s]

Processing tickers:  58%|█████▊    | 4042/6932 [14:31<10:12,  4.72it/s]

Processing tickers:  58%|█████▊    | 4043/6932 [14:31<10:12,  4.72it/s]

Processing tickers:  58%|█████▊    | 4044/6932 [14:32<10:08,  4.74it/s]

Processing tickers:  58%|█████▊    | 4045/6932 [14:32<10:05,  4.76it/s]

Processing tickers:  58%|█████▊    | 4046/6932 [14:32<10:18,  4.67it/s]

Processing tickers:  58%|█████▊    | 4047/6932 [14:32<10:12,  4.71it/s]

Processing tickers:  58%|█████▊    | 4048/6932 [14:32<10:17,  4.67it/s]

Processing tickers:  58%|█████▊    | 4049/6932 [14:33<10:04,  4.77it/s]

Processing tickers:  58%|█████▊    | 4050/6932 [14:33<10:09,  4.73it/s]

Processing tickers:  58%|█████▊    | 4051/6932 [14:33<09:59,  4.81it/s]

Processing tickers:  58%|█████▊    | 4052/6932 [14:33<09:59,  4.81it/s]

Processing tickers:  58%|█████▊    | 4053/6932 [14:34<10:12,  4.70it/s]

Processing tickers:  58%|█████▊    | 4054/6932 [14:34<10:22,  4.63it/s]

Processing tickers:  58%|█████▊    | 4055/6932 [14:34<10:18,  4.65it/s]

Processing tickers:  59%|█████▊    | 4056/6932 [14:34<10:08,  4.73it/s]

Processing tickers:  59%|█████▊    | 4057/6932 [14:34<10:18,  4.65it/s]

Processing tickers:  59%|█████▊    | 4058/6932 [14:35<10:10,  4.71it/s]

Processing tickers:  59%|█████▊    | 4059/6932 [14:35<10:06,  4.73it/s]

Processing tickers:  59%|█████▊    | 4060/6932 [14:35<10:01,  4.78it/s]

Processing tickers:  59%|█████▊    | 4061/6932 [14:35<10:14,  4.67it/s]

Processing tickers:  59%|█████▊    | 4062/6932 [14:35<10:08,  4.71it/s]

Processing tickers:  59%|█████▊    | 4063/6932 [14:36<10:05,  4.74it/s]

Processing tickers:  59%|█████▊    | 4064/6932 [14:36<10:12,  4.68it/s]

Processing tickers:  59%|█████▊    | 4065/6932 [14:36<09:57,  4.79it/s]

Processing tickers:  59%|█████▊    | 4066/6932 [14:36<10:10,  4.69it/s]

Processing tickers:  59%|█████▊    | 4067/6932 [14:37<10:06,  4.73it/s]

Processing tickers:  59%|█████▊    | 4068/6932 [14:37<10:16,  4.65it/s]

Processing tickers:  59%|█████▊    | 4069/6932 [14:37<10:12,  4.67it/s]

Processing tickers:  59%|█████▊    | 4070/6932 [14:37<10:03,  4.74it/s]

Processing tickers:  59%|█████▊    | 4071/6932 [14:37<10:14,  4.65it/s]

Processing tickers:  59%|█████▊    | 4072/6932 [14:38<10:08,  4.70it/s]

Processing tickers:  59%|█████▉    | 4073/6932 [14:38<10:03,  4.74it/s]

Processing tickers:  59%|█████▉    | 4074/6932 [14:38<10:00,  4.76it/s]

Processing tickers:  59%|█████▉    | 4075/6932 [14:38<09:58,  4.77it/s]

Processing tickers:  59%|█████▉    | 4076/6932 [14:38<10:11,  4.67it/s]

Processing tickers:  59%|█████▉    | 4077/6932 [14:39<09:52,  4.82it/s]

Processing tickers:  59%|█████▉    | 4078/6932 [14:39<09:51,  4.82it/s]

Processing tickers:  59%|█████▉    | 4079/6932 [14:39<10:06,  4.71it/s]

Processing tickers:  59%|█████▉    | 4080/6932 [14:39<10:01,  4.74it/s]

Processing tickers:  59%|█████▉    | 4081/6932 [14:39<10:07,  4.70it/s]

Processing tickers:  59%|█████▉    | 4082/6932 [14:40<10:01,  4.74it/s]

Processing tickers:  59%|█████▉    | 4083/6932 [14:40<09:51,  4.81it/s]

Processing tickers:  59%|█████▉    | 4084/6932 [14:40<10:00,  4.74it/s]

Processing tickers:  59%|█████▉    | 4085/6932 [14:40<09:50,  4.82it/s]

Processing tickers:  59%|█████▉    | 4086/6932 [14:41<09:50,  4.82it/s]

Processing tickers:  59%|█████▉    | 4087/6932 [14:41<10:04,  4.71it/s]

Processing tickers:  59%|█████▉    | 4088/6932 [14:41<09:46,  4.85it/s]

Processing tickers:  59%|█████▉    | 4089/6932 [14:41<09:47,  4.84it/s]

Processing tickers:  59%|█████▉    | 4090/6932 [14:41<09:56,  4.76it/s]

Processing tickers:  59%|█████▉    | 4091/6932 [14:42<09:46,  4.85it/s]

Processing tickers:  59%|█████▉    | 4092/6932 [14:42<09:47,  4.84it/s]

Processing tickers:  59%|█████▉    | 4093/6932 [14:42<10:01,  4.72it/s]

Processing tickers:  59%|█████▉    | 4094/6932 [14:42<09:58,  4.74it/s]

Processing tickers:  59%|█████▉    | 4095/6932 [14:42<09:55,  4.76it/s]

Processing tickers:  59%|█████▉    | 4096/6932 [14:43<09:53,  4.77it/s]

Processing tickers:  59%|█████▉    | 4097/6932 [14:43<09:52,  4.78it/s]

Processing tickers:  59%|█████▉    | 4098/6932 [14:43<09:51,  4.79it/s]

Processing tickers:  59%|█████▉    | 4099/6932 [14:43<10:01,  4.71it/s]

Processing tickers:  59%|█████▉    | 4100/6932 [14:43<10:12,  4.62it/s]

Processing tickers:  59%|█████▉    | 4101/6932 [14:44<10:04,  4.68it/s]

Processing tickers:  59%|█████▉    | 4102/6932 [14:44<10:13,  4.61it/s]

Processing tickers:  59%|█████▉    | 4103/6932 [14:44<10:21,  4.55it/s]

Processing tickers:  59%|█████▉    | 4104/6932 [14:44<10:09,  4.64it/s]

Processing tickers:  59%|█████▉    | 4105/6932 [14:45<10:03,  4.68it/s]

Processing tickers:  59%|█████▉    | 4106/6932 [14:45<09:59,  4.71it/s]

Processing tickers:  59%|█████▉    | 4107/6932 [14:45<09:55,  4.75it/s]

Processing tickers:  59%|█████▉    | 4108/6932 [14:45<10:05,  4.66it/s]

Processing tickers:  59%|█████▉    | 4109/6932 [14:45<10:18,  4.57it/s]

Processing tickers:  59%|█████▉    | 4110/6932 [14:46<10:06,  4.66it/s]

Processing tickers:  59%|█████▉    | 4111/6932 [14:46<09:59,  4.71it/s]

Processing tickers:  59%|█████▉    | 4112/6932 [14:46<09:52,  4.76it/s]

Processing tickers:  59%|█████▉    | 4113/6932 [14:46<09:49,  4.78it/s]

Processing tickers:  59%|█████▉    | 4114/6932 [14:46<09:34,  4.90it/s]

Processing tickers:  59%|█████▉    | 4115/6932 [14:47<09:37,  4.88it/s]

Processing tickers:  59%|█████▉    | 4116/6932 [14:47<09:50,  4.77it/s]

Processing tickers:  59%|█████▉    | 4117/6932 [14:47<09:50,  4.77it/s]

Processing tickers:  59%|█████▉    | 4118/6932 [14:47<09:50,  4.77it/s]

Processing tickers:  59%|█████▉    | 4119/6932 [14:47<09:50,  4.76it/s]

Processing tickers:  59%|█████▉    | 4120/6932 [14:48<09:51,  4.76it/s]

Processing tickers:  59%|█████▉    | 4121/6932 [14:48<09:46,  4.79it/s]

Processing tickers:  59%|█████▉    | 4122/6932 [14:48<09:45,  4.80it/s]

Processing tickers:  59%|█████▉    | 4123/6932 [14:48<09:48,  4.77it/s]

Processing tickers:  59%|█████▉    | 4124/6932 [14:49<09:57,  4.70it/s]

Processing tickers:  60%|█████▉    | 4125/6932 [14:49<09:50,  4.75it/s]

Processing tickers:  60%|█████▉    | 4126/6932 [14:49<09:48,  4.77it/s]

Processing tickers:  60%|█████▉    | 4127/6932 [14:49<10:01,  4.67it/s]

Processing tickers:  60%|█████▉    | 4128/6932 [14:49<10:00,  4.67it/s]

Processing tickers:  60%|█████▉    | 4129/6932 [14:50<09:49,  4.76it/s]

Processing tickers:  60%|█████▉    | 4130/6932 [14:50<10:00,  4.67it/s]

Processing tickers:  60%|█████▉    | 4131/6932 [14:50<09:54,  4.71it/s]

Processing tickers:  60%|█████▉    | 4132/6932 [14:50<09:50,  4.74it/s]

Processing tickers:  60%|█████▉    | 4133/6932 [14:50<09:57,  4.69it/s]

Processing tickers:  60%|█████▉    | 4134/6932 [14:51<09:43,  4.79it/s]

Processing tickers:  60%|█████▉    | 4135/6932 [14:51<09:57,  4.68it/s]

Processing tickers:  60%|█████▉    | 4136/6932 [14:51<09:52,  4.72it/s]

Processing tickers:  60%|█████▉    | 4137/6932 [14:51<09:49,  4.74it/s]

Processing tickers:  60%|█████▉    | 4138/6932 [14:51<09:49,  4.74it/s]

Processing tickers:  60%|█████▉    | 4139/6932 [14:52<10:00,  4.65it/s]

Processing tickers:  60%|█████▉    | 4140/6932 [14:52<09:51,  4.72it/s]

Processing tickers:  60%|█████▉    | 4141/6932 [14:52<09:48,  4.75it/s]

Processing tickers:  60%|█████▉    | 4142/6932 [14:52<09:45,  4.76it/s]

Processing tickers:  60%|█████▉    | 4143/6932 [14:53<09:57,  4.67it/s]

Processing tickers:  60%|█████▉    | 4144/6932 [14:53<09:55,  4.69it/s]

Processing tickers:  60%|█████▉    | 4145/6932 [14:53<09:46,  4.75it/s]

Processing tickers:  60%|█████▉    | 4146/6932 [14:53<09:43,  4.77it/s]

Processing tickers:  60%|█████▉    | 4147/6932 [14:53<09:41,  4.79it/s]

Processing tickers:  60%|█████▉    | 4148/6932 [14:54<09:45,  4.76it/s]

Processing tickers:  60%|█████▉    | 4149/6932 [14:54<09:51,  4.71it/s]

Processing tickers:  60%|█████▉    | 4150/6932 [14:54<09:47,  4.73it/s]

Processing tickers:  60%|█████▉    | 4151/6932 [14:54<09:45,  4.75it/s]

Processing tickers:  60%|█████▉    | 4152/6932 [14:54<09:43,  4.77it/s]

Processing tickers:  60%|█████▉    | 4153/6932 [14:55<10:14,  4.52it/s]

Processing tickers:  60%|█████▉    | 4154/6932 [14:55<10:10,  4.55it/s]

Processing tickers:  60%|█████▉    | 4155/6932 [14:55<09:59,  4.63it/s]

Processing tickers:  60%|█████▉    | 4156/6932 [14:55<09:52,  4.68it/s]

Processing tickers:  60%|█████▉    | 4157/6932 [14:56<09:46,  4.73it/s]

Processing tickers:  60%|█████▉    | 4158/6932 [14:56<09:55,  4.66it/s]

Processing tickers:  60%|█████▉    | 4159/6932 [14:56<09:49,  4.70it/s]

Processing tickers:  60%|██████    | 4160/6932 [14:56<09:59,  4.63it/s]

Processing tickers:  60%|██████    | 4161/6932 [14:56<09:54,  4.66it/s]

Processing tickers:  60%|██████    | 4162/6932 [14:57<09:45,  4.73it/s]

Processing tickers:  60%|██████    | 4163/6932 [14:57<09:41,  4.76it/s]

Processing tickers:  60%|██████    | 4164/6932 [14:57<09:39,  4.78it/s]

Processing tickers:  60%|██████    | 4165/6932 [14:57<09:47,  4.71it/s]

Processing tickers:  60%|██████    | 4166/6932 [14:57<09:34,  4.81it/s]

Processing tickers:  60%|██████    | 4167/6932 [14:58<09:34,  4.81it/s]

Processing tickers:  60%|██████    | 4168/6932 [14:58<09:48,  4.70it/s]

Processing tickers:  60%|██████    | 4169/6932 [14:58<09:46,  4.71it/s]

Processing tickers:  60%|██████    | 4170/6932 [14:58<09:40,  4.76it/s]

Processing tickers:  60%|██████    | 4171/6932 [14:58<09:38,  4.77it/s]

Processing tickers:  60%|██████    | 4172/6932 [14:59<09:57,  4.62it/s]

Processing tickers:  60%|██████    | 4173/6932 [14:59<09:46,  4.71it/s]

Processing tickers:  60%|██████    | 4174/6932 [14:59<09:58,  4.61it/s]

Processing tickers:  60%|██████    | 4175/6932 [14:59<09:48,  4.68it/s]

Processing tickers:  60%|██████    | 4176/6932 [15:00<09:39,  4.75it/s]

Processing tickers:  60%|██████    | 4177/6932 [15:00<09:55,  4.63it/s]

Processing tickers:  60%|██████    | 4178/6932 [15:00<09:43,  4.72it/s]

Processing tickers:  60%|██████    | 4179/6932 [15:00<09:53,  4.64it/s]

Processing tickers:  60%|██████    | 4180/6932 [15:00<09:46,  4.69it/s]

Processing tickers:  60%|██████    | 4181/6932 [15:01<09:52,  4.64it/s]

Processing tickers:  60%|██████    | 4182/6932 [15:01<09:52,  4.64it/s]

Processing tickers:  60%|██████    | 4183/6932 [15:01<09:42,  4.72it/s]

Processing tickers:  60%|██████    | 4184/6932 [15:01<09:47,  4.68it/s]

Processing tickers:  60%|██████    | 4185/6932 [15:01<09:34,  4.78it/s]

Processing tickers:  60%|██████    | 4186/6932 [15:02<09:33,  4.79it/s]

Processing tickers:  60%|██████    | 4187/6932 [15:02<09:45,  4.69it/s]

Processing tickers:  60%|██████    | 4188/6932 [15:02<09:42,  4.71it/s]

Processing tickers:  60%|██████    | 4189/6932 [15:02<09:37,  4.75it/s]

Processing tickers:  60%|██████    | 4190/6932 [15:03<09:33,  4.78it/s]

Processing tickers:  60%|██████    | 4191/6932 [15:03<09:32,  4.78it/s]

Processing tickers:  60%|██████    | 4192/6932 [15:03<09:31,  4.79it/s]

Processing tickers:  60%|██████    | 4193/6932 [15:03<09:44,  4.69it/s]

Processing tickers:  61%|██████    | 4194/6932 [15:03<09:39,  4.72it/s]

Processing tickers:  61%|██████    | 4195/6932 [15:04<09:36,  4.75it/s]

Processing tickers:  61%|██████    | 4196/6932 [15:04<09:41,  4.70it/s]

Processing tickers:  61%|██████    | 4197/6932 [15:04<09:42,  4.70it/s]

Processing tickers:  61%|██████    | 4198/6932 [15:04<09:38,  4.72it/s]

Processing tickers:  61%|██████    | 4199/6932 [15:04<09:35,  4.75it/s]

Processing tickers:  61%|██████    | 4200/6932 [15:05<09:44,  4.68it/s]

Processing tickers:  61%|██████    | 4201/6932 [15:05<09:49,  4.63it/s]

Processing tickers:  61%|██████    | 4202/6932 [15:05<09:54,  4.59it/s]

Processing tickers:  61%|██████    | 4203/6932 [15:05<09:47,  4.65it/s]

Processing tickers:  61%|██████    | 4204/6932 [15:06<09:53,  4.60it/s]

Processing tickers:  61%|██████    | 4205/6932 [15:06<09:45,  4.66it/s]

Processing tickers:  61%|██████    | 4206/6932 [15:06<09:52,  4.60it/s]

Processing tickers:  61%|██████    | 4207/6932 [15:06<09:44,  4.66it/s]

Processing tickers:  61%|██████    | 4208/6932 [15:06<09:39,  4.70it/s]

Processing tickers:  61%|██████    | 4209/6932 [15:07<09:34,  4.74it/s]

Processing tickers:  61%|██████    | 4210/6932 [15:07<09:31,  4.76it/s]

Processing tickers:  61%|██████    | 4211/6932 [15:07<09:40,  4.69it/s]

Processing tickers:  61%|██████    | 4212/6932 [15:07<09:35,  4.73it/s]

Processing tickers:  61%|██████    | 4213/6932 [15:07<09:32,  4.75it/s]

Processing tickers:  61%|██████    | 4214/6932 [15:08<09:30,  4.77it/s]

Processing tickers:  61%|██████    | 4215/6932 [15:08<09:40,  4.68it/s]

Processing tickers:  61%|██████    | 4216/6932 [15:08<09:36,  4.71it/s]

Processing tickers:  61%|██████    | 4217/6932 [15:08<09:46,  4.63it/s]

Processing tickers:  61%|██████    | 4218/6932 [15:08<09:26,  4.79it/s]

Processing tickers:  61%|██████    | 4219/6932 [15:09<09:39,  4.69it/s]

Processing tickers:  61%|██████    | 4220/6932 [15:09<09:34,  4.72it/s]

Processing tickers:  61%|██████    | 4221/6932 [15:09<09:44,  4.64it/s]

Processing tickers:  61%|██████    | 4222/6932 [15:09<09:37,  4.69it/s]

Processing tickers:  61%|██████    | 4223/6932 [15:10<09:46,  4.62it/s]

Processing tickers:  61%|██████    | 4224/6932 [15:10<09:26,  4.78it/s]

Processing tickers:  61%|██████    | 4225/6932 [15:10<09:25,  4.78it/s]

Processing tickers:  61%|██████    | 4226/6932 [15:10<09:50,  4.58it/s]

Processing tickers:  61%|██████    | 4227/6932 [15:10<09:44,  4.63it/s]

Processing tickers:  61%|██████    | 4228/6932 [15:11<09:44,  4.63it/s]

Processing tickers:  61%|██████    | 4229/6932 [15:11<09:41,  4.65it/s]

Processing tickers:  61%|██████    | 4230/6932 [15:11<09:35,  4.69it/s]

Processing tickers:  61%|██████    | 4231/6932 [15:11<09:40,  4.65it/s]

Processing tickers:  61%|██████    | 4232/6932 [15:11<09:25,  4.78it/s]

Processing tickers:  61%|██████    | 4233/6932 [15:12<09:23,  4.79it/s]

Processing tickers:  61%|██████    | 4234/6932 [15:12<09:30,  4.73it/s]

Processing tickers:  61%|██████    | 4235/6932 [15:12<09:19,  4.82it/s]

Processing tickers:  61%|██████    | 4236/6932 [15:12<09:32,  4.71it/s]

Processing tickers:  61%|██████    | 4237/6932 [15:13<09:39,  4.65it/s]

Processing tickers:  61%|██████    | 4238/6932 [15:13<09:36,  4.67it/s]

Processing tickers:  61%|██████    | 4239/6932 [15:13<09:45,  4.60it/s]

Processing tickers:  61%|██████    | 4240/6932 [15:13<09:35,  4.67it/s]

Processing tickers:  61%|██████    | 4241/6932 [15:13<09:30,  4.72it/s]

Processing tickers:  61%|██████    | 4242/6932 [15:14<09:27,  4.74it/s]

Processing tickers:  61%|██████    | 4243/6932 [15:14<09:37,  4.65it/s]

Processing tickers:  61%|██████    | 4244/6932 [15:14<09:43,  4.60it/s]

Processing tickers:  61%|██████    | 4245/6932 [15:14<09:35,  4.67it/s]

Processing tickers:  61%|██████▏   | 4246/6932 [15:14<09:30,  4.70it/s]

Processing tickers:  61%|██████▏   | 4247/6932 [15:15<09:31,  4.70it/s]

Processing tickers:  61%|██████▏   | 4248/6932 [15:15<09:23,  4.77it/s]

Processing tickers:  61%|██████▏   | 4249/6932 [15:15<09:21,  4.78it/s]

Processing tickers:  61%|██████▏   | 4250/6932 [15:15<09:22,  4.77it/s]

Processing tickers:  61%|██████▏   | 4251/6932 [15:16<09:18,  4.80it/s]

Processing tickers:  61%|██████▏   | 4252/6932 [15:16<09:18,  4.80it/s]

Processing tickers:  61%|██████▏   | 4253/6932 [15:16<09:32,  4.68it/s]

Processing tickers:  61%|██████▏   | 4254/6932 [15:16<09:25,  4.73it/s]

Processing tickers:  61%|██████▏   | 4255/6932 [15:16<09:26,  4.73it/s]

Processing tickers:  61%|██████▏   | 4256/6932 [15:17<09:20,  4.78it/s]

Processing tickers:  61%|██████▏   | 4257/6932 [15:17<09:19,  4.78it/s]

Processing tickers:  61%|██████▏   | 4258/6932 [15:17<09:18,  4.79it/s]

Processing tickers:  61%|██████▏   | 4259/6932 [15:17<09:17,  4.79it/s]

Processing tickers:  61%|██████▏   | 4260/6932 [15:17<09:17,  4.80it/s]

Processing tickers:  61%|██████▏   | 4261/6932 [15:18<09:28,  4.70it/s]

Processing tickers:  61%|██████▏   | 4262/6932 [15:18<09:25,  4.72it/s]

Processing tickers:  61%|██████▏   | 4263/6932 [15:18<09:38,  4.62it/s]

Processing tickers:  62%|██████▏   | 4264/6932 [15:18<09:31,  4.67it/s]

Processing tickers:  62%|██████▏   | 4265/6932 [15:18<09:22,  4.74it/s]

Processing tickers:  62%|██████▏   | 4266/6932 [15:19<09:19,  4.76it/s]

Processing tickers:  62%|██████▏   | 4267/6932 [15:19<09:18,  4.77it/s]

Processing tickers:  62%|██████▏   | 4268/6932 [15:19<09:27,  4.70it/s]

Processing tickers:  62%|██████▏   | 4269/6932 [15:19<09:13,  4.81it/s]

Processing tickers:  62%|██████▏   | 4270/6932 [15:20<09:19,  4.76it/s]

Processing tickers:  62%|██████▏   | 4271/6932 [15:20<09:11,  4.83it/s]

Processing tickers:  62%|██████▏   | 4272/6932 [15:20<09:25,  4.70it/s]

Processing tickers:  62%|██████▏   | 4273/6932 [15:20<09:24,  4.71it/s]

Processing tickers:  62%|██████▏   | 4274/6932 [15:20<09:16,  4.78it/s]

Processing tickers:  62%|██████▏   | 4275/6932 [15:21<09:15,  4.79it/s]

Processing tickers:  62%|██████▏   | 4276/6932 [15:21<09:14,  4.79it/s]

Processing tickers:  62%|██████▏   | 4277/6932 [15:21<09:27,  4.68it/s]

Processing tickers:  62%|██████▏   | 4278/6932 [15:21<09:21,  4.73it/s]

Processing tickers:  62%|██████▏   | 4279/6932 [15:21<09:31,  4.64it/s]

Processing tickers:  62%|██████▏   | 4280/6932 [15:22<09:12,  4.80it/s]

Processing tickers:  62%|██████▏   | 4281/6932 [15:22<09:15,  4.78it/s]

Processing tickers:  62%|██████▏   | 4282/6932 [15:22<09:09,  4.82it/s]

Processing tickers:  62%|██████▏   | 4283/6932 [15:22<09:22,  4.71it/s]

Processing tickers:  62%|██████▏   | 4284/6932 [15:22<09:18,  4.74it/s]

Processing tickers:  62%|██████▏   | 4285/6932 [15:23<09:18,  4.74it/s]

Processing tickers:  62%|██████▏   | 4286/6932 [15:23<09:27,  4.67it/s]

Processing tickers:  62%|██████▏   | 4287/6932 [15:23<09:21,  4.71it/s]

Processing tickers:  62%|██████▏   | 4288/6932 [15:23<09:17,  4.74it/s]

Processing tickers:  62%|██████▏   | 4289/6932 [15:24<09:15,  4.76it/s]

Processing tickers:  62%|██████▏   | 4290/6932 [15:24<09:22,  4.70it/s]

Processing tickers:  62%|██████▏   | 4291/6932 [15:24<09:24,  4.68it/s]

Processing tickers:  62%|██████▏   | 4292/6932 [15:24<09:30,  4.62it/s]

Processing tickers:  62%|██████▏   | 4293/6932 [15:24<09:23,  4.68it/s]

Processing tickers:  62%|██████▏   | 4294/6932 [15:25<09:18,  4.72it/s]

Processing tickers:  62%|██████▏   | 4295/6932 [15:25<09:15,  4.75it/s]

Processing tickers:  62%|██████▏   | 4296/6932 [15:25<09:13,  4.76it/s]

Processing tickers:  62%|██████▏   | 4297/6932 [15:25<09:10,  4.78it/s]

Processing tickers:  62%|██████▏   | 4298/6932 [15:25<09:21,  4.70it/s]

Processing tickers:  62%|██████▏   | 4299/6932 [15:26<09:19,  4.70it/s]

Processing tickers:  62%|██████▏   | 4300/6932 [15:26<09:13,  4.75it/s]

Processing tickers:  62%|██████▏   | 4301/6932 [15:26<09:11,  4.77it/s]

Processing tickers:  62%|██████▏   | 4302/6932 [15:26<09:10,  4.78it/s]

Processing tickers:  62%|██████▏   | 4303/6932 [15:27<09:19,  4.70it/s]

Processing tickers:  62%|██████▏   | 4304/6932 [15:27<09:15,  4.73it/s]

Processing tickers:  62%|██████▏   | 4305/6932 [15:27<09:12,  4.75it/s]

Processing tickers:  62%|██████▏   | 4306/6932 [15:27<09:10,  4.77it/s]

Processing tickers:  62%|██████▏   | 4307/6932 [15:27<09:08,  4.78it/s]

Processing tickers:  62%|██████▏   | 4308/6932 [15:28<09:28,  4.62it/s]

Processing tickers:  62%|██████▏   | 4309/6932 [15:28<09:14,  4.73it/s]

Processing tickers:  62%|██████▏   | 4310/6932 [15:28<09:12,  4.75it/s]

Processing tickers:  62%|██████▏   | 4311/6932 [15:28<09:22,  4.66it/s]

Processing tickers:  62%|██████▏   | 4312/6932 [15:28<09:17,  4.70it/s]

Processing tickers:  62%|██████▏   | 4313/6932 [15:29<09:25,  4.63it/s]

Processing tickers:  62%|██████▏   | 4314/6932 [15:29<09:18,  4.69it/s]

Processing tickers:  62%|██████▏   | 4315/6932 [15:29<09:13,  4.73it/s]

Processing tickers:  62%|██████▏   | 4316/6932 [15:29<09:10,  4.75it/s]

Processing tickers:  62%|██████▏   | 4317/6932 [15:29<09:08,  4.77it/s]

Processing tickers:  62%|██████▏   | 4318/6932 [15:30<09:08,  4.76it/s]

Processing tickers:  62%|██████▏   | 4319/6932 [15:30<09:05,  4.79it/s]

Processing tickers:  62%|██████▏   | 4320/6932 [15:30<09:09,  4.75it/s]

Processing tickers:  62%|██████▏   | 4321/6932 [15:30<09:02,  4.81it/s]

Processing tickers:  62%|██████▏   | 4322/6932 [15:31<09:02,  4.81it/s]

Processing tickers:  62%|██████▏   | 4323/6932 [15:31<09:23,  4.63it/s]

Processing tickers:  62%|██████▏   | 4324/6932 [15:31<09:11,  4.73it/s]

Processing tickers:  62%|██████▏   | 4325/6932 [15:31<09:06,  4.77it/s]

Processing tickers:  62%|██████▏   | 4326/6932 [15:31<09:18,  4.66it/s]

Processing tickers:  62%|██████▏   | 4327/6932 [15:32<08:59,  4.83it/s]

Processing tickers:  62%|██████▏   | 4328/6932 [15:32<09:12,  4.71it/s]

Processing tickers:  62%|██████▏   | 4329/6932 [15:32<09:08,  4.75it/s]

Processing tickers:  62%|██████▏   | 4330/6932 [15:32<09:13,  4.70it/s]

Processing tickers:  62%|██████▏   | 4331/6932 [15:32<09:01,  4.80it/s]

Processing tickers:  62%|██████▏   | 4332/6932 [15:33<09:01,  4.80it/s]

Processing tickers:  63%|██████▎   | 4333/6932 [15:33<09:13,  4.69it/s]

Processing tickers:  63%|██████▎   | 4334/6932 [15:33<09:09,  4.73it/s]

Processing tickers:  63%|██████▎   | 4335/6932 [15:33<09:05,  4.76it/s]

Processing tickers:  63%|██████▎   | 4336/6932 [15:33<09:04,  4.77it/s]

Processing tickers:  63%|██████▎   | 4337/6932 [15:34<09:04,  4.76it/s]

Processing tickers:  63%|██████▎   | 4338/6932 [15:34<09:02,  4.79it/s]

Processing tickers:  63%|██████▎   | 4339/6932 [15:34<09:00,  4.80it/s]

Processing tickers:  63%|██████▎   | 4340/6932 [15:34<09:00,  4.80it/s]

Processing tickers:  63%|██████▎   | 4341/6932 [15:35<08:59,  4.80it/s]

Processing tickers:  63%|██████▎   | 4342/6932 [15:35<09:19,  4.63it/s]

Processing tickers:  63%|██████▎   | 4343/6932 [15:35<09:16,  4.65it/s]

Processing tickers:  63%|██████▎   | 4344/6932 [15:35<09:09,  4.71it/s]

Processing tickers:  63%|██████▎   | 4345/6932 [15:35<09:17,  4.64it/s]

Processing tickers:  63%|██████▎   | 4346/6932 [15:36<09:24,  4.59it/s]

Processing tickers:  63%|██████▎   | 4347/6932 [15:36<09:16,  4.65it/s]

Processing tickers:  63%|██████▎   | 4348/6932 [15:36<09:10,  4.70it/s]

Processing tickers:  63%|██████▎   | 4349/6932 [15:36<09:05,  4.73it/s]

Processing tickers:  63%|██████▎   | 4350/6932 [15:36<09:03,  4.75it/s]

Processing tickers:  63%|██████▎   | 4351/6932 [15:37<09:14,  4.66it/s]

Processing tickers:  63%|██████▎   | 4352/6932 [15:37<09:12,  4.67it/s]

Processing tickers:  63%|██████▎   | 4353/6932 [15:37<09:08,  4.70it/s]

Processing tickers:  63%|██████▎   | 4354/6932 [15:37<08:59,  4.78it/s]

Processing tickers:  63%|██████▎   | 4355/6932 [15:38<09:11,  4.68it/s]

Processing tickers:  63%|██████▎   | 4356/6932 [15:38<09:29,  4.53it/s]

Processing tickers:  63%|██████▎   | 4357/6932 [15:38<09:32,  4.50it/s]

Processing tickers:  63%|██████▎   | 4358/6932 [15:38<09:19,  4.60it/s]

Processing tickers:  63%|██████▎   | 4359/6932 [15:38<09:12,  4.66it/s]

Processing tickers:  63%|██████▎   | 4360/6932 [15:39<09:07,  4.70it/s]

Processing tickers:  63%|██████▎   | 4361/6932 [15:39<09:14,  4.64it/s]

Processing tickers:  63%|██████▎   | 4362/6932 [15:39<08:57,  4.78it/s]

Processing tickers:  63%|██████▎   | 4363/6932 [15:39<08:56,  4.78it/s]

Processing tickers:  63%|██████▎   | 4364/6932 [15:39<08:56,  4.79it/s]

Processing tickers:  63%|██████▎   | 4365/6932 [15:40<08:55,  4.80it/s]

Processing tickers:  63%|██████▎   | 4366/6932 [15:40<09:02,  4.73it/s]

Processing tickers:  63%|██████▎   | 4367/6932 [15:40<08:55,  4.79it/s]

Processing tickers:  63%|██████▎   | 4368/6932 [15:40<09:07,  4.68it/s]

Processing tickers:  63%|██████▎   | 4369/6932 [15:40<09:02,  4.73it/s]

Processing tickers:  63%|██████▎   | 4370/6932 [15:41<08:56,  4.78it/s]

Processing tickers:  63%|██████▎   | 4371/6932 [15:41<09:00,  4.73it/s]

Processing tickers:  63%|██████▎   | 4372/6932 [15:41<08:52,  4.81it/s]

Processing tickers:  63%|██████▎   | 4373/6932 [15:41<08:51,  4.81it/s]

Processing tickers:  63%|██████▎   | 4374/6932 [15:42<08:51,  4.81it/s]

Processing tickers:  63%|██████▎   | 4375/6932 [15:42<08:51,  4.81it/s]

Processing tickers:  63%|██████▎   | 4376/6932 [15:42<09:03,  4.70it/s]

Processing tickers:  63%|██████▎   | 4377/6932 [15:42<08:59,  4.73it/s]

Processing tickers:  63%|██████▎   | 4378/6932 [15:42<10:10,  4.18it/s]

Processing tickers:  63%|██████▎   | 4379/6932 [15:43<09:47,  4.34it/s]

Processing tickers:  63%|██████▎   | 4380/6932 [15:43<09:28,  4.49it/s]

Processing tickers:  63%|██████▎   | 4381/6932 [15:43<09:19,  4.56it/s]

Processing tickers:  63%|██████▎   | 4382/6932 [15:43<09:09,  4.64it/s]

Processing tickers:  63%|██████▎   | 4383/6932 [15:44<09:05,  4.67it/s]

Processing tickers:  63%|██████▎   | 4384/6932 [15:44<08:57,  4.74it/s]

Processing tickers:  63%|██████▎   | 4385/6932 [15:44<08:53,  4.77it/s]

Processing tickers:  63%|██████▎   | 4386/6932 [15:44<09:11,  4.62it/s]

Processing tickers:  63%|██████▎   | 4387/6932 [15:44<08:58,  4.73it/s]

Processing tickers:  63%|██████▎   | 4388/6932 [15:45<09:09,  4.63it/s]

Processing tickers:  63%|██████▎   | 4389/6932 [15:45<09:00,  4.70it/s]

Processing tickers:  63%|██████▎   | 4390/6932 [15:45<09:00,  4.71it/s]

Processing tickers:  63%|██████▎   | 4391/6932 [15:45<08:53,  4.76it/s]

Processing tickers:  63%|██████▎   | 4392/6932 [15:45<08:52,  4.77it/s]

Processing tickers:  63%|██████▎   | 4393/6932 [15:46<08:51,  4.78it/s]

Processing tickers:  63%|██████▎   | 4394/6932 [15:46<09:02,  4.67it/s]

Processing tickers:  63%|██████▎   | 4395/6932 [15:46<08:58,  4.71it/s]

Processing tickers:  63%|██████▎   | 4396/6932 [15:46<09:01,  4.68it/s]

Processing tickers:  63%|██████▎   | 4397/6932 [15:46<08:51,  4.77it/s]

Processing tickers:  63%|██████▎   | 4398/6932 [15:47<08:59,  4.70it/s]

Processing tickers:  63%|██████▎   | 4399/6932 [15:47<08:57,  4.71it/s]

Processing tickers:  63%|██████▎   | 4400/6932 [15:47<08:57,  4.71it/s]

Processing tickers:  63%|██████▎   | 4401/6932 [15:47<09:14,  4.56it/s]

Processing tickers:  64%|██████▎   | 4402/6932 [15:48<09:17,  4.53it/s]

Processing tickers:  64%|██████▎   | 4403/6932 [15:48<09:08,  4.61it/s]

Processing tickers:  64%|██████▎   | 4404/6932 [15:48<09:01,  4.67it/s]

Processing tickers:  64%|██████▎   | 4405/6932 [15:48<09:00,  4.67it/s]

Processing tickers:  64%|██████▎   | 4406/6932 [15:48<08:57,  4.70it/s]

Processing tickers:  64%|██████▎   | 4407/6932 [15:49<08:48,  4.77it/s]

Processing tickers:  64%|██████▎   | 4408/6932 [15:49<09:00,  4.67it/s]

Processing tickers:  64%|██████▎   | 4409/6932 [15:49<08:55,  4.72it/s]

Processing tickers:  64%|██████▎   | 4410/6932 [15:49<08:51,  4.74it/s]

Processing tickers:  64%|██████▎   | 4411/6932 [15:49<08:56,  4.69it/s]

Processing tickers:  64%|██████▎   | 4412/6932 [15:50<08:58,  4.68it/s]

Processing tickers:  64%|██████▎   | 4413/6932 [15:50<08:52,  4.73it/s]

Processing tickers:  64%|██████▎   | 4414/6932 [15:50<08:49,  4.76it/s]

Processing tickers:  64%|██████▎   | 4415/6932 [15:50<08:47,  4.77it/s]

Processing tickers:  64%|██████▎   | 4416/6932 [15:51<08:59,  4.67it/s]

Processing tickers:  64%|██████▎   | 4417/6932 [15:51<08:54,  4.71it/s]

Processing tickers:  64%|██████▎   | 4418/6932 [15:51<08:50,  4.74it/s]

Processing tickers:  64%|██████▎   | 4419/6932 [15:51<08:55,  4.69it/s]

Processing tickers:  64%|██████▍   | 4420/6932 [15:51<08:44,  4.79it/s]

Processing tickers:  64%|██████▍   | 4421/6932 [15:52<08:55,  4.69it/s]

Processing tickers:  64%|██████▍   | 4422/6932 [15:52<08:51,  4.72it/s]

Processing tickers:  64%|██████▍   | 4423/6932 [15:52<08:49,  4.74it/s]

Processing tickers:  64%|██████▍   | 4424/6932 [15:52<08:47,  4.75it/s]

Processing tickers:  64%|██████▍   | 4425/6932 [15:52<08:44,  4.78it/s]

Processing tickers:  64%|██████▍   | 4426/6932 [15:53<08:46,  4.76it/s]

Processing tickers:  64%|██████▍   | 4427/6932 [15:53<08:42,  4.80it/s]

Processing tickers:  64%|██████▍   | 4428/6932 [15:53<08:42,  4.80it/s]

Processing tickers:  64%|██████▍   | 4429/6932 [15:53<08:41,  4.80it/s]

Processing tickers:  64%|██████▍   | 4430/6932 [15:53<08:55,  4.67it/s]

Processing tickers:  64%|██████▍   | 4431/6932 [15:54<09:12,  4.53it/s]

Processing tickers:  64%|██████▍   | 4432/6932 [15:54<09:04,  4.59it/s]

Processing tickers:  64%|██████▍   | 4433/6932 [15:54<08:55,  4.67it/s]

Processing tickers:  64%|██████▍   | 4434/6932 [15:54<08:52,  4.69it/s]

Processing tickers:  64%|██████▍   | 4435/6932 [15:55<08:56,  4.65it/s]

Processing tickers:  64%|██████▍   | 4436/6932 [15:55<08:47,  4.73it/s]

Processing tickers:  64%|██████▍   | 4437/6932 [15:55<08:49,  4.72it/s]

Processing tickers:  64%|██████▍   | 4438/6932 [15:55<08:56,  4.65it/s]

Processing tickers:  64%|██████▍   | 4439/6932 [15:55<08:50,  4.70it/s]

Processing tickers:  64%|██████▍   | 4440/6932 [15:56<08:46,  4.73it/s]

Processing tickers:  64%|██████▍   | 4441/6932 [15:56<08:43,  4.76it/s]

Processing tickers:  64%|██████▍   | 4442/6932 [15:56<08:53,  4.66it/s]

Processing tickers:  64%|██████▍   | 4443/6932 [15:56<08:47,  4.72it/s]

Processing tickers:  64%|██████▍   | 4444/6932 [15:56<08:56,  4.64it/s]

Processing tickers:  64%|██████▍   | 4445/6932 [15:57<08:48,  4.71it/s]

Processing tickers:  64%|██████▍   | 4446/6932 [15:57<08:44,  4.74it/s]

Processing tickers:  64%|██████▍   | 4447/6932 [15:57<08:30,  4.87it/s]

Processing tickers:  64%|██████▍   | 4448/6932 [15:57<08:31,  4.86it/s]

Processing tickers:  64%|██████▍   | 4449/6932 [15:58<08:44,  4.74it/s]

Processing tickers:  64%|██████▍   | 4450/6932 [15:58<08:43,  4.74it/s]

Processing tickers:  64%|██████▍   | 4451/6932 [15:58<08:39,  4.77it/s]

Processing tickers:  64%|██████▍   | 4452/6932 [15:58<08:38,  4.78it/s]

Processing tickers:  64%|██████▍   | 4453/6932 [15:58<08:43,  4.74it/s]

Processing tickers:  64%|██████▍   | 4454/6932 [15:59<08:35,  4.81it/s]

Processing tickers:  64%|██████▍   | 4455/6932 [15:59<08:35,  4.81it/s]

Processing tickers:  64%|██████▍   | 4456/6932 [15:59<08:44,  4.72it/s]

Processing tickers:  64%|██████▍   | 4457/6932 [15:59<08:32,  4.83it/s]

Processing tickers:  64%|██████▍   | 4458/6932 [15:59<08:32,  4.83it/s]

Processing tickers:  64%|██████▍   | 4459/6932 [16:00<08:31,  4.83it/s]

Processing tickers:  64%|██████▍   | 4460/6932 [16:00<08:44,  4.71it/s]

Processing tickers:  64%|██████▍   | 4461/6932 [16:00<08:43,  4.72it/s]

Processing tickers:  64%|██████▍   | 4462/6932 [16:00<08:38,  4.76it/s]

Processing tickers:  64%|██████▍   | 4463/6932 [16:00<08:37,  4.77it/s]

Processing tickers:  64%|██████▍   | 4464/6932 [16:01<08:38,  4.76it/s]

Processing tickers:  64%|██████▍   | 4465/6932 [16:01<08:34,  4.79it/s]

Processing tickers:  64%|██████▍   | 4466/6932 [16:01<08:34,  4.80it/s]

Processing tickers:  64%|██████▍   | 4467/6932 [16:01<08:35,  4.78it/s]

Processing tickers:  64%|██████▍   | 4468/6932 [16:01<08:33,  4.80it/s]

Processing tickers:  64%|██████▍   | 4469/6932 [16:02<08:35,  4.78it/s]

Processing tickers:  64%|██████▍   | 4470/6932 [16:02<08:33,  4.80it/s]

Processing tickers:  64%|██████▍   | 4471/6932 [16:02<08:31,  4.82it/s]

Processing tickers:  65%|██████▍   | 4472/6932 [16:02<08:30,  4.81it/s]

Processing tickers:  65%|██████▍   | 4473/6932 [16:03<08:31,  4.81it/s]

Processing tickers:  65%|██████▍   | 4474/6932 [16:03<08:42,  4.70it/s]

Processing tickers:  65%|██████▍   | 4475/6932 [16:03<08:27,  4.84it/s]

Processing tickers:  65%|██████▍   | 4476/6932 [16:03<08:41,  4.71it/s]

Processing tickers:  65%|██████▍   | 4477/6932 [16:03<08:36,  4.75it/s]

Processing tickers:  65%|██████▍   | 4478/6932 [16:04<08:24,  4.86it/s]

Processing tickers:  65%|██████▍   | 4479/6932 [16:04<08:37,  4.74it/s]

Processing tickers:  65%|██████▍   | 4480/6932 [16:04<08:38,  4.73it/s]

Processing tickers:  65%|██████▍   | 4481/6932 [16:04<08:32,  4.78it/s]

Processing tickers:  65%|██████▍   | 4482/6932 [16:04<08:43,  4.68it/s]

Processing tickers:  65%|██████▍   | 4483/6932 [16:05<08:48,  4.64it/s]

Processing tickers:  65%|██████▍   | 4484/6932 [16:05<08:44,  4.66it/s]

Processing tickers:  65%|██████▍   | 4485/6932 [16:05<08:42,  4.69it/s]

Processing tickers:  65%|██████▍   | 4486/6932 [16:05<08:32,  4.77it/s]

Processing tickers:  65%|██████▍   | 4487/6932 [16:05<08:28,  4.81it/s]

Processing tickers:  65%|██████▍   | 4488/6932 [16:06<08:50,  4.60it/s]

Processing tickers:  65%|██████▍   | 4489/6932 [16:06<08:45,  4.65it/s]

Processing tickers:  65%|██████▍   | 4490/6932 [16:06<08:39,  4.70it/s]

Processing tickers:  65%|██████▍   | 4491/6932 [16:06<08:36,  4.73it/s]

Processing tickers:  65%|██████▍   | 4492/6932 [16:07<08:42,  4.67it/s]

Processing tickers:  65%|██████▍   | 4493/6932 [16:07<08:37,  4.72it/s]

Processing tickers:  65%|██████▍   | 4494/6932 [16:07<08:35,  4.73it/s]

Processing tickers:  65%|██████▍   | 4495/6932 [16:07<08:33,  4.74it/s]

Processing tickers:  65%|██████▍   | 4496/6932 [16:07<08:32,  4.76it/s]

Processing tickers:  65%|██████▍   | 4497/6932 [16:08<08:29,  4.78it/s]

Processing tickers:  65%|██████▍   | 4498/6932 [16:08<08:40,  4.68it/s]

Processing tickers:  65%|██████▍   | 4499/6932 [16:08<08:35,  4.72it/s]

Processing tickers:  65%|██████▍   | 4500/6932 [16:08<08:32,  4.74it/s]

Processing tickers:  65%|██████▍   | 4501/6932 [16:08<08:30,  4.76it/s]

Processing tickers:  65%|██████▍   | 4502/6932 [16:09<08:41,  4.66it/s]

Processing tickers:  65%|██████▍   | 4503/6932 [16:09<08:35,  4.71it/s]

Processing tickers:  65%|██████▍   | 4504/6932 [16:09<08:32,  4.74it/s]

Processing tickers:  65%|██████▍   | 4505/6932 [16:09<08:29,  4.76it/s]

Processing tickers:  65%|██████▌   | 4506/6932 [16:10<08:27,  4.78it/s]

Processing tickers:  65%|██████▌   | 4507/6932 [16:10<08:39,  4.67it/s]

Processing tickers:  65%|██████▌   | 4508/6932 [16:10<08:33,  4.72it/s]

Processing tickers:  65%|██████▌   | 4509/6932 [16:10<08:32,  4.73it/s]

Processing tickers:  65%|██████▌   | 4510/6932 [16:10<08:26,  4.78it/s]

Processing tickers:  65%|██████▌   | 4511/6932 [16:11<08:25,  4.79it/s]

Processing tickers:  65%|██████▌   | 4512/6932 [16:11<08:34,  4.70it/s]

Processing tickers:  65%|██████▌   | 4513/6932 [16:11<08:33,  4.71it/s]

Processing tickers:  65%|██████▌   | 4514/6932 [16:11<08:33,  4.71it/s]

Processing tickers:  65%|██████▌   | 4515/6932 [16:11<08:28,  4.75it/s]

Processing tickers:  65%|██████▌   | 4516/6932 [16:12<08:25,  4.78it/s]

Processing tickers:  65%|██████▌   | 4517/6932 [16:12<08:24,  4.79it/s]

Processing tickers:  65%|██████▌   | 4518/6932 [16:12<08:24,  4.79it/s]

Processing tickers:  65%|██████▌   | 4519/6932 [16:12<08:29,  4.73it/s]

Processing tickers:  65%|██████▌   | 4520/6932 [16:12<08:21,  4.81it/s]

Processing tickers:  65%|██████▌   | 4521/6932 [16:13<08:22,  4.80it/s]

Processing tickers:  65%|██████▌   | 4522/6932 [16:13<08:22,  4.80it/s]

Processing tickers:  65%|██████▌   | 4523/6932 [16:13<08:21,  4.81it/s]

Processing tickers:  65%|██████▌   | 4524/6932 [16:13<08:23,  4.78it/s]

Processing tickers:  65%|██████▌   | 4525/6932 [16:14<08:18,  4.82it/s]

Processing tickers:  65%|██████▌   | 4526/6932 [16:14<08:19,  4.82it/s]

Processing tickers:  65%|██████▌   | 4527/6932 [16:14<08:26,  4.75it/s]

Processing tickers:  65%|██████▌   | 4528/6932 [16:14<08:26,  4.75it/s]

Processing tickers:  65%|██████▌   | 4529/6932 [16:14<08:24,  4.76it/s]

Processing tickers:  65%|██████▌   | 4530/6932 [16:15<09:05,  4.40it/s]

Processing tickers:  65%|██████▌   | 4531/6932 [16:15<08:50,  4.52it/s]

Processing tickers:  65%|██████▌   | 4532/6932 [16:15<08:48,  4.54it/s]

Processing tickers:  65%|██████▌   | 4533/6932 [16:15<08:38,  4.62it/s]

Processing tickers:  65%|██████▌   | 4534/6932 [16:15<08:32,  4.68it/s]

Processing tickers:  65%|██████▌   | 4535/6932 [16:16<08:28,  4.72it/s]

Processing tickers:  65%|██████▌   | 4536/6932 [16:16<08:25,  4.74it/s]

Processing tickers:  65%|██████▌   | 4537/6932 [16:16<08:33,  4.66it/s]

Processing tickers:  65%|██████▌   | 4538/6932 [16:16<08:29,  4.70it/s]

Processing tickers:  65%|██████▌   | 4539/6932 [16:17<08:25,  4.73it/s]

Processing tickers:  65%|██████▌   | 4540/6932 [16:17<08:22,  4.76it/s]

Processing tickers:  66%|██████▌   | 4541/6932 [16:17<08:24,  4.74it/s]

Processing tickers:  66%|██████▌   | 4542/6932 [16:17<08:19,  4.79it/s]

Processing tickers:  66%|██████▌   | 4543/6932 [16:17<08:18,  4.79it/s]

Processing tickers:  66%|██████▌   | 4544/6932 [16:18<08:18,  4.80it/s]

Processing tickers:  66%|██████▌   | 4545/6932 [16:18<08:17,  4.80it/s]

Processing tickers:  66%|██████▌   | 4546/6932 [16:18<09:14,  4.30it/s]

Processing tickers:  66%|██████▌   | 4547/6932 [16:18<08:57,  4.44it/s]

Processing tickers:  66%|██████▌   | 4548/6932 [16:18<08:44,  4.55it/s]

Processing tickers:  66%|██████▌   | 4549/6932 [16:19<08:37,  4.61it/s]

Processing tickers:  66%|██████▌   | 4550/6932 [16:19<08:29,  4.68it/s]

Processing tickers:  66%|██████▌   | 4551/6932 [16:19<08:25,  4.71it/s]

Processing tickers:  66%|██████▌   | 4552/6932 [16:19<08:25,  4.71it/s]

Processing tickers:  66%|██████▌   | 4553/6932 [16:20<08:19,  4.77it/s]

Processing tickers:  66%|██████▌   | 4554/6932 [16:20<08:34,  4.63it/s]

Processing tickers:  66%|██████▌   | 4555/6932 [16:20<08:25,  4.70it/s]

Processing tickers:  66%|██████▌   | 4556/6932 [16:20<08:19,  4.75it/s]

Processing tickers:  66%|██████▌   | 4557/6932 [16:20<08:29,  4.66it/s]

Processing tickers:  66%|██████▌   | 4558/6932 [16:21<08:25,  4.69it/s]

Processing tickers:  66%|██████▌   | 4559/6932 [16:21<08:20,  4.74it/s]

Processing tickers:  66%|██████▌   | 4560/6932 [16:21<08:21,  4.73it/s]

Processing tickers:  66%|██████▌   | 4561/6932 [16:21<08:15,  4.78it/s]

Processing tickers:  66%|██████▌   | 4562/6932 [16:21<08:15,  4.78it/s]

Processing tickers:  66%|██████▌   | 4563/6932 [16:22<08:25,  4.69it/s]

Processing tickers:  66%|██████▌   | 4564/6932 [16:22<08:21,  4.72it/s]

Processing tickers:  66%|██████▌   | 4565/6932 [16:22<08:18,  4.75it/s]

Processing tickers:  66%|██████▌   | 4566/6932 [16:22<08:29,  4.64it/s]

Processing tickers:  66%|██████▌   | 4567/6932 [16:22<08:22,  4.71it/s]

Processing tickers:  66%|██████▌   | 4568/6932 [16:23<08:19,  4.73it/s]

Processing tickers:  66%|██████▌   | 4569/6932 [16:23<08:16,  4.76it/s]

Processing tickers:  66%|██████▌   | 4570/6932 [16:23<08:22,  4.70it/s]

Processing tickers:  66%|██████▌   | 4571/6932 [16:23<08:20,  4.72it/s]

Processing tickers:  66%|██████▌   | 4572/6932 [16:24<08:08,  4.83it/s]

Processing tickers:  66%|██████▌   | 4573/6932 [16:24<08:22,  4.69it/s]

Processing tickers:  66%|██████▌   | 4574/6932 [16:24<08:16,  4.75it/s]

Processing tickers:  66%|██████▌   | 4575/6932 [16:24<08:14,  4.77it/s]

Processing tickers:  66%|██████▌   | 4576/6932 [16:24<08:25,  4.66it/s]

Processing tickers:  66%|██████▌   | 4577/6932 [16:25<08:08,  4.82it/s]

Processing tickers:  66%|██████▌   | 4578/6932 [16:25<08:20,  4.70it/s]

Processing tickers:  66%|██████▌   | 4579/6932 [16:25<08:16,  4.74it/s]

Processing tickers:  66%|██████▌   | 4580/6932 [16:25<08:25,  4.65it/s]

Processing tickers:  66%|██████▌   | 4581/6932 [16:25<08:34,  4.57it/s]

Processing tickers:  66%|██████▌   | 4582/6932 [16:26<08:34,  4.57it/s]

Processing tickers:  66%|██████▌   | 4583/6932 [16:26<08:47,  4.45it/s]

Processing tickers:  66%|██████▌   | 4584/6932 [16:26<08:44,  4.48it/s]

Processing tickers:  66%|██████▌   | 4585/6932 [16:26<08:44,  4.47it/s]

Processing tickers:  66%|██████▌   | 4586/6932 [16:27<08:37,  4.54it/s]

Processing tickers:  66%|██████▌   | 4587/6932 [16:27<08:31,  4.58it/s]

Processing tickers:  66%|██████▌   | 4588/6932 [16:27<08:17,  4.72it/s]

Processing tickers:  66%|██████▌   | 4589/6932 [16:27<08:26,  4.63it/s]

Processing tickers:  66%|██████▌   | 4590/6932 [16:27<08:19,  4.69it/s]

Processing tickers:  66%|██████▌   | 4591/6932 [16:28<08:15,  4.73it/s]

Processing tickers:  66%|██████▌   | 4592/6932 [16:28<08:12,  4.75it/s]

Processing tickers:  66%|██████▋   | 4593/6932 [16:28<08:10,  4.77it/s]

Processing tickers:  66%|██████▋   | 4594/6932 [16:28<08:23,  4.65it/s]

Processing tickers:  66%|██████▋   | 4595/6932 [16:28<08:15,  4.72it/s]

Processing tickers:  66%|██████▋   | 4596/6932 [16:29<08:23,  4.64it/s]

Processing tickers:  66%|██████▋   | 4597/6932 [16:29<08:18,  4.69it/s]

Processing tickers:  66%|██████▋   | 4598/6932 [16:29<08:14,  4.72it/s]

Processing tickers:  66%|██████▋   | 4599/6932 [16:29<08:11,  4.75it/s]

Processing tickers:  66%|██████▋   | 4600/6932 [16:30<08:09,  4.76it/s]

Processing tickers:  66%|██████▋   | 4601/6932 [16:30<08:07,  4.78it/s]

Processing tickers:  66%|██████▋   | 4602/6932 [16:30<08:06,  4.79it/s]

Processing tickers:  66%|██████▋   | 4603/6932 [16:30<08:13,  4.72it/s]

Processing tickers:  66%|██████▋   | 4604/6932 [16:30<08:11,  4.73it/s]

Processing tickers:  66%|██████▋   | 4605/6932 [16:31<08:00,  4.85it/s]

Processing tickers:  66%|██████▋   | 4606/6932 [16:31<08:01,  4.84it/s]

Processing tickers:  66%|██████▋   | 4607/6932 [16:31<08:13,  4.72it/s]

Processing tickers:  66%|██████▋   | 4608/6932 [16:31<08:09,  4.75it/s]

Processing tickers:  66%|██████▋   | 4609/6932 [16:31<08:07,  4.76it/s]

Processing tickers:  67%|██████▋   | 4610/6932 [16:32<08:06,  4.78it/s]

Processing tickers:  67%|██████▋   | 4611/6932 [16:32<08:04,  4.79it/s]

Processing tickers:  67%|██████▋   | 4612/6932 [16:32<08:10,  4.73it/s]

Processing tickers:  67%|██████▋   | 4613/6932 [16:32<08:09,  4.74it/s]

Processing tickers:  67%|██████▋   | 4614/6932 [16:32<08:11,  4.71it/s]

Processing tickers:  67%|██████▋   | 4615/6932 [16:33<08:07,  4.76it/s]

Processing tickers:  67%|██████▋   | 4616/6932 [16:33<08:06,  4.76it/s]

Processing tickers:  67%|██████▋   | 4617/6932 [16:33<08:05,  4.76it/s]

Processing tickers:  67%|██████▋   | 4618/6932 [16:33<08:06,  4.76it/s]

Processing tickers:  67%|██████▋   | 4619/6932 [16:34<08:00,  4.81it/s]

Processing tickers:  67%|██████▋   | 4620/6932 [16:34<08:11,  4.70it/s]

Processing tickers:  67%|██████▋   | 4621/6932 [16:34<08:08,  4.73it/s]

Processing tickers:  67%|██████▋   | 4622/6932 [16:34<08:05,  4.75it/s]

Processing tickers:  67%|██████▋   | 4623/6932 [16:34<08:04,  4.77it/s]

Processing tickers:  67%|██████▋   | 4624/6932 [16:35<08:04,  4.77it/s]

Processing tickers:  67%|██████▋   | 4625/6932 [16:35<08:03,  4.77it/s]

Processing tickers:  67%|██████▋   | 4626/6932 [16:35<08:11,  4.69it/s]

Processing tickers:  67%|██████▋   | 4627/6932 [16:35<08:20,  4.60it/s]

Processing tickers:  67%|██████▋   | 4628/6932 [16:35<08:10,  4.70it/s]

Processing tickers:  67%|██████▋   | 4629/6932 [16:36<08:05,  4.74it/s]

Processing tickers:  67%|██████▋   | 4630/6932 [16:36<08:03,  4.76it/s]

Processing tickers:  67%|██████▋   | 4631/6932 [16:36<08:02,  4.77it/s]

Processing tickers:  67%|██████▋   | 4632/6932 [16:36<08:12,  4.67it/s]

Processing tickers:  67%|██████▋   | 4633/6932 [16:36<08:08,  4.71it/s]

Processing tickers:  67%|██████▋   | 4634/6932 [16:37<08:04,  4.74it/s]

Processing tickers:  67%|██████▋   | 4635/6932 [16:37<08:10,  4.69it/s]

Processing tickers:  67%|██████▋   | 4636/6932 [16:37<07:58,  4.80it/s]

Processing tickers:  67%|██████▋   | 4637/6932 [16:37<08:07,  4.71it/s]

Processing tickers:  67%|██████▋   | 4638/6932 [16:38<08:03,  4.74it/s]

Processing tickers:  67%|██████▋   | 4639/6932 [16:38<08:01,  4.76it/s]

Processing tickers:  67%|██████▋   | 4640/6932 [16:38<08:07,  4.71it/s]

Processing tickers:  67%|██████▋   | 4641/6932 [16:38<08:07,  4.70it/s]

Processing tickers:  67%|██████▋   | 4642/6932 [16:38<07:56,  4.81it/s]

Processing tickers:  67%|██████▋   | 4643/6932 [16:39<07:53,  4.84it/s]

Processing tickers:  67%|██████▋   | 4644/6932 [16:39<08:03,  4.73it/s]

Processing tickers:  67%|██████▋   | 4645/6932 [16:39<08:02,  4.74it/s]

Processing tickers:  67%|██████▋   | 4646/6932 [16:39<08:00,  4.76it/s]

Processing tickers:  67%|██████▋   | 4647/6932 [16:39<07:58,  4.77it/s]

Processing tickers:  67%|██████▋   | 4648/6932 [16:40<08:10,  4.66it/s]

Processing tickers:  67%|██████▋   | 4649/6932 [16:40<08:03,  4.72it/s]

Processing tickers:  67%|██████▋   | 4650/6932 [16:40<08:08,  4.67it/s]

Processing tickers:  67%|██████▋   | 4651/6932 [16:40<08:08,  4.67it/s]

Processing tickers:  67%|██████▋   | 4652/6932 [16:41<08:06,  4.68it/s]

Processing tickers:  67%|██████▋   | 4653/6932 [16:41<08:11,  4.64it/s]

Processing tickers:  67%|██████▋   | 4654/6932 [16:41<08:05,  4.69it/s]

Processing tickers:  67%|██████▋   | 4655/6932 [16:41<08:01,  4.73it/s]

Processing tickers:  67%|██████▋   | 4656/6932 [16:41<08:10,  4.64it/s]

Processing tickers:  67%|██████▋   | 4657/6932 [16:42<08:07,  4.67it/s]

Processing tickers:  67%|██████▋   | 4658/6932 [16:42<07:59,  4.74it/s]

Processing tickers:  67%|██████▋   | 4659/6932 [16:42<08:04,  4.69it/s]

Processing tickers:  67%|██████▋   | 4660/6932 [16:42<07:55,  4.78it/s]

Processing tickers:  67%|██████▋   | 4661/6932 [16:42<07:52,  4.80it/s]

Processing tickers:  67%|██████▋   | 4662/6932 [16:43<07:52,  4.81it/s]

Processing tickers:  67%|██████▋   | 4663/6932 [16:43<07:58,  4.74it/s]

Processing tickers:  67%|██████▋   | 4664/6932 [16:43<07:49,  4.83it/s]

Processing tickers:  67%|██████▋   | 4665/6932 [16:43<08:01,  4.71it/s]

Processing tickers:  67%|██████▋   | 4666/6932 [16:43<08:09,  4.63it/s]

Processing tickers:  67%|██████▋   | 4667/6932 [16:44<08:02,  4.70it/s]

Processing tickers:  67%|██████▋   | 4668/6932 [16:44<07:59,  4.73it/s]

Processing tickers:  67%|██████▋   | 4669/6932 [16:44<07:55,  4.76it/s]

Processing tickers:  67%|██████▋   | 4670/6932 [16:44<08:04,  4.67it/s]

Processing tickers:  67%|██████▋   | 4671/6932 [16:45<07:58,  4.72it/s]

Processing tickers:  67%|██████▋   | 4672/6932 [16:45<07:56,  4.75it/s]

Processing tickers:  67%|██████▋   | 4673/6932 [16:45<07:54,  4.76it/s]

Processing tickers:  67%|██████▋   | 4674/6932 [16:45<07:52,  4.78it/s]

Processing tickers:  67%|██████▋   | 4675/6932 [16:45<07:51,  4.79it/s]

Processing tickers:  67%|██████▋   | 4676/6932 [16:46<07:49,  4.80it/s]

Processing tickers:  67%|██████▋   | 4677/6932 [16:46<07:59,  4.70it/s]

Processing tickers:  67%|██████▋   | 4678/6932 [16:46<07:56,  4.73it/s]

Processing tickers:  67%|██████▋   | 4679/6932 [16:46<07:54,  4.75it/s]

Processing tickers:  68%|██████▊   | 4680/6932 [16:46<08:02,  4.66it/s]

Processing tickers:  68%|██████▊   | 4681/6932 [16:47<08:08,  4.61it/s]

Processing tickers:  68%|██████▊   | 4682/6932 [16:47<07:52,  4.76it/s]

Processing tickers:  68%|██████▊   | 4683/6932 [16:47<08:02,  4.66it/s]

Processing tickers:  68%|██████▊   | 4684/6932 [16:47<07:57,  4.71it/s]

Processing tickers:  68%|██████▊   | 4685/6932 [16:47<07:54,  4.74it/s]

Processing tickers:  68%|██████▊   | 4686/6932 [16:48<08:08,  4.60it/s]

Processing tickers:  68%|██████▊   | 4687/6932 [16:48<08:06,  4.61it/s]

Processing tickers:  68%|██████▊   | 4688/6932 [16:48<08:11,  4.57it/s]

Processing tickers:  68%|██████▊   | 4689/6932 [16:48<08:04,  4.63it/s]

Processing tickers:  68%|██████▊   | 4690/6932 [16:49<07:59,  4.68it/s]

Processing tickers:  68%|██████▊   | 4691/6932 [16:49<07:55,  4.71it/s]

Processing tickers:  68%|██████▊   | 4692/6932 [16:49<08:03,  4.63it/s]

Processing tickers:  68%|██████▊   | 4693/6932 [16:49<07:57,  4.69it/s]

Processing tickers:  68%|██████▊   | 4694/6932 [16:49<07:53,  4.73it/s]

Processing tickers:  68%|██████▊   | 4695/6932 [16:50<08:01,  4.64it/s]

Processing tickers:  68%|██████▊   | 4696/6932 [16:50<07:59,  4.66it/s]

Processing tickers:  68%|██████▊   | 4697/6932 [16:50<07:52,  4.73it/s]

Processing tickers:  68%|██████▊   | 4698/6932 [16:50<07:55,  4.70it/s]

Processing tickers:  68%|██████▊   | 4699/6932 [16:50<07:46,  4.79it/s]

Processing tickers:  68%|██████▊   | 4700/6932 [16:51<07:46,  4.78it/s]

Processing tickers:  68%|██████▊   | 4701/6932 [16:51<07:44,  4.81it/s]

Processing tickers:  68%|██████▊   | 4702/6932 [16:51<07:57,  4.67it/s]

Processing tickers:  68%|██████▊   | 4703/6932 [16:51<07:57,  4.66it/s]

Processing tickers:  68%|██████▊   | 4704/6932 [16:52<07:56,  4.67it/s]

Processing tickers:  68%|██████▊   | 4705/6932 [16:52<07:52,  4.71it/s]

Processing tickers:  68%|██████▊   | 4706/6932 [16:52<07:49,  4.74it/s]

Processing tickers:  68%|██████▊   | 4707/6932 [16:52<07:52,  4.71it/s]

Processing tickers:  68%|██████▊   | 4708/6932 [16:52<07:44,  4.79it/s]

Processing tickers:  68%|██████▊   | 4709/6932 [16:53<07:43,  4.79it/s]

Processing tickers:  68%|██████▊   | 4710/6932 [16:53<07:51,  4.72it/s]

Processing tickers:  68%|██████▊   | 4711/6932 [16:53<07:50,  4.72it/s]

Processing tickers:  68%|██████▊   | 4712/6932 [16:53<07:47,  4.74it/s]

Processing tickers:  68%|██████▊   | 4713/6932 [16:53<07:45,  4.76it/s]

Processing tickers:  68%|██████▊   | 4714/6932 [16:54<08:08,  4.54it/s]

Processing tickers:  68%|██████▊   | 4715/6932 [16:54<07:57,  4.64it/s]

Processing tickers:  68%|██████▊   | 4716/6932 [16:54<07:55,  4.66it/s]

Processing tickers:  68%|██████▊   | 4717/6932 [16:54<07:47,  4.74it/s]

Processing tickers:  68%|██████▊   | 4718/6932 [16:55<07:57,  4.64it/s]

Processing tickers:  68%|██████▊   | 4719/6932 [16:55<07:50,  4.70it/s]

Processing tickers:  68%|██████▊   | 4720/6932 [16:55<07:58,  4.62it/s]

Processing tickers:  68%|██████▊   | 4721/6932 [16:55<07:52,  4.68it/s]

Processing tickers:  68%|██████▊   | 4722/6932 [16:55<07:48,  4.71it/s]

Processing tickers:  68%|██████▊   | 4723/6932 [16:56<07:46,  4.74it/s]

Processing tickers:  68%|██████▊   | 4724/6932 [16:56<07:46,  4.74it/s]

Processing tickers:  68%|██████▊   | 4725/6932 [16:56<07:42,  4.78it/s]

Processing tickers:  68%|██████▊   | 4726/6932 [16:56<07:51,  4.68it/s]

Processing tickers:  68%|██████▊   | 4727/6932 [16:56<07:36,  4.83it/s]

Processing tickers:  68%|██████▊   | 4728/6932 [16:57<07:35,  4.84it/s]

Processing tickers:  68%|██████▊   | 4729/6932 [16:57<07:44,  4.74it/s]

Processing tickers:  68%|██████▊   | 4730/6932 [16:57<07:51,  4.67it/s]

Processing tickers:  68%|██████▊   | 4731/6932 [16:57<08:00,  4.59it/s]

Processing tickers:  68%|██████▊   | 4732/6932 [16:58<08:03,  4.55it/s]

Processing tickers:  68%|██████▊   | 4733/6932 [16:58<08:04,  4.54it/s]

Processing tickers:  68%|██████▊   | 4734/6932 [16:58<08:12,  4.46it/s]

Processing tickers:  68%|██████▊   | 4735/6932 [16:58<07:57,  4.60it/s]

Processing tickers:  68%|██████▊   | 4736/6932 [16:58<07:59,  4.58it/s]

Processing tickers:  68%|██████▊   | 4737/6932 [16:59<07:52,  4.65it/s]

Processing tickers:  68%|██████▊   | 4738/6932 [16:59<07:51,  4.65it/s]

Processing tickers:  68%|██████▊   | 4739/6932 [16:59<07:48,  4.68it/s]

Processing tickers:  68%|██████▊   | 4740/6932 [16:59<07:45,  4.70it/s]

Processing tickers:  68%|██████▊   | 4741/6932 [16:59<07:40,  4.76it/s]

Processing tickers:  68%|██████▊   | 4742/6932 [17:00<07:34,  4.82it/s]

Processing tickers:  68%|██████▊   | 4743/6932 [17:00<07:34,  4.82it/s]

Processing tickers:  68%|██████▊   | 4744/6932 [17:00<07:45,  4.70it/s]

Processing tickers:  68%|██████▊   | 4745/6932 [17:00<07:41,  4.73it/s]

Processing tickers:  68%|██████▊   | 4746/6932 [17:01<07:49,  4.65it/s]

Processing tickers:  68%|██████▊   | 4747/6932 [17:01<07:45,  4.69it/s]

Processing tickers:  68%|██████▊   | 4748/6932 [17:01<07:52,  4.62it/s]

Processing tickers:  69%|██████▊   | 4749/6932 [17:01<07:47,  4.67it/s]

Processing tickers:  69%|██████▊   | 4750/6932 [17:01<07:53,  4.61it/s]

Processing tickers:  69%|██████▊   | 4751/6932 [17:02<07:48,  4.66it/s]

Processing tickers:  69%|██████▊   | 4752/6932 [17:02<07:42,  4.71it/s]

Processing tickers:  69%|██████▊   | 4753/6932 [17:02<07:51,  4.63it/s]

Processing tickers:  69%|██████▊   | 4754/6932 [17:02<07:49,  4.64it/s]

Processing tickers:  69%|██████▊   | 4755/6932 [17:02<07:40,  4.73it/s]

Processing tickers:  69%|██████▊   | 4756/6932 [17:03<07:37,  4.75it/s]

Processing tickers:  69%|██████▊   | 4757/6932 [17:03<07:35,  4.77it/s]

Processing tickers:  69%|██████▊   | 4758/6932 [17:03<07:34,  4.78it/s]

Processing tickers:  69%|██████▊   | 4759/6932 [17:03<07:34,  4.79it/s]

Processing tickers:  69%|██████▊   | 4760/6932 [17:03<07:43,  4.69it/s]

Processing tickers:  69%|██████▊   | 4761/6932 [17:04<07:30,  4.82it/s]

Processing tickers:  69%|██████▊   | 4762/6932 [17:04<07:42,  4.69it/s]

Processing tickers:  69%|██████▊   | 4763/6932 [17:04<07:44,  4.67it/s]

Processing tickers:  69%|██████▊   | 4764/6932 [17:04<07:39,  4.72it/s]

Processing tickers:  69%|██████▊   | 4765/6932 [17:05<07:38,  4.73it/s]

Processing tickers:  69%|██████▉   | 4766/6932 [17:05<07:35,  4.75it/s]

Processing tickers:  69%|██████▉   | 4767/6932 [17:05<07:35,  4.76it/s]

Processing tickers:  69%|██████▉   | 4768/6932 [17:05<07:43,  4.67it/s]

Processing tickers:  69%|██████▉   | 4769/6932 [17:05<07:49,  4.61it/s]

Processing tickers:  69%|██████▉   | 4770/6932 [17:06<07:40,  4.69it/s]

Processing tickers:  69%|██████▉   | 4771/6932 [17:06<07:46,  4.63it/s]

Processing tickers:  69%|██████▉   | 4772/6932 [17:06<07:42,  4.67it/s]

Processing tickers:  69%|██████▉   | 4773/6932 [17:06<07:46,  4.62it/s]

Processing tickers:  69%|██████▉   | 4774/6932 [17:06<07:41,  4.68it/s]

Processing tickers:  69%|██████▉   | 4775/6932 [17:07<07:38,  4.71it/s]

Processing tickers:  69%|██████▉   | 4776/6932 [17:07<07:34,  4.74it/s]

Processing tickers:  69%|██████▉   | 4777/6932 [17:07<07:40,  4.68it/s]

Processing tickers:  69%|██████▉   | 4778/6932 [17:07<07:39,  4.69it/s]

Processing tickers:  69%|██████▉   | 4779/6932 [17:08<07:41,  4.66it/s]

Processing tickers:  69%|██████▉   | 4780/6932 [17:08<07:57,  4.50it/s]

Processing tickers:  69%|██████▉   | 4781/6932 [17:08<07:48,  4.59it/s]

Processing tickers:  69%|██████▉   | 4782/6932 [17:08<07:41,  4.66it/s]

Processing tickers:  69%|██████▉   | 4783/6932 [17:08<07:43,  4.64it/s]

Processing tickers:  69%|██████▉   | 4784/6932 [17:09<07:42,  4.64it/s]

Processing tickers:  69%|██████▉   | 4785/6932 [17:09<07:39,  4.68it/s]

Processing tickers:  69%|██████▉   | 4786/6932 [17:09<07:33,  4.73it/s]

Processing tickers:  69%|██████▉   | 4787/6932 [17:09<07:44,  4.62it/s]

Processing tickers:  69%|██████▉   | 4788/6932 [17:10<07:49,  4.57it/s]

Processing tickers:  69%|██████▉   | 4789/6932 [17:10<07:52,  4.54it/s]

Processing tickers:  69%|██████▉   | 4790/6932 [17:10<07:48,  4.57it/s]

Processing tickers:  69%|██████▉   | 4791/6932 [17:10<07:46,  4.59it/s]

Processing tickers:  69%|██████▉   | 4792/6932 [17:10<07:39,  4.66it/s]

Processing tickers:  69%|██████▉   | 4793/6932 [17:11<07:40,  4.65it/s]

Processing tickers:  69%|██████▉   | 4794/6932 [17:11<07:29,  4.75it/s]

Processing tickers:  69%|██████▉   | 4795/6932 [17:11<07:28,  4.77it/s]

Processing tickers:  69%|██████▉   | 4796/6932 [17:11<07:26,  4.78it/s]

Processing tickers:  69%|██████▉   | 4797/6932 [17:11<07:36,  4.68it/s]

Processing tickers:  69%|██████▉   | 4798/6932 [17:12<07:32,  4.72it/s]

Processing tickers:  69%|██████▉   | 4799/6932 [17:12<07:29,  4.75it/s]

Processing tickers:  69%|██████▉   | 4800/6932 [17:12<07:37,  4.66it/s]

Processing tickers:  69%|██████▉   | 4801/6932 [17:12<07:33,  4.70it/s]

Processing tickers:  69%|██████▉   | 4802/6932 [17:12<07:44,  4.59it/s]

Processing tickers:  69%|██████▉   | 4803/6932 [17:13<07:33,  4.70it/s]

Processing tickers:  69%|██████▉   | 4804/6932 [17:13<07:29,  4.73it/s]

Processing tickers:  69%|██████▉   | 4805/6932 [17:13<07:40,  4.62it/s]

Processing tickers:  69%|██████▉   | 4806/6932 [17:13<07:34,  4.68it/s]

Processing tickers:  69%|██████▉   | 4807/6932 [17:14<07:28,  4.74it/s]

Processing tickers:  69%|██████▉   | 4808/6932 [17:14<07:28,  4.73it/s]

Processing tickers:  69%|██████▉   | 4809/6932 [17:14<07:33,  4.68it/s]

Processing tickers:  69%|██████▉   | 4810/6932 [17:14<07:29,  4.72it/s]

Processing tickers:  69%|██████▉   | 4811/6932 [17:14<07:26,  4.75it/s]

Processing tickers:  69%|██████▉   | 4812/6932 [17:15<07:15,  4.87it/s]

Processing tickers:  69%|██████▉   | 4813/6932 [17:15<07:26,  4.74it/s]

Processing tickers:  69%|██████▉   | 4814/6932 [17:15<07:26,  4.75it/s]

Processing tickers:  69%|██████▉   | 4815/6932 [17:15<07:25,  4.75it/s]

Processing tickers:  69%|██████▉   | 4816/6932 [17:15<07:21,  4.79it/s]

Processing tickers:  69%|██████▉   | 4817/6932 [17:16<07:29,  4.70it/s]

Processing tickers:  70%|██████▉   | 4818/6932 [17:16<07:27,  4.72it/s]

Processing tickers:  70%|██████▉   | 4819/6932 [17:16<07:25,  4.75it/s]

Processing tickers:  70%|██████▉   | 4820/6932 [17:16<07:26,  4.73it/s]

Processing tickers:  70%|██████▉   | 4821/6932 [17:17<07:33,  4.65it/s]

Processing tickers:  70%|██████▉   | 4822/6932 [17:17<07:36,  4.62it/s]

Processing tickers:  70%|██████▉   | 4823/6932 [17:17<07:21,  4.78it/s]

Processing tickers:  70%|██████▉   | 4824/6932 [17:17<08:02,  4.37it/s]

Processing tickers:  70%|██████▉   | 4825/6932 [17:17<07:48,  4.50it/s]

Processing tickers:  70%|██████▉   | 4826/6932 [17:18<07:47,  4.50it/s]

Processing tickers:  70%|██████▉   | 4827/6932 [17:18<07:40,  4.57it/s]

Processing tickers:  70%|██████▉   | 4828/6932 [17:18<07:32,  4.65it/s]

Processing tickers:  70%|██████▉   | 4829/6932 [17:18<07:36,  4.60it/s]

Processing tickers:  70%|██████▉   | 4830/6932 [17:18<07:30,  4.66it/s]

Processing tickers:  70%|██████▉   | 4831/6932 [17:19<07:27,  4.70it/s]

Processing tickers:  70%|██████▉   | 4832/6932 [17:19<07:25,  4.72it/s]

Processing tickers:  70%|██████▉   | 4833/6932 [17:19<07:26,  4.70it/s]

Processing tickers:  70%|██████▉   | 4834/6932 [17:19<07:17,  4.80it/s]

Processing tickers:  70%|██████▉   | 4835/6932 [17:20<07:16,  4.80it/s]

Processing tickers:  70%|██████▉   | 4836/6932 [17:20<07:26,  4.69it/s]

Processing tickers:  70%|██████▉   | 4837/6932 [17:20<07:23,  4.72it/s]

Processing tickers:  70%|██████▉   | 4838/6932 [17:20<07:21,  4.75it/s]

Processing tickers:  70%|██████▉   | 4839/6932 [17:20<07:28,  4.66it/s]

Processing tickers:  70%|██████▉   | 4840/6932 [17:21<07:36,  4.58it/s]

Processing tickers:  70%|██████▉   | 4841/6932 [17:21<07:27,  4.67it/s]

Processing tickers:  70%|██████▉   | 4842/6932 [17:21<07:24,  4.70it/s]

Processing tickers:  70%|██████▉   | 4843/6932 [17:21<07:31,  4.62it/s]

Processing tickers:  70%|██████▉   | 4844/6932 [17:21<07:26,  4.68it/s]

Processing tickers:  70%|██████▉   | 4845/6932 [17:22<07:22,  4.71it/s]

Processing tickers:  70%|██████▉   | 4846/6932 [17:22<07:37,  4.56it/s]

Processing tickers:  70%|██████▉   | 4847/6932 [17:22<07:33,  4.60it/s]

Processing tickers:  70%|██████▉   | 4848/6932 [17:22<07:26,  4.66it/s]

Processing tickers:  70%|██████▉   | 4849/6932 [17:23<07:22,  4.71it/s]

Processing tickers:  70%|██████▉   | 4850/6932 [17:23<07:19,  4.74it/s]

Processing tickers:  70%|██████▉   | 4851/6932 [17:23<07:27,  4.65it/s]

Processing tickers:  70%|██████▉   | 4852/6932 [17:23<07:14,  4.79it/s]

Processing tickers:  70%|███████   | 4853/6932 [17:23<07:12,  4.81it/s]

Processing tickers:  70%|███████   | 4854/6932 [17:24<07:32,  4.59it/s]

Processing tickers:  70%|███████   | 4855/6932 [17:24<07:29,  4.62it/s]

Processing tickers:  70%|███████   | 4856/6932 [17:24<07:31,  4.60it/s]

Processing tickers:  70%|███████   | 4857/6932 [17:24<07:25,  4.66it/s]

Processing tickers:  70%|███████   | 4858/6932 [17:24<07:21,  4.70it/s]

Processing tickers:  70%|███████   | 4859/6932 [17:25<07:18,  4.73it/s]

Processing tickers:  70%|███████   | 4860/6932 [17:25<07:24,  4.66it/s]

Processing tickers:  70%|███████   | 4861/6932 [17:25<07:21,  4.69it/s]

Processing tickers:  70%|███████   | 4862/6932 [17:25<07:28,  4.62it/s]

Processing tickers:  70%|███████   | 4863/6932 [17:26<07:28,  4.61it/s]

Processing tickers:  70%|███████   | 4864/6932 [17:26<07:26,  4.63it/s]

Processing tickers:  70%|███████   | 4865/6932 [17:26<07:22,  4.68it/s]

Processing tickers:  70%|███████   | 4866/6932 [17:26<07:19,  4.70it/s]

Processing tickers:  70%|███████   | 4867/6932 [17:26<07:13,  4.77it/s]

Processing tickers:  70%|███████   | 4868/6932 [17:27<07:11,  4.79it/s]

Processing tickers:  70%|███████   | 4869/6932 [17:27<07:10,  4.80it/s]

Processing tickers:  70%|███████   | 4870/6932 [17:27<07:09,  4.80it/s]

Processing tickers:  70%|███████   | 4871/6932 [17:27<07:09,  4.80it/s]

Processing tickers:  70%|███████   | 4872/6932 [17:27<07:07,  4.81it/s]

Processing tickers:  70%|███████   | 4873/6932 [17:28<07:06,  4.83it/s]

Processing tickers:  70%|███████   | 4874/6932 [17:28<07:10,  4.78it/s]

Processing tickers:  70%|███████   | 4875/6932 [17:28<07:05,  4.83it/s]

Processing tickers:  70%|███████   | 4876/6932 [17:28<07:08,  4.80it/s]

Processing tickers:  70%|███████   | 4877/6932 [17:28<07:14,  4.73it/s]

Processing tickers:  70%|███████   | 4878/6932 [17:29<07:11,  4.77it/s]

Processing tickers:  70%|███████   | 4879/6932 [17:29<07:02,  4.85it/s]

Processing tickers:  70%|███████   | 4880/6932 [17:29<07:03,  4.84it/s]

Processing tickers:  70%|███████   | 4881/6932 [17:29<07:05,  4.82it/s]

Processing tickers:  70%|███████   | 4882/6932 [17:30<07:16,  4.69it/s]

Processing tickers:  70%|███████   | 4883/6932 [17:30<07:20,  4.65it/s]

Processing tickers:  70%|███████   | 4884/6932 [17:30<07:16,  4.69it/s]

Processing tickers:  70%|███████   | 4885/6932 [17:30<07:13,  4.73it/s]

Processing tickers:  70%|███████   | 4886/6932 [17:30<07:09,  4.76it/s]

Processing tickers:  70%|███████   | 4887/6932 [17:31<07:09,  4.77it/s]

Processing tickers:  71%|███████   | 4888/6932 [17:31<07:08,  4.78it/s]

Processing tickers:  71%|███████   | 4889/6932 [17:31<07:07,  4.78it/s]

Processing tickers:  71%|███████   | 4890/6932 [17:31<07:12,  4.72it/s]

Processing tickers:  71%|███████   | 4891/6932 [17:31<07:03,  4.82it/s]

Processing tickers:  71%|███████   | 4892/6932 [17:32<07:03,  4.81it/s]

Processing tickers:  71%|███████   | 4893/6932 [17:32<07:11,  4.73it/s]

Processing tickers:  71%|███████   | 4894/6932 [17:32<07:01,  4.83it/s]

Processing tickers:  71%|███████   | 4895/6932 [17:32<07:01,  4.83it/s]

Processing tickers:  71%|███████   | 4896/6932 [17:32<07:14,  4.69it/s]

Processing tickers:  71%|███████   | 4897/6932 [17:33<07:07,  4.76it/s]

Processing tickers:  71%|███████   | 4898/6932 [17:33<07:06,  4.77it/s]

Processing tickers:  71%|███████   | 4899/6932 [17:33<07:05,  4.78it/s]

Processing tickers:  71%|███████   | 4900/6932 [17:33<07:04,  4.79it/s]

Processing tickers:  71%|███████   | 4901/6932 [17:33<07:03,  4.79it/s]

Processing tickers:  71%|███████   | 4902/6932 [17:34<07:12,  4.69it/s]

Processing tickers:  71%|███████   | 4903/6932 [17:34<07:09,  4.72it/s]

Processing tickers:  71%|███████   | 4904/6932 [17:34<07:06,  4.75it/s]

Processing tickers:  71%|███████   | 4905/6932 [17:34<07:05,  4.77it/s]

Processing tickers:  71%|███████   | 4906/6932 [17:35<07:03,  4.78it/s]

Processing tickers:  71%|███████   | 4907/6932 [17:35<07:03,  4.78it/s]

Processing tickers:  71%|███████   | 4908/6932 [17:35<07:02,  4.79it/s]

Processing tickers:  71%|███████   | 4909/6932 [17:35<07:02,  4.79it/s]

Processing tickers:  71%|███████   | 4910/6932 [17:35<07:11,  4.68it/s]

Processing tickers:  71%|███████   | 4911/6932 [17:36<07:16,  4.63it/s]

Processing tickers:  71%|███████   | 4912/6932 [17:36<07:09,  4.70it/s]

Processing tickers:  71%|███████   | 4913/6932 [17:36<07:15,  4.64it/s]

Processing tickers:  71%|███████   | 4914/6932 [17:36<07:09,  4.70it/s]

Processing tickers:  71%|███████   | 4915/6932 [17:36<07:06,  4.73it/s]

Processing tickers:  71%|███████   | 4916/6932 [17:37<06:54,  4.87it/s]

Processing tickers:  71%|███████   | 4917/6932 [17:37<07:05,  4.73it/s]

Processing tickers:  71%|███████   | 4918/6932 [17:37<07:03,  4.76it/s]

Processing tickers:  71%|███████   | 4919/6932 [17:37<07:01,  4.77it/s]

Processing tickers:  71%|███████   | 4920/6932 [17:37<07:01,  4.78it/s]

Processing tickers:  71%|███████   | 4921/6932 [17:38<07:09,  4.69it/s]

Processing tickers:  71%|███████   | 4922/6932 [17:38<07:17,  4.60it/s]

Processing tickers:  71%|███████   | 4923/6932 [17:38<07:09,  4.68it/s]

Processing tickers:  71%|███████   | 4924/6932 [17:38<07:09,  4.67it/s]

Processing tickers:  71%|███████   | 4925/6932 [17:39<07:01,  4.77it/s]

Processing tickers:  71%|███████   | 4926/6932 [17:39<07:04,  4.73it/s]

Processing tickers:  71%|███████   | 4927/6932 [17:39<07:03,  4.74it/s]

Processing tickers:  71%|███████   | 4928/6932 [17:39<06:55,  4.82it/s]

Processing tickers:  71%|███████   | 4929/6932 [17:39<07:02,  4.74it/s]

Processing tickers:  71%|███████   | 4930/6932 [17:40<06:54,  4.83it/s]

Processing tickers:  71%|███████   | 4931/6932 [17:40<06:54,  4.83it/s]

Processing tickers:  71%|███████   | 4932/6932 [17:40<07:05,  4.70it/s]

Processing tickers:  71%|███████   | 4933/6932 [17:40<07:04,  4.71it/s]

Processing tickers:  71%|███████   | 4934/6932 [17:40<06:58,  4.77it/s]

Processing tickers:  71%|███████   | 4935/6932 [17:41<06:57,  4.78it/s]

Processing tickers:  71%|███████   | 4936/6932 [17:41<06:57,  4.79it/s]

Processing tickers:  71%|███████   | 4937/6932 [17:41<06:56,  4.79it/s]

Processing tickers:  71%|███████   | 4938/6932 [17:41<07:01,  4.74it/s]

Processing tickers:  71%|███████   | 4939/6932 [17:41<06:53,  4.82it/s]

Processing tickers:  71%|███████▏  | 4940/6932 [17:42<06:53,  4.82it/s]

Processing tickers:  71%|███████▏  | 4941/6932 [17:42<06:53,  4.82it/s]

Processing tickers:  71%|███████▏  | 4942/6932 [17:43<18:57,  1.75it/s]

Processing tickers:  71%|███████▏  | 4943/6932 [17:44<15:23,  2.15it/s]

Processing tickers:  71%|███████▏  | 4944/6932 [17:44<12:47,  2.59it/s]

Processing tickers:  71%|███████▏  | 4945/6932 [17:44<11:08,  2.97it/s]

Processing tickers:  71%|███████▏  | 4946/6932 [17:44<10:07,  3.27it/s]

Processing tickers:  71%|███████▏  | 4947/6932 [17:44<09:03,  3.65it/s]

Processing tickers:  71%|███████▏  | 4948/6932 [17:45<08:29,  3.89it/s]

Processing tickers:  71%|███████▏  | 4949/6932 [17:45<07:55,  4.17it/s]

Processing tickers:  71%|███████▏  | 4950/6932 [17:45<07:42,  4.29it/s]

Processing tickers:  71%|███████▏  | 4951/6932 [17:45<07:21,  4.49it/s]

Processing tickers:  71%|███████▏  | 4952/6932 [17:45<07:12,  4.58it/s]

Processing tickers:  71%|███████▏  | 4953/6932 [17:46<07:06,  4.64it/s]

Processing tickers:  71%|███████▏  | 4954/6932 [17:46<07:03,  4.67it/s]

Processing tickers:  71%|███████▏  | 4955/6932 [17:46<06:58,  4.73it/s]

Processing tickers:  71%|███████▏  | 4956/6932 [17:46<07:03,  4.67it/s]

Processing tickers:  72%|███████▏  | 4957/6932 [17:46<06:52,  4.79it/s]

Processing tickers:  72%|███████▏  | 4958/6932 [17:47<06:51,  4.79it/s]

Processing tickers:  72%|███████▏  | 4959/6932 [17:47<06:51,  4.80it/s]

Processing tickers:  72%|███████▏  | 4960/6932 [17:47<06:50,  4.80it/s]

Processing tickers:  72%|███████▏  | 4961/6932 [17:47<06:55,  4.75it/s]

Processing tickers:  72%|███████▏  | 4962/6932 [17:48<06:55,  4.74it/s]

Processing tickers:  72%|███████▏  | 4963/6932 [17:48<06:55,  4.73it/s]

Processing tickers:  72%|███████▏  | 4964/6932 [17:48<06:54,  4.75it/s]

Processing tickers:  72%|███████▏  | 4965/6932 [17:48<06:52,  4.77it/s]

Processing tickers:  72%|███████▏  | 4966/6932 [17:48<06:51,  4.78it/s]

Processing tickers:  72%|███████▏  | 4967/6932 [17:49<06:59,  4.68it/s]

Processing tickers:  72%|███████▏  | 4968/6932 [17:49<06:56,  4.71it/s]

Processing tickers:  72%|███████▏  | 4969/6932 [17:49<06:54,  4.73it/s]

Processing tickers:  72%|███████▏  | 4970/6932 [17:49<06:57,  4.69it/s]

Processing tickers:  72%|███████▏  | 4971/6932 [17:49<06:47,  4.82it/s]

Processing tickers:  72%|███████▏  | 4972/6932 [17:50<06:46,  4.82it/s]

Processing tickers:  72%|███████▏  | 4973/6932 [17:50<06:55,  4.71it/s]

Processing tickers:  72%|███████▏  | 4974/6932 [17:50<06:53,  4.74it/s]

Processing tickers:  72%|███████▏  | 4975/6932 [17:50<06:51,  4.76it/s]

Processing tickers:  72%|███████▏  | 4976/6932 [17:50<06:49,  4.77it/s]

Processing tickers:  72%|███████▏  | 4977/6932 [17:51<06:57,  4.68it/s]

Processing tickers:  72%|███████▏  | 4978/6932 [17:51<07:03,  4.61it/s]

Processing tickers:  72%|███████▏  | 4979/6932 [17:51<06:58,  4.67it/s]

Processing tickers:  72%|███████▏  | 4980/6932 [17:51<06:54,  4.71it/s]

Processing tickers:  72%|███████▏  | 4981/6932 [17:52<06:51,  4.75it/s]

Processing tickers:  72%|███████▏  | 4982/6932 [17:52<06:54,  4.70it/s]

Processing tickers:  72%|███████▏  | 4983/6932 [17:52<06:56,  4.68it/s]

Processing tickers:  72%|███████▏  | 4984/6932 [17:52<06:52,  4.73it/s]

Processing tickers:  72%|███████▏  | 4985/6932 [17:52<06:50,  4.75it/s]

Processing tickers:  72%|███████▏  | 4986/6932 [17:53<06:48,  4.77it/s]

Processing tickers:  72%|███████▏  | 4987/6932 [17:53<06:55,  4.68it/s]

Processing tickers:  72%|███████▏  | 4988/6932 [17:53<06:53,  4.70it/s]

Processing tickers:  72%|███████▏  | 4989/6932 [17:53<06:50,  4.74it/s]

Processing tickers:  72%|███████▏  | 4990/6932 [17:53<06:48,  4.76it/s]

Processing tickers:  72%|███████▏  | 4991/6932 [17:54<06:46,  4.78it/s]

Processing tickers:  72%|███████▏  | 4992/6932 [17:54<06:45,  4.79it/s]

Processing tickers:  72%|███████▏  | 4993/6932 [17:54<06:44,  4.79it/s]

Processing tickers:  72%|███████▏  | 4994/6932 [17:54<06:43,  4.81it/s]

Processing tickers:  72%|███████▏  | 4995/6932 [17:55<06:46,  4.77it/s]

Processing tickers:  72%|███████▏  | 4996/6932 [17:55<06:52,  4.70it/s]

Processing tickers:  72%|███████▏  | 4997/6932 [17:55<06:58,  4.62it/s]

Processing tickers:  72%|███████▏  | 4998/6932 [17:55<06:54,  4.67it/s]

Processing tickers:  72%|███████▏  | 4999/6932 [17:55<06:59,  4.61it/s]

Processing tickers:  72%|███████▏  | 5000/6932 [17:56<07:02,  4.57it/s]

Processing tickers:  72%|███████▏  | 5001/6932 [17:56<06:57,  4.62it/s]

Processing tickers:  72%|███████▏  | 5002/6932 [17:56<06:52,  4.68it/s]

Processing tickers:  72%|███████▏  | 5003/6932 [17:56<06:43,  4.78it/s]

Processing tickers:  72%|███████▏  | 5004/6932 [17:56<06:48,  4.72it/s]

Processing tickers:  72%|███████▏  | 5005/6932 [17:57<06:49,  4.71it/s]

Processing tickers:  72%|███████▏  | 5006/6932 [17:57<06:46,  4.74it/s]

Processing tickers:  72%|███████▏  | 5007/6932 [17:57<06:44,  4.76it/s]

Processing tickers:  72%|███████▏  | 5008/6932 [17:57<06:50,  4.68it/s]

Processing tickers:  72%|███████▏  | 5009/6932 [17:58<07:05,  4.52it/s]

Processing tickers:  72%|███████▏  | 5010/6932 [17:58<06:57,  4.61it/s]

Processing tickers:  72%|███████▏  | 5011/6932 [17:58<06:57,  4.60it/s]

Processing tickers:  72%|███████▏  | 5012/6932 [17:58<06:45,  4.73it/s]

Processing tickers:  72%|███████▏  | 5013/6932 [17:58<06:43,  4.75it/s]

Processing tickers:  72%|███████▏  | 5014/6932 [17:59<06:51,  4.66it/s]

Processing tickers:  72%|███████▏  | 5015/6932 [17:59<06:47,  4.70it/s]

Processing tickers:  72%|███████▏  | 5016/6932 [17:59<06:44,  4.73it/s]

Processing tickers:  72%|███████▏  | 5017/6932 [17:59<06:42,  4.75it/s]

Processing tickers:  72%|███████▏  | 5018/6932 [17:59<06:52,  4.64it/s]

Processing tickers:  72%|███████▏  | 5019/6932 [18:00<06:54,  4.62it/s]

Processing tickers:  72%|███████▏  | 5020/6932 [18:00<06:49,  4.67it/s]

Processing tickers:  72%|███████▏  | 5021/6932 [18:00<06:40,  4.78it/s]

Processing tickers:  72%|███████▏  | 5022/6932 [18:00<06:44,  4.72it/s]

Processing tickers:  72%|███████▏  | 5023/6932 [18:00<06:33,  4.86it/s]

Processing tickers:  72%|███████▏  | 5024/6932 [18:01<06:43,  4.73it/s]

Processing tickers:  72%|███████▏  | 5025/6932 [18:01<06:45,  4.70it/s]

Processing tickers:  73%|███████▎  | 5026/6932 [18:01<06:41,  4.75it/s]

Processing tickers:  73%|███████▎  | 5027/6932 [18:01<06:37,  4.80it/s]

Processing tickers:  73%|███████▎  | 5028/6932 [18:02<06:36,  4.80it/s]

Processing tickers:  73%|███████▎  | 5029/6932 [18:02<06:54,  4.59it/s]

Processing tickers:  73%|███████▎  | 5030/6932 [18:02<06:48,  4.65it/s]

Processing tickers:  73%|███████▎  | 5031/6932 [18:02<06:36,  4.79it/s]

Processing tickers:  73%|███████▎  | 5032/6932 [18:02<06:35,  4.81it/s]

Processing tickers:  73%|███████▎  | 5033/6932 [18:03<06:34,  4.81it/s]

Processing tickers:  73%|███████▎  | 5034/6932 [18:03<06:44,  4.69it/s]

Processing tickers:  73%|███████▎  | 5035/6932 [18:03<06:41,  4.72it/s]

Processing tickers:  73%|███████▎  | 5036/6932 [18:03<06:47,  4.65it/s]

Processing tickers:  73%|███████▎  | 5037/6932 [18:03<06:44,  4.68it/s]

Processing tickers:  73%|███████▎  | 5038/6932 [18:04<06:40,  4.73it/s]

Processing tickers:  73%|███████▎  | 5039/6932 [18:04<06:38,  4.75it/s]

Processing tickers:  73%|███████▎  | 5040/6932 [18:04<06:36,  4.77it/s]

Processing tickers:  73%|███████▎  | 5041/6932 [18:04<06:44,  4.68it/s]

Processing tickers:  73%|███████▎  | 5042/6932 [18:05<06:40,  4.71it/s]

Processing tickers:  73%|███████▎  | 5043/6932 [18:05<06:47,  4.64it/s]

Processing tickers:  73%|███████▎  | 5044/6932 [18:05<06:45,  4.65it/s]

Processing tickers:  73%|███████▎  | 5045/6932 [18:05<06:44,  4.66it/s]

Processing tickers:  73%|███████▎  | 5046/6932 [18:05<06:44,  4.67it/s]

Processing tickers:  73%|███████▎  | 5047/6932 [18:06<06:48,  4.62it/s]

Processing tickers:  73%|███████▎  | 5048/6932 [18:06<06:43,  4.67it/s]

Processing tickers:  73%|███████▎  | 5049/6932 [18:06<06:38,  4.73it/s]

Processing tickers:  73%|███████▎  | 5050/6932 [18:06<06:43,  4.66it/s]

Processing tickers:  73%|███████▎  | 5051/6932 [18:06<06:46,  4.63it/s]

Processing tickers:  73%|███████▎  | 5052/6932 [18:07<06:35,  4.75it/s]

Processing tickers:  73%|███████▎  | 5053/6932 [18:07<06:43,  4.66it/s]

Processing tickers:  73%|███████▎  | 5054/6932 [18:07<06:38,  4.71it/s]

Processing tickers:  73%|███████▎  | 5055/6932 [18:07<06:45,  4.63it/s]

Processing tickers:  73%|███████▎  | 5056/6932 [18:08<06:48,  4.59it/s]

Processing tickers:  73%|███████▎  | 5057/6932 [18:08<07:01,  4.45it/s]

Processing tickers:  73%|███████▎  | 5058/6932 [18:08<06:50,  4.56it/s]

Processing tickers:  73%|███████▎  | 5059/6932 [18:08<06:44,  4.63it/s]

Processing tickers:  73%|███████▎  | 5060/6932 [18:08<06:43,  4.64it/s]

Processing tickers:  73%|███████▎  | 5061/6932 [18:09<06:40,  4.67it/s]

Processing tickers:  73%|███████▎  | 5062/6932 [18:09<06:31,  4.77it/s]

Processing tickers:  73%|███████▎  | 5063/6932 [18:09<06:30,  4.78it/s]

Processing tickers:  73%|███████▎  | 5064/6932 [18:09<06:39,  4.68it/s]

Processing tickers:  73%|███████▎  | 5065/6932 [18:09<06:35,  4.72it/s]

Processing tickers:  73%|███████▎  | 5066/6932 [18:10<06:33,  4.75it/s]

Processing tickers:  73%|███████▎  | 5067/6932 [18:10<06:31,  4.76it/s]

Processing tickers:  73%|███████▎  | 5068/6932 [18:10<06:30,  4.77it/s]

Processing tickers:  73%|███████▎  | 5069/6932 [18:10<06:20,  4.89it/s]

Processing tickers:  73%|███████▎  | 5070/6932 [18:10<06:31,  4.76it/s]

Processing tickers:  73%|███████▎  | 5071/6932 [18:11<06:34,  4.72it/s]

Processing tickers:  73%|███████▎  | 5072/6932 [18:11<06:27,  4.80it/s]

Processing tickers:  73%|███████▎  | 5073/6932 [18:11<06:27,  4.80it/s]

Processing tickers:  73%|███████▎  | 5074/6932 [18:11<06:27,  4.79it/s]

Processing tickers:  73%|███████▎  | 5075/6932 [18:12<06:27,  4.79it/s]

Processing tickers:  73%|███████▎  | 5076/6932 [18:12<06:35,  4.69it/s]

Processing tickers:  73%|███████▎  | 5077/6932 [18:12<06:33,  4.71it/s]

Processing tickers:  73%|███████▎  | 5078/6932 [18:12<06:30,  4.75it/s]

Processing tickers:  73%|███████▎  | 5079/6932 [18:12<06:28,  4.77it/s]

Processing tickers:  73%|███████▎  | 5080/6932 [18:13<06:27,  4.78it/s]

Processing tickers:  73%|███████▎  | 5081/6932 [18:13<06:20,  4.87it/s]

Processing tickers:  73%|███████▎  | 5082/6932 [18:13<06:27,  4.77it/s]

Processing tickers:  73%|███████▎  | 5083/6932 [18:13<06:27,  4.77it/s]

Processing tickers:  73%|███████▎  | 5084/6932 [18:13<06:34,  4.69it/s]

Processing tickers:  73%|███████▎  | 5085/6932 [18:14<06:40,  4.61it/s]

Processing tickers:  73%|███████▎  | 5086/6932 [18:14<06:34,  4.68it/s]

Processing tickers:  73%|███████▎  | 5087/6932 [18:14<06:31,  4.71it/s]

Processing tickers:  73%|███████▎  | 5088/6932 [18:14<06:28,  4.74it/s]

Processing tickers:  73%|███████▎  | 5089/6932 [18:14<06:32,  4.69it/s]

Processing tickers:  73%|███████▎  | 5090/6932 [18:15<06:33,  4.69it/s]

Processing tickers:  73%|███████▎  | 5091/6932 [18:15<06:29,  4.72it/s]

Processing tickers:  73%|███████▎  | 5092/6932 [18:15<06:38,  4.62it/s]

Processing tickers:  73%|███████▎  | 5093/6932 [18:15<06:31,  4.70it/s]

Processing tickers:  73%|███████▎  | 5094/6932 [18:16<06:34,  4.66it/s]

Processing tickers:  73%|███████▎  | 5095/6932 [18:16<06:24,  4.77it/s]

Processing tickers:  74%|███████▎  | 5096/6932 [18:16<06:32,  4.67it/s]

Processing tickers:  74%|███████▎  | 5097/6932 [18:16<06:29,  4.71it/s]

Processing tickers:  74%|███████▎  | 5098/6932 [18:16<06:26,  4.74it/s]

Processing tickers:  74%|███████▎  | 5099/6932 [18:17<06:29,  4.71it/s]

Processing tickers:  74%|███████▎  | 5100/6932 [18:17<06:22,  4.79it/s]

Processing tickers:  74%|███████▎  | 5101/6932 [18:17<06:26,  4.74it/s]

Processing tickers:  74%|███████▎  | 5102/6932 [18:17<06:25,  4.75it/s]

Processing tickers:  74%|███████▎  | 5103/6932 [18:17<06:26,  4.73it/s]

Processing tickers:  74%|███████▎  | 5104/6932 [18:18<06:24,  4.75it/s]

Processing tickers:  74%|███████▎  | 5105/6932 [18:18<06:23,  4.77it/s]

Processing tickers:  74%|███████▎  | 5106/6932 [18:18<06:22,  4.78it/s]

Processing tickers:  74%|███████▎  | 5107/6932 [18:18<06:21,  4.79it/s]

Processing tickers:  74%|███████▎  | 5108/6932 [18:18<06:20,  4.80it/s]

Processing tickers:  74%|███████▎  | 5109/6932 [18:19<06:19,  4.81it/s]

Processing tickers:  74%|███████▎  | 5110/6932 [18:19<06:21,  4.78it/s]

Processing tickers:  74%|███████▎  | 5111/6932 [18:19<06:18,  4.81it/s]

Processing tickers:  74%|███████▎  | 5112/6932 [18:19<06:23,  4.74it/s]

Processing tickers:  74%|███████▍  | 5113/6932 [18:20<06:26,  4.71it/s]

Processing tickers:  74%|███████▍  | 5114/6932 [18:20<06:27,  4.70it/s]

Processing tickers:  74%|███████▍  | 5115/6932 [18:20<06:20,  4.78it/s]

Processing tickers:  74%|███████▍  | 5116/6932 [18:20<06:19,  4.79it/s]

Processing tickers:  74%|███████▍  | 5117/6932 [18:20<06:18,  4.79it/s]

Processing tickers:  74%|███████▍  | 5118/6932 [18:21<06:18,  4.80it/s]

Processing tickers:  74%|███████▍  | 5119/6932 [18:21<06:31,  4.63it/s]

Processing tickers:  74%|███████▍  | 5120/6932 [18:21<06:22,  4.74it/s]

Processing tickers:  74%|███████▍  | 5121/6932 [18:21<06:20,  4.76it/s]

Processing tickers:  74%|███████▍  | 5122/6932 [18:21<06:18,  4.78it/s]

Processing tickers:  74%|███████▍  | 5123/6932 [18:22<06:17,  4.79it/s]

Processing tickers:  74%|███████▍  | 5124/6932 [18:22<06:17,  4.79it/s]

Processing tickers:  74%|███████▍  | 5125/6932 [18:22<06:20,  4.74it/s]

Processing tickers:  74%|███████▍  | 5126/6932 [18:22<06:22,  4.72it/s]

Processing tickers:  74%|███████▍  | 5127/6932 [18:22<06:13,  4.83it/s]

Processing tickers:  74%|███████▍  | 5128/6932 [18:23<06:13,  4.83it/s]

Processing tickers:  74%|███████▍  | 5129/6932 [18:23<06:16,  4.79it/s]

Processing tickers:  74%|███████▍  | 5130/6932 [18:23<06:16,  4.79it/s]

Processing tickers:  74%|███████▍  | 5131/6932 [18:23<06:12,  4.83it/s]

Processing tickers:  74%|███████▍  | 5132/6932 [18:24<06:13,  4.82it/s]

Processing tickers:  74%|███████▍  | 5133/6932 [18:24<06:22,  4.70it/s]

Processing tickers:  74%|███████▍  | 5134/6932 [18:24<06:27,  4.64it/s]

Processing tickers:  74%|███████▍  | 5135/6932 [18:24<06:25,  4.67it/s]

Processing tickers:  74%|███████▍  | 5136/6932 [18:24<06:19,  4.73it/s]

Processing tickers:  74%|███████▍  | 5137/6932 [18:25<06:18,  4.75it/s]

Processing tickers:  74%|███████▍  | 5138/6932 [18:25<06:19,  4.73it/s]

Processing tickers:  74%|███████▍  | 5139/6932 [18:25<06:15,  4.78it/s]

Processing tickers:  74%|███████▍  | 5140/6932 [18:25<06:14,  4.78it/s]

Processing tickers:  74%|███████▍  | 5141/6932 [18:25<06:13,  4.79it/s]

Processing tickers:  74%|███████▍  | 5142/6932 [18:26<06:13,  4.79it/s]

Processing tickers:  74%|███████▍  | 5143/6932 [18:26<06:12,  4.80it/s]

Processing tickers:  74%|███████▍  | 5144/6932 [18:26<06:22,  4.67it/s]

Processing tickers:  74%|███████▍  | 5145/6932 [18:26<06:17,  4.73it/s]

Processing tickers:  74%|███████▍  | 5146/6932 [18:27<06:26,  4.62it/s]

Processing tickers:  74%|███████▍  | 5147/6932 [18:27<06:27,  4.61it/s]

Processing tickers:  74%|███████▍  | 5148/6932 [18:27<06:21,  4.68it/s]

Processing tickers:  74%|███████▍  | 5149/6932 [18:27<06:23,  4.65it/s]

Processing tickers:  74%|███████▍  | 5150/6932 [18:27<06:29,  4.57it/s]

Processing tickers:  74%|███████▍  | 5151/6932 [18:28<06:22,  4.66it/s]

Processing tickers:  74%|███████▍  | 5152/6932 [18:28<06:28,  4.59it/s]

Processing tickers:  74%|███████▍  | 5153/6932 [18:28<06:21,  4.66it/s]

Processing tickers:  74%|███████▍  | 5154/6932 [18:28<06:17,  4.71it/s]

Processing tickers:  74%|███████▍  | 5155/6932 [18:28<06:15,  4.73it/s]

Processing tickers:  74%|███████▍  | 5156/6932 [18:29<06:21,  4.65it/s]

Processing tickers:  74%|███████▍  | 5157/6932 [18:29<06:19,  4.67it/s]

Processing tickers:  74%|███████▍  | 5158/6932 [18:29<06:23,  4.62it/s]

Processing tickers:  74%|███████▍  | 5159/6932 [18:29<06:16,  4.71it/s]

Processing tickers:  74%|███████▍  | 5160/6932 [18:30<06:18,  4.68it/s]

Processing tickers:  74%|███████▍  | 5161/6932 [18:30<06:18,  4.68it/s]

Processing tickers:  74%|███████▍  | 5162/6932 [18:30<06:14,  4.73it/s]

Processing tickers:  74%|███████▍  | 5163/6932 [18:30<06:12,  4.75it/s]

Processing tickers:  74%|███████▍  | 5164/6932 [18:30<06:10,  4.77it/s]

Processing tickers:  75%|███████▍  | 5165/6932 [18:31<06:09,  4.79it/s]

Processing tickers:  75%|███████▍  | 5166/6932 [18:31<06:11,  4.76it/s]

Processing tickers:  75%|███████▍  | 5167/6932 [18:31<06:06,  4.81it/s]

Processing tickers:  75%|███████▍  | 5168/6932 [18:31<06:08,  4.79it/s]

Processing tickers:  75%|███████▍  | 5169/6932 [18:31<06:05,  4.82it/s]

Processing tickers:  75%|███████▍  | 5170/6932 [18:32<06:06,  4.81it/s]

Processing tickers:  75%|███████▍  | 5171/6932 [18:32<06:13,  4.72it/s]

Processing tickers:  75%|███████▍  | 5172/6932 [18:32<06:12,  4.72it/s]

Processing tickers:  75%|███████▍  | 5173/6932 [18:32<06:10,  4.75it/s]

Processing tickers:  75%|███████▍  | 5174/6932 [18:32<06:08,  4.77it/s]

Processing tickers:  75%|███████▍  | 5175/6932 [18:33<06:07,  4.78it/s]

Processing tickers:  75%|███████▍  | 5176/6932 [18:33<06:07,  4.78it/s]

Processing tickers:  75%|███████▍  | 5177/6932 [18:33<06:09,  4.74it/s]

Processing tickers:  75%|███████▍  | 5178/6932 [18:33<06:09,  4.74it/s]

Processing tickers:  75%|███████▍  | 5179/6932 [18:33<06:02,  4.83it/s]

Processing tickers:  75%|███████▍  | 5180/6932 [18:34<06:03,  4.81it/s]

Processing tickers:  75%|███████▍  | 5181/6932 [18:34<06:02,  4.82it/s]

Processing tickers:  75%|███████▍  | 5182/6932 [18:34<06:11,  4.71it/s]

Processing tickers:  75%|███████▍  | 5183/6932 [18:34<06:08,  4.74it/s]

Processing tickers:  75%|███████▍  | 5184/6932 [18:35<06:06,  4.76it/s]

Processing tickers:  75%|███████▍  | 5185/6932 [18:35<06:06,  4.77it/s]

Processing tickers:  75%|███████▍  | 5186/6932 [18:35<06:10,  4.71it/s]

Processing tickers:  75%|███████▍  | 5187/6932 [18:35<06:11,  4.70it/s]

Processing tickers:  75%|███████▍  | 5188/6932 [18:35<06:08,  4.73it/s]

Processing tickers:  75%|███████▍  | 5189/6932 [18:36<06:07,  4.74it/s]

Processing tickers:  75%|███████▍  | 5190/6932 [18:36<06:03,  4.79it/s]

Processing tickers:  75%|███████▍  | 5191/6932 [18:36<06:03,  4.79it/s]

Processing tickers:  75%|███████▍  | 5192/6932 [18:36<06:01,  4.82it/s]

Processing tickers:  75%|███████▍  | 5193/6932 [18:36<06:00,  4.83it/s]

Processing tickers:  75%|███████▍  | 5194/6932 [18:37<06:09,  4.71it/s]

Processing tickers:  75%|███████▍  | 5195/6932 [18:37<06:06,  4.74it/s]

Processing tickers:  75%|███████▍  | 5196/6932 [18:37<06:04,  4.77it/s]

Processing tickers:  75%|███████▍  | 5197/6932 [18:37<06:10,  4.68it/s]

Processing tickers:  75%|███████▍  | 5198/6932 [18:37<06:07,  4.72it/s]

Processing tickers:  75%|███████▌  | 5199/6932 [18:38<06:13,  4.64it/s]

Processing tickers:  75%|███████▌  | 5200/6932 [18:38<06:09,  4.69it/s]

Processing tickers:  75%|███████▌  | 5201/6932 [18:38<06:14,  4.62it/s]

Processing tickers:  75%|███████▌  | 5202/6932 [18:38<06:16,  4.59it/s]

Processing tickers:  75%|███████▌  | 5203/6932 [18:39<06:05,  4.73it/s]

Processing tickers:  75%|███████▌  | 5204/6932 [18:39<06:03,  4.76it/s]

Processing tickers:  75%|███████▌  | 5205/6932 [18:39<06:06,  4.72it/s]

Processing tickers:  75%|███████▌  | 5206/6932 [18:39<06:00,  4.79it/s]

Processing tickers:  75%|███████▌  | 5207/6932 [18:39<05:59,  4.79it/s]

Processing tickers:  75%|███████▌  | 5208/6932 [18:40<05:58,  4.80it/s]

Processing tickers:  75%|███████▌  | 5209/6932 [18:40<05:58,  4.80it/s]

Processing tickers:  75%|███████▌  | 5210/6932 [18:40<05:58,  4.80it/s]

Processing tickers:  75%|███████▌  | 5211/6932 [18:40<06:06,  4.70it/s]

Processing tickers:  75%|███████▌  | 5212/6932 [18:40<06:03,  4.73it/s]

Processing tickers:  75%|███████▌  | 5213/6932 [18:41<06:05,  4.70it/s]

Processing tickers:  75%|███████▌  | 5214/6932 [18:41<05:59,  4.78it/s]

Processing tickers:  75%|███████▌  | 5215/6932 [18:41<05:58,  4.79it/s]

Processing tickers:  75%|███████▌  | 5216/6932 [18:41<05:57,  4.80it/s]

Processing tickers:  75%|███████▌  | 5217/6932 [18:41<06:01,  4.75it/s]

Processing tickers:  75%|███████▌  | 5218/6932 [18:42<05:55,  4.82it/s]

Processing tickers:  75%|███████▌  | 5219/6932 [18:42<05:55,  4.82it/s]

Processing tickers:  75%|███████▌  | 5220/6932 [18:42<05:57,  4.78it/s]

Processing tickers:  75%|███████▌  | 5221/6932 [18:42<05:55,  4.82it/s]

Processing tickers:  75%|███████▌  | 5222/6932 [18:43<05:55,  4.82it/s]

Processing tickers:  75%|███████▌  | 5223/6932 [18:43<06:03,  4.70it/s]

Processing tickers:  75%|███████▌  | 5224/6932 [18:43<06:00,  4.73it/s]

Processing tickers:  75%|███████▌  | 5225/6932 [18:43<06:00,  4.73it/s]

Processing tickers:  75%|███████▌  | 5226/6932 [18:43<05:57,  4.77it/s]

Processing tickers:  75%|███████▌  | 5227/6932 [18:44<05:56,  4.79it/s]

Processing tickers:  75%|███████▌  | 5228/6932 [18:44<05:55,  4.79it/s]

Processing tickers:  75%|███████▌  | 5229/6932 [18:44<06:03,  4.68it/s]

Processing tickers:  75%|███████▌  | 5230/6932 [18:44<06:00,  4.73it/s]

Processing tickers:  75%|███████▌  | 5231/6932 [18:44<05:57,  4.76it/s]

Processing tickers:  75%|███████▌  | 5232/6932 [18:45<05:59,  4.73it/s]

Processing tickers:  75%|███████▌  | 5233/6932 [18:45<05:53,  4.80it/s]

Processing tickers:  76%|███████▌  | 5234/6932 [18:45<06:01,  4.70it/s]

Processing tickers:  76%|███████▌  | 5235/6932 [18:45<06:04,  4.65it/s]

Processing tickers:  76%|███████▌  | 5236/6932 [18:46<06:03,  4.66it/s]

Processing tickers:  76%|███████▌  | 5237/6932 [18:46<06:00,  4.70it/s]

Processing tickers:  76%|███████▌  | 5238/6932 [18:46<06:07,  4.61it/s]

Processing tickers:  76%|███████▌  | 5239/6932 [18:46<06:02,  4.68it/s]

Processing tickers:  76%|███████▌  | 5240/6932 [18:46<05:59,  4.71it/s]

Processing tickers:  76%|███████▌  | 5241/6932 [18:47<05:59,  4.71it/s]

Processing tickers:  76%|███████▌  | 5242/6932 [18:47<06:01,  4.67it/s]

Processing tickers:  76%|███████▌  | 5243/6932 [18:47<05:58,  4.71it/s]

Processing tickers:  76%|███████▌  | 5244/6932 [18:47<05:57,  4.72it/s]

Processing tickers:  76%|███████▌  | 5245/6932 [18:47<05:59,  4.70it/s]

Processing tickers:  76%|███████▌  | 5246/6932 [18:48<05:59,  4.69it/s]

Processing tickers:  76%|███████▌  | 5247/6932 [18:48<05:56,  4.73it/s]

Processing tickers:  76%|███████▌  | 5248/6932 [18:48<05:54,  4.75it/s]

Processing tickers:  76%|███████▌  | 5249/6932 [18:48<05:53,  4.76it/s]

Processing tickers:  76%|███████▌  | 5250/6932 [18:48<06:02,  4.64it/s]

Processing tickers:  76%|███████▌  | 5251/6932 [18:49<05:57,  4.70it/s]

Processing tickers:  76%|███████▌  | 5252/6932 [18:49<05:58,  4.69it/s]

Processing tickers:  76%|███████▌  | 5253/6932 [18:49<05:59,  4.68it/s]

Processing tickers:  76%|███████▌  | 5254/6932 [18:49<05:47,  4.83it/s]

Processing tickers:  76%|███████▌  | 5255/6932 [18:50<05:55,  4.71it/s]

Processing tickers:  76%|███████▌  | 5256/6932 [18:50<05:53,  4.75it/s]

Processing tickers:  76%|███████▌  | 5257/6932 [18:50<05:51,  4.77it/s]

Processing tickers:  76%|███████▌  | 5258/6932 [18:50<05:50,  4.77it/s]

Processing tickers:  76%|███████▌  | 5259/6932 [18:50<05:49,  4.79it/s]

Processing tickers:  76%|███████▌  | 5260/6932 [18:51<05:48,  4.80it/s]

Processing tickers:  76%|███████▌  | 5261/6932 [18:51<05:52,  4.75it/s]

Processing tickers:  76%|███████▌  | 5262/6932 [18:51<05:46,  4.82it/s]

Processing tickers:  76%|███████▌  | 5263/6932 [18:51<05:54,  4.71it/s]

Processing tickers:  76%|███████▌  | 5264/6932 [18:51<05:44,  4.85it/s]

Processing tickers:  76%|███████▌  | 5265/6932 [18:52<05:45,  4.83it/s]

Processing tickers:  76%|███████▌  | 5266/6932 [18:52<05:52,  4.72it/s]

Processing tickers:  76%|███████▌  | 5267/6932 [18:52<05:53,  4.70it/s]

Processing tickers:  76%|███████▌  | 5268/6932 [18:52<05:51,  4.73it/s]

Processing tickers:  76%|███████▌  | 5269/6932 [18:52<05:45,  4.81it/s]

Processing tickers:  76%|███████▌  | 5270/6932 [18:53<05:45,  4.80it/s]

Processing tickers:  76%|███████▌  | 5271/6932 [18:53<05:46,  4.79it/s]

Processing tickers:  76%|███████▌  | 5272/6932 [18:53<05:44,  4.82it/s]

Processing tickers:  76%|███████▌  | 5273/6932 [18:53<05:45,  4.80it/s]

Processing tickers:  76%|███████▌  | 5274/6932 [18:54<05:48,  4.76it/s]

Processing tickers:  76%|███████▌  | 5275/6932 [18:54<05:43,  4.82it/s]

Processing tickers:  76%|███████▌  | 5276/6932 [18:54<05:44,  4.81it/s]

Processing tickers:  76%|███████▌  | 5277/6932 [18:54<05:51,  4.70it/s]

Processing tickers:  76%|███████▌  | 5278/6932 [18:54<05:49,  4.74it/s]

Processing tickers:  76%|███████▌  | 5279/6932 [18:55<05:48,  4.74it/s]

Processing tickers:  76%|███████▌  | 5280/6932 [18:55<05:45,  4.78it/s]

Processing tickers:  76%|███████▌  | 5281/6932 [18:55<05:44,  4.79it/s]

Processing tickers:  76%|███████▌  | 5282/6932 [18:55<05:49,  4.72it/s]

Processing tickers:  76%|███████▌  | 5283/6932 [18:55<05:41,  4.83it/s]

Processing tickers:  76%|███████▌  | 5284/6932 [18:56<05:42,  4.82it/s]

Processing tickers:  76%|███████▌  | 5285/6932 [18:56<05:42,  4.81it/s]

Processing tickers:  76%|███████▋  | 5286/6932 [18:56<05:50,  4.70it/s]

Processing tickers:  76%|███████▋  | 5287/6932 [18:56<05:47,  4.73it/s]

Processing tickers:  76%|███████▋  | 5288/6932 [18:56<05:46,  4.75it/s]

Processing tickers:  76%|███████▋  | 5289/6932 [18:57<05:50,  4.69it/s]

Processing tickers:  76%|███████▋  | 5290/6932 [18:57<05:49,  4.70it/s]

Processing tickers:  76%|███████▋  | 5291/6932 [18:57<05:51,  4.67it/s]

Processing tickers:  76%|███████▋  | 5292/6932 [18:57<05:48,  4.71it/s]

Processing tickers:  76%|███████▋  | 5293/6932 [18:58<05:40,  4.82it/s]

Processing tickers:  76%|███████▋  | 5294/6932 [18:58<05:47,  4.72it/s]

Processing tickers:  76%|███████▋  | 5295/6932 [18:58<05:44,  4.76it/s]

Processing tickers:  76%|███████▋  | 5296/6932 [18:58<05:42,  4.78it/s]

Processing tickers:  76%|███████▋  | 5297/6932 [18:58<05:41,  4.79it/s]

Processing tickers:  76%|███████▋  | 5298/6932 [18:59<05:40,  4.79it/s]

Processing tickers:  76%|███████▋  | 5299/6932 [18:59<05:40,  4.80it/s]

Processing tickers:  76%|███████▋  | 5300/6932 [18:59<05:40,  4.80it/s]

Processing tickers:  76%|███████▋  | 5301/6932 [18:59<05:39,  4.80it/s]

Processing tickers:  76%|███████▋  | 5302/6932 [18:59<05:39,  4.80it/s]

Processing tickers:  77%|███████▋  | 5303/6932 [19:00<05:39,  4.80it/s]

Processing tickers:  77%|███████▋  | 5304/6932 [19:00<05:40,  4.78it/s]

Processing tickers:  77%|███████▋  | 5305/6932 [19:00<05:38,  4.81it/s]

Processing tickers:  77%|███████▋  | 5306/6932 [19:00<05:43,  4.74it/s]

Processing tickers:  77%|███████▋  | 5307/6932 [19:00<05:44,  4.72it/s]

Processing tickers:  77%|███████▋  | 5308/6932 [19:01<05:52,  4.60it/s]

Processing tickers:  77%|███████▋  | 5309/6932 [19:01<05:45,  4.70it/s]

Processing tickers:  77%|███████▋  | 5310/6932 [19:01<05:43,  4.72it/s]

Processing tickers:  77%|███████▋  | 5311/6932 [19:01<05:42,  4.73it/s]

Processing tickers:  77%|███████▋  | 5312/6932 [19:02<05:43,  4.72it/s]

Processing tickers:  77%|███████▋  | 5313/6932 [19:02<05:37,  4.79it/s]

Processing tickers:  77%|███████▋  | 5314/6932 [19:02<05:37,  4.80it/s]

Processing tickers:  77%|███████▋  | 5315/6932 [19:02<05:36,  4.80it/s]

Processing tickers:  77%|███████▋  | 5316/6932 [19:02<05:36,  4.80it/s]

Processing tickers:  77%|███████▋  | 5317/6932 [19:03<05:36,  4.81it/s]

Processing tickers:  77%|███████▋  | 5318/6932 [19:03<05:39,  4.75it/s]

Processing tickers:  77%|███████▋  | 5319/6932 [19:03<05:35,  4.81it/s]

Processing tickers:  77%|███████▋  | 5320/6932 [19:03<05:34,  4.81it/s]

Processing tickers:  77%|███████▋  | 5321/6932 [19:03<05:34,  4.81it/s]

Processing tickers:  77%|███████▋  | 5322/6932 [19:04<05:36,  4.79it/s]

Processing tickers:  77%|███████▋  | 5323/6932 [19:04<05:33,  4.82it/s]

Processing tickers:  77%|███████▋  | 5324/6932 [19:04<05:34,  4.81it/s]

Processing tickers:  77%|███████▋  | 5325/6932 [19:04<05:41,  4.70it/s]

Processing tickers:  77%|███████▋  | 5326/6932 [19:04<05:42,  4.70it/s]

Processing tickers:  77%|███████▋  | 5327/6932 [19:05<05:37,  4.76it/s]

Processing tickers:  77%|███████▋  | 5328/6932 [19:05<05:36,  4.77it/s]

Processing tickers:  77%|███████▋  | 5329/6932 [19:05<05:35,  4.78it/s]

Processing tickers:  77%|███████▋  | 5330/6932 [19:05<05:42,  4.68it/s]

Processing tickers:  77%|███████▋  | 5331/6932 [19:05<05:32,  4.82it/s]

Processing tickers:  77%|███████▋  | 5332/6932 [19:06<05:33,  4.80it/s]

Processing tickers:  77%|███████▋  | 5333/6932 [19:06<05:38,  4.72it/s]

Processing tickers:  77%|███████▋  | 5334/6932 [19:06<05:30,  4.84it/s]

Processing tickers:  77%|███████▋  | 5335/6932 [19:06<05:30,  4.83it/s]

Processing tickers:  77%|███████▋  | 5336/6932 [19:07<05:36,  4.74it/s]

Processing tickers:  77%|███████▋  | 5337/6932 [19:07<05:34,  4.77it/s]

Processing tickers:  77%|███████▋  | 5338/6932 [19:07<05:39,  4.69it/s]

Processing tickers:  77%|███████▋  | 5339/6932 [19:07<05:44,  4.63it/s]

Processing tickers:  77%|███████▋  | 5340/6932 [19:07<05:41,  4.67it/s]

Processing tickers:  77%|███████▋  | 5341/6932 [19:08<05:37,  4.72it/s]

Processing tickers:  77%|███████▋  | 5342/6932 [19:08<05:35,  4.74it/s]

Processing tickers:  77%|███████▋  | 5343/6932 [19:08<05:33,  4.76it/s]

Processing tickers:  77%|███████▋  | 5344/6932 [19:08<05:32,  4.78it/s]

Processing tickers:  77%|███████▋  | 5345/6932 [19:08<05:31,  4.78it/s]

Processing tickers:  77%|███████▋  | 5346/6932 [19:09<05:31,  4.79it/s]

Processing tickers:  77%|███████▋  | 5347/6932 [19:09<05:30,  4.79it/s]

Processing tickers:  77%|███████▋  | 5348/6932 [19:09<05:30,  4.79it/s]

Processing tickers:  77%|███████▋  | 5349/6932 [19:09<05:29,  4.80it/s]

Processing tickers:  77%|███████▋  | 5350/6932 [19:09<05:32,  4.76it/s]

Processing tickers:  77%|███████▋  | 5351/6932 [19:10<05:29,  4.80it/s]

Processing tickers:  77%|███████▋  | 5352/6932 [19:10<05:28,  4.81it/s]

Processing tickers:  77%|███████▋  | 5353/6932 [19:10<05:35,  4.71it/s]

Processing tickers:  77%|███████▋  | 5354/6932 [19:10<05:25,  4.85it/s]

Processing tickers:  77%|███████▋  | 5355/6932 [19:11<05:33,  4.73it/s]

Processing tickers:  77%|███████▋  | 5356/6932 [19:11<05:39,  4.64it/s]

Processing tickers:  77%|███████▋  | 5357/6932 [19:11<05:37,  4.67it/s]

Processing tickers:  77%|███████▋  | 5358/6932 [19:11<05:31,  4.75it/s]

Processing tickers:  77%|███████▋  | 5359/6932 [19:11<05:30,  4.76it/s]

Processing tickers:  77%|███████▋  | 5360/6932 [19:12<05:29,  4.78it/s]

Processing tickers:  77%|███████▋  | 5361/6932 [19:12<05:28,  4.79it/s]

Processing tickers:  77%|███████▋  | 5362/6932 [19:12<05:27,  4.79it/s]

Processing tickers:  77%|███████▋  | 5363/6932 [19:12<05:23,  4.85it/s]

Processing tickers:  77%|███████▋  | 5364/6932 [19:12<05:29,  4.76it/s]

Processing tickers:  77%|███████▋  | 5365/6932 [19:13<05:29,  4.76it/s]

Processing tickers:  77%|███████▋  | 5366/6932 [19:13<05:21,  4.87it/s]

Processing tickers:  77%|███████▋  | 5367/6932 [19:13<05:22,  4.86it/s]

Processing tickers:  77%|███████▋  | 5368/6932 [19:13<05:29,  4.75it/s]

Processing tickers:  77%|███████▋  | 5369/6932 [19:13<05:27,  4.77it/s]

Processing tickers:  77%|███████▋  | 5370/6932 [19:14<05:26,  4.78it/s]

Processing tickers:  77%|███████▋  | 5371/6932 [19:14<05:26,  4.78it/s]

Processing tickers:  77%|███████▋  | 5372/6932 [19:14<05:26,  4.78it/s]

Processing tickers:  78%|███████▊  | 5373/6932 [19:14<05:23,  4.82it/s]

Processing tickers:  78%|███████▊  | 5374/6932 [19:14<05:23,  4.81it/s]

Processing tickers:  78%|███████▊  | 5375/6932 [19:15<05:22,  4.83it/s]

Processing tickers:  78%|███████▊  | 5376/6932 [19:15<05:24,  4.80it/s]

Processing tickers:  78%|███████▊  | 5377/6932 [19:15<05:22,  4.82it/s]

Processing tickers:  78%|███████▊  | 5378/6932 [19:15<05:30,  4.71it/s]

Processing tickers:  78%|███████▊  | 5379/6932 [19:16<05:19,  4.85it/s]

Processing tickers:  78%|███████▊  | 5380/6932 [19:16<05:28,  4.73it/s]

Processing tickers:  78%|███████▊  | 5381/6932 [19:16<05:26,  4.75it/s]

Processing tickers:  78%|███████▊  | 5382/6932 [19:16<05:25,  4.76it/s]

Processing tickers:  78%|███████▊  | 5383/6932 [19:16<05:24,  4.78it/s]

Processing tickers:  78%|███████▊  | 5384/6932 [19:17<05:23,  4.79it/s]

Processing tickers:  78%|███████▊  | 5385/6932 [19:17<05:22,  4.79it/s]

Processing tickers:  78%|███████▊  | 5386/6932 [19:17<05:22,  4.80it/s]

Processing tickers:  78%|███████▊  | 5387/6932 [19:17<05:26,  4.74it/s]

Processing tickers:  78%|███████▊  | 5388/6932 [19:17<05:26,  4.73it/s]

Processing tickers:  78%|███████▊  | 5389/6932 [19:18<05:19,  4.83it/s]

Processing tickers:  78%|███████▊  | 5390/6932 [19:18<05:19,  4.83it/s]

Processing tickers:  78%|███████▊  | 5391/6932 [19:18<05:20,  4.82it/s]

Processing tickers:  78%|███████▊  | 5392/6932 [19:18<05:27,  4.70it/s]

Processing tickers:  78%|███████▊  | 5393/6932 [19:18<05:24,  4.74it/s]

Processing tickers:  78%|███████▊  | 5394/6932 [19:19<05:24,  4.73it/s]

Processing tickers:  78%|███████▊  | 5395/6932 [19:19<05:21,  4.78it/s]

Processing tickers:  78%|███████▊  | 5396/6932 [19:19<05:21,  4.78it/s]

Processing tickers:  78%|███████▊  | 5397/6932 [19:19<05:19,  4.80it/s]

Processing tickers:  78%|███████▊  | 5398/6932 [19:20<05:24,  4.73it/s]

Processing tickers:  78%|███████▊  | 5399/6932 [19:20<05:26,  4.69it/s]

Processing tickers:  78%|███████▊  | 5400/6932 [19:20<05:22,  4.74it/s]

Processing tickers:  78%|███████▊  | 5401/6932 [19:20<05:21,  4.76it/s]

Processing tickers:  78%|███████▊  | 5402/6932 [19:20<05:27,  4.67it/s]

Processing tickers:  78%|███████▊  | 5403/6932 [19:21<05:24,  4.71it/s]

Processing tickers:  78%|███████▊  | 5404/6932 [19:21<05:22,  4.73it/s]

Processing tickers:  78%|███████▊  | 5405/6932 [19:21<05:21,  4.75it/s]

Processing tickers:  78%|███████▊  | 5406/6932 [19:21<05:19,  4.77it/s]

Processing tickers:  78%|███████▊  | 5407/6932 [19:21<05:18,  4.79it/s]

Processing tickers:  78%|███████▊  | 5408/6932 [19:22<05:18,  4.78it/s]

Processing tickers:  78%|███████▊  | 5409/6932 [19:22<05:17,  4.80it/s]

Processing tickers:  78%|███████▊  | 5410/6932 [19:22<05:17,  4.80it/s]

Processing tickers:  78%|███████▊  | 5411/6932 [19:22<05:18,  4.77it/s]

Processing tickers:  78%|███████▊  | 5412/6932 [19:22<05:16,  4.80it/s]

Processing tickers:  78%|███████▊  | 5413/6932 [19:23<05:23,  4.69it/s]

Processing tickers:  78%|███████▊  | 5414/6932 [19:23<05:21,  4.73it/s]

Processing tickers:  78%|███████▊  | 5415/6932 [19:23<05:22,  4.71it/s]

Processing tickers:  78%|███████▊  | 5416/6932 [19:23<05:17,  4.78it/s]

Processing tickers:  78%|███████▊  | 5417/6932 [19:24<05:21,  4.71it/s]

Processing tickers:  78%|███████▊  | 5418/6932 [19:24<05:14,  4.81it/s]

Processing tickers:  78%|███████▊  | 5419/6932 [19:24<05:22,  4.69it/s]

Processing tickers:  78%|███████▊  | 5420/6932 [19:24<05:18,  4.74it/s]

Processing tickers:  78%|███████▊  | 5421/6932 [19:24<05:17,  4.76it/s]

Processing tickers:  78%|███████▊  | 5422/6932 [19:25<05:16,  4.77it/s]

Processing tickers:  78%|███████▊  | 5423/6932 [19:25<05:21,  4.69it/s]

Processing tickers:  78%|███████▊  | 5424/6932 [19:25<05:13,  4.82it/s]

Processing tickers:  78%|███████▊  | 5425/6932 [19:25<05:20,  4.70it/s]

Processing tickers:  78%|███████▊  | 5426/6932 [19:25<05:17,  4.74it/s]

Processing tickers:  78%|███████▊  | 5427/6932 [19:26<05:16,  4.76it/s]

Processing tickers:  78%|███████▊  | 5428/6932 [19:26<05:29,  4.56it/s]

Processing tickers:  78%|███████▊  | 5429/6932 [19:26<05:24,  4.63it/s]

Processing tickers:  78%|███████▊  | 5430/6932 [19:26<05:27,  4.59it/s]

Processing tickers:  78%|███████▊  | 5431/6932 [19:27<05:22,  4.65it/s]

Processing tickers:  78%|███████▊  | 5432/6932 [19:27<05:19,  4.70it/s]

Processing tickers:  78%|███████▊  | 5433/6932 [19:27<05:16,  4.73it/s]

Processing tickers:  78%|███████▊  | 5434/6932 [19:27<05:21,  4.65it/s]

Processing tickers:  78%|███████▊  | 5435/6932 [19:27<05:24,  4.61it/s]

Processing tickers:  78%|███████▊  | 5436/6932 [19:28<05:26,  4.58it/s]

Processing tickers:  78%|███████▊  | 5437/6932 [19:28<05:28,  4.55it/s]

Processing tickers:  78%|███████▊  | 5438/6932 [19:28<05:27,  4.57it/s]

Processing tickers:  78%|███████▊  | 5439/6932 [19:28<05:18,  4.69it/s]

Processing tickers:  78%|███████▊  | 5440/6932 [19:28<05:15,  4.73it/s]

Processing tickers:  78%|███████▊  | 5441/6932 [19:29<05:14,  4.75it/s]

Processing tickers:  79%|███████▊  | 5442/6932 [19:29<05:13,  4.76it/s]

Processing tickers:  79%|███████▊  | 5443/6932 [19:29<05:12,  4.77it/s]

Processing tickers:  79%|███████▊  | 5444/6932 [19:29<05:16,  4.70it/s]

Processing tickers:  79%|███████▊  | 5445/6932 [19:29<05:08,  4.82it/s]

Processing tickers:  79%|███████▊  | 5446/6932 [19:30<05:08,  4.82it/s]

Processing tickers:  79%|███████▊  | 5447/6932 [19:30<05:08,  4.81it/s]

Processing tickers:  79%|███████▊  | 5448/6932 [19:30<05:38,  4.39it/s]

Processing tickers:  79%|███████▊  | 5449/6932 [19:30<05:29,  4.50it/s]

Processing tickers:  79%|███████▊  | 5450/6932 [19:31<05:21,  4.60it/s]

Processing tickers:  79%|███████▊  | 5451/6932 [19:31<05:23,  4.58it/s]

Processing tickers:  79%|███████▊  | 5452/6932 [19:31<05:21,  4.60it/s]

Processing tickers:  79%|███████▊  | 5453/6932 [19:31<05:24,  4.56it/s]

Processing tickers:  79%|███████▊  | 5454/6932 [19:31<05:17,  4.65it/s]

Processing tickers:  79%|███████▊  | 5455/6932 [19:32<05:14,  4.70it/s]

Processing tickers:  79%|███████▊  | 5456/6932 [19:32<05:12,  4.73it/s]

Processing tickers:  79%|███████▊  | 5457/6932 [19:32<05:17,  4.65it/s]

Processing tickers:  79%|███████▊  | 5458/6932 [19:32<05:14,  4.68it/s]

Processing tickers:  79%|███████▉  | 5459/6932 [19:33<05:10,  4.74it/s]

Processing tickers:  79%|███████▉  | 5460/6932 [19:33<05:16,  4.65it/s]

Processing tickers:  79%|███████▉  | 5461/6932 [19:33<05:12,  4.70it/s]

Processing tickers:  79%|███████▉  | 5462/6932 [19:33<05:10,  4.73it/s]

Processing tickers:  79%|███████▉  | 5463/6932 [19:33<05:12,  4.71it/s]

Processing tickers:  79%|███████▉  | 5464/6932 [19:34<05:06,  4.78it/s]

Processing tickers:  79%|███████▉  | 5465/6932 [19:34<05:06,  4.79it/s]

Processing tickers:  79%|███████▉  | 5466/6932 [19:34<05:13,  4.68it/s]

Processing tickers:  79%|███████▉  | 5467/6932 [19:34<05:10,  4.72it/s]

Processing tickers:  79%|███████▉  | 5468/6932 [19:34<05:08,  4.74it/s]

Processing tickers:  79%|███████▉  | 5469/6932 [19:35<05:07,  4.77it/s]

Processing tickers:  79%|███████▉  | 5470/6932 [19:35<05:06,  4.77it/s]

Processing tickers:  79%|███████▉  | 5471/6932 [19:35<05:11,  4.69it/s]

Processing tickers:  79%|███████▉  | 5472/6932 [19:35<05:09,  4.71it/s]

Processing tickers:  79%|███████▉  | 5473/6932 [19:35<05:00,  4.85it/s]

Processing tickers:  79%|███████▉  | 5474/6932 [19:36<05:09,  4.70it/s]

Processing tickers:  79%|███████▉  | 5475/6932 [19:36<05:05,  4.77it/s]

Processing tickers:  79%|███████▉  | 5476/6932 [19:36<05:04,  4.78it/s]

Processing tickers:  79%|███████▉  | 5477/6932 [19:36<05:07,  4.73it/s]

Processing tickers:  79%|███████▉  | 5478/6932 [19:37<05:07,  4.72it/s]

Processing tickers:  79%|███████▉  | 5479/6932 [19:37<05:12,  4.65it/s]

Processing tickers:  79%|███████▉  | 5480/6932 [19:37<05:07,  4.72it/s]

Processing tickers:  79%|███████▉  | 5481/6932 [19:37<05:05,  4.74it/s]

Processing tickers:  79%|███████▉  | 5482/6932 [19:37<05:04,  4.77it/s]

Processing tickers:  79%|███████▉  | 5483/6932 [19:38<05:09,  4.68it/s]

Processing tickers:  79%|███████▉  | 5484/6932 [19:38<05:15,  4.58it/s]

Processing tickers:  79%|███████▉  | 5485/6932 [19:38<05:10,  4.66it/s]

Processing tickers:  79%|███████▉  | 5486/6932 [19:38<05:13,  4.62it/s]

Processing tickers:  79%|███████▉  | 5487/6932 [19:38<05:08,  4.68it/s]

Processing tickers:  79%|███████▉  | 5488/6932 [19:39<05:05,  4.72it/s]

Processing tickers:  79%|███████▉  | 5489/6932 [19:39<05:09,  4.66it/s]

Processing tickers:  79%|███████▉  | 5490/6932 [19:39<05:01,  4.79it/s]

Processing tickers:  79%|███████▉  | 5491/6932 [19:39<05:06,  4.70it/s]

Processing tickers:  79%|███████▉  | 5492/6932 [19:39<04:57,  4.83it/s]

Processing tickers:  79%|███████▉  | 5493/6932 [19:40<05:05,  4.72it/s]

Processing tickers:  79%|███████▉  | 5494/6932 [19:40<05:03,  4.74it/s]

Processing tickers:  79%|███████▉  | 5495/6932 [19:40<05:09,  4.64it/s]

Processing tickers:  79%|███████▉  | 5496/6932 [19:40<05:05,  4.71it/s]

Processing tickers:  79%|███████▉  | 5497/6932 [19:41<05:03,  4.73it/s]

Processing tickers:  79%|███████▉  | 5498/6932 [19:41<05:02,  4.74it/s]

Processing tickers:  79%|███████▉  | 5499/6932 [19:41<05:01,  4.76it/s]

Processing tickers:  79%|███████▉  | 5500/6932 [19:41<04:59,  4.79it/s]

Processing tickers:  79%|███████▉  | 5501/6932 [19:41<04:59,  4.77it/s]

Processing tickers:  79%|███████▉  | 5502/6932 [19:42<04:58,  4.79it/s]

Processing tickers:  79%|███████▉  | 5503/6932 [19:42<04:56,  4.81it/s]

Processing tickers:  79%|███████▉  | 5504/6932 [19:42<04:57,  4.81it/s]

Processing tickers:  79%|███████▉  | 5505/6932 [19:42<04:56,  4.81it/s]

Processing tickers:  79%|███████▉  | 5506/6932 [19:42<05:00,  4.74it/s]

Processing tickers:  79%|███████▉  | 5507/6932 [19:43<04:53,  4.85it/s]

Processing tickers:  79%|███████▉  | 5508/6932 [19:43<04:54,  4.84it/s]

Processing tickers:  79%|███████▉  | 5509/6932 [19:43<04:55,  4.82it/s]

Processing tickers:  79%|███████▉  | 5510/6932 [19:43<04:55,  4.81it/s]

Processing tickers:  80%|███████▉  | 5511/6932 [19:43<04:55,  4.81it/s]

Processing tickers:  80%|███████▉  | 5512/6932 [19:44<04:56,  4.80it/s]

Processing tickers:  80%|███████▉  | 5513/6932 [19:44<04:55,  4.81it/s]

Processing tickers:  80%|███████▉  | 5514/6932 [19:44<04:55,  4.81it/s]

Processing tickers:  80%|███████▉  | 5515/6932 [19:44<04:55,  4.80it/s]

Processing tickers:  80%|███████▉  | 5516/6932 [19:45<04:54,  4.81it/s]

Processing tickers:  80%|███████▉  | 5517/6932 [19:45<04:53,  4.82it/s]

Processing tickers:  80%|███████▉  | 5518/6932 [19:45<04:59,  4.72it/s]

Processing tickers:  80%|███████▉  | 5519/6932 [19:45<05:06,  4.60it/s]

Processing tickers:  80%|███████▉  | 5520/6932 [19:45<05:01,  4.68it/s]

Processing tickers:  80%|███████▉  | 5521/6932 [19:46<05:04,  4.64it/s]

Processing tickers:  80%|███████▉  | 5522/6932 [19:46<05:00,  4.69it/s]

Processing tickers:  80%|███████▉  | 5523/6932 [19:46<04:57,  4.73it/s]

Processing tickers:  80%|███████▉  | 5524/6932 [19:46<04:58,  4.72it/s]

Processing tickers:  80%|███████▉  | 5525/6932 [19:46<04:55,  4.76it/s]

Processing tickers:  80%|███████▉  | 5526/6932 [19:47<04:53,  4.79it/s]

Processing tickers:  80%|███████▉  | 5527/6932 [19:47<04:52,  4.80it/s]

Processing tickers:  80%|███████▉  | 5528/6932 [19:47<04:53,  4.79it/s]

Processing tickers:  80%|███████▉  | 5529/6932 [19:47<05:01,  4.65it/s]

Processing tickers:  80%|███████▉  | 5530/6932 [19:47<04:55,  4.75it/s]

Processing tickers:  80%|███████▉  | 5531/6932 [19:48<04:53,  4.77it/s]

Processing tickers:  80%|███████▉  | 5532/6932 [19:48<04:46,  4.88it/s]

Processing tickers:  80%|███████▉  | 5533/6932 [19:48<04:54,  4.75it/s]

Processing tickers:  80%|███████▉  | 5534/6932 [19:48<04:53,  4.77it/s]

Processing tickers:  80%|███████▉  | 5535/6932 [19:49<04:52,  4.78it/s]

Processing tickers:  80%|███████▉  | 5536/6932 [19:49<04:58,  4.68it/s]

Processing tickers:  80%|███████▉  | 5537/6932 [19:49<04:56,  4.70it/s]

Processing tickers:  80%|███████▉  | 5538/6932 [19:49<04:54,  4.73it/s]

Processing tickers:  80%|███████▉  | 5539/6932 [19:49<04:51,  4.77it/s]

Processing tickers:  80%|███████▉  | 5540/6932 [19:50<04:54,  4.72it/s]

Processing tickers:  80%|███████▉  | 5541/6932 [19:50<04:49,  4.81it/s]

Processing tickers:  80%|███████▉  | 5542/6932 [19:50<04:53,  4.74it/s]

Processing tickers:  80%|███████▉  | 5543/6932 [19:50<04:47,  4.83it/s]

Processing tickers:  80%|███████▉  | 5544/6932 [19:50<04:56,  4.68it/s]

Processing tickers:  80%|███████▉  | 5545/6932 [19:51<05:00,  4.62it/s]

Processing tickers:  80%|████████  | 5546/6932 [19:51<04:57,  4.66it/s]

Processing tickers:  80%|████████  | 5547/6932 [19:51<04:52,  4.73it/s]

Processing tickers:  80%|████████  | 5548/6932 [19:51<04:51,  4.75it/s]

Processing tickers:  80%|████████  | 5549/6932 [19:51<04:52,  4.73it/s]

Processing tickers:  80%|████████  | 5550/6932 [19:52<04:58,  4.63it/s]

Processing tickers:  80%|████████  | 5551/6932 [19:52<04:59,  4.61it/s]

Processing tickers:  80%|████████  | 5552/6932 [19:52<04:54,  4.69it/s]

Processing tickers:  80%|████████  | 5553/6932 [19:52<04:59,  4.61it/s]

Processing tickers:  80%|████████  | 5554/6932 [19:53<04:54,  4.67it/s]

Processing tickers:  80%|████████  | 5555/6932 [19:53<04:59,  4.60it/s]

Processing tickers:  80%|████████  | 5556/6932 [19:53<04:54,  4.67it/s]

Processing tickers:  80%|████████  | 5557/6932 [19:53<04:52,  4.70it/s]

Processing tickers:  80%|████████  | 5558/6932 [19:53<04:56,  4.63it/s]

Processing tickers:  80%|████████  | 5559/6932 [19:54<04:54,  4.66it/s]

Processing tickers:  80%|████████  | 5560/6932 [19:54<04:50,  4.72it/s]

Processing tickers:  80%|████████  | 5561/6932 [19:54<04:48,  4.75it/s]

Processing tickers:  80%|████████  | 5562/6932 [19:54<04:53,  4.66it/s]

Processing tickers:  80%|████████  | 5563/6932 [19:55<04:52,  4.68it/s]

Processing tickers:  80%|████████  | 5564/6932 [19:55<04:54,  4.64it/s]

Processing tickers:  80%|████████  | 5565/6932 [19:55<04:51,  4.68it/s]

Processing tickers:  80%|████████  | 5566/6932 [19:55<04:49,  4.72it/s]

Processing tickers:  80%|████████  | 5567/6932 [19:55<04:53,  4.65it/s]

Processing tickers:  80%|████████  | 5568/6932 [19:56<04:50,  4.70it/s]

Processing tickers:  80%|████████  | 5569/6932 [19:56<04:47,  4.73it/s]

Processing tickers:  80%|████████  | 5570/6932 [19:56<04:46,  4.75it/s]

Processing tickers:  80%|████████  | 5571/6932 [19:56<04:45,  4.77it/s]

Processing tickers:  80%|████████  | 5572/6932 [19:56<04:44,  4.78it/s]

Processing tickers:  80%|████████  | 5573/6932 [19:57<04:50,  4.68it/s]

Processing tickers:  80%|████████  | 5574/6932 [19:57<04:48,  4.70it/s]

Processing tickers:  80%|████████  | 5575/6932 [19:57<04:44,  4.76it/s]

Processing tickers:  80%|████████  | 5576/6932 [19:57<04:49,  4.68it/s]

Processing tickers:  80%|████████  | 5577/6932 [19:57<04:46,  4.73it/s]

Processing tickers:  80%|████████  | 5578/6932 [19:58<04:44,  4.75it/s]

Processing tickers:  80%|████████  | 5579/6932 [19:58<04:43,  4.77it/s]

Processing tickers:  80%|████████  | 5580/6932 [19:58<04:42,  4.78it/s]

Processing tickers:  81%|████████  | 5581/6932 [19:58<04:41,  4.79it/s]

Processing tickers:  81%|████████  | 5582/6932 [19:59<04:44,  4.75it/s]

Processing tickers:  81%|████████  | 5583/6932 [19:59<04:46,  4.71it/s]

Processing tickers:  81%|████████  | 5584/6932 [19:59<04:38,  4.84it/s]

Processing tickers:  81%|████████  | 5585/6932 [19:59<04:44,  4.74it/s]

Processing tickers:  81%|████████  | 5586/6932 [19:59<04:36,  4.87it/s]

Processing tickers:  81%|████████  | 5587/6932 [20:00<04:43,  4.74it/s]

Processing tickers:  81%|████████  | 5588/6932 [20:00<04:42,  4.76it/s]

Processing tickers:  81%|████████  | 5589/6932 [20:00<04:41,  4.78it/s]

Processing tickers:  81%|████████  | 5590/6932 [20:00<04:49,  4.64it/s]

Processing tickers:  81%|████████  | 5591/6932 [20:00<04:43,  4.73it/s]

Processing tickers:  81%|████████  | 5592/6932 [20:01<04:56,  4.51it/s]

Processing tickers:  81%|████████  | 5593/6932 [20:01<04:52,  4.58it/s]

Processing tickers:  81%|████████  | 5594/6932 [20:01<04:45,  4.68it/s]

Processing tickers:  81%|████████  | 5595/6932 [20:01<04:42,  4.73it/s]

Processing tickers:  81%|████████  | 5596/6932 [20:01<04:40,  4.76it/s]

Processing tickers:  81%|████████  | 5597/6932 [20:02<04:40,  4.76it/s]

Processing tickers:  81%|████████  | 5598/6932 [20:02<04:42,  4.72it/s]

Processing tickers:  81%|████████  | 5599/6932 [20:02<04:37,  4.81it/s]

Processing tickers:  81%|████████  | 5600/6932 [20:02<04:43,  4.70it/s]

Processing tickers:  81%|████████  | 5601/6932 [20:03<04:41,  4.73it/s]

Processing tickers:  81%|████████  | 5602/6932 [20:03<04:39,  4.76it/s]

Processing tickers:  81%|████████  | 5603/6932 [20:03<04:38,  4.77it/s]

Processing tickers:  81%|████████  | 5604/6932 [20:03<04:43,  4.68it/s]

Processing tickers:  81%|████████  | 5605/6932 [20:03<04:44,  4.67it/s]

Processing tickers:  81%|████████  | 5606/6932 [20:04<04:43,  4.68it/s]

Processing tickers:  81%|████████  | 5607/6932 [20:04<04:41,  4.70it/s]

Processing tickers:  81%|████████  | 5608/6932 [20:04<04:46,  4.63it/s]

Processing tickers:  81%|████████  | 5609/6932 [20:04<04:37,  4.77it/s]

Processing tickers:  81%|████████  | 5610/6932 [20:04<04:36,  4.79it/s]

Processing tickers:  81%|████████  | 5611/6932 [20:05<04:35,  4.80it/s]

Processing tickers:  81%|████████  | 5612/6932 [20:05<04:41,  4.69it/s]

Processing tickers:  81%|████████  | 5613/6932 [20:05<04:39,  4.72it/s]

Processing tickers:  81%|████████  | 5614/6932 [20:05<04:31,  4.86it/s]

Processing tickers:  81%|████████  | 5615/6932 [20:05<04:38,  4.73it/s]

Processing tickers:  81%|████████  | 5616/6932 [20:06<04:38,  4.73it/s]

Processing tickers:  81%|████████  | 5617/6932 [20:06<04:41,  4.68it/s]

Processing tickers:  81%|████████  | 5618/6932 [20:06<04:38,  4.71it/s]

Processing tickers:  81%|████████  | 5619/6932 [20:06<04:36,  4.74it/s]

Processing tickers:  81%|████████  | 5620/6932 [20:07<04:35,  4.76it/s]

Processing tickers:  81%|████████  | 5621/6932 [20:07<04:41,  4.66it/s]

Processing tickers:  81%|████████  | 5622/6932 [20:07<04:37,  4.73it/s]

Processing tickers:  81%|████████  | 5623/6932 [20:07<04:41,  4.66it/s]

Processing tickers:  81%|████████  | 5624/6932 [20:07<04:44,  4.61it/s]

Processing tickers:  81%|████████  | 5625/6932 [20:08<04:40,  4.67it/s]

Processing tickers:  81%|████████  | 5626/6932 [20:08<04:37,  4.71it/s]

Processing tickers:  81%|████████  | 5627/6932 [20:08<04:35,  4.74it/s]

Processing tickers:  81%|████████  | 5628/6932 [20:08<04:34,  4.76it/s]

Processing tickers:  81%|████████  | 5629/6932 [20:08<04:37,  4.70it/s]

Processing tickers:  81%|████████  | 5630/6932 [20:09<04:32,  4.78it/s]

Processing tickers:  81%|████████  | 5631/6932 [20:09<04:30,  4.80it/s]

Processing tickers:  81%|████████  | 5632/6932 [20:09<04:36,  4.70it/s]

Processing tickers:  81%|████████▏ | 5633/6932 [20:09<04:40,  4.62it/s]

Processing tickers:  81%|████████▏ | 5634/6932 [20:10<04:38,  4.66it/s]

Processing tickers:  81%|████████▏ | 5635/6932 [20:10<04:39,  4.63it/s]

Processing tickers:  81%|████████▏ | 5636/6932 [20:10<04:37,  4.67it/s]

Processing tickers:  81%|████████▏ | 5637/6932 [20:10<04:37,  4.67it/s]

Processing tickers:  81%|████████▏ | 5638/6932 [20:10<04:35,  4.70it/s]

Processing tickers:  81%|████████▏ | 5639/6932 [20:11<04:30,  4.77it/s]

Processing tickers:  81%|████████▏ | 5640/6932 [20:11<04:29,  4.79it/s]

Processing tickers:  81%|████████▏ | 5641/6932 [20:11<04:29,  4.79it/s]

Processing tickers:  81%|████████▏ | 5642/6932 [20:11<04:36,  4.66it/s]

Processing tickers:  81%|████████▏ | 5643/6932 [20:11<04:26,  4.84it/s]

Processing tickers:  81%|████████▏ | 5644/6932 [20:12<04:33,  4.72it/s]

Processing tickers:  81%|████████▏ | 5645/6932 [20:12<04:25,  4.85it/s]

Processing tickers:  81%|████████▏ | 5646/6932 [20:12<04:25,  4.84it/s]

Processing tickers:  81%|████████▏ | 5647/6932 [20:12<04:25,  4.83it/s]

Processing tickers:  81%|████████▏ | 5648/6932 [20:12<04:32,  4.71it/s]

Processing tickers:  81%|████████▏ | 5649/6932 [20:13<04:30,  4.74it/s]

Processing tickers:  82%|████████▏ | 5650/6932 [20:13<04:35,  4.66it/s]

Processing tickers:  82%|████████▏ | 5651/6932 [20:13<04:26,  4.81it/s]

Processing tickers:  82%|████████▏ | 5652/6932 [20:13<04:32,  4.70it/s]

Processing tickers:  82%|████████▏ | 5653/6932 [20:14<04:24,  4.84it/s]

Processing tickers:  82%|████████▏ | 5654/6932 [20:14<04:31,  4.71it/s]

Processing tickers:  82%|████████▏ | 5655/6932 [20:14<04:29,  4.74it/s]

Processing tickers:  82%|████████▏ | 5656/6932 [20:14<04:27,  4.77it/s]

Processing tickers:  82%|████████▏ | 5657/6932 [20:14<04:35,  4.63it/s]

Processing tickers:  82%|████████▏ | 5658/6932 [20:15<04:36,  4.62it/s]

Processing tickers:  82%|████████▏ | 5659/6932 [20:15<04:35,  4.61it/s]

Processing tickers:  82%|████████▏ | 5660/6932 [20:15<04:34,  4.63it/s]

Processing tickers:  82%|████████▏ | 5661/6932 [20:15<04:31,  4.69it/s]

Processing tickers:  82%|████████▏ | 5662/6932 [20:15<04:29,  4.71it/s]

Processing tickers:  82%|████████▏ | 5663/6932 [20:16<04:33,  4.64it/s]

Processing tickers:  82%|████████▏ | 5664/6932 [20:16<04:35,  4.60it/s]

Processing tickers:  82%|████████▏ | 5665/6932 [20:16<04:33,  4.63it/s]

Processing tickers:  82%|████████▏ | 5666/6932 [20:16<04:29,  4.70it/s]

Processing tickers:  82%|████████▏ | 5667/6932 [20:17<04:34,  4.61it/s]

Processing tickers:  82%|████████▏ | 5668/6932 [20:17<04:30,  4.68it/s]

Processing tickers:  82%|████████▏ | 5669/6932 [20:17<04:29,  4.68it/s]

Processing tickers:  82%|████████▏ | 5670/6932 [20:17<04:25,  4.76it/s]

Processing tickers:  82%|████████▏ | 5671/6932 [20:17<04:24,  4.77it/s]

Processing tickers:  82%|████████▏ | 5672/6932 [20:18<04:23,  4.78it/s]

Processing tickers:  82%|████████▏ | 5673/6932 [20:18<04:22,  4.79it/s]

Processing tickers:  82%|████████▏ | 5674/6932 [20:18<04:25,  4.74it/s]

Processing tickers:  82%|████████▏ | 5675/6932 [20:18<04:21,  4.82it/s]

Processing tickers:  82%|████████▏ | 5676/6932 [20:18<04:21,  4.81it/s]

Processing tickers:  82%|████████▏ | 5677/6932 [20:19<04:21,  4.81it/s]

Processing tickers:  82%|████████▏ | 5678/6932 [20:19<04:26,  4.71it/s]

Processing tickers:  82%|████████▏ | 5679/6932 [20:19<04:24,  4.74it/s]

Processing tickers:  82%|████████▏ | 5680/6932 [20:19<04:22,  4.76it/s]

Processing tickers:  82%|████████▏ | 5681/6932 [20:19<04:22,  4.77it/s]

Processing tickers:  82%|████████▏ | 5682/6932 [20:20<04:21,  4.78it/s]

Processing tickers:  82%|████████▏ | 5683/6932 [20:20<04:20,  4.80it/s]

Processing tickers:  82%|████████▏ | 5684/6932 [20:20<04:20,  4.79it/s]

Processing tickers:  82%|████████▏ | 5685/6932 [20:20<04:20,  4.78it/s]

Processing tickers:  82%|████████▏ | 5686/6932 [20:21<04:19,  4.81it/s]

Processing tickers:  82%|████████▏ | 5687/6932 [20:21<04:18,  4.81it/s]

Processing tickers:  82%|████████▏ | 5688/6932 [20:21<04:22,  4.74it/s]

Processing tickers:  82%|████████▏ | 5689/6932 [20:21<04:17,  4.83it/s]

Processing tickers:  82%|████████▏ | 5690/6932 [20:21<04:23,  4.71it/s]

Processing tickers:  82%|████████▏ | 5691/6932 [20:22<04:21,  4.74it/s]

Processing tickers:  82%|████████▏ | 5692/6932 [20:22<04:20,  4.76it/s]

Processing tickers:  82%|████████▏ | 5693/6932 [20:22<04:19,  4.77it/s]

Processing tickers:  82%|████████▏ | 5694/6932 [20:22<04:20,  4.75it/s]

Processing tickers:  82%|████████▏ | 5695/6932 [20:22<04:17,  4.80it/s]

Processing tickers:  82%|████████▏ | 5696/6932 [20:23<04:23,  4.69it/s]

Processing tickers:  82%|████████▏ | 5697/6932 [20:23<04:22,  4.70it/s]

Processing tickers:  82%|████████▏ | 5698/6932 [20:23<04:20,  4.73it/s]

Processing tickers:  82%|████████▏ | 5699/6932 [20:23<04:17,  4.79it/s]

Processing tickers:  82%|████████▏ | 5700/6932 [20:23<04:16,  4.80it/s]

Processing tickers:  82%|████████▏ | 5701/6932 [20:24<04:16,  4.81it/s]

Processing tickers:  82%|████████▏ | 5702/6932 [20:24<04:10,  4.92it/s]

Processing tickers:  82%|████████▏ | 5703/6932 [20:24<04:16,  4.78it/s]

Processing tickers:  82%|████████▏ | 5704/6932 [20:24<04:16,  4.78it/s]

Processing tickers:  82%|████████▏ | 5705/6932 [20:25<04:18,  4.75it/s]

Processing tickers:  82%|████████▏ | 5706/6932 [20:25<04:15,  4.80it/s]

Processing tickers:  82%|████████▏ | 5707/6932 [20:25<04:15,  4.80it/s]

Processing tickers:  82%|████████▏ | 5708/6932 [20:25<04:14,  4.81it/s]

Processing tickers:  82%|████████▏ | 5709/6932 [20:25<04:16,  4.78it/s]

Processing tickers:  82%|████████▏ | 5710/6932 [20:26<04:19,  4.71it/s]

Processing tickers:  82%|████████▏ | 5711/6932 [20:26<04:17,  4.74it/s]

Processing tickers:  82%|████████▏ | 5712/6932 [20:26<04:17,  4.74it/s]

Processing tickers:  82%|████████▏ | 5713/6932 [20:26<04:15,  4.77it/s]

Processing tickers:  82%|████████▏ | 5714/6932 [20:26<04:13,  4.81it/s]

Processing tickers:  82%|████████▏ | 5715/6932 [20:27<04:13,  4.81it/s]

Processing tickers:  82%|████████▏ | 5716/6932 [20:27<04:12,  4.81it/s]

Processing tickers:  82%|████████▏ | 5717/6932 [20:27<04:12,  4.81it/s]

Processing tickers:  82%|████████▏ | 5718/6932 [20:27<04:12,  4.81it/s]

Processing tickers:  83%|████████▎ | 5719/6932 [20:27<04:12,  4.81it/s]

Processing tickers:  83%|████████▎ | 5720/6932 [20:28<04:11,  4.82it/s]

Processing tickers:  83%|████████▎ | 5721/6932 [20:28<04:16,  4.72it/s]

Processing tickers:  83%|████████▎ | 5722/6932 [20:28<04:14,  4.76it/s]

Processing tickers:  83%|████████▎ | 5723/6932 [20:28<04:18,  4.67it/s]

Processing tickers:  83%|████████▎ | 5724/6932 [20:28<04:18,  4.67it/s]

Processing tickers:  83%|████████▎ | 5725/6932 [20:29<04:14,  4.75it/s]

Processing tickers:  83%|████████▎ | 5726/6932 [20:29<04:17,  4.68it/s]

Processing tickers:  83%|████████▎ | 5727/6932 [20:29<04:10,  4.81it/s]

Processing tickers:  83%|████████▎ | 5728/6932 [20:29<04:10,  4.81it/s]

Processing tickers:  83%|████████▎ | 5729/6932 [20:30<04:10,  4.81it/s]

Processing tickers:  83%|████████▎ | 5730/6932 [20:30<04:15,  4.70it/s]

Processing tickers:  83%|████████▎ | 5731/6932 [20:30<04:13,  4.73it/s]

Processing tickers:  83%|████████▎ | 5732/6932 [20:30<04:14,  4.71it/s]

Processing tickers:  83%|████████▎ | 5733/6932 [20:30<04:16,  4.68it/s]

Processing tickers:  83%|████████▎ | 5734/6932 [20:31<04:13,  4.72it/s]

Processing tickers:  83%|████████▎ | 5735/6932 [20:31<04:12,  4.74it/s]

Processing tickers:  83%|████████▎ | 5736/6932 [20:31<04:11,  4.76it/s]

Processing tickers:  83%|████████▎ | 5737/6932 [20:32<06:05,  3.27it/s]

Processing tickers:  83%|████████▎ | 5738/6932 [20:32<05:34,  3.57it/s]

Processing tickers:  83%|████████▎ | 5739/6932 [20:32<05:03,  3.93it/s]

Processing tickers:  83%|████████▎ | 5740/6932 [20:32<04:51,  4.09it/s]

Processing tickers:  83%|████████▎ | 5741/6932 [20:32<04:39,  4.27it/s]

Processing tickers:  83%|████████▎ | 5742/6932 [20:33<04:29,  4.42it/s]

Processing tickers:  83%|████████▎ | 5743/6932 [20:33<04:22,  4.53it/s]

Processing tickers:  83%|████████▎ | 5744/6932 [20:33<04:19,  4.58it/s]

Processing tickers:  83%|████████▎ | 5745/6932 [20:33<04:20,  4.55it/s]

Processing tickers:  83%|████████▎ | 5746/6932 [20:33<04:15,  4.64it/s]

Processing tickers:  83%|████████▎ | 5747/6932 [20:34<04:12,  4.68it/s]

Processing tickers:  83%|████████▎ | 5748/6932 [20:34<04:11,  4.72it/s]

Processing tickers:  83%|████████▎ | 5749/6932 [20:34<04:11,  4.70it/s]

Processing tickers:  83%|████████▎ | 5750/6932 [20:34<04:09,  4.73it/s]

Processing tickers:  83%|████████▎ | 5751/6932 [20:34<04:06,  4.78it/s]

Processing tickers:  83%|████████▎ | 5752/6932 [20:35<04:06,  4.79it/s]

Processing tickers:  83%|████████▎ | 5753/6932 [20:35<04:08,  4.75it/s]

Processing tickers:  83%|████████▎ | 5754/6932 [20:35<04:04,  4.81it/s]

Processing tickers:  83%|████████▎ | 5755/6932 [20:35<04:08,  4.74it/s]

Processing tickers:  83%|████████▎ | 5756/6932 [20:36<04:06,  4.76it/s]

Processing tickers:  83%|████████▎ | 5757/6932 [20:36<04:09,  4.71it/s]

Processing tickers:  83%|████████▎ | 5758/6932 [20:36<04:09,  4.71it/s]

Processing tickers:  83%|████████▎ | 5759/6932 [20:36<04:05,  4.78it/s]

Processing tickers:  83%|████████▎ | 5760/6932 [20:36<04:04,  4.79it/s]

Processing tickers:  83%|████████▎ | 5761/6932 [20:37<03:58,  4.92it/s]

Processing tickers:  83%|████████▎ | 5762/6932 [20:37<03:59,  4.88it/s]

Processing tickers:  83%|████████▎ | 5763/6932 [20:37<04:11,  4.66it/s]

Processing tickers:  83%|████████▎ | 5764/6932 [20:37<04:10,  4.66it/s]

Processing tickers:  83%|████████▎ | 5765/6932 [20:37<04:09,  4.68it/s]

Processing tickers:  83%|████████▎ | 5766/6932 [20:38<04:12,  4.62it/s]

Processing tickers:  83%|████████▎ | 5767/6932 [20:38<04:09,  4.66it/s]

Processing tickers:  83%|████████▎ | 5768/6932 [20:38<04:06,  4.72it/s]

Processing tickers:  83%|████████▎ | 5769/6932 [20:38<04:05,  4.74it/s]

Processing tickers:  83%|████████▎ | 5770/6932 [20:39<04:09,  4.66it/s]

Processing tickers:  83%|████████▎ | 5771/6932 [20:39<04:11,  4.61it/s]

Processing tickers:  83%|████████▎ | 5772/6932 [20:39<04:09,  4.65it/s]

Processing tickers:  83%|████████▎ | 5773/6932 [20:39<04:06,  4.70it/s]

Processing tickers:  83%|████████▎ | 5774/6932 [20:39<04:10,  4.61it/s]

Processing tickers:  83%|████████▎ | 5775/6932 [20:40<04:07,  4.68it/s]

Processing tickers:  83%|████████▎ | 5776/6932 [20:40<04:04,  4.72it/s]

Processing tickers:  83%|████████▎ | 5777/6932 [20:40<04:07,  4.67it/s]

Processing tickers:  83%|████████▎ | 5778/6932 [20:40<04:07,  4.67it/s]

Processing tickers:  83%|████████▎ | 5779/6932 [20:40<04:05,  4.69it/s]

Processing tickers:  83%|████████▎ | 5780/6932 [20:41<04:04,  4.72it/s]

Processing tickers:  83%|████████▎ | 5781/6932 [20:41<04:01,  4.76it/s]

Processing tickers:  83%|████████▎ | 5782/6932 [20:41<04:02,  4.74it/s]

Processing tickers:  83%|████████▎ | 5783/6932 [20:41<03:59,  4.79it/s]

Processing tickers:  83%|████████▎ | 5784/6932 [20:41<04:05,  4.68it/s]

Processing tickers:  83%|████████▎ | 5785/6932 [20:42<04:03,  4.70it/s]

Processing tickers:  83%|████████▎ | 5786/6932 [20:42<04:04,  4.69it/s]

Processing tickers:  83%|████████▎ | 5787/6932 [20:42<04:04,  4.68it/s]

Processing tickers:  83%|████████▎ | 5788/6932 [20:42<04:02,  4.72it/s]

Processing tickers:  84%|████████▎ | 5789/6932 [20:43<04:00,  4.75it/s]

Processing tickers:  84%|████████▎ | 5790/6932 [20:43<03:59,  4.77it/s]

Processing tickers:  84%|████████▎ | 5791/6932 [20:43<04:01,  4.72it/s]

Processing tickers:  84%|████████▎ | 5792/6932 [20:43<03:59,  4.75it/s]

Processing tickers:  84%|████████▎ | 5793/6932 [20:43<04:20,  4.38it/s]

Processing tickers:  84%|████████▎ | 5794/6932 [20:44<04:11,  4.53it/s]

Processing tickers:  84%|████████▎ | 5795/6932 [20:44<04:06,  4.61it/s]

Processing tickers:  84%|████████▎ | 5796/6932 [20:44<04:03,  4.66it/s]

Processing tickers:  84%|████████▎ | 5797/6932 [20:44<04:02,  4.68it/s]

Processing tickers:  84%|████████▎ | 5798/6932 [20:45<04:04,  4.63it/s]

Processing tickers:  84%|████████▎ | 5799/6932 [20:45<04:01,  4.69it/s]

Processing tickers:  84%|████████▎ | 5800/6932 [20:45<03:59,  4.72it/s]

Processing tickers:  84%|████████▎ | 5801/6932 [20:45<03:58,  4.75it/s]

Processing tickers:  84%|████████▎ | 5802/6932 [20:45<04:01,  4.67it/s]

Processing tickers:  84%|████████▎ | 5803/6932 [20:46<03:59,  4.72it/s]

Processing tickers:  84%|████████▎ | 5804/6932 [20:46<03:58,  4.73it/s]

Processing tickers:  84%|████████▎ | 5805/6932 [20:46<04:00,  4.69it/s]

Processing tickers:  84%|████████▍ | 5806/6932 [20:46<03:58,  4.73it/s]

Processing tickers:  84%|████████▍ | 5807/6932 [20:46<03:53,  4.82it/s]

Processing tickers:  84%|████████▍ | 5808/6932 [20:47<03:53,  4.82it/s]

Processing tickers:  84%|████████▍ | 5809/6932 [20:47<03:58,  4.71it/s]

Processing tickers:  84%|████████▍ | 5810/6932 [20:47<03:57,  4.73it/s]

Processing tickers:  84%|████████▍ | 5811/6932 [20:47<03:55,  4.77it/s]

Processing tickers:  84%|████████▍ | 5812/6932 [20:47<03:57,  4.71it/s]

Processing tickers:  84%|████████▍ | 5813/6932 [20:48<03:58,  4.70it/s]

Processing tickers:  84%|████████▍ | 5814/6932 [20:48<03:58,  4.69it/s]

Processing tickers:  84%|████████▍ | 5815/6932 [20:48<03:54,  4.76it/s]

Processing tickers:  84%|████████▍ | 5816/6932 [20:48<03:59,  4.67it/s]

Processing tickers:  84%|████████▍ | 5817/6932 [20:49<03:56,  4.71it/s]

Processing tickers:  84%|████████▍ | 5818/6932 [20:49<03:55,  4.73it/s]

Processing tickers:  84%|████████▍ | 5819/6932 [20:49<03:59,  4.65it/s]

Processing tickers:  84%|████████▍ | 5820/6932 [20:49<03:56,  4.69it/s]

Processing tickers:  84%|████████▍ | 5821/6932 [20:49<03:55,  4.73it/s]

Processing tickers:  84%|████████▍ | 5822/6932 [20:50<03:53,  4.75it/s]

Processing tickers:  84%|████████▍ | 5823/6932 [20:50<03:52,  4.76it/s]

Processing tickers:  84%|████████▍ | 5824/6932 [20:50<03:51,  4.78it/s]

Processing tickers:  84%|████████▍ | 5825/6932 [20:50<03:51,  4.79it/s]

Processing tickers:  84%|████████▍ | 5826/6932 [20:50<03:50,  4.80it/s]

Processing tickers:  84%|████████▍ | 5827/6932 [20:51<03:52,  4.75it/s]

Processing tickers:  84%|████████▍ | 5828/6932 [20:51<03:54,  4.71it/s]

Processing tickers:  84%|████████▍ | 5829/6932 [20:51<03:52,  4.74it/s]

Processing tickers:  84%|████████▍ | 5830/6932 [20:51<03:54,  4.71it/s]

Processing tickers:  84%|████████▍ | 5831/6932 [20:51<03:51,  4.77it/s]

Processing tickers:  84%|████████▍ | 5832/6932 [20:52<03:55,  4.67it/s]

Processing tickers:  84%|████████▍ | 5833/6932 [20:52<03:52,  4.73it/s]

Processing tickers:  84%|████████▍ | 5834/6932 [20:52<03:56,  4.65it/s]

Processing tickers:  84%|████████▍ | 5835/6932 [20:52<03:55,  4.66it/s]

Processing tickers:  84%|████████▍ | 5836/6932 [20:53<03:51,  4.73it/s]

Processing tickers:  84%|████████▍ | 5837/6932 [20:53<03:54,  4.66it/s]

Processing tickers:  84%|████████▍ | 5838/6932 [20:53<03:53,  4.69it/s]

Processing tickers:  84%|████████▍ | 5839/6932 [20:53<03:56,  4.63it/s]

Processing tickers:  84%|████████▍ | 5840/6932 [20:53<03:53,  4.68it/s]

Processing tickers:  84%|████████▍ | 5841/6932 [20:54<03:50,  4.72it/s]

Processing tickers:  84%|████████▍ | 5842/6932 [20:54<03:52,  4.68it/s]

Processing tickers:  84%|████████▍ | 5843/6932 [20:54<03:52,  4.68it/s]

Processing tickers:  84%|████████▍ | 5844/6932 [20:54<03:50,  4.72it/s]

Processing tickers:  84%|████████▍ | 5845/6932 [20:54<03:49,  4.74it/s]

Processing tickers:  84%|████████▍ | 5846/6932 [20:55<03:47,  4.77it/s]

Processing tickers:  84%|████████▍ | 5847/6932 [20:55<03:46,  4.78it/s]

Processing tickers:  84%|████████▍ | 5848/6932 [20:55<03:46,  4.78it/s]

Processing tickers:  84%|████████▍ | 5849/6932 [20:55<03:46,  4.79it/s]

Processing tickers:  84%|████████▍ | 5850/6932 [20:55<03:45,  4.79it/s]

Processing tickers:  84%|████████▍ | 5851/6932 [20:56<03:50,  4.68it/s]

Processing tickers:  84%|████████▍ | 5852/6932 [20:56<03:49,  4.72it/s]

Processing tickers:  84%|████████▍ | 5853/6932 [20:56<03:47,  4.75it/s]

Processing tickers:  84%|████████▍ | 5854/6932 [20:56<03:51,  4.66it/s]

Processing tickers:  84%|████████▍ | 5855/6932 [20:57<03:49,  4.69it/s]

Processing tickers:  84%|████████▍ | 5856/6932 [20:57<03:47,  4.74it/s]

Processing tickers:  84%|████████▍ | 5857/6932 [20:57<03:50,  4.66it/s]

Processing tickers:  85%|████████▍ | 5858/6932 [20:57<03:49,  4.68it/s]

Processing tickers:  85%|████████▍ | 5859/6932 [20:57<03:41,  4.84it/s]

Processing tickers:  85%|████████▍ | 5860/6932 [20:58<03:46,  4.73it/s]

Processing tickers:  85%|████████▍ | 5861/6932 [20:58<03:45,  4.74it/s]

Processing tickers:  85%|████████▍ | 5862/6932 [20:58<03:44,  4.77it/s]

Processing tickers:  85%|████████▍ | 5863/6932 [20:58<03:44,  4.76it/s]

Processing tickers:  85%|████████▍ | 5864/6932 [20:58<03:42,  4.80it/s]

Processing tickers:  85%|████████▍ | 5865/6932 [20:59<03:47,  4.70it/s]

Processing tickers:  85%|████████▍ | 5866/6932 [20:59<03:49,  4.64it/s]

Processing tickers:  85%|████████▍ | 5867/6932 [20:59<03:47,  4.69it/s]

Processing tickers:  85%|████████▍ | 5868/6932 [20:59<03:50,  4.62it/s]

Processing tickers:  85%|████████▍ | 5869/6932 [21:00<03:47,  4.67it/s]

Processing tickers:  85%|████████▍ | 5870/6932 [21:00<03:45,  4.71it/s]

Processing tickers:  85%|████████▍ | 5871/6932 [21:00<03:43,  4.74it/s]

Processing tickers:  85%|████████▍ | 5872/6932 [21:00<03:47,  4.66it/s]

Processing tickers:  85%|████████▍ | 5873/6932 [21:00<03:40,  4.80it/s]

Processing tickers:  85%|████████▍ | 5874/6932 [21:01<03:46,  4.67it/s]

Processing tickers:  85%|████████▍ | 5875/6932 [21:01<03:47,  4.64it/s]

Processing tickers:  85%|████████▍ | 5876/6932 [21:01<03:49,  4.60it/s]

Processing tickers:  85%|████████▍ | 5877/6932 [21:01<03:46,  4.65it/s]

Processing tickers:  85%|████████▍ | 5878/6932 [21:01<03:44,  4.69it/s]

Processing tickers:  85%|████████▍ | 5879/6932 [21:02<03:48,  4.62it/s]

Processing tickers:  85%|████████▍ | 5880/6932 [21:02<03:45,  4.66it/s]

Processing tickers:  85%|████████▍ | 5881/6932 [21:02<03:43,  4.71it/s]

Processing tickers:  85%|████████▍ | 5882/6932 [21:02<03:41,  4.74it/s]

Processing tickers:  85%|████████▍ | 5883/6932 [21:03<03:40,  4.75it/s]

Processing tickers:  85%|████████▍ | 5884/6932 [21:03<03:38,  4.79it/s]

Processing tickers:  85%|████████▍ | 5885/6932 [21:03<03:42,  4.71it/s]

Processing tickers:  85%|████████▍ | 5886/6932 [21:03<03:41,  4.71it/s]

Processing tickers:  85%|████████▍ | 5887/6932 [21:03<03:40,  4.74it/s]

Processing tickers:  85%|████████▍ | 5888/6932 [21:04<03:39,  4.76it/s]

Processing tickers:  85%|████████▍ | 5889/6932 [21:04<03:38,  4.78it/s]

Processing tickers:  85%|████████▍ | 5890/6932 [21:04<03:41,  4.70it/s]

Processing tickers:  85%|████████▍ | 5891/6932 [21:04<03:44,  4.63it/s]

Processing tickers:  85%|████████▍ | 5892/6932 [21:04<03:38,  4.76it/s]

Processing tickers:  85%|████████▌ | 5893/6932 [21:05<03:43,  4.65it/s]

Processing tickers:  85%|████████▌ | 5894/6932 [21:05<03:39,  4.73it/s]

Processing tickers:  85%|████████▌ | 5895/6932 [21:05<03:38,  4.75it/s]

Processing tickers:  85%|████████▌ | 5896/6932 [21:05<03:37,  4.76it/s]

Processing tickers:  85%|████████▌ | 5897/6932 [21:05<03:39,  4.71it/s]

Processing tickers:  85%|████████▌ | 5898/6932 [21:06<03:35,  4.80it/s]

Processing tickers:  85%|████████▌ | 5899/6932 [21:06<03:36,  4.78it/s]

Processing tickers:  85%|████████▌ | 5900/6932 [21:06<03:34,  4.81it/s]

Processing tickers:  85%|████████▌ | 5901/6932 [21:06<03:37,  4.74it/s]

Processing tickers:  85%|████████▌ | 5902/6932 [21:07<03:33,  4.82it/s]

Processing tickers:  85%|████████▌ | 5903/6932 [21:07<03:38,  4.71it/s]

Processing tickers:  85%|████████▌ | 5904/6932 [21:07<03:41,  4.64it/s]

Processing tickers:  85%|████████▌ | 5905/6932 [21:07<03:44,  4.58it/s]

Processing tickers:  85%|████████▌ | 5906/6932 [21:07<03:44,  4.57it/s]

Processing tickers:  85%|████████▌ | 5907/6932 [21:08<03:45,  4.55it/s]

Processing tickers:  85%|████████▌ | 5908/6932 [21:08<03:48,  4.49it/s]

Processing tickers:  85%|████████▌ | 5909/6932 [21:08<03:41,  4.62it/s]

Processing tickers:  85%|████████▌ | 5910/6932 [21:08<03:38,  4.68it/s]

Processing tickers:  85%|████████▌ | 5911/6932 [21:08<03:36,  4.72it/s]

Processing tickers:  85%|████████▌ | 5912/6932 [21:09<03:35,  4.73it/s]

Processing tickers:  85%|████████▌ | 5913/6932 [21:09<03:33,  4.76it/s]

Processing tickers:  85%|████████▌ | 5914/6932 [21:09<03:38,  4.67it/s]

Processing tickers:  85%|████████▌ | 5915/6932 [21:09<03:35,  4.72it/s]

Processing tickers:  85%|████████▌ | 5916/6932 [21:10<03:30,  4.84it/s]

Processing tickers:  85%|████████▌ | 5917/6932 [21:10<03:35,  4.72it/s]

Processing tickers:  85%|████████▌ | 5918/6932 [21:10<03:37,  4.67it/s]

Processing tickers:  85%|████████▌ | 5919/6932 [21:10<03:35,  4.69it/s]

Processing tickers:  85%|████████▌ | 5920/6932 [21:10<03:30,  4.81it/s]

Processing tickers:  85%|████████▌ | 5921/6932 [21:11<03:35,  4.70it/s]

Processing tickers:  85%|████████▌ | 5922/6932 [21:11<03:33,  4.73it/s]

Processing tickers:  85%|████████▌ | 5923/6932 [21:11<03:32,  4.75it/s]

Processing tickers:  85%|████████▌ | 5924/6932 [21:11<03:36,  4.66it/s]

Processing tickers:  85%|████████▌ | 5925/6932 [21:11<03:36,  4.64it/s]

Processing tickers:  85%|████████▌ | 5926/6932 [21:12<03:35,  4.67it/s]

Processing tickers:  86%|████████▌ | 5927/6932 [21:12<03:29,  4.79it/s]

Processing tickers:  86%|████████▌ | 5928/6932 [21:12<03:34,  4.69it/s]

Processing tickers:  86%|████████▌ | 5929/6932 [21:12<03:27,  4.83it/s]

Processing tickers:  86%|████████▌ | 5930/6932 [21:12<03:27,  4.82it/s]

Processing tickers:  86%|████████▌ | 5931/6932 [21:13<03:29,  4.78it/s]

Processing tickers:  86%|████████▌ | 5932/6932 [21:13<03:27,  4.82it/s]

Processing tickers:  86%|████████▌ | 5933/6932 [21:13<03:27,  4.82it/s]

Processing tickers:  86%|████████▌ | 5934/6932 [21:13<03:27,  4.82it/s]

Processing tickers:  86%|████████▌ | 5935/6932 [21:14<03:27,  4.82it/s]

Processing tickers:  86%|████████▌ | 5936/6932 [21:14<03:27,  4.80it/s]

Processing tickers:  86%|████████▌ | 5937/6932 [21:14<03:26,  4.81it/s]

Processing tickers:  86%|████████▌ | 5938/6932 [21:14<03:31,  4.70it/s]

Processing tickers:  86%|████████▌ | 5939/6932 [21:14<03:29,  4.73it/s]

Processing tickers:  86%|████████▌ | 5940/6932 [21:15<03:32,  4.66it/s]

Processing tickers:  86%|████████▌ | 5941/6932 [21:15<03:31,  4.69it/s]

Processing tickers:  86%|████████▌ | 5942/6932 [21:15<03:34,  4.62it/s]

Processing tickers:  86%|████████▌ | 5943/6932 [21:15<03:32,  4.66it/s]

Processing tickers:  86%|████████▌ | 5944/6932 [21:15<03:31,  4.68it/s]

Processing tickers:  86%|████████▌ | 5945/6932 [21:16<03:30,  4.68it/s]

Processing tickers:  86%|████████▌ | 5946/6932 [21:16<03:25,  4.79it/s]

Processing tickers:  86%|████████▌ | 5947/6932 [21:16<03:25,  4.80it/s]

Processing tickers:  86%|████████▌ | 5948/6932 [21:16<03:25,  4.80it/s]

Processing tickers:  86%|████████▌ | 5949/6932 [21:16<03:24,  4.80it/s]

Processing tickers:  86%|████████▌ | 5950/6932 [21:17<03:34,  4.59it/s]

Processing tickers:  86%|████████▌ | 5951/6932 [21:17<03:26,  4.76it/s]

Processing tickers:  86%|████████▌ | 5952/6932 [21:17<03:34,  4.57it/s]

Processing tickers:  86%|████████▌ | 5953/6932 [21:17<03:31,  4.63it/s]

Processing tickers:  86%|████████▌ | 5954/6932 [21:18<03:28,  4.69it/s]

Processing tickers:  86%|████████▌ | 5955/6932 [21:18<03:31,  4.61it/s]

Processing tickers:  86%|████████▌ | 5956/6932 [21:18<03:24,  4.78it/s]

Processing tickers:  86%|████████▌ | 5957/6932 [21:18<03:23,  4.78it/s]

Processing tickers:  86%|████████▌ | 5958/6932 [21:18<03:23,  4.79it/s]

Processing tickers:  86%|████████▌ | 5959/6932 [21:19<03:27,  4.69it/s]

Processing tickers:  86%|████████▌ | 5960/6932 [21:19<03:26,  4.71it/s]

Processing tickers:  86%|████████▌ | 5961/6932 [21:19<03:24,  4.76it/s]

Processing tickers:  86%|████████▌ | 5962/6932 [21:19<03:23,  4.77it/s]

Processing tickers:  86%|████████▌ | 5963/6932 [21:19<03:25,  4.71it/s]

Processing tickers:  86%|████████▌ | 5964/6932 [21:20<03:21,  4.81it/s]

Processing tickers:  86%|████████▌ | 5965/6932 [21:20<03:20,  4.82it/s]

Processing tickers:  86%|████████▌ | 5966/6932 [21:20<03:20,  4.81it/s]

Processing tickers:  86%|████████▌ | 5967/6932 [21:20<03:20,  4.81it/s]

Processing tickers:  86%|████████▌ | 5968/6932 [21:21<03:20,  4.81it/s]

Processing tickers:  86%|████████▌ | 5969/6932 [21:21<03:25,  4.69it/s]

Processing tickers:  86%|████████▌ | 5970/6932 [21:21<03:23,  4.73it/s]

Processing tickers:  86%|████████▌ | 5971/6932 [21:21<03:23,  4.72it/s]

Processing tickers:  86%|████████▌ | 5972/6932 [21:21<03:24,  4.69it/s]

Processing tickers:  86%|████████▌ | 5973/6932 [21:22<03:19,  4.80it/s]

Processing tickers:  86%|████████▌ | 5974/6932 [21:22<03:19,  4.80it/s]

Processing tickers:  86%|████████▌ | 5975/6932 [21:22<03:19,  4.80it/s]

Processing tickers:  86%|████████▌ | 5976/6932 [21:22<03:19,  4.80it/s]

Processing tickers:  86%|████████▌ | 5977/6932 [21:22<03:18,  4.80it/s]

Processing tickers:  86%|████████▌ | 5978/6932 [21:23<03:18,  4.80it/s]

Processing tickers:  86%|████████▋ | 5979/6932 [21:23<03:22,  4.69it/s]

Processing tickers:  86%|████████▋ | 5980/6932 [21:23<03:21,  4.73it/s]

Processing tickers:  86%|████████▋ | 5981/6932 [21:23<03:20,  4.75it/s]

Processing tickers:  86%|████████▋ | 5982/6932 [21:23<03:19,  4.76it/s]

Processing tickers:  86%|████████▋ | 5983/6932 [21:24<03:18,  4.78it/s]

Processing tickers:  86%|████████▋ | 5984/6932 [21:24<03:18,  4.78it/s]

Processing tickers:  86%|████████▋ | 5985/6932 [21:24<03:18,  4.78it/s]

Processing tickers:  86%|████████▋ | 5986/6932 [21:24<03:17,  4.79it/s]

Processing tickers:  86%|████████▋ | 5987/6932 [21:25<03:20,  4.70it/s]

Processing tickers:  86%|████████▋ | 5988/6932 [21:25<03:25,  4.59it/s]

Processing tickers:  86%|████████▋ | 5989/6932 [21:25<03:22,  4.66it/s]

Processing tickers:  86%|████████▋ | 5990/6932 [21:25<03:19,  4.72it/s]

Processing tickers:  86%|████████▋ | 5991/6932 [21:25<03:20,  4.69it/s]

Processing tickers:  86%|████████▋ | 5992/6932 [21:26<03:19,  4.71it/s]

Processing tickers:  86%|████████▋ | 5993/6932 [21:26<03:15,  4.81it/s]

Processing tickers:  86%|████████▋ | 5994/6932 [21:26<03:15,  4.80it/s]

Processing tickers:  86%|████████▋ | 5995/6932 [21:26<03:18,  4.71it/s]

Processing tickers:  86%|████████▋ | 5996/6932 [21:26<03:13,  4.83it/s]

Processing tickers:  87%|████████▋ | 5997/6932 [21:27<03:14,  4.82it/s]

Processing tickers:  87%|████████▋ | 5998/6932 [21:27<03:18,  4.71it/s]

Processing tickers:  87%|████████▋ | 5999/6932 [21:27<03:16,  4.74it/s]

Processing tickers:  87%|████████▋ | 6000/6932 [21:27<03:19,  4.67it/s]

Processing tickers:  87%|████████▋ | 6001/6932 [21:27<03:23,  4.58it/s]

Processing tickers:  87%|████████▋ | 6002/6932 [21:28<03:19,  4.67it/s]

Processing tickers:  87%|████████▋ | 6003/6932 [21:28<03:22,  4.60it/s]

Processing tickers:  87%|████████▋ | 6004/6932 [21:28<03:18,  4.67it/s]

Processing tickers:  87%|████████▋ | 6005/6932 [21:28<03:16,  4.73it/s]

Processing tickers:  87%|████████▋ | 6006/6932 [21:29<03:18,  4.66it/s]

Processing tickers:  87%|████████▋ | 6007/6932 [21:29<03:21,  4.59it/s]

Processing tickers:  87%|████████▋ | 6008/6932 [21:29<03:18,  4.65it/s]

Processing tickers:  87%|████████▋ | 6009/6932 [21:29<03:16,  4.70it/s]

Processing tickers:  87%|████████▋ | 6010/6932 [21:29<03:14,  4.73it/s]

Processing tickers:  87%|████████▋ | 6011/6932 [21:30<03:13,  4.75it/s]

Processing tickers:  87%|████████▋ | 6012/6932 [21:30<03:09,  4.85it/s]

Processing tickers:  87%|████████▋ | 6013/6932 [21:30<03:08,  4.86it/s]

Processing tickers:  87%|████████▋ | 6014/6932 [21:30<03:09,  4.84it/s]

Processing tickers:  87%|████████▋ | 6015/6932 [21:30<03:14,  4.72it/s]

Processing tickers:  87%|████████▋ | 6016/6932 [21:31<03:12,  4.75it/s]

Processing tickers:  87%|████████▋ | 6017/6932 [21:31<03:11,  4.77it/s]

Processing tickers:  87%|████████▋ | 6018/6932 [21:31<03:11,  4.77it/s]

Processing tickers:  87%|████████▋ | 6019/6932 [21:31<03:10,  4.80it/s]

Processing tickers:  87%|████████▋ | 6020/6932 [21:31<03:14,  4.69it/s]

Processing tickers:  87%|████████▋ | 6021/6932 [21:32<03:12,  4.72it/s]

Processing tickers:  87%|████████▋ | 6022/6932 [21:32<03:11,  4.75it/s]

Processing tickers:  87%|████████▋ | 6023/6932 [21:32<03:12,  4.73it/s]

Processing tickers:  87%|████████▋ | 6024/6932 [21:32<03:09,  4.79it/s]

Processing tickers:  87%|████████▋ | 6025/6932 [21:33<03:09,  4.79it/s]

Processing tickers:  87%|████████▋ | 6026/6932 [21:33<03:08,  4.80it/s]

Processing tickers:  87%|████████▋ | 6027/6932 [21:33<03:13,  4.68it/s]

Processing tickers:  87%|████████▋ | 6028/6932 [21:33<03:11,  4.73it/s]

Processing tickers:  87%|████████▋ | 6029/6932 [21:33<03:09,  4.76it/s]

Processing tickers:  87%|████████▋ | 6030/6932 [21:34<03:09,  4.77it/s]

Processing tickers:  87%|████████▋ | 6031/6932 [21:34<03:08,  4.78it/s]

Processing tickers:  87%|████████▋ | 6032/6932 [21:34<03:08,  4.79it/s]

Processing tickers:  87%|████████▋ | 6033/6932 [21:34<03:12,  4.68it/s]

Processing tickers:  87%|████████▋ | 6034/6932 [21:34<03:10,  4.73it/s]

Processing tickers:  87%|████████▋ | 6035/6932 [21:35<03:04,  4.86it/s]

Processing tickers:  87%|████████▋ | 6036/6932 [21:35<03:05,  4.84it/s]

Processing tickers:  87%|████████▋ | 6037/6932 [21:35<03:05,  4.83it/s]

Processing tickers:  87%|████████▋ | 6038/6932 [21:35<03:05,  4.82it/s]

Processing tickers:  87%|████████▋ | 6039/6932 [21:35<03:05,  4.82it/s]

Processing tickers:  87%|████████▋ | 6040/6932 [21:36<03:05,  4.80it/s]

Processing tickers:  87%|████████▋ | 6041/6932 [21:36<03:05,  4.81it/s]

Processing tickers:  87%|████████▋ | 6042/6932 [21:36<03:04,  4.81it/s]

Processing tickers:  87%|████████▋ | 6043/6932 [21:36<03:05,  4.78it/s]

Processing tickers:  87%|████████▋ | 6044/6932 [21:37<03:04,  4.82it/s]

Processing tickers:  87%|████████▋ | 6045/6932 [21:37<03:04,  4.81it/s]

Processing tickers:  87%|████████▋ | 6046/6932 [21:37<03:04,  4.80it/s]

Processing tickers:  87%|████████▋ | 6047/6932 [21:37<03:04,  4.81it/s]

Processing tickers:  87%|████████▋ | 6048/6932 [21:37<03:03,  4.81it/s]

Processing tickers:  87%|████████▋ | 6049/6932 [21:38<03:03,  4.83it/s]

Processing tickers:  87%|████████▋ | 6050/6932 [21:38<03:02,  4.83it/s]

Processing tickers:  87%|████████▋ | 6051/6932 [21:38<03:02,  4.84it/s]

Processing tickers:  87%|████████▋ | 6052/6932 [21:38<03:02,  4.83it/s]

Processing tickers:  87%|████████▋ | 6053/6932 [21:38<03:02,  4.82it/s]

Processing tickers:  87%|████████▋ | 6054/6932 [21:39<03:02,  4.82it/s]

Processing tickers:  87%|████████▋ | 6055/6932 [21:39<03:04,  4.74it/s]

Processing tickers:  87%|████████▋ | 6056/6932 [21:39<03:01,  4.83it/s]

Processing tickers:  87%|████████▋ | 6057/6932 [21:39<03:04,  4.74it/s]

Processing tickers:  87%|████████▋ | 6058/6932 [21:39<03:04,  4.73it/s]

Processing tickers:  87%|████████▋ | 6059/6932 [21:40<03:03,  4.75it/s]

Processing tickers:  87%|████████▋ | 6060/6932 [21:40<03:02,  4.77it/s]

Processing tickers:  87%|████████▋ | 6061/6932 [21:40<03:01,  4.79it/s]

Processing tickers:  87%|████████▋ | 6062/6932 [21:40<03:02,  4.77it/s]

Processing tickers:  87%|████████▋ | 6063/6932 [21:40<03:05,  4.69it/s]

Processing tickers:  87%|████████▋ | 6064/6932 [21:41<03:03,  4.72it/s]

Processing tickers:  87%|████████▋ | 6065/6932 [21:41<03:03,  4.72it/s]

Processing tickers:  88%|████████▊ | 6066/6932 [21:41<03:01,  4.76it/s]

Processing tickers:  88%|████████▊ | 6067/6932 [21:41<03:01,  4.77it/s]

Processing tickers:  88%|████████▊ | 6068/6932 [21:42<03:02,  4.74it/s]

Processing tickers:  88%|████████▊ | 6069/6932 [21:42<02:59,  4.80it/s]

Processing tickers:  88%|████████▊ | 6070/6932 [21:42<03:04,  4.68it/s]

Processing tickers:  88%|████████▊ | 6071/6932 [21:42<03:02,  4.72it/s]

Processing tickers:  88%|████████▊ | 6072/6932 [21:42<03:00,  4.76it/s]

Processing tickers:  88%|████████▊ | 6073/6932 [21:43<03:04,  4.67it/s]

Processing tickers:  88%|████████▊ | 6074/6932 [21:43<03:03,  4.69it/s]

Processing tickers:  88%|████████▊ | 6075/6932 [21:43<03:00,  4.75it/s]

Processing tickers:  88%|████████▊ | 6076/6932 [21:43<02:59,  4.77it/s]

Processing tickers:  88%|████████▊ | 6077/6932 [21:43<02:58,  4.78it/s]

Processing tickers:  88%|████████▊ | 6078/6932 [21:44<02:58,  4.79it/s]

Processing tickers:  88%|████████▊ | 6079/6932 [21:44<03:02,  4.68it/s]

Processing tickers:  88%|████████▊ | 6080/6932 [21:44<03:01,  4.70it/s]

Processing tickers:  88%|████████▊ | 6081/6932 [21:44<02:59,  4.75it/s]

Processing tickers:  88%|████████▊ | 6082/6932 [21:44<02:59,  4.73it/s]

Processing tickers:  88%|████████▊ | 6083/6932 [21:45<02:57,  4.78it/s]

Processing tickers:  88%|████████▊ | 6084/6932 [21:45<02:59,  4.72it/s]

Processing tickers:  88%|████████▊ | 6085/6932 [21:45<02:55,  4.82it/s]

Processing tickers:  88%|████████▊ | 6086/6932 [21:45<02:55,  4.82it/s]

Processing tickers:  88%|████████▊ | 6087/6932 [21:46<02:59,  4.70it/s]

Processing tickers:  88%|████████▊ | 6088/6932 [21:46<02:57,  4.75it/s]

Processing tickers:  88%|████████▊ | 6089/6932 [21:46<02:56,  4.78it/s]

Processing tickers:  88%|████████▊ | 6090/6932 [21:46<03:00,  4.67it/s]

Processing tickers:  88%|████████▊ | 6091/6932 [21:46<02:58,  4.70it/s]

Processing tickers:  88%|████████▊ | 6092/6932 [21:47<02:56,  4.76it/s]

Processing tickers:  88%|████████▊ | 6093/6932 [21:47<02:55,  4.78it/s]

Processing tickers:  88%|████████▊ | 6094/6932 [21:47<02:56,  4.76it/s]

Processing tickers:  88%|████████▊ | 6095/6932 [21:47<02:54,  4.80it/s]

Processing tickers:  88%|████████▊ | 6096/6932 [21:47<02:54,  4.80it/s]

Processing tickers:  88%|████████▊ | 6097/6932 [21:48<02:56,  4.72it/s]

Processing tickers:  88%|████████▊ | 6098/6932 [21:48<02:55,  4.74it/s]

Processing tickers:  88%|████████▊ | 6099/6932 [21:48<02:51,  4.85it/s]

Processing tickers:  88%|████████▊ | 6100/6932 [21:48<02:56,  4.72it/s]

Processing tickers:  88%|████████▊ | 6101/6932 [21:48<02:54,  4.76it/s]

Processing tickers:  88%|████████▊ | 6102/6932 [21:49<02:58,  4.66it/s]

Processing tickers:  88%|████████▊ | 6103/6932 [21:49<02:55,  4.71it/s]

Processing tickers:  88%|████████▊ | 6104/6932 [21:49<02:54,  4.74it/s]

Processing tickers:  88%|████████▊ | 6105/6932 [21:49<02:53,  4.76it/s]

Processing tickers:  88%|████████▊ | 6106/6932 [21:50<02:57,  4.66it/s]

Processing tickers:  88%|████████▊ | 6107/6932 [21:50<02:56,  4.69it/s]

Processing tickers:  88%|████████▊ | 6108/6932 [21:50<02:55,  4.70it/s]

Processing tickers:  88%|████████▊ | 6109/6932 [21:50<02:56,  4.67it/s]

Processing tickers:  88%|████████▊ | 6110/6932 [21:50<02:54,  4.71it/s]

Processing tickers:  88%|████████▊ | 6111/6932 [21:51<02:54,  4.72it/s]

Processing tickers:  88%|████████▊ | 6112/6932 [21:51<02:54,  4.71it/s]

Processing tickers:  88%|████████▊ | 6113/6932 [21:51<02:54,  4.69it/s]

Processing tickers:  88%|████████▊ | 6114/6932 [21:51<02:53,  4.73it/s]

Processing tickers:  88%|████████▊ | 6115/6932 [21:51<02:54,  4.69it/s]

Processing tickers:  88%|████████▊ | 6116/6932 [21:52<02:50,  4.78it/s]

Processing tickers:  88%|████████▊ | 6117/6932 [21:52<02:50,  4.77it/s]

Processing tickers:  88%|████████▊ | 6118/6932 [21:52<02:49,  4.80it/s]

Processing tickers:  88%|████████▊ | 6119/6932 [21:52<02:50,  4.77it/s]

Processing tickers:  88%|████████▊ | 6120/6932 [21:53<02:49,  4.79it/s]

Processing tickers:  88%|████████▊ | 6121/6932 [21:53<02:53,  4.69it/s]

Processing tickers:  88%|████████▊ | 6122/6932 [21:53<02:50,  4.74it/s]

Processing tickers:  88%|████████▊ | 6123/6932 [21:53<02:49,  4.76it/s]

Processing tickers:  88%|████████▊ | 6124/6932 [21:53<02:49,  4.78it/s]

Processing tickers:  88%|████████▊ | 6125/6932 [21:54<02:49,  4.75it/s]

Processing tickers:  88%|████████▊ | 6126/6932 [21:54<02:47,  4.81it/s]

Processing tickers:  88%|████████▊ | 6127/6932 [21:54<02:49,  4.74it/s]

Processing tickers:  88%|████████▊ | 6128/6932 [21:54<02:50,  4.72it/s]

Processing tickers:  88%|████████▊ | 6129/6932 [21:54<02:50,  4.72it/s]

Processing tickers:  88%|████████▊ | 6130/6932 [21:55<02:48,  4.75it/s]

Processing tickers:  88%|████████▊ | 6131/6932 [21:55<02:51,  4.68it/s]

Processing tickers:  88%|████████▊ | 6132/6932 [21:55<02:49,  4.72it/s]

Processing tickers:  88%|████████▊ | 6133/6932 [21:55<02:50,  4.68it/s]

Processing tickers:  88%|████████▊ | 6134/6932 [21:55<02:50,  4.69it/s]

Processing tickers:  89%|████████▊ | 6135/6932 [21:56<02:49,  4.70it/s]

Processing tickers:  89%|████████▊ | 6136/6932 [21:56<02:50,  4.67it/s]

Processing tickers:  89%|████████▊ | 6137/6932 [21:56<02:46,  4.79it/s]

Processing tickers:  89%|████████▊ | 6138/6932 [21:56<02:49,  4.70it/s]

Processing tickers:  89%|████████▊ | 6139/6932 [21:57<02:49,  4.67it/s]

Processing tickers:  89%|████████▊ | 6140/6932 [21:57<02:49,  4.67it/s]

Processing tickers:  89%|████████▊ | 6141/6932 [21:57<02:47,  4.72it/s]

Processing tickers:  89%|████████▊ | 6142/6932 [21:57<02:47,  4.72it/s]

Processing tickers:  89%|████████▊ | 6143/6932 [21:57<02:45,  4.78it/s]

Processing tickers:  89%|████████▊ | 6144/6932 [21:58<02:44,  4.79it/s]

Processing tickers:  89%|████████▊ | 6145/6932 [21:58<02:44,  4.80it/s]

Processing tickers:  89%|████████▊ | 6146/6932 [21:58<02:47,  4.70it/s]

Processing tickers:  89%|████████▊ | 6147/6932 [21:58<02:49,  4.64it/s]

Processing tickers:  89%|████████▊ | 6148/6932 [21:58<02:47,  4.69it/s]

Processing tickers:  89%|████████▊ | 6149/6932 [21:59<02:47,  4.69it/s]

Processing tickers:  89%|████████▊ | 6150/6932 [21:59<02:44,  4.76it/s]

Processing tickers:  89%|████████▊ | 6151/6932 [21:59<02:48,  4.64it/s]

Processing tickers:  89%|████████▊ | 6152/6932 [21:59<02:46,  4.68it/s]

Processing tickers:  89%|████████▉ | 6153/6932 [22:00<02:44,  4.74it/s]

Processing tickers:  89%|████████▉ | 6154/6932 [22:00<02:50,  4.56it/s]

Processing tickers:  89%|████████▉ | 6155/6932 [22:00<02:47,  4.63it/s]

Processing tickers:  89%|████████▉ | 6156/6932 [22:00<02:45,  4.68it/s]

Processing tickers:  89%|████████▉ | 6157/6932 [22:00<02:46,  4.66it/s]

Processing tickers:  89%|████████▉ | 6158/6932 [22:01<02:42,  4.76it/s]

Processing tickers:  89%|████████▉ | 6159/6932 [22:01<02:44,  4.70it/s]

Processing tickers:  89%|████████▉ | 6160/6932 [22:01<02:44,  4.69it/s]

Processing tickers:  89%|████████▉ | 6161/6932 [22:01<02:42,  4.73it/s]

Processing tickers:  89%|████████▉ | 6162/6932 [22:01<02:41,  4.76it/s]

Processing tickers:  89%|████████▉ | 6163/6932 [22:02<02:41,  4.77it/s]

Processing tickers:  89%|████████▉ | 6164/6932 [22:02<02:43,  4.69it/s]

Processing tickers:  89%|████████▉ | 6165/6932 [22:02<02:39,  4.81it/s]

Processing tickers:  89%|████████▉ | 6166/6932 [22:02<02:40,  4.76it/s]

Processing tickers:  89%|████████▉ | 6167/6932 [22:02<02:38,  4.82it/s]

Processing tickers:  89%|████████▉ | 6168/6932 [22:03<02:39,  4.79it/s]

Processing tickers:  89%|████████▉ | 6169/6932 [22:03<02:38,  4.81it/s]

Processing tickers:  89%|████████▉ | 6170/6932 [22:03<02:38,  4.82it/s]

Processing tickers:  89%|████████▉ | 6171/6932 [22:03<02:38,  4.82it/s]

Processing tickers:  89%|████████▉ | 6172/6932 [22:04<02:41,  4.71it/s]

Processing tickers:  89%|████████▉ | 6173/6932 [22:04<02:40,  4.73it/s]

Processing tickers:  89%|████████▉ | 6174/6932 [22:04<02:39,  4.76it/s]

Processing tickers:  89%|████████▉ | 6175/6932 [22:04<02:38,  4.78it/s]

Processing tickers:  89%|████████▉ | 6176/6932 [22:04<02:42,  4.66it/s]

Processing tickers:  89%|████████▉ | 6177/6932 [22:05<02:39,  4.72it/s]

Processing tickers:  89%|████████▉ | 6178/6932 [22:05<02:38,  4.76it/s]

Processing tickers:  89%|████████▉ | 6179/6932 [22:05<02:37,  4.77it/s]

Processing tickers:  89%|████████▉ | 6180/6932 [22:05<02:40,  4.69it/s]

Processing tickers:  89%|████████▉ | 6181/6932 [22:05<02:36,  4.81it/s]

Processing tickers:  89%|████████▉ | 6182/6932 [22:06<02:35,  4.81it/s]

Processing tickers:  89%|████████▉ | 6183/6932 [22:06<02:39,  4.69it/s]

Processing tickers:  89%|████████▉ | 6184/6932 [22:06<02:38,  4.73it/s]

Processing tickers:  89%|████████▉ | 6185/6932 [22:06<02:40,  4.65it/s]

Processing tickers:  89%|████████▉ | 6186/6932 [22:06<02:41,  4.63it/s]

Processing tickers:  89%|████████▉ | 6187/6932 [22:07<02:37,  4.73it/s]

Processing tickers:  89%|████████▉ | 6188/6932 [22:07<02:37,  4.71it/s]

Processing tickers:  89%|████████▉ | 6189/6932 [22:07<02:35,  4.79it/s]

Processing tickers:  89%|████████▉ | 6190/6932 [22:07<02:34,  4.80it/s]

Processing tickers:  89%|████████▉ | 6191/6932 [22:08<02:40,  4.60it/s]

Processing tickers:  89%|████████▉ | 6192/6932 [22:08<02:41,  4.57it/s]

Processing tickers:  89%|████████▉ | 6193/6932 [22:08<02:42,  4.55it/s]

Processing tickers:  89%|████████▉ | 6194/6932 [22:08<02:43,  4.51it/s]

Processing tickers:  89%|████████▉ | 6195/6932 [22:08<02:39,  4.61it/s]

Processing tickers:  89%|████████▉ | 6196/6932 [22:09<02:37,  4.67it/s]

Processing tickers:  89%|████████▉ | 6197/6932 [22:09<02:36,  4.71it/s]

Processing tickers:  89%|████████▉ | 6198/6932 [22:09<02:34,  4.74it/s]

Processing tickers:  89%|████████▉ | 6199/6932 [22:09<02:34,  4.75it/s]

Processing tickers:  89%|████████▉ | 6200/6932 [22:09<02:36,  4.67it/s]

Processing tickers:  89%|████████▉ | 6201/6932 [22:10<02:35,  4.70it/s]

Processing tickers:  89%|████████▉ | 6202/6932 [22:10<02:34,  4.73it/s]

Processing tickers:  89%|████████▉ | 6203/6932 [22:10<02:33,  4.75it/s]

Processing tickers:  89%|████████▉ | 6204/6932 [22:10<02:32,  4.77it/s]

Processing tickers:  90%|████████▉ | 6205/6932 [22:11<02:31,  4.78it/s]

Processing tickers:  90%|████████▉ | 6206/6932 [22:11<02:35,  4.68it/s]

Processing tickers:  90%|████████▉ | 6207/6932 [22:11<02:33,  4.72it/s]

Processing tickers:  90%|████████▉ | 6208/6932 [22:11<02:32,  4.74it/s]

Processing tickers:  90%|████████▉ | 6209/6932 [22:11<02:34,  4.68it/s]

Processing tickers:  90%|████████▉ | 6210/6932 [22:12<02:33,  4.70it/s]

Processing tickers:  90%|████████▉ | 6211/6932 [22:12<02:32,  4.72it/s]

Processing tickers:  90%|████████▉ | 6212/6932 [22:12<02:31,  4.75it/s]

Processing tickers:  90%|████████▉ | 6213/6932 [22:12<02:30,  4.77it/s]

Processing tickers:  90%|████████▉ | 6214/6932 [22:12<02:30,  4.77it/s]

Processing tickers:  90%|████████▉ | 6215/6932 [22:13<02:32,  4.71it/s]

Processing tickers:  90%|████████▉ | 6216/6932 [22:13<02:28,  4.81it/s]

Processing tickers:  90%|████████▉ | 6217/6932 [22:13<02:30,  4.75it/s]

Processing tickers:  90%|████████▉ | 6218/6932 [22:13<02:27,  4.83it/s]

Processing tickers:  90%|████████▉ | 6219/6932 [22:13<02:31,  4.71it/s]

Processing tickers:  90%|████████▉ | 6220/6932 [22:14<02:27,  4.83it/s]

Processing tickers:  90%|████████▉ | 6221/6932 [22:14<02:30,  4.73it/s]

Processing tickers:  90%|████████▉ | 6222/6932 [22:14<02:29,  4.76it/s]

Processing tickers:  90%|████████▉ | 6223/6932 [22:14<02:28,  4.77it/s]

Processing tickers:  90%|████████▉ | 6224/6932 [22:15<02:28,  4.78it/s]

Processing tickers:  90%|████████▉ | 6225/6932 [22:15<02:31,  4.68it/s]

Processing tickers:  90%|████████▉ | 6226/6932 [22:15<02:31,  4.67it/s]

Processing tickers:  90%|████████▉ | 6227/6932 [22:15<02:28,  4.76it/s]

Processing tickers:  90%|████████▉ | 6228/6932 [22:15<02:27,  4.78it/s]

Processing tickers:  90%|████████▉ | 6229/6932 [22:16<02:30,  4.66it/s]

Processing tickers:  90%|████████▉ | 6230/6932 [22:16<02:28,  4.72it/s]

Processing tickers:  90%|████████▉ | 6231/6932 [22:16<02:27,  4.74it/s]

Processing tickers:  90%|████████▉ | 6232/6932 [22:16<02:27,  4.76it/s]

Processing tickers:  90%|████████▉ | 6233/6932 [22:16<02:29,  4.68it/s]

Processing tickers:  90%|████████▉ | 6234/6932 [22:17<02:29,  4.68it/s]

Processing tickers:  90%|████████▉ | 6235/6932 [22:17<02:27,  4.73it/s]

Processing tickers:  90%|████████▉ | 6236/6932 [22:17<02:25,  4.78it/s]

Processing tickers:  90%|████████▉ | 6237/6932 [22:17<02:25,  4.78it/s]

Processing tickers:  90%|████████▉ | 6238/6932 [22:17<02:25,  4.77it/s]

Processing tickers:  90%|█████████ | 6239/6932 [22:18<02:24,  4.80it/s]

Processing tickers:  90%|█████████ | 6240/6932 [22:18<02:24,  4.80it/s]

Processing tickers:  90%|█████████ | 6241/6932 [22:18<02:23,  4.80it/s]

Processing tickers:  90%|█████████ | 6242/6932 [22:18<02:23,  4.80it/s]

Processing tickers:  90%|█████████ | 6243/6932 [22:19<02:23,  4.81it/s]

Processing tickers:  90%|█████████ | 6244/6932 [22:19<02:26,  4.70it/s]

Processing tickers:  90%|█████████ | 6245/6932 [22:19<02:25,  4.74it/s]

Processing tickers:  90%|█████████ | 6246/6932 [22:19<02:24,  4.75it/s]

Processing tickers:  90%|█████████ | 6247/6932 [22:19<02:23,  4.77it/s]

Processing tickers:  90%|█████████ | 6248/6932 [22:20<02:26,  4.67it/s]

Processing tickers:  90%|█████████ | 6249/6932 [22:20<02:25,  4.71it/s]

Processing tickers:  90%|█████████ | 6250/6932 [22:20<02:23,  4.74it/s]

Processing tickers:  90%|█████████ | 6251/6932 [22:20<02:23,  4.76it/s]

Processing tickers:  90%|█████████ | 6252/6932 [22:20<02:25,  4.66it/s]

Processing tickers:  90%|█████████ | 6253/6932 [22:21<02:24,  4.70it/s]

Processing tickers:  90%|█████████ | 6254/6932 [22:21<02:26,  4.62it/s]

Processing tickers:  90%|█████████ | 6255/6932 [22:21<02:24,  4.67it/s]

Processing tickers:  90%|█████████ | 6256/6932 [22:21<02:23,  4.72it/s]

Processing tickers:  90%|█████████ | 6257/6932 [22:22<02:22,  4.74it/s]

Processing tickers:  90%|█████████ | 6258/6932 [22:22<02:25,  4.63it/s]

Processing tickers:  90%|█████████ | 6259/6932 [22:22<02:24,  4.66it/s]

Processing tickers:  90%|█████████ | 6260/6932 [22:22<02:25,  4.61it/s]

Processing tickers:  90%|█████████ | 6261/6932 [22:22<02:22,  4.71it/s]

Processing tickers:  90%|█████████ | 6262/6932 [22:23<02:21,  4.74it/s]

Processing tickers:  90%|█████████ | 6263/6932 [22:23<02:20,  4.76it/s]

Processing tickers:  90%|█████████ | 6264/6932 [22:23<02:22,  4.70it/s]

Processing tickers:  90%|█████████ | 6265/6932 [22:23<02:22,  4.67it/s]

Processing tickers:  90%|█████████ | 6266/6932 [22:23<02:20,  4.74it/s]

Processing tickers:  90%|█████████ | 6267/6932 [22:24<02:20,  4.74it/s]

Processing tickers:  90%|█████████ | 6268/6932 [22:24<02:19,  4.77it/s]

Processing tickers:  90%|█████████ | 6269/6932 [22:24<02:20,  4.71it/s]

Processing tickers:  90%|█████████ | 6270/6932 [22:24<02:17,  4.81it/s]

Processing tickers:  90%|█████████ | 6271/6932 [22:24<02:17,  4.81it/s]

Processing tickers:  90%|█████████ | 6272/6932 [22:25<02:17,  4.80it/s]

Processing tickers:  90%|█████████ | 6273/6932 [22:25<02:16,  4.81it/s]

Processing tickers:  91%|█████████ | 6274/6932 [22:25<02:16,  4.81it/s]

Processing tickers:  91%|█████████ | 6275/6932 [22:25<02:20,  4.68it/s]

Processing tickers:  91%|█████████ | 6276/6932 [22:26<02:20,  4.67it/s]

Processing tickers:  91%|█████████ | 6277/6932 [22:26<02:20,  4.67it/s]

Processing tickers:  91%|█████████ | 6278/6932 [22:26<02:19,  4.70it/s]

Processing tickers:  91%|█████████ | 6279/6932 [22:26<02:17,  4.75it/s]

Processing tickers:  91%|█████████ | 6280/6932 [22:26<02:16,  4.77it/s]

Processing tickers:  91%|█████████ | 6281/6932 [22:27<02:16,  4.78it/s]

Processing tickers:  91%|█████████ | 6282/6932 [22:27<02:17,  4.71it/s]

Processing tickers:  91%|█████████ | 6283/6932 [22:27<02:14,  4.81it/s]

Processing tickers:  91%|█████████ | 6284/6932 [22:27<02:14,  4.81it/s]

Processing tickers:  91%|█████████ | 6285/6932 [22:27<02:14,  4.81it/s]

Processing tickers:  91%|█████████ | 6286/6932 [22:28<02:14,  4.82it/s]

Processing tickers:  91%|█████████ | 6287/6932 [22:28<02:13,  4.82it/s]

Processing tickers:  91%|█████████ | 6288/6932 [22:28<02:16,  4.71it/s]

Processing tickers:  91%|█████████ | 6289/6932 [22:28<02:16,  4.72it/s]

Processing tickers:  91%|█████████ | 6290/6932 [22:28<02:16,  4.70it/s]

Processing tickers:  91%|█████████ | 6291/6932 [22:29<02:13,  4.81it/s]

Processing tickers:  91%|█████████ | 6292/6932 [22:29<02:15,  4.72it/s]

Processing tickers:  91%|█████████ | 6293/6932 [22:29<02:16,  4.70it/s]

Processing tickers:  91%|█████████ | 6294/6932 [22:29<02:13,  4.78it/s]

Processing tickers:  91%|█████████ | 6295/6932 [22:30<02:13,  4.77it/s]

Processing tickers:  91%|█████████ | 6296/6932 [22:30<02:12,  4.80it/s]

Processing tickers:  91%|█████████ | 6297/6932 [22:30<02:14,  4.71it/s]

Processing tickers:  91%|█████████ | 6298/6932 [22:30<02:11,  4.83it/s]

Processing tickers:  91%|█████████ | 6299/6932 [22:30<02:14,  4.71it/s]

Processing tickers:  91%|█████████ | 6300/6932 [22:31<02:13,  4.74it/s]

Processing tickers:  91%|█████████ | 6301/6932 [22:31<02:12,  4.76it/s]

Processing tickers:  91%|█████████ | 6302/6932 [22:31<02:11,  4.78it/s]

Processing tickers:  91%|█████████ | 6303/6932 [22:31<02:14,  4.69it/s]

Processing tickers:  91%|█████████ | 6304/6932 [22:31<02:10,  4.82it/s]

Processing tickers:  91%|█████████ | 6305/6932 [22:32<02:13,  4.70it/s]

Processing tickers:  91%|█████████ | 6306/6932 [22:32<02:12,  4.74it/s]

Processing tickers:  91%|█████████ | 6307/6932 [22:32<02:11,  4.75it/s]

Processing tickers:  91%|█████████ | 6308/6932 [22:32<02:12,  4.70it/s]

Processing tickers:  91%|█████████ | 6309/6932 [22:32<02:09,  4.80it/s]

Processing tickers:  91%|█████████ | 6310/6932 [22:33<02:09,  4.80it/s]

Processing tickers:  91%|█████████ | 6311/6932 [22:33<02:12,  4.69it/s]

Processing tickers:  91%|█████████ | 6312/6932 [22:33<02:11,  4.73it/s]

Processing tickers:  91%|█████████ | 6313/6932 [22:33<02:10,  4.76it/s]

Processing tickers:  91%|█████████ | 6314/6932 [22:34<02:12,  4.67it/s]

Processing tickers:  91%|█████████ | 6315/6932 [22:34<02:11,  4.71it/s]

Processing tickers:  91%|█████████ | 6316/6932 [22:34<02:12,  4.65it/s]

Processing tickers:  91%|█████████ | 6317/6932 [22:34<02:11,  4.68it/s]

Processing tickers:  91%|█████████ | 6318/6932 [22:34<02:09,  4.72it/s]

Processing tickers:  91%|█████████ | 6319/6932 [22:35<02:09,  4.75it/s]

Processing tickers:  91%|█████████ | 6320/6932 [22:35<02:08,  4.77it/s]

Processing tickers:  91%|█████████ | 6321/6932 [22:35<02:09,  4.73it/s]

Processing tickers:  91%|█████████ | 6322/6932 [22:35<02:06,  4.81it/s]

Processing tickers:  91%|█████████ | 6323/6932 [22:35<02:09,  4.69it/s]

Processing tickers:  91%|█████████ | 6324/6932 [22:36<02:05,  4.83it/s]

Processing tickers:  91%|█████████ | 6325/6932 [22:36<02:08,  4.73it/s]

Processing tickers:  91%|█████████▏| 6326/6932 [22:36<02:19,  4.34it/s]

Processing tickers:  91%|█████████▏| 6327/6932 [22:36<02:15,  4.47it/s]

Processing tickers:  91%|█████████▏| 6328/6932 [22:37<02:15,  4.45it/s]

Processing tickers:  91%|█████████▏| 6329/6932 [22:37<02:11,  4.57it/s]

Processing tickers:  91%|█████████▏| 6330/6932 [22:37<02:09,  4.65it/s]

Processing tickers:  91%|█████████▏| 6331/6932 [22:37<02:10,  4.60it/s]

Processing tickers:  91%|█████████▏| 6332/6932 [22:37<02:11,  4.56it/s]

Processing tickers:  91%|█████████▏| 6333/6932 [22:38<02:10,  4.60it/s]

Processing tickers:  91%|█████████▏| 6334/6932 [22:38<02:07,  4.71it/s]

Processing tickers:  91%|█████████▏| 6335/6932 [22:38<02:05,  4.74it/s]

Processing tickers:  91%|█████████▏| 6336/6932 [22:38<02:07,  4.67it/s]

Processing tickers:  91%|█████████▏| 6337/6932 [22:38<02:05,  4.73it/s]

Processing tickers:  91%|█████████▏| 6338/6932 [22:39<02:04,  4.76it/s]

Processing tickers:  91%|█████████▏| 6339/6932 [22:39<02:06,  4.68it/s]

Processing tickers:  91%|█████████▏| 6340/6932 [22:39<02:05,  4.72it/s]

Processing tickers:  91%|█████████▏| 6341/6932 [22:39<02:04,  4.73it/s]

Processing tickers:  91%|█████████▏| 6342/6932 [22:40<02:03,  4.78it/s]

Processing tickers:  92%|█████████▏| 6343/6932 [22:40<02:03,  4.78it/s]

Processing tickers:  92%|█████████▏| 6344/6932 [22:40<02:04,  4.72it/s]

Processing tickers:  92%|█████████▏| 6345/6932 [22:40<02:01,  4.82it/s]

Processing tickers:  92%|█████████▏| 6346/6932 [22:40<02:01,  4.82it/s]

Processing tickers:  92%|█████████▏| 6347/6932 [22:41<02:01,  4.81it/s]

Processing tickers:  92%|█████████▏| 6348/6932 [22:41<02:01,  4.81it/s]

Processing tickers:  92%|█████████▏| 6349/6932 [22:41<02:04,  4.68it/s]

Processing tickers:  92%|█████████▏| 6350/6932 [22:41<02:05,  4.63it/s]

Processing tickers:  92%|█████████▏| 6351/6932 [22:41<02:01,  4.78it/s]

Processing tickers:  92%|█████████▏| 6352/6932 [22:42<02:03,  4.69it/s]

Processing tickers:  92%|█████████▏| 6353/6932 [22:42<02:02,  4.72it/s]

Processing tickers:  92%|█████████▏| 6354/6932 [22:42<02:01,  4.74it/s]

Processing tickers:  92%|█████████▏| 6355/6932 [22:42<02:04,  4.64it/s]

Processing tickers:  92%|█████████▏| 6356/6932 [22:42<02:02,  4.70it/s]

Processing tickers:  92%|█████████▏| 6357/6932 [22:43<02:01,  4.72it/s]

Processing tickers:  92%|█████████▏| 6358/6932 [22:43<02:00,  4.76it/s]

Processing tickers:  92%|█████████▏| 6359/6932 [22:43<02:00,  4.77it/s]

Processing tickers:  92%|█████████▏| 6360/6932 [22:43<01:59,  4.79it/s]

Processing tickers:  92%|█████████▏| 6361/6932 [22:44<02:01,  4.69it/s]

Processing tickers:  92%|█████████▏| 6362/6932 [22:44<02:00,  4.72it/s]

Processing tickers:  92%|█████████▏| 6363/6932 [22:44<02:00,  4.74it/s]

Processing tickers:  92%|█████████▏| 6364/6932 [22:44<02:02,  4.63it/s]

Processing tickers:  92%|█████████▏| 6365/6932 [22:44<02:00,  4.70it/s]

Processing tickers:  92%|█████████▏| 6366/6932 [22:45<01:59,  4.73it/s]

Processing tickers:  92%|█████████▏| 6367/6932 [22:45<01:59,  4.73it/s]

Processing tickers:  92%|█████████▏| 6368/6932 [22:45<02:00,  4.67it/s]

Processing tickers:  92%|█████████▏| 6369/6932 [22:45<02:00,  4.65it/s]

Processing tickers:  92%|█████████▏| 6370/6932 [22:45<01:58,  4.73it/s]

Processing tickers:  92%|█████████▏| 6371/6932 [22:46<02:00,  4.67it/s]

Processing tickers:  92%|█████████▏| 6372/6932 [22:46<02:01,  4.60it/s]

Processing tickers:  92%|█████████▏| 6373/6932 [22:46<01:59,  4.66it/s]

Processing tickers:  92%|█████████▏| 6374/6932 [22:46<01:58,  4.72it/s]

Processing tickers:  92%|█████████▏| 6375/6932 [22:47<02:10,  4.27it/s]

Processing tickers:  92%|█████████▏| 6376/6932 [22:47<02:05,  4.43it/s]

Processing tickers:  92%|█████████▏| 6377/6932 [22:47<02:00,  4.60it/s]

Processing tickers:  92%|█████████▏| 6378/6932 [22:47<02:00,  4.58it/s]

Processing tickers:  92%|█████████▏| 6379/6932 [22:47<01:59,  4.64it/s]

Processing tickers:  92%|█████████▏| 6380/6932 [22:48<01:57,  4.70it/s]

Processing tickers:  92%|█████████▏| 6381/6932 [22:48<01:56,  4.73it/s]

Processing tickers:  92%|█████████▏| 6382/6932 [22:48<01:55,  4.76it/s]

Processing tickers:  92%|█████████▏| 6383/6932 [22:48<01:54,  4.78it/s]

Processing tickers:  92%|█████████▏| 6384/6932 [22:48<01:55,  4.74it/s]

Processing tickers:  92%|█████████▏| 6385/6932 [22:49<01:53,  4.81it/s]

Processing tickers:  92%|█████████▏| 6386/6932 [22:49<01:53,  4.80it/s]

Processing tickers:  92%|█████████▏| 6387/6932 [22:49<01:56,  4.70it/s]

Processing tickers:  92%|█████████▏| 6388/6932 [22:49<01:55,  4.73it/s]

Processing tickers:  92%|█████████▏| 6389/6932 [22:50<01:54,  4.75it/s]

Processing tickers:  92%|█████████▏| 6390/6932 [22:50<01:53,  4.77it/s]

Processing tickers:  92%|█████████▏| 6391/6932 [22:50<01:55,  4.70it/s]

Processing tickers:  92%|█████████▏| 6392/6932 [22:50<01:52,  4.80it/s]

Processing tickers:  92%|█████████▏| 6393/6932 [22:50<01:56,  4.64it/s]

Processing tickers:  92%|█████████▏| 6394/6932 [22:51<01:53,  4.73it/s]

Processing tickers:  92%|█████████▏| 6395/6932 [22:51<01:52,  4.76it/s]

Processing tickers:  92%|█████████▏| 6396/6932 [22:51<01:54,  4.67it/s]

Processing tickers:  92%|█████████▏| 6397/6932 [22:51<01:53,  4.71it/s]

Processing tickers:  92%|█████████▏| 6398/6932 [22:51<01:52,  4.73it/s]

Processing tickers:  92%|█████████▏| 6399/6932 [22:52<01:52,  4.75it/s]

Processing tickers:  92%|█████████▏| 6400/6932 [22:52<01:54,  4.66it/s]

Processing tickers:  92%|█████████▏| 6401/6932 [22:52<01:55,  4.59it/s]

Processing tickers:  92%|█████████▏| 6402/6932 [22:52<01:53,  4.67it/s]

Processing tickers:  92%|█████████▏| 6403/6932 [22:52<01:52,  4.69it/s]

Processing tickers:  92%|█████████▏| 6404/6932 [22:53<01:56,  4.54it/s]

Processing tickers:  92%|█████████▏| 6405/6932 [22:53<01:54,  4.59it/s]

Processing tickers:  92%|█████████▏| 6406/6932 [22:53<01:52,  4.67it/s]

Processing tickers:  92%|█████████▏| 6407/6932 [22:53<01:51,  4.71it/s]

Processing tickers:  92%|█████████▏| 6408/6932 [22:54<01:50,  4.74it/s]

Processing tickers:  92%|█████████▏| 6409/6932 [22:54<01:52,  4.65it/s]

Processing tickers:  92%|█████████▏| 6410/6932 [22:54<01:51,  4.70it/s]

Processing tickers:  92%|█████████▏| 6411/6932 [22:54<01:50,  4.70it/s]

Processing tickers:  92%|█████████▏| 6412/6932 [22:54<01:50,  4.71it/s]

Processing tickers:  93%|█████████▎| 6413/6932 [22:55<01:48,  4.78it/s]

Processing tickers:  93%|█████████▎| 6414/6932 [22:55<01:50,  4.68it/s]

Processing tickers:  93%|█████████▎| 6415/6932 [22:55<01:49,  4.72it/s]

Processing tickers:  93%|█████████▎| 6416/6932 [22:55<01:51,  4.64it/s]

Processing tickers:  93%|█████████▎| 6417/6932 [22:55<01:49,  4.70it/s]

Processing tickers:  93%|█████████▎| 6418/6932 [22:56<01:48,  4.73it/s]

Processing tickers:  93%|█████████▎| 6419/6932 [22:56<01:47,  4.75it/s]

Processing tickers:  93%|█████████▎| 6420/6932 [22:56<01:47,  4.77it/s]

Processing tickers:  93%|█████████▎| 6421/6932 [22:56<01:50,  4.63it/s]

Processing tickers:  93%|█████████▎| 6422/6932 [22:57<01:47,  4.73it/s]

Processing tickers:  93%|█████████▎| 6423/6932 [22:57<01:47,  4.75it/s]

Processing tickers:  93%|█████████▎| 6424/6932 [22:57<01:48,  4.66it/s]

Processing tickers:  93%|█████████▎| 6425/6932 [22:57<01:47,  4.70it/s]

Processing tickers:  93%|█████████▎| 6426/6932 [22:57<01:46,  4.74it/s]

Processing tickers:  93%|█████████▎| 6427/6932 [22:58<01:48,  4.67it/s]

Processing tickers:  93%|█████████▎| 6428/6932 [22:58<01:47,  4.70it/s]

Processing tickers:  93%|█████████▎| 6429/6932 [22:58<01:46,  4.74it/s]

Processing tickers:  93%|█████████▎| 6430/6932 [22:58<01:45,  4.77it/s]

Processing tickers:  93%|█████████▎| 6431/6932 [22:58<01:47,  4.68it/s]

Processing tickers:  93%|█████████▎| 6432/6932 [22:59<01:46,  4.71it/s]

Processing tickers:  93%|█████████▎| 6433/6932 [22:59<01:45,  4.74it/s]

Processing tickers:  93%|█████████▎| 6434/6932 [22:59<01:47,  4.65it/s]

Processing tickers:  93%|█████████▎| 6435/6932 [22:59<01:45,  4.70it/s]

Processing tickers:  93%|█████████▎| 6436/6932 [23:00<01:44,  4.74it/s]

Processing tickers:  93%|█████████▎| 6437/6932 [23:00<01:48,  4.57it/s]

Processing tickers:  93%|█████████▎| 6438/6932 [23:00<01:44,  4.74it/s]

Processing tickers:  93%|█████████▎| 6439/6932 [23:00<01:45,  4.65it/s]

Processing tickers:  93%|█████████▎| 6440/6932 [23:00<01:44,  4.70it/s]

Processing tickers:  93%|█████████▎| 6441/6932 [23:01<01:43,  4.73it/s]

Processing tickers:  93%|█████████▎| 6442/6932 [23:01<01:43,  4.75it/s]

Processing tickers:  93%|█████████▎| 6443/6932 [23:01<01:42,  4.76it/s]

Processing tickers:  93%|█████████▎| 6444/6932 [23:01<01:42,  4.75it/s]

Processing tickers:  93%|█████████▎| 6445/6932 [23:01<01:41,  4.80it/s]

Processing tickers:  93%|█████████▎| 6446/6932 [23:02<01:41,  4.80it/s]

Processing tickers:  93%|█████████▎| 6447/6932 [23:02<01:43,  4.69it/s]

Processing tickers:  93%|█████████▎| 6448/6932 [23:02<01:42,  4.70it/s]

Processing tickers:  93%|█████████▎| 6449/6932 [23:02<01:41,  4.75it/s]

Processing tickers:  93%|█████████▎| 6450/6932 [23:02<01:42,  4.72it/s]

Processing tickers:  93%|█████████▎| 6451/6932 [23:03<01:40,  4.78it/s]

Processing tickers:  93%|█████████▎| 6452/6932 [23:03<01:39,  4.80it/s]

Processing tickers:  93%|█████████▎| 6453/6932 [23:03<01:40,  4.77it/s]

Processing tickers:  93%|█████████▎| 6454/6932 [23:03<01:39,  4.81it/s]

Processing tickers:  93%|█████████▎| 6455/6932 [23:04<01:39,  4.81it/s]

Processing tickers:  93%|█████████▎| 6456/6932 [23:04<01:41,  4.70it/s]

Processing tickers:  93%|█████████▎| 6457/6932 [23:04<01:40,  4.74it/s]

Processing tickers:  93%|█████████▎| 6458/6932 [23:04<01:39,  4.76it/s]

Processing tickers:  93%|█████████▎| 6459/6932 [23:04<01:39,  4.77it/s]

Processing tickers:  93%|█████████▎| 6460/6932 [23:05<01:38,  4.79it/s]

Processing tickers:  93%|█████████▎| 6461/6932 [23:05<01:38,  4.78it/s]

Processing tickers:  93%|█████████▎| 6462/6932 [23:05<01:38,  4.79it/s]

Processing tickers:  93%|█████████▎| 6463/6932 [23:05<01:37,  4.79it/s]

Processing tickers:  93%|█████████▎| 6464/6932 [23:05<01:37,  4.80it/s]

Processing tickers:  93%|█████████▎| 6465/6932 [23:06<01:37,  4.80it/s]

Processing tickers:  93%|█████████▎| 6466/6932 [23:06<01:37,  4.80it/s]

Processing tickers:  93%|█████████▎| 6467/6932 [23:06<01:36,  4.80it/s]

Processing tickers:  93%|█████████▎| 6468/6932 [23:06<01:36,  4.80it/s]

Processing tickers:  93%|█████████▎| 6469/6932 [23:06<01:34,  4.92it/s]

Processing tickers:  93%|█████████▎| 6470/6932 [23:07<01:34,  4.88it/s]

Processing tickers:  93%|█████████▎| 6471/6932 [23:07<01:37,  4.73it/s]

Processing tickers:  93%|█████████▎| 6472/6932 [23:07<01:38,  4.68it/s]

Processing tickers:  93%|█████████▎| 6473/6932 [23:07<01:37,  4.70it/s]

Processing tickers:  93%|█████████▎| 6474/6932 [23:08<01:36,  4.73it/s]

Processing tickers:  93%|█████████▎| 6475/6932 [23:08<01:35,  4.76it/s]

Processing tickers:  93%|█████████▎| 6476/6932 [23:08<01:37,  4.68it/s]

Processing tickers:  93%|█████████▎| 6477/6932 [23:08<01:38,  4.60it/s]

Processing tickers:  93%|█████████▎| 6478/6932 [23:08<01:36,  4.69it/s]

Processing tickers:  93%|█████████▎| 6479/6932 [23:09<01:39,  4.54it/s]

Processing tickers:  93%|█████████▎| 6480/6932 [23:09<01:38,  4.61it/s]

Processing tickers:  93%|█████████▎| 6481/6932 [23:09<01:36,  4.68it/s]

Processing tickers:  94%|█████████▎| 6482/6932 [23:09<01:35,  4.69it/s]

Processing tickers:  94%|█████████▎| 6483/6932 [23:09<01:34,  4.74it/s]

Processing tickers:  94%|█████████▎| 6484/6932 [23:10<01:33,  4.77it/s]

Processing tickers:  94%|█████████▎| 6485/6932 [23:10<01:33,  4.78it/s]

Processing tickers:  94%|█████████▎| 6486/6932 [23:10<01:35,  4.66it/s]

Processing tickers:  94%|█████████▎| 6487/6932 [23:10<01:34,  4.69it/s]

Processing tickers:  94%|█████████▎| 6488/6932 [23:10<01:34,  4.69it/s]

Processing tickers:  94%|█████████▎| 6489/6932 [23:11<01:32,  4.79it/s]

Processing tickers:  94%|█████████▎| 6490/6932 [23:11<01:32,  4.80it/s]

Processing tickers:  94%|█████████▎| 6491/6932 [23:11<01:31,  4.80it/s]

Processing tickers:  94%|█████████▎| 6492/6932 [23:11<01:34,  4.66it/s]

Processing tickers:  94%|█████████▎| 6493/6932 [23:12<01:32,  4.74it/s]

Processing tickers:  94%|█████████▎| 6494/6932 [23:12<01:34,  4.66it/s]

Processing tickers:  94%|█████████▎| 6495/6932 [23:12<01:30,  4.81it/s]

Processing tickers:  94%|█████████▎| 6496/6932 [23:12<01:32,  4.70it/s]

Processing tickers:  94%|█████████▎| 6497/6932 [23:12<01:32,  4.73it/s]

Processing tickers:  94%|█████████▎| 6498/6932 [23:13<01:31,  4.75it/s]

Processing tickers:  94%|█████████▍| 6499/6932 [23:13<01:30,  4.76it/s]

Processing tickers:  94%|█████████▍| 6500/6932 [23:13<01:30,  4.78it/s]

Processing tickers:  94%|█████████▍| 6501/6932 [23:13<01:30,  4.76it/s]

Processing tickers:  94%|█████████▍| 6502/6932 [23:13<01:30,  4.74it/s]

Processing tickers:  94%|█████████▍| 6503/6932 [23:14<01:28,  4.83it/s]

Processing tickers:  94%|█████████▍| 6504/6932 [23:14<01:31,  4.66it/s]

Processing tickers:  94%|█████████▍| 6505/6932 [23:14<01:30,  4.71it/s]

Processing tickers:  94%|█████████▍| 6506/6932 [23:14<01:28,  4.79it/s]

Processing tickers:  94%|█████████▍| 6507/6932 [23:14<01:28,  4.80it/s]

Processing tickers:  94%|█████████▍| 6508/6932 [23:15<01:28,  4.80it/s]

Processing tickers:  94%|█████████▍| 6509/6932 [23:15<01:28,  4.80it/s]

Processing tickers:  94%|█████████▍| 6510/6932 [23:15<01:29,  4.74it/s]

Processing tickers:  94%|█████████▍| 6511/6932 [23:15<01:27,  4.82it/s]

Processing tickers:  94%|█████████▍| 6512/6932 [23:16<01:29,  4.71it/s]

Processing tickers:  94%|█████████▍| 6513/6932 [23:16<01:28,  4.73it/s]

Processing tickers:  94%|█████████▍| 6514/6932 [23:16<01:27,  4.76it/s]

Processing tickers:  94%|█████████▍| 6515/6932 [23:16<01:27,  4.77it/s]

Processing tickers:  94%|█████████▍| 6516/6932 [23:16<01:26,  4.78it/s]

Processing tickers:  94%|█████████▍| 6517/6932 [23:17<01:26,  4.79it/s]

Processing tickers:  94%|█████████▍| 6518/6932 [23:17<01:27,  4.72it/s]

Processing tickers:  94%|█████████▍| 6519/6932 [23:17<01:25,  4.83it/s]

Processing tickers:  94%|█████████▍| 6520/6932 [23:17<01:25,  4.82it/s]

Processing tickers:  94%|█████████▍| 6521/6932 [23:17<01:25,  4.82it/s]

Processing tickers:  94%|█████████▍| 6522/6932 [23:18<01:25,  4.82it/s]

Processing tickers:  94%|█████████▍| 6523/6932 [23:18<01:26,  4.72it/s]

Processing tickers:  94%|█████████▍| 6524/6932 [23:18<01:26,  4.74it/s]

Processing tickers:  94%|█████████▍| 6525/6932 [23:18<01:25,  4.76it/s]

Processing tickers:  94%|█████████▍| 6526/6932 [23:18<01:25,  4.77it/s]

Processing tickers:  94%|█████████▍| 6527/6932 [23:19<01:25,  4.76it/s]

Processing tickers:  94%|█████████▍| 6528/6932 [23:19<01:27,  4.64it/s]

Processing tickers:  94%|█████████▍| 6529/6932 [23:19<01:25,  4.74it/s]

Processing tickers:  94%|█████████▍| 6530/6932 [23:19<01:26,  4.66it/s]

Processing tickers:  94%|█████████▍| 6531/6932 [23:20<01:25,  4.70it/s]

Processing tickers:  94%|█████████▍| 6532/6932 [23:20<01:25,  4.66it/s]

Processing tickers:  94%|█████████▍| 6533/6932 [23:20<01:23,  4.78it/s]

Processing tickers:  94%|█████████▍| 6534/6932 [23:20<01:23,  4.78it/s]

Processing tickers:  94%|█████████▍| 6535/6932 [23:20<01:22,  4.79it/s]

Processing tickers:  94%|█████████▍| 6536/6932 [23:21<01:22,  4.80it/s]

Processing tickers:  94%|█████████▍| 6537/6932 [23:21<01:22,  4.80it/s]

Processing tickers:  94%|█████████▍| 6538/6932 [23:21<01:23,  4.70it/s]

Processing tickers:  94%|█████████▍| 6539/6932 [23:21<01:24,  4.63it/s]

Processing tickers:  94%|█████████▍| 6540/6932 [23:21<01:21,  4.79it/s]

Processing tickers:  94%|█████████▍| 6541/6932 [23:22<01:23,  4.69it/s]

Processing tickers:  94%|█████████▍| 6542/6932 [23:22<01:22,  4.73it/s]

Processing tickers:  94%|█████████▍| 6543/6932 [23:22<01:21,  4.75it/s]

Processing tickers:  94%|█████████▍| 6544/6932 [23:22<01:23,  4.66it/s]

Processing tickers:  94%|█████████▍| 6545/6932 [23:23<01:22,  4.70it/s]

Processing tickers:  94%|█████████▍| 6546/6932 [23:23<01:21,  4.71it/s]

Processing tickers:  94%|█████████▍| 6547/6932 [23:23<01:22,  4.69it/s]

Processing tickers:  94%|█████████▍| 6548/6932 [23:23<01:22,  4.68it/s]

Processing tickers:  94%|█████████▍| 6549/6932 [23:23<01:21,  4.71it/s]

Processing tickers:  94%|█████████▍| 6550/6932 [23:24<01:20,  4.74it/s]

Processing tickers:  95%|█████████▍| 6551/6932 [23:24<01:20,  4.75it/s]

Processing tickers:  95%|█████████▍| 6552/6932 [23:24<01:19,  4.78it/s]

Processing tickers:  95%|█████████▍| 6553/6932 [23:24<01:19,  4.79it/s]

Processing tickers:  95%|█████████▍| 6554/6932 [23:24<01:20,  4.71it/s]

Processing tickers:  95%|█████████▍| 6555/6932 [23:25<01:19,  4.73it/s]

Processing tickers:  95%|█████████▍| 6556/6932 [23:25<01:19,  4.73it/s]

Processing tickers:  95%|█████████▍| 6557/6932 [23:25<01:18,  4.75it/s]

Processing tickers:  95%|█████████▍| 6558/6932 [23:25<01:18,  4.76it/s]

Processing tickers:  95%|█████████▍| 6559/6932 [23:25<01:18,  4.74it/s]

Processing tickers:  95%|█████████▍| 6560/6932 [23:26<01:19,  4.69it/s]

Processing tickers:  95%|█████████▍| 6561/6932 [23:26<01:19,  4.69it/s]

Processing tickers:  95%|█████████▍| 6562/6932 [23:26<01:17,  4.77it/s]

Processing tickers:  95%|█████████▍| 6563/6932 [23:26<01:21,  4.51it/s]

Processing tickers:  95%|█████████▍| 6564/6932 [23:27<01:21,  4.53it/s]

Processing tickers:  95%|█████████▍| 6565/6932 [23:27<01:19,  4.60it/s]

Processing tickers:  95%|█████████▍| 6566/6932 [23:27<01:19,  4.59it/s]

Processing tickers:  95%|█████████▍| 6567/6932 [23:27<01:18,  4.67it/s]

Processing tickers:  95%|█████████▍| 6568/6932 [23:27<01:18,  4.62it/s]

Processing tickers:  95%|█████████▍| 6569/6932 [23:28<01:17,  4.67it/s]

Processing tickers:  95%|█████████▍| 6570/6932 [23:28<01:16,  4.71it/s]

Processing tickers:  95%|█████████▍| 6571/6932 [23:28<01:18,  4.63it/s]

Processing tickers:  95%|█████████▍| 6572/6932 [23:28<01:16,  4.69it/s]

Processing tickers:  95%|█████████▍| 6573/6932 [23:28<01:16,  4.67it/s]

Processing tickers:  95%|█████████▍| 6574/6932 [23:29<01:17,  4.64it/s]

Processing tickers:  95%|█████████▍| 6575/6932 [23:29<01:15,  4.71it/s]

Processing tickers:  95%|█████████▍| 6576/6932 [23:29<01:15,  4.73it/s]

Processing tickers:  95%|█████████▍| 6577/6932 [23:29<01:15,  4.67it/s]

Processing tickers:  95%|█████████▍| 6578/6932 [23:30<01:17,  4.56it/s]

Processing tickers:  95%|█████████▍| 6579/6932 [23:30<01:15,  4.68it/s]

Processing tickers:  95%|█████████▍| 6580/6932 [23:30<01:16,  4.61it/s]

Processing tickers:  95%|█████████▍| 6581/6932 [23:30<01:15,  4.67it/s]

Processing tickers:  95%|█████████▍| 6582/6932 [23:30<01:16,  4.57it/s]

Processing tickers:  95%|█████████▍| 6583/6932 [23:31<01:14,  4.68it/s]

Processing tickers:  95%|█████████▍| 6584/6932 [23:31<01:15,  4.61it/s]

Processing tickers:  95%|█████████▍| 6585/6932 [23:31<01:14,  4.67it/s]

Processing tickers:  95%|█████████▌| 6586/6932 [23:31<01:13,  4.71it/s]

Processing tickers:  95%|█████████▌| 6587/6932 [23:31<01:12,  4.74it/s]

Processing tickers:  95%|█████████▌| 6588/6932 [23:32<01:13,  4.67it/s]

Processing tickers:  95%|█████████▌| 6589/6932 [23:32<01:13,  4.67it/s]

Processing tickers:  95%|█████████▌| 6590/6932 [23:32<01:12,  4.74it/s]

Processing tickers:  95%|█████████▌| 6591/6932 [23:32<01:12,  4.69it/s]

Processing tickers:  95%|█████████▌| 6592/6932 [23:33<01:12,  4.69it/s]

Processing tickers:  95%|█████████▌| 6593/6932 [23:33<01:11,  4.72it/s]

Processing tickers:  95%|█████████▌| 6594/6932 [23:33<01:11,  4.74it/s]

Processing tickers:  95%|█████████▌| 6595/6932 [23:33<01:10,  4.76it/s]

Processing tickers:  95%|█████████▌| 6596/6932 [23:33<01:12,  4.66it/s]

Processing tickers:  95%|█████████▌| 6597/6932 [23:34<01:11,  4.70it/s]

Processing tickers:  95%|█████████▌| 6598/6932 [23:34<01:11,  4.69it/s]

Processing tickers:  95%|█████████▌| 6599/6932 [23:34<01:09,  4.76it/s]

Processing tickers:  95%|█████████▌| 6600/6932 [23:34<01:09,  4.77it/s]

Processing tickers:  95%|█████████▌| 6601/6932 [23:34<01:09,  4.78it/s]

Processing tickers:  95%|█████████▌| 6602/6932 [23:35<01:09,  4.72it/s]

Processing tickers:  95%|█████████▌| 6603/6932 [23:35<01:08,  4.82it/s]

Processing tickers:  95%|█████████▌| 6604/6932 [23:35<01:08,  4.81it/s]

Processing tickers:  95%|█████████▌| 6605/6932 [23:35<01:08,  4.81it/s]

Processing tickers:  95%|█████████▌| 6606/6932 [23:35<01:07,  4.81it/s]

Processing tickers:  95%|█████████▌| 6607/6932 [23:36<01:08,  4.78it/s]

Processing tickers:  95%|█████████▌| 6608/6932 [23:36<01:07,  4.82it/s]

Processing tickers:  95%|█████████▌| 6609/6932 [23:36<01:08,  4.70it/s]

Processing tickers:  95%|█████████▌| 6610/6932 [23:36<01:08,  4.73it/s]

Processing tickers:  95%|█████████▌| 6611/6932 [23:37<01:07,  4.76it/s]

Processing tickers:  95%|█████████▌| 6612/6932 [23:37<01:07,  4.76it/s]

Processing tickers:  95%|█████████▌| 6613/6932 [23:37<01:06,  4.78it/s]

Processing tickers:  95%|█████████▌| 6614/6932 [23:37<01:07,  4.68it/s]

Processing tickers:  95%|█████████▌| 6615/6932 [23:37<01:07,  4.69it/s]

Processing tickers:  95%|█████████▌| 6616/6932 [23:38<01:06,  4.75it/s]

Processing tickers:  95%|█████████▌| 6617/6932 [23:38<01:06,  4.77it/s]

Processing tickers:  95%|█████████▌| 6618/6932 [23:38<01:05,  4.78it/s]

Processing tickers:  95%|█████████▌| 6619/6932 [23:38<01:05,  4.79it/s]

Processing tickers:  95%|█████████▌| 6620/6932 [23:38<01:04,  4.81it/s]

Processing tickers:  96%|█████████▌| 6621/6932 [23:39<01:04,  4.82it/s]

Processing tickers:  96%|█████████▌| 6622/6932 [23:39<01:05,  4.72it/s]

Processing tickers:  96%|█████████▌| 6623/6932 [23:39<01:04,  4.76it/s]

Processing tickers:  96%|█████████▌| 6624/6932 [23:39<01:05,  4.67it/s]

Processing tickers:  96%|█████████▌| 6625/6932 [23:39<01:05,  4.71it/s]

Processing tickers:  96%|█████████▌| 6626/6932 [23:40<01:04,  4.74it/s]

Processing tickers:  96%|█████████▌| 6627/6932 [23:40<01:04,  4.76it/s]

Processing tickers:  96%|█████████▌| 6628/6932 [23:40<01:04,  4.69it/s]

Processing tickers:  96%|█████████▌| 6629/6932 [23:40<01:03,  4.81it/s]

Processing tickers:  96%|█████████▌| 6630/6932 [23:41<01:03,  4.74it/s]

Processing tickers:  96%|█████████▌| 6631/6932 [23:41<01:03,  4.72it/s]

Processing tickers:  96%|█████████▌| 6632/6932 [23:41<01:03,  4.71it/s]

Processing tickers:  96%|█████████▌| 6633/6932 [23:41<01:03,  4.73it/s]

Processing tickers:  96%|█████████▌| 6634/6932 [23:41<01:02,  4.79it/s]

Processing tickers:  96%|█████████▌| 6635/6932 [23:42<01:01,  4.80it/s]

Processing tickers:  96%|█████████▌| 6636/6932 [23:42<01:01,  4.80it/s]

Processing tickers:  96%|█████████▌| 6637/6932 [23:42<00:59,  4.92it/s]

Processing tickers:  96%|█████████▌| 6638/6932 [23:42<01:00,  4.89it/s]

Processing tickers:  96%|█████████▌| 6639/6932 [23:42<01:01,  4.75it/s]

Processing tickers:  96%|█████████▌| 6640/6932 [23:43<01:01,  4.77it/s]

Processing tickers:  96%|█████████▌| 6641/6932 [23:43<01:00,  4.78it/s]

Processing tickers:  96%|█████████▌| 6642/6932 [23:43<01:00,  4.78it/s]

Processing tickers:  96%|█████████▌| 6643/6932 [23:43<01:01,  4.72it/s]

Processing tickers:  96%|█████████▌| 6644/6932 [23:43<01:01,  4.70it/s]

Processing tickers:  96%|█████████▌| 6645/6932 [23:44<01:01,  4.70it/s]

Processing tickers:  96%|█████████▌| 6646/6932 [23:44<01:00,  4.73it/s]

Processing tickers:  96%|█████████▌| 6647/6932 [23:44<00:59,  4.79it/s]

Processing tickers:  96%|█████████▌| 6648/6932 [23:44<00:59,  4.80it/s]

Processing tickers:  96%|█████████▌| 6649/6932 [23:45<00:59,  4.72it/s]

Processing tickers:  96%|█████████▌| 6650/6932 [23:45<01:01,  4.62it/s]

Processing tickers:  96%|█████████▌| 6651/6932 [23:45<01:00,  4.67it/s]

Processing tickers:  96%|█████████▌| 6652/6932 [23:45<00:59,  4.71it/s]

Processing tickers:  96%|█████████▌| 6653/6932 [23:45<00:59,  4.65it/s]

Processing tickers:  96%|█████████▌| 6654/6932 [23:46<00:58,  4.78it/s]

Processing tickers:  96%|█████████▌| 6655/6932 [23:46<00:57,  4.79it/s]

Processing tickers:  96%|█████████▌| 6656/6932 [23:46<00:59,  4.61it/s]

Processing tickers:  96%|█████████▌| 6657/6932 [23:46<00:59,  4.64it/s]

Processing tickers:  96%|█████████▌| 6658/6932 [23:46<00:59,  4.59it/s]

Processing tickers:  96%|█████████▌| 6659/6932 [23:47<00:58,  4.66it/s]

Processing tickers:  96%|█████████▌| 6660/6932 [23:47<00:58,  4.67it/s]

Processing tickers:  96%|█████████▌| 6661/6932 [23:47<00:57,  4.75it/s]

Processing tickers:  96%|█████████▌| 6662/6932 [23:47<00:56,  4.76it/s]

Processing tickers:  96%|█████████▌| 6663/6932 [23:48<00:57,  4.70it/s]

Processing tickers:  96%|█████████▌| 6664/6932 [23:48<00:57,  4.70it/s]

Processing tickers:  96%|█████████▌| 6665/6932 [23:48<00:56,  4.76it/s]

Processing tickers:  96%|█████████▌| 6666/6932 [23:48<00:56,  4.67it/s]

Processing tickers:  96%|█████████▌| 6667/6932 [23:48<00:56,  4.71it/s]

Processing tickers:  96%|█████████▌| 6668/6932 [23:49<00:55,  4.74it/s]

Processing tickers:  96%|█████████▌| 6669/6932 [23:49<00:55,  4.75it/s]

Processing tickers:  96%|█████████▌| 6670/6932 [23:49<00:54,  4.77it/s]

Processing tickers:  96%|█████████▌| 6671/6932 [23:49<00:54,  4.78it/s]

Processing tickers:  96%|█████████▌| 6672/6932 [23:49<00:54,  4.73it/s]

Processing tickers:  96%|█████████▋| 6673/6932 [23:50<00:53,  4.81it/s]

Processing tickers:  96%|█████████▋| 6674/6932 [23:50<00:54,  4.72it/s]

Processing tickers:  96%|█████████▋| 6675/6932 [23:50<00:53,  4.83it/s]

Processing tickers:  96%|█████████▋| 6676/6932 [23:50<00:54,  4.72it/s]

Processing tickers:  96%|█████████▋| 6677/6932 [23:50<00:53,  4.74it/s]

Processing tickers:  96%|█████████▋| 6678/6932 [23:51<00:53,  4.78it/s]

Processing tickers:  96%|█████████▋| 6679/6932 [23:51<00:52,  4.78it/s]

Processing tickers:  96%|█████████▋| 6680/6932 [23:51<00:53,  4.74it/s]

Processing tickers:  96%|█████████▋| 6681/6932 [23:51<00:52,  4.81it/s]

Processing tickers:  96%|█████████▋| 6682/6932 [23:51<00:52,  4.80it/s]

Processing tickers:  96%|█████████▋| 6683/6932 [23:52<00:51,  4.80it/s]

Processing tickers:  96%|█████████▋| 6684/6932 [23:52<00:51,  4.82it/s]

Processing tickers:  96%|█████████▋| 6685/6932 [23:52<00:50,  4.91it/s]

Processing tickers:  96%|█████████▋| 6686/6932 [23:52<00:50,  4.89it/s]

Processing tickers:  96%|█████████▋| 6687/6932 [23:53<00:50,  4.87it/s]

Processing tickers:  96%|█████████▋| 6688/6932 [23:53<00:51,  4.74it/s]

Processing tickers:  96%|█████████▋| 6689/6932 [23:53<00:51,  4.75it/s]

Processing tickers:  97%|█████████▋| 6690/6932 [23:53<00:51,  4.68it/s]

Processing tickers:  97%|█████████▋| 6691/6932 [23:53<00:50,  4.82it/s]

Processing tickers:  97%|█████████▋| 6692/6932 [23:54<00:50,  4.71it/s]

Processing tickers:  97%|█████████▋| 6693/6932 [23:54<00:51,  4.66it/s]

Processing tickers:  97%|█████████▋| 6694/6932 [23:54<00:50,  4.68it/s]

Processing tickers:  97%|█████████▋| 6695/6932 [23:54<00:50,  4.72it/s]

Processing tickers:  97%|█████████▋| 6696/6932 [23:54<00:49,  4.75it/s]

Processing tickers:  97%|█████████▋| 6697/6932 [23:55<00:49,  4.74it/s]

Processing tickers:  97%|█████████▋| 6698/6932 [23:55<00:49,  4.75it/s]

Processing tickers:  97%|█████████▋| 6699/6932 [23:55<00:48,  4.81it/s]

Processing tickers:  97%|█████████▋| 6700/6932 [23:55<00:48,  4.81it/s]

Processing tickers:  97%|█████████▋| 6701/6932 [23:55<00:48,  4.74it/s]

Processing tickers:  97%|█████████▋| 6702/6932 [23:56<00:48,  4.77it/s]

Processing tickers:  97%|█████████▋| 6703/6932 [23:56<00:47,  4.83it/s]

Processing tickers:  97%|█████████▋| 6704/6932 [23:56<00:47,  4.77it/s]

Processing tickers:  97%|█████████▋| 6705/6932 [23:56<00:46,  4.84it/s]

Processing tickers:  97%|█████████▋| 6706/6932 [23:57<00:47,  4.75it/s]

Processing tickers:  97%|█████████▋| 6707/6932 [23:57<00:47,  4.73it/s]

Processing tickers:  97%|█████████▋| 6708/6932 [23:57<00:46,  4.77it/s]

Processing tickers:  97%|█████████▋| 6709/6932 [23:57<00:46,  4.79it/s]

Processing tickers:  97%|█████████▋| 6710/6932 [23:57<00:46,  4.80it/s]

Processing tickers:  97%|█████████▋| 6711/6932 [23:58<00:46,  4.80it/s]

Processing tickers:  97%|█████████▋| 6712/6932 [23:58<00:45,  4.81it/s]

Processing tickers:  97%|█████████▋| 6713/6932 [23:58<00:45,  4.80it/s]

Processing tickers:  97%|█████████▋| 6714/6932 [23:58<00:46,  4.71it/s]

Processing tickers:  97%|█████████▋| 6715/6932 [23:58<00:45,  4.73it/s]

Processing tickers:  97%|█████████▋| 6716/6932 [23:59<00:45,  4.76it/s]

Processing tickers:  97%|█████████▋| 6717/6932 [23:59<00:45,  4.76it/s]

Processing tickers:  97%|█████████▋| 6718/6932 [23:59<00:44,  4.81it/s]

Processing tickers:  97%|█████████▋| 6719/6932 [23:59<00:46,  4.60it/s]

Processing tickers:  97%|█████████▋| 6720/6932 [23:59<00:45,  4.66it/s]

Processing tickers:  97%|█████████▋| 6721/6932 [24:00<00:44,  4.70it/s]

Processing tickers:  97%|█████████▋| 6722/6932 [24:00<00:44,  4.71it/s]

Processing tickers:  97%|█████████▋| 6723/6932 [24:00<00:43,  4.77it/s]

Processing tickers:  97%|█████████▋| 6724/6932 [24:00<00:45,  4.62it/s]

Processing tickers:  97%|█████████▋| 6725/6932 [24:01<00:44,  4.63it/s]

Processing tickers:  97%|█████████▋| 6726/6932 [24:01<00:44,  4.67it/s]

Processing tickers:  97%|█████████▋| 6727/6932 [24:01<00:43,  4.69it/s]

Processing tickers:  97%|█████████▋| 6728/6932 [24:01<00:43,  4.73it/s]

Processing tickers:  97%|█████████▋| 6729/6932 [24:01<00:42,  4.76it/s]

Processing tickers:  97%|█████████▋| 6730/6932 [24:02<00:42,  4.78it/s]

Processing tickers:  97%|█████████▋| 6731/6932 [24:02<00:43,  4.67it/s]

Processing tickers:  97%|█████████▋| 6732/6932 [24:02<00:42,  4.71it/s]

Processing tickers:  97%|█████████▋| 6733/6932 [24:02<00:41,  4.74it/s]

Processing tickers:  97%|█████████▋| 6734/6932 [24:02<00:41,  4.76it/s]

Processing tickers:  97%|█████████▋| 6735/6932 [24:03<00:41,  4.78it/s]

Processing tickers:  97%|█████████▋| 6736/6932 [24:03<00:41,  4.68it/s]

Processing tickers:  97%|█████████▋| 6737/6932 [24:03<00:41,  4.71it/s]

Processing tickers:  97%|█████████▋| 6738/6932 [24:03<00:40,  4.75it/s]

Processing tickers:  97%|█████████▋| 6739/6932 [24:04<00:40,  4.76it/s]

Processing tickers:  97%|█████████▋| 6740/6932 [24:04<00:40,  4.78it/s]

Processing tickers:  97%|█████████▋| 6741/6932 [24:04<00:39,  4.79it/s]

Processing tickers:  97%|█████████▋| 6742/6932 [24:04<00:40,  4.69it/s]

Processing tickers:  97%|█████████▋| 6743/6932 [24:04<00:39,  4.73it/s]

Processing tickers:  97%|█████████▋| 6744/6932 [24:05<00:39,  4.75it/s]

Processing tickers:  97%|█████████▋| 6745/6932 [24:05<00:39,  4.69it/s]

Processing tickers:  97%|█████████▋| 6746/6932 [24:05<00:39,  4.68it/s]

Processing tickers:  97%|█████████▋| 6747/6932 [24:05<00:39,  4.73it/s]

Processing tickers:  97%|█████████▋| 6748/6932 [24:05<00:38,  4.75it/s]

Processing tickers:  97%|█████████▋| 6749/6932 [24:06<00:38,  4.78it/s]

Processing tickers:  97%|█████████▋| 6750/6932 [24:06<00:38,  4.76it/s]

Processing tickers:  97%|█████████▋| 6751/6932 [24:06<00:37,  4.80it/s]

Processing tickers:  97%|█████████▋| 6752/6932 [24:06<00:38,  4.70it/s]

Processing tickers:  97%|█████████▋| 6753/6932 [24:06<00:38,  4.69it/s]

Processing tickers:  97%|█████████▋| 6754/6932 [24:07<00:38,  4.68it/s]

Processing tickers:  97%|█████████▋| 6755/6932 [24:07<00:36,  4.80it/s]

Processing tickers:  97%|█████████▋| 6756/6932 [24:07<00:37,  4.67it/s]

Processing tickers:  97%|█████████▋| 6757/6932 [24:07<00:36,  4.74it/s]

Processing tickers:  97%|█████████▋| 6758/6932 [24:08<00:36,  4.76it/s]

Processing tickers:  98%|█████████▊| 6759/6932 [24:08<00:37,  4.66it/s]

Processing tickers:  98%|█████████▊| 6760/6932 [24:08<00:36,  4.71it/s]

Processing tickers:  98%|█████████▊| 6761/6932 [24:08<00:35,  4.83it/s]

Processing tickers:  98%|█████████▊| 6762/6932 [24:08<00:35,  4.75it/s]

Processing tickers:  98%|█████████▊| 6763/6932 [24:09<00:35,  4.69it/s]

Processing tickers:  98%|█████████▊| 6764/6932 [24:09<00:34,  4.81it/s]

Processing tickers:  98%|█████████▊| 6765/6932 [24:09<00:36,  4.61it/s]

Processing tickers:  98%|█████████▊| 6766/6932 [24:09<00:36,  4.58it/s]

Processing tickers:  98%|█████████▊| 6767/6932 [24:09<00:36,  4.56it/s]

Processing tickers:  98%|█████████▊| 6768/6932 [24:10<00:35,  4.63it/s]

Processing tickers:  98%|█████████▊| 6769/6932 [24:10<00:35,  4.59it/s]

Processing tickers:  98%|█████████▊| 6770/6932 [24:10<00:34,  4.66it/s]

Processing tickers:  98%|█████████▊| 6771/6932 [24:10<00:34,  4.70it/s]

Processing tickers:  98%|█████████▊| 6772/6932 [24:11<00:33,  4.71it/s]

Processing tickers:  98%|█████████▊| 6773/6932 [24:11<00:33,  4.76it/s]

Processing tickers:  98%|█████████▊| 6774/6932 [24:11<00:33,  4.77it/s]

Processing tickers:  98%|█████████▊| 6775/6932 [24:11<00:33,  4.68it/s]

Processing tickers:  98%|█████████▊| 6776/6932 [24:11<00:33,  4.72it/s]

Processing tickers:  98%|█████████▊| 6777/6932 [24:12<00:33,  4.63it/s]

Processing tickers:  98%|█████████▊| 6778/6932 [24:12<00:32,  4.68it/s]

Processing tickers:  98%|█████████▊| 6779/6932 [24:12<00:32,  4.72it/s]

Processing tickers:  98%|█████████▊| 6780/6932 [24:12<00:31,  4.75it/s]

Processing tickers:  98%|█████████▊| 6781/6932 [24:12<00:31,  4.77it/s]

Processing tickers:  98%|█████████▊| 6782/6932 [24:13<00:31,  4.78it/s]

Processing tickers:  98%|█████████▊| 6783/6932 [24:13<00:31,  4.75it/s]

Processing tickers:  98%|█████████▊| 6784/6932 [24:13<00:30,  4.80it/s]

Processing tickers:  98%|█████████▊| 6785/6932 [24:13<00:30,  4.80it/s]

Processing tickers:  98%|█████████▊| 6786/6932 [24:13<00:31,  4.70it/s]

Processing tickers:  98%|█████████▊| 6787/6932 [24:14<00:30,  4.71it/s]

Processing tickers:  98%|█████████▊| 6788/6932 [24:14<00:30,  4.75it/s]

Processing tickers:  98%|█████████▊| 6789/6932 [24:14<00:30,  4.75it/s]

Processing tickers:  98%|█████████▊| 6790/6932 [24:14<00:29,  4.79it/s]

Processing tickers:  98%|█████████▊| 6791/6932 [24:15<00:29,  4.79it/s]

Processing tickers:  98%|█████████▊| 6792/6932 [24:15<00:29,  4.80it/s]

Processing tickers:  98%|█████████▊| 6793/6932 [24:15<00:29,  4.69it/s]

Processing tickers:  98%|█████████▊| 6794/6932 [24:15<00:29,  4.73it/s]

Processing tickers:  98%|█████████▊| 6795/6932 [24:15<00:28,  4.75it/s]

Processing tickers:  98%|█████████▊| 6796/6932 [24:16<00:28,  4.77it/s]

Processing tickers:  98%|█████████▊| 6797/6932 [24:16<00:28,  4.77it/s]

Processing tickers:  98%|█████████▊| 6798/6932 [24:16<00:27,  4.79it/s]

Processing tickers:  98%|█████████▊| 6799/6932 [24:16<00:27,  4.79it/s]

Processing tickers:  98%|█████████▊| 6800/6932 [24:16<00:27,  4.80it/s]

Processing tickers:  98%|█████████▊| 6801/6932 [24:17<00:27,  4.80it/s]

Processing tickers:  98%|█████████▊| 6802/6932 [24:17<00:27,  4.80it/s]

Processing tickers:  98%|█████████▊| 6803/6932 [24:17<00:27,  4.72it/s]

Processing tickers:  98%|█████████▊| 6804/6932 [24:17<00:26,  4.83it/s]

Processing tickers:  98%|█████████▊| 6805/6932 [24:17<00:26,  4.83it/s]

Processing tickers:  98%|█████████▊| 6806/6932 [24:18<00:26,  4.83it/s]

Processing tickers:  98%|█████████▊| 6807/6932 [24:18<00:26,  4.72it/s]

Processing tickers:  98%|█████████▊| 6808/6932 [24:18<00:25,  4.82it/s]

Processing tickers:  98%|█████████▊| 6809/6932 [24:18<00:25,  4.74it/s]

Processing tickers:  98%|█████████▊| 6810/6932 [24:18<00:25,  4.77it/s]

Processing tickers:  98%|█████████▊| 6811/6932 [24:19<00:25,  4.78it/s]

Processing tickers:  98%|█████████▊| 6812/6932 [24:19<00:25,  4.68it/s]

Processing tickers:  98%|█████████▊| 6813/6932 [24:19<00:25,  4.70it/s]

Processing tickers:  98%|█████████▊| 6814/6932 [24:19<00:24,  4.74it/s]

Processing tickers:  98%|█████████▊| 6815/6932 [24:20<00:24,  4.73it/s]

Processing tickers:  98%|█████████▊| 6816/6932 [24:20<00:24,  4.80it/s]

Processing tickers:  98%|█████████▊| 6817/6932 [24:20<00:24,  4.69it/s]

Processing tickers:  98%|█████████▊| 6818/6932 [24:20<00:23,  4.83it/s]

Processing tickers:  98%|█████████▊| 6819/6932 [24:20<00:23,  4.71it/s]

Processing tickers:  98%|█████████▊| 6820/6932 [24:21<00:23,  4.74it/s]

Processing tickers:  98%|█████████▊| 6821/6932 [24:21<00:23,  4.72it/s]

Processing tickers:  98%|█████████▊| 6822/6932 [24:21<00:23,  4.78it/s]

Processing tickers:  98%|█████████▊| 6823/6932 [24:21<00:22,  4.79it/s]

Processing tickers:  98%|█████████▊| 6824/6932 [24:21<00:23,  4.69it/s]

Processing tickers:  98%|█████████▊| 6825/6932 [24:22<00:22,  4.73it/s]

Processing tickers:  98%|█████████▊| 6826/6932 [24:22<00:22,  4.76it/s]

Processing tickers:  98%|█████████▊| 6827/6932 [24:22<00:22,  4.77it/s]

Processing tickers:  98%|█████████▊| 6828/6932 [24:22<00:21,  4.78it/s]

Processing tickers:  99%|█████████▊| 6829/6932 [24:22<00:21,  4.79it/s]

Processing tickers:  99%|█████████▊| 6830/6932 [24:23<00:21,  4.80it/s]

Processing tickers:  99%|█████████▊| 6831/6932 [24:23<00:20,  4.92it/s]

Processing tickers:  99%|█████████▊| 6832/6932 [24:23<00:20,  4.88it/s]

Processing tickers:  99%|█████████▊| 6833/6932 [24:23<00:20,  4.86it/s]

Processing tickers:  99%|█████████▊| 6834/6932 [24:24<00:20,  4.73it/s]

Processing tickers:  99%|█████████▊| 6835/6932 [24:24<00:20,  4.76it/s]

Processing tickers:  99%|█████████▊| 6836/6932 [24:24<00:20,  4.77it/s]

Processing tickers:  99%|█████████▊| 6837/6932 [24:24<00:19,  4.79it/s]

Processing tickers:  99%|█████████▊| 6838/6932 [24:24<00:19,  4.80it/s]

Processing tickers:  99%|█████████▊| 6839/6932 [24:25<00:19,  4.69it/s]

Processing tickers:  99%|█████████▊| 6840/6932 [24:25<00:19,  4.73it/s]

Processing tickers:  99%|█████████▊| 6841/6932 [24:25<00:19,  4.75it/s]

Processing tickers:  99%|█████████▊| 6842/6932 [24:25<00:18,  4.77it/s]

Processing tickers:  99%|█████████▊| 6843/6932 [24:25<00:19,  4.67it/s]

Processing tickers:  99%|█████████▊| 6844/6932 [24:26<00:18,  4.71it/s]

Processing tickers:  99%|█████████▊| 6845/6932 [24:26<00:18,  4.73it/s]

Processing tickers:  99%|█████████▉| 6846/6932 [24:26<00:18,  4.70it/s]

Processing tickers:  99%|█████████▉| 6847/6932 [24:26<00:17,  4.79it/s]

Processing tickers:  99%|█████████▉| 6848/6932 [24:27<00:18,  4.58it/s]

Processing tickers:  99%|█████████▉| 6849/6932 [24:27<00:17,  4.65it/s]

Processing tickers:  99%|█████████▉| 6850/6932 [24:27<00:17,  4.69it/s]

Processing tickers:  99%|█████████▉| 6851/6932 [24:27<00:17,  4.62it/s]

Processing tickers:  99%|█████████▉| 6852/6932 [24:27<00:17,  4.60it/s]

Processing tickers:  99%|█████████▉| 6853/6932 [24:28<00:16,  4.65it/s]

Processing tickers:  99%|█████████▉| 6854/6932 [24:28<00:16,  4.70it/s]

Processing tickers:  99%|█████████▉| 6855/6932 [24:28<00:16,  4.74it/s]

Processing tickers:  99%|█████████▉| 6856/6932 [24:28<00:16,  4.74it/s]

Processing tickers:  99%|█████████▉| 6857/6932 [24:28<00:15,  4.77it/s]

Processing tickers:  99%|█████████▉| 6858/6932 [24:29<00:15,  4.79it/s]

Processing tickers:  99%|█████████▉| 6859/6932 [24:29<00:15,  4.80it/s]

Processing tickers:  99%|█████████▉| 6860/6932 [24:29<00:15,  4.68it/s]

Processing tickers:  99%|█████████▉| 6861/6932 [24:29<00:15,  4.73it/s]

Processing tickers:  99%|█████████▉| 6862/6932 [24:29<00:14,  4.75it/s]

Processing tickers:  99%|█████████▉| 6863/6932 [24:30<00:14,  4.79it/s]

Processing tickers:  99%|█████████▉| 6864/6932 [24:30<00:14,  4.81it/s]

Processing tickers:  99%|█████████▉| 6865/6932 [24:30<00:14,  4.74it/s]

Processing tickers:  99%|█████████▉| 6866/6932 [24:30<00:13,  4.83it/s]

Processing tickers:  99%|█████████▉| 6867/6932 [24:31<00:13,  4.81it/s]

Processing tickers:  99%|█████████▉| 6868/6932 [24:31<00:13,  4.71it/s]

Processing tickers:  99%|█████████▉| 6869/6932 [24:31<00:13,  4.72it/s]

Processing tickers:  99%|█████████▉| 6870/6932 [24:31<00:13,  4.76it/s]

Processing tickers:  99%|█████████▉| 6871/6932 [24:31<00:13,  4.69it/s]

Processing tickers:  99%|█████████▉| 6872/6932 [24:32<00:12,  4.71it/s]

Processing tickers:  99%|█████████▉| 6873/6932 [24:32<00:12,  4.67it/s]

Processing tickers:  99%|█████████▉| 6874/6932 [24:32<00:12,  4.77it/s]

Processing tickers:  99%|█████████▉| 6875/6932 [24:32<00:11,  4.78it/s]

Processing tickers:  99%|█████████▉| 6876/6932 [24:32<00:11,  4.70it/s]

Processing tickers:  99%|█████████▉| 6877/6932 [24:33<00:11,  4.83it/s]

Processing tickers:  99%|█████████▉| 6878/6932 [24:33<00:11,  4.71it/s]

Processing tickers:  99%|█████████▉| 6879/6932 [24:33<00:11,  4.74it/s]

Processing tickers:  99%|█████████▉| 6880/6932 [24:33<00:10,  4.77it/s]

Processing tickers:  99%|█████████▉| 6881/6932 [24:33<00:10,  4.78it/s]

Processing tickers:  99%|█████████▉| 6882/6932 [24:34<00:10,  4.79it/s]

Processing tickers:  99%|█████████▉| 6883/6932 [24:34<00:10,  4.79it/s]

Processing tickers:  99%|█████████▉| 6884/6932 [24:34<00:10,  4.79it/s]

Processing tickers:  99%|█████████▉| 6885/6932 [24:34<00:09,  4.79it/s]

Processing tickers:  99%|█████████▉| 6886/6932 [24:35<00:09,  4.79it/s]

Processing tickers:  99%|█████████▉| 6887/6932 [24:35<00:09,  4.67it/s]

Processing tickers:  99%|█████████▉| 6888/6932 [24:35<00:09,  4.65it/s]

Processing tickers:  99%|█████████▉| 6889/6932 [24:35<00:08,  4.78it/s]

Processing tickers:  99%|█████████▉| 6890/6932 [24:35<00:09,  4.65it/s]

Processing tickers:  99%|█████████▉| 6891/6932 [24:36<00:08,  4.73it/s]

Processing tickers:  99%|█████████▉| 6892/6932 [24:36<00:08,  4.75it/s]

Processing tickers:  99%|█████████▉| 6893/6932 [24:36<00:08,  4.76it/s]

Processing tickers:  99%|█████████▉| 6894/6932 [24:36<00:07,  4.77it/s]

Processing tickers:  99%|█████████▉| 6895/6932 [24:36<00:07,  4.67it/s]

Processing tickers:  99%|█████████▉| 6896/6932 [24:37<00:07,  4.71it/s]

Processing tickers:  99%|█████████▉| 6897/6932 [24:37<00:07,  4.73it/s]

Processing tickers: 100%|█████████▉| 6898/6932 [24:37<00:07,  4.76it/s]

Processing tickers: 100%|█████████▉| 6899/6932 [24:37<00:06,  4.78it/s]

Processing tickers: 100%|█████████▉| 6900/6932 [24:37<00:06,  4.68it/s]

Processing tickers: 100%|█████████▉| 6901/6932 [24:38<00:06,  4.71it/s]

Processing tickers: 100%|█████████▉| 6902/6932 [24:38<00:06,  4.75it/s]

Processing tickers: 100%|█████████▉| 6903/6932 [24:38<00:06,  4.67it/s]

Processing tickers: 100%|█████████▉| 6904/6932 [24:38<00:05,  4.69it/s]

Processing tickers: 100%|█████████▉| 6905/6932 [24:39<00:05,  4.75it/s]

Processing tickers: 100%|█████████▉| 6906/6932 [24:39<00:05,  4.77it/s]

Processing tickers: 100%|█████████▉| 6907/6932 [24:39<00:05,  4.67it/s]

Processing tickers: 100%|█████████▉| 6908/6932 [24:39<00:05,  4.71it/s]

Processing tickers: 100%|█████████▉| 6909/6932 [24:39<00:04,  4.75it/s]

Processing tickers: 100%|█████████▉| 6910/6932 [24:40<00:04,  4.80it/s]

Processing tickers: 100%|█████████▉| 6911/6932 [24:40<00:04,  4.81it/s]

Processing tickers: 100%|█████████▉| 6912/6932 [24:40<00:04,  4.80it/s]

Processing tickers: 100%|█████████▉| 6913/6932 [24:40<00:03,  4.80it/s]

Processing tickers: 100%|█████████▉| 6914/6932 [24:40<00:03,  4.80it/s]

Processing tickers: 100%|█████████▉| 6915/6932 [24:41<00:03,  4.81it/s]

Processing tickers: 100%|█████████▉| 6916/6932 [24:41<00:03,  4.81it/s]

Processing tickers: 100%|█████████▉| 6917/6932 [24:41<00:03,  4.80it/s]

Processing tickers: 100%|█████████▉| 6918/6932 [24:41<00:02,  4.80it/s]

Processing tickers: 100%|█████████▉| 6919/6932 [24:41<00:02,  4.83it/s]

Processing tickers: 100%|█████████▉| 6920/6932 [24:42<00:02,  4.82it/s]

Processing tickers: 100%|█████████▉| 6921/6932 [24:42<00:02,  4.81it/s]

Processing tickers: 100%|█████████▉| 6922/6932 [24:42<00:02,  4.70it/s]

Processing tickers: 100%|█████████▉| 6923/6932 [24:42<00:01,  4.70it/s]

Processing tickers: 100%|█████████▉| 6924/6932 [24:43<00:01,  4.76it/s]

Processing tickers: 100%|█████████▉| 6925/6932 [24:43<00:01,  4.68it/s]

Processing tickers: 100%|█████████▉| 6926/6932 [24:43<00:01,  4.71it/s]

Processing tickers: 100%|█████████▉| 6927/6932 [24:43<00:01,  4.70it/s]

Processing tickers: 100%|█████████▉| 6928/6932 [24:43<00:00,  4.77it/s]

Processing tickers: 100%|█████████▉| 6929/6932 [24:44<00:00,  4.78it/s]

Processing tickers: 100%|█████████▉| 6930/6932 [24:44<00:00,  4.74it/s]

Processing tickers: 100%|█████████▉| 6931/6932 [24:44<00:00,  4.70it/s]

Processing tickers: 100%|██████████| 6932/6932 [24:44<00:00,  4.71it/s]

Processing tickers: 100%|██████████| 6932/6932 [24:44<00:00,  4.67it/s]

         date ticker   gap
0  2025-12-22      A  0.28
1  2025-12-23      A -0.25
2  2025-12-24      A -0.01
3  2025-12-26      A  0.13
4  2025-12-29      A  0.01
Загалом рядків: 413461

In [45]:
std_by_ticker = (
    df_gaps_all.groupby("ticker")["gap"]
    .std()                 # std по групі (ddof=1)
    .round(2)              # округлення до 2 знаків
    .reset_index(name="sigma")
)

In [46]:
std_by_ticker

     ticker  sigma
0         A   0.78
1        AA   2.31
2      AAAU   1.97
3      AACG   3.70
4       AAL   1.73
...     ...    ...
6927    ZWS   0.97
6928   ZYBT   4.16
6929   ZYME   1.22
6930   ZYXI   0.84
6931  ZYXIQ  13.51

[6932 rows x 2 columns]

In [47]:
import os, time, gc
import pandas as pd
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
except Exception:
    pa = pq = None


def _prepare_sigma_df(
    sigma_df: Optional[pd.DataFrame] = None,
    sigma_path: Optional[str] = None
) -> pd.DataFrame:
    """
    Готує мапу ['ticker','sigma'] з DataFrame або з файлу (.parquet/.csv).
    Нормалізує регістр, типи і прибирає дублікати по 'ticker'.
    """
    if sigma_df is None and sigma_path is None:
        raise ValueError("Передай або sigma_df, або sigma_path.")

    if sigma_df is None:
        ext = os.path.splitext(sigma_path)[1].lower()
        if ext == ".parquet":
            sigma_df = pd.read_parquet(sigma_path)
        else:
            sigma_df = pd.read_csv(sigma_path, low_memory=False)

    df = sigma_df.copy()
    # знайдемо колонки гнучко
    cols_lower = {c.lower().strip(): c for c in df.columns}
    tcol = cols_lower.get("ticker")
    scol = cols_lower.get("sigma")
    if tcol is None or scol is None:
        raise KeyError("Очікую колонки 'ticker' і 'sigma' у даних зі скріна.")

    df = df[[tcol, scol]].rename(columns={tcol: "ticker", scol: "sigma"})
    df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()
    df["sigma"]  = pd.to_numeric(df["sigma"], errors="coerce")
    df = (df.sort_values(["ticker"])
            .drop_duplicates(subset=["ticker"], keep="last")
            .reset_index(drop=True))
    return df[["ticker", "sigma"]]


def add_sigma_by_ticker_to_parquet(
    base_path: str = "CRACEN/work/premarket_rows_with_bench_pct.parquet",
    out_path:  Optional[str] = None,
    *,
    sigma_df: Optional[pd.DataFrame] = None,   # напр. твій std_by_ticker зі скріна
    sigma_path: Optional[str] = None,          # або шлях до файла з цими даними
    batch_rows: int = 2_000_000,
    compression: str = "snappy",
    insert_before: Optional[str] = None,       # напр. "Bench%" або "pct_vs_prev_close"; якщо None — в кінець
    log_every_batches: int = 5,
    round_decimals: Optional[int] = 6,
) -> str:
    """
    Потоково додає колонку 'sigma' (за 'ticker') до великого Parquet та зберігає новий файл.
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(base_path):
        raise FileNotFoundError(base_path)

    # вихідний шлях
    if out_path is None:
        folder, fname = os.path.split(base_path)
        name, ext = os.path.splitext(fname)
        out_path = os.path.join(folder, f"{name}_with_sigma{ext or '.parquet'}")

    # підготовка мапи sigma
    sigma_map = _prepare_sigma_df(sigma_df=sigma_df, sigma_path=sigma_path)
    if round_decimals is not None:
        sigma_map["sigma"] = sigma_map["sigma"].round(round_decimals)

    # запис у тимчасовий файл → атомарна заміна
    tmp_path = out_path + f".tmp_{os.getpid()}_{int(time.time())}"
    pf = pq.ParquetFile(base_path)
    writer = None
    total = 0
    t0 = time.time()

    print(f"▶️ START merge sigma → {out_path}")
    for i, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()
        if "ticker" not in df.columns:
            raise KeyError("У базовому файлі відсутня колонка 'ticker'.")

        df["ticker"] = df["ticker"].astype(str).str.strip().str.upper()

        merged = df.merge(sigma_map, on="ticker", how="left", validate="m:1")

        # розташувати 'sigma' за бажанням
        if insert_before and insert_before in merged.columns:
            cols = list(merged.columns)
            cols.remove("sigma")
            idx = cols.index(insert_before)
            cols = cols[:idx] + ["sigma"] + cols[idx:]
            merged = merged[cols]
        else:
            base_cols = [c for c in merged.columns if c != "sigma"]
            merged = merged[base_cols + ["sigma"]]

        table = pa.Table.from_pandas(merged, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_path, table.schema, compression=compression)
        writer.write_table(table)

        total += len(merged)
        if i % log_every_batches == 0:
            print(f"[batch {i:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, merged, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # атомарна заміна
    if os.path.exists(out_path):
        os.remove(out_path)
    os.replace(tmp_path, out_path)

    print(f"✅ DONE rows={total:,} → {out_path}  in {time.time()-t0:,.1f}s")
    return out_path

In [48]:
# std_by_ticker має колонки: ['ticker','sigma']
add_sigma_by_ticker_to_parquet(
    base_path=str(WORK_DIR / "premarket_rows_with_bench_pct.parquet"),
    sigma_df=std_by_ticker,  # <- твій DF зі скріна
    # або sigma_path="CRACEN/std_by_ticker.parquet"/".csv"
    insert_before=None,      # або "Bench%" / "pct_vs_prev_close" — куди вставити
)

▶️ START merge sigma → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet

[batch    5] rows=10,000,000  elapsed=10.6s

[batch   10] rows=20,000,000  elapsed=21.2s

[batch   15] rows=30,000,000  elapsed=31.7s

[batch   20] rows=40,000,000  elapsed=42.1s

[batch   25] rows=50,000,000  elapsed=52.4s

[batch   30] rows=60,000,000  elapsed=62.9s

[batch   35] rows=70,000,000  elapsed=73.4s

[batch   40] rows=80,000,000  elapsed=83.9s

[batch   45] rows=90,000,000  elapsed=94.4s

[batch   50] rows=100,000,000  elapsed=104.8s

[batch   55] rows=110,000,000  elapsed=115.3s

✅ DONE rows=111,034,041 → C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  in 116.5s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\work\\premarket_rows_with_bench_pct_with_sigma.parquet'

In [49]:
peek_parquet("CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet", n=21150)

Файл: CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet
Рядків (meta): 111,034,041
Колонок: 16
Схема: ticker, dt, o, h, l, c, v, date, open, prev_close, Stack%, bench, corr, beta, Bench%, sigma
NaN у 'bench' (у прев'ю): 0/21150
NaN у 'corr' (у прев'ю): 0/21150
NaN у 'beta' (у прев'ю): 0/21150

Перші рядки:

      ticker                  dt           o           h           l           c          v        date    open  prev_close  Stack% bench  corr  beta  Bench%  sigma
0          A 2025-12-21 20:52:00  137.809998  137.809998  137.800003  137.800003        5.0  2025-12-21     NaN         NaN     NaN   SPY  0.81  0.93     NaN   0.78
1          A 2025-12-21 20:55:00  137.800003  137.800003  137.800003  137.800003        2.0  2025-12-21     NaN         NaN     NaN   SPY  0.81  0.93     NaN   0.78
2          A 2025-12-21 21:13:00  136.410004  136.410004  136.410004  136.410004        1.0  2025-12-21     NaN         NaN     NaN   SPY  0.81  0.93     NaN   0.78
3          A 2025-12-22 01:27:00  136.990005  136.990005  136.990005  136.990005       36.0  2025-12-22  137.62      137.22   -0.17   SPY  0.81  0.93    0.25   0.78
4          A 2025-12-22 03:38:00  137.179993  137.179993  137.179993  137.179993        1.0  2025-12-22  137.62      137.22   -0.03   SPY  0.81  0.93    0.31   0.78
5          A 2025-12-22 09:29:00  137.460007  137.470001  137.460007  137.470001      531.0  2025-12-22  137.62      137.22    0.17   SPY  0.81  0.93    0.49   0.78
6          A 2025-12-22 09:30:00  137.619995  137.619995  137.229996  137.229996    10639.0  2025-12-22  137.62      137.22    0.29   SPY  0.81  0.93    0.49   0.78
7          A 2025-12-22 09:31:00  137.399994  137.399994  137.205002  137.205002      200.0  2025-12-22  137.62      137.22    0.13   SPY  0.81  0.93    0.47   0.78
8          A 2025-12-22 09:32:00  137.516998  137.990005  137.516998  137.990005      220.0  2025-12-22  137.62      137.22    0.22   SPY  0.81  0.93    0.56   0.78
9          A 2025-12-22 09:33:00  137.899994  138.139999  137.824997  137.824997      900.0  2025-12-22  137.62      137.22    0.50   SPY  0.81  0.93    0.52   0.78
10         A 2025-12-22 09:34:00  138.279999  138.279999  137.789993  137.789993     1862.0  2025-12-22  137.62      137.22    0.77   SPY  0.81  0.93    0.44   0.78
11         A 2025-12-22 09:35:00  138.020004  138.020004  138.020004  138.020004      300.0  2025-12-22  137.62      137.22    0.58   SPY  0.81  0.93    0.45   0.78
12         A 2025-12-22 09:36:00  138.080002  138.080002  138.020004  138.039993     1672.0  2025-12-22  137.62      137.22    0.63   SPY  0.81  0.93    0.42   0.78
13         A 2025-12-22 09:37:00  138.039993  138.039993  137.431000  137.714996     1811.0  2025-12-22  137.62      137.22    0.60   SPY  0.81  0.93    0.44   0.78
14         A 2025-12-22 09:38:00  137.809998  137.809998  137.699997  137.699997      200.0  2025-12-22  137.62      137.22    0.43   SPY  0.81  0.93    0.43   0.78
15         A 2025-12-22 09:40:00  137.550003  137.615005  137.544998  137.544998      600.0  2025-12-22  137.62      137.22    0.24   SPY  0.81  0.93    0.40   0.78
16         A 2025-12-22 09:41:00  137.544998  137.544998  137.544998  137.544998      396.0  2025-12-22  137.62      137.22    0.24   SPY  0.81  0.93    0.40   0.78
17         A 2025-12-22 09:43:00  137.639999  137.639999  137.350006  137.350006     1357.0  2025-12-22  137.62      137.22    0.31   SPY  0.81  0.93    0.36   0.78
18         A 2025-12-22 09:44:00  137.470001  137.479996  137.320007  137.479996     1228.0  2025-12-22  137.62      137.22    0.18   SPY  0.81  0.93    0.41   0.78
19         A 2025-12-22 09:46:00  137.509995  137.509995  137.369995  137.395004      715.0  2025-12-22  137.62      137.22    0.21   SPY  0.81  0.93    0.38   0.78
20         A 2025-12-22 09:47:00  137.395004  137.509995  137.339996  137.509995      420.0  2025-12-22  137.62      137.22    0.13   SPY  0.81  0.93    0.40   0.78
21         A 2025-12-22 09:48:00  137.429993  137.429993  137.380005  137.380005      200.0  2025-12-22  137.62      137.22    0.15   SPY  0.81  0.93    0.44   0.78
22         A 2025-12-22 09:49:00  137.360001  137.559998  137.360001  137.559998      968.0  2025-12-22  137.62      137.22    0.10   SPY  0.81  0.93    0.43   0.78
23         A 2025-12-22 09:50:00  137.639999  137.660004  137.570007  137.639999     1079.0  2025-12-22  137.62      137.22    0.31   SPY  0.81  0.93    0.41   0.78
24         A 2025-12-22 09:51:00  137.610001  137.639999  137.479996  137.509995      974.0  2025-12-22  137.62      137.22    0.28   SPY  0.81  0.93    0.43   0.78
25         A 2025-12-22 09:52:00  137.470001  137.470001  137.470001  137.470001      270.0  2025-12-22  137.62      137.22    0.18   SPY  0.81  0.93    0.45   0.78
26         A 2025-12-22 09:53:00  137.410004  137.550003  137.410004  137.550003      901.0  2025-12-22  137.62      137.22    0.14   SPY  0.81  0.93    0.43   0.78
27         A 2025-12-22 09:54:00  137.565002  137.565002  137.565002  137.565002      200.0  2025-12-22  137.62      137.22    0.25   SPY  0.81  0.93    0.45   0.78
28         A 2025-12-22 09:55:00  137.669998  137.690002  137.669998  137.690002      865.0  2025-12-22  137.62      137.22    0.33   SPY  0.81  0.93    0.50   0.78
29         A 2025-12-22 09:56:00  137.770004  137.770004  137.705002  137.710007     2045.0  2025-12-22  137.62      137.22    0.40   SPY  0.81  0.93    0.50   0.78
30         A 2025-12-22 09:57:00  137.809998  137.820007  137.720001  137.729996     2131.0  2025-12-22  137.62      137.22    0.43   SPY  0.81  0.93    0.47   0.78
31         A 2025-12-22 09:58:00  137.839996  137.839996  137.779999  137.789993     1130.0  2025-12-22  137.62      137.22    0.45   SPY  0.81  0.93    0.51   0.78
32         A 2025-12-22 09:59:00  137.750000  137.750000  137.600006  137.669998     1437.0  2025-12-22  137.62      137.22    0.39   SPY  0.81  0.93    0.50   0.78
33         A 2025-12-22 10:00:00  137.580002  137.580002  137.382507  137.382507     1079.0  2025-12-22  137.62      137.22    0.26   SPY  0.81  0.93    0.50   0.78
34         A 2025-12-22 10:01:00  137.440002  137.440002  137.440002  137.440002      120.0  2025-12-22  137.62      137.22    0.16   SPY  0.81  0.93    0.46   0.78
35         A 2025-12-22 10:02:00  137.539993  137.539993  137.539993  137.539993      425.0  2025-12-22  137.62      137.22    0.23   SPY  0.81  0.93    0.45   0.78
36         A 2025-12-22 10:04:00  137.589996  137.589996  137.524994  137.524994      300.0  2025-12-22  137.62      137.22    0.27   SPY  0.81  0.93    0.45   0.78
37         A 2025-12-22 10:05:00  137.479996  137.479996  137.479996  137.479996      100.0  2025-12-22  137.62      137.22    0.19   SPY  0.81  0.93    0.42   0.78
38         A 2025-12-22 10:06:00  137.410004  137.455002  137.309998  137.350006     2348.0  2025-12-22  137.62      137.22    0.14   SPY  0.81  0.93    0.43   0.78
39         A 2025-12-22 10:07:00  137.365005  137.389999  137.365005  137.369995     1628.0  2025-12-22  137.62      137.22    0.11   SPY  0.81  0.93    0.43   0.78
40         A 2025-12-22 10:08:00  137.365005  137.470001  137.362503  137.365005     2788.0  2025-12-22  137.62      137.22    0.11   SPY  0.81  0.93    0.44   0.78
41         A 2025-12-22 10:09:00  137.365005  137.369995  137.350006  137.369995      600.0  2025-12-22  137.62      137.22    0.11   SPY  0.81  0.93    0.43   0.78
42         A 2025-12-22 10:10:00  137.389999  137.389999  137.380005  137.380005      200.0  2025-12-22  137.62      137.22    0.12   SPY  0.81  0.93    0.44   0.78
43         A 2025-12-22 10:12:00  137.320007  137.320007  137.320007  137.320007      100.0  2025-12-22  137.62      137.22    0.07   SPY  0.81  0.93    0.37   0.78
44         A 2025-12-22 10:13:00  137.309998  137.479996  137.309998  137.479996      246.0  2025-12-22  137.62      137.22    0.07   SPY  0.81  0.93    0.35   0.78
45         A 2025-12-22 10:14:00  137.410004  137.472504  137.350006  137.472504     1347.0  2025-12-22  137.62      137.22    0.14   SPY  0.81  0.93    0.36   0.78
46         A 2025-12-22 10:15:00  137.339996  137.389999  137.309998  137.352997      922.0  2025-12-22  137.62      137.22    0.09   SPY  0.81  0.93    0.35   0.78
47         A 2025-12-22 10:16:00  137.309998  137.520004  137.309998  137.520004     1445.0  2025-12-22  137.62      137.22    0.07   SPY  0.81  0.93    0.37   0.78
48         A 2025-12-22 10:17:00  137.600693  137.714996  137.600693  137.714996      285.0  2025-12-22  137.62      137.22    0.28   SPY  0.81  0.93    0.40   0.78
49         A 2025-12-22 10:18:00  137.630005  137.630005  137.619995  137.619995      600.0  2025-12-22  137.62      137.22    0.30   SPY  0.81  0.93    0.43   0.78
50         A 2025-12-22 10:19:00  137.625000  137.710007  137.559998  137.710007     1601.0  2025-12-22  137.62      137.22    0.30   SPY  0.81  0.93    0.41   0.78
51         A 2025-12-22 10:20:00  137.755005  137.779999  137.755005  137.774994      450.0  2025-12-22  137.62      137.22    0.39   SPY  0.81  0.93    0.42   0.78
52         A 2025-12-22 10:21:00  137.772507  137.860001  137.772507  137.860001      200.0  2025-12-22  137.62      137.22    0.40   SPY  0.81  0.93    0.45   0.78
53         A 2025-12-22 10:22:00  137.877502  138.020004  137.877502  138.020004     2000.0  2025-12-22  137.62      137.22    0.48   SPY  0.81  0.93    0.45   0.78
54         A 2025-12-22 10:23:00  138.020004  138.100006  137.960007  138.100006     1125.0  2025-12-22  137.62      137.22    0.58   SPY  0.81  0.93    0.44   0.78
55         A 2025-12-22 10:24:00  138.100006  138.279999  138.089996  138.149994     3817.0  2025-12-22  137.62      137.22    0.64   SPY  0.81  0.93    0.45   0.78
56         A 2025-12-22 10:25:00  138.080002  138.164993  138.000000  138.020004      900.0  2025-12-22  137.62      137.22    0.63   SPY  0.81  0.93    0.47   0.78
57         A 2025-12-22 10:26:00  138.050003  138.190002  138.050003  138.190002     1143.0  2025-12-22  137.62      137.22    0.60   SPY  0.81  0.93    0.48   0.78
58         A 2025-12-22 10:27:00  138.040100  138.330002  138.040100  138.330002     1650.0  2025-12-22  137.62      137.22    0.60   SPY  0.81  0.93    0.46   0.78
59         A 2025-12-22 10:28:00  138.335007  138.335007  138.179993  138.179993     5249.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93    0.46   0.78
60         A 2025-12-22 10:29:00  138.320007  138.320007  138.110001  138.210007     1333.0  2025-12-22  137.62      137.22    0.80   SPY  0.81  0.93    0.47   0.78
61         A 2025-12-22 10:30:00  138.289993  138.365005  138.199997  138.289993    13039.0  2025-12-22  137.62      137.22    0.78   SPY  0.81  0.93    0.47   0.78
62         A 2025-12-22 10:31:00  138.315002  138.354996  138.169998  138.190002     4200.0  2025-12-22  137.62      137.22    0.80   SPY  0.81  0.93    0.48   0.78
63         A 2025-12-22 10:32:00  138.190002  138.389999  138.190002  138.369995     1928.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93    0.44   0.78
64         A 2025-12-22 10:33:00  138.354996  138.354996  138.270004  138.270004      200.0  2025-12-22  137.62      137.22    0.83   SPY  0.81  0.93    0.45   0.78
65         A 2025-12-22 10:34:00  138.270004  138.270004  138.255005  138.255005      404.0  2025-12-22  137.62      137.22    0.77   SPY  0.81  0.93    0.44   0.78
66         A 2025-12-22 10:35:00  138.139999  138.199997  138.139999  138.199997      700.0  2025-12-22  137.62      137.22    0.67   SPY  0.81  0.93    0.43   0.78
67         A 2025-12-22 10:36:00  138.250000  138.255005  138.225006  138.225006      300.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93    0.40   0.78
68         A 2025-12-22 10:37:00  138.119995  138.220001  138.119995  138.220001      303.0  2025-12-22  137.62      137.22    0.66   SPY  0.81  0.93    0.34   0.78
69         A 2025-12-22 10:38:00  138.110001  138.169998  138.100006  138.169998      900.0  2025-12-22  137.62      137.22    0.65   SPY  0.81  0.93    0.34   0.78
70         A 2025-12-22 10:39:00  138.169998  138.169998  138.169998  138.169998      100.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93    0.34   0.78
71         A 2025-12-22 10:40:00  138.190002  138.210007  138.190002  138.190002     1597.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93    0.34   0.78
72         A 2025-12-22 10:41:00  138.195007  138.279999  138.080002  138.205002     2970.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93    0.35   0.78
73         A 2025-12-22 10:42:00  138.199997  138.240005  138.199997  138.240005      600.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93    0.36   0.78
74         A 2025-12-22 10:43:00  138.255005  138.309998  138.255005  138.309998      672.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93    0.44   0.78
75         A 2025-12-22 10:44:00  138.255005  138.259995  138.255005  138.259995      900.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93    0.45   0.78
76         A 2025-12-22 10:45:00  138.235001  138.380005  138.190002  138.324997     4648.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93    0.46   0.78
77         A 2025-12-22 10:46:00  138.324997  138.330002  138.324997  138.330002      200.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93    0.47   0.78
78         A 2025-12-22 10:47:00  138.330002  138.490005  138.300003  138.490005    12601.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93    0.48   0.78
79         A 2025-12-22 10:48:00  138.429993  138.520004  138.429993  138.520004     1929.0  2025-12-22  137.62      137.22    0.88   SPY  0.81  0.93    0.47   0.78
80         A 2025-12-22 10:49:00  138.520004  138.524994  138.470001  138.470001      520.0  2025-12-22  137.62      137.22    0.95   SPY  0.81  0.93    0.47   0.78
81         A 2025-12-22 10:50:00  138.524994  138.524994  138.524994  138.524994      100.0  2025-12-22  137.62      137.22    0.95   SPY  0.81  0.93    0.47   0.78
82         A 2025-12-22 10:51:00  138.550003  138.660004  138.544998  138.630005     1818.0  2025-12-22  137.62      137.22    0.97   SPY  0.81  0.93    0.46   0.78
83         A 2025-12-22 10:52:00  138.615005  138.615005  138.615005  138.615005      100.0  2025-12-22  137.62      137.22    1.02   SPY  0.81  0.93    0.48   0.78
84         A 2025-12-22 10:53:00  138.610001  138.615005  138.610001  138.615005      600.0  2025-12-22  137.62      137.22    1.01   SPY  0.81  0.93    0.47   0.78
85         A 2025-12-22 10:54:00  138.654999  138.660004  138.610001  138.660004     1855.0  2025-12-22  137.62      137.22    1.05   SPY  0.81  0.93    0.47   0.78
86         A 2025-12-22 10:55:00  138.699997  138.710007  138.699997  138.710007      500.0  2025-12-22  137.62      137.22    1.08   SPY  0.81  0.93    0.48   0.78
87         A 2025-12-22 10:56:00  138.679993  138.679993  138.229996  138.229996     7661.0  2025-12-22  137.62      137.22    1.06   SPY  0.81  0.93    0.47   0.78
88         A 2025-12-22 10:57:00  138.229996  138.259995  138.210007  138.229996     1313.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93    0.49   0.78
89         A 2025-12-22 10:58:00  138.210007  138.210007  138.210007  138.210007      100.0  2025-12-22  137.62      137.22    0.72   SPY  0.81  0.93    0.49   0.78
90         A 2025-12-22 10:59:00  138.210007  138.279999  138.070007  138.080002     4665.0  2025-12-22  137.62      137.22    0.72   SPY  0.81  0.93    0.46   0.78
91         A 2025-12-22 11:00:00  138.110001  138.130005  137.940002  137.990005     7578.0  2025-12-22  137.62      137.22    0.65   SPY  0.81  0.93    0.45   0.78
92         A 2025-12-22 11:01:00  137.979996  137.979996  137.940002  137.940002      757.0  2025-12-22  137.62      137.22    0.55   SPY  0.81  0.93    0.46   0.78
93         A 2025-12-22 11:02:00  137.945007  138.199997  137.945007  138.199997     5810.0  2025-12-22  137.62      137.22    0.53   SPY  0.81  0.93    0.46   0.78
94         A 2025-12-22 11:03:00  138.289993  138.289993  138.289993  138.289993     2680.0  2025-12-22  137.62      137.22    0.78   SPY  0.81  0.93    0.46   0.78
95         A 2025-12-22 11:04:00  138.080002  138.080002  138.080002  138.080002      117.0  2025-12-22  137.62      137.22    0.63   SPY  0.81  0.93    0.48   0.78
96         A 2025-12-22 11:06:00  138.169998  138.214996  138.169998  138.214996      652.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93    0.49   0.78
97         A 2025-12-22 11:07:00  138.214996  138.214996  138.214996  138.214996      200.0  2025-12-22  137.62      137.22    0.73   SPY  0.81  0.93    0.52   0.78
98         A 2025-12-22 11:08:00  138.149994  138.179993  138.130005  138.179993     1208.0  2025-12-22  137.62      137.22    0.68   SPY  0.81  0.93    0.51   0.78
99         A 2025-12-22 11:09:00  138.289993  138.289993  138.229996  138.270004      400.0  2025-12-22  137.62      137.22    0.78   SPY  0.81  0.93    0.53   0.78
100        A 2025-12-22 11:10:00  138.330002  138.429993  138.330002  138.429993      900.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93    0.53   0.78
101        A 2025-12-22 11:11:00  138.330002  138.360001  138.309998  138.309998     2250.0  2025-12-22  137.62      137.22    0.81   SPY  0.81  0.93    0.56   0.78
102        A 2025-12-22 11:13:00  138.240005  138.315994  138.240005  138.315002     1560.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93    0.57   0.78
103        A 2025-12-22 11:14:00  138.315002  138.315002  138.315002  138.315002      388.0  2025-12-22  137.62      137.22    0.80   SPY  0.81  0.93    0.58   0.78
104        A 2025-12-22 11:15:00  138.380005  138.380005  138.324997  138.324997      333.0  2025-12-22  137.62      137.22    0.85   SPY  0.81  0.93    0.60   0.78
105        A 2025-12-22 11:16:00  138.250000  138.309998  138.190002  138.190002     1300.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93    0.61   0.78
106        A 2025-12-22 11:17:00  138.199997  138.199997  138.199997  138.199997      200.0  2025-12-22  137.62      137.22    0.71   SPY  0.81  0.93    0.62   0.78
107        A 2025-12-22 11:18:00  138.164993  138.164993  138.164993  138.164993      200.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93    0.62   0.78
108        A 2025-12-22 11:19:00  138.110001  138.110001  138.110001  138.110001      100.0  2025-12-22  137.62      137.22    0.65   SPY  0.81  0.93    0.61   0.78
109        A 2025-12-22 11:20:00  138.160004  138.160004  138.110001  138.110001     1209.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93    0.63   0.78
110        A 2025-12-22 11:21:00  138.110001  138.169998  138.110001  138.169998      200.0  2025-12-22  137.62      137.22    0.65   SPY  0.81  0.93    0.64   0.78
111        A 2025-12-22 11:22:00  138.250000  138.250000  138.250000  138.250000      200.0  2025-12-22  137.62      137.22    0.75   SPY  0.81  0.93    0.63   0.78
112        A 2025-12-22 11:23:00  138.229996  138.240005  138.172501  138.172501      550.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93    0.61   0.78
113        A 2025-12-22 11:24:00  138.179993  138.179993  138.179993  138.179993      100.0  2025-12-22  137.62      137.22    0.70   SPY  0.81  0.93    0.62   0.78
114        A 2025-12-22 11:25:00  138.229996  138.229996  138.139999  138.139999      277.0  2025-12-22  137.62      137.22    0.74   SPY  0.81  0.93    0.61   0.78
115        A 2025-12-22 11:26:00  138.164993  138.164993  138.164993  138.164993      200.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93    0.59   0.78
116        A 2025-12-22 11:27:00  138.164993  138.164993  138.164993  138.164993      100.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93    0.59   0.78
117        A 2025-12-22 11:28:00  138.169998  138.175003  138.169998  138.175003      400.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93    0.59   0.78
118        A 2025-12-22 11:29:00  138.160004  138.250000  138.160004  138.214996     1043.0  2025-12-22  137.62      137.22    0.69   SPY  0.81  0.93    0.60   0.78
119        A 2025-12-22 11:30:00  138.214996  138.220001  138.214996  138.220001      546.0  2025-12-22  137.62      137.22    0.73   SPY  0.81  0.93    0.60   0.78

,ticker,dt,o,h,l,c,v,date,open,prev_close,Stack%,bench,corr,beta,Bench%,sigma
0,A,2025-12-21 20:52:00,137.809998,137.809998,137.800003,137.800003,5.0,2025-12-21,NaN,NaN,NaN,SPY,0.81,0.93,NaN,0.78
1,A,2025-12-21 20:55:00,137.800003,137.800003,137.800003,137.800003,2.0,2025-12-21,NaN,NaN,NaN,SPY,0.81,0.93,NaN,0.78
2,A,2025-12-21 21:13:00,136.410004,136.410004,136.410004,136.410004,1.0,2025-12-21,NaN,NaN,NaN,SPY,0.81,0.93,NaN,0.78
3,A,2025-12-22 01:27:00,136.990005,136.990005,136.990005,136.990005,36.0,2025-12-22,137.62,137.22,-0.17,SPY,0.81,0.93,0.25,0.78
4,A,2025-12-22 03:38:00,137.179993,137.179993,137.179993,137.179993,1.0,2025-12-22,137.62,137.22,-0.03,SPY,0.81,0.93,0.31,0.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21145,AA,2026-01-23 08:45:00,61.509998,61.509998,61.209999,61.209999,335.0,2026-01-23,60.79,63.15,-2.60,SPY,0.76,2.60,-0.18,2.31
21146,AA,2026-01-23 08:46:00,61.439999,61.439999,61.439999,61.439999,2500.0,2026-01-23,60.79,63.15,-2.71,SPY,0.76,2.60,-0.19,2.31
21147,AA,2026-01-23 08:47:00,61.240002,61.490002,61.240002,61.392399,450.0,2026-01-23,60.79,63.15,-3.02,SPY,0.76,2.60,-0.19,2.31
21148,AA,2026-01-23 08:48:00,61.840000,61.840000,61.480000,61.480000,2600.0,2026-01-23,60.79,63.15,-2.07,SPY,0.76,2.60,-0.17,2.31
21149,AA,2026-01-23 08:49:00,61.639999,61.869999,61.639999,61.689999,2490.0,2026-01-23,60.79,63.15,-2.39,SPY,0.76,2.60,-0.16,2.31

In [50]:
import os, time, gc
import pandas as pd
import numpy as np
from typing import Optional

try:
    import pyarrow as pa
    import pyarrow.parquet as pq
    import pyarrow.dataset as ds
except Exception:
    pa = pq = ds = None


def _write_final_sorted_alphabetical(
    input_path: str,
    output_path: str,
    *,
    compression: str = "snappy",
    roundtrip_pandas: bool = True,   # найнадійніше для sort_values
    log_every: int = 200,
):
    """
    Rewrites input parquet into output parquet in strict physical order:
      ticker A→Z, then (date, dt) within each ticker (or dt only).
    Uses dataset scanning per ticker to avoid global in-memory sort.
    """
    if ds is None or pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow.dataset (pyarrow>=6).")

    dataset = ds.dataset(input_path, format="parquet")

    # Discover columns
    schema_names = [f.name for f in dataset.schema]
    if "ticker" not in schema_names:
        raise KeyError("У вхідному parquet немає колонки 'ticker' — неможливо відсортувати по тикерах.")

    has_date = ("date" in schema_names)
    has_dt   = ("dt" in schema_names)

    # get unique tickers (safe, but could be heavy; acceptable for your use-case)
    tickers_tbl = dataset.to_table(columns=["ticker"])
    tickers = sorted(pd.unique(tickers_tbl.column("ticker").to_pandas().astype(str)))
    del tickers_tbl
    gc.collect()

    tmp_out = output_path + f".tmp_sorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_out):
        os.remove(tmp_out)

    writer = None
    total_written = 0
    t0 = time.time()

    print(f"▶ SORT: {input_path} → {output_path} | tickers={len(tickers):,} | has_date={has_date} has_dt={has_dt}")

    try:
        for i, tk in enumerate(tickers, 1):
            # Filter rows for this ticker
            filt = (ds.field("ticker") == tk)
            table = dataset.to_table(filter=filt)
            if table.num_rows == 0:
                continue

            if roundtrip_pandas:
                df = table.to_pandas()
                # Ensure date exists if needed
                if has_date:
                    # keep as-is; assume date is string 'YYYY-MM-DD'
                    pass
                elif has_dt and ("date" not in df.columns):
                    # If no date column exists, optionally derive it (not required for sort)
                    pass

                if has_date and has_dt and {"date", "dt"}.issubset(df.columns):
                    df.sort_values(["date", "dt"], kind="mergesort", inplace=True)
                elif has_dt and "dt" in df.columns:
                    df.sort_values(["dt"], kind="mergesort", inplace=True)
                else:
                    # fallback: stable sort by all columns
                    df.sort_values(list(df.columns), kind="mergesort", inplace=True)

                out_table = pa.Table.from_pandas(df, preserve_index=False)
                del df
            else:
                # Arrow-only fallback (less flexible)
                out_table = table

            if writer is None:
                writer = pq.ParquetWriter(tmp_out, out_table.schema, compression=compression)

            writer.write_table(out_table)
            total_written += out_table.num_rows

            if (i % log_every) == 0:
                print(f"  [{i:>6}/{len(tickers):,}] {tk}  written={total_written:,}  elapsed={time.time()-t0:,.1f}s")

            del table, out_table
            gc.collect()

    finally:
        if writer is not None:
            writer.close()

    # atomic replace
    if os.path.exists(output_path):
        os.remove(output_path)
    os.replace(tmp_out, output_path)

    print(f"✅ SORT DONE: {total_written:,} rows → {output_path} | time={time.time()-t0:,.1f}s")
    return output_path


def recompute_tp_deviation_devsig(
    input_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma.parquet",
    output_path: str = "CRACEN/work/premarket_rows_with_bench_pct_with_sigma_v2.parquet",
    chunksize: int = 2_000_000,   # використовується як batch_rows для Parquet
    round_tp_dev: Optional[int] = 2,
    round_devsig: Optional[int] = 6,
    compression: str = "snappy",
    *,
    sort_final_by_ticker: bool = True,      # NEW: rewrite final sorted
) -> str:
    """
    Parquet-версія.
    Перерахунок:
      - t_p       = stack% * beta
      - deviation = t_p - bench%
      - dev_sig   = deviation / sigma  (0 -> NaN)
    Стирає старі t_p / deviation / dev_sig, якщо були.
    Працює потоково.

    NEW:
      - якщо sort_final_by_ticker=True, то фінальний output_path буде фізично
        відсортований: ticker A→Z, всередині тикера date,dt (або dt).
    """
    if pq is None or pa is None:
        raise RuntimeError("Потрібен pyarrow (pyarrow, pyarrow.parquet).")

    if not os.path.exists(input_path):
        raise FileNotFoundError(input_path)

    t0 = time.time()
    batch_rows = chunksize

    # 1) write unsorted tmp parquet
    tmp_unsorted = output_path + f".tmp_unsorted_{os.getpid()}_{int(time.time())}"
    if os.path.exists(tmp_unsorted):
        os.remove(tmp_unsorted)

    pf = pq.ParquetFile(input_path)
    writer = None
    total = 0

    print(f"▶ START (Parquet): {input_path}  →  {output_path} | batch_rows≈{batch_rows:,}")

    for bi, batch in enumerate(pf.iter_batches(batch_size=batch_rows), 1):
        df = batch.to_pandas()

        # гнучке визначення колонок
        names = {c.lower().strip(): c for c in df.columns}
        stack_col = names.get("stack%") or names.get("pct_vs_prev_close")
        bench_col = names.get("bench%")
        beta_col  = names.get("beta")
        sigma_col = names.get("sigma")

        need = {
            "stack%/pct_vs_prev_close": stack_col,
            "bench%": bench_col,
            "beta": beta_col,
            "sigma": sigma_col,
        }
        missing = [k for k, v in need.items() if v is None]
        if missing:
            raise KeyError(f"У вхідному файлі бракує колонок: {missing}")

        # приберемо старі результати, якщо були
        for col in ("t_p", "deviation", "dev_sig"):
            if col in df.columns:
                del df[col]

        # числові типи
        df[stack_col] = pd.to_numeric(df[stack_col], errors="coerce")
        df[bench_col] = pd.to_numeric(df[bench_col], errors="coerce")
        df[beta_col]  = pd.to_numeric(df[beta_col],  errors="coerce")
        df[sigma_col] = pd.to_numeric(df[sigma_col], errors="coerce")

        # обчислення
        tp  = df[stack_col] * df[beta_col]
        dev = tp - df[bench_col]
        denom = df[sigma_col].replace({0: np.nan})
        dsg = dev / denom

        # округлення
        if round_tp_dev is not None:
            tp  = tp.round(round_tp_dev)
            dev = dev.round(round_tp_dev)
        if round_devsig is not None:
            dsg = dsg.round(round_devsig)

        # додати в кінець
        df["t_p"] = tp
        df["deviation"] = dev
        df["dev_sig"] = dsg

        table = pa.Table.from_pandas(df, preserve_index=False)
        if writer is None:
            writer = pq.ParquetWriter(tmp_unsorted, table.schema, compression=compression)
        writer.write_table(table)

        total += len(df)
        if bi % 5 == 0:
            print(f"[batch {bi:>4}] rows={total:,}  elapsed={time.time()-t0:,.1f}s")

        del df, batch, table
        gc.collect()

    if writer is not None:
        writer.close()

    # 2) sort & finalize
    if sort_final_by_ticker:
        # rewrite sorted to output_path
        _write_final_sorted_alphabetical(
            tmp_unsorted,
            output_path,
            compression=compression,
            roundtrip_pandas=True,
            log_every=200,
        )
        # cleanup unsorted tmp
        try:
            os.remove(tmp_unsorted)
        except Exception:
            pass
    else:
        # atomic replace unsorted as final
        if os.path.exists(output_path):
            os.remove(output_path)
        os.replace(tmp_unsorted, output_path)

    print(f"✅ DONE: {total:,} rows → {output_path} | total_time={time.time()-t0:,.1f}s")
    return output_path

In [51]:
recompute_tp_deviation_devsig(
    input_path=str(WORK_DIR / "premarket_rows_with_bench_pct_with_sigma.parquet"),
    output_path=str(FINAL_PATH),
    chunksize=2_000_000,
    round_tp_dev=2,
    round_devsig=6,
)

▶ START (Parquet): C:\datum-api-examples-main\OriON\CRACEN\work\premarket_rows_with_bench_pct_with_sigma.parquet  →  C:\datum-api-examples-main\OriON\CRACEN\final.parquet | batch_rows≈2,000,000

[batch    5] rows=10,000,000  elapsed=6.1s

[batch   10] rows=20,000,000  elapsed=12.3s

[batch   15] rows=30,000,000  elapsed=18.5s

[batch   20] rows=40,000,000  elapsed=24.7s

[batch   25] rows=50,000,000  elapsed=30.9s

[batch   30] rows=60,000,000  elapsed=37.0s

[batch   35] rows=70,000,000  elapsed=43.1s

[batch   40] rows=80,000,000  elapsed=49.2s

[batch   45] rows=90,000,000  elapsed=55.3s

[batch   50] rows=100,000,000  elapsed=61.5s

[batch   55] rows=110,000,000  elapsed=67.6s

▶ SORT: C:\datum-api-examples-main\OriON\CRACEN\final.parquet.tmp_unsorted_10440_1774073215 → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | tickers=7,115 | has_date=True has_dt=True

  [   200/7,115] AIPO  written=3,200,289  elapsed=47.3s

  [   400/7,115] APPF  written=6,490,769  elapsed=97.0s

  [   600/7,115] AVY  written=9,825,989  elapsed=143.0s

  [   800/7,115] BIL  written=12,591,266  elapsed=193.8s

  [  1000/7,115] BTCI  written=15,845,514  elapsed=244.2s

  [  1200/7,115] CELU  written=18,843,248  elapsed=295.1s

  [  1400/7,115] CNXC  written=21,762,161  elapsed=343.7s

  [  1600/7,115] CV  written=25,129,416  elapsed=394.6s

  [  1800/7,115] DLTH  written=28,083,100  elapsed=445.2s

  [  2000/7,115] ELBM  written=31,045,200  elapsed=494.0s

  [  2200/7,115] EWT  written=34,149,879  elapsed=543.9s

  [  2400/7,115] FLY  written=37,224,799  elapsed=593.2s

  [  2600/7,115] GEN  written=40,135,654  elapsed=643.4s

  [  2800/7,115] GTE  written=43,217,782  elapsed=691.4s

  [  3000/7,115] HTZ  written=46,195,684  elapsed=741.4s

  [  3200/7,115] INDA  written=49,023,041  elapsed=792.6s

  [  3400/7,115] JACK  written=52,276,332  elapsed=847.7s

  [  3600/7,115] KRBN  written=55,174,909  elapsed=901.2s

  [  3800/7,115] LPRO  written=58,072,215  elapsed=954.2s

  [  4000/7,115] MGRX  written=61,037,333  elapsed=1,006.7s

  [  4200/7,115] MTZ  written=64,099,393  elapsed=1,057.6s

  [  4400/7,115] NP  written=67,244,689  elapsed=1,107.7s

  [  4600/7,115] OMSE  written=70,554,383  elapsed=1,163.0s

  [  4800/7,115] PEP  written=73,941,282  elapsed=1,217.5s

  [  5000/7,115] PSIX  written=76,938,176  elapsed=1,270.0s

  [  5200/7,115] REAX  written=80,160,636  elapsed=1,322.4s

  [  5400/7,115] RZLV  written=83,504,291  elapsed=1,373.6s

  [  5600/7,115] SIGA  written=86,833,828  elapsed=1,424.3s

  [  5800/7,115] SPCY  written=90,230,145  elapsed=1,474.9s

  [  6000/7,115] SYK  written=93,582,686  elapsed=1,526.0s

  [  6200/7,115] TOPT  written=96,691,761  elapsed=1,577.3s

  [  6400/7,115] UHG  written=100,154,829  elapsed=1,628.0s

  [  6600/7,115] VIVS  written=103,609,255  elapsed=1,676.8s

  [  6800/7,115] WHR  written=106,797,233  elapsed=1,723.1s

  [  7000/7,115] XWEL  written=109,549,443  elapsed=1,764.4s

✅ SORT DONE: 111,034,041 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | time=1,785.6s

✅ DONE: 111,034,041 rows → C:\datum-api-examples-main\OriON\CRACEN\final.parquet | total_time=1,860.4s

'C:\\datum-api-examples-main\\OriON\\CRACEN\\final.parquet'